### ISSUE TITLE
Use distroless images for Istio proxy

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#37952]
**Request description:**
The upstream distroless istio-proxyv2 container be mirrored and used throughout charts

**Actual behavior:**
Currently the ubuntu-based upstream image is used, containing apt and distro-related tooling

**Expected behavior:**
Only required binaries/libraries etc. are available in the container image to improve security

SURE-3494
SURE-4606

**Comment by SheilaghM** [comment]
@samkulkarni20 - at this point all we need is an LOE/Tshirt size, we don't have to commit to this. Your team has been keeping us up to date on the Istio releases so this isn't as urgent as was thought.

**Comment by samkulkarni20** [comment]
@SheilaghM Done.

**Comment by doflamingo721** [comment]
**Steps to Validate**:
Create 2 downstream clusters, first k8s 1.24 cluster and the second k8s 1.23.

-  Fresh install checks with istio `100.4.0+up1.14.1` on downstream k8s 1.24 cluster. 

-  Upgrade checks from istio 1.13 --> istio 1.14 on k8s 1.23 cluster (istio 1.13 does not support k8s 1.24).

**Comment by doflamingo721** [comment]
**Steps to Validate**:
Create 2 downstream clusters, first k8s 1.24 cluster and the second k8s 1.23.

-  Fresh install checks with istio `100.4.0+up1.14.1` on downstream k8s 1.24 cluster. 

-  Upgrade checks from istio 1.13 --> istio 1.14 on k8s 1.23 cluster (istio 1.13 does not support k8s 1.24).

**Comment by rishabhmsra** [comment]
**Validated on rancher v2.6-head(https://github.com/rancher/rancher/commit/13482caab5fb28b9445494d95f865eeb5d39c44e)**

**Created a downstream k8s v1.24.2-rancher1-1 cluster with 2 worker, 1 etcd, 1 cp nodes.**

Tested below scenarios with istio 100.4.0+up1.14.1. All checks look good.

- Fresh install checks
- Upgrade istio from 100.3.0+up1.13.3 —> 100.4.0+up1.14.1 (after upgrade deployed book app and validated traffic and traces through kiali and jaeger)
- Upgrade with custom overlay
- Kiali
- Jaeger traces
- Reinstall with Kiali and Jaeger enabled
- Fresh install with modified ingress gateway
- Unistall/reinstall checks
- Istio pointing to externally-installed Prometheus
- Multiple ingress
- Egressgateway
- Also provisioned k8s v1.23.8-rancher1-1 cluster(1cp, 1e, 2w) and validated the upgrade checks from 100.3.0+up1.13.3 —> 100.4.0+up1.14.1(after upgrade deployed book app and validated traffic and traces through kiali and jaeger). All checks look good.

**Istio components with distroless images:**

![distroless1](https://user-images.githubusercontent.com/36376154/178271084-57f316f9-6f73-4d58-b275-fc23e03f2fea.png)

**Result:**
- Istio 100.4.0+up1.14.1, Kiali and Jaeger are working as expected, hence closing the issue.
