### ISSUE TITLE
Creating an AKS cluster with a duplicate name as an Azure cluster throws error

### ISSUE THREAD

**Issue by annablender** [rancher/rancher#37955]
**Rancher Server Setup**
- Rancher version: v2.6-head (dev rainbow cluster)
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: 1.23.5
- Cluster Type (Local/Downstream): Downstream AKS cluster provisioned via the Rancher UI
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) admin
  - If custom, define the set of permissions:

**Describe the bug**

When you try to provision an AKS cluster with the same name and resource group as one that already exists in Azure, an error appears in the rancher UI because the [CreateOrUpdate call to AKS](https://github.com/rancher/aks-operator/blob/a32c2bf0c3254301d1257345d4db786fef49162e/pkg/aks/create.go#L186) fails. Rancher is trying to overwrite the DNS prefix for the cluster in Azure with the prefix provided in the UI. Azure does not allow this.

![image](https://user-images.githubusercontent.com/12955547/172928178-de525984-e215-4a7f-91a1-7b36006d695c.png)

**To Reproduce**
 

* Create an AKS cluster via Azure portal with [name] and [resource group]
* Create an AKS cluster via the Rancher UI with [name] and [resource group]

**Result**

Azure error about DNS prefix.

**Expected Result**

Users should not be able to do this in the first place, instead of being able to create a duplicate cluster and call the AKS call fail. If a cluster already exists, they need to import it. The AKS operator should be updated to return an err saying that a duplicate cluster already exists in Azure and to please import it.

**Comment by Josh-Diamond** [comment]
Ticket #37955 - Test Results [pt. 1]

With Docker on a single-node instance:

Reproduced on rancher `v2.6.5`:
1. Create an AKS cluster in azure portal 
2. Fresh install of rancher `v2.6.5`
3. Provision an AKS cluster in Rancher UI w/ same cluster name + resource group as cluster created in step 1
4. Reproduced - issue reproduced w/ `servicePrinciple` field

Screenshot:
<img width="1519" alt="Screen Shot 2022-06-16 at 2 27 10 PM" src="https://user-images.githubusercontent.com/46494969/174169405-458652fa-9b56-4f1f-be85-718126ac3194.png">

**Comment by annablender** [comment]
Verified on rancher v2.6-head with kubernetes 1.23.8. PR submitted with a fix

**Comment by annablender** [comment]
## Testing template

#### Root cause

There was no check for an existing cluster in the aks operator `createCluster` function.
 
#### What was fixed, or what changes have occurred

* Added check for existing cluster in the `createCluster` func https://github.com/rancher/aks-operator/blob/8a968ec94ab7833dcb70890c8268c215bf58a43d/controller/aks-cluster-config-handler.go#L241
* Updated [exists.go](https://github.com/rancher/aks-operator/blob/master/pkg/aks/exists.go) logic

#### Areas or cases that should be tested

1. Create an AKS cluster in Azure Portal with [name] and [resource group]
2. Create an AKS cluster in the rancher UI with [name] and [resource group]. Verify the following error thrown:

![image](https://user-images.githubusercontent.com/12955547/188961779-7503cdfa-c439-4704-a365-b83370d58588.png)

3. Create an AKS cluster in the rancher UI with [name] and [resource group 2]. Verify cluster provisions successfully
4. Create an AKS cluster in the rancher UI with [name2] and [resource group]. Verify cluster provisions successfully

#### What areas could experience regressions ?

None/test cases cover it
 
#### Are the repro steps accurate/minimal ?

Yes.

**Comment by Josh-Diamond** [comment]
Not yet started - BLOCKED by: [#38845](https://github.com/rancher/rancher/issues/38845)
---

Ticket #37955 - Test Results

With Docker on a single-node instance:

Verified on rancher ``:

Scenario 1 - `Create AKS cluster in Azure portal; Create AKS in RancherUI w/ same cluster_name and resource_group`

Scenario 2 - `Create AKS cluster in RancherUI w/ same cluster name as Scenario 1 but w/ new resource group`

Scenario 3 - `Create AKS cluster in RancherUI w/ new cluster name but same resource group as Scenario 1`

**Comment by annablender** [comment]
This was merged prior to 2.7 branching. This does not need to be forward ported as `rancher/release-2.7` is already using aks-operator [v1.0.7-rc1](https://github.com/rancher/rancher/blob/d34a1343e9a13a97f4cbdb753d2e21705923a468/go.mod#L105).
