### ISSUE TITLE
upgrade cluster c-jpzdw system service alerting failed: template system-library-rancher-monitoring incompatible with rancher version or cluster's [c-jpzdw] kubernetes version, requeuing

### ISSUE THREAD

**Issue by YouthInThinking** [rancher/rancher#37963]
![Snipaste_2022-06-10_15-51-52](https://user-images.githubusercontent.com/38899870/173017982-24290f63-2f6a-420c-836d-5e2b88d58f37.png)

K8S env:   GKE  
Rancher Method:  Helm HA
Rancher Versions: V2.6.5
Rancher Downstream Cluster Register  Method:  Google GKE

Rancher system logs show a large number of errors

**Comment by papanito** [comment]
I assume that is the same: https://github.com/rancher/rancher/issues/37039
