### ISSUE TITLE
Can not add a github user to an environment

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#3796]
Rancher Version:
v0.61.0-rc3

Docker Version:
[N/A]
OS: 
[N/A]
Steps to Reproduce: 
Launch rancher/server:v0.61.0-rc3
Enable github auth. (Sometimes this fails for the user the first time. Needs to be run twice)
Go to manage environments
Edit an environment
Add a github user (not org)

Results: 
Identities API calls and returns. 
No new member shows up in the UI.
Clicking save does not show the new identity being passed to the API.
User is *NOT* added.

Expected:
User is added.

**Comment by tfiduccia** [comment]
Verified this is a bug in master.  This did not exist in previous release.

**Comment by tfiduccia** [comment]
Version - master 3/7
Verified fixed
