### ISSUE TITLE
Various Helm Chart Issues in Rancher v2.6.5 (was working fine in 2.5.14)

### ISSUE THREAD

**Issue by jloisel** [rancher/rancher#37974]
**Rancher Server Setup**
- Rancher version: v2.6.5
- Installation option (Docker install/Helm Chart): Docker Install
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details: 

**Information about the Cluster**
- Kubernetes version: v1.20.15
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

Custom

**User Information**
- What is the role of the user logged in? Admin/Cluster
  - If custom, define the set of permissions:

   
**Describe the bug**

Several problems seen when installing helm charts on Rancher v2.6.5:
1. values.yml must contain all the default values, otherwise the helm chart won't install (tried with cert-manager),
2. When installing helm chart through command line with `helm install`, `values.yml` works as expected (I only put the relevant / modified info in it), but for datadog helm chart the upgrades are not detected:
https://github.com/DataDog/helm-charts/tree/main/charts/datadog

3. Installing cert-manager through their helm chart, everything works fine through `helm` (including detecting upgrades). 

**To Reproduce**

- Try to install helm chart via Rancher UI, when asked for `values.yml`  content, remove everything, the helm chart cannot be installed because it complains of missing default values (which should be provided by the default values.yml in the helm chart). This is annoying because it's extremely difficult / impractical to maintain a values.yml with all the default values in it,
- Try to install datadog helm chart, upgrades are not detected.

Datadog is installed but not up-to-date:
![image](https://user-images.githubusercontent.com/3208716/173354664-4f0b9fbe-8780-43f5-b1b6-ba410ce27f3b.png)

I need to uninstall / reinstall the chart everytime an upgrade is available.

**Comment by ajacques** [comment]
Related: #35717

There are a number of issues with the Rancher Helm experience.

**Comment by jloisel** [comment]
Thx for the update! We'll use the helm cli for now as a workaround until it's fixed.

**Comment by jloisel** [comment]
Still active.

**Comment by mklenk** [comment]
Still relevant

**Comment by erSitzt** [comment]
still relevant
