### ISSUE TITLE
is cert-manager still optional?

### ISSUE THREAD

**Issue by harridu** [rancher/rancher#37973]
According to the documentation (https://rancher.com/docs/rancher/v2.6/en/installation/install-rancher-on-k8s/) cert-manager is optional, but on several occasions I heard that cert-manager is a requirement for Rancher version 2.6.5, e.g. on slack.

Can you confirm that cert-manager is still optional for using an external PKI like letsencrypt?

**Comment by harridu** [comment]
please keep this open

**Comment by harridu** [comment]
please keep this open

**Comment by bashofmann** [comment]
Yes, cert-manager is optional. You can also provide a TLS certificate as a secret to Rancher: https://ranchermanager.docs.rancher.com/pages-for-subheaders/install-upgrade-on-a-kubernetes-cluster#3-choose-your-ssl-configuration

**Comment by harridu** [comment]
thank you for the clarification
