### ISSUE TITLE
manage Rancher cluster using Rancher

### ISSUE THREAD

**Issue by harridu** [rancher/rancher#37972]
Can you imagine that people would love to use Rancher for managing its own cluster? There might be technical problems making this impossible (I don't know), but the documentation should be much more clear in this respect. For example, https://rancher.com/docs/rancher/v2.6/en/cluster-admin/certificate-rotation/ describes certificate rotation and mentions something about RKE and RKE2, but then it describes certificate rotation only for the clusters launched in Rancher. No word about the cluster **running** Rancher. 

Rancher pretends to manage its own cluster, but apparently there are restrictions. That should be improved.

**Comment by ajacques** [comment]
I'd still like to see this. It's inconvenient not being able to use Rancher to upgrade my cluster because I don't have multiple clusters. I lost this ability when I had to move away from single-node Docker installation.

**Comment by harridu** [comment]
I understand that there is some kind of catch22 here. 

IMHO Rancher is too much about rke or rke2 or k3s right from the start. Being new to Kubernetes I had a very hard time to understand how to setup a cluster to host Rancher. Why did I have to struggle with this? Installing clusters was exactly the part I had hoped to do with Rancher. Highly confusing. Of course I know better now. Today I wouldn't use an rke cluster to run Rancher.

**Comment by ajacques** [comment]
This feature would still be useful.
