### ISSUE TITLE
Cannot find the apps.catalog.cattle.io object for a chart after upgrading from rancher v2.5.10 to rancher v2.6.4

### ISSUE THREAD

**Issue by PhanLe1010** [rancher/rancher#37978]
**Rancher Server Setup**
- Rancher version: v2.6.4
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): Docker
- Proxy/Cert Details: Default Rancher-generated Self-signed Certificate 

**Information about the Cluster**
- Kubernetes version: v1.20.11
- Cluster Type (Local/Downstream): Downstream 
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):
     * Infrastructure Provider = Rancher provisioning the nodes using different node drivers Digital Ocean, RKE1

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): Admin

   
**Describe the bug**
Cannot find the apps.catalog.cattle.io object for a chart after upgrading from rancher v2.5.10 to rancher v2.6.4.

**To Reproduce**

1. Deploy v2.5.10 rancher
2. Create a downstream cluster and install Longhorn in the old rancher catalog UI
    <img width="959" alt="Screen Shot 2022-06-07 at 4 16 01 PM" src="https://user-images.githubusercontent.com/22139961/173427822-bb9301de-60ca-43ec-a177-53367ccb9fcb.png">
    We can see the [apps.catalog.cattle.io](http://apps.catalog.cattle.io/) object:
    ```
    ➜  ~/.kube kubectl get  apps.catalog.cattle.io  longhorn-system -n longhorn-system        
    NAME              CHART      VERSION   RELEASE NAME      RELEASE VERSION   STATUS
    longhorn-system   longhorn   1.2.2     longhorn-system   1                 deployed
    ```
4. Upgrade rancher to >= v2.6.4.  We can see the Longhorn chart in the legacy section:
    <img width="948" alt="Screen Shot 2022-06-07 at 4 34 28 PM" src="https://user-images.githubusercontent.com/22139961/173428166-6c4bfef3-c790-48be-8f35-01bea0927061.png">
    However, we can not see the [apps.catalog.cattle.io](http://apps.catalog.cattle.io/) object any more:
    ```
    ➜  ~/.kube kubectl get  apps.catalog.cattle.io -n longhorn-system 
    No resources found in longhorn-system namespace.
    ```
**Result**
we can not see the [apps.catalog.cattle.io](http://apps.catalog.cattle.io/) object any more

**Expected Result**
we should see the [apps.catalog.cattle.io](http://apps.catalog.cattle.io/) objects so that we can do the migration steps at  https://confluence.suse.com/display/EN/Migrating+legacy+apps+to+dashboard+apps

**Comment by rmweir** [comment]
The part about being able to see the app is incorrect. That was done on purpose in the UI. This is because interacting with the apps.catalog.cattle.io object could cause bugs (unless a manual migration process is done). However, the app should still exist in k8s. It looks like it's getting deleted which is the bug here.
