### ISSUE TITLE
Azure AD fails when configured with custom end points

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#37988]
Information about the Cluster
**Rancher Server Setup**
- Rancher version: `v2.6-head c8d01c6 `
- Installation option (Docker install/Helm Chart): `Helm Chart`
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): `RKE1`, `v1.23.6 `, `1.3.10`
- Proxy/Cert Details: `Self-signed`

**Information about the Cluster**
- Kubernetes version: `v1.23.6 `
- Cluster Type (Local/Downstream): `Custom  3 worker, 1 etcd, 1 cp RKE1`

**Describe the bug**

**To Reproduce**
1. On rancher v2.6-head, enabled Azure AD auth from Users & Auth >> Auth providers >> Azure AD
2. While configuring the auth, select the option custom end points under the section endpoints.
3. Provide the endpoints - Graph Endpoint, Token Endpoint and Auth Endpoint by providing the old graph endpoint values:
```
Graph end point:  https://graph.windows.net
Auth end point: https://login.microsoftonline.com/{tenantID}/oauth2/authorize
Token end point: https://login.microsoftonline.com/{tenantID}/oauth2/token
```
4. Provide the required tenant ID, Client ID and Secret
5. Save the config
6. Add the permissions: Microsoft Graph: need Group.Read.All, User.Read.All in the test app from Azure Portal

**Result**
Enabling auth fails with the error:
`server error while authenticating: missing required permissions from Microsoft Graph: need Group.Read.All, User.Read.All`

**Expected Result**
Expected the auth enabled.

**Comment by anupama2501** [comment]
Closing this issue as this seems to happens because of a missing slash at the end of graph endpoint:
Graph end point:  https://graph.windows.net should be  `https://graph.windows.net/`

After adding the slash, enabling auth works fine.

**Comment by anupama2501** [comment]
V2.6-head 2b1e3ee

re opening as the issue is seen after the new fixes, azure ad cannot be enabled with the old graph end points provided as custom end points. Same error as mentioned in the original comment is seen. 

App in azure portal has the required permissions
`server error while authenticating: missing required permissions from Microsoft Graph: need Group.Read.All, User.Read.All`

```
Graph end point:  https://graph.windows.net/
Auth end point: https://login.microsoftonline.com/{tenantID}/oauth2/authorize
Token end point: https://login.microsoftonline.com/{tenantID}/oauth2/token
```

**Comment by maxsokolovsky** [comment]
I don't believe this is a valid scenario because on v2.6.7+, Rancher will use the new auth flow, and the SDKs too, which rely on new graph endpoints. I looked at this, and the SDK code tries to create a URL (when making a request to the Graph) that is a mix of the old endpoint and parts designed to work with the new endpoint.
We should instead test with a real custom endpoint, but that's challenging, because we'd need a test tenant for Azure US Government, for example.
Regardless, this particular scenario should not work at all. Rancher should outright not allow old endpoints masqueraded as custom on new setups, but we are not strict with this.

**Comment by samjustus** [comment]
@anupama2501 can we close this?

**Comment by anupama2501** [comment]
As we do not have a test tenant to verify custom end points currently, moving this to v2.6.8.
