### ISSUE TITLE
ERR_ADDRESS_UNREACHABLE

### ISSUE THREAD

**Issue by wanaoishi** [rancher/rancher#3799]
Rancher Version: v0.59.0-rc1

Docker Version: 1.9.1, build a34a1d5

OS: CentOS Linux release 7.2.1511

Steps to Reproduce: Unknown
Nothing was done between the two states.

Results: ERR_ADDRESS_UNREACHABLE
I don't know why but yesterday Rancher server was working perfectly.
And this morning I am facing an "ERR_ADDRESS_UNREACHABLE". 
Tried docker restart, no changes.
Tried docker stop & start, same.

Any idea how I can debug that.

**Comment by deniseschannon** [comment]
Is there a reason why you are on v0.59.0-rc1? Our rc releases are release candidates and we hope that most users will use the actual released versions.

Where are you facing this problem? UI? Seeing in the logs?

Can you provide some of the last 200 lines of your rancher server logs?

**Comment by deniseschannon** [comment]
If you could use a non rc candidate and reproduce, please re-open.

**Comment by wanaoishi** [comment]
Fixed by intsalling the last version.
