### ISSUE TITLE
RHEL 8.6 is unable to successfully provision a downstream RKE2 cluster, custom or node driver

### ISSUE THREAD

**Issue by markusewalker** [rancher/rancher#37997]
**Rancher Server Setup**
- Rancher version: `v2.6-head`
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: `v1.23.6+rke2r2`
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Custom

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Standard
  - If custom, define the set of permissions:

   
**Describe the bug**

When attempting to register a RHEL 8.6 node to have a downstream custom RKE2 cluster in Rancher, I am seeing the following behavior:

![image](https://user-images.githubusercontent.com/52591819/173706343-c6b9804a-f2e7-40bc-a1b2-cb5cc37dda01.png)

Additionally, this is not just an issue with custom clusters, when using a RHEL 8.6 AMI (private and public) to create a downstream node driver cluster, I am still seeing the above issue. Switching the CNIs does not help at all, still same hang.

I did verify that RKE1 DOES NOT have this issue; custom and node driver provisioning works as expected. Additionally, I used a RHEL 8.4 private AMI with the same configuration and both RKE1/RKE2 provisioning works as expected.

Looking deeper into it, I tried to install/configure a server node installation by itself, but `systemctl start rke2-server.service` consistently and looking at `journalctl -xe`, I see the following:

```
# journalctl -xe
-- 
-- Unit nm-cloud-setup.service has begun starting up.
Jun 14 23:20:30 ip-172-31-30-154.us-east-2.compute.internal systemd[1]: Starting Rancher Kubernetes Engine v2 (server)...
-- Subject: Unit rke2-server.service has begun start-up
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- Unit rke2-server.service has begun starting up.
Jun 14 23:20:30 ip-172-31-30-154.us-east-2.compute.internal sh[14457]: + /usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service
Jun 14 23:20:30 ip-172-31-30-154.us-east-2.compute.internal systemd[1]: rke2-server.service: Control process exited, code=exited status>
Jun 14 23:20:30 ip-172-31-30-154.us-east-2.compute.internal systemd[1]: rke2-server.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- The unit rke2-server.service has entered the 'failed' state with result 'exit-code'.
Jun 14 23:20:30 ip-172-31-30-154.us-east-2.compute.internal systemd[1]: Failed to start Rancher Kubernetes Engine v2 (server).
-- Subject: Unit rke2-server.service has failed
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- Unit rke2-server.service has failed.
-- 
-- The result is failed.
Jun 14 23:20:30 ip-172-31-30-154.us-east-2.compute.internal systemd[1]: nm-cloud-setup.service: Succeeded.
-- Subject: Unit succeeded
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- The unit nm-cloud-setup.service has successfully entered the 'dead' state.
Jun 14 23:20:30 ip-172-31-30-154.us-east-2.compute.internal systemd[1]: Started Automatically configure NetworkManager in cloud.
-- Subject: Unit nm-cloud-setup.service has finished start-up
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- Unit nm-cloud-setup.service has finished starting up.
-- 
-- The start-up result is done.
```

**To Reproduce**
 
1. Setup Rancher and navigate to the UI in a browser.
2. Create a standard user and login to Rancher as that user.
3. Provision a downstream custom cluster and register a RHEL 8.6 AMI; it should hang when attempting to configure the bootstrap node.

**Result**
RKE2 provisioning hangs when configuring the bootstrap node, causing RHEL 8.6 unable to use RKE2.

**Expected Result**

RHEL 8.6 should be able to successfully provision an RKE2 cluster.

**Comment by markusewalker** [comment]
For additional information, I am seeing this behavior with multiple public AMIs that I tested. With a private AMI that I created that has  the  `rancher-selinux` package installed, I still see this problem. Interestingly, with that same mentioned private AMI, that is where I see RKE1 provisioning successful as well.

**Comment by snasovich** [comment]
Blocked by https://github.com/rancher/rke2/issues/3112. Clearing `release-blocker` label as I don't believe there is a hard requirement to support RHEL 8.6 for RKE2 provisioning.

**Comment by coutureb** [comment]
unsubscribe

**Comment by rancher-max** [comment]
I believe that the private ami being used needs to also follow https://docs.rke2.io/known_issues/#networkmanager. I tried it out and these two services still need to be disabled for rke2 to install properly.

**Comment by markusewalker** [comment]
@rancher-max maybe we can chat offline next week regarding this. I am still seeing issues when attempting to provision with your recommendations. When you looked into this, were you able to get RKE2 provisioned on RHEL 8.6 and if so, was it with a public or private AMI?

**Comment by markusewalker** [comment]
I believe my issues I faced were related to the following issue: https://github.com/rancher/rancher/issues/38190. Once this is resolved, I will try again and provide further feedback.
