### ISSUE TITLE
EC2 Machine: Deleting machines that are stuck in "creating" state does not remove the VMs

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#380]
Version - V0.14.1

In my case , machine creation was stuck in "creating" state because of the issue encountered in #374.
Try to delete this host from Rancher UI.
It gets deleted in the Rancher UI.
But the instance that was created in Amazon EC2 was never deleted.

**Comment by deniseschannon** [comment]
Steps to Reproduce:

Pick a security group that doesn't have port `22` open when creating host.

**Comment by will-chan** [comment]
I'm not sure you can reproduce this anymore but should at least check.

**Comment by deniseschannon** [comment]
@will-chan I just reproduced yesterday and gave steps to reproduce. @wlan0 if you need help reproducing, let me know.

**Comment by will-chan** [comment]
This is something docker-machine cannot do right now simply because it could not SSH into the machine to complete the provisioning process.  I think we can add something in the UI to indicate that if you are going to use your own security group, please make sure the required docker-machine ports need to be opened.

**Comment by vincent99** [comment]
@will-chan I get that it can't complete provisioning if 22 isn't open, but why can't it delete the VM when the machine/host resource is removed?  Machine doesn't need SSH for that, it's just sending a delete to the driver API with the credentials that must work if the VM was created in the first place.

**Comment by vincent99** [comment]
The UI currently says to make sure 22 is open if you choose custom security group.  And I'm pretty sure Machine automatically opens it if it isn't whether you ask it to or not.  So I'm not actually sure how 22 could not be open in the first place.

![image](https://cloud.githubusercontent.com/assets/753917/8047685/54ac904a-0dfd-11e5-8c09-de43503e7beb.png)

**Comment by deniseschannon** [comment]
We need to put in something that says that port 22 needs to be open prior to the actual creation of the machine. As a user, I feel like I could just use a security group and then update my traffic after the creation to get it to work.

**Comment by ekristen** [comment]
I can't get the rancher to provision any ec2 instance. It just gets stuck in creating mode. The ec2 instance gets created. The AMI has docker on it. The SSH keys get added properly, but never provisions/bootstraps/etc ...

```
Rancher 	v0.24.0
Cattle 	v0.56.0
User Interface 	v0.28.0
Rancher Compose 	latest
Machine Service 	v0.13.0 (docker-machine v0.3.0-dev-packet-rc2)
```

**Comment by deniseschannon** [comment]
Can you provide me a couple more details? What AMI did you use? When you say that the AMI has docker on it, do you know what version of Docker? 

Did you use your own security group or allow rancher to create rancher-machine security group?

**Comment by ekristen** [comment]
Allowed rancher to create a group and it has 1.7.

It appears that docker machine just hangs pegs the processor. If I go to the machine directory and do a docker machine list it appears but not active. Config command fails as it cannot find the carts where docker machine expects them to be.

**Comment by deniseschannon** [comment]
Unfortunately, it sounds more like a docker machine issue instead of a rancher issue. Would you be able to send me the AMI ID? I'd like to test it out and if I can also replicate, we can look into filing an issue with docker machine.

**Comment by ekristen** [comment]
@deniseschannon I found the problem. docker-machine automatically tells the server to get a public IP and then uses that to try and connect, but I am in a VPC and the subnet that my server is going into isn't a public one, so while ec2 grants it and gives it a public ip as well as its internal VPC ip, it cannot access via the public ip and so it just hangs forever.

**Comment by ekristen** [comment]
@deniseschannon it looks like there is `--amazonec2-private-address-only` from the amazonec2 driver, but I see no way in Rancher to set this.

**Comment by ekristen** [comment]
I can also verify that deleting a host that is stuck in creating causing Rancher to not clean anything up on the ec2 side. It does not run `docker-machine rm` when deleting.

**Comment by deniseschannon** [comment]
@ekristen If you wait long enough, the machine will eventually error out and when it's in the error state, then rancher will properly remove the machine on amazon. there is an issue with deleting in the middle of creation. @wlan0 please let me know if this is not correct.

**Comment by ekristen** [comment]
I've waiting 10-15 minutes and it has never error-ed out ...

**Comment by wlan0** [comment]
@deniseschannon @ekristen We are in the middle of implementing a distributed lock on each request. One that is done, and if you try to delete on create, your deletion will happen even if create fails.

**Comment by wlan0** [comment]
@ekristen machine waits and retires upto 60 times for a number of steps (wait for ip to be available, waiting for ssh to be available) etc. It times out eventually. https://github.com/docker/machine/blob/master/utils/utils.go#L117

**Comment by ekristen** [comment]
@wlan0 sounds good, thanks

**Comment by will-chan** [comment]
please re-test

**Comment by sangeethah** [comment]
Tested with latest build from master.

When adding EC2 Machines fail (In my case I add 10 machines in parallel , out of which 2 of them reported error while trying to install dokcer) , hosts are in "Error" state in rancher-server. They are in running state in Amazon EC2 instance dashboard.

Deleting the instance in "Error" state results in the machines being deleted and  Amazon EC2 instance dashboard shows state as "terminated".
