### ISSUE TITLE
[v2.6] Port KDM Update for K8s 2022 May patches from release-v2.6 to dev-v2.6 Branch

### ISSUE THREAD

**Issue by rayandas** [rancher/rancher#38005]
Port KDM Update for K8s 2022 May patches changes from `release-v2.6` to `dev-v2.6` branch.

**Comment by dhruvmewada15** [comment]
Linked PR:
https://github.com/rancher/kontainer-driver-metadata/pull/916

**Comment by rayandas** [comment]
Closing this issue as the PR is now merged.

**Comment by Josh-Diamond** [comment]
Ticket #38005 - Test Results

With HA Helm:

Verified on rancher `v2.6-772b2f0232764ec1f0f9f90d938a69cce647dcdb-head`:
1. Fresh install of rancher `v2.6-head`
2. Downstream k8s versions available:
    - RKE1:
           - `v1.23.7-rancher1-1`
           - `v1.22.10-rancher1-1`
           -  `v1.21.13-rancher1-1`
           -  `v1.20.15-rancher1-4`
           -  `v1.19.16-rancher1-6`
           -  `v1.18.20-rancher1-3`
    - RKE2:
           - `v1.23.7+rke2r2`
           -  `v1.22.10+rke2r2`
           -  `v1.21.13+rke2r2`
    - K3s:
           - `v1.23.7+k3s1`
           -  `v1.22.10+k3s1`
           -  `v1.21.13+k3s1`
