### ISSUE TITLE
Load Balancer 

### ISSUE THREAD

**Issue by robinr888** [rancher/rancher#3800]
unable to find  rancher/load-balancer-service  from repository . However I am able to download docker server agents etc ...Can you please help me to download load balancer image

[root@XXXX ~]# docker pull rancher/load-balancer-service
Using default tag: latest
Pulling repository docker.io/rancher/load-balancer-service
Error: image rancher/load-balancer-service:latest not found

[root@XXXX-a ~]# docker search load-balancer-service
NAME                              DESCRIPTION                                     STARS     OFFICIAL   AUTOMATED
lmancilla/load-balancer-service   custom agent instance                           0
meltwater/proxymatic              Dynamic service discovery TCP/UDP proxy an...   0                    [OK]
qnib/es-lb                        Nginx loadbalancer over all passing elasti...   0                    [OK]
gambol99/embassy                  Docker Service Proxy / Loadbalancer             0                    [OK]
stackhub/nginx-lb                 Dynamic service using Nginx as a load bala...   0                    [OK]
inercia/docker-nginx-dns          Dynamic reverse proxy/load balancer for mi...   0                    [OK]
paulczar/lolbalancer              A very small IPVS load balancer that uses ...   0                    [OK]
jfautley/ssws                     Super Simple Web Service, using Python. De...   0                    [OK]
texthtml/consul-loadbalancer      nginx loadbalancer for consul services          0                    [OK]

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v0.59.1` Cattle: `v0.148.1` UI: `v0.90.0` |
|Access|`Disabled`}|
|Route|`null`|

**Comment by vincent99** [comment]
`rancher/load-balancer-service` is just a placeholder.  The actual image for balancers, the network agent, etc is [rancher/agent-instance](https://github.com/rancher/agent-instance), which is just Ubuntu with a few packages installed.
