### ISSUE TITLE
Rancher 2.6.x: Unauthorized 401: must authenticate on Rancher API (/v3) when using scope

### ISSUE THREAD

**Issue by Napsty** [rancher/rancher#38016]
**Rancher Server Setup**
- Rancher version: 2.6.5
- Installation option (Docker install/Helm Chart): Docker Install
- Proxy/Cert Details: default / self-signed

**Information about the Cluster**
- Kubernetes version: 1.23.6
- Cluster Type (Local/Downstream): local

**User Information**
- What is the role of the user logged in? Admin (issue happens on all user roles)

   
**Describe the bug**
Accessing the Rancher 2 API (`/v3`) **does not work when using API Keys with a scope**. Being logged in to the UI, the API can be seen. 

**To Reproduce**
- Click on user icon top-right corner
- Click on Account and API Keys
- Create API Key, select a specific cluster for scope (e.g. local)
- Use the token and secret to access the API

**Result**
The API returns a 401.

```
$ curl -s -u token-p62nb:chcnszhxp6zqrbxwcz5z2r2w9jrftlvtwvzbsr88v4mk28kw4k5c2p https://rancher.example.com/v3/projects -k
{"type":"error","status":"401","message":"Unauthorized 401: must authenticate"}
```

**Expected Result**
The API should work, even when using a cluster scope for the API key.
Here's the API access with a API Key without scope:

```
$ curl -s -u token-qb4ww:5h4p2znsjlbglkjx2l8vt7sbtnd49qszgh27jx6zgmqcp96dkl787z https://rancher.example.com/v3/projects -k
{"type":"collection","links":{"self":"https://rancher.example.com/v3/projects"},"createTypes ....
```

**Screenshots**
![image](https://user-images.githubusercontent.com/3702203/174004807-cc8b5508-20b1-4022-bd74-63c75c2af83e.png)

**Additional context**
This may also be a limitation by design. But if that's the case, what is the API supposed to do or which requests would actually work with a scope?

**Comment by sebastienroul** [comment]
@Napsty : I had the same error... But

Scope doesn't mean shortcut. Scope only mean, "you can access" and not means "you are in".
So your request must includes the [cluster_id] : https://XXX.XXX.net/v3/clusters/**cluster_id**/namespaces

should maybe close issue : BUT PLEASE @RANCHER_TEAM improve the API doc - only magicians or lucky guys can succed with it.

**Comment by Quantas** [comment]
I am having this exact same issue. On Rancher 2.6.6, proxy/cert is let's encrypt, kubernetes version for local is 1.21.5 and the cluster type for the downstream is RKE1 1.21.5.  The issue happens to all user types when creating a token with any scope.

**Comment by ArsaCode** [comment]
I'm also having this problem with Rancher version 2.6.6 on a fresh install with the bootstrap password when trying to login into the dashboard against the local cluster.

**Comment by esakarya** [comment]
same issue here

**Comment by kensbyn** [comment]
same issue here

**Comment by esakarya** [comment]
While creating api, it gives this error if cluster is selected. Do not select cluster when creating api keys

**Comment by t-chab** [comment]
Same error with Rancher 2.4.7

**Comment by Syntax3rror404** [comment]
I also get this error with RKE2. I just want to generate a api-key with curl.

**Comment by riclava** [comment]
same issue on server v2.6.8 with cli v2.6.7

**Comment by DaddyApi** [comment]
Apparently, you have to select **NO scope**, while generating API keys in rancher

**Comment by nymo** [comment]
Can confirm this issue too on 2.6.5. Looks like have been already fixed in the past see https://github.com/rancher/rancher/issues/18639

**Comment by eecavanna** [comment]
I hit this issue today, using:
- Rancher CLI version: `rancher-windows-386-v2.6.11`
- Rancher version: `v2.6.13`

Using an API key scoped to a cluster, the `login` command gave me:
```Powershell
rancher.exe login "https://...redacted_url..." --token "...redacted_access_key...:...redacted_secret_key..."
time="2023-06-22T18:52:03-07:00" level=fatal msg="Bad response statusCode [401]. Status [401 Unauthorized]. Body: [message=Unauthorized 401: must authenticate] from [https://...redacted_url.../v3]"
```

Using an API key with no scope, the `login` command gave me:
```Powershell
rancher.exe login "https://...redacted_url..." --token "...redacted_access_key...:...redacted_secret_key..."
NUMBER    CLUSTER NAME   PROJECT ID        PROJECT NAME   PROJECT DESCRIPTION
...redacted_project_list...
```

**Comment by LucasVanHaaren** [comment]
I confirm the issue still exist on rancher `v2.7.4`.

Can't create working api token while having a scope (got 401 responses).

**Comment by tbuddhika-dvloper** [comment]
The issue still exists on Rancher: v2.8.0
Can't create a working API token while having a scope.

Returns,
```
{
    "type": "error",
    "status": "401",
    "message": "Unauthorized 401: must authenticate"
}
```

**Comment by bert-jan** [comment]
I confirm the issue still exist on rancher v2.7.7 when using a scope.

**Comment by burigolucas** [comment]
Same issue using rancher v2.8.4 without scope and with local scope.

**Comment by spartan-it** [comment]
> Can someone please open this issue again as it's not resolved? @superseb maybe?

I agree, I don't think adding no scope is a viable workaround when I need added security for my token. In case of the worst scenario, a bad actor could access all my clusters when I only need access to one of them.

**Comment by superseb** [comment]
> Can someone please open this issue again as it's clearly not resolved? @superseb maybe?

Sorry, I am unable to help.

**Comment by mr-awk** [comment]
I can still confirm the bug with 2.7.9 when using scope also.

**Comment by mixxor** [comment]
confirmed in v2.8.5

**Comment by valkiriaaquatica** [comment]
bug stills on 2.9.1 at least with terraform rancher provider, enabling insecure protocol **" Bad response statusCode [401]. Status [401 Unauthorized]"**   while the credentials are correr

**Comment by LaluprasadJaladi** [comment]
Hello 

select `no scope` and generate api_key it will work


![image](https://github.com/user-attachments/assets/448cff1a-d083-44dd-920a-523e612cab6d)
