### ISSUE TITLE
`enable_cri_dockerd: true` causes dockerd to use all CPU resources available.

### ISSUE THREAD

**Issue by Raboo** [rancher/rancher#38018]
**Rancher Server Setup**
- Rancher version: 2.6.5
- Installation option (Docker install/Helm Chart): helm, rke1

**Information about the Cluster**
- Kubernetes version: v1.22.9
- Cluster Type (Local/Downstream): Custom

**Information about underlying OS**
- OS: Flatcar Linux
- Release: Beta Channel / 3227.1.0
- Kernel: 5.15.43
- Docker engine: 20.10.14
- using legacy cgroups (cgroups v1)

**Describe the bug**
I set cluster configuration `rancher_kubernetes_engine_config.enable_cri_dockerd: true` and dockerd started using all available CPU and causing high load, eventually causing the entire cluster to create cascading errors.

Seems related to https://github.com/rancher/rke/issues/2938 and https://github.com/rancher/rke/issues/2709.

**To Reproduce**
Enable `rancher_kubernetes_engine_config.enable_cri_dockerd` on Rancher v2.6.5 or earlier on k8s v1.21, v1.22 or v1.23.

**Result**

**Expected Result**
dockerd should not be using 4800% CPU and causing a system load of over 80 on a 48 core node.

**Additional context**
Perhaps there should be a warning in the documentation about using `enable_cri_dockerd: true` since it's been known for a while that the performance is bad. At least until fixing the root problem since this is a cluster breaking bug.

**Comment by Raboo** [comment]
This will be fixed in Rancher v2.6.7 according to https://github.com/rancher/rke/issues/2938

**Comment by Raboo** [comment]
@cite I have not upgraded and not enabled cri_dockerd.
But more users have confirmed that there is indeed still a problem https://github.com/rancher/rke/issues/2709

**Comment by cite** [comment]
I took a look at https://github.com/Mirantis/cri-dockerd/pull/38 - it seems this only fixes the problem of metrics not being returned fast enough, by delegating stats collection to a goroutine. So the metrics aren't collected any faster or in a more clever way, but just in parallel. Then, when metrics are collected, and you run a lot of pods, it makes sense that `dockerd` would need several 10s of cores.

**Comment by Raboo** [comment]
That sucks.
Well  my situation was that my entire cluster went haywire. High CPU on dockerd and unresponsive kubelet.
So I reverted everything. Currently there are no battle-tested way of migrating a Rancher provisioned RKE1 cluster to a RKE2 which sucks.

**Comment by nickvth** [comment]
With rancher 2.6.8 dockerd is still consuming more CPU than other nodes where cri_dockerd is disabled.

**Comment by phoenix-bjoern** [comment]
This issue is still unresolved. Maybe continue in https://github.com/rancher/rancher/issues/38816, which seems to be a duplicate.

**Comment by Raboo** [comment]
Yes, it seems to be the same issue. Unfortunately this has been a known problem for a very long period without any resolution in sight

**Comment by Raboo** [comment]
Seems that this will be resolved in next release, details: https://github.com/rancher/rancher/issues/38816

**Comment by immanuelfodor** [comment]
Can confirm the CPU issue fixed: upgraded v1.23.16-rancher2-1 -> v1.24.13-rancher2-1 with `enable_cri_dockerd: true` and the CPU usage is normal.
