### ISSUE TITLE
User defined EKS security groups are configured as the only node group security groups, versus being appended to the cluster default security group

### ISSUE THREAD

**Issue by annablender** [rancher/rancher#38014]
**Rancher Server Setup**
- Rancher version: 2.6.5
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version:
- Cluster Type (Local/Downstream): Downstream Cluster EKS v1.21.12-eks-a64ea69
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:

**Describe the bug**

The change introduced to the EKS operator in Rancher v2.6.4 (https://github.com/rancher/eks-operator/commit/c91df2d6f32c8feb5661a45216a37904d6b8efa5) to resolve https://github.com/rancher/rancher/issues/34749 configures the security groups for the node group launch template (in the instance the user does not provide a custom launch template) to the user-defined set, versus appending them to the list of security groups alongside the cluster default security group. The UI describes the optional user-defined security groups as follows "EKS creates a security group for your cluster by default. You may choose additional security groups that will be applied to EKS instances alongside the default security group created by EKS".

Business impact:
Breaks EKS cluster communication where a user defines additional security groups to grant some additional inbound/outbound rules besides the cluster default.

**To Reproduce**
 

Provision a Rancher v2.6.5 instance (I used github.com/superseb/tf-do-rancher2)
Provision an EKS cluster, defining a custom security group for the cluster, and without specifying a custom launch template
Observe that only the custom security group is set on node group instances, which are missing the cluster default security group

**Result**

User-defined security groups are the only security groups for node groups (where user does not define custom launch template)

**Expected Result**

User-defined security groups appended to cluster default security group for node groups (where user does not define custom launch template)

SURE-4790

**Comment by annablender** [comment]
## Testing template

#### Root cause

This issue is a regression when an EKS cluster is provisioned via the rancher UI, the [default security group](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/default-custom-security-groups.html#default-security-group) is not appended to the node group when a launch template is not specified.
 
#### What was fixed, or what changes have occurred

When an EKS cluster is provisioned through rancher, after the cluster is done creating the eks operator adds the default vpc security group generated by AWS here https://github.com/rancher/eks-operator/blob/012d292592a0141b21e9b0cffac1a46360eea5f8/controller/eks-cluster-config-handler.go#L1181, creates a new launch template version for each node group in the cluster, and applies the new launch templates(s). The [config.Status is updated](https://github.com/rancher/eks-operator/blob/012d292592a0141b21e9b0cffac1a46360eea5f8/controller/eks-cluster-config-handler.go#L1185) with the new list of security groups.

My solution here is to create a new launch template version and apply it to the EC2 nodes after the cluster is finished creating. EKS does not generate the default security group until after the cluster finishes creating. Specifically in eks operator, we now add a bool addDefaultSecurityGroup to mark that it needs to be added to the node group, update the config.Status with the vpc default security group included, create a new launch template version and apply it to the nodes.

Functionality notes

The security group update takes some time, so when you provision an EKS cluster with no launch template specified, the update will take an extra 5-10 mins on top of provisioning. I usually see 2 nodes clusters become fully active in Rancher after about 25 mins. That time bump is due to EKS creating a new launch template, deleting the old one, and recycling the nodes in the node group to use the new launch template.

Sometimes, the cloud provider is slow to update the cluster and config.Status.SecurityGroups doesn't get updated until after a few syncs of the operator. This results in 2-3 new launch template versions getting created before the update completes. The old ones are immediately cleaned up by rancher, so @rmweir have agreed this is fine as long as EKS is not getting overloaded with template objects.

#### Areas or cases that should be tested
 
#### What areas could experience regressions ?
 
#### Are the repro steps accurate/minimal ?

**Comment by Josh-Diamond** [comment]
Ticket #38014 - Test Results

With Docker on a single-node instance:

Reproduced on rancher `v2.6.6`:
1. Fresh install of rancher `v2.6.6`
2. Provision a downstream EKS cluster via the rancher UI - [Specify 2 vpc subnets + custom security group; no launch template]
3. Reproduced - EKS Cluster instance shows default + custom sg; Node instances show custom sg only;

Screenshots:

`Cluster Instance`
![cluster_specs](https://user-images.githubusercontent.com/46494969/179561901-58f33b8d-498f-4582-b063-d8d75ea0288e.png)

`Node 1`
![node1](https://user-images.githubusercontent.com/46494969/179562269-2b7d0b4b-20d3-4469-83ef-d33bfef2e52d.png)

`Node 2`
![node2](https://user-images.githubusercontent.com/46494969/179562416-10d60b3a-9889-432c-8566-966b1f3d4398.png)

---

Veri-FAILED on rancher `v2.6-1134cad32243dc8c60812517d370690c754d05c9-head`:
1. Fresh install of rancher `v2.6-head`
2. Provision a downstream EKS cluster via the rancher UI - [Specify 2 vpc subnets + custom security group; no launch template]
3. Verified - EKS Cluster instance and Node instances show default + custom sg;
4. Provision a downstream EKS cluster via the rancher UI - [Specify 2 vpc subnets + custom security group; with launch template]
5. Veri-FAILED - EKS Cluster instance and Node instances show default + custom sg;

Screenshots:

`Step 3 - No template - Cluster Instance`
![no-temp-cluster-specs1](https://user-images.githubusercontent.com/46494969/179568668-55616581-bed5-4864-a8d1-e8ed16033c51.png)

`Step 3 - No template - Node 1`
![no-temp-node11](https://user-images.githubusercontent.com/46494969/179569006-3497ed72-c5e4-4162-af51-b3dd4561ea7c.png)

`Step 3 - No template - Node 2`
![no-temp-node22](https://user-images.githubusercontent.com/46494969/179569196-5f43e66e-5e31-4da5-b36d-2c23c71945c7.png)

`Step 4 - Template`
<img width="1216" alt="Screen Shot 2022-07-18 at 11 27 34 AM" src="https://user-images.githubusercontent.com/46494969/179578694-43f8102d-918d-47ab-a646-7969962f4feb.png">

`Step 5 - w/ template -Cluster Instance`
<img width="243" alt="Screen Shot 2022-07-18 at 11 25 38 AM" src="https://user-images.githubusercontent.com/46494969/179578273-9cd278db-f982-41ba-8a7a-dde7db1774ed.png">

`Step 5 - w/ template - Node 1`
<img width="421" alt="Screen Shot 2022-07-18 at 11 26 02 AM" src="https://user-images.githubusercontent.com/46494969/179578341-c6e1d28e-00f7-45fc-9ce8-199f200f73ad.png">

`Step 5 - w/ template - Node 2`
<img width="423" alt="Screen Shot 2022-07-18 at 11 26 18 AM" src="https://user-images.githubusercontent.com/46494969/179578365-faf44495-6f2e-42fd-bc1f-e3057dee780b.png">

**Comment by annablender** [comment]
@Josh-Diamond This test case can be disregarded

```
Provision a downstream EKS cluster via the rancher UI - [Specify 2 vpc subnets + custom security group; with launch template]
```

Team needs to discuss the expected behavior for that case. The default security group may not need to be added to the node instances in the case of a custom launch template being specified in rancher. Otherwise, the regression is fixed and this ticket can be closed

**Comment by snasovich** [comment]
Reopened, @Josh-Diamond to provide additional information on why it's going to be reopened.
We want to roll back the changes and not have the current fix in 2.6.7 yet.

**Comment by Josh-Diamond** [comment]
Re-opened due to fix being the root cause of unexpected behavior seen with EKS clusters.

Upon further testing, it was determined that this fix causes all provisioned EKS clusters to do a rolling update, which is not desired behavior.

When provisioning a 3-node EKS cluster from Rancher UI, the cluster takes just over 30m to come up active.
From AWS Console, you can observe 3 nodes come up active.  Then nodes are scaled to 6, then back down to 3.  Once nodes scale back down to 3 and are active, the cluster will come up active in Rancher UI

**Comment by jiaqiluo** [comment]
Can be validated on the latest v2.6-head

**Comment by Josh-Diamond** [comment]
Ticket #38014 - Test Results [cont.]

With HA Helm:

Verified on rancher `v2.6.6 => v2.6-c47178eb1457a7ff1aac135c86d3627dc971b704-head`:
1. Fresh install of rancher `v2.6.6`
2. Provision a downstream EKS cluster w/ k8s v1.21
3. Once `Active`, upgrade rancher server from `v2.6.6 => v2.6-head`
4. Verified - Cluster does not go into `Updating` state; no rolling update triggered
5. Verified - Rancher eks operator version is `rancher/eks-operator:v1.1.4-rc4`
6. Provision a new downstream EKS cluster w/ k8s 1.22
7. Verified - Cluster provisions in roughly 13m; no rolling updates are triggered in AWS Console

Screenshot:

`Step 5`
<img width="1297" alt="Screen Shot 2022-07-21 at 1 42 08 PM" src="https://user-images.githubusercontent.com/46494969/180322531-739ffbe4-ede1-42c7-a5c9-640d678a13cb.png">

**Comment by snasovich** [comment]
@annablender to investigate if there is any other way to fix the issue that will not trigger much slower initial provisioning and ideally not trigger rolling updates on upgrade (not sure if it's possible).

**Comment by annablender** [comment]
I have an alternate solution for the fix that I discussed with @phillipsj that will fix the provisioning time bump on both creation and upgrade. Needs design discussion.

**Comment by annablender** [comment]
Design discussion complete.

Discussion summary

Fixing the issue of slower initial provisioning to add the EKS default security group to the launch template is moot, because that is not the expected behavior. The original PR https://github.com/rancher/eks-operator/pull/60 changed this behavior and will be reverted.

_We want how rancher handles security groups in EKS to have parity with vanilla EKS_. EKS will only add the default security group to node instances unless there are security group(s) on the launch template, in which case those security group(s) replace the default on the nodes. Rancher will not add custom security groups to the launch template; any security groups defined by the user in the rancher UI will only be added at cluster level.

**Comment by annablender** [comment]
#### Test Results

**Results**
- [x] ablender-eks-sg-ltwithnosg (donnie-test-lt): default and user sg on cluster level, default sg on nodes
- [x] ablender-eks-sg-nolt: default and user sg on cluster level, default sg on nodes
- [x] ablender-eks-nosg-ltwithnosg: default sg on cluster level and nodes
- [x] ablender-eks-nosg-nolt: default sg on cluster level and nodes
- [ ] ablender-eks-nosg-ltwithsg (hgalal-mc-demo): (note: having a custom user sg doesn't matter here. We're testing that if an LT passed to EKS contains a sg, that sg will replace the default on the nodes. User sgs in rancher are not adding to the LT) - PENDING

![a3766091760d0daeb50642879f72101e.png](:/2d5c2cc4292547dab6fda072cd5045dc)

I ran into several EKS errors while verifying sg behavior on v2.6.7. If QA runs into errors testing this, please reach out to me. I will know how to resolve/workaround it.

**Comment by Josh-Diamond** [comment]
Test Plan:

Verify on `v2.6-head`:
1. Provision a downstream EKS cluster via the rancher UI - [use `donnie-test-lt` ]
2. Verify default + user sg on cluster level; default sg on nodes
3. Provision a downstream EKS cluster via the rancher UI - [sg w/ no launch template]
4. Verify default + user sg on cluster level; default sg on nodes
5. Provision a downstream EKS cluster via the rancher UI - [no sg w/ launch template w/ no sg]
6. Verify default sg on cluster level and nodes
7. Provision a downstream EKS cluster via the rancher UI - [no sg w/ no launch template]
8. Verify default sg on cluster level and nodes
9. Provision a downstream EKS cluster via the rancher UI - [use `hgalal-mc-demo` ]
10. Verify sg specified in template replace default sg on nodes; user sg's in rancher are not added to LT

Verify upgrade from `v2.6.6 => v2.6-head`:
1. Provision a downstream EKS cluster via the rancher UI - [use `donnie-test-lt` ]
2. Verify default + user sg on cluster level; default sg on nodes
3. Provision a downstream EKS cluster via the rancher UI - [sg w/ no launch template]
4. Verify default + user sg on cluster level; default sg on nodes
5. Provision a downstream EKS cluster via the rancher UI - [no sg w/ launch template w/ no sg]
6. Verify default sg on cluster level and nodes
7. Provision a downstream EKS cluster via the rancher UI - [no sg w/ no launch template]
8. Verify default sg on cluster level and nodes
9. Provision a downstream EKS cluster via the rancher UI - [use `hgalal-mc-demo` ]
10. Verify sg specified in template replace default sg on nodes; user sg's in rancher are not added to LT

Verify upgrade from `v2.6.5 => v2.6-head`:
1. Provision a downstream EKS cluster via the rancher UI - [use `donnie-test-lt` ]
2. Verify default + user sg on cluster level; default sg on nodes
3. Provision a downstream EKS cluster via the rancher UI - [sg w/ no launch template]
4. Verify default + user sg on cluster level; default sg on nodes
5. Provision a downstream EKS cluster via the rancher UI - [no sg w/ launch template w/ no sg]
6. Verify default sg on cluster level and nodes
7. Provision a downstream EKS cluster via the rancher UI - [no sg w/ no launch template]
8. Verify default sg on cluster level and nodes
9. Provision a downstream EKS cluster via the rancher UI - [use `hgalal-mc-demo` ]
10. Verify sg specified in template replace default sg on nodes; user sg's in rancher are not added to LT

**Comment by annablender** [comment]
Advising @Josh-Diamond on updating step 9-10

**Comment by Josh-Diamond** [comment]
Updated Test plan around offline info provided by @annablender

**Comment by Josh-Diamond** [comment]
Ticket #38014 - Test Results

With Docker on a single-node instance:

Verified on rancher `v2.6-c54b655dfab4838063758278664f7437fa0a2dac-head`:
1. Fresh install of rancher `v2.6-head`
2. As admin, create a standard user
3. As standard user, provision a downstream 2-node EKS cluster w/ sg defined + LT w/ no sgs used
4. Verified - SG description updated + accurate
5. Verified - Default sg + User sg on cluster level; Default sg on nodes
6. As standard user, provision a downstream 2-node EKS cluster w/ sg defined + no LT used
7. Verified - Default sg + User sg on cluster level; Default sg on nodes
8. As standard user, provision a downstream 2-node EKS cluster w/ no sg defined + LT w/ no sgs used
9. Verified - Default sg on cluster level; Default sg on nodes
10. As standard user, provision a downstream 2-node EKS cluster w/ no sg defined + LT w/ sgs used
11. Verified - sg from LT overwrites default sg on nodes

Screenshot:

`Step 4`
<img width="1206" alt="Screen Shot 2022-08-24 at 10 34 25 AM" src="https://user-images.githubusercontent.com/46494969/186514290-767152ac-8eac-4850-8454-8c90f2c9d14d.png">

---

Upgrade verified on rancher `v2.6.5 => v2.6-633f5aadaf0768f85f7ada74888f8392d374a394-head`:
1. Fresh install of rancher `v2.6.5`
2. As admin, create a standard user
3. As standard user, provision a downstream 2-node EKS cluster w/ sg defined + LT w/ no sgs used
4. Verified - Default sg + User sg on cluster level; Default sg on nodes
5. Upgrade rancher to `v2.6-head`
6. Verified - No rolling update; expected behavior
