### ISSUE TITLE
Azure AD authentication fails when the end points are set to China

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#38022]
**Rancher Server Setup**
- Rancher version: `rancher/rancher:v2.6-0fd630dd1328233958bdef6b9f7f413eb7463005-linux-amd64`
- Installation option (Docker install/Helm Chart): Docker install
   - If Helm Chart, Kubernetes Info: k3s
         Cluster Type (RKE1, RKE2, k3s, EKS, etc):
         Node Setup: 1 node 
         Version: `v1.21.3+k3s1`
- Proxy/Cert Details: `self-signed`

**Describe the bug**
Authentication with azure AD fails when end points are set to China. 
Following is the error that is received when we try to authenticate:
```
 server error while authenticating: UsersClient.BaseClient.Get(): unexpected status 401 with OData error: InvalidAuthenticationToken: Access token validation failure. Invalid audience.
```

**To Reproduce**
1. Create a rancher server on v2.6-head
2. From explorer >> Users & Authentication >> Auth providers >> Azure AD
3. enable Azure AD by selecting the endpoints for China and providing required tenant ID, client ID and secret
4. Save the config

**Result**
Authentication fails with the error:
```
server error while authenticating: UsersClient.BaseClient.Get(): unexpected status 401 with OData error: InvalidAuthenticationToken: Access token validation failure. Invalid audience.
```

**Expected Result**
Expected the auth to be enabled.

**Additional context**
When we try custom end points by providing the values of endpoints for China, it fails with the error:
```
server error while authenticating: authority does not have two segments
```

https://github.com/rancher/dashboard/issues/5671#issuecomment-1157431071

**Comment by rootwuj** [comment]
Validated on rancher v2.6-head (`df1b202`)

Azure AD authentication uses china endpoint and auth can be enabled.

<img width="1791" alt="image" src="https://user-images.githubusercontent.com/42061003/179660139-9917c432-9770-451b-a33d-07db7e75e721.png">
