### ISSUE TITLE
[Feature] Select groups with Okta integration

### ISSUE THREAD

**Issue by gaktive** [rancher/rancher#38029]
Internal reference: SURE-2882

**Rancher Server Setup**
- Rancher version: 2.6.3 Patch 1 & 2.6.5

**Describe the bug**

Captured from Slack, users cannot see groups in dropdown in Cluster Settings after an upgrade.

> They're using Okta and can log in without problems and in one of their older clusters (Rancher 2.5.3) it seems to work fine; both of their SAML applications in Okta are configured the same way.

> The difference is that their installation is clean (installed 2.6.3-patch1 a month ago) Taking a look into the SAML Assertion the assertion that 2.6.3-patch1 makes (or gets) does not have the groups attribute, and the assertions that 2.5.3 makes (or gets) does have the groups attribute.

From the user:
> This is my Attribute configuration Okta side 2.6.3-patch1 only gets userName and displayName 2.5.3 get userName, displayName and the groups list: https://user-images.githubusercontent.com/97888974/159506093-81140762-655a-4bb7-b115-8e67bdb71e80.png

Report from elsewhere:

> Users have reported a regression they have encountered on 2.6 and is a blocker for moving off 2.5.x. Without functional SSO (Okta) in front of Rancher, they will not green-light migrating to 2.6 from 2.5. This is a critical and time-sensitive issue for them as they add more clusters.

**Screenshots**
Related Dashboard issue with screenshots: https://github.com/rancher/dashboard/issues/5464

**Additional context**
Historical context from 2.5.7 (with a fix in 2.5.8): https://github.com/rancher/rancher/issues/30401

**Comment by MKlimuszka** [comment]
Adding a milestone for planning purposes, not as a commitment.

**Comment by ronhorton** [comment]
**Pass** Feature verified for release in rancher 2.7.5. 
Testing complete
Feature has QA sign off.
