### ISSUE TITLE
RKE2 Master node stuck in "Waiting for kubelet to update" after upgrade

### ISSUE THREAD

**Issue by shkarface** [rancher/rancher#38033]
**Rancher Server Setup**
- Rancher version: v2.6.5
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): v1.22.9+rke2r2<html>

- Proxy/Cert Details: Let's Encrypt Cert

**Information about the Cluster**
- Kubernetes version: 1.21.5rke2r2
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? Custom nodes using rancher command on each node

**User Information**
- What is the role of the user logged in? Cluster Owner
   
**Describe the bug**

When upgrading a downstream rke2 cluster from v1.21.5+rke2r2 to v1.22.9+rke2r2, the master node will be stuck in `Waiting for kubelet to update` (the actual node is upgraded)

***Machine Object***
```yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: Machine
metadata:
  annotations:
    objectset.rio.cattle.io/applied: H4sIAAAAAAAA/6STT4/TMBDFvwqac7Kbv242EhcQpxUcCuLUy9get6aOHdmTLqjqd0fJwtKlovw7Rpn3/Jv37CMMxKiREfojoPeBkW3waf4M8hMpTsQ30YYbhcyObmy4tRp6mPyAHrek8wHVznqC7JeC8OAp5tvDHnq4PZTZi3vr9cv3pCLxb2UeB4Ie1JQ4DLkQVJVNedeIsvwjaRpRLfp8yNv9YIw8SMgg7uls3KEkl6CH4wbOTNIG+g0466fPGzjBKQMVacnngx0oMQ4j9H5yLoPvDsdneugf1VdId5h20EPXaeoqXQuJUjS60FVb1cLUsmx1J7pGtF2hGmMu0FXwHIPLR4ee8hjcvCzHiS4miZW+OvCtyHzp18zH3olVQWSIilooIaRpWoN1q00hu6qQDVUFtSvsutqsSNeqKgvSVSm0nsO62tx5N8YRca7J4OR4VqaR1JylDIETRxyXYIM3drsms1zV0X6kmGzw0P+0xmG231s/b7G+f/PqyePfiebm3ZSY4rtHh8S4tX6be3qADKw3ERPHSfEU6e8IXy8sb5/e0H8gJkae0rPc1oT6C/QGXaJLzh//TqevAQAA///XVcZCCgQAAA
    objectset.rio.cattle.io/id: unmanaged-machine
    objectset.rio.cattle.io/owner-gvk: /v1, Kind=Secret
    objectset.rio.cattle.io/owner-name: custom-66e214194611
    objectset.rio.cattle.io/owner-namespace: c-m-5kmffbvb
    rke.cattle.io/join-url: https://10.10.80.111:9345
    rke.cattle.io/labels: '{"cattle.io/os":"linux"}'
  creationTimestamp: "2021-10-15T14:42:12Z"
  finalizers:
  - machine.cluster.x-k8s.io
  generation: 3
  labels:
    cattle.io/os: linux
    cluster.x-k8s.io/cluster-name: staging-new
    objectset.rio.cattle.io/hash: 88de82d36bab64d0d25236f3b15d86846580c4ff
    rke.cattle.io/control-plane-role: "true"
    rke.cattle.io/etcd-role: "true"
    rke.cattle.io/init-node: "true"
    rke.cattle.io/machine-id: fd8689670eefee036c66bf45fa35df0b820b4e20e57a883f7ed3c210ed216dd
  managedFields:
  - apiVersion: cluster.x-k8s.io/v1alpha4
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:objectset.rio.cattle.io/applied: {}
          f:objectset.rio.cattle.io/id: {}
          f:objectset.rio.cattle.io/owner-gvk: {}
          f:objectset.rio.cattle.io/owner-name: {}
          f:objectset.rio.cattle.io/owner-namespace: {}
          f:rke.cattle.io/join-url: {}
          f:rke.cattle.io/labels: {}
        f:finalizers:
          .: {}
          v:"machine.cluster.x-k8s.io": {}
        f:labels:
          .: {}
          f:cattle.io/os: {}
          f:objectset.rio.cattle.io/hash: {}
          f:rke.cattle.io/control-plane-role: {}
          f:rke.cattle.io/etcd-role: {}
          f:rke.cattle.io/init-node: {}
          f:rke.cattle.io/machine-id: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"e69ede6a-e935-43b7-9191-c37ca01fcd68"}: {}
      f:spec:
        .: {}
        f:bootstrap:
          .: {}
          f:configRef:
            .: {}
            f:apiVersion: {}
            f:kind: {}
            f:name: {}
            f:namespace: {}
          f:dataSecretName: {}
        f:clusterName: {}
        f:infrastructureRef:
          .: {}
          f:apiVersion: {}
          f:kind: {}
          f:name: {}
          f:namespace: {}
        f:providerID: {}
      f:status:
        .: {}
        f:addresses: {}
        f:bootstrapReady: {}
        f:infrastructureReady: {}
        f:lastUpdated: {}
        f:nodeInfo:
          .: {}
          f:architecture: {}
          f:bootID: {}
          f:containerRuntimeVersion: {}
          f:kernelVersion: {}
          f:kubeProxyVersion: {}
          f:kubeletVersion: {}
          f:machineID: {}
          f:operatingSystem: {}
          f:osImage: {}
          f:systemUUID: {}
        f:nodeRef:
          .: {}
          f:apiVersion: {}
          f:kind: {}
          f:name: {}
          f:uid: {}
        f:observedGeneration: {}
        f:phase: {}
    manager: rancher
    operation: Update
    time: "2021-12-22T09:54:16Z"
  - apiVersion: cluster.x-k8s.io/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions: {}
    manager: rancher
    operation: Update
    subresource: status
    time: "2022-05-19T19:00:24Z"
  name: custom-66e214194611
  namespace: fleet-default
  ownerReferences:
  - apiVersion: cluster.x-k8s.io/v1alpha4
    kind: Cluster
    name: staging-new
    uid: e69ede6a-e935-43b7-9191-c37ca01fcd68
  resourceVersion: "214586622"
  uid: 67fa2747-2742-42cd-b8d2-618fdfefbdfd
spec:
  bootstrap:
    configRef:
      apiVersion: rke.cattle.io/v1
      kind: RKEBootstrap
      name: custom-66e214194611
      namespace: fleet-default
    dataSecretName: custom-66e214194611-machine-bootstrap
  clusterName: staging-new
  infrastructureRef:
    apiVersion: rke.cattle.io/v1
    kind: CustomMachine
    name: custom-66e214194611
    namespace: fleet-default
  providerID: rke2://n1stgk8s
status:
  addresses:
  - address: 10.10.80.111
    type: InternalIP
  - address: n1stgk8s
    type: Hostname
  bootstrapReady: true
  conditions:
  - lastTransitionTime: "2021-10-15T14:45:57Z"
    status: "True"
    type: Ready
  - lastTransitionTime: "2021-10-15T14:42:13Z"
    status: "True"
    type: BootstrapReady
  - lastTransitionTime: "2021-10-15T14:45:57Z"
    status: "True"
    type: InfrastructureReady
  - lastTransitionTime: "2022-03-31T23:15:17Z"
    status: "True"
    type: NodeHealthy
  - lastTransitionTime: "2022-05-19T19:39:54Z"
    status: "True"
    type: PlanApplied
  - lastTransitionTime: "2022-05-19T19:00:35Z"
    status: "True"
    type: Provisioned
  - lastTransitionTime: "2022-06-19T12:35:10Z"
    message: waiting for kubelet to update
    reason: Waiting
    status: Unknown
    type: Reconciled
  infrastructureReady: true
  lastUpdated: "2021-10-15T14:45:58Z"
  nodeInfo:
    architecture: amd64
    bootID: a6990ea6-c87b-4470-a3c0-b4acb7e9d16f
    containerRuntimeVersion: containerd://1.4.11-k3s1
    kernelVersion: 5.4.0-94-generic
    kubeProxyVersion: v1.21.5+rke2r2
    kubeletVersion: v1.21.5+rke2r2
    machineID: 06002bf384af46c6861649f51232fcd9
    operatingSystem: linux
    osImage: Ubuntu 20.04.3 LTS
    systemUUID: d4383942-bdb2-bf27-7ff5-ecbe788122d1
  nodeRef:
    apiVersion: v1
    kind: Node
    name: n1stgk8s
    uid: 9e4b3f9a-2fd5-47c6-aae9-80d817330533
  observedGeneration: 3
  phase: Running

```

**Comment by dmpe** [comment]
Yeeh, I am also see this message. All pods are running, all container seem to be healthy but rancher GUI "cluster management" shows on all control nodes that "they are waiting for kubelet to update". 

Provider: RKE2
Kubernetes Version: v1.23.4

Upgraded using https://github.com/rancher/system-upgrade-controller

**Comment by sandori01** [comment]
I experience the same after upgrading from v1.22.9
RKE2
Kubernetes v1.23.7
Rancher gui: 2.6.7 on premise.
How did you resolve this?

**Comment by Sepiidae** [comment]
I experience the same issue after upgrading from v1.24.4+rke2r1 Customer RKE2 cluster deployment

Rancher GUI: 2.6.9 on prem
Provider: RKE2
Kubernetes Version: v1.24.7


Configuring bootstrap node(s) custom-0c5b0aabce03: waiting for kubelet to update
  |  

<br class="Apple-interchange-newline">

**Comment by malmor** [comment]
Same issue here:
We upgraded our RKE2 cluster from `v1.24.4+rke2r1` to `v1.24.9+rke2r1` using the `system-upgrade-controller` running Rancher `v2.7.0`.

Now under "Cluster Management" > "Cluster XY" it says `Waiting for kubelet to update` - but all pods seem to be up and running.

Looking at the node there is also a running `kubelet` process:
```
root      163561  5.7  0.7 890772 126496 ?       Sl   07:59   0:31 kubelet --volume-plugin-dir=/var/lib/kubelet/volumeplugins ...
```

Restarting the `rke2-server` service on the nodes did not fix this either:
```
systemctl stop rke2-server
systemctl start rke2-server
```

Are there any known workarounds or fixes?

**Comment by edgrz** [comment]
I can confirm it's still happening. From `v1.23.10+rke2r1` to `v1.24.10+rke2r1` after performing it the manual way from script (https://get.rke2.io), after restarting the rke2-server, the RKE2 Master node stuck in "Waiting for kubelet to update".

**Comment by sandori01** [comment]
I might be wrong here, but it seems that the upgrade  performed didn't correspond to change in cluster version. Rancher server provides an option to upgrade clusters. In order to do that, you can simply change the version in Cluster management/Edit config (or edit yaml) and there cluster version. 
Upgrading the cluster on the cluster nodes results in difference between the actual cluster version and the version indicated in cluster config. This causes the "Waiting for kubelet to upgrade" message. 
Solution 1: if upgraded manually from the nodes (https://get.rke2.io) change the version number in cluster contfiguration to correspond with the installed version.
Solution 2: Avoid upgrading from the RKE2 nodes, upgrade from Rancher. When you change the cluster version in the cluster configuration file, rancher will automatically download and install new cluster software on all nodes.

**Comment by edgrz** [comment]
@sandori01 indeed cluster was reporting back "active" after editing manually the cluster configuration object to correspond with the version installed in the cluster. However, even if it's a smaller change it implies that we need to reach UI to "update" it. In my opinion it would make sense that UI refreshed after the upgrade has been "manually" (by an automation) performed.

**Comment by sandori01** [comment]
Actually I think this is the other way around. A normal upgrade is performed on the rancher server by modifying the version. After the modification is recorded, rancher instructs the downstream cluster to perform an upgrade. Meddling with the cluster without knowledge of the Rancher server is not how it is supposed to work, I think.

**Comment by edgrz** [comment]
Well I don't agree on that. We have a rancher server/control-plane where we have created/imported many clusters, so that we have a centralized point. If any of those RKE2 clusters wants to be upgraded, they shouldn't need to rely on Rancher UI, but allow them to do it by themselves according to rancher [documentation](https://docs.rke2.io/upgrade/manual_upgrade).

If we need to visit UI to perform upgrades, that would kill any potential automation.

**Comment by sandori01** [comment]
I can relate to that. The documentation related to upgrades doesn't 
mention the requirement of visiting the Rancher UI.

However, for changing the downstream cluster configuration (version 
number in particular) one does not have to rely on thew Rancher GUI.

The cluster configuration for the default fleet is stored in a cluster 
CRD with the same name as your cluster. You can check the configuration 
by getting it on the mgmt cluster:
kubectl get cluster -n fleet-default <clustername> -o yaml

The cluster version is stored in kubernetesVersion. The cluster 
configuration can be patched so automations can be run there. In order 
to do a cluster upgrade you do not even have to have access to the 
cluster nodes.

The beauty of kubernetes is that most tasks can be performed many 
different ways, so one can start from the nodes or from the management. 
I wonder what Rancher folks think about this?
