### ISSUE TITLE
 Node stuck in Waiting for Node Ref in a Custom RKE2 cluster

### ISSUE THREAD

**Issue by Kamaradeivanov** [rancher/rancher#38032]
**Rancher Server Setup**
- Rancher version: 2.6.5
- Installation option (Docker install/Helm Chart): Helm Chart, Kubernetes 1.23.6 Kapsule (scaleway)

**Information about the Cluster**
- Kubernetes version: v1.23.7+rke2r2
- Cluster Type (Local/Downstream):  Custom = Running a Registration Command on each node. Nodes are elastic-metal instances from scaleway

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  admin
   
**Describe the bug**
All nodes are stuck in Waiting for Node Ref 

**To Reproduce**
- Create an RKE2 Custom cluster with no cloud provider (everything else on default)
- 3 etcd+control-plane nodes and 3 worker nodes
- The first node where the registration command was apply came up in the cluster, but no other node appears
- All nodes are stuck in "Waiting for Node Ref" in cluster management 
- All pods are running on the first node except "cattle-fleet-system"  because it's a control-plane node (had the associated taint)

**Expected Result**
All the nodes should come up Active in the cluster management and in the cluster view

**Comment by bennysp** [comment]
I am noticing the same thing right now. 

Using the below:
3 control plane nodes (These come online)
3 work nodes (These ones are stuck on "Waiting for Node")

Rancher: `2.6.5`
RKE2: `v1.23.6+rke2r2`
Terraform Rancher Provider: `1.24.0`

**Comment by Kamaradeivanov** [comment]
Same thing with rke2 cluster version : v1.22.10+rke2r2 and with node containing the 3 roles (etcd+control-plane+worker)

**Comment by AlexisDucastel** [comment]
Same problem here ! 
 
Node are stuck in WaitingForNodeRef  (Rancehr 2.6.5, rke2 v1.23.7+rke2r2 on Ubuntu 20.04)
```
  - lastTransitionTime: "2022-06-20T20:12:41Z"
    reason: WaitingForNodeRef
    severity: Info
    status: "False"
    type: NodeHealthy
```

**Comment by boldynnetwork** [comment]
i have the same problem - everything works great. but when cloud provide is set to vsphere -nodes/vms are stuck in creating

      reason: WaitingForNodeRef
      severity: Info
      status: 'False'
      type: NodeHealthy
      
      
Tried changind all possible values of CPI and CSI 

     chart_values = <<EOF
rancher-vsphere-cpi:
  vCenter:
    host: ${var.vcenter-server}
    port: 443
    insecureFlag: true
    datacenters: ${var.vcenter-datacenters}
    username: ${var.vcenter-user}
    password: ${var.vcenter-pass}
    credentialsSecret:
    #  name: "vsphere-cpi-creds"
      generate: true
  # cloudControllerManager:
  #   nodeSelector:
  #     node-role.kubernetes.io/control-plane: 'true'

rancher-vsphere-csi:
  vCenter:
    host: ${var.vcenter-server}
    # port: 443
    # insecureFlag: "1"
    datacenters: ${var.vcenter-datacenters}
    username: ${var.vcenter-user}
    password: ${var.vcenter-pass}
    configSecret:
      #name: "vsphere-config-secret"
      generate: true
  # csiNode:
  #   nodeSelector: 
  #     node-role.kubernetes.io/worker: 'true'
  storageClass:
    # allowVolumeExpansion: true
    datastoreURL: ${"var.vcenter-ds-url"}
  #  storagePolicyName: "k8s-storage"
  # asyncQueryVolume:
  #   enabled: true
  # csiAuthCheck:
  #   enabled: true
  # improvedCsiIdempotency:
  #   enabled: true
  # improvedVolumeTopology:
  #   enabled: true
  # onlineVolumeExtend:
  #   enabled: true
  storageClass:
    # allowVolumeExpansion: true
    storageClassName: "vsphere-csi-sc"
  # triggerCsiFullsync:
  #   enabled: true
EOF
