### ISSUE TITLE
Rancher Backup to S3 On Prem

### ISSUE THREAD

**Issue by lex-asr** [rancher/rancher#38039]
Environment: On Prem
Rancher Version: 2.5.8
K8s Version: RKE 1.20.5
Docker Version: CE 20.10.6
CNI: Canal

Hello I have a problem when I want to backup my rancher ETCD to an On Prem Minio S3.
I had follow this topic: https://rancher.com/docs/rancher/v2.5/en/backups/configuration/backup-config/#example-minio-configuration 

This is my config file:

`apiVersion: resources.cattle.io/v1`
`kind: Backup`
`metadata:`
  `name: test`
`spec:`
  `resourceSetName: rancher-resource-set`
  `retentionCount: 10`
  `storageLocation:`
    `s3:`
      `bucketName: test`
      `credentialSecretName: secrets-s3-backup`
      `credentialSecretNamespace: default`
      `endpoint: test.example.com`
      `endpointCA: CA`

When I start a backup I have this message: 
`message: 'failed to check s3 bucket:test, err:Get https://minio.exemple.com/test/?location=: net/http: invalid header field value "AWS4-HMAC-SHA256 Credential=XXXXX/us-east-1/s3/aws4_request,
      SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=xxx"
      for key Authorization'`

I don't understand why Rancher Backup want to contact AWS when i'm in On Prem environnement. 

I test an other config with folder name (folder: /) and I have a second error without AWS request:
    `message: 'mkdir /tmp/uploadpath160223130: file exists'`

Is it possible to help me ? Thank you.

**Comment by superseb** [comment]
What version of the rancher-backup chart are you using to install? This error usually relates to a wrongly created secret (see https://github.com/stashed/stash/issues/547#issuecomment-411358523) but could be something else. To investigate we need exact details how to reproduce (so all versions used, including Minio and if possible, the way it was setup so we can use that to reproduce)
