### ISSUE TITLE
[2.6] Provisioning-tests pipeline phase is failing due to KDM bug

### ISSUE THREAD

**Issue by MbolotSuse** [rancher/rancher#38048]
**Rancher Server Setup**
Pipeline - provisioning-tests phase failing for both provisioning-tests-k3s and provisioining-tests-rke.

   
**Describe the bug**
The provisioning-tests phase is failing due to a bug in KDM. This bug causes the tests to wait for a cluster which never becomes available. 

If the KDM version is pinned to the version used before the changes made on 06/17/2022, the tests pass. This behavior can be seen in `https://github.com/rancher/rancher/pull/38047`. 

**To Reproduce**
Run a pipeline without pinning the KDM version.

**Result**
Pipeline fails - takes over an hour waiting for deployed cluster to become available.

**Expected Result**
Pipeline does not fail and runs successfully.

**Comment by jakefhyde** [comment]
Fixed due to #38645 & #38531, see https://drone-pr.rancher.io/rancher/rancher/23369/1/2 for confirmation. Also closing because there is nothing for QA to test.
