### ISSUE TITLE
Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered

### ISSUE THREAD

**Issue by ahmad-sadia** [rancher/rancher#38052]
Rancher version: v2.6.1
Installation Helm Chart:
Chart: rancher-stable/rancher 2.6.1
RKE1: terraform-provider-rke_1.3.0
Kubernetes v1.21.7
Hosted via Openstack

None of the cluster's master nodes with rancher/rancher-agent:v2.6.1 image can get registered. 
rancher agent logs on the master node shows an infinite number of this message: msg="Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered".

I'm using the same network configuration used in a working rancher v2.4.3/terraform-provider-rke v1.0.0.

 Would appreciate any help.

Complete logs are attached below: 
<img width="1680" alt="Screenshot 2022-06-22 at 01 30 42" src="https://user-images.githubusercontent.com/44840274/174914622-2f30155f-7c89-49f2-96b9-e4c9d0c422e7.png">
<img width="1445" alt="Screenshot 2022-06-22 at 01 26 26" src="https://user-images.githubusercontent.com/44840274/174914660-829221bf-0b90-4281-99f5-9256f4791afd.png">
<img width="1441" alt="Screenshot 2022-06-22 at 01 26 43" src="https://user-images.githubusercontent.com/44840274/174914677-c5e726bd-832c-49d2-9e43-88ddb0c14c73.png">

Containers images in one of the _rancher master nodes_:

![Screenshot 2022-06-22 at 11 43 12](https://user-images.githubusercontent.com/44840274/174998290-24150d5b-71ef-4b55-bd3d-919356ba52f1.png)

Some errors I see in rancher/rancher container:

![Screenshot 2022-06-22 at 12 25 23](https://user-images.githubusercontent.com/44840274/175007159-0b1a1156-2dd3-4575-9868-f8f91f701408.png)

**Comment by hadihammurabi** [comment]
How you solve this @ahmad-sadia ?

**Comment by ahmad-sadia** [comment]
@hadihammurabi  The problem was for me that I used to create the master nodes first, wait for them to be ready, then create the worker nodes.

That how my was the order of Terraform code when building rancher v2.4.3, and K8's v1.17.5.

With newer versions, creating/registering the master and worker nodes at the same time solved it for me.

**Comment by hadihammurabi** [comment]
Thanks @ahmad-sadia .

I am facing condition that everything already run and need to add more nodes.
Do you have suggestion?

**Comment by ahmad-sadia** [comment]
@hadihammurabi  Any logs of the errors?

**Comment by hadihammurabi** [comment]
@ahmad-sadia i create issue here #38200
