### ISSUE TITLE
[CSP Adapter] Support for Proxy scenarios

### ISSUE THREAD

**Issue by MbolotSuse** [rancher/rancher#38051]
The CSP adapter should support the use of a proxy to better support airgap environments. 

This use of a proxy should be similar to what we offer for our core rancher deployment and what we specify in the [docs](https://rancher.com/docs/rancher/v2.6/en/installation/install-rancher-on-k8s/chart-options/#http-proxy)

**Comment by cbron** [comment]
This may just need to be tested
