### ISSUE TITLE
Min value of sliders differs

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#3805]
This is a tiny nitpick. Feel free to just close this issue. But, take a look at this image:
![screen shot 2016-03-07 at 10 58 18 am](https://cloud.githubusercontent.com/assets/2473240/13578173/86bea33e-e453-11e5-8132-7ec90ac44ff0.png)
All three sliders are as far to the left as they can possibly go, but the slider for vCPUs is much further out than the other two. Memory slider has a little blue and disk has no visible blue. I'd argue that at their min values, all these sliders should be where the disk slider is.

**Comment by cjellick** [comment]
Ping @vincent99

**Comment by vincent99** [comment]
If you look closely there is actually blue there :smile:.  The scales are from 0 to $some_max, and the range is just much narrower on CPUs so each step is many pixels.  But fine, the scales can just start at $some_min.

**Comment by lvuch** [comment]
resolved in https://github.com/rancher/ui/pull/535

**Comment by tfiduccia** [comment]
Missed service

**Comment by vincent99** [comment]
Nope... Service is allowed to have a scale of zero, but the default should still be 1.

**Comment by tfiduccia** [comment]
Version - master UI 3/17
Verified fixed
