### ISSUE TITLE
Upgrading rancher helm install patch version to an rc or head version should not log users out

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#38060]
**Rancher Server Setup**
- Rancher version: `v2.6.5` upgraded to `v2.6.6-rc1`
- Installation option (Docker install/Helm Chart): `Helm install`
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1
- Proxy/Cert Details: `Self signed`

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Admin
   
**Describe the bug**
Upgrading rancher helm install previous patch version to a current version should not log users out. From the column `>= v2.6.0-rc1 to >= v2.6.0-rc1` https://github.com/rancher/rancher/issues/34149#issuecomment-901249550

**To Reproduce**
1. Install rancher server v2.6.5 helm install
2. Upgrade rancher server version to v2.6.6-rc1
3. Wait until the rancher pods are upgraded.
4. Once the upgrade is completed, refresh the UI.

**Result**
Users are logged out and are allowed upon a re login.

**Expected Result**
Expected the users to stay logged in

**Additional context**
This doesn't happen when we upgrade from v2.6.4 to v2.6.5. Only happens on an upgrade from v2.6.4[any released versions] to 2.6.6-rc[current rc version] or v2.6-head.

**Comment by paynejacob** [comment]
For the developer that picks this up, we should unit test all the possible upgrades pattern.
