### ISSUE TITLE
Networking no longer working

### ISSUE THREAD

**Issue by nhumrich** [rancher/rancher#3806]
Rancher Version:
v0.56.1 and v0.59.1

Docker Version:
1.9.1 and 1.10.2

OS: Ubuntu

Cloud: AWS

Steps to Reproduce: 
Create two hosts in rancher. And run a service such that a container exists on each host, with port forwarding on a specific port such as 30001.
Try to telnet to Container B (which lives on host B) from Container A (which lives on host A) by IP address. 

Results: 
Container B can not find Container A. IP isn't reachable. Usually, telnet just hangs on "trying <IPADRRESS>"

I can however telnet from Container B to Host A, via the forwarded port. Therefor all connection seems to be fine. I even quadruple checked that the hosts can talk to eachother via ALL protocols and ports (via AWS Security Groups), so firewall shouldn't be an issue. 

Expected:
Containers should be able to telnet eachother.

This is a regression. Everything was working correctly in v.0.56.1 then you guys released 0.59 and it continued to work for me because my network agents were still running 0.56.1 stuff. I never updated to 0.59 and as soon as I introduced a new host (thus a new network agent container) it all broke. My guess is that it downloaded the new network stuff for 0.59, even without me deciding to upgrade. 
Out of desperation I updated to v0.59.1 and still things were not working. I also updated to the latest docker 1.10.2, and still not working. I have also tried to downgrade again and that doesn't work, so now I am stuck and none of my hosts can talk to eachother.

**Comment by ibuildthecloud** [comment]
@nhumrich Correct me if I'm wrong but you are just saying that networking 100% doesn't work?  If you have a running multi host setup in which networking does not work can you please share the `/var/log/rancher-net.log` and `/var/log/charon.log` from the network agent running on both hosts.

If this is an upgraded setup I would recommend that you delete all network agents from all hosts and then deploy something (any container) and the network agents will recreate.

Finally, there is a known issue around GCM mode for ipsec encryption getting set wrong.  In the network agent can you do a `ps -ef` and see if `rancher-net` is launched with `--gcm=false` or `--gcm-true`.

**Comment by nhumrich** [comment]
Thanks for the followup. Looks like GCM is being used:
`/var/lib/cattle/bin/rancher-net --log /var/log/rancher-net.log -f /var
/lib/cattle/etc/cattle/ipsec/config.json -c /var/lib/cattle/etc/cattle/ipsec -i 172.17.0.3/16 --pid-file /var/run/ranc
her-net.pid --gcm=true`

As far as the files, here are the file for hostA:
https://gist.github.com/nhumrich/e6188aca24b174b7e748
https://gist.github.com/nhumrich/93a3f2f0c101c2ad2182

And here are the ones for hostB:
https://gist.github.com/nhumrich/37e3eb0bbe88f7ae817b
https://gist.github.com/nhumrich/e8a698b3a63c657cf23a

Please note that I had HostA running by itself for a while, then I added host B. If I need to create both at the same time, I can. 


As far as being an "upgraded setup", whenever I upgrade, I create brand new hosts, so that shouldn't be an issue. I upgraded to 59.1, then created two new hosts, and deleted the old ones.

**Comment by nhumrich** [comment]
Is there a workaround or anything I can do in the meantime to get rancher working again?

**Comment by ibuildthecloud** [comment]
@nhumrich between hosts A and B I can see its sending packets to port 500 to start the IPSec handshake.  It doesn't appear that either host is receiving them though.  I will dig further into the logs but are you sure that your security group settings allow traffic in on udp ports 500 and 4500.

Also note that traffic is being sent to the public IP of the instances, not the private instance IP.

**Comment by nhumrich** [comment]
I am sure they should be able to access each other on every port.
One reason I know that is, everything was working OK before, and I haven't changed any firewall settings on aws.
Why would they use the public IP address instead of the private? Not sure how to change that, but it shouldn't matter.
I will try to open 500 and 4500 to the public and see if that helps.

**Comment by nhumrich** [comment]
Ok so I opened 500 and 4500 to the public, and everything worked. However this is not ideal. The issue is probably related to the fact that the public IP is being used.
Any idea why the public IP's are being used instead of the internal? How could I get the network agents to use the internal ip's?

**Comment by deniseschannon** [comment]
What IPs are shown on the hosts within Rancher server?

If you want Rancher to use the private IP, you'd need to set it when launching your rancher/agent.

http://docs.rancher.com/rancher/rancher-ui/infrastructure/hosts/custom/#vms-with-private-and-public-ip-addresses

**Comment by nhumrich** [comment]
The public IP shows, but its always been that way. Is there anything that has changed that would change how the networking would work with public ip's and whatnot?

**Comment by ibuildthecloud** [comment]
@nhumrich Can you please retest w/ 1.0 once released (in less than 24 hours).

**Comment by nhumrich** [comment]
@ibuildthecloud Same behaviour. Telling rancher to use the internal IP's seems to work. Just not sure why the public ip's were working before, or why they wouldn't work in general. Typically AWS doesn't block based on public/private ip's but maybe I have that wrong.

**Comment by leodotcloud** [comment]
@nhumrich I just played with the security groups on AWS. The behavior I am seeing is it all traffic is blocked except those specified in the security group. To enable the private IP to work with I had to add the private IP subnet in the security group. You were able to see the hosts in the Rancher UI because you would have specified port 8080 in the security group and the initial connection from the agent to the server is on this port.

Solution for your problem: Add the ports 500/4500 or whatever you need to the security group and you don't have to specify 0.0.0.0 but just the subnet of your hosts.

**Comment by nhumrich** [comment]
I've just been using the private ip's when registering with rancher and that seams to work.
