### ISSUE TITLE
[BUG] Imported cluster agent cannot connect when applying import instructions twice

### ISSUE THREAD

**Issue by rverchere** [rancher/rancher#38072]
**Rancher Server Setup**
- Rancher version: 2.6.5
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): Tested on RKE1, managed clusters (OVH, Civo) with k8s 1.20, 1.22 (k3s), 1.23
- Proxy/Cert Details: cert-manager, with nginx adn traefik

**Information about the Cluster**
- Kubernetes version: 1.20, 1.22, 1.23
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Imported (OVH, Civo)

**User Information**
- What is the role of the user logged in? Admin
   
**Describe the bug**
When you apply the setup manifests **twice** (more than one time), the imported cluster cannot connect to rancher anymore.
I've tested with multiple k8s versions and providers, I always have the issue.

**To Reproduce**
1. Create a generci imported cluster
2. Apply setup manifests to install the cattle-cluster-agent on the downstream cluster, and then see it registered to rancher
3. Apply setup manifest a 2nd time. The downstream cattle-cluster-agent restarts and cannot connect to rancher anymore

**Result**
The downstream cluster is not connected anymore. I tried to uninstall/reinstall all the downstream cluster manifests (cattle-cluster-agent), the cluster is still unable to connect.

The only way to add it to rancher is to create a new cluster.

**Expected Result**
The downstream cluster should connect to rancher without issue.

**Additional context**
Some logs :

1. When applying twice the setup manifests, I see that the `deployment.apps/cattle-cluster-agent` resource changes, using another secret `cattle-credentials`

2. Logs on the downstream server:
```
NFO: Environment: CATTLE_ADDRESS=10.42.2.9 CATTLE_CA_CHECKSUM= CATTLE_CLUSTER=true CATTLE_CLUSTER_AGENT_PORT=tcp://10.43.174.159:80 CATTLE_CLUSTER_AGENT_PORT_443_TCP=tcp://10.43.174.159:443 CATTLE_CLUSTER_AGENT_PORT_443_TCP_ADDR=10.43.174.159 CATTLE_CLUSTER_AGENT_PORT_443_TCP_PORT=443 CATTLE_CLUSTER_AGENT_PORT_443_TCP_PROTO=tcp CATTLE_CLUSTER_AGENT_PORT_80_TCP=tcp://10.43.174.159:80 CATTLE_CLUSTER_AGENT_PORT_80_TCP_ADDR=10.43.174.159 CATTLE_CLUSTER_AGENT_PORT_80_TCP_PORT=80 CATTLE_CLUSTER_AGENT_PORT_80_TCP_PROTO=tcp CATTLE_CLUSTER_AGENT_SERVICE_HOST=10.43.174.159 CATTLE_CLUSTER_AGENT_SERVICE_PORT=80 CATTLE_CLUSTER_AGENT_SERVICE_PORT_HTTP=80 CATTLE_CLUSTER_AGENT_SERVICE_PORT_HTTPS_INTERNAL=443 CATTLE_CLUSTER_REGISTRY= CATTLE_INGRESS_IP_DOMAIN=sslip.io CATTLE_INSTALL_UUID=5e01b0fd-e971-4e08-aee5-2f95434f0ce4 CATTLE_INTERNAL_ADDRESS= CATTLE_IS_RKE=false CATTLE_K8S_MANAGED=true CATTLE_NODE_NAME=cattle-cluster-agent-75f78d47d-pfspq CATTLE_SERVER=https://rancher.cluster1.civo.vrchr.fr CATTLE_SERVER_VERSION=v2.6.5
INFO: Using resolv.conf: search cattle-system.svc.cluster.local svc.cluster.local cluster.local nameserver 10.43.0.10 options ndots:5
INFO: https://rancher.cluster1.civo.vrchr.fr/ping is accessible
INFO: rancher.cluster1.civo.vrchr.fr resolves to 74.220.16.174
time="2022-06-23T10:36:06Z" level=info msg="Listening on /tmp/log.sock"
time="2022-06-23T10:36:06Z" level=info msg="Rancher agent version v2.6.5 is starting"
time="2022-06-23T10:36:06Z" level=info msg="Connecting to wss://rancher.cluster1.civo.vrchr.fr/v3/connect/register with token starting with 944gl5l45h6d8fvdpn8dm4z7bwc"
time="2022-06-23T10:36:06Z" level=info msg="Connecting to proxy" url="wss://rancher.cluster1.civo.vrchr.fr/v3/connect/register"
```

3. Logs on the rancher server, nothing really revelent:
```
2022/06/23 10:42:44 [ERROR] Error during subscribe websocket: close sent
2022/06/23 10:42:44 [ERROR] Error during subscribe websocket: close sent
```

**Comment by rverchere** [comment]
Just upgraded to v2.6.6, same issue.

But I get a workaround. When getting the diff on what is applied, I see 2 modifications:
1. **cattle-credentials** secret reference
2. **CATTLE_FEATURES**: `embedded-cluster-api=false,fleet=false,monitoringv1=false,multi-cluster-management=false,multi-cluster-management-agent=true,provisioningv2=false,rke2=false`

Updating this 2 values to the deployment corrects the issue for the already-registered cluster.

**Comment by anthony-decusati-tfs** [comment]
> Just upgraded to v2.6.6, same issue.
> 
> But I get a workaround. When getting the diff on what is applied, I see 2 modifications:
> 
> 1. **cattle-credentials** secret reference
> 2. **CATTLE_FEATURES**: `embedded-cluster-api=false,fleet=false,monitoringv1=false,multi-cluster-management=false,multi-cluster-management-agent=true,provisioningv2=false,rke2=false`
> 
> Updating this 2 values to the deployment corrects the issue for the already-registered cluster.

@rverchere - Can you elaborate on your workaround?  Are you updating these in the agent deployment YAML?  What do you update them to?  In my case, I dont see `CATTLE_FEATURES` referenced in the agent deploy.

I am also having this issue now.

**Comment by rverchere** [comment]
@anthony-decusati-tfs sure!

WHen you first apply the manifests, these values are not set, but they are added/updated once the cluster is registered to Rancher.

To find the workaround and what changed between the first and second register, I did:

1. kubectl apply -f https://rancher.company.com/registering-manifests.yml
2. wait for the cluster to be registered
5. Saved the cattle-cluster-agent deployment manifests (kubectl get deployment cattle-cluster-agent -o yaml)
4. curl https://rancher.company.com/registering-manifests.yml -o registering-manifests.yml
6. kubectl diff -f registering-manifests.yml

kubectl diff is a plugin which show the differences before applying. I've seen then the CATTLE_FEATURES and cattle-credentials changes.

**Comment by anthony-decusati-tfs** [comment]
> @anthony-decusati-tfs sure!
> 
> WHen you first apply the manifests, these values are not set, but they are added/updated once the cluster is registered to Rancher.
> 
> To find the workaround and what changed between the first and second register, I did:
> 
> 1. kubectl apply -f https://rancher.company.com/registering-manifests.yml
> 2. wait for the cluster to be registered
> 3. Saved the cattle-cluster-agent deployment manifests (kubectl get deployment cattle-cluster-agent -o yaml)
> 4. curl https://rancher.company.com/registering-manifests.yml -o registering-manifests.yml
> 5. kubectl diff -f registering-manifests.yml
> 
> kubectl diff is a plugin which show the differences before applying. I've seen then the CATTLE_FEATURES and cattle-credentials changes.
> 
> And yes, at the end I just updated the cattle-cluster-agent deployment with the previous one saved to make it work.

Thanks, @rverchere, this did help us.  We have about 30 clusters, and I've been able to reconnect about a dozen so far.

These two problems seem to be separate, but possibly related.  I found that if I completely wipe the agent off the clusters, remove the `cattle-system` namespace, and re-install, the deployment is missing the `CATTLE_FEATURES` environment variable.  If I add it manually to the deployment with the values above, the agent *usually* starts and re-connects to rancher.  `CATTLE_FEATURES` is not present in the YAML provided by the registration token.

I encountered a few where a second cattle-credentials secret was created, the deployment was updated to use it, but I had to switch back to the secret referenced in the deployment yaml from rancher or it did not work.  I'm not exactly sure what creates the second secret, but it seems related to the agent.

Anyone trying this, make sure all agent pods are terminated *and removed* when making changes.  I found some cases where the pod in `terminating` status was maintaining the connection to Rancher, making things look like they were okay when they weren't.

**Comment by rverchere** [comment]
stil there

**Comment by rverchere** [comment]
Appears on one of my clusters.

Just re-add the `CATTLE_FEATURES` values to de deployement, triggering new pods, and the cluster is now connected to Rancher.

**Comment by reneradoi** [comment]
Hi all,

I've experienced these issues with the cattle cluster agent now as well, and the workaround mentioned by @rverchere did the trick, so thank you for that! I just wanted to follow up and ask if there is any permanent fix to this, or if this has to be applied every time the cluster agent deployment is updated (e.g. certs renewal)?

**Comment by liuzel01** [comment]
Unfortunately, i occured same issue:
finally solved using the same way above, But still unclear the reason  caused this problem
This problem seems to have been going on for a long time.

the rancher version deployed: rancher version v2.10.3
using docker-compose, image: rancher/rancher:latest
kubernetes version: v1.30.10-eks-bc803b4 on eks

**Comment by GoKael** [comment]
- name: cluster-register
  imagePullPolicy: IfNotPresent
  env:
    - name: CATTLE_FEATURES
      value: "embedded-cluster-api=false,fleet=false,managed-system-upgrade-controller=false,multi-cluster-management=false,multi-cluster-management-agent=true,provisioning-reboots=false,provisioningv2=false,rke2=false,ui-spi-cache=false"

same issue with version v2.11.3, add above NEW env fix it.
