### ISSUE TITLE
Unable to add custom hosts

### ISSUE THREAD

**Issue by piscis** [rancher/rancher#3807]
Rancher Version: 0.59

Docker Version: 0.10.2

OS: Ubuntu

Steps to Reproduce: 
Setup and run a clean install of `rancher-server` then setup and run a docker container running ubuntu 15.04. 

Try to install a agent by using the custom host tool.

Results: 
Agent will hang without progress. Agent instance will not instantiate.

docker ps shows:

CONTAINER ID        IMAGE                  COMMAND             CREATED             STATUS              PORTS               NAMES
2155e7341f01        rancher/agent:v0.9.2   "/run.sh run"       14 seconds ago      Up 13 seconds                           rancher-agent

Expected:
Agent should run and run agent-instance process then apear in server ui. I realzed that when my docker host system is 14.04 the agent will not hang and agent-instance process will run and register with rancher-server. Probally it's a problem inside of `run.sh`

**Comment by deniseschannon** [comment]
Can you explain your setup a bit more? Are you trying to run the rancher/agent on the same host of Rancher. Where does the docker container running Ubuntu 15.04 take palce? Are you trying to run the rancher/agent in that docker container?

**Comment by piscis** [comment]
Sure. I'm running the agent on a dedicated host (ubuntu 15.04) both have internet connection. Rachner Agent is located in collocation A and Rancher Server is located in collocation B. Rancher Server is behind a HA Proxy doing SSL termination. 

Both servers are connected to the internet and can see each other. Tried to reach rachner server API with curl wich was succcesful.

So from what I see its able to find the rancher server and tries to connect to it. The verification steps are fine but it then hangs with 

`docker ps`

     CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
     2155e7341f01 rancher/agent:v0.9.2 "/run.sh run" 14 seconds ago Up 13 seconds rancher-agent

`docker logs [id]` shows something like mention in #3666

    INFO: Starting agent for 6C99057D0CCB406C356A

And from there nothing happens. When I use ubuntu 14.04 + docker 1.10 everything seams to work and rancher agent initializes and bootstraps the agent instance. The host then appears just fine in the server GUI. Testing with DigitalOcean just works fine. So I thing it has something to do with Ubuntu version ... in my case.

For the Rancher Host OS I used a ubuntu 15.04 image from vultr.com.

**Comment by deniseschannon** [comment]
Docker doesn't officially support Ubuntu 15.04. https://docs.docker.com/engine/installation/linux/ubuntulinux/

Would you be able to switch to a Docker supported OS?

At this time, we haven't tested Ubuntu 15.04.

**Comment by piscis** [comment]
Thanks for the information. What I did eventually to get the agents running was to downgrade to 14.04 for the docker container hosts as you suggested. 

For me It was kind hard to debug because I didn't know that there might be a constraint on the OS version your running and that the agents just stall without an error or timeout is pretty hard to debug.

Is there a page where I can see the recommended hosting OS versions you tested against? Or is it basically the same version you pointed out docker officially supports?

**Comment by deniseschannon** [comment]
@ibuildthecloud Can you take a look and see why Ubuntu 15.04 might not work for Rancher?

**Comment by ibuildthecloud** [comment]
I'm going to close as we won't be supporting Ubuntu 15.04 because it is end of life.  https://wiki.ubuntu.com/Releases
