### ISSUE TITLE
Deleting a stack seems to randomly reorders stacks

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#3808]
If I delete a stack from the applications page, the order of the remaining stacks jumps around. Would be nice if they maintained their order.

Just another nitpick. Feel free to close.

**Comment by cjellick** [comment]
Follow up: it seems the behavior is that while the stack is in a transitioning state, it gets moved to the top of the list.

**Comment by cjellick** [comment]
ping @vincent99

**Comment by vincent99** [comment]
@cjellick Sounds like you have it sorted by state (top-right corner), and this is a feature because it becomes transitioning?
