### ISSUE TITLE
Installed Longhorn app not visible in UI

### ISSUE THREAD

**Issue by crazyelectron-io** [rancher/rancher#38094]
Im running Rancher v2.6.5 using the official Docker image (rancher/rancher:latest) and installed a 5-node Kubernetes cluster using v1.23.7+rke2r2 on local hardware (Harvester nodes).

After installing Longhon from the App charts, it doesn't show up in the installed apps. There is a message in the top banner stating "An installed application is a Helm 3 chart that was installed either via our charts or through the Helm CLI.".

I would expect that the Longhorn App installed with the UI is also visible as installed App.

**Comment by asalamintel** [comment]
I am still seeing this issue with v2.7.1

**Comment by asalamintel** [comment]
crazyelectron-io, if you were able to, how did you uninstall the apps longhorn and longhorn-crd since they are not visible in the UI?

**Comment by crazyelectron-io** [comment]
Wel it was my mistake because I did not select the correct namespace...
