### ISSUE TITLE
RKE2 Server & Agent Service Does not Start After Reboot on SLES 15.3

### ISSUE THREAD

**Issue by frank-at-suse** [rancher/rancher#38106]
Issue details here: https://github.com/rancher/rke2/issues/3001

This only occurs with RKE2 clusters on SLES/Leap 15.3 & 15.4 provisioned via Rancher.  In short, a Rancher-provisioned RKE2 cluster is not placing the rke2-server or agent service in `/etc/systemd/system` - provisioning is dropping them into `/usr/local/lib `instead.

**Comment by cwayne18** [comment]
cc @snasovich this has been coming up quite a bit again FYI

**Comment by snasovich** [comment]
@rancher-max , assigning to you to validate on RKE2 versions to be released in Dec 2022 patches. LMK if this is incorrect.

**Comment by alexdepalex** [comment]
I can confirm it works with Rancher v2.6.9 and v1.24.9-rc4+rke2r1. RKE2 is installed in `/opt/rke2` and unit files are located in `/etc/systemd/system` for rke2 agent and server and rancher-system-agent. So all looks good.

**Comment by est-suse** [comment]
Validated the new files are created under /etc/systemd/system

TESTED on SLE 15.3 with a custom Cluster

```
sudo ls /etc/systemd/system
afterburn-sshkeys.target.requires  dbus-org.freedesktop.nm-dispatcher.service  multi-user.target.requires   network.service		  rke2-agent.service	syslog.service
basic.target.wants		   default.target.wants			       multi-user.target.wants	    rancher-system-agent.env	  rke2-server.service	timers.target.wants
bootmsg.service			   getty.target.wants			       network-online.target.wants  rancher-system-agent.service  sysinit.target.wants

```


Not under /usr/local/lib/systemd/system
```
 sudo ls /usr/local/lib/systemd/system
ls: cannot access '/usr/local/lib/systemd/system': No such file or directory
```


![image](https://user-images.githubusercontent.com/106194120/208567444-2b207eb6-7f89-4df6-a16a-6547c012e142.png)

**Comment by Martin-Weiss** [comment]
How will this fix deal with clusters installed before? Will the upgrade via Rancher „correct“ the wrong locations or does this only fix „new deployments“?

**Comment by alexdepalex** [comment]
@Martin-Weiss It won't. But the new locations will be used when you upgrade an existing cluster to a release that incorporates the fix.

**Comment by Martin-Weiss** [comment]
@alexdepalex  - where do we document all the workarounds we needed and with which patchlevel they need to be removed? ;-)

**Comment by alexdepalex** [comment]
@Martin-Weiss Well, you have to ask internally for that 😜

**Comment by alexdepalex** [comment]
@Martin-Weiss Well, you have to ask internally for that. I'm just an end-user 😜

**Comment by rancher-max** [comment]
The fix actually should deal with clusters installed previously. We validated in both an upgrade of a broken cluster (one that was rebooted and therefore rke2-server wasn't starting) and an upgrade of a working one (that just hadn't been rebooted prior to upgrading) and in both of those cases, the new service file was picked up and used, and the old one ignored 🎉 

This should be based on the way systemd loads files: https://www.freedesktop.org/software/systemd/man/systemd.unit.html. If desired or if there has been any customization made there, users can cleanup the previous file after upgrading to any of `v1.22.17+rke2r1`, `v1.23.15+rke2r1`, and `v1.24.9+rke2r1`. This issue should be documentation enough in that case in my opinion for anyone encountering this issue after upgrading.

**Comment by alexdepalex** [comment]
@Martin-Weiss The services files are recreated when you restart the `rancher-system-agent`. So any customizations after the initial deployment will be overwritten.

**Comment by Martin-Weiss** [comment]
> @Martin-Weiss The services files are recreated when you restart the `rancher-system-agent`. So any customizations after the initial deployment will be overwritten. At least, as long as they have the same name as the original unit files.

But they are not re-created  / overwritten in /etc/systemd/system - so the ones that I copied there as workaround for the time beeing will still have higher priority and I have to delete them from there.. (see my current workaround https://github.com/Martin-Weiss/rke-cluster/blob/a525de747064ea37ecfba75b3221ade94d6d08ef/rke-cluster.sh#L88 )

**Comment by alexdepalex** [comment]
Actually, they are. It's happening here https://github.com/rancher/rke2/blob/master/install.sh#L372
