### ISSUE TITLE
terraform-provider-rancher2 to support kubelet-args under machine_selector_config

### ISSUE THREAD

**Issue by dbravo0531** [rancher/rancher#38112]
**Is your feature request related to a problem? Please describe.**
I'm trying to user the terraform rancher2_cluster_v2 module to build an rke2 cluster in Rancher 2.6.5. I have figured out most of the settings and things are making sense however I can not figure out how to add kubelet arguments as I need to pass an array into a string field. Here is a condensed version of my terraform. resource "rancher2_cluster_v2" "cluster" { name = "sand011" kubernetes_version = "v1.22.9+rke2r2" rke_config { machine_selector_config { config = { profile = "cis-1.6" cloud-provider-name = "external" kubelet-arg = "--protect-kernel-defaults" } } } } The kubelet-arg = "--protect-kernel-defaults" causes rancher to treat every char as an array element which makes it look like this in rancher. machineSelectorConfig: - config: kubelet-arg: - '-' - '-' - p - r - o - t - e - c - t - '-' - k - e - r - "n" - e - l - '-' - d - e - f - a - u - l - t - s If I try to pass in an array instead of a string terraform yells at me with this error. │ Inappropriate value for attribute "config": element "kubelet-arg": string required. So is there some special way to pass in the kubelet args from terraform? Also I know that protect-kernel-defaults can be set in the machine_global_config settings, it is just an example that I noticed the string/array behavior with.

Also this format causes only the last kubelet-arg to get applied. The others are overridden and shown as an array with ever char as an element of it like I mentioned in the original text of the issue.
machine_selector_config {
config =
{ cloud-provider-name = "external" kubelet-arg = "cloud-provider=external" kubelet-arg = "protect-kernel-defaults=true" }
}

**Describe the solution you'd like**
To be able to add Kubelet-args under machine_selector_config

Workaround:
Is workararound available and implemented? yes
What is the workaround:Moving the kubelet-args to the the machine_global_config does "work" however now the rancher UI does not reflect those settings. They are pushed down to the nodes and applied however.

**Comment by sass1997** [comment]
Any workarounds?
