### ISSUE TITLE
View Logs feature no longer works after upgrading to 2.6.5

### ISSUE THREAD

**Issue by telderfts** [rancher/rancher#38118]
**Rancher Server Setup**
- Rancher version: 2.6.5
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): EKS
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: 1.21
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Imported

**User Information**
- What is the role of the user logged in? Admin

**Describe the bug**
When looking at a pod under workload on Rancher 2.6.4 we used to be able to see the logs on a per pod basis. After upgrading to 2.6.5 this no longer works. Just a grey screen appears where the logs used to show up.

**Result**

**Expected Result**
View logs feature works after upgrade from 2.6.4 to 2.6.5

**Comment by martialblog** [comment]
Might be a duplicate. See https://github.com/rancher/rancher/issues/38082

**Comment by Rancheroo** [comment]
This is a duplicate. Workaround and replication steps provided in [38082](url)
