### ISSUE TITLE
Ability to set "assignServiceIpAddress" from UI when creating service.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#3812]
With https://github.com/rancher/rancher/issues/2817 issue addressed , VIP will be assigned to the service only when "assignServiceIpAddress" (new param) is set to true on the service. 

Provide ability  to set "assignServiceIpAddress" from UI when creating service.

**Comment by vincent99** [comment]
Darren says no(t yet)

**Comment by MOZGIII** [comment]
How about now?

**Comment by vincent99** [comment]
Not relevant for 2.0.
