### ISSUE TITLE
Intermittent LKE cluster provisioning failures

### ISSUE THREAD

**Issue by LBGarber** [rancher/rancher#38120]
**Rancher Server Setup**
- Rancher version: v2.6.4
   
**Describe the bug**
When creating an LKE cluster using the Rancher UI, there will occasionally be provisioning failures that put Rancher in a perpetual retry loop. As these intermittent failures do not result in a cluster clean-up on Linode's side, every subsequent retry fails with a `label already in use` error. 

**To Reproduce**
1. Attempt to provision an LKE cluster
2. Encounter an intermittent LKE cluster provisioning error (intermittent)
3. Observe an infinite provisioning retry loop

**Result**
The cluster is stuck retrying creation and will never successfully create.

**Expected Result**
The cluster provisions as normal.

**Comment by snasovich** [comment]
@LBGarber , your PR has been merged. Once updated `v2.6-head` tag is up for `rancher/rancher`, could you please validate it's working as expected?

**Comment by LBGarber** [comment]
@snasovich Everything is working as expected and the intermittent provisioning errors seem to be gone :slightly_smiling_face:

**Comment by sowmyav27** [comment]
Closing this issue per this comment - https://github.com/rancher/rancher/issues/38120#issuecomment-1169317538
