### ISSUE TITLE
Don't show catalog name in drop-down if no kubernetes templates

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3813]
Version - master 3/7

Steps to Reproduce: 
1.  Create a kubernetes environment
2.  Go to catalog under kubernetes
3.  Select the Community or Library catalog from drop-down

Results: 
There are no catalogs templates showing in list

Expected:
Would be nice if there are no templates that will show up, that we don't show the catalog in the drop-down

**Comment by vincent99** [comment]
No longer applicable in 1.4.
