### ISSUE TITLE
Updates to RKE1 Provisioning testing

### ISSUE THREAD

**Issue by igomez06** [rancher/rancher#38135]
**Things to update**

- Move hosted provisioning test into it's own directory it doesn't belong in rke2
- The rke1 and rke2 files have the package name as `package provisioning` it should be `package rke1` and `package rke2` respectively
- Test standard user as well, it's only testing admin user
- The cluster := &management.Cluster instantiation in line 80 needs to be put in extensions as constructor similar to rke2
- Same with node pool, so we are only going to test all roles, so no need to test different roles and number of node per pool? Regardless this should be in a constructor
- Absolutely no` fmt.Println` there is one on line 135

**Comment by markusewalker** [comment]
PR: https://github.com/rancher/rancher/pull/38166

**Comment by markusewalker** [comment]
Installed.
