### ISSUE TITLE
In dark theme, can't see selected stack/service/host/container

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3814]
Version - master 3/7

Steps to Reproduce: 
1.  Add a bunch of hosts (or stacks, services, containers)
2.  Click on name to get to details page
3.  Click on drop-down to see rest in list
4.  Move mouse to select a different host (or stack, service, container)

Results:   When I move my mouse to select a different host, the currently selected host turns to a white background with light grey text.  I can't see it and it doesn't look very good
![image](https://cloud.githubusercontent.com/assets/11514927/13595547/81e30b5e-e4c9-11e5-9bf2-026ac9ba1b36.png)

Expected: Should be able to see text

**Comment by lvuch** [comment]
resolved in https://github.com/rancher/ui/pull/515

**Comment by tfiduccia** [comment]
Version - master 3/9
Verified fixed
