### ISSUE TITLE
[Question] How does Loadbalance update config when scaling targeted services?

### ISSUE THREAD

**Issue by phucvinh52** [rancher/rancher#3815]
Hi @alena1108 
Could you help me to understand the whole process which loadbalancer does to update its config when one of targeted service start scaling?
Thank.

**Comment by CBR09** [comment]
Đắng!

**Comment by vincent99** [comment]
At what level of detail/focus?  The high level is just a new config file is generated by catle when the list of target IPs, it's sent down to all the balancer instances and their configs are reloaded.

**Comment by phucvinh52** [comment]
Hi @vincent99 ,
Thanks for your answer. Could you tell me balancer is how updated config at low level (as detailed as possible).
Have a good day for you.

**Comment by illyul** [comment]
+1

**Comment by CBR09** [comment]
+1
I'm also wonder how the load balancer auto update config when scale in/out at low level.

**Comment by alena1108** [comment]
@phucvinh52 @illyul @CBR09 

Haproxy config update can be triggered by several processes:

* instance stop/start/create/destroy - can be triggered by target service scaleUp/scaleDown, as well as operation on individual instance
* target service deactivate
* load balancer ssl certificate updates
* host name routing rules updates
* lb service links get updated (new links added, old links removed)

When any of the above happens, our config framework signals that change needs to be applied, we re-generate haproxy config and the new config gets downloaded by lb instance, followed by haproxy process reload.
Note that we build config from scratch on any change; code responsible for config population is here: https://github.com/rancher/cattle/blob/b958d1eaf9506fb0049a7befe1603a32d641aca0/code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/impl/LoadBalancerInfoFactory.java

Let me know what other details you are interested in, and I would put in more details.

**Comment by deniseschannon** [comment]
If there are more questions, please let us know.
