### ISSUE TITLE
Write ERD for multiple registry support

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#38150]
Create an ERD to cover the following workflows

 * Supporting multiple registries and the user experience
 * Upgrade process of charts between two registries
 * Migration from current registry to new registry
 * Airgap use cases

**Comment by prachidamle** [comment]
@PennyScissors Please check with @aiyengar2 for any issues you face while handling this and also with @rosskirkpat if you have questions with how he plans to add new “product registry” that apps/charts can use
