### ISSUE TITLE
Upgrade from k8s v1.23 to v1.24 fails due to restarting kubelet. 

### ISSUE THREAD

**Issue by vivek-infracloud** [rancher/rancher#38160]
**Rancher Server Setup**
- Rancher version: v2.6.6 --->  v2.6.7-rc1
- Installation option (Docker install/Helm Chart): Docker

**Information about the Cluster**
- Kubernetes version: v1.23.7-rancher1-1
- Cluster Type (Local/Downstream): Downstream

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom).
Admin
   
**Describe the bug**

Observed this issue while testing upgrade checks for k8s v1.24.
Upgrade from k8s v1.23 to v1.24 fails with kubelet restarting and showing the following error in the log.

**To Reproduce**
1. Create a rancher server v2.6.6
2. Provision a downstream custom cluster v1.23.
3. Upgrade rancher to latest v2.6.7-rcX version.
4. Upgrade downstream cluster v1.23 to v1.24
5. Notice control-plane remains in unavailable state.

**Result**

Cluster upgrade to v1.24 fails. Cluster remains in Updating state with Control plane failed to upgrade error message. 

**Expected Result**

Cluster upgrade from k8s v1.23 to v1.24 succeeds. 

**Screenshots**

Error message on cluster nodes.
![Screenshot from 2022-07-01 13-40-51](https://user-images.githubusercontent.com/83208989/176913847-8042d29b-e685-4f47-ac7d-6fac14ab3ab9.png)

Kubelet on control plane keeps restarting. (possibly on every node, did not check all the nodes).
![Screenshot from 2022-07-01 15-53-20](https://user-images.githubusercontent.com/83208989/176913841-4c95d0c4-5c74-4003-8186-dffc00e06a1f.png)

**Additional context**

kubelet container on Control Plane keeps restarting, and the kubelet container log shows the following error.
`Error: failed to run Kubelet: unable to determine runtime API version: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial unix: missing address"`

**Comment by sowmyav27** [comment]
This is because `enable_cri_dockerd` is set to false and it fails to provision 1.24 cluster completely. Had an offline discussion with @kinarashah @snasovich. Needs more discussion -  if we must set it to `true` by default on cluster update or not.

**Comment by kinarashah** [comment]
Discussed offline: rancher will turn on `enable_cri_dockerd` by default on upgrade to v1.24. To force disable it, a new annotation/field will be required to set on the cluster object. For now, please set the `enable_cri_dockerd` to `true` before upgrades to workaround this issue.

**Comment by kinarashah** [comment]
Available to test after build is green https://drone-publish.rancher.io/rancher/rancher/8059 with v2.6-head. 

Changes: 
- All 1.24 clusters have cri dockerd enabled by default, both on creates and updates 
- Users can `"io.cattle.cluster.cridockerd.enable"` annotation on cluster, the annotation will override the default behavior. If the annotation is set to false and `enable_cri_dockerd` is set to true, annotation overrides the field/flag behavior and `enable_cri_dockerd` will be updated to false. Clusters wouldn't come up correctly if cri dockerd is disabled, that's expected unless proper docker runtime is provided.

**Comment by rishabhmsra** [comment]
Validated on rancher v2.6-head(2c21373)

Steps followed:
- On rancher v2.6.6, provisioned downstream v1.23 k8s custom clusters on all network providers.
- Upgraded the rancher server to v2.6-head(2c21373)
- Upgraded downstream clusters to k8s v1.24.2-rancher1-1.
- All clusters came into Active state.

Result:
- Clusters upgraded successfully to k8s v1.24 and came into Active state, hence closing the issue.
![clusters-up](https://user-images.githubusercontent.com/36376154/178749733-0d46558e-70d2-4e52-adc0-f55f55036053.png)
