### ISSUE TITLE
Files changed by go fmt do not cause build failure

### ISSUE THREAD

**Issue by MbolotSuse** [rancher/rancher#38167]
**Rancher Server Setup**
- Rancher version: 2.5.14, 2.5.15 (at minimum)
- Installation option (Docker install/Helm Chart): N/A Issue in build

**Describe the bug**
When the build process is not able to download golangci ([relevant code](https://github.com/rancher/rancher/blob/v2.5.15/Dockerfile.dapper#L32)), it instead runs `go fmt` on all code and skips an exit check for a dirty repo ([relevant code](https://github.com/rancher/rancher/blob/v2.5.15/scripts/validate#L11-L14)). 

This prevents the build from failing when a user has not properly ran `go fmt` on their code (since the check for a dirty repo which fails the build appears to be no longer run). In addition, since the code is different in the pipeline after `go fmt` is run, rancher artifacts built in the CI have a version which is marked as `dirty`.

**To Reproduce**
Run the CI pipeline for one of the affected versions above.

**Result**
Rancher agent version is suffixed with `dirty`

**Expected Result**

Agent version should not be suffixed with `dirty`.

**Additional context**
- Related to rancher/tasks#203
- The most simple fix for this issue is to just ensure that the golangci utility is downloaded as expected. This was achieved for 2.5 with rancher/rancher#38161 and for 2.6 with rancher/rancher#35429
- Realistically, the build should be fixed to fail if any given command fails. This will help to ensure similar behavior does not occur if the url is changed again in the future.

**Comment by samjustus** [comment]
only a drone change - should be fine to past DC cc @sowmyav27

**Comment by steffantucker** [comment]
Build successfully failed in test PR https://github.com/rancher/rancher/pull/39244 because of a file that was not go-fmt-ed.
<img width="476" alt="Screen Shot 2022-10-06 at 12 54 06 AM" src="https://user-images.githubusercontent.com/40306798/194234329-56ee0964-a9a6-40ee-a834-55d74b74e918.png">
