### ISSUE TITLE
Unable to provision downstream clusters in Rancher HA Setup

### ISSUE THREAD

**Issue by rishabhmsra** [rancher/rancher#38162]
**Rancher Server Setup**
- Rancher version: v2.6-head(14572ee)
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1 v1.24.2

**Information about the Cluster**
- Kubernetes version: v1.24.2-rancher1-1
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Custom and Node Driver

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Admin
  - If custom, define the set of permissions:

   
**Describe the bug**
- Downstream custom or node driver clusters fails to provision on rancher HA setup with following error : `Failed to initialize new kubernetes client: stat management-state/rke/rke-3333251940/kube_config_cluster.yml: no such file or directory`
- **Note : Downstream 1.24 Node driver Cluster provisioning is successful on docker installation of rancher v2.6-head(14572ee)**

**To Reproduce**
 
- Deploy rancher v2.6-head(14572ee) HA setup with local cluster as RKE1 k8s `v1.24.2-rancher1-1`
- Provision downstream RKE1, custom clusters (3etcd, 2cp, 3w) -> in this case these AMIs are used(ami-0960ab670c8bb45f3, ami-0452941f41a1b0608)
- Or deploy node driver clusters.
- Cluster will get stuck into provisioning state.

**Result**
- Cluster gets stuck into Provisioning state with error: `Failed to initialize new kubernetes client: stat management-state/rke/rke-3333251940/kube_config_cluster.yml: no such file or directory`
- Provisioning logs:
```
...
[INFO ] [/etc/kubernetes/kube-api-authn-webhook.yaml] Successfully deployed authentication webhook config Cluster nodes
--
9:16:01 pm | [INFO ] [/etc/kubernetes/audit-policy.yaml] Successfully deployed audit policy file to Cluster control nodes
9:16:01 pm | [INFO ] [reconcile] Reconciling cluster state
9:16:01 pm | [INFO ] [reconcile] This is newly generated cluster
9:16:01 pm | [INFO ] Pre-pulling kubernetes images
9:16:01 pm | [INFO ] Kubernetes images pulled successfully
9:16:01 pm | [ERROR] failed to initialize new kubernetes client: stat management-state/rke/rke-2824063194/kube_config_cluster.yml: no such file or directory
```

**Expected Result**
- Downstream clusters should provision successfully and come into Active state.

**Screenshots**

**Additional context**

**Comment by brudnak** [comment]
### Reproduction Environment

| Component                 | Version / Type                                                                     |
| ------------------------- | ---------------------------------------------------------------------------------- |
| Rancher version           | v2.6.7-rc1                                                                         |
| Pre release page link     | https://github.com/rancher/rancher/releases/tag/v2.6.7-rc1                         |
| Rancher commit link       | https://github.com/rancher/rancher/commit/14572eea6208922c45a38e477f3adc4944f90c96 |
| Installation option       | helm                                                                               |
| If Helm Chart k8s cluster | EKS v1.22.10-eks-84b4fe6                                                           |
| Cert Details              | let's encrypt                                                                      |
| Helm version              | v2.16.8-rancher1                                                                   |
| Downstream cluster type   | rke1 linode                                                                        |
| Downstream K8s version    | v1.23.8-rancher1-1                                                                 |
| Logged in user role       | administrator                                                                      |
| Browser type              | google chrome                                                                      |
| Browser version           | 103.0.5060.53 (Official Build) (x86_64)                                            |

**ADDITIONAL SETUP**

- eksctl installation commands used

```shell
eksctl create cluster \
  --name $CLUSTER_NAME \
  --version 1.22 \
  --region us-east-2 \
  --nodegroup-name $NODE_GROUP_NAME \
  --nodes 3 \
  --nodes-min 1 \
  --nodes-max 4 \
  --managed
```

- Helm commands for Rancher installation:

```shell
helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=$HOSTNAME_VAR \
  --set bootstrapPassword=admin \
  --set ingress.tls.source=letsEncrypt \
  --set letsEncrypt.email=$EMAIL_VAR \
  --set letsEncrypt.ingress.class=nginx \
  --version 2.6.7-rc1 \
  --set extraEnv\[0\].name="CATTLE_PROMETHEUS_METRICS" --set-string extraEnv\[0\].value=true
```

## Reproduction steps

1. Create a Rancher HA EKS cluster using `eksctl`
2. Install the Rancher chart onto the EKS cluster
3. Create a downstream Linode cluster
4. Down stream cluster never provisions successfully

## Additional Info
<img width="1448" alt="2022-07-05_15-52-51" src="https://user-images.githubusercontent.com/40877149/177431370-e8068783-5886-47ee-80d7-ac28aca053d2.png">

#### Rancher error logs

```log
2022/07/05 22:25:18 [ERROR] Failed to connect to peer wss://<REDACTED>/v3/connect [local ID=<REDACTED>]: websocket: bad handshake
W0705 22:25:22.437322 33 warnings.go:80] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
```

#### Down stream rke1 linode provisioning logs

```log
[INFO ] Initiating Kubernetes cluster
[INFO ] Successfully Deployed state file at [management-state/rke/rke-3319920594/cluster.rkestate]
[INFO ] Building Kubernetes cluster
[INFO ] [dialer] Setup tunnel for host [<REDACTED_IP>]
[ERROR] Failed to set up SSH tunneling for host [<REDACTED_IP>]: Can't retrieve Docker Info: error during connect: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/info": can not build dialer to [c-<REDACTED_SHORT_UUID>:m-<REDACTED_SHORT_UUID>]
[ERROR] Removing host [<REDACTED_IP>] from node lists
[ERROR] Cluster must have at least one etcd plane host: failed to connect to the following etcd host(s) [<REDACTED_IP>]
```

#### Cluster management overview error message

```log
Cluster must have at least one etcd plane host: failed to connect to the following etcd host(s) [<REDACTED_IP>]
```

```log
Cannot proceed with upgrade of controlplane since 4 host(s) cannot be reached prior to upgrade
```

## RESULTS

#### :white_check_mark: Expected
Expected to be able to successfully deploy down stream rke1 linode clusters

#### :x: Actual
Clusters go into an error state and never come up active

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `f40e542`**

- Rancher HA - 1.24 local RKE1 cluster using `v1.3.13-rc3`
- RKE1 1.24 downstream cluster come sup Active, but `timeout getting credential for cluster group` seen in continuous Delivery page for this cluster --> 
- RKE2 downstream cluster - 1.23.8-RKE2 does not come up Active.
- Errors seen in Rancher logs:
```
2022/07/06 03:38:02 [ERROR] error syncing '_all_': handler user-controllers-controller: failed to start user controllers for cluster c-m-mfhzj6w6: ClusterUnavailable 503: cluster not found, requeuing
2022/07/06 03:38:10 [INFO] cri-dockerd is enabled for cluster version [v1.24.2-rancher1-1]
2022/07/06 03:39:12 [INFO] cri-dockerd is enabled for cluster version [v1.24.2-rancher1-1]
2022/07/06 03:39:20 [ERROR] Failed to handle tunnel request from remote address 10.42.1.4:34690 (X-Forwarded-For: 18.224.63.142): response 401: failed authentication
2022/07/06 03:39:21 [INFO] cri-dockerd is enabled for cluster version [v1.24.2-rancher1-1]
```
and
```
2022/07/06 03:35:53 [ERROR] error syncing 'p-8mdtt/creator-project-owner': handler cluster-prtb-sync: couldn't ensure service account impersonator: failed to get secret for service account: cattle-impersonation-system/cattle-impersonation-user-4n6jv, error: timed out waiting for the condition, requeuing
2022/07/06 03:35:53 [ERROR] error syncing 'c-q69rl/creator-cluster-owner': handler cluster-crtb-sync: couldn't ensure service account impersonator: failed to get secret for service account: cattle-impersonation-system/cattle-impersonation-user-4n6jv, error: timed out waiting for the condition, requeuing
```

**Comment by sowmyav27** [comment]
On 2.6-head commit id: `f40e542`

- Rancher HA - 1.24 local RKE1 cluster using v1.3.13-rc3
- RKE2 EC2 cluster comes up Active - 1 etcd, 1 cp and 1 worker node
- Logging separate issues for [fleet controller error](https://github.com/rancher/rancher/issues/38199) and the [impersonation error](https://github.com/rancher/rancher/issues/38198)
