### ISSUE TITLE
Error request spot instance: InvalidParameter with m6 instance type

### ISSUE THREAD

**Issue by Soft-jp** [rancher/rancher#38176]
**Rancher Server Setup**
- Rancher version: v2.6.6
- Installation option (Docker install/Helm Chart): Docker install

**Information about the Cluster**
- Kubernetes version: v1.23.7
- Cluster Type (Local/Downstream):
    RKE2 + cluster with EC2 instances

**User Information**
- Admin

   
**Describe the bug**
After setting up and creating the cluster. There is an error message when creating the nodes. 
IAM is well set up. I have no problem with other types of instances like t3, m5 or r5

Failed creating server xxx of kind (Amazonec2Machine) for machine xxx in infrastructure provider: 
CreateError: Trying to access option which does not exist THIS ***WILL*** CAUSE UNEXPECTED BEHAVIOR Type assertion did not go smoothly to string for key Running pre-create checks... 
Creating machine... (xxx) Launching instance... (xxx) 
Creating New SSH Key (xxx) 
...
Error creating machine: Error in driver during machine creation: Error request spot instance: InvalidParameter: 'instance' is not a valid taggable resource type for this operation. 
status code: 400, request id: 373e55c6-682f-4660-b1e6-80b54e2ea5cb The default lines below are for a sh/bash shell, you can specify the shell you're using, with the --shell flag.

**To Reproduce**
- Create a new cluster RKE2 with provision Amazon EC2.
- Create 2 pool with m6g.xlarge instance type and uncheck "Request Sopt Instance" (I also tested with the spot instances, there is the same message)

**Result**
Error during machine creation with the above error message.

**Expected Result**
The nodes should be created

**Additional context**

**Comment by niusmallnan** [comment]
probably duplicate of #37775

**Comment by Soft-jp** [comment]
indeed the message is identical but I am in RKE2 and the problem is identical with or without spot instance.

I tried to switch to a v2.6-head version but the problem is the same.
The problem is on the m6 instance type --> problem and m5 works fine (spot instance or not).

**Comment by kimsw61** [comment]
i can't find even m6, i need m6g or t4g instance such like graviton instance.

how do i set node group like m6g or t4g using Rancher UI?

and If cannot set in Rancher UI, how do i set?

**Comment by Soft-jp** [comment]
Sorry I meant m6g...
I just redid a test with the last stable version and I have the same message.

here is the message displayed :
Failed creating server [fleet-default/test-migration-pool2-5e552c9d-vdcjh] of kind (Amazonec2Machine) for machine test-migration-pool2-7b77cd6df8-6fbh4 in infrastructure provider: CreateError: Trying to access option which does not exist THIS ***WILL*** CAUSE UNEXPECTED BEHAVIOR Type assertion did not go smoothly to string for key Running pre-create checks... Creating machine... (test-migration-pool2-5e552c9d-vdcjh) Launching instance... (test-migration-pool2-5e552c9d-vdcjh) Creating New SSH Key (test-migration-pool2-5e552c9d-vdcjh) creating key pair: test-migration-pool2-5e552c9d-vdcjh-hcVrU (test-migration-pool2-5e552c9d-vdcjh) configuring security groups in vpc-0d5c6bcba28e4a436 (test-migration-pool2-5e552c9d-vdcjh) found existing security group (rancher-nodes) in vpc-0d5c6bcba28e4a436 (test-migration-pool2-5e552c9d-vdcjh) configuring security group authorization for 0.0.0.0/0 (test-migration-pool2-5e552c9d-vdcjh) launching instance in subnet subnet-070737bea34cf5825 (test-migration-pool2-5e552c9d-vdcjh) error encountered during instance creation: Error request spot instance: InvalidParameterValue: The architecture 'arm64' of the specified instance type does not match the architecture 'x86_64' of the specified AMI. Specify an instance type and an AMI that have matching architectures, and try again. You can use 'describe-instance-types' or 'describe-images' to discover the architecture of the instance type or AMI. (test-migration-pool2-5e552c9d-vdcjh) status code: 400, request id: f89febb5-4c6c-4b4a-851f-efaf1ad43e38 (test-migration-pool2-5e552c9d-vdcjh) Missing instance ID, this is likely due to a failure during machine creation (test-migration-pool2-5e552c9d-vdcjh) deleting key pair: test-migration-pool2-5e552c9d-vdcjh-hcVrU (test-migration-pool2-5e552c9d-vdcjh) Could not retrieve EC2 instance while attempting key-pair deletion, will attempt to delete locally stored key test-migration-pool2-5e552c9d-vdcjh-hcVrU Error creating machine: Error in driver during machine creation: Error request spot instance: InvalidParameterValue: The architecture 'arm64' of the specified instance type does not match the architecture 'x86_64' of the specified AMI. Specify an instance type and an AMI that have matching architectures, and try again. You can use 'describe-instance-types' or 'describe-images' to discover the architecture of the instance type or AMI. status code: 400, request id: f89febb5-4c6c-4b4a-851f-efaf1ad43e39 The default lines below are for a sh/bash shell, you can specify the shell you're using, with the --shell flag.
