### ISSUE TITLE
vSphere CPI Support for 1.24

### ISSUE THREAD

**Issue by phillipsj** [rancher/rancher#38187]
**Is your feature request related to a problem? Please describe.**

 vSphere CPI chart just released an official image for 1.24, 1.24.0. This will need to be implemented in our charts to bring in official 1.24 support and provide skew policy support for 1.25.

**Describe the solution you'd like**

Update the chart to include the new version and tweak the semver ranges.

# Checklist for items that need completed

- [x] Update Image-mirror repo
- [x] Update manifests in rancher/vsphere-charts
- [x] Notify about chart "release" (reference @brandond @cwayne18 and @rancher-max in team-release-rancher-bits that new chart version is available)
- [x] Update chart in rancher/charts
- [x] Update chart in rancher/rke2-charts (RKE2 team)
- [x] Updated RKE2 to consume new chart (RKE2 team)

**Comment by snasovich** [comment]
Since 1.24.1 is now also available as of couple days ago, we may want to update to it too. And then coordinate updates to other charts as per the checklist in this issue.

**Comment by jiaqiluo** [comment]
Moved back to "working" because we need to update charts in the Update chart in rancher/charts, rancher/rke2-charts, and rancher/RKE2.  
See the checklist in the issue for progress.

**Comment by annablender** [comment]
@TJPatel is working with a customer who has the problem 

```
Pink Triangle Press can't delete volumes or get kubectl top from their Rancher cluster ever since upgrading to kubernetes 1.24.4 but other commands appear to work (I see metrics server is down and out) since they are using vSphere CPI on Rancher 2.6.8.
```

They are waiting for vSphere CPI support for 1.24 to resolve this.

**Comment by annablender** [comment]
See test template in associated CSI issue [here](https://github.com/rancher/rancher/issues/38188#issuecomment-1322495276).

**Comment by vivek-infracloud** [comment]
vSphere CPI chart didn't install successfully v1.24.8.

Testing steps:
1. Created a rancher server v2.7.0 on vSphere.
2. Created a downstream node driver cluster with 1cp, 1worker and 1 etcd node.
3. Installed a CPI chart v101.1.0+up1.4.1
  i. Installation process finished, however, the cloud provider was not set on the node.

CPI chart didn't install successfully, hence reopening the issue.

**Comment by vivek-infracloud** [comment]
vSphere CPI chart install successfully on v1.24.8.

Testing steps:
1. Created a rancher server v2.7.0 on vSphere.
2. Created a downstream node driver cluster with 1cp, 1worker and 1 etcd node.
3. Installed a CPI chart v101.1.0+up1.4.1
4. Made sure the Provider ID is set.

CPI chart install successfully, hence closing the issue.
