### ISSUE TITLE
Feature Request - API - Graphite.Host

### ISSUE THREAD

**Issue by Rucknar** [rancher/rancher#3819]
Low priority, wanted to get this on the radar if at all possible...

`v1/settings/graphite.host` is super-useful for us gathering statistics out of our Rancher instances. However after using it for a while in a few environments, i feel a few updates to how it works could make it even more useful. 

* Enable setting to make use of the rancher-dns. Useful when pointing it to a managed rancher node.
* Enable the value to be updated without requiring a server restart to take effect.
* Allow it to be updated through the API with a curl command. This works when browsing the UI but when i try run it in by copying the curl command out i get errors.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v0.59.0` Cattle: `v0.148.0` UI: `v0.90.0` |
|Access|`github` `admin`|
|Route|`null`|

**Comment by vincent99** [comment]
It's a server setting so using internal container DNS doesn't really make any sense (which environment?); you can use the external-dns (Route53, etc) to create a public entry that the setting could then use.

Updating without restart seems reasonable...

The UI **is** the API.  Anything that's possible can be done with curl or any other http client.  Show us the request you're making and response you're getting back.  There's probably something simple wrong.

**Comment by Rucknar** [comment]
* Good point, will have to come up with something else for non-cloud setups.

The request i'm taking out of the curl command it gives me, for example:
```
curl -u "${CATTLE_ACCESS_KEY}:${CATTLE_SECRET_KEY}" \
-X PUT \
-H 'Accept: application/json' \
-H 'Content-Type: application/json' \
-d '{"activeValue":"", "id":"1as13", "name":"graphite.host", "source":"Database", "value":"example"}' \
'http://52.48.131.67:8080/v1/activesettings/1as13'
```
I'm trying to run the above from a container with the following labels set, without joy sadly.

```
      io.rancher.container.create_agent: true
      io.rancher.container.agent.role: environment
```

**Comment by Rucknar** [comment]
I'm going to close this, after some thought.... i'm not sure the graphite endpoint is the best way to go. It might be easier to expose the metrics to URL, something that could be scraped. Would avoid the setup issues and the errors in the logs when graphite isn't there. Closing.
