### ISSUE TITLE
`handler import-cluster: timeout getting credential for cluster group, requeuing` error in fleet-controller pods

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#38199]
**Rancher Server Setup**
- Rancher version: 2.6head `f40e542`
- Installation option (Docker install/Helm Chart): Helm

**Information about the Cluster**
- Kubernetes version: 1.24.2
- Cluster Type (Local/Downstream): local - 1.24.2 RKE1

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) : Admin

   
**Steps to reproduce:**

- RKE1 1.24 downstream cluster come sup Active, but `timeout getting credential for cluster group` seen in continuous Delivery page for this cluster 
- On cluster management page --> Cluster details --> related resources --> Cluster object is seen in Wait Applied/Error state
- Errors seen in Rancher logs:
```
2022/07/06 03:38:02 [ERROR] error syncing '_all_': handler user-controllers-controller: failed to start user controllers for cluster c-m-mfhzj6w6: ClusterUnavailable 503: cluster not found, requeuing
2022/07/06 03:38:10 [INFO] cri-dockerd is enabled for cluster version [v1.24.2-rancher1-1]
2022/07/06 03:39:12 [INFO] cri-dockerd is enabled for cluster version [v1.24.2-rancher1-1]
2022/07/06 03:39:20 [ERROR] Failed to handle tunnel request from remote address 10.42.1.4:34690 (X-Forwarded-For: 18.224.63.142): response 401: failed authentication
2022/07/06 03:39:21 [INFO] cri-dockerd is enabled for cluster version [v1.24.2-rancher1-1]
```
- And errors in fleet-controller pod:
```
time="2022-07-06T04:37:17Z" level=error msg="error syncing 'fleet-local/local': handler import-cluster: secrets \"local-cluster\" not found, requeuing"
--
Tue, Jul 5 2022 9:37:24 pm | time="2022-07-06T04:37:24Z" level=error msg="error syncing 'fleet-default/sowmya-linode-rke2': handler import-cluster: timeout getting credential for cluster group, requeuing"
Tue, Jul 5 2022 9:37:46 pm | time="2022-07-06T04:37:46Z" level=error msg="error syncing 'fleet-default/c-q69rl': handler import-cluster: timeout getting credential for cluster group, requeuing"
Tue, Jul 5 2022 9:37:56 pm | time="2022-07-06T04:37:56Z" level=error msg="error syncing 'cattle-fleet-system/fleet-controller': handler global-config: waiting on secret for service account cattle-fleet-system/fleet-controller-bootstrap, requeuing"
```

**Comment by kinarashah** [comment]
Fleet errors will be resolved separately via https://github.com/rancher/fleet/pull/850

**Comment by markusewalker** [comment]
Verified this is addressed in https://github.com/rancher/rancher/commit/cfba0bc4fe19177cef627d36ad86744b62e5e751.

**ENVIRONMENT DETAILS**
- Rancher Install: Helm
- Rancher version: `v2.6-head` https://github.com/rancher/rancher/commit/cfba0bc4fe19177cef627d36ad86744b62e5e751
- Browser: Chrome

**TEST RESULT**
PASS

**VERIFICATION STEPS**
1. Setup Rancher and navigate to the UI in a browser.
2. Created a standard user and login to Rancher as that user.
3. Provisioned a downstream RKE1 1.24 node driver cluster and verified that it came up as `Active`:
![image](https://user-images.githubusercontent.com/52591819/179325469-95a65b55-1d07-440b-af29-529e06c6bf85.png)
![image](https://user-images.githubusercontent.com/52591819/179325491-410fe851-157a-462e-b407-57398ca82469.png)
![image](https://user-images.githubusercontent.com/52591819/179325500-7eb372fb-4bcd-47a5-afe9-b28e5b44008b.png)
4. Verified in the Rancher logs that the original error is not seen.
