### ISSUE TITLE
`couldn't ensure service account impersonator` error seen in Rancher logs

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#38198]
**Rancher Server Setup**
- Rancher version: 2.6head `f40e542`
- Installation option (Docker install/Helm Chart): Helm

**Information about the Cluster**
- Kubernetes version: 1.24.2
- Cluster Type (Local/Downstream): local - 1.24.2 RKE1

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) : Admin

   
**Steps to reproduce:**

- RKE1 1.24 downstream cluster come sup Active, but `timeout getting credential for cluster group` seen in continuous Delivery page for this cluster 
- On cluster management page --> Cluster details --> related resources --> Cluster object is seen in Wait Applied/Error state
- Errors seen in Rancher logs:
```
2022/07/06 03:38:02 [ERROR] error syncing '_all_': handler user-controllers-controller: failed to start user controllers for cluster c-m-mfhzj6w6: ClusterUnavailable 503: cluster not found, requeuing
2022/07/06 03:38:10 [INFO] cri-dockerd is enabled for cluster version [v1.24.2-rancher1-1]
2022/07/06 03:39:12 [INFO] cri-dockerd is enabled for cluster version [v1.24.2-rancher1-1]
2022/07/06 03:39:20 [ERROR] Failed to handle tunnel request from remote address 10.42.1.4:34690 (X-Forwarded-For: 18.224.63.142): response 401: failed authentication
2022/07/06 03:39:21 [INFO] cri-dockerd is enabled for cluster version [v1.24.2-rancher1-1]
```
and
```
2022/07/06 03:35:53 [ERROR] error syncing 'p-8mdtt/creator-project-owner': handler cluster-prtb-sync: couldn't ensure service account impersonator: failed to get secret for service account: cattle-impersonation-system/cattle-impersonation-user-4n6jv, error: timed out waiting for the condition, requeuing
2022/07/06 03:35:53 [ERROR] error syncing 'c-q69rl/creator-cluster-owner': handler cluster-crtb-sync: couldn't ensure service account impersonator: failed to get secret for service account: cattle-impersonation-system/cattle-impersonation-user-4n6jv, error: timed out waiting for the condition, requeuing
```
- This rancher also had a downstream RKE2 EC2 cluster deployed.

**Comment by jiaqiluo** [comment]
**Problem**:
The function waitForServiceAccount checks the length of Secrets on the service account to determine if the service account is ready. 
However, starting from k8s 1.24, there is no service account token secret being auto-generated, so the length is always 0. 
As a result, we see the following error in rancher logs 
```
2022/07/06 03:35:53 [ERROR] error syncing 'p-8mdtt/creator-project-owner': handler cluster-prtb-sync: couldn't ensure service account impersonator: failed to get secret for service account: cattle-impersonation-system/cattle-impersonation-user-4n6jv, error: timed out waiting for the condition, requeuing
2022/07/06 03:35:53 [ERROR] error syncing 'c-q69rl/creator-cluster-owner': handler cluster-crtb-sync: couldn't ensure service account impersonator: failed to get secret for service account: cattle-impersonation-system/cattle-impersonation-user-4n6jv, error: timed out waiting for the condition, requeuing
```


**Fix**:
instead of checking the length of that specific field, we now check the secret we created for the service account. 
Because we always create the secret, the new logic works regardless of the cluster version. 


**Dev Tests**:
I run the local build on local cluster versions 1.23 and 1.24 and do not see the mentioned error anymore. 

**QA Tests**:
Following the same steps described in the issue, we should not see the above error messages in rancher logs anymore.

**Comment by jiaqiluo** [comment]
the fix is available in the latest v2.6-head

**Comment by Josh-Diamond** [comment]
Blocked - https://github.com/rancher/rancher/issues/38217;
Will resume testing when above issue is resolved

**Comment by Josh-Diamond** [comment]
Ticket #38198 - Test Results

With Helm:

Verified on `v2.6-988b8d1f63c19b13f6afba9de2e34e30cac133a7-head`:
1. Fresh install of rancher `v2.6-head` with local RKE1 1.24.2
2. As admin, provision a downstream RKE1 AWS Node driver cluster
3. Verified - Cluster successfully provisions; `service account impersonator` errors are not encountered;

Screenshot:

`Step 3`
<img width="1649" alt="Screen Shot 2022-07-15 at 10 43 01 AM" src="https://user-images.githubusercontent.com/46494969/179281582-bef449ca-2e45-4ea7-9211-2bec9734148e.png">
