### ISSUE TITLE
Rancher Agent can not connect to existing cluster

### ISSUE THREAD

**Issue by hadihammurabi** [rancher/rancher#38200]
**Rancher Server Setup**
I use this command to run rancher inside my cloud VPS.
`docker run -d --restart=unless-stopped -p 8080:80 -p 8443:443 --privileged --name=rancher rancher/rancher:latest`

And now, i have rancher work properly with this details.
![image](https://user-images.githubusercontent.com/16364286/177618386-2880c494-6853-4c2a-a9a5-f1a83e019986.png)

**Information about the Cluster**
- Kubernetes version: 
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6+k3s1", GitCommit:"418c3fa858b69b12b9cefbcff0526f666a6236b9", GitTreeState:"clean", BuildDate:"2022-04-28T22:16:18Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6+k3s1", GitCommit:"418c3fa858b69b12b9cefbcff0526f666a6236b9", GitTreeState:"clean", BuildDate:"2022-04-28T22:16:18Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? Custom

**User Information**
- What is the role of the user logged in? Admin
   
**Describe the bug**
With previous setup, i want to add more nodes to join within cluster.
But, i got a problem.

**To Reproduce**
First, i have new cluster configured and this page shown.
<img width="1591" alt="image" src="https://user-images.githubusercontent.com/16364286/177621225-7e1c9f0e-e6f3-4165-938b-0f954d6c146f.png">

Than, i run that Registration Command inside my second cloud VPS.

**Result**
The process was stuck.

```
INFO: Arguments: --server https://kube.formi.id:8443 --token REDACTED --ca-checksum cfc893f9fb43ef3...5a477a5bf02bdad7a --worker
INFO: Environment: CATTLE_ADDRESS=188.166.219.55 CATTLE_INTERNAL_ADDRESS= CATTLE_NODE_NAME=formi-node-1 CATTLE_ROLE=,worker CATTLE_SERVER=https://kube.formi.id:8443 CATTLE_TOKEN=REDACTED
INFO: Using resolv.conf: nameserver 127.0.0.53 options edns0 trust-ad
WARN: Loopback address found in /etc/resolv.conf, please refer to the documentation how to configure your cluster to resolve DNS properly
INFO: https://kube.formi.id:8443/ping is accessible
INFO: kube.formi.id resolves to 104.21.63.178 172.67.171.150
INFO: Value from https://kube.formi.id:8443/v3/settings/cacerts is an x509 certificate
time="2022-07-06T18:43:45Z" level=info msg="Listening on /tmp/log.sock"
time="2022-07-06T18:43:45Z" level=info msg="Rancher agent version v2.6.6 is starting"
time="2022-07-06T18:43:45Z" level=info msg="Option requestedHostname=formi-node-1"
time="2022-07-06T18:43:45Z" level=info msg="Option dockerInfo={YCH4:MOPW:Y3LE:U6NB:LBXX:WN2H:6WNJ:MKCM:WEZW:HOAW:UMHX:BHFG 1 1 0 0 1 overlay2 [[Backing Filesystem extfs] [Supports d_type true] [Native Overlay Diff true] [userxattr false]] [] {[local] [bridge host ipvlan macvlan null overlay] [] [awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog]} true false true true true true true true true true true true false 30 true 38 2022-07-06T18:43:45.508240147Z json-file cgroupfs 1 0 5.4.0-107-generic Ubuntu 20.04.4 LTS 20.04 linux x86_64 https://index.docker.io/v1/ 0xc0018adab0 2 2079367168 [] /var/lib/docker    formi-node-1 [] false 20.10.17   map[io.containerd.runc.v2:{runc [] <nil>} io.containerd.runtime.v1.linux:{runc [] <nil>} runc:{runc [] <nil>}] runc {  inactive false  [] 0 0 <nil> []} false  docker-init {10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1 10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1} {v1.1.2-0-ga916309 v1.1.2-0-ga916309} {de40ad0 de40ad0} [name=apparmor name=seccomp,profile=default]  [] [WARNING: No swap limit support]}"
time="2022-07-06T18:43:45Z" level=info msg="Option customConfig=map[address:188.166.219.55 internalAddress: label:map[] roles:[worker] taints:[]]"
time="2022-07-06T18:43:45Z" level=info msg="Option etcd=false"
time="2022-07-06T18:43:45Z" level=info msg="Option controlPlane=false"
time="2022-07-06T18:43:45Z" level=info msg="Option worker=true"
time="2022-07-06T18:43:45Z" level=info msg="Connecting to wss://kube.formi.id:8443/v3/connect/register with token starting with lmsqzv...8hjnph"
time="2022-07-06T18:43:45Z" level=info msg="Connecting to proxy" url="wss://kube.formi.id:8443/v3/connect/register"
time="2022-07-06T18:43:45Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered"
time="2022-07-06T18:43:47Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered"
time="2022-07-06T18:43:49Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered"
```
**Expected Result**
Second cloud VPS can join to existing cluster.

**Comment by baguasquirrel** [comment]
I see this issue all the time...

**Comment by baguasquirrel** [comment]
Okay, we did some deeper investigation of this at Tubi. Some notes:
1. When provisioning a new cluster, you need etcd, control-plane and workers all online before it will begin provisioning. Crucially, it appears that a critical piece of the Rancher software that runs on the clusters is scheduled on the *worker* nodes, not the control-plane nodes.
3. It is possible to break the cluster when you're replacing the etcd nodes if you don't make sure rancher has come completely online on the etcd nodes. It is *NOT* sufficient to wait for the etcd cluster itself to reach quorum. When we encountered this, we had to restore from backup, but the cluster came back in this state, and only the etcd and control-plane nodes were online.

Strangely for case 2, @orz-nil noticed that rancher could bring up a worker node if you re-provisioned an etcd or control-plane node. It just so happened to be that the first time we saw it, it brought up one of our special workers, which gets tainted because it's not supposed to run regular deployments. When we provisioned another control-plane node, this time it happened to bring online one of the regular workers, and then the cluster came back online.
