### ISSUE TITLE
Azure certs not passed to docker-machine correctly

### ISSUE THREAD

**Issue by vincent99** [rancher/rancher#3820]
Impossible to use azure driver because https://github.com/rancher/go-machine-service/blob/cf443915492773a9c30154115e4e640b35d1d607/handlers/providers/azure.go attempts to write the cert data to a file and change the driver config to point at the filename, but it doesn't work.

**Comment by hibooboo2** [comment]
This has been fixed.

**Comment by deniseschannon** [comment]
@tfiduccia This also looks like the PR was merged, so just needs to be tested. I think @westlywright just spun up on Azure host recently so maybe you just need his confirmation on the certs.

**Comment by tfiduccia** [comment]
Version - master UI 3/18
Verified fixed - able to setup Azure.
