### ISSUE TITLE
Cannot update s3 credentials after cluster has been created.

### ISSUE THREAD

**Issue by jakefhyde** [rancher/rancher#38215]
**Rancher Server Setup**
- Rancher version: v2.6.4 - v2.6.7

**Information about the Cluster**
- Cluster Type (Local/Downstream): Downstream
  - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): RKE1

**User Information**
- What is the role of the user logged in? Admin

**Describe the bug**

After the creation of the cluster without setting S3 credentials to take snapshots of the downstream cluster, it's not possible to update the cluster to upload snapshots to S3 buckets. The S3 settings only work when it's set during the creation of the cluster. 

**To Reproduce**
 
- Create a new cluster without setting S3 snapshots;
- After the cluster it's created set the S3 snapshot and try to run a snapshot.
**Result**
Not able to create backups of the downstream cluster and send the backup to S3. Not able to add, update, or remove the secrets.
**Expected Result**

Can add, edit & remove S3 credential in order to enable or disable s3 snapshot capabilities for a cluster. If the cluster was created with S3 credentials, then it is possible to update the secret, but it is much harder to get around if the cluster was created without it.
**Screenshots**

I believe this issue is caused here:

https://github.com/rancher/norman/blob/61b018639b217b33604cae675e189c2afa4cf378/types/convert/merge/merge.go#L11-L20

which is called in `rancher` here:

https://github.com/rancher/rancher/blob/b919539b4869325aadcdb737070c02914a692cb2/pkg/api/norman/store/cluster/cluster_store.go#L841

Before:
![image](https://user-images.githubusercontent.com/33796120/177827299-f7d25ab9-9edd-4173-8f01-eb908d27d3ea.png)

(Service Account Token was purposely spoofed here)

After:
```
value = {interface{} | map[string]interface{}} 
 0 = agentImage -> rancher/rancher-agent:v2.6-head
 1 = aksStatus -> 
 2 = capacity -> 
 3 = gkeStatus -> 
 4 = nodeCount -> 1
 5 = authImage -> rancher/kube-api-auth:v0.1.8
 6 = driver -> rancherKubernetesEngine
 7 = nodeVersion -> 1
 8 = requested -> 
 9 = apiEndpoint -> https://161.35.143.159:6443/
 10 = appliedPodSecurityPolicyTemplateId -> 
 11 = caCert -> LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM0VENDQWNtZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFTTVJB
 12 = certificatesExpiration -> 
 13 = conditions -> len:19, cap:32
 14 = limits -> 
 15 = provider -> rke
 16 = serviceAccountTokenSecret -> cluster-serviceaccounttoken-xrj5v
 17 = version -> 
 18 = agentFeatures -> 
 19 = allocatable -> 
 20 = appliedAgentEnvVars -> len:3, cap:4
 21 = appliedEnableNetworkPolicy -> false
 22 = appliedSpec -> 
 23 = capabilities -> 
 24 = eksStatus -> 
 25 = linuxWorkerCount -> 1
```

**Additional context**

I was able to verify that [merging statuses within norman solves the problem](https://github.com/rancher/norman/compare/master...jakefhyde:norman:merge-status) (albeit the test was a bit naive), but I'm no norman expert so there may be multiple ways to tackle this issue.

Additionally, I've only tested `s3CredentialSecret`, but I imagine the other secret fields may be impacted as well.

SURE-4833

**Comment by pwurbs** [comment]
I ran in (maybe) the same issue with Rancher 2.6.4 and created RKE1 cluster.
When chaanging the etcd snapshot from local to S3, the configuration was accepted by the Rancher UI, so credentials and parameters are correct obviously. But when I start a manual snapshot, there is an error with the following Rancher log line:
`[WARNING] [etcd] Failed to take one-time snapshot on host [192.168.0.15], exit code [1]: time="2022-07-11T13:07:01Z" level=fatal msg="failed to set s3 server: failed to check s3 bucket:sdcloud-etcd-backup, err:Access Denied."`

**Comment by Josh-Diamond** [comment]
Ticket #38215 - Test Results

With Docker on a single-node instance:

Reproduced on rancher `v2.6.6`:
1. Fresh install of rancher `v2.6.6`
2. Provision a downstream RKE1 AWS Node driver cluster w/ local etcd snapshots configured
3. Once `Active`, `Edit Config` of cluster and configure s3 snapshots
4. Take snapshot with s3 configured
5. Reproduced - Failed to take snapshot; received error message (see logs below)

Screenshot:

`Step 5`
![s3-reproduced](https://user-images.githubusercontent.com/46494969/180858578-151dc65b-632b-4640-9c5f-0ac53510f7e2.png)

`Logs`
```
2022/07/25 19:21:17 [WARNING] [etcd] Failed to take one-time snapshot on host [REDACTED], exit code [1]: time="2022-07-25T19:21:16Z" level=fatal msg="failed to set s3 server: failed to check s3 bucket:REDACTED, err:Access Denied."
```

---

Verified on rancher `v2.6-b66dd0f614f9d60ef54dfb82da12b9b8b194021b-head`:
1. Fresh install of rancher `v2.6-head`
2. Provision a downstream RKE1 AWS Node driver cluster w/ local etcd snapshots configured
3. Once `Active`, `Edit Config` of cluster and configure s3 snapshots
4. Take snapshot with s3 configured
5. Verified - s3 snap successful
6. Deploy a workload
7. Restore to snap taken in step 3, with `etcd only` option selected
8. Verified - s3 snap/restore successful

Screenshot:

`Step 5`
![s3-proof](https://user-images.githubusercontent.com/46494969/180868419-ff3fcaec-8e10-4ef0-841f-d09dc8a4331a.png)

**Comment by anupama2501** [comment]
Re opening for a few more validations

**Comment by cmurphy** [comment]
## Release note template

Synopsis of issue: if S3 or other kinds of credentials are added to a cluster after it is already created, the reference to the secret containing the credentials was lost because the cluster Status cannot be updated through the API. The references are moved to the cluster Spec so that they can be added after creation.
Resolved (or not): resolved
Versions: v2.5.13-v2.5.15, v2.6.4-v2.6.6

**Comment by anupama2501** [comment]
Verified on v2.6-head `78017e6`
1. rke1 node driver with rke1 template - etcd snapshot enabled - Pass
2. rke1 node driver with rke1 template override enabled - s3 etcd snapshot enabled - Pass
3. rke1 node driver with rke1 template override enabled and override parameter required - s3 etcd snapshot enabled - Pass

Verified upgrade from v2.6.6 >> v2.6-head `78017e6`
1. rke1 node driver with rke1 template - s3 etcd snapshot enabled - Pass
2. rke1 node driver with rke1 template upgrade - local etcd snapshot enabled - Pass
4. rke1 node driver with rke1 template override enabled - s3 etcd snapshot enabled - Pass
5. rke1 node driver with rke1 template override enabled - local etcd snapshot enabled  - Pass
6. rke1 node driver with rke1 template override enabled and override parameter required - s3 etcd snapshot enabled - Pass
7. rke1 node driver with rke1 template override enabled and override parameter required - local etcd snapshot enabled - Pass

**Comment by anupama2501** [comment]
I tried the following scenario:
1. Spin up a docker install rancher server v2.6.6 
2. create a downstream rke1 Amazon EC2 node driver 1 etcd, 1 cp and 1 worker nodes and leave the etcd snapshot to local
3. Once the cluster is active, change the etcd snapshot `etcd Snapshot Backup Target` location to s3
4. CLuster goes into updating state and comes back up active.
5. Take an etcd snapshot --> errors out 
```
 "failed to set s3 server: failed to check s3 bucket:<bucketname>, err:Access Denied."
```
6. Upgrade rancher server to v2.6.7-rc7
7. Once the downstream cluster agent is updated to v2.6.7-rc7, navigate to cluster management >> downstream cluster >> Snapshots >> take a snapshot >> still errors out 
```
2022/08/10 04:38:01 [ERROR] error syncing 'c-xm9fg/c-xm9fg-ms-cltrr': handler etcdbackup-controller: [etcd-backup] failed to perform etcd backup: [etcd] Failed to take snapshot on all etcd hosts: failed to take one-time snapshot on host [66.228.46.71], exit code [1]: time="2022-08-10T04:37:44Z" level=fatal msg="failed to set s3 server: failed to check s3 bucket:au-s3bucket, err:Access Denied."
```

**Workaround** >> change the snapshot to local and then change back to s3 location.

**Comment by jakefhyde** [comment]
@cmurphy We may need to add a migration if we are attempting to fix the above case, or release note it.

**Comment by cmurphy** [comment]
I recommend we include the following in the release notes:

To repair a cluster after upgrade, edit the cluster and enter the credential again and save it. The cluster will now retain references to the credentials.

**Comment by Josh-Diamond** [comment]
Ticket #38215 - Test Results

With Docker on a single-node instance:

Upgrade (workaround) Verified on rancher `2.6.6 => 2.6.7-rc7`:
1. Fresh install of rancher `v2.6.6`
2. Provision a 3-node downstream AWS Node driver cluster w/ individual roles - [ 1 etcd, 1 cp, 1 wkr]
3. Once active, `Edit Config` and set snapshots to s3 bucket
4. Cluster goes into `updating` state, then resolves as active w/ the following error seen in rancher logs:
     - `[WARNING] [etcd] Failed to take one-time snapshot on host [REDACTED], exit code [1]:  level=fatal msg="failed to set s3 server: failed to check s3 bucket:<REDACTED>, err:Access Denied."`
5. Manually take etcd snapshot
6. Etcd snapshot fails with same error seen in step 4
7. Upgrade rancher to `v2.6.7-rc7`
8. Once upgrade is complete and cluster is active, `edit config` and observe s3 credentials are configured
9. Hit save, then take snapshot
10. Snapshot fails w/ error message seen in step 4
11. `edit config` on cluster once more, this time, delete s3 credentials and re-type them, then hit `save`
12. Take a snapshot
13. Snapshot fails w/ error seen in step 4
14. `edit config` of cluster, then set snapshots to `local` and save
15. Once cluster is active, `edit config` and set snapshots to s3, then hit save
16. Once cluster is active, take a snapshot
17. Verified - Successful snapshot w/ s3
18. Deploy a workload
19. Restore to snapshot taken in step 17
20. Verified - s3 backup/restore works

Note:
Colleen's workout did not work, as outlined in her comment above; Anu's workaround did work, and based on my test results, post-rancher server upgrade, it is necessary to set snapshots back to local first, then once active, configure s3.

**Comment by sowmyav27** [comment]
Reopening for @cmurphy to confirm if [this](https://github.com/rancher/rancher/issues/38215#issuecomment-1211210555) workaround here is good?

**Comment by Josh-Diamond** [comment]
Workaround confirmed 👍
