### ISSUE TITLE
Unable to provision downstream RKE1 clusters on rancher v2.6-head

### ISSUE THREAD

**Issue by Josh-Diamond** [rancher/rancher#38217]
**Rancher Server Setup**
- Rancher version: `v2.6-650cb0b0b8981ffcdc094e730db93a101dbcb9d6-head`
- Installation option (Docker install/Helm Chart): `Helm`
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details: `byo-valid`

**Information about the Cluster**
- Kubernetes version: `v1.24.2-rancher1-1`
- Cluster Type (Local/Downstream):
Downstream

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
Admin/standard user - both user types are unable to provision downstream clusters

   
**Describe the bug**
When attempting to provision a downstream cluster on rancher `v2.6-650cb0b0b8981ffcdc094e730db93a101dbcb9d6-head`, various errors are encountered preventing successful provisioning.  Errors seem to change with each attempt.

**To Reproduce**
1. Fresh install of rancher `v2.6-650cb0b0b8981ffcdc094e730db93a101dbcb9d6-head`
2. Provision a downstream cluster
3. Reproduced 

**Result**
provisioning fails with errors

**Expected Result**
cluster successfully provisions

**Screenshots**
![errors](https://user-images.githubusercontent.com/46494969/177863753-640c51b8-18fe-4fc0-ac83-a0ab5c447f97.png)

**Comment by sowmyav27** [comment]
**2.6head - `2508215` HA install 1.24 RKE1 local cluster** 

- RKE1 clusters stuck with error - 1.23 and 1.24 (1 etcd, 1 cp and 1 worker node - Linode and AWS Node driver clusters)
```
Failed to set up SSH tunneling for host [ip]: Can't retrieve Docker Info: error during connect: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/info": can not build dialer to [c-ppcw6:m-284xf]
[ERROR] Removing host [ip] from node lists
[ERROR] Cluster must have at least one etcd plane host: failed to connect to the following etcd host(s) [ip]
```

**Comment by sowmyav27** [comment]
Closing this issue since we have validated and closed the dialer issue. Will reopen this or log a new one if we see this rbac issue.
