### ISSUE TITLE
内置集群local不能删除

### ISSUE THREAD

**Issue by RootFive** [rancher/rancher#38226]
*内置集群local不能删除*

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.5.15` UI: `v2.5.14` |
|Route|`undefined`|

**Comment by niusmallnan** [comment]
The Local cluster is used to run Rancher server and its auxiliary programs, and it should not be deleted.

Please try to use common languages in the international community. If you wish to communicate in Chinese only, please visit here. https://forums.rancher.cn/

**Comment by DevelopmentAndOperations** [comment]
好垃圾

**Comment by Brightest08** [comment]
最开始是用来管理k8s集群的，后来功能越来越多，居然内置了k3s集群还不能禁用，我需要k3s集群我会去部署k3s而不是rancher，强制安装也算了，内置后容器时不时就发生重启影响正常使用。。。
