### ISSUE TITLE
EPIC: Azure China Cloud

### ISSUE THREAD

**Issue by niusmallnan** [rancher/rancher#38225]
As with many public clouds, Azure builds multiple cloud environments to address compliance in different regions:
- AzurePublicCloud
- AzureGermanCloud
- AzureChinaCloud
- AzureUSGovernmentCloud

These environments were well supported in the previous Cluster Manager UI.

From v2.6, there were problems with multi-environment support for Azure as the API and UI of Rancher Manager were rewritten.
- https://github.com/rancher/rancher/issues/35600
- https://github.com/rancher/dashboard/issues/4585
- https://github.com/rancher/rancher/issues/36048

This issue will focus on the support for **AzureChinaCloud** on v2.6:
- Cloud credential management
- Provisioning for RKE2/K3s via azure node driver
- Provisioning for RKE via azure node driver
- Full Lifecycle Management of AKS

Code commits and tests can be done by the Rancher China E&I team.

**Comment by niusmallnan** [comment]
The PRs for cluster manager and cluster explorer can be reviewed anytime.
The PR for `rancher/rancher` needs to be updated after the PR for `rancher/aks-operator` gets to be merged.

**Comment by tibodf** [comment]
Hello, the issue still exist en 2.7.x. Not possible to use AzureChinaCloud. Is it possible to fix ?
