### ISSUE TITLE
RKE1 Cluster is stuck in `Waiting for API to be available` state

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#38222]
**Rancher Server Setup**
- Rancher version: 2.6head commit id: `13482ca`
- Installation option (Docker install/Helm Chart): helm

**Information about the Cluster**
- Kubernetes version: 1.24.2
- Cluster Type (Local/Downstream): Local - RKE1
- Downstream cluster - EC2 - 1 etcd, 1 cp, 1 worker node - RKE1 1.24.2 cluster

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): admin

**Describe the bug**
Cluster is stuck in `Waiting for API to be available` state

**To Reproduce**

- Deployed an  EC2 - 1 etcd, 1 cp, 1 worker node - RKE1 1.24.2 cluster
- Nodes come up Active
- But the cluster is stuck in `Waiting` state with `Waiting for API to be available` message
- No errors in Provisioning logs
- There is a restart in cluster-agent on contrrol plane node with error `ERROR: https://rancher-server/ping is not accessible (Could not resolve host: server)`

**Comment by sowmyav27** [comment]
@kinarashah offline debug comment - "the agent was running fine, but the cluster conditions never got updated"

**Comment by mimani68** [comment]
I had faced with error `Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused`

**Comment by sowmyav27** [comment]
Please validate these scenarios on a RKE1 local cluster HA Rancher setup
- Provisioning RKE1 Node driver cluster - 3 etcd, 2cp, 3 worker nodes
- Provisioning RKE1 custom cluster
- Provisioning RKE1 import cluster

**Comment by markusewalker** [comment]
Verified this is addressed on https://github.com/rancher/rancher/commit/cfba0bc4fe19177cef627d36ad86744b62e5e751.

**ENVIRONMENT DETAILS**
- Rancher Install: Helm
- Rancher version: `v2.6-head` https://github.com/rancher/rancher/commit/cfba0bc4fe19177cef627d36ad86744b62e5e751
- Browser: Chrome

**TEST RESULT**
PASS

**VERIFICATION STEPS**
1. Setup Rancher HA and navigate to the UI in a browser.
2. Created a standard user and login to Rancher as that user.
3. Provisioned the following clusters: RKE1 node driver, RKE1 custom, RKE1 imported. Verified all of them came up as `Active`:
![image](https://user-images.githubusercontent.com/52591819/179324005-1970c136-984a-4338-affb-78e72bc5352c.png)
