### ISSUE TITLE
It is no longer possible to update Kubernetes version since Rancher 2.6.4

### ISSUE THREAD

**Issue by killerquitsche** [rancher/rancher#38224]
**Rancher Server Setup**
- Rancher version: v2.6.5
- Installation option (Docker install/Helm Chart):
   - Docker (single Node install on AWS EC2 instance) 
   - Docker version: 20.10.12
   - OS: Ubuntu 20.04.4 CIS AMI

**Information about the Cluster**
- Kubernetes version: 1.21.10
- Cluster Type (Local/Downstream):
   - Downstream (1x etcd, 1x controller, 3x Worker)
   - Infrastructure Provider = Rancher provisioning the nodes using AWS node driver
   - Hosted: RKE Cluster - Amazon EC2
   - OS on each node: Flatcar

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - Admin
   
**Describe the bug**
Cluster goes into Error state during a Kubernetes update.

**To Reproduce**
- Provision an EC2 instance and install Rancher in version 2.6.4 or 2.6.5 (docker single node install) 
- Deploy a Kubernetes Cluster in Rancher
- Edit the cluster configuration and increase the Kubernetes version to initiate an update

**Result**
- The update process starts, the controller node is shown as cordoned in the Rancher UI, but after a short time we get the following error and the cluster goes into error state.
`Host xxxxx-controller-1 failed to report Ready status with error: [controlplane] Error getting node xxxxx-controller-1:  "xxxxxxx-controller-1" not found`

**Expected Result**
The controller node should be successfully updated at some point and in the Rancher UI the cordoned should disappear at the controller node and update the next node until the whole cluster is updated. After that, the cluster should be available again normally.

**Screenshots**

**Additional context**
We have already tried different Rancher version and Kubernetes versions. We noticed that this problem only appears in Rancher 2.6.4 and higher.
- Rancher 2.6.3
- Kubernetes Cluster 1.21.10 to 1.21.12
-> No Problems 
-------------------
- Rancher 2.6.4
- Kubernetes Cluster 1.21.10 to 1.21.12
- > Update does not work
--------------------
- Rancher 2.6.4
- Kubernetes Cluster 1.22.4 to 1.22.5
- > Update does not work
-------------------
- Rancher 2.6.5
- Kubernetes Cluster 1.21.13
- Update Kubernetes Cluster to 1.22.4
- > Update does not work

**Comment by killerquitsche** [comment]
Hi @Aransh,
sorry for my late feedback.
I took a close look at the kubelet logs, but we didn't seem to have the same problem as you.
The network plugin was loaded successfully
`0715 07:33:41.508511   10522 docker_service.go:242] "Hairpin mode is set" hairpinMode=hairpin-veth
I0715 07:33:41.671158   10522 plugins.go:168] "Loaded network plugin" networkPluginName="cni"
I0715 07:33:41.671892   10522 docker_service.go:257] "Docker cri networking managed by the network plugin" networkPluginName="cni"`

On the node itself, I also see that all required CNI files are in the directory /etc/cni/net.d
`ip-1XX-1XX-1XX-XXX /etc/cni/net.d # ls
10-canal.conflist  calico-kubeconfig`

All docker containers have been updated to the new version (1.21.13)
`CONTAINER ID   IMAGE                                 COMMAND                  CREATED             STATUS             PORTS     NAMES
92c0ea5c4191   rancher/hyperkube:v1.21.13-rancher1   "/opt/rke-tools/entr…"   About an hour ago   Up About an hour             kube-proxy
022cc8af964d   rancher/hyperkube:v1.21.13-rancher1   "/opt/rke-tools/entr…"   About an hour ago   Up About an hour             kubelet
7dbbad92f3cf   rancher/hyperkube:v1.21.13-rancher1   "/opt/rke-tools/entr…"   About an hour ago   Up About an hour             kube-scheduler
c1120d751f21   rancher/hyperkube:v1.21.13-rancher1   "/opt/rke-tools/entr…"   About an hour ago   Up About an hour             kube-controller-manager
9a4563b63229   rancher/hyperkube:v1.21.13-rancher1   "/opt/rke-tools/entr…"   About an hour ago   Up About an hour             kube-apiserver`

When I look at the logs of the containers, I see a few errors in between, but in the end all containers are started successfully.
I will take a closer look at the individual errors.

In the Rancher logs I see at the beginning that it checks the node list and finds the controller node:
`2022/07/15 07:33:01 [DEBUG] Checking node list for node [playground-controller-1], try #1
2022/07/15 07:33:01 [DEBUG] [controlplane] Found node by name playground-controller-1
2022/07/15 07:33:01 [INFO] [controlplane] Now checking status of node playground-controller-1, try #1
2022/07/15 07:33:01 [DEBUG] Checking node list for node [playground-controller-1], try #1
2022/07/15 07:33:01 [INFO] cluster [c-hm4s5] provisioning: [controlplane] Processing controlplane hosts for upgrade 1 at a time
2022/07/15 07:33:01 [INFO] cluster [c-hm4s5] provisioning: Processing controlplane host playground-controller-1
2022/07/15 07:33:01 [DEBUG] [controlplane] Found node by name playground-controller-1`

In the further process it updates all containers and at the end it checks the node list again. It looks like it does not find the node anymore:
`2022/07/15 07:34:08 [DEBUG] Checking node list for node [playground-controller-1], try #4
2022/07/15 07:34:09 [DEBUG] 2022/07/15 07:34:09 http: TLS handshake error from 194.39.218.10:63801: EOF
2022/07/15 07:34:13 [DEBUG] Checking node list for node [playground-controller-1], try #5
2022/07/15 07:34:18 [ERROR] Failed to upgrade hosts: playground-controller-1 with error [[controlplane] Error getting node playground-controller-1:  "playground-controller-1" not found]`

**Comment by Aransh** [comment]
This is still relevant, latest rancher is still broken for me

**Comment by killerquitsche** [comment]
Still relevant also for us.

**Comment by Aransh** [comment]
This is still relevant, latest rancher is still broken for me

**Comment by killerquitsche** [comment]
Hi @Aransh,

It looks like we are affected by the following [bug](https://github.com/rancher/rancher/issues/37634). As a result of the change introduced via [Rancher RKE](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Francher%2Frke%2Fcommit%2Feb8b278bcd306283bacaaf3afa8cb27a3b25305d&data=05%7C01%7Cdaniela.buescher%40etas.com%7C77a4b2e97f1b44b00d3408dab0204963%7C0ae51e1907c84e4bbb6d648ee58410f4%7C0%7C0%7C638015949955770537%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=dCefoAB70mnIvlqnf1FUTKr9ayQQbuOVHjFNjWXU1aI%3D&reserved=0) in RKE 1.3.5, the **hostname-override** flag is no longer set for the kubelet in clusters with the AWS Cloud Provider configured.

When the kubelet container is created by RKE v1.3.5 the **kubernetes.io/hostname** label of the node is set to the EC2 instance's hostname, typically of the form `ip-<private ip>.<region>.<internal>`. In our case the hostname configured by the AWS cloud provider and the kubernetes/hostname don`t match.

We were able to solve the problem with existing clusters as follows:

1. Check hostname from all nodes
`kubectl describe node <NODE NAME> | grep name`
2. If a node's `kubernetes.io/hostname`  is the same value as `Hostname` , it must be changed back to the name of the node. The kubernetes.io/hostname should be the same as the node name shown in the AWS Console → EC2 → Instances.
3. Edit all nodes where the wrong kubernetes.io/hostname  is set.
```yaml
> kubectl edit node <NODE NAME>
apiVersion: v1
kind: Node
metadata:   
     labels:
        kubernetes.io/hostname: <NODE NAME>
```
4. Force a reconcile for the cluster. For example: Edit your cluster and change the values of the snapshot interval and click save.

In some cases it happens that after step 4 the update still does not pass successfully. If this is the case, perform the following steps:

1. Change the `kubernetes.io/hostname`  of all nodes to the same name as `Hostname`.
2. Force a reconcile of your Cluster.

Hopefully this helps you @Aransh .

**Comment by Aransh** [comment]
Hey @killerquitsche 
Thank you very very much for the detailed explanation!

In our case we are deploying rancher using terraform, so your solution is much too manual for us...
But I'm glad to know you were able to pinpoint the issue and pass it along, hopefully it'll be officially resolved soon!

**Comment by bkonick** [comment]
I believe this is similar to the issue I opened here https://github.com/rancher/rke/issues/3091
