### ISSUE TITLE
Module logs not available, client-side error with cached logs size

### ISSUE THREAD

**Issue by gerkra** [rancher/rancher#38231]
**Rancher Server Setup**
- Rancher version: **v2.6.5**
- Installation option (Docker install/Helm Chart): **Docker**

**User Information**
- What is the role of the user logged in? **Admin**

**Describe the bug**
Not available logs of pods

**To Reproduce**
 
1. Open any pod 
2. Click "View Logs" 
3. Open logs settings 
4. Change "Show the last" to any value (not "30 Minutes")
5. Change "Show the last" to "30 Minutes"
6. Refresh page (F5 / Command + R)

** HOW WE FIX IT **
**We find only one way to fix this error, delete the user and re-create it in rancher.**

**Result**
Logs tab not show logs and get error in web developer console:
![image](https://user-images.githubusercontent.com/8065296/178026027-3cab16ff-ba4e-476c-9ec8-65577542bf23.png)
![image](https://user-images.githubusercontent.com/8065296/178026087-0f1243d0-65fd-4e75-99be-0b154bd7e2c0.png)

**Expected Result**
See logs of pod
![image](https://user-images.githubusercontent.com/8065296/178025929-bb4229d8-6c9a-4aaa-9007-136bf163fd80.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/8065296/178024851-ee2164ea-c0ea-4b7f-b183-a4375c8b9a74.png)
![image](https://user-images.githubusercontent.com/8065296/178024984-03d331d9-809a-4894-bdb5-ba137109e455.png)
![image](https://user-images.githubusercontent.com/8065296/178025336-bc9d887b-1d98-4e50-93f0-ebca37f3a8e8.png)

**Comment by JPBariaa** [comment]
Hello budy, how are you?
I have the same problem.
Your resolution didn't work in my case, if I reload the page the bug happens again.

**Comment by JPBariaa** [comment]
Follow Workaround

```kubectl delete preferences.management.cattle.io -n u-xxxxxx logs-range```

Fix my case!

**Comment by mstrent** [comment]
We are also seeing this issue on Rancher 2.6.6. We're using AD/LDAP auth. Only users that change the "Show the last" option seem to be affected. Deleting their individual user in Rancher and having them re-login to re-create their user in Rancher resolves (until they use the "Show the last" option again).
