### ISSUE TITLE
Rancher >=2.6.4 not installing CNI on nodes

### ISSUE THREAD

**Issue by Aransh** [rancher/rancher#38236]
**Rancher Server Setup**
- Rancher version: 2.6.4-2.6.6
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.21.7-rancher1-1
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Custom

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Admin

   
**Describe the bug**

Trying to deploy a new downstream cluster, nodes running the docker registration command will fail to register.
Looking at the kubelet container logs on the node shows it is complaining the folder /etc/cni/net.d is empty.
Deploying the exact same configuration with rancher 2.6.3 works just fine.

**To Reproduce**
 
Deploy a rancher host cluster with the following versions:
Rancher: 2.6.4-2.6.6
Docker: 20.10.13
k8s: v1.21.7-rancher1-1

Deploy a downstream cluster with the following versions:
Docker: 20.10.13
k8s: v1.21.13-rancher1-1

**Result**
node will be stuck registering, kubelet logs will complain CNI installation is missing

**Expected Result**

CNI is installed by rancher as on rancher 2.6.3

**Screenshots**

**Additional context**

**Comment by niusmallnan** [comment]
Can you share how to configure Node Role, your docker info, and the RKE CNI plugin?
So far my setup is working fine.

**Comment by Aransh** [comment]
I use docker 20.10.13 on the nodes, and the whole configuration is created with terraform (rke provider version 1.3.1, rancher2 provider version 1.24.0).
The nodes are started and connected using the docker registration command outputted from the server.

The "rancher2_cluster" resource has the "network" configuration block inside the "rke_config" block as follows (again, this works just fine with rancher 2.6.3 and below):
```
    network {
      plugin = "canal"
    }
```
Our module is based on the documentation [here](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster)
Let me know if I answered your questions and if you need any more info
And take you for your response

**Comment by niusmallnan** [comment]
I'm not a TF expert and I can't quickly find the root cause.
If you don't use TF, can the problem be reproduced through Rancher UI operations?

**Comment by Aransh** [comment]
@niusmallnan Will have to test this at a later date, might take some time as I've never done this manually, plus have some other urgent tasks.
Will report once I test, thanks
