### ISSUE TITLE
Validation failed in API: field `environment` is deprecated, please use Kubernetes native field `env` for the container's environment variables

### ISSUE THREAD

**Issue by yinqichao** [rancher/rancher#38239]
*Describe your issue here*

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.6.3` UI: `vmaster-dev` |
|Route|`undefined`|

**Comment by yinqichao** [comment]
![image](https://user-images.githubusercontent.com/40418422/178202315-5284c8af-e39b-47ee-b3ef-40afe9a0f391.png)

**Comment by yinqichao** [comment]
![image](https://user-images.githubusercontent.com/40418422/178202378-5b37b869-211a-4b15-8b0c-2fc61a413c6a.png)

**Comment by SmileTower** [comment]
this ui 2.5?

**Comment by yinqichao** [comment]
@SmileTower  this ui v2.6.3

**Comment by SmileTower** [comment]
![1](https://user-images.githubusercontent.com/17945169/178397523-659dc487-da6b-4a3f-b908-c24423b9273a.png)
why ? not like

**Comment by yinqichao** [comment]
@SmileTower  my url is "/g/clusters" , and choose this
![image](https://user-images.githubusercontent.com/40418422/178400099-1b7ada20-38f4-4cae-9399-2c70e0aa9777.png)
and click this
![image](https://user-images.githubusercontent.com/40418422/178400150-0a6f7dac-45f3-4dae-a193-d0e4775289f7.png)



by the way
where is "负载均衡" in new ui?
![image](https://user-images.githubusercontent.com/40418422/178400256-5576283d-4151-44cf-b876-ec0a10512bbc.png)

**Comment by yinqichao** [comment]
@SmileTower  in new ui, i can config env value,and run success
![image](https://user-images.githubusercontent.com/40418422/178400932-b9beedb6-c259-45e3-ba11-e1cf98be75ad.png)

but i turn back to "/g/clusters" ,i found there is no env value
![image](https://user-images.githubusercontent.com/40418422/178401091-71b1910d-c156-4457-be0f-d5e41dc0f083.png)

maybe incompatible?

**Comment by SmileTower** [comment]
like you, incompatible

![1](https://user-images.githubusercontent.com/17945169/178403451-e4ba7ec1-426b-44bc-9905-dc2b545d9294.png)
