### ISSUE TITLE
建议版号展示框增加下拉列表，展示之前的程序版本号，方便回滚

### ISSUE THREAD

**Issue by wwrh** [rancher/rancher#38240]

**Comment by niusmallnan** [comment]
You need to follow the issue template to make friendly expressions.

Please try to use common languages in the international community. If you wish to communicate in Chinese only, please visit here. https://forums.rancher.cn/

**Comment by wirwolf** [comment]
@niusmallnan Often this not help the rancher team and the issue lies in the list until the bot closes it due to inactivity
