### ISSUE TITLE
Unable to provision RKE2 downstream clusters on HA Rancher install

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#38247]
**Rancher Server Setup**
- Rancher version: `2508215`
- Installation option (Docker install/Helm Chart): Rancher HA Helm install
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1
- Proxy/Cert Details: Rancher geenrated

**Information about the Cluster**
- Kubernetes version: 1.24 local RKE1 cluster

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) admin

   
**Describe the bug**
Unable to provision RKE2 downstream clusters on HA Rancher install

**To Reproduce**

- Deploy 1 etcd, 1 cp and 1 worker node clusters - Linode and AWS RKE2 node driver cluster - `v1.23.8+rke2r1`
- Cluster is stuck in Error state `Cluster health check failed: Failed to communicate with API server during namespace check: Get "https://10.43.0.1:443/api/v1/namespaces/kube-system?timeout=45s": context deadline exceeded`
- Provisioning logs:

```
11:15:40 am | [INFO ] waiting for viable init node
-- | --
11:16:08 am | [INFO ] configuring bootstrap node(s) sowmya-test-rke2-pool1-c6d66f7c-6dw8f: waiting for agent to check in and apply initial plan
11:17:40 am | [INFO ] configuring bootstrap node(s) sowmya-test-rke2-pool1-c6d66f7c-6dw8f: waiting for probes: etcd, kubelet
11:18:20 am | [INFO ] configuring control plane node(s) sowmya-test-rke2-pool2-cccc95948-j279x: waiting for agent to check in and apply initial plan
11:18:24 am | [INFO ] configuring control plane node(s) sowmya-test-rke2-pool2-cccc95948-j279x: waiting for probes: calico, kube-apiserver, kube-controller-manager, kube-scheduler, kubelet
11:19:02 am | [INFO ] configuring control plane node(s) sowmya-test-rke2-pool2-cccc95948-j279x: waiting for probes: calico, kube-apiserver, kube-controller-manager, kube-scheduler
11:19:08 am | [INFO ] configuring control plane node(s) sowmya-test-rke2-pool2-cccc95948-j279x: waiting for probes: calico
11:20:22 am | [INFO ] configuring control plane node(s) sowmya-test-rke2-pool2-cccc95948-j279x: waiting for cluster agent to connect
11:48:49 am | [INFO ] waiting for control plane to be available
```

**Expected Result**
Cluster should come up Active

**Note:**

- On a docker install, clusters come up Active
- Fleet on both the rancher server - docker install and Rancher HA are in a bad state.
- Error on fleet:

```
"rancher/fleet:v0.3.10-rc1": rpc error: code = Unknown desc = Error response from daemon: manifest for rancher/fleet:v0.3.10-rc1 not found: manifest unknown: manifest unknown
```

**Comment by kinarashah** [comment]
Fleet errors will be resolved separately via https://github.com/rancher/fleet/pull/850

**Comment by sowmyav27** [comment]
Please validate these scenarios on a RKE1 local cluster HA Rancher setup
- Provisioning RKE2 Node driver cluster - 3 etcd, 2cp, 3 worker nodes
- Provisioning RKE2 custom cluster
- Provisioning RKE2 import cluster

**Comment by markusewalker** [comment]
Verified this is addressed on https://github.com/rancher/rancher/commit/cfba0bc4fe19177cef627d36ad86744b62e5e751.

**ENVIRONMENT DETAILS**
- Rancher Install: Helm
- Rancher version: `v2.6-head` https://github.com/rancher/rancher/commit/cfba0bc4fe19177cef627d36ad86744b62e5e751
- Browser: Chrome

**TEST RESULT**
PASS

**VERIFICATION STEPS**
1. Setup Rancher and navigate to the UI in a browser.
2. Created a standard user and login to Rancher as that user.
3. Provisioned the following clusters: RKE2 node driver, RKE2 custom, RKE2 imported. Verified all of them came up as `Active`:
![image](https://user-images.githubusercontent.com/52591819/179324005-1970c136-984a-4338-affb-78e72bc5352c.png)
