### ISSUE TITLE
Introduce  v1.24 RKE2 and k3s in Rancher 

### ISSUE THREAD

**Issue by Sahota1225** [rancher/rancher#38258]
Tracking this change

**Comment by Sahota1225** [comment]
PR: https://github.com/rancher/kontainer-driver-metadata/pull/930#issuecomment-1180821537

**Comment by Josh-Diamond** [comment]
Ticket #38258 - Test Results [pt. 1]

With HA Helm:

RKE2 - Verified on rancher `v2.6-988b8d1f63c19b13f6afba9de2e34e30cac133a7-head`:
1. Fresh install of rancher `v2.6-head`
2. Provision a downstream RKE2 k8s 1.24 cluster
3. Verified - k8s 1.24 is available for RKE2 and cluster provisions successfully

K3s - Blocked - k8s 1.24 for k3s is currently unavailable

PR to track progress here: 
- https://github.com/rancher/kontainer-driver-metadata/pull/936
