### ISSUE TITLE
Catalogtemplates.management.cattle.io "cattle-global-data/system-library-rancher-monitoring" not found  but system-library is active

### ISSUE THREAD

**Issue by 631068264** [rancher/rancher#38250]
**Rancher Server Setup**
- Rancher version: 2.6.5
- Installation option (Docker install/Helm Chart):  docker install
 
install cmd   running **offline**
```
docker run -d --name rancher2.6.5 --restart=unless-stopped -e CATTLE_SYSTEM_CATALOG=bundled -e SSL_CERT_DIR="/container/certs" -v /root/xxxx/certs -p 3280:80 -p 3443:443 --privileged rancher/rancher:v2.6.5
```

<img width="941" alt="image" src="https://user-images.githubusercontent.com/8144089/178391025-b9ccb61c-0e90-42fb-abaa-5473dbf0d947.png">

<img width="1337" alt="image" src="https://user-images.githubusercontent.com/8144089/178391581-e48e591b-3451-4625-99c5-452f666166df.png">

I have set  `CATTLE_SYSTEM_CATALOG=bundled` and the **system-library** is active .  Why get error?

**Comment by shenhuan2021** [comment]
> **Rancher Server Setup**
> 
> * Rancher version: 2.6.5
> * Installation option (Docker install/Helm Chart):  docker install
> 
> install cmd running **offline**
> 
> ```
> docker run -d --name rancher2.6.5 --restart=unless-stopped -e CATTLE_SYSTEM_CATALOG=bundled -e SSL_CERT_DIR="/container/certs" -v /root/xxxx/certs -p 3280:80 -p 3443:443 --privileged rancher/rancher:v2.6.5
> ```
> 
> <img alt="image" width="941" src="https://user-images.githubusercontent.com/8144089/178391025-b9ccb61c-0e90-42fb-abaa-5473dbf0d947.png">
> 
> <img alt="image" width="1337" src="https://user-images.githubusercontent.com/8144089/178391581-e48e591b-3451-4625-99c5-452f666166df.png">
> 
> I have set `CATTLE_SYSTEM_CATALOG=bundled` and the **system-library** is active . Why get error?

Did you solve it？？？
