### ISSUE TITLE
1.18 and 1.19 RKE clusters fail to come up; cluster agents restart with error `fatal msg="looking up cattle-system/cattle ca/token: failed to find configmap containing the CA crt: configmaps \"kube-root-ca.crt\" not found`

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#38255]
**Rancher Server Setup**
- Rancher version: 2.6-head commit id `3506e4`
- Installation option (Docker install/Helm Chart): docker install

**Information about the Cluster**
- Kubernetes version: 1.18 and 1.19
- Cluster Type (Local/Downstream): Downstream - AWS - 1etcd, 1 cp and 1 worker nodes Node driver cluster

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) admin

   
**Describe the bug**

**To Reproduce**

- Deployed 1.18 and 1.19 clusters.
- Nodes come up Active.

**Result**

- Cluster is stuck in `Waiting for API to be available` state
- Error seen in cattle cluster agent on Control plane node:

```
INFO: Value from https://rancher-server/v3/settings/cacerts is an x509 certificate
time="2022-07-12T17:44:43Z" level=info msg="Listening on /tmp/log.sock"
time="2022-07-12T17:44:43Z" level=info msg="Rancher agent version 3506e43ce is starting"
time="2022-07-12T17:44:43Z" level=fatal msg="looking up cattle-system/cattle ca/token: failed to find configmap containing the CA crt: configmaps \"kube-root-ca.crt\" not found"
```
**Expected Result**
clusters should come up Active

**Note:**
1.20, 1.21 clusters RKE come up Active

**Comment by kinarashah** [comment]
Available to test after build https://drone-publish.rancher.io/rancher/rancher/8060 is green with v2.6-head.

**Comment by rishabhmsra** [comment]
Validated on rancher v2.6-head(2c21373), k8s v1.18.20-rancher1-3 and v1.19.16-rancher1-6 downstream node driver clusters provisioned successfully and coming into Active state. Issue is resolved, hence closing it.
