### ISSUE TITLE
Azure AD Auth Fails for Some Users After We Upgraded from 2.6.2 to 2.6.5

### ISSUE THREAD

**Issue by k8s42** [rancher/rancher#38267]
**Rancher Server Setup**
- Rancher version: 2.6.5
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1 (v1.3.11), Helm 3

**Information about the Cluster**
- Kubernetes version: 1.23.6

**User Information**
- What is the role of the user logged in? Admin
  
**Describe the bug**
Azure AD authentication for multiple users is not working after upgrading Rancher from 2.6.2 to 2.6.5. Users and I get a loading page when I try to log in using my Azure AD account. When I switch to the classic Rancher interface by adding **/g** at the end of the Rancher portal URL, I am able to login.

**To Reproduce**
 
1. With Azure AD auth enabled in your Rancher 2.6.5 instance (upgraded from 2.6.2), click on "Log in with AzureAD button).
2. Type in your Azure AD user account to authenticate.

**Result**
Page stays stuck in loading state (blue spinning circle). Sometimes I am presented with a "Logging in" message instead of the spinning blue circle.

**Expected Result**
Azure AD auth should work. 

**Additional context**

I am able to log in with a /g at the end of the Rancher URL, which is basically the classic interface. Under the "Users" section, I do not see my user account I am logging in with. I am able to view all other user accounts.

**Comment by garrmark** [comment]
I was having a similar login experience, but I used your workaround with the "/g" to login and then logged out.  Now I can login fine both ways.  Probably wont help you, but I appreciate the /g trick, thanks.
