### ISSUE TITLE
[Cattle] Add 'inspect' action to container to get the full docker inspect output

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#3826]

**Comment by QIvan** [comment]
Hi! Will this feature add to the rancher? 

I need this one because there is no way to show containers environment variables in rancher UI. 
Maybe is there feature-request fot adding new tab with environment variables in container overview?

**Comment by tfiduccia** [comment]
@QIvan - We are working on showing all container information in the container overview.  Should be seeing that soon.

**Comment by QIvan** [comment]
@deniseschannon @tfiduccia 
Hi again! Did you close this issue because it's implemented? Where can I see inspect of a container (I didn't find this info in the release notes)?

**Comment by vincent99** [comment]
[Almost] all the fields are shown in the UI in 1.2.x:

![image](https://cloud.githubusercontent.com/assets/753917/19123683/6fe3b7ac-8ae4-11e6-8aba-bd51e0be3edb.png)
