### ISSUE TITLE
Install Alibaba ack driver failed     X509 error for drivers.rancher.cn

### ISSUE THREAD

**Issue by cwdsuzhou** [rancher/rancher#38269]
**Rancher Server Setup**
- Rancher version: v2.6.0
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version:
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:

   
**Describe the bug**

Install Alibaba ack driver failed

Returning previous error: Get "https://drivers.rancher.cn/node-driver-aliyun/1.0.4/docker-machine-driver-aliyunecs.tgz": x509: certificate is valid for *.oss-cn-beijing.aliyuncs.com, *.cn-huhehaote-nebula-1.oss.aliyuncs.com, *.cn-huhehaote.oss.aliyuncs.com, *.oss-cn-wulanchabu-cross.aliyuncs.com, *.oss-enet-cm.aliyuncs.com, *.vpc100-oss-cn-huhehaote.aliyuncs.com, *.cn-north-2-gov-1.oss.aliyuncs.com, *.img-cn-beijing-internal.aliyuncs.com, *.oss-internal.aliyuncs.com, *.oss-cn-north-2-gov-1-internal.aliyuncs.com, *.oss-accelerate.aliyuncs.com, *.oss-cn-beijing-internal-cross.aliyuncs.com, *.oss-cn-qingdao.aliyuncs.com, *.oss-accelerate-overseas.aliyuncs.com, *.cn-wulanchabu.oss.aliyuncs.com, *.oss-cn-huhehaote.aliyuncs.com, *.oss-cn-huhehaote-cross.aliyuncs.com, *.aliyuncs.com, *.oss-cn-zhengzhou-nebula-1-internal.aliyuncs.com, *.oss-cn-beijing-internal.aliyuncs.com, *.oss-cn-beijing-cross.aliyuncs.com, *.oss.aliyuncs.com, *.oss-cn-huhehaote-nebula-1-cross.aliyuncs.com, *.oss-cn-huhehaote-internal.aliyuncs.com, *.img-cn-beijing.aliyuncs.com, *.oss-cn-huhehaote-nebula-1-internal.aliyuncs.com, *.img-cn-qingdao.aliyuncs.com, *.cn-qingdao.oss.aliyuncs.com, *.oss-enet.aliyuncs.com, *.oss-cn-huhehaote-nebula-1.aliyuncs.com, *.oss-cn-north-2-gov-1.aliyuncs.com, *.oss-enet-cu.aliyuncs.com, *.oss-enet-ct.aliyuncs.com, *.oss-cn-wulanchabu.aliyuncs.com, *.oss-cn-shanghai.aliyuncs.com, *.oss-cn-wulanchabu-internal.aliyuncs.com, *.vpc100-oss-cn-beijing.aliyuncs.com, *.vpc100-oss-cn-qingdao.aliyuncs.com, *.oss-cn-qingdao-internal.aliyuncs.com, *.cn-beijing.oss.aliyuncs.com, *.oss-cn-zhengzhou-nebula-1.aliyuncs.com, *.cn-zhengzhou-nebula-1.oss.aliyuncs.com, *.oss-cn-qingdao-cross.aliyuncs.com, *.oss-cn-qingdao-internal-cross.aliyuncs.com, *.oss-cn-qingdao-diku-internal.aliyuncs.com, *.cn-wulanchabu.oss-internal.aliyun-inc.com, *.oss-cache-cn-beijing-h.aliyuncs.com, *.oss-cache-cn-beijing-h-cross.aliyuncs.com, *.oss-internal.aliyun-inc.com, *.oss-cn-beijing-finance-1-pub-internal.aliyuncs.com, *.oss-cn-beijing-finance-1-pub.aliyuncs.com, *.cn-beijing-finance.oss.aliyuncs.com, *.oss-cn-beijing-finance-1-internal.aliyuncs.com, *.oss-cn-beijing-finance-1.aliyuncs.com, *.cn-beijing-finance-1.oss.aliyuncs.com, oss-cn-beijing.aliyuncs.com, not drivers.rancher.cn

**To Reproduce**
 

**Result**

**Expected Result**

**Screenshots**

**Additional context**

**Comment by niusmallnan** [comment]
@cwdsuzhou You can temporarily use this URL. https://rancher2-drivers.oss-cn-beijing.aliyuncs.com/node-driver-aliyun/1.0.4/docker-machine-driver-aliyunecs.tgz

The URL you mentioned is blocked by some mysterious agency.
