### ISSUE TITLE
Rancher 2.6.4 backup - UI not display validation error

### ISSUE THREAD

**Issue by wirwolf** [rancher/rancher#38272]
**Rancher Server Setup**
- Rancher version: v2.6.4
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): Kubespray
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.21.8
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Kubespray

**User Information**
- What is the role of the user logged in: Admin

**Describe the bug**
The system does not display validation errors when i try to create a new backup with wrong name

**To Reproduce**
Install rancher backups from Cluster Tools
Open Backups tab
Click to create a new backup
Type wrong name - "Wrong Name Not RFC 1123 Standart"
Click to create

**Result**
![image](https://user-images.githubusercontent.com/8457572/178977563-c410867b-4167-4e3d-9b74-a6c53384974e.png)

**Expected Result**
System display error text

**Screenshots**

**Additional context**
![](https://visitor-badge.glitch.me/badge?page_id=rancher_rancher_issues_38272)

**Comment by niusmallnan** [comment]
It will be used as the name of CR(`backups.resources.cattle.io`) and is limited by the specification of the k8s API.

I recommend that you transfer this issue to `rancher/dashboard`, which can be optimized from a UI perspective.

**Comment by wirwolf** [comment]
Okey. I need to recreate this issue in rancher/dashboard or you have some permission to migrate current issue?

**Comment by niusmallnan** [comment]
I don't have permission either... 😂
