### ISSUE TITLE
[RKE2] Unable to rotate encryption keys after rotating once

### ISSUE THREAD

**Issue by timhaneunsoo** [rancher/rancher#38277]
**Rancher Server Setup**
- Rancher version: v2.6-head 2c21373
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version:
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

Node driver cluster
**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Admin/Standard user who is Cluster Owner
   
**Describe the bug**

After rotating the secret encryption keys, user is unable to rotate keys again. The message logged is
```
[INFO ] waiting for encryption key rotation [Prepare] for machine [<machine-name>]
[INFO ] provisioning done
```
Alternatively, sometimes these errors get logged
```
[INFO ] waiting for encryption key rotation [Prepare] for machine [<machine-name>]
[ERROR] Operation cannot be fulfilled on machines.cluster.x-k8s.io "<machine-name>": the object has been modified; please apply your changes to the latest version and try again
[INFO ] provisioning done
```

**To Reproduce**
 
1. Create RKE2 EC2 cluster
2. Create secrets
3. Rotate encryption keys
4. Wait for keys to rotate
5. Rotate encryption keys again

**Result**
Rancher seems to try rotating but then just ends the process

**Expected Result**

Keys should be able to rotate after being rotated once.

**Comment by thaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6-head b66dd0f
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: RKE2 

----------

### Testing: ###

Tested this issue with the following steps:
1. Create cluster with 3 etcd, 2 cp, 3 worker
2. Create secret
3. ssh into etcd node, use root user (`sudo -i`) and create `install-etcdctl.sh` with the following script
```
#!/bin/bash
ETCD_VER=v3.5.0
 
# choose either URL
GOOGLE_URL=https://storage.googleapis.com/etcd
GITHUB_URL=https://github.com/etcd-io/etcd/releases/download
DOWNLOAD_URL=${GOOGLE_URL}
 
rm -f /tmp/etcd-${ETCD_VER}-linux-amd64.tar.gz
rm -rf /tmp/etcd-download-test && mkdir -p /tmp/etcd-download-test
 
curl -L ${DOWNLOAD_URL}/${ETCD_VER}/etcd-${ETCD_VER}-linux-amd64.tar.gz -o /tmp/etcd-${ETCD_VER}-linux-amd64.tar.gz
tar xzvf /tmp/etcd-${ETCD_VER}-linux-amd64.tar.gz -C /tmp/etcd-download-test --strip-components=1
rm -f /tmp/etcd-${ETCD_VER}-linux-amd64.tar.gz
 
/tmp/etcd-download-test/etcd --version
/tmp/etcd-download-test/etcdctl version
/tmp/etcd-download-test/etcdutl version
cp /tmp/etcd-download-test/etcdctl /usr/local/bin/etcdctl
etcdctl version
```
4. chmod +x install-etcdctl.sh
5. Run the following command to make sure etcdctl is working
```
sudo ETCDCTL_API=3 etcdctl --cert /var/lib/rancher/rke2/server/tls/etcd/server-client.crt --key /var/lib/rancher/rke2/server/tls/etcd/server-client.key --endpoints https://127.0.0.1:2379 --cacert /var/lib/rancher/rke2/server/tls/etcd/server-ca.crt get /registry/secrets/default/<name_of_secret> | hexdump -C
```
6. Rotate secret encryption keys using the UI button as shown below
![image.png](https://zube.io/files/rancher/0598130b772f55d08e4d718e4d0b607c-image.png)
7. Use the command from step 5 to verify keys were rotated. Pay attention to time stamp on the encryption
8. Rotate secret encryption keys again
9. Use the command from step 7 to verify keys were rotated. Verify that time stamp is now different than step 7, also the encrypted value is now different from step 7
10. Verify in rancher logs that rotation process was logged and process was completed.

**Result** - Pass

User is now able to rotate encryption keys multiple times
