### ISSUE TITLE
`Invalid value: "cluster-name-c-xx-rs-cwn4m_2022-03-24T20:07:42Z.zip-s3"` error during etcd snapshot on RKE2 cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#38304]
**Rancher Server Setup**
- Rancher version: 2.6head - `07ee596`
- Installation option (Docker install/Helm Chart): docker install

**Information about the Cluster**
- Kubernetes version: `v1.23.8+rke2r1`
- Cluster Type (Local/Downstream): AWS Node driver - 1 node all roles

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) admin

**Describe the bug**
RKE2 cluster - S3 etcd snapshot issues

**To Reproduce**

- Deploy a 1 node RKE2 cluster wth S3 enabled etcd snapshots
<img width="1649" alt="Screen Shot 2022-07-17 at 11 20 21 AM" src="https://user-images.githubusercontent.com/26032343/179419460-b65189cf-bae9-4f65-8a3e-61766ca1bc14.png">

- When the cluster comes up Active, take a snapshot on the cluster 

**Result**
**Error Logs:**
- Also Error in Rancher logs:
```
2022/07/17 15:21:35 [INFO] [snapshotbackpopulate] rkecluster fleet-default/sowmya-4-aws: processing configmap kube-system/rke2-etcd-snapshots
2022/07/17 15:21:35 [ERROR] error syncing 'kube-system/rke2-etcd-snapshots': handler snapshotbackpopulate: rkecluster fleet-default/sowmya-4-aws: error while creating s3 etcd snapshot fleet-default/sowmya-4-aws-c-t9kx4-rs-d24f5_2022-03-25T08:12:42Z.zip-s3: ETCDSnapshot.rke.cattle.io "sowmya-4-aws-c-t9kx4-rs-d24f5_2022-03-25T08:12:42Z.zip-s3" is invalid: metadata.name: Invalid value: "sowmya-4-aws-c-t9kx4-rs-d24f5_2022-03-25T08:12:42Z.zip-s3": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), requeuing
```
**Note:**
- This does not happen on `2.6.6`

**Comment by Oats87** [comment]
Pretty sure this is caused due to a change on K3s/RKE2: https://github.com/k3s-io/k3s/pull/5703 and is not necessarily a regression on the Rancher side.

**Comment by snasovich** [comment]
@sowmyav27 , I don't believe this is a regression as previously we wouldn't even receive any updated snapshots from RKE2 in this situation as there was no fix https://github.com/k3s-io/k3s/pull/5703 present. So Rancher didn't even get to the code that throws this error.

**Comment by sowmyav27** [comment]
After an offline conversation with @Oats87 this error is seen when there are invalid snapshots in the S3 bucket (snapshots with bad name). 

- When I used an empty S3 bucket, no errors were seen in Rancher logs. 
- `etcd` restore using the created local snapshot does not work

**Comment by sowmyav27** [comment]
**On 2.6head commit id: `c47178e`**

**Scenario 1**
- Deployed an AWS Node driver cluster - 1 node all roles, 1 worker node - `v1.24.2+rke2r1`
- Set ETCD snapshot to S3
- After the cluster came up Active, Take a snapshot s1 on the cluster
- Deploy some workloads on the cluster
- Restore to snapshot - s1 `etcd` restore from the local snapshot
- The cluster goes into Updating state and comes back Active
- Verified the workloads are not available on the cluster.
---
**Scenario 2**
- Deployed an AWS Node driver cluster - 1 node all roles, 1 worker node - `v1.24.2+rke2r1`
- After the cluster came up Active, Take a snapshot s1 on the cluster
- Deploy some workloads on the cluster
- Restore to snapshot - s1 using `all` restore from the local snapshot
- The cluster goes into Updating state and comes back Active
- Verified the workloads are not available on the cluster.

**Comment by jonathon2nd** [comment]
I have been seeing this for a little bit, and wanted to chime in
I have ensured that the s3 buckets do not contain anything strange in them.

```
2023/05/08 18:40:15 [INFO] [snapshotbackpopulate] rkecluster fleet-default/new-production: processing configmap kube-system/rke2-etcd-snapshots
2023/05/08 18:40:15 [INFO] [snapshotbackpopulate] rkecluster fleet-default/new-preprod: processing configmap kube-system/rke2-etcd-snapshots
2023/05/08 18:40:15 [ERROR] rkecluster fleet-default/new-production: error while creating s3 etcd snapshot fleet-default/new-production-.-s3: ETCDSnapshot.rke.cattle.io "new-production-.-s3" is invalid: metadata.name: Invalid value: "new-production-.-s3": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
2023/05/08 18:40:18 [INFO] [snapshotbackpopulate] rkecluster fleet-default/new-preprod: processing configmap kube-system/rke2-etcd-snapshots
```

**Comment by sba30** [comment]
We tried the same, renaming the folder, and when we renamed it back the snapshot worked, but a couple days later the issue starts up again
