### ISSUE TITLE
RKE2 cluster - Local etcd snapshots is taken on a cluster where S3 etcd snapshots are enabled

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#38302]
**Rancher Server Setup**
- Rancher version: 2.6head - `07ee596`
- Installation option (Docker install/Helm Chart): docker install

**Information about the Cluster**
- Kubernetes version: `v1.23.8+rke2r1`
- Cluster Type (Local/Downstream): AWS Node driver - 1 node all roles

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) admin

**Describe the bug**
RKE2 cluster - Local etcd snapshots is taken on a cluster where S3 etcd snapshots are enabled

**To Reproduce**
Deploy a 1 node RKE2 cluster wth S3 enabled etcd snapshots
When the cluster comes up Active, take a snapshot on the cluster 

**Issue 1**

- local etcd snapshot is generated. 
- This issue is seen on 2.6.6 also

**Expected:**
Local etcd snapshots should not be taken when S3 enabled cluster is deployed.

**Comment by Oats87** [comment]
This is expected behavior, and stems from K3s/RKE2 behavior. The supervisor/engine keeps a local copy and a remote copy of snapshots, and made changes on the Rancher side to reflect this.

**Comment by snasovich** [comment]
@Oats87 , based on your explanation above as well as some side conversations we've had, I'm assuming this is actually beneficial and was done on purpose. Should we close this as "functions as designed"?

**Comment by jakefhyde** [comment]
@snasovich This should be closed as functions as designed, as this is also in parity with RKE1 snapshots.
