### ISSUE TITLE
Deployments flapping regarding deployment generation[BUG]

### ISSUE THREAD

**Issue by MarM25** [rancher/rancher#38319]
**Rancher Server Setup**
- Rancher version: 2.6.5
- Installation option (Docker install/Helm Chart): Helm Chart
   - Cluster k3s v1.23.6+k3s1 (also on v1.21.11+k3s1)

**Information about the Cluster**
- Kubernetes version: v1.23.6+k3s1 (also on v1.21.11+k3s1)
- Cluster Type (Local/Downstream): Local

**User Information**
- What is the role of the user logged in? Admin/Cluster Owner

**Describe the bug**
Deployments switching randomly from "Active" to "In Progress" and back, with following warning:
" Deployment generation is 37446, but latest observed generation is 37444 "
(Number is increasing, Interval of switching ~1-5 seconds)
Independend from Deploymenttype, custom from company or official
Seems to affect only containers with network endpoint. I guess a Network error, but dont know what exactly or how to debug.

**Screenshots**
(Kafka only for example, affects other deployments like databases, identitybroker and rev proxy too)

![grafik](https://user-images.githubusercontent.com/20906996/179719421-a34781d6-1773-43a6-80ab-a4371014b8d4.png)

**Comment by heartcored98** [comment]
I experienced exactly same issue. Deployment generation is increased very quickly. But can't find the cuase. So fraustrating..

**Comment by artemus717** [comment]
I experienced exactly same issue
Rancher 2.8.3
Kubernetes 1.24.17

**Comment by vincentduprez** [comment]
having the same issue
