### ISSUE TITLE
[BUG] some kube-system network jobs are not updating after upgrading from 1.23 -> 1.24 on a SLES custom rke1 cluster

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#38324]
**Rancher Server Setup**
- Rancher version: v2.6.7-rc3
- Installation option (Docker install/Helm Chart): helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): rke1, 1.3.12
- Proxy/Cert Details: valid (letsencrypt) certs)

**Information about the Cluster**
- Kubernetes version: 1.24.2
- Cluster Type (Local/Downstream): downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): custom, rke1 using SLES 15.3

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): standard user (cluster owner)

**Describe the bug**
After upgrading from 1.23.7 -> 1.24.2, the cluster is in a healthy state however the following **jobs** failed to update the hyperkube version to 1.24.2:
* ingress-controller
* metrics-addon
* network-plugin

**To Reproduce**
* deploy rancher 2.6.6 with a custom RKE cluster using 1.23.7 
* upgrade rancher to 2.6.7-rc3
* upgrade the custom cluster to 1.24.2
* wait for the cluster to upgrade

**Result**
the upgrade is successful, however the aforementioned jobs do not use a new version

**Expected Result**
expecting all workloads to use a newer version

**Screenshots**
![Screen Shot 2022-07-18 at 3 32 10 PM](https://user-images.githubusercontent.com/16691014/179790174-2199d437-710c-4e32-ae94-0c65705db2d6.png)

**Additional context**
* this was found during release testing
* coredns-addon job did successfully upgrade
* this does not happen on an upgrade from 1.22 -> 1.23

**Comment by jiaqiluo** [comment]
This behavior is expected. 

The addon deploy jobs are re-deployed when the conressponding configMaps are changed after upgrading the cluster. 
In this case, after we upgrade the RKE1 cluster from `v1.23.7-rancher1-1` to `v1.24.2-rancher1-1`, only the configMap `rke-coredns-addon` is changed. Therefore only the job `rke-coredns-addon` is redeployed. 


sending this back to QA. Be free to close it.

**Comment by slickwarren** [comment]
retested, and closing in favor of a new enhancement ticket so that we can track the inconsistency. see above link
