### ISSUE TITLE
[BUG] Harvester Cloud Provider is not able to deploy upgraded container after upgrading the cluster

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#38336]
**Rancher Server Setup**
- Rancher version: v2.6.7-rc3
- Installation option (Docker install/Helm Chart): docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.23.8+rke2r2 -> 1.23.9-rc3+rke2r1
- Cluster Type (Local/Downstream): downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): harvester

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): standard user, cluster owner

**Describe the bug**
upgrade from 1.23.x -> rc’d version updates the chart HOWEVER the deployment is not successfully deploying the new container with version 0.1.4

**To Reproduce**
* deploy a harvester downstream cluster through rancher using the node driver and k8s 1.23.8
  * observe the old versions of the chart are used
* change the KDM to one that has the RC'd versions available
* upgrade the cluster to 1.23.x-rc3

**Result**
the harvester cloud provider container is not updating properly

**Expected Result**

Chart workloads and pods should successfully upgrade

**Screenshots**
![Screen Shot 2022-07-19 at 12 10 40 PM](https://user-images.githubusercontent.com/16691014/179852381-8f933371-727a-47a7-847c-66546630f278.png)

**Additional context**

fresh install of rc version is working fine.

**Comment by chrisho** [comment]
Where can I get the KDM RC'd version??

**Comment by rancher-max** [comment]
> Hi, Where can I get the KDM RC'd version??

https://raw.githubusercontent.com/matttrach/kontainer-driver-metadata/july-release-rke2/data/data.json

**Comment by chrisho** [comment]
> > Hi, Where can I get the KDM RC'd version??
> 
> https://raw.githubusercontent.com/matttrach/kontainer-driver-metadata/july-release-rke2/data/data.json

Thanks!

**Comment by slickwarren** [comment]
tested using rancher v2.6.7-rc5 and harvester v1.0.3-rc1:
* v1.23.8+rke2r2 -> 1.23.9+rke2r1 -- pass
* v1.23.8-rancher1-1 -> 1.24.2-rancher1-1 -- pass
  * tested with/without cloud provider
