### ISSUE TITLE
[BUG] Memory leak in cluster provisioning/deletion process

### ISSUE THREAD

**Issue by MbolotSuse** [rancher/rancher#38330]
**Rancher Server Setup**
- Rancher version: 2.6.6
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1
- Proxy/Cert Details: Self-signed

**Information about the Cluster**
- Kubernetes version: v1.22.4-rancher1-1
- Cluster Type (Local/Downstream): Local

**User Information**
- What is the role of the user logged in? Admin

**Describe the bug**
After a cluster is provisioned and deleted, rancher idles consuming more memory than before.

**To Reproduce**
1. Start rancher.
2. Log into rancher. Wait a short period for rancher to fully initialize.
3. Take a memory reading of all rancher pods using the below command.
4. Create an RKE1 cluster on digital ocean.
5. Wait for the cluster to fully provision.
6. Delete the RKE1 cluster.
7. Take a memory reading of all rancher pods using the below command.

Memory command:
```bash
#!/bin/bash
pods=$(kubectl get pods -l=app=rancher -n cattle-system | cut -d ' ' -f 1 | tail -n +2)
current=0
for pod in $pods;
do
	metrics=$(kubectl top pod $pod -n cattle-system);
	memory=$(echo "$metrics" | tr -s ' ' | cut -d ' ' -f 3 | tail -n +2 | tr -d "Mi");
	current=`expr $current + $memory`
done
echo $current

```

These reading can also be taken every five seconds for a period of 5 minutes using a container command like below (assuming the memory command is in `get_metrics.sh`):
```bash
#!/bin/bash
for ((n=0;n<60;n++))
do
	bash get_metrics.sh >> $1
	sleep 5
done
```

**Result**
The second memory reading is higher than the first.

**Expected Result**
The first memory reading should be equal to the second memory reading, since rancher is managing mostly the same number of resources.

**Additional context**
- Restarting rancher will bring the memory usage back down
- This will continually occur on subsequent cluster creation/deletion (i.e. if you create another cluster and delete it, the memory will go up- it's not just a one-time event)

SURE-4226

**Comment by cbron** [comment]
Bumping

**Comment by MbolotSuse** [comment]
## Validation Template

## Root Cause

Steve maintains a cache of user schemas to avoid re-creating these complex objects each time the api is accessed. This cache has a key which represents a hash of the roles/cluster roles that the user has access to (in short, if a user is bound to a new role or cluster role, this key will change regardless of if the user's effective permissions changed). When a user gets access to a new role or cluster role, this key will change and the schemas will be re-generated. However, the old schemas, which still take up substantial memory, are never removed. This leads to a leak, since when a cluster is provisioned, it will bind the user who created the cluster to a cluster-owner role, causing the key to be re-calculated and new schemas to be generated.

## What was fixed, or what change have occurred

Steve now maintains a second cache mapping a user name to the current access cache key. This way, when a user's cache key is re-calculated, it can remove the old entry so that only one schema exists for a given user in the cache at any one given time. 

## Areas or cases that should be tested

1. Original issue.
2. General steve response time. (see regressions for more details)
3. Memory usage of steve overall (see notes on how to accomplish this). 

## What areas could experience regressions

Steve response time. This change causes Steve to clear the cache more frequently. In theory, if there is a bug with this process, this could lead to Steve having a slower response time, which would be undesirable. 

## Are the repro steps accurate/minimal?

Yes. They included here for convenience:
1. Install rancher on an HA setup 
2. Wait 5 minutes.
3. Deploy a new RKE cluster on digital ocean as a downstream cluster.
4. Wait for the cluster to fully provision.
5. Delete the cluster
6. Wait 5 minutes.
7. Take another memory reading
8. Note that the second memory reading is higher than the first.

## Notes

### General Notes
- The 5 min buffer time in the reproduction steps is meant to give various parts of the provisioning process time to legitimately release memory, but is overall arbitrary.
- Taking a single memory reading and comparing can lead to inaccuracy in data. It is recommended to take a 5 min reading (as described in the issue) and compare this larger reading. I have a python script (available on request) which you can use to produce a graph that allows easy comparison of these values.
- This fix is not expected to fix every memory leak. Overall memory usage will still be higher after the cluster is deleted. We are aiming with this change to make it "less higher" (if that makes sense), and specifically to not go up in the areas of steve that this is targeting

### Actions that will invalidate test cases
There are legitimate reasons why memory usage could increase in this area. I'm including these reasons here to help maintain test integrity.

- Adding new users. The steve cache will store a schema entry for each user that has interacted with rancher. Adding new users could legitimately increase the size of the value in the cache.
- Adding new charts/CRDs. Schemas are produced for each type of resource available in the local cluster. If you install something in the local cluster which adds new custom resources, these could increase in size
- Adding new permissions. Schemas will grow based on the number of resource types a user has access to. If a user is given a new permission which allows them new permissions on a CR, the schema size will grow. For example, if before I had access to 1 schema (say clusters) taking up 1 mb of memory, and after I have 2 schemas (clusters and cluster role template bindings) each taking up 1 mb of memory, I will have an increase of 1mb memory. But this is perfectly legitimate.

### Steve Memory usage/analysis
You can use pprof to extract/analyze memory usage in an attempt to ensure that excess memory usage is not due to steve.

First, extract the current memory usage:

```bash
#!/bin/bash 
for pod in $(kubectl get pods --no-headers -l app=rancher -n cattle-system | cut -d ' ' -f 1); do
        echo getting heap for $pod
        kubectl exec $pod -n cattle-system -- curl -s http://localhost:6060/debug/pprof/heap -o heap;
        kubectl cp -n cattle-system $pod:heap $pod-heap;
        echo saved heap $pod-heap;
done
```

This will produce a file for each rancher pod in the current directory, named `$POD_NAME-heap`.

Next, use pprof to combine these files into a more readable/usable format:

```bash
go tool pprof $HEAP_1 $HEAP_2 $HEAP_3
svg
```
Note that this makes use of additional tools to generate a browser-friendly reading. You can also use `top` to see the top uses of memory without installing additional tools.

If you choose to use the svg, this will output a file (name given in command line) which you can open with your browser. This will show top users of memory. We are attempting to avoid excessive memory use of the `NewSchemas` owned objects (look for schema related methods which are traceable back to steve's package).

**Comment by brudnak** [comment]
# ✅ PASSED

## Reproduction Environment

| Component                        | Version / Type                                   |
|----------------------------------|--------------------------------------------------|
| Rancher version                  | 2.6.7                                            |
| Installation option              | Helm (high availability)                         |
| If Helm Chart k8s cluster        | v1.24.6+k3s1                                     |
| Cert Details                     | Let's Encrypt / `traefik`                        |
| k3s ha external db               | Aurora MySQL 5.7.mysql_aurora.2.10.2             |
| Helm version                     | v2.16.8-rancher2                                 |
| Downstream cluster type          | RKE1 Linode                                      |
| Downstream K8s version           | v1.24.4-rancher1-1                               |
| Authentication providers enabled | local                                            |
| Logged in user role              | Administrator                                    |
| Browser type                     | Google Chrome                                    |
| Browser version                  | Version 106.0.5249.103 (Official Build) (x86_64) |

<details>
    <summary>🚨 Additional Reproduction Setup Details: Click to Expand</summary>

```shell
curl -sfL https://get.k3s.io | sh -s - server \
  --token=SECRET \
  --datastore-endpoint=$ENDPOINT_VAR \
  --tls-san $URL_VAR \
  --node-external-ip $IP_VAR
```

</details>


## Reproduction steps

- Start rancher.
- Log into rancher. Wait a short period for rancher to fully initialize
- Take a memory reading of all rancher pods using the below command
- Create an RKE1 cluster on linode
- Wait for the cluster to fully provision
- Delete the RKE1 cluster
- Take a memory reading of all rancher pods
- See the screenshot below under `Additional Info`

## Additional Info

Schemas size coming originating from `http HandlerFunc ServeHTTP` `BEFORE` ==> `15.35MB`
Schemas size coming originating from `http HandlerFunc ServeHTTP` `AFTER` ==> `104.23MB`

<img width="640" alt="001-2-6-7" src="https://user-images.githubusercontent.com/40877149/194679058-c4c2a43e-fec8-4da7-9cda-99fcc3cc2096.png">

## RESULTS

#### ✅ Expected

I'd expect for the memory reading to be closer to the original point after deleting the downstream cluster and waiting 5 minutes

#### ❌ Actual

The memory reading is significantly higher after deleting the downstream cluster and waiting 5 minutes

<hr>

## Validation Environment


| Component                        | Version / Type                                   |
|----------------------------------|--------------------------------------------------|
| Rancher version                  | 2.7.0-rc3                                        |
| Installation option              | Helm (high availability)                         |
| If Helm Chart k8s cluster        | v1.24.6+k3s1                                     |
| Cert Details                     | Let's Encrypt / `traefik`                        |
| k3s ha external db               | Aurora MySQL 5.7.mysql_aurora.2.10.2             |
| Helm version                     | v2.16.8-rancher2                                 |
| Downstream cluster type          | RKE1 Linode                                      |
| Downstream K8s version           | v1.24.4-rancher1-1                               |
| Authentication providers enabled | local                                            |
| Logged in user role              | Administrator                                    |
| Browser type                     | Google Chrome                                    |
| Browser version                  | Version 106.0.5249.103 (Official Build) (x86_64) |


<details>
    <summary>🚨 Additional Validation Setup Details: Click to Expand</summary>

```shell
curl -sfL https://get.k3s.io | sh -s - server \
  --token=SECRET \
  --datastore-endpoint=$ENDPOINT_VAR \
  --tls-san $URL_VAR \
  --node-external-ip $IP_VAR
```

</details>

## Validation steps

- Start rancher.
- Log into rancher. Wait a short period for rancher to fully initialize
- Take a memory reading of all rancher pods using the below command
- Create an RKE1 cluster on linode
- Wait for the cluster to fully provision
- Delete the RKE1 cluster
- Take a memory reading of all rancher pods
- See the screenshot below under `Additional Info`

## Additional Info

Schemas size coming originating from `http HandlerFunc ServeHTTP` `BEFORE` ==> `15.50MB`
Schemas size coming originating from `http HandlerFunc ServeHTTP` `AFTER` ==> `40.13MB`

![002-2-7-head](https://user-images.githubusercontent.com/40877149/194679070-9f276c7f-0abb-479a-b0e9-37fec0d422e7.png)

## RESULTS

#### ✅ Expected
I'd expect for the memory reading to be closer to the original point after deleting the downstream cluster and waiting 5 minutes

#### ✅ Actual
The memory reading is closer to the original point after deleting the downstream cluster and waiting 5 minutes


## 📋 QA Test Plan

<table>
    <tbody>
        <tr>
            <th>Scenario</th>
            <th>Steps</th>
            <th>Expected</th>
            <th>Actual & Pass/Fail</th>
        </tr>
        <tr>
            <td>Upgrade from 2.6.7 to 2.7.0-rc3</td>
            <td>
                <ol>
                    <li>Start with fresh Rancher</li>
                    <li>Upgrade from 2.6.7 to 2.7.0-rc3</li>
                    <li>Create downstream</li>
                    <li>Delete downstream</li>
                    <li>Wait 5 minutes</li>
                    <li>Take memory readings</li>
                </ol>
            </td>
            <td>Expected: Memory usage to stay within reasonable range and not spike severely</td>
            <td>Actual: Memory stayed within reasonable range<br><br>Pass/Fail: ✅<code>PASS</code></td>
        </tr>
    </tbody>
</table>
