### ISSUE TITLE
Change from 1.20 to 1.21 resulted in Networking tab missing in Edit Config page on rke2 provisioned cluster? 

### ISSUE THREAD

**Issue by gaktive** [rancher/rancher#38343]
UI received https://github.com/rancher/dashboard/issues/5866 from @ShylajaDevadiga (specifically https://github.com/rancher/dashboard/issues/5866#issuecomment-1187878844) about a missing Networking tab for the specific Kubernetes 1.21 version. The Networking tab is missing in the Edit Config page. Issue is seen in v1.21.12-rke2r1 only or any 1.21 version but not in later versions.

The UI team suspects that 1.22 introduced another annotation or some other metadata to render the tab but we're not clear what changed from 1.21 to 1.22. 

Reported in Rancher version: v2.6.5-rc8 but also v2.6.7-rc2
RKE2 Version: v1.21.12-rke2r1

To Reproduce
Provision a rke2 cluster version v1.21.12-rke2r1 in 2.6.4 and upgrade rancher version to 2.6.5-rc8. (@ShylajaDevadiga what was the behaviour in 2.6.5 RC7 and lower?)

Expected Result
Networking tab is missing in Edit Config page

Actual Result
Networking tab should be present in Edit Config page

Linked Dashboard item has additional information.

**Comment by HarrisonWAffel** [comment]
@ShylajaDevadiga 

RKE2 in 2.6.4 was offered as a `Tech preview`, but went GA in 2.6.5. After creating a rancher-server running 2.6.5 and attempting to create an RKE2 cluster I am not able to select 1.21.x as a k8's version.  So, when bringing a RKE2 cluster running 1.21.x from 2.6.4 to 2.6.5 the cluster has a k8's version that is considered 'unsupported' 

This is denoted by the UI, when attempting to edit the cluster config the `Basics` tab states `Configuration information is not available for the selected Kubernetes version. The options available in this screen will be limited, you may want to use the YAML editor.`. 

Looking at the dashboard code I can see that this message is dependent on the `haveArgInfo` variable equaling `false.` This variable is also used when rendering the `Advanced` tab, and the `Networking` Tab. When editing the 1.21.x cluster created in 2.6.4 after upgrading to 2.6.5, the `Advanced` tab is completely empty, but the tab still exists in the list of options. This makes sense considering the following block of code used to render the tab

```
 <Tab
  name="advanced"
  label-key="cluster.tabs.advanced"
  :weight="-1"
  @active="refreshYamls"
 >
  <template v-if="haveArgInfo">
...
```
It looks like the tab is always rendered irregardless of the `haveArgInfo` value, but its contents are not. However, for the Networking tab this is not the case. 

```
  <Tab v-if="haveArgInfo" name="networking" label-key="cluster.tabs.networking">
    <h3>
      {{ t('cluster.rke2.address.header') }}
      <i v-tooltip="t('cluster.rke2.address.tooltip')" class="icon icon-info" />
    </h3>
...
```
Here, the rendering of the entire tab is based off of the value of `haveArgInfo`. 

The decision to not support 1.21.x for RKE2 in 2.6.5 was purposeful, so I'm not sure if there is any work required from the backend at this point.

**Comment by Sahota1225** [comment]
Based on this comment https://github.com/rancher/dashboard/issues/5866#issuecomment-1244555143 closing the issue.
