### ISSUE TITLE
Bump RKE2/K3s default version to 1.24 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#38348]
Bump the default version of RKE2/K3s to 1.24

**Comment by jiaqiluo** [comment]
can be tested on the latest v2.6-head

you may need to wait a few mins or refresh the Kubernetes metadata manually to see the changes applied.

**Comment by slickwarren** [comment]
tested on v2.6-head (c47178e):
* custom cluster default version for rke2 is 1.24.x
* node driver default version is 1.24.x
* 1.24.x is no longer marked as experimental for rke2/k3s
