### ISSUE TITLE
Logging v1 images not listed in rancher-images.txt 2.6.7-rc3

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#38356]
**Rancher Server Setup**
- Rancher version: 2.6.7-rc3
- Installation option: Helm chart Airgap HA
   - If Helm Chart, Kubernetes Cluster and version: RKE1
- Proxy/Cert Details: No proxy, valid certificates

**Information about the Cluster**
- Kubernetes version: `v1.20.15-rancher2-1`
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster?: Custom RKE1

**User Information**
- What is the role of the user logged in? Admin

**Describe the bug**
When installing the logging v1 legacy app in a downstream kubernetes cluster in `v2.6.7-rc3` there are ImagePullBackoff errors and the fluentd images are not listed in the release's rancher-images.txt

**To Reproduce**
- Airgap Rancher install
- Downstream cluster with k8s version `1.20` support for Logging v1 is no longer available on k8s `1.21`
- Enable Legacy Features
- Navigate to the Downstream Cluster cluster tools
- Enable Logging v1 with one of the logging providers (I used fluentd)

**Result**

App is installed but the deployments are showing ImagePullBackOff errors.

```
ImagePullBackOff: Back-off pulling image "<REGISTRY>/rancher/fluentd:v0.1.30"
ImagePullBackOff: Back-off pulling image "<REGISTRY>/rancher/configmap-reload:v0.3.0-rancher4"
```

**Expected Result**
App and its deployments are active and functional in the downstream cluster. No ImagePullBackOff errors.

**Comment by MKlimuszka** [comment]
This has been this way since 2.6.3. So we cannot fix it in 2.6.7 in time. Our next release will be 2.7.0 where we will be removing v1 charts, so we will not be fixing that with this.
