### ISSUE TITLE
Istio v2 chart tries to pull mirrored-kiali-kiali:v1.50.0 but it's not listed in rancher-images.txt 2.6.7-rc3

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#38358]
**Rancher Server Setup**
- Rancher version: 2.6.7-rc3
- Installation option: Helm chart Airgap HA
   - If Helm Chart, Kubernetes Cluster and version: RKE1
- Proxy/Cert Details: No proxy, valid certificates

**Information about the Cluster**
- Kubernetes version: `v1.20.15-rancher2-1`
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster?: Custom RKE1

**User Information**
- What is the role of the user logged in? Admin

**Describe the bug**
When installing the Istio v2 app 100.3.0+up1.13.3 the chart creates the kiali deployment that's trying to pull:
`rancher/mirrored-kiali-kiali:v1.50.0`

But rancher-images.txt lists only
```
rancher/mirrored-kiali-kiali:v1.17
rancher/mirrored-kiali-kiali:v1.35.0
rancher/mirrored-kiali-kiali:v1.52.0
```

This prevents the chart to install correctly with the default values.

**To Reproduce**
- Airgap Rancher install
- Downstream cluster RKE1
- Navigate to Cluster -> Apps -> Charts
- Install the required (Monitoring v2)
- Then click over Istio and install with the default values.

**Result**

App is installed but the deployment is showing ImagePullBackOff errors in the `kiali` deployment in the `istio-system` namespace

**Expected Result**
App and its deployments are active and functional in the downstream cluster. No ImagePullBackOff errors.

**Comment by samkulkarni20** [comment]
@izaac As mentioned by @PennyScissors [here](https://github.com/rancher/rancher/issues/38357#issuecomment-1192765809) this is intended behavior & users will need to use the version specific release artifacts to install the charts.

**Comment by izaac** [comment]
@samkulkarni20 
I will do another round of testing as I'm not sure why the latest chart version on dev-2.6 wasn't listed as an install option in my Airgap setup when I did this.

https://github.com/rancher/rancher/issues/38357#issuecomment-1195726227

**Comment by izaac** [comment]
Rancher version: `v2.6.7-rc5`
rancher-istio:100.4.0+up1.14.1


I was able to install the latest chart version of Istio and the kiali image was pulled correctly for it `mirrored-kiali-kiali:v1.52.0`. No need to add images other than what's in the rancher-images.txt
