### ISSUE TITLE
[BUG] CSP Adapter invalid product string

### ISSUE THREAD

**Issue by MbolotSuse** [rancher/rancher#38351]
**Rancher Server Setup**
- Rancher version: 2.6.7-rc1, adapter version 1.0.0-rc3
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): EKS 1.22
- Proxy/Cert Details: Self-signed

**User Information**
- What is the role of the user logged in? Admin

**Describe the bug**
When the supportconfig bundle is generated the product string includes a v in rancher's version, like below:
```
cpe:/o:suse:rancher:v2.6.6
```

**To Reproduce**
1. Deploy rancher.
2. Manually edit the `server-version` setting to mock a production rancher version of `v2.6.6.`
3. Complete the csp adapter pre-requisites
4. Install the csp adapter
5. Generate a supportconfig bundle
6. Extract the bundle, and view the `rancher/config.json` file in the bundle

**Result**
The product string reads `cpe:/o:suse:rancher:v2.6.6`

**Expected Result**
The product string should not contain a v in rancher's version, like `cpe:/o:suse:rancher:2.6.6`

**Comment by brudnak** [comment]
# :white_check_mark: PASSED

## Reproduction Environment

| Component                 | Version / Type                            |
| ------------------------- | ----------------------------------------- |
| Rancher version           | 2.6.7-rc3                                 |
| CSP Adapter version       | 🚨 rancher-csp-adapter:1.0.0+up1.0.0-rc3 🚨 |
| Installation option       | eks via eksctl                            |
| If Helm Chart k8s cluster | v1.22.10-eks-84b4fe6                      |
| Cert Details              | let's encrypt                             |
| Helm version              | v2.16.8-rancher2                          |
| Downstream cluster type   | not applicable                            |
| Downstream K8s version    | not applicable                            |
| Logged in user role       | administrator                             |
| Browser type              | opera gx                                  |
| Browser version           | LVL4 (core: 88.0.4412.75) (x86_64)        |

**ADDITIONAL SETUP**

```shell
eksctl create cluster \
  --name $NAME_VAR \
  --version 1.22 \
  --region $REGION_VAR \
  --nodegroup-name $NG_NAME_VAR \
  --nodes 3 \
  --nodes-min 1 \
  --nodes-max 4 \
  --managed
```

```shell
helm install rancher rancher-latest/rancher \
  --version 2.6.7-rc3 \
  --namespace cattle-system \
  --set hostname=$URL_VAR \
  --set ingress.tls.source=letsEncrypt \
  --set letsEncrypt.email=$EMAIL_VAR \
  --set letsEncrypt.ingress.class=nginx \ 
  --set ingress.ingressClassName=nginx \
  --set extraEnv\[0\].name="CATTLE_PROMETHEUS_METRICS" --set-string extraEnv\[0\].value=true
```

```shell
helm install rancher-csp-adapter rancher-dev/rancher-csp-adapter --namespace cattle-csp-adapter-system --set aws.enabled=true --set-string aws.accountNumber=$MY_ACC_NUM --set aws.roleName=$MY_ROLE_NAME --create-namespace
```

## Reproduction steps

1. Create an eks cluster with eksctl
2. Install Rancher
3. Create an OIDC Provider
4. Create an IAM Role
5. Install the CSP Adapter chart
6. Download the support config
  
## Additional Info

## RESULTS

#### :white_check_mark: Expected
The product value in the config should not have a `v` in the rancher version

#### :x: Actual
The product value has a `v` in the rancher version

<hr>
  
## Validation Environment

| Component                 | Version / Type                            |
| ------------------------- | ----------------------------------------- |
| Rancher version           | 2.6.7-rc3                                 |
| CSP Adapter version       | 🚨 rancher-csp-adapter:1.0.0+up1.0.0-rc4 🚨 |
| Installation option       | eks via eksctl                            |
| If Helm Chart k8s cluster | v1.22.10-eks-84b4fe6                      |
| Cert Details              | let's encrypt                             |
| Helm version              | v2.16.8-rancher2                          |
| Downstream cluster type   | not applicable                            |
| Downstream K8s version    | not applicable                            |
| Logged in user role       | administrator                             |
| Browser type              | opera gx                                  |
| Browser version           | LVL4 (core: 88.0.4412.75) (x86_64)        |

**ADDITIONAL SETUP**

```shell
eksctl create cluster \
  --name $NAME_VAR \
  --version 1.22 \
  --region $REGION_VAR \
  --nodegroup-name $NG_NAME_VAR \
  --nodes 3 \
  --nodes-min 1 \
  --nodes-max 4 \
  --managed
```

```shell
helm install rancher rancher-latest/rancher \
  --version 2.6.7-rc3 \
  --namespace cattle-system \
  --set hostname=$URL_VAR \
  --set ingress.tls.source=letsEncrypt \
  --set letsEncrypt.email=$EMAIL_VAR \
  --set letsEncrypt.ingress.class=nginx \ 
  --set ingress.ingressClassName=nginx \
  --set extraEnv\[0\].name="CATTLE_PROMETHEUS_METRICS" --set-string extraEnv\[0\].value=true
```

```shell
helm install rancher-csp-adapter rancher-dev/rancher-csp-adapter --namespace cattle-csp-adapter-system --set aws.enabled=true --set-string aws.accountNumber=$MY_ACC_NUM --set aws.roleName=$MY_ROLE_NAME --create-namespace
```

## Validation steps

1. Create an eks cluster with eksctl
2. Install Rancher
3. Create an OIDC Provider
4. Create an IAM Role
5. Install the CSP Adapter chart
6. Download the support config
  
## Additional Info

## RESULTS

#### :white_check_mark: Expected
For the `product` value not to have a `v` in the Rancher version

#### :white_check_mark:Actual
The `product` value did not have a `v` in the Rancher version
