### ISSUE TITLE
[BUG] Docker installation script fails on ubuntu 22.04 nodes

### ISSUE THREAD

**Issue by rishabhmsra** [rancher/rancher#38362]
**Describe the bug**

- Docker installation script on `ubuntu 22.04` is failing with below error:
```
$ curl https://releases.rancher.com/install-docker/20.10.sh | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 21946  100 21946    0     0  85727      0 --:--:-- --:--:-- --:--:-- 86062
# Executing docker install script, commit: 93d2499759296ac1f9c510605fef85052a2c32be
+ sudo -E sh -c apt-get update -qq >/dev/null
+ sudo -E sh -c DEBIAN_FRONTEND=noninteractive apt-get install -y -qq apt-transport-https ca-certificates curl >/dev/null
+ sudo -E sh -c curl -fsSL "https://download.docker.com/linux/ubuntu/gpg" | gpg --dearmor --yes -o /usr/share/keyrings/docker-archive-keyring.gpg
+ sudo -E sh -c echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu jammy stable" > /etc/apt/sources.list.d/docker.list
+ sudo -E sh -c apt-get update -qq >/dev/null
INFO: Searching repository for VERSION '20.10.12'
INFO: apt-cache madison 'docker-ce' | grep '20.10.12.*-0~ubuntu' | head -1 | awk '{$1=$1};1' | cut -d' ' -f 3

ERROR: '20.10.12' not found amongst apt-cache madison results
```
OS details:
```
PRETTY_NAME="Ubuntu 22.04 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
```
**Note : The scripts successfully installs docker on ubuntu 20.04 nodes.**

**To Reproduce**

- On AWS create nodes using ubuntu 22.04 AMI. In this case ami-02f3416038bdb17fb is used.
- SSH into the node and run the docker installation script : `https://releases.rancher.com/install-docker/20.10.sh`

**Result**
- Docker installation script errors out.

**Expected Result**

- Docker should get installed successfully.

**Screenshots**

**Additional context**

https://github.com/rancher/qa-tasks/issues/448#issuecomment-1191493015

**Comment by jakefhyde** [comment]
Looks like 20.10.12 isn't available in Ubuntu 22.04, only 20.10.13 - 20.10.17. I'll investigate updating the version and see if there is a way that we can integrate functionality for only installing a specific docker version for a particular OS.

**Comment by snasovich** [comment]
The issue to add support for Docker 20.10.13 - 20.10.17: https://github.com/rancher/rancher/issues/38390

**Comment by hammer-of-thor** [comment]
Do you have a workaround for this for the time being?

**Comment by RaceFPV** [comment]
Workaround: Download the install script locally, then edit the line with 'VERSION' to ="20.10.17"

**Comment by hammer-of-thor** [comment]
Thanks, will do

**Comment by irishgordo** [comment]
Was seeing a similar issue with: https://github.com/rancher/rancher/issues/38541

**Comment by vivek-infracloud** [comment]
Tested this issue again on Ubuntu 22.04 AMI - ami-02f3416038bdb17fb

Validation steps:

- Created an instance on AWS with Ubuntu 22.04.
- SSH into node and installed a docker with installation script - https://releases.rancher.com/install-docker-dev/$VERSION.sh
- For this validation Docker version 20.10.17 was used.
- Docker installation was successful.

Hence, the issue is no longer active on Ubuntu 22.04 for docker version 22.04

**Comment by jakefhyde** [comment]
### Root cause

Docker install script was capped at 20.10.12

### What was fixed, or what changes have occurred

Added docker versions 20.10.13-17
 
### Areas or cases that should be tested

Rancher provisioned and imported clusters with docker versions 20.10.13-17 (see https://github.com/rancher/rancher/issues/38362#issuecomment-1220496141 for instructions to install docker on imported node)
 
### What areas could experience regressions?

Upgraded docker versions could cause breakages in unknown areas for RKE1 clusters.
 
### Are the repro steps accurate/minimal?
:heavy_check_mark:

**Comment by thaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6-head 4f2da17
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: RKE1

----------

### Testing: ###
https://releases.rancher.com/install-docker-dev/20.10.17.sh is not yet released so can only be accessed through ../install-docker-dev/.. path and not ../install-docker/..

Tested this issue with the following steps:
1. Create RKE1 cluster using ubuntu 22.04 AMI. AMI used: ami-07a49ad213adc30c6
2. While creating template, update `Docker Install URL` under `Engine Options` to point to `https://releases.rancher.com/install-docker-dev/20.10.17.sh`
![image.png](https://zube.io/files/rancher/77d5a0e6eaf6009e9095ab45e6e44399-image.png)
3. Create cluster

Imported Nodes:
1. Created an instance on AWS with Ubuntu 22.04. AMI used: ami-07a49ad213adc30c6
2. SSH into node and installed a docker with installation script - https://releases.rancher.com/install-docker-dev/20.10.17.sh
3. For this validation Docker version 20.10.17 was used.
4. Docker installation was successful.

**Result**
Docker installation was successful in both scenarios.
