### ISSUE TITLE
[BUG] Bump RKE1 default version to 1.24

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#38369]
Bump the default version of RKE1 to 1.24.x on downstream clusters

**Comment by jiaqiluo** [comment]
can be tested on the latest v2.6-head or any 2.6.7-rc
you might need to refresh KDM to get the updated metadata.

**Comment by anupama2501** [comment]
Verified on v2.6.7-rc3

RKE1 downstream clusters have 1.24.x marked as default - created an infrastructure provider 3 nodes all roles  - PASS 
RKE1 custom cluster - 1 node all roles  - PASS 
<img width="150" alt="124" src="https://user-images.githubusercontent.com/38144301/180580487-f9eb6d7b-15a7-4761-8929-06f2d857a875.png">
