### ISSUE TITLE
[BUG][AKS] - Unable to reach Rancher Dashboard after deploying Rancher on AKS 1.24.0 cluster

### ISSUE THREAD

**Issue by thaneunsoo** [rancher/rancher#38380]
**Rancher Server Setup**
- Rancher version: 2.6.7-rc3
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: 1.24.0
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

Hosted AKS

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Admin

**Describe the bug**

User is unabe to deploy Rancher on AKS 1.24.0 cluster

**To Reproduce**

1. Provision 1.24.0 cluster on AKS using azure portal
2. Install Rancher on cluster
3. Try to reach Rancher UI

**Result**
Rancher is not reachable on the browser. Also tried upgrading from 1.23.8 to 1.24.0. Rancher was working on 1.23.8, but after upgrading to 1.24.0 from azure portal, Rancher was no longer reachable.

**Expected Result**

Rancher should be reachable

**Comment by thaneunsoo** [comment]
There was a misunderstanding and this behavior is expected until 1.24.0 is a stable release on AKS

**Comment by thaneunsoo** [comment]
Reopening and will validate this issue once AKS 1.24.0 becomes supported.

**Comment by snasovich** [comment]
Since 1.24 is still in preview and we don't have enough time to validate it once it's out until 2.6.7 release, running Rancher on top of 1.24 AKS will not be on the official support matrix for Rancher 2.6.7 (it will be 1.23.8).
Moving this issue to 2.7.0.

**Comment by annablender** [comment]
Kubernetes 1.24 AKS is still in preview (as of 8/17 when tested)

**Comment by Sahota1225** [comment]
@thaneunsoo - can you please retest this on the latest 1.24.3

**Comment by thaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6-head a3b5237
Rancher cluster type: HA
Docker version: 20.10

----------

### Testing: ###
1. Provision 1.24.3 cluster on AKS using Azure portal
2. Install Rancher on cluster
3. Try to reach Rancher UI

**Result** - Pass
Rancher is now reachable on the browser.
![image.png](https://zube.io/files/rancher/d7b44fbe0ffec0bbc3eaccedb671a366-image.png)
