### ISSUE TITLE
Error: chart requires kubeVersion: < 1.24.0-0 which is incompatible with Kubernetes v1.24.3+k3s1

### ISSUE THREAD

**Issue by jicvi** [rancher/rancher#38392]
**Rancher Server Setup**
- Rancher version: 2.6.5
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):  k3s
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: k3s version v1.24.3+k3s1
- Cluster Type (Local/Downstream): Local k3s version v1.24.3+k3s1
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:

**Describe the bug**

**To Reproduce**

**Result**
Error: chart requires kubeVersion: < 1.24.0-0 which is incompatible with Kubernetes v1.24.3+k3s1

**Expected Result**

**Screenshots**

![2022-07-24_22-13](https://user-images.githubusercontent.com/14210650/180680337-586f3655-43a3-4f54-9191-b148cd539031.png)

**Additional context**

**Comment by silverfisk** [comment]
I see the same issue. Not sure if it's a k3s or helm issue tough. Is this supposed to follow semver.org / Semantic Versioning 2.0.0? It states `Build metadata MAY be denoted by appending a plus sign and a series of dot separated identifiers immediately following the patch or pre-release version`

**Comment by silverfisk** [comment]
A workaround for now is to download the chart locally, then change to something like `kubeVersion: 1.24.4`
in charts/rancher/Chart.yaml
Then install it with
helm install rancher ./charts/rancher --namespace cattle-system --set hostname=k3s.hostname --set replicas=3  --set bootstrapPassword=admin

**Comment by jicvi** [comment]
@silverfisk 
thank you

**Comment by wbarnard81** [comment]
This is still an issue.
```
user@host:~$ helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=10.0.0.15.sslip.io \
  --set replicas=1 \
  --set bootstrapPassword=xxxxxxxx
Error: INSTALLATION FAILED: chart requires kubeVersion: < 1.25.0-0 which is incompatible with Kubernetes v1.25.4+k3s1
```

**Comment by icsy7867** [comment]
Yep.  Same here.  Just tried flatcar + k3s

**Comment by kanersps** [comment]
Also having the same issue, automated install of k3s and Rancher deployment is now failing due to this.

**Comment by icsy7867** [comment]
> Also having the same issue, automated install of k3s and Rancher deployment is now failing due to this.

I posted above about changing the helm chart to get it to install.  This did, in fact, seem to install fine, but rancher still had issues loading.  I ended up having to get a previous k3s release:
https://github.com/k3s-io/k3s/releases

This one worked like a charm:
https://github.com/k3s-io/k3s/releases/tag/v1.24.8%2Bk3s1

I think there are some changes to the API in 1.25.  But I am curious if anyone else has rancher working fully with the latest k3s.

**Comment by toddspencer95** [comment]
> > Also having the same issue, automated install of k3s and Rancher deployment is now failing due to this.
> 
> I posted above about changing the helm chart to get it to install. This did, in fact, seem to install fine, but rancher still had issues loading. I ended up having to get a previous k3s release: https://github.com/k3s-io/k3s/releases
> 
> This one worked like a charm: https://github.com/k3s-io/k3s/releases/tag/v1.24.8%2Bk3s1
> 
> I think there are some changes to the API in 1.25. But I am curious if anyone else has rancher working fully with the latest k3s.

Hi @icsy7867 

I am still having issues with rolling back my k3s version. 

I used this command:

curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.24.8+k3s1-rc1 sh -

and it said it downloaded the hash? but when I try to redownload rancher, I still get a chart/k3s version incompatibility error.

I am very very new to this, so it's been a steep learning curve for me, so anything helps.

Thanks!

**Comment by icsy7867** [comment]
> > > Also having the same issue, automated install of k3s and Rancher deployment is now failing due to this.
> > 
> > 
> > I posted above about changing the helm chart to get it to install. This did, in fact, seem to install fine, but rancher still had issues loading. I ended up having to get a previous k3s release: https://github.com/k3s-io/k3s/releases
> > This one worked like a charm: https://github.com/k3s-io/k3s/releases/tag/v1.24.8%2Bk3s1
> > I think there are some changes to the API in 1.25. But I am curious if anyone else has rancher working fully with the latest k3s.
> 
> Hi @icsy7867
> 
> I am still having issues with rolling back my k3s version.
> 
> I used this command:
> 
> curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.24.8+k3s1-rc1 sh -
> 
> and it said it downloaded the hash? but when I try to redownload rancher, I still get a chart/k3s version incompatibility error.
> 
> I am very very new to this, so it's been a steep learning curve for me, so anything helps.
> 
> Thanks!

I wouldnt run a release candidate (rc-1).  Try this version:
https://github.com/k3s-io/k3s/releases/tag/v1.24.8%2Bk3s1

You might also want to try to completely remove k3s first.
/opt/bin/k3s-uninstall.sh

If you are still having issues, you can download the binary manually and place it.

**Comment by toddspencer95** [comment]
@icsy7867 that did the trick!!!! thanks so much!

**Comment by johnwyles** [comment]
Anyone here like me because this was the top listing on the search results here are the steps I took from the above in order to get it to work:

```shell
helm pull rancher-latest/rancher
tar zxvf rancher-X.X.X.tgz
vi rancher/Chart.yaml # modify version to +1 more than the error and save
tar cvf rancher-X.X.X-1.tar rancher/
gzip rancher-X.X.X-1.tar
 helm install rancher ./rancher-X.X.X-1.tar.gz   --namespace cattle-system   --set hostname=FOO.BAR.EXAMPLE.COM   --set replicas=1   --set ingress.tls.source=letsEncrypt   --set letsEncrypt.email=YOUREMAIL@FOO.BAR.EXAMPLE.COM --set bootstrapPassword=YOUR_PASSWORD_HERE
kubectl -n cattle-system rollout status deploy/rancher
```
