### ISSUE TITLE
Not able to See the logs with Limited Permission to user

### ISSUE THREAD

**Issue by amitdrana** [rancher/rancher#38395]
Hi Team,
   Currently i am using RANCHER-2.6 version.
     I have a situation where i need to give a user to see the logs but not execute the shell but i am unable to do so.
     Its look like logs shell is hangs. Attaching  the permission i have added: 
     
     
 
     
![1](https://user-images.githubusercontent.com/46323748/180769048-4a9f229f-572f-4999-9dc0-f94050518f8c.png)

also When i checked the logs at first user can check the logs but after sometime shell hangs.

![2](https://user-images.githubusercontent.com/46323748/180769561-1678544d-16b5-41eb-99b9-9a2a2d026ff4.png)

Any idea..
  Thanks

**Comment by mstrent** [comment]
@amitdrana we are having a similar issue possibly. We are using AD/LDAP auth with groups. If I delete the individual user from Users & Authentication, and let them log in again and re-create, it clears up. But sometimes it comes back.

**Comment by mstrent** [comment]
Our symptoms are the same at least. Some users try to view logs and get the empty gray box at the bottom, with no bottom status bar.

**Comment by mstrent** [comment]
Ok, actually I think this bug is what we're hitting: https://github.com/rancher/rancher/issues/38231
