### ISSUE TITLE
Add Docker 20.10.17

### ISSUE THREAD

**Issue by jakefhyde** [rancher/rancher#38390]
https://github.com/moby/moby/releases/tag/v20.10.17

This also includes adding support for previous versions that are not yet there in https://github.com/rancher/install-docker as well as changing `20.10.sh` install script to point to the latest supported version. We do want to ensure this latest version is available on the OSes listed on Rancher's Support Matrix (e.g. here is one for 2.6.5 release which is the latest available at this time: https://www.suse.com/suse-rancher/support-matrix/all-supported-versions/rancher-v2-6-5/)

**Comment by vivek-infracloud** [comment]
1. Successfully completed testing docker install scripts 20.10.13-20.10.17 on following OSes.

> - Ubuntu 20.04
> - CentOS 7.9
> - RockyLinux 8.6

2. Following OSes comes with docker pre-installed.

> - SLES - 15 SP4
> - OpenSUSE Leap 15.4 


3. On RHEL 8.6 docker version greater than 20.10.7 is not supported.

4. On Oracle Linux 8.6 the cluster creation is blocked by [this issue](https://github.com/rancher/rancher/issues/38214). 


Hence, closing this issue.
