### ISSUE TITLE
No valid AKS k8s versions on rancher 2.5 

### ISSUE THREAD

**Issue by Josh-Diamond** [rancher/rancher#38406]
**Rancher Server Setup**
- Rancher version: `v2.5.14`
- Installation option (Docker install/Helm Chart): `Seen on both`
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details: `byo-valid w/ helm` and `self-signed w/ docker`

**Information about the Cluster**
- Kubernetes version: ANY
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):
Downstream Hosted AKS cluster

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
admin or standard user

**Describe the bug**
No valid k8s versions to populate k8s version dropdown when provisioning downstream Hosted AKS cluster

**To Reproduce**
1. Fresh install of rancher `v2.5.14`
2. Provision a downstream AKS cluster
3. Reproduced 

**Result**
No k8s versions are populated in version dropdown

**Expected Result**
k8s versions will populate in version dropdown

**Screenshots**
`Step 3`
<img width="1452" alt="Screen Shot 2022-07-25 at 3 12 50 PM" src="https://user-images.githubusercontent.com/46494969/180882823-05b7cd23-83ff-4690-a043-08833259d29b.png">

**Additional context**
K8s versions are seen in `Network` tab of chrome dev tools;
Rancher `v2.5` doesn't support k8s 1.21+; All versions listed in `Network` tab don't qualify, so they are not populated in dropdown

Screenshot:
<img width="1624" alt="Screen Shot 2022-07-25 at 2 50 04 PM" src="https://user-images.githubusercontent.com/46494969/180883000-bbdf7558-56a7-4a79-af03-b55ceb7bcaaa.png">

**Comment by jiaqiluo** [comment]
AKS deprecated the support for k8s versions < 1.21 and rancher v2.5.x supports k8s version <= 1.20. 
As a result, there is no available version to show if we want to create an AKS cluster in rancher UI. 

The following is the screenshot of the version list when creating AKS cluster on the Azure console. 
<img width="776" alt="Screen Shot 2022-07-25 at 3 32 08 PM" src="https://user-images.githubusercontent.com/6218999/180888852-10d7b462-1c10-41de-94a8-0b0e90414be7.png">

**Comment by snasovich** [comment]
Per the comment above this is expected - Rancher 2.5.x does not support k8s greater than 1.20.x and since AKS no longer supports 1.20.x and earlier, it's not possible to provision new AKS clusters.
However, I believe it's a good idea to "release note" this as a known issue to avoid confusion.

**Comment by sowmyav27** [comment]
From API, the provisioning of 1.20 AKS works fine in `2.5.16-rc1`

**Comment by Josh-Diamond** [comment]
Further testing reveals that AKS no longer supports k8s `1.20`;
Provisioning AKS `1.20` is no longer possible; Deprecated

<img width="1278" alt="Screen Shot 2022-07-26 at 2 36 03 PM" src="https://user-images.githubusercontent.com/46494969/181117911-7d46d25f-9c69-4abf-b842-ea5c0ee187e5.png">
