### ISSUE TITLE
[BUG] RKE2 EC2 Node Driver provisioning fails in EC2 environments with IMDSv2 enforced on instance creation

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#38405]
**Rancher Server Setup**
- Rancher version: v2.6.7-rc3
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): rke1, 1.3.13-rc5
- Proxy/Cert Details: valid, letsencrypt certs

**Information about the Cluster**
- Kubernetes version: any (tested with 1.24.x
- Cluster Type (Local/Downstream): downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): AWS EC2 rke2 node driver

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): standard user, cluster owner

**Describe the bug**

**To Reproduce**
* ensure you have the permissions for IMDSv2 as specified from this ticket: https://github.com/rancher/rancher/issues/37943
* create an rke2 cluster with the following options enabled (all required for spot instance creation):
  * (advanced options) enable Use `tokens for metadata`
  * (advanced options) enable `allow access to ec2 metadata`
  * (advanced options) enable `spot instances`
    * increase spot instance cost to 1
  * this can be with a single node cluster, all other options left to default (known working) values

**Result**
the machine is created and deleted repeatedly within 10 seconds

**Expected Result**
user should be able to create spot instances with rke2

**Additional context**
some important error logs:
```
error syncing 'fleet-default/ctw-rke2-spot-all-a-b47abd40-jg6cf': handler machine-provision-remove: Operation cannot be fulfilled on amazonec2machines.rke-machine.cattle.io "ctw-rke2-spot-all-a-b47abd40-jg6cf": StorageError: invalid object, Code: 4, Key: /registry/rke-machine.cattle.io/amazonec2machines/fleet-default/ctw-rke2-spot-all-a-b47abd40-jg6cf, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: 964cb58f-4fdc-4128-b70b-83331df9e331, UID in object meta: , requeuing
```

and 

```
error syncing 'fleet-default/ctw-rke2-spot-all-bootstrap-template-ksq2x': handler rke-machine: failed to delete fleet-default/ctw-rke2-spot-all-bootstrap-template-ksq2x-machine-bootstrap /v1, Kind=Secret for rke-machine fleet-default/ctw-rke2-spot-all-bootstrap-template-ksq2x: secrets "ctw-rke2-spot-all-bootstrap-template-ksq2x-machine-bootstrap" not found, failed to delete fleet-default/ctw-rke2-spot-all-bootstrap-template-ksq2x-machine-plan /v1, Kind=Secret for rke-machine fleet-default/ctw-rke2-spot-all-bootstrap-template-ksq2x: secrets "ctw-rke2-spot-all-bootstrap-template-ksq2x-machine-plan" not found, requeuing
`secrets "ctw-rke2-spot-all-bootstrap-template-ksq2x-machine-plan" not found, requeuing
```

**Comment by snasovich** [comment]
Bumping this one out to 2.7.0 as SURE-4767 is applicable to RKE1 only and that behavior was fixed for 2.6.7 per https://github.com/rancher/rancher/issues/37943.

**Comment by HarrisonWAffel** [comment]
Now that the UI ticket has been closed this issue can be moved to to-test. I've done a quick smoke test (my account still has IMDSv2 enabled, for this ticket specifically) and things seem to be working as expected.


Test Steps:

0. Ensure that EIO has enabled the IMDSv2 policy on your IAM user.
1. Begin to create a new EC2 cluster
2. Add in required information, then click the `Show Advanced` button directly below the `VPC/Subnet` field
3. Scroll down, and select both `Allow access to EC2 metadata` and `Use tokens for metadata`
4. Create the cluster
5. Observe the EC2 instance being successfully created by machine. Any errors encountered after the creation of the VM are not related to this ticket.

**Comment by slickwarren** [comment]
tested on rancher v2.7-head (c567ef3):
* with an IMDSv2 policy user, create an ec2 rke2 cluster with `Allow access to EC2 metadata` and `Use tokens for metadata` enabled -- pass (cluster provisions, node is created in backend)
