### ISSUE TITLE
[BUG] Launching neuvector chart post upgrade results in unable to create impersonator account

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#38408]
Information about the Cluster
**Rancher Server Setup**
- Rancher version: `v2.6.5` upgraded to `v2.6.7-rc3`
- Installation option (Docker install/Helm Chart): `Helm Chart`
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): `RKE1`, `v1.23.6`, `1.3.11`
- Proxy/Cert Details: `byo-valid`

**Information about the Cluster**
- Kubernetes version: `v1.23.7 `
- Cluster Type (Local/Downstream): `Custom  3 worker, 1 etcd, 1 cp RKE1`

**Describe the bug**
Launching neuvector chart results in an error post rancher upgrade but the error is not seen relaunching the app. 

**To Reproduce**
1. Install rancher on v2.6.5 using byo-valid certs
2. Install neuvector app version `100.0.0+up2.2.0`
3. Launch neuvector app, no errors are seen
4. Upgrade rancher server to v2.6.7-rc3
5. Launch neuvector app 

**Result**
Error `unable to create impersonator account: error getting service account token: error getting token: invalid secret object` is seen
If we re launch the app, the error is not seen anymore and the app works without any error.

**Expected Result**
No errors seen on launching the app post upgrade.

**Additional context**

**Comment by samjustus** [comment]
@anupama2501 @selvamt94 pushing this issue out since there's been no progress

**Comment by cbron** [comment]
I think this may have been related to earlier impersonation issues, which should have been resolved now. If this is seen again we can re-open.
