### ISSUE TITLE
vSphere CSI chart not available on k8s v1.24 cluster due to kube-version annotation

### ISSUE THREAD

**Issue by rishabhmsra** [rancher/rancher#38414]
**Rancher Server Setup**
- Rancher version: v2.6.7-rc3
- Installation option (Docker install/Helm Chart): Docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.24.2+k3s1
- Cluster Type (Local/Downstream): Local
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Admin
  - If custom, define the set of permissions:

**Describe the bug**

- On k8s v1.24 clusters, vSphere CSI charts is not available because of the kube-version annotation in the charts.yaml.
- This annotation `catalog.cattle.io/kube-version: '>= 1.20.0-0 < 1.24.0-0'` needs to be updated for installation of CSI charts.

**To Reproduce**

- Deploy rancher v2.6.7-rc3 with local cluster as v1.24 or deploy downstream cluster using k8s v1.24
- Goto apps and marketplace.
- Search for vSphere CSI chart.

**Result**
- vSphere CSI chart not available for k8s v1.24 clusters

**Expected Result**

- CSI chart should be available

**Screenshots**

![csi-not-available](https://user-images.githubusercontent.com/36376154/180967804-79b2e0d4-a186-49b3-808b-8bbab780a0d2.png)

**Additional context**

**Comment by phillipsj** [comment]
This isn't a bug. The CSI version in the chart doesn't support K8s 1.24 and that is why their is a restriction. The vSphere CPI and CSI don't typically provide support for the newest K8s version immediately. CSI just go support 13 days ago for 1.24 which is after the code freeze point for 2.6.7. 

* https://github.com/kubernetes-sigs/vsphere-csi-driver/releases/tag/v2.6.0

**Comment by snasovich** [comment]
This should be addressed by the updates done as part of https://github.com/rancher/rancher/issues/38188

**Comment by vivek-infracloud** [comment]
vSphere CSI chart installed successfully on rancher v2.7-head and v2.7.0.

Testing steps:
1. Created a rancher server v2.7.0 (also v2.7-head) on vSphere.
2. Created a downstream node driver cluster (v1.24.8) with 1cp, 1worker and 1 etcd node.
3. Installed a CPI chart v101.1.0+up1.4.1
4. Installed a CSI chart v101.1.0+up2.6.2-rancher1
5. Created a deployment with storage using PVC.
6. Deployment creation was successful.

CPI and CSI charts are working as expected for RKE1 k8s v1.24.8, hence closing the issue.
