### ISSUE TITLE
CIS benchmark scan 1.6 permissive has failures on downstream RHEL 8.6 RKE 1 cluster

### ISSUE THREAD

**Issue by AndrewHoffmanQA** [rancher/rancher#38418]
**Rancher Setup**
- Rancher version: 2.6head c47178e
-HA install

**Information about the Cluster**

ami-053835e36b16f97d0
custom RHEL 8.6 RKE 1 downstream cluster
Kubernetes version: v1.24.2
Cluster Type (Local/Downstream): Downstream node driver 4 worker, 1 etcd, 2 cp RKE1

**Describe the bug**
CIS benchmark helm chart 2.0.5-rc5 when scan 'rke-profile-permissive-1.6' is executed on the downstream cluster results in 3 failures

**failed tests**
ID       -     description
1.2.19  - 	Ensure that the --insecure-port argument is set to 0 (Automated)
4.1.7 - 	Ensure that the certificate authorities file permissions are set to 644 or more restrictive (Automated)
4.1.8	  -    Ensure that the client certificate authorities file ownership is set to root:root (Automated)

**To Reproduce**

1. stand up HA cluster
2.  standup RHEL 8.6 RKE1 custom downstream cluster
3. enter the downstream cluster and navigate to the 'charts' page in the 'apps' section
4. select CIS benchmark
5. install 2.0.5-rc5 to system
6. click on the CIS benchmark tab
7. click create
8. select profile type 'rke-profile-permissive-1.6' 
9. create the scan

**Result**
scan 'rke-profile-permissive-1.6' returns 3 failed tests 

**Expected Result**
no failures upon scanning downstream cluster

**Screenshots**
![image](https://user-images.githubusercontent.com/89030218/180463410-2d29a7f7-7718-4ab0-9fe2-68392efd33bc.png)

**Additional context**
- when installing benchmark 2.0.3 on the server the 'Ensure that the --insecure-port argument is set to 0 (Automated)' still displays
- scan profile RKE 1.5 permissive also has Ensure that the --insecure-port argument is set to 0 (Automated) failure. I believe fixing this bug will fix that one, if you would like a separate bug created please contact @AndrewHoffmanQA 

**Detailed Description**

**Context**

**Comment by gaktive** [comment]
@AndrewHoffmanQA I've transferred this to the backend team since the errors aren't tied to the UI (they just appear there).

**Comment by AndrewHoffmanQA** [comment]
![image](https://user-images.githubusercontent.com/89030218/181340004-647fd7c3-139f-4fca-997a-cfc368578f0c.png)


@gaktive I am closing this because I can no longer reproduce it on v2.6.7-rc5

I will keep an eye out and reopen if becomes consistently reproducible again
