### ISSUE TITLE
[RFE] Steve should support sharing watchers across user sessions (Port from Norman to Steve)

### ISSUE THREAD

**Issue by catherineluse** [rancher/rancher#38412]
This issue is part of a set of Steve performance enhancements for v2.7.x. https://github.com/rancher/dashboard/issues/5243

Norman implemented watch sharing with Broadcasters. https://github.com/rancher/norman/blob/master/pkg/broadcast/broadcaster.go Every time a user opened a connection and subscribed to a resource through the Norman API, Norman created a generic watch for the type. It was like subscribing to a topic, as multiple users could subscribe to the same type. So in Norman, the number of watches corresponded to the number of types, whereas in Steve, there is a new watch per resource type per user session.

The request is for someone to investigate if a similar "Broadcaster" feature could improve performance for Steve, and if possible, forward port it from Norman to Steve.

**Comment by gaktive** [comment]
Internal reference: SURE-5396

**Comment by MKlimuszka** [comment]
Closed as stale, reopen if needed.
