### ISSUE TITLE
[BUG] Cluster agent shows running at 100% cpu

### ISSUE THREAD

**Issue by thaneunsoo** [rancher/rancher#38417]
**Rancher Server Setup**
- Rancher version: 2.6.7-rc3
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: 1.24.2
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

Local and node driver cluster

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Admin

**Describe the bug**

Rancher cluster agent seems to be running at 100% cpu when running the `top` command on a control plane node. Also shows rke to be running at 100% cpu when running the `top` command on an etcd node. ![image](https://user-images.githubusercontent.com/108360907/181044332-61712f42-0641-4731-bfe1-2a40290587d7.png)

On EC2 though, I see that cpu utilization is around 26% I was using a 4vCPU setup, so we are assuming that the 100% meant full use of one core since EC2 showed 26%
<img width="300" alt="image" src="https://user-images.githubusercontent.com/108360907/181044717-23782d67-aa94-4783-b7ba-c5765b1295d2.png">

**To Reproduce**

1. Provision EC2 node driver cluster on 2.6.7-rc3
2. SSH into control plane node and run `top` and see the cpu usage for `agent`
3. SSH into etcd node and run `top` and see the cpu usage for `rke`

**Result**
`rke` and `agent` both show 100% cpu usage

**Expected Result**

These processes should not be showing 100% cpu usage.

**Comment by snasovich** [comment]
This is believed to be caused by the following change in `dynamiclistener` - https://github.com/rancher/dynamiclistener/pull/49/files#diff-52136e2f401dea328d50069c304fe222eb004d0ca7b8b12e6e6c4adbc9df6979L156

`dynamiclistener` got somewhat recently bumped to the version containing this change per https://github.com/rancher/rancher/pull/36932 so the issue started showing up in `2.6-head` leading to 2.6.7 release.

**Comment by thaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6-head 93a4f30
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: RKE2, RKE1

----------

### Testing: ###
Tested this issue with the following steps:
1. Provision EC2 node driver cluster on 2.6.7-rc3
2. SSH into control plane node and run `top` and see the cpu usage for `agent`
3. SSH into etcd node and run `top` and see the cpu usage for `rke`

**Result**
The `agent` and `rke` processes are no longer showing as taking up 100% of cpu

RKE2
agent
![image.png](https://zube.io/files/rancher/6aa2fbc1c7dbbfc2a3395270cd5bb1f3-image.png)
rke2
![image.png](https://zube.io/files/rancher/744e562bdb8e07dd7aa3991f21ec167a-image.png)

RKE1
agent
![image.png](https://zube.io/files/rancher/d26d41bf86e18200aefe6a8a1df432e8-image.png)
rke2 does not apply here

**Comment by rmweir** [comment]
The PR(s) for this was merged prior to 2.7 branching.
