### ISSUE TITLE
[RFE] Steve should provide pod data along with list of workloads

### ISSUE THREAD

**Issue by catherineluse** [rancher/rancher#38428]
This issue is part of a set of Steve performance enhancements for v2.7.x. https://github.com/rancher/dashboard/issues/5243

When the UI displays a list of workloads in the UI, it also must loop over pods to get these properties for each workload:

- The total count of pods that match the workload selector
- The health status of all pods in the workload - pending, active etc.
- The total pod restart count of all pods in the workload

It could improve performance in the UI if Steve could provide the above three pieces of information so that the UI would not have to loop over the pods so many times.

**Comment by gaktive** [comment]
Internal reference: SURE-5397
