### ISSUE TITLE
[BUG] AWS has errors when using the node driver, but those errors aren't showing in rancher

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#38422]
**Rancher Server Setup**
- Rancher version: v2.6.7-rc3
- Installation option (Docker install/Helm Chart): helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): rke1, 1.3.13-rc5
- Proxy/Cert Details: any (tested with letsencrypt valid certs)

**Information about the Cluster**
- Kubernetes version: any (tested with 1.24.2-rancher1-1)
- Cluster Type (Local/Downstream): downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): rke1, aws node driver

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): standard user, cluster owner

**Describe the bug**
when provisioning a node driver cluster using aws, some important errors are not showing through rancher.

**To Reproduce**
* provision an aws node driver cluster 
  * specify a smaller than default value for the disk size (i.e. if an AMI has size 16gb, specify 8gb)
* wait for the cluster to provision

**Result**
though we know parameters are incorrect, the cluster does not give useful information as to why provisioning is failing through rancher. 

**Expected Result**
rancher should surface valuable errors for users

**Additional information**
found while testing IMDSv2 ticket with rke1
new error seen from this example:
```
Error creating machine: Error in driver during machine creation: MissingParameter: The request must contain the parameter InstanceId
```
typical error (as of 2.6.6):
```
error creating machine: Error in driver during machine creation: Error launching instance: InvalidBlockDeviceMapping: Volume of size 4GB is smaller than snapshot 'snap-0fc035b4fca3582b6', expect size >= 35GB
```

**Comment by sowmyav27** [comment]
**On 2.6head commit id: `b1f04af`**

- Deployed an RKE1 cluster using an AMI and incorrect size
- Error on the node pool in Rancher UI - `Error creating machine: Error in driver during machine creation: MissingParameter: The request must contain the parameter InstanceId`
- Error in Rancher logs:
```
2022/07/28 04:24:32 [INFO] [node-controller-rancher-machine] (sowmya-test-1) error encountered during instance creation: Error launching instance: InvalidBlockDeviceMapping: Volume of size 4GB is smaller than  snapshot 'snap-0fc035b4fca3582b6', expect size >= 35GB
2022/07/28 04:24:32 [INFO] [node-controller-rancher-machine] (sowmya-test-1) 	status code: 400, request id: 5c7d8cfc-2717-41e4-9fdf-815d78c94c1e
2022/07/28 04:24:32 [INFO] [node-controller-rancher-machine] (sowmya-test-1) Missing instance ID, this is likely due to a failure during machine creation
2022/07/28 04:24:32 [INFO] [node-controller-rancher-machine] (sowmya-test-1) deleting key pair: sowmya-test-1-vUwpA
2022/07/28 04:24:40 [INFO] [node-controller-rancher-machine] The default lines below are for a sh/bash shell, you can specify the shell you're using, with the --shell flag.
2022/07/28 04:24:40 [INFO] [node-controller-rancher-machine] 
2022/07/28 04:24:40 [INFO] Generating and uploading node config sowmya-test-1
2022/07/28 04:24:40 [ERROR] error syncing 'c-nrz8c/m-wt56m': handler node-controller: Error creating machine: Error in driver during machine creation: MissingParameter: The request must contain the parameter InstanceId, requeuing
```
---

Whereas on 2.6.6, for the same usecase, error seen on UI: `Error creating machine: Error in driver during machine creation: Error launching instance: InvalidBlockDeviceMapping: Volume of size 4GB is smaller than snapshot 'snap-0fc035b4fca3582b6', expect size >= 35GB`


This seems like a regression from 2.6.6

**Comment by slickwarren** [comment]
Yes lets reopen, @HarrisonWAffel would it be possible to get the same detailed errors back into rancher?

**Comment by HarrisonWAffel** [comment]
@slickwarren Yes it should be, I can work on this next

**Comment by slickwarren** [comment]
tested on rancher v2.6.7-rc6:
* provisioning an instance with less disk space than snapshot allows now shows this error through rancher:
<img width="1536" alt="Screen Shot 2022-08-02 at 12 21 20 PM" src="https://user-images.githubusercontent.com/16691014/182457019-8300219e-06fb-4a1d-8011-084748f61408.png">
I believe this is enough testing for this particular issue
