### ISSUE TITLE
Update CIS benchmark scans to work on specific kubernetes versions that it supports

### ISSUE THREAD

**Issue by mitulshah-suse** [rancher/rancher#38439]
**Describe the bug**
Older CIS benchmark scans are available to run on newer kubernetes versions even though they are not supported and fail as expected. The benchmark scan profiles should be updated to specify the minimum and maximum kubernetes version they are supported on.

| Scan profile version | Kubernetes version |
|---------------------------|----------------------------|
| 1.6 | 1.16 - 1.18 |
| 1.20 | 1.19 - 1.21 |
| 1.23 | 1.22 - 1.24 |

**Expected Result**
Scan on an unsupported version will fail with kubernetes version mismatch error.

**Comment by vivek-infracloud** [comment]
Validated if the scan profile works on specific kubernetes versions.

Validations were done for following types of clusters.

1. RKE1 k8s v1.18 to v1.24.
2. RKE2 k8s v1.22 to v1.24
3. k3s v1.22 to v1.24


As per the description in the issue. Tested the following scenarios and all the scenarios passed.

On k8s v1.18
CIS scan profile 1.6 passed. Rest show errors of unsupported k8s version.
![Screenshot from 2022-09-20 13-16-13](https://user-images.githubusercontent.com/83208989/191265523-d56b26cc-f8d5-4485-a12e-b1d7a2e0f034.png)

On k8s v1.19-v1.21
CIS scan profile 1.20 passed. Rest show error of unsupported k8s version.
![Screenshot from 2022-09-20 11-57-13](https://user-images.githubusercontent.com/83208989/191265692-aef46b9f-3b81-4676-a74b-f34916ec5b3f.png)

On RKE1, RKE2 k8s and k3s v1.22-v1.24
CIS scan profile 1.23 passed. Rest show error of unsupported k8s version.
![Screenshot from 2022-09-20 11-56-32](https://user-images.githubusercontent.com/83208989/191265452-a4029915-290d-4ab8-baa6-f37ee06560b0.png)

**Comment by vivek-infracloud** [comment]
Based on above validations, all the checks passed. Hence, closing the issue.
