### ISSUE TITLE
Airgap - RKE2 custom cluster upgrade from 1.23 to 1.24 kubernetes stuck in Updating state

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#38438]
**Rancher Server Setup**
- Rancher version: `v2.6.7-rc5` Airgapped
- Installation option: Helm RKE1
- Proxy/Cert Details: valid certs

**Information about the Cluster**
- Kubernetes version: `v1.23.8+rke2r1` (upgrade to `v1.24.2+rke2r1`)
- Cluster Type : Downstream
   - Custom RKE2
**User Information**
- What is the role of the user logged in? `Admin`

**Describe the bug**

While upgrading a custom RKE2 cluster from `v1.23.8+rke2r1` → `v1.24.2+rke2r1` the kubernetes version gets upgraded but the cluster is stuck in `Updating` state indefinitely.
The cluster is an airgapped RKE2 Custom cluster  

**To Reproduce**
- Setup Rancher Airgap `v2.6.7-rc5`
- Provision a Custom RKE2 cluster with 1 node all roles. Use `v1.23.8+rke2r1`
- Copy paste the provided command in the node that's Airgapped
- Wait for the cluster to come up active
- Edit Config the cluster from Cluster Management
- Select kubernetes version `v1.24.2+rke2r1`
- Apply the change
- Wait for the cluster it gets stuck in Updating state waiting for probes to succeed.

**Result**
Cluster stuck in Updating state.
Last messages seen on two different clusters:
`Configuring bootstrap node(s) custom-b47fae5785c4: waiting for probes: kubelet`
`Configuring bootstrap node(s) custom-48adf9b6bd93: waiting for probes: etcd, kube-apiserver, kube-controller-manager, kube-scheduler`

**Expected Result**
Cluster comes up active upgrading to the latest 1.24 kubernetes.

**Screenshots**

<img width="826" alt="Screen Shot 2022-07-26 at 6 46 30 PM" src="https://user-images.githubusercontent.com/27659/181142751-1b29a617-6498-40f4-9d6b-108c75773dc6.png">

**Additional context**

Querying the processes in the node i see this process getting executed:

`curl --connect-timeout 60 --max-time 300 --write-out %{http_code}\n -sS -fL https://github.com/rancher/system-agent/releases/download/v0.0.1-alpha18/system-agent-uninstall.sh -o /usr/local/bin/rancher-system-agent-uninstall.sh`

This is an airgapped node so this command will fail.

**Comment by jakefhyde** [comment]
This is blocked until we can release `system-agent` and update the version in rancher.

**Comment by izaac** [comment]
Rancher version: `v2.6.7-rc6`

The cluster goes into Active state as expected after upgrading the kubernetes version on these paths:

RKE2
`v1.23.8+rke2r1` → `v1.24.2+rke2r1`

k3s
`v1.23.8+k3s2` → `v1.24.2+k3s2`

Closing
