### ISSUE TITLE
[BUG] `user-node-remove` finalizer not being properly cleaned up.

### ISSUE THREAD

**Issue by jakefhyde** [rancher/rancher#38442]
**Rancher Server Setup**
- Rancher version: v2.6.6

**Describe the bug**

If a user upgrades from a version of rancher where the `user-node-remove` controller still existed, there is a period where the node can be deleted before the finalizer is able to be removed from the node. Since an annotation is used to track whether or not the finalizer needs to be removed, it is thus never removed.

https://github.com/rancher/rancher/blob/a86ad02746c0846fedb8fa7436b1d7e6017a73d6/pkg/controllers/management/node/controller.go#L524-L535

**To Reproduce**

This is difficult to test, since this is effectively a race condition, although it can be done by manually adding the finalizer `clusterscoped.controller.cattle.io/user-node-remove_xxxxx` (the five x values do not matter, but the prefix is important), and then deleting the node, like so:

```
# patch.yaml
metadata:
  finalizers:
  - controller.cattle.io/node-controller
  - clusterscoped.controller.cattle.io/user-node-remove_abcde
```

```
kubectl patch --patch-file patch.yaml --type=merge -n <CLUSTER_ID (e.g. c-xxxxx)> node.management.cattle.io <NODE> patch.yaml <NODE> && kubectl delete -n <CLUSTER_ID (e.g. c-xxxxx)> node.management.cattle.io <NODE>
```

**Result**

The finalizer stays on the object indefinitely, preventing it from being deleted.

**Expected Result**

The finalizer is removed and the annotation is ignored because the object is already being deleted.

**Screenshots**

**Additional context**

SURE-4806

**Comment by Josh-Diamond** [comment]
Test Plan:

W.I.P.

**Comment by jakefhyde** [comment]
### Root cause

In Rancher `v2.5.2`, the user-node-remove cluster scoped lifecycle was removed and merged with the node controller. In the event that a node is already deleted before the annotation can be applied and the finalizer removed, the node will hang indefinitely.

This can be replicated by creating a node provisioned cluster in `v2.5.1`, stopping rancher and deleting the v3 node object (verifying that the finalizer is present first), and then starting rancher in v2.6.7.

### What was fixed, or what changes have occurred

The finalizer is removed on deletion instead. 
 
### Areas or cases that should be tested

- The finalizer should no longer prevent the object from being deleted in v2.6-head
- Upgrading a rancher install from v2.5.2 -> v2.6-head, the finalizer should still be present on the node until it is deleted, at which point it should be removed.
 
### What areas could experience regressions?
 
N/A

### Are the repro steps accurate/minimal?
:heavy_check_mark:

**Comment by Josh-Diamond** [comment]
Syncing w/ @jakefhyde w.r.t. behavior seen in `Scenario 1`; ticket is being re-opened;
Will continue validation when ticket is back in `to-test`

---

Ticket #38442 - Test Results

With Docker on a single-node instance:

Reproduced on `v2.5.1 => v2.6.6`:
1. Fresh install of rancher `v2.5.1`
2. As admin, provision a downstream AWS Node driver cluster w/  k8s `v1.19.15` - [ 1 etcd, 1 cp, 1 wkr ]
3. Once successfully provisioned, delete worker node + immediately stop rancher + upgrade to `v2.6.6`
4. Observe cluster go into `Unavailable` state on `v2.6.6`, then come up `Active`
5. Reproduced - Node stuck in `Removing` state; `Node scheduled for deletion`

Screenshots:

`Step 7 - Cluster Management`
<img width="1455" alt="Screen Shot 2022-09-06 at 12 54 58 PM" src="https://user-images.githubusercontent.com/46494969/188727017-88a6adfc-1cc0-4ccf-af75-b67ceebef61c.png">

`Step 7 - Cluster Management > Cluster Details > Machine Pools`
<img width="1453" alt="Screen Shot 2022-09-06 at 12 55 10 PM" src="https://user-images.githubusercontent.com/46494969/188727051-0d11b811-988a-4360-b026-4052d535f37e.png">

---

Verified on rancher `v2.5.1 => v2.6.6 => v2.6-400e559407d14ad925caf2f56f5edd8645dbdaba-head`:

Scenario 1 - `Reproduce in v2.6.6 => Upgrade to v2.6-head + verify node deletion` - ❌ 
1. Fresh install of rancher `v2.5.1`
2. As admin, provision a downstream AWS Node driver cluster w/  k8s `v1.19.15` - [ 1 etcd, 1 cp, 1 wkr ]
3. Once `Active`, upgrade rancher to `v2.6.6`; Observe cluster go into `Unavailable` state, then come up `Active`
4. Once `Active` on v2.6.6, add finalizer to a worker node + delete the node
5. Reproduced - Node in `Removing` state w/ message: `Node scheduled for deletion`
6. Upgrade rancher to `v2.6-head`
7.  Veri-FAILED - Node stuck in `Removing` state w/ message: `Node scheduled for deletion`; expected node to be removed

---

Scenario 2 - `In v2.6-head - add finalizer to node, then delete it => Ensure node successfully deleted`
1. Fresh install of rancher `v2.5.1`
2. As admin, provision a downstream AWS Node driver cluster w/  k8s `v1.19.15` - [ 1 etcd, 1 cp, 1 wkr ]
3. Once `Active`, upgrade rancher to `v2.6-head`; Observe cluster go into `Unavailable` state, then come up `Active`
4. Once `Active` on `v2.6-head`, add finalizer to a worker node + delete the node
5.  <RESULT_HERE> - <NODE_EXPECTED_TO_BE_SUCCESSFULLY_DELETED>

Scenario 3 - `Provision cluster in v2.5.1  => Delete node + immediately stop server + upgrade to v2.6-head => verify node successfully deleted upon upgrade`
1. Fresh install of rancher `v2.5.1`
2. As admin, provision a downstream AWS Node driver cluster w/  k8s `v1.19.15` - [ 1 etcd, 1 cp, 3 wkr ]
3. Once successfully provisioned, delete worker node + immediately stop rancher + upgrade to `v2.6-head`
4. Observe cluster go into `Unavailable` state on `v2.6-head`, then come up `Active`
5. <RESULT_HERE> - <NODE_EXPECTED_TO_BE_SUCCESSFULLY_DELETED>

**Comment by Josh-Diamond** [comment]
IN PROGRESS - Ticket #378442 - Test Results [pt. 2] 
---

With Docker on a single-node instance:

Verified on rancher `v2.7-609db0ad434be0f0f8d4578bf4eb03502a39be6d-head`:
- Scenario 1 - ❌ 
   - `Reproduce in v2.6.6 => Upgrade to v2.6-head + verify node deletion`
   
- Scenario 2 - **NOT YET STARTED**
   - `In v2.6-head - add finalizer to node, then delete it => Ensure node successfully deleted`
   
- Scenario 3 - **NOT YET STARTED**
   - `Provision cluster in v2.5.1 => Delete node + immediately stop server + upgrade to v2.6-head => verify node successfully deleted upon upgrade`

---

Scenario 1 - `Reproduce in v2.6.6 => Upgrade to v2.6-head + verify node deletion`:
1. Fresh install of rancher `v2.6.6`
2. As admin, provision a downstream RKE1 AWS Node driver cluster w/ k8s `v1.19.16` - [ 1 etcd, 1 cp, 1 wkr ]
3. Once successfully provisioned, add finalizer to wkr node, then delete wkr node
4. Reproduced - Node in `Removing` state w/ message: `Node scheduled for deletion`
5. Upgrade rancher to `v2.7-head`
6. Veri-FAILED - Node stuck in `Removing` state w/ message: `Node scheduled for deletion`; 
    - `cleanup.cattle.io/user-node-remove: "true"` annotation is present; 
    - `clusterscoped.controller.cattle.io/user-node-remove_abcde` finalizer is present; 
    - expected node to be removed; node still present 1 hour after upgrade to `v2.7-head`

Screenshots:

`Step 3 - Add finalizer`
<img width="550" alt="add-finalizer-before-delete" src="https://user-images.githubusercontent.com/46494969/190025264-c2d0720c-e758-4e19-bb23-2462d886a5ef.png">

`Step 3 - Delete wkr node`
<img width="449" alt="delete-node" src="https://user-images.githubusercontent.com/46494969/190025306-bcac4ba7-985d-420f-b5f7-5b120fb85988.png">

`Step 4 - YAML of wkr node`
<img width="572" alt="yaml-post-delete-reproduced" src="https://user-images.githubusercontent.com/46494969/190025371-c4ab99ff-e7ce-45b9-9bcf-c0118ce48c02.png">

`Step 4 - Cluster Management`
<img width="1332" alt="preupgrade" src="https://user-images.githubusercontent.com/46494969/190025448-512ad60b-1f98-4316-983b-1bc79b4f7079.png">

`Step 4 - Cluster Details > Machine Pools`
<img width="1327" alt="repro-stuck-preupgrade" src="https://user-images.githubusercontent.com/46494969/190025537-4ee1f7ac-6f68-491d-80c0-79c6f9fddac3.png">

`Step 6 - Never resolves`
<img width="1337" alt="post-upgrade-before-cleanup" src="https://user-images.githubusercontent.com/46494969/190025665-2da6c06b-99de-4eb3-8372-04c5155809fc.png">

---

Scenario 2 - `In v2.6-head - add finalizer to node, then delete it => Ensure node successfully deleted`:
1. 

Screenshots

---

Scenario 3 - `Provision cluster in v2.5.1 => Delete node + immediately stop server + upgrade to v2.6-head => verify node successfully deleted upon upgrade`:
1. 

Screenshots

**Comment by Josh-Diamond** [comment]
Ticket #38442 - Test Results [cont.]
---

With HA Helm:

Reproduced on rancher `v2.5.1 => v2.6.8`:
- `User-node-remove` finalizer not being properly cleaned up - ✅ 

Verified on rancher `v2.7-8a2e68267c882a8adf612a29ae2bf3274a4d8572-head`:

- Scenario 1 - ❌ 
    - `Reproduce in v2.6.8 => Upgrade to v2.7-head + verify node deletion`
- Scenario 2 - **NOT YET TESTED**

- Scenario 3 - **NOT YET TESTED**

---

Reproduced on rancher `v2.5.1 => v2.6.8`:
1. Fresh install of rancher `v2.5.1` - [w/ rke `v1.2.0`]
2. Provision a downstream RKE1 AWS Node driver cluster w/ k8s `v1.19.15-rancher1-1`
3. Scale down rancher deployment to `0`:

```
kubectl scale deployment rancher -n cattle-system --replicas=0
```
4. Add finalizer to worker node:

```yaml
# patch.yaml
metadata:
  finalizers:
  - controller.cattle.io/node-controller
  - clusterscoped.controller.cattle.io/user-node-remove_abcde
```
```
kubectl patch --patch-file patch.yaml --type=merge -n <CLUSTER_ID (e.g. c-xxxxx)> node.management.cattle.io <NODE> patch.yaml <NODE>
```

5. Delete worker node:

```
kubectl delete -n <namespace/cluster_id> node.management.cattle.io <NODE>
```

6. Upgrade rancher to `v2.6.8` - [post-upgrade, rancher will automatically be scaled back to 3 replica sets]
7. Reproduced - Node in `Unavailable` state, reporting: `Kubelet stopped posting node status`; 
    - `cleanup.cattle.io/user-node-remove: "true"` annotation is not seen
    - `clusterscoped.controller.cattle.io/user-node-remove_abcde` finalizer is present

---

Scenario 1 - `Reproduce in v2.6.8 => Upgrade to v2.7-head + verify node deletion`:
1. Reproduce issue, following reproduction steps outlined above
2. Upgrade rancher to `v2.7-8a2e68267c882a8adf612a29ae2bf3274a4d8572-head`
3. Veri-FAILED:
    - Cluster in `Provisioning` state;
    - Node is removed from wkr pool and seen `Not in a pool`
    - Node in `Unavailable` state w/ message: `Kubelet stopped posting node status.`
    - `controller.cattle.io/node-controller` finalizer present on node
    -  `cleanup.cattle.io/user-node-remove: "true"` annotation is present on node

**Comment by jakefhyde** [comment]
A previous fix was merged to remove the clusterscoped.controller.cattle.io/user-node-remove_xxxxx finalizer and allow a machine to be deleted, however this would cause new machines to be created for the downstream node. Since the node came from such an old version of rancher, the v3.Node (machine) and the v1.Node (downstream node) could not be correlated, and since the v3.Node was already deleted, there was no way to correlate them. This was causing an orphaned downstream node, which a machine would then be created for. https://github.com/rancher/rancher/pull/39016 solves this by first checking to see if the node is currently being deleted, and if so, do not attempt to reconcile it.

**Comment by jakefhyde** [comment]
### Root cause
In Rancher v2.5.2, the user-node-remove cluster scoped lifecycle was removed and merged with the node controller. In the event that a node is already deleted before the annotation can be applied and the finalizer removed, the node will hang indefinitely.

This can be replicated by creating a node provisioned cluster in v2.5.1, stopping rancher and deleting the v3 node object (colloquially known as the machine object) in the local cluster, in the `c-xxxxx` namespace (which is the cluster ID of the cluster the machine belongs to)after first verifying that the finalizer is present, and then starting rancher on `v2.6-head`.

This is also reproducible by creating a node on v2.6.8, stopping rancher, manually adding the following finalizer: `clusterscoped.controller.cattle.io/user-node-remove_abcde`, and deleting the associated cleanup annotation: `cleanup.cattle.io/user-node-remove` by setting it to `null` and then performing the upgrade to `v2.6-head`. 

### What was fixed, or what changes have occurred

The finalizer is removed on sync instead, which should happen on startup, when the node is modified, or after an internal interval (I observer this to be ~5 minutes, but YMMV). The "stuck" node should have the finalizer removed, and be deleted.

A previous fix was merged (on `release/v2.7`) to remove the `clusterscoped.controller.cattle.io/user-node-remove_xxxxx` finalizer and allow a machine to be deleted, however this would cause new machines to be created for the downstream node. Since the node came from such an old version of rancher, the v3.Node (machine) and the v1.Node (downstream node) could not be correlated, and since the v3.Node was already deleted, there was no way to correlate them. This was causing an orphaned downstream node, which a machine would then be created for, despite the fact that the machine had a `deletionTimestamp`, and realistically there is not reason to create a machine for a downstream node that is already being deleted, especially when the infstructure no longer exists (i.e. the hardware from e.g. DO has already been destroyed). https://github.com/rancher/rancher/pull/39016 solved this in `release/v2.7` by first checking to see if the node is currently being deleted, and if so, do not attempt to reconcile it.

### Areas or cases that should be tested
The finalizer should no longer prevent the object from being deleted in v2.6-head
Upgrading a rancher install from v2.5.2 -> v2.6-head, the finalizer should still be present on the node until it is deleted, at which point it should be removed.
What areas could experience regressions?
N/A

### Are the repro steps accurate/minimal?
:heavy_check_mark:

**Comment by Josh-Diamond** [comment]
Ticket #38442 - Test Results [cont.]
---

With HA Helm:

Reproduced on rancher `v2.5.1 => v2.6.8`:
- Reproduction - ✅ 
    - `User-node-remove` finalizer not being properly cleaned up 

---

Verified on rancher `v2.7-cadad2e8f1285bcfc136484d4dcbf73c7b5e7bb8-head`:

- Scenario 1 - ❌ 
    - Test: `Reproduce in v2.6.8 => Upgrade to v2.7-head + verify node deletion`
    - Result: Local cluster terminated; Worker node not removed
- Scenario 2 - ❌ 
   - Test: `In v2.7-head - add finalizer to node, then delete it => Ensure node successfully deleted`
   - Result: Worker node `scheduled for deletion` hangs
- Scenario 3 - ❌ 
   - Test: `Provision cluster in v2.5.1 => stop rancher, add finalizer, delete node + upgrade to v2.7-head => verify node successfully deleted upon upgrade`
   - Result:  Local cluster is missing; original issue appears to be resolved

---

Reproduced on rancher `v2.5.1 => v2.6.8`:
1. Fresh install of rancher `v2.5.1` - [w/ rke `v1.2.0`]
2. Provision a downstream RKE1 AWS Node driver cluster w/ k8s `v1.19.15-rancher1-1`
3. Scale down rancher deployment to `0`:

```
kubectl scale deployment rancher -n cattle-system --replicas=0
```
4. Add finalizer to worker node:

```yaml
# patch.yaml
metadata:
  finalizers:
  - controller.cattle.io/node-controller
  - clusterscoped.controller.cattle.io/user-node-remove_abcde
```
```
kubectl patch --patch-file patch.yaml --type=merge -n <CLUSTER_ID (e.g. c-xxxxx)> node.management.cattle.io <NODE> patch.yaml <NODE>
```

5. Delete worker node:

```
kubectl delete -n <namespace/cluster_id> node.management.cattle.io <NODE>
```

6. Upgrade rancher to `v2.6.8` - [post-upgrade, rancher will automatically be scaled back to 3 replica sets]
7. Reproduced - Node in `Unavailable` state, reporting: `Kubelet stopped posting node status`; 
    - `cleanup.cattle.io/user-node-remove: "true"` annotation is not seen
    - `clusterscoped.controller.cattle.io/user-node-remove_abcde` finalizer is present

---

Scenario 1 - `Reproduce in v2.6.8 => Upgrade to v2.7-head + verify node deletion`:
1. Reproduce issue, following reproduction steps outlined above
2. Veri-FAILED: local cluster terminated
3. Upgrade rancher to `v2.7-cadad2e8f1285bcfc136484d4dcbf73c7b5e7bb8-head`
4. Veri-FAILED:
    - Cluster in `Provisioning` state;
    - Node is removed from wkr pool and seen `Not in a pool`
    - Node in `Unavailable` state w/ message: `Kubelet stopped posting node status.`
    - `controller.cattle.io/node-controller` finalizer present on node
    -  `cleanup.cattle.io/user-node-remove: "true"` annotation is present on node
    - local cluster is restored and `active`

Screenshots:

`Step 2 - Issue is reproduced - wkr node YAML`
<img width="904" alt="reproduced-proof" src="https://user-images.githubusercontent.com/46494969/192391704-73281980-6409-45de-8f49-76f06bb50c59.png">

`Step 2 - Local cluster terminated`
<img width="467" alt="Screen Shot 2022-09-26 at 12 29 49 PM" src="https://user-images.githubusercontent.com/46494969/192391974-835e34a6-d2d3-4100-8586-5c238242c76e.png">

`Step 4 - Post-upgrade, "Docker machine exists"`
<img width="531" alt="Screen Shot 2022-09-26 at 3 31 01 PM" src="https://user-images.githubusercontent.com/46494969/192392165-86ec4a20-ccdc-47f5-a3b9-79b47c2f7a46.png">

`Step 4 - Post-upgrade, cluster w/ node hanging "Not in a pool"`
<img width="479" alt="Screen Shot 2022-09-26 at 3 31 48 PM" src="https://user-images.githubusercontent.com/46494969/192392246-f2682cb3-8652-4327-b335-f4363d82edfe.png">

`Step 4 - Final result, after some time`
<img width="1472" alt="post-upgrade-local-restore" src="https://user-images.githubusercontent.com/46494969/192392412-624dce96-a6dc-48fc-be70-075778d90ebe.png">

---

Scenario 2 - `In v2.7-head - add finalizer to node, then delete it => Ensure node successfully deleted`
1. Fresh install of rancher `v2.7-head`
2. Provision a downstream RKE1 AWS Node driver cluster w/ k8s `v1.19.16-rancher2-1`
3. Once `active`, stop rancher server, add finalizer to worker node, delete worker node, then start rancher server
4. Veri-FAILED: Worker node `Scheduled for deletion`; new worker node provisions and comes up `active`, Worker node `scheduled for deletion` hangs

Screenshots:

`Step 4 - Cluster Details > Machine Pools`
<img width="747" alt="Screen Shot 2022-09-26 at 4 38 36 PM" src="https://user-images.githubusercontent.com/46494969/192399518-a9db603a-5f2a-4df6-8801-6c4d304b3101.png">

`Step 4 - Worker node stuck YAML`
<img width="562" alt="final-screenshot-scenario-2" src="https://user-images.githubusercontent.com/46494969/192399560-570baeea-aa1a-4422-aa1b-cea3fb2497bf.png">

---

Scenario 3 - `Provision cluster in v2.5.1 => stop rancher, add finalizer, delete node + upgrade to v2.7-head => verify node successfully deleted upon upgrade`:
1. Fresh install of rancher `v2.5.1` - [w/ rke `v1.2.0`]
5. Provision a downstream RKE1 AWS Node driver cluster w/ k8s `v1.19.15-rancher1-1`
6. Scale down rancher deployment to `0`:

```
kubectl scale deployment rancher -n cattle-system --replicas=0
```
7. Add finalizer to worker node:

```yaml
# patch.yaml
metadata:
  finalizers:
  - controller.cattle.io/node-controller
  - clusterscoped.controller.cattle.io/user-node-remove_abcde
```
```
kubectl patch --patch-file patch.yaml --type=merge -n <CLUSTER_ID (e.g. c-xxxxx)> node.management.cattle.io <NODE> patch.yaml <NODE>
```

8. Delete worker node:

```
kubectl delete -n <namespace/cluster_id> node.management.cattle.io <NODE>
```

9. Upgrade rancher to `v2.7-head`
10. Veri-FAILED: 
    - Post-upgrade, local cluster is no longer seen
    - Original issue appears to be resolved, but local cluster is affected by fix

Screenshots:

`Step 7 - No local cluster, Post-upgrade`
<img width="1473" alt="no-local" src="https://user-images.githubusercontent.com/46494969/192393028-80c1a598-eaab-4ae8-a2f3-ada20ae07d58.png">

`Step 7 - No local namespace`
<img width="439" alt="no-local-ns" src="https://user-images.githubusercontent.com/46494969/192393262-aaa299f5-528a-4434-bbd6-8414de581d27.png">

`Step 7 - Final result, cluster is `Active`, local is missing`
<img width="1473" alt="active-cluster-no-local" src="https://user-images.githubusercontent.com/46494969/192393356-8ee0d068-a400-413d-a1cd-c5aa11f97ebb.png">

**Comment by jakefhyde** [comment]
### Root cause

When a node is deleted/deleting while rancher is upgraded from a version `< v2.6.7`, the `cluster.Status.ServiceAccountTokenSecret` is not yet populated. There was a bug in the internal logic of acquiring a rest config for a downstream cluster, where this would cause a `nil` rest config to be returned, with a `nil` error. The only other case for this was when a cluster either hadn't been provisioned yet, or was already being deleted. This caused the `Remove` function for a `v3.Node` object to (incorrectly) exit prematurely, and rancher to (correctly) create an unmanaged `machine-`prefixed `v3.Node` object for the orphaned `v1.Node`.

### What was fixed, or what changes have occurred

If the `ServiceAccountSecretsMigrated` condition is not true for the cluster, return an error. The `v1.Node` removal in the downstream cluster will be re-attempted until this field is populated.

### Areas or cases that should be tested

- On v2.5.1, provision a 1 etcd, 1 controlplane, 3 worker cluster
- Download a kubeconfig for the local cluster
- Download a kubeconfig for the downstream cluster
- Using the kubeconfig for the local cluster:
  - Stop rancher with the following command: `kubectl scale deploy -n cattle-system --replicas=0 rancher`
	- Run the following command to delete a worker node: `kubectl delete node.management.cattle.io -n <CLUSTER_ID (e.x. c-xxxxx)> <MACHINE_ID (e.x. m-xxxxx)> --wait=false`
  	- We use `--wait=false`, since `kubectl delete` will wait for finalizers by default
  - Perform a helm upgrade of rancher to the desired version
    - Example command: `helm upgrade --install rancher rancher-latest/rancher --namespace cattle-system --set hostname=<HOSTNAME> --version v2.7-head`
  - Observe that the `v3.Node` (machine) object was successfully removed in the local cluster: `kubectl get node.management.cattle.io -A`
- Using the kubeconfig for the downstream cluster:
  - Observe that the `v1.Node` object was successfully removed in the downstream cluster: `kubectl get node`
- No `machine-` objects should be created for the `v1.Node` in the downstream, since it has been deleted

### What areas could experience regressions?

- This bug was present on rancher versions `< v2.6.7`, so `machine-` objects (which are unmanaged i.e. no infrastructure `node.management.cattle.io` objects in the local cluster created for `v1.Node` objects in the downstream, could potentially be created in environments where a downstream is provisioned on `v2.6.6`, the rancher server is paused, and then upgraded to `v2.6.7`. There is no way to clean up these objects if this happens, however provisioning on v2.6.6`, stopping rancher, and then upgrading to `v2.7-head` should no longer create these `machine-` objects, and both the `v3.Node` in the local cluster and the `v1.Node` in the downstream cluster should be deleted successfully.

### Are the repro steps accurate/minimal?
:heavy_check_mark:

**Comment by Josh-Diamond** [comment]
Test Plan - Revised
---

Scenario 1:
- Reproduce in `v2.6.8` => Upgrade to `v2.7-head`; verify node successfully deletes

Scenario 2:
- Provision cluster in `v2.6.6` => stop rancher, delete node + upgrade to `v2.7-head`; verify node successfully deletes

Scenario 3:
-  Provision cluster in `v2.5.1` => stop rancher, delete node + upgrade to `v2.7-head` => verify node successfully deletes

**Comment by Josh-Diamond** [comment]
Ticket #38442 - Test Results [cont.] - IN PROGRESS
---

With HA Helm + RKE1 local:

Verified on rancher `v2.7-1456576dc70b646e8457024e6d44e9691ed517ba-head`:

Summary
---

| Scenario | Test Case | Result |
|---|---|---|
|1|Reproduce in `v2.6.8` => Upgrade to `v2.7-head`; verify node successfully deletes|✅|
|2|Provision cluster in `v2.5.1` => stop rancher, delete node + upgrade to `v2.7-head` => verify node successfully deletes| **NOT STARTED**|
|3|Provision cluster in v2.5.1 => stop rancher, delete node + upgrade to v2.7-head => verify node successfully deletes|**NOT STARTED**|
---

Details
---

Scenario 1:
1. Fresh install of rancher `v2.5.1`
2. Provision a downstream RKE1 AWS Node driver cluster - [3 nodes, individual roles]
3. Once `Active`, download kubeconfig of downstream cluster - [save for later use]
4. Using kubeconfig of local cluster, stop rancher by scaling deployment to `0`:
```
kubectl scale deployment rancher -n cattle-system --replicas=0
```
5. Delete worker node using the following command:
```
kubectl delete node.management.cattle.io -n <CLUSTER_ID> <MACHINE_ID> --wait=false
```
6. Upgrade rancher to `v2.6.8`
7. Observe worker node stuck in deletion; Observe new worker node successfully provisions
8. Once new worker node is `Active`, upgrade rancher to `v2.7-head`
9. Verified - Node successfully deletes; cluster comes up `Active`
10. Verified - v3 node object removed from local cluster
```
kubectl get node.management.cattle.io -A
```
11. Verified - v1 node object removed from downstream cluster [verify w/ kubeconfig from step 3]
```
kubectl get nodes
```

---

Scenario 2:
1.

---

Scenario 3:
1.
