### ISSUE TITLE
Upgrade gatekeeper charts to 3.9.0

### ISSUE THREAD

**Issue by mitulshah-suse** [rancher/rancher#38450]
Upgrade rancher-gatekeeper chart to latest releases. As of July 28, 2022 the latest gatekeeper version is 3.9.0

**Comment by vivek-infracloud** [comment]
Tested the OPA gatekeeper 101.0.0+up3.9.0 on Rancher v2.7-head. Created the constraints using the default templates for Namespace and Repository and it's working as expected.

![Screenshot from 2022-09-22 18-08-48](https://user-images.githubusercontent.com/83208989/191749321-5162ebf6-6c99-4170-b3d2-b9d3a0e2f40e.png)

![Screenshot from 2022-09-22 18-08-36](https://user-images.githubusercontent.com/83208989/191749251-a7f57f47-dda4-428a-9598-539caa9cb53b.png)
