### ISSUE TITLE
[BUG] CIS scan fails on RKE1 hardened HA setup

### ISSUE THREAD

**Issue by rishabhmsra** [rancher/rancher#38453]
**Rancher Server Setup**
- Rancher version: v2.6.7-rc3
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):

**Information about the Cluster**
- Kubernetes version: v1.24.2-rancher1-1
- Cluster Type (Local/Downstream): Local
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Admin
  - If custom, define the set of permissions:

**Describe the bug**

- On RKE1 hardened HA setup, CIS 1.20 and 1.23 hardened profile scan fails.

**To Reproduce**

- Create RKE1 k8s v1.24, hardened HA cluster(`3-nodes all roles`) using this [hardening guide](https://rancher.com/docs/rancher/v2.6/en/security/hardening-guides/rke-1.6-hardening-2.6/).
- Deploy rancher v2.6.7-rc3.
- Install CIS benchmark 2.0.5-rc6 on local cluster.
- Run the scans using 1.20 and 1.23 hardened profile scans.

**Result**
- Observe the below failures in the scan:

**1.23 profile :**
![1 23-error](https://user-images.githubusercontent.com/36376154/181513597-dfcc9e45-f46c-492a-988b-bb864f32d5a6.png)

--------------------------------------------------------

**1.20 profile:**
![1 20-error](https://user-images.githubusercontent.com/36376154/181513720-9ff2b541-bf38-4edd-b0dc-cbd1b716d71e.png)

**Expected Result**

- Scan should pass successfully.

**Additional context**

**Comment by mitulshah-suse** [comment]
The scan is failing due to known issue as described in the hardening [guide](https://rancher.com/docs/rancher/v2.6/en/security/hardening-guides/rke-1.6-hardening-2.6/)
The fleet-content ClusterRole seems to be causing the failure as described in the guide.
Moving the issue back to testing.

**Comment by rishabhmsra** [comment]
From the above comment seems like it's a known issue and it's documented. CIS 5.1.5 check expects default service accounts have no roles or cluster roles bound to it. Based on the same closing the issue.
