### ISSUE TITLE
Change name for the kubeconfig TTL setting.

### ISSUE THREAD

**Issue by KevinJoiner** [rancher/rancher#38456]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by KevinJoiner** [comment]
Related to https://github.com/rancher/rancher/issues/37705

**Comment by KevinJoiner** [comment]
## Root Cause
The TTL is for the token used in the kubeconfig, not the kubeconfig itself. Since this is for a new setting that has not been released, we should change the name to accurately represent what the setting is controlling.

## Fix
Update the token name from `kubeconfig-default-ttl-minutes` -> `kubeconfig-default-token-ttl-minutes`
## Areas or cases that should be tested
Update the name to better represent that the setting is for the token used with kubeconfigs, not the config itself.

-  Verify the new token setting is readable through norman and steve.
     1. Start a new rancher instance
     2. Verify you can navigate to `https://<rancher-server>/v1/management.cattle.io.settings/kubeconfig-default-token-ttl-minutes`
     3. Verify you can naviagte to `https://<rancher-server>/v3/settings/kubeconfig-default-token-ttl-minutes`

**Comment by anupama2501** [comment]
v2.6-head 6629e3e

1. verified https://<rancher-server>/v1/management.cattle.io.settings/kubeconfig-default-token-ttl-minutes
2. Verified  https://<rancher-server>/v3/settings/kubeconfig-default-token-ttl-minutes
3. Verified navigating to explorer >> Global settings >> changing the value of `kubeconfig-default-token-ttl-minutes`
