### ISSUE TITLE
Upgrade Istio versions to 1.14.3

### ISSUE THREAD

**Issue by mitulshah-suse** [rancher/rancher#38451]
Upgrade Istio to the latest release of 1.14.3

**Comment by vivek-infracloud** [comment]
Validated on rancher/rancher:v2.7-head (10fd32b)

Created a downstream cluster with 3worker, 3etcd, 2 cp

**Tested Istio charts for version 100.3.0+up1.14.3, Kiali - v1.55.0, and Jaeger - v1.37.0.**
**Tested following scenarios. all the tested scenarios passed the checks.**

- Fresh install checks
- Upgrade test case from istio 1.13.3 —> 1.14.3
- Upgrade with custom overlay
- Kiali
- Jaeger traces
- Reinstall with Kiali and Jaeger enabled
- Fresh install with modified ingress gateway
- Reinstall
- Istio pointing to externally-installed Prometheus
- Multiple ingress
- Egressgateway

Istio 1.14.3, Kiali and Jaeger are working fine for all the tested scenarios. Hence, closing the issue.
