### ISSUE TITLE
Feature charts: Add Longhorn 1.3.1 chart in 2.7

### ISSUE THREAD

**Issue by rebeccazzzz** [rancher/rancher#38463]
Longhorn has an upcoming release 1.3.1 which will be released around the middle of August so we need to add this new release in the feature charts along with the upcoming Rancher 2.7.x.

Probably need to make it OOB if need to release it earlier. 

- Add 1.3.1 LH chart in feature chart - Cluster Manager/Rancher Marketplace

cc @khushboo-rancher @yasker @MKlimuszka @deniseschannon @meldafrawi @cchien816 @yangchiu @prachidamle

**Comment by innobead** [comment]
This needs OOB release as 1.3.0.

**Comment by MKlimuszka** [comment]
This will be an OOB release after 2.7.0 is released.

**Comment by innobead** [comment]
Longhorn 1.3.2 has been released, so we don't need to OOB this anymore but rather https://github.com/rancher/rancher/issues/39224.

cc @rebeccazzzz @PhanLe1010
