### ISSUE TITLE
[BUG] Creating rke2 airgapped custom clusters fail immediately with failed calling webhook in an airgapped 

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#38475]
**Rancher Server Setup**
- Rancher version: `v2.6.7-rc5`
- Installation option (Docker install/Helm Chart): Docker install
   - If Helm Chart, Kubernetes Info: k3s
         Cluster Type (RKE1, RKE2, k3s, EKS, etc):
         Node Setup: 1 node 
         Version: `v1.24.2+k3s1`
- Proxy/Cert Details: `self-signed`

**Information about the Cluster**
- Kubernetes version: `v1.24.2+rke2r1
- Cluster Type (Local/Downstream): `Custom RKE2`

**Describe the bug**
When creating an rke2 aigrapped custom cluster,  we are immediately hit with a webhook-service error with default settings for the cluster create even before adding nodes.

**To Reproduce**
Create a custom rke2 cluster

**Result**
Fails with the error 
```
Failed to create fleet-default/anucustomrke2 cluster.x-k8s.io/v1beta1, Kind=Cluster for rke-cluster fleet-default/anucustomrke2: Internal error occurred: failed calling webhook "default.cluster.cluster.x-k8s.io": failed to call webhook: Post "https://webhook-service.cattle-system.svc:443/mutate-cluster-x-k8s-io-v1beta1-cluster?timeout=10s": service "webhook-service" not found

```

**Expected Result**
No error expected.

**Screenshots**
<img width="400" alt="customrke2" src="https://user-images.githubusercontent.com/38144301/181920705-da718ee6-6748-49a2-aa53-3fdd1ec79864.png">

**Comment by jakefhyde** [comment]
Also encountered this issue with a fresh install of rancher on `v2.6.6`

**Comment by kinarashah** [comment]
@anupama2501 Did you see webhook service deployed in the local cluster? Sometimes it takes a while for the service to be up, the cluster creation will fail if webhook isn't present. Are there any errors in the rancher logs?

**Comment by anupama2501** [comment]
This works on an airgap HA rancher server. On docker airgap servers, webhook is not deployed in the local cluster and thereby the rke2 provisioning fails. 
Some error logs found in the helm operations: 
```
Failed to pull image "<privatereg>/rancher/shell:v0.1.18-rc8": rpc error: code = Unknown desc = failed to pull and unpack image "ec2-3-141-47-228.us-east-2.compute.amazonaws.com/rancher/shell:v0.1.18-rc8": failed to resolve reference "<privatereg>/rancher/shell:v0.1.18-rc8": failed to do request: Head "https://<privatereg>/v2/rancher/shell/manifests/v0.1.18-rc8": x509: certificate signed by unknown authority
```
Could be an issue with the setup.

**Comment by anupama2501** [comment]
From offline conversation it was confirmed to be a setup issue. Closing the ticket
