### ISSUE TITLE
[BUG] Airgap - RKE1 custom clusters stuck on provisioning state on k8s version 1.24

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#38473]
**Rancher Server Setup**
- Rancher version: `v2.6.7-rc5` Airgapped
- Installation option: Docker k3s
- Proxy/Cert Details: valid certs

**Information about the Cluster**
- Kubernetes version: `v1.24.2-rancher1-1` 
- Cluster Type : Downstream
   - Custom RKE1
**User Information**
- What is the role of the user logged in? `Admin`

**Describe the bug**

Registering a node with custom rke cluster, the state of the cluster stays in provisioning indefinitely.
The cluster is an airgapped RKE1 Custom cluster  

**To Reproduce**
- Setup Rancher Airgap `v2.6.7-rc5`
- Provision a Custom RKE1 cluster with 1 node all roles. Use `v1.24.2-rancher1-1`
- Copy paste the provided command in the node that's Airgapped
- Wait for the cluster to come up active

**Result**
Cluster stays in provisioning state and the following error is seen 
```
[controlPlane] Failed to upgrade Control Plane: [[host ip-172-31-3-141 not ready]]
```
Some errors seen in the kubelet logs:
```
I0729 22:34:11.578162    6258 kuberuntime_manager.go:469] "No sandbox for pod can be found. Need to start a new one" pod="kube-system/rke-network-plugin-deploy-job-nt5dn"
time="2022-07-29T22:34:11Z" level=info msg="Pulling the image without credentials. Image: /rancher/mirrored-pause:3.6"
E0729 22:34:11.593356    6258 remote_runtime.go:212] "RunPodSandbox from runtime service failed" err="rpc error: code = Unknown desc = failed pulling image \"redacted/rancher/mirrored-pause:3.6\": Error response from daemon: Get https://<redacted>/v2/rancher/mirrored-pause/manifests/3.6: no basic auth credentials"
E0729 22:34:11.593509    6258 kuberuntime_sandbox.go:70] "Failed to create sandbox for pod" err="rpc error: code = Unknown desc = failed pulling image \"redacted/rancher/mirrored-pause:3.6\": Error response from daemon: Get https:///v2/rancher/mirrored-pause/manifests/3.6: no basic auth credentials" pod="kube-system/rke-network-plugin-deploy-job-nt5dn"
E0729 22:34:11.593569    6258 kuberuntime_manager.go:815] "CreatePodSandbox for pod failed" err="rpc error: code = Unknown desc = failed pulling image \"redacted/rancher/mirrored-pause:3.6\": Error response from daemon: Get https:///v2/rancher/mirrored-pause/manifests/3.6: no basic auth credentials" pod="kube-system/rke-network-plugin-deploy-job-nt5dn"
E0729 22:34:11.593687    6258 pod_workers.go:951] "Error syncing pod, skipping" err="failed to \"CreatePodSandbox\" for \"rke-network-plugin-deploy-job-nt5dn_kube-system(2fd3406a-563a-4979-8cda-f1734e07f8d7)\" with CreatePodSandboxError: \"Failed to create sandbox for pod \\\"rke-network-plugin-deploy-job-nt5dn_kube-system(2fd3406a-563a-4979-8cda-f1734e07f8d7)\\\": rpc error: code = Unknown desc = failed pulling image \\\redacted"redacted/rancher/mirrored-pause:3.6\\\": Error response from daemon: Get https:///v2/rancher/mirrored-pause/manifests/3.6: no basic auth credentials\"" pod="kube-system/rke-network-plugin-deploy-job-nt5dn" podUID=2fd3406a-563a-4979-8cda-f1734e07f8d7
E0729 22:34:11.823388    6258 kubelet.go:2349] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized"
E0729 22:34:16.841527    6258 kubelet.go:2349] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized"
E0729 22:34:21.858581    6258 kubelet.go:2349] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized"
```

**Expected Result**
Expected the cluster to come up active

**Screenshots**
<img width="300" alt="rke1-airgap" src="https://user-images.githubusercontent.com/38144301/181855677-07d0e010-d582-4c3e-9745-78b389455477.png">

**Additional context**
Issue not see on 1.23 k8s on the same rancher server.

**Comment by sowmyav27** [comment]
**On 2.6.7-rc7**

- Deployed an airgapped rancher.
- Deployed an RKE1 1.24.2 k8s cluster - 1 etcd, 1 cp and 1 worker nodes
- Cluster is stuck in Provisioning state with error `[controlPlane] Failed to upgrade Control Plane: [[host ip-xyz not ready]]`
- Error in kubelet logs of control plane node : 

```
time="2022-08-09T03:36:10Z" level=info msg="Pulling the image without credentials. Image: registry/rancher/mirrored-pause:3.6"
E0809 03:36:10.649209    5223 remote_runtime.go:212] "RunPodSandbox from runtime service failed" err="rpc error: code = Unknown desc = failed pulling image \"registry/rancher/mirrored-pause:3.6\": Error response from daemon: Get https://registry/v2/rancher/mirrored-pause/manifests/3.6: no basic auth credentials"
E
```

**Comment by kinarashah** [comment]
https://github.com/rancher/rke-tools/pull/156

**Comment by kinarashah** [comment]
https://github.com/rancher/kontainer-driver-metadata/pull/945

**Comment by kinarashah** [comment]
https://github.com/rancher/rke/pull/3005

**Comment by sowmyav27** [comment]
**On `2.6.7-rc9`**

- Deployed an RKE1 `v1.24.2` custom cluster - 1 etcd/cp and 1 worker nodes
- Cluster deploys successfully. 
- All workloads in System Project page is up and Active
- Deployed an RKE1 `v1.23.8` custom cluster - 1 etcd/cp and 1 worker nodes
- Cluster deploys successfully. All workloads in System Project page is up and Active
- Upgraded 1.23.8 k8s cluster to 1.24.2 k8s version
- Cluster upgrades successfully.
