### ISSUE TITLE
[BUG] When provisioning RKE1 downstream node driver cluster, the message `Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized` appears

### ISSUE THREAD

**Issue by markusewalker** [rancher/rancher#38489]
**Rancher Server Setup**
- Rancher version: `v2.6-head` https://github.com/rancher/rancher/commit/93a4f30d9c361c8c274f58ebdff73e4f6cc45a81
- Installation option (Docker install/Helm Chart): Docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: `v1.24.2-rancher1-1`
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): AWS

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Admin
  - If custom, define the set of permissions:

**Describe the bug**

When provisioning a downstream RKE1 AWS node driver cluster, I am seeing the following regression:

![image](https://user-images.githubusercontent.com/52591819/182239195-c4277324-9c3a-43b8-8ad8-cf306e2b77dd.png)

I was not seeing this issue prior to the above-mentioned Rancher version that I am using, so this seems to be a recent regression that has occurred.

**To Reproduce**

1. Setup Rancher and navigate to the UI in a browser.
2. Provision a downstream RKE1 AWS node driver cluster (any other node driver should have this issue).
3. While provisioning, click the cluster's name and look at the `Machine Pools` tab.
4. Once Kubernetes registers on the machine, you should see this error message.

**Result**

- The RKE1 cluster does not provision successfully as expected.
- Error in Kubelet logs:

```
E0801 21:00:08.442938   15053 pod_workers.go:951] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"install-cni\" with ImagePullBackOff: \"Back-off pulling image \\\"rancher/calico-cni:v3.22.0-rancher1\\\"\"" pod="kube-system/canal-wpqk6" podUID=1e191e2c-5075-4d5c-b439-6d293496c7f3
```

**Expected Result**
The RKE1 cluster should provision successfully as expected.

**Note:**

happens on 1.23 k8s also

**Comment by sowmyav27** [comment]
Happens on latest 2.6head also `20d6e22`

**Comment by markusewalker** [comment]
Additionally, I verified that when provisioning with `v1.23.8-rancher1-1`, I am seeing this behavior as well. So it seems that RKE1 provisioning is not working across multiple versions.

**Comment by snasovich** [comment]
`rancher/calico-cni:v3.22.0-rancher1` image was not published. It's now available (https://hub.docker.com/layers/calico-cni/rancher/calico-cni/v3.22.0-rancher1/images/sha256-2c8ff36b18871c36b194dd61ae4077a2639f71097d13f976fa4379b651d1ad3d?context=explore) and the issue is ready to retest.

**Comment by markusewalker** [comment]
Verified in `v2.6-head` that I can once more provision RKE1 clusters.

**ENVIRONMENT DETAILS**
- Rancher Install: Docker
- Rancher version: `v2.6-head` https://github.com/rancher/rancher/commit/88888601e472fb629f30a3eb6bc3321bc93db8b7
- Browser: Chrome

**TEST RESULT**
PASS

**VERIFICATION STEPS**
1. Setup Rancher and navigate to the UI in a browser.
2. Create a standard user.
3. Provision a downstream RKE1 downstream node driver cluster; verified that it comes up as active:
![image](https://user-images.githubusercontent.com/52591819/182428035-2a6d7a00-19f8-41ec-98e0-37c8360c4d64.png)
     - Provisioned both a 1.23 and a 1.24 cluster as shown above. Additionally, created clusters using standard user as well and this was successful.
