### ISSUE TITLE
Research and design roadmap for automated testing framework for individual helm charts

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#38488]
With QA involvement, design an automated testing framework for individual helm charts. Then split it into workable areas with separate levels of effort.

SURE-5081

**Comment by aiyengar2** [comment]
The general outline for automated testing frameworks is contained in Confluence.

https://github.com/aiyengar2/hull is the outcome of designing such an automated testing framework for non-live cluster tests on the templates generated by Helm charts.

**Comment by aiyengar2** [comment]
Moving this back to triage to identify if we need to execute on any of the remaining tasks in the outline or whether Hull is sufficient to close out this ticket.

**Comment by gunamata** [comment]
@MKlimuszka , This ticket looks like it can be closed? Is there anything Maaps team needs to takeover?

**Comment by prachidamle** [comment]
yes this can be closed now since Hull framework has been designed and implemented https://github.com/rancher/hull

Work to apply this for CIS, Backup-restore, Istio and Gatekeeper is in progress.
