### ISSUE TITLE
[RFE] Implement SAML Single Logout 

### ISSUE THREAD

**Issue by susenguyen** [rancher/rancher#38494]
**Rancher Server Setup**
- Rancher version: 2.6.6
- Installation option Helm chart
   - RKE2 & RKE

**Information about the Cluster**
- Kubernetes version: 1.23.7
- Cluster Type Local

**Describe the bug**
When integrating Rancher 2.6.6 with a SAML provider (we tried with Keycloak and Shibboleth), after a logout, if the user presses F5, he/she gets to login again without providing his/her credentials.

**To Reproduce**
- Login
- Logout
- Hit <F5>

**Result**
The user logs in again without providing credentials

**Expected Result**
Rancher should ask for your credentials

**Additional context**
Looking at the code (in pkg/auth/providers/saml), we are missing a single logout handler.
https://docs.oasis-open.org/security/saml/Post2.0/sstc-saml-tech-overview-2.0-cd-02.html#5.3.Single%20Logout%20Profile|outline

**Comment by samjustus** [comment]
SURE-3572

**Comment by andreas-kupries** [comment]
### Research Status

Rancher processes UI logout requests in `pkg/auth/tokens`.

The existing code removes the relevant cookies from the browser and deletes the Rancher Token
resource associated with the current user.

This part has to be expanded to perform the SAML logout as well.

It is not possible to directly call into the `pkg/auth/providers` packages, as these use the tokens
package themselves, leading to an import loop.

This can be solved by extending the `tokens` package with a global callback invoked during logout
processing, if set.

Setting the callback to a suitable function during auth provider setup means that this function has
access to the `auth/provider` functionality while hiding this fact from the token manager.

The logout workflow is like the SSO a back and forth between the various components, i.e. Rancher,
IdP, and Browser.

It was attempted to avoid the latter by directly fetching the logout redirect url from within
Rancher.

This failed with KeyCloak (the IdP used for testing) returning an `unknown error`. The KC log
indicated a missing KEYCLOAK_IDENTITY cookie. I.e. this was likely an auth failure before auth could
even be checked. Inspection of the browser cookie management found such a cookie for the local KC
instance.

And with a proper redirect through the browser this kind of cookie should then be picked up and
properly auth the request.

Today this was tried, i.e. the code for the callback rewritten to have access to the initial logout
request and pending response structures and initiating a redirect in the response.

This also failed, to the point that KC did not even record any logout request, something which
happened for the direct fetch trialed before.

At this point I suspect that the Rancher UI fails to properly handle the redirect request we
return. It seems to ignore the result from its own logout request and simply continue on to showing
the main Rancher login and welcome form.

If that is true it means that the extended logout will require UI changes too.

Although it is not known to me yet where such changes have to happen.

This requires research into the UI code.

**Comment by samjustus** [comment]
@gaktive can we get someone from your team to assist on Andreas research here?

**Comment by richard-cox** [comment]
I've added a comments to the JIRA issue. We might need to step back and plan this a bit more

**Comment by gaktive** [comment]
Related UI ticket: https://github.com/rancher/dashboard/issues/10941

**Comment by samjustus** [comment]
https://github.com/rancher/rancher-docs/issues/1431

**Comment by andreas-kupries** [comment]
# Release Note

Added support for SAML `logout-all` to the SAML-based external auth providers. A `logout-all` logs a user not only out of Rancher, but also out of the associated session in the EAP. This logs the user out of other applications attached to the same session as well. When logging into Rancher again a full authentication has to be performed to reestablish a new session in the EAP. This is in contrast to a regular logout where a re-login re-uses the session and bypasses the need for actual re-authentication.

Extended the EAP configuration form enabling the configuring admin to choose whether `logout-all` will be available to users or not, and if yes, if users may even be forced to always use `logout-all` instead of having a choice between it and regular logout.

**Comment by nickwsuse** [comment]
Verified on v2.10-head ID: `212d8b6` ✅ 
----
Tested on both a fresh install of v2.10-head and an upgrade from v2.9.3, and Okta was used for SAML based testing while Github OAuth was used for non-SAML testing.

- Verify that users logged in with SAML auth provider are properly logged out of Rancher.
- Verify that users logged in with SAML auth provider are properly logged out of Okta.
- Verify that users logged in with SAML auth provider are prompted with an option to choose their preferred logout method, and that method properly logs them out of Rancher or the SAML provider.
- Verify that when users log out of Rancher with the "Logout All" option selected, they are logged out of the SAML provider as well as their credentials being required for the next login attempt.
- Verify that when users are connected to ADFS they are still able to use the CLI to login and logout as expected. 
- Verify that when logging out of Rancher with Keycloak SAML auth enabled, there is no error returned on the UI or the logs.
- Verify that on a fresh install of Rancher v2.10.0, when enabling non-SAML auth providers there are no user logout options.
- Verify on fresh install of v2.10.0 and with a SAML auth provider enabled, logging in and out of Rancher still works as expected.
