### ISSUE TITLE
[BUG] rancher/mirrored-calico-cni:v3.22.0 is missing in rancher-images.txt

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#38503]
**Rancher Server Setup**
- Rancher version: v2.6.7-rc6
- Installation option (Docker install/Helm Chart):any
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): rke1, 1.3.13-rc5
- Proxy/Cert Details:any

**Information about the Cluster**
- Kubernetes version:n/a
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): local 

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: n/a

**Describe the bug**
when deploying rancher in an airgap setup, the image rancher/mirrored-calico-cni:v3.22.0 is missing and therefore rancher will not come up with just this list

**To Reproduce**
provision rancher v2.6.7-rc6 in an airgap setup using helm

**Result**
rancher never starts due to the image missing

**Expected Result**
the network should start so that rancher may provision correctly

**Screenshots**
<img width="821" alt="Screen Shot 2022-08-02 at 3 09 18 PM" src="https://user-images.githubusercontent.com/16691014/182482001-295f7ce4-77fc-4245-8182-1e2d7909ab4f.png">

**Comment by sowmyav27** [comment]
The RKE Rc - v1.3.13-rc5 does not have Chris's fixes, which is why its using the older CNI images.
Technically, mirrored images has been replaced by new images which is available in images.txt file of latest Rancher RC. (2.6.7-rc6). So for this to work now, we need a new RKE RC

**Comment by slickwarren** [comment]
on rancher v2.6.7-rc7, this image is now in the `rancher-images.txt`
