### ISSUE TITLE
[BUG] Fleet bundle in error state after upgrade rancher from 2.6.6 to 2.6.7-rc5 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#38501]
**Rancher Server Setup**
- Rancher version:  from 2.6.6 to 2.6.7-rc5 
- Installation option (Docker install/Helm Chart): HA
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1 v1.23.6 
- Proxy/Cert Details: none 

**Information about the Cluster**
- Kubernetes version: RKE2 v1.23.7+rke2r2 
- Cluster Type (Local/Downstream): downstream 
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): one custom cluster, one node-driver cluster, both use AWS EC2 instance 

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Admin
  - If custom, define the set of permissions:

**Describe the bug**

After upgrading rancher from 2.6.6 to 2.6.7-rc5, some of the bundles are in the error state, as the following screen shows. 
Fleet version seen on the local and downstream cluster is `100.0.4+up0.3.10-rc5`

![screencapture-sowmaupg-qa-rancher-space-dashboard-c-local-fleet-fleet-cattle-io-bundle-2022-08-02-11_58_35](https://user-images.githubusercontent.com/6218999/182456764-d9c6e46c-f350-42a3-a78d-8ac10e4c92e3.png)

**To Reproduce**

- HA install Rancher 2.6.6
- provision some downstream clusters, rke1, rke2, node-driver, custom 
- upgrade rancher to 2.6.7-rc5 

**Result**
see the above screenshot 

**Expected Result**

All bundles should upgrade successfully. 

**Additional Info**
![screencapture-sowmaupg-qa-rancher-space-dashboard-c-c-m-lmbn99hj-apps-catalog-cattle-io-app-cattle-system-mcc-sowmya-266-upg-managed-system-upgrade-controller-2022-08-02-12_12_11](https://user-images.githubusercontent.com/6218999/182457458-9bb4b164-dce1-46b9-804c-e7b56ea6f5bc.png)
![screencapture-sowmaupg-qa-rancher-space-dashboard-c-c-m-vnqrjphd-apps-catalog-cattle-io-app-cattle-system-mcc-jiaqi-rke2-c1-managed-system-upgrade-controller-2022-08-02-12_08_13](https://user-images.githubusercontent.com/6218999/182457474-e0989e04-1271-4251-a14f-8e0fa5a7fc7e.png)

 **Note:**
This was a Rancher server where an upgrade from 2.6.6 to 2.6.7-rc5 was done. Then a restore/rollback to 2.6.6 using rancher backup restore. And then this upgrade was performed again from 2.6.6 to 2.6.7-rc5.

**Comment by izaac** [comment]
Reproduced on Rancher 2.6.7-rc6

This doesn't seem to happen with RKE1 clusters.

**Comment by manno** [comment]
Seems like something is trying to patch the deployment's label selector, but:

> In API version apps/v1, a Deployment's label selector is immutable after it gets created.

I understand this was never tested before? The setup seems complicated: upgrade rancher, rollback rancher, upgrade again, with multiple downstream clusters. Can that be simplified to reproduce the problem?

**Comment by HarrisonWAffel** [comment]
The additional label and selector for the system-upgrade-controller has been reverted (rancher/system-charts#569, rancher/charts#2008) and rancher has been updated to use the previous release of the system-upgrade-controller chart (rancher/rancher#38527, version v100.0.2+up0.3.2). The issue should no longer reproduce on the next RC. During my testing I was unable to reproduce the problem when not utilizing the backup-restore operator.

**Comment by mattfarina** [comment]
I removed this from the fleet project since this isn't related to fleet itself.

**Comment by izaac** [comment]
Rancher version: `v2.6.7-rc7`

Downstream clusters:

- **RKE2** - `v1.23.7+rke2r2`
- **k3s** - `v1.23.7+k3s1`

Upgrade from Rancher `v2.6.6` to `v2.6.7-rc7` I no longer reproduce the issue, see screenshot of bundles after upgrade:

<img width="749" alt="Screen Shot 2022-08-08 at 4 51 03 PM" src="https://user-images.githubusercontent.com/27659/183533692-5e353c4c-90e6-4816-b330-6e6f90b39b43.png">
