### ISSUE TITLE
[BUG] Cannot Provision RKE2 Cluster on 2.6-head

### ISSUE THREAD

**Issue by HarrisonWAffel** [rancher/rancher#38514]
**Rancher Server Setup**
- Rancher version: v2.6-head
- Installation option (Docker install/Helm Chart): Local IDE, should repro on docker-install as well
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details: 

**Information about the Cluster**
- Kubernetes version: v1.23.8+rke21 and v1.24.2+rke2r1
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Digital Ocean

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Admin

**Describe the bug**
I cannot provision an RKE2 Cluster. After instance creation, the system-agent reports 

```
Aug 03 15:49:03 haffel-test-pool1-05e4fb45-t5d6v rancher-system-agent[1971]: W0803 15:49:03.252401    1971 reflector.go:325] pkg/mod/github.com/rancher/client-go@v1.24.0-rancher1/tools/cache/reflector.go:168: failed to list *v1.Secret: the server has asked for the client to provide credentials (get secrets.meta.k8s.io)
Aug 03 15:49:03 haffel-test-pool1-05e4fb45-t5d6v rancher-system-agent[1971]: E0803 15:49:03.253095    1971 reflector.go:139] pkg/mod/github.com/rancher/client-go@v1.24.0-rancher1/tools/cache/reflector.go:168: Failed to watch *v1.Secret: failed to list *v1.Secret: the server has asked for the client to provide credentials (get secrets.meta.k8s.io)
```

The local rancher server continuously reports 
```
2022/08/03 12:59:18 [DEBUG] no local installation script found, moving on to url: https://raw.githubusercontent.com/rancher/system-agent/v0.2.10/install.sh
2022/08/03 12:59:18 [DEBUG] DesiredSet - No change(2) /v1, Kind=ServiceAccount fleet-default/haffel-124-test-bootstrap-template-f5ddt-machine-bootstrap for rke-machine fleet-default/haffel-124-test-bootstrap-template-f5ddt
2022/08/03 12:59:18 [DEBUG] DesiredSet - No change(2) /v1, Kind=ServiceAccount fleet-default/haffel-124-test-bootstrap-template-f5ddt-machine-plan for rke-machine fleet-default/haffel-124-test-bootstrap-template-f5ddt
2022/08/03 12:59:18 [DEBUG] DesiredSet - No change(2) /v1, Kind=Secret fleet-default/haffel-124-test-bootstrap-template-f5ddt-machine-bootstrap for rke-machine fleet-default/haffel-124-test-bootstrap-template-f5ddt
2022/08/03 12:59:18 [DEBUG] DesiredSet - No change(2) /v1, Kind=Secret fleet-default/haffel-124-test-bootstrap-template-f5ddt-machine-plan for rke-machine fleet-default/haffel-124-test-bootstrap-template-f5ddt
2022/08/03 12:59:18 [DEBUG] DesiredSet - No change(2) rbac.authorization.k8s.io/v1, Kind=Role fleet-default/haffel-124-test-bootstrap-template-f5ddt-machine-plan for rke-machine fleet-default/haffel-124-test-bootstrap-template-f5ddt
2022/08/03 12:59:18 [DEBUG] DesiredSet - No change(2) rbac.authorization.k8s.io/v1, Kind=RoleBinding fleet-default/haffel-124-test-bootstrap-template-f5ddt-machine-plan for rke-machine fleet-default/haffel-124-test-bootstrap-template-f5ddt
2022/08/03 12:59:18 [DEBUG] Extras returned map[principalid:[system://provisioning/fleet-default/haffel-124-test local://u-dlin5yx5mr] username:[]]
2022/08/03 12:59:18 [DEBUG] Triggering auth refresh on u-dlin5yx5mr
2022/08/03 12:59:18 [DEBUG] Skipping refresh for system-user u-dlin5yx5mr 
2022/08/03 12:59:18 [DEBUG] Searching for providerID for selector rke.cattle.io/machine=130d0c7a-f7b1-4441-9525-847fb75467c8 in cluster fleet-default/haffel-124-test, machine haffel-124-test-pool1-7f57497486-vqtkd: {"Code":{"Code":"Forbidden","Status":403},"Message":"clusters.management.cattle.io \"c-m-nvcfnss5\" is forbidden: User \"u-dlin5yx5mr\" cannot get resource \"clusters\" in API group \"management.cattle.io\" at the cluster scope","Cause":null,"FieldName":""} (get nodes)
```
I can also see the log 

```
fleet-default/haffel-124-test-pool1-7f57497486-vqtkd planSecret () or tokenSecretName () were empty, planSA fleet-default/haffel-124-test-bootstrap-template-f5ddt-machine-bootstrap is not ready for consumption yet
```

This may potentially be related to recent service-account changes made in preparation for k8's 1.24. This behavior began recently.

**To Reproduce**
+ Setup a rancher server on 2.6-head 
+ Create a new RKE2 cluster
   + this issue should be provider agnostic, but I tested on DigitalOcean 

**Result**
After instance creation, observe that the node stays in the `Waiting for agent to check in and apply initial plan` stage

**Expected Result**
The agent should connect and the node should complete provisioning. 

**Additional context**
After extracting the kube-config from the downstream node and attempting to use it locally, the following message is shown 
```
error: You must be logged in to the server (the server has asked for the client to provide credentials (get nodes))
```

My cluster ID for a 1.23.8+rke2r1 instance (haffel-test) is c-m-28bj4gf6, and when using the Rancher API I can see a default service-account token for the cluster with the a secret name of `default-token-k2s2s`. 

```
{
  "id": "c-m-28bj4gf6/default",
  "type": "serviceaccount",
  "links": {
    "remove": "…/v1/serviceaccounts/c-m-28bj4gf6/default",
    "self": "…/v1/serviceaccounts/c-m-28bj4gf6/default",
    "update": "…/v1/serviceaccounts/c-m-28bj4gf6/default",
    "view": "…/api/v1/namespaces/c-m-28bj4gf6/serviceaccounts/default"
  },
  "apiVersion": "v1",
  "automountServiceAccountToken": false,
  "kind": "ServiceAccount",
  "metadata": {
    "creationTimestamp": "2022-08-03T15:06:15Z",
    "fields": [
      "default",
      1,
      "107m"
    ],
    "name": "default",
    "namespace": "c-m-28bj4gf6",
    "relationships": null,
    "resourceVersion": "3674",
    "state": {
      "error": false,
      "message": "Resource is current",
      "name": "active",
      "transitioning": false
    },
    "uid": "d708d033-62b3-4eac-a0c0-30d696df7713"
  },
  "secrets": [
    {
      "name": "default-token-k2s2s"
    }
  ]
}
```

The secret pointed to by the service-account does exist and is not empty.  I can also see the following secrets for this cluster 

```
fleet-default                            haffel-test-rke-state                                              rke.cattle.io/cluster-state                   2      122m
fleet-default                            haffel-test-bootstrap-template-z2mxg-machine-bootstrap-toksbsbk    kubernetes.io/service-account-token           3      122m
fleet-default                            haffel-test-bootstrap-template-z2mxg-machine-plan-token-rg7fj      kubernetes.io/service-account-token           3      122m
fleet-default                            haffel-test-bootstrap-template-z2mxg-machine-bootstrap-token       kubernetes.io/service-account-token           3      122m
fleet-default                            haffel-test-kubeconfig                                             Opaque                                        2      122m
fleet-default                            haffel-test-bootstrap-template-z2mxg-machine-bootstrap             rke.cattle.io/bootstrap                       1      122m
fleet-default                            haffel-test-pool1-05e4fb45-t5d6v-machine-driver-secret             Opaque                                        4      122m
fleet-default                            haffel-test-pool1-05e4fb45-t5d6v-machine-provision                 Opaque                                        0      122m
fleet-default                            haffel-test-pool1-05e4fb45-t5d6v-machine-provision-token-q7cf2     kubernetes.io/service-account-token           3      122m
fleet-default                            haffel-test-pool1-05e4fb45-t5d6v-machine-state                     rke.cattle.io/machine-state                   1      122m
fleet-default                            haffel-test-bootstrap-template-z2mxg-machine-plan                  rke.cattle.io/machine-plan                    3      122m
fleet-default                            haffel-test-bootstrap-template-z2mxg-machine-plan-token            kubernetes.io/service-account-token           3      121m
```

**Comment by MbolotSuse** [comment]
Related PRs: 
- rancher/steve#56
- rancher/rancher#38534

**Comment by Josh-Diamond** [comment]
Ticket #38514 - Test Results

With Docker on a single-node instance:

Reproduced on rancher `v2.6-89fec60628df484c6a136e49ac5b49834df0b51d-head`:
1. Fresh install of rancher `v2.6-head`
2. Provision a downstream AWS Node driver RKE2 cluster w/ k8s 1.23.8
3. Provision a downstream AWS Node driver RKE2 cluster w/ k8s 1.24.2
4. Reproduced - Clusters fail to provision; stuck `waiting for agent to check in and apply initial plan`

Screenshot:

`Step 4`
<img width="1626" alt="Screen Shot 2022-08-08 at 10 08 58 AM" src="https://user-images.githubusercontent.com/46494969/183474821-66f60c1c-f613-4347-8925-b3759c6b468f.png">

---

Verified on rancher `v2.6-e9e88db363ae369bec044372cae8a36c66c042c9-head`:
1. Fresh install of rancher `v2.6-head`
6. Provision a downstream AWS Node driver RKE2 cluster w/ k8s 1.23.8
7. Provision a downstream AWS Node driver RKE2 cluster w/ k8s 1.24.2
8. Verified - RKE2 clusters successfully provision

Screenshot:

`Step 4`
<img width="1628" alt="Screen Shot 2022-08-08 at 8 53 47 AM" src="https://user-images.githubusercontent.com/46494969/183463206-57b1166e-8679-4bbd-abff-2b2d02887d34.png">

**Comment by Josh-Diamond** [comment]
Re-opening for further validation

**Comment by Josh-Diamond** [comment]
Ticket #38514 - Test Results [pt. 2]

With Docker on a single-node instance:

Verified on rancher `v2.6-cd97f6fd1e894dd8677efa2fa87c57d7c7a68d54-head`:
1. Fresh install of rancher `v2.6-head`
2. Deploy downstream RKE2 and k3s k8s v1.23.8 and v1.24.2 clusters - [4 clusters in total]
3. Verified - All clusters successfully provision and functional

Screenshot:

`Step 3`
<img width="1405" alt="Screen Shot 2022-08-08 at 4 39 52 PM" src="https://user-images.githubusercontent.com/46494969/183533048-e92281bc-2226-463e-992c-39ae4b2ef81b.png">

**Comment by izaac** [comment]
Rancher version `v2.6.7-rc7`

Fleet Continuous Delivery coverage:

- Executed the P0 scenarios on k3s, RKE2 and RKE1 clusters
- Validated the scenarios passed

Fleet provisioning coverage

- Upgrade k8s versions of k3s/rke2 clusters passed. 1.23 to 1.24

**Comment by Josh-Diamond** [comment]
Further QA validation checks have been considered, tested and passed - closing issue
