### ISSUE TITLE
[BUG] Logging rke2 operators go in crashloop when upgrading to 3.17.7

### ISSUE THREAD

**Issue by ronhorton** [rancher/rancher#38519]
**Rancher Server Setup**
- Rancher version: `2.6.7-rc6`
- Installation option (Docker install/Helm Chart): `HELM`
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): `RKE2`
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: `v1.23.7`
- Cluster Type (Local/Downstream): `Downstream Imported AWS RKE2 cluster`
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: `admin`

**Describe the bug**
After upgrading rancher from 2.6.6. to 2.6.7-rc6, I upgraded logging to 3.17.7; The rancher-logging app on the installed apps page shows a `FAILED` tag. the rancher-logging-rke2-journalId-aggregators are in `crashloop`

**To Reproduce**
1. Install previous version of logging in rke2 cluster
2. configure cluster output
3. configure cluster flow
4. verify that logs are flowing to output (eg, elasticsearch)
5. upgrade logging to latest 100.1.3-up3.17.7 [pointed charts repo to dev-2.6]

**Result**
Upgrade fails; rke2 logging aggregator pods in crashloop. 

**Expected Result**
Upgrade succeeds and logs resume flowing to elasticsearch. 

**Screenshots**

<img width="1628" alt="2022-08-03_17-49-00" src="https://user-images.githubusercontent.com/89212856/182718992-1bafa027-6503-4f8f-94a6-a2e4d48d84ce.png">
<img width="1355" alt="2022-08-03_17-49-37" src="https://user-images.githubusercontent.com/89212856/182719043-72cbd655-718e-4ea2-bcd7-7bfd215927ae.png">

<img width="1415" alt="2022-08-03_17-51-17" src="https://user-images.githubusercontent.com/89212856/182719070-da44ff1b-aa5f-4fc0-a921-6c2db43dd5a8.png">

**Additional context**
`
logs from [rancher-logging-rke2-journald-aggregator-2vw5g]
-- | --
Wed, Aug 3 2022 5:42:32 pm | Fluent Bit v1.9.3
Wed, Aug 3 2022 5:42:32 pm | * Copyright (C) 2015-2022 The Fluent Bit Authors
Wed, Aug 3 2022 5:42:32 pm | * Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
Wed, Aug 3 2022 5:42:32 pm | * https://fluentbit.io
Wed, Aug 3 2022 5:42:32 pm |  
Wed, Aug 3 2022 5:42:32 pm | [2022/08/03 21:42:32] [ info] [fluent bit] version=1.9.3, commit=9eb4996b7d, pid=1
Wed, Aug 3 2022 5:42:32 pm | [2022/08/03 21:42:32] [ info] [storage] version=1.2.0, type=memory-only, sync=normal, checksum=disabled, max_chunks_up=128
Wed, Aug 3 2022 5:42:32 pm | [2022/08/03 21:42:32] [ info] [cmetrics] version=0.3.1
Wed, Aug 3 2022 5:42:32 pm | [2022/08/03 21:42:32] [error] [input:systemd:systemd.0] could not open the Journal
Wed, Aug 3 2022 5:42:32 pm | [2022/08/03 21:42:32] [error] [input:systemd:systemd.0] cannot initialize
Wed, Aug 3 2022 5:42:32 pm | [2022/08/03 21:42:32] [error] Failed initialize input systemd.0
Wed, Aug 3 2022 5:42:32 pm | [2022/08/03 21:42:32] [error] [lib] backend failed`

**Comment by eliyamlevy** [comment]
Issue resolved by checking that `global` -> `seLinux` -> `enabled` is set to `true`. Upon upgrading the chart the value was reset to `false` causing a permission error with the aggregator when it was trying to access a privileged directory.

**Comment by nickwsuse** [comment]
I was able to confirm that re-enabling seLinux did indeed fix the issue. I made a new dashboard ticket to address the issue of it being disabled in the first place: https://github.com/rancher/dashboard/issues/6629
