### ISSUE TITLE
Rancher Cleanup Scripts Not Removing a Large Number of Rancher Resources After Upgrade from 2.6.6 to 2.6.7-rc5

### ISSUE THREAD

**Issue by nickwsuse** [rancher/rancher#38516]
**Rancher Server Setup**
- Rancher version: 2.6.7-rc5
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1 v1.3.11
- Proxy/Cert Details: byo-valid

**Information about the Cluster**
- Kubernetes version: v1.23.6-rancher1-1
- Cluster Type (Local/Downstream): Local

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): Admin

**Describe the bug**
After performing an upgrade from Rancher version 2.6.6 to 2.6.7-rc5, when running the cleanup script to perform a rollback the script leaves behind a large amount of Rancher resources. 

**To Reproduce**
1. Deploy an HA cluster on Rancher v2.6.6
2. Log into HA cluster
3. Click the hamburger menu in the upper left of the page
4. Click the local cluster
5. In the left side menu, select Storage > Secrets
6. Create an Opaque secret with your AWS access keys
7. Go to Apps > Search for backup > Install Rancher Backups v2.1.2
8. Configure the default storage location to an AWS S3 bucket
9. Create a few resources such as users, roles, templates
10. Create a downstream EC2 cluster with three nodes with all roles
11. Go back to your local cluster > Rancher Backup > Backup
12. Create a backup
13. Perform an upgrade to 2.6.7-rc5
14. Log in to the control plane node of the HA1 cluster
15. Install kubectl client on the control plane
16. Get the kubeconfig file of the local cluster
17. export KUBECONFIG=<kubeconfig.yaml>
18. Follow instructions at https://github.com/rancher/rancher-cleanup
19. Verify the cleanup is successful - kubectl -n kube-system logs -l job-name=verify-job -f -

**Result**
A large amount of Rancher resources are still present after the cleanup script finishes

**Expected Result**
No Rancher resources remain after the cleanup script finishes

**Screenshots**
Cleanup Job Complete:
![job_complete](https://user-images.githubusercontent.com/107147272/182685573-9a932040-b463-4438-99ae-f322b6da98f9.png)

Cleanup Job Logs:
![cleanup_logs](https://user-images.githubusercontent.com/107147272/182685779-269b7d69-ad72-4989-8600-46059d78a4fd.png)

Verify Script Logs:
![verify_script_results](https://user-images.githubusercontent.com/107147272/182685849-1b9bc7c7-1591-4482-ae99-14e2a2cd0b3b.png)

**Comment by MKlimuszka** [comment]
SURE-5349

**Comment by eliyamlevy** [comment]
Tagging some issues that seem related.
[The cleanup script doesn't remove finalizers from namespaces](https://github.com/rancher/rancher-cleanup/issues/5)
[Running for hours but nothing seems to be deleted](https://github.com/rancher/rancher-cleanup/issues/3)

**Comment by eliyamlevy** [comment]
Tested on both v2.6-head and v2.7-head rancher clusters and was verified to work as expected. The issue was caused by running the shell script directly on the control node instead of creating the kubernetes job allowing it to run across the whole cluster.

Since this is a non-issue I recommend just closing the issue. If it comes back again we can do further testing, but it was not reproducible on either version.
