### ISSUE TITLE
[BUG] When logged into the Rancher CLI as a standard user, you are unable to view an admin user's name when running `rancher clusters list-members`

### ISSUE THREAD

**Issue by markusewalker** [rancher/rancher#38512]
**Rancher Server Setup**
- Rancher CLI version: `v2.6.7-rc1`
- Installation option (Docker install/Helm Chart): CLI
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): N/A
- Proxy/Cert Details: N/A

**Information about the Cluster**
- Kubernetes version: N/A
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): AWS

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Standard
  - If custom, define the set of permissions:

**Describe the bug**

When logged into the Rancher CLI as a standard user, when I attempt to view the members of a provisioned downstream cluster created from Rancher, I am unable to see the administrator's name under the `USER` column. See below:

```
$ rancher clusters list-members
BINDING-ID                      USER       ROLE            CREATED
c-j5rj4:creator-cluster-owner              cluster-owner   03 Aug 2022 15:39:06 UTC
c-j5rj4:crtb-6r5rz              standard   cluster-owner   03 Aug 2022 15:49:15 UTC
c-j5rj4:crtb-gf8bc                         cluster-owner   03 Aug 2022 16:01:55 UTC
```
However, when you log out as log back in as an administrator user, you're able to properly see all the members in the same cluster:

```
$ rancher clusters list-members
BINDING-ID                      USER            ROLE            CREATED
c-j5rj4:creator-cluster-owner   Default Admin   cluster-owner   03 Aug 2022 15:39:06 UTC
c-j5rj4:crtb-6r5rz              standard        cluster-owner   03 Aug 2022 15:49:15 UTC
c-j5rj4:crtb-gf8bc              testadmin       cluster-owner   03 Aug 2022 16:01:55 UTC
```

**To Reproduce**

1. Setup Rancher and navigate to the UI in a browser.
2. Create a standard user and login to Rancher as that user.
3. Provision a downstream RKE1 (or RKE2) node driver cluster.
4. On a client machine, download the Rancher CLI, version `v2.6.7-rc1`.
5. Run `rancher login` and log in as the standard user first. Be sure to login to the cluster that the standard user provisioned.
6. Run `rancher clusters list-members`. From there, you should see only the standard user displayed as shown above.
7. Run `rancher server delete` and delete current server login.
8. Log back in with `rancher login`, but this time as an administrative user.
9. Re-run `rancher clusters list-members` and you should see that all of the users are properly displayed, as expected.

**Result**
Standard users are unable to view administrative users in a cluster.

**Expected Result**

Standard users should be able to view administrative users in a cluster.

**Comment by HarrisonWAffel** [comment]
It should be noted that I could not reproduce this issue without including an additional step of adding an admin as a cluster-member after/before creation.

This behavior is due to the permissions that a standard user has by default. The CLI will query the `v3/clusterroletemplatebindings` API and receive all role-template-bindings for users who have access to that cluster. However, when the CLI queries `v3/users` using a standard-users API token, it will not be able to see admin users by design. This is why we see an entry, but no user-name. However, It is possible to see a cluster-member who is an admin within the UI. It is likely that the UI is using an API call that the CLI is not.

**Comment by annablender** [comment]
The standard user does not have `Viewing` role binding and it is expected behavior that when you are logged in as a standard user, the CLI won't display the admin user name. This can be closed.

**Comment by markusewalker** [comment]
@annablender that makes sense to me, thanks for the explanation. Seems this is CLI-specific and the behavior is as designed. With that in mind then, I'll close this.
