### ISSUE TITLE
CIS	rke2-cis-1.5-profile-permissive scan results in 1 failure on downstream rke2 RHEL cluster

### ISSUE THREAD

**Issue by AndrewHoffmanQA** [rancher/rancher#38510]
**Setup**
- Rancher version: v2.6.7-rc6
- rhel 8.6 - ami-053835e36b16f97d0
- rke1 1.23.6
- hardened

**downstream cluster**
rke2
Kubernetes Version: v1.23.7
3 workers 1 etcd 1 cp
custom cluster
rhel 8.6; ami-053835e36b16f97d0

CIS chart 2.0.5-rc6

**Describe the bug**
as an admin when I install CIS Benchmark (2.0.4) and run a 1.6 permissive scan against the cluster, 1 failure is thrown
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/DREWHO~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/DREWHO~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

id | description | remediation | state
-- | -- | -- | --
5.7.4 | The default namespace should not be used (Scored) | Ensure that namespaces are created   to allow for appropriate segregation of Kubernetes     resources and that all new resources are created in a specific   namespace. | fail

</body>

</html>

**To Reproduce**
1. create rancher local HA
2. create downstream custom cluster
3. install helm chart CIS Benchmark (2.0.5-rc6) 
4. Locate and click on CIS benchmark chart. (2.0.5-rc6)
5. Click install (top right)
6. In ‘install into project’ dropdown select system.
7 Click install
8 Click install a second time
9 On the side menu, ‘CIS benchmark’ dropdown should now be available. (refresh page if not)
10 Click the ‘CIS benchmark’ dropdown, select scans
11 Click create
12I n ‘profile dropdown’ select rke2-cis-1.5-profile-permissive 

**Result**
the scan runs and returns the failure documented above.

**Expected Result**
no failures are displayed 

**Screenshots**
![image](https://user-images.githubusercontent.com/89030218/182647464-ee92d1e1-6187-4a60-981f-17593fdbdb36.png)

**Additional context**

this was also reproduced in an older build 

**Setup**
- Rancher version: 2.6.6
- rhel 8.6 - ami-053835e36b16f97d0
- rke1 v1.3.11
- hardened

**downstream cluster**
- rke2
- Kubernetes Version: v1.23.6
- 3 workers 1 etcd 1 cp
- custom cluster
- rhel 8.6; ami-053835e36b16f97d0

**Detailed Description**

**Context**

**Comment by AndrewHoffmanQA** [comment]
this can also be reproduced in 

rancher
v2.6.7-rc6

Setup

Rancher version: 2.6.6
rhel 8.6 - ami-053835e36b16f97d0
rke1 v1.3.11
hardened
downstream cluster
rke2
Kubernetes Version: v1.23.6
3 workers 1 etcd 1 cp
custom cluster
rhel 8.6; ami-053835e36b16f97d0

CIS chart - 2.0.5-rc6

**Comment by mitulshah-suse** [comment]
We have deprecated 1.5 scan profiles as part of https://github.com/rancher/rancher/issues/38668
1.5 scans are meant to be run only on kubernetes version 1.15 as per the CIS benchmark, which is not in use anywhere on rancher.
@AndrewHoffmanQA Please confirm if this can be closed.

**Comment by mitulshah-suse** [comment]
@prachidamle @AndrewHoffmanQA Can this be closed?

**Comment by AndrewHoffmanQA** [comment]
per the deprecation of 1.5 scans this should be closed. moving to done.
