### ISSUE TITLE
Rancher 2.6.head - CIS permissive chart 1.6 runs result in 9 failures on downstream Rhel rke1 clusters

### ISSUE THREAD

**Issue by AndrewHoffmanQA** [rancher/rancher#38511]
**Setup**
- Rancher version: 2.6.6
- rhel 8.6 - ami-053835e36b16f97d0
- rke1 v1.3.11
- hardened

**downstream cluster**
- rke1
- Kubernetes Version: v1.20.15-rancher 1-4
- 3 workers 1 etcd 1 cp
- custom cluster
- rhel 8.6; ami-053835e36b16f97d0

**Describe the bug**
as an admin when I install CIS Benchmark (2.0.4) and run a 1.6 permissive scan against the cluster, 9 failures are found. 

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/DREWHO~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/DREWHO~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

id | description | remediation | state
-- | -- | -- | --
1.1.11 | Ensure that the etcd data directory permissions are set to 700 or more   restrictive (Automated) | On the etcd server node, get the   etcd data directory, passed as an argument --data-dir,     from the below command:     ps -ef \| grep etcd Run the below command (based on the etcd data directory   found above). For example,     chmod 700 /var/lib/etcd | mixed
1.1.12 | Ensure that the etcd data directory ownership is set to etcd:etcd   (Automated) | On the etcd server node, get the   etcd data directory, passed as an argument --data-dir,     from the below command:     ps -ef \| grep etcd     Run the below command (based on the etcd data directory found above).     For example, chown etcd:etcd /var/lib/etcd          A system service account is required for etcd data directory   ownership.     Refer to Rancher's hardening guide for more details on how to configure   this ownership. | mixed
2.1 | Ensure that the --cert-file and --key-file arguments are set as   appropriate (Automated) | Follow the etcd service   documentation and configure TLS encryption.     Then, edit the etcd pod specification file   /etc/kubernetes/manifests/etcd.yaml     on the master node and set the below parameters.     --cert-file=</path/to/ca-file>     --key-file=</path/to/key-file> | mixed
2.2 | Ensure that the --client-cert-auth argument is set to true (Automated) | Edit the etcd pod specification   file $etcdconf on the master     node and set the below parameter.     --client-cert-auth="true" | mixed
2.3 | Ensure that the --auto-tls argument is not set to true (Automated) | Edit the etcd pod specification   file $etcdconf on the master     node and either remove the --auto-tls parameter or set it to false.       --auto-tls=false | mixed
2.4 | Ensure that the --peer-cert-file and --peer-key-file arguments are set as   appropriate (Automated) | Follow the etcd service   documentation and configure peer TLS encryption as appropriate     for your etcd cluster.     Then, edit the etcd pod specification file $etcdconf on the     master node and set the below parameters.     --peer-client-file=</path/to/peer-cert-file>     --peer-key-file=</path/to/peer-key-file> | mixed
2.5 | Ensure that the --peer-client-cert-auth argument is set to true   (Automated) | Edit the etcd pod specification   file $etcdconf on the master     node and set the below parameter.     --peer-client-cert-auth=true | mixed
2.6 | Ensure that the --peer-auto-tls argument is not set to true (Automated) | Edit the etcd pod specification   file $etcdconf on the master     node and either remove the --peer-auto-tls parameter or set it to   false.     --peer-auto-tls=false | mixed
2.7 | Ensure that a unique Certificate Authority is used for etcd (Automated) | [Manual test]     Follow the etcd documentation and create a dedicated certificate authority   setup for the     etcd service.     Then, edit the etcd pod specification file $etcdconf on the     master node and set the below parameter.     --trusted-ca-file=</path/to/ca-file> | mixed

</body>

</html>

**To Reproduce**
1. create rancher local HA
2. create downstream custom cluster
3. install helm chart CIS Benchmark (2.0.4) 
4. Locate and click on CIS benchmark chart. (2.0.4)
5. Click install (top right)
6. In ‘install into project’ dropdown select system.
7 Click install
8 Click install a second time
9 On the side menu, ‘CIS benchmark’ dropdown should now be available. (refresh page if not)
10 Click the ‘CIS benchmark’ dropdown, select scans
11 Click create
12I n ‘profile dropdown’ select permissive chart 1.6
13 Click create

**Result**
the scan runs and returns the failures documented above.

**Expected Result**
no failures are displayed 

**Screenshots**
![image](https://user-images.githubusercontent.com/89030218/182638434-f0f95429-860e-40a3-89d2-8f5b3ddeb71f.png)

**Additional context**

this was also reproduced in a similar DS cluster, minorly different k8 

rke1
Kubernetes Version: v1.23.7-rancher 1-1
3 workers 1 etcd 1 cp
custom cluster
rhel 8.6; ami-053835e36b16f97d0

**Detailed Description**

**Context**

**Comment by mitulshah-suse** [comment]
@AndrewHoffmanQA 
1.6 scan profiles are supposed to run on kubernetes 1.16-1.18 as per CIS benchmark guidelines.

Also, seems like these issues are fixed in chart 2.1.0, but the chart is only available in kubernetes version 1.21 and above. I tried running a 1.6 scan on K8s version 1.21 and it passed without errors.
So do we want to push the same fixes in the older charts and release them again?

**Comment by prachidamle** [comment]
@AndrewHoffmanQA Can we test if the CIS 1.6 scan profiles pass when using the supported kubernetes 1.16-1.18 for the downstream rke1 clusters? 

@mitulshah-suse do we have it documented/indicated anywhere that  for CIS benchmark 1.6, supported range is  kubernetes 1.16-1.18?

**Comment by mitulshah-suse** [comment]
Attached the benchmark document where it it mentioned (Page 10).

[CIS_Kubernetes_Benchmark_v1.6.0.pdf](https://zube.io/files/rancher/7c78de7538996f4d9d2dc12b6ec75c6c-cis_kubernetes_benchmark_v1-6-0.pdf)

**Comment by prachidamle** [comment]
Thanks @mitulshah-suse, I meant if we have it documented in any of the Rancher docs or the hardening guides? If not we should add the supported versions to the hardening guides. 

I have added a docs ticket https://github.com/rancher/docs/issues/4301 to update this, could you please add a PR to update these? cc check with @btat or @jtravee for any info about docs PR

**Comment by mitulshah-suse** [comment]
@prachidamle @AndrewHoffmanQA Can this be closed?

**Comment by bmdepesa** [comment]
Moving this to 2.7.0 because there's no code change and just a QA validation required, and we are past code freeze date.

**Comment by AndrewHoffmanQA** [comment]
per the [support ](https://github.com/aquasecurity/kube-bench/blob/main/docs/platforms.md#cis-kubernetes-benchmark-support) matrix 1.6 scan isnt compatible with 1.20k8. 

to retest I stood up a rancher (2.6.6) old enough to support 1.20 rhel and ran the appropriate CIS 1.20 permissive scan which passed. closing this ticket.
