### ISSUE TITLE
[RFE] Why not clear the cluster completely when remove the cluster

### ISSUE THREAD

**Issue by 631068264** [rancher/rancher#38545]
I want to know that why rancher can not clear the node completely because I find some containers still running after xxx-cleanup completed ，when remove the cluster it created.

And what will xxx-cleanup do when remove the cluster

**Comment by yankees5963** [comment]
I remember seeing a bug ticket where clearing nodes got hung somewhere and ranchers solution was to just have the UI say it was removed, but as you can see doesn't fully clean the node.
