### ISSUE TITLE
[BUG] NeuVector: `cache.syncCheck: Detected sync error` errors seen in the controller pod of Neuvector on RKE2 clusters 

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#38544]
Information about the Cluster
**Rancher Server Setup**
- Rancher version: `v2.6.7-rc6`
- Installation option (Docker install/Helm Chart): `Helm Chart`
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): `RKE1`, `v1.24.2 `, `v1.3.13-rc6`
- Proxy/Cert Details: `Self-signed`

**Information about the Cluster**
- Kubernetes version: `v1.24.2`
- Cluster Type (Local/Downstream): `Downstream Custom  3 worker, 1 etcd, 1 cp RKE2 hardened`

**Describe the bug**
When we install neuvector app on an RKE2 hardened cluster, few errors are seen in the controller pod of the neuvector app.

**To Reproduce**
1. Created an RKE2 hardened custom cluster with the spec mentioned above
2. From apps & market place >> Install neuvector chart version `100.0.1+up2.2.2`
3. In the edit options page, navigate to `other configurations` page and select `Pod security Policy` check box
4. Provide the value 1 for Manager runAsUser ID, Scanner  runAsUser ID and Updater runAsUser ID
5. App deploys 
6. Navigate to deployments page >> Select `cattle-neuvector-system` in the namespace picker
7. View the controller pod logs

**Result**
Following errors are seen in all of the controller pods:
```
2022-08-08T07:39:38.606|ERRO|CTL|cache.syncCheck: Detected sync error - ss=GraphNodeCount:22 LearnedRuleMax:10009 Mismatches:<ClusterRule:<ID:10009 From:"Workload:10.42.237.128" To:"nv.rke2-metrics-server.kube-system" Ports:"any" Applications:1002 CreatedTS:1659943837 LastModTS:1659943837 > LearnedRule:<ID:10009 From:"nv.fleet-agent.cattle-fleet-system" To:"external" Ports:"any" Applications:1002 CreatedTS:-62135596800 LastModTS:-62135596800 > >
```

**Expected Result**
Above errors not expected.

Additional Info: Seen on non hardened RKE2 clusters as well
Not seen on NeuVector chart versions `100.0.0+up2.2.0`
Found while validating: https://github.com/rancher/rancher/issues/37799

**Comment by garyduan** [comment]
This is normal and can happen in the behavior learning process. 3 controllers will resolve the differences automatically.

**Comment by anupama2501** [comment]
Since this is expected, closing as per the above comment.
