### ISSUE TITLE
[BUG] Unable to view cluster's YAML when logged in as a non-administrative user

### ISSUE THREAD

**Issue by markusewalker** [rancher/rancher#38555]
**Rancher Server Setup**
- Rancher version: `v2.6-head` https://github.com/rancher/rancher/commit/cd97f6fd1e894dd8677efa2fa87c57d7c7a68d54
- Installation option (Docker install/Helm Chart): Docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version:
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Imported

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Project Member
  - If custom, define the set of permissions:

**Describe the bug**

There has been a regression found in `v2.6-head` https://github.com/rancher/rancher/commit/cd97f6fd1e894dd8677efa2fa87c57d7c7a68d54, pertaining to viewing a cluster's YAML. Specifically, only an administrative user is able to go to Cluster Management and view the YAML of the specified cluster. If you are any other user, including a standard user that is the Cluster Owner, you are redirected to the login page. When you attempt to log back in, you are once again redirected to login and this happens indefinitely.

I also tested creating a cluster as the standard user. This way, the standard user would be the Cluster Owner. HOWEVER, even when doing that, I couldn't view the YAML and I get redirected to the login page....

Only by logging into Rancher as an administrative user, are you then able to properly view the YAML of the cluster. This has been verified to NOT occur in `v2.6.6`, so this is a regression that needs to be addressed.

**To Reproduce**

1. On a separate client machine that did not install Rancher, provision an RKE2 cluster (I used `v1.23.9+rke2r2`).
2. Setup Rancher and navigate to the UI in a browser.
3. Create a standard user.
4. Navigate to Cluster Management and import the above provisioned RKE2 cluster.
5. Once provisioned, navigate to Cluster Explorer > cluster > Projects/Namespaces. 
6. Create a project and add the standard user as a `Member`.
7. Log out and log back in as this standard user; verify you can see the cluster.
8. In Cluster Management, click the ellipses in the cluster's row and click `View YAML`; you will be redirected to the login screen.
     - Additionally, this also happens for `Download YAML`.

**Result**
You are looped in an indefinite cycle to login instead of being able to view the cluster's YAML.

**Expected Result**
I should be able to view the cluster's YAML without being redirected to the login screen.

**Comment by sowmyav27** [comment]
Will need a backport to 2.5

**Comment by hazim1093** [comment]
We face the same issue when viewing or editing "cluster config" and even when trying to import the cluster from UI (https://github.com/rancher/rancher/issues/36946) since we restored rancher from a velero backup

We have seen this issue on v2.6.0, v2.6.3, v2.6.4 and even v2.6.6

**Comment by markusewalker** [comment]
Verified that this has been addressed on `v2.6-head` https://github.com/rancher/rancher/commit/9670628a4813d43a8410fe27c745c79a4b566c3a.

**ENVIRONMENT DETAILS**
- Rancher Install: Docker
- Rancher Version: `v2.6-head` https://github.com/rancher/rancher/commit/9670628a4813d43a8410fe27c745c79a4b566c3a
- Browser: Chrome

**TEST RESULT**
PASS

**VERIFICATION STEPS**
1. On two separate client machines that did not install Rancher, provisioned an RKE2 cluster (`v1.23.9+rke2r2`) and an RKE1 cluster (`v1.23.7`).
2. Setup Rancher and navigate to the UI in a browser.
3. Created a standard user.
4. Navigated to Cluster Management and import the above provisioned RKE2 cluster.
5. Once provisioned, navigated to Cluster Explorer > cluster > Projects/Namespaces. 
6. Created a project and added the standard user as a `Member` to both the RKE1 and RKE2 clusters.
7. Log out and logged back in as this standard user; verified that I see both clusters:
![image](https://user-images.githubusercontent.com/52591819/183983352-908cdfac-57bb-414f-9036-15a2da62432b.png)
9. In Cluster Management, clicked the ellipses in the cluster's row and clicked `View YAML`; verified the standard user can view the cluster's YAML.
10. Clicked `Download YAML`; verified the standard user can download both of the cluster's YAML files:
![Aug-10-2022 10-59-46](https://user-images.githubusercontent.com/52591819/183984037-6693ddfc-5595-4f4a-b0b8-d604a211e204.gif)
