### ISSUE TITLE
[RFE] Updating the Rancher server helm chart publishing to publish into the new repo for builds

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#38551]
This should be as simple as updating this area: https://github.com/rancher/rancher/blob/release/v2.6/.drone.yml#L1218-L1251

Though, do we know if there will be latest/stable/alpha repos ? 

SURE-4939
blocked by SURE-4938

**Comment by jiaqiluo** [comment]
removing the dev-validate label, we do need QA to validate the issue.

**Comment by slickwarren** [comment]
using rancher v2.7.0-rc3, I was able to use both helm and docker to install rancher from a non-docker registry. there are unrelated problems that I encountered that will not block this ticket, but will block others:
* branding was missing from rancher when using this image
* many images were missing, meaning that rancher was not very usable when only using the non-docker registry

The following were validated as part of this ticket:
* rancher has the non-docker registry set as default for system-default-registry when deployed from the non-docker image/helm repo
