### ISSUE TITLE
CSP Adapter - Support for new Product ID

### ISSUE THREAD

**Issue by MbolotSuse** [rancher/rancher#38552]
## Background

There are currently planned to be two product listings that the CSP adapter will need to integrate with. One will be available in America, and another for the rest of the world. In the current state, the CSP adapter only supports one listing (the one planned to be available for america).

The new listing will have a new product ID since it is technically being produced by a separate entity. 

## New Functionality
- The adapter should also be able to receive licenses for the non-america product id `d3ca94f5-fb96-44c1-a094-415fc0463605`
- The adapter should prefer the america product id - so the non-america product id should be a fallback use case

**Comment by brudnak** [comment]
<table>
    <tbody>
        <tr>
            <th>Test</th>
            <th>Steps</th>
            <th>Expected</th>
            <th>Actual</th>
            <th>Pass/Fail</th>
        </tr>
        <tr>
            <td>EU Product ID tests</td>
            <td>See internal test plan</td>
            <td>See internal test plan</td>
            <td>See internal test plan</td>
            <td>:white_check_mark: PASS</td>
        </tr>
        <tr>
            <td>USA Product ID tests</td>
            <td>See internal test plan</td>
            <td>See internal test plan</td>
            <td>See internal test plan</td>
            <td>:white_check_mark: PASS</td>
        </tr>
    </tbody>
</table>
