### ISSUE TITLE
[RFE] Dashboard UI request for detecting feature flag

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#38554]
SURE-5023

**Comment by samjustus** [comment]
#38445

**Comment by samjustus** [comment]
moving to QA

**Comment by brudnak** [comment]
# ✅ PASSED

## Reproduction Environment

#### Not required.

<hr>

## Validation Environment

| Component                        | Version / Type                           |
|----------------------------------|------------------------------------------|
| Rancher version                  | v2.7.0-rc3                               |
| Installation option              | Helm (high availability)                 |
| If Helm Chart k8s cluster        | v1.24.6+k3s1                             |
| Cert Details                     | Let's Encrypt / `traefik`                |
| k3s ha external db               | Aurora MySQL 5.7.mysql_aurora.2.10.2     |
| Helm version                     | v2.16.8-rancher2                         |
| Downstream cluster type          | RKE1 Linode                              |
| Downstream K8s version           | v1.24.6                                  |
| Authentication providers enabled | local                                    |
| Logged in user role              | Administrator                            |
| Browser type                     | Google Chrome                            |
| Browser version                  | 105.0.5195.125 (Official Build) (x86_64) |


## Validation steps

1. With a Rancher server that's already setup
2. Using postman or hoppscotch with no authentication
3. Make a `GET` request to `https://<rancher-server>/rancherversion`
4. Received the following response

```json
{
  "Version": "v2.7.0-rc3",
  "GitCommit": "314e690a1",
  "RancherPrime": "false"
}
```

## Additional Info

## RESULTS

#### ✅ Expected
Expected to get the response noted above when hitting the `/rancherversion` endpoint while unauthenticated

#### ✅ Actual
Received the expected response while unauthenticated

## Additional Checks

# Test Plan

<table>
    <tbody>
        <tr>
            <th>Test</th>
            <th>Steps</th>
            <th>Expected</th>
            <th>Actual & Pass/Fail</th>
        </tr>
        <tr>
            <td>Upgrade from 2.6.7 Rancher</td>
            <td>
                <ol>
                    <li>Starting with a 2.6.7 Rancher</li>
                    <li>Upgrade Rancher to 2.7.0-rc3</li>
                    <li>Check the <code>/rancherversion</code> endpoint</li>
                </ol>
            </td>
            <td>Expected: Receive the expected json response</td>
            <td>Actual: <br><br>Pass/Fail: ✅<code>PASS</code></td>
        </tr>
        <tr>
            <td>Hitting the endpoint on a 2.7-head version of Rancher</td>
            <td>
                <ol>
                    <li>Setup a Rancher server that's using v2.7-head as the version</li>
                    <li>Make a <code>GET</code> request to the <code>/rancherversion</code> endpoint</li>
                </ol>
            </td>
            <td>Expected: Receive the git commit as the version</td>
            <td>Actual: Received the version as the git commit<br><br>Pass/Fail: ✅<code>PASS</code>--></td>
        </tr>
        <tr>
            <td>Set RANCHER_PRIME env to true</td>
            <td>
                <ol>
                    <li>Create a v2.7-0-rc3 rancher server</li>
                    <li>Set an env var of RANCHER_PRIME with the key true</li>
                    <li>Check the rancher version endpoint</li>
                </ol>
            </td>
            <td>Expected: For the endpoint response to reflect rancher prime env as true if set as such</td>
            <td>Actual: JSON response shows rancher prime env set to true<br><br>Pass/Fail: ✅<code>PASS</code></td>
        </tr>
    </tbody>
</table>
