### ISSUE TITLE
[BUG]  UI is accessible but websocket is returning 404 error

### ISSUE THREAD

**Issue by dpzx** [rancher/rancher#38584]
**Rancher Server Setup**
- Rancher version: **v2.6.7-rc9**
- Installation option (Docker install/Helm Chart): **Helm Chart**
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): **v1.24.2+k3s2**
- Proxy/Cert Details: **rancher/cert-manager**

**Information about the Cluster**
- Kubernetes version: **v1.24.2**
- Cluster Type (Local/Downstream): **Local**

**User Information**
- What is the role of the user logged in? **Admin/Cluster** 

**Describe the bug**
The deployment is successful and we are able to reach the ui but in the browser console we get 404 when rancher tries to establish any websocket connections:
    * /v3/subscribe
    * /k8s/clusters/local/v1/subscribe

**To Reproduce**
Install rancher helm chart version v2.6.7-rc9 with k3s + kubernetes v1.24.2:

**Result**
Websocket connections failed with 404

**Expected Result**
Successfully establish websocket connects

**Screenshots**

**Additional context**
We are able to connect to the websocket inside the rancher pod with curl cmd.
The logs for the pod does not print anything helpful for debugging this issue.
We have the following setup in our environment and made sure to add the headers to upgrade the connection with nginx :

nginx -> traefik ingress controller -> pod

**Comment by dpzx** [comment]
It was an nginx misconfiguration.

**Comment by jbpoint** [comment]
Can you please describe what did you do to solve the issue?

**Comment by jbpoint** [comment]
> It was an nginx misconfiguration.

Can you please describe what did you do to solve the issue?
