### ISSUE TITLE
[2.5] Unable to view cluster's YAML when logged in as a non-administrative user

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#38581]
backport of rancher/rancher#38555

**Comment by markusewalker** [comment]
@sowmyav27 for QA responsible for owning this ticket in my absence, please find the test plan that I have laid out in this comment. Feel free to add anything to it.

**TEST PLAN**
1. On two separate client machines that did not install Rancher, provision an RKE2 cluster (`v1.23.9+rke2r2`) and an RKE1 cluster (`v1.23.7`).
2. Setup Rancher and navigate to the UI in a browser.
3. Creat a standard user.
4. Navigate to Cluster Management and import the above provisioned clusters.
5. Once provisioned, navigate to Cluster Explorer > cluster > Projects/Namespaces. 
6. Creat a project and add the standard user as a `Member` to both the RKE1 and RKE2 clusters.
7. Log out and log back in as this standard user; verify that you see both clusters `Active`.
9. In Cluster Management, click the ellipses in the cluster's row and click `View YAML`; verify that the standard user can see the cluster's YAML.
10. Click `Download YAML`; verify the standard user can download the cluster's YAML.

**Comment by sowmyav27** [comment]
These steps [here](https://github.com/rancher/rancher/issues/38581#issuecomment-1211422169) cannot be validated. The original issue causing this regression has been validated. Fleet check has been performed. CLosing this issue
