### ISSUE TITLE
[BUG] Kubelet crashes when cri_dockerd is enabled on latest 1.21, 1.22, 1.23 RKE1 cluster 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#38594]
**Rancher Server Setup**
- Rancher version: v2.6-head b8b95dc
- Installation option (Docker install/Helm Chart): Docker install
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: found on `1.23.8`, and theoretical `1.22.11` and `1.21.14` 
- Cluster Type (Local/Downstream): Downstream 
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): RKE1 custom, and theoretical node-driver 

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Admin
  - If custom, define the set of permissions:

**Describe the bug**

When creating/editing a cluster with the latest patch version of 1.23/1.22/1.21 and enable `cri_dockerd`, the cluster can not be active because  the `kubelet` container  on the control plane node keeps restarting 

**To Reproduce**

2 scenarios to reproduce it:
1. create  a new cluster in which the k8s version is 1.23.8 / 1.22.11 / 1.21.14, and with `cri_dockerd` enabled 
2. upgrade an existing 1.23.x / 1.22.x/ 1.21.x cluster to 1.23.8 / 1.22.11 / 1.21.14, and with `cri_dockerd` enabled

**Result**
- The cluster cannot be upgrade successfully, and it will be stuck in provisioning/upgrading/error state 
- the `kubelet` container on the control plane node will keep restarting, and its logs contain the following error 
```
E0811 21:51:49.364434  391697 server.go:302] "Failed to run kubelet" err="failed to run Kubelet: unable to determine runtime API version: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial unix /var/run/dockershim.sock: connect: no such file or directory\""
```

**Expected Result**

The cluster should be provisioned/upgraded successfully.

**Comment by Josh-Diamond** [comment]
Ticket #38594 - Test Results

With Docker on a single-node instance:

Reproduced on rancher `v2.6.7-rc7` and `v2.6.7-rc9`:
1. Fresh install of rancher `v2.6.7-rc9`
2. Provision a downstream RKE1 AWS Node driver cluster - 3 nodes - [`1 etcd, 1 cp, 1 wkr`] - w/ k8s `v1.23.8-rancher1-1` and set `enableCriDockerd = true`
3. Reproduced - Cluster stuck in `Provisioning` state w/ error seen below; kubelet on controlplane continuously restarts in attempts to self-heal and provision:
    - `[controlPlane] Failed to upgrade Control Plane: [[[controlplane] Error getting node <REDACTED>: "<REDACTED>" not found]]`

Screenshots:

`rc7`
<img width="1509" alt="Screen Shot 2022-08-11 at 3 08 05 PM" src="https://user-images.githubusercontent.com/46494969/184250905-3766227d-9782-4e44-9ece-3f259274bfd6.png">

`rc9`
<img width="1511" alt="Screen Shot 2022-08-11 at 3 08 21 PM" src="https://user-images.githubusercontent.com/46494969/184250931-2bb231e1-8c87-4055-955e-25be2f2c4ea4.png">

**Comment by kinarashah** [comment]
Waiting on RKE PR to merge, but should be available to test with Rancher setups by refreshing and getting the new KDM on `dev-v2.6` https://drone-publish.rancher.io/rancher/kontainer-driver-metadata/726

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `ee084d0`**

- Set `enable_cri_dockerd: true` in the cluster.yml for clusters with k8s `1.23.8`, `1.22.11` and `1.21.14`.
- Clusters come up Active.

**Comment by Josh-Diamond** [comment]
Ticket #38594 - Test Results

With Docker on a single-node instance:

Verified on rancher `v2.6-ee084d0c431e066e35a861f58a578d12875b0675-head`:
1. Fresh install of rancher `v2.6-head`
2. As admin, create a standard user
3. As standard user, provision a downstream RKE1 AWS Node driver cluster [ 1 etcd, 1 cp, 1 wkr] w/ k8s `v1.23.8-rancher1-1` and `enableCriDockerd=true`
4. Verified - Cluster successfully provisions
5. As standard user, provision a downstream RKE1 AWS Node driver cluster [ 1 etcd, 1 cp, 1 wkr] w/ k8s `v1.23.7-rancher1-1` and `enableCriDockerd=true`
6. Once active, upgrade to k8s `v1.23.8-rancher1-1`
7. Verified - Cluster successfully upgrades and is active

---

Verified on rancher `v2.6.5`:
1. Fresh install of rancher `v2.6.5`
2. Under `Global Settings`, point KDM from `release-2.6` to `dev-2.6`
3. As admin, create a standard user
4. As standard user, provision a downstream RKE1 AWS Node driver cluster [ 1 etcd, 1 cp, 1 wkr] w/ k8s `v1.23.8-rancher1-1` and `enableCriDockerd=true`
5. Verified - Cluster successfully provisions
6. As standard user, provision a downstream RKE1 AWS Node driver cluster [ 1 etcd, 1 cp, 1 wkr] w/ k8s `v1.22.11-rancher1-1` and `enableCriDockerd=true`
7. Verified - Cluster successfully provisions

**Comment by Josh-Diamond** [comment]
Awaiting confirmation that there are no more pending checks before closing this out

**Comment by Josh-Diamond** [comment]
All test cases have been confirmed and successful. Closing issue
