### ISSUE TITLE
[BUG] - Cluster Unavailable after moving a fleet cluster from a fleet workspace to other workspace

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#38596]
**Rancher Server Setup**
- Rancher version: 2.5-head `788262e`
- Installation option: Helm
   - If Helm Chart, Kubernetes Cluster and version: RKE1
- Proxy/Cert Details: rancher-self-signed

**Information about the Cluster**
- Kubernetes version: 1.20.15
- Cluster Type: local and downstream
   - If downstream, what type of cluster? : AWS EC2 node driver

**User Information**
- What is the role of the user logged in? Admin

**Describe the bug**
When moving fleet clusters from the `fleet-default` workspace to other created workspace (e.g `fleet-dashboard`) the fleet agent bundle is stuck in `Wait Applied` state and then the cluster seems Unavailable from the Rancher UI. It's there but:

Cluster here is `izt5`

<img width="1009" alt="Screen Shot 2022-08-11 at 4 38 26 PM" src="https://user-images.githubusercontent.com/27659/184259904-c2e0851b-fa15-46fa-9e93-96698d249c3e.png">

**To Reproduce**

- Create 2 clusters I used AWS node driver with k8s 1.20.15
- Navigate to `Cluster Explorer` -> `Continuous Delivery`
- Configure a fleet repository and target `Cluster 1`
- Create a fleet workspace `fleet-dashboard`
- Move `Cluster 2` from `fleet-default` to `fleet-dashboard`

**Result**
<img width="1009" alt="Screen Shot 2022-08-11 at 4 42 39 PM" src="https://user-images.githubusercontent.com/27659/184260231-fdf4c9d6-2b9b-470b-bc65-b75d42b5a99e.png">

Fleet controller logs:

```
time="2022-08-11T21:20:03Z" level=error msg="error syncing 'fleet-dashboard/c-627f6': handler import-cluster: an error on the server (\"secrets \\\"cattle-global-data/\\\" not found\") has prevented the request from succeeding, requeuing"

time="2022-08-11T21:20:41Z" level=info msg="Deleting expired registration secret fleet-clusters-system/c-81f6c7459756620ee4ee22a83dd5fdba8e0f0c56d2338ff8539969da79b56"

time="2022-08-11T21:21:03Z" level=error msg="error syncing 'fleet-dashboard/c-627f6': handler import-cluster: an error on the server (\"secrets \\\"cattle-global-data/\\\" not found\") has prevented the request from succeeding, requeuing"

time="2022-08-11T21:22:03Z" level=error msg="error syncing 'fleet-dashboard/c-627f6': handler import-cluster: an error on the server (\"secrets \\\"cattle-global-data/\\\" not found\") has prevented the request from succeeding, requeuing"

time="2022-08-11T21:23:03Z" level=error msg="error syncing 'fleet-dashboard/c-627f6': handler import-cluster: an error on the server (\"secrets \\\"cattle-global-data/\\\" not found\") has prevented the request from succeeding, requeuing"

time="2022-08-11T21:24:03Z" level=error msg="error syncing 'fleet-dashboard/c-627f6': handler import-cluster: an error on the server (\"secrets \\\"cattle-global-data/\\\" not found\") has prevented the request from succeeding, requeuing"

time="2022-08-11T21:25:03Z" level=error msg="error syncing 'fleet-dashboard/c-627f6': handler import-cluster: an error on the server (\"secrets \\\"cattle-global-data/\\\" not found\") has prevented the request from succeeding, requeuing"

time="2022-08-11T21:26:03Z" level=error msg="error syncing 'fleet-dashboard/c-627f6': handler import-cluster: an error on the server (\"secrets \\\"cattle-global-data/\\\" not found\") has prevented the request from succeeding, requeuing"
```

Rancher Logs when trying to access the cluster from the Rancher UI

```
2022/08/11 20:46:14 [DEBUG] Triggering auth refresh on user-clmt2
2022/08/11 20:46:14 [DEBUG] Skipping refresh for user-clmt2 due to max-age
2022/08/11 20:46:14 [ERROR] failed on subscribe gateway: ClusterUnavailable 503: ClusterUnavailable 503: cluster not found
2022/08/11 20:46:14 [ERROR] failed on subscribe serviceMonitor: ClusterUnavailable 503: ClusterUnavailable 503: cluster not found
2022/08/11 20:46:14 [ERROR] failed on subscribe replicationController: ClusterUnavailable 503: ClusterUnavailable 503: cluster not found
2022/08/11 20:46:14 [ERROR] failed on subscribe cronJob: ClusterUnavailable 503: ClusterUnavailable 503: cluster not found
2022/08/11 20:46:14 [ERROR] failed on subscribe persistentVolumeClaim: ClusterUnavailable 503: ClusterUnavailable 503: cluster not found
2022/08/11 20:46:14 [ERROR] failed on subscribe namespacedCertificate: ClusterUnavailable 503: ClusterUnavailable 503: cluster not found
2022/08/11 20:46:14 [ERROR] failed on subscribe pod: ClusterUnavailable 503: ClusterUnavailable 503: cluster not found
2022/08/11 20:46:14 [ERROR] failed on subscribe configMap: ClusterUnavailable 503: ClusterUnavailable 503: cluster not found
2022/08/11 20:46:14 [ERROR] failed on subscribe daemonSet: ClusterUnavailable 503: ClusterUnavailable 503: cluster not found
2022/08/11 20:46:14 [ERROR] failed on subscribe prometheusRule: ClusterUnavailable 503: ClusterUnavailable 503: cluster not found

```

**Expected Result**
Cluster moved to the `fleet-dashboard` workspace and in `Active` state
Cluster is accessible from the Rancher UI

**Additional context**
This is not reproducible on 2.5.15
Fleet version is: `v0.3.9`

**Comment by sowmyav27** [comment]
**On 2.5head commit id: `d9101f3`**

- Upgraded rancher operator from `rancher-operator:0.1.400` to `rancher-operator:0.1.500-rc1+up0.1.5-rc1` manually
- Create 1 cluster1  AWS node driver with k8s 1.20.15
- Navigate to Cluster Explorer -> Continuous Delivery
- Create a fleet workspace `test`
- Move Cluster 1 from `fleet-default` to `test`
- Cluster comes up Active in the new workspace
- Cluster Bundles page is Active

**Comment by izaac** [comment]
Rancher version: `v2.5.15-rc3` 
rancher operator version `rancher-operator:v0.1.5-rc1`
fleet version: `v0.3.9`

This is no longer reproducible, there aren't cluster unavailable errors after moving clusters from fleet workspaces.

**Comment by izaac** [comment]
https://github.com/rancher/rancher/issues/38613
