### ISSUE TITLE
[BUG] seLinux Being Disabled by Default Causing Logging Upgrade to Fail

### ISSUE THREAD

**Issue by nickwsuse** [rancher/rancher#38600]
**Rancher Server Setup**

- Rancher version: `2.6.7-rc6`
- Installation option (Docker install/Helm Chart): HELM
  - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2
- Proxy/Cert Details: byo-valid

**Information about the Cluster**
- Kubernetes version: `v1.23.7`
- Cluster Type (Local/Downstream): `Downstream Imported AWS RKE2 cluster`

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): `admin`

**Describe the bug**
After upgrading rancher from 2.6.6. to 2.6.7-rc6, I upgraded logging to 3.17.7; The rancher-logging app on the installed apps page shows a FAILED tag. the rancher-logging-rke2-journalId-aggregators are in crashloop and after investigation it's because the seLinux value in the values.yaml file is set to `false` when it should be set to `true`

**To Reproduce**
1. Install previous version of logging in rke2 cluster
2. configure cluster output
3. configure cluster flow
4. verify that logs are flowing to output (eg, elasticsearch)
5. upgrade logging to latest 100.1.3-up3.17.7 [pointed charts repo to dev-2.6]
6. click the "Edit YAML" button on the second page of the install
7. search for `global` > `seLinux` > `enabled` > see it's `false` instead of `true`

Result
Upgrade fails; rke2 logging aggregator pods in crashloop

Expected Result
Upgrade succeeds and logs resume flowing to elasticsearch

**Screenshots**

App Failed State:
![app_failed_state](https://user-images.githubusercontent.com/107147272/183769953-c4ff69e9-339f-4a08-97aa-1eb1c0af9427.png)

Crashloop:
![image](https://user-images.githubusercontent.com/107147272/183948229-52c60b2b-7832-4037-b364-47bab9fd88f4.png)

seLinux Set to False:
**deleted**

Deployed After Setting seLinux to True:
![deployed_after_edit](https://user-images.githubusercontent.com/107147272/183771427-dbf115a1-60b3-4e63-a9dd-c6ab27103810.png)

**Comment by bmdepesa** [comment]
This is a non-issue. The OS/AMI used in this test (RHEL) requires seLinux to be enabled. 

UI is actually functioning correctly, and there's no backend or chart problem.
