### ISSUE TITLE
Unable to run K3s/RKE2 1.24.x on CentOS 7/RHEL 7

### ISSUE THREAD

**Issue by Oats87** [rancher/rancher#38611]
Due to https://github.com/k3s-io/k3s/issues/5912, we are unable to run K3s/RKE2 1.24.x on CentOS 7/RHEL 7 machines.

See https://github.com/rancher/rancher/issues/38610 for a similar issue.

**Comment by snasovich** [comment]
@Oats87 , closing this issue as with the current wording it sounds more like RKE2/k3s standalone issue.
As far as Rancher is concerned, a combination of https://github.com/rancher/rancher/issues/38610 and https://github.com/rancher/rancher/issues/38619 seems to cover the impact of the issue.
