### ISSUE TITLE
Unable to effectively run Rancher as a Docker container on CentOS/RHEL 7

### ISSUE THREAD

**Issue by Oats87** [rancher/rancher#38610]
Version: v2.6-head (`ee084d0`)
Rancher is unable to run effectively as a docker container on CentOS 7/RHEL 7 due to https://github.com/k3s-io/k3s/issues/5912

This issue doesn't manifest itself in a very obvious manner until an action that requires a functional local cluster is performed. For example, creating a new RKE2 cluster results in an error message like:
<img width="1158" alt="Screen Shot 2022-08-15 at 10 42 34 AM" src="https://user-images.githubusercontent.com/30601846/184687558-a4d335ac-1df3-4fb1-99b7-1e7620f7072f.png">

**Comment by sowmyav27** [comment]
Reproduced the issue on `2.6.7-rc9` using RHEL 7.9 instance to run rancher docker install on

The downstream Rancher RKE2 1.24 cluster fails to come up with error: `Failed to create fleet-default/sowmya-1 cluster.x-k8s.io/v1beta1, Kind=Cluster for rke-cluster fleet-default/sowmya-1: Internal error occurred: failed calling webhook "default.cluster.cluster.x-k8s.io": failed to call webhook: Post "https://webhook-service.cattle-system.svc:443/mutate-cluster-x-k8s-io-v1beta1-cluster?timeout=10s": service "webhook-service" not found, failed to create fleet-default/sowmya-1-pool1 cluster.x-k8s.io/v1beta1, Kind=MachineDeployment for rke-cluster fleet-default/sowmya-1: Internal error occurred: failed calling webhook "default.machinedeployment.cluster.x-k8s.io": failed to call webhook: Post "https://webhook-service.cattle-system.svc:443/mutate-cluster-x-k8s-io-v1beta1-machinedeployment?timeout=10s": service "webhook-service" not found`

**Comment by snasovich** [comment]
The plan it to address this issue by bumping down k3s version embedded in Rancher to `1.24.1-k3s` that does not have this issue.
Note this will not fix https://github.com/rancher/rancher/issues/38619, but that issue can be addressed via out-of-band KDM release introducing 1.24.4 versions of RKE2/k3s which will have this issue fixed (once they are available).

**Comment by snasovich** [comment]
This is ready to test. The only change is we've changed embedded k3s for Docker run case in Rancher from 1.24.2 to 1.24.1 which should not exhibit this issue and run fine on CentOS/RHEL 7.

**Comment by Josh-Diamond** [comment]
Ticket #38610 - Test Results

With Docker on a single-node RHEL 7.9 instance:

Verified on rancher `v2.6-d519776e6d9ddddb0781638c8bbb38c629022225-head`:
1. Fresh install of rancher `v2.6-head`
2. Verified - local k3s is `v1.24.1+k3s1`
3. Provision a downstream RKE2 AWS Node driver cluster - 3 nodes - [ 1 etcd, 1 cp, 1 wkr]
4. Verified - Cluster successfully provisions

Screenshot:
<img width="1686" alt="Screen Shot 2022-08-16 at 4 56 02 PM" src="https://user-images.githubusercontent.com/46494969/185005236-c04b06a9-73f7-4238-9fe5-605c7cc73a94.png">

**Comment by gregoryca** [comment]
I'm having the same error on version v2.8.2.
