### ISSUE TITLE
Harvester cloud provider bump to 1.13 in charts 

### ISSUE THREAD

**Issue by chrisho** [rancher/rancher#38618]
Harvester cloud provider bump to 1.13 in charts 
Add CPI chart on release.yaml
Make Harvester CSI Driver support kubernetes 1.24

**Comment by TachunLin** [comment]
Pre-validate before merging https://github.com/rancher/charts/pull/2012
Verified **fixed** with Harvester v1.0.3 with Rancher v2.6.7-rc6 using the following 

* Git Repo URL: https://github.com/chrisho/rancher-charts
* Git branch: cloud-provider
  ![image](https://user-images.githubusercontent.com/29251855/184811282-65084c69-5902-4db9-bcdf-430681e0a69f.png)
  ![image](https://user-images.githubusercontent.com/29251855/184811792-c4e5b789-e411-48da-82fa-5811b637ec95.png)
* Cloud provider version: `100.0.3+up0.1.13`
* CSI driver version: `100.0.3+up0.1.14`

Verified the following KDM release version on **RKE1** cluster
* v1.24.2
* v1.23.8
* v1.22.11
* v1.21.14

### RKE1 v1.24.2

#### Cloud provider 100.0.3+up0.1.13 (v1.24.2)
  ![image](https://user-images.githubusercontent.com/29251855/184795975-85a761fc-23c2-497e-afdc-428a98404f3d.png)
  ![image](https://user-images.githubusercontent.com/29251855/184796104-1c8a3531-16b4-4a5b-8e65-cf8983cc09e4.png)
  ![image](https://user-images.githubusercontent.com/29251855/184796128-7b9918cd-ca2f-46ea-97dc-605201d72f7f.png)

#### CSI driver 100.0.3+up0.1.14 (v1.24.2)
  ![image](https://user-images.githubusercontent.com/29251855/184796008-996afa61-4548-4257-b641-e8fb6e718f96.png)
  ![image](https://user-images.githubusercontent.com/29251855/184796354-44de5eaa-7abf-4ce1-98e5-73302855d028.png)
  ![image](https://user-images.githubusercontent.com/29251855/184796518-a61b6ff9-955d-4c98-a9dd-c8ccbeabda7d.png)

#### CCM & CSI chart (v1.24.2)
1. Test CSI driver on nginx (v1.24.2) 
  ![image](https://user-images.githubusercontent.com/29251855/184798301-4a4b901c-c633-4ecf-949c-a8278cb5af99.png)
  ![image](https://user-images.githubusercontent.com/29251855/184798339-5c1d4195-693c-48fe-9702-70dae8eb60ed.png)
  ![image](https://user-images.githubusercontent.com/29251855/184798359-c1965cf0-d7fb-45ab-9d6e-43623c25fb19.png)

2.  Cloud provider - LB DHCP (v1.24.2)
  ![image](https://user-images.githubusercontent.com/29251855/184799385-f091e462-bf10-4e85-aa88-069ca28576e7.png)

3. Cloud provider - LB Pool (v1.24.2)
  ![image](https://user-images.githubusercontent.com/29251855/184802709-49055979-0242-4922-ae28-f443de44973f.png)

#### CCM and CSI chart in v1.24.2
  ![image](https://user-images.githubusercontent.com/29251855/184796845-4869ba3b-f6c6-4eff-b940-f36556de29dc.png)


### RKE1 v1.23.8

#### Cloud provider 100.0.3+up0.1.13 (v1.23.8)
  ![image](https://user-images.githubusercontent.com/29251855/184812207-c12cad45-1e0c-43ca-bce0-6d2d0e859bab.png)

#### CSI driver 100.0.3+up0.1.14 (v1.23.8)
  ![image](https://user-images.githubusercontent.com/29251855/184812734-cdcd7000-258c-468b-92d9-32d410de5ed7.png)

#### CSI driver (v1.23.8)
1. Test CSI driver on nginx (v1.23.8) 
  ![image](https://user-images.githubusercontent.com/29251855/184813981-c5272fc0-230e-483a-9217-b75513a8134a.png)
  ![image](https://user-images.githubusercontent.com/29251855/184814022-d3ee5aa8-01ac-47c1-9ceb-28502415ecb3.png)

2.  Cloud provider - LB DHCP (v1.23.8)
  ![image](https://user-images.githubusercontent.com/29251855/184814202-54df66d7-6b35-4c72-8260-ef8cadeb9508.png)

3. Cloud provider - LB Pool (V1.23.8)
  ![image](https://user-images.githubusercontent.com/29251855/184814356-d9f09107-31fc-43e4-839c-d5874362adac.png)

#### CCM and CSI chart in v1.23.8
  ![image](https://user-images.githubusercontent.com/29251855/184814817-ed2e2b7d-040a-4c9c-9257-117122ed27e0.png)


### RKE1 v1.22.11

#### Cloud provider 100.0.3+up0.1.13 (v1.22.11)
  ![image](https://user-images.githubusercontent.com/29251855/184818766-4be6e964-31ac-405b-9106-374d462f433e.png)

#### CSI driver 100.0.3+up0.1.14 
  ![image](https://user-images.githubusercontent.com/29251855/184819737-1549778f-5d98-4c0a-acd0-55403897f7a4.png)

#### CSI driver (v1.22.11)
1. Test CSI driver on nginx (v1.22.11) 
  ![image](https://user-images.githubusercontent.com/29251855/184821594-365a5842-5736-46c0-b932-7dc2529da712.png)
  ![image](https://user-images.githubusercontent.com/29251855/184821739-5ac03899-28ba-4930-a72a-2dcde8233d2e.png)

2.  Cloud provider - LB DHCP (v1.22.11)
  ![image](https://user-images.githubusercontent.com/29251855/184822148-0df10997-1f18-415d-8989-14f7fccba5d9.png)

3. Cloud provider - LB Pool (v1.22.11)
  ![image](https://user-images.githubusercontent.com/29251855/184822386-e9e8ec7c-f6f7-406e-94d6-ddb5a86bba00.png)

#### CCM and CSI chart in v1.22.11
  ![image](https://user-images.githubusercontent.com/29251855/184820265-73b2bc1e-b9f2-40c7-a853-2f506c6b7e01.png)


### RKE1 v1.21.14

#### Cloud provider 100.0.3+up0.1.13 (v1.21.14)
  ![image](https://user-images.githubusercontent.com/29251855/184828239-600a8aa0-7a27-4806-875d-70065926b6a3.png)

#### CSI driver 100.0.3+up0.1.14 (v1.21.14)
  ![image](https://user-images.githubusercontent.com/29251855/184828625-168503c4-ae2b-44db-85b6-38584e493d1c.png)

#### CSI driver (v1.21.14)
1. Test CSI driver on nginx (v1.21.14) 
  ![image](https://user-images.githubusercontent.com/29251855/184829604-100473a8-6473-4ea9-a462-1be72d31f1f0.png)
  ![image](https://user-images.githubusercontent.com/29251855/184829662-74eff081-9ef9-471a-8c25-7fc236383979.png)

2.  Cloud provider - LB DHCP (v1.21.14)
  ![image](https://user-images.githubusercontent.com/29251855/184829890-feaa7ada-491c-446f-a833-e8c7bdfd215f.png)

3. Cloud provider - LB Pool (v1.21.14)
  ![image](https://user-images.githubusercontent.com/29251855/184830181-e48921ac-ca36-4fa3-be8e-08a09d1b245d.png)

#### CCM and CSI chart in v1.21.14
  ![image](https://user-images.githubusercontent.com/29251855/184830221-8c5d838c-5e93-4a69-a4d5-3282c8853d72.png)

**Comment by TachunLin** [comment]
Verified **fixed** with Harvester v1.0.3 with Rancher v2.6.7-rc9. 

### Result 
Verified the bumped cloud provider v0.1.13 and fixed the CSI driver supported kubernetes version PR 
https://github.com/rancher/charts/pull/2012 worked correctly under the following test scenarios

- [ ] Deploy custom CSI and Cloud provider on different RKE1 cluster version
- [ ] Test the bumped CSI driver on each KDM release by using `Nginx PVC` deployment
- [ ] Test the bumped Cloud Provider on each KDM release  by using `DHCP` load balancer
- [ ] Test the bumped Cloud Provider on each KDM release  by using `Pool` load balancer

#### Verified the following KDM release version on **RKE1** cluster
* v1.24.2
* v1.23.8
* v1.22.11
* v1.21.14

### Test Information
* Test Environment: 1 node harvester on local kvm machine
* Harvester version: v1.0.3
* Rancher version: v2.6.7-rc9
* Git Repo URL: https://github.com/chrisho/rancher-charts
* Git branch: cloud-provider
  ![image](https://user-images.githubusercontent.com/29251855/184811282-65084c69-5902-4db9-bcdf-430681e0a69f.png)
  ![image](https://user-images.githubusercontent.com/29251855/184811792-c4e5b789-e411-48da-82fa-5811b637ec95.png)
* Cloud provider version: `100.0.3+up0.1.13`
* CSI driver version: `100.0.3+up0.1.14`
* Cloud provider installation: manual 


### Verify Steps
1. Import Harvester in Rancher
2. Create cloud credential
3. Create an RKE1 template 
4. Provision the RKE1 cluster with different Kubernetes version (1.24.2, v1.23.8, v1.22.11, v1.21.14) 
5. Select `Harvester (Out-of-tree)` in the cloud provider 
6. Wait for provisioning complete 
7. Open RKE1 cluster page 
8. Open Apps -> Repositories
9. Create a new repository
10. Select Git repository containing ...
11. Paste the url: https://github.com/chrisho/rancher-charts
12. Provide git branch: cloud-provider
13. Open Apps -> Charts
14. Search cloud provider and csi driver 
15. Install the latest version of cloud provider and csi driver
16. Check the installed version on Apps -> Install Apps
17. Open Workload -> Daemon sets 
18. Deploy a nginx with custom Harvester PVC (refer to https://github.com/harvester/harvester/issues/1812) 
19. Check default storage and PVC in Storage
20. Create a DHCP Load balance using the nginx service 
21. Check can route correctly
22. Add vip-pool in Harvester settings
23. Create a Pool Load balance using the nginx service 
24. Check can route correctly

### Additional Context

**Comment by slickwarren** [comment]
closing in favor of the above validation done by harvester team now that the PR is merged.
