### ISSUE TITLE
cluster not found 400 error in rancher logs after cluster is deleted

### ISSUE THREAD

**Issue by kinarashah** [rancher/rancher#38617]
Rancher version: v2.6.2/v2.6.3 
RKE1 Downstream cluster (k8s 1.19.5, vsphere) 

After cluster is deleted, rancher continues logging errors for the cluster: 
`
2022/02/28 09:57:05 [ERROR] Failed to handling tunnel request from 10.42.1.0:37160: response 400: nodes.management.cattle.io "c-7gjdk/m-222e942a7f26" not found
`
`
2022/02/28 09:57:05 [ERROR] Failed to handling tunnel request from 10.42.1.0:40520: response 400: nodes.management.cattle.io "c-7gjdk/m-7c6368f4f2fd" not found 
`
`
2022/02/28 09:57:06 [ERROR] Failed to handling tunnel request from 172.16.34.19:52296: response 400: cluster not found 
`
`
2022/02/28 09:57:07 [ERROR] Failed to handling tunnel request from 10.42.0.0:40414: response 400: cluster not found
 `
 
Note that in 2.6.7+ the message wording is changed slightly (could be relevant when grepping for these errors): https://github.com/rancher/rancher/commit/abe5a4ea08ec8891f821d5e9c95e74d12f3e16c5#diff-547d3b6dfb401e9332db8c2d3873de49270b5ff02013c8ef7e5035e9a1fa5e5aR21

 SURE-4161 
 Also possibly related - SURE-4332

**Comment by yankees5963** [comment]
This issue has been filling our logs making reading any true errors impractical. Please Fix!!!

**Comment by Sahota1225** [comment]
Closing this ticket as per the reporter on the Jira ticket, the customer is unresponsive.

**Comment by yankees5963** [comment]
How do you add this to a milestone to fix then close? And I see no linked jira ticket where I responded that it could be closed. I am still waiting for a fix from rancher
