### ISSUE TITLE
[Cattle] Cluster agent should restart if it is currently down prior to deploying a container to it

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#3863]
Since it's possible for a user to deactivate the cluster agent or cluster instance (swarm server) manually via the API, this would prevent a container from being deploy to the cluster even though the cluster is active. We should detect this and automatically restart the agent / re-deploy the cluster server if this happens.

**Comment by will-chan** [comment]
closing with new swarm implementation.
