### ISSUE TITLE
[BUG][Windows] pushprox-kube-etcd-client is failing due to copy-certs failure

### ISSUE THREAD

**Issue by ronhorton** [rancher/rancher#38648]
**Rancher Server Setup**
- Rancher version: `2.6-head Commit ID e899f13`
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): Helm HA
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: `v1.24.2`
- Cluster Type (Local/Downstream): `downstream - windows - rke2`
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: `Admin`

**Describe the bug**

when installing monitoring on windows rke2 cluster, Cluster Type =  Windows, pushprox-kube-etcd-client goes into a crash loop due to unable to locate cert. 
**To Reproduce**
1. create windows rke2 server
2. install rancher-monitoring
3. on step 2, change cluster type to `windows`
4. Install
5. got to workload > pods

**Result**
pushprox in a crash loop
pushprox-kube-etcd-client-74z2g logs
```
Wed, Aug 17 2022 11:04:30 am | Searching for files to copy within the source volume
Wed, Aug 17 2022 11:04:30 am | cert: kube-etcd-*.pem
Wed, Aug 17 2022 11:04:30 am | key: kube-etcd-*-key.pem
Wed, Aug 17 2022 11:04:30 am | cacert: kube-ca.pem
Wed, Aug 17 2022 11:04:30 am | Failed to find cert file
```

**Expected Result**
all pods in an active state

**Screenshots**

<img width="1372" alt="2022-08-17_14-03-06" src="https://user-images.githubusercontent.com/89212856/185210982-22c715c0-f7e7-4dfa-af78-17a864c7ae66.png">
<img width="1399" alt="2022-08-17_14-03-25" src="https://user-images.githubusercontent.com/89212856/185211028-6eda11cf-56c1-43be-a16b-f12b4ebe0c4b.png">
<img width="1127" alt="2022-08-17_14-04-43" src="https://user-images.githubusercontent.com/89212856/185211062-1099bd8b-4e2d-449a-b2e7-2a2fe446466e.png">

**Additional context**

**Comment by bmdepesa** [comment]
This issue is caused by selecting `Windows` as the cluster type when installing monitoring. When doing so, the RKE1 windows components are deployed instead of the proper rke2 components. 

Selecting `rke2` allows the correct components to deploy and the pushprox pods come up succesfully.
