### ISSUE TITLE
[BUG][Windows] check-wins-version container in rancher-monitoring-windows-exporter failing in windows rke2

### ISSUE THREAD

**Issue by ronhorton** [rancher/rancher#38650]
**Rancher Server Setup**
- Rancher version: `2.6-head Commit ID e899f13`
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): Helm HA
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: `v1.24.2`
- Cluster Type (Local/Downstream): `downstream - windows - rke2`
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: `Admin`

**Describe the bug**
When installing monitoring on windows rke2, rancher-monitoring-windows-exporter is failing due to contain check-wins-version encountering an invalid argument
`InvalidArgument: C:\scripts\check-wins-version.ps1:9
Line |
9 | return [System.Version]($winsAppInfo.Server.Version.substring(1))
| ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| Cannot convert value "799597-dirty" to type "System.Version".
| Error: "Version string portion was too short or too long.
| (Parameter 'input')"`

see this comment from issue that has the same issue: https://github.com/rancher/rancher/issues/37022#issuecomment-1110289430

**To Reproduce**
1. deploy windows rke2 cluster
2. install rancher-monitoring

**Result**
rancher-monitoring-windows-exporter fails

**Expected Result**
all pods/services install and are active

**Screenshots**
<img width="1575" alt="Screen Shot 2022-08-17 at 1 25 24 PM" src="https://user-images.githubusercontent.com/89212856/185213206-8ea7cc62-c45e-471e-ae62-d76d20e5a6e4.png">
<img width="1491" alt="Screen Shot 2022-08-17 at 1 25 59 PM" src="https://user-images.githubusercontent.com/89212856/185213250-9d35e99f-4baf-4da2-8629-ca66e87bb87e.png">

**Additional context**
issue: https://github.com/rancher/rancher/issues/37022

**Comment by sowmyav27** [comment]
**On 2.6head commit id: `b198945`**

- Deployed RKE2 windows `v1.24.2+rke2r1` Custom cluster - 1 etcd, 1 cp, 3 worker nodes Linux and.1 Windows 2022 worker node
- Deployed monitoring v2 on the cluster (cluster type RKE2)
- `rancher-monitoring-windows-exporter` daemonset is up and Active
- rancher-wins version on windows node is `0.4.6`
