### ISSUE TITLE
[Cattle] [swarm integration] cattle should expose which hosts are currently reachable by a swarm cluster

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#3865]
Even though a host may be reachable by cattle, it might not be reachable by the swarm cluster due to firewall issues (or bad SSL certs). It would be useful to know which hosts a swarm cluster deems is downed. Otherwise, the only indication a user would get is that containers seem to never be deployed to a specific host (and only distributed across the other hosts in the cluster).

**Comment by will-chan** [comment]
closing for new swarm integration.
