### ISSUE TITLE
[BUG] system-upgrade-controller version is not defaulting to 0.3.3

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#38652]
**on 2.6.7-rc9**

- Deployed a windows RKE2 cluster (1 etcd/cp/worker linux nodes and 1 windows 2022 node) - 1.23RKE2 version
- In System project page, system-upgrade-controller deployment/pod defaults to 0.3.2

Expected
system-upgrade-controller defaults to 0.3.3

**Comment by kinarashah** [comment]
Available to test with v2.6-head after drone passes https://drone-publish.rancher.io/rancher/rancher/8214

**Comment by sowmyav27** [comment]
**on 2.6head commit id: `b198945`**

- Deployed a windows RKE2 cluster (1 etcd/cp/worker linux nodes and 1 windows 2022 node) - 1.24RKE2 version
- `system-upgrade-controller:100.0.3+up0.3.3` is seen installed.
