### ISSUE TITLE
[BUG] CIS scan runs indefinitely and never completes. windows RKE2 clusters

### ISSUE THREAD

**Issue by AndrewHoffmanQA** [rancher/rancher#38664]
**Setup**

- rancher version -v2.6-cb9ccde
 Browser type & version: HA rancher
- RKE1 v1.24.4

**Downstream cluster**

RKE- v1.24.4+rke2r1
3 linux worker, 2 controlplante, 2 etcd, 1 windows worker
AMI used- ami-0e676645ef0eaf221
custom cluster.
CIS chart 2.1.0 

**Describe the bug**
as a user when I run I install and run CIS Scan 2.1.0, with any scan, it never completes and indefinitely displays as 'running' 

**To Reproduce**

Stand up a HA server
Utilize the side menu via hamburger in left top corner
Click on desired server in the ‘explore cluster’ section
select the downstream windows cluster
Click ‘apps’, in dropdown click ‘charts’
Locate and click on CIS benchmark chart. (2.1.0)
Click install (top right)
In ‘install into project’ dropdown select system.
Click install
Click install a second time
On the side menu, ‘CIS benchmark’ dropdown should now be available. (refresh page if not)
Click the ‘CIS benchmark’ dropdown, select scans
Click create
In ‘profile dropdown’ select 1.5 permissive or 1.6 permissive
Click create

**Result**
the scan hangs indefinitely.  the UI reports that the scan is 'running'

**Expected Result**
after about 60 seconds the scan returns the results and displays them, updating the UI

**Screenshots**

![image](https://user-images.githubusercontent.com/89030218/185496708-7c8f937b-ce2a-410d-90e2-f0015959d7c2.png)

**Additional context**
in both clusters, the pod seems to be throwing this error. 
![image](https://user-images.githubusercontent.com/89030218/185633374-cf46411e-aeaa-4143-8558-35eb694be735.png)

per more investigation with Brandon Depesa the scan is scheduled on the Windows node, which is probably the root cause of the issue. 

![image](https://user-images.githubusercontent.com/89030218/189397744-bef3f79e-7cc8-4221-99df-774f4dad6230.png)

**Comment by AndrewHoffmanQA** [comment]
reproduced this bug again. updated the body of the ticket to reflect the additional repro info and added the AMI.

**Comment by bmdepesa** [comment]
The security scan runner is being scheduled on the Windows node, which is not supported. The deployment needs a node selector to only target Linux nodes.

**Comment by rishabhmsra** [comment]
Validated on rancher v2.7.0-rc2 HA setup.

Steps followed:
- Provisioned a downstream RKE2 v1.24.6-rancher1-1 cluster -> 3 linux worker, 2 cp, 2 etcd, 1 windows worker
- Installed CIS 3.0.0-rc3 chart version.
- Ran the v1.23 permissive profile scan.

Result:
- Scan is getting completed and NOT running indefinitely now. However it takes around 5 mins for the scan to get completed.
