### ISSUE TITLE
Hide CIS 1.5 scan profiles from cis benchmark charts

### ISSUE THREAD

**Issue by mitulshah-suse** [rancher/rancher#38668]
CIS benchmark 1.5 scan profiles support kubernetes version 1.15 which is not used anywhere in rancher.
So we need to hide those scan profiles in the CIS benchmark chart

**Comment by vivek-infracloud** [comment]
The CIS benchmark scan profile 1.5 is not visible on the cluster.
![Screenshot from 2022-09-20 12-00-30](https://user-images.githubusercontent.com/83208989/191183946-fcd24f12-f5e8-454b-b0f6-990439b17afe.png)
