### ISSUE TITLE
Upgrade Calico CNI to 3.21.3

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#38662]
**Issue Description:**
The latest RKE1 K8s versions of 1.22.x in KDM include Calico 3.21.1 which has a known regression in client-go, which can cause Canal to lose connectivity on larger clusters (50+ nodes) with a lot of resources/objects (500+) This was fixed in Calico 3.21.3. Typha can disconnect from the datastore when a resync is required such as after an etcd compaction.
More info here -
[https://github.com/projectcalico/calico/issues/5173]
[https://github.com/projectcalico/calico/pull/5332]
Bugfix listed in changelog -
[https://projectcalico.docs.tigera.io/archive/v3.21/release-notes/#v3213]

**Business impact:**
CNI disruption during an upgrade from 1.21 to 1.22, possible random CNI disruptions.

**Troubleshooting steps:**
Customer redeployed canal ds after an upgrade from 1.21.10 to 1.22.9.
Noticed a pattern of errors from the calico-node_canal pods as below

{{2022-08-11T02:39:04.747280720Z 2022-08-11 02:39:04.746 [INFO][55] status-reporter/watchercache.go 97: Watch channel closed by remote - recreate watcher ListRoot="/calico/resources/v3/projectcalico.org/caliconodestatuses"}}
{{2022-08-11T02:39:04.844155723Z W0811 02:39:04.843903      51 warnings.go:70] discovery.k8s.io/v1beta1 EndpointSlice is deprecated in v1.21+, unavailable in v1.25+; use discovery.k8s.io/v1 EndpointSlice}}
{{2022-08-11T02:39:04.961869532Z 2022-08-11 02:39:04.961 [INFO][55] status-reporter/watchercache.go 122: Watch error received from Upstream ListRoot="/calico/resources/v3/projectcalico.org/caliconodestatuses" error=too old resource version: 1048885061 (1048889455)}}
{{2022-08-11T02:39:04.961893361Z 2022-08-11 02:39:04.961 [INFO][55] status-reporter/watchercache.go 175: Full resync is required ListRoot="/calico/resources/v3/projectcalico.org/caliconodestatuses"}}

Changing images for Calico to reflect 3.21.3 makes the errors and messages disappear.

**Repro steps:**
 * Create a large RKE1 cluster with k8s 1.21.10 & 50+ nodes, canal as CNI
 * Create a large amount of resources, pods/configmaps/secrets/services etc, 500+
 * upgrade to 1.22.9, updating calico from 3.17.2 to 3.21.1

**Additional context**
Other versions are fine as they are using either Calico 3.19.x or Calico 3.22.0 which respectively don't have the regression or have it fixed (https://projectcalico.docs.tigera.io/archive/v3.22/release-notes#v3220).

SURE-5117

**Comment by sowmyav27** [comment]
@samkulkarni20 Please validate
- on 2.6.7, KDM pointing to dev-v2.6, provision a`1.22.13` RKE1 cluster and Verify the Calico CNI version is `3.21.3`
- Run network checks on the above cluster ^^
- Upgrade usecase
```
- - on 2.6.7, KDM pointing to release, provision a `v1.21.14-rancher1-1` RKE1 cluster. 
- - Run pre upgrade checks. 
- - Upgrade KDM to dev-v2.6
- - Upgrade k8s version to `1.22.13`
- - Verify cluster finishes updating and comes back up Active
- - Run post upgrade checks and verify they pass
```

**Comment by vivek-infracloud** [comment]
**Validated upgrade usecase for Calico CNI.**

- on 2.6.7, KDM pointing to release, provision a `v1.21.14-rancher1-1` RKE1 cluster. 
- Run pre upgrade checks. 
- Upgrade KDM to dev-v2.6
- Upgrade k8s version to `1.22.13`
- Verify cluster finishes updating and comes back up Active
- Verifies the Calico CNI version is **3.21.3**
- Run post upgrade checks and verify they pass

**Comment by vivek-infracloud** [comment]
**Validated fresh install checks.**

- On 2.6.7, KDM pointing to dev-v2.6, provisioned a 1.22.13 RKE1 cluster.
- Verified the Calico CNI version is 3.21.3.
- Run network checks on the above cluster.
- Network checks passed.
