### ISSUE TITLE
[BUG] I restart docker,and rancher server  v2.6.3 loop restarting.

### ISSUE THREAD

**Issue by saxonredhat** [rancher/rancher#38671]
_I running rancher v2.6.3 in docker.
Today I restart docker,and rancher server loop restarting._
**$ docker ps |grep rancher-v263** 
39c893408b77   rancher/rancher:v2.6.3                          "entrypoint.sh"          2 months ago         Restarting (1) 31 seconds ago                                               rancher-v263

_I restart rancher many times,but logs time always 2022/08/19 08:43,not any updates._
**$ docker restart  rancher-v263** 
**$ docker logs rancher-v263 --tail=300**
022/08/19 08:43:35 [INFO] error in remotedialer server [400]: websocket: close 1006 (abnormal closure): unexpected EOF
2022/08/19 08:43:35 [INFO] error in remotedialer server [400]: websocket: close 1006 (abnormal closure): unexpected EOF
2022/08/19 08:43:35 [INFO] error in remotedialer server [400]: websocket: close 1006 (abnormal closure): unexpected EOF
E0819 08:43:35.776035     135 upgradeaware.go:401] Error proxying data from backend to client: tunnel disconnect
E0819 08:43:35.776427     135 upgradeaware.go:401] Error proxying data from backend to client: tunnel disconnect
W0819 08:43:35.776709     135 reflector.go:442] pkg/mod/github.com/rancher/client-go@v1.22.3-rancher.1/tools/cache/reflector.go:168: watch of *v1.Role ended with: an error on the server ("unable to decode an event from the watch stream: tunnel disconnect") has prevented the request from succeeding
W0819 08:43:35.776744     135 reflector.go:442] pkg/mod/github.com/rancher/client-go@v1.22.3-rancher.1/tools/cache/reflector.go:168: watch of *v1.StatefulSet ended with: an error on the server ("unable to decode an event from the watch stream: tunnel disconnect") has prevented the request from succeeding
W0819 08:43:35.776760     135 reflector.go:442] pkg/mod/github.com/rancher/client-go@v1.22.3-rancher.1/tools/cache/reflector.go:168: watch of *v1.Node ended with: an error on the server ("unable to decode an event from the watch stream: tunnel disconnect") has prevented the request from succeeding
W0819 08:43:35.779080     135 reflector.go:442] pkg/mod/github.com/rancher/client-go@v1.22.3-rancher.1/tools/cache/reflector.go:168: watch of *v1.ReplicaSet ended with: an error on the server ("unable to decode an event from the watch stream: tunnel disconnect") has prevented the request from succeeding
2022/08/19 08:43:35 [INFO] Shutting down management.cattle.io/v3, Kind=SamlToken workers
2022/08/19 08:43:35 [INFO] Shutting down management.cattle.io/v3, Kind=GlobalDnsProvider workers
2022/08/19 08:43:35 [INFO] Shutting down management.cattle.io/v3, Kind=ClusterAlert workers
2022/08/19 08:43:35 [INFO] Shutting down management.cattle.io/v3, Kind=Notifier workers
2022/08/19 08:43:35 [INFO] Shutting down apps/v1, Kind=Deployment workers
2022/08/19 08:43:35 [INFO] Shutting down management.cattle.io/v3, Kind=ClusterAlertGroup workers
2022/08/19 08:43:35 [INFO] Shutting down admissionregistration.k8s.io/v1, Kind=ValidatingWebhookConfiguration workers
2022/08/19 08:43:35 [INFO] Shutting down /v1, Kind=ReplicationController workers
2022/08/19 08:43:35 [INFO] Shutting down /v1, Kind=Pod workers
2022/08/19 08:43:35 [INFO] Shutting down catalog.cattle.io/v1, Kind=Operation workers
2022/08/19 08:43:35 [INFO] Shutting down management.cattle.io/v3, Kind=GlobalRole workers
2022/08/19 08:43:35 [INFO] Shutting down batch/v1beta1, Kind=CronJob workers
2022/08/19 08:43:35 [INFO] Shutting down management.cattle.io/v3, Kind=CisBenchmarkVersion workers
2022/08/19 08:43:35 [INFO] Shutting down management.cattle.io/v3, Kind=GlobalRoleBinding workers
2022/08/19 08:43:35 [INFO] Shutting down catalog.cattle.io/v1, Kind=ClusterRepo workers
2022/08/19 08:43:35 [INFO] Shutting down networking.k8s.io/v1, Kind=Ingress workers
2022/08/19 08:43:35 [INFO] Shutting down management.cattle.io/v3, Kind=ProjectRoleTemplateBinding workers
2022/08/19 08:43:35 [INFO] Shutting down management.cattle.io/v3, Kind=UserAttribute workers
2022/08/19 08:43:35 [INFO] Shutting down management.cattle.io/v3, Kind=Cluster workers
2022/08/19 08:43:35 [INFO] Shutting down /v1, Kind=Namespace workers
2022/08/19 08:43:35 [INFO] Shutting down project.cattle.io/v3, Kind=SourceCodeRepository workers

**Comment by saxonredhat** [comment]
2022/08/19 08:43:35 [INFO] Shutting down /v1, Kind=ConfigMap workers
2022/08/19 08:43:35 [INFO] Shutting down management.cattle.io/v3, Kind=RkeAddon workers
2022/08/19 08:43:35 [INFO] Shutting down fleet.cattle.io/v1alpha1, Kind=Cluster workers
2022/08/19 08:43:35 [INFO] Shutting down monitoring.coreos.com/v1, Kind=ServiceMonitor workers
2022/08/19 08:43:35 [INFO] Shutting down apiregistration.k8s.io/v1, Kind=APIService workers
2022/08/19 08:43:36 [INFO] Creating token for user user-bgknd
2022/08/19 08:43:37 [INFO] error in remotedialer server [400]: websocket: close 1006 (abnormal closure): unexpected EOF
2022/08/19 08:43:37 [INFO] Cluster API is started
2022/08/19 08:43:37 [FATAL] leaderelection lost for cattle-controllers
2022/08/19 08:44:33 [INFO] Listening on /tmp/log.sock
2022/08/19 08:44:33 [INFO] Rancher version v2.6.3 (3c1d5fac3) is starting
2022/08/19 08:44:33 [INFO] Rancher arguments {ACMEDomains:[] AddLocal:true Embedded:false BindHost: HTTPListenPort:80 HTTPSListenPort:443 K8sMode:auto Debug:false Trace:false NoCACerts:false AuditLogPath:/var/log/auditlog/rancher-api-audit.log AuditLogMaxage:10 AuditLogMaxsize:100 AuditLogMaxbackup:10 AuditLevel:0 Features: ClusterRegistry:}
2022/08/19 08:44:33 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6443/version?timeout=15m0s": dial tcp 127.0.0.1:6443: connect: connection refused
2022/08/19 08:44:35 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6443/version?timeout=15m0s": dial tcp 127.0.0.1:6443: connect: connection refused
2022/08/19 08:44:37 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6443/version?timeout=15m0s": dial tcp 127.0.0.1:6443: connect: connection refused
2022/08/19 08:44:39 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6443/version?timeout=15m0s": dial tcp 127.0.0.1:6443: connect: connection refused
2022/08/19 08:44:40 [FATAL] startup canceled

**Comment by saxonredhat** [comment]
@ereslibre @steved @phillc @flavio  help me

**Comment by cbron** [comment]
Please open an issue with all provide template details. Issues without that information will be closed. Please also include host CPU/memory information.
