### ISSUE TITLE
Validation for cert-manager v1.8 - v1.7 is EOL (Jul 22, 2022)

### ISSUE THREAD

**Issue by sphr2k** [rancher/rancher#38678]
Cert-manager 1.7.x is EOL since Jul 22, 2022; requesting validation for cert-manager 1.8

Ref: #36693

**Comment by jonathon2nd** [comment]
For a workaround we used this: https://medium.com/@michael_33280/fixing-current-release-manifest-contains-removed-kubernetes-api-s-da6d948b651d 

Only one instance updated, after that was able to upgrade.

**Comment by sphr2k** [comment]
The issue is still relevant
