### ISSUE TITLE
[BUG] Rancher container keeps restarting on Ubuntu 22.04.1

### ISSUE THREAD

**Issue by Niall-Scott** [rancher/rancher#38680]
Rancher Server Setup
- Rancher version: 2.6.7
- Installation option (Docker install/Helm Chart): Docker Install 20.10.12

Describe the bug

Rancher container restarts within a minute of starting, please see logs below:
```
INFO: Running k3s server --cluster-init --cluster-reset
2022/08/20 18:18:34 [INFO] Rancher version v2.6.7 (e5c6f0f6a) is starting
2022/08/20 18:18:34 [INFO] Rancher arguments {ACMEDomains:[] AddLocal:true Embedded:false BindHost: HTTPListenPort:80 HTTPSListenPort:443 K8sMode:auto Debug:false Trace:false N
2022/08/20 18:18:34 [INFO] Listening on /tmp/log.sock
2022/08/20 18:18:34 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused
2022/08/20 18:18:36 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused
2022/08/20 18:18:38 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused
2022/08/20 18:18:40 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused
2022/08/20 18:18:42 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused
2022/08/20 18:18:44 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused
2022/08/20 18:18:46 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused
2022/08/20 18:18:48 [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused
2022/08/20 18:19:03 [INFO] Running in single server mode, will not peer connections
2022/08/20 18:19:03 [INFO] Applying CRD features.management.cattle.io
2022/08/20 18:19:04 [INFO] Applying CRD navlinks.ui.cattle.io
2022/08/20 18:19:04 [INFO] Applying CRD clusters.management.cattle.io
2022/08/20 18:19:04 [INFO] Applying CRD apiservices.management.cattle.io
2022/08/20 18:19:04 [INFO] Applying CRD clusterregistrationtokens.management.cattle.io
2022/08/20 18:19:05 [INFO] Applying CRD settings.management.cattle.io
2022/08/20 18:19:05 [FATAL] k3s exited with: exit status 1

```

**To Reproduce**
Clean install of Ubuntu 22.04.1
Install Docker - `sudo apt install -y docker.io`
Start and enable docker - `sudo systemctl start docker`  then `sudo systemctl enable docker`
Install Rancher - `docker run -d --name=rancher-server --restart=unless-stopped -p 80:80 -p 443:443 --privileged rancher/rancher:latest`

**Result**
UI does not load and this message is in the logs:
` [INFO] Waiting for server to become available: Get "https://127.0.0.1:6444/version?timeout=15m0s": dial tcp 127.0.0.1:6444: connect: connection refused`

**Expected Result**
UI to be available by navigating to HTTPS://<machine_ip>

**Additional context**
This issue does not occur on Rancher v2.4.18 in exactly the same setup.  Changing the install command to the below is a workaround:
 `docker run -d --name=rancher-server --restart=unless-stopped -p 80:80 -p 443:443 --privileged rancher/rancher:v2.4.18`

**Comment by justSem** [comment]
There's  a temporary fix for this as addressed in #36238 
On 22.04 edit `/etc/default/grub` and add the line:
`GRUB_CMDLINE_LINUX="cgroup_memory=1 cgroup_enable=memory swapaccount=1 systemd.unified_cgroup_hierarchy=0"`

Then run `sudo update-grub` and `reboot`

**Comment by Niall-Scott** [comment]
Excellent thank you the work around worked nicely

**Comment by kinarashah** [comment]
Closing to track here https://github.com/rancher/rancher/issues/36238
