### ISSUE TITLE
[Cattle]the --connect-timeout is too short

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#3868]
@fly2wind issue:

in my network environment, resolving the DNS need more than 3 seconds.
```
curl --connect-timeout 3 -L 'https://github.com/rancherio/host-api/releases/download/v0.17.0/host-api.tar.gz?current='
curl: (28) Resolving timed out after 3520 milliseconds
```

Error logs:
```
[scripts.sh:59] call_curl -L 'https://github.com/rancherio/host-api/releases/download/v0.17.0/host-api.tar.gz?current='
[scripts.sh:43] local 'curl=curl -s --connect-timeout 3'
[scripts.sh:44] '[' false = false ']'
[scripts.sh:45] curl -s --connect-timeout 3 -L 'https://github.com/rancherio/host-api/releases/download/v0.17.0/host-api.tar.gz?current='
[scripts.sh:1] cleanup
[config.sh:9] EXIT=28
[config.sh:11] '[' -e /var/lib/cattle/download.g8IjTfT ']'
[config.sh:12] rm -rf /var/lib/cattle/download.g8IjTfT
[config.sh:15] return 28
``` 

@ibuildthecloud: Never really considered this. Are you saying that DNS resolution is included in connect time? We can increase this timeout I think. I need to look back in the history to see if there was a specific reason why we set it so low.

@fly2wind: Yes, because access the s3 service is slow in my country (many times url redirect and dns lookup).

@Marcel-Hahn: i had the same issue on my local boot2docker test environment

my quick fix for the moment:
find /var/lib/docker/ -name "scripts.sh" -exec sed -i 's/connect-timeout 3/connect-timeout 42/g' {} \;

@ibuildthecloud: On master this has been changed to 20 seconds. The next release which should be within a week will include the change.

**Comment by deniseschannon** [comment]
@fly2wind: I've duplicated your issue in cattle to Rancher, but just noticed that @ibuildthecloud mentioned that it has been updated. Is this still an issue for you?

**Comment by fly2wind** [comment]
that issue has been solved.
