### ISSUE TITLE
[BUG]  "old" versions of EKS/AKS/GKE do not show up in the new Dashboard

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#38688]
**2.6.7-rc10**

- "old" / kev1 versions of EKS/AKS cluster deployed - are not seen on Cluster management and Home page. 
- They are however visible on Ember UI

**On 2.6.6**

- cluster -  "old" / kev1 versions of EKS/AKS-  in Prov state doesn't come up on the Cluster Management UI; But it shows up in the home page and in the side nav
- Cluster-  "old" / kev1 versions of EKS/AKS- in Prov state with a failure comes up on the Cluster Management UI

**Expected:**

As a user, i would expect all clusters to be listed in Cluster Management and Home page. - including EKS/AKS/GKE v1 prov (older versions of these hosted prov clusters)

**Comment by cpinjani** [comment]
**2.7.5-rc1**
- "old" / kev1 versions of EKS cluster deployed - seen on Cluster management and Home page.
- Visible on Ember UI as well

![image](https://github.com/rancher/rancher/assets/73099870/efacace6-f12b-4808-bdf2-3a779a4e2815)

![image](https://github.com/rancher/rancher/assets/73099870/aed46768-611b-4996-a2e1-6d2f468a84cd)

**Comment by kkaempf** [comment]
Thanks @cpinjani, closing as fixed
