### ISSUE TITLE
Branding configuration is not used anymore after update to Rancher 2.6.7

### ISSUE THREAD

**Issue by pwurbs** [rancher/rancher#38697]
**Rancher Server Setup**
- Rancher version: 2.6.7
- Installation option (Docker install/Helm Chart): Helm chart
- K8S: v1.22.11 / RKE1

**Information about the Cluster**
- Kubernetes version: v1.22.11
- Cluster Type (Local/Downstream): Local

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): Admin

**Describe the bug**
After update from Rancher 2.6.6 to 2.6.7, the Branding configuration under Global settings/Branding is not longer taken into account. Especially, the Primary Color and the Link Color is displayed with the default color in the Rancher UI even if it's configured with some special colors.

**To Reproduce**
- Configure your own color in Branding settings using Rancher 2.6.6, check that it's displayed correctly
- Update to rancher 2.6.7
- Refresh any Rancher UI page in the browser 
- Check the link and font colors, they are set to the default colors

**Expected Result**
The branding configuration should be used when rendering the pages also after update to Rancher 2.6.7

**Screenshots**

**Comment by xhejtman** [comment]
https://github.com/rancher/dashboard/issues/6704

**Comment by pwurbs** [comment]
Duplicate
