### ISSUE TITLE
Feature charts: Update Longhorn 1.3.1 chart in 2.6.7

### ISSUE THREAD

**Issue by rebeccazzzz** [rancher/rancher#38693]
Longhorn 1.3.1 needs an update to the feature charts in Rancher 2.6.7. We would like to do this by Thursday, September 1.

Probably need to make it OOB if need to release it earlier.
- Update 1.3.1 LH chart in feature chart - Cluster Manager/Rancher Marketplace

cc @khushboo-rancher @yasker @MKlimuszka @deniseschannon @meldafrawi @cchien816 @yangchiu @prachidamle @innobead

**Comment by prachidamle** [comment]
@rebeccazzzz Please let @aiyengar2 know when the PR for this update will be ready for review.

**Comment by PhanLe1010** [comment]
PR is ready for reviewing https://github.com/rancher/charts/pull/2058
cc @prachidamle and @aiyengar2

**Comment by PhanLe1010** [comment]
The chart was released. Probably we can close this ticket

**Comment by khushboo-rancher** [comment]
Longhorn v1.3.1 is validated on Rancher v2.6.8.
