### ISSUE TITLE
[BUG] Unable to interact with downstream clusters after upgrading from 2.5.15 to 2.5.16

### ISSUE THREAD

**Issue by junkiebev** [rancher/rancher#38699]
**Rancher Server Setup**
- Rancher version: 2.5.16
- Installation option: Helm Chart
   - RKE1, 1.20.4

**Information about the Cluster**
- Kubernetes version: 1.20.4
- Cluster Type: Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):
* Hosted =AKS

**User Information**
- What is the role of the user logged in? Admin

**Describe the bug**
Post upgrade 2.5.15 to 2.5.16, we are unable to communicate to any downstream AKS clusters (immediate 503 errors) though they appear green in the UI

**To Reproduce**
~Have registered AKS clusters in _any_ version of k8s. Upgrade 2.5.15 to 2.5.16~

1. Run rancher v2.6.3
2. Navigate to <server-url>/g/clusters/add/launch/azureaks
3. Create AKSv1 cluster using the UI.
4. Wait for cluster to become active.
5. Upgrade to v2.6.7.
6. Try to access workloads in system project of AKSv1 cluster. Agent will be outdated.
7. View rancher logs. Should see logs stating it is unavailable.

**Result**
When clicking on the cluster in Cluster Manager, an immediate 503 results
![image](https://user-images.githubusercontent.com/6684332/186246831-616dff65-f8e2-4cf0-b833-584bda50b972.png)

**Expected Result**
Cluster able to be interacted with

**Additional context**
I believe this has to do with changes to the cluster spec in 2.5.16 - all other providers (RKE on Azure, vSphere, custom, etc) clusters work, but it looks like the secrets migrator is tripping over itself.
`kubectl get clusters.management.cattle.io c-CLUSTERID` shows a `status.serviceAccountToken` rather than `status.serviceAccountTokenSecret` and fleet has all sorts of authentication errors.

Rancher support case 00359224 for reference.

**Comment by junkiebev** [comment]
Rancher support provided me a script to fix that - it's in the case I referenced.

**Comment by rmweir** [comment]
This was merged prior to 2.7 branching.

**Comment by rmweir** [comment]
Release note:
* A bug has been fixed that resulted in certain clusters being rendered unavailable after upgrade. This was due to improper migration of certain cluster fields to secrets. The known cluster types this affected were legacy AKS, GKE, and EKS clusters but may have affected other types of clusters as well.

**Comment by Napsty** [comment]
@junkiebev Would you mind sharing the solution on the 2.5.16 cluster? All notes after your initial report relate to 2.6.x, also the SUSE KB (https://www.suse.com/support/kb/doc/?id=000020910) shows a solution for 2.6.x.
