### ISSUE TITLE
Can't set minimum scaling to 0 for EKS node groups

### ISSUE THREAD

**Issue by Sahota1225** [rancher/rancher#38698]
When creating an EKS hosted cluster with nodegroups that have a min_size set to 0, we see the following error:
eks-config-operator-5dc8f6b488-xlbt6 eks-operator time="2021-07-14T12:25:58Z" level=error msg="error syncing 'cattle-global-data/c-4v22d': handler eks-controller: InvalidParameter: 1 validation error(s) found.\n- minimum field value of 1, CreateNodegroupInput.ScalingConfig.MinSize.\n, requeuing"

It looks like the rancher EKS operator is using an older version of the SDK. You can see in the newer version that the constraint has been removed: https://docs.aws.amazon.com/sdk-for-go/api/service/eks/#NodegroupScalingConfig

Note that there is an existing PR (https://github.com/rancher/eks-operator/pull/51/) that updates to SDK 1.40. At this time up to 1.44 is out, so we should attempt to update to the latest and see if there are any regressions.

SURE-3466

**Comment by sowmyav27** [comment]
@Josh-Diamond Please include these in your validations:

1. From rancher UI, you should be able to deploy an EKS with 0 nodes in node group. Cluster should come up successfully.
2. Edit ^^ this cluster and scale up the node group and the Cluster should come up successfully.
3. Deploy an EKS cluster with nodes. Edit cluster and scale down the nodes in node group to 0 and save changes. Verify the cluster comes up successfully
4. From EKS console, create an EKS with 0 nodes in node group. Verify user is able to import this cluster into Rancher successfully
5. Using TF, verify user are able to deploy an EKS with 0 nodes in node group. Cluster should come up successfully.
6. On 2.6.7, deploy an EKS cluster. Upgrade to 2.6head, edit cluster, and scale down the nodes in the EKS cluster to 0. Edit should be successful and cluster should come up Active.

**Comment by annablender** [comment]
@Josh-Diamond From the [AWS NodegroupScalingConfig docs](https://docs.aws.amazon.com/eks/latest/APIReference/API_NodegroupScalingConfig.html), `desiredSize` and `minSize` for a nodegroup can be 0 but `maxSize` cannot (min of 1). Keep this in mind for test steps 1 and 5. If you set the `maxSize=0` EKS will refuse to create the nodegroup.

**Comment by annablender** [comment]
Possible bug found

If an eks cluster is provisioned with a node group with 0 nodes, the cluster gets stuck in `Waiting for API to be available` in the rancher ui and never becomes active.
<img width="1181" alt="image" src="https://user-images.githubusercontent.com/12955547/186771675-4b66f608-619a-4ff8-87fc-f37ad26e2b79.png">

**Comment by annablender** [comment]
The above ^ behavior is expected, because if there are no nodes in a node group rancher has nowhere to run the cluster agent. What _is_ expected is that if a node group with 0 nodes is scaled back to have 1+ nodes, the cluster successfully reconnects in rancher. Testing

**Comment by annablender** [comment]
Additional test - Sergey

1. Initial test is to have 2 node groups with 1 node in each - confirm how those nodes are shown in the UI (are they both in “No node pool” bucket)?
2. Scale down one of node groups to 0 and confirm that the cluster is still connected OK and there is nothing obviously wrong with how it shows up in Rancher.
3. Scale it back to 1 and confirm everything is back to how it was at step #1.

Results

Step 1 - shows "Not in a Pool"
![6845a8439592a56399797e4367358a92.png](:/876d5ba69c1f4ad5bb2bbf5e415b05e8)

Step 2 - 0/1 nodes stay connected in rancher. 0/0 disconnects. Rancher needs at least 1 node in 1 node pool to stay connected
![055df24dd011eff12a3ff4bef0362ae8.png](:/99ca3ddf4d1d4326beab42e042b59090)

Step 3 - PASS
![d8cec8cda668114b70969d8bde3b24d7.png](:/0b53091e5432426798ca164747ec1720)

**Comment by Josh-Diamond** [comment]
Re-opening for QA validation

**Comment by Josh-Diamond** [comment]
Awaiting PR merge from [2056](https://github.com/rancher/charts/pull/2056) to begin QA validation

**Comment by Josh-Diamond** [comment]
W.I.P. - 8/31/22

With Docker on a single-node instance:

Reproduced on rancher `v2.6.8`:

---

Verified on rancher `v2.6-3e5fb4a537731df7ed96cc9ddae6a3902a57c8b1-head`:
1. Fresh install of rancher `v2.6-head`
2. As admin, create a standard user
3. As standard user, provision a downstream EKS cluster w/ desired_size=0, max_size=1, min_size=0, from rancher UI
4. Logout as standard user, log in as admin
5. As admin, verify eks operator version
6. Verified - `rancher/eks-operator:v1.1.5-rc1`
7. Logout Admin. login as standard user
8. Verified - EKS cluster provisioned w/ desired_size=0, max_size=1, min_size=0, remains in `waiting` state
9. `Edit Config` and scale up node group
10. Verified - cluster comes up `active`
11. As standard user, provision a downstream EKS cluster w/ desired_size=2, max_size=2, min_size=0, from rancher UI
12. Verified - Cluster successfully provisions
13. `Edit Config` and scale node groups to 0; - [ desired_size=0, max_size=1, min_size=0 ]
14. Verified - Cluster goes into `Unavailable` state; `cluster agent is not connected`
15. `Edit Config` and scale node groups back up
16. Verified - Cluster comes up `active` with nodes
17. From EKS Console, create a cluster with no node groups and import it into rancher
18. Veri-FAILED - Cluster in error state; `Failed to communicate with cluster: Unauthorized`
19. Terraform Test Case - In Progress

**Comment by annablender** [comment]
Added a UI enhancement issue to warn users of new behavior.

**Comment by annablender** [comment]
This was merged prior to 2.7 branching in the rancher/rancher repo.
