### ISSUE TITLE
[BUG] Authentication provider fails after migration to Microsoft Graph API endpoint

### ISSUE THREAD

**Issue by disparo13** [rancher/rancher#38724]
**Rancher Server Setup**
- Rancher version:` 2.6.7`
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): `Helm chart, EKS 1.23`
- Proxy/Cert Details: AWS Certificate

**Information about the Cluster**
- Kubernetes version: `1.23.7`
- Cluster Type (Local/Downstream): Local

**User Information**
- What is the role of the user logged in? `Admin`

**Describe the bug**
After pushing the button "Update Endpoint" or trying to manually edit the Custom config AzureAD provider fails with an error "server error while authenticating: missing required permissions from Microsoft Graph: need Group.Read.All, User.Read.All" despite all the required permissions been set. 

**To Reproduce**
Check that we have the needed permissions: Microsoft Graph: Group.Read.All, User.Read.All in the app from Azure Portal. Mine also has Directory.AccessAsUser.All, Directory.Read.All, User.Read, User.ReadBasic.All

1. On Rancher v2.6.6, set the Azure AD auth from Users & Auth >> Auth providers >> Azure AD
2. Upgrade to Rancher v.2.6.7.
3. In the Rancher UI homepage, make note of the banner at the top of screen that advises users to update their Azure AD authentication. Click on the link provided to do so, then push the "Update Endpoint" button.

Or: 
3. In the Rancher UI homepage, make note of the banner at the top of screen that advises users to update their Azure AD authentication click "Edit Config".
4. Provide the endpoints - Endpoint, Graph Endpoint, Token Endpoint and Auth Endpoint by providing the old graph endpoint values:
Endpoint: https://login.microsoftonline.com/
Graph end point:  https://graph.microsoft.com
Auth end point: https://login.microsoftonline.com/{tenantID}/oauth2/authorize
Token end point: https://login.microsoftonline.com/{tenantID}/oauth2/token
6. Provide the required tenant ID, Client ID and Secret
7. Save the config

**Result**
You will no longer be able to login using the AD account at all or will see error "`server error while authenticating: missing required permissions from Microsoft Graph: need Group.Read.All, User.Read.All`", and configuration won't save.

**Expected Result**
Authentication provider works after migration to the new endpoint.

**Comment by maxsokolovsky** [comment]
@disparo13, does your app registration have Application (not Delegated) permissions to read all Groups and Users?

**Comment by disparo13** [comment]
@maxsokolovsky It has "Delegated" type of permissions, even on Rancher docs screenshots I see "Delegated" type
https://rancher.com/docs/img/rancher/select-req-permissions.png

With standard endpoints it doesn't work as well.

**Comment by maxsokolovsky** [comment]
@disparo13, that screenshot belongs to a series of screenshots, the first one shows the app without the two configured permissions, the next screenshots show how to add the two Application permissions. And the banner also says to configure Application permissions.

**Comment by gisyrus** [comment]
Hi @maxsokolovsky, please try to remove the User.Read.All and Group.Read.All (with Delegated) first in your API permissions. Then add it back to your API permissions with the admin consent. This works for my Rancher v2.6.7

**Comment by gisyrus** [comment]
And seems it's a duplicate of #38673

**Comment by maxsokolovsky** [comment]
@gisyrus, the permissions should be Application. If you also have the Delegated set, that's fine as long as you have the Application set. You may not immediately see the effect of these changes because the access token from Azure (stored in a secret called `azuread-access-token`) is cached for about an hour. Even if it has insufficient or wrong permissions, it's still cached. You can delete that secret and try again or wait until a token refresh will try to fetch a new token with the right permissions.

**Comment by gisyrus** [comment]
@maxsokolovsky Yes I got your solution worked. Comments below are to further illustrate your approach about refresh the token manually by deleting the access-token and re-enable the AzureAD:

From the cluster which installed Rancher, find out the `azuread-access-token` in `cattle-global-data`. It is probably the cached access token.
![image](https://user-images.githubusercontent.com/44492082/186966652-422efafc-31d7-413f-9af1-039226a9ad85.png)
Delete `azuread-access-token` and try to re-enable the AzureAD auth provider with the **User.Read.All** and **Group.Read.All** **Application** permissions.

Thank you very much for the help! And my last question is that the change of Graph Endpoint lead to this change of API permissions?

**Comment by maxsokolovsky** [comment]
@gisyrus, the Graph Endpoint change is just a part of the larger change. We are also moving from the Delegated model to the Application model, where the access token from the new Microsoft Graph API is granted only to the service account (the app registration) and not to each user in Azure, as before.

**Comment by codecae** [comment]
FWIW:

I had this issue and later found that if there any API permissions existing on the app registration beyond Application scoped Group.Read.All and User.Read.All (including the same permissions with delegated scope), this error occurs.  Only removing ALL OTHER permissions except Application Scoped Group.Read.All and User.Read.All solved this issue for me.

To me, this feels like an unwarranted exception.  Just because other permissions exist does not mean the ones that are required do not. Would be nice if this error didn't occur when the proper permissions exist with others.  Some organizations may share app registrations with other endpoints sharing similar scope and API requirements.

**Comment by disparo13** [comment]
Changing the type of permissions from "Delegated" to "Application" resolved the situation. I'm closing the issue.

**Comment by maxsokolovsky** [comment]
@codecae, I had tried having other unneeded permissions (alongside the required ones) on the app registration before and did not have that issue. Additional permissions are fine and should not affect anything. I wonder if you had a bad token cached? Could you delete the `azuread-access-token` secret and try again?

**Comment by maxsokolovsky** [comment]
@cdtzabra, yes, this makes sense. If you want to update the Azure AD setup of an existing Terraform deployment, then you need to update the auth config values as described in this table in the docs (old vs new).
https://rancher.com/docs/rancher/v2.6/en/admin-settings/authentication/azure-ad/#global

Most importantly, you will need to set the `annotations` argument to contain the key-value pair `auth.cattle.io/azuread-endpoint-migrated: true`.

Please let me know if this helps. I will try to test it too.

**Comment by maxsokolovsky** [comment]
@zabra, about the Terraform resource - we will update the provider docs and mention that admins who set up Azure AD with Terraform would need to update the configuration in the UI (which will prompt them on every screen).
Then they will need to change the endpoints as per docs in their TF code to avoid state drift.
This is relevant for setups which were created before v2.6.7 but which had the underlying Rancher image updated to v2.6.7+.

(I deleted my original response when I looked into this deeper, not sure what happened to your original note, though.)
