### ISSUE TITLE
[BUG] Docker installed airgap env, fails to provision downstream rke2/k3s custom clusters

### ISSUE THREAD

**Issue by Josh-Diamond** [rancher/rancher#38733]
**Rancher Server Setup**
- Rancher version: `v2.6.7`
- Installation option (Docker install/Helm Chart): `Docker Air-Gapped Env`
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details: `byo-valid`

**Information about the Cluster**
- Kubernetes version: `v1.24.2+k3s2` - [any rke2/k3s k8s version will reproduce issue]
- Cluster Type (Local/Downstream):
Downstream rke2/k3s custom cluster

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
Admin

**Describe the bug**
When attempting to provision a downstream rke2/k3s custom cluster on a Docker installed Air-gapped env, error is seen on `Cluster Details` page where registration command is found.

**To Reproduce**
1. Docker installed air-gapped env w/ rancher v2.6.7 - [ i used jenkins ]
2. As admin, `Create` new cluster, select `rke2/k3s` Custom cluster
3. Name cluster, select k8s version 1.24.2+k3s2 - [ any version will reproduce ] - add registry [auth or no auth; doesn't matter, issue will reproduce]
4. Select `Create` in bottom-right corner of rancherUI
5. Reproduced - [when ignoring error and attempting to register nodes anyway, cluster does NOT provision; hangs in error state]

**Result**
Rancher encounters the following error:

```logs
failed to create fleet-default/jkeslar-authh cluster.x-k8s.io/v1beta1, Kind=Cluster for rke-cluster fleet-default/jkeslar-authh: Internal error occurred: failed calling webhook "default.cluster.cluster.x-k8s.io": failed to call webhook: Post "https://webhook-service.cattle-system.svc:443/mutate-cluster-x-k8s-io-v1beta1-cluster?timeout=10s": service "webhook-service" not found
```

**Expected Result**
No error is seen and provisioning cluster is successful

**Screenshots**
<img width="1420" alt="docker w: auth" src="https://user-images.githubusercontent.com/46494969/186780562-98ad0ec6-c555-4d07-8501-6750097b8ace.png">

<img width="1411" alt="docker w: auth 2" src="https://user-images.githubusercontent.com/46494969/186780587-68a42499-d946-4405-83a5-9cf3b8399640.png">

**Additional context**
Issue not seen with HA air-gapped env; Docker air-gapped specific
Also, issue not seen w/ RKE1 custom clusters on Docker air-gapped env; RKE2/K3s custom specific

**Comment by sowmyav27** [comment]
this isn't an issue. this is a limitation with how QA's docker installed airgap setups are deployed
