### ISSUE TITLE
[BUG]  Istio-cni-node daemonset is unavailable (broken) when CIS 1.6 profile is enabled in RKE2 config.yaml

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#38732]
**Rancher Server Setup**
Rancher Cluster:
Rancher version: Rancher 2.6.4
Number of nodes:
Node OS version:

Downstream Cluster:
Number of Downstream clusters:
Node OS:
RKE/RKE2/K3S version:
Kubernetes version:
CNI:

Longhorn:
Longhorn version:
CPU per node:
Memory per node:
Disk type: HDD/SSD/NVMe
Network bandwidth between the nodes:

Other:
Underlying Infrastructure: AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:

**Issue description:**
Istio-cni-node daemonset is unavailable (broken) when CIS 1.6 profile is enabled in RKE2 config.yaml

**Business impact:**
Users have to manually add the privileged: true to the psp-istio-cni when CIS 1.6 is enabled. Users are wondering if this is being worked on such that a manual modification to the psp-istio-cni is not necessary.

**Troubleshooting steps:**
I attempted the same installation on an RKE2 cluster without "profile: CIS 1.6" enabled and did not have this same error. This seems to be only an issue when CIS benchmarks are applied. When testing on an RKE2 cluster with the CIS profile flag, the customer and I had to add "privileged: true" on the PSP for the daemonset to create. The configuration of the PSP is below:

apiVersion: policy/v1beta1 
kind: PodSecurityPolicy 
metadata: 
  annotations: 
    meta.helm.sh/release-name: rancher-istio 
    meta.helm.sh/release-namespace: istio-system 
    creationTimestamp: "2022-05-02T18:11:22Z" 
  labels: 
    app.kubernetes.io/managed-by: Helm 
    name: psp-istio-cni 
    resourceVersion: "6159" 
    uid: xxxxxxxxxxx (see original report)
spec: 
  allowPrivilegeEscalation: true 
  fsGroup: 
    rule: RunAsAny 
  hostNetwork: true 
  privileged: true # <-- had to add this 
  runAsUser: 
    rule: RunAsAny 
  seLinux: 
    rule: RunAsAny 
  supplementalGroups: 
    rule: RunAsAny 
  volumes: 
  - secret 
  - configMap 
  - emptyDir 
  - hostPath 

(roughly reformatted, as formatting is lost in case)

The above change allowed the psp-istio-cni daemonset to become available and Istio worked as expected.

Repro steps:

Step 1: Installed Centos 7.9
Step 2: Ensured SELinux was enforcing
Step 3: Install RKE2v1.21.7+rke2r2 on a 1 node cluster w/ CIS 1.6 profile enabled in config.yaml
Step 4: Install Rancher 2.6.4
Step 5: Install Istio Chart version 100.1.2+up1.11.7 through the Rancher UI (following the instructions from Rancher documentation: https://rancher.com/docs/rancher/v2.6/en/istio/configuration-reference/rke2/a)

    Select Customize Helm Chart option
    Enabled CNI under "Components"
    Added the custom overlay file under "Custom Overlay File" from https://rancher.com/docs/rancher/v2.6/en/istio/configuration-reference/rke2/
    (Changed the image: rancher/mirrored-istio-install-cni:1.9.3 to 1.10.4, as that is what the customer was using)
    Clicked install

Workaround:
Is workararound available and implemented? yes
What is the workaround: editing daemonset yaml as outlined above

Actual behavior:
[root@ip-xxxxxx]# k get ds -A
NAMESPACE NAME DESIRED CURRENT READY UP-TO-DATE AVAILABLE NODE SELECTOR AGE
istio-system istio-cni-node 0 0 0 0 0 kubernetes.io/os=linux 11m

Expected behavior:

[root@ip-xxxxxxxx]# k get ds -A
NAMESPACE NAME DESIRED CURRENT READY UP-TO-DATE AVAILABLE NODE SELECTOR AGE
istio-system istio-cni-node 1 1 1 1 1 kubernetes.io/os=linux 131m

[root@ip-xxxxxxxx]# k get pods -n istio-system
NAMESPACE NAME READY STATUS RESTARTS AGE
istio-system istio-cni-node-ndt4m 1/1 Running 0 129m

Files, logs, traces:
See original report

Additional notes:
The original ticket the customer inputted is below, to provide further context: We could not successfully deploy istio to an RKE2 cluster (v1.21.7+rke2r2) with the cis-1.6 benchmark applies and a default restricted pod security policy. We followed the special instructions here: https://rancher.com/docs/rancher/v2.6/en/istio/configuration-reference/rke2/ But the istio-cni-node daemonset would not successfully deploy due to insufficient privilege. We were able to make the deployment successful by manually editing the psp-istio-cni pod security policy and adding ‘privileged: true’ (allowing privileged containers). It seems that the custom overlay from the link above introduces the following patch line for deployment: - path: spec.template.spec.containers.[name:install-cni].securityContext.privileged And this creates the requirement for manual modification we had to make. Is this a known issue? If so, is this being worked such that a manual modification to the to the psp-istio-cni is not necessary?Edit Description

SURE-4582

**Comment by rayandas** [comment]
The issue doesn't appear on latest Rancher (RKE2 Hardened) and Istio versions.
Tested on:
- Rancher: v2.7.0-rc4
- K8s: v1.24.6+rke2r1
- rancher-istio: 101.0.0+up1.14.3
- istio-cni-node: rancher/mirrored-istio-install-cni:1.14.3-distroless

**Fix:** 
After creating an RKE2 hardened cluster (with Restricted PSP), as per [Enable Istio with Pod Security Policies](https://docs.ranchermanager.rancher.io/explanations/integrations-in-rancher/istio/configuration-options/pod-security-policies), Set the PSP to unrestricted in the project where is Istio is installed, or the project where you plan to install Istio, else Istio may not function correctly with restricted PSP. Follow the guide mentioned [here](https://docs.ranchermanager.rancher.io/explanations/integrations-in-rancher/istio/configuration-options/pod-security-policies#1-set-the-podsecuritypolicy-to-unrestricted). Then install Istio with CNI enabled and a custom overlay file.

**Comment by mitulshah-suse** [comment]
Closing this based on the comments on the associated JIRA issue.
