### ISSUE TITLE
kubelogin getting 401 unauthorized when authenticating downstream clusters

### ISSUE THREAD

**Issue by mrlnstpn** [rancher/rancher#38739]
All our AKS clusters are AAD RBAC enabled and we are using kubelogin for authentication to manage our clusters (via Terraform). It works for local cluster, I could create a namespace and even run helm_release (using helm provider block with the same exec plugins).  

However, for some reason it's not working when I'm trying to hit downstream clusters, trace logs says **401 Unauthorized**. The service principal we're using has the same role assignment for all our clusters. What could be the issue? All clusters are created via Terraform hence all configs/k8 versions are similar. 

`provider "kubernetes" {
  host                   = https://rancher.main.net/k8s/clusters/local"
  cluster_ca_certificate = file("./ca-issuer.cer")
  exec {
    api_version = "client.authentication.k8s.io/v1beta1"
    command     = "kubelogin"
    args = [
      "get-token",
      "--login", "spn",
      "--environment", "AzurePublicCloud",
      "--server-id", "6dae42f8-4368-4678-94ff-3960e28e3630",
      "--tenant-id", "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
      "--client-id", "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
      "--client-secret", "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    ]
  }
}`

**Comment by Syntax3rror404** [comment]
is this a similar problem?

https://github.com/rancher/rancher/issues/38016

**Comment by mrlnstpn** [comment]
> is this a similar problem?
> 
> #38016

It could be. I'm using kubelogin to authenticate via service principal's secret not via rancher's API token.
