### ISSUE TITLE
[BUG] Rancher provisioned RKE2 cluster agent always crashes in multi-node cluster environment

### ISSUE THREAD

**Issue by masteryyh** [rancher/rancher#38734]
**Rancher Server Setup**
- Rancher version: 2.6.7
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): k3s v1.24.3+k3s1
- Proxy/Cert Details: Let's Encrypt E1 Certificate

**Information about the Cluster**
- Kubernetes version: v1.22.11+rke2r1 (multiple version tested and every one of them fails)
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Custom (on-premise installation)

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Admin

**Describe the bug**

Multiple `cattle-cluster-agent` pod scheduled on the same node and because of occupied port only one pod can survive and other pods stays in `CrashLoopBackoff`.

**To Reproduce**

1. Install a local k3s cluster for rancher installation;
2. Install rancher using helm chart;
3. Use rancher to create a new RKE2 cluster;
4. Use command given by rancher to initialize more than one nodes, including control plane and workers;
5. `kubectl get pods -n cattle-system` and see crushing `cattle-cluster-agent` pods were all scheduled to the same node;
6. `kubectl logs cattle-cluster-agent-blah-blah -n cattle-system` will see a message saying `address already in use`.

**Result**

Cluster will always be stuck in `Reconcile` or `Updating` state.

**Expected Result**

Cluster created and provisioned without any issue.

**Workaround**
1. Scale the deployment `cattle-cluster-agent` to 0 replica by `kubectl scale deployment cattle-cluster-agent -n cattle-system --replicas=0`;
2. Scale back the deployment to the desired replicas and wait kubernetes to schedule those pods to those nodes.

**Additional context**

If I'm reading this correct, this `cattle-cluster-agent` deployment were used for nodes to communicate with upstream rancher, and multiple instance of agent is not possible because of occupied port. Why not use `DaemonSet` instead of `Deployment` to achieve this goal?

**Comment by niusmallnan** [comment]
@masteryyh There are two kinds of rancher agents in the downstream cluster: cluster-agent and node-agent.

- The cluster-agent is used to proxy the k8s API, it has steve built in, and will run some controllers.
- The node-agent is used to manage the node and execute the node plan issued by Rancher.

The cluster-agent is not necessary to use `DaemonSet`, the reason you see 2 replicas is because cluster-agent HA was added in 2.6.

You can check it out based on the clues here

https://github.com/rancher/rancher/blob/6239a857b1fbb22a4745f3dc54c6ac23bef98b39/pkg/systemtemplate/template.go#L117

**Comment by masteryyh** [comment]
@niusmallnan Thanks. I think I missed a point in the description, is that I edited the deployment with the content below:
```
hostNetwork: true
dnsPolicy: None
dnsConfig:
  nameservers:
      - 192.168.31.254    # which is my self hosted DNS server
```
because of [this](https://github.com/rancher/rancher/issues/16454) issue. So my rancher is using a domain that resolves only on my private DNS server and `cattle-cluster-agent` pods are trying to resolve this domain using in-cluster CoreDNS and public DNS like `8.8.8.8` which is not possible to resolve a private domain, so I'm using a workaround mentioned in that issue, which will solve this problem but also brings another problem about occupied port.
