### ISSUE TITLE
[BUG] GKE hosted clusters are not able to be deployed on k8s 1.23+, error : `Googleapi: Error 400: Creation of node pools using node images based on Docker container runtimes is not supported in GKE v1.23+ clusters as Dockershim has been removed in Kubernetes v1.24., badRequest`

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#38743]
**Rancher Server Setup**
- Rancher version: v2.6.7
- Installation option (Docker install/Helm Chart): docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): n/a
- Proxy/Cert Details: self signed

**Information about the Cluster**
- Kubernetes version: 1.23, 1.24
- Cluster Type (Local/Downstream): downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): hosted, GKE

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: tested as standard user, applies to all (admin included) users

**Describe the bug**
GKE hosted clusters are not able to deploy through rancher when using 1.23 or 1.24 due to the dockershim dependency.  GKE appears to have removed support for it as of 1.23 citing the deprecation soon to come (at the time) in 1.24

**To Reproduce**
* through rancher, deploy a GKE hosted cluster on k8s 1.23 or 1.24

**Result**
user is presented with an error shortly after clicking "create" citing the dockershim changes in 1.24

**Expected Result**
We should still be able to deploy GKE clusters on 1.23+ through rancher. 

**Screenshots**

**Additional context**
1.22 and below appear to still work as expected.

**Comment by annablender** [comment]
Known major issue has been added to GKE release notes for 2.6.8 in [this PR](https://github.com/rancherlabs/release-notes/pull/266) by @jtravee. This is fine for now, but the rancher backend needs to be fixed to set the containerd runtime as default for all GKE 1.23+ clusters.

Backend issue: [#38750](https://github.com/rancher/rancher/issues/38750)
UI issue: [#6769](https://github.com/rancher/dashboard/issues/6769)

Thank you @markusewalker

**Comment by snasovich** [comment]
This issue has been superseded with other issues as per https://github.com/rancher/rancher/issues/38743#issuecomment-1231618092.
