### ISSUE TITLE
Rancher Server High Availability Update

### ISSUE THREAD

**Issue by 5an1ty** [rancher/rancher#3874]
I tried rancher half a year ago and immediately fell in love with what rancher was and where it was heading. Fast forward to today and I was hoping on a little more progress on the high availability setup.

I have read the existing guide you have on: http://docs.rancher.com/rancher/installing-rancher/installing-server/multi-nodes/

And besides the setup work (I don't really mind), this just externalises safety concerns to a self run MYSQL, Redis, Zookeeper environment. unless you manually maintain a HA cluster of each of those yourself.

A way nicer solution would be to run these as containers on each of the Rancher servers. Making them all aware of each other and with constant replication/mirroring.

**Comment by ibuildthecloud** [comment]
Gimme a week, you'll get your wish :)

**Comment by ibuildthecloud** [comment]
@5an1ty I'll update this issue when we publish our new HA setup, but we fully managed everything except the DB.  I'm sure we'll manage the DB too eventually, but just not right now.

**Comment by 5an1ty** [comment]
@ibuildthecloud amazing! Seriously, I'm so ready to start using Rancher in production!

Have you given any consideration to other DB software btw? I'm thinking RethinkDB or Cassandra, something with HA concerns built in.

I'm wondering, could I set up two RancherOS servers both running rancher server. And run some kind of HA mysql setup on the both of them as docker images?

On a side note, SSL support for the rancher servers is on the way as well right?

I've been hyped about rancher for so long, I just can't wait :smile:!

**Comment by ibuildthecloud** [comment]
![](https://i.imgflip.com/10i0i6.jpg)

**Comment by taketnoi** [comment]
+1 for the picture

**Comment by revett** [comment]
@ibuildthecloud looking forward to the new release as we are trying to migrate from Docker Cloud.

Is there an ETA? :+1:

**Comment by vincent99** [comment]
End of the month.

**Comment by 5an1ty** [comment]
![](http://i.imgur.com/4ecMgb2.gif)

**Comment by j** [comment]
@ibuildthecloud any documentation on the new HA setup?  I was just going through the steps on the site until I saw this post. :)

**Comment by deniseschannon** [comment]
We'll actually have it out with our v1.0.1 release. Stay tuned!

**Comment by cuiyz** [comment]
@deniseschannon Sure about that? When will be the v1.0.1 release?

**Comment by deniseschannon** [comment]
@cuiyz Today's Rancher meetup covers HA and so this will definitely be in v1.0.1. We're hoping to push out 1.0.1 in the next week.

**Comment by flaccid** [comment]
@deniseschannon if you could also let us know when http://docs.rancher.com/rancher/installing-rancher/installing-server/multi-nodes/ is fully updated for HA, most appreciated!

**Comment by SydOps** [comment]
I have gone through the video https://www.youtube.com/watch?v=hwhxXwT6zlw, looks great. 

I am also waiting for the latest released v1.0.1.

By the way, if I try to build latest rancher/server image  by myself, any instructions for it?

**Comment by LLParse** [comment]
Tests pass in v1.0.1-rc5, thanks @ibuildthecloud !

**Comment by deniseschannon** [comment]
@flaccid @SydOps As soon as v1.0.1 ships, the docs link will be updated. If you follow our announcements category in our Forums, you will receive a note about the latest release and the link to the docs will be in those release notes. If you really can't wait, you can look at [my docs PR](https://github.com/rancher/rancher.github.io/pull/245)

**Comment by flaccid** [comment]
I'm all subscribed up :) thanks again, we are just very eager on this one!

**Comment by GameScripting** [comment]
Are there any plans/is it technically possible to have the HA mysql-server and load-balancer within the rancher cluster/nodes/hosts?

Right now we are using rancher to manage all of our containers and when we deploy a repplicated database, we do so within rancher. The requirement to have the mysql-database outsite of rancher feels a little bit odd to me :)

**Comment by LLParse** [comment]
@GameScripting This is definitely on the radar and possible, we would like Rancher to orchestrate it's own HA database within the System Stack.

I don't think it is officially on the roadmap. Could you open a new issue to further discuss (we don't actively monitor closed issues)?

**Comment by virtuman** [comment]
Any progress with this? Is there any chance that rancher's mysql will become part of the rancher installer, ie - if i don't already have an existing MySQL cluster that it would help me spin up a mysql galera cluster, or at least some good instructions / installer script on how to do it properly for best rancher's operation?

as of right now i can see it achievable this way only:
1) install mysql server
2) install rancher with external mysql support
3) from rancher - install mysql gallera cluster
4) stop rancher server
5) copy db from standalone mysql ( installed in step.1 ) to galera cluster
6) remove rancher
7) re-install rancher with new cattle connection string for mysql cluster
8) follow High Availability menu to generate installer scripts that will be then deployed on additional nodes


is there a better / easier / more correct / more reliable way of getting this done on a new cluster deployment?

Thank you.
