### ISSUE TITLE
Unable to update/change Rancher Certificate

### ISSUE THREAD

**Issue by simonbirtles** [rancher/rancher#38748]
```
Rancher version 2.6.7
Rancher Build Command:
helm install rancher rancher-latest/rancher --namespace cattle-system --set hostname=<name.domain>--set bootstrapPassword=<password> --set ingress.tls.source=secret --set privateCA=true
```

I am using a private CA and have been able to update the CA certificate successfully using the procedures in `https://rancher.com/docs/rancher/v2.6/en/installation/resources/update-rancher-cert/`, this is shown via the URL `https://<ip>/v3/settings/cacerts`, this CA cert displayed is the correct and valid CA. I also followed this to update the cert in `tls-rancher-ingress`.

I have been unable to change the certificate used by the UI and more importantly used when trying to build a cluster with Rancher. I expected using the above procedure to update the `tls-rancher-ingress` cert would have changed this cert. 

The cluster build hangs with a message in rancher of `Waiting for cluster agent to connect`.

If I take a look at the logs on the first node (control plane, etc, worker) build on a RHEL8.6 OS, I get the following output which shows that the correct CA cert is being downloaded, then the actual certificates for rancher, the problem is that this is the self signed cert which is the one I had tried to change but with no effect. `kubectl -n cattle-system create secret tls tls-rancher-ingress --cert=tls.crt --key=tls.key`

```
kubectl logs -n cattle-system cattle-cluster-agent-745859cc77-7chrq
...
INFO: Value from https://172.31.12.0/v3/settings/cacerts is an x509 certificate
time="2022-08-29T08:25:41Z" level=info msg="Listening on /tmp/log.sock"
time="2022-08-29T08:25:41Z" level=info msg="Rancher agent version v2.6.7 is starting"
time="2022-08-29T08:25:41Z" level=info msg="Certificate details from https://172.31.12.0"
time="2022-08-29T08:25:41Z" level=info msg="Certificate #0 (https://172.31.12.0)"
time="2022-08-29T08:25:41Z" level=info msg="Subject: CN=dynamic,O=dynamic"
time="2022-08-29T08:25:41Z" level=info msg="Issuer: CN=dynamiclistener-ca@1661689758,O=dynamiclistener-org"
time="2022-08-29T08:25:41Z" level=info msg="IsCA: false"
...
time="2022-08-29T08:25:41Z" level=error msg="Issuer of last certificate found in chain (CN=dynamiclistener-ca@1661689758,O=dynamiclistener-org) does not match with CA certificate Issuer (CN=lanservices.labs.haystacknetworks.com,OU=labs,O=Haystack Networks Ltd,L=City,ST=County,C=UK,1.2.850.113169.1.8.1=#0c2273696d6f6e2e626972746c6344656566777887461636b6e6574776f726b732e636f6d). Please check if the configured server certificate contains all needed intermediate certificates and make sure they are in the correct order (server certificate first, intermediates after)"
```

I am following the right process to change this certificate?, if so any ideas to what the issue is ?

**Comment by simsicon** [comment]
I am experiencing the same issue, I have provided my private CA to cacerts.pem and store it to `tls-ca`, but I still get the certs signed by `TRAEFIK`.
```bash
$ kubectl -n cattle-system get secret

NAME                                    TYPE                                  DATA   AGE
tls-rancher-ingress                     kubernetes.io/tls                     2      9m47s
tls-ca                                  Opaque                                1      9m44s
bootstrap-secret                        Opaque                                1      9m35s
sh.helm.release.v1.rancher.v1           helm.sh/release.v1                    1      9m35s
rancher-token                           kubernetes.io/service-account-token   3      9m33s
tls-rancher                             kubernetes.io/tls                     2      9m12s
tls-rancher-internal-ca                 kubernetes.io/tls                     2      9m12s
tls-rancher-internal                    kubernetes.io/tls                     2      9m12s
serving-cert                            kubernetes.io/tls                     2      9m12s
git-webhook-api-service-token           kubernetes.io/service-account-token   3      8m26s
pod-impersonation-helm-op-bth82-token   kubernetes.io/service-account-token   3      8m25s
helm-operation-vzcg9                    Opaque                                3      8m23s
pod-impersonation-helm-op-4rlnc-token   kubernetes.io/service-account-token   3      8m16s
helm-operation-d2w5n                    Opaque                                3      8m14s
rancher-webhook-tls                     kubernetes.io/tls                     2      8m11s
cattle-webhook-ca                       kubernetes.io/tls                     2      8m9s
cattle-webhook-tls                      kubernetes.io/tls                     2      8m9s
sh.helm.release.v1.rancher-webhook.v1   helm.sh/release.v1                    1      8m11s
```


![image](https://user-images.githubusercontent.com/475199/190571428-56d9f0ee-daa7-45f6-ba6a-f556cfe03f2c.png)

**Comment by simonbirtles** [comment]
After some "playing" around I found I had to update the "serving-cert", which in turn then served that cert on the UI and therefore the rancher cluster bootstrap script receives the correct client cert with CA cert in order to continue the k8s install for the new cluster. I still have some issues I am working on and not sure if related to certs still. 

I changed the certs by using `kubectl edit secrets -n cattle-system serving-cert`, note the certificates need to be base64 encoded in the secrets when editing directly.

**Comment by simsicon** [comment]
> After some "playing" around I found I had to update the "serving-cert", which in turn then served that cert on the UI and therefore the rancher cluster bootstrap script receives the correct client cert with CA cert in order to continue the k8s install for the new cluster. I still have some issues I am working on and not sure if related to certs still.
> 
> I changed the certs by using `kubectl edit secrets -n cattle-system serving-cert`, note the certificates need to be base64 encoded in the secrets when editing directly.

I tried the default method, install with rancher-generated certs, and I can get the certs signed by cert-manager when visiting rancher site, but I still get traefik certs. I found the traefik certs actually come from k3s, somehow rancher can not override the LB configuration to use its certs, but cert-manager managed to do so.
