### ISSUE TITLE
[Release Note] Update release notes for 2.6.8

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#38751]
### Changes to 2.6.7 Notes

- We need a large warning added to the top of the release notes:

> Version 2.6.7 introduced a [bug](https://github.com/rancher/rancher/issues/38672) that can cause data loss. If you are running 2.6.7, it is highly recommended to update to 2.6.8 or later. 

### Updates for 2.6.8 Notes

- This release contains the same Rancher Manager code as 2.6.7, but fixes an issue in Fleet. https://github.com/rancher/rancher/issues/38672

> Bundle pruning became too aggressive in Rancher Manager 2.6.7.  This has been fixed. **Update to 2.6.8 or later to prevent potential data loss.** See the fix for more details: https://github.com/rancher/fleet/pull/933

**Comment by btat** [comment]
Both tasks completed.
