### ISSUE TITLE
[BUG] ETCD is healthy but showing not healthy.

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#38779]
Issue description:
ETCD is showing unhealthy in the UI and kubectl get CS, but in EKS and readiness check it was healthy and the cluster seems running fine.

Business impact: 

*C*ustomer wants to update the kubernetes and the cluster is in a error state. Wants to fix this before upgrading.

*Actual behavior:*One of the etcd nodes are showing unhealthy.

Expected behavior:

ETCD should be healthy if the raw data from API readyz is showing healthy

SURE-4071

**Comment by MKlimuszka** [comment]
Moving this into Needs Info until original reporter gives more info

**Comment by yankees5963** [comment]
I have seen this issue when one node is offline/error/has issue, but the cluster is HA so ETCD is still healthy. However, in the UI the ETCD is red and says unhealthy.it should report it as degraded not unhealthy, as upon first look it appears an ETCD backup is needed when in fact its just a single ETCD node needs restarting.

**Comment by MKlimuszka** [comment]
Original reporter is non-responsive, so I am closing this. If anyone comes across this again, re-open with more info.
