### ISSUE TITLE
[Backport v2.6.9][Azure AD] Fail auth config migration if admins have not set up their app permissions properly

### ISSUE THREAD

**Issue by maxsokolovsky** [rancher/rancher#38774]
It would be good to check if admins have done everything per documentation before we allow them to commit to the Azure AD configuration update. This is relevant for Rancher setups that use Azure AD before v2.6.7 that are upgraded to v2.6.7+.

Specifically, we want to ensure the admins add the correct set of permissions for their App registration in the Azure portal. To check this, we could create a test Azure client and get an access token, then validate its permissions. If the token does not have the permissions we want, then we indicate that the migration process has failed and do not complete it.

**Comment by cbron** [comment]
Deleting this to unify with https://github.com/rancher/rancher/issues/38774
