### ISSUE TITLE
Add user agent to handlers requests

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#38775]
**Is your feature request related to a problem? Please describe.**
Kube API requests contain little info on where in rancher they were made from.

**Describe the solution you'd like**
Want requests to kube apiserver to have agent that reflects which handler in rancher made them.

**Describe alternatives you've considered**

**Additional context**

**Comment by samjustus** [comment]
LOE s

**Comment by moio** [comment]
If done at the wrangler or lasso levels, this would be useful in fleet too (cc @manno)
