### ISSUE TITLE
[BUG] NodePool controller is racy

### ISSUE THREAD

**Issue by Oats87** [rancher/rancher#38786]
**Rancher Server Setup**
- Rancher version: v2.6.8
- Installation option (Docker install/Helm Chart): N/A
- 
**Describe the bug**
The existing NodePool controller is racy and can lead to thrashing of node objects. This poses many problems, particularly against infrastructure backends that do not tolerate duplicate nodes or have fixed capacity.

**To Reproduce**
It is quite difficult to accurately reproduce this. We have (for whatever reason) seen this particularly exasperated in environments where Rancher is backed by K3s with postgres.

In these environments, in certain cases, on node scale operations, it is possible to see many nodes above the net desired quantity created.

**Result**
Many nodes are created/deleted.

**Expected Result**
Exactly the number of new desired nodes should be created.

**Screenshots**

<img width="1840" alt="Screen Shot 2022-08-29 at 9 00 08 PM" src="https://user-images.githubusercontent.com/30601846/187791382-84878886-c736-45cb-995d-8d808c34a90c.png">

**Additional context**

**Comment by sowmyav27** [comment]
- k3s version - `v1.23.8+k3s1`
- rancher external db - `postgres`version - `14.2`
- rancher version - `2.6.8`
- Deployed an RKE1 cluster with 1 etcd + cp and 1 worker nodes. Multiple etcd/cp nodes provisioned and got deleted
- Eventually cluster did come up but after quite a long time.

<img width="1229" alt="Screen Shot 2022-08-31 at 7 31 22 PM" src="https://user-images.githubusercontent.com/26032343/187821861-8cd790e9-ae2e-4cf5-bdc8-5bc95e160bb8.png">
