### ISSUE TITLE
Release 1.0.1 csp-adapter

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#38794]
This was fixed and released out of band: https://github.com/rancher/rancher/issues/38712
We should make a full release of csp-adapter to include this now.

**Comment by brudnak** [comment]
# ✅ PASSED

## Reproduction Environment

#### Not required.

<hr>

## Validation Environment

| Component                        | Version / Type                                                                     |
|----------------------------------|------------------------------------------------------------------------------------|
| Rancher version                  | v2.6-a3b5237ce1da4228c97df7552d57464c64947b3b-head                                 |
| Rancher commit link              | https://github.com/rancher/rancher/commit/a3b5237ce1da4228c97df7552d57464c64947b3b |
| Installation option              | `eksctl`                                                                           |
| If Helm Chart k8s cluster        | v1.22.12-eks-6d3986b                                                               |
| Cert Details                     | Let's Encrypt                                                                      |
| Helm version                     | v2.16.8-rancher2                                                                   |
| Downstream cluster type          | RKE1 Linode                                                                        |
| Downstream K8s version           | 	v1.24.4                                                                           |
| Authentication providers enabled | local, GitHub OAuth, ActiveDirectory LDAP                                          |
| Browser type                     | Opera GX                                                                           |
| Logged in user role              | `(Standard User)` as `(GitHub OAuth)`                                              |
| Browser type                     | Opera GX                                                                           |
| Browser version                  | LVL4 (core: 90.0.4480.100) (x86_64)                                                |

### ADDITIONAL VALIDATION SETUP

```shell
eksctl create cluster \
  --name $NAME_VAR \
  --version 1.22 \
  --region $REGION_VAR \
  --nodegroup-name $NODEGROUP_VAR \
  --nodes 3 \
  --nodes-min 1 \
  --nodes-max 4 \
  --managed
```

```shell
kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.7.1/cert-manager.crds.yaml

helm install cert-manager jetstack/cert-manager \
  --namespace cert-manager \
  --create-namespace \
  --version v1.7.1
```

```shell
helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=$HOSTNAME_VAR \
  --set bootstrapPassword=$PASSWORD_VAR \
  --set ingress.tls.source=letsEncrypt \
  --set letsEncrypt.email=$EMAIL_VAR \
  --set letsEncrypt.ingress.class=nginx \
  --set ingress.ingressClassName=nginx \
  --set rancherImageTag=v2.6-head \
  --set extraEnv\[0\].name="CATTLE_PROMETHEUS_METRICS" --set-string extraEnv\[0\].value=true
```

## Validation steps

- Set up the CSP Adapter
   1. Can follow these steps: https://docs.ranchermanager.rancher.io/explanations/integrations-in-rancher/cloud-marketplace/aws-cloud-marketplace/adapter-requirements
   2. Create an OIDC Provider
   3. Create an IAM Role
   4. Create the adapter namespace `kubectl create ns cattle-csp-adapter-system`
   5. Install the chart

```shell
helm install rancher-csp-adapter rancher-charts/rancher-csp-adapter --namespace cattle-csp-adapter-system --set aws.enabled=true --set aws.roleName=$MY_ROLE_NAME --set-string aws.accountNumber=$MY_ACC_NUM --set image.tag=v1.0.1
```

- Verify the version installed was v1.0.1
  1. Starting from the **default** Rancher homepage `/dashboard/home`
  2. Click `hamburger menue` > `Workload` > `Deployments` > filter to `cattle-csp-adapter-system` namespace
  3. Verify the version of the `rancher-csp-adapter` deployment is `v1.0.1`
     - It is correctly: `709825985650.dkr.ecr.us-east-1.amazonaws.com/suse/rancher/rancher-csp-adapter:v1.0.1`

## Additional Info

## RESULTS

#### ✅ Expected
Expected the version of the `rancher-csp-adapter` deployment to be `v1.0.1`

#### ✅ Actual
The actual version of the `rancher-csp-adapter` deployment was `v1.0.1`

## Additional Test Cases

# Test Plan

<table>
    <tbody>
        <tr>
            <th>Test</th>
            <th>Steps</th>
            <th>Expected</th>
            <th>Actual & Pass/Fail</th>
        </tr>
        <tr>
            <td>Download the support config (While In Compliance)</td>
            <td>
                <ol>
                    <li>Click hamburger menu ==> Get Support ==> Generate Support Config</li>
                    <li>Open the config file on your local machine</li>
                    <li>Verify the format and fields in the support config</li>
                </ol>
            </td>
            <td>Expected: For the support config to show the Rancher server in compliance and fields to be correct</td>
            <td>Actual: Support config showed being in compliance and all fields were correct<br><br>Pass/Fail: ✅<code>PASS</code></td>
        </tr>
        <tr>
            <td>Out of Compliance</td>
            <td>
                <ol>
                    <li>Using an AWS account with 2 entitlements (40 nodes)</li>
                    <li>Create a downstream RKE1 Linode cluster</li>
                    <li>26 worker nodes</li>
                    <li>10 control plane nodes</li>
                    <li>5 etcd nodes</li>
                </ol>
            </td>
            <td>Expected: For the Rancher server to go into an out of compliance state. The UI banner should indicate that the Rancher server is out of compliance.</td>
            <td>Actual: Rancher goes into a state of being out of compliance when surpassing 40 nodes <br><br>Pass/Fail: ✅<code>PASS</code></td>
        </tr>
        <tr>
            <td>Download the support config (While <b>Out of Compliance</b>)</td>
            <td>
                <ol>
                    <li>Start with a Rancher server that is out of compliance (41 + nodes for this AWS account)</li>
                    <li>Click hamburger menu ==> Get Support ==> Generate Support Config</li>
                    <li>Open the config file on your local machine</li>
                    <li>Verify the format and fields in the support config</li>
                    <li>Verify the support config states being out of compliance</li>
                </ol>
            </td>
            <td>Expected: Rancher server required 3 license(s) and was able to check out 2 license(s)</td>
            <td>Actual: Rancher server required 3 license(s) and was able to check out 2 license(s)<br><br>Pass/Fail: ✅<code>PASS</code></td>
        </tr>
        <tr>
            <td>Scaling down nodes brings an out of compliance Rancher back into compliance if dropping to the correct entitlement/node count</td>
            <td>
                <ol>
                    <li>Start with a Rancher that is out of compliance (2 entitlements 41 nodes)</li>
                    <li>Scale back a worker node bringing the node total to 40 with 2 entitlements</li>
                    <li>Within 30 seconds the cluster goes back into compliance</li>
                    <li>Download the support config to ensure it also shows being back into compliance</li>
                </ol>
            </td>
            <td>Expected: For Rancher to be in compliance once it's within entitlement constraints</td>
            <td>Actual: Rancher went back into compliance<br><br>Pass/Fail: ✅<code>PASS</code></td>
        </tr>
        <tr>
            <td>Local nodes should not count against entitlements / node count</td>
            <td>
                <ol>
                    <li>Using an AWS account with 2 entitlements 40 nodes</li>
                    <li>Local cluster is 3 nodes</li>
                    <li>Create a downstream cluster with 40 nodes</li>
                </ol>
            </td>
            <td>Expected: Rancher should be in compliance because local nodes are not counted</td>
            <td>Actual: Rancher is in compliance because the local nodes aren't counted<br><br>Pass/Fail: ✅<code>PASS</code></td>
        </tr>
    </tbody>
</table>
