### ISSUE TITLE
[RFE] Add vcluster support

### ISSUE THREAD

**Issue by iMikeG6** [rancher/rancher#38803]
As already asked in issue #32733, can you please add support for vcluster ?

**Describe the solution you'd like**
Like importing other cluster type, add an import feature to handle vcluster.

**Additional context**
Currently, we had to manually add a vcluster by importing a new one then apply yaml import url in the vcluster conext. Its working but it's not fully supported. Also, for those who are using psp that restrict pod to only run in nonroot and with uid/gid higher than 0, scripting cluster import is not possible.

**Comment by steffeneichler** [comment]
We are also interested in this feature.

**Comment by iMikeG6** [comment]
up

**Comment by Sporesirius** [comment]
+1

**Comment by Sporesirius** [comment]
up

**Comment by stmcallister** [comment]
Hello! I'm a developer advocate over at LoftLabs (creators of vCluster), and I wanted to let everyone in this thread know that we just released an OSS Rancher Integration for vCluster! You can read more about it at the [vcluster-rancher-operator](https://github.com/loft-sh/vcluster-rancher-operator) project as well as the [vcluster-rancher-extension-ui](https://github.com/loft-sh/vcluster-rancher-extension-ui) project.  

You can also see it in action in the [vCluster OSS on Rancher: Creating Virtual Clusters in Rancher](https://youtu.be/vom4Lr8VZNY?si=fNO2C5Z1HwXh0Tqd) video on YouTube.
