### ISSUE TITLE
DNS resolution for sidekickname.servicename fails using dig.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#3880]
Server version - Build from master

Steps to reproduce the problem:
Create a stack.
Create a service - test11 with sidekick - hello99
Create another service- S1 in the same stack.
From containers of this service - S1 , try to use dig for "hello99.test11" to resolve sidekick container of service - test11.
dig does not return any answer.

I am able to ping  hello99.test11.

<img width="718" alt="screen shot 2016-03-08 at 5 52 51 pm" src="https://cloud.githubusercontent.com/assets/4266958/13622847/a6c8881c-e556-11e5-9a98-fb533cef19d4.png">

**Comment by alena1108** [comment]
@sangeethah can you check answers.json file to see if the:

* searchDomain is present
* ips are present 

in the client section

**Comment by alena1108** [comment]
@sangeethah this bug and https://github.com/rancher/rancher/issues/3811 caused by "." present in the name-to-resolve + the fact that dig doesn't use search domains from resolve.conf. Our internal dns assumes that the name with "." in it is fqdn, and doesn't try search domains from config sections.

**Comment by sangeethah** [comment]
Tested with server version - V0.63.0-rc3

DNS resolution for sidekickname.servicename works as expected using dig.
