### ISSUE TITLE
[RFE] Rancher can get all images from a non-Docker registry

### ISSUE THREAD

**Issue by mattfarina** [rancher/rancher#38808]
**Is your feature request related to a problem? Please describe.**
Need to be able to set the registry that all images are pulled from in a way that does not interfere with the user environment variable of CATTLE_SYSTEM_DEFAULT_REGISTY. 

**Describe the solution you'd like**
To add a new environment variable that is the default, instead of "", for CATTLE_SYSTEM_DEFAULT_REGISTY

**Describe alternatives you've considered**
Two alternatives have been looked at:

1. Using CATTLE_SYSTEM_DEFAULT_REGISTRY. The impact of using this is larger as charts will need to be updated to make sure it's default value doesn't overwrite one set in an image. This is a user set flag and we're looking for a SUSE set one.
2. Setting the registry at build time. [This already happens with settings](https://github.com/rancher/rancher/blob/a7c5da0cec039524c3d386bfd26d15697cc546b2/scripts/build-server#L14). The problem with this is that every registry change would require a new build.

**Additional context**

SURE-5046

**Comment by sowmyav27** [comment]
Reopening for QA validations

**Comment by sowmyav27** [comment]
Can we validated when `2.7.0-rc1` is available

**Comment by slickwarren** [comment]
after speaking with Matt offline, we will move this ticket to blocked. The PR above allows a registry to be set upon building the rancher image. So QA will need that image built, targeting the trusted registry, before being able to test it.

**Comment by deniseschannon** [comment]
Technically this is able to be tested from an end to end work flow since both of these issues are merged and available to test, but this is not the final locations of where the server helm chart will be or where the rancher/rancher image will be. 

@slickwarren Would you like to do a preliminary smoke test or wait until the final updates regarding where this chart and image would be available?

**Comment by slickwarren** [comment]
I would prefer to wait until we have all updates regarding chart and image are available before testing this feature. Otherwise, it puts some unnecessary setup on QA that would otherwise be addressed by the aforementioned updates.

**Comment by slickwarren** [comment]
this ticket was validated using 2.7.0-rc3 in both a docker and rke install of rancher using a non-docker registry
