### ISSUE TITLE
[BUG] Constant refreshes of userAttributes with Active Directory provider

### ISSUE THREAD

**Issue by stipx** [rancher/rancher#38804]
**Rancher Server Setup**
- Rancher version: 2.6.8

**Describe the bug**
It seems that the commit 60323f734a5b3278e837b81916705136430092d6 introduced a constant refresh of the users with ExtraByProvider=null with the Active Directory auth provider.

Looking at the user attribute resource two times after a short timeframe it shows the following differences:
```
618c618
< LastRefresh: "2022-09-02T13:13:35Z"
---
> LastRefresh: "2022-09-02T13:13:39Z"
625c625
<   generation: 52996
---
>   generation: 52998
634c634
<   resourceVersion: "605496806"
---
>   resourceVersion: "605497354"
```
And nothing else.

Just a small sample shows:
```
kc get userattributes.management.cattle.io -ocustom-columns='NAME:.metadata.name,GENERATION:.metadata.generation,LASTREFRESH:.LastRefresh,EXTRABYPROVIDER:.ExtraByProvider' | head
NAME           GENERATION   LASTREFRESH            EXTRABYPROVIDER
u-24jutqr3jg   53509        2022-09-02T13:34:20Z   <nil>
u-25dvupbu76   309          2022-09-02T13:27:51Z   map[activedirectory:map[principalid:[activedirectory_user://CN=...
u-26fbjrkxav   53390        2022-09-02T13:34:18Z   <nil>
u-2bmzhmvsdd   53007        2022-09-02T13:34:18Z   <nil>
u-2cy4ad2qpb   51065        2022-09-02T13:34:19Z   <nil>
u-2hajvdqo3k   2454         2022-09-02T13:27:51Z   map[activedirectory:map[principalid:[activedirectory_user://CN=...
u-2idaiw7ism   1264         2022-09-02T13:27:52Z   map[activedirectory:map[principalid:[activedirectory_user://CN=...
u-2pv4fs4a2a   53069        2022-09-02T13:34:19Z   <nil>
u-2pxfjnntzy   52175        2022-09-02T13:34:20Z   <nil>
```
As you can see by the number generations and the last refresh the ones with nil constantly refresh. The ones with the extrabyprovider set refreshed the last time when I synced the group memberships.

This also results in instabilities with the websocket in the UI because the constant refreshes are sent as "resource.changed" events via the websocket. Also high CPU usage because of constant changes is a result.

**To Reproduce**
I guess patching a userattribute to have ExtraByProvider=nil and using the Active Directory provider would already show the constant refreshes.

**Comment by franznemeth** [comment]
We fixed this in our environment by running the following in the local cluster:
https://gist.github.com/franznemeth/db3fb9aa317f1cdaa6601f6204a3a2ec

Definitely make sure this fix suits your configuration as it otherwise might break authentication for users.

**Comment by dnoland1** [comment]
Hit this on Okta integration as well after upgrading from v2.6.6 to v2.6.8. If you turn on rancher pod [debug logs](https://docs.ranchermanager.rancher.io/troubleshooting/other-troubleshooting-tips/logging), will see messages like this repeated:
```
2022/09/29 19:07:36 [DEBUG] Starting refresh process for u-abcdefghij
2022/09/29 19:07:36 [DEBUG] Finished refresh process for u-abcdefghij
```

**Comment by samjustus** [comment]
SURE-5268

**Comment by maxsokolovsky** [comment]
No additional work is needed here because there has been a change that will prevent the issue from happening.
Introduced in v2.6.9 by this commit https://github.com/rancher/rancher/commit/a8518f07865db96c577ffb2115260b9d4e85f09a.
