### ISSUE TITLE
[BUG][Monitoring v2]Prometheus target serviceMonitor/kube-system/rancher-monitoring-coredns is down in k3s hardened cluster - connect refused

### ISSUE THREAD

**Issue by ronhorton** [rancher/rancher#38820]
**Rancher Server Setup**
- Rancher version: `2.6-head Commit ID cb9ccde`
- Installation option (Docker install/Helm Chart): `Helm`
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): `k3s`
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: `v1.24.4`
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): `imported`

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: `standard user`

**Describe the bug**

After installing monitoring, prometheus target: serviceMonitor/kube-system/rancher-monitoring-coredns/ is down. restarting the pod does not resolve issue. 
I don't see this error on a non-hardened cluster

**To Reproduce**
1. import hardened k3s cluster 
2. create standard user
3. install monitoring (100.1.3+up19.0.3)
4. install alerting drivers chart (100.0.3)
5. navigate to cluster>monitoring
6. select 'prometheus targets' link 
 
**Result**
prometheus target is down
**Expected Result**

all prometheus targets are healthy/running
**Screenshots**

![2022-09-06_13-43-47](https://user-images.githubusercontent.com/89212856/188704026-3bcc9e05-ba8d-459b-a1eb-fcaf075089c9.png)

**Additional context**

SURE-5357

**Comment by MKlimuszka** [comment]
@ronhorton , we discussed in the refinement that you would retest this before we work on it.

**Comment by MKlimuszka** [comment]
This needs to be reproduced in 2023-Q1-2.6x and 2023-Q1-2.7x

**Comment by ronhorton** [comment]
**reproduced** rancher `2.7-head commit ID c66d79a666`
1. create a hardened k3s cluster
2. in rancher UI, hamburger > cluster management > import existing > generic
3. ssh to k3s cluster node and run the following:
4. `export KUBECONFIG=/etc/rancher/k3s/k3s.yaml PATH=$PATH:/var/lib/rancher/k3s/bin:/opt/k3s/bin`
5. run rancher registration command (from ui) on k3s node
6. cluster will register and be added to the clusters in the rancher instance
7. install latest rancher-monitoring (enable/disable psps according to k3s version - [v1.24.4+k3s1](https://github.com/k3s-io/k3s/releases/tag/v1.24.4%2Bk3s1) check psp enabled box when installing monitoring
8. navigate to monitoring > prometheus targets
9. click on 'unhealthy'
`rancher-monitoring-coredns connection refused`

**Comment by geethub97** [comment]
The rancher monitoring chart is missing a network policy in the hardened cluster. As a temporary work around, you can add port 9153 to the default-network-dns-policy and restart the coredns pod.

**Comment by vivek-shilimkar** [comment]
Validated the issue on rancher v2.8-head and k8s cluster v1.26.8+k3s1.

Validation steps

1. Created a k3s harden cluster.
2. Imported the k3s harden cluster into rancher v2.8-head
3. Created a Standard User.
4. Added a Standard User as an Cluster Owner of k3s harden cluster. (Without Owner role cannot install charts with standard user)
5. Login into standard user.
6. Installed a Monitoring and Alerting charts.
7. Opened 'Prometheus Targets' link by navigating Cluster --> Monitoring --> Prometheus Targets.
8. All the Endpoints/Targets are in 'Up' state.

Since issue is resolved. Closing the ticket.
