### ISSUE TITLE
[release/v2.6] Add 1.23 for EKS clusters

### ISSUE THREAD

**Issue by Oats87** [rancher/rancher#38837]
Like https://github.com/rancher/rancher/issues/37534, we need to add AMIs for 1.23

**Comment by Oats87** [comment]
This issue is blocked pending correspondence with someone with access to the China regions who can provide me the AMI IDs for the regions.

**Comment by Sahota1225** [comment]
https://github.com/rancher/dashboard/issues/6826

**Comment by niusmallnan** [comment]
I can access the AWS China regions, and tried to run this script:
```
#!/bin/bash

_aws_regions="cn-north-1 cn-northwest-1"

_ami_list=ami.txt

> $_ami_list

for _version in $@
do
    echo "\"$_version\": {" >> $_ami_list
    for _region in $_aws_regions
    do
        _eks_ami=`aws ssm get-parameter --no-cli-pager --name /aws/service/eks/optimized-ami/$_version/amazon-linux-2/recommended/image_id --region $_region --query "Parameter.Value" --output text`
        echo "        \"$_region\": \"$_eks_ami\"," >> $_ami_list
        sleep 1
    done
    echo "}," >> $_ami_list
done
```

Here is the output:
```
$ ./list_eks_ami.sh 1.23
$ cat ami.txt
"1.23": {
        "cn-north-1": "ami-03c283d37d6d555c9",
        "cn-northwest-1": "ami-052f05a1bb39ebae2",
},
```

**Comment by Oats87** [comment]
@niusmallnan Would you mind running the script for 1.18 -> 1.22 so that I can update all AMIs?

**Comment by niusmallnan** [comment]
@Oats87 Sure thing.
```
"1.18": {
        "cn-north-1": "ami-04c2ddc2c87ad14c6",
        "cn-northwest-1": "ami-088cc1ef35c151326",
},
"1.19": {
        "cn-north-1": "ami-065dff7849a61eaf7",
        "cn-northwest-1": "ami-0c023d9330c8e31a7",
},
"1.20": {
        "cn-north-1": "ami-06713bbde58657a46",
        "cn-northwest-1": "ami-0a212aae8ecbda546",
},
"1.21": {
        "cn-north-1": "ami-0a8893e2be26e0b30",
        "cn-northwest-1": "ami-0400b7c06f0b0dc7e",
},
"1.22": {
        "cn-north-1": "ami-0078eb8f790bb1c73",
        "cn-northwest-1": "ami-0e863f0d49a4719d1",
},
```

**Comment by Oats87** [comment]
@Sahota1225 We will probably need open a dashboard issue for release/v2.7 as well.

**Comment by markusewalker** [comment]
**QA TEST PLAN**
1. Setup Rancher, create a standard user and login as that user.
2. Navigate to Cluster Management > Amazon EKS.
3. Fill out the requested prompts and in the `Managed Node Groups`, fill out a custom `AMI ID` that has been updated for EKS.
     - Ensure that the version is `1.23`.
4. Provision the cluster and validate that it is in a state of `Active` in Cluster Management and Cluster Explorer
5. Repeat steps 3-4 for all supported EKS versions.

**Comment by snasovich** [comment]
> @Sahota1225 We will probably need open a dashboard issue for release/v2.7 as well.

@Oats87 & @Sahota1225 , given that https://github.com/rancher/ui/pull/4890 was merged to `master` it doesn't look like we need that UI issue for v2.7 as `rancher/ui` doesn't seem to be branched for 2.6.x vs. 2.7.x yet.
@gaktive , please confirm.

**Comment by gaktive** [comment]
@snasovich correct; branching in UI will be early next week so what's in `master` now will be in 2.7.x.
