### ISSUE TITLE
[BUG] Proxied node driver cluster fails to provision through rancher

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#38838]
**Rancher Server Setup**
- Rancher version: v2.6.8
- Installation option (Docker install/Helm Chart): docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):n/a
- Proxy/Cert Details:n/a

**Information about the Cluster**
- Kubernetes version: any (tested with 1.24.4-rancher1-1, 1.24.4+rke2r1
- Cluster Type (Local/Downstream): downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): node driver (tested with aws)

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: tested with admin, standard user, cluster owner

**Describe the bug**

When adding HTTPS_PROXY, HTTP_PROXY, and NO_PROXY to a node driver cluster, the proxy is not used. If the node driver has the `only use private network` setting enabled, the cluster will not come to an active state

**To Reproduce**

* configure a proxy in a subnet where you can provision nodes without a public address
* in your rancher setup, provision an ec2 cluster
  * under andvanced settings, enable the `use only private address` setting
  * under `environment variables`, add HTTPS_PROXY, HTTP_PROXY, and NO_PROXY that work with your proxy
  * ensure the subnet selected is where you have deployed your proxy
* wait for the cluster to provision

**Result**
* the node never gets past the docker install/ssh.hostName steps for rke1, and `waiting for agent to checkin and apply plan` for rke2

**Expected Result**

the node(s) from the node driver should be using the proxy specified in order to connect to the public rancher setup

**Screenshots**

**Additional context**

* following the same steps, but using a custom cluster (and private nodes in the same subnet as the proxy) on the same k8s version does allow the cluster to come to an active state.

**Comment by jiaqiluo** [comment]
This is the expected behavior because Rancher cannot install Docker on the nodes if the nodes do not have access to the internet. 
To make the node-driver clusters work, we need to prepare an AMI which has Docker pre-installed and trusts the certifications of the proxy server; and Docker is configured to pull images via the proxy.

**Comment by slickwarren** [comment]
I see, thank you for digging into this,  Jiaq! 
The reason custom clusters were working is because we [automate adding the proxy information](https://github.com/rancher/rancher/blob/release/v2.6/tests/validation/tests/v3_api/test_proxy.py#L125) to the docker config (and have docker pre-installed on the private node where the custom cluster will run).  

Main takeaways are:
* nodes used by the node driver would need to already have docker installed
  * the image used for these nodes would also need to have docker configured to use the proxy specified before using them in the node driver


We will alter our test plans moving forward based on these findings.
