### ISSUE TITLE
Public endpoints are not updated on agent ip change

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#3883]
@ibuildthecloud

**Comment by sangeethah** [comment]
Tested with latest build from master:

Added Amazon EC2 host to rancher-setup.
Created few services with exposed ports .
Some of the containers of the services were on the EC2 host.

"publicEndpoints" for service reflects the EC2 host's ip address for container in this host.

power off the EC2 host (from AWS console) and wait for the host to get to "reconnecting" state.

power on the EC2 host (from AWS console). Host is now given a different ip.

Once the host gets to active state , we still see the same old ip associated with the host.
"publicEndpoints" for service reflects the EC2  host's old ip address for container in this host.

Rerun the host registration docker command on the EC2 host.

We will see that new Ip change being reflected for the host.

"publicEndpoints" for service now reflects the EC2 host's new ip address for container in this host.
