### ISSUE TITLE
[BUG] provisioning with redhat phase fails for a RHEL node without repositories

### ISSUE THREAD

**Issue by fins2** [rancher/rancher#38840]
**Rancher Server Setup**

Rancher version: v2.6.7, v2.6.8
    
**Information about the Cluster**

 Kubernetes version: v1.24.4
 Cluster Type (Local/Downstream): downstream
        If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): RKE VMware vSphere 

**Describe the bug**

When provisioning a new downstream cluster with RHEL nodes, the provision phase doesn't work, it fails on the installation of curl even if curl is already installed on the node.

**To Reproduce**

 Create a new downstream cluster with RHEL nodes not registered with Satellite and with no repositories available.
`yum repolist 
Updating Subscription Management repositories.
Unable to read consumer identity
This system is not registered with an entitlement server. You can use subscription-manager to register.
No repositories available`

**Result**

 the provisioning phase fails with this error message
`Error creating machine: RHEL ssh command error: command: sudo -E yum install -y curl err: exit status 1 output: Updating Subscription Management repositories.`

**Expected Result**

A downstream cluster provisioned with RHEL nodes.

**Additional context**

I'm working with RHEL templates that are not registered on our Satellite, so they don't have any repositories configured.
I don't want to register them because they are meant to be immutable and ephemeral. 
I suppose that the script responsible for the redhat provisioning has to check if curl is already available before trying to install it.
The provisioning phase works with RHEL nodes with at least one repo configured on it.

**Comment by dkeightley** [comment]
Hi @fins2, if you have Docker pre-installed, you should be able to skip the package management by overriding the engine install URL in the node template for the cluster, the URL value can be set to `none`.

![image (4)](https://user-images.githubusercontent.com/20566450/190936826-89eec1f7-4989-4e8e-a2a4-90e18c6bee1e.png)

Please let me know if this resolves the issue, as I'd like to improve our documentation on this.

Related: https://github.com/rancher/rancher/issues/30895

**Comment by fins2** [comment]
Hi @dkeightley,

Thanks for the update.
Just updated the node template with the Docker Install URL set to `none` and I'm still facing the same error message:
`Error creating machine: RHEL ssh command error: command: sudo -E yum install -y curl err: exit status 1 output: Updating Subscription Management repositories.`

**Comment by dkeightley** [comment]
Thanks for confirming, it appears this is already tracked under https://github.com/rancher/rancher/issues/35195.

I'll close this to track it there.
