### ISSUE TITLE
[BUG] Istio with CNI install fails on k3s hardened cluster

### ISSUE THREAD

**Issue by nickwsuse** [rancher/rancher#38849]
**Rancher Server Setup**
- Rancher version: `v2.6-head Commit ID: cb9ccde`
- Installation option (Docker install/Helm Chart): `Helm Install`
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): `Hardened k3s`
- Proxy/Cert Details: `byo-valid`

**Information about the Cluster**
- Kubernetes version: `v1.24.4+k3s1`
- Cluster Type (Local/Downstream): `Downstream`
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): `Imported`

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): `Admin`

**Describe the bug**

When attempting to install `Istio v100.4.0+up1.14.1` with CNI and Jeager enabled the install fails. The logs for the `Unready` pods show that there are no networks found, while the `Error` pods show the resources timed out.

<details>
   <summary>Unready Logs</summary>

```
2022-09-08T18:07:17.556700Z info CNI install configuration:
CNINetDir: /etc/cni/net.d
MountedCNINetDir: /host/etc/cni/net.d
CNIConfName:
ChainedCNIPlugin: true
CNINetworkConfigFile:
CNINetworkConfig: {
"cniVersion": "0.3.1",
"name": "istio-cni",
"type": "istio-cni",
"log_level": "info",
"log_uds_address": "__LOG_UDS_ADDRESS__",
"kubernetes": {
"kubeconfig": "__KUBECONFIG_FILEPATH__",
"cni_bin_dir": "/opt/cni/bin",
"exclude_namespaces": [ "istio-system", "kube-system" ]
}
}
CNIEnableInstall: true
CNIEnableReinstall: true
LogLevel: warn
KubeconfigFilename: ZZZ-istio-cni-kubeconfig
KubeconfigMode: 0600
KubeCAFile:
SkipTLSVerify: false
K8sServiceProtocol:
K8sServiceHost: "<redacted>"
K8sServicePort: 443
K8sNodeName: istio-cni-node-825xg
UpdateCNIBinaries: true
SkipCNIBinaries: []
MonitoringPort: 15014
LogUDSAddress: /var/run/istio-cni/log.sock
2022-09-08T18:07:17.556747Z info CNI race repair configuration:
Enabled: true
RunAsDaemon: true
NodeName: "<redacted>"
LabelKey: cni.istio.io/uninitialized
LabelValue: true
DeletePods: true
LabelPods: true
SidecarAnnotation: sidecar.istio.io/status
InitContainerName: istio-validation
InitTerminationMsg:
InitExitCode: 126
LabelSelectors:
FieldSelectors:
2022-09-08T18:07:17.556739Z info ControlZ available at "<redacted>"
2022-09-08T18:07:17.557031Z info Start a UDS server for CNI plugin logs
2022-09-08T18:07:17.557119Z info repair Start CNI race condition repair.
2022-09-08T18:07:17.798493Z info install Copied istio-cni to /host/opt/cni/bin.
2022-09-08T18:07:17.798560Z info install Directory /host/secondary-bin-dir is not writable, skipping.
2022-09-08T18:07:17.798756Z info install write kubeconfig file /host/etc/cni/net.d/ZZZ-istio-cni-kubeconfig with:
# Kubeconfig file for Istio CNI plugin.
apiVersion: v1
kind: Config
clusters:
- name: local
cluster:
server: "<redacted>"
certificate-authority-data: <CA cert from /var/run/secrets/kubernetes.io/serviceaccount/ca.crt>
users:
- name: istio-cni
user:
token: "<redacted>"
contexts:
- name: istio-cni-context
context:
cluster: local
user: istio-cni
current-context: istio-cni-context
2022-09-08T18:07:17.799015Z info install Using CNI config template from CNI_NETWORK_CONFIG environment variable.
2022-09-08T18:07:17.799040Z info install CNI config: {
"cniVersion": "0.3.1",
"name": "istio-cni",
"type": "istio-cni",
"log_level": "info",
"log_uds_address": "/var/run/istio-cni/log.sock",
"kubernetes": {
"kubeconfig": "/etc/cni/net.d/ZZZ-istio-cni-kubeconfig",
"cni_bin_dir": "/opt/cni/bin",
"exclude_namespaces": [ "istio-system", "kube-system" ]
}
}
2022-09-08T18:07:17.799217Z warn install Istio CNI is configured as chained plugin, but cannot find existing CNI network config: no networks found in /host/etc/cni/net.d
2022-09-08T18:07:17.799232Z info install Waiting for CNI network config file to be written in /host/etc/cni/net.d...
```

</details>

<details>
   <summary>Error Logs</summary>

```
setting up kubeconfig
Switched to context "rancher-istio-context".
starting istioctl commands
no running Istio pods in "istio-system"
1.14.1
Info [IST0118] (Service istio-system/jaeger-collector) Port name jaeger-collector-grpc (port: 14250, targetPort: 14250) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service istio-system/jaeger-collector) Port name jaeger-collector-http (port: 14268, targetPort: 14268) doesn't follow the naming convention of Istio port.
running istioctl install
- Processing resources for Istio core.
✔ Istio core installed
- Processing resources for Istiod.
- Processing resources for Istiod. Waiting for Deployment/istio-system/istiod
✔ Istiod installed
- Processing resources for CNI, Ingress gateways.
- Processing resources for CNI, Ingress gateways. Waiting for DaemonSet/istio-system/istio-cni-node
- Processing resources for CNI, Ingress gateways. Waiting for DaemonSet/istio-system/istio-cni-no...
✔ Ingress gateways installed
- Processing resources for CNI. Waiting for DaemonSet/istio-system/istio-cni-node
✘ CNI encountered an error: failed to wait for resource: resources not ready after 5m0s: timed out waiting for the condition
- Pruning removed resourcesError: failed to install manifests: errors occurred during operation
error found during istioctl install
```

</details>

**To Reproduce**

1. Set up a v2.6-head HA Rancher instance
2. Create a hardened k3s cluster
3. Import the k3s cluster into the HA Rancher instance
4. On the imported cluster, install the Monitoring app (v100.1.3+up19.0.3)
5. On the imported cluster, install the Istio app (v100.4.0+up1.14.1) with CNI and Jaeger options selected

**Result**
The Istio install fails because CNI networks aren't found

**Expected Result**
The Istio install is successfully completed and a demo app can be deployed

**Screenshots**
Failed Install:
![failed_install](https://user-images.githubusercontent.com/107147272/189211920-e02f3271-3cb4-4fe5-b663-3f9f58c1eea6.png)

Pods:
![pods](https://user-images.githubusercontent.com/107147272/189211978-85d86361-a3ba-47e9-a8f7-7ffc72efdf65.png)

**Additional context**
- The install works without CNI enabled, but deploying an app fails because CNI is needed.
- The install works on RKE1 and RKE2 hardened clusters, as well as non-hardened k3s clusters, so this appears to be an issue with just hardened k3s imported clusters.

**Comment by doflamingo721** [comment]
Hey @nickwsuse, This issue is occurring because the Istio CNI plugin operates as a chained CNI plugin, and it is designed to be used with another CNI plugin ([reference](https://istio.io/latest/docs/setup/additional-setup/cni/)). Here it is not able to find the network configuration for any network provider under `/etc/cni/net.d`. In case of RKE1 and RKE2, the network configurations are present and hence istio installation with CNI enabled is not erroring out there. Can you please confirm if the CNI was configured for the k3s setup you have mentioned in the issue. And if not can you please try configuring the CNI first and then installing istio? Thanks.

**Comment by doflamingo721** [comment]
Hey @nickwsuse , did you get a chance to re-test this issue with CNI(calico/canal,etc) configured while provisioning the cluster and then installing istio with CNI enabled?

**Comment by nickwsuse** [comment]
@doflamingo721 I haven't had a chance yet, I've been busy with v2.6.9 charts testing. I'll try it today though and give an update when I have more info.

**Comment by doflamingo721** [comment]
Sure @nickwsuse .

**Comment by ronhorton** [comment]
**Install Failed** `2.7-head commit id 4092002`

1. created hardened k3s cluster
2. installed monitoring chart
3. installed istio chart

result: installation failed

logs from installer:
`

W1011 17:48:54.567373 24 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
--
Tue, Oct 11 2022 1:48:54 pm | W1011 17:48:54.567453 24 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
Tue, Oct 11 2022 1:48:54 pm | W1011 17:48:54.567476 24 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
Tue, Oct 11 2022 1:48:54 pm | beginning wait for 29 resources with timeout of 10m0s
Tue, Oct 11 2022 1:48:54 pm | Starting delete for "istioctl-installer" Job
Tue, Oct 11 2022 1:48:54 pm | jobs.batch "istioctl-installer" not found
Tue, Oct 11 2022 1:48:54 pm | creating 1 resource(s)
Tue, Oct 11 2022 1:48:54 pm | Watching for changes to Job istioctl-installer with timeout of 10m0s
Tue, Oct 11 2022 1:48:54 pm | Add/Modify event for istioctl-installer: ADDED
Tue, Oct 11 2022 1:48:54 pm | istioctl-installer: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
Tue, Oct 11 2022 1:48:55 pm | Add/Modify event for istioctl-installer: MODIFIED
Tue, Oct 11 2022 1:48:55 pm | istioctl-installer: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
Tue, Oct 11 2022 1:54:48 pm | Add/Modify event for istioctl-installer: MODIFIED
Tue, Oct 11 2022 1:54:48 pm | istioctl-installer: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
Tue, Oct 11 2022 1:54:48 pm | Add/Modify event for istioctl-installer: MODIFIED
Tue, Oct 11 2022 1:54:48 pm | istioctl-installer: Jobs active: 1, jobs failed: 1, jobs succeeded: 0
Tue, Oct 11 2022 1:58:54 pm | Error: INSTALLATION FAILED: failed post-install: timed out waiting for the condition

`

✘ CNI encountered an error: failed to wait for resource: resources not ready after 5m0s: timed out waiting for the condition
  
- Pruning removed resourcesError: failed to install manifests: errors occurred during operation
error found during istioctl upgrade

logs from cni node:
 kubectl logs istio-cni-node-gvlcd  -n istio-system
2022-10-11T17:49:56.130645Z     info    CNI install configuration: 
CNINetDir: /etc/cni/net.d
MountedCNINetDir: /host/etc/cni/net.d
CNIConfName: 
ChainedCNIPlugin: true
CNINetworkConfigFile: 
CNINetworkConfig: {
  "cniVersion": "0.3.1",
  "name": "istio-cni",
  "type": "istio-cni",
  "log_level": "info",
  "log_uds_address": "__LOG_UDS_ADDRESS__", 
  "kubernetes": {
      "kubeconfig": "__KUBECONFIG_FILEPATH__",
      "cni_bin_dir": "/opt/cni/bin",
      "exclude_namespaces": [ "istio-system", "kube-system" ]
  }
}
CNIEnableInstall: true
CNIEnableReinstall: true
LogLevel: warn
KubeconfigFilename: ZZZ-istio-cni-kubeconfig
KubeconfigMode: 0600
KubeCAFile: 
SkipTLSVerify: false
K8sServiceProtocol: 
K8sServiceHost: XXXXXXXXXX
K8sServicePort: 443
K8sNodeName: istio-cni-node-gvlcd
UpdateCNIBinaries: true
SkipCNIBinaries: []
MonitoringPort: 15014
LogUDSAddress: /var/run/istio-cni/log.sock

2022-10-11T17:49:56.131239Z     info    CNI race repair configuration: 
Enabled: true
RunAsDaemon: true
NodeName: ip-XXXXXXXX
LabelKey: cni.istio.io/uninitialized
LabelValue: true
DeletePods: true
LabelPods: true
SidecarAnnotation: sidecar.istio.io/status
InitContainerName: istio-validation
InitTerminationMsg: 
InitExitCode: 126
LabelSelectors: 
FieldSelectors: 

2022-10-11T17:49:56.132348Z     info    Start a UDS server for CNI plugin logs
2022-10-11T17:49:56.132483Z     info    repair  Start CNI race condition repair.
2022-10-11T17:49:56.131226Z     info    ControlZ available at XXXXXXXXX
2022-10-11T17:49:56.609378Z     info    install Copied istio-cni to /host/opt/cni/bin.
2022-10-11T17:49:56.609602Z     info    install Directory /host/secondary-bin-dir is not writable, skipping.
2022-10-11T17:49:56.609824Z     info    install write kubeconfig file /host/etc/cni/net.d/ZZZ-istio-cni-kubeconfig with: 
# Kubeconfig file for Istio CNI plugin.
apiVersion: v1
kind: Config
clusters:
- name: local
  cluster:
    server: https:/XXXXXXXXX:443
    certificate-authority-data: <CA cert from /var/run/secrets/kubernetes.io/serviceaccount/ca.crt>
users:
- name: istio-cni
  user:
    token: "<redacted>"
contexts:
- name: istio-cni-context
  context:
    cluster: local
    user: istio-cni
current-context: istio-cni-context

2022-10-11T17:49:56.609919Z     info    install Using CNI config template from CNI_NETWORK_CONFIG environment variable.
2022-10-11T17:49:56.609935Z     info    install CNI config: {
  "cniVersion": "0.3.1",
  "name": "istio-cni",
  "type": "istio-cni",
  "log_level": "info",
  "log_uds_address": "/var/run/istio-cni/log.sock", 
  "kubernetes": {
      "kubeconfig": "/etc/cni/net.d/ZZZ-istio-cni-kubeconfig",
      "cni_bin_dir": "/opt/cni/bin",
      "exclude_namespaces": [ "istio-system", "kube-system" ]
  }
}
2022-10-11T17:49:56.610083Z     warn    install Istio CNI is configured as chained plugin, but cannot find existing CNI network config: no networks found in /host/etc/cni/net.d
2022-10-11T17:49:56.610092Z     info    install Waiting for CNI network config file to be written in /host/etc/cni/net.d...

**Comment by doflamingo721** [comment]
Hey @ronhorton just wanted to confirm once, while provisioning the k3s hardened cluster did you configure a CNI(calico/canal,etc) as pointed [here](https://github.com/rancher/rancher/issues/38849#issuecomment-1257991211)?

**Comment by ronhorton** [comment]
[doflamingo721](https://github.com/doflamingo721) I did not do anything with calico specifically, so it looks like i missed the whole point of the exercise. i'll retest with that in mind.

**Comment by doflamingo721** [comment]
@ronhorton Sure, thanks.

**Comment by ronhorton** [comment]
@doflamingo721 have you been able to install istio on k3s hardened with cni? i've not been succesful, but i'm minimally familiar with istio and istio with cni, so want to determine if this is a bug or a configuration problem. if you're able to accomplish the istio install on hardened k3s with cni, we can close this.

**Comment by vardhaman22** [comment]
Hardened K3s Cluster Setup Steps with Calico CNI:

1. Created 3 vm instances(aws ec2) for cluster. (1 control plane and 2 workers).

2. perform actions required to make the cluster hardened on the nodes.
	Note: do not set api server arg flags

3. The node which you want to be the control plane run the following command:
	```curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.24.6+k3s1 K3S_KUBECONFIG_MODE="644" INSTALL_K3S_EXEC="--flannel-backend=none --disable-network-policy --disable=traefik  --protect-kernel-defaults" sh -```
	
	Note: In place of v1.24.6+k3s1 use any version which is supported by the rancher server. And use the same version for worker nodes as well.
	Note: here ```--flannel-backend=none --disable-network-policy``` is necessary to tell k3s to not install flannel cni.
ref: https://docs.k3s.io/installation/network-options?_highlight=custom#custom-cni
```--disable=traefik``` is used just to disable the embedded LB.

4. install calico in the cluster by running the following command on the control plane node:
``` sudo kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.24.5/manifests/calico.yaml ```


5. Obtain the ```Token``` from k3s control plane node: 
	```sudo cat /var/lib/rancher/k3s/server/token```
   this token will be used in adding k3s agents (worker nodes)

6. run the following command on worker nodes
	```curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.24.6+k3s1 K3S_URL=https://<control_plane_node_ip>:6443 K3S_TOKEN="<token_retrived_from_step_3>" INSTALL_K3S_EXEC="--protect-kernel-defaults" sh -```

7. import the cluster in rancher.


8. add the api server flags updating the service file and then restarting the service.(needed for hardened cluster)
```sudo nano /etc/systemd/system/k3s.service```
```
ExecStart=/usr/local/bin/k3s \
    server \
        '--flannel-backend=none' \
        '--disable=traefik' \
        '--disable-network-policy' \
        '--protect-kernel-defaults' \
        '--kube-apiserver-arg=audit-log-path=/var/lib/rancher/k3s/server/logs/audit.log' \
        '--kube-apiserver-arg=audit-policy-file=/var/lib/rancher/k3s/server/audit.yaml' \
        '--secrets-encryption' \
        '--kube-apiserver-arg=enable-admission-plugins=NodeRestriction,PodSecurityPolicy,ServiceAccount' \
        '--kube-apiserver-arg=audit-log-maxage=30' \
        '--kube-apiserver-arg=audit-log-maxbackup=10' \
        '--kube-apiserver-arg=audit-log-maxsize=100' \
        '--kube-apiserver-arg=request-timeout=300s' \
        '--kube-apiserver-arg=service-account-lookup=true' \

  ```
  
  then restart the service 
 ```
  sudo systemctl daemon-reload
  sudo systemctl restart k3s.service
```

9. install monitoring chart and then install istio chart with cni enabled.

Result: istio installation successful.

**Comment by vardhaman22** [comment]
Istio works with both flannel and calico cni. Just that in case of k3s cluster if we are using flannel cni then the cni related configuration and bin directories are different then which istio uses by default. 
Istio works well with calico cni by default so if we are using calico cni we don't need to configure anything.

1. Steps to use calico with k3s

- 	create a k3s hardened cluster. just make sure to pass ```--flannel-backend=none``` and ```--disable-network-policy``` if k3s config file is used then ```flannel-backend: none``` and ```disable-network-policy: true```

	because flannel is not installed all the pods will be stuck in containerCreating state. but after we install calico everything will work fine.

- 	 after that install calico.yaml manifest.

	```ref: https://projectcalico.docs.tigera.io/getting-started/kubernetes/self-managed-onprem/onpremises```
	
	in that link use installation by manifest option and download calico.yaml by using a command 
	which is similar to the following command:
	
	```curl https://raw.githubusercontent.com/projectcalico/calico/v3.24.5/manifests/calico.yaml -O```
	

- 	then as mentioned here https://docs.k3s.io/installation/network-options#custom-cni update the calico-config ConfigMap

	and add container_settings to enable ip forwarding.
	```
	...
	 "plugins":
	    [
	      {
		"type": "calico",
		...
		...
		...
		 "container_settings": { "allow_ip_forwarding": true }
	      },
	      ....
	    ]
	```
	this is needed to avoid crashloopbackoff issues related to load balancers.
	ref: https://github.com/k3s-io/klipper-lb/issues/6
	

- 	 then apply that manifest

	``` kubectl apply -f calico.yaml ```
	

- 	 after this the calico node and calico kube controllers pod will and start and eventually all pod which are stuck in container creating state will be started.

	

- 	Now the cluster is ready we can import it in rancher and install monitoring and istio chart and everything will work just fine.

	
	
2. If we use k3s with flannel then

- 	the location for flannel config and bin dir is a bit different on k3s cluster then what istio uses.

	the locations are
```
cniConfDir: /var/lib/rancher/k3s/agent/etc/cni/net.d
cniBinDir: /var/lib/rancher/k3s/data/<someuuid>/bin  // the uuid value can be checked by ssh on any node of cluster.

Note: this bin dir has a symlink also: /var/lib/rancher/k3s/data/current/bin this can be used as a value 
since it is more deterministic.

```

- 	these path needs to be set while installing istio chart. the following configuration parameters needs to be set:

	``` values.cni.cniBinDir and values.cni.cniConfDir ```
	these needs to be set into istio operator so there needs to be a way to add them to istio operator using chart values.yaml
	

- 	 if we add set the required configuration while installing istio then also istio chart installation is successful.
