### ISSUE TITLE
Metadata config "self" sections should be built only for containers running on the same host

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#3884]
Metadata config file has the following structure:

```
default:
     stack // all stacks
     services // all services
     containers // all containers

ip1:
    self
        container,
        stack,
        service
}
ip2:
    self
        container,
        stack,
        service
}
```

where ip1/ip2 - client ips of the containers making requests to fetch /self info. We should optimize file generation by building "self" sections only for ip addresses of the containers running on the same host (today we generate it for all containers of the environment, and basically duplicate config cross hosts)

"default" section should be consistent cross hosts as it contains info about all stacks/services/containers in the system.

@ibuildthecloud

**Comment by alena1108** [comment]
@sangeethah 

Steps to test will be:

1) have more than one host in your setup: h1, h2, h3
2) deploy service scale=3 cross hosts.
3) On every host, check:

* that metadata.yml has IP address (self) sections just for the containers deployed on the host. 
* each container still should see all the instances of the service when accessed via:

```
/latest/self/service/container
/latest/stack/<stackname>/services/<serviceName>/containers 
```

**Comment by sangeethah** [comment]
Tested with latest build from master:

1. have more than one host in your setup: h1, h2, h3
2. deploy service scale=3 with exposed port so containers get deployed in different hosts.
3. From every container of the service , able to get container's ip details for all the 3 containers in the service using the following 2 metadata access urls:
 /latest/self/service/container
/latest/stacks/<stackname>/services/<serviceName>/containers 

4. metadata.yml has IP address (self) sections just for the containers deployed on the host.
