### ISSUE TITLE
Not able to create a service with volumes_from set to side kick service. 

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#3885]
Rancher server version - Build from master

Steps to reproduce the problem:

Create a service s1 with sidekick service s2 and set volume From for s1 to s2.

Service creation failed with error -  "Validation failed in API: CircularReference"

Following is the API error:
```
ApiError(...), "InvalidReference : None\n{'status': 422, 'code': u'InvalidReference', 'links': {}, 'detail': None, 'actions': {}, 'fieldName': u'CircularReference', 'message': None, 'type': u'error', 'id': u'1be57a70-d4bb-4028-bb28-6036550cbd9f'}")
```

**Comment by alena1108** [comment]
@sangeethah its not a bug if s2 uses networks of s1. If you want s1 to use volumes of s2, networks modes on both should be managed. In other words, there shouldn't be any circular dependencies.
