### ISSUE TITLE
Weird button below footer

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3886]
Version - master 3/8

Steps to Reproduce: 
1.  Go into rancher and scroll to bottom of page

Results: button below footer that says "No actions available"
![image](https://cloud.githubusercontent.com/assets/11514927/13627978/ac722ffe-e58b-11e5-9d53-e1a1d7090c2d.png)

Expected: Should not be there

**Comment by lvuch** [comment]
resolved in https://github.com/rancher/ui/pull/519

**Comment by tfiduccia** [comment]
Version - master 3/9
Verified fixed
