### ISSUE TITLE
[RFE] Need a way to upgrade or warn users when upgrading hardened k3s/rke2 to v1.25

### ISSUE THREAD

**Issue by rancher-max** [rancher/rancher#38875]
**Is your feature request related to a problem? Please describe.**
When v1.25 is introduced in Rancher, the k3s and rke2 upgrades will break. I'm not 100% sure what will happen when upgrading **provisioned** clusters, but **imported** clusters will fail due to them using system-upgrade-controller under the hood. This is because hardened k3s/rke2 clusters use PSPs, and PSPs are removed in v1.25. Currently, system-upgrade-controller does not do any mitigation for these.
For k3s, see https://github.com/k3s-io/k3s/issues/6121.
For rke2, the steps to do a SUC upgrade to v1.25 are:
1. Change config.yaml on each node to use profile: cis-1.23 instead of profile: cis-1.6
2. Run standard system-upgrade-controller steps. This step, from the Rancher side, just means selecting the v1.25 version desired from the dropdown when editing the cluster through the UI.

**Describe the solution you'd like**

- For upgrading **provisioned** rke2, lock the only profile version option to `cis-1.23`. If there was previously a selection of `cis-1.6` or `cis-1.5`, give the user a warning. 
- For upgrading **provisioned** k3s, if the user has a `kube-apiserver-arg` that includes `PodSecurityPolicy` in the `admission-plugins` (for example: `kube-apiserver-arg: enable-admission-plugins=NodeRestriction,PodSecurityPolicy,NamespaceLifecycle,ServiceAccount`), give the user a warning with instructions to remove that arg and remove any PSPs from the cluster. 
- For upgrading **imported** rke2, have the user perform the steps mentioned above first on their nodes, then use the Rancher UI to upgrade. 
- For upgrading **imported** k3s, provide a warning that the upgrade should be performed manually, and do not give any option to upgrade from a <v1.25 cluster to a >=v1.25.

In general, if there are any PSPs or the `admission-plugins` include `PodSecurityPolicy`, we should give the user a warning that this is invalid for k8s v1.25+.

**Describe alternatives you've considered**
1. Lots of warnings everywhere
2. Update system-upgrade-controller itself or the Plans or the upgrade images to do any workarounds automagically.

**Comment by rancher-max** [comment]
https://github.com/rancher/rancher/issues/38701

**Comment by jiaqiluo** [comment]
Currently, there is no logic in the backend of Rancher to handle the hardening of an RKE2/K3S cluster, including the following three types: node-driver, custom, and imported.  What that means is that if users set the field "profile" on the cluster via Edit as YAML in Rancher UI, Rancher will pass it to the RKE2/K3S engine and return whatever the engine returns, which could be a rejection of the operation or an eventual failure after the creation/upgrading starts, the behavior is the same as when you use RKE2/K3S standalone outside of Rancher.

**Comment by snasovich** [comment]
Closing this one and separate issues will be created to track couple items related to this.

**Comment by snasovich** [comment]
This has been superseded by a combination of the following issues:
- https://github.com/rancher/rancher/issues/40736
- https://github.com/rancher/rancher/issues/40737
- https://github.com/rancher/rancher/issues/40738
- https://github.com/rancher/rancher/issues/40739
