### ISSUE TITLE
Move/Clone service to different stack

### ISSUE THREAD

**Issue by kaos** [rancher/rancher#3887]
I think it would be nice to be able to migrate services between stacks. This is especially useful in cases where the service has a lot of config that is hard (tiresome and error prone) to copy manually (Thinking of the LB service, with dozens or more of target services with routing rules).

**Comment by Negashev** [comment]
+1

**Comment by ebr** [comment]
I've been doing this by copying the relevant parts of generated docker-compose and rancher-compose YAML. but indeed this would be a super helpful feature. +1.

**Comment by emlagowski** [comment]
+1

**Comment by basbiezemans** [comment]
+1

**Comment by MaxNoe** [comment]
+1

**Comment by feffi** [comment]
+2

**Comment by xlight** [comment]
+1

**Comment by Dongss** [comment]
+1

**Comment by easylo** [comment]
+1

**Comment by JKWalrave** [comment]
+1

**Comment by junkiebev** [comment]
+1

**Comment by flaviuspopan** [comment]
Agreed; it'd be nice to group the Janitor and ECR auto-login stacks from the catalog together since they're both related to maintenance.

**Comment by dionisiolopez** [comment]
+1

**Comment by PhilippHeuer** [comment]
+1

**Comment by brettneese** [comment]
+1

**Comment by alexleekt** [comment]
+1

**Comment by infinitysgame** [comment]
+1

**Comment by pmalsenz** [comment]
+1

**Comment by Sraleik** [comment]
+1

**Comment by shidoh** [comment]
+1

**Comment by Leen15** [comment]
+1

**Comment by arizz96** [comment]
+1

**Comment by pensiero** [comment]
+1

**Comment by d-h-e** [comment]
+1

**Comment by Jeroen7V** [comment]
+1

**Comment by besishblia** [comment]
+1

**Comment by HaiNguyen007** [comment]
+1

**Comment by hcountou** [comment]
+1

**Comment by hcountou** [comment]
And one other thing, if you have created a service in a custom catalog, you can not add this new service to an existing stack.
You can only add services from external sources or from a private registry. If i'm correct.
All the services in a catalog can be launch as create a stack (cattle) but can't be add to a previous stack. 

Anyone tell me if i'm wrong or if you have a alternative. This why i'm looking to create the service outside the stack and then move it to the correct Stack (of course i could create a new stack with all my services combined, but it would mean to stop the previous Stack).

**Comment by vincent99** [comment]
You're looking for `rancher up --upgrade ...`.  See `rancher up -h`.

**Comment by NetScaleNow-Admin** [comment]
+1

**Comment by DirkWolthuis** [comment]
+1

**Comment by avouspierre** [comment]
+1

**Comment by lee5i3** [comment]
+1 this is annoying having to recreate

**Comment by vincent99** [comment]
- This will not be happening in 1.x.
- 2.0 will have the ability to change the stack when cloning.
- We will not be doing move, as renaming existing resources breaks service discovery references unpredictably.
- Please stop +1ing.

**Comment by tfiduccia** [comment]
version - master 2.0 8/28
Verified added and works

**Comment by HypertextPP** [comment]
+1

**Comment by naisanza** [comment]
@tfiduccia Where? I don't see the option to select a stack for it to be cloned into

![screenshot from 2017-12-23 18-10-08](https://user-images.githubusercontent.com/1614425/34323216-8e3beb44-e80c-11e7-80b8-d21b3357b8b6.png)

**Comment by vincent99** [comment]
> version - master 2.0 8/28

Only in 2.0 (previews).

**Comment by naisanza** [comment]
Ah I just saw `master` branch and stopped reading
