### ISSUE TITLE
[Azure AD] Always check access token from Microsoft

### ISSUE THREAD

**Issue by maxsokolovsky** [rancher/rancher#38880]
It would be good to add this guardrail to prevent users from losing access to Rancher via Azure AD or getting their Azure AD setup in an invalid state. This can happen if they don't follow the documentation in setting the necessary permissions for their App registrations in Azure for Rancher v2.6.7+.

On initial Azure AD setup or subsequent login or search attempts, always check the access token to Microsoft Graph if it does not have the necessary permissions.

**Comment by anupama2501** [comment]
Moving this issue to test as there is a design change and might not be needing this check anymore.
