### ISSUE TITLE
Refactoring or use a faster database for Rancher

### ISSUE THREAD

**Issue by Negashev** [rancher/rancher#3888]
Rancher Version: 0.59.1

Docker Version:1.7.1-1.10.2

OS: CentOS 6.6 and CentOS 7

Steps to Reproduce: N/A

Results: Mysql becomes very slow to rancher. If you use SATA drives

Expected: Refactoring or use a faster database
Quick solution to #3750

**Comment by bacheson** [comment]
Provide some specific information. I'm running 1200 containers across 30 stacks. MySQL doesn't break a sweat.

I have to manually run optimize to reclaim disk space on certain tables from time to time. Other then that MySQL is more than adequate to handle Rancher's workload.

**Comment by Negashev** [comment]
@bacheson, Could you share what requests are for mysql optimization. We have it stored the data in July 2015, you may clean the debris from mysql?

**Comment by cloudnautique** [comment]
@bacheson , curious across how many hosts?

@Negashev, we have been analyzing the DB usage quite a bit as we head towards GA. We should have some improvements in the coming RCs before GA.

**Comment by Negashev** [comment]
@cloudnautique , Then I think you can close this issue

**Comment by cloudnautique** [comment]
Thanks.

**Comment by Negashev** [comment]
We have tried to expand mysql separate from the rancher, and add configuration


`/rancher_mysql_cnf/config-file.cnf`
```
[mysqld]
innodb_buffer_pool_size = 2G
```
This helped a little

and start rancher with mysql

```
docker run --name=rancher_mysql -it -d -v /rancher_mysql:/var/lib/mysql -v /rancher_mysql_cnf:/etc/mysql/conf.d --restart=always -e 'MYSQL_ROOT_PASSWORD=secretpassword' mysql

docker run -d --link rancher_mysql:mysql -e 'CATTLE_DB_CATTLE_MYSQL_HOST=mysql' -e CATTLE_DB_CATTLE_MYSQL_PORT=3306 -e CATTLE_DB_CATTLE_MYSQL_NAME=cattle -e CATTLE_DB_CATTLE_USERNAME=root -e 'CATTLE_DB_CATTLE_PASSWORD=secretpassword' --restart=always -p 80:8080 - e JAVA_OPTS="- Xmx4096m" rancher/server:latest
```

**Comment by demarant** [comment]
@Negashev we run in similar performance issues. we have around 700 containers and we had to set 
innodb_buffer_pool_size = 11G ... yes 11G so we run rancher on a 16GB ram host and so far so good.
see forum post https://forums.rancher.com/t/what-is-the-max-nr-of-hosts-and-containers-rancher-is-able-to-manage/3681/3
