### ISSUE TITLE
Right-click menu stops working

### ISSUE THREAD

**Issue by ebr** [rancher/rancher#3889]
Rancher Version: 0.59.0

Docker Version: 1.10.2

OS: Mac OS X 10.11.2, Google Chrome 48

Steps to Reproduce: 

 - Applications -> service -> click the `(i)`
 - Right-click the container (green circle) -> display Logs or execute Shell
 - close the Logs or Shell popup
 - Right-click the container (green circle) 

Results: pop-up menu no longer works; page refresh required

Expected: pop-up menu should continue working without a page refresh

**Comment by vincent99** [comment]
Pretty sure this was fixed already but can you verify

**Comment by tfiduccia** [comment]
This has a design change and working in next release.

**Comment by tfiduccia** [comment]
Version - master 3/9
Verified fixed

@ebr - check with next release
