### ISSUE TITLE
[release/v2.7] Forwardport of Add 1.23 for EKS

### ISSUE THREAD

**Issue by Oats87** [rancher/rancher#38898]
Forwardport of https://github.com/rancher/rancher/issues/38837

**Comment by Oats87** [comment]
EKSv2 1.23 was added with https://github.com/rancher/ui/pull/4890

**Comment by markusewalker** [comment]
**QA TEST PLAN**
1. Setup Rancher, create a standard user and login as that user.
2. Navigate to Cluster Management > Amazon EKS.
3. Fill out the requested prompts and in the `Managed Node Groups`, fill out a custom `AMI ID` that has been updated for EKS.
     - Ensure that the version is `1.23`.
4. Provision the cluster and validate that it is in a state of `Active` in Cluster Management and Cluster Explorer
5. Repeat steps 3-4 for all supported EKS versions.

**Comment by snasovich** [comment]
Ready to test on v2.7-head.

**Comment by markusewalker** [comment]
Validated that this is addressed in `v2.7-head` https://github.com/rancher/rancher/commit/c567ef3f2bd13c2f2a5819242ab88cd334b1ae79.

**ENVIRONMENT DETAILS**
- Rancher install: Docker
- Rancher version: `v2.7-head` https://github.com/rancher/rancher/commit/c567ef3f2bd13c2f2a5819242ab88cd334b1ae79
- Browser: Chrome

**TEST RESULT
PASS**

**VERIFICATION STEPS**
1. Setup Rancher, created a standard user and logged in as that user.
2. Navigated to Cluster Management > Amazon EKS.
3. Filled in all the prompts, ensured that the K8s version is `1.23` and created the cluster.
4. Validated that the cluster is provisioned and that the cluster and nodes are in a state of `Active` in Cluster Management and Cluster Explorer:
![image](https://user-images.githubusercontent.com/52591819/192573535-c24afef2-e93a-4608-bb45-46c71b731fd5.png)
![image](https://user-images.githubusercontent.com/52591819/192573609-2cd66ca0-e573-42f1-a776-edf4c67ec90b.png)
![Screen Shot 2022-09-27 at 8 47 29 AM](https://user-images.githubusercontent.com/52591819/192573744-3a2c60f9-6006-4f33-8327-b4499178f377.png)
6. Navigated to the AWS Management Console > EC2 > Instances.
7. Validated that the associated instances created use the updated AMI ID that the PR uses.
