### ISSUE TITLE
[BUG, RKE2] cluster with windows node fails to deploy System Upgrade Controller to windows node, `Write-EventLog : The source name "rancher-wins" does not exist on computer "localhost".` on pods using `rancher-wins` image

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#38896]
**Rancher Server Setup**
- Rancher version: v2.6-head (a3b5237)
- Installation option (Docker install/Helm Chart): docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):n/a
- Proxy/Cert Details:n/a

**Information about the Cluster**
- Kubernetes version:1.24.4+rke2r1
- Cluster Type (Local/Downstream):downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):vsphere

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: standard user, cluster owner

**Describe the bug**

when deploying a windows cluster (1etcd, 1cp, 2workers are linux, 1 worker is windows after the linux nodes are all active), the SUC job fails to deploy to the windows node. 

**To Reproduce**

* in vsphere, deploy a windows cluster  (1etcd, 1cp, 2workers are linux pools, 1 worker is windows pool)
* wait for the cluster to get to an active state

**Result**
pods using `rancher-wins` fail with this error in their logs 
```
Creating C:\etc\rancher\wins
Tue, Sep 13 2022 2:11:51 pm | Write-EventLog : The source name "rancher-wins" does not exist on computer
Tue, Sep 13 2022 2:11:51 pm | "localhost".
Tue, Sep 13 2022 2:11:51 pm | At C:\run.ps1:103 char:5
Tue, Sep 13 2022 2:11:51 pm | + Write-EventLog -LogName "$LogName" -Source "$Source" -Message "$M ...
Tue, Sep 13 2022 2:11:51 pm | + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Tue, Sep 13 2022 2:11:51 pm | + CategoryInfo : InvalidOperation: (:) [Write-EventLog], InvalidO
Tue, Sep 13 2022 2:11:51 pm | perationException
Tue, Sep 13 2022 2:11:51 pm | + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteEventLogCommand
```

**Expected Result**

windows should allow suc to deploy

**Screenshots**

**Additional context**

unable to test in a custom cluster with this version due to https://github.com/rancher/rancher/issues/38893

**Comment by Oats87** [comment]
Ugh, this should not have been closed.

**Comment by snasovich** [comment]
This is ready to test on v2.7-head.

**Comment by slickwarren** [comment]
tested on rancher v2.7-head (62f7959):
* deployed windows 2022 rke2 cluster (v1.24.4+rke2r1) -- pass
  * after adding the windows node, it takes about 10 minutes for the SUC job to finish.
