### ISSUE TITLE
[BUG] RKE2 System Images Are Not Pulled From Cluster Level Registry 

### ISSUE THREAD

**Issue by HarrisonWAffel** [rancher/rancher#38890]
**Rancher Server Setup**
- Rancher version: 2.6.5 and up
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): n/a
- Proxy/Cert Details: n/a

**Information about the Cluster**
- Kubernetes version: any
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): RKE2/K3s

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: admin

**Describe the bug**

When provisioning an RKE2 cluster configured with a cluster level registry, while also having a global level registry defined in the Rancher global settings, not all system images are pulled from the cluster level registry. 

**To Reproduce**

1. Create 1 unauthenticated and 1 authenticated registry containing all system images for a released version of Rancher (2.6.7 for example)
  1a. The unauthenticated registry will act as your global level registry 
  1b. The authenticated registry will act as your cluster level registry 
2. Change the global system-default-registry in the Rancher global settings to point to your unauthenticated registry 
3. Begin to create an RKE2 cluster, ensuring you chose the correct version of k8's for the images loaded into your registries
4. In the `Cluster Configuration` section, select `Registries`
5. The `Pull images for Rancher from a private registry` option should already be selected, and the value should default to your global level registry. Change the value to point to your cluster level registry.
6. For `Authentication` select `Create a basic HTTP Auth Secret` and pass in the username and password of your authenticated registry 
7. Create the cluster

**Result**
Navigate to the cluster explorer, and view all pods within all namespaces. Observe that a majority of the images pulled are from the global level registry, and not he cluster level registry. 

**Expected Result**

All images should be pulled from the cluster level registry if one is defined. 

**Additional context**
**This change will require a release note, as it will impact existing clusters which may or may not have the cluster level registry configured correctly. Additional documentation should also be added to denote this change in behavior.**

**Comment by HarrisonWAffel** [comment]
This issue is related to https://github.com/rancher/rancher/issues/35189

**Comment by HarrisonWAffel** [comment]
This work will be included in `2.7.0-rc1`

### Root cause
Rancher was passing the `--system-default-registry` flag to RKE2 even in situations where a cluster level registry was defined, causing images to be pulled from the wrong registry. 
  
### What was fixed, or what changes have occurred
If a cluster level private registry is defined in the UI, this flag will not be passed. System images will be pulled from the correct registry defined in `registries.yaml`. 
  
### Areas or cases that should be tested  
1. Create 1 unauthenticated and 1 authenticated registry containing all system images for a released version of Rancher (Images for registries are generated with reach release and RC, and can be located in the `rancher-images.txt` file.) 
  1a. The unauthenticated registry will act as your global level registry 
  1b. The authenticated registry will act as your cluster level registry 
2. Change the global `system-default-registry` in the Rancher global settings to point to your unauthenticated registry 
3. Begin to create an RKE2/K3s cluster, ensuring you chose the correct version of k8's for the images loaded into your registries
4. In the `Cluster Configuration` section, select `Registries`
5. The `Pull images for Rancher from a private registry` option should already be selected, and the value should default to your global level registry. Change the value to point to your cluster level registry.
6. For `Authentication` select `Create a basic HTTP Auth Secret` and pass in the username and password of your authenticated registry 
7. Create the cluster and wait for it to become available 
8. Navigate to the `Cluster Explorer`
9. In the top right corner, select all namespaces 
10. Navigate to the `pods` section of the explorer so that all pods are visible
11. Check that all images pulled by default (system-default-images) are pulled from the cluster level registry and not the global level registry. 
12. It is expected that the `fleet-agent` image is not pulled from the cluster level registry, this is a known issue that was intentionally not resolved in this PR 

The above steps should be repeated for K3s clusters, as they both share the same logic 

### What areas could experience regressions?
  
situations where only the global system-default-registry has been defined, however I have done manual testing of this and have seen no issues.

**Comment by Josh-Diamond** [comment]
Ticket #38890 - Test Results - WIP
---

With HA Helm:

To be verified on rancher `v2.7-head`:

- Scenario 1 - 
   - Test: `Provision a downstream AWS Node driver RKE2 cluster, w/ authenticated registry configured`
   - Result:
- Scenario 2 - `Provision a downstream AWS Node driver K3s cluster, w/ authenticated registry configured`
   - Test:
   - Result:
- Scenario 3 - `Provision downstream AWS Node driver RKE2 + K3s clusters, w/ global (un-auth'd) registry configured`
   - Test:
   - Result:

---

Reproduced - ✅ - Friday September 23, 2022

On rancher `v2.6.8`:
1. Create 2 private registries - [1 authenticated + 1 un-authenticated]
2. Fresh install of rancher `v2.6.8`
3. From `Global Settings > system-default-registry`, update field to point to un-authenticated registry created in step 1
4. As admin, provision a downstream AWS Node driver RKE2 cluster, w/ authenticated registry configured
5. Reproduced - Images are primarily pulled from global registry, not cluster registry

Screenshot:

<img width="988" alt="reproduced" src="https://user-images.githubusercontent.com/46494969/192029211-8bcba621-b8f1-4d02-be9a-c1933194c549.png">

---

Scenario 1:
**Validation Not Yet Started**

**Comment by deniseschannon** [comment]
Can we validate with a cluster registry with and without authentication?

**Comment by Josh-Diamond** [comment]
@deniseschannon yes, Scenario 3 was specifically for that use case

**Comment by sowmyav27** [comment]
Test cases to be included
|  Cluster Type | Cluster Level Registry    | Global Level registry  | Status  |
|---|---|---|---|
| RKE2  | Yes; Authenticated  | Yes; Not Authenticated  |   |
| RKE2  | Yes; Authenticated  | Not Set  |   |
| RKE2  | Yes; Not Authenticated  | Yes; Not Authenticated  |   |
| RKE2  | Yes; Not Authenticated  | Not Set  |   |
| K3s  | Yes; Authenticated  | Yes; Not Authenticated  |   |
| K3s  | Yes; Authenticated  | Not Set  |   |
| K3s  | Yes; Not Authenticated  | Yes; Not Authenticated  |   |
| K3s  | Yes; Not Authenticated  | Not Set  |   |
| RKE2  | Not Set | Yes; Not Authenticated  |   |
| k3s  | Not Set | Yes; Not Authenticated  |   |

**Comment by Josh-Diamond** [comment]
Awaiting rancher `v2.7.0-rc2` to resume testing

**Comment by Josh-Diamond** [comment]
Awaiting test results from https://github.com/rancher/rancher/issues/39104;

Will request RC for `v2.7` to resume testing once that has been validated + closed

**Comment by Josh-Diamond** [comment]
#39104 - ✅ 
Requested `v2.7.0-rc3`
Will resume testing when RC is published

**Comment by Josh-Diamond** [comment]
Ticket #38890 - Test Results
---

Reproduction on `v2.6.8` found [here](https://github.com/rancher/rancher/issues/38890#issuecomment-1256616482)

Verified on rancher `v2.7.0-rc3` w/ k8s `v1.24.4+rke2r1` || `v1.24.6+k3s1`

|  Cluster Type | Cluster Level Registry    | Global Level registry  | Status  |
|---|---|---|---|
| RKE2  | Yes; Authenticated  | Yes; Not Authenticated  | ✅  |
| RKE2  | Yes; Not Authenticated  | Yes; Not Authenticated  | ✅  |
| K3s  | Yes; Authenticated  | Yes; Not Authenticated  | ✅  |
| K3s  | Yes; Not Authenticated  | Yes; Not Authenticated  | ✅  |
