### ISSUE TITLE
Password that begins or ends with space is broken

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3892]
Version - 3/9

Steps to Reproduce: 
1.  create a password for local auth that beings or ends with a password

Results: space gets lost

Expected: space should not get lost

**Comment by vincent99** [comment]
@hibooboo2 I need fields that are passwords like `credential.secretValue` to be `type: 'password'`, so that the UI can know not to trim them like it does for regular strings.

**Comment by tfiduccia** [comment]
Version - master UI 3/18
Verified fixed
