### ISSUE TITLE
[BUG] Unable to provision K3s Custom Clusters on Ubuntu 18.04

### ISSUE THREAD

**Issue by jameson-mcghee** [rancher/rancher#38941]
**Rancher Server Setup**
- Rancher version: v2.6-head (Commit ID: a3b5237) & v2.6.8
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1 - v1.23.8
- Proxy/Cert Details: N/A

**Information about the Cluster**
- Kubernetes version: v1.24.4+k3s1 & v1.23.10+k3s1
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Custom K3s

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): Admin & Standard Cluster Owner
  - If custom, define the set of permissions: N/A

**Describe the bug**
Users are unable to provision a downstream K3s Custom Cluster using Kubernetes versions v1.24.4+k3s1 & v1.23.10+k3s1 on Ubuntu 18.04. When attempted, they receive appear to be stuck in the "Updating" state with the message "Configuring control plane node(s) {node name}: waiting for cluster agent to connect". The Control Plane node is stuck in the "Reconciling" state with the message "Waiting for cluster agent to connect" while the ETCD and worker nodes are stuck in the "Waiting for Node" state. No other errors are present in the UI.

**To Reproduce**

1. Create a Custom K3s cluster using k8s version v1.24.4+k3s1 and using Ubuntu 18.04 OS.
- AMIs that have reproduce this issue are: ami-00978328f54e31526 & ami-0c3357e45c1a0eebe

**Result**
Note that the cluster will not provision

**Expected Result**
The cluster provisions successfully without issue

**Screenshots**
v2.6.8:
![image](https://user-images.githubusercontent.com/13294321/190513905-fe7ea254-fe83-4783-b6a8-32287086622f.png)
![image](https://user-images.githubusercontent.com/13294321/190513917-5b4ca2db-f79c-4c89-b563-245b29d19f61.png)

v2.6-head:
![image](https://user-images.githubusercontent.com/13294321/190513942-39770e0f-f1f4-47dd-bc99-d12f5d4802a9.png)

**Comment by jameson-mcghee** [comment]
I added this in the "Additional Context" section, but I wanted to add a separate comment with it as well so it doesn't get over looked:

**VERY IMPORTANT NOTE:** I was able to successfully provision K3s Custom clusters on both v2.6-head and v2.6.8 using k8s versions v1.23.8+k3s2 & v1.24.2+k3s2.

**Comment by Sahota1225** [comment]
Ubuntu 18.04 is no longer supported. Therefore, closing the ticket.
