### ISSUE TITLE
[BUG] Monitoring - Alertmanager is not working when TLS enabled

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#38945]
**Rancher Server Setup**
Rancher Cluster:
Rancher version: 2.6.5
Number of nodes: 3
Node OS version: Ubuntu

Downstream Cluster:
Number of Downstream clusters: 2
Node OS: Ubuntu
RKE/RKE2/K3S version: RKE

Issue description:
Customer wants to use the Alert manager with TLS enabled ( Including username and password). 

Business impact:
Unable to use monitoring

Troubleshooting steps:
We have enabled monitoring using the Rancher chart and configured the Email.

    We have enabled Legacy monitoring for checking : 

    For smtp relay (no authentication needed) alerts works
    For smtp (with authentication)
    “Test” option works (we received the email)
    BUT Alarms are not arriving

    Alert monitor (new monitoring):
        “Test” option doesn’t exist, so we cannot check it
        Alarms are not arriving
    For smtp relay (no authentication needed) alerts works
    For smtp (with authentication)

To make sure no blocking to the ports and authentication works fine,  we sent the email manually as below

        Email using authentication from a KaaS server and it is working

Repro steps:

Rancher 2.6.5

Install the latest Monitoring chart from Apps/Market place

Configure Receiver as Email and Routes

Use the TLS enabled and provide the SMTP relay user name and password.

For testing enabling Legacy and configure the Alerts and do a test and its sending the emails but when configuring the Routes its not sending.

Workaround:
Is work around available and implemented? NO
What is the workaround: 

Actual behavior:
Email Alerting is not working when the Authentication is enabled. 

Expected behaviour:
Email Alerting should work when the Authentication is enabled. 

Additional info available in
SURE-4788

**Comment by geethub97** [comment]
Closing this based on comments here https://github.com/rancher/rancher/issues/40307 and https://jira.suse.com/browse/SURE-4788
