### ISSUE TITLE
Prepare rancher-webhook chart for 2.7.0

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#38943]
rancher-webhook chart needs to be updated for 2.7 by 

1) File a PR removing the `doNotRelease` flag form the package.yaml; in this PR, you will also want to make any changes that need to be made to update the chart to the version you intend to release in 2.7. For example, for a charts like rancher-aks-operator / rancher-gke-operator / rancher-eks-operator, you will need to create a new branch in upstream for Rancher 2.7, cut the first release for that chart, and introduce those changes in to the package.yaml as well before removing the doNotRelease flag
2) To make your chart available for 2.7, almost every chart will also have to modify the Rancher Version annotations that scope it to 2.6, i.e. https://github.com/rancher/charts/blob/2e058e93ee01f2980e4750148842dd7f04262b38/charts/fleet-agent/100.0.5%2Bup0.3.11/Chart.yaml#L8
3) Once the PR is merged, ensure that the brand new chart is smoke tested by QA/dev

**Comment by KevinJoiner** [comment]
To validate

Deploy rancher `v2.7.0-rc3`
Open a shell on the `local` cluster
Run `helm list -n cattle-system` in the local cluster
Verify chart versions of rancher webhook is: `rancher-webhook-2.0.0+up0.3.0-rc4`

**Comment by dasarinaidu** [comment]
I deployed v2.7-head and seeing correct rancher-webhook version and closing this card.

![image](https://user-images.githubusercontent.com/22034884/194949416-493968cc-7336-4d8d-9cb0-31b0ff2f0d42.png)
