### ISSUE TITLE
Network Errors following upgrade from 0.56.1 to 0.59.1

### ISSUE THREAD

**Issue by Rucknar** [rancher/rancher#3894]
Upgraded the rancher server, the hosts and agents have upgraded and come back just fine, however...

We have two possibly seperate issues. The first is the error below, this occours when rancher is trying to start some existing rancher supplied haproxy instances, i'm guessing due to it's upgrade of haproxy. The log the below error to the rancher server logs: 

```
2016-03-09 19:11:21,677 ERROR [:] [] [] [] [ecutorService-3] [.p.c.v.i.ConfigItemStatusManagerImpl] Failed null, exit code [2] output [INFO: Updating healthcheck
INFO: Downloading http://XX.XX.XX.XX:8080/v1//configcontent//healthcheck current=healthcheck-111-ccf4b6729e29cd38f161b88f68587ac9ac339d69de024b747bd613846c7185fe
INFO: Running /var/lib/cattle/download/healthcheck/healthcheck-123-ada6114082d48a8c54a7efa738736e92d651c6e76040360e010ffc0c75260b08/apply.sh
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.JqJMuQTvim --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyserver keyserver.ubuntu.com --recv-keys 1C61B9CD
gpg: requesting key 1C61B9CD from hkp server keyserver.ubuntu.com
?: keyserver.ubuntu.com: Connection refused
gpgkeys: HTTP fetch error 7: couldn't connect: Connection refused
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
[[scripts.sh:184] script_env
[[scripts.sh:109] '[' -n http://XX.XX.XX.XX:8080/v1 ']'
[[scripts.sh:110] return
[[scripts.sh:186] export CATTLE_HOME=/var/lib/cattle
[[scripts.sh:186] CATTLE_HOME=/var/lib/cattle
[[scripts.sh:187] export CATTLE_CONFIG_URL=http://XX.XX.XX.XX:8080/v1
[[scripts.sh:187] CATTLE_CONFIG_URL=http:///XX.XX.XX.XX:8080/v1
[[scripts.sh:188] export CATTLE_STORAGE_URL=http://XX.XX.XX.XX:8080/v1
[[scripts.sh:188] CATTLE_STORAGE_URL=http://XX.XX.XX.XX:8080/v1
[apply.sh:5] haproxy -v
[apply.sh:5] grep -q 'version 1.6'
[apply.sh:6] apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 1C61B9CD
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.FgtvhNKtdB --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyserver keyserver.ubuntu.com --recv-keys 1C61B9CD
gpg: requesting key 1C61B9CD from hkp server keyserver.ubuntu.com
?: keyserver.ubuntu.com: Connection refused
gpgkeys: HTTP fetch error 7: couldn't connect: Connection refused
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
]
```

Sort of looks like a non-rancher issue but impacts that feature none the less. 

**Other issue**
More importantly, i'm unable to start new containers, they get stuck in 'networking' state, i can't see much in the API nor can i see any evidence of them in the output of `docker ps -a`

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v0.59.1` Cattle: `v0.148.1` UI: `v0.90.0` |
|Access|`localauth` `admin`|
|Route|`null`|

**Comment by Rucknar** [comment]
Okay, 

Start issues i've tracked down to the HTTP1.1 bug. That's fine, i've moved those to 1.0 and that part is working. It looks like however none of the haproxy upgrades are successful. The above is being spammed to the rancher logs, we run quite a few of these, any idea how i might manually force an upgrade?

**Comment by Rucknar** [comment]
https://github.com/rancher/rancher/issues/3499 might be related.

**Comment by Rucknar** [comment]
So the above was basically every haproxy instance i had all trying to upgrade but failing. 
I've deleted all of them and purged, they all came back up as 1.6.3 and seem to be working fine.

**Comment by warroyo** [comment]
@Rucknar I am having the container start up issues (stuck in networking state) how did you fix this?

**Comment by deniseschannon** [comment]
@warroyo Please try deleting your network agents, which will cause new network agents to be respawned. The upgrade to HAproxy v1.6 sometimes fails, which cause this to happen.
