### ISSUE TITLE
Prepare rancher-external-ip-webhook chart for 2.7.0

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#38954]
rancher-external-ip-webhookchart needs to be updated the charts for 2.7 by

- File a PR removing the doNotRelease flag form the package.yaml; in this PR, you will also want to make any changes that need to be made to update the chart to the version you intend to release in 2.7. For example, for a charts like rancher-aks-operator / rancher-gke-operator / rancher-eks-operator, you will need to create a new branch in upstream for Rancher 2.7, cut the first release for that chart, and introduce those changes in to the package.yaml as well before removing the doNotRelease flag

- To make your chart available for 2.7, almost every chart will also have to modify the Rancher Version annotations that scope it to 2.6, i.e. https://github.com/rancher/charts/blob/2e058e93ee01f2980e4750148842dd7f04262b38/charts/fleet-agent/100.0.5%2Bup0.3.11/Chart.yaml#L8

- Once the PR is merged, ensure that the brand new chart is smoke tested by QA/dev

**Comment by KevinJoiner** [comment]
To validate

- Deploy `v2.7.0-rc3` on `k8s v1.21` (can be done via AWS cluster)
- Install `External IP Webhook` into the local cluster
    - Apps -> Charts -> Search `External IP Webhook`
    - Leave configuration options empty
- Verify chart versions are
      ```
      rancher-external-ip-webhook:
      101.0.0+up1.0.1
      ```

**Comment by cbron** [comment]
Moving this out from test because we need to remove from 2.7.

**Comment by sowmyav27** [comment]
To validate

- On 2.6.8 - verify this chart is available on the local cluster.
- on 2.7-head, verify this chart doesn't show up.

**Comment by dasarinaidu** [comment]
I validated this card on both v2.7-head and v2.6.8 and seeing below observations:
1. On v2.7-head -- I am seeing the app "External IP Webhook" on my local cluster
2. On v2.7-head ->Local cluster->Apps-> "External IP Webhook" : I did not see a version with `rancher-external-ip-webhook: 101.0.0+up1.0.1`

**Installed Versions:**
    a. RANCHER_CHART_VERSION=2.7.0-rc3
    b. RANCHER_IMAGE_TAG=v2.7-head
    c. RKE VERSION= v1.4.0-rc3

3. On v2.6.8 -- I am NOT seeing the "External IP Webhook" on my local cluster

**Installed Versions:**
   a. RANCHER_CHART_VERSION=2.6.8
   b. RANCHER_IMAGE_TAG=v2.6.8
   c. RKE_VERSION=v1.3.13

<img width="841" alt="image" src="https://user-images.githubusercontent.com/22034884/195929987-ff6945be-3601-4d8c-9de2-f8d53405f514.png">

<img width="1496" alt="image" src="https://user-images.githubusercontent.com/22034884/195931708-860a70ac-526c-43da-9760-dabd6e1d7bc9.png">


<img width="1506" alt="image" src="https://user-images.githubusercontent.com/22034884/195931544-31a78445-8008-4d23-b2ca-0ca88b684a38.png">

**Comment by dasarinaidu** [comment]
I revalidated the ticket on `v2.7.0-rc3` and I did not see the app "External IP Webhook".

I am closing this ticket.

<img width="1443" alt="image" src="https://user-images.githubusercontent.com/22034884/195960369-701ce3fc-14ff-42cd-b927-5dca11fd5df7.png">
