### ISSUE TITLE
Prepare rancher-csp-adapter chart for 2.7.0

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#38953]
rancher-csp-adapter chart needs to be updated the charts for 2.7 by

-  File a PR removing the doNotRelease flag form the package.yaml; in this PR, you will also want to make any changes that need to be made to update the chart to the version you intend to release in 2.7. For example, for a charts like rancher-aks-operator / rancher-gke-operator / rancher-eks-operator, you will need to create a new branch in upstream for Rancher 2.7, cut the first release for that chart, and introduce those changes in to the package.yaml as well before removing the doNotRelease flag

- To make your chart available for 2.7, almost every chart will also have to modify the Rancher Version annotations that scope it to 2.6, i.e. https://github.com/rancher/charts/blob/2e058e93ee01f2980e4750148842dd7f04262b38/charts/fleet-agent/100.0.5%2Bup0.3.11/Chart.yaml#L8

- Once the PR is merged, ensure that the brand new chart is smoke tested by QA/dev

**Comment by brudnak** [comment]
# ✅ PASSED

## Reproduction Environment

#### Not required.

<hr>

## Validation Environment

| Component                        | Version / Type                           |
| -------------------------------- | ---------------------------------------- |
| Rancher version                  | 2.7.0-rc3                                |
| Installation option              | Helm (high availability)                 |
| If Helm Chart k8s cluster        | v1.22.13-eks-15b7512                     |
| Cert Details                     | Let's Encrypt                            |
| Helm version                     | v2.16.8-rancher2                         |
| Downstream cluster type          | RKE1 Linode                              |
| Downstream K8s version           | v1.24.6                                  |
| Authentication providers enabled | local                                    |
| Logged in user role              | Administrator & Standard User            |
| Browser type                     | Google Chrome                            |
| Browser version                  | 106.0.5249.119 (Official Build) (x86_64) |
| CSP adapter chart version        | v2.0.0-rc1                               |

<details>
    <summary>🚨 Additional Validation Setup Details: Click to Expand</summary>

```shell
helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=$URL_VAR \
  --set bootstrapPassword=$PW_VAR \
  --set ingress.tls.source=letsEncrypt \
  --set letsEncrypt.email=$EMAIL_VAR \
  --set letsEncrypt.ingress.class=nginx \
  --set ingress.ingressClassName=nginx \
  --version 2.7.0-rc3
  --set extraEnv\[0\].name="CATTLE_PROMETHEUS_METRICS" --set-string extraEnv\[0\].value=true
```

```shell
helm install rancher-csp-adapter rancher-charts/rancher-csp-adapter --namespace cattle-csp-adapter-system --set aws.enabled=true --set aws.roleName=$ROLE_NAME_VAR --set-string aws.accountNumber=$ACC_NUM_VAR --set image.tag=v2.0.0-rc1
```

</details>

## Validation steps

1. Verify license manager is setup
2. Create an EKS cluster
3. Install Rancher with the commnad noted above
4. Create an OIDC provider
5. Create an IAM role
6. Create the adapter namespace
7. Install the csp adapter Chart - see the install command noted above
8. Run P0 test cases described in internal docs

## Additional Info

## RESULTS

#### ✅ Expected
P0 use cases to pass

#### ✅ Actual
P0 use cases passed
