### ISSUE TITLE
Prepare system-upgrade-controller chart for 2.7.0

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#38958]
system-upgrade-controller chart needs to be updated the charts for 2.7 by

- File a PR removing the doNotRelease flag form the package.yaml; in this PR, you will also want to make any changes that need to be made to update the chart to the version you intend to release in 2.7. For example, for a charts like rancher-aks-operator / rancher-gke-operator / rancher-eks-operator, you will need to create a new branch in upstream for Rancher 2.7, cut the first release for that chart, and introduce those changes in to the package.yaml as well before removing the doNotRelease flag

- To make your chart available for 2.7, almost every chart will also have to modify the Rancher Version annotations that scope it to 2.6, i.e. https://github.com/rancher/charts/blob/2e058e93ee01f2980e4750148842dd7f04262b38/charts/fleet-agent/100.0.5%2Bup0.3.11/Chart.yaml#L8

- Once the PR is merged, ensure that the brand new chart is smoke tested by QA/dev

**Comment by rishabhmsra** [comment]
Re-opening this issue:

Validated on rancher v2.7-head(4092002) and rancher v2.7.0-rc3
- Created a RKE2 v1.24.6+rke2r1 cluster
- Validated `system-upgrade-controller` chart version under `Apps -> Installed Apps`

Result:
- Chart version `100.0.3+up0.3.3` is present which is different from what's mentioned in the [PR](https://github.com/rancher/charts/pull/2114#issuecomment-1259922528). See the incorrect chart versions below:

- **On rancher v2.7-head**

![suc-head](https://user-images.githubusercontent.com/36376154/195016987-0ca2b085-4e8c-4406-9499-b24e8bae2797.png)
- **On rancher v2.7.0-rc3**

![suc-rc3](https://user-images.githubusercontent.com/36376154/195016995-48d68c41-e72b-4d10-bbbb-81341524eadc.png)

**Comment by kinarashah** [comment]
Available to test with v2.7-head after `https://drone-publish.rancher.io/rancher/rancher/8433` passes.

**Comment by rishabhmsra** [comment]
Validated on rancher v2.7-head(0dcfd16)

Steps followed:
- Provisioned single node all role rke2 `v1.24.6+rke2r1` cluster
- Validated system-upgrade-controller chart version under Apps -> Installed Apps

Result:
- Chart version `101.0.0+up0.3.3` is present, hence closing the issue.
![suc](https://user-images.githubusercontent.com/36376154/196138853-498a5648-81d8-449a-94af-f572fbc1e108.png)
