### ISSUE TITLE
Prepare rancher-eks-operator chart for 2.7.0

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#38956]
rancher-eks-operator chart needs to be updated the charts for 2.7 by

- File a PR removing the doNotRelease flag form the package.yaml; in this PR, you will also want to make any changes that need to be made to update the chart to the version you intend to release in 2.7. For example, for a charts like rancher-aks-operator / rancher-gke-operator / rancher-eks-operator, you will need to create a new branch in upstream for Rancher 2.7, cut the first release for that chart, and introduce those changes in to the package.yaml as well before removing the doNotRelease flag

- To make your chart available for 2.7, almost every chart will also have to modify the Rancher Version annotations that scope it to 2.6, i.e. https://github.com/rancher/charts/blob/2e058e93ee01f2980e4750148842dd7f04262b38/charts/fleet-agent/100.0.5%2Bup0.3.11/Chart.yaml#L8

- Once the PR is merged, ensure that the brand new chart is smoke tested by QA/dev

**Comment by sowmyav27** [comment]
On 2.7-head,

- Deploy EKS cluster
- Navigate to Local cluster's CLuster Explorer --> Apps --> Installed charts
- Verify the version of EKS-operator and crd are
```
rancher-eks-operator:
- 101.0.0+up1.1.5-rc1
rancher-eks-operator-crd:
- 101.0.0+up1.1.5-rc1
```

**Comment by rishabhmsra** [comment]
Re-opening this issue:
- On rancher v2.7-head(0de241c), provisioned EKS v1.23 k8s cluster, but it's getting stuck into Provisioning state with below error in provisioning logs:
```
[ERROR] Failed to install system chart rancher-eks-operator: failed to install , pod cattle-system/helm-operation-kn9kd exited 123
[ERROR] Failed to install system chart rancher-eks-operator: failed to install , pod cattle-system/helm-operation-959dl exited 123
[INFO] waiting for cluster create [c-x6zjl] to start
[INFO] waiting for cluster create [c-x6zjl] to start
```

**Comment by Josh-Diamond** [comment]
Ticket #38956 - Test Results - ❌ 
---

With Docker on a single-node instance:

Verified on rancher `v2.7-eab28ddaeeb772894c35a7e86b0e37d3cb484b8c-head`:
1. Fresh install of rancher `v2.7-head`
2. Provision a downstream EKS cluster w/ k8s `v1.23`
3. Veri-FAILED: 
    - EKS cluster fails to provision
    - `eks-config-operator` is NOT installed
    - UI Error seen: `Imagepullbackoff`
    - Log Errors:
```logs
[ERROR] error syncing REDACTED: handler eks-operator-controller: waiting eks crd to be initialized, cluster: REDACTED, requeuing
[ERROR] Failed to install system chart rancher-eks-operator: failed to install , pod cattle-system/helm-operation-REDACTED exited 123
```
   - Attempted to install `rancher/eks-operator:v1.1.5-rc2`; v1.1.5-rc2 not published on dockerhub;
   - EKS cluster made no progress in provisioning, although, local cluster reached its maxPodLimit, possibly as a result of EKS cluster provisioning attempt
   
Screenshots:

`UI Error`
![ui](https://user-images.githubusercontent.com/46494969/193908132-505e558c-c345-4253-8a62-9a4327e85d39.png)

`maxPodLimit - Local`
![maxResourceLimit](https://user-images.githubusercontent.com/46494969/193907448-fee607ae-4708-4015-aa91-793b3513f722.png)

**Comment by mitulshah-suse** [comment]
@sowmyav27 @Sahota1225 
I see that `rancher-eks-operator` chart has been upgraded using upstream chart `1.1.5-rc2` as part of https://github.com/rancher/charts/pull/2122. 
The original issue was to use the `1.1.5-rc1` upstream chart same as 2.6 based on which the chart was created by @rayandas.
The above tests seem to use the new chart `1.1.5-rc2`. Looks like that upgrade has issues of missing images in the rancher repository.
@KevinJoiner please advise on your PR.

**Comment by KevinJoiner** [comment]
> The original issue was to use the 1.1.5-rc1 upstream chart same as 2.6 based on which the chart was created

The RC changed because there were updates in the operators needed for `rancher/v2.7` https://github.com/rancher/rancher/issues/37927

>The above tests seem to use the new chart 1.1.5-rc2. Looks like that upgrade has issues of missing images in the rancher repository.

It appears our Drone pipeline failed when generating `arm64` images. I was able to rerun Drone and all of the assets are now published on docker hub.

>  please advise on your PR.

Sorry, @mitulshah-suse I am not sure what you mean by this.

**Comment by Josh-Diamond** [comment]
Ticket #38956 - Test Results [cont.]
---

With HA Helm + RKE1 local:

Verified on rancher `v2.7-1f67495adb68fa24c4cb4f710e7301a5331da78d-head`:
1. Fresh install of rancher `v2.7-head`
2. Provision a downstream EKS hosted cluster w/ k8s `v1.23.10-eks-15b7512`
3. Verified:
    - Cluster successfully provisions
    - eks-config-operator successfully installed - [`v1.1.5-rc2`]
    - No UI errors
    - Clean logs
    - Local cluster w/ plenty of resource availability
