### ISSUE TITLE
Prepare rancher-windows-gmsa chart for 2.7.0

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#38964]
rancher-windows-gmsa chart needs to be updated the charts for 2.7 by

- File a PR removing the doNotRelease flag form the package.yaml; in this PR, you will also want to make any changes that need to be made to update the chart to the version you intend to release in 2.7. For example, for a charts like rancher-aks-operator / rancher-gke-operator / rancher-eks-operator, you will need to create a new branch in upstream for Rancher 2.7, cut the first release for that chart, and introduce those changes in to the package.yaml as well before removing the doNotRelease flag

- To make your chart available for 2.7, almost every chart will also have to modify the Rancher Version annotations that scope it to 2.6, i.e. https://github.com/rancher/charts/blob/2e058e93ee01f2980e4750148842dd7f04262b38/charts/fleet-agent/100.0.5%2Bup0.3.11/Chart.yaml#L8

- Once the PR is merged, ensure that the brand new chart is smoke tested by QA/dev

**Comment by sowmyav27** [comment]
Expected versions:
```
rancher-windows-gmsa:
- 2.0.0
rancher-windows-gmsa-crd:
- 2.0.0
```

**Comment by jameson-mcghee** [comment]
I installed the Windows GMSA (2.0.0) Chart onto a Windows Custom cluster on Rancher v2.7-head (Commit ID: 43f25cd) using dummy values, and was able to confirm the version installed was v2.0.0 (see screenshots). Therefore I am closing this ticket.

![image.png](https://zube.io/files/rancher/e7ce173cbc3393a025152679f40aebd9-image.png)
![image.png](https://zube.io/files/rancher/88703b143e77a451871e5be01ecdcce4-image.png)
![image.png](https://zube.io/files/rancher/4d7fc240eec7f4f48e496c117b278212-image.png)
![image.png](https://zube.io/files/rancher/90bca77a352cf91a89bb6d0ada5ca415-image.png)
![image.png](https://zube.io/files/rancher/e484f5b845a049c47347bd7ace69cbd8-image.png)
