### ISSUE TITLE
In automation framework rke1 extension doesn't use k8's version parameter

### ISSUE THREAD

**Issue by igomez06** [rancher/rancher#38961]
**Is your feature request related to a problem? Please describe.**
In tests/framework/extensions/clusters/clusters.go the rke1 helper ignores the Kubernetes version.

**Describe the solution you'd like**
Make sure the Kubernetes version is used in the function.

https://github.com/rancher/rancher/blob/release/v2.6/tests/framework/extensions/clusters/clusters.go#L110-L140

**Comment by markusewalker** [comment]
Since this is a relatively small change, I'm going to incorporate this with https://github.com/rancher/qa-tasks/issues/461.

**Comment by markusewalker** [comment]
PR: https://github.com/rancher/rancher/pull/39124

**Comment by markusewalker** [comment]
Installed.
