### ISSUE TITLE
Rancher removing `external_links` from Docker-Compose file 

### ISSUE THREAD

**Issue by gcallsen** [rancher/rancher#3896]
Rancher Version: v0.59.0

Docker Version: v1.9.1

OS: Ubuntu 14.04 LTS

Steps to Reproduce: 
An application stack (`myapp-workers`) that has one or more services. All of these services have `external_links` to services in another stack (`myapp`). e.g. launch the following into a stack `myapp-workers`:

    some-worker:
      image: some/image
      ...
      external_links:
        - myapp/rabbitmq:rabbitmq
        - myapp/redis:redis
        - myapp/postgres:postgres

__Note: all `myapp` services run on "Host A" and all `myapp-workers` services run across "Host B" and "Host C".__

Scenario 1: Create the `myapp-workers` stack for the first time.
Outcome: Looking at the 'Compose YAML' in the rancher interface is 100% correct, and includes the `external_links`.

Scenario 2: Stop all services in the `myapp-workers` stack and then start them again.
Outcome: All works as expected (`external_links` is still in the Compose YAML).

Scenario 3:
  * Stop all services in `myapp-workers` 
  * Remove the hosts that were supporting `myapp-workers` (Host B and Host C)
  * Add two new hosts with required labels for scheduling
  * Start the `myapp-workers` services again
Outcome: The `Compose YAML` file is now incorrect and the whole `external_links` block has disappeared. 

Results: See above.

Expected:
My use case is: the main application runs on "Host A" and workers are only needed periodically, therefore are spot instances that auto-attach to rancher with correct host labels. This means they will come and go.

The behavior  outlined above causes me to be unable to simply "Stop" and "Start" the workers stack, instead I have to delete it and manually re-launch the stack using rancher-compose. Otherwise the external links are not created and the workers are unable to talk with redis/postgres/etc.

Any guidance is much appreciated!

**Comment by alena1108** [comment]
@gcallsen in scenario3, did you stop/start services using UI or rancher-compose?

**Comment by gcallsen** [comment]
I have only stopped services through the UI. 

In Scenario 1 I start using rancher-compose up -d. Scenario 2 I start using rancher UI. Scenario 3 I start using rancher compose (because I have deleted the stack, through the UI).

**Comment by alena1108** [comment]
@gcallsen you didn't mention you've removed the stack in scenario 3...Could you please re-describe Scenario 3 (including the initial stacks creation) steps with comment against each step telling whether its executed from Rancher-compose? Something like:

1. Created my-app stack (from rancher-compose)
2. Created myapp-workers stack (from rancher-compose)
3. Stopped myapp-workers (rancher)
....etc

I can't reproduce the bug, so detailed steps would be very helpful.

**Comment by alena1108** [comment]
@gcallsen 

>>I would expect instead for the docker-compose file to remain exactly as it was when the stack was deployed through rancher-compose, regardless.

Unfortunately that might not be possible, as even after deploying the stack with rancher-compose, you can modify many things using rancher UI - add more links, remove existing links, upgrade the service. On the export, we build the config based on the current state of the stack.

>> Thanks and my sincere apologies for the goose chase regarding the hosts.

No problem at all, we always appreciate users input
