### ISSUE TITLE
Prepare rancher-wins-upgrader chart for 2.7.0

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#38965]
rancher-wins-upgrader chart needs to be updated the charts for 2.7 by

- File a PR removing the doNotRelease flag form the package.yaml; in this PR, you will also want to make any changes that need to be made to update the chart to the version you intend to release in 2.7. For example, for a charts like rancher-aks-operator / rancher-gke-operator / rancher-eks-operator, you will need to create a new branch in upstream for Rancher 2.7, cut the first release for that chart, and introduce those changes in to the package.yaml as well before removing the doNotRelease flag

- To make your chart available for 2.7, almost every chart will also have to modify the Rancher Version annotations that scope it to 2.6, i.e. https://github.com/rancher/charts/blob/2e058e93ee01f2980e4750148842dd7f04262b38/charts/fleet-agent/100.0.5%2Bup0.3.11/Chart.yaml#L8

- Once the PR is merged, ensure that the brand new chart is smoke tested by QA/dev

**Comment by sowmyav27** [comment]
On 2.7-head, please validate this version of chart is deployed when deploying an RKE2 windows cluster 
```
rancher-wins-upgrader:
- 101.0.0+up0.0.1
```

**Comment by slickwarren** [comment]
why do we need this on 2.7? rke2 windows clusters should not be using rancher-wins-upgrader, but should use SUC instead: https://github.com/rancher/rancher/issues/37020#issuecomment-1076948074

**Comment by jameson-mcghee** [comment]
> why do we need this on 2.7? rke2 windows clusters should not be using rancher-wins-upgrader, but should use SUC instead: [#37020 (comment)](https://github.com/rancher/rancher/issues/37020#issuecomment-1076948074)

@sowmyav27 @Sahota1225 @rayandas 👆

**Comment by jameson-mcghee** [comment]
Setting this ticket to Need Info state until the question posed by @slickwarren can be answered.
cc @sowmyav27 @rayandas @Sahota1225

**Comment by mitulshah-suse** [comment]
We dont know details about how or where this chart is used. It was simply added based on the request to replicate the 2.6 charts on to 2.7. If it is not needed please let us know, we can revert the changes done for it and set it back to `doNotRelease=true`

**Comment by slickwarren** [comment]
ok thank you for that info. Yes, please mark it as `doNotRelease=true`, as rke1 windows is no longer supported and rke2 does not need this chart.

**Comment by snasovich** [comment]
@slickwarren , thank you for clarifying this.
@mitulshah-suse , please proceed with reverting the related commits (I believe https://github.com/rancher/charts/commit/c9c69d662f9c89b77e2962155ef178624d90e049 and https://github.com/rancher/charts/commit/4f6845e3949e1a5e9e454bfbe1b963debafb3472).

@aiyengar2 @prachidamle , in this situation where we're not planning to release this chart for 2.7, should the chart be removed from `packages` folder or in some other way indicated as not required in addition to having `doNotRelease=true` ?

**Comment by aiyengar2** [comment]
> @aiyengar2 @prachidamle , in this situation where we're not planning to release this chart for 2.7, should the chart be removed from packages folder or in some other way indicated as not required in addition to having doNotRelease=true ?

Removed from the packages folder

**Comment by vivek-infracloud** [comment]
rancher-win-upgrader chart verison 0.0.100 is visible on the rancher v2.7.0-rc3.

![Screenshot from 2022-10-05 14-10-36](https://user-images.githubusercontent.com/83208989/194018503-95f0d37b-52f7-441a-bbf4-6f0023689565.png)

**Comment by prachidamle** [comment]
@doflamingo721 We should hide it by adding in the missing rancher-version annotations for 2.7.0

**Comment by rishabhmsra** [comment]
Validated on rancher v2.7.0-rc3 and the `rancher-win-upgrader` chart is not visible, hence closing the issue.

![rancher-win-na](https://user-images.githubusercontent.com/36376154/195327175-35c05b0b-bc5d-46ff-9ee9-f733c205f18a.png)
