### ISSUE TITLE
projectURL is missing in the UI for catalog entries

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#3897]
Rancher Version: v0.61.0-rc3

Steps to Reproduce: 

1. Add a custom catalog that has a `projectURL` in `_config.yml`. 

Results: 
It doesn't show up in the UI.

Expected:
It shows up in the UI along with the other fields (e.g. maintainer, license)

**Comment by westlywright** [comment]
Add the custom catalog `https://github.com/deniseschannon/community-catalog.git`
Go to the catalog and open the template for Alfresco from the new custom catalog
Verify that `Project URL` is display under the image.

**Comment by tfiduccia** [comment]
Version - master 3/15
Not complete - the link should be clickable and open in a new window.

**Comment by tfiduccia** [comment]
Version - master UI 3/17
Need to recognize url without http:// or https://.  I should be able to just put www.amazon.com.

**Comment by tfiduccia** [comment]
Version - master 3/20
Verified fixed
