### ISSUE TITLE
Prepare harvester-cloud-provider chart for 2.7.0

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#38975]
harvester-cloud-provider chart needs to be updated for 2.7 by 

1) File a PR removing the `doNotRelease` flag form the package.yaml; in this PR, you will also want to make any changes that need to be made to update the chart to the version you intend to release in 2.7. For example, for a charts like rancher-aks-operator / rancher-gke-operator / rancher-eks-operator, you will need to create a new branch in upstream for Rancher 2.7, cut the first release for that chart, and introduce those changes in to the package.yaml as well before removing the doNotRelease flag
2) To make your chart available for 2.7, almost every chart will also have to modify the Rancher Version annotations that scope it to 2.6, i.e. https://github.com/rancher/charts/blob/2e058e93ee01f2980e4750148842dd7f04262b38/charts/fleet-agent/100.0.5%2Bup0.3.11/Chart.yaml#L8
3) Once the PR is merged, ensure that the brand new chart is smoke tested by QA/dev

**Comment by TachunLin** [comment]
Verified **fixed** on Rancher `v2.7.0-rc8` with Harvester `v1.1.0`. 

### Result
We could able to install Harvester cloud provider `101.0.0+up0.1.13` on RKE1 cluster and tested the basic load balancer can work as expected

* Harvester cloud provider version: 101.0.0+up0.1.13
![image](https://user-images.githubusercontent.com/29251855/199444968-a25a11e9-4505-47bf-930f-29afdadfafe4.png)

* Successfully installed harvester-cloud-provider: **101.0.0+up0.1.13**
![image](https://user-images.githubusercontent.com/29251855/199450709-cf2b1367-276a-488e-9925-4ca1712cb608.png)

* Can create DHCP mode Load Balancer and route correctly 
![image](https://user-images.githubusercontent.com/29251855/199508638-fc02e022-1e7c-408b-bc89-ca60b7f8b00c.png)

* Can create Pool mode Load Balancer and route correctly 
![image](https://user-images.githubusercontent.com/29251855/199510208-5288c5b0-475d-4ceb-ab06-92ec1fed249a.png)

### Test Information
* Test Environment: 1 node Harvester on local kvm machine
* Harvester version: `v1.1.0`
* Rancher version: `v2.7.0-rc8` 

### Verify Steps
1. Import Harvester in Rancher 
2. Create cloud credential
3. Create RKE1 tempalte
4. Provision an RKE1 cluster with Harvester cloud provider checked
5. Install Harvester cloud provider in RKE 1 guest cluster through Apps market 
6. Install Harvester csi driver in RKE 1 guest cluster through Apps market 
7. Create an nginx deployment and create an PersistentVolum
8. Create an dhcp loadbalancer and bind to nginx service 
9. Setup VIP pool in Harvester 
10. Create an pool loadbalancer and bind to nginx service

**Comment by Sahota1225** [comment]
Based on [TachunLin comment, closing the issue. https://github.com/rancher/rancher/issues/38975#issuecomment-1300494064
