### ISSUE TITLE
Validate ubuntu 22.04 from Rancher

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#38984]
Deploy `2.6.7-rc3` Rancher server using `ubuntu 22.04` AMI on an RKE1 cluster

RKE1 node templates - Deploy RKE1 node driver cluster by selecting Ubuntu 22.04 from the Node template and run Network checks on the cluster
- [x] AWS
- [x] DO
- [ ] Linode
---
RKE1 custom cluster
- [x] Deploy RKE1 custom cluster using private `ubuntu 22.04` AMI with docker installed and run Network checks on the cluster 

---
RKE2 cluster - Deploy RKE2 node driver cluster by selecting Ubuntu 22.04 from the cluster confg and run Network checks on the cluster
- [x] AWS
- [x] DO
- [x] Linode

---
RKE2 custom cluster
- [x] Deploy RKE2 custom cluster using private `ubuntu 22.04` AMI with docker installed and run Network checks on the cluster

---

**Note:**
- Cluster config - 3 etcd, 2 cp and 3 worker nodes
- Cluster k8s version - latest - 1.24 for RKE1 and RKE2 

---

### Docker install
- [x] Install Rancher 2.6-head on Ubuntu 22.04. Verify Rancher provisions successfully and there are no restarts
- [x] Deploy downstream cluster
- [x] Ensure downstream cluster comes up successfully.

**Comment by sowmyav27** [comment]
@vivek-infracloud @rishabhmsra Please validate ubuntu 22.04 using standalone RKE1 (latest version) and ensure all pods are up and Active on the cluster. And ensure cluster health check is fine. Thanks

**Comment by sowmyav27** [comment]
Waiting on https://github.com/rancher/dashboard/issues/6774

**Comment by Sahota1225** [comment]
As the dashboard issue is in QA next up. Moving this to test.

**Comment by vivek-infracloud** [comment]
Validated docker install test scenario.
1. Installed a rancher server v2.6-head on Ubuntu 22.04.
2. Made sure rancher do not restart.
3. Provisioned a downstream cluster. Cluster comes up active successfully.

**Comment by sowmyav27** [comment]
Linode will be validated as part of the UI issue. Closing this.

**Comment by sowmyav27** [comment]
Issue found - https://github.com/rancher/rancher/issues/39281
