### ISSUE TITLE
[BUG] Editing the azure AD auth provider config before updating the endpoints result in failed to parse the 'roles' field in JWT 

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#39000]
**Setup**
- Rancher version: v2.6-head 82bf000 upgraded from v2.6.5
- Browser type & version: Chrome

**Describe the bug**
When a rancher server is upgraded from versions v2.6.5 and below  we would have the old graph end points set. On a rancher server upgrade before updating the endpoints, if we try to edit the config and input the secret we get an error upon authenticating.
 

**To Reproduce**
1. On v2.6.5 rancher server enable Azure AD auth config with standard endpoints
2. Upgrade the rancher server to v2.6-head
3. Do not update the endpoints but click on edit config
4. Input the secret value and save

**Result**
Upon authenticating we run into the issue `server error while authenticating: failed to parse the 'roles' field in JWT - either the token is malformed or lacks permissions`

Following errors are seen in the rancher server logs:
```
2022/09/19 12:52:04 [INFO] Failed to decode the 'metadata' field of the AuthConfig. Attempting to decode 'annotations' at the top level.
2022/09/19 12:52:04 [INFO] Failed to decode the 'annotations' field of the AuthConfig.
2022/09/19 12:52:09 [INFO] failed to get the access token from cache: access token not found
2022/09/19 12:52:09 [INFO] attempting to acquire the access token by credential
2022/09/19 12:52:09 [ERROR] Unknown error: server error while authenticating: failed to parse the 'roles' field in JWT - either the token is malformed or lacks permissions
2022/09/19 12:59:41 [ERROR] Error during subscribe websocket: close sent
```

**Expected Result**
Expected the edit config to work fine without any errors.

**Additional context**
Found while validating https://github.com/rancher/dashboard/issues/6868
Noticed that the UI is sending the existing graph endpoints 
All the required permissions are present in the azure portal for the app.

**Comment by maxsokolovsky** [comment]
# QA testcases

#### Case 1
1. Set up Azure AD on Rancher v2.6.6.
1. Upgrade Rancher to v2.6-head.
1. Try logging out and in. No errors.
1. Edit the configuration by supplying the Application Secret value and saving. No errors.
1. Try logging out and in. No errors.
1. Update the endpoints in the UI. No errors.
1. Try logging out and in. No errors.
1. Edit the configuration by supplying the Application Secret value and saving. No errors.
1. Try logging out and in. No errors.

#### Case 2
1. Start with Rancher v2.6.6. Do not setup Azure AD.
1. Upgrade Rancher to v2.6-head.
1. Set up Azure AD. No errors.
1. Try logging out and in. No errors.
1. Edit the configuration by supplying the Application Secret value and saving. No errors.
1. Try logging out and in. No errors.

#### Case 3
1. Start with Rancher v2.6-head.
1. Set up Azure AD. No errors.
1. Try logging out and in. No errors.
1. Edit the configuration by supplying the Application Secret value and saving. No errors.
1. Try logging out and in. No errors.

**Comment by anupama2501** [comment]
Verified following cases on v2.7-head `b3c5e9f`

Case1
- Start with Rancher v2.7-head.
- Set up Azure AD. No errors.
- Try logging out and in. No errors.
- Edit the configuration by supplying the Application Secret value and saving. No errors.
- Try logging out and in. No errors.

Case 2

- Start with Rancher v2.6.5. Do not setup Azure AD.
- Upgrade Rancher to v2.7-head.
- Set up Azure AD. No errors.
- Try logging out and in. No errors.
- Edit the configuration by supplying the Application Secret value and saving. No errors.
- Try logging out and in. No errors.


Case3:

- Set up Azure AD on Rancher v2.6.5.
- Upgrade Rancher to v2.7-head.
- Try logging out and in. No errors.
- Edit the configuration by supplying the Application Secret value and saving. No errors.
- Try logging out and in. No errors.
- Update the endpoints in the UI. No errors.
- Try logging out and in. No errors.
- Edit the configuration by supplying the Application Secret value and saving. No errors.
- Try logging out and in. No errors.


Case4:

- Set up Azure AD on Rancher v2.6.8.
- Upgrade Rancher to v2.7-head.
- Try logging out and in. No errors.
- Edit the configuration by supplying the Application Secret value and saving. No errors.
- Try logging out and in. No errors.

**Comment by maxsokolovsky** [comment]
The backport is for v2.6.10.
