### ISSUE TITLE
Catalog refresh button continuously spins and never stop

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3902]
Version - master 3/9

Steps to Reproduce:
1.  Go to Catalog page
2.  Click on the refresh button

Results: Button just keeps spinning and never stops

Expected: Should stop once it's finished refreshing

**Comment by tfiduccia** [comment]
Version - master 3/15
Spinning button still spinning.  Fresh install, no changes to catalogs and no additional catalogs added.

**Comment by vincent99** [comment]
Missed updating the api client that actually makes the reqeust and fixes the issue...

**Comment by tfiduccia** [comment]
Version - master UI 3/18
Verified fixed
