### ISSUE TITLE
[BUG] K3s cluster goes into a full reconcile when upgrade strategy on the cluster is changed

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#39020]
**Rancher Server Setup**
- Rancher version: 2.6-head commit id: `4206f57`
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): EKS `v1.23.7-eks-4721010`

**Information about the Cluster**
- Kubernetes version: `v1.24.4+k3s1` Downstream - AWS Node Driver cluster - 3 etcd, 2 cp, 3 worker nodes

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): admin

**Describe the bug**
[BUG] K3s cluster goes into a full reconcile when upgrade strategy on the cluster is changed

**To Reproduce**

- Deploy a k3s Node driver cluster from Rancher
- Edit cluster, change the Upgrade Strategy to - `Worker Concurrency: 2` and enable `Drain Nodes` for both Worker and control plane nodes
- Save changes made
- Cluster goes into a full reconcile, with all nodes Draining and upgrading.

**Result**
- Cluster goes into a full reconcile, with all nodes Draining and upgrading.
- Rancher Prov logs:
```
draining bootstrap node(s) sowmya-k3s-iam-pool1-595d8854cf-2gq4n: draining node
[INFO ] configuring bootstrap node(s) sowmya-k3s-iam-pool1-595d8854cf-2gq4n: waiting for plan to be applied
[INFO ] draining control plane node(s) sowmya-k3s-iam-pool2-6b68c77d5c-99m2s: draining node
[INFO ] configuring control plane node(s) sowmya-k3s-iam-pool2-6b68c77d5c-99m2s,sowmya-k3s-iam-pool2-6b68c77d5c-fhgcl
[INFO ] draining control plane node(s) sowmya-k3s-iam-pool2-6b68c77d5c-fhgcl: draining node
[INFO ] configuring control plane node(s) sowmya-k3s-iam-pool2-6b68c77d5c-fhgcl: waiting for plan to be applied
[INFO ] draining worker node(s) sowmya-k3s-iam-pool3-c6fd664d7-9lz47,sowmya-k3s-iam-pool3-c6fd664d7-blkr4
[INFO ] draining worker node(s) sowmya-k3s-iam-pool3-c6fd664d7-9lz47: draining node
[INFO ] draining worker node(s) sowmya-k3s-iam-pool3-c6fd664d7-9lz47,sowmya-k3s-iam-pool3-c6fd664d7-lchhr
[INFO ] configuring control plane node(s) sowmya-k3s-iam-pool2-6b68c77d5c-99m2s,sowmya-k3s-iam-pool2-6b68c77d5c-fhgcl
[INFO ] sowmya-k3s-iam-pool2-6b68c77d5c-99m2s,sowmya-k3s-iam-pool2-6b68c77d5c-fhgcl
[INFO ] draining worker node(s) sowmya-k3s-iam-pool3-c6fd664d7-9lz47: draining node
[INFO ] configuring worker node(s) sowmya-k3s-iam-pool3-c6fd664d7-9lz47,sowmya-k3s-iam-pool3-c6fd664d7-lchhr
[INFO ] configuring worker node(s) sowmya-k3s-iam-pool3-c6fd664d7-9lz47: waiting for plan to be applied
[INFO ] configuring worker node(s) sowmya-k3s-iam-pool3-c6fd664d7-9lz47: Node condition Ready is False., waiting for plan to be applied
[INFO ] non-ready worker machine(s) sowmya-k3s-iam-pool3-c6fd664d7-9lz47,sowmya-k3s-iam-pool3-c6fd664d7-lchhr
[INFO ] non-ready worker machine(s) sowmya-k3s-iam-pool3-c6fd664d7-9lz47: Node condition Ready is False.
[INFO ] provisioning done
[INFO ] waiting for machine fleet-default/sowmya-k3s-iam-pool3-c6fd664d7-mctkx driver config to be saved
[INFO ] configuring worker node(s) sowmya-k3s-iam-pool3-c6fd664d7-mctkx: waiting for agent to check in and apply initial plan
[INFO ] non-ready worker machine(s) sowmya-k3s-iam-pool3-c6fd664d7-mctkx
[INFO ] provisioning done

```

**Expected Result**

- A full reconcile/upgrade should NOT happen
- In an RKE2 cluster, when these steps are performed, a full reconcile doesn't happen
- In an RKE1 cluster, cluster goes into an `Updating` state and comes back up Active. Nodes do not reconcile/drain/upgrade.

**Comment by markusewalker** [comment]
**QA TEST PLAN - Scenario 1 (Fresh Install)**
1. Setup Rancher, create a standard user and login as that user.
2. Provision a downstream K3s node driver cluster with the following: 3 etcd, 2 cp, 3 worker nodes.
     - Before creating the cluster, change the upgrade strategy to have `Worker Concurrency: 2` and enable `Drain Nodes` for the worker and conrol plane nodes.
3. Create the cluster; validate if the cluster and nodes come up as `Active` in Cluster Management and Cluster Explorer.

**QA TEST PLAN - Scenario 2 (K8s Upgrade)**
1. Setup Rancher, create a standard user and login as that user.
2. Provision a downstream K3s node driver cluster with the following: 3 etcd, 2 cp, 3 worker nodes.
     - Before creating the cluster, change the upgrade strategy to have `Worker Concurrency: 2` and enable `Drain Nodes` for the worker and conrol plane nodes.
3. Ensure that the K8s version is the second highest K8s version available.
4. Create the cluster; validate if the cluster and nodes come up as `Active` in Cluster Management and Cluster Explorer.
5. Edit the cluster's config and upgrade the K8s version.
6. Validate that the cluster and nodes appear as `Active` in Cluster Management and Cluster Explorer.

**Comment by sowmyav27** [comment]
### K3s clusters
On k3s prov:
```
machineGlobalConfig
: 
{disable-kube-proxy: false, etcd-expose-metrics: false, profile: null}
disable-kube-proxy
: 
false
etcd-expose-metrics
: 
false
profile
: 
null
```
- On edit and update of Upgrade strategy 
```
machineGlobalConfig
: 
{disable-apiserver: false, disable-cloud-controller: false, disable-controller-manager: false,…}
disable-apiserver
: 
false
disable-cloud-controller
: 
false
disable-controller-manager
: 
false
disable-etcd
: 
false
disable-kube-proxy
: 
false
disable-network-policy
: 
false
disable-scheduler
: 
false
etcd-expose-metrics
: 
false
profile
: 
null
secrets-encryption
: 
false
```

### RKE2 clusters
- during provisioning:
```
cni
: 
"calico"
disable-kube-proxy
: 
false
etcd-expose-metrics
: 
false
profile
: 
null
```
- After update on upgrade strategy:
```
machineGlobalConfig
: 
{cni: "calico", disable-kube-proxy: false, etcd-expose-metrics: false, profile: null}
cni
: 
"calico"
disable-kube-proxy
: 
false
etcd-expose-metrics
: 
false
profile
: 
null
```

**Comment by gaktive** [comment]
UI has merged https://github.com/rancher/dashboard/pull/7140 in and placed https://github.com/rancher/dashboard/issues/6881 to test so this should be unblocked now for backend. @jakefhyde let me know if you need anything else.

**Comment by jakefhyde** [comment]
@gaktive Thank you for the update and the quick turnaround, looking at the fix I'm fairly confident that's all we'll need from UI, Issue has been moved to test. Thanks again!

**Comment by thaneunsoo** [comment]
Moving back to test and will test once [6881](https://github.com/rancher/dashboard/issues/6881) is fixed

**Comment by thaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.7-head 9f1e043
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: K3s

----------

### Testing: ###
Tested this issue with the following steps:
1. Deploy a k3s Node driver cluster from Rancher
2. Edit cluster, change the Upgrade Strategy to - Worker Concurrency: 2 and enable Drain Nodes for both Worker and control plane nodes
3. Save changes made
4. Verify if cluster does not go into a full reconcile, with all nodes Draining and upgrading.

As mentioned by @markusewalker the following scenarios were tested:
1. Fresh install with highest K8s version for K3s node driver cluster
2. Fresh install with K8s version upgrade for K3s node driver cluster

**Result**
The cluster did not go into a full reconcile. the cluster went into `Updating` and the control plane node had the plan applied. Also the yaml config did not have additional fields added into the request.
![image.png](https://zube.io/files/rancher/bffa3ddbede69e2e88a5eb1f1b864853-image.png)

The provisioning log now shows
```
[INFO ] provisioning done
[INFO ] configuring control plane node(s) <cp_node1>,<cp_node2>,<cp_node3>: waiting for plan to be applied
[INFO ] provisioning done
```
