### ISSUE TITLE
[BUG] Deleted cluster not removed from UI view until hard refresh (Ghost cluster)

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#39033]
Rancher 2.6.1

Login as standard, non-admin user
Create a RKE2 cluster
In a second browser login as admin user and navigate to Cluster Manager view
As the non-admin user delete the cluster
Expected:

When the cluster is deleted it is removed from the view.

Actual:

Normal user session: Deleted cluster is not removed from the view until performing a hard browser refresh.
Admin user session: Deleted cluster is removed from the view immediately

Backport Issue: https://github.com/rancher/rancher/issues/36072

**Comment by anupama2501** [comment]
Since the original issue in v2.6.9 is re opened, created a ticket in v2.7.0 milestone. We only need the fix for re opened state in both milestones as the issue was merged prior to the split between 2.6 and 2.7. https://github.com/rancher/rancher/issues/36072#issuecomment-1246760987

**Comment by MbolotSuse** [comment]
This appears to be potentially related to rancher/dashboard#5997. We would expect the delete/remove event to be properly streamed to the UI as long as the version number when opening the watch has been set correctly. Without this being properly set, it will be difficult to devise a solution which ensures that the UI properly gets the delete event.

**Comment by cbron** [comment]
Moving out of 2.7.1

**Comment by gaktive** [comment]
https://github.com/rancher/dashboard/issues/5997 landed in 2.7.2 so UI should be done on this front. Hopefully that unblocks additional work here if this is still relevant.
