### ISSUE TITLE
[BUG] Linode Node driver RKE2/K3s fails to register worker node + successfully provision

### ISSUE THREAD

**Issue by Josh-Diamond** [rancher/rancher#39038]
**Rancher Server Setup**
- Rancher version: `v2.6.9-rc1`, `v2.6.8`
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:
Seen w/ HA Helm + byo-valid certs, as well as Docker w/ self-signed certs

**Information about the Cluster**
- Kubernetes version: `v1.24.4+rke2r1`, `v1.23.10+rke2r1`, `v1.24.4+k3s1`
- Cluster Type (Local/Downstream):
Downstream

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:
Admin

**Describe the bug**
When provisioning a downstream Linode RKE2/K3s cluster with individual roles - [ 1 etcd, 1 cp, 1 wkr] - cluster fails to register worker node and come up `active`

**To Reproduce**
1. Fresh install of rancher `v2.6.9-rc1`
2. Provision a downstream Linode RKE2/k3s cluster with individual roles - [ 1 etcd, 1 cp, 1 wkr] - any of latest released rke2/k3s k8s versions
3. Reproduced

**Result**
Etcd + CP nodes provision and are `active`; worker node hangs, reporting the following status: 
- `Configuring worker node(s): waiting for probes: calico, kubelet`
Cluster hangs in `Updating` state indefinitely

**Expected Result**
Worker node should register successfully and cluster should come up `active`

**Screenshots**
<img width="1414" alt="Screen Shot 2022-09-20 at 9 52 14 AM" src="https://user-images.githubusercontent.com/46494969/191318579-d521666f-9b4f-4a85-b2e6-5cf748254421.png">

**Additional context**
Multiple logs stating the following:
```logs
an error on the server ("unable to decode an event from the watch stream: tunnel disconnect") has prevented the request from succeeding
```

Provisioning Linode Node driver RKE2/K3s clusters w/ all-roles assigned on each node  is successful

**Comment by Josh-Diamond** [comment]
Issue not seen when provisioning on `v2.6-48b6bc6b4a6adb4fd4c623984862494cd0b70a5f-head` with:
- `v1.24.2+rke2r1`
- `v1.24.2+k3s2`

**Comment by brandond** [comment]
> Multiple logs stating the following:
> ```
> an error on the server ("unable to decode an event from the watch stream: tunnel disconnect") has prevented the request from succeeding
> ```
Where are these logs? In the cattle-cluster-agent pod, rancher-system-agent logs, or in the rke2-server/rke2-agent service log itself… or somewhere else?

**Comment by Josh-Diamond** [comment]
@brandond The logs were grabbed from rancher-logs coming from a single-instance Docker install of `v2.6.9-rc1`  
-  e.g. `docker logs <container_id> -f`

**Comment by brandond** [comment]
OK, so the downstream cluster agent is disconnecting for some reason. Can we get service logs and `kubectl get node -o yaml` output from the downstream cluster?

**Comment by Josh-Diamond** [comment]
I don't have the env up anymore but it is easily reproducible

**Comment by Josh-Diamond** [comment]
Seems to just affect the latest released versions of rke2/k3s with Linode Node driver w/ individual node roles.

**Comment by Josh-Diamond** [comment]
Reproducing and grabbing requested logs now...

**Comment by brandond** [comment]
Root-caused this to changes in upstream Kubernetes now causing IPv6 node addresses to be auto-detected. Rancher does not have any logic to handle dual-stack node addresses, and seems to just pick whichever one comes first in the node status.

![image](https://user-images.githubusercontent.com/370103/191369959-64e427d8-2bd8-4519-9921-60f56aa067d4.png)

This results in agents being pointed at the server's IPv6 address to join the cluster. This would be fine if it rendered the server URL properly - but it does not, it's missing the `[]` around the IPv6 address literal.

```json
{
  "node-label": [
    "rke.cattle.io/machine=569c358f-3d5e-41a9-b179-ce06ea366e91"
  ],
  "private-registry": "/etc/rancher/rke2/registries.yaml",
  "protect-kernel-defaults": false,
  "server": "https://2600:3c03::f03c:93ff:fe0c:b71f:9345",
  "token": "4cxzknjpl6tj5hlvp4bhltcfwxbhw6c2ctkw822gvkf9zbh5998r7t"
}
```

Once I manually corrected the server address to `https://[2600:3c03::f03c:93ff:fe0c:b71f]:9345` and restarted rke2-agent, the node immediately joined the cluster and finished provisioning.

**Comment by jakefhyde** [comment]
### Root cause

The join URL that control plane nodes would use to join a cluster would always be an ipv4 address, scraped from the etcd leader. The join URL that worker nodes would use would instead be the first controlplane node's last `InternalIP` address (or `ExternalIP` if no suitable `InternalIP` is found) as shown in it's status, like so:
```
status:
  addresses:
  - address: 165.227.189.32
    type: InternalIP
  - address: 2604:a880:800:10::7c6:7001
    type: InternalIP
  - address: jhyde-rke2-test-controlplane-838bba1c-8fhkh
    type: Hostname
```
In this case, the ipv6 address was being used, but it was being rendered as `https://2604:a880:800:10::7c6:7001:9345`, with `9345` being appended as the port. This is an invalid URL, as ipv6 hosts must be enclosed with `[]` like so: `https://[2604:a880:800:10::7c6:7001]:9345`

### What was fixed, or what changes have occurred

Enclose ipv6 addresses with brackets.

### Areas or cases that should be tested
 
ipv4 only nodes, ipv6 nodes, and ipv6 + Private Networking should be tested.

### What areas could experience regressions?

N/A

### Are the repro steps accurate/minimal?
:heavy_check_mark:

**Comment by Josh-Diamond** [comment]
Ticket #39038 - Test Results
---

With Docker on a single-node instance:

Verified on rancher `v2.7-6c9cb9c87d67f57d8bb7451cec7b932c92c12d24-head`:

- Scenario 1 - ✅ 
   - Test: `Deploy Linode RKE2 + K3s clusters w/ individual roles`
   - Result: Clusters successfully provision; YAMLs properly formatted
- Scenario 2 - ✅ 
   - Test: `Deploy Linode RKE2 + K3s clusters  w/ individual roles + private networking`
   - Result: Clusters successfully provision; YAMLs properly formatted
- Scenario 3 - ✅ 
   - Test: `Deploy EC-2 RKE2 + K3s clusters w/ individual roles - [ ipv4 only ]`
   - Result:  Clusters successfully provision; YAMLs properly formatted

---

Scenario 1:
1. Fresh install of rancher `v2.7-head`
2. Deploy a downstream Linode RKE2 cluster w/ individual roles
3. Deploy a downstream Linode K3s cluster w/ individual roles
4. Verified - Clusters successfully provision; YAMLs properly formatted

---

Scenario 2:
1. Fresh install of rancher `v2.7-head`
2. Provision a downstream Linode RKE2 cluster w/ individual roles + private networking
3. Provision a downstream Linode K3s cluster w/ individual roles + private networking
4. Verified - Clusters successfully provision; YAMLs properly formatted

---

Scenario 3:
1. Fresh install of rancher `v2.7-head`
2. Provision a downstream AWS Node driver RKE2 cluster w/ individual roles - [ ipv4 only ]
3. Provision a downstream AWS Node driver K3s cluster w/ individual roles - [ ipv4 only ]
4. Verified - Clusters successfully provision; YAMLs properly formatted
