### ISSUE TITLE
[BUG][k3s] Unable to provision custom k3s cluster

### ISSUE THREAD

**Issue by thaneunsoo** [rancher/rancher#39032]
**Rancher Server Setup**
- Rancher version: v2.6-head & v2.7-head
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): k3s
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: 1.23 & 1.24
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

Custom

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Admin user & Standard user

**Describe the bug**

User is unable to provision a custom k3s cluster for 1.23 & 1.24 k8s version on v2.6-head and v2.7-head

**To Reproduce**

1. Provision k3s custom cluster
2. Wait for cluster to become active

**Result**
Cluster is stuck in updating with the following message in the logs
```
[Waiting] configuring control plane node(s) custom-<node_name>: waiting for cluster agent to connect
```

**Expected Result**

Cluster should be able to come up active

**Comment by jameson-mcghee** [comment]
I was able to reproduce this issue on v2.7-head (Commit ID: d675fbb) and on v2.6-head (Commit ID: a3b5237).

**Comment by snasovich** [comment]
@thaneunsoo @jameson-mcghee , could you please clarify what nodes (and roles of those nodes) you were joining to this cluster? Just a single all-role node or something else?

**Comment by thaneunsoo** [comment]
@snasovich I had a 3 etcd, 2 cp, 3 worker setup

**Comment by thaneunsoo** [comment]
Closing this issue as a duplicate of [38941](https://github.com/rancher/rancher/issues/38941)
