### ISSUE TITLE
glusterfs service says degraded even thou all containers are running

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3904]
Version - 0.63.0-rc2 

Steps to Reproduce: 
1.  Add a couple of hosts
2.  Add the glusterfs catalog

Results: All the containers are running but the service and stack says degraded

Expected: It should not be degraded

**Comment by alena1108** [comment]
@tfiduccia do you have an access to the environment? need to check something in the DB

**Comment by tfiduccia** [comment]
http://130.211.169.26:8080/env/1a11/apps

**Comment by Slamper** [comment]
The same happens to me after upgrading to 0.63.0-rc2 with my health checked Mongodb container

**Comment by janeczku** [comment]
Similar here after upgrade to 0.63.0-rc2

By the way, what will be the next non-RC release version number? v0.61.0 or v0.63.0 ? @alena1108 @tfiduccia 

![screencap](https://cloud.githubusercontent.com/assets/3813921/13674562/41710c4e-e6de-11e5-9188-44badcdecce3.png)

**Comment by vincent99** [comment]
We're reverting back to the UI calculating the health state again for now..

At least until 1.0, releases are the week of the year, +52 for last year.  So 11+52=63

**Comment by janeczku** [comment]
@vincent99 thanks!

**Comment by alena1108** [comment]
@janeczku @Slamper the bug was in the health check calculation for services having "startedOnce" set on sidekicks. I know thats the case for glusterfs and mongodb, and validated the fix for these catalog items. @janeczku wanted to double check if your app has startedOnce=true as well.

**Comment by janeczku** [comment]
> wanted to double check if your app has startedOnce=true as well.

@alena1108  No it does not. The issue doesn't seem to affect newly created stacks though. Only those that already existed when i upgraded from v0.59.1.

**Comment by alena1108** [comment]
@janeczku could you open a separate bug (with me as an assignee) for the upgrade use case?

@tfiduccia I've applied the fix for the health check bug you've hit while testing glusterfs, could you verify that use case?

**Comment by tfiduccia** [comment]
Version - master 3/16
Verified fixed
