### ISSUE TITLE
[BUG][project monitoring v2]helm-install-cattle-project-p- pod error state due to missing key

### ISSUE THREAD

**Issue by ronhorton** [rancher/rancher#39046]
**Rancher Server Setup**
- Rancher version: `2.6.9-rc1`
- Installation option (Docker install/Helm Chart): `HELM`
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: `v1.24.4`
- Cluster Type (Local/Downstream): `downstream ec2 k3s cluster k3s cluster - provisioned thru rancher ui`
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: `admin`

**Describe the bug**
After installing prometheus federator on a downstream cluster, I created a project monitor, a project and a namespace in the new project. checking pods, i see any pod titled helm-install-cattle-project-p-xxxxx-monitoring-xxxxx is in an error state. 

`Tue, Sep 20 2022 3:42:42 pm | + echo 'Installing helm_v3 chart'
Tue, Sep 20 2022 3:42:42 pm | + helm_v3 install --namespace cattle-project-p-2gfdt-monitoring cattle-project-p-2gfdt-monitoring /tmp/cattle-project-p-2gfdt-monitoring.tgz --values /config/values-01_HelmChart.yaml
Tue, Sep 20 2022 3:42:47 pm | W0920 19:42:47.840743 43 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
Tue, Sep 20 2022 3:42:47 pm | W0920 19:42:47.843486 43 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
Tue, Sep 20 2022 3:42:47 pm | W0920 19:42:47.846553 43 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
Tue, Sep 20 2022 3:42:47 pm | W0920 19:42:47.849395 43 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
Tue, Sep 20 2022 3:42:48 pm | Error: INSTALLATION FAILED: rendered manifests contain a resource that already exists. Unable to continue with install: PrometheusRule "cattle-project-p-2gfdt-mon-prometheus" in namespace "cattle-project-p-2gfdt-monitoring" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "cattle-project-p-2gfdt-monitoring"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "cattle-project-p-2gfdt-monitoring"`
**To Reproduce**
1. provision downstream k3s cluster
2. install monitoring
3. install prometheus federator
4. create new project
5. create new namespace
6. create project monitor

**Result**
helm-install-cattle-project pods in error state - terminates, restarts and errors again. 

**Expected Result**
project monitoring v2 running with no errors

**Screenshots**

<img width="1625" alt="2022-09-20_16-09-13" src="https://user-images.githubusercontent.com/89212856/191354866-717dc510-dca7-4782-a024-1b4b0d6671a3.png">

**Comment by aiyengar2** [comment]
@ronhorton is there a chance that you did not set `helmProjectOperator.helmController.enabled` to false as described in the docs in https://github.com/rancher/prometheus-federator/blob/main/docs/design.md#advanced-helm-project-operator-configuration? 

This could cause weird conditions like above as the Helm Controller of k3s and that of Prometheus Federator are encountering race conditions when trying to manage the same resource.

**Comment by aiyengar2** [comment]
The workaround for this issue would be to manually delete the resources that are causing the conflicts. 

You could also script up a deletion process by parsing the resources listed in the helm release secret using the utility command in https://github.com/rancher/helm-locker#how-do-i-manually-inspect-the-content-of-the-helm-release-secret-to-debug-a-possible-helm-locker-issue

**Comment by aiyengar2** [comment]
> @ronhorton is there a chance that you did **not** set `helmProjectOperator.helmController.enabled` to false as described in the docs in https://github.com/rancher/prometheus-federator/blob/main/docs/design.md#advanced-helm-project-operator-configuration?
> 
> This could cause weird conditions like above as the Helm Controller of k3s and that of Prometheus Federator are encountering race conditions when trying to manage the same `HelmChart` resource.

Checked setup offline. This was the issue.

Filed a PR to indicate that K3s has the same underlying issue as RKE2 and also needs the embedded helmController to be disabled, since they deploy the same internal components. This is a low priority issue though since it's just a documentation fix @MKlimuszka; if users are seeing this, disabling the helmController should work perfectly fine in the current version of the chart.

**Comment by ronhorton** [comment]
**Functioning as Designed**
k3s has same requirement as rke2 regarding the helm project operator - it must be disabled at install. 
as suggested, i updated prometheus federator and set `helmProjectOperator.helmController.enabled to false.` Pods came up without errors. 
closing this issue.

**Comment by ronhorton** [comment]
reopened ticket for additional testing 2.6.9 & 2.7.0

**Comment by ronhorton** [comment]
**Pass** verified in `2.7.0-rc8`
when installing prom federator, i disabled the helm controller.
1. create new project
2. create new namespace
3. create project monitor

project monitor created, all workloads active and complete. 

docs change filed by dev to include k3s in the installation step to disable helm controller, same as rke2 in that regard.
