### ISSUE TITLE
Remove auto-generated deepcopy functions for v1 cis-benchmark

### ISSUE THREAD

**Issue by doflamingo721** [rancher/rancher#39053]
### Problem
We need to remove the deepcopy functions for v1 cis-benchmark in [zz_generated_deepcopy.go](https://github.com/rancher/rancher/blob/release/v2.7/pkg/apis/management.cattle.io/v3/zz_generated_deepcopy.go).

### Description 
The deepcopy functions for v1 cis-benchmark in [zz_generated_deepcopy.go](https://github.com/rancher/rancher/blob/release/v2.7/pkg/apis/management.cattle.io/v3/zz_generated_deepcopy.go) are not getting removed after cleaning up [clusterscan_types](https://github.com/rancher/rancher/blob/release/v2.7/pkg/apis/management.cattle.io/v3/cluster_scan_types.go) and other v1 cis-scan related components. Also after removing the functions manually and running `go generate` is causing these methods to regenerate in the `zz_generated_deepcopy.go` file. 

We made sure that there is no occurrence related to cis-scan which the codegen might look at to generate these functions but still these functions are not getting removed.

**Comment by vivek-infracloud** [comment]
Validated changes on rancher v2.7-head.

- Created a rancher server v2.7-head.
- Opened a URL `rancher-server-ip/v3`
- Made sure the following 3 are not present.

```
"cisBenchmarkVersions": "…/v3/cisbenchmarkversions",
"cisConfigs": "…/v3/cisconfigs",
"clusterScans": "…/v3/clusterscans",
```

Since the above scan related apis are not present this issue can be closed.
