### ISSUE TITLE
Fix docker-compose.yml sync in rancher

### ISSUE THREAD

**Issue by protheusfr** [rancher/rancher#3905]
Rancher Version: 0.59.0

Docker Version:1.10

OS: RancherOS 

Steps to Reproduce: Create a new stack in Rancher through docker-compose.yml & rancher-compose.yml option, define a option in docker-compose.yml like :

> mac_address: XX:XX:XX:XX:XX:XX

When Rancher try to build the stack, they doesn't apply the mac_address option.

Results: Impossibility to build stack with some of the docker-compose.yml officials options.

Expected:  Rancher apply all docker-compose.yml instructions.

Please see : https://forums.rancher.com/t/how-to-fix-mac-address-through-rancher/1983

**Comment by deniseschannon** [comment]
@protheusfr Apologies as I spoke with @ibuildthecloud and he mentioned that Rancher itself will not be able to support mac addresses.

Sorry for any confusion.

**Comment by protheusfr** [comment]
Ok thank you for the information.
It could be an issue for "contenairization" of commercial products with MAC adresse based licenses.
