### ISSUE TITLE
[of topic] how to manage GH issue labels

### ISSUE THREAD

**Issue by hwinkel** [rancher/rancher#3906]
just aa quick question, do you  manage the issue Labels manually or is this driven by a tool using the GH API. Have seen the same structure in the k8s project.

**Comment by ibuildthecloud** [comment]
Manually and very painfully.

**Comment by hwinkel** [comment]
@ibuildthecloud I expected that and feel your pain...

**Comment by vincent99** [comment]
Not that @ibuildthecloud is the one doing the managing :-P

But yes, basically manually.. There are keyboard shortcuts for label/assigned/milestone so you don't need a mouse, which helps.  There's also some tools like waffle.io that we've tried but had some issue with.  And https://github.com/9-volt/bug-life is cool for visualizing them.

**Comment by hwinkel** [comment]
I mess around with huboard a bit. Not so bad, at least a start

**Comment by deniseschannon** [comment]
Closing this issue so I don't have to label it. ;)
