### ISSUE TITLE
Unable to set rancher default admin password (local accounts)

### ISSUE THREAD

**Issue by tallandtree** [rancher/rancher#3907]
If I try to set a password (either manual of generate password) on the default admin account and press "Save" nothing happens (via "http://flowertree.ccveu.local:8080/admin/accounts and then "edit". No error as well. I can only cancel. I can change the password of my own (other local admin) account.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v0.59.1` Cattle: `v0.148.1` UI: `v0.90.0` |
|Access|`localauth` `admin`|
|Route|`null`|

**Comment by hibooboo2** [comment]
@tallandtree When you say the default admin account do you mean account 1a1? If so I believe that version of cattle does not create a password for 1a1 which means that when the ui goes to update the password it cannot as there is not one to update. with the newest version of cattle this behavior is changed and this will not occur.

**Comment by tallandtree** [comment]
Yes, it is the 1a1 account indeed. So, I will not try to use it in that case.
