### ISSUE TITLE
[CSP Adapter] Support for new test product skus

### ISSUE THREAD

**Issue by MbolotSuse** [rancher/rancher#39087]
Since the adapter has now gone live, we can no longer use the SKUs associated with the production listings for our test accounts (as this would incur a large charge). Because of this, the adapter will now need to support two additional product skus which serve as the test skus for EU and US.

The two new SKUs are:
- 83929a73-7c49-4511-aa45-8854a4f001d4 (us)
- e001cf36-9e45-496e-be2c-b48749bf7dd2 (eu)

The adapter should be able to consume licenses with these SKUs as well as licenses from the production SKUs. 
 
It is probable that the current approach of "try one, default to another" won't scale well to 4 ids. However, we can't supply the sku as a runtime variable, as this would potentially create the ability to trick the adapter with fake listings. Any approach that we come up with to solve this should meet the following requirements:
- It can use any of the 4 skus (production or test)
- It can't use a license with a sku that is not in one of our 4 skus

**Comment by MbolotSuse** [comment]
## Validation Template

## Root Cause

The adapter uses hardcoded tests skus to identify the licenses in AWS that it can check out entitlements against. In the current state, these were only set to use production skus, and there was no way to test against test licenses. 

## What was fixed, or what change have occurred

The adapter has been updated to allow for the use of test skus. To use this, a new option has been created in the chart `devMode`. This option, which defaults to false, when set to true will use the new test skus.

## Areas or cases that should be tested

- The use of test skus (emea and non emea)
- The use of prod skus (emea and non emea)

## What areas could experience regressions

The use of prod skus (emea and non emea)

## Are the repro steps accurate/minimal?
N/A

**Comment by brudnak** [comment]
# ✅ PASSED

## Reproduction Environment

Reproduction not requred.

## Validation Environment


| Component                        | Version / Type                                            |
| -------------------------------- | --------------------------------------------------------- |
| Rancher version                  | v2.7-c842598344ee552daf5cf4e8d31d6e11621e07ad-head        |
| Installation option              | Helm (high availability)                                  |
| Local cluster creation method    | `eksctl` EKS                                              |
| If Helm Chart k8s cluster        | v1.22.17-eks-0a21954                                      |
| Cert Details                     | Let's Encrypt / `nginx`                                   |
| Helm version                     | v2.16.8-rancher2                                          |
| Downstream cluster type          | RKE1 Linode                                               |
| Downstream K8s version           | v1.26.4                                                   |
| Authentication providers enabled | local                                                     |
| Logged in user role              | administrator                                             |
| Browser type                     | Microsoft Edge                                            |
| Browser version                  | 113.0.1774.35                                             |
| CSP adapter version              | v2.0.2-rc2                                                |
| CSP chart branch                 | https://raw.githubusercontent.com/rancher/charts/dev-v2.7 |

Install csp adapter:

```sh
 helm install rancher-csp-adapter rancher-dev-v2.7/rancher-csp-adapter \
    --namespace cattle-csp-adapter-system \
    --set aws.enabled=true \
    --set aws.roleName=$ROLE_NAME_VAR \
    --set-string aws.accountNumber=$ACC_NUM_VAR \
    --version 2.0.2+up2.0.2-rc2 \
    --set global.cattle.systemDefaultRegistry=docker.io \
    --set devMode=true
```

## Validation steps

1. Initiate the installation of the CSP Adapter.
2. Ensure that 'devMode' is accurately configured to 'true', as indicated in the referenced command.
3. Confirm the number of node packs assigned to the test product SKU. In this instance, the assigned number was one.
4. Transition from the Rancher UI to the AWS UI console, and confirm that the test SKU has been appropriately checked out from the license manager.
5. Establish a downstream cluster comprised of 20 nodes.
6. Procure the support configuration and verify its format for accuracy.
7. Construct an additional downstream cluster, this time consisting of 5 nodes.
8. Check for the visibility of the compliance banner, which indicates an out-of-compliance status of the rancher server.
9. Retrieve the support configuration once again, ensuring that it has been duly updated with the anticipated out-of-compliance notifications.

## Additional Info

## RESULTS

### ✅ (Validation) Expected

We anticipate that the CSP Adapter will function optimally when set to 'devMode', successfully utilizing the assigned test SKU.

### ✅ (Validation) Actual

As observed, the CSP Adapter performed as predicted when configured in 'devMode', seamlessly utilizing the assigned test SKU.

## 📋 QA Test Plan

<table>
    <tbody>
        <tr>
            <th>#</th>
            <th>Scenario</th>
            <th>Steps</th>
            <th>Expected</th>
            <th>Actual & Pass/Fail</th>
        </tr>
        <tr>
            <td>1</td>
            <td>Verifying CSP Adapter Functionality with a Production SKU</td>
            <td>
                <ol>
                    <li>Execute the primary validation steps as outlined above. However, during the installation of the
                        CSP Adapter, refrain from including the 'devMode' flag.</li>
                    <li>Note: Will be unable to test with production SKU after May 24th, 2023 </li>
                </ol>
            </td>
            <td>Expected: The CSP adapter should function correctly when not in development mode and when using
                production SKUs.</td>
            <td>Actual: The CSP adapter functions as expected with production SKUs when development mode is not
                enabled.<br><br>Pass/Fail: ✅<code>PASS</code></td>
        </tr>
        <tr>
            <td>2</td>
            <td>Transition from Production SKUs to Test SKUs</td>
            <td>
                <ol>
                    <li>Install the CSP adapter version 2.0.1.</li>
                    <li>Verify that everything is functioning as expected.</li>
                    <li>Uninstall the CSP adapter following the official Rancher documentation.</li>
                    <li>Reinstall the CSP adapter using the development branch and version
                        <code>2.0.2+up2.0.2-rc2</code> with dev mode enabled.
                    </li>
                    <li>Verify that the CSP adapter has transitioned from using production SKUs to test SKUs.</li>
                </ol>
            </td>
            <td>Expected: The CSP adapter should transition from using production SKUs to test SKUs.</td>
            <td>Actual: The CSP adapter successfully switched from using production SKUs to test SKUs when uninstalling
                and reinstalling with development mode enabled.<br><br>Pass/Fail: ✅<code>PASS</code></td>
        </tr>
    </tbody>
</table>
