### ISSUE TITLE
[BUG] Fleet not showing labels created with kubectl patch

### ISSUE THREAD

**Issue by clemenko** [rancher/rancher#39095]
**Rancher Server Setup**
- Rancher version: 2.6.8
- Installation option (Docker install/Helm Chart):
   helm on rke2 with selinux
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.24.4+rke2r1
- Cluster Type (Local/Downstream):
    local 
* Custom = Running a docker command on a node
* Imported = Running kubectl apply onto an existing k8s cluster
* Hosted = EKS, GKE, AKS, etc
 * Infrastructure Provider = Rancher provisioning the nodes using different node drivers (e.g. AWS, Digital Ocean, etc)
   DO

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
 Admin user logged in

**Describe the bug**
When updating the `Cluster` label for fleel-local with
`kubectl patch Cluster -n fleet-local local --type=merge -p '{"metadata": {"labels":{"name":"local"}}}'`
It is not showing up in the GUI. This is trying another work around for : https://github.com/rancher/fleet/issues/759 

**To Reproduce**
Run `kubectl patch Cluster -n fleet-local local --type=merge -p '{"metadata": {"labels":{"name":"local"}}}'` to add the label. Then check the gui. It shows up in `kubectl  get Cluster -n fleet-local local -o json | jq .metadata.labels`

**Result**
![Screen Shot 2022-09-23 at 9 29 43 AM](https://user-images.githubusercontent.com/3177276/191971989-a83e28f9-c290-4cf0-b256-d65f6d56daf0.jpg)

**Expected Result**
they match

**Screenshots**
see above

**Additional context**
please help obiwan.

**Comment by manno** [comment]
Are you sure this patches the right "cluster"? There are multiple CRDs named "cluster:

```
clusters.cluster.x-k8s.io
clusters.fleet.cattle.io
clusters.management.cattle.io
clusters.provisioning.cattle.io
```

**Comment by clemenko** [comment]
I think that explains it. There are several locations for the label. 

```
clempro:clemenko rke2 ( 137.184.158.230:6443 ) $ kubectl get clusters.fleet.cattle.io -n fleet-local local -o json | jq .metadata.labels
{
  "management.cattle.io/cluster-display-name": "local",
  "management.cattle.io/cluster-name": "local",
  "name2": "local2",
  "nametest": "local",
  "objectset.rio.cattle.io/hash": "f2a8a9999a85e11ff83654e61cec3a781479fbf7",
  "provider.cattle.io": "rke2"
}
clempro:clemenko rke2 ( 137.184.158.230:6443 ) $ kubectl get clusters -n fleet-local local -o json | jq .metadata.labels
{
  "nametest": "local",
  "objectset.rio.cattle.io/hash": "50675339e9ca48d1b72932eb038d75d9d2d44618",
  "provider.cattle.io": "rke2"
}
```

`kubectl patch clusters.fleet.cattle.io -n fleet-local local --type=merge -p '{"metadata": {"labels":{"name":"local"}}}' `
worked for the fleet-local bug

**Comment by clemenko** [comment]
closing as per location for `clusters.fleet.cattle.io`.
