### ISSUE TITLE
Error when disabling grafana rancher-monitoring

### ISSUE THREAD

**Issue by LockedThread** [rancher/rancher#39090]
`Error: UPGRADE FAILED: template: rancher-monitoring/templates/rancher-monitoring/clusterrole.yaml:116:13: executing "rancher-monitoring/templates/rancher-monitoring/clusterrole.yaml" at <include "call-nested" (list . "grafana" "grafana.fullname")>: error calling include: template: rancher-monitoring/templates/_helpers.tpl:21:4: executing "call-nested" at <include $template (dict "Chart" (dict "Name" (last $subchart)) "Values" $values "Release" $dot.Release "Capabilities" $dot.Capabilities)>: error calling include: template: no template "grafana.fullname" associated with template "gotpl" `

https://github.com/rancher/charts/blob/cc64055c886306a6cb4180a1c76b2c9e1285c8c6/charts/rancher-monitoring/100.1.0%2Bup19.0.3/templates/rancher-monitoring/clusterrole.yaml#L116

**Comment by aiyengar2** [comment]
PR already exists in https://github.com/rancher/charts/pull/2087, we just need to wrangle and cherry-pick the commits.

@ronhorton @bmdepesa have signed off on 2.7.0 as the milestone.

cc: @geethub97 can we address this as part of https://github.com/rancher/rancher/issues/37778?

**Comment by ronhorton** [comment]
**Pass** verified in `2.7-head commit id 9e7e4bc`
installed monitoring
edited yaml file to disable grafana (grafana.enabled: false)
no errors
grafana link on monitoring page grayed out and unavailable
![2022-10-25_15-24-31.png](https://zube.io/files/rancher/0c7a3dc3f7986721eadc151ac22e0bc6-2022-10-25_15-24-31.png)

**Comment by 1aw1iet** [comment]
Still relevant in Rancher v2.7.0 with rancher-monitoring 101.0.0+up19.0.3.
