### ISSUE TITLE
[BUG] Erroneous "Operation cannot be fulfilled" Error in RKE2 Provisioning Logs

### ISSUE THREAD

**Issue by jameson-mcghee** [rancher/rancher#39108]
**Rancher Server Setup**
- Rancher version: v2.6.9-rc1
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1
- Proxy/Cert Details: N/A

**Information about the Cluster**
- Kubernetes version: v1.24.4+rke2r1
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): EC2 Node Driver

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Admin and Standard - Cluster Owner
  - If custom, define the set of permissions: N/A

**Describe the bug**
When provisioning an RKE2 EC2 Node Driver cluster, an error is generated in the Provisioning Logs 

**To Reproduce**

1. On a Rancher server, navigate to the _Cluster Management_ page
2. Click the _Create_ button
3. Toggle to _RKE2/K3s_, and then click _Amazon EC2_
4. Input a _unique name_ as well as the correct _AWS Access Key_ and _SecretKey_ credentials, and then click the _Create_ button
5. Input a _unique name_, set the _Machine Count_ value to "3", and select a valid _VPC/Subnet_, and then click the _Create_ button
6. After the cluster has provisioned successfully and is "Active", navigate to the _Cluster Management--> Cluster_ page for the cluster, and then navigate to the _Provisioning Log_ tab

**Result**
Note that an error is present in the logs which states "[ERROR] Operation cannot be fulfilled on machines.cluster.x-k8s.io "{MACHINE POOL NAME}": the object has been modified; please apply your changes to the latest version and try again"

**Expected Result**
No error is observed in the Provisioning Logs

**Screenshots**
![image](https://user-images.githubusercontent.com/13294321/192048141-a0d49e32-aacc-4a80-b641-549f4c700d4d.png)

**Additional context**
**Provisioning Logs:**
<code>
2:35:42 pm | [INFO ] waiting for viable init node
2:36:00 pm | [INFO ] configuring bootstrap node(s) jrmk3serrortest-pool1-5cf699c6fb-k6q9q: waiting for agent to check in and apply initial plan
2:37:33 pm | [INFO ] configuring bootstrap node(s) jrmk3serrortest-pool1-5cf699c6fb-k6q9q: waiting for probes: calico, etcd, kube-apiserver, kube-controller-manager, kube-scheduler, kubelet
2:38:09 pm | [INFO ] configuring bootstrap node(s) jrmk3serrortest-pool1-5cf699c6fb-k6q9q: waiting for probes: calico, etcd, kube-apiserver, kube-controller-manager, kube-scheduler
2:38:19 pm | [INFO ] configuring bootstrap node(s) jrmk3serrortest-pool1-5cf699c6fb-k6q9q: waiting for probes: calico, kube-apiserver, kube-controller-manager, kube-scheduler
2:38:25 pm | [INFO ] configuring bootstrap node(s) jrmk3serrortest-pool1-5cf699c6fb-k6q9q: waiting for probes: calico
2:39:35 pm | [INFO ] configuring bootstrap node(s) jrmk3serrortest-pool1-5cf699c6fb-k6q9q: waiting for cluster agent to connect
2:40:51 pm | [INFO ] non-ready bootstrap machine(s) jrmk3serrortest-pool1-5cf699c6fb-k6q9q and join url to be available on bootstrap node
2:41:07 pm | [ERROR] Operation cannot be fulfilled on machines.cluster.x-k8s.io "jrmk3serrortest-pool1-5cf699c6fb-sv9j2": the object has been modified; please apply your changes to the latest version and try again
2:41:09 pm | [INFO ] configuring etcd node(s) jrmk3serrortest-pool1-5cf699c6fb-sv9j2,jrmk3serrortest-pool1-5cf699c6fb-t5h9g
2:43:01 pm | [INFO ] configuring etcd node(s) jrmk3serrortest-pool1-5cf699c6fb-t5h9g: waiting for probes: calico
2:43:13 pm | [INFO ] non-ready etcd machine(s) jrmk3serrortest-pool1-5cf699c6fb-t5h9g
2:43:15 pm | [INFO ] provisioning done
</code>

**journalctl -u rancher-system-agent Logs:**
<code>
-- Logs begin at Fri 2022-09-23 18:36:01 UTC, end at Fri 2022-09-23 18:57:54 UTC. --
Sep 23 18:37:26 jrmk3serrortest-pool1-bdac25ec-c58nn systemd[1]: Started Rancher System Agent.
Sep 23 18:37:26 jrmk3serrortest-pool1-bdac25ec-c58nn rancher-system-agent[1391]: time="2022-09-23T18:37:26Z" level=info msg="Rancher System Agent version v0.2.10 (6a89e30) is starting"
Sep 23 18:37:26 jrmk3serrortest-pool1-bdac25ec-c58nn rancher-system-agent[1391]: time="2022-09-23T18:37:26Z" level=info msg="Using directory /var/lib/rancher/agent/work for work"
Sep 23 18:37:26 jrmk3serrortest-pool1-bdac25ec-c58nn rancher-system-agent[1391]: time="2022-09-23T18:37:26Z" level=info msg="Starting remote watch of plans"
Sep 23 18:37:26 jrmk3serrortest-pool1-bdac25ec-c58nn rancher-system-agent[1391]: time="2022-09-23T18:37:26Z" level=info msg="Starting /v1, Kind=Secret controller"
Sep 23 18:41:06 jrmk3serrortest-pool1-bdac25ec-c58nn rancher-system-agent[1391]: time="2022-09-23T18:41:06Z" level=info msg="Detected first start, force-applying one-time instruction set"
Sep 23 18:41:06 jrmk3serrortest-pool1-bdac25ec-c58nn rancher-system-agent[1391]: time="2022-09-23T18:41:06Z" level=info msg="[Applyinator] Applying one-time instructions for plan with checksum 6d8c502e51cd30a9866d09994365a3f0c64bd203ab58352648af3c3cda530d6b"
Sep 23 18:41:06 jrmk3serrortest-pool1-bdac25ec-c58nn rancher-system-agent[1391]: time="2022-09-23T18:41:06Z" level=info msg="[Applyinator] Extracting image rancher/system-agent-installer-rke2:v1.24.4-rke2r1 to directory /var/lib/rancher/agent/work/20220923-184106/6d8c502e51cd30a9866d09994365a3f0c64bd203ab58352648af3>
Sep 23 18:41:06 jrmk3serrortest-pool1-bdac25ec-c58nn rancher-system-agent[1391]: time="2022-09-23T18:41:06Z" level=info msg="Using private registry config file at /etc/rancher/agent/registries.yaml"
Sep 23 18:41:06 jrmk3serrortest-pool1-bdac25ec-c58nn rancher-system-agent[1391]: time="2022-09-23T18:41:06Z" level=info msg="Pulling image index.docker.io/rancher/system-agent-installer-rke2:v1.24.4-rke2r1"
Sep 23 18:41:06 jrmk3serrortest-pool1-bdac25ec-c58nn rancher-system-agent[1391]: time="2022-09-23T18:41:06Z" level=info msg="Extracting file installer.sh to /var/lib/rancher/agent/work/20220923-184106/6d8c502e51cd30a9866d09994365a3f0c64bd203ab58352648af3c3cda530d6b_0/installer.sh"
Sep 23 18:41:06 jrmk3serrortest-pool1-bdac25ec-c58nn rancher-system-agent[1391]: time="2022-09-23T18:41:06Z" level=info msg="Extracting file rke2.linux-amd64.tar.gz to /var/lib/rancher/agent/work/20220923-184106/6d8c502e51cd30a9866d09994365a3f0c64bd203ab58352648af3c3cda530d6b_0/rke2.linux-amd64.tar.gz"
Sep 23 18:41:07 jrmk3serrortest-pool1-bdac25ec-c58nn rancher-system-agent[1391]: time="2022-09-23T18:41:07Z" level=info msg="Extracting file sha256sum-amd64.txt to /var/lib/rancher/agent/work/20220923-184106/6d8c502e51cd30a9866d09994365a3f0c64bd203ab58352648af3c3cda530d6b_0/sha256sum-amd64.txt"
Sep 23 18:41:07 jrmk3serrortest-pool1-bdac25ec-c58nn rancher-system-agent[1391]: time="2022-09-23T18:41:07Z" level=info msg="Extracting file run.sh to /var/lib/rancher/agent/work/20220923-184106/6d8c502e51cd30a9866d09994365a3f0c64bd203ab58352648af3c3cda530d6b_0/run.sh"
Sep 23 18:41:07 jrmk3serrortest-pool1-bdac25ec-c58nn rancher-system-agent[1391]: time="2022-09-23T18:41:07Z" level=info msg="[Applyinator] Running command: sh [-c run.sh]"
Sep 23 18:41:07 jrmk3serrortest-pool1-bdac25ec-c58nn rancher-system-agent[1391]: time="2022-09-23T18:41:07Z" level=info msg="[6d8c502e51cd30a9866d09994365a3f0c64bd203ab58352648af3c3cda530d6b_0:stderr]: + SA_INSTALL_PREFIX=/usr/local"
Sep 23 18:41:07 jrmk3serrortest-pool1-bdac25ec-c58nn rancher-system-agent[1391]: time="2022-09-23T18:41:07Z" level=info msg="[6d8c502e51cd30a9866d09994365a3f0c64bd203ab58352648af3c3cda530d6b_0:stderr]: + mkdir -p /var/lib/rancher/rke2"
Sep 23 18:41:07 jrmk3serrortest-pool1-bdac25ec-c58nn rancher-system-agent[1391]: time="2022-09-23T18:41:07Z" level=info msg="[6d8c502e51cd30a9866d09994365a3f0c64bd203ab58352648af3c3cda530d6b_0:stderr]: + SAI_FILE_DIR=/var/lib/rancher/rke2/system-agent-installer"
Sep 23 18:41:07 jrmk3serrortest-pool1-bdac25ec-c58nn rancher-system-agent[1391]: time="2022-09-23T18:41:07Z" level=info msg="[6d8c502e51cd30a9866d09994365a3f0c64bd203ab58352648af3c3cda530d6b_0:stderr]: + RESTART_STAMP_FILE=/var/lib/rancher/rke2/system-agent-installer/rke2_restart_stamp"
Sep 23 18:41:07 jrmk3serrortest-pool1-bdac25ec-c58nn rancher-system-agent[1391]: time="2022-09-23T18:41:07Z" level=info msg="[6d8c502e51cd30a9866d09994365a3f0c64bd203ab58352648af3c3cda530d6b_0:stderr]: + RKE2_SA_ENV_FILE_NAME=rke2-sa.env"
Sep 23 18:41:07 jrmk3serrortest-pool1-bdac25ec-c58nn rancher-system-agent[1391]: time="2022-09-23T18:41:07Z" level=info msg="[6d8c502e51cd30a9866d09994365a3f0c64bd203ab58352648af3c3cda530d6b_0:stderr]: + [ ! -d /var/lib/rancher/rke2/system-agent-installer ]"
Sep 23 18:41:07 jrmk3serrortest-pool1-bdac25ec-c58nn rancher-system-agent[1391]: time="2022-09-23T18:41:07Z" level=info msg="[6d8c502e51cd30a9866d09994365a3f0c64bd203ab58352648af3c3cda530d6b_0:stderr]: + mkdir -p /var/lib/rancher/rke2/system-agent-installer"
Sep 23 18:41:07 jrmk3serrortest-pool1-bdac25ec-c58nn rancher-system-agent[1391]: time="2022-09-23T18:41:07Z" level=info msg="[6d8c502e51cd30a9866d09994365a3f0c64bd203ab58352648af3c3cda530d6b_0:stderr]: + check_target_mountpoint"
Sep 23 18:41:07 jrmk3serrortest-pool1-bdac25ec-c58nn rancher-system-agent[1391]: time="2022-09-23T18:41:07Z" level=info msg="[6d8c502e51cd30a9866d09994365a3f0c64bd203ab58352648af3c3cda530d6b_0:stderr]: + mountpoint -q "
Sep 23 18:41:07 jrmk3serrortest-pool1-bdac25ec-c58nn rancher-system-agent[1391]: time="2022-09-23T18:41:07Z" level=info msg="[6d8c502e51cd30a9866d09994365a3f0c64bd203ab58352648af3c3cda530d6b_0:stderr]: + check_target_ro" </code>

**Comment by jameson-mcghee** [comment]
QA TEST PLAN
| Scenarios | Test Case |
|-------------------------------|
| 1 | Fresh install with highest K8s version for RKE2 node driver cluster as Admin User |
| 2 | Fresh install with second highest K8s version for RKE2 node driver cluster as Standard User with Cluster Owner role |

**Comment by HarrisonWAffel** [comment]
It seems this error stems from Rancher [updating the status field on the infrastructure object](https://github.com/rancher/rancher/blob/0811ad05c011e7becea052b107d1b62ce69e22d8/pkg/controllers/provisioningv2/rke2/machineprovision/controller.go#L175) each time the `machine-provision-pod` job state changes. The status is updated when the job is changed, as well as [during job creation](https://github.com/rancher/rancher/blob/0811ad05c011e7becea052b107d1b62ce69e22d8/pkg/controllers/provisioningv2/rke2/machineprovision/controller.go#L459).

Because these errors are benign and quickly resolve themselves I'm not sure there is much use propagating them to the UI, though they definitely should remain in the rancher logs.

**Comment by jameson-mcghee** [comment]
During testing on `v2.7-head` (Commit ID: e54432e) by following the Steps To Reproduce, I was able to verify that the error is no longer present in the Provisioning Logs for RKE2 clusters.  Therefore I am closing this ticket as Done.

**Steps to Reproduce (performed on both `v1.25.5+rke2r1` and `v1.24.4+rke2r1`:**
1. On a Rancher server, navigate to the _Cluster Management_ page
2. Click the _Create_ button
3. Toggle to _RKE2/K3s_, and then click _Amazon EC2_
4. Input a _unique name_ as well as the correct _AWS Access Key_ and _SecretKey_ credentials, and then click the _Create_ button
5. Input a _unique name_, set the _Machine Count_ value to "3", and select a valid _VPC/Subnet_, and then click the _Create_ button
6. After the cluster has provisioned successfully and is "Active", navigate to the _Cluster Management--> Cluster_ page for the cluster, and then navigate to the _Provisioning Log_ tab
7.  Scale the cluster up and down by 1 node
8. After the cluster has provisioned successfully and is "Active", navigate to the _Cluster Management--> Cluster_ page for the cluster, and then navigate to the _Provisioning Log_ tab

**`v2.7-head` (Commit ID: e54432e):**
**After Original Provisioning:**
![image](https://user-images.githubusercontent.com/13294321/212130324-f694706d-fc0a-4249-a7ed-0d01bd18dfb9.png)
![image](https://user-images.githubusercontent.com/13294321/212134670-63e3a5bb-bb0c-4daf-aac6-79d5cc8b55fd.png)

**After Scaling Up and Down:**
![image](https://user-images.githubusercontent.com/13294321/212134432-d2d082c0-d6cd-49d0-bfa6-80b742fa72ab.png)
![image](https://user-images.githubusercontent.com/13294321/212135780-bb0d210b-99c5-429c-b713-28aa2b10c427.png)
