### ISSUE TITLE
[BUG] v2prov is broken on `v2.7.0-rc1`

### ISSUE THREAD

**Issue by Josh-Diamond** [rancher/rancher#39106]
**Rancher Server Setup**
- Rancher version: `v2.7.0-rc1`
- Installation option (Docker install/Helm Chart): `Docker`
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details: `byo-valid`

**Information about the Cluster**
- Kubernetes version: Any
- Cluster Type (Local/Downstream):
Downstream v2prov clusters - [ node driver + custom ]

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
`Admin`

**Describe the bug**
v2prov is broken on `v2.7.0-rc1` and reports `No version info found in KDM`

**To Reproduce**
1. Fresh install of rancher `v2.7.0-rc1`
2. Attempt to provision a v2prov cluster
3. Reproduced

**Result**
UI reports the following error: `No version info found in KDM`

**Expected Result**
Create Cluster page should load and allow user input to provision cluster

**Screenshots**
<img width="1478" alt="Screen Shot 2022-09-23 at 11 45 45 AM" src="https://user-images.githubusercontent.com/46494969/192037980-bead9105-970a-4ca8-9313-e61af7563c17.png">

**Comment by snasovich** [comment]
This should be ready to test on `dev-v2.7` KDM branch as https://github.com/rancher/kontainer-driver-metadata/pull/978 is now merged.

**Comment by markusewalker** [comment]
Validated that this is addressed in `v2.7-head` https://github.com/rancher/rancher/commit/c567ef3f2bd13c2f2a5819242ab88cd334b1ae79.

**ENVIRONMENT DETAILS**
- Rancher install: Docker
- Rancher version: `v2.7-head` https://github.com/rancher/rancher/commit/c567ef3f2bd13c2f2a5819242ab88cd334b1ae79
- Browser: Chrome

**TEST RESULT
PASS**

**VERIFICATION STEPS**
1. Setup Rancher, created a standard user and logged in as that user.
2. Provisioned two downstream K3s node driver clusters with following roles: 1 etcd, 1 cp, 1 worker.
     - Ensured that one is of a fresh install of the highest K8s version and another is of the second highest K8s version to be upgraded.
3. Validated that the clusters and nodes came up `Active` in Cluster Management and Cluster Explorer.
4. With the second cluster provisioned, edited the config and upgraded the K8s version.
5. Validated that the upgrade completes and that the nodes and cluster are `Active` in Cluster Management and Cluster Explorer and that the K8s version is updated.
