### ISSUE TITLE
Scale not saving when Cloning a host

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3912]
Version: master 3/10

Steps to Reproduce: 
1.  Create a host with a scale of 3
2.  Clone that host

Results: The scale is set back to 1

Expected: Scale should still be 3?

**Comment by vincent99** [comment]
Scale isn't actually a property of the host and isn't saved anywhere.. if you set it to more than 1, multiple independent hosts are individually created.

**Comment by tfiduccia** [comment]
Version - master 3/16
Accepted as won't fix
