### ISSUE TITLE
Remove Istio versions prior to 1.14.x

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#39135]
As of Rancher 2.7.0, we will only be supporting Istio 1.14 and onward. Previous versions should be removed from the rancher/charts repo. 

The oldest k8s version that Rancher 2.7.0 will support is 1.23, we are safe to only have Istio 1.14.x available. 

EDIT: Even though it's not a supported setup, we need to still allow people to upgrade from 2.6.x and keep earlier versions. See comments on the PR for more info.

**Comment by vivek-infracloud** [comment]
Tested this issue on rancher v2.7.0-rc3. Only istio version 101.0.0+up1.14.3 is visible as per expectation.
Hence closing this issue.
![Screenshot from 2022-10-05 13-54-19](https://user-images.githubusercontent.com/83208989/194015347-2a8545ea-6c8f-4727-9d07-7b3a148ba17b.png)
