### ISSUE TITLE
v0.59.1 - Volumes do not remain checked when tabbing through sidekicks during upgrade

### ISSUE THREAD

**Issue by bkuhl** [rancher/rancher#3914]
I've attached a gif demonstrating this issue.  When performing an upgrade on a container with sidekicks, when I toggle through the various sidekicks the volume options do not remain checked.

Initially looking at the primary container:
![screen shot 2016-03-10 at 2 10 07 pm](https://cloud.githubusercontent.com/assets/524933/13681153/e5072af6-e6c9-11e5-9244-18a849bbd8fa.png)

Looking at the plugins sidekick
![screen shot 2016-03-10 at 2 10 14 pm](https://cloud.githubusercontent.com/assets/524933/13681163/f61ae814-e6c9-11e5-978a-d665fa102ccc.png)

Going back to the primary the volume checkboxes are no longer checked
![screen shot 2016-03-10 at 2 10 21 pm](https://cloud.githubusercontent.com/assets/524933/13681168/fec29660-e6c9-11e5-9e0c-4695e032cf22.png)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v0.59.1` Cattle: `v0.148.1` UI: `v0.90.0` |
|Access|`github` `admin`|
|Route|`null`|

**Comment by deniseschannon** [comment]
There is something weird going on with how it decides to keep the checkmarks for the volumes from section.

**Comment by tfiduccia** [comment]
Version - 1.1.0-rc3
Still not showing up in upgrade/clone

**Comment by pwFoo** [comment]
Also with v1.1.0. Following here.

**Comment by CumpsD** [comment]
1.1.2 still has this, caused me quite a few problems when upgrading with a sidekick, which suddenly didnt use the volumes from anymore

**Comment by tfiduccia** [comment]
Version - v1.2.0-pre2-rc2
Not fixed
Cloning - as soon as I rename the service the checkboxes for main service all get check and all sidekick checkboxed become unchecked.

**Comment by tfiduccia** [comment]
Version - v1.2.0-pre2-rc5
Verified fixed
