### ISSUE TITLE
Can't add Packet host

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3915]
Version - master 3/10

Steps to Reproduce: 
1. Try to add a packet host

Results:  Validation failed in API: DriverConfigExactlyOneRequired. Post error 422 in dev tools

Expected:
should add

**Comment by hibooboo2** [comment]
This is due to schema not being correctly uploaded. And gms not catching the error.

**Comment by tfiduccia** [comment]
Version - 0.63.0-rc3
Not fixed

Comment - only 1 machine driver is working at a time.  James informed and looking at it.

**Comment by sangeethah** [comment]
Fresh set up of rancher-server version - v0.59.1 
Had 1 amazon host added
Upgraded to v0.63.0-rc3
Tried to add packets host.
Host addition failed with error "Validation failed in API: DriverConfigExactlyOneRequired"

**Comment by will-chan** [comment]
Closing as this has now been verified.
