### ISSUE TITLE
[Forwardport] v2.7: Add options to lasso that improve performance

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#39160]
**Original Issue:**
https://github.com/rancher/rancher/issues/37350

**Comment by brudnak** [comment]
# ✅ PASSED

## Reproduction Environment

#### Not required.

<hr>

## Validation Environment


| Component                        | Version / Type                                     |
|----------------------------------|----------------------------------------------------|
| Rancher version                  | v2.7-4092002b7b921d2862b75d0111f2805200832ee0-head |
| Installation option              | Helm (high availability)                           |
| If Helm Chart k8s cluster        | v1.24.6+k3s1                                       |
| Cert Details                     | Let's Encrypt / `traefik`                          |
| k3s ha external db               | Aurora MySQL 5.7.mysql_aurora.2.10.2               |
| Helm version                     | v2.16.8-rancher2                                   |
| Downstream cluster type          | RKE1 Linode                                        |
| Downstream K8s version           | v1.24.6                                            |
| Authentication providers enabled | local                                              |
| Logged in user role              | Administrator & Standard user                      |
| Browser type                     | Google Chrome                                      |
| Browser version                  | 106.0.5249.103 (Official Build) (x86_64)           |


## Validation steps

1. Enabled metrics with controllers
2. Provision downstream cluster 
3. Create 300 projects in the local and downstream cluster - using terraform
4. Create 1,000 workloads in the projects - using deno/typescript `https://github.com/brudnak/deno-cattle-workloads` 
5. Set `CATTLE_RESYNC_DEFAULT` rancher env var to 5
6. Confirmed that controllers are running every 5 minutes
7. Set CATTLE_SYNC_ONLY_CHANGED_OBJECTS to mgmt
8. Confirm handlers spikes every 5 minutes are smaller
9. Set CATTLE_SYNC_ONLY_CHANGED_OBJECTS to mgmt,user
10. Should be even smaller
11. Set CATTLE_SYNC_ONLY_CHANGED_OBJECTS to mgmt,user,scaled
12. Will probably look comparable or smaller

## Additional Info

## RESULTS

#### ✅ Expected
Handler spikes to decrease

#### ✅ Actual
The handler spikes did decrease

<img width="601" alt="2022-10-10_22-04-51" src="https://user-images.githubusercontent.com/40877149/195006774-f2e20072-ea3b-4bba-a7b9-8e1a61400bfa.png">
