### ISSUE TITLE
[RFE]  Build and Push Image rancher/rancher to a different registry rather than Dockerhub

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#39162]
We need the ability to build and push rancher/rancher to a different registry rather than Dockerhub. 

This is to support https://github.com/rancher/rancher/issues/38551

**Comment by jiaqiluo** [comment]
removing the dev-validate label, we do need QA to validate the issue.

**Comment by jiaqiluo** [comment]
rancher v2.7.0-rc3 is available now

**Comment by slickwarren** [comment]
using rancher v2.7.0-rc3, I was able to use both helm and docker to install rancher from a non-docker registry. there are unrelated problems that I encountered that will not block this ticket, but will block others:
* branding was missing from rancher when using this image
* many images were missing, meaning that rancher was not very usable when only using the non-docker registry

The following were validated as part of this ticket:
* rancher has the non-docker registry set as default for system-default-registry when deployed from the non-docker image/helm repo
