### ISSUE TITLE
Cant load service container view with large number of hosts/containers

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#3918]
Rancher Version:
v0.63.0-rc2
Docker Version:
Docker 1.10.2
OS: 
Ubuntu 14.04
Steps to Reproduce: 
Create an environment with 20+ nodes
launch service with 300+ containers
Results: 
500 server error. Times out listening hosts

Expected:
See a list of containers within a service.

**Comment by prachidamle** [comment]
@cloudnautique do you still have your setup to debug on, or logs? Or can you add some details as to how to set this up locally?

**Comment by prachidamle** [comment]
@cjellick assigning this to you since it is the perf issue ticket

**Comment by will-chan** [comment]
@prachidamle this might be a different issue.  Part of this is the listHost command right?  Can we look to see if that is even optimizable before GA?

**Comment by cjellick** [comment]
I'm going to assign this to you @deniseschannon so that you can pick someone else to assign this to. I don't think this is in my current purview.

**Comment by deniseschannon** [comment]
@vincent99 Can you look at this issue and see if we're addressing it with the new performance fixes for UI?

**Comment by vincent99** [comment]
Yes, things will be faster in general.  Further improvement later with paged views instead of showing the whole world.
