### ISSUE TITLE
[BUG] metric-server pod remains in crashloop back off on k8s cluster v1.22.15

### ISSUE THREAD

**Issue by vivek-infracloud** [rancher/rancher#39188]
**Rancher Server Setup**
- Rancher version: v2.7-head
- Installation option (Docker install/Helm Chart): Docker RKE1

**Information about the Cluster**
- Kubernetes version: v1.22.15-rancher1-1
- Cluster Type (Local/Downstream): Downstream

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Admin

**Describe the bug**

On k8s v1.22.15-rancher1-1 the metric-server pod remains in CrashloopBackOff state. 
The v1.23 and v1.24 does not have this issue.

**To Reproduce**

1. Create a rancher server v2.7-head
2. Provision a RKE1 custom cluster v1.22.15-rancher1-1
3. Wait for cluster to come to an active state.
4. List all the pods.
5. Notice the metric-server (v0.5.1) pod is in CrashLoopBackOff state.

**Result**
Notice the metric-server pod is in CrashLoopBackOff state.

**Expected Result**
metric-server should be in running state.

**Screenshots**

![Screenshot from 2022-09-29 11-25-40](https://user-images.githubusercontent.com/83208989/193242868-e37058c4-4b09-44c6-a090-ad2aceb74d60.png)

**Comment by sowmyav27** [comment]
on 2.7-head, `35388ea` , on a 1.22.15 RKE1 (1 etcd/cp and 1 worker node cluster) metrics server is up and running, no issues seen. 

@vivek-infracloud could you re-test this issue?

**Comment by vivek-infracloud** [comment]
Re-tested this issue on rancher v2.7-head (0de241c).
The issue is indeed not reproducible. Hence closing the issue.

**Comment by markusewalker** [comment]
Reopening the issue so that @kinarashah can take a look at a current failing build issue. We'll need to cut a new RKE RC as a result once the build passes.

Once the build passes and a new RKE RC is cut, we can close this issue out.

**Comment by rishabhmsra** [comment]
Validated on rancher v2.7-head(c03e438)
- Provisioned RKE1 k8s v1.22.15-rancher1-1 cluster(1-cp, 1-etcd, 1-w).
- Validated the metrics-server pod.

Result:
- Metrics server pod is up and running and v0.5.2 version is present:
![metrics-server](https://user-images.githubusercontent.com/36376154/195272577-7c795745-bf79-4bf8-957f-00f537766518.png)

- Issue is resolved, hence closing it.
