### ISSUE TITLE
Document Out of Band release procedures

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#39195]
Write a document that includes the procedures and expectations for Out of Band (OOB) releases. Break this down by role, such as responsibilities for Helm Yes! engineer, code owner, project manager, etc. 

SURE-5362

**Comment by MKlimuszka** [comment]
@PennyScissors , where are the documents we need to review?

**Comment by PennyScissors** [comment]
@MKlimuszka This was completed a while ago as part of the series of KTs we did for the MApps team

**Comment by MKlimuszka** [comment]
The transition to the Mappsteam is complete, and all hand offs have been finished. Marking as complete.
