### ISSUE TITLE
Automated testing for Plug-In Operator

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#39192]
SURE-5361

**Comment by MKlimuszka** [comment]
@aiyengar2 , I know you added tests in 2.7.0. If you have more testing tasks for 2.7.1, can you list them out here?

**Comment by aiyengar2** [comment]
@MKlimuszka we only have automated testing the the plugin server, not the plugin operator. For 2.7.1, we need to entirely build out automated testing for the Plugin Operator
