### ISSUE TITLE
[BUG] Extreme memory usage when migrating projecttemplaterolebindings to different roletemplates

### ISSUE THREAD

**Issue by cmurphy** [rancher/rancher#39217]
Epic: https://github.com/rancher/rancher/issues/36702

Repro steps:

1. Create role that inherits from another role
 a. Go to add a project/namespace role, add one rule for "get secrets", then set it to "inherits from" "View Configmaps"
2. Create 100 projects in a cluster (https://github.com/cmurphy/scalingscripts/blob/main/genprojects.sh)
3. Create projectroletemplatebindings for each project pointing to this role
```
$ cat prtb.yaml 
apiVersion: management.cattle.io/v3
kind: ProjectRoleTemplateBinding
metadata:
  name: prtb-pbc4x
  namespace: {project}
projectName: c-m-r6rccwxt:{project}
roleTemplateName: rt-64j87
userName: u-8kd9l
userPrincipalName: local://u-8kd9l
$ for p in $(kubectl get projects -n c-m-r6rccwxt | grep -v p-698db | grep -v p-llmsr | awk 'NR>1{print $1}') ; do sed -e "s/{project}/${p}/" prtb.yaml | kubectl apply -f - ; done # p-698db and p-llmsr are default and system
```
3. Create a new role that has all the rules of the original role but does not inherit from anything
 a. Go to add a project/namespace role, add one rule for "get,list,watch configmaps" and another rule for "get secrets", do not go to inheritance tab
4. Delete all projectroletemplatebindings just created and create identical ones with `roleTemplateName` changed to the new role
```
$ for p in $(kubectl get projects -n c-m-r6rccwxt | grep -v p-698db | grep -v p-llmsr | awk 'NR>1{print $1}') ; do kubectl -n $p delete projectroletemplatebinding prtb-pbc4x ; sed -e "s/{project}/${p}/" -e 's/rt-64j87/rt-gn565/' prtb.yaml | kubectl apply -f - ; done
```
5. Notice memory usage rise. Usage does not immediately return to baseline after all 100 PRTBs are migrated.

**Comment by moio** [comment]
Engineering notes: realistically, it is unlikely a user really needs to delete and recreate hundreds of PRTBs in short time.

However, in general, collisions between objects named with [GenerateName](https://github.com/rancher/norman/blob/8d7dd5fb27fab105e63e9dd743917d59ec250245/types/id.go#L15-L18) functions might happen if a lot of objects are created and not garbage collected over long periods of time.

Specifically the collision probability is `P=1/(27^5)*N`, so there is a 1% collision probability with ~150k objects of the same kind, which is small but non negligible.

**Comment by moio** [comment]
Ongoing work in https://github.com/rancher/rancher/issues/46077 is expected to overhaul completely the mechanisms exercised here, and it is expected to considerably reduce resource consumption in this case.

So I am closing this ticket in favor of https://github.com/rancher/rancher/issues/46077. Another can always be reopened later if the problem appears again
