### ISSUE TITLE
Cloning/Upgrading do not remove old scheduling rules

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#3921]
Rancher Version:
v0.63.0-rc1

Steps to Reproduce: 
1. Create a service with scheduling rules
2. Clone the service
3. Remove all scheduling rules 

Results: 
The old scheduling rules are still on the service.

Expected:
No rules should be applied. 

Note: When testing we should make sure to verify that adding a new rule during upgrade/clone is honored.

**Comment by vincent99** [comment]
This is part of #3707
