### ISSUE TITLE
[BUG] Role inheritance adds unnecessary roles and rolebindings to the local cluster

### ISSUE THREAD

**Issue by cmurphy** [rancher/rancher#39216]
Epic: https://github.com/rancher/rancher/issues/36702

When a role template is created that inherits from another role template, and then a user is added to a cluster or project with that new role template, Rancher unnecessarily creates rolebindings for the additional rules in the local cluster.

Repro steps:

1. Create a downstream cluster
2. Create a user user1
3. Create a project/namespace role test1. Add rule "get secrets", then go to "Inherit From" -> "View config maps".
4. Add user1 to cluster with role test1.
5. Notice three new rolebindings in the local cluster:

```
$ kubectl get rolebindings -A -o wide | grep u-8kd9l | grep -v cattle-global-data
c-m-r6rccwxt                             rb-zosadc5l7m                                               Role/p-llmsr-projectmember                            7m32s   u-8kd9l                                                                                                                 
fleet-default                            r-cluster-k-view-p-llmsr-prtb-pbc4x-tfxi5itz7e              Role/r-cluster-k-view                                 7m32s   u-8kd9l                                                                                                                 
p-llmsr                                  prtb-pbc4x-rt-64j87                                         Role/rt-64j87                                         7m32s   u-8kd9l
$ kubectl -n p-llmsr get role rt-64j87 -o yaml | grep -A6 rules:
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
```
One of the rolebindings is for the rule to "get secrets". The others are for viewing the cluster or project objects. None have to do with configmaps, which the role inherited from. On the downstream cluster, both roles for configmaps and secrets are present:

```
kubectl get rolebinding -A
...
default                       rb-lfyqnqvcjz                                       ClusterRole/rt-64j87                                  3m11s
default                       rb-rbnofevqtx                                       ClusterRole/configmaps-view                           3m11s
...
```

The role rt-64j87 is totally unnecessary in the local cluster, as it is present in the downstream cluster. It should be omitted.

**Comment by moio** [comment]
Closing in favor of https://github.com/rancher/rancher/issues/46077
