### ISSUE TITLE
Should be taken back to "System" view when deploying catalog entries from "Rancher services".

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#3923]
Rancher Version: v0.63.0-rc2

Deploy any service from Catalog under catergory - "Rancher Services".
Once you launch the service , we are brought back to "Stacks" view which does not have the stack that was launched.
Since these services show up under "System" tab , user should be taken to this view where he will be able to see the progress of the service deployment that was launched.

**Comment by vincent99** [comment]
It should be going to:
  - The stack that was created for Cattle
  - The services page for K8s
  - The services page for Swarm

**Comment by tfiduccia** [comment]
Version - master 3/23
Verified fixed
