### ISSUE TITLE
Supporting K8s v1.23 -v1.24

### ISSUE THREAD

**Issue by Sahota1225** [rancher/rancher#39239]
We will be supporting 1.23 and 1.24 for 2.7.0. 

- [x]  RKE1 (and standalone) - Make changes in KDM 
- [x] RKE2/k3s - changes in KDM 
- [x] Hosted providers - EKS, AKS, GKE - Make changes accordingly (UI ?) - kev1 vs kev2
- [x] Imported clusters - k3s/RKE2

**Comment by Josh-Diamond** [comment]
Team 2 has reviewed this ticket;
Multiple assignees;
Leaving unassigned for now;

**Comment by sowmyav27** [comment]
**On latest 2.7.0-rc**

### RKE1 (and standalone) 
- [ ] Verify the k8s versions available for standalone `1.4.0-rcx` RKE1 are _only_ `v1.24.6-rancher1-1` and `v1.23.10-rancher1-1`

### RKE2/k3s
- [ ] RKE2 - Verify when provisioning RKE2 clusters from Rancher, the versions available should be _only_  `1.24.6+rke2r1` and `1.23.12+rke2r1`
- [ ] Provisioning a `1.24.6+rke2r1` custom cluster and verify cluster comes up successfully
- [ ] Provisioning a `1.23.6+rke2r1` AWS Node driver cluster and verify cluster comes up successfully
- [ ] K3S - Verify when provisioning k3s clusters from Rancher, the versions available should be _only_  `1.24.6+k3s1` and `1.23.12+ k3s1`
- [ ] Provisioning a `1.24.6+k3s1` custom cluster and verify cluster comes up successfully
- [ ] Provisioning a `1.23.6+k3s1` AWS Node driver cluster and verify cluster comes up successfully

### Imported clusters - k3s/RKE2
- [ ] Import a `1.21.14+k3s1` cluster into rancher. Verify user has only `1.24.6+k3s1` and `1.23.12+ k3s1` versions to upgrade to.
- [ ] Import a `1.21.14+rke2r1` cluster into rancher. Verify user has only 1.24.6+rke2r1` and `1.23.12+rke2r1` versions to upgrade to.

### Hosted providers - EKS, AKS, GKE 
- [ ] Provision an EKS kev2 cluster. Verify k8s version only 1.23+ are available on UI. Verify user is able to provision 1.23 cluster successfully.
- [ ] Provision an GKE kev2 cluster. Verify k8s version only 1.23+ are available on UI. Verify user is able to provision 1.23 cluster successfully.
- [ ] Provision an AKS kev2 cluster. Verify k8s version only 1.23+ are available on UI. Verify user is able to provision 1.24 cluster successfully.

**Comment by jiaqiluo** [comment]
can be validated on the latest v2.7-head

**Comment by sowmyav27** [comment]
Not completely ready for testing. So moving this to reopen
- 2.7-head shows all versions which is not expected - reopening
- Blocked by - https://github.com/rancher/dashboard/issues/7203

**Comment by sowmyav27** [comment]
**On `2.7.0-rc4`**

### RKE1
<img width="1233" alt="Screen Shot 2022-10-18 at 2 07 34 PM" src="https://user-images.githubusercontent.com/26032343/196545235-e14054fc-1239-4fb0-9816-ee714480e300.png">

### RKE2/k3s
<img width="1022" alt="Screen Shot 2022-10-18 at 2 08 11 PM" src="https://user-images.githubusercontent.com/26032343/196545244-2a9aca42-45b2-4071-8ae1-1689f4f6b15f.png">

**Comment by sowmyav27** [comment]
We will test everything else other than hosted clusters. But for tracking purpose, moving this to Blocked, since this issue is not completely available for validation until the UI issue is fixed.

**Comment by rishabhmsra** [comment]
Validated [these](https://github.com/rancher/rancher/issues/39239#issuecomment-1273578818) testcases on rancher v2.7-head(9f1e043):

**RKE2/k3s :**

- Below RKE2 and K3s versions available on rancher:

![versions](https://user-images.githubusercontent.com/36376154/196694148-9ccdbf87-d925-4a43-a17f-d4b6defdc7c4.png)

- Provisioned `1.24.6+rke2r1` custom cluster(1-cp, 1-etcd, 1-w) and it came up Active.
- Provisioned  `1.23.12+rke2r1` AWS Node driver cluster(1-cp, 1-etcd, 1-w) and it came up Active.
- Provisioned  `1.24.6+k3s1` custom cluster(1-cp, 1-etcd, 1-w) and it came up Active.
- Provisioned `1.23.12+k3s1` AWS Node driver cluster(1-cp, 1-etcd, 1-w) and it came up Active.

**Imported clusters - k3s/RKE2 :**
- Imported below K3s and RKE2 clusters and validated the cluster versions available for upgrade:

![imported-cluster](https://user-images.githubusercontent.com/36376154/196696917-47958225-b58f-4043-b666-db131ccce39c.png)

- Validated the versions available for k8s upgrade :

K3s:
![k3s-upgrade](https://user-images.githubusercontent.com/36376154/196705846-cce07335-1a47-44e1-948b-bcd7fee40b1b.png)

RKE2:
![rke2-upgrade](https://user-images.githubusercontent.com/36376154/196706053-dd37172a-fb6d-4cec-88b3-3076780bd8b2.png)

**Comment by Josh-Diamond** [comment]
The remaining tasks have been assigned as follows:

- @Josh-Diamond: RKE1 (standalone) + EKS

- @thaneunsoo: AKS + GKE

**Comment by thaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.7.0-rc6
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: Kev2
----------

### Testing: ###
NOTE: Kev1 is not supported as mentioned by @nwmac in [7277](https://github.com/rancher/dashboard/issues/7277#issuecomment-1293772873)

**AKS:** - Pass
1. Created an AKS cluster from Rancher UI → Create → AKS
2. Verified k8s versions only 1.23+ are available in the dropdown on UI 
3. Deployed an AKS cluster using default k8s version.
4. Verified the cluster comes up Active. k8s version `1.24.6`

Screenshot:
![image.png](https://zube.io/files/rancher/8c3a62a9fa48250591405c0082b309ce-image.png)

**GKE:** - Pass
1. Created a GKE cluster from Rancher UI → Create → GKE
2. Verified k8s versions only 1.23+ are available in the dropdown on UI
3. Deployed a GKE cluster using default k8s version.
4. Verified the cluster comes up Active. k8s version `1.23.8.1900`

Screenshot:
![image.png](https://zube.io/files/rancher/ea81d207d3532ff36da0681bbdd4f2ae-image.png)
