### ISSUE TITLE
Use XMLHttpRequest() to access metadata is not allowed

### ISSUE THREAD

**Issue by JayHaoDing** [rancher/rancher#3924]
Rancher Version: 0.59.1

**Steps to Reproduce:**

1. Send GET request to http://rancher-metadata via XMLHttpRequest() in JavaScript

```
var xmlhttp = new XMLHttpRequest();
xmlhttp.open('GET', 'http://rancher-metadata/latest/stacks/', false);
xmlhttp.open('GET', 'http://jsonip.com/', false);
xmlhttp.setRequestHeader('Accept', 'application/json')
xmlhttp.send(null);
```

**Results:**

```
XMLHttpRequest cannot load http://rancher-metadata/latest/stacks/. Origin file:// is not allowed by Access-Control-Allow-Origin.
⚠  Error: NETWORK_ERR: XMLHttpRequest Exception 101
```

**Expected:**

JSON formatted metadata is stored in xmlhttp.responseText

**Other Comments**
- http://rancher-metadata/latest/stacks/ can be accessed via curl in the same container
- Above JavaScript codes were executed together with casperjs

**Comment by vincent99** [comment]
I mean we could add the `Access-Control-Allow-Origin: *` header and that seems fairly harmless, but what exactly is the usecase for running a fake browser in node accessing metadata via XHR instead of just getting it with node directly?

**Comment by JayHaoDing** [comment]
@vincent99 we have an existing test framework based on casperjs and it will hit each JVM running in Docker container. Before Rancher is used, those JVMs' IPs were known because hosts were dedicated and we knew which host include what JVMs.

So now with Rancher we need be able to detect container's IP under specific service and stack to proceed testing.

**Comment by vincent99** [comment]
Fair enough; this won't make it in until after 0.63, and I'm not entirely sure it will actually fix your issue because it says the origin is `file://` in the error somewhow, but... https://github.com/rancher/rancher-metadata/pull/10

**Comment by JayHaoDing** [comment]
I was also bit confused why the log showed file:// although only http:// was used in the code.
Thanks for the fix :)

**Comment by vincent99** [comment]
This will be in the next release.
