### ISSUE TITLE
 Rancher-wins-upgrader 0.0.100 chart is visible on rancher-v2.6

### ISSUE THREAD

**Issue by doflamingo721** [rancher/rancher#39246]
**Problem**:
The rancher-wins-upgrader chart version `0.0.100` is a forward-ported chart which is visible on Rancher v2.6 because of the missing rancher-version constraints. For more context, refer: https://github.com/rancher/rancher/issues/38965#issuecomment-1268131263

**Solution**:
Add rancher-version annotation to the rancher-wins-upgrader `0.0.100` chart so that it does not appear on Rancher v2.6.x

**Comment by prachidamle** [comment]
@slickwarren Ca this chart be removed from rancher 2.6 charts?

I see your comments about this chart being nit needed in 2.7.0 here - https://github.com/rancher/rancher/issues/38965#issuecomment-1263748696

Does this change also apply to 2.6? 
cc @PennyScissors @doflamingo721 Lets hold on mergng this PR to 2.6 until this is confirmed.

cc @sowmyav27

**Comment by PennyScissors** [comment]
To clarify, this is a 2.5 version line chart and the only reason it exists in the >=2.6 version lines is to account for Rancher upgrade cases. However, we don't allow users to install a 2.5 chart in a >=2.6 setup, so we need to hide it for those Rancher versions like we do for all of our other charts. We just missed adding the annotation to this one.

**Comment by sowmyav27** [comment]
@prachidamle @PennyScissors Can you please confirm, if hiding an existing in 2.6.x is okay? As per the PR, the annotations are now : `catalog.cattle.io/rancher-version: '>= 2.5.0-0 < 2.6.0-0'`

**Comment by PennyScissors** [comment]
Yes, it is okay to hide an existing 2.5 chart in 2.6. It will not break existing installations, only hide the chart for new ones.

**Comment by rishabhmsra** [comment]
Validated on rancher v2.6.8:
- Goto local -> Apps -> Installed Apps
- Searched for rancher-wins-upgrader chart and it's not visible

Result:
- Rancher-wins-upgrader chart is not visible, hence closing the issue:
![wins-chart](https://user-images.githubusercontent.com/36376154/195355923-12a1345d-0003-4dfe-a35f-9f9fc1bf628e.png)
