### ISSUE TITLE
[BUG] Monitoring v2 - serviceMonitor/kube-system/rancher-monitoring-kubelet down after installing monitoring

### ISSUE THREAD

**Issue by ronhorton** [rancher/rancher#39242]
**Rancher Server Setup**
- Rancher version: `2.7.0-rc3`
- Installation option (Docker install/Helm Chart): `Helm`
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): `Rke1`
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: `v1.24.6`
- Cluster Type (Local/Downstream): `downstream amazon ec2 sles 15`
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: `admin`

**Describe the bug**

After installing monitoring v2, launch prometheus targets page and observe that `serviceMonitor/kube-system/rancher-monitoring-kubelet` has 3/8 up 
**To Reproduce**
1. install rancher-monitoring on downstream sles 15 cluster
2. navigate to cluster > monitoring > prometheus targets

**Result**
unhealthy rancher-monitoring-kubelet

**Expected Result**
all healthy

**Screenshots**

<img width="1593" alt="2022-10-05_18-33-23" src="https://user-images.githubusercontent.com/89212856/194176192-ca2b9529-530f-4ed8-b4e3-d757fc317345.png">

**Additional context**

**Comment by MKlimuszka** [comment]
We think this will end up being due to a different underlying issue for Team 2. But Team 3 should do some initial investigation first.

**Comment by geethub97** [comment]
this is working in v2.7.0-rc9

**Comment by ronhorton** [comment]
Verified `fixed` 
rancher `2.7-head commit ID da810a7`
all workloads active
all prometheus targets active
