### ISSUE TITLE
kontainer-engine-driver-huawei for rancher v2.6.8 

### ISSUE THREAD

**Issue by JorgeMaciel93** [rancher/rancher#39270]
i've trying to provisioning a cluster huawei cce with Rancher v2.6.8 using: https://github.com/cnrancher/kontainer-engine-driver-huawei/releases/download/v0.1.5/kontainer-engine-driver-huawei-linux, but it does't work, the cluster assuming the state of provisioning but show a error: "rpc error reading from server eof: "

**Comment by niusmallnan** [comment]
You can launch a CCE cluster on Huawei Cloud portal, then generic import it into Rancher.

If you wish `Launch CCE From Rancher`, it doesn't work now.

**Comment by testn** [comment]
So https://github.com/cnrancher/kontainer-engine-driver-huawei/releases/download/v0.1.5/kontainer-engine-driver-huawei-linux is not maintained anymore?
