### ISSUE TITLE
Reporting container issues in rancher UI

### ISSUE THREAD

**Issue by miko** [rancher/rancher#3928]
Rancher Version: v0.56.1

Docker Version: 1.9.1

OS: CentOS Linux 7

Steps to Reproduce: make 2 instances of containers with conflicting published port

Results: One container started correctly, the other one is in "Stopped" state with ip="None", sometimes " 500 Server Error". If you are lucky and fast, yaou can see in "View in API" longer version: " 500 Server Error": Internal Server Error ("failed to create endpoint r-test_test_2 on network bridge: Bind for 0.0.0.0:80 failed: port is already allocated") ". But this "500 Server Error" message stays for short amount of time.

Expected: The "500 Server Error" and its longer form should be available as a "last error reported by the container" as long as possible (until next error overwrites it). 90% of the time there is no visible error ("Networking", "None", "In Progress", "Running")

Generally, It would be nice to have last error message (and possible details) on any reason why running a container did not succeed (like port conflict, port out of range, no volume, disk full or any other reason). It could help in debugging some issues, like #1372, #435, #633.

**Comment by deniseschannon** [comment]
In our next release we have added the messages in the UI. 
https://github.com/rancher/rancher/issues/3630
