### ISSUE TITLE
[BUG] New project creation with restricted or unrestricted PSP fails on k3s cluster

### ISSUE THREAD

**Issue by vivek-infracloud** [rancher/rancher#39298]
**Rancher Server Setup**
- Rancher version: v2.7-head
- Installation option (Docker install/Helm Chart): Docker install

**Information about the Cluster**
- Kubernetes version: v1.24.6+k3s1
- Cluster Type (Local/Downstream): Downstream

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Admin

**Describe the bug**

New project creation with restricted or unrestricted PSP fails with the error.

**To Reproduce**

1. Create a k3s [harden cluster](https://github.com/macedogm/rancher-docs/blob/12eda5ea06b84650f2ccf59e917ee95b1c892283/docs/reference-guides/rancher-security/rancher-v2.7-hardening-guides/k3s-hardening-guide-with-cis-benchmark.md) with PSP set to restricted.
2. Make sure the cluster comes up to active state.
3. Create a new project with PSP set to unrestricted.

**Result**
New project creation fails with error `Cluster does not have Pod Security Policies enabled`

**Expected Result**
New project with unrestricted PSP gets created.

**Screenshots**
![psp-error](https://user-images.githubusercontent.com/83208989/195852677-a3154b8d-d417-4bfb-983f-519a4e36c7aa.png)

**Additional context**
While creating project with any PSP other than "Cluster Default" throws following error: cluster [c-m-59d4rz6p] does not have Pod Security Policies enabled on the UI.

- Web console error:

  - Failed to load resource: the server responded with a status of 404 (Not Found)
  - Failed to load resource: the server responded with a status of 422 (Unprocessable Entity)

- Network calls:

  - GET call to endpoint fails with below response-> https://cluster-ip/k8s/clusters/c-m-59d4rz6p/v1/namespaces/c-m-59d4rz6p
    - response : {"type":"error","links":{},"code":"NotFound","message":"namespaces \"c-m-59d4rz6p\" not found","status":404,"type":"error"}

- POST call to endpoint https://cluster-ip/v3/projects succeeds with 201 status and project gets created
- POST call to endpoint fails with below response -> https://cluster-ip/v3/projects/c-m-59d4rz6p:p-pkhjc?action=setpodsecuritypolicytemplate
  - response : {"baseType":"error","code":"InvalidAction","message":"cluster [c-m-59d4rz6p] does not have Pod Security Policies enabled","status":422,"type":"error"}
  - Request Payload: {"podSecurityPolicyTemplateId":"restricted"}

**Comment by Sahota1225** [comment]
moving the issue to 2.7.1 as it is not required for k3s to go GA.

**Comment by snasovich** [comment]
This is related to (not caused by) the following issue - https://github.com/rancher/rancher/issues/37443 and the corresponding PR https://github.com/rancher/rancher/pull/37475.
Unfortunately, unlike in the case of RKE2 clusters, PSPs are not enabled by default for k3s clusters (https://docs.k3s.io/security/hardening-guide#kubernetes-runtime-requirements). So, the logic for checking whether PSPs are enabled needs to be improved and cover the case of k3s.

**Comment by sbstp** [comment]
@vivek-infracloud hey Vivek. Could you detail the steps that you used to setup the hardened k3s cluster? I have tried following the guide you linked to, but I keep running into issues trying to setup the cluster. Having the exact steps you used would help be reproduce the issue and get the same kind of cluster running.

**Comment by vivek-infracloud** [comment]
Tested the issue on rancher v2.7.2-rc1. 

Test steps

- Created a rancher server v2.7.2-rc1
- Provisioned a hardened k3s cluster.
- Created a New Project with PSP set to unrestricted.
- Project creation was successful.
- In addition, created a namespace and deployed a workload.

Issue is not active anymore, hence closing the issue.
