### ISSUE TITLE
Feature Charts: Add NeuVector 2.2.3 Chart in 2.6.9

### ISSUE THREAD

**Issue by selvamt94** [rancher/rancher#39295]
NeuVector chart 2.2.3 has an update for image tag 5.0.3. Need to add the Neuvector chart for the upcoming Rancher 2.6.9.

Add 2.2.3 Neuvector chart in feature chart 2.6.9 - Cluster Manager/Rancher Marketplace
@sowmyav27 @jiaqiluo

**Comment by jiaqiluo** [comment]
should be available on the v2.6-head

**Comment by selvamt94** [comment]
Tested with latest Rancher v2.6-head image with Neuvector feature chart 100.0.2+up2.2.3 from dev-v2.6 branch, able to deploy and do SSO to NeuVector UI from Rancher manager.
