### ISSUE TITLE
[BUG] backup-restore-operator yaml file causes install error when including value for imagePullSecrets

### ISSUE THREAD

**Issue by ronhorton** [rancher/rancher#39291]
**Rancher Server Setup**
- Rancher version: `2.6.9-rc4`
- Installation option (Docker install/Helm Chart): `Helm`
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): `local rke1`
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: `v1.24.4`
- Cluster Type (Local/Downstream): `Local`
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: `admin`

**Describe the bug**
when passing in values for imagePullSecrets in values.yaml file, error is generated when attempting to pass in an array ['value1','value2']; on install, error thrown, and imagePullSecrets field is saved with `null`. 

**To Reproduce**
1. begin installation of backup-restore-operator 
2. edit values yaml
3. include value ['value1','value2','value3']
4. edit value to include a list and value is saved.

**Result**
error in logs: 
`Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(Deployment.spec.template.spec.imagePullSecrets[0]): invalid type for io.k8s.api.core.v1.LocalObjectReference: got "string", expected "map"`

**Expected Result**
backup-restore-operator installed with no errors. included array saved to values.yaml

**Additional context**
discovered when testing **https://github.com/rancher/backup-restore-operator/issues/264**

**Comment by sowmyav27** [comment]
Hi @MKlimuszka Can you confirm if this has to go in `2.7.0` or `2023-Q1-v2.7x` ? cc: @bmdepesa

**Comment by nickwsuse** [comment]
`Verified on v2.7-head ID: 6316baf`

The array is now being recognized as expected for the imagePullSecrets as well as new custom values.
