### ISSUE TITLE
[BUG] Non-user friendly/inaccurate message when attempting to delete Cloud Credentials being used

### ISSUE THREAD

**Issue by jameson-mcghee** [rancher/rancher#39300]
**Rancher Server Setup**
- Rancher version: v2.7-head (Commit ID: 76c98b4)
- Installation option (Docker install/Helm Chart): Any
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): Any
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: Any
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Node Driver (Infrastructure Provider)

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Any
  - If custom, define the set of permissions: N/A

**Describe the bug**
When attempting to delete a Cloud Credential that is being used by an active cluster, the user is presented with a non-user friendly error message.

**To Reproduce**

1. Create AWS Cloud Credentials in Rancher
2. Create an EC2 Node Driver cluster using the newly created AWS Cloud Credentials
3. When the cluster is Active, navigate back to the AWS Cloud Credentials, click the "three-dot" button for the credentials, and then click the Delete button
4. In the "Are you sure?" dialogue box, click the Delete button

**Result**
Note the user is presented with the message "_Index with name by-cloud-cred does not exist_" in the "Are you sure?" dialogue box.

**Expected Result**
A clear and concise error message is presented that explains to the user why they are not able to delete that set of Cloud Credentials.

**Screenshots**
![image](https://user-images.githubusercontent.com/13294321/195912608-4f5a2995-0a45-4a0e-8c21-506611893909.png)

**Additional context**
This is a Blocker to the completion/validation of [Dashboard ticket 7138](https://github.com/rancher/dashboard/issues/7138)

**Comment by jameson-mcghee** [comment]
This ticket is not a release blocker for v2.7.0, and is therefore going to be moved to the v2.7.1 Milestone.

**Comment by HarrisonWAffel** [comment]
I cannot reproduce this on 2.7-head (0dcfd16e7af68b6856ecc38654254e8ed18567de). 

When deleting a cloud credential currently being used by an RKE1 cluster in AWS or Digital Ocean, i get the following message `cloud credential is currently referenced by node template <node_template_name>`. 

When deleting a cloud credential being used by an RKE2 cluster i get the message `cloud credential is currently referenced by provisioning cluster <provisioning_cluster_name>`. 

@jameson-mcghee are there any additional details or steps that are needed to reproduce this issue?

**Comment by snasovich** [comment]
@jameson-mcghee , moving this "To Test" as there is a pending question to reproduce it per the previous comment.

**Comment by jameson-mcghee** [comment]
I retested this issue on both `v2.7.0-rc10` as well as `v2.7-head` (Commit ID: ) as both an Admin User and a Standard User. During testing, I followed the previously described Steps to Reproduce (relisted below), and I observed that intermittently the "_Index with name by-cloud-cred does not exist_" error message would appear (when the API response returned a 500), and that it would intermittently provide the error message "_cloud credential is currently referenced by provisioning cluster <CLUSTER_NAME>_" (when the API response returned a 422). However, during the bulk of the testing, the  "_Index with name by-cloud-cred does not exist_" error message was observed as being provided.
cc @HarrisonWAffel @snasovich

As a secondary note, the first letter of the first word in the message should be capitalized for proper grammar when this issue is resolved. i.e. For the sake of grammar and presentation, the error message should state **"_These cloud credentials are currently referenced by provisioning cluster: <CLUSTER_NAME>_"**

**To Reproduce**

1. Create AWS Cloud Credentials in Rancher
2. Create an EC2 Node Driver cluster using the newly created AWS Cloud Credentials
3. When the cluster is Active, navigate back to the AWS Cloud Credentials, click the "three-dot" button for the credentials, and then click the Delete button
4. In the "Are you sure?" dialogue box, click the Delete button

`v2.7.0-rc10` Standard User (422 Response):
![image](https://user-images.githubusercontent.com/13294321/201137989-53c1aca5-9439-40ef-8a6d-a2207e940eac.png)

`v2.7.0-rc10` Standard User (500 Response):
![image](https://user-images.githubusercontent.com/13294321/201137898-3cdcc2d1-4bdd-4efc-a246-011195d03cad.png)

`v2.7-head` Standard User:
![image](https://user-images.githubusercontent.com/13294321/201137871-ca5cc369-8bfc-47be-8882-e9a893c544a9.png)

**Comment by HarrisonWAffel** [comment]
After a few more attempts I was able to reproduce this error, it seems it is more easily reproducible on an HA setup. The root cause seems to be an error returned by the cluster cache when we attempt to query the provisioning cluster this cloud credential belongs to.

https://github.com/rancher/rancher/blob/fe78be33779cd0d4ee122bd17e9678d3700f9787/pkg/api/norman/customization/cred/store.go#L87-L91

Because this error is being returned from client-go directly i'm not yet sure if there is a way to definitively resolve the error, but I'm still looking into it. At the very least we can make the error messages shown to the user more informative / friendly and fix some of the other casing issues noted by Jameson.

**Comment by HarrisonWAffel** [comment]
Looking into this a bit deeper I believe I have found the reason that this issue only intermittently appears in HA setups.

The credential store is using an indexer within the provisioning cluster cache to associate provisioning clusters with cloud credentials by looking at the provisioning clusters `CloudCredentialSecretName` and comparing it with the id sent to the backend by the frontend. 

However, This indexer is added to the cache within the `v2provisioning` cluster controller which is only registered within the leader pod in an HA setup. The requests to delete the cloud credential are not always sent to the leader pod, in which case we see the `index with name cloud-cred does not exist` message. This also explains why it is not reproducible in local setups or on docker installs - as the single rancher instance will always be the leader. In order for this issue to be resolved we likely need to register this indexer for all Rancher replica's, not just the leader.

**Comment by annablender** [comment]
@HarrisonWAffel's fix here may also fix https://github.com/rancher/rancher/issues/39515.

**Comment by jameson-mcghee** [comment]
When testing on Rancher `v2.7-head` (Commit ID: 38979f8), I was able to verify this issue is no longer reproducing by following the Steps to Reproduce multiple times (ensuring that the issue is no longer intermittent) . Therefore I am closing this ticket.

Steps To Reproduce:
1. Create AWS Cloud Credentials in Rancher
2. Create an EC2 Node Driver cluster using the newly created AWS Cloud Credentials
3. When the cluster is Active, navigate back to the AWS Cloud Credentials, click the "three-dot" button for the credentials, and then click the Delete button
4. In the "Are you sure?" dialogue box, click the Delete button


`v2.7-head` (Commit ID: 38979f8):
![image](https://user-images.githubusercontent.com/13294321/205396681-925928bb-60df-45e1-a656-e73d4a3179cd.png)
![image](https://user-images.githubusercontent.com/13294321/205396690-35463e96-e7fd-40a2-af77-91664c5f1671.png)
