### ISSUE TITLE
[BUG] Unable to provision an RKE2 cluster when a global registry of format `xyz.io/test` is set

### ISSUE THREAD

**Issue by markusewalker** [rancher/rancher#39307]
**Rancher Server Setup**
- Rancher version: `v2.6.9-rc4`
- Installation option (Docker install/Helm Chart): Docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: `v1.24.4+rke2r1`
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): AWS

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Standard
  - If custom, define the set of permissions:

**Describe the bug**

Prior to attempting to provision an RKE2 cluster, I set the global registry to be of a format `xyz.io/test`. When doing that, the cluster never provisions as the etcd node is stuck in `Reconciling`, waiting for the etcd and kubelet to finish. Upon investigating the logs, I noted the following:

```
Oct 14 20:00:10 sowmya-rke2-pool1-d84e1fe4-dbxtm systemd[1]: rke2-server.service: Scheduled restart job, restart counter is at 21.
Oct 14 20:00:10 sowmya-rke2-pool1-d84e1fe4-dbxtm systemd[1]: Stopped Rancher Kubernetes Engine v2 (server).
Oct 14 20:00:10 sowmya-rke2-pool1-d84e1fe4-dbxtm systemd[1]: Starting Rancher Kubernetes Engine v2 (server)...
Oct 14 20:00:10 sowmya-rke2-pool1-d84e1fe4-dbxtm sh[2852]: + /usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service
Oct 14 20:00:10 sowmya-rke2-pool1-d84e1fe4-dbxtm sh[2857]: Failed to get unit file state for nm-cloud-setup.service: No such file or directory
Oct 14 20:00:10 sowmya-rke2-pool1-d84e1fe4-dbxtm rke2[2876]: time="2022-10-14T20:00:10Z" level=warning msg="not running in CIS mode"
Oct 14 20:00:10 sowmya-rke2-pool1-d84e1fe4-dbxtm rke2[2876]: time="2022-10-14T20:00:10Z" level=fatal msg="failed to parse system-default-registry: registries must be valid RFC 3986 URI authorities: <retracted registry>"
Oct 14 20:00:10 sowmya-rke2-pool1-d84e1fe4-dbxtm systemd[1]: rke2-server.service: Main process exited, code=exited, status=1/FAILURE
Oct 14 20:00:10 sowmya-rke2-pool1-d84e1fe4-dbxtm systemd[1]: rke2-server.service: Failed with result 'exit-code'.
Oct 14 20:00:10 sowmya-rke2-pool1-d84e1fe4-dbxtm systemd[1]: Failed to start Rancher Kubernetes Engine v2 (server).
```
It is worth noting that when attempting to provision an K3s cluster with this setup, that is able to provision successfully. This is because RKE2 pulls images to bootstrap at runtime, so the registry needs to validated immediately; K3s does not, so it is more lenient.

**To Reproduce**

1. Install Rancher with the `CATTLE_SYSTEM_DEFAULT` equal to a private registry with `xyz.io/test` format.
2. Create a standard user and login to Rancher as that user.
3. Provision a downstream RKE2 cluster with 1 etcd, 1 cp, 1 worker; ensure that the private registry is set.
4. Note that the etcd node is stuck in a state of `Reconciling`.

**Result**
RKE2 cluster is unable to provision successfully.

**Expected Result**

RKE2 cluster should be able to provision successfully.

**Comment by HarrisonWAffel** [comment]
This is expected behavior and is working as designed. When providing custom registries we expect you to only provide the hostname (URI) of the registry, and not any paths or additional information. To successfully use a registry hostname which includes a path you should add in rewrite behavior when configuring the registry so the hostname can be resolved without any paths when pulling an image. 

K3s handles registries slightly differently, and does not perform the same validation as RKE2, which is it is able to successfully pull images using a registry hostname including a path.  I am closing this issue as the behavior shown in RKE2 is desired and up to spec.

**Comment by markusewalker** [comment]
Thanks @HarrisonWAffel for the above detailed explanation. Along with the offline slack thread with additional information, I'm comfortable closing this issue as this is working as intended.
