### ISSUE TITLE
Add release notes to rc tags

### ISSUE THREAD

**Issue by withinboredom** [rancher/rancher#3931]
It would be super helpful if we could see which bugs are addressed in a release candidate. If I see a bug I'm experiencing is fixed in an rc, I'd be willing to update the affected install and help with verifying that it's fixed.

I think this could lead to a better rancher for everyone.

**Comment by deniseschannon** [comment]
Right after a RC is cut, anything labeled "status/to-test" is ready to be tested, but as time goes on more issues that are not actually in a RC are will be added to that same label. Most of our engineers will link the relevant PR, so you can always look at when it was merged and compare it to when the RC was cut. 

We typically assign these issues to our QA team to look at and we try to verify them as fast as possible. Please feel free to look at the filter if you want to try testing any of them. :)
