### ISSUE TITLE
[RFE] Ability to customize RKE2 Provisioned VSphere machine names and hostnames

### ISSUE THREAD

**Issue by HoustonDad** [rancher/rancher#39317]
**Is your feature request related to a problem? Please describe.**
When VSphere machines are provisioned with RKE2, the machine name and hostname of the machine are provisioned with a hash, similar to this:
{CLUSTER_NAME}-{POOL_NAME}-##########-#####

Gov agencies require all machines to be connected to Active Directory, and generally, they will key off the first 15 chars of a hostname. 

Due to this provisioning with the hashes, Rancher is unable to generate 'unique' hostnames for machines in a pool. 

eg. 
Cluster Name: C1
Pool name: P1

This ends up with machine names such as:
C1-P1-##########-#####

As AD will key off the first 15 chars, it will key off of 'C1-P1-##########'. Since the hash is so long, this results in non-unique hostnames for AD to key off of. 

**Describe the solution you'd like**
The ability to set the length of the hashes, away from the default 10 characters

**Describe alternatives you've considered**
We can use hostnamectl inside of cloud-init, but on VSphere, this is hard to do properly, as there has to be an API or system that can be called to figure out which hostname is required

**Comment by robertancheril** [comment]
I have the same issue. If you have a workaround, please share.

Thanks,

**Comment by HoustonDad** [comment]
This is still needed

**Comment by kennychen101** [comment]
yes, this is still needed.

**Comment by fabiorauber** [comment]
Still relevant! Hostnames are just too long, should be customizable.
