### ISSUE TITLE
k3s / RKE2: allow requesting Spot Instances for EC2 deployment

### ISSUE THREAD

**Issue by vkruoso** [rancher/rancher#39328]
When creating RKE1 clusters with EC2 node driver it is possible to request Spot Instances. This option is not available when provisioning clusters with k3s / RKE2 engine.

**Comment by HarrisonWAffel** [comment]
Hi @vkruoso, this feature is currently supported for RKE2/K3s clusters. The option to enable it can be found under the `Advanced` options of a given node pool. 

![Screen Shot 2022-10-17 at 5 40 08 PM](https://user-images.githubusercontent.com/25062254/196289141-79ab16e2-f38c-43ca-8247-e976938871bb.png)

**Comment by vkruoso** [comment]
hi @HarrisonWAffel! Thanks a lot! So sorry, did not see it there (even though I've opened the advanced menu).

**Comment by HarrisonWAffel** [comment]
No worries! happy to help
