### ISSUE TITLE
[feature testing bug] UI extensions install failure on a hardened cluster. pod stuck in Createcontainer state

### ISSUE THREAD

**Issue by AndrewHoffmanQA** [rancher/rancher#39323]
**Rancher Server Setup**
Rancher HA hardened generated via jenkins job
rancher image 2.7-0dcfd16

**Describe the bug**
as an admin when I navigate to the extensions page and attempt to install the UI extensions operator, the pod never enters a 'running' state. the pod stays in 'Createcontainer' state with error  'Containers with unready status: [ui-plugin-operator]'

the logs show as blank. 

**To Reproduce**
create an HA hardened local
log in
hamburger menu > configurations > extensions
click to install the operator

**Result**
pod never enters a 'running' state. the pod stays in 'Createcontainer' state with error  'Containers with unready status: [ui-plugin-operator]'

**Expected Result**
a successful install with the pod displaying a 'running' state

**Screenshots**
![image](https://user-images.githubusercontent.com/89030218/196247829-a801b61e-f5a8-4252-be51-13a63fea1e3b.png)

**Additional context**

**Comment by MKlimuszka** [comment]
@PennyScissors, this a blocker for testing in hardened clusters.

**Comment by PennyScissors** [comment]
Error seen in the pod:
```
CreateContainerConfigError (container has runAsNonRoot and image has non-numeric user (uipluginoperator), cannot verify user is non-root (pod: "ui-plugin-operator-6b9fd69b49-cmpxq_cattle-ui-plugin-system(4a719147-c23b-42de-a4e0-a75a95aa8149)", container: ui-plugin-operator)) 
```
