### ISSUE TITLE
Machine driver state doesn't update unless I refresh

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3932]
Version: 0.63.0-rc3

Steps to Reproduce: 
1.  Add a Machine Driver
2.  Wait

Results: State does not update unless I hit the browser's refresh button

Expected: Should update

**Comment by vincent99** [comment]
They're not really properly marked transitioning in the API, but added state=requested as another thing that will trigger polling.

**Comment by tfiduccia** [comment]
Version - master 3/15
Verified fixed
