### ISSUE TITLE
Update Nutanix Node Driver to 3.3.0+

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#39333]
Updated Nutanix node driver to version 3.3.0 or later.

**Comment by snasovich** [comment]
Confirmed I see Node Driver updated to 3.3.0 on the latest `v2.7-head` tag.
@tuxtof since I don't have a Nutanix account, could you please confirm this version of driver is working as expected?

**Comment by tuxtof** [comment]
i confirm v3.3.0 was tested with rancher 2.6 and 2.7

**Comment by snasovich** [comment]
Closing as validated per the previous comment.
