### ISSUE TITLE
Add Docker 20.10.18, 20.10.19, 20.10.20 and 20.10.21

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#39345]
Upstream has released the following:
https://github.com/moby/moby/releases/tag/v20.10.18
https://github.com/moby/moby/releases/tag/v20.10.19
https://github.com/moby/moby/releases/tag/v20.10.20
https://github.com/moby/moby/releases/tag/v20.10.21

The same approach for implementation and testing as https://github.com/rancher/rancher/issues/38390

**Comment by jloisel** [comment]
https://github.com/moby/moby/releases/tag/v20.10.20

**Comment by sowmyav27** [comment]
Note: This issue to be closed only after release of these docker versions cc: @vivek-infracloud @rishabhmsra @mitulshah-suse

**Comment by vivek-infracloud** [comment]
Completed testing docker versions as per the test plan on the confluence. 
Docker is working as expected for all the OSes. 

@sowmyav27 @kinarashah  Waiting for the release of the docker versions before closing this issue.

**Comment by kinarashah** [comment]
Docker versions are now released: 

Tested the following URLs: 

- [x]  curl -L https://releases.rancher.com/install-docker/20.10.18.sh 
- [x] curl -L https://releases.rancher.com/install-docker/20.10.19.sh 
- [x] curl -L https://releases.rancher.com/install-docker/20.10.20.sh 
- [x] curl -L https://releases.rancher.com/install-docker/20.10.21.sh 

Confirmed the default URL points to the latest: 20.20.21
- [x] curl -L https://releases.rancher.com/install-docker/20.10.sh

**Comment by sowmyav27** [comment]
Closing the issue.
