### ISSUE TITLE
[Feature Testing Bug] UI extensions- if operator is not installed, upon logging in a 404 is thrown by the API. 

### ISSUE THREAD

**Issue by AndrewHoffmanQA** [rancher/rancher#39357]
**Rancher Server Setup**
Rancher HA Local
Rancher v2.70-rc4

**Describe the bug**
requirements- local server must not have the UI extensions operator installed

1. standup an HA
2. open your browser console
3. log into HA

**Result**
in browser dev tool console -- 
GET https://[enter server name here].qa.rancher.space/api/v1/namespaces/cattle-ui-plugin-system/services/http:ui-plugin-operator:80/proxy/index.json 404 

```
console.js:31 Could not load UI Plugin list 
{kind: 'Status', apiVersion: 'v1', metadata: {…}, status: 'Failure', message: 'services "ui-plugin-operator" not found', …}
apiVersion
: 
"v1"
code
: 
404
details
: 
{name: 'ui-plugin-operator', kind: 'services'}
kind
: 
"Status"
message
: 
"services \"ui-plugin-operator\" not found"
metadata
: 
{}
reason
: 
"NotFound"
status
: 
"Failure"
_headers
: 
{audit-id: '18eeac9a-5bda-4e70-8172-8434feffa36c', cache-control: 'no-cache, no-store, must-revalidate, no-cache, private', content-length: '259', content-type: 'application/json', date: 'Tue, 18 Oct 2022 21:28:32 GMT', …}
_req
: 
XMLHttpRequest {readyState: 4, timeout: 0, withCredentials: true, upload: XMLHttpRequestUpload, onreadystatechange: ƒ, …}
_status
: 
404
_statusText
: 
""
_url
: 
"/api/v1/namespaces/cattle-ui-plugin-system/services/[http:ui-plugin-operator:80/proxy/index.json](http://ui-plugin-operator/proxy/index.json)"
[[Prototype]]
: 
Object


```
**Expected Result**
no 404s are thrown

**Screenshots**

![image](https://user-images.githubusercontent.com/89030218/196743428-e2f45695-c688-4b65-8823-24a8b9d55e67.png)

**Additional context**

**Comment by MKlimuszka** [comment]
According to Ron, this is functioning as intended. It is a consequence of not using Steve.
