### ISSUE TITLE
[BUG] Rancher api schema missing causes workload deployment to fail

### ISSUE THREAD

**Issue by ronhorton** [rancher/rancher#39350]
**Rancher Server Setup**
- Rancher version: `v2.7.0-rc4`
- Installation option (Docker install/Helm Chart): `helm`
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): AKS - 1.24.6

**Information about the Cluster**
- Kubernetes version: `v1.24.6`

- Cluster Type (Local/Downstream): Downsream - AKS kev2 - can be any cluster

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) `admin`

**Describe the bug**

- Deploying workload in 2.7.0-rc4, error for missing schema prevents workload from deploying
- Navigate to Ember UI --> cluster --> Project --> and create a workload.
- Error seen on UI

<img width="705" alt="Screen Shot 2022-10-18 at 1 27 42 PM" src="https://user-images.githubusercontent.com/26032343/196537111-dd2858ca-7f6a-4e69-ab46-d0ab0fbff092.png">

- Network calls that throw error:
`https://rancher-server/v3/schemas/projectlogging?sort=name` and `https://rancher-server/v3/schemas/clusterlogging?sort=name` and they throw a 404 error
**To Reproduce**

**Result**
error for missing schema:
`/v3/schemas/clusterlogging?sort=name`
`/v3/schemas/projectlogging?sort=name`

**Expected Result**
workload deploys

**Screenshots**

<img width="911" alt="2022-10-18_15-44-52" src="https://user-images.githubusercontent.com/89212856/196533871-1b870df9-eab3-4f9b-92e2-5de98151e6fd.png">

<img width="1231" alt="2022-10-18_15-46-20" src="https://user-images.githubusercontent.com/89212856/196533921-a2f5cd0b-a492-48bc-869d-e44f04789ce8.png">

**Comment by aiyengar2** [comment]
Probably related to https://github.com/rancher/rancher/pull/39189

**Comment by prachidamle** [comment]
Yes it seems like the v1 Logging removal has removed the CRDs related to `projectlogging` and `clusterlogging`.

We need to check if UI is making an API call that gets the error since backend/API schema is now removed and deprecated

**Comment by nwmac** [comment]
https://github.com/rancher/dashboard/issues/7300 will address this

**Comment by ronhorton** [comment]
**Pass** Verified in `2.7.0-rc9`

tested in https://github.com/rancher/dashboard/issues/7300
