### ISSUE TITLE
Should not be able to create Machine with same name

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3936]
Version - 0.63.0-rc3

Steps to Reproduce: 
1.  create a machine driver
2.  Create another one with same name

Results: Lets you create two with same name

Expected: Should not be able to have two with same name?

**Comment by wlan0** [comment]
Tested with rancher/server (Image Id: fd6c71b4f71e). Uniqueness constraint on machine driver exists. Could not reproduce issue.

**Comment by deniseschannon** [comment]
@tfiduccia Could you re-test with latest?

**Comment by tfiduccia** [comment]
Version - The UI still allows me to create another machine driver with the same "Name".
![image](https://cloud.githubusercontent.com/assets/11514927/13795482/4bf5969c-eabe-11e5-8b2a-5cf55f41be59.png)
