### ISSUE TITLE
[Feature]  k8s 1.25 Support - RBAC 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#39365]
This is derived from https://github.com/rancher/rancher/issues/38701

The following table describes the permissions for each role. 
We would like to match the behavior as close as to what we have for PSP today.
This is not the final vesion.  

 . | Configure the Admission Controller ( edit cluster) | Configure Pod Security Standard at the Project level | Configure Pod Security Standard at the Namespace level 
--- | --- | --- | --- 
Admin                     | Yes | Yes | Yes  
Restricted Admin  | Yes | Yes | Yes   
Cluster Owner       | Yes | Yes | Yes      
Cluster Member    | No  | No | No
Project Owner       | No  | No | No
Project Member    | No  | No | No
Project Read Only | No | No | No

**Comment by cbron** [comment]
* Cluster Member is a permission-less role until they make a project/namespace, so that should be no across the board. 
* Project owner can be yes for 2nd two columns

**Comment by anupama2501** [comment]
Re opening rancher version `v2.7-head 8062f1e`
Downstream webhook version `rancher/rancher-webhook:v0.3.2-rc7`
As a cluster member, project owner, project member I'm able to create a namespace by enabling the Pod Security Admissions.

Steps to repro:
1. Install rancher on v2.7 -head
2. Create a downstream RKE1 node driver 1 node all roles
3. As an admin create 3 users as a standard user 
4. Add the users as cluster members, project owners and cluster owners
5. Login as a cluster member and create a namespace from the Pod security Admission tab on the namespace try to enable 
    
    -  audit
    - enforce
    - warn
6. Can create namespace without any errors.

**Comment by crobby** [comment]
It looks like https://github.com/rancher/webhook/pull/165 caused the downstream webhook to break.  I've contacted @jiaqiluo about a potential fix.  Hopefully, this will be addressed quickly.

**Comment by jiaqiluo** [comment]
can be validated in the latest v2.7-head with webhook version  v0.3.2-rc9

**Comment by anupama2501** [comment]
Validated following test cases on v2.7-head `487df16`, rancher-webhook on the downstream `rancher/rancher-webhook:v0.3.2-rc9`
1. Created an rke1 node driver cluster - 1 node all roles
2. Created 4 standard users with roles - Cluster member, cluster owner, project member, project owner and a restricted admin.

 .  | Add PSA labels at Namespace level | Status
--- | --- | -- |
Admin                    | Yes | Pass
Restricted Admin  | Yes   | Pass
Cluster Owner        | Yes   | Pass
Cluster Member        | No  | Pass
Project Owner        | No  | Pass
Project Member        | No  | Pass


 .  | Edit PSA labels at Namespace level | Status
--- | --- | -- |
Admin                    | Yes | Pass
Restricted Admin  | Yes   | Pass
Cluster Owner        | Yes   | Pass
Cluster Member        | No  | Pass
Project Owner        | No  | Pass
Project Member        | No  | Pass

**Comment by anupama2501** [comment]
Re opening as the cluster members/project owners/ project members should not be able to delete the namespaces:


 .  | Delete PSA labels at Namespace level | Status
--- | --- | -- |
Admin                    | Yes  | Pass
Restricted Admin  | Yes   | Pass
Cluster Owner        | Yes   | Pass
Cluster Member        | Yes  | Fail
Project Owner        | Yes   | Fail
Project Member        | Yes   | Fail

**Comment by crobby** [comment]
Good catch.  I believe I see the problem, should have this fixed soon.

**Comment by crobby** [comment]
Fixed by:  https://github.com/rancher/webhook/pull/179
Rancher charts have been updated and this fix is available in rancher-head

**Comment by anupama2501** [comment]
Verified the following test cases on v2.7-head 9278cf1, webhook version `v0.3.2-rc11` at namespace level
validated all the usecases from here work as expected https://github.com/rancher/rancher/issues/39365#issuecomment-1381101405

Also validated the following cases:
**Case1:**
Standard users - cluster member, project owner and project member should be able to update the psa labels with additional cluster role that has the verb `updatepsa` as shown below:
```
apiVersion: management.cattle.io/v3
builtin: false
context: cluster
description: ''
external: false
hidden: false
kind: RoleTemplate
metadata:
  name: updatepsa
rules:
  - apiGroups:
      - management.cattle.io
    resources:
      - projects
    verbs:
      - updatepsa
```

1. Create a cluster template with the above yaml
2. Create 3 standard users - user1, user2, user3, user4
3. Add user1 as cluster member, user2 as project owner and user3 as project member
4. Verify none of the users have access to update the psa labels.
5. Add the custom role with just the verb `updatepsa` at cluster level to each of the users
6. Verified user1, user2 and user3 can edit the psa namespace permissions

**Case2:**
User with custom create namespaces and the cluster permission `updatepsa` can edit the psa labels

1. Add a standard user, user4 with the custom project permission `Create namespaces`  and custom cluster `updatepsa` permission.
2. Verify user4 can edit the namespace
3. Remove the cluster role `updatepsa` permissions and verified user4 cannot edit the PSA labels

**Case3:** 
Upgrade rancher server and verify previously added cluster members can edit the psa labels pre rancher upgrade and cannot edit the labels post rancher upgrade.
1. Create a downstream cluster with psa enabled at namespace level
2. Create 3 standard users - user1, user2, user3, user4
3. Add user1 as cluster member, user2 as project owner and user3 as project member
4. Verify all of the users have access to update the psa labels.
5. Upgrade rancher server and verify webhook gets installed on the downstream clusters. 
6. Verified user1, user2 and user3 cannot edit the psa namespace permissions post rancher upgrade.
7. Add the custom role with just the verb `updatepsa` at cluster level to each of the users
8. Verified users can update the psa labels.

**Comment by anupama2501** [comment]
rbac at cluster level test cases will be validated by @markusewalker as part of this [issue](https://github.com/rancher/rancher/issues/38701)

**Comment by markusewalker** [comment]
Validated on `v2.7-head` https://github.com/rancher/rancher/commit/1032039db9cf803c582b3a860df7fae6f85b9d63 the following RBAC at the cluster level:

RBAC cluster level - enable PSA
|Role|Expected Result|Actual Result|Status|
|---|---|---|---|
|Admin|Yes|Yes|:white_check_mark:|
|Restricted Admin|Yes|Yes|:white_check_mark:|	
|Cluster owner|Yes|Yes|:white_check_mark:|	
|Cluster member|No|No|:white_check_mark:|	
Project Owner|No|No|:white_check_mark:|
Project member|No|No|:white_check_mark:|	
Read only|No|No|:white_check_mark:|
Custom permissions|No|No|:white_check_mark:|

**Comment by anupama2501** [comment]
Closing the issue as required RBAC validations at cluster level and namespace level have been validated.
