### ISSUE TITLE
[BUG] - UI doesn't show Monitoring v1 (legacy) versions to install on 2.7.0-rc4

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#39363]
**Rancher Server Setup**
- Rancher version: `v2.7.0-rc4`
- Installation option: Helm HA Airgap but also on non-Airgap
   - If Helm Chart, Kubernetes Cluster and version: RKE1 k8s 1.24
- Proxy/Cert Details: byo-valid

**Information about the Cluster**
- Kubernetes version: 1.23 and 1.24
- Cluster Type: Downstream
   - If downstream, what type of cluster?: Custom RKE1

**User Information**
- What is the role of the user logged in? Admin
  - If custom, define the set of permissions: none

**Describe the bug**

Navigating to Cluster Tools clicking on Monitoring (Legacy) Install button takes us to the settings page, but there's no way to select a version using the Dropdown

Clicking Enable throws an error

**To Reproduce**

- Install a Rancher 2.7.0-rc
- Create a RKE1 downstream cluster
- Navigate to Cluster Tools, click install on Monitoring (Legacy)
- In the install options check the version dropdown
- Or click Save directly

**Result**

Dropdown empty:
<img width="549" alt="Screen Shot 2022-10-19 at 2 36 08 PM" src="https://user-images.githubusercontent.com/27659/196815086-2b7dc6e0-3298-4291-a44c-9f1ec7e04b49.png">

Clicking Enable:

```
This cluster is currently Error.
Template system-library-rancher-monitoring incompatible with rancher version or cluster's [c-q2vrn] kubernetes version
```

**Expected Result**
Version Dropdown shows a version
Enabling monitoring v1 (legacy) installs monitoring

**Comment by ronhorton** [comment]
additional context: we have to support upgrades of existing 1.21 clusters so that monitoring v1 continues to operate.

**Comment by MKlimuszka** [comment]
This is "as designed." The error is accurate.
