### ISSUE TITLE
[BUG] Users are unable to create RKE2 vSphere Node Driver clusters with more than 1 Windows worker node

### ISSUE THREAD

**Issue by jameson-mcghee** [rancher/rancher#39362]
**Rancher Server Setup**
- Rancher version: v2.6.5 and v2.6.8
- Installation option (Docker install/Helm Chart): Docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): N/A
- Proxy/Cert Details: N/A

**Information about the Cluster**
- Kubernetes version: v1.24.6+rke2r1
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Node Driver (Infrastructure Provider)

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): Standard User with Cluster Owner Role
  - If custom, define the set of permissions: N/A

**Describe the bug**
When attempting to create a vSphere Node Driver cluster with more than one Windows worker node or when attempting to scale up a second Windows worker node on an existing cluster, only the first Windows worker node will provision successfully.

**To Reproduce**
_Scenario 1:_
1. On a vSphere Hosted instance of Rancher, attempt to create a vSphere Node Driver cluster with 3 Linux ETCD nodes, 2 Linux Control Plane Nodes, 2 Linux Worker Nodes, and 2 Windows worker nodes

_Scenarios 2:_
1. On a vSphere Hosted instance of Rancher, create a vSphere Node Driver cluster with 3 Linux ETCD nodes, 2 Linux Control Plane Nodes, 2 Linux Worker Nodes, and 1 Windows worker node
2. Once the cluster becomes active, attempt to Scale up a Second Windows worker node

_Scenario 3:_
1. On a vSphere Hosted instance of Rancher, attempt to create a vSphere Node Driver cluster with 3 Linux ETCD nodes, 2 Linux Control Plane Nodes, 2 Linux Worker Nodes, 1 Windows worker node, and 1 Windows worker node (separate node pool) with the same OS Template as the first. 

_Scenario 4:_
1. On a vSphere Hosted instance of Rancher, attempt to create a vSphere Node Driver cluster with 3 Linux ETCD nodes, 2 Linux Control Plane Nodes, 2 Linux Worker Nodes, 1 Windows worker node, and 1 Windows worker node (separate node pool) with a different Windows OS Template/Version from the first.

**Result**
The first 3 scenarios result in the first Windows worker node being Active, but the second (and any subsequent ones after that) being stuck in a Reconciling state. However, in the 4th scenario, all Windows nodes will become active.

**Expected Result**
Users are able to provision vSphere Node Driver clusters with multiple Windows worker nodes without issue.

**Screenshots**
Windows 2022 Template:
![image](https://user-images.githubusercontent.com/13294321/196779782-c665bb15-7179-4ba1-a918-2d6c1df1c85d.png)
![image](https://user-images.githubusercontent.com/13294321/196779825-9ab649f3-b832-483f-934c-a236e9b4bc84.png)
![image](https://user-images.githubusercontent.com/13294321/196779847-a2edbdde-70a7-406a-9ccd-954aaada8d76.png)
![image](https://user-images.githubusercontent.com/13294321/196779882-58613da3-5411-4dd6-bd63-f572da047bb2.png)

Windows 2019 Template:
![image](https://user-images.githubusercontent.com/13294321/196779965-d30b7bce-36da-487a-8c25-ebd832cc29bc.png)
![image](https://user-images.githubusercontent.com/13294321/196779979-6d6db723-9127-4c31-8e1c-1f3d8f618d1b.png)

**Additional context**
This issue will reproduce for all supported versions of the Windows Operating System.
It was observed during testing that the Node Name, Hostname, and DNS of the Windows worker nodes are the same for every node every time dependent upon the OS Template being used (refer to the Screenshots). We were unable to confirm during testing, but it is our understanding that all of the Windows Templates in our setup have been properly Sysprepped/Generalized during their creation (though we were not able to confirm if this is true about the User that initially reported this issue).

SURE-5319

**Comment by jakefhyde** [comment]
Moved back into working to investigate an issue where windows vms are rebooted.

**Comment by snasovich** [comment]
The issue mentioned above is now tracked separately as https://github.com/rancher/rancher/issues/39658, moving this one back to test.

**Comment by jameson-mcghee** [comment]
During testing on `v2.6.5`, I observed the `set_hostname` error in the Cloudbase-Init logs for the Windows Nodes. However, during testing on `v2.7-head` (Commit ID: ae44c39), I no longer observed the error in the logs, and I was able to successfully provision vSphere RKE2 clusters with multiple Windows nodes following each of the previously failing Scenarios in the Description's[ Steps to Reproduce](https://github.com/rancher/rancher/issues/39362#issue-1415480166). Therefore I am closing this ticket.

**`v2.6.5`:**
[CloudBase-Init Logs v265.txt](https://github.com/rancher/rancher/files/10230799/CloudBase-Init.Logs.v265.txt)

**`v2.7-head` (Commit ID: ae44c39):**
[CloudBase-Init Logs v27head.txt](https://github.com/rancher/rancher/files/10230806/CloudBase-Init.Logs.v27head.txt)
![image](https://user-images.githubusercontent.com/13294321/207687853-f6266f2c-fb20-49cf-a5f6-7af0b3e59028.png)
