### ISSUE TITLE
[Feature] k8s 1.25 Support - Apps

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#39366]
This is derived from https://github.com/rancher/rancher/issues/38701

[Pod Security Policy](https://kubernetes.io/docs/concepts/security/pod-security-policy/) is currently used in the following charts, and we need to update them to use [Pod Security Standards](https://kubernetes.io/docs/tasks/configure-pod-container/enforce-standards-namespace-labels/) 
 

- [x] Rancher: https://github.com/rancher/rancher/blob/release/v2.6/chart/templates/post-delete-hook-psp.yaml
- [x] Longhorn: https://github.com/rancher/charts/blob/dev-v2.6/charts/longhorn/100.2.0%2Bup1.3.0/templates/psp.yaml
- [x] Neuvector: https://github.com/rancher/charts/blob/dev-v2.6/charts/neuvector/100.0.0%2Bup2.2.0/templates/psp.yaml
- [x] Rancher-alerting-drivers: https://github.com/rancher/charts/blob/dev-v2.6/charts/rancher-alerting-drivers/100.0.3/templates/hardened.yaml
- [x] Rancher-backup: https://github.com/rancher/charts/blob/dev-v2.6/charts/rancher-backup/2.1.3-rc5/templates/psp.yaml
- [x] Rancher-gatekeeper: https://github.com/rancher/charts/blob/dev-v2.6/charts/rancher-gatekeeper/100.2.0%2Bup3.8.1/templates/gatekeeper-admin-podsecuritypolicy.yaml
- [x] Rancher-istio: https://github.com/rancher/charts/blob/dev-v2.6/charts/rancher-istio/100.4.0%2Bup1.14.1/templates/istio-psp.yaml
- [x] Rancher-kiali: https://github.com/rancher/charts/blob/dev-v2.6/charts/rancher-kiali-server/1.41.0/templates/psp.yaml
- [x] Rancher-logging: https://github.com/rancher/charts/blob/dev-v2.6/charts/rancher-logging/100.1.3%2Bup3.17.7/templates/psp.yaml
- [x] Rancher-monitoring: https://github.com/rancher/charts/tree/dev-v2.6/charts/rancher-monitoring/100.1.3%2Bup19.0.3
- [x] Rancher-project-monitoring: https://github.com/rancher/charts/tree/dev-v2.6/charts/rancher-project-monitoring/0.1.0
- [x] Rancher-traching: https://github.com/rancher/charts/blob/dev-v2.6/charts/rancher-tracing/100.0.0/templates/psp.yaml
- [x] Rancher-webhook: https://github.com/rancher/charts/blob/dev-v2.6/charts/rancher-webhook/1.0.5%2Bup0.2.6-rc9/templates/pre-delete-hook-psp.yaml

**Comment by stormqueen1990** [comment]
rancher-gatekeeper PR:
* rancher/charts#2221

**Comment by prachidamle** [comment]
This can be moved to-test; after re-design the new PSP related changes are tracked here: https://github.com/rancher/rancher/issues/40331

**Comment by ronhorton** [comment]
**Pass** verified in `v2.7.2-rc5`
