### ISSUE TITLE
Exclude internal rancher 'io.rancher.service.hash' label from exported config yml files

### ISSUE THREAD

**Issue by prachidamle** [rancher/rancher#3937]
On config export we should skip the label `io.rancher.service.hash`.  rancher-compose uses this for internal tracking and this should not be added to the compose files exported by cattle

**Comment by sangeethah** [comment]
Tested with latest build from master - Mar/16

Create a stack by providing docker-compose and rancher-compose.

Once the services are activated , use "view config" option to see the generated config files.

There is no io.rancher.service.hash in lables (in docker-compose.yml). But still see it in the metadata section for the services (in rancher-compose.yml). 

<img width="1093" alt="screen shot 2016-03-16 at 10 34 08 am" src="https://cloud.githubusercontent.com/assets/4266958/13822441/dea235e6-eb62-11e5-9165-976b756abb90.png">

**Comment by sangeethah** [comment]
@prachidamle , Reopening this issue to see if the expected behavior is for io.rancher.service.hash to be excluded from metadata as well.

**Comment by prachidamle** [comment]
@ibuildthecloud should I exclude the 'io.rancher.service.hash' label also from the metadata in rancher-compose.yml  ?

**Comment by sangeethah** [comment]
Tested with latest build from master:
There is no io.rancher.service.hash in lables (in docker-compose.yml) and in metadata section for the services (in rancher-compose.yml).
