### ISSUE TITLE
[BUG] loglevel trace are not set inside rke2 rancher-machine job

### ISSUE THREAD

**Issue by tuxtof** [rancher/rancher#39377]
**Rancher Server Setup**
- Rancher version: v2.6.8
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): k3s version v1.22.7+k3s1 (8432d7f2)

- Proxy/Cert Details: none

**Describe the bug**

when i set loglevel to trace in rancher , rke2 rancher-machine deployment job don't provide trace level

**To Reproduce**

set loglevel to trace
deploy a rke2 cluster

**Result**

check rke2 rancher-machine deployment pod and you will see no trace 

**Expected Result**

see trace level for rancher-machine logs

**Comment by snasovich** [comment]
Moving back to "Working" to potentially address https://github.com/rancher/rancher/pull/39375#issuecomment-1351688797
