### ISSUE TITLE
rancher-monitoring prometheus not returning container memory usage

### ISSUE THREAD

**Issue by harsh61426** [rancher/rancher#39396]
The container_memory_working_set_bytes is returning the memory corresponding to the pod and not for each container in the pod. Using container!=POD and container!="" as filters to the container_memory_working_set_bytes() is returning empty array.

How do I get the container level metrics instead of pod level metrics?

**Comment by BBQigniter** [comment]
duplicate to https://github.com/rancher/rancher/issues/39185
