### ISSUE TITLE
Delete then Restore leaves Volume in inactive state

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#394]
v0.13.1
Steps:
1.  Remove container associated to Volume
2.  Delete Volume
3.  Restore Volume

Results:  Volume is now in a inactive state with no way to reactivate.

Expected:  I should be able to reactivate it or it should not allow me to get into that state.

**Comment by cjellick** [comment]
Manually activating a volume is not allowed. A volume becomes active when it is mounted to a container. So, when you follow this up by creating a new container that referenced the same volume name and driver, the volume becomes active again.

**Comment by tfiduccia** [comment]
Version - master 4/1
Verified works as designed
