### ISSUE TITLE
[BUG] Istio - upgrade to lastest version paths all lead to a blank page - can't upgrade via UI

### ISSUE THREAD

**Issue by ronhorton** [rancher/rancher#39409]
**Rancher Server Setup**
- Rancher version: v2.7.0-rc4
- Installation option (Docker install/Helm Chart): `HELM`
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1
- Proxy/Cert Details: 

**Information about the Cluster**
- Kubernetes version: `v1.24.4`
- Cluster Type (Local/Downstream): downstream ec2 ubuntu rke1 cluster 
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: `admin`

**Describe the bug**
when attempting to upgrade an existing installation of istio, all the possible paths to upgrade lead to a blank page; also verified with clean cache
1. clicking verison tag on installed apps page
2. clicking 3 dots > edit/upgrade on installed apps page
3. clicking istio tile on Charts page
4. clicking 3 dots on installed app detail page > edit/upgrade

**To Reproduce**

click install paths listed in description
**Result**
blank page due to 500 error on a userpreferences PUT https://hostname/v1/userpreferences/user-xxxxx
**Expected Result**

upgrade screen
**Screenshots**

**Additional context**

**Comment by prachidamle** [comment]
@ronhorton The bug mentions "when attempting to upgrade an existing installation of istio" - on which rancher version was Istio installed and what was Istio's version?

**Comment by ronhorton** [comment]
- Istio 100.4.0+up1.14.1 was installed on 2.6.9.
- Rancher was upgraded to 2.7.0-rc4
- Istio has an upgrade available: 101.0.0+up1.14.3 
- The upgrade failure is when attempting to upgrade istio to the latest verison

**Comment by doflamingo721** [comment]
@ronhorton @prachidamle This issue was specific to `2.7.0-rc4` and was not active on `2.7.0-rc7`. This issue is similar to https://github.com/rancher/rancher/issues/39354 where chart upgrade path leads to a blank page. This was resolved in the later RC version. Moving this ticket to Test bucket.

**Comment by nickwsuse** [comment]
`Verified on v2.7.0-rc9`

All of the upgrade paths are working as expected. Even did an upgrade from v2.6.9 to v2.7.0-rc9 to ensure that going from an older version of the plugin to a newer version works.
