### ISSUE TITLE
[BUG]OPA Gatekeeper - error in logs 'unable to process a request with an unknown content type

### ISSUE THREAD

**Issue by ronhorton** [rancher/rancher#39408]
**Rancher Server Setup**
- Rancher version: `2.7-head commit id 9e7e4bc `
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): HELM
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: `v1.24.6`
- Cluster Type (Local/Downstream): `downstream` AWS k3s 
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:
`admin`

**Describe the bug**

checking logs for errors, located this error in gatekeeper-controller-manager 

http: TLS handshake error from ip-address:42306: EOF
--
Tue, Oct 25 2022 5:03:35 pm | {"level":"error","ts":1666731815.459482,"logger":"controller-runtime.webhook.webhooks","msg":"unable to process a request with an unknown content type","webhook":"/v1/admitlabel","content type":"","error":"contentType=, expected application/json","stacktrace":"github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerInFlight.func1\n\t/go/src/github.com/open-policy-agent/gatekeeper/vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go:40\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2084\ngithub.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1\n\t/go/src/github.com/open-policy-agent/gatekeeper/vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go:117\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2084\ngithub.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerDuration.func2\n\t/go/src/github.com/open-policy-agent/gatekeeper/vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go:84\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2084\nnet/http.(*ServeMux).ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2462\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2916\nnet/http.initALPNRequest.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:3523\nnet/http.(*http2serverConn).runHandler\n\t/usr/local/go/src/net/http/h2_bundle.go:5903"

**To Reproduce**
1. install 101.0.0+up3.9.0
2. create label constraint to require owner label
3. attempt to create namespace without label
4. add label and create namespace
5. open gatekeeper-controller-manager and grep logs for error

**Result**
error - no deployments show errors in the ui
**Expected Result**

no error
**Screenshots**

**Additional context**

**Comment by doflamingo721** [comment]
The error seen in one of the controller pods does seem to affect the gatekeeper functionality. The Gatekeeper workflow is working as expected. As per the offline discussion with @ronhorton, moving this ticket to test bucket.

**Comment by ronhorton** [comment]
cannot reproduce in `2.7.0-rc7`
as mentioned in previous comment, there's no apparent effect on gatekeeper functionality. closing for now, but will monitor for error in further testing.
