### ISSUE TITLE
[BUG] Steve does not pass through the warning HTTP response header for Pod creation requests

### ISSUE THREAD

**Issue by nwmac** [rancher/rancher#39413]
To support PSAs in the UI, we want to be able to show the warnings when a pod is created that violates a policy (when the policy is set to `warn`). The warning in the case is returned in the HTTP response `Warning` header.

e.g. using kubectl:

```
I1026 10:17:33.559293   68477 request.go:1154] Request Body: {"apiVersion":"v1","kind":"Pod","metadata":{"name":"nginx","namespace":"test"},"spec":{"containers":[{"image":"nginx","name":"nginx","ports":[{"containerPort":80}]}]}}
I1026 10:17:33.559567   68477 round_trippers.go:463] POST https://127.0.0.1:42239/api/v1/namespaces/test/pods?fieldManager=kubectl-create&fieldValidation=Strict
I1026 10:17:33.559595   68477 round_trippers.go:469] Request Headers:
I1026 10:17:33.559610   68477 round_trippers.go:473]     Accept: application/json
I1026 10:17:33.559694   68477 round_trippers.go:473]     Content-Type: application/json
I1026 10:17:33.559715   68477 round_trippers.go:473]     User-Agent: kubectl/v1.25.3 (linux/amd64) kubernetes/434bfd8
I1026 10:17:33.569440   68477 round_trippers.go:574] Response Status: 201 Created in 9 milliseconds
I1026 10:17:33.569608   68477 round_trippers.go:577] Response Headers:
I1026 10:17:33.569812   68477 round_trippers.go:580]     X-Kubernetes-Pf-Prioritylevel-Uid: 44a18f9b-30fb-4b1e-903a-2aeaf0766cf2
I1026 10:17:33.569897   68477 round_trippers.go:580]     Content-Length: 2064
I1026 10:17:33.569968   68477 round_trippers.go:580]     Date: Wed, 26 Oct 2022 10:17:33 GMT
I1026 10:17:33.570032   68477 round_trippers.go:580]     Audit-Id: 5df0e610-a410-46c2-87bf-4138f4ff5699
I1026 10:17:33.570100   68477 round_trippers.go:580]     Cache-Control: no-cache, private
I1026 10:17:33.570145   68477 round_trippers.go:580]     Content-Type: application/json
I1026 10:17:33.570266   68477 round_trippers.go:580]     Warning: 299 - "would violate PodSecurity \"restricted:latest\": allowPrivilegeEscalation != false (container \"nginx\" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container \"nginx\" must set securityContext.capabilities.drop=[\"ALL\"]), runAsNonRoot != true (pod or container \"nginx\" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container \"nginx\" must set securityContext.seccompProfile.type to \"RuntimeDefault\" or \"Localhost\")"
I1026 10:17:33.570332   68477 round_trippers.go:580]     X-Kubernetes-Pf-Flowschema-Uid: 1169dc7f-5866-4db7-bbb2-83411fb968a1
I1026 10:17:33.570641   68477 request.go:1154] Response Body: {"kind":"Pod","apiVersion":"v1","metadata":{"name":"nginx","namespace":"test","uid":"4bdacd71-2a1f-4a34-90c6-51bba51fde33","resourceVersion":"23369","creationTimestamp":"2022-10-26T10:17:33Z","managedFields":[{"manager":"kubectl-create","operation":"Update","apiVersion":"v1","time":"2022-10-26T10:17:33Z","fieldsType":"FieldsV1","fieldsV1":{"f:spec":{"f:containers":{"k:{\"name\":\"nginx\"}":{".":{},"f:image":{},"f:imagePullPolicy":{},"f:name":{},"f:ports":{".":{},"k:{\"containerPort\":80,\"protocol\":\"TCP\"}":{".":{},"f:containerPort":{},"f:protocol":{}}},"f:resources":{},"f:terminationMessagePath":{},"f:terminationMessagePolicy":{}}},"f:dnsPolicy":{},"f:enableServiceLinks":{},"f:restartPolicy":{},"f:schedulerName":{},"f:securityContext":{},"f:terminationGracePeriodSeconds":{}}}}]},"spec":{"volumes":[{"name":"kube-api-access-4kqfk","projected":{"sources":[{"serviceAccountToken":{"expirationSeconds":3607,"path":"token"}},{"configMap":{"name":"kube-root-ca.crt","items":[{"key":"ca.crt","path":"ca.crt"}]}},{"dow [truncated 1040 chars]
Warning: would violate PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "nginx" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "nginx" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "nginx" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "nginx" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
```

When we use the Steve API to create a pod by POSTing to `/v1/pods`, we do not get the warning header returned in the response.

The warning header needs to be passed through the Steve requests.

**Comment by Jono-SUSE-Rancher** [comment]
@samjustus - Sending this your way for Neo to look at.

**Comment by nwmac** [comment]
@samjustus why does this need a PRD?

**Comment by samjustus** [comment]
@nwmac 

@cbron would like to see Will's PRD so we know all the moving parts related to PSAs

**Comment by nwmac** [comment]
@samjustus I don't think this is specific to PSAs - but we will need this to show warnings when the PSA to warn and there is a violation.

**Comment by crobby** [comment]
Small update, mostly for my own rubber ducking...

In our client that makes the call to k8s, we currently don't set any WarningHandler, which leads us to just ignore warnings that come back on calls that we make.  We may have the option to create our own WarningHandler and maybe somehow include that warning in our response, but I've yet to find a way to make that happen.  So far, I've only managed to get the warning sent to stderr/out as a log entry, but that's obviously not useful for this scenario.  

The WarningHandler interface, which seems to be the prescribed way to go about this doesn't seem to fit what we're looking to do here.
```
// WarningHandler is an interface for handling warning headers
type WarningHandler interface {
	// HandleWarningHeader is called with the warn code, agent, and text when a warning header is countered.
	HandleWarningHeader(code int, agent string, text string)
}
```
The handler bit seems to get executed at the time the k8s api call returns and before our code has a chance to handle things.

So far, I have not found a place in our code where that header is available for us to grab and stick in our response.
I will consult @cmurphy

**Comment by crobby** [comment]
https://github.com/kubernetes/client-go/blob/master/dynamic/simple.go#L112 appears to be where the warning header is available, but it is left out of the response, which is only the table object in our case.  I'm not seeing any option available to get the k8s response headers out.  I suppose we could make our own version of this, but maybe there is a better way.

**Comment by crobby** [comment]
I've posed a question to the client-go gh:  https://github.com/kubernetes/client-go/issues/1185

**Comment by crobby** [comment]
Based on a kube slack conversation, it sounds like warninghandler is the only option if we want to stick with client-go built-in bits.  Unfortunately, I can't think of a way to make those handlers useful in our context.  If we do need to implement this, I think our remaining option would be to implement our own version of the dynamicResourceClient.
Any thoughts on this @cbron or @cmurphy

**Comment by crobby** [comment]
One last comment on this for now.  I suppose it would be possible for us to create our own one-off http Client/Request and submit those requests "manually".  Seems a little awkward to forego all the upside of client-go for this case though.  Maybe there is another way to query for these "warning" situations.

**Comment by cmurphy** [comment]
Is there a change we could contribute to https://github.com/kubernetes/client-go/blob/master/dynamic/simple.go to let us use WarningHandler from dynamicResourceClient?

**Comment by crobby** [comment]
I'm not sure if a WarningHandler there would get us what we're looking to do..  Maybe some sort of change that would return more than just the resultant object, but we'd have to do it in a backwards-compatible way.  We should talk more about which options we might have here.  Maybe we can come up with something--sure seems like it would be a useful upstream contrib, but I suppose our use of client-go may be a bit different than most.

**Comment by crobby** [comment]
The returned APIObject now has a field "Warnings" where the warning headers, if any, will reside.

**Comment by crobby** [comment]
To test this via curl, you can do the following <adding in your own bearer_token where indicated):

```
#create namespace
kubectl create namespace testnamespace
#add the restricted label to that namespace
kubectl label --overwrite ns testnamespace pod-security.kubernetes.io/warn=restricted

curl -v -k '<rancher or steve>/v1/pods'   -H 'accept: application/json'   -H 'accept-language: en-US,en;q=0.9'   -H 'content-type: application/yaml'   -H 'cookie: R_PCS=light; R_LOCALE=en-us; R_REDIRECTED=true; R_SESS=<your bearer token>'   --data-raw $'apiVersion: v1\nkind: Pod\nmetadata:\n  name: nginx\n  namespace: testnamespace\nspec:\n  containers:\n    - image: nginx\n      name: nginx\n      ports:\n        - containerPort: 80\n'   --compressed
```
In the output, you should see a header that looks like the following
`< warning: 299 - would violate PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "nginx" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "nginx" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "nginx" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "nginx" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")`

You could also change the namespace label value to baseline or privileged.  For the nginx pod example, I don't think you'll see the warning header since that example doesn't violate either of those PSA levels.

**Comment by cnotv** [comment]
@crobby I am trying to generate a warning by creating/editing a Pod which has a Namespace with PSA Warning and any level combination, but I got no warning or mention anywhere. Any hint?

**Comment by crobby** [comment]
@cnotv Have you tried the example I gave below?

If you have, what do you get for `kubectl describe ns <yournamespace`

**Comment by cnotv** [comment]
Since I'm developing the UI I'll use that, mind you? 😄 
This is my scenario:

<img width="1912" alt="Screenshot 2023-01-12 at 16 21 05" src="https://user-images.githubusercontent.com/5009481/212107230-78916c92-2478-4491-aef2-652d64e20386.png">

<img width="1226" alt="Screenshot 2023-01-12 at 16 22 23" src="https://user-images.githubusercontent.com/5009481/212107262-2cc5d82a-3f3c-4bbb-8729-dbf8d6f03f7a.png">

**Comment by cnotv** [comment]
I get an error (wall) in that case, but not a warning.

![Screenshot 2023-01-12 at 16 42 35](https://user-images.githubusercontent.com/5009481/212112535-5d7856c1-a290-466e-ad37-67335de0d814.png)

**Comment by crobby** [comment]
When you first create the pod, add the port.  Not sure you can modify it on the fly.

**Comment by cnotv** [comment]
Now it let me create it, but still no warning, just like before.

![Screenshot 2023-01-12 at 16 58 04](https://user-images.githubusercontent.com/5009481/212116403-0493fe54-c738-4c8f-8515-30dfcbbf93df.png)

**Comment by crobby** [comment]
which version of Rancher are you testing with?

**Comment by cnotv** [comment]
It should be the latest one or around that.
[Rancher](https://github.com/rancher/rancher)	v2.7-8062f1e3ab7bff870dfab195ff699a308644168a-head

**Comment by dasarinaidu** [comment]
Dashboard Card: [https://github.com/rancher/dashboard/issues/7875](url)

**Comment by cnotv** [comment]
I'll create a new instance of Rancher, so we get it right for sure.

**Comment by cnotv** [comment]
As mentioned by @nwmac , using 'Privilege Escalation' to 'Yes' generates the issue.
Rancher has been installed from scratch due corruption in the last update, prior this test.

**Comment by dasarinaidu** [comment]
I have validated this issue on `v2.7-623addd2b1f055e7da84f74e130b7a92c4b2599e-head`

All the test cases were passed and closing this ticket.

**Below test cases were executed as part of the validations:** 

1. Validated with different user types : 
- Admin
- Standard
- Auth Provider (OpenLDAP)

2. Validated with different cluster types :
- Local
- RKE1
- RKE2
- EKS

3. Validated with different ranchers types :
- Docker
- HA

**Reproducible Steps:**

1. Login to rancher
2. Create a cluster
3. Create a Project
4. Create a Name Space
5. Add the restricted label to that namespace `kubectl label --overwrite ns testnamespace pod-security.kubernetes.io/warn=restricted`
6. Run this command 
`curl -v -k '<rancher or steve>/k8s/clusters/clustername/v1/pods'   -H 'accept: application/json'   -H 'accept-language: en-US,en;q=0.9'   -H 'content-type: application/yaml'   -H 'cookie: R_PCS=light; R_LOCALE=en-us; R_REDIRECTED=true; R_SESS=<your bearer token>'   --data-raw $'apiVersion: v1\nkind: Pod\nmetadata:\n  name: nginx\n  namespace: testnamespace\nspec:\n  containers:\n    - image: nginx\n      name: nginx\n      ports:\n        - containerPort: 80\n'   --compressed`
7. Check for the warning message

Warning message displayed as: 
`warning: 299 - would violate PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "nginx" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "nginx" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "nginx" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "nginx" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")`
