### ISSUE TITLE
How can I call  Rancher PUT/POST API via Java Application

### ISSUE THREAD

**Issue by heidongbianjie** [rancher/rancher#39412]
I'm trying to call rancher api  in my java application.Apis using Get method  works out fine.But when I am  using put/post method, it suggests that csrf token is invalid. I tried to put  "X-API-CSRF " in my request header with the value I copied from Rancher UI(via Chrome dev tools).But it just won't work.So I wonder what could possibly go wrong.
Here's my header.

 `
  HashMap<String, String> putHeaderMap = new HashMap<>(10);

        putHeaderMap.put("Authorization", "Bearer token-thssv:xcn5x7k5ff5zcrk5qkfmstmh64mzpztdmb8vp4r8gmscfg56p79kmd");
        putHeaderMap.put("Content-Type", "application/json");
        putHeaderMap.put("Accept", "application/json");
        putHeaderMap.put("X-API-CSRF", "b6f7ccf93d3cb61d2bb06db3cd3bbc58");
        put.headerMap(putHeaderMap, false);
        JSONObject jsonObject2 = JSON.parseObject(getString());
        put.form(jsonObject2);
`

Here's the response info.

`
{"baseType":"error","code":"InvalidCSRFToken","message":"Invalid CSRF token","status":422,"type":"error"}
`
I'm not a native english speaker.So forgive my any grammar mistakes.
Best regards.

**Comment by heidongbianjie** [comment]
I tried to pull the source code of rancher to search the response info and I could not find any matches.

**Comment by heidongbianjie** [comment]
I tried to delete the CSRF Cookie via Chrome's devTools and then I resent the request.And I got the same response like the one I got in my java application.Is this suggesting that the 'X-API-CSRF' I put in headers is useless or I didn't use it properly ? Then  I  tried to  modify the value of csrf cookie and resent the request.And it operates successfully which confuses me a  liitle bit.I thought if the value of the csrf token changed,the server should tell me the csrf token is invalid.

**Comment by junkiebev** [comment]
The CSRF token you used is only valid for your browser session, not other sessions.

**Comment by heidongbianjie** [comment]
> The CSRF token you used is only valid for your browser session, not other sessions.

Could you please suggest how can I  access the csrf token  which is valid for the session between my application and rancher?Thanks a lot.

**Comment by junkiebev** [comment]
Wireshark the request and dump your headers

I'd guess you are triggering a CSRF check because you're sending a User-Agent header that looks like a browser

Remove the User-Agent and the check should not be applied - you could also send `User-Agent: lmao` as a header

**Comment by heidongbianjie** [comment]
> Wireshark the request and dump your headers
> 
> I'd guess you are triggering a CSRF check because you're sending a User-Agent header that looks like a browser
> 
> Remove the User-Agent and the check should not be applied - you could also send `User-Agent: lmao` as a header

You're right. I sent a http request and wiresharked it. And like you said, it carried the User-Agent header. I overrode it and it finally worked.
Thanks a lot.
