### ISSUE TITLE
Lost host connectivity between 2 of the host in a setup with 3 hosts.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#3941]
Fresh install of v0.59.1.

Had 3 hosts and connectivity between them were working as expected.
Created few services.

Upgraded to v0.63.0-rc3.

After sometime , Lost host connectivity between 2 of the host in a setup with 3 hosts.

3 hosts in the set up - sangee0591-10acre-1, sangee0591-10acre-2 and sangee0591-10acre-3

Connectivity between sangee0591-10acre-2 and sangee0591-10acre-3 is lost.

swanctl --list-sas  on sangee0591-10acre-3  shows connection to sangee0591-10acre-1 but not to sangee0591-10acre-2.

**Comment by ibuildthecloud** [comment]
This issue was due to a ipsec rekey collision.  The rekey times need to be adjusted to avoid this.

**Comment by philmes** [comment]
@ibuildthecloud I see you've fixed this in network agent 0.8.1. I've hit this bug, so is there anyway of upgrading to this version in Rancher, or do I need to wait for the next version? Or can I increase the number of hosts to circumvent it?

**Comment by ibuildthecloud** [comment]
@philmes You'll have to wait for the next RC (1.0.0-rc1, which will be in about 12 hours from now).  I've changed is such that when building a tunnel rekey will be initiated from one side only.  The rekey timeout is the default 4 hours for one side and the other will be set to 1 year.  This effectively means that only one side will initiate rekey.  https://github.com/rancher/cattle/pull/1526

**Comment by sangeethah** [comment]
Tested with rancher-server v1.0.0-rc1 and v1.0.0-rc2 . 
Have not encounter the issue with connectivity between hosts being lost.
