### ISSUE TITLE
With fresh install, ubiquity driver goes to error and can't be seen in Add host

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3942]
Version - 0.63.0-rc4

Steps to Reproduce: 
1.  Install rancher
2.  Go to Add Host (notice ubiquity is not there)
3.  Go to Setting

Results: Ubiquity is in Error, if I hit retry it goes to active and I'm able to see it in Add hosts.

Expected: Ubiquity should not be in Error.

**Comment by wlan0** [comment]
Tested with rancher/server (Image Id: fd6c71b4f71e). Could not reproduce.

**Comment by deniseschannon** [comment]
@tfiduccia Can you try and re-test?

**Comment by tfiduccia** [comment]
Version -  master 3/15
Verified fixed
