### ISSUE TITLE
[BUG] CIS hardened 1.23 scan failure 5.3.2 on hardened RKE1 v1.24.6

### ISSUE THREAD

**Issue by AndrewHoffmanQA** [rancher/rancher#39421]
**Rancher Server Setup**
- Rancher version: 2.7head 9e7e4bc
- Installation option (Docker install/Helm Chart): helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.24.6
- Cluster Type (Local/Downstream): downstream
- Hardened

**Describe the bug**
when running CIS scan 2.3 on downstream hardened RKE1 server k8 - v1.24.6 the scan returns with a single failure, 5.3.2 "Ensure that all Namespaces have Network Policies defined (Automated)"

**To Reproduce**
1. provision a hardened RKE1 server
2. install CIS scan 3.0.0-rc9
3. run scan "rke-profile-hardened-1.23"

**Result**
1 failure
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/DREWHO~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/DREWHO~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

id | description | remediation | state | node_type | audit | audit_config | test_info | commands | config_commands | expected_result | test_type | scored
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
5.3.2 | Ensure that all Namespaces have Network Policies defined (Automated) | Follow the documentation and   create NetworkPolicy objects as you need them. | fail | node | check_for_network_policies.sh | Follow the documentation and   create NetworkPolicy objects as you need them. |   |   | 'true' is present | TRUE

</body>

</html>

**Expected Result**
no failures are found

**Screenshots**
![image](https://user-images.githubusercontent.com/89030218/198134175-9ef1e7e8-0117-437d-a7c8-e102e67e0bdc.png)

![image](https://user-images.githubusercontent.com/89030218/198134285-ed0dbeb9-6302-482a-bfe7-e5b9c88100af.png)

**Additional context**

**Comment by AndrewHoffmanQA** [comment]
closing. this is no longer reproducible

**Comment by jiaqiluo** [comment]
For the record, the same error happens when using the cis benchmark v1.23 to evaluate a REK1 1.25.5 cluster.
