### ISSUE TITLE
[RFE] Enable possibility to set private DNS on AKS provisioning

### ISSUE THREAD

**Issue by mantis-toboggan-md** [rancher/rancher#39422]
Internal reference: SURE-3392

Request description:
Enable the possibility to set private DNS on AKS provisioning cluster. Currently, clusters are manually provisioned (or via Terraform) and skips the UI completely.

Actual behavior:
Currently, there is no setting in Rancher to set a private DNS for AKS cluster.

Expected behavior:
Add the possibility to set private DNS on AKS provisioning cluster.

Additional notes:
Based on one environment, the network infrastructure is more or less the same as the "hub and spoke" on the page: https://docs.microsoft.com/en-us/azure/aks/private-clusters#hub-and-spoke-with-custom-dns

Their DNS is centralized in the hub network, and they want to run AKS clusters in spoke networks.
To get it to work, they need to be able to point the AKS clusters to the central private DNS zone. Otherwise, the created AKS cluster's Kubernetes API endpoint address won't resolve, and the cluster will fail to provision, and the VMs can't resolve the Kubernetes API address.

Additional Azure documentation on how to set a custom private DNS zone: https://docs.microsoft.com/en-us/azure/aks/private-clusters#create-a-private-aks-cluster-with-a-custom-private-dns-zone

Usage: under clusters.tf, within the `resource` JSON, there'd be a `private_dns_zone_id` to leverage

 
 
This looks like something that will require both backend and UI changes; the ui ticket is [here](https://github.com/rancher/dashboard/issues/7163)

**Comment by kkaempf** [comment]
This is tracked in [aks-operator](https://github.com/rancher/aks-operator/issues/131)

**Comment by Jono-SUSE-Rancher** [comment]
Closing in favor of being tracked at https://github.com/rancher/aks-operator/issues/131
