### ISSUE TITLE
Obtaining metrics  file systems rancher-monitoring

### ISSUE THREAD

**Issue by pollynesterovich** [rancher/rancher#39425]
How can you get metrics for file systems with mounted access points? 
Temporary solution was https://github.com/prometheus/node_exporter/issues/1754 (- --path.rootfs=/host instead of the  --path.sysfs=/host/sys), but after updating rancher-monitoring the values set in the DaemonSet are overridden to the standard ones.
Can you add at https://github.com/rancher/charts/blob/release-v2.5/charts/rancher-monitoring/rancher-monitoring/9.4.203/charts/prometheus-node-exporter/templates/daemonset.yaml path.rootfs = / host , mountPath: /host, like https://github.com/rancher/system-charts/blob/dev-v2.5/charts/rancher-monitoring/v0.2.1/charts/exporter-node/templates/daemonset.yaml  or is there another solution please tell me?

**Comment by MKlimuszka** [comment]
XL because this requires a deep dive into node exporter. We also need a test plan.
