### ISSUE TITLE
not able to install rancher monitoring on AWS after upgrade EKS from 1.20 to 1.21

### ISSUE THREAD

**Issue by fdamoni** [rancher/rancher#39434]
Hi. I am not able to install rancher monitoring after upgrade from AWS EKS 1.20 to 1.21 . For the moment one job  rancher-monitoring-patch-sa is failing with permission issue.  The problem is found that after securtycontect the fsgroup:65534 in helm file is missing https://github.com/rancher/charts/blob/dev-v2.6/charts/rancher-monitoring/100.1.2%2Bup19.0.3/templates/rancher-monitoring/hardened.yaml and also could not be given as input parameter in helm values.yaml file https://github.com/rancher/charts/blob/dev-v2.6/charts/rancher-monitoring/100.1.2%2Bup19.0.3/values.yaml. 
I tested to add in the securityCotect fsGroup: 65534 and it is working. But for doing this I need to download charts edit the files and that install and actually I am not able to install rancher monitoring will api http. 
To resolve the problem, Could you please add as parameter values the fsGroup 65534 to hardened.yaml file?

**Comment by aiyengar2** [comment]
testing on the rebased setup in https://github.com/rancher/rancher/issues/37778

**Comment by MKlimuszka** [comment]
We may want to do this in the same PR as https://github.com/rancher/rancher/issues/39435
