### ISSUE TITLE
[BUG] Upgrade from non-community version -> community version of rancher does not reset branding / `ui-brand` persists after upgrade

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#39456]
**Rancher Server Setup**
- Rancher version: v2.7.0-rc6
- Installation option (Docker install/Helm Chart): docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):n/a
- Proxy/Cert Details:n/a

**Information about the Cluster**
- Kubernetes version: v1.24.4
- Cluster Type (Local/Downstream):local
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): n/a

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: tested with admin user (upgrade use case, must be admin to view settings)

**Describe the bug**

When upgrading from a non-community version of rancher to a community version, the upgrade is successful and the private registry details are reset. However, the non-community version's branding persists.

**To Reproduce**

* deploy a non-community version of rancher
  * ensure that non-community version's registry and branding are set 
* upgrade the setup to a community version of rancher
  * wait for the upgrade to complete

**Result**
the `ui-brand` setting persists after upgrade, and so we see non-community branding after the upgrade. 

**Expected Result**

the `ui-brand` should clear on an upgrade from a non-community version of rancher to a community version of rancher. 

**Screenshots**

**Additional context**

upgrading from a community-version to a non-community version of rancher does properly set the `ui-brand` and registry.

further investigation reveals that the `CATTLE_UI_BRAND` is not set after the upgrade, therefore this is likely a UI bug. Transferring to the UI repo.

**Comment by cbron** [comment]
Making some assumptions, @slickwarren please correct if they are not right: 

1. The upgrade steps here was just switching which chart is used, no other env vars or settings were manually changed. 
2. The non-community env var is `CATTLE_UI_BRAND="suse"`, and above comments seem to convey that the env var is gone, but the setting is there, and the setting is still set to "suse". No other custom ui-brand was set (if it was I imagine this would be fixed). 

So I think this is a known case where once you set the env var, it sticks, and removing the env var does not remove the setting. The `system-default-registry` should actually also still be set, @slickwarren can you confirm ?

**Comment by slickwarren** [comment]
confirmed (also had some offline discussion)

**Comment by crobby** [comment]
@rmweir Sounds like forcing and env var to == "community" may cause problems for the UI.  What about if we just force the value of the CATTLE_UI_BRAND env var to be == "" in the Dockerfile.  I'll test it out tomorrow, but unless there's something that is specifically ignoring empty strings, that might be a reasonable way to go.

**Comment by sowmyav27** [comment]
On `2.7.0-rc10`

- Deploy a non-community version of rancher
- ensure that non-community version's registry and branding are set
- upgrade the setup to a community version of rancher and wait for the upgrade to complete
- registry is unset and branding - ui-brand setting is also unset.

**Comment by slickwarren** [comment]
separately validated the same use cases above on 2.7.0-rc10 👍🏼
