### ISSUE TITLE
UI: Host view Status changed?

### ISSUE THREAD

**Issue by hwinkel** [rancher/rancher#3945]
Rancher Version: 0.63

Docker Version: n/a

OS: Chrome Version 48.0.2564.116 (64-bit)

Steps to Reproduce: show host view

Results: the formally GREEN or RED Indicators for ACTVE are just text now

Expected: is this expected behaviour and changed in 0.63? the Host State  in 0.59.1 was much more visible before

**Comment by vincent99** [comment]
Only the green style changed; it is de-emphasized (text color instead of background) so that the others will stand out, especially if you're color blind.  Try deactivating a host.

**Comment by deniseschannon** [comment]
<img width="354" alt="screen shot 2016-03-13 at 11 33 04 am" src="https://cloud.githubusercontent.com/assets/11410997/13730540/64e8f776-e90f-11e5-9dfe-cb38626137d7.png">

<img width="350" alt="screen shot 2016-03-13 at 11 33 10 am" src="https://cloud.githubusercontent.com/assets/11410997/13730541/67ba5ec2-e90f-11e5-81bc-14f37696e8bb.png">
