### ISSUE TITLE
Support Azure Availability Zones

### ISSUE THREAD

**Issue by HarrisonWAffel** [rancher/rancher#39458]
Request description:

Add Availability zone to Rancher Azure Node Driver.

Actual behavior:
Rancher node driver does not support Azur Availability zones

Expected behavior:
Rancher node driver support for Azur Availability zones

Additional notes:
Rancher Azure node driver and docker node driver support availability set but not availability zones.

While availability sets are used to protect applications from hardware failures within an Azure data center, Availability zones, protect applications from complete Azure data center failures.

 Docker Machine driver support option --azure-availability-set but has no option for availability zones. https://docs.docker.com/machine/drivers/

See also "Availability zones" description at: https://cloudacademy.com/course/getting-started-with-azure-virtual-machines-988/availability-sets-and-availability-zones/

SURE-3319

**Comment by HarrisonWAffel** [comment]
@gaktive This ticket is currently blocked by the respective UI work. rancher-machine has been updated so the required API schema changes should be present, resolving previous UI blockers. #39672 has also been raised to address some concerns from the UI team about VM feature support / available Availability zones

**Comment by thaneunsoo** [comment]
The test plan can be viewed [here](https://confluence.suse.com/pages/viewpage.action?pageId=1141178915)
