### ISSUE TITLE
Scale and Performance testing for 1.25 k8s clusters

### ISSUE THREAD

**Issue by markusewalker** [rancher/rancher#39469]
- Performance testing involved somewhere regarding large clusters to see how it performs.
     - PSA is replacing PSP officially, so we will need to see in the reports the difference, if any.

Specific use-cases include the following:
- Local and downstream 1.25 RKE1 and RKE2 clusters - individual cluster performance
- Large number of downstream RKE1/RKE2 Rancher provisioned clusters

**Comment by git-ival** [comment]
Scale and Performance checks were completed and documented internally
