### ISSUE TITLE
[BUG] The cluster specific registry is not internally synced between v3 & v1 which blocks fleet from using it

### ISSUE THREAD

**Issue by mattfarina** [rancher/rancher#39468]
**Rancher Server Setup**
- Rancher version: 2.7.0-rc7
- Installation option (Docker install/Helm Chart): Docker install
- Proxy/Cert Details: N/A

**Information about the Cluster**
- Kubernetes version: v1.24.6-rancher1-1 (RKE1)
- Cluster Type (Local/Downstream): doesn't matter
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  _Admin_

**Describe the bug**
Internally in Rancher, when RKE1 is managed it creates a v3 object. This in tern causes a v1 object to also be created. The v1 object doesn't get the registry synced to it. Some things, like the creation of the fleet.Cluster object, key off events to the v1 object. Those events are not properly handled when there is missing information.

You can see where the v1.Cluster is created/updated from a v3 object [here](https://github.com/rancher/rancher/blob/2ba49040cfcdd79fa34be91d010923390a5ac529/pkg/controllers/provisioningv2/cluster/controller.go#L176-L190).

When rke2 or k3s are handled it's first with a v1.Cluster that is synced to v3. You can see that information is synced to v3 with more detail (see [here](https://github.com/rancher/rancher/blob/2ba49040cfcdd79fa34be91d010923390a5ac529/pkg/controllers/provisioningv2/cluster/controller.go#L264)).

**To Reproduce**
An easy way to reproduce this is to create or import an RKE1 cluster while using a cluster specific registry. The fleet agent installed will not use that registry because the v1 object never got it.

**Result**
Fleet uses the global or default registry and not the cluster specific one. Fleet is just an example to easily highlight this. As information is not synced there could be other cases this causes an issue for.

**Expected Result**
Fleet should use the cluster specific registry. Again, fleet is just an example as this is a sync issue between resources and other things could have issues due to this.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Josh-Diamond** [comment]
Awaiting rancher `v2.7.0-rc9` to resume testing

**Comment by sowmyav27** [comment]
`v2.7.0-rc9` is available to test

**Comment by Josh-Diamond** [comment]
Ticket #39468 - Test Results
---

With HA Helm:

Verified on rancher `v2.7.0-rc9`:

| Downstream Cluster | K8s Version | Global Registry | Cluster Registry | System Images | Helm Operation Pod Image | Chart Images | Result |
|---|---|---|---|---|---|---|---|
| RKE1 AWS Node Driver | v1.24.6-rancher1-1 | Unauthenticated | Authenticated | Cluster Registry | Cluster Registry | Cluster Registry | **PASS** ✅  |
| RKE1 AWS Node Driver | v1.24.6-rancher1-1 | Unauthenticated | Unauthenticated | Cluster Registry | Cluster Registry | Cluster Registry | **PASS** ✅  |
| RKE1 AWS Node Driver | v1.24.6-rancher1-1 | Not Set | Unauthenticated | Cluster Registry | Cluster Registry | Cluster Registry | **PASS** ✅  |

**Additional Comments**:
- `fleet-agent` now respects cluster level registry with RKE1 and pulls image accurately and successfully from cluster level registry
