### ISSUE TITLE
RFE: Operations on multiple entities

### ISSUE THREAD

**Issue by hwinkel** [rancher/rancher#3947]
Rancher Version: 0.63

It would be great to habe operations for multiple selected entities from the UI. Like Selecting a number of container to Stop, delete and Purge them. Basically means to have a option to select a number of entities from a list and perform certain actions on it.

Having the action button and dropdown in the row of the entity does not really allow that from a UX perspective. Having such a button/dropdown on top like in the stack groupings could work, or we need global actions somehow on top of the given UI.

**Comment by vincent99** [comment]
Duplicate of #342
