### ISSUE TITLE
[BUG] non-community version of rancher does not have correct setting in `/rancherversion`

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#39474]
**Rancher Server Setup**
- Rancher version: v2.7.0-rc6
- Installation option (Docker install/Helm Chart): docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): n/a
- Proxy/Cert Details: n/a

**Information about the Cluster**
- Kubernetes version: any
- Cluster Type (Local/Downstream): local 
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): n/a

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: admin

**Describe the bug**

when viewing `/rancherversion` in a non-community version of rancher, the version is still set as the community version. 

**To Reproduce**

* deploy a non-community version of rancher
* view /rancherversion

**Result**
the non-community setting is still set to false

**Expected Result**

on non-community versions of rancher, the non-community version should be set to true

**Screenshots**

**Additional context**

https://github.com/rancher/dashboard/issues/6665#issuecomment-1295792025

**Comment by jiaqiluo** [comment]
can be validated in non-community version v2.7.0-rc8

**Comment by slickwarren** [comment]
tested on v2.7.0-rc8: 
* check /rancherversion on non-community version (now set to true) -- pass
* check /rancherversion on community version (should set to false) -- pass
