### ISSUE TITLE
rancher/server crashes due to database timeout error due to long migration process

### ISSUE THREAD

**Issue by xaka** [rancher/rancher#3949]
Rancher Version: 0.63

Docker Version: 1.9.1

OS: Ubuntu 14.04

-

Table `process_execution` has only 5000 rows, but as those contain Java exceptions (a lot data to move during altering process) and database server isn't that fast (i allocated small chunk of CPU/RAM), it takes up to 3 minutes to finish `ALTER TABLE process_execution ADD created datetime NULL`. rancher/server doesn't wait long enough for `ALTER TABLE` to finish and so process crashes.

**Comment by teon** [comment]
+1

**Comment by teon** [comment]
Although I have a very fast cpu and a lot of ram, but still after few minutes there's an exception

**Comment by xaka** [comment]
Robert,

There is bigger issue. After crash there is lock that rancher is going to
wait for forever. You can remove it manually by reading documentation, but
as alter table is done and due to crash there is no record about successful
migration, you end up with infinite loop of crashes.

My workaround was to stop server, rollback database, remove all records
from that table and start server with new version. It worked well.

**Comment by ibuildthecloud** [comment]
We will do a v0.63.1 to address this.  Sorry for the troubles.

**Comment by xaka** [comment]
@ibuildthecloud I'd recommend to add extra info about migration process to log at startup time as it wasn't clear at the beginning why server isn't moving further and stuck at "Loading configuration" or something.

**Comment by ibuildthecloud** [comment]
@xaka Excellent point, will do.  Thanks, and again sorry for the issues here.

**Comment by sangeethah** [comment]
Tested with upgrade from V0.59.1 -> v0.63.1-rc1 with a rancher-server setup that had ~317,000 entries in process_execution table.

Upgrade was successful. Took about 5 minutes to perform the DB upgrade.
