### ISSUE TITLE
[RFE] Optionally build with debugger-friendly compile settings

### ISSUE THREAD

**Issue by moio** [rancher/rancher#39491]
**Is your feature request related to a problem? Please describe.**

In order to use a debugger such as [Delve](https://github.com/go-delve/delve), binaries have to be compiled with debugging symbols and disabling some optimizations.

**Describe the solution you'd like**
Pass the `DEBUG` variable to build scripts and, if set, make sure `-gcflags="all=-N -l"` is set and `-ldflags -s -w` is not set.

**Describe alternatives you've considered**
Another new variable could be added to the build scripts. That would be more granular but perhaps more redundant.

**Additional context**
Fleet and k3s already accepted similar patches:

https://github.com/rancher/fleet/pull/961
https://github.com/k3s-io/k3s/pull/6147

**Comment by rmweir** [comment]
Tried this twice and ended up with the following output:
```
Please wait for the line "debug layer=debugger continuing" to appear...

Targeting container "rancher". If you don't see processes from this container it may be because the container runtime doesn't support this feature.
Defaulting debug container name to debugger-zt6t8.
Forwarding from 127.0.0.1:4000 -> 4000
Forwarding from [::1]:4000 -> 4000
If you don't see a command prompt, try pressing enter.
Error attaching, falling back to logs: unable to upgrade connection: container debugger-zt6t8 not found in pod rancher-5699dcb9f6-96gxg_cattle-system
++ pgrep rancher
+ PID=34
++ stat -c %u /proc/34
+ USER_ID=0
++ stat -c %g /proc/34
+ GROUP_ID=0
+ ((  0 != 0  ))
+ ((  0 != 0  ))
+ echo 'root    ALL=(ALL:ALL) ALL'
+ exec sudo -u#0 -g#0 dlv attach 34 --continue --accept-multiclient --api-version 2 --headless --log --listen :4000
API server listening at: [::]:4000
2022-12-22T01:29:27Z warning layer=rpc Listening for remote connections (connections are not authenticated nor encrypted)
2022-12-22T01:29:27Z info layer=debugger attaching to pid 34
Could not attach to pid 34: this could be caused by a kernel security setting, try writing "0" to /proc/sys/kernel/yama/ptrace_scope
```
I built an image with the command `sudo TAG=v2.7-head DEBUG=true make`.
I then docker tagged it for my own repo with the tag "v2.7-head-debug".
I installed kubernetes using that image with the command
```
helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=<url> \
  --set bootstrapPassword=<pw> \
  --set rancherImage=<my-repo> \
  --set rancherImageTag=v2.7-head-debug
```
Then I ran pointed KUBECONFIG to the kubeconfig path for the local cluster and ran the script located [here](https://github.com/rancherlabs/delve-debugger/blob/master/util/debug-rancher.sh).

I'm assuming this should work as is without any intervention by me in the container. Moving to reopened for now, please let me know if I missed something.

**Comment by moio** [comment]
> Could not attach to pid 34: this could be caused by a kernel security setting, try writing "0" to /proc/sys/kernel/yama/ptrace_scope

It seems like ptrace could not attach to the process. Did you try applying the suggestion there in the host?

**Comment by rmweir** [comment]
No I did not, I figured this was meant to work with no intervention.

**Comment by moio** [comment]
Well, IIUC kernel settings cannot be changed by an unprivileged container - if that is really the root problem in your case.

Anyway, I'd track that as a separate problem - this issue is about adding debugger-friendly compile settings which is another necessary, but not sufficient, condition in order to debug successfully.

**Comment by moio** [comment]
I took a look at your setup and can confirm that:

1. `/proc/sys/kernel/yama/ptrace_scope` is a host kernel setting, default value depends on your distro and configuration. One should normally change it on the host via `echo 0 >/proc/sys/kernel/yama/ptrace_scope` as `root` on the node running the delve pod. [I added this to the delve-debugger README](https://github.com/rancherlabs/delve-debugger/blob/master/README.md#troubleshooting)
2. if one does not have SSH access to the host but can run privileged containers, one possibility is to run a pod with the host's `/proc` mounted inside of the container and changing the flag there. [I made a gist to explain how to do that.](https://gist.github.com/moio/97c55fd742f407e294d370e4f4876f96)
3. [there was a bug in the delve-debugger script which was pulling the wrong image, now fixed](https://github.com/rancherlabs/delve-debugger/commit/4bd762e19270bd99c36e568d617cc7a70d001298).

After that I could connect the debugger successfully to your instance, feel free to double check:

```
cd delve-debugger
git checkout master
git pull
./util/debug-rancher.sh
```

You should see a line like the following after 30 seconds or so:
```
2023-03-16T08:51:25Z debug layer=debugger continuing
```

That means the debugger has connected successfully.

**Comment by rmweir** [comment]
Awesome, worked. I will close this issue.
