### ISSUE TITLE
Introduce RKE2/k3s October 2022 Releases to KDM

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#39507]
Due to major issue existing in September 2022 releases of RKE2 (https://github.com/rancher/rke2/issues/3425) the following releases initially planned to be released with 2.7.0 / 2.6-out-of-band releases should **NOT** be included:
* v1.24.6+rke2r1
* v1.23.12+rke2r1
* v1.22.15+rke2r1

Instead, the following releases **should** be added:
* v1.24.7+rke2r1
* v1.23.13+rke2r1
* v1.22.15+rke2r2

While at it, for consistency also introduce corresponding k3s releases for October 2022 patches (there is no need to remove September 2022 patch versions for k3s as they are not affected by the referenced issue)

**Comment by Josh-Diamond** [comment]
Ticket #39507 - Test Results
---

With Docker on a single-node instance:

Verified on rancher `v2.7-08bf3fedd660c884fab1780a172593d5ad59f7cf-head`:
1. Fresh install of rancher `v2.7-head`
2. Verified - The following k8s versions are available on `2.7-head`:
     - `v1.24.7+rke2r1`
     - `v1.23.13+rke2r1`
     - `v1.24.7+k3s1`
     - `v1.23.13+k3s1`
3. Verified - Only k8s 1.23 + 1.24 available; as expected

Screenshot:

<img width="403" alt="Screen Shot 2022-11-08 at 11 30 37 AM" src="https://user-images.githubusercontent.com/46494969/200647528-62cbd60e-afac-4b27-bce0-6b1cbf52973a.png">

**Comment by rancher-max** [comment]
I can confirm this looks good on v2.7.0-rc9. I see the same results as posted by Josh above, and additionally:
1. Creating clusters with all above 4 versions are successful.
2. Upgrading imported clusters to all above 4 versions is successful.

I will wait for https://github.com/rancher/kontainer-driver-metadata/pull/1003 before validating on v2.6, then we can close this out. But for the purposes of rancher v2.7, this is done.

**Comment by Sahota1225** [comment]
@rancher-max 
https://github.com/rancher/kontainer-driver-metadata/pull/1003  - merged. Can we close this issue ?

**Comment by rancher-max** [comment]
#### Validated in Rancher v2.6.9 using KDM URL https://raw.githubusercontent.com/rancher/kontainer-driver-metadata/dev-v2.6-0922-patches/data/data.json

- Versions show up correctly
<img width="593" alt="image" src="https://user-images.githubusercontent.com/55997940/201197830-5bf26db6-0423-4aa0-bc32-d9e83022624c.png">

- Provisioning clusters with all of those versions are successful
<img width="1453" alt="image" src="https://user-images.githubusercontent.com/55997940/201201193-c34c39ff-4d8d-47ba-a652-0a28d9f6fed2.png">
