### ISSUE TITLE
vSphere Cloud Credentials name by-cloud-cred does not exist

### ISSUE THREAD

**Issue by aleiner** [rancher/rancher#39515]
**Rancher Server Setup**
- Rancher version: 2.7.0-rc9
- Installation option: Helm Chart
   - Kubernetes Cluster and version: RKE2 v1.24.7+rke2r1
- Proxy/Cert Details: Cert-Manager

**Information about the Cluster**
- Kubernetes version: v1.24.7+rke2r1
- Cluster Type: Local

**User Information**
- What is the role of the user logged in?: Admin/Cluster
  - If custom, define the set of permissions:

**Describe the bug**
Error: "Index with name by-cloud-cred does not exist" when attempting to add new cloud credentials for vSphere.

**To Reproduce**
Cluster Management -> Cloud Credentials -> Add credentials -> Save

**Result**
"Index with name by-cloud-cred does not exist".  Credentials do get added, just not with the name provided.

**Expected Result**
Credentials get added with proper name an no error banner.

**Screenshots**
<img width="805" alt="image" src="https://user-images.githubusercontent.com/104371562/200334868-4b14369e-e87f-44ef-836f-913da6c34b7a.png">

**Additional context**

**Comment by annablender** [comment]
@jameson-mcghee I just tried and was also unable to reproduce the issue on a rancher instance v2.6.9 in a vSphere environment. I believe when I saw the issue, my rancher instance was not behind the required vpn which caused connection issues and that error.

**Comment by jameson-mcghee** [comment]
**Reproduction attempt test information:**

**Rancher Server Setup**
- Rancher version: `v2.7.0-rc8` and `v2.6.9`.
- Installation option (Docker install/Helm Chart): Docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): N/A
- Proxy/Cert Details: N/A

**Information about the Cluster**
- Kubernetes version: N/A
- Cluster Type (Local/Downstream): N/A

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Admin and Standard

**Steps followed during the attempt to Reproduce**

1. Spin up a Rancher server on `v2.6.9`, and navigate to the Cluster Management --> Cloud Credentials page
2. Attempt to create VMware vSphere credentials with correct credential information

**Note:** I was unable to reproduce the reported issue on our test vSphere environment.

**Comment by aleiner** [comment]
Yes, I was successfully connected to the VPN.

**Comment by annablender** [comment]
@aleiner Could you add any more details you have on your lab setup? vCenter, vpn, where you're running the rancher instance, any custom networking setup? Thanks

**Comment by aleiner** [comment]
Can't think of anything out of the ordinary.  Since it's strictly for testing purposes, I have a three node RKE2 cluster running on the same ESXi node.  We can do a screen share if you'd like to see.
