### ISSUE TITLE
K8s: kubelet does not start

### ISSUE THREAD

**Issue by hwinkel** [rancher/rancher#3952]
Rancher Version: 0.63

Docker Version: 1.10.2

OS: CoreOS alpha 998

Steps to Reproduce: Create New Kubernetes Env. and add hosts.

Results: all services are started on the first host. kubelet on the 2nd. On both hosts the kubelet service cylces through start procedure with an error message in the log below

Expected: kubelet will start

Log Messages:

`time="2016-03-13T14:20:34Z" level=fatal msg="Failed to find container id:\n9:freezer:/system.slice/docker-9233deb31fca1231408c3f3147dfca28a5160ad8c682e07fc87f473eaef63e2d.scope\n8:blkio:/system.slice/docker-9233deb31fca1231408c3f3147dfca28a5160ad8c682e07fc87f473eaef63e2d.scope\n7:perf_event:/system.slice/docker-9233deb31fca1231408c3f3147dfca28a5160ad8c682e07fc87f473eaef63e2d.scope\n6:cpuset:/system.slice/docker-9233deb31fca1231408c3f3147dfca28a5160ad8c682e07fc87f473eaef63e2d.scope\n5:net_cls,net_prio:/system.slice/docker-9233deb31fca1231408c3f3147dfca28a5160ad8c682e07fc87f473eaef63e2d.scope\n4:cpu,cpuacct:/system.slice/docker-9233deb31fca1231408c3f3147dfca28a5160ad8c682e07fc87f473eaef63e2d.scope\n3:devices:/system.slice/docker-9233deb31fca1231408c3f3147dfca28a5160ad8c682e07fc87f473eaef63e2d.scope\n2:memory:/system.slice/docker-9233deb31fca1231408c3f3147dfca28a5160ad8c682e07fc87f473eaef63e2d.scope\n1:name=systemd:/system.slice/docker-9233deb31fca1231408c3f3147dfca28a5160ad8c682e07fc87f473eaef63e2d.scope\n"`

**Comment by ibuildthecloud** [comment]
Shoot... I know exactly what is wrong.  We might do a 0.63.1 to address this.

**Comment by hwinkel** [comment]
@ibuildthecloud great to know you know :+1:

**Comment by hwinkel** [comment]
there is no software without a .1 release... ;-)

**Comment by sangeethah** [comment]
Tested with rancher-server version - v0.63.1-rc1

Able to add 2 "CoreOS 899.10.0" hosts to Kubernetes environment.
 
kubelet container starts successfully.

Able to launch GuestBook catalog successfully.

**Comment by hwinkel** [comment]
Updated to 0.63.1 and the kubelet_1 starts on the first host, fine. but starting of kubelet_2 and _3 on further hosts (CoreOS 983) is failing as well.

```
core@coreos-1gb-fra1-02 ~ $ docker logs 0056bd76303e
I0315 17:52:01.853370       1 iptables.go:177] Could not connect to D-Bus system bus: dial unix /var/run/dbus/system_bus_socket: no such file or directory
I0315 17:52:01.853712       1 server.go:148] setting OOM scores is unsupported in this build
I0315 17:52:01.859304       1 server.go:210] Using userspace Proxier.
I0315 17:52:01.860523       1 proxier.go:159] Setting proxy IP to 46.101.101.81 and initializing iptables
I0315 17:52:01.895837       1 server.go:230] Tearing down pure-iptables proxy rules.
I0315 17:52:01.931678       1 conntrack.go:36] Setting nf_conntrack_max to 262144
I0315 17:52:01.932051       1 conntrack.go:41] Setting conntrack hashsize to 65536
I0315 17:52:01.934413       1 conntrack.go:46] Setting nf_conntrack_tcp_timeout_established to 86400
E0315 17:52:20.223291       1 event.go:202] Unable to write event: 'Post http://master/api/v1/namespaces/default/events: dial tcp 10.42.79.61:80: no route to host' (may retry after sleeping)
E0315 17:52:27.301549       1 event.go:202] Unable to write event: 'Post http://master/api/v1/namespaces/default/events: dial tcp 10.42.79.61:80: no route to host' (may retry after sleeping)
I0315 17:52:35.341501       1 proxier.go:415] Adding new service "default/kubernetes:https" at 10.43.0.1:443/TCP
I0315 17:52:35.343712       1 proxier.go:360] Proxying for service "default/kubernetes:https" on TCP port 43556
```

**Comment by hwinkel** [comment]
and kubelet_1 is failing as well.

**Comment by deniseschannon** [comment]
@hwinkel I haven't been able to reproduce your issue. I spun up a coreOS 983 setup. I have been able to successfully add in 3 hosts. All kubelets have started up with no issues. Then I deployed a Catalog entry and still fine. Then, I added in a fourth host and still no issues. And added another Catalog entry. 

Is this a fresh install or upgrade?

**Comment by hwinkel** [comment]
@deniseschannon rancher self os an upgrade from 0.59.1 -> 0.63 -> 0.63.1 today.

The 1st and 2nd host was a fresh install for K8s with rancher 0.63 the 3rd was fresh added today. alle are at DO with CoreOS 983

Currently the three kubelet container cycling through restarts.

**Comment by deniseschannon** [comment]
I had a fresh install of v0.63.1 on DO at CoreOS 983 and then added hosts/services in my K8S environment. Would you be willing to delete your K8s environment and creating a new one and re-adding hosts?

**Comment by hwinkel** [comment]
sure, later this german evening.. a fresh Rancher Install would not work quickly, but Deleting K(s and adding a new one with 3 Hosts is no prob. should I have fresh CoreOS instances or just deletiing and purging containers before I re-add?

**Comment by deniseschannon** [comment]
@hwinkel I haven't tested it, but I would believe that deleting and purging containers before adding should work. If not, I have found that adding DO hosts for CoreOS are one of the quickest and easiest to get set up. :)

**Comment by hwinkel** [comment]
Right, not only to setup also to maintain, because CoreOS make it for free for you ...

**Comment by deniseschannon** [comment]
@hwinkel I wish it was free. Is it free for you? It's just a lot easier than the other distros which require a Docker installation after getting the droplet set up.

**Comment by hwinkel** [comment]
CoreOS of course is free

**Comment by hwinkel** [comment]
like CentOS is free. The Update Procedure Runs free as well, What is not free is the Managed Linux Web Console

**Comment by hwinkel** [comment]
3 Node Cluster is coming up now. 3x fresh CoreOS 983. BTW: why the etcd container only runs on one host?

**Comment by hwinkel** [comment]
Cluster seems runnig, but installing GuestBook from catalog hungs with restarts of kubernetes-loadbalancer

**Comment by deniseschannon** [comment]
@hwinkel Now that you have k8s running, it seems like you are hitting https://github.com/rancher/rancher/issues/4006 which we haven't been able to reproduce. Can you open new bugs if you are having issues as it's hard to track a closed bug. :)

**Comment by hwinkel** [comment]
sure. lets focus on #4006
