### ISSUE TITLE
[rancher-dns] External DNS removes records not related to Rancher

### ISSUE THREAD

**Issue by theit8514** [rancher/rancher#3954]
Rancher Version: 0.63.0 and rancher/external-dns:v0.2.1

Docker Version: 1.10.1

OS: RancherOS

Steps to Reproduce:
1. Setup up AWS domain, add A record for test-default.domain.com
2. Ensure Rancher has environment named Default.
3. Set up Route53 external dns container for domain.

Results: 
Route53 external dns removes record test-default.

    3/13/2016 3:00:29 PMtime="2016-03-13T19:00:29Z" level=info msg="DNS records to remove: [{test-default.domain.com. [8.x.x.x] A 86400}]"
    3/13/2016 3:00:29 PMtime="2016-03-13T19:00:29Z" level=info msg="Removing dns record: {test-default.domain.com. [8.x.x.x] A 86400}"

Expected:
Should only remove records with *.default.domain.com and not *default.domain.com.

**Comment by alena1108** [comment]
Duplicate of of https://github.com/rancher/rancher/issues/3716; we are going to address it soon.
