### ISSUE TITLE
Rancher Catalogs do not respect capitalization in url requests

### ISSUE THREAD

**Issue by willseward** [rancher/rancher#3955]
Rancher Version: v0.63.0

Steps to Reproduce:  Name a catalog "ExampleCatalog"

Results: Catalog items will populate, but they cannot be launched from the UI because the api request will look for "example:item:0" not "Example:item:0"

**Comment by prachidamle** [comment]
@vincent99 added the fix needed. PR https://github.com/rancher/rancher-catalog-service/pull/44

**Comment by willseward** [comment]
This is great, thanks! I did admittedly, pull out a bit of hair over this one...

**Comment by prachidamle** [comment]
@willseward sure thanks, and sorry for the trouble...

**Comment by sangeethah** [comment]
Tested with latest build from master and rancher-catalog version - v0.6.0

Had catalog name with Capital letters/Mixed case/numeric values.

Able to successfully launch templates from this catalog.

@willseward , fix for this issue will be available in the next rancher server release.
