### ISSUE TITLE
Update embedded k3s version for Rancher to 1.24.8+

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#39559]
Currently, Rancher embeds k3s 1.24.4 (see https://github.com/rancher/rancher/blob/59661d10c9feb860b552a68dbca5fab771ff6236/package/Dockerfile#L31) when running in Docker.

There is already [1.24.7](https://github.com/k3s-io/k3s/releases/tag/v1.24.7%2Bk3s1) available with 1.24.8 not far off (with upstream releasing on 11/9/22 or a day-two later).

It's requested to update embedded k3s to 1.24.8 (or even a later one depending on when the next Rancher release happens).

**Comment by PratikforCoding** [comment]
Hey  @snasovich can I work on this? Is this the only file where I have to update this?

**Comment by sbstp** [comment]
@PratikforCoding you can work on this. Check out this [commit](https://github.com/rancher/rancher/commit/5f66d2404355de93649841504f91ece924f73272) where the version was incremented. There's a few places where it needs to be updated.

**Comment by PratikforCoding** [comment]
Hey @sbstp can you review this? I made the changes.

**Comment by sbstp** [comment]
Done. Thanks for the PR. Closing this one as it's been merged.

**Comment by snasovich** [comment]
Reopening for testing.

**Comment by jameson-mcghee** [comment]
During validation, I confirmed that on `v2.6.9` the default embedded k8s version for **K3s** clusters is `v1.24.4+k3s1` while on `v2.7-head` (Commit ID: 216bb7f) I confirmed that the version of k8s for **K3s** clusters is `v1.24.8+k3s1`. Therefore I am closing this ticket as Done.

**`v2.6.9`:**
![image](https://user-images.githubusercontent.com/13294321/207146056-6da8c1ae-cdf9-4876-8eaa-26c6fc00c8ba.png)

**`v2.7-head` (Commit ID: 216bb7f):**
![image](https://user-images.githubusercontent.com/13294321/207146576-10fd16c8-2400-410b-8035-fae81c6574b7.png)
