### ISSUE TITLE
[RFE] Steve: Add debounce logic to websocket

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#39568]
The UI has difficulty processing more than one event. Our watches currently flood it with events, which can cause pauses/performance delays due to constant processing of websocket events. Our counts resource includes debounce logic, which aggregates the events over a given time period and only returns events after a specific time period has past (which prevents these issues from occurring). It would be helpful if all communication over the websockets was subject to similar debounce logic.

**Comment by KevinJoiner** [comment]
This would be an enhancement to the steve web socket with the following requirements
- Websocket only send the latest unique events to the front end.
   - unique is defined by `GVR + name + namespace`
- Websocket will bundle events into a single message that is a list of events.
- Websocket will allow a configurable size for list message  `maxMessageSize`.
   - This could be done using the `sub.Start` message already sent to the back end
- Websocket will only send the list of events after a set amount of time (default: 100 milliseconds)
   - If the number of events to send is greater than `maxMessageSize` then the debounce time will be ignored
- Websocker will allow a configurable debounce time.
    - This could also be done using the `sub.Start` message

**Comment by moio** [comment]
This will come as part of https://github.com/rancher/rancher/issues/40773, closing
