### ISSUE TITLE
[go-machine-service] Adding machine driver fails with checksum error

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#3956]
Rancher Version:
v0.63.0
Docker Version:
1.9.1
OS: 
Ubuntu 14.04-64bit

**Steps to Reproduce**
Add a new machine driver using the following parameters:

```
Download URL: https://github.com/janeczku/docker-machine-vultr/releases/download/v1.0.5/docker-machine-driver-vultr-v1.0.5-linux-amd64.tar.gz
MD5 Checksum: 409c17282982c169c379645336b3caa4
```
**Results**
Fails with checksum error:

> level=error msg="Error while downloading and verifying: https://github.com/janeczku/docker-machine-vultr/releases/download/v1.0.5/docker-machine-driver-vultr-v1.0.5-linux-amd64.tar.gz Checksum provided: 409c17282982c169c379645336b3caa4 does not match calculated checksum : ece3d622b2d95f2f2d18074c6a5ced16 for driver with uri: /tmp/gms-010906735/docker-machine-driver-vultr-v1.0.5-linux-amd64.tar.gz"

**Expected**
No error. The supplied checksum is correct.

**Comment by vincent99** [comment]
@janeczku Lies? :smile:

```
mercury:tmp vincent$ curl -L -O https://github.com/janeczku/docker-machine-vultr/releases/download/v1.0.5/docker-machine-driver-vultr-v1.0.5-linux-amd64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   629    0   629    0     0    642      0 --:--:-- --:--:-- --:--:--   641
100 2804k  100 2804k    0     0   944k      0  0:00:02  0:00:02 --:--:-- 2232k
mercury:tmp vincent$ md5 docker-machine-driver-vultr-v1.0.5-linux-amd64.tar.gz
MD5 (docker-machine-driver-vultr-v1.0.5-linux-amd64.tar.gz) = ece3d622b2d95f2f2d18074c6a5ced16
```

**Comment by vincent99** [comment]
Oh, your published list is the md5 of the `.tar`, not the `.tar.gz` that's actually downloaded.

BTW we used your driver for QA to test custom drivers, but apparently they didn't try the supplied checksums :smile:

**Comment by janeczku** [comment]
:stuck_out_tongue_winking_eye: Haha, golden. Apparently Safari gunzips `.tar.gz` downloads and then stores them as `.tar`. And i almost believed in a checksum conspiracy....

**Comment by janeczku** [comment]
Works as expected after supplying the correct checksum.

![screenc](https://cloud.githubusercontent.com/assets/3813921/13744760/5089426e-e9ea-11e5-917e-0bee8c90cc4a.png)
