### ISSUE TITLE
[BUG] Internal error occurred: failed calling webhook "rancher.cattle.io"

### ISSUE THREAD

**Issue by pramodsetlur** [rancher/rancher#39577]
**Rancher Server Setup**
- Rancher version: 2.6.9
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): GKE  v1.23.8
- Proxy/Cert Details: TLS externally handled by nginx ingress controller

**Information about the Cluster**
- Kubernetes version: GKE  v1.23.8-gke.1900
- Cluster Type (Local/Downstream): Local

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): Admin

**Describe the bug**
Completing the first installation of Rancher using helm chart (no errors from helm), there was a lot of errors seen in Rancher logs and the UI indicating
`Internal error occurred: failed calling webhook "rancher.cattle.io": failed to call webhook: Post "https://rancher-webhook.cattle-system.svc:443/v1/webhook/mutation?timeout=10s": context deadline exceeded`.

It looked like Rancher was unable to invoke the webhook successfully, and this could be due to the self signed certificate being used by rancher-webhook svc. Confirmed that by invoking the rancher-webhook svc from the rancher pod.

```
rancher-infra-dev-54885dd99d-89htt:/var/lib/rancher # curl https://rancher-webhook.cattle-system.svc:443/v1/webhook/mutation?timeout=10s
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

I worked around this issue by setting the rancher.cattle.io, rancherfleet.cattle.io MutatingWebhookConfiguration and the ValidatingWebhookConfigurations's `failurePolicy: Ignore`. This allowed the API calls to the rancher-webhook to pass through and then complete the installation steps required by Rancher.

**To Reproduce**
1. Install Rancher (using Helm) for the first time in a new cluster using the follow values:
```
  tls: external
  hostname: rancher.company.com
  ingress:
    extraAnnotations:
      kubernetes.io/ingress.class: "nginx-internal"
      external-dns.alpha.kubernetes.io/hostname: rancher.company.com
  bootstrapPassword: value1
```
2. Login to the UI.
3. Observer in the homepage (under Cluster) with the error:
`Internal error occurred: failed calling webhook "rancher.cattle.io": failed to call webhook: Post "https://rancher-webhook.cattle-system.svc:443/v1/webhook/mutation?timeout=10s": context deadline exceeded`.

This was also seen when Rancher had to invoke the fleet endpoint. 

**Result**
rancher-webhook's svc is unable to accept requests and the requester is seen with `Context deadline exceeded`. 

**Expected Result**
Rancher should be able to bypass the internal calls to its svc.

**Screenshots**
An error from a different operation within Rancher showing the same error
![image](https://user-images.githubusercontent.com/8100497/201411097-2c07071c-239d-4db5-b40a-137a02765284.png)

**Additional context**
The workaround to set the mwc and vwc rancher.cattle.io's failurePolicy has also been automatically reverted to `failurePolicy: Fail`.

**Comment by pablos91** [comment]
Hi there! It looks like we are facing the same issue here. My first suspect is TLS termination on L7 that I'm using as well.

Did you, by any chance try without the `tls: external` switch ?

Cheers

**Comment by pramodsetlur** [comment]
We are still not sure of a solution or the root cause. The one thing we are trying to see is, if installing cert-manager (even though it is not needed when Rancher is installed with `tls:external`) can help alleviate the issue.
