### ISSUE TITLE
Other machine drivers aren't populating in the UI after selecting the "None" driver

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#3957]
Rancher Version:
v0.63.0

Steps to Reproduce: 
1. Click to add Host
2. Select "Other"
3. Use dropdown for driver to select `None`. Afterwards, the other drivers are not populating correctly.

Results: 
The questions/answers remain blank.

<img width="811" alt="screen shot 2016-03-13 at 9 55 23 pm" src="https://cloud.githubusercontent.com/assets/11410997/13735405/55826ff4-e966-11e5-8688-8ae3781f5beb.png">

Expected:

The other options should provide what the questions for the answers.

**Comment by vincent99** [comment]
`noneConfig` shouldn't appear in the `machine` schema.  It's useless, and blowing up the UI because it refers to a schema that doesn't exist.

**Comment by deniseschannon** [comment]
Verified with v1.0.0-rc1 that this is no longer showing up.
