### ISSUE TITLE
[RFE] Migrate rancher-[save,load]-images.[sh,ps1] functionality to a CLI utility

### ISSUE THREAD

**Issue by stormqueen1990** [rancher/rancher#39583]
**Is your feature request related to a problem? Please describe.**

Currently, it is not possible to mirror a full OCI index using the `rancher-save-images` and `rancher-load-images` scripts. This is because of the default behaviour for `docker pull`, which matches your architecture against the images available in an index and downloads only the image that matches your current architecture.

Another pain point with the current scripts is that there is some code redundancy between these scripts.

**Describe the solution you'd like**

Have a CLI utility written in Golang to perform these tasks in a way that causes less divide between the Windows and Linux versions of the script, allow for better automated testing, and allow performing more complex tasks when copying the images. Examples of such tasks would be copying to more than a registry at a time and copying full OCI indices.

**Describe alternatives you've considered**

Update the bash and PowerShell scripts to use `crane` or `skopeo` instead of `docker` would allow for mirroring OCI indices.

**Comment by sbstp** [comment]
#39609 is probably related to this issue
