### ISSUE TITLE
handler pspdelete-deferred: Index with name by-cluster does not exist, requeuing

### ISSUE THREAD

**Issue by xaha24** [rancher/rancher#39587]
**Rancher Server Setup**
- Rancher version: 2.6.9
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: RKE 1.20.15
- Cluster Type (Local/Downstream): Local

**User Information**
- What is the role of the user logged in? Admin

**Describe the bug**

After upgrading from 2.6.7 to 2.6.9 I get the error:
   
handler pspdelete-deferred: Index with name by-cluster does not exist, requeuing. 

For two of multiple installed clusters only.

What can i do to find the cause?

**Comment by steffeneichler** [comment]
Same problem here. Same rancher and k8s version.
`2022/11/16 08:47:07 [ERROR] error syncing 'c-xxxxx': handler pspdelete-deferred: Index with name by-cluster does not exist, requeuing
...
2022/11/16 08:48:40 [ERROR] error syncing 'c-xxxxx': handler pspdelete-deferred: Index with name by-cluster does not exist, requeuing
2022/11/16 08:49:09 [ERROR] error syncing 'c-xxxxx': handler pspdelete-deferred: Index with name by-cluster does not exist, requeuing
`

**Comment by Rancheroo** [comment]
I'm seeing this error message accomponied with slowness on a managed cluster with around 34250 resources.
`error syncing 'c-*****': handler pspdelete-deferred: Index with name by-cluster does not exist, requeuing`

**Comment by xaha24** [comment]
After upgrading to 2.6.11 the message disappeared.
