### ISSUE TITLE
k3s cluster with EC2 Spot instances: nodes are not replaced when spot is terminated

### ISSUE THREAD

**Issue by vkruoso** [rancher/rancher#39590]
This is a follow up on #39328.

I've been using the k3s cluster with EC2 Spot Instances for about 25 days now. All working great, except the fact that when spot instances are taken down, the cluster fails to replace them correctly. I'm not running any spot termination detection in the cluster (this would help me prepare for the node being taken down, but would not remove the node from the cluster itself).

If I take a node that was previously removed by AWS, and remove it manually from the cluster management screen, it fails to delete (gives permission error) because the machine does not exist anymore. Force deleting works after that.

Is there anyway to work around this problem?

**Comment by vkruoso** [comment]
It is still relevant. If someone can point if this support is something of interest for rancher, would have interest to dig deeper on alternatives.

**Comment by GugaAraujo** [comment]
I'm going through the same situation.
It would be fantastic to replace the node automatically without the need for force deletion

**Comment by vkruoso** [comment]
The issue is still relevant.
