### ISSUE TITLE
[BUG] Rancher 2.6.9 installs Docker 20.10.17 instead of 20.10.21

### ISSUE THREAD

**Issue by TomyLobo** [rancher/rancher#39601]
Rancher 2.6.9 is installing Docker 20.10.17 from 2022-06-06.
The current version is 20.10.21 from 2022-10-25, so there's almost 5 months worth of bugfixes and security updates missing, including fixes for 3 CVEs with a score of 7.5 (High) in 20.10.19.
Rancher 2.6.9 is from 2022-10-18 and at least Docker 20.10.18 had been out for more than a month back then.
So I figured this must be something independent of the specific Rancher version.
I found out Rancher retrieves a file from an URL under [releases.rancher.com](http://releases.rancher.com/) and that version 20.10.17 is hardcoded in there:
```bash
$ curl -s https://releases.rancher.com/install-docker/20.10.sh | grep ^VERSION
VERSION="20.10.17"
```
Furthermore, a 20.10.17.sh is available, but a 20.10.21.sh is not.

I looked into this a bit and it seems that this PR was supposed to fix this:
https://github.com/rancher/install-docker/pull/107
If I interpret this correctly, there needs to be a tag to make it go live.

**Comment by snasovich** [comment]
@TomyLobo , you've linked correct PR.
The work on this is handled as part of https://github.com/rancher/rancher/issues/39345, closing this as a duplicate.
