### ISSUE TITLE
[BUG] updated Agent Environment Vars are not synced to existing nodes

### ISSUE THREAD

**Issue by thomashoell** [rancher/rancher#39603]
**Rancher Server Setup**
- Rancher version: 2.6.9
- Installation option Helm on rke2 1.24.7

**Information about the Cluster**
- Kubernetes version: 1.24.4
- Cluster Type: Downstream (created via vSphere cloud provider)

**Describe the bug**
I need to use a http proxy so the rancher agent can reach the internet. This is done by setting HTTP_PROXY, HTTPS_PROXY and NO_PROXY under _Agent Environment Vars_ when creating the cluster. So far, this worked.
In order to enable etcd snapshots to s3, I hat to extend the NO_PROXY variable. Snapshots still didn't work and I noticed that on the master nodes the variables in _/etc/systemd/system/rancher-system-agent.env_ are **NOT** updated. 

However, when I add new nodes to the cluster, the settings are fine. 
Editing the file on the existing nodes manually and restarting _rancher-system-agent_ seems to work.

**To Reproduce**
- create a cluster and set _Agent Environment Vars_
- edit cluster configuration and change the variables

**Result**
- variables are not updated on existing nodes

**Expected Result**
- variables are updated according to cluster configuration

**Comment by billhong-just** [comment]
Me too! 👀
