### ISSUE TITLE
[BUG]ldap failing to bind user on initial setup (openldap)

### ISSUE THREAD

**Issue by jwhitelbl** [rancher/rancher#39610]
**Rancher Server Setup**
- Rancher version: 2.6.9
- Installation option: Docker

**Information about the Cluster**
- Kubernetes version: v1.18.6
- Cluster Type: Local

**User Information**
- What is the role of the user logged in? Admin

**Describe the bug**
Setting up the openldap auth provider, the initial 'enable' fails with:
`2022/11/15 21:04:40 [DEBUG] Now generating Ldap token
2022/11/15 21:04:40 [DEBUG] Now creating Ldap connection
2022/11/15 21:04:40 [DEBUG] Binding service account username password
2022/11/15 21:04:40 [DEBUG] Binding username password
2022/11/15 21:04:40 [ERROR] API error response 401 for POST /v3/openLdapConfigs/openldap?action=testAndApply. Cause: LDAP Result Code 49 "Invalid Credentials":`

**To Reproduce**
Attempt to configure OpenLDAP auth provider with TLS

**Result**
authentication failed: Invalid credentials

**Expected Result**
The provide to become enabled

**Screenshots**

**Additional context**
Attempted several ldapsearch commands from the node itself, all successful, including:
ldapsearch -H ldaps://[redacted] -x -D "cn=[redacted]" -W -b "ou=[redacted]" -s sub "sAMAccountName=[redacted]"

It would seem the Service Account binding is successful but the follow-up user binding is not.  Confirmed user credentials via several methods.

**Comment by slickwarren** [comment]
tried to reproduce this on v2.6.9, but could not:

setup:
docker install, v2.6.9 on v1.24.7+k3s1 local cluster
**non-tls** openLDAP server

* add an LDAP auth provider with valid credentials -- successful

have you tried without tls enabled, and if so do you run into the same problems?

**Comment by jwhitelbl** [comment]
I now believe this is a local configuration (openldap ACL) issue and not a bug.  I'll reopen if we fix the ACL and still experience the issue.
