### ISSUE TITLE
[BUG] RKE2, Edit Config, Advanced Menu blank

### ISSUE THREAD

**Issue by jonathon2nd** [rancher/rancher#39619]
**Rancher Server Setup**
- Rancher version: v2.6.8
- Installation option (Docker install/Helm Chart): docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details: Self

**Information about the Cluster**
- Kubernetes version: v1.24.2	
- Cluster Type (Local/Downstream): local
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? Admin/Cluster
  - If custom, define the set of permissions: 

**Describe the bug**

Advanced menu is blank when attempting to edit config of an existing rke2 cluster.

**To Reproduce**

Select existing RKE2 cluster, and `Edit config`
Then go to `Advanced`

**Result**
It is blank

**Expected Result**

To have access to the advanced menu

**Screenshots**

![image](https://user-images.githubusercontent.com/52681917/202237703-2dcfca82-59e2-4bf6-bd23-6b859793fd29.png)

**Additional context**

I have not updated recently. 
There are no console logs or network 404's or anything of the like.
I do not see anything in the Rancher logs.
I have tested with Chrome and Firefox.
I do not have anything else other than RKE2 and imported clusters, so I do not know if this is happening with RKE.
When I go to create a new RKE2 cluster, advanced menu is there
![image](https://user-images.githubusercontent.com/52681917/202238122-bfc87a4e-8f9a-4f69-81de-0211b5f23e6c.png)
![image](https://user-images.githubusercontent.com/52681917/202238156-c578e848-b993-42d7-b67a-1b15a8381cfc.png)

**Comment by slickwarren** [comment]
this is not reproducible on v2.6.9 nor v2.7.0 on custom or node driver rke1, rke2 clusters. Could you please try to upgrade? 
Closing as you filed a duplicate in dashboard as well, linked above
