### ISSUE TITLE
Initializing timeout box is missing from HealthCheck tab

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#3962]
Rancher Version:
v0.63.0

We've introduced the ability to set an initializing time out so that if a service is stuck in initializing state, it will start to recreate the containers.

**Comment by andyshinn** [comment]
Are there any plans (I couldn't find an existing issue) to give better feedback on the "initializing forever" issues? Off the top of my head, I've run into:

* Registry not configured.
* Registry 401
* No hosts available to schedule container
* Image / tag does exists on registry

It would be great to bubble up these states. Not critical, but it seems like the majority of my user questions are always "Hey, it is stuck in Initializing forever".

**Comment by deniseschannon** [comment]
@andyshinn In v0.63.0, we've added this issue to address a lot of what you mentioned.
https://github.com/rancher/rancher/issues/3630

Containers can now have an "Error" state.

**Comment by deniseschannon** [comment]
The service will be stuck in "Activating" but if you click on the containers, you can see the error state of the container and the message of why it failed.

**Comment by andyshinn** [comment]
Ah, great. I didn't see that in the release notes. I'll try and get upgraded soon.

**Comment by tfiduccia** [comment]
Version - master 3/16
Verified Added and posting
