### ISSUE TITLE
[BUG] Rancher helm chart doesnt work with latest nginx helm chart due to ingress spec

### ISSUE THREAD

**Issue by jbilliau-rcd** [rancher/rancher#39638]
**Rancher Server Setup**
- Rancher version: 2.6.9 / 2.7.0
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): EKS
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: EKS 1.21
- Cluster Type (Local/Downstream): Local
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): EKS

**Describe the bug**
The Helm chart used to install Rancher doesn't contain a `path: /` in it's `Ingress` spec, as you can see here: https://github.com/rancher/rancher/blob/c0f6cdb9a7494cb6eae2e3b341174bd079f13073/chart/templates/ingress.yaml#L45

Because of this, if using the latest *0.15.1* **nginx-ingress** Helm chart from here - https://helm.nginx.com/stable, it fails to create the proper nginx configuration for the Rancher ingress due to this error that shows up when you describe the **rancher** `Ingress` object:

```
  Warning  Rejected        12s (x3 over 12s)    nginx-ingress-controller  spec.rules[0].http.path[0].path: Required value
  Warning  Rejected        12s                  nginx-ingress-controller  cattle-system/rancher was rejected: with error: spec.rules[0].http.path[0].path: Required value
```

Adding `path: "/"` fixes it. This needs to be supported in the Rancher chart.

**To Reproduce**
Deploy newest Rancher chart, deploy newest nginx chart. They aren't compatible.

**Expected Result**
I expected an `Ingress` object to be created with the Rancher helm chart that supports the latest `Ingress` spec that the nginx Helm chart requires in order to create the proper ingress configuration.

**Comment by slickwarren** [comment]
Rancher runs specific versions of nginx, which is why we have our own version in the chart. If you need to use the latest nginx install, you would need to follow nginx documentation to do so, though that is an unsupported workflow based on what you have provided.

**Comment by jbilliau-rcd** [comment]
Yeah that's the gist I am getting. Would still be nice if the Rancher chart offered this option for those of us who want to use the nginx-provided Helm chart and not the kubernetes-provided one. That being said, if this is something that won't ever be considered, I can close the issue; dont wan't to bloat up the already high issue list. Let me know.

**Comment by slickwarren** [comment]
Since it is not directly affecting any functionality and is outside the scope of our support I would say this should be closed, but if this issue lights up in the future we can reopen it and reconsider.

**Comment by cbron** [comment]
If we have time to dev-validate we may be able to get into q2, otherwise hopefully q3.

**Comment by KevinJoiner** [comment]
This was fixed three weeks ago in the latest NGINX release.  https://github.com/nginxinc/kubernetes-ingress/issues/3498

**Comment by JonCrowther** [comment]
Steps to reproduce the bug:
1. Create a kubernetes cluster (I personally used an AKS cluster)
2. Add helm repos:
    1. `helm repo add nginx-stable https://helm.nginx.com/stable`
    2. `helm repo add rancher-stable https://releases.rancher.com/server-charts/stable`
    3. `helm repo add jetstack https://charts.jetstack.io`
4. Install ingress: `helm upgrade --install ingress nginx-stable/nginx-ingress --namespace ingress-nginx --set controller.service.type=LoadBalancer --version 0.15.1 --create-namespace --set controller.watchIngressWithoutClass=true`
5. Apply crds: `kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v1.11.0/cert-manager.crds.yaml`
6. Install cert-manager: `helm upgrade --install cert-manager jetstack/cert-manager --namespace cert-manager --create-namespace --version v1.11.0`
7. Install rancher: `helm upgrade --install rancher rancher-stable/rancher --namespace cattle-system --set hostname=jono.cp-dev.rancher.space --set bootstrapPassword=admin --set global.cattle.psp.enabled=false --version 2.7.2 --set ingress.ingressClassName=nginx`
8. Describe the ingress: `kubectl describe ingress -n cattle-system rancher`

Under the `Events` you should see:
```
  Warning  Rejected           6m19s  nginx-ingress-controller   spec.rules[0].http.path[0].path: Required value
```

**Comment by KevinJoiner** [comment]
Closed due to commit comment still needs validation

**Comment by JonCrowther** [comment]
Installing the latest helm chart with the same nginx version successfully fixes the bug. 

```
kubectl describe ingress -n cattle-system rancher
...
Events:
  Type     Reason                     Age    From                       Message
  ----     ------                     ----   ----                       -------
  Normal   CreateCertificate          2m47s  cert-manager-ingress-shim  Successfully created Certificate "tls-rancher-ingress"
  Warning  AddedOrUpdatedWithWarning  2m47s  nginx-ingress-controller   Configuration for cattle-system/rancher was added or updated ; with warning(s): TLS secret tls-rancher-ingress is invalid: secret doesn't exist or of an unsupported type

```
