### ISSUE TITLE
Catalog service to use cached git clone

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#3964]
We would like to ship a pre-cloned version of the catalog repo as part of the rancher server container.

If the rancher-catalog-service detects a cloned version, it should try and pull an update down to the server. 

If the upstream catalog url can not be reached or cloned, then it should serve up the cached version shipped with the container.

**Comment by cloudnautique** [comment]
I added cached copy to build process.
 I run `rancher-catalog-service -validate -catalogUrl <default>` as part of the container build process.
It gets cloned into /var/lib/cattle/DATA
I use IPtables to block outbound 443. 

when the container starts up I get:

```
INFO[0000] Starting Rancher Catalog service             
INFO[2016-03-21T04:35:55Z] Using catalog library=https://github.com/rancher/rancher-catalog.git 
INFO[2016-03-21T04:35:55Z] Using catalog community=https://github.com/rancher/community-catalog.git 
INFO[2016-03-21T04:35:55Z] Cloning the catalog from git URL https://github.com/rancher/rancher-catalog.git 
Cloning into './DATA/library'...
INFO[0000] Setting log level                             logLevel=info
INFO[0000] Starting go-machine-service...                gitcommit=8bc2633
INFO[0000] Updating docker-machine-drivers from cattle. 
INFO[0000] Starting rancher-compose-executor             version=v0.7.2
fatal: unable to access 'https://github.com/rancher/rancher-catalog.git/': Failed to connect to github.com port 443: Connection refused
ERRO[2016-03-21T04:35:55Z] Failed to clone the catalog from git err: exit status 128 
INFO[2016-03-21T04:35:55Z] Cloning the catalog from git URL https://github.com/rancher/community-catalog.git 
Cloning into './DATA/community'...
INFO[0000] Initializing event router                     workerCount=10
fatal: unable to access 'https://github.com/rancher/community-catalog.git/': Failed to connect to github.com port 443: Connection refused
```

When I click on the catalog in the UI no items show up.

I would expect that the catalog items still show up. The /var/lib/cattle/DATA directory is destroyed.

This is using the latest v0.6.0 version.

**Comment by prachidamle** [comment]
These are the steps I did:

1) docker run -it rancher/server:v1.0.0-rc1 bash
2) root@c5cb3b4b7db9:/# ls
bin  boot  dev  etc  home  lib  lib64  media  mnt  opt  proc  root  run  s6-statics  sbin  service  srv  sys  tmp  usr  var

====> As seen here no "DATA" directory seen existing

3) So when catalog-service is started, it clones the repo's newly

root@c5cb3b4b7db9:/# rancher-catalog-service -validate -debug -catalogUrl library=https://github.com/rancher/rancher-catalog.git,community=https://github.com/rancher/community-catalog.git
INFO[0000] Starting Rancher Catalog service             
DEBU[2016-03-22T19:48:59Z] url %slibrary=https://github.com/rancher/rancher-catalog.git,community=https://github.com/rancher/community-catalog.git 
INFO[2016-03-22T19:48:59Z] Using catalog library=https://github.com/rancher/rancher-catalog.git 
INFO[2016-03-22T19:48:59Z] Using catalog community=https://github.com/rancher/community-catalog.git 
DEBU[2016-03-22T19:48:59Z] Catalog library does not exist, proceeding to clone the repo :  
INFO[2016-03-22T19:48:59Z] Cloning the catalog from git URL https://github.com/rancher/rancher-catalog.git 
Cloning into './DATA/library'...
remote: Counting objects: 1038, done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 1038 (delta 0), reused 0 (delta 0), pack-reused 1036
Receiving objects: 100% (1038/1038), 380.62 KiB | 0 bytes/s, done.
Resolving deltas: 100% (473/473), done.
Checking connectivity... done.
DEBU[2016-03-22T19:49:01Z] Reading metadata folder for template:cloudflare, path: DATA/library/templates/cloudflare 
DEBU[2016-03-22T19:49:01Z] Reading metadata folder for template:convoy-gluster, path: DATA/library/templates/convoy-gluster 
DEBU[2016-03-22T19:49:01Z] Reading metadata folder for template:convoy-nfs, path: DATA/library/templates/convoy-nfs 
DEBU[2016-03-22T19:49:01Z] Reading metadata folder for template:dnsimple, path: DATA/library/templates/dnsimple 
DEBU[2016-03-22T19:49:01Z] Reading metadata folder for template:logstash, path: DATA/library/templates/logstash 
DEBU[2016-03-22T19:49:01Z] Reading metadata folder for template:pointhq, path: DATA/library/templates/pointhq 
DEBU[2016-03-22T19:49:01Z] Reading metadata folder for template:route53, path: DATA/library/templates/route53 
INFO[2016-03-22T19:49:01Z] Catalog loaded without errors                

4) Stop the rancher-catalog-service

5) Start back again 

6) root@c5cb3b4b7db9:/# rancher-catalog-service -validate -debug -catalogUrl library=https://github.com/rancher/rancher-catalog.git,community=https://github.com/rancher/community-catalog.git
INFO[0000] Starting Rancher Catalog service             
DEBU[2016-03-22T19:49:47Z] url %slibrary=https://github.com/rancher/rancher-catalog.git,community=https://github.com/rancher/community-catalog.git 
INFO[2016-03-22T19:49:47Z] Using catalog library=https://github.com/rancher/rancher-catalog.git 
INFO[2016-03-22T19:49:47Z] Using catalog community=https://github.com/rancher/community-catalog.git 
DEBU[2016-03-22T19:49:47Z] Catalog library already exists with same repo url, pulling updates 
DEBU[2016-03-22T19:49:47Z] Pulling the catalog library from the repo to sync any new changes to ./DATA/library 
DEBU[2016-03-22T19:49:47Z] Reading metadata folder for template:cloudflare, path: DATA/library/templates/cloudflare 
DEBU[2016-03-22T19:49:47Z] Reading metadata folder for template:convoy-gluster, path: DATA/library/templates/convoy-gluster 
DEBU[2016-03-22T19:49:47Z] Reading metadata folder for template:convoy-nfs, path: DATA/library/templates/convoy-nfs 
DEBU[2016-03-22T19:49:47Z] Reading metadata folder for template:dnsimple, path: DATA/library/templates/dnsimple 
DEBU[2016-03-22T19:49:47Z] Reading metadata folder for template:logstash, path: DATA/library/templates/logstash 
DEBU[2016-03-22T19:49:47Z] Reading metadata folder for template:pointhq, path: DATA/library/templates/pointhq 
DEBU[2016-03-22T19:49:47Z] Reading metadata folder for template:route53, path: DATA/library/templates/route53 
INFO[2016-03-22T19:49:47Z] Catalog loaded without errors

**Comment by prachidamle** [comment]
@cloudnautique I see the service using the cached repo if it is available under ./DATA/<catalogName>/  where ./DATA should be available at the level where the service is started.

**Comment by cloudnautique** [comment]
@prachidamle, we had a packaging issue with the Rancher server container. Will be testing again in the next RC.

**Comment by cloudnautique** [comment]
@prachidamle , it is using the cached copy in RC2. 
The log levels are ERROR, can they be WARN. This is normal/defined behavior for hosts behind proxies or Airgap networks.

**Comment by vincent99** [comment]
Can we do exponential back off up to 1 check/day or something like that so this isn't spamming logs for updates that will never succeed on airgapped networks?  And reset the back off on a reload request from the UI.

**Comment by prachidamle** [comment]
@cloudnautique I can change the log levels
@vincent99 can we use the parameter "refreshInterval" for this use case? This interval can be set to 24hrs and the service will not pull often. I am wondering if for air gapped usecases, catalog service "refreshInterval" could be set higher.
Btw this parameter can be changed from cattle settings and that will reboot the catalog service

**Comment by ruimarinho** [comment]
@cloudnautique Under v1.1.4, I've mounted a host path under `/var/lib/cattle/DATA/<catalogName>` which is not a git repository, but since the catalog service fails to `git pull`, it is unable to use it.
