### ISSUE TITLE
Update ACI CNI to 5.2.3.4

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#39640]
There is ACI CNI version 5.2.3.4 available which is an upgrade to 5.2.3.2 we currently have included in KDM for RKE1 provisioned clusters.

**Comment by snasovich** [comment]
@siva-muni @snaiksat @lavanyavaddavalli , with https://github.com/rancher/kontainer-driver-metadata/pull/1017 merged, please confirm ACI CNI is working as expected in newly introduced k8s versions in on [dev-v2.7-1122-patches](https://github.com/rancher/kontainer-driver-metadata/tree/dev-v2.7-1122-patches) KDM branch.

**Comment by snaiksat** [comment]
@snasovich is there an action-item for us (meaning myself, @siva-muni, @LavanyaVaddavalli ) beyond providing answer to this question -

> please confirm ACI CNI is working as expected in newly introduced k8s versions in on [dev-v2.7-1122-patches](https://github.com/rancher/kontainer-driver-metadata/tree/dev-v2.7-1122-patches) KDM branch

**Comment by snasovich** [comment]
@snaiksat , there is an action item to confirm that ACI is working as expected on newly introduced versions since we don't have infrastructure or knowledge to test ACI CNI.

**Comment by siva-muni** [comment]
@snasovich, ACI CNI working fine with newly added k8s versions in  on [dev-v2.7-1122-patches](https://github.com/rancher/kontainer-driver-metadata/tree/dev-v2.7-1122-patches) KDM branch

**Comment by snaiksat** [comment]
Thanks @siva-muni for confirming.

@snasovich which RKE releases will these changes be available?

**Comment by snasovich** [comment]
@snaiksat , the RKE releases we do next week will include it (actual release numbers will probably be 1.4.1 and 1.3.17). These are PRs to bring in these changes to RKE: https://github.com/rancher/rke/pull/3098, https://github.com/rancher/rke/pull/3097.

**Comment by snasovich** [comment]
Closing based on the successful testing reported above.
