### ISSUE TITLE
rancher-catalog-service should support files under nested folders of a template version

### ISSUE THREAD

**Issue by prachidamle** [rancher/rancher#3965]
Changes to support reading of files under the nested folders of a template version. Thus any file under say rancher-catalog/ElasticSearch/0/foo/another.yml or rancher-catalog/ElasticSearch/0/foo/bar/some.json will be pulled and added to "files" map in the response.

**Comment by prachidamle** [comment]
This is how the "files" Map in the templateversion response will look

https://cloud.githubusercontent.com/assets/753917/13862144/90f18b66-ec4e-11e5-9822-f48a37893c20.png

then

files: {
  "frontend/frontend-controller.yaml": '...",
  "frontend/frontend-service.yaml": '...",
  "redis/redis-master-controller.yaml": '...",
  "redis/redis-master-service.yaml": '...",
  "redis/redis-slave-controller.yaml": '...",
  "redis/redis-slave-service.yaml": '...",
  "rancher-compose.yaml": '...",
}

**Comment by sangeethah** [comment]
Tested with latest build from master and rancher-catalog version - v0.6.0

Able to see additional files that were present in templates/version directory being listed in "files" field along with docker-compose.yml and rancher-compose.yml when accessing -  http://<ip>:8080/v1-catalog/templates/SANGEETHA_12345:elasticsearch:0

<img width="731" alt="screen shot 2016-03-19 at 6 18 25 pm" src="https://cloud.githubusercontent.com/assets/4266958/13902248/0be03dac-edff-11e5-942c-88a2703f60d4.png">
