### ISSUE TITLE
[BUG] Cannot access or add local cluster to Rancher

### ISSUE THREAD

**Issue by ax88008** [rancher/rancher#39655]
**Rancher Server Setup**

Rancher version: v2.6.9
Installation option (Docker install/Helm Chart): Helm chart
If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): v1.25.3+rke2r1

Cluster Type (Local/Downstream): local

Describe the bug

Seeing the following warning during normal operation of Rancher:

Installing Rancher on RKE2 we have a sequence of errors that result in being able to logon to rancher but the local cluster is not visable

1. Rancher Helm Chart throws an error relating to Kubectl version that is resoved by removing the Kubectl definition in the Chart.yaml (locally downloaded)
2. Rancher portal appears (with spinning wheel, but never proceeds
3. Using the API to change the password I am able to logon to cluster however Local cluster does not appear.
4. Trying to add the cluster throws an error that fleet-default namespace is not available.

Screenshots

![image](https://user-images.githubusercontent.com/21329801/203036974-ae038df9-3ac9-46bb-9995-cd09d62b6c31.png)

![image](https://user-images.githubusercontent.com/21329801/203037128-e5ef0623-7ec4-4284-8019-6d1e7633448d.png)

**Comment by Josh-Diamond** [comment]
@ax88008 Kubernetes 1.25 is not yet supported in Rancher

**Comment by Josh-Diamond** [comment]
Kubernetes 1.25 support may be further tracked here: https://github.com/rancher/rancher/issues/38701
