### ISSUE TITLE
Not able to start wordpress serive in k8s cluster.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#3966]
Rancher Version: v0.63.1-rc1

Docker Version:1.9.1

OS: CoreOS 899.10.0 (with KVM)

Steps to Reproduce: 

Create a Kubernetes environment.
Added 2 CoreOS hosts to this environment.
Kubernetes and Kubernetes-loadbalaner stacks start successfully.

From catalog , added "K8s Example WordPress" service.

Status for the WorrdPress container is stuck in "Waiting" state and message says "Image: wordpress is ready, container is creating"

**Comment by will-chan** [comment]
Can we re-test here?

**Comment by soumyalj** [comment]
Tested with v1.1.0-dev4-rc1. The wordpress catalog launches successfully. The containers are in running state.
