### ISSUE TITLE
HAProxy stats metrics port - requires a non-forwarding port

### ISSUE THREAD

**Issue by etlweather** [rancher/rancher#3967]
To set up HAProxy stats, I can add the following custom configuration:
```
listen stats 
bind 0.0.0.0:9000
mode http
stats enable
stats hide-version
stats realm Haproxy\ Statistics
stats uri /haproxy_stats
stats auth Username:Password
```

However, I am unable to expose the port 9000 so that the monitoring system can collect the information. 

If I have only one load balancer, then I can run a container with a link to the load balancer and I can collect the data as the container has access to the internal port 9000. 

However, in my case, I run one load balancer per host (in this case 2 hosts). So I need to be able to expose the stats port. Container link in this case does not work because the container doing the monitoring gets given one of the two load balancer container in a round-robin fashion.

Another (maybe better) approach would be to not expose the port but add sidekick capability to the load balancer service. Then I would run a collector agent attached to each load balancer instance.

Ref: https://forums.rancher.com/t/collecting-haproxy-stats-multiple-lb-container-for-the-service

**Comment by janeczku** [comment]
You should be able to achieve this just by using the internal network an DNS service discovery. But instead of using the service FQDN (`<service-name>.<stack-name>`), pass the instance FQDN (`<instance-name>.<service-name>.<stack-name>`) to your metrics collector.

For example, given a stack name `public` and load balancer service name `api-lb` you should be able to address the two instances of the load balancer like this:

> ping public_api-lb_1.api-lb.public
> ping public_api-lb_2.api-lb.public

**Comment by vincent99** [comment]
Note: in v0.63.0+ only, before that there were no DNS entries for the individual containers.

**Comment by etlweather** [comment]
Hey, that should work. I'll find a time to schedule the upgrade in the next couple of days.

**Comment by deniseschannon** [comment]
@etlweather If you still have questions after you upgrade, please re-open.

**Comment by etlweather** [comment]
Thanks all, that works!

**Comment by wcgcoder** [comment]
If anyone is arriving here who is not trying to address individual containers (like above), [a comment on another ticket demonstrates how to enable the stats backed without the `listen` directive.](url)
