### ISSUE TITLE
CIS Benchmark cannot be installed in airgapped env

### ISSUE THREAD

**Issue by doflamingo721** [rancher/rancher#39673]
**Description**:
CIS benchmark tried to load additional images via registry in an air-gapped env, despite the images being loaded into /var/lib/rancher/rke2/agent/images, it seems that they default to an always pull policy.

**Actual Behaviour**:
The install fails with the following error message in the CIS operator pod:
ErrImagePull (rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/rancher/cis-operator:v1.0.8": failed to resolve reference "docker.io/rancher/cis-operator:v1.0.8": failed to do request: Head "https://registry-1.docker.io/v2/rancher/cis-operator/manifests/v1.0.8": dial tcp: lookup registry-1.docker.io on <IPaddr>:53: no such host)

**Expected Behaviour**:
The helm chart and subsequent pulls are able to grab images loaded manually rather than forcing a registry.

SURE-5093

**Comment by doflamingo721** [comment]
@MKlimuszka Do we need to backport this in 2.6?

**Comment by MKlimuszka** [comment]
@doflamingo721 , the original reporter would prefer that if possible.

**Comment by rishabhmsra** [comment]
Validated on rancher v2.7.2-rc1 in an airgap environment
- Created a RKE1 custom cluster(1-cp, 1-e, 1-w) with k8s v1.24.8-rancher1-1 version.
- Installed CIS benchmark chart 3.0.1-rc2 version.

Result:
- Chart deployed successfully:

![cis](https://user-images.githubusercontent.com/36376154/211010563-dc78c327-49f1-439d-8242-9ed12a058689.png)

- Re-installed the chart after removing it and the images are not getting pulled again from registry as it was already available on the machine:
```
Normal | Pulled | 5 mins ago | Container image "<REDACTED>/rancher/cis-operator:v1.0.11-rc1" already present on machine
Normal | Created | 5 mins ago | Created container cis-operator
Normal | Started | 5 mins ago | Started container cis-operator
Normal | Scheduled | 5 mins ago | Successfully assigned cis-operator-system/cis-operator-68f9857f77-z8k4h to ip-<REDACTED>
```
