### ISSUE TITLE
Enhance `/meta/aksVMSizes` API with SKU details 

### ISSUE THREAD

**Issue by HarrisonWAffel** [rancher/rancher#39672]
Issues: https://github.com/rancher/rancher/issues/39458 https://github.com/rancher/rancher/issues/37847 https://github.com/rancher/dashboard/issues/7182

**Problem**
Azure features such as Availability Zones and Accelerated Networking are only supported on some VM types. Currently, the only way to determine if a VM supports a particular feature is querying the Azure API using credentials. The UI needs to enforce particular features for particular VM sizes, so as to not allow users to create invalid configurations. Unfortunately, the UI does not have access to the Azure cloud credentials, so it cannot query the Azure API to get this information.

**Describe the solution you'd like**
The API endpoint `/meta/aksVMSizes` needs to be enhanced to not only return the all VM sizes, but also their support for features such as Availability Zones and Accelerated Networking. 

**Additional context**
This endpoint is already being used by the API to get VM sizes for RKE2/K3s Azure clusters.
From what I can tell, RKE1 currently stores all VM sizes statically, node template UI may need to be updated to use this API.

**Comment by HarrisonWAffel** [comment]
The PR for this issue has been raised and approved, holding off on merging until the UI side is implemented so as to not break the Azure / AKS UI

**Comment by thaneunsoo** [comment]
Test plan can be viewed [here](https://confluence.suse.com/pages/viewpage.action?pageId=1141178915)

**Comment by thaneunsoo** [comment]
The test results can be found [here](https://confluence.suse.com/pages/viewpage.action?pageId=1141178915)
