### ISSUE TITLE
[BUG] 000 received while downloading Rancher connection information. Sleeping for 5 seconds and trying again

### ISSUE THREAD

**Issue by justSem** [rancher/rancher#39689]
**Rancher Server Setup**
- Rancher version: 2.7.0
- Installation option (Docker install/Helm Chart):
   Helm on DOKS 1.24.4
- Proxy/Cert Details: N/A

**Information about the Cluster**
- Kubernetes version: 1.24.4
- Cluster Type (Local/Downstream):
   - Local, DigitalOcean DOKS (The cluster Rancher's running on)
   - The cluster for which the node was being provisioned in: RKE2 1.24.4 running on Ubuntu 20.04 on Hetzner cloud instances
- Infrastructure Provider: Custom from Rancher's perspective, cluster involved in this error runs on Hetzner's Cloud instances.

**User Information**
- What is the role of the user logged in?: Admin

**Describe the bug**
When attemting to run Rancher's RKE2 registration script we're hit with the following errors:
```bash
root@v001:~# curl -fL https://<redacted>/system-agent-install.sh | sudo  sh -s - --server https://<redacted> --label 'cattle.io/os=linux' --token <redacted> --ca-checksum <redacted> --etcd --controlplane
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 29818    0 29818    0     0   214k      0 --:--:-- --:--:-- --:--:--  214k
[INFO]  Label: cattle.io/os=linux
[INFO]  Role requested: etcd
[INFO]  Role requested: controlplane
[INFO]  Using default agent configuration directory /etc/rancher/agent
[INFO]  Using default agent var directory /var/lib/rancher/agent
[INFO]  Determined CA is not necessary to connect to Rancher
[INFO]  Successfully tested Rancher connection
[INFO]  Downloading rancher-system-agent binary from https://<redacted>/assets/rancher-system-agent-amd64
[INFO]  Successfully downloaded the rancher-system-agent binary.
[INFO]  Downloading rancher-system-agent-uninstall.sh script from https://<redacted>/assets/system-agent-uninstall.sh
[INFO]  Successfully downloaded the rancher-system-agent-uninstall.sh script.
[INFO]  Generating Cattle ID
curl: (28) Operation timed out after 60001 milliseconds with 0 bytes received
[ERROR]  000 received while downloading Rancher connection information. Sleeping for 5 seconds and trying again
```

The new node _does_ show up in Rancher, this is the only entry regarding the node in Rancher's privisioning log:
```
Wed, Nov 23 2022 3:01:18 pm | [INFO ] configuring bootstrap node(s) custom-389531d57312: waiting for cluster agent to connect
--
Wed, Nov 23 2022 3:01:18 pm | [INFO ] provisioning done

```

**To Reproduce**

We have an existing RKE2 cluster in Rancher running on Ubuntu 20.04 nodes (nothing special installed, just as bare as they can get).
When attempting to provision extra nodes for this cluster we're getting hit with this error.

**Result**

**Expected Result**
I expected the node to be initialized in Rancher and provisioned with RKE2

**Additional context**
This bug seems related to rancher/rancher#38916

**Comment by Oats87** [comment]
Thanks for filing your issue.

Does Rancher eventually deliver the correct connection info after the timeout?

Is this consistent?

If possible, if you can enable trace logging in Rancher i.e. exec into the Rancher pods and `loglevel -set trace` them, we might be able to pin down why it's timing out. If you want to filter for logs you can grep for `rke2configserver` but that won't capture some of the errors that the code can emit.

There are a few cases where Rancher might actually miss the change event of the service account token secret, which could lead to this behavior; however, if you are consistently able to reproduce this issue then something is likely broken/not working correctly.

**Comment by justSem** [comment]
Hi,

No, Rancher doesn't seem to ever give out the correct info, the registration script is just stuck in the loop of receiving the data.
So yes, this is consistent. I've been trying to dissect the logs, but tracing generates a stupid amount of logs. I've been running the registration script in the background and provided the logs for the 2 minutes relevant around that time.

The only relevant lines containing `rke2configserver` are pasted below, the full logs can be found [here](https://pastebin.com/yiGgbJJk)

```
2022/11/28 13:29:30 [DEBUG] [rke2configserver] parsed 8635a0fa70f879d54fbd121c66416565fa99a7df173e073a3775fb623ad884c as machineID
2022/11/28 13:29:30 [DEBUG] [rke2configserver] Got / machine from provisioning SA
2022/11/28 13:29:30 [DEBUG] [rke2configserver] Got fleet-default/custom-57fc27517de6 machine from cluster token
2022/11/28 13:29:30 [DEBUG] [rke2configserver] fleet-default/custom-57fc27517de6 listed 0 planSAs
2022/11/28 13:29:30 [DEBUG] [rke2configserver] fleet-default/custom-57fc27517de6 watching for plan secret to become ready for consumption
2022/11/28 13:30:35 [DEBUG] [rke2configserver] parsed 8635a0fa70f879d54fbd121c66416565fa99a7df173e073a3775fb623ad884c as machineID
2022/11/28 13:30:35 [DEBUG] [rke2configserver] Got / machine from provisioning SA
2022/11/28 13:30:35 [DEBUG] [rke2configserver] Got fleet-default/custom-57fc27517de6 machine from cluster token
2022/11/28 13:30:35 [DEBUG] [rke2configserver] fleet-default/custom-57fc27517de6 listed 0 planSAs
2022/11/28 13:30:35 [DEBUG] [rke2configserver] fleet-default/custom-57fc27517de6 watching for plan secret to become ready for consumption
2022/11/28 13:33:31 [DEBUG] [rke2configserver] parsed 8635a0fa70f879d54fbd121c66416565fa99a7df173e073a3775fb623ad884c as machineID
2022/11/28 13:33:31 [DEBUG] [rke2configserver] Got / machine from provisioning SA
2022/11/28 13:33:31 [DEBUG] [rke2configserver] Got fleet-default/custom-57fc27517de6 machine from cluster token
2022/11/28 13:33:31 [DEBUG] [rke2configserver] fleet-default/custom-57fc27517de6 listed 0 planSAs
2022/11/28 13:33:31 [DEBUG] [rke2configserver] fleet-default/custom-57fc27517de6 watching for plan secret to become ready for consumption
2022/11/28 13:37:56 [DEBUG] [rke2configserver] parsed 8635a0fa70f879d54fbd121c66416565fa99a7df173e073a3775fb623ad884c as machineID
2022/11/28 13:37:56 [DEBUG] [rke2configserver] Got / machine from provisioning SA
2022/11/28 13:37:56 [DEBUG] [rke2configserver] Got fleet-default/custom-57fc27517de6 machine from cluster token
2022/11/28 13:37:56 [DEBUG] [rke2configserver] fleet-default/custom-57fc27517de6 listed 0 planSAs
2022/11/28 13:37:56 [DEBUG] [rke2configserver] fleet-default/custom-57fc27517de6 watching for plan secret to become ready for consumption
2022/11/28 13:40:06 [DEBUG] [rke2configserver] parsed 8635a0fa70f879d54fbd121c66416565fa99a7df173e073a3775fb623ad884c as machineID
2022/11/28 13:40:06 [DEBUG] [rke2configserver] Got / machine from provisioning SA
2022/11/28 13:40:06 [DEBUG] [rke2configserver] Got fleet-default/custom-57fc27517de6 machine from cluster token
2022/11/28 13:40:06 [DEBUG] [rke2configserver] fleet-default/custom-57fc27517de6 listed 0 planSAs
2022/11/28 13:40:06 [DEBUG] [rke2configserver] fleet-default/custom-57fc27517de6 watching for plan secret to become ready for consumption
2022/11/28 13:42:16 [DEBUG] [rke2configserver] parsed 8635a0fa70f879d54fbd121c66416565fa99a7df173e073a3775fb623ad884c as machineID
2022/11/28 13:42:16 [DEBUG] [rke2configserver] Got / machine from provisioning SA
2022/11/28 13:42:16 [DEBUG] [rke2configserver] Got fleet-default/custom-57fc27517de6 machine from cluster token
2022/11/28 13:42:16 [DEBUG] [rke2configserver] fleet-default/custom-57fc27517de6 listed 0 planSAs
2022/11/28 13:42:16 [DEBUG] [rke2configserver] fleet-default/custom-57fc27517de6 watching for plan secret to become ready for consumption
```

**Comment by Oats87** [comment]
@justSem do you know what the rest of the conditions in Rancher are after it finishes provisioning your bootstrap node? Are you able to "explore" the cluster? 

There is a problem that can occur where the CAPI machine controller does not take ownership of the RKEBootstrap resource that correlates to your new machines in question, but I have only seen this happen after the cluster-agent disconnects from the cluster. Normally, the cluster-agent should reconnect and the CAPI controllers should resume reconciliation. That is related to https://github.com/rancher/rancher/issues/41080 

If you are still able to reproduce this, please let me know.

**Comment by ShubhamDesai17** [comment]
Rancher Version: v2.11.3
Installation Method: Helm
Node OS: Ubuntu

**Summary**
Node cannot join cluster. Stuck at WaitingForDataSecret. Rancher UI shows cluster in Updating state.

**Steps to Reproduce**
1. Create a new node with etcd and controlplane or worker role
2. Use the generated command to register the node.
3. Observe the logs from the node.

**Actual Result**

[INFO]  Label: cattle.io/os=linux
[INFO]  Role requested: etcd
[INFO]  Role requested: controlplane
[INFO]  Using default agent configuration directory /etc/rancher/agent
[INFO]  Using default agent var directory /var/lib/rancher/agent
[INFO]  Determined CA is not necessary to connect to Rancher
[INFO]  Successfully tested Rancher connection
[INFO]  Downloading rancher-system-agent binary from https://<redacted>/assets/rancher-system-agent-amd64
[INFO]  Successfully downloaded the rancher-system-agent binary.
[INFO]  Downloading rancher-system-agent-uninstall.sh script from https://<redacted>/assets/system-agent-uninstall.sh
[INFO]  Successfully downloaded the rancher-system-agent-uninstall.sh script.
[INFO]  Generating Cattle ID
curl: (28) Operation timed out after 60001 milliseconds with 0 bytes received
[ERROR]  000 received while downloading Rancher connection information. Sleeping for 5 seconds and trying again

**Rancher UI shows:**

Node: WaitingForDataSecret
Cluster: Updating

**Expected Result**
Node should join the cluster successfully and appear as Active in the UI.

**Additional Information**
curl -v https://<rancher-url>/v3/connect/agent
> HTTP/2 401 
Unauthorized
