### ISSUE TITLE
[BUG] rancher-istio 100.3.0+up1.13.3: Remove istiod-remote chart to align with upstream, istiodRemote.enabled: true causes installation failure

### ISSUE THREAD

**Issue by vardhaman22** [rancher/rancher#39680]
Installations and upgrades fail when the `istiodRemote.enabled` chart value is set to `true`.

**Environment:** 
Rancher Cluster: v1.23.8+rke2r1 
Rancher Version: v2.6.6
Number of nodes: 2
Node OS version: Fedora 36

Downstream Cluster:
Number of Downstream clusters: 1
Node OS: Fedora 36
RKE/RKE2/K3S version: rke2 
Kubernetes version: v1.23.7
CNI: calico

****Other**:**
Underlying Infrastructure: VMWare

**Troubleshooting steps:**

Reproduced the issue in a lab environment.
Researched relevant issues and PRs on GitHub

**Repro steps**:

Attempt an installation or update of the rancher-istio chart on any downstream cluster
Click 'Edit YAML' and set:
```
 istiodRemote:
  enabled: true
  ```
Receive the following error: 
```
setting up kubeconfig
Switched to context "rancher-istio-context".
starting istioctl commands
client version: 1.13.3
control plane version: 1.13.3
creating istio system using overlay
running istioctl upgrade
Error: failed to install manifests: errors occurred during operation: path [:].spec.template.spec.tolerations has an unexpected first element [:] in OverlayK8sSettings
error found during istioctl upgrade
```
**Workaround:**
Is workararound available and implemented? : NO

**Actual behavior**: istio installer job terminating with error
```Error: failed to install manifests: errors occurred during operation: path [:].spec.template.spec.tolerations has an unexpected first element [:] in OverlayK8sSettings```

**Expected behavior:** chart should be deployed  successfully.

**Files, logs, traces**: N/A

**Additional notes:**

**Comment by rishabhmsra** [comment]
Closing this, since the original issue where `istiodRemote.enabled: true` was causing the installation failure is fixed and chart is getting installed successfully now.

Also tracking the istioctl-installer error as mentioned [here](https://github.com/rancher/rancher/issues/39680#issuecomment-1340917354) in a separate issue: https://github.com/rancher/rancher/issues/39938
