### ISSUE TITLE
Rancher UI opening too slowly because GET /v1/schemas data is too heavy

### ISSUE THREAD

**Issue by oingooing** [rancher/rancher#39701]
**Versions**
Rancher v2.6.7

**Is your feature request related to a problem? Please describe.**
hi,
My Rancher UI opening too slowly.
I think, the **/v1/schemas API** response data is too big that cause slowly.
When i checking, the data size is **304KB** and took **2.3 minute** to complete.
And The number of data in array is **2679**.

/v1/schemas api call is really need to rancher ui?
How can i reduce the UI opening time?

thank you

**Comment by u001201** [comment]
any update on this ? I'm facing the same problem
