### ISSUE TITLE
[BUG] CIS Scan rke2-cis-1.6-profile-permissive displays false warning at 4.1.6

### ISSUE THREAD

**Issue by vardhaman22** [rancher/rancher#39704]
**Rancher Server Setup**
- Rancher version: 2.6.6
- Installation option (Docker install/Helm Chart): Docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.23.7+rke2r2
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Infrastructure Provider (AWS EC2)

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): Admin
  - If custom, define the set of permissions:

**Describe the bug**

Test 4.1.6 reports a warn that --kubeconfig kubelet.conf file ownership is not set to root:root.
However, sshing in the machine the file is root:root

**To Reproduce**

Installed rancher using: https://github.com/axeal/tf-do-rke
Deployed a downstream rke2 cluster on the UI
Installed the CSI Operator
Run scan for profile rke2-cis-1.6-profile-permissive

**Result**
Test 4.1.6 reports a warn that --kubeconfig kubelet.conf file ownership is not set to root:root.

**Expected Result**

Test should pass

**Comment by vardhaman22** [comment]
This issue does not occur in CIS benchmark chart 2.1.0 . The state of 4.1.6 test is pass.
Testing Steps:
Setup: 
    Rancher: v2.6.6
    Cluster:  Downstream RKE2 nodedriver
    Kubernetes version: v1.23.14+rke2r1

Repro Steps:
1. install CIS benchmark <v2.1.0 (2.0.3 or 2.0.4)
2. Create a scan with rke2-cis-1.6-profile-permissive.

Result : Warn State for 4.1.6 test.

3. upgrade the chart to v2.1.0 
4. Create a scan with rke2-cis-1.6-profile-permissive.

Result : Pass State for 4.1.6 Test.

**Comment by vivek-infracloud** [comment]
Validated the issue on rancher v2.6.6 with CIS version v2.1.0

validations steps followed
1. Created a rancher server v2.6.6
2. Provisioned a RKE2 node driver cluster v1.23.14+rke2r1
3. Installed a CIS benchmark v2.0.4
4. Created a scan with **rke2-cis-1.6-profile-permissive**.
Scan results in warning state for 4.1.6

5. Upgraded the chart to v2.1.0
6. Created a scan with **rke2-cis-1.6-profile-permissive.**
Scan result for 4.1.6 shows pass state.

Hence issue is not active on CIS benchmark version v2.1.0. Closing the issue.
