### ISSUE TITLE
launchConfig.requestedHostId isn't id-obfuscated

### ISSUE THREAD

**Issue by vincent99** [rancher/rancher#3970]
The launchConfig.requestedHostId field comes back as a raw int ID instead of a string.  This breaks re-selecting the same host when cloning/upgrading the UI because the value doesn't match any hosts (rancher/rancher#3707)

**Comment by deniseschannon** [comment]
Could this be the same issue that's happening for https://github.com/rancher/rancher/issues/3929?

**Comment by alena1108** [comment]
@deniseschannon  yes. Closing in favor of https://github.com/rancher/rancher/issues/594
