### ISSUE TITLE
[RFE] Add bash_completion the the k alias in rancher shell

### ISSUE THREAD

**Issue by KevinJoiner** [rancher/rancher#39714]
**Is your feature request related to a problem? Please describe.**
we currently enable bash autocompletion for kubectl but not the corresponding k alias.

**Describe the solution you'd like**
Add bash completion for the k alias to the shell's .bashrc

**Comment by KevinJoiner** [comment]
## Root Cause
Bash completion in the shell's .bashrc was only for kubectl, not the k alias.

## What was fixed, or what change has occurred
Updated the .bashrc in the shell to include completion for the k command.

## Areas or cases that should be tested
### Users can still successfully open a shell to cluster through the rancher UI.
###  The alias k has auto-completion.
1.  Open a new shell to a cluster
2. Type `k`, then press `tab` twice.
3. Verify that the shell gives valid resource suggestions.
```
annotate       apply          autoscale      completion     cp             delete         drain          explain        help           logs           plugin         replace        scale          top            wait           
api-resources  attach         certificate    config         create         describe       edit           expose         kustomize      options        port-forward   rollout        set            uncordon       
api-versions   auth           cluster-info   cordon         debug          diff           exec           get            label          patch          proxy          run            taint          version      
```

## Are the repro steps accurate/minimal?
1.  Open a new shell to a cluster
2. Type `k`, then press `tab`.
3. Verify that the shell gives file names for suggestions
 ```
.bashrc       .kube/        kustomize.sh
```

**Comment by macedogm** [comment]
PRs:
- 2.7 - https://github.com/rancher/rancher/pull/39715
- 2.6 - https://github.com/rancher/rancher/pull/39695
