### ISSUE TITLE
[external-dns] Environments setup with special characters including spaces should not be passed to route53/any dns provider

### ISSUE THREAD

**Issue by agalpin** [rancher/rancher#3972]
Rancher Version: 0.59.1

Docker Version: 1.10.2

OS: Ubuntu

Steps to Reproduce: 
1) Create an Environment in rancher with a special character in it (i had a space)
2) create a Route53 Service for registering your domains automatically
3) create a service with an exposed port

Results: 
FQDN is not registers as you will get an invalid character response from Route53

Expected:
The FQDN to be registered replacing invalid characters with a valid one so Route53 doesn't complain about invalid characters

**Comment by janeczku** [comment]
https://github.com/rancher/external-dns/pull/48

**Comment by janeczku** [comment]
Validate using Route53 template v0.6.0 from rancher/rancher-catalog:qa

**Comment by galal-hussein** [comment]
@janeczku Tested with the mentioned catalog and the invalid characters are replaced with dashes.
