### ISSUE TITLE
[Feature] Adjust Rancher helm chart to allow disabling of PSPs

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#39734]
Epic: https://github.com/rancher/rancher/issues/38701
SURE-5624

Need to adjust the rancher chart to handle this PSP existing, which right now you can't disable: https://github.com/rancher/rancher/blob/release/v2.7/chart/templates/post-delete-hook-psp.yaml
There might be other places as well. 
Note that this has nothing to do with feature charts, only the rancher chart itself.

**Comment by maxsokolovsky** [comment]
## QA Testing
Ensure the following configurations produce no errors on downstream cluster provisioning or any unusual error messages in the local cluster's logs. A downstream v1.24 cluster always has PSP's enabled:

local 1.25 downstream 1.25
local 1.25 downstream 1.24
local 1.24 downstream 1.25
local 1.24 downstream 1.24

**Comment by sowmyav27** [comment]
This isn't ready for test yet. this will need a Rancher RC to test

**Comment by jiaqiluo** [comment]
Can be validated in Rancher [v2.7.2-rc1](https://github.com/rancher/rancher/releases/tag/v2.7.2-rc1)

**Comment by anupama2501** [comment]
QA to validate:
1. Install rancher on RKE1 k8s 1.24 hardened cluster - have a hardened PSP 1.24 RKE2 custom cluster - c1 and a non hardened 1.25 k3s node driver cluster - c2 , psp 1.23 rke1 node driver non hardened - c3
2. Uninstall rancher on RKE1 k8s 1.24 local cluster from step1 by running the [cleanup](https://ranchermanager.docs.rancher.com/faq/rancher-is-no-longer-needed) script 
3. Install rancher on k8s 1.25 RKE2 cluster non hardened cluster - Have a hardened PSP 1.24 k3s custom cluster - c1, non hardened 1.25 RKE1 node driver- c2
4. Uninstall rancher on RKE2 local cluster from step3 by running the [cleanup]

**Comment by sowmyav27** [comment]
Wait until this is fixed - https://github.com/rancher/rancher/issues/40327 since this issue talks about reverting the above linked PR

**Comment by cbron** [comment]
Superceded by: https://github.com/rancher/rancher/issues/40327
