### ISSUE TITLE
kubernetes controller and agent keeps restarting

### ISSUE THREAD

**Issue by tyhoho** [rancher/rancher#3974]
Rancher Version: 0.63.1

Docker Version:1.10.2

OS: CentOs 7

Steps to Reproduce: 1. change to Kubernetes environment 2. add a host

Results:  The kubernetes controller and agents keeps restarting again and again.

** error logs in controller: **
E0315 17:55:20.929428       1 nodecontroller.go:227] Error monitoring node status: couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
E0315 17:55:20.929855       1 controllermanager.go:233] Failed to get api versions from server: unexpected error: invalid character '<' looking for beginning of value

**error logs in agent：**
time="2016-03-15T17:51:18Z" level=info msg="Connecting to event stream." url="ws://master/api/v1/services?watch=true" 
time="2016-03-15T17:51:18Z" level=warning msg="Error connecting to ws://master/api/v1/services?watch=true. Try 0 of 6. Will wait 1 seconds and try again. Error: &errors.errorString{s:\"websocket: bad handshake\"}" 
time="2016-03-15T17:51:18Z" level=info msg="Initializing event router" workerCount=50 
time="2016-03-15T17:51:18Z" level=info msg="Connection established" 
time="2016-03-15T17:51:19Z" level=warning msg="Error connecting to ws://master/api/v1/services?watch=true. Try 1 of 6. Will wait 2 seconds and try again. Error: &errors.errorString{s:\"websocket: bad handshake\"}" 
time="2016-03-15T17:51:21Z" level=warning msg="Error connecting to ws://master/api/v1/services?watch=true. Try 2 of 6. Will wait 4 seconds and try again. Error: &errors.errorString{s:\"websocket: bad handshake\"}" 
time="2016-03-15T17:51:25Z" level=warning msg="Error connecting to ws://master/api/v1/services?watch=true. Try 3 of 6. Will wait 8 seconds and try again. Error: &errors.errorString{s:\"websocket: bad handshake\"}" 
time="2016-03-15T17:51:26Z" level=info msg="Received event: Name: compute.instance.providelabels, Event Id: 64185e51-f862-4600-92e3-7380231ab730, Resource Id: 1ihm51" 
time="2016-03-15T17:51:33Z" level=warning msg="Error connecting to ws://master/api/v1/services?watch=true. Try 4 of 6. Will wait 16 seconds and try again. Error: &errors.errorString{s:\"websocket: bad handshake\"}" 
time="2016-03-15T17:51:39Z" level=info msg="Received event: Name: compute.instance.providelabels, Event Id: 84a82519-4cd3-44a4-8ab7-093f7d43dfef, Resource Id: 1ihm51"

Expected:
The host can be added successfully and the kubernetes containers can be started successfully.

**Comment by sangeethah** [comment]
Rancher Version: 0.63.1
Docker version 1.10.3, build 20f81dd
CentOS Linux release 7.2.1511 (Core) 

I am able to add a host successfully to a kubernetes environment.
Controller and agent start successfully.
I am also able to deploy service - "K8s Example Guestbook" from catalog successfully.

**Comment by deniseschannon** [comment]
@tyhoho Do you have a fresh setup or an upgraded setup?

Did you add a new k8s environment or did you change the default one to k8s?

**Comment by tyhoho** [comment]
@deniseschannon I used to have an old version of rancher, then I stopped and deleted the old version rancher containers, and begin to install the new version.

After installing, I add a K8s env, and set it as default one, and switch current env to it.

ps: uname -a.
Linux localhost 3.10.0-327.10.1.el7.x86_64 #1 SMP Tue Feb 16 17:03:50 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by deniseschannon** [comment]
@tyhoho Would you be willing to test out v1.0.0-rc1 to see if you are still facing the same k8s issues? We are preparing to GA and would love our community to test out our release candidate (esp if they are doing a fresh install). 

We haven't been able to reproduce your issue.

**Comment by deniseschannon** [comment]
@tyhoho We've made a lot of improvements in k8s in the last couple of releases. If you could test out v1.1.0-dev2 and see if you still have issues, then please re-open.
