### ISSUE TITLE
Perf UI issues

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#3976]
While running the perf tests these items were found in the UI:

- [x] Services can not be clicked on. The number of requests to all the hosts takes longer then 30 s. 
     It does a lot of GET requests for hosts/<id>/ipaddresses on infra page is expensive. Looks like its an expensive API call.

- [ ] between 600-700 hosts UI fails to load.

- [x] 500 hosts with a 20 service with 20 containers will not scale from the UI when going through edit. Entity to large. Also can not press + sign

**Comment by vincent99** [comment]
Entity too large fixed.. the other two require API changes to tell me what host a container is on without n+1 calls, and to respond faster to `hosts?include=instances` faster in general.

**Comment by ibuildthecloud** [comment]
@vincent99 I increased the limit to 10000 and also you can just set -1 for everything.  Beyond that I'm not too sure how to make `hosts?include=instances`.  I am sending megabytes of data....

**Comment by vincent99** [comment]
More limit doesn't really help.. It's taking 30 sec and hitting the UI timeout at 30s with 500-600 hosts.

For the other part I need a [primary]HostId field on container so I don't have to look them all up by n+1 link follows.  Then I could probably actually get rid of include=instances,.

**Comment by vincent99** [comment]
Though I will use -1 to fix depagination issues until API v2

**Comment by vincent99** [comment]
Changed to limit=-1, and to use the hostId on container  (which fixes the n+1 calls on Services)
