### ISSUE TITLE
Upgrade "Alerting drivers " chart version to the newest version

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#39784]
Upgrade "Alerting drivers " chart version to the newest version, which at the time of making this ticket is 3.17.9

**Comment by vardhaman22** [comment]
updated sachet to [0.3.1](https://github.com/messagebird/sachet/releases/tag/0.3.1) and prom2teams to [4.2.0](https://github.com/idealista/prom2teams/releases/tag/4.2.0)

**Comment by rishabhmsra** [comment]
Validated on rancher v2.7-head(8062f1e)
- alerting-drivers-sachet is at version `0.3.1`
- alerting-drivers-prom2team is at version `4.2.0`

![versions](https://user-images.githubusercontent.com/36376154/211306313-6006b12c-54bb-4477-ac6f-c9525de4fdc0.png)

**Comment by rishabhmsra** [comment]
Validated on rancher v2.7-head(https://github.com/rancher/rancher/commit/8062f1e3ab7bff870dfab195ff699a308644168a)
- alerting-drivers-sachet is at version `0.3.1`
- alerting-drivers-prom2team is at version `4.2.0`

![versions](https://user-images.githubusercontent.com/36376154/211306727-b116d34a-3b95-4b08-9ecf-0000ec90da47.png)
