### ISSUE TITLE
1.25 RKE2 and K3s version in Rancher KDM

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#39795]
Introduce RKE2/k3s 1.25 version in Rancher KDM

**Comment by rancher-max** [comment]
K3s KDM PR: https://github.com/rancher/kontainer-driver-metadata/pull/1038

**Comment by rancher-max** [comment]
RKE2 KDM PR: https://github.com/rancher/kontainer-driver-metadata/pull/1045

**Comment by sowmyav27** [comment]
**On 2.7-head commit id: `65089ee`**

- `1.25.5+rke2r1` and `1.25.5+k3s1` are available.
- Able to provision clusters and upgrade from 1.24 to 1.25 successfully.
