### ISSUE TITLE
[BUG] app catalog does not list chart vershttps://github.com/rancher/rancher-docs/issues/512ions that follow semver2.0

### ISSUE THREAD

**Issue by jsmonet** [rancher/rancher#39792]
**Rancher Server Setup**
- Rancher version: 2.6.6 and 2.7
- Installation option (Docker install/Helm Chart):
   - helm chart on gke 1.22.15-gke100, rke 1.20, docker locally, same behavior regardless of where it is installed
- Proxy/Cert Details: no proxies, LE certs and wildcard certs depending on the install

**Information about the Cluster**
- Kubernetes version: v1.23.7+k3s1
- Cluster Type (Local/Downstream):
   - downstream, imported, running on vm

**User Information**
- What is the role of the user logged in? admin

**Describe the bug**
When adding a catalog to a cluster, either by terraform or by using the console, Cluster Management -> click explore -> click "apps" on the left colume -> click repositories -> add repository, the addition of the repo succeeds, but my prerelease chart versions, denoted by a 0.0.0-dev.hash chart version, do not get listed when I subsequently go to "Charts" and try installing. My stable channel chart versions (simple semvar n.n.n versions) list fine, and if I swap the "-" for "+" as seen with "0.0.0+dev.hash", the chart versions are listed. 

The issue here is, the docs make no concrete mention that this can only take "+" for suffixing versions, but do state they follow semver 2.0, which explicitly permits "-" suffixing as previously noted. 

**To Reproduce**
Create a chart for your catalog, give it a version of any valid semver, but with the "-dev.ab124f" suffix, and push to your chart repo. Explicit example: version would be "0.0.0-dev.ab124f
Additionally, modify the version of that pushed chart to "0.0.0+dev.12ab4f" (hash changed for sake of differentiation)

Now refresh the catalog and look at your chart's available versions

**Result**
Only the version with the "+" in the suffix is displayed

**Expected Result**
It should, as the legacy catalog permitted, permit and display charts with prerelease suffixes containing "-". In short, both
"0.0.0-dev.ab124f"
and
"0.0.0+dev.12ab4f"
should now be listed in the available versions.

**Additional context**
I believe this is in line with the request on this issue https://github.com/rancher/rancher/issues/24863 to permit the semver-compliant plus sign for suffixed versions.

**Comment by jsmonet** [comment]
Perhaps some additional context, this is hard-blocking us from getting to 2.7 where the legacy catalogs, that still work, are no longer available for new imported clusters.

Some additional odd behavior I've found is that I can push a number of chart versions that are ignored, but then push something like "0.0.1" and a number of other, previously-pushed chart versions now show up in the available versions for that chart.

I've been comparing my prerelease chart versions with the semver lib it _appears_ to be in use and everything checks out, so I'm at a bit of a loss right now.

**Comment by nicholasSUSE** [comment]
Hello @jsmonet I have investigated the issue and it is not a bug, just a lack of documentation.
Please take a look at the issue I opened for the documentation team and I believe your problem will be solved.

https://github.com/rancher/rancher-docs/issues/512
