### ISSUE TITLE
[BUG] [QA Automaton] Skip PSP-related test on cluster 1.25 and above 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#39804]
Related issue: 
https://github.com/rancher/rancher/issues/38701

Problem:
QA test case related to or using `Pod Security Policy` failed after bumping the local cluster k8s to 1.25. 
It is expected because the PSP is removed from the k8s 1.25 cluster API. 

Possible fix:
The fix could be skipping those test cases when the clutter version is >= 1.25

**Comment by markusewalker** [comment]
Draft PR that contains the local fix: https://github.com/rancher/rancher/pull/39809/. Once the local fix is cherry-picked, I'll close the draft PR as it was for testing purposes only.

**Comment by markusewalker** [comment]
Closing this issue as this has been resolved.
