### ISSUE TITLE
Upgrade Logging to 3.17.9

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#39802]
Upgrade Logging to 3.17.9 or the newest version

**Comment by stormqueen1990** [comment]
PR was merged earlier today.

**Comment by AndrewHoffmanQA** [comment]
per meeting, QA will check and confirm this newest version of logging is available in 2.7head

**Comment by ronhorton** [comment]
**PASS**
Confirmed in 2.7-head commit ID 48d1f8e  - 
`rancher-logging:101.1.0+up3.17.10` installed without errors
