### ISSUE TITLE
[BUG] Fleet upgrade failing with Rancher 2.7

### ISSUE THREAD

**Issue by jonathon2nd** [rancher/rancher#39822]
**Rancher Server Setup**
- Rancher version: v2.7.0
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1 v1.24.2	

- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.24.2	
- Cluster Type (Local/Downstream): Local
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Admin

**Describe the bug**

Upon running `helm upgrade rancher rancher-stable/rancher --namespace cattle-system --set hostname=HOSTNAME` It seems like there is a problem with one of the jobs for upgrading fleet.

**To Reproduce**

Upgrade Rancher to 2.7. No other actions taken.

**Result**
Logs from helm operation
```
helm upgrade --force-adopt=true --history-max=5 --install=true --namespace=cattle-fleet-system --reset-values=true --timeout=5m0s --values=/home/shell/helm/values-fleet-101.0.0-up0.5.0.yaml --version=101.0.0+up0.5.0 --wait=true fleet /home/shell/helm/fleet-101.0.0-up0.5.0.tgz
Error: UPGRADE FAILED: YAML parse error on fleet/templates/deployment.yaml: error converting YAML to JSON: yaml: line 27: did not find expected key
```
Error from rancher pod
```
2022/12/08 16:53:26 [ERROR] Failed to install system chart fleet: failed to install , pod cattle-system/helm-operation-6kg6j exited 123
```

**Expected Result**

Not have any pod errors after upgrade.

**Screenshots**

![image](https://user-images.githubusercontent.com/52681917/206513838-1faf3685-c4eb-42be-8364-9b605c256cdb.png)
All errors are for the same command.

**Additional context**

I have attempted to disable fleet in the past, as we do not use it. But it is persistent on running.
![image](https://user-images.githubusercontent.com/52681917/206514037-5c1c5193-c2e9-45fc-b5ae-4073d15695be.png)

**Comment by jonathon2nd** [comment]
Attempting to disable again after doing RKE upgrade to 1.4.0
![image](https://user-images.githubusercontent.com/52681917/206517270-7500acca-66ce-4d06-8ff1-4d61ea337eb2.png)
After rancher restart
![image](https://user-images.githubusercontent.com/52681917/206517803-0b953aaa-5883-4a02-9674-a557c3324b0b.png)

And boy is it not happy. All the errors are the same
```
Thu, Dec 8 2022 9:02:58 am | helm upgrade --force-adopt=true --history-max=5 --install=true --namespace=cattle-fleet-system --reset-values=true --timeout=5m0s --values=/home/shell/helm/values-fleet-101.0.0-up0.5.0.yaml --version=101.0.0+up0.5.0 --wait=true fleet /home/shell/helm/fleet-101.0.0-up0.5.0.tgz
Thu, Dec 8 2022 9:02:59 am | Error: UPGRADE FAILED: YAML parse error on fleet/templates/deployment.yaml: error converting YAML to JSON: yaml: line 27: did not find expected key
```

![image](https://user-images.githubusercontent.com/52681917/206518042-03ed9413-9fe4-4078-a0aa-2e6f5b9b4a89.png)

**Comment by jonathon2nd** [comment]
Same thing happens when I try and manually upgrade it
![image](https://user-images.githubusercontent.com/52681917/206520449-d43d002e-ce13-48d2-9d1c-15deec2f8b85.png)

**Comment by jonathon2nd** [comment]
I wish I had a debug flag here :sob:
![image](https://user-images.githubusercontent.com/52681917/206520974-ef48bb51-9e1a-4169-a0d4-50668a7ab5e6.png)

**Comment by onpaws** [comment]
Similar experience here :(

Not sure how we best to point Helm to [this](https://github.com/rancher/fleet/issues/1166#issuecomment-1355293061)  but seems  worth trying

**Comment by sarg3nt** [comment]
This seems to be the case for a brand new install as well.  Fleet does not install and startup gets stuck. 
This is a single node install as a Docker container for testing purposes.
I'm assuming it will time out and continue at some point, but so far it's been looping.  I'll continue to wait to see if it ever does finish.
See screenshot for details
![image](https://user-images.githubusercontent.com/3372486/211889421-0b97e144-081c-4ce5-a05d-84a2490b2744.png)

**Comment by michieldeg** [comment]
We are also experiencing this issue, in both 2.7.0 and 2.7.1
The issue seems to this part of the container spec in the deployment template:

```
        command:
        - fleetcontroller
        {{- if .Values.debug }}
        - --debug
        - --debug-level
        - {{ quote .Values.debugLevel }}
        {{- else }}
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        {{- end }}
        {{- if not .Values.gitops.enabled }}
        - --disable-gitops
        {{- end }}
```

when `.Values.debug` is `false` and `.Values.gitops.enabled` is also false it gets templated into

```
        command:
        - fleetcontroller
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        - --disable-gitops
```

instead of 

```
        command:
        - fleetcontroller
        - --disable-gitops
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
```

**Comment by jonathon2nd** [comment]
Seems like fleet has a [fix](https://github.com/rancher/fleet/issues/1166#issuecomment-1404759135). Not available for Rancher [2.7.1](https://github.com/rancher/rancher/releases/tag/v2.7.1), upgrade only brings it to 101.0.1+up0.5.1

**Comment by sass1997** [comment]
I have the same issue after I upgraded to 2.6.10. Any plans to also fix this over there?

**Comment by vc43** [comment]
I had the same problem with 2.6.x and fixed it by installing the plugin `continuous-delivery`. After that, the `fleet` chart was successfully installed.

**Comment by gchait** [comment]
Any plan to fix this issue in 2.7.2? We are currently stuck on 2.6.9 because of this.
Would also like an option to disable fleet completely without Rancher crashing and enabling it again.

**Comment by jonathon2nd** [comment]
Don't see this listed in https://github.com/rancher/rancher/releases/tag/v2.7.2 :sob:

**Comment by bryanasdev000** [comment]
> Don't see this listed in https://github.com/rancher/rancher/releases/tag/v2.7.2 sob

Did a update from 2.7.0 with:

```
    extraEnv:
    - name: CATTLE_FEATURES
      value: "istio-virtual-service-ui=false,harvester=false,rke2=false,token-hashing=true,continuous-delivery=false"
``` 

as helm values and seems to be working now.

**Comment by jonathon2nd** [comment]
Upgrading to 2.7.2 with no other action fixed it for me.

**Comment by jonathon2nd** [comment]
WARNING!

DO NOT DELETE FLEET IN IT'S ENTIRETY!
https://github.com/rancher/rancher/issues/31044#issuecomment-834023763

Unless you want to waste a bunch of your time fixing things.
