### ISSUE TITLE
Switching to another service from dropdown menu doesn't work

### ISSUE THREAD

**Issue by xaka** [rancher/rancher#3983]
Rancher Version: 0.63

-

Here are screenshots and JS error in console:

<img width="431" alt="screen shot 2016-03-15 at 6 23 53 pm" src="https://cloud.githubusercontent.com/assets/504813/13799346/9c7cf2a0-eadb-11e5-9aa3-8c957bb74440.png">

<img width="1440" alt="screen shot 2016-03-15 at 6 24 38 pm" src="https://cloud.githubusercontent.com/assets/504813/13799349/a1630714-eadb-11e5-9cd8-469ffef97cb8.png">

**Comment by deniseschannon** [comment]
Reproduced in v0.63.1.

**Comment by tfiduccia** [comment]
Version - master UI 3/17
Verified fixed
