### ISSUE TITLE
 [Istio] Check for PSP compatibility in target cluster

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#39847]
Parent ticket: https://github.com/rancher/rancher/issues/39366

Kubernetes 1.25 drops support for PSP, so additional checks need to be added.

Rancher team 3 is following the proposal outlined in "Kubernetes v1.25 PSP to PSA migration proposal document"

Every chart that ships with a PSP must be changed to add a new condition checking for the PSP capability in the target cluster:

**Capabilities check for Helm**

```{{- if .Capabilities.APIVersions.Has "policy/v1beta1/PodSecurityPolicy" }}```

This change allows the charts to still work with PSPs in Kubernetes versions prior to v1.25, and work in Kubernetes v1.25 or higher by skipping installation of PSPs.

If a cluster role in a chart contains PSP's along with other permissions extra work may be needed to achieve the intended behavior of that role.

**Comment by rishabhmsra** [comment]
Re-opening the issue

Validated on rancher v2.7-head(8062f1e)
- Fresh install checks - PASS
  - On v1.25.5-rancher1-1, istio `101.1.1+up1.15.3` installed successfully and P1 scenarios also passed.

- Upgrade checks - FAIL
  - Created a node driver, k8s v1.24.8-rancher1-1 cluster. 
  - Installed istio `101.0.0+up1.14.3` version. 
  - Upgraded the cluster to k8s v1.25.5-rancher1-1.
  - Upgraded the istio chart to version `101.1.1+up1.15.3` but it failed with below error:
```
helm upgrade --history-max=5 --install=true --namespace=istio-system --timeout=10m0s --values=/home/shell/helm/values-rancher-istio-101.1.1-up1.15.3.yaml --version=101.1.1+up1.15.3 --wait=true rancher-istio /home/shell/helm/rancher-istio-101.1.1-up1.15.3.tgz
Error: UPGRADE FAILED: unable to build kubernetes objects from current release manifest: [resource mapping not found for name: "kiali-psp" namespace: "istio-system" from "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
ensure CRDs are installed first, resource mapping not found for name: "rancher-istio-tracing" namespace: "istio-system" from "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
ensure CRDs are installed first, resource mapping not found for name: "psp-istio-cni" namespace: "istio-system" from "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
ensure CRDs are installed first, resource mapping not found for name: "istio-installer" namespace: "istio-system" from "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
ensure CRDs are installed first, resource mapping not found for name: "istio-psp" namespace: "istio-system" from "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
ensure CRDs are installed first]
```

**Comment by mitulshah-suse** [comment]
Pending on https://github.com/rancher/rancher/pull/40104

**Comment by mitulshah-suse** [comment]
Closing this issue since approach for this setup has been changed. Refer to https://github.com/rancher/rancher/issues/40331 for further details
