### ISSUE TITLE
[Monitoring] Check for PSP compatibility in target cluster 

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#39846]
Parent ticket: https://github.com/rancher/rancher/issues/39366

Kubernetes 1.25 drops support for PSP, so additional checks need to be added.

Rancher team 3 is following the proposal outlined in "Kubernetes v1.25 PSP to PSA migration proposal document"

Every chart that ships with a PSP must be changed to add a new condition checking for the PSP capability in the target cluster:

**Capabilities check for Helm**

```{{- if .Capabilities.APIVersions.Has "policy/v1beta1/PodSecurityPolicy" }}```

This change allows the charts to still work with PSPs in Kubernetes versions prior to v1.25, and work in Kubernetes v1.25 or higher by skipping installation of PSPs.

Charts that need updating: 
- prometheus-federator 
- rancher-grafana 
- rancher-project-monitoring 
- rancher-monitoring/rancher-monitoring-crd 
- rancher-kube-state-metrics 
- rancher-prometheus-adapter 
- rancher-pushprox 
- rancher-node-exporter 

If a cluster role in a chart contains PSP's along with other permissions extra work may be needed to achieve the intended behavior of that role.

**Comment by prachidamle** [comment]
@geethub97 pls syncup with @aiyengar2 for the changes that should be done for monitoring charts needed for k8s 1.25

**Comment by prachidamle** [comment]
We are splitting this task as follows:
@aiyengar2 will be adding in the PSP related changes to following charts:
- helm-project-operator
- prometheus-federator

@geethub97 will be handling the following updates:
- rancher-grafana 
- rancher-project-monitoring 
- rancher-monitoring/rancher-monitoring-crd 
- rancher-kube-state-metrics 
- rancher-prometheus-adapter 
- rancher-pushprox 
- rancher-node-exporter

**Comment by ronhorton** [comment]
**Pass** verfied in rancher `v2.7.2-rc5`

Rancher-monitoring 102.0.0+up40.1.2
installed and tested with and without psps on k8s 1.24
installed and tested on k8s 1.25
installed alerting-drivers 102.0.0 and confirmed monitoring alerts sent to sms
