### ISSUE TITLE
[prom2teams ] Check for PSP compatibility in target cluster

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#39849]
Parent ticket: https://github.com/rancher/rancher/issues/39366

Kubernetes 1.25 drops support for PSP, so additional checks need to be added.

Rancher team 3 is following the proposal outlined in "Kubernetes v1.25 PSP to PSA migration proposal document"

Every chart that ships with a PSP must be changed to add a new condition checking for the PSP capability in the target cluster:

**Capabilities check for Helm**

```{{- if .Capabilities.APIVersions.Has "policy/v1beta1/PodSecurityPolicy" }}```

This change allows the charts to still work with PSPs in Kubernetes versions prior to v1.25, and work in Kubernetes v1.25 or higher by skipping installation of PSPs.

Charts that need updating: 
- rancher-prom2teams 

If a cluster role in a chart contains PSP's along with other permissions extra work may be needed to achieve the intended behavior of that role.

**Comment by rishabhmsra** [comment]
Validated on rancher v2.7-head(9bb8d56)

Fresh install checks - Pass
- Created an ec2 node driver, k8s v1.25.5-rancher1-1 cluster(1-cp, 1-e, 3-w)
- Installed monitoring chart version `102.0.0+up40.1.2`
- Installed Alerting Driver chart version `102.0.0`
- Chart installed successfully also validated `rancher-alerting-drivers-prom2teams` deployment is up and Active:

![chart](https://user-images.githubusercontent.com/36376154/215769220-97b9ab0a-c37b-4a7c-94d1-eb1d724937f1.png)

![prom2teams](https://user-images.githubusercontent.com/36376154/215769227-1ce11580-c290-450e-b8ba-ae8ec6fed0b0.png)

**Comment by mitulshah-suse** [comment]
Closing this issue since approach for this setup has been changed. Refer to https://github.com/rancher/rancher/issues/40331 for further details
