### ISSUE TITLE
[alerting-drivers] Check for PSP compatibility in target cluster 

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#39848]
Parent ticket: https://github.com/rancher/rancher/issues/39366

Kubernetes 1.25 drops support for PSP, so additional checks need to be added.

Rancher team 3 is following the proposal outlined in "Kubernetes v1.25 PSP to PSA migration proposal document"

Every chart that ships with a PSP must be changed to add a new condition checking for the PSP capability in the target cluster:

**Capabilities check for Helm**

```{{- if .Capabilities.APIVersions.Has "policy/v1beta1/PodSecurityPolicy" }}```

This change allows the charts to still work with PSPs in Kubernetes versions prior to v1.25, and work in Kubernetes v1.25 or higher by skipping installation of PSPs.

Charts that need updating: 
- rancher-alerting-drivers

If a cluster role in a chart contains PSP's along with other permissions extra work may be needed to achieve the intended behavior of that role.

**Comment by rishabhmsra** [comment]
Re-opening this issue:
- Upgrade scenario is failing:
  - On rancher v2.7-head(8062f1e)
  - Created a v1.24.8-rancher1-1 k8s cluster(1-cp,1-e,2-w)
  - Installed monitoring chart `101.1.0+up40.1.2` version.
  - Installed Alerting Drivers chart `101.0.0` version.
  - Upgraded the cluster to k8s version v1.25.5-rancher1-1.
  - Upgraded the alerting driver chart to version `101.0.1` and it failed with below error:
```
helm upgrade --history-max=5 --install=true --namespace=cattle-monitoring-system --timeout=10m0s --values=/home/shell/helm/values-rancher-alerting-drivers-101.0.1.yaml --version=101.0.1 --wait=true rancher-alerting-drivers /home/shell/helm/rancher-alerting-drivers-101.0.1.tgz
Error: UPGRADE FAILED: unable to build kubernetes objects from current release manifest: resource mapping not found for name: "rancher-alerting-drivers-sachet-psp" namespace: "" from "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
ensure CRDs are installed first
```

- Also the chart `101.0.0` un-installation also erring out on v1.25.5-rancher1-1 k8s cluster:
```
helm uninstall --namespace=cattle-monitoring-system rancher-alerting-drivers
Error: uninstallation completed with 1 error(s): unable to build kubernetes objects for delete: resource mapping not found for name: "rancher-alerting-drivers-sachet-psp" namespace: "" from "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
ensure CRDs are installed first
```

**Comment by mitulshah-suse** [comment]
Pending on https://github.com/rancher/rancher/pull/40104

**Comment by mitulshah-suse** [comment]
Closing this issue since approach for this setup has been changed. Refer to https://github.com/rancher/rancher/issues/40331 for further details
