### ISSUE TITLE
[Enhancement] add probe customization to the Rancher chart

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#39841]
Breakout from: https://github.com/rancher/rancher/issues/38177
Adds values to the chart for rancher server to override the livenessProbe and readinessProbe's initialDelaySeconds and periodSeconds

**Comment by samjustus** [comment]
@cbron  needs PR

**Comment by jiaqiluo** [comment]
Can be validated in Rancher [v2.7.2-rc1](https://github.com/rancher/rancher/releases/tag/v2.7.2-rc1)

**Comment by brudnak** [comment]
# ✅ PASSED

## Reproduction Environment

#### Not required.

<hr>

## Validation Environment


| Component                        | Version / Type           |
| -------------------------------- | ------------------------ |
| Rancher version                  | v2.7.2-rc1               |
| Installation option              | Helm (high availability) |
| RKE binary version used          | v1.4.0                   |
| If Helm Chart k8s cluster        | v1.24.6                  |
| Cert Details                     | Let's Encrypt / `nginx`  |
| Docker version                   | 20.10.7, build f0df350   |
| Helm version                     | v2.16.8-rancher2         |
| Downstream cluster type          | not applicable           |
| Downstream K8s version           | not applicable           |
| Authentication providers enabled | local                    |
| Logged in user role              | administrator            |
| Browser type                     | Google Chrome            |
| Browser version                  | 108.0.5359.124           |


<details>
    <summary>🚨 Additional Validation Setup Details: Click to Expand</summary>

```shell
#!/bin/sh

helm repo update

kubectl create namespace cattle-system

kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.7.1/cert-manager.crds.yaml

helm install cert-manager jetstack/cert-manager \
  --namespace cert-manager \
  --create-namespace \
  --version v1.7.1

helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=$URL_VAR \
  --set bootstrapPassword=$PASSWORD_VAR \
  --set ingress.tls.source=letsEncrypt \
  --set letsEncrypt.email=$EMAIL_VAR \
  --set letsEncrypt.ingress.class=nginx \
  --set rancherImageTag=v2.7.2-rc1 \
  --version 2.7.2-rc1 \
  --set livenessProbe.initialDelaySeconds=77 \
  --set livenessProbe.periodSeconds=77 \
  --set readinessProbe.initialDelaySeconds=77 \
  --set readinessProbe.periodSeconds=77
```

</details>

## Validation steps

1. Setup Rancher server with the local cluster as RKE1
2. When doing helm install provide the additional set values

```shell
  --set livenessProbe.initialDelaySeconds=77 \
  --set livenessProbe.periodSeconds=77 \
  --set readinessProbe.initialDelaySeconds=77 \
  --set readinessProbe.periodSeconds=77
```

3. Once Rancher is installed >>> navigate to local cluster Kubectl Shell
4. Run the following command

```shell
kubectl get pods -n cattle-system
kubectl get pod <rancher-pod-name-here> -n cattle-system -o yaml
```

5. Verify the liveness and readiness probe settings have been updated to 77

## Additional Info

## RESULTS

#### ✅ Expected

For the liveness and readiness probe settings to match what was passed to the helm install command

#### ✅ Actual

The liveness and readiness probe settings did match what was passed to the helm install command

## 📋 QA Test Plan

>Additional Tests Setup


| Component                        | Version / Type                       |
| -------------------------------- | ------------------------------------ |
| Rancher version                  | v2.7.2-rc1                           |
| Installation option              | Helm (high availability)             |
| If Helm Chart k8s cluster        | v1.24.7+k3s1                         |
| Cert Details                     | Let's Encrypt / `traefik`            |
| k3s ha external db               | Aurora MySQL 5.7.mysql_aurora.2.10.2 |
| Helm version                     | v2.16.8-rancher2                     |
| Downstream cluster type          | not applicable                       |
| Downstream K8s version           | not applicable                       |
| Authentication providers enabled | local                                |
| Logged in user role              | administrator                        |
| Browser type                     | Google Chrome                        |
| Browser version                  | 108.0.5359.124                       |

<table>
    <tbody>
        <tr>
            <th>Scenario</th>
            <th>Steps</th>
            <th>Expected</th>
            <th>Actual & Pass/Fail</th>
        </tr>
        <tr>
            <td>Test against both a local setup with HA k3s/external DB & RKE1 HA</td>
            <td>
                <ol>
                    <li>Test against RKE1 HA Rancher</li>
                    <li>Test against k3s/external DB HA Rancher</li>
                </ol>
            </td>
            <td>Expected: For enhancement to work with various local cluster types</td>
            <td>Actual: Enhancement works with various local cluster types (k3s/external DB HA & RKE1 HA)<br><br>Pass/Fail: ✅<code>PASS</code></td>
        </tr>
        <tr>
            <td>Set liveness and readiness probes via Terraform</td>
            <td>
                <ol>      
                    <li>Install Rancher chart with Terraform provider hashicorp/helm, version 2.7.1</li>
                    <li>Include the 4 additional set statements to set the probes values</li>
                    <li>Run the Terraform module. (see the screenshot below the table for successful results)</li>
                </ol>
            </td>
            <td>Expected: New probe values should be able to be set via helm install or via helm provider</td>
            <td>Actual: Values set successfully<br><br>Pass/Fail: ✅<code>PASS</code></td>
        </tr>
        <tr>
            <td>start with rancher <code>2.7.0</code> upgrade to <code>2.7.2-rc1</code> and add new probe values to helm</td>
            <td>
                <ol>
                    <li>start with rancher <code>2.7.0</code></li>
                    <li>upgrade to rancher <code>2.7.2-rc1</code></li>
                    <li>include new values to the 4 probe settings</li>
                </ol>
            </td>
            <td>Expected: For the new probe values to be present after upgrade</td>
            <td>Actual: New probe values present after upgrade from 2.7.0 to 2.7.2-rc1<br><br>Pass/Fail: ✅<code>PASS</code></td>
        </tr>
    </tbody>
</table>

<img width="751" alt="2023-01-11_02-42-57" src="https://user-images.githubusercontent.com/40877149/211863100-6cfc234e-a87a-49bc-9df3-a7a7ba735437.png">

**Comment by cbron** [comment]
Re-opening to add startupProbe

**Comment by jiaqiluo** [comment]
Can be validated in Rancher [v2.7.2-rc2](https://github.com/rancher/rancher/releases/tag/v2.7.2-rc2)

**Comment by brudnak** [comment]
# ✅ PASSED

## Reproduction Environment

#### Not required.

<hr>

## Validation Environment


| Component                        | Version / Type           |
| -------------------------------- | ------------------------ |
| Rancher version                  | v2.7.2-rc2               |
| Installation option              | Helm (high availability) |
| RKE binary version used          | v1.4.0                   |
| If Helm Chart k8s cluster        | v1.24.6                  |
| Cert Details                     | Let's Encrypt / `nginx`  |
| Docker version                   | 20.10.7, build f0df350   |
| Helm version                     | v2.16.8-rancher2         |
| Downstream cluster type          | not applicable           |
| Downstream K8s version           | not applicable           |
| Authentication providers enabled | local                    |
| Logged in user role              | admin, standard user     |
| Browser type                     | Microsoft Edge           |
| Browser version                  | 110.0.1587.41            |


<details>
    <summary>🚨 Additional Validation Setup Details: Click to Expand</summary>

Rancher setup with: https://github.com/brudnak/aws-ha-infra

</details>

## Validation steps


1. Setup Rancher server with the local cluster as RKE1
2. When doing helm install provide the additional set values

```shell
  --set livenessProbe.initialDelaySeconds=42 \
  --set livenessProbe.periodSeconds=42 \
  --set readinessProbe.initialDelaySeconds=42 \
  --set readinessProbe.periodSeconds=42 \
  --set startupProbe.periodSeconds=42
```

3. Once Rancher is installed >>> navigate to local cluster Kubectl Shell
4. Run the following command

```shell
kubectl get pods -n cattle-system
kubectl get pod <rancher-pod-name-here> -n cattle-system -o yaml
```

5. Verify the probe settings have been updated

## Additional Info

## RESULTS

#### ✅ Expected

For the supplied values to be set

#### ✅ Actual

The supplied values were successfully set

**Comment by cbron** [comment]
See original issue for release-note
