### ISSUE TITLE
[Longhorn] Check for PSP compatibility in target cluster

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#39855]
Parent ticket: https://github.com/rancher/rancher/issues/39366

Kubernetes 1.25 drops support for PSP, so additional checks need to be added.

Rancher team 3 is following the proposal outlined in "Kubernetes v1.25 PSP to PSA migration proposal document"

Every chart that ships with a PSP must be changed to add a new condition checking for the PSP capability in the target cluster:

**Capabilities check for Helm**

```{{- if .Capabilities.APIVersions.Has "policy/v1beta1/PodSecurityPolicy" }}```

This change allows the charts to still work with PSPs in Kubernetes versions prior to v1.25, and work in Kubernetes v1.25 or higher by skipping installation of PSPs.

Charts that need updating: 
- longhorn

If a cluster role in a chart contains PSP's along with other permissions extra work may be needed to achieve the intended behavior of that role.

**Comment by PhanLe1010** [comment]
Thanks @MKlimuszka  for helping Longhorn. However, the Longhorn team already resolved this issue by:
1. Current existing Longhorn chart versions (<= 1.3.x) have PSP but they don't work with Kubernetes 1.25 by default. So it is no problem
2. Newer Longhorn 1.4.x support Kubernetes 1.25 and it already disabled PSP by default. https://github.com/longhorn/longhorn/pull/4695

**Comment by prachidamle** [comment]
@PhanLe1010 can you move this ticket then moved "to-test" to be validated by Longhorn QA?

**Comment by PhanLe1010** [comment]
@prachidamle 

Since there is no work need to be done on Rancher side as mentioned in [the comment ](https://github.com/rancher/rancher/issues/39855#issuecomment-1344989288),  should this ticket be marked as `wont fix` or just move it to `to-test` ?

**Comment by prachidamle** [comment]
@khushboo-rancher is this ok to close?

**Comment by khushboo-rancher** [comment]
Yes, we've tested the upgrade and Longhorn v1.4.x installation on 1.25
