### ISSUE TITLE
[Epinio] Check for PSP compatibility in target cluster

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#39858]
Parent ticket: https://github.com/rancher/rancher/issues/39366

Kubernetes 1.25 drops support for PSP, so additional checks need to be added.

Rancher team 3 is following the proposal outlined in "Kubernetes v1.25 PSP to PSA migration proposal document"

Every chart that ships with a PSP must be changed to add a new condition checking for the PSP capability in the target cluster:

**Capabilities check for Helm**

```{{- if .Capabilities.APIVersions.Has "policy/v1beta1/PodSecurityPolicy" }}```

This change allows the charts to still work with PSPs in Kubernetes versions prior to v1.25, and work in Kubernetes v1.25 or higher by skipping installation of PSPs.

Charts that need updating: 
- Epinio 

If a cluster role in a chart contains PSP's along with other permissions extra work may be needed to achieve the intended behavior of that role.

**Comment by prachidamle** [comment]
Kubernetes 1.25 drops support for following APIs along with PSPs, so additional changes need to be added to these charts to be able to support K8s 1.25

APIs deprecated:
HPA: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#horizontalpodautoscaler-v125

Migrate manifests and API clients to use the autoscaling/v2 API version
PodDisruptionBudget https://kubernetes.io/docs/reference/using-api/deprecation-guide/#poddisruptionbudget-v125

Migrate manifests and API clients to use the policy/v1 API version

**Comment by andreas-kupries** [comment]
Thanks for the note ... Checking Epinio I find that the core and most dependencies do not use HPA and PodDisruptionBudget at all.

For the `dex` dependency I find that while it is capable of using HPA/PDB these features are disabled by default, and Epinio does not activate them.

As such we are looking good on that front. We have to keep watching the situation however, in case an upgrade of the dex chart changes its defaults.

**Comment by MKlimuszka** [comment]
@andreas-kupries, should we assign this to you and mark it as in progress?

**Comment by MKlimuszka** [comment]
Oh great! @andreas-kupries , has it been tested?

**Comment by andreas-kupries** [comment]
> Oh great! @andreas-kupries , has it been tested?

According to the last point in @thehejik's [QA report](https://github.com/rancher/charts/pull/2247#issuecomment-1353269771)

> Check PSP warnings on k8s 1.25 when installing the chart - they are gone:
Given that we are currently unable to install rancher:v2.7.0 via helm on cluster with k8s 1.25 (and downstream cluster with 1.25 is not refreshing Repositories for some reason) I've at least verified that there are no PSP warning present anymore when installing the App (epinio+crd) manually over Helm CLI to my downstream rancher 1.25 cluster. Also the sample application has been deployed successfully there. OTOH as expected the PSP Warnings are still present in helm output when installing to 1.24 k8s cluster.

**Comment by andreas-kupries** [comment]
Ping.

**Comment by andreas-kupries** [comment]
Ref #40338

**Comment by olblak** [comment]
@MKlimuszka I let you close this issue as all work is done on Epinio side

**Comment by prachidamle** [comment]
@olblak @andreas-kupries https://github.com/rancher/rancher/issues/40338#issuecomment-1420087622

**Comment by sowmyav27** [comment]
@MKlimuszka Can you close this issue if our team has no validations pending?

**Comment by olblak** [comment]
I am closing this issue as all things looks good, feel free to reopen
