### ISSUE TITLE
[Neuvector] Check for PSP compatibility in target cluster

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#39856]
Parent ticket: https://github.com/rancher/rancher/issues/39366

Kubernetes 1.25 drops support for PSP, so additional checks need to be added.

Rancher team 3 is following the proposal outlined in "Kubernetes v1.25 PSP to PSA migration proposal document"

Every chart that ships with a PSP must be changed to add a new condition checking for the PSP capability in the target cluster:

**Capabilities check for Helm**

```{{- if .Capabilities.APIVersions.Has "policy/v1beta1/PodSecurityPolicy" }}```

This change allows the charts to still work with PSPs in Kubernetes versions prior to v1.25, and work in Kubernetes v1.25 or higher by skipping installation of PSPs.

Charts that need updating: 
- Neuvector (has PSPs in the upstream )

If a cluster role in a chart contains PSP's along with other permissions extra work may be needed to achieve the intended behavior of that role.

**Comment by samjustus** [comment]
https://github.com/rancher/charts/pull/2300

**Comment by anupama2501** [comment]
will be validated by @selvamt94

**Comment by selvamt94** [comment]
Verified with 2.7 dev brach Rancher Manager v2.7-9bb8d5674d4f2fe85cca799b07a6d18eee257b9e-head. The new Neuvector feature chart 102.0.0+up2.4.2 show error if psp is enabled on k8s version 1.26. And chart with older version k8s if psp is enabled.

**Comment by sowmyav27** [comment]
@selvamt94 Can you confirm if checks for this issue are complete and if we can close the issue ?

**Comment by selvamt94** [comment]
@sowmyav27 I verified both older and newer version of Kubernetes for this check. Please close it. Thanks.
