### ISSUE TITLE
[Webhook] Check for PSP compatibility in target cluster

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#39854]
Parent ticket: https://github.com/rancher/rancher/issues/39366

Kubernetes 1.25 drops support for PSP, so additional checks need to be added.

Rancher team 3 is following the proposal outlined in "Kubernetes v1.25 PSP to PSA migration proposal document"

Every chart that ships with a PSP must be changed to add a new condition checking for the PSP capability in the target cluster:

**Capabilities check for Helm**

```{{- if .Capabilities.APIVersions.Has "policy/v1beta1/PodSecurityPolicy" }}```

This change allows the charts to still work with PSPs in Kubernetes versions prior to v1.25, and work in Kubernetes v1.25 or higher by skipping installation of PSPs.

Charts that need updating: 
- Webhook (has PSPs in the upstream)

If a cluster role in a chart contains PSP's along with other permissions extra work may be needed to achieve the intended behavior of that role.

**Comment by cbron** [comment]
I'm going to move this back to working, as we need to track the upgrade issue around PSPs in the webhook. If the wider pattern is to make sure PSPs in all charts are disabled before upgrading a cluster to 1.25, we need to make sure webhook (which is managed) disables PSPs when upgrading to this Rancher release. Or provides some mechanism to disable them manually, so a user can go to 1.25. 
Adding @maxsokolovsky as well

**Comment by maxsokolovsky** [comment]
I don't entirely understand what we must do here.
What do we mean by "webhook disables PSPs when upgrading to new Rancher release"?

**Comment by maxsokolovsky** [comment]
Spoke with @cbron and @MbolotSuse, we should test the following scenarios:
1. Delete webhook as an app from a downstream cluster - ensure its post-delete job completes.
2. Detach an import cluster - ensure there are no errors in the webhook or its post-delete job.

**Comment by maxsokolovsky** [comment]
Ran the two cases above and saw no problems with `rancher-webhook` being deleted. Not sure what to do with the issue itself, switched from `working` to `review`.

**Comment by anupama2501** [comment]
Verified on v27-head `e73cfe8`
With local k8s 1.24 psp hardened cluster:
1. Imported AKS, RKE1[PSP enabled] clusters - On un importing a cluster verified the webhook was deleted
2. Verified upon un installing the rancher server - webhook is cleaned up.
With local k8s 1.25 PSA hardened cluster:
1. Imported AKS, RKE1 clusters - On un importing a cluster verified the webhook was deleted
2. Verified upon un installing the rancher server - webhook is cleaned up.
Upgrade:
1. Verified with local 1.24 rancher 2.7.0, upgraded rancher to v2.7-head, un importing RKE2, AKS cluster removed the webhook from the clusters.
2. Verified uninstalling rancher - webhook is cleaned up.

Additionally verified manually uninstalling webhook will recreate the app on the downstream - AKS hosted, RKE1 and RKE2 node drivers.
