### ISSUE TITLE
[Backup] Check for PSP compatibility in target cluster

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#39850]
Parent ticket: https://github.com/rancher/rancher/issues/39366

Kubernetes 1.25 drops support for PSP, so additional checks need to be added.

Rancher team 3 is following the proposal outlined in "Kubernetes v1.25 PSP to PSA migration proposal document"

Every chart that ships with a PSP must be changed to add a new condition checking for the PSP capability in the target cluster:

**Capabilities check for Helm**

```{{- if .Capabilities.APIVersions.Has "policy/v1beta1/PodSecurityPolicy" }}```

This change allows the charts to still work with PSPs in Kubernetes versions prior to v1.25, and work in Kubernetes v1.25 or higher by skipping installation of PSPs.

Charts that need updating: 
- rancher-backup 

If a cluster role in a chart contains PSP's along with other permissions extra work may be needed to achieve the intended behavior of that role.

**Comment by prachidamle** [comment]
Few things we would also need to do:

-  test the rancher-backup chart on k8s 1.25 cluster and update the `catalog.cattle.io/kube-version: '>= 1.16.0-0 < 1.25.0-0'  https://github.com/rancher/charts/blob/dev-v2.7/charts/rancher-backup/3.0.1-rc1/Chart.yaml#L5

**Comment by ronhorton** [comment]
**Pass** verified in rancher `v2.7.2-rc6`

testing was completed according to `Feature Chart k8s v1.25 Test Plan`
all test cases passed
