### ISSUE TITLE
[Extensions] Check for PSP compatibility in target cluster

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#39853]
Parent ticket: https://github.com/rancher/rancher/issues/39366

Kubernetes 1.25 drops support for PSP, so additional checks need to be added.

Rancher team 3 is following the proposal outlined in "Kubernetes v1.25 PSP to PSA migration proposal document"

Every chart that ships with a PSP must be changed to add a new condition checking for the PSP capability in the target cluster:

**Capabilities check for Helm**

```{{- if .Capabilities.APIVersions.Has "policy/v1beta1/PodSecurityPolicy" }}```

This change allows the charts to still work with PSPs in Kubernetes versions prior to v1.25, and work in Kubernetes v1.25 or higher by skipping installation of PSPs.

Charts that need updating: 
- ui-plugin-operator 

If a cluster role in a chart contains PSP's along with other permissions extra work may be needed to achieve the intended behavior of that role.

**Comment by prachidamle** [comment]
PR to make changes to https://github.com/rancher/ui-plugin-operator is merged: 
https://github.com/rancher/ui-plugin-operator/pull/8

Need to update chart version @PennyScissors

**Comment by ronhorton** [comment]
**Pass** verified in rancher `v2.7.2-rc8`

**Test 1: Upgrade Test**
1. enabled extensions on 1.24 cluster
2. installed kube-warden
3. added kube-warden repo
4. upgraded k8s to 1.25
5. added default policyservers chart to kube warden
`result: Pass`

**Test 2: Fresh Install**
1. enabled extensions
2. installed kube warden
3. installed OS management
4. added default policyservers chart to kube warden
`result: Pass`
