### ISSUE TITLE
[Windows] Check for PSP compatibility in target cluster

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#39852]
Parent ticket: https://github.com/rancher/rancher/issues/39366

Kubernetes 1.25 drops support for PSP, so additional checks need to be added.

Rancher team 3 is following the proposal outlined in "Kubernetes v1.25 PSP to PSA migration proposal document"

Every chart that ships with a PSP must be changed to add a new condition checking for the PSP capability in the target cluster:

**Capabilities check for Helm**

```{{- if .Capabilities.APIVersions.Has "policy/v1beta1/PodSecurityPolicy" }}```

This change allows the charts to still work with PSPs in Kubernetes versions prior to v1.25, and work in Kubernetes v1.25 or higher by skipping installation of PSPs.

Charts that need updating: 
-   rancher-windows-exporter 
-   rancher-wins-upgrader 

If a cluster role in a chart contains PSP's along with other permissions extra work may be needed to achieve the intended behavior of that role.

**Comment by snasovich** [comment]
Closing this issue as "not applicable" per the following:
* `rancher-windows-exporter` is a sub-chart of `rancher-monitoring` and should be handled as part of https://github.com/rancher/rancher/issues/39846 (if needed)
* `rancher-wins-upgrader` is not applicable for 2.7.x, see https://github.com/rancher/rancher/issues/38965#issuecomment-1263748696 for more info
* _(Bonus)_ `rancher-windows-gmsa` and `rancher-windows-gmsa-crd` are part of experimental feature (GMSA) that is not even supporting 1.24 at this moment
