### ISSUE TITLE
[Fleet] Check for PSP compatibility in target cluster

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#39857]
Parent ticket: https://github.com/rancher/rancher/issues/39366

Kubernetes 1.25 drops support for PSP, so additional checks need to be added.

Rancher team 3 is following the proposal outlined in "Kubernetes v1.25 PSP to PSA migration proposal document"

Every chart that ships with a PSP must be changed to add a new condition checking for the PSP capability in the target cluster:

**Capabilities check for Helm**

```{{- if .Capabilities.APIVersions.Has "policy/v1beta1/PodSecurityPolicy" }}```

This change allows the charts to still work with PSPs in Kubernetes versions prior to v1.25, and work in Kubernetes v1.25 or higher by skipping installation of PSPs.

Charts that need updating: 
- Fleet

If a cluster role in a chart contains PSP's along with other permissions extra work may be needed to achieve the intended behavior of that role.

**Comment by kkaempf** [comment]
There's no PSP reference in Fleet charts.

**Comment by prachidamle** [comment]
We can close this ticket as there will not be any changes needed for fleet and fleet charts regarding PSP compatability.
