### ISSUE TITLE
SVG badge for markdown README

### ISSUE THREAD

**Issue by aletessier** [rancher/rancher#3986]
Rancher Version: all

Docker Version: all

OS: all

Steps to Reproduce: none

Results: none

Expected: display a badge on a README (md,rst,cc menu) showing the state of a service

**Comment by aletessier** [comment]
Hello,

is it possible to get a badge out of rancher easily ?

cordialement,

**Comment by vincent99** [comment]
This would have to be available unauthenticated even if auth is enabled, and would leak information about your setup to anybody that could hit it.  You can build something yourself that uses the API to get a service and returns a SVG of the `state` or `healthState`, but this is not something that we're going to be adding to the core application.
