### ISSUE TITLE
[RFE] Remove usage of `gorilla` packages

### ISSUE THREAD

**Issue by richardcase** [rancher/rancher#39862]
**Is your feature request related to a problem? Please describe.**
The [gorilla project](https://github.com/gorilla#gorilla-toolkit) has been archived and is no longer maintained. As we use a number of projects like `mux` and `websocket`  within Rancher, we should look to remove our usage of these packages.

From the readme:

```
The Gorilla project has been archived, and is no longer under active maintainenance. You can read more here: https://github.com/gorilla#gorilla-toolkit
```

**Describe the solution you'd like**
Remove the usage or `gorilla` packages from Rancher and find/use alternative packages.

**Describe alternatives you've considered**
We could:

- Continue to use them as is and accept there will be no bug fixes etc
- Fork and maintain our own versions
- Use someone else's fork
- Take over maintaining the project

**Additional context**

**Comment by cbron** [comment]
I'm going to close, project is being maintained again: https://gorilla.github.io/blog/2023-07-17-project-status-update/
