### ISSUE TITLE
[RFE] Branch KEv2 operators

### ISSUE THREAD

**Issue by a-blender** [rancher/rancher#39860]
**Is your feature request related to a problem? Please describe.**

We need to branch the KEv2 operators so that we don't end up pulling features into v2.6x that we don't need, or bugs into v2.7x that we don't need. We are *only backporting* bugs to 2.6.

**Describe the solution you'd like**

To add / expand the above.

**For aks-operator**
We only have v1.0.x releases at this time used by both Rancher v2.6.x and v2.7.x.
For the next 2.7.x/2.6.x release we only plan  to include bug fixes, so technically we can release v1.0.8 and use it in both next 2.7.x and 2.6.x releases.
But as soon as we need new feature, we will need to branch and do 1.1.x for 2.7.x and continue 1.0.x for 2.6.x. So might as well branch now.
So, create release/v1.0 from master’s HEAD and tag it as both v1.1.0-rc1 and v1.0.8-rc2 to reference by release/v2.7 and release/v2.6 for Rancher/charts.
Note that from that point any bugfixes for aks-operator will need to go to both branches.

**For eks-operator**
We already have release/v1.0 branch for Rancher 2.5.x releases, but it’s effectively dead with Rancher 2.5.x nearly EOL.
v1.1.x releases are produced from master  and are used by both 2.7.0 and 2.6.9.
For the next 2.7.x and 2.6.x releases we plan to only add new features, so technically we can have 2.6.next reference 1.1.5 without any changes and then have 2.7.next jump onto 1.1.6. That’s kind of how we have it currently in https://github.com/rancher/eks-operator/commits/master
But the same way as for aks-operator, as soon as we have a bugfix we need to do, we have to branch.
So might as well do it now.
For that. we want to create release/v1.1 from 9/28/22 commit (https://github.com/rancher/eks-operator/commit/0fe4d22f1edbf5a35dd2c0f56e32f3c0827a1db4), delete the v1.1.6-rc1 tag from the later commit and delete related pre-release (not ideal, but that’s OK since it’s not a full release) , and retag it as v1.2.0-rc1 to be used by Rancher’s (and chart’s) release/v2.7 branch.

**For gke-operator**
Similar situation to EKS-operator as we have release/v1 branch for 2.5.x releases, but there are no changes currently planned for 2.6.next or 2.7.next releases.
So I think it’s worth creating release/v1.1 branch from master’s HEAD. Whether we preemptively retag the same as v1.2.0-rc1 to be used Rancher’s (and chart’s) release/v2.7 branch or just keep using v1.1.5 in both 2.6 and 2,7 for now I’m somewhat torn on.

**Docs**
For all 3, we definitely want to update README.MD to explain branching for each of master and release/… branches to explain which branch is for which Rancher release.

**Comment by annablender** [comment]
For this I will need,

- [ ] Branch and tag the KEv2 operators
- [ ] rancher/charts:dev-v2.6 PR? and rancher/charts:dev-v2.7 PR to bump operator chart versions
- [ ] rancher/rancher PR to bump operator versions
- [ ] Docs PR

**Comment by annablender** [comment]
Branching is complete! In the process of verifying that how I've split is correct, then will submit PRs to rancher/charts and rancher/rancher on Monday

**Comment by annablender** [comment]
After branching the KEv2 operators, the new EKS operator readme needs to be backported to the new branch for 2.6 and 2.7 release/v1.1 before this issue is done.

**Comment by annablender** [comment]
No testing required. Issue can be closed

**Comment by annablender** [comment]
@sowmyav27 No testing required here. QA can close this

**Comment by snasovich** [comment]
This was done for a loooong time, closing.
