### ISSUE TITLE
RKE2 and K3S - KDM Update for K8s December patch release for Rancher 2.7

### ISSUE THREAD

**Issue by rancher-max** [rancher/rancher#39886]
# KDM Updates

| New Kubernetes Version  | Min Rancher Version | Max Rancher Version | Default Version |
|                  :---:                  |              :---:               |               :---:               |          :---:          |
| v1.22.17+rke2r1                 | v2.6.3-alpha1             | v2.6.99 |  x                         |
| v1.23.15+rke2r1                  | v2.6.4-alpha1             | v2.7.99 |                         |
| v1.24.9+rke2r1                  | v2.6.7-alpha1             | v2.7.99 |                         |
| v1.22.17+k3s1                   | v2.6.3-alpha1             | v2.6.99 |   x                        |
| v1.23.15+k3s1                    | v2.6.4-alpha1             | v2.7.99 |                         |
| v1.24.9+k3s1                    | v2.6.7-alpha1             | v2.7.99 |                          |

# Chart Changelog

| Chart Name  | New Version | Affected Kubernetes Version(s) |
|        :---:        |       :---:        |                     :---:                     |
| rke2-cilium | 1.12.402 | v1.23.15+rke2r1, v1.24.9+rke2r1 |
| rke2-canal | v3.24.5-build2022120101 | v1.23.15+rke2r1, v1.24.9+rke2r1 |
| rke2-calico | v3.24.501 | v1.23.15+rke2r1, v1.24.9+rke2r1 |
| rke2-calico-crd | v3.24.501 | v1.23.15+rke2r1, v1.24.9+rke2r1 |
| rke2-ingress-nginx | 4.1.007 | v1.23.15+rke2r1, v1.24.9+rke2r1 |
| rke2-metrics-server | 2.11.100-build2022101107 | v1.23.15+rke2r1, v1.24.9+rke2r1 |
| rke2-multus | v3.9-build2022102805 | v1.23.15+rke2r1, v1.24.9+rke2r1 |

# Argument Changelog

| Argument Name  | Affected Kubernetes Version(s) |
|        :---:           |                     :---:                     |
| | |

# Additional Notes
N/A

**Comment by est-suse** [comment]
Validated on rancher 2.7.0, versions 1.23 and 1.24 are available.

![image](https://user-images.githubusercontent.com/106194120/208110077-55748f26-b3fa-4399-9dc2-4d920abd118f.png)

**Comment by rancher-max** [comment]
This has passed post-release validations now as well and KDM PRs have been merged.

**Comment by snasovich** [comment]
Reopening for tracking replacement of original December releases with `r2`s coming out soon.

**Comment by rancher-max** [comment]
This has been re-validated with r2 versions
