### ISSUE TITLE
[rancher-compose] Add ability to select S3 bucket for builds 

### ISSUE THREAD

**Issue by ryaninvents** [rancher/rancher#3989]
Rancher Version: 0.59.1

Docker Version: 1.9.1

OS: Debian

Steps to Reproduce:
1. Create a bucket named `rancher-builds` on S3 for your builds.
2. Download IAM credentials for your user and set up using the `aws` CLI tool.
3. In AWS, give your user full access to the bucket.
4. Use `rancher-compose up` on a `docker-compose` file with a local `build:` directory.

Results: 403 error; I suspect it's because Rancher doesn't know to use the `rancher-builds` bucket.

Expected: A configuration step pointing to the `rancher-builds` bucket.

**Comment by deniseschannon** [comment]
Whenever I've tested builds, it hasn't gone in a specific bucket, but in the "All buckets" section.

I think it'd be an enhancement to be able to specify what bucket to go into.

**Comment by r24y** [comment]
Oh, I see. So it creates a new bucket then? I've set the most permissive possible S3 policy for my user and it still seems to be giving me a permissions error.

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Stmt1458178323000",
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": [
                "arn:aws:s3:::*"
            ]
        }
    ]
}
```

**Comment by c0deaddict** [comment]
+1 for being able to specify a s3 bucket

**Comment by lewistaylor** [comment]
+1, my base bucket is littered with builds from rancher now!

**Comment by r24y** [comment]
@lewistaylor @c0deaddict are there any tutorials you've found beyond the docs for setting up S3 builds? I think my access permissions for Amazon are incorrect but have not been able to find out what the matter is.

**Comment by adrianfalleiro** [comment]
@r24y This policy works for me
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect":"Allow",
            "Action":[
                "s3:ListAllMyBuckets"
            ],
            "Resource":"arn:aws:s3:::*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": [
                "arn:aws:s3:::*"
            ]
        }
    ]
}
```

**Comment by archie** [comment]
In a CI/CD environment having the buckets created in the S3 root is a severe limitation. While it is possible to increase the max limit of buckets allowed at AWS it's not sustainable in the long run. Is there any progress on collecting all S3 builds into one bucket? 

Is there something we can help with in terms of design input or similar?

**Comment by cpoole** [comment]
This is an absolute mess. AWS sets hard limits on the number of buckets you can have. 30 developers with 10 images each already puts you over the limit. Not to mention each build seems to create a new bucket...

This feature is a non starter until we can specify a "build" bucket and then have each unique build create a subfolder inside that build bucket.

Or even better would be able to specify a bucket and a path within said bucket.

**Comment by adrianfalleiro** [comment]
Hey @cpoole, I faced a similar issue and ended up creating an internal fork of `rancher-compose` that allows you to specify a target bucket as a command line argument. 

I never ended up submitting a pull request because it was against an older version of `rancher-compose`. Since this is still an issue perhaps I will take a look at it over the weekend

**Comment by cpoole** [comment]
@adrianfalleiro that would be awesome. I'm willing to help out with the PR if you'd like. 

Is it the compose posted on your github? https://github.com/adrianfalleiro/rancher-compose

**Comment by adrianfalleiro** [comment]
@cpoole I've only just got to this. Yep, correct thats the repo. 

Unfortunately I've got pretty bad internet atm - so haven't been able get a Go dev environment running so I haven't been able to test this against the latest version of `rancher-compose`

A couple things to note:

- You might need to run `go fmt` I think some of my indents are messed up
- I've not written any tests
- Might want to make the command line argument name a bit more descriptive

I've added you as a collaborator to my repo 👍

**Comment by davidknezic** [comment]
Just submitted a pr with @adrianfalleiro's commit that went through `go fmt`. https://github.com/rancher/rancher-compose/pull/244

Let's hope this will get merged soon.

**Comment by adrianfalleiro** [comment]
Oh man, totally forgot about this. Cheers @davidknezic

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
