### ISSUE TITLE
[RFE] Add validation for podSecurityAdmissionConfigrationTemplate 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#39891]
Recently we added the CRD `podSecurityAdmissionConfigrationTemplate` to rancher: https://github.com/rancher/rancher/pull/39759

We would like to add validation for the values when creating/updating a PSACT; the validation should be similar to what the upstream does for [PodSecurityConfiguration]( https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/pod-security-admission/admission/api/validation/validation.go ).

The validation should go into rancher/webhook

**Comment by HarrisonWAffel** [comment]
The work for this has been merged and can be tested once the web-hook version is bumped

**Comment by sowmyav27** [comment]
This is not ready for test until a new Webhook RC is tagged. cc: @snasovich @Sahota1225

**Comment by HarrisonWAffel** [comment]
a webhook RC has been tagged and bumped in Rancher, this can now be tested

**Comment by markusewalker** [comment]
Test cases highlighted in the internal test plan pertaining to validation checks have been validated. Therefore, closing this issue.
