### ISSUE TITLE
Add CIS hardening guide for rancher provisioned RKE1 clusters on k8s 1.25

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#39894]
We currently need to have an up-to-date hardening guide for the v2.7x line to harden k8s v1.25 clusters. 
Epic: https://github.com/rancher/rancher/issues/38701

**Comment by cbron** [comment]
FYI @jiaqiluo / @macedogm 

This is a CIS standard: https://docs.rke2.io/security/cis_self_assessment123#52-pod-security-standards

Which could be interpreted as PSS, since that is only default mechanism available in 1.25. Though I'm assuming they left it vague to allow for other things like gatekeeper/kubewarden. We should probably chat about this.

**Comment by jiaqiluo** [comment]
The linked PR is merged, QA may need to reach out to the doc team for how to access to the staging docs for v2.7.2

**Comment by macedogm** [comment]
FYI for QA, next Monday I'll submit a PR on top of Jiaqi's PR with some minor updates to the hardening guides.

**Comment by macedogm** [comment]
Second PR with updates to hardening guides https://github.com/rancher/rancher-docs/pull/478.

**Comment by anupama2501** [comment]
Verified the following test scenarios on v2.7-head `cd1a716`

Created a rancher server on k8s 1.25 RKE1
1. As a standard user created a downstream RKE1 cluster with 1.25 PSA hardened 
   - Install cis chart `4.0.0-rc3`, ran cis hardened profile 1.23 scans 
   - Verified all scans except the ones mentioned in the screenshot below are failing. These are expected failures see https://github.com/rancher/rancher-docs/blob/release/v2.7.2/docs/pages-for-subheaders/rke1-hardening-guide.md?plain=1#L18
   - Scans 5.1.5 and 5.7.4 are failing as mentioned in https://github.com/rancher/rancher/issues/40817 and https://github.com/rancher/rancher/issues/40818
2. As a standard user created a downstream RKE1 cluster with 1.24 PSP hardened by setting psp.enabled=true in the chart
   - Install cis chart `4.0.0-rc3`, ran cis hardened profile 1.23 scans and the scans pass
   - delete psp profiles from the cluster
   - Upgrade the cluster to k8s 1.25
   - Edit the cluster.yml to harden the cluster using PSA template.
   - Once the cluster is active, run the rke-profile-hardened-1.23 scans.
   - As mentioned in the above test case, the scans are failing for 5.1.5 and 5.7.4 and others mentioned in the screenshot.
3.   As a standard user created a downstream RKE1 cluster with 1.23 PSP hardened by setting psp.enabled=true in the chart
   - Install cis chart `4.0.0-rc3`, ran cis hardened profile 1.23 scans and the scans pass
   - delete psp profiles from the cluster
   - Upgrade the cluster to k8s 1.25
   - Edit the cluster.yml to harden the cluster using PSA template.
   - Once the cluster is active, run the rke-profile-hardened-1.23 scans.
   - As mentioned in the above test case, the scans are failing for 5.1.5 and 5.7.4 and others mentioned in the screenshot.
<img width="400" alt="2023-03-15_15-36-19" src="https://user-images.githubusercontent.com/38144301/225460010-03ed4af6-4796-4602-853f-528907f0c8bf.png">
