### ISSUE TITLE
[Backport 2.6] [Project Monitoring V2] Rebase Project Monitoring against 40.x.x Rancher Monitoring

### ISSUE THREAD

**Issue by aiyengar2** [rancher/rancher#39904]
Forward port PR for https://github.com/rancher/rancher/issues/39724.

For QA: please take a look at the comments on the original issue w.r.t. additional testing that needs to be done.

**Comment by ronhorton** [comment]
dup of https://github.com/rancher/rancher/issues/38934
closing this ticket and including in 38934 for reference

**Comment by ronhorton** [comment]
testing completed
<h3 id="RancherMonitoringV2Rebase-TestMatrix-Monitoring101.1.0+up40.1.2E2E-2.6-head-Defaultk8sversion:1.24" style="margin: 30px 0px 0px; padding: 0px; font-size: 16px; font-weight: bold; line-height: 1.5; letter-spacing: -0.006em; text-transform: none; color: rgb(23, 43, 77); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><strong>Test Matrix - Monitoring 101.1.0+up40.1.2 E2E - 2.6-head - Default k8s version: 1.24</strong></h3><div class="table-wrap" style="margin: 10px 0px 0px; padding: 0px; overflow-x: auto; color: rgb(23, 43, 77); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

Assignee | Cluster | Fresh Install | Upgrade | Notes / Ticket Number
-- | -- | -- | -- | --
Ron | Ubuntu RKE1 | PASS | PASS |  
Ron | Ubuntu RKE2 | PASS | PASS |  
Ron | K3S | PASS | PASS |  
Drew | K3S Hardened | PASS | PASS |  
Ron | SLES | PASS | PASS |  
Nick | Rocky | PASS | PASS |  
Nick | OpenSuse-Leap | PASS | PASS |  
Nick | RHEL 8.6 | PASS | PASS |  
Ron | GKE | PASS | PASS  |  
Ron | AKS | PASS | PASS  |  
Ron | EKS | PASS | PASS |  
Ron | Windows | PASS | PASS |  

</div><br class="Apple-interchange-newline">
