### ISSUE TITLE
[BUG] Norman websocket closes repeatedly

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#39915]
**Rancher Server Setup**
- Rancher version: 2.7.0

**Describe the bug**
The UI opens a single web socket to the `/v3` Norman endpoint. 

During two customer calls we witnessed the socket opening and then immediately closing. The UI then re-opens the socket. This cycle continues without end.

> This is seen when running Rancher in docker every 30 minutes, though close-open cycle only happens twice.

Some opened sockets show messages sent to the UI, some are empty

**To Reproduce**
Navigate to the Rancher UI log in page
Open up browsers dev tools --> Network Tab --> WS tab (to see web sockets)
Sign in the the Rancher UI
Monitor number of open sockets in dev tools

**Result**
`/v3` socket is closed, opened, closed, opened, etc

**Expected Result**
`/v3` socket is opened and stays open

When Norman – Kube socket closes after 30 minutes, which results in UI – Norman sockets closing, the UI should be able to open a new socket which stays open

Additional notes:

Kevin Joiner and I (Richard Cox) had a long discussion on how the Norman socket works. From my understanding...

SURE-5699

- There are many UI – Norman socket connections, but one Norman – Kube connection
- When Norman watches for resources it uses `Get State and Start at Any` mode, which may result in a large number of resource history messages (particularly in HA due to partitions and stale caches)
- When Norman sockets (to UI?) fall behind by 100 messages the socket is closed
- Assumption - When Norman is replaying messages to the UI sockets AND the system is under heavy use causing frequent resource.change messages... the socket will continually be closed as it will always be behind

Unknowns 
- Why on Rancher in docker the initial `v3` connection doesn't result in the same resource.change spam as when the `v3` socket is re-opened after the 30 minutes timeout

This could be the underlying cause for SURE-5185
- The issue was about excessive notifications for websocket disconnects
- The attached files seem in show the `v3` socket repeatedly disconnecting
  - image-328.info-websock-disconnect.png
- The issue was 'resolved' by reducing the growl notifications in the UI

**Comment by samjustus** [comment]
SURE-5699

**Comment by KevinJoiner** [comment]
Related dashboard changes https://github.com/rancher/dashboard/issues/7906

**Comment by MKlimuszka** [comment]
Closing as stale
