### ISSUE TITLE
[BUG] Error when upgrading logging in k8s 1.25 - upgrade failed

### ISSUE THREAD

**Issue by ronhorton** [rancher/rancher#39912]
**Rancher Server Setup**
- Rancher version: `2.7-head commit ID bae3241 `
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): `Helm`
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: `v1.25.2-rancher1-1`
- Cluster Type (Local/Downstream): `downstream ec2 ui provisioned`
* Custom = Running a docker command on a node
* Imported = Running kubectl apply onto an existing k8s cluster
* Hosted = EKS, GKE, AKS, etc
 * Infrastructure Provider = Rancher provisioning the nodes using different node drivers (e.g. AWS, Digital Ocean, etc)
-->

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: `admin`

**Describe the bug**
after having installed logging, clicked 'edit/upgrade' on rancher logging - upgrade failed with error

**To Reproduce**
1. install logging on 1.25 rke1 cluster
2. edit/upgrade logging

**Result**
upgrade fails with 
`v1.25.2-rancher1-1`
`helm upgrade --history-max=5 --install=true --namespace=cattle-logging-system --timeout=10m0s --values=/home/shell/helm/values-rancher-logging-101.1.0-up3.17.10.yaml --version=101.1.0+up3.17.10 --wait=true rancher-logging /home/shell/helm/rancher-logging-101.1.0-up3.17.10.tgz
Error: UPGRADE FAILED: resource mapping not found for name: "rancher-logging-rke-aggregator" namespace: "cattle-logging-system" from "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
ensure CRDs are installed first
 `

**Expected Result**
upgrade successful

**Screenshots**

**Additional context**
PR raised to fix same issue when deleting rancher-logging:  https://github.com/rancher/charts/pull/2272

**Comment by MKlimuszka** [comment]
@stormqueen1990 , should Ron retest this now that the PSP PR is merged?

**Comment by stormqueen1990** [comment]
@MKlimuszka this will likely keep failing unless the installation is updated to remove PSPs prior to a cluster version upgrade.

**Comment by stormqueen1990** [comment]
This issue should be fixed with rancher/charts#2362 + rancher/charts#2390.

**Comment by prachidamle** [comment]
@ronhorton can we retest this issue considering the comment above?

**Comment by prachidamle** [comment]
@stormqueen1990 Can you please summarize here what should be expected behavior that QA should validate now that the PSP approach has changed.

**Comment by stormqueen1990** [comment]
Hi @prachidamle, sure thing!

The general expectation would be that it's feasible now to install v102.0.0+up3.17.10 of this chart on Kubernetes v1.24. When the flag `global.cattle.psp.enabled` is set to `false` in this new chart version, it allows the removal of the existing PodSecurityPolicies that were installed with v101.0.0+up3.17.7. After the installation of the latest version with the PSP flag disabled, when a cluster is upgraded to Kubernetes v1.25, no lingering PSPs should exist, enabling the upgrade and/or removal of the application.
