### ISSUE TITLE
[BUG] `rancher-webhook` pod erring out in k8s v1.25.2-rancher1-1 cluster and gets stuck into ContainerCreating state

### ISSUE THREAD

**Issue by rishabhmsra** [rancher/rancher#39923]
**Rancher Server Setup**
- Rancher version: v2.7-head(dadb4c0)
- Installation option (Docker install/Helm Chart): Docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):

**Information about the Cluster**
- Kubernetes version: v1.25.2-rancher1-1
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): ec2 node driver

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Admin
  - If custom, define the set of permissions:

**Describe the bug**

- Under `cattle-system` ns `rancher-webhook` pod fails to come up with below error in events:
```
Warning | FailedMount (16) | 36 secs ago | MountVolume.SetUp failed for volume "tls" : secret "rancher-webhook-tls" not found
Warning | FailedMount (7) | 1.3 mins ago | Unable to attach or mount volumes: unmounted volumes=[tls], unattached volumes=[tls kube-api-access-lxvmf]: timed out waiting for the condition
Normal | Scheduled | 16 mins ago | Successfully assigned cattle-system/rancher-webhook-5d7bf7f985-6q7ch to rishabhw1
```

**To Reproduce**

- Provision an ec2 node driver k8s `v1.25.2-rancher1-1` cluster(1cp, 1-etcd, 1-w)
- Wait for it to come into Active state.
- Explore cluster and under `cattle-system` ns observe that rancher-webhook pod is stuck into `ContainerCreating` state.

![webhook](https://user-images.githubusercontent.com/36376154/208089558-aea1fe87-46c7-475b-a92d-067cc3ab3dbf.png)

**Result**
- rancher-webhook pod is erring out.

**Expected Result**

- rancher-webhook pod should be up and running.

**Comment by crobby** [comment]
This will be fixed by https://github.com/rancher/webhook/pull/155 which includes a chart change so that the required secret will be present for rancher-webhook.

If you need to have it work before then, you can add the following annotation to the rancher-webhook service in the downstream cluster:

  annotations:
    need-a-cert.cattle.io/secret-name: rancher-webhook-tls

**Comment by rishabhmsra** [comment]
Re-opening this issue:
- On rancher v2.7-head(65089ee), provisioned a k8s v1.25.2-rancher1-1 custom cluster.
- rancher-webhook pod is using v0.3.0 image tag and is erring out.

![webhook](https://user-images.githubusercontent.com/36376154/208911515-5b9fec00-456e-4e63-884e-ddbdfd48db6b.png)

**Comment by crobby** [comment]
Sorry about that.  Turns out the webhook chart RC had a problem.  Fixing it now, should be ready to roll shortly.  Will advise when ready again.

**Comment by crobby** [comment]
https://github.com/rancher/webhook/pull/163 fixed this issue.  Moving back toTest

**Comment by rishabhmsra** [comment]
Validated on rancher v2.7-head(5398b07)
- Provisioned an ec2 node driver, k8s v1.25.2-rancher1-1 cluster(1-cp, 1-etcd, 1-w)
- rancher-webhook is up and running, hence closing the issue:

![webhook](https://user-images.githubusercontent.com/36376154/209341078-1392c604-a007-448b-9845-94816f705fc5.png)
