### ISSUE TITLE
Update KEv2 Operators to declare k8s 1.25 support

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#39929]
KEv2 operators (`aks-operator`, `eks-operator`, `gke-operator`) and their related charts don't seem to reference any APIs that are removed in k8s 1.25 and don't use PSPs.

However, the charts define `catalog.cattle.io/kube-version` as `>= 1.20.0-0 < 1.25.0-0` and it needs to be changed to `>= 1.20.0-0 < 1.26.0-0` so these charts declare as supporting 1.25.

Part of https://github.com/rancher/rancher/issues/39366

**Comment by annablender** [comment]
@Josh-Diamond The KEv2 operators are not installed via UI (hence [catalog.cattle.io/hidden](http://catalog.cattle.io/hidden): "true" annotation). Therefore, there is really not much to actually test here - we just wanted to bump [catalog.cattle.io/kube-version](http://catalog.cattle.io/kube-version) so it’s clean and clear that these charts were validated for use with 1.25 and don’t contain any k8s 1.25-removed resources. KEv2 operators should be checked while provisioning hosted clusters (AKS, EKS, or GKE) during testing for https://github.com/rancher/rancher/issues/39366 to make sure they deploy successfully and are healthy.

**Comment by Josh-Diamond** [comment]
Ticket #39929 - Test Results
---

With Docker on a single-node instance:

Verified on rancher `v2.7-99077b3d8475b1bd1ac1faec222172bb8143a09c-head`:
1. Fresh install of rancher `v2.7-head`
2. Provision a downstream AKS cluster w/ highest available k8s version
3. Verified:
    - k8s `v1.25.4`
    - `aks-operator:v1.1.0-rc1`
    - cluster comes up `Active`

---

4. Provision a downstream EKS cluster w/ highest available k8s version
5. Verified:
    - k8s `v1.24.8-eks-ffeb93d`
    - `eks-operator:v1.2.0-rc2`
    - cluster comes up `Active`
    
---

6. Provision a downstream GKE cluster w/ highest available k8s version
7. Verified:
    - k8s `v1.25.4-gke.2100`
    - `gke-operator:v1.1.5`
    - cluster comes up `Active`

---
    
Screenshots:

`All clusters in Active state`
<img width="1622" alt="Screenshot 2023-01-03 at 2 58 38 PM" src="https://user-images.githubusercontent.com/46494969/210448230-b369adaf-9fb8-461c-bb78-de0f539cbfc9.png">

`KEv2 Operators`
<img width="231" alt="Screenshot 2023-01-03 at 2 48 38 PM" src="https://user-images.githubusercontent.com/46494969/210448265-b71bf349-5a3d-454f-9eb8-8710ded07523.png">

`Available AKS k8s versions`
<img width="676" alt="Screenshot 2023-01-03 at 2 42 09 PM" src="https://user-images.githubusercontent.com/46494969/210448334-d64a1944-8a2d-4d74-920c-bdfcc5230159.png">

`Available EKS k8s versions`
<img width="666" alt="Screenshot 2023-01-03 at 3 00 18 PM" src="https://user-images.githubusercontent.com/46494969/210448451-8d125bb8-2bcc-44a1-baf2-5680b53deb6f.png">

`Available GKE k8s versions`
<img width="260" alt="Screenshot 2023-01-03 at 2 43 23 PM" src="https://user-images.githubusercontent.com/46494969/210448383-64b3c18c-aa8b-47b4-8411-3f949d848411.png">
