### ISSUE TITLE
[BUG] Rancher on docker fails to start up with no log messages

### ISSUE THREAD

**Issue by SanderKnauff** [rancher/rancher#39939]
**Rancher Server Setup**
- Rancher version: 2.6.3
- Installation option: Docker

**Information about the Cluster**
- Kubernetes version:  v1.21.7+k3s1
- Cluster Type (Local/Downstream): Custom

**User Information**
- What is the role of the user logged in? Admin 

**Describe the bug**
I've noticed my Rancher installation was unreachable today. It turned out that the docker container was in a boot-loop. The unfortunate thing is that `docker logs` did not show any recent log items on startup. Even manually using `docker run` to start the container just returned back to the shell prompt.
Upon investigation I found out that a `k3s-cluster-reset.log` file was present in the data directory. This file explained that there was a `reset-flag` file present in the db folder that prevented the cluster from starting.

This kind of information should be explained to the user when Rancher fails to boot.

**To Reproduce**
On a docker based rancher installation (v2.6.3 in my case) create an empty file named `/var/lib/rancher/k3s/server/db/reset-flag` in the docker container (or volume mount).
When starting Rancher, the container will exit quietly without explanation on why it is not working.

**Result**
The container will exit without explanation.

**Expected Result**
A clear error message should tell the user why the application startup has failed or directing them to a place with more information.

**Comment by Oats87** [comment]
This was more or less resolved with this PR: https://github.com/rancher/rancher/pull/35931

I would recommend updating your Rancher, as this change was introduced in `v2.6.4`
