### ISSUE TITLE
service is not populated for the LB instances in "ports" section in host detail view.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#3993]
Rancher Version: Build from master - Mar/16

Steps to Reproduce: 
Create a LB service - lb-1.

Launch the Host detail view of the host where LB instance is running.

In the ports tab, service is not populated for the LB instances.

<img width="1266" alt="screen shot 2016-03-16 at 11 14 41 am" src="https://cloud.githubusercontent.com/assets/4266958/13823781/62b2b360-eb68-11e5-9dce-ea1d4f897c44.png">

**Comment by tfiduccia** [comment]
Version - master UI 3/17
Verified fixed
