### ISSUE TITLE
DB data migration: Add one-time task for service/stack healthState update

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#3994]
The task would take care of updating service/stack having null health state. This is to cover upgrade use cases scenario where healthState used to be null.

**Comment by sangeethah** [comment]
Tested the following upgrade path:

v0.59.1 -> created stack with 2 services
Upgraded to V0.63.1 - > created  more stacks and services.

For service and stacks that were created in v0.59.1 , health_state column was "Null". 
Service and stacks that were created in v0.63.1 have health_state values.

Upgrade to v1.0.0-rc2
health_state for service and stacks that were created in v0.59.1 have  health_state values populated in DB.
