### ISSUE TITLE
[Monitoring] Update monitoring charts to declare k8s 1.25 support

### ISSUE THREAD

**Issue by prachidamle** [rancher/rancher#39954]
Kubernetes 1.25 drops support for following APIs, so additional changes need to be added to these charts to be able to support K8s 1.25

APIs deprecated:
HPA: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#horizontalpodautoscaler-v125
- Migrate manifests and API clients to use the autoscaling/v2 API version

PodDisruptionBudget https://kubernetes.io/docs/reference/using-api/deprecation-guide/#poddisruptionbudget-v125
- Migrate manifests and API clients to use the policy/v1 API version

Charts that need updating:

- rancher-monitoring (HPA deprecated)
- rancher-prometheus-adapter (PodDisruptionBudget deprecated)
- rancher-project-monitoring (HPA deprecated)
- rancher-grafana (HPA and PodDisruptionBudget deprecated)
- rancher-kube-state-metrics (PodDisruptionBudget deprecated)

**Comment by prachidamle** [comment]
@aiyengar2 please work with @geethub97 to review the changes needed here

**Comment by geethub97** [comment]
rancher-prometheus-adapter: 
no changes needed as the _helpers.tpl determines which version of the PDB to use
https://github.com/rancher/charts/blob/310619f5ee6d5a1713eb264b6b3118b6a856d5c5/charts/rancher-monitoring/101.1.0%2Bup40.1.2/charts/prometheus-adapter/templates/_helpers.tpl#L106

**Comment by ronhorton** [comment]
need to follow up with @geethub97 to understand what I'm looking for in this ticket.

**Comment by ronhorton** [comment]
This will be tested in k8s 1.25 monitoring testing; should also include a monitoring upgrade from previous version to current/rebased monitoring.

**Comment by ronhorton** [comment]
**Pass** Verified in `2.7.2-rc5`
Installed monitoring & alerting drivers fresh install 1.25
Installed on 1.24 and upgraded to 1.25
Tested with psp enabled=true & false
