### ISSUE TITLE
Update SR-IOV chart to declare k8s 1.25 support

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#39951]
[SR-IOV chart](https://github.com/rancher/charts/tree/dev-v2.7/charts/sriov) doesn't seem to reference any APIs that are removed in k8s 1.25 and don't use PSPs.

However, the chart defines `catalog.cattle.io/kube-version` as `>= 1.20.0-0 < 1.25.0-0` and it needs to be changed to `>= 1.20.0-0 < 1.26.0-0` so these charts declare as supporting 1.25.
Additionally, the latest version of the chart has `catalog.cattle.io/rancher-version: '>= 2.6.0-0 < 2.7.0-0'` and it should be updated to `catalog.cattle.io/rancher-version: '>= 2.7.0-0 < 2.8.0-0'` instead as the chart is for 2.7.x releases.

Part of https://github.com/rancher/rancher/issues/39366

**Comment by bmdepesa** [comment]
Since we can't test the actual SR-IOV chart due to a lack of hardware, we should ensure that the chart appears correctly in the Apps Marketplace.
