### ISSUE TITLE
Add 1.25.5 Support + Make 1.25 default

### ISSUE THREAD

**Issue by Sahota1225** [rancher/rancher#39960]
We [introduced 1.25.2 in KDM](https://github.com/rancher/kontainer-driver-metadata/pull/991) as part of [1.25 support issue](https://github.com/rancher/rancher/issues/38701).
v1.25.5 is now released, so we need to update KDM and RKE with v1.25.5.
Note: Only v1.25.5 will be released, so replace v1.25.2 with v1.25.5 in KDM.
Also, this is to be done in `dev-v2.7` KDM branch.

Additionally, please update v1.25.5 to be the default. Understanding it should be done in the following places:
* For RKE1 standalone:
	* Update https://github.com/rancher/kontainer-driver-metadata/blob/dev-v2.7/rke/k8s_version_info.go#L52, then bring the KDM updates to `release/v1.4` branch
* For RKE1 provisioned clusters:
	* Update https://github.com/rancher/kontainer-driver-metadata/blob/dev-v2.7/rke/k8s_version_info.go#L44 but also add line to retain `v1.24.x` as the default for Rancher 2.7.0 AND 2.7.1 (as both will stay on 1.24). We do not need to add other 2.6.x versions as this branch is used for v2.7.x versions only. For the same reason we're not doing any updates for `k8s_version_info.go` in `dev-v2.6` KDM branch as 1.24.x stays default for 2.6.x releases.
* For RKE2/k3s provisioned clusters:
	* Modify ranges in https://github.com/rancher/kontainer-driver-metadata/blob/dev-v2.7/channels.yaml#L4-L12 so versions starting from 2.7.2 default to 1.25.x. Same for `channels-rke2.yaml`.

Also, bump embedded Rancher k3s version to 1.25.5, similar to https://github.com/rancher/rancher/pull/39697

**Comment by rishabhmsra** [comment]
Validate on rancher v2.7-head(7d16a0d)
- Validated k8s v1.25.5 is present as default version for RKE1, RKE2 and k3s.
- Also RKE1, RKE2, K3s v1.25 cluster provisioned successfully:

![clusters](https://user-images.githubusercontent.com/36376154/210219426-85163364-079d-4239-81c8-57929d2a5791.png)

**Comment by sowmyav27** [comment]
@rishabhmsra Can you also verify the embedded k8s version on a docker install rancher is 1.25.5k3s version?

**Comment by rishabhmsra** [comment]
In docker install, local cluster is at v1.25.5+k3s1, please see the attached screenshot [here](https://github.com/rancher/rancher/issues/39960#issuecomment-1368816470). Closing the issue.
