### ISSUE TITLE
Prevent Upgrading RKE1 Cluster to 1.25 if PSP resources are detected in the cluster

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#39995]
Main issue: https://github.com/rancher/rancher/issues/38701

In the case of upgrading an existing RKE1 downstream cluster to 1.25, Rancher should prevent the upgrade if any PSP resources are left in the cluster.   

This is necessary because [PSP is removed from the API in k8s 1.25](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.25.md#podsecuritypolicy-is-removed-pod-security-admission-graduates-to-stable), which means users will lose access to the PSP resources once they upgrade the cluster to 1.25. Also, the upgrade will cause issues for Helm Apps, which define PSPs resources in the chart; for example, upgrading of such Apps will fail because Helm cannot find the PSPs it created before. 

One more note that the PSP resources are different from the  "enable PSP" feature Rancher added to the cluster.  Users can create PSPs resources without enabling the "enable PSP" feature in the cluster.

**Comment by jiaqiluo** [comment]
Here is Rancher's behavior after [this RKE PR](https://github.com/rancher/rke/pull/3132)  is merged: 

Steps:
- create an RKE1 1.24 cluster and create some PSP resources in the cluster
- trigger the upgrade from 1.24 to 1.25

Results:
Rancher UI shows the cluster in  "Updating" status with an error message ( see screenshot).
However, the cluster is still functional because the actual upgrade process is not triggered, and we have two ways to get out of the status:
- option 1: go to the cluster -> delete all PSP resources -> edit the cluster but do not change anything  -> save
- option 2: edit the cluster ->  change the k8s version back to 1.24 (see screentshot)-> save

<img width="1712" alt="Screen Shot 2022-12-29 at 3 41 29 PM" src="https://user-images.githubusercontent.com/6218999/210112153-1b819573-28f1-49af-a306-68e676a66e96.png">
<img width="1709" alt="Screen Shot 2022-12-29 at 3 42 31 PM" src="https://user-images.githubusercontent.com/6218999/210112154-26d2f0b1-90d0-4e2f-a402-aa76da3ad7eb.png">

**Comment by jiaqiluo** [comment]
waiting for a new rancher-webhook RC ...

**Comment by markusewalker** [comment]
This issue is covered in the overall K8s 1.25 test plan. Once that internal test plan has been marked as completed, I will close this issue accordingly.

**Comment by jiaqiluo** [comment]
This issue can be validated in the lastest v2.7-head.

**Comment by sowmyav27** [comment]
@markusewalker Can you please add comments on how this was prevented/errors seen on UI or in rancher logs?

**Comment by snasovich** [comment]
We want to Release Note / document this behavior: https://github.com/rancher/rancher/issues/39995#issuecomment-1368093175

**Comment by Martin-Weiss** [comment]
Why do we fail an upgrade in case 1.24 still has PSPs?

From my point of view It is totally valid to let the upgrade remove the PSP objects in case “PSA or Kubewarden or OPA has been enabled before the upgrade” on 1.24 or even during the upgrade to 1.25.

Customers might have setup PSA or Kubewarden / OPA on 1.24 and might or might not have configured role assignments to give all service accounts in the cluster access to an unrestricted PSP..

Do we really need to delete all PSP stuff manually before upgrading?

**Comment by snasovich** [comment]
For posterity, the behavior to fail upgrade if RKE1 has existing PSP resources has been reverted per https://github.com/rancher/rke/pull/3188 / https://github.com/rancher/rancher/issues/40652.
