### ISSUE TITLE
Support the use of PSACT in RKE1 1.25 cluster 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#39992]
Main issue: https://github.com/rancher/rancher/issues/38701

We want to support using PSACT (Pod Security Admission Configuration Template) in the RKE1 1.25 downstream cluster.

The implementation should be in [rancher/webhook](https://github.com/rancher/webhook)

Generally speaking,  rancher-webhook needs to mutate and validate the cluster spec accordingly when the filed `DefaultPodSecurityAdmissionConfigurationTemplateName` is set or updated/ or removed in the RKE1 1.25 downstream cluster.

**Comment by jiaqiluo** [comment]
waiting for a new rancher-webhook RC

**Comment by markusewalker** [comment]
This issue is covered in the overall K8s 1.25 test plan. Once that internal test plan has been marked as completed, I will close this issue accordingly.

**Comment by jiaqiluo** [comment]
This issue can be validated in the lastest v2.7-head.

**Comment by markusewalker** [comment]
Initial use cases have been validated in the internal test plan. Advanced workflows, not necessarily specific to being able to provision a PSACT enabled RKE1 cluster, that may have issues will be logged in separate issues.

Closing this issue for the above reason.
