### ISSUE TITLE
Monitoring Charts are failing to install on any cluster

### ISSUE THREAD

**Issue by jameson-mcghee** [rancher/rancher#39997]
**Rancher Server Setup**
- Rancher version: `v2.7-head` (Commit ID: 5398b07)
- Installation option (Docker install/Helm Chart): Docker and Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1, K3s, and RKE2
- Proxy/Cert Details: N/A

**Information about the Cluster**
- Kubernetes version: `v1.24.8-rancher1-1` and `v1.24.8+rke2r1`
- Cluster Type (Local/Downstream): Local and Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Verified on Infrastructure Provider, but likely will reproduce on others

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Admin Cluster Owner and Standard Cluster Owner

**Describe the bug**
When installing Monitoring Charts (Default Chart Version: `v101.1.0+up40.1.2`) on `local` and downstream clusters, an error is observed, preventing monitoring from being installed

**To Reproduce**
1. Spin up a Rancher server on `v2.7-head` (Commit ID: 5398b07)
2. Install Monitoring using the default Chart Version `v101.1.0+up40.1.2` on the `local` cluster

**Result**
- An error is observed that states "Error: YAML parse error on rancher-monitoring/charts/rke2ControllerManager/templates/pushprox-clients-rbac.yaml: error converting YAML to JSON: yaml: line 11: did not find expected key"
- In the `cattle-system` namespace, one of the `helm-operation-XXXXX:helm` pods is in an Error/Fail

**Expected Result**
Monitoring is installed successfully without error

**Screenshots**
**Monitoring is not present:**
![image](https://user-images.githubusercontent.com/13294321/209400701-cb92cda4-0fce-43da-acac-0ec6d13c3335.png)

**Error in the logs:**
![image](https://user-images.githubusercontent.com/13294321/209400727-77f7447e-014a-40c7-bcf3-fd88daab7d6f.png)

**Failed Install Pod Logs (Chart Version: `v101.1.0+up40.1.2`):**
[helm-operation-4lmcm_helm.log](https://github.com/rancher/rancher/files/10297127/helm-operation-4lmcm_helm.log)

**Additional Info:**
This issue appears to reproduce on the Default Chart Version. I have verified this does not reproduce on older Chart Version `v101.0.0+up19.0.3`.

**Successful Monitoring Chart Install:**
![image](https://user-images.githubusercontent.com/13294321/209830653-7b294580-ff40-4395-983f-138e48251de7.png)

**Successful Install Pod Logs (Chart Version: `v101.0.0+up19.0.3`):**
[helm-operation-vzvmr_undefined.log](https://github.com/rancher/rancher/files/10314789/helm-operation-vzvmr_undefined.log)

**Comment by ronhorton** [comment]
**Pass** verified on `rancher 2.7-head commit id da810a7`
provisioned downstream rke1 cluster with k8s version 1.24
`installed rancher-monitoring:101.1.0+up40.1.2`
monitoring installed with no errors
