### ISSUE TITLE
[RFE] Support pod selector in drain options

### ISSUE THREAD

**Issue by bk201** [rancher/rancher#40003]
**Is your feature request related to a problem? Please describe.**

[Longhorn doc](https://longhorn.io/docs/1.3.2/volumes-and-nodes/maintenance/#updating-the-node-os-or-container-runtime) advises that users should drain a node with `--pod-selector='app!=csi-attacher,app!=csi-provisioner'`. But the pod selector is not supported in [drain options](https://github.com/rancher/rancher/blob/28a84c710edf49a4acedfdc3624d427a36124672/pkg/apis/rke.cattle.io/v1/cluster.go#L63). Harvester relies on Rancher to upgrade the underlying RKE2 stack and would like to have this feature.

**Describe the solution you'd like**
Support passing pod selector (same as `kubectl drain --pod-selector`) when draining a node.

**Describe alternatives you've considered**
I can't find a workaround.

**Additional context**

**Comment by brandond** [comment]
`rancher/system-upgrade-controller:v0.11.0-dev.1 is available for testing. If you're able to give it a try, please do so. If it meets your needs I can tag a non-dev release.

**Comment by brandond** [comment]
Not stale. Now implement in the controller, needs to be used in Rancher.
