### ISSUE TITLE
[rancher-compose] logs option does not exit when output is finished

### ISSUE THREAD

**Issue by JayHaoDing** [rancher/rancher#4001]
When rancher-compose logs is called, it stalled even there is no more logs from container. docker-compose had the same issue but was fixed not long ago. Hopefully the change can be inherited to rancher-compose as well, thanks.

rancher-compose version: 0.7.2

PR from docker-compose repo: https://github.com/docker/compose/pull/2720

**Comment by deniseschannon** [comment]
Rancher-compose is based on libcompose, so it would need to be in docker/libcompose. Have you checked to see if the compatible PR has been made in that repo?

**Comment by JayHaoDing** [comment]
@deniseschannon unfortunately that PR has not made in docker/libcompose and ETA is unknown.

**Comment by martinbaillie** [comment]
@deniseschannon - this is now merged into libcompose and part of rancher-compose (I tried 0.8.2-rc2)

**Comment by deniseschannon** [comment]
Confirmed with v0.8.2 what @martinbaillie shared. Now if you do a `rancher-compose logs`, it exits when there are no more logs. 

Thanks @martinbaillie!!
