### ISSUE TITLE
Update ACI CNI to 5.2.3.5

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#40026]
There is ACI CNI version 5.2.3.5 available which is an upgrade to 5.2.3.4 we currently have included in KDM for RKE1 provisioned clusters.

**Comment by snasovich** [comment]
@siva-muni @snaiksat @LavanyaVaddavalli , with https://github.com/rancher/kontainer-driver-metadata/pull/1044 merged, please confirm ACI CNI is working as expected in newly introduced k8s versions in on `dev-v2.7-1222-patches` KDM branch.

**Comment by LavanyaVaddavalli** [comment]
@snasovich  ACI CNI 5.2.3.5 is working as expected on dev-v2.7-1222-patches kdm branch

**Comment by snasovich** [comment]
Closing the issue based on the comment above.
