### ISSUE TITLE
Docker-Machine SG is always picked which launching EC2 Host

### ISSUE THREAD

**Issue by bscott** [rancher/rancher#4002]
Rancher Version:
v0.63.0
Docker Version:
1.10
OS: 
Ubuntu 15
Steps to Reproduce: 
Create AWS Host via Rancher UI and Enter a Security Group to use that is pre-existing
Results: 
Host will always be placed in a SG called 'docker-machine', no matter what Security Group you choose.
Expected:
Selected Security Group should be used instead of Default being forced.

**Comment by deniseschannon** [comment]
I just tested with v0.63.1. I was unable to reproduce. My machine was placed in the security group that I selected. 

Can you check the server logs to see the docker-machine command that was passed to see which SG was passed?

**Comment by bscott** [comment]
I'l have to go back deep in the logs

**Comment by deniseschannon** [comment]
You can try again and see if it happens again and provide the logs. I wasn't able to reproduce.

**Comment by deniseschannon** [comment]
@bscott Let me know if you are still facing this issue. I think you guys have upgraded to a later release, so curious if this is still an issue for you.

**Comment by deniseschannon** [comment]
@bscott If you face this issue again, please re-open.
