### ISSUE TITLE
INSTALLATION FAILED: chart requires kubeVersion: < 1.25.0-0 which is incompatible with Kubernetes v1.26.0

### ISSUE THREAD

**Issue by dboevets** [rancher/rancher#40035]
Good day!
Try to install Rancher
Added the Helm Chart Repository rancher-latest
I get an error
Error: INSTALLATION FAILED: chart requires kubeVersion: < 1.25.0-0 which is incompatible with Kubernetes v1.26.0
Can you please tell me if there is a date when support will be implemented or is there a way to install to ignore versioning?

**Comment by tuupola** [comment]
There already seems to be a fix (https://github.com/rancher/rancher/commit/42736d951530520954be6c23f5f5329944e5dc4a) but it has not been [released](https://artifacthub.io/packages/helm/rancher-stable/rancher) yet.
