### ISSUE TITLE
[System Upgrade Controller (SUC)] Check for PSP compatibility in target cluster

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#40030]
Parent ticket: https://github.com/rancher/rancher/issues/39366

Kubernetes 1.25 drops support for PSP, so additional checks need to be added.

Every chart that ships with a PSP must be changed to add a new condition checking for the PSP capability in the target cluster:

**Capabilities check for Helm**

```{{- if .Capabilities.APIVersions.Has "policy/v1beta1/PodSecurityPolicy" }}```

This change allows the charts to still work with PSPs in Kubernetes versions prior to v1.25, and work in Kubernetes v1.25 or higher by skipping the installation of PSPs.

Charts that need updating as part of this issue: 
- system-upgrade-controller

(PSP and related objects are referenced at least in https://github.com/rancher/charts/blob/dev-v2.7/charts/system-upgrade-controller/101.0.0%2Bup0.3.3/templates/psp.yaml)

Since PSPs seems to be the only 1.25-removed feature/API used by SUC, as part of this issue it's expected that `catalog.cattle.io/kube-version` will be updated to `'>= 1.18.0-0 < 1.26.0-0'` to declare support for 1.25.

If a cluster role in a chart contains PSP's along with other permissions extra work may be needed to achieve the intended behavior of that role.

**Note:** Making SUC work with restrictive PSAs is out of the scope of this issue. Policy shipping with Rancher out of the box will be updated to exclude the namespace SUC runs in per https://github.com/rancher/rancher/issues/39996.

**Comment by markusewalker** [comment]
As this is part of the broader K8s 1.25 internal test plan, this will be tested alongside other test cases. Once tested, I will close this issue.

**Comment by markusewalker** [comment]
Validated the test cases associated with this issue in the internal test plan, so I will close this issue.
