### ISSUE TITLE
Several RKE2 provisioning tests are skipped, re-enable?

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#40055]
As per https://github.com/rancher/rancher/pull/36147 the following provisioning tests are skipped for RKE2 (but not k3s):
* `TestMachineTemplateClonedAnnotations`
* `TestMachineSetDeletePolicyOldestSet`
* `TestFiveNodesUniqueRolesWithDelete`
* `TestFourNodesServerAndWorkerRolesWithDelete`

It looks like the intent of the PR was to temporarily disable these tests for RKE2 due to some issues at the time, but it stuck.
So, we want to re-enable these tests and see if they work for RKE2 and decide the next steps based on the results (hopefully we can just re-enable them and that's it).

**Comment by Sahota1225** [comment]
Based on https://suse.slack.com/archives/C02PSP0VBLL/p1683138600553039 this thread closing the issue.
