### ISSUE TITLE
Unable to setup guestbook from catalog (Kubernetes)

### ISSUE THREAD

**Issue by roflmao** [rancher/rancher#4006]
Rancher Version: 0.63.1

Docker Version: 1.10.3

OS: Ubuntu 14.04.4

Steps to Reproduce: 
Setup kubernetes environment, enter catalog, try to setup K8s Example Guestbook

Results: 
Pressing launch gives:
```
Error: unknown command "catalog" for "kubectl"
Run 'kubectl --help' for usage.
```

Expected:
K8s Example Guestbook to setup.

**Comment by LLParse** [comment]
@roflmao I am unable to reproduce, could you please provide more information about how you setup your kubernetes environment (host registration, etc)

Could you provide the kubectld logs?
e.g. `docker logs r-Kubernetes_kubectld_1`

**Comment by deniseschannon** [comment]
@roflmao I also was unable to reproduce using the same versions that you are running. 

Did you change any of the defaults in the catalog?

**Comment by roflmao** [comment]
@LLParse: here is the logs:
```
time="2016-03-17T13:52:28Z" level=info msg="Starting kubectld on :8091" 
time="2016-03-17T13:57:50Z" level=info msg="kubectl -s http://master catalog -f -" 
time="2016-03-17T13:57:50Z" level=info msg="output: server.Output{ExitCode:1, StdOut:\"\", StdErr:\"Error: unknown command \\\"catalog\\\" for \\\"kubectl\\\"\\nRun 'kubectl --help' for usage.\\n\", Err:(*exec.ExitError)(0xc8200d8048)}" 
time="2016-03-17T13:59:14Z" level=info msg="kubectl -s http://master catalog -f -" 
time="2016-03-17T13:59:14Z" level=info msg="output: server.Output{ExitCode:1, StdOut:\"\", StdErr:\"Error: unknown command \\\"catalog\\\" for \\\"kubectl\\\"\\nRun 'kubectl --help' for usage.\\n\", Err:(*exec.ExitError)(0xc820122000)}" 
time="2016-03-18T07:54:29Z" level=info msg="kubectl -s http://master catalog -f -" 
time="2016-03-18T07:54:29Z" level=info msg="output: server.Output{ExitCode:1, StdOut:\"\", StdErr:\"Error: unknown command \\\"catalog\\\" for \\\"kubectl\\\"\\nRun 'kubectl --help' for usage.\\n\", Err:(*exec.ExitError)(0xc820122020)}" 
```

@deniseschannon: I did not change anything in the catalog, just hit Launch. Same goes for wordpress and cassandra examples.

**Comment by vincent99** [comment]
@LLParse possibly useful context:  the `catalog`command is supported Ed to be handled by kubectld.  It takes the yaml rules, applies variable interpolations, and then passes the results to `kubectl create`.  So somehow that is not happening and kubectl is receiving `catalog`, which it rightfully knows nothing about.

**Comment by LLParse** [comment]
@roflmao I am still unable to reproduce this, are you still running into this issue on v1.1.0-dev3?
