### ISSUE TITLE
[BUG] Cattle-cleanup job for imported clusters not pulling from configured private registry

### ISSUE THREAD

**Issue by sachua** [rancher/rancher#40068]
**Rancher Server Setup**
- Rancher version: **2.6.9**
- Installation option (Docker install/Helm Chart): **Helm Chart**
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): **Generic, 1.21**
- Proxy/Cert Details: **n/a**

**Information about the Cluster**
- Kubernetes version: **1.21**
- Cluster Type (Local/Downstream): **Downstream**
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): **Imported**

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:

**Describe the bug**

When deleting an imported cluster from Rancher Dashboard UI, the `cattle-cleanup` job that is created in the downstream cluster pulls from Dockerhub instead of the configured private registry.

**To Reproduce**

1. Import a generic cluster
2. Delete the generic cluster

**Result**

A `cattle-cleanup` job is created, but it pulls its image from Dockerhub and not the configured private registry for the cluster.

**Expected Result**

`cattle-cleanup` job should pull from the configured private registry

**Screenshots**

![image](https://user-images.githubusercontent.com/41395198/210761512-d6536e94-a15c-42a1-9a03-ef80355a11cf.png)
![image](https://user-images.githubusercontent.com/41395198/210761601-1f5f26c0-f5a6-4e78-be95-78b759c61792.png)

**Additional context**

SURE-8712

**Comment by skanakal** [comment]
This issue is reproducible even in rancher-v2.9.0-rc3 and comes from https://github.com/rancher/rancher/blob/release/v2.9/pkg/controllers/management/usercontrollers/controller.go#L305

Internal ref: SURE-8712

**Comment by Josh-Diamond** [comment]
awaiting requested alpha to resume testing

**Comment by Josh-Diamond** [comment]
Ticket #40068 - Test Results - ✅ 
---

Verified on Rancher `v2.9.1-rc1`:

| Scenario | Test Case | Result |
|---|---|---|
| 1. | Import downstream cluster => delete imported cluster via Rancher => verify `cattle-cleanup` job | ✅ |

---

Scenario 1 - ✅ 
1. Fresh install of Rancher `v2.9.1-rc1`
2. Provision a standalone cluster - ( I used RKE `v1.6.1` w/ k8s `v1.29.7-rancher1-1` )
3. Once `active`, import the cluster into Rancher
4. Wait for cluster to come up `active` in Rancher UI, then delete the imported cluster
5. Verified - cluster successfully deletes from Rancher UI
6. Using `kubectl`, describe the `cattle-cleanup` job and verify where `cleanup-agent` is pulled, using the following command:
```log
kubectl describe job <job_name_here> -n default
```
7. Verified - `cleanup-agent` image points to globally configured private registry; as expected
