### ISSUE TITLE
Norway East not a selectable region when create a node template for Azure

### ISSUE THREAD

**Issue by bspeagle** [rancher/rancher#40072]
When creating a new cluster using the Azure provider, for the node template region, Norway East is missing from the list of regions.

**Comment by bpedersen2** [comment]
Norway East is not  Azure region, see 
https://learn.microsoft.com/en-us/azure/reliability/availability-zones-service-support#azure-regions-with-availability-zone-support for a list of valid regions.

**Comment by bspeagle** [comment]
Norway East is most definitely a region and the article you provided doesn't say anything about Norway East not being a region 🤷‍♂️ 

It is listed as an available region: https://azure.microsoft.com/en-us/explore/global-infrastructure/geographies/#geographies

**Comment by bpedersen2** [comment]
Sorry, overlooked that.  

possibly https://github.com/rancher/rancher/blob/76c5c80bd1069bc14c8961014bd8b559b97bf22a/pkg/api/norman/customization/aks/listers.go#L500 is where the available regions a retrieved. maybe that gives you a hint?
