### ISSUE TITLE
[BUG] AKS Updating AgentPools with custom route table is not allowed

### ISSUE THREAD

**Issue by mjura** [rancher/rancher#40087]
**Rancher Server Setup**
- Rancher version: v2.6.9
- Installation option (Docker install/Helm Chart):
   - Helm Chart: stable-rancher-2.6.9
   - Kubernetes Cluster: v1.23.5
- Proxy/Cert Details: n/a

**Information about the Cluster**
- Kubernetes version: 1.24.6
- Cluster Type (Local/Downstream):
   - downstream
* Hosted = AKS Cluster

**User Information**
- What is the role of the user logged in?
  - Rancher Admin and Cluster Owner

**Describe the bug**

For AKS private cluster with network-plugin `kubenet`, with `userDefinedRouting` and imported in Rancher no update cluster update operations can be performed.

**To Reproduce**

1. Create AKS private cluster in following way:

```
az aks create --resource-group <RESOURCE_GROUP> --location eastus --name <CLUSTER_NAME> \
                        --network-plugin kubenet --network-policy calico --vnet-subnet-id "/subscriptions/..." \
                        --ssh-key-value /root/.ssh/id_rsa.pub --enable-private-cluster \
                        --enable-managed-identity --assign-identity "/subscriptions/..." \
                        --outbound-type userDefinedRouting
```

2. Import cluster in Rancher
3. Try to update AgentPool size or enable autoscaling.

**Result**

```
time="2022-10-21" level=info msg="Updating maximum count in node pool [...] for cluster [....]"
time="2022-10-21" level=error msg="error syncing 'cattle-global-data/...': handler aks-controller: failed to update cluster: containerservice.AgentPoolsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code=\"CustomRouteTableInvalidUpdateAttempt\" Message=\"Updating custom route table is not allowed. Custom route table was originally \\\"/subscriptions/...\\\" and a newly associated route table of \\\"\\\" was detected. Please revert back to the original route table. Please see https://aka.ms/aks/customrt for more information\", requeuing"
time="2022-10-21" level=info msg="Checking configuration for cluster [...]"
```

**Expected Result**

**Screenshots**

**Additional context**

**Comment by markusewalker** [comment]
**QA TEST PLAN**

Scenarios
|Scenario|Test Case|
|---|---|
|1|As a standard user, import an AKS cluster with the highest K8s version available, edit the cluster configuration and increase the agentpool size, validate that the agentpool increases|
|2|As a standard user, import a private AKS cluster with the highest K8s version available, edit the cluster configuration and increase the agentpool size, validate that the agentpool increases|
|3|As a standard user, import an AKS cluster with the second highest K8s version available, upgrade the K8s version to the highest K8s version available, edit the cluster configuration and increase the agentpool size, validate that the agentpool increases|
|4|As a standard user, import a private AKS cluster with the second highest K8s version available, upgrade the K8s version to the highest K8s version available, edit the cluster configuration and increase the agentpool size, validate that the agentpool increases|

**Comment by mjura** [comment]
@sowmyav27 I have finished testing it on Rancher `v2.7.2-rc5` with aks-operator and https://github.com/rancher/aks-operator/pull/146

**Comment by mjura** [comment]
## Additionnal QA

### Issue: #40087


### Problem

For AKS private cluster with network-plugin kubenet, with userDefinedRouting and imported in Rancher no update cluster update operations can be performed.

### Solution

We added the code which is passing node pool's subnet id to azure, during perfoming node pool update.

### Testing

Create Azure virtual subnet, create AKS private cluster and import it to Rancher. After it try to perform Node Pool update e.g. updating min or max nodes number.

### Engineering Testing
#### Manual Testing

1. Create Azure Virtual Network

2. Create AKS private cluster in following way:

```
az aks create --resource-group <RESOURCE_GROUP> --location eastus --name <CLUSTER_NAME> \
                        --network-plugin kubenet --network-policy calico --vnet-subnet-id "/subscriptions/..." \
                        --ssh-key-value /root/.ssh/id_rsa.pub --enable-private-cluster \
                        --enable-managed-identity --assign-identity "/subscriptions/..." \
                        --outbound-type userDefinedRouting
```

3. Import it in Rancher

4. Try to make Node Pool update from Rancher, e.g. change min or max number of nodes in Node Pool.

#### Automated Testing

Integration test exists.

**Comment by markusewalker** [comment]
Validated this on `v2.7-head` https://github.com/rancher/rancher/commit/2b2ed443065a9f38c4c5764461be33823eb6fec3. See details below:

**ENVIRONMENT DETAILS**
- Rancher install: Docker
- Rancher version: `v2.7-head`  https://github.com/rancher/rancher/commit/2b2ed443065a9f38c4c5764461be33823eb6fec3
- Browser: Chrome

**TEST RESULT**
|Scenario|Test Case|Result
|---|---|---|
|1|As a standard user, import an AKS cluster with the highest K8s version available, edit the cluster configuration and increase the agentpool size, validate that the agentpool increases|:white_check_mark:|
|2|As a standard user, import an AKS cluster with the second highest K8s version available, upgrade the K8s version to the highest K8s version available, edit the cluster configuration and increase the agentpool size, validate that the agentpool increases|:white_check_mark:|

**VALIDATION STEPS**

**Scenario 1**
1. In Azure portal, created the following resources in my resource group:
     - Virtual network with the default subnet
     - Route table configured with my default subnet just created
     - User managed identity with Owner permissions as a role assignment
2. Navigated to a Azure VM with `az` installed and already logged into my Azure subscription.
     - Ensured the Azure VM is in the same region as the VNET and route table.
3. Ran command `az aks create --resource-group <resource group> --location eastus2 --name <cluster name> --network-plugin kubenet --network-policy calico --vnet-subnet-id "/subscriptions/…/Microsoft.Network/virtualNetworks/<virtual network>/subnets/default" --ssh-key-value /…/id_rsa.pub --enable-private-cluster --enable-managed-identity --assign-identity "/subscriptions/…/Microsoft.ManagedIdentity/userAssignedIdentities/<user identity name>" --outbound-type userDefinedRouting --service-cidr 10.1.0.0/16 --dns-service-ip 10.1.0.10`
4. Validated that the private AKS cluster successfully deployed in my Azure resource group.
5. Navigated to Rancher > Cluster Management > Import Existing > Azure AKS.
6. Imported my private cluster into Rancher; validated this was successful and the cluster and nodes came up as `Active` in Cluster Management and Cluster Explorer.
7. Validated that all pods in the system project page came up as `Active`.
8. Edited the cluster's configuration and increased the node pool to have maximum of 5 nodes.
9. Validated that the node pool increased to 5 nodes and the cluster and nodes are `Active` in Cluster Management and Cluster Explorer.
_____
**Scenario 2**
1. Repeated scenario 1, steps 1-8, except ensured that my private AKS cluster is at v1.24.9 and not v1.25.5.
2. Edited the cluster's configuration and updated the K8s version to v1.25.5 for BOTH cluster and agent node pool.
3. Validated that the cluster and nodes upgraded to v1.25.5 in Cluster Management and Cluster Explorer.
4. Validated that all pods in the system project page remained as `Active`.
5. Edited the cluster's configuration and increased the node pool from 5 nodes to 8 nodes.
Validated that the node pool increased to 8 nodes and the cluster and nodes are `Active` in Cluster Management and Cluster Explorer.
