### ISSUE TITLE
[BUG] Add CIS hardening guide for RKE1 standalone clusters on k8s 1.25 

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#40094]
Following, https://github.com/rancher/rancher/issues/39894 we also need a hardening guide for RKE1 standalone clusters for clusters with k8s 1.25

**Comment by samjustus** [comment]
moving this out as its not a blocker

**Comment by macedogm** [comment]
@samjustus and @anupama2501 like #39894, the hardening guide is available in [github.com/rancher/rancher-docs/blob/release/v2.7.2/docs/pages-for-subheaders/rke1-hardening-guide.md](https://github.com/rancher/rancher-docs/blob/release/v2.7.2/docs/pages-for-subheaders/rke1-hardening-guide.md).

**Comment by samjustus** [comment]
@macedogm so what would the status of this be?

**Comment by macedogm** [comment]
Ready for QA to test.

**Comment by anupama2501** [comment]
QA Validate:
Fresh install:
1. Local rke1 cluster hardened PSA - k8s 1.25
2. Import rke1 hardened cluster with PSA - k8s 1.25
Upgrade:
1. Local 1.24 k8s cluster hardened with PSP on 2.7.0, upgrade rancher to v2.7-head, upgrade k8s to 1.25 by enabling hardening with PSA 
2. Rancher 2.7-head, k8s 1.24 PSP hardened, remove PSPs and upgrade to k8s 1.25 PSA hardened.

**Comment by anupama2501** [comment]
Verified on v2.7-head `a841a9e `
**Fresh install**
Local rke1 cluster hardened PSA - k8s 1.25
Import rke1 hardened cluster with PSA - k8s 1.25

**Upgrade:**
Local 1.24 k8s cluster hardened with PSP on 2.7-head,  upgrade k8s to 1.25 by enabling hardening with PSA
Rancher 2.7-head, k8s 1.24 PSP hardened, remove PSPs and upgrade to k8s 1.25 PSA hardened.

**Comment by anupama2501** [comment]
@macedogm can we also include the namespace exemptions in the hardening guide for standalone rke1 clusters [here](https://github.com/rancher/rancher-docs/blob/release/v2.7.2/docs/pages-for-subheaders/rke1-hardening-guide.md) ?

**Comment by macedogm** [comment]
> @macedogm can we also include the namespace exemptions in the hardening guide for standalone rke1 clusters [here](https://github.com/rancher/rancher-docs/blob/release/v2.7.2/docs/pages-for-subheaders/rke1-hardening-guide.md) ?

@anupama2501 please see PR https://github.com/rancher/rancher-docs/pull/529 with the requested instructions.

**Comment by anupama2501** [comment]
Verified the changes and they look good. Closing the issue.
