### ISSUE TITLE
Performance improvements to "host" config items update: DB data migration is required

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#4009]
To track performance improvements for host config item update (triggered by dns/metadata changes)

**Comment by alena1108** [comment]
DB data migration is required for service_index_id field (moving from Data to table field). Should be one time task

**Comment by sangeethah** [comment]
Tested upgrade from v0.69.1 -> v1.0.0-rc1.

After upgrade ,  instance table has  new column - "service_index_id" which is populated with service_index_id value which is from the "serviceIndexId" from Data field.
