### ISSUE TITLE
[BUG] Cannot install latest opa-gatekeeper verison 101.1.0+up3.10.0 - timeout

### ISSUE THREAD

**Issue by ronhorton** [rancher/rancher#40108]
**Rancher Server Setup**
- Rancher version: `2.7.head commit id 8062f1e`
- Installation option (Docker install/Helm Chart): `Helm`
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): `RKE1`
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: `1.24`
- Cluster Type (Local/Downstream): `downstream aws ec2`
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: `admin`

**Describe the bug**
installation of opa-gatekeeper 101.1.0+up3.10.0 fails - timeout reached and chart marked `fail`

**To Reproduce**
Install opa gatekeeper 101.1.0+up3.10.0

**Result**
Failure to install; timeout

**Expected Result**
opa gatekeeper installed

**Screenshots**

<img width="1762" alt="2023-01-09_16-41-35" src="https://user-images.githubusercontent.com/89212856/211415074-2bebb6fe-7d97-4f30-9eac-0a60b55883fd.png">

**Additional context**
`
Deployment is not ready: cattle-gatekeeper-system/gatekeeper-controller-manager. 2 out of 3 expected pods are ready
Starting delete for "gatekeeper-update-namespace-label" ServiceAccount
serviceaccounts "gatekeeper-update-namespace-label" not found
creating 1 resource(s)
Starting delete for "gatekeeper-update-namespace-label" ClusterRole
clusterroles.rbac.authorization.k8s.io "gatekeeper-update-namespace-label" not found
creating 1 resource(s)
Starting delete for "gatekeeper-update-namespace-label" ClusterRoleBinding
clusterrolebindings.rbac.authorization.k8s.io "gatekeeper-update-namespace-label" not found
creating 1 resource(s)
Starting delete for "gatekeeper-update-namespace-label" Job
jobs.batch "gatekeeper-update-namespace-label" not found
creating 1 resource(s)
Watching for changes to Job gatekeeper-update-namespace-label with timeout of 10m0s
Add/Modify event for gatekeeper-update-namespace-label: ADDED
gatekeeper-update-namespace-label: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
Add/Modify event for gatekeeper-update-namespace-label: MODIFIED
gatekeeper-update-namespace-label: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
Add/Modify event for gatekeeper-update-namespace-label: MODIFIED
Error: failed post-install: job failed: BackoffLimitExceeded`

previous version installs without error

**Comment by ronhorton** [comment]
gatekeeper-controller-manager logs:
`{"level":"error","ts":1673301634.0044096,"logger":"cert-rotation","msg":"secret is not well-formed, cannot update webhook configurations","error":"Cert secret is not well-formed, missing ca.crt","errorVerbose":"Cert secret is not well-formed, missing ca.crt\ngithub.com/open-policy-agent/cert-`

`{"level":"error","ts":1673301641.2368248,"msg":"Reconciler error","controller":"cert-rotator","object":{"name":"gatekeeper-webhook-server-cert","namespace":"cattle-gatekeeper-system"},"namespace":"cattle-gatekeeper-system","name":"gatekeeper-webhook-server-cert","reconcileID":"23d997fd-4247-4b43-b45f-cda50fc859d7","error":"Operation cannot be fulfilled on mutatingwebhookconfigurations.admissionregistration.k8s.io \"gatekeeper-mutating-webhook-configuration\": the object has been modified; please apply your changes to the latest version and try again","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/open-policy-agent/gatekeeper/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/src/github.com/open-policy-agent/gatekeeper/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:234"}`

**Comment by ronhorton** [comment]
gatekeeper-update-namespace-label fails with 
`Warning: existing pods in namespace "cattle-gatekeeper-system" violate the new PodSecurity enforce level "restricted:v1.24"
Warning: gatekeeper-update-namespace-label-74rbn: seccompProfile
error: You must be logged in to the server (admission webhook "rancher.cattle.io.namespaces" denied the request: Unauthorized)`

**Comment by ronhorton** [comment]
possibly occurring for the same reason: https://github.com/rancher/rancher/issues/39913

**Comment by aiyengar2** [comment]
@doflamingo721 @vardhaman22 are we sure that the approach in https://github.com/rancher/charts/pull/2367 suggested from your comment is the right approach to take?

cc: @jiaqiluo @stormqueen1990 @ronhorton, I believe our expectation was that all system chart namespaces were to be excluded from the list of namespaces where PSPs are enforced. As a result, the above PR to have OPA gatekeeper itself patch the namespace it exists in would not be necessary right?

**Comment by aiyengar2** [comment]
Caught up with the context for this issue offline; for anyone else reading this issue, the reason why we are taking the approach of allowing users to patch PSA-related labels via helm chart install is because it is something that has been supported by the upstream chart, not something introduced by Rancher. This would not be a feature that is in-scope for any other Rancher feature chart since the expectation would be for users to either handle upgrading labels on namespaces for PSAs manually or for the namespaces to be exempt from PSA enforcement if they are a system namespace.

Since Rancher intends to support features that our upstream chart supports to avoid too much divergence from upstream, this fix is being patched.

**Comment by prachidamle** [comment]
@doflamingo721 With the PR to add the necessary permissions for `updatepsa` verb, can we test this chart in following cases and post results:
1. With these fixes, log in as an global admin user and try to install the chart
2. With these fixes, log in as an cluster-admin user and try to install the chart
3. With these fixes, log in as a project-owner and try to install the chart
4. With these fixes, log in as a project-member  user and try to install the chart

**Comment by doflamingo721** [comment]
@prachidamle @aiyengar2 I tested the gatekeeper chart with the fixes for the scenarios you had mentioned and following were the results:
1. Log in as an **global admin user** and try to install the chart: The chart installation was successful without any errors.
 
![Screenshot from 2023-02-07 13-27-31](https://user-images.githubusercontent.com/34883075/217235570-04b8e8fd-ead8-47df-8a0c-e261b5add433.png)

2. Log in as an **cluster-owner** user and try to install the chart: The chart installation was successful without any errors.
 
![Screenshot from 2023-02-07 14-22-59](https://user-images.githubusercontent.com/34883075/217235341-00b61cda-90cc-45df-a97c-bd0cf8a5bc9f.png)

3. Log in as a **project-owner** and try to install the chart: The chart installation failed with the following error
![Screenshot from 2023-02-07 13-58-38](https://user-images.githubusercontent.com/34883075/217235949-bfcbd50e-1f16-4a58-8cff-47cde57ed832.png)

4. Log in as a **project-member** user and try to install the chart: The chart installation failed with the following error
![Screenshot from 2023-02-07 14-05-22](https://user-images.githubusercontent.com/34883075/217236065-1a97d1e1-552b-4651-8a50-2e84587d3aaa.png)

**Comment by doflamingo721** [comment]
@prachidamle I tested the the gatekeeper chart version `101.0.0-up3.9.0` on v2.7-head k8s version 1.24 and following were the results:

1. Log in as an **global admin user** and try to install the chart: The chart installation was successful without any errors.
![image](https://user-images.githubusercontent.com/34883075/217551910-49bdca12-0ede-4fd5-9865-767c2f06117b.png)

2. Log in as an **cluster-owner** user and try to install the chart: The chart installation was successful without any errors.
![Screenshot from 2023-02-08 15-10-41](https://user-images.githubusercontent.com/34883075/217552333-cc9941e3-4b29-49f6-99ee-8ce2c0d6f034.png)

3. Log in as a **project-owner** and try to install the chart: The chart installation failed with the following error

![Screenshot from 2023-02-08 15-16-50](https://user-images.githubusercontent.com/34883075/217552635-f89ccf7f-fb49-454c-93ae-00ebac735e22.png)

4. Log in as a **project-member** user and try to install the chart: The chart installation failed with the following error
![Screenshot from 2023-02-08 15-20-43](https://user-images.githubusercontent.com/34883075/217552739-52d59b0a-a53b-4ae0-b150-bec0e9748d4e.png)

The previous version of gatekeeper chart installation also fails for users with `project-owner` and `project-member` roles.

**Comment by rishabhmsra** [comment]
Validated on rancher v2.7-head(8287913)
- Created a k8s v1.24.10-rancher1-1, ec2 node driver cluster(1-cp, 1-e, 2-w)
- Installed OPA gatekeeper chart version `102.0.0+up3.10.0`, chart installed successfully.
- Validated the chart by creating the constraints using the default templates - k8sallowedrepos and k8srequiredlabels. Constraints are working as expected.
- Also validated the chart upgrade from `101.0.0+up3.9.0` to `102.0.0+up3.10.0` and upgrade was successful.

Result:
- Chart is getting installed successfully and constraints are also working as expected, hence closing the issue.

![opa](https://user-images.githubusercontent.com/36376154/218723137-0442b4d8-7fbc-402d-862e-79058e5f0365.png)
