### ISSUE TITLE
Proxy-mode: ipvs activation problem when setting up clusters in rke2 infrastructure

### ISSUE THREAD

**Issue by koraykutanoglu** [rancher/rancher#40101]
I want to activate ipvs as proxy-mode when setting up kubernetes cluster in RKE2 infrastructure. but I don't know how to add it in cluster.yaml. because even though I write proxy-mode: ipvs in kubectl args part, it doesn't work. How do I specify this expression in cluster.yaml?

**Comment by brandond** [comment]
I don't know what the ipvs field you're looking at represents of why you'd chose to look at that to check to see if ipvs is enabled. I would probably just look at the kube-proxy pod logs to see if it's using ipvs mode, or iptables.
