### ISSUE TITLE
API v2-beta 

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#4010]
Add an new version of the api that renames enviornment to stack then fix everything that breaks.

Note: project to environment -> will occur after 1.2 
https://github.com/rancher/rancher/issues/6132

**Comment by cjellick** [comment]
Done, right @sangeethah ?

**Comment by sangeethah** [comment]
@cjellick: v2-beta renames  enviornment to stack. But  renaming project to environment is not done yet.

**Comment by sangeethah** [comment]
@deniseschannon , v2-beta renames enviornment to stack. But renaming project to environment is not done yet.

Is this change is also scoped for this release ?

**Comment by deniseschannon** [comment]
Please note that the issue has been updated and test it for exactly what the issue says.

environment -> stack


@sangeethah

**Comment by sangeethah** [comment]
Tested with rancher-server version -v1.2.0-pre3.

Environment has been renamed to stack for v2-beta apis. Validation tests uses stack related apis when testing with v2-beta apis.
