### ISSUE TITLE
Zombies on servers

### ISSUE THREAD

**Issue by Negashev** [rancher/rancher#4011]
I think a good solution would be to write the number of zombie processes on servers

![screenshot 66](https://cloud.githubusercontent.com/assets/4653589/13857317/369faede-ec9b-11e5-92ca-68a42e7f6d13.png)

**Comment by Negashev** [comment]
Also it does not hurt to add a method of stopping the container. In order to be able to send a container command "service stop"

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
