### ISSUE TITLE
Errors in the local cluster when informer tries to list resources whose kind no longer exists

### ISSUE THREAD

**Issue by maxsokolovsky** [rancher/rancher#40133]
Related issue: https://github.com/rancher/rancher/issues/39733

**Is your feature request related to a problem? Please describe.**
When a downstream cluster is upgraded to a new K8s version, some of its API resources may be undefined, like PodSecurityPolicies. Or a group/version of a resource has changed. Rancher, however, is still watching over the resources that were part of the downstream's capabilities from before the K8s version upgrade. There are constant informer errors, as Rancher tries to list and watch for resources that are unknown to the downstream cluster's API server.

**Describe the solution you'd like**
When a downstream cluster is upgraded, and its status is Ready, stop and restart all its controllers in the local cluster.

**Describe alternatives you've considered**

**Additional context**
This might be good not just for smooth upgrades from PSPs without needing a Rancher restart, but also for other cases, such as when group/version of some resources might have changed across K8s versions.

**Comment by maxsokolovsky** [comment]
# QA Testing

#### Use as many downstream cluster types as possible - RKE1, RKE2, AKS, EKS, GKE.
Run an HA Rancher cluster with Kubernetes v1.24. Provision a downstream cluster with Kubernetes v1.24 and Pod Security Policies enabled. When it runs, ensure there are no PSP-related log messages in the local cluster.

Upgrade the downstream cluster to v1.25 (you might need to explicitly disable PSP as a feature of the cluster, delete all PSP found in the downstream cluster, and also set the defaultPSPTemplate to an empty string on the cluster object).

Wait for the downstream cluster to fully update. Check the local cluster's logs and ensure there are no messages from informers that fail to list and watch PSP resources in the downstream cluster.

Once you've tested multiple downstream clusters, run the same tests on Rancher running Kubernetes v1.25.

**Comment by dasarinaidu** [comment]
I have executed below test cases and did not see any new issues related to this change and closing this ticket.

**Details:**
Rancher Version : `v2.7-f2faf1a8aa1081301e1fe6c21637fe9b7044f188-head` (v2.7.2-rc6)

**Test cases:
Fresh install with rancher on 1.24 :  Rancher version: v2.7.2-rc6:**

1. Created RKE1(hardened Cluster with 1.24) cluster and Upgraded to 1.25
2. Created RKE2(hardened Cluster with 1.24) cluster and Upgraded to 1.25
3. Created EKS cluster(1.23) and Upgraded to 1.24
4. Created AKS cluster(1.24) and Upgraded to 1.25
5. Created GKE cluster(1.24) and Upgraded to 1.25

**Fresh install with rancher on 1.25 :  Rancher version: v2.7.2-rc6:**

1. Created RKE1(hardened Cluster with 1.24) cluster and Upgraded to 1.25
2. Created RKE2(hardened Cluster with 1.24) cluster and Upgraded to 1.25
3. Created EKS cluster(1.23) and Upgraded to 1.24
4. Created AKS cluster(1.24) and Upgraded to 1.25
5. Created GKE cluster(1.24) and Upgraded to 1.25

**Upgrade from 2.7.0 to 2.7-head(v2.7.2-rc6) with rancher on 1.24**

1. Created RKE1(hardened Cluster with 1.24) cluster and Upgraded to 1.25
2. Created RKE2(hardened Cluster with 1.24) cluster and Upgraded to 1.25
3. Created EKS cluster(1.23) and Upgraded to 1.24
4. Created AKS cluster(1.24) and Upgraded to 1.25
5. Created GKE cluster(1.24) and Upgraded to 1.25
