### ISSUE TITLE
[RFE] Support to reverse proxy for non root location base path

### ISSUE THREAD

**Issue by S0LERA** [rancher/rancher#40134]
**Is your feature request related to a problem? Please describe.**
A lot of technologies allow to serve their contents and work from a different base path than root (/). This is very useful when working behind a reverse proxy, to serve different applications from the same server.

For example: https://www.myserver.com/rancher

**Describe the solution you'd like**
Allow rancher works from different path that root (/). For example, with an environment variable like `BASE_PATH=/rancher` or some variable on configuration.

**Comment by S0LERA** [comment]
Any updates on this?

**Comment by S0LERA** [comment]
Any updates on this?

**Comment by S0LERA** [comment]
Any updates on this?

**Comment by S0LERA** [comment]
Any updates on this?

**Comment by S0LERA** [comment]
Any updates on this?

**Comment by S0LERA** [comment]
Any updates on this?

**Comment by Anatol-Beck** [comment]
I am facing the same issue and would appreciate if someone could answer here.
