### ISSUE TITLE
[Docs] Document how to setup a PSA restricted-by-default local cluster

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#40149]
We'll need to document which namespaces need to be exempt from a restricted-by-default local cluster.

These are the current local system namespaces: https://github.com/rancher/rancher/blob/release/v2.7/pkg/settings/setting.go#L27

This is a list of downstream namespaces (check on release branch for updates): https://github.com/rancher/rancher/blob/487df1636bacd94453e9b71141e56d8ea4a2f897/pkg/data/management/podadmissionconfigurationtemplate_data.go#L12-L32

QA: setup a local cluster with these instructions and check that it functions

**Comment by crobby** [comment]
@cbron Is there a particular place/format where these things need to be documented?

**Comment by cbron** [comment]
You can just document it here for now, but then it will need to end up in https://github.com/rancher/rancher-docs
Though _where_ in rancher_docs, I am not sure yet. We can talk to docs team.

It's mainly about enumerating the namespaces (or other configs) you would need to safely run Rancher, given a default restricted policy everywhere.

**Comment by cbron** [comment]
@crobby you can add docs here now: https://github.com/rancher/rancher-docs/blob/release/v2.7.2/docs/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/pod-security-standards.md

**Comment by sowmyav27** [comment]
Reopening for QA Test Template

**Comment by crobby** [comment]
Template added to https://github.com/rancher/rancher-docs/pull/423#issuecomment-1476885752

**Comment by anupama2501** [comment]
Reopening the ticket: 

@crobby I validated bringing up a local cluster on v2.7-head with the namespace exemptions mentioned [here](docs/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/psa-restricted-exemptions.yaml). 

However when I tried to create an rke2/k3s downstream node driver cluster, the cluster won't come up active and stay in `provisioning` state as the job for rke2 clusters get deployed in the `fleet-default` namespace and the pods have the status 
```
(combined from similar events): Error creating: pods "anuk3slocalpsa-ec-94b4a6dc-zrlgb-machine-provision-gvxwn" is forbidden: violates PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "machine" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "machine" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "machine" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "machine" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
```
I tried adding the `fleet-default` also in the exemption list and that worked for rke2/k3s node driver clusters.

Can we also add `fleet-default` in the exemption list when the psa is set to `restricted`?

Steps:
1. Create an rke1 standalone cluster with the cluster.yml as [attached]([cluster-psp copy.yml.txt](https://github.com/rancher/rancher/files/11023719/cluster-psp.copy.yml.txt)
)
2. Follow the steps mentioned in the PR to harden the RKE1 cluster with PSA config.
3. Follow the rancher docs to proceed with rancher installation https://ranchermanager.docs.rancher.com/pages-for-subheaders/install-upgrade-on-a-kubernetes-cluster
4.  Once rancher come up active, create an rke2/k3s node driver cluster with k8s 1.25 and default options - as either admin or a standard users.
5. RKE2/k3s clusters won't come up active and stay in provisioning state.

**Comment by crobby** [comment]
The PR to add fleet-default has been merged.  Moving back to To Test

**Comment by anupama2501** [comment]
Verified the namespace exemption list has `fleet-default` added in the docs. Since, it was already validated with `fleet-default` added to namespaces [here](https://github.com/rancher/rancher/issues/40149#issuecomment-1477152814) closing the ticket.
