### ISSUE TITLE
[Forwardport v2.7] node upgrade failed with 'node not found' in v2.6.4

### ISSUE THREAD

**Issue by kinarashah** [rancher/rancher#40147]
Forward port issue for https://github.com/rancher/rancher/issues/37634.

**Comment by kinarashah** [comment]
Available to test with RKE `v1.4.3-rc4` and Rancher v2.7-head once https://drone-publish.rancher.io/rancher/rancher/8851 is green.

**Comment by Josh-Diamond** [comment]
Ticket #40147 - Test Results - ✅ 
---

With Docker on a single-node instance:

Verified on rancher `v2.7-0170920c4fe7d4d86de7ea3af7a43958287c7394-head`:

**Kubelet**

| Scenario | Test Case | Result |
|---|---|---|
| 1. Fresh install [`2.7-head`] | Provision a downstream RKE1 Custom cluster w/ Amazon Cloud provider enabled + Node name != hostname | ✅ |

---

**Kube-proxy**

| Scenario | Test Case | Result |
|---|---|---|
| 1. Fresh install | Provision Custom cluster on 2.6-head + misconfigure Node name from cloud provider assigned hostname => Verify hostname-override value to args of kube-proxy value is same as node-name passed by registration cmd | ✅ |

---

Full testing report available internally via Confluence

Note: `useInstanceMetadataHostname` is not present on cluster.yml after provisioning by default; an additional ticket will be created to further track and address this

**Comment by rishabhmsra** [comment]
Re-opening for below validations.

**Comment by rishabhmsra** [comment]
**Validated on rancher v2.7.2-rc4, KDM pointing to dev-v2.7 :**

**Scenario https://github.com/rancher/rancher/issues/37634#issuecomment-1441329096**

- Created following single node all role, ec2 node driver clusters with Amazon(in-tree) enabled - v1.25.6-rancher2-1, v1.24.10-rancher3-1, v1.23.16-rancher2-1. Also while provisioning, make sure to set `useInstanceMetadataHostname` as `true`.
- `--hostname-override` is set to the node name provided by cloud provider:
```
ps -ef | grep -i kube-proxy
root        9443    9421  0 08:54 ?        00:00:00 kube-proxy --cluster-cidr=<REDACTED>/16 --kubeconfig=/etc/kubernetes/ssl/kubecfg-kube-proxy.yaml --healthz-bind-address=127.0.0.1 --v=2 --bind-address=<REDACTED> --hostname-override=ip-<REDACTED>.us-east-2.compute.internal
```
- Created deployment, service and patched the service with "externalTrafficPolicy":"Local" as mentioned [here](https://github.com/rancher/rancher/issues/18483#issue-415771391) 
```
kubectl describe svc | grep Local
External Traffic Policy:  Local
```
- externalTrafficPolicy=Local works:
```
for node in $NODES; do curl -s $node:$NODEPORT | grep -i client_address; done
client_address=<REDACTED>
```
- Similarly provisioned single node all role, ec2 node driver clusters with Amazon(in-tree) enabled - v1.25.6-rancher2-1, v1.24.10-rancher3-1, v1.23.16-rancher2-1 again, but **without** `useInstanceMetadataHostname`.
- Followed above steps and `--hostport-override` is NOT set to the node name provided by cloud provider:
```
ps -ef | grep -i kube-proxy
root        9492    9472  0 08:40 ?        00:00:01 kube-proxy --healthz-bind-address=127.0.0.1 --v=2 --bind-address=<REDACTED> --cluster-cidr=<REDACTED>/16 --hostname-override=rishabh-25-sn1 --kubeconfig=/etc/kubernetes/ssl/kubecfg-kube-proxy.yaml
```
- With externalTrafficPolicy=Local service stopped working - got no respone from `for node in $NODES; do curl -s $node:$NODEPORT | grep -i client_address; done`
