### ISSUE TITLE
json pretty fix, causes value to be on separate lines

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4014]
Version - master 3/17

Steps to Reproduce: 
1.  Add a label to host where key = json and value = {"hi": {"key": "value"}, "array": [1,2,3,4,5]}
2.  Add a service and go to Scheduling and Add Scheduling Rule
3.  Select json in key and then use click on drop-down for value

Results: the value is now a list of the json broken up by the comma
![image](https://cloud.githubusercontent.com/assets/11514927/13861817/a35a47fe-ec4c-11e5-9c99-f07c94a5773d.png)

Expected: should still be 1 selection

**Comment by vincent99** [comment]
This is not new or because of the pretty printing, it's because its splitting values on comma (and JSON happens to contain them).

**Comment by tfiduccia** [comment]
Version - master 3/18
Verified fixed
