### ISSUE TITLE
[RFE] Filter resources by multiple projects or namespaces through the API

### ISSUE THREAD

**Issue by cmurphy** [rancher/rancher#40140]
Relates to https://github.com/rancher/rancher/issues/38427

SURE-5698

**Is your feature request related to a problem? Please describe.**

From Jira:

Filtering by multiple namespaces 
* For convenience filtering by specific Projects would help, but would not remove the requirement to filter (possibly a lot of) namespaces  
* This can be optimised by NOT the namespaces provided (aka give me all resources from NOT system namespaces)

**Describe the solution you'd like**

There should be an API that allows you to list resources filtered by one or more projects or namespaces, to enable this dashboard functionality:

![image](https://user-images.githubusercontent.com/1220710/211928536-928221a0-41b0-4f51-9144-2d30f3396013.png)

**Comment by cmurphy** [comment]
I created test images that include this change and the change for https://github.com/rancher/rancher/issues/40141 in

cmurpheus/rancher:40155-40583
cmurpheus/rancher-agent:40155-40583

Neither have been approved so they are subject to change but most likely the API will not change, unless UI team has concerns or recommendations.

Documentation for filtering by projects and namespaces is in https://github.com/rancher/rancher/wiki/Rancher-API-Extensions. Documentation for regular filtering options is in https://github.com/rancher/steve#filter.

**Comment by richard-cox** [comment]
As part of https://github.com/rancher/dashboard/issues/9478 i validated that multiple namespaces / projects and NOTing those worked. I didn't thrash or test for edge cases, though from a dev validate side of things would be ok closing this
