### ISSUE TITLE
remove icon on scheduling tab in Add Service is not aligned properly

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4015]
Version - master 3/17

Steps to Reproduce: 
1.  Add Service
2.  In Scheduling tab click on Add Scheduling Rule

Results: the remove icon on right is not aligned properly
![image](https://cloud.githubusercontent.com/assets/11514927/13861898/18096814-ec4d-11e5-8997-9efa83cd5729.png)

Expected: Should be aligned properly

**Comment by lvuch** [comment]
fix in https://github.com/rancher/ui/pull/542

**Comment by deniseschannon** [comment]
Verified with master that this is fixed. 

<img width="392" alt="screen shot 2016-03-17 at 10 58 38 pm" src="https://cloud.githubusercontent.com/assets/11410997/13869621/d8aab53c-ec93-11e5-9a74-5ffea0dc90dc.png">
