### ISSUE TITLE
[BUG] Pin Installed Version for Rancher-Webhook

### ISSUE THREAD

**Issue by KevinJoiner** [rancher/rancher#40159]
**Rancher Server Setup**
- Rancher version: 2.7-HEAD
- Installation option (Docker install/Helm Chart): N\A

**Information about the Cluster**
- Kubernetes version: N\A
- Cluster Type (Local/Downstream): Local

**User Information**
- What is the role of the user logged in? Admin

**Describe the bug**
Users can only specify the minimum version of the installed rancher-webhook chart. This means that the latest version will always be installed for the user by the Rancher server

This can cause users to unknowingly install different Webhook versions across different clusters, even if the Rancher version is the same. 

This also means that the user has the potential to run a Rancher server and Rancher-Webhook combination that has not been properly tested. 

**To Reproduce**

1. Start a Rancher server with version v2.7.0
2. Wait for the Rancher-Webhook to be installed 
   - `kubectl rollout status deployment rancher-webhook -n cattle-system`
3.  Note the version of Rancher-Webhook
   - `kubectl get deployments -n cattle-system rancher-webhook -o jsonpath='{.spec.template.spec.containers[*].image}`

1. Start a Rancher server with version v2.7-HEAD
2. Wait for the Rancher-Webhook to be installed 
   - `kubectl rollout status deployment rancher-webhook -n cattle-system`
3. Note the version of Rancher-Webhook
   - `kubectl get deployments -n cattle-system rancher-webhook -o jsonpath='{.spec.template.spec.containers[*].image}`

**Result**
Rancher-Webhook versions are the same

**Expected Result**
Rancher-Webhook version change depending on the version of Rancher

**Comment by KevinJoiner** [comment]
After some investigation, packaged and released Rancher images are unaffected.  This is because the charts used in our images are pulled from a local cache that does not contain images later than what was in the [rancher/charts](https://guthub.com/rancher/charts) release-v2.x branch at the time of asset generation.

**Comment by maxsokolovsky** [comment]
## QA Testing

### Root cause
When Rancher installs system charts, it only receives the minimum version of the chart. It may upgrade a system chart if it detects that there is a newer available version. For the webhook chart, we don't want this, as there may be
incompatilibities.

### What was fixed, or what changes have occurred
We now pin the webhook chart version to an exact version. 
The existing `rancher-webhook-min-version` is now deprecated, there is `rancher-webhook-version`.
Nothing changes for other system charts, like fleet.

### Areas or cases that should be tested
1. rancher-webhook
1. fleet


### What areas could experience regressions?
1. rancher-aks-operator
1. rancher-eks-operator
1. rancher-gke-operator

### Steps

#### Use the new `rancher-webhook-version` setting
1. Set it to some fixed value (like `2.0.3+up0.3.3`) when starting Rancher. Or use the `RANCHER_WEBHOOK_VERSION` environment variable.
2. When Rancher starts up, ensure that the version of the `rancher-webhook` chart matches the one you specified.
3. Set it to some other value, restart Rancher. Observe that the there is a new release with the new version.

#### Use the existing `fleet-min-version` setting
1. Set it to some older version (like `102.0.0+up0.6.0`) when starting Rancher.
2. When Rancher starts up, ensure that the version of the `fleet` is higher than the one you specified.
It should be the latest available at the moment.

**Comment by anupama2501** [comment]
QA to validate:

**P0 use case:**
1. Fresh install rancher on v2.7.5-rc3
2. Verify the webhook chart version matches the latest webhook version on both local cluster and downstream clusters
3. Verify the logs of webhook pod 

**Upgrade test case:**
1. Install rancher on v2.7.4 and notice the webhook chart matches the min version. 
2. Verify the webhook version on a downstream as well as the local cluster
3. Upgrade rancher version to v2.7.5-rc3/v2.7-head
5. Notice the webhook version is changed to a new version [latest version] on both downstream and local clusters.
6.  Verify the logs of webhook pod 

#| Test case | Steps | Status | Comments
--- | --- | --- | --- | --- 
1 | Use the new rancher-webhook-version setting  | <li>P0 use case but pass the env var `RANCHER_WEBHOOK_VERSION` while installing rancher. </li> <li>Verify the version on both downstream and local cluster matches the specified version. </li> <li>Verify a new webhook chart is shown in the dropdown </li> | | References the test case mentioned by Max: Use the new rancher-webhook-version setting
2 | Use an incorrect webhook version setting | <li>P0 use case but pass the env var `RANCHER_WEBHOOK_VERSION` while installing rancher. </li> <li>Verify the version on both downstream and local cluster matches the specified version. </li> <li>Verify a new webhook chart is shown in the dropdown </li> |  | References the test case mentioned by Max:  Provide a non-existent exact version setting
3 | Verify roll back using rancher backup/restore charts |  |
4 | Run P0 use cases for fleet chart and verify the chart works as expected? | | | references Use the existing fleet-min-version setting
5 | Hosted rancher P0 use case | <li>Create a hosted rancher setup on v2.7.4</li> <li> Upgrade the host</li> <li>verify the webhook version on the downstream clusters and the local cluster should have the upgraded version.</li> | | 
6 | Create an aks/gke/eks clusters and run upgrade checks on the clusters | <li></li> | |  References What areas could experience regressions?

**Comment by brudnak** [comment]
## Reproduction Environment

Reproduction not requred.

## Validation Environment


| Component                        | Version / Type                                                                     |
| -------------------------------- | ---------------------------------------------------------------------------------- |
| Rancher version before upgrade   | v2.7.4                                                                             |
| Rancher version after upgrade    | v2.7-f0d4078f4fa75b303ce276c3f4b12fc465b1ba2a-head                                 |
| Rancher commit link              | https://github.com/rancher/rancher/commit/f0d4078f4fa75b303ce276c3f4b12fc465b1ba2a |
| Installation option              | Helm (high availability)                                                           |
| If Helm Chart k8s cluster        | v1.25.10+k3s1                                                                      |
| Cert Details                     | Let's Encrypt / `traefik`                                                          |
| k3s ha external db               | Aurora MySQL 5.7.mysql_aurora.2.11.1                                               |
| Helm version                     | v2.16.8-rancher2                                                                   |
| Downstream cluster type          | RKE1                                                                               |
| Downstream K8s version           | v1.26.4                                                                            |
| Authentication providers enabled | local                                                                              |
| Logged in user role              | Admin, Restricted Admin, Standard User                                             |
| Browser type                     | Microsoft Edge                                                                     |
| Browser version                  | 113.0.1774.57                                                                      |

## Validation steps

<table>
    <tbody>
        <tr>
            <th>#</th>
            <th>Scenario</th>
            <th>Steps</th>
            <th>Expected</th>
            <th>Actual & Pass/Fail</th>
        </tr>
        <tr>
            <td>5</td>
            <td>Hosted rancher P0 use case, upgrade client first 2.7.4 >> 2.7.5-rc</td>
            <td>
                <ol>
                    <li>Create a hosted/tenant rancher setup on v2.7.4</li>
                    <li>Upgrade the tenant</li>
                    <li>verify the webhook version on the downstream clusters and the local cluster should have the
                        upgraded version.</li>
                    <li>Versions on tenant:</li>
                    <ul>
                        <li>`Local` cluster `BEFORE` upgrade: rancher/rancher-webhook:`v0.3.4`</li>
                        <li>`Local` cluster `AFTER` upgrade: rancher/rancher-webhook:`v0.3.5-rc7`</li>
                        <li>`Downstream` cluster `BEFORE` upgrade: rancher/rancher-webhook:`v0.3.4`</li>
                        <li>`Downstream` cluster `AFTER` upgrade: rancher/rancher-webhook:`v0.3.5-rc7</li>
                    </ul>
                    <li>Upgrade the host</li>
                    <li>Versions on host:</li>
                    <ul>
                        <li>`Local` cluster `BEFORE` upgrade: rancher/rancher-webhook:`v0.3.4`</li>
                        <li>`Local` cluster `AFTER` upgrade: rancher/rancher-webhook:`v0.3.5-rc7`</li>
                    </ul>
                    <li>Verify the webhook upgrades in the host cluster</li>
                </ol>
            </td>
            <td>Expected: Webhook upgrades successfully and P0 checks pass</td>
            <td>Actual: Webhook upgrades successfully and P0 checks pass<br><br>Pass/Fail: ✅<code>PASS</code></td>
        </tr>
    </tbody>
</table>

- Test case 6 checked on:
  - start rancher version: ==> `2.6.13`
  - upgraded to: ==> `v2.7-f0d4078f4fa75b303ce276c3f4b12fc465b1ba2a-head`

<table>
    <tbody>
        <tr>
            <th>#</th>
            <th>Scenario</th>
            <th>Steps</th>
            <th>Expected</th>
            <th>Actual & Pass/Fail</th>
        </tr>
        <tr>
            <td>6</td>
            <td>Hosted rancher P0 use case, upgrade host first 2.6.13 >> 2.7-head</td>
            <td>
                <ol>
                    <li>Create a hosted rancher setup on v2.6.13</li>
                    <li>Upgrade the host</li>
                    <li>verify the webhook version on the downstream clusters and the local cluster should have the
                        upgraded version.</li>
                    <li>Versions on host:</li>
                    <ul>
                        <li>`Local` cluster `BEFORE` upgrade: rancher/rancher-webhook:`v0.2.10`</li>
                        <li>`Local` cluster `AFTER` upgrade: rancher/rancher-webhook:`v0.3.5-rc7`</li>
                    </ul>
                    <li>Upgrade the tenant</li>
                    <li>Versions on tenant:</li>
                    <ul>
                        <li>`Local` cluster `BEFORE` upgrade: rancher/rancher-webhook:`v0.2.10`</li>
                        <li>`Local` cluster `AFTER` upgrade: rancher/rancher-webhook:`v0.3.5-rc7`</li>
                        <li>`Downstream` cluster `BEFORE` upgrade: rancher/rancher-webhook:`v0.2.10`</li>
                        <li>`Downstream` cluster `AFTER` upgrade: rancher/rancher-webhook:`v0.3.5-rc7`</li>
                    </ul>
                    <li>Verify the webhook upgrades in the host cluster</li>
                </ol>
            </td>
            <td>Expected: Webhook upgrades successfully and P0 checks pass</td>
            <td>Actual: Webhook upgrades successfully and P0 checks pass<br><br>Pass/Fail: ✅<code>PASS</code></td>
        </tr>
    </tbody>
</table>

- For case 8:
- `eksctl` install
- k8s `v1.25.9-eks-0a21954`
- `v2.7-f0d4078f4fa75b303ce276c3f4b12fc465b1ba2a-head`
- Installation command:

```shell
 helm install rancher-csp-adapter rancher-dev-v2.7/rancher-csp-adapter \
    --namespace cattle-csp-adapter-system \
    --set aws.enabled=true \
    --set aws.roleName=$REDACTED_ROLE_NAME \
    --set-string aws.accountNumber=$REDACTED_ACC_NUM \
    --version 2.0.2+up2.0.2-rc2 \
    --set global.cattle.systemDefaultRegistry=docker.io \
    --set devMode=true
```

<table>
    <tbody>
        <tr>
            <th>#</th>
            <th>Scenario</th>
            <th>Steps</th>
            <th>Expected</th>
            <th>Actual & Pass/Fail</th>
        </tr>
        <tr>
            <td>8</td>
            <td>CSP adapter P0 use cases</td>
            <td>
                <ol>
                    <li>P0 CSP use case</li>
                </ol>
            </td>
            <td>Expected: csp adapter working as expected</td>
            <td>Actual: csp adapter working as expected<br><br>Pass/Fail: ✅<code>PASS</code></td>
        </tr>
    </tbody>
</table>
