### ISSUE TITLE
Not all alerts are showing up on Slack channel using AlertManagerConfigs

### ISSUE THREAD

**Issue by neuhausskaio** [rancher/rancher#40165]
**Setup**

Rancher version: 2.6.9
Browser type & version: Chrome Version 107.0.5304.110 (Official Build) (x86_64)
Monitoring version: rancher-monitoring:100.1.3+up19.0.3

**Describe the issue**

When configuring alerts with the AlertManagerConfigs under the Rancher WebUI, not all alerts are firing up on the slack channel. However, when using the old method with Routes and Receivers, everything works as expected. 

These alerts were generated by purpose so I could test them. Basically, I powered off one node and also added some pods in crashloopback state so I could check the behavior both on webUI and Slack.

Here is the screenshot of some alerts on slack:

![image](https://user-images.githubusercontent.com/52573935/209562014-a60f45fe-7871-471a-a782-1cf4b6939c62.png)

Here is the screenshot of alerts showing in the webUI:

![image](https://user-images.githubusercontent.com/52573935/209562046-c1b4294b-723c-405e-bca3-5c8d2c1ea1fb.png)

Note that the alert KubedeploymentReplicasMismatch is not appearing on slack.

Maybe it could be an additional step that could be included in the documentation, or I'm missing something.

If I configure using the old method with routes and receivers, everything works as expected. 

I noticed that when I configured using routes and receivers, automatically the alertmanager.yaml config was updated, but using the alertmanagerConfigs with the slack secret doesn't change this config. Maybe there is something related to that.

**To reproduce**

go into Monitoring >> Alerting >> AlertManagerConfigs, create one alert config on the namespace cattle-monitoring-system, and add the receivers pointing to the secret with the slack URL (In this part you may encounter what is possible a bug: https://github.com/rancher/dashboard/issues/7517 so it might be necessary change the YAML directly).  Yaml file with the configs:

```
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: teste-slack
  annotations:
    {}
  creationTimestamp: '2022-12-26T17:08:03Z'
  generation: 7
  labels:
      {}
  namespace: cattle-monitoring-system
  resourceVersion: '2144086'
  uid: 489eef13-e578-4f38-94a6-5cd5de0387bf
  fields:
    - teste-slack
    - 29m
spec:
  receivers:
    - name: alertas
      slackConfigs:
        - apiURL:
            key: slackurl
            name: apiurl
          channel: alertas-cluster-prod
          sendResolved: true
          text: '{{ template "slack.rancher.text" . }}'
          httpConfig: {}
  route:
   groupBy:
      - ...
    groupInterval: 5m
    groupWait: 30s
    receiver: alertas
    repeatInterval: 10m
__clone: true
```

**Comment by MKlimuszka** [comment]
This needs to be reproduced in 2023-Q1-2.6x, 2023-Q1-2.6x, and if it cannot be reproduced in those, 2.6.9
