### ISSUE TITLE
Rancher Webhook should allow omitted fields when validating PodSecurityAdmissionConfigurationTemplates

### ISSUE THREAD

**Issue by HarrisonWAffel** [rancher/rancher#40166]
[Prior implementation of the `PodSecurityAdmissionConfigurationTemplate` validator](https://github.com/rancher/webhook/pull/157) within the Rancher webhook required that users specify a valid level and version value for each of the `defaults` fields (`enforce`, `warn`, `audit`). However, after testing how Kubernetes validates `PodSecurityAdmissionConfiguration` objects, we found that users _can_ omit certain elements of the `defaults` field without issue. So, we need to allow users to omit these fields when creating rancher specific `PodSecurityAdmissionConfigurationTemplate`'s.

Users should be able to omit the level, version, or both for any field within the `defaults` list.

**Comment by HarrisonWAffel** [comment]
The webhook has been bumped in Rancher, so this issue can now be tested. Detailed test steps can be found in the original rancher/webhook PR.

**Comment by markusewalker** [comment]
This issue will be tested alongside the other test cases in the overall 1.25 test plan. Once that is done, I will close this issue at that time.

**Comment by markusewalker** [comment]
Verified in the internal test plan that the backend is working as expected. In testing, noted there is an issue while editing as YAML, but logged a separate UI [issue](https://github.com/rancher/dashboard/issues/8057) for this behavior.

Marking this issue as completed.
