### ISSUE TITLE
[BUG] Re-importing a cluster fails due to webhook not being fully deleted

### ISSUE THREAD

**Issue by maxsokolovsky** [rancher/rancher#40164]
**Rancher Server Setup**
- Rancher version: v.2.7.2-pre-release
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):

**Information about the Cluster**
- Kubernetes version: v1.25
- Cluster Type (Local/Downstream): Downstream imported (RKE1 or AKS)

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:

**Describe the bug**
Re-importing previously detached clusters on fails on v2.7.2. Tried on v2.7.0 and had no issues.
The imported cluster may be AKS or even RKE1. The initial import is fine, detachment is fine. But when you import again by applying the manifests, you get:
```
clusterrole.rbac.authorization.k8s.io/proxy-clusterrole-kubeapiserver unchanged
clusterrolebinding.rbac.authorization.k8s.io/proxy-role-binding-kubernetes-master unchanged
clusterrolebinding.rbac.authorization.k8s.io/cattle-admin-binding unchanged
clusterrole.rbac.authorization.k8s.io/cattle-admin unchanged
Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "rancher.cattle.io.namespaces": failed to call webhook: Post "[https://rancher-webhook.cattle-system.svc:443/v1/webhook/validation/namespaces?timeout=10s](https://rancher-webhook.cattle-system.svc/v1/webhook/validation/namespaces?timeout=10s)": service "rancher-webhook" not found
Error from server (NotFound): error when creating "STDIN": namespaces "cattle-system" not found
```

**To Reproduce**
1. Provision any K8s cluster.
2. Import it into Rancher (generic or managed).
3. Optionally ensure that the cluster has a `rancher-webhook` release is deployed in a couple of minutes.
4. Detach the cluster from Rancher.
5. Import the cluster again and apply the necessary manifests that Rancher provides in the URL.

**Result**
Error when deploying the necessary resources in the cluster, not when the cluster object is created in Rancher when I click import.

**Expected Result**
Cluster is properly re-imported. 

**Screenshots**

**Additional context**

**Comment by maxsokolovsky** [comment]
When an imported cluster is detached, Rancher tries to delete all resources associated with it from the cluster.
But both mutating and validating webhook configurations (each named `rancher.cattle-io`) remain in the cluster after detachment.
And they refer to the webhook deployment that no longer exists when a cluster is detached, since it's a Rancher resource that is deleted on detachment.
The workaround is to manually delete both and try importing again.

**Comment by dasarinaidu** [comment]
I reproduce the issue on v2.7-head : `v2.7-6316baf1697cca085e073ccd5e9e7a3bc542d0e5-head`

**Steps to Reproduce:** 
1. Provision RKE/EKS/GKE cluster
2. Import it into Rancher (generic or managed).
3. Make sure imported cluster is Active
4. Delete the Cluster
5. Import the cluster again and apply the necessary manifests that Rancher provides in the URL

**Actual :**
1. Reimport GKE cluster :
`UI Error : failed to communicate with cluster: error generating service account token: Internal error occurred: failed calling webhook "rancher.cattle.io.namespaces": failed to call webhook: Post "https://rancher-webhook.cattle-system.svc:443/v1/webhook/validation/namespaces?timeout=10s": service "rancher-webhook" not found`

Logs :
```
2023/01/20 03:59:37 [ERROR] error syncing 'c-t8c8w': handler gke-operator-controller: error generating service account token: Internal error occurred: failed calling webhook "rancher.cattle.io.namespaces": failed to call webhook: Post "https://rancher-webhook.cattle-system.svc:443/v1/webhook/validation/namespaces?timeout=10s": service "rancher-webhook" not found, requeuing
2023/01/20 04:00:04 [ERROR] error syncing '_all_': handler user-controllers-controller: failed to start user controllers for cluster c-t8c8w: secrets "cattle-global-data/" not found, requeuing
2023/01/20 04:00:07 [ERROR] error syncing 'c-t8c8w': handler gke-operator-controller: error generating service account token: Internal error occurred: failed calling webhook "rancher.cattle.io.namespaces": failed to call webhook: Post "https://rancher-webhook.cattle-system.svc:443/v1/webhook/validation/namespaces?timeout=10s": service "rancher-webhook" not found, requeuing
2023/01/20 04:00:34 [ERROR] error syncing '_all_': handler user-controllers-controller: failed to start user controllers for cluster c-t8c8w: secrets "cattle-global-data/" not found, requeuing
2023/01/20 04:00:38 [ERROR] error syncing 'c-t8c8w': handler gke-operator-controller: error generating service account token: Internal error occurred: failed calling webhook "rancher.cattle.io.namespaces": failed to call webhook: Post "https://rancher-webhook.cattle-system.svc:443/v1/webhook/validation/namespaces?timeout=10s": service "rancher-webhook" not found, requeuing
2023/01/20 04:01:04 [ERROR] error syncing '_all_': handler user-controllers-controller: failed to start user controllers for cluster c-t8c8w: secrets "cattle-global-data/" not found, requeuing


2023/01/20 04:00:01 [ERROR] error syncing '_all_': handler user-controllers-controller: failed to start user controllers for cluster c-t8c8w: secrets "cattle-global-data/" not found, requeuing
E0120 04:00:16.218844      34 reflector.go:141] pkg/mod/github.com/rancher/client-go@v1.25.4-rancher1/tools/cache/reflector.go:170: Failed to watch *v1.Secret: the server has asked for the client to provide credentials (get secrets.meta.k8s.io)
2023/01/20 04:00:31 [ERROR] error syncing '_all_': handler user-controllers-controller: failed to start user controllers for cluster c-t8c8w: secrets "cattle-global-data/" not found, requeuing

2023/01/20 04:00:01 [ERROR] error syncing '_all_': handler user-controllers-controller: failed to start user controllers for cluster c-t8c8w: secrets "cattle-global-data/" not found, requeuing
E0120 04:00:03.291065      33 reflector.go:141] pkg/mod/github.com/rancher/client-go@v1.25.4-rancher1/tools/cache/reflector.go:170: Failed to watch *v1.ClusterRoleBinding: the server has asked for the client to provide credentials (get clusterrolebindings.meta.k8s.io)
2023/01/20 04:00:31 [ERROR] error syncing '_all_': handler user-controllers-controller: failed to start user controllers for cluster c-t8c8w: secrets "cattle-global-data/" not found, requeuing
E0120 04:00:48.278125      33 reflector.go:141] pkg/mod/github.com/rancher/client-go@v1.25.4-rancher1/tools/cache/reflector.go:170: Failed to watch *v1.ClusterRole: the server has asked for the client to provide credentials (get clusterroles.meta.k8s.io)
2023/01/20 04:01:01 [ERROR] error syncing '_all_': handler user-controllers-controller: failed to start user controllers for cluster c-t8c8w: secrets "cattle-global-data/" not found, requeuing
2023/01/20 04:01:31 [ERROR] error syncing '_all_': handler user-controllers-controller: failed to start user controllers for cluster c-t8c8w: secrets "cattle-global-data/" not found, requeuing


2023/01/20 04:30:47 [ERROR] error syncing 'p-4m6pr/creator-project-owner': handler mgmt-auth-prtb-controller: projects.management.cattle.io "c-m-c7ztldgd/p-4m6pr" not found, requeuing
2023/01/20 04:30:47 [INFO] [mgmt-auth-prtb-controller] Deleting roleBinding crb-7ro4p3q5y3
2023/01/20 04:30:53 [ERROR] error syncing 'c-t8c8w': handler gke-operator-controller: error generating service account token: Internal error occurred: failed calling webhook "rancher.cattle.io.namespaces": failed to call webhook: Post "https://rancher-webhook.cattle-system.svc:443/v1/webhook/validation/namespaces?timeout=10s": service "rancher-webhook" not found, requeuing
```

**Reimport RKE :**
UI : `Cluster goes to unavailable state with error Cluster agent is not connected` 
```
Seeing Below ERROR at Kubeconfig terminal after running the cluster registration command
Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "rancher.cattle.io.namespaces": failed to call webhook: Post "https://rancher-webhook.cattle-system.svc:443/v1/webhook/validation/namespaces?timeout=10s": service "rancher-webhook" not found
Error from server (NotFound): error when creating "STDIN": namespaces "cattle-system" not found
Error from server (NotFound): error when creating "STDIN": namespaces "cattle-system" not found
Error from server (NotFound): error when creating "STDIN": namespaces "cattle-system" not found
Error from server (NotFound): error when creating "STDIN": namespaces "cattle-system" not found
```

**Comment by maxsokolovsky** [comment]
# QA testing

1. Get a v2.7-head Rancher instance and start it with a v2.7-head agent image. For example, `CATTLE_AGENT_IMAGE=rancher/rancher-agent:v2.7-head` or use `maxsokolovsky/rancher:rancher-agent`.
2. Provision a separate cluster outside Rancher. You can use any managed service or local cluster on your machine.
3. Import this cluster into Rancher, ensure there are no errors, and Rancher completes the import by marking the cluster as Active.
4. Detach the cluster (delete it from Rancher).
5. Try importing it again and ensure there are no errors.

**Comment by dasarinaidu** [comment]
Completed testing with all the other cluster types except EKS cluster Import. I do not have IMA access to validate this test case. I created an EIO ticket to get access. I will validate this card once I get the access. 

https://github.com/rancherlabs/eio/issues/1538

**Comment by dasarinaidu** [comment]
I have validated this issue on `v2.7-f2faf1a8aa1081301e1fe6c21637fe9b7044f188-head` - re-import cluster is working as expected and closing this card.

**Validation Details:**
Users : Admin & Standard
Clusters : Generic / AKS / GKE

**Steps to Reproduce:**

1. Provision RKE/AKS/GKE cluster
2. Import it into Rancher (generic or managed).
3. Make sure imported cluster is Active
4. Delete the Cluster
5. Re-Import the cluster again and apply the necessary manifests that Rancher provides in the URL

**Actual :**
1. Reimport is successful and the cluster came back to Active
2. No Error Logs were seen
