### ISSUE TITLE
Clearing value of `fleetWorkspaceName` leads to cluster deletion

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#40180]
**Rancher Server Setup**
- Rancher version: v2.6.6 (should be reproducible on later releases such as 2.6.9 and 2.7.0 as well)
- Installation option (Docker install/Helm Chart): Not important
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details: None

**Information about the Cluster**
- Kubernetes version: 1.22.9 (Not important though)
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): RKE1 provisioned cluster (custom or node driver) 

**User Information**
- What is the role of the user logged in? - Admin

**Describe the bug**
Clearing the value of `fleetWorkspaceName` causes the cluster to get deleted by Rancher

**To Reproduce**
1. Provision RKE1 downstream cluster (either Custom or Node Provisioned (with any infrastructure provider)) would do
2. Locate the corresponding `cluster.management.cattle.io` object and modify it to remove `fleetWorkspaceName`. This can be done via any mechanism, e.g.:
	1. `kubectl edit cluster.management.cattle.io (cluster-id)` and removing `fleetWorkspaceName: fleet-default` from the `spec`
	1. Calling Rancher API's endpoint `https://${RANCHEREND}/v3/clusters/${CLUSTERID}?_replace=true` with the payload representing the cluster object with missing `fleetWorkspaceName` field (`_replace=true` is key as it's required for removal to happen).

**Result**
The cluster goes to "Removing" state and gets deleted.

**Expected Result**
Not exactly sure. This may be "functions as designed", but it makes it too easy to delete the cluster accidentally - one would not expect the cluster to get _deleted_ when such fairly minor update is done.

**Additional context**
I suspect this is happening in the code responsible for generating provisioning cluster objects from management cluster objects. More specifically, these lines https://github.com/rancher/rancher/blob/ca9fea2d38dae9a4408646af6514f3a001ac609e/pkg/controllers/provisioningv2/cluster/controller.go#L177-L178 return `nil` provisioning cluster object. Then Wrangler's `Apply` mechanism is used to apply updates, but `Apply` by default also deletes existing objects if there is not a matching object in the desired set (which in this case has `nil` for provisioning cluster object). This is evident by the following line from Rancher log - "provisioning-cluster-create" matches handler name as passed here https://github.com/rancher/rancher/blob/ca9fea2d38dae9a4408646af6514f3a001ac609e/pkg/controllers/provisioningv2/cluster/controller.go#L102:
```
2022/10/10 15:34:51 [DEBUG] DesiredSet - Delete provisioning.cattle.io/v1, Kind=Cluster fleet-default/c-8zt45 for provisioning-cluster-create c-8zt45
```
Then since the provisioning cluster object is deleted, another handler syncs that to deletion of management cluster object.

**Comment by jakefhyde** [comment]
We should probably update the webhook to prevent unsetting this field once it has been set.

**Comment by snasovich** [comment]
The proposed changes to webhook result in some other issues like the inability to delete clusters, which we're looking into. Depending on the amount of changes needed to fix this, it may slip into the next milestone.

**Comment by snasovich** [comment]
With https://github.com/rancher/webhook/pull/217 merged this can be moved to "To Test" after there is new webhook chart with included changes available.
cc: @bfbachmann @KevinJoiner

**Comment by Josh-Diamond** [comment]
Ticket #40180 - Test Results - ✅ 
---

Verified with HA Helm Rancher on `v2.7-c842598344ee552daf5cf4e8d31d6e11621e07ad-head`:

| Scenario | Test Case | Result |
|---|---|---|
| 1. | Manually editing the `clusters.management.cattle.io` object and removing its `fleetWorkspaceName` field gets rejected by the webhook | ✅ |
| 2. | Clusters can still be assigned to new Fleet workspaces | ✅ |
| 3. | Clusters are indirectly deleted, when deleting their corresponding Fleet workspace | ✅ |
| 4. | Regular deletion of RKE1 + RKE2 clusters continues to work | ✅ |

---

Scenario 1 -
1. Fresh install of rancher `v2.7-head`
2. Copy kubeconfig of local cluster, paste it in a local yaml file, and export via terminal to have kubectl access
3. Provision a downstream RKE1 AWS Node driver cluster
4. Once `active`, grab the cluster-id, and run the following command in your (local) terminal:
```kubectl
kubectl edit cluster.management.cattle.io <cluster-id>
```
5. Navigate to `spec > fleetWorkspaceName` and remove the entire field, then save and quit
6. Verified - attempting to remove `fleetWorkspaceName` and then save, gets rejected by webhook; as expected

---

Scenario 2 -
1. Fresh install of rancher `v2.7-head`
2. Navigate to `Cluster Explorer > Namespaces > All Namespaces` of local cluster and create a new namespace: `fleet-default-2`
3. Provision a downstream RKE1 AWS Node driver cluster
4. Once `active`, grab the cluster-id and run the following command in your (local) terminal:
```kubectl
kubectl edit cluster.management.cattle.io <cluster-id>
```
5. Navigate to `spec > fleetWorkspaceName` and change this to namespace created in step 2, `fleet-default-2`, then save + quit
6. Verified - Valid changes accepted and successfully applied; as expected

---

Scenario 3 -
1. Picking up where Scenario 2 left off, navigate to `Cluster Explorer > Namespaces > All Namespaces` of local cluster, and delete the `fleet-default-2` namespace, previously created in step 2 of scenario 2
2. Verified - Cluster created in step 3 of scenario 2 is indirectly deleted as a result of deleting its corresponding fleet workspace, `fleet-default-2`; as expected

---

Scenario 4 -
1. Fresh install of rancher `v2.7-head`
2. Provision a downstream RKE1 AWS Node driver cluster
3. Provision a downstream RKE2 AWS Node driver cluster
4. Delete downstream RKE1 + RKE2 clusters created in steps 2 + 3 above
5. Verified - Regular deletion of RKE1 + RKE2 clusters continues to work; as expected
