### ISSUE TITLE
Shell window has unnecessary scrollbar on bottom

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4018]
Version - master 3/17

Steps to Reproduce: 
1.  Create a service
2.  Go to container and click on Shell from it's menu

Results: The shell window has a scrollbar on the bottom that is unnecessary.
![image](https://cloud.githubusercontent.com/assets/11514927/13863758/70f9f31a-ec59-11e5-89f9-18799906f1d0.png)

Expected: Remove unnecessary scrollbar

**Comment by vincent99** [comment]
This seems to be from the term.js changes, and the length varies as you type into the terminal.

**Comment by tfiduccia** [comment]
Version - master 3/18
Verified fixed
