### ISSUE TITLE
[Enhancement] add STARTUP probe customization to the Rancher chart

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#40191]
Adds values to the chart for rancher server enable startupProbe and configure its periodSeconds and failureThreshold fields. This is not enabled by default because we enable `initialDelaySeconds` for the readiness probe and these two features somewhat overlap.

**Comment by cbron** [comment]
Let's re-use this instead (and it's backport): https://github.com/rancher/rancher/issues/39841
