### ISSUE TITLE
Machine description not being shown anywhere

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#402]
v0.13.1
1.  Create a DO machine with a description

Results:
After it's done, the description and Region are not displayed anywhere

Expected:
When I click on the Machine/Host name and go to that machine's page, it should have all the information displayed somewhere on that page.

**Comment by vincent99** [comment]
Description ends up going on the `machine` object and isn't copied onto the `host`, so there's not going to be a good way to see it..

**Comment by tfiduccia** [comment]
Version - master 7/15
Description has been removed
