### ISSUE TITLE
After upgrade to rancher 2.5.6 HA mode resource unavailable

### ISSUE THREAD

**Issue by nickvth** [rancher/rancher#40208]
### see also SURE-2984

- After upgrade to rancher 2.5.6 HA mode I get resource unavailable for grafana, prometheus ui etc. 

- I am cluster-admin 
- When creating the url in the browser it work (example): https://[fqdn]/k8s/clusters/[cluster-id]/api/v1/namespaces/cattle-monitoring-system/services/http:rancher-monitoring-grafana:80/proxy/?orgId=1  

No errors in rancher log..

**Comment by MKlimuszka** [comment]
SURE-2984. This will need reproduction in 2023-Q1-2.6x and  2023-Q1-2.7x

**Comment by nflynt** [comment]
I was able to reproduce the issue with port forwarding on Private GKE clusters, and confirm the workaround. The URLs _do_ show up as active and are not greyed out. Without working proxy traffic they spin and eventually produce a 503 gateway timeout:

```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "error trying to reach service: dial tcp 10.112.1.6:9093: i/o timeout",
  "reason": "ServiceUnavailable",
  "code": 503
}
```

To fix, these ports must be opened from the Control Plane to the Target Node instances:
9093 - AlertManager
8080 - Grafana
8081 - Prometheus

(Thanks bluemalkin for the initial find.)

Additionally, new to Rancher v2.7.2, the following port must be opened on new clusters, without which chart installation will fail:
9443 - Rancher Webhook

With the above in place, all monitoring URLs appear to be in good working order, so I'd agree that this is primarily a documentation failure. The GKE instructions are provided in great detail here: 
https://cloud.google.com/kubernetes-engine/docs/how-to/private-clusters#add_firewall_rules

Our Rancher documentation for GKE Private clusters currently makes no mention of these ingress rules:
https://ranchermanager.docs.rancher.com/reference-guides/cluster-configuration/rancher-server-configuration/gke-cluster-configuration/gke-private-clusters

There is a separate tracking issue for Rancher Webhook: https://github.com/rancher/rancher/issues/41142 with more details and workarounds for anyone affected.

**Comment by MKlimuszka** [comment]
Resolving as the original report is resolved.
