### ISSUE TITLE
Release and update `system-agent` in Rancher

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#40215]
The `system-agent` in Rancher `release/v2.7` branch is on version 0.2.13 (updated per https://github.com/rancher/rancher/pull/39262). While it's currently the latest version released, there are several updates merged past the 0.2.13 release, see https://github.com/rancher/system-agent/commits/main.

Thus, we want to release a new version of system-agent (probably 0.3.0, but 0.2.14 is acceptable as well) and update Rancher to reference it instead.

None of the recent changes should change behavior (however they add support for arm64 version of `-suc` image for https://github.com/rancher/rancher/issues/34658), but given the bump to go/dapper/wharfie versions there is a (low) chance of possible regressions. Testing RKE2 provisioning is recommended after bumping the `system-agent`.

**Comment by sbstp** [comment]
There was an error in the pipeline for the tag `v0.3.0`
```
Error response from daemon: manifest for rancher/drone-images:docker-arm64 not found: manifest unknown: manifest unknown
```
Investigating this.

**Comment by Josh-Diamond** [comment]
Ticket #40215 - Test Results [pt. 2] - :x: RE-OPENED
---

With Docker on a single-node instance:

Verified on rancher `v2.7-0504ce63c1cad67b2c2be14a0325533b60902832-head`:

| Scenario | Test Case | Result|
|---|---|---|
| 1. | Provision a downstream RKE2 Node driver cluster w/ arm64 infrastructure | ❌  |
| 2. | Provision a downstream K3s Node driver cluster w/ arm64 infrastructure | ✅ |

---

Scenario 1 - 
1. Fresh install of rancher `v2.7-head`
2. As admin, create a standard user
3. As standard user, provision a downstream RKE2 Node driver cluster / arm64 infrastructure; `k8s v1.25.6+rke2r1`
    - AMI: [`ami-0a9790c5a531163ee`/`ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-arm64-server-20220912`]
    - Instance Type: [`a1.xlarge`]
4. Veri-FAILED: Cluster stuck in `Updating` state with an error on the node (this is a single-node cluster)

Logs on node:
```logs
Feb 08 23:09:23 jkeslar-test-6-pool1-<REDACTED>-<REDACTED> rancher-system-agent[1481]: time="2023-02-08T23:09:23Z" level=error msg="error loading CA cert for probe (kube-scheduler) /var/lib/rancher/rke2/server/tls/kube-scheduler/kube-scheduler.crt: open /var/lib/rancher/rke2/server/tls/kube-scheduler/kube-scheduler.crt: no such file or directory"
Feb 08 23:09:23 jkeslar-test-6-pool1-<REDACTED>-<REDACTED> rancher-system-agent[1481]: time="2023-02-08T23:09:23Z" level=error msg="error while appending ca cert to pool for probe kube-scheduler"
Feb 08 23:09:23 jkeslar-test-6-pool1-<REDACTED>-<REDACTED> rancher-system-agent[1481]: time="2023-02-08T23:09:23Z" level=error msg="error encountered during parsing of last run time: parsing time \"\" as \"Mon Jan _2 15:04:05 MST 2006\": cannot parse \"\" as \"Mon\""
Feb 08 23:09:23 jkeslar-test-6-pool1-<REDACTED>-<REDACTED> rancher-system-agent[1481]: time="2023-02-08T23:09:23Z" level=error msg="error loading x509 client cert/key for probe kube-apiserver (/var/lib/rancher/rke2/server/tls/client-kube-apiserver.crt//var/lib/rancher/rke2/server/tls/client-kube-apiserver.key): open /var/lib/rancher/rke2/server/tls/client-kube-apiserver.crt: no such file or directory"
```

Screenshot:
![image (9)](https://user-images.githubusercontent.com/46494969/217674683-3c38f166-a187-48d7-982c-940a2a99a9cd.png)

---

Scenario 2 - 
1. Fresh install of rancher `v2.7-head`
2. As admin, create a standard user
3. As standard user, provision a downstream K3s Node driver cluster / arm64 infrastructure; `k8s 1.24.10+k3s1`
    - AMI: [`ami-0a9790c5a531163ee`/`ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-arm64-server-20220912`]
    - Instance Type: [`a1.xlarge`]
4. Once `active`, navigate to `Cluster Explorer > Pods > All Namespaces` and observe all pods active and running
5. Verified - cluster successfully provisions, all pods active and running, `system-agent:v0.3.2-rc1`

**Comment by sbstp** [comment]
> RKE2 Node driver cluster / arm64 infrastructure

I don't think RKE2 is supposed to support arm64 at the moment, only K3S.

**Comment by Josh-Diamond** [comment]
@sbstp thank you for bringing this to my attention.  yes, RKE2 is not currently supported for arm64, so this use case was invalid and will be removed.

**Comment by Josh-Diamond** [comment]
Ticket #40215 - Test Results [continued] - ✅ 
---

With Docker on a single-node instance:

Verified on rancher `v2.7-0504ce63c1cad67b2c2be14a0325533b60902832-head`:

| Scenario | Test Case | Result|
|---|---|---|
| 1. | Provision a downstream K3s Node driver cluster w/ arm64 infrastructure | ✅ |
| 2. | Provision a downstream RKE2 Node driver cluster w/ amd64 - [`regression check`] | ✅  |
| 3. | Provision a downstream K3s Node driver cluster w/ amd64 - [`regression check`] | ✅ |

---

Scenario 1 - ✅ 
1. Fresh install of rancher `v2.7-head`
2. As admin, create a standard user
3. As standard user, provision a downstream K3s Node driver cluster / arm64 infrastructure; `k8s 1.24.10+k3s1`
    - AMI: [`ami-0a9790c5a531163ee`/`ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-arm64-server-20220912`]
    - Instance Type: [`a1.xlarge`]
4. Once `active`, navigate to `Cluster Explorer > Pods > All Namespaces` and observe all pods active and running
5. Verified - cluster successfully provisions, all pods active and running, `system-agent:v0.3.2-rc1`

---

Scenario 2 - ✅ 
1. Fresh install of rancher `v2.7-head`
2. As admin, create a standard user
3. As standard user, provision a downstream RKE2 Node driver cluster w/ amd infrastructure; `k8s v1.24.10+rke2r1`
4. Once `active`, navigate to `Cluster Explorer > Pods > All Namespaces` and observe all pods active and running
5. Verified - cluster successfully provisions, all pods active and running, `system-agent:v0.3.2-rc1`

---

Scenario 3 - ✅ 
1. Fresh install of rancher `v2.7-head`
2. As admin, create a standard user
3. As standard user, provision a downstream K3s Node driver cluster w/ amd infrastructure; `k8s v1.24.10+k3s1`
4. Once `active`, navigate to `Cluster Explorer > Pods > All Namespaces` and observe all pods active and running
5. Verified - cluster successfully provisions, all pods active and running, `system-agent:v0.3.2-rc1`

**Comment by Josh-Diamond** [comment]
jumped the gun moving to `QA Working`; moving to `QA Next Up` until PR to unRC `system-agent` is linked.

Attempting to locate this now..

**Comment by sbstp** [comment]
PR to unRC is here: https://github.com/rancher/rancher/pull/40477

**Comment by Josh-Diamond** [comment]
Ticket #40215 - Test Results [final] - ✅ 
---

With Docker on a single-node instance:

Verified on rancher `v2.7-828fe615a30ed0302d39df1a78366ce4f4a8b381-head`:

| Scenario | Test Case | Result|
|---|---|---|
| 1. | Provision a downstream K3s Node driver cluster w/ arm64 infrastructure | ✅ |
| 2. | Provision a downstream RKE2 Node driver cluster w/ amd64 - [`regression check`] | ✅  |
| 3. | Provision a downstream K3s Node driver cluster w/ amd64 - [`regression check`] | ✅ |

---

Scenario 1 - ✅ 
1. Fresh install of rancher `v2.7-head`
2. As admin, create a standard user
3. As standard user, provision a downstream K3s Node driver cluster / arm64 infrastructure; `k8s 1.24.10+k3s1`
    - AMI: [`ami-0a9790c5a531163ee`/`ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-arm64-server-20220912`]
    - Instance Type: [`a1.xlarge`]
4. Once `active`, navigate to `Cluster Explorer > Pods > All Namespaces` and observe all pods active and running
5. Verified - cluster successfully provisions, all pods active and running, `system-agent:v0.3.2`

Screenshot:
![image (10)](https://user-images.githubusercontent.com/46494969/218217199-52004988-95c2-4ddd-a6f4-9907f15f85c6.png)

---

Scenario 2 - ✅ 
1. Fresh install of rancher `v2.7-head`
2. As admin, create a standard user
3. As standard user, provision a downstream RKE2 Node driver cluster w/ amd infrastructure; `k8s v1.24.10+rke2r1`
4. Once `active`, navigate to `Cluster Explorer > Pods > All Namespaces` and observe all pods active and running
5. Verified - cluster successfully provisions, all pods active and running, `system-agent:v0.3.2`

Screenshot:
![image (11)](https://user-images.githubusercontent.com/46494969/218218998-8afdbc54-12f8-458a-97eb-899ab4ac9361.png)

---

Scenario 3 - ✅ 
1. Fresh install of rancher `v2.7-head`
2. As admin, create a standard user
3. As standard user, provision a downstream K3s Node driver cluster w/ amd infrastructure; `k8s v1.24.10+k3s1`
4. Once `active`, navigate to `Cluster Explorer > Pods > All Namespaces` and observe all pods active and running
5. Verified - cluster successfully provisions, all pods active and running, `system-agent:v0.3.2`

Screenshot:
![image (12)](https://user-images.githubusercontent.com/46494969/218220703-d6400fcc-0db0-46c7-8177-f84de514795c.png)
