### ISSUE TITLE
Copy to clipboard highlight and tool tip text is broken

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4021]
Version - master 3/17

Steps to Reproduce: 
1.  Go to API menu
2.  Click on Add Account (or Environment) API Key
3.  Enter a name and click on Create
4.  Click on the Secret Key (password) copy to clipboard icon

Results: Notice the Access key icon is highlighted.  If I keep clicking them back and forth, eventually they also both say Copied! in the tool tip as well.

Expected: Highlight needs to be fixed and they should never both say Copied! at same time.

**Comment by tfiduccia** [comment]
Version - master 3/22
Not fixed.  Same thing is happening.
Clicking on Secret key copy to clipboard icon highlights the Access key icon.  Clicking on them will get them to a state where they are both "Copied!"  Both cannot be on the clipboard at same time.

**Comment by vincent99** [comment]
The text updates now to Copied, which it didn't before.  But sometimes it doesn't go back to 'copy to clipboard', and the background doesn't resize when it changes, and what @tfiduccia said.

**Comment by westlywright** [comment]
I think most of the issues are addressed in rancher/ui#587 except the focus issue that occurs in the Create Environment modal. I have not been able to track down the cause for that yet. Can we open up a different issue for that and close this one since it seems the root issue here is the text inside the tooltip not changing back?

**Comment by westlywright** [comment]
@tfiduccia can we move the last issue i mentioned in my previous comment into a separate bug.

**Comment by tfiduccia** [comment]
Version - master 6/13
Closing
