### ISSUE TITLE
Reuse network from one service in another (--net=container)

### ISSUE THREAD

**Issue by v01t** [rancher/rancher#4022]
Hello,

there no way so far to use one service as network provider (openvpn client) for other service(s) that reuse this connection as network (only).

I know for this case we should use sidekicks and then everything works but what about the case when 10 different services (applications) need to reuse same connection (openvpn client), i.e. we don't want to keep all 10 applications in one service (as sidekicks) just because they reuse same connection, because then they became "sidekicks" of network service and not as standalone service(s).

Usecase:
- Network service - openvpn client used as network provider for other services in same stack.
- Application services - many applications that needs to reuse same network service (restricted to access only network that provided by network service)

lets say that we have 10 applications that needs to have such connectivity in same stack, then by current sidekicks approach we will have one stack, then inside of it we will have 1 service and inside of service 10 (!) sidekicks, and now lets imagine that we need to change (add) new "sidekick" to this implementation (add to running one), unfortunately there no such possibility so far, so we will need to clone existing "service" (that contain network and 10 sidekicks) just to extend the list of services that use openvpn client network connectivity this will mean recreation of whole "stack" (because everything became "aggregated" in one service that provide network), and yes no sidekicks for "services" in that case...

Approach when each application service use his own openvpn client "network", i.e. dedicated network service for each application also not perfect solution because then we will need to extends number of openvpn connections every time when we add new application service, for use case from above this will mean 10 connections (10 openvpn clients running as services (+ sidekicks with applications)), that also looks as overachievement because its enough to have just one connection (max 2, balanced) for all of them, also number of concurrent connections can be limited on openvpn server side.

As conclusion it will be good to be able to select bridge network (--net=container) from another service without sidekick approach.

Thanks for your great work!

Rancher Version: v.1.0
Docker Version: 1.11
OS : Debian 8

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
