### ISSUE TITLE
[BUG][RKE2] `node auto-replace` does not work on RKE2/k3s etcd nodes

### ISSUE THREAD

**Issue by thaneunsoo** [rancher/rancher#40232]
**Rancher Server Setup**
- Rancher version: v2.7-head 6ee3949
- Installation option (Docker install/Helm Chart): Helm

**Information about the Cluster**
- Kubernetes version: v1.25.5+rke2r2
- Cluster Type (Local/Downstream): rke2 and k3s

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Admin

**Describe the bug**
When shutting the etcd node outside of Rancher, the etcd node gets deleted, but gets stuck at that process. A new node is not provisioned and the node auto-replace process gets stuck.
<img width="1442" alt="image" src="https://user-images.githubusercontent.com/108360907/213746768-7712bba4-7973-4a16-8d84-75d82f4e110d.png">

**To Reproduce**

1. Create rke2 cluster
2. Set Auto-replace to `30s`
3. Wait for cluster to become active
4. Shut down etcd node outside of Rancher (in this case I shut down the node through aws portal)
5. Wait for Cluster to go into node auto-replace process

**Result**
Etcd node is not able to auto-replace. The process gets stuck at node deletion. The control plane nodes and worker nodes are being replaced successfully while the etcd node is not. The machine health check seems to be failing

**Expected Result**

Node should be removed after deletion and new node should be created to replace the "failed" etcd node.

**Comment by jakefhyde** [comment]
Moving back to working, as this issue is reproducible on v2.6-head with v1.24.8+rke2r1/v1.24.8+k3s1 and v2.7-head with v1.25.5+rke2r2/v1.25.5+k3s2.

**Comment by jakefhyde** [comment]
Blocked by https://github.com/rancher/rke2/issues/3842 & https://github.com/k3s-io/k3s/issues/6816 (rancher issue here: https://github.com/rancher/rancher/issues/40301)

**Comment by snasovich** [comment]
This can be retested after the linked issues are fixed, hopefully by https://github.com/k3s-io/k3s/pull/6922 in February 2023 RKE2/k3s k8s patches release.

**Comment by Sahota1225** [comment]
https://github.com/k3s-io/k3s/pull/6922 is ready to test, however not moving this issue to test until KDM PRs from RKE2 team are merged in 
cc: @sowmyav27 @thaneunsoo

**Comment by snasovich** [comment]
This is waiting for Feb 2023 versions to be available per https://github.com/rancher/kontainer-driver-metadata/pull/1099
