### ISSUE TITLE
rancher -agent registration  for help

### ISSUE THREAD

**Issue by sunhawk2100** [rancher/rancher#4023]
Rancher Version:0.59.1

Docker Version:1.10.2

OS: centos 7.2

Steps to Reproduce: 

Results: 

Expected:

we  add the same host running the Rancher server as a host in Rancher, host has a private or local IP address like 192.168.1.* [But IP is not fixed]and host ip 172.17.0.2,from quick-start-guide docs ,we know 
sudo docker run -e CATTLE_AGENT_IP=172.17.0.2 -d --privileged -v /var/run/docker.sock:/var/run/docker.sock rancher/agent:v0.9.2 http://172.17.0.2:8080/v1/scripts/DB121CFBA836F9493653:1434085200000:2ZOwUMd6fIzz44efikGhBP1veo.
but  we faild.
Our purpose is not to achieve LAN IP (192.168.1.*) rancher -agent registration, because HOST IP is not fixed.What should we do？

**Comment by deniseschannon** [comment]
Can you provide your logs from your rancher/agent?

**Comment by deniseschannon** [comment]
Before re-registering with your `-e CATTLE_AGENT_IP`, please do the following commands. 

```
# rm -rf /var/lib/rancher/state
# docker rm -fv rancher-agent
# docker rm -fv rancher-agent-staterancher-agent-state
```

**Comment by deniseschannon** [comment]
@sunhawk2100 If you are still having issues after my recommended steps, please re-open.
