### ISSUE TITLE
[BUG] Hardened cluster should not have CIS "Fails"

### ISSUE THREAD

**Issue by doflamingo721** [rancher/rancher#40230]
Security concerns regarding CIS check

**Business impact**: CIS 1.6 scan is not 100% clean, security concerns for the customer 

**Repro steps:**

Setup a hardened cluster 2.5.7 cluster

Start a few custom pod on some namespaces
Run a CIS 1.6 scan

**Actual behavior:**

With custom workload , point 5.1.5 is not automatically solved
Some Warnings could be solved automatically

**Expected behavior:**

Some Manual warnings can be solved automatically:
1.1.9
1.1.10

SURE: 2917

**Comment by vivek-infracloud** [comment]
![Screenshot from 2023-01-27 12-59-29](https://user-images.githubusercontent.com/83208989/215031904-25246d3d-23d5-40e2-8b97-c7510c96be86.png)

![Screenshot from 2023-01-27 12-59-46](https://user-images.githubusercontent.com/83208989/215031895-109fa0e1-4e39-4922-9eee-51d1071c072a.png)

`1.1.9`, `1.1.10`, and `5.1.5` tests are passing automatically with the CIS Benchmark chart `v3.0.1-rc6`. 
The test `5.3.2` is failing for which the [issue is already](https://github.com/rancherlabs/rancher-security/issues/952) logged, hence closing this issue.
