### ISSUE TITLE
Add CIS hardening guide for rancher provisioned RKE2/K3S clusters on k8s 1.25

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#40237]
We need to update the hardening guide for the v2.7x line to harden k8s RKE2/K3S  v1.25 clusters.

For provisioned clusters, users can use the PSACT to configure the Pod Security Admission. RKE2's default `cis-1.23` profile does not work in Rancher. See [the comment](https://github.com/rancher/rancher/issues/39148#issuecomment-1398956656). 

For imported clusters, users need to prepare the cluster in such a way that all Rancher's namespaces are in the exception list beforehand. 

Epic: https://github.com/rancher/rancher/issues/38701

**Comment by jiaqiluo** [comment]
The linked PR is merged.
QA may need to reach out to the doc team for how to access the staging docs for v2.7.2

**Comment by sowmyav27** [comment]
**QA Validations**
- Ensure the Steps listed in rancher docs are sufficient to deploy a CIS hardened RKE2/k3s custom cluster from Rancher using latest k8s - 1.25. Ensure the hardeneed CIS scans on the clusters `PASS`

**Comment by macedogm** [comment]
Second PR with updates to hardening guides https://github.com/rancher/rancher-docs/pull/478.

**Comment by Josh-Diamond** [comment]
adding myself as assignee to ^^

**Comment by Josh-Diamond** [comment]
Putting validations on hold until PR above ^^ is merged.

Will resume validations then

**Comment by Josh-Diamond** [comment]
Validated on Rancher `v2.7-cf555aa50720b9764a5fc7504eb324c60b72963c-head`, following hardening guide from local build of rancher-docs branch `release/v2.7.2`

Hardening guides are accurate and sufficient to deploy a CIS hardened RKE2/k3s k8s 1.25 custom cluster.

Note:
With RKE2, the following CIS Benchmark failures were encountered, however, they are expected and have been noted in the documentation

<img width="873" alt="Screenshot 2023-03-09 at 3 04 50 PM (1)" src="https://user-images.githubusercontent.com/46494969/224785484-e0b7a3cd-864e-49d8-baeb-a89b9e1893f4.png">

<img width="869" alt="Screenshot 2023-03-09 at 3 05 33 PM (1)" src="https://user-images.githubusercontent.com/46494969/224785515-ed2b9dad-1a40-4168-a735-bf69587cef87.png">
