### ISSUE TITLE
RKE2 Provisioning on custom Nodes: Cluster Options

### ISSUE THREAD

**Issue by matefarkas-eft** [rancher/rancher#40249]
When deploying RKE2 from Rancher on custom nodes, the "server" parameter in the RKE2 config (/etc/rancher/rke2/config.yaml.d/50-rancher.yaml) will be set automatically by Rancher to the first Master Nodes' physical address.
Once additional rke2-servers/master nodes are registered, the worker agents will discover the additional servers (assuming via the already existing connection to the first master), and start loadbalancing the control connections to all the server/master nodes.

However, the recommendation for building a HA control plane for RKE2, is to deploy a LB (like kube-vip) in front of the server nodes. 

Is there a parameter available in the Cluster provisioning schema to configure the IP of the server the agent to use to communicate, or it's not needed since the agents will cache all the master nodes IPs upon the first connection, so we do not even need the first master to be up while the worker agents are restarting (the rke server processing also connect to each other in a mesh)?
Should the latter be fine for downstream clusters, and given that the "control plane mesh" for rke2 agents work the same for both the "mgmt cluster" and the downstream clusters, can we also use this less complex approach for the mgt cluster too?

**Comment by brandond** [comment]
The documentation simply recommends a "fixed registration address". This doesn't have to be a load-balancer; it could just be a DNS alias, and in most cases that's what I recommend. 

The idea behind this is to make node registration not reliant on a specific server being online. Nodes do cache control-plane node addresses once they join the cluster, which should make warm starts of nodes functional when using an individual server address HA, as long as one of the other nodes in the cluster is available. 

Where this breaks down is cases where servers are upgraded by replacement, in which case none of the original servers are still around, and the fixed registration address points at the current set of servers.

When using Rancher provisioning, it does not set up an external load-balancer, but it does manage the configuration to ensure that the server address points at the address of a control-plane node, which should be sufficient to handle the case described above.

**Comment by matefarkas-eft** [comment]
@brandond 
Appreciate your input, and the explanation. I was not aware initially that the control node addresses are cached, so it was obvious to use a VIP, and it seems I have ignored the fact that a Rancher managed cluster can involve the management of the control plane join address. The LB makes no sense then, so we can just go with the built-in HA which is always preferred. Thx :)
