### ISSUE TITLE
Rancher Agent ping error on Worker Nodes 

### ISSUE THREAD

**Issue by Sandeepgapp** [rancher/rancher#40240]
Hello All,

We are using rancher 2.5.9 rancher server. Due to some work we removed the 2 worker nodes for around 2 months back. We followed the process to remove the node from Rancher. We are using redhat 8.6 with latest docker version.

When we tried to re-add the two worker nodes back into the Rancher cluster it is giving us the below error log rancher-agent docker container logs on the worker node.

Error: https://hostname.domainname.com/ping is not accessible (The requested url returned error : 503)

After that we tried with a fresh node with same configuration it added successfully.
Also we removed one ubuntu worker node and it was also added successfully.

But we don’t understand why the problem of adding those two worker nodes back into the Rancher cluster.

If anybody have an idea what is the wrong kindly help us.

**Comment by niusmallnan** [comment]
Maybe you need to check the support matrix first. https://www.suse.com/suse-rancher/support-matrix/all-supported-versions/rancher-v2-5-9/

If you add a node that has been used, you need to clean up the data and reboot it.
https://github.com/rancherlabs/support-tools/tree/master/extended-rancher-2-cleanup

**Comment by Sandeepgapp** [comment]
Hello Niusmallnan,
Thanks for the reply, below are the updates:
We have cleaned up the nodes and also rebooted which we have mentioned already in the post. As far as support matrix of supported versions we are complaint from that also.
