### ISSUE TITLE
Project Monitoring with standard user and project owner does not allow users to monitor workloads in assigned project correctly. 

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#40251]
Rancher Cluster:
Rancher version: 2.6.6
Number of nodes: 3
Node OS version: Ubuntu 18.04

Downstream Cluster:
Number of Downstream clusters: 1
Node OS: Ubuntu 18.04
RKE/RKE2/K3S version: RKE
Kubernetes version: 1.19
CNI: calico

Longhorn: NA
Longhorn version: NA
CPU per node: NA
Memory per node: NA
Disk type: NA
Network bandwidth between the nodes: NA

Other:
Underlying Infrastructure: VMWare

Issue description:
Standard User with Project Owner permissions are not able to monitor workloads in the project that they are assigned to.

Business impact:
This does not allow users part of project owner to monitor workloads that they are part of.

Troubleshooting steps:
When changing user permission from Standart User to Cluster Admin, the user is able to monitor the project but this is not the requirement. As a standard user with Project Owner role, users are not able to monitor the workloads.

Repro steps:

    Logged in to Rancher UI with Cluster Admin privileges.
    New user created with Standard User Global Permission.
    Created a new project and a namespace within that project.
    Added the new user to the project as Project Owner
    Created a Project Monitor for the newly created project.
    Logged out from Rancher and logged in as the new user which has project owner privileges.
    Selected the cluster and moved over to Project Monitors.
    Clicked the newly created Project Monitor and then I see the following error message instantly or within 5 sec. Attached as screenshot to this message.
    Also, when I click on the Grafana Hyperlink button, it opens up a new tab and the if I wait for 5 seconds or instantly I see the same error messag

Workaround:
Is workararound available and implemented?: no

Actual behavior:
User with Standard User permissions and Project Owner roles does not allow a user part of the project to monitor the workloads.

Expected behavior:
Standard users with Project Owner role part of the project should be able to monitor the workloads without any errors.

Files, logs, traces:
Federator logs attached to the case.

Additional notes:
Could not find any error messages in the Federator logs.
SURE-5637

**Comment by MKlimuszka** [comment]
This needs to be reproduced in 2023-Q1-2.6x, 2023-Q1-2.7x, and if it cannot be reproduced in those, 2.6.6

**Comment by stormqueen1990** [comment]
### Investigation outcome

#### Rancher v2.7-head
**Cluster type**: RKE
**Monitoring version**: 102.0.0+up40.1.2
**Prometheus Federator version**: 2.0.0+up0.2.0
**Kubernetes version**: v1.24.10

The issue is fully reproducible with the replication steps outlined in the description. The issue is related to a missing RBAC permission for the `services/proxy` resource for the user in question. It seems to be related to rancher/rancher#40253.

**Comment by stormqueen1990** [comment]
### Investigation outcome

#### Rancher v2.6.10

**Cluster type**: RKE
**Monitoring version**: 102.0.0+up40.1.2
**Prometheus Federator version**: 0.1.1
**Kubernetes version**: v1.24.10

The issue is fully reproducible with the replication steps outline in the description.

**Comment by stormqueen1990** [comment]
I was also able to confirm that adding the verb `create` to the `services/proxy` in [dashboard roles](https://github.com/rancher/prometheus-federator/blob/8e5092d7370fb30396a64fcb7c42c57928635453/packages/rancher-project-monitoring/generated-changes/overlay/templates/dashboard-roles.yaml) makes the error go away in the UI and the browser JS console. I wasn't able to verify whether the dashboard works correctly in this scenario due to a misconfiguration on my cluster's Grafana.

**Comment by breitenj** [comment]
I can confirm that granting `create` to the `services/proxy` resource also makes the grafana dashboards work. I just tested it with Rancher `v2.7.2` (Downstream Cluster RKE2 `v1.25.7+rke2r1`).

**Comment by MKlimuszka** [comment]
This was a legitimate issue, it was fixed, but may not have been tested. We will retest in 2.8.3.

**Comment by pankajsqe** [comment]
Verified this issue and Standard user who is project owner is able to monitor project workload using project monitor.

Rancher : v2.8.3.-rc5
Cluster : v1.28.7+rke2r1
prometheus-federator:103.0.1+up0.4.0
rancher-monitoring:103.0.4+up45.31.1

Admin user : admin
Standard User : sutest

- Logged in to Rancher UI with Cluster Admin privileges.
- New user created with Standard User Global Permission. : "sutest"
- Created a new project and a namespace within that project. : project =Standarduserproject , Namespace= standarduserna
- Added the new user to the project as Project Owner.
- Installed Monitoring chart and prometheus fed chart into system.
- Created a Project Monitor for the newly created project.
- Logged out from Rancher and logged in as the new user "sutest" which has project owner privileges.
- Selected the cluster and moved over to Project Monitors.
- Clicked the newly created Project Monitor and user can see project metrics and alerts PFA
- Also, when I click on the Grafana Hyperlink button, There also user can see metrics. PFA
