### ISSUE TITLE
"Let's Encrypt" catalog service spinning very rapidly

### ISSUE THREAD

**Issue by r24y** [rancher/rancher#4028]
Rancher Version: 0.63.1

Docker Version: 1.10.3

OS: Ubuntu 14.04.4 LTS on DigitalOcean

Steps to Reproduce: 
1. Create a "Let's Encrypt" service from the catalog with the following options:
 - "I Agree to the Let's Encrypt TOS": "yes"
 - "Let's Encrypt API version": "production"
 - "Email address": valid email address
 - "Domain names": enter three comma-separated domain names handled by your DigitalOcean account
 - "Public Key Algorithm": "RSA-4096"
 - "Renewal Time of Day": "5"
 - "DNS Provider": "DigitalOcean"
 - "DigitalOcean API Access Token": valid DO API token

Results: Container attempts to start and dies on a repeating interval of about 2 seconds. Log:

```
3/18/2016 8:27:04 AMlevel=info msg="Starting Let's Encrypt Certificate Manager v0.2.5 a31b992"
3/18/2016 8:27:04 AMlevel=info msg="Generating private key (4096) for me@r24y.com."
3/18/2016 8:27:07 AMlevel=info msg="Creating Let's Encrypt account for me@r24y.com"
3/18/2016 8:27:08 AMlevel=info msg="Trying to obtain SSL certificate for rancher.r24y.net | project.r24y.net | git.r24y.net"
3/18/2016 8:27:09 AMlevel=error msg="[rancher.r24y.net] Failed to obtain certificate: Error presenting token HTTP 404: not_found: The resource you were accessing could not be found."
3/18/2016 8:27:09 AMlevel=error msg="[project.r24y.net] Failed to obtain certificate: Error presenting token HTTP 404: not_found: The resource you were accessing could not be found."
3/18/2016 8:27:09 AMlevel=error msg="[git.r24y.net] Failed to obtain certificate: Error presenting token HTTP 404: not_found: The resource you were accessing could not be found."
```

Expected: Let's Encrypt service would run.

**Comment by deniseschannon** [comment]
Any templates from our [Community Catalog](https://github.com/rancher/community-catalog) is contributed and maintained by our community. Rancher will not be maintaining those templates. Please feel free to add your issue in the community and ping the owner who contributed it.
