### ISSUE TITLE
[RFE] `Manage PSACTs` global role should be implemented to ensure non-admin users can properly use PSACT during cluster provisioning

### ISSUE THREAD

**Issue by markusewalker** [rancher/rancher#40289]
**Is your feature request related to a problem? Please describe.**
As it currently stands, non-administrative users are unable to properly utilize PSACTs during cluster provisioning. In other words, non-administrative users lack the needed RBAC global role to use PSACTs. 

**Describe the solution you'd like**
As PSACT is currently defined, there isn't a viable method to have non-administrative users manage the cluster-level resource. In contrast, PSPs have the global role `Manage Pod Security Policies (PSPs)`. This global role allows an administrative user to grant, for example, a standard user to utilize PSPs in cluster creation. They cannot modify the actual resource, but they can only use it.

For PSACTs, we should have a similar `Manage PSACT` global role that will grant standard users the ability to utilize PSACTs when provisioning clusters. As with `Manage Pod Security Policies (PSPs)` global role, they will simply be able to view the role and NOT be able to modify the resource itself.

**Comment by markusewalker** [comment]
Marking this issue as closed as this global role has been implemented and the internal testing plan can proceed. There is a separate issue to fix the display (https://github.com/rancher/dashboard/issues/8015) that I am assigned to as well. But that is independent of this issue.

**Comment by cbron** [comment]
Re-opening to remove the Manage PSACT role

**Comment by sowmyav27** [comment]
We can do one quick check to confirm its not available iN Rancher UI anymore.

**Comment by markusewalker** [comment]
Validated in `v2.7-head` https://github.com/rancher/rancher/commit/62c5e321da5b576e565adf12c666489de9ea9373 that the PSACT role has been removed. See details below:

**ENVIRONMENT DETAILS**
- Rancher install: Helm
- Rancher version: `v2.7-head` https://github.com/rancher/rancher/commit/62c5e321da5b576e565adf12c666489de9ea9373
- Browser: Chrome

**TEST RESULTS**
|Scenario|Test Cases|Result|
|---|---|---|
|1|Validate that new global role `Manage Pod Security Admission Configuration Templates (PSACT)` has been removed|:white_check_mark:|

**Scenario 1**
1. As an admin user, navigate to top-left drop down menu > Users & Authentication > Roles.
2. Validated that there is no global pertaining to PSACT:
![image](https://user-images.githubusercontent.com/52591819/219439363-f74d7506-6fa5-4cfe-a0f5-f1eb091441d5.png)
