### ISSUE TITLE
Upgrading from k8s 1.23.14 to 1.23.15 fails in Rancher 2.6.9

### ISSUE THREAD

**Issue by wargamez** [rancher/rancher#40280]
In Cluster manager I tried to upgrade to kubernetes 1.23.15 from 1.23.14 but the process ends in upgrade failed and error message , see screenshots. However when it says fail I hit the  edit cluster again and to my surprise 1.23.14 is still a selectable option. If I choose that, and hit upgrade(downgrade) again,  the cluster becomes green again. However the cluster info now says 1.23.15 and all nodes show 1.23.15. Is this a known bug?

![rancherprobl2](https://user-images.githubusercontent.com/76409/214262924-345ccacb-0d4f-4a8c-8812-2f5b475e02bf.png)

![rancherprobl1](https://user-images.githubusercontent.com/76409/214262884-edac4ff5-1523-42c1-a0ed-8f3bb6191c5f.png)

![image](https://user-images.githubusercontent.com/76409/214262786-349a1fcb-1c92-4e75-9173-2f0b8984ee97.png)

![rancherprobl3](https://user-images.githubusercontent.com/76409/214263028-048eac19-7b2b-4747-bf0e-b76df6d40a7d.png)

**Comment by wargamez** [comment]
Seems worker nodes are stuck at 1.23.14 but control-plane and etc nodes are upgraded to 1.23.15...

**Comment by gestgithub** [comment]
I can confirm I do also have the same issue. Tried several times with both Rancher 2.6.9 and 2.7.0 to upgrade to 1.23.15 as well as 1.24.9.

It seems that under "Workload" --> "Jobs" in the namespace kube-system you can see that the Job rke-network-plugin-deploy-job keeps failing with messages mentioned in this issue: https://github.com/projectcalico/calico/issues/6258

**Comment by mat1010** [comment]
We can confirm the behaviour while upgrading from 1.24.4 to 1.24.9 with rancher 2.7.1

**Comment by jimliming** [comment]
confirmed editing these crd's allowed the update to complete successfully /w rke 1.4.2 & k8s 1.21.5 => 1.24.9

https://github.com/rancher/kontainer-driver-metadata/pull/1069/commits/608a5ff48b30c1728cd4ca1356cb181fc0b655ca

**Comment by niusmallnan** [comment]
I am trying to figure out this problem, considering that it may be caused by the upgrade of CNI components, so I simulate the version upgrade by adjusting KDM(https://github.com/rancher/kontainer-driver-metadata).

Rancher: v2.6.10
KDM 1: https://raw.githubusercontent.com/rancher/kontainer-driver-metadata/08-30-2022/data/data.json
KDM 2: https://releases.rancher.com/kontainer-driver-metadata/release-v2.6/data.json

| Case | From                                                | To                                                 | Result  |
|------|-----------------------------------------------------|----------------------------------------------------|---------|
| A    | KDM 1<br>RKE 1.24.4-rancher1-1<br>Calico v3.22.0   | KDM 2<br>RKE 1.24.9-rancher1-1<br>Calico v3.22.5  | Success |
| B    | KDM 1<br>RKE 1.22.13-rancher1-1<br>Calico v3.21.1  | KDM 2<br>RKE 1.22.17-rancher1-1<br>Calico v3.22.5 | Success |
| C    | KDM 2<br>RKE v1.21.14-rancher1-1<br>Calico v3.19.2 | KDM 2<br>RKE 1.22.17-rancher1-1<br>Calico v3.22.5 | Success |
| D    | KDM 2<br>RKE v1.20.15-rancher2-2<br>Calico v3.17.2 | KDM 2<br>RKE 1.22.17-rancher1-1<br>Calico v3.22.5 | Success |

I haven't found a way to reproduce it yet.

Is the CNI using the default configuration, or has it been changed since the initial installation? Maybe this is a clue?

**Comment by rootwuj** [comment]
I tried to follow these steps to test but did not reproduce the issue. Cluster can be upgraded.


Rancher:v2.6.9

KDM1: https://raw.githubusercontent.com/rancher/kontainer-driver-metadata/11-28-2022/data/data.json
KDM2: https://releases.rancher.com/kontainer-driver-metadata/release-v2.6/data.json

Steps:

1. install v2.6.9
2. update settings -> rke-metadata-config url to KDM1
3. create rke cluster, k8s version select `v1.23.14-rancher1-1`, network select Calico, the cluster active.
4. update settings -> rke-metadata-config url to KDM2
5. Upgrade the k8s version of the cluster to `v1.23.15-rancher1-1`，The cluster can be upgraded successfully.

**Comment by fengxx** [comment]
there are RKE1 clusters setup 2 years go which used v1beta1 CRD, and spec.preserveUnknownFields value is set to true (v1beta1 default to true). 
if you use recent k8s version and want to reproduce the issue, just edit CRD and set preserveUnknownFields to true before upgrading

workaround:
```
kubectl get crd ipamblocks.crd.projectcalico.org -o yaml |sed 's#preserveUnknownFields: true#preserveUnknownFields: false#' |kubectl apply -f -
kubectl get crd felixconfigurations.crd.projectcalico.org -o yaml |sed 's#preserveUnknownFields: true#preserveUnknownFields: false#' |kubectl apply -f -
```

P.S.  upstream already added  backwards-compatible fix in https://github.com/projectcalico/calico/pull/6242 but only in 3.24

**Comment by niusmallnan** [comment]
Using the v1beta1 CRD as a clue, I did this test.

I would check the setting of preserveUnknownFields. 
`kubectl get crd ipamblocks.crd.projectcalico.org -o yaml | grep preserveUnknownFields`

Rancher: v2.6.10
Upgrade path:
- RKE v1.18.18-rancher1-2, Calico v3.13.4, preserveUnknownFields=true, Success
- RKE v1.19.16-rancher2-1, Calico v3.16.5, preserveUnknownFields=true, Success
- RKE v1.20.15-rancher2-1, Calico v3.17.2, preserveUnknownFields=true, Success
- RKE v1.21.14-rancher1-1, Calico v3.19.2, preserveUnknownFields=true, Success
- **RKE v1.22.17-rancher1-1, Calico v3.22.5, preserveUnknownFields=true, Fail**

When the upgrade fails, I can see that the `rke-network-plugin-deploy-job` fails to run. It shows some error logs:
```
for: "/etc/config/rke-network-plugin.yaml": customresourcedefinitions.apiextensions.k8s.io "felixconfigurations.crd.projectcalico.org" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update
for: "/etc/config/rke-network-plugin.yaml": customresourcedefinitions.apiextensions.k8s.io "ipamblocks.crd.projectcalico.org" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update
```

I run the following command, edit the cluster on the UI, and click the save button to upgrade the cluster successfully.
```
kubectl get crd ipamblocks.crd.projectcalico.org -o yaml |sed 's#preserveUnknownFields: true#preserveUnknownFields: false#' |kubectl apply -f -
kubectl get crd felixconfigurations.crd.projectcalico.org -o yaml |sed 's#preserveUnknownFields: true#preserveUnknownFields: false#' |kubectl apply -f -
kubectl annotate crd felixconfigurations.crd.projectcalico.org kubectl.kubernetes.io/last-applied-configuration-
kubectl annotate crd ipamblocks.crd.projectcalico.org kubectl.kubernetes.io/last-applied-configuration-
```

The Calico v3.22.5 version may have some special changes. From the information provided, all RKEs that fail to upgrade use Calico v3.22.5. Never mind, there should be a solution here.

If anyone finds other errors in `rke-network-plugin-deploy-job`, please provide clues. I can update the workaround.

**Comment by fengxx** [comment]
Calico 3.22 CRD introduced new fields with default values, so have to set `preserveUnknownFields=false`, please help review the PR https://github.com/rancher/kontainer-driver-metadata/pull/1069

**Comment by pkhamre** [comment]
> I run the following command, edit the cluster on the UI, and click the save button to upgrade the cluster successfully.
> 
> ```
> kubectl get crd ipamblocks.crd.projectcalico.org -o yaml |sed 's#preserveUnknownFields: true#preserveUnknownFields: false#' |kubectl apply -f -
> kubectl get crd felixconfigurations.crd.projectcalico.org -o yaml |sed 's#preserveUnknownFields: true#preserveUnknownFields: false#' |kubectl apply -f -
> kubectl annotate crd felixconfigurations.crd.projectcalico.org kubectl.kubernetes.io/last-applied-configuration-
> kubectl annotate crd ipamblocks.crd.projectcalico.org kubectl.kubernetes.io/last-applied-configuration-
> ```

I can confirm this workaround successfully worked on our Rancher-environment, thanks.

**Comment by gregfurman** [comment]
We used the workaround provided by @niusmallnan to go from K8s v1.22.9 and Rancher v2.6.5 -> K8s v1.24.9 Rancher v2.7.1.

**Comment by wargamez** [comment]
I can confirm that this worked aswell. Thanks you so much!

**Comment by jloisel** [comment]
Same issue here, upgrading a cluster from v1.23.14 to v1.23.15 on Rancher 2.6.10.

**Comment by rayandas** [comment]
Steps to validate:

- Setup Rancher `v2.6.5` using docker
- Create a `v1.18.20-rancher1` cluster.
- Upgrade to Rancher `v2.6.10` using [these steps](https://ranchermanager.docs.rancher.com/v2.5/getting-started/installation-and-upgrade/other-installation-methods/rancher-on-a-single-node-with-docker/upgrade-docker-installed-rancher)
- Upgrade the existing `v1.18.20-rancher1` cluster to `v1.23.16-rancher1` OR `v1.24.10-rancher1`

The job `rke-network-plugin-deploy-job` shouldn't fail and calico/canal pods should be running.

cc: @rishabhmsra

**Comment by rishabhmsra** [comment]
Validated using below steps:
- On rancher v2.6.5, provisioned k8s v1.18.20-rancher1-1, ec2 node driver cluster(1-cp, 1-e, 1-w)
- Upgraded rancher server to version v2.6.10
- Upgraded existing k8s cluster to version v1.23.16-rancher1-1.
- Validated the `rke-network-plugin-deploy-job` and pods.

Result:
- Cluster upgraded successfully to v1.23.16-rancher1-1 and `rke-network-plugin-deploy-job` is in Completed state with canal pods up and running:

![canal-pods](https://user-images.githubusercontent.com/36376154/219007005-051f787f-2b05-46e1-b841-45f513406b85.png)

![completed](https://user-images.githubusercontent.com/36376154/219007013-f49508e0-0e41-40cd-92d4-273e8240bb2f.png)
