### ISSUE TITLE
"Taiga" catalog service broken

### ISSUE THREAD

**Issue by r24y** [rancher/rancher#4029]
Rancher Version: 0.63.1

Docker Version: 1.10.3

OS: Ubuntu 14.04.4 LTS on DigitalOcean

Steps to Reproduce: 
1. Create a Taiga service from the catalog.
2. Attempt to create an account.

Results: Receive message "Something happened and our Oompa Loompas are working on it."

`postgres` service gives following error log:

```

3/18/2016 8:04:35 AM
3/18/2016 8:04:35 AMWARNING: enabling "trust" authentication for local connections
3/18/2016 8:04:35 AMYou can change this by editing pg_hba.conf or using the option -A, or
3/18/2016 8:04:35 AM--auth-local and --auth-host, the next time you run initdb.
3/18/2016 8:04:35 AM****************************************************
3/18/2016 8:04:35 AMWARNING: No password has been set for the database.
3/18/2016 8:04:35 AM         This will allow anyone with access to the
3/18/2016 8:04:35 AM         Postgres port to access your database. In
3/18/2016 8:04:35 AM         Docker's default configuration, this is
3/18/2016 8:04:35 AM         effectively any other container on the same
3/18/2016 8:04:35 AM         system.
3/18/2016 8:04:35 AM
3/18/2016 8:04:35 AM         Use "-e POSTGRES_PASSWORD=password" to set
3/18/2016 8:04:35 AM         it in "docker run".
3/18/2016 8:04:35 AM****************************************************
3/18/2016 8:04:37 AMLOG:  database system was shut down at 2016-03-18 12:04:36 UTC
3/18/2016 8:04:37 AMLOG:  MultiXact member wraparound protections are now enabled
3/18/2016 8:04:37 AMLOG:  database system is ready to accept connections
3/18/2016 8:04:37 AMLOG:  autovacuum launcher started
3/18/2016 8:05:38 AMFATAL:  role "taiga" does not exist
```

Expected: Confirmation of creation of account.

**Comment by deniseschannon** [comment]
Any templates from our Community Catalog is contributed and maintained by our community. Rancher will not be maintaining those templates. Please feel free to add your issue in the community and ping the owner who contributed it.

**Comment by rjpalermo1** [comment]
Not a good reply Denise.  Horrible user experience for those of us trying to get a grasp of the Rancher environment by setting up your highly touted click to install catalog stacks and they do not work.  I picked the Taiga stack here as it was a no-brainer install on a non-docker host.

If I can make a suggestion, if this is the hands-off approach on a stellar-feature then can you at least make the docker-compose.yml files provided by the 'community' editable so we can modify them to suit our unique environments?  For example, this .yml for this stack in the 'official' Rancher catalog has 'boot2docker' as the environment API ~ perfect for Rancher managed enterprise deployments on Mac laptops but not so useful for cloud deployments...

**Comment by deniseschannon** [comment]
It's actually very easy to edit the compose files for your own needs. 

After looking at the catalog entry, you can click on "Preview", which will show the exact docker-compose.yml and rancher-compose.yml files that are associated with the catalog template.

You can copy and edit those files. Then, you can launch the edited files when you create your own stack.

Alternatively, you could take those same files and use rancher-compose to launch them into Rancher.
