### ISSUE TITLE
Rancher is inaccessible

### ISSUE THREAD

**Issue by nimisha-rci** [rancher/rancher#40298]
Hello Team

Request you to fix it as our team is facing issues in accessing Rancher for the past few weeks.

Thanks.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.5.7` UI: `v2.5.6` |
|Route|`undefined`|

**Comment by rmweir** [comment]
Hello, can you add details to this issue? What do you see when you try to access rancher? Can you provide a screenshot with any sensitive/personal info redacted?

**Comment by rmweir** [comment]
Also, I see that it says your UI is on v2.5.6 while rancher is on v2.5.7. Can you explain how you changed the UI version? It may be related.

**Comment by nimisha-rci** [comment]
.

**Comment by nimisha-rci** [comment]
.
