### ISSUE TITLE
Error when adding a volume with the "volumes from" option.

### ISSUE THREAD

**Issue by JulekFr** [rancher/rancher#4030]
Rancher Server : v0.63.1
OS : RancherOS v0.4.3

Steps to reproduce:

1. Launch a convoy-nfs stack.
2. Setup a volume in Storage pool.
3. Create a new container and try to add a volume with the "Volumes from" option.
4. You will get the following error in the GUI:
{new-select{ classNames="form-control input-sm volumefrom-container" prompt="Select a container..." value=vol.value content=hostContainerChoices optionValuePath="id" optionLabelPath="name" optionGroupPath="group" }}

**Comment by vincent99** [comment]
https://github.com/rancher/ui/commit/f45234c77e3dfc5fd79985d2514663d2e51cc599
