### ISSUE TITLE
[BUG] Impersonator account invalid secret object Race Condition post 2.6.9 from 2.6.6

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#40302]
**Rancher Server Setup**
Rancher Cluster:
Rancher version: 2.6.9 after being upgraded from 2.6.6
Number of nodes: 3
Node OS version: Ubuntu 20.04

Downstream Cluster:
Number of Downstream clusters: 3
Node OS: Ubuntu 20.04
RKE/RKE2/K3S version: RKE 1.3.15
Kubernetes version: K8s 1.23.10
CNI: Calico

**Describe the bug**
After upgrading from 2.6.6 to 2.6.9, the admin account on the downstream is missing the new impersonator token. This should be fine as: https://github.com/rancher/rancher/blob/v2.6.9/pkg/impersonation/impersonation.go#L102-L131 creates the token on demand. However, the first time the admin attempts to run a command it fails with unable to create impersonator account: error getting service account token: error getting token: invalid secret object. Subsequent commands all pass. This is because the code does create the token, but I believe the code checks for the existence to fast so it fails before it has a chance for the create to finish. 

Users without this new token after upgrading will get the invalid secret object fail even though nothing occurred.

**To Reproduce**
1) upgrade from 2.6.6 to 2.6.9, and as admin user run a command downstream such as 
kubectl create cm testing_toke_creation --from-literal=triggered="inprogress" -o yaml --dry-run=client | kubectl apply -f - 
.
OR

2)Delete the cattle-impersonation-u-$id-token-$id and cattle-impersonation-u-$id-token tokens. You will see cattle-impersonation-u-$id-token-$id comes back immediately while the other stays deleted. Then run the above command as that user downstream.

**Result**
User gets an error even though next command works as expected, and token was created during first run.

**Expected Result**
First command succeeds with token that was created

**Additional context**
What is the workaround: just run command again

SURE-5651

**Comment by oe-hbk** [comment]
We see this too, after migrating from 2.6.2 to 2.7.0.  Per user, per managed cluster.

**Comment by samjustus** [comment]
not reproducible as of 2.7.1
