### ISSUE TITLE
[BUG] Provisioning log config map is empty

### ISSUE THREAD

**Issue by thaneunsoo** [rancher/rancher#40305]
**Rancher Server Setup**
- Rancher version: v2.7-head a352c87
- Installation option (Docker install/Helm Chart): Helm

**Information about the Cluster**
- Kubernetes version: v1.24.8
- Cluster Type (Local/Downstream): local

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: admin

**Describe the bug**

When provisioning an rke2 cluster, the provisioning log was empty but the rancher logs were there. The provisioning log for configmap is empty.

**To Reproduce**

1. Provision Rancher with 1.24.8 k8s version
2. Create rke2 aws node driver cluster
3. Verify provisioning log is empty
4. Check provisioning log config map

**Result**
provisioning log config map is empty

**Expected Result**

Config map should not be empty and show data to show rancher logs

**Comment by jakefhyde** [comment]
By editing the configmap, the expected `data` fields (`last` and `log) were added via the controller reconciling the configmap. This is due to a race condition within the controller exiting reconciliation prematurely and never re-enqueueing itself. @snasovich Is this something we want to get in the upcoming 2.6 and 2.7 releases?

**Comment by thaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.7-head
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: rke2

----------

### Testing: ###
Tested this issue with the following steps:
1. Provision Rancher with 1.24.8 k8s version
2. Create rke2 aws node driver cluster
3. Check provisioning log config map

**Result**
Provisioning log config map is no longer empty and provisioning log now shows information while cluster is provisioning.

![image.png](https://zube.io/files/rancher/4034e45060a5549a5f2e30b9f390f681-image.png)

**Comment by gee456** [comment]
I am having this problem on a newly built v2.10.3 Rancher system. I have added three clusters and the provisioner log is empty. Please advise what I should do. Create a new Bug? Any diagnostics you would like me to run?

![Image](https://github.com/user-attachments/assets/42941b14-855d-4473-9b7f-d15124947b7b)
