### ISSUE TITLE
Default or configure "Add Host" to Docker 1.10.3

### ISSUE THREAD

**Issue by will-chan** [rancher/rancher#4031]
Currently, we always install Docker Engine:latest when you use Docker Machine and this may cause problems in the future if the current version of Rancher does not support the latest version of Docker.  Creating a setting to allow an admin/user to default to this would be good.

**Comment by vincent99** [comment]
By what mechanism?  https://get.docker.com/ installs latest and the only two documented options are worse (release candidate and experimental).

**Comment by wlan0** [comment]
@vincent99 The plan is to pass in our own docker install script (at let's say get.docker.rancher.com), and then point the --engine-install-url to the hosted script. By doing that, we can control the version of docker that gets installed.

**Comment by vincent99** [comment]
ok; you can use the releases CDN, something like `https://releases.rancher.com/get-docker/1.10.sh`.  There should be a setting for the default engine URL and add that setting name to the `settings.public` setting so the UI can read it.

**Comment by wlan0** [comment]
Gotcha, thanks!

**Comment by sangeethah** [comment]
Tested with rancher-server version - v1.0.0-rc1

When adding hosts , "Advanced option" has "Docker Install URL"  which is defaulted to https://releases.rancher.com/install-docker/1.10.sh .
This value gets passed to docker machine create as  --engine-install-url parameter.
docker 1.10.3 gets gets installed in the hosts.

Able to set the "Docker Install URL" to a different script that points to a different version of docker. In this case , host that gets added uses the docker version pointed in the script.
