### ISSUE TITLE
[BUG][UI] no Kubernetes > 1.22 on EKS with Rancher 2.6.9

### ISSUE THREAD

**Issue by n1kk0** [rancher/rancher#40323]
On Rancher 2.6.9, the UI does not permit (hard coded) to select Kubernetes version over 1.22 on AWS EKS
=> https://github.com/rancher/ui/blob/v2.6.9/lib/shared/addon/utils/amazon.js#L686

And on Rancher 2.7.0+, the UI does not permit (hard coded too) to select Kubernetes version under 1.23 on AWS EKS
=> https://github.com/rancher/ui/blob/v2.7.0/lib/shared/addon/utils/amazon.js#L686

The upgrade path seems impossible from Rancher 2.6.9 kube 1.22 to kube 1.23

If you ask me, version 1.23 needs to be added to the 2.6 branch

**Comment by rmweir** [comment]
Currently, it looks like EKS 1.23 is being added in 2.6.11: https://github.com/rancher/ui/pull/4948.

**Comment by n1kk0** [comment]
Oh you are right ! thx.

But... I'm still wondering
1.22 and 1.23 will never exist in the same version...
Will upgrade from 1.22 to 1.23 need to be done "manually"...
or should we wait for 2.6.11 even if 1.22 will have disapeared from the select options...

**Comment by rmweir** [comment]
We are still discussing what the exact version will be but if this does end up being the case, you should still be able to go from 1.22 to 1.23. If your cluster is already on 1.22 it doesn't need to be in the dropdown as far as I know.

**Comment by n1kk0** [comment]
Great !

Thx for taking time for those precisions.
