### ISSUE TITLE
Update Webhook chart to support updated approach for PSPs

### ISSUE THREAD

**Issue by MbolotSuse** [rancher/rancher#40326]
<s>The chart for rancher/webhook will need to be updated to handle the new approach designed for PSPs. 

The chart will need to be modified include the following option:

```yaml
global:
  cattle:
     psp:
        enabled: false #PSPs enablement should default to true
```

A new file will need to be added called `validate-psp-install.yaml` in the `charts/rancher-webhook/templates` directory with the following content:

```yaml
#{{- if gt (len (lookup "rbac.authorization.k8s.io/v1" "ClusterRole" "" "")) 0 -}}
#{{- if .Values.global.cattle.psp.enabled }}
#{{- if not (.Capabilities.APIVersions.Has "policy/v1beta1/PodSecurityPolicy") }}
#{{- fail "The target cluster does not have the PodSecurityPolicy API resource. Please disable PSPs in this chart before proceeding." -}}
#{{- end }}
#{{- end }}
#{{- end -}}
```

Any files that render PSPs will need to make that rendering conditional solely on the `global.cattle.psp.enabled` value, like below:

```yaml
{{- if .Values.global.cattle.psp.enabled  -}}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
...
{{- end }}
```
This approach meets the following requirements:
- PSPs should be used by the chart by default, keeping compatibility with the current 2.7.0 approach. 
- If users attempt to request PSPs  when installing the chart in a cluster which does not support PSPs (for example, a cluster running k8s version 1.25), an error will be presented so that the user knows to change the `global.cattle.psp.enabled` value to `false` before continuing.  

A solution for this should probably start by reverting rancher/webhook#171, and then continue by applying the above approach.</s>

After further consideration of how this approach will work with webhooks which are installed in remote clusters, we've adjusted to a new approach outlined in this comment: https://github.com/rancher/rancher/issues/40326#issuecomment-1423238619. 

This approach has the following components:

- The `MutatingWebhookConfiguration` `rancher.cattle.io` will now be declared by the webhook's chart
- All references to the pre-delete job in the webhook chart (which was used solely to delete the above `MutatingWebhookConfiguration`), will be removed, including:
  - The pre-delete configuration values in `values.yaml`
  - The psp configuration values in `values.yaml` (psps were only used for the pre-delete job)
  - The  `validate-psp-install.yaml`
  - Pre-delete cluster role
  - Pre-delete cluster role binding
  - Pre-delete job
  - Pre-delete psp
  - Pre-delete service account
- Rancher will be updated to "adopt" resources which should belong to the webhook chart (according to name/namespace) but don't currently belong to the existing helm release. This is necessary since there will be an existing `MutatingWebhookConfiguration` `rancher.cattle.io` and webhook installs may fail to upgrade if this adoption does not occur.

**Comment by MbolotSuse** [comment]
Moving this back to working for a moment. While the original approach (default PSP enabled set to false) worked fine for the local cluster, now that the webhook is in the downstream clusters as well there are other factors to consider. With this in mind, we are going to re-evaluate the webhook's use of PSPs and see if there is a way to refactor the chart to not need PSPs at all. This would preserve existing functionality and allow us to avoid complex logic which deals with downstream clusters with different k8s versions and psp enablement status. 

As of now, the plan is to:
- Remove the pre-delete job which is currently being used to cleanup the MutatingAdmissionWebhook (which the webook creates post-install)
- Add the MutatingAdmissionWebhook to the chart definition so helm removes it as part of the uninstall process

Moving this back to working as I work on the solution.

**Comment by MbolotSuse** [comment]
## Validation Template

## Root Cause

The webhook previously used psps as part of the pre-delete job that ran when you uninstalled the webhook. The purpose of this job was to delete the MutatingWebhookConfiguration, which was not part of the webhook's chart, but was used by the webhook to force validation of certain entries. This caused the webhook to need psps to run the post-delete job.

## What was fixed, or what change have occurred

- The MutatingWebhookConfiguration has been added to the webhook's chart. Now the helm uninstall command will remove the value directly, rather than running a post-delete job.
- The post-delete job and it's various resources have been removed from the webhook's chart. This includes: a psp, a job, a cluster role, a cluster role binding, and a service account. This also included several variables in the values.yaml.
- The various elements which decided if psps should be used in the webhook have been removed. This includes the validate-install-psp.yaml which checked if a cluster supported psps, and the variables in the values.yaml that allowed the use of psps.
- The PR to pass down rancher's psp setting to the webhook has been reverted.
- New logic has been introduced in rancher to force helm to adopt existing resources when installing/upgrading the webhook. This is necessary so that existing MutatingWebhookConfigurations (which were not deployed/managed using helm) don't cause helm upgrade commands to fail.

## Areas or cases that should be tested

- Webhook install/uninstall on hardened/non-hardened clusters
- Webhook upgrade (specifically rancher initiated upgrade) on hardened/non-hardened clusters (Docker install and High Availability)
- Webhook install/uninstall on downstream clusters (hardened/non-hardened)

## What areas could experience regressions

Webhook install, uninstall, and upgrade.

**Comment by anupama2501** [comment]
QA to validate:
Pre-req:
Rancher versions: 2.7.0 & 2.7-head
Clusters: RKE1 non-hardened, RKE2 hardened .
Steps:
- Install  rancher on v2.7.0 and webhook 2.0.0+up0.3.0
- Verify the webhook is installed without the resource MutatingWebhookConfiguration
- Upgrade rancher server to version 2.7-head
- Webhook version should be upgraded to `[2.0.2+up0.3.2-rc17](https://github.com/rancher/charts/tree/dev-v2.7/charts/rancher-webhook/2.0.2%2Bup0.3.2-rc17)
- Verify resources now show MutatingWebhookConfiguration as well.
Test cases:


 Test case | Status
--- | --- 
Upgrade 2.7.0 >> 2.7-head hardened PSP local cluster | | 
Upgrade 2.7.0 >> 2.7-head hardened PSA local cluster | | 
Upgrade 2.7.0 >> 2.7-head non-hardened local cluster | | 
Webhook in downstream upgrades on rancher version upgrade hardened PSP cluster | | 
Webhook in downstream upgrades on rancher version upgrade non hardened cluster | | 
Webhook in downstream upgrades on rancher version upgrade hardened PSA cluster | | 
Uninstall rancher on hardened PSP cluster  | | 
Uninstall rancher on hardened PSA cluster  | | 
Uninstall rancher on non hardened cluster  | | 
Import a downstream cluster on 2.7.0 and un import the downstream hardened PSP cluster | |
Import a downstream cluster on 2.7.0 and un import the downstream hardened PSA cluster | |
Import a downstream cluster on 2.7.0 and un import the downstream non-hardened cluster | |
Rancher backup/roll back v2.7.0 >> 2.7-head >> 2.7.0 | |
Rancher backup/roll back v2.6.9 >> 2.7-head >> 2.6.9 | |
