### ISSUE TITLE
Update Rancher's chart to support updated approach for PSPs

### ISSUE THREAD

**Issue by MbolotSuse** [rancher/rancher#40327]
Rancher will need to be updated to handle the new approach designed for PSPs. 

The chart will need to be modified include the following option:

```yaml
global:
  cattle:
     psp:
        enabled: true #PSPs enablement should default to true
```

A new file will need to be added called `validate-psp-install.yaml` in the `chart/templates` directory with the following content:

```yaml
#{{- if gt (len (lookup "rbac.authorization.k8s.io/v1" "ClusterRole" "" "")) 0 -}}
#{{- if .Values.global.cattle.psp.enabled }}
#{{- if not (.Capabilities.APIVersions.Has "policy/v1beta1/PodSecurityPolicy") }}
#{{- fail "The target cluster does not have the PodSecurityPolicy API resource. Please disable PSPs in this chart before proceeding." -}}
#{{- end }}
#{{- end }}
#{{- end -}}
```

Any files that render PSPs will need to make that rendering conditional solely on the `global.cattle.psp.enabled` value, like below:

```yaml
{{- if .Values.global.cattle.psp.enabled  -}}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
...
{{- end }}
```

This approach meets the following requirements:
- PSPs should be used by the chart by default, keeping compatibility with the current 2.7.0 approach. 
- If users attempt to request PSPs  when installing the chart in a cluster which does not support PSPs (for example, a cluster running k8s version 1.25), an error will be presented so that the user knows to change the `global.cattle.psp.enabled` value to `false` before continuing.  

A solution for this should probably start by reverting rancher/rancher#40089 to re-introduce PSPs to the chart, and then continue by applying the above approach.

**Comment by jiaqiluo** [comment]
Can be validated in Rancher [v2.7.2-rc2](https://github.com/rancher/rancher/releases/tag/v2.7.2-rc2)

**Comment by anupama2501** [comment]
QA to validate:

Rancher version | k8s version | psp.enabled flag | hardened jenkins flag | Additional comments | Actual Status
-- | -- | -- | -- | -- | -- |
rancher_version=v2.7-head |  k8s=1.24 | global.cattle.psp.enabled=false | hardened=False | installation goes through |
rancher_version=v2.7-head |  k8s=1.24 |  global.cattle.psp.enabled=true | hardened=True |  installation goes through | 
rancher_version=v2.7-head | k8s=1.25 | global.cattle.psp.enabled=false | hardened=False |  installation goes through |
rancher_version=v2.7-head | k8s=1.25 | global.cattle.psp.enabled=true |  hardened=False |  installation fails |
rancher_version=v2.7.0 | k8s=1.24 | N/A | hardened=False | Upgrade rancher to v2.7-head by adding the flag global.cattle.psp.enabled=False  and installation goes through | 
rancher_version=v2.7-head | k8s 1.24 | global.cattle.psp.enabled=true | hardened=True | install rancher and upgrade k8s to 1.25 and  installation goes through |
 rancher_version=v2.7.0 | k8s=1.24 | N/A | hardened=True | upgrade rancher to v2.7-head, no global.cattle.psp.enabled flag set as by default it is set to true  and upgrade goes through |

**Comment by dasarinaidu** [comment]
I have validated all above test cases on` v2.7.2-rc6` and did not see any new issues. I am closing the ticket.
