### ISSUE TITLE
Update Rancher to pass PSP setting to the webhook

### ISSUE THREAD

**Issue by MbolotSuse** [rancher/rancher#40328]
As part of the updated approach for PSPs, Rancher will need to pass down the setting configured for its install to the webhook. This will ensure that both the webhook and rancher use PSPs only in the correct circumstance (and that they stay in sync).

In short, the setting for `global.cattle.psp.enabled` should be the same for both rancher, and the webhook. Rancher should detect what value this was set to and update the webhook when it is deployed correspondingly. 

This issue will depend on the Webhook's chart and Rancher's chart being updated to support an option to control PSPs. That work is tracked by seprate issues for rancher (#40327) and the webhook (#40326).

The approach should mimic the approach taken for priority classes, which was introduced in rancher/rancher#39071.

**Comment by jiaqiluo** [comment]
Can be validated in Rancher [v2.7.2-rc2](https://github.com/rancher/rancher/releases/tag/v2.7.2-rc2)

**Comment by MbolotSuse** [comment]
The new approach for https://github.com/rancher/rancher/issues/40326 has made this ticket no longer valid. Since the webhook no longer uses PSPs, there's no need for rancher to pass this setting down to the webhook.

**Comment by anupama2501** [comment]
Closing the issue based on the comment https://github.com/rancher/rancher/issues/40328#issuecomment-1471922392 and the PR has been reverted.
