### ISSUE TITLE
Update rancher-charts/epinio chart to support updated approach for PSPs

### ISSUE THREAD

**Issue by stormqueen1990** [rancher/rancher#40338]
### Parent issue: https://github.com/rancher/rancher/issues/40331
---
Implement the changes specified in the parent issue for the epinio chart.

- Create a new chart version (102.0.0+up1.5.1)
- Update the default from `true` to `false` for the variable `global.rbac.pspEnabled` in the [values.yaml](https://github.com/rancher/charts/blob/dev-v2.7/charts/epinio/101.0.2%2Bup1.5.1/values.yaml#L127). 
- Create a variable for the question in the [questions.yml](https://github.com/rancher/charts/blob/dev-v2.7/charts/epinio/101.0.2%2Bup1.5.1/questions.yml) to ask if they want to enable/disable PSP with a default set to `false` for the `global.rbac.pspEnabled` value in order for the user to update and change the UI of disabling/enabling PSPs. Suggestion on what to add is in the parent issue, though the value name is different. 
- Add the context in the [app-readme.md](https://github.com/rancher/charts/blob/dev-v2.7/charts/epinio/101.0.2%2Bup1.5.1/app-readme.md) file about the changes related to PSPs. Example content is in the main parent issue linked above.  Please note that all the other charts are getting the same value name, but we are not expecting that change for our SUSE projects (aka epinio)
- Add a validation psp install check in the chart so that if someone tries to enable PSPs on a cluster that doesn’t have the capability, then it would error out. Note: This is recommended for the upstream Epinio chart and not just our “patched” upstream as defaulting to true would cause immediate errors. Code on how to do this is in the parent issue.

**Comment by andreas-kupries** [comment]
@stormqueen1990 @deniseschannon A question to clarify things ...

The Epinio chart currently uses an automatic system to handle PSPs.
All the PSPs in the chart start with

> {{- if .Capabilities.APIVersions.Has "policy/v1beta1/PodSecurityPolicy" -}}
{{- if .Values.global.rbac.pspEnabled }}

The first condition automatically prevents the creation of PSPs on clusters not supporting them.
The second condition then checks the user's choice.

Is the new system intended to completely replace such automatic operation ?

**Comment by andreas-kupries** [comment]
Work is done in PR https://github.com/rancher/charts/pull/2344.

**Comment by prachidamle** [comment]
@andreas-kupries @olblak  Currently for the epinio chart, there are following 4 versions in the rancher/charts release.yaml - do you intend to release multiple chart versions in one Rancher release (2.7.2)?

if you plan to release the latest then you need to remove the previous versions using `make remove`

**Comment by andreas-kupries** [comment]
@prachidamle Thank you for this information. I was not aware of this target. Yes, we only wish to release the latest in the set.
