### ISSUE TITLE
Update feature charts to support updated approach for PSPs

### ISSUE THREAD

**Issue by stormqueen1990** [rancher/rancher#40331]
Update the feature charts currently hosted on rancher/charts to implement the new approach for dealing with PodSecurityPolicies.

Each chart will need to include the following option and consume it to determine whether PSPs are to be installed, instead of the currently existing variables. Note: This only applies to the feature charts that we package from external upstream projects. Any internal SUSE project can continue to use their own value.

```yaml
global:
  cattle:
    psp:
      enabled: false # PSP enablement should default to false
```

Create a new validation file called `validate-psp-install.yaml` for each chart, and include the following validation:
```
#{{- if gt (len (lookup "rbac.authorization.k8s.io/v1" "ClusterRole" "" "")) 0 -}}
#{{- if .Values.global.cattle.psp.enabled }}
#{{- if not (.Capabilities.APIVersions.Has "policy/v1beta1/PodSecurityPolicy") }}
#{{- fail "The target cluster does not have the PodSecurityPolicy API resource. Please disable PSPs in this chart before proceeding." -}}
#{{- end }}
#{{- end }}
#{{- end }}
```

For charts that use `questions.yml`, it should be updated to include the new variable:
```yaml
questions:
- variable: global.cattle.psp.enabled
  default: "false"
  description: "Flag to enable or disable the installation of PodSecurityPolicies by this chart in the target cluster. If the cluster is running Kubernetes 1.25+, you must update this value to false."
  label: "Enable PodSecurityPolicies"
  type: boolean
  group: "Security Settings"
```

Update the `app-readme.md` to explain changes in behaviour and expectations for the PodSecurityPolicy switch:
```md
## Upgrading to Kubernetes v1.25+

Starting in Kubernetes v1.25, [Pod Security Policies](https://kubernetes.io/docs/concepts/security/pod-security-policy/) have been removed from the Kubernetes API.

As a result, **before upgrading to Kubernetes v1.25** (or on a fresh install in a Kubernetes v1.25+ cluster), users are expected to perform an in-place upgrade of this chart with `global.cattle.psp.enabled` set to `false` if it has been previously set to `true`.
​
> **Note:**
> In this chart release, any previous field that was associated with any PSP resources have been removed in favor of a single global field: `global.cattle.psp.enabled`.

> **Note:**
> If you upgrade your cluster to Kubernetes v1.25+ before removing PSPs via a `helm upgrade` (even if you manually clean up resources), **it will leave the Helm release in a broken state within the cluster such that further Helm operations will not work (`helm uninstall`, `helm upgrade`, etc.).**
>
> If your charts get stuck in this state, please consult the Rancher docs on how to clean up your Helm release secrets.

Upon setting `global.cattle.psp.enabled` to false, the chart will remove any PSP resources deployed on its behalf from the cluster. This is the default setting for this chart.
​
As a replacement for PSPs, [Pod Security Admission](https://kubernetes.io/docs/concepts/security/pod-security-admission/) should be used. Please consult the Rancher docs for more details on how to configure your chart release namespaces to work with the new Pod Security Admission and apply Pod Security Standards.
```

In addition, each changed chart should have:
* Its version bumped to the next major, since the variable standardization is a breaking change.
* Previously added capabilities checks to PodSecurityPolicies and related resources removed, while keeping the flag check to decide whether to apply those resources.

This approach meets the following requirements:
* PSPs should be installed by charts that have it by default, keeping compatibility with the current Rancher 2.7 approach.
* If users request installation of PSPs in a target cluster that does not have the PodSecurityPolicy API resource available (Kubernetes v1.25+), a user-friendly error will be presented to ask the user to switch the flag `global.cattle.psp.enabled` off before proceeding.

The following feature charts need to be changed to address these requirements:
- [x] rancher/rancher#40338
- [x] rancher/rancher#40342
- [x] rancher/rancher#40343
- [x] rancher/rancher#40344
- [x] rancher/rancher#40345
- [x] rancher/rancher#40346
- [x] rancher/rancher#40347
- [x] rancher/rancher#40348
- [x] rancher/rancher#40349
- [x] rancher/rancher#40350
- [x] rancher/rancher#40351

**Comment by mattfarina** [comment]
@stormqueen1990 instead of using `required` you might try using the [`fail`](https://helm.sh/docs/chart_template_guide/function_list/#fail) template function.

**Comment by mattfarina** [comment]
Also, in the questions.yaml should we call out the full name PodSecurityPolicy instead of the acronym?

**Comment by stormqueen1990** [comment]
> @stormqueen1990 instead of using `required` you might try using the [`fail`](https://helm.sh/docs/chart_template_guide/function_list/#fail) template function.

Will update!

**Comment by stormqueen1990** [comment]
> Also, in the questions.yaml should we call out the full name PodSecurityPolicy instead of the acronym?

I'll update it too.

**Comment by aiyengar2** [comment]
### For QA

Some QA Test Cases to consider:
- [ ] app-readme.md should be updated and formatted nicely
- [ ] questions.yml should be updated to have the new field under `Security Settings` OR https://github.com/rancher/dashboard/issues/8053 should be tracking that fix.
- In a 1.24- cluster
  - [ ] If you do not modify any values in the chart, `global.cattle.psp.enabled` should be set to `false` and **no PSP resources should be tracked** in the Installed App
  - [ ] If you set `global.cattle.psp.enabled=true` on this new chart, PSP resources should be tracked in the Installed App
  - [ ] If you set `global.cattle.psp.enabled=false` on this new chart, **no PSP resources should be tracked** in the Installed App
  - [ ] Going from `true` to `false` should remove PSPs from the Installed App in an in-place upgrade
  - [ ] Going from `true` to `false` should deploy PSPs from the Installed App in an in-place upgrade
- In a 1.25 cluster
  - [ ] If you do not modify any values in the chart, chart should deploy successfully with no issues
  - [ ] If you set `global.cattle.psp.enabled=true` on this new chart, the human-readable error from `validate-psp-install.yaml` above should be displayed on main chart install (or CRD chart install, if the CRD chart uses a job to install CRDs like Monitoring)
- Upgrade from 1.24 -> 1.25
  - [ ] If you install the chart in 1.24 without modifications and upgrade to 1.25, no errors should be observed. No PSP resources should be tracked
  - [ ] If you install the chart in 1.24 with `global.cattle.psp.enabled=true` and upgrade to 1.25, a `helm upgrade` or `helm uninstall` should fail. 
    - Once we have the mapkubeapis fix in (cc: @stormqueen1990 can you link the issue to this ticket), we should test if that fixes it
  - [ ] If you install the chart in 1.24 with `global.cattle.psp.enabled=true`, then in-place upgrade it to `global.cattle.psp.enabled=false` (where PSP resources should be removed), and then upgrade to 1.25, you should be able to perform an in-place upgrade without any changes to the `values.yaml`.

### For Developers

Some Developer test cases to consider (after adding `validate-psp-install.yaml`):
- [ ] Ensure a `helm template <release-name> <chart-path>` never fails
- [ ] Ensure a `helm template --set global.cattle.psp.enabled=true <release-name> <chart-path>` never fails
- [ ] Ensure a `helm install --dry-run <release-name> <chart-path>` does not fail when your KUBECONFIG is pointing to a 1.24 cluster
- [ ] Ensure a `helm install --dry-run --set global.cattle.psp.enabled=true <release-name> <chart-path>` does not fail when your KUBECONFIG is pointing to a 1.24 cluster
- [ ] Ensure a `helm install --dry-run <release-name> <chart-path>` does not fail when your KUBECONFIG is pointing to a 1.25 cluster
- [ ] Ensure a `helm install --dry-run --set global.cattle.psp.enabled=true <release-name> <chart-path>` does not fail when your KUBECONFIG is pointing to a 1.25 cluster
- [ ] Ensure a `helm install <release-name> <chart-path>` does not fail when your KUBECONFIG is pointing to a 1.24 cluster
- [ ] Ensure a `helm install --set global.cattle.psp.enabled=true <release-name> <chart-path>` does not fail when your KUBECONFIG is pointing to a 1.24 cluster
- [ ] Ensure a `helm install <release-name> <chart-path>` does not fail when your KUBECONFIG is pointing to a 1.25 cluster
- [ ] Ensure a `helm install --set global.cattle.psp.enabled=true <release-name> <chart-path>` **does fail** when your KUBECONFIG is pointing to a 1.25 cluster, with the error from `validate-psp-install.yaml` showing up

**NOTE: depending on your chart, you may need to add other `--set` fields for the default rendering to work. For example, `rancher-alerting-drivers` requires `sachet.enabled=true` or `prom2teams.enabled=true` to be set, so just preprend that to all helm calls above

**Comment by stormqueen1990** [comment]
Developer testing checklist template for copying:
```md
- [ ] Ensure a `helm template <release-name> <chart-path>` never fails
- [ ] Ensure a `helm template --set global.cattle.psp.enabled=true <release-name> <chart-path>` never fails
- [ ] Ensure a `helm install --dry-run <release-name> <chart-path>` does not fail when your `KUBECONFIG` is pointing to a 1.24 cluster
- [ ] Ensure a `helm install --dry-run --set global.cattle.psp.enabled=true <release-name> <chart-path>` does not fail when your `KUBECONFIG` is pointing to a 1.24 cluster
- [ ] Ensure a `helm install --dry-run <release-name> <chart-path>` does not fail when your `KUBECONFIG` is pointing to a 1.25 cluster
- [ ] Ensure a `helm install --dry-run --set global.cattle.psp.enabled=true <release-name> <chart-path>` does not fail when your `KUBECONFIG` is pointing to a 1.25 cluster
- [ ] Ensure a `helm install <release-name> <chart-path>` does not fail when your `KUBECONFIG` is pointing to a 1.24 cluster
- [ ] Ensure a `helm install --set global.cattle.psp.enabled=true <release-name> <chart-path>` does not fail when your `KUBECONFIG` is pointing to a 1.24 cluster
- [ ] Ensure a `helm install <release-name> <chart-path>` does not fail when your `KUBECONFIG` is pointing to a 1.25 cluster
- [ ] Ensure a `helm install --set global.cattle.psp.enabled=true <release-name> <chart-path>` does fail when your `KUBECONFIG` is pointing to a 1.25 cluster, with the error from `validate-psp-install.yaml` showing up
```

**Comment by ronhorton** [comment]
**Pass** Verified in rancher `v2.7.2-rc5`
https://zube.io/rancher/rancher/c/53854#:~:text=Some%20QA%20Test-,Cases,-to%20consider%3A for QA included in feature charts test plan. All points tested & verified.

**Comment by kevinayres** [comment]
This issue was closed but I still get the error on EKS 1.25 with rancher-stable 

"helm install rancher --set global.cattle.psp.enabled=false" ... resolved it

**Comment by seemsindie** [comment]
For me too 
![image](https://user-images.githubusercontent.com/1268576/233807017-a3b8fdab-52d1-4150-85fb-7e77e718b0cf.png)

**Comment by timothystewart6** [comment]
I too still get this error

`k3s 1.25.8` & `k3s 1.25.9`

Rancher 2.7.3

```
Helm upgrade failed: execution error at (rancher/templates/validate-psp-install.yaml:4:5): The target cluster does not have the PodSecurityPolicy API resource. Please disable PSPs in this chart before proceeding. Last Helm logs: preparing upgrade for rancher resetting values to the chart's original version
```
