### ISSUE TITLE
[BUG]kubelet is storing hundreds of MB of Calico CNI logs in the container overlay

### ISSUE THREAD

**Issue by dbravo0531** [rancher/rancher#40330]
**Rancher Server Setup**
- Rancher version: 2.6.9
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: 1.19 and 1.21
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:

**Describe the bug**
[Bug/RKE] kubelet is storing hundreds of MB of Calico CNI logs in the container overlay
 Actual results: /var/log/calico/cni fills with hundreds of MB of logs.

Looking at the kubelet command line options, note that there is no `--volumes=/var/log/calico` of any kind, which is why the logs end up in the overlayfs:

docker run --rm -v /var/run/docker.sock:/var/run/docker.sock [docker.io/assaflavie/runlike:1.4.4](https://docker.io/assaflavie/runlike:1.4.4) -p kubelet
docker run \
        --name=kubelet \
        --hostname=drekar-rancher-na-dev-a \
        --pid host \
        --env=PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
        --volume=/etc/kubernetes:/etc/kubernetes:z \
        --volume=/etc/cni:/etc/cni:rw,z \
        --volume=/opt/cni:/opt/cni:rw,z \
        --volume=/var/lib/cni:/var/lib/cni:z \
        --volume=/var/lib/calico:/var/lib/calico:z \
        --volume=/etc/resolv.conf:/etc/resolv.conf \
        --volume=/sys:/sys:rprivate \
        --volume=/var/lib/docker:/var/lib/docker:rw,rslave,z \
        --volume=/var/lib/kubelet:/var/lib/kubelet:shared,z \
        --volume=/var/lib/rancher:/var/lib/rancher:shared,z \
        --volume=/var/run:/var/run:rw,rprivate \
        --volume=/run:/run:rprivate \
        --volume=/etc/ceph:/etc/ceph \
        --volume=/dev:/host/dev:rprivate \
        --volume=/var/log/containers:/var/log/containers:z \
        --volume=/var/log/pods:/var/log/pods:z \
        --volume=/usr:/host/usr:ro \
        --volume=/etc:/host/etc:ro \
        --volumes-from=service-sidekick \
        --network=host \
        --privileged \
        --restart=always \
        --label='[io.rancher.rke.container.name](https://io.rancher.rke.container.name/)=kubelet' \
        --label='org.opencontainers.image.url=https://github.com/rancher/hyperkube' \
        --label='org.opencontainers.image.revision=45f277531affda80baa80398fa2d6cc4a75058a3' \
        --label='org.opencontainers.image.source=https://github.com/rancher/hyperkube.git' \
        --label='org.opencontainers.image.created=2022-03-04T16:18:38Z' \
        --log-opt compress=true \
        --log-opt max-file=7 \
        --log-opt max-size=100m \
        --runtime=runc \
        --detach=true \
        rancher/hyperkube:v1.21.10-rancher1

**To Reproduce**
Rancher 2.6.9
Steps to reproduce: This issue occurs in k8s 1.19 and 1.21.

**Result**

**Expected Result**
Expected results: kubelet does not write logs into container overlay

SURE-5814

**Comment by Sahota1225** [comment]
Moving this issue to Q3 for now because this issue needs to go with rancher release that introduce new k8s version.

**Comment by snasovich** [comment]
Kicked it out to Q4 as at this point we're not sure if we're introducing new k8s versions in Q3 release or doing July k8s patches out of band.
Can pull back into Q3 depending on the above.

**Comment by snasovich** [comment]
Closing this issue as "won't do" at this time due to lack of interest and challenges with timing the implementation (see https://github.com/rancher/rke/pull/3218#issuecomment-1513404004 for the context).
