### ISSUE TITLE
Update rancher-charts/rancher-cis-benchmark chart to support updated approach for PSPs

### ISSUE THREAD

**Issue by stormqueen1990** [rancher/rancher#40345]
### Parent issue: rancher/rancher#40331
---
Implement the changes specified in the parent issue for the rancher-cis-benchmark chart.

**Comment by mitulshah-suse** [comment]
Details regarding behaviour of CIS scans on 1.25 cluster have been added in the issue https://github.com/rancher/rancher/issues/39851 which need to be added to the release notes.

**Comment by ronhorton** [comment]
**Pass** Verified in rancher `v2.7.2-rc5`
confirmed [39581](https://github.com/rancher/rancher/issues/39851) has release note label
