### ISSUE TITLE
Update rancher-charts/longhorn chart to support updated approach for PSPs

### ISSUE THREAD

**Issue by aiyengar2** [rancher/rancher#40342]
### Parent issue: rancher/rancher#40331
---
Implement the changes specified in the parent issue for the longhorn chart.

- Create a new chart version (102.0.0+up1.4.0)
- Update the default from `true` to `false` for the variable `enablePSP` for the UI setting in questions.yml. It appears that the [value in the Chart.yaml](https://github.com/rancher/charts/blob/dev-v2.7/charts/longhorn/101.2.0%2Bup1.4.0/values.yaml#L321) is already set to `false`
   - https://github.com/rancher/charts/blob/dev-v2.7/charts/longhorn/101.2.0%2Bup1.4.0/questions.yaml#L827 
- Add the context in the [app-readme.md](https://github.com/rancher/charts/blob/dev-v2.7/charts/longhorn/101.2.0%2Bup1.4.0/app-readme.md) file about the changes related to PSPs. Example content is in the main parent issue linked above.  Please note that all the other charts are getting the same value name, but we are not expecting that change for our SUSE projects (aka longhorn)
- Add a validation psp install check in the chart so that if someone tries to enable PSPs on a cluster that doesn’t have the capability, then it would error out. Note: This is recommended for the upstream Longhorn chart and not just our “patched” upstream. Code on how to do this is in the parent issue. 

Cleanup note:
Can you please also remove this line from the Chart.yaml as this line implies that there is custom UI for this feature chart which doesn't exist according to the UI code?

https://github.com/rancher/charts/blob/dev-v2.7/charts/longhorn/101.2.0%2Bup1.4.0/Chart.yaml#L12

**Comment by PhanLe1010** [comment]
Longhorn chart already handles PSP/PSA stuff so we don't need to use the Rancher chart approach (which is creating the new setting `.Values.global.cattle.psp.enabled`) 

The upstream chart has been running on Kubernetes >= 1.25 for a while now. There is no issue coming up yet.

**Comment by PhanLe1010** [comment]
Discussed with Denise. We will implement the suggestions in Longhorn 1.4.0 chart for Rancher chart dev-v2.7

**Comment by PhanLe1010** [comment]
Test plan:

1. Deploy Rancher 2.7.2-rc
2. Add the chart repo in this PR
3. Create 2 downstream clusters: One 1.24 and one 1.25 Kubernetes version
4. Install Longhorn `102.2.0+up1.4.0` chart with `enablePSP` set to `true`
5. Verify that:
    1.  On K8s 1.24 cluster, it is installed fine
    2.  On K8s 1.25 cluster, it failed to be installed with the PSP error message 
6. For the 1.25 cluster, try to remove the Helm secrete and reinstall  Longhorn `102.2.0+up1.4.0` chart with `enablePSP` set to `false`. Verify that it is installed ok
7. For the 1.25 cluster, perform the in-place upgrade the chart to the same version `102.2.0+up1.4.0`  but with `enablePSP` set to `false`
8. Upgrade K8s to 1.25
9. Verify that the Longhorn system is healthy

**Comment by roger-ryao** [comment]
Validation Pass on **Rancher v2.7.2-rc3** and tested in below steps

**The test steps**


1. Deploy Rancher **2.7.2-rc3**
2. Add the chart repo in https://github.com/rancher/charts/pull/2385
3. Create 2 downstream clusters: One 1.24 and one 1.25 Kubernetes version
4. Install Longhorn 102.2.0+up1.4.0 chart with enablePSP set to true. Verify that:
![Screenshot_20230217_155129](https://user-images.githubusercontent.com/104337648/219613594-3ac5258d-d563-45aa-b37c-9ba665d26531.png)
    - [x]   On K8s 1.24 cluster, it is installed fine
    - [x]   On K8s 1.25 cluster, it failed to be installed with the PSP error message
![Screenshot_20230217_160410](https://user-images.githubusercontent.com/104337648/219613717-984a67f6-f2d7-41e1-bf47-2e85c646092d.png)


For the 1.25 cluster,

    - [x]   Try to remove the Helm secrete and reinstall Longhorn 102.2.0+up1.4.0 chart with enablePSP set to false.
    - [x]   Verify that it is installed ok

For the 1.24 cluster:

    - [x]   The version 101.2.0+up1.4.0 upgrade the chart to the same version 102.2.0+up1.4.0 but with enablePSP set to false
    - [x]   Upgrade K8s to 1.25
    - [x]   Verify that the Longhorn system is healthy
    
5. Uninstall

    - [x] Longhorn CRD all cleaned up
    - [x] Namespace longhorn-system deleted success
    
    cc @PhanLe1010 @khushboo-rancher

**Comment by PhanLe1010** [comment]
Thank you very much @roger-ryao
