### ISSUE TITLE
Update rancher-charts/neuvector chart to support updated approach for PSPs

### ISSUE THREAD

**Issue by stormqueen1990** [rancher/rancher#40343]
### Parent issue: rancher/rancher#40331
---
Implement the changes specified in the parent issue for the neuvector chart.

- Create a new chart version (102.0.0+up2.4.0)
- Add the context in the [app-readme.md](https://github.com/rancher/charts/blob/dev-v2.7/charts/neuvector/101.0.2%2Bup2.4.0/app-readme.md) file about the changes related to PSPs for running within Rancher Manager. Example content is in the main parent issue linked above. Please note that all the other charts are getting the same value name, but we are not expecting that change for our SUSE projects (aka NeuVector), so the language may need to be updated. 
- Add a validation psp install check in the chart so that if someone tries to enable PSPs on a cluster that doesn’t have the capability, then it would error out. Note: This is recommended for the upstream NeuVector chart and not just our “patched” upstream as it could be updated to true and it would cause immediate errors on a k8s 1.25 cluster. Code on how to do this is in the parent issue.

Cleanup note:
Can you please also remove this line from the Chart.yaml as this line implies that there is custom UI for this feature chart which doesn't exist according to the UI code?

https://github.com/rancher/charts/blob/dev-v2.7/charts/neuvector/101.0.2%2Bup2.4.0/Chart.yaml#L13

**Comment by prachidamle** [comment]
Note: The new chart version should be 102.x.y - Also, if you plan to release only this version in Rancher 2.7.2, please remove using `make remove` any older 101.x.x versions that you may have in release.yaml earlier for 2.7.2 release

**Comment by selvamt94** [comment]
@prachidamle I am about to make PR today for the changes mentioned in this issue for 2.7.2 release. Do we need to remove older version 101.x.x or up to us to decide.

**Comment by selvamt94** [comment]
Created a PR to fix the issue. The fix includes
+ Added global variable to set PSP
+ Updated questional yaml
+ Added PSP validation yaml
+ Removed other psp configuration from yaml
+ Updated psp.yaml template to include global psp value
+ removed UI component from Charts.yaml
+ Updated app-readme to include PSP detail
+ Bumped version to 102.0.0

https://github.com/rancher/charts/pull/2395

**Comment by prachidamle** [comment]
@selvamt94 yes ideally we should release only one version with Rancher manager - if you do not intend to release multiple Neuvector versions with Rancher 2.7.2, we should remove the older 101.x.x versions in the release.yaml https://github.com/rancher/charts/blob/dev-v2.7/release.yaml#L18

**Comment by cbron** [comment]
PR merged

**Comment by ronhorton** [comment]
**Pass** verified in rancher `2.7.2-rc8`

this chart was tested in https://github.com/rancher/rancher/issues/39856
