### ISSUE TITLE
Sidekick name should have same rules as Servicename

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4035]
Version - master UI 3/18

Steps to Reproduce: 
1.  Create a sidekick name with a space in it

Results: Allows you do create

Expected: Should follow same rules as Service name
validChars": "a-zA-Z0-9-",
"minLength": 1,
"maxLength": 63,
No double "-"

**Comment by vincent99** [comment]
Needs validChars in API

**Comment by tfiduccia** [comment]
Version - master 3/20
Verified fixed
