### ISSUE TITLE
Update rancher-charts/ui-plugin-operator chart to support updated approach for PSPs

### ISSUE THREAD

**Issue by stormqueen1990** [rancher/rancher#40351]
### Parent issue: rancher/rancher#40331
---
Implement the changes specified in the parent issue for the ui-plugin-operator chart.

**Comment by ronhorton** [comment]
**Pass** verified in rancher `v2.7.2-rc8`

**Test 1: Upgrade Test**
1. enabled extensions on 1.24 cluster
2. installed kube-warden
3. added kube-warden repo
4. upgraded k8s to 1.25
5. added default policyservers chart to kube warden
`result: Pass`

**Test 2: Fresh Install**
1. enabled extensions
2. installed kube warden
3. installed OS management
4. added default policyservers chart to kube warden
`result: Pass`
