### ISSUE TITLE
Cant create kubernetes loadbalancers if hostname has dot

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#4036]
Steps to reproduce:
1. Create a kubernetes environment using hosts that have dots in their hostnames
2. Attempt to create a k8s load balancer

Expected result:
LB service in rancher keeps getting created and destroyed

Actual result:
Should create LB

Root case:
In the kubernetes cloud provider, we create an external service for each host included in an LB. We name the external service the same as the host name. If the hostname has a dot in it, the API rejects the call.

Fix:
Sanitize the names. Must be:
- Great than 0 chars
- Less than 64 chars
- Contain only A-Z a-z 0-9 and hyphens
- No two hyphens togehter
- Cant start or end with a hyphen

**Comment by deniseschannon** [comment]
Verified with v1.0.0-rc1 with having a host called `denise.k8s` and I was able to add GuestBook (which uses a LB).
