### ISSUE TITLE
[rancher-pushprox] Deprecated PSPs in K8S v1.25

### ISSUE THREAD

**Issue by kladiv** [rancher/rancher#40372]
Hello
like another PR for rancher-logging (https://github.com/rancher/charts/pull/2272) we need the same fix for standalone [rancher-pushprox](https://github.com/rancher/charts/tree/dev-v2.7/charts/rancher-pushprox) Helm Chart to support K8S v1.25
Actually it does not work on that release.

Are you able to update the Helm Chart like did for [k3sServer](https://github.com/rancher/charts/tree/dev-v2.7/charts/rancher-monitoring/101.1.0%2Bup40.1.2/charts/k3sServer) subchart or rancher-monitoring?

Thank you

**Comment by kladiv** [comment]
Hi @MKlimuszka,
i see new feature (to disable PSP) is not still available in Rancher helm charts here: https://charts.rancher.io/index.yaml
Is there any ETA?

Thank you

**Comment by geethub97** [comment]
The rancher/pushprox standalone chart was updated by https://github.com/rancher/charts/pull/2375, where https://github.com/rancher/charts/blob/dev-v2.7/charts/rancher-pushprox/102.0.0/templates/validate-psp-install.yaml was added to support K8s 1.25. The script will throw an error if a user tries to install pushprox with PSPs enabled on a cluster where they are deprecated.

**Comment by AndrewHoffmanQA** [comment]
ticket scope:

a request that chart 'Pushprox' is updated to support k8s 1.25 support on non hardened clusters.

testing steps-

1.  stand up a rancher cluster with 1.25+ k8s (mine is v1.25.6)
2.  open the cluster's kubectl 
3. helm repo add rancher-charts https://charts.rancher.io
4.  `helm repo add rancher-charts https://charts.rancher.io/`
5. 'helm repo update'
6. 'helm install rancher-pushprox rancher-charts/rancher-pushprox --set global.cattle.psp.enabled=false'
7.  navigate to installed apps page- verify pushprox app is installed successfully (the version I installed is 102.0.0)
8. navigate to workloads and confirm pushprox client and the proxy are running correctly.

**Comment by AndrewHoffmanQA** [comment]
testing passed. Pushprox can be stand alone installed on a 1.25k8 cluster running 2.7-head on a HA local 3 machines (all roles)

![2023-05-09_10-10-25.png](https://zube.io/files/rancher/07aa4b59e965a7656a1ecda4ff73c0bc-2023-05-09_10-10-25.png)
