### ISSUE TITLE
Support for updated PSP handling for `system-upgrade-controller` (SUC) from `charts`

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#40384]
`system-upgrade-controller` (SUC) chart (https://github.com/rancher/charts/tree/dev-v2.7/charts/system-upgrade-controller) is a Managed Rancher chart currently used by RKE2/k3s v2prov provisioning framework to upgrade `system-agent` on downstream clusters' nodes. "Managed Rancher chart" here means the chart is automatically installed/uninstalled/upgraded without explicit user interaction.

## The Issue
The chart currently deploys PSP and related resources and even with the recent [change](https://github.com/rancher/charts/pull/2338/files#diff-a607fb89c3ee8edff22b3016e694bdafeb585ffe7dfe82f8474b279ed0a9f7e5R1) to not deploy PSPs if API is not available, there is a potential issue with upgrade flow.

Consider the following scenario:
1. k8s 1.24 RKE2 downstream cluster is provisioned from Rancher
	- This deploys SUC chart to the downstream cluster which in turn creates PSP and related resources from `psp.yaml` file.
	- Helm creates a secret of type "Helm Release" to store objects that got created
2. The downstream cluster is upgraded to k8s 1.25 (on Rancher release 2.7.2)
	- k8s 1.25+ no longer serves PSP API; however that "Helm Release" secret still has a record of PSP resource created
3. If SUC needs to be upgraded/reinstalled, it will fail because `helm uninstall` / `helm upgrade` would fail due to having record of PSP created on install (see https://github.com/helm/helm/issues/11287). SUC upgrade/reinstall will be triggered by Rancher upgrade to version _after_ 2.7.2, but there are probably other cases where it will be triggered.

## Solution Outline
Block (defer) upgrade to 1.25+ until Rancher deploys a version of the SUC chart that has the PSPs disabled, and ensure the chart has actually rolled out before proceeding with the actual upgrade to 1.25+

### Additional Solution Details
Courtesy of @Oats87 
#### v2prov Planner Modifications
- `managesystemagentplan.go` needs to set a condition after it checks the status of the bundle, to see if the bundle is ready: https://fleet.rancher.io/cluster-bundles-state (bonus points if the condition contains a hash or something of the bundle so that we don’t have the possibility of inconsistency if we reuse the condition in the future). It also needs to check for the version of k8s on the cluster object and if it’s >= 1.25, make sure to disable PSP via the chart option detailed below.
- `planner.go` needs to be modified to not allow an upgrade to 1.25+ (i.e. halt any plan modifications) if the bundle condition for ready is not set, AND ANY plans have been delivered to any of the nodes. There will probably have to be additional functionality added to the `store.go` load cluster to see if there are any plans that have been delivered already. Otherwise, proceed with reconcilation.  Ideally, we should provide feedback about this to the user, and this is the one and only time they can revert their K8s version, but that should not be advertised.

#### Chart Updates
Need to update SUC chart to support a flag that completely turns off PSP.
```
global:
  cattle:
     psp:
        enabled: true
```
The actual chart should have:
```
{{- if .Values.global.cattle.psp.enabled }}
{{- if not (.Capabilities.APIVersions.Has "policy/v1beta1/PodSecurityPolicy") }}
  {{- fail "The target cluster does not have the PodSecurityPolicy API resource. Please disable PSPs before proceeding." -}}
{{- else }}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
 
...
 
{{- end }}
{{- end }}
```
This will need to be updated in `rancher/system-charts` in `rancher-k3s-upgrader`, and then eventually in the `rancher/charts` repo.

## Misc
Parent Issue: https://github.com/rancher/rancher/issues/38701

**Comment by sowmyav27** [comment]
Tests to be included during validation:

1. On 2.7.0 - deploy RKE2 1.24 cluster (Node driver or custom cluster). Upgrade Rancher to 2.7.2-rc (with fix) or 2.7-head , verify the SUC has upgraded. Verify user is able to upgrade RKE2 to 1.25. 
2. On 2.7.0 - deploy k3s 1.24 cluster (Node driver or custom cluster). Upgrade Rancher to 2.7.2-rc (with fix) or 2.7-head , verify the SUC has upgraded. Verify user is able to upgrade k3s to 1.25.

**Comment by HarrisonWAffel** [comment]
This issue has been merged into 2.7-head and can now be tested. I've added some lengthy test steps to the PR that QA can reference, if there are any issues please reach out asap.

**Comment by markusewalker** [comment]
**QA TEST PLAN**

|Scenario|Test Case|
|---|---|
|1|Validate SUC upgrades after upgrading Rancher v2.7.1 -> v2.7-head + RKE2 node driver cluster v1.24 → v1.25|
|2|Validate SUC upgrades after upgrading Rancher v2.7.1 -> v2.7-head + K3s node driver cluster v1.24 → v1.25|
|3|Create etcd snapshot with RKE2 node driver cluster v1.24 in Rancher v2.7.1, upgrade Rancher to v2.7-head, upgrade to v1.25 and restore|
|4|Create etcd snapshot with K3s node driver cluster v1.24 in Rancher v2.7.1, upgrade Rancher to v2.7-head, upgrade to v1.25 and restore|

**Comment by HarrisonWAffel** [comment]
The build for this PR has partially passed after several restarts. The provisioning tests were flakey, but passed on prior ci executions. Regardless, the most recent run has published the required assets needed to test this issue, so testing is good to go

**Comment by markusewalker** [comment]
Upon testing test scenario 3 and 4 in the above scenario, the following UI [issue](https://github.com/rancher/dashboard/issues/8281) was found. As such, going to mark this issue as blocked until that is resolved.

**Comment by markusewalker** [comment]
Closed UI issue as it appeared to have been a fluke; I consistently am not seeing the reported behavior on RKE2/K3s. I can proceed forward with the test plan now, so updating to `QA Working`.

**Comment by markusewalker** [comment]
Validated that this is addressed. See details below:

**ENVIRONMENT DETAILS**
- Rancher install: Docker
- Rancher version
     - Fresh install: `v2.7.0`
     - Upgraded: `v2.7.0` -> `v2.7-head`
- Browser: Chrome

**TEST RESULT**
|Scenario|Test Case|Result
|---|---|---|
|1|Validate SUC upgrades after upgrading Rancher v2.7.1 -> v2.7-head + RKE2 node driver cluster v1.24 → v1.25|:white_check_mark:|
|2|Validate SUC upgrades after upgrading Rancher v2.7.1 -> v2.7-head + K3s node driver cluster v1.24 → v1.25|:white_check_mark:|
|3|Validate SUC upgrades after upgrading Rancher v2.7.1 -> v2.7-head + RKE2 imported cluster v1.24 → v1.25|:white_check_mark:|
|4|Validate SUC upgrades after upgrading Rancher v2.7.1 -> v2.7-head + K3s imported cluster v1.24 → v1.25|:white_check_mark:|
|5|Create etcd snapshot with RKE2 node driver cluster v1.24 in Rancher v2.7.1, upgrade Rancher to v2.7-head, upgrade to v1.25 and restore|:white_check_mark:|
|6|Create etcd snapshot with K3s node driver cluster v1.24 in Rancher v2.7.1, upgrade Rancher to v2.7-head, upgrade to v1.25 and restore|:white_check_mark:|
|7|On a fresh install of Rancher v2.7-head, validate SUC upgrades after upgrading RKE2 imported cluster v1.23 -> v1.24 -> v1.25|:white_check_mark:|
|8|On a fresh install of Rancher v2.7-head, validate SUC upgrades after upgrading K3s imported cluster v1.23 -> v1.24 -> v1.25|:white_check_mark:|

**VALIDATION STEPS**

**Scenario 1**
1. Provisioned a v1.24 RKE2 downstream cluster with RKE2 Default set as PSP value.
2. Validated that the cluster and nodes come up as Active in Cluster Management and Cluster Explorer.
3. Verified the workloads/pods in System project page are up and `Active`.
4. Navigated to RKE2 cluster's workload and took note of the SUC version (v0.9.1) and that `rancher/system-agent:v0.2.13-suc`.
5. Upgraded to Rancher to the latest `v2.7-head`.
6. Validated that the cluster and nodes did not auto-upgrade and that they remained in `Active` state in both Cluster Management and Cluster Explorer.
7. Took note again of the SUC version; validated that SUC upgraded and image `rancher/system-agent:v0.3.2-suc` successfully upgraded.
8. Upgraded the cluster to v1.25 and ensure the PSA level is set to `rancher-restricted`.
9. Validate that the upgrade was successful and that the cluster and nodes are still Active in Cluster Management and Cluster Explorer.
10. Viewed the cluster YAML and validate that `spec.defaultPodSecurityAdmissionTemplateName`  is set to `rancher-restricted`.
11. Created a new pod with the container image nginx:latest and default settings in the test namespace; validated that the pod DOES NOT create.

_____
**Scenario 2**
1. Repeated scenario 1, but using K3s as the downstream cluster instead.
2. Validated that all steps were successful as mentioned in scenario 3, but with K3s instead.

____
**Scenario 3**
1. Navigated to a client machine and created an RKE2 cluster to be later imported into Rancher.
2. As a standard user, navigated to Rancher UI.
3. Imported the RKE2 cluster; validated that the cluster and nodes came up as `Active`.
4. Verify the workloads/pods in System project page are up and `Active`.
5. Upgraded Rancher to `v2.7-head`; validated that the cluster and nodes did not auto-upgrade and remained `Active`.
6. Took note that the `system-upgrade-controller` image tag is at `v0.10.0`.
7. Edited the cluster config of the 1.24 cluster and updated the K8s version to 1.25.
8. Upgraded the cluster and see the following:
![image](https://user-images.githubusercontent.com/52591819/221671080-4fcf3384-a9e0-4154-a711-742423e38a21.png) 
9. Validated that the cluster and nodes upgraded successfully to v1.25 and are `Active` in Cluster Management and Cluster Explorer.
10. Verified the workloads/pods in System project page are up and `Active`.
11. Validated that the `system-upgrade-controller` image tag still at `v0.10.0`.
______
**Scenario 4**
1. Repeated scenario 3, but used an imported K3s cluster instead.
_______
**Scenario 5**
1. Provisioned a v1.24 RKE2 downstream cluster with RKE2 Default set as PSP value.
2, Validated that the cluster and nodes come up as Active in Cluster Management and Cluster Explorer.
3. Verify the workloads/pods in System project page are up and Active.
4. Navigated to RKE2 cluster's workload and took note of the SUC version and that `rancher/system-agent:v0.2.13-suc`.
5. Upgraded to Rancher to the latest `v2.7-head`.
6. Validate that the cluster and nodes did not auto-upgrade and that they remain in Active state in both Cluster Management and Cluster Explorer.
7. Took note again of the SUC version; validated that SUC upgraded and image `rancher/system-agent:v0.3.2-suc` successfully upgraded.
8. Took an etcd snapshot of the RKE2 downstream cluster.
9. Created deployments `d1` ,`d2` and `d3` , all with `nginx:latest` as the container image.
10. Validated that they all come up as Active .
11. Upgraded the cluster to v1.25 and ensure the PSA level is set to rancher-restricted .
12. Validated that the upgrade was successful and that the cluster and nodes are still Active in Cluster Management and Cluster Explorer.
13. Viewed the cluster YAML and validate that `spec.defaultPodSecurityAdmissionTemplateName`  is set to `rancher-restricted`.
14. Restored the etcd snapshot with options cluster configuration, Kubernetes version and etcd.
15. Validated the following items:
     - Cluster is back at v1.24
     - Cluster configuration is back to the v1.24 configuration and is not at the v1.25 configuration
     - The SUC version is back at the v1.24 viewed version
     - The d1 , d2 and d3 deployments do not appear
______
**Scenario 6**
1. Repeated scenario 5, but used K3s instead as the downstream cluster.
2. Validated that all steps were successful as mentioned in scenario 5, but using a K3s downstream cluster.
______
**Scenario 7**
1. Navigated to a client machine and created an RKE2 cluster to be later imported into Rancher.
2. As a standard user, navigated to Rancher UI.
3. Imported the RKE2 cluster; validated that the cluster and nodes came up as `Active`.
4. Verify the workloads/pods in System project page are up and `Active`.
5. Took note that the `system-upgrade-controller` image tag is at `v0.9.1`.
6. Edited the cluster config of the 1.24 cluster and updated the K8s version to 1.25.
7. Upgraded the cluster and see the following:
![image](https://user-images.githubusercontent.com/52591819/221671186-1452c41d-9c8a-47b2-81a9-5e8879d0c9f7.png) 
8. Validated that the cluster and nodes upgraded successfully to v1.25 and are `Active` in Cluster Management and Cluster Explorer.
9. Verified the workloads/pods in System project page are up and `Active`.
10. Validated that the `system-upgrade-controller` image tag upgraded to `v0.10.0`.
________
**Scenario 8**
1. Repeated scenario 7, but used a K3s imported cluster instead with the same successful results.
