### ISSUE TITLE
Error message for last admin account is unprofessional

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4039]
Version - master 3/18

Steps to Reproduce: 
1.  Enable local authentication
2.  Go to accounts and click on edit for the admin
3.  Try to change the Account Type to User

Results: Error message that comes up is unprofessional
![image](https://cloud.githubusercontent.com/assets/11514927/13889583/994097d8-ed04-11e5-827a-22aef07f829b.png)

Expected: Please remove everything in the the parentheses.  Also please rephrase Error to say "Cannot change the Account Type for the last Admin account"

**Comment by ibuildthecloud** [comment]
https://github.com/rancher/cattle/pull/1511

**Comment by tfiduccia** [comment]
Version - master 3/18
Verified fixed
