### ISSUE TITLE
Monitoring V2 Introduction and Release Documents

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#40397]
Create documents that cover an introduction to monitoring v2. Present them to the Opni team and post them internally.

**Comment by ronhorton** [comment]
asked for link to docs.

**Comment by geethub97** [comment]
@ronhorton the majority of the monitoring and federator developer docs can be found here: https://github.com/rancher/prometheus-federator/tree/main/docs

**Comment by ronhorton** [comment]
LGTM!
