### ISSUE TITLE
[BUG] v2.7.1 - Pod Recent Events Missing?

### ISSUE THREAD

**Issue by voarsh2** [rancher/rancher#40406]
**Rancher Server Setup**
- Rancher version: v2.7.1
- Installation option (Docker install/Helm Chart): Docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: 1.23

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:
Cluster Owner

**Describe the bug**

I previously deployed RKE1, and was on Rancher V 2.6.4 - PODs had Recent Events, just like deployments/etc, and pod events showed you healthcheck and termination reasons, etc. But After reinstalling Rancher v2.7.1 and deploying a fresh RKE2 instance, recent events in PODS does not show up........

**To Reproduce**

**Result**

**Expected Result**

**Screenshots**

![image](https://user-images.githubusercontent.com/60437695/216329462-643ca393-cdab-44dd-a0cf-2d1458fd3502.png)

**Additional context**

**Comment by niusmallnan** [comment]
This is a known issue, pls refer to: https://github.com/rancher/dashboard/issues/7374

**Comment by voarsh2** [comment]
> This is a known issue, pls refer to: [rancher/dashboard#7374](https://github.com/rancher/dashboard/issues/7374)

Oops - I usually search for issues before posting, glad it's known. Thanks.

**Comment by voarsh2** [comment]
Fixed.
