### ISSUE TITLE
[BUG] CIS Benchmark chart fails to upgrade

### ISSUE THREAD

**Issue by rishabhmsra** [rancher/rancher#40405]
**Rancher Server Setup**
- Rancher version: v2.7-head(9bb8d56)
- Installation option (Docker install/Helm Chart): Docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):

**Information about the Cluster**
- Kubernetes version: v1.25.6+rke2r1
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): aws node driver

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Admin
  - If custom, define the set of permissions:

**Describe the bug**

- Upgrading the CIS benchmart chart `3.0.1-rc7` to same version `3.0.1-rc7` errors out with below logs:
```
...
delete-rolebinding: Jobs active: 1, jobs failed: 1, jobs succeeded: 0
Add/Modify event for delete-rolebinding: MODIFIED
delete-rolebinding: Jobs active: 0, jobs failed: 1, jobs succeeded: 0
Add/Modify event for delete-rolebinding: MODIFIED
Starting delete for "delete-rolebinding" Job
Error: UPGRADE FAILED: pre-upgrade hooks failed: job failed: BackoffLimitExceeded
```
- **`delete-rolebinding-*` pod logs:**
```
Error from server (Forbidden): clusterrolebindings.rbac.authorization.k8s.io "cis-operator-rolebinding" is forbidden: User "system:serviceaccount:cis-operator-system:cis-operator-serviceaccount" cannot delete resource "clusterrolebindings" in API group "rbac.authorization.k8s.io" at the cluster scope
Error from server (Forbidden): clusterrolebindings.rbac.authorization.k8s.io "cis-operator-installer" is forbidden: User "system:serviceaccount:cis-operator-system:cis-operator-serviceaccount" cannot delete resource "clusterrolebindings" in API group "rbac.authorization.k8s.io" at the cluster scope
```

**To Reproduce**

- Provision a RKE2 v1.25.6+rke2r1, ec2 node driver cluster(2-cp, 3-e, 3-w)
- Goto Apps -> Install CIS benchmark chart version `3.0.1-rc7`. It will get installed successfully.
- Again goto Apps -> CIS benchmark chart -> update it to same version `3.0.1-rc7`. 

**Result**
- CIS benchmark chart fails to update.

**Expected Result**

- Chart should get upgraded successfully.

**Comment by vardhaman22** [comment]
the **delete-rolebinding** here is deleting clusterrolebindings as a part of pre update of the chart which i believe will be taken care of by helm automatically while upgrading i.e. if those bindings are not present/ changed in any newer version then helm will delete/patch them by itself and also in case of uninstall of the chart these will be removed by helm only.
So in my opinion this job is redundant and hence we can remove it.
@galal-hussein please advice.
this change was added for [issue](https://github.com/rancher/cis-operator/issues/165) in PR: https://github.com/rancher/charts/pull/2151/files 
cc: @prachidamle

**Comment by rishabhmsra** [comment]
Validated on rancher v2.7-head(61dae8d)

**Scenario 1 :**
- Created a k8s v1.25.6+rke2r1, ec2, node driver cluster.
- Installed CIS benchmark chart version `3.0.1-rc8` and upgraded it to same version `3.0.1-rc8`.
- Chart upgraded successfully, permissive profile scan also passed.

**Scenario 2 :**
- On k8s v1.25.6+rke2r1 cluster, installed CIS benchmark chart version `2.1.0` and upgraded it to latest version `3.0.1-rc8`.
- Chart upgraded successfully, permissive profile scan also passed.

**Scenario 3 :**
- Created a k8s v1.24.10+rke2r1, ec2, node driver cluster.
- Installed CIS benchmark chart version `3.0.0` and upgraded the chart to version `3.0.1-rc8`.
- Chart upgraded successfully, permissive profile scan also passed.

**Scenario 4 :**
- On k8s `v1.24.10+rke2r1` cluster, installed CIS benchmark chart version `2.1.0`.
- Upgraded the chart version to `3.0.0` and then upgraded it to latest version `3.0.1-rc8`.
- Chart upgraded successfully, permissive profile scan also passed.

**Result :**
- Chart upgrade is successful. Pods are up and running:

![latest](https://user-images.githubusercontent.com/36376154/217520018-4bb0d28f-9d97-4715-be84-7745b1a84618.png)

- Permissive scan also passed, hence closing this issue.

![permissive](https://user-images.githubusercontent.com/36376154/217520131-e98c7e49-a799-41f7-847f-5d8814207f91.png)
