### ISSUE TITLE
Clicking on deactivate does nothing

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4040]
Version - master 3/18

Steps to Reproduce: 
1.  Authenticate using local auth
2.  Go to Account and try to deactivate last admin account

Results: Nothing happens

Expected: Maybe an error message should pop up saying that you cannot deactivate last admin account. Or maybe the menu item should be disabled?

**Comment by vincent99** [comment]
![image](https://cloud.githubusercontent.com/assets/753917/13901126/1bd5d6ae-edd7-11e5-9331-9f83fbbb2626.png)

**Comment by tfiduccia** [comment]
Version - master 3.20
Verified fixed
