### ISSUE TITLE
Rancher Metadata service should expose service and container state

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#4042]
Rancher Metadata returns services and containers that are not running (e.g. inactive, stopped, upgrading...) in its responses. Currently there is no way to identify these unavailable entities since the `state` API field is not exposed in the Metadata service.
This is especially problematic when generating config files (e.g. using [confd with Rancher backend](https://github.com/kelseyhightower/confd/blob/master/docs/quick-start-guide.md#rancher)) from the Metadata: You don't want stopped/unavailable container instances to go in there of course.

**Comment by alena1108** [comment]
@janeczku we haven't added service.state to metadata deliberately as a) we don't update metadata on each and every service state change b) most of users app would rather rely on services' containers states, not on the service service itself - and from you've said above, that seems to be the case for your app as well.

Saving container.state/health state to the metadata is something that we have to address.  We've already addressed this issue partially by propagating health state to the metadata; lets keep this ticket as an enhancement request for propagating container.state as well.

**Comment by janeczku** [comment]
>  lets keep this ticket as an enhancement request for propagating container.state as well.

I agree. Exposing the container's state is enough. It's also essential for any kind of service discovery relying on the metadata service as not all containers will have health checks configured: https://github.com/janeczku/rancher-template

**Comment by cdrx** [comment]
@alena1108 #4308 had a 1.1 milestone and was closed duplicate into this issue. Do you think container state will be added to the metadata service for 1.1?

I'm working on integrating Traefik as a load balance for Rancher but blocked by not being able to weed out stopped containers from the configuration, which is generated from the metadata service.

**Comment by alena1108** [comment]
@cdrx we can make it work

**Comment by cdrx** [comment]
Great, thanks!

**Comment by alena1108** [comment]
We are going to propagate container state to metadata for now. I will file a separate bug for service state propagation.

**Comment by cdrx** [comment]
Thanks @alena1108

**Comment by alena1108** [comment]
@sangeethah to verify the bug, check that the container state is in metadata

**Comment by soumyalj** [comment]
Verified in master:
```
root@2c2ed4e25fe2:/# curl --header 'Accept: application/json' http://rancher-met
adata/2015-12-19/self/service
{"containers":[{"create_index":1,"health_state":null,"host_uuid":"3b1ffe0b-a5d7-
4522-b040-4bb2cdb91621","hostname":null,"ips":["10.42.253.198"],"labels":{"io.ra
ncher.container.pull_image":"always","io.rancher.project.name":"Default","io.ran
cher.project_service.name":"Default/newservicebug4042","io.rancher.service.deplo
yment.unit":"bffdfe84-98a5-42d9-988b-82a92d7e11c5","io.rancher.service.launch.co
nfig":"io.rancher.service.primary.launch.config","io.rancher.stack.name":"Defaul
t","io.rancher.stack_service.name":"Default/newservicebug4042"},"name":"Default_
newservicebug4042_1","ports":[],"primary_ip":"10.42.253.198","service_index":"1"
,"service_name":"newservicebug4042","stack_name":"Default","start_count":1,"stat
e":"running","uuid":"8d3a6b3c-f512-4a58-8348-dee63e19f3d0"}],"create_index":1,"e
xpose":[],"external_ips":[],"fqdn":null,"hostname":null,"kind":"service","labels
":{"io.rancher.container.pull_image":"always"},"links":{},"metadata":{},"name":"
newservicebug4042","ports":[],"scale":1,"sidekicks":[],"stack_name":"Default","t
oken":null,"uuid":"68d34202-5f88-485b-a2f5-6283cb7bbde8","vip":null}root@2c2ed4e
25fe2:/#
```
