### ISSUE TITLE
[BUG] When taking a snapshot of an RKE1 cluster with no PSACT value defined, editing the cluster's configuration to have a PSACT value and restoring the snapshot causes the PSACT value to persist when it shouldn't

### ISSUE THREAD

**Issue by markusewalker** [rancher/rancher#40433]
**Rancher Server Setup**
- Rancher version: `v2.7-head` https://github.com/rancher/rancher/commit/9bb8d5674d4f2fe85cca799b07a6d18eee257b9e
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: `v1.24`
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Linode

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Standard
  - If custom, define the set of permissions:

**Describe the bug**

As part of the broader K8s 1.25 testing efforts, one of the test scenarios involves restoring an RKE1 v1.25 cluster with PSACT enabled that was previously at v1.24 with no PSP or PSACT values enabled. The issue noted is that when you choose to restore with options cluster configuration, Kubernetes version and etcd, the cluster's configuration incorrectly still reflects my PSACT value at v1.24 despite not setting this value in v1.24.

It is important to note that this is not specific from v1.24 to v1.25. For instance, I provisioned a RKE1 v1.25 cluster with PSACT value `privileged`, created a snapshot, edited the PSACT value to `restricted` and restored the snapshot. In doing this, the cluster configuration did not update as the `defaultPodSecurityAdmissionConfigurationTemplateName` value remained at `restricted` instead of reverting back to `privileged`.

In short, it would appear that when restoring a snapshot with options cluster configuration, Kubernetes version and etcd, the cluster's configuration DOES NOT fully revert to the configuration before any post-snapshot updates.

**To Reproduce**

1. As a standard user, provision a RKE1 v1.24 cluster with no PSP or PSACT values set.
2. Validate that the cluster and nodes come up as `Active` in Cluster Management and Cluster Explorer.
3. Create a snapshot of the cluster in this state.
4. Edit the cluster's configuration and update the K8s version to v1.25 and PSACT value to `privileged`.
5. Validate the cluster and nodes are upgraded to v1.25 in Cluster Management and Cluster Explorer.
6. Validate in the cluster's YAML that `spec.defaultPodSecurityAdmissionTemplateName` is set to `privileged`.
7. Restore the previously-created snapshot from step 3 with options cluster configuration, Kubernetes version and etcd.
8. Once finished and cluster and nodes are back `Active`, view the cluster YAML and view that `spec.defaultPodSecurityAdmissionTemplateName` is still present.

**Result**
PSACT changes made to the cluster configuration post-snapshot creation are persisting after restoring my snapshot.

**Expected Result**
Any PSACT change that I made to my cluster configuration post-snapshot creation should NOT be reflected in my snapshot.

**Comment by markusewalker** [comment]
Testing this further, this does not seem specific to RKE1. With the same repro steps, I was able to validate that this is occurring on K3S as well, so presumably RKE2 also has this issue.

**Comment by jiaqiluo** [comment]
can be validated in the latest v2.7-head

**Comment by markusewalker** [comment]
**QA TEST PLAN**

Scenarios
|Scenario|Test Case|
|---|---|
|1|As a standard user, provision RKE1 v1.24 cluster with no PSP or PSA configured, create an etcd snapshot, upgrade to v1.25 cluster with PSA set to `rancher-privileged`, restore snapshot, validate cluster configuration matches v1.24 cluster configuration|
|2|As a standard user, provision RKE2 v1.24 cluster with no PSP or PSA configured, create an etcd snapshot, upgrade to v1.25 cluster with PSA set to `rancher-privileged`, restore snapshot, validate cluster configuration matches v1.24 cluster configuration|
|3|As a standard user, provision K3s v1.24 cluster with no PSP or PSA configured, create an etcd snapshot, upgrade to v1.25 cluster with PSA set to `rancher-privileged`, restore snapshot, validate cluster configuration matches v1.24 cluster configuration|
|4|Setup Rancher v2.7.1, provision RKE1 v1.23 cluster with no PSP configured, upgrade to Rancher v2.7-head, upgrade to v1.24 cluster with no PSP or PSA configured, create an etcd snapshot, upgrade to v1.25 with PSA set to `rancher-restricted`, restore snapshot, validate cluster configuration matches v1.24 cluster configuration|

**Comment by markusewalker** [comment]
Validated that this is addressed in `v2.7-head` https://github.com/rancher/rancher/commit/f741a6db138e2b84f11b78b2e1cbf38f631fe855.

**ENVIRONMENT DETAILS**
- Rancher install: Helm
- Rancher version: `v2.7-head` https://github.com/rancher/rancher/commit/f741a6db138e2b84f11b78b2e1cbf38f631fe855
- Browser: Chrome

**TEST RESULT**
|Scenario|Test Case|Result
|---|---|---|
|1|As a standard user, provision RKE1 v1.24 cluster with no PSP or PSA configured, create an etcd snapshot, upgrade to v1.25 cluster with PSA set to `rancher-privileged`, restore snapshot, validate cluster configuration matches v1.24 cluster configuration|:white_check_mark:|
|2|As a standard user, provision RKE2 v1.24 cluster with no PSP or PSA configured, create an etcd snapshot, upgrade to v1.25 cluster with PSA set to `rancher-privileged`, restore snapshot, validate cluster configuration matches v1.24 cluster configuration|:white_check_mark:|
|3|As a standard user, provision K3s v1.24 cluster with no PSP or PSA configured, create an etcd snapshot, upgrade to v1.25 cluster with PSA set to `rancher-privileged`, restore snapshot, validate cluster configuration matches v1.24 cluster configuration|:white_check_mark:|
|4|Setup Rancher v2.7.1, provision RKE1 v1.23 cluster with no PSP configured, upgrade to Rancher v2.7-head, upgrade to v1.24 cluster with no PSP or PSA configured, create an etcd snapshot, upgrade to v1.25 with PSA set to `rancher-restricted`, restore snapshot, validate cluster configuration matches v1.24 cluster configuration|:white_check_mark:|


**VALIDATION STEPS**

**Scenario 1**
1. As a standard user, provisioned a RKE1 downstream node driver v1.24 cluster with no PSP or PSA configured.
2. Validated that the cluster and nodes came up as `Active` in Cluster Management and Cluster Explorer.
3. Took note of the cluster's configuration via YAML to reference this later.
4. Created an etcd snapshot of the cluster; validated that it created successfully.
5. Edited the cluster's configuration and updated the K8s version to `v1.25` and updated the PSA value to `rancher-privileged`.
6. Validated that the cluster and nodes upgraded successfully to `v1.25` in Cluster Management and Cluster Explorer.
7. Once more, took note of the cluster's configuration via YAML; validated that it is different from the YAML seen in v1.24.
     - Additionally, `spec.defaultPodSecurityAdmissionTemplateName` is set correctly to `rancher-privileged`.
8. Navigated to top-left menu > cluster > Workloads.
9. Created three deployments, `d1`, `d2`, `d3` with container image set to `nginx:latest`.
10. Restored the snapshot using option cluster configuration, etcd and Kubernetes version.
11. Once completed, validated cluster and nodes are `Active` and are at version v.124.
12. Viewed the cluster YAML and validated that I see the previous v1.24 cluster configuration, as expected.
_____
**Scenario 2**
1. Performed same steps as scenario 1, but used an RKE2 downstream node driver cluster instead.
     - Same successful results as seen in scenario 1.
______
**Scenario 3**
1. Performed same steps as scenario 1, but used an K3s downstream node driver cluster instead.
     - Same successful results as seen in scenario 1.
______
**Scenario 4**
1. Repeated scenario 1 steps 1-3, but on Rancher v2.7.1 and using RKE1 downstream node driver v1.23 cluster with no PSP or PSA configured.
2. Upgraded Rancher v2.7.1 -> v2.7-head; validated that the cluster and nodes did not auto-upgrade themselves.
3. Upgraded the K8s cluster to v1.24, still with no PSP or PSA configured; validated that this was successful and the cluster and nodes upgraded to v1.24 in Cluster Management and Cluster Explorer.
4. Repeated scenario 1 steps 3-12, but used `rancher-restricted` instead of `rancher-privileged` in step 5; validated that all of the steps were successful.
