### ISSUE TITLE
New Ports present in the launchConfig dont get allocated during service upgrade

### ISSUE THREAD

**Issue by prachidamle** [rancher/rancher#4043]
If a Service is upgraded and if new private ports are added in the upgraded without the associated public ports, then upgrade does not allocate random public ports to these new additional ports.

**Comment by prachidamle** [comment]
@alena1108 please reassign as needed when this bug is to be picked.

**Comment by alena1108** [comment]
We can fix it after GA, as it's not as common as another use case - where you upgrade w/o modifying the ports

**Comment by johnrengelman** [comment]
Just ran into this one as well. I currently can't find a way to assign a new random port to existing service. Have to delete and define the service

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
