### ISSUE TITLE
selection outline on Access control icons is off

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4046]
Version - master 3/18

Steps to Reproduce: 
1.  Go to Access Control screen
2.  Click on any of the icons

Results: There is a strange --- outline that is off of the icon (it's high and to the right)
![image](https://cloud.githubusercontent.com/assets/11514927/13893364/ee3f10fa-ed1a-11e5-8c0c-1ec2f55bbb49.png)

Expected: No dotted outline is needed since the the selection is highlighted and has a checkmark.

**Comment by lvuch** [comment]
resolve in https://github.com/rancher/ui/pull/549

**Comment by tfiduccia** [comment]
Version - master 3/18
Verified fixed
