### ISSUE TITLE
Add Docker 20.10.22, 20.10.23

### ISSUE THREAD

**Issue by vivek-shilimkar** [rancher/rancher#40469]
Upstream has released the following:
https://github.com/moby/moby/releases/tag/v20.10.22
https://github.com/moby/moby/releases/tag/v20.10.23

The same approach for implementation and testing as https://github.com/rancher/rancher/issues/39345

**Comment by vivek-infracloud** [comment]
Tested a docker install script v20.10.22 and v20.10.23 for following OSes as mentioned in the test plan.

1. ubuntu 20.04 - ami-0568936c8d2b91c4e
2. ubuntu 22.04 - ami-02f3416038bdb17fb
3. rocky 8.7 - ami-093fce7707cfd5839
4. centos 7.9 - ami-033adaf0b583374d4 (community), ami-0714d1cb45d276890 (private, without docker already installed)

Node driver cluster creation with 1cp, 1 etcd, and 1 wk nodes was successful with above mentioned docker versions.

**Comment by vivek-infracloud** [comment]
Tested the issue with https://releases.rancher.com/install-docker-dev/20.10.22.sh and https://releases.rancher.com/install-docker-dev/20.10.23.sh links. It installs correct docker versions and provisioned a cluster successfully.

However, the https://releases.rancher.com/install-docker-dev/20.10.sh link still installs the docker version v20.10.21.
Hence, reopening the issue. Once fixed will test again on one OS with https://releases.rancher.com/install-docker-dev/20.10.sh URL.

**Comment by snasovich** [comment]
Is there some problem with publishing? I see 20.10.sh points to 20.10.23.sh - https://github.com/rancher/install-docker/blob/c99bbbde05546cf044fcb32aecd3d6b93b2dc4a1/20.10.sh#L1
@kinarashah

**Comment by kinarashah** [comment]
@snasovich Based on the script we run and the documentation, looks like only the linking only works for the latest tag so it'll work for 23.0.x but not 21.10.x. I have pinged Seb on a few questions around this and will then fix it accordingly or respond with the conclusion here later.

**Comment by kinarashah** [comment]
Was a bit confused earlier, but the tag isn't connected to the publish links logic. 20.10.sh was in the wrong location. Looks like @mitulshah-suse already fixed it in his PR. We can move the issue to test after his PR is merged.

**Comment by vivek-infracloud** [comment]
Tested the Node driver cluster creation with docker install script https://releases.rancher.com/install-docker-dev/20.10.sh.

The expected docker version was installed on the node with above URL. Hence moving this issue to Release Task bucket.
This issue can be closed once the new docker versions are released.

**Comment by mitulshah-suse** [comment]
@kinarashah @sowmyav27 Assigning to you for further tracking until its released.

**Comment by kinarashah** [comment]
Docker versions are now released:

Tested the following URLs:

- [x] curl -L https://releases.rancher.com/install-docker/20.10.22.sh
- [x] curl -L https://releases.rancher.com/install-docker/20.10.23.sh

Confirmed the default URL points to the latest: 20.20.23

- [x]  curl -L https://releases.rancher.com/install-docker/20.10.sh

**Comment by vivek-shilimkar** [comment]
The docker scripts were tested and working as expected, hence closing this issue.
