### ISSUE TITLE
Increment major version for rancher/charts to indicate k8s 1.25 support in Rancher v2.7.2

### ISSUE THREAD

**Issue by prachidamle** [rancher/rancher#40464]
The major version of rancher/charts is tied to Rancher minor version from a supportability perspective. In Rancher 2.7.2, we are adding support to k8s 1.25 - to indicate explicit support of chart deployment in 1.25 clusters, we will need to increment the major version of rancher/charts from 101.x.y to 102.x.y; 

Even if there aren’t any chart changes actually made, the 102.x.y version is indicating that anything in that release line has been vetted for 1.25 support in 2.7.2 

Here is a list of charts that need to bump the major version from 101.x.y to 102.x.y to indicate the K8s 1.25 support in Rancher v2.7.2:

- fleet
- fleet-agent
- system-upgrade-controller
- sriov
- rancher-vsphere-cpi
- rancher-vsphere-csi
- rancher-gke-operator
- rancher-eks-operator
- rancher-aks-operator

Not updating the major versions for charts that do not follow the 101.x.y versioning.

**Comment by cbron** [comment]
@prachidamle webhook and csp-adapter are both versioned separately, not in 100's, could they be removed ? 
* https://github.com/rancher/charts/blob/dev-v2.7/packages/rancher-csp-adapter/package.yaml
* https://github.com/rancher/charts/blob/dev-v2.7/packages/rancher-webhook/package.yaml

**Comment by prachidamle** [comment]
updated @cbron 
Removed 
- rancher-csp-adapter
- rancher-webhook

**Comment by snasovich** [comment]
For the following charts:
- system-upgrade-controller
	- @HarrisonWAffel , could you please take care of this since you're working with SUC chart already?
- sriov
	- @thomasferrandiz, could you please take care of this one?
- rancher-vsphere-cpi
- rancher-vsphere-csi
	- @annablender , could you please handle 2 vSphere charts above?
- rancher-gke-operator
- rancher-eks-operator
- rancher-aks-operator
	- @pgonin, could your team please update these 3 hosted provider charts' versions?

**Comment by annablender** [comment]
vSphere charts CSI and CPI have been updated to track 1.25 support

**Comment by prachidamle** [comment]
@olblak Can we add in this change for Fleet charts - we need to bump the major version in rancher/charts for Fleet to 102.x.y instead of the current 101.x.y version

**Comment by kkaempf** [comment]
> @olblak Can we add in this change for Fleet charts - we need to bump the major version in rancher/charts for Fleet to 102.x.y instead of the current 101.x.y version

See https://github.com/rancher/rancher/pull/40600 - merged last week
