### ISSUE TITLE
Rename Rancher's builtin PSACTs

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#40478]
We would like to rename two builtin PSACTs to make it clear to users that those come from Rancher by prefixing them with "rancher":
```
restricted -> rancher-restricted
privileged -> rancher-privileged
```

**Comment by snasovich** [comment]
@jiaqiluo , with PRs merged, is this ready to test?

**Comment by jiaqiluo** [comment]
Yes, it is. 
Moving it to to-test now!

**Comment by jiaqiluo** [comment]
This issue can be validated in the latest 2.7-head. 

QA:
We need validate that names of the built-in PSACT has the `rancher-` prefix

**Comment by markusewalker** [comment]
Validated in `v2.7-head` https://github.com/rancher/rancher/commit/622511d8959c678ecc3f58edd68ac4a5e142f114 that this is addressed. See results below:

**ENVIRONMENT**
- Rancher install: Helm
- Rancher version: `v2.7-head` https://github.com/rancher/rancher/commit/622511d8959c678ecc3f58edd68ac4a5e142f114
- Browser: Chrome

**TEST RESULT**
|Scenario|Test Case|Result|
|---|---|---|
|1|As an admin user, validate that the built-in PSACT values are `rancher-privileged` and `rancher-restricted` in a fresh install of Rancher|:white_check_mark:|

**Scenario 1**
1. As an admin user, navigate to Cluster Management > Advanced > Pod Security Admissions.
2. Validated that `rancher-privileged` and `rancher-restricted` are the two built-n PSACT values in a fresh install of Rancher:
![image](https://user-images.githubusercontent.com/52591819/220729911-26c28355-c12d-4b60-81dd-28f5fb6a3d38.png)
