### ISSUE TITLE
[BUG] ClusterRoleTemplates should not inherit ProjectRoleTemplates

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#40498]
**Rancher Server Setup**

Rancher version: < 2.7

**What is the role of the user logged in?**
Admin
Describe the bug

When creating a CRTB, users can inherit other RoleTemplates. These RoleTemplates can currently either be RoleTemplates with the context of "cluster" or "project". Though when reconciliation happens of the CRTB, all inherited roles are assumed to have the same context of "cluster" even if the role is a PRTB role.

**To Reproduce**

Start a new rancher instance
Create a downstream cluster
Create a new Standard User
Create a new Cluster Role template Users & Authentication -> Roles -> Cluster tab
Have the new role named test-role inherit the project-owner RoleTemplate
Add the newly created user to the downstream cluster with the role of test-role
Login as the newly created user and see that you now have admin privileges in the cluster
e.g. (User can create new pods and delete nodes)
Result

The cluster role that inherits the project roles has granted the project-owner rules to the entire cluster.

**Expected Result**
Users should not be able to inherit role templates with the context of 'project' to a cluster role template and vice-versa.

![image](https://user-images.githubusercontent.com/95646164/218173920-25b17063-99b6-493b-88b1-843427004e76.png)

![image](https://user-images.githubusercontent.com/95646164/218173939-34a48be6-f709-4096-bf32-286637965557.png)

**Comment by jbilliau-rcd** [comment]
Do you guys realize your own built-in roles do this very thing? I have a support case opened for weeks about this very thing. Your cluster role "View All Projects" inherits a project role called "Kubernetes view" which apparently is empty, making this all the more confusing.

<img width="924" alt="image" src="https://user-images.githubusercontent.com/69006307/218899726-de73f5af-ac68-416c-b230-18d6beb58e58.png">

<img width="848" alt="image" src="https://user-images.githubusercontent.com/69006307/218899765-4787715f-4f08-4618-ad24-0c2c6015beec.png">

**Comment by KevinJoiner** [comment]
Yes, you are right there are some edge cases for Kubernetes built-in roles that will need to be accounted for during implementation.
