### ISSUE TITLE
If another user is logged in when I auth, stuck on waiting cow image

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4049]
Version - master 3/18

Steps to Reproduce: 
1.  Log into Rancher on two separate browsers
2.  In one of the browsers, enable auth using active Directory
3.  After it's logged in, in the other browser click on Catalog or another menu you are not currently in

Results: Goes to waiting cow image and gets stuck
![image](https://cloud.githubusercontent.com/assets/11514927/18568450/3a020446-7b52-11e6-8678-f391ddf089cb.png)

Expected: should go to log in page

Comment - All authentication types are doing this.  So should check github, azure, ldap & local as well.

**Comment by vincent99** [comment]
Is this still relevant?

**Comment by tfiduccia** [comment]
Still in 1.6 - will check 1.2.0 when auth is available.

**Comment by tfiduccia** [comment]
Version - 1.6 master 10/16
Verified fixed

Closing this, will worry about 2.0 when we have new code to support it.  Added to test cases
