### ISSUE TITLE
[BUG] Rancher Terraform Provider: Unable to remove pod_security_policy from projects

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#40494]
SURE-5795

Terraform Provider for SUSE Rancher 1.22.2

Removing psp seems easy, by just disabling the psp in the cluster config.

pod_security_policy = false 
And then remove the [pod_security_policy_template_id](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/project#pod_security_policy_template_id) of each project. However this does not work and leads to errors when making changes to the projects (e.g. increasing the storage limits):

  # rancher2_project.pr["demo"] will be updated in-place
  ~ resource "rancher2_project" "pr" {
        id                              = "c-xxx:p-xxx"
        name                            = "Demo"
      - pod_security_policy_template_id = "restricted" -> null
        # (6 unchanged attributes hidden)

        # (3 unchanged blocks hidden)
    }
This does not work and terraform apply fails

│ Error: Bad response statusCode [500]. Status [500 Internal Server Error]. 
    Body: [baseType=error, code=ServerError, message=error parse/validate 
     action body: podSecurityPolicyTemplateId=MissingRequired 422: ]
     from [https://rancher.intra/v3/projects/c-xxxx:p-xxxx?action=setpodsecuritypolicytemplate]

│
│   with rancher2_project.pr["demo"],
│   on projects_namespaces.tf line 14, in resource "rancher2_project" "pr":
│   14: resource "rancher2_project" "pr" 
Neither removing the whole attribute pod_security_policy_template_id nor setting it to null or "" works. So how can I disable the psp and remove associated psp from the projects.

Only disabling the pod_security_policy and not removing the psps of the projects, will lead to errors when changing projects (e.g. increasing storage limits).

Error: Bad response statusCode [422]. Status [422 Unprocessable Entity]. 
Body: [baseType=error, code=InvalidAction, 
message=cluster [c-xxxx] does not have Pod Security Policies enabled] 
from [https://rancher.intra/v3/projects/c-xxxx:p-xxxx?action=setpodsecuritypolicytemplat 
While it looks like while on existing projects the pod_security_policy_template_id cannot be removed, I however can create new projects where pod_security_policy_template_id = null. Hence the conclusion is

if psp is disabled, I can create projects where the pod_security_policy_template_id is not set
I can't remove the psp association of existing projects, cause setting pod_security_policy_template_id to null, gives me the error above
I still believe one should be able to remove the psp association of existing projects, it tend not to have any side-effects when it is not removed, but pod_security_policy = false is set

Workaround- 

I actually in the UI I can set the psp manually to "Cluster Default", after that I can use

pod_security_policy_template_id = null
And I will not get Error: Bad response statusCode [422]

**Comment by samjustus** [comment]
see https://github.com/rancher/terraform-provider-rancher2/issues/1006

**Comment by brudnak** [comment]
# ✅ PASSED

## Reproduction Environment


| Component                        | Version / Type                          |
| -------------------------------- | --------------------------------------- |
| Rancher version                  | v2.7.1                                  |
| Installation option              | Helm (high availability)                |
| RKE binary version used          | v1.4.0                                  |
| If Helm Chart k8s cluster        | v1.24.6                                 |
| Cert Details                     | Let's Encrypt / `nginx`                 |
| Docker version                   | 20.10.7, build f0df350                  |
| Helm version                     | v2.16.8-rancher2                        |
| Downstream cluster type          | RKE1 Linode                             |
| Downstream K8s version           | v1.24.9-rancher1-1                      |
| Authentication providers enabled | OpenLDAP                                |
| Logged in user role              | admin, standard user                    |
| Browser type                     | Microsoft Edge                          |
| Browser version                  | 110.0.1587.50 (Official build) (x86_64) |

## Reproduction steps

1. Log into Rancher as admin >>> setup OpenLDAP >>> logout >>> login as standard user
2. Create a downstream RKE1 Linode
3. Before creating set `Advanced Options` : `Pod Security Policy Support` to >>> `Enabled`
4. Default Pod Security Policy >>> `unrestricted`
5. Create the cluster
6. Run this `terraform` : https://github.com/brudnak/rancher-psp-tf
7. Navigate to the project it created and check via `View YAML` >>> ensure security policy is `foo`
8. After the `terraform` has run, edit the `main.tf`
   1. Change `pod_security_policy_template_id = "foo"` 
   2. to `pod_security_policy_template_id = null`
   3. Then re-run the terraform
9. Getting the following error


```txt
│ Error: Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [baseType=error, code=ServerError, message=error parse/validate action body: podSecurityPolicyTemplateId=MissingRequired 422: ] from [https://<REDACTED>c-n8cps:p-j9lhv?action=setpodsecuritypolicytemplate]
│ 
```

## Additional Info

## RESULTS

#### ✅ Expected

To be able to remove the `pod_security_policy_template_id` using Terraform

#### ❌ Actual

Was not able to remove the `pod_security_policy_template_id` using Terraform. Getting the error:

```txt
│ Error: Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [baseType=error, code=ServerError, message=error parse/validate action body: podSecurityPolicyTemplateId=MissingRequired 422: ] from [https://<REDACTED>c-n8cps:p-j9lhv?action=setpodsecuritypolicytemplate]
│ 
```

<hr>

## Validation Environment


| Component                        | Version / Type                                                                     |
| -------------------------------- | ---------------------------------------------------------------------------------- |
| Rancher version                  | v2.7-622511d8959c678ecc3f58edd68ac4a5e142f114-head                                 |
| Rancher commit link              | https://github.com/rancher/rancher/commit/622511d8959c678ecc3f58edd68ac4a5e142f114 |
| Installation option              | Helm (high availability)                                                           |
| RKE binary version used          | v1.4.0                                                                             |
| If Helm Chart k8s cluster        | v1.24.6                                                                            |
| Cert Details                     | Let's Encrypt / `nginx`                                                            |
| Docker version                   | 20.10.7, build f0df350                                                             |
| Dashboard                        | master a41b8631a                                                                   |
| Helm version                     | v2.16.8-rancher2                                                                   |
| Downstream cluster type          | RKE1 Linode                                                                        |
| Downstream K8s version           | v1.24.10-rancher3-1                                                                |
| Authentication providers enabled | OpenLDAP                                                                           |
| Logged in user role              | admin, standard user                                                               |
| Browser type                     | Microsoft Edge                                                                     |
| Browser version                  | 110.0.1587.50 (Official build) (x86_64)                                            |


## Validation steps

1. Log into Rancher as admin >>> setup OpenLDAP >>> logout >>> login as standard user
2. Create a downstream RKE1 Linode >>> k8s: `v1.24.10-rancher3-1`
3. Before creating set `Advanced Options` : `Pod Security Policy Support` to >>> `Enabled`
4. Default Pod Security Policy >>> `unrestricted`
5. Create the cluster
6. Run this `terraform` : https://github.com/brudnak/rancher-psp-tf
7. Navigate to the project it created and check via `View YAML` >>> ensure security policy is `foo`
8. After the `terraform` has run, edit the `main.tf`
   1. Change `pod_security_policy_template_id = "foo"` 
   2. to `pod_security_policy_template_id = null`
   3. Then re-run the terraform
9. No errors and `terraform apply` successfully runs and makes the changes
10. Navigate to the project it created and check via `View YAML` >>> ensure security policy is `''` (an empty string)

## Additional Info

## RESULTS

#### ✅ Expected

To be able to remove the `pod_security_policy_template_id` using Terraform

#### ✅ Actual

Was able to remove the `pod_security_policy_template_id` using Terraform

## 📋 QA Test Plan

<table>
    <tbody>
        <tr>
            <th>Scenario</th>
            <th>Steps</th>
            <th>Expected</th>
            <th>Actual & Pass/Fail</th>
        </tr>
        <tr>
            <td>Upgrade Rancher from 2.7.1 to 2.7-head then re-attempt the 2nd terraform apply<</td>
            <td>
                <ol>
                    <li>Start with the reproduction setup</li>
                    <li>After the failure upgrade rancher and try the terraform apply again</li>
                </ol>
            </td>
            <td>Expected: For the policy to be removed via terraform after upgrade</td>
            <td>Actual: The policy was successfully removed after running terraform after upgrade<br><br>Pass/Fail: ✅<code>PASS</code></td>
        </tr>
</table>
