### ISSUE TITLE
GlusterFS kubelet image issue

### ISSUE THREAD

**Issue by rayandas** [rancher/rancher#40508]
**Issue description:**
To make glusterfs work properly, we have a workaround in https://docs.ranchermanager.rancher.io/how-to-guides/advanced-user-guides/manage-clusters/create-kubernetes-persistent-storage/manage-persistent-storage/about-glusterfs-volumes

But it appears to be giving an error as required libraries missing inside the hyperkube image

**Business impact:**
Medium

**Troubleshooting steps:**
Mount the system-run binary to hyperkube image and execute the following command

/usr/bin/systemd-run --version

**Repro steps:**

Run the following command in any RKE cluster node
- docker run -v /usr/bin/systemd-run:/usr/bin/systemd-run --entrypoint /usr/bin/systemd-run rancher/hyperkube:v1.21.13-rancher1 --version

**Workaround:**
Is workararound available and implemented? yes
What is the workaround: Adding a volume with specific library works and it can be configured directly on kubelet by using extra_binds

-v /lib/systemd/libsystemd-shared-249.so:/lib/systemd/libsystemd-shared-249.so

**Actual behavior:**
systemd-run --version display the following error

/usr/bin/systemd-run: error while loading shared libraries: libsystemd-shared-249.so: cannot open shared object file: No such file or directory

**Expected behavior:**
systemd-run --version should be executed correctly and list the following result

systemd 249 (249.11-0ubuntu3)

+PAM +AUDIT +SELINUX +APPARMOR +IMA +SMACK +SECCOMP +GCRYPT +GNUTLS -OPENSSL +ACL +BLKID +CURL +ELFUTILS -FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP -LIBFDISK +PCRE2 -PWQUALITY -P11KIT -QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified

**Files, logs, traces:**

$ docker run -v /usr/bin/systemd-run:/usr/bin/systemd-run --entrypoint /usr/bin/systemd-run rancher/hyperkube:v1.21.13-rancher1 --version

/usr/bin/systemd-run: error while loading shared libraries: libsystemd-shared-249.so: cannot open shared object file: No such file or directory

SURE-5281

**Comment by vivek-infracloud** [comment]
Issue is not active anymore on newly bumped hyperkube images.

The issue is resolved in following hyperkube images.

- rancher/hyperkube:v1.25.6-rancher2
- rancher/hyperkube:v1.24.10-rancher2
- rancher/hyperkube:v1.23.16-rancher2
- rancher/hyperkube-base:v0.0.16

Closing the issue.

**Comment by snasovich** [comment]
This is waiting on https://github.com/rancher/kontainer-driver-metadata/pull/1089 before it can be tested for v2.7 on https://github.com/rancher/kontainer-driver-metadata/tree/dev-v2.7-for-2.6.11 branch.

**Comment by vivek-infracloud** [comment]
Issue is not active anymore on newly bumped hyperkube images.

Running below command lists the version successfully.
`docker run --entrypoint /usr/bin/systemd-run <IMAGE-TAG> --version`
The issue is resolved in following hyperkube images.

- rancher/hyperkube:v1.24.10-rancher2 and rancher/hyperkube:v1.24.10-rancher3
- rancher/hyperkube:v1.23.16-rancher2
- rancher/hyperkube-base:v0.0.16

Hence closing the issue.
