### ISSUE TITLE
Using latest metrics server image for kubernetes v1.24

### ISSUE THREAD

**Issue by vardhaman22** [rancher/rancher#40514]
metrics server image needs to be updated from v0.6.1 to v0.6.2 for new kubernetes v1.24 patch releases.
SURE-5661

**Comment by vardhaman22** [comment]
in metrics server 0.6.1 there was an issue regarding error when we update `--metric-resolution=15s` argument to `--metric-resolution=180s` which was fixed in 0.6.2 upstream issue: [1031](https://github.com/kubernetes-sigs/metrics-server/issues/1031) .
To test that the upstream issue is fixed:
1. create RKE1  K8s v1.24.10 downstream cluster with metrics server.
2. edit the metrics server deployment and replace `--metric-resolution=15s` argument to `--metric-resolution=180s`
3. check the logs of metrics server pod for the error described in the upstream issue, which should not be present in the logs.

the fix is added in 1.24.10 so this error can be reproduced on 1.24.9 (since metrics server version is 0.6.1)

**Comment by vivek-infracloud** [comment]
Tested the issue on rancher v2.7.2-rc2. The upstream issue mentioned here is not active on k8s v1.24.10.

Steps followed.
1. Created RKE1 K8s v1.24.10 downstream cluster with metrics server v0.6.2.
2. Edited the metrics server deployment and updated `--metric-resolution=15s` argument to `--metric-resolution=180s`.

After few minutes the old pod was deleted and new pod was running successfully. Hence, closing the issue.
![Screenshot from 2023-02-14 12-33-56](https://user-images.githubusercontent.com/83208989/218663439-a9ef18b4-a1b1-489b-abb5-1b3f16e54330.png)

**Comment by snasovich** [comment]
This is waiting on https://github.com/rancher/kontainer-driver-metadata/pull/1089 before it can be tested for v2.7 on https://github.com/rancher/kontainer-driver-metadata/tree/dev-v2.7-for-2.6.11 branch.

**Comment by vivek-infracloud** [comment]
Re-tested the issue on rancher v2.7.1 as [commented here](https://github.com/rancher/rancher/issues/40514#issuecomment-1429228811).

Provisioned a k8s cluster `v1.24.10-rancher3-1` and `v1.23.16-rancher2-1` by pointing a KDM to `dev-v2.7-for-2.6.11`.

metric server version installed on cluster was 0.6.2 as expected. Hence, closing the issue.
