### ISSUE TITLE
Rancher UI not running under apache http proxy

### ISSUE THREAD

**Issue by kk86bioinfo** [rancher/rancher#4052]
Rancher Version: Current latest

Docker Version: Docker version 1.10.3, build 20f81dd

OS: Ubuntu 14.04

Steps to Reproduce: 

- Install os-vagrant with vagrant up
- add apache subdomain proxy to 127.0.0.1:8080 (current set at http://rancheros1.inbiosis.org)

Results: 
Failed when vendor.js running vagrant machine IP instead of the proxy subdomain.

Expected:

http://172.19.8.101:8080/v1/environments?limit=1000 

Should be with proxy subdomain as below:

http://rancheros1.inbiosis.org/v1/environments?limit=1000

**Comment by kk86bioinfo** [comment]
Additional info:

When vagrant is up, vagrant ssh into the vm:

Rancher server is installed via the following command:

```
sudo docker run -d -e http_proxy=http://rancheros1.inbiosis.org:80 -e no_proxy="localhost,127.0.0.1" --restart=always -p 8080:8080 rancher/server
```

**Comment by vincent99** [comment]
You need Apache to send `X-Forwarded-Host` and `-Proto` headers or PROXY protocol preamble.  The API generates absolute URLs and needs to know where you're originally coming from.  Similar to SSL config, but without SSL: http://docs.rancher.com/rancher/installing-rancher/installing-server/basic-ssl-config/#apache-configuration

The `http_proxy` header is for something completely different, that is for if your network environment blocks direct access to the Internet and requires requests to it go through a proxy like Squid.

**Comment by kk86bioinfo** [comment]
It works now. :)
