### ISSUE TITLE
Support for docker defined networks

### ISSUE THREAD

**Issue by carlskii** [rancher/rancher#4053]
Rancher Version: v0.63.1

Docker Version: 

Client:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 20:39:58 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 20:39:58 2016
 OS/Arch:      linux/amd64

OS: RancherOS

Steps to Reproduce: 

Results: 

It seems that Rancher does not currently support docker defined networks. Is this going to change in future releases ? 

Expected:

**Comment by deniseschannon** [comment]
Please see this forum post on Rancher's stance on Docker networking. Specifically, @ibuildthecloud's comment

https://forums.rancher.com/t/roadmap-for-docker-1-10-compose-1-6/1643/2

**Comment by dbones** [comment]
is there any update on this one?

**Comment by bradjones1** [comment]
Thinking this can be closed in favor of https://github.com/rancher/rancher/issues/5715

**Comment by deniseschannon** [comment]
@bradjones1 This would be the change that needs to happen in Cattle and then #5715 would be the changes needed in rancher-compose to support the network items.

**Comment by Braintelligence** [comment]
Could someone please comment on the current state of this?
My current problem is that I have spun up nginx-proxy and letsencrypt-companion on their own external network but I can't specify it in the docker-compose.yml. (It just gets removed from the config as if I never entered it.)

Now if I understand correctly my only choice is to set everything to bridge mode. Or is there any other way? If so, please do point me towards it ☹️ .

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
