### ISSUE TITLE
[BUG] System Default Private Registry not being used to pull images

### ISSUE THREAD

**Issue by jakefhyde** [rancher/rancher#40546]
**Rancher Server Setup**
- Rancher version: v2.6.10

**Information about the Cluster**
- Kubernetes version:
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Custom

**Describe the bug**

The rancher/shell image for helm-operation Pods is pulled from Docker Hub not the system-default-registry (i.e. where the user has a registry without authentication, per https://ranchermanager.docs.rancher.com/v2.6/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/global-default-private-registry#setting-a-private-registry-with-no-credentials-as-the-default-registry) nor the cluster private registry (i.e. when a user has a registry with authentication, per https://ranchermanager.docs.rancher.com/v2.6/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/global-default-private-registry#setting-a-private-registry-with-no-credentials-as-the-default-registry). As a result users in an air-gapped environment are unable to perform chart installations/upgrades/deletions via Apps & Marketplace in Rancher v2.6.10.

This commit changed the way the private registry was determined for the cluster:
[rancher/rancher@`025cb5f`](https://github.com/rancher/rancher/commit/025cb5f6011775c1c0b184e06ddaf33019a7bdb1#diff-722dd3d67f8f907274951d7867e8e225f4f4fd865dd47b0a3f37162c8680abfbL81-R82)
instead using the one passed in, which is always nil here (when it should be the system default registry):
https://github.com/rancher/rancher/blob/2207cfed180315c015223c07ba4462888b8acf9f/pkg/systemtemplate/import.go#L140
https://github.com/rancher/rancher/blob/2207cfed180315c015223c07ba4462888b8acf9f/pkg/api/norman/customization/clusterregistrationtokens/import.go#L50

https://github.com/rancher/rancher/pull/40368 fixes all that by instead removing that registry parameter, and moving all extraction logic here: 
[rancher/rancher@`b27a701` (#40368)](https://github.com/rancher/rancher/pull/40368/commits/b27a701ed71cbb0ab2223e0805e3e56876a9a83f#diff-1e0003bf68600cff0241e8b7cc95d8428055c1e792c5b27e73e5ac9bfd8b9576R68)

Specifically [rancher/rancher@`b27a701` (#40368)](https://github.com/rancher/rancher/pull/40368/commits/b27a701ed71cbb0ab2223e0805e3e56876a9a83f#diff-1e0003bf68600cff0241e8b7cc95d8428055c1e792c5b27e73e5ac9bfd8b9576R87) will utilize the system default registry if one is not defined

**To Reproduce**

- Provision a Rancher v2.6.10 instance and a single all-role node custom RKE cluster
- Populate a Docker registry with the images for Rancher v2.6.10 (and v2.6.9 for regression testing)
- Set system-default-registry to the registry.
- Navigate to Apps & Marketplace and install the rancher-logging chart
- Observe the helm-operation Pod within the cattle-system Namespace created to run the helm install uses the rancher/shell image without a registry prefix, i.e. pulls from Docker Hub by default
- Set registry to private versus public access and repeat the test for downstream cluster with cluster private registry configured and observe same result.
- Repeat tests in Rancher v2.6.9 and observe rancher/shell image is pulled from custom registry as expected.

**Result**

Images are pulled from Docker Hub

**Expected Result**

Images should be pulled from registries

**Additional context**

This issue is believed to be solved based on validation during https://github.com/rancher/rancher/issues/40457 due to changes made during the related PRs, as well as solving merge conflicts per https://github.com/rancher/rancher/pull/40369 (specifically this changeset: [rancher/rancher@`aa2eb29` (#40369)](https://github.com/rancher/rancher/pull/40369/commits/aa2eb293645a41c439084ee44d709cbc928ea89f#diff-1e0003bf68600cff0241e8b7cc95d8428055c1e792c5b27e73e5ac9bfd8b9576R87)

SURE-5881

**Comment by markusewalker** [comment]
**QA TEST PLAN**

**Scenarios**
|Scenario|Test Case|
|---|---|
|1|Set the system default registry to use a non auth-enabled private registry, provision a custom RKE1 cluster, validate the rancher/shell image is pulled from private registry, install rancher-logging chart, add a worker node
|2|Setup Rancher `v2.6.9`, set the system default registry to use a non auth-enabled private registry, provision a custom RKE1 cluster, validate the rancher/shell image is pulled from private registry, install rancher-logging chart, upgrade Rancher, validate all images are still pulling from private registry, upgrade cluster K8s version, add a worker node

**Comment by markusewalker** [comment]
Reproduced scenario 1 from the mentioned [test plan](https://github.com/rancher/rancher/issues/40546#issuecomment-1431685478) `v2.6.9`. Please find results below:

**ENVIRONMENT**
- Rancher install: Docker
- Rancher version: `v2.6.10`
- Browser: Chrome

**TEST RESULT**
|Scenario|Test Case|Result|
|---|---|---|
|1|Set the system default registry to use a non auth-enabled private registry, provision a custom RKE1 cluster, validate the rancher/shell image is pulled from private registry, install rancher-logging chart, add a worker node|:x:|

**Scenario 1**
1. As an admin user, navigated to top-left menu > Global Settings > Settings.
2. Updated the system default registry to use a non auth-enabled private registry.
3. Logged out and logged back in as a standard user.
4. Provisioned a downstream RKE1 custom cluster (3 etcd, 2 cp, 3 worker); validated that the cluster and nodes came up as `Active` in Cluster Management and Cluster Explorer.
5. Navigated to Cluster Explorer > RKE1 cluster.
6. Navigated to Apps > Logging.
7. Installed the Logging chart and validated the chart was successfully deployed to the cluster with deployments and pods in a state of `Active`.
8. Noted that the rancher/shell is referencing a Docker image instead of my specified private registry:
![image](https://user-images.githubusercontent.com/52591819/219114536-a2bacd9a-c4e3-4209-a9c6-03196c2c42ba.png)

Now that this has been reproduced, I will attempt to run the original test plan and see if this has been addressed.

**Comment by markusewalker** [comment]
Validated that this has been addressed on `v2.6.11-rc6`. Please see details below:

**ENVIRONMENT DETAILS**
- Rancher install: Docker
- Rancher version:
     - Fresh install: `v2.6.11-rc6`
     - Upgrade: `v2.6.9` -> `v2.6.11-rc6`
- Browser: Chrome

**TEST RESULT**
|Scenario|Test Case|Result
|---|---|---|
|1|Set the system default registry to use a non auth-enabled private registry, provision a custom RKE1 cluster, validate the rancher/shell image is pulled from private registry, install rancher-logging chart, add a worker node|:white_check_mark:|
|2|Setup Rancher `v2.6.9`, set the system default registry to use a non auth-enabled private registry, provision a custom RKE1 cluster, validate the rancher/shell image is pulled from private registry, install rancher-logging chart, upgrade Rancher, validate all images are still pulling from private registry, upgrade cluster K8s version, add a worker node|:white_check_mark:|

**Scenario 1**
1. As an admin user, navigated to top-left menu > Global Settings > Settings.
2. Updated the system default registry to use a non auth-enabled private registry.
3. Logged out and logged back in as a standard user.
4. Provisioned a downstream RKE1 custom cluster (1 etcd, 1 cp, 1 worker); validated that the cluster and nodes came up as `Active` in Cluster Management and Cluster Explorer.
5. Navigated to Cluster Explorer > RKE1 cluster.
6. Navigated to Apps > Logging.
7. Installed the Logging chart and validated the chart was successfully deployed to the cluster with deployments and pods in a state of `Active`.
8. Validated that the rancher/shell is referencing the private registry and not Docker.
9. Navigated back to Cluster Management.
10. Added a worker node to the RKE1 custom cluster; validated that it came up as `Active` in Cluster Management and Cluster Explorer.
11. Repeated step 8 with the same successful results.
_______
**Scenario 2**
1. Repeated scenario 1 steps 1-8, but ensured that the provisioned downstream RKE1 custom cluster (3 etcd, 2 cp, 3 worker) uses the second-highest K8s version available.
     - Each step was successful as was seen in scenario 1.
2. Upgraded Rancher `v2.6.9` to `v2.6.11-rc6`.
3. Validated that the cluster and nodes did not auto-upgrade.
4. Navigated to Cluster Explorer > RKE1 cluster and validated that the `rancher/shell` image is still being pulled from the non auth-enabled private registry as expected.
     - Since this was an upgrade, there is the old `helm-operation` successful pod with the old `rancher/shell` image tag and the new `rancher/shell` with the new image tag.
5. Upgraded the cluster's K8s version to the highest available; validated that the upgrade was successful and the cluster and nodes remain as `Active`.
6. Repeated step 4 with the same successful results.
7. Added a worker node to the RKE1 custom cluster; validated that it came up as `Active` in Cluster Management and Cluster Explorer.
8. Repeated step 4 with the same successful results.
