### ISSUE TITLE
[BUG]when provisioning downstream clusters, the namespace ingress-nginx is not being created

### ISSUE THREAD

**Issue by ronhorton** [rancher/rancher#40547]
**Rancher Server Setup**
- Rancher version: `v2.6.11-rc5`
- Installation option (Docker install/Helm Chart): `Helm`
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): `RKE1`
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: `1.24`
- Cluster Type (Local/Downstream): `downstream ec2`
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: `admin`

**Describe the bug**

**To Reproduce**
provisioned downstream ec2 cluster
rke1
k8s v1.24.9
3 etc, 1 cp, 5 workers
installed rancher-monitoring

**Result**
Monitoring install fails with `Error: namespaces "ingress-nginx" not found`

**Expected Result**
Monitoring installs
as namespace created on downstream cluster

**Screenshots**

<img width="1667" alt="2023-02-14_14-09-45" src="https://user-images.githubusercontent.com/89212856/218834218-d82a9413-8516-4361-a7ec-f66c566466e8.png">

<img width="1724" alt="2023-02-14_14-10-06" src="https://user-images.githubusercontent.com/89212856/218834254-cbd93f0c-895e-4c5b-bb28-a7767a220571.png">

**Additional context**

**Comment by Josh-Diamond** [comment]
Reproduced on `v2.6.11-rc5` w/ downstream RKE1 EC2 Node driver - 3 nodes, individual roles + k8s `v1.24.9-rancher1-1`.

<img width="1326" alt="Screenshot 2023-02-14 at 1 13 05 PM" src="https://user-images.githubusercontent.com/46494969/218852143-c9ce4fe3-05a8-4e8b-8afc-0825d24bc06f.png">

**Comment by ronhorton** [comment]
RKE2 Clusters are not affected by this issue. It's RKE1 only.

**Comment by sowmyav27** [comment]
On `2.6.11-rc7`, dpeloyed an RKE1 cluster using default k8s version - `v1.24.10`,  nginx-ingress namespace is created and `rancher/nginx-ingress-controller:nginx-1.5.1-rancher2` is deployed
