### ISSUE TITLE
[BUG] Creating/deleting management resources cause resources to be unsubscribed

### ISSUE THREAD

**Issue by richard-cox** [rancher/rancher#40558]
**Rancher Server Setup**
- Rancher version: v2.7-head (`1dd2af2`)
- Installation option (Docker install/Helm Chart):
   - docker install
   - docker run -d --restart=unless-stopped --privileged -e CATTLE_PASSWORD_MIN_LENGTH=8 --name $container --network host rancher/rancher:v2.7-head --acme-domain <snip>

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - Admin

**Describe the bug**
- In the UI we subscribe over socket for updates to resources
- There are three socket endpoints 
  - steve management / `v1/subscribe`
  - steve cluster `k8s/clusters/local/v1/subscribe`
  - norman / `v3/subscribe`
- This issue only applies to steve management, and not steve cluster or norman.
- When a resource that is subscribed to is created or deleted, all/most resource subscriptions in the socket will get `resource.stop` message (sometimes preceded by `resource.error`) aka is unsubscribed. The UI then re-subscribes.
- If there is enough churn of created/deleted resources then resource subscriptions die and are reborn a lot
- This causes missed resource updates resulting in stale information on screen. This _could_ be the root cause of https://github.com/rancher/dashboard/issues/7819 and https://github.com/rancher/dashboard/issues/7815

I can't quite tie down the pattern of which resources cause the `resource.stop` messages, there's some findings below

**To Reproduce**
- Open browser 1 and navigate to the Dashboards `Cluster Management` page
- Open browser 1's Dev Tools --> Network tab --> WS Tab --> select v1/subscription --> Messages tab
- Open browser 2 and navigate to the Dashboards `Cluster Management` page
- In browser 2 --> `Import Existing` --> `Generic` --> enter anything for the `Name` --> `Create`

**Result**
- In browser 1's dev tools there will be multiple `resource.error` and `resource.stop` messages

**Expected Result**
- No `resource.stop` message - aka resource subscriptions aren't dropped

**Screenshots**

**Additional context**
##### Specific resource messages
![image](https://user-images.githubusercontent.com/18697775/219060580-bbe017ad-4a91-4207-8357-1449851b8e97.png)

Create - `resource.error` and `resource.stop`
Edit - Neither
Delete - `resource.error` and `resource.stop`

resource.error data 
```
"event watch error: an error on the server (\"unable to decode an event from the watch stream: http2: response body closed\") has prevented the request from succeeding"
```
##### All messages
![image](https://user-images.githubusercontent.com/18697775/219061613-7b18a7d1-9433-43eb-92bc-4ddae9c1ffa6.png)

#### management.cattle.io.settings
Create / Edit did not cause `resource.stop` or `resource.error`

#### provisioning.cattle.io.cluster
Create - `resource.stop` but not `resource.error`
Delete - `resource.stop` and `resource.error`

resource.error data 1 (many)
```
notifier watch error: clusters.provisioning.cattle.io \"asdsad\" not found: clusters.provisioning.cattle.io \"asdsad\" not found
```
resource.error data 2 (one)
```
event watch error: an error on the server (\"unable to decode an event from the watch stream: http2: response body closed\") has prevented the request from succeeding
```

#### namespace (via `local` cluster explorer)
Create / Edit / Delete in both v1 and k8s/clusters/local/v1/subscribe show correct events, no resource.stop or resource.error

#### management.cattle.io.project (via `local` cluster explorer)

Create - `resource.error` and `resource.stop`
Edit - Neither
Delete - `resource.error` and `resource.stop`

resource.error data 1 
```
notifier watch error: projects.management.cattle.io \"p-mrqlr\" not found: projects.management.cattle.io \"p-mrqlr\" not found
```
resource.error data 2 
```
event watch error: an error on the server (\"unable to decode an event from the watch stream: http2: response body closed\") has prevented the request from succeeding
```

**Comment by gaktive** [comment]
For 2.7.2, UI will do a client-side workaround. @MbolotSuse to link to an existing issue to help with buffering results to the UI.

**Comment by MbolotSuse** [comment]
Backend Issue for Watch buffering: #39568

**Comment by richard-cox** [comment]
Just tracking results. 

I've validated the same behaviour for fleet workspaces happens in 2.7.0 (as mentioned in the call)

![image](https://user-images.githubusercontent.com/18697775/219624831-7b62aec3-9148-4fda-9538-a98abac89b20.png)

**Comment by torchiaf** [comment]
## Three nodes, 1 pool
As per https://github.com/rancher/dashboard/issues/7819

### Create Cluster
resource.stop/start cycles: todo
cluster state: updated ok
nodes states: 1 node summary graph did not update

Driver: `Digital Ocean`
Machine Count: `3`
Kubernetes version: `v1.23.15+rke2r1`

![image](https://user-images.githubusercontent.com/26394656/220134181-715a521d-aae3-4bf4-8101-ef5bba2d946a.png)

**Comment by richard-cox** [comment]
Think I've come up with three reasonable improvements for 2.7.2 for the three issues issues listed in https://github.com/rancher/rancher/issues/40558#issuecomment-1434462942 (see https://github.com/rancher/dashboard/pull/8224).

As there's no decent reproduction steps anywhere it might take some playing to see if the improvements do resolve all issues.

In terms of this specific issue though, as the functionality has been the same for a number of releases (including going back to 2.6) and we have something proposed to fix the linked issues, i'm going to close this.

If the improvements still require more work, we may need to look into a joint fix

1) Reducing the need for the frontend to re-subscribe given `resource.stop` events (30 minute refresh of kube socket, frequent permissions changes, etc)
2) Reducing the impact of the re-subscribe. Could see issues with possibly stale local revision (though this won't cause spam), scale of fetching everything again, etc

Something concrete that would be grand is to smother the two resource.error messages that are harmless/to be expected (`unable to decode an event..` & `notifier watch error: clusters.provisioning.cattle.io \"asdsad\" not found..` more details above). Those appear a lot in logs.

**Comment by boltdog2022** [comment]
hi，after happen this issue, is there anyway to recover?

**Comment by richard-cox** [comment]
> hi，after happen this issue, is there anyway to recover?
> 

@boltdog2022 The user just needs to refresh their browser. That will get the latest resource info and subscribe to changes from that revision.

**Comment by boltdog2022** [comment]
> > hi，after happen this issue, is there anyway to recover?
> 
> @boltdog2022 The user just needs to refresh their browser. That will get the latest resource info and subscribe to changes from that revision.

Thanks, by the way, can you have a look at my issue? I don't know how it happens and how to resolve it. 
https://github.com/rancher/rancher/issues/41748
