### ISSUE TITLE
Null Pointer Exception in the logs and agent keeps disconnecting

### ISSUE THREAD

**Issue by sacheendra** [rancher/rancher#4055]
Rancher Version: v0.59.1

Docker Version: 1.9.1

OS: CoreOS 899.11.0

Steps to Reproduce: Added some hosts using the add custom host method and started a stack on them. After some time the hosts disconnect. 

Results: The disconnect is due to the agent being unable to connect the host and stopping. 

Expected: The host be able to connect to the server and keep running. 

The logs on the server showing the timeframe. Time at which the stack was deployed and time of error can be seen in this. https://gist.github.com/sacheendra/bb2e67b074d1ca343046

The full log for the error can be seen in this. https://gist.github.com/sacheendra/e5fae8d0627ba0e02d70

The log of the agent on the host. https://gist.github.com/sacheendra/d9660739603b2bfac46a

**Comment by deniseschannon** [comment]
Where and how are you creating your hosts?

**Comment by sacheendra** [comment]
The hosts are created on AWS using Terraform. 

Here is the cloud-init passed to the hosts. https://gist.github.com/sacheendra/923c8d88ad56ede71cd8

Thank you for looking into this.

**Comment by ibuildthecloud** [comment]
@sacheendra your service for rancher needs to be type oneshot.  The container you launch will immediately die and create the actual rancher-agent container.

**Comment by sacheendra** [comment]
@ibuildthecloud Can you explain that again? So, if i deploy a service in rancher, it will stop the rancher-agent container and start another one?

**Comment by deniseschannon** [comment]
When we launch rancher/agent, we actually launch 3 containers. The first container launched immediately is stopped and a rancher-agent-state container is launched (and also stopped) and then finally the rancher/agent container is launched and remains running.

**Comment by deniseschannon** [comment]
@sacheendra If you have further questions, please re-open or open a new issue.
