### ISSUE TITLE
[BUG] Monitoring Prometheus images are not using the global system registry setting

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#40567]
**Rancher Server Setup**
- Rancher version:
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.23.15 / v1.24.9
- Cluster Type (Local/Downstream): downstream 
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): custom, tested with both rke1 and rke2

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: standard user, cluster owner

**Describe the bug**

when deploying monitoring in an airgap setup, there are some images that do not properly use the system-default-registry.

**To Reproduce**

* deploy rancher with system-default-registry set (a registry using no authentication method)
* deploy a downstream cluster large enough to install monitoring (registry details should automatically use the system default registry)
* deploy monitoring on the downstream cluster

**Result**
* prometheus images are not all using the system-default-registry

**Expected Result**

* all images should be using the system-default-registry

**Screenshots**

<img width="960" alt="prometheus" src="https://user-images.githubusercontent.com/16691014/219172097-8edc7733-1650-43a0-a3ea-35a62dfe7992.PNG">
**Additional context**

* tried with default monitoring settings, as well as manually setting the `system-default-registry` value in the monitoring chart yaml, but neither resulted in a successful deployment.

**Comment by AndrewHoffmanQA** [comment]
![image](https://user-images.githubusercontent.com/89030218/219790863-a2ffd683-2b02-4c56-89d8-e60f636d24d3.png)
this is fixed in Rc7

retest passed

followed repro steps, monitoring was successfully installed. setting to closed.
