### ISSUE TITLE
[BUG] intermittent Errimagepull issue with fleet in an airgap setup for RKE1 downstream clusters

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#40568]
**Rancher Server Setup**
- Rancher version: v2.6.11-rc6
- Installation option (Docker install/Helm Chart): helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): rke1
- Proxy/Cert Details: valid signed certs

**Information about the Cluster**
- Kubernetes version: v1.23.15-rancher1-1
- Cluster Type (Local/Downstream):downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): custom

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: standard user, cluster owner

**Describe the bug**

When provisioning an rke1 cluster in an airgap setup, sometimes there is an issue pulling the fleet image. <registry>/rancher/fleet-agent:v0.5.2-rc.3

**To Reproduce**

* deploy rancher in an airgap environment using system-default-registry (uses a registry without authentication enabled)
* deploy an rke1 downstream cluster on v1.23.15-rancher1-1 using a 2nd, authenticated private registry + at least 1etcd, 1cp, 2 worker nodes
* wait for all resources to come to an active state

**Result**
the fleet image `<registry>/rancher/fleet-agent:v0.5.2-rc.3` was not able to pull on v1.23.15. However I had no issues on another cluster in the same environment when using v1.24.9-rancher1-1

**Expected Result**

fleet image should be able to pull in an airgapped setup

**Screenshots**

**Additional context**

It is unclear if this is related to the k8s version or some underlying fleet issue.

**Comment by sowmyav27** [comment]
Wasn't able to reproduce this consistently. Closing this out
