### ISSUE TITLE
Admin access lost

### ISSUE THREAD

**Issue by blu35ky** [rancher/rancher#4056]
We have recently lost a team member who is an admin in both production (site without 8080) and other environments (site with 8080). Our access control is via github and he has been removed from it. He has also returned his laptop days earlier than expected and we had no handover/knowledge transfer. 

There is no issue with the non-production environment as I have been made admin. But with the production, unfortunately, we realised it late and no one else has admin access to it. 

How can we have the same admin setting in 8080 site and the production site? It is a blocker at the moment as we cannot troubleshoot some of the services not displaying logs (no access to admin tab).

The account is setup under the organisation I am a member of. 

Many thanks.
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v0.63.0` Cattle: `v0.155.0` UI: `v0.94.0` |
|Access|`github` `admin`|
|Route|`authenticated.project.help`|

**Comment by vincent99** [comment]
You'll have to change it in the database if there's no admins left..

  - Go to the host that the `rancher/server` container is on
  - Run `docker ps` to get the container ID for it
  - Run `docker exec -it THE_CONTAINER_ID mysql cattle` to bring up the mysql CLI
  - `SELECT * FROM account;` to list the accounts, identify the ID of you (or whoever you want to be admin)
  - `UPDATE account SET kind='admin' WHERE id=THAT_ID;`

**Comment by blu35ky** [comment]
Thank you @vincent99 :+1: Will give this a go.

**Comment by blu35ky** [comment]
I'm getting `ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)` for the `mysql cattle` command.

**Comment by vincent99** [comment]
If your database is setup externally somewhere, you'll need to connect to that instead.

**Comment by blu35ky** [comment]
You're right, found out that the db is setup in RDS. Gained admin access back :) Cheers @vincent99

**Comment by 2416ryan** [comment]
Has this process changed since March 2016?  Running rancher v2.1.6 and I don't see a rancher/server container.  Accidentally hosed the admin account while testing changes.

**Comment by vincent99** [comment]
1.x and 2.x are almost entirely unrelated.  https://rancher.com/docs/rancher/v2.x/en/faq/technical/#how-can-i-reset-the-admin-password
