### ISSUE TITLE
[BUG] upgrading Monitoring from  100.1.3+up19.0.3 to 100.2.0+up40.1.2 results in alert webhooks failing to send

### ISSUE THREAD

**Issue by AndrewHoffmanQA** [rancher/rancher#40566]
**Rancher Server Setup**
- Rancher version: v2.6.11-rc5
reproduced on downstream clusters RKE1, RKE2. 

**Describe the bug**
perquisite- User sets up and configures alerting and monitoring and creates a working webhook alert 100.1.3+up19.0.3 to 100.2.0+up40.1.2  the alert stops working and throws this error

`ts=2023-02-15T20:23:04.406Z caller=dispatch.go:354 level=error component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="default/amc-7/prom2sms/webhook[0]: notify retry canceled due to unrecoverable error after 1 attempts: unexpected status code 400: http://rancher-alerting-drivers-sachet.cattle-monitoring-system.svc:9876/alert"`

when the user upgrades monitoring 
**To Reproduce**
1. install alerting 100.0.4 (also reproduced on 100.0.3)
2. install monitoring 100.1.3+up19.0.3
3. configure A webhook alert to fire.  Please reach out to @AndrewHoffmanQA or @ronhorton for confluence documentation
4. confirm alerts are being sent through your webhook
5. upgrade monitoring to 100.2.0+up40.1.2 

**Result**
alerts stop sending and the error documented above is thrown within the logs

**Expected Result**
alerts function as they did before upgrade 

**Screenshots**

**Additional context**

**Comment by MKlimuszka** [comment]
This is not a bug. This is a migration to a new minor version determined upstream to prevent collisions in different namespaces. We will put details in release notes.

**Comment by geethub97** [comment]
Upstream PR/Release Notes: 

https://github.com/prometheus-operator/prometheus-operator/commit/80a72c42f5c62012d27330b7c5203fd110d7f764
https://github.com/prometheus-operator/prometheus-operator/pull/4626

Related Ticket: https://github.com/rancher/rancher/issues/40358
