### ISSUE TITLE
[DOCS] Add documentation around PSP -> PSS upgrades and management

### ISSUE THREAD

**Issue by crobby** [rancher/rancher#40575]
https://github.com/rancher/rancher-docs needs to have documentation about how to upgrade from PSP to PSS as well as how to manage Pod Security Admission Configuration Templates.

**Comment by sowmyav27** [comment]
Reopening for QA Test Template

**Comment by crobby** [comment]
PR: https://github.com/rancher/rancher-docs/pull/423
  
# Problem
PSPs are not supported in k8s 1.25, so we need to educate users on how to update to use the new solution PSS/PSA
  
# Solution
I believe there have been more than one PR to document this, so I'll point to the current version of the PSP page in the 2.7.2 docs.
https://github.com/rancher/rancher-docs/blob/release/v2.7.2/docs/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/pod-security-standards.md
  
# Testing

 
## Engineering Testing
### Manual Testing
I've created and ran many clusters, both local and downstream, utilizing different PSS configurations with different namespace exemptions. 
Tested the management of PSACTs by following the guide at https://github.com/rancher/rancher-docs/blob/release/v2.7.2/docs/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/pod-security-standards.md#pod-security-admission-configuration-templates

 
### Automated Testing
Unit testing of the functionality in the rancher source exists, but this is a docs issue, so there is no further automated testing for this specific issue
 
## QA Testing Considerations
Make sure that expected users are able to Create and manage PSS configurations that are in addition to the 2 included by default.  Ensure that those new configurations are usable by new clusters.
  
### Regressions Considerations
Nothing I can think of.  For the purposes of this doc change, PSS is a new feature.

**Comment by anupama2501** [comment]
Verified on v2.7-head `a841a9e`

- Created a custom psact template
- Created an rke1 and rke2 clusters with the custom template and verified the clusters were active

- Created an rke2 cluster with PSP enabled on v1.24
- Once the cluster is active, deleted the PSPs from the cluster from Pod Security Policies tab
- Upgraded the cluster to v1.25 
- Selected the PSACT profile - `rancher-restricted` and cis-profile `1.23`
- Cluster comes back up active.
- Created a workload and the workload fails to come up active
