### ISSUE TITLE
Creating a new Kubernetes environment doesn't work if Rancher is running as HTTPS

### ISSUE THREAD

**Issue by jonjo-manywho** [rancher/rancher#4058]
Rancher Version: 0.63.1

Docker Version: None, yet

OS: Ubuntu 15.10, RancherOS 0.42, CoreOS 835.13.0 (as hosts)

Steps to Reproduce: Have Rancher running under HTTPS, then try to create a new Kubernetes environment from scratch (we were using the EC2 host provisioner, but I think it's non-specific)

Results: The host is created and contactable, but 3 containers never start (controller-manager, rancher-kubernetes-agent, scheduler) and in the logs they give the error **x509: failed to load system roots and no roots provided** (or a variation of "can't load roots")

Expected: All the Kubernetes containers to start successfully, working with Rancher using HTTPS

**Comment by imesh** [comment]
AFAIU Rancher and K8S serve the same purpose (container cluster management). Any particular reason to use both in the same environment?
Thanks

**Comment by jonjo-manywho** [comment]
@imesh the latest release of Rancher (0.63.1) now supports orchestration using Kubernetes, along with the existing Cattle framework ([see here](http://rancher.com/rancher-now-supports-kubernetes/)) - we were trying it out with a separate, fresh environment in Rancher but to no avail :cry:

**Comment by ibuildthecloud** [comment]
It appears we are missing the SSL ca roots in the images.  I'll take a look at this.

**Comment by ibuildthecloud** [comment]
I've updated all the k8s images to include the proper SSL roots as part of the sync up to k8s 1.2.0 official release. https://github.com/rancher/cattle/pull/1544

**Comment by deniseschannon** [comment]
@jonjo-manywho @imesh Would either of you be willing to try out v1.0.0-rc1 to test K8s on https?

**Comment by jonjo-manywho** [comment]
@deniseschannon sure! Is there anything special that needs be done to do so?

**Comment by deniseschannon** [comment]
If you could try a fresh install of v1.0.0-rc1 with what you originally tried to do, that'd be great. We haven't started doing upgrade testing from v0.63.1 to v1.0.0 yet. 

In the rc1, you should be able to start a new k8s environment.

**Comment by deniseschannon** [comment]
This is addressed in v1.0.0-rcX releases. If you have stil lhave issues with one of those releases, please re-open.

**Comment by imesh** [comment]
@jonjo-manywho Thanks for the response! 
@deniseschannon Yes I would like to give it a try, do we have a Vagrant or something similar to setup Rancher?

**Comment by deniseschannon** [comment]
@imesh No, we don't have a Vagrant file anymore as we weren't able to keep up with it and the changes occuring in Rancher. 

Here are some docs on how to get started with Rancher:

http://docs.rancher.com/rancher/installing-rancher/installing-server/

**Comment by imesh** [comment]
Thanks @deniseschannon!! I will try the docker image with the instruction given. Thanks!
