### ISSUE TITLE
Not able to resolve sidekick service name.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#4060]
Rancher Version: Build from master - Mar20

Steps to reproduce the problem:
Create a service - "testnow" with side kick service - "sk1".
From containers of service testnow , try to ping sk1.

Ping fails to resolve sk1 and we get "unknow host sk1"

<img width="844" alt="screen shot 2016-03-20 at 5 21 05 pm" src="https://cloud.githubusercontent.com/assets/4266958/13908489/832f4576-eec0-11e5-897e-3dd9490dfe5a.png">

**Comment by michaellopez** [comment]
I was hitting this today, glad to see it resolved.

**Comment by sangeethah** [comment]
Tested with rancher-server version -v1.0.0-rc1

Steps to reproduce the problem:
Create a service - "testnow" with side kick service - "sk1".
From containers of service testnow , try to ping sk1.
sk1 resolves to ipaddress of containers in sk1 and ping succeeds.
