### ISSUE TITLE
[cli] Cannot list or update apps in a specific namespace

### ISSUE THREAD

**Issue by vfouqueron** [rancher/rancher#40621]
Hello,

I've tried to used Rancher CLI to update an app. However, when I execute `rancher apps ls`, there is nothing returned despite the fact that I have a bunch of apps installed in different namespaces on the current project. I have only found a namespace attribute when using `rancher apps install` but no attributes on `rancher apps ls` or `rancher apps update`

Am I missing something ? Without that, the CLI is unusable for app management

**Comment by mobilutz** [comment]
I am also still seeing this issue.

I wish I had the time to look into this and add a pull-request, but I don't 😦

**Comment by nandlalushir** [comment]
Any update on this topic, it is still relevant !!!
