### ISSUE TITLE
rancher-agent fails to find Rancher Server on both same host and separate host on same network.

### ISSUE THREAD

**Issue by DMJ743** [rancher/rancher#40636]
When attempting to start a Rancher host Docker instance using the Rancher Server interface, the instance fails to find the server. On startup it prints:

`INFO: Running Agent Registration Process, CATTLE_URL=http://gimli:8080/v1`
`INFO: Attempting to connect to: http://gimli:8080/v1`
`INFO: http://gimli:8080/v1 is accessible`
`INFO: Configured Host Registration URL info: CATTLE_URL=http://gimli:8080/v1 `
`ENV_URL=http://gimli:8080/v1`
`INFO: Inspecting host capabilities`
`INFO: Boot2Docker: false`
`INFO: Host writable: true`
`INFO: Token: xxxxxxxx`
`INFO: Running registration`
`INFO: Printing Environment`
`INFO: ENV: CATTLE_ACCESS_KEY=F082A6F3FDAA821D0FF3`
`INFO: ENV: CATTLE_AGENT_IP=192.168.1.9`
`INFO: ENV: CATTLE_HOME=/var/lib/cattle`
`INFO: ENV: CATTLE_REGISTRATION_ACCESS_KEY=registrationToken`
`INFO: ENV: CATTLE_REGISTRATION_SECRET_KEY=xxxxxxx`
`INFO: ENV: CATTLE_SECRET_KEY=xxxxxxx`
`INFO: ENV: CATTLE_URL=http://gimli:8080/v1`
`INFO: ENV: DETECTED_CATTLE_AGENT_IP=192.168.1.9`
`INFO: ENV: RANCHER_AGENT_IMAGE=rancher/agent:v1.2.11`
`INFO: Launched Rancher Agent: d96817454e034df26f6b83c5882515e3bc361ac585bd19dd51ca8cfdba4d3317`

But the host never appeared in the server interface. `docker logs rancher-agent` revealed the following:

`
time="2023-02-22T03:26:28Z" level=fatal msg="Failed to find container id:\n0::/\n"
`

I've run the container on both the same host as the Rancher Server and on a separate host, and received the same error.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.30` Cattle: `v0.183.83` UI: `v1.6.52` |
|Access|`Disabled`|
|Orchestration|`Cattle`|
|Route|`admin-tab.settings`|

**Comment by bwcxyk** [comment]
```
echo 'GRUB_CMDLINE_LINUX=systemd.unified_cgroup_hierarchy=false' > /etc/default/grub.d/cgroup.cfg
update-grub
```
https://stackoverflow.com/questions/68176138/rancher-agent-fails-with-failed-to-find-container-id-n0-n
