### ISSUE TITLE
[BUG] Harvester node driver stuck in creating (2 NICs) nodes with error: flags provided: missing section: network

### ISSUE THREAD

**Issue by futuretea** [rancher/rancher#40633]
**Rancher Server Setup**
- Rancher version: v2.7-head/ v2.6-head
- Installation option (Docker install/Helm Chart): Docker install
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: 
- Cluster Type (Local/Downstream): Harvester Provider
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:
admin

This is a Harvester node driver bug
Refer to https://github.com/harvester/harvester/issues/3443

**Comment by lanfon72** [comment]
close as the issue been verified on Rancher Version: **v2.7-7c60dc0856e19c278d520946d4d2e7ea2b86d70f-head** and **v2.6-657d8ec456f572efb4503d3499f2eedff0edab96-head** (Docker Image: **cf565c7e2276** and **964540586c5c**)

more details in https://github.com/harvester/harvester/issues/3443#issuecomment-1441271227
