### ISSUE TITLE
[BUG] CIS scan 5.3.2 fails on rke1 custom hardened cluster

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#40648]
**Rancher Server Setup**
- Rancher version: v2.7.1
- Installation option (Docker install/Helm Chart): helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): rke2, v1.24.9+rke2r1
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.24.9-rancher1-1
- Cluster Type (Local/Downstream): downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): custom, hardened

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: standard user, cluster owner

**Describe the bug**

when running the CIS scan on an rke1 hardened cluster, the 5.3.2 test is failing

**To Reproduce**

* provision an rke1 custom cluster
 * on each node and throughout the cluster creation process, follow the [guide on hardening your cluster](https://docs.ranchermanager.rancher.io/v2.6/reference-guides/rancher-security/rancher-v2.6-hardening-guides/rke1-self-assessment-guide-with-cis-v1.6-benchmark)
 * once the hardening process is complete, install CIS chart (tested v3.0.0) and run the `rke1-1.23-restricted` scan

**Result**

scan fails with the following message:
```
Ensure that all Namespaces have Network Policies defined (Automated)
Remediation: Follow the documentation and create NetworkPolicy objects as you need them.

```
**Expected Result**

a hardened cluster should pass restrictive CIS scans

**Screenshots**

**Additional context**

There is the same issue on a local hardened rke1 cluster

**Comment by rishabhmsra** [comment]
Validated on rancher v2.7.1 HA setup, with local cluster as RKE2 v1.24.9+rke2r1

- Provisioned downstream RKE1 v1.24.9-rancher1-1 hardened cluster(1-cp, 1-e, 1-w)
- Added dev-v2.7 charts repo under Apps -> Repositories
- Installed CIS benchmark chart version `4.0.0-rc3`. While installing set `global.psp.enabled: true`
- Ran rke-profile-hardened-1.23 and rke-profile-permissive-1.23. Both passed successfully.

Result :
- Scans passed successfully, hence closing the issue.

![scans](https://user-images.githubusercontent.com/36376154/222082937-1698493a-017b-481a-b04e-3ca1cd683d25.png)

![pass](https://user-images.githubusercontent.com/36376154/222083338-2785ff57-ab6e-4666-8e87-4e6d2307c04e.png)
