### ISSUE TITLE
[BUG] status report is incorrect when upgrading an rke1 cluster to 1.25+ with existing PSPs

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#40652]
**Rancher Server Setup**
- Rancher version: v2.7.2-rc3
- Installation option (Docker install/Helm Chart): helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): rke2, v1.24.9+rke2r1
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.24.9-rancher1-1 -> v1.25.6-rancher2-1
- Cluster Type (Local/Downstream): downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):  custom, hardened rke1 cluster

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: standard user, cluster owner

**Describe the bug**

when upgrading k8s that has existing PSPs on an rke1 custom cluster from 1.24.x -> 1.25.x, the cluster reports an error in provisioning, however the status stays as `upgrading`.  

**To Reproduce**

* provision an rke1 custom cluster with PSPs enabled (the cluster [I used was hardened](https://docs.ranchermanager.rancher.io/v2.6/reference-guides/rancher-security/rancher-v2.6-hardening-guides/rke1-self-assessment-guide-with-cis-v1.6-benchmark)) 
  * ensure there is a PSP enabled, and the k8s version is 1.24 or below
* wait for the cluster to provision and ensure the PSP was applied to the cluster
* upgrade the cluster to 1.25
  * you will receive a warning and ultimately be blocked from upgrading since PSPs are depreciated in 1.25.  Select the `disabled` option for PSPs under the `advanced` section, and continue with the upgrade
<img width="987" alt="Screen Shot 2023-02-22 at 1 32 50 PM" src="https://user-images.githubusercontent.com/16691014/220764127-aa17810c-4945-43f4-bf16-67a186817ff2.png">

* observe if the cluster upgrades 

  * **(FAILURE 1)** - cluster gets stuck with an error message, but the cluster status stays in `upgrading` state instead of `error` state (you can double check that in the cluster -> provisioning log tab, there is no progress for the upgrade)

<img width="1050" alt="Screen Shot 2023-02-22 at 1 33 05 PM" src="https://user-images.githubusercontent.com/16691014/220764174-20ec3c5c-ce70-4e5b-9fa9-057a46922d19.png">

* go to your cluster, and remove all PSPs
* go back to cluster management, edit your cluster, and change a non-important variable to trigger another upgrade
* **Failure 2** - cluster immediately goes to an `error` state after triggering the upgrade, though the upgrade is actually continuing (you can double check the status in the cluster -> provisioning log tab, there is indeed progress in the upgrade)
* eventually, after removing the PSPs manually from the cluster, the `upgrading` status returns, and further after that, the upgrade succeeds. 

**Result**
cluster upgrade eventually succeeds, but messages to user are misleading / confusing. 

**Expected Result**

status of cluster should be clear

**Screenshots**

**Additional context**

This was found when upgrading a hardened cluster with PSPs disabled, but PSPs still existing on a cluster.

**Comment by snasovich** [comment]
Moving to Blocked while we're discussing the desired behavior or RKE1 clusters with existing PSPs on upgrade to k8s 1.25. cc: @leflambeur

**Comment by jiaqiluo** [comment]
This issue will be gone because we decide to drop the check for PSP resources in the RKE cluster when upgrading the cluster to 1.25.

**Comment by jiaqiluo** [comment]
Can be validated in the latest v2.7-head

**Comment by slickwarren** [comment]
tested on v2.7-head (23074b5)
* disabling PSPs in an rke1 cluster with existing PSPs does not cause an error when upgrading -- pass
