### ISSUE TITLE
Logging v2 does not work in CSI profile enabled RKE2 cluster

### ISSUE THREAD

**Issue by sanjay920** [rancher/rancher#40654]
### Issue description:
rancher-logging does not work with RKE2 hardened clusters, with the fluentd container of the rancher-logging-root-fluentd-0 Pod failing with an error of the format: `container has runAsNonRoot and image has non-numeric user (fluent), cannot verify user is non-root (pod: "rancher-logging-root-fluentd-0_cattle-logging-system(a92ab19c-c24c-456e-bba2-70c2b6536bb2)", container: fluentd)`
Some related discussion in https://github.com/rancher/rancher/issues/34387 but my lab was using Ubuntu, so no SELinux issues

### Business impact:
The user is currently unable to configure log forwarding in their hardened RKE2 cluster

### Repro steps:
Install Rancher v2.6.5 and configure a single all role node RKE2 custom cluster (I used github.com/superseb/tf-do-rancher2) with v1.23.7+rke2r2 and set:     machineSelectorConfig:
    - config:
        profile: cis-1.6
        protect-kernel-defaults: true
Install rancher-logging:100.1.2+up3.17.4
Observe the fluentd container of the rancher-logging-root-fluentd-0 Pod fails with an error of the format: `container has runAsNonRoot and image has non-numeric user (fluent), cannot verify user is non-root (pod: "rancher-logging-root-fluentd-0_cattle-logging-system(a92ab19c-c24c-456e-bba2-70c2b6536bb2)", container: fluentd)`
Upgrade rancher-logging and add following loggingOverlay spec:
  spec:
    fluentd:
      fluentOutLogrotate:
        enabled: true
        path: /buffers/fluentd.log 
      security:
        podSecurityContext:
          runAsUser: 100 
Delete the failing rancher-logging-root-fluentd-0 Pod and observe newly scheduled instance runs successfully without the non-numeric user warning

### Workaround:
Is workaround available and implemented? Yes according to my testing
What is the workaround: The addition of loggingOverlay spec to fix uid and logs

### Actual behavior:
rancher-logging does not work with RKE2 hardened clusters

### Expected behavior:
rancher-logging works out-of-the-box with RKE2 hardened clusters

**Comment by sanjay920** [comment]
Resolved with https://github.com/rancher/charts/pull/2365

**Comment by nickwsuse** [comment]
`Verified on v2.7-head ID: 4a9b7ba`

I set up a downstream hardened RKE2 cluster, single node with all roles as specified in the ticket, and was able to successfully install Logging `v102.0.0+up3.17.10` with no errors.
