### ISSUE TITLE
rancher-logging kube-audit pods should only run on CP nodes

### ISSUE THREAD

**Issue by sanjay920** [rancher/rancher#40655]
### Issue description:
rancher-logging 101.0.0+up3.17.7
If you enable kubeAudit logging in the rancher-logging app, the rancher-logging-kube-audit-fluentd DaemonSet pods should only run on CP nodes.

### Business impact:
Why the ds would run on nodes without the audit logs? It consumes resources that are not needed on worker nodes.

### Repro steps:
* on cluster with a mix of master nodes and worker only nodes install rancher-logging 101.0.0+up3.17.7
* check which nodes the rancher-logging-kube-audit-fluentd pods run on

### Actual behavior:
kube-audit pods runs on all node roles

### Expected behavior:
kube-audit pods run only on CP nodes

**Comment by sanjay920** [comment]
https://github.com/rancher/charts/pull/2365 resolves this

**Comment by nickwsuse** [comment]
@sanjay920 I'm seeing two of the pods still running on worker nodes, but admittedly I'm not very familiar with logging/kubeAudit so I don't know if this is expected or if this issue should be reopened.

![image](https://user-images.githubusercontent.com/107147272/229598046-a0a68ad2-16a4-4a98-850e-412ae4cbcd9e.png)

**Comment by prachidamle** [comment]
Seems only one of the workloads (fluentbit) got the node selector instead of all of them as suggested should happen in the comments.

**Comment by dbason** [comment]
This is the intended behaviour.  The fluentbit pods are responsible for collecting the kube audit logs and so should only run on controlplane nodes.  These logs are then aggregated to fluentd which is responsible for shipping to the logging store.  Fluentd runs as a statefulset not as a daemonset and due to its role it is appropriate for it to run on worker nodes.

**Comment by ronhorton** [comment]
**Pass** verified in rancher `v2.7-head commit ID 95edd02`
1. installed rancher-logging:102.0.0+up3.17.10
2. enabled fluentd kube audit
3. verified rancher-logging-kube-audit-fluentbit only running on cp node
