### ISSUE TITLE
Do not remove self added "A" entries which does not have atleast 1 "." in name section in the format <name>.<env>.<domain-name>

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#4066]
Rancher Version: build from mater - mar20 and "Route53 DNS" version- v0.3.0-rancher1.

Environment name - "default"
Router53 Domain name - "sangee-test.com"

Manually add an "A" entry with name - testme2.default.sangee-test.com.

This entry gets deleted by rancher-server when route53 rules gets programmed.

Since the format for entries programed by rancher-server's "Route53 DNS" requires stack.service format , we can prevent removing entries that donot have any "." in this section of the name.

**Comment by vincent99** [comment]
I would really like this much better if we specifically remembered which records we have created (in metadata attributes if the provider supports it, or as a special TXT record if it doesn't) so that we're only removing things we explicitly know we created.

**Comment by janeczku** [comment]
https://github.com/rancher/external-dns/pull/47

**Comment by janeczku** [comment]
To validate:

1. Deploy Route 53 v.0.6.0 from rancher/rancher-catalog:qa
2. Manually create a DNS A record under the domain using the AWS console
3. Make sure that the record is not removed by the Route 53 service

**Comment by galal-hussein** [comment]
Tested on master image (24 Oct), The manually created record did not get removed by the route53 service.
