### ISSUE TITLE
Unsupported Kubernetes minor version 

### ISSUE THREAD

**Issue by VesperDev** [rancher/rancher#40673]
**Rancher Server Setup**
- Rancher version: 2.7.1
- Installation option (Docker install/Helm Chart): Helm Chart

**Information about the Cluster**
- Kubernetes version: 1.24
* Hosted = EKS

**User Information**
Admin/Cluster

**Describe the bug**

A cluster was created from rancher in version 1.23 but later from the AWS console I updated to version 1.24, rancher automatically detected that change, but when the update finished. I always get the following error

Controller.FailureMessage{ClusterName:"bruno-dev", Message_:"Unsupported Kubernetes minor version update from 1.24 to 1.23", NodegroupName:""}

![image](https://user-images.githubusercontent.com/14016458/221049922-62fd8fa0-67c8-43d7-a09d-b921148575cb.png)

I see the cluster operating fine from the EKS and rancher

![image](https://user-images.githubusercontent.com/14016458/221050097-83e83117-a687-4093-9d39-41b76030e572.png)

**Comment by HenriqueG123** [comment]
I have the same problem and it seems that no one knows how to solve it, investigating I could see that it is a bug in the recognition of cluster modifications via the AWS console, in one of the scenarios created here I received the following information:
, Message_:"Unsupported Kubernetes minor version update from 1.24 to 1.21", NodegroupName:""}

inside the aws console is kubernete version 1.24 and nodes 1.24,
I'm looking for a way to just remove the message given that the cluster's behavior is ok.

**Comment by HenriqueG123** [comment]
Solution on card https://github.com/rancher/rancher/issues/41643

**Comment by VesperDev** [comment]
yes, the new version of Rancher fixed that
