### ISSUE TITLE
[BUG] Unsupported TLS protocol error after upgrading Rancher

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#40671]
**Rancher Server Setup**
- Rancher version: 2.6.10

**Describe the bug**
After upgrading Rancher to version 2.6.9 or higher, the following error is seen after logging into the Rancher UI:

ldap error Error creating ssl connection: LDAP Result Code 200 "Network Error": tls: server selected unsupported protocol version 301
This problem happens when the LDAP server used for authentication with Rancher uses a version of TLS lower than 1.2. Rancher 2.6.9 uses Go 1.19 where the crypto/tls library that is used requires a minimum version of TLS 1.2 for LDAP connections.

Customer would still like Rancher to offer a way to continue working with their LDAP server if they are using TLS 1.0

**Result**
Unsupported protocol error when logging into Rancher

**Expected Result**
Have a way to still support TLS 1.0 and login without an error

**Comment by samjustus** [comment]
release note in 2.7.2 and update 2.7.0 as well

**Comment by MbolotSuse** [comment]
## Validation Template

## Root Cause

Rancher version 2.6.10 was built using go1.19. Starting with Go 1.18, as noted in the [release notes](https://tip.golang.org/doc/go1.18), go defaults to rejecting connections which use TLS 1.0. This caused rancher to no longer be able to connect with LDAP servers using TLS 1.0.

## What was fixed, or what change have occurred

The minimum TLS version for LDAP connections was manually pinned to TLS 1.0. 

## Areas or cases that should be tested

- Group/user search with an ldap server running TLS 1.0 (start tls and tls)
- Group/user search with an ldap server running TLS 1.2 (start tls and tls)
- Group/user search with an ldap server over http
- Login with an ldap server running TLS 1.0 (start tls and tls)
- Login with an ldap server running TLS 1.2 (start tls and tls)
- Login with an ldap server over http

## What areas could experience regressions

LDAP connection functionality, particularly with regards to tls

## Are the repro steps accurate/minimal?

Yes. They are included here for convienience.
1. Create an LDAP server using TLS 1.0
2. Attempt to connect the server to rancher. Note that rancher will not login users or perform search.

**Comment by anupama2501** [comment]
Reproduced the issue on v2.6.10 and on an upgrade from v2.6.6 >> 2.6.10
1. Created a rancher server on v2.6.6 docker install
2. Enabled freeIPA with tls version 1.0
3. Logged in as a standard user and created 2 downstream cluster node drivers - rke1 and rke2
4. Upgraded rancher server to 2.6.10
5. logged out as the standard user and tried logging in 
6. Unable to login with the console error 
```
xhr.js:178          POST https://<rancherIP>/v3-public/freeIpaProviders/freeipa?action=login net::ERR_CERT_AUTHORITY_INVALID
docker logs:
023/02/24 23:24:54 [ERROR] error syncing 'u-pbc2htc4ld': handler mgmt-auth-userattributes-controller: Error creating ssl connection: LDAP Result Code 200 "Network Error": 
```
7. Created a rancher server on v2.6.10
8. Enabled freeIPA auth provider and see the error:
```
Error creating ssl connection: LDAP Result Code 200 "Network Error": remote error: tls: protocol version not supported
```

**Comment by pjbgf** [comment]
The official Go documentation states that:
```
	// By default, TLS 1.2 is currently used as the minimum when acting as a
	// client, and TLS 1.0 when acting as a server. TLS 1.0 is the minimum
	// supported by this package, both as a client and as a server.
	//
	// The client-side default can temporarily be reverted to TLS 1.0 by
	// including the value "x509sha1=1" in the GODEBUG environment variable.
	// Note that this option will be removed in Go 1.19 (but it will still be
	// possible to set this field to VersionTLS10 explicitly).
```

The user should be able to bypass this by adding the environment variable `GODEBUG=x509sha1=1` to their Rancher container.

@anupama2501 would you mind testing this please?

**Comment by MbolotSuse** [comment]
@pjbgf that only applies for go version 1.18.  As stated in the paragraph that you quoted, this was removed in  go 1.19. You can also see this in the official [go release notes for 1.19](https://tip.golang.org/doc/go1.19). I don't believe that we ever built a version of rancher with go 1.18, so I don't believe that this test would be very helpful.

**Comment by MbolotSuse** [comment]
@pjbgf No problem, I think the comment is confusing (e.x. -the [release notes for 1.18](https://tip.golang.org/doc/go1.18) indicate a different var for this purpose `GODEBUG=tls10default=1`) - if we had a way to do this through an env var though I would prefer that option.

**Comment by pjbgf** [comment]
The source of the confusion was that the comment mentions `x509sha1=1`, which was also supposed to be removed from the codebase on 1.19, but in the end was left in and it still is there: https://github.com/golang/go/issues/41682#issuecomment-1102490055: 
>  The removal of the x509sha1=1 GODEBUG switch has been moved back. SHA-1 certificates are not secure, and applications still relying on them should migrate ASAP and not rely on the ongoing presence of the GODEBUG opt-in.

**Comment by anupama2501** [comment]
Verified on v2.6-head `8f2f506`

Test1:
1. Created a rancher server on v2.6-head docker install
2. Enabled freeIPA with tls version 1.0
3. Logged in as a standard user and created 2 downstream cluster node drivers - rke1 and rke2
4. logged out as the standard user and tried logging in
5. Login was successful
6. Verified user search and group search were successful.

Test2:
Repeated the same steps for start tls and verified no errors were seen. 
Verified user search and group search were successful.

Test3:
1. Created a rancher server on v2.6-head docker install
2. Enabled freeIPA with tls version 1.2
3. Logged in as a standard user and created 2 downstream cluster node drivers - rke1 and rke2
4. logged out as the standard user and tried logging in
5. Login was successful
7. Verified user search and group search were successful.


Test4:
Repeated test3 steps for starttls and verified login was successful
Verified user search and group search were successful.

Test5:

1. Installed rancher on v2.6.5
2. Enabled freeipa with tls 1.0  --> Successful
3. Upgraded rancher server to v2.6.10 
4. Unable to login via free IPA
5. Upgraded rancher to v2.6-head
6. Verified login was successful
7. Verified user search and group search were successful.

Test6:
repeated the same steps as above for starttls.

Test7:
After steps 7 in test5, updated the tls version on freeIPA to tls1.2
Logged out from rancher UI and re logged in as a standard user and a group user
Verified the login was successful
Verified the group search/user search were successful.
