### ISSUE TITLE
[BUG] Project Owner is forbidden to create endpoints

### ISSUE THREAD

**Issue by harridu** [rancher/rancher#40677]
**Rancher Server Setup**
- Rancher version: 2.7.1
- Installation option (Docker install/Helm Chart): Helm chart, RKE2

**Information about the Cluster**
- Kubernetes version: K3s v1.24.9+k3s2
- Cluster Type (Local/Downstream): local

**User Information**
- What is the role of the user logged in?  Project Owner

**Describe the bug**
A Project Owner is not allowed to create endpoints. Sample:
```
% vcluster create vcluster-hdu
info   Create vcluster vcluster-hdu...
info   execute command: helm upgrade vcluster-hdu /var/folders/7t/6d31st453rs107jjhvmkpvgcz8smc7/T/vcluster-0.14.0.tgz-2876634524 --kubeconfig /var/folders/7t/6d31st453rs107jjhvmkpvgcz8smc7/T/1438773474 --namespace sampleteam --install --repository-config='' --values /var/folders/7t/6d31st453rs107jjhvmkpvgcz8smc7/T/2904900695 --values values.yaml
fatal  error executing helm upgrade vcluster-hdu /var/folders/7t/6d31st453rs107jjhvmkpvgcz8smc7/T/vcluster-0.14.0.tgz-2876634524 --kubeconfig /var/folders/7t/6d31st453rs107jjhvmkpvgcz8smc7/T/1438773474 --namespace sampleteam --install --repository-config='' --values /var/folders/7t/6d31st453rs107jjhvmkpvgcz8smc7/T/2904900695 --values values.yaml: Release "vcluster-hdu" does not exist. Installing it now.
Error: roles.rbac.authorization.k8s.io "vcluster-hdu" is forbidden: user "u-4wzq7rucpg" (groups=["freeipa_group://cn=develop,cn=groups,cn=accounts,dc=example,dc=de" "freeipa_group://cn=users,cn=groups,cn=accounts,dc=example,dc=de" "system:authenticated" "system:cattle:authenticated"]) is attempting to grant RBAC permissions not currently held:
{APIGroups:[""], Resources:["endpoints"], Verbs:["create" "delete" "patch" "update"]}

% kubectl auth can-i create svc
yes
% kubectl auth can-i create endpoints
no 
```

**Expected Result**
The comment to Project Owner role says "Owners have full control over the Project and all resources inside it." An endpoint is bound to a namespace, so the Project Owner should be allowed to create it.

**Comment by harridu** [comment]
I have found

- https://github.com/kubernetes/kubernetes/issues/103675
- https://kubernetes.io/docs/reference/access-authn-authz/rbac/#write-access-for-endpoints

**Comment by govindkg** [comment]
I am also getting same error, Project owner cannot create endpoint 

Kubernetes version 1.23.x 
Rancher Version 2.6.6.

Do we have any workaround on this
