### ISSUE TITLE
[BUG] `rancher-webhook` and `rancher/shell` are not using the system default registry images in downstream clusters, instead they are using Docker images

### ISSUE THREAD

**Issue by markusewalker** [rancher/rancher#40685]
**Rancher Server Setup**
- Rancher version: `v2.7.2-rc4`
- Installation option (Docker install/Helm Chart): Docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version:
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Linode

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Standard
  - If custom, define the set of permissions:

**Describe the bug**

As part of https://github.com/rancher/rancher/commit/c3c9a13b277f8c0eaa3e3ab32ba4fae59155af9d, there was a change introduced to always install the webhook in the local and downstream clusters.

This change itself is expected behavior. The issue here is that when validating https://github.com/rancher/rancher/issues/40550, the webhook and subsequent helm-operation pod always install, but is referencing the default Docker image and not the expected system default registry image.

When testing in `v2.6-head`, this behavior is not seen, so this appears to be exclusive to `v2.7` and most likely due to PSA work. The webhook should not always be installed into local and downstream clusters, this is causing the above mentioned issue and potentially others.

**To Reproduce**

1. As an admin user, modify the system default registry to use a non auth-enabled private registry.
2. Log out and login to Rancher as a standard user.
3. Navigate to Cluster Management > Create.
4. Provision a downstream RKE1 node driver cluster.
5. Validate that the cluster and nodes come up `Active` in Cluster Management and Cluster Explorer.
6. Navigate to top-left menu > cluster > Workloads > Pods.
7. You should see the webhook and `rancher/shell` using the default Docker image and not the expected system default registry image.

**Result**
The webhook and `rancher/shell` are using the default Docker image and not the private registry image.

**Expected Result**

The webhook and `rancher/shell` should use the private registry image and not the default Docker image.

**Comment by snasovich** [comment]
Adding `release-blocker` since it's a blocker to another release blocker https://github.com/rancher/rancher/issues/40550.

**Comment by MbolotSuse** [comment]
@markusewalker Can you provide more information on the issue? The webhook being installed in the downstream is a requirement for the 2.7.2 release, not a bug. I do agree that the system default registry should be used, but this seems to be related to #40550 and I'm unclear how this functionality blocks #40550.

**Comment by cbron** [comment]
Does this affect 2.6 ? I would imagine so, and we haven't hit it yet. It's important we know that for upcoming dates.

**Comment by markusewalker** [comment]
@MbolotSuse thanks for clarifying that the webhook being installed in a downstream is a requirement and not a bug. To clarify, are you stating that when a user is using a system default registry, it is expected behavior for them to see two webhook images? One using the default Docker image and one using the private registry image set as the system default registry?

Because that is the current behavior being showcased and I am not sure if that is necessarily expected? I would expect that there would be only one webhook and that image is using the system default registry image, not Docker.

**Comment by MbolotSuse** [comment]
> To clarify, are you stating that when a user is using a system default registry, it is expected behavior for them to see two webhook images? One using the default Docker image and one using the private registry image set as the system default registry?

No, that part is not expected. We would expect it to always use the private registry image. I'm also unclear what you mean by "two webhooks" - the webhook is controlled by a chart/deployment. Even if there are conflicting install commands I would only expect to see at most one at any given moment.

**Comment by MbolotSuse** [comment]
@cbron @markusewalker can confirm, but I don't believe that webhook is active in downstream at the moment for 2.6 (for reference, here's some relevant [2.6 code](https://github.com/rancher/rancher/blob/a1abea50e0f47a5e38a77c72bbab77556805c870/pkg/controllers/dashboard/systemcharts/controller.go#L37)).

From what I have seen, this issue is due to us attempting to use the system default registry even in remote, where it is not set, so this would appear to only apply to the downstream webhooks at the moment.

**Comment by markusewalker** [comment]
That is correct, this is specifically a 2.7 issue. @cbron I am working with @MbolotSuse offline and providing him with an environment for him to further look into this issue.

Since it will take a few hours for the private registry to populate, this will take some time as an FYI.

**Comment by markusewalker** [comment]
Originally, I had tested with `v2.7.2-rc3` where I saw multiple webhooks and `rancher/shell` images; one with Docker image and one with the private registry.

Setting up a `v2.7.2-rc4`, I only see one webhook and one `rancher/shell`, however, they both show incorrectly as the Docker image and not the private registry. Handed environment over to Michael for further investigation.

**Comment by MbolotSuse** [comment]
@markusewalker I used the [PR comment](https://github.com/rancher/rancher/pull/40726#issue-1603879931) as a sort of a validation template. If you need any extra information, please let me know.

**Comment by markusewalker** [comment]
This issue needs a Rancher RC before QA can test.

**Comment by samjustus** [comment]
pushing back to-test with rc4

**Comment by jiaqiluo** [comment]
Can be validated in v2.7.2-rc5

**Comment by Josh-Diamond** [comment]
Ticket #40685 - Test Results - ✅ 

Verified with HA Helm on rancher `v2.7.2-rc5`

| Scenario | Test Case | Result |
|---|---|---|
| 1. | Downstream RKE1 | ✅ |
| 2. | Downstream RKE2 | ✅ |
| 3. | Downstream K3s | ✅ |

---

Scenario 1 -
1. Fresh install of rancher `v2.7.2-rc5`
2. As admin, navigate to `Global Settings` and configure the system default registry to point to an unauthenticated private registry
3. As admin, create a standard user
4. As standard user, provision a downstream RKE1 cluster
5. Once `active`, navigate to `Cluster Explorer > Workloads > Pods > All Namespaces` and verify all images are pulled from globally configured private registry
6. Verified - all images successfully and accurately pulled from globally configured private registry

---

Scenario 2 -
1. Fresh install of rancher `v2.7.2-rc5`
2. As admin, navigate to `Global Settings` and configure the system default registry to point to an unauthenticated private registry
3. As admin, create a standard user
4. As standard user, provision a downstream RKE2 cluster
5. Once `active`, navigate to `Cluster Explorer > Workloads > Pods > All Namespaces` and verify all images are pulled from globally configured private registry
6. Verified - all images successfully and accurately pulled from globally configured private registry

---

Scenario 3 -
1. Fresh install of rancher `v2.7.2-rc5`
2. As admin, navigate to `Global Settings` and configure the system default registry to point to an unauthenticated private registry
3. As admin, create a standard user
4. As standard user, provision a downstream K3s cluster
5. Once `active`, navigate to `Cluster Explorer > Workloads > Pods > All Namespaces` and verify all images are pulled from globally configured private registry
6. Verified - all images successfully and accurately pulled from globally configured private registry
