### ISSUE TITLE
[v2.7.2] Add v1.24.10-rancher4-1 and v1.25.6-rancher4-1

### ISSUE THREAD

**Issue by kinarashah** [rancher/rancher#40688]
Same issue and testing steps as https://github.com/rancher/rancher/issues/40668 but for v2.7.2. 

KDM branch: `dev-v2.7`
RKE version: `v1.4.4-rcX`

**Comment by kinarashah** [comment]
https://github.com/rancher/kubernetes/releases/tag/v1.25.6 
https://github.com/rancher/hyperkube/releases/tag/v1.25.6-rancher4

**Comment by kinarashah** [comment]
https://github.com/rancher/kubernetes/releases/tag/v1.24.10
https://github.com/rancher/hyperkube/releases/tag/v1.24.10-rancher4

**Comment by kinarashah** [comment]
Available to test with Rancher `v2.7-head` and RKE `v1.4.4-rc2`

**Comment by vivek-infracloud** [comment]
**Validated on rancher v2.7.2-rc4, KDM pointing to dev-v2.7**

- Provisioned RKE1 v1.24.10-rancher4-1, v1.25.6-rancher4-1 k8s cluster(1-cp, 1-e, 1-w). 
- Cluster came Active with all the pods up and running
- Validated node version as mentioned in the test template [here](https://github.com/rancher/rancher/issues/40668#issuecomment-1442358078).

**Result :** 
- Node versions are correct, hence closing the issue.
