### ISSUE TITLE
[BUG] Change workspace in Continuous Delivery does not work

### ISSUE THREAD

**Issue by reylejano** [rancher/rancher#40708]
**Rancher Server Setup**
- Rancher version: 2.7.1
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): Helm install on RKE2 v1.24.7+rke2r1 
- Proxy/Cert Details: no proxy, let's encrypt

**Information about the Cluster**
- Kubernetes version: RKE2 v1.24.7+rke2r1 
- Cluster Type (Local/Downstream): local and downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):
 * Infrastructure Provider = AWS

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - Admin/Cluster Owner

**Describe the bug**
I can not move a cluster in Continuous Delivery from the fleet-default workspace to a new workspace

**To Reproduce**
Go to Continuous Delivery, go to Advanced then Workspaces
Create a new Workspace
Then go to Clusters in Continuous Delivery
From the triple dot menu on the right, select Change Workspace
Select the new workspace and select Apply

**Result**
The cluster stays in the fleet-default workspace

**Expected Result**
The cluster should move to the new fleet workspace, in my example the cluster should move to fleet-new

**Screenshots**
![image](https://user-images.githubusercontent.com/52760880/221683026-c54ce81c-ac81-4f9a-8b51-33aa40fa9607.png)

After trying to move a cluster to the new workspace, the new workspace remains empty
![image](https://user-images.githubusercontent.com/52760880/221683443-7addbaa0-c0aa-40ad-a3ce-870c476358d7.png)

**Additional context**

**Comment by mattfarina** [comment]
I believe this is a duplicate of https://github.com/rancher/rancher/issues/36132. It has more detail and context on it.

**Comment by reylejano** [comment]
Closing in favor of https://github.com/rancher/rancher/issues/36132
