### ISSUE TITLE
[BUG] Fleet-Agent bundle errors out depending on Cluster Name

### ISSUE THREAD

**Issue by jameson-mcghee** [rancher/rancher#40709]
**Rancher Server Setup**
- Rancher version: `v2.6-head` (Commit ID: 9b65d8b)
- Installation option (Docker install/Helm Chart): Docker and Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1
- Proxy/Cert Details: N/A

**Information about the Cluster**
- Kubernetes version: v1.24.10+rke2r1
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Infrastructure Provider

**Fleet Information:**
- `fleet-agent` Deployment Image Version of Local Cluster: `rancher/fleet-agent:v0.5.2`
- `fleet-controller` Deployment Image Version of Local Cluster: `rancher/fleet:v0.5.2`
- `fleet-agent-local` Chart Version: `fleet-agent-local:0.0.0+s-f8b2a90`
- `fleet` Chart Version: `fleet:100.2.2+up0.5.2`
- `fleet-crd` Chart Version: `fleet-crd:100.2.2+up0.5.2`

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Cluster Owner or Admin
  - If custom, define the set of permissions: N/A

**Describe the bug**
Depending on the length of the name for a given RKE2/k3s cluster, the fleet-agent bundle can throw an error:
`release name "fleet-agent-loremipsumdolorsitametconsectetueradipiscinge-adc0c": invalid release name, must match regex ^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$ and the length must not be longer than 53`

This occurs because fleet requires that a release name not be more than 53 characters. Rancher was shortening the name of the fleet-agent bundle to at most 63 characters, ten over the limit. This error results in the controller not being deployed properly.

**To Reproduce**
1. Spin up a Rancher cluster
2. Create a downstream cluster with the a cluster name that has 63 characters (e.g. loremipsumdolorsitametconsectetueradipiscingelitaeneancomc71c13)
3. Open the _Kubectl Shell_ for the local cluster and execute the command: `k get bundles.fleet.cattle.io -A`
4. Locate the bundle with the format `fleet-agent-<CLUSTER_NAME>-xxxxx`, and then execute the following command: `k get bundles.fleet.cattle.io fleet-agent-<CLUSTER_NAME>-xxxxx -n fleet-default -o yaml`

**Result**
Note that the message field will state "_release name "fleet-agent-loremipsumdolorsitametconsectetueradipiscinge-af6c2": invalid release name, must match regex ^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$ and the length must not be longer than 53_"

**Expected Result**
The bundle does not show an error, and the pod deploys properly.

**Screenshots**
![image](https://user-images.githubusercontent.com/13294321/221695110-bbba3789-e9f2-438e-b0f8-6abc0b3db906.png)
![image](https://user-images.githubusercontent.com/13294321/221695132-48977639-0338-41e3-8705-316ab6699987.png)

**Fleet-Agent Bundle Error:**
[Fleet-Agent Bundle Error.txt](https://github.com/rancher/rancher/files/10844691/Fleet-Agent.Bundle.Error.txt)

**Additional context**
This is an almost identical issue to ticket [40684](https://github.com/rancher/rancher/issues/40684) and [40565](https://github.com/rancher/rancher/issues/40565)

**Comment by HarrisonWAffel** [comment]
PRs have been merged into both rancher/rancher and rancher/fleet, this issue is now ready for testing on 2.6-head.

**Comment by jameson-mcghee** [comment]
During testing on `v2.6-head` (Commit ID: 5e33172), I was able to verify that this issue is no longer reproducing when following the Test Steps for [these scenarios](https://github.com/rancher/rancher/issues/40684#issuecomment-1446478702). Therefore I am closing this ticket as Done.

**Test Steps:**
1. Spin up a Rancher cluster
2. Create a downstream cluster with the a cluster name that has 63 characters (e.g. loremipsumdolorsitametconsectetueradipiscingelitaeneancomc71c13)
3. Open the _Kubectl Shell_ for the `local` cluster and execute the command: `k get bundles.fleet.cattle.io -A`
4. Locate the bundle with the format `fleet-agent-<CLUSTER_NAME>-xxxxx`, and then execute the following command: `k get bundles.fleet.cattle.io fleet-agent-<CLUSTER_NAME>-xxxxx -n fleet-default -o yaml`
5. Verify that SUC and Fleet pods are installed successfully on the downstream cluster

**Screenshots:**
![image](https://user-images.githubusercontent.com/13294321/222784744-787de1ba-d07a-4d58-889d-27f9e58e7028.png)
![image](https://user-images.githubusercontent.com/13294321/222784766-921fe238-0826-462d-80f0-4df2f1aa711b.png)
![image](https://user-images.githubusercontent.com/13294321/222785677-7d76457e-9c2e-4313-9722-130d9a9d672c.png)
![image](https://user-images.githubusercontent.com/13294321/222785690-4732747c-6465-4b8a-ad02-5c2acecbae50.png)

**Kubectl Bundle Name Logs:**
[Kubectl Bundle Name Logs.txt](https://github.com/rancher/rancher/files/10884690/Kubectl.Bundle.Name.Logs.txt)
