### ISSUE TITLE
Validate and document Hardened Provisioned RKE2 Cluster upgrade from 1.24 to 1.25

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#40736]
As part of validating support for k8s 1.25 support we want to ensure hardened provisioned RKE2 clusters can be upgraded from k8s <=1.24 to 1.25.

The purpose of this "task" issue is to verify/refine/document the steps outlined below. The "document" part can be done as a comment on this issue and will likely be turned in a separate documentation issue.

1. Provision RKE2 hardened cluster on k8s 1.24 per the existing hardening recommendations (only Custom clusters are currently supported; profile `cis-1.6` to be chosen)
1. Provided node requirements are met for CIS 1.23, upgrade k8s version of this cluster to 1.25 while ensuring the following before saving the cluster (if not done automatically by UI yet, make changes manually and note this):
	- The profile is changed to `cis-1.23`
	- PSACT `rancher-restricted` is selected
1. Ensure the cluster is upgraded successfully and is otherwise healthy

Reference "k8s 1.25 support" umbrella issue: https://github.com/rancher/rancher/issues/38701

**Comment by rancher-max** [comment]
Made an edit in the issue description so that it used the correct profile value of `cis-1.23` 👍

**Comment by jiaqiluo** [comment]
Following the steps mentioned in the issue, a custom hardened k3s cluster is upgraded from v1.24.10+rke2r1 to v1.25.6+rke2r1 and passes the cis scan.

The cluster is hardened by following [RKE2 Hardening Guide](https://github.com/rancher/rancher-docs/blob/release/v2.7.2/docs/pages-for-subheaders/rke2-hardening-guide.md) which will be released for v2.7.2

The `rancher-cis-benchmark` app version 4.0.0-rc3 is used to run the CIS scan with the profile `k3s-cis-1.23-profile-hardened`. All checks are passed before and after upgrading the cluster.

**Comment by jiaqiluo** [comment]
This is moved to to-test for QA to validate if they can upgrade the cluster with the provided steps.

Once we get the confirmation from QA, we will add those steps to rancher's documentation.

A separate issue in the rancher-docs repo will be linked to this one.

**Comment by markusewalker** [comment]
**QA TEST PLAN**

**Scenarios**
|Scenario|Test Case|
|---|---|
|1|As a standard user, validated that the instructions in the RKE2 hardening [guide](https://github.com/rancher/rancher-docs/blob/release/v2.7.2/docs/pages-for-subheaders/rke2-hardening-guide.md) successfully upgrades an v1.24 -> v1.25 RKE2 downstream node driver cluster|

**Comment by markusewalker** [comment]
Validated that the guide works as expected in `v2.7-head` https://github.com/rancher/rancher/commit/211409c9a689d8ee4d801ed1bce1d887b0fb4b00. See details below:

**ENVIRONMENT DETAILS**
- Rancher install: Helm
- Rancher version: `v2.7-head` https://github.com/rancher/rancher/commit/211409c9a689d8ee4d801ed1bce1d887b0fb4b00
- Browser: Chrome

**TEST RESULT**
|Scenario|Test Case|Result
|---|---|---|
|1|As a standard user, validated that the instructions in the RKE2 hardening guide successfully upgrades an v1.24 -> v1.25 RKE2 downstream node driver cluster|:white_check_mark:|

**VALIDATION STEPS**

**Scenario 1**
1. Navigated to Rancher > Cluster Management > Create > Custom.
2. Before provisioning, set the following cluster configuration details:
     - K8s version -> v1.24
     - CIS Profile -> `cis-1.6`
     - `protect-kernel-defaults: true`
3. Created the custom cluster.
4. Navigated to a terminal that had 3 separate nodes: 1 etcd, 1 cp, 1 worker.
5. Set the kernel parameters with the following commands in /etc/sysctl.d/90-kubelet.conf:
```
vm.panic_on_oom=0
vm.overcommit_memory=1
kernel.panic=10
kernel.panic_on_oops=1
```
6. Ran the following command: `sudo sysctl -p /etc/sysctl.d/90-kubelet.conf`.
7. On each node, ensured the etcd user is configured properly with the command: `sudo useradd -r -c "etcd user" -s /sbin/nologin -M etcd -U`.
8. Registered each node with its respective registration command.
9. Validated that the cluster and nodes came up as `Active` in Cluster Management and Cluster Explorer.
10. Validated that all pods in the system project page are up and `Active`.
11. Navigated back to the control plane node in a separate terminal,
12. Created files `account_update.yaml` and `account_update.sh` from the guide.
13. Executed the `account_update.sh` script.
14. Installed the CIS benchmark chart in the cluster.
15. Ran a CIS scan with profile `rke2-cis-1.23-profile-hardened` and validated that it passed:
![image](https://user-images.githubusercontent.com/52591819/225076477-21894944-3576-4bee-b00e-bf1db776de68.png) 
16. Edited the cluster's configuration and updated the following cluster configuration details:
     - K8s version -> v1.25
17. Noted that I see the following banner:
![image](https://user-images.githubusercontent.com/52591819/225076392-9378bc86-5906-4a12-826f-2048f57f5476.png) 
18. Updated the CIS profile to `cis-1.23` and noted that the default PSACT value goes to `rancher-restricted`:
![image](https://user-images.githubusercontent.com/52591819/225076357-0b24fa0b-d1e9-42a0-b986-0821513a5db8.png) 
19. Updated the cluster and validated that the cluster and nodes upgraded to v1.25.
20. Validated that the pods in the system project are up and `Active`.
21. Ran a new CIS scan and noted that the scan failed:
[image](https://user-images.githubusercontent.com/52591819/225076298-f830ed0a-c577-4076-b646-4677d04fc04d.png) 
     - As mentioned in the guide, CIS checks 5.2.2-5.2.8 failed as expected:
![image](https://user-images.githubusercontent.com/52591819/225076245-93c8c13b-7b30-4b4b-ba6f-4f2a0bf283b3.png) 
22. Created a test deployment with container image `nginx:latest` and validated that it failed:
![image](https://user-images.githubusercontent.com/52591819/225076201-957daef2-bfa1-4b79-9378-ea1894e7bf0e.png)
