### ISSUE TITLE
Why rancher agent don't check /var/lib/rancher exist ?

### ISSUE THREAD

**Issue by cedvan** [rancher/rancher#4073]
Rancher Version: 0.59.1

Docker Version: 1.9.1

OS: https://github.com/ailispaw/docker-root

Steps to Reproduce: 

```
$ ln /mnt/sda1/var/lib/rancher /var/lib/rancher
$ docker run -d --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v0.10.0 https://my-rancher-server/v1/scripts/4A21993727DD77639CA1:1458608400000:4PopmVK3es88hRjXtZ0Jg8sexg
```

Results: 
`mkdir: cannot create directory '/var/lib/rancher': File exists`

Expected: 
if `/var/lib/rancher` missing : `mkdir /var/lib/rancher` and continue
if `/var/lib/rancher` exist and not empty : `rm -rf /var/lib/rancher/*` and continue
if `/var/lib/rancher` exist and empty : continue

**Comment by ibuildthecloud** [comment]
Well that seems bad.... Let me look

**Comment by cedvan** [comment]
@ibuildthecloud, Need create symbolic link to save rancher data. In my host,` /var/lib` is in memory and not on hard storage.

**Comment by cedvan** [comment]
@ibuildthecloud, Need create symbolic link to save rancher data. In my host,` /var/lib` is in memory and not on hard storage.

**Comment by PotterDai** [comment]
it also seems that if the address of rancher server has changed, directly restarting rancher agent with new server address cause ERROR: Re-register agent.   Need to manually delete all stuffs in /var/lib/rancher folder which is a bit annoying..

**Comment by deniseschannon** [comment]
@StrongMonkey Can you also look at this one to try and reproduce with the new go agent.

**Comment by StrongMonkey** [comment]
@deniseschannon I think the problem happens in the registration shell script not go-agent. I can take a look to see if i can make a PR for shell script.

**Comment by deniseschannon** [comment]
Merged after v1.2.0-pre4-rc5

**Comment by sangeethah** [comment]
Tested with v1.2.0-pre4-rc8

With /var/lib/rancher directory existing (with / without contents) , host registration is successful.

Created empty /var/lib/rancher  directory.
Executed custom host registration docker command and was able to get host successfully added to rancher server.
Deployed few containers.
"Deactivate" and Remove this host from rancher-server.

on the host remove all docker containers.
Re add the host to rancher server by  executing custom host registration docker command.
Able to get host added successfully to rancher server.

**Comment by cedvan** [comment]
Nice, good work ! Thank you

**Comment by occasl** [comment]
This works fine but what the whole point of having the symlink is to use a volume that has more space. Now the data is sitting in /var/lib/rancher rather than where I want it, /data/rancher. How can I configure it do that?

**Comment by orchmaster** [comment]
I have similar question like @occasl asked.

Now the data is sitting in /var/lib/rancher rather than where I want it, /app/rancher. How can I configure it do that?
