### ISSUE TITLE
Validate and document Hardened Imported k3s Cluster upgrade from 1.24 to 1.25

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#40739]
As part of validating support for k8s 1.25 support we want to ensure hardened imported RKE2 clusters can be upgraded from k8s <=1.24 to 1.25.

The purpose of this "task" issue is to verify/refine/document the steps outlined below. The "document" part can be done as a comment on this issue and will likely be turned into a separate documentation issue.

1. Create standalone k3s hardened cluster on k8s 1.24 per the existing hardening recommendations
1. Import this cluster into Rancher
1. Prepare the cluster for the upgrade. _This step definitely needs refinement!_ See the documentation for the standalone k3s upgrade procedure prepared per https://github.com/k3s-io/docs/issues/86 as a starting point. However, we need to add a configuration of cluster-level PSA similar to `rancher-restricted` PSACT to these steps as updating the namespace where SUC runs as well as other Rancher-specific namespaces may not be a feasible option (this is to be evaluated).
1. After preparing the cluster per the above, edit the cluster in Rancher UI, change k8s version to 1.25 and save the changes.
1. Ensure the cluster is upgraded successfully and is otherwise healthy

Reference "k8s 1.25 support" umbrella issue: https://github.com/rancher/rancher/issues/38701

**Comment by jiaqiluo** [comment]
Following the steps mentioned in the issue, an imported hardened k3s cluster is upgraded from 1.24 to 1.25 and passes the cis scan. 

The k3s cluster runs Kubernetes v1.24.10+k3s1 with one node. The cluster is hardened by following [K3s Hardening Guide](https://docs.k3s.io/security/hardening-guide).

The cluster is imported into rancher and upgraded to v1.25.6+k3s1 via Rancher UI. 

 The `rancher-cis-benchmark` app version 4.0.0-rc3 is used to run the CIS scan with the profile `k3s-cis-1.23-profile-hardened`. All checks are passed before and after upgrading the cluster.  


## Additional information for step 3

The steps in the [K3s docs](https://docs.k3s.io/known-issues#:~:text=Upgrading%20Hardened%20Clusters%20from%20v1.24.x%20to%20v1.25.x) are sufficient for preparing the upgrade except that we should use the following PSA config file instead of the one in the docs: 

<details>
<summary> /var/lib/rancher/k3s/server/psa.yaml </summary>

```
apiVersion: apiserver.config.k8s.io/v1
kind: AdmissionConfiguration
plugins:
- configuration:
    apiVersion: pod-security.admission.config.k8s.io/v1
    defaults:
      audit: restricted
      audit-version: latest
      enforce: restricted
      enforce-version: latest
      warn: restricted
      warn-version: latest
    exemptions:
      namespaces:
      - ingress-nginx
      - kube-system
      - cattle-system
      - cattle-epinio-system
      - cattle-fleet-system
      - longhorn-system
      - cattle-neuvector-system
      - cattle-monitoring-system
      - rancher-alerting-drivers
      - cis-operator-system
      - cattle-csp-adapter-system
      - cattle-externalip-system
      - cattle-gatekeeper-system
      - istio-system
      - cattle-istio-system
      - cattle-logging-system
      - cattle-windows-gmsa-system
      - cattle-sriov-system
      - cattle-ui-plugin-system
      - tigera-operator
    kind: PodSecurityConfiguration
  name: PodSecurity
  path: ""
```
</details>

**Comment by markusewalker** [comment]
**QA TEST PLAN**

Scenarios
|Scenario|Test Case|
|---|---|
|1|As a standard user, validated that the instructions in the K3s hardening guide successfully upgrades an v1.24 -> v1.25 imported K3s cluster|

**Comment by markusewalker** [comment]
Reopening as I am seeing similar issue reported in https://github.com/rancher/rancher/issues/40738. See below:

**TEST RESULT**
Scenarios
|Scenario|Test Case|Result
|---|---|---|
|1|As a standard user, validated that the instructions in the K3s hardening guide successfully upgrades an v1.24 -> v1.25 imported K3s cluster|:x:|

**VALIDATION STEPS**

**Scenario 1**
1. In a terminal, setup an K3scluster with 3 servers, 1 worker and K8s version set at v1.24.
2. Followed the K3s hardening guide to ensure the cluster is hardened before importing into Rancher.
3. Navigated to Rancher > Cluster Management > Import Existing.
4. Imported my K3s cluster into Rancher; validated that the cluster and nodes came up as `Active` in Cluster Management and Cluster Explorer.
5. Validated that the pods in the system project page are up and `Active`.
6. Installed the CIS benchmark chart into the cluster.
7. Ran a CIS scan with the `k3s-profile-1.23-hardened` profile and validated that it passed:
![image](https://user-images.githubusercontent.com/52591819/225137109-845a192e-56c5-4b8a-9f17-8cd63a5537fa.png) 
8. Navigated back to my terminal where I created my K3s cluster.
9. In each node, created file `psa.yaml` at the `/var/lib/rancher/k3s/server/psa.yaml` directory. The file contains the ollowing:
```
apiVersion: apiserver.config.k8s.io/v1
kind: AdmissionConfiguration
plugins:
- configuration:
    apiVersion: pod-security.admission.config.k8s.io/v1
    defaults:
      audit: restricted
      audit-version: latest
      enforce: restricted
      enforce-version: latest
      warn: restricted
      warn-version: latest
    exemptions:
      namespaces:
      - ingress-nginx
      - kube-system
      - cattle-system
      - cattle-epinio-system
      - cattle-fleet-system
      - longhorn-system
      - cattle-neuvector-system
      - cattle-monitoring-system
      - rancher-alerting-drivers
      - cis-operator-system
      - cattle-csp-adapter-system
      - cattle-externalip-system
      - cattle-gatekeeper-system
      - istio-system
      - cattle-istio-system
      - cattle-logging-system
      - cattle-windows-gmsa-system
      - cattle-sriov-system
      - cattle-ui-plugin-system
      - tigera-operator
    kind: PodSecurityConfiguration
  name: PodSecurity
  path: ""
```
10. Navigated back to Rancher and upgraded the cluster from v1.24 to v1.25.
11. When upgrading, noted the following screen capture:
![Screen Shot 2023-03-14 at 2 11 25 PM](https://user-images.githubusercontent.com/52591819/225137378-59ef3652-50b6-42e4-b135-c7daedac3b1c.png)

**Comment by markusewalker** [comment]
Spoke with @jiaqiluo offline and we narrowed down the issue I reported to be a configuration issue. I am no longer blocked and will move this back to test.

**Comment by markusewalker** [comment]
Retested and validated that this is working as expected. See details below:

**ENVIRONMENT DETAILS**
- Rancher install: Helm
- Rancher version: `v2.7-head` https://github.com/rancher/rancher/commit/211409c9a689d8ee4d801ed1bce1d887b0fb4b00
- Browser: Chrome

**TEST RESULT**
|Scenario|Test Case|Result
|---|---|---|
|1|As a standard user, validated that the instructions in the K3s hardening guide successfully upgrades an v1.24 -> v1.25 imported K3s cluster|:white_check_mark:|

**VALIDATION STEPS**

**Scenario 1**
1. In a terminal, setup an K3scluster with 3 servers, 1 worker and K8s version set at v1.24.
2. Followed the K3s hardening guide to ensure the cluster is hardened before importing into Rancher.
3. Navigated to Rancher > Cluster Management > Import Existing.
4. Imported my K3s cluster into Rancher; validated that the cluster and nodes came up as `Active` in Cluster Management and Cluster Explorer.
5. Validated that the pods in the system project page are up and `Active`.
6. Installed the CIS benchmark chart into the cluster.
7. Ran a CIS scan with the `k3s-profile-1.23-hardened` profile and validated that it passed:
![image](https://user-images.githubusercontent.com/52591819/225167035-a876d17c-d980-49e2-8227-8245aaa692de.png) 
8. Navigated back to my terminal where I created my K3s cluster.
9. In each node, created file `psa.yaml` at the `/var/lib/rancher/k3s/server/psa.yaml` directory. The file contains the following:
```
apiVersion: apiserver.config.k8s.io/v1
kind: AdmissionConfiguration
plugins:
- configuration:
    apiVersion: pod-security.admission.config.k8s.io/v1
    defaults:
      audit: restricted
      audit-version: latest
      enforce: restricted
      enforce-version: latest
      warn: restricted
      warn-version: latest
    exemptions:
      namespaces:
      - ingress-nginx
      - kube-system
      - cattle-system
      - cattle-epinio-system
      - cattle-fleet-system
      - longhorn-system
      - cattle-neuvector-system
      - cattle-monitoring-system
      - rancher-alerting-drivers
      - cis-operator-system
      - cattle-csp-adapter-system
      - cattle-externalip-system
      - cattle-gatekeeper-system
      - istio-system
      - cattle-istio-system
      - cattle-logging-system
      - cattle-windows-gmsa-system
      - cattle-sriov-system
      - cattle-ui-plugin-system
      - tigera-operator
    kind: PodSecurityConfiguration
  name: PodSecurity
  path: ""
```
10. Restarted the K3s service on each node.
11. Navigated back to Rancher and upgraded the cluster from v1.24 to v1.25.
12. Validated that the cluster and nodes upgraded to v1.25 and is in an `Active` state.
13. Validated that the pods in the system project page are up and `Active`.
14. Ran a new CIS scan and noted that it passed:
![image](https://user-images.githubusercontent.com/52591819/225166999-5fb49c31-6f39-41f3-ba66-77b7a465738a.png)
