### ISSUE TITLE
Validate and document Hardened Provisioned k3s Cluster upgrade from 1.24 to 1.25

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#40737]
As part of validating support for k8s 1.25 support we want to ensure hardened provisioned k3s clusters can be upgraded from k8s <=1.24 to 1.25.

The purpose of this "task" issue is to verify/refine/document the steps outlined below. The "document" part can be done as a comment on this issue and will likely be turned in a separate documentation issue.

1. Provision k3s hardened cluster on k8s 1.24 per the existing hardening recommendations (only Custom clusters are supported; such cluster will have `kube-apiserver-arg.enable-admission-plugins` contain values `PodSecurityPolicy` and `NodeRestriction`)
1. Provided node requirements are met for CIS 1.23, upgrade k8s version of this cluster to 1.25 while ensuring the following before saving the cluster (if not done automatically by UI yet, make changes manually and note this):
	- `PodSecurityPolicy` is removed from `kube-apiserver-arg.enable-admission-plugins`
	- PSACT `rancher-restricted` is selected
1. Ensure the cluster is upgraded successfully and is otherwise healthy

Reference "k8s 1.25 support" umbrella issue: https://github.com/rancher/rancher/issues/38701

**Comment by jiaqiluo** [comment]
Following the steps mentioned in the issue, a custom hardened k3s cluster is upgraded from v1.24.10+k3s1 to v1.25.6+k3s1 and passes the cis scan.

The cluster is hardened by following [K3s Hardening Guide](https://github.com/rancher/rancher-docs/blob/release/v2.7.2/docs/pages-for-subheaders/k3s-hardening-guide.md) which will be released for v2.7.2

The `rancher-cis-benchmark` app version 4.0.0-rc3 is used to run the CIS scan with the profile `k3s-cis-1.23-profile-hardened`. All checks are passed before and after upgrading the cluster.

**Comment by jiaqiluo** [comment]
This is moved to to-test for QA to validate if they can upgrade the cluster with the provided steps.

Once we get the confirmation from QA, we will add those steps to rancher's documentation.

A separate issue in the rancher-docs repo will be linked to this one.

**Comment by markusewalker** [comment]
**QA TEST PLAN**

Scenarios
|Scenario|Test Case|
|---|---|
|1|As a standard user, validated that the instructions in the K3s hardening [guide](https://github.com/rancher/rancher-docs/blob/release/v2.7.2/docs/pages-for-subheaders/k3s-hardening-guide.md) successfully upgrades an v1.24 -> v1.25 K3s downstream node driver cluster|

**Comment by markusewalker** [comment]
Validated this against `v2.7-head`  https://github.com/rancher/rancher/commit/211409c9a689d8ee4d801ed1bce1d887b0fb4b00. See details below:

**ENVIRONMENT DETAILS**
- Rancher install: Helm
- Rancher version: `v2.7-head` https://github.com/rancher/rancher/commit/211409c9a689d8ee4d801ed1bce1d887b0fb4b00
- Browser: Chrome

**TEST RESULT**
|Scenario|Test Case|Result
|---|---|---|
|1|As a standard user, validated that the instructions in the K3s hardening guide successfully upgrades an v1.24 -> v1.25 K3s downstream node driver cluster|:white_check_mark:|

**VALIDATION STEPS**

**Scenario 1**
1. Navigated to Rancher > Cluster Management > Create > Custom.
2. Before provisioning, set the following cluster configuration details:
     - K8s version -> v1.24
     - `protect-kernel-defaults: true`
3. Created the custom cluster.
4. Navigated to a terminal that had 3 separate nodes: 1 etcd, 1 cp, 1 worker.
5. Set the kernel parameters with the following commands in /etc/sysctl.d/90-kubelet.conf:
```
vm.panic_on_oom=0
vm.overcommit_memory=1
kernel.panic=10
kernel.panic_on_oops=1
```
6. Ran the following command: `sudo sysctl -p /etc/sysctl.d/90-kubelet.conf`.
7. In the control plane node, created directory `/var/lib/rancher/k3s/server/logs` and created `audit.yaml` file based on the guide.
8. Registered each node with its respective registration command.
9. Validated that the cluster and nodes came up as `Active` in Cluster Management and Cluster Explorer.
10. Validated that all pods in the system project page are up and `Active`.
11. Navigated back to the control plane node in a separate terminal,
12. Created files `psp.yaml` and `policy.yaml` from the guide in the `/var/lib/rancher/k3s/server` directory.
13. Ran `kubectl apply -f` on both of the above YAML files.
14. Navigated back to cluster configuration in Rancher and included followed the `Reference Hardened K3s Template Configuration` section.
14. Validated that with the above changes, the cluster momentarily went into `Updating` state before reverting back to `Active` once the changes took affect in the cluster.
15. Installed the CIS benchmark chart in the cluster.
16. Ran a CIS scan with profile `k3s-cis-1.23-profile-hardened` and validated that it passed:
![image](https://user-images.githubusercontent.com/52591819/225096316-37ed012e-3ba0-49c2-82fa-624f60133bcd.png) 
17. Attempted to upgrade K8s version to 1.25 and noted the following warning message:
![image](https://user-images.githubusercontent.com/52591819/225096286-3ece2442-280f-43f7-a3da-f1ef49155dd3.png) 
18. Following the instructions, removed the PSP admission controller from my cluster configuration YAML.
19. Updated the cluster and validated that the cluster and nodes upgraded to v1.25.
20. Validated that the pods in the system project are up and `Active`.
21. Ran a new CIS scan and noted that the scan failed:
![image](https://user-images.githubusercontent.com/52591819/225096238-24cde7b0-6c6f-43b5-b8c4-1899dea0975b.png) 
     - Noted that the error is due to admission plugins:
![image](https://user-images.githubusercontent.com/52591819/225096199-d1c40523-eee3-4ad3-b2bb-7b8cfc2210f6.png) 
22. Created a test deployment with container image `nginx:latest` and validated that it failed:
![image](https://user-images.githubusercontent.com/52591819/225096160-e4612a25-5d2a-41db-9931-212b6815274b.png)
