### ISSUE TITLE
Validate and add Docker 23.0.x version

### ISSUE THREAD

**Issue by doflamingo721** [rancher/rancher#40731]
There has been a new major release from docker:
https://docs.docker.com/engine/release-notes/23.0/
https://github.com/moby/moby/releases/tag/v23.0.0
https://github.com/moby/moby/releases/tag/v23.0.1
https://github.com/moby/moby/releases/tag/v23.0.2

- Following docker versions to be added:
```
23.0.0
23.0.1
23.0.2
```
To do:
- [x] Add docker 23.0.0, 23.0.1 and 23.0.2 in install-docker script.
- [x] Add support for docker 23.0.x in RKE.
- [x] Replace all instances of 20.10 in rancher with 23.0 to update the default version to 23.0

Same approach as https://github.com/rancher/rancher/issues/39345 to be followed for implementation and testing.

Related issue: https://github.com/rancher/rancher/issues/40417

SURE-5904

**Comment by doflamingo721** [comment]
PR to add support for docker 23.0.x to rke: https://github.com/rancher/kontainer-driver-metadata/pull/1100

**Comment by doflamingo721** [comment]
PR to add docker version 23.0.0 and 23.0.1 to install-docker script: https://github.com/rancher/install-docker/pull/109

**Comment by snasovich** [comment]
@doflamingo721 , following up to our earlier discussion, we want to also make sure `rancher/rancher` code changes to update default Docker version are done. It should be similar to PRs done as a part of https://github.com/rancher/rancher/issues/30406 and more specifically https://github.com/rancher/rancher/pull/31127 (however there may be more references to 20.10.x added since that PR is quite old).

Note that it also relates to the following comment on UI issue - https://github.com/rancher/dashboard/issues/8682#issuecomment-1514974818

cc: @mitulshah-suse @sowmyav27 @

**Comment by Sahota1225** [comment]
Moving the issue to Q3 as we do not have the capacity to include in Q2

**Comment by Sahota1225** [comment]
Moving this issue back to Q2 as QA have the capacity to test this in Q2.

**Comment by vivek-shilimkar** [comment]
While the docker versions were not released tested the following URLs

- [x]  curl -L https://releases.rancher.com/install-docker-dev/23.0.0.sh 
- [x]  curl -L https://releases.rancher.com/install-docker-dev/23.0.1.sh 
- [x]  curl -L https://releases.rancher.com/install-docker-dev/23.0.2.sh 

Confirmed the default URL points to the latest: 23.0.2.sh
- [x] curl -L https://releases.rancher.com/install-docker/23.0.sh 

All the URLs are pointing to correct docker version.

**Comment by vivek-shilimkar** [comment]
Since docker versions are already released and working as expected, closing this issue.

**Comment by vivek-shilimkar** [comment]
Moving the issue to the release task to ensure nothing else is pending from release side.

**Comment by kinarashah** [comment]
https://github.com/rancher/rancher/issues/41454#issuecomment-1581324341 

Newer versions are now available, so 23.0.sh points to 23.0.6.
