### ISSUE TITLE
[BUG] Updating internal server URL, internal server CA, and user token invalidates CAPI kubeconfig secret

### ISSUE THREAD

**Issue by Oats87** [rancher/rancher#40741]
**Rancher Server Setup**
- Rancher version: v2.7

**Describe the bug**
When updating the internal server URL, internal server CA, and/or Rancher token for a given v2prov cluster, the CAPI kubeconfig secret becomes outdated because Rancher relies on the old version of the secret.

**To Reproduce**
Set up a Rancher installation
Create a v2prov cluster and wait for it to provision
Update the internal server URL, internal server CA, and/or delete/modify the user token that corresponds with the kubeconfig secret of the cluster

**Result**
Observe the kubeconfig secret is not updated

**Expected Result**
The kubeconfig secret should be updated

**Screenshots**

**Additional context**

**Comment by nickwsuse** [comment]
`Verified on v2.7.2-rc7`

This did indeed fix the RKE2 migration issue (https://github.com/rancher/rancher/issues/40080). I did some additional testing outside of that use case by deleting the Rancher pods to trigger this change and saw a message in the logs stating the kubeconfig secret for the cluster is being deleted.
