### ISSUE TITLE
Support new Azure machine driver

### ISSUE THREAD

**Issue by kvaes** [rancher/rancher#4074]
Rancher Version: 0.63.1
Docker Version: Not relevant
OS: Not relevant
Steps to Reproduce: Use the Azure option via the "add hosts"
Results: This deploys hosts into the "Azure Classic"-mode (also called ASM or Azure Service Manager).

Suggestion: This mode is deemed to disappear. The future for Azure is the "ARM" (Azure Resource Manager, or also called "the new portal"). The logic behind this platform is, from a network / API stance, different. I would suggest to focus on this portal in regards to the future, instead of the old...

**Comment by vincent99** [comment]
Those are the options for the Azure driver in `docker-machine`.  It's being broken out into an add on driver and they may have switched APIs while doing that.

**Comment by kvaes** [comment]
Good point. Will pose the question more in that direction. You are correct that this is not a rancher issue, but related to the integration between docker & azure (via docker-machine).

**Comment by kvaes** [comment]
Reopened as a request via Twitter ; https://twitter.com/Rancher_Labs/status/712317756440338432

and after finding some new info ; https://t.co/2JWgVeg4b4 (tnx to @rgardler)

These changes imply a change to the UI.

**Comment by vincent99** [comment]
We will look at supporting this when there's a release of docker-machine that includes the new driver.  It's only in master right now.

**Comment by rcarmo** [comment]
Hi guys, the machine driver for ARM is pretty much finished and [fully documented](https://docs.docker.com/machine/drivers/azure/), so I was wondering when this is due...

**Comment by vincent99** [comment]
Instead of asking for certificates it now does oauth, like the Google driver.  This is fine for use on your laptop but doesn't work very well for our multi-tenant, hosted or API-driven use caas. 

So major changes are needed to add a way to support them, and those are not currently scheduled.

**Comment by rcarmo** [comment]
Actually, you can also use an application key to interact with the Azure ARM APIs using a service principal. I'm currently doing so in Python using https://github.com/gbowerman/azurerm

**Comment by vincent99** [comment]
That would be great, if there were options for it in docker-machine... https://github.com/docker/machine/blob/master/drivers/azure/azure.go

**Comment by rcarmo** [comment]
Actually, the comparable bits are in azureutil, which is the folder just beside that:

https://github.com/docker/machine/tree/master/drivers/azure/azureutil <https://github.com/docker/machine/tree/master/drivers/azure/azureutil>

**Comment by vincent99** [comment]
The driver struct (or more accurately [GetCreateFlags](https://github.com/docker/machine/blob/master/drivers/azure/azure.go#L105-L205) below it) is the public interface exposed by docker-machine and available to use from the outside world.  It doesn't matter where the implementation of auth actually is when there are no flags to take in an application id/secret.

**Comment by kvaes** [comment]
Fyi - https://github.com/docker/machine/pull/3665

**Comment by vincent99** [comment]
@kvaes Yes we saw this last night and expect to be much happier using this and being able to update the rest of docker-machine.

**Comment by tfiduccia** [comment]
Version - master 8/25
Verified - was able to add a Azure machine to rancher
