### ISSUE TITLE
Update Rancher image from k8s.gcr.io to registry.K8s.io 

### ISSUE THREAD

**Issue by Sahota1225** [rancher/rancher#40750]
Please update all of the images owned by Hostbusters to ensure that if they are pulling from the K8s GCR to update them to registry.K8s.io:
 
|rancher/calico-cni|system|
|rancher/flannel-cni|system|
|rancher/hyperkube|system|
|rancher/kube-api-auth|system|
|rancher/machine|core|
|rancher/mirrored-calico-ctl|system|
|rancher/mirrored-calico-kube-controllers|system|
|rancher/mirrored-calico-node|system|
|rancher/mirrored-calico-pod2daemon-flexvol|system|
|rancher/mirrored-cluster-proportional-autoscaler|system|
|rancher/mirrored-coredns-coredns|system|
|rancher/mirrored-coreos-etcd|system|
|rancher/mirrored-coreos-flannel|system|
|rancher/mirrored-flannelcni-flannel|system|
|rancher/mirrored-k8s-dns-dnsmasq-nanny|system|
|rancher/mirrored-k8s-dns-kube-dns|system|
|rancher/mirrored-k8s-dns-node-cache|system|
|rancher/mirrored-k8s-dns-sidecar|system|
|rancher/mirrored-nginx-ingress-controller-defaultbackend|system|
|rancher/mirrored-sigwindowstools-k8s-gmsa-webhook|rancher-windows-gmsa:2.0.0|
|rancher/nginx-ingress-controller|system|
|rancher/rancher-agent|rancher|
|rancher/rancher-runtime|rancher|
|rancher/rke-tools|system|
|rancher/system-agent|rancher|
|rancher/system-agent-installer-k3s|rancher|
|rancher/system-agent-installer-rke2|rancher|
|rancher/system-agent-installer-rke2|rancher,rke2All|
|rancher/system-upgrade-controller|rancher-k3s-upgrader:0.3.3,system-upgrade-controller:101.0.0+up0.3.3|

**Comment by pjbgf** [comment]
Relates to https://github.com/rancher/rancher/issues/40582.
