### ISSUE TITLE
[BUG] RKE2 Cluster Not Coming Up After Migrating With RKE2 + k3s Clusters 

### ISSUE THREAD

**Issue by nickwsuse** [rancher/rancher#40767]
**Rancher Server Setup**
- Rancher version: `v2.6.11-rc9 // v2.6-head ID: ec67e31`
- Installation option (Docker install/Helm Chart): `Helm`
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): `RKE2 // k3s`
- Proxy/Cert Details: `byo-valid cert`

**Information about the Cluster**
- Kubernetes version: `RKE2: v1.24.10+rke2r1 // k3s: v1.24.10+k3s1`
- Cluster Type (Local/Downstream): `Downstream`
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): `EC2`

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): `Admin`

**Describe the bug**
When performing a migration to a new HA cluster with the backup/restore operator and one RKE2 and one k3s cluster, the RKE2 cluster never comes back up after migration. The message shown is that it's waiting for the plan to be applied.

**To Reproduce**
1. Create an HA cluster
2. On that HA cluster, provision an RKE2 EKS cluster (3  workers, 2 control plane, 3 etcd) and one k3s EKS cluster (3 workers, 2 control plane, 3 etcd)
3. While those are provisioning, install the Rancher Backups chart
4. Once the downstream clusters are done provisioning, create a backup using the Rancher Backups chart
5. Migrate from HA1 -> HA2 using the backup that was just taken as the restore point for HA2
6. Once migrated and Rancher is installed, check the cluster management page

**Result**
The k3s cluster comes up, but the RKE2 cluster is stuck in an Updating status and waiting for a plan to be applied

**Expected Result**
Both clusters come back to an Active state after the migration

**Screenshots**
![image](https://user-images.githubusercontent.com/107147272/222804617-47315589-f164-46d6-884e-f45110f9e83b.png)

**Additional context**
This has already been looked into a bit and it appears to be an issue with missing labels and is actually a k3s bug rather than an RKE2 bug.

**Comment by MKlimuszka** [comment]
This has been fixed in 2.6.11/2.7.2 onward.
