### ISSUE TITLE
[RFE] Make the description of built-in PSACT templates more specific

### ISSUE THREAD

**Issue by pjbgf** [rancher/rancher#40761]
**Is your feature request related to a problem? Please describe.**

The current description for the built-in [PSACT templates] are vague, and convey very little about the security posture they provide:

- `rancher-privileged`:
  > The default privileged pod security admission configuration template
- `rancher-restricted`:
  > The default restricted pod security admission configuration template

[PSACT templates]: https://github.com/rancher/rancher/blob/2691d3557c76de96bdb0ff8735105fac2650c0c0/pkg/data/management/podadmissionconfigurationtemplate_data.go

**Describe the solution you'd like**

Given that the permissions are largely aligned with [upstream](https://kubernetes.io/docs/concepts/security/pod-security-standards/), we should align the narrative and highlight divergences:

- `rancher-privileged`: 
  > This is the built-in unrestricted Pod Security Admission Configuration Template. It defines the most permissive PSS policy, allowing for known privilege escalations. This policy contains no exemptions.
- `rancher-restricted`:
  > This is the built-in restricted Pod Security Admission Configuration Template. It defines a heavily restricted policy, based on current Pod hardening best practices. This policy contains namespace level exemptions for Rancher components.

**Describe alternatives you've considered**
`N/A`

**Additional context**
`N/A`

**Comment by pjbgf** [comment]
@macedogm PTAL on the messages above, feel free to amend them directly if necessary.

**Comment by macedogm** [comment]
@pjbgf LGTM, thanks for opening this issue.

CC @jiaqiluo and @cbron for visibility.

**Comment by macedogm** [comment]
@gaktive I see that we already have some basic descriptions for both templates in https://github.com/rancher/rancher/blob/release/v2.7/pkg/data/management/podadmissionconfigurationtemplate_data.go#L54 and https://github.com/rancher/rancher/blob/release/v2.7/pkg/data/management/podadmissionconfigurationtemplate_data.go#L78. However, they are not displayed in the UI (see the image below). Could this be a bug?

![image](https://user-images.githubusercontent.com/17654553/222747802-94f164f6-f910-42ab-b99d-3c41df5922e1.png)

**Comment by macedogm** [comment]
@gaktive apologies for my extra comment, but only after posting it I saw that @pjbgf opened a bug issue for this in https://github.com/rancher/dashboard/issues/8335.

**Comment by gaktive** [comment]
@macedogm gotcha. What's the milestone for this?

**Comment by macedogm** [comment]
`v2.7.2` if possible, unless it requires too much work and time.

**Comment by jiaqiluo** [comment]
The fix on the rancher/rancher side has been merged.  

Now waiting for the PR for docs to be merged.

**Comment by jiaqiluo** [comment]
can be validated in the latest v2.7-head

**Comment by markusewalker** [comment]
Validated that this is addressed in `v2.7-head` https://github.com/rancher/rancher/commit/cd1a71624a94de993d471ce8a643cf4d2dbb75a6. See details below:

**ENVIRONMENT DETAILS**
- Rancher install: Docker
- Rancher version: `v2.7-head` https://github.com/rancher/rancher/commit/cd1a71624a94de993d471ce8a643cf4d2dbb75a6
- Browser: Chrome

**TEST RESULT**
|Scenario|Test Case|Result
|---|---|---|
|1|As a standard user, validate that the built-in PSACT template descriptions are displayed|:white_check_mark:|

**VALIDATION STEPS**

**Scenario 1**
1. Navigated to Rancher > Cluster Management > Advanced > Pod Security Admissions.
2. Validated that the description shows the updated display:
![image](https://user-images.githubusercontent.com/52591819/225405665-2eaeb9cd-e770-422d-9d63-045ffd9fd2ce.png) 
3. Clicked through each built-in PSACT template and validated that the description is there:
![image](https://user-images.githubusercontent.com/52591819/225405692-4825926c-344e-41e2-bf01-5ad33d2c8057.png)
![image](https://user-images.githubusercontent.com/52591819/225405711-96111653-643c-4a98-912c-8a2512f22b4a.png) 
4. Logged out and logged in as an admin user.
5. Navigated to top-left menu > local > More Resources > Rancher > Pod Security Admissions.
6. Repeated steps 2-3 and validated I see the same results, but in the `local` cluster and not Cluster Management.
