### ISSUE TITLE
Typo in Manage Environments page.

### ISSUE THREAD

**Issue by jmatsushita** [rancher/rancher#4076]
Rancher Version:
1.0.0-rc1

Docker Version:

OS: 

Steps to Reproduce: 
Go to the "Manage Environments" page.

Results: 

![image](https://cloud.githubusercontent.com/assets/356097/13953612/1e55c50c-f03d-11e5-8e10-e1b0ad4447b5.png)

Expected:

Orchestartion -> Orchestration

**Comment by lvuch** [comment]
resolved in https://github.com/rancher/ui/pull/555

**Comment by tfiduccia** [comment]
version - master 3/22
Verified fixed
