### ISSUE TITLE
[RFE] add option to set pool location and size

### ISSUE THREAD

**Issue by simonostendorf** [rancher/rancher#40765]
**Is your feature request related to a problem? Please describe.**
I currently see no option to set the location and size from "unknown" to a value for an RKE2 cluster pool.

**Describe the solution you'd like**
Possible solution could be to add an annotation or a new metadata spec for a nodepool where the location and the size can be set. 

**Additional context**
![image](https://user-images.githubusercontent.com/70595012/222751911-3ac3f5eb-3c3b-47fc-acb4-f9ebc4504ed4.png)

**Comment by simonostendorf** [comment]
Still valid.

**Comment by simonostendorf** [comment]
Still valid.

**Comment by johnwc** [comment]
Still valid.
