### ISSUE TITLE
[BUG][monitoring] global.cattle.psp.enabled=true in crd yaml but value=false in chart yaml

### ISSUE THREAD

**Issue by ronhorton** [rancher/rancher#40788]
**Rancher Server Setup**
- Rancher version: `2.7.2-rc5`
- Installation option (Docker install/Helm Chart): `Helm`
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): `Rke1 ubuntu`
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: `v1.25.6`
- Cluster Type (Local/Downstream): `downstream`
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: `admin`

**Describe the bug**
the value of global.cattle.psp.enabled does not match between installed value/chart value/crd value

**To Reproduce**
1. install rancher-monitoring:102.0.0+up40.1.2 with global.cattle.psp.enabled=true
2. verify installed version of global.cattle.psp.enabled in rancher-monitoring-crd:102.0.0+up40.1.2 = true
3. verify installed verison of global.cattle.psp.enabled in rancher-monitoring:102.0.0+up40.1.2 = false
4. verify in edit yaml of chart update global.cattle.psp.enabled in rancher-monitoring:102.0.0+up40.1.2 = true

**Result**
mismatch values of key

**Expected Result**
values of key match - should not have to check crd or do an update to check value of global.cattle.psp.enabled

**Screenshots**

**Additional context**

**Comment by bpedersen2** [comment]
In k8s v1.25 PSP has been removed. So trying to  enable it should be an error or ignored.

**Comment by ronhorton** [comment]
**Pass** verified in rancher `v2.7.2-rc7`
all values matched; set value on yaml at install was reverted to false appropriately.

install rancher-monitoring:102.0.0+up40.1.2 with global.cattle.psp.enabled=true
verify installed version of global.cattle.psp.enabled in rancher-monitoring-crd:102.0.0+up40.1.2 = false
verify installed verison of global.cattle.psp.enabled in rancher-monitoring:102.0.0+up40.1.2 = false
verify in edit yaml of chart update global.cattle.psp.enabled in rancher-monitoring:102.0.0+up40.1.2 = false
