### ISSUE TITLE
AKS charts UN-RC for 2.6.11 

### ISSUE THREAD

**Issue by Sahota1225** [rancher/rancher#40787]
This ticket is a placeholder to track charts unrc- AKS

**Comment by a-blender** [comment]
Based on @pgonin's and @leflambeur feedback, the latest AKS operator fixes for PepsiCo are not expected in rancher release v2.6.11 and will be available in v2.7.x.

So, v1.0.8 will not be used.

Instead, the following plan will be implemented
* Tag v1.0.9 from the same commit we have v1.0.8-rc2 tag on.
* Update release notes on v1.0.8 in GH to indicate it was accidental release and should not be used (not that anyone would, but still want that note for closure)
* Do the rest of steps that are done as part of un-RC process (PRs in rancher/charts and rancher/rancher)
* Don’t do any testing now on https://github.com/rancher/rancher/issues/40087 but test them for 2.7

**Comment by ronhorton** [comment]
verified ask-operator un-rc'd in rancher-images.txt for v2.6.11

**Comment by ronhorton** [comment]
@Josh-Diamond sorry, I closed this one after verifying un-rc of aks-operator. 
moved out of milestone (so 2.6.11 could be closed) and reopened so you can verify.

**Comment by Josh-Diamond** [comment]
Ticket #40787 - Test Results - ✅ 
---

Verified with Docker on a single-node instance using rancher `v2.6-f3f9e476d68dbd08f756f89eac79d243f4448c38-head`:
1. Fresh install of rancher `v2.6-head`
2. Provision a downstream AKS cluster - [`v1.24.9`]
3. Navigate to `Cluster Explorer > Workloads > Pods > All Namespaces` of local and verify aks operator is `v1.0.9` and unRC'd
4. Verified - `aks-operator:v1.0.9`
5. Once cluster successfully provisions, navigate to `Cluster Explorer > Workloads > Pods > All Namespaces`
6. Verified - all pods/workloads up and running and active - (as expected)
