### ISSUE TITLE
After upgrading master, deleted host do not get removed from provider

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4079]
Version - master 3/22

Steps:
1.  Update master version
2.  Delete DO host (or any host)
3.  Go to DO (to provider website)

Results: The host still exist on the provider side.

Expected: Host should be removed.

Comments from Craig: basically, if you end up moving from gms container A to gms container B, when you go to delete a machine, it will get deleted in rancher but will not get deleted in the cloud provider

**Comment by cjellick** [comment]
totes fixed.

**Comment by tfiduccia** [comment]
Version - master 3/23
Verified fixed
