### ISSUE TITLE
Lower charts refresh time

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#40805]
This is for apps v2: https://github.com/rancher/rancher/blob/release/v2.7/pkg/settings/setting.go#L130
We should also look at changing apps v1, though that will have smaller impact. 

Reasoning is to decrease load, and therefore outages, on git.rancher.io when we release charts.

**Comment by snasovich** [comment]
Looks like 15 minutes was always a default, even before it was made configurable per https://github.com/rancher/rancher/pull/33984
Also, https://github.com/rancher/rancher/pull/33879 and discussions in it may be relevant in determining suitable new default (my recommendation is anywhere in 2 to 24h range - KDM is on 24h refresh by default - need product input on this).

Another consideration is whether the setting will update automatically on Rancher upgrade if not overridden (and whether we want it to update in the first place).

**Comment by cbron** [comment]
When picking this up we also need to check how the backoff works, and if perhaps that is also causing a spamming of requests once one fails.

**Comment by rohitsakala** [comment]
Test Cases
[ ] Test if upgrading to the new version changes the refresh time to 6 hours from 15 minutes ?

**Comment by martyav** [comment]
@cbron This is labeled as a release note for 2.7.x. Can we get a blurb describing what should be noted?

**Comment by cbron** [comment]
Someone from Mapps team should be able to help with that. cc @diogoasouza / @rohitsakala

**Comment by rohitsakala** [comment]
@martyav Blurb can be :- Increasing the refresh time to 6 hours for updating rancher charts helm repository to mitigate timeout errors on git.rancher.io that happen during Rancher releases.
