### ISSUE TITLE
[BUG] Un importing an rke1 cluster from rancher floods rancher logs with errors

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#40807]
Information about the Cluster
**Rancher Server Setup**
- Rancher version: `v2.7.2-rc5` 
- Installation option (Docker install/Helm Chart): `Helm Chart`
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): `RKE1`, `v1.24.6`, `1.4.0`
- Proxy/Cert Details: `Self-signed`

**Information about the Cluster**
- Kubernetes version: `v1.24.6`
- Cluster Type (Local/Downstream): `imported  1 worker, 1 etcd, 1 cp RKE1`

**Describe the bug**
When we import an rke1 imported cluster from rancher server, notice the logs ` clusters.management.cattle.io "c-m-lnhlrm79" not found` scroll through continuously.

**To Reproduce**

- Import an rke1 1.25 cluster or rke1 1.24 cluster into the rancher server 
- Delete the imported cluster from rancher server

**Result**
Following errors are seen scrolling through continuously in rancher pod logs:
```
2023/03/07 03:02:04 [ERROR] clusters.management.cattle.io "c-m-lnhlrm79" not found
2023/03/07 03:02:19 [ERROR] clusters.management.cattle.io "c-m-lnhlrm79" not found
2023/03/07 03:02:34 [ERROR] clusters.management.cattle.io "c-m-lnhlrm79" not found
2023/03/07 03:02:49 [ERROR] clusters.management.cattle.io "c-m-lnhlrm79" not found
``` 

Some other errors from today's run:
```
2023/03/08 21:10:34 [ERROR] error syncing 'local': handler namespace-auth: Put "https://10.43.0.1:443/api/v1/namespaces/local": clusters.management.cattle.io "c-m-fctb7v8h" not found, handler defaultSvcAccountHandler: can't find system project, requeuing
ERROR] error syncing 'p-5t6hq/creator-project-owner': handler mgmt-auth-prtb-controller: projects.management.cattle.io "c-m-fctb7v8h/p-5t6hq" not found, requeuing
2023/03/08 21:00:28 [ERROR] error syncing 'p-5t6hq/creator-project-owner': handler mgmt-auth-prtb-controller: projects.management.cattle.io "c-m-fctb7v8h/p-5t6hq" not found, requeuing
2023/03/08 21:00:28 [ERROR] error syncing 'p-5t6hq/creator-project-owner': handler mgmt-auth-prtb-controller: projects.management.cattle.io "c-m-fctb7v8h/p-5t6hq" not found, requeuing
2023/03/08 21:00:28 [ERROR] error syncing 'p-5t6hq/creator-project-owner': handler mgmt-auth-prtb-controller: projects.management.cattle.io "c-m-fctb7v8h/p-5t6hq" not found, requeuing
```

**Expected Result**
No errors expected after the cluster is deleted.

**Additional context**
Issue does not happen for RKE2 imported clusters
does not happen on 2.7.0 release.

**Comment by anupama2501** [comment]
QA to validate:

**Fresh checks:**

- Install rancher on v2.7-head
- Create a downstream rke2 nodedriver- 1.24, imported rke1 1.25 and k3s custom 1.23 cluster
- Delete the clusters and verify no error logs are seen in rancher logs.

**Upgrade checks:**
Install rancher on v2.7.0
- Create a downstream rke2 nodedriver- 1.24, imported rke1 1.25 and k3s custom 1.23 cluster
- Delete the clusters and verify no error logs are seen in rancher pod logs.

**Comment by anupama2501** [comment]
Verified on v2.7-head a841a9e
1. Created an rke1 imported cluster on k8s v1.25 - 3 nodes 1 role each
2. Created an rke1 node driver cluster on k8s 1.24 - 2 nodes - 1 etcd+cp, 1 worker
3. Created an rke2 custom cluster hardened on v1.24 - 3 nodes - 1 role each
4. Deleted the imported cluster and verified no errors were seen
5. Upgraded the rke1 cluster to k8s 1.25 and then deleted the cluster - verified no errors ` clusters.management.cattle.io "c-xxx" not found` were seen
6. Deleted the rke2 cluster and verified no errors were seen.

**Comment by anupama2501** [comment]
Verified 2.7.0 upgraded to v2.7-head `2b2ed44`

1. Created an rke1 imported cluster on k8s v1.24 - 3 nodes 1 role each
2. Created an rke1 node driver cluster on k8s 1.24 - 2 nodes - 1 etcd+cp, 1 worker
3. Created an rke2 custom cluster on v1.24 - 3 nodes - 1 role each
4. Deleted the imported cluster and verified no errors were seen
5. Upgraded the rke2 cluster to k8s 1.25 and then deleted the cluster - verified no errors  clusters.management.cattle.io "c-xxx" not found were seen
6. Deleted the rke2 cluster and verified no errors were seen.
7. Created an k3s node driver cluster on v1.23 - 3 nodes - 1 role each

**Comment by cmurphy** [comment]
No release note needed since this was a 2.7.2 regression
