### ISSUE TITLE
[BUG] CIS scan 5.7.4 fails on RKE1 custom hardened cluster

### ISSUE THREAD

**Issue by macedogm** [rancher/rancher#40818]
**Rancher Server Setup**
- Rancher version: `v2.7.2-rc5`
- Installation option (Docker install/Helm Chart): `Docker install`
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): `N/A`
- Proxy/Cert Details: `N/A`

**Information about the Cluster**
- Kubernetes version: `RKE1 v1.25.6`
- Cluster Type (Local/Downstream): `downstream`
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): `downstream custom cluster manually provisioned in DigitalOcean`

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): `Admin`
  - If custom, define the set of permissions: `N/A`

**Describe the bug**

CIS check 5.7.5 is displayed as `pass` in the UI for the hardened profile CIS 1.23 for RKE1. However, after manually inspecting the JSON results file it's possible to see that the check errored.

**To Reproduce**

1. Manually provision downstream custom cluster for RKE1 `v1.25.6` (the cluster has all roles inside - etcd, cp and worker) following the hardening guides.
2. Install CIS benchmark chart `4.0.0-rc3` and execute a scan using the profile `rke-profile-hardened-1.23`.
3. In the UI the CIS check 5.7.4 is displayed as `pass`.
4. Inspect the JSON results file with `kubectl --kubeconfig <k8s config> get clusterscanreports.cis.cattle.io <scan id> -o json | jq '.spec.reportJSON | fromjson | .results' > results.json`. See that the check 5.7.4 has `"state": "pass"`, but it errors out in `"actual_value_per_node": {`.

```json
        "actual_value_per_node": {
          "cluster-test": "Error from server (Forbidden): replicationcontrollers is forbidden: User \"system:serviceaccount:cis-operator-system:cis-serviceaccount\" cannot list resource \"replicationcontrollers\" in API group \"\" in the namespace \"default\"\nError from server (Forbidden): services is forbidden: User \"system:serviceaccount:cis-operator-system:cis-serviceaccount\" cannot list resource \"services\" in API group \"\" in the namespace \"default\"\nError from server (Forbidden): daemonsets.apps is forbidden: User \"system:serviceaccount:cis-operator-system:cis-serviceaccount\" cannot list resource \"daemonsets\" in API group \"apps\" in the namespace \"default\"\nError from server (Forbidden): deployments.apps is forbidden: User \"system:serviceaccount:cis-operator-system:cis-serviceaccount\" cannot list resource \"deployments\" in API group \"apps\" in the namespace \"default\"\nError from server (Forbidden): replicasets.apps is forbidden: User \"system:serviceaccount:cis-operator-system:cis-serviceaccount\" cannot list resource \"replicasets\" in API group \"apps\" in the namespace \"default\"\nError from server (Forbidden): statefulsets.apps is forbidden: User \"system:serviceaccount:cis-operator-system:cis-serviceaccount\" cannot list resource \"statefulsets\" in API group \"apps\" in the namespace \"default\"\nError from server (Forbidden): horizontalpodautoscalers.autoscaling is forbidden: User \"system:serviceaccount:cis-operator-system:cis-serviceaccount\" cannot list resource \"horizontalpodautoscalers\" in API group \"autoscaling\" in the namespace \"default\"\nError from server (Forbidden): cronjobs.batch is forbidden: User \"system:serviceaccount:cis-operator-system:cis-serviceaccount\" cannot list resource \"cronjobs\" in API group \"batch\" in the namespace \"default\"\nError from server (Forbidden): jobs.batch is forbidden: User \"system:serviceaccount:cis-operator-system:cis-serviceaccount\" cannot list resource \"jobs\" in API group \"batch\" in the namespace \"default\"\ntrue"
        },
```

**Result**
The 5.7.4 passes in UI, but errors in the results file.

**Expected Result**
The 5.7.4 should either pass with no errors, or if it contains errors, it should fail (not pass).

**Screenshots**

![image](https://user-images.githubusercontent.com/17654553/223763553-86bb6d93-fb0e-4ef7-a845-fe6997cb1bab.png)

![image](https://user-images.githubusercontent.com/17654553/223763576-a6b78fa5-c09e-437b-ad2a-f953b584488b.png)

**Additional context**

N/A

**Comment by macedogm** [comment]
CC @jiaqiluo @prachidamle @MKlimuszka

**Comment by macedogm** [comment]
To aid with the investigation, the root cause might be related to PR https://github.com/rancher/charts/pull/2117.

**Comment by vivek-infracloud** [comment]
Validated on the rancher v2.7.2-rc6.

Validation steps.

1. Created a rancher v2.7.2-rc6
2. Provisioned a downstream RKE2 v1.25 **hardened** custom cluster with CIS profile cis-profile-1.6.
3. Validated that the cluster and nodes come up Active in Cluster Management and Cluster Explorer.
4. Installed the CIS benchmark chart v4.0.0-rc4 on the downstream cluster.
5. Ran a CIS scan with profile rke2-cis-1.23-profile-hardened.

The 5.7.4 passes with no errors. Actual value in json also show `ip-172-xx-xx-x: true` as expected.

However, there are 4 other test failures (see attached screenshot).
![Screenshot from 2023-03-20 20-15-41](https://user-images.githubusercontent.com/83208989/226375912-897fa8e2-efdf-439e-86ae-78ed622db290.png)

**Comment by vivek-infracloud** [comment]
Since the above mentioned failures are expected, and the test 5.7.4 is passing without any errors in json as well. Hence, closing this issue.
