### ISSUE TITLE
[RFE] Update Kubernetes API health endpoints

### ISSUE THREAD

**Issue by atsai1220** [rancher/rancher#40810]
**Is your feature request related to a problem? Please describe.**
When using [`tilt`](https://github.com/tilt-dev/tilt) to develop against the local cluster in Kubernetes, tilt's cluster health check fails because they are performing the check against `/livez`. This can be verified here: https://github.com/tilt-dev/tilt/issues/5976

whereas Rancher has `/ping` and `/healthz` implemented. I believe that's implemented here: https://github.com/rancher/rancher/blob/e2410e02494a5b4bd43c50d8d45ed7df5a3ad0a8/pkg/api/steve/health/health.go#L10-L19

According to Kubernetes documentation on [API endopints for health](https://kubernetes.io/docs/reference/using-api/health-checks/), the API server provides 3 API endpoints (`healthz`, `livez`, and `readyz`) to indicate the current state of the API server. **The `healthz` endpoint is also deprecated (since Kubernetes v1.16)** and should use the more specific `livez` and `readyz` endpoints.

Currently a `404` is returned for `/livez` and `/readyz` but the documentation by Kubernetes states:
> Machines that check the `healthz`/`livez`/`readyz` of the API server should rely on the HTTP status code. 

**Describe the solution you'd like**
Having access to `/livez` and `/readyz` endpoints would allow Rancher to present a conformant Kubernetes API server as expected by other tooling when expecting a Kubernetes API server.

**Describe alternatives you've considered**
I've tried using `kubectl proxy` with a kubeconfig for the local cluster to no avail.

```
❯ kubectl proxy&
Starting to serve on 127.0.0.1:8001
❯ curl 127.0.0.1:8001/livez
404 page not found
❯ curl 127.0.0.1:8001/readyz
404 page not found
```

**Additional context**
Thank you!

**Comment by Richie24** [comment]
This is still relevant and blocks the newest version of rancher to be used with the newest version of tilt.

**Comment by yyefet** [comment]
bump
