### ISSUE TITLE
[Add External Service] Adding a hostname to the IP field causes an update loop

### ISSUE THREAD

**Issue by agalpin** [rancher/rancher#4081]
Rancher Version: 0.59.1
Docker Version: 1.10.3
OS: Ubuntu
Steps to Reproduce: 
Add External Service
Target: Point to IP Address(es)
Address: dns.example.com
Results: 
Update loop

Expected:
An error prompt returned to prevent this (Not a Valid IP)

**Comment by alena1108** [comment]
@sangeethah could you link the bug where we keep track of ip address validation issues?

**Comment by deniseschannon** [comment]
@alena1108 There is no bug that keeps track of it, but I"ll mark it as an enhancement.

**Comment by alena1108** [comment]
Linking to https://github.com/rancher/rancher/issues/4125; closing as a duplicate. Going to keep track of ip validation there.
