### ISSUE TITLE
Update webhook patch logic

### ISSUE THREAD

**Issue by jakefhyde** [rancher/rancher#40826]
**Is your feature request related to a problem? Please describe.**

Whenever the provisioning cluster definition is updated, the webhook also has to be released otherwise the new fields are removed. This can cause unexpected behavior, as well as churn from team 2 for creating separate PRs to update the type definition in rancher and then team 1 to release the webhook.

**Describe the solution you'd like**

Change webhook update mechanism to only include intended changes when generating a json patch.

**Describe alternatives you've considered**

**Additional context**

**Comment by kinarashah** [comment]
@jakefhyde, I see that your fix is released with `v0.3.3` but still saw this issue with the fields @a-blender added to provisioning cluster where the agent fields got overridden. Had to update pkg/apis manually.
