### ISSUE TITLE
Service status Timeline/History

### ISSUE THREAD

**Issue by agalpin** [rancher/rancher#4082]
Rancher Version: future

Similar Feature:
Currently Rancher shows the current state of a services containers this can be quite useful in debugging issues however if you are not fast enough you can miss it when the next message replaces it.

Request:
Have a timeline/history tab under **rancher-server/apps/../services/../containers** that displays the most recent (say 20) status updates sorted with latest at the top.

**Comment by teamon** [comment]
Is this UI-only issue or does it require implementing also the persistence of events?

**Comment by agalpin** [comment]
UI mainly, this would be assigned to the service instead of the containers so it won't disappear during the 5 seconds the container runs for before restarting,, will most likely have to have persistence of the last few events to pull it off i would say. I''ll attempt a correctly worded example when i get a chance.

**Comment by teamon** [comment]
If I could suggest something, for me personally the most important use case would be to see what has changed with given upgrade (if it's new image tag or ENV change or some other config).

**Comment by p4l1ly** [comment]
for me, ideally: what has been changed, and by whom

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
