### ISSUE TITLE
Apps Catalog Repositories stuck "In Progress" (Centos 7)

### ISSUE THREAD

**Issue by asloan7** [rancher/rancher#40835]
**Rancher Server Setup**
- Rancher version: v2.7.1
- docker 23.0.1
- upgraded kernel from 3.10 to 5.4 (kernel-lt longterm with headers and devel)
- Installation option (Docker install/Helm Chart):
docker run -d --name rancher --restart=unless-stopped -p 80:80 -p 443:443  -v /etc/pki/ca-trust/extracted/pem/cacerts.pem:/etc/rancher/ssl/cert.pem  -v /etc/pki/ca-trust/extracted/pem/key.pem:/etc/rancher/ssl/key.pem  --privileged rancher/rancher:v2.7.1 --no-cacerts

**Information about the Cluster**
- (not relevant?) Kubernetes version: k3s 1.25.6 

**User Information**
- What is the role of the user logged in? Admin

**Describe the bug**
fresh install on a fresh (Centos 7) server, Apps Catalog Repositories don't download - stuck "In Progress"
![rancher-repo-pull-in-progress](https://user-images.githubusercontent.com/1675425/224067852-6ff7517b-86d4-489f-878d-019c305417b6.png)

**To Reproduce**
install 23.0.1 docker and start 2.7.1 rancher on Centos 7

**Result**
Apps Catalog Repositories don't download - stuck "In Progress" 

**Expected Result**
Apps Catalog Repositories are "Ready"

** Troubleshooting done**
From command-line on the server, 
bash-4.2$ `git clone https://git.rancher.io/partner-charts` pulls the repo, and 
`curl https://prometheus-community.github.io/helm-charts/` brings back the HTML
but in Rancher it isn't working

**Comment by joaofernandes** [comment]
having the exact same behaviour.

**Comment by mike12806** [comment]
Had the same behavior, had to downgrade back to K3S 1.24.10 to get it working again 👎

**Comment by joaofernandes** [comment]
@mike12806 thanks, that fixed, I just had to update 1 of the master nodes and it unstuck it. everything else is still on the latest.

**Comment by asloan7** [comment]
Maybe it is worth trying 1.25.7, bugfixes but not sure exactly what is causing this problem
https://github.com/k3s-io/k3s/releases/tag/v1.25.7%2Bk3s1

**Comment by flrichar** [comment]
If you look at the yaml for the repo, what does it say?
![edit-yaml](https://user-images.githubusercontent.com/3878418/226017019-45a13ae6-101d-4251-a66d-b72117f83cee.png)

**Comment by martinmlkvy** [comment]
I've got same problem. Repositories status is stuck in progress status. I am running **Rancher 2.7.1** on **K3s v1.24.6+k3s1** and i imported RKE2 cluster with version **v1.26.2+rke2r1**. 
On local cluster repositories are okey. Status is Active. But on downstream cluster (RKE2), repositories are stuck in progress mode. I tried to refresh them and it didn't worked. Any idea how to debug this problem?

**Comment by martinmlkvy** [comment]
I think problem can be with Kubernetes version. Support matrix for downstreams RKE2 cluster says 1.23 and 1.24 kubernetes version. And same it is for K3s 
https://www.suse.com/suse-rancher/support-matrix/all-supported-versions/rancher-v2-7-1/

I found this in log of cluster-agent pod of imported cluster. 
`E0320 14:59:44.618163 56 reflector.go:139] pkg/mod/github.com/rancher/client-go@v1.24.0-rancher1/tools/cache/reflector.go:168: Failed to watch *v1beta1.CronJob: failed to list *v1beta1.CronJob: the server could not find the requested resource`

This issue track support of 1.25 kubernetes version in rancher. https://github.com/rancher/rancher/issues/38701

**Comment by asloan7** [comment]
https://github.com/rancher/rancher/issues/38701 says Milestone Rancher 2.7.2, but 1.25 generally runs since 2.7.0(?), it is just the App Catalog having a problem. So this may not be generally known.

**Comment by zhanqigithub** [comment]
> @mike12806 thanks, that fixed, I just had to update 1 of the master nodes and it unstuck it. everything else is still on the latest.

which one?

**Comment by farhansj** [comment]
> Had the same behavior, had to downgrade back to K3S 1.24.10 to get it working again 👎

@mike12806 , how did you downgrade the k3s version?

**Comment by dgadelha** [comment]
Workaround: upgrade to Rancher v2.7.2-rc7

**Comment by mike12806** [comment]
> > Had the same behavior, had to downgrade back to K3S 1.24.10 to get it working again 👎
> 
> @mike12806 , how did you downgrade the k3s version?

@dgadelha  downgraded by changing the version in the k3s master and worker node plans under the upgrade controller page in Rancher

**Comment by mike12806** [comment]
> #38701

@dgadelha is this resolved in Rancher v2.7.2 with K3S 1.25 and above? I'd like to upgrade to 1.25.x at some point but am a bit gun shy

**Comment by dgadelha** [comment]
> > #38701
> 
> @dgadelha is this resolved in Rancher v2.7.2 with K3S 1.25 and above? I'd like to upgrade to 1.25.x at some point but am a bit gun shy

Yes, we're on 2.7.2 and it's working fine on 1.25 clusters.

![image](https://user-images.githubusercontent.com/10081640/232500065-3e76ab77-b920-47e3-a66a-1c99a62aa292.png)

**Comment by tbernacchi** [comment]
Same here. I've just import a GKE cluster 1.26.3-gke.1000 on Rancher 2.7.0.  
<img width="1266" alt="Screen Shot 2023-05-13 at 17 49 44" src="https://github.com/rancher/rancher/assets/26934246/2746dc02-0af5-420a-bc4b-b4e10705e982">

**Comment by tbernacchi** [comment]
Upgrade to Rancher v2.7.3 solved to me. My Rancher it's running in top of GKE: v1.24.10-gke.2300

<img width="1266" alt="Screen Shot 2023-05-13 at 18 26 51" src="https://github.com/rancher/rancher/assets/26934246/12d60076-4403-4bb9-a412-cacbfc1c00d6">

**Comment by asloan7** [comment]
closing, resolved in Rancher v2.7.2

**Comment by gchait** [comment]
still happening in eks 1.26 rancher 2.7.5

**Comment by saarang1995** [comment]
> Workaround: upgrade to Rancher v2.7.2-rc7

Just confirming. I tried to upgrade Rancher to v2.7.6 (latest at this time) and it resolved the issue.

**Comment by aellert** [comment]
I've just upgraded to rancher 2.7.9 and this problem comes back...

**Comment by bashilias** [comment]
Very unprofessional for you to close this issue with offering a permanent solution or point to the commit where the solution is located.

**Comment by TrixTeam** [comment]
Also started after we upgraded to 2.8.5

**Comment by w3z315** [comment]
Started after an upgrade to 2.8.5 - since then not even a downgrade works anymore. I'm running a local k3s cluster (multiple nodes) k3s 	v1.29.7+k3s1
