### ISSUE TITLE
Publishing Images to Prime Registry for Chart OOB releases

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#40836]
Currently, when we do out-of-band Chart releases, the necessary images are published to Dockerhub as part of the development/release process. They are not mirrored into the Rancher Prime registry.

Currently, adding in new images to the SUSE registry is only available using artifacts published as part of a Rancher release. The out of band release process that exists will publish new Docker images in Dockerhub and extends feature functionality to existing Rancher Manager installs.

When releasing something out of band from a Rancher release, these images are not being published into the SUSE registry. No image-digest file is generated.

The "ask"
We need to automate the process to be able to have the images of an OOB release being pushed into prime registry without needing the manual monitoring.

**Comment by PennyScissors** [comment]
It was pointed out in the confluence doc that a potential solution is to cut a "dummy" tag in rancher/rancher to generate the digests file EIO needs. This would be the most straight forward solution as we can tag a x.x.x-rc0 (where x.x.x is whatever next rancher version we are releasing next to avoid the maintenance overhead of having specific tags for this specifically) after a chars OOB release to generate that file for EIO. However, it is important to not this case will generate digests for all images including the charts that were last released and newly released in the OOB release. Would this still work for EIO, or do they need a "filtered" digests file that contains the images of the charts that were released OOB specifically? (this would involve more work to do it right, but doable)

**Comment by rohitsakala** [comment]
Tasks Ahead 
- Remove the Github Action code from dev-v2.7 
- Test if it works even if there is no changes in regsync file.

**Comment by rohitsakala** [comment]
1. Implemented Solution 3 in this - https://confluence.suse.com/display/EN/Rancher+Prime+Image+Publishing+for+OOB+Chart+Releases after consulting the EIO team for Charts OOB releases.
2. PRs - https://github.com/rancher/charts-build-scripts/pull/95
