### ISSUE TITLE
Deploy on GKE Autopilot denied

### ISSUE THREAD

**Issue by cachak** [rancher/rancher#40845]
I create rancher with helm : 
helm upgrade --install rancher rancher-stable/rancher \
  --namespace cattle-system \
  --create-namespace \
  --set hostname=rke.mydomain.tld \
  --set ingress.tls.source=letsEncrypt \
  --set bootstrapPassword=mypassword \
  --set letsEncrypt.email=admin@myindomain.tld \
  --set ingress.extraAnnotations.'cert-manager\.io/cluster-issuer'=letsencrypt-prod \
  --set ingress.ingressClassName=nginx \
  --set addLocal=true \
  --set ingress.enabled=true \

but pods not ready : 
rancher-56bcfcf8b6-f47c8   0/1

i got logs : 

E0310 09:50:50.227419      33 leaderelection.go:334] error initially creating leader election record: configmaps is forbidden: User "system:serviceaccount:cattle-system:rancher" cannot create resource "configmaps" in API group "" in the namespace "kube-system": GKE Warden authz [denied by managed-namespaces-limitation]: the namespace "kube-system" is managed and the request's verb "create" is denied
2023/03/10 09:50:50 [INFO] Waiting for initial data to be populated
2023/03/10 09:50:52 [INFO] Waiting for initial data to be populated
E0310 09:50:52.948747      33 leaderelection.go:334] error initially creating leader election record: configmaps is forbidden: User "system:serviceaccount:cattle-system:rancher" cannot create resource "configmaps" in API group "" in the namespace "kube-system": GKE Warden authz [denied by managed-namespaces-limitation]: the namespace "kube-system" is managed and the request's verb "create" is denied

Regards,

Sahir

**Comment by cbron** [comment]
Autopilot is not supported for Rancher to be deploy on, or for Rancher to deploy: https://ranchermanager.docs.rancher.com/v2.6/pages-for-subheaders/install-upgrade-on-a-kubernetes-cluster#kubernetes-cluster
