### ISSUE TITLE
[BUG] Azure AD Authentication Update Fails

### ISSUE THREAD

**Issue by boriscosic** [rancher/rancher#40848]
**Rancher Server Setup**
- Rancher version: 2.6.11
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): EKS
- Proxy/Cert Details: NA

**Information about the Cluster**
- Kubernetes version: 1.22
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): EKS

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Admin

**Describe the bug**
Upgrading Azure AD Authentication throws `{"baseType":"error","code":"ServerError","message":"authority does not have two segments","status":500,"type":"error"}`

Tried to update endpoints manually to V2 I get `AADSTS901002: The 'resource' request parameter is not supported.` 

**To Reproduce**
Click Update Endpoint. 

**Result**
Azure AD endpoints updated

**Expected Result**
Error above

**Screenshots**
See trace from network request

**Additional context**
Confirmed permissions were correctly set on the application https://ranchermanager.docs.rancher.com/v2.6/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/authentication-config/configure-azure-ad#3-set-required-permissions-for-rancher. 

From what I can tell https://www.ibm.com/support/pages/aadsts901002-resource-request-parameter-not-supported resource is now scopes, is there any other way to change this or manually doing what the Update button is doing.

**Comment by dasarinaidu** [comment]
@boriscosic Can you provide more details on this issue : 

1. From what rancher version were they upgrading from?
2. It was mentioned Upgrading Azure AD Authentication throws errors - can you confirm that the endpoint upgrade itself appeared successful in the UI?
3. It was mentioned upgrading endpoints manually throws a different error - how are you trying to upgrade manually is it via kubectl or any other means?
4. What endpoints were used to enabled azure AD - Standard/China/Custom?
5. Can you provide any additional logs when you get the error?

**Comment by boriscosic** [comment]
Thanks @dasarinaidu ,

1) Upgrading from 2.6.5
2) The upgrade didn't appear successful in the UI nor could I update custom endpoints. As per above:

Click Upgrade, throws {"baseType":"error","code":"ServerError","message":"authority does not have two segments","status":500,"type":"error"}

Upgrading endpoint manually, throws AADSTS901002: The 'resource' request parameter is not supported.

3) I tried to update custom endpoints manually, first via UI, which threw an error. Then I used terraform, see below for that path.
4) Custom
5) I will look for this

Since we install rancher with terraform I added the new endpoints in there and set the annotation `auth.cattle.io/azuread-endpoint-migrated` set on authconfig azuread. 

We are now getting a server error I have to dig into. Part of the problem was, we had api access as Delegated (With admin consent) instead of Application. Once we changed it to Application we couldn't admin consent due to org permissions https://ranchermanager.docs.rancher.com/v2.6/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/authentication-config/configure-azure-ad#3-set-required-permissions-for-rancher. 

Previous API worked with Delegated and Admin consent, just want to confirm that new API requires Application AND Admin consent? Is it possible to display a consent modal, for us its not coming up?

I will dig into further error logs.

**Comment by maxsokolovsky** [comment]
@boriscosic, yes, for the new Azure AD flow Rancher needs Application type permissions (for example, `Directory.Read.All`) and admin consent. Without consent, the permissions aren't granted.

**Comment by boriscosic** [comment]
@maxsokolovsky 
Please see my screenshot, I've added Directory.Read.All, User.Read.All, Group.Read.All as Application and delegated admin. 

From the logs:
2023/03/14 17:20:50 [ERROR] error syncing 'u-vmekimcbd2': handler mgmt-auth-userattributes-controller: authority does not have two segments, requeuing
2023/03/14 17:21:32 [ERROR] API error response 500 for POST /v3-public/azureADProviders/azuread?action=login. Cause: authority does not have two segments
2023/03/14 17:22:50 [ERROR] Error refreshing token principals, skipping: authority does not have two segments
2023/03/14 17:22:50 [ERROR] error syncing 'u-vmekimcbd2': handler mgmt-auth-userattributes-controller: authority does not have two segments, requeuing

![Screenshot 2023-03-14 at 11 25 26 AM](https://user-images.githubusercontent.com/91231/225088076-8ca72452-d293-4b7b-8a11-c1cb6514dd82.png)

**Comment by maxsokolovsky** [comment]
@boriscosic, Rancher is refusing to upgrade because it recognizes the old Graph Endpoint as `https://graph.windows.net/` (with the trailing forward slash). The docs list the endpoints exactly: https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/authentication-config/configure-azure-ad#global

**Comment by boriscosic** [comment]
Thanks @maxsokolovsky got it all upgraded! Making sure the endpoints line up with above link and **especially** with trailing slashes was the answer.
