### ISSUE TITLE
Boolean value not saved for upgrade in catalog

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4085]
Version - master 3/22

Steps to Reproduce: 
1.  Create a catalog template that includes the "type = boolean", default = true
2.  Create another version (so there will be an upgrade path)
3.  Create the catalog using version 1 and set the boolean to false
4.  Click on upgrade for the stack and select version 2

Results: Notice the boolean field has nothing selected.

Expected: Should have False selected

**Comment by vincent99** [comment]
String to actual boolean conversion...

**Comment by tfiduccia** [comment]
Version - master 6/17
Verified fixed
