### ISSUE TITLE
[BUG] Logging install on k8s 1.25 possible to have different versions when install fails due to psps

### ISSUE THREAD

**Issue by ronhorton** [rancher/rancher#40863]
**Rancher Server Setup**
- Rancher version: `2.7.2-rc5`
- Installation option (Docker install/Helm Chart): `helm`
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): `rke1`
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: `1.25`
- Cluster Type (Local/Downstream): `downstream rke1 ubuntu ec2`
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: `admin`

**Describe the bug**
possible to have rancher-logging:102.0.0+up3.17.10 installed along with rancher-logging-crd:100.1.3+up3.17.7

**To Reproduce**
1. install rancher logging v2 with 'enable psps' option
2. install will fail
3. rancher logging crd is installed
4. reinstall logging w/out psps enabled

**Result**
rancher-logging:102.0.0+up3.17.10 installed along with rancher-logging-crd:100.1.3+up3.17.7

**Expected Result**
matching versions

**Screenshots**

<img width="899" alt="2023-03-13_16-33-39" src="https://user-images.githubusercontent.com/89212856/224828824-ad0621c4-83ae-4d7e-a366-157312964245.png">

**Additional context**
all charts & crds should be versioned 102 for 2.7.2
p0 test cases still pass

**Comment by stormqueen1990** [comment]
I was unable to reproduce the specific issue in this scenario. After some offline discussion, there was a sense of some confusion caused by the fact that the CRD chart succeeded installation but not the main chart, which caused the UI to render the Logging configuration tab. This UI improvement has its own issue and is being tracked through rancher/dashboard#8434.

**Comment by ronhorton** [comment]
This specific use case was invalidated by https://github.com/rancher/dashboard/issues/8528
`No longer see 'enable psp' switch during install on 1.25 cluster.`


1. manually changed to 'true' in yaml
2. installed
3. crd installed and logging errored re: psps
4. Updated logging install with 'false' (default in yaml)
 `logging installed successfully`

test version: rancher `v2.7.2-rc8`
