### ISSUE TITLE
[RFE] please support k3s fine tuning after installation

### ISSUE THREAD

**Issue by harridu** [rancher/rancher#40868]
After installing a managed cluster based on k3s it is highly difficult to get rid of the "goodies" (traefik, klipper-lp, others?) later. And it is not clear at all that these changes are persistent. 

Please provide check boxes in Rancher to disable (or enable) these features after the cluster has been deployed.

**Comment by harridu** [comment]
@bpedersen2 
You mean cluster management --> mycluster --> burger menu --> edit config? Maybe I am too blind to see, but I haven't found it yet.

**Comment by bpedersen2** [comment]
![screenshot](https://user-images.githubusercontent.com/5336494/227141676-5d251a3a-0a40-4f35-b665-b47cf5547cf5.png)

**Comment by bpedersen2** [comment]
See the  "system services"

**Comment by harridu** [comment]
![snapshot MqgVif](https://user-images.githubusercontent.com/832164/227727374-31a7aea8-455c-4424-ac14-b3bea7994ff8.png)

Well?

**Comment by harridu** [comment]
@bpedersen2 , can you confirm that the "System Services" checkboxes are gone after the cluster configuration has been saved in Rancher? Is this on purpose?

**Comment by bpedersen2** [comment]
No, they are there (in 2.7.1). Please give exact versions used and how you configured the downstream cluster, otherwise it is hard to say if this was a bug that has been fixed.

**Comment by harridu** [comment]
I have upgraded K3s to 1.24.10. For this version I see the expected System Services checkboxes. 

Thank you for your support.
