### ISSUE TITLE
Service drop-down field does not work properly in catalog

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4086]
Version - master 3/22

Steps to Reproduce: 
1.  Create three different stacks with at least 1 service inside each (make sure they are different names)
2.  Create a catalog with type "service"
3.  View details for that catalog
4.  Go to the Service drop-down and select a service

Results: It does not select the service you originally clicked on.  It selects a different one in the list

Expected: Should select the service I clicked on and not some other random service in list.

**Comment by deniseschannon** [comment]
Also, even if you correct your selection, it still selects the original (incorrect) service.

**Comment by tfiduccia** [comment]
Version - master 3/23
