### ISSUE TITLE
[BUG] Can't re-enable auth provider after setting "enabled" to false in auth config

### ISSUE THREAD

**Issue by maxsokolovsky** [rancher/rancher#40878]
**Rancher Server Setup**
- Rancher version: v2.7.2

**Describe the bug**
Admins can edit Auth Configs and thus set the `enabled` field to false. This is a valid use-case that allows admins to turn a provider off and re-enable it. Normally, admins should do this via UI, but we also support this direct edit to auth config (also via Terraform).
This affects most providers - any that lookup the config and the application secret on testAndApply.
For example, GitHub, Azure AD (both old and new flows), Google.

**To Reproduce**
1. Enable an auth provider that needs an application secret, such as GitHub.
2. Edit its auth config and set `enabled` to false.
3. Observe that Rancher now does not have any configured auth provider.
4. Try to enable the provider again by providing all required data and the application secret.

**Result**
Can't re-enable the provider. Observe an error similar to this: "application secret not found".

**Expected Result**
Re-enable the provider even after settings its `enabled` field to false.

**Screenshots**

**Additional context**
This issue occurs because on setup, Rancher looks up a (usually bare) auth config and finds a non-empty value for the field application secret (named differently for each provider). If the value exists, then Rancher tries to fetch the secret. For new setups, the value is missing, but when admins edit an auth config and set `enabled` to false, the rest of the auth config still holds its values, including one for the application secret. But when an auth provider is disabled, cleanup runs (unless the provider is locked), which deletes the application secret itself.

**Comment by dasarinaidu** [comment]
I reproduce the issue on v2.7-head(2.7.2-rc6)

**Reproduction Steps:**

1. Provision rancher v2.7-head(2.7.2-rc6)
2. Connect to Auth (Azure)
3. Make sure Azure Login is working fine (Login and Re-login)
4. Annotate azuread by kubectl(local cluster)
5. run kubectl edit authconfig azuread
6. Edit : `enabled: false`
7. Check for the application behavior, Secrets and AuthProvider

**Actual:**
a.  App disconnected from the Azure Auth
b.  Secrets deleted
c. Unable to Login back with Azure
d. Try to enable the provider again but the user cannot connect to Azure
     UI error : failed to fetch Azure AD Config from Kubernetes
 Logs : 
```
023/03/16 20:08:27 [ERROR] Failed to fetch Azure AD Config from Kubernetes: error getting secret cattle-global-data:azureadconfig-applicationsecret secrets "azureadconfig-applicationsecret" not found
2023/03/16 20:08:27 [ERROR] Failed to delete the Azure AD access token secret from Kubernetes
```


8. Update the Flag to True ( enabled: true )
9. The user can see the AzureAD is connected 
10. Try to Login back with Azure test user 

**Actual:**
a. User cannot login back
b. No secrets were existed
c. Login throwing a 500 error

`API error response 500 for POST /v3-public/azureADProviders/azuread?action=login. Cause: error getting secret cattle-global-data:azureadconfig-applicationsecret secrets "azureadconfig-applicationsecret" not found`

**Comment by maxsokolovsky** [comment]
# QA Testing

For this issue, test at least one provider from each category: LDAP, OIDC, SAML, OAuth.

## Kubectl
Enable the provider.
Fetch its auth config - `kubectl get authconfig [name] -o yaml`.
Notice that it has not just the essential fields, like metadata, but also provider-specific fields, like endpoints and others.
Also take note of the value of the `management.cattle.io/auth-provider-cleanup` annotation. It should be `unlocked`.
Also notice that you have provider-specific secrets in the `cattle-global-data` namespace and other resources elsewhere.
Edit the auth config - set `enabled` to false and save.
You should immediately see that those provider-specific resources are gone.
Fetch the auth config again and notice that most all of its provider-specific fields are gone. There are only basic fields.
Enable the provider again. Edit the config and set the cleanup annotation value to `user-locked`.
Disable the provider by flipping `enabled` to false again. Notice that the UI shows the provider as disabled. But the secrets are still there. Fetch the auth config and notice that all its fields are there, nothing got reset or removed.
Change `enabled` back to true and save. Refresh the page and notice that the provider works as before.

## UI
Perform the same tests, but disable the config only through the UI with the button. Keep inspecting the config using kubectl where needed but don't edit the `enabled` field.

## Terraform
Enable the provider using Terraform. For example,
```
resource "rancher2_auth_config_azuread" "azuread" {
  tenant_id          = var.tenant_id
  application_id     = var.application_id
  application_secret = var.application_secret

  rancher_url    = "${var.api_url}/verify-auth-azure"
  graph_endpoint = "https://graph.microsoft.com"
  auth_endpoint  = "https://login.microsoftonline.com/${var.tenant_id}/oauth2/v2.0/authorize"
  token_endpoint = "https://login.microsoftonline.com/${var.tenant_id}/oauth2/v2.0/token"
}
```

Perform the same tests, but disable the config only through Terraform by **removing the resource itself and applying your configuration**. Keep inspecting the config using kubectl where needed but don't edit the `enabled` field.

**Comment by anupama2501** [comment]
Verified on v2.7-head `2b2ed44`
Auth providers: Keycloak OIDC, okta
1. Create a rancher server on v2.7-head
2. Enable keycloak auth provider from UI
3. Disable auth provider and re enable auth provider from UI - works as expected 
Repeat the same steps for Okta

Terraform auth validations:
Repeated the steps for openldap and azure AD via terraform:

- Enabled auth via terraform
- Disabled auth via terraform 
- Re enabled auth via terraform.

**Comment by dasarinaidu** [comment]
Validated this issue on `v2.7-41b2cf3ab63fb8b3b90076a29cecb092bdc8d83d-head`,  below tests cases were executed and all of them are passed. I am closing this ticket.

**From UI:**
    1. Enable Auth; Disable Auth from UI; Re-enable Auth from UI
    2. Enable Auth; → Set to user-locked → Disable Auth from UI; → verify if it is still user-locked →  Re-enable Auth from UI
    3. Enable Auth; → Set to user-locked → Disable Auth from UI; → verify if it is still user-locked →  Re-enable Auth from UI
    4. Enable Auth using AUTH1; Set to user-locked → Disable Auth from UI; Re-enable Auth from UI using AUTH2

**Actions from kubectl :**
    1. Enable Auth From Rancher UI; disable (enabled: false) through kubectl; re-enable from Rancher UI
    2. Enable Auth From Rancher UI; → Set to user-locked → disable (enabled: false) through kubectl; re-enable from Rancher UI

**Actions from Terraform:**
    1. Enable Auth From terraform; disable through terraform; re-enable from terraform

**Verifying secrets :**
    1. Enable Auth From Rancher UI; → user-locked → Disable Auth → verify the secrets are NOT deleted → Re-enable Auth
    2. Enable Auth From Rancher UI; → rancher-locked → disable (enabled: false) in Authconfig in kubectl →  verify the secrets are NOT deleted

**Comment by maxsokolovsky** [comment]
# Release note
Rancher now behaves the same when admins disable an auth provider. Whether they disable through the UI, or by deleting the auth config in Terraform, or switch the config's `enabled` field to false in API - Rancher performs the cleanup of resources associated with the auth provider and resets all fields of the corresponding auth config.
