### ISSUE TITLE
Service drop-down not highlighted when tabbing for usability

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4087]
Version - master 3/22

Steps to Reproduce: 
1.  Add a stack and a bunch of services, go to main stack page or stack detail page
2.  Tab to highlight each field for usability

Results:  The Add Service drop-down (that allows me to select Load Balancer, Service Alias, External Service) is not highlighted when I tab to it.  The little blue outline is not showing up

Expected: Blue outline should show up.

**Comment by tfiduccia** [comment]
This seems to be a problem for that type of drop-down.  I noticed in the Add Load Balancer screen the drop-down for Protocol & Access are having that same problem

**Comment by vincent99** [comment]
Also made the menu go towards the left (aligned with the right-edge) instead of out into space.

![image](https://cloud.githubusercontent.com/assets/753917/13971314/7d70c74e-f04c-11e5-928a-2ef0e1ac37d8.png)

**Comment by tfiduccia** [comment]
Version - master 3/23
Verified fixed
