### ISSUE TITLE
[BUG] Machine stuck in "Deleting" state

### ISSUE THREAD

**Issue by fheslouin** [rancher/rancher#40875]
**Rancher Server Setup**
- Rancher version: `v2.7.1`
- Installation option : Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
     - `v1.24.10+k3s1`
- Proxy/Cert Details: None

**Information about the Cluster**
- Kubernetes version: `v1.24.8+rke2r1 `
- Cluster Type: Downstream
   - If downstream, what type of cluster? Infrastructure Provider, using a custom docker-machine driver:
     - [docker-machine-driver-outscale](https://github.com/outscale/docker-machine-driver-outscale)

**User Information**
- What is the role of the user logged in? Admin

**Describe the bug**
I'm creating a cluster with the Help of this [Helm Chart](https://github.com/outscale/osc-k8s-rancher/tree/main/osc-rke2-cluster-template/charts) using [docker-machine-driver-outscale](https://github.com/outscale/docker-machine-driver-outscale) (version 0.2.0). 

* Cluster creation : 
  * Worker is faster to deploy than controller, so sometime the worker get deleted before the controller is up&running. In that case, the worker get stuck in "Deleting" state

* Cluster removal : 
  * This is done with an `helm uninstall`, usually both Machine (node) get stuck in "Deleting" state, no matter if I use Helm chart or Rancher Web UI. The underlying VM is however deleted

**To Reproduce**
  * Install outscale docker driver version 0.2.0
  ![image](https://user-images.githubusercontent.com/3833063/225067149-abfc983c-25c4-4b2f-b162-adf24222048b.png)
    * https://github.com/outscale/docker-machine-driver-outscale/releases/download/v0.2.0/docker-machine-driver-outscale_0.2.0_linux_amd64.zip
    * https://oos.eu-west-2.outscale.com/rancher-ui-driver-outscale/v0.2.0/component.js
    * bb539ed4e2b0f1a1083b29cbdbab59bde3efed0a3145fefc0b2f47026c48bfe0
    * oos.eu-west-2.outscale.com
  * Configure a cloud credentials for Outscale
  * Create a cluster with the Outscale node driver (wait for the node to be ready)
  * Remove the cluster

**Result**

Machine is in "Deleting" state

```
apiVersion: cluster.x-k8s.io/v1beta1
kind: Machine
metadata:
  annotations:
    machine.cluster.x-k8s.io/exclude-node-draining: 'true'
  creationTimestamp: '2023-03-14T15:02:29Z'
  deletionGracePeriodSeconds: 0
  deletionTimestamp: '2023-03-14T15:55:44Z'
  finalizers:
    - machine.cluster.x-k8s.io
  generateName: fhn-dev-rancher-dev-zone-dev2-control-5fdcdc86dd-
  generation: 4
  labels:
    cattle.io/os: linux
    cluster.x-k8s.io/cluster-name: fhn-dev-rancher-dev-zone-dev2
    cluster.x-k8s.io/control-plane: 'true'
    cluster.x-k8s.io/deployment-name: fhn-dev-rancher-dev-zone-dev2-control
    machine-template-hash: '19856474288'
    rke.cattle.io/cluster-name: fhn-dev-rancher-dev-zone-dev2
    rke.cattle.io/control-plane-role: 'true'
    rke.cattle.io/etcd-role: 'true'
    rke.cattle.io/machine-id: 2b85d046acdf976a09d093b35bdc327e792dd3868d8bf1c4031a97b552842de
    rke.cattle.io/rke-machine-pool-name: control
  name: fhn-dev-rancher-dev-zone-dev2-control-5fdcdc86dd-5cnns
  namespace: dev-zone-dev2
  ownerReferences:
    - apiVersion: cluster.x-k8s.io/v1beta1
      blockOwnerDeletion: true
      controller: true
      kind: MachineSet
      name: fhn-dev-rancher-dev-zone-dev2-control-5fdcdc86dd
      uid: 4db62934-5cc0-4f9a-a748-2a58e6117b01
  resourceVersion: '2549832'
  uid: 844ef00e-4221-41a4-ae55-3c3225cd1a2e
spec:
  bootstrap:
    configRef:
      apiVersion: rke.cattle.io/v1
      kind: RKEBootstrap
      name: fhn-dev-rancher-dev-zone-dev2-bootstrap-template-r6668
      namespace: dev-zone-dev2
      uid: 3b869958-8bea-4383-8ce5-ca0f34ab4d98
    dataSecretName: fhn-dev-rancher-dev-zone-dev2-bootstrap-template-r6668-ma-7c6bf
  clusterName: fhn-dev-rancher-dev-zone-dev2
  infrastructureRef:
    apiVersion: rke-machine.cattle.io/v1
    kind: OutscaleMachine
    name: fhn-dev-rancher-dev-zone-dev2-control-b25bf7ee-25sbx
    namespace: dev-zone-dev2
    uid: 52da89cd-b663-468f-982e-445739e81b0b
  nodeDeletionTimeout: 10s
  providerID: aws:///eu-west-2a/i-d874bc09
```

**Expected Result**
The Machine is deleted

**Screenshots**
![image](https://user-images.githubusercontent.com/3833063/225065646-b91dee81-ed65-4aec-b8bb-d64ab34bc5c8.png)

**Comment by fheslouin** [comment]
We finally managed  to solve this issue. 

I spotted that I did not have this issue with other CNI (canal) the issue happened with Cilium mainly.

Here is a specific configuration for Ubuntu 22.04 published on [Cilium doc](https://docs.cilium.io/en/stable/operations/system_requirements/#systemd-based-distributions)

---
_systemd-based distributions_
Some distributions need to be configured not to manage “foreign” routes. This is the case in Ubuntu 22.04, for example (see [GitHub issue 18706](https://github.com/cilium/cilium/issues/18706)). This can usually be done by setting
```

ManageForeignRoutes=no
ManageForeignRoutingPolicyRules=no
```

**Comment by lindhe** [comment]
I'm having a similar issue.

I find what you are referring to in [the v1.13 docs]https://docs.cilium.io/en/v1.13/operations/system_requirements/#systemd-based-distributions) but not in [the v1.14 docs](https://docs.cilium.io/en/v1.14/operations/system_requirements/) onward. Wonder if this has been resolved for newer versions of Cilium. Do you know which version you were on when you had the issue?
