### ISSUE TITLE
[BUG] Error `waiting for dynamic schema to be populated for machine pool` is seen initially when creating an RKE2 cluster, before the cluster proceeds provisioning

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#40886]
**Rancher Server Setup**
- Rancher version: 2.7-head commit id: `cd1a716 `
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2 - `v1.24.10+rke2r1`

**Information about the Cluster**
- Kubernetes version: `v1.25.7+rke2r1`
- Cluster Type (Local/Downstream): Downstream - 1 etcd+cp and 3 worker nodes

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): Admin

**Describe the bug**
[BUG] Error `waiting for dynamic schema to be populated for machine pool` is seen initially when creating an RKE2 cluster, before the cluster proceeds provisioning

**To Reproduce**

- Deploy an RKE2 cluster.
- Error `waiting for dynamic schema to be populated for machine pool` is seen initially when creating an RKE2 cluster, before the cluster proceeds provisioning

**Result**
<img width="612" alt="Screen Shot 2023-03-14 at 9 45 15 PM" src="https://user-images.githubusercontent.com/26032343/225209095-9ae5d6f5-e88a-46b7-bd74-4045c434e02f.png">

- Rancher server logs
```
2023/03/15 04:45:09 [ERROR] error syncing 'fleet-default/sowmya-rke2-3': handler rke-cluster: waiting for dynamic schema to be populated for machine pool sowmya-rke2-3-pool1, requeuing
```

**Expected result:**
Initial Error should not be seen on the cluster. The cluster must go into Provisioning directly.

**Comment by thaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.7-head 8835c43
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: rke2

----------

### Testing: ###

Tested this issue with the following steps:
1. Deploy an rke2 cluster
2. Verify there are no errors while cluster is provisioning
3. Verify cluster comes up active

**Result**
The error is no longer seen but I did notice that in 2.7.0, once creating the cluster, the cluster status goes from `provisioning` to `updating`. In 2.7-head, I noticed the cluster went into `reconciling` first and then to `updating` @jakefhyde with the new dynamic schema changes, is it possible to address this issue?

**Comment by thaneunsoo** [comment]
Sounds good, new ticket created [here](https://github.com/rancher/rancher/issues/40911)
Closing this issue as new issue is being tracked in ticket above.
