### ISSUE TITLE
[BUG] [2.6 backport] Can't re-enable auth provider after setting "enabled" to false in auth config

### ISSUE THREAD

**Issue by maxsokolovsky** [rancher/rancher#40896]
Backport https://github.com/rancher/rancher/issues/40878

**Comment by maxsokolovsky** [comment]
Confirmed that the issue occurs on v2.6.11.

**Comment by maxsokolovsky** [comment]
QA testing steps are the same as those for the v2.7 issue: https://github.com/rancher/rancher/issues/40878#issuecomment-1474292589

**Comment by dasarinaidu** [comment]
Validated this issue on `v2.6-85315a04c4975ff8aeea497d97686f24275be791-head` , below tests cases were executed and all of them are passed. I am closing this ticket.

**From UI:**
1. Enable Auth; Disable Auth from UI; Re-enable Auth from UI
2.  Enable Auth using AUTH1; Set to user-locked → Disable Auth from UI; Re-enable Auth from UI using AUTH2

**Actions from kubectl :**
1. Enable Auth From Rancher UI; disable (enabled: false) through kubectl; re-enable from Rancher UI
2. Enable Auth From Rancher UI; → Set to user-locked → disable (enabled: false) through kubectl; re-enable from Rancher UI

**Actions from Terraform:**
1. Enable Auth From terraform; disable through terraform; re-enable from terraform

**Verifying secrets :**
1. Enable Auth From Rancher UI; → user-locked → Disable Auth → verify the secrets are NOT deleted → Re-enable Auth
