### ISSUE TITLE
[BUG] The `Default Pod Security Policy` value is not restored after restoring the snapshot

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#40899]
**Rancher Server Setup**
- Rancher version: v2.7.2-rc6
- Installation option (Docker install/Helm Chart): docker install 
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): 
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: RKE1 1.24 & RKE2 1.24
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:
 

**Describe the bug**

After restoring the etcd backup on a downstream cluster, the `Default Pod Security Policy` selection is not reset to the value in the backup. 
This happens to both RKE1 and RKE2 node-driver clusters. 

**To Reproduce**

- create an RKE1/RKE2 1.24  node-driver cluster 
- enable PSP and set `Default Pod Security Policy` to `unrestricted`
- take a snapshot  
- edit the cluster to change `Default Pod Security Policy` to "my-psp-copy"
- restore the snapshot 

**Result**

Go to the editing page or view the cluster in API, we can see that the `Default Pod Security Policy` is still "my-psp-copy", not the one in the backup. 

**Expected Result**

The `Default Pod Security Policy` should be set to whatever value in the backup

**Comment by jiaqiluo** [comment]
can be validated in v2.7-head

**Comment by markusewalker** [comment]
**QA TEST PLAN**

**Scenarios**
|Scenario|Test Case|
|---|---|
|1|As a standard user, provision a downstream RKE1 v1.24 node driver cluster with PSP set to `unrestricted`, take an etcd snapshot, update PSP to a custom PSP, upgrade cluster to v1.25 with PSA set to `rancher-restricted`, restore snapshot and validate PSP is set to `unrestricted`
|2|As a standard user, provision a downstream RKE2 v1.24 custom cluster with PSP set to `restricted`, take an etcd snapshot, update PSP to a custom PSP, upgrade cluster to v1.25 with PSA set to `rancher-restricted`, restore snapshot and validate PSP is set to `unrestricted`|
|3|As a standard user, provision a downstream RKE2 v1.24 node driver cluster with PSP set to `restricted` and PSA set to `rancher-restricted`, take an etcd snapshot, update PSP to a custom PSP, upgrade cluster to v1.25, restore snapshot and validate PSP is set to `unrestricted`|

**Comment by markusewalker** [comment]
Validated that this is addressed on `v2.7-head` https://github.com/rancher/rancher/commit/2b2ed443065a9f38c4c5764461be33823eb6fec3.

**ENVIRONMENT DETAILS**
- Rancher install: Docker
- Rancher version: `v2.7-head` https://github.com/rancher/rancher/commit/2b2ed443065a9f38c4c5764461be33823eb6fec3
- Browser: Chrome

**TEST RESULT**
|Scenario|Test Case|Result
|---|---|---|
|1|As a standard user, provision a downstream RKE1 v1.24 node driver cluster with PSP set to `unrestricted`, take an etcd snapshot, update PSP to a custom PSP, restore snapshot and validate PSP is set to `unrestricted`|:white_check_mark:|
|2|As a standard user, provision a downstream RKE2 v1.24 custom cluster with PSP set to `restricted`, take an etcd snapshot, update PSP to a custom PSP,  restore snapshot and validate PSP is set to `restricted`|:white_check_mark:|
|3|As a standard user, provision a downstream RKE2 v1.24 node driver cluster with PSP set to `restricted` and PSA set to `rancher-restricted`, take an etcd snapshot, update PSP to a custom PSP, restore snapshot and validate PSP is set to `restricted`|:white_check_mark:|

**VALIDATION STEPS**

**Scenario 1**
1. As an admin user, navigated over to Cluster Management > Advanced > Pod Security Policy Templates > Add Policy Template.
2. Created policy `mew-new-policy` with all of the default values.
3. Logged out and logged back in as a standard user.
4. Navigated over to Cluster Management > Create.
5. Provisioned a downstream RKE1 v1.24 node driver with PSP set to `unrestricted`.
6. Validated that the cluster and nodes came up as `Active` in Cluster Management and Cluster Explorer.
7. Validated that all the pods in the system project page are up and `Active`.
8. Took an etcd snapshot of the cluster as is; validated that it created successfully
9. Edited the cluster's configuration and changed PSP from `unrestricted` to `mew-new-policy`.
10. Validated that the cluster YAML reflects the new PSP.
11. Restored the previously taken snapshot with options cluster configuration, K8s version and etcd.
12. Validated that the cluster YAML has the PSP set to `unrestricted` and NOT `mew-new-policy`.
________
**Scenario 2**
1. Repeated scenario 1, but used RKE2 v1.24 custom cluster with PSP set to `restricted` when initially deploying the cluster.
2. Validated that all steps are successful as indicated in scenario 1.
_______
**Scenario 3**
1. Repeated scenario 1, but used RKE2 v1.24 node driver with PSP set to `restricted` AND PSA set to `rancher-restricted` when initially deploying the cluster.
2. Validated that all steps are successful as indicated in scenario 1.
