### ISSUE TITLE
DigitalOcean doesn't remove hosts that have errorred out.

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#409]
Version v0.14.2 

DO doesn't successfully remove hosts that have errored out. When a machine errors out, we never see the "You will want to check the provider to make sure the machine and associated resources were properly removed." message anymore. 

The machine is typically created in DO and the host in the UI shows an error message.

When a user deletes it, you don't realize that it doesn't succeed in deleting in DO.

Logs of attempt to purge machine.

```bash
time="2015-04-02T18:24:53Z" level=info msg="Purging Machine" eventId="a6c64048-fd88-4435-9f0f-c655bbfc1171" resourceId=1ph14 
time="2015-04-02T18:24:53Z" level=warning msg="Unable to find machineDir.  Nothing to do" err="MachineDir field not available for machine [1ph14]." machineDir= resourceId=1ph14 
```

**Comment by will-chan** [comment]
please re-test as we are using DM 0.5.x

**Comment by deniseschannon** [comment]
With docker-machine v0.5.x, adding hosts is much more stable and unable to get an errored out host. Closing until I can reproduce.
