### ISSUE TITLE
[BUG] Creating an EKS cluster results in an error "Error creating stack with VPC template: stack failed to create: Resource creation cancelled"

### ISSUE THREAD

**Issue by TangStone** [rancher/rancher#40903]
**Rancher Server Setup**
- Rancher version: v2.7-head
- Installation option (Docker install):
- Proxy/Cert Details: None

**User Information**
- What is the role of the user logged in? (Admin)
 
**Describe the bug**

Creating an EKS cluster results in an error "Error creating stack with VPC template: stack failed to create: Resource creation cancelled"

**To Reproduce**
- Add an Amazon Cloud Credentials with the necessary permissions to create an EKS cluster
- Create an EKS cluster with all options using defaults

**Result**

The final state of the EKS cluster is:

```
time="2023-03-16T08:15:47Z" level=error msg="error syncing 'cattle-global-data/c-mlxn6': handler eks-controller: error creating stack with VPC template: stack failed to create: Resource creation cancelled, requeuing"
```
**Expected Result**

The EKS cluster should be created successfully.

**Screenshots**

<img width="1633" alt="image" src="https://user-images.githubusercontent.com/15829074/225551777-64446af8-1958-4172-ac4a-8006e50fbdb2.png">
<img width="1623" alt="image" src="https://user-images.githubusercontent.com/15829074/225551878-a5ed7a44-cc9b-4ed6-ac62-7698e0652eb5.png">
<img width="1790" alt="image" src="https://user-images.githubusercontent.com/15829074/225555867-ee0e16af-fbdc-4e96-8cb2-89c707f34073.png">

<img width="1785" alt="image" src="https://user-images.githubusercontent.com/15829074/225556132-db5e81ec-c239-45f8-912d-43835ebf6d1f.png">

**Comment by furkatgofurov7** [comment]
@TangStone hey! I am hitting the same error (with Rancher 2.7.9/2.8.0), did you find the root cause or a workaround?

**Comment by furkatgofurov7** [comment]
> Very likely hit VPC limit

Right, was about to comment as well: the VPC limit hitting (5 in my case) was the root cause of the failure, and deleting the redundant VPC helped to provision an EKS cluster successfully.
