### ISSUE TITLE
[Backport v2.6] vSphere CPI chart updates to upstream v1.24.4 / v1.23.4 / v1.22.8

### ISSUE THREAD

**Issue by a-blender** [rancher/rancher#40909]
Backport of https://github.com/rancher/rancher/issues/40908

**Is your feature request related to a problem? Please describe.**

Upstream has released the following new vSphere CPI versions:
~https://github.com/kubernetes/cloud-provider-vsphere/releases/tag/v1.25.1~ (no 1.25 for 2.6.x, so not needed)
https://github.com/kubernetes/cloud-provider-vsphere/releases/tag/v1.24.4
https://github.com/kubernetes/cloud-provider-vsphere/releases/tag/v1.23.4
https://github.com/kubernetes/cloud-provider-vsphere/releases/tag/v1.22.8

**Describe the solution you'd like**

Update the chart to include these new versions

# Checklist for items that need completed

- [ ] Update Image-mirror repo
- [ ] Update manifests in rancher/vsphere-charts
- [ ] Verify Slack hook notified about chart "release" in relevant channels
- [ ] Update chart in rancher/charts
- [ ] Update chart in rancher/rke2-charts (RKE2 team)
- [ ] Updated RKE2 to consume new chart (RKE2 team)

**Comment by sowmyav27** [comment]
@Sahota1225 @snasovich Is this being targeted for Q2 2.6?

**Comment by snasovich** [comment]
@sowmyav27 , not sure yet - pending discussion with product management.

**Comment by snasovich** [comment]
Closing this issue - at this time there is no plan to release updated vSphere versions for now "end of maintenance" 2.6.x line.
