### ISSUE TITLE
[RFE] Rancher machine hostname truncation

### ISSUE THREAD

**Issue by jakefhyde** [rancher/rancher#40901]
**Is your feature request related to a problem? Please describe.**

Allow users to set a per-machine-pool limit on the length of the hostname passed to `rancher-machine` during machine provisioning.

**Describe the solution you'd like**

Add a new field to the provisioning cluster's machine pool list containing a configurable limit from some minimum value (e.g. 10, to prevent collisions) to 63 which is trickled down to the generated infrastructure machine object and used to truncate the hostname.

**Describe alternatives you've considered**

**Additional context**

SURE-5811

**Comment by thaneunsoo** [comment]
Feature test is closed as Pass
UI validations can be found here [8223](https://github.com/rancher/dashboard/issues/8223)
Rancher backup and restore testing was completed by team 3 and can be found here [728](https://github.com/rancher/qa-tasks/issues/728#issuecomment-1548147575)

Tested the following scenarios and all are **Pass**:
1. Create rke2 cluster with "Truncate hostnames to 15 characters for NetBIOS compatibility"  checkbox enabled on Azure
2. Create rke2 cluster with "Truncate hostnames to 15 characters for NetBIOS compatibility"  checkbox disabled on vSphere
3. Create rke2 cluster with "Truncate hostnames to 15 characters for NetBIOS compatibility"  checkbox enabled on AWS with cloud provider enabled
4. Take and restore snapshot
5. Recurring Snapshots and retention
6. Create rke2 cluster with hostnameLengthLimit set to 15 manually on Azure at the cluster level
7. Create rke2 cluster with hostnameLengthLimit set to 0 manually on Azure at the cluster level
8. Create rke2 cluster with hostnameLengthLimit set to 9 manually on Azure at the cluster level
9. Create rke2 cluster with hostnameLengthLimit set to 10 manually on Azure at the cluster level
10. Create rke2 cluster with hostnameLengthLimit set to blank manually on Azure at the cluster level
11. Create rke2 cluster with hostnameLengthLimit manually set to 15 in YAML on vSphere and verify hostname is manually set on a machine pool in edit
12. Create rke2 cluster with hostnameLengthLimit manually set to 0 in YAML on Azure and verify hostname is not truncated
13. Create rke2 cluster with hostnameLengthLimit manually set to -5 in YAML on Azure and verify hostname is not truncated
15. Create rke2 cluster with hostnameLengthLimit manually set to 16 in YAML on Azure and verify hostname is truncated
16. Create rke2 cluster with hostnameLengthLimit manually set to blank in YAML on Azure
17. Create rke2 cluster with hostnameLengthLimit manually set to 15 on cluster level AND 20 at the machine pool level
18. Create k3s cluster with "Truncate hostnames to 15 characters for NetBIOS compatibility"  checkbox enabled on Azure (cluster level)
19. Create k3s cluster with  hostnameLengthLimit set to 15 manually on vSphere (machine pool level)
20. Create rke2 windows cluster with "Truncate hostnames to 15 characters for NetBIOS compatibility"  checkbox enabled on vSphere at cluster level
21. Create rke2 windows cluster with hostnameLengthLimit set to 15 manually on vSphere at machine pool level
22. Create cluster with hostnameLengthLimit set to 15 on Terraform with Azure at the cluster level
23. Create cluster with hostnameLengthLimit set to 15 on Terraform with Azure at the machine pool level
24. Create cluster with hostnameLengthLimit set to -4 on Terraform with Azure at the cluster level
25. Create cluster with hostnameLengthLimit set to -9 on Terraform with Azure at the machine pool level
26. Rancher upgrade from 2.7.2 to 2.7-head
