### ISSUE TITLE
vSphere CPI chart updates to upstream v1.26.0 / v1.25.1 / v1.24.4 / v1.23.4 / v1.22.8

### ISSUE THREAD

**Issue by a-blender** [rancher/rancher#40908]
**Is your feature request related to a problem? Please describe.**

Upstream has released the following new vSphere CPI versions:

https://github.com/kubernetes/cloud-provider-vsphere/releases/tag/v1.26.0
https://github.com/kubernetes/cloud-provider-vsphere/releases/tag/v1.25.1
https://github.com/kubernetes/cloud-provider-vsphere/releases/tag/v1.24.4
https://github.com/kubernetes/cloud-provider-vsphere/releases/tag/v1.23.4
https://github.com/kubernetes/cloud-provider-vsphere/releases/tag/v1.22.8

**Describe the solution you'd like**

Update the chart to include these new versions (possibly using new Renovate automation - not necessarily a requirement).

# Checklist for items that need completed

- [x] Update Image-mirror repo
- [x] Update manifests in rancher/vsphere-charts
- [x] (Non-standard checklist item) Ensure https://github.com/rancher/vsphere-charts/issues/46 is fixed so we include a fix for it as well
- [x] Verify Slack hook notified about chart "release" in relevant channels
- [x] Update chart in rancher/charts
- [ ] Update chart in rancher/rke2-charts (RKE2 team)
- [ ] Updated RKE2 to consume new chart (RKE2 team)

**Comment by Sahota1225** [comment]
synched up @sergey and decided to move all vsphere issues to Q3.

**Comment by thaneunsoo** [comment]
### Test Plan ###
Below are the covered testcases for the CPI chart update

Install CPI chart
1. Create a rancher server on v2.7-head on vSphere
- Login to vsphere engqa-7
- Create a vm from template, install docker, then run Rancher v2.7 head on it (this is behind the VPN so Rancher will be able to reach the downstream cluster)
2. Add vsphere credentials to Rancher
3. Provision a 3 node RKE1 vSphere cluster in Rancher
4. Verify downstream cluster is using `dev-v2.7` and not `release-v2.7`
5. Install CPI chart v1.26
6. Verify installation completed successfully and deployment/pods are running and healthy

Upgrade k8s version with CPI chart installed
1. Create a rancher server on v2.7-head on vSphere
- Login to vsphere engqa-7
- Create a vm from template, install docker, then run Rancher v2.7 head on it (this is behind the VPN so Rancher will be able to reach the downstream cluster)
2. Add vsphere credentials to Rancher
3. Provision a 3 node RKE1 vSphere cluster in Rancher
- Use k8s version 1.25
4. Verify downstream cluster is using `dev-v2.7` and not `release-v2.7`
5. Install CPI chart v1.26
6. Verify installation completed successfully and deployment/pods are running and healthy
7. Edit cluster config
- Upgrade k8s version from 1.25 to 1.26
- Save
8. Wait for cluster to finish upgrading and come up active
9. Verify all CPI pods are running and healthy

Upgrade CPI Chart
1. Create a rancher server on v2.7-head on vSphere
- Login to vsphere engqa-7
- Create a vm from template, install docker, then run Rancher v2.7 head on it (this is behind the VPN so Rancher will be able to reach the downstream cluster)
2. Add vsphere credentials to Rancher
3. Provision a 3 node RKE1 vSphere cluster in Rancher
4. Verify downstream cluster is using `dev-v2.7` and not `release-v2.7`
5. Install CPI chart version v1.25
6. Verify installation completed successfully and deployment/pods are running and healthy
7. Upgrade CPI chart to version v1.26
8. Verify installation completed successfully and deployment/pods are running and healthy

**Comment by a-blender** [comment]
Resolved by https://github.com/rancher/vsphere-charts/pull/55.

**Comment by brandond** [comment]
I believe it is on the end user to set the topology keys themselves by creating tags on the vSphere datacenter and server resources, as per the upstream docs. The vsphere configuration file for the Kubernetes cluster must then list the tags that hold the region and zone values, in the `topology-categories` value of the `Labels` section. I'm not sure if any of these tags are set in our vSphere environment?

**Comment by slickwarren** [comment]
sent review of test plan separately

**Comment by thaneunsoo** [comment]
### Test ###
Below are the covered testcases for the CPI/CSI chart update

**Install CPI/CSI v1.26.0 chart on rke1 cluster** - **PASS**
1. Create a rancher server on v2.7-head on vSphere
- Login to vsphere engqa-7
- Create a vm from template, install docker, then run Rancher v2.7-head on it (this is behind the VPN so Rancher will be able to reach the downstream cluster)
2. Add vsphere credentials to Rancher
3. Provision a 3 node RKE1 vSphere cluster in Rancher
- 1 cp/etcd, 2 worker
- Add taint `node.cloudprovider.kubernetes.io/uninitialized=true:NoSchedule` to cp/etcd node
4. Verify downstream cluster is using `dev-v2.7` and not `release-v2.7`
5. Install CPI chart v1.26
- Validate that cpi pod has been deployed and is active
- Validate that the taint is removed
6. Install CSI chart v3.0.0
- Validate that a storage class is created for `csi`
- Validate that the user can deploy a workload with a mounted volume
  - deploy ranchertest/mytestcontainer
    - mount a volume before creating the deployment
- After workload deploys, add data to the volume\
  - ssh into workload - volume is mounted on root with the name you gave it when creating the volume
- Verify data is created in volume
  - check in vSphere - volumes, or check through rancher

**Install CPI/CSI v1.26.0 chart on rke2 cluster** - **PASS**
1. Create a rancher server on v2.7-head on vSphere
- Login to vsphere engqa-7
- Create a vm from template, install docker, then run Rancher v2.7-head on it (this is behind the VPN so Rancher will be able to reach the downstream cluster)
2. Add vsphere credentials to Rancher
3. Provision a 3 node RKE1 vSphere cluster in Rancher
- 1 cp/etcd, 2 worker
- Add taint `node.cloudprovider.kubernetes.io/uninitialized=true:NoSchedule` to cp/etcd node
4. Verify downstream cluster is using `dev-v2.7` and not `release-v2.7`
5. Install CPI chart v1.26
- Validate that cpi pod has been deployed and is active
- Validate that the taint is removed
6. Install CSI chart v3.0.0
- Validate that a storage class is created for `csi`
- Validate that the user can deploy a workload with a mounted volume
  - deploy ranchertest/mytestcontainer
    - mount a volume before creating the deployment
- After workload deploys, add data to the volume\
  - ssh into workload - volume is mounted on root with the name you gave it when creating the volume
- Verify data is created in volume
  - check in vSphere - volumes, or check through rancher

**Upgrade k8s version with CPI/CSI chart installed** - **PASS**
1. Create a rancher server on v2.7-head on vSphere
- Login to vsphere engqa-7
- Create a vm from template, install docker, then run Rancher v2.7 head on it (this is behind the VPN so Rancher will be able to reach the downstream cluster)
2. Add vsphere credentials to Rancher
3. Provision a 3 node RKE2 vSphere cluster in Rancher
- Use k8s version 1.25
- 1 cp/etcd, 2 worker
- Add taint `node.cloudprovider.kubernetes.io/uninitialized=true:NoSchedule` to cp/etcd node
4. Verify downstream cluster is using `dev-v2.7` and not `release-v2.7`
5. Install CPI chart v1.25
- Validate that cpi pod has been deployed and is active
- Validate that the taint is removed
6. Install CSI chart v2.6.2
- Validate that a storage class is created for `csi`
- Validate that the user can deploy a workload with a mounted volume
  - deploy ranchertest/mytestcontainer
    - mount a volume before creating the deployment
- After workload deploys, add data to the volume\
  - ssh into workload - volume is mounted on root with the name you gave it when creating the volume
- Verify data is created in volume
  - check in vSphere - volumes, or check through rancher
7. Upgrade k8s version
- Edit config
- Upgrade k8s version from 1.25 to 1.26
- Save
8. Wait for cluster to finish upgrading and come up active
9. Verify all CPI pods are running and healthy
10. Upgrade CPI chart to v1.26
- Validate that cpi pod is updated to correct version and is active
11. Upgrade CSI chart to v3.0.0
- Validate that csi storage class is updated to correct version and is active
12. Edit storage and add new data
- ssh into workload - volume is mounted on root with the name you gave it when creating the volume
- Verify data is added to volume

**Install CPI/CSI chart v1.25.1 on rke2 cluster** - **PASS**
1. Create a rancher server on v2.7-head on vSphere
- Login to vsphere engqa-7
- Create a vm from template, install docker, then run Rancher v2.7-head on it (this is behind the VPN so Rancher will be able to reach the downstream cluster)
2. Add vsphere credentials to Rancher
3. Provision a 3 node RKE1 vSphere cluster in Rancher
- 1 cp/etcd, 2 worker
- Add taint `node.cloudprovider.kubernetes.io/uninitialized=true:NoSchedule` to cp/etcd node
4. Verify downstream cluster is using `dev-v2.7` and not `release-v2.7`
5. Install CPI chart v1.25.1
- Validate that cpi pod has been deployed and is active
- Validate that the taint is removed
6. Install CSI chart v2.6.3
- Validate that a storage class is created for `csi`
- Validate that the user can deploy a workload with a mounted volume
  - deploy ranchertest/mytestcontainer
    - mount a volume before creating the deployment
- After workload deploys, add data to the volume\
  - ssh into workload - volume is mounted on root with the name you gave it when creating the volume
- Verify data is created in volume
  - check in vSphere - volumes, or check through rancher

**Install CPI/CSI chart v1.24.4 on rke2 cluster** - **PASS**
1. Create a rancher server on v2.7-head on vSphere
- Login to vsphere engqa-7
- Create a vm from template, install docker, then run Rancher v2.7-head on it (this is behind the VPN so Rancher will be able to reach the downstream cluster)
2. Add vsphere credentials to Rancher
3. Provision a 3 node RKE1 vSphere cluster in Rancher
- 1 cp/etcd, 2 worker
- Add taint `node.cloudprovider.kubernetes.io/uninitialized=true:NoSchedule` to cp/etcd node
4. Verify downstream cluster is using `dev-v2.7` and not `release-v2.7`
5. Install CPI chart v1.24.4
- Validate that cpi pod has been deployed and is active
- Validate that the taint is removed
6. Install CSI chart v2.6.3
- Validate that a storage class is created for `csi`
- Validate that the user can deploy a workload with a mounted volume
  - deploy ranchertest/mytestcontainer
    - mount a volume before creating the deployment
- After workload deploys, add data to the volume\
  - ssh into workload - volume is mounted on root with the name you gave it when creating the volume
- Verify data is created in volume
  - check in vSphere - volumes, or check through rancher

**Install CPI/CSI chart v1.23.4 on rke2 cluster** - **PASS**
1. Create a rancher server on v2.7-head on vSphere
- Login to vsphere engqa-7
- Create a vm from template, install docker, then run Rancher v2.7-head on it (this is behind the VPN so Rancher will be able to reach the downstream cluster)
2. Add vsphere credentials to Rancher
3. Provision a 3 node RKE1 vSphere cluster in Rancher
- 1 cp/etcd, 2 worker
- Add taint `node.cloudprovider.kubernetes.io/uninitialized=true:NoSchedule` to cp/etcd node
4. Verify downstream cluster is using `dev-v2.7` and not `release-v2.7`
5. Install CPI chart v1.23.4
- Validate that cpi pod has been deployed and is active
- Validate that the taint is removed
6. Install CSI chart v2.6.3
- Validate that a storage class is created for `csi`
- Validate that the user can deploy a workload with a mounted volume
  - deploy ranchertest/mytestcontainer
    - mount a volume before creating the deployment
- After workload deploys, add data to the volume\
  - ssh into workload - volume is mounted on root with the name you gave it when creating the volume
- Verify data is created in volume
  - check in vSphere - volumes, or check through rancher
