### ISSUE TITLE
Adjust icons style for projects icons

### ISSUE THREAD

**Issue by manuelecarlini** [rancher/rancher#40905]
The icons for the project's logos in our icon set have all different styles,
sometimes this means having icons with different sizes that result in a poorly looked UI, and in general, there isn't the feeling that these icons belong to the same set.

For those icons, a redesign is needed that will make all the graphic element have the same size, line thickness (when possible), and look. 

Furthermore, we want to add some missing partners' logos such as Kubernetes and GitLab,
and in order to differentiate our projects from the rest of the icon, their logo icon will have a background.

**Comment by kwwii** [comment]
This issue was created in the wrong repo
