### ISSUE TITLE
[BUG] Hosted AKS cluster created from rancher fails to get External/Public IP.

### ISSUE THREAD

**Issue by vivek-infracloud** [rancher/rancher#40916]
**Rancher Server Setup**
- Rancher version: v2.6.5/v2.6.11 (Issue was tested on these two rancher versions)
- Installation option (Docker install/Helm Chart): Docker
- Proxy/Cert Details: Self Signed

**Information about the Cluster**
- Kubernetes version: 1.24
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Hosted AKS cluster.

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): Admin

**Describe the bug**

A hosted cluster created from the rancher v2.6.11 provisions successfully, however, the nodes get only the internal IP address assigned. Public/External IP isn't get assigned to the hosted AKS cluster nodes.

**To Reproduce**

- Create a rancher server v2.6.11.
- Go on to create a hosted AKS cluster with latest version.
- Wait until the cluster is created.

**Result**
**Once the cluster is created successfully, notice the External/Public IP is not assigned to nodes.**

**Expected Result**

External/Public IP should get assigned to hosted AKS cluster nodes.

**Additional information**

I did some debugging and found following things.

While creating a hosted AKS cluster the `Enable Public IP per node` option is missing on rancher UI. Hence all the k8s versions get affected due to this, from rancher v2.6.5 to latest rancher version.
![Screenshot from 2023-03-16 14-39-49](https://user-images.githubusercontent.com/83208989/226523251-91a77a03-0817-4b70-ae77-80af1c89e41a.png)

**This option is available on Azure Portal (last check box, unchecked by default).** 
While creating cluster from azure portal, if this option kept unchecked the nodes do not get External/Public IP assigned.
![Screenshot from 2023-03-16 14-36-19](https://user-images.githubusercontent.com/83208989/226523300-a574d4d3-7b49-408e-8e0a-f2ea85575e37.png)

**Comment by mjura** [comment]
@vivek-infracloud Ok, according to my knowledge we didn't support `Enable Public IP per node` in Rancher UI never. It is not even supported by aks-operator. It is feature request for aks-operator

**Comment by sowmyav27** [comment]
Closing this as its not an issue.
