### ISSUE TITLE
[UI] Bug in vertical axis scale of Storage graph on Container Info page

### ISSUE THREAD

**Issue by frol** [rancher/rancher#4091]
Rancher Version: 0.63.1

Docker Version: 1.10.3

OS: Ubuntu 14.04.4 x64

Steps to Reproduce: 

Open a Container Information page and wait.

Results:

Look at the Storage vertical axis scale:

![rancher-storage-scale-bug](https://cloud.githubusercontent.com/assets/304265/13981463/d859bfd8-f116-11e5-9901-a9e1e21e823e.png)

0 > 901 > (WAT?!) 802 > ...

![rancher-storage-scale-bug2](https://cloud.githubusercontent.com/assets/304265/13981464/d8923ffc-f116-11e5-8e17-dfb6f02ba09e.png)

0 > 240 > 481 > 721 > 962 > (WAT?!) 202

Expected:

Usually, values on a scale go from 0 to ++.

**Comment by vincent99** [comment]
It appears that there's a 4th digit and they're cut off because the scale is fixed width...

Increment is ~901Mbps (901, **1**801, **2**702, **3**603, **4**504) in the first picture and ~240Mbps in the 2nd (240, 481, 721, 962, **1**202)

**Comment by frol** [comment]
Yes, that sounds like a reasonable explanation.

**Comment by vincent99** [comment]
Changed to be a little wider, and adaptive number of decimal points so the value is never more than 3 digits, and show gbps if > 1000mbps.

**Comment by tfiduccia** [comment]
Version - master 4/1
Verified fixed
