### ISSUE TITLE
[BUG] Istio test worker nodes refusing to connect to demo book service after k8s upgrade 1.24.10 -> 1.25.6 

### ISSUE THREAD

**Issue by nickwsuse** [rancher/rancher#40922]
**Rancher Server Setup**
- Rancher version: `v2.7.2-rc6`
- Installation option (Docker install/Helm Chart): `Helm` 
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): `RKE1`
- Proxy/Cert Details: `byo-valid`

**Information about the Cluster**
- Kubernetes version: `1.24.10` (start) -> `v1.25.6`
- Cluster Type (Local/Downstream): `Downstream`
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): `EC2`

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): `Admin`

**Describe the bug**
After upgrading the downstream cluster from k8s version `v1.24.10` to `v1.25.6`, the worker nodes are no longer available when trying to access them using the Istio test URL -- `<worker-node-ip>:31380/productpage`

**To Reproduce**
1. Deploy an HA
2. Deploy a downstream EC2 RKE1 cluster (3 workers, 1 control plane, 1 etcd) on k8s `v1.24.10`
3. On the downstream cluster, install the monitoring chart (`v102.0.0+up40.1.2`)
4. On the downstream cluster, install the Istio chart (`v102.0.0+up1.15.3`) and ensure Jaeger is enabled
5. **NOTE**: This seems to happen regardless of PSPs being enabled, but my most recent reproduction of this **did** have PSPs enabled when installing the Istio chart
6. On the downstream cluster, create a new namespace and add the label `istio-injection=enabled`
7. Import the `demobookservice.yaml` into the new namespace (you can reach out to me if you need it)
8. Grab one of the worker node's external IP address' and open a new tab
9. Go to `<worker-node-ip>:31380/productpage` (if you don't wait for the deployment of the demobookservice.yaml to complete you may have to retry after a minute or so)
10. Once the demo app comes up go back to Rancher and upgrade the downstream cluster to k8s version `v1.25.6`
11. After the upgrade is complete, go back to the demo page -- `<worker-node-ip>:31380/productpage`

**Result**
After the upgrade, the demo book service is unavailable because the node IP is refusing to connect.

**Expected Result**
The demo book service is still available after upgrading the k8s version of the cluster.

**Screenshots**
![image](https://user-images.githubusercontent.com/107147272/225970482-90331e76-b1a4-40cf-8c21-7aee6b8e7c31.png)

**Comment by prachidamle** [comment]
@nickwsuse @ronhorton Seems this is not reproducible as posted in the comments above - Can we re-test this please?

**Comment by vivek-infracloud** [comment]
@prachidamle I tried to reproduce the issue by following the steps mentioned [here](https://github.com/rancher/rancher/issues/40922#:~:text=ip%3E%3A31380/productpage-,To%20Reproduce,-Deploy%20an%20HA). However, the issue was not reproducible. 

Tested two test case scenarios by installing an istio chart with PSP enabled and PSP disabled.
In both cases the demobook app was accessible even after upgrade from k8s v1.24.10 --> 1.25.6.
