### ISSUE TITLE
RKE2 Downstream Custom Cluster gets stuck in Updating State after rancher server upgrade

### ISSUE THREAD

**Issue by dasarinaidu** [rancher/rancher#40924]
**Rancher Server Setup**
- Rancher version: 2.7.0 upgraded to 2.7-head (2.7.2-rc6)
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2 custom cluster
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: `v1.23.14+rke2r1 to v1.25.7+rke2r1`
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Custom

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Admin

**Describe the bug**
Sometimes when performing an HA Upgrade to Rancher v2.7.0 TO v2.7.2-rc6, while having an AWS RKE2 custom cluster - the cluster will go into Updating state and the etcd nodes will go into a Reconciling state, and will not come back up as Active.

**To Reproduce**

1. Create a HA Rancher serve on v2.7.0
2. Provision a downstream AWS RKE2 custom cluster with k8 version : v1.23.14+rke2r1
3. Perform an HA Upgrade on Rancher v2.7-head (v2.7.2-rc6)
4. Make sure the upgrade success and downstream cluster came back active
5. Upgrade downstream cluster kubernetes version to to v1.25.7+rke2r1 and SAVE
6. Check for the system behavior, Logs and cluster state

**Result**
a. Downstream cluster initially came back active and then it went to update state with an error and it never came back to Active
b. Info Logs are showing but there is no error logs
c. Downstream Cluster is in `Updating` state for long time
d. One of the node (etcd) is in Reconciling state and never came back with message on UI (Node condition MemoryPressure is Unknown. Node condition DiskPressure is Unknown. Node condition PIDPressure is Unknown. Node condition Ready is Unknown., waiting for probes: etcd, kubelet)
e. UI error : 

**Expected Result**
a. Downstream cluster should come active without any issues

**Screenshots**
![image](https://user-images.githubusercontent.com/22034884/225985720-ae529823-1cda-4b8f-965f-95acda438643.png)

**Additional context**

https://github.com/rancher/rancher/issues/40110

**Comment by Sahota1225** [comment]
Closing this issue as it is same as [issue#40110](https://github.com/rancher/rancher/issues/40110)
