### ISSUE TITLE
Problems to integrate a EKS cluster with tancher 2.6.6

### ISSUE THREAD

**Issue by dyegodiniz** [rancher/rancher#40937]
Hi guys, I'm trying to import a existing cluster EKS in my rancher server, but I'm receiving the message "[Disconnected] Cluster agent is not connected" when I open de cluster properties. I think that rancher should install the agent automatically. Any clue about this issue?

Rancher: 2.6.6
k8s EKS: 1.22.16
I'm following the doc: https://ranchermanager.docs.rancher.com/v2.6/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/register-existing-clusters#configuring-an-imported-eks-cluster-with-terraform

**Comment by BJWRD** [comment]
@dyegodiniz Did you manage to fix this? Receiving the same problem myself right now.
