### ISSUE TITLE
About git vulnerability into rancher's pods

### ISSUE THREAD

**Issue by Tostapane95** [rancher/rancher#40934]
Hi all, I currently have rancher v.2.4.6  installed in a Kubernetes cluster via Helm. However, in mid-January, a git vulnerability popped out: https://github.blog/2023-01-17-git-security-vulnerabilities-announced-2/ . I noticed that the vulnerability arise in my rancher's pods. Does anyone know which version of rancher uses a non-vulnerable version of git-core packages? I've been told that v.2.7.1 might be a solution, could you provide more informations?

**Comment by Tostapane95** [comment]
Does anyone have news?

**Comment by macedogm** [comment]
Hi @Tostapane95. Rancher versions [v2.7.1](https://github.com/rancher/rancher/releases/tag/v2.7.1) and [v2.6.10](https://github.com/rancher/rancher/releases/tag/v2.6.10) use a version of Git patched against the CVEs that you mentioned.

**Comment by Tostapane95** [comment]
ty very much macedogm
