### ISSUE TITLE
[BUG] Incorrect node IP reported in certain setups

### ISSUE THREAD

**Issue by HarrisonWAffel** [rancher/rancher#40936]
**Rancher Server Setup**
- Rancher version: 2.6.11
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): n/a
- Proxy/Cert Details: n/a

**Information about the Cluster**
- Kubernetes version: n/a
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): AWS

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: n/a

A recent PR introduced the use of DNS to provide a node external IP when the agent registers to Rancher.

This affects custom clusters in a typical configuration of a private subnet/network and a device to provide external connectivity (NAT GW, proxy, VPN, etc.), this falsely represents the public IP (source IP) of nodes as it registers for provisioning. The IP(s) of the device(s) are used.

This causes nodes to get a shared public IP (as rke.cattle.io/external-ip on the nodes.management.cattle.io object), or may not be reachable (further cluster types are still being tested).

In this circumstance the node can register with the plan of an already existing node (worker gets control plane, etc.), but the node will also never register completely. This is due to the non-unique public IP, so it may depend on how many IPs the environment has before nodes begin to overlap (often just one, but may be one per AZ, etc.).

**Reproduction steps:**

Rancher v2.6.11 (possibly also v2.7.1)
Create a downstream custom cluster (may also affect some node-drivers, EC2 did not reproduce)
Launch a node in a private subnet without direct access to the internet (home network, private subnet in a VPC etc.)
Run the docker run join command
The public IP is retrieved from DNS (as in PRs above)
Add a further node, if the public IP overlaps with the first node, provisioning will fail and may receive unexpected components from the plan

**Workaround:**
Is workararound available and implemented? yes
What is the workaround:

Start the agent with --address flag set to the private IP of the node, you could also set -internal-address.

  * https://ranchermanager.docs.rancher.com/reference-guides/cluster-configuration/rancher-server-configuration/use-existing-nodes/rancher-agent-options#ip-address-options

**Actual behavior:**

Nodes can't join the cluster, partial provisioning with incorrect node roles (depending on what node the public IP overlaps with)

**Expected behavior:**

Normal provisioning

**Additional context**
SURE-6033

**Comment by HarrisonWAffel** [comment]
The CI build has passed and this issue can now be tested on 2.7-head, the above PR includes test steps. We should also re-validate the initial kubelet cert DOS issue. That issue includes its own test steps has been linked in the above PR's description.

**Comment by slickwarren** [comment]
tested this on v2.7-head (4a9b7ba):
* deploy a custom cluster using a node with only a private IP address -- pass
* will continue testing https://github.com/rancher/rancher/issues/36025 and possibly other use cases tomorrow

**Comment by slickwarren** [comment]
* completed testing  https://github.com/rancher/rancher/issues/36025 -- pass
* manual removal of cert is regenerated -- pass
* reboot does not affect certificates -- pass

**Comment by slickwarren** [comment]
reopening for upgrade test case

**Comment by slickwarren** [comment]
finalized testing:
* deploy rancher 2.6.11
* deploy a custom rke1 cluster (v1.24.10-rancher1-1
  * 1 node, all roles
  * 1 worker node

* should get to an active state with at least the first node. Observe public IP is reported/used, though it should not be used.
* upgrade rancher
* see if the cluster self-repairs, removing the public IP and getting back to an active state 
  * Cluster did not self repair - rancher logs show that the public IP is (incorrectly) being used, as that is what the cluster was setup with
* if the downstream cluster is not active, test if an upgrade to the cluster through rancher (just changing something small to trigger the upgrade) will repair it + remove the public IP. 
* Cluster did not repair after upgrade - rancher logs show that the public IP is (incorrectly) being used, as that is what the cluster was setup with. the public IP does not correctly resolve to the internal node in this subnet, therefore the upgrade was not successful
* deploy a new cluster (v1.24.10-rancher1-1 1node all roles, 1 worker) , ensure it gets to an active state and only see private IPs used -- pass
  * note: this was using aws with a private subnet, using a NAT gateway
  * rotate certificates -- ensure certificates are all correctly rotated -- **pass**

**Comment by HarrisonWAffel** [comment]
We do not expect the cluster to be recoverable after upgrading Rancher to resolve the bug. The initial connection / configuration of the cluster was invalid due to an improper connection process and thus the resulting configuration is invalid from that point on.

**Comment by slickwarren** [comment]
based on the above 2 messages, this ticket has been validated
