### ISSUE TITLE
[RFE] Allow to set nodeAffinity and tolerations on Helm chart

### ISSUE THREAD

**Issue by seboudry** [rancher/rancher#40948]
**Is your feature request related to a problem? Please describe.**

Currently (version 2.7.1), `nodeAffinity` and `tolerations` are defined to only allow deployments on linux nodes.

https://github.com/rancher/rancher/blob/release/v2.7.1/chart/templates/_helpers.tpl#L52-L66

We need to change this default behaviour to our own requirements.

**Describe the solution you'd like**

Ability to define `nodeAffinity` and `tolerations` as Helm chart values.

**Comment by mohag** [comment]
This is still an issue with the current chart in rancher-stable

**Comment by mmgil** [comment]
same case here,

We need the ability to define `nodeAffinity` and `tolerations` as Helm chart values.
