### ISSUE TITLE
LB not start  after truncate audit_log

### ISSUE THREAD

**Issue by Negashev** [rancher/rancher#4094]
Rancher Version:v0.63.1

Docker Version:1.7-1.10.2

OS: CentOS 6 - CentOS 7

Steps to Reproduce: I truncate old data from audit_log

Results: 
I remove one LB and service LoadBalancer in status `Updating-Active`, new LB not start

and write:

```Updating-Active (SQL [insert into `audit_log` (`account_id`, `authenticated_as_account_id`, `kind`, `auth_type`, `event_type`, `resource_type`, `resource_id`, `description`, `created`, `data`, `authenticated_as_identity_id`, `runtime`, `client_ip`) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]; Data too long for column 'data' at row 1)```

Expected: which queries the database I need to enter

![screenshot 69](https://cloud.githubusercontent.com/assets/4653589/13987995/edbd5154-f12b-11e5-9799-9118afc1f514.png)

**Comment by alena1108** [comment]
@Negashev thanks for reporting it. We would have to change the type (from text to mediumtext) for audit_log.data field to match the size of data field of other cattle db tables (mediumtext)

**Comment by alena1108** [comment]
@sangeethah to test, check that audit_log.data field type got changed from text to mediumtext

**Comment by sangeethah** [comment]
Tested on a upgraded setup - Fresh install - > v0.59.1 -> Upgraded to V0.63.1 - > Upgraded to v1.0.0

audit_log.data field is type "mediumtext"
