### ISSUE TITLE
[BUG] [rancher-monitoring] Unable to upgrade Rancher Monitoring from v101.0.0+up19.0.3 to 102.0.0+up40.1.2

### ISSUE THREAD

**Issue by stormqueen1990** [rancher/rancher#40941]
**Rancher Server Setup**
- Rancher version: v2.7.2-rc6
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1 v1.4.3-rc6
- Proxy/Cert Details: N/A

**Information about the Cluster**
- Kubernetes version: v1.24.4
- Cluster Type (Local/Downstream): local

**User Information**
- What is the role of the user logged in? Default Admin

**Describe the bug**

After an upgrade from Rancher v2.7.1 to v2.7.2-rc6, an upgrade of the rancher-monitoring chart from v101.0.0+up19.0.3 to 102.0.0+up40.1.2 fails with the following error message:
```
Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(ServiceMonitor.spec): unknown field "metricRelabelings" in com.coreos.monitoring.v1.ServiceMonitor.spec
```

**To Reproduce**

* Prepare an RKE1 cluster with RKE v1.4.3-rc6, with Kubernetes v1.24.4.
* Install Rancher v2.7.1 on the cluster.
* Finish the setup for Rancher and install the Monitoring v101.0.0+up19.0.3 chart on the cluster.
* Upgrade Rancher to v2.7.2-rc6.
* Try to upgrade the installation for Monitoring to v102.0.0+up40.1.2.

**Result**
Installation fails with the following error:
```
Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(ServiceMonitor.spec): unknown field "metricRelabelings" in com.coreos.monitoring.v1.ServiceMonitor.spec
```

**Expected Result**

Installation succeeds.

**Screenshots**

**Additional context**

This failure happens only on the local cluster. I am able to upgrade the Monitoring installation on a downstream cluster without issues.

**Comment by geethub97** [comment]
I'm not entirely sure whether this is related or not but I am seeing the following error in the local cluster:
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/99695266/227051221-83527df9-7f8d-4918-ae42-45b2c64eb41a.png">

Steps to recreate: 
1. Installing rancher via `docker run -d --restart=unless-stopped   -p 80:80 -p 443:443   --privileged  rancher/rancher:v2.7.1`
2. Installing rancher-monitoring `101.0.0+up19.0.3`
3. Upgrading the rancher docker image to v2.7.2-rc6 (via steps in https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade/other-installation-methods/rancher-on-a-single-node-with-docker/upgrade-docker-installed-rancher) 
4. upgrading monitoring to `102.0.0+up40.1.2`

**Comment by ronhorton** [comment]
**testing this, encountered error**
1. installed monitoring v101.0.0+up19.0.3 on 1.24 cluster
2. upgraded cluster to 1.25
3. upgraded monitoring to v102.0.0+up40.1.12

`helm upgrade --history-max=5 --install=true --namespace=cattle-monitoring-system --timeout=10m0s --values=/home/shell/helm/values-rancher-monitoring-crd-102.0.0-up40.1.2.yaml --version=102.0.0+up40.1.2 --wait=true rancher-monitoring-crd /home/shell/helm/rancher-monitoring-crd-102.0.0-up40.1.2.tgz
Error: UPGRADE FAILED: unable to build kubernetes objects from current release manifest: resource mapping not found for name: "rancher-monitoring-crd-manager" namespace: "cattle-monitoring-system" from "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
ensure CRDs are installed first`

**Comment by stormqueen1990** [comment]
The upgrade flow is being documented via rancher/rancher-docs#508.

**Comment by prachidamle** [comment]
Moving to-test to verfiy the documented solution of using helm-mapkubeapis plugin unblocks the upgrade by cleaning up the psp and related resources blocking upgrade. Can be tested with charts like gatekeeper/logging as well.

**Comment by stormqueen1990** [comment]
I've noticed during testing that cleaning up the Rancher Monitoring chart with `helm-mapkubeapis` might fail on clusters that use ingress-nginx for ingress traffic due to the size of the request entity. I am currently in the process of reproducing the issue and testing possible workarounds.

**Comment by stormqueen1990** [comment]
> I've noticed during testing that cleaning up the Rancher Monitoring chart with `helm-mapkubeapis` might fail on clusters that use ingress-nginx for ingress traffic due to the size of the request entity. I am currently in the process of reproducing the issue and testing possible workarounds.

I've confirmed it's possible to workaround the following issue:
```console
Error: failed to update release '<release-name>': failed to update release version '<release-name>.v1': update: failed to update: the server responded with the status code 413 but did not return more information (put secrets sh.helm.release.v1.<release-name>.v1)
```

By running the following command in the `local` cluster:
```shell
kubectl annotate ingress rancher nginx.ingress.kubernetes.io/proxy-body-size=4m --namespace cattle-system
```

The issue is caused by a payload bigger than the maximum allowed size by ingress-nginx, and the annotation added by the command allows nginx to accept a bigger payload.

**Comment by ronhorton** [comment]
**Pass** verified in rancher `v2.7-head commit ID 4a07c2f`

**Comment by rameshraya3010** [comment]
> [dev-v2.7] fix serviceMonitor unknown field error rancher/charts#2496

Hi @geethub97 Have you resolved the below issue :- 

Error: UPGRADE FAILED: unable to build kubernetes objects from current release manifest: resource mapping not found for name: "rancher-monitoring-crd-manager" namespace: "cattle-monitoring-system" from "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
2024-08-20T15:51:01.004655810Z ensure CRDs are installed first

**Comment by julienleboeuf** [comment]
Same issue with rancher 2.9.3
Trying to upgrade Monitoring from 100.2.0+up40.1.2 to 104.1.4+up57.0.3

```
helm upgrade --history-max=5 --install=true --labels=catalog.cattle.io/cluster-repo-name=rancher-charts --namespace=cattle-monitoring-system --timeout=10m0s --values=/home/shell/helm/values-rancher-monitoring-crd-104.1.4-up57.0.3.yaml --version=104.1.4+up57.0.3 --wait=true rancher-monitoring-crd /home/shell/helm/rancher-monitoring-crd-104.1.4-up57.0.3.tgz
Error: UPGRADE FAILED: unable to build kubernetes objects from current release manifest: resource mapping not found for name: "rancher-monitoring-crd-manager" namespace: "cattle-monitoring-system" from "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
ensure CRDs are installed first
```
