### ISSUE TITLE
Add Istio 1.16.x and 1.17.x to Rancher

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#40959]
Request Description:
We need to add 1.16.x and 1.17.x Istio to Rancher 2.7.X line

Actual Behavior:
Only 1.15 is available

Expected Behavior:
1.16.x and 1.17.x are available

Workaround:
Is workaround available and implemented? No
What is the workaround: No

 

Notes:
The previous version of Rancher has 1.15.x. When Q2 release is done, 1.17 will be the newest version. But it is not recommended to skip a minor version when upgrading, so we need to provide both 1.16.x and 1.17.x in the Q2 rancher release.

SURE-5879

**Comment by rishabhmsra** [comment]
**Validated on rancher v2.7.2**

- Created k8s v1.25.6-rancher4-1 node driver cluster (1-cp, 1-e, 2-w)
- Installed monitoring `102.0.0+up40.1.2` chart version.
- Installed Istio `102.1.0+up1.16.3` chart version.

**Tested below scenarios and all checks passed :**

- Fresh install checks
- Upgrade test case from istio `102.0.0+up1.15.3` —> `102.1.0+up1.16.3` (after upgrade validated traffic through Kiali and Jaeger)
- Upgrade with custom overlay
- Kiali
- Jaeger traces
- Reinstall with Kiali and Jaeger enabled
- Fresh install with modified ingress gateway
- Reinstall
- Istio pointing to externally-installed Prometheus
- Multiple ingress 
- Egressgateway

**Comment by rishabhmsra** [comment]
Validated istio v1.16, but re-opening this issue since istio v1.17 changes are yet to be merged.

**Comment by rishabhmsra** [comment]
**Validated on rancher v2.7.3-rc1**

- Created k8s v1.25.6-rancher4-1 node driver cluster (1-cp, 1-e, 2-w)
- Installed monitoring 102.0.0+up40.1.2 chart version.
- Installed Istio 102.2.0+up1.17.2 chart version.

**Tested below scenarios and all checks passed :**

- Fresh install checks
- Upgrade test case from istio 102.1.0+up1.16.3 —> 102.2.0+up1.17.2 (after upgrade validated traffic through Kiali and Jaeger)
- Upgrade with custom overlay
- Kiali
- Jaeger traces
- Reinstall with Kiali and Jaeger enabled
- Fresh install with modified ingress gateway
- Reinstall
- Istio pointing to externally-installed Prometheus
- Multiple ingress
- Egressgateway

**Result :** 
- All checks passed for istio, hence closing the issue.
