### ISSUE TITLE
Current logging situation is blowing up my hosts

### ISSUE THREAD

**Issue by atrauzzi** [rancher/rancher#4096]
As per conventional advice with Docker, I have my containers sending all their output to stdout/stderr.

Unfortunately, I'm noticing that my containers end up eating up a large amount of memory and write very large log files to my filesystem over time.

I see in [this issue](https://github.com/rancher/rancher/issues/2935) that any logging configuration support has been pushed to version 1.1, although I really think this might be a 1.0 feature. 

FWIW: I've also read one of [Rancher's blog posts](http://rancher.com/aggregating-application-logs-from-docker-containers-with-loggly/) for configuring a syslogd based logging setup.  I would rather not have to take this approach as it is likely to add complexity to my containers - especially when it comes to our favourite friend nginx.)

Can we get logging support for 1.0?

**Comment by vincent99** [comment]
There is no need for a 2nd issue about this
