### ISSUE TITLE
[BUG]Client can't access rancher

### ISSUE THREAD

**Issue by XMingG99** [rancher/rancher#40961]
**Rancher Server Setup**
- Rancher version: stable (v2.6.11)
- Installation option (Docker install/Helm Chart): Docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.24.10
- Cluster Type (Local/Downstream): 
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? Admin
  - If custom, define the set of permissions:

**Describe the bug**
Now, I have 4 hosts:

host1 IP Address: 192.168.1.2
host2 IP Address: 10.10.100.3
host3 IP Address: 10.10.100.4
host4 IP Address: 10.10.100.8

host1 had a route to connect host3 and host1 can ping host3 successfully.

I used docker to install rancher in host2. And I can access rancher in host3 and host4 by browser. But I can't access rancher by host1.

 I think it may be caused by certificates. So, I used openssl to create a ca.crt for rancher, and I re-install rancher by docker. [Install Command](https://ranchermanager.docs.rancher.com/zh/reference-guides/single-node-rancher-in-docker/advanced-options#%E8%87%AA%E5%AE%9A%E4%B9%89-ca-%E8%AF%81%E4%B9%A6).

But the problem is still exited. How can I do it?

**Comment by Richardswe** [comment]
Did you solve it? I would do a nmap scan from host1 to host2.

**Comment by XMingG99** [comment]
> Did you solve it? I would do a nmap scan from host1 to host2.

I fix that, it's a network problem.
