### ISSUE TITLE
[BUG] Specifying CA Certificate Bundle in v2prov registry authentication leads to duplicate file definition in v2prov plan

### ISSUE THREAD

**Issue by Oats87** [rancher/rancher#40968]
**Rancher Server Setup**
- Rancher version: v2.7.1 (and older)
- Installation option (Docker install/Helm Chart): N/A
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: N/A
- Cluster Type (Local/Downstream): Downstream K3s/RKE2
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:
N/A

**Describe the bug**
When creating or managing a v2prov cluster and specifying custom registry authentication credentials, v2prov will render duplicate entries for the CA cert bundle. While benign if there is only one registry configuration, this leads to plan thrashing if there are more than one registry configurations defined, as the file entries in the plan will be out of order.

**To Reproduce**
Create a v2prov cluster with a registry authentication configuration that specifies a CA Cert Bundle. Details on how to do this are located in the appendix of this issue. Specify multiple registry mirrors and authentication entries for the cluster, create the cluster, register a node (whether provisioned or custom).

**Result**
Note that the `rancher-system-agent` on this node continuously reconciles the plan stating that the plan checksum changes. This is not correct, as the plan checksum should not be changing. If you trace the applied plan history (can be found in `/var/lib/rancher/agent/applied/` and diff the results, you will see that the order of the CA certificate bundle in the files entry changes. 

**Expected Result**
The cluster should provision without issue.

**Screenshots**

Example configuration of the cluster with multiple registries. Note that the CA certificate can (and for the purposes of this issue) be identical, but should have separate entries for different registry endpoints.
<img width="3120" alt="Screenshot 2023-03-23 at 12 22 39 PM" src="https://user-images.githubusercontent.com/30601846/227356378-a59a6155-9778-4e61-88cb-b14cbe84fa78.png">

**Additional context**

These are the steps I followed to creating a private CA backed image registry mirror.

1. Create an instance and install Docker onto it. In my case, I used a CentOS 7 instance with Docker 20.10, installed via `curl https://releases.rancher.com/install-docker/20.10.sh | sh -`
2. Log into the instance and sign both a CA and certificate for the instance. A quick script to do this on an instance where the primary network interface is named `ens192` would be: 
```
MYIP=$(ip -4 addr show ens192 | grep "inet" | awk '{print $2}' | sed -e 's/\/21$//'); docker run -v $PWD/certs:/certs -e SSL_SUBJECT=r.$MYIP.nip.io -e SSL_DNS=r.$MYIP.nip.io -e SSL_IP=$MYIP superseb/omgwtfssl
```
3. Create a `config.yml` for the Docker registry:
*Note* you must add your own username/password to the proxy entry to ensure that you do not get rate limited when pulling images.
```
cat << EOF > config.yml
version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
proxy:
  remoteurl: https://registry-1.docker.io
  username: $DOCKERHUB_USERNAME
  password: $DOCKERHUB_PASSWORD
EOF
```

5. Run the registry, i.e. `docker run -d --restart=always --name registry -v "$(pwd)"/config.yml:/etc/docker/registry/config.yml -v "$(pwd)"/certs:/certs -e REGISTRY_HTTP_ADDR=0.0.0.0:443 -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/cert.pem -e REGISTRY_HTTP_TLS_KEY=/certs/key.pem -p 443:443 registry:2`
6. The registry will be available at `r.<IP-OF-NODE>.nip.io` and you can test it with the `certs/ca.pem` file with your local Docker installation by creating a file in `/etc/docker/certs.d/r.<IP-OF-NODE>.nip.io/ca.crt`that contains the contents from `ca.pem`. For example, try `docker pull r.<IP-OF-NODE>.nip.io/rancher/rancher:v2.7.1`
7. Take the `ca.pem` from `certs/ca.pem` and base64 encode it for use in testing this issue. For example, `cat certs/ca.pem | base64 -w 0`

SURE-5646

**Comment by sowmyav27** [comment]
@jakefhyde to test e2e usecase. @markusewalker to validate Rancher upgrade usecase.

**Comment by Oats87** [comment]
https://github.com/rancher/rancher/pull/41459 adds e2e cases that define private registries (and actually we now define multiple registries)

**Comment by markusewalker** [comment]
**QA TEST PLAN**

**Scenarios**
|Scenario|Test Case|
|---|---|
|1|As a standard user, provision a downstream RKE2 node driver cluster with a private registry with a CA cert bundle and validate there are no redundant entries for the CA cert bundle|
|2|As a standard user, provision a downstream RKE2 node driver cluster with two registry configurations with a shared CA cert bundle and validate there are no duplicate entries|
|3|As a standard user, provision a downstream K3S node driver cluster without a private registry initially defined, edit the cluster configuration and include two private registries configurations with a shared CA cert bundle and validate there are no duplicate entries|

**Comment by markusewalker** [comment]
QA can work on reproducing this issue, but we will need a RC to get a `rancher-images.txt` to test properly with the private registry stood up to validate this issue.

**Comment by markusewalker** [comment]
Reproduced this on `v2.7.2`. See details below:

**ENVIRONMENT DETAILS**
- Rancher install: Docker
- Rancher version: `v2.7.2`
- Browser: Chrome

**TEST RESULTS**
|Scenario|Test Case|Result|
|---|---|---|
|1|As a standard user, provision a downstream RKE2 node driver cluster with a private registry with a unique CA cert bundle and validate there are no redundant entries for the CA cert bundle|:x:|

**REPRODUCTION STEPS**
1. On a client machine, configured a private registry that has tagged `v2.7.2` images to be used in Rancher.
2. Navigated over to Rancher in a browser.
3. As a standard user, provisioned a downstream RKE2 `v1.25.7+rke2r1` custom cluster with my earlier created private registry set to pull the container images.
     - Ensured that the private registry was configured with a CA Cert bundle defined.
4. The cluster never comes up `Active` due to the etcd node being stuck in a `Reconciling` state with message `waiting for probes: kubelet`.

_NOTES:_ For what it is worth, I was successfully able to provision an RKE2 `v1.25.7+rke2r1` cluster when I had no CA Cert bundle defined and I skipped TLS checks. However, I ensured that the CA Cert previously used was valid and was able to be accessed by each of the nodes in my custom cluster.

So it is possible this may be a configuration issue, but seemed unlikely at the time of testing.

**Comment by markusewalker** [comment]
Still seeing issues with this on `v2.7.5-rc2`. See details below:

**ENVIRONMENT DETAILS**
- Rancher install: Docker
- Rancher version: `v2.7.5-rc2`
- Browser: Chrome

**TEST RESULTS**
|Scenario|Test Case|Result|
|---|---|---|
|1|As a standard user, provision a downstream RKE2 node driver cluster with a private registry with a unique CA cert bundle and validate there are no redundant entries for the CA cert bundle|:x:|

**REPRODUCTION STEPS**
1. On a client machine, configured a private registry that has tagged `v2.7.5-rc2` images to be used in Rancher.
2. Navigated over to Rancher in a browser.
3. As a standard user, provisioned a downstream RKE2 `v1.25.9+rke2r1` custom cluster with my earlier created private registry set to pull the container images.
     - Ensured that the private registry was configured with a CA Cert bundle defined.
4. The cluster never comes up `Active` due to the etcd node being stuck with an error stating `error applying plan -- check rancher-system-agent.service logs on node for more information, waiting for agent to check in and apply initial plan`.
     - Investigating the logs, I see the following:
```
May 25 00:44:52 ip-172-31-25-34 rancher-system-agent[87464]: time="2023-05-25T00:44:52Z" level=info msg="[c867ba1ca247d50a7e3e9166008d2a
039178dda85530424de46165fcc57c6e03_0:stdout]: {\"members\":[{\"ID\":8055567742603497234,\"name\":\"ip-172-31-25-34-cd5a0a25\",\"peerURLs
\":[\"https://172.31.25.34:2380\"],\"clientURLs\":[\"https://172.31.25.34:2379\"]}]}"
May 25 00:44:52 ip-172-31-25-34 rancher-system-agent[87464]: time="2023-05-25T00:44:52Z" level=info msg="[Applyinator] Command sh [-c cu
rl -f --retry 100 --retry-delay 5 --cacert /var/lib/rancher/rke2/server/tls/server-ca.crt https://localhost:9345/db/info | grep 'clientU
RLs'] finished with err: <nil> and exit code: 0"
May 25 00:44:52 ip-... rancher-system-agent[87464]: time="2023-05-25T00:44:52Z" level=info msg="[Applyinator] No image provided
, creating empty working directory /var/lib/rancher/agent/work/20230525-004452/c867ba1ca247d50a7e3e9166008d2a039178dda85530424de46165fcc
57c6e03_1"
May 25 00:44:52 ip-... rancher-system-agent[87464]: time="2023-05-25T00:44:52Z" level=info msg="[Applyinator] Running command: 
sh [-c cat /var/lib/rancher/rke2/server/db/etcd/name]"
May 25 00:44:52 ip-... rancher-system-agent[87464]: time="2023-05-25T00:44:52Z" level=info msg="[c867ba1ca247d50a7e3e9166008d2a
039178dda85530424de46165fcc57c6e03_1:stdout]: ip-172-31-25-34-cd5a0a25"
May 25 00:44:52 ip-... rancher-system-agent[87464]: time="2023-05-25T00:44:52Z" level=info msg="[Applyinator] Command sh [-c ca
t /var/lib/rancher/rke2/server/db/etcd/name] finished with err: <nil> and exit code: 0"
May 25 00:44:52 ip-... rancher-system-agent[87464]: time="2023-05-25T00:44:52Z" level=info msg="[Applyinator] No image provided
, creating empty working directory /var/lib/rancher/agent/work/20230525-004452/c867ba1ca247d50a7e3e9166008d2a039178dda85530424de46165fcc
57c6e03_2"
May 25 00:44:52 ip-... rancher-system-agent[87464]: time="2023-05-25T00:44:52Z" level=info msg="[Applyinator] Running command: 
sh [-c rke2 etcd-snapshot list --etcd-s3=false 2>/dev/null]"
May 25 00:44:52 ip-... rancher-system-agent[87464]: time="2023-05-25T00:44:52Z" level=info msg="[c867ba1ca247d50a7e3e9166008d2a
039178dda85530424de46165fcc57c6e03_2:stdout]: Name Location Size Created"
May 25 00:44:52 ip-172-31-25-34 rancher-system-agent[87464]: time="2023-05-25T00:44:52Z" level=info msg="[Applyinator] Command sh [-c rk
e2 etcd-snapshot list --etcd-s3=false 2>/dev/null] finished with err: <nil> and exit code: 0"
```

Additionally, I tried removing the CA cert bundle and selecting skip TLS checks, but I still receive the above error. I did not see this in `v2.7.2`, but I am consistently seeing this on `v2.7.5-rc2` with different private registries and different environments.

Reopening this issue as a result.

**Comment by Oats87** [comment]
As an update, I've been working with @markusewalker trying to reproduce this to debug it.

**Comment by markusewalker** [comment]
Further debugging this with @Oats87, I was unable to reproduce the failures seen in my earlier comment. As such, please find my latest successful test results.

**ENVIRONMENT DETAILS**
- Rancher install: Docker
- Rancher version: `v2.7-head`
- Browser: Chrome

**TEST RESULT**
|Scenario|Test Case|Result
|---|---|---|
|1|As a standard user, provision a downstream RKE2 node driver cluster with a private registry with a unique CA cert bundle and validate there are no redundant entries for the CA cert bundle|:white_check_mark:|
|2|As a standard user, provision a downstream RKE2 node driver cluster with two registry configurations with a unique CA cert bundle and validate there are no duplicate entries|:white_check_mark:|
|3|As a standard user, provision a downstream K3S node driver cluster without a private registry initially defined, edit the cluster configuration and include a private registry configuration with a unique CA cert bundle and validate there are no duplicate entries|:white_check_mark:|

**VALIDATION STEPS**

**Scenario 1**
1. On a client machine, configured an authenticated private registry that has tagged `v2.7.5-rc2` images to be used in Rancher.
2. Navigated over to Rancher in a browser.
3. As a standard user, provisioned a downstream RKE2 `v1.26.4+rke2r1` node driver cluster with my authenticated private registry.
     - Ensured that the private registry was configured with a CA cert bundle.
4. Validated that the cluster and nodes came up as `Active` in Cluster Management and Cluster Explorer.
5. Validated that all of the workloads are in an `Active` state.
_______

**Scenario 2**
1. On two client machines, configured two authenticated private registries, both with `v2.7.5-rc2` images tagged to be used in Rancher.
     - The CA cert bundles are the same in each registry.
2. Repeated scenario 1 steps 2-5, but provisioned a downstream RKE2 `v1.26.4+rke2r1` with both of my authenticated private registries.
     - Ensured that both registries used the same CA cert bundle.
3. Validated that the results were successful as mentioned in scenario 1.
_________

**Scenario 3**
1. On a client machine, configured an authenticated private registry that has tagged `v2.7.5-rc2` images to be used in Rancher.
2. Navigated over to Rancher in a browser.
3. As a standard user, provisioned a downstream K3S `v1.26.4+k3s1` cluster.
4. Once the cluster and nodes were `Active`, edited the cluster configuration to have my private registry configured.
5. Validated that the cluster and nodes came back up as `Active` in Cluster Management and Cluster Explorer.
6. Verified that all of the workloads are pulling their respective images from the defined private registry after editing the cluster's configuration.
