### ISSUE TITLE
[BUG] PSPs not removed in rke2 (custom) cluster when upgrading to 1.25

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#40981]
**Rancher Server Setup**
- Rancher version: v2.7.2-rc7
- Installation option (Docker install/Helm Chart): helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): rke2
- Proxy/Cert Details: valid, signed certs

**Information about the Cluster**
- Kubernetes version: v1.23.17+rke2r1 -> v1.25.7+rke2r1
- Cluster Type (Local/Downstream): downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): custom, running in ec2

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: standard user, cluster owner

**Describe the bug**

when upgrading to 1.25, rke2 warns the user that PSP is not supported and all resources will be removed as part of the upgrade. However, in this case the PSP resources were not removed which causes problems in the cluster, i.e. when upgrading charts that check for PSPs. 

**To Reproduce**

* provision a cluster on 1.23 with PSPs enabled (rke2 default embedded will suffice)
* install a chart i.e. cis benchmark 3.0.0
* wait for the chart to install
  * optional: run the benchmark
* upgrade the cluster to 1.25
  * observe the warning that states PSPs are removed when upgrading
  * wait for the cluster to come back to an active state
* upgrade the chart (for cis benchmark, you can enable pre-release versions and user 4.0.0-rc4)

**Result**
chart upgrade fails with error:
```
UPGRADE FAILED: unable to build kubernetes objects from current release manifest: resource mapping not found for name: "cis-psp" namespace: "" from "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
2023-03-25T05:07:07.954180708Z ensure CRDs are installed first
```

**Expected Result**

this indicates that PSPs were not properly removed from the rke2 cluster

**Screenshots**

**Additional context**

* this was originally found on a custom rke2 windows cluster with monitoring installed.

**Comment by prachidamle** [comment]
This behavior is expected if following is not followed while upgrading a cluster to 1.25:

Users are expected to:
- Upgrade Rancher to v2.7.2.
- Upgrade their charts to the latest v102.x.y version while still in Kubernetes v1.24 and remove their PSPs during this upgrade of charts by selecting the checkbox option to drop PSPs.
- Upgrade their clusters to Kubernetes v1.25 after the chart has been upgraded to drop PSP.

Removing PSPs is a process on the user side. This is meant to be done by upgrading the charts to v102.0.0 while still on Kubernetes v1.24. In this process, the Enable PodSecurityPolicies checkbox would be unchecked, which then results in PSPs being removed. If that has not been followed, after an upgrade to Kubernetes v1.25 has already been performed, a tool such as helm-mapkubeapis is required to remove lingering PSPs from an installed chart.

**Comment by prachidamle** [comment]
@slickwarren can you test this by following the above guideline to upgrade charts to drop PSP prior to k8s upgarde to 1.25

**Comment by markusewalker** [comment]
**QA TEST PLAN**

**Scenarios**
|Scenario|Test Case|
|---|---|
|1|As a standard user, provision a RKE2 v1.23 downstream custom cluster, install monitoring chart on the cluster, upgrade the cluster to v1.25 with no PSA, upgrade the chart and validate PSPs are removed from the cluster|
|2|As a standard user, provision a RKE2 v1.24 downstream node driver cluster, install monitoring chart on the cluster, upgrade the cluster to v1.25 with PSA `rancher-privileged` set, upgrade the chart and validate PSPs are removed from the cluster|
|3|As a standard user, provision a RKE2 v1.24 downstream node driver cluster, install monitoring chart on the cluster, upgrade the cluster to v1.25 with PSA `rancher-restricted` set, upgrade the chart and validate PSPs are removed from the cluster|
|4|As a standard user, provision a RKE2 v1.24 downstream node driver cluster, install monitoring chart on the cluster, upgrade the cluster to v1.25 with a custom PSACT set, upgrade the chart and validate PSPs are removed from the cluster|

**Comment by markusewalker** [comment]
Validated this against `v2.7-head`  https://github.com/rancher/rancher/commit/4a9b7ba441c951a619b8599a7409e6df6dfa34ba. See details below:

**ENVIRONMENT DETAILS**
- Rancher install: Helm
- Rancher version: `v2.7-head` https://github.com/rancher/rancher/commit/4a9b7ba441c951a619b8599a7409e6df6dfa34ba
- Browser: Chrome

**TEST RESULT**
|Scenario|Test Case|Result
|---|---|---|
|1|As a standard user, provision a RKE2 v1.23 downstream custom cluster, install monitoring chart on the cluster, upgrade the cluster to v1.25 with no PSA, upgrade the chart and validate PSPs are removed from the cluster|:white_check_mark:|
|2|As a standard user, provision a RKE2 v1.23 downstream node driver cluster, install monitoring chart on the cluster, upgrade the cluster to v1.25 with PSA `rancher-privileged` set, upgrade the chart and validate PSPs are removed from the cluster|:white_check_mark:|
|3|As a standard user, provision a RKE2 v1.24 downstream node driver cluster, install monitoring chart on the cluster, upgrade the cluster to v1.25 with PSA `rancher-restricted` set, upgrade the chart and validate PSPs are removed from the cluster|:white_check_mark:|
|4|As a standard user, provision a RKE2 v1.24 downstream node driver cluster, install monitoring chart on the cluster, upgrade the cluster to v1.25 with a custom PSACT set, upgrade the chart and validate PSPs are removed from the cluster|:white_check_mark:|

**VALIDATION STEPS**

**Scenario 1**
1. As a standard user, provisioned a RKE2 v1.23.17+rke2r1 downstream custom cluster.
2. Validated that the cluster and nodes came up as `Active` in Cluster Management and Cluster Explorer.
3. Installed the monitoring chart on the cluster successfully.
     - Ensured that the chart is at the second highest version and that PSPs were selected to install onto the chart.
4. Updated the monitoring chart to the highest version and deselected the option to have PSPs installed on the chart.
5. Upgraded the cluster to v1.25.7+rke2r1, with PSACT value `rancher-privileged`.
6. Validated that the cluster and nodes upgraded their K8s version and that the cluster came back up as `Active`.
7. Validated that all of the PSPs are removed.
______
**Scenario 2**
1. Repeated scenario 1, but used a RKE2 v1.24.11+rke2r1 downstream node driver instead for step 1.
2. While upgrading, I selected `rancher-privileged` as the PSACT to be configured in the cluster.
     - All steps were successful as mentioned in scenario 1.
______
**Scenario 3**
1. Repeated scenario 1, but used a RKE2 v1.24.11+rke2r1 downstream node driver instead for step 1.
2. While upgrading, I selected `rancher-restricted` as the PSACT to be configured in the cluster.
     - All steps were successful as mentioned in scenario 1.
______
**Scenario 4**
1. Repeated scenario 1, but used a RKE2 v1.24.11+rke2r1 downstream node driver instead for step 1.
2. While upgrading, I selected my custom PSACT value `rancher-baseline` as the PSACT to be configured in the cluster.
     - This custom PSACT has baseline set to warn, audit and enforce with the same namespaces excluded as found in `rancher-restricted`.
     - All steps were successful as mentioned in scenario 1.

**Comment by markusewalker** [comment]
Reopening issue to add test scenarios using tool `helm-mapkubeapis` tool. The test plan [comment](https://github.com/rancher/rancher/issues/40981#issuecomment-1490598786) is updated with the new scenarios and I will update this test result [comment](https://github.com/rancher/rancher/issues/40981#issuecomment-1490699186) once done.

If the tests pass, I will re-close this issue.

**Comment by markusewalker** [comment]
Test result has been updated with the new test scenarios involving `helm-mapkubeapis` tool. As they have passed, re-closing this issue.
