### ISSUE TITLE
[BUG] EKS hosted cluster removed through rancher is not cleaned up in AWS backend

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#40988]
**Rancher Server Setup**
- Rancher version: v2.7.2-rc7
- Installation option (Docker install/Helm Chart): helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): rke2, v1.24.9+rke2r1
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.24
- Cluster Type (Local/Downstream): downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): hosted, EKS

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: standard user, cluster owner

**Describe the bug**

when deleting a cluster through rancher, the cluster is not removed in the backend provider for AWS / EKS hosted clusters

**To Reproduce**

* deploy an EKS hosted cluster through rancher
* wait for the cluster to provision
* delete the cluster
* wait for the cluster to delete in the backend

**Result**
the EKS cluster is not removed in the backend

**Expected Result**

the cluster should remove in the backend for all hosted cluster types. 

**Additional Info**
* this appears to be a regression and does correctly delete in the backend on v2.7.1

**Comment by richardcase** [comment]
Tried this with `2.7.2.rc7` and haven't managed to reproduce the error.

@slickwarren - any chance you could share the logs for the **eks-config-operator** pod when it fails to delete?

**Comment by slickwarren** [comment]
could not reproduce either - will close for now
