### ISSUE TITLE
[BUG] Windows rke2 custom cluster - nodes stop displaying metrics after upgrading to 1.25

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#40982]
**Rancher Server Setup**
- Rancher version: v2.7.2-rc7
- Installation option (Docker install/Helm Chart): helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): rke2
- Proxy/Cert Details: valid, signed certs

**Information about the Cluster**
- Kubernetes version: v1.23.17+rke2r1 -> v1.25.7+rke2r1
- Cluster Type (Local/Downstream): downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): custom,  with windows workers, all running on ec2

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: standard user, cluster owner

**Describe the bug**

when using monitoring 101.0.0+up19.0.3, windows metrics are displaying properly. However after upgrading to 1.25, the metrics stop being posted though all the pods appear to be active in cattle-monitoring

**To Reproduce**

* deploy a custom rke2 cluster on 1.23
  * 3etcd, 2cp, 3linux workers, 3 windows workers
* wait for the cluster to become active
* install monitoring
* upgrade the cluster to 1.25
* wait for the upgrade to complete
* check monitoring metrics

**Result**
windows metrics no longer show

**Expected Result**

windows metrics should persist after upgrading k8s versions

**Screenshots**

<img width="635" alt="Screen Shot 2023-03-24 at 9 51 03 PM" src="https://user-images.githubusercontent.com/16691014/227698075-20212dcf-d8ed-4564-95ee-039aecfb82de.png">

**Additional context**

I was not able to upgrade the chart to see if that addresses the issue due to this bug: https://github.com/rancher/rancher/issues/40981

**Comment by prachidamle** [comment]
This can be tested, once the https://github.com/rancher/rancher/issues/40981 has been retested according to the steps mentioned there.

**Comment by ronhorton** [comment]
**Pass** verified in `v2.7.2-rc7`

1. rke2 cluster with k8s 1.23
2. installed monitoring
3. verified metrics displaying
4. upgraded to k8s 1.25
5. metrics displaying as expected after upgrade

![2023-03-30_13-28-43.png](https://zube.io/files/rancher/12cb0b758e756e55765a60b84ed12d87-2023-03-30_13-28-43.png)
![2023-03-30_13-10-54.png](https://zube.io/files/rancher/faf0772cd3547621d24e39b68a9c8558-2023-03-30_13-10-54.png)

**Comment by slickwarren** [comment]
seeing this issue again on v2.7.6-rc2 with monitoring 102.0.1+up40.1.2

**Comment by prachidamle** [comment]
@slickwarren just confirming we were able to upgrade the monitoring chart on 1.25? Or was this bug hit since psps were not removed prior to upgrading the chart? https://github.com/rancher/rancher/issues/40981

**Comment by slickwarren** [comment]
closing in favor of linked issue above. More context is available in that issue. But this was an upgrade from 1.25 -> 1.26
