### ISSUE TITLE
[BUG]chart repo pointing to release-v2.7 on downstream clusters when upgraded from rancher 2.7.1 to 2.7.2-rc7

### ISSUE THREAD

**Issue by ronhorton** [rancher/rancher#40990]
**Rancher Server Setup**
- Rancher version: `v2.7.2-rc7`
- Installation option (Docker install/Helm Chart): `Helm`
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): `RKE1`
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: `v1.24.9`
- Cluster Type (Local/Downstream): `Downstream ec2 RKE1`
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: `admin`

**Describe the bug**
rke1 cluster running on 2.7.1 rancher HA. upgraded ha to 2.7.2-rc7. the chart versions listed for edit/upgrade are still 101 versions. the new versions of the charts are not available. the charts repo is pointing to release-v2.7. 

**To Reproduce**
upgrade rancher to 2.7.2-rc7
edit/upgrade rancher-monitoring

**Result**
102 version of rancher monitoring not available. it's the versions shipping with 2.7.2. unable to upgrade charts.

**Expected Result**
102 versions of charts available for upgrade 

**Screenshots**

<img width="1743" alt="2023-03-27_16-00-26" src="https://user-images.githubusercontent.com/89212856/228053564-6ff2a0ee-bb1f-45c4-b2e6-4d4878016c6f.png">
<img width="1713" alt="2023-03-27_15-59-39" src="https://user-images.githubusercontent.com/89212856/228053589-5beb7599-8869-472c-a9ac-497a7c8968c0.png">

**Additional context**
local cluster does not have this issue

**Comment by prachidamle** [comment]
@PennyScissors pointed out that under userPreferences the setting to enable RC helm charts should be set
