### ISSUE TITLE
[SURE-5726] kubeconfig secret does not get updated when rancher service IP is updated

### ISSUE THREAD

**Issue by kkaempf** [rancher/rancher#41002]
#### Issue description:

See errors in logs and under continuous deployment that shows cluster in error state due to the following:
```
time="2022-12-19T23:16:29Z" level=error msg="error syncing 'fleet-default/c-lnvxm': handler import-cluster: Get \"https://192.168.149.236/k8s/clusters/c-lnvxm/version?timeout=15s\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers), requeuing" 
```

This seems to be due to the Rancher service IP being updated which is not caught by fleet. Under the local-kubeconfig secret in fleet-local as well as the <clustername>-kubeconfig secret under fleet-default, you will find that the server line still points to the old rancher service IP which causes these errors.

#### Troubleshooting steps:

Check fleet controller logs for affected clusters.

Check rancher service IP

Check fleet-local and fleet-default namespaces to see which <clusterName>-kubeconfig secrets have the old rancher service IP

#### Repro steps:

    force rancher service IP to update
    check if fleet service has updated secrets

#### Workaround:
Is workararound available and implemented? yes

Updating the secrets in fleet-local and fleet-default fixes this issue. The secrets with the naming convention <clustername>-kubeconfig in fleet-local and fleet-default namespaces need to have the server changed to use the new rancher service IP.  

#### Actual behavior
fleet secrets are not updated to reflect new rancher service IP, preventing fleet from reaching Rancher

#### Expected behavior:
fleet updates secrets to reflect new Rancher service IP and fleet continues to be able to reach Rancher.

#### Files, logs, traces:

```
$ kubectl get secret -n fleet-local local-kubeconfig -o json | jq -r .data.value | base64 -d
apiVersion: v1
clusters:

    cluster:
        certificate-authority-data: redacted
        server: https://192.168.149.236/k8s/clusters/local
      name: cluster
    contexts:
    context:
        cluster: cluster
        user: user
      name: default
    current-context: default
    kind: Config
    preferences: {}
    users:
    name: user
      user:
        token: redacted
    $ kubectl get services -n cattle-system rancher
    NAME      TYPE        CLUSTER-IP        EXTERNAL-IP   PORT(S)          AGE
    rancher   ClusterIP   192.168.131.201   <none>        80/TCP,443/TCP   190d

```

**Comment by Oats87** [comment]
@kkaempf this should actually be resolved through https://github.com/rancher/rancher/issues/40741 -- I guess I never saw this issue in the first place.

If possible, we should close this issue if you agree that the reported issue in this issue is the same as the one in 40741.

**Comment by snasovich** [comment]
Closing the issue based on the comment above. If it turns out to be something else, feel free to reopen it. But we're also confirming this on SURE-5726.

**Comment by sbulage** [comment]
@kkaempf This issue also has to test with the #41193 ? If Yes, then I don't see any milestone there. Can you please take a look at it? Thanks :slightly_smiling_face:
