### ISSUE TITLE
Update image for canalFlannel to `rancher/mirrored-flannelcni-flannel:v0.19.2` for rke1 k8s 1.24.x

### ISSUE THREAD

**Issue by Josh-Diamond** [rancher/rancher#41006]
**Rancher Server Setup**
- Rancher version: `2.7.2-rc7` or `2.7-head`
- Installation option (Docker install/Helm Chart):
`Docker` w/ `self-signed` certs

**Information about the Cluster**
- Kubernetes version: 1.24.x (rke1)

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
`admin`

**Describe the bug**
This issue was created to track changing the image for "canalFlannel" to `rancher/mirrored-flannelcni-flannel:v0.19.2`, for k8s 1.25. 

**To Reproduce**
1. Fresh install of rancher `v2.7.2-rc7`
2. Provision a downstream k8s 1.24 cluster + downstream k8s 1.25 cluster
3. Observe + compare the `canalFlannel` images used and pulled
4. Reproduced

**Result**
`canalFlannel` image in 1.24 is `v.0.17.0` and `canalFlannel` image in 1.25 is `v0.15.1`

**Expected Result**
versions should not degrade when updating a cluster from `1.24` => `1.25`

**Comment by jiaqiluo** [comment]
can be validated in the lastest v2.7-head

**Comment by Josh-Diamond** [comment]
Ticket #41006 - Test Results - ✅ 
---

Verified w/ Docker on a single-node instance using Rancher `v2.7-4a9b7ba441c951a619b8599a7409e6df6dfa34ba-head`:
1. Fresh install of rancher `v2.7-head`
2. Provision a downstream RKE1 k8s 1.25 cluster
3. Once `active`, observe "canalFlannel" version being used
4. Verified - "canalFlannel" version now reflects `v0.19.2` - [as expected]

**Comment by Josh-Diamond** [comment]
re-opening for further validations

**Comment by Josh-Diamond** [comment]
further validations (offline follow-ups) have been confirmed.  Closing out the issue now. ✅
