### ISSUE TITLE
[RFE] vSphere CSI chart updates to upstream v3.0.0 / v2.6.3

### ISSUE THREAD

**Issue by a-blender** [rancher/rancher#41017]
**Is your feature request related to a problem? Please describe.**

Upstream has released CSI plugin versions:

https://github.com/kubernetes-sigs/vsphere-csi-driver/releases/tag/v3.0.0 (support for k8s 1.26)
https://github.com/kubernetes-sigs/vsphere-csi-driver/releases/tag/v2.6.3

**Describe the solution you'd like**

- [x] Update CSI chart to the latest versions
- [x] Fix CSI versioning

TLDR CSI versioning: there has been a lot of confusion around the fact that the CSI chart for Rancher 2.7.x is named `102.0.0+upv2.6.2` so we want to fix versioning so that the 2.7 charts line is up to date on the latest driver image and is named `102.0.0+upv3.0.0`. k8s constraints in the chart will dictate what CSI driver image version is installed on a downstream cluster. If 1.26, then CSI driver 3.0.0 and if 1.25 then CSI driver 2.6.3, and so on. Upstream has a [compatibility matrix](https://docs.vmware.com/en/VMware-vSphere-Container-Storage-Plug-in/2.0/vmware-vsphere-csp-getting-started/GUID-D4AAD99E-9128-40CE-B89C-AD451DA8379D.html) that, when combined with the [versionOverrides block](https://github.com/rancher/vsphere-charts/blob/5bcff9e69b932cb9c86bd1061b2ee4b5367ecb60/charts/rancher-vsphere-csi/values.yaml#L124-L248), any user will be able to know what version of the CSI driver will be installed on their cluster and what is supported.

# Checklist for items that need completed

- [x] Update Image-mirror repo
- [x] Update manifests in rancher/vsphere-charts
- [x] Verify Slack hook notified about chart "release" in relevant channels
- [x] Update chart in rancher/charts
- [ ] Update chart in rancher/rke2-charts (RKE2 team)
- [ ] Updated RKE2 to consume new chart (RKE2 team)

**Comment by snasovich** [comment]
These bumps should also include https://github.com/rancher/rancher/issues/40727

**Comment by a-blender** [comment]
Images bumped in https://github.com/rancher/vsphere-charts/pull/55.

**Comment by a-blender** [comment]
See [test plan](https://github.com/rancher/rancher/issues/40908#issuecomment-1557701707)

**Comment by thaneunsoo** [comment]
### Testing ###
Below are the covered testcases for the CPI/CSI chart update

**Install CPI/CSI v1.26.0 chart on rke1 cluster** - **PASS**
1. Create a rancher server on v2.7-head on vSphere
- Login to vsphere engqa-7
- Create a vm from template, install docker, then run Rancher v2.7-head on it (this is behind the VPN so Rancher will be able to reach the downstream cluster)
2. Add vsphere credentials to Rancher
3. Provision a 3 node RKE1 vSphere cluster in Rancher
- 1 cp/etcd, 2 worker
- Add taint `node.cloudprovider.kubernetes.io/uninitialized=true:NoSchedule` to cp/etcd node
4. Verify downstream cluster is using `dev-v2.7` and not `release-v2.7`
5. Install CPI chart v1.26
- Validate that cpi pod has been deployed and is active
- Validate that the taint is removed
6. Install CSI chart v3.0.0
- Validate that a storage class is created for `csi`
- Validate that the user can deploy a workload with a mounted volume
  - deploy ranchertest/mytestcontainer
    - mount a volume before creating the deployment
- After workload deploys, add data to the volume\
  - ssh into workload - volume is mounted on root with the name you gave it when creating the volume
- Verify data is created in volume
  - check in vSphere - volumes, or check through rancher

**Install CPI/CSI v1.26.0 chart on rke2 cluster** - **PASS**
1. Create a rancher server on v2.7-head on vSphere
- Login to vsphere engqa-7
- Create a vm from template, install docker, then run Rancher v2.7-head on it (this is behind the VPN so Rancher will be able to reach the downstream cluster)
2. Add vsphere credentials to Rancher
3. Provision a 3 node RKE1 vSphere cluster in Rancher
- 1 cp/etcd, 2 worker
- Add taint `node.cloudprovider.kubernetes.io/uninitialized=true:NoSchedule` to cp/etcd node
4. Verify downstream cluster is using `dev-v2.7` and not `release-v2.7`
5. Install CPI chart v1.26
- Validate that cpi pod has been deployed and is active
- Validate that the taint is removed
6. Install CSI chart v3.0.0
- Validate that a storage class is created for `csi`
- Validate that the user can deploy a workload with a mounted volume
  - deploy ranchertest/mytestcontainer
    - mount a volume before creating the deployment
- After workload deploys, add data to the volume\
  - ssh into workload - volume is mounted on root with the name you gave it when creating the volume
- Verify data is created in volume
  - check in vSphere - volumes, or check through rancher

**Upgrade k8s version with CPI/CSI chart installed** - **PASS**
1. Create a rancher server on v2.7-head on vSphere
- Login to vsphere engqa-7
- Create a vm from template, install docker, then run Rancher v2.7 head on it (this is behind the VPN so Rancher will be able to reach the downstream cluster)
2. Add vsphere credentials to Rancher
3. Provision a 3 node RKE2 vSphere cluster in Rancher
- Use k8s version 1.25
- 1 cp/etcd, 2 worker
- Add taint `node.cloudprovider.kubernetes.io/uninitialized=true:NoSchedule` to cp/etcd node
4. Verify downstream cluster is using `dev-v2.7` and not `release-v2.7`
5. Install CPI chart v1.25
- Validate that cpi pod has been deployed and is active
- Validate that the taint is removed
6. Install CSI chart v2.6.2
- Validate that a storage class is created for `csi`
- Validate that the user can deploy a workload with a mounted volume
  - deploy ranchertest/mytestcontainer
    - mount a volume before creating the deployment
- After workload deploys, add data to the volume\
  - ssh into workload - volume is mounted on root with the name you gave it when creating the volume
- Verify data is created in volume
  - check in vSphere - volumes, or check through rancher
7. Upgrade k8s version
- Edit config
- Upgrade k8s version from 1.25 to 1.26
- Save
8. Wait for cluster to finish upgrading and come up active
9. Verify all CPI pods are running and healthy
10. Upgrade CPI chart to v1.26
- Validate that cpi pod is updated to correct version and is active
11. Upgrade CSI chart to v3.0.0
- Validate that csi storage class is updated to correct version and is active
12. Edit storage and add new data
- ssh into workload - volume is mounted on root with the name you gave it when creating the volume
- Verify data is added to volume

**Install CPI/CSI chart v1.25.1 on rke2 cluster** - **PASS**
1. Create a rancher server on v2.7-head on vSphere
- Login to vsphere engqa-7
- Create a vm from template, install docker, then run Rancher v2.7-head on it (this is behind the VPN so Rancher will be able to reach the downstream cluster)
2. Add vsphere credentials to Rancher
3. Provision a 3 node RKE1 vSphere cluster in Rancher
- 1 cp/etcd, 2 worker
- Add taint `node.cloudprovider.kubernetes.io/uninitialized=true:NoSchedule` to cp/etcd node
4. Verify downstream cluster is using `dev-v2.7` and not `release-v2.7`
5. Install CPI chart v1.25.1
- Validate that cpi pod has been deployed and is active
- Validate that the taint is removed
6. Install CSI chart v2.6.3
- Validate that a storage class is created for `csi`
- Validate that the user can deploy a workload with a mounted volume
  - deploy ranchertest/mytestcontainer
    - mount a volume before creating the deployment
- After workload deploys, add data to the volume\
  - ssh into workload - volume is mounted on root with the name you gave it when creating the volume
- Verify data is created in volume
  - check in vSphere - volumes, or check through rancher

**Install CPI/CSI chart v1.24.4 on rke2 cluster** - **PASS**
1. Create a rancher server on v2.7-head on vSphere
- Login to vsphere engqa-7
- Create a vm from template, install docker, then run Rancher v2.7-head on it (this is behind the VPN so Rancher will be able to reach the downstream cluster)
2. Add vsphere credentials to Rancher
3. Provision a 3 node RKE1 vSphere cluster in Rancher
- 1 cp/etcd, 2 worker
- Add taint `node.cloudprovider.kubernetes.io/uninitialized=true:NoSchedule` to cp/etcd node
4. Verify downstream cluster is using `dev-v2.7` and not `release-v2.7`
5. Install CPI chart v1.24.4
- Validate that cpi pod has been deployed and is active
- Validate that the taint is removed
6. Install CSI chart v2.6.3
- Validate that a storage class is created for `csi`
- Validate that the user can deploy a workload with a mounted volume
  - deploy ranchertest/mytestcontainer
    - mount a volume before creating the deployment
- After workload deploys, add data to the volume\
  - ssh into workload - volume is mounted on root with the name you gave it when creating the volume
- Verify data is created in volume
  - check in vSphere - volumes, or check through rancher

**Install CPI/CSI chart v1.23.4 on rke2 cluster** - **PASS**
1. Create a rancher server on v2.7-head on vSphere
- Login to vsphere engqa-7
- Create a vm from template, install docker, then run Rancher v2.7-head on it (this is behind the VPN so Rancher will be able to reach the downstream cluster)
2. Add vsphere credentials to Rancher
3. Provision a 3 node RKE1 vSphere cluster in Rancher
- 1 cp/etcd, 2 worker
- Add taint `node.cloudprovider.kubernetes.io/uninitialized=true:NoSchedule` to cp/etcd node
4. Verify downstream cluster is using `dev-v2.7` and not `release-v2.7`
5. Install CPI chart v1.23.4
- Validate that cpi pod has been deployed and is active
- Validate that the taint is removed
6. Install CSI chart v2.6.3
- Validate that a storage class is created for `csi`
- Validate that the user can deploy a workload with a mounted volume
  - deploy ranchertest/mytestcontainer
    - mount a volume before creating the deployment
- After workload deploys, add data to the volume\
  - ssh into workload - volume is mounted on root with the name you gave it when creating the volume
- Verify data is created in volume
  - check in vSphere - volumes, or check through rancher
