### ISSUE TITLE
[BUG] Unable to provision with private AWS ECR repository

### ISSUE THREAD

**Issue by jakefhyde** [rancher/rancher#41046]
**Rancher Server Setup**
- Rancher version: v2.6.3

**Information about the Cluster**
- Kubernetes version: v1.20.15-rancher1.2
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Node Driver or Custom

**Describe the bug**

Images are not are not able to be successfully pulled from an ECR registry.

**To Reproduce**

1. Populate ECR registry with images
2. For custom clusters, create AMI with credential helper
3. Add configuration snippet or attach IAM roles per https://rke.docs.rancher.com/config-options/private-registries#amazon-elastic-container-registry-ecr-private-registry-setup
4. Deploy a 2 node cluster: 1 etcd+controlplane, 1 worker.

**Result**

Failing to pull images from ECR: `[Error response from daemon: Get https://<REGISTRY_URL>/v2/mirror/docker.io/rancher/rke-tools/manifests/v0.1.78: no basic auth credentials]`.

**Expected Result**

Images are able to be pulled.

**Screenshots**

**Additional context**

SURE-4488

**Comment by markusewalker** [comment]
**QA TEST PLAN**

Scenarios
|Scenario|Test Case|
|---|---|
|1|As a standard user, provision a fresh install of downstream RKE1 node driver cluster with ECR as the private registry, validate that it provisions|
|2|As a standard user, provision a fresh install of downstream RKE1 custom cluster with ECR as the private registry, validate that it provisions, upgrade the K8s version and validate that it upgrades|

**Comment by markusewalker** [comment]
Unable to reproduce this on `v2.6.3`. See details below:

**ENVIRONMENT DETAILS**
- Rancher install: Helm
- Rancher version: `v2.7-head`
- Browser: Chrome

**TEST RESULT**
|Scenario|Test Case|Result
|---|---|---|
|1|As a standard user, provision a fresh install of downstream RKE1 node driver cluster with ECR as the private registry, validate that it provisions|:white_check_mark:|
|2|As a standard user, provision a fresh install of downstream RKE1 custom cluster with ECR as the private registry, validate that it provisions, upgrade the K8s version and validate that it upgrades|:white_check_mark:|

**VALIDATION STEPS**

**Scenario 1**
1. As a standard user, provisioned a downstream RKE1 v1.21.14-rancher1-1  node driver cluster with ECR as the private registry.
2. Validated that the cluster and nodes came up as `Active` in Cluster Manager and Cluster Explorer.
3. Validated that the images are using the ECR images and not the default Docker images.
_______
**Scenario 2**
1. As a standard user, provisioned a downstream RKE1 node driver cluster with ECR as the private registry.
     - Ensured I chose the second highest K8s version.
2. Validated that the cluster and nodes came up as `Active` in Cluster Manager and Cluster Explorer.
3. Validated that the images are using the ECR images and not the default Docker images.
4. Upgraded the K8s version to the highest version and  validated the cluster and nodes upgraded their K8s version and are still `Active`.

I will test on the latest v2.7-head and see if this is the case there as well. I will post in a separate comment.

**Comment by markusewalker** [comment]
Unable to reproduce this on `v2.7.2-rc8`. See details below:

**ENVIRONMENT DETAILS**
- Rancher install: Helm
- Rancher version: `v2.7.2-rc8`
- Browser: Chrome

**TEST RESULT**
|Scenario|Test Case|Result
|---|---|---|
|1|As a standard user, provision a fresh install of downstream RKE1 custom cluster with ECR as the private registry, validate that it provisions, upgrade the K8s version and validate that it upgrades|:white_check_mark:|

**VALIDATION STEPS**

**Scenario 1**
1. As a standard user, provisioned a downstream RKE1 v1.23.16-rancher2-1  node driver cluster (1 etcd/cp, 1 worker) with ECR as the private registry.
2. Validated that the cluster and nodes came up as `Active` in Cluster Manager and Cluster Explorer.
3. Validated that the images are using the ECR images and not the default Docker images.
4. Upgraded the K8s version to the highest version and validated the cluster and nodes upgraded their K8s version and are still `Active`.
