### ISSUE TITLE
Helm Install Rancher: [FATAL] error running the jail command: exit status 2

### ISSUE THREAD

**Issue by git-mb001** [rancher/rancher#41043]
What kind of request is this (question/bug/enhancement/feature request):
Question

Steps to reproduce (least amount of steps as possible):
- Install docker & K8s cluster on 3 nodes with OpenSUSE 15
- Install Rancher on the Kubernetes cluster with Private CA Signed Certificate

Result:
Pods fail to get started with error:
```
kubectl logs rancher-5f7bbc4967-8dvm5 -n cattle-system 
<cut> 
2023/04/03 06:06:38 [DEBUG] Catalog-cache running cleanup 
2023/04/03 06:06:44 [DEBUG] CreateJail: called for [driver-jail] 
2023/04/03 06:06:44 [DEBUG] CreateJail: jailPath is [/opt/jail/driver-jail] 
2023/04/03 06:06:44 [DEBUG] CreateJail: Running script to create jail for [driver-jail] 
2023/04/03 06:06:46 [FATAL] error running the jail command: exit status 2
```

Other details that may be helpful:
```
kubectl describe secret tls-rancher-ingress -n cattle-system
Name:         tls-rancher-ingress
Namespace:    cattle-system
Labels:       <none>
Annotations:  <none>

Type:  kubernetes.io/tls

Data
====
tls.crt:  2614 bytes
tls.key:  1704 bytes
```
Rancher install command:
`helm install rancher rancher-stable/rancher --namespace cattle-system --set hostname=rancher.*****.pl --set bootstrapPassword="admin" --set ingress.tls.source=secret --set privateCA=true --set debug=true --debug`

**Comment by jiaqiluo** [comment]
@git-mb001  The tracing level logs will output the error message returned from the jail-creating script and probably tell us why it fails. ([code](https://github.com/rancher/rancher/blob/4a07c2fe7e8089eeef4be5e158b603a3acddb82f/pkg/jailer/jailer.go#L65-L70)) 
Can you try it again but enable the trace level logging?

**Comment by git-mb001** [comment]
Hey jiaqiluo, Thanks for replay. I am running helm with --debug option and kubectl with --v=9, so I am not sure how to extend debug log..

**Comment by git-mb001** [comment]
@jiaqiluo I did manage to force rancher to write [TRACE] log, using command:
```
kubectl exec rancher-bdccb89d6-dgnzc -n cattle-system -c rancher -- loglevel --set trace
OK
```
Now I can see problem is with CRIO I guess:
```
<cut>
2023/04/05 09:29:52 [INFO] Applying CRD machinesets.cluster.x-k8s.io
2023/04/05 09:30:04 [TRACE] CreateJail: output from jail script for [driver-jail]: [tar: ./urandom: Cannot mknod: Operation not permitted
tar: ./zero: Cannot mknod: Operation not permitted
tar: ./tty: Cannot mknod: Operation not permitted
tar: ./full: Cannot mknod: Operation not permitted
tar: ./random: Cannot mknod: Operation not permitted
tar: ./null: Cannot mknod: Operation not permitted
tar: Exiting with failure status due to previous errors
]
2023/04/05 09:30:04 [FATAL] error running the jail command: exit status 2
```
