### ISSUE TITLE
[v2.7] KDM Update for K8s April patch release

### ISSUE THREAD

**Issue by mitulshah-suse** [rancher/rancher#41054]
# KDM Updates
TO BE RELEASED: **Enabled OOB post Rancher v2.7.2** 

| New Kubernetes Version | Min Rancher Version | Min RKE Version |
| ---------------------- | ------------------- | --------------- |
| 1.25.9-rancher1-1      | 2.7.2-patch0                 | 1.4.0-rc0             |
| 1.24.13-rancher1-1      | 2.6.7-patch0                 | 1.3.13-rc0             |

### Rancher System Images & Add-ons
**_Note: Please update system images and add-ons in the template as needed._**

TBD

# Developer Changelog
- Add templates for new K8s versions. If a template that hasn't been released yet already exists, update it in place.
- Update the default K8s version, and add or update the version information (`MinRancherVersion` and `MinRKEVersion`) in [k8s_version_info.go](https://github.com/rancher/kontainer-driver-metadata/blob/dev-v2.6/rke/k8s_version_info.go) for new K8s versions if needed (Use table from above).
- Confirm versions for system images, add-on templates are correct using versioning reference table from below (expand details to view the table). Update the table if new versions are introduced.
- Confirm add-on template version constraints in [template.go](https://github.com/rancher/kontainer-driver-metadata/blob/dev-v2.5/rke/templates/templates.go#L78) are correct using versioning reference table from below (expand details to view the table). Update the table if needed.

# Versioning Reference
<details>
<summary>
Expand for system images & add-on templates versioning table
</summary>
</br>

**_Note: Truncated repository names with a `*` indicates there are multiple images with that prefix. All repository names that match a truncated prefix should be checked for the same version stated in the table._**
**_For example: `rancher/weave-*` matches `weaveworks/weave-kube` and `weaveworks/weave-npc`, and they should both have the same version._**

## v1.25.9-rancher1-1
| Repository                                               | Tag                   |
| -------------------------------------------------------- | --------------------- |
| rancher/mirrored-coreos-etcd                             | v3.5.4     |
| rancher/hyperkube                                        | v1.25.9-rancher1      |
| rancher/rke-tools                                        | v0.1.87               |
| rancher/mirrored-k8s-dns-*                               | 1.22.8                |
| rancher/mirrored-cluster-proportional-autoscaler         | 1.8.6                 |
| rancher/mirrored-coreos-flannel                          | v0.15.1               |
| rancher/flannel-cni                                      | v0.3.0-rancher7       |
| rancher/mirrored-calico-*                                | v3.24.1               |
| weaveworks/weave-*                                       | 2.8.1                 |
| noiro/* (All ACI images)                                 | 5.2.3.5.1d150da       |
| rancher/mirrored-pause                                   | 3.6                 |
| rancher/nginx-ingress-controller                         | nginx-1.2.1-rancher1 |
| rancher/mirrored-nginx-ingress-controller-defaultbackend | 1.5-rancher1          |
| rancher/mirrored-jettech-kube-webhook-certgen            | v1.1.1                |
| rancher/mirrored-metrics-server                          | v0.6.2                |
| rancher/mirrored-coredns-coredns                         | 1.9.4                 |
| rancher/mirrored-cluster-proportional-autoscaler         | 1.8.6                 |
| rancher/kubelet-pause                                    | v0.1.6                |
| rancher/mirrored-k8s-dns-node-cache                      | 1.22.10                |

| Add-on Name   | Add-on Template Version Constraint |
| ------------- | ---------------------------------- |
| Calico        | calicov319                         |
| Canal         | canalv319                          |
| Flannel       | flannelv115                       |
| CoreDNS       | coreDnsv183                        |
| KubeDNS       | kubeDnsv116                        |
| MetricsServer | metricsServerv050                  |
| Weave         | weavev120                          |
| Aci           | aciv500                            |
| NginxIngress  | nginxIngressv110Rancher3                  |
| Nodelocal     | nodelocalv121                      |

## v1.24.13-rancher1-1
| Repository                                               | Tag                   |
| -------------------------------------------------------- | --------------------- |
| rancher/mirrored-coreos-etcd                             | v3.5.4     |
| rancher/hyperkube                                        | v1.24.13-rancher1      |
| rancher/rke-tools                                        | v0.1.87               |
| rancher/mirrored-k8s-dns-*                               | 1.21.1                |
| rancher/mirrored-cluster-proportional-autoscaler         | 1.8.5                 |
| rancher/mirrored-coreos-flannel                          | v0.15.1               |
| rancher/flannel-cni                                      | v0.3.0-rancher6       |
| rancher/mirrored-calico-*                                | v3.22.0               |
| weaveworks/weave-*                                       | 2.8.1                 |
| noiro/* (All ACI images)                                 | 5.2.3.2.1d150da       |
| rancher/mirrored-pause                                   | 3.6                 |
| rancher/nginx-ingress-controller                         | nginx-1.2.1-rancher1 |
| rancher/mirrored-nginx-ingress-controller-defaultbackend | 1.5-rancher1          |
| rancher/mirrored-jettech-kube-webhook-certgen            | v1.1.1                |
| rancher/mirrored-metrics-server                          | v0.6.1                |
| rancher/mirrored-coredns-coredns                         | 1.9.3                 |
| rancher/mirrored-cluster-proportional-autoscaler         | 1.8.5                 |
| rancher/kubelet-pause                                    | v0.1.6                |
| rancher/mirrored-k8s-dns-node-cache                      | 1.21.1                |

| Add-on Name   | Add-on Template Version Constraint |
| ------------- | ---------------------------------- |
| Calico        | calicov319                         |
| Canal         | canalv319                          |
| Flannel       | flannelv115                       |
| CoreDNS       | coreDnsv183                        |
| KubeDNS       | kubeDnsv116                        |
| MetricsServer | metricsServerv050                  |
| Weave         | weavev120                          |
| Aci           | aciv500                            |
| NginxIngress  | nginxIngressv110Rancher3                  |
| Nodelocal     | nodelocalv121                      |

</details>

**Comment by vivek-infracloud** [comment]
**Fresh install checks - PASS**

- On rancher version v2.7.2, KDM pointing to `dev-v2.7-2023-04-patches`, cluster creation succeeds for v1.25.9-rancher1-1on all network providers - canal/flannel/weave/calico.
- Network checks look good
- Canal network checks look good

-------------------
**Upgrade checks - PASS**
- On rancher v2.7.2, KDM pointing to release-v2.7, cluster creation succeeds for v1.25.6-rancher4-1 with all network providers.
- Pre-upgrade checks look good.
- Changed the KDM to point to `dev-v2.7-2023-04-patches` branch.
- Upgraded k8s version to v1.25.9-rancher1-1.
- Post upgrade checks look good.
-------------------
**RKE default k8s version - PASS** 
`dev-v2.7-2023-04-patches`, should have the default as v1.25.9-rancher1-1

```
 "RKEDefaultK8sVersions": {
  "0.3": "v1.16.3-rancher1-1",
  "default": "v1.25.9-rancher1-1"
```

**Comment by vivek-infracloud** [comment]
**Validated following [scenarios](https://github.com/rancher/rancher/issues/40668#issuecomment-1442358078) for kubelet version - PASS**

- On rancher v2.7.2, KDM pointing to dev-v2.7-2023-04-patches, provisioned k8s v1.25.9-rancher1-1 cluster.
- Cluster came Active with all the pods up and running
- Validated node version :

**Using kubectl :**

```
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.9", GitCommit:"a1a87a0a2bcd605820920c6b0e618a8ab7d117d4", GitTreeState:"clean", BuildDate:"2023-04-12T12:08:36Z", GoVersion:"go1.19.8", Compiler:"gc", Platform:"linux/amd64"}
```

```
> kubectl get nodes
NAME               STATUS   ROLES          AGE   VERSION
ip-172-31-11-239   Ready    etcd           17m   v1.25.9
ip-172-31-13-175   Ready    controlplane   17m   v1.25.9
ip-172-31-4-191    Ready    worker         15m   v1.25.9
ip-172-31-5-212    Ready    worker         14m   v1.25.9
```

**Kubelet logs :**
`"Kubelet version" kubeletVersion="v1.25.9"`

**Node yaml :**
```
  nodeInfo:
    kubeProxyVersion: v1.25.9
    kubeletVersion: v1.25.9
```
**On UI :**

On UI as well correct version is present
![Screenshot from 2023-04-17 18-49-02](https://user-images.githubusercontent.com/83208989/232495925-5d4d28bc-1719-4d76-a358-ca9051cd102e.png)

**Comment by vivek-infracloud** [comment]
RKE checks passed with RKE **v1.4.5-rc1** for k8s version **v1.24.13-rancher2-1** and **v1.25.9-rancher2-1**.

**Comment by vivek-infracloud** [comment]
Since all the tests passed, closing this issue.
