### ISSUE TITLE
Add 'Volumes From' when creating docker container does not create dropdowns properly

### ISSUE THREAD

**Issue by ShadowZero3000** [rancher/rancher#4105]
I'm brand new to Rancher, so it's quite possible that I'm doing something wrong, but this seems like a bug. Running the latest docker container from today, when I attempt to add a volume from another container I see the following:
![rancherbug](https://cloud.githubusercontent.com/assets/5047829/14010212/a9cdb042-f158-11e5-9032-b2f5697b63d5.PNG)

This appears to be an dynamic dom creation (ember?) that is placing the template instead of what it's supposed to be converted to maybe? I'm not sure, again, brand new to this.

Please let me know what else I can get you to help debug.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v0.63.1` Cattle: `v0.155.1` UI: `v0.95.0` |
|Access|`Disabled`|
|Route|`authenticated.project.help`|

**Comment by vincent99** [comment]
Yes, a curly brace got loose and migrated too far to the right.. Fixed in next release (which will be `1.0.0`) and also in the current `-rc2`.

https://github.com/rancher/rancher/issues/4030
