### ISSUE TITLE
RKE2 and K3S - KDM Update for K8s April patch release for Rancher 2.6

### ISSUE THREAD

**Issue by rancher-max** [rancher/rancher#41066]
# KDM Updates

| New Kubernetes Version  | Min Rancher Version | Max Rancher Version |
|                  :---:                  |              :---:               |               :---:               |
| v1.24.13+rke2r1                  | v2.6.7-alpha1             | v2.6.99 |
| v1.24.13+k3s1                    | v2.6.7-alpha1             | v2.6.99 |

# KDM Branch
https://github.com/rancher/kontainer-driver-metadata/tree/dev-v2.6-2023-04-patches

# Chart Changelog

| Chart Name  | New Version | Affected Kubernetes Version(s) |
|        :---:        |       :---:        |                     :---:                     |
| rke2-canal | v3.25.0-build2023020902 | v1.24.13+rke2r1 |
| rke2-cilium | 1.13.000 | v1.24.13+rke2r1 |
| harvester-csi-driver | 0.1.1600 | v1.24.13+rke2r1 |
| rke2-multus | v3.9.3-build2023010902 | v1.24.13+rke2r1 |
| rke2-calico | v3.25.002 | v1.24.13+rke2r1 |
| rke2-calico-crd | v3.25.002 | v1.24.13+rke2r1 |
| rke2-ingress-nginx | 4.5.201 | v1.24.13+rke2r1 |
| rke2-coredns | 1.19.402 | v1.24.13+rke2r1 |
| rancher-vsphere-cpi | 1.4.200 | v1.24.13+rke2r1 |
| rancher-vsphere-csi | 2.6.2-rancher200 | v1.24.13+rke2r1 |

# Argument Changelog

| Argument Name  | Affected Kubernetes Version(s) |
|        :---:           |                     :---:                     |
| | |

# Additional Notes

**Comment by rancher-max** [comment]
The Harvester CSI chart bump has been validated as part of the March release cycles as per https://github.com/rancher/rke2/issues/4038, https://github.com/rancher/rke2/issues/4039, and https://github.com/rancher/rke2/issues/4040. March was not released in Rancher, so this is where the chart is being bumped in KDM officially.

**Comment by caroline-suse-rancher** [comment]
Closing as complete

K3s PR:
https://github.com/rancher/kontainer-driver-metadata/pull/1121

RKE2 PR:
https://github.com/rancher/kontainer-driver-metadata/pull/1118

**Comment by ShylajaDevadiga** [comment]
This has been validated using https://github.com/rancher/kontainer-driver-metadata/tree/dev-v2.6-2023-04-patches
