### ISSUE TITLE
Remove wrangler/pkg/git dependency 

### ISSUE THREAD

**Issue by KevinJoiner** [rancher/rancher#41073]
**Rancher Server Setup**
- Rancher version: v2.7.2
- Installation option (Docker install/Helm Chart): N/A

**Information about the Cluster**
- Kubernetes version: N/A

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: N/A

**Describe the bug**
Wrangler will be removing its pkg git https://github.com/rancher/wrangler/issues/249. We will need to remove our usage of this package in Rancher. Currently, the package is only being used by [catalogv2](https://github.com/rancher/rancher/blob/4a07c2fe7e8089eeef4be5e158b603a3acddb82f/pkg/catalogv2/git/download.go#L15)

We should evaluate using a maintained package such as [go-git](https://github.com/go-git/go-git) instead of implementing a separate version.

**Comment by macedogm** [comment]
FYI @pjbgf

**Comment by pjbgf** [comment]
@KevinJoiner let me know whether any help is needed with `go-git` adoption, I have actively contributed to that project on my free time in the last year or so.

**Comment by mattfarina** [comment]
@KevinJoiner Should a change to `go-git` be part of the migration away from wranglers git package? That would be a non-trivial change to test/QA. Wranglers git package exec's out to `git` which is included in the container images. `go-git` is an independent implementation written in Go. No `git` binary included. These are very different code paths to validate.

Alternatively, we could copy the 5 functions, 2 structs, and 1 constant over from wranger git to the Rancher codebase. It's a smaller change as a first step that could be refined in a follow-up.

I only bring this up to separate a change so we can upgrade Wrangler from an overhaul of the git usage.

**Comment by KevinJoiner** [comment]
@mattfarina That is an option. We want to remove the use of executing the git binary for general security best practices. So the suggestion was made to address both the desire to remove git from Wrangler and the execution of an external binary. That said, you are correct; this is a larger burden for QA, so we are not planning on this going into the next release.

**Comment by cbron** [comment]
Adding this to q3 2023 milestone as it's critical for adding automated tests, and it's in next-up so seems like that was plan anyway.

**Comment by ronhorton** [comment]
Testing: testing will be around the apps & marketplace feature in rancher. specifically, charts refresh and anything with a git pull when charts are updated.

**Comment by PennyScissors** [comment]
Confirmed with @gunamata this is done and can be closed
