### ISSUE TITLE
[BUG] goroutine leak in  statsaggregator.go#callWithTimeout

### ISSUE THREAD

**Issue by erkki** [rancher/rancher#41070]
**Rancher Server Setup**
- Rancher version: 2.6.9
- Installation option (Docker install/Helm Chart): EKS

**Information about the Cluster**
- Kubernetes version: v1.22.17
- Cluster Type (Local/Downstream): Local

**User Information**

**Describe the bug**
`callWithTimeout` in `statsaggregator.go` (https://github.com/rancher/rancher/blob/release/v2.7/pkg/controllers/management/clusterstats/statsaggregator.go#L306-L317) leaks goroutines when timeout fires; the done chan is not closed.
Furthermore, the entire `callWithTimeout` method is probably not needed and instead `Discovery`  (https://github.com/rancher/rancher/blob/release/v2.7/pkg/controllers/management/clusterstats/statsaggregator.go#L215) should be run with a reduced k8s client timeout (default is 45s, which probably lead to the `callWithTimeout` addition).

**To Reproduce**
With a lot of disconnected clusters (in our case over 200) the timeout fires often, leading to a monotonic growth of number of goroutines and stack memory usage.

**Result**
Goroutine leaks

**Expected Result**
No leakage

**Screenshots**
`go_goroutines{service="rancher"}` counts before and after fix applied
<img width="1716" alt="Screen Shot 2023-04-05 at 8 59 30" src="https://user-images.githubusercontent.com/3516/229995196-1fee2956-0138-48fb-ac32-b6f0d38df714.png">

**Additional context**
Test fix was applied, results visible in the screenshot
```--- a/pkg/controllers/management/clusterstats/statsaggregator.go
+++ b/pkg/controllers/management/clusterstats/statsaggregator.go
@@ -307,7 +307,7 @@ func callWithTimeout(do func()) {
        done := make(chan struct{})
        go func() {
                do()
-               done <- struct{}{}
+               close(done)
```

**Comment by erkki** [comment]
Depending on the fix here, another issue is that there is a data race in https://github.com/rancher/rancher/blob/release/v2.7/pkg/controllers/management/clusterstats/statsaggregator.go#L221

It would be prudent to either use locks here or move the version assignement out of the `callWithTimeout` block.

**Comment by rmweir** [comment]
@erkki fix for go routine leak has been merged and was easy enough to identify on its own. Can you create a new issue for the data race?

**Comment by rmweir** [comment]
Release note:
`A memory leak related to clusters whose kube-api cannot be reached by rancher has been fixed. An example of such clusters are ones that have been shutdown or are blocked due to network policies.`

**Comment by rmweir** [comment]
This was validated by the customer.
