### ISSUE TITLE
When scale change for a service returns failure , there is no indication in the UI about this failure.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#4107]
Rancher Version: upgraded from v0.63.1 -> v1.0.0-rc2

Had a service with name - "test1--2" which was allowed as a valid service name in previous releases, but considered invalid in this release.

Try to update the scale of this service using the scale "+" option in service detail view.

Service scale increases . But service does not scale since API returned the following error:
```
{"id":"90cb8dd9-314b-43bb-bb5a-72d32a40ba0d","type":"error","links":{},"actions":{},"status":422,"code":"InvalidCharacters","message":null,"detail":null,"fieldName":"name"}
```

UI does not show any indication that this action did not succeed.

**Comment by tfiduccia** [comment]
Version - v1.2.0-pre2-rc2
Verified fixed
