### ISSUE TITLE
[RFE] Fix vSphere CSI images installed by default

### ISSUE THREAD

**Issue by a-blender** [rancher/rancher#41098]
**Is your feature request related to a problem? Please describe.**

Fix CSI default images! The image versions for the CSI driver we install in association with kubernetes versions is backwards. 2.7.0 supports k8s 1.23-1.25 but we are installing driver `2.5.2` by default.

**Describe the solution you'd like**

We should be installing the latest CSI driver image that supports kubernetes 1.25 / latest by _default_, with the options in values.yaml to install other images if the kubernetes version is not latest

# Checklist for items that need completed

- [x] Update Image-mirror repo
- [x] Update manifests in rancher/vsphere-charts
- [x] Verify Slack hook notified about chart "release" in relevant channels
- [ ] Update chart in rancher/charts
- [ ] Update chart in rancher/rke2-charts (RKE2 team)
- [ ] Updated RKE2 to consume new chart (RKE2 team)

SURE-6083

**Comment by thaneunsoo** [comment]
Testing will be covered while testing this issue here. Testplan can also be found here. [41017](https://github.com/rancher/rancher/issues/41017#issuecomment-1555160092)

**Comment by a-blender** [comment]
This has been an outstanding issue for a while and a fix has been included in @brandond's PR https://github.com/rancher/vsphere-charts/pull/55 to set CSI/CPI default cloud controller images to `latest` to make it obvious when version overrides are not working properly.
