### ISSUE TITLE
Add a link checker to verify links in install docker repo are pointing to the latest version of the script

### ISSUE THREAD

**Issue by mitulshah-suse** [rancher/rancher#41096]
**Description:** 
Add a link checker to the CI setup in the install-docker repo, to check if the link created in the /dist directory is always pointing to the latest version available for that particular docker version.

For example: 20.10.sh link should always point to the latest version of 20.10.xx.sh script present in the /dist directory.

**Comment by snasovich** [comment]
PR merged, feel free to close @mitulshah-suse (@rishabhmsra - please handle while Mitul out)

**Comment by mitulshah-suse** [comment]
Closing this since PR is merged and validation is running fine.
