### ISSUE TITLE
Routing error when deploying Swarm templates

### ISSUE THREAD

**Issue by LLParse** [rancher/rancher#4109]
Rancher Version: 1.0.0-rc2

Docker Version: 1.10.3

OS: Boot2Docker version 1.10.3

Steps to Reproduce: 
1. Create a Swarm environment
2. Navigate to catalog, and select details for any entry
3. Select a version and click launch

Results: The user is routed to the swarm services page

Expected: The user is routed to the swarm projects page

**Comment by tfiduccia** [comment]
Version - v1.0.0-rc4
Verified fixed
