### ISSUE TITLE
Machine error messages should be similar

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#411]
v0.14.2

Steps:
1.  Go to Add Host
2.  Select DO
3.  Fill out information and leave the Access Token out
4.  Create (will give you error message stating "Access Token is required")
5.  Fill in Access Token but remove Name
6.  Create (will give you error message stating "Validation failed: name")

Results:
Access Token and Name field are both required but the error messages are different

Expected;
Access Token and Name field are both required and should both should state "<filed name> is required"

**Comment by vincent99** [comment]
4. comes from the UI, 6 from the backend/api...  There is some validation on the client side of required fields now, so you'll get differently inconsistent errors.

**Comment by tfiduccia** [comment]
Closing - lack of interest or complaints from customers.
