### ISSUE TITLE
Local docker host duplicates

### ISSUE THREAD

**Issue by maZahaca** [rancher/rancher#4111]
Rancher Version: v0.63.1

Docker Version: 1.9.1

OS: OS x 10.10.4

Steps to Reproduce: I've added a local docker host one time

Results: Somehow, after sometime spent I see my local host added twice and three times.

Expected: Just one host, which was really added.

![](https://i.gyazo.com/a43919a8348582f7e4e865bf9453c57f.png)

**Comment by deniseschannon** [comment]
At the bottom of this closed issue, it explains why this is occurring. 

https://github.com/rancher/rancher/issues/936

**Comment by deniseschannon** [comment]
@maZahaca Let me know if you have further questions.

**Comment by maZahaca** [comment]
@deniseschannon Did I understand this point correctly and on regular linux machines it will be fine? I consider Rancher to run in production. But unfortunately, we have to restart our hosts sometime.

**Comment by deniseschannon** [comment]
Yes, on regular machines it should be fine.
