### ISSUE TITLE
[RFE] Update EKS regions to include eu-south-2  (Spain)

### ISSUE THREAD

**Issue by agorosti** [rancher/rancher#41111]
Eu-south-2 region was added more than 3 months ago,  allowing Spanish user an specific region to them with a very low latency when compared to other regions.

However,  eu-south-2 does not appears on the list of available regions on Rancher (I am currently using Rancher 2.7.1)

Can you please add that new region asap ?

Thks!

**Comment by orest-p** [comment]
same issue please add region asap

**Comment by petilolz** [comment]
2.7.4 still missing

**Comment by petilolz** [comment]
Sorry for the double post, I just realized that in 2.7.5 it is available, but I also did a manual step in my AWS account. The region is not enabled by default, so it is possible that enabling it would be functional in 2.7.4.
You can enable the region from this link
https://us-east-1.console.aws.amazon.com/billing/home?region=us-east-1#/account?AWS-Regions

@orest-p @agorosti
