### ISSUE TITLE
Shell text selection is offset if page is scrolled

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#4112]
Rancher Version:v1.0.0-rc2

Steps to reproduce the problem:
Have many containers deployed in the setup , so you will have to scroll down the "Hosts" page to pick the container.

Use "Execute Shell" option to launch container shell.
Run few command in the shell and try to hight light few lines.

Notice that the highlight actually happens in the end of the screen.
<img width="935" alt="screen shot 2016-03-24 at 11 47 32 am" src="https://cloud.githubusercontent.com/assets/4266958/14028030/c3254334-f1b7-11e5-9813-a4048d8d0c19.png">

**Comment by tfiduccia** [comment]
Version - master 7/8
Verified fixed

Sangeetha, did you want to check to make sure it's working for you as well.

**Comment by sangeethah** [comment]
@tfiduccia , I dont have anything specific to test , if u have already verified it.
