### ISSUE TITLE
Deleting v2prov cluster leads to vague messaging

### ISSUE THREAD

**Issue by Oats87** [rancher/rancher#41129]
Deleting a v2prov cluster does not properly trickle feedback to the user via the UI. The cluster will look like the screen shot when it is deleting.

We should update the planner controller to noop and set a condition stating we're deleting the cluster.

<img width="2749" alt="Screenshot 2023-04-11 at 8 19 17 AM" src="https://user-images.githubusercontent.com/30601846/231210198-0cc99707-3d1a-401f-aec4-b562d8c26ec2.png">

SURE-6268

**Comment by sowmyav27** [comment]
When validating: Verify the state of the cluster is `Deleting` and the message should show something related to "Deleting cluster"

**Comment by slickwarren** [comment]
Lets also be on the lookout for the affect on other cluster states, like updating or unavailable.

**Comment by Josh-Diamond** [comment]
Ticket #41129 - Test Results - ✅ 
---

Verified with HA Helm Rancher on `v2.7-1ae8ca94691cd2a5a6d6732da4a8670af6206f0f-head`:
1. Fresh install of rancher `v2.7-head`
2. Provision a downstream RKE2 AWS Node driver cluster
3. Observe cluster states as cluster provisions; `reconcile => updating => active`
4. Once `active`, scale up nodes and observe cluster states during the process; `updating => active`
5. Delete the cluster and observe cluster's state and message; `Removing: resource scheduled for deletion`
6. Verified - All cluster states and messages as expected for each requested operation

Screenshot:
<img width="351" alt="Screenshot 2023-05-17 at 2 16 31 PM" src="https://github.com/rancher/rancher/assets/46494969/603bf95c-1fda-45a9-aeb4-d2e384a27df1">
