### ISSUE TITLE
[BUG] Rancher managed RKE2 clusters stuck in "Waiting for probes: kube-controller-manager, kube-scheduler"

### ISSUE THREAD

**Issue by AlexisDucastel** [rancher/rancher#41125]
As the issue occurs on quite every cluster we own, I try to sum up version information for all of them :

**Rancher Server Setup**
- Rancher version: 2.6.9 and 2.7.1
- Installation option (Docker install/Helm Chart):
   - HeIm chart on RKE2 cluster version 1.24
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: 
- Cluster Type (Local/Downstream):
   - Downstream RKE2 Custom (version 1.24.7+rek2r1, 1.24.8+rke2r1, 1.24.9+rke2r2)

**User Information**
- What is the role of the user logged in? 
  - Admin

**Describe the bug**
On all our clusters, upgrades are frozen with one/multiple controlplane node(s) stuck in state `Waiting for probes: kube-controller-manager, kube-scheduler`.

**To Reproduce**
Not sure how to reproduce it, but all our clusters have hundreds days of run time, and they did not have any problem prior to Rancher 2.6.9 / Kubernetes version 1.24.7, but we have mix of cluster with Rancher 2.6.9 and 2.7.1 with clusters in 1.24.7 to 1.24.9. 
The problem appears after we edit the cluster to upgrade to a newer version.

**Result**

Upgrade is stuck, waiting for on or more controlpane stuck in state `Waiting for probes: kube-controller-manager, kube-scheduler`.

**Expected Result**

We expect upgrades to work without being stuck.

**Screenshots**

Ex cluster 1 (on controlplane impacted) :
![image](https://user-images.githubusercontent.com/1911945/231137741-921b1bcc-f939-4ff1-ad36-8120c4b2c860.png)

Ex cluster 2 (all controlplanes impacted) :
![image](https://user-images.githubusercontent.com/1911945/231137652-98f3edd2-25ac-49dc-a483-3d4afd7344a4.png)

**Additional context**
We tried to upgrade a stuck cluster that was stuck going from 1.24.7 to 1.24.9, by upgrading to 1.24.11, nothing happened. When we restarted `rancher-system-agent` the node was effectively in 1.24.11, but still stuck in state `Waiting for probes: kube-controller-manager, kube-scheduler`.
(SURE-6264)

**Comment by AlexisDucastel** [comment]
Clusters are healthy from k8s point of view, ETCD cluster is healthy with all members sync, scheduling and controllers are working correctly.

**Comment by AlexisDucastel** [comment]
Note: This only affects rke2 custom clusters managed by Rancher, for cluster deployed manually with RKE2 and then imported into Rancher upgrades works without any issue.

**Comment by AlexisDucastel** [comment]
For information, here are some logs of rancher-system-agent, and kubelet : 

Here is  rancher-system-agent log filtered on errors :
```
# journalctl -u rancher-system-agent -n 2000 |grep -i error
Apr 10 13:11:35 <nodename> rancher-system-agent[50346]: time="2023-04-10T13:11:35Z" level=error msg="[K8s] received secret to process that was older than the last secret operated on. (369730905 vs 369730954)"
Apr 10 13:11:35 <nodename> rancher-system-agent[50346]: time="2023-04-10T13:11:35Z" level=error msg="error syncing 'fleet-default/custom-6ab162c666c9-machine-plan': handler secret-watch: secret received was too old, requeuing"
```

With crictl, I can tell that both kube-controller-manager-<node> and kube-scheduler-<node> are Running
In kubelet log there are several errors talking about `failed to sync secret cache: timed out waiting for the condition` or like this one :
```
E0410 22:34:51.109948    1396 pod_workers.go:965] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"kube-controller-manager\" with CrashLoopBackOff: \"back-off 10s restarting failed container=kube-controller-manager pod=kube-controller-manager-<node-name>_kube-system(57585a0305e4e46df816ebab263926f3)\"" pod="kube-system/kube-controller-manager-<node-name>" podUID=57585a0305e4e46df816ebab263926f3
```

**Comment by AlexisDucastel** [comment]
By checking certificate validity, we can find that the kube-controller-certificate is indeed expired.
```
# openssl x509 -text -in /var/lib/rancher/rke2/server/tls/kube-controller-manager/kube-controller-manager.crt | grep -A 2 Validity
        Validity
            Not Before: Dec 29 13:14:28 2021 GMT
            Not After : Dec 29 13:14:28 2022 GMT
```

**Comment by r65535** [comment]
I'm getting the same problem on my downstream clusters that are over a year old. I'm running:
Rancher: `v2.7.2`
RKE2: `v1.24.12+rke2r1`

Have tried rotating all certs through the rancher UI, and manually by running the commands on [this](https://docs.rke2.io/advanced#certificate-rotation) page, but neither has fixed the problem.

**Comment by ron1** [comment]
@Oats87 FYI.

**Comment by AlexisDucastel** [comment]
If you get this error : 
```
Command 'crictl' not found, ...
```
You just have to set env var to make crictl available and working :
```
export CRI_CONFIG_FILE=/var/lib/rancher/rke2/agent/etc/crictl.yaml
export CONTAINERD_ADDRESS=unix:///run/k3s/containerd/containerd.sock
export PATH=$PATH:/var/lib/rancher/rke2/bin
```

**Comment by AlexisDucastel** [comment]
@Oats87 Maybe fleet or rancher plan should just remove certificate prior to restart controller, scheduler, and every process that have a https self-signed certificate probe ?

**Comment by r65535** [comment]
@AlexisDucastel - thanks for the bash steps above! 😄 

That's fixed the issue on all of our clusters 🥳

**Comment by Oats87** [comment]
this requires testing to ensure we won't cause an outage unnecessarily if we remove the certs from disk from under the components. I don't think it'll be an issue, but I know the probes will fail temporarily (which is to be expected when restarting rke2/k3s anyway)

**Comment by borrown** [comment]
@AlexisDucastel I really appreciate your description and the steps followed when exposing this issue. It saved me a lot of time.

**Comment by funilrys** [comment]
I can confirm that @AlexisDucastel steps (CF: [Step 1](https://github.com/rancher/rancher/issues/41125#issuecomment-1506667795) ; then [Step 2](https://github.com/rancher/rancher/issues/41125#issuecomment-1506620040)) solve the issue. 
Can someone from @rancher/all please look into this, or at least give official guidance ?

**Comment by Oats87** [comment]
https://github.com/rancher/rancher/pull/41459 adds e2e tests for certificate rotation

**Comment by snasovich** [comment]
@Josh-Diamond , with https://github.com/rancher/rancher/issues/41613 determined as the root cause for the reopen in "To Test" now, moving this one "To Test" as well. cc: @Sahota1225

**Comment by Josh-Diamond** [comment]
Ticket #41125 - Test Results - ✅ 
---

Verified with HA Helm Rancher on `v2.7-6ce75a0b57ad9e88cf135254a9b3b40082788eb6-head`:
1. Fresh install of rancher `v2.7-head`
2. Provision a downstream RKE2 AWS Node driver cluster - [ i used a single-node instance w/ k8s `v1.26.4+rke2r1` ]
3. Once `active`, ssh into instance, and grab expiration date of `kube-scheduler` cert by running the following command:
```
openssl x509 -enddate -noout -in /var/lib/rancher/rke2/server/tls/kube-scheduler/kube-scheduler.crt
```
4. Note the expiration date:
```
notAfter=May 23 14:49:52 2024 GMT
```
5. Grab expiration date of `kube-controller-manager` cert by running the following command:
```
openssl x509 -enddate -noout -in /var/lib/rancher/rke2/server/tls/kube-controller-manager/kube-controller-manager.crt
```
6. Note the expiration date:
```
notAfter=May 23 14:49:52 2024 GMT
```
7. From Rancher UI, rotate certificates by navigate to `Cluster Management > Cluster > Rotate certificates > Rotate all service certificates` and selecting `Rotate`
8. Once cluster is `active`, ssh back into instance and check if certs have been rotated:
  
   - `kube-scheduler`:
   ```
   notAfter=May 23 15:02:41 2024 GMT
   ```
   - `kube-controller-manager`:
   ```
   notAfter=May 23 15:02:41 2024 GMT
   ```
9. Verified - `kube-scheduler` cert is rotated; as expected
10. Verified - `kube-controller-manager` cert is rotated; as expected

**Comment by emoxam** [comment]
It's wonderfull that there is still no fix!

**Comment by Rodri9o** [comment]
> Solution found ! Thanks for the hint Chris Kim and brandond on Rancher Community Slack !
> 
> There is no official solution right now, but here is the manual fix that worked for me, you may launch these commands on every nodes that is stuck in `Waiting for probes: kube-controller-manager, kube-scheduler` state (aka: controlplane nodes).
> 
> Here is a shell command to check if probes are okay or not :
> 
> ```
> (
> curl  --cacert /var/lib/rancher/rke2/server/tls/kube-controller-manager/kube-controller-manager.crt \
>   https://127.0.0.1:10257/healthz >/dev/null 2>&1 \
>   && echo "[OK] Kube Controller probe" \
>   || echo "[FAIL] Kube Controller probe";
> 
> curl --cacert /var/lib/rancher/rke2/server/tls/kube-scheduler/kube-scheduler.crt \
>   https://127.0.0.1:10259/healthz >/dev/null 2>&1  \
>   && echo "[OK] Scheduler probe" \
>   || echo "[FAIL] Scheduler probe";
> )
> ```
> 
> And below commands I used to force certificate rotation on failed probes :
> 
> ```
> echo "Rotating kube-controller-manager certificate"
> rm /var/lib/rancher/rke2/server/tls/kube-controller-manager/kube-controller-manager.{crt,key}
> crictl rm -f $(crictl ps -q --name kube-controller-manager)
> 
> echo "Rotating kube-scheduler certificate"
> rm /var/lib/rancher/rke2/server/tls/kube-scheduler/kube-scheduler.{crt,key}
> crictl rm -f $(crictl ps -q --name kube-scheduler)
> ```
> 
> Enjoy !

This is not a solution. Yet SUSE support, which is horrendous, keep referencing this post as a solution. I have informed my director not to renew SUSE Rancher support. In fact, we should be moving off Rancher. Never seen anything like it. Absolutely disgusting support.

**Comment by Rodri9o** [comment]
> It's wonderfull that there is still no fix!

@emoxam -- I agree wholeheartedly. SUSE Support horrendous. In fact, they actually point to this closed issue as a solution for the bug **Waiting for probes: kube-controller-manager, kube-scheduler**

**Comment by snasovich** [comment]
@Rodri9o , I'm sorry to hear about your dissatisfaction with the support received.

However, please note that this issue is closed as fixed in 2.7.5 as per code changes in [this PR](https://github.com/rancher/rancher/pull/41398) the certificates that may result in cluster getting stuck on upgrade are now also rotated when using "Rotate Certificates" feature. It's highly recommended to rotate certificates periodically (at least once a year) to ensure they do not expire.

The [comment](https://github.com/rancher/rancher/issues/41125#issuecomment-1506620040) referenced is a workaround that can be applied if you're running Rancher versions prior to 2.7.5 and/or got into the situation described in this issue.

Could you please clarify what your expectations for the fix? Please note that it's not impossible for you to be running into some other issue that manifests similarly.

@emoxam , you reported quite recently that this issue is not fixed. Please feel free to chime in with more information.

**Comment by alphabet5** [comment]
These certs would not be generated with a wide variety of rancher versions, and cluster versions.

All rke2 custom clusters, installed by rancher. 

This was the fix.

```
timeout 1 openssl s_client -connect 127.0.0.1:10257 -showcerts 2>&1 | grep -A 19 -m 1 'BEGIN CERTIFICATE' | sudo tee /var/lib/rancher/rke2/server/tls/kube-controller-manager/kube-controller-manager.crt

timeout 1 openssl s_client -connect 127.0.0.1:10259 -showcerts 2>&1 | grep -A 19 -m 1 'BEGIN CERTIFICATE' | sudo tee /var/lib/rancher/rke2/server/tls/kube-scheduler/kube-scheduler.crt
```

**Comment by thyarles** [comment]
> Solution found ! Thanks for the hint Chris Kim and brandond on Rancher Community Slack !
> 
> There is no official solution right now, but here is the manual fix that worked for me, you may launch these commands on every nodes that is stuck in `Waiting for probes: kube-controller-manager, kube-scheduler` state (aka: controlplane nodes).
> 
> Here is a shell command to check if probes are okay or not :
> 
> ```
> (
> curl  --cacert /var/lib/rancher/rke2/server/tls/kube-controller-manager/kube-controller-manager.crt \
>   https://127.0.0.1:10257/healthz >/dev/null 2>&1 \
>   && echo "[OK] Kube Controller probe" \
>   || echo "[FAIL] Kube Controller probe";
> 
> curl --cacert /var/lib/rancher/rke2/server/tls/kube-scheduler/kube-scheduler.crt \
>   https://127.0.0.1:10259/healthz >/dev/null 2>&1  \
>   && echo "[OK] Scheduler probe" \
>   || echo "[FAIL] Scheduler probe";
> )
> ```
> 
> And below commands I used to force certificate rotation on failed probes :
> 
> ```
> echo "Rotating kube-controller-manager certificate"
> rm /var/lib/rancher/rke2/server/tls/kube-controller-manager/kube-controller-manager.{crt,key}
> crictl rm -f $(crictl ps -q --name kube-controller-manager)
> 
> echo "Rotating kube-scheduler certificate"
> rm /var/lib/rancher/rke2/server/tls/kube-scheduler/kube-scheduler.{crt,key}
> crictl rm -f $(crictl ps -q --name kube-scheduler)
> ```
> 
> Enjoy !

Life saver, thanks!

**Comment by textgroove-steven** [comment]
For those wondering, this works for k3s too. You just need to change rke2 to k3s, then reboot the server.

**Comment by Tejeev** [comment]
For those still seeing this, I'm filing an internal RFE for RKE2 cert rotation to hit these (once I've confirmed that it does not) and for an automated cert rotation feature in the Rancher UI (with possibly a third for an automated cert rotation for RKE2, though I do not know if there is a security reason we do not do this).

The fix that this bug was closed with is that the Rancher cert rotation (`Cluster Management > Cluster > Rotate certificates > Rotate all service certificates` and selecting `Rotate`) now hits these two certs as well.  I'll see if I can drum up the API command for this from the UI so folks can send it to more clusters at once via CLI.

**Comment by codeHui** [comment]
I want to ask, for this issue, will restarting the VMs of the nodes trigger the rotation, so the service will recover?

Our service just showed a 503 error today (without any updates), exactly 365 days after the cluster was created. So I guess it is the same issue.
![WhatsApp Image 2024-06-25 at 17 39 05_0d1a8380](https://github.com/rancher/rancher/assets/17940498/de1cf105-edcb-416a-93e7-5f1bec0bc19c)
Then I restarted the 2 VMs of the nodes mentioned above. After that, the services recovered. But the cluster shows "Updating."
![image](https://github.com/rancher/rancher/assets/17940498/afa9a1c1-899a-4a5f-a82c-f5191011555c)

1，If you think restarting the VMs will trigger the rotation, then I can be sure that we are having the same issue, and others can try restart for a quick recover for their production services.
2,  What is the easiest way to solve my issue(1, cluster shows "Updating." 2, Our service may show 503 again one year later) permanently? Should I update the Rancher version (currently v2.7.4)?

**Comment by Tejeev** [comment]
@codeHui Have you run the [cert rotation via UI](https://github.com/rancher/rancher/issues/41125#issuecomment-1561483947)? If you're behind on your updates, you'll have to use the workaround posted previously here ([step1](https://github.com/rancher/rancher/issues/41125#issuecomment-1506667795) ; then [step2](https://github.com/rancher/rancher/issues/41125#issuecomment-1506620040)).

If you are seeing this issue, restarting the nodes will only work for the certs managed by RKE2.  Unfortunately there are two certs which are _not_ deployed by or managed by RKE2 (https://docs.rke2.io/security/certificates), and those two are the rc of this issue.  To rotate them we have to get the K8s components to rotate them or use a current version of the Rancher Manager to do so.  



> It's wonderfull that there is still no fix!
@emoxam did the above not work for you?  If you have a specific way you would like the fix to work, please let us know. I'm filing for an RKE2 based fix as well as the Rancher based one that was implemented prior to your comment.  Perhaps this is closer to what you were wanting?  Your input would be useful to me when crafting the ask, so please don't hesitate to share, and I'll see if there isn't something we can do

**Comment by jmara** [comment]
This happens for k3s, too.

A possible solution would be to rotate the certificates automatically prior to an update triggered via Rancher UI, maybe with a checkbox to "opt-in" to do this in the "Edit Config" Dialog. 

Or do you see any downside of this approach?

**Comment by emoxam** [comment]
@tajeev I still got this issues but my cluster is not rancher.

**Comment by marvinlnnx** [comment]
Oct 14 2024, still this issue persist, 
env:


`Rancher: 2.9.2`

`rke2 version v1.30.4+rke2r1 (9517eea519b780e154dd791c555c698e84a0e5cd)
go version go1.22.5 X:boringcrypto`

OS:
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=24.04
DISTRIB_CODENAME=noble
DISTRIB_DESCRIPTION="Ubuntu 24.04.1 LTS"
```
any idea ?

**Comment by gapopp** [comment]
we facing this issue too on Rancher 2.9.2 and RKE2 1.29.8. Cluster is just over 1 year old and certificates are not rotating automatically. However this workaround helped: https://github.com/rancher/rancher/issues/41125#issuecomment-1506620040

**Comment by Velociraptor85** [comment]
Yap same on Rancher 2.9.3 - RKE2 v1.28.10+rke2r1

This does not seem to be resolved @Josh-Diamond

**Comment by acosoft** [comment]
### Simple GUI way to resolve  "Waiting for probes: kube-controller-manager, kube-scheduler"

1. Hamburger menu / Cluster management
1. click on three dots menu in row with cluster you want to fix
1. select Rotate certificates 
1. in dialog that opens, select "Rotate all service certificates" and then click on Rotate button

After few refreshes, everything should work as expected.

Tested on Rancher 2.7.9 with K3s cluster.

![image](https://github.com/user-attachments/assets/d7cb538f-99a7-4da2-bfd5-58340b33f90d)
 
### User perspective

Rancher is doing a lot of heavy lifting, so as a user, I didn't expect this kind of issue. The message that appears is not very informative, so at first it all seems like a big problem. Maybe, if the message was "Your certificates are expired. Your should rotate them manually" everything would look much more simple.

**Comment by PierTrailslight** [comment]
The issue is still present, I fixed it using the GUI solution from @acosoft quoted before.
Tested on rancher 2.8.3 and v1.30.10+rke2r1
I totally agree with him that the certificate rotation should be auotmatic OR the error message should be more explicit.

> ### Simple GUI way to resolve "Waiting for probes: kube-controller-manager, kube-scheduler"
> 1. Hamburger menu / Cluster management
> 2. click on three dots menu in row with cluster you want to fix
> 3. select Rotate certificates
> 4. in dialog that opens, select "Rotate all service certificates" and then click on Rotate button
> 
> After few refreshes, everything should work as expected.
> 
> Tested on Rancher 2.7.9 with K3s cluster.
> 
> ![image](https://github.com/user-attachments/assets/d7cb538f-99a7-4da2-bfd5-58340b33f90d)
> 
> ### User perspective
> Rancher is doing a lot of heavy lifting, so as a user, I didn't expect this kind of issue. The message that appears is not very informative, so at first it all seems like a big problem. Maybe, if the message was "Your certificates are expired. Your should rotate them manually" everything would look much more simple.

**Comment by miudinho** [comment]
Facing the same issue: 
Rancher ( in container ) 2.9.3
Provisionde cluster: 1.29.15.
Steps from above and from this issues:
https://www.suse.com/support/kb/doc/?id=000021371
https://forums.suse.com/t/cluster-cannot-be-accessed-trough-rancher-after-rancher-upgrade/41791
didnt solve my case. Any other quidelines ?

**Comment by yassin282** [comment]
> Facing the same issue: Rancher ( in container ) 2.9.3 Provisionde cluster: 1.29.15. Steps from above and from this issues: https://www.suse.com/support/kb/doc/?id=000021371 https://forums.suse.com/t/cluster-cannot-be-accessed-trough-rancher-after-rancher-upgrade/41791 didnt solve my case. Any other quidelines ?

Did you try this commands on each of the  reconciling nodes, the GUI solution did not work for me, this did.

> ```
> echo "Rotating kube-controller-manager certificate"
> rm /var/lib/rancher/rke2/server/tls/kube-controller-manager/kube-controller-manager.{crt,key}
> crictl rm -f $(crictl ps -q --name kube-controller-manager)
> 
> echo "Rotating kube-scheduler certificate"
> rm /var/lib/rancher/rke2/server/tls/kube-scheduler/kube-scheduler.{crt,key}
> crictl rm -f $(crictl ps -q --name kube-scheduler)
> ```
>

**Comment by miudinho** [comment]
Hello @yassin282,
Yes I did and it didn't solve my case. I did it also from the gui ( rotate certifcates ) for the whole cluster and still the same issu.

**Comment by JacobGV369** [comment]
Thank you, big shots, for helping me, little Karami。

**Comment by nikos445** [comment]
Happened to one cluster in Rancher 2.10.4 (prime) 
Used instructions on control plane nodes from here: https://www.suse.com/support/kb/doc/?id=000021371 
and recovered cluster to active state.

**Comment by Allowencer** [comment]
> Solution found ! Thanks for the hint Chris Kim and brandond on Rancher Community Slack !
> 
> There is no official solution right now, but here is the manual fix that worked for me, you may launch these commands on every nodes that is stuck in `Waiting for probes: kube-controller-manager, kube-scheduler` state (aka: controlplane nodes).
> 
> Here is a shell command to check if probes are okay or not :
> 
> ```
> (
> curl  --cacert /var/lib/rancher/rke2/server/tls/kube-controller-manager/kube-controller-manager.crt \
>   https://127.0.0.1:10257/healthz >/dev/null 2>&1 \
>   && echo "[OK] Kube Controller probe" \
>   || echo "[FAIL] Kube Controller probe";
> 
> curl --cacert /var/lib/rancher/rke2/server/tls/kube-scheduler/kube-scheduler.crt \
>   https://127.0.0.1:10259/healthz >/dev/null 2>&1  \
>   && echo "[OK] Scheduler probe" \
>   || echo "[FAIL] Scheduler probe";
> )
> ```
> 
> And below commands I used to force certificate rotation on failed probes :
> 
> ```
> echo "Rotating kube-controller-manager certificate"
> rm /var/lib/rancher/rke2/server/tls/kube-controller-manager/kube-controller-manager.{crt,key}
> crictl rm -f $(crictl ps -q --name kube-controller-manager)
> 
> echo "Rotating kube-scheduler certificate"
> rm /var/lib/rancher/rke2/server/tls/kube-scheduler/kube-scheduler.{crt,key}
> crictl rm -f $(crictl ps -q --name kube-scheduler)
> ```
> 
> Enjoy !

Holy hell did this ever SAVE ME!! THANK YOU!!

FOR HOURS I was banging my head on this. Nothing made sense and I was determined this time around to figure it out instead of defaulting to re-imaging each affected node.

BIG THANK YOU AGAIN!!!!

I'm running Rancher v2.11.3 for reference.

**Comment by Allowencer** [comment]
@snasovich / @Josh-Diamond - it's clear many of us are still running into this issue. There should be an auto-rotation cycle built into RKE and not something that has to be an annual housekeeping item. In the spirit of IaC tooling with tons of solutions out there for pods, there has got to be a method here that can resolve this.

**Comment by srnlorenz** [comment]
I run in the exact issue, this https://github.com/rancher/rancher/issues/41125#issuecomment-1506620040 has been a perfect solution.

I'm running Rancher v2.11.1 for reference.
