### ISSUE TITLE
[BUG] Rancher deployed charts respect Rancher min/max version and k8s min/max version. (Webhook)

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#41139]

**Comment by KevinJoiner** [comment]
This can be addressed by https://github.com/rancher/rancher/issues/40159

**Comment by cbron** [comment]
Webhook doesn't need to check k8s version, because it is tied directly to rancher, and rancher has its own k8s matrix which handles that case.

**Comment by cbron** [comment]
I think we can close and rely on 40159 to solve

**Comment by pgonin** [comment]
This is an issue for hosted providers operators as well
https://github.com/rancher/rancher/issues/41123
