### ISSUE TITLE
[BUG] RKE2 Upgrade gets started when adding a new node to existing but already-upgraded cluster

### ISSUE THREAD

**Issue by bfbachmann** [rancher/rancher#41143]
**Rancher Server Setup**
- Rancher version: v2.7.1
  - Installation option (Docker install/Helm Chart): Docker install
- Proxy/Cert Details: Default self-signed

**Information about the Cluster**
- Kubernetes version: v1.20.10+rke2r1
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster?: Imported

**User Information**
- What is the role of the user logged in? Admin

**Describe the bug**
After upgrading an imported RKE2 cluster, new nodes being added to the cluster cause the system upgrade controller to attempt to upgrade them even when they are already running the right version of Kubernetes.

**To Reproduce**
1. Create a simple RKE2 v1.20.10+rke2r1 cluster with 1 master and 1 worker node
2. Import the cluster into Rancher
3. Using the Rancher UI, update the cluster to a newer Kubernetes version (I upgraded to v1.23.17). Make sure to check the boxes for "Drain control plane nodes" and "Drain worker nodes". Wait for the cluster upgrade to complete successfully.
4. Add a new node to the cluster running the version of Kubernetes that you just upgraded to (for me, this was v1.23.17).
5. Use `watch kubectl get pods -n cattle-system` on the downstream cluster and notice the system upgrade controller create and run a pod for a job that upgrades the new node you just added to the cluster even though it is already running the correct  k8s version.

**Result**
System upgrade controller creates and runs job for new node, causing it to be cordoned.

**Expected Result**
New node is not cordoned and upgraded after being added since it is already running the right k8s version.

**Screenshots**
<img width="325" alt="image" src="https://user-images.githubusercontent.com/9647946/231315362-6dbd9606-8817-49f7-8372-03ce15f3c0d9.png">
<img width="2058" alt="image" src="https://user-images.githubusercontent.com/9647946/231315429-d387d368-916b-427b-98f9-be1164420dff.png">

**Additional context**
SURE-5020

**Comment by susesgartner** [comment]
Ticket #41143 - Test Results - ✅ 
---
 
| Scenario | Test Case | Result |
|---|---|---|
| 1. | Scale upgraded rke2 cluster | PASS |
 
---
Verified with (HA Helm or Docker) on Rancher `v2.10-21c339dd8adeaba5661b21c537f7ff409637ab61-head`:
---
 
Scenario 1: Scale upgraded rke2 cluster
---
1. Create an RKE2 standalone cluster using k8s version v1.30.5+rke2r1
2. Import the cluster into rancher
3. Upgrade the k8s version of the cluster to v1.31.1+rke2r1
4. Add a new node with the k8s version v1.31.1+rke2r1
5. Watch the pods and verify that no upgrade occurs as part of the node being added and no cordoning occurs


Results:  No upgrade occurs as part of adding a new node to the imported cluster.
