### ISSUE TITLE
[BUG] Cannot use asia-northeast3 (Seoul) GCP region for GKE

### ISSUE THREAD

**Issue by jangjaelee** [rancher/rancher#41140]
**Rancher Server Setup**
- Rancher version: v2.7.1
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: 
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:

I'm using Rancher v2.7.1 on GCP with asia-northeast3 (seoul region).
When I create downstream cluster with GKE. It is not in the list asia-northeast3(seoul) region.

**Describe the bug**

**To Reproduce**

**Result**

**Expected Result**

**Screenshots**

**Additional context**

**Comment by JangGyeongSik** [comment]
I agree with this issue, and I hope that showing the Seoul region is quickly fixed.

**Comment by kkaempf** [comment]
rancher pr merged, needs to be tested
