### ISSUE TITLE
Support for DNSMadeEasy

### ISSUE THREAD

**Issue by gblmarquez** [rancher/rancher#4114]
Hi Guys,

First of all, thanks for this awesome project.
There is any efforts for supporting DNSMadeEasy as a dns provider?

**Comment by deniseschannon** [comment]
In our community catalog, there have been a couple of contributions from other people for other DNS providers. At this time, we are not working on supporting additional dns providers, but feel free to make a PR to our community catalog. :)

**Comment by gblmarquez** [comment]
@deniseschannon just to confirm I should contribute to this project https://github.com/rancher/external-dns correct?

**Comment by deniseschannon** [comment]
@gblmarquez I was thinking more like these tempates: https://github.com/rancher/community-catalog/tree/master/templates

Check out CloudFlare, DNSimple, which were added by community members.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
