### ISSUE TITLE
[BUG] Installed rancher running but it is not working on the EKS v1.25.6-eks-48e63af

### ISSUE THREAD

**Issue by tainguyenbp** [rancher/rancher#41149]
**Rancher Server Setup**
- Rancher version:
- Installation option (Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (EKS):
   helm install rancher rancher-stable/rancher \
  --namespace cattle-system \
  --set hostname=ranui.tainnsre.vn \
  --set global.cattle.psp.enabled=false \
  --set ingress.tls.source=secret
rancher-stable/rancher - rancher-2.7.2
- Proxy/Cert Details: no

**Information about the Cluster**
- Kubernetes version: v1.25.6-eks-48e63af
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:

![image](https://user-images.githubusercontent.com/14048946/231675341-07123dcb-3007-4c2d-beb8-ccd182ecb56f.png)

![Uploading image.png…]()

![image](https://user-images.githubusercontent.com/14048946/231675409-8b6c8f80-1084-4a52-934f-c697b0823829.png)

i am ussing forward port 80 is not working 
![image](https://user-images.githubusercontent.com/14048946/231675674-008d908b-a44d-400b-91d7-218f21d0d8c4.png)

i am ussing forward port 443 is not working 
![image](https://user-images.githubusercontent.com/14048946/231675869-903de909-381b-4287-93c8-b762170d56cf.png)
![image](https://user-images.githubusercontent.com/14048946/231675915-deaf212b-bcbd-48a2-a0c6-39cb91428f1f.png)

can you help me please
tks you very much

**Describe the bug**

**To Reproduce**

**Result**

**Expected Result**

 can not access to service rancher while i set forward port

**Screenshots**

**Additional context**

**Comment by Josh-Diamond** [comment]
Kubernetes `v1.25` EKS clusters are not currently supported in Rancher.

Rancher supports `v1.23` and `v1.24` on Rancher `v2.7.2`

**Comment by Josh-Diamond** [comment]
However, I was able to successfully spin up Rancher `v2.7.2` on local EKS `v1.25.8-eks-ec5523e`, following the documentation outlined here:
- https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/rancher-on-amazon-eks#5-install-an-ingress

Perhaps, there is a misconfiguration in your environment.

**Comment by tainguyenbp** [comment]
tks @Josh-Diamond for your support
I done read and setup with docs above but it not working.
my log system rancher setup:
`2023/04/17 09:30:14 [INFO] Watching metadata for rke-machine-config.cattle.io/v1, Kind=LinodeConfig                                                                                                                                                                          │
│ 2023/04/17 09:30:14 [INFO] Watching metadata for rke-machine.cattle.io/v1, Kind=AzureMachine                                                                                                                                                                                 │
│ 2023/04/17 09:30:14 [INFO] Watching metadata for rke-machine.cattle.io/v1, Kind=DigitaloceanMachine                                                                                                                                                                          │
│ 2023/04/17 09:30:14 [INFO] Watching metadata for rke-machine.cattle.io/v1, Kind=AzureMachineTemplate                                                                                                                                                                         │
│ 2023/04/17 09:30:14 [INFO] Watching metadata for rke-machine.cattle.io/v1, Kind=DigitaloceanMachineTemplate                                                                                                                                                                  │
│ 2023/04/17 09:30:15 [INFO] Watching metadata for rke-machine.cattle.io/v1, Kind=Amazonec2MachineTemplate                                                                                                                                                                     │
│ 2023/04/17 09:30:15 [INFO] Watching metadata for rke-machine-config.cattle.io/v1, Kind=VmwarevsphereConfig                                                                                                                                                                   │
│ 2023/04/17 09:30:15 [INFO] Watching metadata for rke-machine-config.cattle.io/v1, Kind=Amazonec2Config                                                                                                                                                                       │
│ 2023/04/17 09:30:15 [INFO] Watching metadata for rke-machine.cattle.io/v1, Kind=VmwarevsphereMachineTemplate                                                                                                                                                                 │
│ 2023/04/17 09:30:15 [INFO] Watching metadata for rke-machine.cattle.io/v1, Kind=VmwarevsphereMachine                                                                                                                                                                         │
│ 2023/04/17 09:30:15 [INFO] Watching metadata for rke-machine.cattle.io/v1, Kind=Amazonec2Machine                                                                                                                                                                             │
│ 2023/04/17 09:30:16 [ERROR] Failed to handle tunnel request from remote address 172.31.22.78:46978: response 400: cluster not found                                                                                                                                          │
│ 2023/04/17 09:30:16 [ERROR] Failed to handle tunnel request from remote address 172.31.39.172:57716: response 400: cluster not found                                                                                                                                         │
│ 2023/04/17 09:30:16 [INFO] Starting cluster controllers for local                                                                                                                                                                                                            │
│ 2023/04/17 09:30:16 [INFO] Starting cluster agent for local [owner=false]                                                                                                                                                                                                    │
│ 2023/04/17 09:30:16 [INFO] Starting rbac.authorization.k8s.io/v1, Kind=ClusterRoleBinding controller                                                                                                                                                                         │
│ 2023/04/17 09:30:16 [INFO] Starting rbac.authorization.k8s.io/v1, Kind=ClusterRole controller                                                                                                                                                                                │
│ 2023/04/17 09:30:16 [INFO] Starting rbac.authorization.k8s.io/v1, Kind=RoleBinding controller                                                                                                                                                                                │
│ 2023/04/17 09:30:16 [INFO] Starting rbac.authorization.k8s.io/v1, Kind=Role controller                                                                                                                                                                                       │
│ 2023/04/17 09:30:16 [INFO] Starting /v1, Kind=Secret controller                                                                                                                                                                                                              │
│ 2023/04/17 09:30:16 [INFO] Starting /v1, Kind=Namespace controller                                                                                                                                                                                                           │
│ 2023/04/17 09:30:16 [INFO] Starting /v1, Kind=ServiceAccount controller                                                                                                                                                                                                      │
│ 2023/04/17 09:30:17 [INFO] Watching metadata for rke-machine-config.cattle.io/v1, Kind=HarvesterConfig                                                                                                                                                                       │
│ 2023/04/17 09:30:17 [INFO] Watching metadata for rke-machine.cattle.io/v1, Kind=HarvesterMachine                                                                                                                                                                             │
│ 2023/04/17 09:30:17 [INFO] Watching metadata for rke-machine.cattle.io/v1, Kind=HarvesterMachineTemplate                                                                                                                                                                     │
│ 2023/04/17 09:30:21 [INFO] Adding peer wss://172.31.39.172/v3/connect, 172.31.39.172                                                                                                                                                                                         │
│ 2023/04/17 09:30:21 [ERROR] Failed to handle tunnel request from remote address 172.31.22.78:35804: response 400: cluster not found                                                                                                                                          │
│ 2023/04/17 09:30:21 [INFO] Handling backend connection request [172.31.39.172]                                                                                                                                                                                               │
│ 2023/04/17 09:30:23 [INFO] Updating TLS secret for cattle-system/serving-cert (count: 7): map[field.cattle.io/projectId:local:p-psrnr listener.cattle.io/cn-127.0.0.1:127.0.0.1 listener.cattle.io/cn-172.31.22.78:172.31.22.78 listener.cattle.io/cn-172.31.39.172:172.31.3 │
│ 2023/04/17 09:30:23 [INFO] Active TLS secret cattle-system/serving-cert (ver=68997277) (count 7): map[field.cattle.io/projectId:local:p-psrnr listener.cattle.io/cn-127.0.0.1:127.0.0.1 listener.cattle.io/cn-172.31.22.78:172.31.22.78 listener.cattle.io/cn-172.31.39.172: │
│ 2023/04/17 09:30:23 [INFO] Updating TLS secret for cattle-system/tls-rancher-internal (count: 2): map[field.cattle.io/projectId:local:p-psrnr listener.cattle.io/cn-10.100.63.154:10.100.63.154 listener.cattle.io/fingerprint:SHA1=87E1746EFB9222340468BB9F2C562A059C4D03E8 │
│ 2023/04/17 09:30:23 [INFO] Active TLS secret cattle-system/tls-rancher-internal (ver=68997333) (count 2): map[field.cattle.io/projectId:local:p-psrnr listener.cattle.io/cn-10.100.63.154:10.100.63.154 listener.cattle.io/fingerprint:SHA1=87E1746EFB9222340468BB9F2C562A05 │
│ 2023/04/17 09:30:26 [ERROR] Failed to serve peer connection 172.31.39.172: websocket: close 1006 (abnormal closure): unexpected EOF                                                                                                                                          │
│ 2023/04/17 09:30:26 [INFO] error in remotedialer server [400]: read tcp 172.31.6.57:443->172.31.39.172:58100: use of closed network connection                                                                                                                               │
│ 2023/04/17 09:30:26 [ERROR] Failed to handle tunnel request from remote address 172.31.22.78:35810: response 400: cluster not found                                                                                                                                          │
│ 2023/04/17 09:30:26 [INFO] Adding peer wss://172.31.22.78/v3/connect, 172.31.22.78                                                                                                                                                                                           │
│ 2023/04/17 09:30:31 [INFO] Handling backend connection request [172.31.39.172]                                                                                                                                                                                               │
│ 2023/04/17 09:30:31 [INFO] Handling backend connection request [172.31.22.78]                                                                                                                                                                                                │
│ 2023/04/17 09:31:15 [INFO] Watching metadata for fleet.cattle.io/v1alpha1, Kind=ClusterGroup                                                                                                                                                                                 │
│ 2023/04/17 09:31:15 [INFO] Watching metadata for fleet.cattle.io/v1alpha1, Kind=ClusterRegistrationToken                                                                                                                                                                     │
│ 2023/04/17 09:31:15 [INFO] Watching metadata for fleet.cattle.io/v1alpha1, Kind=GitRepo                                                                                                                                                                                      │
│ 2023/04/17 09:31:15 [INFO] Watching metadata for fleet.cattle.io/v1alpha1, Kind=BundleDeployment                                                                                                                                                                             │
│ 2023/04/17 09:31:15 [INFO] Watching metadata for gitjob.cattle.io/v1, Kind=GitJob                                                                                                                                                                                            │
│ 2023/04/17 09:31:15 [INFO] Watching metadata for fleet.cattle.io/v1alpha1, Kind=ClusterRegistration                                                                                                                                                                          │
│ 2023/04/17 09:31:15 [INFO] Watching metadata for fleet.cattle.io/v1alpha1, Kind=BundleNamespaceMapping                                                                                                                                                                       │
│ 2023/04/17 09:31:15 [INFO] Watching metadata for fleet.cattle.io/v1alpha1, Kind=ImageScan                                                                                                                                                                                    │
│ 2023/04/17 09:31:15 [INFO] Watching metadata for fleet.cattle.io/v1alpha1, Kind=Content                                                                                                                                                                                      │
│ 2023/04/17 09:31:15 [INFO] Watching metadata for fleet.cattle.io/v1alpha1, Kind=GitRepoRestriction`
