### ISSUE TITLE
Firefox - Containers with long names don't show up properly on host page

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4116]
Version - master 3/22

Steps to Reproduce: 
1.  Create a stack, then a service where both have long names
2.  Activate service and go to host page

Results: Notice none of the name shows up and only a ... is there
![image](https://cloud.githubusercontent.com/assets/11514927/14032066/b1d3fda8-f1cd-11e5-9305-be54892ada7b.png)

Expected: Should have some of the name showing.

**Comment by sshipway** [comment]
I noticed this one as well when testing 1.0-rc2.  Since the container names tend to be very long (as they are "stack_service_instance") this effect is rather common

**Comment by tfiduccia** [comment]
version - master 6/9
Verified fixed
