### ISSUE TITLE
Abstract system-agent-installer image resolution

### ISSUE THREAD

**Issue by jakefhyde** [rancher/rancher#41167]
The dependency graph of rancher's bootstrap and controlplane providers is too tightly coupled with rancher specific implementation details, use dependency injection to invert the dependency of the controlplane controller on rancher's settings API, as well as allow the ability to mock during unit tests.
SURE-6250

**Comment by sowmyav27** [comment]
Reopening this since there are no automated tests

**Comment by jakefhyde** [comment]
@sowmyav27 Tests are here: https://github.com/rancher/rancher/pull/41168/files#diff-d3bc1cf510959c64453c9c58e7aed7dc119bfc746d450f580b9a563c7bd1a5c3

**Comment by sowmyav27** [comment]
Basic rke2/k3s provisioning - linode/AWS node driver and custom clusters work on 2.7-head commit id: `1f014b7` "No other specific checks needed". Closing this issue.
