### ISSUE TITLE
[BUG] First kubectl command by an admin on an imported cluster produces an error

### ISSUE THREAD

**Issue by JonCrowther** [rancher/rancher#41185]
**Rancher Server Setup**
- Rancher version: v2.7.2
- Installation option (Docker install/Helm Chart):
   - local 

**Information about the Cluster**
- Kubernetes version: v1.26.3
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):
   - custom: k3d cluster
     - k3s: v1.25.7
     - k3d: v5.4.9

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - Admin

**Describe the bug**

The first `kubectl` command issued after importing a cluster by an admin user produces an error message. Subsequent `kubectl` commands on the same cluster are successful.

**To Reproduce**

I was able to reproduce this using the following steps in a local instance of rancher:

1. Create an admin user (Hamburger Menu -> Users & Authentication -> Create). Set the global permission to Administrator
2. Create another local cluster `k3d create cluster import-test`
4. In rancher, import a generic cluster (Hamburger Menu -> Cluster Management -> Import Existing -> Generic)
5. It gives you a registration command to run to import it into rancher. Run that
6. In rancher, wait for the cluster to become active
7. Log out
8. Log in as the admin user you created
9. From the home page, select the new cluster and get the kubeconfig (top right)
10. Paste the kubeconfig in a terminal into a yaml file
11. Run any kubectl command using the kubeconfig `kubectl --kubeconfig test-config.yaml get pods -A`

**Result**

```
I0414 16:04:58.148389   45660 versioner.go:58] an error on the server ("unable to create impersonator account: error setting up impersonation for user u-glkpr: failed to get secret for service account: cattle-impersonation-system/cattle-impersonation-u-glkpr, error: resource name may not be empty") has prevented the request from succeeding
```

**Expected Result**

When the admin user issues the `kubectl` command it should succeed with no error message.

**Screenshots**

**Additional context**

**Comment by JonCrowther** [comment]
Point 2 of this answer has some details:
https://stackoverflow.com/questions/60109761/error-while-running-pod-defination-file-in-kubernetes

**Comment by samjustus** [comment]
duplicate #43293 maybe?

**Comment by MKlimuszka** [comment]
Assigning to team/collie since it is impersonation related.

**Comment by crobby** [comment]
Taking this temporarily for triage

**Comment by crobby** [comment]
I was unable to reproduce this on 2.9-head.
I will try with previous Rancher releases.

**Comment by crobby** [comment]
I was also unable to reproduce this on the latest 2.8 release.
Strangely enough, I could not repro on the reported version 2.7.2 either.  

@JonCrowther I know it's been awhile since you originally reported this, but do you have any additional tips for me to repro this?

**Comment by JonCrowther** [comment]
I can no longer reproduce the issue either. Closing!
