### ISSUE TITLE
[project-monitoring] Helm Chart crashs with disabled AlertManager

### ISSUE THREAD

**Issue by eumel8** [rancher/rancher#41198]
**Describe the bug**
The Helm Chart has the [option](https://github.com/rancher/prometheus-federator/blob/main/charts/rancher-project-monitoring/0.2.1/values.yaml#L139) to disable the AlertManager. If this value is set (`enabled: false`) Helm crashs due the broken yaml file for alertmanager.yaml

**To Reproduce**
disable AlertManager

 

**Result**
Helm crashs

**Expected Result**
AlertManager is completely disabled and will not installed

**Screenshots**

**Additional context**
In the deeper look and why this is not happen in the [rancher-monitoring Chart](https://github.com/rancher/charts/blob/release-v2.7/charts/rancher-monitoring/101.0.0%2Bup19.0.3/templates/alertmanager/alertmanager.yaml):

This [patch file](https://github.com/rancher/prometheus-federator/blob/main/packages/rancher-project-monitoring/generated-changes/patch/templates/alertmanager/alertmanager.yaml.patch) sets the `end`tag of the first condition in line 73 instead at the end of the file. As a result you become a broken alertmanager.yaml which can't parse by Helm.
Just wondering why this patch logic is a good idea because it's complicated to debug and caused easy to an error.

**Comment by AndrewHoffmanQA** [comment]
retested on a local HA (3 nodes all roles)
2-7head

retest status- passed. see video

steps 
1 installed monitoring
2. installed prom federator without alert manager enabled
3.  confirmed the application successfully installed, validated the alerts page 'alert manager config' page does not displayed and Alert Manager wasn't installed. 

https://zube.io/files/rancher/4288faf85bd748336ddb7b71b42ccddc-2023-05-03_10-38-24.mp4

**Comment by AndrewHoffmanQA** [comment]
testing completed and passed. prom federator works as expected with alert manager disabled.
