### ISSUE TITLE
[BUG] tigera-operator fails due to rancher-webhook denying access

### ISSUE THREAD

**Issue by bpedersen2** [rancher/rancher#41191]
**Rancher Server Setup**
- Rancher version: 2.7.2
- Installation option (Docker install/Helm Chart): docker

**Information about the Cluster**
- Kubernetes version: v1.24.11 +k3s1
- Cluster Type (Local/Downstream): Downstream custom

**User Information**
- What is the role of the user logged in? Admin

**Describe the bug**

tigera-operator fails due to rancher-webhook denying access:
```
{"level":"info","ts":1681811352.3538423,"logger":"controller_installation","msg":"Failed to update object.","Name":"calico-system","Namespace":"","Kind":"Namespace","key":"/calico-system"}
Tue, Apr 18 2023 11:49:12 am
{"level":"error","ts":1681811352.3538892,"logger":"controller_installation","msg":"Error creating / updating resource","Request.Namespace":"tigera-operator","Request.Name":"tigera-ca-private","reason":"ResourceUpdateError","error":"admission webhook \"rancher.cattle.io.namespaces\" denied the request: Unauthorized","stacktrace":"github.com/tigera/operator/pkg/controller/status.(*statusManager).SetDegraded\n\t/go/src/github.com/tigera/operator/pkg/controller/status/status.go:406\ngithub.com/tigera/operator/pkg/controller/installation.(*ReconcileInstallation).Reconcile\n\t/go/src/github.com/tigera/operator/pkg/controller/installation/core_controller.go:1358\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:121\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:320\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:234"}
2023-04-18T11:49:12.354158625+02:00 {"level":"error","ts":1681811352.3540413,"msg":"Reconciler error","controller":"tigera-installation-controller","object":{"name":"tigera-ca-private","namespace":"tigera-operator"},"namespace":"tigera-operator","name":"tigera-ca-private","reconcileID":"593d8d9e-272b-4009-a6d1-823e0a39883d","error":"admission webhook \"rancher.cattle.io.namespaces\" denied the request: Unauthorized","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:326\nsigs
.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.
```

**To Reproduce**

Run cluster with tigera-operator for calico-installation  and update:
 rancher from  2.7.1 -> 2.7.2
 tigera-operator from 3.16 to 3.25

observe that  the calico installation does not update

**Result**

**Expected Result**
tigera-operator can update without problems.

**Additional context**
related to #41172?

**Comment by pancochea** [comment]
Yes, definitely related to #41172

**Comment by anupama2501** [comment]
Hi @bpedersen2 here's what I tried and I'm unable to reproduce the issue. Could you let us know if there's any other steps that are needed here?

- Created a rancher docker install on v2.7.1
- Create a k3s custom 1.24 cluster
- On the custom cluster install calico via tigera operator  https://docs.tigera.io/calico/latest/getting-started/kubernetes/k3s/quickstart
- kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.24.1/manifests/tigera-operator.yaml
- kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.24.1/manifests/custom-resources.yaml
- Upgrade rancher server to v2.7.2
- Upgrade calico via tigera-operator to v3.25 https://docs.tigera.io/calico/latest/operations/upgrading/kubernetes-upgrade#upgrading-an-installation-that-uses-the-operator
`- curl https://raw.githubusercontent.com/projectcalico/calico/v3.25.1/manifests/tigera-operator.yaml -O`
`- kubectl replace -f tigera-operator.yaml`
- Tigera operator came back up fine without any issue.

**Comment by bpedersen2** [comment]
I did create a namespace fir tigera/caclico in the System-project, may that be the root cause of the problem?

**Comment by bpedersen2** [comment]
and the tigera-operator comes up, but fails to upgrade calico due to the webhook denying access.

**Comment by dtrouillet** [comment]
We have the same issue when we are trying to add ApiServer CRD. The Tigera Operator try to create a namespace called "calico-apiserver" with privileged PSA. The ValidatingWebhook deny this request.

**Comment by bpedersen2** [comment]
I got  the operator to update after 
excluding  the  namespaces with a namespace selector for the following  validating hooks:
```
    name: rancher.cattle.io.namespaces.create-non-kubesystem
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            - kube-system
            - calico-apiserver
            - calico-system
            - tigera-operator
 ```
and 
```    name: rancher.cattle.io.namespaces
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            - kube-system
            - calico-apiserver
            - calico-system
            - tigera-operator
```

**Comment by travisghansen** [comment]
Getting the same issue with a fresh installation of the trident operator (NetApp). Recently updated to rancher `2.7.2` and also bumped the version of trident so not entirely sure what introduced the issue. Older installations of trident aren't showing the issue but they may have already updated the ns as desired, not sure.

```
time="2023-05-04T16:58:51Z" level=error msg="error syncing 'trident': reconcile failed; error re-installing Trident 'trident' ; err: reconcile failed; failed to patch Trident installation namespace trident; admission webhook \"rancher.cattle.io.namespaces\" denied the request: Unauthorized, requeuing"
```

**Comment by strom18** [comment]
Hello, 

We have the same error when we try to install Calico Enterprise.
RKE2 v1.25.9+rke2r1 with CIS 1.23 profile.

The tigerastatus report webhook denied when creating namespace : 

```
status:
    conditions:
    - lastTransitionTime: "2023-05-05T09:40:44Z"
      message: 'Error creating / updating resource: admission webhook "rancher.cattle.io.namespaces.create-non-kubesystem"
        denied the request: Unauthorized'
      observedGeneration: 4
      reason: ResourceUpdateError
      status: "True"
      type: Degraded
```

**Comment by justdan96** [comment]
It looks like Rancher is adding some namespaces to the System project automatically so I don't think that the root cause is the project settings: https://github.com/rancher/rancher/blob/release/v2.7/pkg/settings/setting.go#L27-L50

**Comment by justdan96** [comment]
Additionally according to the code the admission should only be rejected if we are altering PSA on a namespace, which we aren't: https://github.com/rancher/webhook/blob/release/v0.3/pkg/resources/core/v1/namespace/validator.go

**Comment by justdan96** [comment]
I've managed to resolve this by adding some new ClusterRoles and ClusterRoleBindings. For instance for Tigera:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tigera-operator-psa
rules:
- apiGroups:
  - management.cattle.io
  resources:
  - projects
  verbs:
  - updatepsa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tigera-operator-psa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tigera-operator-psa
subjects:
- kind: ServiceAccount
  name: tigera-operator
  namespace: tigera-operator
```

This resolves the issue we were having with Tigera Operator, and a similar set of resources resolves a similar issue with the OPA Gatekeeper Update Namespace Label deployment.

**Comment by lindhe** [comment]
I too had the issue where Trident reported `'Failed to install Trident; err: failed to patch Trident installation namespace trident; admission webhook "rancher.cattle.io.namespaces" denied the request: Unauthorized'`.

I can confirm that upgrading to Rancher v2.7.5 have fixed the issue for me.

**Comment by lindhe** [comment]
This leaves me wondering...

* Is this a bug in Rancher or a bug in the Trigera/Trident operators?
* I cannot find any documentation for these RBAC rules. Is it really an undocumented feature of Rancher??
* Is it reasonable that having `patch` privileges on the `namespace` resource is not enough for adding a label?
* Is it reasonable for people to have to write special cases for each Kubernetes distribution?
* At least in my case, the `trident` namespace is not part of any Rancher project. To me, it feels strange then that I need _any_ privileges on the `projects` resource for things to work. Should that be changed in Rancher?

So, is this a bug in Rancher or a bug in the operators? I have to admit that it is a bit murky. On one hand, I generally expect Kubernetes manifests to work the same no matter if I deploy on Rancher, Minikube, AKS or vanilla Kubernetes. On the other hand, projects is a neat piece of management abstraction that Rancher provides, so that's obviously something that needs to be handled when using Rancher.

If this should be added in the operator's manifests in order to handle the "edge case of Rancher", I assume it should be as simple as adding the relevant rule to the list of rules for the existing ClusterRole, right? Because it's using the API group `management.cattle.io`, that should be unique and have no effect on other Kubernetes distributions. Am I correct in this assumption, or do we need some logic to determine which Kubernetes distribution we deploy to and have Helm render different manifests depending on that?

As far as I'm concerned, there is at least one thing that is 100% on Rancher's responsibility and that they must fix: **this API must be documented!** And not just how to add PSA labels for namespaces, the whole `management.cattle.io` API group must be documented!

**Comment by samjustus** [comment]
SURE-6274

**Comment by KevinJoiner** [comment]
@lindhe Thanks for your help triaging this issue 

We are continuing to look for ways to make Rancher integrate better with other products. For the time being, documentation around the webhook behavior with the tiger-operator and any application deployed on a cluster with the webhook can be found in the [Common Issues](https://ranchermanager.docs.rancher.com/reference-guides/rancher-webhook#application-fails-to-deploy-due-to-rancher-webhook-blocking-access) section of the webhook docs.

Specific per-resource validation can be found in the[ webhook repo](https://github.com/rancher/webhook/blob/release/v0.4/docs.md).

**Comment by mohag** [comment]
> So, is this a bug in Rancher or a bug in the operators? I have to admit that it is a bit murky. On one hand, I generally expect Kubernetes manifests to work the same no matter if I deploy on Rancher, Minikube, AKS or vanilla Kubernetes. On the other hand, projects is a neat piece of management abstraction that Rancher provides, so that's obviously something that needs to be handled when using Rancher.
> 
> If this should be added in the operator's manifests in order to handle the "edge case of Rancher", I assume it should be as simple as adding the relevant rule to the list of rules for the existing ClusterRole, right? Because it's using the API group `management.cattle.io`, that should be unique and have no effect on other Kubernetes distributions. Am I correct in this assumption, or do we need some logic to determine which Kubernetes distribution we deploy to and have Helm render different manifests depending on that?


It seem acceptable on RKE / other Rancher deployed clusters, but if deploying the agent to the cluster to just use Rancher as a GUI, it should not interfere with other things running on the cluster...

**Comment by FredNass** [comment]
As of Rancher 2.10, rancher-webhook v0.6.1 denies tigera-operator to renew its typha-certs secret unless you manually set CR/CRB or validation hook exclusions.

This didn't happen with Rancher 2.9.2 and rancher-webhook v0.5.2 (with no CR/CRB and no validation hook exclusions).
