### ISSUE TITLE
[BUG] Docker installation script fails to install docker on RHEL 9

### ISSUE THREAD

**Issue by rishabhmsra** [rancher/rancher#41192]
**Describe the bug**
- On RHEL 8, only docker versions upto `20.10.7` was supported and docker script was working fine till then. Any docker version above that errors out with `Packages for RHEL are currently only available for s390x`. Please see the [Note](https://docs.docker.com/engine/install/rhel/#prerequisites) on docker website.
- On RHEL 9 docker 20.10.7 is not available and the docker installation script errors out with :
```
$ curl https://releases.rancher.com/install-docker/20.10.7.sh | sh
...
Docker CE Stable - x86_64                                                                                                                     59 kB/s |  21 kB     00:00    
Red Hat Enterprise Linux 9 for x86_64 - AppStream from RHUI (RPMs)                                                                            72 kB/s | 4.5 kB     00:00    
Red Hat Enterprise Linux 9 for x86_64 - BaseOS from RHUI (RPMs)                                                                               60 kB/s | 4.1 kB     00:00    
Red Hat Enterprise Linux 9 Client Configuration                                                                                               25 kB/s | 2.0 kB     00:00    
Metadata cache created.
INFO: Searching repository for VERSION '20.10.7'
INFO: yum list --showduplicates 'docker-ce' | grep '20.10.7.*el' | tail -1 | awk '{print $2}'

ERROR: '20.10.7' not found amongst yum list results
```
- Docker version `20.10.7` is not available on RHEL 9 and lowest version of docker available on RHEL 9 is `20.10.15`, but that errors out with `Packages for RHEL are currently only available for s390x`.
```
$ yum list --showduplicates 'docker-ce'
...
Available Packages
docker-ce.x86_64                                                              3:20.10.15-3.el9     
```

**To Reproduce**

- On AWS create a VM using RHEL 9 ami.
- Run docker installation script `curl https://releases.rancher.com/install-docker/20.10.7.sh | sh`

**Result**
- Docker install script fails to install docker on RHEL 9.

**Expected Result**
- Docker should get installed successfully

**Additional context**

- https://github.com/rancher/qa-tasks/issues/690#issuecomment-1510776484

**Comment by mitulshah-suse** [comment]
As suggested on the docker website, tried using the CentOS repo to install docker.

> We currently only provide packages for RHEL on s390x (IBM Z). Other architectures are not yet supported for RHEL, but you may be able to install the CentOS packages on RHEL. Refer to the [Install Docker Engine on CentOS](https://docs.docker.com/engine/install/centos/) page for details.

https://docs.docker.com/engine/install/centos/#install-using-the-repository

The installation was successful, so we may need to update the install-docker script to run the installation using CentOS repo.
@snasovich @kinarashah

**Comment by Sahota1225** [comment]
Waiting to hear back from Product

**Comment by vivek-shilimkar** [comment]
Tested docker installation script on RHEL9 `ami-067a8829f9ae24c1c`. Docker installation script is working as expected and cluster is getting provisioned successfully. Hence closing this issue.
