### ISSUE TITLE
[v2.7] Update Pause version for K8s v1.24.13 and 1.25.9 in KDM

### ISSUE THREAD

**Issue by rayandas** [rancher/rancher#41207]
As per https://github.com/kubernetes/kubernetes/blob/v1.25.9/build/dependencies.yaml and https://github.com/kubernetes/kubernetes/blob/v1.24.13/build/dependencies.yaml

**Comment by vivek-infracloud** [comment]
Tested the cluster creation on rancher v2.7.2

**- v1.25.9-rancher2-1**
  - k8s v1.25.9-rancher2-1 provisioned successfully. Also checked the `rancher/mirrored-pause` version is `3.7`.
  
Docker container with downgraded Pause image is successfully running on the node.

Hence closing this issue.
