### ISSUE TITLE
How to use added registries in rancher?

### ISSUE THREAD

**Issue by bestwishes110** [rancher/rancher#4120]
Hi,
I'm confused by registry in rancher. I don't know what to do after I added a private registry in rancher.Or is there anyway to use added registry by environment variable?

Looking forward to your reply! Thank you!

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v0.63.1` Cattle: `v0.155.1` UI: `v0.95.0` |
|Access|`Disabled`|
|Route|`registries.index`|

**Comment by deniseschannon** [comment]
The syntax for image name match any docker run commands.

`[registry-name]/[namespace]/[imagename]:[version]`

**Comment by clicman** [comment]
Where I can get registry name? Rancher doesn`t ask it on adding. And in api I see name: null.
Please help.

**Comment by deniseschannon** [comment]
What kind of private registry are you using? Are you using one hosted in docker or quay.io or a custom?

**Comment by clicman** [comment]
It is my own. I follow [this](https://docs.docker.com/registry/deploying/) manual
It works if I pull image from console on host, but cannot pull it from rancher.

**Comment by deniseschannon** [comment]
So have you set up a private registry inside Rancher?

http://docs.rancher.com/rancher/configuration/registries/

**Comment by clicman** [comment]
Yes. But problem is what there is no name for registry
30 апр. 2016 г. 12:01 AM пользователь "Denise" <notifications@github.com>
написал:

**Comment by deniseschannon** [comment]
If you were to run a container from the host, what docker run command would you use to launch a container? Have you confirmed that this docker run command works on the host?

**Comment by clicman** [comment]
yes. I confirm.

**Comment by deniseschannon** [comment]
Can you provide the docker run command?

**Comment by clicman** [comment]
Ive solved an error. I have two misconfigurations:
1. Hide registry behind apache https proxy instead of creating ssl on container itself
2. not passed full path on container creation.

And I have question for 2.
Is it possible to not pass full path in racher?
Now I should pass docker-registry.mydomain.com:5000/somename/image:tag
But I want to pass somename/image:tag instead. Is it possible?
or make an lalias for hostname? Like alias/somename/image:tag

**Comment by deniseschannon** [comment]
I believe you'll need to pass the full name.

**Comment by deniseschannon** [comment]
@clicman Let me know if you still have any questions.
