### ISSUE TITLE
Allow specifying alternative controlplane object in provisioning cluster generating framework

### ISSUE THREAD

**Issue by jakefhyde** [rancher/rancher#41204]
We currently allow a "bring your own" style infrastructure provider solution using v2prov's provisioning cluster object and the associated generating framework. This PR adds support for allowing arbitrary controlplane providers as well.

**Comment by Oats87** [comment]
I'm not so sure that we should implement this change -- if a user is using our provisioning framework, it likely makes sense for us to lock to CAPR for now.

**Comment by jakefhyde** [comment]
closed as won't do
