### ISSUE TITLE
Abstract v2prov KDM data

### ISSUE THREAD

**Issue by jakefhyde** [rancher/rancher#41218]
The dependency graph of rancher's bootstrap and controlplane providers is too tightly coupled with rancher specific implementation details, use dependency injection to invert the dependency of the controlplane controller on rancher's settings API, as well as allow the ability to mock during unit tests.
SURE-6250

**Comment by sowmyav27** [comment]
Basic rke2/k3s provisioning - linode/AWS node driver and custom clusters work on 2.7-head commit id: `1f014b7` "No other specific checks needed". Closing this issue.

K8s versions tested:
- v1.26.4+k3s1 
- v1.26.4+rke2r1
- v1.25.9+k3s1
