### ISSUE TITLE
[BUG] Node Pods list is always empty

### ISSUE THREAD

**Issue by p-kimberley** [rancher/rancher#41226]
**Rancher Server Setup**
- Rancher version: 2.7.2
- Installation option:
  - Helm chart
  - RKE2 1.25.7+rke2r1

**Information about the Cluster**
- Kubernetes version: 1.25.7+rke2r1
- Cluster Type: Downstream, imported local RKE2 cluster

**User Information**
- What is the role of the user logged in? Cluster Owner

**Describe the bug**
After the upgrade from Rancher v2.7.1 to v2.7.2, the `Pods` list for a selected node, is always empty.

**To Reproduce**
1. Navigate to `Cluster` -> `Nodes`
2. Click on a node

**Result**
Observe the list under `Pods` is empty, regardless of the namespace/project filter

**Expected Result**
The `Pods` list should contain the pods running on the selected node.

**Screenshots**
![image](https://user-images.githubusercontent.com/17559369/233323948-5592b634-9dcf-4abe-a95e-c4a65a656172.png)

**Additional context**
Without having visibility of the running pods on a node, the task of draining nodes is much harder, requiring one to resort to `kubectl` to confirm which pods are failing to be evicted.

**Comment by niusmallnan** [comment]
On a cluster with monitoring enabled, the Node Pods list can be displayed in my Rancher setup.

A request for `/v1/catalog.cattle.io.apps/cattle-monitoring-system/rancher-monitoring` may have affected the UI processing logic.

I think this should be a UI bug.

**Comment by p-kimberley** [comment]
UPDATE: I've destroyed the RKE2 Rancher cluster and rebuilt it from scratch.

Even on the fresh `local` cluster, the issue persists. No pods visible on the Node screen.

As @niusmallnan mentioned, I'm seeing a 404 response for an AJAX request to `/v1/catalog.cattle.io.apps/cattle-monitoring-system/rancher-monitoring` made by the front-end. Not sure if this is normal.

**Comment by bananflugan** [comment]
I can confirm this issue as well in 2.7.2. Since we upgraded from 2.6.11 -> 2.7.2 this past monday we see this very often. When i or any of our devs go into a workload the pod list is often empty. A page refresh fixes it.

**Comment by p-kimberley** [comment]
Rebuilt a fresh cluster using RKE2 1.24.12+rke2r1, Rancher v2.7.1. Pods show in Node view for the `local` cluster.

After `helm upgrade` to Rancher v2.7.2, issue surfaces. This is evidently a problem with the newer Rancher version.

Page refresh does not help with this, nor does clearing browser cache.

**Comment by niusmallnan** [comment]
@p-kimberley Is it possible to transfer this issue to the [rancher/dashboard](https://github.com/rancher/dashboard) repo? we have some ideas to fix it

**Comment by p-kimberley** [comment]
@niusmallnan Created new issue, closing this one: https://github.com/rancher/dashboard/issues/8725.
