### ISSUE TITLE
Upgrade Service Auto Restart is not taken into account

### ISSUE THREAD

**Issue by kevinliteon** [rancher/rancher#4122]
When I upgrade a service and I check option Auto Restart "Always", service keeping "never (Start Once)"

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v0.63.0` Cattle: `v0.155.0` UI: `v0.94.0` |
|Access|`localauth` `admin`|
|Route|`service.new`|

**Comment by deniseschannon** [comment]
Duplicate of https://github.com/rancher/rancher/issues/3707. Verified fixed in v1.0.0-rc4

**Comment by kevinliteon** [comment]
thank you :+1:
