### ISSUE TITLE
Is there any plans on adding Kerberos authentication support for Access Control?

### ISSUE THREAD

**Issue by frol** [rancher/rancher#4123]
We are using [FreeIPA](https://www.freeipa.org/) to manage user accounts in our company, and it would be great if there would be a support for Kerberos authentication in Rancher.

**Comment by frol** [comment]
This might be related to #1952.

**Comment by frol** [comment]
Gitlab OAuth integration (#1317) may also solve the issue for us.

**Comment by vincent99** [comment]
I believe people have gotten 389DS to work through the OpenLDAP config;  I don't know anything specifically about how, but there's nothing actually OpenLDAP-specific about it.  We do not have any immediate plans to add more auth providers.

**Comment by frol** [comment]
@vincent99 I'm not an expert in LDAP/Kerberos, but it seems that Rancher has only implemented LDAP authentication while FreeIPA uses exclusively Kerberos for authentication. Thus, while there is nothing specific about OpenLDAP vs 389DS, Kerberos makes things a bit difficult. I will need to spend more time on this, so maybe I will be able to re-enable native LDAP authentication just for Rancher.

**Comment by vincent99** [comment]
Yeah I don't know anything about FreeIPA either, I just know that it contains 389DS

**Comment by frol** [comment]
Finally, after some failures and tries I have managed to setup Rancher talking directly to LDAP avoiding Kerberos.

For those, who will face the same issue, I have partially followed [FreeIPA wiki-page about EJabberd integration](http://www.freeipa.org/page/EJabberd_Integration_with_FreeIPA_using_LDAP_Group_memberships) (the only important part there is "Create Bind account in FreeIPA"), and here are the Rancher options I specified on LDAP:

General

* Server: `freeipa.example.com`
* Port: `389`
* TLS: `No` (TLS is not yet configured correctly on FreeIPA side in our setup)
* Service Account: `uid=rancher,cn=sysaccounts,cn=etc,dc=example,dc=com`
* Service Account Password: *(this is what you set in the ldapmodify .ldif file on the article mentioned above)*
* Search Base: `dc=example,dc=com`

Users

* Object Class: `person`
* Login Field: `uid`
* Name Field: `displayName`
* Search Field: `uid`
* Enabled Field: *(empty; LDAP won't validate inactive user password anyway)*
* Disabled BitMask: `0`

Group

* Object Class: `groupofnames`
* Name Field: `description`
* Search Field: `cn`

P.S. I haven't got any use of Groups yet, since I don't understand what is the expected usage of those. Should a group name match an environment name, so users in a matching group automatically added into those environments?

**Comment by RoryHunter** [comment]
@frol this helped me, thanks.

**Comment by TheCrealm** [comment]
Thanks, it works!

But not with TLS.. 
Maybe Rancher does not accept self signed certificates..
Is there a way to use self signed certificate with the ldap connection?
