### ISSUE TITLE
[project-monitoring] default-allow-all NetworkPolicy

### ISSUE THREAD

**Issue by eumel8** [rancher/rancher#41241]
In [hardened.yaml](https://github.com/rancher/prometheus-federator/blob/main/charts/rancher-project-monitoring/0.2.0/templates/hardened.yaml#L107) of the rancher-project-monitoring Helm chart would a default-allow-all NetworkPolicy applied in the monitoring namespace. In a hardened environment I would expect a minimum of required access, e.g. outgoing connections to cluster prometheus endpoint, incoming to the applied services. Any thoughts?

**Comment by AndrewHoffmanQA** [comment]
hey @bashofmann  what exactly should QA validate here? would running a p0 regression suite on project monitoring on a hardened server be sufficient?

**Comment by bashofmann** [comment]
@AndrewHoffmanQA yes, it should be tested that project monitoring still works as expected in a hardened cluster.

**Comment by AndrewHoffmanQA** [comment]
testing scope-

run p0 test cases and an adhoc timeboxxed regression of prometheus federator functionality on a hardened downstream cluster

testing results:

downstream hardened: 

install - pass
helm locker functionality - pass
project monitoring- pass
UI check- pass
adhoc testing - pass


cluster information-
Local cluster
3 nodes, all. roles each node
rancher image v2.6.13
k8- v1.24.13
RKE1

downstream cluster
3 nodes, 1 role each node. 2xlarge 100gb
v1.24.13-rancher2-1

chart versions-
monitoring chart version- 100.2.0+up40.1.2
promfetheus federator version pulled from https://github.com/rancher/prometheus-federator - version 0.3.1
