### ISSUE TITLE
Support for displaying health_check values - Initializing/Degraded/Unhealthy/Started-Once for stacks in UI.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#4124]
Rancher Version:v1.0.0-rc2

Currently the same icon is used for displaying health_check values for Initializing/Degraded/Unhealthy/Started-Once for stacks.

<img width="1540" alt="screen shot 2016-03-24 at 3 09 09 pm" src="https://cloud.githubusercontent.com/assets/4266958/14045470/caf31942-f257-11e5-9c87-1c36000a799c.png">

Have different icons to represent these different health_check values.

**Comment by vincent99** [comment]
The icon is red for `unhealthy` and the difference is not particularly significant to most people for `degraded` vs `initializing`.  But fine.

**Comment by tfiduccia** [comment]
Version - master 3.27
Verified fixed
