### ISSUE TITLE
[RFE] Request for Addition of ".spec.ttlSecondsAfterFinished" Feature in Rancher Gatekeeper Chart

### ISSUE THREAD

**Issue by rohitsakala** [rancher/rancher#41243]
JIRA Issue - 5857

Description:
The customer installed OPA Gatekeeper using Fleet, and they have noticed that the Helm annotation "helm.sh/hook-delete-policy=hook-succeeded" does not always seem to be honoured. This has resulted in errors like "jobs.batch "rancher-gatekeeper-crd-create" already exists" and has required manual intervention to resolve (go to each cluster and delete that Job).

ErrApplied(2) [Cluster fleet-default/c-n2jrk: post-upgrade hooks failed: warning: Hook post-upgrade rancher-gatekeeper-crd/templates/jobs.yaml failed: jobs.batch "rancher-gatekeeper-crd-create" already exists]; WaitApplied(2) [Cluster fleet-default/aws-ec2-opencost]
Request:
The customer requested the addition of ".spec.ttlSecondsAfterFinished=15" to the CRD Jobs in the Rancher Gatekeeper chart located here: https://github.com/rancher/charts/blob/dev-v2.7/charts/rancher-gatekeeper-crd/102.0.0%2Bup3.10.0/templates/jobs.yaml

Objective: This feature would ensure that the CRD Jobs are automatically cleaned up after 15 seconds, preventing the errors mentioned above and reducing the need for manual intervention.

**Comment by gunamata** [comment]
We could not reproduce the issue and the Support team closed the Jira (SURE-5857)
