### ISSUE TITLE
[BUG] Rancher 2.7.2 Continually Logs 'Requesting kubelet certificate regeneration'

### ISSUE THREAD

**Issue by justdan96** [rancher/rancher#41256]
**Rancher Server Setup**
- Rancher version: 2.7.2
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: 1.24
- Cluster Type (Local/Downstream): Downstream, Imported
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:
Admin

**Describe the bug**

Since upgrading to Rancher 2.7.2 our `cattle-node-agent` pods are requesting kubelet certificate regeneration every 2 minutes. This didn't happen in 2.6.9 and setting the image to 2.7.2-rc7 we also do not see these log entries. Example log entries are below:
```
time="2023-04-24T10:23:50Z" level=info msg="Requesting kubelet certificate regeneration"
time="2023-04-24T10:25:51Z" level=info msg="Requesting kubelet certificate regeneration"
time="2023-04-24T10:27:51Z" level=info msg="Requesting kubelet certificate regeneration"
time="2023-04-24T10:29:52Z" level=info msg="Requesting kubelet certificate regeneration"
time="2023-04-24T10:31:52Z" level=info msg="Requesting kubelet certificate regeneration"
time="2023-04-24T10:33:52Z" level=info msg="Requesting kubelet certificate regeneration"
time="2023-04-24T10:35:53Z" level=info msg="Requesting kubelet certificate regeneration"
time="2023-04-24T10:37:53Z" level=info msg="Requesting kubelet certificate regeneration"
time="2023-04-24T10:39:53Z" level=info msg="Requesting kubelet certificate regeneration"
time="2023-04-24T10:41:54Z" level=info msg="Requesting kubelet certificate regeneration"
time="2023-04-24T10:43:54Z" level=info msg="Requesting kubelet certificate regeneration"
time="2023-04-24T10:45:54Z" level=info msg="Requesting kubelet certificate regeneration"
time="2023-04-24T10:47:55Z" level=info msg="Requesting kubelet certificate regeneration"
time="2023-04-24T10:49:55Z" level=info msg="Requesting kubelet certificate regeneration"
time="2023-04-24T10:51:56Z" level=info msg="Requesting kubelet certificate regeneration"
time="2023-04-24T10:53:56Z" level=info msg="Requesting kubelet certificate regeneration"
time="2023-04-24T10:55:56Z" level=info msg="Requesting kubelet certificate regeneration"
time="2023-04-24T10:57:57Z" level=info msg="Requesting kubelet certificate regeneration"
```
I've enabled trace level logging to try to get more information about what is going on, I'll paste that in a comment below.

**To Reproduce**

Upgrade RKE cluster to Rancher 2.7.2. Rancher local cluster is EKS, downstream clusters are all RKE.

**Result**
Log entries show kubelet certificate regeneration every 2 minutes.

**Expected Result**

Log entries show the kubelet certificates regenerated on the usual schedule.

**Screenshots**

**Additional context**

**Comment by HarrisonWAffel** [comment]
@justdan96 If you still have the environment available could you post the full logs of the rancher system agent? (With any sensitive details redacted). Additionally, do you have the `generate_serving_certificate` value set to `true` for the kubelet service? This may be an errant log message that is not indicative of actual certs being generated

**Comment by justdan96** [comment]
I can confirm we haven't set `generate_serving_certificate` to `true`. Does the log line need to be Info? Seems like it should be Trace or something similar.

**Comment by HarrisonWAffel** [comment]
I agree, I'll create an issue to fix this. This message can be safely disregarded if `generate_serving_certificate` is not true and shouldn't impact upgrading to 2.7.2, apologies for the false alarm.

**Comment by Josh-Diamond** [comment]
Ticket #41256 - Test Results - ✅ 
---

Verified on Rancher (HA Helm) upgrade from `v2.7.1 => v2.7.2`:
1. Fresh install of rancher `v2.7.1` on EKS (local) cluster w/ k8s `v1.24.13-eks-0a21954`
2. Provision two downstream RKE1 Custom clusters, one with a single-node and all roles, the other with 3-nodes and individual roles, both clusters using k8s `v1.24.13-rancher2-1`
3. Enable trace level logs and observe `cattle-node-agent` logs for both downstream clusters
4. Upgrade Rancher from `v2.7.1 => v2.7.2`
5. Observe rancher server successfully upgrades to `v2.7.2`
6. Observe clean `cattle-node-agent` logs for BOTH downstream clusters:
    - wait/watch for ~10-15 minutes
    - `Requesting kubelet certificate regeneration` log is not seen

7. Verified - clean logs w/ trace level logging enabled; as expected

**Comment by daemonadmin** [comment]
I see the same begaviour. 
Rancher 2.6.13, 1.23.4+rke2r1 - rancher management cluster. 
Downstream cluster: 1.17.17 RKE1.
Logs of cattle-node-agents are the same: 
`level=info msg="Requesting kubelet certificate regeneration"`

Should I ignore these messages or it may affect something?

**Comment by HarrisonWAffel** [comment]
@daemonadmin It looks like this didn't get back ported in time for 2.6.13, if you do not have `generate_serving_certificate` set to true you can safely ignore this message. I will work on getting a back port open soon

**Comment by HarrisonWAffel** [comment]
@MisderGAO Could you answer the following

+ What version of the agent is running on the downstream cluster?
+ Do you have debug logging on for the agent? 
+ Do you have the field `generate_serving_certificate: true` on your cluster? 

This log message was moved to the debug log level, so if you are still seeing this without having changed the log level the agent image has not been updated. If you do not have the field `generate_serving_certificate: true` on your cluster then it is likely a separate issue preventing your cluster from connecting.
