### ISSUE TITLE
[BUG] Project owner can't manage project members

### ISSUE THREAD

**Issue by xaha24** [rancher/rancher#41255]
**Rancher Server Setup**
- Rancher version: 2.6.11
- Installation option : Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1

**Information about the Cluster**
- Kubernetes version: RKE 1.21.14
- Cluster Type (Local/Downstream): Local
 
**User Information**
- What is the role of the user logged in? Project Owner

**Describe the bug**
After Upgrading to 2.6.11 project owner get an error after changing project members. The following error occurs: error creating binding: Forbidden 403: podsecuritypolicytemplateprojectbindings.management.cattle.io is forbidden: User "u-xxxxxx" cannot create resource "podsecuritypolicytemplateprojectbindings" in API group "management.cattle.io" in the namespace "c-xxxxx".

The error only occurs with project owner. admis can change the project members.

**Comment by MKlimuszka** [comment]
A ticket title and more thorough reproduction steps would help this get triaged faster. What version are you upgrading from?

**Comment by xaha24** [comment]
Thanks for your question. I upgraded from version 2.6.9.

**Comment by xaha24** [comment]
After upgrading to 2.6.12 the error is gone. Thanks for fixing.

**Comment by wzrdtales** [comment]
in 2.7.9 the same error exists again
