### ISSUE TITLE
Rancher projects as YAML 

### ISSUE THREAD

**Issue by sravanakinapally** [rancher/rancher#41265]
## Description

Rancher projects as YAML files. Projects allow us to group namespaces and assign quotas,role bindings on the project; as of now, we cannot access projects as YAML or manifest files. The idea is to manage projects as GitOPS so that we can leverage the automatic deployment of projects into the target cluster with additional automated programming. 

And if projects can be scoped to cluster groups on Rancher Fleet this would solve the issue as well. 

## Possible Implementation
Rancher objects like project/quotas/rolebindings as manifest/YAML files 
Rancher projects span across Fleet cluster groups 

## Context

As the volume of namespaces and projects is growing, we would like to have an entire project and related components for the project to be available as code/yaml, which would simplify deployments and moving targets across clusters.

**Comment by maxgio92** [comment]
Hi all, this is still an interesting and valuable proposal I think.

The possibility to manage project declaratively would be beneficial to the Rancher ecosystem, enabling for example a GitOps approach of resources, `Project`s included.

These latter would further be integrated with multi-tenancy frameworks (e.g. [Capsule](https://github.com/clastix/capsule) alongside the related integration [addon](https://github.com/clastix/capsule-addon-rancher)).

**Comment by w3blogfr** [comment]
Please do not abandon project layer, it's very usefull...
declaring with yaml would be very good.

**Comment by davidpasqua-asml** [comment]
was this closed? can not be done yet?
