### ISSUE TITLE
port link has invalid url for LB services that binds to an ipaddress.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#4126]
Rancher Version: Build from master Mar/25

Steps to reproduce the problem:
Create LB rule by specifying "Source IP/Port*" as `<ip>: port`.

Once LB service is activated and running , try to access the port link for this LB service in "stacks" view

Link is of the format `<ip>:<port>:<target-port>`

<img width="1369" alt="screen shot 2016-03-25 at 9 33 17 am" src="https://cloud.githubusercontent.com/assets/4266958/14048726/3e0cbf0e-f26d-11e5-9146-32ae7e3012c8.png">

**Comment by tfiduccia** [comment]
Version - v1.0.0-rc1
Verified fixed
