### ISSUE TITLE
The first time I add host, I get an error page after setting Host URL

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4127]
Version - v1.0.0-rc3

Steps to Reproduce: 
1.  Start with fresh version of Rancher
2.  Click on Add Host
3.  Click on Save on the Host Registration URL page

Results: Error page comes up.  
GET http://104.197.41.106:8080/v1/settings/api.host net::ERR_CONNECTION_REFUSED (from dev tools)

Expected: No Error page

**Comment by vincent99** [comment]
WSP is restarting at just the wrong time between pages

**Comment by tfiduccia** [comment]
Version - v1.0.0-rc4
Fixed verified
