### ISSUE TITLE
Merge dev-v2.6-2023-04-patches into dev-v2.6 again

### ISSUE THREAD

**Issue by vivek-infracloud** [rancher/rancher#41275]
RKE1 December KDM patches are tested and ready for the release.

Custom branch `dev-v2.6-2023-04-patches` was merged in `dev-v2.6` 4 days ago - here https://github.com/rancher/kontainer-driver-metadata/pull/1125. 

However the RKE2 and k3s changes were merged into custom branch recently from `brooksn:dev-v2.6-rke2-april-2023-patches` here - https://github.com/rancher/kontainer-driver-metadata/pull/1118, hence these changes are not on `dev-v2.6` branch.

This ticket is to track the merging of `dev-v2.6-2023-04-patches` into the `dev-v2.6` branch again to have the recent RKE2 and k3s changes in dev branch.

**Comment by rayandas** [comment]
The changes are now synced as https://github.com/rancher/kontainer-driver-metadata/pull/1129 PR is merged.

**Comment by sowmyav27** [comment]
`v2.6.12-rc4` is tagged

**Comment by vivek-infracloud** [comment]
Tested the RKE2 and K3s versions on rancher v2.6.12-rc4. 
Correct versions are showing up and cluster provisioned successfully. 

Hence, closing this issue.
