### ISSUE TITLE
Rancher container sidekicks silently ignore container links

### ISSUE THREAD

**Issue by LLParse** [rancher/rancher#4129]
Rancher Version: 1.0.0-rc3

Docker Version: 1.10.3

OS: Boot2Docker 1.10.3

Steps to Reproduce: 
1. Define a compose template with two containers, one defined as a sidekick of the other. Define a link from the sidekick to the main container, mapping the container name to something new to avoid a namespace collision.
2. Launch the template
3. From the sidekick, attempt to resolve the IP address of the main container using the specified link name.

Results: 
The name can't be resolved.

Expected:
The name resolves to the main container's IP address
- or -
Rancher warns the user that links are ignored on sidekick containers in favor of Rancher-specific DNS resolution for cattle-orchestrated stacks.

**Comment by LLParse** [comment]
[Here](https://github.com/LLParse/community-catalog/tree/issue-4129/templates/issue-4129) is an example catalog entry for reproducing/testing.

**Comment by alena1108** [comment]
@LLParse we do not support links from sidekick to master (and vice versa). It gets represented as a single service in Rancher (similar to k8s pod), and you can only do links from one service to another.

>>  something new to avoid a namespace collision.

It shouldn't be any namespace collisions. Service name is unique per stack, and if you resolve it by servicename.stackname.rancher.internal, it will always get resolved to a single service.

 >> or - Rancher warns the user that links are ignored on sidekick containers in favor of Rancher-specific DNS resolution for cattle-orchestrated stacks.

@deniseschannon we should document it.

**Comment by LLParse** [comment]
@alena1108 Thanks for clarifying. I expected that it was unsupported (redundant) since a Rancher sidekick is effectively a link with other side effects. The DNS name collision for which I was referring (servicename and linkname) is only relevant if you are trying to confirm/deny that the containers are truly linking, since servicename alone will already resolve in context of a stack.
