### ISSUE TITLE
In swarm I can create empty project - then it errors

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4130]
Version : v1.0.0-rc3

Steps to Reproduce: 
1.  Setup swarm
2.  Click on Add Project
3.  Give name and click Create
4.  Click on Name

Results: Error page.  You actually should not be able to create a project without some sort of info in the docker-compose.yml.

Expected: Make docker-compose.yml a required field.

**Comment by vincent99** [comment]
Not applicable as of 1.2..
