### ISSUE TITLE
[RFE] Improve Steve Schemas performance

### ISSUE THREAD

**Issue by MbolotSuse** [rancher/rancher#41301]
**Is your feature request related to a problem? Please describe.**
Steve currently provides schemas which provide several pieces of information, such as:
- What fields exist on a resource
- What verbs a user has on a resource

These schemas can be quite large, and the UI needs to fetch all of them each time it refreshes, which causes significant performance impacts.

**Describe the solution you'd like**
Steve should support two separate endpoints - `/v1/schemas` and `/v1/schemaDefinitions`. 

The schema endpoint should only contain information for top-level resources (i.e. resources representing actual resources in k8s and not their field definitions). For example, this endpoint would contain information for pods, but not information for a pod spec. Information on things like resourceVerbs should be included in this endpoint.

The schemaDefinitions endpoint should contain full field definitions for every resource (like it does today), but should not contain any information (such as verbs) on access to those resources.

The back end may need to adjust the internal vs external representation of schemas to meet these requirements.

After this has been implemented, the UI should only pull the entirety of the resources endpoint on refresh. It should only fetch on an as-needed basis from the schemaDefinitions endpoint. 

**Describe alternatives you've considered**
A previous attempt was made to make the schemas work like the "resources" endpoint described in here. This was abandoned since the UI needs full field definition to provide suggestions on creating helm charts. 

**Additional context**

**Comment by richard-cox** [comment]
From a purely UI perspective, it may be best swap the change to schemas and new resource endpoint around. This would help us avoid a mass rename in the UI. Thought it would mean other consumers of the API would be more heavily affected. If this is just an implementation detail we can work it out later? If not we would need to plan the feature a bit more.

Might be worth double checking with Colleen regarding the new `resources.project.cattle.io` resource / endpoint to support namespace/project filtering.

Linking UI issue https://github.com/rancher/dashboard/issues/7716

**Comment by MbolotSuse** [comment]
> From a purely UI perspective, it may be best swap the change to schemas and new resource endpoint around. This would help us avoid a mass rename in the UI.

I'll make this change. Absent any other evidence, right now I would consider the UI the main consumers of the schemas, so a change like this should be accceptable.

**Comment by richard-cox** [comment]
Linking customer issue SURE-6584

**Comment by richard-cox** [comment]
There's a few use cases
- Users create a resource via yaml (instead of form) and we show resource fields as commented out lines
- Create forms for credentials and machine configs base on node driver schema resource fields
- Create a pre-populated json object when creating provisioning clusters
- Conditionally show tabs given resource fields in schema (though only one place, which is i think cluster `conditions`
- A few other misc places (determining ingress classes, CIS cluster scan types, etc)

In terms of frequency i've taken steps in the [UI PR](https://github.com/rancher/dashboard/pull/10141) to restrict the times we hit the new endpoint to only when needed. These are all trigger by user's navigating to a certain area and should be restricted to a single call. There may be multiple per session, but not anything quickly / sequentially.

During development we did hit one issue cacheing side. When a new chart is installed (for instance monitoring) which contains CRDs a user navigating to the new screens and attempting to access a new schema (from crd)'s definitions would fail whilst the cache is reset. We have a retry in place UI side to cater for this now.

**Comment by MKlimuszka** [comment]
Blocked until UI merges their changes.

**Comment by MbolotSuse** [comment]
@richard-cox let me know when the Frontend is ready to merge and we can merge at the same time.

**Comment by richard-cox** [comment]
Almost there. Neil's keen to merge and has reviewed, but requested a review from @codyrancher. Once done will let you know

**Comment by andreas-kupries** [comment]
Not sure what to review here. All the referenced PRs are merged. Only various referenced issues are open.

**Comment by MbolotSuse** [comment]
## Validation Template

## Changes

- A new endpoint `/v1/schemaDefinitions` was added
  - This endpoint allows you to get the full field definition of a single type.
  - Attempting to list all definitions returns no results.
  - This list works by using the same name as the schemas. For example, for 
`management.cattle.io` `GlobalRoles`:
    - The schemas endpoint is `/v1/schemas/management.cattle.io.globalroles`.
    -  The schema definitions endpoint is `/v1/schemaDefinitions/management.cattle.io.globalroles`.
    - The field definitions are taken from the preferred version of the group.
  - Users can only access the schemaDefinition endpoint for a schema if they can get the schema itself. In short, if you can't get `/v1/schemas/x` you can't get `/v1/schemaDefinitions/y`.
- The current `/v1/schemas` endpoint has been changed to no longer return field definitions.
  - Some built-in, non-k8s types may still have limited field definitions.
  - This means that only top-level types are included in this endpoint now - so `Pods` will be in this endpoint but `PodSpec` will not.
- A caching mechanism was added for the schemaDefinitions endpoint
  - Upon adding/removing a relevant resource, we will retrieve definitions for all resources and update the internal cache.
  - We use an internal locking mechanism to attempt to ensure only one refresh occurs at a given moment.
  - User requests should not have to wait for the caching mechanism to complete
  - We wait a short time between when a CRD/APIService is added and when we refresh. This can be controlled by the env var `CATTLE_CRD_REFRESH_DELAY_SECONDS` and defaults to 2 seconds. This is done since the api definition for a CRD is not immediately available in kubernetes after a CRD has been refreshed.
  - We forcibly refresh all CRDs in case the first mechanism does not capture a newly added CRD. This can be controlled by the env var `CATTLE_BACKGROUND_REFRESH_MINUTES` and defaults to 10 minutes. 

## Areas or cases that should be tested

- Create a CRD.
  - After a short period, it should be visible in both `/v1/schemas` and `/v1/schemaDefinitions`
  - There may be a shorter period where it is visible in `/v1/schemas` but not in `/v1/schemaDefinitions`. An error with code > 500 should be noticed during this time.
- Update a CRD with new fields (add/remove)
  -  Note that the definition was updated after a short priod.
- Remove a CRD.
  - The definition, and schema should no longer be present.
- Access the schemas endpoint. The size of the result should be smaller than in previous iterations, and the request should be returned more quickly.
- Access the schemas endpoint during a refresh. A significant delay should not be observed between the "during a refresh" and "not during a refresh" cases.

## What areas could experience regressions

UI Functionality relying on the schema fields/definitions. Particularly regarding preferred versions/types.

## Are the repro steps accurate/minimal?

N/A.

**Comment by Priyashetty17** [comment]
Testing for this issue will be a shared effort between **3 teams - Frameworks, BullsEye and UI**.
- **Frameworks** - will focus on validating the fields for existing steve endpoint "v1/schemas" and the new steve endpoint "v1/schemadefinitions" and CRUD scenarios - @Priyashetty17 to work on Frameworks specific test plan
- **Bullseye**: cc @git-ival to add more details around testing caching, performance and scalability 
- **UI**: cc @yonasberhe23 for testing UI changes for this issue (Reference: https://github.com/rancher/dashboard/issues/7716)

**Comment by Priyashetty17** [comment]
Moving this back to "QA Next Up". Automation of P0 tests for this issue is complete. Tests to validate this issue will be executed when fixes for https://github.com/rancher/rancher/issues/45158 and https://github.com/rancher/rancher/issues/45157 get merged.

**Comment by git-ival** [comment]
Bullseye QA: Automation of test cases for this issue is complete. Runs for each test case have been shared internally.

**Comment by Priyashetty17** [comment]
All scenarios in the test plan (confluence page) have been validated with `v2.9-ddabf6b2266255276352beb1eeb740d9e4de802d-head` 

- [ ] Schemas Endpoint Validation - Local Cluster
- [ ] Schemas Endpoint Validation - Downstream Cluster
- [ ] Existing Schema - Local Cluster
- [ ] Existing Schema - Downstream Cluster
- [ ] Schemadefinitions Endpoint Error Validation - Local Cluster
- [ ] Schemadefinitions Endpoint Error Validation - Downstream Cluster
- [ ] Schemadefinitions Endpoint Validation for existing schema - Local Cluster
- [ ] Schemadefinitions Endpoint Validation for existing schema - Downstream Cluster
- [ ] Verify Schema Definitions Exists For Each Schema - Local Cluster
- [ ] Verify Schema Definitions Exists For Each Schema - Downstream Cluster
- [ ] Create a CRD - verify schemas and schemadefinition
- [ ] Delete a CRD - verify schemas and schemadefinitions
- [ ] Update a CRD - verify schemas and schemadefinitions
- [ ] Create a CRD with CRD refresh delay set to 120seconds
- [ ] Update a CRD with CRD refresh delay set to 120seconds
- [ ] Verify Preferred version in schemas endpoint - Local Cluster
- [ ] Verify Preferred version in schemas endpoint - Downstream Cluster
- [ ] Verify Preferred version in schemadefinitions endpoint
- [ ] Upgrade Rancher and verify schemas and schemadefinition endpoints
- [ ] Validate the rkeConfig field in provisioning.cattle.io.cluster schema is correctly defined with subfields
- [ ] APIGroup Endpoint Validation - Local Cluster
- [ ] APIGroup Endpoint Validation - Downstream Cluster

**Comment by Priyashetty17** [comment]
@MKlimuszka Frameworks QA has finished validating this issue. However, UI validation for this issue appears to be pending. Should we close this issue now that both Frameworks and Bullseye QA have completed their validations, or should we keep it open until the UI team finishes their validation?
