### ISSUE TITLE
Edit Cluster Config Behavior [BUG]

### ISSUE THREAD

**Issue by jtrewartha** [rancher/rancher#41307]
**Rancher Server Setup**
- Rancher version: 2.7.0

**Information about the Cluster**
- Kubernetes version: 1.23.10+rke2r1
- Cluster Type (Local/Downstream): Downstream vmware cluster provisioned via terraform

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Admin

**Describe the bug**
When you use the GUI to edit a cluster that has had the underlying template deleted, a new template is automatically chosen from the available list without notifying the user. When the user saves their intended changes, it also applies the new template to the cluster, potentially crippling it.

**To Reproduce**
Create a vsphere template and provision a cluster using this template.
Inside vsphere delete the template-file referenced by the provisioned cluster.
In the rancher UI edit the cluster and notice the template chosen is different, and selected from the list of available templates. When this is saved the template change is applied to the cluster.
**Result**
In the rancher UI edit the cluster and notice the template chosen is different, and selected from the list of available templates. When this is saved the template change is applied to the cluster.
**Expected Result**
In the rancher UI edit the cluster and either be forced to select a new template or this field should have validation to ensure the template still exists, otherwise it should stop the ability to save/update the config.

SURE-6214

**Comment by rak-phillip** [comment]
This issue is related to #9559.

We will notify the user when values are invalid in #9699 instead of replacing them.

**Comment by gaktive** [comment]
I suspect the right tickets are in the dashboard repo: https://github.com/rancher/dashboard/issues/9559 & https://github.com/rancher/dashboard/issues/9699 since both touch vSphere.

**Comment by snasovich** [comment]
Closing this backend issue as it's tracked in already-resolved https://github.com/rancher/dashboard/issues/9699
