### ISSUE TITLE
[RFE] GCP us-south-1 region is not showing up for GKE

### ISSUE THREAD

**Issue by achavan-cr** [rancher/rancher#41317]
**Is your feature request related to a problem? Please describe.**
GKE integration with Rancher do not support all the GCP regions.
GKE is supported in Dallas (us-south-1) but while creating new cluster from rancher, it do not show up us-south-1 in the Region drop-down.
Please find the screenshot attached

**Describe the solution you'd like**
Support for us-south-1 region in the Rancher for creating GKE cluster

![Screenshot 2023-04-27 at 12 58 19 PM](https://user-images.githubusercontent.com/121092544/234791177-0960a427-0289-47c6-a6dd-5caf46fd249c.png)

**Comment by an1ket** [comment]
Any update?
