### ISSUE TITLE
Documentation for OpenLDAP configuration

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#41322]
Related to https://github.com/rancher/rancher/issues/38029

We need documentation that covers custom schema fields related to OpenLDAP configuration. This is required because it does not get tested in the authentication flow

**Comment by prachidamle** [comment]
@nflynt is there a docs PR that can be linked here to this ticket?

**Comment by prachidamle** [comment]
PR for docs: https://github.com/rancher/rancher-docs/pull/599

**Comment by martyav** [comment]
@prachidamle The doc is now merged into the release branch.

**Comment by dan05011991** [comment]
This can now be closed
