### ISSUE TITLE
Enhance provisioning-tests to log more debug data

### ISSUE THREAD

**Issue by Oats87** [rancher/rancher#41334]
provisioning-tests are very difficult to debug because they do not include the full picture.

We should increase logging of the provisioning-tests to allow for better debugging.
SURE-6250

**Comment by Oats87** [comment]
@sowmyav27 given this issue is entirely around testing... what do we need to do to "close" the issue?

**Comment by Sahota1225** [comment]
@jakefhyde - can you please validate this ticket

**Comment by jakefhyde** [comment]
## Testing

No testing required, the CI debug logs were updated to produce more output, and example of which can be found under the `Test_Operation_Custom_EtcdSnapshotOperationsOnNewCombinedNode` section of the `provisioning-operations-tests-k3s` on this drone run: https://drone-publish.rancher.io/rancher/rancher/9778/3/2
