### ISSUE TITLE
[BUG] Clusters lost upgrading from Rancher 2.7.1 to 2.7.3

### ISSUE THREAD

**Issue by dvarrazzo** [rancher/rancher#41333]
Rancher 2.7.1 originally installed from Helm chart on k8s v1.23.8. 

Upon upgrade to Rancher 2.7.3, fleet was updated from 0.5.2 to 0.6.0.

Every bundle deployed has lost its `global.fleet.clusterLabel` settings, which resulted in every service re-deployed and pretty much broken.

Attempting to change the labels on a cluster has failed because "Cluster agent is not connected". Attempts to restore connection so far seem to fail.

On the managed cluster, logs of the agent show:

```
$ stern -n cattle-system cattle-cluster-agent
+ cattle-cluster-agent-77c9887864-sjf46 › cluster-register
cattle-cluster-agent-77c9887864-sjf46 cluster-register INFO: Environment: CATTLE_ADDRESS=10.255.0.237 CATTLE_CA_CHECKSUM= CATTLE_CLUSTER=true CATTLE_CLUSTER_REGISTRY= CATTLE_INGRESS_IP_DOMAIN=sslip.io CATTLE_INSTALL_UUID=fa835ebb-1c55-4471-8ffb-43877b90569c CATTLE_INTERNAL_ADDRESS= CATTLE_IS_RKE=false CATTLE_K8S_MANAGED=true CATTLE_NODE_NAME=cattle-cluster-agent-77c9887864-sjf46 CATTLE_SERVER=https://rancher.XXX.com CATTLE_SERVER_VERSION=v2.7.3
cattle-cluster-agent-77c9887864-sjf46 cluster-register INFO: Using resolv.conf: search cattle-system.svc.cluster.local svc.cluster.local cluster.local sgcqtyvl235utjtdv4feyp3sbd.dx.internal.cloudapp.net nameserver 10.0.0.10 options ndots:5
cattle-cluster-agent-77c9887864-sjf46 cluster-register INFO: https://rancher.XXX.com/ping is accessible
cattle-cluster-agent-77c9887864-sjf46 cluster-register INFO: rancher.XXX.com resolves to N.N.N.N
cattle-cluster-agent-77c9887864-sjf46 cluster-register time="2023-04-28T15:32:55Z" level=info msg="Listening on /tmp/log.sock"
cattle-cluster-agent-77c9887864-sjf46 cluster-register time="2023-04-28T15:32:55Z" level=info msg="Rancher agent version v2.7.3 is starting"
cattle-cluster-agent-77c9887864-sjf46 cluster-register time="2023-04-28T15:32:55Z" level=info msg="Connecting to wss://rancher.XXX.com/v3/connect/register with token starting with r5l2nb4bsn4km28x4qm2cbwq88b"
cattle-cluster-agent-77c9887864-sjf46 cluster-register time="2023-04-28T15:32:55Z" level=info msg="Connecting to proxy" url="wss://rancher.XXX.com/v3/connect/register"
cattle-cluster-agent-77c9887864-sjf46 cluster-register time="2023-04-28T15:32:55Z" level=info msg="Requesting kubelet certificate regeneration"
```

and is stuck here.  Tried to delete namespaces cattle-* and local on the managed cluster, and every resource installed by the import/....yaml file, and re-apply it, but the state doesn't change (managed cluster stuck on "Requesting kubelet certificate regeneration", cluster marked as not connected).

How can we get out of this state? Thank you

**Comment by snasovich** [comment]
Assigning @jakefhyde to (eventually) investigate.

**Comment by jakefhyde** [comment]
@dvarrazzo Can you share some more information into how these bundles were configured per and post upgrade?

**Comment by snasovich** [comment]
Closing the issue as we can't investigate much further without additional information requested. We have not caught anything like this in our internal testing as far as I can see.
Please also note there were many stability improvements to handling of RKE2/K3s provisioned clusters between 2.7.3 and 2.7.9.
