### ISSUE TITLE
Bump Nginx Controller to 1.7.0 for RKE1 cluster version 1.24+ 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#41338]
Starting from [v1.6.4](https://github.com/kubernetes/ingress-nginx/releases/tag/controller-v1.6.4), Nginx Controller adds the support for configuring `gzip-disable`. 

To bring the new functionality into the RKE1 cluster, we'd like to bump the Nginx Controller to [1.7.0](https://github.com/kubernetes/ingress-nginx/releases/tag/controller-v1.7.0), which is the latest version, for RKE1 cluster version 1.24 and above.  

SURE-6025

**Comment by kinarashah** [comment]
@jiaqiluo Infracloud team would be working on this to update for k8s 1.26, once that is done we can test and forward port for other k8s versions. https://github.com/rancher/kontainer-driver-metadata/pull/1133#discussion_r1181883026
