### ISSUE TITLE
Move CAPR and provisioningv2 controllers into independent folders/packages

### ISSUE THREAD

**Issue by Oats87** [rancher/rancher#41346]
Today, provisioningv2 encompasses "RKE2" and "v2prov" as almost synonymous packages. As we continue to develop provisioning within Rancher, we are moving towards a model where "provisioningv2" encompasses the `provisioning.cattle.io` objects and is essentially the generating/integrating framework/controllers for the Rancher functionality, and `CAPR` or `cluster-api-provider-rancher` which is a cluster-api bootstrap/controlplane provider for RKE2 and K3s. In order to enforce the delineation and continue logical development into this model, we need to decouple the "rke2" package from the `provisioningv2` package.

The first step is to simply move the controllers/rename the package from rke2 to capr.

As we continue development on the framework + provider, we can continue decoupling. The end goal is to be able to use CAPR as a standalone provider in a CAPI management cluster without requiring Rancher, to allow for active management of K3s/RKE2 clusters.
SURE-6250

**Comment by Sahota1225** [comment]
@jakefhyde - Can you please validate this issue

**Comment by jakefhyde** [comment]
## Testing

No testing required, all changes made were non-functional and related to the structuring of the repository.
