### ISSUE TITLE
VM details page's menu and status are in wrong place

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4134]
Version:

Steps to Reproduce: 
1.  Create a VM (create a packet host & add VM to that host)
2.  Click on VM name to get to details page

Results: The VM's menu and status are not consistent with the rest of the application.
![image](https://cloud.githubusercontent.com/assets/11514927/14052420/6a3400d2-f287-11e5-97fb-216b9d6824e0.png)

Expected:  Menu should be on the far right & the status should be to the left of it.  You can see this in the all the other details pages (like host, stack or services)

**Comment by tfiduccia** [comment]
Also for these:
1.  They look bigger then in other screens.
2.  The drop-down and the Menu items are different sizes

**Comment by lvuch** [comment]
https://github.com/rancher/ui/pull/722

**Comment by tfiduccia** [comment]
Version - master 6/13
Verified fixed
