### ISSUE TITLE
dynamic ports

### ISSUE THREAD

**Issue by SydOps** [rancher/rancher#4135]
Rancher Version: 

    v0.63.1
    rancher/server           latest              f2584280e144        10 days ago         768.1 MB

Docker Version: 

    Docker version 1.10.1, build 9e83765

OS: 

    rancheros 0.4.3

Steps to Reproduce: 
```
CREATE A MULTI-CONTAINER APPLICATION USING RANCHER COMPOSE (follow the steps in [quick start guide](http://docs.rancher.com/rancher/quick-start-guide/)
need set dynamic ports on mywordpress containers, and loadbalancer (wordpresslb) can connnect to that dynamic ports automatically
```

Results:  

    not sure if Rancher compose support dynamic ports or not. 

Expected: 

    Start services with dynamic ports, Docker Datacenter (UCP) has this function already.

**Comment by vincent99** [comment]
I'm not sure what the question is here, but the load balancer connects to target services using the overlay network and does not need the target port to be published at all, whether dynamically or statically assigned.

**Comment by SydOps** [comment]
seems Rancher support random ports

http://docs.rancher.com/rancher/rancher-ui/infrastructure/containers/
