### ISSUE TITLE
[BUG] After 2.7.x upgrade Pods list is empty for all nodes

### ISSUE THREAD

**Issue by alexjarvis** [rancher/rancher#41363]
**Rancher Server Setup**
- Rancher version: 2.7.*
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2 
- Proxy/Cert Details: Let's Encrypt certificate provisioned via Cert Manager

**Information about the Cluster**
- Kubernetes version: v1.24.12+rke2r1
- Cluster Type (Local/Downstream): Local; three primaries, five worker nodes

**User Information**
- What is the role of the user logged in? Admin

**Describe the bug**
In Rancher 2.7.x, the Pods list for all nodes is blank (ex: /dashboard/c/local/explorer/node/node1#pods).

There is a workaround. If you click on the node name from the Workloads > Pods list, the list will be populated until the next page refresh.

**To Reproduce**

1. Install Rancher 2.7.x on RKE2 v1.24.12 (tested both upgrade of 2.6 and clean install)
2. Click on any node from the Nodes list (Cluster > Nodes)
3. Note that no Pods are listed on the pods' tab "There are no rows to show."
4. Now click on the Pods list (Workloads > Pods)
5. Find a workload running on the node you just tried to look at, click on the node link
6. You will end up on the pods' list for that node with the same URL, but the list will be populated appropriately
7. Reload the page

**Result**
The pods' list will be empty when the node is opened directly and populated when accessed via workloads.

**Expected Result**
The actual pods running on the node should be visible regardless of how the list is loaded.

**Screenshots**

<img width="647" alt="CleanShot 2023-05-01 at 16 31 21@2x" src="https://user-images.githubusercontent.com/269270/235535106-8581b45c-a9f3-4011-b6ee-2c632fbf6fab.png">

<img width="818" alt="CleanShot 2023-05-01 at 16 42 37@2x" src="https://user-images.githubusercontent.com/269270/235536780-59724607-3dbf-4236-a739-a3981585c15c.png">

**Comment by reb-xpat** [comment]
Seeing the same issue after updating to 2.7.3.

**Comment by niusmallnan** [comment]
Please track this issue: https://github.com/rancher/dashboard/issues/8725

**Comment by lomasger** [comment]
Likewise, seemed OK on 2.7.1 (v1.23.14+rke2r1) but after upgrading to 2.7.3 (v1.24.13+rke2r1) the pod count and list is now empty on node view.

**Comment by shkarface** [comment]
Same issue here on v2.7.3

**Comment by mconnley** [comment]
Issue is still present for me on v2.7.3.

**Comment by skycyan** [comment]
Same issue here on v2.7.3 【There are no rows to show】

**Comment by jcmontigny** [comment]
Same issue in `v2.7.4`, also : 
- he total number of pods is correct on the cluster dashboard page, but on each node, it shows up as 0.
- If I click on a pod object in the cluster dashboard page in the events area, I am taken to the pod page. Then if I click on the node name that hosted that pod, I can see it on the pods list. The first time I did this, I only saw the related pod in the list ; after a second attempt, I now see all the pods for that particular node, and also the number of pods running on that node is correct.
- BUT if I leave the node page and go back to the cluster page, then back to the node page, the list is now empty.

**Comment by fernandomullerjr** [comment]
Same issue here on v2.7.2.

**Comment by diogoalvesrs** [comment]
Same issue here on v2.7.2.

**Comment by jcmontigny** [comment]
Installed `v2.7.5` today and can confirm the issue is fixed.

**Comment by alexjarvis** [comment]
This appears to be fixed in v2.7.5.
