### ISSUE TITLE
RKE2 and K3S - 1.26 support in KDM

### ISSUE THREAD

**Issue by rancher-max** [rancher/rancher#41376]
# KDM Updates

We need to add initial support for k8s v1.26 in KDM so that it is available for support in Rancher Manager.

| New Kubernetes Version  | Min Rancher Version | Max Rancher Version |
|                  :---:                  |              :---:               |               :---:               |
| v1.26.4+rke2r1                  | v2.7.5-alpha1             | v2.7.99 |
| v1.26.4+k3s1 | v2.7.5-alpha1 | v2.7.99 |

# KDM Branch
https://github.com/rancher/kontainer-driver-metadata/tree/dev-v2.7

# Chart Changelog
N/A - This will be the first 1.26 version added

# Argument Changelog

There have not been any new arguments, but some arguments have been deprecated in v1.26 for k3s and should be specially considered when making these changes:
https://docs.k3s.io/cli/server#deprecated-options
Specifically:

Flag | Default | Description
-- | -- | --
--flannel-backend value | "vxlan" | One of 'none', 'vxlan', 'ipsec'(deprecated), 'host-gw', 'wireguard-native', or 'wireguard'(deprecated)

# Additional Notes

Related to https://github.com/rancher/rancher/issues/41113

**Comment by rancher-max** [comment]
When testing, we should use rancher `v2.7-head` for imported and provisioned clusters

**Comment by rancher-max** [comment]
Initial testing looks pretty good (thanks Kinara):
![image](https://user-images.githubusercontent.com/55997940/236068360-3e6af529-3d68-4ffb-935f-c9918098f27b.png)

**Comment by cwayne18** [comment]
@rancher-max is this clear to close?

**Comment by rancher-max** [comment]
We can probably close it... we still need to resolve the Argument Changelog bits, but can do that as part of May release cycle I think.

**Comment by rancher-max** [comment]
The argument changelog bits were fixed and validated as part of May releases, so this is good to close now.
