### ISSUE TITLE
[BUG] Rancher agent's `CATTLE_REQUEST_CACHE_DISABLED` env var is false by default

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#41379]
**Rancher Server Setup**
- Rancher version:
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version:
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:

**Describe the bug**

[Cache is enabled in agent](https://github.com/rancher/steve/blob/master/pkg/stores/partition/store.go#L63) but is not being used by UI yet. This is causing memory to spike. [In the long term we need to address the memory issues](https://github.com/rancher/rancher/issues/41378) but for now it should be disabled by default in the agent.

**To Reproduce**

1. create a downstream cluster
2. install monitoring
3. create 1000 configmaps with any data of at least size 1kb in downstream cluster. You can make either number larger to make it easier to notice the difference.
4. list configmaps

**Result**
should see more memory used than usual.

**Expected Result**

Now that it is disabled you should see at least 1mb less data than usual.

**Screenshots**

**Additional context**

**Comment by orangedeng** [comment]
Can I link to this issue? It seems the same issue to me. https://github.com/rancher/rancher/issues/41225

**Comment by rmweir** [comment]
@orangedeng we are separating it out because we need a more long term fix. This issue and https://github.com/rancher/rancher/issues/41378 are related to https://github.com/rancher/rancher/issues/41225. This should just improve the situation for now.

**Comment by rmweir** [comment]
release note:
A feature that resulted in a significant memory increase in both rancher and downstream clusters has been disabled.

**Comment by atsai1220** [comment]
If anyone needs to loop through their Rancher environment. 

``` shell
rancher server switch
for x in `rancher cluster ls --format '{{.Cluster.Name}}'`;
do
  kubectl set env deploy/cattle-cluster-agent -n cattle-system CATTLE_REQUEST_CACHE_DISABLED=true --context $x
done
```

**Comment by orangedeng** [comment]
The issue title is a little bit confusing. I read through the PR and it means that the list cache in steve will be disable by default and only setting `CATTLE_REQUEST_CACHE_DISABLED=false` will enable the list cache.

**Comment by rmweir** [comment]
The wording in general is confusing. It is not being changed because this is only temporary and will be once again enabled by default. That logic will be changed at that time. This way we do not need to introduce another env var. See https://github.com/rancher/steve/pull/106#discussion_r1190471067.

**Comment by Priyashetty17** [comment]
## **QA TEST PLAN**

### **Scenario1: Fresh install v2.7-head** (Test Result: To be updated)

1. Install Rancher and a downstream cluster. 
2. Install monitoring chart on local and downstream cluster.
3. In the downstream cluster, Create a project with 5 namespaces. Create 2000 config maps in each namespace with data of 2KB in size. 
4. In the Rancher UI, navigate to the config maps page of the downstream cluster the first time, and wait until all the config maps are listed. After a few minutes, capture the memory usage of the rancher pods in the local cluster and the cattle-cluster-agent pods in the downstream cluster. 
5. Refresh the ConfigMaps Page multiple times at different intervals. Capture the memory usage data of the Rancher pods in the local cluster and the cattle-cluster-agent pods in the downstream cluster. Verify that the memory usage IS NOT significantly more than usual. 

### **Scenario2: Upgrade from v2.7.3 to v2.7-head** (Test Result: To be updated)

1. Install Rancher v2.7.3 and a downstream cluster. 
2. Install monitoring chart on local and downstream cluster.
3. In the downstream cluster, Create a project with 5 namespaces. Create 2000 config maps in each namespace with data of 2KB in size. 
4. In the Rancher UI, navigate to the config maps page of the downstream cluster the first time, and wait until all the config maps are listed. After a few minutes, capture the memory usage of the rancher pods in the local cluster and the cattle-cluster-agent pods in the downstream cluster. 
5. Refresh the ConfigMaps Page multiple times at different intervals. Capture the memory usage data of the Rancher pods in the local cluster and the cattle-cluster-agent pods in the downstream cluster. Verify that the memory usage IS significantly more than usual. 
6. Upgrade the cluster to v2.7-head.
Refresh the ConfigMaps Page multiple times at different intervals. Capture the memory usage data of the Rancher pods in the local cluster and the cattle-cluster-agent pods in the downstream cluster. Verify that the memory usage IS NOT significantly more than usual.
