### ISSUE TITLE
Description in container & service container details is not showing up properly

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4138]
Version - master 3/25

Steps to Reproduce: 
1.  Create a container with a description
2.  Go to the details page

Results: Notice the description is not in a grid, and the row it's in has a different size line on the right side.
![image](https://cloud.githubusercontent.com/assets/11514927/14054023/05f58422-f293-11e5-9908-bb3480311035.png)

Expected: Should be in grid and the lines should align

**Comment by lvuch** [comment]
https://github.com/rancher/ui/pull/722

**Comment by tfiduccia** [comment]
Version - master 6/13
Verified fixed
