### ISSUE TITLE
Swarm - Not able to download  docker_cli.zip when generating config.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#4139]
Rancher Version:v1.0.0-rc3

Create a swarm environment.
Log into this environment as one of the members of the environment.

Go to Swarm->cli  and do "Generate Config".
docker_cli.zip  is not generated.

**Comment by tfiduccia** [comment]
Sangeetha, can you verify this.  Not sure which authentication you had active.

**Comment by sangeethah** [comment]
Tested with Rancher Version:v1.0.0-rc4

rancher-server has github authentication enabled .
Create a swarm environment.
Log into this environment as one of the members of the environment.

Go to Swarm->cli and do "Generate Config".
docker_cli__<github name>.zip gets downloaded.
