### ISSUE TITLE
[BUG] K3s cluster is stuck in `Updating` state on an etcd snapshot restore

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#41457]
**Rancher Server Setup**
- Rancher version: 2.7-head commit id: `1f014b7`
- Installation option (Docker install/Helm Chart): Helm install
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1 - 1.4.3-rc4 and local cluster on `v1.25.9` k8s version

**Information about the Cluster**
- Kubernetes version: `v1.26.4+k3s1` and `v1.25.9+k3s1`
- Cluster Type (Local/Downstream): 3 etcd and cp (on one node) and 2 worker nodes - Linode Node driver cluster 

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): Admin

**Describe the bug**
K3s cluster is stuck in `Updating` state on an etcd snapshot restore - "Configuring bootstrap node(s) test-k3s-sowmya-master-5ff49b9555-xmfth: waiting for cluster agent to connect"

**To Reproduce**
- Deploy the cluster
- Take a manual snapshot once cluster is active
- Restore from one of the snapshots.
- cluster is stuck in `Updating` state on an etcd snapshot restore.
- One of the etcd/cp nodes is stuck in `Reconciling` state and `Waiting for cluster agent to connect` message on the node. 

**Expected Result**
The cluster restore should go through and cluster must come up Active. 

- `journalctl -u rancher-system-agent` logs:
```
May 08 21:07:44 test-k3s-125-sowmy-pool1-07a52a96-hzgbt rancher-system-agent[6701]: time="2023-05-08T21:07:44Z" level=info msg="[K8s] updated plan secret fleet-default/test-k3s-125-sowmy-bootstrap-template-8r5b2-machine-plan with feedback"
May 08 21:07:45 test-k3s-125-sowmy-pool1-07a52a96-hzgbt rancher-system-agent[6701]: time="2023-05-08T21:07:45Z" level=info msg="[K8s] updated plan secret fleet-default/test-k3s-125-sowmy-bootstrap-template-8r5b2-machine-plan with feedback"
May 08 21:17:20 test-k3s-125-sowmy-pool1-07a52a96-hzgbt rancher-system-agent[6701]: time="2023-05-08T21:17:20Z" level=info msg="[Applyinator] No image provided, creating empty working directory /var/lib/rancher/agent/work/20230508-211720/b47f7b07c38e3ad26c359b30d3>
May 08 21:17:20 test-k3s-125-sowmy-pool1-07a52a96-hzgbt rancher-system-agent[6701]: time="2023-05-08T21:17:20Z" level=info msg="[Applyinator] Running command: sh [-c k3s etcd-snapshot list --etcd-s3=false 2>/dev/null]"
May 08 21:17:20 test-k3s-125-sowmy-pool1-07a52a96-hzgbt rancher-system-agent[6701]: time="2023-05-08T21:17:20Z" level=info msg="[b47f7b07c38e3ad26c359b30d33a46d361feea4a85ccc51abeb58a7ecca9e5b2_0:stdout]: Name                                                       >
May 08 21:17:20 test-k3s-125-sowmy-pool1-07a52a96-hzgbt rancher-system-agent[6701]: time="2023-05-08T21:17:20Z" level=info msg="[b47f7b07c38e3ad26c359b30d33a46d361feea4a85ccc51abeb58a7ecca9e5b2_0:stdout]: on-demand-test-k3s-125-sowmy-pool1-07a52a96-hzgbt-168357983>
May 08 21:17:20 test-k3s-125-sowmy-pool1-07a52a96-hzgbt rancher-system-agent[6701]: time="2023-05-08T21:17:20Z" level=info msg="[b47f7b07c38e3ad26c359b30d33a46d361feea4a85ccc51abeb58a7ecca9e5b2_0:stdout]: on-demand-test-k3s-125-sowmy-pool1-07a52a96-hzgbt-168357983>
May 08 21:17:20 test-k3s-125-sowmy-pool1-07a52a96-hzgbt rancher-system-agent[6701]: time="2023-05-08T21:17:20Z" level=info msg="[b47f7b07c38e3ad26c359b30d33a46d361feea4a85ccc51abeb58a7ecca9e5b2_0:stdout]: on-demand-test-k3s-125-sowmy-pool1-07a52a96-hzgbt-168357986>
May 08 21:17:20 test-k3s-125-sowmy-pool1-07a52a96-hzgbt rancher-system-agent[6701]: time="2023-05-08T21:17:20Z" level=info msg="[b47f7b07c38e3ad26c359b30d33a46d361feea4a85ccc51abeb58a7ecca9e5b2_0:stdout]: on-demand-test-k3s-125-sowmy-pool1-07a52a96-hzgbt-168357999>
May 08 21:17:20 test-k3s-125-sowmy-pool1-07a52a96-hzgbt rancher-system-agent[6701]: time="2023-05-08T21:17:20Z" level=info msg="[Applyinator] Command sh [-c k3s etcd-snapshot list --etcd-s3=false 2>/dev/null] finished with err: <nil> and exit code: 0"
May 08 21:17:20 test-k3s-125-sowmy-pool1-07a52a96-hzgbt rancher-system-agent[6701]: time="2023-05-08T21:17:20Z" level=info msg="[K8s] updated plan secret fleet-default/test-k3s-125-sowmy-bootstrap-template-8r5b2-machine-plan with feedback"
```

---
**Note:**

- On `2.7.3` - tried it 3 times, I was not able to reproduce this.
- On 2.7-head, hit it 2 out of 3 times with the above mentioned cluster config ^

**Comment by snasovich** [comment]
Added `regression` label as it _could_ be a regression based on:
> On `2.7.3` - tried it 3 times, I was not able to reproduce this.
On 2.7-head, hit it 2 out of 3 times with the above mentioned cluster config ^

FYI @Oats87

**Comment by Oats87** [comment]
@sowmyav27 is this on the "same set" of etcd nodes or is it a new set of etcd nodes? i.e. did you delete any of the machines?

I've been noticing some issues when restoring onto brand new nodes that I am trying to figure out how to handle.

**Comment by Oats87** [comment]
I don't believe that this is a regression. It stems from the fact that K3s/RKE2's stock `kube-controller-manager` does not perform taint based eviction for `NotReady` nodes in small < 50 clusters.

**Comment by Oats87** [comment]
https://github.com/rancher/rancher/pull/41459 adds etcd restore logic that proceeds to both clean up stale nodes and pods that need to be restarted

**Comment by Josh-Diamond** [comment]
Ticket #41457 - Test Results - ✅ 
---

Verified with HA Helm Rancher on `v2.7-1ae8ca94691cd2a5a6d6732da4a8670af6206f0f-head`:
1. Fresh install of rancher `v2.7-head`
2. Provision a downstream K3s Linode Node driver cluster (3 etcd/cp nodes, 2 wkr nodes) w/ k8s `v1.26.4+k3s1`
3. Provision a downstream K3s Linode Node driver cluster (3 etcd/cp nodes, 2 wkr nodes) w/ k8s `v1.25.9+k3s1`
4. Once clusters are `active`, take a manual snapshot of each
5. Verified - snapshots successfully captured
6. For each cluster, restore to latest snapshot taken
7. Verified - both clusters successfully restore
8. For each cluster, take a second manual snapshot
9. Verified - both clusters successfully capture second snapshot
10. For each cluster, restore to second manual snapshot taken
11. Verified - both clusters successfully restore
12. Take one final manual snapshot for each cluster
13. Verified - 3rd manual snapshot successfully captured
14. For each cluster, restore to third manual snapshot taken
15. Verified - both clusters successfully restore
16. Verified - snap/restore working as expected for downstream K3s clusters

**Comment by Josh-Diamond** [comment]
In addition to the above posted test results, the same use case was also tested and confirmed using a downstream RKE2 Linode Node driver cluster w/ k8s `v1.26.4+rke2r1`.
