### ISSUE TITLE
[BUG][RKE2] - Reprovisioning all nodes in cluster causes nodes to get stuck in reprovisioning

### ISSUE THREAD

**Issue by thaneunsoo** [rancher/rancher#41458]
**Rancher Server Setup**
- Rancher version: v2.7-head 1f014b7
- Installation option (Docker install/Helm Chart): helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.26.4+rke2r1
- Cluster Type (Local/Downstream): any rke2 node driver cluster

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Admin

**Describe the bug**
When changing a setting that affects all machine pools in a cluster, the nodes got stuck while reprovisioning. The nodes are either stuck in `reconciling` or `deleting`

**To Reproduce**

1. Provision rke2 node driver cluster with 3 etcd 2 cp 3 workers
2. Wait for cluster to become active
3. Edit cluster config
4. Set `hostnameLengthLimit` in cluster config
5. Save
6. Wait for Cluster to come up active

This was also reproducible by changing the image of all the machine pools in step 4.

**Result**
- The cluster is stuck in reprovisioning with nodes stuck in `reconciling` or `deleting`. This doesn't seem to be specific to hostnameLengthLimit as changing the image for the machine pools also reproduced this issue. I don't see any errors in the logs and when I check kubectl, the nodes are in status `Ready`.
- In case where `hostnameLengthLimit` was changed on an Edit Cluster - worker node was stuck and did not reprovison. Etcd and control plane reprovisioning went through

**Expected Result**

All machine pools should be reprovisioned successfully.

**Comment by jakefhyde** [comment]
The root cause of this issue is that the etcd safe removal isn't done for the init etcd node before removal, and causes new etcd nodes to continuously fail leader election due to the ghost nodes. This also prevents the new controlplane and worker nodes from successfully registering because there is no suitable leader node, as well as preventing the old ones from deleting since they will not delete until the new nodes are active.

**Comment by Oats87** [comment]
https://github.com/rancher/rancher/pull/41459 enhances rke bootstrap management of etcd nodes to allow for safe removal of etcd nodes.

**Comment by thaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.7-head 1eb478f
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: rke2

----------

### Testing: ###
Tested this issue with the following steps:
1. Provision rke2 node driver cluster with 3 etcd 2 cp 3 workers
2. Wait for cluster to become active
3. Edit cluster config
4. Set `hostnameLengthLimit` in cluster config
5. Save
6. Wait for Cluster to come up active

**Result** - Pass
Nodes are now being provisioned successfully
![image.png](https://zube.io/files/rancher/ff116c41be06321c9f96e181e0001233-image.png)
