### ISSUE TITLE
Validate and add Docker 20.10.24, 23.0.3, 23.0.4, 23.0.5 & 23.0.6

### ISSUE THREAD

**Issue by doflamingo721** [rancher/rancher#41454]
There has been new releases from docker:
https://docs.docker.com/engine/release-notes/20.10/#201024
https://docs.docker.com/engine/release-notes/23.0/#2303
https://docs.docker.com/engine/release-notes/23.0/#2304
https://docs.docker.com/engine/release-notes/23.0/#2305
https://docs.docker.com/engine/release-notes/23.0/#2306

The following versions will be added:
````
20.10.24
23.0.3
23.0.4
23.0.5
23.0.6
````

Same approach as https://github.com/rancher/rancher/issues/39345 to be followed for implementation and testing.

**Comment by vivek-shilimkar** [comment]
While the docker versions were not released tested the following URLs

- [x]  curl -L https://releases.rancher.com/install-docker-dev/20.10.24.sh 
- [x]  curl -L https://releases.rancher.com/install-docker-dev/23.0.3.sh 
- [x]  curl -L https://releases.rancher.com/install-docker-dev/23.0.4.sh 
- [x]  curl -L https://releases.rancher.com/install-docker-dev/23.0.5.sh 
- [x]  curl -L https://releases.rancher.com/install-docker-dev/23.0.6.sh 

Confirmed the default URL points to the latest: 23.0.6.sh
- [x] curl -L https://releases.rancher.com/install-docker-dev/23.0.sh 

All the URLs are pointing to correct docker version.

**Comment by vivek-shilimkar** [comment]
Tested the docker versions as mentioned above on following OSes.

1. RHEL 8.7
2. centos 8.4

**Comment by vivek-shilimkar** [comment]
Docker install script are working as expected,  hence moving the issue to Release Task. 

Once the docker versions are released the issue can be closed.

**Comment by konvergence** [comment]
Hi all
Could also add the new release docker 24.0
https://docs.docker.com/engine/release-notes/24.0/#2401

**Comment by kinarashah** [comment]
Docker versions are released, 

- [x]  curl -L https://releases.rancher.com/install-docker/20.10.24.sh 
- [x]  curl -L https://releases.rancher.com/install-docker/23.0.3.sh 
- [x]  curl -L https://releases.rancher.com/install-docker/23.0.4.sh 
- [x]  curl -L https://releases.rancher.com/install-docker/23.0.5.sh 
- [x]  curl -L https://releases.rancher.com/install-docker/23.0.6.sh 

Confirmed the default URL for 20.10.sh points to the latest: 20.10.24.sh
- [x] curl -L https://releases.rancher.com/install-docker/20.10.sh 

Confirmed the default URL for 23.0.sh points to the latest: 23.0.6.sh
- [x] curl -L https://releases.rancher.com/install-docker/23.0.sh 

All the URLs are pointing to correct docker version.
