### ISSUE TITLE
创建完成集群后,使用deployment.yml部署pod,但是pod中的服务无法访问公共网络,改为使用主机网络策略可以访问

### ISSUE THREAD

**Issue by social-926425** [rancher/rancher#41462]
*Describe your issue here*

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.4.15` UI: `v2.4.47` |
|Route|`undefined`|

**Comment by orangedeng** [comment]
Please notices that Rancher v2.4.x is no longer in active maintenance. You can try to use a newer version like v2.6/v2.7 to see if it still happens.
The problem itself seems like the network problem, you can try to add more information for your issue like:
- cluster version
- network plugin version
- ping between pods or pod to host

Or maybe you can try to submit your issue in https://forums.rancher.cn so the community in GC can also help you.
