### ISSUE TITLE
Add Renovate bot to CIS-Scanning repo

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#41467]
Add Renovate bot to CIS-Scanning repo. Renovate bot opens PRs to bump versions in order to resolve CVE's. The PR's still need to be approved and merged by hand.

https://docs.renovatebot.com/
https://github.com/renovatebot/renovate

https://github.com/rancher/demo-renovate

**Comment by doflamingo721** [comment]
Added renovate bot configuration to both [cis-operator](https://github.com/rancher/cis-operator) and [security-scan](https://github.com/rancher/security-scan) repositories.
