### ISSUE TITLE
System menu is top for swarm and second for kubernetes

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4147]
Version: v1.0.0-rc3 

Steps to Reproduce:
1.  Create a swarm and kubernetes environments

Results: Notice the System menu for swarm is top level and it's second level for kubernetes

Expected: Have it be same level for both

**Comment by vincent99** [comment]
Fixed in dev2 or so with header redesign

**Comment by tfiduccia** [comment]
Version - master 6/13
Verified fixed
