### ISSUE TITLE
[BUG] Can't see Prometheus Monitoring under Cluster tools or in Charts in Rancher 2.7.3                         

### ISSUE THREAD

**Issue by balajivedagiri** [rancher/rancher#41487]
**Rancher Server Setup**
- Rancher version: 2.7.3
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2 , 1.24.4
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: 1.27.1
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Imported ( boostraped by kubeadm)

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): Admin
  - If custom, define the set of permissions:

**Describe the bug**

`Can't see Prometheus Monitoring under Cluster tools or under charts (not only prometheus/monitoring, can't see CIS, Istio, OPA gatekeeper,etc . Which is visible on other rancher version 2.6)`

**To Reproduce**

> 1. Login to Rancher.
> 2. Click on Downsream cluster
> 3. Click on Cluster tools or Apps => Charts

**Result**

![image](https://github.com/rancher/rancher/assets/42333968/351387e1-d79f-415f-a0d8-d7c98c314c46)

**Expected Result**

![image](https://github.com/rancher/rancher/assets/42333968/4f60633f-5768-42ce-ae19-bc25cf0b6fe0)

**Screenshots**

![image](https://github.com/rancher/rancher/assets/42333968/5a856489-0be0-49e0-bff0-0d74d26e5608)

**Additional context**

**Comment by Eldritch2004** [comment]
Have the same issue with 2.7.2

**Comment by balajivedagiri** [comment]
@Eldritch2004 probably it is not a bug, rancher might be doing a validation against the k8s version. What is the version of your downstream cluster ? . What i noticed is , when i go to local cluster which is on 1.24, it shows all the charts prometheus, opa gatekeeper, cis , etc , same doesn't show when the version is 1.27.

Regards,
Balaji

**Comment by Eldritch2004** [comment]
That's my guess as well. Using 1.27.0 atm, guess it's time to go back to 1.26

**Comment by MKlimuszka** [comment]
Yes. 1.27 is not supported yet. You can see Rancher's official support matrix here: https://www.suse.com/suse-rancher/support-matrix/all-supported-versions/rancher-v2-7-4/
