### ISSUE TITLE
Add Unit Test for "managesystemagent" to ensure safe condition manipulation

### ISSUE THREAD

**Issue by Oats87** [rancher/rancher#41495]
This is an issue to track adding unit tests for the "managesystemagent" controller with the goal of helping to validate resolution of https://github.com/rancher/rancher/issues/41202

I propose that the primary unit test run a mock controlplane object through the `syncSystemUpgradeControllerStatus` object and assert conditions do not change through the function.

**Comment by Oats87** [comment]
Test for this is here: https://github.com/rancher/rancher/blob/release/v2.7/pkg/controllers/capr/managesystemagent/managesystemagentplan_test.go#L18

**Comment by slickwarren** [comment]
QA doesn't have a process for unit tests at this time, so we will close this with no QA for now.
