### ISSUE TITLE
rancher-cis-benchmark  k8s 1.26 chart support

### ISSUE THREAD

**Issue by gunamata** [rancher/rancher#41506]
This issue is to implement the chart changes & perform the testing required to upgrade to k8s 1.26. Please perform below steps.

- [x] Check whether the chart has any references to the below deprecated features of k8s 1.26. You can find information about deprecated APIs here on [Kubernetes Deprecation guide](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-26).

- **flowcontrol.apiserver.k8s.io/v1beta1** API version of **FlowSchema**

- **flowcontrol.apiserver.k8s.io/v1beta1** API version of **PriorityLevelConfiguration**

- **autoscaling/v2beta2** API version of **HorizontalPodAutoscaler** 

- [x] Update `kube-version` annotation in `Chart.yaml`. `catalog.cattle.io/kube-version: '>= 1.23.0-0 < 1.27.0-0'`
**Note:**  If this is an upstream chart and if the upstream chart doesn't support k8s 1.26 then do not update the `kube-version` annotation
- [x] Perform below tests
- Fresh install/uninstall/upgrade/downgrade of the charts on K8s 1.26 provisioned on Rancher. Test the chart functionality
- Provision rancher on k8s 1.25 or lesser
- Install chart on this cluster
- Upgrade this cluster in rancher to k8s 1.26
- Make sure the existing chart and the app is functional after cluster upgrade

**Please note that the k8s 1.26 upgrade is targeted for the [2023-Q2-v2.7x](https://github.com/rancher/rancher/milestone/300 ). Please complete this task by 05/19/2023.**

**Comment by rayandas** [comment]
Tested it on hardened clusters as well. The expected errors are same as we got while scanning on K8s 1.25 cluster. 
RKE1 1.26 Hardened:

![rke1-h-126](https://github.com/rancher/rancher/assets/32811240/e104dedb-5101-4694-9699-8ac74e46f221)

RKE2 1.26 Hardened:

![rke2-h-126](https://github.com/rancher/rancher/assets/32811240/d39b0958-265f-4c8b-9199-ab280b8d39db)

**Comment by vivek-shilimkar** [comment]
Tested the CIS-benchmark chart on non-hardened cluster.

Tested as follows.
1. Fresh install/uninstall/upgrade/downgrade of the chart on K8s v1.26 provisioned on Rancher. Tested the chart functionality.
2. Provisioned k8s v1.25. Installed a chart on a cluster.
    - Made sure chart is working as expected. 
3. Upgraded the cluster in to k8s v1.26.
    - Made sure the existing chart and the app is functional after cluster upgrade

**Comment by vivek-shilimkar** [comment]
Tested the CIS-branchmark chart on hardened cluster.
Following four tests are failing, however, these are expected with 1.23 benchmark version and chart can be released with note.

![Screenshot from 2023-05-19 17-34-52](https://github.com/rancher/rancher/assets/83208989/e52dec11-1435-4e85-bfb5-c61e135cc283)

Hence closing this issue.

**Comment by vivek-shilimkar** [comment]
Issue was reopened to test chart on following type of clusters. Once the testing is done on all the charts issue will be closed.

- [ ]  RKE2
- [ ]  RKE2 hardened
- [ ]  k3s
- [ ]  k3s hardened
- [ ]  custom
- [ ]  imported

**Comment by vivek-shilimkar** [comment]
One of the tests in CIS scan is failing on k3s hardened cluster. [An issue](https://github.com/rancher/rancher/issues/41642) is logged for the same.
