### ISSUE TITLE
Detailed requirements for Fleet supporting k8s 1.26

### ISSUE THREAD

**Issue by gunamata** [rancher/rancher#41502]
This issue is to implement the chart changes & perform the testing required to upgrade to k8s 1.26. Please perform below steps.

- [x] Check whether the chart has any references to the below deprecated features of k8s 1.26. You can find information about deprecated APIs here on [Kubernetes Deprecation guide](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-26).

- **flowcontrol.apiserver.k8s.io/v1beta1** API version of **FlowSchema**

- **flowcontrol.apiserver.k8s.io/v1beta1** API version of **PriorityLevelConfiguration**

- **autoscaling/v2beta2** API version of **HorizontalPodAutoscaler** 

- [x] Update `kube-version` annotation in `Chart.yaml`. `catalog.cattle.io/kube-version: '>= 1.23.0-0 < 1.27.0-0'`
**Note:**  If this is an upstream chart and if the upstream chart doesn't support k8s 1.26 then do not update the `kube-version` annotation
- [ ] Perform below tests
- Fresh install/uninstall/upgrade/downgrade of the charts on K8s 1.26 provisioned on Rancher. Test the chart functionality
- Provision rancher on k8s 1.25 or lesser
- Install chart on this cluster
- Upgrade this cluster in rancher to k8s 1.26
- Make sure the existing chart and the app is functional after cluster upgrade

Please note that the k8s 1.26 upgrade is targeted for the [2023-Q2-v2.7x](https://github.com/rancher/rancher/milestone/300 ). Please complete this task by 05/19/2023.

**Comment by manno** [comment]
We didn't change anything for 1.26 and we do run our test suite on 1.26 
https://github.com/rancher/fleet/actions/runs/4991679263/jobs/8956095066

Notes:

> Fresh install/uninstall/upgrade/downgrade of the charts on K8s 1.26 provisioned on Rancher. Test the chart functionality

Fleet cannot be uninstalled.

> Provision rancher on k8s 1.25 or lesser

> Install chart on this cluster

Fleet is installed automatically by Rancher.

> Upgrade this cluster in rancher to k8s 1.26

How do you upgrade a cluster?

**Comment by kkaempf** [comment]
@gunamata - how to proceed here ? We believe to have done all tests.

**Comment by gunamata** [comment]
@kkaempf - It looks like the fleet chart already has the `catalog.cattle.io/kube-version` annotation updated. As @manno mentioned that you test fleet with k8s 1.26,  no action required for this chart to support k8s 1.26. Thanks.

**Comment by kkaempf** [comment]
Ok, thanks, closing then.
