### ISSUE TITLE
k8s 1.26 support for system-upgrade-controller chart

### ISSUE THREAD

**Issue by gunamata** [rancher/rancher#41511]
This issue is to implement the chart changes & perform the testing required to upgrade to k8s 1.26. Please perform below steps.

- [ ] Check whether the chart has any references to the below deprecated features of k8s 1.26. You can find information about deprecated APIs here on [Kubernetes Deprecation guide](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-26).

- **flowcontrol.apiserver.k8s.io/v1beta1** API version of **FlowSchema**

- **flowcontrol.apiserver.k8s.io/v1beta1** API version of **PriorityLevelConfiguration**

- **autoscaling/v2beta2** API version of **HorizontalPodAutoscaler** 

- [ ] Update `kube-version` annotation in `Chart.yaml`. `catalog.cattle.io/kube-version: '>= 1.23.0-0 < 1.27.0-0'`
**Note:**  If this is an upstream chart and if the upstream chart doesn't support k8s 1.26 then do not update the `kube-version` annotation
- [ ] Perform below tests
- Fresh install/uninstall/upgrade/downgrade of the charts on K8s 1.26 provisioned on Rancher. Test the chart functionality
- Provision rancher on k8s 1.25 or lesser
- Install chart on this cluster
- Upgrade this cluster in rancher to k8s 1.26
- Make sure the existing chart and the app is functional after cluster upgrade

**Please note that the k8s 1.26 upgrade is targeted for the [2023-Q2-v2.7x](https://github.com/rancher/rancher/milestone/300 ). Please complete this task by 05/19/2023.**

**Comment by jiaqiluo** [comment]
TODO specifically for the system-upgrade-controller chart:

- [ ] https://github.com/rancher/system-upgrade-controller
  - [ ] check if any changes are needed in supporting 1.26
  - [ ] check if a new tag is needed 
- [ ] https://github.com/rancher/system-charts/tree/dev-v2.7/charts/rancher-k3s-upgrader
  - [ ] release a new version of the rancher-k3s-upgrader chart 
- [ ] https://github.com/rancher/charts/tree/dev-v2.7/charts/system-upgrade-controller
  - [ ] release a new version of the system-upgrade-controller chart 
- [ ] https://github.com/rancher/rancher/blob/release/v2.7/package/Dockerfile#L55
  - [ ]  Update the SUC version in the Dockerfile

**Comment by jiaqiluo** [comment]
**Problem**
The system-upgrade-controller chart needs to be updated to support k8s 1.26

**Solution**

New versions of the following two charts are released and used in Rancher:
- rancher-k3s-upgrader 0.5.0
- system-upgrade-controller 102.1.0+up0.5.0
 
**QA Testing**

rancher-k3s-upgrader 0.5.0
- on a freshly-installed rancher RC, import a k8s 1.26 RKE2(or K3s) cluster, the app rancher-rke2-upgrade(or rancher-k3s-upgrade) should be installed with chart `rancher-k3s-upgrader` 0.5.0 
- upgrading Rancher from a previous version, the above app should be upgraded from 0.4.0 to 0.5.0 on any existing RKE2/K3s cluster automatically

system-upgrade-controller 102.1.0+up0.5.0
- on freshly-installed Rancher RC, create a k8s 1.26 RKE2/k3s cluster, the chart system-upgrade-controller 102.1.0+up0.5.0 should be installed
- upgrading Rancher from a previous version, the above app should be upgraded to 102.1.0+up0.5.0 on any existing RKE2/K3s cluster automatically

**Comment by Josh-Diamond** [comment]
RC has been cut: https://github.com/rancher/rancher/releases/tag/v2.7.5-rc2

moving `to-test`

**Comment by Josh-Diamond** [comment]
There was an issue w/ `v2.7.5-rc2` which was recently resolved, however we will need a new RC cut before validations will be resumed.  Moving back to `waiting for rancher RC`

**Comment by Josh-Diamond** [comment]
`v2.7.5-rc3` has been cut and is ready for testing.  Moving ticket `to-test`

**Comment by Josh-Diamond** [comment]
Same issue w/ `v2.7.5-rc2` is seen on `v2.7.5-rc3`.  Moving this back to `waiting for rancher RC`, until a valid RC is created to resume testing efforts.

**Comment by Josh-Diamond** [comment]
proceeding w/ validations on `v2.7-head`. taking this up now

**Comment by Josh-Diamond** [comment]
RC is required to proceed w/ testing.  Awaiting new RC to resume testing efforts

**Comment by Josh-Diamond** [comment]
Ticket #41511 - Test Results - ✅ 
---

Verified with HA Helm Rancher on `v2.7-5334be362e291576c8f32b4432762399729832e6-head`:

| Scenario | Test Case | Result |
|---|---|---|
| 1. | Provision a downstream k3s w/ k8s `v1.26` on Rancher `v2.7-head` and observe `system-upgrade-controller` chart version | ✅ |
| 2. | Provision a downstream k3s w/ k8s `v1.25` on Rancher `v2.7.4` => upgrade Rancher to `v2.7-head` and observe `system-upgrade-controller` chart version | ✅ |
| 3. | Import a downstream RKE2 cluster w/ k8s `v1.25` on Rancher `v2.7-head` => upgrade k8s version to `v1.26` and observe `rancher-rke2-upgrader` version | ✅ |
| 4. | Import a downstream RKE2 cluster w/ k3s `v1.24` on Rancher `v2.7.4` => upgrade k8s version to `v1.25` and observe `rancher-rke2-upgrader:v0.4.0` => upgrade Rancher to `v2.7-head` => upgrade k8s to `v1.26` + observe updated `rancher-rke2-upgrader` version | ✅ |

---

Scenario 1 -
1. Fresh install of Rancher `v2.7-head`
2. Provision a downstream RKE2 cluster w/ k8s `v1.26`
3. Once `active`, navigate to `Cluster Explorer > Apps > Installed Apps > All Namespaces` and observe `system-upgrade-controller` version
4. Verified - `system-upgrade-controller:102.1.0+up0.5.0`

---

Scenario 2 -
1. Fresh install of Rancher `v2.7.4`
2. Provision a downstream RKE2 cluster w/ k8s `v1.25`
3. Once `active`, navigate to `Cluster Explorer > Apps > Installed Apps > All Namespaces` and observe `system-upgrade-controller:102.0.0+up0.4.0`
4. Upgrade Rancher to `v2.7-head`
5. Post-upgrade, navigate back to `Cluster Explorer > Apps > Installed Apps > All Namespaces` and observe `system-upgrade-controller:102.1.0+up0.5.0`
6. Verified - `system-upgrade-controller` successfully updates post-rancher server upgrade; as expected

---

Scenario 3 - 
1. Fresh install of Rancher `v2.7-head`
7. Import a downstream RKE2 cluster w/ k8s `v1.25`
8. Once imported and `active`, upgrade cluster's k8s version to `v1.26`
9. Once upgraded and `active`, observe `rancher-rke2-upgrader` version
10. Verified - `rancher-rke2-upgrader:v0.5.0`; as expected

---

Scenario 4 -
1. Fresh install of Rancher `v2.7.4`
2. Import a downstream RKE2 cluster w/ k8s `v1.24`
3. Once imported and `active`, upgrade the k8s version to `v1.25`
4. Once upgraded and `active`, observe `rancher-rke2-upgrader:v0.4.0`
5. Upgrade Rancher to `v2.7-head`
6. Post-rancher upgrade, upgrade cluster's k8s version to `v1.26`
7. Once upgraded and `active`, observe `rancher-rke2-upgrader` version
8. Verified - `rancher-rke2-upgrader:v0.5.0`; as expected
