### ISSUE TITLE
Stack sits in degraded state if service is successful "started-once"

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4151]
Version - v1.0.0-rc1

Steps to Reproduce: 
1.  Create a stack
2.  Add and start a service to the stack that has:
image = hello-world
Auto-restart = Never (started-once)

Results: Stack says degraded
![image](https://cloud.githubusercontent.com/assets/11514927/14059071/f0705acc-f2f2-11e5-8a92-4aa73c605073.png)

Expected: Stack should not be degraded.  Service ran successfully once.  Stack should be Active

**Comment by sangeethah** [comment]
@vincent99 @alena1108 In this case , for stack -  "healthState": "started-once" . This is relating to the UI issue - https://github.com/rancher/rancher/issues/4124

**Comment by tfiduccia** [comment]
Version - master 3.27
Verified fixed
