### ISSUE TITLE
Text overlap seen in "Description" field in "Audit Logs" 

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#4152]
Rancher Version:v1.0.0-rc3

<img width="1123" alt="screen shot 2016-03-26 at 8 29 26 am" src="https://cloud.githubusercontent.com/assets/4266958/14060812/ecfe3e56-f32c-11e5-8b91-a59e120cb1a0.png">

**Comment by lvuch** [comment]
resolved in https://github.com/rancher/ui/pull/578

**Comment by tfiduccia** [comment]
Version - v1.0.1-rc1
Verified fixed
