### ISSUE TITLE
Add RHEL 9 to docker automated tests in install-docker.

### ISSUE THREAD

**Issue by doflamingo721** [rancher/rancher#41526]
We have currently started supporting docker installation on RHEL 9 OS using our docker-install scripts. We need to add RHEL 9 to the list of OSes in [install-docker](https://github.com/rancher/install-docker) automated testing scripts.

**Comment by vivek-shilimkar** [comment]
Docker versions were tested on RHEL9 (`ami-067a8829f9ae24c1c`) by creating downstream cluster with the following URLs

- [x]  curl -L https://releases.rancher.com/install-docker-dev/20.10.24.sh 
- [x]  curl -L https://releases.rancher.com/install-docker-dev/23.0.4.sh 
- [x]  curl -L https://releases.rancher.com/install-docker-dev/23.0.5.sh 
- [x]  curl -L https://releases.rancher.com/install-docker-dev/23.0.6.sh 

Confirmed the default URL for 20.10.sh points to the latest: 20.10.24.sh
- [x] curl -L https://releases.rancher.com/install-docker-dev/20.10.sh 

Confirmed the default URL for 23.0.sh points to the latest: 23.0.6.sh
- [x] curl -L https://releases.rancher.com/install-docker-dev/23.0.sh 

All the URLs are pointing to correct docker version.
