### ISSUE TITLE
[Epic] Refine private registry experience for provisioning Windows clusters and deploying Rancher windows components

### ISSUE THREAD

**Issue by aiyengar2** [rancher/rancher#41535]
This issue tracks a larger story around multiple issues that the Rancher Windows team has identified around Windows in Rancher when a private registry has been configured to contain the Windows container images.

On resolving this epic, the following issues should be addressed:
- https://github.com/rancher/rancher/issues/41533
- https://github.com/rancher/rancher/issues/41534
- https://github.com/rancher/rancher/issues/39582
- https://github.com/rancher/rancher/issues/39609
- https://github.com/rancher/windows/issues/161

**Comment by aiyengar2** [comment]
Given the fact that https://github.com/rancher/rancher/issues/39583 seeks to create a brand new process / CLI tool for mirroring images to a private registry, we should ensure that the new CLI tool (if created) does resolve the above issues as well.

**Comment by aiyengar2** [comment]
One of the common themes in the above issues is that it is a confusing user experience for the Windows host to only create Windows images, not Windows manifests (since it is currently expected the Linux host / Linux scripts create **all** the manifests, including the Windows manifests).

**Comment by snasovich** [comment]
Closing this umbrella issue and will track issues individually.
