### ISSUE TITLE
Windows node stuck at wins.exe on airgapped env

### ISSUE THREAD

**Issue by aiyengar2** [rancher/rancher#41534]
**Rancher Server Setup**
- Rancher version: 2.7.2
- Installation option (Docker install/Helm Chart): N/A
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details: N/A

**Information about the Cluster**
- Kubernetes version: Not known, will update
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): RKE2 Windows (vsphere)

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: N/A

**Describe the bug**

When creating a windows node on airgap env, it does not go over the wins.exe

**To Reproduce**

- set up the private registry with the instructions: https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade/other-installation-methods/air-gapped-helm-cli-install/publish-images
- deploy Rancher using the private registry
- deploy RKE2 cluster with the registry
- add windows worker node

**Result**

Windows node does not get deployed

**Expected Result**

Windows node gets deployed

**Screenshots**

**Additional context**

```
4/12/2023 7:56:46 AM {[Applyinator] Running command: powershell.exe [-File run.ps1]}
4/12/2023 7:56:46 AM {Pulling image <REDACTED>/rancher/system-agent-installer-rke2:v1.24.11-rke2r1}
4/12/2023 7:56:46 AM {Using private registry config file at /etc/rancher/agent/registries.yaml}
4/12/2023 7:56:46 AM {[Applyinator] Extracting image <REDACTED>/rancher/system-agent-installer-rke2:v1.24.11-rke2r1 to directory C:\var\lib\rancher\agent\work\20230412-075646\c08ad05f2bf3a2aaae58d2a55d9393bb8d47e2643a0daf208cd24a8cd89b4fb1_0}
4/12/2023 7:56:46 AM {[Applyinator] Applying one-time instructions for plan with checksum c08ad05f2bf3a2aaae58d2a55d9393bb8d47e2643a0daf208cd24a8cd89b4fb1}
4/12/2023 7:56:14 AM {error executing instruction 0: <nil>}
4/12/2023 7:56:14 AM {[Applyinator] Command powershell.exe [-File run.ps1] finished with err: <nil> and exit code: 4294770688}
4/12/2023 7:56:14 AM {[c08ad05f2bf3a2aaae58d2a55d9393bb8d47e2643a0daf208cd24a8cd89b4fb1_0:stdout]: }
4/12/2023 7:56:14 AM {[c08ad05f2bf3a2aaae58d2a55d9393bb8d47e2643a0daf208cd24a8cd89b4fb1_0:stdout]: Copyright (C) Microsoft Corporation. All rights reserved.}
4/12/2023 7:56:14 AM {[c08ad05f2bf3a2aaae58d2a55d9393bb8d47e2643a0daf208cd24a8cd89b4fb1_0:stderr]: The argument 'run.ps1' to the -File parameter does not exist. Provide the path to an existing '.ps1' file as an argument to the -File parameter.}
4/12/2023 7:56:14 AM {[c08ad05f2bf3a2aaae58d2a55d9393bb8d47e2643a0daf208cd24a8cd89b4fb1_0:stdout]: Windows PowerShell } 
```

SURE-6196

**Comment by slickwarren** [comment]
I believe this is the same issue: https://github.com/rancher/windows/issues/161#issuecomment-1526115371

**Comment by snasovich** [comment]
@slickwarren , moved it "Ready for QA" - hoping we can close it for the same reason as https://github.com/rancher/windows/issues/161#issuecomment-2021591118

**Comment by slickwarren** [comment]
confirmed, this is the same issue and repro steps. Closing this issue as of 2.7.12
