### ISSUE TITLE
[rke1 etcd restore] unable to restore etcd snapshot

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#41547]
**Rancher Server Setup**
- Rancher version: v2.7-head (95edd02)
- Installation option (Docker install/Helm Chart): helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): rke1, 1.4.5
- Proxy/Cert Details: valid letsencrypt certs

**Information about the Cluster**
- Kubernetes version: v1.25.9
- Cluster Type (Local/Downstream): downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): node driver, linode

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: standard user, cluster owner

**Describe the bug**

unable to restore from snapshot
cluster info:
3 etcd
2cp
2worker
docker v23.0 from rancher install script `https://releases.rancher.com/install-docker/23.0.sh`
cluster and fleet customizations (same settings for each):
* one node affinity
  * required, expression: not.this/nodepool = true
* toleration: tolerate/control-plane: `exists` noSchedule (for fleet, tolerate/worker instead of tolerate/control-plane)
* requests:
  * cpu:  500
  * memory: 500
* limits
  * cpu: 750
  * memory: 850

**To Reproduce**

* deploy an rke1 cluster with the following settings 
  * k8s v1.25.9
  * cluster agent customization
    * resource limits and requests
    * add one additional affinity
    * add a toleration
  * fleet agent customization
    * resource limits and requests
    * add one additional affinity
    * add a toleration
 * let the cluster get to an active state -> observe that an etcd snapshot is captured and ready
 * update the cluster
   * remove all cluster and fleet agent customizations that were added in the previous step
 * let the cluster get to an active state -> observe a new etcd snapshot is captured and ready
 * restore the cluster to the first snapshot

**Result**
rancher logs:
```
[WARNING] Failed to set up SSH tunneling for host [<etcd_ip>]: Can't retrieve Docker Info: error during connect: Get "http://%!F(MISSING)var%!F(MISSING)run%!F(MISSING)docker.sock/v1.24/info": can not build dialer to [c-ffztj:m-6qmj5]
```

kubelet logs of etcd node:
```
E0512 18:13:34.861200  465765 summary_sys_containers.go:48] "Failed to get system container stats" err="failed to get cgroup stats for \"/kubepods.slice\": failed to get container info for \"/kubepods.slice\": unknown container \"/kubepods.slice\"" containerName="/kubepods.slice"
E0512 18:13:34.861233  465765 helpers.go:672] "Eviction manager: failed to construct signal" err="system container \"pods\" not found in metrics" signal=allocatableMemory.available
I0512 18:13:34.861245  465765 helpers.go:745] "Eviction manager: no observation found for eviction signal" signal=allocatableMemory.available
E0512 18:13:35.518065  465765 qos_container_manager_linux.go:374] "Failed to update QoS cgroup configuration" err="unable to set unit properties: Unit kubepods.slice not found."
I0512 18:13:35.518145  465765 kubelet.go:1677] "Failed to update QoS cgroups while syncing pod" pod="kube-system/canal-vttgx" err="unable to set unit properties: Unit kubepods.slice not found."
E0512 18:13:35.520796  465765 pod_workers.go:965] "Error syncing pod, skipping" err="failed to ensure that the pod: d1f05746-fd7f-4728-950a-7d2c7c59ff2d cgroups exist and are correctly applied: failed to create container for [kubepods burstable podd1f05746-fd7f-4728-950a-7d2c7c59ff2d] : unable to start unit \"kubepods-burstable-podd1f05746_fd7f_4728_950a_7d2c7c59ff2d.slice\" (properties [{Name:Description Value:\"libcontainer container kubepods-burstable-podd1f05746_fd7f_4728_950a_7d2c7c59ff2d.slice\"} {Name:Wants Value:[\"kubepods-burstable.slice\"]} {Name:MemoryAccounting Value:true} {Name:CPUAccounting Value:true} {Name:IOAccounting Value:true} {Name:TasksAccounting Value:true} {Name:DefaultDependencies Value:false}]): Unit kubepods-burstable.slice not found." pod="kube-system/canal-vttgx" podUID=d1f05746-fd7f-4728-950a-7d2c7c59ff2d
E0512 18:13:36.034088  465765 kubelet.go:2373] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized"
E0512 18:13:39.513336  465765 qos_container_manager_linux.go:374] "Failed to update QoS cgroup configuration" err="unable to set unit properties: Unit kubepods.slice not found."
I0512 18:13:39.513367  465765 kubelet.go:1677] "Failed to update QoS cgroups while syncing pod" pod="cattle-system/cattle-node-agent-5rh5f" err="unable to set unit properties: Unit kubepods.slice not found."
E0512 18:13:39.514607  465765 pod_workers.go:965] "Error syncing pod, skipping" err="failed to ensure that the pod: 0a4636ed-b50e-4ca2-a797-14f6db644295 cgroups exist and are correctly applied: failed to create container for [kubepods besteffort pod0a4636ed-b50e-4ca2-a797-14f6db644295] : unable to start unit \"kubepods-besteffort-pod0a4636ed_b50e_4ca2_a797_14f6db644295.slice\" (properties [{Name:Description Value:\"libcontainer container kubepods-besteffort-pod0a4636ed_b50e_4ca2_a797_14f6db644295.slice\"} {Name:Wants Value:[\"kubepods-besteffort.slice\"]} {Name:MemoryAccounting Value:true} {Name:CPUAccounting Value:true} {Name:IOAccounting Value:true} {Name:TasksAccounting Value:true} {Name:DefaultDependencies Value:false}]): Unit kubepods-besteffort.slice not found." pod="cattle-system/cattle-node-agent-5rh5f" podUID=0a4636ed-b50e-4ca2-a797-14f6db644295
E0512 18:13:40.500851  465765 summary_sys_containers.go:83] "Failed to get system container stats" err="failed to get cgroup stats for \"/kubepods.slice\": failed to get container info for \"/kubepods.slice\": unknown container \"/kubepods.slice\"" containerName="/kubepods.slice"
```

**Expected Result**

cluster should restore without issue

**Screenshots**

**Additional context**

no problem for similar use case on rke2

SURE-5769

**Comment by a-blender** [comment]
@slickwarren I see the kubelet logs are showing the container runtime network and cni config not ready. Rancher will sometimes reconcile this, did an etcd snapshot ever work for you on rke1? Even if you tried a second time? Have you ever seen this issue on previous rancher versions?

**Comment by slickwarren** [comment]
* An etcd snapshot + restore on 1 node each role and no cluster / fleet agent changes seemed to work fine
* I have not seen this on previous versions
* I no longer have access to this setup

**Comment by a-blender** [comment]
@slickwarren Gotcha! I am also unable to repro the issue you saw above on an rke node driver cluster on EC2 nodes. I didn't see any abnormal issues at all.

Repro steps
* On rainbow v2.7-head cluster (c842598), run 2 cp/3 etcd/2 worker rke node driver cluster on EC2 nodes with agent customization
* Take a snapshot
* Remove agent customization
* Restore cluster to earlier snapshot

Snapshot taken successfully.
![image](https://github.com/rancher/rancher/assets/12955547/0fdde286-2f00-407b-bfd0-ffd48c91c259)

Rancher logs
```
2023/05/15 22:06:56 [INFO] [etcd] Finished saving snapshot [c-hpj8c-ml-ss2x5_2023-05-15T22:06:35Z] on all etcd hosts
2023/05/15 22:06:56 [INFO] Finished saving/uploading snapshot [c-hpj8c-ml-ss2x5_2023-05-15T22:06:35Z] on all etcd hosts
```

I removed agent customization from cluster and attempted to restore to earlier snapshot.
![1337621f8c91c917a40f82b49afcccdb.png](:/3e709aa3115948e081d14ecb818abc5d)

rancher UI
![af4a83f1a0bd76df833122025b0c9c35.png](:/0f9d6ad324fc487f91627db2e15566e0)

Logs - look as expected
```
2023/05/15 22:08:20 [INFO] Creating system token for u-ebv2p2gthq, token: agent-u-ebv2p2gthq
2023/05/15 22:13:21 [INFO] clusterDeploy: redeployAgent: redeploy Rancher agents due to agent customization mismatch for [c-hpj8c], was [&{[] nil nil}] and will be [&{[{tolerate/control-plane Exists  NoSchedule <nil>}] &Affinity{NodeAffinity:&NodeAffinity{RequiredDuringSchedulingIgnoredDuringExecution:&NodeSelector{NodeSelectorTerms:[]NodeSelectorTerm{NodeSelectorTerm{MatchExpressions:[]NodeSelectorRequirement{NodeSelectorRequirement{Key:not.this/nodepool,Operator:NotIn,Values:[true],},},MatchFields:[]NodeSelectorRequirement{},},},},PreferredDuringSchedulingIgnoredDuringExecution:[]PreferredSchedulingTerm{},},PodAffinity:&PodAffinity{RequiredDuringSchedulingIgnoredDuringExecution:[]PodAffinityTerm{},PreferredDuringSchedulingIgnoredDuringExecution:[]WeightedPodAffinityTerm{},},PodAntiAffinity:&PodAntiAffinity{RequiredDuringSchedulingIgnoredDuringExecution:[]PodAffinityTerm{},PreferredDuringSchedulingIgnoredDuringExecution:[]WeightedPodAffinityTerm{},},} &ResourceRequirements{Limits:ResourceList{cpu: {{750 -3} {<nil>} 750m DecimalSI},memory: {{891289600 0} {<nil>} 850Mi BinarySI},},Requests:ResourceList{cpu: {{500 -3} {<nil>} 500m DecimalSI},memory: {{524288000 0} {<nil>} 500Mi BinarySI},},}}]
```

UI looks correct as well. Unable to repro.

**Comment by slickwarren** [comment]
I am still able to reproduce this - v2.7-head (b04c942)
This time, i was able to repro by deploying a cluster with no cluster / fleet agent customizations, updating it to include some customizations, then restoring to the original.
@jakefhyde was also able to reproduce it

**Comment by a-blender** [comment]
I will try the reverse and hopefully will be able to repro

**Comment by a-blender** [comment]
@jakefhyde was able to reproduce this issue on rke and confirmed that it's the same root cause as SURE-5769 and that agent customization is unrelated.

**Comment by snasovich** [comment]
This issue has been around for a while (at least since 2.6.6) and will require a rather deep fix that we're not comfortable doing for the Q2 release given the release timeline due to regression concerns.
@jakefhyde to post notes on workaround to release note for Q2.

**Comment by jakefhyde** [comment]
## Workaround

When the cluster gets into this state, containers from previous pods will become orphaned on downstream nodes. In order to fix this, a `docker restart kubelet` should be run on each affected worker node, which will trigger the orphaned containers to be removed.

**Comment by Sahota1225** [comment]
After having the discussion with @jiaqiluo, we are removing the release blocker label because this issue is not a release blocker.

**Comment by jiaqiluo** [comment]
## Workaround Method 2 

### Goal
Restart the kubelet container on affected worker nodes (see the Caveat below before applying) 

### Approach

We can trigger the recreation of the kubelet container by modifying kubelet's configuration. We can do so by editing the cluster as YAML in Rancher UI.

### Steps:
- on the Cluster Management page,  find and choose "Edit config" on the target cluster 
- in the "Cluster Options" section, choose "Edit as YAML" 
- add/remove/change any value under the etra_args or extra_env section under `rancher_kubernetes_engine_config.services.kubelet`
- save the change to trigger the cluster to upgrade 
- wait for the cluster to finish the upgrade and become active 

**Example values**:
```
rancher_kubernetes_engine_config:
  services:
    kubelet:
      extra_env:
        - env1=val1
      extra_args:
        v: 4
      fail_swap_on: false
      generate_serving_certificate: false
```

### Results:

The kubelet containers on all nodes are recreated to apply the new configuration. 


### Caveats:

1. This approach results in the recreation of the kubelet container on all nodes, not only worker nodes. Rancher handles the process to ensure zero downtime, just like for any other normal editing or updating of the cluster. 
2. If you prefer to use the `extra_args` blob, be sure both the arg(ie. option) and its value are valid. Please refer to the K8s documentation for available options: https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/

**Comment by jiaqiluo** [comment]
### Root cause

The `kubelet` container does not restart on the `worker-only `node of the RKE1 node-driver cluster after performing an etcd snapshot restore, which causes chaos and unexpected behaviors because of the stale cache inside the container.
  
### What was fixed, or what changes have occurred

A new environment variable, `CATTLE_ETCD_RESTORE_GENERATION=<some-value>`, is added or updated in the node plan for the kubelet process (container) when a restore is performed. This allows the node agent to detect a change in the node plan and redeploy the kubelet container with the new plan during the upgrading process after the etcd restore is finished.

The kubelet containers on the etcd and control plane node are restated by RKE during the restore process.

### Areas or cases that should be tested

- etcd snapshot restore on RKE1 node-driver clusters
-  kubelet-related configurations update on RKE1 node-driver clusters

### What areas could experience regressions?

- etcd snapshot restore - Generally speaking, the fix affects only the etcd snapshot restoring; I do not think and did not see any regression during my development and dev-validation. but I still suggest QA to perform the regression validation.
- regular cluster editing & upgrading - the extra env should be preserved if it was added
  
### Are the repro steps accurate/minimal?

yes.

**Comment by jiaqiluo** [comment]
can be validated in the latest v2.8-head

**Comment by susesgartner** [comment]
Automation note: This should be covered under some recent changes to the automation framework.

**Comment by susesgartner** [comment]
Ticket #41547 - Test Results - ✅ 
---
 
| Scenario | Test Case | Result |
|---|---|---|
| 1. | Snap restore | PASS |

---
Verified with HA Helm on Rancher `v2.8-head`:
---
 
Scenario 1: Snap restore
---
1. Create a rke1 9 node downstream cluster
2. Take a snapshot
3. Restore a snapshot
4. Repeat steps 2-3 5 times
 
Results: All snapshots successfully restored
