### ISSUE TITLE
Cannot upgrade services with Sidekicks (after upgrade)

### ISSUE THREAD

**Issue by Slamper** [rancher/rancher#4154]
Rancher Version: v1.0.0-rc4 (NOTE: upgraded from v0.63.1)
Docker Version: Docker version 1.10.1, build 9e83765
OS: RancherOS v0.4.3

Steps to Reproduce: 
1. Create a Service with a Sidekick in v0.63.1 (in this case the prometheus Service from the Community Catalog)
2. Upgrade to v1.0.0-rc4
3. Try to upgrade the Service from the UI.

I don't know whether the upgrade causes these issues or this also happens with a clean install of rc4.

When creating services with sidekicks from the catalog in 1.0.0-rc4 eg. the Prometheus Stack containers with Sidekicks can still not be upgraded.

Results: 
Empty UI page (except the header) shows up and the following error appears in the debug console:
```parse-healthcheck.js:7 Uncaught TypeError: Cannot read property 'trim' of undefined```

Expected:
Should show the normal Upgrade UI page.

**Comment by vincent99** [comment]
Thanks, error parsing an empty requestLine (for a TCP healthcheck).  Will be in next RC

**Comment by tfiduccia** [comment]
Version - master 3.27
Verified fixed
