### ISSUE TITLE
Rancher V3 Api Documentation archived?

### ISSUE THREAD

**Issue by Erodotos** [rancher/rancher#41558]
I am trying to find some useful documentation about Rancher API, but once I found this : https://github.com/rancher/api-spec/blob/master/specification.md, I noticed that this was archived. Which is the proper Rancher API documentation to use?

**Comment by stefanlasiewski** [comment]
(I'm a fellow user, not affiliated with Rancher).

I am also looking for more API documentation. If I recall correctly, https://rancher.com/docs/ or another site did have a fair amount of documentation a few years ago. However, I also cannot find it any more. I suspect the existing documentation was had suffered from bit rot and was no longer maintained.

See this recent issue https://github.com/rancher/rancher-docs/issues/583 . Looks like someone is considering new docs for the API, but there's no timeline or commitment at the moment. Please add a comment or a vote there.
