### ISSUE TITLE
Switching to Swarm or Kubernetes environment flashes the Waiting page

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4155]
Version - v1.0.0-rc4

Steps to Reproduce: 
1.  Set up a Swarm or Kubernetes environment
2.  Add a host and wait until it's completely setup
3.  Using drop-down switch to default environment
4.  Now switch back to swarm or kubernetes environment

Results: the waiting page flashes before you are taken to project/services page

Expected: Waiting page should not flash

**Comment by vincent99** [comment]
This was changed with header redesign

**Comment by tfiduccia** [comment]
Version - master 6/9
Verified fixed
