### ISSUE TITLE
[cli]Is v0.6.14 supported on m1 mac?

### ISSUE THREAD

**Issue by Qingkongji** [rancher/rancher#41555]
I use m1 macbook air.
When I execute "rancher env ls", the result is "zsh: segmentation fault".

**Comment by BodhiHu** [comment]
My M1 MacBook is running successfully with rancher version of 2.7.1 inside docker of single-node:

https://ranchermanager.docs.rancher.com/pages-for-subheaders/rancher-on-a-single-node-with-docker

**Comment by Qingkongji** [comment]
@BodhiHu I want to install the CLI to connect to remote Rancher. Rancher is using version 1.6.30 and the corresponding Rancher CLI version is 0.6.14. However, it throws an error on m1 Mac.
