### ISSUE TITLE
[CAPR] Keep any node that either has a matching machine UID label or matching machine status NodeRef during etcd restore

### ISSUE THREAD

**Issue by Oats87** [rancher/rancher#41563]
When performing an etcd restore, it is important that we keep nodes that either have a matching machine UID label, or a matching machine status noderef.

There are very few edge cases where we can run into the situation where we need to "fallback" between the two, but the primary edge cases that I can think of are:
* Restoring an etcd snapshot that was taken on a different Rancher installation (i.e. a Rancher installation that was migrated from). In this case, the etcd snapshot nodes will have machine UIDs that do not match the existing Rancher installation, and while we have a "InitialRestartCluster" phase that hopefully will reconcile the label, this is not necessarily a reliable method to ensure that the machine UID label is up to date.
* Restoring a snapshot that contains a node that has not been backpopulated by the CAPI machine controllers yet -- this is a very low likelihood case, and should realistically not affect much but it is still better to keep the node around.

**Comment by markusewalker** [comment]
**QA TEST PLAN**

**Scenarios**
|Scenario|Test Case|
|---|---|
|1|Provision a downstream RKE1 node driver cluster, create an etcd snapshot of the cluster, migrate Rancher to a new server, restore the downstream cluster and validate that it restores properly|
|2|Provision a downstream RKE2 node driver cluster, create an etcd snapshot of the cluster, migrate Rancher to a new server, restore the downstream cluster and validate that it restores properly|
|3|As a standard user, provision a downstream K3S custom cluster (1 etcd, 1 cp, 1 worker), create an etcd snapshot, replace the etcd node, restore the snapshot and validate that it restores properly|
|4|As a standard user, provision a downstream K3S custom cluster (1 etcd/cp, 1 worker), create an etcd snapshot, replace the etcd/cp node, restore the snapshot and validate that it restores properly|

**Comment by markusewalker** [comment]
Tested this against `v2.7-head` https://github.com/rancher/rancher/commit/6ce75a0b57ad9e88cf135254a9b3b40082788eb6.

**ENVIRONMENT DETAILS**
- Rancher install: Docker
- Rancher version: `v2.7-head` https://github.com/rancher/rancher/commit/6ce75a0b57ad9e88cf135254a9b3b40082788eb6
- Browser: Chrome

**TEST RESULT**
|Scenario|Test Case|Result
|---|---|---|
|1|Provision a downstream RKE2 node driver cluster, create an etcd snapshot of the cluster, backup/restore Rancher on the same server, restore the downstream cluster and validate that it restores properly|:white_check_mark:|
|2|Provision a downstream RKE2 node driver cluster, create an etcd snapshot of the cluster, migrate Rancher to a new server, restore the downstream cluster and validate that it restores properly|:x:|

**VALIDATION STEPS**

**Scenario 1**
1. As a standard user, provisioned a downstream RKE2 `v1.26.4+rke2r1` node driver cluster.
     - Validated that the cluster and nodes came up as `Active` in Cluster Management and Cluster Explorer.
2. Created an etcd snapshot of this downstream cluster.
3. In the local cluster, installed the Rancher Backup chart.
4. Created a Rancher backup to my pre-defined AWS S3 bucket.
     - Validated that my backup properly appears in my S3 bucket in the S3 Management Console.
5. Successfully restored the Rancher backup on my same server.
6. Successfully restored my downstream cluster's snapshot using options cluster configuration, Kubernetes version and etcd.
     - Cluster and nodes are in a state of `Active` in Cluster Management and Cluster Explorer.
_____________

**Scenario 2**
1. Repeated scenario 1 steps 1-4.
2. On a new client machine, followed the Rancher migration documentation on a new server that will act as my new Rancher server.
3. Navigated to the migrated Rancher in a browser and validated the following:
     - Rancher successfully stood up.
     - Rancher restore successfully completed:
![image](https://github.com/rancher/rancher/assets/52591819/99a732a2-b3a0-483c-8d8c-8c2c086dc19e) 
     - My provisioned downstream RKE2 cluster migrated to the new Rancher server.
4. While my downstream RKE2 cluster migrated over, it is not `Active`; only the etcd node is stuck in a `Reconciling` state.
     - This is an issue as I expect the cluster to come up as `Active` after I performed this migration.

In terms of this issue, the migration does actually take place and I am not seeing the issue described in scenario two. However, I have marked it as failure as I expected the cluster to come up as `Active` after I migrated. Seeing as it did not pass that test step, I marked the test scenario as a failure.

If this is a separate issue that needs a separate issue, please let me know. For now, I will be reopening this issue.

**Comment by markusewalker** [comment]
Spoke offline with the team of this. Scenario 2 was found to be an unsupported workflow as we more so are looking to migrate the Rancher cluster and not the actual Rancher server URL. Please see below with the updated test results:

**ENVIRONMENT DETAILS**
- Rancher install: Docker
- Rancher version: `v2.7-head` https://github.com/rancher/rancher/commit/fbca7c34e5aeae36b85d8b0e9af12a2f6f13e0ea
- Browser: Chrome

**TEST RESULT**
|Scenario|Test Case|Result
|---|---|---|
|1|Provision a downstream RKE2 node driver cluster, create an etcd snapshot of the cluster, backup/restore Rancher on the same server, restore the downstream cluster and validate that it restores properly|:white_check_mark:|
|2|Provision a downstream RKE2 node driver cluster, create an etcd snapshot of the cluster, migrate Rancher to a new cluster, restore the downstream cluster and validate that it restores properly|:white_check_mark:|

**VALIDATION STEPS**

**Scenario 1**
1. As a standard user, provisioned a downstream RKE2 `v1.26.4+rke2r1` node driver cluster.
     - Validated that the cluster and nodes came up as `Active` in Cluster Management and Cluster Explorer.
2. Created an etcd snapshot of this downstream cluster.
3. In the local cluster, installed the Rancher Backup chart.
4. Created a Rancher backup to my pre-defined AWS S3 bucket.
     - Validated that my backup properly appears in my S3 bucket in the S3 Management Console.
5. Successfully restored the Rancher backup on my same server.
6. Successfully restored my downstream cluster's snapshot using options cluster configuration, Kubernetes version and etcd.
     - Cluster and nodes are in a state of `Active` in Cluster Management and Cluster Explorer.
_____________

**Scenario 2**
1. Repeated scenario 1 steps 1-4.
2. On a new client machine, followed the Rancher migration [documentation](https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/backup-restore-and-disaster-recovery/migrate-rancher-to-new-cluster) and migrated Rancher to a new cluster.
3. Validated that my same Rancher server URL is accessible with the cluster migration.
4. Performed a restore operation using my created backup; this was successful.
5. Successfully restored my downstream cluster's snapshot using options cluster configuration, Kubernetes version and etcd.
     - Cluster and nodes are in a state of `Active` in Cluster Management and Cluster Explorer.
