### ISSUE TITLE
Can't create environment API keys for AD user

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4157]
Version: v1.0.0-rc4

Steps to Reproduce: 
1.  Authenticate using Active Directory
2.  Log in as another user in separate browser
3.  Go to API screen
4.  Try to create an Environment API key

Results: Keeps getting added to the Account API key

Expected: Should be added as an Environment API key

**Comment by vincent99** [comment]
Actual issue is it works for admin accounts but not for non-admin.

**Comment by tfiduccia** [comment]
Version - master 3.27
Verified fixed
