### ISSUE TITLE
[intermittent] when adding a cluster / fleet agent toleration, sometimes there is an appended toleration that was used in a previously provisioned cluster, but was not added by the user to this cluster

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#41571]
**Setup**
- Rancher version: v2.7-head (95edd02)
- Rancher UI Extensions: n/a
- Browser type & version: chrome

**Describe the bug**

In some cases, there is an appended toleration that is added to a new cluster. This toleration could be from an existing cluster's spec. 

**To Reproduce**

**CURRENTLY NOT FINDING CONSISTENTLY REPRODUCIBLE STEPS** 
* provision a cluster (rke1 or rke2)
  * add some cluster agent customizations
* provision a second cluster
  * enter a toleration for cluster or fleet agent customization
    * fill in all text values first, then update from `=` to `Exists`
* wait for the cluster to get to an active state

**Result**
* check the cluster / fleet agent pod, and observe that 2 tolerations were applied instead of only 1

**Expected Result**

only 1 toleration should have existed

**Screenshots**
<img width="1000" alt="Screen Shot 2023-05-12 at 9 19 32 AM" src="https://github.com/rancher/dashboard/assets/16691014/55a7dc51-f0b0-493e-aaff-ad7c99b4d0b6">

<img width="466" alt="Screen Shot 2023-05-12 at 9 36 46 AM" src="https://github.com/rancher/dashboard/assets/16691014/98678670-95dc-4c7d-8fb4-ba09efdc564c">

**Additional context**

has happened 1x on rke1 and rke2

**Comment by slickwarren** [comment]
note: this can also happen on an upgrade scenario -> removing all cluster agent customizations can result in the toleration removed from the spec, but still applied to the cluster agent deployment but without an `operator`

**Comment by slickwarren** [comment]
for the operator missing, which I think is related to this problem, the description specifies 
```
// Operator represents a key's relationship to the value.
	// Valid operators are Exists and Equal. Defaults to Equal.
	// Exists is equivalent to wildcard for value, so that a pod can
	// tolerate all taints of a particular category.
	// +optional
	Operator TolerationOperator
```
so I'm wondering if there's some weird issue happening whenever the cluster is updated and sees an `=` operator, tries to omit it?

**Comment by a-blender** [comment]
Briefly discussed with @slickwarren. User defined tolerations getting updated in the ui should update the user defined list not just append the latest updates. This looks like a backend bug that was missed. Will put in a PR later/tomorrow to fix this when I have the chance.

**Comment by slickwarren** [comment]
after more discussion, this is expected behavior. Taints on the CP node are automatically added as a toleration. This has been the behavior for quite some time.

**Comment by a-blender** [comment]
Correct, I agree.

Just for a bit more context, the cluster agent deployment manifest has always added tolerations based on cp node taints https://github.com/rancher/rancher/blob/df199040cb66602bf1b10c5cfcdaffd05ad85124/pkg/systemtemplate/template.go#L177-L180 if they are present. If they are not, hardcoded default tolerations are added. Agent customization tolerations that are defined by the user are appended to this list.
