### ISSUE TITLE
[CAPR] CAPR should deliver important instructions with idempotence

### ISSUE THREAD

**Issue by Oats87** [rancher/rancher#41587]
**Rancher Server Setup**
- Rancher version: v2.7-head

**Describe the bug**
We have seen on-and-off transient failures of RKE2 and K3s-based integration tests in CI.

It appears that there are important instructions that are getting executed multiple times that should not be executed multiple times. The factors that influence the execution of these instructions are generally out of our control -- therefore we should ensure idempotence when executing instructions. 

**To Reproduce**
Difficult to reproduce as this is a race condition in CI, but, just run the v2prov integration CI tests for `Test_Operation_Custom_EncryptionKeyRotation` and/or `Test_Operation_MP_EncryptionKeyRotation` a bunch.

**Result**
Integration tests are flaky.

**Expected Result**
Integration tests shouldn't fail and they should not fail.

**Screenshots**

**Additional context**
Example run where this failed: https://drone-publish.rancher.io/rancher/rancher/9705/4/2

**Comment by jakefhyde** [comment]
## Test Results - :heavy_check_mark: 
Verified on HA install on v2.7-head `fbca7c3`
### Scenario 1 (apiserver is not reachable) :heavy_check_mark: 
- Blocked traffic to apiserver on downstream host
- `system-agent` reconciles idempotent etcd snapshot restore instruction, then stops reconciling once failing to update secret
- Unblocking traffic, the plan is reconciled, but etcd is not restored a second time if the first time was successful
