### ISSUE TITLE
[BUG] Ingress related tests fails in post upgrade checks on k3s v1.26 after upgrade from v1.25.

### ISSUE THREAD

**Issue by vivek-shilimkar** [rancher/rancher#41582]
**Rancher Server Setup**
- Rancher version: v2.7.5-rc1
- Installation option (Docker install/Helm Chart): Docker
- Proxy/Cert Details: 

**Information about the Cluster**
- Kubernetes version: v1.25
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Amazon EC2

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Admin

**Describe the bug**

Ingress related tests fails in post upgrade checks on k3s v1.26 after upgrade from v1.25.

**To Reproduce**

- Provision 3 etcd, 2 cp, 3 worker nodes K3s v1.25 cluster - custom cluster
- Run pre upgrade checks
- Upgrade to 1.26 K3s version
- Verify all nodes have k8s version upgraded to 1.26
- Run post upgrade checks on the downstream clusters.

**Result**
Ingress related tests fails in post upgrade checks.

traefik pod shows error similar to following.
`2023-05-17T13:53:48.961454111Z time="2023-05-17T13:53:48Z" level=error msg="Cannot create service: endpoints not found" namespace=mystep2-ns1 serviceName=ingress-7e16fcb620599d283b7a2399e2880336 servicePort="&ServiceBackendPort{Name:,Number:80,}" providerName=kubernetes ingress=mystep2-testingress2`

**Expected Result**
All the post upgrade checks should pass.

**Additional context**
This was observed while testing K8s v1.26 support.

**Comment by kinarashah** [comment]
@vivek-shilimkar Looks like you're creating ingress from old UI, is that the right assumption? Not that it matters but just to keep things simpler, I created ingress using new UI and could still reproduce the issue but I no longer see the error in the traefik pods. 

What I am seeing is that `http://ing.default.xx.xx.xx.xx.sslip.io/name.html` continues to work from the host itself, but it fails from outside - `unable to connect to port 80 curl: (7) Failed to connect to [ing.default.xx.xx.xx.xx.slip.io](http://ing.default.xx.xx.xx.xx.slip.io/) port 80: Couldn't connect to server`. Restarting traefik service pods `svclb-traefik` fixes the issue. 

@rancher-max also tried this on standalone k3s cluster and reproduced the issue, so going open a new issue under k3s-io/ instead.

**Comment by snasovich** [comment]
Looks like this will be addressed by new k3s versions to be introduced as part of https://github.com/rancher/rancher/issues/41615, adding `release-note` label to ensure we document a known issue with previously released versions.

**Comment by Sahota1225** [comment]
Since K3s team released May patch, moving this issue to test

**Comment by kinarashah** [comment]
New k3s versions are released, but yet to be available via KDM so can be tested after https://github.com/rancher/kontainer-driver-metadata/pull/1137 is merged.

**Comment by sowmyav27** [comment]
Moving to blocked unti this PR is merged - https://github.com/rancher/kontainer-driver-metadata/pull/1137

**Comment by Sahota1225** [comment]
since PR is merged https://github.com/rancher/kontainer-driver-metadata/pull/1137 moving the issue to test

**Comment by vivek-shilimkar** [comment]
Tested the issue on newly released k3s **v1.26.5+k3s1**.

**Test steps**
- Provision 3 etcd, 2 cp, 3 worker nodes K3s v1.25 cluster - custom cluster
- Run pre upgrade checks
- Upgrade to 1.26 K3s version
- Verify all nodes have k8s version upgraded to 1.26
- Run post upgrade checks on the downstream clusters.

Post upgrade checks are passing. Hence, closing this issue.

**Comment by martyav** [comment]
@vivek-shilimkar Could you describe the issue from a customer perspective? This one requires a release note and I'm not sure how to express the problem in a way that makes it pertinent to a customer attempting to upgrade.
