### ISSUE TITLE
[BUG] rke1 cluster agent customization is not restored when during a rancher (local cluster) restore

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#41589]
**Rancher Server Setup**
- Rancher version: v2.7-head (ece9134)
- Installation option (Docker install/Helm Chart): helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): rke1, 1.4.5
- Proxy/Cert Details: valid certs

**Information about the Cluster**
- Kubernetes version: v1.25.9
- Cluster Type (Local/Downstream): downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): amazon node driver

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: administrator (for local cluster restore) - cluster created by standard user, cluster owner

**Describe the bug**

when restoring local cluster with a downstream cluster that had removed rke1 cluster agent customization back to a version that did have cluster agent customization, the customization is available in the cluster spec, however the cluster-agent did not redeploy 

**To Reproduce**

* deploy rancher and enable the `backup and restore` chart in the local cluster
  * tested with s3 store
* deploy a downstream cluster with cluster agent customization enabled for tolerations, resources, and affinity
  * verify that customization is applied in the cluster agent deployment
* backup the local cluster (backup 1)
* upgrade the downstream cluster to remove cluster agent customization
  * verify that the customization is removed in the cluster agent deployment
* backup the local cluster (backup 2)
* follow the restore procedure for the local cluster using backup 1

**Result**
the customization is available in the cluster spec, however the cluster-agent did not redeploy and thus does not have the old cluster agent customizations

**Expected Result**

cluster agent should redeploy with the updated spec

**Screenshots**

**Additional context**

not an issue for rke2 downstream clusters for cluster / fleet agent
not an issue for rke1 fleet agent customization

**Comment by a-blender** [comment]
I was able to repro this on `v2.7-head.`

Repro steps

* deploy rancher
* create new AWS s3 bucket, install the backup and restore chart in the local cluster
* deploy a single node rke cluster with cluster agent customization enabled for tolerations, resources, and affinity
* verify that customization is applied in the cluster agent deployment
* backup the local cluster (backup 1)
* remove cluster agent customization
* verify that the customization is removed in the cluster agent deployment
* backup the local cluster (backup 2)
* follow the restore procedure for the local cluster using backup 1

Backups 1 and 2
<img width="1520" alt="image" src="https://github.com/rancher/rancher/assets/12955547/b68d37e9-aa23-43d2-842f-346c0de60a5d">

Restore to backup 1 (which has cluster agent customization)
<img width="1138" alt="image" src="https://github.com/rancher/rancher/assets/12955547/bc51a10d-5c87-4a51-bd8e-16985fd094d7">

Fields are present on cluster spec
<img width="1141" alt="image" src="https://github.com/rancher/rancher/assets/12955547/0331acee-53fa-4ae6-a4db-656ed93d7510">

But defaults are still present on cluster agent, it was not redeployed.

`redeployAgent` should see the spec update and return true to redeploy the agent, but either it's returning false for some reason or it's viewing an outdated spec object where it still sees the default values set pre-restore. Will debug a local instance to find out.

**Comment by snasovich** [comment]
Following offline discussions the current plan for addressing this issue is to force `cattle-cluster-agent` redeployment on all downstream clusters as part of restore by setting `io.cattle.agent.force.deploy` annotation on all management cluster objects restored. The fix will be in https://github.com/rancher/backup-restore-operator, so Team 3 and @eliyamlevy are getting involved.

**Comment by slickwarren** [comment]
tested the following on v2.7-head (6ce75a0) and backup&restore v102.0.1+up3.1.1-rc9:
* install backup and restore app on local cluster
* create rke1 and rke2 with all parameters customized for cluster and fleet agents
  * eks cluster has a bug where customizations can't be removed in an upgrade, so tested the inverse for this ticket (deploy a fresh eks cluster with no agent customizations for this step)
* create a backup after the clusters are active and after verifying that the agents have the correct customizations applied
* upgrade each cluster
  * remove all agent customizations (for eks, add all agent customizations)
* verify that each cluster has removed the agent customizations
* backup the local cluster again
* restore the local cluster to the initial backup
* verify that rke1 agent customization is restored -- pass
* verify that rke2 agent customization is restored -- pass
* verify that eks agent customization is removed -- pass
  * will separately test eks after [this bug is fixed](https://github.com/rancher/dashboard/issues/8887)
