### ISSUE TITLE
[BUG] Sorry Cypress doesn't show E2E test run videos

### ISSUE THREAD

**Issue by Shavindra** [rancher/rancher#41583]
**Describe the bug**
Videos of E2E runs are not available to view

/instance/60b5e400-7c30-400a-a233-a478d7dcb860/test/r11

**To Reproduce**
- Create a PR / Trigger a e2e run 
- Click on a spec
- Click on "Recorded Video" button under Tests
- e.g. /instance/6bb3b834-05ef-4b93-880f-87baa5d2517e/others/RECORDED_VIDEO

**Result**

Videos are not uploaded and available

**Expected Result**
Test run videos should be available to view

**Additional context**
Could be a permission issue?
![image](https://github.com/rancher/rancher/assets/1387263/c49e8436-b436-42a5-a413-d0be174eae4d)

CICD logs show
- Dashboard github actions runs shows this error even after successful e2e test run
- https://github.com/rancher/dashboard/actions/runs/4994198048/jobs/8944416957
`Failed Uploading (1/1) /home/runner/work/dashboard/dashboard/cypress/videos/setup/rancher-setup.spec.ts.mp4`

**Comment by cnotv** [comment]
Closed as duplicated https://github.com/rancher/dashboard/issues/8904
