### ISSUE TITLE
[2.8] Images of Apps Charts provoke a slow functioning of Apps on airgapped clusters

### ISSUE THREAD

**Issue by gunamata** [rancher/rancher#41603]
[SURE-6332](https://jira.suse.com/browse/SURE-6332)

**Comment by nicholasSUSE** [comment]
Hello @kwwii 

For this issue, one of the proposed solutions is to download all images when building a Rancher container image. 
To optimize this process I need to have a minimum height and width for the images. 
Some of them are .png and most are .svg, but I am afraid in the end the images might take up too much space.
So perhaps it would be best to convert all of them to the minimum height x width.

**Comment by kwwii** [comment]
Thanks @nicholasSUSE - I assume that the images in question come from 3rd party repos and might change at any time (as would the charts themselves). How is that dealt with on air-gapped clusters?

I don't have any detailed information about the images themselves, so I cannot speak to whether scaling will easily work and/or be automatable. Do you have more details on the images themselves?

**Comment by nicholasSUSE** [comment]
This is resolved: https://github.com/rancher/rancher/pull/43909
