### ISSUE TITLE
Description field for Sidekicks is smaller than other fields.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#4160]
Rancher Version:v1.1.0-rc4

<img width="1134" alt="screen shot 2016-03-26 at 6 54 57 pm" src="https://cloud.githubusercontent.com/assets/4266958/14063496/bc85dff2-f388-11e5-8560-74abf749d58f.png">

**Comment by lvuch** [comment]
resolved in https://github.com/rancher/ui/pull/578

**Comment by tfiduccia** [comment]
Version - v1.0.1-rc1
Verified fixed
