### ISSUE TITLE
[BUG] rancher-webhook blocking CAPR operations/cluster operations in downstream cluster

### ISSUE THREAD

**Issue by Oats87** [rancher/rancher#41613]
**Rancher Server Setup**
- Rancher version: v2.7-head 

**Information about the Cluster**
- Kubernetes version: K3s and/or RKE2
- Cluster Type (Local/Downstream): Downstream CAPR/v2prov

**Describe the bug**
The `rancher-webhook` is being deployed into downstream clusters and creating a `MutatingWebhookConfiguration` and `ValidatingWebhookConfiguration` that checks `corev1/Secret` objects. While ordinarily this wouldn't be a big problem with minimally invasive configurations, the configurations are deployed and have a failure policy that blocks creation of secret objects. K3s/RKE2 use secrets internally for various reasons, such as `node-passwd` and (in RKE2's case) around static manifest generation for system components.

I observed this in 2 isolated cases but both related to v2prov:

**To Reproduce**
Scenario A: Create 3 node cluster with 1 controlplane, 1 etcd, and 1 worker node, then replace the worker node and observe your new worker node never registers. This was encountered in this issue: https://github.com/rancher/rancher/issues/41133#issuecomment-1550519440

Scenario B: Create a single-node all-in-one downstream RKE2 cluster, and perform a selective `kube-controller-manager` certificate rotation. This was encountered when manually validating this issue: https://github.com/rancher/rancher/issues/41125

**Result**

Scenario A: Observe that `k3s-agent` is complaining about an invalid `node password` file, and look in the `k3s` unit on the controlplane host to see that it is failing to create a secret due to the webhook policy. 

Scenario B: Observe that the `kube-controller-manager` doesn't come back up on its own, and `rke2-server` logs: 
```
May 19 15:03:43 kskcm-pool1-2876d649-4xn4n rke2[17126]: time="2023-05-19T15:03:43Z" level=warning msg="Failed to create Kubernetes secret: Internal error occurred: failed calling webhook \"rancher.cattle.io.secrets\": failed to call webhook: Post \"https://rancher-webhook.cattle-system.svc:443/v1/webhook/mutation/secrets?timeout=10s\": context deadline exceeded"
```

**Expected Result**
Neither scenario fails.

**Screenshots**

**Additional context**

**Comment by Oats87** [comment]
I filed a corresponding issue on RKE2 here: https://github.com/rancher/rke2/issues/4266

**Comment by brandond** [comment]
This would probably break secrets encryption key rotation as well, as the webhook would prevent the secrets from being updated to reencrypt.

**Comment by snasovich** [comment]
Added `team/area2` to labels as QA for this fix will probably be mostly handled by provisioning team QA, possibly indirectly via re-validating https://github.com/rancher/rancher/issues/41133 and https://github.com/rancher/rancher/issues/41125
FYI @sowmyav27 @daviswill2

**Comment by markusewalker** [comment]
> Added `team/area2` to labels as QA for this fix will probably be mostly handled by provisioning team QA, possibly indirectly via re-validating #41133 and #41125 FYI @sowmyav27 @daviswill2

As mentioned, this issue is a byproduct of the aforementioned issues. Once those have been validated and closed, I will close this issue as well.

**Comment by markusewalker** [comment]
As both of the issues have been respectively validated and closed, I will now close this issue as well.

**Comment by MbolotSuse** [comment]
## Release note

The mutating webhook configuration for secrets is no longer active in downstream clusters.
