### ISSUE TITLE
Gatekepper 3.12 OOB release into 2.7 

### ISSUE THREAD

**Issue by rohitsakala** [rancher/rancher#41625]
PR merged into Dev https://github.com/rancher/charts/pull/2574

**Comment by vivek-shilimkar** [comment]
Tested the OPA gatekeeper 102.1.0+up3.12.0 on Rancher v2.7.5-rc1 and k8s v1.26.4-rancher2-1. 
![image](https://github.com/rancher/rancher/assets/83208989/0ea33572-ee6c-4a07-b1f0-91e500a9e96a)

Created the constraints using the default templates for Namespace and Repository and it's working as expected.

Hence closing this issue.
