### ISSUE TITLE
[RFE] vSphere CPI chart updates to upstream v1.25.2 / v1.24.5

### ISSUE THREAD

**Issue by a-blender** [rancher/rancher#41626]
**Is your feature request related to a problem? Please describe.**

Upstream has released the following new vSphere CPI versions:

https://github.com/kubernetes/cloud-provider-vsphere/releases/tag/v1.25.2
https://github.com/kubernetes/cloud-provider-vsphere/releases/tag/v1.24.5

**Describe the solution you'd like**

Update the chart to include these new versions (possibly using new Renovate automation - not necessarily a requirement).

_Note: There will likely be new chart versions out by the time that we bump so check upstream for newly released versions, do the same with CSI._

# Checklist for items that need completed

- [ ] Update Image-mirror repo
- [ ] Update manifests in rancher/vsphere-charts
- [ ] (Non-standard checklist item) Ensure https://github.com/rancher/vsphere-charts/issues/46 is fixed so we include a fix for it as well
- [ ] Verify Slack hook notified about chart "release" in relevant channels
- [ ] Update chart in rancher/charts
- [ ] Update chart in rancher/rke2-charts (RKE2 team)
- [ ] Updated RKE2 to consume new chart (RKE2 team)

**Comment by snasovich** [comment]
This was done as per https://github.com/rancher/vsphere-charts/pull/56 / https://github.com/rancher/charts/pull/2668
