### ISSUE TITLE
[RFE] Add CIS-1.7 (1.25) Scan capability

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#41631]

**Comment by andypitcher** [comment]
Related JIRA: https://jira.suse.com/browse/SURE-5878

**Comment by Priyashetty17** [comment]
**QA TEST PLAN - YET TO BE REVIEWED BY QA TEAM**

<table>
    <tbody>
        <tr>
            <th>#</th>
            <th>Scenario</th>
            <th>Steps</th>
            <th>Expected</th>
            <th>Pass/Fail</th>
        </tr>
        <tr>
            <td>1</td>
            <td>Fresh install Rancher - k8s v1.25 and CIS profile v1.7</td>
            <td>
                <ol>
                    <li> Create a rancher server v2.7.6. </li> 
                    <li> Create the following non-hardened downstream clusters with k8s v1.25: Node driver provisioned - RKE/RKE2/K3S, Custom - RKE/RKE2/K3S, Imported - RKE/RKE2/K3S. </li>
                    <li> Create following hardened downstream clusters with k8s v1.25 and CIS profile v1.7: Custom - RKE/RKE2/K3S, Imported - RKE/RKE2/K3S. </li>
                    <li> Install the "rancher-cis-benchmark" on each cluster.</li>
                    <li> Verify that the min and max k8s version for CIS benchmark profile v1.7 is accurate. </li>
                    <li> Run CIS scans on all the clusters with the corresponding profiles: rke/rke2/k3s-profile-permissive-1.7 for non-hardened clusters and rke/rke2/k3s-profile-hardened-1.7 for hardened clusters. </li>
                </ol>
            </td>
            <td> 
                <ol>
                    <li> Rancher installation completes successfully. </li>
                    <li> All non-hardened downstream clusters with k8s v1.25 are created successfully. </li>
                    <li> All hardened downstream clusters with k8s v1.25 and CIS profile v1.7 are created successfully.  </li>
                    <li> Chart "rancher-cis-benchmark" is installed on each cluster successfully. </li>
                    <li> The min and max k8s version for CIS benchmark profile v1.7 are accurate. </li>
                    <li> CIS scan on all the clusters pass. </li>
                </ol>
            </td>
            <td><br><br>Pass/Fail: </td>
        </tr>
        <tr>
            <td>2</td>
            <td>Fresh install Rancher - k8s v1.26 and CIS profile v1.7</td>
            <td>
                <ol>
                    <li> Create a rancher server v2.7.6. </li> 
                    <li> Create the following non-hardened downstream clusters with k8s v1.26: Node driver provisioned - RKE/RKE2/K3S, Custom - RKE/RKE2/K3S, Imported - RKE/RKE2/K3S. </li>
                    <li> Create following hardened downstream clusters with k8s v1.26 and CIS profile v1.7: Custom - RKE/RKE2/K3S, Imported - RKE/RKE2/K3S. </li>
                    <li> Install the "rancher-cis-benchmark" on each cluster.</li>
                    <li> Verify that the min and max k8s version for CIS benchmark profile v1.7 is accurate. </li>
                    <li> Run CIS scans on all the clusters with the corresponding profiles: rke/rke2/k3s-profile-permissive-1.7 for non-hardened clusters and rke/rke2/k3s-profile-hardened-1.7 for hardened clusters. </li>
                </ol>
            </td>
            <td> 
                <ol>
                    <li> Rancher installation completes successfully. </li>
                    <li> All non-hardened downstream clusters with k8s v1.26 are created successfully. </li>
                    <li> All hardened downstream clusters with k8s v1.26 and CIS profile v1.7 are created successfully.  </li>
                    <li> Chart "rancher-cis-benchmark" is installed on each cluster successfully. </li>
                    <li> The min and max k8s version for CIS benchmark profile v1.7 are accurate. </li>
                    <li> CIS scan on all the clusters pass. </li>
                </ol>
            </td>
            <td><br><br>Pass/Fail: </td>
        </tr>
        <tr>
            <td>3</td>
            <td>Rancher Upgrade - v2.7.5 to v2.7.6</td>
            <td>
                <ol>
                    <li> Create a rancher server v2.7.5. </li> 
                    <li> Create a custom hardened RKE2 downstream cluster with v1.25 (with CIS profile v1.23) </li>
                    <li> Install the "rancher-cis-benchmark" on the cluster.</li>
                    <li> Upgrade Rancher from v2.7.5 to v2.7.6. </li>
                    <li> Verify that the min and max k8s version for CIS benchmark profile v1.7 is accurate. </li>
                    <li> Edit the downstream cluster and update the CIS profile to cis-1.7. </li>
                    <li> Run CIS scans on all the clusters with the corresponding profiles: rke/rke2/k3s-profile-permissive-1.7 for non-hardened clusters and rke/rke2/k3s-profile-hardened-1.7 for hardened clusters. </li>
                </ol>
            </td>
            <td> 
                <ol>
                    <li> Rancher installation completes successfully. </li>
                    <li> Custom hardened RKE2 downstream cluster is created successfully. </li>
                    <li> Chart "rancher-cis-benchmark" is installed on the cluster successfully. Note: CIS v1.23 profile will be the latest that's available. </li>
                    <li> Rancher is upgraded from v2.7.5 to v2.7.6 successfully. </li>
                    <li> The min and max k8s version for CIS benchmark profile v1.7 are accurate. </li>
                    <li> CIS profile for the downstream cluster is updated to cis-1.7. </li>
                    <li> CIS scan on all the clusters pass. </li>
                </ol>
            </td>
            <td><br><br>Pass/Fail: </td>
        </tr>
    </tbody>
</table>

**Comment by andypitcher** [comment]
PR created for rke1-cis-1.7 (1.25): https://github.com/rancher/security-scan/pull/134

**Comment by andypitcher** [comment]
PR created for `k3s-cis-1.7` (1.25): https://github.com/rancher/security-scan/pull/135

**Comment by andypitcher** [comment]
PR created for `rke2-cis-1.7` (1.25): https://github.com/rancher/security-scan/pull/136

Next step:  Craft a dedicated PR for `CIS-1.7 - rke/k3s/rke2 - config.yaml`

**Comment by andypitcher** [comment]
PR created for CIS-1.7 (1.25)  ConfigMap : https://github.com/rancher/security-scan/pull/137

**Comment by Priyashetty17** [comment]
@JonCrowther @andypitcher The chart installation with the security scan tag "v0.2.13-rc3" gets stuck in "Running" state because the security-scan pod couldn't pull the image associated with that tag. Upon checking docker hub, I discovered that the correct tag for the security scan image actually includes a dot after the 'v', i.e., "v.0.2.13-rc3". 
![image](https://github.com/rancher/rancher/assets/42880103/7c06b242-c6d5-4b3c-8066-8e002a643d70)

**Comment by andypitcher** [comment]
@Priyashetty17 this was my mistake, I just recreated the tag :

- GH : [v0.2.13-rc3](https://github.com/rancher/security-scan/releases/tag/v0.2.13-rc3)
- DockerHub: [v0.2.13-rc3](https://hub.docker.com/layers/rancher/security-scan/v.0.2.13-rc3)
