### ISSUE TITLE
[BUG] Cluster deletion is stuck `Resource scheduled for deletion` on an rke2 node driver cluster

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#41635]
**Rancher Server Setup**
- Rancher version: `v2.7.3` to v2.7-head `9f6a39e `
- Installation option (Docker install/Helm Chart): `Docker install`
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): k3s
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: `v1.26.4+k3s1`
- Cluster Type (Local/Downstream): Downstream Infrastructure provider RKE2, 2 nodes - 1 etcd + cp and 1 worker node
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Admin
   
**Describe the bug**
When I performed delete operation on an rke2 node driver cluster, the cluster is stuck in `removing` and the nodes were never deleted from the cloud provider. The following error is seen on the nodes in rancher server 
```
Failed deleting server [fleet-default/anurke2fleet2-ec-c7ba3540-lz7f7] of kind (LinodeMachine) for machine anurke2fleet2-ec-c994f7995-zp9qq in infrastructure provider: DeleteError: Downloading driver from https://<redacted>/assets/docker-machine-driver-linode Doing /etc/rancher/ssl docker-machine-driver-linode docker-machine-driver-linode: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, stripped About to remove anurke2fleet2-ec-c7ba3540-lz7f7 WARNING: This action will delete both local reference and remote instance. (anurke2fleet2-ec-c7ba3540-lz7f7) Removing linode: 46235898 Error removing host "anurke2fleet2-ec-c7ba3540-lz7f7": [502] Internal server error
```

**To Reproduce**
1. On rancher server v2.7.3, create an rke2 node driver cluster with 2 nodes - 1 etcd + cp and 1 worker
2. Created a helm git repo from continuous delivery tab https://github.com/anupama2501/fleet-examples/tree/master/single-cluster/monitoringchart
3. Upgrade rancher server to v2.7-head
4. Once the upgrade is successful, try to delete the rke2 node driver cluster.

**Result**
Following error is seen on the nodes `Deleteerror` and the deletion is stuck in `removing` state
```
Failed deleting server [fleet-default/anurke2fleet2-ec-c7ba3540-lz7f7] of kind (LinodeMachine) for machine anurke2fleet2-ec-c994f7995-zp9qq in infrastructure provider: DeleteError: Downloading driver from https://45.79.97.64/assets/docker-machine-driver-linode Doing /etc/rancher/ssl docker-machine-driver-linode docker-machine-driver-linode: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, stripped About to remove anurke2fleet2-ec-c7ba3540-lz7f7 WARNING: This action will delete both local reference and remote instance. (anurke2fleet2-ec-c7ba3540-lz7f7) Removing linode: 46235898 Error removing host "anurke2fleet2-ec-c7ba3540-lz7f7": [502] Internal server error

```
Nodes are also not deleted from the Linode cloud provider.

**Expected Result**
Expected the delete operation to go through without errors

**Additional context**
I tried to reproduce this on the following clusters and configs but so far not able to reproduce it again:
1. RKE2 AWS node driver - 1 etcd, 1 cp and 1 worker --> fresh install
2. RKE2 Linode node driver - 1 etcd, 1 cp and 1 worker --> fresh install
3. RKE2 Linode node driver - 1 etcd + cp and 1 worker --> fresh install
4. RKE2 AWS node driver - 1 etcd + cp and 1 worker --> upgrade
5. RKE1 Linode node driver - 1 etcd + cp and 1 worker --> fresh install
6. K3s AWS node driver - 1 etcd + cp and 1 worker --> upgrade

In the local cluster following is noticed in the `fleet-default` namespace on the jobs `anurke2fleet2-ec-c7ba3540-lz7f7-machine-provision` and `anurke2fleet2-w-c7ba3540-lz7f7-machine-provision`
```
docker-machine-driver-linode: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, stripped
About to remove anurke2fleet2-ec-c7ba3540-lz7f7
2023-05-18T23:20:09.539739405Z WARNING: This action will delete both local reference and remote instance.
2023-05-18T23:20:09.545375047Z (anurke2fleet2-ec-c7ba3540-lz7f7) Removing linode: 46235898
2023-05-18T23:20:09.755354580Z Error removing host "anurke2fleet2-ec-c7ba3540-lz7f7": [502] Internal server error
```

Following errors are seen in the docker logs of rancher server:
```
2023/05/22 22:20:46 [INFO] [planner] fleet-default/anurke2fleet2: reconciliation stopped: CAPI cluster is deleting
2023/05/22 22:20:51 [INFO] [planner] fleet-default/anurke2fleet2: reconciliation stopped: CAPI cluster is deleting
2023/05/22 22:20:56 [INFO] [planner] fleet-default/anurke2fleet2: reconciliation stopped: CAPI cluster is deleting
2023/05/22 22:21:01 [INFO] [planner] fleet-default/anurke2fleet2: reconciliation stopped: CAPI cluster is deleting
```

Some kubelet error logs on the cluster:
```
E0518 23:14:52.634440    2292 remote_runtime.go:625] "ContainerStatus from runtime service failed" err="rpc error: code = NotFound desc = an error occurred when try to find container \"5d9963bf080aa9f1fbf1205f0217d7c6950255c0906604fd967e16699783f729\": not found" containerID="5d9963bf080aa9f1fbf1205f0217d7c6950255c0906604fd967e16699783f729"
I0518 23:14:52.635288    2292 pod_container_deletor.go:52] "DeleteContainer returned error" containerID={Type:containerd ID:5d9963bf080aa9f1fbf1205f0217d7c6950255c0906604fd967e16699783f729} err="failed to get container status \"5d9963bf080aa9f1fbf1205f0217d7c6950255c0906604fd967e16699783f729\": rpc error: code = NotFound desc = an error occurred when try to find container \"5d9963bf080aa9f1fbf1205f0217d7c6950255c0906604fd967e16699783f729\": not found"

E0517 21:59:00.280855    2292 pod_workers.go:965] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"helm\" with CrashLoopBackOff: \"back-off 10s restarting failed container=helm pod=helm-install-rke2-calico-r4nh2_kube-system(d5c0b389-855a-41e1-9dd4-2922d0fa6002)\"" pod="kube-system/helm-install-rke2-calico-r4nh2" podUID=d5c0b389-855a-41e1-9dd4-2922d0fa6002
```

**Comment by Oats87** [comment]
This is expected behavior on both the Rancher and CAPI side. The machine infrastructure under the cluster has failed to delete, i.e. the `502`. If we remove the cluster and ignore these errors, then it will likely orphan infrastructure which is not desirable.

**Comment by markusewalker** [comment]
From the explanation above, I will close this issue out.
