### ISSUE TITLE
[SURE-6228] [RFE] Tool for scheduled/conditional profiles

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#41645]
Internal reference: [SURE-6228](https://jira.suse.com/browse/SURE-6228)

**Request description:**
Most memory related issues could benefit from having a relevant heap profile provided for them. Unfortunately it is not always easy to take a profile when it could provide valuable information. This may be because memory spikes are unpredictable. This may be because multiple profiles are needed.

**Actual behavior:**
None.

**Expected behavior:**
There should be a tool for scheduling these profiles. A bonus would be to added a conditional for only taking the profile when memory reaches a certain threshold. This tool could be a script for setting up a linux cronjob, a chart for deploying a k8s cronjob, or anything else that gets the job done.

**Workaround:**
Is workararound available and implemented? sort of
What is the workaround: Ask support or customer to take profile. We only get it for one point in time and sometimes it cannot be taken at a time where the data is relevant.

**Comment by samjustus** [comment]
SURE-6228

**Comment by moio** [comment]
The original scope of this ticket was to add tooling inside of Rancher itself, but at the moment the plan is to work on improving external tooling, documentation, procedures and guidelines instead - also to keep them applicable to various other products and components, not just Rancher.

I am thus closing this issue for the time being.
