### ISSUE TITLE
SSL checkbox is not saved when cloning Load Balancer

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4165]
Version: master 3.27

Steps to Reproduce: 
1.  Create a load balancer and check the ssl checkbox and select a certificate
2.  Create the LB and wait for it to activate
3.  Click on Clone for active LB

Results: The ssl checkbox is no longer checked

Expected: ssl checkbox should be saved

**Comment by vincent99** [comment]
Also with editing a balancer that has SSL

**Comment by tfiduccia** [comment]
Version - v1.0.1-rc1
Verified fixed
