### ISSUE TITLE
GCE cluster

### ISSUE THREAD

**Issue by akamisarau** [rancher/rancher#41655]
Would be great to have documentation explaining how to create RKE2 GCE cluster. For now after specifying all the settings in Rancher UI it goes to a failure loop with the following error:
```bash
Error (Trying to access option which does not exist THIS ***WILL*** CAUSE UNEXPECTED BEHAVIOR Type assertion did not go smoothly to string for key [cmdCreateInner] error setting machine configuration from flags provided: no Google Cloud Project name specified (--google-project) )
```
During cluster configuration in UI we specify the following cloud provider config:
![image](https://github.com/rancher/rke2/assets/58438505/f88dae0f-7e6d-4879-a24b-6277157379f3)
But probably that is wrong because such format is taken from custom cluster setup in rancher docs. So, in opposite to Azure, it is absolutely not clear what is the format of Google Cloud provider config.
We use Rancher 2.7

**Comment by akamisarau** [comment]
@brandond 
Thank you for moving it to correct space!

Regarding documentation, I used it to setup a cluster, but it does not help. In description it says, that in such way we can enable cloud provider for custom cluster. For GCE cluster I expect specifying somewhere cloud credentials, so Rancher could create VMs in GCP, but for RKE1 GCE cluster it does not ask for cloud credentials at all. For RKE2 GCE cluster it asks for credentials, but it does not affect anything. In both cases it fails with the error described above. Also I don't see any option to specify VM size or region.

**Comment by QuadmanSWE** [comment]
I am also having issues trying to use the google provider to create a cluster on google cloud engine. I want to run RKE2 for a demo but I can not get any sane error message. Came across this issue and tried to apply configuration like in the picture. Get the error message 

`Trying to access option  which does not exist
THIS ***WILL*** CAUSE UNEXPECTED BEHAVIOR
Type assertion did not go smoothly to string for key 
[cmdCreateInner] error setting machine configuration from flags provided: no Google Cloud Project name specified (--google-project)
Stream closed EOF for fleet-default/rke2-gcp-pool1-8072120c-gp8mq-machine-provision-6zh8w (machine)
`

![image](https://github.com/rancher/rancher/assets/8070109/89cfa3e5-787b-44ef-a716-e5490e36e6b8)

**Comment by akamisarau** [comment]
Rancher guys!
Please respond there. It is not a feature request or something that is not clear. We just a need a clarification how to deploy clusters on VMs in GCP.

**Comment by brandond** [comment]
I'm not sure that the GCP node driver is currently functional; note that it is not listed on our support matrix:
https://www.suse.com/suse-rancher/support-matrix/all-supported-versions/rancher-v2-7-3/#el-48902

![image](https://github.com/rancher/rancher/assets/370103/c19d1c4e-06a4-44a7-82ee-597aac8feab7)

**Comment by QuadmanSWE** [comment]
Google node driver is not enabled by default but the docs don't reflect that this should be challenging or tricky once enabled. I got GKE to work pretty much out of the gate but since RKE2 is what I wanted to evaluate my entire experience felt off putting.

**Comment by akamisarau** [comment]
Thank you @brandond that you are trying to help. But it would be great if you could ask someone who has more information to look at this. For me this looks quite strange, that there is an option to create GCE cluster, there is some documentation, but on practice you can't do it. 
![image](https://github.com/rancher/rancher/assets/58438505/9687cac8-8da2-43e7-b9e0-b1a6c6155d6d)

**Comment by akamisarau** [comment]
Some additional details
rancher-machine binary which is responsible for provisioning VMs is ready for google driver.
```bash
./rancher-machine create --driver google --help
```
The command above returns the list of possible parameters to spin-up VMs in GCP:
```bash
   --google-address                                                                                                    GCE Instance External IP [$GOOGLE_ADDRESS]
   --google-auth-encoded-json                                                                                          Base64 encoded GCE auth json [$GOOGLE_APPLICATION_CREDENTIALS_ENCODED_JSON]
   --google-disk-size "10"                                                                                             GCE Instance Disk Size (in GB) [$GOOGLE_DISK_SIZE]
   --google-disk-type "pd-standard"                                                                                    GCE Instance Disk type [$GOOGLE_DISK_TYPE]
   --google-machine-image "ubuntu-os-cloud/global/images/ubuntu-1604-xenial-v20170721"                                 GCE Machine Image Absolute URL [$GOOGLE_MACHINE_IMAGE]
   --google-machine-type "n1-standard-1"                                                                               GCE Machine Type [$GOOGLE_MACHINE_TYPE]
   --google-network "default"                                                                                          Specify network in which to provision vm [$GOOGLE_NETWORK]
   --google-open-port [--google-open-port option --google-open-port option]                                            Make the specified port number accessible from the Internet, e.g, 8080/tcp
   --google-preemptible                                                                                                GCE Instance Preemptibility [$GOOGLE_PREEMPTIBLE]
   --google-project                                                                                                    GCE Project [$GOOGLE_PROJECT]
```
Still not clear how to pass these parameters through Rancher UI

**Comment by ahmedrshdy** [comment]
Hi all,
I am hitting the same challenge, in contrast to GKE clusters, there is no obvious way to provision GCE clusters using the UI. The strange thing is that, in contrast to the GKE cluster, there is no way to configure the credentials nor the machine type for the new cluster within the GCE creation form.

**Comment by akamisarau** [comment]
Still waiting for implementation or documentation

**Comment by ErmalKo** [comment]
Is there any update on documentation on how to deploy in GCE?

**Comment by dantecl** [comment]
hi folks, I see the issue is auto-closed, but this is still not working. Can someone comment on what's the supported way to create a cluster in GCE?

**Comment by yas51ne** [comment]
Hi same issue here, any updates?

**Comment by skanakal** [comment]
I am able to create the GCE cluster on 2.12 rancher... please try this on latest rancher and let us know if you still face any issues...
please follow the documentation https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/launch-kubernetes-with-rancher/use-new-nodes-in-an-infra-provider/create-a-google-compute-engine-cluster#1-enable-the-gce-node-driver

<img width="1715" height="781" alt="Image" src="https://github.com/user-attachments/assets/dff69a74-2836-4683-80b5-338c878d2880" />

**Comment by skanakal** [comment]
- Rancher 2.12 now supports Google Compute Engine (GCE) Node Driver provisioning of RKE2 and K3s clusters. See [#49681](https://github.com/rancher/rancher/issues/49681) and [#14011](https://github.com/rancher/dashboard/issues/14011).
