### ISSUE TITLE
How to use Rancher environment certificates in custom container?

### ISSUE THREAD

**Issue by lalarsson** [rancher/rancher#4166]
Hi,

I've been looking around for an answer to this question but couldn't find any - sorry if I somehow missed it!

How do I use an environment certificate (for example generated by LE) in a custom container? 

I know how to add certificates to the loadbalancer but I can't find any information on how to add them to my own nginx proxies(for example).

**Comment by vincent99** [comment]
The load balancer terminates the SSL connection and sends the plaintext request (over the separately-encrypted IPSec overlay network) to the target container.  So if you're using our balancer you don't need to manage certs on the container at all.  And there is a community catalog entry to manage auto-renewing certs in Rancher from Let's Encrypt.

If you aren't using SSL-termination in the balancer, then Rancher is essentially uninvolved and your question as I understand it is more like "how do I use Let's Encrypt with Docker in general", so [their docs](http://letsencrypt.readthedocs.org/en/latest/using.html#running-with-docker) may help.

**Comment by lalarsson** [comment]
Thanks for the quick reply! :+1: 

I think I was a bit unclear in my question. Lets try again :)

What I need to know is how I can access (read-only) the certificates stored in Rancher generated by LE in other contexts than the loadbalancer. Is this possible?

**Comment by vincent99** [comment]
It is intentionally not possible to read the private keys for certificates out of the Rancher API.  So if you need them you'll have to run the Let's Encrypt client yourself.

**Comment by lalarsson** [comment]
Ah, ok. Hmmm, I understand why. I guess that I'll set up another LE instance then.

Thanks for the answers :+1:

**Comment by vincent99** [comment]
It's possible the [Let's Encrypt container](https://github.com/janeczku/rancher-letsencrypt) in the catalog exposes some way to get to them, I'm not sure.  @janeczku ?

**Comment by janeczku** [comment]
@lalarsson Should be possible to access certificates/keys via volume mounting as they are currently stored in the container during the entire runtime. I was actually going to change that (meaning nothing will be stored in the container) in the next version. So if you need this kind of functionality join the discussion in https://github.com/janeczku/rancher-letsencrypt.

**Comment by lalarsson** [comment]
Alright, I'll do so! Thanks for the info!

**Comment by deniseschannon** [comment]
@lalarsson Let me know if you have any further questions. Otherwise, it looks like you're all set and I'll close this issue.
