### ISSUE TITLE
Tolerations and nodeSelector values from values.yaml are not getting applied to Gatekeeper templates.

### ISSUE THREAD

**Issue by doflamingo721** [rancher/rancher#41688]
Following is the issue occurring for `rancher-gatekeeper 102.1.0+up3.12.0`

The `tolerations` and `nodeSelector` values sourced from the `values.yaml` to the [webhook-configs-pre-delete.yaml](https://github.com/rancher/charts/blob/af25f5149aa04db6c2ef9ffb09bd3286e26e8a18/charts/rancher-gatekeeper/102.1.0%2Bup3.12.0/templates/webhook-configs-pre-delete.yaml#L57-L58) are not getting applied to the template as expected. 
The reason being it is only taking in the values for these fields from the [helpers.tpl](https://github.com/rancher/charts/blob/af25f5149aa04db6c2ef9ffb09bd3286e26e8a18/charts/rancher-gatekeeper/102.1.0%2Bup3.12.0/templates/_helpers.tpl#L51-L64) file and not appending the values  we're passing from the values.yaml.
The same issue might also be present in other templates and not just the one mentioned above.

Blocker for: https://github.com/rancher/rancher/issues/41026

**Comment by gunamata** [comment]
@doflamingo721 , As we have moved past the code freeze for [2023-Q2-v2.7x](https://github.com/rancher/rancher/milestone/300), I am taking this out of the milestone now.

**Comment by doflamingo721** [comment]
@gunamata Can you assign the next milestone since there is another issue(gatekeeper hull tests) which is tied to this issue and we can update the milestone of that ticket accordingly.
