### ISSUE TITLE
Add option to select image in digitalocean driver

### ISSUE THREAD

**Issue by hwinkel** [rancher/rancher#4168]
Rancher Version: 1.0.0-rc4

Docker Version: 1.10.3

OS: ubuntu 14.04

Steps to Reproduce: create new hosts with the DO driver

Results: can only choose one image version of DO droplets (Ubuntu 14.04)

Expected: can choose all available DO droplet images,especially CoreOS and CentOS for our use cases

**Comment by vincent99** [comment]
I'm not sure which ones of the machine can *actually* provision, but they're added for now..

**Comment by tfiduccia** [comment]
Centos not showing up in drop-down?

**Comment by vincent99** [comment]
So basically they all fail, even though there are provisioners available for each.  Seems like something we'll have to look into machine/go-machine-service integration for.  I'll leave them there but disabled for now.

**Comment by vincent99** [comment]
Cent7 and Ubuntu 16.10 work with machine 0.8, but I don't see much of a good reason why more shouldn't work.  @wlan0 ?

**Comment by wlan0** [comment]
@vincent99 I don't know the reason yet. Im investigating.

**Comment by wlan0** [comment]
@westlywright After investigating, I found that Ubuntu, CentOS, Fedora work fine. The problem is only with CoreOS. In case of the CoreOS image in DO, the keys are set for the user "core" and not for "root". If I set the "sshUser" parameter in the API to "core" and try to provision a DO CoreOS host, it works just fine. 

This option is available in the API, but not in the UI. This needs to be fixed.

**Comment by tfiduccia** [comment]
CentOS, Debian and FreeBSDk are all still dimmed?  Should they be?

**Comment by tfiduccia** [comment]
Vincent enabling other drivers - will test after next build.

**Comment by westlywright** [comment]
I was enabling the ones that @wlan0 mentioned in his comment that he said were working fine

**Comment by tfiduccia** [comment]
Verified the following setup:
CentOS - 7
CoreOS - 11.85 (stable)
Debian - 8.6
Fedora - 23 & 24
Ubuntu - 14.04 & 16.04

**Comment by tfiduccia** [comment]
Version - v1.2.0-pre4-rc10
Verified fixed - Images stated above are now available for use
