### ISSUE TITLE
[BUG] Since 2.7.2 Rancher Cluster/Node page doesn't show pods anymore

### ISSUE THREAD

**Issue by julienym** [rancher/rancher#41697]
**Rancher Server Setup**
- Rancher version: 2.7.2 and 2.7.3
- Installation option (Docker install/Helm Chart): Helm chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): k3s v1.23.9+k3s1

**Describe the bug**
On local (k3s) and AKS imported cluster, the node page doesn't show pods anymore
![image](https://github.com/rancher/rancher/assets/10652969/6fc8911f-b25f-48a9-94d3-20fd63dc9c0f)

Downgraded to 2.7.1 and bug confirmed for 2.7.2 and 2.7.3

**Comment by geoff-carr-bzy** [comment]
Confirm we see the same behaviour / bug after upgrading from `2.6.6` to `2.7.3`

**Comment by swelcker** [comment]
Confirm too for `v2.7.3` (k3s/etcd)
View on selected Node:
![image](https://github.com/rancher/rancher/assets/12301571/cf6428cf-2fbd-43ab-9f7c-d48dde27b223)

Nodes List View:
![image](https://github.com/rancher/rancher/assets/12301571/fbf775cb-1e8e-4f6d-add9-412053234e45)

**Comment by malmor** [comment]
Hey there, I just upgraded to `v.2.7.5` - and this issues seems to be fixed.
Can you confirm this?

**Comment by julienym** [comment]
Yes indeed thanks!

**Comment by k8s-doomzday** [comment]
Im noticing this same behavior on RKE2 Rancher 2.8.2/1.27.12rke2+r1 with workload clusters on kubernetes versions 1.27.12rke2+r1 and 1.27.13rke2+r1. For myself, I rarely am able to reproduce the issue (Firefox browser seems to give me a better chance to produce the issue), however, a handful of my Developers are reproducing the issue on a daily basis across multiple web browsers. We have attempted some infrastructure work such as increasing CPU/Memory and rebalancing across our hypervisors (our clusters are built on-prem).

We have another, unrelated, local cluster on Rancher 2.8.2/1.27.14rke2+r1 and workload clusters running 1.27.14rke2r1. These clusters do not produce the same issue.
