### ISSUE TITLE
[BUG] download chart from rancher apps-charts-monitoring-download and install manually but can not been detect by rancher monitoring dashboard

### ISSUE THREAD

**Issue by JaneLiuL** [rancher/rancher#41692]
rancher 2.7.3 version
for easy manage, we can not install monitoring from rancher gui one by one. so we download the chart from rancher console: click:  Apps--> monitoring ---> chart---download.
we download the rancher-monitoring-crd and rancher-monitoring two charts. 
and we use helm install command for all downsteam cluster.
then we create ingress and found the prometheus and grafana are succesfully.
the question is, when we login rancher console, from cluster-->clustername-->monitoring, the dashboard for grafana or promethes or prometheusrules are disable, it said "Resource unavailable"

**Comment by breitenj** [comment]
Hi @JaneLiuL,
I have the same issue. Did you figure out a solution?

**Comment by betonmoewe** [comment]
same for me with rancher 2.7.5 :(

**Comment by WeAreHadock** [comment]
Hi,
Same issue here, any workaround @JaneLiuL ?

**Comment by breitenj** [comment]
I found a solution that worked for me. Apparently rancher looks for an `App` with the name `rancher-monitoring`. After creating a dummy app with the same name, everything works again:
```
apiVersion: catalog.cattle.io/v1
kind: App
metadata:
  name: rancher-monitoring
  namespace: cattle-monitoring-system
spec: {}
```
