### ISSUE TITLE
Submit native docker command to create container

### ISSUE THREAD

**Issue by smw355** [rancher/rancher#417]
I think it would be great to be able to create containers by submitting the Docker run command, instead of the Rancher GUI.  Ideally this could be done from within the GUI.  when I click to create a container, I could either use the GUI or write out the command. 

For example: to translate "sudo docker run --name some-wordpress -e WORDPRESS_DB_HOST=10.1.2.3:3306 \
    -e WORDPRESS_DB_USER=... -e WORDPRESS_DB_PASSWORD=... -d wordpress" into the UI takes quite a bit of time.  It would be great to have an option to just paste in my command.

**Comment by sheng-liang** [comment]
I totally agree. It's weird to be able to interpret Docker Compose templates but not Docker command line itself.

**Comment by vincent99** [comment]
This would pair well with #258

**Comment by faddat** [comment]
Hear Hear!

**Comment by vincent99** [comment]
I think it's fair to say this hasn't received much interest, and does not mix well with the emphasis on services over standalone containers...
