### ISSUE TITLE
[RFE] Add and update Rancher controllers with godoc descriptions

### ISSUE THREAD

**Issue by a-blender** [rancher/rancher#41703]
**Is your feature request related to a problem? Please describe.**

Add and update Rancher controllers to have detailed `godoc` descriptions. Currently, info on controllers can only be found in generic Kubernetes docs or on confluence behind the VPN or passed within the team internally via discussion / word of mouth. If you need to work on a particular controller, you learn how it works by reading code and a huge chunk of it is uncommented. +1 for doing this because it will save on that learning time, it's better practice, and will give engineers a better understanding of the provisioning flow.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by snasovich** [comment]
Closing as it's no longer prioritized. The referenced PR may be restarted by the team owning those controllers as/if needed.
