### ISSUE TITLE
[BUG] RKE1, RKE2 fleet agent is not redeploying after upgrading from 2.7.3 -> 2.7-head

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#41700]
**Rancher Server Setup**
- Rancher version: v2.7-head (fbca7c3)
- Installation option (Docker install/Helm Chart): helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): rke1, 1.4.5
- Proxy/Cert Details: valid certs 

**Information about the Cluster**
- Kubernetes version: any downstream cluster, tested on v1.25 and v1.26
- Cluster Type (Local/Downstream): downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): tested on providers aws and linode

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: tested as standard user, cluster owner

**Describe the bug**

if fleet agent is deployed with a misconfigured agent customization, subsequent cluster updates with a correct configuration will not redeploy fleet

**Update** - as of now, no updates on rke1 nor rke2 are going through - regardless of the previous state of fleet agent, subsequent updates to the cluster spec are not being reflected in the fleet workload
additionally, it seems that the initial deploy using agentCustomization for fleet is not working either. 

**update 2** - this issue appears to be due to fleet not redeploying on the latest RC. Instead, it is still using 0.6.0 instead of 0.7.x-rc3

**To Reproduce**

* deploy rancher on v2.7.3
* deploy a 3 node cluster
  * 1 etcd node
  * 1 cp node
  * 1 worker node
* upgrade rancher to 2.7-head
* 

**Result**
fleet agent isn't re-deploying to the latest version available

**Expected Result**

fleet agent should redeploy

**Screenshots**

**Additional Context**
* This happens for new clusters on the upgraded rancher server as well (fleet version is 0.6.0 instead of 0.7.x-rc3)

**Comment by manno** [comment]
Initial experiments with https://github.com/rancher/fleet/pull/1567 are looking good.

**Comment by slickwarren** [comment]
closing this issue; the problem was in how a restore occurred in my setup, so fleet agent wasn't using the proper version. Re-testing on a fresh install, and a fresh upgrade, do not present this error.
