### ISSUE TITLE
[Feature] k8s 1.27 support - apps and feature charts

### ISSUE THREAD

**Issue by rohitsakala** [rancher/rancher#41720]
**Team Mapps**

- [x] rancher/rancher#41781
- [x] rancher/rancher#41782
- [x] rancher/rancher#41783

**Team 3**

- [x] rancher/rancher#41784
- [x] rancher/rancher#41785
- [x] rancher/rancher#41786
- [x] rancher/rancher#41787

**Team 1**

- [x] rancher/rancher#41789
- [x] rancher/rancher#41790

**Team 2**

- [x] rancher/rancher#41791
- [x] rancher/rancher#41792
- [x] rancher/rancher#41793

**Opni**

- [x] rancher/rancher#41794
- [x] rancher/rancher#41788

**Fleet**

- [x] rancher/rancher#41795

**Highlander**

- [x] rancher/rancher#41796
- [x] rancher/rancher#41797
- [x] rancher/rancher#41798

**Harvester**

- [x] rancher/rancher#41799
- [x] rancher/rancher#41800

**Longhorn**

- [x] rancher/rancher#41801

**Epinio**

- [x] rancher/rancher#41802

**NeuVector**

- [x] rancher/rancher#41803

**Kubewarden**

- [x] KubeWarden [#41893](https://github.com/kubewarden/kubewarden-controller/issues/465)

**Comment by jhmarina** [comment]
@gunamata could you please add Kubewarden to the list? https://github.com/kubewarden/kubewarden-controller/issues/465

**Comment by gunamata** [comment]
@jhmarina , Added Kubewarden to the list.

**Comment by gunamata** [comment]
@jhmarina , As we are now targeting k8s 1.27 and 1.28 upgrade for the rancher Q4 release, I have updated the tickets description for all the charts accordingly. As you created the Kubewarden ticket, Can you please do the same and add k8s 1.27 & 1.28 upgrade for the Q4 release. Thank you.
