### ISSUE TITLE
Errors logged when "Updating haproxy"

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#4172]
Rancher Version:v1.0.0.-rc4

Had global LB services. Added 5 hosts (Digital Ocean hosts).
Lb service came up successfully on the hosts. 
But following exception seen in logs:

```
2016-03-28 15:30:10,146 ERROR [:] [] [] [] [ecutorService-3] [.p.c.v.i.ConfigItemStatusManagerImpl] Failed null, exit code [1] output [INFO: Updating haproxy
INFO: Downloading http://104.197.7.182:8080/v1//configcontent//haproxy current=haproxy-14-a5eac3965952846cbd39c610ae44d58f5b54450bd46bdfba35c57dda8edfaab0
basename: missing operand
Try 'basename --help' for more information.
ERROR: Missing SHA1SUMS files, invalid download
```

**Comment by alena1108** [comment]
Same root cause as in https://github.com/rancher/rancher/issues/4171

**Comment by sangeethah** [comment]
Tested with Rancher Version:v1.0.0-rc6
Had global LB services. Added 5 hosts (Digital Ocean hosts).
Lb service came up successfully on the hosts. 
No errors seen in logs.
