### ISSUE TITLE
[BUG] Project roles are associated to the Latest NameSpace only

### ISSUE THREAD

**Issue by dasarinaidu** [rancher/rancher#41727]
**Rancher Server Setup**
- Rancher version: v2.7.3 & v2.7-c2971d8d84e79a2ddbc0bda3d482090abccc6124-head also
- Installation option (Docker install/Helm Chart): Docker and HA
- Cluster Type (Local/Downstream): Downstream Cluster of any typ

**Describe the bug**

This is causing multiple issues when we create projects and associate project roles to a standard user. The associated users unable to create Deployments/DaemonSets/Config Maps etc, all of these are associated to a single name space. While creating Deployments/ Daemonset etc-- The namespace dropdown contains only one name space and creation is failing with Forbidden error.

**To Reproduce**

1. Create a Project Role `pr1` (verb Create & Resource :'`Deployment`')
2. Create another Project Role `pr2` (verb Create & Resource :'`Daemonset`')
3. Create a Standard User `su1`
4. Create a Downstream cluster `cls1`
5. On cls1 create a Project `proj1` : Add `su1` and `pr1`
6. Create a Name Space for `proj1` : `ns1`
7. On cls1 create another Project `proj2` : Add `su1` and `pr2`
8. Create a Name Space for `proj2` : `ns2`
9. Login with su1
10. User can see both projects and under workloads Deployment & Daemonset as well
11. Now, when you try to create a `Deployment` the name space showing `ns2` only in the drop down and user cannot create a Deployment. User getting Forbidden error.

**`More details:`**
1. Latest created name space is displaying in the dropdown on UI while creating workloads.
2. After Inheriting a project role : User cannot create workloads unless it is associated to the latest namespace.

**Expected Result**
1. While creating Deployment/ Daemonset : The appropriate NameSpace should be selected and upon creating the workloads the user should able to create workloads properly.

**Screenshots**
<img width="1494" alt="image" src="https://github.com/rancher/rancher/assets/22034884/fc4bcd72-ecb7-4835-98a2-92fc305ced73">

<img width="1478" alt="image" src="https://github.com/rancher/rancher/assets/22034884/87208848-8524-4c1a-bc7f-758e5959e6ef">

**Additional context**

This is an existing issue, seeing it on v2.7.3

**Comment by dasarinaidu** [comment]
This is happening on v2.7.2 and moving the milestone to 2023-Q3-v2.7x

**Comment by samjustus** [comment]
these issues are known by UI team and exist in GH already
