### ISSUE TITLE
Pin downstream cluster's webhook version

### ISSUE THREAD

**Issue by maxsokolovsky** [rancher/rancher#41730]
SURE-6429

**Comment by maxsokolovsky** [comment]
# QA Testing
Ensure the agent deployment's env var `CATTLE_RANCHER_WEBHOOK_VERSION` controls the version of the webhook that the agent deploys.

### New cluster with a new agent
1. Provision a downstream cluster, wait for it to come up and for the webhook to be deployed on it.
1. Note the version of the webhook. Go to the UI in the downstream cluster and change the webhook's version to something else.
1. Wait for the new webhook to be deployed.
1. Refresh the Rancher's chart catalog.
1. Note that, after a few seconds, the agent takes down webhook and deploys one whose version is the original.

### Existing cluster with a new agent
1. Provision a downstream cluster, wait for it to come up and for the webhook to be deployed on it.
1. Note the version of the webhook. Now update agent's deployment - specify `CATTLE_RANCHER_WEBHOOK_VERSION` with a different value. This would specify the new pinned version of the webhook. Save the deployment and observe how the agent gets restated.
1. Note that the newagent takes down webhook and deploys one whose version is the new pinned version specified by the env var.

**Comment by anupama2501** [comment]
QA to validate:

**Test case1: **
Reference from Max's comment: New cluster with a new agent

- Create a downstream cluster RKE1 and RKE2 node driver by adding the env var `CATTLE_RANCHER_WEBHOOK_VERSION=v2.0.4+up0.3.4` and verify the downstream cluster comes up on the specified version.

**Test case2:** 

-  Following the above use case, upgrade the downstream cluster's webhook version to the version `v0.3.5-rc7` , refresh the system charts repo and verify the webhook version goes back to `0.3.4`

**Test case3:**
- Verify `CATTLE_RANCHER_WEBHOOK_MIN_VERSION` is not enforced on a rancher server upgrade on the downstream clusters:
    - Create a few downstream clusters on rancher v2.7.3, upgrade rancher server to v2.7-head. 
    - Update the downstream clusters `CATTLE_RANCHER_WEBHOOK_VERSION` to `v2.0.4+up0.3.4`
    - Cluster comes up active on the version `v2.0.4+up0.3.4`
    - Upgrade the version to `v0.3.5-rc7`
    - Verify after refreshing the repo, the version changes back to `v2.0.4+up0.3.4`

**Test case4:**
Reference from Max's comment: Apply the workaround and upgrade scenario

- In a downstream cluster, update the cluster agent deployment by setting the CATTLE_RANCHER_WEBHOOK_MIN_VERSION env var to a proper value. For 2.7.3, it would be 2.0.3+up0.3.3. For 2.7.2, it would be 2.0.2+up0.3.2.
- Observe that the downstream webhook's version is the value you set for the value.
- Upgrade Rancher to 2.7.5-rc5.
- Remove the CATTLE_RANCHER_WEBHOOK_MIN_VERSION env var that you'd set in the workaround.
- Validate that the webhook deployment and chart are now at exact version.

**Test case5:**
- Remove the CATTLE_RANCHER_WEBHOOK_VERSION var from the downstream clusters and verify the clusters are upgraded to the version `v0.3.5-rc7`

**Test case6:**
Reference from Max's comment: Existing cluster with a new agent

- Provision a downstream cluster, wait for it to come up and for the webhook to be deployed on it.
- Note the version of the webhook. Now update agent's deployment - specify CATTLE_RANCHER_WEBHOOK_VERSION with a different value. This would specify the new pinned version of the webhook. Save the deployment and observe how the agent gets restated.
- Note that the newagent takes down webhook and deploys one whose version is the new pinned version specified by the env var.
