### ISSUE TITLE
[Feature Request] Rancher logs spammed with info logs for hosted downstream clusters

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#41735]
**Rancher Server Setup**
- Rancher version: `v2.7.3` upgraded to v2.7-head `f0d4078`
- Installation option (Docker install/Helm Chart): Docker install
   - If Helm Chart, Kubernetes Info: k3s
         Cluster Type (RKE1, RKE2, k3s, EKS, etc):
         Node Setup: 1 node 
         Version: `v1.26.4+k3s1
- Proxy/Cert Details: `self-signed`

**Information about the Cluster**
- Kubernetes version:  `v1.25.6`
- Cluster Type (Local/Downstream): `Downstream hosted AKS 1 node`, `Downstream hosted EKS 3 nodes`, Downstream hosted GKE 2 nodes`

**Describe the bug**
Rancher server logs are spammed with info logs when I have hosted downstream clusters created.

**To Reproduce**
1. Create a rancher server on v2.7.3
2. Create an AKS/GKE/EKS hosted cluster on version 1.25.6 with the default configuration on the UI
3. Upgrade rancher server to v2.7-head

**Result**
Observed multiple info logs spamming every few minutes in rancher logs
```
2023/06/03 15:34:36 [INFO] checking cluster [c-vtm2p] upstream state for changes
2023/06/03 15:34:36 [INFO] updating cluster [c-vtm2p], upstream change detected
2023/06/03 15:34:36 [INFO] cluster [c-vtm2p] matches upstream, skipping spec sync
2023/06/03 15:35:07 [INFO] checking cluster [c-94v8x] upstream state for changes
2023/06/03 15:35:08 [INFO] updating cluster [c-94v8x], upstream change detected
2023/06/03 15:35:08 [INFO] cluster [c-94v8x] matches upstream, skipping spec sync
2023/06/03 15:36:37 [INFO] checking cluster [c-zq2kd] upstream state for changes
2023/06/03 15:36:37 [INFO] cluster [c-zq2kd] matches upstream, skipping spec sync
2023/06/03 15:39:36 [INFO] checking cluster [c-vtm2p] upstream state for changes
2023/06/03 15:39:36 [INFO] updating cluster [c-vtm2p], upstream change detected
```

**Expected Result**
Expected rancher logs to be not spammed as if we have multiple clusters, we will see more of the info logs. 

**Describe the solution you'd like**
Move the logs to debug level, so the info level are not spammed with the events.

**Describe alternatives you've considered**
N/A

## PR's:

- [x] https://github.com/rancher/rancher/pull/42620
- [x] https://github.com/rancher/rancher/pull/42619

**Comment by richardcase** [comment]
@anupama2501 - this is expected behaviour as Rancher does a refresh of the upstream clusters periodically. By default, this is every 300 seconds for each cluster. This can be seen with these log entries from the sample you supplied:

```
2023/06/03 15:34:36 [INFO] checking cluster [c-vtm2p] upstream state for changes
```

And then 5 minutes later the same cluster:

```
2023/06/03 15:39:36 [INFO] checking cluster [c-vtm2p] upstream state for changes
```

So this is not a bug

**Comment by anupama2501** [comment]
@richardcase Thank you! I've updated the ticket to be an enhancement for the next milestone. Request was to move these events from info level to debug level.

**Comment by mjura** [comment]
This task is done
