### ISSUE TITLE
certificate update should trigger lb config update

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#4173]
@vincent99

**Comment by sangeethah** [comment]
Tested with server version v1.0.0-rc1

1. Created Lb service for 2 targets with ssl enabled listener using default certificate say - test2 - with domian-name test2.com.

2. Make sure that Lb service IP is accessible with certs for test1.

3. Update certificate - "test1" with new set of key and cert so the new domain name is test3.com.

When accessing  Lb service IP with old cert (from step1) , it is not accessible and following error is encountered:
```
ERROR: cannot verify <domains> certificate, issued by '/C=US/ST=CA/L=Cupertino
/O=rancher/OU=test/CN=test3.com/emailAddress=test3@abc.com':
  Self-signed certificate encountered.
    ERROR: certificate common name 'test3.com' doesn't match requested host name
 'test2.com'.
To connect to test2.com insecurely, use `--no-check-certificate'.
root@0d4ddd34219b:~#
```

Able to access  Lb service IP with new certs (for domian - test3.com) successfully.
