### ISSUE TITLE
[BUG] rancher basic function broke, seems cannot listen crd changes

### ISSUE THREAD

**Issue by boltdog2022** [rancher/rancher#41748]
**Rancher Server Setup**
- Rancher version: 2.7.0
- Installation option (Docker install/Helm Chart): start up the rancher in dev mode using source code
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details: self certificate according to official guide

**Information about the Cluster**
- Kubernetes version: 1.22
- Cluster Type (Local/Downstream): 1 local + 1 downstream (origin K8S)
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:
admin

**Describe the bug**

I was trying to add a user into an new created project, but it reports error like below
![image](https://github.com/rancher/rancher/assets/96976700/13601ccf-f097-4fcc-9c5a-7391077305a7)
I know creating 1 project will also create 1 namespace named by projectID. But in this situation, it seems something wrong with the listener? I m not sure if this issue is K8S issue or rancher issue.

And I checked the backend log, found some logs below
![image](https://github.com/rancher/rancher/assets/96976700/ef3c4459-82a3-47a8-a422-97777a1e911c)

1. closing watcher for xxxxx
2. unable to decode an event from the watch stream: http2: response body closed

I m not sure if these logs are related to this issue.
I did not notice this issue in v2.6, just found this issue in v2.7 recently.

I also test user creation.
In normal rancher, when creating a user, rancher will listen this new user, and create default cluster role for this user.  But in this bug situation, it seems rancher cannot listen this new user creation. Therefore, no default cluster role will be created for this user.

I have 2 environments on 2 PC.  Both using the same source code to start the rancher.
One environment does not have this issue.
The other one has this issue.

I don't know how to reproduce the issue. It seems this issue happens all of a sudden.
And if this issue happens, it cannot be repaired by restart rancher.

I tried to reset the K8S and then start the rancher (like reinstall the rancher), then the issue is gone. But after using a while, this issue happens again. 

I also searched known issues in rancher github, there is one issue very similar to this issue.
[BUG] Creating/deleting management resources cause resources to be unsubscribed #40558
the error log is same.

But still not sure if it is the same issue.

I think this a critical issue. Many basic function cannot use after issue happens, and restart operation cannot recover the rancher.

Can some experts help check if this issue like issue 40558 or this is a new issue.

**To Reproduce**

**Result**

**Expected Result**

**Screenshots**

**Additional context**

**Comment by richard-cox** [comment]
Some of those error messages are spurious and should hopefully be removed soon (see https://github.com/rancher/rancher/issues/40627).

https://github.com/rancher/rancher/issues/40558 is an expected result of a change of permissions (where resource watches are closed).

I've just tried creating a Project that contains an additional user as a member and this worked fine (Rancher ~2.7.5).

@boltdog2022 Can you provide some step by step instructions on how to recreate the bug?

Unfortunately I work UI side, so that's the only part I can assist with

**Comment by boltdog2022** [comment]
> 

Thanks anyway. I think this is a backend issue too.
