### ISSUE TITLE
Inherit variables from main Dockerfile to agent's Dockerfile

### ISSUE THREAD

**Issue by maxsokolovsky** [rancher/rancher#41741]
**Is your feature request related to a problem? Please describe.**
Related to https://github.com/rancher/rancher/issues/41730, which is a short-term solution to the problem of having to specify the pinned webhook version upstream (package/Dockerfile) and downstream (package/Dockerfile.agent).

The goal is to minimize the number of steps release captains need to take to prepare a release. The more things are automated, the better.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

SURE-6429

**Comment by anupama2501** [comment]
QA to validate:


<table>
    <tbody>
        <tr>
            <th>#</th>
            <th>Scenario</th>
            <th>Steps</th>
            <th>Status</th>
        </tr>
        <tr>
            <td>1</td>
            <td>Fresh install checks</td>
            <td>
                <ol>
                    <li>Create rancher server by setting the webhook version env as CATTLE_RANCHER_WEBHOOK_VERSION=2.0.4+up0.3.5</li>
                    <li>Verify local cluster webhook version is on the version specified above</li>
                    <li>Create a downstream cluster and verify the version on the downstream clusters is 2.0.4+up0.3.5</li>
                    <li>Verify the downstream cluster’s webhook has newer versions.</li>
                    <li>Upgrade the downstream clusters webhook version </li>
                    <li>Verify the webhook version is changed back to the version 2.0.4+up0.3.5 </li>
                </ol>
            </td>
            <td></td></tr>
       <tr>
         <td>2</td>
            <td>Fresh install checks</td>
            <td>
                <ol>
                    <li>Create rancher server by setting the webhook version - do not set the CATTLE_RANCHER_WEBHOOK_VERSION env var</li>
                    <li>Verify local cluster webhook version is the latest version.</li>
                    <li>Create a downstream cluster and verify the version on the downstream clusters is same as that of the local cluster.</li>
                    <li>Edit the cluster-agent and set the env var CATTLE_RANCHER_WEBHOOK_VERSION=2.0.4+up0.3.5</li>
<li>Verify the downstrem clusters webhook is not changed and stays at the latest rc version.</li>
<li>Verify the downstream cluster’s webhook has newer versions.</li>
<li>Upgrade the downstream clusters webhook version</li>
<li>Verify the webhook version is changed back to the version on the local cluster.</li>
              </ol> 
        </td>
       <td></td>
</tr>
<tr>
         <td>3</td>
            <td>Upgrade checks</td>
            <td>
                <ol>
                    <li>Create a rancher server on v2.7.5</li>
                    <li>Create a downstream cluster and verify the version on the downstream clusters</li>
                    <li>Upgrade rancher server and set the webhook version to CATTLE_RANCHER_WEBHOOK_VERSION=2.0.4+up0.3.5</li>
                    <li>Verify the version on the downstream clusters is 2.0.4+up0.3.5</li>
                    <li>Create a new downstream cluster and verify the version on the downstream is also 2.0.4+up0.3.5</li>
              </ol> 
        </td>
       <td></td>
</tr>
<tr>
         <td>4</td>
            <td>Hosted rancher checks - Fresh install checks</td>
            <td>
                <ol>
                    <li>Create a hosted rancher on v2.7-head</li>
                    <li>Create 2 downstream clusters on the server</li>
                    <li>verify the version of webhook on both the clusters</li>
                    <li>Install rancher on one of the clusters</li>
                    <li>Create a downstream cluster on the tenant server</li>
                    <li>Verify the webhook versions on both the clusters match the host webhook version.</li>
              </ol> 
        </td>
       <td></td>
</tr>
<tr>
<tr>
         <td>5</td>
            <td>Hosted rancher checks - Upgrade checks</td>
            <td>
                <ol>
                      <li>Create a hosted rancher on v2.7.5</li>
                      <li>Create 2 downstream clusters on the server</li>
                      <li>verify the version of webhook on both the clusters</li>
                      <li>Install rancher on one of the clusters</li>
                      <li>Create a downstream cluster on the tenant server</li>
                      <li>Verify the webhook versions on both the clusters.</li>
                       <li>Upgrade the host and verify the version on the downstream and the tenant</li>
                       <li>Tenant and the downstream on tenant should stay at 2.0.4+up0.3.5</li>
                       <li>Downstream cluster should have upgraded rancher version</li>
                       <li>Upgrade the tenant and verify the webhook version</li>
                       <li>Tenant and the downstream on tenant should have upgraded versions.</li>
              </ol> 
        </td>
       <td></td>
</tr>
<tr>
         <td>6</td>
            <td>Backup restore rollback via migration</td>
            <td>
                <ol>
              </ol> 
        </td>
       <td></td>
</tr>

**Comment by maxsokolovsky** [comment]
# QA Testing

## Use the default config

### Build Rancher for linux amd64

Build and package Rancher (and the agent) using our scripts.

Currently, the scripts assume the desired OS and architecture are those of the current system.
Thus, you'd need to adjust the scripts for linux amd64.
Prepend `GOOS=linux GOARCH=amd64` to the commands that build the agent and server binaries:
https://github.com/rancher/rancher/blob/befc0c8e912fd4287488d0db899156d54c6b9a76/scripts/build-agent#L21
https://github.com/rancher/rancher/blob/befc0c8e912fd4287488d0db899156d54c6b9a76/scripts/build-server#L27

Modify the `docker build` command invocations, so that they start as
`docker buildx build --platform linux/amd64` rather than `docker build`:
https://github.com/rancher/rancher/blob/befc0c8e912fd4287488d0db899156d54c6b9a76/scripts/package#L24
https://github.com/rancher/rancher/blob/befc0c8e912fd4287488d0db899156d54c6b9a76/scripts/package#L36

### Run scripts

Run `build` and `package`. Tag the resulting two images however you want and push them.

### Run your custom Rancher build with your custom agent

For Docker, run:
`docker run -d -p 80:80 -p 443:443 -e CATTLE_AGENT_IMAGE={your-agent-image} --privileged --name rancher {your-main-image}`

For an HA setup with Helm, specify the agent and main image as needed.

### Check component versions in a running Rancher instance

Ensure the version of the webhook deployed in the local cluster is one you find in the `build.yaml`. Same for the
fleet agent.

## Change the configuration

Change some configuration value in the `build.yaml` file. For example, change the version of `webhookVersion` to be
`2.0.4+up0.3.4`. Then run `go generate`. This causes all codegen programs to run, which is wasteful. Instead, you can
run just the program in `pkg/codegen/buildconfig/main.go`. As a result, your Git working area has two changed files:
the build.yaml file itself and `pkg/buildconfig/constants.go`.

Run the scripts again, tag and push the images. Repeat the previous test and ensure that the webhook deployed in the
local cluster is the one you specified in your configuration update.

**Comment by andreas-kupries** [comment]
As it is closed as completed should it still be in review ?

**Comment by maxsokolovsky** [comment]
Moved to Done, thanks for catching this.
