### ISSUE TITLE
Add azure-dns provider to rancher/external-dns

### ISSUE THREAD

**Issue by codedevote** [rancher/rancher#4174]
At the moment [rancher/external-dns](https://github.com/rancher/external-dns) does not have a provider supporting [azure-dns service](https://azure.microsoft.com/en-us/documentation/articles/dns-overview/). I understand that the azure team provides a [sdk for go ](https://github.com/Azure/azure-sdk-for-go) that is able to talk to the azure dns service. 
I have no prior Go experience, but from what I see, it should be possible to implement this provider. I could implement this provider, if you can help me get started. 
- Can you confirm that the azure dns service as well as the azure go sdk are suitable to implement this provider? If not, skip second point.
- I never wrote single line of Go code before, but from what I see, I am fine with the language. I just don't have a clue what development environment I need in order to be able to send a useful PR for you. Do you have a link on how to setup an environment needed to be able to contribute? Are the instructions on [rancher wiki](https://github.com/rancher/rancher/wiki) applying here?

**Comment by vincent99** [comment]
You basically just need to add a provider that implements these [5 basic CRUD methods](  https://github.com/rancher/external-dns/blob/master/providers/provider.go#L10-L16), which their SDK must have a way to do to do anything that resembles managing DNS...

For Go in general checkout the [tour](https://tour.golang.org/welcome/1) and then the [install docs](https://golang.org/doc/install), particular the part about setting up `$GOPATH` and putting all your code where it expects inside of there.

**Comment by guydou** [comment]
Hi guys, 

What is the status of this issue? Is there a way to configure Azure DNS with external DNS?

**Comment by alcaneo** [comment]
Hi Guys,

I implemented it for Azure as I needed as well.
Didn't make a lot of tests yet, but if you want to try it out and provide me feedback before I propose a PR next week, I'd appreciate it.

Add this catalog in Rancher settings to get access to Azure DNS service: https://github.com/nespresso/rancher-custom-catalog

The rest should be self explanatory, you need:
* A service principal
* A resource group
* A Zone DNS already configured with a domain (or subdomain delegation like in my case)

That should be it.

Cheers

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
