### ISSUE TITLE
[BUG] Fail to provision RKE2 cluster onto Harvester HCI

### ISSUE THREAD

**Issue by aleveille** [rancher/rancher#41758]
**Rancher Server Setup**
- Rancher version: v2.7.3
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): k3s
- Proxy/Cert Details: n/a

**Information about the Cluster**
- Kubernetes version: v1.25.10+k3s1
- Cluster Type (Local/Downstream): local

**User Information**
- What is the role of the user logged in? Admin

**Describe the bug**

When tryring to provision a RK2 cluster on Harvester, the provisioning fails to create the virtual machines on the infrastructure and this is the error message:

```yaml
failureMessage: >-
    Failure detected from referenced resource rke-machine.cattle.io/v1,
    Kind=HarvesterMachine with name "project-env-default-fae05684-wpd8k":
    Downloading driver from
    https://rancher.domain.com/assets/docker-machine-driver-harvester

    Doing /etc/rancher/ssl

    ls: cannot access 'docker-machine-driver-*': No such file or directory

    downloaded file  failed sha256 checksum

    download of driver from
    https://rancher.domain.com/assets/docker-machine-driver-harvester failed
  failureReason: CreateError
```

**To Reproduce**
This error happens every time for me. I'm not sure how to have anyone else reproduce this error.

**Result**
Cluster is not created (and fails to be "deleted").

**Expected Result**
The RKE2 cluster should be provisioned in Harvester.

**Additional context**
I'm using VLANs, if that could cause such an issue.

My Harvester nodes have their mgmt interfaces on a untagged VLAN-20 (VLAN set on the switch).
The Rancher VM runs as a virtual machine within Harvester and is using the tagged VLAN-20.

The Harvester nodes can successfully reach the Ranche VM on its port 443, and the Rancher VM can reach the Harvester nodes on their port 443.

The link mentionned in the error message (https://rancher.domain.com/assets/docker-machine-driver-harvester) successfully downloads a file from my laptop (local GNU sha256sum 9.3 of the file gives me `91771f30a7e9cb73805129a263d87058d6e5538ee201bc5704513a693615f535`)

**Comment by aleveille** [comment]
It was a DNS issue on the Rancher VM. It couldn't resolve `rancher.domain.com`, leading to the failure seen above.


> It's not DNS
> 
> There's no way it's DNS
> 
> It was DNS


https://external-preview.redd.it/SRVKUe2MGSCBVB56FwBzwFZE6uxGaNZ_Vknx5vioVAw.png?auto=webp&s=b21e5b8bde6eed10e5ef54a188ebf0840e0bf8b4

**Comment by gabrielbelli** [comment]
> It was a DNS issue on the Rancher VM. It couldn't resolve `rancher.domain.com`, leading to the failure seen above.
> 
> > It's not DNS
> > There's no way it's DNS
> > It was DNS
> 
> https://external-preview.redd.it/SRVKUe2MGSCBVB56FwBzwFZE6uxGaNZ_Vknx5vioVAw.png?auto=webp&s=b21e5b8bde6eed10e5ef54a188ebf0840e0bf8b4

How did you manage to solve it? I'm having the same problem!

**Comment by aleveille** [comment]
> > It was a DNS issue on the Rancher VM. It couldn't resolve `rancher.domain.com`, leading to the failure seen above.
> > > It's not DNS
> > > There's no way it's DNS
> > > It was DNS
> > 
> > 
> > https://external-preview.redd.it/SRVKUe2MGSCBVB56FwBzwFZE6uxGaNZ_Vknx5vioVAw.png?auto=webp&s=b21e5b8bde6eed10e5ef54a188ebf0840e0bf8b4
> 
> How did you manage to solve it? I'm having the same problem!

I changed the DNS resolvers on the Rancher virtual machine so that it could resolve the domain.

**Comment by gabrielbelli** [comment]
> I changed the DNS resolvers on the Rancher virtual machine so that it could resolve the domain.

Well, in my case the Rancher VM is in fact resolving DNS, but unfortunately when I make a cluster on Harvester via Rancher the nodes can't resolve DNS.
