### ISSUE TITLE
[BUG] Panic: indexer conflict: map[byPod:{}] when upgrading rancher from 2.7.1 to 2.7.2  

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#41757]
**Rancher Server Setup**
- Rancher version: 2.7.1
- Installation option (Docker install/Helm Chart): Helm chart 
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):  
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version:  
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Admin
  - If custom, define the set of permissions:

**Describe the bug**

When the customer tries to upgrade Rancher 2.7.1 -> 2.7.2, the Rancher pods get stuck in a restart loop, so Rancher is never usable. 

The following panic error shows in Rancher's logs:
```
panic: indexer conflict: map[byPod:{}]

goroutine 1800 [running]:
k8s.io/apimachinery/pkg/util/runtime.Must(...)
	/go/pkg/mod/k8s.io/apimachinery@v0.25.4/pkg/util/runtime/runtime.go:172
github.com/rancher/rancher/pkg/generated/controllers/catalog.cattle.io/v1.(*operationCache).AddIndexer(0xc00adc5bf0, {0x3f0d10e, 0x5}, 0x41ebaa8)
	/go/src/github.com/rancher/rancher/pkg/generated/controllers/catalog.cattle.io/v1/operation.go:247 +0xe5
github.com/rancher/rancher/pkg/controllers/dashboard/helm.RegisterOperations({0x4830500, 0xc008127dc0}, {0x4871610, 0xc00142e300}, {0x48561a0, 0xc00aa1c150}, {0x4853c38?, 0xc00aa1c1c0?})
	/go/src/github.com/rancher/rancher/pkg/controllers/dashboard/helm/operations.go:42 +0x1c6
github.com/rancher/rancher/pkg/controllers/dashboard/helm.Register({0x4830500, 0xc008127dc0}, 0xc000aa4280)
	/go/src/github.com/rancher/rancher/pkg/controllers/dashboard/helm/register.go:22 +0x2d8
github.com/rancher/rancher/pkg/controllers/dashboard.Register({0x4830500?, 0xc008127dc0}, 0xc000aa4280, 0xa0?, {0x0, 0x0})
	/go/src/github.com/rancher/rancher/pkg/controllers/dashboard/controller.go:25 +0x65
github.com/rancher/rancher/pkg/rancher.(*Rancher).Start.func1.1({0x4830500?, 0xc008127dc0?})
	/go/src/github.com/rancher/rancher/pkg/rancher/rancher.go:266 +0x45
github.com/rancher/rancher/pkg/wrangler.(*Context).StartWithTransaction(0xc000aa4280, {0x482fd90?, 0xc00331cf40}, 0xc00a645f58)
	/go/src/github.com/rancher/rancher/pkg/wrangler/context.go:182 +0xdf
github.com/rancher/rancher/pkg/rancher.(*Rancher).Start.func1({0x482fd90, 0xc00331cf40})
	/go/src/github.com/rancher/rancher/pkg/rancher/rancher.go:265 +0xd9
github.com/rancher/wrangler/pkg/leader.(*Manager).OnLeader.func1()
	/go/pkg/mod/github.com/rancher/wrangler@v1.1.0/pkg/leader/manager.go:51 +0x92
created by github.com/rancher/wrangler/pkg/leader.(*Manager).OnLeader
	/go/pkg/mod/github.com/rancher/wrangler@v1.1.0/pkg/leader/manager.go:48 +0x72
```

 
**To Reproduce**

 - run Rancher v2.7.1 in HA mode 
 - create a bunch of downstream clusters including  RKE2 (mostly), imported and RKE 
 - upgrade Rancher to v2.7.2 

**Result**

Rancher pods get stuck in a restart loop, and logs shows the `panic: indexer conflict: map[byPod:{}]` error 

**Expected Result**

Rancher is working properly after upgrading to 2.7.2

**Screenshots**

**Additional context**

- the issue is reproducible every time they attempt to upgrade from 2.7.1 to 2.7.2
- we saw mentioned stacktrace every 1-3 minutes after changing the version which was triggering pod restart
- rancher pods had access to a lot of memory and CPU (not a resource problem), we even tried to provide more resources, but it didn't help.
- the issue was also occurring with a single rancher pod (replicas=1) - We tried to scale down to only one replica.

SURE-6433

**Comment by jiaqiluo** [comment]
## Reproduce

The bug can be reproduced by upgrading Rancher from v2.7.1 to v2.7.2

There are two prerequisites to reproducing the bug:

1.  There is at least one downstream REK2 node-driver cluster in Rancher 
2. There is a process or program that keeps updating the above RKE2 cluster **outside or Rancher** 

To meet the 1st prerequisite, we must create a downstream REK2 node-driver cluster. 
To meet the 2nd prerequisite, the following bash script can be used to simulate the update outside of Rancher:
```
#!/bin/bash

x=1
while true
do
	kubectl -n fleet-default label cluster.provisioningr rke2 label-$x=$x
	kubectl -n fleet-default get cluster.provisioning rke2  -o yaml | grep label-$x
  echo "Update $x times"
  x=$(( $x + 1 ))
  sleep 0.01
done

```

### Steps:
- Install Rancher v2.7.1 in HA mode
- create a downstream REK2 node-driver cluster
- run the above bash script in one terminal window, then run the `helm upgrade` command to upgrade Rancher to v2.7.2  in another window 
- monitoring rancher logs 


### Results:

We will see the following error soon, then the panic error, in the logs:

`[ERROR] failed to call leader func: Operation cannot be fulfilled on clusters.provisioning.cattle.io "rke2": the object has been modified; please apply your changes to the latest version and try again`


## Root Cause 

Starting from Rancher v2.7.2, a new field [DynamicSchemaSpec](https://github.com/rancher/rancher/blob/32b5ffd41f698ce32c5cbe962c23d707b70a984e/pkg/apis/provisioning.cattle.io/v1/rke.go#L31) is added to the `RKEMachinePool` which can be found in the Provisioning Cluster object under `spec.rkeConfig.machinePools[*]`. 

When Rancher is upgrading, it migrates the existing Provisioning Cluster object, specifically for the RKE2 node-driver cluster,  to set the above-mentioned field.  The current implementation simply returns the error when it fails to update the cluster ([code](https://github.com/rancher/rancher/blob/32b5ffd41f698ce32c5cbe962c23d707b70a984e/pkg/rancher/migrations.go#L533-L536)). If another process or program updates the same cluster object simultaneously,  the upgrade will fail due to the conflict. The failure is escalated to be a panic eventually. 


## Workaround

Please check your environment to ensure no program other than Rancher is updating the provisioning cluster object during the Rancher-upgrading process.

**Comment by jiaqiluo** [comment]
This issue can be validated in the latest v2.7-head. 
Please check my previous comment for details.

**Comment by thaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.7-head dcfd5e1
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: RKE2

----------

### Testing: ###
Tested this issue with the following steps:
1. Create Rancher server on 2.7.1
2. Provision RKE2 aws node driver cluster
3. Run bash script to simulate the update outside of Rancher
```
#!/bin/bash

x=1
while true
do
    kubectl -n fleet-default label cluster.provisioningr rke2 label-$x=$x
    kubectl -n fleet-default get cluster.provisioning rke2  -o yaml | grep label-$x
  echo "Update $x times"
  x=$(( $x + 1 ))
  sleep 0.01
done
```
4. Run helm upgrade and upgrade Rancher to 2.7-head
5. Monitor Rancher logs as upgrade is running
6. Verify there are no errors similar to the one below
```
[ERROR] failed to call leader func: Operation cannot be fulfilled on clusters.provisioning.cattle.io "rke2": the object has been modified; please apply your changes to the latest version and try again
```

**Result**
Upgrade was successful and the errors are no longer reproducible on 2.7-head dcfd5e1.
