### ISSUE TITLE
Failed to launch a host in Ubuntu Desktop

### ISSUE THREAD

**Issue by syedalamabbas** [rancher/rancher#4175]
Rancher Version:Latest

Docker Version:Latest

OS: Ubuntu Desktop

Steps to Reproduce:
1. Install Ubuntu Desktop 14.04, 64, 8GB + 120GB Hard. 
2. Install Docker (I also tried additional Docker-Compose, Docker Machine, Docker Engine etc).
3. Install rancher server : sudo docker run -d --restart=always -p 8080:8080 rancher/server
4. Try adding custom host using : sudo docker run -d --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v0.10.0 http://localhost:8080/v1/scripts/4CC8CC0835115432DDB1:1459184400000:pVlY1DcUuBmCdffjaOrURnQpdo

Results:  No host added, no error message, no docker ps list entry (like rancher agent).

Expected: A New Host should pop up , just like it does with RancherOS (I tested with this operating system , all configurations work fine).

**Comment by deniseschannon** [comment]
@syedalamabbas What is the result of `docker ps -a`? Is there any containers that launched `rancher/agent`?

**Comment by syedalamabbas** [comment]
Yes, it appears to have exited. I did try to add host many times. 
The following output I get : 

```
CONTAINER ID        IMAGE                   COMMAND                  CREATED             STATUS                    PORTS                              NAMES
b3825c0ac76e        hello-world             "/hello"                 20 hours ago        Exited (0) 20 hours ago                                      backstabbing_perlman
416043c180ab        rancher/agent:v0.10.0   "/run.sh http://local"   20 hours ago        Exited (1) 20 hours ago                                      determined_booth
a79ded5d6eb0        rancher/agent:v0.10.0   "/run.sh http://local"   24 hours ago        Exited (1) 24 hours ago                                      suspicious_kirch
f4b3f38be8d4        rancher/agent:v0.10.0   "/run.sh http://local"   24 hours ago        Exited (1) 24 hours ago                                      awesome_ptolemy
ea977e0eeb19        rancher/agent:v0.10.0   "/run.sh http://local"   24 hours ago        Exited (1) 24 hours ago                                      prickly_babbage
c97fc7c31809        rancher/agent:v0.10.0   "/run.sh http://local"   24 hours ago        Exited (1) 24 hours ago                                      berserk_lovelace
8559da8d85e7        ubuntu                  "bash"                   24 hours ago        Exited (0) 24 hours ago                                      focused_jennings
10dc3762c79d        hello-world             "/hello"                 24 hours ago        Exited (0) 24 hours ago                                      small_bohr
34a45002c5fb        rancher/agent:v0.10.0   "/run.sh http://local"   24 hours ago        Exited (1) 24 hours ago                                      adoring_jang
05585683b07e        rancher/agent:v0.10.0   "/run.sh http://local"   24 hours ago        Exited (1) 24 hours ago                                      sleepy_feynman
bd74a994bacc        rancher/agent:v0.10.0   "/run.sh http://local"   24 hours ago        Exited (1) 24 hours ago                                      sick_blackwell
d8ecacb9d0bb        rancher/server          "/usr/bin/s6-svscan /"   24 hours ago        Up 2 minutes              3306/tcp, 0.0.0.0:8080->8080/tcp   myrancher_server
d3575f6e8d95        hello-world             "/hello"                 24 hours ago        Exited (0) 24 hours ago                                      big_goodall
35801326757b        hello-world             "/hello"                 25 hours ago        Exited (0) 25 hours ago                                      happy_kowalevski
20f368a2bb25        hello-world             "/hello"                 25 hours ago        Exited (0) 25 hours ago                                      serene_mahavira
e07124a516c1        hello-world             "/hello"                 25 hours ago        Exited (0) 25 hours ago                                      boring_galileo
```

**Comment by deniseschannon** [comment]
Can you get the logs? http://docs.rancher.com/rancher/faqs/agents/#where-can-i-find-detailed-logs-of-the-rancher-agent-container

**Comment by syedalamabbas** [comment]
`ubuntu@ubuntu:~$ docker ps -a
CONTAINER ID        IMAGE                   COMMAND                  CREATED             STATUS                     PORTS                              NAMES
8307366d4491        rancher/agent:v0.11.0   "/run.sh http://local"   5 minutes ago       Exited (1) 4 minutes ago                                      high_northcutt
1532b1526984        rancher/server          "/usr/bin/s6-svscan /"   8 minutes ago       Up 8 minutes               3306/tcp, 0.0.0.0:8080->8080/tcp   myrancher_server
35801326757b        hello-world             "/hello"                 25 hours ago        Exited (0) 25 hours ago                                       happy_kowalevski
20f368a2bb25        hello-world             "/hello"                 26 hours ago        Exited (0) 26 hours ago                                       serene_mahavira
e07124a516c1        hello-world             "/hello"                 26 hours ago        Exited (0) 26 hours ago                                       boring_galileo
ubuntu@ubuntu:~$ sudo docker logs -f 8307366d4491

INFO: Running Agent Registration Process, CATTLE_URL=http://10.173.214.229:8080/v1
INFO: Checking for Docker version >= 1.6.0
INFO: Found Server version: 1.10.3
INFO: docker version: Client version: 1.6.0
INFO: docker version: Client API version: 1.18
INFO: docker version: Go version (client): go1.4.2
INFO: docker version: Git commit (client): 4749651
INFO: docker version: OS/Arch (client): linux/amd64
INFO: docker version: Server version: 1.10.3
INFO: docker version: Server API version: 1.22
INFO: docker version: Go version (server): go1.5.3
INFO: docker version: Git commit (server): 20f81dd
INFO: docker version: OS/Arch (server): linux/amd64
INFO: docker info: Containers: 5
INFO: docker info: Images: 3
INFO: docker info: Storage Driver: aufs
INFO: docker info: Root Dir: /var/lib/docker/aufs
INFO: docker info: Backing Filesystem: extfs
INFO: docker info: Dirs: 29
INFO: docker info: Dirperm1 Supported: true
INFO: docker info: Execution Driver: native-0.2
INFO: docker info: Kernel Version: 3.19.0-25-generic
INFO: docker info: Operating System: Ubuntu 14.04.4 LTS
INFO: docker info: CPUs: 2
INFO: docker info: Total Memory: 7.781 GiB
INFO: docker info: Name: ubuntu
INFO: docker info: ID: DZRM:SWFY:EGTK:ZOYU:D7CL:Y2AP:3ZKV:6WUK:Y6GL:VAFG:D5G5:TUXU
INFO: docker info: Http Proxy:
INFO: docker info: Https Proxy:
INFO: docker info: No Proxy:
WARNING: No swap limit support
INFO: Attempting to connect to: http://10.173.214.229:8080/v1
INFO: http://10.173.214.229:8080/v1 is accessible
INFO: Inspecting host capabilities
INFO: System: false
INFO: Host writable: true
INFO: Token: xxxxxxxx
INFO: Running registration
Traceback (most recent call last):
  File "./register.py", line 11, in <module>
    secret_key=os.environ['CATTLE_REGISTRATION_SECRET_KEY'])
  File "/usr/local/lib/python2.7/site-packages/cattle.py", line 45, in from_env
    return gdapi.from_env(prefix=prefix, factory=Client, **kw)
  File "/usr/local/lib/python2.7/site-packages/gdapi.py", line 608, in from_env
    return _from_env(prefix=prefix, factory=factory, **args)
  File "/usr/local/lib/python2.7/site-packages/gdapi.py", line 627, in _from_env
    return factory(**result)
  File "/usr/local/lib/python2.7/site-packages/cattle.py", line 12, in __init__
    super(Client, self).__init__(*args, **kw)
  File "/usr/local/lib/python2.7/site-packages/gdapi.py", line 195, in __init__
    self._load_schemas()
  File "/usr/local/lib/python2.7/site-packages/gdapi.py", line 313, in _load_schemas
    response = self._get_response(self._url)
  File "/usr/local/lib/python2.7/site-packages/gdapi.py", line 262, in _get_response
    headers=self._headers)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 437, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /v1 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f98048ca310>: Failed to establish a new connection: [Errno 111] Connection refused',))
ubuntu@ubuntu:~$ 
`

**Comment by cjellick** [comment]
@syedalamabbas I see you have the registration url set to use "localhost". The initial rancher/agent container that you launch uses docker's default bridge networking, not host networking. So, "localhost" to that container is the container. So, it is not actually hitting the rancher server. You would want to set the host registration URL to the IP of the host where rancher server is running, which in this case would be the IP of your machine running Ubuntu Desktop.

**Comment by cjellick** [comment]
@sleepycat I see that you have a non-localhost ip in your run command:
```
docker run -d ... rancher/agent:v0.10.0 http://192.168.1.4:8080/v1/scripts/...
```

But I also see that the agent is attempting to connect to localhost:
```
...
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8080):...
```
so I'm wondering: did you manually change the ip in the run command after copying the command out of the UI or did you actually change the Host Registration URL on the Admin > Settings page? 

The behavior I see leads me to believe that you changed the URL after copying the command (or that we have a bug).

**Comment by syedalamabbas** [comment]
I did the host setting from local to its ip, and still the rancher agent shows exited. 

`ubuntu@ubuntu:~$ ifconfig
docker0   Link encap:Ethernet  HWaddr 02:42:d9:1b:51:a0  
          inet addr:172.17.0.1  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::42:d9ff:fe1b:51a0/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:5265 errors:0 dropped:0 overruns:0 frame:0
          TX packets:5276 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:1882281 (1.8 MB)  TX bytes:9653871 (9.6 MB)

eth0      Link encap:Ethernet  HWaddr 00:0c:29:1c:4e:d0  
          inet addr:10.173.214.229  Bcast:10.173.214.255  Mask:255.255.255.0
          inet6 addr: fe80::20c:29ff:fe1c:4ed0/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:69284 errors:0 dropped:1 overruns:0 frame:0
          TX packets:12070 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:31322845 (31.3 MB)  TX bytes:1757861 (1.7 MB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:9880 errors:0 dropped:0 overruns:0 frame:0
          TX packets:9880 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:8335508 (8.3 MB)  TX bytes:8335508 (8.3 MB)

veth3b1e82f Link encap:Ethernet  HWaddr b2:bb:8f:a0:e7:b8  
          inet6 addr: fe80::b0bb:8fff:fea0:e7b8/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:5233 errors:0 dropped:0 overruns:0 frame:0
          TX packets:5295 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:1953200 (1.9 MB)  TX bytes:9655681 (9.6 MB)

ubuntu@ubuntu:~$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                        NAMES
e2bced3c1c05        rancher/server      "/usr/bin/s6-svscan /"   5 minutes ago       Up 5 minutes        3306/tcp, 8080/tcp, 0.0.0.0:8081->8081/tcp   determined_leakey
ubuntu@ubuntu:~$ sudo docker run -d --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v0.11.0 http://10.173.214.229:8081/v1/scripts/4392EDD1C877C5D5006E:1459378800000:V2Yey726Bg2cCIBiLfOZzmhhO0
[sudo] password for ubuntu: 
b09ffbd7cc643755eb01d2248f52ab3ecba157122323a221e14784b9596a5643
ubuntu@ubuntu:~$ docker ps -a
CONTAINER ID        IMAGE                   COMMAND                  CREATED             STATUS                     PORTS                                        NAMES
b09ffbd7cc64        rancher/agent:v0.11.0   "/run.sh http://10.17"   11 seconds ago      Exited (1) 9 seconds ago                                                high_varahamihira
8852ed24abfe        rancher/agent:v0.11.0   "/run.sh http://10.17"   2 minutes ago       Exited (1) 2 minutes ago                                                agitated_babbage
e2bced3c1c05        rancher/server          "/usr/bin/s6-svscan /"   5 minutes ago       Up 5 minutes               3306/tcp, 8080/tcp, 0.0.0.0:8081->8081/tcp   determined_leakey
18e1d3da289a        rancher/server          "/usr/bin/s6-svscan /"   6 minutes ago       Created                                                                 furious_kirch
6e9ac3a9870d        rancher/server          "/usr/bin/s6-svscan /"   6 minutes ago       Created                                                                 backstabbing_lumiere
ubuntu@ubuntu:~$ 

`

**Comment by cjellick** [comment]
@syedalamabbas can you share the logs for the instance that was started with the 192 address in the registration URL?

**Comment by syedalamabbas** [comment]
```
ubuntu@ubuntu:~$ sudo docker -logs b09ffbd7cc64 
[sudo] password for ubuntu: 
flag provided but not defined: -logs
See 'docker --help'.
ubuntu@ubuntu:~$ sudo docker -logs -f b09ffbd7cc64 
flag provided but not defined: -logs
See 'docker --help'.
ubuntu@ubuntu:~$ sudo docker logs -f b09ffbd7cc64

INFO: Running Agent Registration Process, CATTLE_URL=http://10.173.214.229:8081/v1
INFO: Checking for Docker version >= 1.6.0
INFO: Found Server version: 1.10.3
INFO: docker version: Client version: 1.6.0
INFO: docker version: Client API version: 1.18
INFO: docker version: Go version (client): go1.4.2
INFO: docker version: Git commit (client): 4749651
INFO: docker version: OS/Arch (client): linux/amd64
INFO: docker version: Server version: 1.10.3
INFO: docker version: Server API version: 1.22
INFO: docker version: Go version (server): go1.5.3
INFO: docker version: Git commit (server): 20f81dd
INFO: docker version: OS/Arch (server): linux/amd64
WARNING: No swap limit support
INFO: docker info: Containers: 5
INFO: docker info: Images: 3
INFO: docker info: Storage Driver: aufs
INFO: docker info: Root Dir: /var/lib/docker/aufs
INFO: docker info: Backing Filesystem: extfs
INFO: docker info: Dirs: 29
INFO: docker info: Dirperm1 Supported: true
INFO: docker info: Execution Driver: native-0.2
INFO: docker info: Kernel Version: 3.19.0-25-generic
INFO: docker info: Operating System: Ubuntu 14.04.4 LTS
INFO: docker info: CPUs: 2
INFO: docker info: Total Memory: 7.781 GiB
INFO: docker info: Name: ubuntu
INFO: docker info: ID: DZRM:SWFY:EGTK:ZOYU:D7CL:Y2AP:3ZKV:6WUK:Y6GL:VAFG:D5G5:TUXU
INFO: docker info: Http Proxy:
INFO: docker info: Https Proxy:
INFO: docker info: No Proxy:
INFO: Attempting to connect to: http://10.173.214.229:8081/v1
INFO: http://10.173.214.229:8081/v1 is accessible
INFO: Inspecting host capabilities
INFO: System: false
INFO: Host writable: true
INFO: Token: xxxxxxxx
INFO: Running registration
Traceback (most recent call last):
  File "./register.py", line 11, in <module>
    secret_key=os.environ['CATTLE_REGISTRATION_SECRET_KEY'])
  File "/usr/local/lib/python2.7/site-packages/cattle.py", line 45, in from_env
    return gdapi.from_env(prefix=prefix, factory=Client, **kw)
  File "/usr/local/lib/python2.7/site-packages/gdapi.py", line 608, in from_env
    return _from_env(prefix=prefix, factory=factory, **args)
  File "/usr/local/lib/python2.7/site-packages/gdapi.py", line 627, in _from_env
    return factory(**result)
  File "/usr/local/lib/python2.7/site-packages/cattle.py", line 12, in __init__
    super(Client, self).__init__(*args, **kw)
  File "/usr/local/lib/python2.7/site-packages/gdapi.py", line 195, in __init__
    self._load_schemas()
  File "/usr/local/lib/python2.7/site-packages/gdapi.py", line 313, in _load_schemas
    response = self._get_response(self._url)
  File "/usr/local/lib/python2.7/site-packages/gdapi.py", line 262, in _get_response
    headers=self._headers)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 437, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8081): Max retries exceeded with url: /v1 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f2e4cec4310>: Failed to establish a new connection: [Errno 111] Connection refused',))

```

**Comment by sleepycat** [comment]
@cjellick: bang on. I changed the host registration URL and now everything works.
:+1: 

Maybe the default host registration URL should be the container IP or the host IP.

**Comment by cjellick** [comment]
@sleepycat glad you got it straightened out. it defaults to the url on which you hit the UI, which is the best guess we can make.

**Comment by tiger2wander** [comment]
Caused localhost:8080, so this url will not reachable from agent container as it is 'another localhost', it should change the launch agent command with host's LAN IP or rancher/server's container ip.

**Comment by rkpujari10** [comment]
Thanks. You guys saved my time.

**Comment by deniseschannon** [comment]
@syedalamabbas Are you still facing this issue?

**Comment by Halfwalker** [comment]
Hrm - I seem to be hitting the same issue.  Ubuntu 16.04 virtualbox host on `192.168.2.147`, docker installed from the repo, and started with `docker run -d --restart=always -p 8080:8080 rancher/server`

The host is `installerbox.local` and I've added `192.168.2.147 installerbox.local installerbox` to the /etc/hosts file (although after starting rancher/server)

Adding a host with `docker run -e CATTLE_AGENT_IP="192.168.2.147"  -d --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.0.2 http://installerbox.local:8080/v1/scripts/AC930440DDBD289B6B2F:1472248800000:q8L8MU8hKeTXFU7GLdynoBSrrM`

That results in 

> INFO: Attempting to connect to: http://installerbox.local:8080/v1
> ERROR: http://installerbox.local:8080/v1 is not accessible

I can hit that url just fine though ...  If I change the registration URL to use `192.168.2.147` instead of `installerbox.local` it fails with a slightly different stack trace :
>requests.exceptions.ConnectionError: HTTPConnectionPool(host='installerbox.local', port=8080): Max retries exceeded with url: /v1 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f1c86390e10>: Failed to establish a new connection: [Errno -2] Name or service not known',))

I can hit the registration url just fine from my desktop and from the virtualbox host with wget.

**Comment by vincent99** [comment]
@Halfwalker Containers (like the agent) do not inherit the `/etc/hosts` entries from the machine Docker is running on.

**Comment by Halfwalker** [comment]
Ah, OK.  So how do I modify the registration url then ?  It already has the 192.168.2.147 in to replace installerbox.local.

**Comment by Halfwalker** [comment]
Ah, got it I think.  Went into Settings and changed the Host Registration URL to use the IP address.  Then the docker run seems to have worked.

Cool.  Exploring now.

**Comment by deniseschannon** [comment]
It seems like most everyone's issues regarding this has been resolved. If anyone has issues around this specific use case, please open a new issue.
