### ISSUE TITLE
[BUG] air-gap rancher still trying to reach internet

### ISSUE THREAD

**Issue by WeAreHadock** [rancher/rancher#41765]
**Rancher Server Setup**
- Rancher version: v2.7.3
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version: rke2 1.25.8

**Information about the Cluster**
- Kubernetes version: 1.25.8
- Cluster Type (Local/Downstream): Local and rancher managed downstream

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Admin

**Describe the bug**
When rancher is deployed in air gapped env (`useBundledSystemChart: true` in the helm chart values), It still make requests to the internet when loading logos from charts on `https://<rancher url>/dashboard/c/<cluster id>/apps/charts`. This leads to two issues:
- Apps logo are not displayed.
- A request is made from the server hosting rancher to a public IP, which can trigger alerts from security tools

**To Reproduce**
- deploy rancher with `useBundledSystemChart: true` in an air-gapped env
- create an air-gapped rke2 downstream cluster
- go on the Apps page of the downstream cluster. 
- check the logs from cattle-cluster-agent pod

**Result**

Logos are not displayed: See screenshot below

When the Apps page is opened, we can see the following logs in the cattle-clusuter-agent pod:
`time="2023-06-07T11:51:42Z" level=error msg="Unknown error: Get \"https://raw.githubusercontent.com/CrowdStrike/falcon-helm/main/images/crowdstrike-logo.svg\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
time="2023-06-07T11:51:42Z" level=error msg="Unknown error: Get \"https://github.com/hashicorp/vault/raw/f22d202cde2018f9455dec755118a9b84586e082/Vault_PrimaryLogo_Black.png\": dial tcp 140.82.121.3:443: i/o timeout (Client.Timeout exceeded while awaiting headers)"`
for every chart.

**Expected Result**
Logos are displayed or there is no request trying to gather them from internet.

**Screenshots**
![image](https://github.com/rancher/rancher/assets/52026113/b22eb115-9a63-4f4e-bb9e-2f87ecace103)

**Additional context**

**Comment by yamansama** [comment]
Hi
Same issue here (internal support request 00699699).

Rancher Server Setup
- Rancher version: v2.7.4
- Installation option (Docker install/Helm Chart): Helm
  - If Helm Chart, Kubernetes Cluster and version: rke2 1.25.11
 
Information about the Cluster

Kubernetes version: 1.25.11
Cluster Type (Local/Downstream): Local and rancher managed downstream

**Comment by KaliMist777** [comment]
hello , i have same problem , im using proxy for internet but maybe im not doing configuration right can someone help?

**Comment by nicholasSUSE** [comment]
Hello, @KaliMist777 , @yamansama , @WeAreHadock , @HectorB-2020  
I have been working on the fix for this issue.
The PR is open and waiting for reviews, thank you for reporting it.
https://github.com/rancher/rancher/pull/43909

**Comment by nicholasSUSE** [comment]
This is resolved. 
Will be release on Rancher v2.8.3 probably: https://github.com/rancher/rancher/pull/43909
