### ISSUE TITLE
Update ACI-CNI to 5.2.7.1

### ISSUE THREAD

**Issue by LavanyaVaddavalli** [rancher/rancher#41762]
There is ACI CNI version 5.2.7.1 available which is an upgrade to 5.2.3.6 we currently have included in KDM for RKE1 provisioned clusters

**Comment by snasovich** [comment]
@LavanyaVaddavalli , the PRs have been merged and RKE `v1.4.6-rc4` has the changes in. Could you please confirm it's working as expected for you?

**Comment by markusewalker** [comment]
From QA's perspective, we are good on this. Running our RKE1 regression test suite passed as expected and I validated that the ACI-CNI values were updated.

**Comment by siva-muni** [comment]
@snasovich, testing is done. we found only one issue, @LavanyaVaddavalli posted PR https://github.com/rancher/kontainer-driver-metadata/pull/1163, this  is fix for the issue.

**Comment by snasovich** [comment]
The changes requested above were merged and new RKE1 RC cut with the fix. No non-ACI related retesting is needed. The issue is ready to be closed.

**Comment by markusewalker** [comment]
Following the [comment](https://github.com/rancher/rancher/issues/41762#issuecomment-1602970684) above, QA will go ahead and close this issue as resolved.
