### ISSUE TITLE
[BUG] Allow Steve to handle generated fields.

### ISSUE THREAD

**Issue by KevinJoiner** [rancher/rancher#41772]
**Rancher Server Setup**
- Rancher version: v2.7.x
- Installation option (Docker install/Helm Chart): N/A

**Information about the Cluster**
- Kubernetes version: 1.25 <
- Cluster Type (Local/Downstream): N/A

**Describe the bug**
When Steve returns requested resources it adds extra information on objects that does exist in ETCd [via a Formatter](https://github.com/rancher/steve/blob/master/pkg/resources/common/formatter.go#L98-L108)

When a user attempts to update the new object kube-apiserver. Warnings are returned for adding unknown fields.
```
299 - unknown field "metadata.fields"
299 - unknown field "metadata.relationships"
299 - unknown field "metadata.state"
299 - unknown field "status.conditions[0].error"
299 - unknown field "status.conditions[0].transitioning"
299 - unknown field "status.conditions[1].error"
299 - unknown field "status.conditions[1].transitioning"
```
**To Reproduce**
Request a running pod via Steve `/v1/pods`
Add a new label to the pod
Attempt to persist the updated pod via Steve or kubectl.

**Result**
Notice that Warnings are returned.

**Expected Result**

No Warnings are returned.

**Additional context**

These warnings are now  sent by default in K8s  >= 1.25 due to https://kubernetes.io/docs/reference/using-api/api-concepts/#validation-for-unrecognized-or-duplicate-fields-setting-the-field-validation-level

It is possible for Steve to remove these added fields when updating an object.
This does not handle the use case where a user get's an object from the UI's yaml view and then attempts to use it elsewhere. It would be helpful if we documented which fields are added by Steve so the UI can strip them when displaying  YAML to a Users.

This is related to https://github.com/rancher/dashboard/issues/9016
And can cause failed messages, such as seen here https://github.com/rancher/dashboard/issues/9012

**Comment by brudnak** [comment]
# ❌ REOPENED

## Reproduction Environment


| Component                        | Version / Type           |
| -------------------------------- | ------------------------ |
| Rancher version                  | 2.7.4                    |
| Installation option              | Helm (high availability) |
| RKE binary version used          | 1.4.4                    |
| If Helm Chart k8s cluster        | 1.25.6                   |
| Cert Details                     | external tls             |
| Docker version                   | 20.10.7, build f0df350   |
| Helm version                     | v2.16.8-rancher2         |
| Downstream cluster type          | Linode RKE1              |
| Downstream K8s version           | v1.26.6-rancher1-1       |
| Authentication providers enabled | local                    |
| Logged in user role              | admin, standard user     |
| Browser type                     | Microsoft Edge           |
| Browser version                  | 114.0.1823.82            |

## Reproduction steps

1. Create a config map named `test-cm-1`
2. Provide the following data:
   - key: `foo`
   - value: `bar`
3. Save the config map
4. Once seted edit the conifg and add a label
5. Label that was added:
   - key: `test-key`
   - value: `test-value`
6. Make sure the browser network tab is opened before saving and submiting the request
7. After saving check the network tab in the browser for the response headers
8. See the following:

```txt
Warning:
299 - unknown field "metadata.fields"
Warning:
299 - unknown field "metadata.relationships"
Warning:
299 - unknown field "metadata.state"
```

## Additional Info

## Reproduction Results

### ✅ (Reproduction) Expected

For these unknown fields to be dropped before the `PUT` request goes through

### ❌ (Reproduction) Actual

These unknown fields are going through causing these warnings in the response header

## Validation Environment


| Component                        | Version / Type                                                                     |
| -------------------------------- | ---------------------------------------------------------------------------------- |
| Rancher version                  | v2.7-67422772955d5830b237fe84dbf1a26d266b55c1-head                                 |
| Rancher commit link              | https://github.com/rancher/rancher/commit/67422772955d5830b237fe84dbf1a26d266b55c1 |
| Installation option              | Helm (high availability)                                                           |
| RKE binary version used          | 1.4.4                                                                              |
| If Helm Chart k8s cluster        | 1.25.6                                                                             |
| Cert Details                     | external tls                                                                       |
| Docker version                   | 20.10.7, build f0df350                                                             |
| Helm version                     | v2.16.8-rancher2                                                                   |
| Downstream cluster type          | Linode RKE1                                                                        |
| Downstream K8s version           | v1.26.6-rancher1-1                                                                 |
| Authentication providers enabled | local                                                                              |
| Logged in user role              | admin, standard user                                                               |
| Browser type                     | Microsoft Edge                                                                     |
| Browser version                  | 114.0.1823.82                                                                      |

## Validation steps

1. Create a config map named `test-cm-1`
2. Provide the following data:
   - key: `foo`
   - value: `bar`
3. Save the config map
4. Once seted edit the conifg and add a label
5. Label that was added:
   - key: `test-key`
   - value: `test-value`
6. Make sure the browser network tab is opened before saving and submiting the request
7. After saving check the network tab in the browser for the response headers
8. See the following:

```txt
299 - unknown field "__clone"
```

## The Payload the UI Sent

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm-1
  annotations:
    {}
    #  key: string
  creationTimestamp: <REDACTED>
  labels:
    foo: bar
    #  key: string
  namespace: default
  resourceVersion: <REDACTED>
  uid: 
  fields:
    - foo
    - 1
    - 0s
data:
  foo: bar
  #  key: string
__clone: true
#binaryData:  key: string
#immutable: boolean
```

## RESULTS

### ✅ (Validation) Expected

For there not to be response header warnings 299

### ❌ (Validation) Actual

Getting response header warning: `299 - unknown field "__clone"`

**Comment by cmurphy** [comment]
Moving back to to-test, the UI should address the remaining fields in https://github.com/rancher/dashboard/issues/9371

**Comment by brudnak** [comment]
# ✅ PASS

<details>
    <summary>Reproduction details... Click to expand</summary>


| Component                        | Version / Type           |
| -------------------------------- | ------------------------ |
| Rancher version                  | 2.7.4                    |
| Installation option              | Helm (high availability) |
| RKE binary version used          | 1.4.4                    |
| If Helm Chart k8s cluster        | 1.25.6                   |
| Cert Details                     | external tls             |
| Docker version                   | 20.10.7, build f0df350   |
| Helm version                     | v2.16.8-rancher2         |
| Downstream cluster type          | Linode RKE1              |
| Downstream K8s version           | v1.26.6-rancher1-1       |
| Authentication providers enabled | local                    |
| Logged in user role              | admin, standard user     |
| Browser type                     | Microsoft Edge           |
| Browser version                  | 114.0.1823.82            |

## Reproduction steps

1. Create a config map named `test-cm-1`
2. Provide the following data:
   - key: `foo`
   - value: `bar`
3. Save the config map
4. Once seted edit the conifg and add a label
5. Label that was added:
   - key: `test-key`
   - value: `test-value`
6. Make sure the browser network tab is opened before saving and submiting the request
7. After saving check the network tab in the browser for the response headers
8. See the following:

```txt
Warning:
299 - unknown field "metadata.fields"
Warning:
299 - unknown field "metadata.relationships"
Warning:
299 - unknown field "metadata.state"
```

## Additional Info

## Reproduction Results

### ✅ (Reproduction) Expected

For these unknown fields to be dropped before the `PUT` request goes through

### ❌ (Reproduction) Actual

These unknown fields are going through causing these warnings in the response header

</details>

## Validation Environment


| Component                        | Version / Type                                                                     |
| -------------------------------- | ---------------------------------------------------------------------------------- |
| Rancher version                  | v2.7-67422772955d5830b237fe84dbf1a26d266b55c1-head                                 |
| Rancher commit link              | https://github.com/rancher/rancher/commit/67422772955d5830b237fe84dbf1a26d266b55c1 |
| Installation option              | Helm (high availability)                                                           |
| RKE binary version used          | 1.4.4                                                                              |
| If Helm Chart k8s cluster        | 1.25.6                                                                             |
| Cert Details                     | external tls                                                                       |
| Docker version                   | 20.10.7, build f0df350                                                             |
| Helm version                     | v2.16.8-rancher2                                                                   |
| Downstream cluster type          | Linode RKE1                                                                        |
| Downstream K8s version           | v1.26.6-rancher1-1                                                                 |
| Authentication providers enabled | local                                                                              |
| Logged in user role              | admin, standard user                                                               |
| Browser type                     | Microsoft Edge                                                                     |
| Browser version                  | 114.0.1823.82                                                                      |

## Validation steps

1. Create a config map named `test-cm-1`
2. Provide the following data:
   - key: `foo`
   - value: `bar`
3. Save the config map
4. Once seted edit the conifg and add a label
5. Label that was added:
   - key: `test-key`
   - value: `test-value`
6. Make sure the browser network tab is opened before saving and submiting the request
7. After saving check the network tab in the browser for the response headers
8. See the following:

## The Payload the UI Sent

## RESULTS

### ✅ (Validation) Expected

299 Warnings covered in the PR are not present

### ✅  (Validation) Actual

299 Warnings covered in the PR are not present

**Comment by cmurphy** [comment]
# Release note template

**Synopsis of issue**: Warnings about "unknown field" appeared in the UI when updating any Kubernetes object for Kubernetes versions 1.25 and up.
**Resolved (or not)**: resolved
**Versions**: 2.7.0-2.7.6

**Comment by richard-cox** [comment]
@Shavindra Those are dashboard added properties and should not be sent when creating resource. We don't want to send anything that's not listed in the spec. For instance for `containers` see https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#pod-v1-core --> 
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#container-v1-core
