### ISSUE TITLE
[RFE] Single sign-out (SSO) Keycloak

### ISSUE THREAD

**Issue by huy8114644** [rancher/rancher#41774]
I've tried integrating SSO with Keycloak using both SAML and OIDC, but when I logout from Rancher, the session on Keycloak is not being invalidated. Does Rancher support Single Sign-Out, or am I missing something in my configuration?

**Comment by rieger07** [comment]
This issue is biting me as well. If someone can point me in the right direction, I'd be happy to contribute a solution.
