### ISSUE TITLE
Slow internal name resolution

### ISSUE THREAD

**Issue by retardtank** [rancher/rancher#4177]
Rancher Version: v0.63.1

Docker Version: 1.10.3, build 20f81dd

OS: Debian GNU/Linux 8 (jessie)

Steps to Reproduce: resolve an internal name

Results: slow internal name resolution

Expected: fast internal name resolution

From inside one of the containers:
```
/usr/src/app # cat /etc/resolv.conf 
search tv2-jukebox.rancher.internal asset.tv2-jukebox.rancher.internal rancher.internal
nameserver 169.254.169.250
```

```
/usr/src/app # time wget -O - http://db:5984
Connecting to db:5984 (10.42.174.24:5984)
{"couchdb":"Welcome","uuid":"bb8fb832bdebabe9925fbcf6b9dba5a8","version":"1.6.1","vendor":{"version":"1.6.1","name":"The Apache Software Foundation"}}
-                    100% ...
real	0m 5.00s
...
```

```
/usr/src/app # time wget -O - http://10.42.174.24:5984
Connecting to 10.42.174.24:5984 (10.42.174.24:5984)
{"couchdb":"Welcome","uuid":"bb8fb832bdebabe9925fbcf6b9dba5a8","version":"1.6.1","vendor":{"version":"1.6.1","name":"The Apache Software Foundation"}}
-                    100%  ...
real	0m 0.00s
...
```

External domains resolves just fine and local ping times are low, any steps that can be taken to further debug this?

Thanks.

**Comment by vincent99** [comment]
@retardtank Can you try v1.0.0-rc6, there's a bunch of changes made since 0.63 for DNS performance.

**Comment by ronag** [comment]
@vincent99: Same problem...

**Comment by retardtank** [comment]
Unfortunately the problem still persists with v1.0.0-rc6. Copied the db from the old rancher server, wiped all containers and rancher images. Then started v1.0.0-rc6 with the db directory bind mounted...

**Comment by HardcorEViruS** [comment]
I experience the same problem with an Alpine Linux image (which is the new default base image of Docker). The name resolution seems to get an timeout for the pure hostname after 5 seconds, causing it to try hostname.stack.rancher.internal which succeeds.
Ubuntu on the other side (14.04 and 15.10) works just fine.

**Comment by retardtank** [comment]
@HardcorEViruS Yes. That became our solution too, but just adding the stack was enough (db -> db.jukebox). Though it has worked fine before using Alpine images as well, I guess it's circumstantial to the network environment. This particular setup is on a closed network (behind a corporate proxy) which we don't have much control of, and exactly the same setup has no issues on aws, etc...

**Comment by HardcorEViruS** [comment]
@retardtank I tested it in the same stack at the same time with an Alpine and the two Ubuntu images and the Alpine one had the delay while the Ubuntu ones didn't. Unfortunately in our case it is not a solution to append the stack as this would

**Comment by retardtank** [comment]
This is likely caused by the way the musl-libc (which Alpine uses) resolver works, combined with (I guess) how the DNS servers on the network which this setup is on is configured. I kind of knew of the musl-libc resolver, but initially missed to take that into account for this case. Workaround is to not use local names for queries or images based on systems that uses musl-libc (Alpine! :D)...

Thanks.

**Comment by richfelker** [comment]
This is a bug in rancher-dns. Specifically, it returns ServFail rather than NxDomain when the requested name does not exist. ServFail is not an answer as to whether the name exists or not, just an indication that something went wrong on the nameserver attempting to resolve it, so musl continues to retry until it times out. The offending code is at:

https://github.com/rancher/rancher-dns/blob/master/main.go#L406

See also the definition of dns.HandleFailed:

https://github.com/miekg/dns/blob/4744e915eb51a9defb5fb13c24ce2c8408d2fd98/server.go#L90
