### ISSUE TITLE
rancher-alerting-drivers k8s 1.27 chart support (Infracloud)

### ISSUE THREAD

**Issue by gunamata** [rancher/rancher#41785]
This issue is to implement the chart changes & perform the testing required to upgrade to k8s 1.27. Please perform below steps. 

- [ ] Check whether the chart has any references to the below deprecated features of k8s 1.27. You can find information about deprecated APIs here on [Kubernetes Deprecation guide](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-27).

**storage.k8s.io/v1beta1** API version of **CSIStorageCapacity**
 

- [ ] Update kube-version annotation in Chart.yaml. catalog.cattle.io/kube-version: '>= 1.23.0-0 < 1.28.0-0'

Note: If this is an upstream chart and if the upstream chart doesn't support k8s 1.27 then do not update the kube-version annotation or update the k8s version accordingly.

- [ ] Perform below tests

- Fresh install/uninstall/upgrade/downgrade of the charts on K8s 1.27 provisioned on Rancher. Test the chart functionality.
(Please refer to the https://github.com/rancher/rancher/issues/41395 to know what testing was done for k8s 1.26 upgrade for your chart)
- Provision rancher on k8s 1.26 or lesser
- Install chart on this cluster
- Upgrade this cluster in rancher to k8s 1.27
- Make sure the existing chart and the app is functional after cluster upgrade

**Comment by gunamata** [comment]
@mitulshah-suse , I think it's your team who would be picking up this task. I see it's marked for triaging at the moment. Please let me know if you need any info to get started on this.

**Comment by mitulshah-suse** [comment]
@gunamata I believe we need to wait for the K8s 1.27 support to be added to rancher before we can proceed with this, since this needs 1.27 clusters to be tested on.
But we can definitely pick it up as and when that happens.

**Comment by gunamata** [comment]
@mitulshah-suse , Are you blocked by something to test this ?

**Comment by mitulshah-suse** [comment]
@gunamata Not blocked on anything as such. Just dont have QA bandwidth to test it this week. Will probably be tested sometime next week.

**Comment by rishabhmsra** [comment]
Tested rancher alerting drivers chart on k8s v1.27 on rancher v2.8-head(675a0e4)

Tested as follows.
- Fresh install/uninstall/upgrade:
  - Installed monitoring chart version `103.0.0+up40.1.2`.
  - Installed alerting drivers chart version `103.0.0`
  - Validated the chart functionality and it's working as expected.
- Provisioned k8s v1.26. Installed chart on a cluster and validated the alerting functionality
  - Made sure chart is working as expected.
  - Upgraded the cluster in to k8s v1.27.
  - Made sure the existing chart and the app is functional after cluster upgrade.

Also tested the chart on below k8s v1.27 clusters:
- RKE2
- RKE2 hardened
- k3s
- k3s hardened
- custom
- imported

All validations passed, hence closing the issue.
