### ISSUE TITLE
k8s 1.27 support for system-upgrade-controller chart

### ISSUE THREAD

**Issue by gunamata** [rancher/rancher#41791]
This issue is to implement the chart changes & perform the testing required to upgrade to k8s 1.27. Please perform below steps. 

- [ ] Check whether the chart has any references to the below deprecated features of k8s 1.27. You can find information about deprecated APIs here on [Kubernetes Deprecation guide](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-27).

**storage.k8s.io/v1beta1** API version of **CSIStorageCapacity**
 

- [ ] Update kube-version annotation in Chart.yaml. catalog.cattle.io/kube-version: '>= 1.23.0-0 < 1.28.0-0'

Note: If this is an upstream chart and if the upstream chart doesn't support k8s 1.27 then do not update the kube-version annotation or update the k8s version accordingly.

- [ ] Perform below tests

- Fresh install/uninstall/upgrade/downgrade of the charts on K8s 1.27 provisioned on Rancher. Test the chart functionality.
(Please refer to the https://github.com/rancher/rancher/issues/41395 to know what testing was done for k8s 1.26 upgrade for your chart)
- Provision rancher on k8s 1.26 or lesser
- Install chart on this cluster
- Upgrade this cluster in rancher to k8s 1.27
- Make sure the existing chart and the app is functional after cluster upgrade

**Comment by thatmidwesterncoder** [comment]
### Root cause
k8s 1.27 not supported in the version of the chart

### What was fixed, or what changes have occurred
chart version bumped and included a change to include all versions up to 1.28
 
### Areas or cases that should be tested
deploying on a k8s cluster v1.27 should be supported once all of rancher supports it

### What areas could experience regressions?
n/a
  
### Are the repro steps accurate/minimal?
n/a

**Comment by Josh-Diamond** [comment]
Ticket #41511 - Test Results - ✅ 
---

Verified with HA Helm Rancher on `v2.8-efc48ac09ab8307cc949f13aa5e57cc2568c4ab6-head`:

| Scenario | Test Case | Result |
|---|---|---|
| 1. | Provision a downstream RKE2 w/ k8s `v1.27` on Rancher `v2.8-head` and observe `system-upgrade-controller` chart version | ✅ |
| 2. | Provision a downstream RKE2 w/ k8s `v1.26` on Rancher `v2.7.6` => upgrade Rancher to `v2.8-head` => upgrade k8s to `v1.27` and observe `system-upgrade-controller` chart version | :x: |
| 3. | Import a downstream RKE2 cluster w/ k8s `v1.26` on Rancher `v2.8-head` => upgrade k8s version to `v1.27` and observe `system-upgrade-controller` version | ✅  |
| 4. | Import a downstream RKE2 cluster w/ k8s `v1.25` on Rancher `v2.7.6` => upgrade k8s version to `v1.26` and observe `system-upgrade-controller` version => upgrade Rancher to `v2.8-head` => upgrade k8s to `v1.27` + observe updated `system-upgrade-controller` version | ✅  |

---

Scenario 1 -
1. Fresh install of Rancher `v2.8-head`
2. Provision a downstream RKE2 cluster w/ k8s `v1.27.5+rke2r1`
3. Once `active`, navigate to `Cluster Explorer > Apps > Installed Apps > All Namespaces` and observe `system-upgrade-controller` version
4. Verified - `system-upgrade-controller:103.0.0+up0.6.0`

---

Scenario 2 -
1. Fresh install of Rancher `v2.7.6`
2. Provision a downstream RKE2 cluster w/ k8s `v1.26`
3. Once `active`, navigate to `Cluster Explorer > Apps > Installed Apps > All Namespaces` and observe `system-upgrade-controller:102.1.0+up0.5.0`
4. Upgrade Rancher to `v2.8-head`
5. Upgrade cluster k8s version to `v1.27`
6. Veri-FAILED: cluster hangs in `In progress` status; rancher logs continuously log the following:
```logs
2023/09/20 16:14:52 [ERROR] Failed to find system chart fleet will try again in 5 seconds: no chart name found
2023/09/20 16:14:57 [ERROR] available chart version (102.1.1+up0.7.1) for fleet is less than the min version (103.0.0+up0.9.0-rc.1)
2023/09/20 16:14:57 [ERROR] Failed to find system chart fleet will try again in 5 seconds: no chart name found
W0920 16:14:57.827606      50 warnings.go:80] cluster.x-k8s.io/v1alpha3 Machine is deprecated; use cluster.x-k8s.io/v1beta1 Machine
W0920 16:14:57.827907      50 reflector.go:533] pkg/mod/github.com/rancher/client-go@v1.27.4-rancher1/tools/cache/reflector.go:231: failed to list *unstructured.Unstructured: conversion webhook for cluster.x-k8s.io/v1beta1, Kind=Machine failed: Post "https://capi-webhook-service.cattle-provisioning-capi-system.svc:443/convert?timeout=30s": service "capi-webhook-service" not found
E0920 16:14:57.827965      50 reflector.go:148] pkg/mod/github.com/rancher/client-go@v1.27.4-rancher1/tools/cache/reflector.go:231: Failed to watch *unstructured.Unstructured: failed to list *unstructured.Unstructured: conversion webhook for cluster.x-k8s.io/v1beta1, Kind=Machine failed: Post "https://capi-webhook-service.cattle-provisioning-capi-system.svc:443/convert?timeout=30s": service "capi-webhook-service" not found
2023/09/20 16:15:02 [ERROR] available chart version (102.1.1+up0.7.1) for fleet is less than the min version (103.0.0+up0.9.0-rc.1)
2023/09/20 16:15:02 [ERROR] Failed to find system chart fleet will try again in 5 seconds: no chart name found
2023/09/20 16:15:07 [ERROR] available chart version (102.1.1+up0.7.1) for fleet is less than the min version (103.0.0+up0.9.0-rc.1)
```

Screenshot:
<img width="1678" alt="Screenshot 2023-09-20 at 9 15 55 AM" src="https://github.com/rancher/rancher/assets/46494969/4957860c-87d4-4085-8fd6-b28a3dbb77ab">

`~15mins later - still hanging "In progress"`
<img width="1681" alt="Screenshot 2023-09-20 at 9 32 11 AM" src="https://github.com/rancher/rancher/assets/46494969/84811653-cf48-45c1-99fc-0b577f2198b3">

---

Scenario 3 - 
1. Fresh install of Rancher `v2.8-head`
8. Import a downstream RKE2 cluster w/ k8s `v1.26`
9. Once imported and `active`, upgrade cluster's k8s version to `v1.27`
10. Once upgraded and `active`, observe `system-upgrade-controller` version
11. Verified - `system-upgrade-controller:v0.13.1`; as expected

---

Scenario 4 -
1. Fresh install of Rancher `v2.7.6`
2. Import a downstream RKE2 cluster w/ k8s `v1.25`
3. Once imported and `active`, upgrade the k8s version to `v1.26`
4. Once upgraded and `active`, observe `system-upgrade-controller` version
5. Verified - `system-upgrade-controller:v0.11.0`
6. Upgrade Rancher to `v2.8-head`
7. Post-rancher upgrade, upgrade cluster's k8s version to `v1.27`
8. Once upgraded and `active`, observe `system-upgrade-controller` version
9. Verified - `system-upgrade-controller:v0.13.1`; as expected

**Comment by Josh-Diamond** [comment]
Re-opening due to failure seen when testing Scenario 2

**Comment by gunamata** [comment]
@Josh-Diamond , I see you have reopened this due to issues identified in testing. What's the ETA to get this working? Are you blocked on something to address the issue?

**Comment by Josh-Diamond** [comment]
@gunamata  Hey Guna 👋 as QA, i re-opened this ticket due to the failure seen in Scenario 2, but as far as an ETA to have this issue resolved, i'm not sure, Team 2 Hostbuster devs are looking into this.   I personally am not blocked, i'm just awaiting this to come back `to-test`, where i'll re-validate this at that point. 

I will follow up w/ my team to provide you an ETA for this 👍 (coming soon)

**Comment by thatmidwesterncoder** [comment]
Per https://github.com/rancher/rancher/issues/42888 it looks like we aren't the only ones seeing problems with upgrades like this. 

When working on determining if there was an issue with the system-upgrade-controller chart with Josh yesterday I saw the same errors with the webhook not upgrading and thought it was peculiar. 

After restarting the pod a few times it seems to get back into a "good" state too - so I don't think there is particularly a problem with the chart itself it's more a general charts problem.

**Comment by Josh-Diamond** [comment]
Ticket https://github.com/rancher/rancher/issues/41511 - Test Results pt. 2 - ✅ 
---

Re-testing scenario 2 from above test results on Rancher `v2.8-f9baf1d0cf08e5450a06bb5e94b6af1ac4b96798-head`:
1. Fresh install of Rancher `v2.7.6` - [`tested w/ Docker install`]
2. Provision a downstream RKE2 cluster w/ k8s `v1.26`
3. Once active, navigate to Cluster Explorer > Apps > Installed Apps > All Namespaces and observe `system-upgrade-controller:102.1.0+up0.5.0`
4. Upgrade Rancher to `v2.8-head`
5. Upgrade cluster k8s version to `v1.27`
6. Verified - `system-upgrade-controller:103.0.0+up0.6.0`
