### ISSUE TITLE
rancher -csp-adapter k8s 1.27 chart support

### ISSUE THREAD

**Issue by gunamata** [rancher/rancher#41790]
This issue is to implement the chart changes & perform the testing required to upgrade to k8s 1.27. Please perform below steps. 

- [ ] Check whether the chart has any references to the below deprecated features of k8s 1.27. You can find information about deprecated APIs here on [Kubernetes Deprecation guide](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-27).

**storage.k8s.io/v1beta1** API version of **CSIStorageCapacity**
 

- [ ] Update kube-version annotation in Chart.yaml. catalog.cattle.io/kube-version: '>= 1.23.0-0 < 1.28.0-0'

Note: If this is an upstream chart and if the upstream chart doesn't support k8s 1.27 then do not update the kube-version annotation or update the k8s version accordingly.

- [ ] Perform below tests

- Fresh install/uninstall/upgrade/downgrade of the charts on K8s 1.27 provisioned on Rancher. Test the chart functionality.
(Please refer to the https://github.com/rancher/rancher/issues/41395 to know what testing was done for k8s 1.26 upgrade for your chart)
- Provision rancher on k8s 1.26 or lesser
- Install chart on this cluster
- Upgrade this cluster in rancher to k8s 1.27
- Make sure the existing chart and the app is functional after cluster upgrade

**Comment by MbolotSuse** [comment]
## Validation Template

## What was fixed, or what change have occurred

Underlying Libraries were updated for the CSP Adapter to support k8s 1.27.

## Areas or cases that should be tested

Adapter P0 use cases, including:
- Supportconfig generation
- Warning creation when we go over allowed node count
- Warning deletion when we go back under node count
- Installation using the helm chart

## What areas could experience regressions

Adapter P0 use cases.

## Notes

These changes were made as a part of the adapter version v3.0.0-rc1.

**Comment by anupama2501** [comment]
Verified on v2.8.0-alpha1 
@MbolotSuse From the description of the ticket the kube-version should be  `'>= 1.23.0-0 < 1.28.0-0'`
But the chart values.yaml has the following kube version: `'>= 1.22.0-0 < 1.28.0-0'`. Kube min version to be at `1.23.0-0`

<img width="649" alt="2023-09-27_14-03-01" src="https://github.com/rancher/rancher/assets/38144301/a4ac6c3a-ed6d-457d-ad14-f5033b5df19c">

Re opening for the kube min version to be updated.

**Comment by MbolotSuse** [comment]
Chart has now been updated with the requested values in 3.0.0-rc2, sending back to-test.

**Comment by anupama2501** [comment]
Verified on 2.8.0-alpha2
1. Installed csp-adapter `103.0.0+up3.0.0-rc2`
2. Annotations `'>= 1.23.0-0 < 1.28.0-0'` were set
3. Limit is exceeded when we have more than required nodes in the downstream cluster.
4. Support config is downloaded as a zipped file
5. Banner is gone once the exceeded node is removed.
