### ISSUE TITLE
aks-operator k8s 1.27 chart support

### ISSUE THREAD

**Issue by gunamata** [rancher/rancher#41796]
This issue is to implement the chart changes & perform the testing required to upgrade to k8s 1.27. Please perform below steps. 

- [ ] Check whether the chart has any references to the below deprecated features of k8s 1.27. You can find information about deprecated APIs here on [Kubernetes Deprecation guide](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-27).

**storage.k8s.io/v1beta1** API version of **CSIStorageCapacity**
 

- [ ] Update kube-version annotation in Chart.yaml. catalog.cattle.io/kube-version: '>= 1.23.0-0 < 1.28.0-0'

Note: If this is an upstream chart and if the upstream chart doesn't support k8s 1.27 then do not update the kube-version annotation or update the k8s version accordingly.

- [x] Perform below tests

- Fresh install/uninstall/upgrade/downgrade of the charts on K8s 1.27 provisioned on Rancher. Test the chart functionality.
(Please refer to the https://github.com/rancher/rancher/issues/41395 to know what testing was done for k8s 1.26 upgrade for your chart)
- Provision rancher on k8s 1.26 or lesser
- Install chart on this cluster
- Upgrade this cluster in rancher to k8s 1.27
- Make sure the existing chart and the app is functional after cluster upgrade

PR's:
- [x] https://github.com/rancher/rancher/pull/42882

**Comment by cpinjani** [comment]
Depends on KDM 1.27 support https://github.com/rancher/rancher/issues/41840

**Comment by gunamata** [comment]
@cpinjani , Are you still blocked by #41840?

**Comment by cpinjani** [comment]
@gunamata To unblock, team is bumping dependencies for k8s 1.27 support https://github.com/rancher/aks-operator/issues/269

**Comment by cpinjani** [comment]
Validated as fixed on build:
`v2.8-e5ce94a4c8572a8af176188172a57805e1dc76a4-head`

Test Results - Passed

- Provisioning of downstream AKS v1.27 on Rancher
- Importing downstream AKS v1.27 into Rancher
- Provision/Import downstream AKS cluster with version < v1.27, then upgrade of k8s version of downstream AKS to v1.27
- Rancher upgrade from v2.7.6 to v2.8-head, then upgrade of k8s version of downstream AKS to v1.27
- Performed P0 checks for downstream AKS clusters
