### ISSUE TITLE
Fleet supports k8s 1.27 & 1.28

### ISSUE THREAD

**Issue by gunamata** [rancher/rancher#41795]
This issue is to implement the chart changes & perform the testing required to upgrade to k8s 1.27. Please perform below steps. 

- [x] Check whether the chart has any references to the below deprecated features of k8s 1.27. You can find information about deprecated APIs here on [Kubernetes Deprecation guide](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-27).

**storage.k8s.io/v1beta1** API version of **CSIStorageCapacity**
 

- [x] Do an RC of fleet "0.9" for charts/dev-v2.8
- [x] Update kube-version annotation in Chart.yaml. catalog.cattle.io/kube-version: '>= 1.23.0-0 < 1.28.0-0'
  https://github.com/rancher/charts/blame/dev-v2.8/packages/fleet/fleet/generated-changes/patch/Chart.yaml.patch

Note: If this is an upstream chart and if the upstream chart doesn't support k8s 1.27 then do not update the kube-version annotation or update the k8s version accordingly.

- [x] Perform below tests

- Fresh install/uninstall/upgrade/downgrade of the charts on K8s 1.27 provisioned on Rancher. Test the chart functionality.
(Please refer to the https://github.com/rancher/rancher/issues/41395 to know what testing was done for k8s 1.26 upgrade for your chart)
- Provision rancher on k8s 1.26 or lesser
- Install chart on this cluster
- Upgrade this cluster in rancher to k8s 1.27
- Make sure the existing chart and the app is functional after cluster upgrade

**Comment by manno** [comment]
Needs at least a Fleet RC.

**Comment by gunamata** [comment]
@manno , Are you still blocked?

**Comment by raulcabello** [comment]
Fleet is installed automatically with Rancher. The upstream cluster has the `fleet-controller` and `fleet-agent`, and all downstream clusters have a `fleet-agent`.

There is no helm chart for Rancher v2.8 yet, so I used the following command to install Rancher:
```
helm install rancher rancher-latest/rancher --create-namespace --devel \
  --namespace cattle-system \
  --set hostname=<hostname> \
  --set rancherImageTag=v2.8-head \
  --set bootstrapPassword=<pass>
```

> Perform below tests
> * Fresh install/uninstall/upgrade/downgrade of the charts on K8s 1.27 provisioned on Rancher. Test the chart functionality.

Rancher installation failed with the following error message:

```
Error: INSTALLATION FAILED: chart requires kubeVersion: < 1.27.0-0 which is incompatible with Kubernetes v1.27.5+k3s1
```

Do we need to wait for the Rancher 2.8 alpha version?

> * Provision rancher on k8s 1.26 or lesser
> * Install chart on this cluster
> * Upgrade this cluster in rancher to k8s 1.27
> * Make sure the existing chart and the app is functional after cluster upgrade

Upgrade worked fine. 

- Installed Rancher in a k8s v1.26.8+k3s1 cluster, and added a downstream cluster with the same version. 
- Upgraded both upstream and downstream to v1.27.5+k3s1
- Verified fleet-agent and fleet-controller were working fine. 

Version of rancher: rancher/rancher:v2.8-head 
Version of Fleet: rancher/fleet:v0.9.0-rc.1

**Comment by sbulage** [comment]
### System information:
- Rancher version: 2.7.7
- Fleet version: 0.8.0

###  Rancher Upgrade Scenario
- Upgrade from Rancher `2.7.7` to `2.8.0-alpha2` works fine, (Upgrading k3s version `v1.27.1+k3s1` is done prior to the Rancher upgrade).
- Fleet upgraded to the 0.9.0-rc3 without any error.
- GitRepo is also working fine.

### Fresh Rancher installation

- Fresh Rancher installation with the `v1.27.1+k3s1` or beyond is throwing below error: 
```
Error: INSTALLATION FAILED: chart requires kubeVersion: < 1.27.0-0 which is incompatible with Kubernetes v1.27.1+k3s1
```

**Comment by dgadelha** [comment]
@gunamata / @thardeck, shouldn't the patch be `catalog.cattle.io/kube-version: '>= 1.23.0-0 < 1.29.0-0'` according to the issue title, or you are doing each version step by step?

**Comment by sbulage** [comment]
> ### System information:
> * Rancher version: 2.7.7
> * Fleet version: 0.8.0
> 
> ### Rancher Upgrade Scenario
> * Upgrade from Rancher `2.7.7` to `2.8.0-alpha2` works fine, (Upgrading k3s version `v1.27.1+k3s1` is done prior to the Rancher upgrade).
> * Fleet upgraded to the 0.9.0-rc3 without any error.
> * GitRepo is also working fine.
> 
> ### Fresh Rancher installation
> * Fresh Rancher installation with the `v1.27.1+k3s1` or beyond is throwing below error:
> 
> ```
> Error: INSTALLATION FAILED: chart requires kubeVersion: < 1.27.0-0 which is incompatible with Kubernetes v1.27.1+k3s1
> ```

Fresh installation of Rancher version: `v1.27.6+rke2r1` working without any error. Also, tested below points:

- [ ] Cluster import
- [ ] Installs fleet version 0.9 RC
- [ ] Working of GitRepo.

**Comment by manojkumargogula** [comment]
helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=hostname \
  --set bootstrapPassword=**** \
  --set replicas=3
Error: INSTALLATION FAILED: chart requires kubeVersion: < 1.28.0-0 which is incompatible with Kubernetes v1.28.7


Hey is there any chance of installing rancher on kubeverison 1.28.0
