### ISSUE TITLE
eks-operator k8s 1.27 chart support

### ISSUE THREAD

**Issue by gunamata** [rancher/rancher#41797]
This issue is to implement the chart changes & perform the testing required to upgrade to k8s 1.27. Please perform below steps. 

- [ ] Check whether the chart has any references to the below deprecated features of k8s 1.27. You can find information about deprecated APIs here on [Kubernetes Deprecation guide](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-27).

**storage.k8s.io/v1beta1** API version of **CSIStorageCapacity**
 

- [ ] Update kube-version annotation in Chart.yaml. catalog.cattle.io/kube-version: '>= 1.23.0-0 < 1.28.0-0'

Note: If this is an upstream chart and if the upstream chart doesn't support k8s 1.27 then do not update the kube-version annotation or update the k8s version accordingly.

- [ ] Perform below tests

- Fresh install/uninstall/upgrade/downgrade of the charts on K8s 1.27 provisioned on Rancher. Test the chart functionality.
(Please refer to the https://github.com/rancher/rancher/issues/41395 to know what testing was done for k8s 1.26 upgrade for your chart)
- Provision rancher on k8s 1.26 or lesser
- Install chart on this cluster
- Upgrade this cluster in rancher to k8s 1.27
- Make sure the existing chart and the app is functional after cluster upgrade

## PR's:
- [x] https://github.com/rancher/charts/pull/2889
- [x] https://github.com/rancher/charts/pull/2892
- [x] https://github.com/rancher/rancher/pull/42879

**Comment by cpinjani** [comment]
Depends on KDM 1.27 support https://github.com/rancher/rancher/issues/41840

**Comment by gunamata** [comment]
@cpinjani , My understanding is that there's no need to wait for the KDM release and there are other ways to test rancher with k8s 1.27. 

@snasovich, As discussed in the LT call, May I ask you to add your suggestions on other ways one can use k8s 1.27 in rancher ? Thank you.

**Comment by valaparthvi** [comment]
I ran smoke tests, creating/importing cluster, upgrading k8s version, adding/deleting nodes and some tests with RBAC, everything works as expected.

1.27 k8s version is still not available.

**Comment by valaparthvi** [comment]
Checked for 1.27, it works as expected.
