### ISSUE TITLE
k8s 1.27  support for rancher-vsphere-cpi chart

### ISSUE THREAD

**Issue by gunamata** [rancher/rancher#41792]
This issue is to implement the chart changes & perform the testing required to upgrade to k8s 1.27. Please perform below steps. 

- [x] Check whether the chart has any references to the below deprecated features of k8s 1.27. You can find information about deprecated APIs here on [Kubernetes Deprecation guide](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-27).

**storage.k8s.io/v1beta1** API version of **CSIStorageCapacity**
 

- [x] Update kube-version annotation in Chart.yaml. catalog.cattle.io/kube-version: '>= 1.23.0-0 < 1.28.0-0'

Note: If this is an upstream chart and if the upstream chart doesn't support k8s 1.27 then do not update the kube-version annotation or update the k8s version accordingly.

- [x] Perform below tests

- Fresh install/uninstall/upgrade/downgrade of the charts on K8s 1.27 provisioned on Rancher. Test the chart functionality.
(Please refer to the https://github.com/rancher/rancher/issues/41395 to know what testing was done for k8s 1.26 upgrade for your chart)
- Provision rancher on k8s 1.26 or lesser
- Install chart on this cluster
- Upgrade this cluster in rancher to k8s 1.27
- Make sure the existing chart and the app is functional after cluster upgrade

**Comment by a-blender** [comment]
# QA Test Template - vSphere

Issue: 

  
# Problem

  
# Solution

  
# Testing

 
## Engineering Testing

### Manual Testing


- [ ] Spin up a Rancher v2.8-head instance
- [ ] Add cloud credentials, node template
- [ ] Spin up a vsphere 3 node cluster with k8s 1.27 (if rke node driver cluster `disk.UUID=TRUE` will be set by default. If rke custom cluster, set `disk.UUID=TRUE` on Rancher node. This is required for the CSI node driver to attach itself to the correct disk and function properly)
- [ ] Add taint `node.cloudprovider.kubernetes.io/uninitialized=true:NoSchedule` to nodes
- [ ] Install CPI on the downstream cluster via the rancher UI
- [ ] Verify CPI deployed successfully and the kubelet removed that taint from the nodes, providerID is set
- [ ] Install CSI on the downstream cluster via the rancher UI
- [ ] Verify CSI deployed successfully

Upgrade - on Rancher 2.8-head, install both CPI and CSI charts on a downstream k8s 1.26 cluster. Upgrade cluster to k8s 1.27 and verify the charts are still functional.
 
### Automated Testing

 
## QA Testing Considerations

  
### Regressions Considerations


 vSphere CPI/CSI charts, rke2 charts.

**Comment by thaneunsoo** [comment]
### Test ###
Below are the covered testcases for the CPI/CSI chart update on v2.8-head a4eae80

**Install CPI/CSI v1.27.0 chart on rke1 cluster** - **PASS**
1. Create a rancher server on v2.8-head on vSphere
- Login to vsphere 
- Create a vm from template, install docker, then run Rancher v2.8-head on it (this is behind the VPN so Rancher will be able to reach the downstream cluster)
2. Add vsphere credentials to Rancher
3. Provision a 3 node RKE1 vSphere cluster in Rancher
- 1 cp/etcd, 2 worker
- Add taint `node.cloudprovider.kubernetes.io/uninitialized=true:NoSchedule` to cp/etcd node
4. Verify downstream cluster is using `dev-v287` and not `release-v2.8`
5. Install CPI chart v1.27
- Validate that cpi pod has been deployed and is active
- Validate that the taint is removed
6. Install CSI chart v3.0.2
- Validate that a storage class is created for `csi`
- Validate that the user can deploy a workload with a mounted volume
  - deploy ranchertest/mytestcontainer
    - mount a volume before creating the deployment
- After workload deploys, add data to the volume\
  - ssh into workload - volume is mounted on root with the name you gave it when creating the volume
- Verify data is created in volume
  - check in vSphere - volumes, or check through rancher

**Install CPI/CSI v1.27.0 chart on rke2 cluster** - **PASS**
1. Create a rancher server on v2.8-head on vSphere
- Login to vsphere
- Create a vm from template, install docker, then run Rancher v2.8-head on it (this is behind the VPN so Rancher will be able to reach the downstream cluster)
2. Add vsphere credentials to Rancher
3. Provision a 3 node RKE1 vSphere cluster in Rancher
- 1 cp/etcd, 2 worker
- Add taint `node.cloudprovider.kubernetes.io/uninitialized=true:NoSchedule` to cp/etcd node
4. Verify downstream cluster is using `dev-v2.8` and not `release-v2.8`
5. Install CPI chart v1.27
- Validate that cpi pod has been deployed and is active
- Validate that the taint is removed
6. Install CSI chart v3.0.2
- Validate that a storage class is created for `csi`
- Validate that the user can deploy a workload with a mounted volume
  - deploy ranchertest/mytestcontainer
    - mount a volume before creating the deployment
- After workload deploys, add data to the volume\
  - ssh into workload - volume is mounted on root with the name you gave it when creating the volume
- Verify data is created in volume
  - check in vSphere - volumes, or check through rancher

**Upgrade k8s version with CPI/CSI chart installed** - **PASS**
1. Create a rancher server on v2.8-head on vSphere
- Login to vsphere
- Create a vm from template, install docker, then run Rancher v2.8-head on it (this is behind the VPN so Rancher will be able to reach the downstream cluster)
2. Add vsphere credentials to Rancher
3. Provision a 3 node RKE2 vSphere cluster in Rancher
- Use k8s version 1.26
- 1 cp/etcd, 2 worker
- Add taint `node.cloudprovider.kubernetes.io/uninitialized=true:NoSchedule` to cp/etcd node
4. Verify downstream cluster is using `dev-v2.8` and not `release-v2.8`
5. Install CPI chart v1.26
- Validate that cpi pod has been deployed and is active
- Validate that the taint is removed
6. Install CSI chart v3.0.1
- Validate that a storage class is created for `csi`
- Validate that the user can deploy a workload with a mounted volume
  - deploy ranchertest/mytestcontainer
    - mount a volume before creating the deployment
- After workload deploys, add data to the volume\
  - ssh into workload - volume is mounted on root with the name you gave it when creating the volume
- Verify data is created in volume
  - check in vSphere - volumes, or check through rancher
7. Upgrade k8s version
- Edit config
- Upgrade k8s version from 1.26 to 1.27
- Save
8. Wait for cluster to finish upgrading and come up active
9. Verify all CPI pods are running and healthy
10. Upgrade CPI chart to v1.27
- Validate that cpi pod is updated to correct version and is active
11. Upgrade CSI chart to v3.0.2
- Validate that csi storage class is updated to correct version and is active
12. Edit storage and add new data
- ssh into workload - volume is mounted on root with the name you gave it when creating the volume
- Verify data is added to volume

**Comment by thaneunsoo** [comment]
Automated testing is being covered here [872](https://github.com/rancher/qa-tasks/issues/872)
