### ISSUE TITLE
Epinio: support of k8s 1.27

### ISSUE THREAD

**Issue by gunamata** [rancher/rancher#41802]
This issue is to implement the chart changes & perform the testing required to upgrade to k8s 1.27. Please perform below steps. 

- [ ] Check whether the chart has any references to the below deprecated features of k8s 1.27. You can find information about deprecated APIs here on [Kubernetes Deprecation guide](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-27).

**storage.k8s.io/v1beta1** API version of **CSIStorageCapacity**
 

- [ ] Update kube-version annotation in Chart.yaml. catalog.cattle.io/kube-version: '>= 1.23.0-0 < 1.28.0-0'

Note: If this is an upstream chart and if the upstream chart doesn't support k8s 1.27 then do not update the kube-version annotation or update the k8s version accordingly.

- [ ] Perform below tests

- Fresh install/uninstall/upgrade/downgrade of the charts on K8s 1.27 provisioned on Rancher. Test the chart functionality.
(Please refer to the https://github.com/rancher/rancher/issues/41395 to know what testing was done for k8s 1.26 upgrade for your chart)
- Provision rancher on k8s 1.26 or lesser
- Install chart on this cluster
- Upgrade this cluster in rancher to k8s 1.27
- Make sure the existing chart and the app is functional after cluster upgrade

**Comment by thehejik** [comment]
At time of validating Epinio v1.9.0 app chart the latest rancher is 2.7.5 which is not compatible with k8s 1.27 yet.

**Comment by gunamata** [comment]
@thehejik , Can you please test this with k8s 1.27?

**Comment by gunamata** [comment]
@andreas-kupries , @thehejik - Has the testing been done for this PR?

**Comment by thehejik** [comment]
@gunamata latest Epinio v1.9.0 has been validated within https://github.com/rancher/charts/pull/2804 on `v1.26.6+k3s1` and `rancher v2.7.5` in Jun.

We will try to test with k8s 1.27 on Epinio v1.10.0 PR https://github.com/rancher/charts/pull/3064 - currently blocked by mirroring epinio images to the rancher namespace https://github.com/rancher/image-mirror/pull/475

**Comment by thehejik** [comment]
Seems that Rancher itself is still not yet compatible with k8s 1.27:
```bash
$ helm upgrade --install=true rancher rancher-latest/rancher -n cattle-system \
  --set replicas=1 \
  --set hostname=1.2.3.4.nip.io \
  --create-namespace \
  --version 2.7.8-rc1
Release "rancher" does not exist. Installing it now.
Error: chart requires kubeVersion: < 1.27.0-0 which is incompatible with Kubernetes v1.27.6+k3s1
```

**Comment by thehejik** [comment]
Rechecked in `rancher:2.8.0-alpha2` on `v1.27.6+k3s1` with Epinio `103.0.1+up1.9.0` from official rancher `dev-v2.8` chart repo:
* installation - no DEPRECATION/ERROR
![image](https://github.com/rancher/rancher/assets/12828077/48c61da2-d728-481e-940b-512affd7bd55)
![image](https://github.com/rancher/rancher/assets/12828077/15fa382c-5363-46e1-a0b2-88bc5c71c7ac)
* Sample app deployment in Epinio
![image](https://github.com/rancher/rancher/assets/12828077/16280d51-37bc-41fc-9b0f-5eaf3b4c8ac3)
* Un-installation: epinio, then epinio-crd
* all good
* (upgrades were not performed as 2.8 is still in alpha)

I guess this can be closed.
