### ISSUE TITLE
Update Packet Plugin

### ISSUE THREAD

**Issue by wlan0** [rancher/rancher#4180]
Rancher Version: 1.0

Docker Version: 1.10.0

OS: Any

Steps to Reproduce: Create a Packet Host

Results: "connection was shut down"
              "Unexpected EOF"

Expected: "Success!"

The plugin is compiled for docker machine 0.5.x and we use docker machine 0.6.x in our setup. We need to ask packet to update this.

**Comment by will-chan** [comment]
Not reproducible with 1.0.0 GA.
