### ISSUE TITLE
Create istio 1.18 chart

### ISSUE THREAD

**Issue by diogoasouza** [rancher/rancher#41833]
Istio 1.18 was released. https://github.com/istio/istio/releases/tag/1.18.0
 
The upstream does support kubernetes 1.27, but since we also use jaeger, we need to wait for [this pr](https://github.com/jaegertracing/jaeger-operator/pull/2235) to be merged to proceed.

**Comment by newroc** [comment]
[This PR](https://github.com/jaegertracing/jaeger-operator/pull/2235 )   was solved. Waiting  istio 1.18 chart ....
