### ISSUE TITLE
RKE2 and K3S - KDM Update for K8s June patch release for Rancher 2.6

### ISSUE THREAD

**Issue by rancher-max** [rancher/rancher#41855]
# KDM Updates

| New Kubernetes Version  | Min Rancher Version | Max Rancher Version |
|                  :---:                  |              :---:               |               :---:               |
| v1.24.15+rke2r1                  | v2.6.7-alpha1             | v2.6.99 |
| v1.24.15+k3s1                    | v2.6.7-alpha1             | v2.6.99 |

# KDM Branch
https://github.com/rancher/kontainer-driver-metadata/tree/dev-v2.6-2023-06-patches

# Chart Changelog

| Chart Name  | New Version | Affected Kubernetes Version(s) |
|        :---:        |       :---:        |                     :---:                     |
| rke2-canal | v3.25.1-build2023051201 | v1.24.15+rke2r1 |
| rke2-coredns | 1.24.002 | v1.24.15+rke2r1 |
| rancher-vsphere-cpi | 1.5.100 | v1.24.15+rke2r1 |
| rancher-vsphere-csi | 3.0.1-rancher101 | v1.24.15+rke2r1 |
| harvester-cloud-provider | 0.2.200 | v1.24.15+rke2r1 |

# Argument Changelog

| Argument Name  | Affected Kubernetes Version(s) |
|        :---:           |                     :---:                     |
| | |

# Additional Notes

N/A

**Comment by caroline-suse-rancher** [comment]
PRs:
**K3s**
https://github.com/rancher/kontainer-driver-metadata/pull/1152
**RKE2**
https://github.com/rancher/kontainer-driver-metadata/pull/1160

**Comment by rancher-max** [comment]
Validated using Rancher v2.6.13 that this has the correct versions and they are working correctly:
<img width="1104" alt="image" src="https://github.com/rancher/rancher/assets/55997940/986b7904-c2a2-4939-b4a3-0189bce1ebda">

<img width="1437" alt="image" src="https://github.com/rancher/rancher/assets/55997940/672584a9-f4de-4268-8b44-dbb3e7eef755">
