### ISSUE TITLE
RKE2 and K3S - KDM Update for K8s June patch release for Rancher 2.7

### ISSUE THREAD

**Issue by rancher-max** [rancher/rancher#41856]
# KDM Updates

| New Kubernetes Version  | Min Rancher Version | Max Rancher Version |
|                  :---:                  |              :---:               |               :---:               |
| v1.24.15+rke2r1                  | v2.6.7-alpha1             | v2.7.99 |
| v1.25.11+rke2r1                  | v2.7.2-alpha1             | v2.7.99 |
| v1.26.6+rke2r1                  | v2.7.5-alpha1             | v2.7.99 |
| v1.24.15+k3s1                    | v2.6.7-alpha1             | v2.7.99 |
| v1.25.11+k3s1                  | v2.7.2-alpha1             | v2.7.99 |
| v1.26.6+k3s1                  | v2.7.5-alpha1             | v2.7.99 |

# KDM Branch
https://github.com/rancher/kontainer-driver-metadata/tree/dev-v2.7-2023-06-patches

# Chart Changelog

| Chart Name  | New Version | Affected Kubernetes Version(s) |
|        :---:        |       :---:        |                     :---:                     |
| rke2-canal | v3.25.1-build2023051201 | v1.24.15+rke2r1, v1.25.11+rke2r1, v1.26.6+rke2r1 |
| rke2-coredns | 1.24.002 | v1.24.15+rke2r1, v1.25.11+rke2r1, v1.26.6+rke2r1 |
| rancher-vsphere-cpi | 1.5.100 | v1.24.15+rke2r1, v1.25.11+rke2r1, v1.26.6+rke2r1 |
| rancher-vsphere-csi | 3.0.1-rancher101 | v1.24.15+rke2r1, v1.25.11+rke2r1, v1.26.6+rke2r1 |
| harvester-cloud-provider | 0.2.200 | v1.24.15+rke2r1, v1.25.11+rke2r1, v1.26.6+rke2r1 |
| rke2-snapshot-controller | 1.7.202 | v1.25.11+rke2r1, v1.26.6+rke2r1 |
| rke2-snapshot-controller-crd | 1.7.202 | v1.25.11+rke2r1, v1.26.6+rke2r1 |
| rke2-snapshot-validation-webhook | 1.7.101 | v1.25.11+rke2r1, v1.26.6+rke2r1 |

# Argument Changelog

N/A

# Additional Notes

N/A

**Comment by gpanasci** [comment]
Hi @rancher-max,

currently we have a rke2 cluster (v1.26.2+rke2r1). According to this [compatibility matrix](https://www.suse.com/suse-rancher/support-matrix/all-supported-versions/rancher-v2-7-4/) there isn't a Rancher version compatible with our rke2 version. 

According to KDM Updates above instead, v1.26.6+rke2r1 is the only compatible version with Rancher 2.7.x. Is this Rancher version also compatible with my rke2 version? Do I have to upgrade rke2 version from v1.26.2+rke2r1 to v1.26.6+rke2r1?

Thank you in advance!

**Comment by caroline-suse-rancher** [comment]
PRs:
**K3s**
https://github.com/rancher/kontainer-driver-metadata/pull/1153
**RKE2**
https://github.com/rancher/kontainer-driver-metadata/pull/1156

**Comment by rancher-max** [comment]
Validated using Rancher v2.7.5 that this has the expected versions and they are working correctly:
<img width="1168" alt="image" src="https://github.com/rancher/rancher/assets/55997940/caf8fb2f-a5ab-45a3-94b0-88f8835cc6b7">

<img width="1458" alt="image" src="https://github.com/rancher/rancher/assets/55997940/9299210c-ddc4-4f2d-bc63-5c9b1a2a36c7">

<img width="1437" alt="image" src="https://github.com/rancher/rancher/assets/55997940/8b19c347-8f62-40b2-8015-464cf5f9d02b">
