### ISSUE TITLE
Test prometheus-federator 0.3.2 on 2.6.13

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#41865]
When testing prometheus-federator 0.3.1/0.3.2, make sure the 2.6.13 charts are being pulled in as the user would, then add 0.3.1/0.3.2 on top of that.

**Comment by AndrewHoffmanQA** [comment]
this ticket is intended to capture other regression testing efforts:
- on the latest 2.6 released image, test a fresh install of prom federator from 2.6-dev branch
- on the latest 2.6 released image, install current prom fed and upgrade to version meant for OOB release

**Comment by AndrewHoffmanQA** [comment]
cluster info-
- rancher image - 2.6.10
- k8- v1.24.9 
- RKE- v1.3.18

p0 test case suite run against the following cluster configurations-


- fresh install of monitoring and prom federator on a local cluster
results- passed
- fresh install of monitoring and prom federator on a downstream cluster
results- passed
- install monitoring and prom federator, run p0. upgrade to latest prom federator on a local cluster, run p0.
results - passed
- install monitoring and prom federator, run p0. upgrade to latest prom federator on a downstream cluster, run p0.
- results - passed



fresh install chart versions 
- monitoring =100.2.0+up40.1.2
- prom fed= 0.3.0+up0.3.2


upgrade chart scenario, chart versions used - 
monitoring- 100.1.3+up19.0.3
prom fed - 0.2.0+up0.2.2 upgraded to 0.3.0+up0.3.2




logged bugs - https://github.com/rancher/rancher/issues/41973

**Comment by AndrewHoffmanQA** [comment]
testing completed. closing ticket
