### ISSUE TITLE
"Unable to find a node fulfilling all dependencies" error when upgrading

### ISSUE THREAD

**Issue by npcode** [rancher/rancher#4187]
Rancher Version: latest

Docker Version: 1.10.3

OS: CentOS 7

Steps to Reproduce: 

Try to upgrade rancher from an old version, which was created 4 weeks ago, to the latest version following [the official upgrading guide](http://docs.rancher.com/rancher/upgrading/).

Results: 

"Unable to find a node fulfilling all dependencies" error when running `docker run -d --volumes-from rancher-data --restart=always -p 8080:8080 rancher/server:latest`, as follows:

```
$ docker pull rancher/server:latest
$ docker create --volumes-from kickass_jennings --name rancher-data rancher/server:latest
faa543f1cf95c5354734349cbfd7c0244c075cb219526f353e862dc7365f6419
$ docker run -d --volumes-from rancher-data --restart=always -p 8080:8080 rancher/server:latest
docker: Error response from daemon: Unable to find a node fulfilling all dependencies: --volumes-from=rancher-data.
See 'docker run --help'.
```

Expected:

Rancher starts successfully.

**Comment by npcode** [comment]
Note: I pulled rancher/server:latest **before** creating rancher-data. Is this the culprit?

**Comment by deniseschannon** [comment]
When creating an issue, could you specify what version of your latest is? I'm not sure when you pulled and what latest container you have. 

When creating a data container, it shouldn't matter what image you are using, so I don't believe that pulling before creating the data container should matter. 

Can you provide `docker ps`?

**Comment by npcode** [comment]
The newer version is 0.63.1 but I couldn't figure out the old version because I missed the old image.

I guess the culprit was the swarm cluster which I'm using. I couldn't find the volume I created:

```
$ docker volume ls -q | grep rancher-data
$ docker create --volumes-from kickass_jennings --name rancher-data rancher/server:latest
Error response from daemon: Conflict: The name rancher-data is already assigned. You have to delete (or rename) that container to be able to assign rancher-data to a container again.
$ docker volume rm rancher-data
Error response from daemon: No such volume rancher-data
```

**Comment by npcode** [comment]
Here is my `docker ps`:
```
CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS              PORTS                                                                                   NAMES
b912b0a156b5        rancher/server:latest           "/usr/bin/s6-svscan /"   22 hours ago        Up 22 hours         3306/tcp, 10.123.123.149:8080->8080/tcp                                                 chadp018/high_archimedes
45e4f505d936        rancher/server:latest           "/usr/bin/s6-svscan /"   22 hours ago        Up 22 hours         10.123.123.147:8080->8080/tcp, 3306/tcp                                                 chadp016/elegant_wescoff
8499688f4918        progrium/consul                 "/bin/start -server -"   4 days ago          Up 4 days           53/tcp, 53/udp, 8300-8302/tcp, 8301-8302/udp, 8400/tcp, 10.123.123.138:8500->8500/tcp   chadp007/consul
ef736cedd907        rancher/agent-instance:v0.8.0   "/etc/init.d/agent-in"   2 weeks ago         Up 2 weeks          10.123.123.139:500->500/udp, 10.123.123.139:4500->4500/udp                              chadp008/caae87d5-dfc8-4569-aa0d-d8c7f88ce6bc
a0d0d41b187e        rancher/agent-instance:v0.8.0   "/etc/init.d/agent-in"   2 weeks ago         Up 2 weeks          10.123.123.149:500->500/udp, 10.123.123.149:4500->4500/udp                              chadp018/9e00b82a-12b2-40c9-b4ee-4169cdd0679e
83856d0ff3ad        rethinkdb                       "rethinkdb --bind all"   2 weeks ago         Up 5 days           8080/tcp, 28015/tcp, 29015/tcp                                                          chadp007/shipyard-rethinkdb,chadp007/shipyard-controller/rethinkdb
```

**Comment by deniseschannon** [comment]
@npcode It's hard to tell from your comments but are you still having issues?

In your `docker ps -a`, you should be able to find the rancher-data container. It's not a volume that is being created but a data container that is not running.

**Comment by npcode** [comment]
> In your docker ps -a, you should be able to find the rancher-data container. It's not a volume that is being created but a data container that is not running.

You're right. I misunderstood. Thanks.

> docker: Error response from daemon: Unable to find a node fulfilling all dependencies: --volumes-from=rancher-data.

I think this error means there is no swarm node which has "rancher-data" container and unoccupied ports to be required to run rancher server. Actually in my swarm cluster the only node which has "rancher-data" is using 8080 port.

I upgraded rancher successfully without data migration which is not important. Thanks for your help!

**Comment by deniseschannon** [comment]
@npcode Sounds like you're all set. Please re-open if you are still having issues.
