### ISSUE TITLE
[BUG] Installing rancher on GKE with gce ingress class return "response 404 (backend NotFound)"

### ISSUE THREAD

**Issue by orhan89** [rancher/rancher#41873]
**Rancher Server Setup**
- Rancher version: 2.7.5-rc2
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): GKE
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: 1.25.8-gke.500
- Cluster Type (Local/Downstream): Local
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? Admin
  - If custom, define the set of permissions:

**Describe the bug**
Fresh install using helm chart version 2.7.5-rc2 on GCP, return "response 404 (backend NotFound), service rules for the path non-existent.

**To Reproduce**
- install rancher with helm version 2.7.5-rc2 on GKE cluster 

```
helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=<rancher_url> \
  --set bootstrapPassword=admin
```

- open the dashboard in browser at https://<rancher_url>/

**Result**
got "response 404 (backend NotFound), service rules for the path non-existent "

**Expected Result**
Get the bootstrap page

**Screenshots**

**Additional context**
Installing rancher on GKE without specifying ingressClass will use the default GKE Ingress Controller that is implemented as GCP Load Balancer (see [doc](https://cloud.google.com/kubernetes-engine/docs/concepts/ingress)). Pre 2.7.5-rc2, we can access rancher just fine through the GCP load balancer.

I did little investigation, and i suspect this change in behaviour is due to commit https://github.com/rancher/rancher/commit/7e207c30163e373d8471bf1c370531ecd8af7d75 that add `path: "/"` to ingress rules. Since the pathType is already set to `ImplementationSpecific`, the behaviour can be different between ingress controller.

To ensure that rancher can be more independent of the ingress controller, i propose that we change the `pathType` to `Prefix` instead (see doc of ingress [pathType](https://kubernetes.io/docs/concepts/services-networking/ingress/#path-types)). I have test it that rancher is accessible again after i change the pathType to `Prefix`.

**Comment by gaktive** [comment]
Internal reference: SURE-6901

**Comment by susesgartner** [comment]
Ticket #41873 - Test Results - ✅ 
---
 
| Scenario | Test Case | Result |
|---|---|---|
| 1. | Provision rancher on a GKE local cluster | PASS |
| 2. | Provision rancher on AWS and set ingress.path | PASS  |
 

Verified with with HA Helm on Rancher `v2.8-rc4`:
---
 
Scenario 1: Provision rancher on a GKE local cluster
---
1. Create a 3 node GKE standard cluster
2. Configure the cluster as per https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/rancher-on-gke
3. Run helm install with ingress.Path="/*" and service.type=NodePort
 
Results: Rancher UI is accessible and no errors are observed.
 
---
 
Scenario 2: Provision rancher on AWS and set ingress.path
---
1. Create a 3 node AWS cluster
2. Run helm install with ingress.Path="/*" and service.type=NodePort
 
Results: Rancher UI is accessible and no errors are observed.
