### ISSUE TITLE
[BUG] Do not delete CAPI cluster resources when finalizers are removed from provisioning cluster

### ISSUE THREAD

**Issue by jakefhyde** [rancher/rancher#41887]
**Rancher Server Setup**
- Rancher version: v2.7.3

**Describe the bug**

When finalizers are removed from a provisioning cluster object, there is a race condition between adding the finalizers back, and the generating framework deleting the generated `rkecluster`, `rkecontrolplane`, `cluster.cluster.x-k8s.io` and `machinedeployment`s.

**To Reproduce**

Reproduction is not reliable, but have the same reproduction steps as https://github.com/rancher/terraform-provider-rancher2/issues/993

**Result**

Cluster resources are undesriably removed.

**Expected Result**

Generating handler waits until finalizers are added.

**Screenshots**

**Additional context**

**Comment by thaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.7-head 0bcf068
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: rke2 aws node driver cluster using terraform

----------

### Testing: ###
Tested this issue with the following steps:
1. Provision RKE2 cluster with terraform
2. modify `additional_manifest` for RKE2 cluster
3. apply change

**Result**
As mentioned in ticket the race condition is hard to reproduce and I was not able to hit the issue but the expected workflow has not been affected and terraform was able to update the cluster successfully.
