### ISSUE TITLE
Add CIS 1.24 benchmark support

### ISSUE THREAD

**Issue by rayandas** [rancher/rancher#41886]
Upstream kube-bench configs: https://github.com/aquasecurity/kube-bench/tree/main/cfg/cis-1.24

**Comment by rayandas** [comment]
@Jamison1 The dev work is ongoing. and that's getting tracked here https://github.com/rancher/rancher/issues/41631

**Comment by dasarinaidu** [comment]
**QA TEST PLAN**

<table>
    <tbody>
        <tr>
            <th>#</th>
            <th>Scenario</th>
            <th>Steps</th>
            <th>Expected</th>
            <th>Status(Pass/Fail)</th>
        </tr>
        <tr>
            <td>1</td>
            <td>Fresh install Rancher with hardened downstream clusters - k8s v1.24 and CIS profile v1.24</td>
            <td>
                <ol>
                    <li> Create a rancher server v2.7.6 </li> 
                    <li> Create the following hardened downstream clusters with k8s v1.24 and CIS profile v1.24: Custom - RKE/RKE2/K3S, Imported - RKE/RKE2/K3S. </li>
                    <li> Install the "rancher-cis-benchmark" on each cluster.</li>
                    <li> Verify that the min and max k8s version for CIS benchmark profile v1.24 is accurate. </li>
                    <li> Run CIS scan on all the downstream clusters with the corresponding cis benchmark profiles: rke/rke2/k3s-cis-1.24-hardened. </li>
                    <li> Verify that the scan reports don't contain any sensitive information. </li>
                </ol>
            </td>
            <td> 
                <ol>
                    <li> Rancher installation completes successfully. </li>
                    <li> All hardened downstream clusters with k8s v1.24 and CIS profile v1.24 are created successfully.  </li>
                    <li> Chart "rancher-cis-benchmark" is installed on each cluster successfully. </li>
                    <li> The min and max k8s version for CIS benchmark profile v1.24 are accurate. </li>
                    <li> CIS scan on all the downstream clusters pass. </li>
                    <li> Scan reports don't contain any sensitive information. </li>
                </ol>
            </td>
            <td><br><br>: </td>
        </tr>
        <tr>
            <td>2</td>
            <td>Fresh install Rancher with non-hardened downstream clusters - k8s v1.24</td>
            <td>
                <ol>
                    <li> Create a rancher server v2.7.6 </li> 
                    <li> Create the following non-hardened downstream clusters with k8s v1.24: Node driver provisioned - RKE/RKE2/K3S, Custom - RKE/RKE2/K3S, Imported - RKE/RKE2/K3S. </li>
                    <li> Install the "rancher-cis-benchmark" on each cluster.</li>
                    <li> Verify that the min and max k8s version for CIS benchmark profile v1.24 is accurate. </li>
                    <li> Run CIS scan on all the downstream clusters with the corresponding cis benchmark profiles: rke/rke2/k3s-cis-1.24-permissive. </li>
                    <li> Verify that the scan reports don't contain any sensitive information. </li>
                </ol>
            </td>
            <td> 
                <ol>
                    <li> Rancher installation completes successfully. </li>
                    <li> All non-hardened downstream clusters with k8s v1.24 are created successfully. </li>
                    <li> Chart "rancher-cis-benchmark" is installed on each cluster successfully. </li>
                    <li> The min and max k8s version for CIS benchmark profile v1.24 are accurate. </li>
                    <li> CIS scan on all the downstream clusters pass. </li>
                    <li> Scan reports don't contain any sensitive information. </li>
                </ol>
            </td>
            <td><br><br>: </td>
        </tr>
        <tr>
            <td>3</td>
            <td>Fresh install Rancher with hardened downstream clusters - k8s v1.26 and CIS profile v1.24</td>
            <td>
                <ol>
                    <li> Create a rancher server v2.7.6. </li> 
                    <li> Create the following hardened downstream clusters with k8s v1.26 and CIS profile v1.24: Custom - RKE/RKE2/K3S, Imported - RKE/RKE2/K3S. </li>
                    <li> Install the "rancher-cis-benchmark" on each cluster.</li>
                    <li> Verify the CIS scan installation is succesful </li>
                </ol>
            </td>
            <td> 
                <ol>
                    <li> Rancher installation completes successfully. </li>
                    <li> All hardened downstream clusters with k8s v1.26 and CIS profile v1.24 are created successfully.  </li>
                    <li> Chart "rancher-cis-benchmark" is installed on each cluster should NOT be succesful </li>
                </ol>
            </td>
            <td><br><br>: </td>
        </tr>
        <tr>
            <td>4</td>
            <td>Fresh install Rancher with non-hardened downstream clusters - k8s v1.26 and CIS profile v1.24</td>
            <td>
                <ol>
                    <li> Create a rancher server v2.7.6. </li> 
                    <li> Create the following non-hardened downstream clusters with k8s v1.26: Node driver provisioned - RKE/RKE2/K3S, Custom - RKE/RKE2/K3S, Imported - RKE/RKE2/K3S. </li>
                    <li> Install the "rancher-cis-benchmark" on each cluster.</li>
                    <li> Verify the CIS scan installation is succesful </li>
                </ol>
            </td>
            <td> 
                <ol>
                    <li> Rancher installation completes successfully. </li>
                    <li> All hardened downstream clusters with k8s v1.26 and CIS profile v1.24 are created successfully.  </li>
                    <li> Chart "rancher-cis-benchmark" is installed on each cluster should NOT be succesful </li>
                </ol>
            </td>
            <td><br><br>: </td>
        </tr>
        <tr>
            <td>5</td>
            <td>Fresh install Rancher with hardened local cluster - k8s v1.24 and CIS profile v1.24</td>
            <td>
                <ol>
                    <li> Create a hardened rancher server v2.7.6 (on RKE2 cluster with k8s v1.24 and CIS profile v1.24). </li> 
                    <li> Install the "rancher-cis-benchmark" on the local cluster.</li>
                    <li> Verify that the min and max k8s version for CIS benchmark profile v1.24 is accurate. </li>
                    <li> Run CIS scan on the local cluster with the cis profile: rke2-cis-v1.24-hardened. </li>
                    <li> Verify that the scan report don't contain any sensitive information. </li>
                </ol>
            </td>
            <td> 
                <ol>
                    <li> Rancher installation completes successfully. </li>
                    <li> Chart "rancher-cis-benchmark" is installed on the local cluster successfully. </li>
                    <li> The min and max k8s version for CIS benchmark profile v1.24 are accurate. </li>
                    <li> CIS scan on the local cluster pass. </li>
                    <li> Scan report don't contain any sensitive information. </li>
                </ol>
            </td>
            <td><br><br>: </td>
        </tr>
        <tr>
            <td>6</td>
            <td>Fresh install Rancher with non-hardened local cluster - k8s v1.24</td>
            <td>
                <ol>
                    <li> Create a rancher server v2.7.6. </li> 
                    <li> Install the "rancher-cis-benchmark" on the local cluster.</li>
                    <li> Verify that the min and max k8s version for CIS benchmark profile v1.24 is accurate. </li>
                    <li> Run CIS scan on the local cluster with the cis profile: rke2-cis-1.24-permissive. </li>
                    <li> Verify that the scan report don't contain any sensitive information. </li>
                </ol>
            </td>
            <td> 
                <ol>
                    <li> Rancher installation completes successfully. </li>
                    <li> Chart "rancher-cis-benchmark" is installed on the local cluster successfully. </li>
                    <li> The min and max k8s version for CIS benchmark profile v1.24 are accurate. </li>
                    <li> CIS scan on the local cluster pass. </li>
                    <li> Scan report don't contain any sensitive information. </li>
                </ol>
            </td>
            <td><br><br>: </td>
        </tr>
        <tr>
            <td>7</td>
            <td>Fresh install Rancher with hardened downstream cluster and non-default CNI</td>
            <td>
                <ol>
                    <li> Create a rancher server v2.7.6. </li> 
                    <li> Create a custom hardened RKE2 downstream cluster (v1.24 with CIS profile v1.24 and canal as CNI) </li>
                    <li> Install the "rancher-cis-benchmark" on the downstream cluster. </li>
                    <li> Verify that the min and max k8s version for CIS benchmark profile v1.24 is accurate. </li>
                    <li> Run CIS scan on the downstream cluster with the following cis benchmark profile: rke2-cis-v1.24-hardened. </li>
                    <li> Verify that the scan report don't contain any sensitive information. </li>
                </ol>
            </td>
            <td> 
                <ol>
                    <li> Rancher installation completes successfully. </li>
                    <li> Custom hardened RKE2 downstream cluster is created successfully. </li>
                    <li> Chart "rancher-cis-benchmark" is installed on the downstream cluster successfully. </li>
                    <li> The min and max k8s version for CIS benchmark profile v1.24 are accurate. </li>
                    <li> CIS scan on the downstream cluster pass. </li>
                    <li> Scan report don't contain any sensitive information. </li>
                </ol>
            </td>
            <td><br><br>: </td>
        </tr>
        <tr>
            <td>8</td>
            <td>Rancher Upgrade with hardened downstream cluster - v2.7.5 to v2.7.6</td>
            <td>
                <ol>
                    <li> Create a rancher server v2.7.5. </li> 
                    <li> Create a custom hardened RKE2 downstream cluster (v1.24 with CIS profile v1.23) </li>
                    <li> Install the "rancher-cis-benchmark" on the downstream cluster.</li>
                    <li> Upgrade Rancher from v2.7.5 to v2.7.6. </li>
                    <li> Verify that the min and max k8s version for CIS benchmark profile v1.24 is accurate. </li>
                    <li> Edit the downstream cluster and update the CIS profile to cis-v1.24. </li>
                    <li> Run CIS scan on the downstream cluster with the following cis benchmark profile: rke2-cis-v1.24-hardened. </li>
                    <li> Verify that the scan report don't contain any sensitive information. </li>
                </ol>
            </td>
            <td> 
                <ol>
                    <li> Rancher installation completes successfully. </li>
                    <li> Custom hardened RKE2 downstream cluster is created successfully. </li>
                    <li> Chart "rancher-cis-benchmark" is installed on the downstream cluster successfully. Note: CIS v1.23 profile will be the latest that's available. </li>
                    <li> Rancher is upgraded from v2.7.5 to v2.7.6 successfully. </li>
                    <li> The min and max k8s version for CIS benchmark profile v1.24 are accurate. </li>
                    <li> CIS profile for the downstream cluster is updated to cis-v1.24. </li>
                    <li> CIS scan on the downstream cluster pass. </li>
                    <li> Scan report don't contain any sensitive information. </li>
                </ol>
            </td>
            <td><br><br>: </td>
        </tr>
        <tr>
            <td>9</td>
            <td>Rancher Upgrade with non-hardened downstream cluster - v2.7.5 to v2.7.6</td>
            <td>
                <ol>
                    <li> Create a rancher server v2.7.5. </li> 
                    <li> Create a custom non-hardened RKE2 downstream cluster with v1.24. </li>
                    <li> Install the "rancher-cis-benchmark" on the downstream cluster.</li>
                    <li> Upgrade Rancher from v2.7.5 to v2.7.6. </li>
                    <li> Verify that the min and max k8s version for CIS benchmark profile v1.24 is accurate. </li>
                    <li> Run CIS scan on the downstream cluster with the following cis benchmark profile: rke2-cis-v1.24-permissive. </li>
                    <li> Verify that the scan report don't contain any sensitive information. </li>
                </ol>
            </td>
            <td> 
                <ol>
                    <li> Rancher installation completes successfully. </li>
                    <li> Custom non-hardened RKE2 downstream cluster is created successfully. </li>
                    <li> Chart "rancher-cis-benchmark" is installed on the downstream cluster successfully. Note: CIS v1.23 profile will be the latest that's available. </li>
                    <li> Rancher is upgraded from v2.7.5 to v2.7.6 successfully. </li>
                    <li> The min and max k8s version for CIS benchmark profile v1.24 are accurate. </li>
                    <li> CIS scan on the downstream cluster pass. </li>
                    <li> Scan report don't contain any sensitive information. </li>
                </ol>
            </td>
            <td><br><br>: </td>
        </tr>
    </tbody>
</table>

**Comment by rayandas** [comment]
@Priyashetty17 I am looking into it.

**Comment by Priyashetty17** [comment]
@rayandas Thanks! 
Similar to what Andy has documented for CIS 1.7 PRs ([RKE](https://github.com/rancher/security-scan/pull/134), [RKE2](https://github.com/rancher/security-scan/pull/136), [K3S](https://github.com/rancher/security-scan/pull/135)), is it possible to document the additions/removals/changes in the CIS 1.24 PRs ([RKE](https://github.com/rancher/security-scan/pull/117), [RKE2](https://github.com/rancher/security-scan/pull/118), [K3s](https://github.com/rancher/security-scan/pull/119)) as well? This will help with our validations since its hard to go through multiple commits in each PR to isolate what's changed

**Comment by rayandas** [comment]
Alright I’ll try to document the changes.

**Comment by Priyashetty17** [comment]
Thanks @rayandas! Since we don't have updated assessment guides for CIS 1.24 profile yet, it'd help us if the changes to the profiles for each distro are clearly documented in the PRs.

**Comment by rayandas** [comment]
@Priyashetty17 There were not many changes in CIS 1.24 except some permissions. Rest of the profiles are same as CIS 1.23. I added which permissions got updated in RKE. will add for the rest as well and mention the major changes if any.

**Comment by rayandas** [comment]
A consolidated details of the changes that has been done in CIS 1.24 RKE, RKE2, and K3s

## RKE
### Details
Distribution: `RKE`
Kubernetes version: `1.24.x`
CIS version: `1.24`
kube-bench profile: [cis-1.24](https://github.com/aquasecurity/kube-bench/tree/main/cfg/cis-1.24)
Profiles created: `rke-cis-1.24-permissive` and `rke-cis-1.24-hardened`

### Main test additions/removals in CIS-1.24

**config.yaml**
- None

**controlplane.yaml**
- None

**etcd.yaml**
- None

**master.yaml**

- Permission for below checks got stricter from 644 to 600

>  `1.1.1`, `1.1.3`, `1.1.5`, `1.1.7`, `1.1.9`, `1.1.15`, `1.1.17`

- No major changes other than above, except a few remediation message  updates. Everything else is same as 1.23 configs. 

**node.yaml**

- Permission for below checks got stricter from 644 to 600

> `4.1.1`, `4.1.3`, `4.1.5`, `4.1.7`, `4.1.9`

- No major changes except remediation updates. Everything else is same as 1.23 configs.

**policies.yaml**
- None

## RKE2
### Details
Distribution: `RKE2`
Kubernetes version: `1.24.x`
CIS version: `1.24`
kube-bench profile: [cis-1.24](https://github.com/aquasecurity/kube-bench/tree/main/cfg/cis-1.24)
Profiles created: `rke2-cis-1.24-permissive` and `rke2-cis-1.24-hardened`

### Main test additions/removals in CIS-1.24

**config.yaml**
- None

**controlplane.yaml**
- None

**etcd.yaml**
- None

**master.yaml**

- Permission for below checks got stricter from 644 to 600

>  `1.1.3`, `1.1.5`, `1.1.9`, `1.1.13`, `1.1.15`, `1.1.17`, `1.1.20`

- No major changes other than above, except a few remediation message  updates. Everything else is same as 1.23 configs. 

**node.yaml**

- Permission for below checks got stricter from 644 to 600

> `4.1.1`, `4.1.3`, `4.1.5`, `4.1.7`, `4.1.9`

- No major changes except remediation updates. Everything else is same as 1.23 configs.

**policies.yaml**
- None

## K3s
### Details
Distribution: `K3s`
Kubernetes version: `1.24.x`
CIS version: `1.24`
kube-bench profile: [cis-1.24](https://github.com/aquasecurity/kube-bench/tree/main/cfg/cis-1.24)
Profiles created: `k3s-cis-1.24-permissive` and `k3s-cis-1.24-hardened`

### Main test additions/removals in CIS-1.24

**config.yaml**
- None

**controlplane.yaml**
- None

**etcd.yaml**
- None

**master.yaml**

- Permission for below checks got stricter from 644 to 600

>  `1.1.3`, `1.1.5`, `1.1.7`, `1.1.9`, `1.1.15`, `1.1.17`, `1.1.20`

- No major changes other than above, except a few remediation message  updates. Everything else is same as 1.23 configs. 

**node.yaml**

- Permission for below checks got stricter from 644 to 600

> `4.1.1`, `4.1.3`, `4.1.5`, `4.1.7`, `4.1.9`

- No major changes except remediation updates. Everything else is same as 1.23 configs.

**policies.yaml**
- None

**Comment by Priyashetty17** [comment]
## **(Validation: In-Progress)**
### **TEST RESULTS** 

**Documentation/Known Issue(s):** 
- CIS checks related to file permissions is currently failing on RKE2 and K3S clusters. These failures are expected and will be documented in the hardening guide - GH-42140.
  - RKE2 failed checks: 1.1.3, 1.1.5, 1.1.13, 1.1.15, 1.1.17, 4.1.5, 4.1.9.
  - K3S failed checks: 1.1.15, 1.1.17, 4.1.5, 4.1.7.
  - RKE failed check: 4.1.7
- CIS check 1.2.19 failure on hardened RKE2 cluster: This failure is due to an issue in RKE2 distro, where the audit log path is not set when using the CIS profile to create the cluster: rancher/rke2/issues/4415.  

**Dashboard Issue(s):** 
- https://github.com/rancher/dashboard/issues/9459
<br>
<table>
    <tbody>
        <tr>
            <th>#</th>
            <th>Scenario</th>
            <th>Pass/Fail</th>
        </tr>
        <tr>
            <td>1</td>
            <td>Fresh install Rancher with hardened downstream custom clusters - k8s v1.24 and CIS profile v1.6</td>
            <td>
                <ol>
                    <li> CIS Scan on RKE cluster: ✅ PASS (with exceptions). </li>
                    <li> CIS Scan on RKE2 cluster: ✅ PASS (with exceptions). </li>
                    <li> CIS Scan on K3S cluster: ✅ PASS (with exceptions). </li>
                    <l> <br> Note: CIS checks related to file permissions failed on hardened RKE, RKE2 and K3S clusters. CIS check related to audit-log-path failed on hardened RKE2 cluster. Refer the notes provided after "TEST RESULTS" for more details. </l>
                </ol>
            </td>
        </tr>
        <tr>
            <td>2</td>
            <td>Fresh install Rancher with non-hardened downstream custom and node driver provisioned clusters - k8s v1.24</td>
            <td>
                <ol>
                    <li> CIS Scan on RKE clusters: ✅ PASS. </li>
                    <li> CIS Scan on RKE2 clusters: ✅ PASS (with exceptions). </li>
                    <li> CIS Scan on K3S clusters: ✅ PASS (with exceptions). </li>
                    <l> <br> Note: CIS checks related to file permissions failed on RKE2 and K3S clusters. Refer the notes provided after "TEST RESULTS" for more details. </l>
                </ol>
            </td>
        </tr>
        <tr>
            <td>3</td>
            <td>Fresh install Rancher with hardened and non-hardened downstream clusters - k8s v1.25 and k8s v1.23</td>
            <td>
                <ol>
                    <l> ✅ PASS </l>
                    <l> <br> Note: Using CIS 1.24 profile against K8s v1.25 and v1.23 clusters failed as expected with a Kubernetes version mismatch error. </l>
                </ol>
            </td>
        </tr>
        <tr>
            <td>4</td>
            <td>Fresh install Rancher with hardened local cluster - k8s v1.24</td>
            <td>
                <ol>
                    <l> In-Progress. </l>
                </ol>
            </td>
        </tr>
        <tr>
            <td>5</td>
            <td>Fresh install Rancher with non-hardened local RKE cluster - k8s v1.24 </td>
            <td>
                <ol>
                    <l> CIS Scan on local RKE cluster: ✅ PASS. </l>
                </ol>
            </td>
        </tr>
        <tr>
            <td>6</td>
            <td>Fresh install Rancher with hardened downstream custom RKE2 cluster (k8s v1.24 and CIS profile v1.6) and non-default CNI</td>
            <td>
                <ol>
                    <l>  Yet to Run </l>
                </ol>
            </td>
        </tr>
        <tr>
            <td>7</td>
            <td>Rancher, K8s and CIS chart upgrade with hardened downstream custom RKE2 cluster </td>
            <td>
                <ol>
                    <l> ✅ PASS (with exceptions).</l>
                    <l> <br> Note: CIS checks related to file permissions and audit-log-path failed on hardened RKE2 cluster. Refer the notes provided after "TEST RESULTS" for more details. </l>
                </ol>
            </td>
        </tr>
        <tr>
            <td>8</td>
            <td>Rancher Upgrade with non-hardened local and downstream clusters - v2.7.5 to v2.7-head </td>
            <td>
                <ol>
                    <li> CIS Scan on RKE clusters: ✅ PASS. </li>
                    <li> CIS Scan on RKE2 clusters: ✅ PASS (with exceptions). </li>
                    <li> CIS Scan on K3S clusters: ✅ PASS (with exceptions). </li>
                    <l> <br> Note: CIS checks related to file permissions failed on RKE2 and K3S clusters. Refer the notes provided after "TEST RESULTS" for more details. </l>
                </ol>
            </td>
        </tr>
        <tr>
            <td>9</td>
            <td>GKE downstream cluster - k8s v1.25 and CIS profile gke-1.2.0 </td>
            <td>
                <ol>
                    <l>  Yet to Run </l>
                </ol>
            </td>
        </tr>
        <tr>
            <td>10</td>
            <td>Rancher and CIS chart upgrade with downstream GKE cluster - v2.7.5 to v2.7-head </td>
            <td>
                <ol>
                    <l>  Yet to Run </l>
                </ol>
            </td>
        </tr>
    </tbody>
</table>

**Comment by Priyashetty17** [comment]
@rayandas  In the scan results for GKE profile 1.2.0, out of 67 failed checks, 61 checks appear as "Mixed" despite there being no failures on any of the nodes. I will close this issue once I get confirmation from you that we don't have control over tagging the state as "Mixed" for the checks in GKE.

**Comment by Priyashetty17** [comment]
**Update on the "Mixed" checks:** @rayandas has created a PR with a potential fix https://github.com/rancher/security-scan/pull/151
`GKE AKS and EKS are managed K8s offerings so we should scan only node components (which is happening for AKS and EKS), but for GKE there were other components added as well which were resulting mixed checks.`

**Comment by Priyashetty17** [comment]
@rayandas Will the existing security scan image "[v0.2.13-rc4](https://github.com/rancher/security-scan/releases/tag/v0.2.13-rc4)" be updated with the fix for https://github.com/rancher/security-scan/pull/151 OR will there be a new image **v0.2.13-rc5** with the fix?

**Comment by rayandas** [comment]
@Priyashetty17 the charts PR is merged now. It’s ready for review.
