### ISSUE TITLE
[UI] usability nit-pick

### ISSUE THREAD

**Issue by kaos** [rancher/rancher#4189]
Rancher Version: 1.0.0

There is no visual cue as to which submenu is open... which can cause some minor confusion.

This example shot suggests that we're looking at the submenu for applications.. alas, we're not (for newcomers, it's the catalog submenu)

![image](https://cloud.githubusercontent.com/assets/72965/14101574/a3dde378-f595-11e5-8473-48a67928baf1.png)

As the headline says, this is rather minor, but would be nice to have addressed. ;)

**Comment by vincent99** [comment]
D'oh, there's supposed to be an off-white caret there to match the background but it's only shown on hover of the top-nav:

![image](https://cloud.githubusercontent.com/assets/753917/14101752/46627ee2-f54b-11e5-8113-d18dca5b46c6.png)

**Comment by tfiduccia** [comment]
Version - master 4/1
Verified fixed
