### ISSUE TITLE
[SURE-6988] Evaluate avoiding downstream object caches in the upstream cluster

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#41905]
Internal reference: [SURE-6988](https://jira.suse.com/browse/SURE-6988)

**Is your feature request related to a problem? Please describe.**
Currently we are caching many objects for downstream clusters in the local cluster's rancher instance. This effects rancher's ability to scale. This caching is being done for a small subset of features that need to look at the downstream resources or run handlers against them. We typically try to migrate these to run in downstream clusters.

We cache at least 11 types of kubernetes resources per downstream cluster:
* ClusterRole
* ResourceQuota
* ConfigMap
* ServiceAccount
* Role
* Namespace
* ClusterRoleBinding
* RoleBinding
* LimitRange
* Node
* APIService
* Secret

Although this is only 11 out of the ~111 kubernetes types we cache for local, some of these types tend to have huge footprints relative to others. A few such types would be ConfigMap, ClusterRolebinding, Rolebindings, and Secret.

Caches will be added when registering a handler or using a lister/cache for a downstream cluster from a usercontext that we start. We use a lot of these caches to run rbac handlers against resource in downstream clusters such as:
* `cluster-clusterrole-sync`
* `legacy-crb-cleaner-sync`
* `namespace-auth`

We also use them in rbac handlers that target resources in the upstream cluster but need access to downstream resources.

**Describe the solution you'd like**

I think a combination of the following approaches should be considered depending on what a particular cache is being used in the first place:
* Move downstream cluster handlers (often called workload handlers) to the downstream cluster agent. This does not mean cluster scoped handlers such as `cluster-crtb-sync` that watch local resources, rather handlers that specifically watch resources living in the downstream cluster. An example of a handler that can be moved downstream is `cluster-clusterrole-sync`. it is running against clusterroles in the downstream cluster and need to get a roletemplate from the local cluster.
* For non-workload handlers, either use regular clients instead of caches or convert the handler into a workload handler that can then be moved to the agent.

**Describe alternatives you've considered**

**Additional context**

**Comment by moio** [comment]
Current status: investigation is ongoing to see what interventions could make the most sense on each type depending on the controllers involved.

Collaborating with a customer in the scope of https://jira.suse.com/browse/SURE-6988 to validate the approach.

**Comment by gaktive** [comment]
Candidate for backport for 2.9.x once we sort this out.

**Comment by moio** [comment]
(Still under research)

**Comment by moio** [comment]
Work in https://github.com/rancher/rancher/issues/46827 should have improved this sufficiently.

We will open separate issues if more is found later.
