### ISSUE TITLE
[Bug] On rancher server upgrade and roll back, downstream clusters webhook version needs to be downgraded 

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#41917]
Information about the Cluster
**Rancher Server Setup**
- Rancher version: `v2.7.4` upgraded to v2.7-head `0bcf068 ` rolled back to `2.7.2`
- Installation option (Docker install/Helm Chart): `Helm Chart`
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): `RKE1`, `v1.25.6`, `v1.4.5` Hardened 
- Proxy/Cert Details: `Self-signed`

**Information about the Cluster**
- Kubernetes version: `1.25` RKE2 and RKE1 node driver clusters
- Cluster Type (Local/Downstream): `1 etcd, 1 cp, 1 worker`

**Describe the bug**
When we upgrade and roll back rancher server from v2.7.4 >> v2.7-head >> v2.7.4 or v2.7.2 >> v2.7.3 >> v2.7.2 , downstream clusters webhook version is not upgraded but the local cluster webhook version is downgraded to the required version. 

**To Reproduce**
1. Install rancher on version 2.7.4
2. Create a custom RKE1 and RKE2 cluster with the specs mentioned above.
3. Install rancher backup/restore chart version in the local cluster with config set to S3
4. Take a backup from the rancher backup/restore page and the backupfile gets saved in the s3.
5. Upgrade rancher server to v2.7-head
6. Rollback to 2.7.4 by following the docs 
7. Bring down the nodes of current rancher local cluster
8. Migrate rancher to v2.7.0 by following instructions here https://ranchermanager.docs.rancher.com/v2.7/how-to-guides/new-user-guides/backup-restore-and-disaster-recovery/restore-rancher-launched-kubernetes-clusters-from-backup

**Result**
Once the migration is successful, and rancher is installed if we navigate to downstream clusters, we notice the webhook version stays at the version of v2.7-head and is not compatible with the local cluster webhook version.

**Expected Result**
Webhook on downstream clusters stay compatible with local cluster

**Comment by anupama2501** [comment]
Fix is going to be an update for the script https://github.com/rancherlabs/support-tools/tree/master/remove-webhook

**Comment by cbron** [comment]
Release note here handled by: https://github.com/rancher/rancher/issues/41730#issuecomment-1601373796

**Comment by anupama2501** [comment]
Verified on a roll back from v2.7.4 >> v2.7-head `fda4d4d` >> v2.7.4 

- Webhook on downstream clusters after running the script is restored to the min version `2.0.4+up0.3.4`

Verified on a roll back from v2.7.1 >> v2.7-head `fda4d4d` >> v2.7.1

- Webhook on downstream clusters is removed.

Ran the script by providing the rancher url, api token:  
```
read -s RANCHER_TOKEN && export RANCHER_TOKEN
read -s RANCHER_URL && export RANCHER_URL
bash adjust-downstream-webhook.sh --insecure-skip-tls-verify
```
