### ISSUE TITLE
Containers manually run with a docker-compose as a rancher stack

### ISSUE THREAD

**Issue by VPusher** [rancher/rancher#4191]
Is there a way so manually run stacks (`docker-compose up -d`) can be displayed as a independent Rancher stack in the Rancher UI (and not as several "Standalone Containers")? Is it doable with labels or something?

If not it could be a nice feature.

**Comment by LLParse** [comment]
This functionality already exists. What you need is our `rancher-compose` CLI (binaries available at the bottom right hand corner of the Rancher UI) along with a `rancher-compose.yml` in addition to your `docker-compose.yml`. There are several examples provided by the [community](https://github.com/rancher/community-catalog/tree/master/templates). 

The stack name will default to the working directory, so you might want to explicitly specify one:
`rancher-compose -p stackname up`

**Comment by VPusher** [comment]
@LLParse thanks for your answer but the point here was to not use `rancher-compose` CLI. Is there any way using only `docker-compose` ?

**Comment by deniseschannon** [comment]
@VPusher No, there is no way to use only docker-compose to have containers launched in Rancher in a stack. We only support rancher-compose, which can use the docker-compose.yml files. Can you explain why you wouldn't want to use rancher-compose?

**Comment by VPusher** [comment]
We do not always go through Rancher UI or use `rancher-compose` CLI to deploy stacks. Using a team Docker/Rancher server, may lead to several different uses. The beginners would use the UI to deploy quickly its own stack for dev/test purpose, but the sysadmins only use `docker-compose` level as they do on their local machine. Finally the Docker/Rancher server administrator want to know what has been deployed on its server: which containers are from the same stack... Also, sometimes, we want to keep things simple and only use the low level `docker-compose` for convenience (more portable, no dependency) with no overhead. Being able to see it in the Rancher UI, just as Docker UCP does, would be a nice feature.

**Comment by LLParse** [comment]
@VPusher If you deploy containers with `docker-compose`, your containers are all visible on the UI under `INFRASTRUCTURE > CONTAINERS`. Another screen which may be of use is `INFRASTRUCTURE > HOSTS`, which gives you a visual representation of your deployment topology (in the case of swarm). Rancher doesn't have any more context regarding how these containers should be organized, so no stack name may be inferred. Putting these containers in a default stack might make sense in this particular case, but will have the unintended side effect of exposing standalone system components such as Network Agents to the end user.

I don't understand concerns regarding `rancher-compose`, this tool is a statically-linked binary written in go just like `docker-compose` with no external dependencies, weighing in around 10MiB. It serves as a replacement for `docker-compose` and understands an augmented version of docker-compose schema. We keep the rancher-specific parts of the schema in `rancher-compose.yml` to enable reuse of the `docker-compose.yml` file in non-Rancher Docker environments. In your opinion, would merging the two files into one be simpler for end users?

Summarily, if you are not deploying from Rancher UI or using `rancher-compose`, you aren't fully harnessing Rancher's IaaS potential. However, you may still interact with the containers from the UI.

**Comment by VPusher** [comment]
@will-chan, thanks for you answer. I will give it a try with Swarm. Are you planning to set Swarm as the default Rancher environment ?

@LLParse Having 2 files is quite OK for me since it preserves `docker-compose.yml` from Rancher specific stuff. In the other hand, this file is tightly coupled with the `rancher-compose.yml` file since it may omit some mandatory deployment information for the stack/app. So they often go in pair. It's even more true for catalog stacks. So, yes I am wondering if a merged version both compatible with Docker Compose and Rancher Compose would be better/simpler. In fact, the 2 approaches have their pros/cons.

**Comment by vincent99** [comment]
We internally combine them into one structure so you can put it all into docker-compose.yml if you want.  But `docker-compose` doesn't accept/ignore keys it doesn't recognize.

**Comment by will-chan** [comment]
@VPusher Swarm is a selectable option when you create an environment.  We could add a setting in the future to make it the default though.

**Comment by VPusher** [comment]
@will-chan Great ! Moving to Swarm environment make the docker-compose projets appear ! Thank you.
