### ISSUE TITLE
[RFE] Simple Permissions endpoint for UI

### ISSUE THREAD

**Issue by ghost** [rancher/rancher#41929]
**Is your feature request related to a problem? Please describe.**
The UI needs a way for the logged in user to quickly and easily determine their permissions to an individual resource for the purposes of enabling/disabling UI elements based off a user's Global/Cluster/Project roles which may be directly assigned to a user or may be inherited via group membership, special care should be taken to account for both the "Admin" and "Restricted-Admin" roles, both of which adhere to special logic as it relates to cluster and project permissions.

**Describe the solution you'd like**
There's numerous ways to do this well from a FE perspective but we're looking for the following criteria:

- dense: minimize bytes sent over the wire for rancher instances that include more clusters/projects
- flattened: this endpoint shouldn't show individual permissions are bound to the user, just that it is bound to the user
- contextual: this endpoint only returns data for the current user
- easily filtered on the frontend: rather than making dozens of calls with individual filters we'd prefer to make a single call to the endpoint (or at most filtered to a single cluster) and the data should be structured such that keylookups by resource and project are quick (ideally without iterating over large arrays)
- fast and watchable: ideally the initial call to this endpoint should complete in under 250ms or faster (assuming minimal latency) and the FE should be able to watch for changes to permissions via websocket

**Describe alternatives you've considered**
Performing this type of permission mapping on the frontend requires a minimum of 4 (and upwards of 6 in some cases) separate endpoints, iterating over potentially large lists to discard duplicates, duplicating application logic embedded into the backend and still seems to miss a few important use-cases as our prototypes have shown.

**Comment by richard-cox** [comment]
This ties in with https://jira.suse.com/browse/SURE-6164

Generally, the UI needs to understand it can do action x to resource y in context z. For example
- Add a user as a member of a project
- Remove a user as an owner from a cluster
- Remove a user's restricted-admin's role
- Edit a project (i don't think this is achievable via the resource's link.update value)
- Add a configmap in a namespace

Historically this was done via either a global schema applying to all resources, or the contents of a resource's actions/links collection. We would receive updates to both over socket if anything changed.

We need to work together to understand how this can be done in a way that scales, automatically updates and integrates with the UI well

**Comment by gaktive** [comment]
Ties into fixing a bug reported by QA in https://github.com/rancher/dashboard/issues/9159 -- immediate blocker was addressed.

Initial attempts to address this were done in https://github.com/rancher/dashboard/pull/9184 but that's blocked on this ticket.

**Comment by gaktive** [comment]
Internal reference: SURE-6067

**Comment by gaktive** [comment]
Also this blocks https://github.com/rancher/dashboard/issues/8544

**Comment by cbron** [comment]
Moving out of Q1 in order to do this instead: https://github.com/rancher/rancher/issues/41301

**Comment by richard-cox** [comment]
Closing in preferences of SURE-6164
