### ISSUE TITLE
Swarm agent not being added to new hosts

### ISSUE THREAD

**Issue by getapp** [rancher/rancher#4192]
Rancher Version: v1.0.0

Docker Version: 1.10

OS: ubuntu

Steps to Reproduce: 
* create new swarm environment with 2 hosts
( add 3rd host

Results: 
3rd host does not have swarm agent

Expected:
for new hosts to have swarm agent

**Comment by deniseschannon** [comment]
@getapp Swarm agent is not global and does not need to be running on every host.

**Comment by deniseschannon** [comment]
@getapp If you still have questions about swarm, please re-open.
