### ISSUE TITLE
Can't start a stack if catalog version > 9 since v1.0.0

### ISSUE THREAD

**Issue by mcanevet** [rancher/rancher#4195]
Rancher Version: 1.0.0

Docker Version: 1.10.3

OS: Ubuntu 14.04 LTS

Steps to Reproduce: Create a catalog with version > 9, (template/foo/10) then try to start a stack from this template

Results: Stack does not start and there is no message in rancher server log

Expected: Stack starts

**Comment by mcanevet** [comment]
It used to work in v0.63.1

**Comment by raphink** [comment]
This is really blocking when using catalogs as a mean of deployment workflow.

**Comment by LLParse** [comment]
Reproduced bug:
https://github.com/LLParse/community-catalog/tree/issue-4195-test/templates/issue-4195

Empty stack appears but nothing is scheduled

**Comment by willseward** [comment]
@raphink Agreed. I haven't been able to deploy for 2 weeks due to url bugs, haha!

**Comment by vincent99** [comment]
@willseward if you told us about it 2 weeks ago it wouldn't have been in 1.0.0 :smile:

Anyway, this will be in 1.0.1.

**Comment by willseward** [comment]
No, sorry, a different issue was affecting the deployment. You all have been great about everything! 

Congrats on 1.0! I'm very proud to be introducing this technology to Texas Christian University

**Comment by wundram** [comment]
Awsome!   I was able to compile the fix from your PR branch and install the updated rancher-catalog-service and I now have deployments working again.   This should take care of us until v1.0.1.

**Comment by sangeethah** [comment]
Tested with Rancher server Version: 1.0.1-rc1.
Created a catalog with version > 9, (template/foo/10, template/foo/100) .
Able to start the catalog by choosing a version > 9 successfully.

**Comment by raphink** [comment]
Great, looking forward to it!
