### ISSUE TITLE
Terraform Provider rancher2 Ping Identity missing "Entity ID Field" in rancher2_auth_config_ping

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#41966]
If you provision a Rancher v2.6.8/9 instance and navigate to Users & Authentication -> Auth Provider -> Ping Identity, you can note the presence of the 'Entity ID Field'. Which does not appear to be exposed by the arguments on the rancher2_auth_config_ping resource of the Rancher2 Terraform Provider. (https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/auth_config_ping#argument-reference).

SURE-5596

**Comment by a-blender** [comment]
Test steps described [here](https://github.com/rancher/terraform-provider-rancher2/pull/1163#issue-1782964887). Please reach out to @eliyamlevy for any questions on testing this issue.

**Comment by ronhorton** [comment]
reopened for a TF rc to fix error:
`│ Error: Unsupported argument
│ 
│   on main.tf line 26, in resource "rancher2_auth_config_ping" "ping":
│   26:   entity_id_field = "rancher_tf"
│ 
│ An argument named "entity_id_field" is not expected here.`

**Comment by a-blender** [comment]
@ronhorton @eliyamlevy An rc has been cut to test this issue https://github.com/rancher/terraform-provider-rancher2/releases/tag/v3.1.0-rc4.

**Comment by ronhorton** [comment]
The rc is missing assets @a-blender

**Comment by ronhorton** [comment]
**Pass** verified on rancher2 provider `3.1.0-rc4`

Created ping indentity authconfig using newly added field; 'entity_id_field'
![2023-07-19_12-24-44.png](https://zube.io/files/rancher/dbc060084247b4160bf05abe866358c2-2023-07-19_12-24-44.png)
