### ISSUE TITLE
[BUG] System Chart repos failed to syncing after upgraded from 2.7.1 to 2.7.2+

### ISSUE THREAD

**Issue by bromine0x23** [rancher/rancher#41960]
**Rancher Server Setup**
- Rancher version: 2.7.1
- Installation option (Docker install/Helm Chart):
   - Helm Chart v2.7.1 on generic Kubernetes v1.18.20
- Proxy/Cert Details: Air-Gapped

**Information about the Cluster**
- Kubernetes version: v1.18.20
- Cluster Type (Local/Downstream): Local

**Describe the bug**

After upgraded from v2.7.1 to v2.7.2+, System Chart repos are in error with message like 
```
Git -C /var/lib/rancher-data/local-catalogs/v2/rancher-charts/4b40cac650031b74776e87c1a726b0484d0877c3ec137da0872547ff9b73a721 fetch origin -- 176424fce4f19ab8b01141dcec2d4453f075aad2 error: exit status 128, detail: error: Server does not allow request for unadvertised object 176424fce4f19ab8b01141dcec2d4453f075aad2
Git -C /var/lib/rancher-data/local-catalogs/v2/rancher-partner-charts/8f17acdce9bffd6e05a58a3798840e408c4ea71783381ecd2e9af30baad65974 fetch origin -- d3ad2ded37158ac75e44db651fc5ad223e3587d6 error: exit status 128, detail: error: Server does not allow request for unadvertised object d3ad2ded37158ac75e44db651fc5ad223e3587d6
```
While on rancher servers, got logs like:
```
2023/06/28 09:13:57 [ERROR] error syncing 'rancher-partner-charts': handler helm-clusterrepo-ensure: git -C /var/lib/rancher-data/local-catalogs/v2/rancher-partner-charts/8f17acdce9bffd6e05a58a3798840e408c4ea71783381ecd2e9af30baad65974 fetch origin -- d3ad2ded37158ac75e44db651fc5ad223e3587d6 error: exit status 128, detail: error: Server does not allow request for unadvertised object d3ad2ded37158ac75e44db651fc5ad223e3587d6
, requeuing
2023/06/28 09:13:57 [ERROR] error syncing 'rancher-charts': handler helm-clusterrepo-ensure: git -C /var/lib/rancher-data/local-catalogs/v2/rancher-charts/4b40cac650031b74776e87c1a726b0484d0877c3ec137da0872547ff9b73a721 fetch origin -- 176424fce4f19ab8b01141dcec2d4453f075aad2 error: exit status 128, detail: error: Server does not allow request for unadvertised object 176424fce4f19ab8b01141dcec2d4453f075aad2
, requeuing
```
When downgraded to 2.7.1, they return to active state.

**To Reproduce**

**Result**

**Expected Result**

The repos can sync normally.

**Screenshots**

![image](https://github.com/rancher/rancher/assets/5657337/3e5da6ee-ae61-424a-8bd1-2bce29f69992)

**Additional context**

**Comment by mjj29** [comment]
I experienced the same thing filed as https://github.com/rancher/rancher/issues/41878 - unfortunately for us a simple downgrade to 2.7.1 didn't work

**Comment by gchait** [comment]
Interestingly, in one 2.7.5 cluster it happens and in the other not.
Also, I have no way to downgrade (to any version) since the EKS cluster the chart is installed on is already at 1.26.

**Comment by gchait** [comment]
> Interestingly, in one 2.7.5 cluster it happens and in another it does not. Also, I have no way to downgrade (to any version) since the EKS cluster the chart is installed on is already at 1.26.
The problem in my case was a missing CRD, something related to etcdsnapshot.
The logs in the bad cluster complained about a nonexistent resource, which I initially mistook as a different issue.
IIRC, the logs said something with `kubernetes.io` while the actual CRD was `cattle`-something.
How did I find out about this? Well, out of desperation I tried to diff every aspect of the clusters.
Eventually I ended up `k get crd`ing and diffing the outputs, and the only one missing from the bad cluster was apparently the one that fixed (get crd yaml from the good cluster and apply on the bad one) both the complaints in the logs and the repo sync issue.

**Comment by bromine0x23** [comment]
It seems the commit rancher/charts@176424fce4f19ab8b01141dcec2d4453f075aad2 which `176424fce4f19ab8b01141dcec2d4453f075aad2` refer to not in branch release-v2.7.

**Comment by bromine0x23** [comment]
I try remove all existing System Chart repos and upgrade to v2.7.10 or v.2.8.2.
The Git error no longer appears, instead the repos stays in `In Progress`.

![image](https://github.com/rancher/rancher/assets/5657337/e6f2311c-0716-4a2a-be60-60f7de6df9f4)

**Comment by mvdheenux** [comment]
bump
issue still persists on 2.8.5, rollback doesn't resolve the issue. Along with etcd snapshots not being viewed in the webui, not sure if that's related in any way.

**Comment by bashilias** [comment]
This is not a organic solution and should be fixed, however I fixed it:

- Start an interactive shell in the cluster-agent pod:
`kubectl exec -it cattle-cluster-agent-blabla -n cattle-system -- sh`

- Go to the repositories. They are located in /var/lib/rancher-data/local-catalogs/v2. You can also find them using find:
`find / -name config -type f -path '*/.git/config'`

- Perform a git pull in the directories of the repo.
example:
`sh-4.4# cd /var/lib/rancher-data/local-catalogs/v2/rancher-charts/4b40cac650031b74776e87c1a726b0484d0877c3ec137da0872547ff9b73a721/`
`sh-4.4# git pull`

- Do a refresh of the repos again in the web UI or via the terminal with:

`for i in $(kubectl get clusterrepo -o=jsonpath="{.items[*]['metadata.name']}"); do kubectl patch clusterrepo $i --type='json' -p="[{'op': 'replace', 'path': '/spec/forceUpdate', 'value':'$(gdate +'%Y-%m-%dT%H:%M:%SZ' -d '5 seconds ago')'}]"; done`
