### ISSUE TITLE
[BUG] rancher 2.7.5 version update panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by taehwanlee** [rancher/rancher#41992]
Rancher Server Setup

Rancher version: v2.7.5
Installation option (Docker install/Helm Chart):
Docker install
Proxy/Cert Details:
Information about the Cluster

Kubernetes version: 1.27
Cluster Type (Local/Downstream):
If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):
User Information

What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
If custom, define the set of permissions:
Describe the bug

Memory leak occurs when using Rancher UI on Explorer

To Reproduce

Result

Expected Result

Screenshots
![image](https://github.com/rancher/rancher/assets/20853900/f5560bec-e49b-468b-83ac-e2f6010b7cdb)

**Comment by taehwanlee** [comment]
helm-operation-pt5cn exited 123

**Comment by taehwanlee** [comment]
![image](https://github.com/rancher/rancher/assets/20853900/a2044375-725f-4f75-9cff-dcbab8d566fc)

**Comment by Josh-Diamond** [comment]
Hello, kubernetes version `v1.27` is not yet supported in Rancher.

Kubernetes versions supported in Rancher `v2.7.5` may be found here:
https://www.suse.com/suse-rancher/support-matrix/all-supported-versions/rancher-v2-7-5/

**Comment by taehwanlee** [comment]
Is there any way to support kubernetes 1.27 in Rancher?

**Comment by snasovich** [comment]
@taehwanlee , K8s 1.27 is now supported in Rancher v2.8.0 per https://github.com/rancher/rancher/issues/41840. Closing this issue as a duplicate. Please reopen if you're still having issues.
