### ISSUE TITLE
[2.7] Update BCI versions in base images to `15.5`

### ISSUE THREAD

**Issue by macedogm** [rancher/rancher#41998]
BCI version `15.5` was released in June. `15.4` will be EOL in December 31st. This update should have zero impact in Rancher and Rancher Agent images.

Creating this issue in case QA wants to do any specific tests. I expect that with our regular flow of creating daily `-head` images and day to day tests from our dev teams should be enough in terms of QAing.

It's important do to this now before we branch for 2.8.

**Comment by bmdepesa** [comment]
@macedogm is the issue for tracking the development work as well?

**Comment by macedogm** [comment]
The development was already done and merged in PR https://github.com/rancher/rancher/pull/41996.

I opened in case QA wants to do specific checks and tests.

**Comment by bmdepesa** [comment]
We will run automation against v2.7-head to test this.

**Comment by igomez06** [comment]
QA validation:

Rancher Server Setup

Rancher version: v2.7.7-rc3(which contains new BCI version) HA

v2/validation all automation tests
Status: PASS
