### ISSUE TITLE
Rancher does not support SSL SQL

### ISSUE THREAD

**Issue by marek-stopka** [rancher/rancher#4199]
Rancher Version: 1.0

Docker Version:

OS: CentOS 7.2

Rancher 1.0 does not support SSL MySQL, due to security we deploy all non local-host MySQL connections using TLS / SSL connection, sadly Rancher does not seem to support SSL MySQL. Can this be put on a road map? Perhaps a sponsored feature?

**Comment by ibuildthecloud** [comment]
@marek-stopka It most likely works with an incarnation of settings.  Do you have experience with setting up JDBC w/ SSL?  We use https://mariadb.com/kb/en/mariadb/about-mariadb-connector-j/.  I'm not as experienced myself, but I can probably point you in the right direction to figure it out.  Surprisingly this comes up very little.

**Comment by ibuildthecloud** [comment]
@marek-stopka Okay... you can set the JBDC url directly with environment variables, below is the default.

`docker run -p 8080:8080 -e "CATTLE_DB_CATTLE_MYSQL_HOST=hostname" -e "CATTLE_DB_CATTLE_MYSQL_URL=jdbc:mysql://hostname:3306/cattle?useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&prepStmtCacheSize=517&cachePrepStmts=true&prepStmtCacheSqlLimit=4096&socketTimeout=60000&connectTimeout=60000" rancher/server`

I assume you'd also need to bind mount in some certificates.

**Comment by matthew342** [comment]
@marek-stopka Did you ever get this working? Wrestling with the same issue....

**Comment by marek-stopka** [comment]
@matthew342 I deployed it over Cloud SQL Proxy, but I plan to get back to using direct SSL little later. I will post here any progress, and I would like to kindly ask you for the same.

**Comment by matthew342** [comment]
@marek-stopka Spent hours on this today with no luck. I created a .jsk keystore from my Cloud SQL client certificate using the process outlined in [this blog post](http://xacmlinfo.org/2014/06/13/how-to-keystore-creating-jks-file-from-existing-private-key-and-certificate/). I was able to get it to start trying to connect over SSL using the below environment variable, but I can't get it to actually use the client certificate, so mysql returns access denied:

```
CATTLE_DB_CATTLE_MYSQL_URL=jdbc:mysql://<ip address>:3306/cattle?useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&prepStmtCacheSize=517&cachePrepStmts=true&prepStmtCacheSqlLimit=4096&socketTimeout=60000&connectTimeout=60000&useSSL=true&clientCertificateKeyStoreUrl=file:/keys/cattleKeyStore.jks&clientCertificateKeyStorePassword=<password>&serverSslCert=/keys/cattle-ca.pem"
```

**Comment by dodekeract** [comment]
Can we change this to `kind/security`? Unencrypted database traffic is IMHO a huge security flaw.
Also is there any progress on this? Has anybody got it to work yet? I'd like to deploy this for @attach-live.

**Comment by ibuildthecloud** [comment]
The hardest part about this is getting the certs right.  We can support SSL connection if people are willing to bind mount in the DB server CA pem and client jks.  The client jks is rocket science to create.

**Comment by kvaes** [comment]
+1

kvaes@kvaesranchertest01:~# mysql -h mymysqlhost -u mylittleuser -p
Enter password: ****************
ERROR 2001 (28000): SSL connection is required. Please specify SSL options and retry.

This is a (good!) requirement from the MySQL service provider I'm using.

**Comment by ocasta** [comment]
This really needs to be there, or at least a documentation How to. If you are using an external DB its going to be over SSL unless you're crazy.

**Comment by vincent99** [comment]
This should be theoretically possible in 1.5 for cattle but needs documentation and support in catalog.

**Comment by kvaes** [comment]
What should we add in terms of parameters? -e ENFORCESSL=TRUE :)

**Comment by onnoll** [comment]
is there any documentation about how to do this already?

**Comment by failedguidedog** [comment]
@vincent99 Is this possible in any way? Even unofficial?

**Comment by kvaes** [comment]
@ibuildthecloud ; Any suggestion/insight on this? Imho, one should not use unencrypted DB traffic in cloud setups. Actually, by default, Azure MySQL enforces SSL connections. 

Though I must admit, that the mysql client is kinda odd in regards to the SSL traffic, where the CA cert(s) need to be added and so forth.

**Comment by nesc58** [comment]
@janeczku thank you for linking the files and update the gist file (How to setup Rancher with an external MySQL DB over SSL). I've tried this but failed. Now it makes sense why this failed.

First I was really excited about rancher and it was the first choice for my container orchestration / application. But without encrypted traffic rancher is useless for me. It is highly recommended to encrypt the connections.

I only need an encrypted database connection. No authorization with x509. I enabled SSL using REQUIRE SSL (not REQUIRE X509) to allow login with password. My firewall would deny all other ips than my rancher master servers so the authorization functionality not needed.

I thought about something like this database connection string: `CATTLE_DB_CATTLE_MYSQL_URL: 'jdbc:mysql:loadbalance://<host1:port1>,<host2:port2>,<host3:port3>/<db>?user=<db-user>&password=<user-password>&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&prepStmtCacheSize=50&cachePrepStmts=true&prepStmtCacheSqlLimit=4096&socketTimeout=60000&connectTimeout=60000&useSSL=true&loadBalanceConnectionGroup=first&loadBalanceEnableJMX=true'`
Can this connection string work?

Whats about adding the following params:
`db-use-ssl` for setting useSSL=true/false (maybe requireSSL too?)
`db-host` should contain a list of hosts to use the jdbc-loadbalancing?
`db-allowInvalidCertificates` to use self-signed certificates without a valid CA

Is it an option implement the using of the environment variable `CATTLE_DB_CATTLE_MYSQL_URL`? (maybe as an export option (use on own risk)?

**Comment by janeczku** [comment]
@nesc58 and others

You can make MySQL SSL working by following the steps here: [Setting up Rancher with MySQL SSL](https://gist.github.com/janeczku/ec138e688ad727b5612bd1184135db72)

**Comment by laszlocph** [comment]
I managed to get through the SSL connection issue following the guide by @janeczku - big thanks for that.
Then I hit #9018 :(

**Comment by janeczku** [comment]
@laszlocph see https://github.com/rancher/rancher/issues/9018#issuecomment-309425723 for the fix. I.e. for Azure MySQL SSL set CATTLE_DB_CATTLE_GO_PARAMS to:

```CATTLE_DB_CATTLE_GO_PARAMS="tls=true&allowNativePasswords=true"```

**Comment by laszlocph** [comment]
@janeczku Brilliant, it works now! Thanks a million!

**Comment by galal-hussein** [comment]
Rancher server: v1.6.9-rc3

I was able to follow the documentation http://rancher.com/docs/rancher/v1.6/en/installing-rancher/installing-server/#launching-rancher-server-with-mysql-over-ssl and set up Rancher with external MySQL over SSL
