### ISSUE TITLE
[RFE] Rancer 2.7.5 kubernetes 1.27 support

### ISSUE THREAD

**Issue by taehwanlee** [rancher/rancher#42008]
Is there any way to support kubernetes 1.27 in Rancher?
If yes, please tell me how

**Comment by funkel1989** [comment]
I tried with rancher 2.7.5 and i think it has kuberentes 1.27.0 support but not 1.27.3 which is what I'm using. I'm also stuck as I'm not interested in downgrading my cluster at this time.

**Comment by cbron** [comment]
Hello, there are several issues already tracking 1.27 support and when they will land. Please review existing tickets before opening new ones. 
https://github.com/rancher/rancher/issues/41840
