### ISSUE TITLE
Upgrade path v0.63.1 to v1.0.0?

### ISSUE THREAD

**Issue by CumpsD** [rancher/rancher#4201]
Is there a specific upgrade path from v0.63.1 to v1.0.0 or does this still apply: http://docs.rancher.com/rancher/upgrading/ ?

**Comment by deniseschannon** [comment]
Those docs still apply.

**Comment by CumpsD** [comment]
![image](https://cloud.githubusercontent.com/assets/1201644/14221999/f116b29a-f86b-11e5-8e91-ef2aeeccf35b.png)

Yay :+1:
