### ISSUE TITLE
Rebase Monitoring to 45.x

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#42019]
Monitoring needs to be updated to the latest upstream, which at the time of writing this ticket is 45.x. Opni will be responsible, but Night's Watch will have to train them.

**Comment by fentonfentonfenton** [comment]
be great to see this in!

**Comment by vivek-shilimkar** [comment]
Fresh install and upgrade checks for the monitoring chart were performed on following OSes on RKE1 cluster.

| OS & Cluster type | Fresh Install Checks | Chart upgrade checks |
|---|---|---|
| SLES - RKE1 (node driver) | PASS | PASS |  
| Rocky - RKE1 (node driver) | PASS | PASS |  
| OpenSuse-Leap - RKE1 (node driver) | PASS | PASS |  
| RHEL - RKE1 (node driver) | PASS | PASS |  


In addition following combination was also tested for fresh install checks.

Configuration | k8s version | PASS/FAIL | Notes
-- | -- | -- | --
RKE1 | v1.25 | PASS |  
RKE1 hardened | v1.26 | PASS |  
RKE2 | v1.27 | PASS |  
RKE2 hardened | v1.25 | PASS |  
K3S | v1.26 | PASS |  
K3S hardened | v1.27 | PASS |

**Comment by rishabhmsra** [comment]
Completed fresh install and upgrade checks for monitoring chart on below OS and cluster types:

Cluster | Fresh Install | Upgrade
-- | -- | --
Ubuntu RKE1 (node driver) | PASS | PASS |  
Ubuntu RKE2 (node driver) | PASS | PASS |  
Ubuntu K3S (node driver) | PASS | PASS |  
Hosted GKE | PASS | PASS |  
Hosted AKS | PASS | PASS |  
Hosted EKS | PASS | PASS |  
Windows(RKE2 custom) | PASS | PASS |  

All checks completed from monitoring v2 rebase test plan, hence closing this issue.
