### ISSUE TITLE
[BUG] cattle-impersonation error preventing shell usage and kubectl usage

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#42020]
**Rancher Server Setup**
- Rancher version: 2.6.11

**Describe the bug**
The customer creates a new local user and adds them as a member to a downstream AKS cluster. Creates a new Project and namespace in the cluster. Adds the same user as Project Owner. Logs in as that user, and the user can see the cluster and Project. But not the namespace. The user tries to open a shell in Rancher or run kubectl commands (with kubeconfig downloaded from UI) and gets an impersontation error:

`Error from server (InternalError): an error on the server ("unable to create impersonator account: error setting up impersonation for user u-tzrcv: failed to get secret for service account: cattle-impersonation-system/cattle-impersonation-u-tzrcv, error: timed out waiting for the condition") has prevented the request from succeeding (get pods)`

Then later, he was able to access the shell and got these errors when trying to see resources in that namespace:

```
k get all -n test-suse
 Error from server (Forbidden): pods is forbidden: User "u-45skq" cannot list resource "pods" in API group "" in the namespace "test-suse"
 Error from server (Forbidden): replicationcontrollers is forbidden: User "u-45skq" cannot list resource "replicationcontrollers" in API group "" in the namespace "test-suse"
 Error from server (Forbidden): services is forbidden: User "u-45skq" cannot list resource "services" in API group "" in the namespace "test-suse"
 Error from server (Forbidden): daemonsets.apps is forbidden: User "u-45skq" cannot list resource "daemonsets" in API group "apps" in the namespace "test-suse"
 Error from server (Forbidden): deployments.apps is forbidden: User "u-45skq" cannot list resource "deployments" in API group "apps" in the namespace "test-suse"
 Error from server (Forbidden): replicasets.apps is forbidden: User "u-45skq" cannot list resource "replicasets" in API group "apps" in the namespace "test-suse"
 Error from server (Forbidden): statefulsets.apps is forbidden: User "u-45skq" cannot list resource "statefulsets" in API group "apps" in the namespace "test-suse"
 Error from server (Forbidden): horizontalpodautoscalers.autoscaling is forbidden: User "u-45skq" cannot list resource "horizontalpodautoscalers" in API group "autoscaling" in the namespace "test-suse"
 Error from server (Forbidden): cronjobs.batch is forbidden: User "u-45skq" cannot list resource "cronjobs" in API group "batch" in the namespace "test-suse"
 Error from server (Forbidden): jobs.batch is forbidden: User "u-45skq" cannot list resource "jobs" in API group "batch" in the namespace "test-suse"
```
This is happening on 1 Rancher environment with some (not all) downstream AKS clusters. Problem is not seen on RKE clusters. Rancher is on VMware.

In another Rancher environment hosted on AKS, none of the AKS downstream clusters has the problem.

They started seeing the problem with new clusters on Rancher 2.6.9. They are on 2.6.11 now and still see the issue.

He said the issue is intermittent, some days it might work fine and there is no rhyme or reason to when it works vs when it doesn't work.

This is currently preventing us from successfully provisioning project spaces for our internal customers. Impact is becoming pretty significant as we are approaching SLA on these requests.

**To Reproduce**
Created local account in Rancher
Created project on downstream cluster
Granted account Project Owner on that project
Created namespace under project
Logged in as account, no namespaces are shown under the project
Rancher shell and Kubectl commands using Kubeconfig downloaded from GUI give imeprsonation errors

SURE-6352

**Comment by samjustus** [comment]
#41632

**Comment by cmurphy** [comment]
# Validation

## Root Cause

The service account object in memory was out of date, so Rancher could not look up the impersonation account token on it.

## Areas or cases that should be tested

All interactions with the local or downstream cluster:
- use the cluster explorer UI
- install apps
- use the dashboard shell
- download a kubeconfig and use kubectl

Also test using different auth providers.

## What areas could experience regressions

The issue was introduced by this commit https://github.com/rancher/rancher/commit/8f4d60c2228de4672a469d07213778ce53df9433 - see the github issue related to this security advisory https://github.com/rancher/rancher/security/advisories/GHSA-8c69-r38j-rpfj

That change was in turn a fix for a change introduced in https://github.com/rancher/rancher/pull/38113, specifically "code changes to handle secret creation for service account token, it's no longer created automatically for 1.24". Either of these areas could experience regressions.

## Are the repro steps accurate/minimal?

These steps approximate what the user was experiencing, but the problem was intermittent and it is difficult to cause the exact scenario described in the issue:

1. Add a user to a project
2. As that user, download the kubeconfig for the user.
3. On the cluster, there should be a cattle-impersonation-u-xxx service account in the cattle-impersonation-system namespace, and clusterrole and clusterrolebinding cattle-impersonation-u-xxx.
4. Delete the clusterrolebinding.
5. Edit the service account. Under secrets, replace the secret name with a nonexistent secret ("foo").
6. Use the kubeconfig to make a request in a namespace in the project ("kubectl -n my-ns get pods")

Without this change, this will result in a timeout error. With this change, the request should succeed.

**Comment by Priyashetty17** [comment]
**QA to validate:**

<table>
    <tbody>
        <tr>
            <th>#</th>
            <th>Scenario</th>
            <th>Steps</th>
            <th>Pass/Fail</th>
        </tr>
        <tr>
            <td>1</td>
            <td>Validate the fix for Service Account Token Lookup Failure. </td>
            <td>
                <ol>
                    <li> Create a local user "testuser1". </li> 
                    <li> Create a downstream AKS cluster. </li>
                    <li> Create a project "testproject1" in the downstream AKS cluster. </li>
                    <li> Add "testuser1" as a "Project Owner" to the project. </li>
                    <li> Create a namespace "testns1" in the project. </li>
                    <li> Login as "testuser1" and verify that the namespace is displayed under the project. </li>
                    <li> Create a deployment in the namespace "testns1". </li>
                    <li> Access Rancher shell and execute: kubectl get pods -n testns1. Verify that there are no impersonation errors. </li>
                    <li> Download the kubeconfig file and execute: kubectl get pods -n testns1. Verify that there are no impersonation errors. </li>
                    <li> Login as "admin" and verify that the following exists on the downstream cluster in the cattle-impersonation-system namespace: cattle-impersonation-u-xxx ServiceAccount, cattle-impersonation-u-xxx ClusterRole and cattle-impersonation-u-xxx ClusterRoleBinding. </li>
                    <li> Delete the cattle-impersonation-u-xxx ClusterRoleBinding. </li>
                    <li> Edit the cattle-impersonation-u-xxx service account and update secrets with a non-existent secret "foo". </li>
                    <li> Using the kubeconfig file, execute: kubectl get pods -n testns1. Verify that there are no impersonation errors. </li>
                    <li> Login as "testuser1". Access Rancher shell and execute: kubectl get pods -n testns1. Verify that there are no impersonation errors. </li>
                </ol>
            </td>
            <td><br><br></td>
        </tr>
        <tr>
            <td>2</td>
            <td>Repeat Test #1 with Github user. </td>
            <td>
                <ol>
                    <l> </l>
                </ol>
            </td>
            <td><br><br></td>
        </tr>
        <tr>
            <td>3</td>
            <td>Upgrade from v2.6.11 to v2.7-head and validate the fix. </td>
            <td>
                <ol>
                    <li> Create a rancher server v2.6.11. </li> 
                    <li> Create a local user "testuser1". </li> 
                    <li> Create a downstream AKS cluster. </li>
                    <li> Create a project "testproject1" in the downstream AKS cluster. </li>
                    <li> Add "testuser1" as a "Project Owner" to the project. </li>
                    <li> Create a namespace "testns1" in the project. </li>
                    <li> Login as "testuser1" and verify that the namespace is displayed under the project. </li>
                    <li> Create a deployment in the namespace "testns1". </li>
                    <li> Access Rancher shell and execute: kubectl get pods -n testns1. Verify that there are no impersonation errors. </li>
                    <li> Download the kubeconfig file and execute: kubectl get pods -n testns1. Verify that there are no impersonation errors. </li>
                    <li> Login as "admin" and verify that the following exists on the downstream cluster in the cattle-impersonation-system namespace: cattle-impersonation-u-xxx ServiceAccount, cattle-impersonation-u-xxx ClusterRole and cattle-impersonation-u-xxx ClusterRoleBinding. </li>
                    <li> Upgrade the cluster to v2.7-head. </li>
                    <li> Delete the cattle-impersonation-u-xxx ClusterRoleBinding. </li>
                    <li> Edit the cattle-impersonation-u-xxx service account and update secrets with a non-existent secret "foo". </li>
                    <li> Using the kubeconfig file, execute: kubectl get pods -n testns1. Verify that there are no impersonation errors. </li>
                    <li> Login as "testuser1". Access Rancher shell and execute: kubectl get pods -n testns1. Verify that there are no impersonation errors. </li>
                </ol>
            </td>
            <td><br><br></td>
        </tr>
        <tr>
            <td>4</td>
            <td>Fresh install - Regression test for secret rotation. </td>
            <td>
                <ol>
                    <li> As a standard user, create node driver provisioned downstream clusters: RKE1, RKE2, K3S. </li>
                    <li> On each downstream cluster explorer >> select cattle-system namespace >> navigate to secrets and note the value of the "cattle-token" secret. </li>
                    <li> Delete the token and re-deploy cattle-cluster-agent. </li>
                    <li> Install monitoring chart and verify that the chart is successfully installed. </li>
                    <li> Verify that the re-generated token in "cattle-token" secret is not the same as Step2. </li>
                </ol>
            </td>
            <td><br><br></td>
        </tr>
        <tr>
            <td>5</td>
            <td>Upgrade from v2.6.11 to v2.7-head - Regression test for secret rotation. </td>
            <td>
                <ol>
                    <li> Start with Rancher server v2.6.11. </li>
                    <li> As a standard user, create node driver provisioned downstream clusters: RKE1, RKE2, K3S. </li>
                    <li> On each downstream cluster explorer >> select cattle-system namespace >> navigate to secrets and note the value of the "cattle-token" secret. </li>
                    <li> Upgrade the cluster to v2.7-head. </li>
                    <li> Delete the token and re-deploy cattle-cluster-agent. </li>
                    <li> Install monitoring chart and verify that the chart is successfully installed. </li>
                    <li> Verify that the re-generated token in "cattle-token" secret is not the same as Step3. </li>
                </ol>
            </td>
            <td><br><br></td>
        </tr>
    </tbody>
</table>

**Comment by Priyashetty17** [comment]
Validated all scenarios mentioned [here](https://github.com/rancher/rancher/issues/42020#issuecomment-1631120454) with v2.7-027246f77f03b82660dc2e91df6bf2cd549163f0-head

**Comment by cmurphy** [comment]
# Release note template

**Synopsis of issue**: Users newly added to a cluster or project would sometimes see an error relating to "impersonation" ending with "error: timed out waiting for the condition" when making a request in Cluster Explorer or with kubectl.
**Resolved (or not)**:  resolved
**Versions**: 2.7.1, 2.7.2, 2.7.3, 2.7.4, 2.7.5, 2.7.6
