### ISSUE TITLE
[2.7.0] Unable to import CIS-hardened (cis-1.23) RKE2 v1.25.10+rke2r1 cluster into Rancher due to cluster-agent permissions

### ISSUE THREAD

**Issue by jason-w-stanley** [rancher/rancher#42039]
**Rancher Server Setup**
- Rancher version: 2.7.2
- Installation option (Docker install/Helm Chart): helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
   RKE2 v1.23.17+rke2r1
- Proxy/Cert Details: letsEncrypt

**Information about the Cluster**
- Kubernetes version: RKE2 v1.25.10+rke2r1 ***CIS profile = 1.23***
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):
   Tried to manually import via command listed on Rancher UI, the cluster-register container will not run on RKE2 for 1.25 with CIS profile turned on as it tries to run as root

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:
admin

**Describe the bug**

 Tried to manually import via command listed on Rancher UI, the cluster-register container will not run on RKE2 for 1.25 with CIS profile turned on as it tries to run as escalated, doesnt set security context, etc.  Doing describe on the replica set
 
 `kubectl describe replicaset.apps/cattle-cluster-agent-5f78ffc6f5 -n cattle-system`
 ```
 Events:
  Type     Reason        Age   From                   Message
  ----     ------        ----  ----                   -------
  Warning  FailedCreate  49m   replicaset-controller  Error creating: pods "cattle-cluster-agent-5f78ffc6f5-bkxh5" is forbidden: violates PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "cluster-register" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "cluster-register" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "cluster-register" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "cluster-register" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
  Warning  FailedCreate  32m   replicaset-controller  Error creating: pods "cattle-cluster-agent-5f78ffc6f5-srt2b" is forbidden: violates PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "cluster-register" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "cluster-register" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "cluster-register" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "cluster-register" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
  Warning  FailedCreate  15m   replicaset-controller  Error creating: pods "cattle-cluster-agent-5f78ffc6f5-h6cgr" is forbidden: violates PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "cluster-register" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "cluster-register" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "cluster-register" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "cluster-register" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
```
 
**To Reproduce**

Create RKE2 1.25.x cluster with CIS profile turned on and manually run registration command produced by Rancher Server

**Result**
Registration fails due to container running with escalated privledge.

**Expected Result**
Cluster would register with Rancher Server

**Screenshots**

**Additional context**

**Comment by Oats87** [comment]
FYI, K8s 1.25.x is NOT supported by Rancher v2.7.0 (ref: https://www.suse.com/suse-rancher/support-matrix/all-supported-versions/rancher-v2-7-0/) You will need to update to at least `v2.7.2`: https://www.suse.com/suse-rancher/support-matrix/all-supported-versions/rancher-v2-7-2/ 

Given you are attempting to import a `v1.25` cluster into Rancher, you'll need to exempt a set of namespaces from the Pod Security Admission policy that prevents Rancher components from running. See the Rancher documentation here: https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/psa-config-templates#exempting-required-rancher-namespaces

**Comment by jason-w-stanley** [comment]
copy thanks, we did upgrade to 2.7.2 before testing the 1.25 registration, will update above.  So for all downstream clusters I need to add exceptions for rancher cattle agent?

**Comment by Oats87** [comment]
> copy thanks, we did upgrade to 2.7.2 before testing the 1.25 registration, will update above. So for all downstream clusters I need to add exceptions for rancher cattle agent?

Yes, you'll need to exempt the namespaces listed in the documentation. The `cattle-cluster-agent` requires permissions that are not normally permissible by the CIS policy, but are necessary to enable full functionality of Rancher.

**Comment by dsmithbauer** [comment]
Interesting. Prior to Kubernetes 1.25 and the deprecation of PSPs, it was not necessary to exempt any Rancher namespaces from the default globally restrictive PSP the CIS profile enabled. Is this new requirement due to a change in behavior between how PSPs worked and how PSAs work now or due to changes in the Rancher requirements? Is the only solution to fully exempt those namespaces from the more restrictive PSA or is a less open solution possible? Thanks
