### ISSUE TITLE
[Enhancement]-[Rancher-Agent] Helm Repositories Sync Intervals

### ISSUE THREAD

**Issue by Amos-85** [rancher/rancher#42033]
### Problem:

We are using rancher `v2.7.5` and when I add helm repository through rancher ui, the rancher agent sync the helm repository every 5 minutes and I can't control the sync intervals.

After checking the logs of rancher-agent, I see the following every 5 minutes:
```
time="2023-07-07T11:12:24Z" level=info msg="Downloading repo index from https://<mydomain>.jfrog.io/artifactory/api/helm/helm/index.yaml"
time="2023-07-07T11:17:24Z" level=info msg="Downloading repo index from https://<mydomain>.jfrog.io/artifactory/api/helm/helm/index.yaml"
time="2023-07-07T11:22:24Z" level=info msg="Downloading repo index from https://<mydomain>.jfrog.io/artifactory/api/helm/helm/index.yaml"
```
Since we are using Jfrog artifactory virtual repository which aggregate multiple helm repositories, the `index.yaml` is around 12 MB.
If we add this helm virtual repository to another multiple clusters plus request every 5 minutes a file of 12 MB, the billing of data transfer become super high.

### Suggested Solution:

- Add a flag to control sync intervals on `ClusterRepo` crd, this flag needs also to support `0` minutes for disabling completely the sync intervals.
- Add this flag also to Rancher UI when add a new helm repository.

**Comment by dheardal** [comment]
This is much worse now that the sync interval has been increased to 6 hours, is it possible to make this configurable per repository?
