### ISSUE TITLE
[BUG] Wrong base64-encoding used to encode DockerConfigJSON for private registries

### ISSUE THREAD

**Issue by rookies** [rancher/rancher#42044]
**Rancher Server Setup**
- Rancher version: 2.7.4
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): k3s
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version:  v1.24.6+k3s1
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Custom (RKE2)

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): Admin
  - If custom, define the set of permissions:

**Describe the bug**
After our upgrade from Rancher 2.7.1 to 2.7.4, some of the clusters we manage using Rancher could not upgrade the cattle-cluster-agent. They were stuck in state _Provisioning_ with the following error message in the Rancher UI:
`Error while applying agent YAML, it will be retried automatically: exit status 1,
clusterrole.rbac.authorization.k8s.io/proxy-clusterrole-kubeapiserver unchanged
clusterrolebinding.rbac.authorization.k8s.io/proxy-role-binding-kubernetes-master unchanged
namespace/cattle-system unchanged
serviceaccount/cattle unchanged
clusterrolebinding.rbac.authorization.k8s.io/cattle-admin-binding unchanged
secret/cattle-credentials-9b0bba3 unchanged
clusterrole.rbac.authorization.k8s.io/cattle-admin unchanged
deployment.apps/cattle-cluster-agent configured
service/cattle-cluster-agent unchanged
Error from server (BadRequest): error when creating "./management-statefile_path_redacted": Secret in version "v1" cannot be handled as a Secret: illegal base64 data at input byte 123`

Our investigation showed that the issue was with the `cattle-private-registry` Secret and at byte 123 of the Secret data Rancher tried to apply was an underscore, which is in fact not a valid character for standard base64 but only used for URL-safe base64.

My guess is that this is caused by this line, which should use standard base64 instead of URL-safe base64: https://github.com/rancher/rancher/blob/6d5373ca2b06350362b29954718b73d46d114381/pkg/cluster/private_registry.go#L152

**To Reproduce**
1. Create a new cluster
2. Configure a private registry with a specific set of credentials that causes the generated DockerConfigJSON to contain an underscore when base64-encoded (I can't provide an example because I don't want to leak any secrets)

**Result**
The cattle-cluster-agent can't be deployed and Rancher UI displays the error message mentioned above.

**Expected Result**
Everything should work, the cattle-cluster-agent should be deployed successfully.

**Comment by Oats87** [comment]
@jakefhyde do you know why we are using `URLEncoding` instead of `StdEncoding` here?

**Comment by jakefhyde** [comment]
@Oats87 No idea, initially it was implemented with `URLEncoding` ~4 years ago, if the blame is to be believed, I'll test with `StdEncoding` and get a PR up.

**Comment by thaneunsoo** [comment]
This issue doesn't need to be automated.

**Comment by susesgartner** [comment]
Ticket #42044 - Test Results - ✅ 
---
Verified with (HA Helm or Docker) on Rancher `v2.8-head`:

Scenario 1 -
1. Create a custom cluster
2. Add a private registry to the custom cluster with credentials that cause URL base64 encoding to contain an underscore

Result: No issues seen on the cluster and everything looked to be in a normal state.
