### ISSUE TITLE
Pin the hosted-provider charts to a specific version

### ISSUE THREAD

**Issue by richardcase** [rancher/rancher#42040]
**Is your feature request related to a problem? Please describe.**
When there are newer versions of the charts for the hosted providers (EKS, AKS, GKE) Rancher will install the chart automatically. This has caused some issues with chart versions being installed that we didn't want. And its less deterministic which version of the chart is installed.

**Describe the solution you'd like**
For each Rancher release, we want to pin the version of the hosted provider charts that are installed with that release. This is what is done with `rancher-webhook`.

If we need to do an out-of-band release to fix a issue we will support changing the version via a system setting. This would be something that support would direct a customer to do.

**Additional context**

See the rancher-webhook implmenetation for an example: https://github.com/rancher/rancher/pull/41302

**PR's**

- [x] https://github.com/rancher/rancher/pull/44042

**Comment by mjura** [comment]
Initial implementation which we can use was already submitted and we have to wait until it will be merged https://github.com/rancher/rancher/pull/42304/files

**Comment by cpinjani** [comment]
Updating the target milestone as PR is merged in v2.9
cc: @kkaempf @mjura

**Comment by cpinjani** [comment]
Blocked on https://github.com/rancher/charts/pull/3409

**Comment by cpinjani** [comment]
Validated on build:
`v2.9-44e346d1228543c202a7f7a74a8d3277ca250bbe-head`

**Test case:**
Test Rancher installs AKS version via CATTLE_AKS_OPERATOR_VERSION environment variable.

**Install command:**
Docker Install:
`docker run -d --restart=unless-stopped -p 80:80 -p 443:443 -e CATTLE_AKS_OPERATOR_VERSION=104.0.0+up1.3.0-rc1 -e CATTLE_BOOTSTRAP_PASSWORD=rancherpassword --privileged rancher/rancher:v2.9-head
`

or

Helm Install:
`helm install rancher --devel rancher-latest/rancher --namespace cattle-system --set hostname=<HOSTNAME> --set replicas=1 --set global.cattle.psp.enabled=false --set rancherImageTag=v2.9-head --set 'extraEnv[0].name=CATTLE_AKS_OPERATOR_VERSION' --set 'extraEnv[0].value=104.0.0+up1.3.0-rc1' --wait
`

**Results:**
- Rancher installs and is up and running
- AKS CRDs are not initialized yet
- Provision an downstream AKS cluster, now AKS crds are initialized
- AKS version deployed is:
```
# kubectl describe deployment aks-config-operator -n cattle-system | grep Image
    Image:  rancher/aks-operator:v1.3.0-rc2
```
Expected version is **rancher/aks-operator:v1.3.0-rc1**, provided while Rancher install command.

@mjura Can you please take a look.
Also as in PR, it seems pinned version needs to be provided in build.yaml ? https://github.com/rancher/rancher/pull/42000

**Comment by mjura** [comment]
I have tested it again and everything works as expected.

To use it, please do following steps:
1. Change Rancher deployment and add:

```
        env:
        - name: CATTLE_GKE_OPERATOR_VERSION
          value: 104.0.0+up1.9.0
        - name: CATTLE_EKS_OPERATOR_VERSION
          value: 104.0.0+up1.9.0
```

2. Apply changes to Rancher k8s cluster 
3. Delete old eks and gke operator deployment in Rancher local `Installed Apps` section
4. Try to create new EKS or GKE managed cluster.
5. Rancher will deploy already pinned version of EKS and GKE operator

Nothing to do, I am closing this issue.
3.
