### ISSUE TITLE
Remove deprecated Setting EKSUpstreamRefreshCron

### ISSUE THREAD

**Issue by KevinJoiner** [rancher/rancher#42047]
The setting [EKSUpstreamRefreshCron](https://github.com/rancher/rancher/blob/release/v2.7/pkg/settings/setting.go#L126) was marked as deprecated in `v2.6`  as a part of https://github.com/rancher/rancher/pull/35920
This setting can be removed in Rancher`v2.8.0`. A quick investigation shows that this setting is no longer referenced inside rancher/rancher repo.

**Comment by KevinJoiner** [comment]
@mbologna Created this issue, to make sure the depreciation and removal is being tracked somewhere.

**Comment by mjura** [comment]
merged
