### ISSUE TITLE
[BUG] handler user-controllers-controller: userControllersController: failed to set peers for key all: failed to start user controllers for cluster c-kf2gs: secrets "cattle-global-data/" not found, requeuing

### ISSUE THREAD

**Issue by roshan3133** [rancher/rancher#42055]
**Rancher Server Setup**
- Rancher version: 2.7.5
- Installation option (Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (EKS): EKS 1.25

**Information about the Cluster**
- Kubernetes version: 1.25
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Imported EKS1.25):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/)

**Describe the bug** Unable to import 2nd existing EKS 1.25 cluster into Rancher.
[ERROR] error syncing '_all_': handler user-controllers-controller: userControllersController: failed to set peers for key _all_: failed to start user controllers for cluster c-kf2gs: secrets "cattle-global-data/" not found, requeuing
```  Secrets are available
$ k get secret -n cattle-global-data
NAME       TYPE     DATA   AGE
c-kf2gs    Opaque   2      56m
cc-9bssd   Opaque   3      59m
```
**To Reproduce**

1. helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx --namespace ingress-nginx --set controller.service.type=LoadBalancer --version 4.7.1 --create-namespace
2. kubectl create namespace cattle-system
 3. helm upgrade --install rancher rancher-stable/rancher --namespace cattle-system --version=2.7.5 --set hostname=rancher.xxx.com --set ingress.tls.source=letsEncrypt  --set letsEncrypt.ingress.class=nginx --set ingress.ingressClassName=nginx
 
**Expected Result**
2nd EKS cluster should import without any issue

**Comment by alfredogotamagmail** [comment]
I'm having the same issue. Any progress on this?

**Comment by roshan3133** [comment]
The issue is with AWS IAM user permission, use same IAM user Access and secret in Rancher AWS cloud credentials which you used to install EKS, and the issue will resolved.

**Comment by YangKGcsdms** [comment]
I am operating on a local machine and have the same problem, but I don’t know how to solve it.

**Comment by zfan0310** [comment]
> The issue is with AWS IAM user permission, use same IAM user Access and secret in Rancher AWS cloud credentials which you used to install EKS, and the issue will resolved.

If you don't use the IAM user that installed EKS, then you need to update the aws-auth configmap in the kube-system namespace. Adding userarn, username and groups under mapUsers section.

Reference: https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-clusters-from-hosted-kubernetes-providers/eks#:~:text=Security%20and%20Compliance%E2%80%8B,instructions%2C%20please%20see%20this%20documentation.

**Comment by zfan0310** [comment]
> The issue is with AWS IAM user permission, use same IAM user Access and secret in Rancher AWS cloud credentials which you used to install EKS, and the issue will resolved.

Two solutions:
1. Use the IAM user that created the downstream cluster to access
2. Update the aws-auth configmap in the kube-system namespace of the downstream cluster. Adding userarn, username and groups under mapUsers section.

For example:
  mapUsers: |
    - "userarn": "{{ IAM_ARN }}"
      "username": "{{ USERNAME }}"
      "groups":
        - "system:masters"
        
- Reference: https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-clusters-from-hosted-kubernetes-providers/eks#:~:text=By%20default%20only,this%20documentation.
