### ISSUE TITLE
Duplicate column name 'dns_search_internal'

### ISSUE THREAD

**Issue by blandes** [rancher/rancher#4206]
Rancher Version: Upgrading from 0.63.1 to 1.0.0

Docker Version: 1.10.1

OS: Rancher OS v.043

Steps to Reproduce: Remove update DATABASECHANGELOGLOCK; then this error pops up

Results: rancher-server 1.0.0 fails to start, but the older version of rancher-server works

Basically, it looks like the migration went south. What command can I run that wouldn't completely destroy my external MYSQL db? This is the complete error.

SQL ALTER TABLE rancher.instance ADD dns_search_internal VARCHAR(255) NULL: Duplicate column name 'dns_search_internal'

Thanks!

**Comment by blandes** [comment]
Let older version of rancher-server run for a little bit then tried again.

**Comment by deniseschannon** [comment]
@blandes Did you mean to close this?

**Comment by blandes** [comment]
I did, I think it was an issue of me running the upgrade without executing the DATABASECHANGELOCK; first. Looks like rancher-server:v1.0.0 tried to do some migrations but locked down on config-defaults.
