### ISSUE TITLE
[BUG] Deleting etcd snapshots is not deleting the snapshots from the etcd node on an rke2 cluster

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#42065]
Information about the Cluster
**Rancher Server Setup**
- Rancher version: `v2.7.5`
- Installation option (Docker install/Helm Chart): `Docker`
- Proxy/Cert Details: `Self-signed`

**Information about the Cluster**
- Kubernetes version: `v1.25.11+rke2r1`
- Cluster Type (Local/Downstream): `Node driver  1worker, 1 etcd + cp, RKE2`

**Describe the bug**
Deleting snapshots from the local cluster, retains the snapshot on the etcd node. 

**To Reproduce**
1. Create a downstream rke2 node driver cluster with 2 nodes.
2. Take an etcd snapshot from the cluster management page.
3. Navigate to local cluster and delete the snapshots from the local cluster as follows:
```
k get etcdsnapshots -n fleet-default
k delete etcdsnapshots <snapshotname> -n fleet-default
```
4. Snapshots are deleted from the cluster management page as well as from the fleet-default namespace 
```
k get etcdsnapshot -n fleet-default
No resources found in fleet-default namespace.

etcdsnapshot.rke.cattle.io "anurke2-on-demand-anurke2-all-1cd2eccc-wv7np-1689095986-local" deleted
etcdsnapshot.rke.cattle.io "anurke2-on-demand-anurke2-all-1cd2eccc-wv7np-1689096016-local" deleted
etcdsnapshot.rke.cattle.io "anurke2-on-demand-anurke2-all-1cd2eccc-wv7np-1689096858-local" deleted
```
6. Log into the etcd node of the downstream cluster and verify the snapshots at the location:
```
ls /var/lib/rancher/rke2/server/db/snapshots/
```

**Result**
Snapshots are not deleted from the location.

**Expected Result**
Expected snapshots were deleted at the location.

**Comment by Oats87** [comment]
I'm not sure this is a valid use case. you cannot delete etcd snapshots through Rancher, you must delete them on the node itself...
