### ISSUE TITLE
[3rd Party Component Bump] Update Linode Node Driver to version 0.1.11+

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#42068]
Linode driver is currently on v0.1.8 while there is already v0.1.11. This issue is to track the bump.

**Comment by slickwarren** [comment]
did a round of provisioning tests via automation on rancher v2.7-head (58aede6) using linode driver version 0.1.11
* rke2 -- pass
* rke1 -- pass
* k3s -- pass
* (node creation / removal -- pass)

**Comment by slickwarren** [comment]
reopening this ticket for the following issue: 
rancher v2.7-head (https://github.com/rancher/rancher/commit/58aede67b99fd5002cc44c2b36583834595acad2) using linode driver version 0.1.11:
* deploying clusters with image ubuntu 22.04 do not get past `creating` node stage. 
* upon trying to remove the nodes / cluster stuck in this state, nodes in the backend are not removed.

**Comment by snasovich** [comment]
@zliang-akamai , @slickwarren confirmed that he's not running into any issues when provisioning clusters with ubuntu 22.04 on Rancher 2.7.5 with Linode driver 0.1.8. Could you please look into this?

**Comment by markusewalker** [comment]
Validated that this is working as expected on `v2.7-head` https://github.com/rancher/rancher/commit/39c4c345bcfba5eec8582012629c82917c8eb050. See details below:

**ENVIRONMENT DETAILS**
- Rancher install: Docker
- Rancher version: `v2.7-head` https://github.com/rancher/rancher/commit/39c4c345bcfba5eec8582012629c82917c8eb050
- Browser: Chrome

**TEST RESULT**
|Scenario|Test Case|Result|
|---|---|---|
|1|Provision an RKE1 Linode node driver v1.26.x cluster with Ubuntu 18.04|:white_check_mark:|
|2|Provision an RKE1 Linode node driver v1.26.x cluster with Ubuntu 20.04|:white_check_mark:|
|3|Provision an RKE1 Linode node driver v1.26.x cluster with Ubuntu 22.04|:white_check_mark:|
|4|Provision an K3S Linode node driver v1.26.x cluster with Ubuntu 18.04|:white_check_mark:|
|5|Provision an K3S Linode node driver v1.26.x cluster with Ubuntu 20.04|:white_check_mark:|
|6|Provision an K3S Linode node driver v1.26.x cluster with Ubuntu 22.04|:white_check_mark:|

**VALIDATION STEPS**

**Scenario 1**
1. Setup Rancher `v2.7-head` and logged in as a standard user.
2. Provisioned a downstream Linode node driver RKE1 `v1.26.6-rancher1-1` cluster with Ubuntu 18.04.
3. Validated that the cluster and nodes came up as `Active`.
4. Successfully deleted the cluster and nodes.

_____
**Scenario 2**
1. Repeated scenario 1, but used Ubuntu 20.04 instead; received the same successful results.

_______
**Scenario 3**
1. Repeated scenario 1, but used Ubuntu 22.04 instead; received the same successful results.

_______
**Scenario 4**
1. Repeated scenario 1, but provisioned a downstream Linode driver K3S `v1.26.6+k3s1` cluster with Ubuntu 18.04.

________
**Scenario 5**
1. Repeated scenario 1, but provisioned a downstream Linode driver K3S `v1.26.6+k3s1` cluster with Ubuntu 20.04.

_______
**Scenario 6**
1. Repeated scenario 1, but provisioned a downstream Linode driver K3S `v1.26.6+k3s1` cluster with Ubuntu 22.04.

**Comment by snasovich** [comment]
@zliang-akamai , based on https://github.com/rancher/rancher/issues/42068#issuecomment-1648661281 this seems to be working fine and we'll chalk up reported failure as one-off glitch unlikely to have anything to do with driver version bump.

However, we'll continue watching for it happening until the release and depending on how it goes may elect to rollback driver version bump.
