### ISSUE TITLE
[BUG] When a new etcdsnapshot is taken, any previously deleted snapshots will re appear on the etcdsnapshots page

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#42066]
Information about the Cluster
**Rancher Server Setup**
- Rancher version: `v2.7.5`
- Installation option (Docker install/Helm Chart): `Docker`
- Proxy/Cert Details: `Self-signed`

**Information about the Cluster**
- Kubernetes version: `v1.25.11+rke2r1`
- Cluster Type (Local/Downstream): `Node driver  1worker, 1 etcd + cp, RKE2`

**Describe the bug**
Re taking snapshots after deleting, cause the deleted snapshots to re appear in the etcd snapshot page.

**To Reproduce**
1. Create a downstream rke2 node driver cluster with 2 nodes.
2. Take an etcd snapshot from the cluster management page.
3. Navigate to local cluster and delete the snapshots from the local cluster as follows:
```
k get etcdsnapshots -n fleet-default
k delete etcdsnapshots <snapshotname> -n fleet-default
```
4. Re take the snapshot from the cluster management >> cluster >> etcd snapshot page

**Result**
Previously deleted snapshots re appear on the etcdsnapshots page.

**Expected Result**
Previously deleted snapshots do not appear on the etcd snapshot paege.

Additional Info:
Could be related to https://github.com/rancher/rancher/issues/42065

**Comment by Oats87** [comment]
I'm not sure this is a valid use case. you cannot delete etcd snapshots through Rancher, you must delete them on the node itself...
