### ISSUE TITLE
Editing/Cancel environment from details page takes me back to list page

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4207]
Version - v1.0.0

Steps to Reproduce: 
1.  Go to Manage Environments
2.  Add an Environment
3.  Click on environment to get to details page
4.  Click on Edit from menu
5.  Click on Save or Cancel

Results: Takes me back to list view

Expected: Take me back to details page

**Comment by westlywright** [comment]
@tfiduccia can we close this? Its not a valid scenario anymore. Env details is no more.

**Comment by tfiduccia** [comment]
Version - console 7/5
No details page for environment anymore
