### ISSUE TITLE
[BUG] Continuous Delivery - Request entity too large

### ISSUE THREAD

**Issue by naisanzaa** [rancher/rancher#42085]
**Rancher Server Setup**

Component | Version
-- | --
Rancher | v2.7.5
Dashboard | v2.7.5
Helm | v2.16.8-rancher2
Machine | v0.15.0-rancher100

Component	Version
[Rancher](https://github.com/rancher/rancher)	v2.7.5
[Dashboard](https://github.com/rancher/dashboard)	v2.7.5
[Helm](https://github.com/rancher/helm)	v2.16.8-rancher2
[Machine](https://github.com/rancher/machine)	v0.15.0-rancher100

**Information about the Cluster**
`docker` `rancher/rancher:latest`

**User Information**
`admin`

**Describe the bug**
Unable to add a public github repository to Continuous Delivery.

Error: 
```
Time="2023-07-14T01:45:17Z" level=fatal msg="Request entity too large: limit is 3145728"

```

**To Reproduce**
1. go to Continuous Delivery
2. add github https link
3. error

**Result**
```
Time="2023-07-14T01:45:17Z" level=fatal msg="Request entity too large: limit is 3145728"
```

**Expected Result**
add github repo 

**Screenshots**

**Additional context**
related: https://github.com/rancher/fleet/issues/205
related: https://github.com/rancher/fleet/issues/1650

**Comment by kkaempf** [comment]
Duplicate. Tracking in rancher/fleet#1650
