### ISSUE TITLE
Document limitations on UI-Extensions on air-gapped environments

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#42093]
There is missing Rancher UI "Extension" documentation in the Air-Gapped part: https://ranchermanager.docs.rancher.com/integrations-in-rancher/rancher-extensions. It should describe how and what software has to be provided by the customer's private registry for Air-Gapped.

This includes both the extensions and kubewarden

**Comment by jiaqiluo** [comment]
closing this issue as a duplication of https://github.com/rancher/rancher-docs/issues/773 
Please check progress and updates on the above issue
