### ISSUE TITLE
RKE2 cluster stuck in Updating, with an error message "Init node not found".

### ISSUE THREAD

**Issue by AncyPaul** [rancher/rancher#42096]
**Rancher Server Setup**
- Rancher version: 2.7.5
- Installation option: Helm Chart, RKE2

**Information about the Cluster**
- Kubernetes version: 1.24.7
- Cluster Type - Downstream
   - If downstream, what type of cluster - Custom

**Describe the bug**
I have tried to upgrade the rancher with helm, but my RKE2 cluster is stuck in Updating, with an error message "Init node not found".  As a result, I cannot do anything with the cluster  (like adding more master nodes). How to resolve this?.

![rancher-ui](https://github.com/rancher/rancher/assets/27879229/dd0c2a97-4a47-4fd0-afd3-80b0a92fdf50)
![local](https://github.com/rancher/rancher/assets/27879229/baab2c55-2053-4e80-96ea-7477e7705bb8)

**Additional Information**
Fleet controller log:
```
Sat, Jul 15 2023 12:56:49 amtime="2023-07-14T19:26:49Z" level=error msg="error syncing 'fleet-default/import-token-uat': handler cluster-group-token: failed to delete cattle-fleet-clusters-system/import-token-uat-xxxx-xxxx-xxx-creds rbac.authorization.k8s.io/v1, Kind=RoleBinding for cluster-group-token fleet-default/import-token-uat: rolebindings.rbac.authorization.k8s.io \"import-token-uat-xxxxx-xxxx-xxxx-creds\" not found, requeuing"

Sat, Jul 15 2023 12:56:49 amtime="2023-07-14T19:26:49Z" level=error msg="error syncing 'fleet-local/import-token-local': handler cluster-group-token: failed to delete cattle-fleet-clusters-system/import-token-local-xxxxx-xxxxx-xxxx-creds rbac.authorization.k8s.io/v1, Kind=RoleBinding for cluster-group-token fleet-local/import-token-local: rolebindings.rbac.authorization.k8s.io \"import-token-local-xxxxx-xxx-xxxx-xxxx-creds\" not found, requeuing"
```

**Comment by sarath-sankar** [comment]
> **Rancher Server Setup**
> 
> * Rancher version: 2.7.5
> * Installation option: Helm Chart, RKE2
> 
> **Information about the Cluster**
> 
> * Kubernetes version: 1.24.7
> * Cluster Type - Downstream
>   
>   * If downstream, what type of cluster - Custom
> 
> **Describe the bug** I have tried to upgrade the rancher with helm, but my RKE2 cluster is stuck in Updating, with an error message "Init node not found". As a result, I cannot do anything with the cluster (like adding more master nodes). How to resolve this?.
> 
> ![rancher-ui](https://user-images.githubusercontent.com/27879229/253726916-dd0c2a97-4a47-4fd0-afd3-80b0a92fdf50.jpg) ![local](https://user-images.githubusercontent.com/27879229/253727559-baab2c55-2053-4e80-96ea-7477e7705bb8.jpg)
> 
> **Additional Information** Fleet controller log:
> 
> ```
> Sat, Jul 15 2023 12:56:49 amtime="2023-07-14T19:26:49Z" level=error msg="error syncing 'fleet-default/import-token-uat': handler cluster-group-token: failed to delete cattle-fleet-clusters-system/import-token-uat-xxxx-xxxx-xxx-creds rbac.authorization.k8s.io/v1, Kind=RoleBinding for cluster-group-token fleet-default/import-token-uat: rolebindings.rbac.authorization.k8s.io \"import-token-uat-xxxxx-xxxx-xxxx-creds\" not found, requeuing"
> 
> Sat, Jul 15 2023 12:56:49 amtime="2023-07-14T19:26:49Z" level=error msg="error syncing 'fleet-local/import-token-local': handler cluster-group-token: failed to delete cattle-fleet-clusters-system/import-token-local-xxxxx-xxxxx-xxxx-creds rbac.authorization.k8s.io/v1, Kind=RoleBinding for cluster-group-token fleet-local/import-token-local: rolebindings.rbac.authorization.k8s.io \"import-token-local-xxxxx-xxx-xxxx-xxxx-creds\" not found, requeuing"
> ```

I'm facing the same issue.
It would be great if someone had a solution for this issue 
@erkki @steved @phillc @flavio @AncyPaul

**Comment by sarath-sankar** [comment]
[planner] rkecluster fleet-default/uat: error encountered while searching for init node during etcd snapshot creation: init node not found
I have got this error from 1/3 of the rancher pod replica

**Comment by AncyPaul** [comment]
Able to resolve the issue - 
Referred https://github.com/rancher/rancher/issues/37462#ref-pullrequest-1381844197
