### ISSUE TITLE
If I don't have at least one owner, save does nothing (should show error)

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4209]
Version - v1.0.0

Steps to Reproduce: 
1.  Authenticate with Github
2.  Go to manage environment
3.  Edit an environment
4.  Change all roles to Members (so there is no Owner)
5.  Click on Save

Results: Nothing happens

Expected: An error should come up saying that "You must have at least one Owner"

**Comment by vincent99** [comment]
![image](https://cloud.githubusercontent.com/assets/753917/16128381/5eb56d62-33b5-11e6-97be-b032e446a232.png)

**Comment by tfiduccia** [comment]
Version - master 6/16
Verified fixed
