### ISSUE TITLE
[BUG] Upgrading the Ubuntu to 22.04 resulted in networking failure

### ISSUE THREAD

**Issue by manuelbuil** [rancher/rancher#42103]
**Rancher Server Setup**
- Rancher version:
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version:
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:

**Describe the bug**

When upgrading from a OS that uses iptables-legacy to an OS that uses iptables-nft, the kubernetes containers are not capable of detecting that change. As a consequence, k8s compoents keep using the old iptables-legacy whereas the OS is expecting everything to run in iptables-nft. That creates a broken networking state.

**To Reproduce**

1 - Deploy rke in Ubuntu 20.04
2 - Upgrade Ubuntu 20.04 to Ubuntu 22.04
3 - Check `iptables --version` in both the hostOS and the kubelet container:
```
azureuser@mbuil-vm1:~$ sudo iptables --version
iptables v1.8.7 (nf_tables)
azureuser@mbuil-vm1:~$ docker exec 4a962af559a7 iptables --version
iptables v1.8.7 (legacy)
```

**Result**
Cluster connectivity is broken

**Expected Result**

Cluster connectivity works

**Screenshots**

**Additional context**

**Comment by impsik** [comment]
I'm facing the same problem. Any info how to fix it?
```
docker exec kubelet iptables -V
iptables v1.8.4 (legacy)

```
I tried `update-alternatives --set iptables /usr/sbin/iptables-legacy` + restarted nodes but that didn't help.

**Comment by impsik** [comment]
> > I'm facing the same problem. Any info how to fix it?
> > ```
> > docker exec kubelet iptables -V
> > iptables v1.8.4 (legacy)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I tried `update-alternatives --set iptables /usr/sbin/iptables-legacy` + restarted nodes but that didn't help.
> 
> This is the best workaround while the fix gets merged: https://gist.github.com/superseb/03076b92114ddb7881a91f89914f551b
Unfortunately, it didn't help. I checked all nodes:

```
docker exec kubelet ls -la /etc/alternatives/iptables
lrwxrwxrwx 1 root root 22 Aug 2 13:39 /etc/alternatives/iptables -> /usr/sbin/iptables-nft

docker exec kubelet iptables --version
iptables v1.8.4 (nf_tables)

node1:/home/user# iptables -V
iptables v1.8.7 (nf_tables)
```
`docker ps | grep cattle-node-agent` - no output

**Comment by manuelbuil** [comment]
> > > I'm facing the same problem. Any info how to fix it?
> > > ```
> > > docker exec kubelet iptables -V
> > > iptables v1.8.4 (legacy)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > I tried `update-alternatives --set iptables /usr/sbin/iptables-legacy` + restarted nodes but that didn't help.
> > 
> > 
> > This is the best workaround while the fix gets merged: https://gist.github.com/superseb/03076b92114ddb7881a91f89914f551b
> > Unfortunately, it didn't help. I checked all nodes:
> 
> ```
> docker exec kubelet ls -la /etc/alternatives/iptables
> lrwxrwxrwx 1 root root 22 Aug 2 13:39 /etc/alternatives/iptables -> /usr/sbin/iptables-nft
> 
> docker exec kubelet iptables --version
> iptables v1.8.4 (nf_tables)
> 
> node1:/home/user# iptables -V
> iptables v1.8.7 (nf_tables)
> ```
> 
> `docker ps | grep cattle-node-agent` - no output

So it worked because I see your kubelet using nf_tables, right? The problem you are seeing is that `cattle-node-agent` is not coming up? What if you try `docker ps --all| grep  cattle-node-agent`?

**Comment by manuelbuil** [comment]
> > What if you try `docker ps --all| grep cattle-node-agent`?
> 
> No output. It worked just fine yesterday.

How did you deploy rke?

**Comment by impsik** [comment]
> How did you deploy rke?

With: rke up
Similar to this one: [LINK](https://rke.docs.rancher.com/installation)

**Comment by manuelbuil** [comment]
> > How did you deploy rke?
> 
> With: rke up Similar to this one: [LINK](https://rke.docs.rancher.com/installation)

In that case, `cattle-node-agent` will not be present, your env is correct. That container is present when deploying using rancher

**Comment by impsik** [comment]
> In that case, `cattle-node-agent` will not be present, your env is correct.

But what could be wrong that the cluster essentially does not work?
For example:
```
# time kubectl get pods -n cattle-system
NAME READY STATUS RESTARTS AGE
rancher-656f9f55b9-9vqf7 1/1 Running 184 19h
rancher-webhook-6958cfcddf-ltp6m 1/1 Running 5 19h

in line 1m36.088s
user 0m0.145s
sys 0m0.038s
```
I only did: `do-release-upgrade`

**Comment by manuelbuil** [comment]
> > In that case, `cattle-node-agent` will not be present, your env is correct.
> 
> But what could be wrong that the cluster essentially does not work? For example:
> 
> ```
> # time kubectl get pods -n cattle-system
> NAME READY STATUS RESTARTS AGE
> rancher-656f9f55b9-9vqf7 1/1 Running 184 19h
> rancher-webhook-6958cfcddf-ltp6m 1/1 Running 5 19h
> 
> in line 1m36.088s
> user 0m0.145s
> sys 0m0.038s
> ```
> 
> I only did: `do-release-upgrade`

Are they continuously restarting? What do the logs say?

**Comment by manuelbuil** [comment]
> > What do the logs say?
> 
> 2023/08/02 15:14:23 [ERROR] error syncing 'namespace/application': handler ingressEndpointsController: Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": Post "https://address-here-ingress-nginx-controller-admission.epd-stage.svc:443/networking/v1/ingresses?timeout=10s": context deadline exceeded, requeuing 2023/08/02 15:14:24 [INFO] Updating ingress [namespace:application] with public endpoints [[{"addresses":["10.43.143.195"],"port":80,"protocol":"HTTP","serviceName":"namespace:name","ingressName":"namespace:application","hostname":"hostname-here","path":"/notify","allNodes":false}]] 2023/08/02 15:14:24 [ERROR] Failed to read API for groups map[custom.metrics.k8s.io/v1beta1:the server is currently unable to handle the request metrics.k8s.io/v1beta1:the server is currently unable to handle the request]
> 
> [ERROR] Failed to read API for groups map[custom.metrics.k8s.io/v1beta1:the server is currently unable to handle the request metrics.k8s.io/v1beta1:the server is currently unable to handle the request]
> 
> Those are most common if i look at rancher log.

Could you open another issue? This one is about iptables not changing the mode correctly

**Comment by impsik** [comment]
> Could you open another issue?

Sure

**Comment by kirecek** [comment]
not sure if this will help anybody, but we hit the same issue because of calico:

https://github.com/projectcalico/calico/blob/c31beef97dd7de0dff730a6f1005afae534a1a9e/felix/environment/feature_detect_linux.go#L365-L369

After upgrade, calico kept using the wrong backend because simple legacy tables contained more rules. It was enough to satisfy on of the conditions in the code I linked. Create mangle KUBE-IPTABLES-HINT chain or just transfer the rules.

**Comment by vivek-shilimkar** [comment]
Tested the above issue, iptables version is getting updated as expectation.

Test stepsps.
1. Created a RKE cluster on ubuntu 20.04.
2. Checked the iptables version on host and kubelet container.
3. Upgraded the host OS ubuntu to 22.04.
4. After successful upgrade checked the iptables version of kubelet container.

kubelet also have a updated version of iptables.

Since the kubelet is getting expected version of iptables, closing this issue.
