### ISSUE TITLE
Authenticating creates a "something else" even if using site address for host registration

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4211]
Version 1.0 

Steps to Reproduce: 
1.  Create a new setup
2.  Authenticate through Github before adding host
3.  Go to Settings

Results: Creates a Something Else, even if registration is same as site's address
![image](https://cloud.githubusercontent.com/assets/11514927/14121218/666da56c-f5ab-11e5-88d7-9a418824b8e2.png)

Expected: Should just use the "This site's address" radio button

**Comment by vincent99** [comment]
This was because when turning GitHub on the setting was set to `104.197.186.145:8080`, which does not match `http://104.197.186.145:8080`

**Comment by tfiduccia** [comment]
version - v1.0.1-rc1
Verified fixed
