### ISSUE TITLE
RKE2 and K3S - KDM Update for K8s July patch release for Rancher 2.6

### ISSUE THREAD

**Issue by rancher-max** [rancher/rancher#42116]
# KDM Updates

| New Kubernetes Version  | Min Rancher Version | Max Rancher Version |
|                  :---:                  |              :---:               |               :---:               |
| v1.24.16+rke2r1                  | v2.6.7-alpha1             | v2.6.99 |
| v1.24.16+k3s1                    | v2.6.7-alpha1             | v2.6.99 |

# KDM Branch
dev-v2.6

# Chart Changelog

| Chart Name  | New Version | Affected Kubernetes Version(s) |
|        :---:        |       :---:        |                     :---:                     |
TBD

# Argument Changelog

| Argument Name  | Affected Kubernetes Version(s) |
|        :---:           |                     :---:                     |

TBD

# Additional Notes

N/A

**Comment by est-suse** [comment]
![Untitled](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/b4b314b1-c8ba-4776-8d54-5b85f105cf2a/Untitled.png)

**Comment by est-suse** [comment]
![image](https://github.com/rancher/rancher/assets/106194120/6b758547-58ad-45db-a7eb-822709269ab0)

**Comment by rancher-max** [comment]
These have been validated including post-release
