### ISSUE TITLE
[BUG] CAPR machine-provisioned etcd nodes are never drained before deletion

### ISSUE THREAD

**Issue by Oats87** [rancher/rancher#42119]
**Rancher Server Setup**
- Rancher version: v2.7.5
- Installation option (Docker install/Helm Chart): N/A
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): N/A
- Proxy/Cert Details: N/A

**Information about the Cluster**
- Kubernetes version: N/A
- Cluster Type (Local/Downstream): Downstream CAPR
**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:

**Describe the bug**
CAPR machine provisioned etcd nodes are never drained on deletion. Apparently this was added as a "workaround" in the past but this was not the correct thing to do. 

See: https://github.com/rancher/rancher/blob/8e8c62c86d53690a77260884e6fe1afcdafaafc4/pkg/controllers/provisioningv2/provisioningcluster/template.go#L356 and the corresponding PR here: https://github.com/rancher/rancher/pull/36411 
**To Reproduce**
Create a CAPR-powered cluster with provisioned machines
Delete an etcd node

**Result**
Observe the etcd node is not actually drained even if you specify "drain on delete"

**Expected Result**
If you specify drain on delete, the node should be drained before deletion.

**Screenshots**

**Additional context**

**Comment by Oats87** [comment]
This was merged in as part of PR: https://github.com/rancher/rancher/pull/42228/files#diff-2b509028a39574459f6e6e8dc738e9a1dc9be1c1d20deba00a7abd1f66c927adL356-L357 and as such, will be within the Q3 release.

**Comment by markusewalker** [comment]
**QA TEST PLAN**

**Scenarios**
|Scenario|Test Case|
|---|---|
|1|Using QA's testing framework, provision downstream custom RKE1/RKE2/K3S clusters as a standard user (1 etcd, 1 cp, 1 worker)|
|2|Using QA's testing framework, provision downstream custom RKE1/RKE2/K3S clusters as a standard user (1 etcd+1 cp, 2 workers)|
|3|Using QA's testing framework, upgrade downstream node driver RKE1/RKE2/K3S clusters as a standard user (1 etcd, 1 cp, 1 worker)|
|4|Using QA's testing framework, upgrade downstream node driver RKE1/RKE2/K3S clusters as a standard user (1 etcd+1 cp, 2 workers)|
|5|Using QA's testing framework, run through etcd backup and restore test suite as a standard user|
|6|Setup Rancher v2.6.13, provision downstream node driver RKE1/RKE2/K3S clusters as a standard user, upgrade Rancher to v2.7-head|
|7|As a standard user, provision a downstream RKE2 node driver cluster cluster (2 etcd, 1 cp, 2 workers) w/drain on delete specified, delete an etcd node and validate it's drained before deleted|
|8|As a standard user, provision a downstream RKE2 node driver cluster cluster (2 etcd+ cp, 3 workers) w/drain on delete specified, delete an etcd node and validate it's drained before deleted|

**Comment by slickwarren** [comment]
@markusewalker can you add some cases like drain etcd on delete -> wait for new etcd to come up -> drain again ... until all nodes have cycled 2x? and some other similar use cases given the latest etcd snapshot issues

also can you add some around testing etcd behavior after drain on delete since this probably hasn't been tested through rancher in the last 5 years, at least.

**Comment by markusewalker** [comment]
Validated this against `v2.7-head` https://github.com/rancher/rancher/commit/10d02ae6827fd549ae0f373be84a5e327999925b. See details below:

**ENVIRONMENT DETAILS**
- Rancher install: Docker
- Rancher version: `v2.7-head` https://github.com/rancher/rancher/commit/10d02ae6827fd549ae0f373be84a5e327999925b

**TEST RESULT**
|Scenario|Test Case|Result
|---|---|---|
|1|Using QA's testing framework, provision downstream custom RKE1/RKE2/K3S clusters as a standard user (1 etcd, 1 cp, 1 worker)|:white_check_mark:|
|2|Using QA's testing framework, provision downstream custom RKE1/RKE2/K3S clusters as a standard user (1 etcd+1 cp, 2 workers)|:white_check_mark:|
|3|Using QA's testing framework, upgrade downstream node driver RKE1/RKE2/K3S clusters as a standard user (1 etcd, 1 cp, 1 worker)|:white_check_mark:|
|4|Using QA's testing framework, upgrade downstream node driver RKE1/RKE2/K3S clusters as a standard user (1 etcd+1 cp, 2 workers)|:white_check_mark:|
|5|Using QA's testing framework, run through etcd backup and restore test suite as a standard user|:white_check_mark:|
|6|Setup Rancher v2.6.13, provision downstream node driver RKE1/RKE2/K3S clusters as a standard user, upgrade Rancher to v2.7-head|:white_check_mark:|
|7|As a standard user, provision a downstream RKE2 node driver cluster cluster (2 etcd, 1 cp, 2 workers) w/drain on delete specified, delete an etcd node and validate it's drained before deleted|:white_check_mark:|
|8|As a standard user, provision a downstream RKE2 node driver cluster cluster (2 etcd+ cp, 3 workers) w/drain on delete specified, delete an etcd node and validate it's drained before deleted|:white_check_mark:|

**VALIDATION STEPS**

**Scenario 1**
1. Successfully ran the following test cases using QA's automated test framework:
     - Provision RKE1 `v1.26.7-rancher1-1` custom cluster (1 etcd, 1 cp, 1 worker) as a standard user
     - Provision RKE2 `v1.26.7+rke2r1` custom cluster (1 etcd, 1 cp, 1 worker) as a standard user
     - Provision K3S `v1.26.7+k3s1` custom cluster (1 etcd, 1 cp, 1 worker) as a standard user

_______

**Scenario 2**
1. Successfully ran the following test cases using QA's automated test framework:
     - Provision RKE1 `v1.26.7-rancher1-1` custom cluster (1 etcd+1 cp, 2 workers) as a standard user
     - Provision RKE2 `v1.26.7+rke2r1` custom cluster (1 etcd+1 cp, 2 workers) as a standard user
     - Provision K3S `v1.26.7+k3s1` custom cluster (1 etcd+1 cp, 2 workers) as a standard user

_______

**Scenario 3**
1. Successfully ran the following test cases using QA's automated test framework:
     - Upgrade RKE1 `v1.25.12-rancher1-1` -> `v1.26.7-rancher1-1` downstream node driver cluster (1 etcd, 1 cp, 1 worker) as a standard user
     - Upgrade RKE2 `v1.25.12+rke2r1` -> `v1.26.7+rke2r1` downstream node driver cluster (1 etcd, 1 cp, 1 worker) as a standard user
     - Upgrade K3S `v1.25.12+k3s1` -> `v1.26.7+k3s1` downstream node driver cluster (1 etcd, 1 cp, 1 worker) as a standard user

________

**Scenario 4**
1. Successfully ran the following test cases using QA's automated test framework:
     - Upgrade RKE1 `v1.25.12-rancher1-1` -> `v1.26.7-rancher1-1` downstream node driver cluster (1 etcd+1 cp, 2 workers) as a standard user
     - Upgrade RKE2 `v1.25.12+rke2r1` -> `v1.26.7+rke2r1` downstream node driver cluster (1 etcd+1 cp, 2 workers) as a standard user
     - Upgrade K3S `v1.25.12+k3s1` -> `v1.26.7+k3s1` downstream node driver cluster (1 etcd+1 cp, 2 workers) as a standard user

_______

**Scenario 5**
1. Successfully ran the following test cases using QA's automated test framework:
     - Provision RKE2 `v1.25.12+rke2r1`, took a local etcd snapshot, upgrade to `v1.26.7+rke2r1`, restore to `v1.25.12+rke2r1` using all restore options
     - Provision RKE2 `v1.25.12+rke2r1`, took an S3 etcd snapshot, upgrade to `v1.26.7+rke2r1`, restore to `v1.25.12+rke2r1` using all restore options

_________

**Scenario 6**
1. Setup Rancher `v2.6.13` and logged in as a standard user.
2. Provisioned the following downstream node driver clusters:
     - `v1.24.16-rancher1-1`
     - `v1.24.16+rke2r1`
     - `v1.24.16+k3s1`
3. Upgraded Rancher `v2.6.13` -> `v2.7-head`; validated that no cluster auto-upgraded their K8s version.
4. Upgraded each cluster to the highest K8s versions successfully; validated that each cluster and nodes were in a state of `Active`.

__________

**Scenario 7**
1. As a standard user, provisioned a downstream RKE2 `v1.26.7+rke2r1` node driver cluster (2 etcd, 1 cp, 2 workers).
     - Ensured that drain on delete is specified.
2. Deleted an etcd node; ensured that it is drained before it was deleted and a replacement came up in the cluster `Active`.
3. Repeated step 2 two more times, each with the same results.

__________

**Scenario 8**
1. As a standard user, provisioned a downstream RKE2 `v1.26.7+rke2r1` node driver cluster (2 etcd+ cp, 3 workers).
     - Ensured that drain on delete is specified.
2. Deleted an etcd node; ensured that it is drained before it was deleted and a replacement came up in the cluster `Active`.
3. Repeated step 2 two more times, each with the same results.
