### ISSUE TITLE
[BUG] Test 4.2.12 in CIS scan fails on RKE cluster

### ISSUE THREAD

**Issue by Priyashetty17** [rancher/rancher#42125]
**Rancher Server Setup**
- Rancher version: 	v2.7-58aede67b99fd5002cc44c2b36583834595acad2-head
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1

**Information about the Cluster**
- Kubernetes version:  1.25.11, 1.26.6
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Node driver provisioned, Custom

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Admin

**Describe the bug**
Test 4.2.12 in CIS scan fails on RKE cluster

**To Reproduce**
1. Create a downstream non-hardened RKE cluster
2. Install the "rancher-cis-benchmark" on the downstream cluster (Chart version "4.2.0-rc2" and security tag "v0.2.13-rc3") 
3. Run CIS scan with profile "rke-profile-permissive-1.7"

**Result**
Test 4.2.12 in CIS scan fails

**Expected Result**
All tests pass

**Screenshots**
![cis_rke](https://github.com/rancher/rancher/assets/42880103/373e0b73-6045-4178-978a-83de5a6d2486)

**Additional context**
ID **4.2.12** is set to 2 checks in the [node yaml](https://github.com/rancher/security-scan/blob/9dedd2ddc874c6fb3a6c9a74630700cda6efae8b/package/cfg/rke-cis-1.7-permissive/node.yaml#L408C6-L457C1)
` - id: 4.2.12
        text: "Verify that the RotateKubeletServerCertificate argument is set to true (Manual)"
`

` - id: 4.2.12
        text: "Ensure that the Kubelet only makes use of Strong Cryptographic Ciphers (Automated)"
`

Note: This issue is seen on both permissive and hardened profiles for RKE cluster.

CC @andypitcher @JonCrowther

**Comment by andypitcher** [comment]
This issue can be closed now, https://github.com/rancher/security-scan/pull/144 was merged.
