### ISSUE TITLE
[BUG] Test 4.2.6 in CIS scan fails on K3S cluster 

### ISSUE THREAD

**Issue by Priyashetty17** [rancher/rancher#42138]
**Rancher Server Setup**
- Rancher version: 	v2.7-58aede67b99fd5002cc44c2b36583834595acad2-head
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE

**Information about the Cluster**
- Kubernetes version:  1.25.11, 1.26.6
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Node driver provisioned K3S (non-hardened, 3 nodes-all roles)

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Admin

**Describe the bug**
Test 4.2.6 in CIS scan fails on non-hardened K3S cluster

**To Reproduce**
1. Create a downstream non-hardened K3S cluster
2. Install the "rancher-cis-benchmark" on the downstream cluster (Chart version "4.2.0-rc2" and security tag "v0.2.13-rc3") 
3. Run CIS scan with profile "k3s-cis-1.7-profile-permissive"

**Result**
Test 4.2.6 in CIS scan fails

Here's the snippet from the json report:
![image](https://github.com/rancher/rancher/assets/42880103/c775a09d-89ae-4bce-b3df-6a9ac086ae10)

Note: Looks like this check is set to skip in k3s-cis-1.23-permissive and k3s-cis-1.24-permissive profiles but it is not set to skip in k3s-cis-1.7-profile-permissive profile.
![image](https://github.com/rancher/rancher/assets/42880103/653d1eb2-7ca7-4f37-b9ae-37824349ff14)

**Expected Result**
All tests pass

**Screenshots**
![image](https://github.com/rancher/rancher/assets/42880103/519034e8-1079-4bb6-834b-64bbe84b7833)

CC @andypitcher @JonCrowther

**Comment by andypitcher** [comment]
@Priyashetty17 we just merged a fix to match the previous permissive profiles' (1.5 through 1.24) skips (permissive). `4.2.6` is now `type: skip` for `k3s-cis-1.7-permissive`.

**Comment by Priyashetty17** [comment]
Thanks, Andy! Will there be a new image 'rc4' with this fix included?  Also, I see that you have moved this issue to the "Done". Typically, the general process for the issues filed by QA here is to move the issue to "To Test" once the fix is merged. And, after QA validates the fix, it gets moved to "Done".
