### ISSUE TITLE
[BUG] Rancher windows node occasionally needs restart to properly upgrade

### ISSUE THREAD

**Issue by HarrisonWAffel** [rancher/rancher#42137]
**Rancher Server Setup**
- Rancher version: N/A
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2 on windows, latest versions
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: N?A
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): N/A

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: N/A

**Describe the bug**
Occasionally, a windows worker will fail to properly upgrade to a new Kubernetes version. The RKE2 logs will be filled with `{Calico exited: context canceled}`. This prevents the node from becoming available after an upgrade. Restarting the node fixes this issue, and the root cause seems to be multiple processes related to RKE2 running at once, resulting in undesired behavior. 

**To Reproduce**
+ Provision an RKE2 cluster with 1 linux all roles node, and 1 windows worker node
   + Pick a K8s version one less than the latest 
+ Upgrade the cluster to a newer Kubernetes version

**Result**
Occasionally, the windows worker node will be stuck in `Waiting for Kubelet`, and will stay that way until rebooted. The RKE2 logs will show `{Calico exited: context canceled}` continuously. 

**Expected Result**

Upgrade consistently occur without issue, RKE2 does not log any Calico errors.

**Work Around**

Restarting the node will resolve the issue and the node will be successfully upgraded. 

**Additional context**

Related to: https://github.com/rancher/rancher/issues/41868, though this issue has a clear workaround

**Comment by snasovich** [comment]
Setting milestone to 2023-Q3-v2.7x for visibility, though the fix will be in RKE2/k3s release - hopefully July patches but we're not sure yet when they will be introduced.

**Comment by markusewalker** [comment]
**QA TEST PLAN**

**Scenarios**
|Scenario|Test Case|
|---|---|
|1|As a standard user, provision a downstream RKE2 custom cluster (1 etcd, 1 cp, 2 Linux workers + 1 Windows worker), upgrade the K8s version and validate the cluster and nodes upgrade|
|2|As a standard user, provision a downstream RKE2 custom cluster (1 etcd+cp, 2 Linux workers + 1 Windows worker), upgrade the K8s version and validate the cluster and nodes upgrade|
|3|As a standard user, provision a downstream RKE2 custom cluster (1 etcd, 1 cp, 2 Linux workers + 1 Windows worker), upgrade the K8s version, validate the cluster and nodes upgrade, add a new Windows worker node|
|4|Setup Rancher v2.7.5, as a standard user, provision a downstream RKE2 custom cluster (1 etcd, 1 cp, 2 Linux workers + 1 Windows worker), upgrade Rancher to v2.7-head, upgrade the K8s version, validate the cluster and nodes upgrade, add a new Windows worker node

**Comment by markusewalker** [comment]
Validated that this is addressed in `v2.7-head` https://github.com/rancher/rancher/commit/d8a2bcae227717e16caa8519a3709f3e013673f2. See details below:

**ENVIRONMENT DETAILS**
- Rancher install: Docker
- Rancher version: `v2.7-head` https://github.com/rancher/rancher/commit/d8a2bcae227717e16caa8519a3709f3e013673f2
- Browser: Chrome

**TEST RESULT**
|Scenario|Test Case|Result
|---|---|---|
|1|As a standard user, provision a downstream RKE2 custom cluster (1 etcd, 1 cp, 2 Linux workers + 1 Windows worker), upgrade the K8s version and validate the cluster and nodes upgrade, add a new Windows worker node|:white_check_mark:|
|2|As a standard user, provision a downstream RKE2 custom cluster (1 etcd+cp, 2 Linux workers + 1 Windows worker), upgrade the K8s version and validate the cluster and nodes upgrade, add a new Windows worker node|:white_check_mark:|
|3|Setup Rancher v2.7.5, as a standard user, provision a downstream RKE2 custom cluster (1 etcd, 1 cp, 2 Linux workers + 1 Windows worker), upgrade Rancher to v2.7-head, upgrade the K8s version, validate the cluster and nodes upgrade, add a new Windows worker node|:white_check_mark:|

**VALIDATION STEPS**

**Scenario 1**
1. As a standard user, provisioned a downstream RKE2 `v1.25.11+rke2r1` custom cluster (1 etcd, 1 cp, 2 Linux workers, 1 Windows worker).
2. Took an etcd snapshot of the cluster.
3. Upgraded the K8s version to `v1.26.6+rke2r1`.
4. Restored the snapshot with options cluster config, etcd and Kubernetes version; validated cluster and nodes are back to `v1.25.11+rke2r1`.
5. Successfully upgraded once more to `v1.26.6+rke2r1`.
6. Registered an additional Windows worker node and validated it came up as `Active` in the cluster.
7. Removed a Windows worker node from the cluster and this was successful.
8. Successfully deleted the cluster.

______

**Scenario 2**
1. Repeated scenario 1, but provisioned a downstream RKE2 `v1.25.11+rke2r1` with 1 etcd+1cp, 2 Linux workers and 1 Windows worker initially.
2. Yielded same successful results as seen in scenario 1.

______

**Scenario 3**
1. Setup Rancher `v2.7.5` and logged in as a standard user.
2. Provisioned a downstream RKE2 `v1.25.11+rke2r1` custom cluster (1 etcd, 1 cp, 2 Linux workers, 1 Windows worker).
     - Validated that the cluster and nodes are `Active` in Cluster Management and Cluster Explorer.
3. Upgraded Rancher from `v2.7.5` to `v2.7-head`; validated that the cluster and nodes did not auto-upgrade K8s versions.
4. Upgraded the K8s version to `v1.26.6+rke2r1`.
5. Registered an additional Windows worker node and validated it came up as `Active` in the cluster.
6. Removed a Windows worker node from the cluster and this was successful.
7. Successfully deleted the cluster.
