### ISSUE TITLE
Remove/Disable Add and clone menu items from services & host for read-only or restricted members

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4213]
Version - v1.0.0 

Steps to Reproduce: 
1.  Set a user to read-only
2.  Set another user to restricted

Results: Can add/clone

Expected: For read-only, user should not be able to clone or add services or host.  restricted should not be able to add/clone host.

**Comment by vincent99** [comment]
Need a good way in the API to get the user's effective role for the current project to do this...

**Comment by vincent99** [comment]
We can look at this after RBAC for 2.0 is in.

**Comment by deniseschannon** [comment]
Closing in favor of https://github.com/rancher/rancher/issues/11165
