### ISSUE TITLE
Document expected failures for file permission issues on RKE, RKE2 and K3s Clusters when running CIS Scan

### ISSUE THREAD

**Issue by Priyashetty17** [rancher/rancher#42140]
**Issue Description:**
Currently, there are CIS checks related to file permissions that are failing on RKE, RKE2 and K3S clusters with **CIS v1.7  profiles** and **CIS v1.24  profiles**. These failures are expected and will be addressed in Q4 release with [GH-41131](https://github.com/rancher/rancher/issues/41131), when the issues created for each distro to address the file permissions are resolved ([GH-42012](https://github.com/rancher/rancher/issues/42012) for RKE, [GH-7975](https://github.com/k3s-io/k3s/issues/7975) for K3S, (https://github.com/rancher/rke2/issues/4473) for RKE2). However, it is important to document these expected failures in the **hardening guides for Q3 release** to provide clarity to users.

**With CIS v1.7  profile:**
- **Here are the CIS checks related to file permissions that are failing on RKE cluster:**
![image](https://github.com/rancher/rancher/assets/42880103/6d904172-b411-4990-909b-257e29abb73d)

- **Here are the CIS checks related to file permissions that are failing on RKE2 cluster:**
![image](https://github.com/rancher/rancher/assets/42880103/f8a2d103-5b89-41da-ac5b-899dbdc28efa)

- **Here are the CIS checks related to file permissions that are failing on K3S cluster:**
![image](https://github.com/rancher/rancher/assets/42880103/121158c2-48cb-438f-b323-023974584a5f)

**With CIS v1.24  profile:**
- **Here are the CIS checks related to file permissions that are failing on RKE2 cluster:**
![image](https://github.com/rancher/rancher/assets/42880103/ab5e842a-3966-4c4c-9f9d-784dd794046b)

- **Here are the CIS checks related to file permissions that are failing on K3S cluster:**
<img width="1120" alt="image" src="https://github.com/rancher/rancher/assets/42880103/81c72c39-fda4-4c66-a61b-bbdbaa14f0d6">

**References:**
- General issue: https://github.com/rancher/rancher/issues/41131
- K3S: https://github.com/k3s-io/k3s/issues/7975
- RKE: https://github.com/rancher/rancher/issues/42012
- RKE2: https://github.com/rancher/rke2/issues/4473

CC @andypitcher @JonCrowther @macedogm

**Comment by andypitcher** [comment]
@Priyashetty17 I believe that these checks should not be skipped.

1. For `RKE2`: I tested `1.1.1`, `1.1.3`, `1.1.5` and `1.1.7 ` and they are failing. In the current context, this is an expected behaviour as their respective files are in `644` instead of `600`. Still I added these files to [[RKE2] CIS Benchmark 1.24 requires file permissions to be 600 instead of 644](https://github.com/rancher/rke2/issues/4473#issue-1805606134)

- 1.1.1

```
I0719 21:31:33.286039 2823231 check.go:110] -----   Running check 1.1.1   -----
I0719 21:31:33.300012 2823231 check.go:309] Command: "stat -c permissions=%a /var/lib/rancher/rke2/agent/pod-manifests/kube-apiserver.yaml"
I0719 21:31:33.300057 2823231 check.go:310] Output:
 "permissions=644\n"
I0719 21:31:33.300070 2823231 check.go:231] Running 1 test_items
I0719 21:31:33.300147 2823231 test.go:153] In flagTestItem.findValue 644
I0719 21:31:33.300847 2823231 test.go:247] Flag 'permissions' exists
I0719 21:31:33.300879 2823231 check.go:255] Used auditCommand
I0719 21:31:33.300913 2823231 check.go:287] Returning from execute on tests: finalOutput &check.testOutput{testResult:false, flagFound:false, actualResult:"permissions=644", ExpectedResult:"permissions has permissions 644, expected 600 or more restrictive"}
I0719 21:31:33.300948 2823231 check.go:184] Command: "" TestResult: false State: "FAIL"
```

- 1.1.3

```
I0719 21:31:33.372962 2823231 check.go:110] -----   Running check 1.1.3   -----
I0719 21:31:33.399465 2823231 check.go:309] Command: "/bin/sh -c 'if test -e /var/lib/rancher/rke2/agent/pod-manifests/kube-controller-manager.yaml; then stat -c permissions=%a /var/lib/rancher/rke2/agent/pod-manifests/kube-controller-manager.yaml; fi'"
I0719 21:31:33.401086 2823231 check.go:310] Output:
 "permissions=644\n"
I0719 21:31:33.402836 2823231 check.go:231] Running 1 test_items
I0719 21:31:33.405787 2823231 test.go:153] In flagTestItem.findValue 644
I0719 21:31:33.409357 2823231 test.go:247] Flag 'permissions' exists
I0719 21:31:33.409408 2823231 check.go:255] Used auditCommand
I0719 21:31:33.409437 2823231 check.go:287] Returning from execute on tests: finalOutput &check.testOutput{testResult:false, flagFound:false, actualResult:"permissions=644", ExpectedResult:"permissions has permissions 644, expected 600 or more restrictive"}
I0719 21:31:33.409490 2823231 check.go:184] Command: "" TestResult: false State: "FAIL"
```

- 1.1.5

```
I0719 21:31:33.434259 2823231 check.go:110] -----   Running check 1.1.5   -----
I0719 21:31:33.460406 2823231 check.go:309] Command: "/bin/sh -c 'if test -e /var/lib/rancher/rke2/agent/pod-manifests/kube-scheduler.yaml; then stat -c permissions=%a /var/lib/rancher/rke2/agent/pod-manifests/kube-scheduler.yaml; fi'"
I0719 21:31:33.460456 2823231 check.go:310] Output:
 "permissions=644\n"
I0719 21:31:33.460473 2823231 check.go:231] Running 1 test_items
I0719 21:31:33.460589 2823231 test.go:153] In flagTestItem.findValue 644
I0719 21:31:33.460612 2823231 test.go:247] Flag 'permissions' exists
I0719 21:31:33.460622 2823231 check.go:255] Used auditCommand
I0719 21:31:33.460637 2823231 check.go:287] Returning from execute on tests: finalOutput &check.testOutput{testResult:false, flagFound:false, actualResult:"permissions=644", ExpectedResult:"permissions has permissions 644, expected 600 or more restrictive"}
I0719 21:31:33.460676 2823231 check.go:184] Command: "" TestResult: false State: "FAIL"
```

- 1.1.7

```
I0719 21:42:20.398486 2832369 check.go:110] -----   Running check 1.1.7   -----
I0719 21:42:20.467901 2832369 check.go:309] Command: "/bin/sh -c 'if test -e /var/lib/rancher/rke2/agent/pod-manifests/etcd.yaml; then find /var/lib/rancher/rke2/agent/pod-manifests/etcd.yaml -name '*etcd*' | xargs stat -c permissions=%a; fi'"
I0719 21:42:20.468233 2832369 check.go:310] Output:
 "permissions=644\n"
I0719 21:42:20.468342 2832369 check.go:231] Running 1 test_items
I0719 21:42:20.468497 2832369 test.go:153] In flagTestItem.findValue 644
I0719 21:42:20.468547 2832369 test.go:247] Flag 'permissions' exists
I0719 21:42:20.468569 2832369 check.go:255] Used auditCommand
I0719 21:42:20.468681 2832369 check.go:287] Returning from execute on tests: finalOutput &check.testOutput{testResult:false, flagFound:false, actualResult:"permissions=644", ExpectedResult:"permissions has permissions 644, expected 600 or more restrictive"}
I0719 21:42:20.468805 2832369 check.go:184] Command: "" TestResult: false State: "FAIL"
```


2. For `K3s`, there are some chances that the `1.1.1`, `1.1.3`, `1.1.5` and `1.1.7 ` file permissions are also to be set to 600.

**Comment by andypitcher** [comment]
The expected failures have been added for CIS-1.7 hardening guides. 

See the following PRs:
- https://github.com/rancher/rancher-docs/pull/797
- https://github.com/rancher/rancher-docs/pull/796
- https://github.com/rancher/rancher-docs/pull/794


We have two options regarding the hardening guides to cover CIS-1.24 and CIS-1.7.

1. We keep one hardening guide per distro referenced as CIS-1.7 (latest version), and englobes both `1.24 and older` and `1.25 and newer`, with some tabs (current state).
2. We use two hardening guides per distro, one for CIS-1.24 and one for CIS-1.7.

**Comment by andypitcher** [comment]
Closing this issue, the failing checks will be handled through this [new issue](https://github.com/rancher/rancher/issues/42971).

**Comment by andypitcher** [comment]
@samjustus here are the two issues for RKE/RKE2, that we need to fix:

- RKE: https://github.com/rancher/rancher/issues/42012
- RKE2: https://github.com/rancher/rke2/issues/4473
