### ISSUE TITLE
allow binding to non-local IP

### ISSUE THREAD

**Issue by DanielDent** [rancher/rancher#4214]
I'm extremely glad #53 was addressed.

One additional thought: it would be nice to be able to bind non-local addresses.

This is actually quite common in HA & Anycast setups. You bind an IP that is not local to the machine, while knowing that your binding won't be useful until something else happens somewhere else in the system (e.g. a new interface is bound & some API calls are made or ARP/ND magic is performed by a HA watchdog).

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
