### ISSUE TITLE
[BUG] With AD Auth enabled, on a Rancher server upgrade to 2.7.5+ version, users are suggested to wait to login until migration of users process is completed.

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#42146]
**Rancher Server Setup**
- Rancher version: 2.7-head latest or 2.7.5
- Installation option (Docker install/Helm Chart): Any
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:

**Describe the bug**
As per changes made in this issue - https://github.com/rancher/rancher/issues/37994, On a rancher server, with AD Auth enabled, and an upgrade to 2.7.5+, a migration process of users will be kicked off. This migration could take a couple of minutes depending on the number of users present and the resources related to users like crtbs, prtbs, etc. 

The suggestion is to wait for the migration to happen for users to login to the server to avoid hitting this issue - https://github.com/rancher/rancher/issues/42082 which can be fixed by running a script to delete duplicate users from the server. 

**Expected Result**
User must not have to wait to login to Rancher Server

**Note:**
As such, there is no message on the UI for the admin also to see if the migration has failed.

**Comment by prachidamle** [comment]
This issue was logged when migration process was added for https://github.com/rancher/rancher/issues/37994 in v2.7.5.
But since that is reverted, moving this ticket to be looked at in the milestone where https://github.com/rancher/rancher/issues/37994 will be fixed.

**Comment by nflynt** [comment]
The migration logic was removed from 2.7.6+, so the issue concerns the behavior of code that is no longer part of Rancher. We should test to confirm that the AD migration is no longer running at Rancher startup, and then this can be closed out.

(Note that the "unmigration" is tracked separately; it automatically suppresses logins and notifies the user of the ongoing migration.)
