### ISSUE TITLE
[BUG] Migration process for AD Users is kicked off for any Auth enabled setup not just an AD Auth enabled setup

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#42150]
**Rancher Server Setup**
- Rancher version: 2.7-head latest or 2.7.5
- Installation option (Docker install/Helm Chart): Any
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:

**Describe the bug**
As per changes made in this issue - https://github.com/rancher/rancher/issues/37994, On a rancher server, with Auth enabled other than AD, and an upgrade to 2.7.5+, a migration process of users will be kicked off. Since there are no AD users, this process will exit.

**Expected Result**

- Migration process is not kicked off at all since AD AUth is not set up
- Only when AD Auth is enabled should migration process be kicked off

**Comment by prachidamle** [comment]
This issue was logged when migration process was added for https://github.com/rancher/rancher/issues/37994 in v2.7.5.
But since that is reverted, moving this ticket to be looked at in the milestone where https://github.com/rancher/rancher/issues/37994 will be fixed.

**Comment by nflynt** [comment]
Since the migration logic was removed from 2.7.6+, it seems like we should test to confirm that it is no longer present and running at startup (on _any_ auth setup, not just AD) and then we should be good to close this out.

(Note that the "unmigration" logic is unrelated to this issue, and should be tracked separately.)
