### ISSUE TITLE
Update Hardening Guides to reflect removal of "protect-kernel-defaults" check in RKE/RKE2/K3S CIS 1.7 Profiles

### ISSUE THREAD

**Issue by Priyashetty17** [rancher/rancher#42154]
**Issue Description:**
Based on the PRs for CIS v1.7 profiles in [RKE](https://github.com/rancher/security-scan/pull/134), [RKE2](https://github.com/rancher/security-scan/pull/136), and [K3S](https://github.com/rancher/security-scan/pull/135), the check "4.2.6 Ensure that the --protect-kernel-defaults argument is set to true (Automated)" has been removed from the node.yaml file. 

Currently, the hardening guides for [RKE](https://ranchermanager.docs.rancher.com/pages-for-subheaders/rke1-hardening-guide#reference-hardened-rke-clusteryml-configuration), [RKE2](https://ranchermanager.docs.rancher.com/pages-for-subheaders/rke2-hardening-guide), and [K3S](https://ranchermanager.docs.rancher.com/pages-for-subheaders/k3s-hardening-guide) includes a manual step to set "protect-kernel-defaults" in the section "Ensure protect-kernel-defaults is set". This is set when creating a hardened cluster using a cis profile. However, with the removal of the corresponding check from the CIS 1.7 profiles, the manual step of setting "protect-kernel-defaults" is no longer necessary.

The hardening guides needs to be updated to reflect that the manual step of setting "protect-kernel-defaults" is no longer required when using the CIS 1.7 scan profiles.

CC @andypitcher @JonCrowther @macedogm

**Comment by Priyashetty17** [comment]
@andypitcher Since this change applies to v1.7 CIS profiles only and not the previous CIS profiles, should we explicitly mention in the hardening guide that "protect-kernel-defaults" has been retired by CIS Workbench, from CIS-1.7 but still applies to previous versions?

**Comment by andypitcher** [comment]
@Priyashetty17  this is mentioned in the notes, [example for k3s](https://github.com/rancher/rancher-docs/blob/c48f9f4162360f7fe6f60d59cd33fad2a71cee59/docs/pages-for-subheaders/k3s-hardening-guide.md?plain=1#L19C2-L19C2).

The PRs have been created:

- https://github.com/rancher/rancher-docs/pull/797
- https://github.com/rancher/rancher-docs/pull/796
- https://github.com/rancher/rancher-docs/pull/794

**Comment by andypitcher** [comment]
@macedogm can we merge the above PRs (they are still marked as waiting for your approval) ? This will solve the issue.

**Comment by macedogm** [comment]
@andypitcher PR https://github.com/rancher/rancher-docs/pull/797 is approved.

Apologies regarding the delay with the the other PRs, but I was waiting to get the "re-request review" re-triggered for these two PRs. I made some comments on them:

- RKE1 - https://github.com/rancher/rancher-docs/pull/794#pullrequestreview-1618682132
- RKE2 - https://github.com/rancher/rancher-docs/pull/796#pullrequestreview-1618680277

Sorry for being so picky about in the comments.

**Comment by macedogm** [comment]
@andypitcher I approved both PRs https://github.com/rancher/rancher-docs/pull/794 and https://github.com/rancher/rancher-docs/pull/796.

**Comment by andypitcher** [comment]
All three PRs have now been merged, `RKE/RKE2/K3S` hardening guides are now aligned with `cis-1.24` and `cis-1.7`.

- RKE:  https://ranchermanager.docs.rancher.com/pages-for-subheaders/rke1-hardening-guide
- RKE2: https://ranchermanager.docs.rancher.com/pages-for-subheaders/rke2-hardening-guide
- K3S: https://ranchermanager.docs.rancher.com/pages-for-subheaders/k3s-hardening-guide

This issue can be closed.
