### ISSUE TITLE
Revert all GUID PRs - Revert the fixes attempted post v2.7.5

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#42161]
A collection of bugs are necessitating a number of PRs to be reverted

context: 
- https://github.com/rancher/rancher/issues/42147
- https://github.com/rancher/rancher/issues/42146
- https://github.com/rancher/rancher/issues/42150
- https://github.com/rancher/rancher/issues/42147
- https://github.com/rancher/rancher/issues/42146

Here is the list of 3 PRs (6 commits) that need to be reverted on the release/v2.7 branch (revert  from  top  to  bottom)

-    https://github.com/rancher/rancher/pull/42145
    a308ee0d2aabe9800254a36ebd3960bcda716c97

-    https://github.com/rancher/rancher/pull/42077
    9cf8167081eefaa8ee1b5cf19b551ac7a160c34f
    ffa7994ef3bcb1384014158dee743a2b93a5b459
    32fcc1cce61240157c80dbd7e24674cba2506e0c
    75dea2e6ae932a753707c8800b70fb6665c6a45b

-    https://github.com/rancher/rancher/pull/42022
    c2975024109a01c8a51d988c118df1d325bfad07

**Comment by MKlimuszka** [comment]
PR: https://github.com/rancher/rancher/pull/42169

**Comment by prachidamle** [comment]
All the above PRs have been reverted from release/v2.7 branch, These fixes were made to release/v2.7 branch post v2.7.5 release.
The v2.7.6 branch was created from the v2.7.5 tag - thus 2.7.6 branch does not have any of the PRs.
Hence there is nothing to be reverted from v2.7.6 branch. 

Test cases:
Start with a release/2.7.6-head Rancher and set up Active Directory that has a non-flat hierarchy for users.
Spin-up downstream clusters and assign users throughout the AD hierarchy cluster/project permissions and create tokens for them.

Login as the users set up above and verify that their permissions and tokens are as expected
Login as admin/bound account to AD and verify that you can view/add/manage cluster/project permissions and that they are working.
With Rancher setup using v2.7-head, you should no longer see the errors from the refresher process as the refresh will succeed.
It should also be observed that at Rancher startup no migration process to convert DN to GUID will run, so no log messages indicating any migration run should be seen.

**Comment by Priyashetty17** [comment]
Validated with **v2.7.6-head**

**Priority/0 Basic** tests mentioned in the Test Plan were executed to validate the issues mentioned in this ticket: [GUID Data migration revert test plan](https://confluence.suse.com/pages/viewpage.action?spaceKey=RANQA&title=GUID+data+migration+revert+Test+plan)
