### ISSUE TITLE
Create pre-upgrade script to revert the GUID back to DN 

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#42162]
We need a pre-upgrade migration script to revert the GUID back to DN (to be run before upgrading to v2.7.6). 

This is to take care of customers who already attempted upgrade to v2.7.5 and have users who have their principalID already migrated.

What will the script do?

1. For AD users, Unmigrate the user CR and the prtb/crtb/tokens back to DN. 
2. Mark users that finished this migration with some type of annotation
3. Continue the migration if we hit any failed cases

**Comment by sowmyav27** [comment]
Validated tests as mentioned here - https://github.com/rancher/rancher/issues/42174#issuecomment-1684425538

Any issues found are being logged separately. 

1. For AD users, the user CR and the prtb/crtb/tokens are back to DN. 
2. Migration status is updated in a config map `ad-guid-migration` in cattle-system namespace and in Authconfig
3. if there are deleted users, these are skipped. And corresponding status is marked in configmap and Authconfig
