### ISSUE TITLE
Create a migration code in rancher to revert any users back to DN if they were migrated to GUID

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#42163]
Create a migration code in rancher to revert any users back to DN if they were migrated to GUID. This reverse migration should be in the Rancher codebase, to kickoff at startup. This will prevent bugs if a use attempts to upgrade without using the manual script. 

1. Record using configmaps if the migration ran AND completed, so that it does not kickoff again on rancher startup on next upgrades.
2. The code should log status of the migration (starting, skipping, completing) as well as logging state of updates to users (updating to DN, skipping)

**Comment by sowmyav27** [comment]
Closing as per these comments - https://github.com/rancher/rancher/issues/42162#issuecomment-1684712733
