### ISSUE TITLE
[v2.7.6] Revert feature - GUID for the PrincipalID for Active Directory 

### ISSUE THREAD

**Issue by prachidamle** [rancher/rancher#42174]
A report of bugs are necessitating a revert of the GUID enhancement from v2.7.6 branch:

PRs for GUID, including the following changes should be reverted from v2.7.6:

https://github.com/rancher/rancher/pull/41154

-    https://github.com/rancher/rancher/pull/41154
    80e729e4938c203cc5e0ed46b3396288fd4a6eb8
    cdd90ea6c687d8c83cfd0289e51be32da5c21d14

**Comment by prachidamle** [comment]
The  following PRs for GUID feature, are now reverted from v2.7.6:

https://github.com/rancher/rancher/pull/41154

https://github.com/rancher/rancher/commit/80e729e4938c203cc5e0ed46b3396288fd4a6eb8
https://github.com/rancher/rancher/commit/cdd90ea6c687d8c83cfd0289e51be32da5c21d14

**QA Testing Considerations**

1) With a fresh Rancher install from 2.7.6 branch, set up Active Directory as the auth provider. 
Verify that you can login as usual with valid users from that auth provider. All Rancher functionality should appear normal.

2) Verify that the user has been assigned a principalID based on DN and NOT a GUID by doing:
kubectl get user <user> --template='{{.principalIds}}'
The output of that should show one of the principalIds that will look DN-based principalId, example:
CN=username,CN=Users,DC=qa,DC=company,DC=org

3) This reverts the fix for the original issue https://github.com/rancher/rancher/issues/37994 , so changing the OU of a user will now result in a new Rancher user

**Comment by sowmyav27** [comment]
**On 2.7.6-head commit id: `2cf6683`**

- Verified Users/crtbs/prtbs have DN instead of GUID
- Verified api tokens as standard and admin users user work
- Verified Migration Script started and config map is created
