### ISSUE TITLE
[BUG] Can't add node to pool for RKE2 cluster on Harvester > Waiting for Node Ref

### ISSUE THREAD

**Issue by aleveille** [rancher/rancher#42175]
**Rancher Server Setup**
- Rancher version: v2.7.5
- Installation:
  - Helm
  - k3s --> v1.25.10+k3s1
  - Ubuntu 23.04

**Information about the Cluster**
- Kubernetes version:  v1.26.5+rke2r1
- Cluster Type: downstream (I guess?)
  - Provisioner: RKE2
  - Machine Provider: Harvester
  - (Harvester) Kubernetes Version: v1.24.11+rke2r1

**User Information**
- What is the role of the user logged in? Admin

**Describe the bug**
Can't add node to pool for RKE2 cluster on Harvester. The newly provisioned VM is stuck on "Waiting for Node Ref" in Rancher. The cluster itself is stuck on "Provisioning" with the error message "init node not found"

**To Reproduce**
- Lose a cluster VM (to disk corruption, or whatever other reason).
  - The node was an etcd member, control plane, worker 
  - It probably has to be the first node of the cluster.
- Try to scale the pool from 2 machines back to 3. 

**Result**
The newly provisioned machine on Harvester starts OK, but is stuck as "Waiting for Node Ref" in the Rancher UI.

```
- lastTransitionTime: '2023-07-20T14:04:16Z'
  reason: WaitingForNodeRef
  severity: Info
  status: 'False'
  type: NodeHealthy
```

**Expected Result**
The new VM should be added to the node pool.

**Screenshots**
<img width="1270" alt="Screenshot 2023-07-21 at 3 01 42 PM" src="https://github.com/rancher/rancher/assets/9257290/9c7e4677-4504-4b72-a2c3-3b1c64532702">

**Additional context**
- The other two nodes of the pool are OK. It should be possible to provision the new node from the other existing two.
- The file `/var/lib/rancher/agent/rancher2_connection_info.json` seems to have the correct info
- The service `rancher-system-agent.service` is active and running (see logs below)
- The service `qemu-guest-agent.service` is active and running
- The service `rke2-server.service` is (obviously, I guess?) missing

***Rancher system agent logs:***

> Jul 20 14:24:42 redacted-main-control-14fb3971-szc4b rancher-system-agent[598]: time="2023-07-20T14:24:42Z" level=info msg="Rancher System Agent version v0.3.3-rc4 (9e827a5) is starting"
> Jul 20 14:24:42 redacted-main-control-14fb3971-szc4b rancher-system-agent[598]: time="2023-07-20T14:24:42Z" level=info msg="Using directory /var/lib/rancher/agent/work for work"
> Jul 20 14:24:42 redacted-main-control-14fb3971-szc4b rancher-system-agent[598]: time="2023-07-20T14:24:42Z" level=info msg="Starting remote watch of plans"
> Jul 20 14:24:43 redacted-main-control-14fb3971-szc4b rancher-system-agent[598]: E0720 14:24:43.622899     598 memcache.go:206] couldn't get resource list for management.cattle.io/v3:
> Jul 20 14:24:43 redacted-main-control-14fb3971-szc4b rancher-system-agent[598]: time="2023-07-20T14:24:43Z" level=info msg="Starting /v1, Kind=Secret controller"

**Comment by XLordalX** [comment]
Did you ever figure this out? Having the exact same issue.

**Comment by aleveille** [comment]
I stop using Haverster. Rancher + bare metal (Proxmox) worked better for me.

**Comment by aleveille** [comment]
@maintainers Since I've stopped using Harvester, I'll be unlikely to be able to provide feedback on this issue. I'll therefore be closing it.
