### ISSUE TITLE
Agent registration defaults to private ip even when public is available 

### ISSUE THREAD

**Issue by VDuda** [rancher/rancher#4219]
**Rancher Version** --- 
Rancher	v1.0.0
Cattle	v0.159.2
User Interface	v0.100.3
Rancher Compose	v0.7.3

**Docker Version:** Docker version 1.10.3, build 20f81dd

**OS:** Ubuntu 14.04.2 LTS

**Steps to Reproduce:** 
AWS cloud with two instances.
One instance within a private subnet with only access to NAT; only a private IP will be assigned to the machine. 
One Instance within a public subnet with access to the internet gateway; private and public IPs will be assigned to the machine.
Both instances are able to communicate with each other within the internal network, using the private IP the two instances are able to communicate on all ports against each other. 
The public facing instance has ports 80 and 22 open to the world.

First, the private instance will be used to install the rancher server. The UI can be accessed via ssh-tunneling.
Next, the public instance will grab the project id, token id, and the agent image using curl against the private ip /v1 endpoint of the private instance. 
Using the above data, the public instance will run the rancher agent image and register it.

**Results:** The agent registers successfully against the rancher server, however, the agent registers with its own private ip. 

**Expected:** The expected result was to have the agent register with the public ip as stated within the following doc, http://docs.rancher.com/rancher/rancher-ui/infrastructure/hosts/custom/. Specifically note the statement ```By default, the IP of a VM with a private IP and public IP will be set to the public IP ```

Also here is the output of the log using docker log from the rancher agent on the public instance.
```
INFO: Starting agent for CD18A5DC251692AF13D4
INFO: Access Key: CD18A5DC251692AF13D4
INFO: Config URL: http://rancher.PRIVATE-IP-INSTANCE.com/v1
INFO: Storage URL: http://rancher.PRIVATE-IP-INSTANCE.com/v1
INFO: API URL: http://rancher.PRIVATE-IP-INSTANCE.com/v1
INFO: IP: 10.2.2.24
INFO: Port:
INFO: Required Image: rancher/agent:v0.11.0
INFO: Current Image: rancher/agent:v0.11.0
INFO: Using image rancher/agent:v0.11.0
INFO: Downloading agent http://rancher.PRIVATE-IP-INSTANCE.com/v1/configcontent/configscripts
INFO: Updating configscripts
INFO: Downloading http://rancher.PRIVATE-IP-INSTANCE.com/v1//configcontent//configscripts current=
INFO: Running /var/lib/cattle/download/configscripts/configscripts-1-f0f3fb2e1110b5ada7c441705981f93a480313a324294321cff467f0c3e12319/apply.sh
INFO: Sending configscripts applied 1-f0f3fb2e1110b5ada7c441705981f93a480313a324294321cff467f0c3e12319
INFO: Updating pyagent
INFO: Downloading http://rancher.PRIVATE-IP-INSTANCE.com/v1//configcontent//pyagent current=
INFO: Running /var/lib/cattle/download/pyagent/pyagent-1-9e3dcab12585149a65d818082279708965cd826df1937a55b24f48428f8f0c0673b9f37ae03c16234efdd22657d02b33/apply.sh
INFO: Updating host-api
INFO: Downloading http://rancher.PRIVATE-IP-INSTANCE.com/v1//configcontent//host-api current=
INFO: Running /var/lib/cattle/download/host-api/1-076f245550ef0d977e9dcfe411ef2faebde6b6277c93a3a02a17e69ef6c42c85/apply.sh
INFO: Sending host-api applied 1-076f245550ef0d977e9dcfe411ef2faebde6b6277c93a3a02a17e69ef6c42c85
INFO: Updating agent-binaries
INFO: Downloading http://rancher.PRIVATE-IP-INSTANCE.com/v1//configcontent//agent-binaries current=
INFO: Running /var/lib/cattle/download/agent-binaries/1-4200f9b686342da8e941359211b1d8c5f98877ae293d0ead231d43507f1c9eae/apply.sh
INFO: Sending agent-binaries applied 1-4200f9b686342da8e941359211b1d8c5f98877ae293d0ead231d43507f1c9eae
INFO: Updating python-agent
INFO: Downloading http://rancher.PRIVATE-IP-INSTANCE.com/v1//configcontent//python-agent current=
INFO: Running /var/lib/cattle/download/python-agent/1-a91ca3edd3ab1b58766de4c4206feefa9123274d9b7b999ab48766ca58609528/apply.sh
INFO: Sending python-agent applied 1-a91ca3edd3ab1b58766de4c4206feefa9123274d9b7b999ab48766ca58609528
INFO: Updating cadvisor
INFO: Downloading http://rancher.PRIVATE-IP-INSTANCE.com/v1//configcontent//cadvisor current=
INFO: Running /var/lib/cattle/download/cadvisor/1-21c3283c2bb12833be339f90a0c9a64d933464e475045636b8a43412ad630347/apply.sh
INFO: HOME -> ./
INFO: HOME -> ./bin/
INFO: HOME -> ./bin/cadvisor
INFO: HOME -> ./bin/cadvisor.sh
INFO: Sending cadvisor applied 1-21c3283c2bb12833be339f90a0c9a64d933464e475045636b8a43412ad630347
INFO: Sending pyagent applied 1-9e3dcab12585149a65d818082279708965cd826df1937a55b24f48428f8f0c0673b9f37ae03c16234efdd22657d02b33
INFO: Starting agent /var/lib/cattle/pyagent/apply.sh
INFO: Executing /var/lib/cattle/pyagent/main.py
INFO: Updating host-config
INFO: Downloading http://rancher.PRIVATE-IP-INSTANCE.com/v1//configcontent//host-config current=
INFO: Running /var/lib/cattle/download/host-config/host-config-1-91c08336cd39a5ec2f3dc3b617130380ff2b1a638ca38ad5b59f54fe2925d187/apply.sh
INFO: HOME -> ./
INFO: HOME -> ./etc/
INFO: HOME -> ./etc/cattle/
INFO: HOME -> ./etc/cattle/api.crt
INFO: Sending host-config applied 1-91c08336cd39a5ec2f3dc3b617130380ff2b1a638ca38ad5b59f54fe2925d187
time="2016-03-29T19:34:55Z" level="info" msg="Starting event router." 
time="2016-03-29T19:34:55Z" level="info" msg="Watching state directory: /var/lib/rancher/state/containers" 
Monitoring mount context of PID 961
time="2016-03-29T19:35:12Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"9454ed14ec11d1454b1ee0061d4a1b687fcc05cfea7b7b0e8666dd1cb7cbfe68\", From:\"-simulated-\", Time:0}" 
time="2016-03-29T19:35:12Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"68049f66ecd2b772fffa991d7e9aa5720b3c68be0fcd6b3e1d13f76ce0ee1f45\", From:\"-simulated-\", Time:0}" 
time="2016-03-29T19:35:12Z" level="info" msg="Connecting to proxy." url="ws://rancher.internal.fitzy.co/v1/connectbackend?token=eyJhbGciOiJSUzI1NiJ9.eyJleHAiOjE0NTkyODA0MTIsInN1YiI6ImNhdHRsZSIsImlzcyI6Imh0dHA6XC9cL2NhdHRsZS5pbyIsInJlcG9ydGVkVXVpZCI6Ijk1YjA2ZjAwLWQzNDktNGQ4NC04ZTJhLTEwODMzNjFhYWFmYyIsImlhdCI6MTQ1OTI4MDExMiwia2lkIjoiZGVmYXVsdCJ9.FDZ0SvnQ-RoZ0EYpEntk8pPPKwhsrQM_6BEPcLorXyWXVP49brxeoWlNJ2BzjGg2NGt1zd7k7JHqsFJJwuqzut_3_aoiueep8G_jU_fAzdN2AG5i-YIWbmCswRoTII-4EOOHOiYbsxo8nx-s4K7_3ZyutVx5bbSi79yYL7KDjoYKPRFwPUqQyPcCGwrhL3-qt72y66-7kdRVhZgbw5xJigmX2GVjSMivN4yI81YyoBRVTovcGN7PQbfsB64FjSg-TZCYN57gDpCp1UxCFhO5FD1ZVOL9ot8ahuOiNVFeDgQALFie1NQ0YJX9xzPLfToLleUYATiiwuHv43lcoaejOQ" 
time="2016-03-29T19:35:14Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"68049f66ecd2b772fffa991d7e9aa5720b3c68be0fcd6b3e1d13f76ce0ee1f45\", From:\"-simulated-\", Time:0}" 
time="2016-03-29T19:36:54Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"671ab21f6fe1045b460d0b0766d5015bc85f5ad3e843987496244cff7b56d255\", From:\"rancher/agent-instance:v0.8.1\", Time:1459280214}" 
time="2016-03-29T19:36:54Z" level="info" msg="Assigning IP [10.42.30.0/16], ContainerId [671ab21f6fe1045b460d0b0766d5015bc85f5ad3e843987496244cff7b56d255], Pid [20465]" 
time="2016-03-29T19:36:54Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"671ab21f6fe1045b460d0b0766d5015bc85f5ad3e843987496244cff7b56d255\", From:\"-simulated-\", Time:0}" 
time="2016-03-29T19:37:04Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"bafde55c22f9484e230f493f7f6d9f0f339ce6e2ef6b680c7281bf3d3d170477\", From:\"rancher/external-dns:v0.3.0\", Time:1459280224}" 
time="2016-03-29T19:37:05Z" level="info" msg="Assigning IP [10.42.50.61/16], ContainerId [bafde55c22f9484e230f493f7f6d9f0f339ce6e2ef6b680c7281bf3d3d170477], Pid [21487]" 
time="2016-03-29T19:37:05Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"bafde55c22f9484e230f493f7f6d9f0f339ce6e2ef6b680c7281bf3d3d170477\", From:\"-simulated-\", Time:0}" 
```

**Comment by deniseschannon** [comment]
If you want it to be the public IP, you can always set it by re-registering the agent and adding `-e CATTLE_AGENT_IP=<public_ip>` into the docker run command. Typically, we've seen in the case of both a public and private IP, it tends to pick the public but was this machine also hosting your rancher/server?

http://docs.rancher.com/rancher/faqs/agents/#how-does-the-host-determine-ip-address-and-how-can-i-change-it-what-do-i-do-if-the-ip-of-my-host-has-changed-due-to-reboot

**Comment by VDuda** [comment]
The rancher/server image was only running on the private ip instance. The rancher/agent image was running on the second instance which had a private ip and a public ip. 

A work around that I ended up using was to move the rancher/server image to an instance which had access to the internet gateway thus allowing the instance to have a public ip and private ip. 

However, I would prefer to have my original case since it allows me to isolate rancher/server - giving me the peace of mind that the outside world would not be able to communicate with the rancher/server.

**Comment by cjellick** [comment]
@VDuda I believe you found a bug in our documentation. :-) The docs are misleading as they assume the more typical scenario of the rancher-server being exposed on a public IP and thus the agent connecting to it by going out through its public interface instead of the private network.

rancher/server "guesses" the IP of a host based on the source IP of the agent making the request. So, if you are staying completely within your private network, we will only ever be able to guess the private IP.

**Comment by cjellick** [comment]
@deniseschannon Maybe you could update the docs to be more clear. Here's what it currently states:

> By default, the IP of a VM with a private IP and public IP will be set to the public IP. If you wanted to change the IP address to the private one, you’ll need to edit the command provided from the UI. In order for the rancher-agent container to be launched correctly, set the CATTLE_AGENT_IP environment variable to the private IP address. All the hosts within Rancher will need to be on the same network as Rancher server.

maybe it could be pudated to something like:
> By default, the IP of a VM with a private IP and public IP will be set to match the IP specificied in the registration URL. For example, if a private IP is used in the regirstation URL, then the host's private IP will be used. If you wanted to change the host's IP address, you’ll need to edit the command provided from the UI. In order for the rancher-agent container to be launched correctly, set the CATTLE_AGENT_IP environment variable to the desired IP address. All the hosts within Rancher will need to be on the same network as Rancher server.

**Comment by deniseschannon** [comment]
Thanks @cjellick. Updated docs with your recommendations.

**Comment by deniseschannon** [comment]
@VDuda If you have further questions, please re-open. As @cjellick mentioned, it looked like our docs weren't clear enough, which have been corrected since.

**Comment by imorti** [comment]
yeah, I'm seeing a different behavior. Registration URL is set to public IP but it's using the private IP anyway. Using 1.6.2 (new install). This is on AWS.
