### ISSUE TITLE
rancher/vm-rancheros for VM does not work

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4220]
Version - v1.0.0

Steps to Reproduce: 
1.  Enable VM
2.  Try to add VM with rancher/vm-rancheros as image

Results: VM stops and won't run.  Logs say:
3/29/2016 3:51:20 PMdnsmasq: bad dhcp-range at line 2 of /etc/dnsmasq.conf
3/29/2016 3:51:20 PM/var/lib/rancher/startvm: line 99: let: NEWCIDR=16
3/29/2016 3:51:20 PM16-1: syntax error in expression (error token is "16-1")
3/29/2016 3:51:20 PM/var/lib/rancher/startvm: line 123: let: i=2886795272^(1<<16
3/29/2016 3:51:20 PM16): missing `)' (error token is "16)")
3/29/2016 3:51:20 PMError: either "local" is duplicate, or "10.42.124.55/16" is a garbage.
3/29/2016 3:51:20 PMCould not initialize SDL(No available video device) - exiting

Expected: VM should run

**Comment by will-chan** [comment]
Is this still not working with latest fixes?

**Comment by vincent99** [comment]
`rancher/vm-rancheos` hasn't been updated in forever so I doubt it works, but even if it does we still should have a modern version.

**Comment by vincent99** [comment]
Removed the item from the dropdown in the UI for now..

**Comment by pwFoo** [comment]
Why it could't updated to RancherOS 0.4.5? Would be a great for testing and virtual host instances based on RancherVM RancherOS.

https://github.com/rancher/vm/issues/73

**Comment by tfiduccia** [comment]
master 1/12
VM feature removed from Rancher. When added back in, will do a full retest.  Including retesting this bug.
