### ISSUE TITLE
Node gets kicked out of Cluster after snapshots are restored.

### ISSUE THREAD

**Issue by susesgartner** [rancher/rancher#42201]
**Setup**
Rancher version: 2.7.5
Downstream cluster: Custom cluster
Nodes: 3
CNI: Cilium
Kubernetes version: v1.25.7+rke2r1

**Describe the bug**
When restoring a snapshot on a custom cluster a node gets deleted from the cluster. 

**To Reproduce**
1. Deploy a fresh RKE2 custom cluster
2. Take a snapshot
3. Restore snapshot 
4. repeat steps 2-3 until the bug is hit. (usually 2 tries)

**Result**
A worker node gets deleted from the cluster. 

**Expected Result**
All nodes remain in the cluster and the restore occurs properly.

**Screenshots**
<img width="1100" alt="image" src="https://github.com/rancher/dashboard/assets/136753565/3f0a0484-0733-4582-b47f-ede6da8053a7">

**Additional context**
Tried to reproduce this on 2.7.4 but was unable to do so after 5-10 restores

SURE-6669

**Comment by susesgartner** [comment]
Ticket 42201 - Test Results - ✅ 
---
Issue is no longer reproducible!

Verified fix on Rancher v2.7-369c7d37b9e678922297c3811b4329e18da4abdf-head:

Scenario 1 -
1. Fresh install of rancher v2.7-head
2. Provision a custom cluster with:
 one of each node role, 
 kubernetes version: v1.25.7+rke2r1
 CNI: cilium
3. Take a snapshot.
4. Restore a snapshot
5. Repeat steps 3-4 4 times.

**Comment by jakefhyde** [comment]
During investigation, we have identified two possible workarounds: one for preventing the issue in the first place, and one for cluster recovery when.

To prevent the issue in the first place:
- `rm -rf /var/lib/rancher/capr/idempotence/etcd-restore` on all hosts before attempting an etcd restoration operation(init node is only host that matters)
- Proceed with restore
- To recover the deleted machines from an affected cluster
- Run `rke2-killall.sh` or `k3s-killall.sh` on all nodes within the cluster.
- `rm -rf /var/lib/rancher/capr/idempotence/etcd-restore` on all hosts (init node is only host that matters)
- Proceed with restore
- Re-register removed machines
- `rm -rf /var/lib/rancher/cpr/idempotence/etcd-restore` on all hosts (init node is only host that matters)
- Restore again

**Comment by Tejeev** [comment]
@jakefhyde restating your comment as I think gh reformatted it (I might have read it wrong so please lmk if so):

**To prevent the issue in the first place:**
- `rm -rf /var/lib/rancher/capr/idempotence/etcd-restore` on all hosts before attempting an etcd restoration operation(init node is only host that matters)
- Proceed with restore

**To recover the deleted machines from an affected cluster**
- Run `rke2-killall.sh` or `k3s-killall.sh` on all nodes within the cluster.
- `rm -rf /var/lib/rancher/capr/idempotence/etcd-restore` on all hosts (init node is only host that matters)
- Proceed with restore

**Re-register removed machines**
- rm -rf /var/lib/rancher/cpr/idempotence/etcd-restore on all hosts (init node is only host that matters)
- Restore again
