### ISSUE TITLE
Add Stack button on System page

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4221]
Version - v1.0.0 

Steps to Reproduce: 
1.  Create Convoy-gluster stack from catalog
2.  Go to System under Applications menu
3.  Click on Add Stack and create

Results: The stack goes to the stack page and does not stay in the system page.  This is very confusing.

Expected: Should be a way to add a stack to the system page or not have the Add Stack button on this page.

**Comment by iamveen** [comment]
:+1: It'd be great if we could add stacks to the System namespace. Otherwise I find system services crowd out my application stacks on the main page.

**Comment by tfiduccia** [comment]
Version - master 6/15
This was added and Verified Fixed.
