### ISSUE TITLE
[RFE]  Validate that the new "Status" field cannot be changed by users with standard permissions.

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#42218]
related to Global Roles v2

SURE-6202

**Comment by JonCrowther** [comment]
Assuming `standard permissions` means a `Standard User`, by default they do not have the ability to edit Global Roles. In fact, the only builtin global roles that give edit permissions to global roles are `Administrator` and `Restricted Administrator`. Even the `Manage Users` only gives `get`, `list` and `watch` for globalroles. 

Users with edit permission can modify the status field, but it immediately reconciles and gets corrected. It is only extremely briefly incorrect. I don't think this issue requires new work, so I'll be closing it.
