### ISSUE TITLE
[RFE] Add webhook escalation check for "InheritedClusterRoles" field 

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#42214]
related to Global Roles v2

SURE-6636

**Comment by samjustus** [comment]
blocked by #42213

**Comment by MbolotSuse** [comment]
Validation Template for this is also included in https://github.com/rancher/rancher/issues/42213#issuecomment-1714138036.

**Comment by anupama2501** [comment]
Verified the following test cases on v2.8-head `fc12e7d `
More detailed steps have been added on QASE.

id | title
-- | --
1 | Verify global roles are not accessible by standard user
2 | Verify locked role templates cannot be used in the global roles inherited cluster roles
3 | Add the role template in inheritedClusterRoles and lock the role template
4 | Verify custom role templates cannot be deleted when referred in global roles
5 | UI checks Verify custom role templates cannot be deleted when referred in global roles
6 | Verify adding a project role in global roles >> inherited cluster roles  is rejected
7 | Inherit a cluster role that does not exist, verify webhook rejects the request
8 | Verify removing the label authz.management.cattle.io/grb-owner is rejected by webhook
9 | Edit the crtb and change the clusterroletemplatebinding.roleTemplateName
10 | Verify when a CRTB is stuck in deleting a new CRTB is created
11 | Escalation check: Create a roletemplate with a bad user subject
12 | Escalation check: Create a roletemplate with a bad group subject
13 | Escalation check: Verify roletemplate with local cluster permissions does not create CRTBs in the local cluster
14 | Escalation check: Create a CRTB with the same subject, cluster and same grb owner, verify the CRTB is deleted
15 | Escalation check: Creating a CRTB owned by a GRB in local cluster, should be removed as soon as its created
