### ISSUE TITLE
Document recommendation of not downgrading charts

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#42227]
Downgrading between certain versions of our monitoring chart is not recommended for a few reasons. This should be documented in an official place. 

* It will reintroduce previously fixed CVE's and bugs
* Some versions of monitoring have introduced new fields and there is no clean way to move back from that.

**Comment by Jono-SUSE-Rancher** [comment]
@dbason and @MKlimuszka - How is this still in v2.7.7? Did the documentation ever get completed? If not, we need to move it out of this milestone immediately and put it where it belongs.

**Comment by MKlimuszka** [comment]
@recena , do any charts support downgrading? We originally filed this ticket because there were a bunch of users downgrading monitoring and running into problems. But maybe this is a general issue with charts that should be documented and not just monitoring.

**Comment by recena** [comment]
@MKlimuszka No, we can't support the downgrade of chats.

**Comment by MKlimuszka** [comment]
Since this documentation clarification applies to all charts, not just monitoring, I am reassigning to the Mapps team.
