### ISSUE TITLE
no host appears -- agent gives up after 10 minutes, Firefox does fine nevertheless

### ISSUE THREAD

**Issue by kklepper** [rancher/rancher#4222]
*Describe your issue here*

I'm on AWS EC2 Ubuntu. My public IP address should work, shouldn't it? It doesn't. I tried several times, to no avail.

    http://54.93.76.161:8080/env/1a5/infra/hosts?mode=dot

![160329_rui](https://cloud.githubusercontent.com/assets/6130319/14127814/48161a5c-f61b-11e5-984b-c51d727ebcd4.PNG)

This is what I did:

1. start rancher server

    $ sudo docker run -d --name rs --restart=always -p 8080:8080 rancher/server
    5a0944459bb77f5480da46405dfac36c602aa66bcfcebe54d49c2519cb44b655
    $ sudo docker logs -f rs
    160329 23:19:08 [Note] /usr/sbin/mysqld (mysqld 5.5.47-0ubuntu0.14.04.1-log) starting as process 28 ...
    Uptime: 2  Threads: 1  Questions: 2  Slow queries: 0  Opens: 33  Flush tables: 1  Open tables: 26  Queries per second avg: 1.000
    Setting up database
    Importing schema
    CATTLE_AGENT_PACKAGE_AGENT_BINARIES_URL=/usr/share/cattle/artifacts/agent-binaries.tar.gz
    CATTLE_AGENT_PACKAGE_CADVISOR_URL=/usr/share/cattle/artifacts/cadvisor.tar.gz
    CATTLE_AGENT_PACKAGE_HOST_API_URL=/usr/share/cattle/artifacts/host-api.tar.gz
    CATTLE_AGENT_PACKAGE_NODE_AGENT_URL=/usr/share/cattle/artifacts/node-agent.tar.gz
    CATTLE_AGENT_PACKAGE_PYTHON_AGENT_URL=/usr/share/cattle/artifacts/python-agent.tar.gz
    CATTLE_AGENT_PACKAGE_RANCHER_DNS_URL=/usr/share/cattle/artifacts/rancher-dns.tar.gz
    CATTLE_AGENT_PACKAGE_RANCHER_METADATA_URL=/usr/share/cattle/artifacts/rancher-metadata.tar.gz
    CATTLE_AGENT_PACKAGE_RANCHER_NET_URL=/usr/share/cattle/artifacts/rancher-net.tar.gz
    CATTLE_CATTLE_VERSION=v0.159.2
    CATTLE_DB_CATTLE_DATABASE=mysql
    CATTLE_DB_CATTLE_MYSQL_HOST=localhost
    CATTLE_DB_CATTLE_MYSQL_NAME=cattle
    CATTLE_DB_CATTLE_MYSQL_PORT=3306
    CATTLE_DB_CATTLE_USERNAME=cattle
    CATTLE_GRAPHITE_HOST=
    CATTLE_GRAPHITE_PORT=
    CATTLE_HOME=/var/lib/cattle
    CATTLE_HOST_API_PROXY_MODE=embedded
    CATTLE_LOGBACK_OUTPUT_GELF_HOST=
    CATTLE_LOGBACK_OUTPUT_GELF_PORT=
    CATTLE_RANCHER_COMPOSE_VERSION=v0.7.3
    CATTLE_RANCHER_SERVER_IMAGE=v1.0.0
    CATTLE_USE_LOCAL_ARTIFACTS=true
    DEFAULT_CATTLE_API_UI_INDEX=//releases.rancher.com/ui/0.100.3
    DEFAULT_CATTLE_CATALOG_EXECUTE=true
    DEFAULT_CATTLE_CATALOG_URL=library=https://github.com/rancher/rancher-catalog.git,community=https://github.com/rancher/community-catalog.git
    DEFAULT_CATTLE_COMPOSE_EXECUTOR_EXECUTE=true
    DEFAULT_CATTLE_MACHINE_EXECUTE=true
    DEFAULT_CATTLE_RANCHER_COMPOSE_DARWIN_URL=https://releases.rancher.com/compose/v0.7.3/rancher-compose-darwin-amd64-v0.7.3.tar.gz
    DEFAULT_CATTLE_RANCHER_COMPOSE_LINUX_URL=https://releases.rancher.com/compose/v0.7.3/rancher-compose-linux-amd64-v0.7.3.tar.gz
    DEFAULT_CATTLE_RANCHER_COMPOSE_WINDOWS_URL=https://releases.rancher.com/compose/v0.7.3/rancher-compose-windows-386-v0.7.3.zip
    23:19:16.345 [main] WARN  o.e.jetty.security.SecurityHandler - ServletContext@o.e.j.w.WebAppContext@6b1fabf3{/,file:/usr/share/cattle/9283c067b6f96f5ff1e38fb0ddfd8649/,STARTING}{file:/usr/share/cattle/9283c067b6f96f5ff1e38fb0ddfd8649/} has uncovered http methods for path: /
    23:19:18.188 [main] INFO  ConsoleStatus - [1/6] [1ms] [1ms] Loading config-bootstrap
    23:19:18.512 [main] INFO  ConsoleStatus - [2/6] [327ms] [316ms] Loading base-config
    23:19:19.013 [main] INFO  ConsoleStatus - [3/6] [828ms] [501ms] Loading config
    23:19:19.033 [main] INFO  ConsoleStatus - [4/6] [848ms] [13ms] Starting config-bootstrap
    23:19:19.480 [main] INFO  ConsoleStatus - [5/6] [1295ms] [440ms] Starting base-config
    23:19:19.481 [main] INFO  ConsoleStatus - [6/6] [1296ms] [0ms] Starting config
    2016-03-29 23:19:19,933 INFO    [main] [ConsoleStatus] [1/32] [0ms] [0ms] Loading bootstrap
    2016-03-29 23:19:20,116 INFO    [main] [ConsoleStatus] [2/32] [183ms] [182ms] Loading config-defaults
    2016-03-29 23:19:26,420 WARN    [main] [liquibase] modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
    2016-03-29 23:19:30,810 INFO    [main] [ConsoleStatus] [3/32] [10877ms] [10694ms] Loading system
    2016-03-29 23:19:30,899 INFO    [main] [ConsoleStatus] [4/32] [10966ms] [89ms] Loading defaults
    2016-03-29 23:19:31,396 INFO    [main] [ConsoleStatus] [5/32] [11463ms] [497ms] Loading types
    2016-03-29 23:19:36,424 INFO    [main] [ConsoleStatus] [6/32] [16491ms] [5027ms] Loading system-services
    2016-03-29 23:19:36,780 INFO    [main] [ConsoleStatus] [7/32] [16847ms] [356ms] Loading agent-server
    2016-03-29 23:19:37,134 INFO    [main] [ConsoleStatus] [8/32] [17201ms] [354ms] Loading allocator-server
    2016-03-29 23:19:39,189 INFO    [main] [ConsoleStatus] [9/32] [19256ms] [2055ms] Loading api-server
    2016-03-29 23:19:41,732 INFO    [main] [ConsoleStatus] [10/32] [21799ms] [2543ms] Loading iaas-api
    2016-03-29 23:19:41,860 INFO    [main] [ConsoleStatus] [11/32] [21927ms] [127ms] Loading archaius
    2016-03-29 23:19:42,327 INFO    [main] [ConsoleStatus] [12/32] [22394ms] [467ms] Loading core-model
    2016-03-29 23:19:42,355 INFO    [main] [ConsoleStatus] [13/32] [22422ms] [28ms] Loading core-object-defaults
    2016-03-29 23:19:42,416 INFO    [main] [ConsoleStatus] [14/32] [22483ms] [61ms] Loading encryption
    2016-03-29 23:19:46,329 INFO    [main] [ConsoleStatus] [15/32] [26396ms] [3913ms] Loading process
    2016-03-29 23:19:46,381 INFO    [main] [ConsoleStatus] [16/32] [26448ms] [52ms] Loading redis
    2016-03-29 23:19:46,473 INFO    [main] [ConsoleStatus] [17/32] [26540ms] [92ms] Starting bootstrap
    2016-03-29 23:19:46,474 INFO    [main] [ConsoleStatus] [18/32] [26541ms] [1ms] Starting config-defaults
    2016-03-29 23:19:46,474 INFO    [main] [ConsoleStatus] [19/32] [26541ms] [0ms] Starting system
    2016-03-29 23:19:46,475 INFO    [main] [ConsoleStatus] [20/32] [26541ms] [0ms] Starting defaults
    2016-03-29 23:19:46,475 INFO    [main] [ConsoleStatus] [21/32] [26542ms] [0ms] Starting types
    2016-03-29 23:19:53,046 INFO    [main] [ConsoleStatus] [22/32] [33113ms] [6571ms] Starting system-services
    2016-03-29 23:19:53,049 INFO    [main] [ConsoleStatus] [23/32] [33116ms] [1ms] Starting agent-server
    2016-03-29 23:19:53,049 INFO    [main] [ConsoleStatus] [24/32] [33116ms] [0ms] Starting allocator-server
    2016-03-29 23:19:55,237 INFO    [main] [ConsoleStatus] [25/32] [35304ms] [2188ms] Starting api-server
    2016-03-29 23:19:56,676 INFO    [main] [ConsoleStatus] [26/32] [36743ms] [1439ms] Starting iaas-api
    2016-03-29 23:19:56,676 INFO    [main] [ConsoleStatus] [27/32] [36743ms] [0ms] Starting archaius
    2016-03-29 23:19:56,677 INFO    [main] [ConsoleStatus] [28/32] [36744ms] [0ms] Starting core-model
    2016-03-29 23:19:56,677 INFO    [main] [ConsoleStatus] [29/32] [36744ms] [0ms] Starting core-object-defaults
    2016-03-29 23:19:56,678 INFO    [main] [ConsoleStatus] [30/32] [36745ms] [1ms] Starting encryption
    2016-03-29 23:19:56,686 INFO    [main] [ConsoleStatus] [31/32] [36753ms] [8ms] Starting process
    2016-03-29 23:19:56,686 INFO    [main] [ConsoleStatus] [32/32] [36753ms] [0ms] Starting redis
    23:19:56.923 [main] INFO  ConsoleStatus - [DONE ] [42106ms] Startup Succeeded, Listening on port 8081
    time="2016-03-29T23:19:57Z" level=info msg="Starting websocket proxy. Listening on [:8080], Proxying to cattle API at [localhost:8081], Monitoring parent pid [7]."
    time="2016-03-29T23:19:57Z" level=info msg="Downloading certificate from http://localhost:8081/v1/credentials/1c1/certificate"
    time="2016-03-29T23:19:58Z" level=info msg="Starting Rancher Catalog service"
    time="2016-03-29T23:19:58Z" level=info msg="Using catalog library=https://github.com/rancher/rancher-catalog.git"
    time="2016-03-29T23:19:58Z" level=info msg="Using catalog community=https://github.com/rancher/community-catalog.git"
    time="2016-03-29T23:19:58Z" level=info msg="Setting log level" logLevel=info
    time="2016-03-29T23:19:58Z" level=info msg="Starting go-machine-service..." gitcommit=dc97268
    time="2016-03-29T23:19:58Z" level=info msg="Updating docker-machine-drivers from cattle."
    time="2016-03-29T23:19:58Z" level=info msg="Starting rancher-compose-executor" version=v0.7.3
    time="2016-03-29T23:19:59Z" level=info msg="Initializing event router" workerCount=10
    time="2016-03-29T23:19:59Z" level=info msg="Connection established"    

So this looks fine. Next agent:

    $ sudo docker run --name ag -e CATTLE_AGENT_IP='54.93.76.161'  -d --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v0.11.0 http://54.93.76.161:8080/v1/scripts/1672FF374F062B2FA693:1459288800000:RuycGaLcqtvqLn0n7ETkxy6HfbU

Both are running at first, but agent stops after 10 minutes:

    $ sudo docker ps -a
    
    CONTAINER ID        IMAGE                   COMMAND                  CREATED             STATUS                     PORTS                              NAMES
    7316e019138c        rancher/agent:v0.11.0   "/run.sh http://54.93"   15 minutes ago      Exited (1) 5 minutes ago                                      ag
    5a0944459bb7        rancher/server          "/usr/bin/s6-svscan /"   19 minutes ago      Up 19 minutes              3306/tcp, 0.0.0.0:8080->8080/tcp   rs

This is the agent log:

    $ id=ag
    $ sudo docker logs $id
    
    INFO: Running Agent Registration Process, CATTLE_URL=http://54.93.76.161:8080/v1
    INFO: Checking for Docker version >= 1.6.0
    INFO: Found Server version: 1.10.3
    INFO: docker version: Client version: 1.6.0
    INFO: docker version: Client API version: 1.18
    INFO: docker version: Go version (client): go1.4.2
    INFO: docker version: Git commit (client): 4749651
    INFO: docker version: OS/Arch (client): linux/amd64
    INFO: docker version: Server version: 1.10.3
    INFO: docker version: Server API version: 1.22
    INFO: docker version: Go version (server): go1.5.3
    INFO: docker version: Git commit (server): 20f81dd
    INFO: docker version: OS/Arch (server): linux/amd64
    INFO: docker info: Containers: 2
    INFO: docker info: Images: 104
    INFO: docker info: Storage Driver: aufs
    INFO: docker info: Root Dir: /var/lib/docker/aufs
    INFO: docker info: Backing Filesystem: extfs
    INFO: docker info: Dirs: 137
    INFO: docker info: Dirperm1 Supported: false
    INFO: docker info: Execution Driver: native-0.2
    INFO: docker info: Kernel Version: 3.13.0-79-generic
    INFO: docker info: Operating System: Ubuntu 14.04.4 LTS
    INFO: docker info: CPUs: 1
    INFO: docker info: Total Memory: 992.5 MiB
    INFO: docker info: Name: ip-172-31-30-16
    INFO: docker info: ID: YCVV:YNAX:447K:W5Y7:UMCK:QIJB:3QMI:N47Z:Q2UH:IMFW:HQXA:GWIO
    INFO: docker info: Http Proxy:
    INFO: docker info: Https Proxy:
    INFO: docker info: No Proxy:
    WARNING: No swap limit support
    INFO: Attempting to connect to: http://54.93.76.161:8080/v1
    ERROR: http://54.93.76.161:8080/v1 is not accessible
    ERROR: http://54.93.76.161:8080/v1 is not accessible
    ERROR: http://54.93.76.161:8080/v1 is not accessible
	..................................
    ERROR: http://54.93.76.161:8080/v1 is not accessible
    ERROR: Could not reach http://54.93.76.161:8080/v1. Giving up.    

The error seems clear, but Firefox has no problems at `http://54.93.76.161:8080/v1`:

![160329_ragent](https://cloud.githubusercontent.com/assets/6130319/14127569/3edb7600-f619-11e5-90f8-96a26b36438f.PNG)

Now what?

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.0.0` Cattle: `v0.159.2` UI: `v0.100.3` |
|Access|`Disabled`|
|Route|`hosts.index`|

**Comment by deniseschannon** [comment]
Is `8080` open in your security group?

http://docs.rancher.com/rancher/faqs/agents/#how-to-check-your-host-registration-is-set-correctly

**Comment by kklepper** [comment]
Sorry, I forgot to show this piece of information:

![160329_sg](https://cloud.githubusercontent.com/assets/6130319/14141815/c6093078-f681-11e5-87c4-cad8094fbd26.PNG)

**Comment by kklepper** [comment]
@deniseschannon 

With respect to the aforementioned documentation: `curl -i <Host Registration URL you set in UI>/v1` gives an error:


    ...
    </head>
    <body>
            <div id="container">
                    <h1>An Error Was Encountered</h1>
                    <p>Unable to locate the model you have specified: V1</p>        </div>
    </body>
    
Of course, port 8080 is the one to answer:


    $ curl -i 54.93.175.122:8080/v1
    HTTP/1.1 200 OK
    Content-Type: application/json; charset=utf-8
    Date: Wed, 30 Mar 2016 12:27:57 GMT
    Expires: Thu, 01 Jan 1970 00:00:00 GMT
    Server: Jetty(9.2.11.v20150529)
    Set-Cookie: PL=rancher;Path=/
    Vary: Accept-Encoding, User-Agent
    X-Api-Account-Id: 1a1
    X-Api-Client-Ip: 54.93.175.122
    X-Api-Schemas: http://54.93.175.122:8080/v1/schemas
    Transfer-Encoding: chunked
    
    {"id":"v1","type":"apiVersion","links":{"accounts":"http://54.93.175.122:8080/v1/accounts","...etc....

Or did I miss something?

**Comment by kklepper** [comment]
Once more: exited after 10 minutes


    $ sudo docker ps -a
    CONTAINER ID        IMAGE                                       COMMAND                  CREATED             STATUS                      PORTS                                                 NAMES
    0c37b276b772        rancher/agent:v0.11.0                       "/run.sh http://54.93"   17 minutes ago      Exited (1) 7 minutes ago                                                          ag
    0fdc88b3dd7b        rancher/server                              "/usr/bin/s6-svscan /"   17 minutes ago      Up 17 minutes               3306/tcp, 0.0.0.0:8080->8080/tcp                      rs

**Comment by deniseschannon** [comment]
Can you just confirm that if you log onto the host

```
curl -i http://54.93.76.161:8080/v1
```

returns 200 (if no auth is on) or 401 (if auth is on)

http://docs.rancher.com/rancher/faqs/agents/#how-to-check-your-host-registration-is-set-correctly

**Comment by kklepper** [comment]
What do you mean with _auth is on_?

We have a new IP now, so here it goes:


    $ sudo docker run -d --name rs --restart=always -p 8080:8080 rancher/server
    
    $ sudo docker run --name ag -e CATTLE_AGENT_IP='54.93.175.122'  -d --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v0.11.0 http://54.93.175.122:8080/v1/scripts/1672FF374F062B2FA693:1459288800000:RuycGaLcqtvqLn0n7ETkxy6HfbU
        
    $ curl -i http://54.93.175.122:8080/v1
    HTTP/1.1 200 OK
    Content-Type: application/json; charset=utf-8
    Date: Wed, 30 Mar 2016 18:26:33 GMT
    Expires: Thu, 01 Jan 1970 00:00:00 GMT
    Server: Jetty(9.2.11.v20150529)
    Set-Cookie: PL=rancher;Path=/
    Vary: Accept-Encoding, User-Agent
    X-Api-Account-Id: 1a1
    X-Api-Client-Ip: 54.93.175.122
    X-Api-Schemas: http://54.93.175.122:8080/v1/schemas
    Transfer-Encoding: chunked
    
    {"id":"v1","type":"apiVersion","links":{"accounts":"http://54.93.175.122:8080/v1/accounts","addOutputsInputs"... etc. ...

**Comment by kklepper** [comment]
I bet the agent will exit in 3 minutes:

    $ sudo docker ps -a
    
    CONTAINER ID        IMAGE                   COMMAND                  CREATED             STATUS              PORTS                              NAMES
    fc11baf4ef14        rancher/agent:v0.11.0   "/run.sh http://54.93"   7 minutes ago       Up 7 minutes                                           ag
    4fe427e9e31b        rancher/server          "/usr/bin/s6-svscan /"   8 minutes ago       Up 8 minutes        3306/tcp, 0.0.0.0:8080->8080/tcp   rs

**Comment by kklepper** [comment]
Ok, here is the proof:

    $ sudo docker ps -a
    
    CONTAINER ID        IMAGE                                       COMMAND                  CREATED             STATUS                      PORTS                                                 NAMES
    fc11baf4ef14        rancher/agent:v0.11.0                       "/run.sh http://54.93"   45 minutes ago      Exited (1) 35 minutes ago                                                         ag
    4fe427e9e31b        rancher/server                              "/usr/bin/s6-svscan /"   46 minutes ago      Up 46 minutes               3306/tcp, 0.0.0.0:8080->8080/tcp                      rs

**Comment by cjellick** [comment]
@kklepper bare with me, but I'd like to take rancher/agent out of the picture for a moment.
If you run `docker run -it ubuntu`
and then try `curl -i http://54.93.175.122:8080/v1` (probably will need to install curl) from inside the container, what do you get?

**Comment by kklepper** [comment]
@cjellick This is the result:


    root@ubuntu:/# curl -i http://54.93.220.76:8080/v1
    HTTP/1.1 200 OK
    Content-Type: application/json; charset=utf-8
    Date: Thu, 31 Mar 2016 09:28:52 GMT
    Expires: Thu, 01 Jan 1970 00:00:00 GMT
    Server: Jetty(9.2.11.v20150529)
    Set-Cookie: PL=rancher;Path=/
    Vary: Accept-Encoding, User-Agent
    X-Api-Account-Id: 1a1
    X-Api-Client-Ip: 54.93.220.76
    X-Api-Schemas: http://54.93.220.76:8080/v1/schemas
    Transfer-Encoding: chunked
    
    {"id":"v1","type":"apiVersion","links":{"accounts":"http://54.93.220.76:8080/v1/accounts",.. etc. ...

**Comment by ianwalter** [comment]
I have the same issue except mine occurred when using SSL:
```
ERROR: https://rancher.mydomain.com/v1 is not accessible
```
UI and API work fine in Chrome.

**Comment by ianwalter** [comment]
Apparently I wasn't using the right bundled certificate, not sure how it worked in my browser! Sorry for the noise.

**Comment by deniseschannon** [comment]
@kklepper Could you do another test? Could you try launching a host through the UI using the EC2 option? This would just call a docker-machine command and launch another EC2 instance, but I'm curious if it would be able to connect to your rancher-server instance. Trying to isolate if the issue is with using the same host for rancher/server and rancher/agent or not.

Also, _auth on_ was whether or not you had enabled [Access Control](http://docs.rancher.com/rancher/configuration/access-control/)

**Comment by kklepper** [comment]
@deniseschannon I'd like to, but right now I wrestle with docker eating up all my space. It is not the (stale or not) images and not unused containers - absolutely enigmatic. As soon as I resolve this (resetting docker to a clean state will do) I try to comply to your inquiry.

**Comment by kklepper** [comment]
Problem solved: it was docker volumes which ate up disk space. 

I'm afraid I need more help as I don't know what to do. I have started rancher/server, and now what? 

I found http://docs.rancher.com/rancher/rancher-ui/infrastructure/hosts/amazon/, but I don't see how I can reach this from http://MY_EC2_IP:8080/env/1a5/infra/hosts/add/custom

**Comment by cjellick** [comment]
@kklepper there should be a AWS tab at the top.
![screen shot 2016-04-08 at 1 42 20 pm](https://cloud.githubusercontent.com/assets/2473240/14397030/d9daaefa-fd8f-11e5-9baf-9e653cf36dc5.png)

You don't see that? Do you just see Custom and other?

**Comment by kklepper** [comment]
@cjellick Thank you. Looks really good and convincing.

This is what I see:

![rancher_ui](https://cloud.githubusercontent.com/assets/6130319/14400014/1d38cb56-fdf3-11e5-9677-4e944f9095ec.PNG)

**Comment by deniseschannon** [comment]
Yes, you need to set up your host registration before launching any hosts. This is what helps us customize  the docker command that launches rancher agents.

**Comment by kklepper** [comment]
Ok. Got it. 

![rancher_1](https://cloud.githubusercontent.com/assets/6130319/14403930/feb59e80-fe69-11e5-9b9f-0d16a8938dd8.PNG)
![rancher_2](https://cloud.githubusercontent.com/assets/6130319/14403932/febb2cd8-fe69-11e5-823d-73aacfa53818.PNG)
![rancher_3](https://cloud.githubusercontent.com/assets/6130319/14403931/feb937ac-fe69-11e5-8774-a315db042471.PNG)
![rancher_4](https://cloud.githubusercontent.com/assets/6130319/14403956/a56d7054-fe6a-11e5-986b-da64c041d152.PNG)

What now?

**Comment by cjellick** [comment]
@kklepper that authorization exception is coming from Amazon. It may be that your credentials don't have sufficient access. Off the top of my head, I know the keys need access to 1) list regions 2) create security groups 3) create VMs. Can you confirm that those credentials have those permissions?

**Comment by kklepper** [comment]
@cjellick Well, I'm not that proficient in AWS, but these are the only credentials I got apart from AWS CLI which is ruled out, obviously. I'm based in `eu-central-1`, maybe that's what bites us here.

**Comment by deniseschannon** [comment]
You'll probably need to look into what type of credentials you have and what permissions.

http://docs.aws.amazon.com/general/latest/gr/root-vs-iam.html

Where you are based shouldn't matter as you are just calling the Amazon API.

**Comment by kklepper** [comment]
@deniseschannon I don't use IAM as I just get my feet wet with AWS.

**Comment by deniseschannon** [comment]
@kklepper Were you able to sort out your permissions with AWS? Do you still need assistance?

**Comment by kklepper** [comment]
@deniseschannon I didn't try anymore. There are other technologies to explore solving our problems maybe even better, so rancher isn't on my screen right now.
