### ISSUE TITLE
[flaky-test] test_mcapp_rollback_validation test failure

### ISSUE THREAD

**Issue by MbolotSuse** [rancher/rancher#42239]
**Flaky Test**

```
tests/integration/suite/test_multi_cluster_app.py - test_mcapp_rollback_validation
```

**Release Branch**

source branch of PR: `release/v2.7`

**Drone Build (if applicable)**

pipeline stage URL: https://drone-pr.rancher.io/rancher/rancher/31076/5/2

**Comment by macedogm** [comment]
Another pipeline failure related to the same issue:

- https://drone-pr.rancher.io/rancher/rancher/31411/5/2
