### ISSUE TITLE
host doesn't get added on local machine

### ISSUE THREAD

**Issue by compscied** [rancher/rancher#4225]
Rancher Version: 1.0

Docker Version: 1.10.3, build 20f81dd

OS: ubuntu 14.04

Steps to Reproduce: trying to add host with public IP as recommended
sudo docker run -e CATTLE_AGENT_IP='173.186.135.99'  -d --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v0.11.0 http://localhost:8080/v1/scripts/40CC70F90239782157D7:1459321200000:BQeQPiqXxtQeeBq2D2waEqhMxTA

Results: host doesn't get added

The image seems to pull down fine tried various options:
Unable to find image 'rancher/agent:v0.11.0' locally
Pulling repository docker.io/rancher/agent
5a774ccc97eb: Pull complete 
91f7f9444ee1: Pull complete 
5d48199ced94: Pull complete 
1fbe3bd23e5c: Pull complete 
6dcf641459c9: Pull complete 
ffef134d6ce7: Pull complete 
959d9d0e49ab: Pull complete 
b895775f795e: Pull complete 
e22e8a616e7c: Pull complete 
757774925e38: Pull complete 
cbdec5028dbc: Pull complete 
Status: Downloaded newer image for rancher/agent:v0.11.0
docker.io/rancher/agent: this image was pulled from a legacy registry.  Important: This registry version will not be supported in future versions of docker.
2f9a715efea37d12a5248fbcc530fa0798163fac88c7f6620f4ad35aa7c3db43
a@ubuntu:~$ sudo docker run -e CATTLE_HOST_LABELS='name=mypc'  -d --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v0.11.0 http://localhost:8080/v1/scripts/40CC70F90239782157D7:1459321200000:BQeQPiqXxtQeeBq2D2waEqhMxTA
c8953aac62ab312777e8be9668b1ac37b7029c8c9c5912609ffdf3cefe61341b
a@ubuntu:~$ sudo docker run -e CATTLE_AGENT_IP='127.0.0.1'  -d --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v0.11.0 http://localhost:8080/v1/scripts/40CC70F90239782157D7:1459321200000:BQeQPiqXxtQeeBq2D2waEqhMxTA
e2a9a8aa42e66b68dce2f5a7c75d65056fadde6a0ce1934a8077cfb53a3e7f4f
a@ubuntu:~$ sudo docker run -e CATTLE_AGENT_IP='173.186.135.99'  -d --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v0.11.0 http://localhost:8080/v1/scripts/40CC70F90239782157D7:1459321200000:BQeQPiqXxtQeeBq2D2waEqhMxTA
ffcabf374acbad368bddf467dca64175c9426b788397865c9d9e4c382c80cb37

Expected: host is added ;-)

**Comment by deniseschannon** [comment]
Can your host actually connect to `http://localhost:8080`?

http://docs.rancher.com/rancher/faqs/agents/#how-to-check-your-host-registration-is-set-correctly

Can you get more detailed agent logs?
http://docs.rancher.com/rancher/faqs/agents/#where-can-i-find-detailed-logs-of-the-rancher-agent-container

**Comment by compscied** [comment]
I can connect to http://localhost:8080/ and I get to rancher ui just fine
I don't have even dir /var/log/rancher/ 

the following docker images are running
sudo docker images
[sudo] password for a: 
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
rancher/server      latest              fbc1386c5156        40 hours ago        776 MB
rancher/agent       v0.11.0             92d6d865af44        11 days ago         416.1 MB
hello-world         latest              690ed74de00f        5 months ago        960 B
rancher/agent       v0.7.9              090bb4564994        10 months ago       372.3 MB

**Comment by cjellick** [comment]
@compscied you cannot use localhost, you have to use an ip (even if it just a 192... address) for the domain. The initial container is not --net=host, so "localhost" to it is the agent container itself.

**Comment by deniseschannon** [comment]
@compscied If you are still having issues, please re-open, but as @cjellick mentioned, you'd need to use a real IP for the host registration. 

http://docs.rancher.com/rancher/latest/en/configuration/settings/#host-registration
