### ISSUE TITLE
[2.7.6][BUG] Fleet v0.7.1-rc.1 is not in 2.7.6-head causing errors during docker install

### ISSUE THREAD

**Issue by thaneunsoo** [rancher/rancher#42253]
**Rancher Server Setup**
- Rancher version: v2.7.6-head
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): Docker Install
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: 
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:

**Describe the bug**

When doing a docker install with the following command:
```
sudo docker run -d --restart=unless-stopped -p 80:80 -p 443:443 --privileged rancher/rancher:v2.7.6-head
```
the logs keep outputting 
```
2023/07/28 15:14:26 [ERROR] Failed to find system chart fleet will try again in 5 seconds: no chart name found
2023/07/28 15:14:31 [ERROR] available chart version (102.1.0+up0.7.0) for fleet is less than the min version (102.1.1+up0.7.1-rc.1) 
```
![image](https://github.com/rancher/rancher/assets/108360907/403f5f8e-e066-4ce1-92ce-b1fe440386e3)

**To Reproduce**

Install Rancher using docker command
```
sudo docker run -d --restart=unless-stopped -p 80:80 -p 443:443 --privileged rancher/rancher:v2.7.6-head
```

**Result**
the logs keep outputting 
```
2023/07/28 15:14:26 [ERROR] Failed to find system chart fleet will try again in 5 seconds: no chart name found
2023/07/28 15:14:31 [ERROR] available chart version (102.1.0+up0.7.0) for fleet is less than the min version (102.1.1+up0.7.1-rc.1) 
```

**Expected Result**

The new updated chart version should be available https://github.com/rancher/rancher/pull/42237
It seems the branch is building using a charts repo that doesn't have that version
https://github.com/rancher/rancher/blob/4a675a3cc465c35bc5ae68d427708995ce1eab67/package/Dockerfile#L20

**Comment by deniseschannon** [comment]
Once the build passes with this PR, this will be fixed and unblock all testing.

**Comment by thaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.7.6-head 0113791
Rancher cluster type: single-node docker install
Docker version: 20.10

----------

### Testing: ###
With the Fleet chart version being reverted, the error in the logs are no longer reproducible and Rancher is successfully deployed using the following docker run
```
sudo docker run -d --restart=unless-stopped -p 80:80 -p 443:443 --privileged rancher/rancher:v2.7.6-head
```
