### ISSUE TITLE
agent-instance not upgraded to latest

### ISSUE THREAD

**Issue by liyimeng** [rancher/rancher#4226]
Rancher Version: 1.0.0

Docker Version: Docker version 1.10.1, build 9e83765

OS: RancherOS:v0.4.3

Steps to Reproduce: 
Follow upgrade instruction to upgrade rancher from v0.5.1 to v1.0.0, 
<pre>
CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS              PORTS                                          NAMES
16247ebb7f93        rancher/agent-instance:v0.8.0   "/etc/init.d/agent-in"   4 minutes ago       Up 4 minutes        0.0.0.0:500->500/udp, 0.0.0.0:4500->4500/udp   95c76895-2b6c-4430-bfab-18db63fbbb48
e6f8f68dab4e        rancher/agent:v0.11.0           "/run.sh run"            21 minutes ago      Up 5 minutes                                                       rancher-agent
2b586aaf7981        rancher/server:latest           "/usr/bin/s6-svscan /"   22 minutes ago      Up 22 minutes       3306/tcp, 0.0.0.0:8080->8080/tcp               hopeful_joliot
</pre>  

Stop and remove rancher/agent-instance, and should be restarted automatically with  rancher/agent-instance:v0.8.1.
Results: 
but it is not!
<pre>
[rancher@Rancher ~]$ docker rm -f 16247ebb7f93 && docker rmi rancher/agent-instance:v0.8.0
16247ebb7f93
Untagged: rancher/agent-instance:v0.8.0
Deleted: sha256:f4c7ed48703780039e5d20861fed77c53cd5cd8db9f6959d6cba9f1f6be5a8ae
Deleted: sha256:ac109f97eae55eda628df35d2d3a5d4806e52a03db4cd214e6f5f81faf51c0cb
Deleted: sha256:ef731aefb5cf904be514c20df9ed3445edf4f39bf6db5187a2056a131feac4a6
Deleted: sha256:957c7501c779e78915ddb263a25fd0df905cc21de7b9cc21c5c30d0d1d39be45
[rancher@Rancher ~]$ docker ps 
CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS              PORTS                                          NAMES
b1a83aa9d13c        rancher/agent-instance:v0.8.0   "/etc/init.d/agent-in"   21 seconds ago      Up 20 seconds       0.0.0.0:500->500/udp, 0.0.0.0:4500->4500/udp   95c76895-2b6c-4430-bfab-18db63fbbb48
e6f8f68dab4e        rancher/agent:v0.11.0           "/run.sh run"            25 minutes ago      Up 8 minutes                                                       rancher-agent
2b586aaf7981        rancher/server:latest           "/usr/bin/s6-svscan /"   26 minutes ago      Up 25 minutes       3306/tcp, 0.0.0.0:8080->8080/tcp               hopeful_joliot
</pre>
Expected:
<pre>
[rancher@Rancher ~]$ docker ps 
CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS              PORTS                                          NAMES
b1a83aa9d13c        rancher/agent-instance:v0.8.1   "/etc/init.d/agent-in"   21 seconds ago      Up 20 seconds       0.0.0.0:500->500/udp, 0.0.0.0:4500->4500/udp   95c76895-2b6c-4430-bfab-18db63fbbb48
</pre>

**Comment by deniseschannon** [comment]
Can you do a `docker images` to confirm that your `rancher/server:latest` is actually v1.0.0?

**Comment by nlhkh** [comment]
I am also seeing the same behavior, though it seems the system is working normally. I destroyed the network-agent instances, and they are recreated with the same 0.8.0.

**Comment by deniseschannon** [comment]
Network agents do not need to be upgraded to the latest version as the running container is upgraded even if the image of the container is not. 

I have just updated the docs with the same reflection. 

http://docs.rancher.com/rancher/upgrading/#rancher-agents

**Comment by nlhkh** [comment]
Ah great. Thank you :)

**Comment by liyimeng** [comment]
@deniseschannon  I have two hosts, one is upgraded from the old version, and one is installed fresh new. The new host pick up the last agent-instance, while the upgrade one is not. 

I deploy a wordpress after upgrade. wordpress container is scheduled into the old host, while mariadb is in new host.  I find it is not possible to ping from wordpress container to mariadb container, there seems not network connection.  I am wondering if it is because of the inconsistent of angent-instance between these two host.  Bellow are the images: 
<pre>
[rancher@Rancher ~]$ docker images
REPOSITORY                   TAG                 IMAGE ID            CREATED             SIZE
rancher/server               latest              fbc1386c5156        2 days ago          775.9 MB
rancher/server               v1.0.0              fbc1386c5156        2 days ago          775.9 MB
rancher/agent-instance       latest              57f5787fb673        11 days ago         316.1 MB
rancher/agent-instance       v0.8.1              57f5787fb673        11 days ago         316.1 MB
rancher/agent                latest              d0cbe5a51072        12 days ago         416 MB
rancher/agent                v0.11.0             d0cbe5a51072        12 days ago         416 MB
elasticsearch                2.2.1               51340b3eab01        2 weeks ago         347.1 MB
wordpress                    latest              e146b48c1da2        3 weeks ago         516.6 MB
elasticsearch                latest              3ac9ed8ea311        4 weeks ago         346.5 MB
mariadb                      latest              1df910c57679        4 weeks ago         347.2 MB
rancher/agent-instance       v0.8.0              f4c7ed487037        8 weeks ago         316.1 MB
nginx                        1.9.9               fb7fe53bd952        11 weeks ago        133.8 MB
registry                     2.1                 52bb991b482e        5 months ago        220.1 MB
rancher/elasticsearch-conf   v0.4.0              eebd86a05800        5 months ago        10.53 MB

</pre>

**Comment by deniseschannon** [comment]
@liyimeng The difference between the agent-instance images should not be the issue. If you are having networking issues, can you please read through the the [troubleshooting FAQs](http://docs.rancher.com/rancher/faqs/troubleshooting/) on cross host communication and networking? Can you open a new issue if you are not able to resolve your networking issues with the logs?

We have explained the reasons why the agent-instance will not be updated on the image name.
