### ISSUE TITLE
[v2prov] Unable to change machinedeployment labels/annotations without triggering redeployment of entire machine deployment

### ISSUE THREAD

**Issue by Oats87** [rancher/rancher#42270]
Due to Rancher's usage of CAPI v1.2.x, it is not possible to change labels/annotations on a machine deployment without triggering a full rollout of a machinedeployment. This is less than ideal especially when dealing with nodes that may contain state on disk (for example, using Longhorn).

cluster-api core 1.4 now propagates labels/annotations onto machines without triggering redeployments i.e.
>Cluster API now continuously propagate labels, annotations down the hierachy of objects - from ClusterClass to KubeadmControlPlane/MachineDeployments and ultimately to Machines - without triggering unecessary rollouts. The same improvement applies also to other fields impacting only Kubernetes objects or controller behaviour (e.g NodeDrainTimeout).
as per: https://github.com/kubernetes-sigs/cluster-api/releases/tag/v1.4.0

https://github.com/rancher/rancher/issues/41094 would be a method of resolving this as it allows cluster-api v1.4.x controllers/webhook to be run.

**Comment by hansbogert** [comment]
@Oats87  This no longer happens, do you happen to know when this behavior was changed?
