### ISSUE TITLE
Modify stack/compose file

### ISSUE THREAD

**Issue by JulianKingman** [rancher/rancher#4228]
Rancher Version: 1.0.0
Docker Version: 1.10.3
OS: Ubuntu 14.04

The one thing that I _really_ miss from Tutum is the ability to edit the compose files.

In Tutum, one can edit a compose file, save it, and then affected containers are marked for redeployment. Redeploying containers then starts them with the new configuration, with the option to keep data volumes intact. This is especially helpful if I make a mistake in my compose file, then I don't have to delete the whole stack and try again (which is especially frustrating when I'm first setting it up). Any chance this feature will make its way into rancher? Is the only way to change a stack after deployment really to delete it and start another one, or did I miss something?

**Comment by cloudnautique** [comment]
'Editing' is really upgrading a service. In the ui you can click upgrade and make the changes you need. After the upgrade you can confirm or roll back. 

It is advised that data volumes live in sidekicks, and that you don't edit those once they are deployed. This will allow you to access the data in the new versions.

**Comment by deniseschannon** [comment]
If you prefer to edit compose files, then you could use rancher-compose to upgrade your services.

http://docs.rancher.com/rancher/rancher-compose/upgrading/

**Comment by JulianKingman** [comment]
I take it this can't be done in the UI?

**Comment by JulianKingman** [comment]
How do you upgrade through the UI?

**Comment by deniseschannon** [comment]
On the service dropdown, you can click on **Upgrade**.

**Comment by JulianKingman** [comment]
OK, thanks! Is there a rancher label to enable auto-upgrades? I’m guessing there is not, so I’m setting up Jenkins for now.

**Comment by deniseschannon** [comment]
There is no auto-upgrade. I'm assuming you are thinking of some kind of webhook so that if you push a new image, we'd upgrade to the latest image? 

https://github.com/rancher/rancher/issues/619

**Comment by JulianKingman** [comment]
Thats right. I've figured out how to upgrade with the api, but not sure how to force it to pull the image. The "always pull" label, I'm not sure it works with the Api, or maybe it works but I need to detect if the upgrade completed and run "finish upgrade"... I'll check and report back.

**Comment by JulianKingman** [comment]
It appears the API won't pull a fresh image, even with the "Always pull image before creating" option checked.

**Comment by deniseschannon** [comment]
If you're doing the upgrade with the API, you'll need ot make sure to add the label

`io.rancher.container.pull_image: always` to the service, which is what triggers the service to pull the image before being created.

http://docs.rancher.com/rancher/labels/

The checkbox in the UI is the equivalent of creating this label.

**Comment by JulianKingman** [comment]
Even with the label, it doesn't seem to pull the image when upgraded via the API.

**Comment by deniseschannon** [comment]
@JulianKingman Are you still facing this issue in v1.1.1?

We have been unable to reproduce.

**Comment by deniseschannon** [comment]
@JulianKingman Please re-open if you still have questions.

**Comment by GerBreOwn** [comment]
The link http://docs.rancher.com/rancher/rancher-compose/upgrading/ from above is NO longer available.

**Comment by vincent99** [comment]
http://rancher.com/docs/rancher/v1.6/en/cattle/upgrading/#upgrading-services-with-rancher-compose

**Comment by joantune** [comment]
well, the problem with the UI is that you cannot yet edit the ulimits - as I was trying to launch an instance of ElasticSearch I now have this problem.

So now the solution for me is to use rancher-compose instead - i.e. get the current config - translate ES's docker-compose.yml to rancher-compose.yml and add that section in.

I suggest you guys, if feasible, to add in the UI a field that allows you to change the command, or better yet, to show you the rancher-compose and be able to edit it before you click on upgrade or create a new service.

It is more less maintenance than doing an UI for everything
