### ISSUE TITLE
Device bindings on service are not reflected in Compose YAML

### ISSUE THREAD

**Issue by ovidner** [rancher/rancher#4232]
Rancher Version: 1.0.0
Docker Version: 1.10.1
OS: Ubuntu 14.04.4 x86-64
Steps to Reproduce: 

- Add service to stack with device binding (via GUI)
- View Compose YAML for stack

Results: No device bindings for service in YAML.
Expected: Device bindings for service (as in https://docs.docker.com/compose/compose-file/#devices) in YAML.

**Comment by soumyalj** [comment]
Verified in master, the device binding is reflected in docker-copmose.yml 
```
  devices:
  - /dev/sda:/opt:rwm
```
