### ISSUE TITLE
Add unit tests for AD GUID unmigration 

### ISSUE THREAD

**Issue by nflynt** [rancher/rancher#42328]
Compliments: https://github.com/rancher/rancher/pull/42325

Automated testing is required for the new migration logic. In particular, we should unit test the identification steps of the script that produce work units, as this can be fed a synthesized set of users and will thus only need to mock the LDAP DN lookup. It should be possible to test detection of GUID and DN based duplicates, and the planned changes to CRTBs, PRTBs, and Token bindings, just by running the relevant identification functions and examining the resulting work units.

**Comment by MKlimuszka** [comment]
\forwardport v2.8.2
