### ISSUE TITLE
[RFE] Add labels to CAPI kubeconfig secrets

### ISSUE THREAD

**Issue by richardcase** [rancher/rancher#42333]
**Is your feature request related to a problem? Please describe.**
CAPI v1.5.0 and higher requires that the secrets used for kubeconfigs have the label  `cluster.x-k8s.io/cluster-name=${CLUSTER_NAME}`. If we upgrade Rancher Provisioning (i.e. v2prov) to use CAPI 1.5.0 without these labels then provisioning will be broken with an failed to retrieve kubeconfig secret for Cluster error. 

See the CAPI migration guide: https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/book/src/developer/providers/migrations/v1.4-to-v1.5.md#other

**Describe the solution you'd like**
I'd like to see the label added to secrets early so that its not a problem if someone updates to use CAPI v1.5.0.

**Comment by slickwarren** [comment]
does this need a separate ticket for 2.9? I see the PR above for it, so I'm assuming we should track the work for it separately.

**Comment by snasovich** [comment]
Closing as this has essentially been absorbed into https://github.com/rancher/rancher/issues/43109 / https://github.com/rancher/rancher/issues/43945 and will be indirectly validated per these tickets.
