### ISSUE TITLE
Move PAYG into cattle-system NS

### ISSUE THREAD

**Issue by jeremy-moffitt** [rancher/rancher#42347]
**Rancher Server Setup**
- Rancher version: Q3-2023 (has not shipped yet)
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): any/irrelevant
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: any
- Cluster Type (Local/Downstream): local but applies only when running in a PAYG scenario in AKS/EKS/GKE

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
- Admin user

**Describe the bug**
The admin user for a PAYG deployment should be able to see the supportconfig generation screen and get billed properly for their usage in the public cloud. Due to an oversight in the initial implementation, the containers needed for the billing to work were slated to be deployed in a different namespace than the cattle-system namespace used for Rancher. Due to this, using an umbrella chart to deploy both Rancher and the csp-billing-adapter and usage-operator will fail to deploy successfully. The workaround is to deploy the billing-adapter and usage-operator in cattle-system, but that causes the check for whether supportconfig is enabled to fail because its checking in the namespace "cattle-csp-billing-adapter-system", so the supportconfig UI page won't be available and the metrics collection for billing won't occur.

**To Reproduce**
Since the functionality is incomplete, there isn't a trivial way to reproduce this. @guangyee has a helm chart that can be used to recreate the broken deployment if desired

**Result**
The umbrella chart fails to deploy all of the necessary containers.

**Expected Result**
Rancher and the csp-billing-adapter and the usage-operator should all be deployed successfully by the umbrella helm chart, and the Rancher dashboard should include the page to generate the support config when the admin user is logged in.

**Additional context**
fix in-flight at https://github.com/rancher/rancher/pull/42344

**Comment by jeremy-moffitt** [comment]
Ideally want to include this in https://github.com/rancher/rancher/milestone/313

**Comment by cbron** [comment]
Due to dates and design changes, I'm moving to q4. 
Also adding security-required label, this depends on design, if we go with above plan that should get reviewed. For other plans it may be unnecessary.

**Comment by jeremy-moffitt** [comment]
Per recent discussion, we're exploring other avenues to resolve the issue that triggered this bug/request... If we're able to work it out another way we'll close this. Not yet fully determined, but this approach is "on hold" for now.

**Comment by guangyee** [comment]
The deployer container approch is a viable solution. I think we can close this issue.
