### ISSUE TITLE
Missing SHA1SUMS files, invalid download

### ISSUE THREAD

**Issue by danvanwijk** [rancher/rancher#4235]
Rancher Version: 0.63.1 -> 1.0.0

Docker Version: 1.9.1 (on Rancher server)

OS: Ubuntu 14.04

I'm seeing this error in the Rancher Server logs after upgrading to 1.0.0. The database migration process might have been aborted if that can have anything to do with it?

```2016-03-30 21:14:33,518 ERROR [:] [] [] [] [ecutorService-1] [.p.c.v.i.ConfigItemStatusManagerImpl] Failed null, exit code [1] output [INFO: Updating hosts
INFO: Downloading https://xxx/v1//configcontent//hosts current=hosts-5268-46bf3f2cd5e10e348cea0a9b2c2f20e1ff10eda99e38ca8db85820b45973a1d8
basename: missing operand
Try 'basename --help' for more information.
ERROR: Missing SHA1SUMS files, invalid download
] ```

**Comment by alena1108** [comment]
@danvanwijk it might be related to aborting the db upgrade, and might be caused by some other known issue. To figure out that, could you run this db query against cattle db:

```
select id, name, state from service where id in (select consumed_service_id from service_consume_map where removed is null) and removed is not nul
```
If the output is non empty, then you are hitting this issue:

https://github.com/rancher/rancher/issues/4196

To recover from it, you would have to run this mysql update:

```
update service_consume_map set removed=now(), state='removed' where consumed_service_id in (select id from service where removed is not null) and removed is null;
```

**Comment by danvanwijk** [comment]
@deniseschannon As in the server container was accidentally stopped, presumably during the upgrade process.

@alena1108 Thanks. Got 1 row from running that query. Will try your fix later and report back. Is there anything else I need to be concerned about if the database upgrade process was aborted?

**Comment by frol** [comment]
Hmm, it is interesting. I have seen the same error struggling with #4161. I could not re-add a host which used to be in another Rancher Environment. In the end, I have solved the issue by putting my hands into the Rancher database and purging all hosts marked as removed (I had to resolve all foreign key constraints manually purging the records pointing to the hosts).

**Comment by alena1108** [comment]
@danvanwijk no, nothing else. The issue you were seeing, wasn't related to the db migration. It was happening because there is a bug when you can create a link pointing to a removed service, and one of the queries for config.update wasn't expecting this condition. We are fixing it in 1.0.1 by a) adding not-null check to the config.update query b) api validation disallowing linking to removed services.

**Comment by alena1108** [comment]
@frol your issue seems different given the fact you've fixed it by modifying "host" table

**Comment by danvanwijk** [comment]
Upgraded to v1.0.1 now with no issues.

**Comment by zhangyashen** [comment]
rc1.1.0
docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 279
Server Version: 1.10.3
Storage Driver: overlay
 Backing Filesystem: xfs
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.7.0
Operating System: Red Hat Enterprise Linux Server 7.2 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 55.05 GiB
Name: 31-brood-stg10-app-05
ID: 3VKK:WKBH:TTLM:Y5UP:CL3Y:6ZO2:VYLT:2EXJ:UNDX:7TAS:AGF5:A7LK
Labels:
 env=

OS: Centos6.5

ERROR as following:
[config.sh:126] tar xzf /var/lib/cattle/download.NXo7clo/download -C /var/lib/cattle/download.NXo7clo
[config.sh:135] rm /var/lib/cattle/download.NXo7clo/download
[[[config.sh:137] ls -1 /var/lib/cattle/download.NXo7clo
[[config.sh:137] basename ipsec-1-4b51c8e71d42d91125304a01ef945b6e164231315f0b504a2a7ef67443bd93f4
[config.sh:137] local dir=ipsec-1-4b51c8e71d42d91125304a01ef945b6e164231315f0b504a2a7ef67443bd93f4
[config.sh:138] '[' '!' -e /var/lib/cattle/download.NXo7clo/ipsec-1-4b51c8e71d42d91125304a01ef945b6e164231315f0b504a2a7ef67443bd93f4 ']'
[config.sh:145] cd /var/lib/cattle/download.NXo7clo
[config.sh:147] '[' '!' -e ipsec-1-4b51c8e71d42d91125304a01ef945b6e164231315f0b504a2a7ef67443bd93f4/SHA1SUMSSUM ']'
[config.sh:148] error 'Missing SHA1SUMS files, invalid download'
[scripts.sh:24] echo ERROR: 'Missing SHA1SUMS files, invalid download'
ERROR: Missing SHA1SUMS files, invalid download
[config.sh:149] exit 1
[config.sh:1] cleanup
[config.sh:9] EXIT=1
[config.sh:11] '[' -e /var/lib/cattle/download.NXo7clo ']'
[config.sh:12] rm -rf /var/lib/cattle/download.NXo7clo
[config.sh:15] return 1
The system is going down NOW!
Sent SIGTERM to all processes
Sent SIGKILL to all processes
Requesting system reboot

@danvanwijk  Please help!

**Comment by danvanwijk** [comment]
@zhangyashen as far as I can recall @alena1108 comment solved it for me: https://github.com/rancher/rancher/issues/4235#issuecomment-203662864

Don't really remember much more details regarding it, sorry.
