### ISSUE TITLE
Update CAPI Chart to v1.5.0

### ISSUE THREAD

**Issue by rayandas** [rancher/rancher#42357]
It’s part of the main issue: [[Feature] K8s 1.27 Support](https://github.com/rancher/rancher/issues/41840)

**Comment by Oats87** [comment]
I’m not sure we should be shipping the .0 release in our next patch release. I would prefer we let the minor soak for a bit before jumping to it.

@jakefhyde  @richardcase @furkatgofurov7 any thoughts on this?

**Comment by furkatgofurov7** [comment]
> I’m not sure we should be shipping the .0 release in our next patch release. 

Agree with this, from the release best practices perspective, we could avoid bumping CAPI to minor version in patch release.

**Comment by richardcase** [comment]
Agree with you @Oats87 & @furkatgofurov7 we should wait for a non x.x.1 release as a generally principle (unless there is something we really need)

We'd also need #42406 (or #42402 for v2.7) to merge when doing this, otherwise we'd get failures from when CAPI looks up the kubeconfig.

**Comment by rayandas** [comment]
Closing this issue as per above comments.
