### ISSUE TITLE
[2.7] Bump norman to next

### ISSUE THREAD

**Issue by cmurphy** [rancher/rancher#42369]
Norman has no tags, bump to latest commit hash on release/v2.7 branch.

**Comment by cmurphy** [comment]
https://github.com/rancher/norman/pull/447

**Comment by JonCrowther** [comment]
Here is the v2.7 branch: https://github.com/rancher/norman/tree/release/v2.7

**Comment by tomleb** [comment]
Seems like rancher 2.7 is using an older version of norman from april instead of august:
https://github.com/rancher/rancher/blob/6e7f8c436988e5a45d880528255d68c29b4583d4/go.mod#L118

The latest norman v2.7 commit starts with `078862e5648c`.
