### ISSUE TITLE
Cannot view graphs after upgrading to v1.0.0

### ISSUE THREAD

**Issue by nlhkh** [rancher/rancher#4236]
After I upgraded Rancher to v1.0.0, I can no longer see the graphs of my stacks. Before upgrading from v0.63.1, I was able to view the graphs just fine.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.0.0` Cattle: `v0.159.2` UI: `v0.100.3` |
|Access|`github` `admin`|
|Route|`environment.graph`|

**Comment by vincent99** [comment]
There appears to be an issue with the graph in Firefox

**Comment by nlhkh** [comment]
I am using Safari actually.

**Comment by vincent99** [comment]
Ok, or != Chrome.

**Comment by nlhkh** [comment]
Ahhh, so you are saying that Chrome will show the graph normally? I will check it out with Chrome later today. What could possibly be the issue?

Thanks
Kha

**Comment by vincent99** [comment]
That's what I saw this morning when we were getting ready for a demo for our meetup.  Will get it fixed for next release.

**Comment by nlhkh** [comment]
Awesome! :)

**Comment by tfiduccia** [comment]
Version - master 4/1
Verified fixed
