### ISSUE TITLE
[2.7] Bump apiserver to next

### ISSUE THREAD

**Issue by cmurphy** [rancher/rancher#42365]
No tags for apiserver, just get the latest commit hash.  Bump in steve and rancher.

**Comment by cmurphy** [comment]
https://github.com/rancher/apiserver/pull/29

**Comment by cmurphy** [comment]
https://github.com/rancher/apiserver/pull/29

**Comment by tomleb** [comment]
Seems like it has been bumped in steve but not in rancher.
https://github.com/rancher/rancher/blob/6e7f8c436988e5a45d880528255d68c29b4583d4/go.mod#L109.
Latest should be `v0.0.0-20230810214006-d134152ce6fb`
