### ISSUE TITLE
Memory stats not working

### ISSUE THREAD

**Issue by JaviSabalete** [rancher/rancher#4241]
Rancher Version:
v1.0.0
Docker Version:
1.10.2
OS: 
Debian Jessie 8.3, Dedicated Server OVH
Steps to Reproduce: 
Just install it. All works fine excepts memory stats.
![stats](https://cloud.githubusercontent.com/assets/8037941/14168939/4c2b2c94-f725-11e5-9b65-aadddcbe1d0c.png)

**Comment by deniseschannon** [comment]
This is interesting because the stats usually come all together.

Can you provide rancher/agent logs?

http://docs.rancher.com/rancher/faqs/agents/#where-can-i-find-detailed-logs-of-the-rancher-agent-container

**Comment by JaviSabalete** [comment]
Ye, np

Several problems with agent.log

2016-04-05 08:00:08,309 INFO requests.packages.urllib3.connectionpool [139851952720944] [connectionpool.py:207] Starting new HTTP connection (1216): MYHOSTNAME 
2016-04-05 08:00:23,314 ERROR agent [139851952720944] [event.py:112] Error in request : cecf0f3e-f32b-4636-9eb9-417c2940a556 
Traceback (most recent call last):
  File "/var/lib/cattle/pyagent/cattle/agent/event.py", line 97, in _worker_main
    publisher.publish(resp)
  File "/var/lib/cattle/pyagent/cattle/plugins/core/publisher.py", line 24, in publish
    timeout=60)
  File "/var/lib/cattle/pyagent/dist/requests/sessions.py", line 511, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/var/lib/cattle/pyagent/dist/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/var/lib/cattle/pyagent/dist/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/var/lib/cattle/pyagent/dist/requests/adapters.py", line 426, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', BadStatusLine("''",))

I don't know if this errors cause memory stats problems.

Ty

**Comment by jifeon** [comment]
I've the same error, any news here?

**Comment by cjellick** [comment]
@JaviSabalete can you grab a bigger swath of rancher-agent logs? That stack trace isn't directly related to memory stats not showing.

**Comment by JaviSabalete** [comment]
Of course 😄 
[rancher-agent.txt](https://github.com/rancher/rancher/files/228800/rancher-agent.txt)

**Comment by deniseschannon** [comment]
@JaviSabalete Are you still facing this issue?

**Comment by JaviSabalete** [comment]
Yes, always with Debian. Ubuntu works fine

**Comment by JaviSabalete** [comment]
@deniseschannon could you reopen? isn't fixed yet

**Comment by deniseschannon** [comment]
@JaviSabalete What version are you on? Could you upgrade to the latest stable version (1.1.4) to see if you still face this issue?

**Comment by tfiduccia** [comment]
Version 1.2.0-pre3
Add AWS Debian 8 Jessie machine, and the memory stats are now pulling.  Changing to bug.

**Comment by tfiduccia** [comment]
@JaviSabalete - Hey, after asking around the dev group, I found out this is actually a docker issue and it's already entered over there.  Here is a reference to the bug - https://github.com/docker/docker/issues/396

There is a work-around and I'm on version 1.2.0-pre3 and tried it out and it worked for me.  Here are the steps:

1.  ssh into your rancher server
2.  add cgroup_enable=memory swapaccount=1 to whatever is currently in the GRUB_CMDLINE_LINUX_DEFAULT var in /etc/default/grub
3.  sudo update-grub **make it ready to use
4.  reboot **restart the instance

I'm going to close this in favor of the docker issue.
