### ISSUE TITLE
[BUG] Secrets encryption broken for latest rke2 release

### ISSUE THREAD

**Issue by rancher-max** [rancher/rancher#42425]
**Rancher Server Setup**
- Rancher version: All v2.7 and v2.6
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): both
- Proxy/Cert Details: N/A

**Information about the Cluster**
- Kubernetes version:
```
v1.26.6+rke2r1 
v1.26.7+rke2r1
v1.25.11+rke2r1 
v1.25.12+rke2r1 
v1.24.15+rke2r1 
v1.24.16+rke2r1 
```
- Cluster Type (Local/Downstream): downstream -- custom or v2prov
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
N/A

**Describe the bug**

`featureVersions` arg is missing from KDM for these releases, so secrets encryption is broken.

**To Reproduce**

1. Deploy a cluster 
2. Attempt to reencrypt the secrets using rancher

**Result**
Cannot reencrypt secrets

**Expected Result**

Should be able to reencrypt secrets

**Screenshots**

**Additional context**

**Comment by igomez06** [comment]
QA validation:

Rancher Server Setup

Rancher version: v2.7.6-rc2 HA
Downstream cluster: 3 node RKE2 v1.26.7+rke2r1 encrypt secret enabled

v2prov/encryption_key_rotation_test.go

Test `encryption-key-rotation-new-cluster`
Status: PASS

Test `encryption-key-rotation-stress-test`
1,000 secrets
Status: PASS
