### ISSUE TITLE
Networking Field does not take input

### ISSUE THREAD

**Issue by zrml** [rancher/rancher#4244]
While specifying a Docker container the field _Hostname_ in the _Networking_ tab allows focus
but does not allow me to type anything.

Rancher v1

thank you guys

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.0.0` Cattle: `v0.159.2` UI: `v0.100.3` |
|Access|`Disabled`|
|Route|`containers.new`|

**Comment by deniseschannon** [comment]
Verified this is occuring on the "Add Container" page. Notice that this is not the "Add Service" page.

**Comment by deniseschannon** [comment]
@zrml You could use "Add service", which is what we recommend as this will allow you to take advantage of Rancher's benefits (health checks, scheduling, load balancing, etc etc). You can keep the scale of 1 if you only want 1 container.

**Comment by zrml** [comment]
@deniseschannon Thank you for the suggestion. I'm investigation Rancher and actually I would not be using the Web-UI much as we all need much automation :) but I just though I report the bug if it is such.
thanks
take care

**Comment by tfiduccia** [comment]
Version - master 4/1
Verified fixed

**Comment by zrml** [comment]
thank you all! Great Effort!
