### ISSUE TITLE
Deprecate rancher-k3s-upgrader

### ISSUE THREAD

**Issue by rohitsakala** [rancher/rancher#42448]
As part of deprecating catalog v1, we need to deprecate system charts and thus rancher-k3s-upgrader chart inside it https://github.com/rancher/system-charts/tree/dev-v2.7/charts/rancher-k3s-upgrader

**Comment by jiaqiluo** [comment]
The backend PR has been merged, and the changes are now available in the latest `docker.io/rancher/rancher:head` image. This should no longer be a blocker for the UI.

**Comment by Josh-Diamond** [comment]
Ticket #42448 - Test Results - ✅ 
---

Verified on Rancher `v2.10-ae6ac83471545ab47d052d2d760daa2e6646a969-head`:

| Scenario | Test Case | Result |
|---|---|---|
| 1. | On Rancher `v2.10-head`, import a new downstream k3s cluster => upgrade k8s version => confirm new app is installed and upgrade is successful | ✅ |
| 2. | On Rancher `v2.10-head`, import a new downstream rke2 cluster => upgrade k8s version => confirm new app is installed and upgrade is successful | ✅ |
| 3. | On Rancher `v2.9.2`, import a new downstream k3s cluster => upgrade k8s version => upgrade Rancher server version => confirm old app is removed, new app is installed, and upgrade is successful | ✅ |
| 4. | On Rancher `v2.9.2`, import a new downstream rke2 cluster => upgrade k8s version => upgrade Rancher server version => confirm old app is removed, new app is installed, and upgrade is successful | ✅ |
| 5. | Using env from Scenario 3, rollback to Rancher `v2.9.2` => upgrade k3s cluster k8s version => confirm upgrade succeeds | ✅ |
| 6. | Using env from Scenario 4, rollback to Rancher `v2.9.2` => upgrade rke2 cluster k8s version => confirm upgrade succeeds | ✅ |

---

Scenario 1 - ✅ 
1. Fresh install of Rancher `v2.10-head`
2. Create a standalone k3s cluster w/ k8s `v1.29.9+k3s1`
3. Import the standalone cluster into Rancher
4. Upgrade k8s version to `v1.30.5+k3s1`
5. Verified - cluster successfully upgrades
6. Verified - `Cluster explorer > Cluster > Deployments > system-upgrade-controller` accurately reflects new app label: `app.kubernetes.io/managed-by: Helm`; as expected

---

Scenario  2 - ✅ 
1. Fresh install of Rancher `v2.10-head`
2. Create a standalone k3s cluster w/ k8s `v1.29.9+rke2r1`
3. Import the standalone cluster into Rancher
4. Upgrade k8s version to `v1.30.5+rke2r1`
5. Verified - cluster successfully upgrades
6. Verified - `Cluster explorer > Cluster > Deployments > system-upgrade-controller` accurately reflects new app label: `app.kubernetes.io/managed-by: Helm`; as expected

---

Scenario 3 - ✅ 
1. Fresh install of Rancher `v2.9.2`
2. Create a standalone k3s cluster w/ k8s `v1.29.8+k3s1`
3. Import the standalone cluster into Rancher
4. Upgrade k8s version to `v1.30.4+k3s1`
5. Verified - old app in use; upgrade successful
6. Upgrade Rancher to `v2.10-head`
7. Verified - Rancher successfully upgrades to `v2.10-head`
8. Upgrade k8s version to `v1.30.5+k3s1`
9. Verified - upgrade successful + new app in use; as expected

---

Scenario 4 - ✅ 
1. Fresh install of Rancher `v2.9.2`
2. Create a standalone k3s cluster w/ k8s `v1.29.8+rke2r1`
3. Import the standalone cluster into Rancher
4. Upgrade k8s version to `v1.30.4+rke2r1`
5. Verified - old app in use; upgrade successful
6. Upgrade Rancher to `v2.10-head`
7. Verified - Rancher successfully upgrades to `v2.10-head`
8. Upgrade k8s version to `v1.30.5+rke2r1`
9. Verified - upgrade successful + new app in use; as expected

---

Scenario 5 - ✅ 
1. Fresh install of Rancher `v2.9.2`
2. Create a standalone k3s cluster, then import it into rancher
3. Once imported, upgrade k8s version
4. Verified - old app in use; upgrade successful
5. Upgrade Rancher to `v2.10-head`
6. Verified - Rancher successfully upgrades
7. Upgrade k8s version + confirm new app is in use and functional
8. Verified - upgrade succeeds and new app is in use
9. Rollback Rancher to `v2.9.2`
10. Verified - Rancher successful rollsback to `v2.9.2`
11. Upgrade k8s version
12. Verified - cluster successfully upgrades post-rollback; as expected

---

Scenario 6 - ✅ 
1. Fresh install of Rancher `v2.9.2`
2. Create a standalone rke2 cluster, then import it into rancher
3. Once imported, upgrade k8s version
4. Verified - old app in use; upgrade successful
5. Upgrade Rancher to `v2.10-head`
6. Verified - Rancher successfully upgrades
7. Upgrade k8s version + confirm new app is in use and functional
8. Verified - upgrade succeeds and new app is in use
9. Rollback Rancher to `v2.9.2`
10. Verified - Rancher successful rollsback to `v2.9.2`
11. Upgrade k8s version
12. Verified - cluster successfully upgrades post-rollback; as expected

**Comment by snasovich** [comment]
Reopening as this will need to be retested once https://github.com/rancher/rancher/pull/47894 is merged.

**Comment by jiaqiluo** [comment]
this issue can be validated on the latest head image

**Comment by Josh-Diamond** [comment]
Ticket #42448 - Test Results - ✅ 
---

Verified on Rancher `v2.10-5e218e3790238a5e6fe8cc07e9c3adeb7dd5dccf-head`:

| Scenario | Test Case | Result |
|---|---|---|
| 1. | On Rancher `v2.10-head`, import a new downstream k3s cluster => upgrade k8s version => confirm new app is installed and upgrade is successful | ✅ |
| 2. | On Rancher `v2.10-head`, import a new downstream rke2 cluster => upgrade k8s version => confirm new app is installed and upgrade is successful | ✅ |
| 3. | On Rancher `v2.9.3`, import a new downstream k3s cluster => upgrade k8s version => upgrade Rancher server version => confirm old app is removed, new app is installed, and upgrade is successful | ✅ |
| 4. | On Rancher `v2.9.3`, import a new downstream rke2 cluster => upgrade k8s version => upgrade Rancher server version => confirm old app is removed, new app is installed, and upgrade is successful | ✅ |
| 5. | Using env from Scenario 3, rollback to Rancher `v2.9.3` => upgrade k3s cluster k8s version => confirm upgrade succeeds | ✅ |
| 6. | Using env from Scenario 4, rollback to Rancher `v2.9.3` => upgrade rke2 cluster k8s version => confirm upgrade succeeds | ✅ |

---

Scenario 1 - ✅ 
1. Fresh install of Rancher `v2.10-head`
2. Create a standalone k3s cluster w/ k8s `v1.30.6+k3s1`
3. Import the standalone cluster into Rancher
4. Upgrade k8s version to `v1.31.2+k3s1`
5. Verified - cluster successfully upgrades
6. Verified - `Cluster explorer > Cluster > Deployments > system-upgrade-controller` accurately reflects new app label: `app.kubernetes.io/managed-by: Helm`; as expected

---

Scenario  2 - ✅ 
1. Fresh install of Rancher `v2.10-head`
2. Create a standalone k3s cluster w/ k8s `v1.30.6+rke2r1`
3. Import the standalone cluster into Rancher
4. Upgrade k8s version to `v1.31.2+rke2r1`
5. Verified - cluster successfully upgrades
6. Verified - `Cluster explorer > Cluster > Deployments > system-upgrade-controller` accurately reflects new app label: `app.kubernetes.io/managed-by: Helm`; as expected

---

Scenario 3 - ✅ 
1. Fresh install of Rancher `v2.9.3`
2. Create a standalone k3s cluster w/ k8s `v1.29.9+k3s1`
3. Import the standalone cluster into Rancher
4. Upgrade k8s version to `v1.30.5+k3s1`
5. Verified - old app in use; upgrade successful
6. Upgrade Rancher to `v2.10-head`
7. Verified - Rancher successfully upgrades to `v2.10-head`
8. Upgrade k8s version to `v1.31.2+k3s1`
9. Verified - upgrade successful + new app in use; as expected

---

Scenario 4 - ✅ 
1. Fresh install of Rancher `v2.9.3`
2. Create a standalone k3s cluster w/ k8s `v1.29.9+rke2r1`
3. Import the standalone cluster into Rancher
4. Upgrade k8s version to `v1.30.5+rke2r1`
5. Verified - old app in use; upgrade successful
6. Upgrade Rancher to `v2.10-head`
7. Verified - Rancher successfully upgrades to `v2.10-head`
8. Upgrade k8s version to `v1.31.2+rke2r1`
9. Verified - upgrade successful + new app in use; as expected

---

Scenario 5 - ✅ 
1. Fresh install of Rancher `v2.9.3`
2. Create a standalone k3s cluster, then import it into rancher
3. Once imported, upgrade k8s version
4. Verified - old app in use; upgrade successful
5. Upgrade Rancher to `v2.10-head`
6. Verified - Rancher successfully upgrades
7. Upgrade k8s version + confirm new app is in use and functional
8. Verified - upgrade succeeds and new app is in use
9. Rollback Rancher to `v2.9.3`
10. Verified - Rancher successful rolls back to `v2.9.3`
11. Upgrade k8s version
12. Verified - cluster successfully upgrades post-rollback; as expected

---

Scenario 6 - ✅ 
1. Fresh install of Rancher `v2.9.3`
2. Create a standalone rke2 cluster, then import it into rancher
3. Once imported, upgrade k8s version
4. Verified - old app in use; upgrade successful
5. Upgrade Rancher to `v2.10-head`
6. Verified - Rancher successfully upgrades
7. Upgrade k8s version + confirm new app is in use and functional
8. Verified - upgrade succeeds and new app is in use
9. Rollback Rancher to `v2.9.3`
10. Verified - Rancher successful rolls back to `v2.9.3`
11. Upgrade k8s version
12. Verified - cluster successfully upgrades post-rollback; as expected

**Comment by jiaqiluo** [comment]
**What are changed**

Rancher deploys the System Upgrade Controller (SUC) to facilitate Kubernetes upgrades for imported RKE2/K3s clusters. Previously, this app was installed in the target cluster when a Kubernetes version upgrade was triggered; however, it was deployed as a legacy v1 app, making it invisible in the Dashboard UI. Starting with this Rancher version, the deployment mechanism for this component has transitioned from legacy v1 apps to fully supported v2 apps, with a seamless migration during the Rancher upgrade process. Once Rancher is upgraded to this version, it will automatically uninstall the legacy v1 app from all imported RKE2/K3s clusters, if present. When the new version of the rancher-cluster-agent starts in the downstream cluster, it will install SUC as a managed v2 app, which is now visible on the Installed Apps page in the Dashboard UI. 

Additionally, a new feature flag, `managed-system-upgrade-controller` (enabled by default), is available to allow disabling the migration if preferred. Additionally, a new setting, `k3s-based-upgrader-uninstall-concurrency` (default: 5), is available to control the cadence of uninstalling this app in downstream imported RKE2/K3s clusters.
