### ISSUE TITLE
[2.8] Forward port August patches to 2.8

### ISSUE THREAD

**Issue by mitulshah-suse** [rancher/rancher#42453]
Forward port august patches to 2.8 branches for the Q4 release.
KDM : `dev-v2.8`
RKE: `release/1.5`

**Comment by HarrisonWAffel** [comment]
I've updated the description to reflect that the RKE branch for 2.8 is `1.5`, not `1.8`

**Comment by HarrisonWAffel** [comment]
This has been completed
