### ISSUE TITLE
Stuck on "waiting for agent connection" while creating a Digital Ocean Host

### ISSUE THREAD

**Issue by aieeeeeeeee** [rancher/rancher#4246]
Rancher Version:v1.0.0

Steps to Reproduce: Create a host on Digital Ocean via the "Add Host" button in the Infrastructure tab

Results: Waiting for agent connection

Expected: Active host

I'm trying to add a new Digital Ocean host in a Cattle environment as well as in a Swarm Environment but in both environments it gets stuck on "Waiting for agent connection". On Digital Ocean I can see the two droplets (one for each environment).

**Comment by deniseschannon** [comment]
Where is your Rancher server hosted/located?

**Comment by aieeeeeeeee** [comment]
@deniseschannon Rancher is running on a VM (Debian 8 - with the latest version of Docker) on an on-premise Hyper-V environment that my company put at our disposal for testing purposes.

**Comment by deniseschannon** [comment]
Do you have some kind of firewall or proxy for internet access? 

http://docs.rancher.com/rancher/installing-rancher/installing-server/#launching-rancher-server-behind-a-http-proxy

**Comment by aieeeeeeeee** [comment]
Not any firewall nor proxy on my road ;-)

**Comment by deniseschannon** [comment]
The VM that you have set up where Rancher server is running. Is the host routable from the internet?

**Comment by aieeeeeeeee** [comment]
I don't think so. 
Do you think I could find some (verbose) logs somewhere?

**Comment by deniseschannon** [comment]
There are no logs specific for this use case, but your Rancher server needs to be routable from the internet. After the DO droplet is created, we automatically launch a rancher/agent container onto the host, in this case, the rancher/agent container on the DO host is trying to communicate back to the rancher/server container via the internet and is getting stuck as the VM that you have rancher server on is not routable. 

How did you add your hosts/where are your hosts located in your swarm environment that you have had questions about?

**Comment by aieeeeeeeee** [comment]
Sorry, I've double checked and it seems that all our VMs are routable from internet... 

I'm not trying to add a DO droplets in my swarm cluster, I'm trying so in my Cattle env.

**Comment by deniseschannon** [comment]
Sorry to confuse the issues, but I was curious on how you got your other `active` hosts in your swarm cluster. Did you run a custom command on a VM that was already up and running?

Adding a DO droplet to the swarm cluster would be the same in your Cattle env. (Unless you're telling me that it works in 1 and not the other, which would be surprising to me).

**Comment by aieeeeeeeee** [comment]
Ahh ok, no problem. I've added the other hosts with the command provided by
Rancher while adding a host so yes on an existing VM already up and running.

Indeed adding a DO droplet in the swarm cluster doesn't provide better
results... therefore no surprise there ;-)

**Comment by deniseschannon** [comment]
Okay, it sounds like the hosts in DO cannot communicate back to your VM that is running Rancher server. 

1. What is the IP of your Rancher server? 
2. Can you do a test? Manually create a DO droplet and log into it. Try this command from inside the DO droplet. 

```
#This is my example Rancher server IP, please replace with your Rancher server IP
curl -i 104.197.228.X:8080/v1
```

**Comment by aieeeeeeeee** [comment]
Rancher server IP is in my private range thus not reachable from that droplet. Is this what you meant that routed from internet ? How the agent communicates with the server (ssh like or via a public IP only)?

**Comment by deniseschannon** [comment]
Yes, that is exactly what I was meaning. 

Rancher agent communicates with the server through the internet. Without that access, these agents will not be able to be added to Rancher server.

**Comment by aieeeeeeeee** [comment]
Ok thanks, sorry for the confusion then I will setup my reverse proxy to
make rancher routable FROM internet and then I'll close this issue if it
was indeed the cause.

Thanks again for your help!

**Comment by aieeeeeeeee** [comment]
Ok ranche is now accessible via a public url and I'm able to get an unauthorized message (since I need to login I guess) using your curl command but I'm still facing a "waiting for agent connection"...

**Comment by cjellick** [comment]
If you setup a reverse proxy in front rancher to make it accessible, you probably have a new IP or domain for it, right? If so, you'd need to update the Host Registration URL under Admin > Settings and then go to the add host page, verify the docker run command has the new IP address, and then run that on the DO hosts.

If you created the DO hosts via our UI, it might be easier to just delete them and create new ones.

Also, that rancher-server requires certain headers be set properly in the reverse proxy and the reverse proxy _must_ support websockets, as much of the communication from agent to server is done via a websocket connection. An example nginx and apache config for a reverse proxy for rancher can be found here: http://docs.rancher.com/rancher/installing-rancher/installing-server/basic-ssl-config/#notes-on-the-settings
