### ISSUE TITLE
[BUG] Post upgrade, AD user cluster owner cannot list anything on the cluster 

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#42466]
**Rancher Server Setup**
- Rancher version:  `v2.7.4` upgraded to `v2.7.5` upgraded to v2.7.6-head `2cf6683 `
- Installation option (Docker install/Helm Chart): `Docker install`
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: `v1.26.7+k3s1`
- Cluster Type (Local/Downstream): Downstream Infrastructure provider k3s 
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: AD Standard user Cluster owner
   
**Describe the bug**
Post upgrade from v2.7.4 to v2.7.5 to v2.7.6-head, AD user cluster owner, cannot list any resources on the downstream cluster. 
As a workaround if we create a project, all the resources load.

**To Reproduce**
1. On rancher v2.7.4, enable active directory
2. Create a downstream node driver k3s cluster 1 node all roles
3. Add a nesteduser1, a non nested user from the AD server as cluster owner and cluster member respectively.
5. Upgrade to rancher v2.7.5
6. Re login as the nested user and a few other users.
7. Upgrade rancher to v2.7.6-head
8. Login as the clusterowner user - nesteduser1

**Result**
Cluster owner cannot list any resources on the UI.

**Expected Result**
Expected the cluster owner to be able to load resources.

**Additional context**

![Screenshot1](https://github.com/rancher/rancher/assets/38144301/0f71c680-edc7-42e2-896e-2ccdef2bd15b)

This is not seen happening on an upgrade from v2.7.3 to v2.7.4 with auth users
Also not observed on an upgrade from v2.7.3 to v2.7.4 to v2.7.5 to v2.7.6-head with auth users
Also not see on an upgrade from v2.7.5 to v2.7.6-head with local user added as a cluster owner.

**Comment by MKlimuszka** [comment]
1.
"Also not observed on an upgrade from v2.7.3 to v2.7.4 to v2.7.5 to v2.7.6-head with auth users"
@anupama2501  Is the only difference between this and the steps in the ticket, starting with 2.7.3?

2.
We'd love to see the cluster role bindings for each of the users before and after each upgrade. 

3.
Maybe the role bindings haven't synced to the downstream clusters yet. If you go back after, do the resources appear? Maybe we just need to add a sleep to the end of the migration.

**Comment by anupama2501** [comment]
@MKlimuszka I have provided the setup where the issue is reproduced to @crobby and @nflynt along with the CRTBs for both before and after upgrade.

**Comment by prachidamle** [comment]
Moving this issue to-test as PR is merged.

**Comment by anupama2501** [comment]
Upgrade checks:
1. Have the issue reproduced setup in v2.7.6-head
   - Updated the rancher image, to be v2.7.6-head `53ebd8c`
   - Verified once the rancher server is active, cluster owners can create projects, namespaces and workloads.
2. Verified upgrade from v2.7.4 >> v2.7.5 >> v2.7.6-head `53ebd8c` with nested users added as CO
   - On rancher v2.7.4, enable active directory
   - Create a downstream node driver k3s cluster 1 node all roles
   - Add a nesteduser1, a non nested user from the AD server as cluster owner and cluster member respectively.
   - Upgrade to rancher v2.7.5
   - Re login as the nested user and a few other users.
   - Upgrade rancher to v2.7.6-head
   - Login as the clusterowner user - nesteduser1
   - Verified nesteduser1 as cluster owners can create projects, namespaces and workloads.
3.  Verified upgrade from v2.7.5 >> v2.7.6-head `53ebd8c` with groups added as CO
    - Added a group as a cluster owner
    - Logged in as a nesteduser from the group
    - Upgarded rancher to v2.7.6-head
    - Logged in as the cluster owner user from the group
    - Verified users can login without errors
4. Verified upgrade from v2.7.4 >> v2.7.5 >> v2.7.6-head `53ebd8c`  with groups added as CO
5. Verified upgrade from v2.7.4 >> v2.7.5 >> v2.7.6-head `53ebd8c`  with non nested users added as CO
6. Verified upgrade from v2.7.5 >> v2.7.6-head `53ebd8c`  with non nested users added as CO
