### ISSUE TITLE
[2.8] Deprecate Restricted Admin 

### ISSUE THREAD

**Issue by MbolotSuse** [rancher/rancher#42462]
With the introduction of the new fields in the GlobalRoles v2 work (such as #42213), it is no longer necessary to include the Restricted Admin as a built-in role. Because of this, Restricted admin should be deprecated in the upcoming 2.8 release (though not fully removed until much later).

**Comment by lindhe** [comment]
I think that the docs should be updated too. Is that tracked in any issue right now?

[Currently, they say](https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/manage-role-based-access-control-rbac/global-permissions#changing-global-administrators-to-restricted-admins):

> If Rancher already has a global administrator, they should change all global administrators over to the new `restricted-admin` role.

Also, I find no mention of the deprecation [here](https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/manage-role-based-access-control-rbac/global-permissions#restricted-admin).
