### ISSUE TITLE
[BUG] AD Migration - Users deleted from AD before migration not caught

### ISSUE THREAD

**Issue by nickwsuse** [rancher/rancher#42464]
**Rancher Server Setup**
- Rancher version: `v2.7.4 -> v2.7.6`
- Installation option (Docker install/Helm Chart): `Docker`
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): `k3s local, rke2 downstream`

**Information about the Cluster**
- Kubernetes version: `v1.26.4+k3s1`

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): Admin

**Describe the bug**
After adding AD users with CRTBs and PRTBs to a downstream cluster in 2.7.4, if some of those users are deleted from AD and then Rancher is upgraded to 2.7.6-head the users aren't caught and still appear in Rancher under Users & Authentication as well as appearing broken on the Cluster and Project member section of the downstream cluster.

**To Reproduce**
1. Deploy 2.7.4 
2. Deploy RKE2 downstream cluster 
3. Enable AD auth
4. In the downstream cluster, add nested AD users to cluster and project roles
5. Delete two of the users from AD (one CRTB and one PRTB)
6. Upgrade to 2.7.6 
7. Check the ad-guid-migration configmap

**Result**
Status of `Finished` and no users listed to be removed

**Expected Result**
`FinishedWithMissing` status and users listed to be removed

**Screenshots**
![image](https://github.com/rancher/rancher/assets/107147272/31ca371e-8601-436b-8749-cde3e62437de)
![image](https://github.com/rancher/rancher/assets/107147272/151bb7ff-cc15-408d-ad87-13ae6954be9c)
![image](https://github.com/rancher/rancher/assets/107147272/546fe49b-c472-413c-8077-5bc0fa03958e)

**Comment by nickwsuse** [comment]
Talked with @crobby offline about this and turns out this is expected. Going from 2.7.4 to 2.7.6 means there were no GUID users, therefore no dupes and no resources to un-migrate. Because of that the migration logic doesn't really do anything in this case, so the status should indeed be `Finished`. Still a gross UX imo, but not an issue for AD migration.

**Comment by nickwsuse** [comment]
reopening as we can use this for later

**Comment by MKlimuszka** [comment]
This is not a scenario for the unmigration. It's a generic missing users case, so I am moving the milestone.

**Comment by MKlimuszka** [comment]
Closing because it'll be covered in another ticket.
