### ISSUE TITLE
Stuck on "activating" while deploying an item from the catalog on a swarm environment

### ISSUE THREAD

**Issue by aieeeeeeeee** [rancher/rancher#4247]
Rancher Version: v1.0.0

Steps to Reproduce: Create a ghost blog or a wordpress from the catalog

Results: stuck on "activating" in the project tab of a swarm environment

Expected: a working ghost blog and a working wordpress stack

**Comment by deniseschannon** [comment]
Did you get a host working in your environment as I see you filed #4246

**Comment by aieeeeeeeee** [comment]
Yes I have 2 hosts running on local servers on which I'm able to run containers but not deploying an item from the catalog.

**Comment by LLParse** [comment]
Hi @aieeeeeeeee, I am unable to reproduce without more information.

Under `INFRASTRUCTURE > HOSTS`, are any hosts listed as `ACTIVE`? Assuming there are, you should see a Swarm stack with at least one swarm agent, and it should be running. If these requirements are satisfied, you should have a healthy swarm environment.

Next, when you deploy the project and it enters the "activating" state, are any containers actually launched? If you could post the swarm agent log and any other details, it would be helpful.

**Comment by aieeeeeeeee** [comment]
Hi @LLParse.

Yes I have 2 hosts that are Active and the following containers are running (on top of any "dummy" container that I have created to check that deploying a container was ok):

Host 1:
- swarm_swarm_1
- Network agent

Host 2:
- Swarm_swarm-agent_1
- Network agent

While in the activating state no container has been launched.
Here is the only logging information that I have while running a docker logs on the agent container:

> time="2016-04-02T02:11:01Z" level=info msg="Listening for health checks on 0.0.0.0:10240/healthcheck"
> time="2016-04-02T02:11:01Z" level=info msg="Initializing event router" workerCount=50
> time="2016-04-02T02:11:02Z" level=info msg="Connection established"

For the any other details, except telling you that the hosts are VMs running on an Hyper-V environment local to my company and on-premise, that these VMs are running Debian 8 with the latest Docker version (see quote below), I'm running out of info that I could share to help you:

> Client:
>  Version:      1.10.3
>  API version:  1.22
>  Go version:   go1.5.3
>  Git commit:   20f81dd
>  Built:        Thu Mar 10 15:38:58 2016
>  OS/Arch:      linux/amd64
> 
> Server:
>  Version:      1.10.3
>  API version:  1.22
>  Go version:   go1.5.3
>  Git commit:   20f81dd
>  Built:        Thu Mar 10 15:38:58 2016
>  OS/Arch:      linux/amd64

Thanks for your support !

**Comment by deniseschannon** [comment]
Do your hosts have cross host communication actually working? Have you opened up UDP ports 500 and 4500? If you exec into the network agent on one host, can you ping the IP of the other network agent (10.42.x.x)? 

http://docs.rancher.com/rancher/faqs/#cross-host-communication

**Comment by deniseschannon** [comment]
@aieeeeeeeee If you could confirm if your cross host communication is working in your setup and are still having issues, please re-open.

**Comment by aieeeeeeeee** [comment]
@deniseschannon Yep I confirm that the issue can be closed since everything now behaves as expected! Thanks again for your support!
