### ISSUE TITLE
[BUG] AD Migration | Connection to LDAP lost during un-migration and users skipped and given empty DNs | cannot login

### ISSUE THREAD

**Issue by nickwsuse** [rancher/rancher#42478]
**Rancher Server Setup**
- Rancher version: `v2.7.4 -> v2.7.5 -> v2.7.6-head`
- Installation option (Docker install/Helm Chart): `Docker`

**Information about the Cluster**
- Kubernetes version: `v1.26.4+k3s1`

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): Admin
 
**Describe the bug**
For users that were on v2.7.4 and run into the AD auth issues on 2.7.5 (duplicate users and lost permissions), if the connection to the AD server is lost during the migration, some users appear to be skipped and their DNs are empty, while some users are successfully un-migrated. The users that were successfully un-migrated can login and everything looks dandy, but users that were skipped cannot login.

I checked the debug logs for this at two separate times 
1. Within 1min of the docker container starting with the upgrade and it showed the LDAP connection errors
2. After the upgrade was complete and Rancher was available and it looked like the migration script was able to connect and migrate users

Error from the first log: `WARNING] [migrate-ad-user] LDAP connection failed: 'Error creating connection: LDAP Result Code 200 "Network Error": dial tcp <AD_SERVER_IP>: i/o timeout', retrying...`

I also noticed this line from the log: `[DEBUG] [identify-ad-users] user <redacted> is GUID-based (<redacted>) and the Active Directory server knows it by the Distinguished Name ''`

I have the full log saved as a txt file for the second check, so if dev would like to see that just ping me and I'll DM it.

**To Reproduce**
1. deploy 2.7.4
4. Enable AD Auth
5. Provision downstream rke2
6. Add a single user as with CRTB to the rke2 cluster
7. Login to Rancher with that user
8. Delete that user from AD
9. Add several more users for CRTBs and PRTBs
10. Login as each of those users
11. Upgrade to 2.7.5
12. Login as each of the users again
13. Upgrade to 2.7.6-head
14. Immediately try to block the AD server from connecting (I used `docker exec -it <containerID> /bin/bash iptables -A OUTPUT -d  <AD_SERVER_IP> -j DROP`
15. Check the logs, see the failed to connect errors
16. Rancher is up, check the state of the configmap, see it says 100% finished
17. Look at users and see dupes and empty DNs
18. Check docker logs again, see that it says users were migrated

**Result**
Users are seemingly skipped and given blank DNs when "migrated" and then cannot login

**Expected Result**
Users are either skipped and left with GUID or are un-migrated back to their DN 

**Screenshots**
Not sure how to properly redact these screenshots and still provide useful information, so again if dev wants to see some screenshots just let me know and I can DM them.

**Comment by sowmyav27** [comment]
PR: https://github.com/rancher/rancher/pull/42479

**Comment by brudnak** [comment]
# ✅ PASS

## Validation Environment


| Component                        | Version / Type                                                                 |
| -------------------------------- | ------------------------------------------------------------------------------ |
| Rancher version                  | Start 2.7.4 >>> 2.7.5 >>> v2.7.6-53ebd8cbbcf50528774023f08202b082f95d1937-head |
| Installation option              | Docker                                                                         |
| Cert Details                     | `--acme-domain`                                                                |
| Docker version                   | 20.10.7, build f0df350                                                         |
| Downstream cluster type          | Linode RKE2                                                                    |
| Downstream K8s version           | v1.25.12+rke2r1                                                                |
| Authentication providers enabled | AD                                                                             |
| Logged in user role              | AD admin, AD standard usser, local admin                                       |
| Browser type                     | Opera GX                                                                       |
| Browser version                  | LVL5 (core: 100.0.4815.82) (x86_64)                                            |


<a name="top"></a>

### :muscle: Test Cases

| \#  | Priority | Description & Link | PASS/FAIL |
| --- | -------- | ------------------ | --------- |
| 1   | P0       | [Test 1](#test-1)  | ✅ PASS    |


<hr>

<a name="test-1"></a>

## :mag_right: `#`1 / Status: ✅ PASS


#### :small_red_triangle: [Back to top](#top)

<details>
    <summary>Test 1 details... Click to expand</summary>

#### Test Steps for Validation

#### Test Steps for Validation

1. Deploy Rancher version 2.7.4.
2. Activate AD authentication.
3. As an AD auth standard user, provision a downstream rke2 cluster.
4. Incorporate 6 AD users to the downstream cluster: 3 as owners, 3 as members.
5. Initiate login for all added users.
6. Remove 2 cluster owners from AD.
7. Upgrade to Rancher version 2.7.5.
8. Attempt user logins again, noting the absence of the cluster.
9. Transition to version 2.7.6-head.
10. Promptly obstruct the AD server's connection (utilizing the command: `docker exec -it <containerID> /bin/bash iptables -A OUTPUT -d  <AD_SERVER_IP> -j DROP`).
11. Adjust the log level to 'debug'.
12. Examine the system logs and the configuration map.




```log
2023/08/22 06:12:35 [ERROR] [migrate-ad-user] unable to migrate user 'u-<redacted>' due to a connection failure; this user will be skipped
2023/08/22 06:12:35 [ERROR] [migrate-ad-user] unable to migrate user 'u-<redacted>' due to a connection failure; this user will be skipped
```


#### ConfigMap

```yaml
apiVersion: v1
data:
  ad-guid-migration-status: FinishedWithSkipped
  skippedUsers: u-<redacted>,u-<redacted>,u-<redacted>,u-<redacted>,u-<redacted>,u-<redacted>
  skippedUsersCount: "6"
  statusLastUpdated: "2023-08-22T06:12:35Z"
kind: ConfigMap
metadata:
  creationTimestamp: "2023-08-22T06:12:29Z"
  labels:
    cattle.io/creator: norman
  name: ad-guid-migration
  namespace: cattle-system
  resourceVersion: "144695"
  uid: <redacted>
```

#### ✅ Expected Outcome

Users are bypassed once the connection to AD is severed.

#### ✅ Actual Outcome

Users are bypassed once the connection to AD is severed.

</details>

<hr>
