### ISSUE TITLE
[BUG] RKE2 2.7.5 etcdSnapshotRestore.name to restore ETCD not working for me

### ISSUE THREAD

**Issue by voarsh2** [rancher/rancher#42472]
**Rancher Server Setup**
- Rancher version: 2.7.5
- Installation option (Docker install/Helm Chart): Docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: 1.24
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Custom

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:
Admin/Owner

**Describe the bug**

Backup a RKE2 cluster.
Destroy it. 

Create a new one. Edit the cluster YAML to include (as an example):
```
    etcdSnapshotRestore:
      generation: 1
      name: etcd-snapshot-worker5-1692284404
```
Place an ETCD backup in proper path.

**Result**
My result is it creates an empty "fresh" cluster with my node and doesn't actually restore the ETCD data...
Sometimes I get "bootstrap data already found and encrypted with different token" error. I copy /var/lib/rancher/rke2/server/ (token, node token) over from old cluster and it seems to get overwritten and the "restore" just makes a blank cluster.

**Expected Result**

An actual restore. I managed to do it once, kind of by accident, have been trying to reproduce to salvage my ETCD data to a new cluster and it hasn't been working out.

**Screenshots**

**Additional context**

**Comment by Oats87** [comment]
What you are trying to do is not officially supported.

The server/agent token are populated from the `<cluster-name>-rke-state` secret, so manually trying to add the server/agent token to the node before running your restoration will simply be overwritten as you are seeing.

I see you are already commenting on the other issue we have for this: https://github.com/rancher/rancher/issues/36298 so I'm going to close this one.
