### ISSUE TITLE
Must click "Add Host" before dynamically registering Rancher Hosts

### ISSUE THREAD

**Issue by artburkart** [rancher/rancher#4248]
**Rancher Version:**

Rancher v1.0.0
Cattle v0.159.2
User Interface v0.100.3
Rancher Compose v0.7.3

**Docker Version:**

Docker version 1.10.3, build 20f81dd

**OS:**

Ubuntu 14.04.2 LTS

**Steps to Reproduce:**

- Start a Rancher Server from scratch
- Start a Rancher Host and make it dynamically register itself using [this strategy](http://rancher.com/using-ansible-with-docker-to-deploy-a-wordpress-service-on-rancher/)

**Results:**

- If you have not clicked the "Add Host" button yet, the `data` field in the response from the `/v1/registrationtokens` endpoint is `[]`

```json
{
  "type": "collection",
  "resourceType": "registrationToken",
  "links": {
    "self": "http://rancher_domain.example.com/v1/registrationtokens"
  },
  "createTypes": {},
  "actions": {},
  "data": [],
  "sortLinks": {
    "accountId": "http://rancher_domain.example.com/v1/registrationtokens?projectId=1a5&sort=accountId",
    "created": "http://rancher_domain.example.com/v1/registrationtokens?projectId=1a5&sort=created",
    "description": "http://rancher_domain.example.com/v1/registrationtokens?projectId=1a5&sort=description",
    "id": "http://rancher_domain.example.com/v1/registrationtokens?projectId=1a5&sort=id",
    "kind": "http://rancher_domain.example.com/v1/registrationtokens?projectId=1a5&sort=kind",
    "name": "http://rancher_domain.example.com/v1/registrationtokens?projectId=1a5&sort=name",
    "publicValue": "http://rancher_domain.example.com/v1/registrationtokens?projectId=1a5&sort=publicValue",
    "registryId": "http://rancher_domain.example.com/v1/registrationtokens?projectId=1a5&sort=registryId",
    "removeTime": "http://rancher_domain.example.com/v1/registrationtokens?projectId=1a5&sort=removeTime",
    "removed": "http://rancher_domain.example.com/v1/registrationtokens?projectId=1a5&sort=removed",
    "secretValue": "http://rancher_domain.example.com/v1/registrationtokens?projectId=1a5&sort=secretValue",
    "state": "http://rancher_domain.example.com/v1/registrationtokens?projectId=1a5&sort=state",
    "uuid": "http://rancher_domain.example.com/v1/registrationtokens?projectId=1a5&sort=uuid"
  },
  "pagination": {
    "first": null,
    "previous": null,
    "next": null,
    "limit": 100,
    "total": null,
    "partial": false
  },
  "sort": null,
  "filters": {
    "accountId": null,
    "created": null,
    "description": null,
    "id": null,
    "kind": null,
    "name": null,
    "publicValue": null,
    "registryId": null,
    "removeTime": null,
    "removed": null,
    "secretValue": null,
    "state": null,
    "uuid": null
  },
  "createDefaults": {}
}
```
- Once the "Add Host" button is clicked, registration can commence dynamically as expected.

<h1 align="center">
	<br>
	<img src="https://cloud.githubusercontent.com/assets/463528/14176343/85ec3844-f71e-11e5-91d9-5fe4e00e88ab.png" alt="awesome">
	<br>
	<br>
	<br>
</h1>
**Expected:**

- I wouldn't expect to need to click the "Add Host" button in order to dynamically register Rancher Hosts

**Comment by vincent99** [comment]
@galal-hussein The ansible script should generate a registrationToken if none exist instead of assuming one does.

**Comment by artburkart** [comment]
Oh, I think this might be a problem on my side. I'm not using Ansible for this, instead we wrote up a bash script to do this instead. Right now we have:

```bash
PROJECT_ID=$(curl -s -u $KEY http://__RANCHER_DOMAIN__/v1/projects | jq -r ".data[0].id")
TOKEN=`curl -s -u $KEY http://__RANCHER_DOMAIN__/v1/registrationtokens?projectId=$PROJECT_ID | jq -r '.data[0].token'`
DOCKER_IMAGE=`curl -s -u $KEY http://__RANCHER_DOMAIN__/v1/registrationtokens?projectId=$PROJECT_ID | jq -r '.data[0].image'`

sudo docker run  -d --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher $DOCKER_IMAGE http://__RANCHER_DOMAIN__/v1/scripts/$TOKEN
```

But we should really have:

```bash
PROJECT_ID=$(curl -s -u $KEY http://__RANCHER_DOMAIN__/v1/projects | jq -r ".data[0].id")
TOKEN=`curl -s -X POST -u $KEY http://__RANCHER_DOMAIN__/v1/registrationtokens?projectId=$PROJECT_ID | jq -r '.data[0].token'`
DOCKER_IMAGE=`curl -s -u $KEY http://__RANCHER_DOMAIN__/v1/registrationtokens?projectId=$PROJECT_ID | jq -r '.data[0].image'`

sudo docker run  -d --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher $DOCKER_IMAGE http://__RANCHER_DOMAIN__/v1/scripts/$TOKEN
```

We're performing a `GET` instead of a `POST`

**Comment by artburkart** [comment]
I'm testing this theory now.

**Comment by galal-hussein** [comment]
@vincent99 The ansible script should generate a registration token from the default project id

```
- name: Get the default project id
  action: uri
      method=GET
      status_code=200
      url="http://{{ rancher_server }}:{{ rancher_port }}/v1/projects" return_content=yes
  register: project_id
- name: Return the registration token URL of Rancher server
  action: uri 
      method=POST
      status_code=201
      url="http://{{ rancher_server }}:{{ rancher_port }}/v1/registrationtokens?projectId={{ project_id.json['data'][0]['id'] }}" return_content=yes
  register: rancher_token_url
- name: Return the registration URL of Rancher server
  action: uri 
      method=GET 
      url={{ rancher_token_url.json['links']['self'] }} return_content=yes
  register: rancher_token
```

**Comment by vincent99** [comment]
Yes that's right, sorry I was reading on my phone and missed it.

You do also technically have to wait until the state becomes `active`, but it is unlikely you can really use it before that has happened.

**Comment by cloudnautique** [comment]
This https://github.com/cloudnautique/rbs-sandbox project might help with some of this.. at least show the code path. The intention of this is to build a config file with config management then execute the command. It is meant to take a fresh rancher install and bring it to a state where its ready to hand to a user. It can handles creating the run command.

**Comment by artburkart** [comment]
I tested it, it worked as I expected. I imagine the server is active when we've generated API tokens for our script to run? I don't imagine I'd ever be in a state where a Rancher Host would attempt to register when I don't have tokens yet. Maybe I haven't automated it enough yet :wink:

```bash
# Get project ID
PROJECT_ID=$(curl -s -u $KEY http://__RANCHER_DOMAIN__/v1/projects | jq -r ".data[0].id")

# Create registration token
curl -s -X POST -u $KEY http://__RANCHER_DOMAIN__/v1/registrationtokens?projectId=$PROJECT_ID

# Get registration token
TOKEN=`curl -s -u $KEY http://__RANCHER_DOMAIN__/v1/registrationtokens?projectId=$PROJECT_ID | jq -r '.data[0].token'`

# Get docker image name
DOCKERIMAGE=`curl -s -u $KEY http://__RANCHER_DOMAIN__/v1/registrationtokens?projectId=$PROJECT_ID | jq -r '.data[0].image'`

# Start up the beast
sudo docker run  -d --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher $DOCKERIMAGE http://__RANCHER_DOMAIN__/v1/scripts/$TOKEN
```

... and @cloudnautique has verified that we have not automated enough yet.

**Comment by deniseschannon** [comment]
@artburkart If you have more questions, please re-open or open a new issue, but it seems like you figured out how to fix your original issue.

**Comment by donfirst** [comment]
@artburkart 
Hi do you have any other script to Rancheros automation ? And you would mind to share this scripts with us :-)
I'm looking for script witch allows me to import users to rancheros
cheers
