### ISSUE TITLE
Add Volume path to container info page

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#425]
v0.14.2

Steps:
1.  Click on a mysql container name in the Container list page

Results:
You see the volume id number

Expected:
Would be nice to see the volume path, so you can just copy/paste it from here.

**Comment by lvuch** [comment]
Is path now displayed under volumes mount point?

**Comment by lvuch** [comment]
![screen shot 2016-03-14 at 3 34 57 pm](https://cloud.githubusercontent.com/assets/3013118/13762189/6b4eb0ba-e9fa-11e5-9de6-9a223d55ec85.png)

**Comment by lvuch** [comment]
clipboard functionality added in https://github.com/rancher/ui/pull/535

**Comment by tfiduccia** [comment]
Version - master 3/15
Verified fixed
