### ISSUE TITLE
[BUG] Provisioning an RKE1 Custom Downstream Cluster Throws an error about unsupported Docker version 24.0.2

### ISSUE THREAD

**Issue by floatingman** [rancher/rancher#42501]
**Rancher Server Setup**
- Rancher version: 2.7.7-rc3
- Installation option (Docker install/Helm Chart): RKE1
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.26.7-rancher1-1
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Custom

**User Information**
- What is the role of the user logged in? Admin

**Describe the bug**
When provisioning an RKE1 downstream custom cluster, an error message is shown that the Docker version 24.0.2 is unsupported. 

**To Reproduce**
Create a custom RKE1 cluster in Cluster Management 

**Result**
Error message stating Docker version 24.0.2 is unsupported

**Expected Result**
Custom cluster should register without error.

**Screenshots**
![Screenshot 2023-08-22 at 12 29 49 PM](https://github.com/rancher/rancher/assets/48339/9e8aeb0c-c309-42c4-9c43-b602d6c09e4c)
![Screenshot 2023-08-22 at 2 19 56 PM](https://github.com/rancher/rancher/assets/48339/e1b5a060-1605-4a41-a9f0-661285098915)

**Comment by igomez06** [comment]
QA validation:

Rancher Server Setup

Rancher version: v2.7.7-rc4 HA
Downstream cluster: 1 node RKE1 v1.26.7+rke2r1 encrypt secret enabled

provisioning/rke1/provisioning_node_driver_test.go
with `Require a supported Docker version` enabled 

Status: PASS
