### ISSUE TITLE
No basic auth credentials supplied using custom registry

### ISSUE THREAD

**Issue by rocketeer125** [rancher/rancher#4250]
When configuring a custom registry (using Amazon ECR), Basic Auth credentials are stripped out on pulling the docker image from the registry: 

docker-compose.yml:

    myapp:
      image: 95629****971.dkr.ecr.us-east-1.amazonaws.com/app

Results in:

`Waiting for [instance:mystack_myapp_1]. Instance status: 500 Server Error: Internal Server Error ("Get    https://95629****971.dkr.ecr.us-east-1.amazonaws.com/v2/app/manifests/latest: no basic auth credentials")`

Though the registry shows active.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.0.0` Cattle: `v0.159.2` UI: `v0.100.3` |
|Access|`Disabled`|
|Route|`environment.index`|

**Comment by deniseschannon** [comment]
Can you confirm what type of environment you have? Cattle/K8S/Swarm?

**Comment by rocketeer125** [comment]
@deniseschannon I'm using Cattle on CentOS 7.

**Comment by deniseschannon** [comment]
I re-read the issue and realized that this is a duplicate of https://github.com/rancher/rancher/issues/3126.

We don't have support for Amazon ECR.

**Comment by rocketeer125** [comment]
Ok I thought this was now supported: http://rancher.com/using-amazon-container-registry-service/

**Comment by deniseschannon** [comment]
It looks like there is a basic auth issue with custom registries. Please follow: https://github.com/rancher/rancher/issues/3634

Thanks for pointing out the Amazon ECR blog post. :)

**Comment by deniseschannon** [comment]
I forgot to mention that it will be in our next major release (1.1).
