### ISSUE TITLE
[BUG] Hostbusters Image CVEs fix

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#42525]
usr/bin/rancher-machine -> https://github.com/rancher/machine/pull/219

**Comment by snasovich** [comment]
This will be ready to test once new `rancher-machine` version with the changes from linked PR is referenced in Rancher.
The testing will be "while at it" to see if there are any obvious regressions.

**Comment by thaneunsoo** [comment]
Tested this issue on v2.7-head 9a41588
The go dependencies version bumps seem to be working as expected.
