### ISSUE TITLE
Feature request: Clone / Move services across Stacks

### ISSUE THREAD

**Issue by ahfeel** [rancher/rancher#4253]
It would be great to be able to clone and / or move services across different stack. There's a lot of usecases for this, may it be duplicating a backup or monitoring or whatever service.

**Comment by xlight** [comment]
+1

**Comment by kilmarnock** [comment]
+1
Maybe a duplicate of  #3887

**Comment by easylo** [comment]
+1

**Comment by vincent99** [comment]
Yes, #3887
