### ISSUE TITLE
How do I find the Red resource

### ISSUE THREAD

**Issue by andersla** [rancher/rancher#42557]
I am using Rancher 2.7.4 and have a red label 1 on my Cluster Dashboard, how can I find what is the problem?

![image](https://github.com/rancher/rancher/assets/17414346/9e070071-f50e-4779-b1fb-07bbf0345caf)

**Comment by Creat1v** [comment]
We are facing the same question using Rancher 2.7.5

**Comment by p-mlynik** [comment]
Hi, has this problem been solved? Do you have any ideas how can I find this recourse, which generate a error? Why can I find more information in this tab "total resources"

**Comment by belfhi** [comment]
Same question here. That information seems a little superfluous if you can't get any more details 🙄
