### ISSUE TITLE
[RFE] Generate openapi spec for rancher 

### ISSUE THREAD

**Issue by KevinJoiner** [rancher/rancher#42553]
SURE-6822 

**Is your feature request related to a problem? Please describe.**
Docs need a way to generate openapiv3 spec for all publicly supported CRDs created by Rancher

**Describe the solution you'd like**
Create a swagger.json for generated Rancher CRDs.

**Additional context**
This file is needed to display reference guides for Rancher CRDs, the location of this code is still TBD.

### Dev Validate 
This issue requires validation from the docs team that the supplied swagger.json works with there desire tools and has the paths for the following CRDs
- GlobalRole
- GlobalRoleBinding
- RoleTemplate
- ClusterRoleTemplateBinding
- ProjectRoleTemplateBinding
- Projects

**Comment by samjustus** [comment]
I know Caleb added it, but Kevin when you get around to it, please follow this process https://confluence.suse.com/display/RANQA/Neo+dev-validate+Process regarding the dev-validate label

**Comment by KevinJoiner** [comment]
@gunamata I created the above swagger.JSON can someone from the docs team validate that it works with our current docs tools.

**Comment by gunamata** [comment]
Thanks @KevinJoiner

@btat, Can you please try the swagger JSON with the API docs plugin you have identified.

**Comment by btat** [comment]
@KevinJoiner @gunamata Confirming it works with our current tooling.

![Swagger API](https://github.com/rancher/rancher/assets/1832069/52b068b3-23ef-4bc9-99e9-189fca370ea4)
