### ISSUE TITLE
Forwardport GUID AD issues to 2.8-head

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#42561]
| Original Issue(s) | Original PR |  Forwardport PRs |
| --- | --- | --- |
| https://github.com/rancher/rancher/issues/42161, https://github.com/rancher/rancher/issues/42162, https://github.com/rancher/rancher/issues/42163 | https://github.com/rancher/rancher/pull/42325 | https://github.com/rancher/rancher/pull/42548 |
| https://github.com/rancher/rancher/issues/42467 | https://github.com/rancher/rancher/pull/42470 | https://github.com/rancher/rancher/pull/42549 |
| https://github.com/rancher/rancher/issues/42467 | https://github.com/rancher/rancher/pull/42470 | https://github.com/rancher/rancher/pull/42550 |
| https://github.com/rancher/rancher/issues/42478 | https://github.com/rancher/rancher/pull/42479 | https://github.com/rancher/rancher/pull/42551 |
| https://github.com/rancher/rancher/issues/42466 | https://github.com/rancher/rancher/pull/42493 | https://github.com/rancher/rancher/pull/42552 |

**Comment by MKlimuszka** [comment]
https://github.com/rancher/rancher/pull/42470 being mentioned twice is correct, as there were two different commits in that PR, which are being done separately here. Also, see https://github.com/rancher/rancher/issues/42560 for 2.7-head sideport ticket.

**Comment by nickwsuse** [comment]
`Verified on v2.8-head ID: 734ee0e`

I ran the test cases below and everything is looking great.

**Test Cases:**
1. Upgrade from 2.7.4 -> 2.7.5 -> 2.8-head | Duplicate users removed
2. Upgrade from 2.7.4 -> 2.7.5 -> 2.8-head | GUID users are back to DN
3. Fresh install of 2.8-head | Configmap is created
4. Fresh install of 2.8-head | Restarting Rancher pod with configmap doesn't re-run un-migration
5. Enabling other auth providers not causing issues with configmap/un-migration not being re-run
