### ISSUE TITLE
Update ACI-CNI to 6.0.3.1

### ISSUE THREAD

**Issue by jeffinkottaram** [rancher/rancher#42568]
There is ACI-CNI version 6.0.3.1 which is an upgrade to 5.2.7.1 we currently have included in KDM for RKE1 provisioned clusters.

**Comment by snasovich** [comment]
QA to be handled by Cisco team. Rancher QA has confirmed that non-ACI flows are working as expected following the updates applied per this issue.

@jeffinkottaram , please report test results.

**Comment by akhilesh-oc** [comment]
Done with testing. No issues observed.

**Comment by snasovich** [comment]
Closing per above. FYI @daviswill2
