### ISSUE TITLE
RKE2 and K3S - KDM Update for K8s August patch release for Rancher 2.6

### ISSUE THREAD

**Issue by rancher-max** [rancher/rancher#42575]
# KDM Updates

| New Kubernetes Version  | Min Rancher Version | Max Rancher Version |
|                  :---:                  |              :---:               |               :---:               |
| v1.24.17+rke2r1                  | v2.6.7-alpha1             | v2.6.99 |
| v1.24.17+k3s1                    | v2.6.7-alpha1             | v2.6.99 |

# KDM Branch
dev-v2.6

# Chart Changelog

| Chart Name  | New Version | Affected Kubernetes Version(s) |
|        :---:        |       :---:        |                     :---:                     |
| rke2-multus | v4.0.2-build2023081100 | v1.24.17+rke2r1 |
| rke2-canal | v3.26.1-build2023080200 | v1.24.17+rke2r1 |
| rke2-cilium | 1.14.000 | v1.24.17+rke2r1 |

# Argument Changelog

| Argument Name  | Affected Kubernetes Version(s) |
|        :---:           |                     :---:                     |
| helm-job-image | v1.24.17+k3s1 |

# Additional Notes

N/A

**Comment by ShylajaDevadiga** [comment]
Validated using Rancher v2.6.13 that this has the expected versions and they are working correctly:

<img width="1399" alt="image" src="https://github.com/rancher/rancher/assets/56045581/1cb97106-34ec-4820-940e-ae94f6a44266">

**Comment by ShylajaDevadiga** [comment]
<img width="1888" alt="image" src="https://github.com/rancher/rancher/assets/56045581/fdf16b68-336a-4c55-80b3-87c32c53eec9">
