### ISSUE TITLE
RKE2 and K3S - KDM Update for K8s August patch release for Rancher 2.7

### ISSUE THREAD

**Issue by rancher-max** [rancher/rancher#42574]
# KDM Updates

| New Kubernetes Version  | Min Rancher Version | Max Rancher Version |
|                  :---:                  |              :---:               |               :---:               |
| v1.24.17+rke2r1                  | v2.6.7-alpha1             | v2.7.99 |
| v1.25.13+rke2r1                  | v2.7.2-alpha1             | v2.7.99 |
| v1.26.8+rke2r1                  | v2.7.5-alpha1             | v2.7.99 |
| v1.24.17+k3s1                    | v2.6.7-alpha1             | v2.7.99 |
| v1.25.13+k3s1                  | v2.7.2-alpha1             | v2.7.99 |
| v1.26.8+k3s1                  | v2.7.5-alpha1             | v2.7.99 |

# KDM Branch
dev-v2.7-2023-08-patches

# Chart Changelog

| Chart Name  | New Version | Affected Kubernetes Version(s) |
|        :---:        |       :---:        |                     :---:                     |
| rke2-multus | v4.0.2-build2023081100 | v1.24.17+rke2r1, v1.25.13+rke2r1, v1.26.8+rke2r1 |
| rke2-canal | v3.26.1-build2023080200 | v1.24.17+rke2r1, v1.25.13+rke2r1, v1.26.8+rke2r1 |
| rke2-cilium | 1.14.000 | v1.24.17+rke2r1, v1.25.13+rke2r1, v1.26.8+rke2r1 |
| rke2-snapshot-validation-webhook | 1.7.300 | v1.25.13+rke2r1, v1.26.8+rke2r1 |

# Argument Changelog

| Argument Name  | Affected Kubernetes Version(s) |
|        :---:           |                     :---:                     |
| helm-job-image | v1.24.17+k3s1, v1.25.13+k3s1, v1.26.8+k3s1 |

# Additional Notes

N/A

**Comment by ShylajaDevadiga** [comment]
Validated using Rancher v2.7.6 that this has the expected versions and they are working correctly:
<img width="1465" alt="image" src="https://github.com/rancher/rancher/assets/56045581/b025d23a-c6ba-4d9e-8836-2c7637d11f85">

<img width="1889" alt="image" src="https://github.com/rancher/rancher/assets/56045581/9d5c460a-a4a8-4b66-8acb-75557c09465c">
