### ISSUE TITLE
Update Nutanix node driver to version 3.4.0+

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#42576]
Updated Nutanix node driver to version 3.4.0 or later.

**Comment by tuxtof** [comment]
OK just test container rancher:v2.7-head

- driver is available in version 3.4.0
- activation of the driver is OK
- VM is correctly created on the Nutanix cluster

**Comment by thaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.8-head 6936f84
Rancher cluster type: HA
Docker version: 20.10

----------

### Testing: ###
v2.8-head 6936f84 is updated to use v3.4.0 and can be activated successfully. I don't have credentials to test the functionality but it seems @tuxtof has already tested the functionality. Closing this issue as completed.
![image.png](https://zube.io/files/rancher/30e24c25f2ec67db7cea8f9b8b4b19fb-image.png)

**Comment by thaneunsoo** [comment]
This issue does not need to be automated.
