### ISSUE TITLE
[Backport v2.6] Update ACI-CNI to 6.0.3.1

### ISSUE THREAD

**Issue by jeffinkottaram** [rancher/rancher#42570]
There is ACI-CNI version 6.0.3.1 which is an upgrade to 5.2.7.1 we currently have included in KDM for RKE1 provisioned clusters.

This is a backport of rancher/rancher#42568  for 2.6 release line.

**Comment by snasovich** [comment]
QA to be handled by Cisco team. Rancher QA has confirmed that non-ACI flows are working as expected following the updates applied per this issue.

@jeffinkottaram , please report test results.

**Comment by jeffinkottaram** [comment]
Testing is done.

**Comment by snasovich** [comment]
Closing per above. FYI @daviswill2
