### ISSUE TITLE
[BUG] Only set owned tag on ec2 instance if tag is not present

### ISSUE THREAD

**Issue by jakefhyde** [rancher/rancher#42588]
**Rancher Server Setup**
- Rancher version: v2.7.5

**Information about the Cluster**
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): v2prov

**Describe the bug**

When using CAPR, ec2 instances are automatically tagged with the cluster id of the newly generated cluster (`c-m-xxxxxxx`). This tag is only know after the cluster is created, and therefore if a user selects their own security group and/or subnet, they will have to manually tag them later by interacting with their cloud provider. This proposed change only tags the ec2 instances if there is not an existing `kubernetes.cluster.io/<id>,owned` or `kubernetes.cluster.io/<id>,shared` tag, as an ec2 object cannot be owned by multiple entities.

**To Reproduce**

Provision an amazon node driver rke2 cluster with the tag `kubernetes.cluster.io/<id>,owned`.

**Result**

The machine will have multiple owned tags, and will fail to provision successfully.

**Expected Result**

Tags are not duplicated.

**Screenshots**

**Additional context**

This is required for cloud provider integrations with the aws cloud provider to function properly.

**Comment by Josh-Diamond** [comment]
No automation needed for this, as there isn't a way to view AWS resource tags on Rancher's end.  Proceeding w/ manual validations.

**Comment by Josh-Diamond** [comment]
Ticket #42588 - Test Results - ✅ 
---

Reproduced on Rancher `v2.7.6`:
1. Fresh install of Rancher `v2.7.6`
2. Provision a downstream RKE2 AWS Node driver cluster
3. Once `active`, `Edit Config`, and add the following tag, twice: `kubernetes.cluster.io/<id>,owned`, then hit `Save`
4. Reproduced - user is navigated back to `Cluster Management` page, where cluster hangs in an updating state and never resolves back to `active`

---

Verified with HA Helm on Rancher `v2.8-5cffa891781908dcbe2c6bb8be2084b362e2ff00-head`:
1. Fresh install of Rancher `v2.8-head`
2. Provision a downstream RKE2 AWS Node driver cluster
3. Once `active`, `Edit Config`, and add the following tag, twice: `kubernetes.cluster.io/<id>,owned`, then hit `Save`
4. Verified - user is navigated back to `Cluster Management` page, however the cluster never enters an `Updating` state, as Rancher prevents the duplicate tags from being created; as expected
