### ISSUE TITLE
[BUG] RKE2 downstream cluster does not become "Active" and it is stuck in "Provisioning" state (v2.7.5)

### ISSUE THREAD

**Issue by egrosdou** [rancher/rancher#42585]
**Rancher Server Setup**

- Rancher version: 2.7.5
- Installation option (Docker install/Helm Chart): Helm with self-sign certificate
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2 v1.26.6+rke2r1

**Information about the Cluster**

- Kubernetes version: v1.26.6+rke2r1
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? RKE2 v1.26.6+rke2r1

**User Information**

- What is the role of the user logged in? Admin

**Describe the bug**

We use the rancher_v2 TF provider to deploy RKE2 downstream clusters in vSphere. Once the TF plan is applied, we wait till all the nodes are available/active, and then the cluster will be in an "Active" state for a minute max, then the condition will change and fallback to the "Provisioning" state.

Our observations: when Rancher configures the rancher-webhook in the RKE2 downstream cluster, we get an unhealthy state which leads to the "Provisioning" state. Taking a better look into this issue, two of the Helm-pods for the rancher-webhook fail with an Error while on the third one is successful, and the rancher-webhook pod is in a "Running" state.

**To Reproduce**

1. Install Rancher Server v2.7.5 via ArgoCD as a Helm chart and update the Rancher CA with a custom one. Deploy Helm Chart on underlying RKE2 v1.26.6+rke2r1 cluster
2. Deploy a downstream RKE2 v1.26.6+rke2r1 cluster on vSphere
3. Check the status of the downstream cluster

**Result**

The cluster appears to be in an "Active" state for less than a minute as all nodes are running, but afterwards it fallsback to a "Provisioning" state and never recovers.

**Expected Result**

I would expect the cluster to de in an "Active" state as the cluster condition "Ready" is set to "True"

**Additional context**
Cilium as a CNI

**Comment by egrosdou** [comment]
![Screenshot 2023-08-30 at 10 36 03](https://github.com/rancher/rancher/assets/129873421/4506fd30-c891-4101-a5b6-ccf59689e21e)
![Screenshot 2023-08-30 at 10 36 40](https://github.com/rancher/rancher/assets/129873421/7c46a6e0-2a9d-4826-a506-c4a9a55c019f)
![Screenshot 2023-08-30 at 10 36 55](https://github.com/rancher/rancher/assets/129873421/f89b16ea-94cc-46a7-a53c-82bd950be39a)

**Comment by egrosdou01** [comment]
The root cause of this matter was a misconfiguration in our internal DNS server. Once this was fixed, the cluster remained in an "Active" state.
