### ISSUE TITLE
[cattle-cli] cant search hosts by hostname

### ISSUE THREAD

**Issue by mrproper** [rancher/rancher#4258]
Rancher Version:
1.0.0
Docker Version:
N/A
OS: 
N/A
Steps to Reproduce: 

```
client = cattle.Client(
  url=rancher_full_url,
  access_key=key,
  secret_key=secret,
)
h = client.list_host(hostname=host, state='active')
```

this results in a http request of:
http://$rancher_host:8080/v1/hosts?state=active&hostname=$hostname

hostname is not a filter...but 'name' is
and by default 'name' is null....however in the UI it says that for 'custom name' that: 'If this is left empty, the Hostname will be used as the Name.'

So unless you set that custom name, theres no effective way of searching hosts by hostname.

The only way currently around this is by searching for all hosts then filtering the results in your own code

**Comment by kaos** [comment]
Is it not an easy fix, to let us filter by `hostname` ?

**Comment by BobVanB** [comment]
Our work around to find our host is to set the name the same as the hostname.
Because name can be filtered.

But this is not a very good solution, because when the name is altered, it can't be found.
I would like to see this fixed as well.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
