### ISSUE TITLE
[RKE2 and K3s] Add K8s 1.27.5 support in KDM

### ISSUE THREAD

**Issue by rayandas** [rancher/rancher#42590]
Related: https://github.com/rancher/rancher/issues/41840

**Comment by cwayne18** [comment]
Which branch? Just dev-2.7? dev-2.8?

**Comment by kinarashah** [comment]
Yup, confirmed with @Sahota1225 that 1.27 is for rancher 2.8+ only.

**Comment by snasovich** [comment]
Closing as it was implemented per https://github.com/rancher/rancher/issues/41840
