### ISSUE TITLE
[UI] Font missing/not rendered correctly

### ISSUE THREAD

**Issue by pulberg** [rancher/rancher#4259]
Rancher Version: 1.0.0

Docker Version: 1.10.1

OS: RancherOS v0.4.3

UI is being used on Mac OS X 10.11.4, Chrome Version 49.0.2623.110 (64-bit), Firefox 45.0.1

Steps to Reproduce: Navigate to any host/container system info page to view graph for CPU/Mem/Network

Results: View the font on the left of the graph that indicates info - % for cpu, Kbps for network, etc., see that the font used is some sort of "default" font from your system and does not match any other font used in the Rancher UI.

Expected: The font specified in the "ui-light.css", or "ui-dark.css" is called "Open Sans", but the font rendered on the page is clearly a "serif" font (it looks like TimesNR).  I tested changing the font in the Chrome dev tools to match the UI, the font is "Lato" and looks great.

Thanks,

Phillip

Wrong Font - 
![wrong_font](https://cloud.githubusercontent.com/assets/11069351/14197177/25546448-f791-11e5-867f-37d587d91b78.png)

Correct Font - 
![correct_font](https://cloud.githubusercontent.com/assets/11069351/14197183/2fd710c8-f791-11e5-8de7-8e45ab96a643.png)

**Comment by vincent99** [comment]
Oops, this one got missed when we last switched the font, and we all have it installed on our computers so it still renders.

**Comment by pulberg** [comment]
Thanks for the update, I really appreciate the effort of the Rancher team, you are doing great work and have made many things much better/easier for my team.

**Comment by tfiduccia** [comment]
Version - v1.0.1-rc1
Verified fixed
