### ISSUE TITLE
[flaky-test]  TestRancherManagedChartsSuite

### ISSUE THREAD

**Issue by MbolotSuse** [rancher/rancher#42606]
**Flaky Test**

**Release Branch**

source branch of PR: `release/v2.8`

**Drone Build (if applicable)**

pipeline stage URL: https://drone-pr.rancher.io/rancher/rancher/32154/5/2

Notes: This test appears to be introduced by rancher/rancher#42421, which appeared to copy/modify a separate flaky test (identified in rancher/rancher#41853).

**Comment by felipe-colussi** [comment]
his also happen 2 days ago.  Sep 6, 2023, 6:16 PM. 

https://drone-publish.rancher.io/rancher/rancher/10520/6/2 under default-linux-arm64
