### ISSUE TITLE
[BUG] Download / Copy KubeConfig creates a new api key / token each time

### ISSUE THREAD

**Issue by erSitzt** [rancher/rancher#42603]
**Rancher Server Setup**
- Rancher version: 2.7.4 / 2.7.5
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.23.17+rke2r1
- Cluster Type (Local/Downstream): Local and Downstream Clusters
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:
Admin

**Describe the bug**

Not sure if this is a bug or intended this way
Clicking on "Copy KubeConfig to Clipboard" or "Download KubeConfig" generates a new API-Token and therefore a new kubeconfig each time.
 All of them are set to "Never" expire and accumulate in the list of api keys

<img width="859" alt="image" src="https://github.com/rancher/rancher/assets/1625376/e7c4d76f-37e1-4a9d-a92d-86804d59e4fd">

**To Reproduce**

<img width="488" alt="image" src="https://github.com/rancher/rancher/assets/1625376/e80d68b9-c592-44c5-9789-b199d8431555">

**Result**

**Expected Result**

the same working kubeconfig for the current user and scope unless the token is not valid 
**Screenshots**

**Additional context**

If this is a bug or not, in both cases this messes with the terraform rancher provider datasource rancher2_cluster because the kubeconfig changes every time `terraform plan` or `terraform apply` is executed

https://github.com/rancher/terraform-provider-rancher2/issues/841

**Comment by cbron** [comment]
I believe every kubeconfig now generates a new token. That changed when token-hashing was implemented, because if the token is hashed you can't retrieve the user's previous token. You can change the default TTL though, see: 
https://github.com/rancher/rancher/issues/37705
https://ranchermanager.docs.rancher.com/reference-guides/about-the-api/api-tokens

**Comment by erSitzt** [comment]
Ok, i think i found the problem in the terraform-provider-rancher2.
I will close this.
