### ISSUE TITLE
All containers are removed when host is deleted from environment

### ISSUE THREAD

**Issue by npcode** [rancher/rancher#4261]
Rancher Version: 1.0.0

Docker Version: 1.10.3

OS: CentOS 7

Steps to Reproduce: 

1. Install rancher
2. Create a swarm environment
3. Infrastructure > Hosts > Add some hosts including the one on which rancher server is running
4. Delete the host on which the server is running

Results: 

Rancher server down

Expected:

Rancher server keeps running

**Comment by npcode** [comment]
Rancher seems to stop all containers of the node which is removing. Is there any way to remove a node without such side-effect?

**Comment by deniseschannon** [comment]
Verified with v1.0.0. 

In a Cattle environment, if you add Rancher as a host and then delete it, it stops and remove the Rancher container and all other running containers (including rancher server if running).

**Comment by deniseschannon** [comment]
@npcode This is not expected behavior as in previous releases, we would not remove all running containers.

**Comment by deniseschannon** [comment]
Verified in v1.0.1-rc3
