### ISSUE TITLE
Spike - Deprecate OPA Gatekeeper - https://jira.suse.com/browse/SURE-6270

### ISSUE THREAD

**Issue by rohitsakala** [rancher/rancher#42627]
Before moving ahead with the decision, the engineering team has to do a spike/research on the difference between OPA Gatekeerp and Kubewarden. The main things to look for are the following 

1. Is there a feature parity? If so list them out
2. Can there be a migration path from OPA Gatekeeper to KubeWarden ? Talk to Kubewarden team. 
3. If there is, then what would be the engineering timeload for creating such a migration path . It can be through documentation or through scripts in an automated manner (through codebase)

**Comment by rohitsakala** [comment]
@martyav @btat Can we add this deprecation notice of OPA Gatekeeper chart from rancher/charts in the release notes ? Along with the comparison b/w OPA Gatekeeper and Kubewarden https://docs.kubewarden.io/explanations/opa-comparison. 

The UI is putting the deprecation warning as this ```The OPA Gatekeeper chart is deprecated as of Rancher 2.8 and will be removed in a future release. Please consider switching to Kubewarden.```

**Comment by martyav** [comment]
@rohitsakala It's probably too early to open a draft for v2.8, but I'll make a note of this.

**Comment by rohitsakala** [comment]
Closing this as UI PR is merged to put the deprecation warning.

**Comment by martyav** [comment]
Just a note that this should have the `release-note` and "added to release note" labels applied. I don't currently have the perms to do so.

**Comment by anguswilliams** [comment]
Hey @rohitsakala would it be possible to provide more infomation about the reasoning for deprecation? I can't access the jira issue unfortunately.

**Comment by CamrynCarter** [comment]
Hi @anguswilliams, OPA gatekeeper is being deprecated in favor of Kubewarden

**Comment by Tejeev** [comment]
@CamrynCarter Do we have more information about the reasoning for deprecation that we can share with customers?

**Comment by zilmarr** [comment]
I have the same question as @Tejeev.

**Comment by flavio** [comment]
> **Disclaimer:** I'm one of the maintainers of Kubewarden and a SUSE employee.

Kubewarden is an open source project created by Rancher and then donated to CNCF. It's currently a sandbox project, we plan to apply for incubation graduation this year.

Kubewarden provides a more flexible and powerful way to write policies compared to OPA Gatekeeper. As part of this flexibility, OPA Gatekeeper policies can be reused on top of Kubewarden.
You can find a comparison of Kubewarden and OPA Gatekeeper [here](https://docs.kubewarden.io/explanations/opa-comparison).

Finally, Rancher has a UI extension developed for Kubewarden. This provides a UI that manages the lifecycle of the Kubewarden stack, plus it augments parts of the regular Rancher UI with information coming from Kubewarden.

**Comment by zilmarr** [comment]
@flavio thanks for the clarification!

Being kubewarden an originally SUSE product, this decision makes total sense.

**Comment by Tejeev** [comment]
AAaaah, that makes a lot more sense now.  Thank you!
