### ISSUE TITLE
Feature Request: Route53 DNS to support internal zones

### ISSUE THREAD

**Issue by rocketeer125** [rancher/rancher#4262]
The Rancher **Add Route53 DNS Stack** Catalog entry currently only supports public zones.

I can suggest that this can probably be implemented by changing the configuration options from **Hosted zone** to **Hosted zone ID**. Hosted zone can then be pulled programatically from AWS.

Use Case / Background; We use a VPN to connect to our AWS infrastructure. On the VPN, only the internal DNS is available.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.0.0` Cattle: `v0.159.2` UI: `v0.100.3` |
|Access|`Disabled`|
|Route|`environments.index`|

**Comment by janeczku** [comment]
@rocketeer125 Is this a split-horizon DNS configuration or do you use a dedicated zone apex for the private zone? The current Route53 should already support the latter.

**Comment by rocketeer125** [comment]
@janeczku, yes we have a split horizon DNS topology. 
Your solution sounds good too, and is probably more backwards compatible.

**Comment by guruvan** [comment]
:+1:  This is awesome @janeczku  :)) I didn't know Rt53 would support public/private zone with the same name - a checkbox or allowing the user to input the Rt53 Zone ID would be great for our case.

**Comment by janeczku** [comment]
> I didn't know Rt53 would support public/private zone with the same name 
Me neither 😆 . And apparently you can even have multiple public zones with the same name. In that case checkbox won't do. Hence we are going with the Hosted Zone ID input field.

**Comment by guruvan** [comment]
Yes, indeed you can - just tested this. - Multiple private zones of the same name do not appear to be supported.  This is fantastic news - allows us to proceed with adding skydns+rt53 for additional announcements not directly supported via rancher and continue using rancher DNS (which rocks)

**Comment by sangeethah** [comment]
With Route53 catalog version - rancher/external-dns:v0.4.0 , we are allowed to enter values for "HostedZoneId" in additoin to "Hosted zone name" .

So we are able to program entries to a specfic "Hosted zone" when there are multiple hosted zones with the same name by using the "HostedZoneId".

But  when entering values for "HostedZoneId" without entering "Hosted zone name" , User is prompted to enter "Hosted zone name" which should not be necessary in the case "HostedZoneId" is provided.
This issue is tracked in https://github.com/rancher/rancher/issues/4583.

**Comment by sangeethah** [comment]
@rocketeer125 , With Route53 catalog version - rancher/external-dns:v0.4.0 , we have the ability to  enter values for "HostedZoneId" in addition to "Hosted zone name" .
Could you see that  this version of external-dns addresses the support internal zones ?

**Comment by rocketeer125** [comment]
@sangeethah sure I'll test this tomorrow when I'm back at my desktop. Thanks for your work on this.

**Comment by deniseschannon** [comment]
@rocketeer125 Please re-open if you still have issues.
