### ISSUE TITLE
[BUG] Backport of https://github.com/rancher/rancher/issues/41746 PR to 2.7 release line

### ISSUE THREAD

**Issue by rohitsakala** [rancher/rancher#42628]

**Comment by gaktive** [comment]
In case folks are looking for the link: https://github.com/rancher/rancher/issues/41746

**Comment by rohitsakala** [comment]
There is no customer justification for it to be backported. @CamrynCarter  said there needs to be a customer justification if a backport is required. 

So, I will close this. @diogoasouza Let me if I am wrong.
