### ISSUE TITLE
Feature Request: Private Registry Integration with Kubernetes

### ISSUE THREAD

**Issue by strantalis** [rancher/rancher#4263]
As of right now it does not look like that kubernetes can interact with private registries that are setup in rancher. I was specifically trying to setup AWS ECR with kubernetes. I think this feature would be a nice to have and make things easier working with kubernetes through rancher in the future.

Rancher Version: v1.0

**Comment by deniseschannon** [comment]
Pre-duplicate of https://github.com/rancher/rancher/issues/4529
