### ISSUE TITLE
[BUG][RKE1][CIS-1.24] New failures observed on RKE1 permissive and hardened clusters with the latest CIS chart 4.2.0-rc6 

### ISSUE THREAD

**Issue by Priyashetty17** [rancher/rancher#42655]
**Rancher Server Setup**
- Rancher version: 	v2.7-dbac88362ae3bea3f7b912e52dcefaa750133277-head
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1 

**Information about the Cluster**
- Kubernetes version: v1.24.16
- CIS chart version: 4.2.0-rc6
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Custom permissive and hardened RKE1 clusters

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Admin

**Describe the bug**
New failures are observed on the RKE1 permissive and hardened clusters with the latest CIS chart **4.2.0-rc6** which was not previously observed on **chart 4.2.0-rc5.**

**Here are the issues we found:**
- **RKE1 Permissive:** 

State | Number | Description |  
-- | -- | -- | --
Fail | 4.1.3 | If proxy kubeconfig   file exists ensure permissions are set to 600 or more restrictive (Manual) |  
Fail | 4.1.4 | If proxy kubeconfig   file exists ensure ownership is set to root:root (Manual) |  
```
NOTE: I executed the command manually for checks 4.1.3 and 4.1.4 on the permissive node and the actual output did match the expected result:

ubuntu@xyz:~$ /bin/sh -c 'if test -e /etc/kubernetes/ssl/kubecfg-kube-proxy.yaml; then stat -c permissions=%a /etc/kubernetes/ssl/kubecfg-kube-proxy.yaml; fi' 
permissions=600
ubuntu@xyz:~$ /bin/sh -c 'if test -e /etc/kubernetes/ssl/kubecfg-kube-proxy.yaml; then stat -c %U:%G /etc/kubernetes/ssl/kubecfg-kube-proxy.yaml; fi' 
root:root
```
On RKE1 Permissive cluster, in addition to the failures above, following issues should be addressed:
- The returned value for checks 1.1.9 and 1.1.10 shows this instead of a valid output:
`Usage: grep [OPTION]... PATTERN [FILE]... Try 'grep --help' for more information.`
 ```
     {
        "id": "1.1.9",
        "description": "Ensure that the Container Network Interface file permissions are set to 600 or more restrictive (Manual)",
        "remediation": "Run the below command (based on the file location on your system) on the control plane node.\nFor example, chmod 600 <path/to/cni/files>\n",
        "state": "warn",
        "node_type": [
          "master"
        ],
        "audit": "ps -ef | grep $kubeletbin | grep -- --cni-conf-dir | sed 's%.*cni-conf-dir[= ]\\([^ ]*\\).*%\\1%' | xargs -I{} find {} -mindepth 1 | xargs --no-run-if-empty stat -c permissions=%a\nfind /var/lib/cni/networks -type f 2> /dev/null | xargs --no-run-if-empty stat -c permissions=%a\n",
        "audit_config": "",
        "test_info": [
          "Run the below command (based on the file location on your system) on the control plane node.\nFor example, chmod 600 <path/to/cni/files>\n"
        ],
        "commands": null,
        "config_commands": null,
        "actual_value_per_node": {
          "priyanodeprov124": "Usage: grep [OPTION]... PATTERN [FILE]...\nTry 'grep --help' for more information."
        },
        "expected_result": "'permissions' is present",
        "test_type": "",
        "scored": false
      },
      {
        "id": "1.1.10",
        "description": "Ensure that the Container Network Interface file ownership is set to root:root (Manual)",
        "remediation": "Run the below command (based on the file location on your system) on the control plane node.\nFor example,\nchown root:root <path/to/cni/files>\n",
        "state": "warn",
        "node_type": [
          "master"
        ],
        "audit": "ps -ef | grep $kubeletbin | grep -- --cni-conf-dir | sed 's%.*cni-conf-dir[= ]\\([^ ]*\\).*%\\1%' | xargs -I{} find {} -mindepth 1 | xargs --no-run-if-empty stat -c %U:%G\nfind /var/lib/cni/networks -type f 2> /dev/null | xargs --no-run-if-empty stat -c %U:%G\n",
        "audit_config": "",
        "test_info": [
          "Run the below command (based on the file location on your system) on the control plane node.\nFor example,\nchown root:root <path/to/cni/files>\n"
        ],
        "commands": null,
        "config_commands": null,
        "actual_value_per_node": {
          "priyanodeprov124": "Usage: grep [OPTION]... PATTERN [FILE]...\nTry 'grep --help' for more information."
        },
        "expected_result": "'root:root' is present",
        "test_type": "",
        "scored": false
      },
```
- There is no PKI dir on RKE clusters and checks 1.1.20 and 1.1.21 should be modified similar to what was done in 1.7 RKE permissive profile. Valid commands are: 
  1.1.20: find /node/etc/kubernetes/ssl/  -name '*.pem' ! -name '*key.pem' | xargs stat -c permissions=%a
  1.1.21: find /node/etc/kubernetes/ssl/ -name '*key.pem' | xargs stat -c permissions=%a

**RKE1 Hardened:** (Note: Check 4.1.7 below is a known file permission issue)
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=OneNote.File>
<meta name=Generator content="Microsoft OneNote 15">
</head>

<body lang=en-US style='font-family:Calibri;font-size:11.0pt'>

<div style='direction:ltr'>

State | Number | Description
-- | -- | --
Fail | 4.1.4 | If proxy kubeconfig   file exists ensure ownership is set to root:root (Automated)
Fail | 4.1.7 | Ensure that the   certificate authorities file permissions are set to 600 or more restrictive   (Automated)

</div>

</body>

</html>

```
NOTE: I executed the command manually for check 4.1.4 on the hardened node and the actual output did match the expected result:

ubuntu@ip-XXX-XX-XX-XXX:~$ /bin/sh -c 'if test -e /etc/kubernetes/ssl/kubecfg-kube-proxy.yaml; then stat -c %U:%G /etc/kubernetes/ssl/kubecfg-kube-proxy.yaml; fi' 
root:root
```
**Note:**
- Previously with Chart **4.2.0-rc5**,
  - RKE1 Permissive cluster: ALL checks passed
  - RKE1 Hardened cluster: 4.1.7 was the only failed check which was due to a known file permission issue: https://github.com/rancher/rancher/issues/42140
- Should "[$proxykubeconfig](https://github.com/rancher/security-scan/blob/master/package/cfg/rke-cis-1.24-permissive/node.yaml#L41C42-L41C57)" be replaced with "/node$proxykubeconfig" in the node.yaml for these issues to get resolved?
- CIS Scan Results: 
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=OneNote.File>
<meta name=Generator content="Microsoft OneNote 15">
</head>

<body lang=en-US style='font-family:Calibri;font-size:11.0pt'>

<div style='direction:ltr'>

  | Total | Pass | Fail | Warn | NA
-- | -- | -- | -- | -- | --
RKE Permissive | 125 | 56 | 2 | 34 | 33
RKE Hardened | 113 | 62 | 2 | 28 | 21

</div>

</body>

</html>

CC @andypitcher @JonCrowther

**Comment by andypitcher** [comment]
[ci-benchmark-4.2.0-rc7](https://github.com/rancher/charts/pull/2960) fixes this issue (tag: [security-scan:v0.2.13-rc8](https://github.com/rancher/security-scan/releases/tag/v0.2.13-rc8)) and is now available. @Priyashetty17 Could you make your tests, and close this issue if all scans outcome are as expected ?

**Comment by Priyashetty17** [comment]
@andypitcher Reopening this issue as checks **4.1.3, 4.1.5 and 4.1.6** are failing on the RKE1 hardened cluster because of an extra **/node** in the audit command for these checks:
<img width="1236" alt="image" src="https://github.com/rancher/rancher/assets/42880103/937405c7-b383-4a2e-993e-02a9814665a0">

**Note**: Check 4.1.7 below is a known file permission issue

**Check 4.1.3:**
  ```
    {
        "id": "4.1.3",
        "description": "If proxy kubeconfig file exists ensure permissions are set to 600 or more restrictive (Automated)",
        "remediation": "Run the below command (based on the file location on your system) on the each worker node.\nFor example,\nchmod 600 /node/etc/kubernetes/ssl/kubecfg-kube-proxy.yaml\n",
        "state": "fail",
        "node_type": [
          "node"
        ],
        "audit": "/bin/sh -c 'if test -e /node/node/etc/kubernetes/ssl/kubecfg-kube-proxy.yaml; then stat -c permissions=%a /node/node/etc/kubernetes/ssl/kubecfg-kube-proxy.yaml; fi' ",
        "audit_config": "",
        "test_info": [
          "Run the below command (based on the file location on your system) on the each worker node.\nFor example,\nchmod 600 /node/etc/kubernetes/ssl/kubecfg-kube-proxy.yaml\n"
        ],
        "commands": null,
        "config_commands": null,
        "actual_value_per_node": {
          "ip-172-31-6-190": ""
        },
        "expected_result": "'permissions' is present",
        "test_type": "",
        "scored": true
      },
```
**Checks 4.1.5 and 4.1.6:**
```
{
        "id": "4.1.5",
        "description": "Ensure that the --kubeconfig kubelet.conf file permissions are set to 600 or more restrictive (Automated)",
        "remediation": "Run the below command (based on the file location on your system) on the each worker node.\nFor example,\nchmod 600 /node/etc/kubernetes/ssl/kubecfg-kube-node.yaml\n",
        "state": "fail",
        "node_type": [
          "node"
        ],
        "audit": "/bin/sh -c 'if test -e /node/node/etc/kubernetes/ssl/kubecfg-kube-node.yaml; then stat -c permissions=%a /node/node/etc/kubernetes/ssl/kubecfg-kube-node.yaml; fi' ",
        "audit_config": "",
        "test_info": [
          "Run the below command (based on the file location on your system) on the each worker node.\nFor example,\nchmod 600 /node/etc/kubernetes/ssl/kubecfg-kube-node.yaml\n"
        ],
        "commands": null,
        "config_commands": null,
        "actual_value_per_node": {
          "ip-172-31-6-190": ""
        },
        "expected_result": "'permissions' is present",
        "test_type": "",
        "scored": true
      },
      {
        "id": "4.1.6",
        "description": "Ensure that the --kubeconfig kubelet.conf file ownership is set to root:root (Automated)",
        "remediation": "Run the below command (based on the file location on your system) on the each worker node.\nFor example,\nchown root:root /node/etc/kubernetes/ssl/kubecfg-kube-node.yaml\n",
        "state": "fail",
        "node_type": [
          "node"
        ],
        "audit": "/bin/sh -c 'if test -e /node/node/etc/kubernetes/ssl/kubecfg-kube-node.yaml; then stat -c %U:%G /node/node/etc/kubernetes/ssl/kubecfg-kube-node.yaml; fi' ",
        "audit_config": "",
        "test_info": [
          "Run the below command (based on the file location on your system) on the each worker node.\nFor example,\nchown root:root /node/etc/kubernetes/ssl/kubecfg-kube-node.yaml\n"
        ],
        "commands": null,
        "config_commands": null,
        "actual_value_per_node": {
          "ip-172-31-6-190": ""
        },
        "expected_result": "'root:root' is present",
        "test_type": "",
        "scored": true
      },
```

**Comment by Priyashetty17** [comment]
@andypitcher I see the [same issue](https://github.com/rancher/rancher/issues/42655#issuecomment-1712257221) with **1.7 RKE1 hardened and permissive profiles** as well.

<img width="1208" alt="image" src="https://github.com/rancher/rancher/assets/42880103/4462877a-e5e1-4e99-b45a-245dfbd517a2">

<img width="1258" alt="image" src="https://github.com/rancher/rancher/assets/42880103/4e80f799-068c-4425-b5de-3529288c2a54">


**Note**: Previously with 4.2.0-rc6 chart - for 1.7 profiles, ALL checks passed on RKE1 permissive cluster and check 4.1.7 (known file permission issue) was the only check that failed on RKE1 hardened cluster

**Comment by andypitcher** [comment]
@Priyashetty17 @samjustus  a new chart `4.2.0-rc8` is ready which embeds `security-scan:v0.2.13-rc9`. This fixes the two issues:
- https://github.com/rancher/rancher/issues/42725
- https://github.com/rancher/rancher/issues/42655
