### ISSUE TITLE
[agent-instance] Get real user ip

### ISSUE THREAD

**Issue by Negashev** [rancher/rancher#4265]
Rancher Version: 0.63.1

Docker Version: 1.7-1.10

OS: CentOS 6-7

Steps to Reproduce: N/A

Results: N/A

Expected:How i can get real ip from Load Balancer in new nginx container?

**Comment by vincent99** [comment]
HTTP (not TCP) listener + the `X-Forwarded-For` header?

**Comment by Negashev** [comment]
@vincent99 Yes HTTP

![screenshot 73](https://cloud.githubusercontent.com/assets/4653589/14219598/9d9d4e2c-f874-11e5-9eae-67abb0aaf590.png)


and add to `server{...}` in nginx



```
set_real_ip_from 10.42.0.0/24;
real_ip_header X-Forwarded-For;
```

after in log i write `$remote_addr` - It's right?

```
log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';
```

**Comment by Negashev** [comment]
I sorry ):

with key `$http_x_forwarded_for` all work

@vincent99 Thank for information, about `http`
