### ISSUE TITLE
[TESTING] Add full end-to-end tests for Rancher Machine CLI

### ISSUE THREAD

**Issue by bfbachmann** [rancher/rancher#42665]
Currently, the only tests for Rancher Machine that we have running in our CI are a few for specific drivers: https://github.com/rancher/machine/blob/6a9ad26c86089f0a5a289f9ab498de5ebb09de11/scripts/test#L8. The obvious consequence here is that it's very easy to break Rancher Machine's CLI and not realize it.

We should create a test suite that we can use to easily invoke the CLI and check that it exhibits the correct behaviour. Ideally, we can simply copy CLI commands into the test suite and add some assertions without having to write a bunch of code to do setup, teardown, and mocking.

**Comment by thaneunsoo** [comment]
@bfbachmann could you give a reason for QA/None?

**Comment by bfbachmann** [comment]
Yikes! Sorry I totally forgot to fill that part out. There's a second PR for this going into Rancher soon, and I figured it would make most sense to test this via Rancher when I merge the second PR. It's kinda tricky and not super useful to test this on its own – it kinda requires the Rancher change.
