### ISSUE TITLE
Front-End UI Issue

### ISSUE THREAD

**Issue by Chenpipi** [rancher/rancher#4266]
_Describe your issue here_
I found a front-end UI Issue, the following can not scroll the page to follow the drop-down bar. 
Browser chrome, Such as the following:
![1](https://cloud.githubusercontent.com/assets/9670781/14211946/3129495a-f863-11e5-950c-e1ca62743ad3.png)

---

| Useful | Info |
| :-- | :-- |
| Versions | Rancher `v1.0.0` Cattle: `v0.159.2` UI: `v0.100.3` |
| Access | `localauth` `admin` |
| Route | `splash` |

**Comment by tfiduccia** [comment]
@Chenpipi - I am unable to reproduce this.  Can you please let me know if this happens every time you create a new environment or was it just the first time you setup v1.0?

**Comment by Chenpipi** [comment]
@tfiduccia -- Not the first time there will be set up, but sometimes appear, and two computers have suffered this problem.
When I add a host will appear, when I chose on the third step of：
![1](https://cloud.githubusercontent.com/assets/9670781/14224739/6a2f4198-f8d9-11e5-9511-db6fed92118e.png)

**Comment by tfiduccia** [comment]
@Chenpipi 

There have been some changes to the footer since 1.0.0.  Have you upgraded to newer version and are you still seeing this problem?
