### ISSUE TITLE
[RFE] communication method between Cluster Controller and Cluster Agent 

### ISSUE THREAD

**Issue by wujiandong217** [rancher/rancher#42693]
May I ask about the communication method between Cluster Controller and Cluster Agent in Rancher version 2.7, and what is the network latency tolerance for their communication method.

**Comment by gabrielaomoraes** [comment]
@wujiandong217 I think this article in the [docs](https://ranchermanager.docs.rancher.com/reference-guides/rancher-manager-architecture/communicating-with-downstream-user-clusters) will help you.
