### ISSUE TITLE
[BUG] Fresh installation of Rancher using developer codebase gives me NotReady Helm Operation Pods

### ISSUE THREAD

**Issue by rohitsakala** [rancher/rancher#42704]
Deploy Rancher from release/v2.8 as developer debug mode and go to localhost -> Pods.

<img width="1456" alt="Screenshot 2023-09-07 at 1 27 27 PM" src="https://github.com/rancher/rancher/assets/8402361/2c3bb8e2-4460-4a72-9663-33327c90fb32">

**Comment by diogoasouza** [comment]
Upon further investigation, this appears to be a problem when using a cluster created by rancher desktop using the moby (docker cli) runtime. I tested it with containerd and the issue did not happen and I also tested it in a cluster created using k3s without rancher desktop, with both containerd and moby and there was no issue as wel.

I created a issue in the rancher desktop github https://github.com/rancher-sandbox/rancher-desktop/issues/5534

**Comment by rohitsakala** [comment]
Closing this issue since it seems like it is an issue on Rancher Desktop. Will reopen if there is anything from Mapps side of things.
