### ISSUE TITLE
[BUG][CAPR] rancher-provisioning-capi-patch-sa job failing due to lack of exclusion from PSA enforcement

### ISSUE THREAD

**Issue by thaneunsoo** [rancher/rancher#42719]
**Rancher Server Setup**
- Rancher version: v2.7-head 787c056
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):

**Information about the Cluster**
- Kubernetes version: v1.26.7+rke2r1
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):
AWS node driver

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Admin

**Describe the bug**

Downstream cluster is unable to provision and cluster is stuck at `waiting for viable init node`. I don't see the machines getting created on the AWS portal and the latest log message is `Creating server [fleet-default/auto-aws-kkswl-pool0-01d54a4c-4kr6x] of kind (Amazonec2Machine) for machine auto-aws-kkswl-pool0-74f9b78f74xcl6q9-fjnch in infrastructure provider`

**To Reproduce**

1. Provision RKE2 AWS node driver cluster

**Result**
Cluster gets stuck while provisioning with the status `waiting for viable init node`

**Expected Result**

Cluster is able to provision successfully

**Screenshots**

<img width="1027" alt="image" src="https://github.com/rancher/rancher/assets/108360907/22a5b865-967c-4192-b757-ee1c4b57c3e6">

**Comment by slickwarren** [comment]
This is not resolved for us. 
We looked into our automation and nothing looks out of the ordinary.  Here's what we know:
* this only fails for rke1 local clusters (rke2 on the same 1.26.7 k8s version deploys just fine)
* if you manually set the `rancher-provisioning-capi-patch-sa` 's namespace to enforce:psa:privileged and the `cattle-fleet-local-system` to enforce:psa:privileged , both `rancher-provisioning-capi-patch-sa` job and the fleet-agent job are successful
* without doing this, the cluster never resolves and is basically unusable

**Comment by slickwarren** [comment]
tested versions:
(Tim): v2.7.7-rc4
Caleb: v2.7-head and v2.8-head

**Comment by aiyengar2** [comment]
I would suspect that the issue here is that changes that were made to introduce the new CAPI chart may not have been coordinated with changes to [FeatureAppNS list](https://github.com/rancher/rancher/blob/c4b9091cba60ef1402688fb246a880272bf6a921/pkg/data/management/podadmissionconfigurationtemplate_data.go#L12-L33), which should track all feature chart / system namespaces to exclude PSA enforcements from them.

`cattle-fleet-local-system` and `cattle-provisioning-capi-system` (the [CAPI Provisioning Namespace](https://github.com/rancher/rancher/blob/c4b9091cba60ef1402688fb246a880272bf6a921/pkg/namespace/namespace_utils.go#L15) that is set as the [chart's release namespace](https://github.com/rancher/rancher/blob/c4b9091cba60ef1402688fb246a880272bf6a921/pkg/controllers/dashboard/systemcharts/controller.go#L174) do not appear to be in this list, so the fix should simply be to add those namespaces to the list.

**Comment by slickwarren** [comment]
using [these namspaces](cattle-provisioning-capi-system) in the pod security configuration, I was able to resolve the issue for fleet. It appears that `cattle-provisioning-capi-system` is missing from this list though.

**Comment by thaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.7-head 1d25044
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: RKE2 node driver cluster

----------

### Testing: ###
Tested this issue with the following steps:
1. Provision RKE2 AWS node driver cluster

**Result**
The job no longer fails but the cluster still isn't able to come up.
<img width="1017" alt="image" src="https://github.com/rancher/rancher/assets/108360907/e02b9e1a-18af-4a11-8760-5ab39275e32f">

@Oats87 Should I close this ticket now that the job isn't faililng and open a different issue? The cluster went to delete after about 5 minutes and is now just stuck in deleting
<img width="1022" alt="image" src="https://github.com/rancher/rancher/assets/108360907/dd8a4627-9359-43f4-a7bb-47aa7153a0f9">
<img width="637" alt="image" src="https://github.com/rancher/rancher/assets/108360907/f854dd9f-fddf-4d1f-85a8-e55450699e22">

**Comment by thaneunsoo** [comment]
My bad @Oats87 this was an issue with our jenkins job which was fixed here https://github.com/rancher/rancher/pull/42743

Closing this issue as fixed.
