### ISSUE TITLE
Cannot upgrade a Stack's restart policy from `Never (Start Once)` to `Always`

### ISSUE THREAD

**Issue by ragaar** [rancher/rancher#4273]
It isn't really relevant but the parent container looks like this:

> ```
> ovpn:
>   ports:
>   - 1194:1194/udp
>   labels:
>     io.rancher.sidekicks: ovpn-genconfig,ovpn-data,ovpn-initpki
>   image: kylemanna/openvpn
>   volumes_from:
>   - ovpn-genconfig
>   - ovpn-data
>   - ovpn-initpki
>   cap_add:
>   - NET_ADMIN
> ```

Steps to recreate:
1. Create a stack with multiple sidekicks, define the primary service as `never (start once)`
2. Launch the stack
3. Navigate to the container view for the stack ```<rancher url>/apps/1e18/services/1s12/containers```
4. Select the `upgrade` option
5. Change the restart behavior of the primary service to `always`
6. Finalize the change by clicking [upgrade]

The upgrade finished, but the restart policy did not change.
I double checked the Labels tab to make sure no labels were defined.

---
`Rancher`
> v0.59.1

`Cattle`
> v0.148.1

`User Interface`
> v0.90.0

`Rancher Compose`
> v0.7.2

`docker info`
> Server Version: 1.9.1
> Storage Driver: btrfs
> Build Version: Btrfs v3.17
> Library Version: 101
> Execution Driver: native-0.2
> Logging Driver: json-file
> Kernel Version: 3.16.0-4-amd64
> Operating System: Debian GNU/Linux 8 (jessie)

**Comment by vincent99** [comment]
This was fixed in 1.0 (https://github.com/rancher/rancher/issues/3707)
