### ISSUE TITLE
[RFE] Deprecate Weave CNI plugin from rke

### ISSUE THREAD

**Issue by manuelbuil** [rancher/rancher#42730]
**Is your feature request related to a problem? Please describe.**

It was agreed to deprecate Weave in rke 1.27 for different reasons:
1 - Weave has not released a new version since Jan 2021
2 - Weave is not supported in rke2/k3s, i.e. no migration path
3 - Apparently, no customer is really using weave CNI plugin

**Describe the solution you'd like**

A message stating that Weave is deprecated in 1.27, 1.28 and 1.29. Weave will be removed in 1.30

**Describe alternatives you've considered**

**Additional context**

- This is issue was already tracked in https://github.com/rancher/rke/issues/3338, but I learnt that rke1 issues must be raised in this repo for consolidation.
- This is coordinating with UI by using JIRA https://jira.suse.com/browse/SURE-6793 and https://github.com/rancher/dashboard/issues/9556

**Comment by thaneunsoo** [comment]
This issue was validated and closed in [3338](https://github.com/rancher/rke/issues/3338)
