### ISSUE TITLE
[BUG] Upon upgrading to 2.7.6, uuid-unmigration can enter "Failure" state silently

### ISSUE THREAD

**Issue by nflynt** [rancher/rancher#42734]
**Rancher Server Setup**
- Rancher version: v2.7.6
- Installation option (Docker install/Helm Chart): Direct Code Observation

**Describe the bug**
We observed cases where the uuid-unmigration script enters a "Failed" status but never writes any reason to the Rancher log. Digging through the relevant code, I found at least one location where a sub-task returns an error that is never sent to logrus:

https://github.com/rancher/rancher/blob/release/v2.8/pkg/agent/clean/adunmigration/migrate.go#L271

This warrants a deeper analysis, so this issue will cover any such cases that arise.

**To Reproduce**
Reproduction steps are currently unclear, as this issue was discovered while browsing the code, and we don't have access to the affected environments to troubleshoot in depth. Based on my understanding however, I suspect a situation which permits reading the AuthConfig but not **changing** the AuthConfig may produce this error.

**Result**
In Rancher logs, this output from the unmigration script in the `rancher` pod:
```
[INFO] [migrate-ad-user] beginning ad-guid unmigration
```
Followed by this configmap:
```
kubectl get -n cattle-system cm ad-guid-migration -o yaml
apiVersion: v1
data:
ad-guid-migration-status: Failed
kind: ConfigMap
metadata:
labels:
cattle.io/creator: norman
name: ad-guid-migration
namespace: cattle-system
```

**Expected Result**
In case of failure, details should _always_ be logged.

**Additional Context**
There are several factors external to the unmigration logic that can cause a failure to occur, especially if RBAC is having a rough time of things, so _merely_ having entered a "Failed" status is not necessarily a problem with the logic. Doing so _silently_ is what we're trying to correct.

**Comment by nickwsuse** [comment]
`Validated on 2.7-head ID: ea796f0`

After many attempts to reproduce this, it seems that this is actually maybe not possible to reproduce in any sort of **valid** AD auth setup in Rancher. That said, I did run a few regression checks (listed below) and everything is still working perfectly fine. 

Test Cases:
1. Upgrade from 2.7.4 -> 2.7.5 -> 2.7-head | Duplicate users removed
2. Upgrade from 2.7.4 -> 2.7.5 -> 2.7-head | GUID users are back to DN
3. Fresh install of 2.7-head | Configmap is created
4. Fresh install of 2.7-head | Restarting Rancher pod with configmap doesn't re-run un-migration
5. Enabling other auth providers not causing issues with configmap/un-migration not being re-run
