### ISSUE TITLE
storagepool not removed

### ISSUE THREAD

**Issue by hwinkel** [rancher/rancher#4274]
Rancher Version: 1.0.0

Docker Version: 1.10.3

OS: ubuntu 14.04

Steps to Reproduce: add a convoy NFS stack. Fail to configure as the NFS Server was not ready yet. remove the Convoy NFS stack.

Results: the state of stack remains very long in "removing" after removing the service and containers from the host the storage pool remains in "storagepoolas" even after the system stack convoy NFS is removed

Expected: The Storagepool gets removed

**Comment by deniseschannon** [comment]
We still need to implement the ability to delete storage pools.

https://github.com/rancher/rancher/issues/2918

**Comment by guruvan** [comment]
A workaround until this is implemented would be most helpful - for those who have attempted creating a convoy storage pool, in many or most cases it's failed, and the only apparent solution is to recreate the environment.

**Comment by deniseschannon** [comment]
@hwinkel I'll close in favor of #2918
