### ISSUE TITLE
No stats for vm

### ISSUE THREAD

**Issue by eebjr** [rancher/rancher#4275]
*Describe your issue here*

I just did a custom add for three VMs, running Docker 1.10.3. The host OS is Ubuntu 14.04. 

After I add the host, by cutting-n-pasting from the Custom Add page, the host shows up in Rancher. 

The only problem I'm seeing is that the stats for these VMs don't show up in the Rancher UI.  Graphs are just blank. 

I see logs like this from the ranger agent:
I0402 12:06:56.085551 11768 container.go:430] Failed to update stats for container "/docker/44a3ab12eb04df32d67aa765946679204c79fa49d1839a3b555d68047a42e039": stat failed on /var/lib/docker/aufs/diff/44a3ab12eb04df32d67aa765946679204c79fa49d1839a3b555d68047a42e039 with error: no such file or directory, continuing to push stats
time="2016-04-02T12:07:09Z" level="error" msg="Couldn't find container for id." error="token is expired" id=""
time="2016-04-02T12:07:23Z" level="error" msg="Couldn't find container for id." error="token is expired" id=""
time="2016-04-02T12:07:38Z" level="error" msg="Couldn't find container for id." error="token is expired" id=""
time="2016-04-02T12:07:54Z" level="error" msg="Couldn't find container for id." error="token is expired" id=""

Please, advise. 

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v0.63.1` Cattle: `v0.155.1` UI: `v0.95.0` |
|Access|`localauth` `admin`|
|Route|`hosts.index`|no

**Comment by deniseschannon** [comment]
Fixed in v1.0.0.

https://github.com/rancher/rancher/issues/3384
