### ISSUE TITLE
mirror rancher metadata into consul kv

### ISSUE THREAD

**Issue by jippi** [rancher/rancher#4276]
Would be very useful to be able to use consul / consul-template with rancher

Consul Template have some very consul specific features, which i depend on, and thus preventing me from using conf.d which integrate with rancher-metadata directly

see https://twitter.com/ibuildthecloud/status/716327258302980096

**Comment by ekristen** [comment]
+1

**Comment by pasikarkkainen** [comment]
Agreed, automatically syncing rancher stacks/services/containers to consul would be nice..

**Comment by jippi** [comment]
not relevant any more :)
