### ISSUE TITLE
[flaky-test] Failed to connect to bus: Host is down

### ISSUE THREAD

**Issue by nicholasSUSE** [rancher/rancher#42761]
**Flaky Test**

- I have made a previous PR with the same changes to `release/v2.8` it passed the Drone Build: https://github.com/rancher/rancher/pull/42753
- Now I have made a second PR with the same changes but for `release/v2.7`: https://github.com/rancher/rancher/pull/42750
- These PRs are just removing Flaky Python Tests

I got the following error:

First error message: `Failed to connect to bus: Host is down`
Pipeline stage: `default-linux-amd64`

[Drone Build](https://drone-pr.rancher.io/rancher/rancher/32711/5/2)

I have seen this before sometimes, is kind of random.
Normally when I re-run the test the error vanishes, however, this has been happening over and over again.

**Release Branch**: `release/v2.7`

@rancher/qa-automation 
@bmdepesa 
@igomez06 
@caliskanugur 
@floatingman 
@nataliefyi

**Comment by bmdepesa** [comment]
@nicholasSUSE why is TOU specifically assigned to this issue? What needs to be done from our side?

**Comment by nicholasSUSE** [comment]
This issue is already been fixed and I wrongly assigned you guys, I am sorry for that.
