### ISSUE TITLE
[flaky-test] [v2prov] [release/v2.7] Etcd restoration provisioning tests collecting/printing test data bundles when they are not actually failing

### ISSUE THREAD

**Issue by Oats87** [rancher/rancher#42778]
**Flaky Test**

```
Test_Operation_MP_EtcdSnapshotCreationRestoreInPlace
Test_Operation_MP_EtcdSnapshotOperationsWithThreeEtcdNodesOnNewNode
Test_Operation_MP_EtcdSnapshotOperationsOnNewNode
Test_Operation_Custom_EtcdSnapshotCreationRestoreInPlace
Test_Operation_Custom_EtcdSnapshotOperationsOnNewCombinedNode
Test_Operation_Custom_EtcdSnapshotOperationsOnNewNode
```

**Release Branch**

source branch of PR: `release/v2.7`

The tests are printing test data bundles and failure messages even though they are not actually failing. Furthermore, they are printing `\n` which is not useful.

**Comment by nicholasSUSE** [comment]
Hello @Oats87 

Can you confirm to me if this issue is also regarding this kind of Drone Build Failure:
```
--- FAIL: Test_Operation_Custom_EtcdSnapshotOperationsOnNewNode (1151.63s)
FAIL
FAIL	github.com/rancher/rancher/tests/v2prov/tests/custom	3044.249s
```

https://drone-pr.rancher.io/rancher/rancher/32876/4/2

**Comment by snasovich** [comment]
@nicholasSUSE , nope. If a test actually reports FAIL it's indeed failing.

I see `Test_Operation_Custom_EtcdSnapshotOperationsOnNewNode` mentioned as intermittently failing before but I don't see `flaky-test` issue filed for it (it was before we established flaky-test processes). If you have a build where it failed please file `flaky-test` issue - https://github.com/rancher/rancher/issues/new?assignees=&labels=kind%2Fflaky-test&projects=&template=flaky-tests.md&title=%5Bflaky-test%5D

**Comment by snasovich** [comment]
@Oats87 , just reran CI on https://github.com/rancher/rancher/pull/42779. Please also create PR for `release/v2.8` as well.

**Comment by jiaqiluo** [comment]
The following two cases failed in https://drone-publish.rancher.io/rancher/rancher/10741/4/2
- Test_Operation_MP_EtcdSnapshotCreationRestoreInPlace
- Test_Provisioning_Custom_ThreeNode
