### ISSUE TITLE
[BUG] Update DynamicSchema generation to use `.metadata.Name` rather than `.spec.DisplayName` for Dynamic Schema Generation

### ISSUE THREAD

**Issue by thatmidwesterncoder** [rancher/rancher#42784]
**Rancher Server Setup**
- Rancher version: v2.8 head
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): n/a
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: n/a
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:
admin

**Describe the bug**
As per https://github.com/rancher/webhook/pull/277, the node drivers should be using the `.metadata.Name` field and not the `.spec.DisplayName` field to create the dynamic schemas. 

By using the display name it can result in conflicts on lookup and/or deletion. This was already handled on the webhook side in that PR as far as validation on deletion/disabling goes.

**To Reproduce**
https://github.com/rancher/rancher/issues/42378

**Result**
Nothing as of right now since out of tree drivers aren't working - but once they are this would be an issue if the display names matched and the CRDs failed to get created. 

**Expected Result**

We can create N number of dynamic schemas and voila everything works as expected. 

**Screenshots**

n/a

**Additional context**

Fix will go here per Jake: 
https://github.com/rancher/rancher/blob/HEAD/pkg/controllers/management/drivers/nodedriver/machine_driver.go#L105-L110

**Comment by snasovich** [comment]
This is the same (or a part of) https://github.com/rancher/rancher/issues/42378 essentially.
