### ISSUE TITLE
Rancher Websockets do not work with Caddy as a reverse proxy

### ISSUE THREAD

**Issue by 5an1ty** [rancher/rancher#4278]
I am using Caddy (https://github.com/mholt/caddy) as a reverse proxy in front of Rancher and I'm having issue with one of the websocket connections:

```
Connect socket for 1a5
socket.js:32 Socket connect 1 to wss://myhost/v1/subscribe...
socket.js:8 WebSocket connection to 'wss://myhost/v1/subscribe?eventNames=resource.change&eventNa…s&include=instance&include=instanceLinks&include=ipAddresses&projectId=1a5' failed: Error during WebSocket handshake: 'Upgrade' header is missing
socket.js:145 Socket 1 error
socket.js:145 Socket 1 disconnect
socket.js:113 Socket closed
socket.js:32 Socket connect 2 to wss://myhost/v1/containerstats...
socket.js:145 Socket 2 opened
socket.js:32 Socket connect 3 to wss://myhost/v1/hoststats...
socket.js:145 Socket 3 opened
```

As you can see some websocket connections work but the one starting with v1/subscribe always fails.

This is my caddyfile:

```
https://myhost {
	proxy / x.x.x.x:8080 {
		proxy_header Host {host}
		proxy_header X-Real-IP {remote}
		proxy_header X-Forwarded-Proto {scheme}
		proxy_header X-Forwarded-Port 443
		proxy_header Sec-Websocket-Key {>Sec-Websocket-Key}
		proxy_header Sec-Websocket-Extensions {>Sec-Websocket-Extensions}
		proxy_header Sec-Websocket-Version {>Sec-Websocket-Version}
		proxy_header Connection {>Connection}
		proxy_header Upgrade {>Upgrade}
	}
	tls email@email.email
	errors stdout
}
```

Reverse proxying does work with nginx as seen in the rancher guide:
http://docs.rancher.com/rancher/installing-rancher/installing-server/basic-ssl-config/

And going directly to the rancher IP also works as expected.

This might be an issue with either Caddy or Rancher, but I believe Caddy is doing it's job correctly if you look at what I see after doing a tcpdump from within the rancher server container:

```
GET /v1/subscribe?eventNames=resource.change&eventNames=service.kubernetes.change&include=hosts&include=services&include=instances&include=instance&include=instanceLinks&include=ipAddresses&projectId=1a5 HTTP/1.1
Host: myhost
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8,nl;q=0.6
Cache-Control: no-cache
Connection: Upgrade
Cookie: __cfduid=d2579964f06b1d551b96ab514e85fdd4b1459276863; PL=rancher; token=inserttokenhere; CSRF=insertcsrfhere
Origin: https://myhost
Pragma: no-cache
Sec-Websocket-Extensions: permessage-deflate; client_max_window_bits
Sec-Websocket-Key: insertkeyhere
Sec-Websocket-Version: 13
Upgrade: websocket
X-Forwarded-For: x.x.x.x (my public ip)
X-Forwarded-Port: 443
X-Forwarded-Proto: https
X-Real-Ip: x.x.x.x (my public ip)
```

I blanked out some things but as you can see I think all the needed headers are there right?

I'd like to understand what's going on and why this doesn't work while it seems it should.

**Comment by 5an1ty** [comment]
This seems to be the response from within the rancher container in tcpdump:

```
HTTP/1.1 101 Switching Protocols
Date: Sat, 02 Apr 2016 19:23:56 GMT
X-API-Schemas: https://myhost/v1/schemas
X-API-ACCOUNT-ID: insertaccountid
X-API-Client-IP: x.x.x.x (my public ip)
Set-Cookie: CSRF=insertCSRFhere;Path=/
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Connection: Upgrade
Sec-WebSocket-Accept: insertacceptcodehere
Upgrade: WebSocket
Content-Type: text/plain
```

**Comment by 5an1ty** [comment]
Problem solved in the pull request I created for caddy. Caddy expected full lowercase "websocket" in upgrade headers, this is correct according to the spec (https://en.wikipedia.org/wiki/HTTP/1.1_Upgrade_header).

@vincent99 
Rancher should probably change this for their v1/subscribe websocket...

You can add Caddy as an option as a supported ssl termination endpoint for Rancher. A config like this should work:

```
https://your.domain {
	proxy / x.x.x.x:8080 {
		proxy_header Host {host}
		proxy_header X-Real-IP {remote}
		proxy_header X-Forwarded-Proto {scheme}
		proxy_header X-Forwarded-Port 443
		proxy_header Sec-Websocket-Key {>Sec-Websocket-Key}
		proxy_header Sec-Websocket-Extensions {>Sec-Websocket-Extensions}
		proxy_header Sec-Websocket-Version {>Sec-Websocket-Version}
		proxy_header Connection {>Connection}
		proxy_header Upgrade {>Upgrade}
	}
	tls your@email
	errors stdout
}
```

**Comment by vincent99** [comment]
We can change it anyway but Wikipedia is not a spec.  Caddy is clearly wrong here.

http://tools.ietf.org/html/rfc6455#section-4.2.1

> 3.   An |Upgrade| header field containing the value "websocket",
>        treated as an ASCII case-insensitive value.

**Comment by 5an1ty** [comment]
@vincent99 You're absolutely right, sorry for the wikipedia reference, should have looked at the real spec.

**Comment by vincent99** [comment]
Or maybe we can't easily... It's in Jetty: https://github.com/eclipse/jetty.project/blob/ac24196b0d341534793308d585161381d5bca4ac/jetty-websocket/websocket-server/src/main/java/org/eclipse/jetty/websocket/server/HandshakeRFC6455.java#L49

**Comment by SoreGums** [comment]
according to the linked spec - "case-insensitive value" - so actually Caddy just needed to be tweaked, which it has been, hence why nginx "just worked".
