### ISSUE TITLE
Simple Stuff - how to trigger a service upgrade 

### ISSUE THREAD

**Issue by mikepc** [rancher/rancher#4279]
I'm really looking for a simple example on how to wire up a webhook to trigger a service upgrade.

When a container is built on Quay.io, I'd like to execute the rancher api to build my dev service automatically.

While the documentation is quite detailed, it would be very helpful to have a simple guide on how to do this exact task, as I'm sure many of us Tutum refugees would find useful.

So the work flow will be Code -> Check-in -> Quay -> [need help here ]-> Rancher -> Profit.

My old workflow was Code -> Check-In -> Quay -> Tutm via Webhook -> Profit

**Comment by deniseschannon** [comment]
I believe you are looking for this feature to be implemented:

https://github.com/rancher/rancher/issues/619

**Comment by deniseschannon** [comment]
Please re-open if the issue that I referenced is not what you are looking for.

**Comment by hernandev** [comment]
made a quick script on a docker image do do the job from my ci
https://github.com/codecasts/rancher-deployer
