### ISSUE TITLE
Can't run runcher server v1.0.1

### ISSUE THREAD

**Issue by ivan-exness** [rancher/rancher#4281]
I want to run rancher in HA setup. Followed by march 2016 meetup 
[https://www.youtube.com/watch?v=hwhxXwT6zlw](url)

Steps to Reproduce: 
```
➜  ~ docker run -d --restart=always -p 8080:8080 rancher/server:v1.0.1
```
Results: 
```
Unable to find image 'rancher/server:v1.0.1' locally
Pulling repository docker.io/rancher/server
docker: Tag v1.0.1 not found in repository docker.io/rancher/server.

```
Expected:

**Comment by baryshev** [comment]
Rancher v1.0.1 still not released. You can monitor progress here: https://github.com/rancher/rancher/milestones/Release%201.0.1

**Comment by deniseschannon** [comment]
@ivan-exness Rancher 1.0.1 is not released, you can follow the announcements category in our [forums](https://forums.rancher.com/c/announcements) and get an email whenever we release a new version.
