### ISSUE TITLE
CRTB: apiVersion and kind are mandatory in PUT but NOT on POST

### ISSUE THREAD

**Issue by dasarinaidu** [rancher/rancher#42823]
While creating/Updating PRTB : The fields `apiVersion` and `kind` are mandatory in PUT operation but NOT on POST.

Getting 400 error is we did not pass these attributes in PUT.

**Steps:**

1. Provision rancher
2. Create a downstream cluster
3. Create a CRTB with Steve API(v1)
4. Endpoint : PUT : {{URL}}/v1/management.cattle.io.clusterRoleTemplateBinding/{nameSpace/{name}

**Body:**

```
{
  "type": "clusterRoleTemplateBinding",
  "apiVersion": "management.cattle.io/v3",
  "kind": "ClusterRoleTemplateBinding",
  "metadata": {
    "resourceVersion": "62251",
    "namespace": "cccccccccc",
    "name": "dastest3",
    "labels": {
      "hello":"World5"
    }
  },
  "clusterName": "cccccccccc",
  "roleTemplateName": "cluster-member",
  "userPrincipalName": "local://u-cccccc",
  "userName": "u-ccccc"
}
```

**Result:**
1. CRTB is updated if user specify apiVersion and kind fields, Otherwise the fields ar
2. User getting 400 error
```
{
    "type": "error",
    "links": {},
    "code": "BadRequest",
    "message": "the API version in the data () does not match the expected API version (management.cattle.io/v3)",
    "status": 400,
    "type": "error"
}
```

**Expected:**

a. In POST `apiVersion` and `kind` are NOT mandatory, without these fields this method is successful 
b. In PUT these two fields are mandatory and user getting 400 errors. 
c. PUT should not require these two fields as mandatory. PUT method should be successful without these two fields.

SURE-7720

**Comment by gehrkefc** [comment]
I was able to reproduce the error using rancher built with Goland in the main branch.

**Comment by gehrkefc** [comment]
![image](https://github.com/user-attachments/assets/e3bd676e-98bb-4753-8072-ef5da3780545)

**Comment by gehrkefc** [comment]
Seems like this error comes from k8s apiserver:

https://github.com/kubernetes/apiserver/blob/da8e2914b01df0dad8d4612b181bc417ae495a53/pkg/endpoints/handlers/update.go#L132

**Comment by gehrkefc** [comment]
I created an environment for debugging and understand the whole process that happens inside of this. 
My conclusion is that this error comes from k8s apiserver. It's caused by us. [Here](https://github.com/rancher/steve/pull/270) I  created a PR to fix it in steve repo.

Below you can find a step-by-step guide to reproduce that:

## Requirements:

0. Clone main branch of rancher/rancher on your machine.

1. Start a debugging session of rancher/rancher. I suggest [this]() guide using Goland, but of course you can use whatever editor/IDE of your preference.
NOTE: In case you choose Goland, I suggest: please add the k3d part, it's gonna make your life much easier.

2. As soon as rancher starts, please go to [localhost:8443](https://localhost:8443) initialize it and wait for the cluster to become available. 
IMPORTANT: If you've followed the guide, then the password shoud be: 'adminadminadmin'. Othewise, please follow the steps presented in the screen to get
the password.

## Reproducing the error:

Make the request to get a list of Cluster Role Template Bindings

NOTE: Replace the headers by yours. You can get those from Rancher UI running at [localhost:8443](https://localhost:8443), 
just filter by XHR requests in the Network tab of you browser and copy the headers from there. 

I suggest using Insomnia or any other REST client to do these operations.

### Gets a list of CRTBs:

```
curl --request GET \
  --url 'https://localhost:8443/v1/management.cattle.io.clusterRoleTemplateBinding' \
```

### Create a CRTB:

Please replace username by yours, it should be in the list returned by the GET method before.

```
curl --request POST \
  --url 'https://localhost:8443/v1/management.cattle.io.clusterRoleTemplateBinding' \
  --data '{
	"clusterName": "local",
	"kind": "ClusterRoleTemplateBinding",
	"metadata": {
		"namespace": "local",
		"labels": {
			"hello": "World5"
		},
		"name": "testing"
	},
	"roleTemplateName": "cluster-member",
	"userName": "**REPLACE_ME**",
	"userPrincipalName": "system://provisioning/fleet-local/local"
}'
```

As soon as you're able to make this, you can call GET again and you new CRTB should be in the data array returned by that request.

### Updating a CRTB:

In order to update a CRTB you'll have to add a field called 'resourceVersion' to you JSON payloads inside metadata field. 
This can be found at the GET request in your newly created CRTB. You can just copy it from there. From my experience, I can say
everytime you want to update, you'll have to GET it first then grab the resouceVersion and replace it in this payload.

Now with this new information, let's make the request itself:

```
curl --request PUT \
  --url 'https://localhost:8443/v1/management.cattle.io.clusterRoleTemplateBinding/local/testing' \
  --data '{
	"apiVersion": "management.cattle.io/v3",
	"clusterName": "local",
	"kind": "ClusterRoleTemplateBinding",
	"metadata": {
		"namespace": "local",
		"resourceVersion": "**REPLACE_ME**",
		"labels": {
			"hello": "World5",
		},
		"name": "testing"
	},
	"roleTemplateName": "cluster-member",
	"userName": "**REPLACE_ME**",
	"userPrincipalName": "system://provisioning/fleet-local/local"
}'
```

I suggest to you add/replace labels and see those changes again in the GET.

If you notice in the POST payload the 'apiVersion' field is absent and it works. But this doesn't happens in the PUT, so this
confirms this issue is real.

## Following on the code:

1. Here's the point where [steve](https://github.com/rancher/steve) api is initalized within Rancher.

__pkg/rancher/rancher.go__ - line 196
```go
steve, err := steveserver.New(ctx, restConfig, &steveserver.Options{...}
```

2. Going forward it's initialzing api server

** This is in steve, but you can follow it with Goland or your IDE:
__pkg/server/server.go__ (func setup, called by func New before) - line 216
```go
apiServer, handler, err := handler.New(server.RESTConfig, sf, server.authMiddleware, server.next, server.router)
```

3. Then it goes for the generic api handler

** This is steve also, but the same applies here:
__pkg/server/handler/apiserver.go__ (func apiHandler called by New) - line 99
```go
a.server.Handle(apiOp)
```

4. Adding a breakpoint in here and making a request POST request to the api should give you the path. I'll walk you throught it.
Please use step-into feature in the debugging session to follow it, if you prefer. At the end you'll reach at:

__pkg/stores/proxy/proxy_store.go__ - line 434. This is in the create function. It completes the 'gvk' which stands for Group, Version, Kind in the input object.
```go
gvk := attributes.GVK(schema)
input["apiVersion"], input["kind"] = gvk.ToAPIVersionAndKind()
```

and then at line 448 it sends the input object:
```go
resp, err = k8sClient.Create(apiOp, &unstructured.Unstructured{Object: input}, opts)
```

In the update method it doesn't complete the 'gvk' information. This way, kubernetes api server doens't accept it.

The update method can be found at:
__pkg/stores/proxy/proxy_store.go__ - line 454. 

Adding this same code at line 506 just right after the resourceVersion handling should solve the issue.

**Comment by brudnak** [comment]
<a name="top"></a>

<details>
    <summary>🧪 Test Environment Details... CLICK TO EXPAND! ⬅️</summary>


| Component                        | Version / Type                                     |
| -------------------------------- | -------------------------------------------------- |
| Rancher version starting         | v2.9.2                                             |
| Rancher version upgraded         | v2.9-7ead7f4c4eca65de99836be9c1771ce921ab81db-head |
| Installation option              | Helm (high availability)                           |
| Cert Details                     | external tls `aws acm`                             |
| Docker version                   | 20.10.7, build f0df350                             |
| Authentication providers enabled | local                                              |
| Logged in user role              | admin / standard user                              |
| Browser type                     | Opera GX                                           |
| Browser version                  | LVL6 (core: 113.0.5230.75) (x86_64)                |
| Webhook version                  | rancher/rancher-webhook:v0.4.11                    |

</details>

### 🧪  Test Cases

| \#  | Priority | Description & Link                                | PASS/FAIL |
| --- | -------- | ------------------------------------------------- | --------- |
| 1   | P0       | [Create valid CRTB](#test-1)                      | ✅ PASS    |
| 2   | P0       | [Read valid CRTB](#test-2)                        | ✅ PASS    |
| 3   | P0       | [⭐️(PUT) Update CRTB With apiV & kind](#test-3)    | ✅ PASS    |
| 4   | P0       | [⭐️(PUT) Update CRTB Without apiV & kind](#test-4) | ✅ PASS    |
| 5   | P0       | [Delete valid CRTB](#test-5)                      | ✅ PASS    |
| 6   | P0       | [Run RBAC automated tests](#test-6)               | ✅ PASS    |
| 7   | P0       | [Run RBAC/CRTB automated tests](#test-7)          | ✅ PASS    |
| 8   | P0       | [Upgrade](#test-8)                                | ✅ PASS    |
| 9   | P0       | [(kubectl) Create valid CRTB](#test-9)            | ✅ PASS    |
| 10  | P0       | [(kubectl) Read valid CRTB](#test-10)             | ✅ PASS    |
| 11  | P0       | [(kubectl) Update valid CRTB](#test-11)           | ✅ PASS    |
| 12  | P0       | [(kubectl) Delete valid CRTB](#test-12)           | ✅ PASS    |

<details>
    <summary>🚨 12 test cases... CLICK TO EXPAND! (For table links to work) ⬅️</summary>

<br>

# 1 / Create valid CRTB Status: ✅ PASS 

<a name="test-1"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 1 details... Click to expand</summary>

**Test Steps for Validation**

1. Create a valid CRTB
2. `POST` request to `{{rancherURL}}/v1/management.cattle.io.clusterroletemplatebindings`
3. Body:

    ```json
    {
      "clusterName": "local",
      "metadata": {
        "generateName": "bruno-",
        "namespace": "local"
      },
      "roleTemplateName": "cluster-owner",
      "userPrincipalName": "local://{{createUserID}}"
    }
    ```

4. Ensure that the user has been granted the appropriate permission level

**✅ Expected Outcome**

CRTB to be created and permissions to function as expected

**✅ Actual Outcome**

CRTB created and permission level is working as expected


</details>

<hr>

# 2 / Read valid CRTB Status: ✅ PASS 

<a name="test-2"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 2 details... Click to expand</summary>

**Test Steps for Validation**

1. Send `GET` request to `{{rancherURL}}/v1/management.cattle.io.clusterroletemplatebindings/local/{{crtbName}}`

**✅ Expected Outcome**

Expect the specified CRTB returned 

**✅ Actual Outcome**

The specific CRTB was returned


</details>

<hr> 

# 3 / ⭐️(PUT) Update CRTB With apiV & kind Status: ✅ PASS

<a name="test-3"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 3 details... Click to expand</summary>

**Test Steps for Validation**

1. `PUT` request to `{{rancherURL}}/v1/management.cattle.io.clusterroletemplatebindings/local/{{crtbName}}`
2. Body:

    ```json
    {
      "apiVersion": "management.cattle.io/v3",
      "kind": "ClusterRoleTemplateBinding",
      "clusterName": "local",
      "metadata": {
        "resourceVersion": "{{crtbResVersion}}",
        "namespace": "local",
        "name": "{{crtbName}}",
        "labels": {
          "hello": "dadfish"
        }
      },
      "roleTemplateName": "cluster-owner",
      "userPrincipalName": "local://{{createUserID}}",
      "userName": "{{createUserID}}"
    }
    ```



**✅ Expected Outcome**

`PUT` to succeed

**✅ Actual Outcome**

`PUT` is successful

</details>

<hr>

# 4 / ⭐️(PUT) Update CRTB Without apiV & kind Status: ✅ PASS

<a name="test-4"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 4 details... Click to expand</summary>

**Test Steps for Validation**

1. `PUT` request to `{{rancherURL}}/v1/management.cattle.io.clusterroletemplatebindings/local/{{crtbName}}`
2. Body:

    ```json
    {
      "clusterName": "local",
      "metadata": {
        "resourceVersion": "{{crtbResVersion}}",
        "namespace": "local",
        "name": "{{crtbName}}",
        "labels": {
          "hello": "dadfish"
        }
      },
      "roleTemplateName": "cluster-owner",
      "userPrincipalName": "local://{{createUserID}}",
      "userName": "{{createUserID}}"
    }
    ```



**✅ Expected Outcome**

`PUT` to succeed

**✅ Actual Outcome**

`PUT` is successful

</details>

<hr>

# 5 / Delete valid CRTB Status: ✅ PASS

<a name="test-5"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 5 details... Click to expand</summary>

**Test Steps for Validation**

1. `DELETE` request to `{{rancherURL}}/v1/management.cattle.io.clusterroletemplatebindings/local/{{crtbName}}`
2. Ensure that the user loses the access that the CRTB was granting

**✅ Expected Outcome**

`DELETE` success and for the user to lose the access the CRTB was providing

**✅ Actual Outcome**

CRTB was deleted and the user lost access it was granting

</details>

<hr>

# 6 / Run RBAC automated tests Status: ✅ PASS

<a name="test-6"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 6 details... Click to expand</summary>

**Test Steps for Validation**

1. Run these tests: `https://github.com/rancher/rancher/blob/release/v2.9/tests/v2/validation/rbac/rbac_test.go`

**✅ Expected Outcome**

Expecting a pass

**✅ Actual Outcome**

61 of 61 tests pass 

</details>

<hr>

# 7 / Run RBAC/CRTB automated tests Status: ✅ PASS

<a name="test-7"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 7 details... Click to expand</summary>

**Test Steps for Validation**

1. Run these tests: `https://github.com/rancher/rancher/blob/release/v2.9/tests/v2/validation/rbac/crtb/crtb_create_steve_test.go`


**✅ Expected Outcome**

Expecting a pass

**✅ Actual Outcome**

9 of 9 tests pass

</details>

<hr>

# 8 / Upgrade Status: ✅ PASS
<a name="test-8"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 8 details... Click to expand</summary>

**Test Steps for Validation**

1. Repeat test cases 1 through 9 on an upgraded Rancher

**✅ Expected Outcome**

For all tests to pass

**✅ Actual Outcome**

All tests passing on an upgraded Rancher

</details>

<hr>

# 9 / (kubectl) Create valid CRTB Status: ✅ PASS

<a name="test-9"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 9 details... Click to expand</summary>

**Test Steps for Validation**

1. As an admin, create a downstream cluster.
2. As an admin, create a standard user with the name `user1`.
3. Use `kubectl apply -f` command as an admin to create a CRTB ClusterRoleTemplateBinding for `user1`.
4. Use the following yaml:

    ```yaml
    apiVersion: management.cattle.io/v3
    clusterName: c-xxxxx # replace with your cluster name
    kind: ClusterRoleTemplateBinding
    metadata:
      namespace: c-xxxxx # replace with your cluster name
      name: cluster-owner
    roleTemplateName: cluster-owner
    userName: u-xxxxx # replace with your standard user id
    userPrincipalName: local://u-xxxxx # replace with your standard user id
    ```

5. Execute `kubectl apply -f` command again as an admin.
6. Log into the Rancher UI as `user1`.
7. Verify that `user1` has cluster owner access to the downstream cluster.
8.  Create a deployment in the default namespace, check the logs, and then delete the deployment.
    

#### ✅ Expected Outcome

Access was anticipated to be granted successfully.

#### ✅ Actual Outcome

As expected, access was granted successfully.


</details>

<hr>

# 10 / (kubectl) Read valid CRTB Status: ✅ PASS

<a name="test-10"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 10 details... Click to expand</summary>

**Test Steps for Validation**

1. After creating the CRTB with kubectl ensure that you can get/read it
2. Run: `kubectl get clusterroletemplatebindings cluster-owner -n c-m-rhmwsvc5 -o yaml`

**✅ Expected Outcome**

Expect to get the yaml output of the CRTB that was previously created

**✅ Actual Outcome**

Getting the expected CRTB yaml output

</details>

<hr>

# 11 / (kubectl) Update valid CRTB Status: ✅ PASS

<a name="test-1"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 11 details... Click to expand</summary>

**Test Steps for Validation**

1. As an admin, instantiate a downstream cluster.
2. Using the admin account, establish a standard user, hereby referred to as `user1`.
3. With the `kubectl apply -f` command, create a CRTB ClusterRoleTemplateBinding for `user1`.
4. Utilize the below yaml:

    ```yaml
    apiVersion: management.cattle.io/v3
    clusterName: c-xxxxx # Replace with your cluster name
    kind: ClusterRoleTemplateBinding
    metadata:
      namespace: c-xxxxx # Replace with your cluster name
      name: cluster-owner
    roleTemplateName: cluster-owner
    userName: u-xxxxx # Replace with your standard user id
    userPrincipalName: local://u-xxxxx # Replace with your standard user id
    ```

5. Run the `kubectl apply -f` command once more as an admin.
6. Access the Rancher UI by logging in as `user1`.
7. Ensure that `user1` possesses cluster owner access to the downstream cluster.
8.  Generate a deployment in the default namespace, inspect the logs, and subsequently delete the deployment.
9.  Proceed to edit the previously created CRTB.
10. Use `kubectl edit clusterroletemplatebinding cluster-owner -n c-qg584`.
11. Introduce a label `env: prod`.

    ```yaml
    apiVersion: management.cattle.io/v3
    clusterName: c-xxxxx # Replace with your cluster name
    kind: ClusterRoleTemplateBinding
    metadata:
      namespace: c-xxxxx # Replace with your cluster name
      name: cluster-owner
      labels:
        env: prod
    roleTemplateName: cluster-owner
    userName: u-xxxxx # Replace with your standard user id
    userPrincipalName: local://u-xxxxx # Replace with your standard user id
    ```

12. Save the changes using `:wq`.
13. Validate that the save was successful and the added label persists.

**✅ Expected Outcome**

**✅ Actual Outcome**


</details>

<hr>

# 12 / (kubectl) Delete valid CRTB Status: ✅ PASS

<a name="test-12"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 12 details... Click to expand</summary>

**Test Steps for Validation**

1. Utilize kubectl to remove the CRTB: `kubectl delete clusterroletemplatebinding cluster-owner -n c-m-rhmwsvc5`.
2. Proceed to log into the Rancher UI as `user1`.
3. Validate that `user1` no longer has the previously granted permissions.

**✅ Expected Outcome**

`user1` should have lost permissions to the downstream cluster, as intended.

**✅ Actual Outcome**

As anticipated, `user1` has lost permissions to the downstream cluster.

</details>

<hr>

</details>
