### ISSUE TITLE
CRTB created with a non existing user from rancher, it causes UI is broken 

### ISSUE THREAD

**Issue by dasarinaidu** [rancher/rancher#42822]
Create crtb with steve api(v1) OR kubectl by passing non-existing user, the CRTB is created without checking userName. After that on UI : Cluster and Project Members page is not rendering. 

Seeing 404 errors on the network call for the users not existed in the rancher.

**Steps:**

1. Provision rancher
2. Create a downstream cluster
3. Create a CRTB with Steve API(v1)
       Endpoint : {{URL}}/v1/management.cattle.io.clusterroletemplatebindings
       Make sure to provide userName as non-existing userID in the rancher
       Method : POST

Body:

```
{
  "type": "clusterRoleTemplateBinding",
  "apiVersion": "management.cattle.io/v3",
  "kind": "ClusterRoleTemplateBinding",
  "metadata": {
    "namespace": "c-m-ms8hj4zb",
    "name": "dastest12",
    "labels": {
      "hello":"World"
    }
  },
  "clusterName": "c-m-ms8hj4zb",
  "roleTemplateName": "cluster-owner",
   "userName": "u-drrexv73"
}
```

**Result:**
1. CRTB is created successfully 
2. Not checking that the passing userName is existed in the system or not
3. From UI navigate to Cluster->Cluster and Project Members->Cluster members page : This page is not rendering , UI is blank. Seeing 404 errors in the network call
4. Same issue happening when user create crtb with kubectl also
5. System not validating the values for `userName` and `userPrincipalName` fields and creating crtbs. These fields are immutable.
6. LOG contains the errors 
`[ERROR] Unknown error: users.management.cattle.io "u-mxdgn" not found`

**Expected:**
1. While creating CRTB system should validate the input values for `userName` and `userPrincipalName` and create CRTBs
2. UI should not broken, UI should display all the cluster members associated to the cluster

![image](https://github.com/rancher/rancher/assets/22034884/ca66bcbe-17a8-407b-8185-2ce1c0020367)

**Comment by JonCrowther** [comment]
The UI breaks when you create a CRTB that has a userName that does not exist. It fails to load any of the Cluster Memberships under the "Cluster and Project Members" tab:
![Screenshot 2023-09-15 at 3 42 01 PM](https://github.com/rancher/rancher/assets/9119124/81ce4e99-ab62-496e-9689-0c1b21d45634)

Deleting it makes the other roles reappear immediately:
![Screenshot 2023-09-15 at 3 42 29 PM](https://github.com/rancher/rancher/assets/9119124/a0d2e95d-34a3-4c44-8c96-c7d797039dc7)

If you provide a non-existent userPrincipalName, it is able to render that:
![Screenshot 2023-09-15 at 3 46 55 PM](https://github.com/rancher/rancher/assets/9119124/7c392ad5-d28e-42cb-82a7-66d3514cb160)

Interestingly the same issue is not present with PRTBs in the Project Membership tab when you create a PRTB with a non-existent userName:
![image](https://github.com/rancher/rancher/assets/9119124/077f4692-ee6c-4b79-bd0a-a5dab34fba61)


--- 

Steps to reproduce:
1. Create a Cluster Role Template in the Users & Authentication tab
2. Open a kubectl shell for your local cluster
3. Apply the following CRTB via `kubectl apply -f crtb.yaml`
```
apiVersion: management.cattle.io/v3
kind: ClusterRoleTemplateBinding
metadata:
  name: test-crtb
  namespace: local
clusterName: local
roleTemplateName: <clusterRoleTemplate.Name>
userName: fake-user
```
4. Go to the "Cluster and Project Members" tab and see that the list of Cluster Memberships won't populate

**Comment by JonCrowther** [comment]
It is acceptable functionality to allow users to create CRTBs with userNames that don't exist in the system. Similar to kubernetes RBAC, there is no restriction requiring a user to exist to bind permissions to it. An admin should be able to create a full set of role bindings and then create the user after that.

We don't need to change the UI to allow creation of CRTBs with non-existent userNames, but doing so through the public API shouldn't cause the UI to break.
