### ISSUE TITLE
"Connection reset by peer" error in Docker CLI

### ISSUE THREAD

**Issue by npcode** [rancher/rancher#4282]
Rancher Version: 1.0.0

Docker Version: 1.10.3

OS: CentOS 7

Steps to Reproduce: 

1. Create a swarm envinronment
1. Go SWARM > CLI
2. Type `docker ps` and press enter

Results: 

An error occurred trying to connect: Get http://docker:2375/v1.22/containers/json: read tcp 10.42.89.13:55438->10.42.252.111:2375: read: connection reset by peer

Expected:

Console shows docker containers

**Comment by npcode** [comment]
It seems to occur under a specific condition but I coudn't find it yet.

**Comment by npcode** [comment]
11.22.89.13 is the ip of swarm agent and 11.22.252.111 is the ip of swarm manager.

I sent a GET message to 11.22.252.111:2375 and it produced same error:
```
root@163d6f575d4e:/# curl -v http://11.22.252.111:2375
* Rebuilt URL to: http://11.22.252.111:2375/
*   Trying 11.22.252.111...
* Connected to 11.22.252.111 (11.22.252.111) port 2375 (#0)
> GET / HTTP/1.1
> Host: 11.22.252.111:2375
> User-Agent: curl/7.43.0
> Accept: */*
>
* Recv failure: Connection reset by peer
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer
```

**Comment by deniseschannon** [comment]
@npcode We are re-doing swarm in v1.2.0 with a new catalog entry and one that leverages Docker 1.12 swarm. If you still have issues with the new swarm after 1.2.0 is released, please open a new issue.
