### ISSUE TITLE
Load Balancer TCP stickiness

### ISSUE THREAD

**Issue by zean00** [rancher/rancher#4283]
I tried to add a load balancer for my app server which include websocket / socket.io that serve mobile client, when I set it to http mode, the app server got intermittent problem, sometimes the client is unable to perform request (didn't get the reply), but with the tcp mode, everything seems fine / normal except the socket.io / websocket, since there are no stickiness for the tcp. 

So, I tried to add the stickiness manually by editing haproxy.cfg directly in a container with below line

  balance roundrobin
  stick-table type ip size 200k expire 30m
  stick on src

And it's work, the app server run as expected. But the problem is when I restart the container, the configuration will be reverted to the previous one, all the new configuration is reverted back. 

Is there any way to add the stickiness property for tcp mode, or at least keep the haproxy.cfg being rewritten after container restart?

---
|Versions|Rancher `v1.0.0` Cattle: `v0.159.2` UI: `v0.100.3` |

**Comment by deniseschannon** [comment]
This should be covered in our issue that is refactoring the load balancer. It would add the ability  to define custom parameters for haproxy backends.

https://github.com/rancher/rancher/issues/2179

Please let me know if that issue woudln't cover your use case

**Comment by zean00** [comment]
Yes, I think the referenced issue will cover my needs . thank you
