### ISSUE TITLE
[RFE] Cloud Credentials API should validate the data provided to create a credential just like the UI

### ISSUE THREAD

**Issue by valaparthvi** [rancher/rancher#42842]
**Is your feature request related to a problem? Please describe.**
Rancher API does not validate the data provided to create a credential while creating a resource. The validation works well on the UI and I expected the same from API, but I was able to create a google cloud credential with all kind of invalid/missing key/expired credential data.

**Describe the solution you'd like**

API must throw an error when the given data is invalid, and not allow to create a resource, just the way UI does.

**Describe alternatives you've considered**

Alternatively, API could provide an endpoint to validate a given credential.

**Additional context**
Sample invalid data:
```json
{
  "type": "service_account",
  "project_id": "test-project-qa",
  "private_key_id": "abcdefghi0123456789jklmnop",
  "private_key": "-----BEGIN PRIVATE KEY-----\nsomeprivatekey\n\nsominvalidprivatekey\n-----END PRIVATE KEY-----\n",
  "client_email": "test-example@test-project-qa.iam.gserviceaccount.com",
  "client_id": "01234567890",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/test-example%40test-project-qa.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}
```
UI:
![Screenshot from 2023-09-18 12-28-33](https://github.com/rancher/rancher/assets/11015077/19872402-0cc6-49f9-bdf8-d9530e691551)

PS: Let me know if this is not the right place for this issue, I'll recreate it at the appropriate place.

**Comment by Leddy-92** [comment]
@valaparthvi Hello, if you don't mind could you let me know you solved this trouble? I faced exactly the same problem now. Thank you.

**Comment by Leddy-92** [comment]
@valaparthvi Oh, sorry my bad. I missed some configs. Ignore it. Thank you.

**Comment by vatsalparekh** [comment]
This is still an issue
