### ISSUE TITLE
Force IPv4 DNS lookups until IPv6 is supported

### ISSUE THREAD

**Issue by jangrewe** [rancher/rancher#4288]
Rancher Version: 1.0

Docker Version: 1.10.3

OS: Debian jessie

Steps to Reproduce: Add host with full IPv6 stack and AAAA records

Results: Same as #1946

Expected: Everythings runs smoothly just like with 0.59

Could you please force DNS lookups to IPv4 until IPv6 is supported? I wasn't able to get my host to run any stacks until i explicitly changed the Host Registration URL to a non-HTTPS IPv4 URL.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
