### ISSUE TITLE
JIRA Issue SURE-5595

### ISSUE THREAD

**Issue by rohitsakala** [rancher/rancher#42885]
Please look into JIRA issue SURE-5595 for more information

**Comment by l4zy0n3** [comment]
Verified on 2.7.7-rc7 air-gapped cluster k8s 1.26.9
Available istio versions were
v1.17.2
v1.18.2

**Comment by rohitsakala** [comment]
@l4zy0n3

- Expected Result must be 
101.0.0+up1.14.3
102.0.0+up1.15.3
102.1.0+up1.16.3
102.2.0+up1.17.2

Testing Scenario 
Able to install all the following in airgap setup 
101.0.0+up1.14.3
102.0.0+up1.15.3
102.1.0+up1.16.3
102.2.0+up1.17.2

**Comment by rohitsakala** [comment]
Sorry my bad only v1.17.2
v1.18.2 should be available on k8s 1.26. 

Could you test this on 1.24 k8s ?

**Comment by l4zy0n3** [comment]
Tested the following Chart Versions on k8s 1.24
102.3.0+up1.18.2
102.2.0+up1.17.2
102.1.0+up1.16.3
102.0.0+up1.15.3
