### ISSUE TITLE
[RFE] Update kubectl version in shell to support 1.27

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#42903]
**Is your feature request related to a problem? Please describe.**
The kubectl version in shell is behind our supported versions: https://github.com/rancher/shell/blob/master/package/Dockerfile#L9

**Describe the solution you'd like**
Update the kubectl version to 1.26 so we are +/- 1 from latest k8s version.

**Comment by JonCrowther** [comment]
Issue for improving the way rancher handles shell versions in the future:
https://github.com/rancher/rancher/issues/42951

**Comment by tomleb** [comment]
I see that the `kubectl` version on v2.8-head is still the old one (`1.24.16`) as can be seen below: 

```
> kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.16", GitCommit:"51e33fadff13065ae5518db94e84598293965939", GitTreeState:"clean", BuildDate:"2023-07-19T12:26:21Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.6+k3s1", GitCommit:"bd04941a294793ec92e8703d5e5da14107902e88", GitTreeState:"clean", BuildDate:"2023-09-20T23:05:58Z", GoVersion:"go1.20.8", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.24) and server (1.27) exceeds the supported minor version skew of +/-1
```

Does this matter for this issue or do we have a separate one for actually upgrading the shell image in rancher/rancher?

**Comment by JonCrowther** [comment]
@tomleb I believe that `master` is the development branch and is the one we should be referring to. I'm not sure what the `release/v2.8` branch is for, but looking at the history, `master` is the one being updated. I think for this issue having the active branch updated should be good enough.

**Comment by tomleb** [comment]
@JonCrowther My concern was less about the branch name in `rancher/shell` and more about what version is being pinned in `rancher/rancher`. It's fine now anyway because the current latest v2.8-head of `rancher/rancher` [pins the new v0.1.22 shell release](https://github.com/rancher/rancher/blob/446d9f3d77118ef9614b7bfd7866304cc622ba5e/pkg/settings/setting.go#L121). So I have closed this issue as done :+1:

**Comment by maxsokolovsky** [comment]
Looks like this issue isn't done because the 2.8.0 release uses shell 0.1.22, which still uses kubectl 1.26. In fact, there isn't yet a newer shell release that uses kubectl 1.27 at all.

**Comment by tomleb** [comment]
@maxsokolovsky From the description above:

> Update the kubectl version to **1.26** 

We lean on the fact that kubectl will support one version above (so 1.26 will support 1.27)
