### ISSUE TITLE
[BUG]Rancher UI Cluster members and project members random behavior

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#42941]
**Rancher Server Setup**

Rancher Cluster:
Rancher version: 2.7.5
Number of nodes:3
Number of Downstream clusters: 2-3

**Describe the bug**
In Rancher UI, the Cluster and Project Members misbehave for DS clusters. Sometimes there is not information, image1. Sometimes it shows some users(image2), and sometimes it lists other users that are not part of the cluster.

The auth provider is PingId with AzureAD.

**To Reproduce**
Log in Rancher using local admin user and pingIdentity user. The behavior is the same. Select a DS cluster and click Cluster and Project Members tab. No users are listed. (image1), a few minutes later, after refreshing the web, somes users appear(image2).

Support was unable to repro in lab

**Result**
Cluster and Project Members misbehaving in Rancher UI

**Expected Result**
The Member and Project members should be listed.

see SURE-6769 for attachments

**Comment by MKlimuszka** [comment]
Closed per original ticket.
