### ISSUE TITLE
[BUG] v2.7.5 can not add new member for cluster and project, it complaints exceed the quota

### ISSUE THREAD

**Issue by linuxerlogic** [rancher/rancher#42956]
**Rancher Server Setup**
- Rancher version:
Rancher	v2.7.5
Dashboard	v2.7.5
Helm	v2.16.8-rancher2
Machine	v0.15.0-rancher100

- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): TKE from Tencent Cloud
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: 1.24.4-tke.7
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

Imported

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:
Admin

**Describe the bug**

When adding Cluster Membership, it complaints that "clusterroletemplatebindings.management.cattle.io "crtb-d45pq" is forbidden: exceeded quota: tke-default-quota, requested: count/clusterroletemplatebindings.management.cattle.io=1, used: count/clusterroletemplatebindings.management.cattle.io=4, limited: count/clusterroletemplatebindings.management.cattle.io=4"

I double check the resourequota for clusterroletemplatebindings.management.cattle.io, the output is 0 for used and hard:
> kubectl get clusterroletemplatebindings.management.cattle.io -A
NAMESPACE      NAME                               AGE
c-m-n8qctplx   c-m-n8qctplx-fleet-default-owner   42d
c-m-n8qctplx   creator-cluster-owner              42d
c-m-n8qctplx   creator-rt-n2z9b                   42d
c-m-n8qctplx   u-uwehxd4kdp-admin                 42d
local          local-fleet-local-owner            126d
local          u-b4qkhsnliz-admin                 126d
> kubectl get clusterroletemplatebindings.management.cattle.io -A|grep crtb-4l7wr
> kubectl describe resourcequotas tke-default-quota |grep clusterroletemplatebindings.management.cattle.io
count/clusterroletemplatebindings.management.cattle.io               0     0
> 

So what's wrong? clusterroletemplatebindings.management.cattle.io "crtb-d45pq" is forbidden. It's so strange that  "crtb-d45pq" for resource clusterroletemplatebindings.management.cattle.io can not be found in all namespaces.

What adding membership for project, it will report similar error: 
{ "baseType": "error", "code": "Forbidden", "message": "projectroletemplatebindings.management.cattle.io \"prtb-mvfpl\" is forbidden: exceeded quota: tke-default-quota, requested: count/projectroletemplatebindings.management.cattle.io=1, used: count/projectroletemplatebindings.management.cattle.io=2, limited: count/projectroletemplatebindings.management.cattle.io=2", "status": 403, "type": "error" }

The resource quota for resourcequotas tke-default-quota are also 0 both for used and hard.
> kubectl describe resourcequotas tke-default-quota |grep projectroletemplatebindings.management.cattle.io
count/projectroletemplatebindings.management.cattle.io               0     0
> 

What the hell are these ?

**To Reproduce**

Explore one cluster from dashboard, the click Cluster and Project Members -> Cluster Membership -> Add, seach a user provided by openLdap and click create. It will report error above

**Result**

**Expected Result**

The membership should can be created for cluster and project normally.

**Screenshots**

**Additional context**

![error2](https://github.com/rancher/rancher/assets/50649445/bffc8aa2-34a9-4d25-9472-10fd3b116ea8)
![error1](https://github.com/rancher/rancher/assets/50649445/a0361fc6-b160-4312-8dc4-81212d858d0d)
![error4](https://github.com/rancher/rancher/assets/50649445/3401d13e-5603-4d19-ba68-149beb2a32d7)
![error5](https://github.com/rancher/rancher/assets/50649445/3d8a162e-ee44-4f9c-bccd-5dfd9c938bbf)
![error3](https://github.com/rancher/rancher/assets/50649445/ee5c3e13-699b-4c4c-905e-56c033072517)

**Comment by linuxerlogic** [comment]
The scrennshots are shows as 
![error4](https://github.com/rancher/rancher/assets/50649445/62686b6a-c8ea-4426-9161-a4d189d9cf51)
![error2](https://github.com/rancher/rancher/assets/50649445/8362a45e-2e8d-4f6e-bdfc-b39dec915dd1)
![error3](https://github.com/rancher/rancher/assets/50649445/a907ac49-6707-41e3-a42b-aeb0a494a3fb)
![error1](https://github.com/rancher/rancher/assets/50649445/010a1346-3e94-429c-bcce-439008ff53be)
below

**Comment by linuxerlogic** [comment]
Sorry, the root cause is the limitations from TKE platform, which can't shown from kubectl get or describe. The problem is solved. So close the issue and sorry for the trouble caused.

**Comment by 594872799** [comment]
> Sorry, the root cause is the limitations from TKE platform, which can't shown from kubectl get or describe. The problem is solved. So close the issue and sorry for the trouble caused.

please tell me how to solved?

**Comment by likku123** [comment]
+1
