### ISSUE TITLE
CLI menu item goes to Error page

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4295]
Version - master 4/5

Steps to Reproduce: 
1.  Create a Swarm environment
2.  Click on CLI before swarm sets up

Results:  Error page

Expected:  The menu items should not be available until after Swarm environment is setup.  This should work the same as Kubernetes.

**Comment by vincent99** [comment]
Header redesign..

**Comment by vincent99** [comment]
The Swarm (and K8s) menu should now have no sub-items if the service is not ready and the loading page would fail.

**Comment by tfiduccia** [comment]
Version - master 5/5
Verified fixed
