### ISSUE TITLE
[BUG] Remove reference to "NamespacedRules" field in "kubectl explain globalroles"

### ISSUE THREAD

**Issue by Priyashetty17** [rancher/rancher#42965]
**Rancher Server Setup**
- Rancher version: v2.8-5cffa891781908dcbe2c6bb8be2084b362e2ff00-head
- Installation option (Docker install/Helm Chart): Helm chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE

**Information about the Cluster**
- Kubernetes version: v1.27.5
- Cluster Type (Local/Downstream): Local

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Admin

**Describe the bug**
In Global roles v2, "NamespacedRules" field isn't implemented yet. We need to remove the reference to "NamespacedRules" from the documentation for "kubectl explain globalroles" to avoid confusion. 

**To Reproduce**

1. Execute "kubectl explain globalroles" command.

**Result**
```
   inheritedClusterRoles	<[]string>
     InheritedClusterRoles are the names of RoleTemplates whose permissions are
     granted by this GlobalRole in every cluster besides the local cluster. To
     grant permissions in the local cluster, use the Rules or NamespacedRules
     fields.
```
**Expected Result**
The documentation for "kubectl explain globalroles" should not include a reference to the "**NamespacedRules**" field.

cc @MbolotSuse

**Comment by MbolotSuse** [comment]
## Validation Template

## Root Cause

The description referred to a field which did not exist.

## What was fixed, or what change have occurred

The description has been updated to no longer refer to the missing field.

## Areas or cases that should be tested

The explain output noted in the issue.

## What areas could experience regressions

The explain output.
## Are the repro steps accurate/minimal?

**Comment by Priyashetty17** [comment]
Verified with **v2.8-c55d3344dc46525a860c712f868f1b7ab1826b1b-head**. "kubectl explain globalroles" no longer references the "NamespacedRules" field.

```
   inheritedClusterRoles	<[]string>
     InheritedClusterRoles are the names of RoleTemplates whose permissions are
     granted by this GlobalRole in every cluster besides the local cluster. To
     grant permissions in the local cluster, use the Rules field.
```
