### ISSUE TITLE
[BUG] Race Condition issue in dynamic listener

### ISSUE THREAD

**Issue by vardhaman22** [rancher/rancher#42961]
there is a race condition in cert generation process in rancher/dynamiclistener. Because of that rancher CI is failing when we include latest dynamiclistener in rancher, but it it working fine with k3s.
So that issue needs to be fixed and a new tag for dynamiclistener is needed so that dynamiclistener versions can be kept in sync in k3s and rancher.

**Comment by Sahota1225** [comment]
Since the PR is merged, moving the issue to test.

**Comment by vardhaman22** [comment]
the Ci passed for rancher PR.
@brandond @felipe-colussi do we need any additional testing for this ?
Please advise.

**Comment by felipe-colussi** [comment]
@vardhaman22  I think that the PR test is enough.
That said I do prefer being on the safe side. I would: 

Startup a new rancher, create a downstream cluster. 
Restart rancher, and check if the certificate that is being used is the same and if the downstream cluster can communicate with the upstream one.

**Comment by vivek-shilimkar** [comment]
Validated the issue on rancher v2.8.0-alpha2 created with docker and HA as well.
The certificate that is being used is the same even after restarting the rancher and downstream cluster can communicate with the upstream one. 

Hence closing the issue.
