### ISSUE TITLE
Change text for Step 2 of Local Auth

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4296]
Version - master 04/05

Steps to Reproduce: 
1. Go to Access Control page
2. Select Local icon

Results: The step two says "There is not Step 2"
![image](https://cloud.githubusercontent.com/assets/11514927/14295793/ecad3568-fb2b-11e5-8683-83c3a31aae17.png)

Expected: Change to "Enable Authentication"

**Comment by vincent99** [comment]
-1

**Comment by tfiduccia** [comment]
Version - v1.0.1-rc1
Verified fixed
