### ISSUE TITLE
Upgrading text moves buttons and menus to second line in stack details page

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4297]
Version - master 4.05

Steps to Reproduce: 
1.   Add a catalog that will have an upgrade
2.   After active go to stacks detail page and click on upgrade
3.   Upgrade stack

Results: The upgrade message moves all the buttons and menus to second line with text
![image](https://cloud.githubusercontent.com/assets/11514927/14296008/f7e12e5c-fb2c-11e5-926f-1af2e2cc3be7.png)

Expected: Prefer only messages moves to second line?  or maybe just the message and the menu on the right.

**Comment by lvuch** [comment]
https://github.com/rancher/ui/pull/721

**Comment by tfiduccia** [comment]
Version - master 6/13
Verified fixed
