### ISSUE TITLE
Long Environment names causes problems with drop-down and manage environment page

### ISSUE THREAD

**Issue by agalpin** [rancher/rancher#4298]
Rancher Version: 0.59.1

Docker Version: 1.10.3

OS: Ubuntu (Server), Windows 10 (Client)

Browser: Chrome 49.0.2623.110 m

Steps to Reproduce: 
1) Create 9+ Environments, some with names that will be truncated in the drop down list.
2) Select/Activate one of the longer names

Results: 
"Manage Environments" can't be accessed as you can no longer scroll enough to see it.

Expected:
Able to select "Manage Environments"

Could be solved by fixing the CSS or making a separate button near the drop down instead.

**Comment by tfiduccia** [comment]
Verison - master 4.05
This is reproducible.  We should either:
1.  Truncate environment name sooner so you can see list properly or:
2.  Make Environment name a set fixed length (or maybe both)
![image](https://cloud.githubusercontent.com/assets/11514927/14298850/08cdd0e4-fb3c-11e5-9046-67c59d5168fd.png)

While you're there fixing... when you have long names it actually messes up the manage environments page as well.  It overwrites the description & orchestration.
![image](https://cloud.githubusercontent.com/assets/11514927/14298864/2a556632-fb3c-11e5-8ec1-d87daf149875.png)

**Comment by lvuch** [comment]
resolved in https://github.com/rancher/ui/pull/578

**Comment by tfiduccia** [comment]
Version - v1.0.1-rc1
All the above are fixed.  But I missed reporting one.
Drop-down in environment details page:
![image](https://cloud.githubusercontent.com/assets/11514927/14363896/425a7080-fcbb-11e5-8560-2dc32512d466.png)

**Comment by tfiduccia** [comment]
Version - master 5/5
This was fixed at some point. So I'm closing
Verified fixed
