### ISSUE TITLE
Can't upgrade chart at v1.28.2+rke2r1 cluster

### ISSUE THREAD

**Issue by dusatvoj** [rancher/rancher#42988]
**Rancher Server Setup**
- Rancher version: 2.7.5
- Installation option (Docker install/Helm Chart): helm chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): v1.28.2+rke2r1
- Proxy/Cert Details: N/A

**Information about the Cluster**
- Kubernetes version: v1.28.2+rke2r1
- Cluster Type (Local/Downstream): local
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Custom

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Admin
  - If custom, define the set of permissions:

**Describe the bug**
When I did upgrade to v1.28.2+rke2r1, I can't upgrade (and maybe install, didn't tested) helm chart `rancher rancher-latest/rancher` at version 2.7.6 due to error:
```
Error: UPGRADE FAILED: chart requires kubeVersion: < 1.27.0-0 which is incompatible with Kubernetes v1.28.2+rke2r1
```

**To Reproduce**
Upgrade RKE2 cluster, try to install / upgrade rancher.

**Result**
Error upgrading (and probably installing)

**Expected Result**
No error, can upgrade, can upgrade downstream cluster to 1.28

**Screenshots**

**Additional context**

**Comment by David-VTUK** [comment]
As the helm message suggests, Rancher is currently not supported running on that version of K8s. 

The support matrix outlines supported versions: https://www.suse.com/suse-rancher/support-matrix/all-supported-versions/rancher-v2-7-6/

**Comment by dusatvoj** [comment]
Ok, so I can't use latest version of your product with another latest version of your product. Wow :grinning: 

Is there a possibility to switch "certified" -> "non certified" but probably working?

I though that this is the reason why you have latest and stable repos for rancher :thinking:

**Comment by loopingz** [comment]
I got tricked by the same issue, updating to latest k8s version to then realized the UI is not compatible officially.

I do think another disclaimer should be set somewhere, I know now that checking the support matrix is needed before applying updates.

**Comment by K3ndu** [comment]
What you can do to work around this problem is to fork the Helm chart and increase the Helm chart Kubernetes requirement from 1.27 to 1.28 :D
We did this when upgraded the cluster to 1.27 and it was not supported, Rancher worked fine. Haven't tested 1.28 yet.

**Comment by josmo** [comment]
I get the idea of enforcing stable to have limits on where it gets deployed (although I would prefer a note that it's not verified and use at your own risk). Could we at least get "latest" or "alpha" helm repos to remove that restriction? So for folks that are ok running bleeding edge they can without have to fork the chart?

**Comment by tboerger** [comment]
Bleeding edge? 1.27.0 have been released in april... That's not bleading edge anymore, that's getting old in Kubernetes timeframe :D

**Comment by xinity** [comment]
same here still, the 1.26.x branch of kubernetes is now EOS from the kubernetes community as the 1.29 is now out in the wild and still rancher isn't compatible with 1.28 branch ....

Is this product still maintained like it was before ???

**Comment by dusatvoj** [comment]
@xinity I found this stuff ...

https://github.com/rancher/rancher/issues/43109

https://github.com/rancher/rke/issues/3441#issuecomment-1818899432

**Comment by dusatvoj** [comment]
... but true - I'm stuck at RKE2 `v1.28.5+rke2r1` with rancher `2.7.7` and maintained K8s at `1.26.11` ... and still waiting for 1.28 support to upgrade rancher and then managed k8s clusters :upside_down_face: :confused:

**Comment by snasovich** [comment]
> I get the idea of enforcing stable to have limits on where it gets deployed (although I would prefer a note that it's not verified and use at your own risk). Could we at least get "latest" or "alpha" helm repos to remove that restriction? So for folks that are ok running bleeding edge they can without having to fork the chart?

@josmo , like you mentioned there is a rather simple workaround to fork chart however until Rancher officially supports given K8s version we're adding reasonable restrictions to prevent users from using unsupported versions (note since upgrade of local cluster is handled outside of Rancher, it's challenging or even impossible to prevent users from upgrading the cluster Rancher is running on to unsupported version).

K8s 1.28 support is tracked in https://github.com/rancher/rancher/issues/43109, closing this issue.
