### ISSUE TITLE
Hosts/Stacks/Containers temporally swapping environments

### ISSUE THREAD

**Issue by agalpin** [rancher/rancher#4299]
Rancher Version: 0.59.1
Docker Version: 1.10.3
OS: Ubuntu (server), Windows 10 (client)
Browser: Chrome

Steps to Reproduce: 
Not 100% sure on these steps
1) Create a few environments (i have 10)
2) Add a few hosts to each environment
3) sit on hosts page, let access token expire (i think?) (~15-30min)

Results: 
Hosts from other environments temporally appear in the list

Expected:
Only host for that environment appear in the list at all times

i have seen this happen with containers/stacks too.

**Comment by tfiduccia** [comment]
@agalpin - This was previously reported and fixed in v1.0

**Comment by deniseschannon** [comment]
https://github.com/rancher/rancher/issues/3639
