### ISSUE TITLE
[RFE] Add a consistent way to obtain the Rancher-generated Cluster ID within downstream clusters.

### ISSUE THREAD

**Issue by atoy3731** [rancher/rancher#42992]
**Is your feature request related to a problem? Please describe.**
We're developing a tool that is leveraging Rancher oauth, but requires the Rancher-generate cluster ID (ie. `c-m-12345678`) to be available on the downstream clusters to perform appropriate routing back to Rancher for the authentication workflow.

Currently, we have an initContainer checking for the existence of annotations/labels on a number of configMaps/secrets in various places, but it seems inconsistent at best if/when those labels/annotations exist.

**Describe the solution you'd like**
When Rancher provisions a downstream cluster, create a consistent ConfigMap in the `cattle-system` namespace containing the cluster ID.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by dweomer** [comment]
Additionally, per version guidance on reliably sussing this out would also be appreciated.

See https://github.com/rancher-government-carbide/rancher-cluster-id-finder /cc @ebauman

**Comment by dweomer** [comment]
> Additionally, per version guidance on reliably sussing this out would also be appreciated.
> 
> See https://github.com/rancher-government-carbide/rancher-cluster-id-finder /cc @ebauman

As in, a fix moving forward would be fantastic but unless it can be backported, further guidance may be necessary for extant versions/releases as of now.
