### ISSUE TITLE
Merge September 2023 patches from custom branch to dev branch

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#43002]
Tracking issue for merging Sept patches from custom KDM branch `dev-v2.7-2023-09-patches` to `dev-v2.7` (note RKE1 Sept patches went into `release/v1.4` already so that is covered - https://github.com/rancher/rke/pull/3389)

**Comment by vardhaman22** [comment]
done. PR: https://github.com/rancher/kontainer-driver-metadata/pull/1274
