### ISSUE TITLE
search domain is not passed from host to container after upgrade from 0.59 to 1.0.0

### ISSUE THREAD

**Issue by ingardm** [rancher/rancher#4300]
Rancher Version:1.0.0

Docker Version:latest

OS: ubuntu trusty

Steps to Reproduce: deploy new service

Results: search domain is not passed from host to container

Expected:

**Comment by ingardm** [comment]
reported the problem on irc and got reply from vincent:
16:30 <@vincent99> ingard_: Sounds like a bug if the host's search domain isn't passed down

**Comment by alena1108** [comment]
@ingardm I can't reproduce the issue you are seeing, here are the steps - please point if you've done something differently:

1) Created a service "foo" with:
* image ubuntu:trusty
* managed network
* search domains foo.com, bar.com (picked under Networking tab in the UI)
2) Inspect on the container returns following data:

```
"DnsSearch": [
                "foo.com",
                "bar.com",
                "default.rancher.internal",
                "svc.default.rancher.internal",
                "rancher.internal"
            ],

```

3) From inside the container, /etc/resolv.com returns all the domains set:

```
root@747af15f604b:/# cat /etc/resolv.conf
search foo.com bar.com default.rancher.internal svc.default.rancher.internal rancher.internal
nameserver 169.254.169.250
```

**Comment by ingardm** [comment]
Hi
Yes we've done it differently as in we haven't added any search domains, but still found that the containers would have inherited the ones from the host server. That was when we were running 0.59. After upgrading to 1.0 we observed that the containers no longer inherited search domains, but rather that we had to add them to all services separately.

**Comment by alena1108** [comment]
@ingardm thank you, I know what the issue is. Going to work on fixing it

**Comment by alena1108** [comment]
@sangeethah to test the fix, do the following:

Prereq: change /etc/resolv.conf on one of your hosts  by adding "search foo.com bar.com" domain

Case 1
1) Create a regular service in cattle. Don't specify any extra params
2) Login to the container, check /etc/resolv.conf.  Verify it has search domains from the host prepended to the list of rancher domains:

```
search foo.com bar.com ...and list of internal rancher domains
```

Case 2
1) Create a regular service in cattle; specify one custom network search domain (under "networks" tab"
2) Login to the container, check /etc/resolv.conf. Verify that host's search domains are NOT there

We should add host's search domains when user doesn't provide any extra domains for the service

**Comment by sangeethah** [comment]
Tested with rancher-server version - v1.0.1-rc2

Host has search domains -  c.rancher-dev.internal google.internal set.

1. Created as service - test2 under stack-dns2 without passing any network search domain.

container's /etc/resolv.conf has hosts's search domain prepended to the rancher search domains.

```
search c.rancher-dev.internal google.internal dns2.rancher.internal test2.dns2.r
ancher.internal rancher.internal
nameserver 169.254.169.250
```

2. Created as service - test1 under stack-dns2 by passing cusotm network search domain.
container's /etc/resolv.conf has hosts's search domain prepended to the rancher search domains.

```
search hello.com test.com yo.com dns2.rancher.internal test1.dns2.rancher.intern
al rancher.internal
```
