### ISSUE TITLE
Update Documentation to Reflect Support for cert-manager.io/v1

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#43015]
Backend validations for: https://github.com/rancher/rancher-docs/issues/742

See historical examples such as: https://github.com/rancher/rancher/issues/36693

**Comment by PennyScissors** [comment]
According to this [issue](https://github.com/rancher/rancher-docs/issues/511), cert-manager v1.11.0 has already been validated. It is also the recommended option in our documentation [here](https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade/resources/upgrade-cert-manager#option-a-upgrade-cert-manager-with-internet-access) (See Option A, step 7). Therefore, I validated upgrading cert-manager from v1.11.0 to v1.13.1 (latest version as of now) instead, following the steps [here](https://github.com/rancher/rancher/issues/36693#issuecomment-1059621367) with LetsEncrypt certs in Rancher v2.8-fc12e7d779577d10ded1a8e249f51727848b878e-head in a local RKE1 v1.5.0-rc8 cluster. The upgrade was successful, no data was loss and certs remained valid.

**Comment by prachidamle** [comment]
As per offline conversation with @sowmyav27 the steps mentioned here are correct to validate this https://github.com/rancher/rancher/issues/36693#issuecomment-1059621367

@PennyScissors Can you dev-validate it, add the steps and results of your validation and move to-test

**Comment by PennyScissors** [comment]
Steps followed to validate (PASSED):
1. Create RKE1 cluster (v1.5.0-rc8, k8s v1.27.6)
2. Install cert-manager
```
helm install cert-manager jetstack/cert-manager --namespace cert-manager --create-namespace --version v1.11.0 --set installCRDs=true
```
3. Install Rancher using Let's Encrypt (v2.8-alpha2, v2.8-6376016a309a166c50fe6203b2e97dae0b90c89c-head)
```
helm install rancher rancher-alpha/rancher --version 2.8.0-alpha2 --namespace cattle-system --set hostname=$HOSTNAME --set global.cattle.psp.enabled=false --set ingress.tls.source=letsEncrypt --set letsEncrypt.email=$EMAIL --set rancherImageTag=v2.8-head --set bootstrapPassword=admin
```
![image](https://github.com/rancher/rancher/assets/8951271/ecfae74b-7615-48a7-92f9-db52c6b1d4d9)

4. Create downstream RKE1 cluster (v1.27.6+rke2r1) in AWS
5. Create new user "testuser1" with standard user global role
![image](https://github.com/rancher/rancher/assets/8951271/1a3744ad-f49e-4b1b-8469-1e865358cdf8)

6. Create project "testproject1" in downstream cluster and add the newly created user to the project as a project member.
![image](https://github.com/rancher/rancher/assets/8951271/d3ef71c7-faa6-42ab-89cc-adc0b47b1b62)

7. Create a namespace in the project, one with the admin user and another with testuser1
![image](https://github.com/rancher/rancher/assets/8951271/dd1c93d5-7f9c-4daa-af09-41952afd66c7)

8. Uninstall Rancher
```
helm delete rancher -n cattle-system
```
9. Uninstall cert-manager v1.11.0
```
helm delete cert-manager -n cert-manager
kubectl delete -f https://github.com/cert-manager/cert-manager/releases/download/v1.11.0/cert-manager.crds.yaml
```
10. Install new cert-manager version v1.13.1
```
helm install cert-manager jetstack/cert-manager --namespace cert-manager --create-namespace --version v1.13.1 --set installCRDs=true
```
11. Reinstall Rancher (same command as above)
![image](https://github.com/rancher/rancher/assets/8951271/50f795e3-3ba2-452e-becb-33842f17ff2c)

12. Confirm cert remains valid, by going to the Rancher UI and creating a third namespace with testuser1. Confirm that the cluster/project/user data was not lost during the upgrade.
![image](https://github.com/rancher/rancher/assets/8951271/6cf5cd19-26fc-4869-9a24-389c4b57e4cb)

**Comment by ronhorton** [comment]
**Pass** verified `cert-manager 1.13.1`
rancher docker install v2.8.0-alpha2

1. created ubuntu with docker
2. installed helm 
3. installed kubectl
4. wget https://github.com/rancher/rke/releases/download/v1.5.0-rc8/rke_linux-amd64 -O rke
5. chmod +x rke
6. sudo mv rke /usr/local/bin/
7. downloaded latest rke & installed
8. created a cluster.yml file
9. rke up the cluster.yml
10. export KUBECONFIG=kube_config_cluster.yml
11. added jetstack repo
12. installed cert-manager v1.11.0 has been deployed successfully!
13. installed rancher 2.8.0-alpha2
14. created route 53 a record
15. logged in to rancher ui
<img width="1169" alt="2023-10-12_15-37-20" src="https://github.com/rancher/rancher/assets/89212856/d24e32f4-38a3-4b26-baba-4996ca4ed4e9">
17. created rke2 cluster v1.27.6+rke2r1
18. creaetd standard user user1
19. created project in ds cluster
20. created namespace in project as admin
21. created namespace in project as user1

![2023-10-12_15-51-32](https://github.com/rancher/rancher/assets/89212856/b9cce28e-2a0b-4c90-8e6d-8b747fa63ff7)

23. uninstalled rancher
24. uninstalled cert cert-manager
25. installed cert-manager v1.13.1
26. installed rancher
27. logged in as user1
28. created new namespace in test-project
<img width="1180" alt="2023-10-12_16-01-35" src="https://github.com/rancher/rancher/assets/89212856/8dbc7a2d-129f-4635-a8e0-52e4510597a6">

**result:**
`tests passed`
`cluster/project/user data was not lost during the upgrade`
