### ISSUE TITLE
Unable to edit load balance certificates.

### ISSUE THREAD

**Issue by curinir** [rancher/rancher#4301]
Rancher Version: 1.0.0
Docker Version: Docker version 1.9.1, build a34a1d5
OS: Ubuntu 14.04.1

Steps to Reproduce: 
- Use Cattle
- Create a load balancer.
- Ensure that it listens to port 80 and port 443, and check the box for SSL
- Set up a main certificate and a bunch of other certificates for different domains.
- Save it and then go and edit the load balancer.

Results: 
The checkmark under port 443 has disappeared, and if you scroll down, you see "There are no SSL listening ports configured."

The SSL termination still works correctly though, I'm just unable to view it or edit it.
If I clone the load balancer, and then check the SSL-box under 443, the certs reappear.

Expected:
I should be able to edit the load balancer certificates.

Notes:
I did try to clone the load balancer config, check the box for "SSL" and then in fact all the old certificates show up in the editable certs section below. But as soon as I click to save it, when I edit the newly cloned load balancer, it also is missing the config section for certs (and the checkmark for SSL).

Version info: <img width="359" alt="version" src="https://cloud.githubusercontent.com/assets/125490/14307860/fe835500-fb86-11e5-8333-4f277a4130e4.png">
Top part of load balancer config:
<img width="944" alt="top" src="https://cloud.githubusercontent.com/assets/125490/14307861/01f326fc-fb87-11e5-8311-3afef3d79182.png">
Bottom part of load balancer config:
<img width="852" alt="bottom" src="https://cloud.githubusercontent.com/assets/125490/14307864/046c8842-fb87-11e5-939b-59245212a044.png">

Cloning load balancer view:
<img width="1517" alt="cloning-loadbalancer" src="https://cloud.githubusercontent.com/assets/125490/14307991/f1afca56-fb87-11e5-865b-39002e451e74.png">
Then checking the "SSL" checkbox under port 443 and scrolling down to certs:
<img width="1385" alt="certs-reappear" src="https://cloud.githubusercontent.com/assets/125490/14308001/fe6ff36a-fb87-11e5-9eab-4e3ca51ca103.png">

**Comment by sven-codeculture** [comment]
Im expricing the same issue on our Server

**Comment by D3CK3R** [comment]
I think this is the same problem as described here: #4165

**Comment by vincent99** [comment]
Yes, this is the same as #4165
