### ISSUE TITLE
[BUG] Azure Gov RKE2 provisioning fails due to request to "westus"

### ISSUE THREAD

**Issue by atoy3731** [rancher/rancher#43024]
**Rancher Server Setup**
- Rancher version: 2.8.0-alpha (required for Azure Cloud Credential fix: https://github.com/rancher/aks-operator/issues/98)
- Installation option (Docker install/Helm Chart): Helm (RKE2)
- Proxy/Cert Details: N/A

**Information about the Cluster**
- Kubernetes version: v1.25.11
- Cluster Type (Local/Downstream): Azure RKE2 Cluster (Failure During Provisioning)

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): admin

**Describe the bug**
The UI/AKS Operator team worked through an issue affecting Azure govcloud creds getting created and have sorted it out, but now I'm seeing an issue at the Create screen for RKE2 on Azure using the  this request looks like it is potentially hardcoded to `westus` and returns `null` when I'm using govcloud creds since it can't access commercial:
```
/meta/aksVMSizesV2?cloudCredentialId=cattle-global-data%3Acc-l7n8x&region=westus
```

If I hit that same endpoint with the same creds and use `usgovvirginia` as the region, it returns.

**To Reproduce**

1. Install Rancher v2.8.0-alpha with this image containing the GovCloud bug fix: mjura/rancher:v2.8.0-alpha1-mj5
2. Create Azure Gov cloud credentials.
3. Try to create an Azure RKE2 cluster using those credentials.

**Result**

**Expected Result**
The Create Cluster UI successfully loads with metadata populated from Azure Gov.

**Screenshots**
The UI stuck in "Loading":
![image](https://github.com/rancher/rancher/assets/5939985/966c36d0-14b7-411a-90e0-78197c1f9e3f)

The javascript console showing all the requests and where it gets stuck:
![image](https://github.com/rancher/rancher/assets/5939985/2f2a8d59-e7f1-43be-8ed6-6c2e1eaf8e3d)

The javascript console showing `null` for the above request:
<img width="1038" alt="Screen Shot 2023-09-30 at 10 46 35 AM" src="https://github.com/rancher/rancher/assets/5939985/256c06c8-af46-47d7-b433-5d99d303532a">

**Additional context**
N/A

**Comment by mjura** [comment]
I did some investigation about this, it seems that this value is harcoded in Rancher UI here
https://github.com/rancher/ui/blob/master/lib/nodes/addon/components/driver-azure/component.js#L462
and it is taken from https://github.com/rancher/ui/blob/master/lib/shared/addon/utils/azure-choices.js

So it seems that this task is for UI team

**Comment by kkaempf** [comment]
ping @gaktive @nwmac

**Comment by gaktive** [comment]
@kkaempf @mbologna is this needed for 2.8.0? or what's the priority? This looks simple but I'd like to know more since code freeze is days away.

**Comment by mantis-toboggan-md** [comment]
As this is RKE2 the relevant code is in rancher/dashboard. In rke2 the region options are not hardcoded, they're fetched from `/v1/meta/aksLocations` ...assuming the list we get from that request is accurate when using azure gov credentials, the ui fix would require us to update the hardcoded default region [here](https://github.com/rancher/dashboard/blob/master/shell/machine-config/azure.vue#L95) and hardcoded default node pool configuration [here](https://github.com/rancher/dashboard/blob/master/shell/machine-config/azure.vue#L37) to use a location returned from the api call [here](https://github.com/rancher/dashboard/blob/master/shell/machine-config/azure.vue#L159)

**Comment by kkaempf** [comment]
> @kkaempf @mbologna is this needed for 2.8.0? or what's the priority?

I don't have more information than what's in SURE-5437.
For (business) priority, maybe @davidstauffer can help ?

**Comment by atoy3731** [comment]
Talked to folks on the federal side, we're comfortable with this not making it in 2.8.0, as long as we can expect it within Q1 of next year. Hope that helps!

**Comment by gaktive** [comment]
UI has a solution in https://github.com/rancher/dashboard/pull/10472 that's in QA's hands. Removing the awaiting-ui label so this should unblock whichever team can take this.

**Comment by mjura** [comment]
@atoy3731 can you please help us with testing this ?

**Comment by atoy3731** [comment]
> @atoy3731 can you please help us with testing this ?

Hey Michal,

I've validated this change/fix works. I was able to provision clusters through the UI onto AzureGov.

LGTM.

**Comment by kkaempf** [comment]
closing as done, thanks all !
