### ISSUE TITLE
[BUG] CIS benchmark chart 5.0.0-rc3 fails to install on upgraded Rancher server

### ISSUE THREAD

**Issue by Priyashetty17** [rancher/rancher#43021]
**Rancher Server Setup**
- Rancher version: 	Upgraded from v2.7.6 to v2.8-436f4de405dece4b03d1a8e059d9bad35db37cea-head
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1 

**Information about the Cluster**
- Kubernetes version:v1.26.7
- CIS chart version: 5.0.0.rc3
- Cluster Type (Local/Downstream): Local

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Admin

**Describe the bug**
Attempting to install the CIS benchmark chart 5.0.0-rc3 on a Rancher server that was upgraded from v2.7.6 to v2.8-head fails with the following error:
```
{
    "type": "error",
    "links": {},
    "code": "ServerError",
    "message": "failed to find chartName rancher-cis-benchmark-crd version 5.0.0-rc3: NotFound 404",
    "status": 500,
    "type": "error"
}

```
**Steps to reproduce:**

1. Create a Rancher server - v2.7.6
2. Upgrade Rancher server from v2.7.6 to v2.8-head
3. Install CIS benchmark chart - 5.0.0-rc3

**Issue**:
	CIS chart fails to install with the following error: 
	{
	    "type": "error",
	    "links": {},
	    "code": "ServerError",
	    "message": "failed to find chartName rancher-cis-benchmark-crd version 5.0.0-rc3: NotFound 404",
	    "status": 500,
	    "type": "error"
}

Snippet from the Rancher log:
`2023/09/29 21:58:11 [ERROR] Unknown error: failed to find chartName rancher-cis-benchmark-crd version 5.0.0-rc3: NotFound 404`

Frequency of the issue: 5/5

Note: 
- This issue is seen only on UPGRADED local cluster and is not observed on fresh installations.
- This issue is seen only on LOCAL cluster and is not observed on downstream clusters. 
- This issue is seen only with chart 5.0.0-rc3. CIS chart 4.2.0 gets installed on the same cluster without any issues.
- To work around this issue, you can first install CIS chart 4.2.0 on the upgraded cluster and then upgrade the chart to 5.0.0-rc3. Interestingly, this succeeds. However, if you uninstall chart 5.0.0-rc3 and attempt to install it again, it fails with the same issue.

cc @rayandas @andypitcher @JonCrowther

**Comment by vardhaman22** [comment]
i was able to reproduce the issue.....but for me after some retries i was able to install the chart...i also tried to install other charts(gatekeeper, monitoring) and there was a problem installing those charts as well... so i believe this issue is related to apps -> repositories not being synced properly and needs to be handled by mapps team.

**Comment by gunamata** [comment]
cc: @rohitsakala @diogoasouza

**Comment by rohitsakala** [comment]
@Priyashetty17 I think it takes at max 5 minutes for the sync to happen. Can you wait for 5 minutes and retry installing the chart after the upgrade ? 

Also, the rc versions , you need to enable `Inlcude PreRelease Versions` in Preferences https://localhost:8443/dashboard/prefs

**Comment by rohitsakala** [comment]
@vardhaman22 How much time did it take after the upgrade?

**Comment by vardhaman22** [comment]
Hi @rohitsakala i did wait for around half an hour...the chart was showing in the UI but when we try to install it.. it was throwing a chart not found error....as mentioned in the issue this is an issue with the LOCAL cluster only and not the downstream clusters...i am not exactly sure... but this could be related to https://github.com/rancher/rancher/issues/42471

**Comment by Priyashetty17** [comment]
@rohitsakala As @vardhaman22 mentioned waiting doesn't help. It didn't seem to be an issue with charts syncing to me because the chart was available to install but failed to install only on a UPGRADED local cluster. Here's what I had to do to workaround this issue (also mentioned in my notes [here](https://github.com/rancher/rancher/issues/43021#issue-1919961323))

`To work around this issue, you can first install CIS chart 4.2.0 on the upgraded cluster and then upgrade the chart to 5.0.0-rc3. Interestingly, this succeeds. However, if you uninstall chart 5.0.0-rc3 and attempt to install it again, it fails with the same issue.`

**Comment by Priyashetty17** [comment]
@rohitsakala I'm seeing this issue even after waiting for 2hours post upgrade :)
Steps to recreate: 
- Start with Rancher 2.7.6
- Upgrade to v2.8-head
- Wait for an hour
- Attempt to install CIS chart

**Comment by gunamata** [comment]
@rohitsakala , After the reverts to pull off go-git stuff, this issue should no longer be a blocker right?

**Comment by rohitsakala** [comment]
Fixed this issue by the following PRs 

https://github.com/rancher/rancher/pull/43137
https://github.com/rancher/rancher/pull/43136

**Comment by Priyashetty17** [comment]
Validated with latest 2.8-head `v2.8-6cd32b985f0b39ef2eed363458f86a352c67a42b-head`

Test Scenarios:
On a HA Rancher setup,
- Validated CIS chart can be installed, uninstalled and reinstalled on a upgraded local cluster
- Validated CIS chart can be installed, uninstalled and reinstalled on a fresh install local cluster
- Validated CIS chart can be installed, uninstalled and reinstalled on a downstream cluster
- Validated CIS chart can be upgraded to the latest version 
- Validated monitoring chart can be installed, uninstalled and reinstalled on a upgraded local cluster

There are additional scenarios covered by Mapps QA team [here](https://github.com/rancher/rancher/issues/39532#issuecomment-1761820144) to ensure there are no regressions
