### ISSUE TITLE
Not able to see the apps in the rancher ui

### ISSUE THREAD

**Issue by gaktive** [rancher/rancher#43036]
Internal reference: SURE-6972
Reported in 2.7.5

In one environment, users are no longer able to see the installed apps in the rancher ui. Users are able to see the installed apps using a kubectl command so the guess is that this is a UI issue.

Notes:
- In certain namespaces, Helm charts did not appear in the install apps section.
- Initially, it was thought that this was a permissions issue but upon closer inspection, it was noticed in the logs that there were some cattle-cluster-agent errors.
- Subsequent thinking was that maybe it was a corrupted helm chart, but there wasn't enough evidence to conclude this theory.
- They have another issue where CPU and Memory consumption was running ramped.

Upgrade to 2.7.6 requested.

**Comment by ericpromislow** [comment]
Note to self: this fix will need to be forward-ported to `steve:release/v2.8`

**Comment by ericpromislow** [comment]
Fixing the cause of the 500 status error results in a UI problem: `curl -s …/k8s/clusters/$CLUSTER/v1/catalog.cattle.io.apps | jq '.data[] | [.type, .metadata.namespace, .metadata.name]'` returns the expected apps, and the `Installed Apps` count in the UI is updated correctly, but the list of apps in the details table is always empty.

This is with rancher 2.8. I haven't been able to stand up a local version of rancher 2.9 that can create a digital ocean cluster - when I try to create one I get an error: "No version info found in KDM"

**Comment by MKlimuszka** [comment]
This is not a problem in 2.9.x, closing.
