### ISSUE TITLE
local kubectl fails to negotiate api version with rancher kubernetes

### ISSUE THREAD

**Issue by laycat** [rancher/rancher#4303]
Rancher Version: v1.0.0

Docker Version: Docker version 1.10.1, build 9e83765

Kubectl version: Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.0+5cb86ee", GitCommit:"5cb86ee022267586db386f62781338b0483733b3", GitTreeState:"not a git tree"}

OS: OSX (Rancher running under boot2docker)

Steps to Reproduce:
- Create a rancher server
- Create a new environment
- Set that environment to kubernetes
- Download rancher kubectl config
- Use this kubectl config with local kubectl to trigger kubectl commands. 

Results: 
No kubectl actions are successful. E.g. kubectl get nodes, kubectl version
These actions fail with the message "error: failed to negotiate an api version; server supports: map[], client supports: map[v1:{} authorization.k8s.io/v1beta1:{} autoscaling/v1:{} batch/v1:{} componentconfig/v1alpha1:{} extensions/v1beta1:{} metrics/v1alpha1:{}]"

Expected:
kubectl can successfully negotiated with rancher kubernetes, and affect the environment through get, create, delete actions.

**Comment by linxit** [comment]
This has been bugging me too, but on Linux and with a slightly different error:
error: server does not support API version "v1"

However, I've found a workaround - the ~/.kube/config generated by Rancher has an error in the server url.

To get it working, just remove the /api bit on the end, as it seems that kubectl adds it on anyway and it then tries a GET request to https://<rancher>/r/projects/<env>/kubernetes/api/api, which returns a 404 error.

**Comment by alena1108** [comment]
@laycat @linxit the error you both are seeing, has the same root cause. We are going to exclude /api from the server path for 1.2 clients; the fix will be available in the next release.

**Comment by sangeethah** [comment]
Tested with rancher-server version- v1.01-rc6


server url in kube config file generated by UI does not have "/api" now.

Using this config file , we are able to use kubectl to perform actions successfully

```
Sangeethas-MacBook-Pro:kubectl21 sangeethahariharan1$ ./kubectl version
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.0", GitCommit:"5cb86ee022267586db386f62781338b0483733b3", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2+", GitVersion:"v1.2.0-rancher-1", GitCommit:"ed6532f975cff184196dbe214de8fa0198b415ef", GitTreeState:"clean"}
Sangeethas-MacBook-Pro:kubectl21 sangeethahariharan1$ ./kubectl create -f nginx.yml
replicationcontroller "shenginx" created
service "shenginx" created
Sangeethas-MacBook-Pro:kubectl21 sangeethahariharan1$ 
```

**Comment by bean5** [comment]
Finally, I know a work-around. I don't recall using anything that said or was named "Ranch", but I had `/api` in my config files. Glad to have things working with the latest version now!
