### ISSUE TITLE
[BUG] Rancher cleanup script to be updated to remove the podsecuritypolicy references

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#43043]
Information about the Cluster
**Rancher Server Setup**
- Rancher version: v2.7.6 to v2.8-head `436f4de` rolled back to `v2.7.6`
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1, v1.26.7, 1.4.10
- Proxy/Cert Details: Selfsigned
Script: https://github.com/rancher/rancher-cleanup

**Information about the Cluster**
- Kubernetes version: `v1.26.8+k3s1`
- Cluster Type (Local/Downstream): `Downstream node driver 1 worker, 1 etcd, 1 cp k3s`

**Describe the bug**
while performing a rancher roll back, we would need to run the cleanup script as mentioned here https://github.com/rancherlabs/support-tools/pull/167. Once the cleanup script is completely run, if we run the verify script, we notice a few errors 
```
error: the server doesn't have a resource type "podsecuritypolicy"
```

There are a few references in the script to obtain podSecurityPolicy in the following lines: https://github.com/rancher/rancher-cleanup/blob/main/cleanup.sh#L274C1-L297C5. Since, PSPs are deprecated and removed from k8s versions 1.25+, script should be modified to run these only on k8s versions 1.25 and below and should not be run from 1.25 and above k8s versions

**To Reproduce**

1. Install rancher on v2.7.6 version
2. As an admin create an rke1 node driver cluster 1 worker, 1 cp, 1 etcd nodes, and and rke2 node driver cluster with 1 worker, 1 cp, and 1 etcd nodes.
3. Create 2 standard users u1 and u2 and the users in the clusters as cluster owners.
5. Install rancher backup/restore chart 3.1.2 using s3 as storage option.
6. Take a backup b1
7. Upgraded rancher server to v2.8-head
9. Follow the instructions to run the cleanup script https://github.com/rancher/rancher-cleanup

**Result**
Once the cleanup is finished, we get the following error when we run verify.sh script
```
error: the server doesn't have a resource type "podsecuritypolicy"
error: the server doesn't have a resource type "podsecuritypolicy"
error: the server doesn't have a resource type "podsecuritypolicy"
error: the server doesn't have a resource type "podsecuritypolicy"
error: the server doesn't have a resource type "podsecuritypolicy"
error: the server doesn't have a resource type "podsecuritypolicy"
error: the server doesn't have a resource type "podsecuritypolicy"
error: the server doesn't have a resource type "podsecuritypolicy"
error: the server doesn't have a resource type "podsecuritypolicy"
error: the server doesn't have a resource type "podsecuritypolicy"
```

**Expected Result**
Job runs without any error

**Comment by eliyamlevy** [comment]
Merged commit which should fix this issue.

**Comment by anupama2501** [comment]
Verified rollback via backup/restore operator from v2.7.6 >> v2.8-head `6376016 ` >> v2.7.6

- Install rancher on v2.7.6 version
- As an admin create an rke1 node driver cluster 1 worker, 1 cp, 1 etcd nodes, and and rke2 node driver cluster with 1 worker, 1 cp, and 1 etcd nodes.
- Create 2 standard users u1 and u2 and the users in the clusters as cluster owners.
- Install rancher backup/restore chart 3.1.2 using s3 as storage option.
- Take a backup b1
- Upgraded rancher server to v2.8-head
- Follow the instructions to run the cleanup script https://github.com/rancher/rancher-cleanup
- Verified post cleanup, the errors for PSPs were not seen.
- Verified rancher installation was successfully created on v2.7.6.

**Comment by anupama2501** [comment]
Verified cleanup on a k8s 1.24 local cluster with the PSP resources.

- Install rancher on v2.7.8 version on a k8s 1.24 cluster rke1
- As an admin create an rke2 node driver cluster 1 worker, 1 cp, 1 etcd nodes
- Install rancher backup/restore chart 3.1.2 using s3 as storage option.
- Take a backup b1
- Upgraded rancher server to v2.8-head
- Follow the instructions to run the cleanup script https://github.com/rancher/rancher-cleanup
- Verified post cleanup, no errors for PSPs were not seen.
- Install the rancher helm chart for 2.7.8
- Roll back to v2.7.8 rancher by following docs https://ranchermanager.docs.rancher.com/v2.7/how-to-guides/new-user-guides/backup-restore-and-disaster-recovery/restore-rancher
