### ISSUE TITLE
Network corruption across hosts

### ISSUE THREAD

**Issue by deadbeef84** [rancher/rancher#4304]
Rancher Version: 1.0.0

Docker Version: 1.10.3

OS: Debian GNU/Linux 8.3 (jessie)

Steps to Reproduce:
Create stack with the following service:

**Dockerfile**
```
FROM alpine:3.3
RUN apk update && apk add socat
COPY ./server.sh /server.sh
CMD [ "/server.sh" ]
```

**server.sh**
```
#!/bin/sh
socat -u TCP-LISTEN:5555 OPEN:out.file,creat,trunc
{ date; md5sum out.file; } | tr '\n' ' '; echo
exec $0
```

This should accept connections on port 5555 and print md5sum's of the sent content.

Now, assuming you have at least 2 hosts, run the following script from the host that isn't running the service:

**client.sh**
```
#!/bin/sh
socat -u FILE:testfile.ext TCP:service_private_ip:5555
sleep 0.5
exec $0
```
Having a `testfile.ext` in the same folder (mine was about 300MB), and replace `service_private_ip` with the rancher assigned ip of the service created above. This will continuously send the testfile to the server.

Once everything is running, try adding/removing services, and you'll see that the md5 checksums will be different. **I also get checksum errors even when not adding/removing services.**

I've created the same setup without containers and ranchers managed network, running sever.sh/client.sh directly on the hosts, then everything works fine; so the problem does not appear to be related to the physical network.

Results: 
Different md5 checksums.

Expected:
Same md5 checksum.

**Comment by deadbeef84** [comment]
Maybe related:
- https://tech.vijayp.ca/linux-kernel-bug-delivers-corrupt-tcp-ip-data-to-mesos-kubernetes-docker-containers-4986f88f7a19#.9syabwjc0
- #4284

**Comment by deadbeef84** [comment]
Just verified that the issue also exist when:
- using rancher 1.0.0 with kubernetes orchestration
- using rancher 0.56.1

**Comment by vincent99** [comment]
#4284 is probably the DNS service crashing when an update event comes in  and getting restarted if anything.

Is the kernel on your hosts new enough to have that issue addressed?  Unless you're running RancherOS we have no control over what kernel you're using.

**Comment by ronag** [comment]
What kernel is recommended?

**Comment by ronag** [comment]
Debian 3.8 has kernel v. 3.16

**Comment by retardtank** [comment]
@ronag 6 lines where removed from `drivers/net/veth.c` in 3.16.7-ckt24 (*hint*,*hint*). As of now, the Debian source package for the kernel delivers 3.16.7-ckt25...

**Comment by ronag** [comment]
@retardtank: That doesn't really tell me anything...

**Comment by retardtank** [comment]
@ronag A patch for the bug was applied in 3.16.7-ckt24.

"veth: don’t modify ip_summed; doing so treats packets with bad checksums as good."

**Comment by sshipway** [comment]
This could be related to our random 'Host reconnecting' dropouts, and the apparently random 'LoadBalancer initialising' issue.  However this was fixed in kernel 3.16 and CoreOS claims to run kernel 4.3.6?

**Comment by retardtank** [comment]
@sshipway Fixes like these are often backported by distribution maintainers, as in the case of Debian mentioned above. So just comparing versions specific to the kernel itself don't always say that much...

**Comment by deadbeef84** [comment]
I've now confirmed that this is indeed related to the linux kernel bug mentioned above. A simple apt-get dist-upgrade solved the issue. I'll close this for now!
