### ISSUE TITLE
[Backport v2.7] [SURE-6630] High CPU usage on Rancher cluster nodes when downstream clusters are shutdown

### ISSUE THREAD

**Issue by moio** [rancher/rancher#43051]
This is a backport issue for https://github.com/rancher/rancher/issues/42864

Original issue description:

Internal reference: [SURE-6630](https://jira.suse.com/browse/SURE-6630)

**Rancher Server Setup**
- Rancher version: 2.7.5
- Installation option (Docker install/Helm Chart): Helm Chart, AKS

**Information about the Cluster**
- Kubernetes version: 1.26
- Cluster Type (Local/Downstream): 50 Downstream clusters (90% AKS and the remaining RKE1)

**User Information**
- What is the role of the user logged in? Irrelevant

**Describe the bug**
Some clusters are periodically unavailable, from a few to up to 55% of them. High CPU usage from rancher pods is noticed with one node always being at 100% CPU, and it worsens whenever a bigger number of clusters is not available.

A profile captured in a moment when most clusters were not available highlights the following hotspots:

![sure-6630_analysis](https://github.com/rancher/rancher/assets/250541/cfb4688f-5dc6-43e3-a9d7-17f036d929bd)
`go tool pprof -http=: ~/Downloads/after-profile-2023-09-08_16_03_45/rancher-5d6f96fdfd-ml58q-profile-2023-09-08T14_44_50`

**Hotspot 1** is the `restrictedAdminGlobalBindingsFleet` controller handler, which continuously rewrites `fleetworkspace` RoleBindings (2 per Restricted Admin, per cluster) even in absence of any changes.

 - when downstream clusters are available it fires every 5 minutes ([kubelet's nodeStatusReportFrequency](https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/) default)
 - when downstream clusters are not available it fires more often, every ~50s in my setup (30s + other compute time which depends on hardware ant other factors), every 2 minutes after the 30th time

It is believed this handler is also responsible for a significant amount of watch traffic and possibly memory trashing (GC time).

**To Reproduce**

I have not been able to reproduce all symptoms of this bug faithfully, however, **Hotspot 1** can easily be detected via `kubectl get --watch`.

Specifically:

 - set up a Rancher installation with at least one downstream cluster
 - set up at least one Restricted Admin user
 - run `kubectl get -A --watch --watch-only rolebinding`

(see later section for a full reproducer)

**Result**
 - `kubectl` outputs two `fleetworkspace` RoleBinding lines every 5 minutes (per Restricted Admin, per downstream cluster)

**Expected Result**
 - no output

**Additional context**

Full reproducer below:

```
# from a machine running Docker or with access to a Docker daemon
# with kubectl, helm, terraform, git and node installed

git clone -b disconnected_clusters https://github.com/moio/scalability-tests.git
cd scalability-tests
./bin/setup.mjs && ./bin/run_tests.mjs
KUBECONFIG=./config/upstream.yaml kubectl get -A --watch --watch-only rolebinding
```

Note: the reproducer uses the [disconnected_clusters branch](https://github.com/moio/scalability-tests/compare/master...disconnected_clusters) of the [scalability-tests project](https://github.com/moio/scalability-tests) which will deploy k3d clusters, install and set up Rancher, and create Restricted Admin test users.

**Comment by gaktive** [comment]
2.7.8 was an emergency release to address a blocker. Since this wasn't needed for that release, I put this in the 2.7.x backlog for Q1.

**Comment by moio** [comment]
Closing per https://github.com/rancher/rancher/issues/42864#issuecomment-1855740063
