### ISSUE TITLE
[RFE] Add "additional-trusted-cas" to Rancher Global Settings -> Feature Flags

### ISSUE THREAD

**Issue by zanewgray** [rancher/rancher#43055]
**Is your feature request related to a problem? Please describe.**
I recently had a cluster manager add a private repo to their cluster using a self-signed cert.  The manager was frustrated that their was no option to allow the self-signed cert to either be ignored or have an easy way to upload the private CA to his cluster so that the local registry is trusted.

**Describe the solution you'd like**
Adding trusted CAs should be as "self-service" as possible and, preferably, controllable through the GUI.  I propose that:

- As a Rancher Manager instance owner, I can use the Rancher UI -> Global Settings -> Feature Flags to toggle "additionalTrustedCAs" to "true"
- As a downstream cluster administrator, assuming the Rancher Manager owner allows it, I should be able to add the trusted CAs via the GUI (e.g. something like cluster -> More Resources -> Core -> TrustedCAs) to have them consumed by the upstream Rancher Manager and pushed to the downstream cattle agents.

**Describe alternatives you've considered**
None.

**Additional context**
Currently, as the Rancher Manager owner, to allow a downstream cluster manager to trust a resource with a self-signed cert, I must:

1. Re-run the Rancher Helm operation with a "--set additionalTrustedCAs=true" flag
2. Request a copy of the downstream cluster-owner's CA in PEM format
3. Upload the CA using a kubectl command to the central Rancher Manager

I would prefer that this process become "self-service" for cluster managers, and rely less on the command line.  Many of our cluster managers are just getting familiar with Kubernetes, and are leaning heavily on the GUI.

**Comment by hv15** [comment]
I think would be very useful feature, is there any progress on this?
