### ISSUE TITLE
v2.7.8 cluster error messages - SOLVED

### ISSUE THREAD

**Issue by smirnov-mi** [rancher/rancher#43075]
**Rancher Server Setup**
- Rancher version:2.7.8. updated from 2.7.7, single docker installation

**Information about the Cluster**
- Kubernetes version: 1.26.8-rancher1
- Cluster Type (Downstream):
created via rancher 

**User Information**
local admin in rancher, since openldap stopped working in 2.7.1

**Describe the bug**
docker logs shows:
2023/10/05 18:56:26 [ERROR] Unknown error: Operation cannot be fulfilled on preferences.management.cattle.io "cluster": the object has been modified; please apply your changes to the latest version and try again
W1005 18:56:35.996413      49 warnings.go:80] cluster.x-k8s.io/v1alpha3 MachineSet is deprecated; use cluster.x-k8s.io/v1beta1 MachineSet
W1005 18:59:00.998591      49 warnings.go:80] cluster.x-k8s.io/v1alpha3 MachineHealthCheck is deprecated; use cluster.x-k8s.io/v1beta1 MachineHealthCheck
2023/10/05 18:59:54 [ERROR] Unknown error: Operation cannot be fulfilled on preferences.management.cattle.io "cluster": the object has been modified; please apply your changes to the latest version and try again
W1005 19:00:28.394722      49 warnings.go:80] cluster.x-k8s.io/v1alpha3 Machine is deprecated; use cluster.x-k8s.io/v1beta1 Machine
W1005 19:00:46.259136      49 warnings.go:80] cluster.x-k8s.io/v1alpha3 MachineDeployment is deprecated; use cluster.x-k8s.io/v1beta1 MachineDeployment

I also can't see cluster details in the "cluster management" -> "Edit Config" page, so I can't update it.

**To Reproduce**
update from 2.7.7 to 2.7.8 , 
1) see docker logs;
2) Goto CLuster Management page, then select "edit config" of the existing cluster.

**Result**
1) errors in the docker logs
2) Page doesn't include the top part with config.

**Expected Result**
1) no errors in the docker logs
2) Page should include the config details

**Comment by smirnov-mi** [comment]
restarting rancher docker after approx 30 minutes of running it for the first time (updating the things) solved both issues. 

Issue can be closed.

**Comment by smirnov-mi** [comment]
alpha / beta  error messages are logged in a separate issue:  https://github.com/rancher/rancher/issues/43083

**Comment by ne0YT** [comment]
@smirnov-mi what's the best thing to do here on a freshg install? waiting 30 minutes and then restarting?
