### ISSUE TITLE
[BUG] RKE2/K3s cluster nodes get recreated on a rollback using backup/restore operator

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#43070]
Information about the Cluster
**Rancher Server Setup**
- Rancher version: `v2.7.6 ` >> v2.8.0-alpha2 >> `v2.7.6`
- Installation option (Docker install/Helm Chart): `Helm Chart`
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): `RKE1`, `v1.27.6`, `1.5.0-rc8`
- Proxy/Cert Details: `Self-signed`

**Information about the Cluster**
- Kubernetes version: `v1.26.8+k3s1` and `v1.26.8+rke2r1`
- Cluster Type (Local/Downstream): `Node driver AWS  3 worker, 3 etcd, 2 cp k3s`, `Node driver Linode  1 worker, 1 etcd + cp RKE2`, 

**Describe the bug**
On a rancher roll back from v2.7.6 upgraded to v2.8.0-alpha2 back to v2.7.6, notice that rke2 and k3s nodes are getting recreated,

**To Reproduce**

1. Install rancher on version 2.7.6
2. Create a node driver k3s and RKE2 cluster with the specs mentioned above.
3. Install rancher backup/restore chart version in the local cluster with config set to S3, version `102.0.1+up3.1.1`
4. Take a backup from the rancher backup/restore page and the backupfile gets saved in the s3.
5. Upgrade rancher server to v2.8.0-alpha2
6. Rollback to 2.7.6 on the same rancher server by running the cleanup https://github.com/rancher/rancher-cleanup
7. Install rancher server by following the instructions from here: https://ranchermanager.docs.rancher.com/v2.7/how-to-guides/new-user-guides/backup-restore-and-disaster-recovery/restore-rancher
8. Once rancher server is up, notice the clusters go into updating state 

**Result**
Notice the nodes are recreated on both the downstream clusters of rke2 and k3s. 

**Expected Result**
Nodes not recreated for the downstream clusters

**Screenshots**
<img width="600" alt="2023-10-05_20-08-13" src="https://github.com/rancher/rancher/assets/38144301/4987f1d8-43de-491b-b73c-dc0d02882764">

**Additional context**
Initially noticed the following logs in rancher pods, after checking the AWS, noticed new nodes were created.
```
2023/10/05 14:35:46 [INFO] Deleted cluster node machine-kp6sg [anuk3srbs-e-534c38cb-cgdxw]
2023/10/05 14:35:46 [ERROR] error syncing 'fleet-default/anuk3srbs-bootstrap-template-prd6x': handler rke-bootstrap: failed to delete fleet-default/anuk3srbs-bootstrap-template-prd6x-machine-plan /v1, Kind=ServiceAccount for rke-bootstrap fleet-default/anuk3srbs-bootstrap-template-prd6x: serviceaccounts "anuk3srbs-bootstrap-template-prd6x-machine-plan" not found, failed to delete fleet-default/anuk3srbs-bootstrap-template-prd6x-machine-plan rbac.authorization.k8s.io/v1, Kind=Role for rke-bootstrap fleet-default/anuk3srbs-bootstrap-template-prd6x: roles.rbac.authorization.k8s.io "anuk3srbs-bootstrap-template-prd6x-machine-plan" not found, requeuing
```

Note:

1. The issue is not noticed when we roll back on a different rancher server following the docs https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/backup-restore-and-disaster-recovery/migrate-rancher-to-new-cluster 
2. Also not noticed when docker upgrade/rollback is performed following the docs https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade/other-installation-methods/rancher-on-a-single-node-with-docker/upgrade-docker-installed-rancher
3. Observed consistently 2 out of 2 times when the roll back is performed on the same rancher server following the docs https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/rollbacks

**Comment by anupama2501** [comment]
Still notice this issue on a roll back from v2.7.8 >> v2.8-head >> v2.7.8 on an rke2 node driver. Notice the nodes are recreated and the cluster stays in updating state.
Found while validating: https://github.com/rancher/rancher/issues/43043

**Comment by jiaqiluo** [comment]
Hi @jakefhyde , can you take a look?

**Comment by nickwsuse** [comment]
I'm running into this with a rollback from v2.7.8 to v2.7.9 back to v2.7.8, so I'll make a backport issue for this

**Comment by jakefhyde** [comment]
Just ran a manual validation with cleanup `v1.0.3-rc2` and there was nothing left over except the default expected k8s namespaces. Post restore, the cluster generation was updated, fleet installs, the webhook is rolled out, the cluster reconciles (standard HA 3/2/3), the webhook-service error that usually shows up when we try to update the cluster and the webhook isn't available shows up which is expected, and the error goes away once the cluster has finished reconciling. I am kicking this back to to test based on this. I had to manually update the cleanup yaml to use the following, as the fix is not released yet in a non-rc version of `rancher-cleanup`:
```yaml
spec:
  template:
    spec:
      containers:
        - name: cleanup
          image: rancher/rancher-cleanup:v1.0.3-rc2
```

**Comment by thaneunsoo** [comment]
I tested the scenario above @jakefhyde mentioned. I am not able to reproduce this issue.
1. 2.7.6 to 2.8.0-rc1 to 2.7.6 - rke2/k3s clusters The cluster came back up and none of the cluster nodes got recreated.
2. 2.7.8 to 2.8.0-rc1 to 2.7.6 - rke2/k3s clusters The cluster came back up and none of the cluster nodes got recreated.
3. 2.7.6 to 2.8.0-rc1 to 2.7.6 - rke2 cluster only
@nickwsuse did you want to verify if you are now seeing the same thing?

**Comment by nickwsuse** [comment]
I ran the following cases:

1. With 'latest' image: 2.7.6 -> 2.7.7 -> 2.7.6 - rke2/k3s cluster nodes _**did**_ get recreated and the k3s cluster came back active - rke1 unaffected
2. With v1.0.3-rc2 image: 2.7.6 -> 2.7.7 -> 2.7.6 - rke2/k3s cluster nodes did **_not_** reprovision and both were active within 6 minutes - rke1 unaffected

**Comment by thaneunsoo** [comment]
Closing this issue based on Nick and my tests.
