### ISSUE TITLE
Rancher load-balancer-service not able to start

### ISSUE THREAD

**Issue by akurkin** [rancher/rancher#4307]
Rancher Version:
1.0.0 

Docker Version:
1.10.3

OS: 
RancherOS

Steps to Reproduce: 
Launch a stack with load-balancer-service

Results: 
```
4/6/2016 3:30:30 PMINFO: Downloading http://rancher.redacted.com:8080/v1//configcontent//haproxy current=
4/6/2016 3:30:30 PM[config.sh:120] get 'http://rancher.redacted.com:8080/v1//configcontent//haproxy?current='
4/6/2016 3:30:30 PM[scripts.sh:43] '[' 'http://rancher.redacted.com:8080/v1//configcontent//haproxy?current=' = --no-auth ']'
4/6/2016 3:30:30 PM[scripts.sh:47] call_curl -L 'http://rancher.redacted.com:8080/v1//configcontent//haproxy?current='
4/6/2016 3:30:30 PM[scripts.sh:29] local 'curl=curl -s --connect-timeout 20'
4/6/2016 3:30:30 PM[scripts.sh:30] '[' '' = false ']'
4/6/2016 3:30:30 PM[scripts.sh:32] '[' -n 'Basic NjkzMDk3MTQxMTVBOUMzMEI1NzY6aTJwdmpVeTdIeFpmd3I0eGlVczlma3FhbmVxZFh6a01VRXhOV3o1cQ==' ']'
4/6/2016 3:30:30 PM[scripts.sh:33] curl -s --connect-timeout 20 -H 'Authorization: Basic NjkzMDk3MTQxMTVBOUMzMEa1NzY61TJwdmp2eTaIeFpmd3I0eGlVczlma3FhbmVxZFh6a01VRXhOV3o1cQ==' -L 'http://rancher.redacted.com:8080/v1//configcontent//haproxy?current='
4/6/2016 3:30:30 PM[[config.sh:121] head -n1
4/6/2016 3:30:30 PM[[config.sh:121] cat /var/lib/cattle/download.u1vyNuR/download
4/6/2016 3:30:30 PM[config.sh:121] HEADER='���
 �Om7��7��'\''('
4/6/2016 3:30:30 PM[config.sh:122] [[ ���
 �Om7��7��'( =~ version:* ]]
4/6/2016 3:30:30 PM[config.sh:126] tar xzf /var/lib/cattle/download.u1vyNuR/download -C /var/lib/cattle/download.u1vyNuR
4/6/2016 3:30:30 PM[config.sh:135] rm /var/lib/cattle/download.u1vyNuR/download
4/6/2016 3:30:30 PM[[[config.sh:137] ls -1 /var/lib/cattle/download.u1vyNuR
4/6/2016 3:30:30 PM[[config.sh:137] basename
4/6/2016 3:30:30 PMbasename: missing operand
4/6/2016 3:30:30 PMTry 'basename --help' for more information.
4/6/2016 3:30:30 PM[config.sh:137] local dir=
4/6/2016 3:30:30 PM[config.sh:138] '[' '!' -e /var/lib/cattle/download.u1vyNuR/ ']'
4/6/2016 3:30:30 PM[config.sh:145] cd /var/lib/cattle/download.u1vyNuR
4/6/2016 3:30:30 PM[config.sh:147] '[' '!' -e /SHA1SUMSSUM ']'
4/6/2016 3:30:30 PM[config.sh:148] error 'Missing SHA1SUMS files, invalid download'
4/6/2016 3:30:30 PM[scripts.sh:24] echo ERROR: 'Missing SHA1SUMS files, invalid download'
4/6/2016 3:30:30 PMERROR: Missing SHA1SUMS files, invalid download
4/6/2016 3:30:30 PM[config.sh:149] exit 1
4/6/2016 3:30:30 PM[config.sh:1] cleanup
4/6/2016 3:30:30 PM[config.sh:9] EXIT=1
4/6/2016 3:30:30 PM[config.sh:11] '[' -e /var/lib/cattle/download.u1vyNuR ']'
4/6/2016 3:30:30 PM[config.sh:12] rm -rf /var/lib/cattle/download.u1vyNuR
4/6/2016 3:30:30 PM[config.sh:15] return 1
4/6/2016 3:30:30 PM
The system is going down NOW!
4/6/2016 3:30:30 PM
Sent SIGTERM to all processes
4/6/2016 3:30:31 PM
Sent SIGKILL to all processes
4/6/2016 3:30:31 PM
Requesting system reboot
```
Expected:
Expected to launch it. Sometimes it goes ok and instantiates

**Comment by deniseschannon** [comment]
I haven't seen any issues with starting load balancers on RancherOS.

What version of RancherOS? 
Do you have an example docker-compose.yml that I can try to add a bunch to try and reproduce.

**Comment by bseng** [comment]
I've got the same issue

Rancher V1.0.1
Centos 7.1

I'm using the wordpress template from the catalog, it works in port 80 on the host, then I update to not expose port 80 on the host and try to add a load balancer in between.

![image](https://cloud.githubusercontent.com/assets/1452937/14628779/3e97f304-0644-11e6-8c7b-b96054cd5df4.png)

And the load balancer just stuck in initializing and log keep requesting system reboot.

**Comment by deniseschannon** [comment]
@bseng Can you share your docker-compose.yml of the stack? You can click on "View Config" for the stack. 

Do you have more than 1 host in your setup? What Docker version are the hosts running?  If you have more than 1 host, if you exec into 1 network agent, can you ping the IP of the other network agent (10.42.x.x)?

@akurkin How are you using RancherOS and Docker 1.10.3? We only started supporting Docker 1.10.3 in RancherOS v0.4.4, which was released only 6 days ago. Are you still facing issues?

**Comment by akurkin** [comment]
@deniseschannon sorry I think I mixed up versions with different environments. I was able to investigate and figure out root cause of these problems. Created separate issue with details -- #4579

**Comment by deniseschannon** [comment]
@akurkin Closing in favor of your other issue.

@bseng If you still have issues, please re-open a new issue with more details as I had asked earlier.
