### ISSUE TITLE
[BUG] `patch-sa-cattle-provisioning-capi-system` securityContext issues when deploying rancher on a hardened rke2 (local) cluster

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#43078]
**Rancher Server Setup**
- Rancher version: v2.8-head (fc12e7d)
- Installation option (Docker install/Helm Chart): helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): rke2 v1.27.6+rke2r1
- Proxy/Cert Details: valid certs

**Information about the Cluster**
- Kubernetes version: 1.27.6+rke2r1
- Cluster Type (Local/Downstream): local

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: admin

**Describe the bug**

when deploying rancher onto a hardened rke2 cluster, the `patch-sa-cattle-provisioning-capi-system` reports an error

**To Reproduce**

* setup a hardened rke2 cluster
* deploy rancher onto it

**Result**

```
container "patch-sa-cattle-provisioning-capi-system" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "patch-sa-cattle-provisioning-capi-system" must set securityContext.capabilities.drop=["ALL"]), seccompProfile (pod or container "patch-sa-cattle-provisioning-capi-system" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost"
```

**Expected Result**

capi job should be able to run on a hardened cluster

**Screenshots**

**Additional context**

possibly a subset of this issue: https://github.com/rancher/rancher/issues/42777

**Comment by snasovich** [comment]
Marking as release blocker as it's likely regression from 2.7.6 -> 2.7.7 (where CAPI controllers moved to own deployment).

**Comment by snasovich** [comment]
Moving back to "To Test" as it seems to be caused by missing exceptions for Pod Security configuration in local hardened cluster Rancher is running on. FYI @susesgartner @thaneunsoo @slickwarren

**Comment by thaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.8-head 6376016 
Rancher cluster type: RKE2 HA hardened
Docker version: 20.10

----------

### Testing: ###
1. Setup RKE2 Hardened cluster
2. Deploy Rancher v2.8-head 6376016 on top of the cluster

**Result**
The capi job completed successfully on the hardened cluster. I also provisioned a downstream rke2 node driver cluster and the cluster provisioned successfully as well.  Gist has been updated on QA end to add namespace `cattle-provisioning-capi-system` under exemption list. Closing this issue.

**Comment by jiaqiluo** [comment]
Workaround:

Add  `cattle-provisioning-capi-system` under the `exemptions.namespaces` list in the AdmissionConfiguration (file) applied to the `kube-apisever` in the local cluster. This must be performed on all `kube-apiserver` containers/processes on all control plane nodes.

**Comment by Martin-Weiss** [comment]
Any idea why we did not find this in the release-notes? Basically during the upgrade 2.7.6 to 2.7.9 I ran into this problem where the capi control manager did not get started:

```
    - lastTransitionTime: "2023-11-10T08:34:50Z"
      lastUpdateTime: "2023-11-10T08:34:50Z"
      message: 'pods "capi-controller-manager-7d9d579cbf-" is forbidden: PodSecurityPolicy:
        unable to admit pod: [pod.metadata.annotations[seccomp.security.alpha.kubernetes.io/pod]:
        Forbidden: seccomp may not be set pod.metadata.annotations[container.seccomp.security.alpha.kubernetes.io/manager]:
        Forbidden: seccomp may not be set pod.metadata.annotations[seccomp.security.alpha.kubernetes.io/pod]:
        Forbidden: seccomp may not be set pod.metadata.annotations[container.seccomp.security.alpha.kubernetes.io/manager]:
        Forbidden: seccomp may not be set]'

```

**Comment by daemonadmin** [comment]
> Any idea why we did not find this in the release-notes? Basically during the upgrade 2.7.6 to 2.7.9 I ran into this problem where the capi control manager did not get started:
> 
> ```
>     - lastTransitionTime: "2023-11-10T08:34:50Z"
>       lastUpdateTime: "2023-11-10T08:34:50Z"
>       message: 'pods "capi-controller-manager-7d9d579cbf-" is forbidden: PodSecurityPolicy:
>         unable to admit pod: [pod.metadata.annotations[seccomp.security.alpha.kubernetes.io/pod]:
>         Forbidden: seccomp may not be set pod.metadata.annotations[container.seccomp.security.alpha.kubernetes.io/manager]:
>         Forbidden: seccomp may not be set pod.metadata.annotations[seccomp.security.alpha.kubernetes.io/pod]:
>         Forbidden: seccomp may not be set pod.metadata.annotations[container.seccomp.security.alpha.kubernetes.io/manager]:
>         Forbidden: seccomp may not be set]'
> ```

Hello! I resolved this in few steps:
1) On Local Rancher cluster: kubectl get psp global-unrestricted-psp -o yaml
You'll see no annotations.
2) kubectl edit psp global-unrestricted-psp (or with kubectl annotate psp global-unrestricted-psp)
Add annotations:
```
metadata:
     annotations:
         psp.rke2.io/global-unrestricted: resolved
         seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
```
3) Restart deployment:
kubectl -n cattle-provisioning-capi-system restart deploy capi-controller-manager

That's it. You'll see created pod capi-controller-manager-XXX-YYY.

**Comment by murand78** [comment]
Thanks @daemonadmin , encountered same issue upgrading rancher 2.7.6 -> 2.7.9 on a v1.24.17+rke2r1  cluster, your workaround solved for  me
