### ISSUE TITLE
Allow extensions to load before login

### ISSUE THREAD

**Issue by diogoasouza** [rancher/rancher#43090]
Currently extensions only load after the user logs in, this limits our ability to add new locales, custom branding and custom login screen.

**Comment by sunilarjun** [comment]
Hello @diogoasouza, for clarification is the feature flag `uiextension` a new flag coming in v2.9.0 or one that previously existed? Should this flag be added to the Rancher documentation [feature flag](https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade/installation-references/feature-flags) page? Any guidance appreciated, thank you!

**Comment by diogoasouza** [comment]
Hi @sunilarjun, it's a new flag. I mentioned it in the docs for extensions (https://github.com/rancher/rancher-docs/pull/1301), but I think it would be nice to have it in the feature flag page

**Comment by sunilarjun** [comment]
Thank you for the response @diogoasouza! Will be getting this added into the feature flag page ([tracking issue](https://github.com/rancher/rancher-docs/issues/1403)).

**Comment by martyav** [comment]
@diogoasouza Docs team here. Is this flag considered experimental, or GA?

**Comment by diogoasouza** [comment]
@martyav Hi! The flag is not experimental
