### ISSUE TITLE
[BUG] Incorrect LimitRange Creation When project doesn't set default value

### ISSUE THREAD

**Issue by smallteeths** [rancher/rancher#43098]
**Rancher Server Setup**
- Rancher version: 2.7.x
- Installation option (Docker install/Helm Chart): docker

**Describe the bug**
When the project does not set a default limitRange, and the namespace sets a limitRange, the limitRange is not correctly created

**To Reproduce**
1. Create project without defaultLimitRange
<img width="1790" alt="截屏2023-10-09 下午1 44 57" src="https://github.com/rancher/rancher/assets/27733391/93730024-1d45-46ba-bddf-1db68c3f54af">

2. Create ns with limitRange
<img width="1575" alt="截屏2023-10-09 下午1 45 57" src="https://github.com/rancher/rancher/assets/27733391/16652b87-28fc-4e7e-8f20-dc76395c8adb">

3. `kubectl get -n ns limitRange`  -> No resources found in the ns

**Expected Result**
Successfully creating the limitRange.

**Comment by samjustus** [comment]
@smallteeths which version exactly was your setup?

**Comment by smallteeths** [comment]
rancher/rancher:v2.7.8

> @smallteeths which version exactly was your setup?
