### ISSUE TITLE
[RFE] Label deprecated setting kubeconfig-token-ttl-minutes from v3 and v1 API for future removal

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#43103]
**Is your feature request related to a problem? Please describe.**
Currently on an upgraded setup, the setting `kubeconfig-token-ttl-minutes` is not removed since it is a resource in the local cluster. 

**Describe the solution you'd like**
As the setting `kubeconfig-token-ttl-minutes` has been deprecated and removed, it would be nice to remove the setting from v3/v1 API on an upgraded rancher server. 

**Additional context**
https://github.com/rancher/rancher/issues/38535

**Comment by MKlimuszka** [comment]
Assigning @pmatseykanets for the design phase.

**Comment by pmatseykanets** [comment]
The consensus seem to be we don't want to clean one setting at a time. Instead we'd like to have a generalized approach which covers all deprecated/removed and any custom settings.

Initially, on Rancher startup we list all the setting resources in the cluster and mark all unknown/unrecognized (e.g. deprecated) settings with a label. In a future release e.g. 2.9 we'll be removing them instead. This gives an opportunity to someone who used setting resources, e.g. for integration purposes, to transition to something else.

**Comment by joesims22** [comment]
Verified on v2.9-head `71fde1b` 

**Validate**:

1. Create a single node Docker install of Rancher at v2.9-head
2. Go to Global Settings and observe that the `kubeconfig-token-ttl-minutes` setting is NOT present and that `kubeconfig-default-token-ttl-minutes` setting is present.
3. Go to `<hostname>/v1/management.cattle.io.settings` and verify that the `kubeconfig-token-ttl-minutes` setting is present and has the label: `cattle.io/unknown": "true"` and that the `kubeconfig-default-token-ttl-minutes` setting is present.
4. Go to `<hostname>/v3/settings` and verify that the `kubeconfig-token-ttl-minutes` setting is present and has the label: `cattle.io/unknown": "true"` and that the `kubeconfig-default-token-ttl-minutes` setting is present.

**Upgrade Check**:
1. Create a single node Docker install of Rancher on v2.7.9
2. Create a downstream RKE2 cluster
3. Go to Global Settings and observe that the `kubeconfig-token-ttl-minutes` setting is still present and marked as deprecated, and that `kubeconfig-default-token-ttl-minutes` setting is present.
4. Go to `<hostname>/v1/management.cattle.io.settings` and verify that the `kubeconfig-token-ttl-minutes` setting is present and does NOT have the label: `cattle.io/unknown": "true"` and that the `kubeconfig-default-token-ttl-minutes` setting is present.
5. Go to `<hostname>/v3/settings` and verify that the `kubeconfig-token-ttl-minutes` setting is present and does NOT have the label: `cattle.io/unknown": "true"` and that the `kubeconfig-default-token-ttl-minutes` setting is present.
6. Upgrade Rancher to v2.9-head
7. Verify downstream cluster is active with no issues
8. Go to Global Settings and observe that the `kubeconfig-token-ttl-minutes` setting is NOT present and that `kubeconfig-default-token-ttl-minutes` setting is present.
9. Go to `<hostname>/v1/management.cattle.io.settings` and verify that the `kubeconfig-token-ttl-minutes` setting is present and has the label: `cattle.io/unknown": "true"` and that the `kubeconfig-default-token-ttl-minutes` setting is present.
10. Go to `<hostname>/v3/settings` and verify that the `kubeconfig-token-ttl-minutes` setting is present and has the label: `cattle.io/unknown": "true"` and that the `kubeconfig-default-token-ttl-minutes` setting is present.

**Comment by pmatseykanets** [comment]
We need to handle `eula-agreed` setting that is used by UI, otherwise in v2.9 it's going to be removed.

**Comment by joesims22** [comment]
Verified on an upgrade from v2.8.3 -> v2.9-head id ```f26d988```

eula-agreed setting does not have cattle.io/unknown label ✅
