### ISSUE TITLE
In kubernetes, Delay observed when accessing Lb services.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#4310]
Rancher Version:v1.0.0

Created a Replication Control for nginx container with replicas 2.
Created Lb service for this RC.
When accessing LB rules ,  there is a delay observed when accessing the targets.

Wget initially fails with "No data received" and then successive attempt succeeds.

```
Sangeethas-MacBook-Pro:testwget sangeethahariharan1$ wget http://104.236.94.210:9988/name.html
--2016-04-06 16:15:08--  http://104.236.94.210:9988/name.html
Connecting to 104.236.94.210:9988... connected.
HTTP request sent, awaiting response... No data received.
Retrying.

--2016-04-06 16:15:13--  (try: 2)  http://104.236.94.210:9988/name.html
Connecting to 104.236.94.210:9988... connected.
HTTP request sent, awaiting response... 200 OK
Length: 16 [text/html]
Saving to: ‘name.html.1’

100%[=============================================================================================================>] 16          --.-K/s   in 0s      

2016-04-06 16:15:13 (1.91 MB/s) - ‘name.html.1’ saved [16/16]

```

**Comment by sangeethah** [comment]
Even when scale is set to 2 , I see 4 targets ( 1 for each host in the setup) being programmed in the haproxy.conf

<img width="762" alt="screen shot 2016-04-06 at 5 36 45 pm" src="https://cloud.githubusercontent.com/assets/4266958/14336984/8536380a-fc1e-11e5-82e0-fbd360a95f92.png">

**Comment by alena1108** [comment]
@prachidamle looks like today we include all the nodes registered within k8s, as lb targets. We should only pick the nodes where instances behind the lbs, are running.

**Comment by EugenMayer** [comment]
I have the same issue, pretty severe. I have one LDAP server and routing 389 to one container, scale on, on 10389. In haproxy i see more entries http://pastebin.com/hNajgKyn - each entry is for one service i have a target for tottaly different ports (443) https://goo.gl/YtfUlM

iam using 1.0.1 latest stable

@alena1108 very big issue here, since this makes the LB useless here, and i use it as a main router as of rancher.com/virtual-host-routing-using-rancher-load-balancer/

Binding the container port 10389 on the host 10389 and using ldapsearch with watch -n1 results in a steady connection, doeing so with LB on port 389, every second i get a "server not avaiable"

**Comment by EugenMayer** [comment]
Upgraded to rancher server 1.1.0-dev3, cloned the lb and removed the old one - same result.
Its rancher/agent-instance:v0.8.1

to illustrate how this looks like, here a screencast - watch -n1 ldapsearch.. 

https://goo.gl/veBhoz

**Comment by alena1108** [comment]
@EugenMayer the original issue exists for k8s setups only, and there is no hostname routing supported for k8s as well. Are you observing your issue on k8s as well? If not, it might be something else.

**Comment by EugenMayer** [comment]
no, i am using cattle. Maybe i mixed this up, thought its the same issue

**Comment by alena1108** [comment]
@wlan0 can you confirm that k8s code expects your services' endpoints to be available on every host?

**Comment by wlan0** [comment]
@alena1108 As stated in the docs here -> http://kubernetes.io/docs/user-guide/services/#type-nodeport, each node will proxy that port. Which means that every node acts as an LB target. The service need not have a pod on that node.

**Comment by alena1108** [comment]
I think it would still make sense to exclude the service endpoint w/o any targets on the host, from the LB configured on Rancher. We should research how to do it, fix it on our cloud provider side by NOT including external service link having 0 targets on the host.
