### ISSUE TITLE
Sidekick instance gets recreated on primary instance health check failure (and vice versa) 

### ISSUE THREAD

**Issue by ianwalter** [rancher/rancher#4311]
Rancher Version: v1.0.0

Docker Version: 1.9.1 build a3a1d5

OS: Debian 8 Jessie

Steps to Reproduce: 
1. Create a service with a sidekick that's used as a data container and has a health_check strategy of recreate
2. Have the service's main container fail the health check

Results: 
The sidekick gets recreated along with the main container.
If you specify `strategy: none` for the sidekick under health_check, you get the following error:
```
Bad response statusCode [422]. Status [422 status code 422]. Body: [code=MissingRequired, fieldName=port] 
```

Expected:
That the service's main container gets recreated but the sidekick does not.

---

This is a major pain-point. I was so happy that Rancher allowed me to set up a Gitlab instance fairly easily and then so sad when, after setting that instance up, lost all of my data because I was installing a firewall and my gitlab instance failed its health check and so it was recreated.

So my questions are:
1. How can I configure my sidekick to not get recreated on a health check failure?
2. Can we make it the default that sidekicks do NOT inherit their services health check strategy? In the rancher-compose the health_check configuration is specified on the server, not the sidekick, so why would someone assume that it also applies to the sidekick?

**Comment by alena1108** [comment]
@ianwalter 

> If you specify strategy: none for the sidekick under health_check, you get the following error:

looks like the health check port wasn't specified. I was able to configure health check for data container.

The real bug here is - we recreate the entire unit (primary+sidekick(s)) as long as one of the instances of the bundle becomes unhealthy. We should be smarter about it, and leave out healthy instances.

**Comment by ianwalter** [comment]
@alena1108 Yes sidekicks probably never should be recreated. You shouldn't have to add a health check to a sidekick right? How would the health check work? Even if you wanted a health check for a sidekick, you shouldn't have to specify a port.

**Comment by alena1108** [comment]
@ianwalter no, you don't have to add a health check. If health check is not defined, no health check will be performed.

>  Even if you wanted a health check for a sidekick, you shouldn't have to specify a port.

:) it implies you don't need a health check. Noop means "I want to perform the health check, but only want to see the health reported, no need to act on it". And you a right, for your use case - sidekick as a data container - you don't need a health check. But people use sidekicks for scheduling purpose also (when they want primary+sidekick bundle to be deployed on the same host). For this use case, health check even on a sidekick makes sense.

**Comment by alena1108** [comment]
@ianwalter reverted the fix after chatting with other engineers. Destroying the entire deployment unit (n sidekicks) if primary container fails, is actually a correct behavior. The sidekick should be deployed and destroyed as a whole thing. K8s does it this way for Pods.
