### ISSUE TITLE
[BUG]Edit ConfigMap With RancherUI

### ISSUE THREAD

**Issue by LaoZhang-best** [rancher/rancher#43125]
When the characters of each line exceed a certain length, after saving through the UI, all non-blank lines will eventually have extra line breaks. It appears every time you save.

**Comment by kangjd81** [comment]
rancher v2.7.9 Same problem ㅜㅜ

**Comment by mohag** [comment]
If the long lines are comments in things like nginx config files, this results in an unusable, corrupted config.

**Comment by LaoZhang-best** [comment]
@alves08

**Comment by kangjd81** [comment]
same issue
#42288

**Comment by richard-cox** [comment]
@LaoZhang-best thanks for raising this issue. There was another on rancher/rancher with more detail. I've transferred that over to this repo and will close this as a duplicate
