### ISSUE TITLE
When viewing Service, container stats graphs wrap unnecessarily onto 2nd line

### ISSUE THREAD

**Issue by sshipway** [rancher/rancher#4312]
When on the Service view page, the table of Service instances has 'Stats' as the 6th column, holding 4 thumbnail graphs of container performance.  These should be placed in a horizontal line; however the 4th is often placed on a lower level, causing the screen to repeatedly re-format as the images are loaded.  This happens when there is considerable spare horizontal space in the table to widen the Stats column, but for some reason other columns have unused width.  If the window is full-screened this does not happen, but as it gets smaller the stats graphs wrap earlier than they should.

I think that the stats graphs should never wrap to a 2nd line, since the whole table reformats when the windows gets too narrow in any case.

Using Firefox 38.7

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.0.0` Cattle: `v0.159.2` UI: `v0.100.3` |
|Access|`ldap` `admin`|
|Route|`service.containers`|

**Comment by tfiduccia** [comment]
version - master 4/28
Verified fixed
