### ISSUE TITLE
[RFE]  Feature flag to have RKE1 disabled 

### ISSUE THREAD

**Issue by gaktive** [rancher/rancher#43131]
**Describe the solution you'd like**
UI is working on https://github.com/rancher/dashboard/issues/9823 to explore disabling RKE1 for certain scenarios. Certain users would not like to expose the option to deploy RKE1 (or RKE) for Harvester, forcing their base to use RKE2 only. There may be other use cases whereby a limitation for this distro would be beneficial, including encouraging more RKE2 usage.

We would like a feature flag on the backend to allow Rancher to be deployed without RKE1 as an option.

**Comment by nwmac** [comment]
Suggest the feature flag is named: `rke1-ui`, description: `Enable RKE1 provisioning in the Rancher UI` - default is true.

**Comment by nwmac** [comment]
Backend PR - https://github.com/rancher/rancher/pull/44966

**Comment by gaktive** [comment]
Based on that PR merged and reports of this working now, RKE1 can be disabled. Closing this ticket but @nwmac let me know if there's anything still to do here. This could also help teams like Harvester (fyi @rebeccazzzz )
