### ISSUE TITLE
SSL is not setup in the load balancer when using Source IP/Port mapping.

### ISSUE THREAD

**Issue by LoreleiAurora** [rancher/rancher#4314]
Rancher Version: 1.0.0

Docker Version: 1.10.1, build 9e83765

OS: ros version v0.4.3

Steps to Reproduce: 

Create a new load balancer with Listening Ports set to Source IP/Port (e.g. 1.2.3.4:443) and the ssl checkbox selected.

Results: SSL is not running on the port

Expected: SSL to be running on the port

As far as i can see this issue only occurs with Source IP/Port mappings.

**Comment by tfiduccia** [comment]
Version - v1.0.1-rc3
Verified fixed
