### ISSUE TITLE
[v2.8] [RFE] Add `CIS-1.8` (k8s v1.26) Scan capability

### ISSUE THREAD

**Issue by andypitcher** [rancher/rancher#43159]
CIS Workbench has released [CIS-1.8 for k8s v1.26](https://workbench.cisecurity.org/benchmarks/12958) (on oct 6th). 

This issue is pending the creation of cis-1.8 in [kube-bench's cfg](https://github.com/aquasecurity/kube-bench/tree/main/cfg). We will start integrating CIS-1.8 to Rancher cis-benchmark once the profile will be made available upstream.

Past issue for CIS-1.7 : https://github.com/rancher/rancher/issues/41631

**Comment by andypitcher** [comment]
### Procedure to develop CIS-1.8 scan capability (generic, rke1, rke2 and k3s)

#### Places that will be modified:

- `rancher/security-scan/package/cfg` -> add the profiles 
   - cis-1.8
   - rke-cis-1.8-permissive 
   - rke-cis-1.8-hardened
   - rke2-cis-1.8-permissive 
   - rke2-cis-1.8-hardened
   - k3s-cis-1.8-permissive
   - k3s-cis-1.8-hardened

- `rancher/charts/rancher-cis-benchmark(-crd) `-> update the chart with the new profiles
- `rancher/rancher-docs` -> hardening-guides & self-assessment-guides

**Note:** CIS-1.8 will use CIS-1.7 profiles as baseline, this is why it's really important to list what checks have been added/modified/removed in CIS-1.8.
Here are the two ways to confirm the changelogs:

- From CIS Workbench, read the changes, see [CIS Kubernetes CIS-1.8](https://workbench.cisecurity.org/benchmarks/12958).
- From kube-bench, compare CIS-1.7 vs CIS-1.8 files (once CIS-1.8 will be added), here is a command to generate the diff.
```
git clone https://github.com/aquasecurity/kube-benc
cd kube-bench/cfg
for component in {config.yaml,controlplane.yaml,etcd.yaml,master.yaml,node.yaml,policies.yaml}; do echo "[$component]" && diff cis-1.24/$component cis-1.7/$component | tee -a changelog_$component; done
```


#### For each profile (e.g. rke-cis-1.8-permissive):

1. Create one PR

**Comment by mitulshah-suse** [comment]
@andypitcher The cis-1.8 profile is for k8s 1.27 not 1.26 as per the benchmark documentation. I tried to check the 1.7 benchmark if they mentioned 1.26 there, but cannot find it on the cis benchmark website. Not sure what happened there.

**Comment by samjustus** [comment]
@andypitcher any update on this? should this be in for Q1?

**Comment by mitulshah-suse** [comment]
Its not adopted by kube-bench yet. Dont even see any PRs about it yet, so might be a while before its adopted and released.
I don't think we can take a call about it for Q1 until kube-bench releases it.

**Comment by andypitcher** [comment]
I agree, there are no PRs or issues related to the release of CIS-1.8 in kube-bench yet. I've opened a [discussion](https://github.com/aquasecurity/kube-bench/discussions/1524) to get more info about the release date.

**Comment by rayandas** [comment]
But it’s not released yet. So we can’t update kube-bench version and test the changes. Anyways, we’ve started working on the config files. 

/backport v2.7-Next1

**Comment by vivek-shilimkar** [comment]
Tested following scenarios with RKE1, RKE2, and K3S kubernetes clusters and cis-benchmark chart v5.1.0-rc5 on rancher v2.8.0-rc1.

1. Fresh Install of chart on non-harden and harden downstream cluster with k8s v1.26 and v1.27.
2. Upgrade checks of chart on node driver and harden downstream cluster. Following upgrade scenarios were tested.
    - k8s v1.25 --> v1.26
    - k8s v1.26 --> v1.27

3. Tested chart on non-harden and harden local clusters with k8s v1.26 and v1.27.

Some scans fail on RKE1 and RKE2 clusters but it is [expected](https://github.com/rancher/rancher/issues/42971#issuecomment-1888698491) and will be release noted. Hence closing the issue.
