### ISSUE TITLE
Not able to identify the LB service container associated with Lb service.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#4315]
Rancher Version:v1.0.0
Create a kubernetese environment with few hosts.
Created a Replication Control for nginx container with replicas 2.
Created Lb service for this RC.

Once the LB Service is created , we do not see the Lb service container (that has access to the LB ip link) being listed in Kubernetes->Services view.
<img width="1402" alt="screen shot 2016-04-06 at 5 48 34 pm" src="https://cloud.githubusercontent.com/assets/4266958/14337242/ddbf23ea-fc20-11e5-9f5e-e93b81efab37.png">

LB container is listed in the System->Stacks view under "kubernetes-loadbalancers", where it is hard to locate the LB container that was created for the LB service.

<img width="1396" alt="screen shot 2016-04-06 at 5 54 15 pm" src="https://cloud.githubusercontent.com/assets/4266958/14337239/d4fc8d42-fc20-11e5-9c95-cc8059f7f3da.png">

**Comment by alena1108** [comment]
Punting to the future. You can use ingress to load balance your services now, and ingress gives you an LB endpoint(s)

**Comment by alena1108** [comment]
@vincent99 I've started putting externalId=k8sLBServiceUUID on the corresponding LB service

**Comment by sangeethah** [comment]
Tested with rancher-server versio - v1.2.0-pre1-rc4

Now we see the nodePort url present in the LB service UI , from where the LB service is accessible:

<img width="1254" alt="screen shot 2016-07-25 at 1 39 20 pm" src="https://cloud.githubusercontent.com/assets/4266958/17116844/635dbf5e-526e-11e6-83f1-31ecab61368c.png">

**Comment by sangeethah** [comment]
NopePort URL exposed in the UI is sometimes not functional. It points to host where Lb service is not running.

**Comment by alena1108** [comment]
@vincent99 Digged in more to the K8s LB service, and thats how all these ports/nodeport stuff works. So lb service gets created with:

* port
* nodePort

pods join the LB service using selectors, and Lb gets configured by the cloud provider using "port" field. By hitting hostIp:nodePort, you are accessing the pod containers behind the service, omitting the LB. By hitting hostIp:port, you are going through Rancher LB.

I am not sure how we determine the ip address in the URL though, and whether we are planning to support showing both nodePort or lbPort in the UI. Just wanted to descrie how it works

**Comment by vincent99** [comment]
No longer applicable in 1.4.
