### ISSUE TITLE
[RFE] Rancher backups to Azure Blob Storage 

### ISSUE THREAD

**Issue by JeffParkes** [rancher/rancher#43154]
**Is your feature request related to a problem? Please describe.**
Azure Blob storage does not provide an S3 compatible API.

**Describe the solution you'd like**
Rancher Backup directly to Azure blob storage solution.

**Describe alternatives you've considered**
To have Rancher backups in Azure blob storage requires a third party solution like [s3proxy](https://github.com/gaul/s3proxy) or Minio s3 gateway (which was [deprecated](https://blog.min.io/deprecation-of-the-minio-gateway/?ref=docs-redirect) last year)

**Additional context**
The ask here is to have the ability to send Rancher backups to Azure blob storage natively in Rancher.

**Comment by walkafwalka** [comment]
Would love to see this.
