### ISSUE TITLE
Service wont't create

### ISSUE THREAD

**Issue by mouradsm** [rancher/rancher#4316]
Activating message on creating service are always running and service won't create.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.0.0` Cattle: `v0.159.2` UI: `v0.100.3` |
|Access|`localauth` `admin`|
|Route|`environment.index`|

**Comment by deniseschannon** [comment]
Can you look at the containers on the service to see what error may be displayed at the container level?

Typically, services will be stuck in creating/activating state when the containers cannot reach the scale of the service. The containers will display the error.

**Comment by deniseschannon** [comment]
@mouradsm If you have further information you can provide, please re-open.
