### ISSUE TITLE
[BUG] RKE1 node driver clusters don't work with external AWS cloud provider

### ISSUE THREAD

**Issue by kinarashah** [rancher/rancher#43175]
**Issue**:
One of the prerequisites of external (out-of-tree) aws cloud provider is to follow node naming conventions. 
> When IP-based naming is used, the nodes must be named after the instance followed by the regional domain name (`ip-xxx-xxx-xxx-xxx.ec2.<region>.internal`). https://cloud-provider-aws.sigs.k8s.io/prerequisites/ 

This can be managed by setting `hostname-override` to kubelet and kube-proxy for custom clusters via `--node-name`. But for node driver clusters, Rancher assigns hostname based on the node name generated with prefix from node pool names. This results into cloud controller manager unable to find the node by name: `Error getting instance metadata for node addresses: error fetching node by provider ID:` 

**Fix**:
- Introduce a new cloud provider field name `external-aws` 
- When cloud provider is set to `external-aws` and `useInstanceMetadataHostname` is enabled, rke-tools will fetch the hostname by querying ec2 metadata service `http://169.254.169.254/latest/meta-data/hostname`.  rke-tools will use `hostname -f` if metadata service returns empty. This name will be set as `hostname-override` to kubelet and kube-proxy. 
- `useInstanceMetadataHostname` is disabled by default. It'll need to be enabled by users to get the above mentioned behavior.

**Comment by kinarashah** [comment]
Testing usecases: 

**Rancher v2.8-head and RKE v1.5.0-rc9** 
1. Node driver clusters 
- Install v1.26/v1.27 RKE1 node driver cluster with `external-aws` and  enable `useInstanceMetadataHostname` 
- Follow rancher's aws docs PR to install aws cloud controller manager 
- Confirm LB deploy and other cloud provider checks work as expected 

2. Custom clusters 
- Install v1.26/v1.27 RKE1 custom cluster with `external-aws`  (if enabling `useInstanceMetadataHostname`, no need to pass `--node-name`) 
- Follow rancher's aws docs PR to install aws cloud controller manager 
- Confirm LB deploy and other cloud provider checks work as expected

**Comment by slickwarren** [comment]
tested on v2.8-head (a6b908d) with a hardened rke2 (1.27.6+rke2r1) local cluster:
passing criteria is: observe aws-cloud-controller pod(s) deploy with valid logs, deploy a workload with an LB service, destroy the workload/LB and observe the deletion of LB in the backend

node driver:
* rke1 on v1.27.6-rancher1-1 using external-aws with useINstanceMetadataHostname -- pass
* rke1 on v1.26.8-rancher1-1 using in-tree 
  * deploy an LB
  * -- migrate to out-of-tree and upgrade to 1.27 following new documentation -- pass
  * confirm new LBs can be created and destroyed -- pass
  * confirm existing LB is working and can be destroyed -- pass

custom cluster
* rke1 on v1.27.6-rancher1-1 using external-aws with useINstanceMetadataHostname -- pass
* rke1 on v1.26.8-rancher1-1 using in-tree 
  * deploy an LB
  * -- migrate to out-of-tree and upgrade to 1.27 following new documentation -- pass
  * confirm new LBs can be created and destroyed -- pass
  * confirm existing LB is working and can be destroyed -- pass

also updated documentation review with notes on [new install / migration steps](https://github.com/rancher/rancher-docs/pull/844#pullrequestreview-1690771834)

**Comment by kinarashah** [comment]
Reopening issue, need to set default value for the field `useInstanceMetadataHostname`. Docs and release notes would be updated to note it'll have to be disabled when users are passing custom node names for custom clusters. For all other usecases, the field will be true so that external cloud provider can find the node without `providerID`.

**Comment by slickwarren** [comment]
tested on v2.8-head(1f119bc):
* fresh install on 1.27 / using external-aws -- pass
* upgrade from in-tree to external-aws -- pass
(same test cases as https://github.com/rancher/rancher/issues/43175#issuecomment-1773537784 were ran)

there are some outstanding dashboard tickets that are still pending, but the backend work is done and working as expected

**Comment by rpo-fr** [comment]
Hi,
How can i set hostname-override in the yaml of cluster config ?
Do you have an exemple?

I'am in the case where I have a custom domain name; and I don't find the correct configuration to migrate from in-tree to externel

Thanks for your help
