### ISSUE TITLE
[CLI] Update Go dependencies in `rancher/cli`

### ISSUE THREAD

**Issue by macedogm** [rancher/rancher#43185]
This is a placeholder issue to track updates in Rancher's [CLI](https://github.com/rancher/cli) for when the code freeze period has ended. There are some outdated Go dependencies that will benefit with some bumps to improve both security and stability.

The most important dependencies to bump are:
- `github.com/docker/docker`- preferably the latest version available
- `golang.org/x/net` - `v0.17.0` or greater

Please consult with the Security team to review the final list of dependencies to bump.

**Comment by enrichman** [comment]
[This](https://github.com/rancher/cli/pull/357) PR removed the unused `github.com/docker/docker` dependency (and others). In the past it was used to generate some names, but then the command using it was removed.

The `golang.org/x/net` dependency is a bit more tricky. It's an indirect dependency of the `k8s.io/client-go`, and in `rancher/rancher` we use a fork.

The available version that we have are:
- `rancher/client-go v1.27.4-rancher1` ([go.mod](https://github.com/rancher/client-go/blob/release-1.27.4/go.mod))
- `rancher/client-go v1.28.6-rancher1` ([go.mod](https://github.com/rancher/client-go/blob/release-1.28/go.mod))

The bump for the `x/net` lib was made in the `0.27.7` so we either need to release a new `rancher/client-go v1.27.z` (with `z >= 7`), or we either bump to the `v1.28.6-rancher1`.

We don't use anything fancy from the `client-go` package, most of the things should be just about struct and configuration, so I think it's safe to bump it to the `v1.28`.

**Comment by crobby** [comment]
Dev validated.  All looks correct.
