### ISSUE TITLE
[Backport v2.7] etcd restore get stuck on "Waiting for probes: calico"

### ISSUE THREAD

**Issue by felipe-colussi** [rancher/rancher#43189]
Back-port for partial fix presented on rancher/rancher#42895    

Wile debugging rancher/rancher#42895  we found more then one problem related to race conditions on RKE2. 

The PR rancher/rancher#43158  fixed the problem were the restores were getting stuck with "Waiting for probes: calico", this should be back-ported to 2.7.9

**Comment by snasovich** [comment]
At least for now, closing this issue as per the latest testing even with the partial fix on `rancher/rancher` side etcd snapshot restore often fails on the affected RKE2 versions based on cluster configuration (for example, we're seeing ~70% failure rate with cluster getting stuck with `Waiting for probes: kube-controller-manager` on clusters with combined etcd+CP role node pools).
