### ISSUE TITLE
Refresh Catalog

### ISSUE THREAD

**Issue by cordeirojp** [rancher/rancher#4318]
How can we force a private catalog to do a git pull from the repository ?

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.0.0` Cattle: `v0.159.2` UI: `v0.100.3` |
|Access|`localauth` `admin`|
|Route|`authenticated.project.help`|

**Comment by vincent99** [comment]
![image](https://cloud.githubusercontent.com/assets/753917/14359645/5666c8e4-fca7-11e5-9654-c61a6cbc3055.png)

The same people read issues and the forum.  Please don't simultaneously post things in both.

**Comment by cordeirojp** [comment]
Thank you very much !
It's so evident that i don't imagine it ...
and sorry for the forum, i don't do it again ;-))

**Comment by marksullivancrowd** [comment]
is it possible to do this from the cli? or through an api call, using an api token?

**Comment by vincent99** [comment]
The UI is 100% client-side.  Anything it does you can do.  `curl -X POST http://rancher:8080/v1-catalog/templates?action=refresh`
