### ISSUE TITLE
[BUG] rke1 cni binaries are redundant

### ISSUE THREAD

**Issue by manuelbuil** [rancher/rancher#43199]
**Rancher Server Setup**
- Rancher version:
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version:
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:

**Describe the bug**

Different rke1 components download and install cni binaries:
* hyperkube-base
* rke-tools
* The cni plugin itself

To avoid problems we should try to have one source of truth only

**To Reproduce**

**Result**

**Expected Result**

**Screenshots**

**Additional context**

**Comment by vivek-shilimkar** [comment]
Cluster creation with all the latest (calico/flannel/canal/weave) CNIs was successful. Hence closing the issue.
