### ISSUE TITLE
[Backport] [BUG] RKE2/K3s cluster nodes get recreated on a rollback using backup/restore operator

### ISSUE THREAD

**Issue by nickwsuse** [rancher/rancher#43203]
Information about the Cluster
**Rancher Server Setup**
- Rancher version: `v2.7.6 ` >> v2.8.0-alpha2 >> `v2.7.6`
- Installation option (Docker install/Helm Chart): `Helm Chart`
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): `RKE1`, `v1.27.6`, `1.5.0-rc8`
- Proxy/Cert Details: `Self-signed`

**Information about the Cluster**
- Kubernetes version: `v1.26.8+k3s1` and `v1.26.8+rke2r1`
- Cluster Type (Local/Downstream): `Node driver AWS  3 worker, 3 etcd, 2 cp k3s`, `Node driver Linode  1 worker, 1 etcd + cp RKE2`, 

**Describe the bug**
On a rancher roll back from v2.7.6 upgraded to v2.8.0-alpha2 back to v2.7.6, notice that rke2 and k3s nodes are getting recreated,

**To Reproduce**

1. Install rancher on version 2.7.6
2. Create a node driver k3s and RKE2 cluster with the specs mentioned above.
3. Install rancher backup/restore chart version in the local cluster with config set to S3, version `102.0.1+up3.1.1`
4. Take a backup from the rancher backup/restore page and the backupfile gets saved in the s3.
5. Upgrade rancher server to v2.8.0-alpha2
6. Rollback to 2.7.6 on the same rancher server by running the cleanup https://github.com/rancher/rancher-cleanup
7. Install rancher server by following the instructions from here: https://ranchermanager.docs.rancher.com/v2.7/how-to-guides/new-user-guides/backup-restore-and-disaster-recovery/restore-rancher
8. Once rancher server is up, notice the clusters go into updating state 

**Result**
Notice the nodes are recreated on both the downstream clusters of rke2 and k3s. 

**Expected Result**
Nodes not recreated for the downstream clusters

**Screenshots**
<img width="600" alt="2023-10-05_20-08-13" src="https://github.com/rancher/rancher/assets/38144301/4987f1d8-43de-491b-b73c-dc0d02882764">

**Additional context**
Initially noticed the following logs in rancher pods, after checking the AWS, noticed new nodes were created.
```
2023/10/05 14:35:46 [INFO] Deleted cluster node machine-kp6sg [anuk3srbs-e-534c38cb-cgdxw]
2023/10/05 14:35:46 [ERROR] error syncing 'fleet-default/anuk3srbs-bootstrap-template-prd6x': handler rke-bootstrap: failed to delete fleet-default/anuk3srbs-bootstrap-template-prd6x-machine-plan /v1, Kind=ServiceAccount for rke-bootstrap fleet-default/anuk3srbs-bootstrap-template-prd6x: serviceaccounts "anuk3srbs-bootstrap-template-prd6x-machine-plan" not found, failed to delete fleet-default/anuk3srbs-bootstrap-template-prd6x-machine-plan rbac.authorization.k8s.io/v1, Kind=Role for rke-bootstrap fleet-default/anuk3srbs-bootstrap-template-prd6x: roles.rbac.authorization.k8s.io "anuk3srbs-bootstrap-template-prd6x-machine-plan" not found, requeuing
```

Note:

1. The issue is not noticed when we roll back on a different rancher server following the docs https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/backup-restore-and-disaster-recovery/migrate-rancher-to-new-cluster 
2. Also not noticed when docker upgrade/rollback is performed following the docs https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade/other-installation-methods/rancher-on-a-single-node-with-docker/upgrade-docker-installed-rancher
3. Observed consistently 2 out of 2 times when the roll back is performed on the same rancher server following the docs https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/rollbacks

**Comment by snasovich** [comment]
Closing as out of scope for 2.7.9. It may get reopened if/when it gets back to 2.7.x scope and milestone will be assigned then.

**Comment by sowmyav27** [comment]
@snasovich Let's have the issue opened and in `2.7.x` milestone, and if it needs to be prioritized for any further 2.7.x release, this can be picked up then. Since this is still an issue in 2.7.x branch, let's have the issue in the open state.

**Comment by sowmyav27** [comment]
Validated using latest cleanup script image - https://github.com/rancher/rancher/issues/43070#issuecomment-1773435168. Issue isn't seen anymore.
