### ISSUE TITLE
Allow for dynamic commands in CATTLE_AGENT_IP

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#4322]
@vincent99 if you think this is a bad idea, feel free to close it.

The UI suports setting CATTLE_AGENT_IP but it wraps it in single quotes. Which makes this not work:
```
sudo docker run -e CATTLE_AGENT_IP='$(docker-machine ip docker10)'  -d --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v0.11.0 http://10.0.2.2:8080/v1/scripts/....
```

It would be cool/useful if that did work, but maybe you intentionally used single quotes to prevent exactly that?

**Comment by vincent99** [comment]
This was changed to double quotes at some point in the past..

**Comment by cjellick** [comment]
Confirmed
