### ISSUE TITLE
[RFE] Rancher view right access for grafana only. 

### ISSUE THREAD

**Issue by ilyavbokov** [rancher/rancher#43223]
hello. how i can give new user only to view grafana?

**Comment by gabrielaomoraes** [comment]
@ilyavbokov can you please use the RFE template to provide more details of the feature you need?
It will help us triage and act on it quicker ;)

**Comment by ilyavbokov** [comment]
hello. if i add read-only user, with permissions to delete nodes, grafana isn't active. how i can set to user rights to view only grafana and button will be active.

**Comment by ilyavbokov** [comment]
link to screenshot with error Grafana not available

[](https://ibb.co/9VM2DZZ)
