### ISSUE TITLE
[BUG] Rancher-Webhook dosn't deploy on Downstream Clusters after Upgrade from 2.6.8 to 2.6.13

### ISSUE THREAD

**Issue by mueller-tobias** [rancher/rancher#43238]
**Rancher Server Setup**
- Rancher version: 2.6.13
- Installation option (Helm Chart): RKE1 (1.24.4)
- Proxy/Cert Details: Webproxy for Internet Access is used in addition with a private PKI

**Information about the Cluster**
- Kubernetes version: .121.14
- Cluster Type: Downstream
 * Infrastructure Provider = VMware vSphere (RKE1)

**User Information**
- What is the role of the user logged in? Admin

**Describe the bug**
We upgraded our rancher instance from 2.6.8 to 2.6.13. The Downstream Cluster where update and are Active again. The rancher-agent got upgraded to 2.6.13 as well as the cattle-cluster-agent. But the rancher-webhook constantly runs in an error during the helm deployment because the pod isn't starting while the rancher-webhook-tls secret is missing:

> MountVolume.SetUp failed for volume "tls": secret "rancher-webhook-tls" not found.

**To Reproduce**
We've tried with a test cluster first and that cluster did made the upgrade sucessfully. Also from 2.6.8 to 2.6.13. But on the test cluster the webhook-chart is installed in version rancher-webhook:1.0.9+upd0.2.10. 

On the bugged deployment, rancher says the chart has the version rancher-webhook:1.0.5+upd0.2.6

**Expected Result**

Upgrade from 2.6.8 to 2.6.13 with a running rancher-webhook pod

**Additional context**
I've seen that there's a [adjust-downstream-webhook](https://github.com/rancherlabs/support-tools/blob/master/adjust-downstream-webhook/adjust-downstream-webhook.sh) Script in the Support Tool Repository that also ready for 2.6.13. But normally is only used when a cluster got downgraded, but that wasn't the case here.
According to that the helm chart should be installed in Version 1.0.9+up0.2.10 as in the successful installation of the test cluster.

**Comment by MKlimuszka** [comment]
@mueller-tobias , did you ever get around this?

**Comment by mueller-tobias** [comment]
@MKlimuszka  Yes, we've got the following infos from the support:

> This problem is fixed in the Rancher v2.7.5=< under this issue https://github.com/rancher/rancher/issues/41730
> 
> The root cause of the issue is that in v2.6.13, the downstream agents do not specify which version of rancher-webhook to install. Instead, the agent installs the latest version that it can find in a fresh install of the v2.6.13 agent; this would result in rancher-webhook 1.0.9+up0.2.10 being installed. This is because 1.0.9+up0.2.10 is the only known version in the local rancher-charts repository.
> 
> In the above upgrade scenario, the previously running agent had already saved an older version of the rancher-charts repository, which contained an older version of rancher-webhook (1.0.5+upd0.2.6). It appears that the agent installed rancher-webhook before its local repository of rancher-charts was updated, resulting in 1.0.5+upd0.2.6 being installed. Rancher-Webhook was never upgraded after installation because the v2.6.13 agents do not specify a specific version that needed to be installed.
> 
> The recommended workaround would be to run the [adjust-downstream-webhook](https://github.com/rancherlabs/support-tools/blob/master/adjust-downstream-webhook/adjust-downstream-webhook.sh) script. As noted in the linked issue root cause for the creation of the script is different than that of the customer, but the fix is the same.
> 
> So the solution is either upgrade or use the workaround script via the link above.

We did an upgrade of the rancher Instance. That solved the issue.
