### ISSUE TITLE
[RFE] Add the flag delete_on_termination when creation Openstack Node

### ISSUE THREAD

**Issue by gcezaralmeida** [rancher/rancher#43244]
**Is your feature request related to a problem? Please describe.**
We are facing issues when Rancher has to delete a worker or master node in OpenStack. The node is deleted successfully; however, the boot volume remains in the OpenStack project and consumes quota. 

**Describe the solution you'd like**
The solution would be to add an option to the OpenStack CRD to enable the delete_on_termination flag. With this flag, we can ensure that the boot volume can be deleted. 

**Describe alternatives you've considered**
Nowadays, I need to delete all volumes manually or use a script to do it.

**Comment by gcezaralmeida** [comment]
Still valid

**Comment by gcezaralmeida** [comment]
...

**Comment by syslao** [comment]
Ыame here.
I use Openstack to create test clusters and in the end I have to clean everything by hand or with a script, which is very inconvenient
