### ISSUE TITLE
Network Agent will route traffic from any interface

### ISSUE THREAD

**Issue by vincent99** [rancher/rancher#4324]
Should only route traffic from local containers into the managed network.

https://forums.rancher.com/t/routing-managed-network/2252

**Comment by chshawkn** [comment]
@vincent99 @ibuildthecloud @deniseschannon

Although this is a bug, but I do need a convenient way like this to access containers in managed network.
I think we should not simply add a iptables rule to ban this.
We need a config option to enable/disable communicate with managed network.

I have multi rancher hosts, after execute ip route add 10.42.0.0/16 via <rancher node x>, I can only access containers on rancher node x, cant access containers on rancher node y, z ... I found the vxlan container did not forward packets to other hosts.

I want to access any container in managed network via any rancher host. 
How can I achieve this? Please help!

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
