### ISSUE TITLE
Container stats broken - not pulling current info

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4325]
Version - v1.0.1-rc1

Steps to Reproduce: 
1. Create a stack and add 1 service to it with the ubuntu image
service1:
  log_driver: ''
  labels:
    io.rancher.container.pull_image: always
  tty: true
  log_opt: {}
  image: ubuntu:14.04.3
  stdin_open: true

2.  After service starts go to the containers details page

Results: Stats don't work properly, they seem to get stuck and don't report every second.

Expected: Stats should work properly

**Comment by will-chan** [comment]
There is known issue with docker 1.11 support.  Is this what you had when you saw this?

**Comment by tfiduccia** [comment]
Version - master 6/17
Verified fixed
