### ISSUE TITLE
[BUG] Rancher Backup option not available 

### ISSUE THREAD

**Issue by aamirpatel** [rancher/rancher#43267]
The Rancher Backup app is not available from the Cloud Tool option or Under Apps->Charts option.

**Comment by Richardswe** [comment]
More info, Rancher version?

**Comment by aamirpatel** [comment]
RAN201V2.7

**Comment by aamirpatel** [comment]
![image](https://github.com/rancher/rancher/assets/19854591/729f418b-006a-4f29-bf6b-48c76d3669e6)

**Comment by ctroyp** [comment]
> ![image](https://private-user-images.githubusercontent.com/19854591/278206910-729f418b-006a-4f29-bf6b-48c76d3669e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxMDk0NTksIm5iZiI6MTcxMDEwOTE1OSwicGF0aCI6Ii8xOTg1NDU5MS8yNzgyMDY5MTAtNzI5ZjQxOGItMDA2YS00ZjI5LWJmNmItNDhjNzZkMzY2OWU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEwVDIyMTkxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjYTgyNzdiNzkxYmIxYzJkZDBiOTEzYzZjYjk3MWIzNjFjNzA5ZDhmY2U1ZDMyZWE4MDI2NzZjZWFmNzNkNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZdtAAYPEAhgbV_hEpXuJgWqLqpb5U1FiQiaQDHtwWEg)

@aamirpatel did you have a solution? Experiencing the same here.
