### ISSUE TITLE
[Backport v2.7] Cluster breaks when scaling down etcd nodes in an RKE2 cluster

### ISSUE THREAD

**Issue by Sahota1225** [rancher/rancher#43263]
Backport of rancher/rancher#43097

Rancher Server Setup

Rancher version: 2.8-head commit id: 01127d8 and v2.7.8
Installation option (Docker install/Helm Chart): docker and helm install of rancher
If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1
Information about the Cluster

Kubernetes version: on 2.8-head - v1.27.6+rke2r1 and on 2.7.8 - v1.26.8+rke2r1
Cluster Type (Local/Downstream): Downstream RKE2
User Information

What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) admin
Describe the bug
Cluster breaks when scaling down etcd nodes in an RKE2 cluster

To Reproduce

Deploy a 3 etcd, 2 cp and 3 worker nodes RKE2 cluster.
Once the cluster is Active, Scale down etcd nodepool by 1
The node is deleted and cluster comes up Active
Scale down the nodepool by one more node
Cluster is stuck in Updating state with message - configuring bootstrap node(s) sow-new-pool1-58d8d65466x8nszz-n4cc6: waiting for probes: etcd
One of the etcd nodes is stuck in Deleting state.
Error seen in Rancher logs
2023/10/07 15:49:44 [ERROR] [rkebootstrap] fleet-default/sow-new-bootstrap-template-6hmgn: cluster fleet-default/sow-new machine fleet-default/sow-new-pool2-5fc989cd98x4ghfb-q6xmh was still joined to deleting etcd machine fleet-default/sow-new-pool1-58d8d65466x8nszz-kmk64
Screen Shot 2023-10-07 at 10 04 20 PM
Expected Result
etcd nodes should get deleted and cluster should come up Active

Additional context

I am able to reproduce this on 2.7.8 rancher version also
Could be related to this - https://github.com/rancher/rancher/issues/42034
looks similar to this one that's reported - https://github.com/rancher/rancher/issues/42709
@[sowmyav27](https://github.com/sowmyav27) sowmyav27 added [kind/bug](https://github.com/rancher/rancher/labels/kind%2Fbug) [team/area2](https://github.com/rancher/rancher/labels/team%2Farea2) labels [2 weeks ago](https://github.com/rancher/rancher/issues/43097#event-10582278375)

**Comment by snasovich** [comment]
This is ready to be tested on `v2.7-head` since https://drone-publish.rancher.io/rancher/rancher/10874 passed.
The plan is to no longer include this fix in 2.7.9 release for various reasons so changing the milestone accordingly.

**Comment by snasovich** [comment]
The initial changes to fix this issue are believed to be the reason for issue https://github.com/rancher/rancher/issues/43329 so they are reverted for `release/v2.7` branch as well per https://github.com/rancher/rancher/pull/43352. This issue is back to development queue.
