### ISSUE TITLE
External Service health check is not functioning

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4326]
Version - v1.0.1-rc1

Steps to Reproduce: 
1.  Create an external service through the UI with:
hostname: vtf.me
health_check:
    port: 80
    interval: 2000
    initializing_timeout: 60000
    unhealthy_threshold: 3
    strategy: recreate
    request_line: 'GET "/404" "HTTP/1.1\r\nHost: vtf.me"'
    healthy_threshold: 2
    response_timeout: 2000

Results: Says it's healthy

Expected: Should not be healthy as the vtf.me/404 does not exist.

**Comment by tfiduccia** [comment]
This is a limitation and will not work according to Alena.  So please hide the tab.

**Comment by sangeethah** [comment]
This is the feature request for Health checks for external services - https://github.com/rancher/rancher/issues/2564

**Comment by vincent99** [comment]
It can't be hidden because they're used for Loadbalancer targets.  Added an info box (and hid the strategy, because it makes no sense here..)

**Comment by tfiduccia** [comment]
Version - v1.0.1-rc3
Verified text added.
