### ISSUE TITLE
Cannot setup custom CIS benchmarks in Rancher 2.6.11/12/13 and in Rancher 2.7.3

### ISSUE THREAD

**Issue by rayandas** [rancher/rancher#43268]
Issue description: Setting up a custom cis benchmark following the [documentation](https://ranchermanager.docs.rancher.com/v2.6/integrations-in-rancher/cis-scans/custom-benchmark), It ends up with a scan that does not work.

Business impact:
Cannot create custom cis benchmarks with CIS Operator

Troubleshooting steps:
Config files downloaded from: [Aqua](https://github.com/aquasecurity/kube-bench/tree/main/cfg)

Repro steps:

- Download all cis version yamls from [Aqua](https://github.com/aquasecurity/kube-bench/tree/main/cfg/cis-1.23)
- Add the target_mapping to the config.yaml for the custom configuration
- Create the custom configmap with all required yamls
 
```
±|master ✗|→ kubectl get nodes
NAME   STATUS   ROLES                      AGE    VERSION
2      Ready    controlplane,etcd,worker   5d1h   v1.22.13
±|master ✗|→ kubectl create cm custom-benchmark --from-file=custom-benchmark
configmap/custom-benchmark created
±|master ✗|→ kubectl get cm
NAME               DATA   AGE
custom-benchmark   6      13s
kube-root-ca.crt   1      5d1h
```
 
- Create a new benchmark from Rancher UI on a downstream cluster using the UI
- Create a new profile and a new CIS Scan. The scan does not complete and the sonobuoy pod for the custom scan goes into Error /Crashloopbackoff status.

Workaround:
Is a workaround available and implemented? no
What is the workaround:

**Actual behavior**: 
The scan runs but endlessly and the generated sonobuoy container goes into CrashloopBackoff with an error, that cannot write the output to /tmp/out/sonobuoy.error

**Expected behavior**:
Custom CIS scan works fine

SURE-6611

**Comment by rayandas** [comment]
Seems like a duplicate of https://github.com/rancher/cis-operator/issues/162. Validating it.

**Comment by rayandas** [comment]
We've validated it on Rancher v2.7.8 with K8s v1.26.8 and CIS Benchmark version v4.2.0. We couldn't reproduce the bug. The custom benchmark scan is running fine.

There's certainly some issue with your config.yaml (there shouldn't be any tab/space issue). Please make sure the config.yaml consists of everything mentioned in the top level config.yaml file https://github.com/rancher/security-scan/blob/master/package/cfg/config.yaml and the config file which is inside the benchmark profile eg: https://github.com/rancher/security-scan/tree/master/package/cfg/rke-cis-1.7-permissive 

Also the final config.yaml file should have the custom benchmark name and components mentioned inside the "target_mapping".

**Comment by rayandas** [comment]
I just tested with the given config.yaml. It's working fine. 
I see the profile name mentioned in config.yaml under "target_mapping" is tkgi-1.2.53 but you're creating the benchmark version with the name "test-benchmark". This is where the problem happening. 
The benchmark version name should be same as the profile name mentioned under "target_mapping" in config.yaml.

**Comment by samjustus** [comment]
@rayandas  thank you! i will see what the customer says and then close
