### ISSUE TITLE
Service containers created through Kubernete's catalog and failing, are not removed

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4327]
Version - v1.0.1-rc1

Steps to Reproduce:
1.  Create a kubernetes environment
2.  Add three hosts
3.  Go to Catalog and add WordPress
4.  Go to hosts
 
Results: Notice that the wordpress service has three containers.  2 stopped and 1 active.  The 2 stopped containers actually failed because the sql container wasn't ready yet.  But instead of failing, removing, then recreating.  It's failing, stopping, then recreating until one runs.
![image](https://cloud.githubusercontent.com/assets/11514927/14369766/7c84f71e-fcdc-11e5-8aae-84395e47c6e6.png)

Error from containers:
4/7/2016 4:04:40 PMWarning: mysqli::mysqli(): MySQL server has gone away in - on line 10
4/7/2016 4:04:40 PM
4/7/2016 4:04:40 PMWarning: mysqli::mysqli(): Error while reading greeting packet. PID=165 in - on line 10
4/7/2016 4:04:40 PM
4/7/2016 4:04:40 PMWarning: mysqli::mysqli(): (HY000/2006): MySQL server has gone away in - on line 10
4/7/2016 4:04:40 PM
4/7/2016 4:04:40 PMMySQL Connection Error: (2006) MySQL server has gone away

Expected:  Should removed failed containers.

Comment:  I'm not sure if this a bug in the catalog, kubernetes or if it's the way the catalog is actually setup.

**Comment by alena1108** [comment]
@tfiduccia stop->recreate instead of remove->recreate is default kubernetes behavior. Please refer to for more info: https://github.com/rancher/rancher/issues/4351
