### ISSUE TITLE
[BUG] Failed to Find Service Account on Cluster Registration

### ISSUE THREAD

**Issue by Erodotos** [rancher/rancher#43270]
**Rancher Server Setup**
- Rancher version: 2.7.3
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): AKS 1.24.6

**Information about the Cluster**
- Kubernetes version: 1.25.11
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Imported from Azure (AKS 1.25.11) 

**Describe the bug**
 Failed to Find Service Account on Cluster Registration. There follows a the exact error

level=fatal msg="looking up cattle-system/cattle ca/token: failed to find service account cattle-system/cattle: Get \"https://10.0.0.1:443/api/v1/namespaces/cattle-system/serviceaccounts/cattle\": EOF"

**Comment by gabrielaomoraes** [comment]
@Erodotos can you please provide details on how to reproduce the issue? If it shows in the UI, a screenshot will also help

**Comment by Erodotos** [comment]
Hi @gabrielaomoraes I am not quite sure how to reproduce the issue. I described my setup above. I am importing an existing AKS cluster into Rancher using the UI. The registration project fails when starting the cattle-cluster-agent on the downstream cluster. 

I share the exact log where the error occurs.

time="2023-10-26T18:15:49Z" level=fatal msg="looking up cattle-system/cattle ca/token: failed to find service account cattle-system/cattle: Get \"https://10.0.0.1:443/api/v1/namespaces/cattle-system/serviceaccounts/cattle\": EOF" 

Note that the Service Account named "cattle" has no associated secrets. Will the secret be linked when 
cattle-cluster-agent comes up?

Another thing that comes in my mind regarding the issue's root, is related to supported k8s versions. Is there any possibility the problem to occur due to incompatible versions?
