### ISSUE TITLE
[BUG] v2.8.0 - rke-tools v0.1.95 not included in rancher-images - blocks RKE1 provisioning with private registries.

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#43287]
**Rancher Server Setup**
- Rancher version: `v2.8.0-rc1`
- Installation option (Docker install/Helm Chart): chart rke2 HA 

**Information about the Cluster**
- Kubernetes version: `v1.25.14+rke2r1`
- Cluster Type (Local/Downstream): local Rancher

**User Information**
- What is the role of the user logged in? Admin

**Describe the bug**

-`rancher/rke-tools:v0.1.95` image is not getting pulled from a private registry as it is missing in `rancher-images.txt`

Image `rancher/rke-tools:v0.1.94` is in the image list.

RKE provisioning Kubernetes version: `v1.25.14-rancher1-1`

**To Reproduce**

- Create a Docker registry
- Push all images in `rancher-images.txt`
- Create local cluster for Rancher install and install Rancher with the private registry configuration
- Provision an rke2 or k3s cluster

**Result**

[Failed to pull image [<registry>/rancher/rke-tools:v0.1.95] on host [52.53.192.92]: Error response from daemon: manifest for <registry>/rancher/rke-tools:v0.1.95 not found: manifest unknown: manifest unknown] 

RKE2 and K3s unaffected
RKE1 provisioning impacted

**Expected Result**

`rancher/rke-tools:v0.1.95 ` listed in `rancher-images.txt`
Registry used for Rancher should contain the image and Rancher should be pulling it successfully

**Notes**

`rke-tools:v0.1.95` is in the KDM
This version isn't in the `rke-tools` Rancher repo releases.

**Comment by kinarashah** [comment]
Available to test with `v2.8.0-rc2`

**Comment by izaac** [comment]
Validated on Rancher `v2.8.0-rc2`
