### ISSUE TITLE
Changed stack name not reflected in host or container details page

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4328]
Version - v1.0.1-rc1 

Steps to Reproduce:
1.  Create a stack and call it Test
2.  Add a service and start it up
3.  Edit the stack and change the name to ChangedName
4.  Go to host page or container details page

Results: The project_name is still Test

Expected: Project_name should be ChangedName

**Comment by vincent99** [comment]
The host screen groups containers by the labels on the containers... one of those is the stack name, which is not updated when the stack is renamed.  Fixing it requires tying that back to the actual stack resource, which is basically the same as doing https://github.com/rancher/rancher/issues/2557

**Comment by tfiduccia** [comment]
Version - 12/20
Host page is fixed.  But in the container details page, both the drop-down and the Stack/Service section are still showing old stack name.

**Comment by tfiduccia** [comment]
Entering separate issue for container.  And closing this one
