### ISSUE TITLE
[BUG] first kubectl command fails when no service account has been created

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#43293]
Rancher Version: 2.6.11

**Issue description:**
When an admin user (can access all downstream clusters without any cluster roles being assigned) creates a kubeconfig in a cluster where it does not have a serviceaccount in the cattle-impersonation-system namespace, the first kubectl command fails with the following error:

`Error from server (InternalError): an error on the server ("unable to create impersonator account: error setting up impersonation for user u-hwltnppexi: failed to get secret for service account: cattle-impersonation-system/cattle-impersonation-u-hwltnppexi, error: resource name may not be empty") has prevented the request from succeeding`

When the user runs a subsequent kubectl command using that kubeconfig, it will return without issue since the serviceaccount/secret is created after the first command is run.

This same behaviour existed before 2.6.10 but it is now only an issue due this change:

https://github.com/rancher/rancher/commit/f08c50fa8ea207cbd310e67c8af8cf3b6d13df72#diff-8a853a257f4c9e8e5812b706a4f6a56eaa32ff67e57f9ac5ac4f78f1e1659f04

 

**Business impact:**
User has a pipeline that implements the above process and always fails on first run (when using new clusters). Subsequent reruns are successful.

**Troubleshooting steps:**
adding the admin user as a cluster member/owner creates the serviceaccount/secret which alleviates this issue.

 

**Workaround**:
Is workararound available and implemented? YES

run the code again, or add the cluster member/owner role to the account.

**Actual behavior:**
the first command returns an error.

**Expected behavior:** first command runs successfully, and no error code is returned.

Additional notes:
similar to https://github.com/rancher/rancher/issues/36096

**Comment by samjustus** [comment]
SURE-6026

**Comment by hamistao** [comment]
I am facing the following problem in a downstream cluster(1.35.2+rke2r1) on Rancher(2.40.0-alpha13 on 1.35.2+k3s1) provisioned with Harvester v1.7.1

This issue happens with following namespaces:

```
auto-fleet-test-namespace-mnyjs
cattle-logging-system
kube-system
cattle-impersonation-system
kube-node-lease
cattle-local-user-passwords
compliance-operator-system
```

And after one query in that namespace, it seems the subsequent requests in the same namespace over the following seconds work fine, or it could just be flakyness. I have no no issue accessing information from other namespaces.

```
➜  ~ kubectl get pods -n auto-fleet-test-namespace-mnyjs
Error from server (InternalError): an error on the server ("unable to create impersonator account: error getting service account token: error setting up impersonation for user user-rf2wz: failed to get secret for service account: cattle-impersonation-system/cattle-impersonation-user-rf2wz, error: timed out waiting for the condition") has prevented the request from succeeding (get pods)
➜  ~ kubectl get pods -n auto-fleet-test-namespace-mnyjs 
No resources found in auto-fleet-test-namespace-mnyjs namespace.
➜  ~ kubectl get pods -n auto-fleet-test-namespace-mnyjs
Error from server (InternalError): an error on the server ("unable to create impersonator account: error getting service account token: error setting up impersonation for user user-rf2wz: failed to get secret for service account: cattle-impersonation-system/cattle-impersonation-user-rf2wz, error: timed out waiting for the condition") has prevented the request from succeeding (get pods)
➜  ~ kubectl get pods -n auto-fleet-test-namespace-mnyjs
No resources found in auto-fleet-test-namespace-mnyjs namespace.
➜  ~ kubectl get pods -n auto-fleet-test-namespace-mnyjs
No resources found in auto-fleet-test-namespace-mnyjs namespace.
➜  ~ kubectl get pods -n auto-fleet-test-namespace-mnyjs
Error from server (InternalError): an error on the server ("unable to create impersonator account: error getting service account token: error setting up impersonation for user user-rf2wz: failed to get secret for service account: cattle-impersonation-system/cattle-impersonation-user-rf2wz, error: timed out waiting for the condition") has prevented the request from succeeding (get pods)
➜  ~ kubectl get pods -n local                          
No resources found in local namespace.
➜  ~ kubectl get pods -n local
No resources found in local namespace.
➜  ~ kubectl get pods -n local
No resources found in local namespace.
```
