### ISSUE TITLE
Feature charts: Need to add Istio chart 102.4.0+up1.19.0 in 2.7.x

### ISSUE THREAD

**Issue by rohitsakala** [rancher/rancher#43300]
Istio's subchart Kiali strategy is changed from anonymous to token.

For @l4zy0n3 

QA Important Scenarios other than the usual scenarios you have. 

- [ ] Upgrading from 1.18.2 to 1.19.0 in Rancher 2.7
-- Also, Confirm if you are able to login into Kiali.
- [ ] Installing 1.19.0 in Rancher 2.7
-- Also, Confirm if you are able to login into Kiali.
- [ ] Upgrading from 102.4.0+up1.19.0 in Rancher 2.7 to 103.0.0+up1.19.0 in Rancher 2.8
-- Also, Confirm if you are able to login into Kiali.
- [ ] Upgrading from 1.17 to 1.19.0 in Rancher 2.7
-- Also, Confirm if you are able to login into Kiali.

**Comment by l4zy0n3** [comment]
Tested kiali using the following scenarios
Environment:
Rancher 2.7 HA airgapped setup
Scenario 1: Upgrade Testing
Initial State: Istio 1.18 installed.
Action: Upgraded to Istio 1.19.
Outcome: Kiali token login was successful.
Scenario 2: Fresh Installation
Initial State: No Istio installation.
Action: Fresh installation of Istio 1.19.
Outcome: Kiali token login was successful.
Scenario 3: Kiali 3 Replica Testing
Initial State: Istio with Kiali installed.
Action: Set Kiali to 3 replicas.
Outcome: Kiali token login was successful.
Environment:
Rancher 2.7 non-HA, non-Airgapped setup
Scenario 4: Upgrade in Non-HA, Non-Airgapped Setup
Initial State: Istio version 102.4.0+up1.19.0 installed.
Action: Upgraded Rancher to 2.8 and Istio to 103.2.0+up1.19.0.
Outcome: Kiali token login was successful.
