### ISSUE TITLE
 When are you going to update the rancher-stable/rancher helm chart with the latest version of rancher 2.7.x other than 2.7.6 ?

### ISSUE THREAD

**Issue by konvergence** [rancher/rancher#43313]
Since release  2.7.6  the helm chart rancher-stable/rancher is not updated.
There are 2.7.7, 2.7.8 and now 2.7.9 into the rancher-latest/rancher.

According to the doc :  https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade/resources/choose-a-rancher-version

We have installed rancher with the  chart rancher-stable/rancher 
But the 2.7.6 is really not very stable.

**Comment by megabreit** [comment]
Maybe this helps: https://www.suse.com/es-es/support/kb/doc/?id=000020430

**Comment by konvergence** [comment]
Hi
I see that the release 2.7.9 has been pushed on rancher-stable/rancher

Thank
