### ISSUE TITLE
Need to raise error when trying to scale more one container with same exposed port on same host

### ISSUE THREAD

**Issue by clicman** [rancher/rancher#4331]
Rancher Version:1.0GA

Given:
One host registered.

Steps to Reproduce: 
Create service with one continer with port 80 exposed on it.
Try to scale service to two containers.

Results: 
New container creation stareted but it won`t start with  Error (Scheduling failed: host needs ports 80/tcp available)

Expected:
It is possible to raise this error before real scalling starts. And prevent duplication containers with same exposed ports on same host.
Also current behaviour may lead to confusing situation in case first container will stopped before scalling, because I suppose what in this case scalling will finished fine but it will port conflicts if I try to start first one.

**Comment by deniseschannon** [comment]
Unfortunately, it is not possible to raise the error beforehand. The error state is something that Rancher produces after we've tried to allocate the container and the allocation of the container failed, so we wouldn't get the error until after it's attempted to be allocated onto a host.

**Comment by clicman** [comment]
I belive what rancher server knows about all infrastructure information to raise "no situable hosts for deployment" error. Or not?

**Comment by deniseschannon** [comment]
@clicman No, there are many reasons why a scheduling could fail (ports is just one example). After the allocation fails, we elevate the error and put the instance on the UI as error state with the error.
