### ISSUE TITLE
rancher:[FATAL] leaderelection lost for cattle-controllers 

### ISSUE THREAD

**Issue by yushuobuxiu** [rancher/rancher#43326]
**Rancher Server Setup**
- Rancher version:2.6.9 and 1.6.13
- OS:Centos7
- Docker version:20.10.x
- Installation option (Docker install/Helm Chart):docker
   - Install commands:docker run -d -e TZ="Asia/Shanghai" -v /etc/localtime:/etc/localtime:ro --privileged --restart=unless-stopped    -p 18080:80 -p 443:443    rancher/rancher:v2.6.9 
   - 
**Describe the bug**

**Longging**
[rancherv2.6.9-cn20231030.log](https://github.com/rancher/rancher/files/13201350/rancherv2.6.9-cn20231030.log)

**Comment by yushuobuxiu** [comment]
Can someone help me.

**Comment by yushuobuxiu** [comment]
Keep restarting rancher after deploying it with docker.

**Comment by gabrielaomoraes** [comment]
@yushuobuxiu can you please use the template to provide more information about the issue?

**Comment by yushuobuxiu** [comment]
> @yushuobuxiu您能否使用该模板提供有关该问题的更多信息？

Yes, this is meg of the machine.
[logs20231030.tar.gz](https://github.com/rancher/rancher/files/13212737/logs20231030.tar.gz)

**Comment by yushuobuxiu** [comment]
>
