### ISSUE TITLE
Unable to connect to OpenDJ server

### ISSUE THREAD

**Issue by illyul** [rancher/rancher#4333]
Rancher Version:v1.0.0

Docker Version:v1.10.3

OS: Centos 7

Steps to Reproduce: 
## 4. Configure an OpenLDAP server in Rancher UI

- IP: 192.168.99.1 (my LDAP server)
- Port: 389
- Service Account Username: cn=Directory Manager
- Service Account Password: xxxxxx
- Search Base: dc=abc,dc=com

### Users

- Objectclass: inetOrgPerson
- Login Field: uid
- Name Field: cn
- Search Field: uid
- Status Field: <blank>
- Disable Status Bitmask: 0

### Groups

- Objectclass: groupOfNames
- Login Field: cn
- Search Field: cn

## 6. Test and enable authentication

- Username: uid=ill,dc=abc,dc=com
- Password: xxxxx

Results: Could not talk to ldap

Expected: Able to authenticate using username and password provided.

**Comment by deniseschannon** [comment]
@illyul Do you have any errors in the logs?

**Comment by illyul** [comment]
Thanks for your attention, @deniseschannon 
I can config it as follows:
In step 4, I use parameters: 
Service Account Username: cn=ill,dc=abc,dc=com
Service Account Password:  xxxxxxx

In step 6: 
     Username: ill
     Password: xxxxx

**Comment by deniseschannon** [comment]
Glad you were able to figure it out.
