### ISSUE TITLE
[rancher-compse] Using logs "--lines" flag show full log

### ISSUE THREAD

**Issue by jllucas** [rancher/rancher#4334]
Rancher Version:
Rancher v1.0.0
Cattle  v0.159.2
User Interface  v0.100.3
Rancher Compose v0.7.3

Docker Version:
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64

OS: 
Linux rancher 3.13.0-83-generic #127-Ubuntu SMP Fri Mar 11 00:25:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Steps to Reproduce: 
rancher-compose [OPTS] logs --lines "2"

Results: 
full log

Expected:
last 2 lines

**Comment by deniseschannon** [comment]
Reproduced with v0.7.3 on v1.0.1-rc1

**Comment by joshwget** [comment]
I'm not sure why this field is shown since it's never actually been implemented and doesn't match the corresponding flag in Docker Compose. The proper flag `tail` will be implemented once it's supported in libcompose.

For now, I'll remove this flag.

**Comment by deniseschannon** [comment]
Verified in rancher-compose v0.11.0-rc5 that `--lines` has been removed
