### ISSUE TITLE
Deactivating Account API Key displays "Deactivate Error / Not Found"

### ISSUE THREAD

**Issue by adamkdean** [rancher/rancher#4336]
Rancher Version: 1.0.0
Cattle: 0.159.2
UI: 0.100.3
Compose: 0.7.3

Docker Version: N/A
OS: N/A

Steps to Reproduce: Add Account API Key, then try and deactivate it
Results: UI Error message in top right box: "Deactivate Error / Not Found"
Expected: API Key is deactivated

**Comment by tfiduccia** [comment]
Version - v1.0.1-rc1
I verified this is still a problem in the current build.  Error in dev tools:
jquery.js:8630 POST http://<host ip>/v1/apikeys/1c52/?action=deactivate 404 (Not Found)

**Comment by will-chan** [comment]
Is this a UI issue or a backend problem?

**Comment by vincent99** [comment]
UI; fixed in next release by way of a much bigger set of changes to separate resources owned by user vs environment into two separate browser "stores".

**Comment by tfiduccia** [comment]
Version - master 4/28
