### ISSUE TITLE
Add Docker version v24.0.3 to v24.0.7

### ISSUE THREAD

**Issue by rayandas** [rancher/rancher#43362]
The following docker versions are to be added:
```
v24.0.3
v24.0.4
v24.0.5
v24.0.6
v24.0.7
```

The same approach as https://github.com/rancher/rancher/issues/40731 is to be followed for implementation and testing.

> Note: The s390x change that went into 23.0.x is also present in 20.10.24.

**Comment by vivek-shilimkar** [comment]
| OS to test | Version | Docker Version | Custom Cluster | Node Driver | Notes/Prerequisites |
|---|---|---|---|---|---|
CentOS | 7.9 | 24.0.3 to 24.0.7| PASS | PASS | 
Oracle Linux | 9.2 | 24.0.3 to 24.0.7| | PASS | Firewalld disabled, nm-cloud-setup.service and nm-cloud-setup.timer stopped and disabled. 
||9.1| 24.0.3 to 24.0.7|| PASS | Firewalld disabled, nm-cloud-setup.service and nm-cloud-setup.timer disabled. 
||9.0| 24.0.3 to 24.0.7|| PASS | Firewalld disabled, nm-cloud-setup.service and nm-cloud-setup.timer disabled. 
||8.8| 24.0.3 to 24.0.7|| PASS | Firewalld disabled, nm-cloud-setup.service and nm-cloud-setup.timer disabled. 
||8.7| 24.0.3 to 24.0.7|| PASS | Firewalld disabled, nm-cloud-setup.service and nm-cloud-setup.timer disabled. 
RHEL | 9.2 |24.0.3 to 24.0.7| PASS | PASS |
|| 9.1 |24.0.3 to 24.0.7| PASS | PASS |
|| 9.0 |24.0.3 to 24.0.7| PASS | PASS |
|| 8.8 |24.0.3 to 24.0.7| PASS | PASS |
|| 8.7 |24.0.3 to 24.0.7| PASS | PASS |
|| 7.9 |24.0.3 to 24.0.7| PASS | PASS |
Rocky | 9.2 |24.0.3 to 24.0.7| PASS | PASS |
|| 9.1 |24.0.3 to 24.0.7| PASS | PASS |
|| 9.0 |24.0.3 to 24.0.7| PASS | PASS |
|| 8.8 |24.0.3 to 24.0.7| PASS | PASS |
|| 8.7 |24.0.3 to 24.0.7| PASS | PASS |
Ubuntu | 22.04 |24.0.3 to 24.0.7| PASS | PASS |

**Comment by rishabhmsra** [comment]
Docker testing is completed and the status is updated above, hence closing the issue.

**Comment by snasovich** [comment]
This was released out of band on 1/3/2024 and it not tied to any Rancher milestone so clearing milestone here.
