### ISSUE TITLE
[RFE] Fix issues using rancher-pushprox to hit authenticated kubernetes endpoints

### ISSUE THREAD

**Issue by markhillgit** [rancher/rancher#43387]
This issue is for landing community-contributed PR https://github.com/rancher/charts/pull/2851

The PR also fixes https://github.com/rancher/rancher/issues/43414

### Is your feature request related to a problem? Please describe.
Users cannot use authenticated endpoints directly without modifying the servicemonitors created by this chart if using the upstream kube-prometheus-stack chart.

Additionally, users cannot use imagePullSecrets for private repositories.

### Describe the solution you'd like
Add the ability to use authentication on the clients to the kubernetes components.

**Comment by pankajsqe** [comment]
Rancher : v2.8.2-rc2
Restest Pass

**Test Plan**
Installed rancher  v2.8.2-rc2
Installed monitoring latest chart successfully .
Installed alerts latest chart successfully.
verified all the pods and deployment are running.
Verify all monitoring component are working as expected.
Setup alert using telegram and able to receive alerts.
Deletion of monitoring and alerts chart successfully.
