### ISSUE TITLE
[RFE] Update logging-operator to version 4.2+

### ISSUE THREAD

**Issue by lopf** [rancher/rancher#43383]
In RKE2 clusters, Docker (and therefore JSON logging) is replaced with containerd. The default Fluentbit configuration created by the Logging Operator worked well with Docker but doesn't produce the same output with containerd.

The required feature to generate the necessary configuration was merged in https://github.com/kube-logging/logging-operator/pull/1329 and made available in the Operator release version 4.2.0.

Rancher is currently shipping with version 3.17.10 which was released in November 2022. This makes it difficult if not impossible to apply a best-practice configuration for RKE2/containerd.

Additional resources:
- https://github.com/microsoft/fluentbit-containerd-cri-o-json-log
- https://github.com/kube-logging/logging-operator/issues/1315
- https://github.com/kube-logging/logging-operator/issues/1007

**Comment by vincebrannon** [comment]
Rancher release 2.8.3 should be shipping with logging operator chart version 4.4

**Comment by pankajsqe** [comment]
Retest passed :  Update logging-operator to version 4.2+. 

Test scenarios:
* verified on local cluster where logging operator version is 4.4.0
* verified on downstream cluster where logging operator version is 4.4.0.
* verified logging operator version is 4.4.0 using rancher upgrade from rancher 2.8.5  to 2.9.0-alpha7
* verified Update logging-operator by upgrading, downgrading and uninstalling logging chart  

Rancher version: 2.9.0-alpha7 
RKE2 : v1.29.4+rke2r1
Logging : rancher-logging:104.0.0-rc1+up4.4.0



![Image](https://github.com/rancher/rancher/assets/149133120/4715842f-1fc1-42dc-b50f-ef478aa7cfe0)
![Image](https://github.com/rancher/rancher/assets/149133120/39f3f719-62fe-4696-bfe4-952a4421a65c)
