### ISSUE TITLE
[BUG] rancher-monitoring-crd Helm lint fails on rancher-monitoring-crd chart

### ISSUE THREAD

**Issue by jromelague** [rancher/rancher#43380]
### Describe the bug
When performing an helm lint on the rancher-monitoring-crd chart, the lint fails because the chart type field is not supported in apiVersion 1

### To Reproduce
``` console
$ helm version
version.BuildInfo{Version:"v3.12.2", GitCommit:"1e210a2c8cc5117d1055bfaa5d40f51bbc2e345e", GitTreeState:"clean", GoVersion:"go1.20.5"}

$ helm repo add rancher-chart https://charts.rancher.io
$ helm pull --version 102.0.2+up40.1.2 --untar rancher-chart/rancher-monitoring-crd
$ helm lint ./rancher-monitoring-crd
```

### Actual Result
``` console
==> Linting ./rancher-monitoring-crd
[INFO] Chart.yaml: icon is recommended
[ERROR] Chart.yaml: chart type is not valid in apiVersion 'v1'. It is valid in apiVersion 'v2'

Error: 1 chart(s) linted, 1 chart(s) failed
```

### Expected Result
``` console
$ helm lint ./rancher-monitoring-crd
==> Linting ./rancher-monitoring-crd
[INFO] Chart.yaml: icon is recommended

1 chart(s) linted, 0 chart(s) failed
```

**Comment by pankajsqe** [comment]
It has been tested on dev-2.9 branch of rancher-monitoring/104.0.2+up45.31.1 and there are no error while  Helm lint command.


helm lint ./104.0.1+up45.31.1
==> Linting ./104.0.1+up45.31.1
[INFO] Chart.yaml: icon is recommended

1 chart(s) linted, 0 chart(s) failed

![Image](https://github.com/rancher/rancher/assets/149133120/f5495d19-9e53-4386-b4c4-aef5687cbc6a)
