### ISSUE TITLE
rancher-dns cache data-race

### ISSUE THREAD

**Issue by ronag** [rancher/rancher#4339]
I believe there might be a data-race in the rancher-dns cache code. I'm no go programmer but it looks to me like `addClientCache `(https://github.com/rancher/rancher-dns/blob/3f2565d80d435d95ade0947b51ceac9903eb36d3/cache.go#L8) can be called concurrently through `clientSpecificCacheHit` but it updates an unsafe hash map (`clientSpecificCaches`).

```
fatal error: concurrent map writes

goroutine 331 [running]:
runtime.throw(0x9d7600, 0x15)
    /usr/local/go/src/runtime/panic.go:530 +0x90 fp=0xc8204eb820 sp=0xc8204eb808
runtime.mapassign1(0x84c840, 0xc8203a8d50, 0xc8204eb928, 0xc8204eb910)
    /usr/local/go/src/runtime/hashmap.go:445 +0xb1 fp=0xc8204eb8c8 sp=0xc8204eb820
main.clientSpecificCacheHit(0xc8203c3c20, 0xc, 0xc82048e5a0, 0x1)
    /go/src/github.com/rancher/rancher-dns/cache.go:21 +0x230 fp=0xc8204eb968 sp=0xc8204eb8c8
main.route(0x7fa99c7b5220, 0xc8203bce70, 0xc82048e5a0)
    /go/src/github.com/rancher/rancher-dns/main.go:211 +0x1199 fp=0xc8204ebce0 sp=0xc8204eb968
github.com/rancher/rancher-dns/vendor/github.com/miekg/dns.HandlerFunc.ServeDNS(0xa4cba0, 0x7fa99c7b5220, 0xc8203bce70, 0xc82048e5a0)
    /go/src/github.com/rancher/rancher-dns/vendor/github.com/miekg/dns/server.go:82 +0x3a fp=0xc8204ebd00 sp=0xc8204ebce0
github.com/rancher/rancher-dns/vendor/github.com/miekg/dns.(*ServeMux).ServeDNS(0xc8200148a0, 0x7fa99c7b5220, 0xc8203bce70, 0xc82048e5a0)
    /go/src/github.com/rancher/rancher-dns/vendor/github.com/miekg/dns/server.go:186 +0xbb fp=0xc8204ebd98 sp=0xc8204ebd00
github.com/rancher/rancher-dns/vendor/github.com/miekg/dns.(*Server).serve(0xc820065ad0, 0x7fa99f9d8bd8, 0xc8203a8e40, 0x7fa99f9d8b88, 0xc8200148a0, 0xc8200e7800, 0x2f, 0x200, 0xc82002a438, 0xc8203c3b60, ...)
    /go/src/github.com/rancher/rancher-dns/vendor/github.com/miekg/dns/server.go:535 +0x7c8 fp=0xc8204ebf48 sp=0xc8204ebd98
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8204ebf50 sp=0xc8204ebf48
created by github.com/rancher/rancher-dns/vendor/github.com/miekg/dns.(*Server).serveUDP
    /go/src/github.com/rancher/rancher-dns/vendor/github.com/miekg/dns/server.go:489 +0x3d5

goroutine 1 [IO wait]:
net.runtime_pollWait(0x7fa99f9d8a60, 0x72, 0x0)
    /usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc82012ac30, 0x72, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82012ac30, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc82012abd0, 0x0, 0x7fa99f9d8bb0, 0xc820136de0)
    /usr/local/go/src/net/fd_unix.go:426 +0x27c
net.(*TCPListener).AcceptTCP(0xc82002a428, 0x8db440, 0x0, 0x0)
    /usr/local/go/src/net/tcpsock_posix.go:254 +0x4d
github.com/rancher/rancher-dns/vendor/github.com/miekg/dns.(*Server).serveTCP(0xc820065ba0, 0xc82002a428, 0x0, 0x0)
    /go/src/github.com/rancher/rancher-dns/vendor/github.com/miekg/dns/server.go:435 +0x1c2
github.com/rancher/rancher-dns/vendor/github.com/miekg/dns.(*Server).ListenAndServe(0xc820065ba0, 0x0, 0x0)
    /go/src/github.com/rancher/rancher-dns/vendor/github.com/miekg/dns/server.go:309 +0x3ec
main.main()
    /go/src/github.com/rancher/rancher-dns/main.go:76 +0x8c0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
    /usr/local/go/src/runtime/sigqueue.go:116 +0x132
os/signal.loop()
    /usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
    /usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 6 [select, locked to thread]:
runtime.gopark(0xa4d2f8, 0xc820028728, 0x98d3f0, 0x6, 0x18, 0x2)
    /usr/local/go/src/runtime/proc.go:262 +0x163
runtime.selectgoImpl(0xc820028728, 0x0, 0x18)
    /usr/local/go/src/runtime/select.go:392 +0xa67
runtime.selectgo(0xc820028728)
    /usr/local/go/src/runtime/select.go:215 +0x12
runtime.ensureSigM.func1()
    /usr/local/go/src/runtime/signal1_unix.go:279 +0x358
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 7 [chan receive]:
main.watchSignals.func1(0xc8200624e0)
    /go/src/github.com/rancher/rancher-dns/main.go:121 +0x64
created by main.watchSignals
    /go/src/github.com/rancher/rancher-dns/main.go:125 +0x13f

goroutine 8 [chan receive]:
main.watchSignals.func2()
    /go/src/github.com/rancher/rancher-dns/main.go:128 +0x50
created by main.watchSignals
    /go/src/github.com/rancher/rancher-dns/main.go:134 +0x157

goroutine 9 [IO wait]:
net.runtime_pollWait(0x7fa99f9d88e0, 0x72, 0x0)
    /usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc820166060, 0x72, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820166060, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc820166000, 0x0, 0x7fa99f9d8bb0, 0xc8202d1800)
    /usr/local/go/src/net/fd_unix.go:426 +0x27c
net.(*TCPListener).AcceptTCP(0xc82016a000, 0x463340, 0x0, 0x0)
    /usr/local/go/src/net/tcpsock_posix.go:254 +0x4d
net/http.tcpKeepAliveListener.Accept(0xc82016a000, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/http/server.go:2427 +0x41
net/http.(*Server).Serve(0xc820160000, 0x7fa99d18e028, 0xc82016a000, 0x0, 0x0)
    /usr/local/go/src/net/http/server.go:2117 +0x129
net/http.(*Server).ListenAndServe(0xc820160000, 0x0, 0x0)
    /usr/local/go/src/net/http/server.go:2098 +0x136
net/http.ListenAndServe(0x9907a0, 0xe, 0x7fa99f9d7a98, 0xc820012820, 0x0, 0x0)
    /usr/local/go/src/net/http/server.go:2195 +0x98
created by main.watchHttp
    /go/src/github.com/rancher/rancher-dns/main.go:142 +0x301

goroutine 10 [IO wait]:
net.runtime_pollWait(0x7fa99f9d89a0, 0x72, 0x70)
    /usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc82012aca0, 0x72, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82012aca0, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).readMsg(0xc82012ac40, 0xc8200e7a00, 0x200, 0x200, 0xc8203a8e70, 0x28, 0x28, 0xffffffffffffffff, 0x0, 0x0, ...)
    /usr/local/go/src/net/fd_unix.go:304 +0x33d
net.(*UDPConn).ReadMsgUDP(0xc82002a438, 0xc8200e7a00, 0x200, 0x200, 0xc8203a8e70, 0x28, 0x28, 0x200, 0x84eac0, 0x1, ...)
    /usr/local/go/src/net/udpsock_posix.go:96 +0x171
github.com/rancher/rancher-dns/vendor/github.com/miekg/dns.ReadFromSessionUDP(0xc82002a438, 0xc8200e7a00, 0x200, 0x200, 0x200, 0x200, 0x0, 0x0)
    /go/src/github.com/rancher/rancher-dns/vendor/github.com/miekg/dns/udp.go:47 +0xc1
github.com/rancher/rancher-dns/vendor/github.com/miekg/dns.(*Server).readUDP(0xc820065ad0, 0xc82002a438, 0x77359400, 0x0, 0x0, 0x0, 0xc82003bd90, 0x0, 0x0)
    /go/src/github.com/rancher/rancher-dns/vendor/github.com/miekg/dns/server.go:605 +0x190
github.com/rancher/rancher-dns/vendor/github.com/miekg/dns.(*defaultReader).ReadUDP(0xc82002a460, 0xc82002a438, 0x77359400, 0x0, 0x0, 0x0, 0xc8200148a0, 0x0, 0x0)
    /go/src/github.com/rancher/rancher-dns/vendor/github.com/miekg/dns/server.go:230 +0x5f
github.com/rancher/rancher-dns/vendor/github.com/miekg/dns.(*Server).serveUDP(0xc820065ad0, 0xc82002a438, 0x0, 0x0)
    /go/src/github.com/rancher/rancher-dns/vendor/github.com/miekg/dns/server.go:478 +0x1fe
github.com/rancher/rancher-dns/vendor/github.com/miekg/dns.(*Server).ListenAndServe(0xc820065ad0, 0x0, 0x0)
    /go/src/github.com/rancher/rancher-dns/vendor/github.com/miekg/dns/server.go:327 +0x6fc
main.main.func1(0xc820065ad0)
    /go/src/github.com/rancher/rancher-dns/main.go:73 +0x25
created by main.main
    /go/src/github.com/rancher/rancher-dns/main.go:74 +0x751

goroutine 330 [runnable]:
github.com/rancher/rancher-dns/vendor/github.com/Sirupsen/logrus.WithFields(0xc820473dd0, 0xc820473dd0)
    /go/src/github.com/rancher/rancher-dns/vendor/github.com/Sirupsen/logrus/exported.go:66
main.route(0x7fa99c7b5220, 0xc82021f650, 0xc8203c8000)
    /go/src/github.com/rancher/rancher-dns/main.go:227 +0x1cc1
github.com/rancher/rancher-dns/vendor/github.com/miekg/dns.HandlerFunc.ServeDNS(0xa4cba0, 0x7fa99c7b5220, 0xc82021f650, 0xc8203c8000)
    /go/src/github.com/rancher/rancher-dns/vendor/github.com/miekg/dns/server.go:82 +0x3a
github.com/rancher/rancher-dns/vendor/github.com/miekg/dns.(*ServeMux).ServeDNS(0xc8200148a0, 0x7fa99c7b5220, 0xc82021f650, 0xc8203c8000)
    /go/src/github.com/rancher/rancher-dns/vendor/github.com/miekg/dns/server.go:186 +0xbb
github.com/rancher/rancher-dns/vendor/github.com/miekg/dns.(*Server).serve(0xc820065ad0, 0x7fa99f9d8bd8, 0xc8203a8de0, 0x7fa99f9d8b88, 0xc8200148a0, 0xc820461c00, 0x2f, 0x200, 0xc82002a438, 0xc8203c3b40, ...)
    /go/src/github.com/rancher/rancher-dns/vendor/github.com/miekg/dns/server.go:535 +0x7c8
created by github.com/rancher/rancher-dns/vendor/github.com/miekg/dns.(*Server).serveUDP
    /go/src/github.com/rancher/rancher-dns/vendor/github.com/miekg/dns/server.go:489 +0x3d5
```

**Comment by joshwget** [comment]
Should be fixed with rancher/rancher-dns#31

**Comment by joshwget** [comment]
Should be fixed with rancher/rancher-dns#31

**Comment by deniseschannon** [comment]
@ronag Please re-open if you face this issue in our next latest release (v.1.1.0-dev1) as we have updated the code. Feel free to look at the PR.

**Comment by prasannacs** [comment]
Hi,

I have the same issue.

fatal error: concurrent map writes

goroutine 6 [running]:
runtime.throw(0xab24f0, 0x15)
        /usr/local/go/src/runtime/panic.go:547 +0x90 fp=0xc8200cf0c8 sp=0xc8200cf0b0
runtime.mapassign1(0x8eca40, 0xc8203d4480, 0xc8200cf6a0, 0xc8200cf2f0)
        /usr/local/go/src/runtime/hashmap.go:445 +0xb1 fp=0xc8200cf170 sp=0xc8200cf0c8
github.com/rancher/rancher-catalog-service/manager.(*Catalog).walkCatalog(0xc82028f790, 0xc82017bfa0, 0x20, 0x7f78f28e2080, 0xc8205309c0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/rancher/rancher-catalog-service/manager/catalog.go:180 +0x1267 fp=0xc8200cf908 sp=0xc8200cf170
github.com/rancher/rancher-catalog-service/manager.(*Catalog).(github.com/rancher/rancher-catalog-service/manager.walkCatalog)-fm(0xc82017bfa0, 0x20, 0x7f78f28e2080, 0xc8205309c0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/rancher/rancher-catalog-service/manager/catalog.go:67 +0x74 fp=0xc8200cf958 sp=0xc8200cf908
path/filepath.walk(0xc82017bfa0, 0x20, 0x7f78f28e2080, 0xc8205309c0, 0xc8200cfe10, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:349 +0x80 fp=0xc8200cfa90 sp=0xc8200cf958
path/filepath.walk(0xc820164560, 0x18, 0x7f78f28e2080, 0xc820406750, 0xc8200cfe10, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:374 +0x4fc fp=0xc8200cfbc8 sp=0xc8200cfa90
path/filepath.walk(0xc820332470, 0x10, 0x7f78f28e2080, 0xc82034ec30, 0xc8200cfe10, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:374 +0x4fc fp=0xc8200cfd00 sp=0xc8200cfbc8
path/filepath.Walk(0xc820332470, 0x10, 0xc8200cfe10, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:396 +0xe1 fp=0xc8200cfd68 sp=0xc8200cfd00
github.com/rancher/rancher-catalog-service/manager.(*Catalog).readCatalog(0xc82028f790, 0x0, 0x0)
        /go/src/github.com/rancher/rancher-catalog-service/manager/catalog.go:67 +0x722 fp=0xc8200cff10 sp=0xc8200cfd68
github.com/rancher/rancher-catalog-service/manager.Init()
        /go/src/github.com/rancher/rancher-catalog-service/manager/catalog_manager.go:248 +0x7a fp=0xc8200cff90 sp=0xc8200cff10
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8200cff98 sp=0xc8200cff90
created by main.main
        /go/src/github.com/rancher/rancher-catalog-service/main.go:19 +0xb9

goroutine 1 [IO wait]:
net.runtime_pollWait(0x7f78f28e3150, 0x72, 0x0)
        /usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc82032b9c0, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82032b9c0, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc82032b960, 0x0, 0x7f78f28e3248, 0xc820462000)
        /usr/local/go/src/net/fd_unix.go:426 +0x27c
net.(*TCPListener).AcceptTCP(0xc82002a5b0, 0x451eb0, 0x0, 0x0)
        /usr/local/go/src/net/tcpsock_posix.go:254 +0x4d
net/http.tcpKeepAliveListener.Accept(0xc82002a5b0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:2427 +0x41
net/http.(*Server).Serve(0xc82030f080, 0x7f78f28e3210, 0xc82002a5b0, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:2117 +0x129
net/http.(*Server).ListenAndServe(0xc82030f080, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:2098 +0x136
net/http.ListenAndServe(0xc820332520, 0x5, 0x7f78f28e2178, 0xc8203322a0, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:2195 +0x98
main.main()
        /go/src/github.com/rancher/rancher-catalog-service/main.go:22 +0x215

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
        /usr/local/go/src/runtime/sigqueue.go:116 +0x132
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 8 [chan receive]:
github.com/rancher/rancher-catalog-service/manager.StartCatalogBackgroundPoll.func1(0xc8202a9f40)
        /go/src/github.com/rancher/rancher-catalog-service/manager/catalog_manager.go:260 +0x77
created by github.com/rancher/rancher-catalog-service/manager.StartCatalogBackgroundPoll
        /go/src/github.com/rancher/rancher-catalog-service/manager/catalog_manager.go:264 +0x4f

goroutine 9 [select, locked to thread]:
runtime.gopark(0xb48a00, 0xc820029f28, 0xa59ad8, 0x6, 0x18, 0x2)
        /usr/local/go/src/runtime/proc.go:262 +0x163
runtime.selectgoImpl(0xc820029f28, 0x0, 0x18)
        /usr/local/go/src/runtime/select.go:392 +0xa67
runtime.selectgo(0xc820029f28)
        /usr/local/go/src/runtime/select.go:215 +0x12
runtime.ensureSigM.func1()
        /usr/local/go/src/runtime/signal1_unix.go:279 +0x358
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 10 [chan receive]:
github.com/rancher/rancher-catalog-service/manager.WatchSignals.func1(0xc820322600)
        /go/src/github.com/rancher/rancher-catalog-service/manager/catalog_manager.go:86 +0x64
created by github.com/rancher/rancher-catalog-service/manager.WatchSignals
        /go/src/github.com/rancher/rancher-catalog-service/manager/catalog_manager.go:91 +0x13f

goroutine 12 [runnable]:
syscall.Syscall6(0x101, 0xffffffffffffff9c, 0xc82046d8c0, 0x80000, 0x0, 0x0, 0x0, 0x6, 0x80000, 0x0)
        /usr/local/go/src/syscall/asm_linux_amd64.s:44 +0x5
syscall.openat(0xffffffffffffff9c, 0xc820164c80, 0x20, 0x80000, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/syscall/zsyscall_linux_amd64.go:40 +0xd0
syscall.Open(0xc820164c80, 0x20, 0x80000, 0x0, 0xc82046c1e0, 0x0, 0x0)
        /usr/local/go/src/syscall/syscall_linux.go:51 +0x58
os.OpenFile(0xc820164c80, 0x20, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/os/file_unix.go:97 +0xaf
os.Open(0xc820164c80, 0x20, 0x0, 0x0, 0x0)
        /usr/local/go/src/os/file.go:244 +0x48
path/filepath.readDirNames(0xc820164c80, 0x20, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:402 +0x5b
path/filepath.walk(0xc820164c80, 0x20, 0x7f78f28e2080, 0xc820227c70, 0xc8200d3780, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:361 +0x1a2
path/filepath.walk(0xc82017b5c0, 0x18, 0x7f78f28e2080, 0xc820429ad0, 0xc8200d3780, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:374 +0x4fc
path/filepath.walk(0xc82018e3f0, 0x10, 0x7f78f28e2080, 0xc82034ed00, 0xc8200d3780, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:374 +0x4fc
path/filepath.Walk(0xc82018e3f0, 0x10, 0xc8200d3780, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:396 +0xe1
github.com/rancher/rancher-catalog-service/manager.(*Catalog).readCatalog(0xc82034e410, 0x0, 0x0)
        /go/src/github.com/rancher/rancher-catalog-service/manager/catalog.go:67 +0x722
github.com/rancher/rancher-catalog-service/manager.Init()
        /go/src/github.com/rancher/rancher-catalog-service/manager/catalog_manager.go:248 +0x7a
github.com/rancher/rancher-catalog-service/service.RefreshCatalog(0x7f78f28e8278, 0xc82034e000, 0xc8203ea0e0)
        /go/src/github.com/rancher/rancher-catalog-service/service/handlers.go:491 +0x4b
net/http.HandlerFunc.ServeHTTP(0xb47f88, 0x7f78f28e8278, 0xc82034e000, 0xc8203ea0e0)
        /usr/local/go/src/net/http/server.go:1618 +0x3a
github.com/rancher/rancher-catalog-service/vendor/github.com/rancher/go-rancher/api.ApiHandler.func1(0x7f78f28e8278, 0xc82034e000, 0xc8203ea0e0)
        /go/src/github.com/rancher/rancher-catalog-service/vendor/github.com/rancher/go-rancher/api/handler.go:20 +0x13c
net/http.HandlerFunc.ServeHTTP(0xc8202c9d40, 0x7f78f28e8278, 0xc82034e000, 0xc8203ea0e0)
        /usr/local/go/src/net/http/server.go:1618 +0x3a
github.com/rancher/rancher-catalog-service/vendor/github.com/gorilla/context.ClearHandler.func1(0x7f78f28e8278, 0xc82034e000, 0xc8203ea0e0)
        /go/src/github.com/rancher/rancher-catalog-service/vendor/github.com/gorilla/context/context.go:141 +0x85
net/http.HandlerFunc.ServeHTTP(0xc8202c9d60, 0x7f78f28e8278, 0xc82034e000, 0xc8203ea0e0)
        /usr/local/go/src/net/http/server.go:1618 +0x3a
github.com/rancher/rancher-catalog-service/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc8201c9220, 0x7f78f28e8278, 0xc82034e000, 0xc8203ea0e0)
        /go/src/github.com/rancher/rancher-catalog-service/vendor/github.com/gorilla/mux/mux.go:98 +0x29e
github.com/rancher/rancher-catalog-service/service.(*MuxWrapper).ServeHTTP(0xc8203322a0, 0x7f78f28e8278, 0xc82034e000, 0xc8203ea0e0)
        /go/src/github.com/rancher/rancher-catalog-service/service/routes.go:21 +0x43
net/http.serverHandler.ServeHTTP(0xc82030f080, 0x7f78f28e8278, 0xc82034e000, 0xc8203ea0e0)
        /usr/local/go/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc8203fe000)
        /usr/local/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2137 +0x44e
