### ISSUE TITLE
[RFE] Bump kubeVersion to 1.28.0-0 (can't install on Docker Desktop)

### ISSUE THREAD

**Issue by aabmets** [rancher/rancher#43390]
### Is your feature request related to a problem? Please describe.
Kubernetes has pushed out many patch releases for version 1.27, but since Rancher helm Chart.yaml files
contain the line `kubeVersion: < 1.27.0-0`, it is not possible to install Rancher on any of those patched
Kubernetes versions. This is painfully apparent when trying to install Rancher on Docker Desktop 
Kubernetes subsystem. It is not possible to choose which version of Kubernetes subsystem is installed by
Docker Desktop and they upgraded their version to 1.27.2, which means that Rancher refuses to install
on all recent Docker Desktop versions.

### Describe the solution you'd like
Change the following line: `kubeVersion: < 1.27.0-0` to `kubeVersion: < 1.28.0-0` in Chart.yaml

### Describe alternatives you've considered
There is a workaround to this issue until the version is officially bumped. 
The workaround involves downloading the helm chart to your drive, extracting the contents of the archive,
editing the version number manually in the Chart.yaml file to `1.28.0-0` and then installing Rancher
from the local chart.
```
helm repo add rancher-stable https://releases.rancher.com/server-charts/stable
helm repo update
helm fetch rancher-stable/rancher

* unzip archive and edit version in Chart.yaml *

helm upgrade --install rancher ./rancher
```

**Comment by snasovich** [comment]
Rancher now supports v1.27 starting with version v2.8.0 per https://github.com/rancher/rancher/issues/41840 and there is already work on adding support for v1.28 per https://github.com/rancher/rancher/issues/43109
Please note that until Rancher officially supports given K8s version it's not certified for usage with newer versions and functionality is likely broken on these unsupported versions. Thus, `kubeVersion` constraint serves important purpose and will not be removed.
