### ISSUE TITLE
After adding stack to system page, it takes me back to system page

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4340]
Version - v1.0.1-rc1

Steps to Reproduce:
1.  Setup kubernetes environment
2.  Add a host and wait for setup to finish
3.  Go to System
4.  Click on Add Stack and create 

Results: Takes me back to Kubernetes Services page

Expected: Should leave me in System page

**Comment by westlywright** [comment]
@tfiduccia I was testing this with your scenario, after I add my stack the page is transitioned to the newly created stack which seems to be the correct behavior. Can you verify?

**Comment by tfiduccia** [comment]
Version - v1.1.0-rc3
Verified fixed
