### ISSUE TITLE
[RFE] Add ImagePullSecrets to rancher-pushprox chart

### ISSUE THREAD

**Issue by VltraHeaven** [rancher/rancher#43414]
### Is your feature request related to a problem? Please describe.
Users are unable to authenticate to private registries to pull images.

### Describe the solution you'd like
Add `ImagePullSecrets` to all deployment.spec and daemonset.spec templates in the rancher-pushprox chart - https://github.com/rancher/charts/tree/dev-v2.6/charts/rancher-pushprox/0.1.501. The requested changes would allow the deployment of this chart in air-gapped environments where unauthenticated image pulls aren't an option. 

### Additional context
pushprox client template - https://github.com/rancher/charts/blob/dev-v2.6/charts/rancher-pushprox/0.1.501/templates/pushprox-clients.yaml

pushprox proxy template - https://github.com/rancher/charts/blob/dev-v2.6/charts/rancher-pushprox/0.1.501/templates/pushprox-proxy.yaml

 SURE-7730

**Comment by pankajsqe** [comment]
Add ImagePullSecrets to rancher-pushprox chart verified.

Rancher : v2.8.3-rc4
Cluster : v1.27.12 +rke2r1 
Monitoring : rancher-monitoring:103.0.4+up45.31.1

**TestSteps**  

Create two secrets one is valid one and another is invalid one.

- Created air gap setup with rancher v2.8.3-rc4 on rke2 cluster.
- Installed monitoring charts from marketplace.
- Once chart is installed go to workloads-> Daemonset and Deployment
- Edit config for all the pushprox daemonset and deployment 
- While edit config add the invalid secret to imagepullsecret option and change pull policy to always. 
- Every pod from pushprox daemonset and deployment should throw error. Later switch the invalid secret with valid one and observe all the pod are again active and running.
