### ISSUE TITLE
Wordpress Service loses it's pods/containers overnight

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4341]
Version - v1.0.1-rc1

Steps to Reproduce: 
1.  Setup kubernetes environment and add a few hosts
2.  Once setup is complete select the Wordpress catalog and create
3.  Ensure pods & containers are created and running under the wpfrontend (check the lb to see wordpress actually runs and is fully setup)
4.  Leave and check on it next day

Results: For some reason my pods & containers are now missing.  There is no way to restart the service so I can't get them back.
![image](https://cloud.githubusercontent.com/assets/11514927/14393172/432b4e48-fd7a-11e5-8315-cc274cbf8ca8.png)

Expected:  Pods and containers should still be there and running.   I've actually seen this before and am not sure why everything is getting deleted.  It would also be nice to be able to rerun to get them back.

**Comment by soumyalj** [comment]
Tested with v1.1.0-dev5-rc2. Wordpress catalog was added and left overnight. The containers remained running next day.
