### ISSUE TITLE
In Service info popup, port link should open in new tab

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4343]
Version - v1.0.1-rc1 

Steps to Reproduce: 
1.  Create a service with the port set
2.  Wait for it to finish
3.  Click on the i for that service
4.  Click on the Port link

Results: Closes rancher and open link in same tab

Expected: Should open in new tab

**Comment by lvuch** [comment]
resolve in https://github.com/rancher/ui/pull/590

**Comment by tfiduccia** [comment]
Version - v1.0.1-rc5
