### ISSUE TITLE
[rancher-logging] references a nonexistant selinux type on RKE2.

### ISSUE THREAD

**Issue by Laikulo** [rancher/rancher#43432]
## Synopsis
On Cent8 with rke2 installed via RPM (with containers-selinux and rke2-selinux present), when `global.seLinux.enabled` is true, the chart produces a deployment that attempts to use a nonexistant seLinux type.

## Environment
CentOS 8 with up-to-date packages
rke2 version v1.21.5+rke2r2 (9e4acdc6018ae74c36523c99af25ab861f3884da) (go version go1.16.6b)
Rancher v2.6.2
rancher-logging 100.0.0+up3.12.0  

## Expected behavior
The fluentbit and journald-aggregator pods are launched with an selinux context that allows them to read logs.

## Observed behavior
fluentbit and journald-aggregator pods fail to launch with the following message:

```
Error: failed to create containerd task: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: failed to set /proc/self/attr/keycreate on procfs: write /proc/self/attr/keycreate: invalid argument: unknown
```

## Workaround
Create an seLinux module aliasing the nonexistant type, and adding some additional rights:

```
module rke2_logging_bodge 1.0;

require {
	type container_logreader_t;

	type container_log_t;
	type syslogd_var_run_t;
	class lnk_file { read getattr };
	class dir { read };
}

typealias container_logreader_t alias rke_logreader_t;

allow container_logreader_t container_log_t:lnk_file { read getattr };
allow container_logreader_t syslogd_var_run_t:dir { read };
```

## Notes:
The nonexistant type is referenced here:
https://github.com/rancher/charts/blob/7bd8cb6123ec5ce9c4aec7f14917de6b3dd74370/charts/rancher-logging/rancher-logging/100.0.0%2Bup3.12.0/templates/loggings/rke2/daemonset.yaml#L26

**Comment by Laikulo** [comment]
Bump to prevent culling

**Comment by marthydavid** [comment]
.
