### ISSUE TITLE
[rancher-monitoring] CPU and memory usage doubled in Rancher/Workload (pods) and Rancher/Workload dashboards

### ISSUE THREAD

**Issue by konih** [rancher/rancher#43468]
All versions up to `100.0.2` of the rancher monitoring chart seem to be affected.

![image-2023-02-15-10-42-27-613](https://user-images.githubusercontent.com/6974853/220322062-0e3078dc-e947-44a9-9da1-7a3d938ffcf8.png)

The solution is to include a filter for ```container!="POD", container!=""``` as else the parent cgroups memory and cpu usage will be added to the usage of each individual container which results in a doubling of metrics.

**Comment by danijel-orsolic** [comment]
I don't see this fix actually merged into any of the releases, and it still happens in rancher-monitoring:103.0.3+up45.31.1. Am I missing something?

**Comment by MKlimuszka** [comment]
Duplicate of https://github.com/rancher/rancher/issues/44726
