### ISSUE TITLE
creating catalog before setting up host giving error in kubernetes

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4346]
Version - v1.0.1-rc1

Steps to Reproduce: 
1.  Create a kubernetes environment
2.  Before your host is setup, go to catalog and try to add

Results: Error
![image](https://cloud.githubusercontent.com/assets/11514927/14394622/fe47ef18-fd81-11e5-85ca-4e40ae0a6b29.png)

Expected: In cattle & swarm environment, catalog setups up and waits for host.

**Comment by vincent99** [comment]
There is nowhere to send the template for creation in K8s because it gets sent directly to their API.  This is why I wanted the catalog button hidden until it was setup...

**Comment by tfiduccia** [comment]
Catalog goes back to waiting until fully setup.  So this is no longer a problem
Version - master 6/16
Verified fixed
