### ISSUE TITLE
Add vSphere csi-snapshotter to vsphere csi chart

### ISSUE THREAD

**Issue by EStork09** [rancher/rancher#43482]
In the current vsphere-csi chart there is an option to enable snapshotting in the config map, but in the vsphere csi documentation it is put into the controller deployment via [this](https://github.com/kubernetes-sigs/vsphere-csi-driver/blob/master/manifests/vanilla/deploy-csi-snapshot-components.sh). Could we get the snapshot included into the helm chart or is there a reason it is separate? 

Here are some docs:
https://github.com/kubernetes-sigs/vsphere-csi-driver/blob/master/docs/book/features/volume_snapshot.md
https://github.com/kubernetes-sigs/vsphere-csi-driver/blob/master/manifests/vanilla/deploy-csi-snapshot-components.sh

**Comment by snasovich** [comment]
This is now superseded by (admittedly newer) issue https://github.com/rancher/rancher/issues/43482
