### ISSUE TITLE
[RFE] vSphere CSI chart updates to upstream v3.0.3 / v1.27.3 (incl. K8s 1.28 support)

### ISSUE THREAD

**Issue by a-blender** [rancher/rancher#43494]
**Is your feature request related to a problem? Please describe.**

Upstream has released the following new vSphere CPI versions:

https://github.com/kubernetes-sigs/vsphere-csi-driver/releases/tag/v3.0.3
https://github.com/kubernetes-sigs/vsphere-csi-driver/releases/tag/v1.27.3
(check for others)

**Describe the solution you'd like**

Update the chart to include these new versions (possibly using new Renovate automation - not necessarily a requirement).

_Note: There will likely be new chart versions out by the time that we bump so check upstream for newly released versions, do the same with CSI._

# Checklist for items that need completed

- [ ] Update Image-mirror repo
- [ ] Update manifests in rancher/vsphere-charts
- [ ] (Non-standard checklist item) Ensure https://github.com/rancher/vsphere-charts/issues/46 is fixed so we include a fix for it as well - _this still required?_
- [ ] Verify labels function correctly https://github.com/rancher/vsphere-charts/issues/33
- [ ] Verify Slack hook notified about chart "release" in relevant channels
- [ ] Update chart in rancher/charts
- [ ] Update chart in rancher/rke2-charts (RKE2 team)
- [ ] Updated RKE2 to consume new chart (RKE2 team)

**Comment by snasovich** [comment]
Moved this back to "Review" until https://github.com/rancher/charts/pull/3395 is merged.

**Comment by Josh-Diamond** [comment]
Ticket #43494 - Test Results - ✅ 
---

Verified on Rancher `v2.9-c9be13b09329bbee60a5f6419d500198f83c44d1-head`:
- fresh install (manual) ✅ 
- automation run `TestVsphereCloudProviderCluster` ✅

Version bump as expected + fully functional
