### ISSUE TITLE
[QUESTION] How to set location for node templates

### ISSUE THREAD

**Issue by sullrich84** [rancher/rancher#43496]
How can I define the location of a node template?  I assume that there is probably a label for this:

![rancher](https://github.com/rancher/rancher/assets/665999/a4729250-6db7-4de6-93fe-9d0d8629a29f)

**Comment by Oats87** [comment]
The `Location` corresponds to the `region` parameter for your given node driver. As such, if your specific node driver does not have a `region` parameter, I would expect `N/A` in the UI like that. See: https://github.com/rancher/dashboard/blob/80762b5d06fdd521f76d95325dac0bace1c7fe6f/shell/models/management.cattle.io.nodetemplate.js#L118
