### ISSUE TITLE
[BUG] Scaling provisioned nodes is unreliable not successful in certain cases

### ISSUE THREAD

**Issue by Oats87** [rancher/rancher#43505]
**Rancher Server Setup**
- Rancher version: v2.7.9
- Installation option (Docker install/Helm Chart): N/A

**Describe the bug**
In certain cases, scaling provisioned clusters can be problematic/unreliable. For background context, the `cluster-api-provider-rancher` infrastructure provider translates the `spec` field of the corresponding InfrastructureMachine object into the arguments that are passed into the `rancher-machine` pod (machine-provision pod). This can be seen here: https://github.com/rancher/rancher/blob/7034c86f64e338464d17721262c3819d946a6070/pkg/controllers/capr/machineprovision/args.go#L284

The issue manifests itself through a very large error message like: 
```
Failed creating server [fleet-default/REDACTED] of kind (VmwarevsphereMachine) for machine REDACTED in infrastructure provider: 
 CreateError: parameters (used for guestinfo) [$VSPHERE_CFGPARAM] --vmwarevsphere-clone-from If you choose creation type clone a name of what you want to clone is required [$VSPHERE_CLONE_FROM] --vmwarevsphere-cloud-config Filepath to a cloud-config yaml file to put into the ISO user-data [$VSPHERE_CLOUD_CONFIG] --vmwarevsphere-cloudinit vSphere cloud-init filepath or url to add to guestinfo, filepath will be read and base64 encoded before adding [$VSPHERE_CLOUDINIT] --vmwarevsphere-content-library If you choose to clone from a content library template specify the name of the library [$VSPHERE_CONTENT_LIBRARY] --vmwarevsphere-cpu-count "2" vSphere CPU number for docker VM [$VSPHERE_CPU_COUNT] --vmwarevsphere-creation-type "legacy" Creation type when creating a new virtual machine. Supported values: vm, template, library, legacy [$VSPHERE_CREATION_TYPE] --vmwarevsphere-custom-attribute [--vmwarevsphere-custom-attribute option --vmwarevsphere-custom-attribute option] vSphere custom attribute, format key/value e.g. '200=my custom value' --vmwarevsphere-datacenter vSphere datacenter for virtual machine [$VSPHERE_DATACENTER] --vmwarevsphere-datastore vSphere datastore for virtual machine [$VSPHERE_DATASTORE] --vmwarevsphere-datastore-cluster vSphere datastore cluster for virtual machine [$VSPHERE_DATASTORE_CLUSTER] --vmwarevsphere-disk-size "20480" vSphere size of disk for docker VM (in MB) [$VSPHERE_DISK_SIZE] --vmwarevsphere-folder vSphere folder for the docker VM. This folder must already exist in the datacenter [$VSPHERE_FOLDER] --vmwarevsphere-hostsystem vSphere compute resource where the docker VM will be instantiated. This can be omitted if using a cluster with DRS [$VSPHERE_HOSTSYSTEM] --vmwarevsphere-memory-size "2048" vSphere size of memory for docker VM (in MB) [$VSPHERE_MEMORY_SIZE] --vmwarevsphere-network [--vmwarevsphere-network option --vmwarevsphere-network option] vSphere network where the virtual machine will be attached [$VSPHERE_NETWORK] --vmwarevsphere-os "linux" If using a non-B2D image you can specify the desired machine OS --vmwarevsphere-password vSphere password [$VSPHERE_PASSWORD] --vmwarevsphere-pool vSphere resource pool for docker VM [$VSPHERE_POOL] --vmwarevsphere-ssh-password "tcuser" If using a non-B2D image you can specify the ssh password [$VSPHERE_SSH_PASSWORD] --vmwarevsphere-ssh-port "22" If using a non-B2D image you can specify the ssh port [$VSPHERE_SSH_PORT] --vmwarevsphere-ssh-user "docker" If using a non-B2D image you can specify the ssh user [$VSPHERE_SSH_USER] --vmwarevsphere-ssh-user-group "staff" If using a non-B2D image the uploaded keys will need chown'ed, defaults to staff e.g. docker:staff [$VSPHERE_SSH_USER_GROUP] --vmwarevsphere-tag [--vmwarevsphere-tag option --vmwarevsphere-tag option] vSphere tag id e.g. urn:xxx --vmwarevsphere-username vSphere username [$VSPHERE_USERNAME] --vmwarevsphere-vapp-ipallocationpolicy vSphere vApp IP allocation policy. Supported values are: dhcp, fixed, transient and fixedAllocated [$VSPHERE_VAPP_IPALLOCATIONPOLICY] --vmwarevsphere-vapp-ipprotocol vSphere vApp IP protocol for this deployment. Supported values are: IPv4 and IPv6 [$VSPHERE_VAPP_IPPROTOCOL] --vmwarevsphere-vapp-property [--vmwarevsphere-vapp-property option --vmwarevsphere-vapp-property option] vSphere vApp properties [$VSPHERE_VAPP_PROPERTY] --vmwarevsphere-vapp-transport vSphere OVF environment transports to use for properties. Supported values are: iso and com.vmware.guestInfo [$VSPHERE_VAPP_TRANSPORT] --vmwarevsphere-vcenter vSphere IP/hostname for vCenter [$VSPHERE_VCENTER] --vmwarevsphere-vcenter-port "443" vSphere Port for vCenter [$VSPHERE_VCENTER_PORT] flag provided but not defined: -vmwarevsphere-provider-id 
```

but the specific problem is the usage of the `provider-id` flag i.e. `flag provided but not defined: -vmwarevsphere-provider-id`.

The reason this flag is attempting to be set is because of the `providerID` spec field, which is a requirement of cluster-api (https://cluster-api.sigs.k8s.io/developer/providers/machine-infrastructure). This is a field set by a controller on the CAPR side (https://github.com/rancher/rancher/blob/7034c86f64e338464d17721262c3819d946a6070/pkg/controllers/capr/machinenodelookup/controller.go#L110) with the intention to "backpopulate" the provider ID from the node to the infrastructure machine object to satisfy the cluster-api requirement.

As the controller mutates the `InfrastructureMachine` object during the provisioning of the node, it can trigger a re-run/mutation of the job definition that runs the actual `machine-provision` portion, which can orphan nodes and/or cause the error message (or one like it) to appear. Notably, this is due to the fact that nodes may be provisioned/system-agent deployed/rke2 installed and joined before the actual `machine-provision` job has deemed itself completed (especially on quick systems).

**To Reproduce**
Create a VMware vSphere cluster on infrastructure that is relatively quick
Scale the cluster (worker node pool is most likely to do this) up

**Result**
Observe machines erroring out with the error above

**Expected Result**

The machines create and register successfully.

**Screenshots**

**Additional context**
While this specific issue with encountered with vSphere, it likely will manifest on any of the infrastructure provider implementations.

I believe this may have been introduced inadvertently in an attempt to solve another race condition (https://github.com/rancher/rancher/pull/41916) 

SURE-7345

**Comment by Josh-Diamond** [comment]
Ticket #43505 - Test Results - ✅ 
---

Verified on single-node docker instance w/ Rancher `v2.8-44bbcc75c46ce9cf5dff950e04658483ff2eb107-head`:

| Scenario | Test Case | Result |
|---|---|---|
| 1. | Reproduce issue w/ vSphere => upgrade Rancher to `v2.8-head` => observe cluster recover => scale up/down worker pool | ✅ |
| 2. | On Rancher `v2.7.9`, provision a downstream AWS Node driver cluster, then scale up/down worker pool => upgrade to Rancher `v2.8-head`, and scale up/down worker pool | ✅ |
| 3. | On Rancher `v2.7.9`, provision a downstream Linode Node driver cluster, then scale up/down worker pool => upgrade to Rancher `v2.8-head`, and scale up/down worker pool | ✅ |

---

Scenario 1 -
1. Fresh install of Rancher `v2.7.9` and set environment variable `CATTLE_MACHINE_PROVISION_IMAGE=oats87/machine:v0.15.0-rancher100-vs5mdelay`
2. Create a new vSphere cluster, using K3s `v1.26.11+k3s2`, with 1 machine pool containing 1 "all-in-one" role.
3. Wait for the cluster to provision
4. Add a second machine pool, identical to the first except for name and specifying roles as "worker only"
5. Observe that machines in the second machine pool are not successfully created, and will flash an error message about unknown field `--provider-id`
6. Upgrade Rancher to `v2.8-head`
7. Verified - See cluster stabilize over time with successfully provisioned nodes
8. Once stable, scale up worker node pool
9. Verified - pool successfully scales up
10. Scale down worker node pool
11. Verified - pool successfully scales down

---

Scenario 2 -
1. Fresh instal of Rancher `v2.7.9`
2. Provision a downstream k3s AWS Node driver w/ k8s `v1.26.11+k3s2`
3. Once active, scale up worker pool
4. Verified - cluster successfully scales up
5. Scale down worker pool
6. Verified - cluster successfully scales down
7. Upgrade Rancher to `v2.8-head`
8. Once upgraded, scale up worker pool
9. Verified - post-upgrade, scale up as expected
10. Scale down worker pool
11. Verified - post-upgrade, scale down as expected

---

Scenario 3 - 
1. Fresh instal of Rancher `v2.7.9`
2. Provision a downstream k3s Linode Node driver w/ k8s `v1.26.11+k3s2`
3. Once active, scale up worker pool
4. Verified - cluster successfully scales up
5. Scale down worker pool
6. Verified - cluster successfully scales down
7. Upgrade Rancher to `v2.8-head`
8. Once upgraded, scale up worker pool
9. Verified - post-upgrade, scale up as expected
10. Scale down worker pool
11. Verified - post-upgrade, scale down as expected
