### ISSUE TITLE
[BUG] [release/v2.7] Scaling provisioned nodes is unreliable not successful in certain cases

### ISSUE THREAD

**Issue by Oats87** [rancher/rancher#43511]
Backport: https://github.com/rancher/rancher/issues/43505

**Comment by sadhugit** [comment]
The customer is hitting this issue, raised an internal issue for tracking purpose SURE-7345

**Comment by Josh-Diamond** [comment]
Ticket #43511 - Test Results - ✅ 
---

Verified on single-node docker instance w/ Rancher `v2.7-6d2dbf1153ffb81928efdbb284a1075850b5d889-head`:

| Scenario | Test Case | Result |
|---|---|---|
| 1. | Reproduce issue w/ vSphere => upgrade Rancher to `v2.7-head` => observe cluster recover => scale up/down worker pool | ✅ |
| 2. | On Rancher `v2.7.9`, provision a downstream AWS Node driver cluster, then scale up/down worker pool => upgrade to Rancher `v2.7-head`, and scale up/down worker pool | ✅ |
| 3. | On Rancher `v2.7.9`, provision a downstream Linode Node driver cluster, then scale up/down worker pool => upgrade to Rancher `v2.7-head`, and scale up/down worker pool | ✅ |

---

Scenario 1 -
1. Fresh install of Rancher `v2.7.9` and set environment variable `CATTLE_MACHINE_PROVISION_IMAGE=oats87/machine:v0.15.0-rancher100-vs5mdelay`
2. Create a new vSphere cluster, using K3s `v1.26.11+k3s2`, with 1 machine pool containing 1 "all-in-one" role.
3. Wait for the cluster to provision
4. Add a second machine pool, identical to the first except for name and specifying roles as "worker only"
5. Observe that machines in the second machine pool are not successfully created, and will flash an error message about unknown field `--provider-id`
6. Upgrade Rancher to `v2.7-head`
7. Verified - See cluster stabilize over time with successfully provisioned nodes
8. Once stable, scale up worker node pool
9. Verified - pool successfully scales up
10. Scale down worker node pool
11. Verified - pool successfully scales down

---

Scenario 2 -
1. Fresh instal of Rancher `v2.7.9`
2. Provision a downstream k3s AWS Node driver w/ k8s `v1.26.11+k3s2`
3. Once active, scale up worker pool
4. Verified - cluster successfully scales up
5. Scale down worker pool
6. Verified - cluster successfully scales down
7. Upgrade Rancher to `v2.7-head`
8. Once upgraded, scale up worker pool
9. Verified - post-upgrade, scale up as expected
10. Scale down worker pool
11. Verified - post-upgrade, scale down as expected

---

Scenario 3 - 
1. Fresh instal of Rancher `v2.7.9`
2. Provision a downstream k3s Linode Node driver w/ k8s `v1.26.11+k3s2`
3. Once active, scale up worker pool
4. Verified - cluster successfully scales up
5. Scale down worker pool
6. Verified - cluster successfully scales down
7. Upgrade Rancher to `v2.7-head`
8. Once upgraded, scale up worker pool
9. Verified - post-upgrade, scale up as expected
10. Scale down worker pool
11. Verified - post-upgrade, scale down as expected

**Comment by Josh-Diamond** [comment]
QA has decided not to automate this, due to the nature of this issue, and node scaling is already supported w/ our framework.
