### ISSUE TITLE
Rancher Gatekeeper Version

### ISSUE THREAD

**Issue by lavanya-6** [rancher/rancher#43529]
Ratify requires 3.10 version of Gatekeeper, is that version supported in Rancher ? 
(Ref.Link- https://ratify.dev/docs/1.0/quickstarts/quickstart-manual/#step-1-setup-gatekeeper-with-external-data)

If yes from what version of Rancher gatekeeper that we should be upgrading to?

**Comment by skanakal** [comment]
Yes, you can get it from here https://github.com/rancher/charts/tree/dev-v2.8/charts/rancher-gatekeeper/102.0.0%2Bup3.10.0
