### ISSUE TITLE
Ha K8s onprem import problem

### ISSUE THREAD

**Issue by ncostis** [rancher/rancher#43526]
Hi i am trying to import an onprem K8s cluster that consists of 1 loadbalancer, 2 masters and 3 workers.

Its stuck on pending. I have succesfully import a single master k8s.

The cluster-management pod fails with:

kc logs cattle-cluster-agent-64f4885fb7-8zqtm -n cattle-system
INFO: Environment: CATTLE_ADDRESS=192.168.22.195 CATTLE_CA_CHECKSUM=781ed7f3a6c3ec413b7820e08a13b42cc76a535bf2d7efb814af0cad0834c9ab CATTLE_CLUSTER=true CATTLE_CLUSTER_AGENT_PORT=tcp://10.100.205.43:80 CATTLE_CLUSTER_AGENT_PORT_443_TCP=tcp://10.100.205.43:443 CATTLE_CLUSTER_AGENT_PORT_443_TCP_ADDR=10.100.205.43 CATTLE_CLUSTER_AGENT_PORT_443_TCP_PORT=443 CATTLE_CLUSTER_AGENT_PORT_443_TCP_PROTO=tcp CATTLE_CLUSTER_AGENT_PORT_80_TCP=tcp://10.100.205.43:80 CATTLE_CLUSTER_AGENT_PORT_80_TCP_ADDR=10.100.205.43 CATTLE_CLUSTER_AGENT_PORT_80_TCP_PORT=80 CATTLE_CLUSTER_AGENT_PORT_80_TCP_PROTO=tcp CATTLE_CLUSTER_AGENT_SERVICE_HOST=10.100.205.43 CATTLE_CLUSTER_AGENT_SERVICE_PORT=80 CATTLE_CLUSTER_AGENT_SERVICE_PORT_HTTP=80 CATTLE_CLUSTER_AGENT_SERVICE_PORT_HTTPS_INTERNAL=443 CATTLE_CLUSTER_REGISTRY= CATTLE_INGRESS_IP_DOMAIN=sslip.io CATTLE_INSTALL_UUID=ee180de2-59b3-44b0-9bb8-54911e27795f CATTLE_INTERNAL_ADDRESS= CATTLE_IS_RKE=false CATTLE_K8S_MANAGED=true CATTLE_NODE_NAME=cattle-cluster-agent-64f4885fb7-8zqtm CATTLE_RANCHER_WEBHOOK_MIN_VERSION= CATTLE_RANCHER_WEBHOOK_VERSION=2.0.6+up0.3.6 CATTLE_SERVER=https://192.168.41.54 CATTLE_SERVER_VERSION=v2.7.9
INFO: Using resolv.conf: search cattle-system.svc.cluster.local svc.cluster.local cluster.local nameserver 10.96.0.10 options ndots:5
ERROR: https://192.168.41.54/ping is not accessible (Failed to connect to 192.168.41.54 port 443 after 129577 ms: Couldn't connect to server)

Any ideas???

**Comment by bigbirdxixi** [comment]
i have the same problem！
i debug pod use busybox not connect sucesses，but can connect succesed on host。what can i do？

![Image](https://github.com/user-attachments/assets/c6e7e2a0-7432-467e-9834-20fa517bc2bc)

![Image](https://github.com/user-attachments/assets/f0466a14-5f5d-4400-94f5-236356789f65)
