### ISSUE TITLE
Need to bump Go to version v1.21 in KDM and Provisioning repos.

### ISSUE THREAD

**Issue by Jono-SUSE-Rancher** [rancher/rancher#43534]
We will need to bump the Go version to v1.21+ in the following repos: 

- https://github.com/rancher/kontainer-driver-metadata
- https://github.com/rancher/provisioning
- https://github.com/rancher/system-agent

SURE-7081

**Comment by snasovich** [comment]
@jiaqiluo , adding this one to your queue.

**Comment by snasovich** [comment]
@jiaqiluo , is there anything left to do here? https://github.com/rancher/kontainer-driver-metadata and https://github.com/rancher/system-agent are already on 1.21+ and https://github.com/rancher/provisioning doesn't directly use Golang but https://github.com/rancher/provisioning/pull/7 / https://github.com/rancher/provisioning/pull/8 bumped base image version accordingly.

**Comment by jiaqiluo** [comment]
@snasovich, all works are done. I am going to close it for now. 

Be free to reopen it if it is needed.
