### ISSUE TITLE
[BUG] Agent environment variables are not updated for rancher-system-agent

### ISSUE THREAD

**Issue by thatmidwesterncoder** [rancher/rancher#43546]
**Rancher Server Setup**
- Rancher version: v2.8-head
- Installation option (Docker install/Helm Chart): docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details: squid running on localhost (referred to by machine IP, only used for agents)

**Information about the Cluster**
- Kubernetes version: v1.27.7, but any works
- Cluster Type (Local/Downstream): downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): custom, running on an Ubuntu VM

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:
Admin

**Describe the bug**

After a cluster is provisioned, the proxy environment variables updated in the cluster configuration (agent environment variables) are not updated for the rancher-system-agent (`/etc/systemd/system/rancher-system-agent.env`).

The HTTPS_PROXY, NO_PROXY, etc. (the only vars that are stored by the rancher-system-agent) remain the same, even though the plan is updated.

**To Reproduce**

1. Create an RKE2 cluster, go into the "Agent Environment Vars" section
2. Set HTTP_PROXY/HTTPS_PROXY/NO_PROXY (any of them will work)
3. Provision the cluster, check `/etc/systemd/system/rancher-system-agent.env` and see that the proxy related env vars are present
4. Update the proxy env vars in Cluster Management, wait for the plan to be applied to nodes

**Result**
`/etc/systemd/system/rancher-system-agent.env` is the same as it was before, even though the `cattle-cluster-agent` pod has been updated with the new variables.

**Expected Result**

Both the cluster-agent **and** the system-agent have the new proxy settings.

**Screenshots**

**Additional context**

It looks like the system-agent-install.sh script only gets ran when initially provisioned, it doesn't get updated otherwise.

Another thing to note is that the new proxy settings do get applied to the rke2-server itself via the run.sh scripts here: https://github.com/rancher/system-agent-installer-rke2/blob/708ad277b89bd7e68fcd0bd959c7df3ffc804b74/package/run.sh#L22

SURE-7157

**Comment by billhong-just** [comment]
https://github.com/rancher/rancher/issues/39603

**Comment by Oats87** [comment]
@thatmidwesterncoder the system-agent installer gets run by way of the `system-upgrade-controller` + `fleet`. See: https://github.com/rancher/rancher/blob/4ffeab1c22530a1a62648a5ed0d49ec43436dce3/pkg/controllers/capr/managesystemagent/managesystemagent.go#L162 

I would investigate to see whether the SUC plan is running successfully or not. It is expected that it takes a little bit after updating the variables for the plan to run, but given the controller is watching the v1 prov cluster object I would expect that it updates the plan pretty quickly (then it's up to fleet to actually apply the plan)

**Comment by Oats87** [comment]
@thatmidwesterncoder if possible, we should try to fix this in `2.7-head` and then forwardport it to `2.8-head`.
