### ISSUE TITLE
Editing ReplicaController to add a new container to the pod does not take effect.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#4355]
Rancher Version:v1.0.0-rc1

Steps to reproduce the problem:
Create a kubernetese environment with few hosts.
Created a Replication Control for a pod with  2 containers.
pod gets created with 2 containers.
Edit Replication Controller and add another container to the pod.

The newly added container (ubuntu) is not being deployed. But it gets saved in the Replica Controller object.

<img width="1471" alt="screen shot 2016-04-08 at 5 43 48 pm" src="https://cloud.githubusercontent.com/assets/4266958/14400718/7a22d20e-fdb1-11e5-9921-40ad44220fe7.png">

**Comment by alena1108** [comment]
@sangeethah doesn't look like its supported by k8s:

http://kubernetes.io/docs/api-reference/v1/definitions/#_v1_podspec

List of containers belonging to the pod. Containers cannot currently be added or removed. There must be at least one container in a Pod. Cannot be updated. More info: http://releases.k8s.io/release-1.2/docs/user-guide/containers.md

**Comment by sangeethah** [comment]
@alena1108 , if this is not supported , we should not expect the Replication Controller to show the containers that failed to be added. 
The newly added container (ubuntu) is not being deployed. But it gets saved in the Replica Controller object and displayed in the UI.

**Comment by alena1108** [comment]
Closing as we no longer support Rancher UI for k8s. All the commands are executed via k8s dashboard and go directly to k8s api server.
