### ISSUE TITLE
[flaky-test] the stage `provisioning-operations-test-rke2` times out, hitting the 1h limit

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#43560]
**Flaky Test**
 
This happens on the `provisioning-operations-tests-rke2` stage, which does not seem to be caused by a particular test case but because it is stuck on initialing/preparing the testing environment.

**Release Branch**

source branch of PR: `release/v2.8`

**Drone Build (if applicable)**

pipeline stage URL:

- https://drone-pr.rancher.io/rancher/rancher/34518/4/2
- https://drone-pr.rancher.io/rancher/rancher/34515/4/2
- https://drone-pr.rancher.io/rancher/rancher/34504/4/2
- https://drone-pr.rancher.io/rancher/rancher/34502/4/2
- https://drone-pr.rancher.io/rancher/rancher/34501/4/2
- https://drone-pr.rancher.io/rancher/rancher/34498/4/2
- https://drone-pr.rancher.io/rancher/rancher/34496/4/2
- https://drone-pr.rancher.io/rancher/rancher/34493/4/2
- https://drone-pr.rancher.io/rancher/rancher/34491/4/2
- https://drone-pr.rancher.io/rancher/rancher/34489/4/2

**Comment by macedogm** [comment]
FYI Drone has a default 60 minutes timeout configuration per pipeline, that's why the pipeline is being killed. Sharing, but unsure if the timeout is being triggered because the tests are getting longer and longer or if it's some flaky test.

**Comment by cbron** [comment]
May be related, we have been hitting a ton of errors in `provisioning-operations-test-k3s`. It's not the timeout error, but it's failing at a rate around 90%. See: https://github.com/rancher/rancher/issues/43367
I had another 5-10 failures I didn't post in there, they were all the same.

**Comment by Oats87** [comment]
@jiaqiluo can we close this issue based on the new merge of the split?

**Comment by jiaqiluo** [comment]
hi @Oats87,  I checked some CI runs that happened after the fix was merged, it takes 30 - 40 mins for each stage to pass, and no failure was found.  That being said, I think we can close this issue. Good job!

**Comment by Oats87** [comment]
Yep, closing it now!
