### ISSUE TITLE
[RFE] ARM64 Architecture Support and Documentation Update in Rancher

### ISSUE THREAD

**Issue by nicokempe** [rancher/rancher#43565]
### Is your feature request related to a problem? Please describe.
Yes, the problem is the lack of support and documentation for deploying Rancher on ARM64 architecture within the Hetzner Cloud environment. The [existing Quick Start Guide ](https://ranchermanager.docs.rancher.com/getting-started/quick-start-guides/deploy-rancher-manager/hetzner-cloud) only addresses x86 (Intel/AMD) setups, and as ARM64 becomes more prevalent, the lack of guidance for it leads to difficulties in deployment and utilization of Rancher on ARM64 systems.

### Describe the solution you'd like
I would appreciate an update to the Quick Start Guide that includes ARM64 architecture. This should not only cover the documentation but also ensure that the underlying functionality supports ARM64 deployments effectively. The solution should facilitate users in setting up Rancher on ARM64 servers, which are now widely available and used.

### Describe alternatives you've considered
An interim solution could be a dedicated experimental feature section in the documentation that outlines the steps and known limitations for ARM64 setups. This would at least provide a starting point for users looking to experiment with Rancher on ARM64.

### Additional context
As per the feedback from the Rancher Docs repository, I am submitting this feature request here. It is currently unclear to what extent Rancher supports ARM64 and whether additional functionality needs to be developed or adjusted. I could not find an existing issue addressing this, indicating a gap in resources for users like myself. (I looked up for solutions directly for Hetzner)

Below is the link to my initial issue in the Rancher Docs repository for reference and the screenshots indicating the availability of ARM64 servers in Hetzner Cloud.

https://github.com/rancher/rancher-docs/issues/970

<img width="1207" alt="280007518-49182347-04f9-44e0-8144-fa87bd4bacf1" src="https://github.com/rancher/rancher/assets/50241630/24f372f5-3479-45ef-8e3b-2ed5d754894d">
<img width="1205" alt="280007590-dd73e717-e149-4a3b-940c-4a5978891f1b" src="https://github.com/rancher/rancher/assets/50241630/bc355df2-5741-4bb7-b816-f2d6e83ea1dc">

**Comment by dj9pz** [comment]
+1

**Comment by jonasfluegge** [comment]
+1

**Comment by alexanderwodarz** [comment]
+1

**Comment by nicokempe** [comment]
still relevant!

**Comment by nicokempe** [comment]
Still relevant
