### ISSUE TITLE
How to share containers(or services) between different stacks(or catalogs)

### ISSUE THREAD

**Issue by okenjian** [rancher/rancher#4357]
Is it possible to share containers between different stacks(or catalogs)?
I have many catalogs, and there is a base one that all other link to it. I want to create only one instance of the base one, just to reduce resource expenses.
Steps to Reproduce: 
both stack A and stack B link to a service in stack C,.
Results: 
 there will be two instances after launching
Expected:
only one instance or the service created.

**Comment by deniseschannon** [comment]
Can you describe your use case? With [Rancher's internal DNS](http://docs.rancher.com/rancher/rancher-services/internal-dns-service/), all containers across stacks are accessible. 

If you are trying to use a data container, you'd need to use a [sidekick service](http://docs.rancher.com/rancher/rancher-ui/applications/stacks/adding-services/#sidekick-services). If using a data container, there is no way to have 2 services using the same data container. This is an open enhancement: https://github.com/rancher/rancher/issues/2159

**Comment by okenjian** [comment]
Adding External Service may slove my problem, But I have to start the External Service before launching a catalog.
