### ISSUE TITLE
[Port v2.8] cluster deploy running excessively and taking a long time to execute

### ISSUE THREAD

**Issue by moio** [rancher/rancher#43570]
This is a port of https://github.com/rancher/rancher/issues/39597

**Rancher Server Setup**
- Rancher version: 2.8.x
- Installation option: any
- Proxy/Cert Details: irrelevant

**Information about the Cluster**
- Kubernetes version: irrelevant
- Cluster Type (Local/Downstream): issue is seen in local cluster with at least one disconnected cluster

**User Information**
- What is the role of the user logged in? irrelevant

**Describe the bug**
With a disconnected downstream cluster, the `clusterdeploy` handler takes several seconds to time out. This is fine with only a few downstream clusters disconnected, but when the number of disconnected clusters goes over 50 or so, the worker queues will get saturated.

Reason for the slow time out is that the handler may execute code that reaches out to the disconnected downstream cluster - typically `clusterDeploy.getNodeAgentImage` which tries to list `DaemonSets`. That alone can take up to ~30 seconds due to how `TunnelServer`'s `remotedialer` mechanism works.

**To Reproduce**
See https://github.com/rancher/rancher/issues/39597#issuecomment-1816099261

**Result**

**Expected Result**
Little to no executions of cluster deploy handler while creating users. Cluster deploy handler should not probably not exceed an execution time of 1 second.

**Screenshots**
N/A
**Additional context**
N/A

**Comment by gaktive** [comment]
@moio v2.8-next1 is at bug complete now. I see a PR has been merged so if that's the case, is this ready for QA?

**Comment by moio** [comment]
@gaktive yes it is, same instructions as the original

**Comment by moio** [comment]
closing per conversation with @git-ival
