### ISSUE TITLE
Container Execute Shell NOT displaying my commands

### ISSUE THREAD

**Issue by zrml** [rancher/rancher#4358]
Hi,

Since yesterday 9th of April 2016 
when I try to connect to the shell of my running containers
the window opens with the root prompt
but 8 times out of 10 the command is not echoed on the terminal
AND it is also not run (I believe)
because I see the # root prompt being echoed back as I press <return> but nothing is happening.

I'm running Rancher on AWS.
This is important for a demo on Tuesday & Wednesday
## Thank you guys.

| Useful | Info |
| :-- | :-- |
| Versions | Rancher `v1.0.0` Cattle: `v0.159.2` UI: `v0.100.3` |
| Access | `Disabled` |
| Route | `containers.index` |

**Comment by deniseschannon** [comment]
Just to confirm, you are opening the execute shell and you can't see what you're typing? Is that the issue?

**Comment by zrml** [comment]
Correct Denise.
I can see the "#" prompt and my cursor but as I type nothing is echoed.
Only when I press <enter> I see a new line, again with the "#" prompt but no output...
thank you

**Comment by vincent99** [comment]
Is your keyboard language in something other than US/English?

**Comment by zrml** [comment]
my keyboard is Italian. However, I'm not utilizing any of those characters. It's a standard querty keyboard as far as linux commands are concerned... and I'm issuing simple pwd, ls etc.
thank you

**Comment by vincent99** [comment]
That doesn't mean the keyboard codes are necessarily the same, but it wouldn't be random.

You can try restarting the rancher/server container and rancher/agent containers on the host(s), they have websocket proxies that connect the terminal to `docker exec`.  Or look at the rancher/server logs and the browser's dev tools -> console for anything interesting.  Everything is loaded locally from the rancher/server container so nothing changed on April 9th unless you changed something like upgrading.

**Comment by deniseschannon** [comment]
I've actually seen this recently (on one of the v1.1.0-dev2-rcX releases, next time it happens, I'll try to see if I can capture anything.

**Comment by zrml** [comment]
Thankyou Denise for sharing it.
FWIW I believe you use the "docker exec" command right?

If I use that (docker exec) on my database container (InterSystems Caché) I can get to the linux shell OK. However when I try to enter the Caché DB shell, it cores.
We have been running on *nix for >20 years and I've never seen that. On a standard Linux distribution IO redirection is just that.
I suspect, and I believe other people saw this in the early days of Docker containers, that the exec command it's not or does not perform that re-direction as it should... I've not looked into that at any lower level (reviewing the GO code etc.) but I think there might be a problem with Docker basically.

just FYI.

Thanks

**Comment by superseb** [comment]
Please file a new issue if you're still experiencing issues.

**Comment by zrml** [comment]
OK Thanks.
FYI it is believed to be this issue
https://github.com/moby/moby/issues/8755
which should be fixed in the next release by 
https://github.com/moby/moby/issues/8755#issuecomment-300152451

a workaround is to use the script command as in
$ docker exec -it <container_name> script -q -c "/bin/bash" /dev/null

HTH
