### ISSUE TITLE
[BUG] LKE clusters fail to provision on newer K8s versions

### ISSUE THREAD

**Issue by lgarber-akamai** [rancher/rancher#43583]
**Rancher Server Setup**
- Rancher version: v2.7.9
- Installation option (Docker install/Helm Chart): Docker install

**Information about the Cluster**
- Kubernetes version: v1.27
- Cluster Type (Local/Downstream): Hosted (LKE)

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): Admin

**Describe the bug**
In newer versions of Kubernetes, service account secrets are not implicitly created alongside service accounts. This is preventing LKE clusters from being provisioned through Rancher because older versions of kontainer-engine-driver-lke rely on this implicitly created token.

**To Reproduce**

1. Attempt to provision an LKE cluster using the built-in LKE driver.

**Result**

Provisioning fails, creation is retried, and the following error is raised:

```
Failed to create LKE cluster: [400] [label] Must be unique
```

**Expected Result**

The cluster successfully provisions as expected.

**Additional context**

We have already addressed this issue in [kontainer-engine-driver-lke v0.0.8](https://github.com/linode/kontainer-engine-driver-lke/releases/tag/v0.0.8), so I'll be putting up a PR shortly to bump the version here.

**Comment by pgonin** [comment]
Kubernetes v1.27 is not supported in Rancher 2.7.9 so it should not be offered (yet)
