### ISSUE TITLE
[BUG] Cannot set custom Node Name for Windows worker nodes

### ISSUE THREAD

**Issue by HarrisonWAffel** [rancher/rancher#43587]
**Rancher Server Setup**
- Rancher version: tested on 2.7.4 and 2.7.9
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): n/a
- Proxy/Cert Details: n/a

**Information about the Cluster**
- Kubernetes version: tested on v1.26.10
- Cluster Type (Local/Downstream): downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: n/a

**Describe the bug**

When registering windows nodes to a custom RKE2 cluster, the UI allows the user to specify the desired name for the incoming node. Executing the registration script after configuring a custom node name does not result in the new node using that name, instead the hostname is used. This issue also reproduces when adding the `-NodeName` flag to the registration command manually. This same UI option works as expected for linux nodes. 

**To Reproduce**
+ Create a custom RKE2 cluster
+ Register an etcd/cp linux node 
+ Provision and prepare a Windows worker node
+ Within the UI, navigate to the registration tab for the custom cluster
+ Open the `Advanced` registration options 
+ Provide a custom node name 
+ execute the updated registration script on the Windows worker node 

**Result**
+ The node successfully joins, but does not use the specified node name. 

**Expected Result**
The node joins using the correct name

**Additional context**
I've seen unexpected behavior when mixing linux style flags and proper Powershell flags (i.e. using `--node-name` as opposed to the proper `-NodeName` flag). 

SURE-6895

**Comment by HarrisonWAffel** [comment]
While looking for a workaround I stumbled upon the root cause, I've raised a PR with a fix within `wins`. 

The root cause is due to a missing header to the `v3/connect/agent` endpoint, which results in the custom node name not being honored. The fix is to add that missing header when wins gathers the Rancher connection info. This fix can be manually applied by breaking the registration command into two parts. First download the `install.ps1` file and update line `766` so that `-H "X-Cattle-Node-Name: $($env:CATTLE_NODE_NAME)"` is added. Then, execute the script (including all flags shown in the Rancher UI).

**Comment by susesgartner** [comment]
Ticket #43587 - Test Results - ✅ 
---
 
| Scenario | Test Case | Result |
|---|---|---|
| 1. | Test custom name | PASS |
| 2. | Test default name | PASS |
 
---
Verified with HA Helm on Rancher `v2.9-head`:
---
 
Scenario 1: Test custom name
---
1. Create a custom cluster 
2. Register 2 linux nodes with all roles
3. Register 1 windows worker node with a custom name
 
Results:
The custom name set in step 3 was properly set

---
 
Scenario 2: Test default name
---
1. Create a custom cluster 
2. Register 2 linux nodes with all roles
3. Register 1 windows worker node
 
Results: The default name was displayed was properly set

**Comment by susesgartner** [comment]
Automation note: No additional automation testing required
