### ISSUE TITLE
[RFE] Add v2prov integration tests to KDM

### ISSUE THREAD

**Issue by jakefhyde** [rancher/rancher#43585]
**Is your feature request related to a problem? Please describe.**

When new versions are added to KDM, failures are often not detected until rancher itself consumes these KDM updates.

**Describe the solution you'd like**

We would like a mechanism to be able to view failures on a PR, and potentially block merging to a KDM release branch in the event of these failures in order to catch thee failures earlier on.

**Describe alternatives you've considered**

It is not feasible or realistic to put these tests into the rke2 or k3s repos, as they have their own standalone tests for these integrations.

**Additional context**

**Comment by jakefhyde** [comment]
No testing needed from QA, CI will judge.

**Comment by markusewalker** [comment]
Closing issue.
