### ISSUE TITLE
[BUG] SSH Shell instant disconnects

### ISSUE THREAD

**Issue by edwin-bruurs** [rancher/rancher#43598]
**Rancher Server Setup**
- Rancher version: 2.7.6
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2 1.26.8

**Information about the Cluster**
- Kubernetes version: 1.26.8
- Cluster Type (Local/Downstream): Local (RKE2 1.26.8) and Downstream (vSphere provisioned RKE2 1.26.8)

**User Information**
- What is the role of the user logged in? Admin

**Describe the bug**
When trying to connect to the host using the SSH Shell feature in Rancher the terminal is disconnected right away. Looking into the logs of the rancher pods it gives the followin error `[ERROR] Unknown error: dial tcp: address fe80::250:56ff:fe9a:3d45:22: too many colons in address`. 
The host is actually configured with an IPv4 and IPv6 address, but even after removing / disabling IPv6 on the host Rancher still tries to use the old IPv6 address.

vSphere states only one IP address (the IPv4), but Rancher still favours the IPv6 address. Where is this IPv6 address configured and how can I force Rancher to use the IPv4 address for the SSH Shell.

Note; it looks like it happens random on nodes. I have nodes with exactly the same configuration which works fine using SSH shell, while others goes into Disconnected state right away.

**Comment by edwin-bruurs** [comment]
Looking further into this issue, it looks like it is related to the OS version the hosts are running. The hosts which works as expected have Ubuntu 22.04.1 running, while the others are running Ubuntu 22.04.3.

**Comment by mario-madrid** [comment]
Hi, I have the same problem trying new ubuntu version (24.04) and I have worked around the issue disabling ipv6 at GRUB level following [this article](https://itsfoss.com/disable-ipv6-ubuntu-linux/#2-disable-ipv6-using-grub) option 2. Disable Ipv6 using GRUB. Now I can ssh from the dashboard without issues. 

I had to reprovision the machines in order for this to work. It's like you need to have ipv6 disabled during the machine provision so Rancher cannot save any Ipv6 that will be used later to try to connect.

**Comment by nickvth** [comment]
@edwin-bruurs I see it's closed, but do you have a solution/workaround for this?

**Comment by edwin-bruurs** [comment]
@nickvth at some point we rebuild our environment using a more recent Rancher version (think we started with 2.9 or 2.10) and Ubuntu 24 as host OS. After using that setup we didn't have this issue anymore. So my assumption was that it was fixed in either Rancher, Ubuntu or a combination of both.

So unfortunately I don't have a real clear solution or workaround.
