### ISSUE TITLE
Add both deleting options to replication controller in kubernetes

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#4359]
Rancher Version:
1.0.0

The current version of Rancher implements deleting replication controller the same way as adding "--cascade=false" in the kubectl command:
```
kubectl delete rc nginx --cascade=false
```
which results in deleting only the replication controller without deleting the associated pods, perhaps it may be better to add both options in deleting from Rancher UI.

**Comment by alena1108** [comment]
It would be a UI issue - UI should call kubectl instead of calling kubernetes APIs

**Comment by drauschenbach** [comment]
Kubernetes docs say that deleting a replication controller deletes the pods. So until the UI allows an override, it should perform the default behavior and match the user expectation set in this Kubernetes doc:

http://kubernetes.io/docs/user-guide/replication-controller/operations/#deleting-replication-controllers

**Comment by vincent99** [comment]
The docs say kubectl does that, and indeed it does.. but there is no such actual option in the API, they do it by listing and individually deleteing resources.

Anyway, the UI was changed in 1.2-pre1 to use kubectl for remove, which will have cascade=true.

**Comment by tfiduccia** [comment]
version - v1.2.0-pre3-rc1
Verified fixed
