### ISSUE TITLE
LB Agent is launched even when there is no targets associated with it

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#436]
Version - V0.14.2

Steps to reproduce the issue:
Create a LB rule with LB config which has 1 listener associated with it.
Add host to this LB rule.

At this point , i see LB Agent being launched on the host.
Why is there a need for this LB Agent to be created now , since there is no targets to serve at this point?

We should be able to launch LB Agent only when there is atleast 1 host , 1 target and 1 listener added to the LB.

**Comment by alena1108** [comment]
It was designed this way to simply avoid more complicated logic. Today haproxy lifecycle is controlled by adding/removing host to the load balancer. If we do it based on adding/removing listener/target, we will have to take care of more use cases (On removal: if the listener removed is the last listener, or is the target removed is the last target; On creation: when target gets added, we should check if there is at least one listener there, etc). We can address this one later after major functional bugs are fixed.

**Comment by deniseschannon** [comment]
I don't believe this is relevant any more with the newly refactored load balancer in v1.2.0.
