### ISSUE TITLE
[BUG] Missing Icon's Images

### ISSUE THREAD

**Issue by nicholasSUSE** [rancher/rancher#43603]
**Rancher Server Setup**
- Rancher version: 2.7.5 +
- Installation option (Docker install/Helm Chart):
   - Helm Chart: v1.25.11+k3s1
- Proxy/Cert Details: None

**Information about the Cluster**
- Kubernetes version:
- Cluster Type (Local/Downstream): Local

**User Information**
- Admin/Cluster

---

**Describe the bug**
At `https://<RANCHER_URL>:8443/dashboard/c/local/apps/charts` 
Some Chart Icons are failing and others are returning status 404 again

I solved a similar bug at the beginning of the year for other charts.
The problem is that we depend on URLs provided by third parties, when something happens to their services or they simply change the URL we get errors fetching the images.

**To Reproduce**
Simple Helm Install from rancher-stable helm repo:
```
RANCHER_VERSION="2.7.5"
RANCHER_REPO="rancher-stable"
RANCHER_REPO_URL="https://releases.rancher.com/server-charts/stable"
HOST="rancher.local"

helm install rancher $RANCHER_REPO/rancher \
  --namespace cattle-system \
  --set replicas=1 \
  --set addLocal="true" \
  --set hostname=$HOST \
  --set global.cattle.psp.enabled=false \
  --version $RANCHER_VERSION \
  --debug
```

**Result**
All these URLs when downloading Icons for Mapps Charts Fail or respond with 404 status 
```
https://rancher.local:8443/v1/catalog.cattle.io.clusterrepos/rancher-partner-charts?chartName=gopaddle&link=icon&version=4.2.8
https://rancher.local:8443/v1/catalog.cattle.io.clusterrepos/rancher-partner-charts?chartName=jenkins&link=icon&version=4.3.29
https://rancher.local:8443/v1/catalog.cattle.io.clusterrepos/rancher-rke2-charts?chartName=rke20coredns&link=icon&version=1.24.004
https://rancher.local:8443/v1/catalog.cattle.io.clusterrepos/rancher-partner-charts?chartName=kamaji-console&link=icon&version=0.0.4
https://rancher.local:8443/v1/catalog.cattle.io.clusterrepos/rancher-rke2-charts?chartName=rke2-multus&link=icon&version=v3.9.3-build2023010903
```

**Expected Result**
All icons should be available for the client responding with 200.

**Screenshots**
![image](https://github.com/rancher/rancher/assets/127259813/cff5dc5c-59f2-4529-8ccb-d451b6f720f4)

**Additional context**
This is a recurring problem and will keep happening unless we start to serve ourselves the icon's images or bundle them within rancher. 

Different chart versions might have different images failing or none.

**Proposed solution**
Host and serve ourselves all the necessary icon images.

**Comment by enneitex** [comment]
Hey, having images stored in rancher would also fix missing icon in air-gapped setup https://github.com/rancher/rancher/issues/41765
