### ISSUE TITLE
[Backport v2.7] Missing the vSphere CSI Snapshotter sidecar - blockSnapshots will never work

### ISSUE THREAD

**Issue by a-blender** [rancher/rancher#43602]
**Is your feature request related to a problem? Please describe.**

Backport for https://github.com/rancher/rancher/issues/41321 because the internal customer saw this issue on 2.7.8 so this needs to be included in the next v2.7.x release.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

SURE-7177

**Comment by snasovich** [comment]
This will not be backported to 2.7 as there is a workaround to deploy CSI snapshotter manually and there are some concerns with additional changes from https://github.com/rancher/vsphere-charts that were included as part of https://github.com/rancher/charts/pull/3658.
Keeping this open until revert PR (https://github.com/rancher/charts/pull/3766) is merged.
