### ISSUE TITLE
Kiali Graph not working with istio 1.19 in a HA cluster

### ISSUE THREAD

**Issue by diogoasouza** [rancher/rancher#43600]
When installing Kiali 1.76 with istio 1.19 in a HA cluster, the graph does not work if the "display idle nodes" option is selected.

![image.png](https://zube.io/files/rancher/b41d93186d068f616204995729ab65e3-image.png)

**Comment by rohitsakala** [comment]
This issue also adds a new version of Istio 1.19.5 to dev-v2.8

**Comment by diogoasouza** [comment]
This was fixed by https://github.com/rancher/charts/pull/3612
