### ISSUE TITLE
[SURE-7214] Helm sync errors in rancher logs after upgrade to 2.7.6 (from 2.6.13)

### ISSUE THREAD

**Issue by skanakal** [rancher/rancher#43611]
**Rancher Server Setup**
- Rancher version: 2.7.6
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: 1.24.17
- Cluster Type (Local/Downstream): Local
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Admin

**Describe the bug**

The rancher pods in the `cattle-system` namespace have errors like the following in their logs:

~~~
2023/10/17 17:59:09 [ERROR] error syncing 'p-vxb8t/rancher-logging': handler helm-controller: wait helm template failed. Error: found in requirements.yaml, but missing in charts/ directory: fluentd, log-aggregator, fluent-tester 2023-10-17T17:59:09.598452250Z : exit status 1, requeuing.
~~~

**To Reproduce**

**Result**
Rancher logs are spammed with helm sync errors after the Rancher upgrade. 

**Expected Result**

No helm sync errors in the Rancher pods.

**Screenshots**

**Additional context**

int ref: [SURE-7214](https://jira.suse.com/browse/SURE-7214)

**Comment by rohitsakala** [comment]
Closing this as rancher-logging is deprecated in 2.5.0 and the suggestion was to move on to logging chart in rancher/charts.
