### ISSUE TITLE
[v2.8] Bump k8s dns images to 1.22.28

### ISSUE THREAD

**Issue by vardhaman22** [rancher/rancher#43637]
SURE-7205
bump kubernetes dns images to 1.22.28 for in RKE1 KDM k8s releases: v1.25.16, v1.26.11, v1.27.8

**Comment by vivek-shilimkar** [comment]
Kubernetes DNS image has been correctly bumped for the k8s versions v1.25.16, v1.26.11, v1.27.8. Hence closing this ticket.
