### ISSUE TITLE
support default container

### ISSUE THREAD

**Issue by beastpu** [rancher/rancher#43642]
During the debugging process, we often need to execute commands within a specified container. However, it becomes increasingly inconvenient when a pod includes multiple containers and we need to select the desired container each time we run the 'exec' command through Rancher.

 To improve this experience, could we possibly implement a feature to set a default container?

 I discovered that Kubernetes supports the kubectl.kubernetes.io/default-container annotation in a Pod to pre-select a container for kubectl exec. This could potentially streamline our debugging process.

**Comment by bereczkitamas** [comment]
Yes, this support would be useful and also it would be good if the pods list shows this default container.

![image](https://github.com/rancher/rancher/assets/11897691/11a515ec-7aa6-4047-a0fa-c2ba7f7bd37a)

**Comment by bereczkitamas** [comment]
open

**Comment by gortvab** [comment]
Please don't close this issue, it is important for us 😢
