### ISSUE TITLE
[BUG]

Failed to reconcile etcd plane: Etcd plane nodes are replaced. Stopping provisioning. Please restore your cluster from backup.


### ISSUE THREAD

**Issue by kernelmix** [rancher/rancher#43644]
**Rancher Server Setup**
- Rancher version: 2.5.16
- Installation option (Docker install):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): docker 
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.20.15
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:

**Describe the bug**

**To Reproduce**

**Result**

**Expected Result**

**Screenshots**

**Additional context**

**Comment by Oats87** [comment]
@kernelmix I fail to see a bug here. As the title of your issue states, you must restore your cluster from an etcd snapshot.

Please refile with further context as to how this is a bug.

**Comment by Delta1977** [comment]
K3s team say that's a rancher problem:

https://github.com/k3s-io/k3s/issues/8997
