### ISSUE TITLE
Disable managed network for services/stacks deployed from catalog

### ISSUE THREAD

**Issue by VPusher** [rancher/rancher#4366]
The issue #1429 brought an interesting topic: how to disable managed network for a container? But, it remains unanswered.

I saw it can be achieved by selecting *bridge* in the **networking** tab when deploying a service.

But what about rancher-compose ? I'm trying to disable the managed network for services deployed from catalog. Is there any attribute in the `rancher-compose.yml` file I can use to perform such a thing ?

I tried to set the label `io.rancher.container.network=false` or set **network_mode** to *bridge* in the `docker-compose.yml` without success.

**Comment by deniseschannon** [comment]
How did you set it up in docker-compose.yml?

https://docs.docker.com/v1.8/compose/yml/#net

Also, if you can't figure out something in the UI and how it translates to docker-compose.yml, you can always add the service in Rancher and click on "View Config" in the stack dropdown menu to see how it is represented in docker-compose/rancher-compose.yml.

**Comment by VPusher** [comment]
Ok, I was using the **docker-compose v2** syntax with attribute `network_mode`.

Using attribute `net` instead made it !

Last question: is it doable in the `rancher-compose.yml` file ?

**Comment by deniseschannon** [comment]
@VPusher No, it has to be in docker-compose.yml.

**Comment by deniseschannon** [comment]
@VPusher I'll close this issue as it seems as you've been able to resolve. You might be also interested in this other issue of  when we add in docker-compose V2 support: 
https://github.com/rancher/rancher/issues/3973
