### ISSUE TITLE
[BUG] OIDCConfig.Scopes struct field tag is not compatible with reflect.StructTag.Get

### ISSUE THREAD

**Issue by pmatseykanets** [rancher/rancher#43668]
**Rancher Server Setup**
N/A

**Information about the Cluster**
N/A

**User Information**
N/A

**Describe the bug**

There is  typo in `OIDCConfig.Scopes` struct field tag
https://github.com/rancher/rancher/blob/2581a956996c948945dac34ca159c32ce556a6bd/pkg/apis/management.cattle.io/v3/authn_types.go#L457

```
struct field tag `json:"scope", norman:"required,notnullable"` not compatible with reflect.StructTag.Get: key:"value" pairs not separated by spaces
```

It was there since the originating commit a2a501c6d2270837ee17d8d139b489ce324ec46e

**To Reproduce**

N/A

**Result**

**Expected Result**

**Screenshots**

**Additional context**

**Comment by MKlimuszka** [comment]
@pmatseykanets , please add reproduction steps for QA to test.

**Comment by MKlimuszka** [comment]
\backport v2.8.3

**Comment by dasarinaidu** [comment]
Validated this issue on `v2.9-db525a1c917b0a24f6e2af1cac32e5c928b2a8be-head`, all the test cases are passed and no new issues reported. I am closing this card.
