### ISSUE TITLE
[Feature] k8s 1.28 support - apps and feature charts

### ISSUE THREAD

**Issue by gunamata** [rancher/rancher#43688]
Parent issue: https://github.com/rancher/rancher/issues/43109

**Team Mapps** (@recena)

- [x] rancher/rancher#43709
- [x] rancher/rancher#43726
- [x] rancher/rancher#43727
- [x] (Infracloud) rancher/rancher#43741

**Team Socket** (@jeremy-moffitt)

- [x] rancher/rancher#43729

**Frameworks** (@prachidamle  / @MKlimuszka )

- [x] rancher/rancher#44018

**Hostbusters** (@snasovich / @Jono-SUSE-Rancher)

- [x] rancher/rancher#43730
- [x] rancher/rancher#43979
- [x] rancher/rancher#43980

**Observation & Backup** (@prachidamle / @MKlimuszka)

- [x] rancher/rancher#43742
- [x] rancher/rancher#43743
- [x] rancher/rancher#43737
- [x] rancher/rancher#43738
- [x] rancher/rancher#43739

**Fleet** (@olblak / @kkaempf)

- [x] rancher/rancher#43744

**Highlander** (@mbologna / @kkaempf)

- [x] rancher/rancher#43745
- [x] rancher/rancher#43746
- [x] rancher/rancher#43747

**Harvester** (@rebeccazzzz)

- [x] rancher/rancher#43748
- [x] rancher/rancher#43749

**Longhorn** (@rebeccazzzz)

- [x] rancher/rancher#43750

**NeuVector** (@selvamt94)

- [x] rancher/rancher#43751

**Kubewarden** (@olblak / @flavio)

- [x] rancher/rancher#43752

**Misc / N/A / TBD**
- [ ] rancher/rancher#44568 (@mgfritch)

**Comment by Jono-SUSE-Rancher** [comment]
Closing as we are currently in final validation stages.
