### ISSUE TITLE
Health check fails if endpoint returns Content-Type: application/json

### ISSUE THREAD

**Issue by akosratku** [rancher/rancher#4368]
##### Rancher Version:
1.0.0
##### Docker Version:
1.10.3
##### OS: 
ubuntu
##### Steps to Reproduce: 
Create a health check to an endpoint which is returning a json with  `Content-Type:application/json`
##### Results: 
Service stucks in initializing and eventually becomes unhealthy
##### Expected:
Http code 200 is respected and the service marked as healthy

**Comment by deniseschannon** [comment]
Do you have an exmaple docker-compose.yml that I could try to reproduce?

Are you sure that cross host communication is working? Services can get stuck in initializing when it's not working. An easy way to test is to exec into one of hte network agents and ping the `10.42.x.x` of another network agent.

**Comment by deniseschannon** [comment]
@akosratku If you are still facing issues and can provide more information, please re-open.
