### ISSUE TITLE
[BUG] Can't upgrade a 1.21 custom cluster to 1.22 with latest Rancher release

### ISSUE THREAD

**Issue by tailtwo** [rancher/rancher#43702]
**Rancher Server Setup**
- Rancher version:
v2.7.9
- Installation option (Docker install/Helm Chart):
Helm chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
   RKE1
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version:
v1.21.14
- Cluster Type (Local/Downstream):
Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):
   Custom

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
Admin

**Describe the bug**

I previously installed a custom 1.21 cluster from an old Rancher release. For a while, I didn't upgraded it but I kept upgrading Rancher the latest version. Now I want to upgrade this cluster to a newer version, but I am unable to because the oldest version that is available for RKE1 templates is `1.23.16-rancher2-3`. I would like to upgrade to any 1.22 version first as recommended by Kubernetes upgrade procedures.
Manually editing the template yaml to specify the desired Kubernetes version returns an error ("not allowed by template"). Using this template doesn't work, nothing happens after saving the cluster with this new template. (see screenshot).

**To Reproduce**

- Install a custom 1.21 cluster with an old Rancher release
- Upgrade Rancher to the latest release available
- Try to upgrade the custom cluster to 1.22

**Result**
Version 1.22 of Kubernetes isn't available to be installed, blocking the cluster upgrade path.

**Expected Result**

Version 1.22 of Kubernetes is available for upgrading a 1.21 Kubernetes cluster with Rancher.

**Screenshots**

![Screenshot_20231206_171742](https://github.com/rancher/rancher/assets/12949450/54d4f248-723a-44b2-bd22-b2a0bb6e20d8)

**Additional context**

**Comment by Oats87** [comment]
@tailtwo Kubernetes v1.22.x is no longer supported by Rancher in `v2.7.9`. See: https://www.suse.com/suse-rancher/support-matrix/all-supported-versions/rancher-v2-7-9/
