### ISSUE TITLE
[v2.8] Merge Nov 2023 K8s patches from custom branch to dev branch

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#43704]
Tracking issue for merging Nov patches from custom KDM branch `dev-v2.8-2023-11-patches` to `dev-v2.8` (or `release-v2.8` to `dev-v2.8` once the custom branch is merged to release).

**Comment by vardhaman22** [comment]
done.
PR: https://github.com/rancher/kontainer-driver-metadata/pull/1287
