### ISSUE TITLE
[v2.7] Merge Nov 2023 K8s patches from custom branch to dev branch

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#43703]
Tracking issue for merging Nov patches from custom KDM branch `dev-v2.7-2023-11-patches` to `dev-v2.7` (or `release-v2.7` to `dev-v2.7` once the custom branch is merged to release).

**Comment by vardhaman22** [comment]
done with PR: https://github.com/rancher/kontainer-driver-metadata/pull/1288
