### ISSUE TITLE
[BUG] - Rancer 2.8 Install docs result in 404

### ISSUE THREAD

**Issue by gavinmcfall** [rancher/rancher#43712]
https://rancher.com/docs/rancher/v2.8/en/installation/

Giving a 404. Can't view install docs

**Comment by quadeare** [comment]
Hi,

Installation doc is here : https://ranchermanager.docs.rancher.com/v2.8

Have a nice day

**Comment by cbron** [comment]
Thanks for providing the link @quadeare . You can also use the latest url: https://ranchermanager.docs.rancher.com/pages-for-subheaders/installation-and-upgrade
