### ISSUE TITLE
[v2.7] Add CIS-1.8 (k8s v1.26) Scan capability

### ISSUE THREAD

**Issue by rayandas** [rancher/rancher#43710]
Backport of https://github.com/rancher/rancher/issues/43159

CIS Workbench has released [CIS-1.8 for k8s v1.26](https://workbench.cisecurity.org/benchmarks/12958) (on oct 6th).

This issue is pending the creation of cis-1.8 in [kube-bench's cfg](https://github.com/aquasecurity/kube-bench/tree/main/cfg). We will start integrating CIS-1.8 to Rancher cis-benchmark once the profile will be made available upstream.

Past issue for CIS-1.7 : https://github.com/rancher/rancher/issues/41631

**Comment by rishabhmsra** [comment]
Validated on rancher v.27-head with CIS chart version 4.3.0-rc4:

Fresh install checks :
- Provisioned k8s v1.26 hardened and non-hardened RKE1, RKE2 and K3s clusters and ran cis 1.8 hardened as well as 1.8 permissive profile scan.
 
Upgrade checks :
- Provisioned k8s v1.25 hardened and non-hardened RKE1, RKE2 and K3s clusters and then installed CIS 4.2.0 chart on all the clusters and ran scan using v1.7 profile.
- Upgraded clusters to k8s v1.26 and then upgraded the chart to CIS 4.3.0-rc4 version.
- Ran CIS 1.8 hardened as well as 1.8 permissive profile scan.

Local cluster checks :
- Created hardened and non-hardened k8s v1.26 RKE1, RKE2 and K3s clusters and ran CIS 1.8 hardened as well as permissive profile scans.

Result:
- All scan passed except below ones, which are [expected](https://github.com/rancher/rancher/issues/42971) and will be release noted:
  - One failure in RKE1 hardened cluster:
```
Mixed
4.1.7	Ensure that the certificate authorities file permissions are set to 600 or more restrictive (Automated)
```

 - Failures in RKE2 clusters:
```
Fail
1.1.1	Ensure that the API server pod specification file permissions are set to 600 or more restrictive (Automated)
Fail
1.1.3	Ensure that the controller manager pod specification file permissions are set to 600 or more restrictive (Automated)
Fail
1.1.5	Ensure that the scheduler pod specification file permissions are set to 600 or more restrictive (Automated)
Fail
1.1.7	Ensure that the etcd pod specification file permissions are set to 600 or more restrictive (Automated)
```
