### ISSUE TITLE
Retrying on non-existant image pull

### ISSUE THREAD

**Issue by bengerman13** [rancher/rancher#4371]
Rancher shows "Starting (Storage : Pulling repository \<repo>/\<image>)"  indefinitely if the image is not found. It looks like Rancher continues to attempt to pull the image indefinitely if it's not found, it would be nice if it reported that the image was not found to make it easier to tell what's going on quickly (i.e. invalid version vs slow pull)

ImageValidationError: Image [\<private-repo>/\<nonexistant image>] failed to pull: Error: image \<nonexistant image> not found

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.0.0` Cattle: `v0.159.2` UI: `v0.100.3` |
|Access|`Disabled`|
|Route|`environment.code`|

**Comment by deniseschannon** [comment]
If your service is stuck in activating state, you can drill down to the containers to see why the containers are not starting. They will be in an error state for a min or two before attempting to deploy again. In the errored state, the container will display the reason why the container was unable to start (most common reason is lack of available ports on a host). 

As Rancher tries to continue to schedule new containers for a service that you may not be paying attention to why it's stuck, we start to back off the attempted scheduling over time. 

In your case, the errored state of the container indicates exactly the fact that the image does not exist.
