### ISSUE TITLE
rancher-webhook k8s 1.28 chart support

### ISSUE THREAD

**Issue by gunamata** [rancher/rancher#43728]
**This issue is to implement the chart changes & perform the required testing to support k8s 1.28. The generic process that's applicable for most charts is described here. Please adjust the steps to fit your respective chart wherever required. Perform the steps below:**

- [x] Once you pick up the issue for your chart, apply the label `[zube]: Working` to the issue
Note: If this is an upstream chart (ex: istio) and if the upstream chart doesn't support k8s 1.28 then this exercise is not applicable to you. Just add a comment that the upstream chart doesn't support k8s 1.28 and apply the label `[zube]: Done`. If this is not an upstream chart then proceed to the next step.
- [ ] Update kube-version annotation in Chart.yaml to `catalog.cattle.io/kube-version: '>= 1.23.0-0'` or `catalog.cattle.io/kube-version: '>= 1.23.0-0 < 1.29.0-0'`
- [ ] Follow the usual process to add a new chart version and file a PR to the `rancher/charts:dev-v2.8` branch. Link the PR to the issue.
- [ ] Perform the usual Developer testing and if everything looks good then merge the PR. After merging the PR,  apply the label `[zube]: To Test`. Tag the respective QA team members.
- [ ] Perform below testing
   - [ ] Spin up Rancher 2.8 with k8s 1.27
   - [ ] Add a downstream cluster with k8s 1.28
   - [ ] Point the Rancher charts repository of the downstream cluster to dev-v2.8 branch
   - [ ] Install the dev version of the chart. Verify that the installation is successful
   - [ ] Perform chart functionality testing (any tests in QA test plans for the chart)
   - [ ] Uninstall the chart. Verify that the uninstallation is successful
   - [ ] Install the prod version of the chart. Verify that the installation is successful
   - [ ] Upgrade to the dev version of the chart. Verify that the upgrade is successful
   - [ ] Add a downstream cluster with k8s 1.27
   - [ ] Install the prod version of the chart
   - [ ] Upgrade the k8s version of the downstream cluster to 1.28. Verify the chart still works after the upgrade
   - [ ] Perform any additional testing specific to your chart if required
- [ ] If the testing passes then apply the label `[zube]: Done`. If you are blocked with any steps, add a comment with details and apply the label `[zube]: Blocked`

**Comment by MKlimuszka** [comment]
SURE-7716

**Comment by Priyashetty17** [comment]
Moving this back to QA Next Up due to a blocker issue: https://github.com/rancher/rancher/issues/45199 which must be resolved first before we can proceed with the validation for this issue. cc @MKlimuszka @daviswill2

**Comment by Priyashetty17** [comment]
QA update: Waiting for https://github.com/rancher/charts/pull/3834 to be merged

**Comment by Priyashetty17** [comment]
# ✅ PASSED

**Validated with: v2.9-052adb3785094a4c9bd75b039552a52478f6edad-head** (**webhook version: v0.5.0-rc8**)

<a name="top"></a>

### Test Cases

| \#  | Priority | Description & Link                           | PASS/FAIL |
| --- | -------- | -------------------------------------------- | --------- |
| 1   | P0       | [Fresh Install Rancher - k8s v1.28](#test-1) | ✅ PASS    |
| 2   | P0       | [Upgrade - k8s 1.27 to 1.28](#test-2)        | ✅ PASS    |

<details>
    <summary>🚨 2 test cases... CLICK TO EXPAND! (For table links to work) ⬅️</summary>

<br>

# 1 / Fresh Install Rancher - k8s v1.28 Status: ✅ PASS

<a name="test-1"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 1 details... Click to expand</summary>

**Test Steps for Validation**

1. Create a rancher server v2.9-head with k8s v1.28 and a downstream cluster with k8s 1.28.
2. Verify that rancher-webhook is installed on both local and downstream clusters
3. Verify that the version of the webhook is as expected on both local and downstream clusters- `v0.5.0-rc8`
4. Verify kube-version annotation in the webhook chart's yaml has: catalog.cattle.io/kube-version: '>= 1.23.0-0 < 1.29.0-0'
5. Verify that there are no errors in the rancher-webhook logs
6. Verify count in local cluster with `kubectl get validatingwebhookconfigurations.admissionregistration.k8s.io rancher.cattle.io`
   1. response: `rancher.cattle.io   19`
   2. passing expected count
7. Verify count in downstream cluster with `kubectl get validatingwebhookconfigurations.admissionregistration.k8s.io rancher.cattle.io`
   1. response: `rancher.cattle.io   7`
   2. passing expected count
8. Create a restricted admin user
9. Login as restricted admin
10. Attempt to edit the admin role, while logged in as restricted admin
11. Attempt to set admin to "Yes: Default role for new users"
    1.  Blocked by webhook as expected

**✅ Expected Outcome**

For Rancher webhook to work with k8s 1.28. For the expected version to be installed and for there to be no errors present. For webhook P0 checks to pass.

**✅ Actual Outcome**

Webhook checks are passing as expected.

</details>

<hr>

# 2 / Upgrade - k8s 1.27 to 1.28 Status: ✅ PASS

<a name="test-2"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 2 details... Click to expand</summary>

**Test Steps for Validation**

1. Create a rancher server on the latest released version with k8s v1.27 
2. Create a downstream RKE2 cluster with k8s 1.27
3. Upgrade Rancher to v2.9-head
4. Upgrade the downstream RKE2 cluster from 1.27 to ==> 1.28
5. Verify that rancher-webhook is upgraded on both local and downstream clusters
6. Verify that the version of the webhook is as expected on both local and downstream clusters. `v0.5.0-rc8`
7. Verify kube-version annotation in the webhook chart's yaml has: catalog.cattle.io/kube-version: '>= 1.23.0-0 < 1.29.0-0'
8. Verify that there are no errors in the rancher-webhook logs
9. Verify count in local cluster with `kubectl get validatingwebhookconfigurations.admissionregistration.k8s.io rancher.cattle.io`
   1. response: `rancher.cattle.io   19`
   2. passing expected count
10. Verify count in downstream cluster with `kubectl get validatingwebhookconfigurations.admissionregistration.k8s.io rancher.cattle.io`
   1. response: `rancher.cattle.io   7`
   2. passing expected count
11. Create a restricted admin user
12. Login as restricted admin
13. Attempt to edit the admin role, while logged in as restricted admin
14. Attempt to set admin to "Yes: Default role for new users"
    1.  Blocked by webhook as expected

**✅ Expected Outcome**

For Rancher webhook to work with k8s 1.28 after upgrade. For the expected version to be installed and for there to be no errors present. For webhook P0 checks to pass.

**✅ Actual Outcome**

Webhook checks are passing as expected.


</details>

<hr>

</details>
