### ISSUE TITLE
system-upgrade-controller k8s 1.28 chart support

### ISSUE THREAD

**Issue by gunamata** [rancher/rancher#43730]
**This issue is to implement the chart changes & perform the required testing to support k8s 1.28. The generic process that's applicable for most charts is described here. Please adjust the steps to fit your respective chart wherever required. Perform the steps below:**

- [ ] Once you pick up the issue for your chart, apply the label `[zube]: Working` to the issue
Note: If this is an upstream chart (ex: istio) and if the upstream chart doesn't support k8s 1.28 then this exercise is not applicable to you. Just add a comment that the upstream chart doesn't support k8s 1.28 and apply the label `[zube]: Done`. If this is not an upstream chart then proceed to the next step.
- [ ] Update kube-version annotation in Chart.yaml to `catalog.cattle.io/kube-version: '>= 1.23.0-0'` or `catalog.cattle.io/kube-version: '>= 1.23.0-0 < 1.29.0-0'`
- [ ] Follow the usual process to add a new chart version and file a PR to the `rancher/charts:dev-v2.8` branch. Link the PR to the issue.
- [ ] Perform the usual Developer testing and if everything looks good then merge the PR. After merging the PR,  apply the label `[zube]: To Test`. Tag the respective QA team members.
- [ ] Perform below testing
   - [ ] Spin up Rancher 2.8 with k8s 1.27
   - [ ] Add a downstream cluster with k8s 1.28
   - [ ] Point the Rancher charts repository of the downstream cluster to dev-v2.8 branch
   - [ ] Install the dev version of the chart. Verify that the installation is successful
   - [ ] Perform chart functionality testing (any tests in QA test plans for the chart)
   - [ ] Uninstall the chart. Verify that the uninstallation is successful
   - [ ] Install the prod version of the chart. Verify that the installation is successful
   - [ ] Upgrade to the dev version of the chart. Verify that the upgrade is successful
   - [ ] Add a downstream cluster with k8s 1.27
   - [ ] Install the prod version of the chart
   - [ ] Upgrade the k8s version of the downstream cluster to 1.28. Verify the chart still works after the upgrade
   - [ ] Perform any additional testing specific to your chart if required
- [ ] If the testing passes then apply the label `[zube]: Done`. If you are blocked with any steps, add a comment with details and apply the label `[zube]: Blocked`

**Comment by markusewalker** [comment]
**QA TEST PLAN**

|#|Scenario|Test Case|
|---|---|---|
|1|Validate `system-upgrade-controller` version in freshly-installed RKE2 v1.28 cluster|Provision downstream RKE2 v1.28 cluster and validate the `system-upgrade-controller` chart version|
|2|Validate `system-upgrade-controller` version in upgraded RKE2 v1.28 cluster|Provision downstream RKE2 v1.27 cluster, upgrade to v1.28 cluster and validate the `system-upgrade-controller` chart version|
|3|Validate `system-upgrade-controller` version in an imported K3s v1.27 cluster|Provision a standalone K3s v1.28 cluster, import it into Rancher, upgrade to v1.28 and validate the `system-upgrade-controller` chart version|
|4|Validate `system-upgrade-controller` version in K3s cluster after upgrading Rancher|Setup Rancher v2.8.2, provision a downstream K3s v1.26 cluster, upgrade Rancher, upgrade to v1.28 and validate the `system-upgrade-controller` chart version|
|5|Validate `system-upgrade-controller` version in an imported RKE2 cluster after upgrading Rancher|Provision a standalone RKE2 v1.26 cluster, setup Rancher v2.8.2, import the cluster into Rancher, upgrade Rancher, upgrade cluster to v1.28 and validate the `system-upgrade-controller` chart version|

**Comment by snasovich** [comment]
Sent back to "Working" for `rancher/rancher` side changes.

**Comment by markusewalker** [comment]
Validated this against `v2.8-head` https://github.com/rancher/rancher/commit/4e51fc9fbe41f4c2900542ed9455a31d913ff51d.

**ENVIRONMENT DETAILS**
- Rancher install: Docker
- Rancher version: `v2.8-head` https://github.com/rancher/rancher/commit/4e51fc9fbe41f4c2900542ed9455a31d913ff51d

**TEST RESULT**
|#|Scenario|Test Case|Result
|---|---|---|---|
|1|Validate `system-upgrade-controller` version in freshly-installed RKE2 v1.28 cluster|Provision downstream RKE2 v1.28 cluster and validate the `system-upgrade-controller` chart version|:white_check_mark:|
|2|Validate `system-upgrade-controller` version in upgraded RKE2 v1.28 cluster|Provision downstream RKE2 v1.27 cluster, upgrade to v1.28 cluster and validate the `system-upgrade-controller` chart version|:white_check_mark:|
|3|Validate `system-upgrade-controller` version in an imported RKE2 v1.27 cluster|Provision a standalone RKE2 v1.28 cluster, import it into Rancher, upgrade to v1.28 and validate the `system-upgrade-controller` chart version|:white_check_mark:|
|4|Validate `system-upgrade-controller` version in K3s cluster after upgrading Rancher|Setup Rancher v2.8.2, provision a downstream K3s v1.26 cluster, upgrade Rancher, upgrade to v1.28 and validate the `system-upgrade-controller` chart version|:white_check_mark:|
|5|Validate `system-upgrade-controller` version in an imported RKE2 cluster after upgrading Rancher|Provision a standalone RKE2 v1.26 cluster, setup Rancher v2.8.2, import the cluster into Rancher, upgrade Rancher, upgrade cluster to v1.28 and validate the `system-upgrade-controller` chart version|:white_check_mark:|

**VALIDATION STEPS**

**Scenario 1**
1. Provisioned a downstream RKE2 `v1.28.6+rke2r1` cluster (1 etcd, 1 cp, 1 worker) as a standard user.
2. Noted that that the chart is at the following version: `system-upgrade-controller:103.0.1+up0.6.0`.

_____

**Scenario 2**
1. Provisioned a downstream RKE2 `v1.27.10+rke2r1` cluster (1 etcd, 1 cp, 1 worker) as a standard user.
2. Noted that that the chart is at the following version: `system-upgrade-controller:103.0.1+up0.6.0`.
3. Upgraded the cluster to v1.28.
4. Validated that the chart version is still the same.

______

**Scenario 3**
1. Provisioned a standalone RKE2 `v1.27.10+rke2r1` cluster.
2. Successfully imported the cluster into Rancher.
3. Upgraded the cluster to `v1.28.6+rke2r1`.
4. Noted that the deployment version is at: `rancher/system-upgrade-controller:v0.13.1`.

_____

**Scenario 4**
1. Provisioned a downstream K3s `v1.26.13+k3s2` cluster (1 etcd, 1 cp, 1 worker) as a standard user.
2. Noted that the chart is at the following version: `system-upgrade-controller:103.0.0+up0.6.0`.
3. Upgraded Rancher to `v2.8-head`.
4. Validated SUC chart is at the same version pre-upgrade.
5. Upgraded cluster to `v1.28.6+k3s2`.
6. Validated that the SUC chart version has been upgraded to `system-upgrade-controller:103.0.1+up0.6.0`.

_____

**Scenario 5**
1. Provisioned a standalone RKE2 `v1.26.13+rke2r1` cluster.
2. Successfully imported the cluster into Rancher.
3. Upgraded Rancher to `v2.8-head`.
4. Upgraded cluster to `v.128.6+rke2r1`.
5. Validated that the deployment version is at: `rancher/system-upgrade-controller:v0.13.1`.
