### ISSUE TITLE
Rancher-compose upgrade and load balancer

### ISSUE THREAD

**Issue by kevinsimper** [rancher/rancher#4374]
I am reading the rancher-compose page about rolling deploys but it does not mention what effect it has to the load balancer that the service changes name from service1 to service2. 

I think the page need an example that includes a load balancer 

http://docs.rancher.com/rancher/rancher-compose/upgrading/

**Comment by deniseschannon** [comment]
It's not obvious but there is a section about inbound links. http://docs.rancher.com/rancher/rancher-compose/upgrading/#updating-inbound-links

By default, all inbound links to the old service will be updated to the new service. 

I will add some additional notes about the inbound links higher up in the documentation, but having a load balancer example will not change anything as you don't need to pass in the load balancer into the docker-compose.yml as the links are automatically updated.

**Comment by kevinsimper** [comment]
@deniseschannon Sounds good adding that, I was really confused about that when I read the documentation.
