### ISSUE TITLE
rancher-cis-benchmark k8s 1.28 chart support (Infracloud)

### ISSUE THREAD

**Issue by gunamata** [rancher/rancher#43741]
**This issue is to implement the chart changes & perform the required testing to support k8s 1.28. The generic process that's applicable for most charts is described here. Please adjust the steps to fit your respective chart wherever required. Perform the steps below:**

- [X] Once you pick up the issue for your chart, apply the label `[zube]: Working` to the issue
Note: If this is an upstream chart (ex: istio) and if the upstream chart doesn't support k8s 1.28 then this exercise is not applicable to you. Just add a comment that the upstream chart doesn't support k8s 1.28 and apply the label `[zube]: Done`. If this is not an upstream chart then proceed to the next step.
- [X] Update kube-version annotation in Chart.yaml to `catalog.cattle.io/kube-version: '>= 1.23.0-0'` or `catalog.cattle.io/kube-version: '>= 1.23.0-0 < 1.29.0-0'`
- [X] Follow the usual process to add a new chart version and file a PR to the `rancher/charts:dev-v2.8` branch. Link the PR to the issue.
- [ ] Perform the usual Developer testing and if everything looks good then merge the PR. After merging the PR,  apply the label `[zube]: To Test`. Tag the respective QA team members.
- [ ] Perform below testing
   - [ ] Spin up Rancher 2.8 with k8s 1.27
   - [ ] Add a downstream cluster with k8s 1.28
   - [ ] Point the Rancher charts repository of the downstream cluster to dev-v2.8 branch
   - [ ] Install the dev version of the chart. Verify that the installation is successful
   - [ ] Perform chart functionality testing (any tests in QA test plans for the chart)
   - [ ] Uninstall the chart. Verify that the uninstallation is successful
   - [ ] Install the prod version of the chart. Verify that the installation is successful
   - [ ] Upgrade to the dev version of the chart. Verify that the upgrade is successful
   - [ ] Add a downstream cluster with k8s 1.27
   - [ ] Install the prod version of the chart
   - [ ] Upgrade the k8s version of the downstream cluster to 1.28. Verify the chart still works after the upgrade
   - [ ] Perform any additional testing specific to your chart if required
- [ ] If the testing passes then apply the label `[zube]: Done`. If you are blocked with any steps, add a comment with details and apply the label `[zube]: Blocked`

**Comment by rishabhmsra** [comment]
Validated on rancher v2.8.3-rc3, using CIS chart 5.1.0-rc7

Fresh install - CIS v1.8-permissive profile scan:
- RKE1 v1.28.7-rancher1-1 node driver and custom - passed
- RKE2 v1.28.7+rke2r1 node driver and custom - observed below failures which are expected [42971](https://github.com/rancher/rancher/issues/42971) 
```
Fail
1.1.1	Ensure that the API server pod specification file permissions are set to 600 or more restrictive (Automated)
Fail
1.1.3	Ensure that the controller manager pod specification file permissions are set to 600 or more restrictive (Automated)
Fail
1.1.5	Ensure that the scheduler pod specification file permissions are set to 600 or more restrictive (Automated)
Fail
1.1.7	Ensure that the etcd pod specification file permissions are set to 600 or more restrictive (Automated)
```
- K3s v1.28.7+k3s1 node driver and custom - passed

Upgrade checks :
- Provisioned v1.27 RKE1, RKE2 and K3s node driver and custom cluster.
- Installed 5.0.0 CIS chart.
- Upgraded clusters to v1.28
- Upgraded chart to 5.1.0-rc7
- Ran permissive profile scan and it passed on all clusters except failures on RKE2 which is expected as mentioned in Fresh install.

Hardened RKE1, RKE2 and K3s - CIS v1.8 permissive as well as hardened profile:
- RKE1 v1.28 - scan failed with below expected failure - [42971](https://github.com/rancher/rancher/issues/42971) 
```
Mixed
4.1.7	Ensure that the certificate authorities file permissions are set to 600 or more restrictive (Automated)
```
- RKE2 v1.28 - passed.
- K3s v.128 - passed.

Imported clusters:
- Provisioned RKE1 v1.28.7-rancher1-1 cluster and ran permissive v1.8 profile scan - passed
