### ISSUE TITLE
[SURE-6576] eks-operator k8s 1.28 chart support

### ISSUE THREAD

**Issue by gunamata** [rancher/rancher#43746]
**This issue is to implement the chart changes & perform the required testing to support k8s 1.28. The generic process that's applicable for most charts is described here. Please adjust the steps to fit your respective chart wherever required. Perform the steps below:**

- [ ] Once you pick up the issue for your chart, apply the label `[zube]: Working` to the issue
Note: If this is an upstream chart (ex: istio) and if the upstream chart doesn't support k8s 1.28 then this exercise is not applicable to you. Just add a comment that the upstream chart doesn't support k8s 1.28 and apply the label `[zube]: Done`. If this is not an upstream chart then proceed to the next step.
- [x] Update kube-version annotation in Chart.yaml to `catalog.cattle.io/kube-version: '>= 1.23.0-0'` or `catalog.cattle.io/kube-version: '>= 1.23.0-0 < 1.29.0-0'`
- [x] Follow the usual process to add a new chart version and file a PR to the `rancher/charts:dev-v2.8` branch. Link the PR to the issue.
- [ ] Perform the usual Developer testing and if everything looks good then merge the PR. After merging the PR,  apply the label `[zube]: To Test`. Tag the respective QA team members.
- [ ] Perform below testing
   - [ ] Spin up Rancher 2.8 with k8s 1.27
   - [ ] Add a downstream cluster with k8s 1.28
   - [ ] Point the Rancher charts repository of the downstream cluster to dev-v2.8 branch
   - [ ] Install the dev version of the chart. Verify that the installation is successful
   - [ ] Perform chart functionality testing (any tests in QA test plans for the chart)
   - [ ] Uninstall the chart. Verify that the uninstallation is successful
   - [ ] Install the prod version of the chart. Verify that the installation is successful
   - [ ] Upgrade to the dev version of the chart. Verify that the upgrade is successful
   - [ ] Add a downstream cluster with k8s 1.27
   - [ ] Install the prod version of the chart
   - [ ] Upgrade the k8s version of the downstream cluster to 1.28. Verify the chart still works after the upgrade
   - [ ] Perform any additional testing specific to your chart if required
- [ ] If the testing passes then apply the label `[zube]: Done`. If you are blocked with any steps, add a comment with details and apply the label `[zube]: Blocked`

**Comment by mjura** [comment]
## PR's:

- [ ] https://github.com/rancher/charts/pull/3265

**Comment by valaparthvi** [comment]
Rancher v2.8-head on K3s v1.27.9+k3s1 does not show EKS 1.28 in the UI. Do I need to wait on something? Testing this via API works as expected.
I noticed Michal added https://github.com/rancher/ui/pull/5094 that hardcodes 1.28 to the UI list, but that does not seem to have worked.

**Comment by valaparthvi** [comment]
> Rancher v2.8-head on K3s v1.27.9+k3s1 does not show EKS 1.28 in the UI. Do I need to wait on something? Testing this via API works as expected. I noticed Michal added [rancher/ui#5094](https://github.com/rancher/ui/pull/5094) that hardcodes 1.28 to the UI list, but that does not seem to have worked.

I guess this will be available once https://github.com/rancher/eks-operator/pull/332 goes in.

**Comment by valaparthvi** [comment]
Blocked: https://github.com/rancher/eks-operator/pull/332

**Comment by valaparthvi** [comment]
1.28 is not available in the UI yet.
cc: @mjura 

Steps to reproduce:
1. Spin up a fresh rancher v2.8-head.
2. Provision an EKS cluster v1.28; it is not available in the UI list.
OR
1. For an existing rancher 2.8.2 with provisioned/imported EKS 1.27; upgrade rancher to v2.8-head/
2. Upgrade the EKS cluster/s to 1.28, it is not available in the UI list.

**Comment by mjura** [comment]
@valaparthvi it is probably because Rancher is not including this updated file
https://github.com/rancher/ui/blob/master/lib/shared/addon/utils/amazon.js#L704C1-L704C26

**Comment by gaktive** [comment]
Please file a ticket in `rancher/dashboard` to get a UI update for this version.

**Comment by gaktive** [comment]
As linked here, I've filed provisional tickets in our backlog to address the UI changes:
- 2.8.next1: https://github.com/rancher/dashboard/issues/10505
- 2.9.0: https://github.com/rancher/dashboard/issues/10504

Feel free to update those accordingly with more info. I expanded that request to indicate if there were other cloud providers that also need references updated to include 1.28.

**Comment by valaparthvi** [comment]
Tested on 2.8.3-rc2, EKS 1.28 works as expected.
