### ISSUE TITLE
[SURE-6576] aks-operator k8s 1.28 chart support

### ISSUE THREAD

**Issue by gunamata** [rancher/rancher#43745]
**This issue is to implement the chart changes & perform the required testing to support k8s 1.28. The generic process that's applicable for most charts is described here. Please adjust the steps to fit your respective chart wherever required. Perform the steps below:**

- [ ] Once you pick up the issue for your chart, apply the label `[zube]: Working` to the issue
Note: If this is an upstream chart (ex: istio) and if the upstream chart doesn't support k8s 1.28 then this exercise is not applicable to you. Just add a comment that the upstream chart doesn't support k8s 1.28 and apply the label `[zube]: Done`. If this is not an upstream chart then proceed to the next step.
- [x] Update kube-version annotation in Chart.yaml to `catalog.cattle.io/kube-version: '>= 1.23.0-0'` or `catalog.cattle.io/kube-version: '>= 1.23.0-0 < 1.29.0-0'`
- [x] Follow the usual process to add a new chart version and file a PR to the `rancher/charts:dev-v2.8` branch. Link the PR to the issue.
- [ ] Perform the usual Developer testing and if everything looks good then merge the PR. After merging the PR,  apply the label `[zube]: To Test`. Tag the respective QA team members.
- [ ] Perform below testing
   - [ ] Spin up Rancher 2.8 with k8s 1.27
   - [ ] Add a downstream cluster with k8s 1.28
   - [ ] Point the Rancher charts repository of the downstream cluster to dev-v2.8 branch
   - [ ] Install the dev version of the chart. Verify that the installation is successful
   - [ ] Perform chart functionality testing (any tests in QA test plans for the chart)
   - [ ] Uninstall the chart. Verify that the uninstallation is successful
   - [ ] Install the prod version of the chart. Verify that the installation is successful
   - [ ] Upgrade to the dev version of the chart. Verify that the upgrade is successful
   - [ ] Add a downstream cluster with k8s 1.27
   - [ ] Install the prod version of the chart
   - [ ] Upgrade the k8s version of the downstream cluster to 1.28. Verify the chart still works after the upgrade
   - [ ] Perform any additional testing specific to your chart if required
- [ ] If the testing passes then apply the label `[zube]: Done`. If you are blocked with any steps, add a comment with details and apply the label `[zube]: Blocked`

**PR's**
- [x] https://github.com/rancher/charts/pull/3342/

**Comment by mjura** [comment]
https://github.com/rancher/charts/pull/3264

**Comment by valaparthvi** [comment]
Blocked on: https://github.com/rancher/aks-operator/pull/368

**Comment by valaparthvi** [comment]
Tested on v2.8-head and works as expected.
Steps to reproduce:
1. Spin Rancher v2.8.2 and provision AKS with the latest available version i.e 1.27, ensure 1.28 is not available in the UI list. Also import a similar cluster.
2. Note the aks-operator chart version. 103.0.0+up1.2.0
3. Upgrade rancher to v2.8-head.
4. Check 1.28 is now available in the UI. Upgrade both provisioned and imported clusters to 1.28.
5. Note the aks-operator chart version. 103.0.0+up1.2.0-rc3 (or something like that).
6. Downgrade the chart.
7. Make a change to the cluster and validate it succeeds.
8. Uninstall the chart and wait for it to re-install to the latest (-rc) version.
9. Make a change to the cluster and validate it succeeds.
