### ISSUE TITLE
Fleet k8s 1.28 chart support

### ISSUE THREAD

**Issue by gunamata** [rancher/rancher#43744]
**This issue is to implement the chart changes & perform the required testing to support k8s 1.28. The generic process that's applicable for most charts is described here. Please adjust the steps to fit your respective chart wherever required. Perform the steps below:**

- [x] Once you pick up the issue for your chart, apply the label `[zube]: Working` to the issue
Note: If this is an upstream chart (ex: istio) and if the upstream chart doesn't support k8s 1.28 then this exercise is not applicable to you. Just add a comment that the upstream chart doesn't support k8s 1.28 and apply the label `[zube]: Done`. If this is not an upstream chart then proceed to the next step.
- [x] Update kube-version annotation in Chart.yaml to `catalog.cattle.io/kube-version: '>= 1.23.0-0'` or `catalog.cattle.io/kube-version: '>= 1.23.0-0 < 1.29.0-0'`
- [x] Follow the usual process to add a new chart version and file a PR to the `rancher/charts:dev-v2.8` branch. Link the PR to the issue.
- [x] Perform the usual Developer testing and if everything looks good then merge the PR. After merging the PR,  apply the label `[zube]: To Test`. Tag the respective QA team members.
- [ ] Perform below testing
   - [ ] Spin up Rancher 2.8 with k8s 1.27
   - [ ] Add a downstream cluster with k8s 1.28
   - [ ] Point the Rancher charts repository of the downstream cluster to dev-v2.8 branch
   - [ ] Install the dev version of the chart. Verify that the installation is successful
   - [ ] Perform chart functionality testing (any tests in QA test plans for the chart)
   - [ ] Uninstall the chart. Verify that the uninstallation is successful
   - [ ] Install the prod version of the chart. Verify that the installation is successful
   - [ ] Upgrade to the dev version of the chart. Verify that the upgrade is successful
   - [ ] Add a downstream cluster with k8s 1.27
   - [ ] Install the prod version of the chart
   - [ ] Upgrade the k8s version of the downstream cluster to 1.28. Verify the chart still works after the upgrade
   - [ ] Perform any additional testing specific to your chart if required
- [ ] If the testing passes then apply the label `[zube]: Done`. If you are blocked with any steps, add a comment with details and apply the label `[zube]: Blocked`

**Comment by kkaempf** [comment]
This can be tested against 2.8-head, dropping "waiting for Rancher rc" label.

**Comment by thehejik** [comment]
### Test report
Works as expected. 

Fleet App Chart in version `103.1.1+up0.9.1-rc.5` is fully compatible with k8s 1.28 - There is no sign of any Error nor k8s Deprecation visible in Helm Jobs logs when installing or upgrading the Fleet App from older k8s versions or from previous stable Rancher 2.8.2 version.

#### Environment
Validated on `rancher:v2.8.3-rc2` from rancher-latest helm repo with target ` v1.28.6+k3s2` on local and downstream cluster. Initial version (when requested) was `v1.27.10+k3s2`.

Fleet App chart under test `103.1.1+up0.9.1-rc.5` using following images:
```
rancher/fleet:v0.9.1-rc.5
rancher/gitjob:v0.9.3
rancher/fleet-agent:v0.9.1-rc.5
```

#### Testing

- [ ] Spin up Rancher 2.8 with k8s 1.27
- [ ] Add a downstream cluster with k8s 1.28
- [ ] Point the Rancher charts repository of the downstream cluster to dev-v2.8 branch 
Note: `v2.8.3-rc2` is using `dev-2.8` chart repository by default
- [ ] Install the dev version of the chart. Verify that the installation is successful - Fleet App `103.1.1+up0.9.1-rc.5`
- [ ] Perform chart functionality testing (any tests in QA test plans for the chart)
Note: Via CD/fleet deployed a workload from Private Github repository (local) and from Private BitBucker repository (downstream) - all good
- [ ] Uninstall the chart. Verify that the uninstallation is successful
Note: Not fully applicable here - the uninstallation is successful but the same version is automatically reinstalled after a while (fleet it manged by rancher). Fleet workload survived without restarting its pods.

~- [ ] Install the prod version of the chart. Verify that the installation is successful~ Not applicable for Fleet

~- [ ] Upgrade to the dev version of the chart. Verify that the upgrade is successful~ Not applicable for Fleet

- [ ] Add a downstream cluster with k8s 1.27
Note: fleet-agent deployed successfully

~- [ ] Install the prod version of the chart~ Not applicable for Fleet
- [ ] Upgrade the k8s version of the downstream cluster to 1.28. Verify the chart still works after the upgrade
Note: Upgrade over Rancher WebUI from `v1.27.10+k3s2` -> `v1.28.6+k3s2` performed on both clusters - no fleet resources changed, workload still running in both - upgrade was successful.

Perform any additional testing specific to your chart if required:
- [ ] Spinned up Rancher 2.8.3-rc2 on local v1.28.6+k3s directly - deployed and sample app - ok
- [ ] Perform upgrade from stable `rancher:2.8.2` with `v1.26.10+k3s1` with downstream cluster added and verify status
Note: Added sample fleet workload on initial version -> upgraded to `rancher:2.8.3-rc2` -> both clusters updated fleet App resources automatically -> both clusters upgraded to `v1.28.6+k3s2` -> Fleet and its workload resources ok
