### ISSUE TITLE
Add support for custom labels on local cluster

### ISSUE THREAD

**Issue by tonybaltazar** [rancher/rancher#43767]
**Is your feature request related to a problem? Please describe.**
Rancher is deployed to the cluster local, and is set with the default `provider.cattle.io` label. Since we rely heavily on Fleet to provisioned all of our downstream clusters as well as our Rancher cluster (local). At the moment, I have to manually update `Cluster` resource to include any custom labels. 
![Screenshot 2023-12-11 at 1 21 30 PM](https://github.com/rancher/rancher/assets/104655758/8cab210f-8f10-4daf-b33b-73b5158af3ff)

**Describe the solution you'd like**
It would be awesome if these custom labels can be set at the helm chart values deployment.

**Describe alternatives you've considered**
N/A

**Additional context**
Having custom labels on local clusters is very helpful as we're able to just have one Fleet GitOps Repository and rely on cluster label selectors when deploying custom configs to all downstream and local clusters.

**Comment by ivko-pivko** [comment]
If someone needs the same, I have managed to add labels using local-exec provisioner to configure them over the Rancher API:

resource "null_resource" "add_labels_to_local_cluster" {
  provisioner "local-exec" {
      command =  <<EOT
       curl -k --insecure -u '${rancher2_token.auth.access_key}:${rancher2_token.auth.secret_key}'  \
        -X PUT \
        -H 'Content-Type: application/json' \
        -d '{
            "name": "${local.rancher_local}",
            "labels": {
              "rancher-name" : "${local.rancher_short_hostname}",
              "owner": "xxx",
              "provider.cattle.io" : "eks",
              "accountID": "${local.account_id}"
           }
           }' \
        https://${var.rancher_hostname}/v3/clusters/${data.rancher2_cluster.local-cluster.id} 
     
    EOT
  }
  triggers = {
    #Forces execution of API call on each "terraform apply", otherwise it's only ran the first time
    always_run = timestamp()
  }
  depends_on = [data.rancher2_cluster.local-cluster]
}


data "rancher2_cluster" "local-cluster" {
  provider = rancher2.admin
  name = "local"
}

resource "rancher2_token" "auth" {
  provider = rancher2.admin
  ttl = 1200
  depends_on = [resource.rancher2_bootstrap.admin]
}
