### ISSUE TITLE
Apache Kafka and zookeeper from the catalog

### ISSUE THREAD

**Issue by eguswes** [rancher/rancher#4376]
*Describe your issue here*

It seems to be an issue here. The kafka service is frequently interrupted.

This is what I can see in the logs from zookeeper.

4/12/2016 12:43:20 PMTue Apr 12 10:43:20 UTC 2016 - checking rancher network...
4/12/2016 12:43:31 PMtail: can't open '/opt/zk/logs/zookeeper.out': No such file or directory
4/12/2016 12:43:31 PMTue Apr 12 10:43:31 UTC 2016 - [ Static zk configuration... ]
4/12/2016 12:43:31 PMTue Apr 12 10:43:31 UTC 2016 - [ Getting zk configuration... ]
4/12/2016 12:43:31 PM2016-04-12T10:43:31Z 9d8e625ad063 /usr/bin/confd[25]: INFO Backend set to rancher
4/12/2016 12:43:31 PM2016-04-12T10:43:31Z 9d8e625ad063 /usr/bin/confd[25]: INFO Starting confd
4/12/2016 12:43:31 PM2016-04-12T10:43:31Z 9d8e625ad063 /usr/bin/confd[25]: INFO Backend nodes set to 
4/12/2016 12:43:31 PM2016-04-12T10:43:31Z 9d8e625ad063 /usr/bin/confd[25]: INFO Using Rancher Metadata URL: http://rancher-metadata
4/12/2016 12:43:31 PM2016-04-12T10:43:31Z 9d8e625ad063 /usr/bin/confd[25]: INFO Target config /opt/zk/data/myid out of sync
4/12/2016 12:43:31 PM2016-04-12T10:43:31Z 9d8e625ad063 /usr/bin/confd[25]: INFO Target config /opt/zk/data/myid has been updated
4/12/2016 12:43:31 PM2016-04-12T10:43:31Z 9d8e625ad063 /usr/bin/confd[25]: INFO Target config /opt/zk/conf/zoo.cfg out of sync
4/12/2016 12:43:35 PMtail: /opt/zk/logs/zookeeper.out has appeared; following end of new file
4/12/2016 12:43:35 PM2016-04-12 10:43:35,333 [myid:] - INFO  [main:QuorumPeerConfig@103] - Reading configuration from: /opt/zk/bin/../conf/zoo.cfg
4/12/2016 12:43:35 PM2016-04-12 10:43:35,340 [myid:] - INFO  [main:QuorumPeerConfig@340] - Defaulting to majority quorums
4/12/2016 12:43:35 PM2016-04-12 10:43:35,343 [myid:3] - INFO  [main:DatadirCleanupManager@78] - autopurge.snapRetainCount set to 3
4/12/2016 12:43:35 PM2016-04-12 10:43:35,343 [myid:3] - INFO  [main:DatadirCleanupManager@79] - autopurge.purgeInterval set to 1
4/12/2016 12:43:35 PM2016-04-12 10:43:35,347 [myid:3] - INFO  [PurgeTask:DatadirCleanupManager$PurgeTask@138] - Purge task started.
4/12/2016 12:43:35 PM2016-04-12 10:43:35,356 [myid:3] - INFO  [main:QuorumPeerMain@127] - Starting quorum peer
4/12/2016 12:43:35 PM2016-04-12 10:43:35,362 [myid:3] - INFO  [PurgeTask:DatadirCleanupManager$PurgeTask@144] - Purge task completed.
4/12/2016 12:43:35 PM2016-04-12 10:43:35,371 [myid:3] - INFO  [main:NIOServerCnxnFactory@94] - binding to port 0.0.0.0/0.0.0.0:2181
4/12/2016 12:43:35 PM2016-04-12 10:43:35,382 [myid:3] - INFO  [main:QuorumPeer@959] - tickTime set to 2000
4/12/2016 12:43:35 PM2016-04-12 10:43:35,382 [myid:3] - INFO  [main:QuorumPeer@979] - minSessionTimeout set to -1
4/12/2016 12:43:35 PM2016-04-12 10:43:35,382 [myid:3] - INFO  [main:QuorumPeer@990] - maxSessionTimeout set to -1
4/12/2016 12:43:35 PM2016-04-12 10:43:35,382 [myid:3] - INFO  [main:QuorumPeer@1005] - initLimit set to 10
4/12/2016 12:43:35 PM2016-04-12 10:43:35,395 [myid:3] - INFO  [main:QuorumPeer@473] - currentEpoch not found! Creating with a reasonable default of 0. This should only happen when you are upgrading your installation
4/12/2016 12:43:35 PM2016-04-12 10:43:35,398 [myid:3] - INFO  [main:QuorumPeer@488] - acceptedEpoch not found! Creating with a reasonable default of 0. This should only happen when you are upgrading your installation
4/12/2016 12:43:35 PM2016-04-12 10:43:35,405 [myid:3] - INFO  [Thread-2:QuorumCnxManager$Listener@504] - My election bind port: /10.42.67.126:3888
4/12/2016 12:43:35 PM2016-04-12 10:43:35,413 [myid:3] - INFO  [QuorumPeer[myid=3]/0:0:0:0:0:0:0:0:2181:QuorumPeer@714] - LOOKING
4/12/2016 12:43:35 PM2016-04-12 10:43:35,419 [myid:3] - INFO  [QuorumPeer[myid=3]/0:0:0:0:0:0:0:0:2181:FastLeaderElection@815] - New election. My id =  3, proposed zxid=0x0
4/12/2016 12:43:35 PM2016-04-12 10:43:35,435 [myid:3] - INFO  [WorkerReceiver[myid=3]:FastLeaderElection@597] - Notification: 1 (message format version), 2 (n.leader), 0x0 (n.zxid), 0x1 (n.round), LOOKING (n.state), 1 (n.sid), 0x0 (n.peerEpoch) LOOKING (my state)
4/12/2016 12:43:35 PM2016-04-12 10:43:35,436 [myid:3] - INFO  [WorkerReceiver[myid=3]:FastLeaderElection@597] - Notification: 1 (message format version), 2 (n.leader), 0x0 (n.zxid), 0x1 (n.round), FOLLOWING (n.state), 1 (n.sid), 0x0 (n.peerEpoch) LOOKING (my state)
4/12/2016 12:43:35 PM2016-04-12 10:43:35,436 [myid:3] - INFO  [WorkerReceiver[myid=3]:FastLeaderElection@597] - Notification: 1 (message format version), 3 (n.leader), 0x0 (n.zxid), 0x1 (n.round), LOOKING (n.state), 3 (n.sid), 0x0 (n.peerEpoch) LOOKING (my state)
4/12/2016 12:43:35 PM2016-04-12 10:43:35,437 [myid:3] - INFO  [WorkerReceiver[myid=3]:FastLeaderElection@597] - Notification: 1 (message format version), 2 (n.leader), 0x0 (n.zxid), 0x1 (n.round), LOOKING (n.state), 2 (n.sid), 0x0 (n.peerEpoch) LOOKING (my state)
4/12/2016 12:43:35 PM2016-04-12 10:43:35,438 [myid:3] - INFO  [WorkerReceiver[myid=3]:FastLeaderElection@597] - Notification: 1 (message format version), 2 (n.leader), 0x0 (n.zxid), 0x1 (n.round), LEADING (n.state), 2 (n.sid), 0x0 (n.peerEpoch) LOOKING (my state)
4/12/2016 12:43:35 PM2016-04-12 10:43:35,439 [myid:3] - INFO  [QuorumPeer[myid=3]/0:0:0:0:0:0:0:0:2181:QuorumPeer@784] - FOLLOWING
4/12/2016 12:43:35 PM2016-04-12 10:43:35,443 [myid:3] - INFO  [QuorumPeer[myid=3]/0:0:0:0:0:0:0:0:2181:Learner@86] - TCP NoDelay set to: true
4/12/2016 12:43:35 PM2016-04-12 10:43:35,448 [myid:3] - INFO  [QuorumPeer[myid=3]/0:0:0:0:0:0:0:0:2181:Environment@100] - Server environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT
4/12/2016 12:43:35 PM2016-04-12 10:43:35,448 [myid:3] - INFO  [QuorumPeer[myid=3]/0:0:0:0:0:0:0:0:2181:Environment@100] - Server environment:host.name=9d8e625ad063
4/12/2016 12:43:35 PM2016-04-12 10:43:35,448 [myid:3] - INFO  [QuorumPeer[myid=3]/0:0:0:0:0:0:0:0:2181:Environment@100] - Server environment:java.version=1.8.0_66
4/12/2016 12:43:35 PM2016-04-12 10:43:35,448 [myid:3] - INFO  [QuorumPeer[myid=3]/0:0:0:0:0:0:0:0:2181:Environment@100] - Server environment:java.vendor=Oracle Corporation
4/12/2016 12:43:35 PM2016-04-12 10:43:35,448 [myid:3] - INFO  [QuorumPeer[myid=3]/0:0:0:0:0:0:0:0:2181:Environment@100] - Server environment:java.home=/opt/jre1.8.0_66
4/12/2016 12:43:35 PM2016-04-12 10:43:35,448 [myid:3] - INFO  [QuorumPeer[myid=3]/0:0:0:0:0:0:0:0:2181:Environment@100] - Server environment:java.class.path=/opt/zk/bin/../build/classes:/opt/zk/bin/../build/lib/*.jar:/opt/zk/bin/../lib/slf4j-log4j12-1.6.1.jar:/opt/zk/bin/../lib/slf4j-api-1.6.1.jar:/opt/zk/bin/../lib/netty-3.7.0.Final.jar:/opt/zk/bin/../lib/log4j-1.2.16.jar:/opt/zk/bin/../lib/jline-0.9.94.jar:/opt/zk/bin/../zookeeper-3.4.6.jar:/opt/zk/bin/../src/java/lib/*.jar:/opt/zk/bin/../conf:
4/12/2016 12:43:35 PM2016-04-12 10:43:35,448 [myid:3] - INFO  [QuorumPeer[myid=3]/0:0:0:0:0:0:0:0:2181:Environment@100] - Server environment:java.library.path=/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
4/12/2016 12:43:35 PM2016-04-12 10:43:35,448 [myid:3] - INFO  [QuorumPeer[myid=3]/0:0:0:0:0:0:0:0:2181:Environment@100] - Server environment:java.io.tmpdir=/tmp
4/12/2016 12:43:35 PM2016-04-12 10:43:35,449 [myid:3] - INFO  [QuorumPeer[myid=3]/0:0:0:0:0:0:0:0:2181:Environment@100] - Server environment:java.compiler=<NA>
4/12/2016 12:43:35 PM2016-04-12 10:43:35,449 [myid:3] - INFO  [QuorumPeer[myid=3]/0:0:0:0:0:0:0:0:2181:Environment@100] - Server environment:os.name=Linux
4/12/2016 12:43:35 PM2016-04-12 10:43:35,449 [myid:3] - INFO  [QuorumPeer[myid=3]/0:0:0:0:0:0:0:0:2181:Environment@100] - Server environment:os.arch=amd64
4/12/2016 12:43:35 PM2016-04-12 10:43:35,449 [myid:3] - INFO  [QuorumPeer[myid=3]/0:0:0:0:0:0:0:0:2181:Environment@100] - Server environment:os.version=3.10.0-327.4.4.el7.x86_64
4/12/2016 12:43:35 PM2016-04-12 10:43:35,449 [myid:3] - INFO  [QuorumPeer[myid=3]/0:0:0:0:0:0:0:0:2181:Environment@100] - Server environment:user.name=root
4/12/2016 12:43:35 PM2016-04-12 10:43:35,449 [myid:3] - INFO  [QuorumPeer[myid=3]/0:0:0:0:0:0:0:0:2181:Environment@100] - Server environment:user.home=/root
4/12/2016 12:43:35 PM2016-04-12 10:43:35,449 [myid:3] - INFO  [QuorumPeer[myid=3]/0:0:0:0:0:0:0:0:2181:Environment@100] - Server environment:user.dir=/opt/zk
4/12/2016 12:43:35 PM2016-04-12 10:43:35,450 [myid:3] - INFO  [QuorumPeer[myid=3]/0:0:0:0:0:0:0:0:2181:ZooKeeperServer@162] - Created server with tickTime 2000 minSessionTimeout 4000 maxSessionTimeout 40000 datadir /opt/zk/data/version-2 snapdir /opt/zk/data/version-2
4/12/2016 12:43:35 PM2016-04-12 10:43:35,451 [myid:3] - INFO  [QuorumPeer[myid=3]/0:0:0:0:0:0:0:0:2181:Follower@63] - FOLLOWING - LEADER ELECTION TOOK - 32
4/12/2016 12:43:35 PM2016-04-12 10:43:35,472 [myid:3] - INFO  [QuorumPeer[myid=3]/0:0:0:0:0:0:0:0:2181:Learner@323] - Getting a diff from the leader 0x0
4/12/2016 12:43:35 PM2016-04-12 10:43:35,474 [myid:3] - INFO  [QuorumPeer[myid=3]/0:0:0:0:0:0:0:0:2181:FileTxnSnapLog@240] - Snapshotting: 0x0 to /opt/zk/data/version-2/snapshot.0
4/12/2016 12:43:35 PM2016-04-12T10:43:35Z 9d8e625ad063 /usr/bin/confd[25]: INFO Target config /opt/zk/conf/zoo.cfg has been updated
4/12/2016 12:43:35 PMTue Apr 12 10:43:35 UTC 2016 - [ Starting monit... ]
4/12/2016 12:43:36 PM New Monit id: 92a28379f6707d7558c4653f57a9b40d
4/12/2016 12:43:36 PM Stored in '/root/.monit.id'
4/12/2016 12:43:36 PMStarting Monit 5.15 daemon with http interface at [*]:2812
4/12/2016 12:44:36 PM2016-04-12 10:44:36,094 [myid:3] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxnFactory@197] - Accepted socket connection from /0:0:0:0:0:0:0:1:44967
4/12/2016 12:44:36 PM2016-04-12 10:44:36,168 [myid:3] - WARN  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@357] - caught end of stream exception
4/12/2016 12:44:36 PMEndOfStreamException: Unable to read additional data from client sessionid 0x0, likely client has closed socket
4/12/2016 12:44:36 PM	at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:228)
4/12/2016 12:44:36 PM	at org.apache.zookeeper.server.NIOServerCnxnFactory.run(NIOServerCnxnFactory.java:208)
4/12/2016 12:44:36 PM	at java.lang.Thread.run(Thread.java:745)
4/12/2016 12:44:36 PM2016-04-12 10:44:36,171 [myid:3] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@1007] - Closed socket connection for client /0:0:0:0:0:0:0:1:44967 (no session established for client)
4/12/2016 12:45:36 PM2016-04-12 10:45:36,096 [myid:3] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxnFactory@197] - Accepted socket connection from /0:0:0:0:0:0:0:1:45107
4/12/2016 12:45:36 PM2016-04-12 10:45:36,096 [myid:3] - WARN  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@357] - caught end of stream exception
4/12/2016 12:45:36 PMEndOfStreamException: Unable to read additional data from client sessionid 0x0, likely client has closed socket
4/12/2016 12:45:36 PM	at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:228)
4/12/2016 12:45:36 PM	at org.apache.zookeeper.server.NIOServerCnxnFactory.run(NIOServerCnxnFactory.java:208)
4/12/2016 12:45:36 PM	at java.lang.Thread.run(Thread.java:745)
4/12/2016 12:45:36 PM2016-04-12 10:45:36,097 [myid:3] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@1007] - Closed socket connection for client /0:0:0:0:0:0:0:1:45107 (no session established for client)
4/12/2016 12:46:36 PM2016-04-12 10:46:36,102 [myid:3] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxnFactory@197] - Accepted socket connection from /0:0:0:0:0:0:0:1:45241
4/12/2016 12:46:36 PM2016-04-12 10:46:36,103 [myid:3] - WARN  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@357] - caught end of stream exception
4/12/2016 12:46:36 PMEndOfStreamException: Unable to read additional data from client sessionid 0x0, likely client has closed socket
4/12/2016 12:46:36 PM	at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:228)
4/12/2016 12:46:36 PM	at org.apache.zookeeper.server.NIOServerCnxnFactory.run(NIOServerCnxnFactory.java:208)
4/12/2016 12:46:36 PM	at java.lang.Thread.run(Thread.java:745)
4/12/2016 12:46:36 PM2016-04-12 10:46:36,103 [myid:3] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@1007] - Closed socket connection for client /0:0:0:0:0:0:0:1:45241 (no session established for client)
4/12/2016 12:47:36 PM2016-04-12 10:47:36,111 [myid:3] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxnFactory@197] - Accepted socket connection from /0:0:0:0:0:0:0:1:45379
4/12/2016 12:47:36 PM2016-04-12 10:47:36,112 [myid:3] - WARN  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@357] - caught end of stream exception
4/12/2016 12:47:36 PMEndOfStreamException: Unable to read additional data from client sessionid 0x0, likely client has closed socket
4/12/2016 12:47:36 PM	at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:228)
4/12/2016 12:47:36 PM	at org.apache.zookeeper.server.NIOServerCnxnFactory.run(NIOServerCnxnFactory.java:208)
4/12/2016 12:47:36 PM	at java.lang.Thread.run(Thread.java:745)
4/12/2016 12:47:36 PM2016-04-12 10:47:36,112 [myid:3] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@1007] - Closed socket connection for client /0:0:0:0:0:0:0:1:45379 (no session established for client)

Zookeeper
3.4.6-RANCHER

Kafka
0.9.0-Rancher

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.0.0` Cattle: `v0.159.2` UI: `v0.100.3` |
|Access|`Disabled`|
|Route|`authenticated.project.help`|

**Comment by deniseschannon** [comment]
Could you look open this issue in the https://github.com/rancher/community-catalog repository? We won't provide direct support to the non-certified templates, but you can submit an issue there and mention the person who created the template to see if they might help out.

**Comment by deniseschannon** [comment]
@eguswes As I mentioned, it's best if you open your issue in the other repo. Thanks!
