### ISSUE TITLE
[BUG] Backup to S3-compatible object store is not working

### ISSUE THREAD

**Issue by bitfisher** [rancher/rancher#43761]
**Rancher Server Setup**
- Rancher version: `v2.7.9`
- Installation option (Docker install/Helm Chart):
   `Helm Chart`, `RKE1 v1.4.11`, `k8s v1.26.9`

**Information about the Cluster**
- Kubernetes version: `v1.26.9`
- Rancher Backups: `v102.0.2+up3.1.2` configured with S3-compatible object store

**Describe the bug**
One-Time Backup fails with
`failed to check if s3 bucket [rancher-backup] exists, error: Access Denied.`

**To Reproduce**
Install Rancher Backups application and configure with S3-compatible object store (minio in my case).
Create One-Time-Backup (using Rancher UI).

**Result**
`failed to check if s3 bucket [rancher-backup] exists, error: Access Denied.`

**Expected Result**
backup successfully stored in configured S3 object store

**Additional context**
I can confirm that used S3-compatible object store (minio) is working as expected.
Tested with s3cmd/s5cmd using same bucket, folder and credentials.

Relevant log output of `rancher-backup-xx` pod:
```
INFO[2023/12/11 15:57:49] invoking set s3 service client                insecure-tls-skip-verify=false s3-accessKey=XXX s3-bucketName=rancher-backup s3-endpoint=minio-fqdn s3-endpoint-ca= s3-folder=rancher s3-region=
ERRO[2023/12/11 15:57:51] error syncing 'test': handler backups: failed to check if s3 bucket [rancher-backup] exists, error: Access Denied., requeuing 
```
---

Maybe related to https://github.com/rancher/rke/issues/3452

**Comment by bpedersen2** [comment]
backup to minio is working fine here, but I need to specifiy the same region as set in minio as well

**Comment by bitfisher** [comment]
Sorry, seems like our admin messed things up here :(

**Comment by AnilCdot** [comment]
what was the solution here? Did you have to install an s3 service such as s3gw?

**Comment by bitfisher** [comment]
we had to adjust our traefik proxy config. some headers got filtered out, which caused the problem.
