### ISSUE TITLE
[Backport v2.7] [BUG] Unnecessary node restart during vSphere provisioning on RHEL 8.8

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#43778]
Backport https://github.com/rancher/rancher/issues/43119 

Please check the original issue for details.

**Comment by jiaqiluo** [comment]
The fix can be validated in the latest Rancher v2.7-head.
For more information about validating the fix, please check [this comment](https://github.com/rancher/rancher/issues/43119#issuecomment-1858320251)

**Comment by susesgartner** [comment]
Ticket #43778 - Test Results - ✅ Pass
---
 
| Scenario | Test Case | Result |
|---|---|---|
| 1. | Validate node doesn't reboot | PASS |
| 2. | Scale Node driver cluster | PASS |
 
---
Validated with Docker on Rancher `v2.7-head`:
---

Scenario 1: Validate node doesn't reboot
---
1. Create an Rhel 8.8 image with NM disabled and network service enabled
2. Create a downstream rancher cluster using the image in step 1
3. Validate that no reboot occurs during provisioning.
 
 
Results:
No reboot occurred on the downstream nodes and the cluster came up successfully.

Scenario 2: Scale Node driver cluster
---
1. Create an Rhel 8.8 image with NM disabled and network service enabled
2. Create a downstream rancher cluster using the image in step 1
3. Scale the cluster up.
4. Validate that no reboots are observed and the cluster remains in a stable state.
 
 
Results:
No reboot occurred on the downstream nodes and the cluster scaled successfully.
