### ISSUE TITLE
Machine config now has UUID as download name instead of machine name

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4378]
Version - v1.0.1-rc1

Steps to Reproduce: 
1.  Click on Machine Config for one of your hosts

Results: Notice download on screen says <machinename>.tar.gz.  But when you open the gz file it changes to the UUID of the machine.
![image](https://cloud.githubusercontent.com/assets/11514927/14474667/168ecc0c-00b3-11e6-9926-f3f4f1a009c8.png)

Expected: Should probably still be machine name so it's easy to find.

**Comment by wlan0** [comment]
I spoke to @cjellick and he said that this might cause problems with the HA logic that will extract the config on a host if gms happened to move to a new host. i'm removing the resolved label for now.

**Comment by wlan0** [comment]
Moving this to unscheduled because this is not important/necessary, but its a lot of effort
