### ISSUE TITLE
[BUG] Deleting namespaces from project as standard user doesn't remove the items from Rancher Dashboard

### ISSUE THREAD

**Issue by aalves08** [rancher/rancher#43799]
Blocker for https://github.com/rancher/dashboard/issues/9517

**Rancher Server Setup**
- Rancher version: `2.8.0-rc3`
- Installation option (Docker install/Helm Chart): `Helm Chart`
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: RKE2 - `v1.27.7+rke2r2`
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): `Infrastructure Provider` - `Digital Ocean`

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:
- Created a new user, with the global role `standard user` + added that user to a cluster as `Cluster Member`

**Describe the bug**

This is related to Dashboard issue https://github.com/rancher/dashboard/issues/9517, more directly to comment from @anupama2501 https://github.com/rancher/dashboard/issues/9517#issuecomment-1759280774.

A `standard user`, added to a downstream cluster as a `cluster member`, deleting a project he created with a couple of namespaces also created by him.
Deleting the project along with the namespaces on the UI doesn't make the namespaces resources disappear from the UI.

From my investigation I think it's related to the fact that we never get the `resource.delete` event via websockets (check videos a bit further down).

I've tried to capture as much information from the browser `Network` tab in terms of api requests and websocket messages we are receiving on Rancher Dashboard

If we refresh the page both the deleted project and namespaces disappear from the UI. (the project part I couldn't consistently repro it).

I don't think it's related to a specific cluster provider, but around permissions as `standard user` and `cluster member`

**To Reproduce**

- Create a downstream cluster of any type, I tried with k3s/rke2 node driver clusters
- Create a new user as a `Standard user`
- Added that user to the cluster as a `cluster member`.
- Login as that user
- Create a project P1 and a 2 namespaces ns1 and ns2
- When we try to delete the project by selecting the delete option for the namespaces, namespaces are still lingering on the UI with state `terminating`
**Note:** Couldn't reproduce it consistently, but sometimes the project still lingers on the UI

Also reproducible with:
- Create a downstream cluster of any type, I tried with k3s/rke2 node driver clusters
- Enabled auth provider
- Added a user from auth provider to the cluster as a cluster member.
- Login as that user
- Create a project P1 and a 2 namespaces ns1 and ns2
- When we try to delete the project by selecting the delete option for the namespaces, project appears back in the UI

**Result**
namespaces are still lingering on the UI with state `terminating`
**Note:** Couldn't reproduce it consistently, but sometimes the project still lingers on the UI

**Expected Result**

namespaces and project entries should disappear from the UI 

**Screenshots**

**Additional context**

_With a standard user_

https://github.com/rancher/rancher/assets/97888974/1a8f0c09-0545-4047-9957-d460f4757d7e

_With an Auth Provider user_

https://github.com/rancher/rancher/assets/97888974/7a42c5b8-0286-4f41-b228-e18fb9599114

**Comment by samjustus** [comment]
jira.suse.com/browse/SURE-8092

**Comment by crobby** [comment]
I was able to reproduce this in the latest main (Sep 9, 2024).
When logged in as the cluster member, I do notice the namespaces hanging around in the UI and I'm not seeing a "deleted/removed" event coming in the websocket.
However, if I log in as admin, the namespaces DO get removed from the UI.

Current theory is that once the namespaces are deleted, the required bindings are also deleted and the cluster member user no longer has permissions to list them , so any further events pertaining to their lifecycle are not reported via the websocket.

If the above theory pans-out:
1.  Maybe delay the removal of bindings until the namespaces are totally gone (not just "terminating).  
2.  <insert idea here>

**Comment by crobby** [comment]
@dasarinaidu Per the Rancher docs, it seems like the behavior when deleting a project is expected and as designed.  _"When you delete a project, any namespaces that were formerly associated with the project will remain on the cluster. You can find these namespaces in the Rancher UI, in the Not in a Project tab of the Projects/Namespaces page. You can reassign these namespaces to a project by moving them."_
I recommend closing this issue out.  If a change in functionality is desired, it would be a new RFE.
