### ISSUE TITLE
Move containers between hosts

### ISSUE THREAD

**Issue by ca0abinary** [rancher/rancher#438]
As an administrator I may need to move containers off of an over-provisioned machine so that I can free up resources on that host. I would like the ability to do this via the Rancher UI.
![image](https://cloud.githubusercontent.com/assets/2895417/7009362/a36b4ebe-dc67-11e4-898d-e57efaab8da0.png)

**Comment by thaJeztah** [comment]
There's currently work in progress to add support for [criu](http://criu.org/Main_Page) to libcontainer (see https://github.com/docker/libcontainer/pull/479). There would still be challenges, and migrating a container to another host would probably take some time.

Depending on your use case, creating a new container to replace the existing one, then stop/remove the old container will probably give a more seamless migration path (at least, for now)

**Comment by ca0abinary** [comment]
CRIU would be cool, however my thoughts were more in line with your suggestion. Imagine an automated rollover as the setup for some containers can be fairly involved and [insert random ops person on call] might not have the skill required to bring up the new container configured exactly the same.

**Comment by thaJeztah** [comment]
> might not have the skill required to bring up the new container configured exactly the same.

Yes, I agree with you there. I really think this would make a good feature. CRIU will also be overkill in many cases and, although it's under development, I don't expect it to be generally available for some time.

**Comment by ibuildthecloud** [comment]
@ca0abinary What about persistent data?  In this scenario do you expect docker volumes to move with the container?

**Comment by ca0abinary** [comment]
@ibuildthecloud No, since docker containers should be ephemeral anyway I wouldn't expect the data to be moved. It's assumed until rancher storage is available that the data container pattern will be used, but I don't think anyone expects data containers to move off-machine. Maybe a big red warning?

**Comment by demarant** [comment]
+1
I would love this feature with associated data volume transfer similar to what Flocker does.

**Comment by funkytaco** [comment]
The referenced docker pull has been merged since May: https://github.com/docker/libcontainer/pull/479 has been closed

So does this mean we can see container moves coming in the near future?

**Comment by RVN-BR** [comment]
+1, also interested in this...

**Comment by fabn** [comment]
What about sidekick data containers?

Does convoy solve this issue?

**Comment by willseward** [comment]
Also not interested in volume transfer. I just need to be able to stop the container on one host and start it on the other.

**Comment by sshipway** [comment]
+1 for this.  While I doubt it would be possible to seamlessly move a container between hosts, a way to manually rebalance a Environment would be very helpful.

In fact, I would like to see a Catalogue item that runs an automatic Environment balancing application, moving container instances around hosts to achieve an optimal balance of load over the Environment, within the scheduling rules.  Something like DRS for VMWare, when the system provides a list of recommendations with scores, and you set a threshold above which recommendations will be automatically applied.

**Comment by willseward** [comment]
Here's an interesting article using CRIU to move containers among hosts.

http://blog.circleci.com/checkpoint-and-restore-docker-container-with-criu/

**Comment by sshipway** [comment]
@willseward - That CRIU looks very nice.  Of course, the container will pause while migrating, and I don't know if it also migrates the ephemeral mounts, but it's way better than the delete/recreate way of moving a container.  If we had this, the VMware people would stop making snarky comments about guest migration vs container migration...
If CRIU were integrated with Rancher, then it would be able to migrate a container and its sidekicks together, removing any issues with volumes-from etc.

**Comment by willseward** [comment]
This looks like the defacto PR for this feature. I doubt it would be wise to integrate rancher with CRIU if docker has support coming. 

https://github.com/docker/docker/pull/13602

It looks like runc already has support, just waiting on Docker.

**Comment by colebrumley** [comment]
Even once this is available in mainline docker, CRIU has some kernel requirements that could pretty severely restrict where this feature could run out of the box. Stock Ubuntu 14.04 can't do it, which is a pretty big ding itself IMO since Rancher's all about working out of the box. Now, combined with ROS might be a different story...

**Comment by willseward** [comment]
Here is the updated issue after runc.

https://github.com/docker/docker/pull/22049

**Comment by feffi** [comment]
+2

**Comment by ebr** [comment]
My current method of migrating containers when retiring hosts is a bit crude, but works:
- start a new host
- put the "old" host into `Inactive` state
- delete containers one by one. this will cause new containers to be started on the "new" host.

I could also delete the host, which would cause all containers to be deleted  simultaneously and started on the new host. I just prefer a slightly more controlled approach.

I also tried to scale the service up+down after putting host into the Inactive state. This theoretically should work for services that don't rely on running a single container (e.g. for idempotency or whatever other reason). But in practice, it's not reliable, as it sometimes destroys the container on the "new" host when scaling down, bringing me back to the starting point. The only reliable (albeit tedious) way to do this so far is what I outlined in the beginning of the comment.

**Comment by willseward** [comment]
FWIW, it looks like checkpoints will make it into docker 1.13.

**Comment by thaJeztah** [comment]
@willseward they will be, but as an experimental feature, so things can (and probably _will_) change in the API and/or UX. We put it in experimental to collect feedback on those points, so feel free to give it a test 👍

**Comment by willseward** [comment]
@thaJeztah Thanks for the clarification. Do you have any info on how to run multiple versions of docker on a single host? It was simple when everything was in one binary, but now I'm not sure how to do it.

**Comment by thaJeztah** [comment]
@willseward there is some information in this section of the docs, but there's many things that can be problematic; multiple daemons managing IPTables (e.g.) won't work, so networking can be a challenge; https://docs.docker.com/engine/reference/commandline/dockerd/#/running-multiple-daemons

Depending on what you want to do (e.g. just do some minor testing with other versions), running docker-in-docker can work;

```
docker run -it --rm --privileged -v /var/lib/docker docker:1.12 sh
/ # dockerd --debug --iptables=false
DEBU[0000] Listener created for HTTP on unix (/var/run/docker.sock)
INFO[0000] libcontainerd: new containerd process, pid: 22
DEBU[0000] libcontainerd: containerd connection state change: CONNECTING
DEBU[0000] libcontainerd: containerd connection state change: TRANSIENT_FAILURE
DEBU[0000] containerd: read past events                  count=0
DEBU[0000] containerd: supervisor running                cpus=4 memory=1998 runtime=docker-runc runtimeArgs=[] stateDir=/var/run/docker/libcontainerd/containerd
DEBU[0000] containerd: grpc api on /var/run/docker/libcontainerd/docker-containerd.sock
DEBU[0001] Using default logging driver json-file
```

**Comment by skofgar** [comment]
Is there an update to this available? Moving containers would really be useful sometimes. Especially if a vm gets shutdown/rebooted. Now I have sometimes two images of the same group on the same vm and cannot move them back (easily). Or is @ebr path the current solution?

**Comment by Shatatel** [comment]
Are there any news about moving containers between hosts?
I use rancher for managing dockerized streaming software.
And when the service faces load spikes I need some extra containers on other hosts.
While load balancer knows about the possible hosts or can be easily updated, the hosts themselves consume some time for deploy.

**Comment by nelsonomuto** [comment]
One workaround is if you delete a host, it's containers will be moved to the next host.

**Comment by funkytaco** [comment]
So why not just port that code?

**Comment by EugenMayer** [comment]
Maybe you guys could participate here https://forums.rancher.com/t/service-stack-host-to-host-migration/6424/2 - the same question - host to host, just a little more elaborated. I would love to hear some feedback of the rancher developers or at least how they see there mission here

**Comment by vincent99** [comment]
Live migrate or similar are not going to happen in 1.x; You an Deactivate (or Evacuate) a Host and delete containers to reschedule them according to their scale/scheduling.  For 2.0, Kubernetes works similarly.

**Comment by kundeng** [comment]
No wonder no one wants to use containers.  such a simple feature unavailable after 5 years.
