### ISSUE TITLE
[Backport] [v2.7] [BUG] RKE1 Node driver cluster creation fails on SLE-15-SP5 and SP4

### ISSUE THREAD

**Issue by vardhaman22** [rancher/rancher#43811]
backport issue for: https://github.com/rancher/rancher/issues/43254**Rancher Server Setup**
- Rancher version: v2.7.9
- Installation option (Docker install/Helm Chart): Docker

**Information about the Cluster**
- Kubernetes version: v1.26.9-rancher1-1
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? : Node Driver (AWS) 

**User Information**
- What is the role of the user logged in? Admin

**Describe the bug**
RKE1 Node driver cluster provisioning fails on SLES-15-SP5 and SLES-15-SP4 OSes with following error in journalctl.
`failed to start daemon: error initializing graphdriver: [graphdriver] ERROR: the overlay storage-driver has been deprecated and removed; visit https://docs.docker.com/go/storage-driver/ for more information: overlay
`

**To Reproduce**

- Create a rancher server v2.7.9
- Create a node template with AMI ID - ami-0e2ff454233f50e3d (If this AMI is not accessible use any AMI with docker version 24.0.5 or create a new AMI with docker version 24.0.5)
- Docker version on this AMI is v24.0.5
- Provision a RKE1 node driver cluster with the SLES 15 OS and docker version 24.0.5

**Result**
Cluster creation fails with below error.
`failed to start daemon: error initializing graphdriver: [graphdriver] ERROR: the overlay storage-driver has been deprecated and removed; visit https://docs.docker.com/go/storage-driver/ for more information: overlay
`

**Expected Result**
Cluster provisions successfully.

**Additional context**
Issue was encountered while testing - https://github.com/rancher/qa-tasks/issues/1003 and https://github.com/rancher/qa-tasks/issues/1004

**Comment by rishabhmsra** [comment]
Validated on rancher v2.7-head(40afb19)

- Provisioned RKE1 v1.26.11-rancher2-1 k8s cluster(1-cp, 1-e, 1-w), using sles 15sp5 and sles 15sp4 amis - ami-0e2ff454233f50e3d, ami-07a85f4472da11a6f	
- docker version:
```
> kubectl describe node | grep docker
  Container Runtime Version:  docker://24.0.5-ce
  Container Runtime Version:  docker://24.0.5-ce
  Container Runtime Version:  docker://24.0.5-ce
```
- issue is fixed and cluster came up active, hence closing it.
