### ISSUE TITLE
Font for metadata values in VM are different style and size

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4382]
Version - v1.0.1-rc3

Steps to Reproduce: 
1.  Create a VM
2.  Click on VM machine name to get to details page

Results: The VM & OS metadata values are in a different font style and size
![image](https://cloud.githubusercontent.com/assets/11514927/14476468/b53facbe-00bc-11e6-9aaf-408437dfb90e.png)

Expected:  Should be same size and style

**Comment by vincent99** [comment]
Size ok, but style no.. it's JSON and should be printed monospace.

**Comment by lvuch** [comment]
https://github.com/rancher/ui/pull/718 not a drastic change but changed alignment and proportions

**Comment by tfiduccia** [comment]
Version - master 6/13
Verified fixed
