### ISSUE TITLE
Complete branching steps for Rancher 2.9 for Fleet 

### ISSUE THREAD

**Issue by rohitsakala** [rancher/rancher#43837]
**Tasks**

- [x] change the rancher-version annotation to `catalog.cattle.io/rancher-version: '>= 2.9.0-0 < 2.10.0-0'` while adding charts to dev-v2.9 branch. We do this so we can add patches to a particular Rancher minor version, in this case it would be the Rancher 2.9 line.
- [x] must have a new chart inside the rancher/charts repository that has a version 104.0.0+upX.Y.Z instead of 103.x.x+upX.Y.Z
- [x] testing

**Comment by kkaempf** [comment]
All checkmarks set, done in "Fleet" and "Platform Team" - closing
