### ISSUE TITLE
Kubectl logs fails 

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#4384]
Rancher Version:
1.0.0
Docker Version:
1.10.3
OS: 
Ubuntu
Steps to Reproduce: 
Create one instances and run kbuernetes environment on Rancher, register the host, and create any example pod, and then try to look through the pod logs using kubectl. 
Results: 
```
$ kubectl run example --image=nginx
replicationcontroller "example" created
$ kubectl logs example-rokc2
Error from server: Get https://node:10250/containerLogs/default/example-rokc2/example: dial tcp: lookup node: no such host
```
**node** is the hostname of the node where the pod run.

**Comment by alena1108** [comment]
https://github.com/kubernetes/kubernetes/issues/22063

**Comment by galal-hussein** [comment]
Kubectl logs/exec was tested against Rancher v1.2.0-pre1 and k8s v1.3, and it worked perfectly without errors.
