### ISSUE TITLE
Complete branching steps for Rancher 2.9 for CSP Adapter

### ISSUE THREAD

**Issue by rohitsakala** [rancher/rancher#43856]
**Tasks**

- [x] change the rancher-version annotation to `catalog.cattle.io/rancher-version: '>= 2.9.0-0 < 2.10.0-0'` while adding charts to dev-v2.9 branch. We do this so we can add patches to a  particular Rancher minor version, in this case, it would be the Rancher 2.9 line.
- [x] must have a new chart inside the rancher/charts repository that has a version 104.0.0+upX.Y.Z instead of 103.x.x+upX.Y.Z. 
- [x] testing

**Comment by jeremy-moffitt** [comment]
@guangyee please take a look at this when you're back next week.

**Comment by jeremy-moffitt** [comment]
my understanding from talking to Guang and Charu is that we need https://github.com/rancher/csp-adapter/pull/76  to land first, which is dependent upon https://github.com/rancher/client-go/pull/7

**Comment by jeremy-moffitt** [comment]
@guangyee I see the branch has been created, whats the status of the charts, annotations, and testing?

**Comment by guangyee** [comment]
`release/v2.9` branch had been created. We'll need to re-target this PR to the new branch and get it reviewed and merged.
https://github.com/rancher/csp-adapter/pull/76

**Comment by guangyee** [comment]
With https://github.com/rancher/csp-adapter/pull/78, we've completed local chart changes to support Rancher v2.9. Next step is to make the changes in `rancher/charts` and perform integration testing.

**Comment by jeremy-moffitt** [comment]
Meera indicates the work is complete with the PRs that merged today, closing issue
