### ISSUE TITLE
When hosts get registered with same name , they are not being listed when listing nodes and also dont seem to get used for container deployments.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#4385]
Rancher Version:v1.0.0-rc3

Steps to reproduce the problem:

Create a kubernetes environment.
Added Digital Ocean machine with name - do1.
Then added another Digital Ocean machine with same name - do1.
I have 2 other Digital Ocean machines with name do2 and do3.

When listing nodes using kubectl , I see only only 3 entries returned. 
Only 1 do1 entry whose state is "NotReady". Also I dont see any containers being deployed in this host.

<img width="860" alt="screen shot 2016-04-12 at 3 49 30 pm" src="https://cloud.githubusercontent.com/assets/4266958/14478077/3e658144-00c7-11e6-97bc-19286e46da46.png">

<img width="1191" alt="screen shot 2016-04-12 at 3 57 59 pm" src="https://cloud.githubusercontent.com/assets/4266958/14478095/60fefc26-00c7-11e6-9d6f-ee21116cbd68.png">

**Comment by sangeethah** [comment]
When I tried deleting one of the host entries with name "do1", kubectl get node returns "do1" node in "Ready" state. Container gets deployed in this host.

**Comment by roman0316** [comment]
@sangeethah 

Has there been any progress in this issue? I happened to bump into a similar behavior:

**Rancher version:** 
v1.1.0-dev5
**Hosts:**
Scaleway - Ubuntu 16.04 - Docker 1.10.3 - 3 hosts
DO - CentOS 7 - Docker 1.10.3 - 1 host
AWS - Ubuntu 15.04 - Docker 1.10.3 - 1 host

Rancher server is running on Ubuntu 16.04 with Docker 1.11.1

Apparently all hosts register, but when executing `kubectl get nodes`, 2 of the 3 scaleway nodes do not appear. The one that appears is the one with Kubernetes master processes. Also, as far as I have noticed, the nodes that don't appear are not used for deployment. 

I've recreated the nodes, inverted their order in which I added them, played with docker version 1.11 and 1.10 and the same result is achieved: only one of the scaleway nodes appears in output of `kubectl get nodes`

**One thing to notice:** kubelet process does not output the line "Successfully registered host ..." after starting up on the hosts that do not get registered. All other output is the same.

Thanks in advance.

**Comment by alena1108** [comment]
This is actually by design. Hostname is used as a unique identifier for k8s nodes, so duplicated names are not allowed. The solution will be: resolve the duplicates, and k8s should be able to go through with the nodes names registration.

@deniseschannon we should document this behavior

**Comment by deniseschannon** [comment]
Added into kubernetes docs about adding hosts.
