### ISSUE TITLE
Complete branching steps for Rancher 2.9 for system-upgrade-controller

### ISSUE THREAD

**Issue by rohitsakala** [rancher/rancher#43863]
**Tasks**

- [ ] change the rancher-version annotation to `catalog.cattle.io/rancher-version: '>= 2.9.0-0 < 2.10.0-0'` while adding charts to dev-v2.9 branch. We do this so we can add patches to a  particular Rancher minor version, in this case, it would be the Rancher 2.9 line.
- [ ] must have a new chart inside the rancher/charts repository that has a version 104.0.0+upX.Y.Z instead of 103.x.x+upX.Y.Z. 
- [ ] testing

**Comment by slickwarren** [comment]
tested the following use cases:
* fresh install custom and node driver clusters on 2.9-head (1970415f302ba1f16a38c1a7105d19055337e094) on 1.26, 1.27 and 1.28 using rke1, rke2, k3s
  * upgrade 1.26 -> 1.27 using rke1, rke2, k3s custom and node driver clusters
  * upgrade 1.27 -> 1.28 using rke1, rke2, k3s custom and node driver clusters
* fresh install custom and node driver clusters on 2.8.3 1.27 and 1.28 using rke1, rke2, and k3s
  * upgrade the rancher server to 2.9-head (1970415f302ba1f16a38c1a7105d19055337e094) 
  * upgrade 1.27 -> 1.28 using rke1, rke2, k3s

all tests have passed
