### ISSUE TITLE
Complete branching steps for Rancher 2.9 for Windows GSMA

### ISSUE THREAD

**Issue by rohitsakala** [rancher/rancher#43862]
**Tasks**

- [ ] change the rancher-version annotation to `catalog.cattle.io/rancher-version: '>= 2.9.0-0 < 2.10.0-0'` while adding charts to dev-v2.9 branch. We do this so we can add patches to a  particular Rancher minor version, in this case, it would be the Rancher 2.9 line.
- [ ] must have a new chart inside the rancher/charts repository that has a version 104.0.0+upX.Y.Z instead of 103.x.x+upX.Y.Z. 
- [ ] testing

**Comment by snasovich** [comment]
@HarrisonWAffel , please take care of it when you're back. Thank you!

**Comment by HarrisonWAffel** [comment]
The PR to add support for GMSAv1 into 2.9 had been merged

Test Steps:
1. Create a Rancher v2.9-head instance 
2. Create a downstream cluster, 1 node all roles 
3. Add a new charts repository which points to the `dev-2.9` branch of charts 
4. Install cert-manager 
5. Find and install the GMSA v1 chart, do not create a credential spec during the installation process
6. Ensure no errors are seen during the installation process, and that the web-hook deployed by the GMSA v1 chart is running as expected

**Comment by markusewalker** [comment]
**QA TEST PLAN**

|#|Scenario|Test Case|
|---|---|---|
|1|Windows gMSA chart installs on Rancher v2.9|Setup Rancher v2.9, provision a downstream RKE2 node driver cluster, install cert-manager chart, install Windows gMSA chart and validate it is successful|

**Comment by markusewalker** [comment]
Validated this is against `v2.9-head` https://github.com/rancher/rancher/commit/0fa763349c4b0e2f568f33dc62b60436f0a29b78. See details below:

**ENVIRONMENT DETAILS**
- Rancher install: Docker
- Rancher version: `v2.9-head` https://github.com/rancher/rancher/commit/0fa763349c4b0e2f568f33dc62b60436f0a29b78

**TEST RESULT**
|#|Scenario|Test Case|Result
|---|---|---|---|
|1|Windows gMSA chart installs on Rancher v2.9|Setup Rancher v2.9, provision a downstream RKE2 node driver cluster, install cert-manager chart, install Windows gMSA chart and validate it is successful|:white_check_mark:|

**VALIDATION STEPS**

**Scenario 1**
1. Setup Rancher v2.9.
2. As a standard user, provisioned a downstream RKE2 `v1.28.8+rke2r1` node driver cluster (3 etcd, 2 cp, 3 worker).
3. Added the `Rancher-Plugin-gMSA` repo to the cluster.
4. Installed the `cert-manager` chart and applied the CRDs to the cluster.
5. Installed the `Windows gMSA` chart without creating a gMSA credential spec.
