### ISSUE TITLE
Complete branching steps for Rancher 2.9 for webhook

### ISSUE THREAD

**Issue by rohitsakala** [rancher/rancher#43861]
**Tasks**

- [x] change the rancher-version annotation to `catalog.cattle.io/rancher-version: '>= 2.9.0-0 < 2.10.0-0'` while adding charts to dev-v2.9 branch. We do this so we can add patches to a  particular Rancher minor version, in this case, it would be the Rancher 2.9 line.
- [x] must have a new chart inside the rancher/charts repository that has a version 104.0.0+upX.Y.Z instead of 103.x.x+upX.Y.Z. 
- [x] testing

**Comment by ericpromislow** [comment]
Does commit feb903b152a0dc9e8e20021a4d9d2d150786f440 cover the first two steps in the checklist?

**Comment by rohitsakala** [comment]
@ericpromislow Yes It does.
