### ISSUE TITLE
[2.9] custom rke2 cluster upgraded to v1.26.8+rke2r1 has issues with limitranges and clusterauthtokens

### ISSUE THREAD

**Issue by maxsokolovsky** [rancher/rancher#43864]
forwardport rancher/rancher#43202

**Comment by samjustus** [comment]
https://github.com/rancher/rancher/pull/43873

**Comment by Priyashetty17** [comment]
## QA TEST PLAN

### Test Cases

| \#  | Description & Link                                                      | 
| --- | ----------------------------------------------------------------------- | 
| 1   | [Fresh install Check - Downstream RKE2 Cluster with K8s v1.27 and ACE enabled](#test-1)  | 
| 2   | [Fresh install Check - Downstream K3s Cluster with K8s v1.27](#test-2)  | 
| 3   | [Upgrade Check - Downstream RKE2 Cluster with K8s v1.26](#test-3)  |

<details>
    <summary>🚨 3 test cases... CLICK TO EXPAND! ⬅️</summary>

<br>

# 1 Fresh install Check - Downstream RKE2 Cluster with K8s v1.27 and ACE enabled

<a name="test-1"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 1 details... Click to expand</summary>

**Test Steps:**
1. Create a Rancher instance with v2.9-Next1.
2. Provision a downstream RKE2 cluster with K8s v1.27. 
   - Specify **defaultPodSecurityPolicyTemplateName: unrestricted**
   - Enable ACE: Cluster configuration >> Networking >> Authorized endpoint
3. Create a Project in the downstream cluster. Populate values for CPU and Memory Limit/reservations In the Container Default Resource Limit.
4. Create a namespace in the project. 
5. Verify that LimitRange object is created with the expected values in the namespace: `k get limitrange -n <namespace> -o yaml`.  
6. Create a deployment with one replica in the namespace and verify that the pod created in the deployment have the same limits set.
7. Edit the Project and modify the values for CPU and Memory Limit/reservations In the Container Default Resource Limit.
8. Create a namespace in the project. 
9. Verify that LimitRange object is created with the updated values in the namespace: `k get limitrange -n <namespace> -o yaml`.  
10. Create a deployment with one replica in the namespace and verify that the pod created in the deployment have the updated limits set.
11. Verify that there are NO PSP reflector errors in the rancher log:   
    - `failed to list *v1beta1.PodSecurityPolicy: the server could not find the requested resource`
12. Verify that there is an informational message starting with "**Creating limit range**" in the rancher log for each namespace.
13. Verify that the following informational message exists in the rancher log: 
    - `Checking cluster [clusterName] compatibility before registering podsecuritypolicy controllers.`
    - `podsecuritypolicies are not available in Kubernetes v1.25 and above - will not register podsecuritypolicy controllers for cluster`
14. Download kubeconfig of downstream cluster and verify that the token is generated on the local cluster: `k get token -A`
   
</details>

<hr>

# 2 Fresh install Check - Downstream K3s Cluster with K8s v1.27

<a name="test-2"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 2 details... Click to expand</summary>

**Test Steps:**
1. Create a Rancher instance with v2.9-Next1.
2. Provision a downstream K3s cluster with K8s v1.27. 
   - Specify **defaultPodSecurityPolicyTemplateName: unrestricted**
3. Repeat Steps 3-14 from Test 1

</details>

<hr>

# 3 Upgrade Check - Downstream RKE2 Cluster with K8s v1.26 

<a name="test-3"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 3 details... Click to expand</summary>

**Test Steps:**
1. Create a Rancher instance with v2.7.5.
2. Provision a downstream RKE2 cluster with K8s v1.26. 
   - Specify **defaultPodSecurityPolicyTemplateName: unrestricted**
3. Create a Project in the downstream cluster. Populate values for CPU and Memory Limit/reservations In the Container Default Resource Limit.
4. Create a namespace in the project. 
5. Verify that LimitRange object is NOT created in the namespace:` k get limitranges -n <namespace>`
6. Verify that there are PSP reflector errors in the rancher log:   
   - `failed to list *v1beta1.PodSecurityPolicy: the server could not find the requested resource`
7. Upgrade Rancher from 2.8.1 to 2.9-Next1.
8. Create a namespace in the project. 
9. Verify that LimitRange object is created with the expected values in the namespace for the namespaces created in Step4 and Step8: k get limitrange -n <namespace> -o yaml. 
10. Create a deployment with one replica in the namespace and verify that the pod created in the deployment have the same limits set.
11. Verify that there are NO PSP reflector errors in the rancher log:   
    - `failed to list *v1beta1.PodSecurityPolicy: the server could not find the requested resource`
12. Verify that there is an informational message starting with "Creating limit range" in the rancher log for each namespace.
13. Verify that the following informational messages exists in the rancher log: 
    - `Checking cluster [clusterName] compatibility before registering podsecuritypolicy controllers.`
    - `podsecuritypolicies are not available in Kubernetes v1.25 and above - will not register podsecuritypolicy controllers for cluster`
14. Download kubeconfig of downstream cluster and verify that the token is generated on the local cluster: `k get token -A`

</details>

**Comment by Priyashetty17** [comment]
Validated with v2.9-a4eb58dc76a85b1a56078f5ade8afe95c5cf0776-head
