### ISSUE TITLE
[Forwardport] [v2.9] [BUG] RKE1 Node driver cluster creation fails on SLE-15-SP5 and SP4

### ISSUE THREAD

**Issue by vardhaman22** [rancher/rancher#43895]
forward port issue for: https://github.com/rancher/rancher/issues/43254

**Comment by vivek-shilimkar** [comment]
Validated on rancher v2.9-head(2635b5a)

- Provisioned RKE1 v1.27.12-rancher2-1 k8s cluster(1-cp, 1-e, 1-w), using sles 15sp5 and sles 15sp4 amis - ami-0e2ff454233f50e3d, ami-07a85f4472da11a6f
- docker version is same as below in both opensue and sles : 
```
> kubectl describe node | grep docker
  Container Runtime Version:  docker://24.0.5-ce
  Container Runtime Version:  docker://24.0.5-ce
  Container Runtime Version:  docker://24.0.5-ce
```
- Also performed same above steps with OpenSUSE 15.5 and 15.4 ami - ami-0f0f07e28a7679ecb, ami-06f52279700a0ff40. Cluster came up active.

- issue is fixed and clusters came up active, hence closing it.
