### ISSUE TITLE
ACI CNI 6.0.3.1 changes for RKE1 v1.5.x

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#43893]
`rancher/rancher` tracking issue for https://github.com/rancher/rke/issues/3465

**Comment by snasovich** [comment]
Note: Unlike some other issues targeting v2.8.1, not creating forward/backports as once it's addressed in next v1.5.x RKE1 release there won't be a need to back/forwardport it to any other v2.8.x related RKE1 release. As far as v2.9.x related Rancher releases, RKE1 will be branched for it (v1.6.x release line likely) _after_ the changes for this issue are merged in.

**Comment by jiaqiluo** [comment]
The fix can be validated in Rancher [v2.8.1-rc1](https://github.com/rancher/rancher/releases/tag/v2.8.1-rc1)

**Comment by snasovich** [comment]
Marking this one as "Done" as we're not testing ACI and looking into PRs we've clearly moved missing changes to RKE1 1.5.x now and will get into v1.5.2 release.

@daviswill2 ,  If there are any issues found during v2.8.1 regression testing that have even remote chance of being related to this change, feel free to reopen this issue.

**Comment by slickwarren** [comment]
QA agrees that there is no direct testing of ACI, and will report any regressions from release testing appropriately.
