### ISSUE TITLE
Provide the links to access node ports exposed on all hosts. 

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#4389]
Rancher Version:v1.0.0-rc3

Create a kubernetese environment with few hosts.
Created a Replication Control for nginx container with replicas 2.
Created service with type="NodePort" for this RC.
1 random port gets assigned to be exposed in all the hosts in the setup , which provides access to all the nginx containers in RC.

There is no place in UI , where links to access node ports exposed on all hosts are provided.
hostIp links could possibly be included in the ports tab:

<img width="1133" alt="screen shot 2016-04-12 at 10 14 15 pm" src="https://cloud.githubusercontent.com/assets/4266958/14483464/1cc87b6a-00fc-11e6-8ce1-18e4b71a7521.png">

**Comment by will-chan** [comment]
This is now obsolete due to Rancher removing k8s UI and using Dashboard UI instead.
