### ISSUE TITLE
[Backport] [v2.7] [RFE] Add CIS-1.8 (k8s v1.26) Scan capability

### ISSUE THREAD

**Issue by vardhaman22** [rancher/rancher#43898]
CIS Workbench has released [CIS-1.8 for k8s v1.26](https://workbench.cisecurity.org/benchmarks/12958) (on oct 6th).

This issue is pending the creation of cis-1.8 in [kube-bench's cfg](https://github.com/aquasecurity/kube-bench/tree/main/cfg). We will start integrating CIS-1.8 to Rancher cis-benchmark once the profile will be made available upstream.

Past issue for CIS-1.7 : https://github.com/rancher/rancher/issues/41631

**Comment by rishabhmsra** [comment]
Closing this issue as it's a duplicate of https://github.com/rancher/rancher/issues/43710
