### ISSUE TITLE
[ForwardPort] [v2.9] [RFE] Add CIS-1.8 (k8s v1.26) Scan capability #43898

### ISSUE THREAD

**Issue by vardhaman22** [rancher/rancher#43899]
CIS Workbench has released [CIS-1.8 for k8s v1.26](https://workbench.cisecurity.org/benchmarks/12958) (on oct 6th).

This issue is pending the creation of cis-1.8 in [kube-bench's cfg](https://github.com/aquasecurity/kube-bench/tree/main/cfg). We will start integrating CIS-1.8 to Rancher cis-benchmark once the profile will be made available upstream.

Past issue for CIS-1.7 : https://github.com/rancher/rancher/issues/41631

**Comment by chiukapoor** [comment]
The issue is resolved by PR https://github.com/rancher/charts/pull/3736

**Comment by rishabhmsra** [comment]
Validated on rancher v2.9-head

- Created k8s v1.27 and v1.28 RKE1, RKE2 and k3s node driver as well as custom clusters.
- Installed CIS benchmark 6.0.0-rc2 chart.
- Ran permissive profile scans, all scans passed with expected failures.
- Also created RKE1 v1.28 hardened cluster and ran hardened profile scan, it passed with expected failures. 

Found an issue where all scans were failing on the k3s cluster, when the nodes were created using ubuntu 24.04. It's being tracked in a separate issue [here](https://github.com/rancher/rancher/issues/45588), hence closing this one.
