### ISSUE TITLE
[Backport - v2.8.1] [BUG] Rancher can't start on air-gapped environments

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#43910]
Backport of https://github.com/rancher/rancher/issues/43779 to https://github.com/rancher/rancher/tree/release/v2.8.1

See the linked issue for details / context.

**Comment by jiaqiluo** [comment]
The fix can be validated in Rancher [v2.8.1-rc1](https://github.com/rancher/rancher/releases/tag/v2.8.1-rc1)

**Comment by snasovich** [comment]
@prabalsharma , assigning to you to take care of QA sign-off for this fix.

**Comment by l4zy0n3** [comment]
Verified on:
rancher: v2.8.1-rc1
k8s: v1.27.8
Airgapped HA cluster
Flags:
 --set useBundledSystemChart=true --set ingress.tls.source=secret --set rancherImageTag=v2.8.1-rc1 --no-hooks

Expected:
- Rancher is able to start all 3 replicas are ready
 
Actual:
- Rancher is able to start all 3 replicas are ready

**Comment by rohitsakala** [comment]
@l4zy0n3 We also need to check if rancher-images.txt is generated correctly and has right entries.

**Comment by l4zy0n3** [comment]
> Verified on: rancher: v2.8.1-rc1 k8s: v1.27.8 Airgapped HA cluster Flags: --set useBundledSystemChart=true --set ingress.tls.source=secret --set rancherImageTag=v2.8.1-rc1 --no-hooks
> 
> Expected:
> 
> * Rancher is able to start all 3 replicas are ready
> 
> Actual:
> 
> * Rancher is able to start all 3 replicas are ready

The image 1rancher/ui-plugin-catalog:1.1.0` is present in `rancher-images.txt`
We can close this issue
