### ISSUE TITLE
Kubernetes Ingress support

### ISSUE THREAD

**Issue by zekizeki** [rancher/rancher#4392]
In order to create inbound routing to multiple web ui based pods running within a cluster, potentially spread over different namespaces then support for Ingress resources would be required.

Using the native Kubernetes Ingress capability would be preferable over custom solutions.

http://kubernetes.io/docs/user-guide/ingress/

The features of the Rancher load balancer match reasonably closely the capabilities offered by the Kubernetes ingress resource. Having the ability and flexibility to specify domain based and context based routing will open up more potential use cases for clusters being used to host multiple apps for multiple team environments.

**Comment by alena1108** [comment]
@prachidamle this ticket is to keep track of refactoring our current k8s lb solution to use k8s v1.2 ingress model.

**Comment by alena1108** [comment]
Branch to keep track of project progress: https://github.com/rancher/rancher-ingress

**Comment by alena1108** [comment]
@zekizeki 

Here is the high level flow for the feature:

1) Rancher ingress-controller gets created as a part of k8s system stack when user enabled k8s on the environment.
2) User creates the ingress in k8s. Example:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test
spec:
  rules:
  - host: foo.bar.com
    http:
      paths:
      - path: /foo
        backend:
          serviceName: nginx-service
          servicePort: 80
```

3) Rancher-ingress controller will create Rancher LB service for every ingress, populate it with the services endpoints and host name routing rules according to the rules defined on ingress, and update ingress "Address" field with the LB public endpoint (host ip address):

```
> kubectl get ingress
NAME      RULE          BACKEND   ADDRESS
test      -                                            104.154.107.202 // address updated by Rancher ingress-controller
          foo.bar.com
          /foo                     nginx-service:80

```

Rancher ingress-controller will monitor changes done to ingress and backend services of ingress controller, such as:

* ingress update
* backend services update (end point changes)

and update Rancher LB based on the changes.

Rancher ingress-controller will also listen to Rancher LB changes such as:

* public end point change (lb container gets redeployed to a different host)

and update Ingress with the new Address if endpoint change happened.

**Comment by alena1108** [comment]
v1 of ingress will be available in Rancher 1.1.0-dev2 release with limitations that will get addressed in 1.1 release:

* TLS support
* Custom public port for a LB
* Horizontal scaling for LB
* Stickiness policies support

**Comment by will-chan** [comment]
Closing enhancement.  If there are bugs found, file separate issues.

**Comment by zekizeki** [comment]
Thanks @alena1108 @will-chan looking good will try this out.
