### ISSUE TITLE
[BUG] Environment variables `https_proxy` and `no_proxy` are not correctly set in windows worker nodes of `custom` type `downstream` `RKE2` cluster with *Agent Environment Vars* `http_proxy`, `https_proxy` and `no_proxy`

### ISSUE THREAD

**Issue by billhong-just** [rancher/rancher#43932]
## Rancher Server Setup

- Rancher version: `v2.7.6`
- Installation option (Docker install/Helm Chart): `Helm Chart`
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): `v1.26.6+k3s1`

## Information about the Cluster

- Cluster Type (Local/Downstream): `Downstream`
  - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): `Custom`
- Kubernetes version: `v1.26.6+rke2r1`

## User Information

- What is the role of the user logged in? `Admin`

## Describe the bug

Environment variables `https_proxy` and `no_proxy` are not correctly set in `windows worker nodes` of `custom` type `downstream` `RKE2` cluster with *Agent Environment Vars* `http_proxy`, `https_proxy` and `no_proxy`

## Steps To Reproduce

1. Go to `Cluster Management` page of rancher
2. Create a `custom` type `downstream` `RKE2` cluster with version `v1.26.6+rke2r1` and with *Agent Environment Vars* `http_proxy`, `https_proxy` and `no_proxy`
3. Register a linux node with roles `control plane`, `etcd` and `worker` to the cluster
4. Wait until the cluster is ready
5. Register a `windows worker node` to the cluster
6. Wait until the cluster is ready
7. Install [Sysinternals Process Explorer](https://learn.microsoft.com/en-us/sysinternals/downloads/process-explorer) in the windows worker node
8. Open `Sysinternals Process Explorer` and search `rke2.exe` and `wins.exe`
9. Right click on the process and choose `Properties`
10. Switch to tab `Environment`
11. You can see that the missing environment variables `https_proxy` and `no_proxy` appear in the value of the environment variable `http_proxy`

## Result

The missing environment variables `https_proxy` and `no_proxy` appear in the value of the environment variable `http_proxy`.

**rke2.exe**
![rke2 exe](https://github.com/rancher/system-agent-installer-rke2/assets/77958736/f601fec3-1af5-46ae-9a1e-423708dcd422)

**wins.exe**
![wins exe](https://github.com/rancher/wins/assets/77958736/3ddcec6d-93ef-43d6-9b1f-32c81f7dc417)

## Expected Result

The environment variables `http_proxy`, `https_proxy`, and `no_proxy` are all correctly set.

**rke2.exe**
![rke2 exe](https://github.com/rancher/system-agent-installer-rke2/assets/77958736/fc3f695d-998e-4508-b986-05f5d8ddc3fd)

**wins.exe**
![wins exe](https://github.com/rancher/wins/assets/77958736/0c7f6dc9-7f0f-47a9-b5ea-66c8f192e1cb)

## Related PRs

- [x] https://github.com/rancher/wins/pull/156
- [x] https://github.com/rancher/system-agent-installer-rke2/pull/48

### OS Specifications of windows worker nodes

- Edition: `Windows Server 2022 Standard`
- Version: `21H2`
- OS build: `20348.2113`
- Powershell version: `PowerShell 5.1` & `PowerShell 7.4`

**Comment by HarrisonWAffel** [comment]
@billhong-just thanks for raising this issue and the two PR's! Out of curiosity, have you found that the proxy functionality does not work as expected with custom clusters because of this issue? The description of this issue correctly points out that the values are not entered into the registry properly, but I want to understand if there is a loss of functionality because of this.

**Comment by billhong-just** [comment]
@HarrisonWAffel 

As you might guess, the windows worker nodes of my `custom` type `downstream` `RKE2` cluster were not functioning properly after applying the proxy environment variables. The process `rke2.exe` kept failing and restarting. In the `Windows Event Viewer`, I found that the process "rke2.exe" kept logging the following error message.

![image](https://github.com/rancher/rancher/assets/77958736/399b9cac-8ba9-421f-a3c9-13646beff48e)

I opened a powershell terminal then used curl to make a request to https://index.docker.io through our proxy server. The request was successful so I can confirm there aren't any issues with our proxy server.

```
curl --proxy http://192.168.XXX.XXX:8080 https://index.docker.io
```

The only difference between the manual test above and `rke2.exe` is that the manual test above explicitly specifies a proxy server while `rke2.exe` use proxy environment variables. So I installed [Sysinternals Process Explorer](https://learn.microsoft.com/en-us/sysinternals/downloads/process-explorer) to check the proxy environment variables of `rke2.exe` and found they were not correctly set.

After checking the installation script `https://{our-rancher-domain}/wins-agent-install.ps1` and googling, I found [rancher/system-agent-installer-rke2/blob/main/package/run.ps1](https://github.com/rancher/system-agent-installer-rke2/blob/main/package/run.ps1#L84) and [rancher/wins/blob/main/install.ps1](https://github.com/rancher/wins/blob/main/install.ps1#L642), these two scripts set proxy environment variables in the registry.

Finally, I referred to the official documentation of powershell, manually executed the commands as my PR to fix the proxy registry, restarted the processes `wins.exe` and `rke2.exe`, and they returned to work normally.

**Comment by billhong-just** [comment]
@HarrisonWAffel 

Hi, will this issue be included in any rancher milestone?

**Comment by HarrisonWAffel** [comment]
@billhong-just sorry for the delay with this issue, I've added it to an upcoming milestone

**Comment by billhong-just** [comment]
@HarrisonWAffel 

Thank you so much! 🙇 

And I have **another question**, will this fix be patched in rancher `v2.7.x`? Or do we have to upgrade to rancher `v2.8.x` to get this fix?

**Comment by HarrisonWAffel** [comment]
@billhong-just I need to check with my team as to whether it will be back ported into a `2.7.x` release. [EOM for 2.7](https://www.suse.com/lifecycle/#suse-rancher-prime) is targeted for May, and we are limiting what is and is not back ported.

**Comment by billhong-just** [comment]
Thanks. 🙏

**Comment by billhong-just** [comment]
@HarrisonWAffel 

Hi, if your team has made a decision, please let me know, thank you. 👀

**Comment by HarrisonWAffel** [comment]
@billhong-just we have agreed to back-port this issue to the 2.7.x line, as well as 2.8.x and 2.9.0. Some things to note regarding the upcoming release cadence 

1. This fix will not make it into the upcoming 2.7.12 and 2.8.3 releases, as we are past code freeze and would not have the capacity to test this change in time for the release. 
2. The release after 2.7.12 and 2.8.3 will be a security only release, and likely will not include this issue 

So **this change will be released for 2.7.x**, but it may take some time before it makes it into an official Rancher release. I appreciate your patience with this, and thanks again for your contribution

**Comment by billhong-just** [comment]
I got it, thanks. 🙇

**Comment by slickwarren** [comment]
https://github.com/rancher/qa-tasks/issues/1290

**Comment by slickwarren** [comment]
tested on v2.8-head (9410818) as part of validation for 2.8.4:
* deploy rancher in a proxied environment
* deploy a custom rke2 cluster that is also proxied (1.28.8+rke2r1) with no outside internet access except via proxy. 
  * add windows worker nodes to the cluster with no outside internet access except via proxy. (windows 2022)
* observe proxy vars are correctly set on windows nodes -- pass
```
PS C:\Users\administrator> get-itemproperty HKLM:\SYSTEM\CurrentControlSet\Services\rke2


Environment    : {HTTP_PROXY=<proxy_ip>:3219, HTTPS_PROXY=<proxy_ip>:3219, 
                 NO_PROXY=localhost,127.0.0.1,0.0.0.0,10.0.0.0/8,<proxy_ip_subnet>/12,cattle-system.svc}
Type           : 16
Start          : 2
ErrorControl   : 1
ImagePath      : C:\usr\local\bin\rke2.exe agent --config /etc/rancher/rke2/config.yaml
DisplayName    : rke2
ObjectName     : LocalSystem
Description    : Rancher Kubernetes Engine v2 (agent) see docs https://github.com/rancher/rke2#readme
FailureActions : {30, 0, 0, 0...}
PSPath         : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\rke2
PSParentPath   : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services
PSChildName    : rke2
PSDrive        : HKLM
PSProvider     : Microsoft.PowerShell.Core\Registry
```
