### ISSUE TITLE
RKE2 and K3S - KDM Update for K8s January 2024 patch release for Rancher 2.7

### ISSUE THREAD

**Issue by rancher-max** [rancher/rancher#43937]
# KDM Updates

| New Kubernetes Version  | Min Rancher Version | Max Rancher Version |
|                  :---:                  |              :---:               |               :---:               |
| v1.26.13+rke2r1                  | v2.7.5-alpha1             | v2.7.99 |
| v1.26.13+k3s1                  | v2.7.5-alpha1             | v2.7.99 |

# KDM Branch
[dev-v2.7-2024-01-patches](https://github.com/rancher/kontainer-driver-metadata/tree/dev-v2.7-2024-01-patches)

# Chart Changelog

| Chart Name  | New Version | Affected Kubernetes Version(s) |
|        :---:        |       :---:        |                     :---:                     |
TBD

# Argument Changelog

| Argument Name  | Affected Kubernetes Version(s) |
|        :---:           |                     :---:                     |

# Additional Notes

**Comment by VestigeJ** [comment]
Validated
