### ISSUE TITLE
Agent fails to start after new proxy configuration

### ISSUE THREAD

**Issue by ndarilek** [rancher/rancher#4393]
Rancher Version: 1.0.0

Docker Version: 1.10.3

OS: Linux vm1 3.19.0-58-generic #64~14.04.1-Ubuntu SMP Fri Mar 18 19:05:43 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Steps to Reproduce: 

1. Use the following docker-compose.yml to spin up a Rancher instance behind a Caddy proxy:

```
server:
  image: rancher/server:latest
  restart: always
  volumes:
    - /srv/mysql:/var/lib/mysql

web:
  image: zzrot/alpine-caddy
  links:
    - server
  ports:
    - ":80:80"
    - ":443:443"
  restart: always
  volumes:
    - /root/Caddyfile:/etc/Caddyfile
    - /root/.caddy:/root/.caddy
  command: caddy --conf /etc/Caddyfile  --agree --email nolan@thewordnerd.info
```

2. Use the following /root/Caddyfile to enable Let's Encrypt on the Rancher endpoint with dynamically-generated, auto-renewing certs:

```
:443

proxy / server:8080 {
  proxy_header Host {host}
  proxy_header X-Real-IP {remote}
  proxy_header X-Forwarded-Proto {scheme}
  websocket
}

tls {
  max_certs 10
}
```

3. Add a host.

Results: 

The agent never spins up and dies with this cryptic error:

```
Monitoring mount context of PID 866
time="2016-04-13T16:02:59Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=1 reportedUuid="9abab06e-cbee-46ec-8bde-6a4900a0fa3e" 
  PID  PGID S TTY          TIME COMMAND
 5696  5406 S ?        00:00:00 /bin/bash /var/lib/cattle/pyagent/cattle/process_watcher.sh
 5701  5406 S ?        00:00:00 host-api -cadvisor-url http://127.0.0.1:9344 -logtostderr=true -ip 0.0.0.0 -port 9345 -auth=true -host-uuid 9abab06e-cbee-46ec-8bde-6a4900a0fa3e -public-key /var/lib/cattle/etc/cattle/api.crt -cattle-url https://rancher.thewordnerd.info/v1 -cattle-state-dir /var/lib/rancher/state/containers
 5708  5406 S ?        00:00:00 /bin/bash /var/lib/cattle/bin/cadvisor.sh cadvisor -logtostderr=true -listen_ip 127.0.0.1 -port 9344 -housekeeping_interval 1s -docker_root /var/lib/docker
 5729  5406 S ?        00:00:00 /var/log/rancher/.cadvisor -logtostderr=true -listen_ip 127.0.0.1 -port 9344 -housekeeping_interval 1s -docker_root /var/lib/docker
 5737  5406 R ?        00:00:00 ps -eO pgid
 5738  5406 R ?        00:00:00 grep -E PGID| 5406
  PID  PGID S TTY          TIME COMMAND
 5696  5406 S ?        00:00:00 /bin/bash /var/lib/cattle/pyagent/cattle/process_watcher.sh
 5701  5406 S ?        00:00:00 host-api -cadvisor-url http://127.0.0.1:9344 -logtostderr=true -ip 0.0.0.0 -port 9345 -auth=true -host-uuid 9abab06e-cbee-46ec-8bde-6a4900a0fa3e -public-key /var/lib/cattle/etc/cattle/api.crt -cattle-url https://rancher.thewordnerd.info/v1 -cattle-state-dir /var/lib/rancher/state/containers
 5708  5406 S ?        00:00:00 /bin/bash /var/lib/cattle/bin/cadvisor.sh cadvisor -logtostderr=true -listen_ip 127.0.0.1 -port 9344 -housekeeping_interval 1s -docker_root /var/lib/docker
 5729  5406 S ?        00:00:00 /var/log/rancher/.cadvisor -logtostderr=true -listen_ip 127.0.0.1 -port 9344 -housekeeping_interval 1s -docker_root /var/lib/docker
 5744  5406 R ?        00:00:00 ps -eO pgid
 5745  5406 R ?        00:00:00 grep -E PGID| 5406
PID 5406 has died doing kill 5701 5708 5729
  PID  PGID S TTY          TIME COMMAND
 5696  5406 S ?        00:00:00 /bin/bash /var/lib/cattle/pyagent/cattle/process_watcher.sh
 5755  5406 R ?        00:00:00 ps -eO pgid
 5756  5406 R ?        00:00:00 grep -E PGID| 5406
Caught EXIT
  PID  PGID S TTY          TIME COMMAND
 5696  5406 S ?        00:00:00 /bin/bash /var/lib/cattle/pyagent/cattle/process_watcher.sh
 5762  5406 R ?        00:00:00 ps -eO pgid
 5763  5406 R ?        00:00:00 grep -E PGID| 5406
INFO: Starting agent for 88CD217CA6A2F5DC58D0
```

Expected:

The host will connect. I'll have auto-generated, auto-renewing SSL certs on my Rancher API endpoint.

This setup seems to have broken after I changed my setup to Caddy/Let's Encrypt. Before that, I had a purchased cert behind an Nginx proxy. I don't know if the cert is cached somewhere, but I rm -rf'd /var/lib/rancher on the host and re-added it. I'm also wondering if Rancher is trying to serve up a cert from somewhere for other types of connections, and that cert doesn't match the LE-issued one. Very confused, but none of my hosts work anymore with this setup.

Thanks.

**Comment by vincent99** [comment]
The agent connection is a WebSocket and [Caddy is broken](https://github.com/rancher/rancher/issues/4278) in a way that specifically affects WebSockets in Jetty apps like ours.  There is a [PR](https://github.com/mholt/caddy/pull/713) merged to fix it but no release containing it yet.

**Comment by ndarilek** [comment]
Cool. Any possibility of a better message in that failure case? I 
suspected Caddy but didn't know for sure as it was just about killing 
pids. :)

Thanks.

**Comment by firrae** [comment]
Hi there,

Not quite sure what I'm missing, but I'm getting the same error with this specific config (identical to above):

```
proxy / server:8080 {
  proxy_header Host {host}
  proxy_header X-Real-IP {remote}
  proxy_header X-Forwarded-Proto {scheme}
  websocket
}
```

The browser spits out: `WebSocket connection to 'ws://rancher... failed: Error during WebSocket handshake: 'Upgrade' header is missing`.

Any and all help would be greatly appreciated!

**Comment by vincent99** [comment]
Are you using the newest Caddy release?

**Comment by firrae** [comment]
I am on version 0.8.2, would that be before the fix @vincent99? The most current version is 0.8.3, I can try upgrading.

**Comment by firrae** [comment]
Well @vincent99 that seems to have been it. Derp. Sorry about that.
