### ISSUE TITLE
[Forwardport v2.9] [Feature] K8s 1.28 Support

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#43945]
Forwardport of https://github.com/rancher/rancher/issues/43109, see details on the linked issue.

* [x] rancher/rancher: 
  * https://github.com/rancher/rancher/pull/45082

**Comment by rishabhmsra** [comment]
Validated on rancher v2.9-head(f26d988)
- Provisioned  RKE1, RKE2 and K3s node driver and custom clusters using below k8s versions : 
  - v1.28.8-rancher1-1
  - v1.28.8+rke2r1
  - v1.28.8+k3s1
 
- All clusters came up successfully with all the pods up and running.

**Comment by rishabhmsra** [comment]
Cluster provisioning using k8s v1.28 is working fine, hence closing this issue.
