### ISSUE TITLE
Should be allowed to create files in kubectl shell

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#4394]
Rancher Version:v1.0.1-rc3

Steps to create the problem:
Create a kubernetes environment.
Launch kubectl shell from kubernetes/Kubectl.
Try to create any file .

Expected Behavior:
Not able to create file - "permission denied" error
we should be allowed to create yaml file that can be used with kubectl command with -f option

**Comment by soumyalj** [comment]
Tested with v1.1.0-dev4-rc1, able to create a file successfully in kubectl.
