### ISSUE TITLE
[Forwardport v2.9] [rke1 etcd restore] unable to restore etcd snapshot

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#43948]
Forwardport of https://github.com/rancher/rancher/issues/41547, see details there.

**Comment by jiaqiluo** [comment]
The fix can be validated on v2.9-head now
For QA details please check https://github.com/rancher/rancher/issues/41547#issuecomment-1883536227

**Comment by susesgartner** [comment]
Ticket #43948 - Test Results - ✅ 
---
 
| Scenario | Test Case | Result |
|---|---|---|
| 1. | Snap restore | PASS |

---
Verified with HA Helm on Rancher `v2.9-head`:
---
 
Scenario 1: Snap restore
---
1. Create a rke1 9 node downstream cluster
2. Take a snapshot
3. Restore a snapshot
4. Repeat steps 2-3 5 times
 
Results: All snapshots successfully restored
