### ISSUE TITLE
DNS support for k8s named ports

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#4395]
Rancher Version:v1.0.0-rc3

Create Kubernetes environment.
Add a service to RC with pod having nginx container have named port.

```
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2016-04-12T23:30:46Z
  name: myservice1
  namespace: default
  resourceVersion: "1990"
  selfLink: /api/v1/namespaces/default/services/myservice1
  uid: 9500996b-0106-11e6-b8c0-026e7570bd47
spec:
  clusterIP: 10.43.149.242
  ports:
  - name: testp
    port: 9999
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

From any other container within the same namespace , we are noot able to resolve _my-port-name._my-port-protocol.my-svc.my-namespace.svc.cluster.local.

<img width="715" alt="screen shot 2016-04-13 at 10 47 58 am" src="https://cloud.githubusercontent.com/assets/4266958/14503532/58beb904-0165-11e6-954e-dc3b1f8cf509.png">

**Comment by sangeethah** [comment]
The same issue seen when testing with headless services as well.
```
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2016-04-13T00:45:10Z
  name: headless
  namespace: default
  resourceVersion: "4039"
  selfLink: /api/v1/namespaces/default/services/headless
  uid: fa040ae9-0110-11e6-b8c0-026e7570bd47
spec:
  clusterIP: None
  ports:
  - name: testp
    port: 2323
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```
<img width="651" alt="screen shot 2016-04-13 at 11 11 36 am" src="https://cloud.githubusercontent.com/assets/4266958/14504199/9b930c6e-0168-11e6-8b87-e419b391d016.png">

**Comment by alena1108** [comment]
Should be fixed sky dns support, sky dns should support this resolution. @imikushin could you test it as a part of sky dns test?

**Comment by imikushin** [comment]
Works as expected with kube-dns

**Comment by imikushin** [comment]
The command to test with `dig`:

```
# dig _http._tcp.nginx-service.default.svc.cluster.local SRV +short
10 100 80 nginx-service.default.svc.cluster.local.
```

Note the "`_`" in `_http` and `_tcp`

**Comment by galal-hussein** [comment]
Tested both normal and headless namedport services and worked on master build, rancher-catalog and vnext branch.
