### ISSUE TITLE
[BUG] Issues identified by go vet 1.21

### ISSUE THREAD

**Issue by pmatseykanets** [rancher/rancher#43957]
**Rancher Server Setup**
N/A

**Information about the Cluster**
N/A

**User Information**
N/A

**Describe the bug**

```
go version
go version go1.21.4 darwin/amd64

go vet ./...
# github.com/rancher/rancher/pkg/controllers/dashboard/chart_test
pkg/controllers/dashboard/chart/chart_test.go:179:38: loop variable tt captured by func literal
# github.com/rancher/rancher/pkg/features
vet: pkg/features/feature_test.go:36:15: undefined: IsDefFalse
```

**To Reproduce**
N/A

**Result**

**Expected Result**

**Screenshots**

N/A

**Additional context**

N/A

**Comment by crobby** [comment]
I have validated this fix.
Running go vet on the commit before the fix showed the problems listed in this ticket.
Running go vet on the commit with this fix shows no problems.
