### ISSUE TITLE
k8s cluster_domain is not supported by Rancher

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#4396]
Today we default k8s namespace to the k8s default domain value - "cluster.local". But there is a way to override the default domain by specifying cluster_domain in the service template:

```
cluster-domain=<default local domain>
```

We should add support for overriding default domain in Rancher dns based on the k8s service clusterDomain; and only if not specified, set to cluster.local.

@ibuildthecloud

**Comment by imikushin** [comment]
@alena1108 Do you think we should fix this?

We can ask the user what their cluster domain should be on before kubernetes system stack start.

**Comment by imikushin** [comment]
Technically, not a bug but a limitation.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
