### ISSUE TITLE
[Forwardport 2.9] system-upgrade-controller k8s 1.28 chart support

### ISSUE THREAD

**Issue by Jono-SUSE-Rancher** [rancher/rancher#43963]
This is a forward port of https://github.com/rancher/rancher/issues/43730

**Comment by markusewalker** [comment]
**QA TEST PLAN**

|#|Scenario|Test Case|
|---|---|---|
|1|Validate `system-upgrade-controller` version in freshly-installed RKE2 v1.28 cluster|Provision downstream RKE2 v1.28 cluster and validate the `system-upgrade-controller` chart version|
|2|Validate `system-upgrade-controller` version in upgraded RKE2 v1.28 cluster|Provision downstream RKE2 v1.27 cluster, upgrade to v1.28 cluster and validate the `system-upgrade-controller` chart version|
|3|Validate `system-upgrade-controller` version in an imported K3s v1.27 cluster|Provision a standalone K3s v1.28 cluster, import it into Rancher, upgrade to v1.28 and validate the `system-upgrade-controller` chart version|
|4|Validate `system-upgrade-controller` version in K3s cluster after upgrading Rancher|Setup Rancher v2.8.2, provision a downstream K3s v1.26 cluster, upgrade Rancher, upgrade to v1.28 and validate the `system-upgrade-controller` chart version|
|5|Validate `system-upgrade-controller` version in an imported RKE2 cluster after upgrading Rancher|Provision a standalone RKE2 v1.26 cluster, setup Rancher v2.8.2, import the cluster into Rancher, upgrade Rancher, upgrade cluster to v1.28 and validate the `system-upgrade-controller` chart version|

**Comment by snasovich** [comment]
Sent back to "Working" for `rancher/rancher` side changes.

**Comment by markusewalker** [comment]
Validated this against `v2.9-head` https://github.com/rancher/rancher/commit/a485774c4f71cc32464537e5982583335956443c.

**ENVIRONMENT DETAILS**
- Rancher install: Docker
- Rancher version: `v2.9-head` https://github.com/rancher/rancher/commit/a485774c4f71cc32464537e5982583335956443c

**TEST RESULT**
|#|Scenario|Test Case|Result
|---|---|---|---|
|1|Validate `system-upgrade-controller` version in freshly-installed RKE2 v1.28 cluster|Provision downstream RKE2 v1.28 cluster and validate the `system-upgrade-controller` chart version|:white_check_mark:|
|2|Validate `system-upgrade-controller` version in upgraded RKE2 v1.28 cluster|Provision downstream RKE2 v1.27 cluster, upgrade to v1.28 cluster and validate the `system-upgrade-controller` chart version|:white_check_mark:|
|3|Validate `system-upgrade-controller` version in an imported RKE2 v1.27 cluster|Provision a standalone RKE2 v1.28 cluster, import it into Rancher, upgrade to v1.28 and validate the `system-upgrade-controller` chart version|:white_check_mark:|
|4|Validate `system-upgrade-controller` version in K3s cluster after upgrading Rancher|Setup Rancher v2.8.2, provision a downstream K3s v1.26 cluster, upgrade Rancher, upgrade to v1.28 and validate the `system-upgrade-controller` chart version|:white_check_mark:|
|5|Validate `system-upgrade-controller` version in an imported RKE2 cluster after upgrading Rancher|Provision a standalone RKE2 v1.26 cluster, setup Rancher v2.8.2, import the cluster into Rancher, upgrade Rancher, upgrade cluster to v1.28 and validate the `system-upgrade-controller` chart version|:white_check_mark:|

**VALIDATION STEPS**

**Scenario 1**
1. Provisioned a downstream RKE2 `v1.28.6+rke2r1` cluster (1 etcd, 1 cp, 1 worker) as a standard user.
2. Noted that that the chart is at the following version: `system-upgrade-controller:104.0.0+up0.7.0`.

_____

**Scenario 2**
1. Provisioned a downstream RKE2 `v1.27.10+rke2r1` cluster (1 etcd, 1 cp, 1 worker) as a standard user.
2. Noted that that the chart is at the following version: `system-upgrade-controller:104.0.0+up0.7.0`.
3. Upgraded the cluster to v1.28.
4. Validated that the chart version is still the same.

______

**Scenario 3**
1. Provisioned a standalone RKE2 `v1.27.10+rke2r1` cluster.
2. Successfully imported the cluster into Rancher.
3. Upgraded the cluster to `v1.28.6+rke2r1`.
4. Noted that the deployment version is at: `rancher/system-upgrade-controller:v0.13.1`.

_____

**Scenario 4**
1. Provisioned a downstream K3s `v1.26.13+k3s2` cluster (1 etcd, 1 cp, 1 worker) as a standard user.
2. Noted that the chart is at the following version: `system-upgrade-controller:103.0.0+up0.6.0`.
3. Upgraded Rancher to `v2.8-head`.
4. Validated SUC chart is at the same version pre-upgrade.
5. Upgraded cluster to `v1.28.6+k3s2`.
6. Validated that the SUC chart version has been upgraded to `system-upgrade-controller:104.0.0+up0.7.0`.

_____

**Scenario 5**
1. Provisioned a standalone RKE2 `v1.26.13+rke2r1` cluster.
2. Successfully imported the cluster into Rancher.
3. Upgraded Rancher to `v2.8-head`.
4. Upgraded cluster to `v.128.6+rke2r1`.
5. Validated that the deployment version is at: `rancher/system-upgrade-controller:v0.13.1`.
