### ISSUE TITLE
[Forwardport v2.9] [Feature] K8s 1.29 Support

### ISSUE THREAD

**Issue by Jono-SUSE-Rancher** [rancher/rancher#43965]
This is a forwardport of https://github.com/rancher/rancher/issues/43110 for adding 1.29 support.

**Comment by snasovich** [comment]
Changed this issue to "forwardport to v2.9" as we will probably be primarily working on `release/v2.8` branch for this effort and then port it to v2.9.

**Comment by Sahota1225** [comment]
Closing this issue as we are tracking the work in https://github.com/rancher/rancher/issues/43110
