### ISSUE TITLE
Not able to resolve POD A records

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#4397]
Rancher Version:v1.0.1-rc3

Create kubernetes environment.
Add a pod.

<img width="1133" alt="screen shot 2016-04-13 at 12 30 01 pm" src="https://cloud.githubusercontent.com/assets/4266958/14506603/7c36346c-0173-11e6-981c-68c7e8a8e210.png">

From a container that belong to another pod in the same namespace , try to  resolve `<ipaddress>.default.pod.cluster.local .`

Resolution fails.

<img width="628" alt="screen shot 2016-04-13 at 11 56 17 am" src="https://cloud.githubusercontent.com/assets/4266958/14505624/db21a93e-016e-11e6-8856-c2f2a7a170fe.png">

**Comment by imikushin** [comment]
This should be resolved by using kube-dns: #5948

**Comment by galal-hussein** [comment]
Rancher version: master
Kubernetes version: 1.4.6
rancher-catalog, vnext branch

Pod A record are being resolved using `<ipaddress>.default.pod.cluster.local`
