### ISSUE TITLE
Add 0.4.2 version of prometheus federator

### ISSUE THREAD

**Issue by rohitsakala** [rancher/rancher#43978]
We are introducing a new version of Prometheus Federator due to CVE's and to remove Chart.yaml.orig which is a useless file.

**Comment by MKlimuszka** [comment]
@rohitsakala , what Rancher version did you merge this into? That is required so QA knows when they have to test it. 
CC @recena

**Comment by MKlimuszka** [comment]
Related: https://github.com/rancher/rancher/issues/44605

**Comment by rohitsakala** [comment]
@MKlimuszka  It was Rancher 2.8

**Comment by alexandreLamarre** [comment]
@MKlimuszka It's not related to #44605, but related to https://github.com/rancher/charts/pull/3271, which was merged months ago. However it looks like the current dev-v2.8 branch does not have this change, potentially due to a sync up issue with the dev-v2.8.11

**Comment by pankajsqe** [comment]
validated prometheus-federator:103.0.1+up0.4.1 it got stuck with status “WaitingForDashboardValues” and throwing error on rancher v2.8.3-rc4 with dev 2.9  PFA

Rancher v2.8.3-rc4
Cluster v1.26.13+rke2r1
prometheus-federator:103.0.1+up0.4.1
Rancher-monitoring:103.0.1+up45.31.1

![Image](https://github.com/rancher/rancher/assets/149133120/9a2534bb-113d-4264-9c28-8c638775f8c9)
![Image](https://github.com/rancher/rancher/assets/149133120/c1222387-b548-4efa-a132-24db161f09d4)

**Comment by alexandreLamarre** [comment]
As I was debugging, It looks like the helm install fails with a templating issue :
```
2024-03-26T15:17:11.635312263Z + helm_v3 upgrade --namespace cattle-project-p-5ftst-monitoring cattle-project-p-5ftst-monitoring /tmp/cattle-project-p-5ftst-monitoring.tgz --values /config/values-01_HelmChart.yaml
Error: UPGRADE FAILED: template: rancher-project-monitoring/charts/grafana/templates/image-renderer-hpa.yaml:1:48: executing "rancher-project-monitoring/charts/grafana/templates/image-renderer-hpa.yaml" at <.Values.imageRenderer.autoscaling.enabled>: nil pointer evaluating interface {}.enabled
+ exit
```
It doesn't seem like the default values cause this template issue, so this likely has to do with the injected values.

**Comment by pankajsqe** [comment]
prometheus-federator:104.0.0-rc1+up0.4.2  has been added and validated successfully on rancher v2.9.0-alpha7 and v2.9-head.

Cluster : v1.30.2+k3s2 , v1.29.4+rke2r1, EKS1.29, AKS1.29
Monitor : rancher-monitoring:104.0.0-rc1+up57.0.3
Alert : 104.0.0-rc1
Prometheus Fed : prometheus-federator:104.0.0-rc1+up0.4.2 

**Fresh Install Testing**

- Install Monitoring 104.0.0-rc1+up57.0.3 for the first time on a new cluster
- Install Alerting Drivers 104.0.0-rc1 for the first time on a new cluster
- Install prometheus-federator:104.0.0-rc1+up0.4.2  for the first time on a new cluster
- Perform E2E Tests on project monitor.
- Confirm that Alerts are still being received and graph and metrics are being populated in project-monitor

**Upgrade Testing**

- Install Monitoring 103.1.1+up45.31.1
- Install Alerting Drivers 104.0.0-rc1
- Perform Alerting-Driver configuration to send an alert to an endpoint (eg, sachet)
- Confirm Alerts are being received
- Upgrade Rancher Monitoring to version 104.0.0-rc1+up57.0.3
- Install prometheus-federator:104.0.0-rc1+up0.4.2  for the first time on a new cluster
- Perform E2E Tests on project monitor.
- Confirm that Alerts are still being received and graph and metrics are being populated in project-monitor
