### ISSUE TITLE
[Backport v2.8] vSphere CPI chart updates to upstream v1.28.0 / v1.23.5 / v1.22.9 (incl. K8s 1.28 support)

### ISSUE THREAD

**Issue by Jono-SUSE-Rancher** [rancher/rancher#43979]
This is a backport for the v2.8 version of this ticket: https://github.com/rancher/rancher/issues/43495

**Comment by slickwarren** [comment]
@rancher-max since RKE2 team did the validation for 1.28, would you mind commenting here / closing the issue if everything passed?

**Comment by rancher-max** [comment]
This has been **validated for rke2** in https://github.com/rancher/rke2/issues/5217#issuecomment-2004706497. We also performed validations creating via rancher, which worked successfully on both split-role setups and single node all-role setups.

**Comment by slickwarren** [comment]
RKE1 was also tested and passing
