### ISSUE TITLE
[v2.8] Update ACI-CNI to 6.0.3.2

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#43987]
There is ACI-CNI version 6.0.3.2 which is an upgrade to 6.0.3.1 we currently have included in KDM for RKE1 provisioned clusters.

**Comment by jeffinkottaram** [comment]
Testing has been completed. No issues observed.

**Comment by Josh-Diamond** [comment]
Ticket #43987 - Test Results - ✅ 
---

Tested w/ RKE `v1.5.3-rc1` and on a Docker install w/ Rancher `v2.8-97b35b27fe786d1707127923e2abfb93fad6ec65-head`:

| Scenario | Test Case | Result |
|---|---|---|
| 1. | Rancher provisioned downstream RKE1 w/ k8s `v1.27.8-rancher2-2` | ✅ |
| 2. | Import into Rancher a downstream RKE1 w/ k8s `v1.27.8-rancher2-2`, using RKE `v1.5.3-rc1` | ✅ |
| 3. | Rancher provisioned downstream RKE1 w/ k8s `v1.26.11-rancher2-2` | ✅ |
| 4. | Import into Rancher a downstream RKE1 w/ k8s `v1.26.11-rancher2-2`, using RKE `v1.5.3-rc1` | ✅ |
| 5. | Rancher provisioned downstream RKE1 w/ k8s `v1.25.16-rancher2-2` | ✅ |
| 6. | Import into Rancher a downstream RKE1 w/ k8s `v1.25.16-rancher2-2`, using RKE `v1.5.3-rc1` | ✅ |

---

Scenario 1 -
1. Fresh install of Rancher `v2.8-head`
2. Provision a downstream AWS RKE1 Node driver cluster w/ k8s `v1.27.8-rancher2-2`
3. Once `active`, navigate to `Cluster Explorer > Workloads` and ensure all pods are `active` and running
4. Verified - all pods are active and running
5. Deploy a workload
6. Verified - workload successfully deployed; pod is active and running

---

Scenario 2 -
1. Fresh install of Rancher `v2.8-head`
2. Using RKE `v1.5.3-rc1`, create a standalone Custom RKE1 cluster w/ k8s `v1.27.8-rancher2-2`, then import it into Rancher
3. Verified - cluster successfully imports and is `active`
4. Navigate to `Cluster Explorer > Workloads` and ensure all pods are `active` and running
5. Verified - all pods active and running
6. Deploy a workload
7. Verified - workload successfully deployed; pod is active and running

---

Scenario 3 -
1. Fresh install of Rancher `v2.8-head`
2. Provision a downstream AWS RKE1 Node driver cluster w/ k8s `v1.26.11-rancher2-2`
3. Once `active`, navigate to `Cluster Explorer > Workloads` and ensure all pods are `active` and running
4. Verified - all pods are active and running
5. Deploy a workload
6. Verified - workload successfully deployed; pod is active and running

---

Scenario 4 -
1. Fresh install of Rancher `v2.8-head`
2. Using RKE `v1.5.3-rc1`, create a standalone Custom RKE1 cluster w/ k8s `v1.26.11-rancher2-2`, then import it into Rancher
3. Verified - cluster successfully imports and is `active`
4. Navigate to `Cluster Explorer > Workloads` and ensure all pods are `active` and running
5. Verified - all pods active and running
6. Deploy a workload
7. Verified - workload successfully deployed; pod is active and running

---

Scenario 5 - 
1. Fresh install of Rancher `v2.8-head`
2. Provision a downstream AWS RKE1 Node driver cluster w/ k8s `v1.25.16-rancher2-2`
3. Once `active`, navigate to `Cluster Explorer > Workloads` and ensure all pods are `active` and running
4. Verified - all pods are active and running
5. Deploy a workload
6. Verified - workload successfully deployed; pod is active and running

---

Scenario 6 -
1. Fresh install of Rancher `v2.8-head`
2. Using RKE `v1.5.3-rc1`, create a standalone Custom RKE1 cluster w/ k8s `v1.25.16-rancher2-2`, then import it into Rancher
3. Verified - cluster successfully imports and is `active`
4. Navigate to `Cluster Explorer > Workloads` and ensure all pods are `active` and running
5. Verified - all pods active and running
6. Deploy a workload
7. Verified - workload successfully deployed; pod is active and running

---

Screenshot:
<img width="1460" alt="Screenshot 2024-01-22 at 12 05 53 PM" src="https://github.com/rancher/rancher/assets/46494969/099a4ea9-1315-449b-8324-e8d223ff008e">
