### ISSUE TITLE
[Backport v2.8] Cannot set custom Node Name for Windows worker nodes

### ISSUE THREAD

**Issue by Jono-SUSE-Rancher** [rancher/rancher#43982]
This is the v2.8 backport of the https://github.com/rancher/rancher/issues/43587 issue.

**Comment by susesgartner** [comment]
Ticket #43982 - Test Results - ✅ 
---
 
| Scenario | Test Case | Result |
|---|---|---|
| 1. | Test custom name | PASS |
| 2. | Test default name | PASS |
 
---
Verified with HA Helm on Rancher `v2.8-head`:
---
 
Scenario 1: Test custom name
---
1. Create a custom cluster 
2. Register 2 linux nodes with all roles
3. Register 1 windows worker node with a custom name
 
Results:
The custom name set in step 3 was properly set

---
 
Scenario 2: Test default name
---
1. Create a custom cluster 
2. Register 2 linux nodes with all roles
3. Register 1 windows worker node
 
Results: The default name was displayed was properly set
