### ISSUE TITLE
[Backport v2.7] Cannot set custom Node Name for Windows worker nodes

### ISSUE THREAD

**Issue by Jono-SUSE-Rancher** [rancher/rancher#43981]
This is a v2.7 backport of the issue https://github.com/rancher/rancher/issues/43587.

**Comment by susesgartner** [comment]
Ticket #43981 - Test Results - ✅ 
---
 
| Scenario | Test Case | Result |
|---|---|---|
| 1. | Test custom name | PASS |
| 2. | Test default name | PASS |
 
---
Verified with HA Helm on Rancher `v2.7-head`:
---
 
Scenario 1: Test custom name
---
1. Create a custom cluster 
2. Register 2 linux nodes with all roles
3. Register 1 windows worker node with a custom name
 
Results:
The custom name set in step 3 was properly set

---
 
Scenario 2: Test default name
---
1. Create a custom cluster 
2. Register 2 linux nodes with all roles
3. Register 1 windows worker node
 
Results: The default name was displayed was properly set
