### ISSUE TITLE
[Backport v2.8] vSphere CSI chart updates to upstream v3.0.3 / v1.27.3

### ISSUE THREAD

**Issue by Jono-SUSE-Rancher** [rancher/rancher#43980]
This is a backport of the vSphere CSI chart support for v2.8 based on this ticket: https://github.com/rancher/rancher/issues/43494 (incl. K8s 1.28 support)

**Comment by slickwarren** [comment]
tested on v2.8-head (44bbcc7)
getting this error on rke2 after deploying the cpi/csi charts on a 1.28.6+rke2r1 cluster
```
rancher/mirrored-sig-storage-csi-node-driver-registrar:latest
```
upon further investigation there are multiple failures with the chart install
![image](https://github.com/rancher/rancher/assets/16691014/c45c1a2e-04e6-4e1c-93e4-b91a33ec20ef)

**Comment by slickwarren** [comment]
further investigation shows that;
* this is working on 1.27
* the chart.yaml doesn't have tagged versions when using / upgrading to 1.28, likely as a result of this line in the chart.yaml:
```
 versionOverrides:
        - constraint: '>= 1.24 < 1.28'
```

**Comment by slickwarren** [comment]
one more update: everything is working as expected for 1.28 on rke1 using 2.8.3-rc2 for both a fresh install and upgrade from 1.27 -> 1.28 using the charts

**Comment by Sahota1225** [comment]
@daviswill2 - can you close this ticket as this is tracking rke1 and rke2 is tracked in another [ticket. ](44754
)
