### ISSUE TITLE
[Backport] Label deprecated setting kubeconfig-token-ttl-minutes from v3 and v1 API for future removal

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#43992]
Backport for issue https://github.com/rancher/rancher/issues/43103

**Is your feature request related to a problem? Please describe.**
Currently on an upgraded setup, the setting `kubeconfig-token-ttl-minutes` is not removed since it is a resource in the local cluster. 

**Describe the solution you'd like**
As the setting `kubeconfig-token-ttl-minutes` has been deprecated and removed, it would be nice to remove the setting from v3/v1 API on an upgraded rancher server. 

**Additional context**
https://github.com/rancher/rancher/issues/38535

**Comment by anupama2501** [comment]
Verified on an upgrade from v2.8.2 to v2.8-head `c4743333c5`
`kubeconfig-token-ttl-minutes` is not listed anymore in the settings from <RancherURL>/v3/settings and <RancherURL>/v1/management.cattle.io.settings

Verified on v2.8-head `c4743333c5`
`kubeconfig-token-ttl-minutes` is not listed anymore in the settings from <RancherURL>/v3/settings and <RancherURL>/v1/management.cattle.io.settings

**Comment by anupama2501** [comment]
Re opening the ticket for few more validations

**Comment by anupama2501** [comment]
Verified on an upgrade from v2.7.9 >> v2.8-head `c474333`
**Test1**
1. Created a rancher server on v2.7.9
2. Verified the setting `kubeconfig-token-ttl-minutes` exists
3. Upgrade rancher server to v2.8-head
4. Verified the setting exists and the following label is added on the setting: `cattle.io/unknown: "true"`

```
apiVersion: management.cattle.io/v3
customized: false
default: "960"
kind: Setting
metadata:
  labels:
    cattle.io/unknown: "true"
  name: kubeconfig-token-ttl-minutes
source: ""
value: ""
```


**Test2:**
1. Created a test setting on v2.8-head:
```
apiVersion: management.cattle.io/v3
customized: false
default: "960"
kind: Setting
metadata:
  name: test-setting
source: ""
value: ""
```
2. Restart the rancher server
3. Verified on a restart, label `cattle.io/unknown: "true"` is added.

**Comment by pmatseykanets** [comment]
# Release Notes

## Rancher General

### Behavior Changes

When starting Rancher now identifies all deprecated and unrecognized `setting` resources and adds a `cattle.io/unknown` label. These settings can be listed with `kubectl get settings -l 'cattle.io/unknown==true'`. Starting with Rancher 2.9 such settings will be removed instead.

**Comment by pmatseykanets** [comment]
Need to backport https://github.com/rancher/rancher/pull/45084 to fix the issue with `eula-agreed` setting.

**Comment by joesims22** [comment]
Verified on an upgrade from v2.7.9 -> v2.8-head id ```59bef33```

- ```eula-agreed``` setting does not have ```cattle.io/unknown``` label ✅
