### ISSUE TITLE
Provide ability to edit hosts to set labels and display labels set on the host.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#4399]
Rancher Version: v1.0.1-rc3

Create a kubernetes environment with few hosts.
Edit option on host provides a way to edit hosts using rancher-server api.
Instead we should be able to provide a way to edit hosts using kubernetes-api-server.

When we set host lables using kubectl command - ```kubectl label node <node-name> name2=value2``` ,
labels set on the host is not reflected for hosts in "Infrastructure->hosts" page.

**Comment by alena1108** [comment]
@sangeethah if you set labels on the host via Rancher, does it get reflected on k8s side?

**Comment by janeczku** [comment]
@alena1108 Doesn't work either way for me. I think we are only syncing Kubernetes pods labels but not node labels with Rancher API.

**Comment by alena1108** [comment]
Closing in favor of https://github.com/rancher/rancher/issues/5269
