### ISSUE TITLE
[BUG] System-agent proceeds with installation despite failing to download connection info

### ISSUE THREAD

**Issue by jakefhyde** [rancher/rancher#43991]
**Rancher Server Setup**
- Rancher version: 2.7.9

**Information about the Cluster**
- Kubernetes version: 1.27.6 -> 1.27.9
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Downstream (v2prov managed, custom or node driver)

**Describe the bug**

If maximum retries (5) are met attempting to download the rancher2_connection_info.json, the installation script continues with invalid data in that file causing the rancher-system-agent to fail to start.

**To Reproduce**

Block the `https://<SERVER_URL>/v3/connect/agent` endpoint from the downstream node (or for a custom cluster, run the install command once successfully, then run it again with an invalid `server-url`).

**Result**

The system agent will fail to download the connection info, but proceed with installation.

**Expected Result**

Installation fails when the connection info cannot be downloaded.

**Screenshots**

**Additional context**

SURE-7406

**Comment by Josh-Diamond** [comment]
Ticket #43991 - Test Results - ✅ 
---

Verified on a single-node instance running Rancher `v2.9-14c0fc6de37c671225edd22e07f1064b0fc53a98-head`:

| Scenario | Test Case | Result |
|---|---|---|
| 1. | Provision a downstream rke2 custom cluster; after first successful registration command, re-run command again w/ invalid server-url provided | ✅ |
| 2. | Provision a downstream rke2 custom cluster w/ an invalid server-url provided | ✅ |

---

Scenario 1 - ✅ 
1. Fresh install of Rancher `v2.9-head`
2. Provision a downstream rke2 custom cluster, and ensure it comes up `active`
3. After registration command is run successfully in Step 2, modify the server url to be invalid and re-run the command
4. Rancher logs report `could not resolve host - sleeping for 5 seconds and will try again` - this will continue until the max attempts of 4,500 is reached.
5. Once max attempts are reached, ensure the process is killed and Rancher does NOT proceed w/ moving forward in the process
6. Verified - once max attempts are reached the folllowing log is seen:
```log
[FATAL]  Error connecting to Rancher. Perhaps --ca-checksum needs to be set?
```
The cluster is still up and active and the re-registration process is killed/canceled; as expected

---

Scenario 2 - ✅ 
1. Fresh install of Rancher `v2.9-head`
2. Provision a downstream rke2 custom cluster, except modify the registration command to provide an invalid server-url
3. Rancher logs report `could not resolve host - sleeping for 5 seconds and will try again` - this will continue until the max attempts of 4,500 is reached.
5. Once max attempts are reached, ensure the process is killed and Rancher does NOT proceed w/ moving forward in the process
6. Verified - once max attempts are reached the folllowing log is seen:
```log
[FATAL]  Error connecting to Rancher. Perhaps --ca-checksum needs to be set?
```
The cluster never comes up active and the registration process is killed/canceled; the cluster object remains in Rancher, in `updating` state, ready for a valid registration command; as expected
