### ISSUE TITLE
[RFE] Remove deprecated setting kubeconfig-token-ttl-minutes from v3 and v1 API

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#44009]
The deprecated settings have already been labeled for deletion in https://github.com/rancher/rancher/issues/43103

The next step will be to perform the actual deleltion

**Comment by samjustus** [comment]
I'd like to see the precursor https://github.com/rancher/rancher/issues/43103 be fully tested before actually deleting settings.
