### ISSUE TITLE
[BUG] Rancher Monitoring components ignore configured image pull registry (failing on air-gapped environments)

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#44006]
**Rancher Server Setup**

Rancher: v2.8.0
App: rancher-monitoring
Version 103.0.0+up45.31.1
Kubernetes: v1.26.10+rke2r2

**Describe the bug**
In Rancher 2.8.0, some components from the Rancher monitoring ignore the "SystemDefaultRegistry". Therefore, the setup fails in air-gapped environments. 

Affected components (they ignore the specification completely and pull from [docker.io/rancher](http://docker.io/rancher)):

    alertmanager-rancher-monitoring-alertmanager
    prometheus-rancher-monitoring-prometheus
    rancher-monitoring-operator
    rancher-monitoring-kube-state-metrics

Additional component (builds the pull path incorrectly / docker.io is incorrectly installed (registry.de/docker.io/rancher....))

    rancher-monitoring-prometheus-node-exporter

Everything worked with version 102.0.2%2Bup40.1.2 (2.7.6). There are interesting differences in the sources on Github:

Works: https://github.com/rancher/charts/blob/release-v2.7/charts/rancher-monitoring/102.0.2%2Bup40.1.2/templates/prometheus/prometheus.yaml#L34

Faulty: https://github.com/rancher/charts/blob/release-v2.8/charts/rancher-monitoring/103.0.0%2Bup45.31.1/templates/prometheus/prometheus.yaml#L34

In the new version, the image is apparently not referenced to >template "system_default_registry< and this variable should contain the setting with the private registry.

See: https://github.com/rancher/charts/blob/release-v2.8/charts/rancher-monitoring/103.0.0%2Bup45.31.1/templates/_helpers.tpl#L2

**Comment by alexandreLamarre** [comment]
The workaround without the proposed fix, i.e. for chart versions < `103.0.3+up45.31.1` is to set rancher-monitoring's values.yaml value [`global.imageRegistry`](https://github.com/rancher/charts/blob/38aed06f77002690b4857d84e79252bed828dc82/charts/rancher-monitoring/103.0.0%2Bup45.31.1/values.yaml#L773)  to the air-gapped registry, whose value would be set in the value [`global.cattle.systemDefaultRegistry`](https://github.com/rancher/charts/blob/38aed06f77002690b4857d84e79252bed828dc82/charts/rancher-monitoring/103.0.0%2Bup45.31.1/values.yaml#L734)

**Comment by jiaqiluo** [comment]
The fix can be validated in [v2.8.1-rc2 ](https://github.com/rancher/rancher/releases/tag/v2.8.1-rc2)

**Comment by jiaqiluo** [comment]
The fix is available in https://github.com/rancher/rancher/releases/tag/v2.8.1-rc3

**Comment by pankajsqe** [comment]
verified issue #44006 on V2.8.1-rc3
	1. Non Air-gap monitoring setup : Passed
	2. Air-gap setup monitoring      : Passed
	3. Air gap upgrade monitoring (v2.7.0 - v2.8.1-rc3) : Passed
	
	
All 5 components mentioned below are pulling images from my private registry
	
- alertmanager-rancher-monitoring-alertmanager
- prometheus-rancher-monitoring-prometheus
- rancher-monitoring-operator
- rancher-monitoring-kube-state-metrics
- rancher-monitoring-prometheus-node-exporter

**Comment by bmdepesa** [comment]
We also tested upgrading a failed installation of monitoring from the previous chart version where images were not pulling from the private registry.
