### ISSUE TITLE
User is taken to "Services" page when activating/deactivating a host.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#4400]
Rancher Version: Build from master

Create kubernetes environment with few host.
Add few services.

Go to Infratructure->Hosts page and decativate any host.
User is taken to "Services" page.
Then same behavior is also seen when activating a host.

**Comment by vincent99** [comment]
This is from the k8s services readiness state being re-checked and then redirecting when we don't need to.. Should be fixed in 1.4

**Comment by tfiduccia** [comment]
Version - master 1/11
Verified fixed
