### ISSUE TITLE
[Backport] OIDCConfig.Scopes struct field tag is not compatible with reflect.StructTag.Get

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#44016]
Backport: https://github.com/rancher/rancher/issues/43668

**Describe the bug**

There is  typo in `OIDCConfig.Scopes` struct field tag
https://github.com/rancher/rancher/blob/2581a956996c948945dac34ca159c32ce556a6bd/pkg/apis/management.cattle.io/v3/authn_types.go#L457

```
struct field tag `json:"scope", norman:"required,notnullable"` not compatible with reflect.StructTag.Get: key:"value" pairs not separated by spaces
```

It was there since the originating commit a2a501c6d2270837ee17d8d139b489ce324ec46e

**Comment by samjustus** [comment]
@pmatseykanets should this go in the next 2.8 release? its flagged for the next-next one, but i dont see why we cant include it? cc @anupama2501

**Comment by pmatseykanets** [comment]
@samjustus I don't see why not if it was tested.

**Comment by dasarinaidu** [comment]
Regression tests validated and looks good, No new issues reported and closing this card.
