### ISSUE TITLE
[Backport] Create crtb with steve api(v1) is throwing 404 instead of 422 when user miss a field 

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#44022]
Backport of https://github.com/rancher/rancher/issues/42788

**CRUD : Create crtb with steve api(v1) is throwing 404 instead of 422 when user miss a field**

When user missing a field (Ex: metadata) : Unable to create a crtb with steve API(v1) end point. Getting 404 exception. instead of 422

**Steps:**

Provision rancher

1. Create a downstream cluster
2. Try to create a CRTB with Steve API(v1)
3. Endpoint : {{URL}}/v1/management.cattle.io.clusterroletemplatebindings
4. Make sure to miss metadata field.

Method : POST
```
Body :
{"clusterName":"c-m-nfft6kdm","metadata":"","roleTemplateName":"cluster-member","userPrincipalName":"local://u-wgtj6"}

OR
{"type": "clusterRoleTemplateBinding", "clusterName": "dastest3", "roleTemplateName": "cluster-member", "userPrincipalName": "local://u-wgtj6"}

OR
{"type":"clusterRoleTemplateBinding","clusterId":"c-m-nfft6kdm","roleTemplateId":"cluster-member", "userPrincipalId":"local://u-wgtj6"}
```

**Actual Result:**
Getting 404 exception
{
"type": "error",
"links": {},
"code": "NotFound",
"message": "the server could not find the requested resource",
"status": 404,
"type": "error"
}

Expected: 
1. The crtb is not created and system throwing an exception with 404 instead of 422 error code.
2. Error code 422 should send appropriate error message, it should indicate that a required field was missing would be more appropriate

Note: Validated the endpoint from Postman and UI but getting the same error.

SURE-7719

**Comment by gehrkefc** [comment]
## How to reproduce / test

Please refer to this comment in issue 42823:

https://github.com/rancher/rancher/issues/42823#issuecomment-2322482575

**Comment by brudnak** [comment]
<a name="top"></a>

<details>
    <summary>🧪 Test Environment Details... CLICK TO EXPAND! ⬅️</summary>


| Component                        | Version / Type                                                                     |
| -------------------------------- | ---------------------------------------------------------------------------------- |
| Rancher version starting         | v2.8.8                                                                             |
| Rancher version upgraded         | v2.8-257fe744e1778b834fa2ebaf0b58c7f1c5a20798-head                                 |
| Rancher commit link              | https://github.com/rancher/rancher/commit/257fe744e1778b834fa2ebaf0b58c7f1c5a20798 |
| Installation option              | Helm (high availability)                                                           |
| RKE binary version used          | v1.5.13                                                                            |
| If Helm Chart k8s cluster        | v1.28.13                                                                           |
| Cert Details                     | external tls `aws acm`                                                             |
| Docker version                   | 20.10.7, build f0df350                                                             |
| Authentication providers enabled | local                                                                              |
| Logged in user role              | admin / standard user                                                              |
| Browser type                     | Opera GX                                                                           |
| Browser version                  | LVL6 (core: 113.0.5230.75) (x86_64)                                                |
| Webhook version                  | rancher/rancher-webhook:v0.4.11                                                    |

</details>

### 🧪  Test Cases

| \#  | Priority | Description & Link                          | PASS/FAIL |
| --- | -------- | ------------------------------------------- | --------- |
| 1   | P0       | [Expect 422 (invalid POST body#1)](#test-1) | ✅ PASS    |
| 2   | P0       | [Expect 422 (invalid POST body#2)](#test-2) | ✅ PASS    |
| 3   | P0       | [Expect 422 (invalid POST body#3)](#test-3) | ✅ PASS    |
| 4   | P0       | [Create valid CRTB](#test-4)                | ✅ PASS    |
| 5   | P0       | [Read valid CRTB](#test-5)                  | ✅ PASS    |
| 6   | P0       | [Update valid CRTB](#test-6)                | ✅ PASS    |
| 7   | P0       | [Delete valid CRTB](#test-7)                | ✅ PASS    |
| 8   | P0       | [Run RBAC automated tests](#test-8)         | ✅ PASS    |
| 9   | P0       | [Run RBAC/CRTB automated tests](#test-9)    | ✅ PASS    |
| 10  | P0       | [Upgrade](#test-10)                         | ✅ PASS    |
| 11  | P0       | [(kubectl) Create valid CRTB](#test-11)     | ✅ PASS    |
| 12  | P0       | [(kubectl) Read valid CRTB](#test-12)       | ✅ PASS    |
| 13  | P0       | [(kubectl) Update valid CRTB](#test-13)     | ✅ PASS    |
| 14  | P0       | [(kubectl) Delete valid CRTB](#test-14)     | ✅ PASS    |

<details>
    <summary>🚨 14 test cases... CLICK TO EXPAND! (For table links to work) ⬅️</summary>

<br>

# 1 / Expect 422 (invalid POST body#1) Status: ✅ PASS 

<a name="test-1"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 1 details... Click to expand</summary>

**Test Steps for Validation**

1. `POST` request to `{{rancherURL}}/v1/management.cattle.io.clusterroletemplatebindings`
2. Body:

    ```json
    {
      "clusterName": "local",
      "metadata": "",
      "roleTemplateName": "cluster-owner",
      "userPrincipalName": "local://{{createUserID}}"
    }
    ```

**✅ Expected Outcome**

Expected a 422

**✅ Actual Outcome**

Receiver 422 with:

```json
{
  "type": "error",
  "links": {},
  "code": "InvalidBodyContent",
  "message": "metadata.namespace is required",
  "status": 422
}
```

</details>

<hr>

# 2 / Expect 422 (invalid POST body#2) Status: ✅ PASS 

<a name="test-2"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 2 details... Click to expand</summary>

**Test Steps for Validation**

1. `POST` request to `{{rancherURL}}/v1/management.cattle.io.clusterroletemplatebindings`
2. Body:

    ```json
    {
      "clusterName": "local",
      "metadata": "",
      "roleTemplateName": "cluster-owner",
      "userPrincipalName": "local://{{createUserID}}"
    }
    ```

**✅ Expected Outcome**

Expected a 422

**✅ Actual Outcome**

Receiver 422 with:

```json
{
  "type": "error",
  "links": {},
  "code": "InvalidBodyContent",
  "message": "metadata.namespace is required",
  "status": 422
}
```


</details>

<hr>

# 3 / Expect 422 (invalid POST body#3) Status: ✅ PASS 

<a name="test-3"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 3 details... Click to expand</summary>

**Test Steps for Validation**

1. `POST` request to `{{rancherURL}}/v1/management.cattle.io.clusterroletemplatebindings`
2. Body:

    ```json
    {
      "type": "clusterRoleTemplateBinding",
      "clusterId": "local",
      "roleTemplateId": "cluster-owner",
      "userPrincipalId": "local://{{createUserID}}"
    }
    ```

**✅ Expected Outcome**

Expected a 422

**✅ Actual Outcome**

Receiver 422 with:

```json
{
  "type": "error",
  "links": {},
  "code": "InvalidBodyContent",
  "message": "metadata.namespace is required",
  "status": 422
}
```

</details>

<hr>

# 4 / Create valid CRTB Status: ✅ PASS 

<a name="test-4"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 4 details... Click to expand</summary>

**Test Steps for Validation**

1. Create a valid CRTB
2. `POST` request to `{{rancherURL}}/v1/management.cattle.io.clusterroletemplatebindings`
3. Body:

    ```json
    {
      "clusterName": "local",
      "metadata": {
        "generateName": "bruno-",
        "namespace": "local"
      },
      "roleTemplateName": "cluster-owner",
      "userPrincipalName": "local://{{createUserID}}"
    }
    ```

4. Ensure that the user has been granted the appropriate permission level

**✅ Expected Outcome**

CRTB to be created and permissions to function as expected

**✅ Actual Outcome**

CRTB created and permission level is working as expected


</details>

<hr>

# 5 / Read valid CRTB Status: ✅ PASS 

<a name="test-5"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 5 details... Click to expand</summary>

**Test Steps for Validation**

1. Send `GET` request to `{{rancherURL}}/v1/management.cattle.io.clusterroletemplatebindings/local/{{crtbName}}`

**✅ Expected Outcome**

Expect the specified CRTB returned 

**✅ Actual Outcome**

The specific CRTB was returned


</details>

<hr>

# 6 / Update valid CRTB Status: ✅ PASS

<a name="test-6"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 6 details... Click to expand</summary>

**Test Steps for Validation**

1. `PUT` request to `{{rancherURL}}/v1/management.cattle.io.clusterroletemplatebindings/local/{{crtbName}}`
2. Body:

    ```json
    {
      "apiVersion": "management.cattle.io/v3",
      "kind": "ClusterRoleTemplateBinding",
      "clusterName": "local",
      "metadata": {
        "resourceVersion": "{{crtbResVersion}}",
        "namespace": "local",
        "name": "{{crtbName}}",
        "labels": {
          "hello": "dadfish"
        }
      },
      "roleTemplateName": "cluster-owner",
      "userPrincipalName": "local://{{createUserID}}",
      "userName": "{{createUserID}}"
    }
    ```



**✅ Expected Outcome**

`PUT` to succeed

**✅ Actual Outcome**

`PUT` is successful

</details>

<hr>

# 7 / Delete valid CRTB Status: ✅ PASS

<a name="test-7"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 7 details... Click to expand</summary>

**Test Steps for Validation**

1. `DELETE` request to `{{rancherURL}}/v1/management.cattle.io.clusterroletemplatebindings/local/{{crtbName}}`
2. Ensure that the user loses the access that the CRTB was granting

**✅ Expected Outcome**

`DELETE` success and for the user to lose the access the CRTB was providing

**✅ Actual Outcome**

CRTB was deleted and the user lost access it was granting

</details>

<hr>

# 8 / Run RBAC automated tests Status: ✅ PASS

<a name="test-8"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 8 details... Click to expand</summary>

**Test Steps for Validation**

1. Run these tests: `https://github.com/rancher/rancher/blob/release/v2.9/tests/v2/validation/rbac/rbac_test.go`

**✅ Expected Outcome**

Expecting a pass

**✅ Actual Outcome**

61 of 61 tests pass 

</details>

<hr>

# 9 / Run RBAC/CRTB automated tests Status: ✅ PASS

<a name="test-9"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 9 details... Click to expand</summary>

**Test Steps for Validation**

1. Run these tests: `https://github.com/rancher/rancher/blob/release/v2.9/tests/v2/validation/rbac/crtb/crtb_create_steve_test.go`


**✅ Expected Outcome**

Expecting a pass

**✅ Actual Outcome**

9 of 9 tests pass

</details>

<hr>

# 10 / Upgrade Status: ✅ PASS
<a name="test-10"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 10 details... Click to expand</summary>

**Test Steps for Validation**

1. Repeat test cases 1 through 9 on an upgraded Rancher

**✅ Expected Outcome**

For all tests to pass

**✅ Actual Outcome**

All tests passing on an upgraded Rancher

</details>

<hr>

# 11 / (kubectl) Create valid CRTB Status: ✅ PASS

<a name="test-11"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 11 details... Click to expand</summary>

**Test Steps for Validation**

1. As an admin, create a downstream cluster.
2. As an admin, create a standard user with the name `user1`.
3. Use `kubectl apply -f` command as an admin to create a CRTB ClusterRoleTemplateBinding for `user1`.
4. Use the following yaml:

    ```yaml
    apiVersion: management.cattle.io/v3
    clusterName: c-xxxxx # replace with your cluster name
    kind: ClusterRoleTemplateBinding
    metadata:
      namespace: c-xxxxx # replace with your cluster name
      name: cluster-owner
    roleTemplateName: cluster-owner
    userName: u-xxxxx # replace with your standard user id
    userPrincipalName: local://u-xxxxx # replace with your standard user id
    ```

5. Execute `kubectl apply -f` command again as an admin.
6. Log into the Rancher UI as `user1`.
7. Verify that `user1` has cluster owner access to the downstream cluster.
8.  Create a deployment in the default namespace, check the logs, and then delete the deployment.
    

#### ✅ Expected Outcome

Access was anticipated to be granted successfully.

#### ✅ Actual Outcome

As expected, access was granted successfully.


</details>

<hr>

# 12 / (kubectl) Read valid CRTB Status: ✅ PASS

<a name="test-12"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 12 details... Click to expand</summary>

**Test Steps for Validation**

1. After creating the CRTB with kubectl ensure that you can get/read it
2. Run: `kubectl get clusterroletemplatebindings cluster-owner -n c-m-rhmwsvc5 -o yaml`

**✅ Expected Outcome**

Expect to get the yaml output of the CRTB that was previously created

**✅ Actual Outcome**

Getting the expected CRTB yaml output

</details>

<hr>

# 13 / (kubectl) Update valid CRTB Status: ✅ PASS

<a name="test-13"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 13 details... Click to expand</summary>

**Test Steps for Validation**

1. As an admin, instantiate a downstream cluster.
2. Using the admin account, establish a standard user, hereby referred to as `user1`.
3. With the `kubectl apply -f` command, create a CRTB ClusterRoleTemplateBinding for `user1`.
4. Utilize the below yaml:

    ```yaml
    apiVersion: management.cattle.io/v3
    clusterName: c-xxxxx # Replace with your cluster name
    kind: ClusterRoleTemplateBinding
    metadata:
      namespace: c-xxxxx # Replace with your cluster name
      name: cluster-owner
    roleTemplateName: cluster-owner
    userName: u-xxxxx # Replace with your standard user id
    userPrincipalName: local://u-xxxxx # Replace with your standard user id
    ```

5. Run the `kubectl apply -f` command once more as an admin.
6. Access the Rancher UI by logging in as `user1`.
7. Ensure that `user1` possesses cluster owner access to the downstream cluster.
8.  Generate a deployment in the default namespace, inspect the logs, and subsequently delete the deployment.
9.  Proceed to edit the previously created CRTB.
10. Use `kubectl edit clusterroletemplatebinding cluster-owner -n c-qg584`.
11. Introduce a label `env: prod`.

    ```yaml
    apiVersion: management.cattle.io/v3
    clusterName: c-xxxxx # Replace with your cluster name
    kind: ClusterRoleTemplateBinding
    metadata:
      namespace: c-xxxxx # Replace with your cluster name
      name: cluster-owner
      labels:
        env: prod
    roleTemplateName: cluster-owner
    userName: u-xxxxx # Replace with your standard user id
    userPrincipalName: local://u-xxxxx # Replace with your standard user id
    ```

12. Save the changes using `:wq`.
13. Validate that the save was successful and the added label persists.

**✅ Expected Outcome**

**✅ Actual Outcome**


</details>

<hr>

# 14 / (kubectl) Delete valid CRTB Status: ✅ PASS

<a name="test-14"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 14 details... Click to expand</summary>

**Test Steps for Validation**

1. Utilize kubectl to remove the CRTB: `kubectl delete clusterroletemplatebinding cluster-owner -n c-m-rhmwsvc5`.
2. Proceed to log into the Rancher UI as `user1`.
3. Validate that `user1` no longer has the previously granted permissions.

**✅ Expected Outcome**

`user1` should have lost permissions to the downstream cluster, as intended.

**✅ Actual Outcome**

As anticipated, `user1` has lost permissions to the downstream cluster.

</details>

<hr>

</details>
