### ISSUE TITLE
unable to restore etcd snapshot

### ISSUE THREAD

**Issue by wuwo1952368901** [rancher/rancher#44038]
Hello,
I’m unable to upgrade custom RKE2 1.24 cluster to any 1.25 version using Rancher GUI (v2.8.0). It returns:
“Unable to restore etcd snapshot – recorded Kubernetes version on snapshot was <= v1.25.0 and current cluster version was v1.25.0 or newer”.
Has anyone run into the same problem?
Upgrade of the same cluster from 1.24 to 1.26  1.27 works.

**Comment by snasovich** [comment]
@wuwo1952368901 , please note Rancher v2.8.0 no longer supports K8s 1.23 and 1.24, see release notes https://github.com/rancher/rancher/releases/tag/v2.8.0
> Kubernetes v1.23 and v1.24 are no longer supported. Before you upgrade to Rancher v2.8.0, make sure that all clusters are running Kubernetes v1.25 or later. See https://github.com/rancher/rancher/issues/42828.
