### ISSUE TITLE
[Backport v2.7] [BUG] Fleet-agent panics on k3s node driver cluster and doesn't recover

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#44049]
Backport of https://github.com/rancher/rancher/issues/43012 for 2.7.x release line.
Also tracked in https://github.com/rancher/fleet/issues/2062 - this `rancher/rancher` issue is created for additional tracking.

Note this issue is believed to be a regression in Rancher 2.7.9 compared to 2.7.6 per versions of Fleet referenced by these releases.

**Comment by olblak** [comment]
I am removing this issue from the Fleet board as duplicated with https://github.com/rancher/fleet/issues/2062
The associated pull request https://github.com/rancher/fleet/pull/2063 is now merged and available in the release candidate [v0.8.2-rc.3](https://github.com/rancher/fleet/releases/tag/v0.8.2-rc.3)

The next step is for https://github.com/rancher/rancher/pull/44069 to merged and only then we'll be able to validate in Rancher

**Comment by gaktive** [comment]
Looks like PR 44069 is merged so this sounds like it's ready to test. Let me know if I'm wrong.
