### ISSUE TITLE
[Backport 2.7] rancher- rancher-webhook k8s 1.27 chart support

### ISSUE THREAD

**Issue by tomleb** [rancher/rancher#44066]
This issue is to implement the chart changes & perform the testing required to upgrade to k8s 1.27. Please perform below steps. 

- [ ] Check whether the chart has any references to the below deprecated features of k8s 1.27. You can find information about deprecated APIs here on [Kubernetes Deprecation guide](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-27).

**storage.k8s.io/v1beta1** API version of **CSIStorageCapacity**
 

- [ ] Update kube-version annotation in Chart.yaml. catalog.cattle.io/kube-version: '>= 1.23.0-0 < 1.28.0-0'

Note: If this is an upstream chart and if the upstream chart doesn't support k8s 1.27 then do not update the kube-version annotation or update the k8s version accordingly.

- [ ] Perform below tests

- Fresh install/uninstall/upgrade/downgrade of the charts on K8s 1.27 provisioned on Rancher. Test the chart functionality.
(Please refer to the https://github.com/rancher/rancher/issues/41395 to know what testing was done for k8s 1.26 upgrade for your chart)
- Provision rancher on k8s 1.26 or lesser
- Install chart on this cluster
- Upgrade this cluster in rancher to k8s 1.27
- Make sure the existing chart and the app is functional after cluster upgrade

**Comment by brudnak** [comment]
# ✅ PASSED

## Validation Environment


| Component                        | Version / Type                                                                     |
| -------------------------------- | ---------------------------------------------------------------------------------- |
| Rancher version starting         | 2.7.10                                                                             |
| RAncher version upgraded         | v2.7.11-0922944c477bfaa1015e8bee71de8d5a7ce46a5b-head                              |
| Rancher commit link              | https://github.com/rancher/rancher/commit/0922944c477bfaa1015e8bee71de8d5a7ce46a5b |
| Installation option              | Helm (high availability)                                                           |
| If Helm Chart k8s cluster        | v1.26.13+k3s2                                                                      |
| Cert Details                     | external tls `aws acm`                                                             |
| k3s ha external db               | Aurora MySQL 5.7.mysql_aurora.2.11.1                                               |
| Helm version                     | v2.16.8-rancher2                                                                   |
| Downstream cluster type          | AWS EKS                                                                            |
| Downstream K8s version           | starting 1.26 ==> upgraded to 1.27                                                 |
| Authentication providers enabled | local                                                                              |
| Logged in user role              | admin / standard user                                                              |
| Browser type                     | Opera GX                                                                           |
| Browser version                  | LVL5 (core: 106.0.4998.76) (x86_64)                                                |
| Dashboard                        | release-2.7 514de6b98                                                              |
| Webhook version                  | rancher/rancher-webhook:v0.3.7-rc2                                                 |


<a name="top"></a>

### :muscle: Test Cases

| \#  | Priority | Description & Link                           | PASS/FAIL |
| --- | -------- | -------------------------------------------- | --------- |
| 1   | P0       | [Fresh Install Rancher - k8s v1.27](#test-1) | ✅ PASS    |
| 2   | P0       | [Upgrade - k8s 1.26 to 1.27](#test-2)        | ✅ PASS    |

<details>
    <summary>🚨 2 test cases... CLICK TO EXPAND! (For table links to work) ⬅️</summary>

<br>

# 1 / Fresh Install Rancher - k8s v1.27 Status: ✅ PASS

<a name="test-1"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 1 details... Click to expand</summary>

**Test Steps for Validation**

1. Create a downstream cluster with k8s 1.27 (EKS)
2. Verify that rancher-webhook is installed on both local and downstream clusters
3. Verify that the version of the webhook is as expected on both local and downstream clusters.
4. Verify kube-version annotation in the webhook chart's yaml has: catalog.cattle.io/kube-version: '>= 1.23.0-0 < 1.28.0-0'
5. Verify that there are no errors in the rancher-webhook logs
6. Verify count in local cluster with `kubectl get validatingwebhookconfigurations.admissionregistration.k8s.io rancher.cattle.io`
   1. response: `rancher.cattle.io   15         69m`
   2. passing expected count
7. Verify count in downstream cluster with `kubectl get validatingwebhookconfigurations.admissionregistration.k8s.io rancher.cattle.io`
   1. response: `rancher.cattle.io   7          45m`
   2. passing expected count
8. Create a restricted admin user
9. Login as restricted admin
10. Attempt to edit the admin role, while logged in as restricted admin
11. Attempt to set admin to "Yes: Default role for new users"
    1.  Blocked by webhook as expected

**✅ Expected Outcome**

For Rancher webhook to work with k8s 1.27. For the expected version to be installed and for there to be no errors present. For webhook P0 checks to pass.

**✅ Actual Outcome**

Webhook checks are passing as expected.

</details>

<hr>

# 2 / Upgrade - k8s 1.26 to 1.27 Status: ✅ PASS

<a name="test-2"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 2 details... Click to expand</summary>

**Test Steps for Validation**

1. Start with Rancher on 2.7.10
2. Create a downstream EKS cluster with k8s 1.26
3. Upgrade Rancher to v2.7.11-head
4. Upgrade the downstream EKS cluster from 1.26 to ==> 1.27
5. Verify that rancher-webhook is upgraded on both local and downstream clusters
6. Verify that the version of the webhook is as expected on both local and downstream clusters. `v0.3.7-rc2`
7. Verify kube-version annotation in the webhook chart's yaml has: catalog.cattle.io/kube-version: '>= 1.23.0-0 < 1.28.0-0'
8. Verify that there are no errors in the rancher-webhook logs
9. Verify count in local cluster with `kubectl get validatingwebhookconfigurations.admissionregistration.k8s.io rancher.cattle.io`
   1. response: `rancher.cattle.io   15         69m`
   2. passing expected count
10. Verify count in downstream cluster with `kubectl get validatingwebhookconfigurations.admissionregistration.k8s.io rancher.cattle.io`
   1. response: `rancher.cattle.io   7          45m`
   2. passing expected count
11. Create a restricted admin user
12. Login as restricted admin
13. Attempt to edit the admin role, while logged in as restricted admin
14. Attempt to set admin to "Yes: Default role for new users"
    1.  Blocked by webhook as expected

**✅ Expected Outcome**

For Rancher webhook to work with k8s 1.27 after upgrade. For the expected version to be installed and for there to be no errors present. For webhook P0 checks to pass.

**✅ Actual Outcome**

Webhook checks are passing as expected.


</details>

<hr>

</details>
