### ISSUE TITLE
Ability to pass in proxy values to containers

### ISSUE THREAD

**Issue by donny-dont** [rancher/rancher#4407]
Currently we have some applications we're running on Rancher that require access to external services. They are behind a proxy so the proxy values need to be set. Currently we apply these values within a catalog entry. However this requires the user to know those values and those values could possibly change.

This would take the host's proxy values and then pass those in as environment variables to the container
- HTTP_PROXY
- HTTPS_PROXY
- NO_PROXY
- http_proxy
- https_proxy
- no_proxy

We found when doing builds within Drone that both shout case and snake case were required.

A potential solution would be to add a new rancher label `use_proxy: true` that would tell Rancher to pass in the proxy values of the host.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
