### ISSUE TITLE
[v2.7] KDM Update for K8s January patch release

### ISSUE THREAD

**Issue by vardhaman22** [rancher/rancher#44087]
# KDM Updates
TO BE RELEASED: **OOB post v2.7.10** 

| New Kubernetes Version | Min Rancher Version | Min RKE Version |
| ---------------------- | ------------------- | --------------- |
| 1.26.13-rancher1-1      | 2.7.5-patch0                 | 1.4.6-rc0             |

### Rancher System Images & Add-ons
**_Note: Please update system images and add-ons in the template as needed._**

TBD

# Developer Changelog
- Add templates for new K8s versions. If a template that hasn't been released yet already exists, update it in place.
- Update the default K8s version, and add or update the version information (`MinRancherVersion` and `MinRKEVersion`) in [k8s_version_info.go](https://github.com/rancher/kontainer-driver-metadata/blob/dev-v2.6/rke/k8s_version_info.go) for new K8s versions if needed (Use table from above).
- Confirm versions for system images, add-on templates are correct using versioning reference table from below (expand details to view the table). Update the table if new versions are introduced.
- Confirm add-on template version constraints in [template.go](https://github.com/rancher/kontainer-driver-metadata/blob/dev-v2.5/rke/templates/templates.go#L78) are correct using versioning reference table from below (expand details to view the table). Update the table if needed.

# Versioning Reference
<details>
<summary>
Expand for system images & add-on templates versioning table
</summary>
</br>

**_Note: Truncated repository names with a `*` indicates there are multiple images with that prefix. All repository names that match a truncated prefix should be checked for the same version stated in the table._**
**_For example: `rancher/weave-*` matches `weaveworks/weave-kube` and `weaveworks/weave-npc`, and they should both have the same version._**

## v1.26.13-rancher1-1
| Repository                                               | Tag                   |
| -------------------------------------------------------- | --------------------- |
| rancher/mirrored-coreos-etcd                             | v3.5.10     |
| rancher/hyperkube                                        | v1.26.13-rancher1      |
| rancher/rke-tools                                        | v0.1.96              |
| rancher/mirrored-k8s-dns-*                               | 1.22.28                |
| rancher/mirrored-cluster-proportional-autoscaler         | 1.8.6                 |
| rancher/flannel-cni                                      | v0.3.0-rancher8       |
| rancher/mirrored-flannel-flannel                                      | v0.21.4      |
| rancher/mirrored-calico-*                                | v3.26.3              |
| weaveworks/weave-*                                       | 2.8.1                 |
| noiro/* (All ACI images)                                 | 6.0.3.2.81c2369       |
| rancher/mirrored-pause                                   | 3.7                 |
| rancher/nginx-ingress-controller                         | nginx-1.9.4-rancher1 |
| rancher/mirrored-nginx-ingress-controller-defaultbackend | 1.5-rancher1          |
| rancher/mirrored-jettech-kube-webhook-certgen            | v20231011-8b53cabe0              |
| rancher/mirrored-metrics-server                          | v0.6.3              |
| rancher/mirrored-coredns-coredns                         | 1.9.4                 |
| rancher/mirrored-cluster-proportional-autoscaler         | 1.8.6                 |
| rancher/mirrored-k8s-dns-node-cache                      | 1.22.28                |

| Add-on Name   | Add-on Template Version Constraint |
| ------------- | ---------------------------------- |
| Calico        | calicov3261Rancher2                         |
| Canal         | canalv3261Rancher2                          |
| Flannel       | flannelv0214                       |
| CoreDNS       | coreDnsv183Rancher2                        |
| KubeDNS       | kubeDnsv116                        |
| MetricsServer | metricsServerv061                  |
| Weave         | weavev122                          |
| Aci           | aciv6032                            |
| NginxIngress  | nginxIngressv194Rancher1                  |
| Nodelocal     | nodelocalv121                      |

</details>

**Comment by chiukapoor** [comment]
Intermittently, `fleet-agent` panics on the k8s v1.28.6 node driver cluster and fails to recover. The related issue is documented here: https://github.com/rancher/rancher/issues/43012

For a workaround, please refer to: https://github.com/rancher/rancher/issues/43012#issuecomment-1926216418

**Comment by rishabhmsra** [comment]
**Fresh install checks - PASS**

- On rancher version v2.7.10-rc7, KDM pointing to dev-v2.7-2024-01-patches branch, cluster creation succeeds for v1.26.13-rancher1-1 on all network providers - canal/flannel/weave/calico
- Network checks look good
- Canal network checks look good

----------

**Upgrade checks - PASS**

- On rancher v2.7.10-rc7, KDM pointing to release-v2.7, cluster creation succeeds for k8s v1.26.11-rancher2-2 version with all network providers.
- Pre-upgrade checks look good.
- KDM points to dev-v2.7-2024-01-patches branch.
- Upgraded cluster to k8s versions - v1.26.13-rancher1-1.
- Post upgrade checks look good.

----------

**RKE default k8s version - PASS**

dev-v2.7-2023-07-patches should have the default as v1.26.13-rancher1-1
```
"RKEDefaultK8sVersions": {
  "0.3": "v1.16.3-rancher1-1",
  "default": "v1.26.13-rancher1-1"
 }
```
-------------

**Minimum rancher version checks - PASS**

- On rancher v2.7.5 with KDM pointing to dev-v2.7-2023-07-patches branch, cluster creation succeeds for v1.26.13-rancher1-1 versions with all network providers.
- Network checks look good.
- Canal network checks look good.
