### ISSUE TITLE
Add kubernetes 1.27 support to backup restore operator

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#44096]
Parent issue: https://github.com/rancher/rancher/issues/44098

Backport of https://github.com/rancher/rancher/issues/41786

This issue is to implement the chart changes & perform the testing required to upgrade to k8s 1.27. Please perform below steps. 

- [x] Check whether the chart has any references to the below deprecated features of k8s 1.27. You can find information about deprecated APIs here on [Kubernetes Deprecation guide](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-27).

**storage.k8s.io/v1beta1** API version of **CSIStorageCapacity**
 

- [x] Update kube-version annotation in Chart.yaml. catalog.cattle.io/kube-version: '>= 1.23.0-0 < 1.28.0-0'

Note: If this is an upstream chart and if the upstream chart doesn't support k8s 1.27 then do not update the kube-version annotation or update the k8s version accordingly.

- [ ] Perform below tests

- [x] - Fresh install/uninstall/upgrade/downgrade of the charts on K8s 1.27 provisioned on Rancher. Test the chart functionality.
- [x] (Please refer to the https://github.com/rancher/rancher/issues/41395 to know what testing was done for k8s 1.26 upgrade for your chart)
- [x] - Provision rancher on k8s 1.26 or lesser
- [x] - Install chart on this cluster
- [x] - Upgrade this cluster in rancher to k8s 1.27
- [x] - Make sure the existing chart and the app is functional after cluster upgrade

**Comment by MKlimuszka** [comment]
https://github.com/rancher/charts/pull/3347

**Comment by nickwsuse** [comment]
Verified on v2.7.11-alpha3 & BRO v102.0.3+up3.1.3-rc6 ✅ 
---
Migration, in-place restore, and upgrade rollback all work as expected with k8s v1.27
