### ISSUE TITLE
[Backport]  rancher-alerting-drivers k8s 1.27 chart support

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#44099]
Backport of https://github.com/rancher/rancher/issues/41785

This issue is to implement the chart changes & perform the testing required to upgrade to k8s 1.27. Please perform below steps. 

- [ ] Check whether the chart has any references to the below deprecated features of k8s 1.27. You can find information about deprecated APIs here on [Kubernetes Deprecation guide](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-27).

**storage.k8s.io/v1beta1** API version of **CSIStorageCapacity**
 

- [ ] Update kube-version annotation in Chart.yaml. catalog.cattle.io/kube-version: '>= 1.23.0-0 < 1.28.0-0'

Note: If this is an upstream chart and if the upstream chart doesn't support k8s 1.27 then do not update the kube-version annotation or update the k8s version accordingly.

- [ ] Perform below tests

- Fresh install/uninstall/upgrade/downgrade of the charts on K8s 1.27 provisioned on Rancher. Test the chart functionality.
(Please refer to the https://github.com/rancher/rancher/issues/41395 to know what testing was done for k8s 1.26 upgrade for your chart)
- Provision rancher on k8s 1.26 or lesser
- Install chart on this cluster
- Upgrade this cluster in rancher to k8s 1.27
- Make sure the existing chart and the app is functional after cluster upgrade

**Comment by pankajsqe** [comment]
Pass Verified in rancher v2.7.11-head. Below are the test cases.

**Local Cluster**
1. Provisioned Rancher with local k8s v1.26.9+k3s1 cluster.
2. Installed rancher-monitoring:102.0.2+up40.1.2
3. Installed rancher-alerting-drivers:102.1.1
4. Configured monitoring and alerting to monitor and send alerts on telegram
5. Upgraded Local cluster to k8s v1.27.9+k3s1
6. Verified configured monitoring still sending alerts.
7. Monitoring passed p0 test cases.
8. Monitoring outbound links, grafana, prometheus targets function properly - ie, no dead links.
9. Chart annotations are correct.
10. Uninstall Monitoring and Alert app successfully on local cluster and deleted respective namespaces.
11. Fresh install monitoring and alert app on K8s v1.27.9
12. Configured monitoring and alerting to monitor and send alerts on telegram on fresh installation of app.
13. Verified configured monitoring still sending alerts.
14. Monitoring outbound links, grafana, prometheus targets function properly - ie, no dead links.

**Downstream Cluster**
1. Provisioned downstream k8s v1.26.9 cluster.
2. Installed rancher-monitoring:102.0.2+up40.1.2
3. Installed rancher-alerting-drivers:102.1.1
4. Configured monitoring and alerting to monitor and send alerts on telegram
5. Upgraded downstream cluster to k8s v1.27.9
6. Verified configured monitoring still sending alerts.
7. Monitoring passed p0 test cases.
8. Monitoring outbound links, grafana, prometheus targets function properly - ie, no dead links
9. Chart annotations are correct.
10. Uninstall Monitoring and Alert app successfully on downstream cluster and deleted respective namespaces.
11.  Fresh install monitoring and alert app on K8s v1.27.9
12. Configured monitoring and alerting to monitor and send alerts on telegram on fresh installation of app.
13. Verified configured monitoring still sending alerts.
14. Monitoring outbound links, grafana, prometheus targets function properly - ie, no dead links.
