### ISSUE TITLE
[Backport v2.7-Patch1] [Feature] K8s 1.27 Support

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#44098]
Umbrella issue for adding support for K8s 1.27 for 2.7.x release line.
Somewhat of a backport of https://github.com/rancher/rancher/issues/41840 ("somewhat" is because it's far from being a simple backport with a lot of changes across multiple components).

**Rancher Changes**
- [x] https://github.com/rancher/rancher/issues/44141
*RKE1 1.27 Support*
- [x] https://github.com/rancher/rancher/issues/44142
*RKE2 1.27 Support*
- [x] https://github.com/rancher/rancher/issues/44143
*1.27 Support for external AWS CP for RKE1*
- [x] https://github.com/rancher/rancher/issues/44144
*1.27 Support for external AWS CP for RKE2*
- [x] https://github.com/rancher/rancher/issues/44145

**RKE Changes**
- [x] https://github.com/rancher/rancher/issues/44191
- [x] https://github.com/rancher/rancher/issues/44192
- [x] https://github.com/rancher/rancher/issues/44193

**Charts**
- [x] https://github.com/rancher/rancher/issues/44126

**Comment by snasovich** [comment]
Closing this umbrella ticket as K8s 1.27 support was backported into v2.7.x line and released with v2.7.11.

**Comment by h0jeZvgoxFepBQ2C** [comment]
When will there be a release for the general public, which supports 1.27 clusters? Digital Ocean auto upgrades to 1.27 on 30th march and I either have to update or to uninstall rancher before?

**Comment by snasovich** [comment]
@h0jeZvgoxFepBQ2C , K8s 1.27 support is available for general public since v2.8.1 release. Please upgrade to the latest v2.8.x release for continued support of your clusters (currently https://github.com/rancher/rancher/releases/tag/v2.8.2).
