### ISSUE TITLE
Long volume name bleed into Mount column

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4410]
Version - v1.0.1-rc7

Steps to Reproduce: 
1.  Setup glusterfs and convoy-gluster catalogs
2.  Create a sql container that uses convoy-gluster as Volume Driver
3.  Go to storage pools page and refresh it 

Results: The sql volume name bleeds into mount column
![image](https://cloud.githubusercontent.com/assets/11514927/14542664/efc6daa4-0244-11e6-8bd8-b810323df75f.png)

Expected: Text should cut off or wrap.

**Comment by lvuch** [comment]
https://github.com/rancher/ui/pull/722

**Comment by tfiduccia** [comment]
Version - master 3/16
Verified fixed
