### ISSUE TITLE
[Backport] rancher-cis-benchmark k8s 1.27 chart support

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#44106]
Backport of https://github.com/rancher/rancher/issues/41787

This issue is to implement the chart changes & perform the testing required to upgrade to k8s 1.27. Please perform below steps. 

- [ ] Check whether the chart has any references to the below deprecated features of k8s 1.27. You can find information about deprecated APIs here on [Kubernetes Deprecation guide](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-27).

**storage.k8s.io/v1beta1** API version of **CSIStorageCapacity**
 

- [ ] Update kube-version annotation in Chart.yaml. catalog.cattle.io/kube-version: '>= 1.23.0-0 < 1.28.0-0'

Note: If this is an upstream chart and if the upstream chart doesn't support k8s 1.27 then do not update the kube-version annotation or update the k8s version accordingly.

- [ ] Perform below tests

- Fresh install/uninstall/upgrade/downgrade of the charts on K8s 1.27 provisioned on Rancher. Test the chart functionality.
(Please refer to the https://github.com/rancher/rancher/issues/41395 to know what testing was done for k8s 1.26 upgrade for your chart)
- Provision rancher on k8s 1.26 or lesser
- Install chart on this cluster
- Upgrade this cluster in rancher to k8s 1.27
- Make sure the existing chart and the app is functional after cluster upgrade

**Comment by rishabhmsra** [comment]
Validated on rancher v2.7.11-head(fc2c10a), using CIS chart 4.3.0-rc1

Fresh install - CIS v1.7-permissive profile scan:
- RKE1 v1.27.10-rancher1-1 node driver and custom - passed
- RKE2 v1.27.10+rke2r1 node driver and custom - observed below failures which are expected [42971](https://github.com/rancher/rancher/issues/42971) 
```
Fail
1.1.1	Ensure that the API server pod specification file permissions are set to 600 or more restrictive (Automated)
Fail
1.1.3	Ensure that the controller manager pod specification file permissions are set to 600 or more restrictive (Automated)
Fail
1.1.5	Ensure that the scheduler pod specification file permissions are set to 600 or more restrictive (Automated)
Fail
1.1.7	Ensure that the etcd pod specification file permissions are set to 600 or more restrictive (Automated)
```
- K3s v1.27.10+k3s2 node driver and custom - passed

Upgrade checks :
- Provisioned v1.26 RKE1, RKE2 and K3s node driver clusters.
- Installed 4.2.0 CIS chart.
- Upgraded clusters to v1.27
- Upgraded chart to 4.3.0-rc1
- Ran permissive profile scan and it passed on all clusters except failures on RKE2 which is expected as mentioned in Fresh install.

Hardened RKE1, RKE2 and K3s - CIS v1.7 permissive as well as hardened profile:
- RKE1 v1.27 - scan failed with below expected failure - [42971](https://github.com/rancher/rancher/issues/42971) 
```
Mixed
4.1.7	Ensure that the certificate authorities file permissions are set to 600 or more restrictive (Automated)
```
- RKE2 v1.27 - passed.
- K3s v.127 - passed.

Imported clusters:
- Provisioned RKE1 v1.27 cluster and ran permissive v1.7 profile scan - passed

**Comment by mitulshah-suse** [comment]
**RELEASE NOTE**
Please release note the known issues reported above.
