### ISSUE TITLE
[Backport] k8s 1.27 support for the rancher-logging chart

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#44102]
Backport of https://github.com/rancher/rancher/issues/41794

This issue is to implement the chart changes & perform the testing required to upgrade to k8s 1.27. Please perform below steps. 

- [ ] Check whether the chart has any references to the below deprecated features of k8s 1.27. You can find information about deprecated APIs here on [Kubernetes Deprecation guide](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-27).

**storage.k8s.io/v1beta1** API version of **CSIStorageCapacity**
 

- [ ] Update kube-version annotation in Chart.yaml. catalog.cattle.io/kube-version: '>= 1.23.0-0 < 1.28.0-0'

Note: If this is an upstream chart and if the upstream chart doesn't support k8s 1.27 then do not update the kube-version annotation or update the k8s version accordingly.

- [ ] Perform below tests

- Fresh install/uninstall/upgrade/downgrade of the charts on K8s 1.27 provisioned on Rancher. Test the chart functionality.
(Please refer to the https://github.com/rancher/rancher/issues/41395 to know what testing was done for k8s 1.26 upgrade for your chart)
- Provision rancher on k8s 1.26 or lesser
- Install chart on this cluster
- Upgrade this cluster in rancher to k8s 1.27
- Make sure the existing chart and the app is functional after cluster upgrade

**Comment by MKlimuszka** [comment]
Duplicate of https://github.com/rancher/rancher/issues/44096

**Comment by pankajsqe** [comment]
Pass Verified in rancher v2.7.11-head. Below are the test cases.

**Local Cluster**
1. Provisioned Rancher with local k8s v1.26.9+k3s1 cluster.
2. Installed rancher-logging:102.0.2+up3.17.10
3. Setup splunk server to receive logs.
4. Configured Rancher to send logs on splunk server and Verify logs are being received in splunk.
5. Upgraded Local cluster to k8s v1.27.9+k3s1
6. Verified configured logging still sending logs to splunk server.
7. Logging passed p0 test cases.
8. Logging components like services, deployment and pods are up and running.
9. Chart annotations are correct.
10. Uninstall Logging app successfully on local cluster and deleted respective namespaces.
11. Fresh install Logging app on K8s v1.27.9
12. Configured Rancher to send logs on splunk server and Verify logs are being received in splunk.

**Downstream Cluster**
1. Provisioned downstream k8s v1.26.9 cluster.
2. Installed rancher-logging:102.0.2+up3.17.10
3. Setup splunk server to receive logs.
4. Configured Rancher to send logs on splunk server and Verify logs are being received in splunk.
5. Upgraded downstream cluster to k8s v1.27.9
6. Verified configured monitoring still sending alerts.
7. Logging passed p0 test cases.
8. Logging components like services, deployment and pods are up and running.
9. Chart annotations are correct.
10. Uninstall Logging app successfully on local cluster and deleted respective namespaces.
11. Fresh install Logging app on K8s v1.27.9
12. Configured Rancher to send logs on splunk server and Verify logs are being received in splunk.
