### ISSUE TITLE
[Backport] k8s 1.27 support for rancher-vsphere-csi chart

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#44119]
Backport of https://github.com/rancher/rancher/issues/41793

This issue is to implement the chart changes & perform the testing required to upgrade to k8s 1.27. Please perform below steps. 

- [ ] Check whether the chart has any references to the below deprecated features of k8s 1.27. You can find information about deprecated APIs here on [Kubernetes Deprecation guide](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-27).

**storage.k8s.io/v1beta1** API version of **CSIStorageCapacity**
 

- [ ] Update kube-version annotation in Chart.yaml. catalog.cattle.io/kube-version: '>= 1.23.0-0 < 1.28.0-0'

Note: If this is an upstream chart and if the upstream chart doesn't support k8s 1.27 then do not update the kube-version annotation or update the k8s version accordingly.

- [ ] Perform below tests

- Fresh install/uninstall/upgrade/downgrade of the charts on K8s 1.27 provisioned on Rancher. Test the chart functionality.
(Please refer to the https://github.com/rancher/rancher/issues/41395 to know what testing was done for k8s 1.26 upgrade for your chart)
- Provision rancher on k8s 1.26 or lesser
- Install chart on this cluster
- Upgrade this cluster in rancher to k8s 1.27
- Make sure the existing chart and the app is functional after cluster upgrade

**Comment by snasovich** [comment]
@thatmidwesterncoder , need to introduce `rancher-vsphere-csi` to `https://github.com/rancher/charts/tree/dev-v2.7.11` similar to https://github.com/rancher/charts/tree/release-v2.8/charts/rancher-vsphere-csi/103.0.0%2Bup3.0.2-rancher1 (but with 2.7.x versioning). See https://github.com/rancher/charts/pull/2956 for reference.

**Comment by slickwarren** [comment]
tested on 2.7.11-rc3:
* deploy 1.26 cluster, install csi chart
* upgrade to 1.27
* upgrade chart to latest version -- pass

fresh install with chart on 1.27 -- pass
