### ISSUE TITLE
[Backport] NeuVector k8s 1.27 chart support

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#44125]
Backport of https://github.com/rancher/rancher/issues/41803

This issue is to implement the chart changes & perform the testing required to upgrade to k8s 1.27. Please perform below steps. 

- [ ] Check whether the chart has any references to the below deprecated features of k8s 1.27. You can find information about deprecated APIs here on [Kubernetes Deprecation guide](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-27).

**storage.k8s.io/v1beta1** API version of **CSIStorageCapacity**
 

- [ ] Update kube-version annotation in Chart.yaml. catalog.cattle.io/kube-version: '>= 1.23.0-0 < 1.28.0-0'

Note: If this is an upstream chart and if the upstream chart doesn't support k8s 1.27 then do not update the kube-version annotation or update the k8s version accordingly.

- [ ] Perform below tests

- Fresh install/uninstall/upgrade/downgrade of the charts on K8s 1.27 provisioned on Rancher. Test the chart functionality.
(Please refer to the https://github.com/rancher/rancher/issues/41395 to know what testing was done for k8s 1.26 upgrade for your chart)
- Provision rancher on k8s 1.26 or lesser
- Install chart on this cluster
- Upgrade this cluster in rancher to k8s 1.27
- Make sure the existing chart and the app is functional after cluster upgrade

**Comment by gaktive** [comment]
Related to https://github.com/rancher/rancher/issues/44222 and https://github.com/rancher/rancher/issues/44223 though I need to confirm if this is the parent to those two.

**Comment by selvamt94** [comment]
@gaktive above PRs for adding new chart for NeuVector app version 5.2.4-s1. I have verified the existing chart 103.0.0+up2.6.4 and 103.0.1+up2.7.1(unreleased version) for k8s 1.27 support.

I did fresh install as well by upgrading downstream cluster from k8s version 1.26 to 1.27. Above charts works as expected. I tested this on Rancher manager 2.8.0 and 2.7.8. I used respective NeuVector charts.

**Comment by gaktive** [comment]
Thanks @selvamt94, does that mean that this ticket is not only dev complete but tested?

**Comment by selvamt94** [comment]
@gaktive Yes, we have tested too.
