### ISSUE TITLE
[Backport] Longhorn k8s 1.27 chart support

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#44123]
Backport of https://github.com/rancher/rancher/issues/41801

This issue is to implement the chart changes & perform the testing required to upgrade to k8s 1.27. Please perform below steps. 

- [ ] Check whether the chart has any references to the below deprecated features of k8s 1.27. You can find information about deprecated APIs here on [Kubernetes Deprecation guide](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-27).

**storage.k8s.io/v1beta1** API version of **CSIStorageCapacity**
 

- [ ] Update kube-version annotation in Chart.yaml. catalog.cattle.io/kube-version: '>= 1.23.0-0 < 1.28.0-0'

Note: If this is an upstream chart and if the upstream chart doesn't support k8s 1.27 then do not update the kube-version annotation or update the k8s version accordingly.

- [ ] Perform below tests

- Fresh install/uninstall/upgrade/downgrade of the charts on K8s 1.27 provisioned on Rancher. Test the chart functionality.
(Please refer to the https://github.com/rancher/rancher/issues/41395 to know what testing was done for k8s 1.26 upgrade for your chart)
- Provision rancher on k8s 1.26 or lesser
- Install chart on this cluster
- Upgrade this cluster in rancher to k8s 1.27
- Make sure the existing chart and the app is functional after cluster upgrade

**Comment by PhanLe1010** [comment]
@MKlimuszka Just want to confirm. This is for Rancher 2.7 charts, right?

**Comment by PhanLe1010** [comment]
Verified the chart and no code modification needed:
- [x] Check whether the chart has any references to the below deprecated features of k8s 1.27. You can find information about deprecated APIs here on [Kubernetes Deprecation guide](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-27).
- [x] Update kube-version annotation in Chart.yaml. catalog.cattle.io/kube-version: '>= 1.23.0-0 < 1.28.0-0'

For the testing part, we need to test the following charts which are currently available in Rancher 2.7 App & Market Place. cc @khushboo-rancher 
* 101.2.0+up1.4.0
* 102.2.0+up1.4.1
* 102.2.1+up1.4.2
* 102.2.2+up1.4.3
* 102.2.3+up1.4.4
* 102.3.0+up1.5.1
* 102.3.1+up1.5.3

**Comment by PhanLe1010** [comment]
@MKlimuszka Our QA should test with Rancher `rancher/rancher:v2.7-head`, right?

**Comment by roger-ryao** [comment]
**Verified on rancher/rancher:v2.7.11-b30643b8f2f1a59acfc348fc32825e9d459c0fbb-head 20240202**

rancher/rancher:`v2.7.11-b30643b8f2f1a59acfc348fc32825e9d459c0fbb-head`

**Result Passed**

- [x] 1. `v1.26.11+rke2r1` upgrade to `v1.27.8+rke2r1` with longhorn `102.2.3+up1.4.4`
- [x] 2. `v1.26.11+k3s2` upgrade to `v1.27.8+k3s2` with longhorn `102.2.3+up1.4.4`
- [x] 3. `v1.26.11+rke2r1` upgrade to `v1.27.8+rke2r1` with longhorn `102.3.1+up1.5.3`
- [x] 4. `v1.26.11+k3s2` upgrade to `v1.27.8+k3s2` with longhorn `102.3.1+up1.5.3`
- [x] 5. `v1.27.8+rke2r1` with longhorn `102.2.3+up1.4.4`
- [x] 6. `v1.27.8+k3s2` with longhorn `102.2.3+up1.4.4`
- [x] 7. `v1.27.8+k3s2` with longhorn `102.3.1+up1.5.3`
- [x] 8. `v1.27.8+k3s2` with longhorn `102.3.1+up1.5.3`

**Comment by snasovich** [comment]
Closing the issue as testing was successful and no new chart needs to be released for Longhorn for K8s 1.27 support.
