### ISSUE TITLE
[Backport 2.7] Fleet supports k8s 1.27

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#44127]
Partial backport of https://github.com/rancher/rancher/issues/41795

This issue is to implement the chart changes & perform the testing required to upgrade to k8s 1.27. Please perform below steps. 

- [x] Check whether the chart has any references to the below deprecated features of k8s 1.27. You can find information about deprecated APIs here on [Kubernetes Deprecation guide](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-27).

**storage.k8s.io/v1beta1** API version of **CSIStorageCapacity**
 

- [x] Do an RC of fleet "0.8" for charts/dev-v2.7
- [x] Update kube-version annotation in Chart.yaml. catalog.cattle.io/kube-version: '>= 1.23.0-0 < 1.28.0-0'
  https://github.com/rancher/charts/blame/dev-v2.8/packages/fleet/fleet/generated-changes/patch/Chart.yaml.patch

Note: If this is an upstream chart and if the upstream chart doesn't support k8s 1.27 then do not update the kube-version annotation or update the k8s version accordingly.

- [x] Perform below tests

- Fresh install/uninstall/upgrade/downgrade of the charts on K8s 1.27 provisioned on Rancher. Test the chart functionality.
(Please refer to the https://github.com/rancher/rancher/issues/41395 to know what testing was done for k8s 1.26 upgrade for your chart)
- Provision rancher on k8s 1.26 or lesser
- Install chart on this cluster
- Upgrade this cluster in rancher to k8s 1.27
- Make sure the existing chart and the app is functional after cluster upgrade

**Comment by sbulage** [comment]
As per issue: https://github.com/rancher/fleet/issues/2084 able to see applications deployed successfully via Fleet.

**Comment by kkaempf** [comment]
@sbulage - I just removed the "waiting for Rancher RC" label and moved it back to "Needs QA review".

Please sign-off and close this issue if all tests pass.

**Comment by sbulage** [comment]
@kkaempf In the latest Rancher RC: 2.7.11-rc3, I can see the fleet version: v0.8.2-rc.4 present.
