### ISSUE TITLE
Deleting a host that is running the server removes the server instead of the agent

### ISSUE THREAD

**Issue by 5f6b3fb8** [rancher/rancher#4412]
Rancher Version: 1.0.0

Docker Version: 1.10.3

OS: OEL 7.2

Steps to Reproduce: 
1. Start rancher server (docker run -d --restart=always -p 8080:8080 rancher/server)
2. Add the machine running the rancher server as a host
3. Once the host is active, remove the host

Results: 
Rancher server is stopped. Agent is still running.

Expected:
Agent is removed, Rancher server is still running.

**Comment by deniseschannon** [comment]
Fixed in v1.0.1. https://github.com/rancher/rancher/issues/4261
