### ISSUE TITLE
[Backport] Harvester-csi-driver k8s 1.27 chart support

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#44122]
Backport of https://github.com/rancher/rancher/issues/41800

This issue is to implement the chart changes & perform the testing required to upgrade to k8s 1.27. Please perform below steps. 

- [ ] Check whether the chart has any references to the below deprecated features of k8s 1.27. You can find information about deprecated APIs here on [Kubernetes Deprecation guide](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-27).

**storage.k8s.io/v1beta1** API version of **CSIStorageCapacity**
 

- [ ] Update kube-version annotation in Chart.yaml. catalog.cattle.io/kube-version: '>= 1.23.0-0 < 1.28.0-0'

Note: If this is an upstream chart and if the upstream chart doesn't support k8s 1.27 then do not update the kube-version annotation or update the k8s version accordingly.

- [ ] Perform below tests

- Fresh install/uninstall/upgrade/downgrade of the charts on K8s 1.27 provisioned on Rancher. Test the chart functionality.
(Please refer to the https://github.com/rancher/rancher/issues/41395 to know what testing was done for k8s 1.26 upgrade for your chart)
- Provision rancher on k8s 1.26 or lesser
- Install chart on this cluster
- Upgrade this cluster in rancher to k8s 1.27
- Make sure the existing chart and the app is functional after cluster upgrade

**Comment by Vicente-Cheng** [comment]
PR here: https://github.com/rancher/charts/pull/3307
Items check as below:

- [ ] Check whether the chart has any references to the below deprecated features of k8s 1.27. You can find information about deprecated APIs here on [Kubernetes Deprecation guide](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-27).

**storage.k8s.io/v1beta1** API version of **CSIStorageCapacity**

- [ ] Update kube-version annotation in Chart.yaml. catalog.cattle.io/kube-version: '>= 1.23.0-0 < 1.28.0-0'
Note: If this is an upstream chart and if the upstream chart doesn't support k8s 1.27 then do not update the kube-version annotation or update the k8s version accordingly.

- [ ] Perform below tests

- Fresh install/uninstall/upgrade/downgrade of the charts on K8s 1.27 provisioned on Rancher. Test the chart functionality.
(Please refer to the [Feature] k8s 1.26 support - apps and feature charts  #41395 to know what testing was done for k8s 1.26 upgrade for your chart)

- Provision rancher on k8s 1.26 or lesser

- Install chart on this cluster

- Upgrade this cluster in rancher to k8s 1.27

- Make sure the existing chart and the app is functional after cluster upgrade

**Comment by Vicente-Cheng** [comment]
Hi @lucasmlp, @snasovich,
I also bump the harvester csi driver to dev-2.7.11
could you help to review it?

Thanks!

**Comment by irishgordo** [comment]
This looks good :smile: :+1: - closing out.

Tested with:
- RKE2:
    - v1.26.13
    - v1.27.10
- RKE1:
   - v1.26.13
   - v1.27.10

On both Harvester v1.2.1 & Harvester v1.3.0-rc3 -> w/ Rancher v2.7.11-rc3.

cc: @TachunLin @lanfon72
