### ISSUE TITLE
[BUG][FATAL] error running the jail command: timed out waiting for the script to complete: signal: killed

### ISSUE THREAD

**Issue by ismailaksim** [rancher/rancher#44134]
**Rancher Server Setup**
- Rancher version: `v2.7.9`
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): `k3s, v1.26.13+k3s2`
- Proxy/Cert Details: `Rancher-generated Certificates`

**Information about the Cluster**
- Kubernetes version: `1.26.12`
- Cluster Type (Local/Downstream): `Downstream`
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): `Imported`

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:

**Describe the bug**

```
when I try to install rancher UI using helm as the official website suggests I get error:
[FATAL] error running the jail command: timed out waiting for the script to complete: signal: killed
```

**To Reproduce**

```
curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.26.13+k3s2 K3S_KUBECONFIG_MODE="644" sh -

kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.13.3/cert-manager.crds.yaml 

helm install cert-manager jetstack/cert-manager \
    --namespace cert-manager \
    --create-namespace

helm install rancher rancher-stable/rancher \
  --namespace cattle-system \
  --set hostname=<ip-adresse>.sslip.io \
  --set bootstrapPassword=admin \
  --set debug=true \
  --debug \
  --create-namespace
```

**Result**
```
2024/01/19 14:46:22 [INFO] Applying CRD clusters.cluster.x-k8s.io
2024/01/19 14:46:22 [DEBUG] DesiredSet - No change(2) apiextensions.k8s.io/v1, Kind=CustomResourceDefinition /clusters.cluster.x-k8s.io for  clusters.cluster.x-k8s.io
2024/01/19 14:46:22 [INFO] Applying CRD machinedeployments.cluster.x-k8s.io
2024/01/19 14:46:22 [DEBUG] DesiredSet - No change(2) apiextensions.k8s.io/v1, Kind=CustomResourceDefinition /machinedeployments.cluster.x-k8s.io for  machinedeployments.cluster.x-k8s.io
2024/01/19 14:46:22 [INFO] Applying CRD machinehealthchecks.cluster.x-k8s.io
2024/01/19 14:46:22 [DEBUG] DesiredSet - No change(2) apiextensions.k8s.io/v1, Kind=CustomResourceDefinition /machinehealthchecks.cluster.x-k8s.io for  machinehealthchecks.cluster.x-k8s.io
2024/01/19 14:46:22 [INFO] Applying CRD machines.cluster.x-k8s.io
2024/01/19 14:46:22 [DEBUG] DesiredSet - No change(2) apiextensions.k8s.io/v1, Kind=CustomResourceDefinition /machines.cluster.x-k8s.io for  machines.cluster.x-k8s.io
2024/01/19 14:46:22 [INFO] Applying CRD machinesets.cluster.x-k8s.io
2024/01/19 14:46:22 [DEBUG] DesiredSet - No change(2) apiextensions.k8s.io/v1, Kind=CustomResourceDefinition /machinesets.cluster.x-k8s.io for  machinesets.cluster.x-k8s.io
2024/01/19 14:46:24 [DEBUG] password fields {"alidnsProviderConfig":{"secretKey":".."},"cloudflareProviderConfig":{"apiKey":".."},"route53ProviderConfig":{"secretKey":".."}}
2024/01/19 14:46:25 [DEBUG] Catalog-cache running cleanup
2024/01/19 14:46:30 [DEBUG] CreateJail: called for [driver-jail]
2024/01/19 14:46:30 [DEBUG] CreateJail: jailPath is [/opt/jail/driver-jail]
2024/01/19 14:46:30 [DEBUG] CreateJail: Running script to create jail for [driver-jail]
2024/01/19 14:47:49 [FATAL] error running the jail command: timed out waiting for the script to complete: signal: killed
```

**Expected Result**

Rancher pod should start and work normally without any errors

**Screenshots**

![image](https://github.com/rancher/rancher/assets/35666502/a57253af-3590-4a8d-ad37-21b8b233d40b)

**Additional context**

I found a solution in this ticket #41043  but he's using CRIO and I'm using k3s with containerd

**Comment by Eldritch2004** [comment]
also happening in 2.8.3

**Comment by ismailaksim** [comment]
its been 6 months and there is no response to this I still have this issue and the error message don't show the cause or where can I look for a solution

**Comment by ismailaksim** [comment]
I solved this issue by just adding:   - --kubelet-insecure-tls to the metrics-server deployment 
kubectl edit deployment metrics-server -n kube-system
   at args:
      - --kubelet-insecure-tls

**Comment by liangouo** [comment]
> I solved this issue by just adding: - --kubelet-insecure-tls to the metrics-server deployment kubectl edit deployment metrics-server -n kube-system at args: - --kubelet-insecure-tls

This helps me a lot, thanks~~~

**Comment by liangouo** [comment]
> I solved this issue by just adding: - --kubelet-insecure-tls to the metrics-server deployment kubectl edit deployment metrics-server -n kube-system at args: - --kubelet-insecure-tls

This really helps me to solve this issue! Thank you very mach~~~
