### ISSUE TITLE
Update SUSE Rancher compatibility matrix info

### ISSUE THREAD

**Issue by NullIsNot0** [rancher/rancher#44131]
Rancher v2.8 is generally available, but [https://www.suse.com/suse-rancher/support-matrix/all-supported-versions](https://www.suse.com/suse-rancher/support-matrix/all-supported-versions) is not updated with compatibility info for Rancher 2.8. Can you please update this info?

**Comment by Martin-Weiss** [comment]
Support Matrix will be updated once Rancher v2.8 reaches stable status.
