### ISSUE TITLE
Add external AWS cloud provider support for downstream RKE2 clusters

### ISSUE THREAD

**Issue by Jono-SUSE-Rancher** [rancher/rancher#44145]
This is a child issue of https://github.com/rancher/rancher/issues/44098.

TODO:
- [x] backport the fix for https://github.com/rancher/rancher/issues/42588, which has been covered in https://github.com/rancher/rancher/pull/44146
- [ ] update Rancher docs for v2.7, ie. backport https://github.com/rancher/rancher-docs/pull/844  - This is covered in https://github.com/rancher/rancher-docs/pull/1080

**Comment by jiaqiluo** [comment]
Origianl https://github.com/rancher/rancher/issues/42749

**Comment by Jono-SUSE-Rancher** [comment]
We are waiting for the docker images to become available so we can move this to QA.

**Comment by jiaqiluo** [comment]
can be validated in the latest v2.7.11-head image

**Comment by slickwarren** [comment]
tested as part of regression tests in rancher, tracked in Qase. All tests are passing on 2.7.11-alpha3
