### ISSUE TITLE
Add external AWS cloud provider support for downstream RKE1 clusters

### ISSUE THREAD

**Issue by Jono-SUSE-Rancher** [rancher/rancher#44144]
This is a child issue of https://github.com/rancher/rancher/issues/44098

TODO:

- [x] fix rke ( https://github.com/rancher/rancher/issues/44192) 
- [x] cut rke new tag
- [x] bring rke into rancher - covered by https://github.com/rancher/rancher/pull/44146
- [x] backport [the fix](https://github.com/rancher/rancher/pull/43258) in rancher (Covered by https://github.com/rancher/rancher/pull/44146)
- [ ] Rancher docs for v2.7 need to backport https://github.com/rancher/rancher-docs/pull/844 - This is covered in https://github.com/rancher/rancher-docs/pull/1080

**Comment by jiaqiluo** [comment]
The UI issue https://github.com/rancher/dashboard/issues/10297

**Comment by slickwarren** [comment]
tested as part of regression tests in rancher, tracked in Qase. All tests are passing on 2.7.11-alpha3. Leaving open since this is a release-note item

**Comment by snasovich** [comment]
Closing as release note was added and all the tests are passing per the above comment.
