### ISSUE TITLE
K8s 1.27 Support for RKE1 and RKE1 Downstream Clusters

### ISSUE THREAD

**Issue by Jono-SUSE-Rancher** [rancher/rancher#44142]
This is a child issue of https://github.com/rancher/rancher/issues/44098.

Todo:

- [x] update KDM
- [x] update RKE
- [x] cut RKE new tag
- [x] bring RKE into Rancher - covered by https://github.com/rancher/rancher/pull/44146
- [x] update KDM URL in Rancher  - covered by https://github.com/rancher/rancher/pull/44146

**Comment by jiaqiluo** [comment]
wait for an image

**Comment by jiaqiluo** [comment]
can be validated in the latest v2.7.11-head image

**Comment by slickwarren** [comment]
tested as part of regression tests in rancher, tracked in Qase. All tests are passing on 2.7.11-alpha3
