### ISSUE TITLE
[BUG] RKE1 Cluster keeps constantly reconciling when secrets encryption is enabled

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#44140]
**Rancher Server Setup**
- Rancher version: `2.7.9`, `2.8.1-rc3`, `2.7.4`, `2.7.1` (Issue is NOT seen on `2.7.0`)
- Installation option (Docker install/Helm Chart): docker install

**Information about the Cluster**
- Kubernetes version: latest/default in the rancher versions
- Cluster Type (Local/Downstream): RKE1 - 3 nodes all roles; 3 etcd/cp nodes and 2 worker nodes

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Admin

**Describe the bug**
RKE1 Cluster keeps constantly reconciling when secrets encryption is enabled

**To Reproduce**
- Deploy an RKE1 cluster with secrets encryption enabled with custom key
```
services:
  kube-api:
    secrets_encryption_config:
      enabled: true
      custom_config:
        apiVersion: apiserver.config.k8s.io/v1
        kind: EncryptionConfiguration
        resources:
        - resources:
          - secrets
          providers:
          - aescbc:
              keys:
              - name: k-fw5hn
                secret: RTczRjFDODMwQzAyMDVBREU4NDJBMUZFNDhCNzM5N0I=
          - identity: {}
```
- The cluster comes up Active
- Every 4-5 minutes, the cluster goes into an Updating state - reconciling
- rancher logs:
```
024/01/19 14:39:27 [INFO] Provisioning cluster [c-mbc2k]
2024/01/19 14:39:27 [INFO] Updating cluster [c-mbc2k]
2024/01/19 14:39:32 [INFO] kontainerdriver rancherkubernetesengine listening on address 127.0.0.1:35531
2024/01/19 14:39:32 [INFO] cluster [c-mbc2k] provisioning: Initiating Kubernetes cluster
2024/01/19 14:39:32 [INFO] [certificates] GenerateServingCertificate is disabled, checking if there are unused kubelet certificates
2024/01/19 14:39:32 [INFO] [certificates] Generating admin certificates and kubeconfig
2024/01/19 14:39:32 [INFO] cluster [c-mbc2k] provisioning: Successfully Deployed state file at [management-state/rke/rke-465041502/cluster.rkestate]
2024/01/19 14:39:32 [INFO] cluster [c-mbc2k] provisioning: Building Kubernetes cluster
...
```

**Expected Result**
there is no constant reconcile happening on downstream RKE1 cluster.

---

**Note:**
On 2.7.0, this issue is NOT seen

**Comment by Josh-Diamond** [comment]
Ticket #44140 - Test Results - ✅ 
---

Verified on Rancher `v2.9-4dd0c38a2aab4f77271c07d2c887ecf5bbcea5e3-head`:

| Scenario | Test Case | Result |
|---|---|---|
| 1. | Provision downstream RKE1 cluster w/ secrets encryption enabled and using a custom key | ✅ |
| 2. | Provision downstream RKE1 cluster w/ secrets encryption disabled | ✅ |
