### ISSUE TITLE
K8s 1.27 Support for local Rancher Cluster

### ISSUE THREAD

**Issue by Jono-SUSE-Rancher** [rancher/rancher#44141]
This is a _child_ issue of the _parent_ issue https://github.com/rancher/rancher/issues/44098

**Comment by slickwarren** [comment]
Getting this error when trying to install rancher on 1.27:
```
chart requires kubeVersion: < 1.27.0-0 which is incompatible with Kubernetes v1.27.9+rke2r1\n'
```
using the registry version of rancher for 2.7.11-head

**Comment by slickwarren** [comment]
New issue - prime is not enabled by default

**Comment by slickwarren** [comment]
awaiting testing now that rc3 has been cut

**Comment by slickwarren** [comment]
tested and tracked in Qase - working on 2.7.11-rc3
