### ISSUE TITLE
Add K8s 1.27 Support for downstream RKE2 clusters

### ISSUE THREAD

**Issue by Jono-SUSE-Rancher** [rancher/rancher#44143]
This is a child ticket of the parent ticket https://github.com/rancher/rancher/issues/44098.

Todo:

- [x] update KDM
- [x]  update KDM URL in Rancher - covered by https://github.com/rancher/rancher/pull/44146

**Comment by jiaqiluo** [comment]
The fix can be validated in the latest `v2.7.11-head`

**Comment by jiaqiluo** [comment]
can be validated in the latest v2.7.11-head image

**Comment by slickwarren** [comment]
tested as part of regression tests in rancher, tracked in Qase. All tests are passing on 2.7.11-alpha3
