### ISSUE TITLE
Sorting by mount confusing in storage pool page

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4415]
Version - v1.0.1-rc7

Steps to Reproduce: 
1.  Create glusterfs and convoy glusterfs catalog
2.  Create multiple services with different mount & container names
3.  Go to storage pool page and sort by mount

Results: results are confusing
![image](https://cloud.githubusercontent.com/assets/11514927/14546178/908ba9c0-0258-11e6-8a83-3bb14cadcc38.png)

Expected: Not sure there is any way to sort and not be confused.  So take away sorting on this column.

**Comment by lvuch** [comment]
https://github.com/rancher/ui/pull/722

**Comment by tfiduccia** [comment]
Version - master 3/16
Verified fixed
