### ISSUE TITLE
[Documentation] Rancher read-only project member seeing 403 errors for monitoring endpoints in console

### ISSUE THREAD

**Issue by ronhorton** [rancher/rancher#44177]
**Setup**
- Rancher version: `2.8-head`
- Rancher UI Extensions: `N/A`
- Browser type & version: `Chrome Version 117.0.5938.92 (Official Build) (x86_64)`

**Describe the bug**
A read-only project member sees 403 errors in the console when navigating the cluster page for the project that user is a member of. 

**To Reproduce**

1. Enable monitoring v2 on downstream cluster
2. Create a project in this downstream cluster
3. Create a namespace in this project
4. Create an nginx workload in this namespace
5. Open grafana as admin user (from monitoring page) and save the URL for later use
6. Edit the members of the project and add a user with the "Read-only" role
7. Run this in the kubectl shell for the cluster:
8. kubectl create clusterrolebinding view-monitoring-ui --clusterrole=monitoring-ui-view --user=userID
9. Sign in as new user and navigate to downstream cluster page

**Result**
`403 errors in console re: monitoring assets`

**Expected Result**
No 403s. As a user, if i don't have access to an endpoint, why fetch that endpoint and return an error? 

**Screenshots**

<img width="271" alt="2023-10-10_13-27-24" src="https://github.com/rancher/dashboard/assets/89212856/794cf6e2-30e5-445b-ba12-a178be08125c">

**Additional context**
this is a separation of 2 different issues covered in https://github.com/rancher/dashboard/issues/9792 - the main issue in that page has been fixed and verified. 

SURE-7160

**Comment by MKlimuszka** [comment]
After another round of triage, this is working as designed. But we should have better docs on this.
