### ISSUE TITLE
[RKE v1.4] Deprecate Weave

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#44193]
This is a child issue of https://github.com/rancher/rancher/issues/44098.

Backport of https://github.com/rancher/rke/issues/3338

TODO:
- [x] backport fix in RKE
- [x] cut RKE RC - covered by RKE [v1.4.15-rc1](https://github.com/rancher/rke/releases/tag/v1.4.15-rc1)
- [x] bring RKE RC into Rancher - covered by https://github.com/rancher/rancher/pull/44146
- [x] backport Rancher UI (by the UI team) (https://github.com/rancher/dashboard/issues/10291)

**Comment by jiaqiluo** [comment]
The UI part is tracked here https://github.com/rancher/dashboard/issues/10291

**Comment by jiaqiluo** [comment]
The fix can be validated in the latest `v2.7.11-head`.

**Comment by Jono-SUSE-Rancher** [comment]
Waiting for the docker images to become available so we can move this to QA.

**Comment by jiaqiluo** [comment]
can be validated in the latest v2.7.11-head image

**Comment by susesgartner** [comment]
Ticket #44193 - Test Results - ✅
---
 
| Scenario | Test Case | Result |
|---|---|---|
| 1. | Verify that the depreciation message is displayed on cluster creation | PASS |
| 2. | Verify that the depreciation message is displayed on cluster upgrade  | PASS |

---
Verified with (HA Helm or Docker) on Rancher `v2.7-head`:
---
 
Scenario 1: Verify that the depreciation message is displayed on cluster creation
---
1. Create a rke1 cluster with Kubernetes 1.27.10 
2. Verify that weave show deprecation message when selected
 
Results: The deprecation message is properly displayed
 
---
 
Scenario 2: Verify that the depreciation message is displayed on cluster upgrade 
---
1. Create a rke1 cluster with Kubernetes 1.26 and weave
2. Upgrade cluster to 1.27.10
3. Verify that the deprecation message is displayed
 
Results: The deprecation message is properly displayed
