### ISSUE TITLE
[RKE v1.4] add logic for external aws cloud provider

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#44192]
This is a child issue of https://github.com/rancher/rancher/issues/44098.
Rancher-side counterpart https://github.com/rancher/rancher/issues/44144  

TODO:

- [x]  Backport of fixes in https://github.com/rancher/rke/pull/3413 and https://github.com/rancher/rke/pull/3443
- [x] Cut RC - RKE [v1.4.15-rc1](https://github.com/rancher/rke/releases/tag/v1.4.15-rc1)

**Comment by jiaqiluo** [comment]
This can be validated in RKE [v1.4.15-rc1](https://github.com/rancher/rke/releases/tag/v1.4.15-rc1).
It is up to the QA whether it is necessary to validate the fix in the standalone RKE because the original issue was validated on the Rancher side ( https://github.com/rancher/rancher/issues/43175 and https://github.com/rancher/rancher/issues/43624)

**Comment by markusewalker** [comment]
**QA TEST PLAN**

|#|Scenario|Test Case|
|---|---|---|
|1|RKE provisions without `use_instance_metadata_hostname`|Provision standalone RKE v1.27 cluster with the `cluster.yml` not having `use_instance_metadata_hostname` defined|
|2|RKE provisions w/`use_instance_metadata_hostname: true` |Provision standalone RKE v1.27 with the `cluster.yml` with `use_instance_metadata_hostname` set to true|
|3|Upgrade RKE v1.26 to v1.27|Provision standalone RKE v1.26 with external AWS cloud provider, upgrade to v1.27 with external AWS cloud provider|
|4|Migrate in-tree to ut of tree during upgrade|Provision standalone RKE v1.26 with in-tree cloud provider, upgrade to v1.27 after migrating to use external AWS cloud provider|

**Comment by markusewalker** [comment]
Validated this against `v1.4.15-rc1`. See details below:

**ENVIRONMENT DETAILS**
- RKE binary version: `v1.4.15-rc1`
- RKE cluster version:
     - Fresh install: `v1.26.13-rancher1-1`
     - Upgrade: `v1.27.10-rancher1-1`

**TEST RESULT**
|#|Scenario|Test Case|Result
|---|---|---|---|
|1|RKE provisions without `use_instance_metadata_hostname`|Provision standalone RKE v1.27 cluster with the `cluster.yml` not having `use_instance_metadata_hostname` defined|:white_check_mark:|
|2|RKE provisions w/`use_instance_metadata_hostname: true` |Provision standalone RKE v1.27 with the `cluster.yml` with `use_instance_metadata_hostname` set to true|:white_check_mark:|
|3|Upgrade RKE v1.26 to v1.27|Provision standalone RKE v1.26 with external AWS cloud provider, upgrade to v1.27 with external AWS cloud provider|:white_check_mark:|
|4|Migrate in-tree to out of tree during upgrade|Provision standalone RKE v1.26 with in-tree cloud provider, upgrade to v1.27 after migrating to use external AWS cloud provider|:white_check_mark:|

**VALIDATION STEPS**

**Scenario 1**
1. Provisioned a standalone RKE v1.27.10 cluster (1 etcd, 1 control plane, 1 worker) and ensured that the following in the `cluster.yml` file:
```
cloud_provider:
  name: "external-aws"
```
2. Validated that the cluster provisioned successfully and `kubectl get nodes` shows all nodes in the cluster as `Ready`.

_______

**Scenario 2**
1. Repeated scenario `, but ensured the `cluster.yml` file had the following:
```
cloud_provider:
  name: "external-aws"
  use_instance_metadata_hostname: true
```
_______

**Scenario 3**
1. Repeated scenario 1, but provisioned a standalone RKE v1.26.13 cluster (1 etcd, 1 control plane, 1 worker).
2. Upgraded cluster to v1.27.10; validated the nodes in the cluster upgraded successfully.

_______

**Scenario 4**
1. Provisioned a downstream RKE v1.26.13 cluster without `cloud_provider` block defined in the `cluster.yaml` file.
2. Upgraded to v1.27.10, but ensured the following in the `cluster.yml` file:
```
cloud_provider:
  name: "external-aws"
  use_instance_metadata_hostname: true
```
3. Validated that the cluster provisioned successfully and `kubectl get nodes` shows all nodes in the cluster as `Ready`.
