### ISSUE TITLE
[RKE v1.4] Support 1.27

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#44191]
This is a child issue of https://github.com/rancher/rancher/issues/44098.

TODO:

- [x] Add 1.27 in KDM
- [x] backport 1.27 related fixes in RKE
- [x] bring updated KDM data into RKE
- [x] cut RC

**Comment by jiaqiluo** [comment]
The support can be validated in RKE [v1.4.15-rc1](https://github.com/rancher/rke/releases/tag/v1.4.15-rc1)

**Comment by slickwarren** [comment]
all checks have passed and are tracked in Qase
