### ISSUE TITLE
When container is restored and started, it is not part of LB configuration any more

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#442]
Server Version - V0.14.2

Steps to reproduce  the problem:
Create LB with LB config that has 1 listener.
Add 1 host and 2 targets.

Remove one of the containers.
Notice that this target (container) is already removed from the LB's list of targets.

Restore this container and start it.

This container is not reachable using the LB Ip address.

Expected Behavior:
Container should be reachable using the LB Ip address after it was deleted , restored and started.

**Comment by alena1108** [comment]
I should change the trigger point for lb-target map removal from instance.destroy to instance.purge

**Comment by deniseschannon** [comment]
@sangeethah: @alena1108 says this was fixed a long time ago. i've just labeled it for testing.

**Comment by alena1108** [comment]
Closing as won't fix as the support for standalone LB is disabled.
