### ISSUE TITLE
[2.7.11] KDM update for RKE2/K3s Jan K8s patches

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#44209]
Tracking issue to sync Jan patches RKE2/K3s k8s versions 1.26.13 and 1.27.10 to 2.7.11. `dev-v2.7` branch is used for `v2.7-Patch1` effort currently and that's where Jan patches should be added too (including 1.27.x version).

https://github.com/rancher/rancher/issues/43937

**Comment by rancher-max** [comment]
This was added and validated and results posted on the PR itself: https://github.com/rancher/kontainer-driver-metadata/pull/1322#issuecomment-1939377574
