### ISSUE TITLE
Host path not showing in host details for volumes created through Service

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4420]
Version - v1.0.1

Steps to Reproduce: 
1.  Setup glusterfs and convoy-glusterfs catalogs
2.  Create a stack and add a service that uses convoy-gluster volume
3.  Create another stack and add a service to it that uses convoy-gluster volume (make sure to have different volume path)
4.  Go to host page and click on a Host name to get to host's detail page
5.  Go to Volume tab at bottom of page

Results: Notice one of the volumes you created has a host path and the other does not
![image](https://cloud.githubusercontent.com/assets/11514927/14547609/78bee008-0264-11e6-95a6-93588c2f1538.png)
![image](https://cloud.githubusercontent.com/assets/11514927/14547617/80b6a656-0264-11e6-9e2d-2a9f36b57113.png)

Expected: Both should have host path.  It looks like it happens every other service you create.

**Comment by westlywright** [comment]
@tfiduccia can you verify this again? I followed your steps and I believe I am seeing the correct data. I have placed a screenshot below. The first row are the convoy gluster mounts. Which have a host path. The second row does not have a host path. Those containers are using volumes on a DO server I have setup to host the convoy-nfs volumes and that server is not added as a host in my Rancher setup, thus I believe seeing an empty host path in that case is correct.

If you are still seeing the problem maybe we can walk through the setup together?
![screenshot 2016-06-24 09 25 38](https://cloud.githubusercontent.com/assets/858614/16343891/9021288e-39ee-11e6-8a85-4002047d66ed.png)

**Comment by tfiduccia** [comment]
After further research:
If I create the volume using the Add Volume in the storage tab, then create a service using that volume - then the host path gets set.
If I just use the service itself to create the volume, then the host path is not set.

Shouldn't these two options act the same?
![image](https://cloud.githubusercontent.com/assets/11514927/16428052/f68bfdfe-3d24-11e6-8cb0-a851541e960f.png)

**Comment by cjellick** [comment]
This is a legit bug, but it is only cosmetic and doesn't have a functional impact. Can we move out of 1.2.0?

**Comment by deniseschannon** [comment]
@tfiduccia Could you retest with the new storage stuff? Not sure if it's still occuring.

**Comment by tfiduccia** [comment]
Version - v1.2.0
Still a problem
![image](https://cloud.githubusercontent.com/assets/11514927/21067763/9eca9652-be2a-11e6-82e6-e05f053f3553.png)
