### ISSUE TITLE
[RFE] rancher-monitoring use the deprecated API v2beta2.HorizontalPodAutoscaler and block k8s update to 1.26

### ISSUE THREAD

**Issue by Xaviou1003** [rancher/rancher#44208]
**Is your feature request related to a problem? Please describe.**
Impossible to upgrade cluster to 1.26 with rancher-monitoring because rancher-monitoring use the hpa deprecated api that have been removed in 1.26
 

**Describe the solution you'd like**
I have noticed: 
- this issue is linked to mirrored-kube-state-metrics-kube-state-metrics version which is defined [in this file](https://github.com/rancher/charts/blob/release-v2.7/charts/rancher-monitoring/102.0.0%2Bup40.1.2/charts/kube-state-metrics/values.yaml).
- kube-state-metrics have deployed [2.7.0](https://github.com/kubernetes/kube-state-metrics/releases/tag/v2.7.0) to support autoscaling/v2 resources for HorizontalPodAutoscaler 
- there is already a version [(v2.10.1) of mirrored-kube-state-metrics-kube-state-metrics](https://github.com/rancher/image-mirror/blob/master/images-list#L1403) that use the new HPA API 

So I suppose rancher-monitoring can embedded the version v2.10.1 of mirrored-kube-state-metrics-kube-state-metrics and create a new version of rancher-monitoring that use this new version of mirrored-kube-state-metrics-kube-state-metrics.

**Describe alternatives you've considered**
I have 2 alternatives:
- Update manually the version of mirrored-kube-state-metrics-kube-state-metrics in the deployment rancher-monitoring-kube-state-metrics (not a long-term solution)
- Install monitoring with bitnami chart (but I prefer to use rancher-monitoring because the compatibility between rancher and the different component of monitoring is stronger)

SURE-7569

**Comment by joshmeranda** [comment]
What version of rancher-monitoring are you using? There are more recent versions of rancher-monitoring which support k8s 1.26, so you should be able to upgrade your monitoring deployment to a version that supports 1.26 and your current version, and then upgrade the cluster

**Comment by Xaviou1003** [comment]
My version of rancher-monitoring is 102.0.2+up40.1.2.
It is the last version that my rancher (v2.7.9) allows me to install.

When I search in rancher/chart github repo, I can't find a chart helm that uses a difference version of 2.6.0 for kube-metric.
 
For example, the last version of rancher monitoring chart is [104.0.2+up45.31.1 ](https://github.com/rancher/charts/tree/dev-v2.9/charts/rancher-monitoring/104.0.2%2Bup45.31.1) and it still includes the version 2.6.0 of kube-metrics .

Maybe I missed somehting but I don't know what.


Thanks for your help

**Comment by joshmeranda** [comment]
Where are you looking for the  kube-state-metrics version? Looking [here](https://github.com/rancher/charts/blob/dev-v2.9/charts/rancher-monitoring/104.0.2%2Bup45.31.1/charts/kube-state-metrics/Chart.yaml#L9) we are using kube-state-metricsd `2.9.2` and have been since [`103.0.0+up45.31.1`](https://github.com/rancher/charts/blob/dev-v2.9/charts/rancher-monitoring/103.0.0%2Bup45.31.1/charts/kube-state-metrics/Chart.yaml#L9). I'm thinking there might be some disconnect here.

Are you looking for us to backport kube-state-metrics >= `2.7.0`?

**Comment by Xaviou1003** [comment]
I tried to install rancher-monitoring _103.0.0+up45.31.1_ and _104.0.2+up45.31.1_. And I have always the same issue with this message (my cluster is on the new version so the call to the deprecated api have been remove): 
`
pkg/mod/k8s.io/client-go@v0.24.4/tools/cache/reflector.go:167: Failed to watch *v2beta2.HorizontalPodAutoscaler: failed to list *v2beta2.HorizontalPodAutoscaler: the server could not find the requested resource
`

My assumption: 
rancher/mirrored-kube-state-metrics-kube-state-metrics is always defined with tag [v2.6.0](https://github.com/rancher/charts/blob/dev-v2.9/charts/rancher-monitoring/104.0.2%2Bup45.31.1/charts/kube-state-metrics/values.yaml#L6) and this image v2.6.0 embedded the old version of kube-state-metrics.

Finally, I have found a way to override the version of rancher/mirrored-kube-state-metrics-kube-state-metrics. 
The solution is to override kube-state-metrics.image.tag in the values.yaml
```
kube-state-metrics:
    image:
       tag: v2.10.1
```
I don't understand why image tag v2.7.0 -> 2.10.0 doesn't exist. I just found this version on this [file](https://github.com/rancher/image-mirror/blob/master/images-list)



@joshmeranda  To answer to your question yes it is a good idea to backport the fix. 
Currently the official rancher is v2.7.x and the official catalog for rancher is the branch release-v2.7. So if we want to keep versions aligned it will great to have the fix! 


@joshmeranda Thanks for your help.
Rancher is an excellent product, so thanks a lot to the whole community that works on it!

**Comment by pankajsqe** [comment]
Retest Passed : Rancher 2.9-head with [monitoring](rancher-monitoring:104.0.2+up45.31.1) has  mirrored-kube-state-metrics-kube-state-metrics:v2.10.1

PFA

![Image](https://github.com/rancher/rancher/assets/149133120/52264474-677d-4844-80e1-5bbb83b8326d)
![Image](https://github.com/rancher/rancher/assets/149133120/6a3531e2-b838-431e-bd66-84f3cfe6b516)
![Image](https://github.com/rancher/rancher/assets/149133120/54942f3f-650b-4912-bced-d05176e1f067)

**Comment by h0jeZvgoxFepBQ2C** [comment]
I'm updating right now to 2.8.2 and we are stuck right now after updating the rancher-monitoring app. How shall we continue? Use the workaround with the values.yaml?
