### ISSUE TITLE
AWS region support ca-west-1 [RFE] 

### ISSUE THREAD

**Issue by atifhafeez** [rancher/rancher#44214]
**Is your feature request related to a problem? Please describe.**
I am trying to create cluster in ca-west-1 but the error indicates region invalid.

.... error setting machine configuration from flags provided: Invalid region specified ....

**Describe the solution you'd like**
add this region support.

**Describe alternatives you've considered**
none

**Additional context**
I have seen similar issues before where people requested and the regions were added accordingly.

https://github.com/rancher/rancher/issues/36783

**Comment by kkaempf** [comment]
See https://github.com/rancher/dashboard/issues/10294

**Comment by atifhafeez** [comment]
@kkaempf That issue is relevant to adding region for dashboard only. Don't we also need to add it in machine code? I opened PR over there but not getting attention. Can you help please?

**Comment by jiaqiluo** [comment]
PR is merged, now waiting for new r/r image

**Comment by jiaqiluo** [comment]
the fix can be validated on the latest v2.9-head

**Comment by Josh-Diamond** [comment]
Blocked - QA AWS Account does not have access to region `ca-west-1`.  Following up internally.
