### ISSUE TITLE
[Backport 2024-Jan RKE 1.4] etcd snapshot-restore with etcd v3.5.9 fails due to missing /bin/sh in etcd container image

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#44219]
`rancher/rancher` tracking issue for https://github.com/rancher/rke/issues/3485 for inclusion in January 2024 RKE1 1.4.x release, see the complete details there

**Comment by robkooper** [comment]
Is there any intermediate option that can be taken? I have a cluster that I tried to do a restore on and now all 3 controlplanes do not have any of the kubernetes services running (etcd, apiserver, etc).

**Comment by rishabhmsra** [comment]
Using standalone RKE v1.4.14-rc2 - fresh install
- Created v1.26.13-rancher1-1 (1-cp, 1-e, 1-w), performed backup after creating workloads - it was successful.
- Performed restore and it was successful:
```
INFO[0203] Restarting network, ingress, and metrics pods 
INFO[0205] Finished restoring snapshot [new_bkp1] on all etcd hosts
```
Using standalone RKE v1.4.14-rc2 - upgrade check:
- Created v1.25 cluster
- Created workloads.
- Perform backup
- Upgraded cluster to v1.26
- Created workloads and then performed backup and it was successful

Both scenarios passed, hence closing it.
