### ISSUE TITLE
[Backport v2.7-Patch1] etcd snapshot-restore with etcd v3.5.9 fails due to missing /bin/sh in etcd container image

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#44218]
`rancher/rancher` tracking issue for https://github.com/rancher/rke/issues/3485 for `v2.7-Patch1` release, see the complete details there

**Comment by rishabhmsra** [comment]
Validated on rancher v2.7.11-head(fc2c10a) HA setup:

Fresh install:
- Provisioned v1.27.8-rancher2-2 node driver cluster.
- Created workload and ingress.
- Took backup.
- Created some other workload and ingress.
- Restored cluster and it was successful.

Upgrade checks:
- Provisioned v1.26.11-rancher2-2 node driver cluster.
- Created workload and ingress.
- Took backup
- Upgraded cluster to v1.27.8-rancher2-2
- Created workload and ingress.
- Performed restore and cluster successfully restored to k8s v1.26 version.

Both the checks passed hence closing the issue.
