### ISSUE TITLE
Migrate to lighter base images

### ISSUE THREAD

**Issue by pjbgf** [rancher/rancher#44226]
## QA validation template

This validation template is for the images below:
- [x] rancher/rancher-agent: https://github.com/rancher/rancher/pull/44044
- [x] rancher/rancher: https://github.com/rancher/rancher/pull/44348

### Root cause
Base images used in Rancher's containers may contain a larger amount of components than required for Rancher Manager execution. By transitioning into lighter base images, the generated images will better age and have a decreased amount of CVEs over time.

### What was fixed?
The base images were changed, everything else remained the same.

### What should be tested?
Normal test suite, just to confirm no regression was introduced as part of these changes. Especial attention should be taken to anything that may execute binaries within either `rancher/rancher` or `rancher/agent` images, as some binaries have been removed as part of the changes.

### What areas could experience regressions?
No regression is to be expected.

**Comment by macedogm** [comment]
Closing as complete. v2.9.0 was released with the light base images. Regular tests were performed during the entire release process and no issues were raised due to the changes.
