### ISSUE TITLE
system-upgrade-controller stuck in "Starting upgrade.cattle.io/v1, Kind=Plan controller"

### ISSUE THREAD

**Issue by sonergzn** [rancher/rancher#44221]
**Version**
0.11.0

**Platform/Architecture**
Rancher 2.7.6 
Hybrid Kubernetes cluster v1.24.15 (with windows workers) 

**Describe the bug**
Hi, 
I am trying to upgrade the kubernetes version of my cluster from 1.24.15 to 1.25.13. The whole cluster was set up and managed by terraform. After changing the K8_version to1.25.13 in terraform and applying the terraform config, the system-upgrade-controller pod was deployed. Everything is fine so far however, when i check the logs of system-upgrade-controller, it is stuck in "Starting upgrade.cattle.io/v1, Kind=Plan controller" since more than 1 day and nodes are not getting upgraded. I guess it is waiting for something but not sure for what.
- CRD's of kind Plans are there.
- I don't see any errors in logs/events related to this upgrade.

I have also tried to manually upgrade the version of system-upgrade-controller from 0.11 to the latest(0.13.2) but no success. 

**Expected behavior**
I would just expect that the nodes are upgraded to the desired K8 version one by one according to spec: concurrency: <1> parameter in plans.

**Actual behavior**
All the nodes are getting labeled with "plan.upgrade.cattle.io/system-agent-upgrader=7385bc..." But no K8 upgrade is being performed on nodes. 

**Additional context**
- Under app's i can see that helm application called: "mcc-<_cluster_name_>-managed-system-upgrade-controller" is installed successfully. 
- There is a general warning on the home page of Rancher for this cluster saying: "Waiting for system-upgrade-controller helm chart reconciliation: waiting for system-upgrade-controller bundle roll out".
- Batch's are created and completed successfully by the Plans. 

He also fails to find the batch for some reason. The batch is there 
- Level=error msg="error syncing 'cattle-system/apply-system-agent-upgrader-windows1-on-windowsvm-with-5ac-60f82': handler system-upgrade-controller: jobs.batch \"apply-system-agent-upgrader-windows1-on-windowsvm-with-5ac-60f82\" not found, requeuing"

Not sure if this is a bug and it is possible that i am missing or overlooking something.. Any advise or guideline is appreciated.
Thank you !

**Comment by kedminute** [comment]
Hi @sonergzn - did you get anywhere with this issue? I'm facing the same problem with cattle-system/system-upgrade-controller trying to perform a downstream RKE2 upgrade, albeit with some differences (no Windows nodes).
