### ISSUE TITLE
User can add a system label but can't delete it

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4422]
Version - v1.0.1

Steps to Reproduce: 
1.  Create a label on a host and name the key io.rancher.host.test1 with any value
2.  Try to delete label

Results: Can't delete

Expected: Shouldn't I be able to delete it since I added it?

**Comment by vincent99** [comment]
Works for me, I think this was fixed a while ago

**Comment by tfiduccia** [comment]
Version - master 6/16
Verified fixed
