### ISSUE TITLE
[RFE] Allow sharing of Cloud Credentials

### ISSUE THREAD

**Issue by HoustonDad** [rancher/rancher#44247]
**Is your feature request related to a problem? Please describe.**
When MCM is in use by a large team of users, it's often times that the same cloud credential is saved amongst numerous Rancher users, but shouldn't be shared with the entire user base. 

**Describe the solution you'd like**
The ability to share a Cloud Credential with other Rancher users or groups. This should be tied into any integrated authentication provider. 
Example 1:
User $BOB needs the ability to provision clusters into $vsphere_alpha. As an administrator, I want the ability to share $vsphere_alpha cloud credentials with the Rancher Group "$vsphere_alpha_admins".

1. Rancher -> Cloud Credentials -> Create new / Edit $platform_credential
2. Name: "vSphere $alpha" Sharing: "Groups -> $vsphere_alpha_admins"

This allows all users of the '$vsphere_alpha_admins' group to use that Cloud Credential.

Example 2:
User $BOB needs the ability to provision clusters into $vsphere_alpha. As an administrator, I want the ability to share $vsphere_alpha cloud credentials with the Rancher user $BOB.

1. Rancher -> Cloud Credentials -> Create new / Edit $platform_credential
2. Name: "vSphere $alpha" Sharing: "Users -> $BOB"

**Describe alternatives you've considered**
Only full administrators can share credentials at this time, which gives full access to the existing fleet of clusters. 

**Additional context**
N/A

**Comment by skimbers** [comment]
It would also be nice if regular users could share their own cloud credentials.  Scenario, User Adam has permissions to create clusters for his team.  He has a cloud credential for vSphere that allows him to do so.  He wants to share access to the cloud credential with other members of his team so they can also create clusters with that credential without ever having to know that password in the credential.

**Comment by HoustonDad** [comment]
not stale

**Comment by vishujoshi123** [comment]
Hello Rancher team, in which release do you think will this feature request be implemented? Can you please reopen the issue? Without this too many entries of the same cloud credentials would be displayed to Rancher administrators in the cluster management.

Thanks in advance.

Kind Regards, 
Vishesh

**Comment by RRadziejewski** [comment]
Sharing those credentials, easy way via UI, would be nice feature to have.
