### ISSUE TITLE
RFE: Airgapped RKE2 etcd to AWS S3 via proxy

### ISSUE THREAD

**Issue by HoustonDad** [rancher/rancher#44256]
Request description:

We are trying to backup our ETCD cluster to AWS S3 from within out network. To do so requires that action to go through a proxy.

While the Rancher-Backup chart has the ability for proxy/noproxy configuration for the deployment only, there does not appear to be a way to do that with the ETCD backup's only as they is at RKE2's level and not a specific backup deployment/job/container.

Adding the noproxy/proxy to the RKE2 level would not be an option as kubelet would then be able to talk externally and that is restricted in our clusters.

Actual behavior:
Grant kubelet access via proxy to get S3 backups placed offsite

Expected behavior:
Grant etcd backup process access to proxy to push backups offsite

Workaround:
None

**Comment by zlmitchell** [comment]
@brandond Sorry if my example on how the functionality could be addressed for specifically Rancher Provisioned Systems gave you the feeling that you could pass this feature request to another team, but the issue still exists for native RKE2 servers with no Rancher Management.

This should be tackled in RKE2 first or entirely to ensure compatibility with Rancher after. The fact of the S3 process being defined directly in the RKE2 binary is an issue. It could instead be handled using the post process in RKE2 when it generates the rke2-etcd-snapshot configmap. At that time there could be an operator or something in RKE2 that monitors the snapshot and provides the S3 upload/download capabilities. This will still allow the original functionality to be available for DR purposes.

The current solution of the RKE2 binary being allowed to restore S3 snapshots and force push them to S3 is fine, but the secret management and flexibility is still not what our systems require.

**Comment by HoustonDad** [comment]
Not stale. Please re-open

**Comment by brandond** [comment]
Its not closed...

**Comment by brandond** [comment]
The K3s ADR supporting this has been open for a while; we need someone from Hostbusters to take a look and sign off on it.

**Comment by brandond** [comment]
Not stale, pending acceptance of ADR by Rancher teams.

**Comment by zlmitchell** [comment]
Not stale, waiting implementation

**Comment by brandond** [comment]
See above linked issues for implementation. Closing issue as completed.
