### ISSUE TITLE
Owncloud from catalog get stuck on activating

### ISSUE THREAD

**Issue by berzas** [rancher/rancher#4427]
Rancher Version: 1.0.1
Docker Version: 1.11.0
OS: Debian 8 Jessie
Steps to Reproduce: catalog>owncloud>activate
Results: Activating... (forever)
Expected:Active

On rancher webUI I succesfully activate Wordpress and Janitor from catalog, but owncloud stuck on activating with no errors. This is my second attempt to use Rancher, the first one it happened that owncloud activated correctly but wordpress get stuck on activating. This from catalog.

I could launch wordpress containers from docker-compose on command line, they are running but on rancher webUI they allways keep on activating

**Comment by deniseschannon** [comment]
Any questions regarding community catalog entries should be asked in the [rancher/community-catalog](https://github.com/rancher/community-catalog) repository to help get support from the community. 

A rancher tip, if a service is stuck in activating, you can click on the service (in your case owncloud) that is stuck and see the containers that are trying to spin up. You can click on one of them and see why it's failing. We provide messages on what is going on during the deployment and if the deployment fails, it will enter an errored state and you can click on that container to see why it is in error state.
