### ISSUE TITLE
kubernetes proxy always activating on 1.0.1

### ISSUE THREAD

**Issue by zzq889** [rancher/rancher#4429]
Rancher Version: 1.0.1

Docker Version: 1.10.3

OS: Centos 7

Steps to Reproduce: add host

Results: 
kubernetes proxy always activating

Expected:

log:
```
4/16/2016 12:38:23 AMI0415 16:38:23.843694       1 iptables.go:177] Could not connect to D-Bus system bus: dial unix /var/run/dbus/system_bus_socket: no such file or directory
4/16/2016 12:38:23 AMI0415 16:38:23.843818       1 server.go:154] setting OOM scores is unsupported in this build
4/16/2016 12:38:23 AMI0415 16:38:23.845807       1 server.go:216] Using userspace Proxier.
4/16/2016 12:38:23 AMI0415 16:38:23.848160       1 proxier.go:159] Setting proxy IP to 192.168.0.6 and initializing iptables
4/16/2016 12:38:23 AMI0415 16:38:23.898682       1 server.go:236] Tearing down pure-iptables proxy rules.
4/16/2016 12:38:23 AMI0415 16:38:23.981901       1 conntrack.go:36] Setting nf_conntrack_max to 262144
4/16/2016 12:38:23 AMI0415 16:38:23.981988       1 conntrack.go:41] Setting conntrack hashsize to 65536
4/16/2016 12:38:23 AMopen /sys/module/nf_conntrack/parameters/hashsize: read-only file system
```

**Comment by alena1108** [comment]
@zzq889 can you add write permissions on /sys/module/nf_conntrack/parameters/hashsize? This is the file where kube-proxy writes for connections tracking

**Comment by zzq889** [comment]
I roll back to rancher server 1.0.0 and proxy works fine for me.
and it seems that `CATTLE_AGENT_IP` doesn't apply to kubernetes config
```
4/16/2016 2:10:11 AMI0415 18:10:11.960793       1 iptables.go:177] Could not connect to D-Bus system bus: dial unix /var/run/dbus/system_bus_socket: no such file or directory
4/16/2016 2:10:11 AMI0415 18:10:11.961931       1 server.go:154] setting OOM scores is unsupported in this build
4/16/2016 2:10:11 AMI0415 18:10:11.968214       1 server.go:216] Using userspace Proxier.
4/16/2016 2:10:11 AMI0415 18:10:11.973238       1 proxier.go:159] Setting proxy IP to <MY_EXTERNAL_IP> and initializing iptables
4/16/2016 2:10:12 AMI0415 18:10:12.052933       1 server.go:236] Tearing down pure-iptables proxy rules.
4/16/2016 2:10:12 AMI0415 18:10:12.181080       1 conntrack.go:36] Setting nf_conntrack_max to 262144
4/16/2016 2:10:12 AMI0415 18:10:12.181167       1 conntrack.go:41] Setting conntrack hashsize to 65536
4/16/2016 2:10:12 AMI0415 18:10:12.182193       1 conntrack.go:46] Setting nf_conntrack_tcp_timeout_established to 86400
4/16/2016 2:10:16 AME0415 18:10:16.182485       1 event.go:202] Unable to write event: 'Post http://master/api/v1/namespaces/default/events: dial tcp: lookup master on 169.254.169.250:53: read udp 169.254.169.250:53: i/o timeout' (may retry after sleeping)
4/16/2016 2:10:22 AMI0415 18:10:22.227345       1 proxier.go:415] Adding new service "default/kubernetes:https" at 10.43.0.1:443/TCP
4/16/2016 2:10:22 AMI0415 18:10:22.227855       1 proxier.go:360] Proxying for service "default/kubernetes:https" on TCP port 60081
4/16/2016 2:10:22 AMI0415 18:10:22.233432       1 roundrobin.go:263] LoadBalancerRR: Setting endpoints for default/kubernetes:https to [192.168.0.12:6443]
```

**Comment by alena1108** [comment]
@sangeethah, could you test it against latest rancher using centos machine? And see if you can reproduce it.

**Comment by sangeethah** [comment]
@alena ,Tested kubernetes environment using Centos 7.2 host.  Kubernetes stack got created successfully , but the hosts keeps getting to "reconnecting" state and back to "active" and   Kubernetes stack took close to 1 hour to get  created . I have logged a different issue to tracke this -https://github.com/rancher/rancher/issues/4610

**Comment by alena1108** [comment]
@sangeethah I believe it should be fixed by now, could you retest?

**Comment by sangeethah** [comment]
Rancher Version: v1.1.1
Docker Version on hosts: 1.10.3
Host OS: CentOS Linux 7 (3.10.0-327.22.2.el7.x86_64)

In the default cattle environment , Add 1 Centos 7 host.
Update default environment to kubernetes env.
Kubernetes system stack gets to "active" state in 5 minutes.

Able to add service/rc/pods successfully.

mysql> select id,name,state,created,removed,first_running from instance where name like "%Kubernetes%";
+----+-----------------------------------------+---------+---------------------+---------------------+---------------------+
| id | name                                    | state   | created             | removed             | first_running       |
+----+-----------------------------------------+---------+---------------------+---------------------+---------------------+
|  1 | Kubernetes_etcd_data_1                  | stopped | 2016-07-20 21:17:26 | NULL                | 2016-07-20 21:17:29 |
|  2 | Kubernetes_etcd_1                       | running | 2016-07-20 21:17:27 | NULL                | 2016-07-20 21:17:56 |
|  4 | Kubernetes_etcd_data_2                  | purged  | 2016-07-20 21:17:58 | 2016-07-20 21:19:12 | NULL                |
|  5 | Kubernetes_kubernetes_1                 | running | 2016-07-20 21:18:13 | NULL                | 2016-07-20 21:18:44 |
|  6 | Kubernetes_rancher-ingress-controller_1 | running | 2016-07-20 21:18:46 | NULL                | 2016-07-20 21:19:15 |
|  7 | Kubernetes_controller-manager_1         | running | 2016-07-20 21:18:46 | NULL                | 2016-07-20 21:18:57 |
|  8 | Kubernetes_kubelet_1                    | running | 2016-07-20 21:18:46 | NULL                | 2016-07-20 21:18:59 |
|  9 | Kubernetes_rancher-kubernetes-agent_1   | running | 2016-07-20 21:18:46 | NULL                | 2016-07-20 21:19:14 |
| 10 | Kubernetes_kubectld_1                   | running | 2016-07-20 21:18:46 | NULL                | 2016-07-20 21:19:59 |
| 11 | Kubernetes_proxy_1                      | running | 2016-07-20 21:18:46 | NULL                | 2016-07-20 21:18:56 |
| 12 | Kubernetes_scheduler_1                  | running | 2016-07-20 21:18:46 | NULL                | 2016-07-20 21:18:53 |
+----+-----------------------------------------+---------+---------------------+---------------------+---------------------+
11 rows in set (0.01 sec)
