### ISSUE TITLE
Framework improvments for 1.27 support

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#44315]
Parent: https://github.com/rancher/rancher/issues/44098

PRs:
https://github.com/rancher/apiserver/pull/52
https://github.com/rancher/norman/pull/469
https://github.com/rancher/steve/pull/145

**Comment by brudnak** [comment]
After talking with other QA, putting this back to dev. Can we get a QA template for it? If it's not possible or doesn't make sense to have a template for each PR listed here, then it could be more of a generic QA template that encompasses the changes for all of these PRs.

**Comment by MbolotSuse** [comment]
## Validation Template

## What was fixed, or what change have occurred

For Norman:
- The Go version was bumped from 1.19 to 1.20
- The Kubernetes libraries (client-go, apiserver, apiextensions-apiserver, apimachinery) and the related controller libraries (lasso/wrangler) were bumped to 1.27 compatible versions.

For APIServer:
- The Go version was bumped from 1.19 to 1.20
- The Kubernetes libraries (apiserver, apimachinery) and the related controller libraries (wrangler) were bumped to 1.27 compatible versions.

For Steve:
- The Go version was bumped from 1.19 to 1.20
- The Kubernetes libraries (client-go, api, apiextensions-apiserver, apimachinery, kube-aggregator) and the related controller libraries (wrangler) were bumped to 1.27 compatible versions. Kube-openapi was also bumped to a more recent version.
- Other Rancher frameworks have been bumped to 1.27 compatible versions (norman, apiserver, dynamiclistener)
- Some rules were excluded from the linter configuration and the build configuration was changed to use golang 1.20 images
- Updates were made to functions that used wrangler controllers to use the new generic controller types.
- The fix for #44804 was backported to the 2.7 line.

## Areas or cases that should be tested

Basic Norman/APIServer/Steve regressions test cases, such as:
- Attempting to CRUD an object through Norman/Steve
- Retrieving a schema through steve `/v1/schemas`
- Running a docker install version of Rancher which needs to use it's own self-signed certificates

Basic Wrangler regressions test cases:
- Create a RoleTemplate in the local cluster
- Create a project in the downstream cluster, and a namespace in the project.
- Bind a user to the roletemplate in a downstream project using a PRTB.
- Ensure that the ClusterRole/RoleBinding was created in the downstream.
- Remove the PRTB.
- Ensure that the ClusterRole/RoleBinding was removed from the downstream.
- Remove the RoleTemplate.
- Ensure that the RoleTemplate was removed from the downstream.

Steve test cases from the panic fix, as outlined in that issue: https://github.com/rancher/rancher/issues/43030#issuecomment-1766597784

## What areas could experience regressions

- Functionality which uses either norman (`/v3/) or steve (`/v1`) endpoints.
- Functionality which uses either the norman controller framework or the wrangler controller framework.

## Are the repro steps accurate/minimal?
N/A.

**Comment by brudnak** [comment]
QA issue to validate this PR: https://github.com/rancher/steve/pull/145

Moved to this issue: https://github.com/rancher/rancher/issues/44371

**Comment by brudnak** [comment]
## Validation Environment


| Component                        | Version / Type                                                                     |
| -------------------------------- | ---------------------------------------------------------------------------------- |
| Rancher version                  | v2.7.11-afd12e81bf14bc59c85d5e2e4ea619411d39fb72-head                              |
| Rancher commit link              | https://github.com/rancher/rancher/commit/afd12e81bf14bc59c85d5e2e4ea619411d39fb72 |
| Installation option              | Helm (high availability)                                                           |
| If Helm Chart k8s cluster        | v1.26.13+k3s2                                                                      |
| Cert Details                     | external tls `aws acm`                                                             |
| k3s ha external db               | Aurora MySQL 5.7.mysql_aurora.2.11.1                                               |
| Helm version                     | v2.16.8-rancher2                                                                   |
| Downstream cluster type          | RKE2 Linode                                                                        |
| Downstream K8s version           | v1.27.10+rke2r1                                                                    |
| Authentication providers enabled | local                                                                              |
| Logged in user role              | admin / standard user                                                              |
| Browser type                     | Google Chrome                                                                      |
| Browser version                  | Version 121.0.6167.184 (Official Build) (x86_64)                                   |
| Dashboard                        | release-2.7 514de6b98                                                              |
| Webhook version                  | rancher/rancher-webhook:v0.3.7-rc2                                                 |


<a name="top"></a>

### Test Cases

| \#  | Priority | Description & Link                                                                                           | PASS/FAIL |
| --- | -------- | ------------------------------------------------------------------------------------------------------------ | --------- |
| 01  | P0       | [Cloud Credentials Create](#test-1)                                                                          | ✅ PASS    |
| 02  | P0       | [Cloud Credentials Read](#test-2)                                                                            | ✅ PASS    |
| 03  | P0       | [Cloud Credentials Update](#test-3)                                                                          | ✅ PASS    |
| 04  | P0       | [Cloud Credentials Delete](#test-4)                                                                          | ✅ PASS    |
| 05  | P0       | [Projects Create](#test-5)                                                                                   | ✅ PASS    |
| 06  | P0       | [Projects Read](#test-6)                                                                                     | ✅ PASS    |
| 07  | P0       | [Projects Update](#test-7)                                                                                   | ✅ PASS    |
| 08  | P0       | [Projects Delete (Project Only)](#test-8)                                                                    | ✅ PASS    |
| 09  | P0       | [Projects Delete (Project & Namespaces)](#test-9)                                                            | ✅ PASS    |
| 10  | P0       | [List all  schema](#test-10)                                                                                 | ✅ PASS    |
| 11  | P0       | [List individual schema](#test-11)                                                                           | ✅ PASS    |
| 12  | P0       | [Check rolebinding for expected finalizer](#test-12)                                                         | ✅ PASS    |
| 13  | P0       | [Ensure roles/bindings exist for a user added to a downstream cluster](#test-13)                             | ✅ PASS    |
| 14  | P0       | [Roles/bindings are cleaned up after cluster deletion](#test-14)                                             | ✅ PASS    |
| 15  | P0       | [Filtering projects/namespace](#test-15)                                                                     | ✅ PASS    |
| 16  | P0       | [Running a docker install version of Rancher which needs to use it's own self-signed certificates](#test-16) | ✅ PASS    |


<details>
    <summary>🚨 16 test cases... CLICK TO EXPAND! (For table links to work) ⬅️</summary>

<br>

# 1 / Cloud Credentials Create Status: ✅ PASS

<a name="test-1"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 1 details... Click to expand</summary>

**Test Steps for Validation**

1. Create a Linode cloud credential  in Rancher via the UI / v3 normal
2. Use the cloud credential to create a downstream cluster of any type in Linode

**✅ Expected Outcome**

Able to create a and use a Linode Cloud Credential

**✅ Actual Outcome**

Successfully was able to create a Linode Cloud Credential


</details>

<hr>

# 2 / Cloud Credentials Read Status: ✅ PASS

<a name="test-2"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 2 details... Click to expand</summary>

**Test Steps for Validation**

1. Create various cloud credentials
    - Linode
    - AWS
2. Ensure when visiting cloud credentials in the UI they are listed

**✅ Expected Outcome**

Cloud credentials are listed 

**✅ Actual Outcome**

Cloud credentials are listed 

</details>

<hr>

# 3 / Cloud Credentials Update Status: ✅ PASS

<a name="test-3"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 3 details... Click to expand</summary>

**Test Steps for Validation**

1. Create a Linode cloud credential with a description "text"
2. After cloud credential is created, edit it and change the description to "changed text"

**✅ Expected Outcome**

Able to update cloud credential description

**✅ Actual Outcome**

Able to update cloud credential description

</details>

<hr>

# 4 / Cloud Credentials Delete Status: ✅ PASS

<a name="test-4"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 4 details... Click to expand</summary>

**Test Steps for Validation**

1. Create a Linode cloud credential
2. Delete the cloud credential

**✅ Expected Outcome**

Able to delete cloud credential

**✅ Actual Outcome**

Able to delete cloud credential


</details>

<hr>

# 5 / Projects Create Status: ✅ PASS

<a name="test-5"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 5 details... Click to expand</summary>

**Test Steps for Validation**

1. Create a project via v3
2. Create a namespace within the project
3. Create a deployment within the namespace

**✅ Expected Outcome**

Able to create a project, namespace and deployment

**✅ Actual Outcome**

Able to create a project, namespace and deployment

</details>

<hr>

# 6 / Projects Read Status: ✅ PASS

<a name="test-6"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 6 details... Click to expand</summary>

**Test Steps for Validation**

1. Create a few projects
   - test-project1
   - test-project2
   - test-project3
2. Navigate to Cluster => Projects/Namespaces
3. Filter to All Namespaces

**✅ Expected Outcome**

Able to list projects

**✅ Actual Outcome**

Able to list projects

</details>

<hr>

# 7 / Projects Update Status: ✅ PASS

<a name="test-7"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 7 details... Click to expand</summary>

**Test Steps for Validation**

1. Starting as cluster owner, create a project named "my-test-project"
2. After the project is created, edit the config
3. Add another standard user as a project owner and rename the project to "changed-project"
4. Login as the user who was just granted project owner
5. Create a namespace "new-namespace"


**✅ Expected Outcome**

Able to update projects

**✅ Actual Outcome**

Able to update projects

</details>

<hr>

# 8 / Projects Delete (Project Only) Status: ✅ PASS

<a name="test-8"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 8 details... Click to expand</summary>

**Test Steps for Validation**

1. Create a project
2. Create a namespace within the project
3. Then delete the project, if using the UI mark to only delete the project and not the namespaces within it

**✅ Expected Outcome**

Delete a project

**✅ Actual Outcome**

Delete a project

</details>

<hr>

# 9 / Projects Delete (Project & Namespaces) Status: ✅ PASS

<a name="test-9"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 9 details... Click to expand</summary>

**Test Steps for Validation**

1. Create a project
2. Create a namespace within the project
3. Then delete the project, if using the UI mark to also delete the namespace

**✅ Expected Outcome**

Delete project and namespaces

**✅ Actual Outcome**

Delete project and namespaces

</details>

<hr>

# 10 / List all  schema Status: ✅ PASS

<a name="test-10"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 10 details... Click to expand</summary>

**Test Steps for Validation**

1. Navigate or call to /v1/schemas

**✅ Expected Outcome**

List all schemas

**✅ Actual Outcome**

List all schemas

</details>

<hr>

# 11 / List individual schema Status: ✅ PASS

<a name="test-11"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 11 details... Click to expand</summary>

**Test Steps for Validation**

1. Navigate to `v1/schemas/rbac.authorization.k8s.io.rolebindings`

**✅ Expected Outcome**

Able to list a singular schema

**✅ Actual Outcome**

Able to list a singular schema

</details>

<hr>

# 12 / Check rolebinding for expected finalizer Status: ✅ PASS

<a name="test-12"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 12 details... Click to expand</summary>

**Test Steps for Validation**

1. As admin create a downstream cluster
2. Create a standard user, "test-user-1"
3. Assign the new standard user as a cluster owner
4. Check the role binding that the finalizer was added: "auth-prov-v2"
5. Check this using kubectl against the local cluster

```sh
kubectl get rolebinding $ROLE_BINDING_NAME -n $ROLE_BINDING_NAMESPACE -o yaml
```

**✅ Expected Outcome**

Finalizer present

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: "2024-02-16T20:28:55Z"
  finalizers:
  - wrangler.cattle.io/auth-prov-v2-rb
```

**✅ Actual Outcome**

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: "2024-02-16T20:28:55Z"
  finalizers:
  - wrangler.cattle.io/auth-prov-v2-rb
```

</details>

<hr>

# 13 / Ensure roles/bindings exist for a user added to a downstream cluster Status: ✅ PASS

<a name="test-13"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 13 details... Click to expand</summary>

**Test Steps for Validation**

1. As admin create a downstream cluster
2. As admin create a new standard user "mytest-user"
3. Assign "mytest-user" as a cluster owner to the downstream
4. Login as the user and verify basic functionality
   - Create a downstream cluster
   - Create a project
   - Create a namespace
   - Create a deployment in that namespace
5. As admin with a kubeconfig to the local cluster, see that roles/bindings were created matching "The roleBinding name format: `crt-<cluster name>-<crtb name>-<hashed subject>`"

**✅ Expected Outcome**

Rolebinding created

**✅ Actual Outcome**

Rolebinding created

</details>

<hr>

# 14 / Roles/bindings are cleaned up after cluster deletion Status: ✅ PASS

<a name="test-14"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 14 details... Click to expand</summary>

**Test Steps for Validation**

1. As admin create a downstream cluster
2. As admin create a new standard user "mytest-user"
3. Assign "mytest-user" as a cluster owner to the downstream
4. Login as the user and verify basic functionality
5. As admin with a kubeconfig to the local cluster, see that roles/bindings were created matching "The roleBinding name format: `crt-<cluster name>-<crtb name>-<hashed subject>`"
6. Now delete the downstream cluster
7. After deleting the downstream cluster, check that the roles/bindings have been cleaned up

**✅ Expected Outcome**

Rolebindings cleaned up

**✅ Actual Outcome**

Rolebindings cleaned up

</details>

<hr>

# 15 / Filtering projects/namespace Status: ✅ PASS

<a name="test-15"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 15 details... Click to expand</summary>

**Test Steps for Validation**

1. As admin create a standard user
2. Login as standard user and create a downstream cluster
3. Create 5 projects and 10 namespaces
   1. a-test-proj-1
      - aa-ns-1
      - aa-ns-2
   2. b-test-proj-2
      - bb-ns-1
      - bb-ns-2
   3. c-test-proj-3
      - cc-ns-1
      - c-ns-2
   4. d-test-proj-4
      - d-ns-1
      - dd-ns-2
   5. e-test-proj-5
      - ee-ns-1
      - ee-ns-2
4. Ensure that filtering by namespaces is accurate

**✅ Expected Outcome**

Filtering projects and namespaces works

**✅ Actual Outcome**

Filtering projects and namespaces works

</details>

<hr>

# 16 / Running a docker install version of Rancher which needs to use it's own self-signed certificates Status: ✅ PASS

<a name="test-16"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 16 details... Click to expand</summary>

**Test Steps for Validation**

1. Create a docker install of Rancher
2. Have it use self signed certs
3. Logged in as admin create a standard user
4. Login as the standard user
5. Create a downstream cluster
6. Create a project
7. Create a namespace
8. Create a deployment in the namespace

**✅ Expected Outcome**

Docker install functioning as expected

**✅ Actual Outcome**

Docker install functioning as expected

</details>

<hr>

</details>
