### ISSUE TITLE
Introduce "Deployments" panel in k8s UI

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#4431]
"Deployment" is a "next Generation Replication Controller" as per k8s docs:

http://kubernetes.io/docs/user-guide/deployments/#what-is-a-deployment

As kubectl 1.2 run command wraps Deployment creation as opposed to 1.1 RC creation, and we are switching to officially support kubectl 1.2, we should introduce Deployments k8s tab.

```
1.1

kubectl run --image=nginx nginx --v=8
...........
I0415 18:01:25.975746     347 debugging.go:99] POST http://master/api/v1/namespaces/default/replicationcontrollers


1.2

kubectl run --image=nginx nginx --v=8
...........

I0415 11:16:03.570481   37998 round_trippers.go:264] POST https://130.211.135.131:8080/r/projects/1a5/kubernetes/apis/extensions/v1beta1/namespaces/default/deployments
```

@vincent99 @ibuildthecloud

**Comment by tfiduccia** [comment]
Version - 1.2.0-pre1-rc1
Verified fixed
