### ISSUE TITLE
Master - Can't add machine driver

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4433]
Version - master 4/15

Steps to Reproduce: 
1.  Go to settings
2.  Click on Add Machine Driver
3.  Put vultr as name and http://vtf.me/docker-machine-driver-vultr.zip as download URL

Results: Not Found

Expected: Should find it

**Comment by jmatsushita** [comment]
Using the tar ball from the Github releases page works: https://github.com/janeczku/docker-machine-vultr/releases/download/v1.0.6/docker-machine-driver-vultr-v1.0.6-linux-amd64.tar.gz 

I had to reload the page for it to show on the "Other" category when adding a host though.

**Comment by jmatsushita** [comment]
Actually it fails when trying to add hosts with the driver with the following error:
```
time="2016-04-19T16:39:59Z" level=info msg="Cmd slice: [create -d vultr --vultr-api-key B3KKFTTNCA5MDRYUVWJTRGALWBCW62 --vultr-os-id rancheros-machine --vultr-plan-id 29 --vultr-region-id 9 lab1]" 
time="2016-04-19T16:39:59Z" level=info msg="stderr: Driver \"vultr\" not found. Do you have the plugin binary accessible in your PATH?" resourceId=1ph22 
```

Not sure if that has anything to do with it, but Rancher displays the driver with an Uppercase V in the driver list when all the other are all lowercase

![image](https://cloud.githubusercontent.com/assets/356097/14647699/45faa9dc-065f-11e6-8325-6a9662e16317.png)

**Comment by jmatsushita** [comment]
It was related to the Uppercase V. janeczku/docker-machine-vultr#10

**Comment by jmatsushita** [comment]
I think I added the driver with "Vultr" as the name, and somehow that capitalised name was used when installing the driver causing the Driver not found error.

**Comment by tfiduccia** [comment]
Version - master 4/19
Verified fixed

@jmatsushita - The inability to find the driver because of capitalization is a separate issue and I verified that it is indeed a problem.  Entered as issue #4495
