### ISSUE TITLE
Windows 10 as worker node

### ISSUE THREAD

**Issue by Onlyward** [rancher/rancher#44330]
Can we add a Windows 10 Enterprise or Pro as a worker node? Or is this restricted to Windows servers?

https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/use-windows-clusters#add-a-windows-worker-node

If it is possible, could someone share any documentation?

**Comment by HarrisonWAffel** [comment]
Only Windows Server versions are supported, version 1809 or above
