### ISSUE TITLE
Kubernetes Pod View vs Infrastructure View - Container Log/Execute Shell Access

### ISSUE THREAD

**Issue by tsupertramp** [rancher/rancher#4434]
Rancher Version: v1.0.0
Docker Version: 1.10.3, build 20f81dd
OS: Linux Ami on AWS https://aws.amazon.com/amazon-linux-ami/2016.03-release-notes/
Kernel: 4.4.5-15.26.amzn1.x86_64

Steps to Reproduce: 
Create Kubernetes Env, create Pod with container running
Go to Infrastructure View, click on container, view_logs -> No Logs (showing connected)
Go to Infrastructure View, click on container, exec_shell -> Opens and closes instantely 

Go to Kubernetes, Pods view, click on container, view_logs -> Logs are shown
Go to Kubernetes, Pods view, click on container, exec_shell -> Exec is working

If i click on the same container (kubernetes view, infrastructure view) and try to open it via "View in Api" i get different Settings:
(https://rancher.injixo.com/v1/projects/1a110/containers/1i1071)
(https://rancher.injixo.com/v1/projects/1a110/containers/1i1072)

One Time the name of the object is: test123 (logs view is not working) and one time the name of the object is: test123-2050a6c384e3312edb3ca4aed06443dc-q3al5 but the hostname of both are always test123-2050a6c384e3312edb3ca4aed06443dc-q3al5 - So it seems that it is the same container but it has two ids. And one allows me to get logs and one not.

Is there some way to log more in server/agents because i am looking at the logs and can't see any "errors" or any related messages that could be a hint to the problem.

**Comment by alena1108** [comment]
@tsupertramp 

>> If i click on the same container (kubernetes view, infrastructure view) and try to open it via "View in Api" i get different Settings:

Those are actually 2 different containers. Pod creation triggers 2 containers creation on k8s: 

* k8s_POD container
* k8s_<container name from the spec> container

Container on Kubernetes UI is the actual user container, therefore you can see the logs and exec.
On infrastructure view, the container that you try to access, is the POD system container. If click on "Containers" link below, you would get forwarded to the user container.

@vincent99 do you think it would make sense to add "pod" identifier for k8s_POD containers under Infrastructure view? And corresponding Containers link below it, similar to k8s view.

**Comment by tsupertramp** [comment]
Ahh I see the difference. Thanks for pointing it out.
Your change suggesting to vincent would help to make the ui even greater.
Thanks 👍

**Comment by tsupertramp** [comment]
Already solved.
