### ISSUE TITLE
[BUG] Stale secrets for impersonation user in downstream cluster

### ISSUE THREAD

**Issue by vatsalparekh** [rancher/rancher#44347]
**Rancher Server Setup**
- Rancher version: 2.7.9, 2.8.2

**Information about the Cluster**
- Kubernetes version: v1.26.11+rke2r1
- Cluster Type (Local/Downstream): Downstream, created from Rancher on EC2

**User Information**
- What is the role of the user logged in?  `Admin`

**Describe the bug**

- Multiple stale `Secrets` created for a single impersonation user/ServiceAccount in the downstream cluster
- SA shows 1 secret and single reference but multiple secrets with same SA reference found
- The stale secrets don't get reconciled even if we delete the current referenced secret in the ServiceAccount
```
> k get secrets -n cattle-impersonation-system
NAME                                            TYPE                                  DATA   AGE
cattle-impersonation-u-hjxlz-token-24kwk        kubernetes.io/service-account-token   3      22h
cattle-impersonation-u-l767yhswxf-token-lnzc2   kubernetes.io/service-account-token   3      3d23h
cattle-impersonation-u-l767yhswxf-token-rdlkx   kubernetes.io/service-account-token   3      4d22h
cattle-impersonation-u-l767yhswxf-token-w5klt   kubernetes.io/service-account-token   3      3d23h
cattle-impersonation-u-oxfisb4qb2-token-gtjln   kubernetes.io/service-account-token   3      4d23h
cattle-impersonation-user-ptj5z-token-gzjnc     kubernetes.io/service-account-token   3      4d23h
> k get sa -n cattle-impersonation-system -o wide
NAME                                SECRETS   AGE
cattle-impersonation-u-hjxlz        1         22h
cattle-impersonation-u-l767yhswxf   1         4d22h
cattle-impersonation-u-oxfisb4qb2   1         4d23h
cattle-impersonation-user-ptj5z     1         4d23h
default                             0         4d23h
> k get secrets -A -o yaml | grep 'cattle-impersonation-u-l767yhswxf'
      kubernetes.io/service-account.name: cattle-impersonation-u-l767yhswxf
    generateName: cattle-impersonation-u-l767yhswxf-token-
    name: cattle-impersonation-u-l767yhswxf-token-lnzc2
      name: cattle-impersonation-u-l767yhswxf
      kubernetes.io/service-account.name: cattle-impersonation-u-l767yhswxf
    generateName: cattle-impersonation-u-l767yhswxf-token-
    name: cattle-impersonation-u-l767yhswxf-token-rdlkx
      name: cattle-impersonation-u-l767yhswxf
      kubernetes.io/service-account.name: cattle-impersonation-u-l767yhswxf
    generateName: cattle-impersonation-u-l767yhswxf-token-
    name: cattle-impersonation-u-l767yhswxf-token-w5klt
      name: cattle-impersonation-u-l767yhswxf
```

A snippet from the Rancher pod log shows that the multiple creation happens usually quickly after each other, hinting at lack of concurency while the Ensure func is called for the same ServiceAccount
```
2024/02/13 11:29:43 [INFO] EnsureSecretForServiceAccount: waiting for secret [cattle-impersonation-user-kgnqk-token-cd6fl] to be populated with token
2024/02/13 11:29:43 [INFO] EnsureSecretForServiceAccount: waiting for secret [cattle-impersonation-user-kgnqk-token-v7r6z] to be populated with token
2024/02/13 11:29:44 [INFO] EnsureSecretForServiceAccount: waiting for secret [cattle-impersonation-user-kgnqk-token-sg9sb] to be populated with token
2024/02/13 11:29:44 [INFO] Creating roleBinding User user-kgnqk Role admin in cattle-system
2024/02/13 11:29:44 [INFO] Updating clusterRole project-owner-promoted for project access to global resource.
2024/02/13 11:29:44 [INFO] [mgmt-auth-crtb-controller] Creating roleBinding for subject u-xpeyhn3op3 with role cluster-owner in namespace p-g8bfg
2024/02/13 11:29:44 [INFO] Creating roleBinding User user-kgnqk Role project-owner in default
2024/02/13 11:29:44 [INFO] [mgmt-auth-crtb-controller] Creating roleBinding for subject u-xpeyhn3op3 with role cluster-owner in namespace p-s2mp7
2024/02/13 11:29:44 [INFO] Creating roleBinding User user-kgnqk Role admin in kube-system
```
**To Reproduce**

This seems random at this point, on a Rancher with a downstream cluster, this can be seen out of the box in the downstream cluster.
A customer has seen this for a custom user, in my reproducer this is happening for a fleet user.
There's a time difference between the stale secrets creation, so this might not occur at the first try

**Comment by vatsalparekh** [comment]
I can see this happening on `2.8.2` also 
![Screenshot_20240214_104543](https://github.com/rancher/rancher/assets/6758282/1f7418a6-ffa9-463c-9155-d7e74f7fd650)

**Comment by samjustus** [comment]
sure-7514

**Comment by bigkevmcd** [comment]
## Validation Template

## What was fixed, or what change has occurred

A mutex was added to the secret creation process, which prevents concurrent creation of secrets and leads to fewer "stale" secrets.

## Areas or cases that should be tested

- Impersonation into downstream clusters.

## What areas could experience regressions

- None

## Are the repro steps accurate/minimal?

**Comment by samjustus** [comment]
why was it reverted? @snasovich

**Comment by snasovich** [comment]
@samjustus , just to close the loop - this is being discussed "offline" (in Slack). But TLDR these changes broke provisioning (and CI is failing after the merge blocking other PRs).

**Comment by bigkevmcd** [comment]
## Validation Template

## What was fixed, or what change has occurred

Failing to connect to upstream Azure endpoints will get a better error message.

## Areas or cases that should be tested

- Configure authentication for Azure AD and enter a custom endpoint that points to a site/port that will not connect

## What areas could experience regressions

- None, we retained the existing behaviour except for the error-case, which wasn't working

## Are the repro steps accurate/minimal?

See the test comments above for more detail.

**Comment by ikogan** [comment]
We may have experienced this on 2.8.3 to the point that one of our clusters fully failed. We found over 37,000 impersonation secrets for the same account. Whenever we would start the cluster agent, our cp nodes would all fill up memory in the api-server and etcd and start OOMKilling critical processes.

All of these tokens were created for a single service account for a pod (Portworx) running in the cluster. Once we terminated that pod, Rancher stopped creating impersonation tokens.

**Comment by riuvshyn** [comment]
We have same problem, alot of stale impersonation secrets in all managed clusters:
```
k -n cattle-impersonation-system  get secrets  | wc -l
   18307
```

And it is only growing...

**Comment by Byh0ki** [comment]
Hello,

We are hitting the issue after an upgrade from 2.7.5 to 2.8.5, is there any work around?

**Comment by samjustus** [comment]
@bigkevmcd @brudnak not sure if this was closed on purpose but it appears it hasn't been fully tested yet so reopening?

**Comment by snasovich** [comment]
@samjustus , moved this one back to "In Progress" as we're reverting the PR merged for it - https://github.com/rancher/rancher/pull/46086

**Comment by xhejtman** [comment]
Hello, in mean time, is it safe to delete the secrets from `cattle-impersonation-system`? I believe it slows down rancher UI, having 70k of secrets there.

**Comment by sosimon** [comment]
This is very similar, if not the same, as https://github.com/rancher/rancher/issues/43717

**Comment by bigkevmcd** [comment]
@xhejtman Yes, you should be able to, worst case it will create a new one...we are still working on a fix for this.

**Comment by vincebrannon** [comment]
See here for a band-aid for the issue:
https://github.com/ryanelliottsmith/cleanup-impersonation-secrets/tree/main

**Comment by Priyashetty17** [comment]
The fix doesn't completely eliminate duplicates. Closing this issue in favor of https://github.com/rancher/rancher/issues/47126 where cleanup of secrets is implemented.
