### ISSUE TITLE
master - Strange message on Add stack page

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4435]
Version  - master 4/15

Steps to Reproduce: 
1.  Add a stack

Results: Strange message at bottom
![image](https://cloud.githubusercontent.com/assets/11514927/14572959/c69eeaaa-0306-11e6-9b63-a8948e5a9642.png)

Expected: Not sure what that message is for

**Comment by vincent99** [comment]
https://github.com/rancher/ui/pull/585

**Comment by tfiduccia** [comment]
Message is no longer there.  Closing
