### ISSUE TITLE
[BUG] Rancher logs spamming error: "failed to write audit log"

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#44359]
**Rancher Server Setup**
Rancher Cluster:
Rancher version: 2.7.9
Number of nodes:
Node OS version: EKS 1.25

**Describe the bug**
The customer is seeing the following spammed in the Rancher pod logs:

` [WARNING] Failed to write audit log: failed to compact audit log: invalid character '}' looking for beginning of value`

Using local accounts and no special auth providers.

**To Reproduce**
Troubleshooting steps:

    Confirmed how they set up audit logging. They enabled it via --set auditLog.level=3 when doing a helm install.
    Checked if they see it with less verbose log levels. This ONLY affects log level 3....if they go to 1 or 2, there is no issue. 
    Collected Rancher pod logs (-c rancher and -c rancher-audit-log)

Repro steps:

     I could repro this on Rancher 2.7.9 by using the --set auditLog.level=3 flag when upgrading Rancher via helm

**Additional context**
SURE-7530
https://github.com/rancher/rancher/issues/38323

**Comment by JonCrowther** [comment]
For reference, the error likely comes from here:
https://github.com/rancher/rancher/blob/0c020f0c6846ddfe1c66e2a9f8ac1ebef3b171c6/pkg/auth/audit/filter.go#L98

**Comment by pankajsqe** [comment]
Retest passed on rancher v2.9.0-alpha5 with EKS cluster 1.28. There were no "Failed to audit log" message in Cattle-system-rancher-* pods PFA

![Image](https://github.com/rancher/rancher/assets/149133120/1c14f038-8241-46b5-9e2b-8eac42a31e0f)
