### ISSUE TITLE
[BUG] [2.7.11] custom rke2 cluster upgraded to v1.26.8+rke2r1 has issues with limitranges and clusterauthtokens 

### ISSUE THREAD

**Issue by MbolotSuse** [rancher/rancher#44406]
Rancher Server Setup

Rancher version: 2.7.5
Kubernetes version: upgrade RKE2 from 1.24.13 to 1.26.8
Describe the bug
The customer upgraded their custom downstream RKE2 cluster from RKE2 1.24.13 to 1.26.8 and afterwards, they noticed they do not see limitranges created for new namespaces they create in a projec tthat has the "Container Default Resource Limit" fields set. Prior to the upgrade, the limitranges were created for these new namespaces. The customer also said this broke clusterauthtokens when generating new kubeconfig files with ACE enabled.

To Reproduce

Result
When a new namespace is created in a project that has Container Default Resource Limits defined, a limit range is not created created for that namespace. Also, when creating a new kubeconfig file, a new token is not created.

Expected Result
When a new namespace is created in a project that has Container Default Resource Limits defined, a limit range should be created for that namespace. Also, when creating a new kubeconfig file, a new token should be created.

SURE-7013

Forward port of https://github.com/rancher/rancher/issues/43202

**Comment by MbolotSuse** [comment]
#44404

**Comment by joesims22** [comment]
I have validated the P0 test cases on v2.7.11-head on commit `fc2c10a`

- [x] Fresh install Check - Downstream RKE2 Cluster with K8s v1.27 and ACE enabled
- [x] Fresh install Check - Downstream K3s Cluster with K8s v1.27
- [x] Upgrade Check - Downstream RKE2 Cluster with K8s v1.26
- [x] Upgrade Check - K8s upgrade from v1.24 to v1.26 with Rancher upgrade

**Comment by snasovich** [comment]
Closing this issue as validation was successful.
