### ISSUE TITLE
[RFE] Upgrade alert manager to 0.26.x

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#44409]
Components:
- [x] Bump the alertmanager image in the chart
  - Resolves CVEs
  - Allows users to consume the newer official configs like teams receivers into raw alertmanager configs stored in configmaps / secrets

- [ ] Bump the Alertmanager CRDs that contain the newer alertmanager config changes introduced in 0.26
  -  Users can consume the the new configuration options via the CRDs

- [ ] Add UI for configuring the new options exposed in the alertmanager configs
  - Allows users to consume the new configuration options via the UI

- [ ] Documentation updates

- [ ] Deprecate the prom2teams alerting driver once the majority of the above items in this issue have been completed

- [ ] Remove the prom2teams alerting driver from the charts repo and from the alertmanager webhook UI

### Backporting considerations

2.8.X

SURE-7727

**Comment by pankajsqe** [comment]
Retest passed : Upgrade alert manager to 0.26.x

Test scenarios:
* verified “Upgrade alert manager to 0.26.x” on local cluster.
* verified “Upgrade alert manager to 0.26.x” downstream cluster.
* verified  “Upgrade alert manager to 0.26.x” using rancher upgrade from rancher 2.8.5 to 2.9.0-alpha7.
* verified Update logging-operator by upgrading, downgrading and uninstalling logging chart .
 
Rancher version: 2.9.0-alpha7
RKE2 : v1.29.4+rke2r1 
monitoring  : rancher-monitoring:104.0.0+up45.31.1 
mirrored-prometheus-alertmanager:v0.26.0




![Image](https://github.com/rancher/rancher/assets/149133120/d857e9e4-c679-4ca1-8447-c7eb31e91fd7)
![Image](https://github.com/rancher/rancher/assets/149133120/2fd9bac2-84b5-4473-94d0-04ed2fa2ce45)
![Image](https://github.com/rancher/rancher/assets/149133120/2ddae6fb-f749-4d2a-bbfe-e1776658ea2c)
