### ISSUE TITLE
Upgrade to 1.29.1/1.28.6/1.27.10 forced recreation of etcd/control plane nodes

### ISSUE THREAD

**Issue by kingnarmer** [rancher/rancher#44407]
I did upgrade three clusters to latest of 1.29/1.28/1.27 this morning and upgrade process forced recreation of etcd/control plane nodes and one worker node.  The clusters are running on rancher 2.8.1.

Is this expected ? 

Thanks 

**Environmental Info:**
RKE2 Version:  1.29.0 --> 1.29.1 , 1.28.5 --> 1.28.6, 1.27.9 --> 1.27.10

Node(s) CPU architecture, OS, and Version: 

Cluster Configuration:

2 control plane VMs, 3 etcd VMs, 3 workers. 

**Describe the bug:**

Upgrade to 1.29.1/1.28.6/1.27.10 forced recreation of etcd/control plane nodes and replace of  ONE worker node.  
**Steps To Reproduce:**

- Installed RKE2: 

**Expected behavior:**

Upgrade to new release without replacing nodes. 

**Actual behavior:**

Upgrade forced recreation of etcd/control plane nodes and replace of  ONE worker node.  
**Additional context / logs:**

**Comment by sba30** [comment]
Where these VMs on vsphere?

**Comment by sba30** [comment]
We have seen an issue, we upgraded from rancher mgmt 2.7.6 to 2.8.1, following this migration to 2.8.1 the first configuration change we made to a cluster then forced a recreate off the whole cluster control planes and workers.

**Comment by kingnarmer** [comment]
Thanks , what might have caused this behavior? I am tying to avoid this behavior on prod clusters if possible.

**Comment by sba30** [comment]
this issue looks to be related to the 2.8.1 upgrade where new values are injected into the VmwarevsphereMachineTemplate. Apparently there is a fix in an upcoming 2.8.x release
