### ISSUE TITLE
hosts cannot communicate with each other

### ISSUE THREAD

**Issue by jojobo** [rancher/rancher#4441]
Rancher Version: 1.0.1

Docker Version: 1.1

OS:  docker

Steps to Reproduce:  install rancher on two hosts, simple worpress app, scale  down, so that database container is on one host, while the wordpress container is on the other.

I installed rancher on a single host and a simple wordpress app and everything worked fine.
Then I installed rancher agent on another host, and scaled the wordpress app from 2 to 4 containers, expecting performance to duoble up. The process was smooth and two new wordpress containers appeared on the new host. But performance got halved instead of increasing.
So I scaled down wordpress to 1 container, so that the wordpress container was on one host, while database container was on the other host. 
At this point the site went down.  `504 Gateway Time-out
The server didn't respond in time.`
I did open ports 500 4500 udp, but still nothing.
It looks the two hosts could not communicate with each other, even though scaling up and down containers works very well on both hosts.

**Comment by deniseschannon** [comment]
Scaling up and down containers are independent of cross host communication. Have you looked through the FAQs on why it might be broken.

A simple way to test is to exec into a network agent on host A and ping the network agent's IP (10.42.x.x) on host B.

**Comment by deniseschannon** [comment]
http://docs.rancher.com/rancher/faqs/

**Comment by deniseschannon** [comment]
@jojobo If you can confirm whether or not cross host communication is working in your setup, then please re-open.
