### ISSUE TITLE
[Backport v2.7] [BUG] kontainer-engine-driver-lke consistently fails to start

### ISSUE THREAD

**Issue by lgarber-akamai** [rancher/rancher#44425]
Backport issue of rancher/rancher#44168 for Rancher 2.7.x

**Comment by snasovich** [comment]
This is to be validated by @lgarber-akamai FYI @daviswill2

**Comment by lgarber-akamai** [comment]
Validated against [v2.7-head (7ef5c81)](https://hub.docker.com/layers/rancher/rancher/v2.7-7ef5c81947bb0240d26cf017ff8725357116b35c-head/images/sha256-7c04ad17d02bef68abd8a18476fbe37926e7edc3b87b24f35240861d9783a489?context=explore) and everything seems to be working as expected 🙂

**Comment by snasovich** [comment]
Closing per the above comment. FYI @daviswill2
