### ISSUE TITLE
Wrong option list when adding an 'other' host and choosing a driver

### ISSUE THREAD

**Issue by Pseudonomy** [rancher/rancher#4442]
Rancher Version: 1.01

Docker Version: 1.10.3

OS: Arch linux

Steps to Reproduce: 

Under infrastructure -> hosts -> other -> choose driver hyper-v and virtualbox options will show up
Under infrastructure -> hosts -> other -> choose driver virtualbox and hyper-v options will show up

Results: 

Not the right options

Expected:

Vice versa

**Comment by Pseudonomy** [comment]
Trying to create a rancher host with hyper-v (which shows virtualbox options) then fails with:

Error with pre-create check: "Powershell was not found in the path"

**Comment by Pseudonomy** [comment]
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.0.1` Cattle: `v0.159.7` UI: `v1.0.5` |
|Access|`Disabled`|
|Route|`hosts.new.other`|

**Comment by deniseschannon** [comment]
@Pseudonomy I'm unable to reproduce the wrong options showing up. 

Have you tried looking at the docker-machine command, which can be found in the rancher server logs to see if you can launch a host iwithout using Rancher but using the same docker-machine command?

**Comment by Pseudonomy** [comment]
Couldn't find the command in the rancher server logs: https://gist.github.com/Pseudonomy/0ff5c9b731973863ddeec5a914411c2e

When should it show up?

**Comment by deniseschannon** [comment]
Lines 92 is the command that launched your docker-machine command to add in hyper-V. Line 98 is the error that came from docker-machine.

**Comment by Pseudonomy** [comment]
You may close this issue, will re-open if I'm able to reproduce.

**Comment by dexterddit** [comment]
I get the same issue. @deniseschannon  when you tried to reproduce the issue did you use Docker Toolbox for windows or Docker for Windows ?

**Comment by deniseschannon** [comment]
@dexterddit We currently don't support Docker for Windows. 

What version of Rancher are you running?

**Comment by dexterddit** [comment]
Rancher 	v1.1.3
Cattle 	v0.165.8.1
User Interface 	v1.1.12
Rancher Compose 	v0.8.6

**Comment by sathishbaburathinavel** [comment]
Now support added to Windows Container. Followed the instruction in [docker doc](https://docs.docker.com/machine/drivers/hyper-v/) and still can see this issue. 

**docker command used:**
`docker-machine create -d hyperv --hyperv-virtual-switch "Primary Virtual Switch" manager1`

**Error**
`Error with pre-create check: "Powershell was not found in the path"`

**Version Info:**
Windows 10 (OS Build 14393.351)
Docker Version : Docker version 1.13.0-dev, build b34b29e
