### ISSUE TITLE
[RFE] Add 1.28 support to KDM 2.8 PR CI

### ISSUE THREAD

**Issue by jakefhyde** [rancher/rancher#44427]
Parent Issue: https://github.com/rancher/rancher/issues/43109

**Is your feature request related to a problem? Please describe.**

Add support for RKE1/K3s 1.28 to KDM PR CI

**Comment by chiukapoor** [comment]
@jakefhyde while working on v1.28 support in KDM I updated the drone file to add support v1.28 in CI, does this suffice https://github.com/rancher/kontainer-driver-metadata/pull/1293/commits/22c4e630d3a12b9bbb6795b26065b663ff2cea0a?

**Comment by jakefhyde** [comment]
@chiukapoor Yes that looks sufficient, thank you!

**Comment by snasovich** [comment]
Closing it as https://github.com/rancher/kontainer-driver-metadata/pull/1293 is now merged.
