### ISSUE TITLE
HSTS on HAProxy

### ISSUE THREAD

**Issue by jmatsushita** [rancher/rancher#4443]
Is there a recommended approach to setup HSTS at the LB level?

**Comment by deniseschannon** [comment]
In order to set it up, you'll need the ability to customize the HAProxy `backends`, which isn't in Rancher yet. Closing this issue in favor of the issue which will be allowing customization for HAProxy backends.

https://github.com/rancher/rancher/issues/2179

**Comment by blaggacao** [comment]
Some on topic reasoning: Rancher UI is supercool! Graylog is supercool! Influx TICK stack is supercool!
While rancher comes with UI auth, just as graylog, chronograf doesn't and even worse, some workhorse API endpoints (graylog GELF input!!!) need to be publicly reachable from browser clients or docker daemons in order for Admin Interfaces or log streaming to work. Horrible! This is where a smooth HSTS would unfold it's unbeaten value.

**Comment by RonWilliams** [comment]
To implement the Strict-Transport-Security (HSTS) header in Rancher, add the following to the haproxy.cfg customization within the Rancher UI:

`frontend 443
        http-response set-header Strict-Transport-Security max-age=16000000;`

You can also use a backend condition which allows HAProxy to insert the header only when certain backends are used:

`backend 80
        http-response set-header Strict-Transport-Security max-age=16000000;`

Thanks @aemneina for the recommendation!
