### ISSUE TITLE
[RFE] Add support for separate UI banner settings

### ISSUE THREAD

**Issue by nwmac** [rancher/rancher#44439]
See UI new feature: https://github.com/rancher/dashboard/issues/7366

Internal Reference: SURE-7619

For this feature, the UI will support optional individual features for the UI banners - these new settings contain the same information as in the existing `ui-banners` setting, but by breaking them out, this simplifies the deployment of configurations of Rancher to set an individual banner but retain existing banners.

The 3 optional settings are:

- `ui-banner-header`
- `ui-banner-footer`
- `ui-banner-login-consent`

We require a backend change to allow these settings to be available to the non-authenticated user, just as the existing `ui-banners` resource is - I believe this requires adding these setting names here: https://github.com/rancher/rancher/blob/ee987a841b57ed2e23c2dfe5e0bffd9efd75833a/pkg/data/dashboard/rbac.go#L23

We don't need these settings to be created by the backend - users will create them manually if they wish to configure banners using this mechanism.

**Comment by pmatseykanets** [comment]
Since v2.9 *ALL* settings should be known to Rancher, otherwise they will be deleted on Rancher (re)start.
The missing settings should be added to https://github.com/rancher/rancher/blob/0818029db0b85d270561b1bbb6af0bed287ced64/pkg/settings/setting.go#L327-L336

**Comment by pmatseykanets** [comment]
Never mind, I see that they were already added https://github.com/rancher/rancher/blob/0818029db0b85d270561b1bbb6af0bed287ced64/pkg/settings/setting.go#L315-L317

**Comment by prachidamle** [comment]
yes this was added to settings and can be closed. QA for this https://github.com/rancher/dashboard/issues/7366 seemed to have covered the changes.
