### ISSUE TITLE
[BUG] [2.8] CLI panics when trying to kubectl after a login

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#44447]
backport #44332

**Comment by enrichman** [comment]
Same test of the original fix: https://github.com/rancher/rancher/issues/44332#issuecomment-1942079900

**Comment by anupama2501** [comment]
Reproduced on v2.8.0 version of rancher CLI. 
1. Configure 2.8.0 rancher cli version
2. Created a rancher server on 2.8-head c474333
3. On the UI, set `kubeconfig-generate-token` = false from the global settings.
4. Using the rancher cli, run the following commands and notice rancher panics:
     a. `~/Downloads/rancher-v2.8.0/rancher login https://<RancheURL>/v3-public/authProviders --name <RancherIP> --token <YourBearerToken>` >> Rancher Panics 
    b. Remove the config file /home/.rancher/cli2.json and run from the cli `rancher server current` >> Rancher Panics

```
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/rancher/cli/cmd.cacheCredential(0xc000127760, 0xc0003963c0, {0xc00038ea50, 0x6})
	/go/src/github.com/rancher/cli/cmd/kubectl_token.go:283 +0x11a
github.com/rancher/cli/cmd.runCredential(0xc000127760)
	/go/src/github.com/rancher/cli/cmd/kubectl_token.go:165 +0x4a5
github.com/urfave/cli.HandleAction({0x16a8280?, 0x182c078?}, 0xc000132fc0?)
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:524 +0x50
github.com/urfave/cli.(*App).RunAsSubcommand(0xc000132fc0, 0xc000127600)
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:410 +0xabd
github.com/urfave/cli.Command.startApp({{0x17d7342, 0x5}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x17f6835, 0x2e}, {0x0, ...}, ...}, ...)
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:372 +0xb7f
github.com/urfave/cli.Command.Run({{0x17d7342, 0x5}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x17f6835, 0x2e}, {0x0, ...}, ...}, ...)
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:102 +0x845
github.com/urfave/cli.(*App).Run(0xc000132e00, {0xc0000b94c0, 0x4, 0x4})
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:277 +0xb67
main.mainErr()
	/go/src/github.com/rancher/cli/main.go:136 +0x1f5d
main.main()
	/go/src/github.com/rancher/cli/main.go:57 +0x1
```


Note: Did not notice a panic when --name is not passed not when the name is set to non Rancher URL. F.e: --name=test

**Comment by anupama2501** [comment]
Spoke offline and moving the issue to next milestone for the re opened issue https://github.com/rancher/rancher/issues/44447#issuecomment-1998171631 

For the other issue that was resolved, created a new ticket and added comments to it. https://github.com/rancher/rancher/issues/44811

cc @enrichman @samjustus

**Comment by enrichman** [comment]
After more tests we have seen that it was an issue related to some conflicting binaries during tests. Closing!
