### ISSUE TITLE
[Backport v2.8] Add docker version v25.0.x

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#44459]
Backport of https://github.com/rancher/rancher/issues/44388

Add 25.0.x versions of Docker released by the time work starts on this ticket (25.0.0 - 25.0.3 at the time of this update per https://docs.docker.com/engine/release-notes/25.0).

Refer to https://github.com/rancher/rancher/issues/41851 for implementation/testing steps.

SURE-7606

**Comment by snasovich** [comment]
@mitulshah-suse / @chiukapoor / @krunalhinguu , I'm not seeing references to 24.0 updated to 25.0 in `rancher/rancher` - e.g. https://github.com/rancher/rancher/blob/6e90cf0f9b9b6d6ec3864e082fe949795d3a69fb/pkg/settings/setting.go#L65

I think we need equivalent of https://github.com/rancher/rancher/pull/42087 done first and maybe even some UI-side changes (please review issues/PRs linked to https://github.com/rancher/rancher/issues/41851).

**Comment by mitulshah-suse** [comment]
@snasovich we cannot update it in rancher/rancher until the scripts are released from install-docker. They point to the release repo in rancher/rancher and if we update that right now everything will start breaking in rancher repo.
Testing with the changes done in KDM is currently in progress. Once completed, we first need to release the install-docker scripts for docker 25.0.x and then we can update the rancher/rancher repo with these changes.

**Comment by snasovich** [comment]
@mitulshah-suse , thank you for the clarifications. What's the ETA on completing these?
@kinarashah , heads-up we will want `install-docker` scripts releases asap after "go ahead" to unblock Rancher-side changes.

**Comment by dcermak** [comment]
Vivek Shilimkar ***@***.***> writes:

> Tested the docker version 25.0.x on `RHEL (9.3, 9.2, 9.1, 9.0, 8.8 and 8.7)` and `Oracle Linux (9.3, 9.2, 9.1)`. Node driver and custom cluster provisioning works well with the docker versions v25.0.x.
>
> Latest docker supported docker version on SLES15SP5 and Opensuse 15.5 is `24.0.7_ce`. Hence, the docker version v25.0.x can't be tested on these OSes.

We have not updated docker to 25 on SLES & openSUSE Leap to not break
Rancher. So this is a chicken-or-egg problem.

**Comment by rishabhmsra** [comment]
Docker install script 25.0.x validation completed on node driver as well as custom clusters using below latest OSes versions :
- RHEL 8.9 and 9.3
- Ubuntu 22.04
- OL 8.9 and 9.3
- Rocky 8.9 and 9.3
- CentOS 7.9

**Comment by kinarashah** [comment]
@mitulshah-suse Released docker v25.0.3. `https://releases.rancher.com/install-docker/25.0.sh` now points to `25.0.3`.
