### ISSUE TITLE
Add Docker version v24.0.8 to v24.0.9

### ISSUE THREAD

**Issue by krunalhinguu** [rancher/rancher#44465]
Following versions to be added 

```
24.0.8
24.0.9
```

Reference for implementation & testing: https://github.com/rancher/install-docker/pull/123

**Comment by slickwarren** [comment]
what milestone is this for?

**Comment by mitulshah-suse** [comment]
These install-docker issues are not usually linked to milestones, since they are released independently as soon as testing is completed.

**Comment by kinarashah** [comment]
Done, 

- [x] https://releases.rancher.com/install-docker/24.0.sh points to 24.0.9 
- [x] https://releases.rancher.com/install-docker/24.0.8.sh available 
- [x] https://releases.rancher.com/install-docker/24.0.9.sh available

**Comment by vivek-shilimkar** [comment]
Tested cluster provisioning with docker v24.0.8 and v24.0.9 on 
- Ubuntu 
- Rocky
- RHEL
- CentOS
- Oracle Linux. 
Provisioning works correctly on above mentioned OSes and docker versions. Docker versions are already released and working as expected, closing this issue.
