### ISSUE TITLE
Cannot connect to rancher-agent on localhost or docker machine. No open ports when running docker ps -a?

### ISSUE THREAD

**Issue by Pseudonomy** [rancher/rancher#4446]
Rancher & docker version:
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.0.1` Cattle: `v0.159.7` UI: `v1.0.5` |
|Access|`Disabled`|
|Route|`virtualmachines.index`|

OS: 
---
Manjaro linux latest

Steps to Reproduce: 
---

Run rancher server on localhost with ```sudo docker run -d --restart=always -p 8080:8080 rancher/server```

**Localhost:** changing IP to `http://172.17.0.3:8080` at `http://127.0.0.1:8080/admin/settings` like the quick start guide instructs. IP is reachable with ping.

**Docker machine:** changing IP to `http://192.168.99.100:8080` at ```http://127.0.0.1:8080/admin/settings``` like the quick start guide instructs. IP is reachable with ping.

Then trying to run the rancher-agent at `http://127.0.0.1:8080/env/1a5/infra/hosts/add/custom`

**Localhost:** at optional enter `http://172.17.0.3:8080` or `172.17.0.3` and run the following string to register with server `sudo docker run -e CATTLE_AGENT_IP='172.17.0.3 or http://172.17.0.3:8080'  -d --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.0.1 http://172.17.0.3:8080/v1/scripts/577F8B2163A3E7671EB9:1460901600000:LWYTRRDjgx5XM5CEKkj3ckyEEY`

**Docker machine:** nothing at optional just running the string inside docker machine `sudo docker run -d --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.0.1 http://192.168.99.100:8080/v1/scripts/577F8B2163A3E7671EB9:1460901600000:LWYTRRDjgx5XM5CEKkj3ckyEEY`

Results: 
---

Nothing happens, host doesn't show up. When I run a docker ps -a from localhost or inside the docker machine there are no open ports.

Expected:
---

Host to show up. Open ports to be able to connect?

**Comment by deniseschannon** [comment]
I see that you have changed your IP to follow the quick start guide exactly. You should keep whatever IP that you have. The quick start guide just has example IPs. 

The key in the quick start guide is that it's trying to show you what you should set when you re-use the same machine that is running Rancher server to be added as a host.

http://docs.rancher.com/rancher/rancher-ui/infrastructure/hosts/custom/#adding-hosts-to-the-same-machine-as-rancher-server

You should keep the IPs that your actual localhost and docker-machine provide.

**Comment by Pseudonomy** [comment]
Got it now, had to use my local ip `192.168.1.12` instead of `127.0.0.1` at `http://192.168.1.116:8080/admin/settings`.

Took me a long time to figure out, somehow wasn't clear.

**Comment by bayboraoren** [comment]
@deniseschannon  http://docs.rancher.com/rancher/rancher-ui/infrastructure/hosts/custom/#adding-hosts-to-the-same-machine-as-rancher-server link is broken
