### ISSUE TITLE
[Backport v2.8] Default RKE1 Node template image for Linode fails to provision w/ Error installing Docker

### ISSUE THREAD

**Issue by lgarber-akamai** [rancher/rancher#44478]
This issue is a backport of #44179 for Rancher v2.8.x.

**Comment by Josh-Diamond** [comment]
Ticket #44478 - Test Results - ✅ 
---

Verified on Rancher `v2.8-ed032a465c8104af396c559640178b00b83c1960-head`:

| Scenario | Test Case | Result |
|---|---|---|
| 1. | Provision downstream RKE1 Linode Node driver w/ defaults | ✅ |

---

Scenario 1 -
1. Fresh install of Rancher `v2.8-head`
2. Provision a downstream RKE1 Linode Node driver cluster, using Rancher defaults
3. Verified - Cluster successfully provisions; as expected
