### ISSUE TITLE
[v2.7.11] sync changes from custom jan patches branches to dev branches for RKE and KDM 

### ISSUE THREAD

**Issue by vardhaman22** [rancher/rancher#44492]
tracking issue for jan patches to be synced with dev branches (release/v1.4 for rke and dev-v2.7 for KDM)

More context on specifically what this issue is about: https://github.com/rancher/rancher/issues/44492#issuecomment-1951764300

**Comment by snasovich** [comment]
Due to the timing of releases (`v2.7-Patch1` is likely to be released before Jan patches) changing the milestone to `v2.7-Next1`.

**Comment by mitulshah-suse** [comment]
@snasovich i think you got confused between Jan and Feb patches. Jan patches are already released, and this issue is to get those changes regarding runc and containerd which went into RKE into 2.7.11 as well, which is why the milestone was `2.7-Patch1`

**Comment by snasovich** [comment]
@mitulshah-suse , correct. Changed milestone to `v2.7-Patch1`.

**Comment by vivek-shilimkar** [comment]
Tested a k8s cluster v 1.27 with rancher v2.7.11-rc3 and standalone RKE v1.4.15-rc4. Cluster creation works fine. Ticket can be closed.
