### ISSUE TITLE
[v2.8] Sync Feb Patches to dev-v2.8

### ISSUE THREAD

**Issue by vardhaman22** [rancher/rancher#44520]
tracking issue to merge release-v2.8 to dev-v2.8 after feb patches are released.

Also We [introduced 1.28.6 in KDM](https://github.com/rancher/kontainer-driver-metadata/pull/1293) as part of [1.28 support issue](https://github.com/rancher/rancher/issues/43109).
v1.28.7 is now released, so we need to update KDM and RKE with v1.28.7.
Note: Only v1.28.7 will be released, so replace v1.28.6 with v1.28.7 in KDM.

**Comment by chiukapoor** [comment]
v2.8 https://github.com/rancher/kontainer-driver-metadata/pull/1354

**Comment by rancher-max** [comment]
`dev-v2.8` looks good for k3s and rke2 ✅

**Comment by vivek-shilimkar** [comment]
`dev-v2.8` looks good for rke1.
