### ISSUE TITLE
Dashboard failed to run on Kubernetes

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#4452]
#### Rancher Version:
1.0.1
#### Docker Version:
1.9.1
#### Kubectl Version: 
1.2.0
#### Steps to Reproduce: 
run the kubernetes-dashboard.yaml file from the repo, and add the argument `--apiserver-host=https://10.43.0.1`

#### Results: 
I was able to access the ui but i got the following error:

```
Internal Server Error (500)

Get https://10.43.0.1/api/v1/replicationcontrollers: x509: failed to load system roots and no roots provided
```

**Comment by deniseschannon** [comment]
I don't think it will make a difference, but can you try running on Docker 1.10.3. That is the current minimum supported Docker version for Rancher.

**Comment by galal-hussein** [comment]
I tried the dashboard on both versions of Docker, and still the same error.

**Comment by ibuildthecloud** [comment]
https://github.com/rancher/rancher-catalog/pull/163

**Comment by galal-hussein** [comment]
Dashboard is working with version  v1.1.0-dev5-rc2
