### ISSUE TITLE
Read Only user able to execute shell

### ISSUE THREAD

**Issue by jhogenlids** [rancher/rancher#44539]
**Rancher Server Setup**
- Rancher version: v2.7.5
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): Helm EKS
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.25.16-eks-77b1e4e
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Imported
* Imported = one Read-only user can still execute shell but others with same permission cannot 
* Hosted = EKS
 * Infrastructure Provider = AWS

**User Information**
- What is the role of the user logged in? (Custom)
  - If custom, define the set of permissions:
  - Standard User
  - get, list, watch on nodes, storage classes, clusterroles, notifiers, priorityclasses, validatingwebhooconfigurations, ingress classes

**Describe the bug**
A user which is read-only as described above was able to execute shell. Other users with the same permission were unable to execute shell.
We have a process that during deployment we elevate user's permission up to the max permission of a cluster owner, then once deployment was finished we remove the elevated permission and move back that user to read-only.
That user found-out that he can still execute shell using read-only access. I reproduce this to other user but other users didn't have the same symptoms.

**To Reproduce**
have a user with the same permission as above, then elevate its role up to a cluster owner and from time to time give permission to the default and system namespaces.

**Result**

**Expected Result**
That user should not be able to execute shell once back to read-only access

**Screenshots**

**Additional context**

**Comment by macedogm** [comment]
Hi @jhogenlids. I'm Guilherme from the Rancher Security team. Out of an abundance of caution, I'm moving this issue to a private repository, where we can better triage it. Please reach out to us in security-rancher@suse.com if you need any additional information. Thank you.
