### ISSUE TITLE
Commas are appearing on last value in JSON in the API area

### ISSUE THREAD

**Issue by StorminGorman** [rancher/rancher#4453]
Rancher Version: v1.0.1
Docker Version: 1.10.3
OS: Boot2Docker

Steps to Reproduce: 
1. Select View in API anywhere in the Rancher UI

Results: 
There is a comma at the end of all JSON arrays and objects

Expected:
The last element in the objects should not have a comma.  This makes quick and dirty experimentation via copying and pasting tough !

![unwanted-comma](https://cloud.githubusercontent.com/assets/13557499/14621671/20179d04-058a-11e6-9a9d-91320649f349.png)

**Comment by vincent99** [comment]
Yes, this is a bug in the json formatter/highlighter...

**Comment by loganhz** [comment]
Fixe in 2.0

**Comment by loganhz** [comment]
![image](https://user-images.githubusercontent.com/21168270/46382244-c9782880-c6dc-11e8-951d-51b33b82da83.png)
