### ISSUE TITLE
[Backport 2.7][BUG] NFS file locks with Kubernetes v1.24.10+ require manual intervention

### ISSUE THREAD

**Issue by mitulshah-suse** [rancher/rancher#44543]
Backport https://github.com/rancher/rancher/issues/41601

**Rancher Server Setup**
- Rancher version: 2.6.9
- Installation option (Docker install/Helm Chart): Helm chart; RKE1 v1.24.9-rancher1-1
- Proxy/Cert Details: LetsEncrypt via cert-manager

**Information about the Cluster**
- Kubernetes version: v1.24.13-rancher2-1, v1.24.10-rancher4-1, v1.24.9-rancher2-1 tested
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Rancher-provisioned vmware vSphere nodes, sourced on Ubuntu 20.04 templates

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Admin
  - If custom, define the set of permissions: N/A

**Describe the bug**
Kubernetes v1.24.10-rancher4-1 and newer seem to have broken NFS client file locking. We use a number of NFS shares in Persistent Volumes and some databases -- mongodb and mysql in particular -- are no longer able to lock certain files, leading them to exit with errors about no locks being available. File locking works if the rpc-statd service on the underlying node is manually started, but this is not necessary with Kubernetes v1.24.9 and below.

Actually mounting, writing to, and reading NFS shares is not impacted. File locking seems to be the only issue.

If a node is running v1.24.9 and upgraded to v1.24.10+, existing pods are not affected. If a single pod on the node was using NFS file locking, then any new pods are able to successfully lock files even after upgrading Kubernetes. Once all pods using NFS file locking are deleted, new pods are unable to utilize locking on NFS shares.

MongoDB logs show similar entries to this:
> 2023-05-18T19:03:25.914+0000 I STORAGE [initandlisten] exception in initAndListen: DBPathInUse: Unable to lock the lock file: /data/mongod.lock (No locks available). Another mongod instance is already running on the /data directory, terminating

The kernel produces logs similar to this:
> [Thu May 18 15:03:19 2023] lockd: cannot monitor nfs-server.example.org

**To Reproduce**
- Deploy a Kubernetes v1.24.9 (any -rancher subversion)
- Create a Persistent Volume and associated claim that uses default NFS mount options (no mountOptions in storageclass, etc)
- Deploy a database that utilizes file locking (a 3-node mongodb instance with the MongoDB community operator works) using the aforementioned NFS-based persistent volume for its data directory
- Wait for statefulset to become Running
- Upgrade Kubernetes cluster to v1.24.10+ (tested up to v1.24.13-rancher2-1)
- Delete any of the mongodb pods

**Result**
mongodb instances are unable to create a file lock on its lockfile, stating that there are no locks available.

**Expected Result**
mongodb (and other processes) should be able to lock its lock file

**Screenshots**
N/A

**Additional context**
https://github.com/coreos/bugs/issues/2038#issuecomment-313483221 seems to follow the same behavior that we're seeing, but is from 2017. We've allowed Rancher to recreate nodes and have replaced all workers in our testing. The only thing that seems to affect the behavior is the Kubernetes version that we're running. We wanted to upgrade to v1.24.10+ to avoid the known CPU issues, but it appears that either upstream Kubernetes (re-)introduced this bug or the fix to address high dockerd CPU usage.

**Comment by vivek-shilimkar** [comment]
Tested the NFS file locks issue with rancher v2.7.11-rc3 and on k8s v1.27.11-rancher1-1. Issue isn't active anymore. Hence closing the issue.
