### ISSUE TITLE
[Azure Integration] Can't add Azure hosts

### ISSUE THREAD

**Issue by pengjiang80** [rancher/rancher#4455]
Rancher Version: both v1.0.0 and v1.0.1

Docker Version: v.1.10.0

OS: CentOS 7.2.1511 

Steps to Reproduce: 
1. Login to portal, click Infra - Hosts - Add host.
2. Input name, subscription id and subscript cert info, click create.

Results: 
The host will be in creating status and finally return “Error with pre-create check: "Get https://management.core.windows.net/3dd63d39-8c46-456c-b589-f73dfea152b9/services/hostedservices/operations/isavailable/ranchervm005: local error: internal error". 

Expected:
Add Azure hosts successfully

**Comment by ronikurnia1** [comment]
We've got the same issue here

**Comment by jsalva** [comment]
I'm experiencing something similar... 

```Error with pre-create check: "Code: ForbiddenError, Message: The server failed to authenticate the request. Verify that the certificate is valid and is associated with this subscription."```

I have verified both.

**Comment by jsalva** [comment]
and after using the raw cert (not base64 encoded), I get the extremely helpful error `exit status 3`
