### ISSUE TITLE
[RKE1] Can not set DeleteEmptyDirData to true, even with delete_local_data: true in node_drain_input

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#44564]
`rancher/rancher` tracking issue for https://github.com/rancher/rke/issues/3412

**Comment by jiaqiluo** [comment]
Closing this issue as it does not affect Rancher.

Because Rancher UI and the Terraform-proviver-rancher2 will always set the default values to the fields, the bug can be triggerred in Rancher.
