### ISSUE TITLE
[AWS&Azure China Integration] Add hosts from AWS&Azure China

### ISSUE THREAD

**Issue by pengjiang80** [rancher/rancher#4456]
Rancher Version: v1.0.0 and v1.0.1

Docker Version: v1.10.0

Steps to Reproduce: 
1. Login to portal, click Infra - Hosts - Add host.
2. Select Amazon EC2, input Access Key and Secret Key, click Next. 

Results: 
Get error  “AuthFailure: AWS was not able to validate the provided access credentials”. It seems Rancher posts the credential to ec2.us-west-2.amazonaws.com for authentication. But in China, there is a separated AWS cloud and independent authentication. Similar issue happens with Azure China.

Expected:
Add hosts with AWS&Azure China sucessfully.

**Comment by vincent99** [comment]
@pengjiang80 AWS should work as of around 1.2.0-pre1, we ask for the region first now.
