### ISSUE TITLE
[RFE] Add settings to customize login and landing page for non-logged in parameters to be passed to UI

### ISSUE THREAD

**Issue by torchiaf** [rancher/rancher#44577]
**Is your feature request related to a problem? Please describe.**

We want to add the ability to customize the Login Background and Banner images on Rancher UI.

**Describe the solution you'd like**

To add new settings:

1. `ui-login-background-light` - for the background, light theme image - It should be accessed by anonymous users (pre-login)
2. `ui-login-background-dark` - for the background, dark theme image - It should be accessed by anonymous users (pre-login)
3. `ui-banner-light` - for the banner, light theme image
4. `ui-banner-dark` - for the banner, dark theme image

**Additional context**

Related UI issue: https://github.com/rancher/dashboard/issues/10423

**Comment by gaktive** [comment]
The key part why the UI needs backend support here is:
>NOTE: This will require a change to backend to allow these new settings to be accessed by anonymous users.

**Comment by gaktive** [comment]
Internal Reference: SURE-4860

**Comment by gaktive** [comment]
@torchiaf we should sync on this ticket since the corresponding dashboard ticket was closed but this still looks open. I'll reword the title since it's confusing at first glance.

**Comment by gaktive** [comment]
Work done in https://github.com/rancher/rancher/pull/44961 as noted so this is done. The QA portion of this I'm not sure of but UI confirmed that this is working so this has had some testing.
