### ISSUE TITLE
[Azure Integration] "Read from file" button issue 

### ISSUE THREAD

**Issue by pengjiang80** [rancher/rancher#4457]
Rancher Version: v1.0.1
 
Docker Version: v.1.10.0

OS: 

Steps to Reproduce: 
1. Login to portal, click Infra - Hosts - Add host.
2. Input name, subscription id.
3. When using the “read from file” button around “publish setting file” field, the content will be read and displayed in “Subscription Certs” area.   
4. Click next

Results: 
Got error "Error with pre-create check: "Code: ForbiddenError, Message: The server failed to authenticate the request. Verify that the certificate is valid and is associated with this subscription.""

Expected:

**Comment by tfiduccia** [comment]
Version - master 4/28
Verified fixed
