### ISSUE TITLE
[BUG] ETCD plane hangs while trying upgrade local cluster from 1.26 to 1.27

### ISSUE THREAD

**Issue by susesgartner** [rancher/rancher#44580]
**Rancher Server Setup**
- Rancher version: 2.7.11-rc3
- Installation option HELM RKE1

**Information about the Cluster**
- Kubernetes version: 1.26
- Cluster Type: Local RKE1
-Infrastructure: AWS

**User Information**
- What is the role of the user logged in: admin

**Describe the bug**
While upgrading the local rke1 cluster from 1.26 to 1.27 the etcd plane hangs and the rancher instance fails to come up.

**To Reproduce**
1. Deploy a 3 node all role rke1 kubernetes cluster
2. Deploy rancher on top of the cluster created in step 1
3. Provision 3 downstream clusters (rke1, rke2, k3s)
4. Upgrade the local cluster from 1.26 to 1.27 using rke up

**Result**
The cluster hangs while waiting for the upgrade to complete.

**Expected Result**
The cluster upgrades successfully and all downstream clusters are in a healthy state

**Screenshots**
<img width="996" alt="Screenshot 2024-02-26 at 1 29 03 PM" src="https://github.com/rancher/rancher/assets/136753565/6e04ce7c-a44e-4131-84fb-282d66959507">

**Additional context**
When trying to set this up we attempted it using the deployer job and are currently trying it completely without automation.

**Comment by jiaqiluo** [comment]
This is an **existing behavior** of RKE CLI: 
RKE expects the nodes' `internal_address` to be consistent in the cluster config file if they are set initially. Otherwise, RKE will fail to upgrade the cluster because etcd hits a "bad certificate" issue.

The same behavior is observed in `RKE CLI v1.5.5` when upgrading a cluster from `v1.25.16-rancher2-2` (etcd v3.5.9) to `v1.26.13-rancher1-1` (etcd v3.5.10).

Workaround:
Adding the internal addresses back, then run `rke up` again. The upgrade will succeed. 

More findings:
- If the internal addresses are NOT set in the initial cluster config, and you add them along with the bump of the Kubernetes version, the upgrade will succeed!

**Comment by jiaqiluo** [comment]
The command `docker exec etcd etcdctl member list -w table` can be used to check the etcd cluster. 

When the `internal_address` is not set in the cluster config:
```
+------------------+---------+-------------------+---------------------------+---------------------------+------------+
|        ID        | STATUS  |       NAME        |        PEER ADDRS         |       CLIENT ADDRS        | IS LEARNER |
+------------------+---------+-------------------+---------------------------+---------------------------+------------+
| 21d421175c319407 | started | etcd-<public-ip-1> | https://<public-ip-1>:2380 | https://<public-ip-1>:2379 |      false |
| 3aaf510e6e850dd7 | started | etcd-<public-ip-2> | https://<public-ip-2>:2380 | https://<public-ip-2>:2379 |      false |
| e04e095bb89615a5 | started | etcd-<public-ip-3> | https://<public-ip-3>:2380 | https://<public-ip-3>:2379 |      false |
+------------------+---------+-------------------+---------------------------+---------------------------+------------+
```

After the `internal_address` is added and `rke up` succeed:
``` 
+------------------+---------+-------------------+---------------------------+---------------------------+------------+
|        ID        | STATUS  |       NAME        |        PEER ADDRS         |       CLIENT ADDRS        | IS LEARNER |
+------------------+---------+-------------------+---------------------------+---------------------------+------------+
| 21d421175c319407 | started | etcd-<public-ip-1> | https://<public-ip-1>:2380 | https://<private-ip-1>:2379 |      false |
| 3aaf510e6e850dd7 | started | etcd-<public-ip-2> | https://<public-ip-2>:2380 | https://<private-ip-2>:2379 |      false |
| e04e095bb89615a5 | started | etcd-<public-ip-3> | https://<public-ip-3>:2380 | https://<private-ip-3>:2379 |      false |
+------------------+---------+-------------------+---------------------------+---------------------------+------------+
```

**Comment by susesgartner** [comment]
Since this is user error there is nothing to fix here, closing this ticket out as there is nothing to do.
