### ISSUE TITLE
[RFE] Kubelet arguments for control plane and workers

### ISSUE THREAD

**Issue by dbravo0531** [rancher/rancher#44594]
**Is your feature request related to a problem? Please describe.**
Our control plane and workers are different in size and pod density, we cannot pass extra arguments depending on node roles and capacity

**Describe the solution you'd like**
Rancher allows passing extra arguments to all Kuberneets services (https://rke.docs.rancher.com/config-options/services/services-extras). We now have a case of adding kube-reserved and system-reserved arguments (https://kubernetes.io/docs/tasks/administer-cluster/reserve-compute-resources/), but our control plane and workers are different in size and pod density, so having same values is not very optimal.  How can we set different extra_args depending on node role?

**Describe alternatives you've considered**
Suggestion:
You can set different extra arguments based on the node roles. Try using the count and for_each mechanisms to iterate through the node pools and apply role-specific configurations as follows.
resource "rke_cluster" "my_rke_cluster" {
  name = "my-cluster"

  node_pools {
    name      = "control-plane"
    role      = "controlplane"
    count     = 3
    extra_args = {
      "key" = "value-for-control-plane"
      # Control plane specific extra arguments
    }
    ...
  }

  node_pools {
    name      = "worker-nodes"
    role      = "worker"
    count     = 5
    extra_args = {
      "key" = "value-for-worker-nodes"
      # Worker node specific extra arguments
    }
    ...
  }

  # Define common settings here
}

Response:
As I said, we are using https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster and NOT rke_cluster resource.  Basically what we do is define cluster itself using rancher2_cluster, and then either register nodes using token if this is onpremise or creating rancher2_node_pools if that is Azure. 

**Additional context**
We are using Terraform to manage our clusters, via rancher2_cluster resource: https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster (using rke_config block, which has services block)

**Comment by gthieleb** [comment]
Hi @dbravo0531 did you tried to solve your requirements with the `machine_label_selector` from the `rancher2_cluster_v2` resource. Was there a reason against using that resource?
