### ISSUE TITLE
Not able to set up rancher v1.0.1 in HA

### ISSUE THREAD

**Issue by epierotto** [rancher/rancher#4459]
Rancher Version: v1.0.1

Docker Version:
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:34:23 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:34:23 2016
 OS/Arch:      linux/amd64

OS: Ubuntu 14.04.3 LTS

Steps to Reproduce: 
Spin up 3 "Ubuntu 14.04.3 LTS" vagrant nodes and follow the instructions at http://docs.rancher.com/rancher/installing-rancher/installing-server/multi-nodes/

**vagrant n1:**
CONTAINER ID        IMAGE                   COMMAND                  CREATED             STATUS              PORTS                              NAMES
5180ac779398        rancher/server:v1.0.1   "/usr/bin/s6-svscan /"   41 minutes ago      Up 40 minutes       3306/tcp, 0.0.0.0:8080->8080/tcp   rancher-server
f4181fb53c49        percona:5.7.11          "/docker-entrypoint.s"   41 minutes ago      Up 41 minutes       0.0.0.0:3306->3306/tcp             rancher-db

mysql> use cattle;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> select * from DATABASECHANGELOGLOCK;
+----+--------+-------------+----------+
| ID | LOCKED | LOCKGRANTED | LOCKEDBY |
+----+--------+-------------+----------+
|  1 |        | NULL        | NULL     |
+----+--------+-------------+----------+
1 row in set (0.00 sec)

**vagrant n2:**
Using rancher-ha.sh script
root@n2:~# docker logs --tail=0 -f rancher-ha
time="2016-04-19T08:21:50Z" level=info msg="Waiting for server to be available" component=cert 
time="2016-04-19T08:21:50Z" level=info msg="Can not launch agent right now: Server not available at http://172.17.0.1:18080/ping:" component=service 

**vagrant n3:**
Using rancher-ha.sh script
Same as n2
root@n3:~# docker logs --tail=0 -f rancher-ha
time="2016-04-19T08:40:27Z" level=info msg="Waiting for server to be available" component=cert 
time="2016-04-19T08:40:27Z" level=info msg="Can not launch agent right now: Server not available at http://172.17.0.1:18080/ping:" component=service 

Results: 
Rancher -> Admin -> HA: Waiting for a host...

Expected: A running cluster

**Comment by str3tch** [comment]
I have the same issue, HA nodes don't start with the following log entry:

"time="2016-04-21T04:58:21Z" level=info msg="Waiting for server to be available" component=cert
time="2016-04-21T04:58:21Z" level=info msg="Can not launch agent right now: Server not available at http://172.17.0.1:18080/ping:" component=service"

Where does it get the ip address 172.17.0.1:18080 from?? is this the container IP?

FYI:

Running RancherOS v0.4.4

**Comment by amenophis** [comment]
Same problem here, with ubuntu 14.04.2 nodes.

**Comment by cloudnautique** [comment]
On the Ubuntu nodes, can you try with Docker 1.10.3. Docker 1.11.x isn't supported yet.

**Comment by duffyjay** [comment]
We're having this issue as well.  Ubuntu 14.04 with Docker 1.11, and also failed with Docker 1.10.3.

**Comment by str3tch** [comment]
hey guys, what load balancer are you using?

I've realised that in my setup I have AWS ELB which has issues with websockets.. it's just a hunch as I have not been able to try anything else just yet - but that might be the issue. 

After the weekend I can try it out without ELB in the picture.

**Comment by amenophis** [comment]
Tried with 1.10.3 and same problem after cleaning all running container

**Comment by iDiogenes** [comment]
I have the same setup as @str3tch RancherOS.0.4.4 with AWS ELB and am seeing the exact same issue. @str3tch did you have any luck setting up HA with ELB removed from the picture? As a side note I have been using ELB configured with the ProxyProtocol to permit websockets for a couple months now without issue.

**Comment by str3tch** [comment]
@iDiogenes I have now tried again with completely different setup. Same issue.

Now I am runnning 3 hosts on ESXi, Ubuntu 14.04, Docker version 1.10.3, build 20f81dd
No ELB, no AWS at all now, instead I'm using just a single DNS entry as load balancer for the three hosts.

Same error in logs:

> time="2016-04-29T03:00:17Z" level=info msg="Waiting for server to be available" component=cert 
> time="2016-04-29T03:00:17Z" level=info msg="Can not launch agent right now: Server not available at http://172.17.0.1:18080/ping:" component=service 

@deniseschannon this looks like a bug, is there something we are all doing wrong??

cheers,
Str3tch

**Comment by str3tch** [comment]
ok it's working!!

but i did things a bit different. I took AWS out of the picture, I ran up three Ubuntu 14.04 hosts, docker 1.10.3, and for load balancer used a dns entry for the three hosts

At first, I got the same error message.. especially when I just ran the HA script on one node. I continued and ran the script on all three nodes regardless. First thing that I noticed was that the managment certificate appeared on the original Rancher server HA page (previously this had not appeared). After that the ha nodes overcame the "waiting for server" bit and starting to come up.

So not sure if it was using a DNS load balancer, or whether I needed to start all three ha nodes regardless of the error.. 

maybe something to try??

**Comment by ThatsNinja** [comment]
Another +1 here, same scenario as above. I lifted and shifted to AWS to get away from ESXi, so @str3tch solution is a no-go, unfortunately.

Further, I've enabled ProxyProtocol on the ELB, as with @iDiogenes, to no avail.

**Comment by deniseschannon** [comment]
@epierotto Can you provide the logs for these other containers? rancher-ha-cattle, rancher-ha-zk

@amenophis @str3tch @iDiogenes Would it be possible for you to open separate issues regarding your HA setup so that we can individually help you? Though the issue of not being able to set up HA is the same, the underlying issue of what's wrong may be different. 

Items to Provide in your Issues:
1. Where/how are you hosting HA? AWS/ELB? If in AWS, did you make sure to open all the necessary [ports](http://docs.rancher.com/rancher/installing-rancher/installing-server/multi-nodes/#requirements) in your security group? If using vagrant, what virtualization provider are you using? Basically any information on how your networking for your nodes are being supported would be helpful
2. What OS and docker version?
3. Logs of rancher-ha , rancher-ha-cattle, rancher-ha-zk containers

**Comment by epierotto** [comment]
Hi @deniseschannon here you are, 

Vagrant 1.8.1
Virtualbox Version 5.0.18_Ubuntu r106667

Vagrant boxes
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.3 LTS"

Logs with docker v1.10.3
[rancher-ha-logs-1_10_3.zip](https://github.com/rancher/rancher/files/243821/rancher-ha-logs-1_10_3.zip)

Logs with docker v1.11.0: 
[rancher-ha-logs-1_11_0.zip](https://github.com/rancher/rancher/files/243814/rancher-ha-logs-1_11_0.zip)

Let me know if I can help with anything else.

**Comment by LLParse** [comment]
@epierotto This looks to be a networking issue and not related to docker versions.

In rancher_ha_n1, i see the following log line:
```
{"log":"time=\"2016-04-30T20:44:34Z\" level=info msg=\"Cluster changed, index=3, members=[10.0.2.15, 10.0.2.15, 10.0.2.15]\" component=service \n","stream":"stderr","time":"2016-04-30T20:44:34.214752214Z"}
```
Members are picking up the same IP address, quite possibly from the wrong interface or we need a different networking mode.

Could you please provide your Vagrantfile and any other relevant scripts/bootstrapping?

**Comment by epierotto** [comment]
Hi @LLParse That means that I should specify rancher-ha to use eth1 instead of eth0

In the Vagrant file I'm defining a private_network for the nodes:
```
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = 'ubuntu/trusty64'
  config.vm.provider :virtualbox do |vb|
    vb.customize [
      'modifyvm', :id,
      '--cpus', '2',
      '--memory', '2048'
    ]
  end

  config.vm.define "n1" do |n1|
    n1.vm.hostname = "n1"
    n1.vm.network "private_network", ip: "172.20.20.10"

*********

  config.vm.define "n2" do |n2|
    n2.vm.hostname = "n2"
    n2.vm.network "private_network", ip: "172.20.20.11"

********
  config.vm.define "n3" do |n3|
    n3.vm.hostname = "n3"
    n3.vm.network "private_network", ip: "172.20.20.12"

```

How can I point it to the right interface?

**Comment by LLParse** [comment]
It looks like you could provide a JVM argument like this:
-Dcattle.server.ip=172.20.20.10

That will tell Rancher server to advertise that IP address. It is not used for anything else besides advertisement.

**Comment by epierotto** [comment]
@LLParse  That JVM argument -Dcattle.server.ip can be specified on the rancher-ha launch script?

**Comment by LLParse** [comment]
@epierotto You may specify it as an environment variable CATTLE_SERVER_IP. Gathering the correct IP address for each node could be scripted without too much difficulty.

**Comment by epierotto** [comment]
@LLParse Well I tried using the rancher-ha.sh script adding export CATTLE_SERVER_IP=172.20.20.10 to /var/lib/rancher/etc/server.conf then tried -e CATTLE_SERVER_IP=172.20.20.10 with no luck.
The nodes still advertising the wrong IP 
```
time="2016-05-05T18:03:25Z" level=info msg="Cluster changed, index=0, members=[10.0.2.15, 10.0.2.15, 10.0.2.15]" component=service
```
Can you tell me how can I set that env for the rancher-ha containers?

**Comment by ibuildthecloud** [comment]
@epierotto The environment is actually `CATTLE_AGENT_IP`.  Can you try that?

**Comment by epierotto** [comment]
@ibuildthecloud @LLParse It worked thanks!! 
The env CATTLE_AGENT_IP on the rancher-ha.sh script works perfect!!

```
time="2016-05-05T19:42:49Z" level=info msg="Cluster changed, index=1, members=[172.20.20.10, 172.20.20.12, 172.20.20.11]" component=service
```
![screenshot from 2016-05-05 21-19-46](https://cloud.githubusercontent.com/assets/5226270/15055965/3d316cfa-1307-11e6-94b8-9320fe3a7922.png)

Would be nice to add some lines about it on the rancher docs.

**Comment by forhot2000** [comment]
I also got similar error, my `rancher-ha-parent` container's ip is `172.17.0.2`, and I `export CATTLE_AGENT_IP=172.17.0.2` to run `rancher-ha-start.sh` script, it also got the same error

```
time="2016-09-26T12:13:06Z" level=info msg="Waiting for server to be available" component=cert
time="2016-09-26T12:13:06Z" level=info msg="Can not launch agent right now: Server not available at http://172.17.0.1:18080/ping:" component=service
```

**Comment by roachmd** [comment]
@forhot2000 

I just got this running. So, the not so clean instructions.....


I'm following the instruction :: http://docs.rancher.com/rancher/v1.2/en/installing-rancher/installing-server/multi-nodes/ on a Ubuntu 16.04 host
1) Copy the generated rancher-ha.sh script to each host.
2) Add export CATTLE_AGENT_IP={ IP Address of the HOST } to line 26 of each script.
     a) this makes it apart of the server.conf  
    
Example:
`export CATTLE_AGENT_IP=10.10.10.103
export CATTLE_HA_PORT_REDIS=6379
export CATTLE_HA_PORT_SWARM=2376
export CATTLE_HA_PORT_HTTP=80
export CATTLE_HA_PORT_HTTPS=443`


ACTIVE NODES 
 1.12.1
 Ubuntu 16.04.1 LTS (4.4.0-38-generic)
 2x2.5 GHz
 2 GiB
 38.7 GiB

**Comment by forhot2000** [comment]
I have created an 3 nodes HA cluster, after run `sudo ./rancher-ha.sh rancher/server:v1.1.4` on each nodes, the rancher-ha container is always waiting

```
docker@rancher3:~$ docker logs -f rancher-ha
...
time="2016-09-30T10:39:58Z" level=info msg="Can not launch agent right now: Server not available at http://172.17.0.1:18080/ping:" component=service
time="2016-09-30T10:40:03Z" level=info msg="Waiting for server to be available" component=cert
time="2016-09-30T10:40:03Z" level=info msg="Can not launch agent right now: Server not available at http://172.17.0.1:18080/ping:" component=service
time="2016-09-30T10:40:08Z" level=info msg="Waiting for server to be available" component=cert
time="2016-09-30T10:40:08Z" level=info msg="Can not launch agent right now: Server not available at http://172.17.0.1:18080/ping:" component=service
time="2016-09-30T10:40:13Z" level=info msg="Waiting for server to be available" component=cert
```

and the zk-client container alert error binding socket

```
docker@rancher3:~$ docker logs rancher-ha-tunnel-zk-client-3
spiped: error binding socket: Address already in use
spiped: error binding socket: Address already in use
spiped: error binding socket: Address already in use
```

I checked all 3 zk-client, all of them started with command 

```
docker@rancher3:~$ docker inspect rancher-ha-tunnel-zk-client-1 | grep -A 7 Cmd
            "Cmd": [
                "tunnel",
                "-d",
                "-s",
                "[0.0.0.0]:12181",     # all 3 zk-client use 12181
                "-t",
                "[127.0.0.1]:2181"     # the other is 2182 and 2183
            ],
```

is that is reason?

**Comment by Cygnust** [comment]
Hi guys,
seems like I have the same problem as yours.
rancher-ha logs says
`time="2016-10-10T17:17:01Z" level=info msg="Waiting for server to be available" component=cert
time="2016-10-10T17:17:01Z" level=info msg="Can not launch agent right now: Server not available at http://172.17.0.1:18080/ping:" component=service`
 and I can't connect my docker ha.

However the cause is different. 172.17.0.1 is an IP currently used on our own network, and I can't reassign it.
Is there any way to make rancher agent use another ip ?
I already tried adding agent_ip in the ranger-ha.sh

Many thanks for your help

**Comment by aemneina** [comment]
@Cygnust you might need to reconfigure docker first to change its bridge ip CIDR. Then pass in the correct agent_ip to rancher.

**Comment by Cygnust** [comment]
Hi guys,
I'm following up.
Don't know what happened, but launching the 2 other hosts made the trick ..

Many thanks for your help

**Comment by Cygnust** [comment]
@aemneina Hi Ahmad, seems like the resolution was not done.
I had a few problems (my rancher servers reboot randomly) and I believe it's due to that ip used on my network.

Could you please guide me to change the bridge IP ?
I know how to force an ip onto a container but I'm completely lost regrding the fact my containers are created by the rancher.sh scripts.

Another question, isn't that IP harcoded withing rancher to be reached ?

Many thanks

**Comment by aemneina** [comment]
Hey @Cygnust,

I cant imagine a host rebooting due to networking issues. You should take a look at the host logs (messages/system), to see if there are other external factors.

Docs for changing dockers bridge-ip here: https://docs.docker.com/engine/userguide/networking/default_network/custom-docker0/

and changing ranchers config to accommodate the updated docker BIP can be found here: https://github.com/rancher/rancher/issues/5115

You'll need rancher 1.2.0-pre3 or later. Those are development builds so less stable.
