### ISSUE TITLE
[Backport] Update monitoring to use prometheus 2.45

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#44606]
Backport of https://github.com/rancher/rancher/issues/44605

Is your feature request related to a problem? Please describe.
The version of Prometheus we've been using is out of date.

Describe the solution you'd like
Update to the latest LTS version, which at the time of writing is 2.45
https://prometheus.io/docs/introduction/release-cycle/

Describe alternatives you've considered
There are newer versions of prometheus, but we've decided to go with the long term support version.

Additional context
SURE-7043

**Comment by ericpromislow** [comment]
Closed in PR [#3609](https://github.com/rancher/charts/pull/3609)

**Comment by pankajsqe** [comment]
Prometheus 2.45 has been updated on below setup. PFA
Rancher: 2.8-head
Cluster: v1.28.7+rke2r1

Monitoring: rancher-monitoring:103.1.0-rc1+up45.31.1
Charts : Dev-2.8





![Image](https://github.com/rancher/rancher/assets/149133120/75547e5d-af39-4264-bc35-4622e481e381)
![Image](https://github.com/rancher/rancher/assets/149133120/517cf20c-b7b3-4561-95a6-9d15e0cdd90c)
![Image](https://github.com/rancher/rancher/assets/149133120/d89952d5-ba16-47f2-9182-42fbbbcaa313)





ip-10-0-0-63:/home/ec2-user # kubectl get pods --namespace=cattle-monitoring-system -o jsonpath="{..image}" | tr -s '[[:space:]]' '\n' | sort | uniq
docker.io/rancher/klipper-helm:v0.7.0-build20220315
docker.io/rancher/mirrored-grafana-grafana:9.1.5
docker.io/rancher/mirrored-kiwigrid-k8s-sidecar:1.24.6
docker.io/rancher/mirrored-kube-state-metrics-kube-state-metrics:v2.10.1
docker.io/rancher/mirrored-library-nginx:1.24.0-alpine
docker.io/rancher/mirrored-prometheus-adapter-prometheus-adapter:v0.10.0
docker.io/rancher/mirrored-prometheus-alertmanager:v0.26.0
docker.io/rancher/mirrored-prometheus-node-exporter:v1.3.1
docker.io/rancher/mirrored-prometheus-operator-prometheus-config-reloader:v0.65.1
docker.io/rancher/mirrored-prometheus-operator-prometheus-operator:v0.65.1
docker.io/rancher/mirrored-prometheus-prometheus:v2.45.0
docker.io/rancher/prometheus-federator:v0.3.4
docker.io/rancher/pushprox-client:v0.1.0-rancher2-client
docker.io/rancher/pushprox-proxy:v0.1.0-rancher2-proxy
rancher/klipper-helm:v0.7.0-build20220315
rancher/mirrored-grafana-grafana:9.1.5
rancher/mirrored-kiwigrid-k8s-sidecar:1.24.6
rancher/mirrored-library-nginx:1.24.0-alpine
rancher/mirrored-prometheus-adapter-prometheus-adapter:v0.10.0
rancher/prometheus-federator:v0.3.4
rancher/pushprox-client:v0.1.0-rancher2-client
rancher/pushprox-proxy:v0.1.0-rancher2-proxy
