### ISSUE TITLE
[RFE] Improve handling of `dynamicSchemaSpec`

### ISSUE THREAD

**Issue by jakefhyde** [rancher/rancher#44618]
**Is your feature request related to a problem? Please describe.**

https://github.com/rancher/rancher/pull/40730 was initially merged for https://github.com/rancher/rancher/issues/40609, introducing the `dynamicSchemaSpec` field under the provisioning cluster resources `machinePools` list to prevent automatic and unintended machine rollout when switching between node driver versions. Built-in and custom node drivers may be updated to add new fields, typically when a new version of `rancher-machine` is released and vendored in as part of a rancher upgrade, or a new version of the custom node driver is released respectively. This approach works for fetch based update methods (such as `Edit Yaml` or `Edit Config` within the Rancher UI), as well as path based update methods, however declarative (i.e. desired state) methods such as terraform or fleet drop this field from the request. As such, this can result in unexpected reprovisioning to the user, as removal of this field will cause it to be repopulated, and the change in `machine-template-hash` by no longer dropping the new fields added since initial provisioning will cause a rollout. While potential workarounds should be investigated in the short term for both fleet and terraform, it is worth investigating a more permanent long term solution. 

**Describe the solution you'd like**

There are a number of potential solutions, but no clear path at this time. The team will evaluate options internally and update this ticket accordingly.

**Describe alternatives you've considered**

**Additional context**
SURE-7751

**Comment by susesgartner** [comment]
Ticket #44618 - Test Results - ✅ 
---
 
| Scenario | Test Case | Result |
|---|---|---|
| 1. | Dynamic schema repopulation test | PASS |
 
---
Verified with Docker on Rancher `v2.9-3c4ccdc5bc9fde3510089153b5ad58fdbe604880-head`:
---
NOTE: Tested on RKE2/K3s
Scenario 1: Dynamic schema gets repopulated
---
1. Provision an rke2 cluster with the dynamic schema 
2. Wait for the cluster to finish provisioning
3. Remove the dynamic schema
 
Results: the dynamic schema repopulates and the cluster doesn't re-provision.

**Comment by lindhe** [comment]
The `dynamicSchemaSpec` field still appears in `kubectl diff`, I'm guessing that means it was not properly marked as a managed field. Is that intentional? Otherwise, should I create an issue for it?

**Comment by t80027t** [comment]
Hi @lindhe ,

I had a similar question and think I've worked out why

See #52938
