### ISSUE TITLE
[RFE] Rebase monitoring to upstream version 50.x

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#44614]
Rebase monitoring to a newer upstream version

There will be new CRDs for alerting, so UI needs to look at it as well. 

SURE-7884

**Comment by gaktive** [comment]
I'll get a ticket over in `rancher/dashboard` for UI tracking purposes. Are there any other details at this time or is this enough to get rolling?

**Comment by MKlimuszka** [comment]
Moving to blocked until e get a new repo from EIO.

**Comment by joshmeranda** [comment]
Adding for tracking purposes:
Image Mirror: https://github.com/rancher/image-mirror/pull/641
EIO Ticket: https://github.com/rancherlabs/eio/issues/2364

**Comment by pankajsqe** [comment]
rebase monitoring has been validated and passed on rancher v2.9.0-alpha7 and v2.9-head.

Cluster : v1.30.2+k3s2 , v1.29.4+rke2r1, EKS1.29, AKS1.29
rancher-monitoring:104.0.0-rc1+up57.0.3


**Fresh Install Testing**

1. Install Monitoring 104.0.0-rc1+up57.0.3 for the first time on a new cluster
2. Install Alerting Drivers 104.0.0-rc1 for the first time on a new cluster
3. Perform E2E Tests
4. Confirm that Alerts are still being received


 **Upgrade Testing**
1. Install Monitoring 103.1.1+up45.31.1
2. Install Alerting Drivers 104.0.0-rc1
3. Perform Alerting-Driver configuration to send an alert to an endpoint (eg, sachet)
4. Confirm Alerts are being received
5. Upgrade Rancher Monitoring to version 104.0.0-rc1+up57.0.3
6. Perform Monitoring E2E tests
7. Confirm that Alerts are still being received




![Image](https://github.com/user-attachments/assets/b3bbb989-4a81-4a6f-884e-641eca082ec4)
![Image](https://github.com/user-attachments/assets/13a505f5-e345-4f2f-b1d6-eba56150210e)
![Image](https://github.com/user-attachments/assets/4bb40b15-94a4-466d-84df-834d918c0601)
