### ISSUE TITLE
[ui] JavaScript+CSS+font taken from external sources (possible information leak/security issue)

### ISSUE THREAD

**Issue by dabelenda** [rancher/rancher#4461]
Rancher Version: 1.0.4 (probably All)

Docker Version: N/A

OS: All

Steps to Reproduce: In your browser with the Network analyser open, go to your rancher API view page.

Results: Content is taken from external sources:
* https://releases.rancher.com/api-ui/1.0.4/ui.min.css
* https://releases.rancher.com/api-ui/1.0.4/ui.min.js
* https://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css
* https://netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js
* https://netdna.bootstrapcdn.com/bootstrap/3.1.1/fonts/glyphicons-halflings-regular.woff

Expected: No content should come from external sources. This content should be bundled into the UI code to avoid external dependency. This would limit the security concerns this external dependency can bring. (Disclosure of Referrer URL, possible malicious content, etc).

**Comment by vincent99** [comment]
Duplicate of https://github.com/rancher/rancher/issues/3258
