### ISSUE TITLE
Graph cut off if I switch stacks while service info is up

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4466]
Version - v1.0.1

Steps to Reproduce: 
1.  Create two stacks
2.  Add a service to each stack
3.  Click on one of the stacks to get to details page
4.  Click on Graph icon
5.  Click on service to bring up service info
6.  Use drop-down to switch stacks

Results: The graph view is cut off
![image](https://cloud.githubusercontent.com/assets/11514927/14652399/009676d6-0629-11e6-851a-dca5d6b9cc24.png)

Expected:  Graph view should not be cut off.

**Comment by lvuch** [comment]
https://github.com/rancher/ui/pull/722

**Comment by vincent99** [comment]
@lvuch This needs to be conditional based on whether the info popup is shown or not...

**Comment by lvuch** [comment]
https://github.com/rancher/ui/pull/725

**Comment by tfiduccia** [comment]
Version - master 6/15
Verified fixed
