### ISSUE TITLE
[RFE] Add Unit Tests to the auth Package

### ISSUE THREAD

**Issue by JonCrowther** [rancher/rancher#44698]
**Is your feature request related to a problem? Please describe.**
Currently the `auth` package has several small files that do not have comprehensive unit tests. This leaves the code vulnerable to regressions and hard to modify.

**Describe the solution you'd like**
Add unit test coverage to the following files:
- https://github.com/rancher/rancher/blob/release/v2.9/pkg/controllers/management/auth/setting.go
- https://github.com/rancher/rancher/blob/release/v2.9/pkg/controllers/management/auth/legacy_rt_cleaner.go
- https://github.com/rancher/rancher/blob/release/v2.9/pkg/controllers/management/auth/legacy_grb_cleaner.go
- https://github.com/rancher/rancher/blob/release/v2.9/pkg/controllers/management/auth/indexes.go

At assignee's discretion:
- Adding comments to any functions that are currently undocumented or under-documented.
- Minor refactors to make code more testable.

If any bugs are found, or the assignee believes major refactoring is necessary, create a new GitHub issue to track the work. This issue is not for potential functionality changes.

**Additional context**
This is a bit of a catchall for any gaps in the unit test coverage of the `auth` package. Any added coverage to files not specifically mentioned in this issue would be appreciated.

**Comment by Jono-SUSE-Rancher** [comment]
QA none. @samjustus - is this still blocked? I think the merged PR adds the needed tests. Can we close?
