### ISSUE TITLE
Clicking on System in Kubernetes environment switches between stack and services page

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4469]
Version - v1.0.1

Steps to Reproduce: 
1.  Setup a kubernetes environment
2.  After it has completely setup, click on the System menu
3.  Click on it again

Results: It switches between the Stacks page (which is correct) to the kubernetes Services Page (which is not correct)

Expected:  Should always go to Stacks page

**Comment by vincent99** [comment]
This doesn't sound relevant anymore withnew header...

**Comment by tfiduccia** [comment]
Version - master 7/15
Verified fixed - or not relevant anymore...
