### ISSUE TITLE
[Forwardport v2.9] [BUG] RKE2/K3S registration command not working on airgap setup

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#44714]
Forwardport of https://github.com/rancher/rancher/issues/44682 for 2.9.x line of releases.

**Comment by vivek-shilimkar** [comment]
Validated on rancher v2.9.0-alpha5 docker airgap setup:
- Created custom RKE2 and K3s v1.29 clusters.
- Registration commands are successfully getting executed now, hence closing the issue.
