### ISSUE TITLE
Kubernetes environment fails to setup - etcd service spins 

### ISSUE THREAD

**Issue by prachidamle** [rancher/rancher#4471]
Docker Version: 1.10.3

Steps to Reproduce: 
- Use master rancher-compose build 
- Go to Manage environment and edit the existing environment to use Kubernetes orchestration
- Check the Kubernetes Stack, etcd service will keep spinning
- Error seen in etcd container logs: 
4/18/2016 3:46:27 PM2016/04/18 22:46:27 error verifying flags, '/usr/local/bin/etcd' is not a valid flag. See 'etcd -help'.

When Kubernetes services are getting launched, checked the API for etcd service and the launchConfig shows misformed command arguments: "/usr/local/bin/etcd" is passed twice.

"name": "etcd",
"state": "removed",
"accountId": "1a5",
"assignServiceIpAddress": false,
"createIndex": 2,
"created": "2016-04-19T00:24:30Z",
"createdTS": 1461025470000,
"description": null,
"environmentId": "1e4",
"externalId": null,
"fqdn": null,
"healthState": "degraded",
"kind": "service",
"launchConfig": {
"command": [ 8 items
"/usr/local/bin/etcd",
"--advertise-client-urls=http://etcd:4001",
"--listen-client-urls=http://0.0.0.0:4001",
"--data-dir=/var/etcd/data",
"/usr/local/bin/etcd",
"--advertise-client-urls=http://etcd:4001",
"--listen-client-urls=http://0.0.0.0:4001",
"--data-dir=/var/etcd/data",
],

In the API, the environment shows the raw compose file with well formed command, only launchConfig has the "/usr/local/bin/etcd" added twice:

docker-compose.yml for Kubernetes environment in API:

dockerCompose": "kubelet:\n    labels:\n        io.rancher.container.dns: \"true\"\n        io.rancher.container.create_agent: \"true\"\n        io.rancher.container.agent.role: environment\n        io.rancher.scheduler.global: \"true\"\n    command:\n        - kubelet\n        - --api_servers=http://master\n        - --allow-privileged=true\n        - --register-node=true\n        - --cloud-provider=rancher\n        - --healthz-bind-address=0.0.0.0\n        - --cluster-dns=169.254.169.250\n        - --cluster-domain=cluster.local\n    image: rancher/k8s:v1.2.0-rancher-1\n    volumes:\n        - /var/run/docker.sock:/var/run/docker.sock\n        - /var/run:/host/var/run\n        - /var/lib/docker:/var/lib/docker\n    net: host\n    pid: host\n    ipc: host\n    privileged: true\n    links:\n        - kubernetes:master\n\nproxy:\n    labels:\n        io.rancher.container.dns: \"true\"\n        io.rancher.scheduler.global: \"true\"\n    command:\n        - kube-proxy\n        - --master=http://master\n        - --v=2\n        - --healthz-bind-address=0.0.0.0\n        - --proxy-mode=userspace\n    image: rancher/k8s:v1.2.0-rancher-1\n    privileged: true\n    net: host\n    links:\n        - kubernetes:master\n\netcd:\n    command:\n        - /usr/local/bin/etcd\n        - --advertise-client-urls=http://etcd:4001\n        - --listen-client-urls=http://0.0.0.0:4001\n        - --data-dir=/var/etcd/data\n    image: rancher/etcd:2.0.12\n    labels:\n        io.rancher.sidekicks: etcd-data\n    volumes_from:\n        - etcd-data\n\netcd-data:\n    image: busybox\n    volumes:\n        - /var/etcd/data\n    labels:\n        io.rancher.container.start_once: \"true\"\n        io.rancher.container.hostname_override: container_name\n    command: /bin/true\n    net: none\n\nkubernetes:\n    labels:\n        io.rancher.container.create_agent: \"true\"\n        io.rancher.container.agent.role: environment\n    command: \n        - kube-apiserver\n        - --service-cluster-ip-range=10.43.0.0/16\n        - --etcd-servers=http://etcd:4001\n        - --insecure-bind-address=0.0.0.0\n        - --insecure-port=80\n        - --cloud-provider=rancher\n    image: rancher/k8s:v1.2.0-rancher-1\n    links:\n        - etcd\n\nkubectld:\n    labels:\n        io.rancher.k8s.kubectld: \"true\"\n    environment:\n        SERVER: http://master\n        LISTEN: \":8091\"\n    image: rancher/kubectld:v0.1.0\n    links:\n        - kubernetes:master\n\nscheduler:\n    command:\n        - kube-scheduler\n        - --master=http://master\n        - --address=0.0.0.0\n    image: rancher/k8s:v1.2.0-rancher-1\n    links:\n        - kubernetes:master\n\ncontroller-manager:\n    command:\n        - kube-controller-manager\n        - --master=http://master\n        - --cloud-provider=rancher\n        - --address=0.0.0.0\n    image: rancher/k8s:v1.2.0-rancher-1\n    labels:\n        io.rancher.container.create_agent: \"true\"\n        io.rancher.container.agent.role: environment\n    links:\n        - kubernetes:master\n\nrancher-kubernetes-agent:\n    labels:\n        io.rancher.container.create_agent: \"true\"\n        io.rancher.container.agent_service.labels_provider: \"true\"\n    environment:\n        KUBERNETES_URL: http://master\n    image: rancher/kubernetes-agent:v0.1.0\n    privileged: true\n    volumes:\n        - /var/run/docker.sock:/var/run/docker.sock\n    links:\n        - kubernetes:master\n",

Results: Kubernetes environment does not finish the setup, etcd service keeping spinning

Expected: Kubernetes environment gets created with all services active

**Comment by deniseschannon** [comment]
Can you double check if this is still happening with the latest rancher-compose?

**Comment by soumyalj** [comment]
Tested with v1.1.0-dev4-rc1. The etcd service was running correctly. The launchConfig in the API for etcd service had correct command arguments. Kubernetes environment was created successfully.
