### ISSUE TITLE
[Backport v2.7] [BUG] RKE2/K3S registration command not working on airgap setup

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#44713]
Backport of https://github.com/rancher/rancher/issues/44682 for 2.7.x line of releases.

See https://github.com/rancher/rancher/issues/44682#issuecomment-1985859748 for a workaround.

**Comment by markusewalker** [comment]
**QA TEST PLAN**

|#|Scenario|Test Case|
|---|---|---|
|1|Provision a downstream K3s custom cluster|Setup an air-gap Rancher environment, provision a downstream K3s custom cluster as a standard user|
|2|Upgrade a downstream RKE2 custom cluster|Setup an air-gap Rancher environment, provision a downstream RKE2 custom cluster as a standard user, upgrade the downstream cluster|

**Comment by markusewalker** [comment]
Validated that this is addressed on `v2.7.12-rc1`. See details below:

**ENVIRONMENT DETAILS**
- Rancher install: Helm
- Rancher version: `v2.7.12-rc1`

**TEST RESULT**
|#|Scenario|Test Case|Result
|---|---|---|---|
|1|Provision a downstream K3s custom cluster|Setup an air-gap Rancher environment, provision a downstream K3s custom cluster as a standard user|:white_check_mark:|
|2|Upgrade a downstream RKE2 custom cluster|Setup an air-gap Rancher environment, provision a downstream RKE2 custom cluster as a standard user, upgrade the downstream cluster|:white_check_mark:|

**VALIDATION STEPS**

**Scenario 1**
1. Setup an air-gapped environment.
2. As a standard user, provisioned a downstream custom K3s `v1.27.11+k3s1` cluster (1 etcd, 1 cp, 1 worker).
3. Validated that nodes could be registered and the cluster came up `Active`.

**Scenario 2**
1. Repeated scenario 1, but provisioned a downstream custom RKE2 `v1.26.14+rke2r1` cluster (1 etcd, 1 cp, 1 worker).
2. Upgraded the cluster to `v1.27.11+rke2r1`; validated that it came up `Active`.
