### ISSUE TITLE
[Backport 2.7] Add the ability to use authentication on clients to the kubernetes component

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#44729]
Backport of https://github.com/rancher/charts/pull/3313

SURE-7506

**Comment by pankajsqe** [comment]
Rancher : v2.7.13-rc4
Cluster : v1.26.15+rke2r1
Monitoring : rancher-monitoring:102.0.3+up3.17.10

TestSteps  

Create two secrets one is valid one and another is invalid one.

Created air gap setup with rancher v2.7.13-rc4 on rke2 cluster.
Installed monitoring charts from marketplace.
Once chart is installed go to workloads-> Daemonset and Deployment
While edit config add the invalid secret to imagepullsecret option and change pull policy to always. 
Every pod from pushprox daemonset and deployment should throw error. Later switch the invalid secret with valid one and observe all the pod are again active and running.



![Image](https://github.com/rancher/rancher/assets/149133120/e55dab12-2c11-40a3-9238-8d70aac42a19)
![Image](https://github.com/rancher/rancher/assets/149133120/b5564308-be57-4074-bd29-07158cdd16eb)
![Image](https://github.com/rancher/rancher/assets/149133120/a2fc7c37-c02e-4c0a-bc0d-6a6ae61c06b1)
![Image](https://github.com/rancher/rancher/assets/149133120/3d7b64fd-c982-4b38-8333-42149d3487e4)
