### ISSUE TITLE
[Backport 2.8] Update logging-operator to version 4.2+

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#44727]
Backport of https://github.com/rancher/rancher/issues/43383

SURE-7264

**Comment by joshmeranda** [comment]
Blocked by: https://github.com/rancher/charts/pull/3547

**Comment by pankajsqe** [comment]
Retest passed : Update logging-operator to version 4.4.0.

Test scenarios:

- verified Update logging-operator on local cluster.
- verified Update logging-operator on downstream cluster.
- verified Update logging-operator using rancher upgrade from rancher 2.7.12 to 2.8.head.
- verified Update logging-operator by upgrading, downgrading and uninstalling logging chart

Rancher version: 2.8-head
RKE2 : v1.28.7+rke2r1
Logging : 103.1.0-rc1+up4.4.0
