### ISSUE TITLE
[BUG] Rancher Monitoring - Unable to specify private registries for all images

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#44725]
**Issue description:**
The rancher-monitoring chart allows a private registry to be used when pulling images through the 'system_default_registry' helm value. The following images do not respect this value:

    rancher/mirrored-prometheus-node-exporter
    rancher/mirrored-kiwigrid-k8s-sidecar
    rancher/mirrored-prometheus-adapter-prometheus-adapter
    rancher/mirrored-kube-state-metrics-kube-state-metrics    
    rancher/mirrored-grafana-grafana

**Business impact:**
Users are unable to force all rancher-monitoring images to be pulled from private registries.

SURE-7145

**Comment by mallardduck** [comment]
Looking over `104.0.0-rc1+up45.31.1` chart version, the following support using `.Values.global.cattle.systemDefaultRegistry` - so testing TBD but based on code, these are good:
- [x] rancher/mirrored-prometheus-node-exporter
- [x] rancher/mirrored-kiwigrid-k8s-sidecar
- [x] rancher/mirrored-prometheus-adapter-prometheus-adapter
- [x] rancher/mirrored-kube-state-metrics-kube-state-metrics - @alexandreLamarre [patched](https://github.com/rancher/charts/commit/58b5ce74cb56746d8e339f6a4772fb72be94fddd) 
- [x] rancher/mirrored-grafana-grafana

**Comment by alexandreLamarre** [comment]
like @mallardduck pointed out, this issue might be specific to the 2.7.x release line

**Comment by mallardduck** [comment]
So it looks like 2.7.x is also all good as of - `102.0.3+up40.1.2` based on:
https://github.com/rancher/charts/blob/6dc220e5ed99d10ac894bd283b28ced2ac26df15/charts/rancher-monitoring/102.0.3%2Bup40.1.2/charts/prometheus-node-exporter/templates/_helpers.tpl#L2

**Comment by mallardduck** [comment]
per advice from @alexandreLamarre - I was able to further verify this as fixed using `helm template`. I can confirm that all the images for updated charts will use the `global.cattle.systemDefaultRegistry` when the value is set.

So to recap the fixed versions are:
- 102.0.3+up40.1.2
- 103.0.3+up45.31.1
- 104.0.0-rc1+up45.31.1
