### ISSUE TITLE
RKE2 and K3S - KDM Update for K8s March 2024 patch release for Rancher 2.8

### ISSUE THREAD

**Issue by rancher-max** [rancher/rancher#44722]
# KDM Updates

| New Kubernetes Version  | Min Rancher Version | Max Rancher Version |
|                  :---:                  |              :---:               |               :---:               |
| v1.26.15+rke2r1                  | v2.7.5-alpha1             | v2.8.99 |
| v1.27.12+rke2r1                  | v2.8.0-alpha1             | v2.8.99 |
| v1.26.15+k3s1                  | v2.7.5-alpha1             | v2.8.99 |
| v1.27.12+k3s1                  | v2.8.0-alpha1             | v2.8.99 |

# KDM Branch
[dev-v2.8](https://github.com/rancher/kontainer-driver-metadata/tree/dev-v2.8)

# Chart Changelog

| Chart Name  | New Version | Affected Kubernetes Version(s) |
|        :---:        |       :---:        |                     :---:                     |

TBD

# Argument Changelog

| Argument Name  | Affected Kubernetes Version(s) |
|        :---:           |                     :---:                     |

TBD

# Additional Notes

**Comment by snasovich** [comment]
FYI my understanding is that the current plan is to have March patches added to v2.8-Next1 full release for vSphere K8s 1.28 support so changing the milestone accordingly.

**Comment by endawkins** [comment]
![Screenshot 2024-03-26 at 14 41 21](https://github.com/rancher/rancher/assets/126098099/f1516a9b-d36e-4ff9-b0f1-f909b91fbaf1)
