### ISSUE TITLE
[BUG] Links leading to 404 errors

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#44724]
**These links are broken :**
[https://github.com/rancher/charts/blob/release-v2.7/charts/ranchermonitoring/102.0.1%2Bup40.1.2/values.yaml#L18C9-L18C89](https://github.com/rancher/charts/blob/release-v2.7/charts/rancher-monitoring/102.0.1%2Bup40.1.2/values.yaml#L18C9-L18C89)

https://github.com/rancher/charts/blob/release-v2.7/charts/rancher-monitoring/102.0.1%2Bup40.1.2/values.yaml#L129

https://github.com/rancher/charts/blob/release-v2.7/charts/rancher-monitoring/102.0.1%2Bup40.1.2/values.yaml#L175

https://github.com/rancher/charts/blob/release-v2.7/charts/rancher-monitoring/102.0.1%2Bup40.1.2/values.yaml#L244

https://github.com/rancher/charts/blob/release-v2.7/charts/rancher-monitoring/102.0.1%2Bup40.1.2/values.yaml#L729C13-L729C101

**Plus other spots:**
https://github.com/search?q=repo%3Arancher%2Fcharts+dev-v2.5&type=code

SURE-6886

**Comment by pankajsqe** [comment]
Issue while upgrading rancher from 2.8 to 2.9. monitoring charts are not coming up on apps marketplace even when I toggle on pre-release. It hit the dead end.

Steps

1. Installed Rancher v2.8.3
2. Charts : dev-v2.8
3. Install monitoring chart : rancher-monitoring:103.0.4+up45.31.1
4. Later upgraded rancher to v2.9.0-alpha1
5. update the chart repository to dev-v2.9
6. turn on the toggle for pre-release
7. Now I dont see any monitoring chart in market place : PFA



![Image](https://github.com/rancher/rancher/assets/149133120/c540837b-e3c3-4a80-a73c-209b431736bf)

**Comment by pankajsqe** [comment]
retest passed on rancher v2.9.0-rc1 with rancher-monitoring:104.0.0-rc1+up45.31.1

![Image](https://github.com/rancher/rancher/assets/149133120/0db05c81-db63-4ac6-84ce-3628fd7b0718)
![Image](https://github.com/rancher/rancher/assets/149133120/47b62405-762d-45d2-8977-a35f32bb9b2f)
