### ISSUE TITLE
No difference between ALL and Library in Catalog unless I add a custom catalog

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4472]
Version - v1.0.1

Steps to Reproduce: 
1.  Go to Catalog menu item before adding a custom catalog

Results: ALL and Library have exactly the same catalog items.  This will always be the case unless you add a custom catalog

Expected: Only show Library until custom catalog is added.

**Comment by vincent99** [comment]
This was done in the new header

**Comment by tfiduccia** [comment]
Version - master 6/9
Verified fixed
