### ISSUE TITLE
highlight for service alias target drop-down is covering part of - button

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4473]
Version - v1.0.1

Steps to Reproduce: 
1.  Add Service Alias
2.  Move mouse over Select a service drop-down

Results: highlight is partially covering the - button.  Really noticeable in dark theme but it's also in the light theme. 
![image](https://cloud.githubusercontent.com/assets/11514927/14656986/93c8dc94-063f-11e6-8bad-4b3554472796.png)
 
Expected:  Should only highlight drop-down itself

**Comment by lvuch** [comment]
https://github.com/rancher/ui/pull/708

**Comment by tfiduccia** [comment]
Version - master 6/9
Verified fixed
