### ISSUE TITLE
[BUG] validatingWebhookConfiguration that points to webhook capi endpoints exists on the local cluster

### ISSUE THREAD

**Issue by Priyashetty17** [rancher/rancher#44734]
**Rancher Server Setup**
- Rancher version: `v2.8-35d6b4eedc3b0274c8c73b830d95bec30a1f2cbc-head`
- Installation option (Docker install/Helm Chart): `Helm Chart` (`2.8.3-rc2`)

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Admin
   
**Describe the bug**
validatingWebhookConfiguration that points to webhook capi endpoints exists on the local cluster

**To Reproduce**
1. Create a rancher server v2.8-head
2. Create a downstream cluster
3. Verify that the version of the webhook is as expected on both local and downstream clusters- `v0.4.3-rc1`
4. On both local and downstream clusters, Verify that there are no capi specific values/resources in the webhook chart/yaml/deployment/pod:
    - [✅] Webhook Chart: helm -n cattle-system get values rancher-webhook
    - [✅] Webhook Yaml in UI
    - [✅] Webhook Resources
        - Service webhook-service in namespace cattle-system should not exist
        - Secret rancher-webhook-tls in namespace cattle-system should not exist
    - [✅] Webhook Deployment: kubectl get deployment rancher-webhook -n cattle-system -o yaml
5. On the local cluster, Verify that validatingWebhookConfiguration that points to capi endpoints is no longer created: kubectl get validatingwebhookconfigurations.admissionregistration.k8s.io  validating-webhook-configuration

**Result**
validatingWebhookConfiguration that points to webhook capi endpoints exists on the local cluster
```
> kubectl get validatingwebhookconfigurations.admissionregistration.k8s.io  validating-webhook-configuration
NAME                               WEBHOOKS   AGE
validating-webhook-configuration   12         17h

> kubectl get validatingwebhookconfigurations.admissionregistration.k8s.io  validating-webhook-configuration -o yaml | grep -i "name: capi"
      name: capi-webhook-service
      name: capi-webhook-service
      name: capi-webhook-service
      name: capi-webhook-service
      name: capi-webhook-service
      name: capi-webhook-service
      name: capi-webhook-service
      name: capi-webhook-service
      name: capi-webhook-service
      name: capi-webhook-service
      name: capi-webhook-service
      name: capi-webhook-service
> 
```

**Expected Result**
validatingWebhookConfiguration that points to webhook capi endpoints should no longer exist on the local cluster

cc @tomleb

**Comment by tomleb** [comment]
I see that the name of the service is

>       name: capi-webhook-service

The [validation template ](https://github.com/rancher/rancher/issues/44619#issuecomment-1981272361) mentioned that the service `webhook-service` needed to be cleaned up, it didn't say anything about `capi-webhook-service`.

The reason this service is there is because we still need the CAPI webhook, but it was moved from inside webhook (in `cattle-system`) to outside webhook in another namespace.

**Comment by Priyashetty17** [comment]
Yes, you are right. I just checked and this is in `namespace: cattle-provisioning-capi-system`. Closing this issue
