### ISSUE TITLE
Service Alias stuck deactivating if they are pointing at each other

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4475]
Version - v1.0.1

Steps to Reproduce: 
1.  Create a service alias called "SA1" and don't point it to anything
2.  Create a service alias called "SA2" and point to SA1
3.  Edit SA1 and point to SA2
4.  Click on Stop service button on stack

Results: Both Service Alias are stuck in Deactivating and I can't get them out of this state.

Expected: I should be able to stop them or get them out of this state so I can fix it.

**Comment by alena1108** [comment]
@tfiduccia could you try it on the latest? I couldn't reproduce the bug

**Comment by tfiduccia** [comment]
Yep looks like it's fixed in 1.2
