### ISSUE TITLE
Release rancher/kubectl with 1.28 support

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#44759]
The rancher/kubectl repo hasn't had a release since 1.23: 
Recent commits have been added to support 1.28: https://github.com/rancher/kubectl/commits/master/
We need to tag a new version to allow 1.28 support, and do a smoke test to ensure it works.

**Comment by Jono-SUSE-Rancher** [comment]
Just adding a note here that this doesn't need QA and can slip past code freeze since we just need to cut a release and do a QA smoke test since the code was already merged for it.

**Comment by cbron** [comment]
This tag already existed from automation, so we can close.
