### ISSUE TITLE
[RFE] Allow provisioning Vsphere RKE2 DS clusters with duplicate networks names [UI & Backend coordination]

### ISSUE THREAD

**Issue by gaktive** [rancher/rancher#44779]
Internal reference: SURE-6853

Request description:
A user uses VMWare as infrastructure to provision rke2 downstream clusters. The Vsphere Distributed Switches, VDS, get networks from NSX-T. There is only one Transport zone so all VDS get the same networks, therefore network names are duplicated.

Actual behavior:
The Rancher UI stalls when provisioning at networks tab and the provisioning process fails.

Expected behavior:
Provisioning a new rke2 cluster when the network names are duplicated

Workaround:
Provisioning the cluster with cluster templates. The networks can be specified

https://github.com/rancher/cluster-template-examples/blob/main/charts/values-vsphere.yaml

```
  # vSphere network where the virtual machine will be attached
  # network: ""
```

A different workaround is using terraform.

UI has tried looking into this in https://github.com/rancher/dashboard/issues/9817 but per @snasovich comment, there's coordination required between teams to do this:

>  the implementation of proposed fix will require changes on both backend and UI side: "Therefore, an alternate strategy to this would be the UI referencing the MOID value rather than the port group name. I would still list the port groups in the UI by name, but once selected, the ID can be used instead"

> That is because I'm pretty sure UI is currently using meta/vsphere/networks endpoint in Rancher to get networks and it returns plain list of strings - see https://github.com/rancher/rancher/blob/f0b3227927ae99dbc8c944b3aca908708bbf23ea/pkg/api/norman/customization/vsphere/listers.go#L307

> So, this will not be a simple fix and will require a redesign of backend/UI data contract and behavior and will likely need to be considered pretty much a feature request.

Potential workaround: create a cluster using TF or cluster templates.

**Comment by snasovich** [comment]
@jiaqiluo to work on the design for this feature. Not moving to "Actively Developing" state until we actually are.

**Comment by gaktive** [comment]
@snasovich how's this looking for 2.9.0? UI is waiting on this and this looks at risk.

**Comment by snasovich** [comment]
@gaktive , there are some internal discussions going on regarding this issue. Stay tuned...

**Comment by jiaqiluo** [comment]
Now that the backend PR has been merged, it should no longer pose a blocker for the UI.

**Comment by jiaqiluo** [comment]
Moving it to `Ready for testing` as the associated [Dashboard issue](https://github.com/rancher/dashboard/issues/9817) is ready for testing now

**Comment by susesgartner** [comment]
Ticket #46837 - Test Results - ✅ 
---
 
| Scenario | Test Case | Result |
|---|---|---|
| 1. | Provision vSphere cluster | PASS |
| 2. | Upgrade vSphere rancher cluster | PASS |
 
---
Verified with (HA Helm or Docker) on Rancher `v2.10-head`:
---
 

Permutations: RKE2/K3s

Scenario 1: Provision vSphere cluster
---
1. Provision a 3 node all role cluster
2. Verify that the network name utilizes MOID
3. Verify that the cluster comes up and all pods in a stable state.
 
Results: the network name utilizes MOID and the cluster came up in a stable state
 
---
 
NOTE: When upgrading rancher the MOID is not displayed in the current network name, however if you click the dropdown it is visible (will file an issue for this bug)

Scenario 2: Upgrade vSphere rancher cluster
---
1. Provision a 3 node all role cluster 
2. Verify that the cluster comes up and all pods in a stable state.
4.  Upgrade rancher to 2.10-head
5. Verify that everything remains in a stable state
 
Results: Everything remains in a stable state
