### ISSUE TITLE
[Forwardport v2.9] [BUG] Installing rancher on GKE with gce ingress class return "response 404 (backend NotFound)"

### ISSUE THREAD

**Issue by prachidamle** [rancher/rancher#44780]
Forwardport of https://github.com/rancher/rancher/issues/41873 for 2.9.x line of releases.

**Comment by pankajsqe** [comment]
Retest passed : Installing rancher on GKE with gce ingress class does not return any error. User is able to launch rancher successfully.


**Details**
Rancher : v2.9.1-alpha1
Cluster : GKE v1.29.6-gke.1038001 (3 nodes)
Ingress : GCE Ingress
SVC : NodePort

**Steps**
- Provision rancher on a GKE local cluster with GCE ingress and not with nginx-ingress.
- Create a 3 node GKE standard cluster.
- Configure the cluster as per rancher doc.
- Run helm install with ingress.Path="/*" and service.type=NodePort (see command below)

Results: Rancher UI is accessible and no errors are observed.

> $helm upgrade  rancher rancher-latest/rancher   --namespace cattle-system   --set hostname=rancher.104.196.35.169.sslip.io   --set replicas=3   --set bootstrapPassword=changeme123456   --set global.cattle.psp.enabled=false   --set rancherImageTag=v2.9.1-alpha1   --set ingress.paths=”/*”   --set service.type=NodePort   --devel


>  $helm get values -n cattle-system rancher
USER-SUPPLIED VALUES:
bootstrapPassword: changeme123456
global:
  cattle:
    psp:
      enabled: false
hostname: rancher.104.196.35.169.sslip.io
ingress:
  paths: ”/*”
rancherImageTag: v2.9.1-alpha1
replicas: 3
service:
  type: NodePort




![Image](https://github.com/user-attachments/assets/6fb569ff-285a-47b1-a5d2-add3d43e5d3f)
