### ISSUE TITLE
[BUG] Rancher CLI panics when trying to kubectl after a login #44811

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#44812]
Forward port https://github.com/rancher/rancher/issues/44811

Root issue: https://github.com/rancher/rancher/issues/44332

**Comment by anupama2501** [comment]
PR: https://github.com/rancher/cli/pull/348

**Comment by anupama2501** [comment]
@enrichman issue requires a 2.9 RC to validate this on.

**Comment by enrichman** [comment]
Closing: https://github.com/rancher/rancher/issues/44332#issuecomment-2040033405

**Comment by anupama2501** [comment]
Re opening as this needs to be tested on 2.9

**Comment by enrichman** [comment]
Hi @anupama2501, the fix for this issue was merged with https://github.com/rancher/cli/pull/348 and it should be already available in the latest v2.9 rc (https://github.com/rancher/cli/releases/tag/v2.9.0-rc1).

**Comment by anupama2501** [comment]
Verified on rancher cli: `v2.9.0-rc1`, rancher v2.9-head `98d8b89`
1. Create a rancher server on 2.9-head
2. Installed rancher cli version v2.9.0-rc1
3. Ran the `rancher context current` without running the login command
4. Verified rancher did not panic but got an error `FATA[0000] no configuration found, run `login``
5. Re ran the same command and verified the context is displayed. 

Kubectl:
1. Verified by changing the global setting to kubeconfig-generate-token=false
2. Ran `rancher kubectl get pods -A`
3. Verified the pods are displayed and no panics noticed
