### ISSUE TITLE
[external-dns] update cloudflare client for API change

### ISSUE THREAD

**Issue by crackcomm** [rancher/rancher#4482]
Docker image `rancher-dns` needs rebuild with https://github.com/crackcomm/cloudflare/pull/4 to work with cloudflare.

**Comment by corentin59** [comment]
Impacted, subscrible.

**Comment by vincent99** [comment]
`external-dns`... `rancher-dns` provides answers to containers.

**Comment by alena1108** [comment]
@janeczku ^^ any chance you could update godeps for cloudflare? assuming you have cloudflare account to test against.

**Comment by janeczku** [comment]
Sure

**Comment by deniseschannon** [comment]
@crackcomm @corentin59 This was updated in v0.4.0 of external-dns and should be reflected in the new images.

Please re-open if you still have issues.
