### ISSUE TITLE
Shibboleth + LDAP small error when searching user and groups (shibbolethconfig-serviceAccountPassword)

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#44845]
Detected an issue when configuring Shibboleth + LDAP for users and groups search.

LDAP search queries were failing with the following error message: [WARNING] ldap search principals failed to get ldap config: error getting secret cattle-global-data:shibbolethconfig-serviceAccountPassword secrets "shibbolethconfig-serviceAccountPassword" not found

The customer detected that the secret was created, but its name was lowercase: "shibbolethconfig-serviceaccountpassword", while it was expected to be camelCase, as per the previous error (shibbolethconfig-serviceAccountPassword), so the search was not working as it could not find the configured secret.

**Workaround**:
Is workararound available and implemented? yes
What is the workaround: manually change the value to "cattle-global-data:shibbolethconfig-serviceaccountpassword" (lowercase), then the LDAP searches worked as expected.

**Actual behavior:**
LDAP searches not working due to a typo on secret name, which is case-sensitive.

**Expected behavior:**
LDAP searches working from the beginning, having the correct secret name (camelCase)

**Comment by samjustus** [comment]
SURE-7772

**Comment by bigkevmcd** [comment]
## Validation Template

## What was fixed, or what change has occurred

LDAP search queries were failing with the following error message: `[WARNING] ldap search principals failed to get ldap config: error getting secret cattle-global-data:shibbolethconfig-serviceAccountPassword secrets "shibbolethconfig-serviceAccountPassword" not found`

The customer detected that the secret was created, but its name was lowercase: "shibbolethconfig-serviceaccountpassword", while it was expected to be camelCase, as per the previous error (shibbolethconfig-serviceAccountPassword), so the search was not working as it could not find the configured secret.

## Areas or cases that should be tested

- Configure Shibboleth _with_ LDAP lookup and a service account password for accessing the LDAP lookup - previously it would fail, but now it should be able to authenticate with the LDAP server (as per the description, the secret name was incorrect previously).

## What areas could experience regressions

- None I can think of.
- 
## Are the repro steps accurate/minimal?

Yes.

**Comment by nickwsuse** [comment]
Re-opening as we are seeing issues when upgrading Rancher. This works fine on a fresh install, but if you upgrade from a previous version with Shibboleth enabled the secret is still in camelCase and the error persists. There is a "workaround" If you disable and then re-enable Shibboleth to simulate a fresh install, the secret is stored in lowercase and works as expected. This should be fixed on upgrade though rather than with a workaround.

**Comment by bigkevmcd** [comment]
## Validation Template

## What was fixed, or what change has occurred

This adds an additional migration to fix broken shibboleth LDAP installations when migrating from 2.8 to 2.9.

If you have 2.8 with Shibboleth configured as an `AuthConfig` (called `shibboleth`), then the LDAP Secret reference may be incorrect.

This will fix it if it matches the known bad data.

The name of the secret that was inserted was mixed case, but the secret that was created was all lower-case, which caused failures when authenticating LDAP for Shibboleth user lookups.

## Areas or cases that should be tested

Install < 2.8.3 l, configure Shibboleth with LDAP, should get an message in the logs:

`[WARNING] ldap search principals failed to get ldap config: error getting secret cattle-global-data:shibbolethconfig-serviceAccountPassword secrets "shibbolethconfig-serviceAccountPassword" not found`

This will migrate this field to use `shibbolethconfig-serviceaccountpassword` only if it is incorrect.

If the user has configured a different secret, it should not be reconfigured.

## What areas could experience regressions

<list of areas that could regress>

## Are the repro steps accurate/minimal?

**Comment by nickwsuse** [comment]
Verified on v2.9-head ID: `d983383` ✅ 
----
### Fresh Install
1. Enable Shibboleth ✅ 
2. Enable LDAP connection with Shibboleth ✅ 
3. Shibboleth Service Account Password is properly stored as `shibbolethconfig-serviceAccountPassword` ✅ 
4. Search for and add LDAP users and groups ✅ 
5. CRTBs and PRTBs properly created for LDAP users
6. LDAP users have correct permissions ✅ 

### Upgrade
1. Shibboleth Service Account Password is properly stored as `shibbolethconfig-serviceAccountPassword` ✅ 
2. Search for and add LDAP users and groups ✅ 
5. CRTBs and PRTBs properly created for LDAP users
6. LDAP users have correct permissions ✅
