### ISSUE TITLE
[DOC] Load balancer ports

### ISSUE THREAD

**Issue by kaos** [rancher/rancher#4485]
I find the comments contradicting regarding `- 80` and `- 9999/tcp`.
When using a single port number, do you get a random public port or not?
Or worse, only when you do not use the `/tcp` suffix.

http://docs.rancher.com/rancher/rancher-compose/rancher-services/#load-balancer-example-l4
![image](https://cloud.githubusercontent.com/assets/72965/14672747/123ac870-06fa-11e6-97ab-42cb235f84da.png)

**Comment by deniseschannon** [comment]
It's a doc discrepancy, which I have now fixed. 

The `9999/tcp` part wasn't updated for random ports.
