### ISSUE TITLE
[v2.8] Upgrade `cluster-proportional-autoscaler` to v1.8.9+

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#44851]
Currently for even the latest RKE1 versions we include `cluster-proportional-autoscaler` `v1.8.6`, see https://github.com/rancher/kontainer-driver-metadata/blob/a294e104b56da802791b9555671d7b1f24634232/pkg/rke/k8s_rke_system_images.go#L10114 / https://github.com/rancher/kontainer-driver-metadata/blob/a294e104b56da802791b9555671d7b1f24634232/pkg/rke/k8s_rke_system_images.go#L10141

There is already `registry.k8s.io/cpa/cluster-proportional-autoscaler:v1.8.9` that features CVE fixes that we want to bring into Rancher, the ask of this issue is to update to this (or newer, if available) version.

Ideally, we want this version bumped in new versions to be added per https://github.com/rancher/rancher/issues/44799

SURE-7862

**Comment by vivek-shilimkar** [comment]
`cluster-proportional-autoscaler` version is upgraded correctly to v1.8.9 in March KDM patches. Hence, closing this issue.
