### ISSUE TITLE
Support for Azure external cloud provider for downstream RKE1 clusters

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#44857]
Parent issue: https://github.com/rancher/rancher/issues/43110

Similar to https://github.com/rancher/rancher/issues/44144 but for Azure cloud provider.

In-tree cloud providers will be disabled by default starting with 1.29 so we want to provide users an option to both:
1. Provision new RKE1 clusters with Azure external (out-of-tree) cloud provider
2. Migrate existing RKE1 clusters that use in-tree Azure cloud provider to external cloud provider.

Supporting this will most likely be down to developing and testing procedure for setting up such external cloud provider but may require code changes (as we needed for the referenced issue for adding AWS cloud provider support).
UI changes may also be needed and it's asked to file `rancher/dashboard` issue(s) if such changes are determined to be necessary as part of working on this issue.

**Comment by kinarashah** [comment]
Load and follow instructions from the linked docs PR to test.

**Comment by vivek-shilimkar** [comment]
1. Provisioned a new RKE1 clusters with Azure external (out-of-tree) cloud provider. 
  - Tested a load balancer creation with workload. It works as expected.

2. Tested Migrating existing RKE1 clusters that use in-tree Azure cloud provider to external cloud provider.
-   After migration the azure cloud provider chart installed correctly.

**Comment by vivek-shilimkar** [comment]
Azure cloud provider migration is working as expected. This issue can be closed once the doc PR is merged - https://github.com/rancher/rancher-docs/pull/1369
