### ISSUE TITLE
Automation for adding support for new Docker versions

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#44863]
New Docker (patch) versions are generally released every 1-4 weeks and it's quite a lot of maintenance to keep up with them (e.g. see https://docs.docker.com/engine/release-notes/25.0/). The ask is to automate opening PRs for adding new Docker versions to https://github.com/rancher/install-docker
Even if the opened PR may require some manual tweaking (especially for new minor versions), it would still be of value if only to ensure we're keeping more up-to-date with upstream versions and to provide a good starting point for implementing new patch/minor Docker versions.

**Comment by snasovich** [comment]
Setting the milestone to `v2.9-Next1` as the "tip of development" version since this is a process/tooling improvement and belongs there.

**Comment by mitulshah-suse** [comment]
Closing the issue as automation is creating PRs as expected.
ex: https://github.com/rancher/install-docker/pull/130
