### ISSUE TITLE
Rancher LB returns 503 after a container restart

### ISSUE THREAD

**Issue by geertvanheusden** [rancher/rancher#4487]
Rancher Version:
**1.0.0**

Docker Version:
**1.11.0**

OS:
**Debian 8.3** 

## Steps to Reproduce:
1. Create a new stack
2. Add a (web)service
3. Create a Rancher LB and connect it to the service created in step 2
4. Start the whole stack
5. The **haproxy.cfg** file is correct and the service is available behind the LB
6. Click the **restart** button of the service container
![image](https://cloud.githubusercontent.com/assets/1923423/14677169/c1246812-0710-11e6-89ca-985955b664a0.png)

## Results: 
The service is unavailable behind the LB.

haproxy.cfg:

```
global
	log 127.0.0.1 local0
    	log 127.0.0.1 local1 notice
        maxconn 4096
        maxpipes 1024
	chroot /var/lib/haproxy
	user haproxy
	group haproxy
	daemon

defaults
	log	global
	mode	tcp
	option	tcplog
        option  dontlognull
        option  redispatch
        option http-server-close
        option forwardfor
        retries 3
        timeout connect 5000
        timeout client 50000
        timeout server 50000
	errorfile 400 /etc/haproxy/errors/400.http
	errorfile 403 /etc/haproxy/errors/403.http
	errorfile 408 /etc/haproxy/errors/408.http
	errorfile 500 /etc/haproxy/errors/500.http
	errorfile 502 /etc/haproxy/errors/502.http
	errorfile 503 /etc/haproxy/errors/503.http
	errorfile 504 /etc/haproxy/errors/504.http


listen default
	bind *:42
```

## Expected:
The service should be available behind the LB and the haproxy.cfg file should be correctly updated.

On the other hand, if you use the **stop** button and wait for the stack to heal, it works as expected.

**Comment by johnrengelman** [comment]
I can confirm to have seen this as well.

**Comment by sangeethah** [comment]
Able to reproduce this issue as well.  
When we  trigger any other config update to Lb service , by stopping other containers in the service / scaling up service , the container that was restarted gets reprogrammed in the haproxy.

**Comment by sangeethah** [comment]
@soumyalj , automation run relating to restarting LB targets should report success now.

**Comment by soumyalj** [comment]
Verified the fix in master.
