### ISSUE TITLE
[BUG] Flaky steve test or race condition still exists

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#44873]
**Rancher Server Setup**
- Rancher version:
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version:
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:

**Describe the bug**

Sometimes

**To Reproduce**

**Result**
Ran same, unchaged steve PR twice with two different outcomes on Test_countsBuffer.
Failed: https://drone-pr.rancher.io/rancher/steve/518/4/2
Passed: https://drone-pr.rancher.io/rancher/steve/519

This could either mean the test is flaky or the [race condition](https://github.com/rancher/steve/pull/162) issue has not been resolved- or a new issue has been introduced by the `counts` package changes.

**Expected Result**

Same outcome every run for unchanged code or at least a very flaky rate if the nature of the test is non-deterministic.

**Screenshots**

**Additional context**

**Comment by JonCrowther** [comment]
Here is another failure that seems related: https://drone-pr.rancher.io/rancher/steve/452/4/2

The `receiveWithTimeout` function takes in a duration and if that duration elapses without receiving a value, it fails with the error both drone failures are getting.

To reproduce, run the following in bash. Some of the instances will fail.  
```
for i in {1..100}; do go test -run=Test_countsBuffer &; done
```

**Comment by JonCrowther** [comment]
Flaky test fixed in https://github.com/rancher/steve/pull/180
