### ISSUE TITLE
Feature: Host Based scheduling selectors

### ISSUE THREAD

**Issue by johnrengelman** [rancher/rancher#4488]
I've been running Rancher in a number of production clusters for months now and one situation that I've encountered over and over is the lack of flexibility in the scheduling constraints for hosts.

Currently, the scheduling requires a label on each and every service that you want to do any type of host based scheduling (affinity or anti-affinity).

This results in a situation where a developer (or whoever is defining services) _must_ remember that label otherwise the end deployment could result in an undesirable situation.

For example, I have an AWS host in my cluster that runs with an IAM profile that allows it access to sensitive resources (a DynamoDB table).

I only want approved services to ever run on this machine. To do this, I currently have to define each and every service ever deployed with an anti-affiinity rule for the host label on the DynamoDB host.
If I ever forget that label, then an unapproved service could be scheduled onto the host. A situation that may not be readily apparent.

The ideal way to control this would be to have host labels that could provide affinity/anti-affinity for scheduled containers. In this scenario, I can launch my host with a label that says any container to be scheduled on this machine must have the specified service label.
In this manner, if the label is forgotten on a service, it won't be scheduled onto the restricted host.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
