### ISSUE TITLE
Add Renovate to project monitoring repositories

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#44880]
- [x]  https://github.com/rancher/helm-project-operator
- [n/a]  https://github.com/rancher/helm-locker (as the repo is effectively deprecated, not counting anymore)
- [x]  https://github.com/rancher/prometheus-federator

See: https://github.com/rancher/security-team/blob/main/docs/guides/renovate.md

SURE-6233

**Comment by mallardduck** [comment]
- For [rancher/helm-project-operator](https://github.com/rancher/helm-project-operator), the configs are in place as of: https://github.com/rancher/helm-project-operator/commit/ebf7ebe1897b8262ba8f941a510a93b6813e06fe
- For [rancher/helm-locker](https://github.com/rancher/helm-locker), I made a PR here: https://github.com/rancher/helm-locker/pull/15
- For [rancher/prometheus-federator](https://github.com/rancher/prometheus-federator), I made a PR here: https://github.com/rancher/prometheus-federator/pull/84

FWIU, once these initial configs are merged in we manually trigger workflows to do our initial runs. And make any necessary adjustments based on the results we get. Then after that we will make follow up PRs to enable the cron schedule to regularly run the actions.

So this is all just Phase 1 so far, and Phase 2 will be enabling the cron schedule. I am still waiting on EIO request for myself to have more access to repos/projects. I believe once that has been completed I should see the buttons to manually trigger actions. So after that can move to next steps.

**Comment by MKlimuszka** [comment]
Blocked by https://github.com/rancher/rancher/issues/46296
