### ISSUE TITLE
Document supported list of kubernetes 1.1/1.2 features

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#4489]

**Comment by galal-hussein** [comment]
#### API - V1

- [x] Secrets
- [x] Namespaces
- [x] Rolling updates
- [x] Configmaps
- [ ] ResourceQuouta  #4454 
- [x] PV HostPath
- [ ] PV GlusterFS #4348 
- [ ] PV NFS #4423 
- [ ] PV EBS #4444 

#### API - V1beta

- [x] Deployments
- [x] DeploymentRollback
- [x] Jobs
- [x] Daemonsets
- [x] replicasets
- [ ] HorizontalPodScaling (Depend on Heapster #4451 )

#### Addons

- [ ] Dashboard #4452 
- [ ] Heapster #4451

**Comment by alena1108** [comment]
@galal-hussein thanks for the list, very helpful!

**Comment by alena1108** [comment]
@deniseschannon ^^ :)

**Comment by galal-hussein** [comment]
@alena1108 You are welcome

**Comment by girishshilamkar** [comment]
@galal-hussein Thanks for the list ! 
Looking at the list for K8s features it seems emptyDir volume support is not being tracked.

**Comment by galal-hussein** [comment]
@girishshilamkar I must have forgot to add it, it was tested and it worked perfectly.

**Comment by girishshilamkar** [comment]
@galal-hussein Good to know. Created an issue to add gitRepo support [4976](https://github.com/rancher/rancher/issues/4976) could you please add it to the list. Thanks !

**Comment by galal-hussein** [comment]
@girishshilamkar added, thanks!

**Comment by girishshilamkar** [comment]
AFAIU, io.rancher.container.create_agent io.rancher.container.agent.role labels are Rancher specific and they won't work for Kubernetes objects, is that correct ?

**Comment by deniseschannon** [comment]
These labels will work for containers created in k8s running on Rancher.

**Comment by girishshilamkar** [comment]
@deniseschannon Thanks for the update. Let me try it in one of the templates then.

**Comment by alena1108** [comment]
@galal-hussein can you test HorizontalPodScaling as the Heapster is fixed already? I don't believe we have a separate ticket opened for it.

**Comment by prachidamle** [comment]
@galal-hussein @alena1108 maybe we should also add Deis workflow to the list

**Comment by galal-hussein** [comment]
@alena1108 Heapster still has some issues that prevents it to collect node information, please check its issue https://github.com/rancher/rancher/issues/4451, i tested the same setup on AWS k8s and it worked without throwing the same error.

@prachidamle Deis added under Addons.
