### ISSUE TITLE
Ensure RKE1 / KDM for Rancher v2.9 include all relevant changes from v2.8

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#44902]
Umbrella issue to ensure that any relevant changes done in https://github.com/rancher/rke/tree/release/v1.5 / https://github.com/rancher/kontainer-driver-metadata/tree/dev-v2.8 are ported to https://github.com/rancher/rke/tree/release/v1.6 / https://github.com/rancher/kontainer-driver-metadata/tree/dev-v2.9

**Comment by chiukapoor** [comment]
KDM v2.9 branch was recreated from KDM v2.8 branch in https://github.com/rancher/kontainer-driver-metadata/pull/1381
RKE v1.6 branch was recreated from RKE v1.5 branch in https://github.com/rancher/rke/pull/3557
