### ISSUE TITLE
Some members with Github as Auth Provider could not be shown in cluster member list

### ISSUE THREAD

**Issue by gaktive** [rancher/rancher#44907]
Internal reference: SURE-7818
Reported in 2.7.9

Some members (Auth Provider=Github) could not be shown in cluster member list.

The user exists on Github Enterprise and the user exists on the list under Add Cluster Member but not when using the filter string upon typing within the Select Member textbox.

**Comment by nickwsuse** [comment]
Verified on v2.9-head ID: `fd73f` ✅ 
---
1. Fresh Install | v2.9-head | Org/Team/User Search
2. Fresh Install | v2.9-head | Team Access
3. Fresh Install | v2.9-head | Nested Memberships
4. Fresh Install | v2.9-head | Enable two (or more) orgs in GH provider
5. Upgrade | v2.8.4 → v2.9-head | GH Auth Enabled Before Upgrade | Org/Team/User Search
6. Upgrade | v2.8.4 → v2.9-head | GH Auth Enabled Before Upgrade | Team Access
7. Upgrade | v2.8.4 → v2.9-head | GH Auth Enabled Before Upgrade | Nested Memberships
8. Upgrade | v2.8.4 → v2.9-head | Enable two (or more) orgs in GH provider
