### ISSUE TITLE
[2.8] Shibboleth + LDAP small error when searching user and groups (shibbolethconfig-serviceAccountPassword) 

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#44917]
backport #44845

**Comment by bigkevmcd** [comment]
@nickwsuse Can you clarify whether or not the Shibboleth installation on 2.8.3 is working _before_ the upgrade?

**Comment by nickwsuse** [comment]
@bigkevmcd Apologies, Shibboleth was **_not_** working on 2.8.3 before the upgrade
`2024/05/07 15:50:32 [WARNING] ldap search principals failed to get ldap config: error getting secret cattle-global-data:shibbolethconfig-serviceAccountPassword secrets "shibbolethconfig-serviceAccountPassword" not found`

**Comment by samjustus** [comment]
@martyav we need to add a last-minute release note to this issue 
@bigkevmcd please add a comment detailing the expected behavior

**Comment by bigkevmcd** [comment]
> When the Shibboleth is configured with OpenLDAP in versions prior to 2.8.4, the secret configuration is incorrect, admins will be unable to search for users in the OpenLDAP server, and will see `[WARNING] ldap search principals failed to get ldap config: error getting secret cattle-global-data:shibbolethconfig-serviceAccountPassword`, the generated secret is `cattle-global-data:shibbolethconfig-serviceaccountpassword`, but this is incorrectly referenced in the `shibboleth` AuthConfig resource, this has been fixed, and the correct name is now identified.
>
> Currently, if you have Shibboleth installed with OpenLDAP and this is not working, it will not be automatically fixed, you can disable and reenable Shibboleth, or alternatively, you can work around this by fixing the secret reference in the `shibboleth` AuthConfig, by changing `.openLdapConfig.serviceAccountPassword` to `cattle-global-data:shibbolethconfig-serviceaccountpassword`.

**Comment by martyav** [comment]
@LucasSaintarbor is the primary writer for the release notes this cycle. Lucas, can you add the note in the comment above?

**Comment by bigkevmcd** [comment]
What I'm going to propose we do, is add an additional status "SecretNameMigrated" or something similar and add a migration based on that status.

**Comment by nickwsuse** [comment]
@bigkevmcd I see a [2.9 PR](https://github.com/rancher/rancher/pull/45701) for the upgrade migration, but I don't see one for 2.8 yet. Is there one, or if not when can we expect one to be ready?

**Comment by nickwsuse** [comment]
Verified on v2.8-head ID: `a91f7c5` ✅ 
----
### Fresh Install
1. Enable Shibboleth ✅ 
2. Enable LDAP connection with Shibboleth ✅ 
3. Shibboleth Service Account Password is properly stored as `shibbolethconfig-serviceAccountPassword` ✅ 
4. Search for and add LDAP users and groups ✅ 
5. CRTBs and PRTBs properly created for LDAP users
6. LDAP users have correct permissions ✅ 

### Upgrade
1. Shibboleth Service Account Password is properly stored as `shibbolethconfig-serviceAccountPassword` ✅ 
2. Search for and add LDAP users and groups ✅ 
5. CRTBs and PRTBs properly created for LDAP users
6. LDAP users have correct permissions ✅
