### ISSUE TITLE
Support Docker 1.11

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#4491]
With the changes from Docker 1.10 -> Docker 1.11, this issue to consolidate issues found when using Docker 1.11.

**Comment by rootsongjc** [comment]
With Docker 1.11 and Rancher 1.0.1, the container monitor can't get any metrics.
The chart show "connecting..."
The rancher server logs:
2016-04-21 01:34:49,834 ERROR [:] [] [] [] [cutorService-16] [o.a.c.m.context.NoExceptionRunnable ] Uncaught exception org.jooq.exception.DataChangedException: Database record has been changed
time="2016-04-21T09:39:01+08:00" level=error msg="Error parsing token." error="token is expired"

**Comment by almapab** [comment]
With Rancher 1.0.1 and Docker 1.11, when deploying a new catalog app, containers show "Starting Networking". The rancher server logs:

2016-04-21 10:56:02,642 ERROR [:] [] [] [] [ecutorService-4] [.p.c.v.i.ConfigItemStatusManagerImpl] Failed null, exit code [1] output [nsenter: failed to execute /var/lib/cattle/events/config.update: No such file or directory

![image](https://cloud.githubusercontent.com/assets/2291207/14706692/933cfed6-07c0-11e6-8f75-777e29ae2028.png)

![image](https://cloud.githubusercontent.com/assets/2291207/14706699/9d58343a-07c0-11e6-82b2-e6bdd7ac62dd.png)

**Comment by sangeethah** [comment]
Following are the issues that already logged for docker 1.11.0:

https://github.com/rancher/rancher/issues/4428
https://github.com/rancher/rancher/issues/4411
https://github.com/rancher/rancher/issues/4406

**Comment by SeerUK** [comment]
Worth noting; Rancher is effectively unusable with Ubuntu Server 16.04 right now. You can't use Docker 1.10.3 that is in the Ubuntu repos because it's compiled with Go 1.6 and that causes errors, and 1.11.0 which is the only version available in the Docker repo also doesn't work.

**Comment by sennerholm** [comment]
It seems like the overlay network is broken with the latest boot2docker to. It works like charm with rancheros vagrant setup but not with docker-machine and boot2docker. Will add examples later today. 

Sincerely  Mikael

**Comment by demarant** [comment]
we would need support for docker 1.11 as well. We use tag option for the journald logging driver as for example:

```
hello:
  image: hello-world
  log_driver: "journald"
  # following tag option is supported from docker 1.11
  log_opt:
     tag: "{{.ImageName}}\{{.Name}}\{{.ID}}"
```

[related rancher forum post](https://forums.rancher.com/t/using-custom-docker-log-drivers-with-rancher/2705/8)

**Comment by deniseschannon** [comment]
Running Docker 1.10.3 and unable to add hosts running Docker 1.11.1: https://github.com/rancher/rancher/issues/4824

**Comment by deniseschannon** [comment]
Please also make sure to look at https://forums.rancher.com/t/internal-dsn-issue-rancher-metadata-not-resolved-rancher-metadata-rancher-internal-resolves-fine/964/8 when we start testing Docker 1.11.

**Comment by soumyalj** [comment]
Tested with v1.1.0-dev5-rc2. Stats are working for both hosts and containers in the following setups -
1. Centos 7 and docker 1.11.2 
2. Ubuntu 14.04.4  and docker 1.11.2

**Comment by HackerWilson** [comment]
@soumyalj
I deployed rancher with v1.1.0-dev5 today and add two hosts in rancher success, but only one host still get these errors:
```
2016/06/20 15:42:23 "token is expired"
goroutine 31 [running]:
github.com/rancherio/host-api/app/common.CheckError(0x7f8e925abbf0, 0xc208104a40, 0x2)
	/source/gopath/src/github.com/rancherio/host-api/app/common/error.go:17 +0x8a
github.com/rancherio/host-api/auth.GetAndCheckToken(0xc208040a41, 0x22b, 0x910800, 0x5)
	/source/gopath/src/github.com/rancherio/host-api/auth/auth.go:51 +0x87
github.com/rancherio/host-api/dockersocketproxy.(*Handler).Handle(0xb9ea78, 0xc208040a00, 0x24, 0xc208040a29, 0x243, 0xc20814b500, 0xc20805ae40)
	/source/gopath/src/github.com/rancherio/host-api/dockersocketproxy/proxy.go:28 +0x3c2
created by github.com/rancherio/websocket-proxy/backend.connectToProxyWS
	/source/Godeps/_workspace/src/github.com/rancherio/websocket-proxy/backend/backend.go:77 +0x5c5

E0620 15:42:23.790826   12545 error.go:26] %q
%s
 token is expired
E0620 23:42:23.996855   12572 handler.go:278] unable to get fs usage from thin pool for device 1057: no cached value for usage of device 1057
E0620 23:42:25.529006   12572 handler.go:278] unable to get fs usage from thin pool for device 1057: no cached value for usage of device 1057
E0620 23:42:26.657321   12572 handler.go:278] unable to get fs usage from thin pool for device 1057: no cached value for usage of device 1057
E0620 23:42:28.483598   12572 handler.go:278] unable to get fs usage from thin pool for device 1057: no cached value for usage of device 1057
time="2016-06-20T15:42:28Z" level="error" msg="Couldn't find container for id." error="token is expired" id="" 
time="2016-06-20T15:42:29Z" level="error" msg="Couldn't find container for id." error="token is expired" id="" 
E0620 23:42:29.609054   12572 handler.go:278] unable to get fs usage from thin pool for device 1057: no cached value for usage of device 1057
E0620 23:42:30.765153   12572 handler.go:278] unable to get fs usage from thin pool for device 1057: no cached value for usage of device 1057
time="2016-06-20T15:42:31Z" level="error" msg="Couldn't find container for id." error="token is expired" id="" 
E0620 23:42:32.451649   12572 handler.go:278] unable to get fs usage from thin pool for device 1057: no cached value for usage of device 1057
E0620 23:42:32.580418   12572 thin_pool_watcher.go:65] encountered error refreshing thin pool watcher: error determining whether snapshot is reserved: unexpected output of dmsetup status command; expected 11 fields, got 11; output: 0 209715200 thin-pool 2556 4428/524288 90274/1638400 - rw discard_passdown queue_if_no_space 
```
docker version is 1.11.2

**Comment by kmcgrath** [comment]
@soumyalj Having the same issue as @HackerWilson with AWS Linux

AMI: amzn-ami-hvm-2016.03.2.x86_64-gp2 (ami-f303fb93)
Docker Version: Docker version 1.11.1, build 5604cbe/1.11.1
Rancher Agent: rancher/agent:v1.0.2

I0624 00:46:55.893612    4241 manager.go:198] Version: {KernelVersion:4.4.11-23.53.amzn1.x86_64 ContainerOsVersion:Amazon Linux AMI 2016.03 DockerVersion:1.11.1 CadvisorVersion:0.23.2 CadvisorRevision:}
I0624 00:46:55.897143    4241 factory.go:217] registering Docker factory
E0624 00:46:55.897160    4241 manager.go:240] Registration of the rkt container factory failed: unable to communicate with Rkt api service: rkt: cannot tcp Dial rkt api service: dial tcp 127.0.0.1:15441: getsockopt: connection refused
I0624 00:46:55.897164    4241 factory.go:54] Registering systemd factory
I0624 00:46:55.897414    4241 factory.go:86] Registering Raw factory
I0624 00:46:55.897663    4241 manager.go:1072] Started watching for new ooms in manager
I0624 00:46:55.897728    4241 oomparser.go:200] OOM parser using kernel log file: "/var/log/messages"
I0624 00:46:55.897995    4241 manager.go:281] Starting recovery of all containers
I0624 00:46:55.903072    4241 thin_pool_watcher.go:117] reserving metadata snapshot for thin-pool docker-202:1-263554-pool
E0624 00:46:55.911908    4241 thin_pool_watcher.go:54] encountered error refreshing thin pool watcher: error performing thin_ls on metadata device /dev/loop1: Error running command `thin_ls --no-headers -m -o DEV,EXCLUSIVE_BYTES /dev/loop1`: exec: "thin_ls": executable file not found in $PATH
output:

I0624 00:46:55.923123    4241 manager.go:286] Recovery completed
I0624 00:46:55.924560    4241 cadvisor.go:151] Starting cAdvisor version: 0.23.2- on port 9344
E0624 00:46:55.924917    4241 handler.go:278] unable to get fs usage from thin pool for device 16: no cached value for usage of device 16
time="2016-06-24T00:46:56Z" level="info" msg="Starting event router." 
time="2016-06-24T00:46:56Z" level="info" msg="Watching state directory: /var/lib/rancher/state/containers" 
E0624 00:46:56.990770    4241 handler.go:278] unable to get fs usage from thin pool for device 16: no cached value for usage of device 16
E0624 00:46:58.147339    4241 handler.go:278] unable to get fs usage from thin pool for device 16: no cached value for usage of device 16
E0624 00:46:59.662532    4241 handler.go:278] unable to get fs usage from thin pool for device 16: no cached value for usage of device 16
E0624 00:47:01.043198    4241 handler.go:278] unable to get fs usage from thin pool for device 16: no cached value for usage of device 16
E0624 00:47:02.326208    4241 handler.go:278] unable to get fs usage from thin pool for device 16: no cached value for usage of device 16
