### ISSUE TITLE
[v2.9][1.29] Remove PSP enablement for RKE2 and K3s (imported clusters)

### ISSUE THREAD

**Issue by krunalhinguu** [rancher/rancher#44922]
`PSPAnswersField = "global.cattle.psp.enabled"` within `k3sbased_upgrade_handler.go` enforces PodSecurityPolicy (PSP) for RKE2 and K3s installations. Given the plan to remove all PSP-related code for version 1.29, it's advisable to consider removing this line as well to improve readability and maintainability for future iterations.

**However, it's important to note that this change is dependent on the removal of related chart variables.**

The line to be removed can be found at [k3sbased_upgrade_handler.go#L27](https://github.com/rancher/rancher/blob/45d7addae59a760d1370092e82c41a07bf8e9228/pkg/controllers/management/k3sbasedupgrade/k3sbased_upgrade_handler.go#L27).

This issue is related to [#43110](https://github.com/rancher/rancher/issues/43110).

**Comment by snasovich** [comment]
Moved to `v2.9-Next1` for the same reason as https://github.com/rancher/rancher/issues/43110#issuecomment-2043546582

**Comment by chiukapoor** [comment]
### Solution

* We first need to remove the PSP reference from `rancher/system-charts`
  * https://github.com/rancher/system-charts/pull/606
* The `system-upgrade-controller` charts needs to be updated in `rancher/charts` using the commit id from `rancher/system-charts`
  * PR will be created once the `rancher/system-charts` is merged.
* Remove PSP checks from SUC charts and it's upgrade process in `rancher/rancher`
  * https://github.com/rancher/rancher/pull/45427

### Testing
* Created a rancher server with `v2.8.3`. Deployed rke2 1.28 k8s downstream cluster.
* Upgraded rancher server to custom image with the PSP checks removed.
* Rancher server and SUC chart upgrade went successful, PSP was removed from the `values.yaml` of SUC chart.
![Screenshot from 2024-05-08 18-04-31](https://github.com/rancher/rancher/assets/32087475/22801393-1401-488a-9dfa-08fd9a2ba0a5)

cc: @kinarashah

**Comment by rishabhmsra** [comment]
Validated imported clusters on rancher v2.9-head using below steps:

- Created RKE2 v1.28.10+rke2r1 and K3s v1.28.10+k3s1 clusters.
- Upgraded it to v1.29.5+rke2r1 and v1.29.5+k3s1 respectively.
- Validated SUC deployment version on both the clusters : `rancher/system-upgrade-controller:v0.13.4`
- Also validated that there were no PSP resources.

Note: There was no SUC chart deployment in an imported cluster(Instead deployment was created on cluster upgrade) and the validation was done as per the previous [testing](https://github.com/rancher/rancher/issues/43730#issuecomment-1959957564:~:text=Provisioned%20a%20standalone%20RKE2%20v1.27.10,system%2Dupgrade%2Dcontroller%3Av0.13.1.).

**Comment by rishabhmsra** [comment]
Rest of the validation are completed here : https://github.com/rancher/rancher/issues/45462#issuecomment-2188645018
