### ISSUE TITLE
[RFE] Can't find 2.7.11 image in dockerhub

### ISSUE THREAD

**Issue by LaoZhang-best** [rancher/rancher#44921]
Can't find 2.7.11 image in dockerhub

**Comment by suryatejaboorlu** [comment]
I think 2.7.11 is exclusive for Prime customers. Guess there is a different repository to pull these images.

**Comment by BloodyIron** [comment]
Yeah I don't get why nothing newer than v2.7.6 (of the v2.7.x branch) isn't on dockerhub. That's 5 revisions just not accessible... What's going on here??
