### ISSUE TITLE
[BUG] Node Driver RKE1 Cluster: Unable to provision RKE1 Amazon EC2 cluster when using most recent k8s version (v1.28.7-rancher1-1)

### ISSUE THREAD

**Issue by yonasberhe23** [rancher/rancher#44931]
**Rancher Server Setup**
- Rancher version: v2.9-head
- Installation option (Docker install/Helm Chart): Helm 
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2 v1.25.9+rke2r1
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.28.7-rancher1-1
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Infrastructure Provider AWS

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Admin
  - If custom, define the set of permissions:

**Describe the bug**
User is unable to provision a RKE1 Amazon EC2 cluster when using the most recent k8s version (v1.28.7-rancher1-1) in v2.9. Older k8s version options (v1.27.11, v1.26.14, v1.25.16) work as expected. 

**To Reproduce**

1. login to Rancher as an admin
2. go to Cluster Management
3. click 'Create'
4. toggle RKE1
5. under 'Provision new nodes and create a cluster using RKE' select Amazon EC2
6. fill in all required fields
7. verify the latest k8s version is selected by default (v1.28.7-rancher1-1)
8. click 'Create'
9. wait ~8 minutes and notice the error thrown in the UI ("GetDefaultKubernetesServicesOptions: No serviceOptions found for cluster version [v1.28.7-rancher1-1] or cluster major version [v1.28]")

**Result**
User is unable to provision a RKE1 Amazon EC2 cluster when using the most recent k8s version (v1.28.7-rancher1-1)

**Expected Result**
User is able to provision a RKE1 Amazon EC2 cluster when using the most recent k8s version (v1.28.7-rancher1-1)

**Screenshots**
<img width="1038" alt="Screenshot 2024-03-18 at 12 58 29 PM" src="https://github.com/rancher/rancher/assets/127343932/e9194dab-7172-4710-a2f3-37daa70bdffd">

**Additional context**
references https://github.com/rancher/dashboard/issues/10640

**Comment by yonasberhe23** [comment]
UPDATE: This is now occurring only when using 1.29.3-rancher1-1 which is the latest k8s version

Tested on v2.9-989139e96a9de1b1792293e75d4e26e694f9a66d-head

<img width="1648" alt="Screenshot 2024-05-21 at 9 05 10 AM" src="https://github.com/rancher/rancher/assets/127343932/d41684da-6376-484c-ba19-8713737bc58f">

**Comment by magicdrums** [comment]
Hello @yonasberhe23 , what version working correctly on ec2 instances?

**Comment by yonasberhe23** [comment]
@magicdrums seems like this issue has been resolved. I'm no longer able to repro this with v1.30.1-rancher1-1, 1.29.3-rancher1-1, or v1.28.7-rancher1-1 k8s. this can be closed out.

tested in v2.9-e0af6cccbff0210e1538004dfc67f10f40597c20-head
