### ISSUE TITLE
Consider protecting docker socket from access within containers

### ISSUE THREAD

**Issue by alecl** [rancher/rancher#4493]
This  may require changes to docker itself perhaps but worthwhile to track in case something can be done. Accessing the socket within a container essentially allows free access to other containers on the host as well as the docker API to spin up more containers and would bypass any security that you setup.

https://www.ctl.io/developers/blog/post/tutorial-understanding-the-security-risks-of-running-docker-containers

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
