### ISSUE TITLE
[RFE] Usability. Allow for login and redirect to a given page within Rancher UI

### ISSUE THREAD

**Issue by juanbrny** [rancher/rancher#44930]
**Is your feature request related to a problem? Please describe.**
I have had a couple of conversations with customers that are interested in having a login+redirect service. Very much like what is described here: https://github.com/rancher/rancher/issues/35379
The whole idea behind this is the more the use Rancher and some of the tools (like Grafana dashboards) they store or share bookmarks and they'll love to use those bookmarks directly. If they are not logged in, they expect to be taken to the login page, and after that, be redirected to the page they were requesting.

**Describe the solution you'd like**
If I request an URL like this https://rancher.testcluster.com/dashboard/c/c-m-cwblz64c/explorer I want to be redirected to that specific page after going through the login page.
Currently I'm directed to the page I have defined in my preferences (which can be the main page, the last visited page, or the main page for a cluster of my choice).

**Describe alternatives you've considered**
I haven't been able to find an alternative way of doing that except doing a double request. First do the login and then use the bookmark again to get to the desired page.

**Additional context**
none

**Comment by torchiaf** [comment]
Thanks @juanbrny , I will highlights this to the UI team.
