### ISSUE TITLE
[2.8] removing permission from role template doesn't propagate to 'promoted' clusterRole in downstream cluster

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#44942]
backport #43292

**Comment by nickwsuse** [comment]
Verified on v2.8-head ID: 862f57b  ✅ 
---
### Basic Steps:
- Create Rancher v2.9-head
- `kubectl apply -f <users_roletemplate>.yaml`
- create a new standard user in Rancher
- Give the user access to the Default Project with the custom role imported from step 2
- Log in as the user and can explore the downstream cluster 
- Go to More Resources > Rancher > Mgmt Clusters
- As an admin, edit the RoleTemplate and remove the get / clusters / management.cattle.io permission
- As the user, relogin/refresh to see Mgmt Clusters is not listed 

### Cases (Tested via UI and kubectl)
- Automation: https://github.com/rancher/qa-tasks/issues/1308
- Fresh Install ✅ 
- Upgrade to v2.8-head ✅ 
- Tested on RKE1 and RKE2 downstream cluster roles ✅ 
- RBAC Regression Automation: ✅ 

Additional Upgrade Test ✅ 
1. Create rancher on 2.8.3
2. Create a role template in 2.8.3
3. Add a standard user to this role
4. Remove a rule from the role templates
5. Promoted role is not updated
6. Upgrade rancher
7. Verify standard user, now is not able to access.

Fresh checks >> remove a verb >> verify user cannot list ✅ 
Fresh checks >> add a rule >> verify user can access ✅ 
Fresh checks >> add a verb >> verify new verb is added ✅ 

Verified all three role types are still working as expected (global, cluster, project) ✅

**Comment by ajg08d** [comment]
@samjustus Which 2.8 version is this getting back ported into?
