### ISSUE TITLE
[v2.9] Windows cluster in an airgap setup doesn't properly get catalog apps. User is unable to install apps to windows cluster in airgap

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#44949]
**Rancher Server Setup**
- Rancher version: v2.7.12-rc2
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): helm, on 1.27.11+k3s1
- Proxy/Cert Details: valid certs

**Information about the Cluster**
- Kubernetes version: any rke2 cluster (tested on 1.27.11+rke2r1)
- Cluster Type (Local/Downstream):  custom downstream cluster
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): custom RKE2 using aws nodes

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
Tested as administrator, also tested with standard user. 

**Describe the bug**

Windows clusters in airgap aren't able to install apps. It appears that after the windows node is added, the catalog tries to refresh not using bundled charts, and the list is then empty so the user can't install any apps on the clsuter

**To Reproduce**

* create a rancher setup in airgap, setting `useBundledSystemCharts=true` when creating the setup
* provision a downstream cluster with windows workers (use rke2)
* wait for the cluster to get to an active state
* install monitoring chart on the windows cluster

**Result**
unable to load any bundled apps

**Expected Result**

user should be able to install apps in airgap on windows clusters

**Screenshots**

![image](https://github.com/rancher/rancher/assets/16691014/6f29ab14-7c83-4ab0-8d34-34509baf550a)

![image](https://github.com/rancher/rancher/assets/16691014/325c0e3c-2c05-46fc-b574-d51fb9085ba8)

**Additional context**

if you check the repos before registering the windows node, the charts are populated correctly. Only after adding the windows node does the issue occur. 
this is not an issue in non-airgapped environments.

**Comment by HarrisonWAffel** [comment]
This issue is highly likely to be a manifestation of SURE-8159, introduced by [this PR](https://github.com/rancher/rancher/pull/43160/files#diff-796d989f6c1367daebda4c3f2d5baed13e3ece991060dbcf049a535d9b609cf2L56), which changed how charts are handled in air-gapped clusters. The change was [reverted](https://github.com/rancher/rancher/pull/45280) in 2.8.4. 

This issue should be retested on 2.8.4 to confirm that no additional work is required from the windows team.

**Comment by slickwarren** [comment]
confirmed on v2.9.0-alpha2 that the charts are populating when using a downstream windows cluster in an airgap setup
