### ISSUE TITLE
Support user namespaces for the container service as well as individual containers for isolation once kernel/docker support in place

### ISSUE THREAD

**Issue by alecl** [rancher/rancher#4494]
https://integratedcode.us/2016/02/05/docker-1-10-security-userns/

This is good to track to provide isolation for the host from the docker daemon (support in Docker 1.10) as well as between individual containers (future kernel and docker daemon work is needed before this is possible).

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
