### ISSUE TITLE
[BUG] - RKE1 Azure node template has Ubuntu 18.04 as default image. Docker fails to install during cluster nodes provision

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#44944]
**Rancher Server Setup**
- Rancher version: `v2.9 c5b4413`
- Installation option: Helm
   - If Helm Chart, Kubernetes Cluster and version: RKE1
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version:
- Cluster Type: Downstream
   - If downstream, what type of cluster?: Azure

**User Information**
- What is the role of the user logged in? admin

**Describe the bug**

The image field of the Azure RKE1 node template defaults to the Ubuntu 18.04 image. This Ubuntu version is end of life and docker fails to install during the node creation
 

**To Reproduce**

Create a node template with correct values for vm creation. Keep the `image` input field with the defaul value.
`canonical:UbuntuServer:18.04-LTS:latest`

The `docker-install` engine script is `24.0.sh`

**Result**

Provision an Azure cluster fails. Nodes show the error: Docker failed to install
```
./24.0.sh 
# Executing docker install script, commit: e5543d473431b782227f8908005543bb4389b8de
+ sudo -E sh -c apt-get update -qq >/dev/null
+ sudo -E sh -c DEBIAN_FRONTEND=noninteractive apt-get install -y -qq apt-transport-https ca-certificates curl >/dev/null
+ sudo -E sh -c install -m 0755 -d /etc/apt/keyrings
+ sudo -E sh -c curl -fsSL "https://download.docker.com/linux/ubuntu/gpg" | gpg --dearmor --yes -o /etc/apt/keyrings/docker.gpg
gpg: WARNING: unsafe ownership on homedir '/home/docker-user/.gnupg'
+ sudo -E sh -c chmod a+r /etc/apt/keyrings/docker.gpg
+ sudo -E sh -c echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu bionic stable" > /etc/apt/sources.list.d/docker.list
+ sudo -E sh -c apt-get update -qq >/dev/null
INFO: Searching repository for VERSION '24.0.7'
INFO: apt-cache madison docker-ce | grep '24.0.7' | head -1 | awk '{$1=$1};1' | cut -d' ' -f 3

ERROR: '24.0.7' not found amongst apt-cache madison results
```

**Expected Result**

An Azure RKE1 cluster provision properly and gets active using an `image` value where the `docker-engine` script works.

**Comment by skanakal** [comment]
The image `canonical:UbuntuServer:18.04-LTS:latest` is referenced in multiple repositories. Once the updated image is approved, I will proceed with updating the` rancher/ui` and `terraform-provider-rancher2` repositories...

**Comment by jiaqiluo** [comment]
This issue can be validated by using the latest rancher/rancher head images.

**Comment by Josh-Diamond** [comment]
Ticket #44944 - Test Results - ✅ 
---

Verified on Rancher `v2.10-847b75ee9e6388c8fa6d77f1e4a7866616423a79-head`:

| Scenario | Test Case | Result |
|---|---|---|
| 1. | Provision downstream RKE1 Azure node driver cluster w/ defaults | ✅ |

---

Scenario 1 - ✅ 
1. Fresh install of Rancher `v2.10-head`
2. Provision a downstream RKE1 Node driver cluster using default image: `canonical:ubuntu-24_04-lts:server-gen1:latest`
3. Verified - docker successfully installed; cluster successfully provisions; all pods up and active; as expected
