### ISSUE TITLE
[RFE]  Utilize Azure Spot virtual instances for cluster nodes

### ISSUE THREAD

**Issue by jvanbrecht** [rancher/rancher#44959]
**Is your feature request related to a problem? Please describe.**
Want to create nodes using the cheaper (by almost 90%) spot instances on Azure

**Describe the solution you'd like**
The ability to select the azure Spot Option
Select the eviction type and policy

**Describe alternatives you've considered**
Currently considering spinning up an Ubuntu instance and installing rancher within Azure rather than my local datacenter, then spinning up additional linux hosts, and  running the manual node registration process.

**Comment by jvanbrecht** [comment]
Bump...

**Comment by neerajjose** [comment]
+1

**Comment by shameemshah** [comment]
+1

**Comment by govindkeyValue** [comment]
Much needed.
