### ISSUE TITLE
Using upper case in machine driver name causes add host to fail

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4495]
Version - v1.0.0

Steps to Reproduce: 
1.  Add a machine driver with Name = Vultr & add the vultr driver URL
2.  Go to Add host and select the Vultr in Other drop-down and add

Results: Can't find 'vultr' driver
![image](https://cloud.githubusercontent.com/assets/11514927/14694438/42722614-071d-11e6-89be-63875597a02a.png)

Expected: Should find driver

**Comment by vincent99** [comment]
Name is no longer an input

**Comment by tfiduccia** [comment]
Version - master 6/16
Verified Name field removed
