### ISSUE TITLE
[v2.8] Update Nutanix node driver to version 3.6.0 / rancher 2.8

### ISSUE THREAD

**Issue by tuxtof** [rancher/rancher#44964]
Update Nutanix node driver to version 3.6.0 for rancher 2.8

**Comment by Josh-Diamond** [comment]
Ticket #44964 - Test Results - ✅ 
---

Verified on Rancher `v2.8-a52d992b21b97ad2df43a6994a73b8792257c11b-head`:
1. Fresh install of Rancher `v2.8-head`
2. Navigate to `Cluster Management > Drivers > Node Drivers`, and observe `nutanix` driver
3. Verified - `v3.6.0` is available
4. Active `nutanix` driver
5. Verified - driver successfully activates and is available for use

Screenshot:
<img width="674" alt="Screenshot 2024-04-15 at 12 24 11 PM" src="https://github.com/rancher/rancher/assets/46494969/cd261bdb-ce9c-42e1-915c-f4c466224549">

**Comment by tuxtof** [comment]
Once enabled i also try to deploy cluster with v2.8-head and vm are correctly created
