### ISSUE TITLE
Disable HA after generating Rancher HA scripts, otherwise user could try to use it and it fails 

### ISSUE THREAD

**Issue by str3tch** [rancher/rancher#4496]
_update_ I did fix this, see later comment. But there is still an issue I think...

I'm using RancherOS v0.4.4 & Rancher v1.0.1

I've been trying to setup HA, but have so far failed (see https://github.com/rancher/rancher/issues/4459)

So my setup is currently like this:
- Normal rancher server (not HA)
- AWS ELB in front of the server 
- External MySQL database

Whilst I'm stuck on getting HA going, I thought I'd setup the rest of Rancher. 

I've created three environments (dev, qa, prod), but all three are stuck in the state "activating".

NOTE: the one thing that might have mucked things up, is that when I installed the server originally, I did not have a load balancer in front. So the host registration url was set to the IP. Then I setup my ELB, and changed the host registration url to the fqdn of the ELB. After that, I setup the environments.. and saw this issue.

![environment](https://cloud.githubusercontent.com/assets/1896276/14700024/0994d508-07e0-11e6-8398-8aad3c255449.png)

Now one other thing which might be related (if not, i'll raise another ticket) - when I go to the Add Host page, it also is stuck "generating registration url"

![generating_url](https://cloud.githubusercontent.com/assets/1896276/14700063/456d6fb8-07e0-11e6-83bd-8de2f0eb7135.png)

Here is one of the processes currently running (I think this is the one trying to create the "QA" env):

> {
> "id": "1a9",
> "type": "project",
> "links": {
> "self": "…/v1/projects/1a9",
> "agents": "…/v1/projects/1a9/agents",
> "auditLogs": "…/v1/projects/1a9/auditlogs",
> "certificates": "…/v1/projects/1a9/certificates",
> "configItemStatuses": "…/v1/projects/1a9/configitemstatuses",
> "containerEvents": "…/v1/projects/1a9/containerevents",
> "credentials": "…/v1/projects/1a9/credentials",
> "environments": "…/v1/projects/1a9/environments",
> "externalEvents": "…/v1/projects/1a9/externalevents",
> "healthcheckInstanceHostMaps": "…/v1/projects/1a9/healthcheckinstancehostmaps",
> "hosts": "…/v1/projects/1a9/hosts",
> "images": "…/v1/projects/1a9/images",
> "instanceLinks": "…/v1/projects/1a9/instancelinks",
> "instances": "…/v1/projects/1a9/instances",
> "ipAddresses": "…/v1/projects/1a9/ipaddresses",
> "labels": "…/v1/projects/1a9/labels",
> "machineDrivers": "…/v1/projects/1a9/machinedrivers",
> "mounts": "…/v1/projects/1a9/mounts",
> "networks": "…/v1/projects/1a9/networks",
> "physicalHosts": "…/v1/projects/1a9/physicalhosts",
> "ports": "…/v1/projects/1a9/ports",
> "projectMembers": "…/v1/projects/1a9/projectmembers",
> "serviceConsumeMaps": "…/v1/projects/1a9/serviceconsumemaps",
> "serviceEvents": "…/v1/projects/1a9/serviceevents",
> "serviceExposeMaps": "…/v1/projects/1a9/serviceexposemaps",
> "services": "…/v1/projects/1a9/services",
> "snapshots": "…/v1/projects/1a9/snapshots",
> "storagePools": "…/v1/projects/1a9/storagepools",
> "userPreferences": "…/v1/projects/1a9/userpreferences",
> "volumes": "…/v1/projects/1a9/volumes",
> "hostStats": "…/v1/projects/1a9/projects/1a9/hoststats",
> },
> "actions": { },
> "name": "QA",
> "state": "activating",
> "allowSystemRole": false,
> "created": "2016-04-21T05:53:34Z",
> "createdTS": 1461218014000,
> "data": {
> "fields": {
> "publicDns": false,
> "allowSystemRole": false,
> "kubernetes": false,
> "swarm": false,
> "members": [ ],
> },
> },
> "description": null,
> "kind": "project",
> "kubernetes": false,
> "members": [ ],
> "publicDns": false,
> "removeTime": null,
> "removed": null,
> "servicesPortRange": null,
> "swarm": false,
> "transitioning": "yes",
> "transitioningMessage": "In Progress",
> "transitioningProgress": null,
> "uuid": "d4f18f4e-c721-466a-b250-638cfe285a89",

these are the other processes.

![image](https://cloud.githubusercontent.com/assets/1896276/14700104/7ac57340-07e0-11e6-912f-843f3bb132b5.png)

Can you help?!

---

| Useful | Info |
| :-- | :-- |
| Versions | Rancher `v1.0.1` Cattle: `v0.159.7` UI: `v1.0.5` |
| Access | `Disabled` |
| Route | `settings.projects.index` |

**Comment by str3tch** [comment]
OK I fixed it... As soon as I clicked "Disable HA", everything worked!

But perhaps this should be made clear in the docs.. that if you are in HA mode but with no HA hosts attached, *nothing* will work.

**Comment by deniseschannon** [comment]
What do you mean by HA hosts? What step were you in the HA process? Had you stopped the script generating Rancher and started your nodes? How many nodes did you select for your HA setup and did you get them all set up before trying the next steps?

**Comment by str3tch** [comment]
Hi Denise.. sorry I will clarify my steps:

- Installed Rancher v1.0.1 using external DB
- Selected 3 Nodes HA configuration
- Copied the generated rancher_ha.sh script to another instance
- On the other instance, HA setup failed (see https://github.com/rancher/rancher/issues/4459)
- Back on the original Rancher server, I left the Settings->HA page and went to manage environments
- I added three new environments. All got stuck in Activating.
- I went to Infrastructure->Add Hosts->Custom
- This was stuck "generating registration url"
- Eventually I went back to Settings->HA
- I clicked "DisableHA"
- Everything started working again (registration url was generated, environments were activated)

So it looks like whilst a server is waiting for additional ha nodes to connect, nothing else will work.

hope this helps.

My main issue now is not being able to get HA setup (https://github.com/rancher/rancher/issues/4459)

cheers.
Stretch

**Comment by deniseschannon** [comment]
The "original Rancher server" which was used to create the scripts should only be used to generate HA scripts. There was no testing on a Rancher server in that state as we request users to stop that instance. 

We should investigate why it's enabled for HA after generating the scripts and whether or not it should be since you aren't able to use that node in the HA setup.

**Comment by str3tch** [comment]
OK makes sense. The reason why I continued using that 'original server' was because the HA scripts failed to create the HA nodes. So the only server I have is the one I've installed.

Is anyone able to help with #4459 ?

Cheers :)

**Comment by deniseschannon** [comment]
With the new HA in 1.2, this is no longer applicable as we've refactored HA to be much simpler and just run additional arguments with the rancher-server command. There is no more script generation.
