### ISSUE TITLE
pid:host setting not exported in service config

### ISSUE THREAD

**Issue by lekum** [rancher/rancher#4497]
**Rancher Version**: 1.0.1-rc2

**Docker Version**: 1.11

**OS**: RHEL

**Steps to Reproduce**: Create a service with the "PID Mode: host" checked in the configuration

**Results**: The setting is applied, but the config parameter pid:host is not exported in docker-compose

**Expected**: pid:host in docker-compose

**Comment by tfiduccia** [comment]
Version - master 4.19
Confirmed this is broken in current build.

**Comment by deniseschannon** [comment]
Duplicate of https://github.com/rancher/rancher/issues/4890

Already fixed in v1.1.0-dev5-rc2
