### ISSUE TITLE
Add CI to frameworks repos

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#44970]
There are a number of repos without any real CI (remotedialer, dynamiclistener, lasso). We should add CI to at least build/run tests

- [ ] remotedialer
- [ ] dynamiclistener
- [ ] lasso
- [ ] apiserver
- [ ] norman

**Comment by MKlimuszka** [comment]
I will split this up into sub tickets.

**Comment by tomleb** [comment]
> I'm going to close this old ticket as dupe now: [rancher/tasks#201](https://github.com/rancher/tasks/issues/201)

I see that issue lists other things like golangci-lint, go fmt and go mod verify checks. For the purpose of #44970 we're looking at just adding `go test`. This will at least gives us more confidence when PRs are opened (especially for PRs from renovate).

When we migrate to GHA proper, or perhaps later, we should revisit which ones are missing. Some are non-trivial to add, for example:
- [apiserver lint fails](https://github.com/rancher/rancher/issues/44817) for a few reasons, like not checking an error. Fixing this should go through the usual process to reduce risk of regression. (Assuming we want to actually add the error check and not just explicitely ignore it)
- Same for remotedialer (github issue not yet created).

Note that if golangci-lint runs and is trivial to fix then I'll add it as well as I go through those missing.

**Comment by MKlimuszka** [comment]
GHA migration will cover the scope of this ticket.
