### ISSUE TITLE
[2.8] Remove the clusteruserattribute in the controller's handler when the corresponding userattribute no longer exists

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#44985]
backport #44914

**Comment by joesims22** [comment]
Validated on v2.8-head id ```5ed0e02```. All scenarios in test plan have been executed and passed.

**Comment by pmatseykanets** [comment]
# Release Notes

## Rancher General

### Behavior Changes

In the unlikely case of ClusterUserAttribute being orphaned (ClusterUserAttribute exists while the corresponding UserAttribute doesn't) it will be cleaned up by the controller.
