### ISSUE TITLE
Migrate rancher/rancher-auth-service from Drone to GH Actions

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#44989]
We need to update our GH repos so that we move from Drone to GitHub Actions so that Drone can be removed. This is a preliminary step on the path to SLSA Build L3.

https://github.com/rancher/rancher-auth-service needs to move to Github Actions.

Guidance can be found at https://docs.google.com/document/d/16SQF6H7HNvKvZ4FDuqA5jRJsfWieTpaTMPmMZPRr7aQ/edit#heading=h.2olrtzjesaqu

https://github.com/rancher/image-build-coredns/pull/50/files

**Comment by samjustus** [comment]
SURE-7964

**Comment by bigkevmcd** [comment]
Is this still used?

There are no commits since 2018, and it depends on https://github.com/rancher/go-rancher which was very recently archived?
