### ISSUE TITLE
[RFE] More restricted permissions for vSphere

### ISSUE THREAD

**Issue by sdaraio** [rancher/rancher#44986]
**Is your feature request related to a problem? Please describe.**
Currently, according to the [documentation](https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/launch-kubernetes-with-rancher/use-new-nodes-in-an-infra-provider/vsphere/create-credentials), the rancher user, with a specific role and granular permissions, has to be assigned in "Global Permissions". In this case, obviously, Rancher can access, deploy and distory things in any possible Datacenter or Resource Pool of the entire infrastructure. This violates the principle of least privilege.
We manage a huge infrastructure with a very large number of clients, and we need a more restricted assignment of permissions.
Plus, with so many resources, the drop-down menus during cluster creation in Rancher are extremely slow to load and sometimes the page crashes.

**Describe the solution you'd like**
It would be nice if the permissions for vSphere were less broad, so the user can only see and use a small subset of the vSphere resources.

**Describe alternatives you've considered**
Our initial attempt to reduce the spectrum was to give the rancher user, permissions only on a specific Resource Pool, Folder, DataStore, ESXi nodes and Network. In that way, the rancher user is locked to use and see only those specific resources, and it has the ability to deploy machines without problems. But, apparently, Rancher requests at least a broader view, just "view".
From the vSphere events: "_Privilege check failed for user VSPHERE.LOCAL\rancher for missing permission System.Read. Session user performing the check: VSPHERE.LOCAL\rancher_"
So the workaround is to give rancher Read-Only permission on the entire Datacenter (no Global Permissions, only the datacenter we want to use). Doing so, Rancher is fine with the abilities it has, and it correctly deploy the machines only where it should. So we restricted its permissions to deploy machines only in specific places, but in the cluster creation page in Rancher, we see all the datacenter resources, which brings up the slowness problems I mentioned before.

**Comment by pdrantunez** [comment]
Thanks for sharing your findings, @sdaraio. I was tinkering to achieve this and I got it following your table.

However, there are two things still appearing in Rancher that can be confusing for the end user.

The `Folder` drop-down shows my selected folder but also all the parent folders individually. The folder of the `Template` I'm using also appears as an option.
![firefox_GMdECXB5T4](https://github.com/user-attachments/assets/1379b86a-c852-418e-b12b-ec0fe15e258c)

The `Network` drop-down shows my selected network but also its VDS.
![firefox_lUwf9ogqEa](https://github.com/user-attachments/assets/9914dbac-765f-450a-9b55-54d15d3b0232)

Any advice on how to hide these?

**Comment by sim500** [comment]
Hi @pdrantunez, I'm grad you found my little guide useful.

Unfortunately I don't think there's a way to hide the absolute path of the entities. Rancher needs to know the full path to send the right directives to vSphere with the APIs. And at the moment, Rancher doesn't allow any customization on the presentation of those fields.

Indeed I have the same situation as yours. Often with very long paths. Sometimes so long that makes very hard to select the entities with the dropdown.
