### ISSUE TITLE
[v2.7] Update Nutanix node driver to version 3.6.0 / rancher 2.7

### ISSUE THREAD

**Issue by tuxtof** [rancher/rancher#44983]
Update Nutanix node driver to version 3.6.0 for rancher 2.7

**Comment by Josh-Diamond** [comment]
Ticket #44983 - Test Results - ✅ 
---

Verified on Rancher `v2.7-3def2db5944369c53249e7fe44f661734a625db4-head`:
1. Fresh install of Rancher `v2.7-head`
2. Navigate to `Cluster Management > Drivers > Node Drivers`, and observe `nutanix` driver
3. Verified - `v3.6.0` is available
4. Active `nutanix` driver
5. Verified - driver successfully activates and is available for use

Screenshot:
<img width="725" alt="Screenshot 2024-04-15 at 4 12 26 PM" src="https://github.com/rancher/rancher/assets/46494969/81e67f87-56b6-44af-8b52-a95c158161c1">

**Comment by tuxtof** [comment]
i just check with v2.7-head (bd0bb77) and driver is always in 3.4

@snasovich @Josh-Diamond

**Comment by snasovich** [comment]
@tuxtof , latest `v2.7-head` images are no longer published to DockerHub and are only available from Rancher Prime registry.
https://github.com/rancher/rancher/commit/bd0bb772b60a447d352789b3d7c4368ffe50eecf is before https://github.com/rancher/rancher/pull/45003 was merged.

**Comment by tuxtof** [comment]
OK i don't have access to this registry
