### ISSUE TITLE
Update Nutanix node driver to version 3.6.0 / rancher 2.9

### ISSUE THREAD

**Issue by tuxtof** [rancher/rancher#44984]
Update Nutanix node driver to version 3.6.0 for rancher 2.9

**Comment by Josh-Diamond** [comment]
Ticket #44984 - Test Results - ✅ 
---

Verified on Rancher `v2.9-0dc6561b4a0cbcda67199cf86d45d28da10ac1f5-head`:
1. Fresh install of Rancher `v2.9-head`
2. Navigate to `Cluster Management > Drivers > Node Drivers`, and observe `nutanix` driver
3. Verified - `v3.6.0` is available
4. Active `nutanix` driver
5. Verified - driver successfully activates and is available for use

Screenshot:
<img width="660" alt="Screenshot 2024-04-15 at 12 01 34 PM" src="https://github.com/rancher/rancher/assets/46494969/ebd79996-57e7-4a31-b82a-81dcc6cb4134">

**Comment by tuxtof** [comment]
Once enabled i also try to deploy cluster with v2.9-head and vm are correctly created
