### ISSUE TITLE
Feature Request - Kubernetes HA through etcd-cluster

### ISSUE THREAD

**Issue by tsupertramp** [rancher/rancher#4499]
Rancher Version:
1.0.1
Docker Version:
1.10.3
OS: 
ubuntu
Steps to Reproduce: 
Have three Nodes in a kubernetes ENV.
Terminate the Instance on which the etcd container is running.

Results: 
Kubernetes is down + All Secrets/Pods/RC Configs are lost after the cluster
repairs itself. Which works like a charm. Thank you :)

Expected:
etcd is HA, has data on all nodes, cluster repairs it self and does not lose all the data

Temporarily Workaround Idea:
If we would allow to configure the etcd address in the kubernetes stack I could install . This would allow me to have etcd HA on different nodes. And every kubernetes Node could go offline without impacting the cluster.

I ask myself if i can click on the kubernetes stack and configure external etcd cluster through the upgrade button, and if the settings i configured will be exchanged after next rancher upgrade?
![image](https://cloud.githubusercontent.com/assets/8327755/14711663/8f700bc6-07da-11e6-9680-0f64f269ca6b.png)
![image](https://cloud.githubusercontent.com/assets/8327755/14711730/cc1b0bde-07da-11e6-95ab-03becf36bdfd.png)

Implementation Idea:
Start etcd container on every server and spin up a cluster. Kubernetes Container connects to an Array of etcd (like in coreos implementation - https://coreos.com/kubernetes/docs/latest/deploy-master.html - See configuration parameter --> - --etcd-servers=${ETCD_ENDPOINTS}). I would try to implement it through manually changes in the stack by myself but how can i "save" it that it won't change after next upgrade?

Just found the catalog ha etcd from rancher. Will try to implement it into the kubernetes stack.

Greetings Thomas 👍

**Comment by tsupertramp** [comment]
After a lot of research. Here are some Ideas to implement it.
First one:
- Create an etcd cluster through docker container on every rancher host. This is really painful because etcd is not created to be managed in dynamic environments. As soon as a Node goes down or a new one is added you need manual interaction (source: https://coreos.com/etcd/docs/latest/runtime-reconf-design.html) - This could be managed through a Container which is running on one Node of the Cluster. This Container would run together with the main kubernetes container (kube-apiserver). This container could query the rancher metadata service and collect information about the nodes. On every Node an etcd container would be started with some kind of api interface which allows to the start etcd service with the right parameters (source: https://coreos.com/etcd/docs/latest/clustering.html - These parameters must include the node ip addresses of the old servers). Furthermore the new server has to be added through etcdctl (etcdctl member add...) first before even started through the api interface. I hope this shows how stressful it is to maintain it and keep track of edge cases (like lost quorum or anything like that)

Second one:
- Create the etcd container on one node and ensure that if the node goes down the data volume will be mounted on a different host and the etcd is started again (together with the kube-apiserver). This would force to create some glusterfs between all nodes. I think this will be painful as well.

Third one:
- Backup the etcd every 5 minutes and transfer the data to the other nodes. If the etcd host goes down, the new container would ensure that it only creates a new etcd cluster if there is no backup. This would allow to easy implement it from my view but is not really "HA" as it loses data.

Third one - From my poin of view the "best" one until etcd is easy to deploy on dynamic environments:
- Allow to configure the etcd node addresses which kube-apiserver accesses.
- Publish a good guide how to install a three Node etcd cluster and monitor it.

What is your opinion?

**Comment by LLParse** [comment]
[Pull request](https://github.com/rancher/cattle/pull/1665)

**Comment by soumyalj** [comment]
Verified on master with three hosts. Powering off one of the hosts brings up etcd on another host successfully. Kubernetes pods, rc, services can be created successfully too.
