### ISSUE TITLE
[2.8] can't enable Azure AD because there is a timeout when our login code tries to do a simple GET on the user

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#45005]
backport #45004

**Comment by samjustus** [comment]
validation template here: https://github.com/rancher/rancher/pull/45572#issue-2310584147

**Comment by joesims22** [comment]
Validated on v2.8-head id `d72c515`. 

Observed updated(actual) error message instead of internal error that would show before when enabling AzureAD with a custom endpoint that points to a site/port that will not connect.
