### ISSUE TITLE
Unable to register host on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by jloisel** [rancher/rancher#4500]
Rancher Version: 1.0.1

Docker Version: 1.10.3

OS: Ubuntu 16.04 LTS Desktop

Steps to Reproduce: 
1. Launch rancher server,
2. Launch rancher host on the same machine with properly configured IP.

Results: 
Unable to launch the agent to register a host, it fails fast with the following logs:
Error response from daemon: 400 Bad Request: malformed Host header

Expected:
It should register the local host properly.

**Comment by vincent99** [comment]
It appears the Ubuntu-packaged Docker was compiled with Go 1.6, for no obvious reason.  This breaks communication with older clients, Docker switched and there was a whole thread that resulted in them reverting back: https://github.com/docker/docker/issues/20865

So you will need to use the docker binaries from Docker, not Ubuntu, until they fix it.

**Comment by jloisel** [comment]
Thanks Vincent for the prompt answer! Going to see how to install Docker binaries, as their get.docker.com script is not working for some unknown reason.

**Comment by jloisel** [comment]
Unfortunately, it seems like there is an issue with installing Docker on Ubuntu Xenial using their APT repository:
https://github.com/docker/docker/issues/22182

The issue should be fixed in Docker 1.11.1.

**Comment by jloisel** [comment]
The solution can be to switch the repository to testing (instead of main) in docker.list, it installs 1.11.0-rc5 at the moment.

**Comment by tiborvass** [comment]
@jloisel sorry for the issue, it's fixed now on our end.

**Comment by vincent99** [comment]
Thanks @tiborvass

**Comment by jloisel** [comment]
@tiborvass Thanks!

**Comment by hwinkel** [comment]
but this means docker 1.11 installation which is as far I know not supported my rancher?

**Comment by vincent99** [comment]
"supported" is relative.. the main thing that doesn't work is cAdvisor/stats graphs, but we can't make Docker add 1.10 to their Xenial repo.

Also I put in a bug with Ubuntu and they pulled in a PR based on what @ibuildthecloud suggested to support the Host header in Go 1.6, so the packaged 1.10.3 should work now:  https://bugs.launchpad.net/ubuntu/+source/docker.io/+bug/1574904

**Comment by mercuriete** [comment]
i hit the same bug.
I'm using gentoo distribution.
docker 1.11.0
go 1.6

in gentoo we only have go 1.6.
https://packages.gentoo.org/packages/dev-lang/go

what i should do? wait?

by the way, your product is awesome. I tried in windows docker-toolbox and is amazing.
thanks for your work.

**Comment by deniseschannon** [comment]
@mercuriete If you can't downgrade to Docker 1.10.3, then you can follow this issue on when we add in Docker 1.11 support for Rancher. It will definitely be available for v1.1, which is scheduled for mid June. 

https://github.com/rancher/rancher/issues/4491

**Comment by mercuriete** [comment]
@deniseschannon thank you very much for the answer. I am only testing your product so i can wait until june or test it on a virtual machine.

PS: i cant downgrade to 1.10.3 because on gentoo we only have docker 1.11.0
https://packages.gentoo.org/packages/app-emulation/docker

your product is awesome :)
