### ISSUE TITLE
Add support for docker 26.0.x

### ISSUE THREAD

**Issue by mitulshah-suse** [rancher/rancher#45013]
Add support for docker 26.0.0. 
Release notes: https://docs.docker.com/engine/release-notes/26.0/

ref issue: https://github.com/rancher/rancher/issues/44388 

Docker versions added: 26.0.0 and 26.0.1

**Comment by chiukapoor** [comment]
install-docker PR: https://github.com/rancher/install-docker/pull/130

**Comment by vivek-shilimkar** [comment]
Tested docker install script for v26.0.0 and v26.0.1 on following OSes.
- Ubuntu 22.04
- RHEL 9.3
- Oracle Linux 9.3
- Rocky 9.3
- CentOS 7.9

Node driver and custom cluster provisioning works correctly.

SLES 15 SP5 doesn't support docker v26.0.X. Getting the following error when tried updating docker version.
`No update candidate for 'docker-24.0.7_ce-150000.198.2.x86_64'. The highest available version is already installed.`

**Comment by rishabhmsra** [comment]
Validated docker 26.0.1 and 26.0.0 script on the remaining OL versions - 9.2, 9.1 and 8.7 using both node driver and custom clusters. All validation completed, hence closing the issue.

**Comment by rishabhmsra** [comment]
Validated docker 26.0.1 and 26.0.0 script on the remaining OL versions - 9.2, 9.1 and 8.7 using both node driver and custom clusters. All validation completed, hence moving it to "ready for release"

**Comment by mitulshah-suse** [comment]
Release for the scripts were done and are available on the below URLs.

https://releases.rancher.com/install-docker/26.0.0.sh
https://releases.rancher.com/install-docker/26.0.1.sh
https://releases.rancher.com/install-docker/26.0.sh

**Comment by rishabhmsra** [comment]
Validated on rancher v2.9-head(3c48a19), Docker Install URL points to `https://releases.rancher.com/install-docker/26.0.sh`
Also successfully provisioned RKE1 v1.28 cluster, default docker version is 26.0.2
