### ISSUE TITLE
[SURE-7739] RKE2 clean up script fails in Windows nodes

### ISSUE THREAD

**Issue by skanakal** [rancher/rancher#45016]
**Rancher Server Setup**
- Rancher version: 2.8.2
- Installation option (Docker install/Helm Chart): Helm  Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): k3s , 1.24
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: 1.26
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): custom

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:

**Describe the bug**

The rke2 clean up script for Windows custom nodes fails with the error:

**To Reproduce**

Create RKE2 custom cluster v1.26.13+rke2r1 with 1 cp-etcd-worker node and 1 Windows nodes, 2019.
Create a basic deployment using image mcr.microsoft.com/dotnet/framework/runtime:4.8
Stop the deployment to remove the container
Delete the Windows node from the Rancher UI
Run the rke2-uninstall.ps1 script. 
The script fails with error:

**Result**

```
INFO: Checking if wins service exists
INFO: Cleaning c:/usr...
INFO: Cleaning c:/etc...
INFO: Cleaning c:/run...
INFO: c:/run is empty, moving on
INFO: Cleaning c:/var...
Get-ChildItem : Access to the path 'C:\var\lib\rancher\rke2\agent\containerd\io.containerd.snapshotter.v1.windows\snapshots\16\Files\Program Files\Windows Defender
Advanced Threat Protection\Classification\Configuration' is denied.
At C:\Usr\local\bin\rke2-uninstall.ps1:183 char:17
+ ...             Get-ChildItem -Path $dir -Recurse -Attributes ReparsePoin ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (C:\var\lib\ranc...n\Configuration:String) [Get-ChildItem], UnauthorizedAccessException
    + FullyQualifiedErrorId : DirUna 
```

**Expected Result**

The script should be finish sucessfully 

**Screenshots**

![image](https://github.com/rancher/rancher/assets/124564266/a12e48ba-77a4-4eb9-83a5-955dc2c827cb)

**Additional context**

**Comment by HarrisonWAffel** [comment]
I'm going to close this issue out as the associated rke2 issue has been validated by the rke2 QA team. There is no other action to be taken in the rancher codebase.
