### ISSUE TITLE
[RFE] Allow OpenStack Cluster provisioner to tag created resources

### ISSUE THREAD

**Issue by hamidos** [rancher/rancher#45025]
**Is your feature request related to a problem? Please describe.**
OpenStack Cluster provisioner doesn't tag resources(VMs, Disks, ..) created for clusters.

**Describe the solution you'd like**
A field in the cluster creation form UI to specify the tags (Node Template/ Node Pool).
Also a parameter in the `OpenstackConfig` resource.

**Describe alternatives you've considered**
A job post deployment of the cluster to add the tags using OpenStack API, but it wouldn't be a good solution specifically in case of scale up of nodes.

**Comment by vincebrannon** [comment]
SURE-8217
