### ISSUE TITLE
Uninstall system-upgrade-controller

### ISSUE THREAD

**Issue by EutiziStefano** [rancher/rancher#45029]
**Version**
Rancher 2.6.6

**Additional context**
Hi, I have migrated rancher from a k3s to a k8s cluster, and the local cluster is always blinking from Active to Upgrading state, I wish to uninstall this upgrade-controller that the migration process have transferred to the new k8s rancher installation.
I didn't find anywhere the uninstall instructions.
I deleted the deployment, configmap, serviceaccount, plans and clusterrolebinding, but the upgrading process didn't stop running... 
The plans object are also recreated...
Because now I am on k8s it is useless can anyone help me to remove it?
thanks
Stefano

**Comment by brandond** [comment]
See also: https://github.com/rancher/rancher/issues/43370
