### ISSUE TITLE
Cannot conveniently locate primary container from sidekick

### ISSUE THREAD

**Issue by moensch** [rancher/rancher#4505]
I have the need to find a parent container from a sidekick. Not the service, but the exact container.

Rancher Version: v1.0.1
Docker Version: Docker version 1.8.2-el7.centos, build a01dc02/1.8.2
OS: CentOS 7
Steps to Reproduce: 
1. Create stack with main container and sidekick
2. Attempt to find parent container from sidekick

Results: 
Not conveniently possible

Expected:
Should be conveniently possible either via DNS or rancher-metadata

I'd love to be able to do something like this from a sidekick:

```
curl -H 'accept: application/json' rancher-metadata/latest/self/parent
```

And get a reference to the parent container instance.

Or maybe even this, using DNS:

```
ping primary
```

For what it's worth, I am using this bash inside the sidekick to find the parent service instance with the same **service_index**:

``` bash
#!/bin/bash

PARENT_SERVICE="$1"

echo Discovering matching service_index instance from parent $PARENT_SERVICE

# Wait for metadata service to be available
iter=0

while :; do
  if [ $iter -gt 9 ]; then
    echo ERROR: Cannot contact rancher-metadata service
    exit 1
  fi
  curl -s --fail rancher-metadata >/dev/null
  if [ $? -eq 0 ]; then
    break
  fi
  iter=$((iter + 1))
  sleep 1
done

SERVICE_INDEX=$(curl -s --fail rancher-metadata/2015-12-19/self/container/service_index)
RET=$?
if [ $RET -ne 0 ]; then
  echo "Failed to get own service index"
  exit 1
fi

echo Service Index: $SERVICE_INDEX

PARENT_IP=""

iter=0
while :; do
  echo Locating ... iteration $iter
  if [ $iter -gt 30 ]; then
    echo ERROR: Cannot find $PARENT_SERVICE service instance in same stack with matching service_index
    exit 1
  fi

  SERVICE_INSTANCES=$(curl -s --fail rancher-metadata/2015-12-19/self/stack/services/$PARENT_SERVICE/containers)
  RET=$?

  for CONTAINER in $SERVICE_INSTANCES; do
    echo Checking container $CONTAINER
    CONT_NUMBER=$(echo $CONTAINER | cut -d'=' -f 1)
    echo "  Number: $CONT_NUMBER"
    INSTANCE_SVC_INDEX=$(curl -s --fail rancher-metadata/2015-12-19/self/stack/services/$PARENT_SERVICE/containers/$CONT_NUMBER/service_index)
    echo "  Instance service index: $INSTANCE_SVC_INDEX"
    if [ "$INSTANCE_SVC_INDEX" -eq "$SERVICE_INDEX" ]; then
      echo "    Found matching service"
      PARENT_IP=$(curl -s --fail rancher-metadata/2015-12-19/self/stack/services/$PARENT_SERVICE/containers/$CONT_NUMBER/primary_ip)
      export PARENT_IP
      break
    fi
  done

  if [ -n "$PARENT_IP" ]; then
    break
  fi

  iter=$((iter + 1))
  sleep 1
done

echo Found parent instance IP address: $PARENT_IP
```

**Comment by ruimarinho** [comment]
This is particularly even more complicated when generating config using confd from a sidekick, as at the time of booting the sidekick won't be able to list the primary ip of the main container on the same deployment unit.

This means that if the main container requires that a certain config exists at boot time (e.g. a Kafka server which requires `listeners` to be set to the main container's primary ip), the main container won't start correctly.

The workaround is having confd installed on the main container, but that defeats the purpose of the config sidekick.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
