### ISSUE TITLE
RKE2 and K3S - KDM Update for K8s April 2024 patch release for Rancher 2.7

### ISSUE THREAD

**Issue by rancher-max** [rancher/rancher#45064]
# KDM Updates

| New Kubernetes Version  | Min Rancher Version | Max Rancher Version |
|                  :---:                  |              :---:               |               :---:               |
| v1.27.13+rke2r1                  | v2.7.11-alpha1             | v2.8.99 |
| v1.27.13+k3s1                  | v2.7.11-alpha1             | v2.8.99 |

# KDM Branch
[dev-v2.7](https://github.com/rancher/kontainer-driver-metadata/tree/dev-v2.7)

# Chart Changelog

| Chart Name  | New Version | Affected Kubernetes Version(s) |
|        :---:        |       :---:        |                     :---:                     |

TBD

# Argument Changelog

| Argument Name  | Affected Kubernetes Version(s) |
|        :---:           |                     :---:                     |

TBD

# Additional Notes

**Comment by mdrahman-suse** [comment]
## K3S - v1.27.13-rc2+k3s1, Rancher v2.7.12
<img width="630" alt="Screen Shot 2024-04-24 at 7 51 11 AM" src="https://github.com/rancher/rancher/assets/91496375/7e3b4984-8972-4450-bb92-57c177eae6e4">

## K3S - v1.27.13-rc2+k3s1 and v1.28.9-rc2+k3s1, Rancher v2.8.3
<img width="660" alt="Screen Shot 2024-04-24 at 8 53 57 AM" src="https://github.com/rancher/rancher/assets/91496375/3bf4289d-217b-4b29-9491-888173e8e31d">

**Comment by rancher-max** [comment]
KDM has been merged and this is validated as per the screenshots above. It is known that during the "rc" phase, it shows as "experimental" but with the non-rc versions, it does not show the "experimental" element in the UI.
