### ISSUE TITLE
Update CAPI in Rancher to 1.7.1+

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#45090]
CAPI is currently on version 1.4.4 in the latest released `rancher-provisioning-capi` chart - https://github.com/rancher/charts/blob/release-v2.8/charts/rancher-provisioning-capi/103.2.0%2Bup0.0.1/Chart.yaml#L13

~The latest released version from upstream is https://github.com/kubernetes-sigs/cluster-api/releases/tag/v1.6.3 and the ask is to update to at least this version (which formally brings support of K8s 1.29) as part of the next minor Rancher release.~

~Depending on the timing, we should also consider updating to the higher version like 1.7.1 which (if history is any indication) should bring in official support for K8s 1.30. 1.7.0 is likely going to be released very soon as https://github.com/kubernetes-sigs/cluster-api/releases/tag/v1.7.0-rc.1 was released yesterday but we should probably skip the first minor release.~

CAPI [v1.7.1](https://github.com/kubernetes-sigs/cluster-api/releases/tag/v1.7.1) is already out with support for K8s 1.30 - so we should bump to (or newer patch version if available).

Related issues: https://github.com/rancher/rancher/issues/43110 / https://github.com/rancher/rancher/issues/45089

Update: It looks like https://github.com/kubernetes-sigs/cluster-api/issues/9334 that is a blocker to https://github.com/rancher/rancher/issues/42582 is close to be fixed, including backport to v1.6.x / v1.7.x CAPI release lines (see https://github.com/kubernetes-sigs/cluster-api/pull/10431 / https://github.com/kubernetes-sigs/cluster-api/pull/10430) so we want to update to the versions that include this fix.

**Comment by vardhaman22** [comment]
CAPI is updated to v1.7.3 with [PR](https://github.com/rancher/provisioning/pull/11) and chart [PR](https://github.com/rancher/charts/pull/4107) is also merged.

**Comment by mitulshah-suse** [comment]
@Oats87 @jakefhyde Do we need any separate testing for this or the 1.30 support testing will already cover whatever testing is needed for this?
cc: @snasovich

**Comment by snasovich** [comment]
@mitulshah-suse , I think between v2prov automated testing running as part of Rancher CI and manual testing on RKE2/K3s provisioning cases we should have pretty good coverage to cover CAPI bump. If you happen to run into any new issues, we will need to evaluate them and see if they can be attributed to CAPI bump.
@Oats87 / @jakefhyde , let us know if you can think of any specific scenarios that should be tested.
@mitulshah-suse , if you don't hear back on the above, feel free to assume this will be sufficiently tested implicitly.

**Comment by vivek-shilimkar** [comment]
Tested on RKE1, RKE2 k8s v1.30. CAPI version is updated to v1.7.3. Hence, closing the ticket.
