### ISSUE TITLE
[BUG] Upgrading rancher-vsphere-csi chart causes VSphere CSI Controller pod to go into CrashLoop

### ISSUE THREAD

**Issue by thatmidwesterncoder** [rancher/rancher#45093]
**Rancher Server Setup**
- Rancher version: 2.8.2
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): rke2
- Proxy/Cert Details: n/a

**Information about the Cluster**
- Kubernetes version: 1.25 -> 1.26
- Cluster Type (Local/Downstream): local
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:
admin

**Describe the bug**

After successfully upgrading RKE2 from 1.25 to 1.26.15, the pods vsphere-csi-controller loop in Crashloopbackoff

```
2024-04-09T14:27:31.572532954Z {"level":"info","time":"2024-04-09T14:27:31.570244465Z","caller":"k8sorchestrator/k8sorchestrator.go:1019","msg":"Could not find the multi-vcenter-csi-topology feature state in ConfigMap internal-feature-states.csi.vsphere.vmware.com. Setting the feature state to false","TraceId":"0ace9e09-c8e4-40ac-9cd6-fe343b48ca51"}
```

Most likely, this problem [https://github.com/kubernetes-sigs/vsphere-csi-driver/issues/2594 ](https://github.com/kubernetes-sigs/vsphere-csi-driver/issues/2594)says that since 3.1, multi-vcenter-csi-topology must be activated
(one of the evolutions from 1.25.16 to 1.26.15 is the vsphere csi from 3.0.1 to 3.1.2)

Though in the rancher-vsphere-csi helm chart 'rancher-vsphere-csi' there is no mention of multi-vcenter-csi-topology.

In the code, it is mentioned here :
https://github.com/kubernetes-sigs/vsphere-csi-driver/blob/d47f32067cff2b1b0df58c8a7435ef3030354b88/pkg/csi/service/common/constants.go#L409C38-L409C54

The CSI controllers can be restarted with success when editing the configmap to include the field.

**To Reproduce**

Difficult - this only seems to occur when upgrading a vsphere cluster from 1.25 -> 1.26

**Result**
Vsphere CSI controller is in crashloop backoff.

**Expected Result**

Vsphere CSI controller is running like normal.

**Screenshots**

**Additional context**

SURE-8151

**Comment by HarrisonWAffel** [comment]
The vsphere-csi chart has been bumped to include the missing config map field and merged into dev-v2.9, this can now be tested

**Comment by snasovich** [comment]
We would like to release note not only the fix itself but also change to default values for flags like in https://github.com/rancher/vsphere-charts/pull/78

**Comment by slickwarren** [comment]
https://github.com/rancher/qa-tasks/issues/1291

**Comment by susesgartner** [comment]
Ticket #45093 - Test Results - ✅ 
---
 
| Scenario | Test Case | Result |
|---|---|---|
| 1. | Upgrade CSI/CPI cluster from 1.25 to 1.26 | PASS |

---
Verified with a docker install of Rancher `v2.9-f26d9888bb35bba93fa3780285ff881c39f76e65-head`:
---
 
Scenario 1: Upgrade CSI/CPI cluster from 1.25 to 1.26
---
1. Create a 3 node split role k8s 1.25 cluster with CSI/CPI enabled
2. Upgrade the k8s version to 1.26 
3. Verify that all pods are active after the upgrade
 
Results: The CSI-controller pods remain in a stable state
