### ISSUE TITLE
client version 1.22 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version

### ISSUE THREAD

**Issue by 777ilya777** [rancher/rancher#45103]
When i try add local docker, i should run command - 
--
docker run --rm --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.2.11 http://192.168.1.107:8080/v1/scripts/0B6BDED3A16D20235DF6:1703980800000:QyIjGiWnDpaL7LPXqcQkekels   
---
But giet this error
Error response from daemon: {"message":"client version 1.22 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version"}
p.s. If remove version and use lateest...no luck, error its a same

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.30` Cattle: `v0.183.83` UI: `v1.6.52` |
|Access|`Disabled`|
|Orchestration|`Cattle`|
|Route|`hosts.new.index`|

**Comment by phancongha24** [comment]
Anyone help?

**Comment by mikygit** [comment]
same here :-(

**Comment by dangtrungnguyen2020** [comment]
https://forums.rancher.com/t/unable-to-add-new-hosts/42502

**Comment by TheBoroer** [comment]
Just a note for anyone else stumbling across this. Rancher v1.6's latest agent (v1.2.11) only works with Docker v24 and lower.

Downgrading docker on the new host is the only way to still add the host to an old rancher server.
