### ISSUE TITLE
[Backport v2.8] [BUG] Upgrading rancher-vsphere-csi chart causes VSphere CSI Controller pod to go into CrashLoop

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#45106]
Backport of https://github.com/rancher/rancher/issues/45093 to v2.8 line of releases (we don't need one for 2.7 as vSphere CSI is not on 3.1.x there).

**Comment by HarrisonWAffel** [comment]
The vsphere-csi chart has been bumped to include the missing config map field and merged into dev-v2.8, this can now be tested

**Comment by susesgartner** [comment]
Ticket #45106 - Test Results - ✅ 
---
 
| Scenario | Test Case | Result |
|---|---|---|
| 1. | Upgrade CSI/CPI cluster from 1.25 to 1.26 | PASS |

---
Verified with a docker install of Rancher `v2.8-head`:
---
 
Scenario 1: Upgrade CSI/CPI cluster from 1.25 to 1.26
---
1. Create a 3 node split role k8s 1.25 cluster with CSI/CPI enabled
2. Upgrade the k8s version to 1.26 
3. Verify that all pods are active after the upgrade
 
Results: The CSI-controller pods remain in a stable state
