### ISSUE TITLE
[BUG] Cannot use us-south1 (Dallas) GCP region for GKE

### ISSUE THREAD

**Issue by michelmarinho** [rancher/rancher#45118]
**Rancher Server Setup**
- Rancher version: v2.8.2
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version:
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:

I'm using Rancher v2.7.2 on GCP with us-east1.
When I create downstream cluster with GKE. It is not in the list  us-south1 (Dallas)  region.

**Describe the bug**

**To Reproduce**

**Result**

**Expected Result**

**Screenshots**

**Additional context**

**Comment by guilhermebob** [comment]
Hello,

I have the same problem in the us-south1 region (Dallas)

Our customers use this region a lot for GCP projects, which makes it impossible for us to use the tool for monitoring and accessing systems.

This is a great tool and we would like to provide this monitoring environment to our customers, it would help a lot in our tasks.

Best regards

**Comment by michelmarinho** [comment]
Fixed in version 2.8.3
