### ISSUE TITLE
[install-docker] Disable Tests For EOL docker versions and Unsupported OSs in CI

### ISSUE THREAD

**Issue by vardhaman22** [rancher/rancher#45114]
currently all the versions are tested in CI and because of that CI build timeout after an hour in some cases
exa CI runs: https://drone-pr.rancher.io/rancher/install-docker/241 and https://drone-pr.rancher.io/rancher/install-docker/258

Unsupported OSs:
- ubuntu:18.04
- ubuntu:20.04
- oraclelinux:7

EOL Docker Versions
- 20.10.x
- 19.0.x

**Comment by chiukapoor** [comment]
Updated `config.sh` for all docker version and default in `test-docker` script removing the EOL docker version and unsupported OSes

```
TEST_OS_IMAGE_NAME=(oraclelinux centos ubuntu rockylinux redhat/ubi9 quay.io/centos/centos redhat/ubi8)
TEST_OS_IMAGE_TAG[0]="8 9"
TEST_OS_IMAGE_TAG[1]="centos7"
TEST_OS_IMAGE_TAG[2]="22.04"
TEST_OS_IMAGE_TAG[3]="8 9"
TEST_OS_IMAGE_TAG[4]="9.3"
TEST_OS_IMAGE_TAG[5]="stream8"
TEST_OS_IMAGE_TAG[6]="8.9"
```
