### ISSUE TITLE
Referencing volume with wrong capitalization causes duplicate mount point error

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4513]
Version - v1.0.1

Steps to Reproduce: 
1.  Add glusterfs and convoy glusterfs catalogs
2.  Go to Storage Pools and Add Volume
3.  Make the Volume Name = Testvolume
4.  Create a service (or a container) and point the volume to testvolume:/newfolder, and volume driver = convoy-gluster

Results: Service fails and says " Error (500 Server Error: Internal Server Error ("Duplicate mount point '/newfolder'"))

Expected: In Add Volume, the Name is case insensitive (I can only add testvolume once no matter if I change to anything to be capital or not), we should recognize that for the service as well.

**Comment by cjellick** [comment]
Legit bug, but I don't think it is critical enough to keep in 1.2.0. Can we bump out?
