### ISSUE TITLE
Environment Variable on External Service Alias

### ISSUE THREAD

**Issue by hendryluk** [rancher/rancher#4514]
External Service Alias (and internal alias too) is a nice way to externalise and consolidate your backend references. The problem is that each backend service usually has its own specific settings, e.g. bearer token, access-key, port numbers, etc that the linking service needs to know about.
Typically when you link to a (docker) service, you could define those settings as environment variables of the linked service, to be consumed by the linking service.
However, I can't seem to find a way to define environment variables to a linked external service. Definitely not from the UI. When I tried defining it using docker-compose.yml, even thought the environment variables do get created within the agent-instance container, these variables aren't getting transported across to the linking service.
Any possibility to support environment variables in (external and internal) service aliases?

**Comment by deniseschannon** [comment]
When you are referring to "external service alias", what exactly are you referring to?

Are you referring to [external services]( http://docs.rancher.com/rancher/rancher-ui/applications/stacks/adding-external-services/) or [service aliases](http://docs.rancher.com/rancher/rancher-ui/applications/stacks/adding-service-alias/)?

Are you trying to link to a docker container that is hosted outside of Rancher and have environment variables passed to that container?

**Comment by hendryluk** [comment]
I was referring to both. But let's have a look at the use case for external services specifically first.
What I need is the opposite of what you were describing. I need to pass certain metadata information from the _external services_ onto the consuming containers. In the docker world, this is normally achieved by environment variables. 
Example:
Imagine I have a docker-compose where ServiceA has a link pointing to ServiceB. (ServiceA and ServiceB are managed by 2 different teams). On the ServiceB, I have an env called "bearer-token", and this env becomes visible to ServiceA. This is a way for ServiceA to know what bearer-token to use when communicating with ServiceB. This way, you have a decoupling between ServiceA and ServiceB, where the bearer token can differ for every environment, but regardless of which ServiceB that ServiceA is pointing to, it always gets the correct bearer-token without needing any reconfiguration.
This seems to be a common integration pattern I've seen used in the docker world.

In rancher, when I try to link to an external-service, I noticed that I could not define any env variable on external-services, and was wondering whether there's any specific reason for this.

**Comment by deniseschannon** [comment]
Is this concept actually possible in docker-compose? Can you really have a service A that reads environment variables from serviceB?

**Comment by vincent99** [comment]
When you link to a container in Docker you automatically get all is environment variables to (which is a terrible idea because they're used for passwords and secrets alk the time, but it is what it is).

**Comment by hendryluk** [comment]
@deniseschannon Yes this is the current behavior of docker-compose, i.e. when you link A to B, the env of A gets imported to B (with a specific prefix).
Rancher-compose also does that, although for some reason it changes the prefix format, which breaks many third-party docker-based components that are making use of this feature. But I suppose that's a separate issue.

**Comment by warroyo** [comment]
This functionality would be great to have. I was thinking of using an external service in rancher as a way to inject environment specific ENV variables into any container that links to it. unfortunately this is not currently possible since the environment variables of external service do no get injected into the containers they link to. Any update on if this will be added?

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
