### ISSUE TITLE
[RFE] [Monitoring V2] windows-exporter should no longer depend on rancher/wins

### ISSUE THREAD

**Issue by HarrisonWAffel** [rancher/rancher#45148]
This is a tracking issue for https://github.com/rancher/windows/issues/223 in rancher/rancher, which is ready to be tested on dev-v2.8.

**Comment by slickwarren** [comment]
tested on v2.8-head (421ce19)
* deploy a windows cluster on 1.27 using the currently released chart
  * upgrade the chart to 103.1.0-rc1+up45.31.1 -- pass
* deploy a windows cluster on the latest k8s version available (1.28)
  * install the chart 103.1.0-rc1+up45.31.1 -- pass
