### ISSUE TITLE
Restore test fails after cleanup

### ISSUE THREAD

**Issue by shindebshekhar** [rancher/rancher#45155]
Hello,

We are trying to perform restore test after Rancher cleanup.

Below are the steps:

1. Rancher running on v2.8.2
2. Total 6 Downstream cluster imported
3. Backed up rancher on s3 object store
4. Performed cleanup using using cleanup script(https://github.com/rancher/rancher-cleanup/tree/main)
5. Installec Backup resources (v103.0.0+up4.0.0)
6. Created a Restore object and apply
7. Observed the logs kubectl logs -n cattle-resources-system --tail 100 -f -l app.kubernetes.io/instance=rancher-backup
8. Found below error. 
   **ERRO[2024/04/17 09:59:09] Error restoring namespaced resources [error restoring fleet-agent of type /v1, Resource=secrets: restoreResource: err creating resource namespaces "cattle-fleet-local-system" not found]
ERRO[2024/04/17 09:59:09] error syncing 'restore-migration': handler restore: error restoring namespaced resources, check logs for exact error, requeuing**

9. Deleted the restore object
10. Installed Rancher
11. All objects/downstream clusters were available

Now I did search based on the error logs(step#8) . I found this issue was documented(https://github.com/rancher/rancher/issues/35050#issuecomment-937968556) stating that "_If a resource has both the deleteionTimeStamp and finalizers, it means the resource is in the middle of the deletion process. But since it matches the resoueceSet in the backup configuration, it will be saved in the backup file and restored into the cluster when we restore the backup file_."_

I downloaded the backup file and searched for the object which has deletionGracePeriodSeconds and found one json file(customresourcedefinitions.apiextensions.k8s.io#v1/gitjobs.gitjob.cattle.io.json) which has deletionGracePeriodSeconds but the error in step#8 was for some other resource

Now my question is how do I ensure my backup is clean in case if I need to restore?

Note- I performed this test couple of times with same result.

**Comment by mallardduck** [comment]
Hello @shindebshekhar - at around the time you reported this issue we released an update for Rancher backups that likely could change the results. It included some pretty important bug fixes that this seems very likely related to.

Around March 25th we had already related [103.0.1+up4.0.1](https://github.com/rancher/charts/tree/release-v2.8/charts/rancher-backup/103.0.1%2Bup4.0.1) but by now you should instead try `103.0.2+up4.0.2` as this is the newest Rancher backup for 2.8 Rancher. Please update, take a new backup and try again.
