### ISSUE TITLE
DNS for service alias to external service sometimes unresolvable

### ISSUE THREAD

**Issue by eguswes** [rancher/rancher#4517]
We're using different stacks in our solution. As an example, we have a stack called platform that points on external services, the internal stacks that need external services use service aliases to ease the management when an external service is changed.

However, sometimes we get errors from our applications with the error "DNS unresolvable"
---

| Useful | Info |
| :-- | :-- |
| Versions | Rancher `v1.0.0` Cattle: `v0.159.2` UI: `v0.100.3` |
| Access | `Disabled` |
| Route | `authenticated.project.help` |

**Comment by alena1108** [comment]
@eguswes could you share docker-compose.yml of your stack? And point which resolution path from this compose file not working. It would help us to reproduce the issue in house.

**Comment by eguswes** [comment]
Here it is, I’ve cleaned it from a number of personal services. My theory is, it appears when a service breaks down, maybe the DNS service is disrupted by frequent renewals/restarts from a failing service.

httpd:
  log_driver: ''
  labels:
    io.rancher.container.pull_image: always
  tty: true
  log_opt: {}
  image: httpd:2.4
  volumes:
  - jobs:/var/opt/jobs
  stdin_open: true
kafka:
  external_links:
  - platform/kafka:kafka
  image: rancher/dns-service


kafka:
  image: rancher/external-service


/Gustaf

**Comment by deniseschannon** [comment]
I used your docker-compose.yml using v1.2.0-pre2-rc3 and did not have any issues with dns resolution. 

@eguswes Are you still having this issue with our later versions?

**Comment by eguswes** [comment]
The problem occurred when one service was failing or something changed. Intermittent, maybe one in a hundred/thousand. That’s the big problem with intermittent problems, you just test them and can reproduce them straight away…

**Comment by aemneina** [comment]
Closing this out as it sounds like you rooted the problem to a faulty container.
