### ISSUE TITLE
[v2.8] [BUG] Inadvertent removal of SSH from `rancher/machine`

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#45174]
Backport of https://github.com/rancher/rancher/issues/45173 for 2.8.x.

**Comment by macedogm** [comment]
New version of rancher/machine was bumped in https://github.com/rancher/rancher/pull/45195.

**Comment by susesgartner** [comment]
Ticket #45174 - Test Results - ✅
---
 
| Scenario | Test Case | Result |
|---|---|---|
| 1. | Provision a downstream RKE2 cluster | PASS |

---
Verified with (HA Helm or Docker) on Rancher `v2.8-efccfef83579dd0fdc5d3cccd954906e516e1df8-head`:
---
 
Scenario 1: Provision a downstream RKE2 cluster 
---
1. Provision a downstream RKE2 cluster with Centos 9 as the OS
2. Verify that the cluster comes up active 
 
Results: The cluster came up active and all pods are in a stable state.
