### ISSUE TITLE
[BUG] Inadvertent removal of SSH from `rancher/machine`

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#45173]
`rancher/machine:v0.15.0-rancher107` through `rancher/machine:v0.15.0-rancher110` are missing `ssh` for the same reason that caused https://github.com/rancher/rancher/issues/43115 (`git-core` no longer has dependency on `openssh-clients`).

Unlike for `rancher/rancher` this didn't cause any immediately apparent issues for OSes listed in [Support Matrix (for 2.8.3)](https://www.suse.com/suse-rancher/support-matrix/all-supported-versions/rancher-v2-8-3/) it seems to affect some OSes that were working before due to fallback to Go's built-in SSH implementation - see https://github.com/nutanix/docker-machine/issues/101 for such an example.

Note at this time the affected versions of `rancher/machine` are only used by latest Rancher releases (2.7.12 and 2.8.3) with previous releases unaffected.

**Comment by tuxtof** [comment]
https://github.com/rancher/machine/pull/240

**Comment by snasovich** [comment]
`rancher/rancher` PR will be opened after https://github.com/rancher/rancher/pull/45082 is merged as it updates `rancher/machine` as well.

**Comment by susesgartner** [comment]
Ticket #45173 - Test Results - ✅
---
 
| Scenario | Test Case | Result |
|---|---|---|
| 1. | Provision a downstream RKE2 cluster | PASS |

---
Verified with HA Helm on Rancher `v2.9-f26d9888bb35bba93fa3780285ff881c39f76e65-head`:
---
 
Scenario 1: Provision a downstream RKE2 cluster 
---
1. Provision a downstream RKE2 cluster with Centos 9 as the OS
2. Verify that the cluster comes up active 
 
Results: The cluster came up active and all pods are in a stable state.
