### ISSUE TITLE
[go-rancher] [client] let's encrypt support

### ISSUE THREAD

**Issue by mbrmj** [rancher/rancher#4519]
Rancher Version:1.0.0

Docker Version:1.10.3

OS: rancher-os v0.4.4

Steps to Reproduce: 
I'm using drone as my CI backbone,to deploy and communicate with in rancher-server drone use rancher client as a library. I hosted my rancher-server under a domaine that use Let's encrypt as Certifiicate Authority .

Results: 
when I try to deploy using drone this message shows up 
"Failed to create rancher client: Get https://domaine.com: x509: certificate signed by unknown authority"
Expected:
well the expected result is that the process does not stop in the SSL verification of the domaine.

Is there any chance for you to add support let's encrypt. or any work-around that you can suggest like skipping ssl verification ?
thank you.

**Comment by deniseschannon** [comment]
@janeczku added let's encrypt as a community [catalog entry](http://docs.rancher.com/rancher/catalog/). 

https://github.com/rancher/rancher/issues/2734

**Comment by mbrmj** [comment]
My problem is not that i can't generate a let's encrypte certificate for rancher it's already done with a nginx reverse proxy. what I'm strugling with is that rancher client block when I give him an https domaine to communicate with.
returning this message :
