### ISSUE TITLE
Loading UI with super slow connection shows different icons

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#452]
Version: Master on 4/7/15

When the internet was extremely slow, I got a strange loading of the Rancher UI.

![screen shot 2015-04-07 at 11 43 19 am](https://cloud.githubusercontent.com/assets/11410997/7031054/c82bd64a-dd1d-11e4-9ee0-001cb8722b70.png)

**Comment by vincent99** [comment]
Weird.. the request for one version of the font must be timing out and one of the other variants succeeds.

**Comment by vincent99** [comment]
We no longer use this icon set, or remote hosting of them.
