### ISSUE TITLE
[Question] Is there a way to configure global settings via the Helm chart?

### ISSUE THREAD

**Issue by mig4ng** [rancher/rancher#45217]
I searched all documentation and the `value.yaml` file for the chart.

Is there a way of configuring rancher settings via the helm chart?

E.g. I want to configure `kubeconfig-default-token-ttl-minutes` to be different from the default one in the settings.

**Comment by SebPlv** [comment]
Hi,

I'm looking for the same feature.
For the moment, I use kubectl patch for that :

`k patch settings.management.cattle.io kubeconfig-default-token-ttl-minutes --type='json' -p='[{"op": "replace", "path": "/value", "value":"129600"}]'`

But it'd be much better if we could set that in the value.yaml file.

**Comment by mig4ng** [comment]
This is still relevant

**Comment by erictoner** [comment]
This is still relevant - is there any way to update this via helm chart? It would make the helm chart complete.

@SebPlv thanks for the heads up about the settings patch.

Edit:
For anyone using Terraform to set up Rancher, you can use the rancher2_setting resource:
```
resource "rancher2_setting" "kubeconfig_default_token_ttl" {
  name  = "kubeconfig-default-token-ttl-minutes"
  value = "129600"
}
```
