### ISSUE TITLE
[Backport] - [v2.7] Bump Windows Containers throughout Rancher

### ISSUE THREAD

**Issue by HarrisonWAffel** [rancher/rancher#45218]
This is a backport issue of https://github.com/rancher/windows/issues/222 for the 2.7 release line. Validation of this ticket requires a smoke test of Rancher logging and Rancher monitoring. No functional changes were made to either chart,  however we should still check that the new images used function as expected

**Comment by slickwarren** [comment]
tested the following regression checks on 2.8-head (421ce19):
* node driver provisioning -- pass
* node driver upgrades -- pass
* custom cluster provisioning -- pass
* custom cluster upgrades -- pass
* chart installation (monitoring) -- pass
* chart installation (logging) -- pass
* chart upgrade (monitoring) -- pass
* workloads/deployments -- pass
