### ISSUE TITLE
[Forward Port] - [v2.9] Bump Windows Containers throughout Rancher

### ISSUE THREAD

**Issue by HarrisonWAffel** [rancher/rancher#45219]
This is a forwardport issue of https://github.com/rancher/windows/issues/222 for the 2.9 release line. Validation of this ticket requires a smoke test of Rancher logging. No functional changes were made to the chart, the windows image was simply rebuilt and bumped to remove foreign layers. However, we should still check that the new image functions as expected

**Comment by slickwarren** [comment]
tested on 2.9-head (4dd0c38a2aab4f77271c07d2c887ecf5bbcea5e3):

* provision windows clusters (1.28.10+rke2r1, 1.29.5+rke2r1, 1.30.1+rke2r1) -- pass
* upgrade windows clusters (1.28.10+rke2r1 ->1.29.5+rke2r1 -> 1.30.1+rke2r1) -- pass
* deploy windows apps + workloads (logging, monitoring) -- pass
