### ISSUE TITLE
Migrate Norman CI To Github Actions

### ISSUE THREAD

**Issue by MbolotSuse** [rancher/rancher#45229]
Norman's CI currently uses [drone](https://github.com/rancher/norman/blob/master/.drone.yml). We need to migrate away from drone to Github Actions. This should be changed for at least the following branches:

- master
- release/v2.7
- release/v2.8

After all stages have been removed, the drone.yml file should be removed to prevent new CI runs from occurring through drone.

**Comment by tomleb** [comment]
CI migrated to GHA for all three release lines of norman. Closing.
