### ISSUE TITLE
Migrate Wrangler CI To Github Actions

### ISSUE THREAD

**Issue by MbolotSuse** [rancher/rancher#45226]
Wrangler's CI currently uses [drone](https://github.com/rancher/wrangler/blob/master/.drone.yml). We need to migrate away from drone to Github Actions. This should be changed for at least the following branches:
- [x] master
- [ ] release-2.2
- [ ] release-2.1
- [ ] release-2.0-untagged

After all stages have been removed, the drone.yml file should be removed to prevent new CI runs from occurring through drone.

**Comment by tomleb** [comment]
This was merged to master but hasn't yet been backported
cc: @MKlimuszka @ericpromislow
