### ISSUE TITLE
For bad volume names, fix error message

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4522]
Version - v1.0.1

Steps to Reproduce: 
1. Add glusterfs and convoy glusterfs catalogs
2. Go to Add Volume and create a volume with a space in it
3. Create a container that uses that volume

Results: Error (500 Server Error: Internal Server Error ("create abc def: Invalid volume abc def. Must be only contains 0-9, a-z, dash(-), underscore(_) and dot(.)")) - "Must be only contains" is not proper english,

Expected: Fix error message to say "Can only have" or even "Can only contain"

**Comment by cjellick** [comment]
Naming should be fixed in convoy-nfs. We are no longer updating convoy-gluster.

**Comment by tfiduccia** [comment]
Version - v1.2.0-pre4-rc3
Verified fixed
