### ISSUE TITLE
Show created Volume even if there are no mounts

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4523]
Version - v1.0.1 

Steps to Reproduce: 
1. Add glusterfs and convoy glusterfs catalogs
2. Go to Add Volume and create a volume

Results: Can't see that volume anywhere even thou it exist and is accessible through the API

Comment:  It would be nice to be able to see the volumes I added so I can use them easily without having to go through the API to find it.

**Comment by willseward** [comment]
@tfiduccia Sometimes if you refresh the page they will show up as "requested". 

That may not be your issue though.

**Comment by tfiduccia** [comment]
duplicate #3208
