### ISSUE TITLE
Provide better errot message when username/password is incorrect in kubectl config file.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#4524]
Rancher Version:Build from master

Have a kubernetes environment set up.
Copy config from kubectl window to local machine.
In the config file , make the username/password invalid.

When kubectl commands are executed , user is presented with the following error message:
 "Error form server has prevented the request from succeeding" 

The error message provided should be more descriptive of the actual problem.

**Comment by HackerWilson** [comment]
I was wondering if #5564 has something related to this topic.
