### ISSUE TITLE
Manually stopping service that is in Error state will restart itself

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4525]
Rancher Version: v1.0.1

Steps to Reproduce: 
1.  Add glusterfs and convoy glusterfs catalogs
2.  Go to Storage Pool and add a volume where the Name = "Testvolume"
3.  Create a service with Volume = testvolume:/testfolder & volume driver = convoy-gluster
4.  Wait for service to error (it will say something about a duplicate errror)
5.  Go to Stacks page and manually stop the Service

Results: After a few minutes the service will restart itself.  Looks like if the service goes into error before the container is fully created, even if I manually stop the service, it will wait a little bit then restart itself.

Expected: If I manually stop the service, it should not restart itself.

Comment: Sorry about the steps, this was the only way I could figure out how to get the container to error before fully creating.

**Comment by alena1108** [comment]
It is a generic problem in the process framework: if the process gets stuck, it doesn't get cancelled by the follow up process. So here what happens:

1) Service.activate is called. It failed, and we just kept on retrying 
2) Service.deactivate was called. It put service to inactive state.
3) As Inactive state is still a valid state for service.activate process, service.activate will not be canceled,but instead we will retry over and over again.

@ibuildthecloud not sure how we should handle this one.

**Comment by tfiduccia** [comment]
For QA - easier to reproduce steps found in bug #7396, just create a service with a bad image and then try to stop it.
