### ISSUE TITLE
Volume Driver name link at top of Storage Pool page goes to blank page

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4527]
Version - v1.0.1 

Steps to Reproduce: 
1.  Create glusterfs & convoy glusterfs catalog
2.  Go to Storage pool page
3.  Click on convoy-gluster name at top of storage pool page

Results: Goes to blank page

Expected: Should go to details page or not be link?

**Comment by lvuch** [comment]
Is this true on all storage pools?

**Comment by vincent99** [comment]
Yes, just remove the link for now

**Comment by tfiduccia** [comment]
Version - master 6/17
Verified fixed
