### ISSUE TITLE
[RFE] Update Schema Definitions to use openapi v3

### ISSUE THREAD

**Issue by MbolotSuse** [rancher/rancher#45272]
**Is your feature request related to a problem? Please describe.**

Currently, the steve schema definitions endpoint primarily uses the openapi/v2 enpdoint to retrieve definitions for types. This approach has several limitations:
- Fields which aren't able to be expressed in openapi's v2 syntax have incomplete defintions (see #45157). This will likely require us to fetch/process not only all openapi/v2 definitions, but also all CRDs.
- CRDs which have no definitions are returned as empty `proto.Maps` rather than `proto.Kinds`, and are missing several common fields such as `apiVersion`, `kind`, and `metadata` (see #45158).
- Any future removal/deprecation of openapi/v2 would necessitate rapid changes (note that this doesn't seemed to be planned at the moment).

**Describe the solution you'd like**
Rather than using a combination of openapi/v2 and crds, steve should source the definitions from the openapi/v3 endpoint. Note that this should use client-go's built-in `OpenAPIV3()` functionality.

**Describe alternatives you've considered**
N/A.

**Additional context**
OpenAPI V3 went GA in [1.27](https://kubernetes.io/blog/2023/04/24/openapi-v3-field-validation-ga/). Prior to this point, it wasn't guaranteed that this endpoint would be available. Because of this, before this feature is implemented, the following needs to be done:
- Rancher needs to exclusively support 1.27+ versions of Kubernetes.
- We need to confirm that it is no longer possible to disable this endpoint (it appears to not be something that can be disabled, but this needs to be double-checked).

**Comment by tomleb** [comment]
We were unable to do this for the schema definition fix (https://github.com/rancher/rancher/issues/45157) because the kube-openapi library doesn't parse the references properly. So the definition schema ends up not having anything from ObjectMeta, managed fields, etc.

I've opened the following https://github.com/kubernetes/kube-openapi/issues/477 to see if we can get that addressed.
