### ISSUE TITLE
Ubuntu 24.04 validations on v2.9

### ISSUE THREAD

**Issue by chiukapoor** [rancher/rancher#45289]
**Is your feature request related to a problem? Please describe.**
* SURE-8315

**Describe the solution you'd like**
* Add Ubuntu 24.04 Support

**Comment by chiukapoor** [comment]
Ubuntu 24.04 only supports Docker 26 and 26.1 at the moment.

```
ubuntu@ip-172-31-31-12:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 24.04 LTS
Release:        24.04
Codename:       noble
ubuntu@ip-172-31-31-12:~$ sudo apt list -a docker-ce
Listing... Done
docker-ce/noble 5:26.1.0-1~ubuntu.24.04~noble amd64
docker-ce/noble 5:26.0.2-1~ubuntu.24.04~noble amd64
docker-ce/noble 5:26.0.1-1~ubuntu.24.04~noble amd64
docker-ce/noble 5:26.0.0-1~ubuntu.24.04~noble amd64
```

**Comment by Gerungofulus** [comment]
I tested this the other night by simply replacing the docker version in the install script with 26.10.. The install script runs perfectly. However, during startup of my first custom cluster it fails noting some missing API. I tried the latest versions of RKE and K3S. If any of the maintainers want me to investigate, I‘d be willing to spend a couple of hours on it if pointed at some direction (I am completely new to setting up Kubernetes so I‘ll probably need help still). I‘ll add screenshots and a description of what’s wrong later.

**Comment by rishabhmsra** [comment]
Validated on rancher v2.9-head

Docker 25.0.5 and 25.0.4 validation completed for below OSes on both node driver and custom clusters:
- RHEL 9.3 and 8.9
- OL 9.3 and 8.9
- Rocky  9.3 and 8.9
- CentOS 7.9
- Ubuntu 22.04

**Comment by rishabhmsra** [comment]
Validated on rancher v2.9-head, ami used : ami-09040d770ffe2224f 

Downstream cluster checks - PASS

Network checks passed on below clusters :
  - RKE1 node driver and custom cluster
  - RHE2 node driver and custom cluster
  - K3s node driver and custom cluster
------------
Local cluster checks - PASS
- RKE1
- RKE2
- K3s

All checks passed, hence closing it.
