### ISSUE TITLE
Space in catalog name breaks images and catalogs

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4528]
Version - v1.0.1 

Steps to Reproduce: 
1.  Go to settings
2.  Add a catalog and put a space in the Name field (example: tani catalog)
3.  Go to that catalog
4.  Try to open a catalog from there

Results: All the images for the catalog are missing.  Error in dev tool: http://104.197.170.20:8080/v1-catalog/templates/tani%20catalog:twofieldversiontest?image.  Go to error page when trying to open catalog.

Expected: Should still show images or we should not allow them to add spaces

**Comment by bengerman13** [comment]
Same issue occurs with dashes

**Comment by EugenMayer** [comment]
confirmed with spaces, but dashes seem to work for me

**Comment by prachidamle** [comment]
Duplicate of https://github.com/rancher/rancher/issues/3124
