### ISSUE TITLE
[DOCUMENTATION] Supported Feature Versions 

### ISSUE THREAD

**Issue by sass1997** [rancher/rancher#45290]
**Is your feature request related to a problem? Please describe.**
I think the documentation about the compatiblity of feature charts wasn't updated since the last few releases. As example the rancher-backup. As it is written in the readme of rancher/charts it needs to follow this schema

```
In this repository, all packages specify the version field in the package.yaml.

The upstream charts follow this versioning: 1.0.#+upX.Y.Z

X.Y.Z is the upstream chart's major.minor.patch

The 1.0.# versioning scheme roughly corresponds to the following rules (with exceptions):

Major Version: represents the Rancher minor version these charts are being released to.
Anything less than 100: Rancher 2.5
100: Rancher 2.6
101 and 102: Rancher 2.7
103: Rancher 2.8
104: Rancher 2.9
etc.
Minor Version: represents a release line of a given chart within a Rancher minor version.
Patch Version: represents a patch to a given release line of a chart within a Rancher minor versio
```

Since we are installing and upgrading not over UI clicking we require a proper documentation about version compatiblity
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by alexandreLamarre** [comment]
@sass1997 Could you specify the issue observed with backup-restore chart versions and rancher version compatibility?

Helm CLI install are not fully supported since the UI does additional API driven validation and value injection, as well as removing incompatible versions with given setups
