### ISSUE TITLE
Add support for docker 25.0.4 and 25.0.5

### ISSUE THREAD

**Issue by mitulshah-suse** [rancher/rancher#45291]
The following docker versions are to be added:
v25.0.4
v25.0.5

The same approach as https://github.com/rancher/rancher/issues/43362 is to be followed for implementation and testing.

**Comment by rishabhmsra** [comment]
Validated on rancher v2.9-head

Docker 25.0.5 and 25.0.4 validation completed for below OSes on both node driver and custom clusters:
- RHEL 9.3 and 8.9
- OL 9.3 and 8.9
- Rocky  9.3 and 8.9
- CentOS 7.9
- Ubuntu 22.04

**Comment by vivek-shilimkar** [comment]
Validated on rancher v2.8-head

Docker 25.0.4 and 25.0.5 validation completed on below OSes with node driver and custom clusters:
- RHEL 9.3 and 8.9
- OL 9.3 and 8.9
- Rocky  9.3 and 8.9
- CentOS 7.9
- Ubuntu 22.04

**Comment by mitulshah-suse** [comment]
Release for the scripts was done and its available on the install-docker url.

https://releases.rancher.com/install-docker/25.0.4.sh
https://releases.rancher.com/install-docker/25.0.5.sh

Closing the issue.
