### ISSUE TITLE
k8s: integration with Rancher private registry

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#4529]
Private registries registered in Rancher, should be available in k8s setups. All user would have to do is:

* create private registry in Rancher
* in POD spec, provide image name in a form of privateRegistryName/imageName. No extra configuration steps should be done on k8s nodes.

**Comment by tombmurphy** [comment]
+1

It makes no sense to support k8s in Rancher if it doesn't support with private registries.

Is there any workaround ?

**Comment by alena1108** [comment]
@tombmurphy unfortunately no workarounds for now. It is going to work in conjunction with Rancher private registries in Rancher dev4 release.

**Comment by alena1108** [comment]
@soumyalj test using ```rancher/k8s:v1.2.4-rancher-1``` image

**Comment by soumyalj** [comment]
Tested for Dockerhub and Quay.io. They are working. 
Private registry is yet to be tested.

**Comment by alena1108** [comment]
@soumyalj if the bug is not fully tested, don't assign it back to developer.

**Comment by soumyalj** [comment]
Tested Private registry on Kubernetes, it is working.

**Comment by colmaengus** [comment]
Is there anything special that needs to be done to enable this ?
I'm using v1.1.0-dev4 and have added a private custom registry (privately hosted dockerhub).
I'm able to create a container explicitly with rancher in hosts tab but when I create a replication controller inside k8s it doesn't pick up the credentials.

**Comment by alena1108** [comment]
@colmaengus if k8s was enabled on your environment before dev4, you would have to re-enable it to pick up k8s dev4 image changes. Besides that, nothing extra needs to be configured.

**Comment by colmaengus** [comment]
@alena1108: just tried this and it does't work

**Comment by deniseschannon** [comment]
@colmaengus Just to warn you, if you try and disable/re-enable the environment again, your k8s environment will not work with v1.1.0-dev4 (https://github.com/rancher/rancher/issues/5204) and you'd need to upgrade to v1.1.0-dev5

Do you have any specific logs from rancher/server?

**Comment by deniseschannon** [comment]
When we say disable/re-enable, I found out that it means you need to switch to a cattle type and come back to a k8s type. Due to this and the release of v1.1.0-dev5, you will need to upgrade to dev5 to have it working.

**Comment by alena1108** [comment]
@colmaengus can you check kubelet logs generated after replicationController/pod create command was issued?

**Comment by colmaengus** [comment]
Hi Alena, Denise,

Sorry for the delay in getting back to this.
We upgraded to rancher dev5, created a new k8s environment and the registry
credentials are being passed down as expected.
Thanks for you prompt response to my original query.

Regards

Colm A

On Wed, Jun 22, 2016 at 6:27 PM, Alena Prokharchyk <notifications@github.com
