### ISSUE TITLE
[BUG] Errors while removing an etcd member can cause RKE to try to remove the member indefinitely

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#45309]
`rancher/rancher` tracking issue for https://github.com/rancher/rke/issues/3570

SURE-7601

**Comment by jakefhyde** [comment]
Blocked, waiting for RKE1 1.6 rc.

**Comment by susesgartner** [comment]
Ticket #45309 - Test Results - ✅ 
---
 
| Scenario | Test Case | Result |
|---|---|---|
| 1. | Remove node from cluster with etcdctl | PASS |
| 2. | Remove node from cluster | PASS |
 
---
Verified with (HA Helm or Docker) on Rancher `v2.9-alpha5`:
---
 
Scenario 1: Remove node from cluster with etcdctl
---
1. Create a 3 node all role rke1 cluster
2. SSH into the node and remove a node using "docker exec etcd etcdctl member remove"
3. Delete the node in the UI
 
Results: The node gets properly deleted and does not hang.

Scenario 2: Remove node from cluster
---
1. Create a 3 node all role rke1 cluster
3. Delete the node in the UI
 
Results: The node gets properly deleted and does not hang.
