### ISSUE TITLE
Catalog items upgrade for k8s deployment

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#4530]
k8s introduced Deployment object in v1.2 - a wrapper around Replication Controller providing an upgrade support.
This feature would help us to do k8s catalog template items upgrade. The flow will be as follows:

* Deployment is created from catalog item v1.
* When catalog gets an update, we signal user that his Deployment has newer version in the catalog.
* User picks the desired version, and we send an upgrade call with the new template to kubectl.

Following fixes are needed:

1) UI fixes: 

* pass catalog item URI to create/update calls + check against catalog items for upgrade.
* Deployment tab in the UI with standard CRUD options + k8s upgrade related options (upgrade/rollback)

2) Backend fixes: inject catalog item URI to Deployment's metadata so the UI can read it. It can be done in our kubectld service: https://github.com/rancher/kubectld/blob/master/server/server.go#L28-L37

3) Catalog fixes: for new templates, we should start using Deployment instead of a Replication controller.

**Comment by vincent99** [comment]
How do we know which templates can be upgraded?  They can consist of any combination of k8s resources, not just deployments.

**Comment by deniseschannon** [comment]
I would assume that this would work after #5268 was completed.

**Comment by tfiduccia** [comment]
Version - v1.2.0-rc4
Verified fixed
