### ISSUE TITLE
k8s HA deployment and k8s stack upgrade

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#4531]
k8s should be deployed in HA mode. That will also allow to run upgrades on k8s stacks. 

This feature request will be used as a placeholder for other k8s HA related bugs:

https://github.com/rancher/rancher/issues/4499

**Comment by alena1108** [comment]
@LLParse could you update the ticket once etcd ha PR is merged?

**Comment by LLParse** [comment]
Will do.

**Comment by soumyalj** [comment]
Features verified v1.1.0-dev5-rc5.
