### ISSUE TITLE
[v2.9] Rancher logging does not work on windows nodes when using `logging-operator:4.4.0`

### ISSUE THREAD

**Issue by HarrisonWAffel** [rancher/rancher#45320]
This is a forward port issue for https://github.com/rancher/rancher/issues/45308

**Comment by HarrisonWAffel** [comment]
Note that this fix is included in `103.1.1-rc1`, which means that rancher must be configured to deploy pre-release charts in order for this to be tested

**Comment by slickwarren** [comment]
tested on v2.9-head 4dd0c38a2aab4f77271c07d2c887ecf5bbcea5e3

    deploy logging 104.0.0+up3.17.10  on a cluster with windows nodes (1.28.10+rke2r1) -- pass
        upgrade the cluster to a later version of k8s (1.29.5+rke2r1) -- pass
