### ISSUE TITLE
[go-rancher] Schema validation when creating machine

### ISSUE THREAD

**Issue by diogogmt** [rancher/rancher#4532]
When initializing the go-rancher client with an Account API KEY it is not possible to create machines on environments, the following error message is raised:

URL: `POST http://server.rancher:8080/v1/machines`

```
Resource type [machine] is not creatable
```

If using an Environment API KEY instead the creation of the machine is successful.
URL: `POST http://server.rancher:8080/v1/projects/1a14/machines`

After doing some debugging I noticed that the UI actually sends a request to `POST http://server.rancher:8080/v1/machines` when creating a host
The only difference I could find was that the header attribute `x-api-project-id` was set in the request made on the UI

After adding the header attribute to the go-rancher request [here](https://github.com/rancher/go-rancher/blob/master/client/common.go#L323) I was able to use an Account API KEY and create a host on an environment through the go-rancher client

```
req.Header.Set("x-api-project-id", "1a14")
```

@ibuildthecloud 
Is this a problem with the API schema validation?
Should we patch the go-rancher client to add the `x-api-project-id` header attribute?

**Comment by vincent99** [comment]
`x-api-project-id` is an alternate way of setting the project context, which makes that request the equivalent of `/v1/projects/1a14/machine`.  Without that you're making a request to create a machine as your user, and users can't own machines, only environments.

**Comment by diogogmt** [comment]
@vincent99 
The go-rancher client loads the API schema for the matching the API key provided when setting up the base client: https://github.com/rancher/go-rancher/blob/master/client/common.go#L145

The problem is that we are setting up the client with an Account API Key and later setting the environmentId as the ```x-api-project-id``` on every subsequent request.
The environmentId could change since one account could manage multiple environments.

How can we bypass the schema validation when setting up the client with an Account API Key?

**Comment by vincent99** [comment]
You can't "bypass" it, it's server-side validation... You're trying to create a machine owned by a user account and they are only allowed to be owned by a project.

There just needs to be an easy way to provide the project context  in the library when creating a client (and if you need multiple, create multiple clients...)

Side note: The current UI always use the URL path version now and not the header.  It will eventually be deprecated and removed, explaining 2 different modes of url context is confusing.

**Comment by deniseschannon** [comment]
@diogogmt Let us know if you have any more questions.

**Comment by diogogmt** [comment]
@deniseschannon 

What would be the recommend approach in the following scenario:

I have an account API key which I use to instantiate a go-rancher client that manage multiple environments created by that account.
I need a way to specify the environment context when sending API requests that were authenticated with the account API key.
Before I was setting the ```x-api-project-id``` header on the requests to set the environment scope. However, based on what @vincent99 mentioned that feature will be deprecated, right?
If so would I need to add the environmentId to the URL path of every API request to accomplish the same result?

And regarding the schema validation I still have the same problem where by instantiating a go-rancher client with an API key it pulls the schema for the account which it fails to validate when doing any actions on environment resources.
Would the go-rancher client need to be patches to pull the schema for the environment as well?

**Comment by vincent99** [comment]
`X-Api-Project-Id` was added for the UI, which no longer uses it, so yes you should expect it to go away at some point (though it's still in 1.2).

`NewRancherClient()` takes in `ClientOpts`, which has a `Url`, which can point to the schemas for a particular environment (http://host:8080/v1/projects/1a5/schemas) instead of the root.  You need to instantiate a separate client object for each environment.
