### ISSUE TITLE
k8s 1.30 Support for rancher-alerting-drivers

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#45338]
Add k8s 1.30 Support for rancher-alerting-drivers

**Comment by pankajsqe** [comment]
User is not able to find rancher-alerts chart on marketplace to install on v2.9.0-alpha5 (Local : v1.30.1+rke2r1, Downstream AKS : v1.30.0-eks-036c24b)



https://github.com/rancher/rancher/assets/149133120/a57bf0c6-ce0f-4ea3-85a6-50c12c3d5c00

**Comment by pankajsqe** [comment]
Pass Verified in rancher v2.9-head Below are the test cases. 

Local Cluster

- Provisioned Rancher with local k8s v1.28.7+rke2r1 cluster.
- Installed rancher-monitoring:104.0.0-rc1+up45.31.1
- Installed rancher-alerting-drivers:104.0.0-rc1
- Configured monitoring and alerting to monitor and send alerts on telegram
- Upgraded Local cluster to k8s v1.30.1+rke2r1
- Verified configured monitoring still sending alerts.
- Monitoring passed p0 test cases.
- Monitoring outbound links, grafana, prometheus targets function properly - ie, no dead links.
- Chart annotations are correct.
- Uninstall Monitoring and Alert app successfully on local cluster and deleted respective namespaces.
- Fresh install monitoring and alert app on v1.30.1+rke2r1
- Configured monitoring and alerting to monitor and send alerts on telegram on fresh installation of app.
- Verified configured monitoring still sending alerts.
- Monitoring outbound links, grafana, prometheus targets function properly - ie, no dead links. 

Downstream Cluster

- Provisioned downstream k8s 1.28.7+rke2r1 cluster.
- Installed rancher-monitoring:104.0.0-rc1+up45.31.1
- Installed rancher-alerting-drivers:104.0.0-rc1
- Configured monitoring and alerting to monitor and send alerts on telegram
- Upgraded downstream cluster to k8s v1.30.1+rke2r1
- Verified configured monitoring still sending alerts.
- Monitoring passed p0 test cases.
- Monitoring outbound links, grafana, prometheus targets function properly - ie, no dead links
- Chart annotations are correct.
- Uninstall Monitoring and Alert app successfully on downstream cluster and deleted respective namespaces.
- Fresh install monitoring and alert app on K8s v1.30.1+rke2r1
- Configured monitoring and alerting to monitor and send alerts on telegram on fresh installation of app.
- Verified configured monitoring still sending alerts.
- Monitoring outbound links, grafana, prometheus targets function properly - ie, no dead links.
