### ISSUE TITLE
k8s 1.30 Support for prometheus-federator

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#45337]
Add k8s 1.30 Support for prometheus-federator

**Comment by pankajsqe** [comment]
Pass : Verified in rancher v2.9.0-alpha5 on local and downstream cluster. Below are the test cases.

**Local Cluster**

- Provisioned Rancher with local k8s v1.28.7+rke2r1 cluster.
- Installed prometheus-federator: 104.0.0-rc1+up0.4.0
- Create a new project, namespace with at least one workload on it so you can track pod metrics.
- Under the cluster view hit monitoring > project monitors and click the project you created.
- Verify that metrics are flowing and graph are displaying correct data.
- Upgraded Local cluster to k8s 1.30.1+rke2r1
- Verified configured project still projecting logs correct metrics and data.

**Downstream Cluster**

- Provisioned downstream k8s v1.28 cluster.
- Installed prometheus-federator: 104.0.0-rc1+up0.4.0
- Create a new project, namespace with at least one workload on it so you can track pod metrics.
- Under the cluster view hit monitoring > project monitors and click the project you created.
- Verify that metrics are flowing and graph are displaying correct data.
- Upgraded Local cluster to k8s v1.30
- Verified configured project still projecting logs correct metrics and data.
