### ISSUE TITLE
k8s 1.30 Support for rancher-logging

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#45335]
Add k8s 1.30 Support for rancher-logging

**Comment by prachidamle** [comment]
Are we blocked on testing the chart?

**Comment by mallardduck** [comment]
I think this still has a slight blocker in that Rancher only has experimental provisioning of 1.29. So we cannot create 1.30 downstreams like I am for testing on 1.29; so I may just need to test the chart installing onto a "local" 1.30 rancher cluster.

I will start that progress once I've sorted out the current issues found on 1.29. As that issue seems it would apply to both 1.29 and 1.30 anyway.

**Comment by pankajsqe** [comment]
Pass Verified in rancher v2.9.0-alpha5. Below are the test cases.

Local Cluster

- Provisioned Rancher with local k8s 1.29.4+rke2r1cluster.
- Installed rancher-logging:104.0.0-rc1+up4.4.0
- Setup splunk server to receive logs.
- Configured Rancher to send logs on splunk server and Verify logs are being received in splunk.
- Upgraded Local cluster to k8s v1.30.1+rke2r1
- Verified configured logging still sending logs to splunk server.
- Logging passed p0 test cases.
- Logging components like services, deployment and pods are up and running.
- Chart annotations are correct.
- Uninstall Logging app successfully on local cluster and deleted respective namespaces.
- Fresh install Logging app on K8s v1.30.1+rke2r1
- Configured Rancher to send logs on splunk server and Verify logs are being received in splunk.

Downstream Cluster

- Provisioned Rancher with downstream k8s v1.28 cluster.
- Installed rancher-logging:104.0.0-rc1+up4.4.0
- Setup splunk server to receive logs.
- Configured Rancher to send logs on splunk server and Verify logs are being received in splunk.
- Upgraded downstream cluster to k8s V1.30 EKS
- Verified configured monitoring still sending alerts.
- Logging passed p0 test cases.
- Logging components like services, deployment and pods are up and running.
- Chart annotations are correct.
- Uninstall Logging app successfully on local cluster and deleted respective namespaces.
- Fresh install Logging app on K8s V1.30 EKS
- Configured Rancher to send logs on splunk server and Verify logs are being received in splunk.
