### ISSUE TITLE
Failed to create pod with hostNetwork spec

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#4534]
Rancher Version:
1.0.1
Docker Version:
1.10.1
OS: 
Ubuntu 14.04
Kubectl Version:
1.2.0

When creating a pod with spec option hostNetwork set to true the pod stuck in pending state and the pod never gets created, however the container appears in infrastructure tab.

**Comment by alena1108** [comment]
@soumyalj test with rancher 1.2.4 kubernetes image

**Comment by soumyalj** [comment]
@alena1108 : With hostNetwork=True, the containers are not starting successfully. It is constantly restarting.

**Comment by soumyalj** [comment]
The issue was seen even with replica: 1

**Comment by alena1108** [comment]
@wlan0 can you look at it?

**Comment by alena1108** [comment]
@soumyalj i assume it works now? could you retest?

**Comment by soumyalj** [comment]
Tested with 1.1.0-rc5. Workd fine.
