### ISSUE TITLE
k8s 1.29 support for rancher-monitoring

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#45354]
Add k8s 1.29 support for rancher-monitoring

**Comment by pankajsqe** [comment]
Pass Verified in rancher v2.9.0-alpha5 Below are the test cases.

Local Cluster

- Provisioned Rancher with local k8s v1.28.7+rke2r1 cluster.
- Installed rancher-monitoring:104.0.0-rc1+up45.31.1
- Configured monitoring and alerting to monitor and send alerts on telegram
- Upgraded Local cluster to k8s v1.29.4+rke2r1
- Verified configured monitoring still sending alerts.
- Monitoring passed p0 test cases.
- Monitoring outbound links, grafana, prometheus targets function properly - ie, no dead links.
- Chart annotations are correct.
- Uninstall Monitoring and Alert app successfully on local cluster and deleted respective namespaces.
- Fresh install monitoring on K8s v1.29.4+rke2r1
- Configured monitoring and alerting to monitor and send alerts on telegram on fresh installation of app.
- Verified configured monitoring still sending alerts.
- Monitoring outbound links, grafana, prometheus targets function properly - ie, no dead links.

Downstream Cluster

- Provisioned downstream k8s v1.28 cluster.
- Installed rancher-monitoring:104.0.0-rc1+up45.31.1
- Configured monitoring and alerting to monitor and send alerts on telegram
- Upgraded downstream cluster to k8s v1.29
- Verified configured monitoring still sending alerts.
- Monitoring passed p0 test cases.
- Monitoring outbound links, grafana, prometheus targets function properly - ie, no dead links
- Chart annotations are correct.
- Uninstall Monitoring and Alert app successfully on downstream cluster and deleted respective namespaces.
- Fresh install monitoring on K8s v1.29
- Configured monitoring and alerting to monitor and send alerts on telegram on fresh installation of app.
- Verified configured monitoring still sending alerts.
- Monitoring outbound links, grafana, prometheus targets function properly - ie, no dead links.
