### ISSUE TITLE
k8s 1.29 support for rancher-alerting-drivers

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#45355]
Add k8s 1.29 support for rancher-alerting-drivers

**Comment by pankajsqe** [comment]
User is not able to find rancher-alerts chart on marketplace to install on v2.9.0-alpha5 (Local : v1.29.4+rke2r1, Downstream AKS : v1.29.4)



![Image](https://github.com/rancher/rancher/assets/149133120/87d701e4-7eb4-4f50-a31f-d512f1633fcf)
![Image](https://github.com/rancher/rancher/assets/149133120/17e131b6-6c64-484c-8b3b-6d7bb505c435)



https://github.com/rancher/rancher/assets/149133120/1da4c218-c0d7-4bf6-9500-64d8ca342749

**Comment by pankajsqe** [comment]
Pass Verified in rancher v2.9-head Below are the test cases. 

Local Cluster

- Provisioned Rancher with local k8s v1.28.7+rke2r1 cluster.
- Installed rancher-monitoring:104.0.0-rc1+up45.31.1
- Installed rancher-alerting-drivers:104.0.0-rc1
- Configured monitoring and alerting to monitor and send alerts on telegram
- Upgraded Local cluster to k8s v1.29.4+rke2r1
- Verified configured monitoring still sending alerts.
- Monitoring passed p0 test cases.
- Monitoring outbound links, grafana, prometheus targets function properly - ie, no dead links.
- Chart annotations are correct.
- Uninstall Monitoring and Alert app successfully on local cluster and deleted respective namespaces.
- Fresh install monitoring and alert app on v1.29.4+rke2r1
- Configured monitoring and alerting to monitor and send alerts on telegram on fresh installation of app.
- Verified configured monitoring still sending alerts.
- Monitoring outbound links, grafana, prometheus targets function properly - ie, no dead links. 

Downstream Cluster

- Provisioned downstream k8s 1.28 cluster.
- Installed rancher-monitoring:104.0.0-rc1+up45.31.1
- Installed rancher-alerting-drivers:104.0.0-rc1
- Configured monitoring and alerting to monitor and send alerts on telegram
- Upgraded downstream cluster to k8s v1.29
- Verified configured monitoring still sending alerts.
- Monitoring passed p0 test cases.
- Monitoring outbound links, grafana, prometheus targets function properly - ie, no dead links
- Chart annotations are correct.
- Uninstall Monitoring and Alert app successfully on downstream cluster and deleted respective namespaces.
- Fresh install monitoring and alert app on K8s v1.29
- Configured monitoring and alerting to monitor and send alerts on telegram on fresh installation of app.
- Verified configured monitoring still sending alerts.
- Monitoring outbound links, grafana, prometheus targets function properly - ie, no dead links.
