### ISSUE TITLE
Extend support for external LB label (io.rancher.service.external_lb_endpoint )

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#4535]
Rancher Version:V1.0.1

Docker Version: 1.11.0

Steps to Reproduce: Currently we can type the label names as user labels during service creation. But when we clone or upgrade the service, the labels are not carried over.

**Comment by tfiduccia** [comment]
Version - master 4/27
Verified fixed

**Comment by soumyalj** [comment]
When an upgrade is performed, the labels are carried over, but the values in upper case are changed to smaller case. On the UI it is still seen as caps, but when we do an inspect on the lauch config parameters sent for an upgrade request, it shows as smaller case. 

<img width="608" alt="screen shot 2016-04-29 at 4 46 33 pm" src="https://cloud.githubusercontent.com/assets/18536626/14932573/6eb6e14e-0e2d-11e6-9369-b7a3aabcb1a2.png">

**Comment by soumyalj** [comment]
Also, external Lb label should be easily visible in the UI  for users. Currently users have to manually type the label name while creating the service.

**Comment by vincent99** [comment]
System label values were at one time defined to be case-insensitive, and then therefore lowercased by the UI.. removed, but you will need to re-check all the system labels (particularly scheduling).

A separate enhancement for shortcuts to adding system labels is fine, but this is not related to this issue.. and this label would be one of the more obscure ones that is only relevant to a small percentage of users.

**Comment by deniseschannon** [comment]
@soumyalj I've created https://github.com/rancher/rancher/issues/4775 which you should use to confirm that scheduling still works with variations of cases for labels.

**Comment by soumyalj** [comment]
Verified in v1.1.0-dev2-rc4. The labels are carried over correctly.
