### ISSUE TITLE
Validate registry credentials before they can be saved.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#4536]
Rancher Version:v1.0.1

Steps to Reproduce: 

From Infrastructure/Registries - Add custom registry with invalid values ( Address/email/username/password). 

Registry entry will get added successfully and in in "active" state.
When service get created using an image from this registry , image pull will fails.
This behavior is not desirable.

We should not allow for registry entries with invalid values to get saved. Registry entries should be saved only after confirming that the docker login to the custom registry with the provided credentials succeeds.

**Comment by vincent99** [comment]
https://github.com/rancher/rancher/issues/300
