### ISSUE TITLE
Migrate rancher/kontainer-driver-metadata from Drone to GH Actions

### ISSUE THREAD

**Issue by mitulshah-suse** [rancher/rancher#45375]
Migrate rancher/kontainer-driver-metadata from Drone to GH Actions.

Need to update the below branches.
- dev-v2.7
- dev-v2.8
- dev-v2.9

SURE-7992

**Comment by snasovich** [comment]
@mitulshah-suse , I believe this should be unblocked now. If not, please let me know.

**Comment by snasovich** [comment]
This is now done and there is nothing to QA. Closing. Also, clearing the milestone as it doesn't actually affect any Rancher release itself.
