### ISSUE TITLE
Migrate rancher/rke from Drone to GH Actions

### ISSUE THREAD

**Issue by mitulshah-suse** [rancher/rancher#45377]
Migrate rancher/rke from Drone to GH Actions

Need to update the below branches.
- release/v1.6
- release/v1.5
- release/v1.4

SURE-7999

**Comment by snasovich** [comment]
@mitulshah-suse , we should be unblocked on this issue now.

**Comment by mitulshah-suse** [comment]
Closing the issue since migration is done and there is no QA work needed on it.
