### ISSUE TITLE
[BUG] Windows system-agent-install script needlessly reinstalls RKE2

### ISSUE THREAD

**Issue by HarrisonWAffel** [rancher/rancher#45385]
**Rancher Server Setup**
- Rancher version:
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version:
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:
  
**Describe the bug**

Each time that a Windows node boots, Rancher will deliver a plan to execute the system-agent-install `run.ps1` script. This script will install, configure, or upgrade rke2 onto the Windows node, based off of several different environment variables. Currently, this script is _always_ stopping and reinstalling RKE2, even if we are not upgrading the version. 

This means that, on a reboot, rke2 will automatically start only to be stopped a few seconds later. In some cases this can result in a plan failure, as the system-agent may attempt to stop the rke2 service while it is starting but before it enters a stoppable state. This often results in the `Stop-Service` command failing. Similar install behavior is seen in the linux variant of the system-agent-install script, however this approach is not a problem due to differences in how each OS handles updating files which are currently running. 

We should improve the install script so that it only stops and reinstalls rke2 when we are upgrading versions. This will help make the script less likely to fail and reduce the amount of times we are starting/stopping/restarting the rke2 service on initial start up of Windows. This will also allow us to properly leverage the `RESTART_STAMP` environment variable, ensuring that rke2 is only restarted by the system-agent when environment variables or other configurations have changed. 

**To Reproduce**
The plan failure described is more easily reproducible in the scope of https://github.com/rancher/rancher/issues/42458

Generally this can be seen when provisioning a windows cluster in any environment and restarting the node. Viewing the rancher-wins logs will show the log message `Waiting for RKE2 agent service to stop`, indicating that the script is in the process of stopping and reinstalling rke2. 

**Result**
In some cases, the rancher-wins will fail to execute the plan and report that the `stop-service` command failed to properly execute.

**Expected Result**
The rke2 service is only stopped when it is being upgraded 

**Screenshots**

**Additional context**

Relates to https://github.com/rancher/rancher/issues/42458

**Comment by HarrisonWAffel** [comment]
As this relates to the RFE described in https://github.com/rancher/rancher/issues/42458, which is in review, this issue will also target the same milestone as https://github.com/rancher/rancher/issues/42458, v2.10

**Comment by HarrisonWAffel** [comment]
Can be tested using the data.json from this KDM PR https://github.com/rancher/kontainer-driver-metadata/pull/1544

URL: https://raw.githubusercontent.com/rafaelbreno/kontainer-driver-metadata/refs/heads/october_rke2_10_patch/data/data.json

**Comment by markusewalker** [comment]
Validated this against `head` https://github.com/rancher/rancher/commit/fe49760f4e50d0b78ca0102c8475bc93361336b0. Results and more details have been recorded in Qase test run /RM 2663.

**ENVIRONMENT DETAILS**
- Rancher install: Helm
- Rancher version: `head` https://github.com/rancher/rancher/commit/fe49760f4e50d0b78ca0102c8475bc93361336b0

**TEST RESULTS**
|#|Scenario|Result|
|---|---|---|
|1|Validate rancher-wins output shows RKE2 service doesn't restart when cluster does not upgrade|:white_check_mark:|
|2|Validate rancher-wins output shows RKE2 service does restart when the cluster does upgrade|:white_check_mark:|
|3|Validate rancher-wins output shows RKE2 service does restart when the cluster configuration is updated|:white_check_mark:|
|4|Validate rancher-wins output shows RKE2 service does restart when the Rancher is upgraded|:white_check_mark:|
