### ISSUE TITLE
Adding host with reused IP address can fail, causing IPsec failures

### ISSUE THREAD

**Issue by guruvan** [rancher/rancher#4538]
Rancher Version:
1.0 1.0.1
Docker Version:
1.10.1 1.10.3
OS: 
RancherOS

Steps to Reproduce: Add & remove host, restart host with fresh OS, reuse same IP address - perhaps multiple times, potentially requires additional failures to reproduce(?)

Results: Database entries are not marked `removed` or `purged` 
**This causes inter-container Rancher-net IPsec failures** SPIs are not setup correctly and connectivity is not possible to restore to any host using the same IP address 

Expected: Start, Stop, Deactivate, Remove, Purge should correctly purge the host form the rancher db. New host install should correctly connect to the IPsec overlay. 

It would be most helpful to have some instruction or other method to manually purge data from the database. In this case I have a well-known IP address that we need to be able to reuse. This issue was apparently caused through start failures (i.e. Vagrantfile errors), likely multiple times. The end result is the database effectively corrupt, and this IP cannot be used. (I have replaced the host multiple times since discovering the nature of IPsec failures)

**Comment by guruvan** [comment]
Further investigation shows that this actually may **not** be the case
  - not directly able to duplicate, 
  - errors seemingly not DB-related occur

I currently see an issue with a host that's restarted, but has never been recreated in the DB.
  - Host runs cjdns for full inter-DataCenter connectivity ipv6 overlay w/ ipv4 tunnels
  - created host, host behind NAT, and rancher server behind another NAT on another network
 - used public outside IP on host as CATTLE_AGENT_IP
 - no IPsec connectivity, "unknown SPI" errors in rancher-net.log
 - removed rancher-agent containers, 
**The machine providing NAT in front of rancher-server was ALSO not working with the IPsec network, rancher-agent containers were removed from this host, but IPtables hadn't been flushed. Presuming that the IPsec issue was incorrect outside-inside<->inside-outside pairs for policy setup - errors involving the NAT machine on the rancher-server side external IP were seen in Host's rancher-net.log

 - CHANGED host CATTLE_AGENT_IP to non-natted cjdns ipv4 tunnel address
 - ipsec connectivity worked immediately

 - Host had unplanned reboot
 - iptables rules were not saved, and required recreation (alas, from memory)
 - cannot restore IPsec connections

- rancher-agent has been restarted multiple times on the host
- rancher-agent + state containers removed and restarted 

only a single entry for this host exists in the DB, so it appears unlikely that rancher is "confused" in this way. This issue appears it likely to be a more common ipsec issue of creating tunnel policies that traverse NAT points. 


Host
192.168.55.2 cjdns ipv4 tunnel / CATTLE_AGENT_IP
192.168.45.2 internal IP external interface
1.1.1.1 (public NATted address, on router, forwarded ports)
NAT - microtik router

Internet / cjdns overlay / cjdns tunnel

NAT - AWS instance w/ RancherOS
cjdns tunnel termination
2.2.2.2 public IP
10.0.5.2 private/internal ip
10.1.1.2 cjdns ipv4 tunnel ip

Rancher-server
10.0.3.2 private ip only

**Comment by deniseschannon** [comment]
@guruvan Are you still facing these issues and do you have any reliable steps to be able to reproduce?

**Comment by deniseschannon** [comment]
@guruvan Please re-open if you are still facing these issues.
