### ISSUE TITLE
Remove cluster-agent replica count to be able to scale up/down 

### ISSUE THREAD

**Issue by thunko** [rancher/rancher#45387]
**Problem description:**
Rancher cluster agent specifications are created automatically by rancher server when downstream cluster is defined.
Currently it runs 2 replicas per cluster, hard coded here: https://github.com/rancher/rancher/blob/release/v2.9/pkg/systemtemplate/template.go#L117  
node affinity is configured to schedule pods on different nodes.

**Desired solution:**
Remove hardcoded replica count
If the hardcoded number of replicas is removed, we could for example, deploy an HPA and let it scale up/down depending on a certain threshold set.  

**Alternatives:**
Either what proposed above or have a feature to configure cluster-agent replicas on downstream clusters.

**Comment by TheBritz** [comment]
+1 To this
