### ISSUE TITLE
Re-deploy Kubernetes components again when the rancher/server failed.

### ISSUE THREAD

**Issue by g0194776** [rancher/rancher#4542]
Rancher Version: v1.0.1

Docker Version:v1.9.0+

OS: CentOS 7.0

Steps to Reproduce: 

1. Run up an rancher/server instance on the docker.
2. Select the Kubernetes stack.
3. Waiting until the rancher/server has finished setup those of components of Kubernetes in the targeted machine(VM).
4. Any other reasons occurs causing the rancher/server instance down.
5. Restarting the rancher/server docker instance and re-configures it with Kubernetes Stack(Because I dont know how to save configurations the rancher/server used in the docker instance).  

  6.Whatever there has any components of Kubernetes the rancher/server docker instance will deploys it again.

Results: 
There have more than one suites of Kubernetes components living in the same VM.

Expected:
Only one suite of components of Kubernetes SHOULD be deploying. The rancher/server instance SHOULD probe the environment conditions before doing sth.

**Comment by alena1108** [comment]
@soumyalj can we test this use case? I believe we did, but just to double check

**Comment by soumyalj** [comment]
Set up a cattle and Kubernetes environment with version 1.1.1.  Kubernetes environment had few pods/service/rcs. Performed an upgrade from v1.1.1 to v1.2.0-pre1-rc3. Upgrade was successful.  Kubernetes stack came up successfully. Pods/services/rcs in Kubernetes were still active after upgrade.
