### ISSUE TITLE
ARM64 integration testing in backup-restore-operator

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#45420]
Most of backup-restore was migrated to GHA with integration testing in this PR
https://github.com/rancher/backup-restore-operator/pull/455

But testing for ARM64 support was not included. This ticket will fix that.

**Comment by mallardduck** [comment]
We had a quick call on this and I want to summarize some things we found for future reference. Long story short, GHA added arm runners but only to orgs (so unlikely we can test on our forks).

The arm based runners are accessible via Rancher repos via their `runs-on` names, and examples listing the names can be found here: https://github.com/rancher/eio-test/actions/runs/8795155580/workflow

**Comment by mallardduck** [comment]
WIP PR here: https://github.com/rancher/backup-restore-operator/pull/555

**Comment by dharmit** [comment]
@mallardduck @MKlimuszka should we keep this open or close it since https://github.com/rancher/backup-restore-operator/pull/555 is merged? Maybe we want to keep it around for backport purpose?

**Comment by mallardduck** [comment]
My vote would be keep it open until backports are sorted out. Once we merge in https://github.com/rancher/backup-restore-operator/pull/566 manual backport PRs can be created for our other active branches (Rancher 2.8+ / BRO 4/5).

**Comment by mallardduck** [comment]
Backport PRs are in review now: 
https://github.com/rancher/backup-restore-operator/pull/569
https://github.com/rancher/backup-restore-operator/pull/570
https://github.com/rancher/backup-restore-operator/pull/571

**Comment by mallardduck** [comment]
All merged up! Setting this solved
