### ISSUE TITLE
Add support for docker 26.1.x

### ISSUE THREAD

**Issue by mitulshah-suse** [rancher/rancher#45439]
Add support for docker 26.1.x.
Release notes: https://docs.docker.com/engine/release-notes/26.1/

ref issue: https://github.com/rancher/rancher/issues/45013

Docker versions added: 26.1.0 and 26.1.1

**Comment by vivek-shilimkar** [comment]
Validated on rancher v2.9-head

Docker 26.1.0 and 26.1.1 validation completed on below OSes with node driver and custom clusters:
- RHEL 9.3 and 8.9
- OL 9.3 and 8.9
- Rocky  9.3 and 8.9
- CentOS 7.9
- Ubuntu 22.04

**Comment by vivek-shilimkar** [comment]
Validated on rancher v2.9-head
Docker 26.1.0 and 26.1.1 validation completed on below OSes with node driver and custom clusters:
- RHEL 9.2, 9.1, 9.0, 8.8, 8.7 and 7.9
- OL 9.2, 9.1, 8.8 and 8.7
- Rocky  9.2, 9.1, 8.8 and 8.7
- Ubuntu 24.04

**Comment by kinarashah** [comment]
`26.1.0` and `26.1.1` released 

- https://releases.rancher.com/install-docker/26.1.0.sh 
- https://releases.rancher.com/install-docker/26.1.1.sh

https://releases.rancher.com/install-docker/26.1.sh points to `26.1.1`

**Comment by mitulshah-suse** [comment]
Moving back to raise the rancher PRs to update the default versions, since testing and release are compeleted.

**Comment by chiukapoor** [comment]
Hello @snasovich & @kinarashah, I was wondering if we may point to [EngineInstallURL](https://github.com/rancher/rancher/blob/49a10b3070b3d25b2990ea9fac01b876c32f92bd/pkg/settings/setting.go#L66) from `setting.go` for install-docker script URL in [controller.go](https://github.com/rancher/rancher/blob/49a10b3070b3d25b2990ea9fac01b876c32f92bd/pkg/controllers/management/node/controller.go#L48)?

https://github.com/rancher/rancher/blob/49a10b3070b3d25b2990ea9fac01b876c32f92bd/pkg/controllers/management/node/controller.go#L48

https://github.com/rancher/rancher/blob/49a10b3070b3d25b2990ea9fac01b876c32f92bd/pkg/settings/setting.go#L66

**Comment by chiukapoor** [comment]
Created [issue](https://github.com/rancher/rancher/issues/45633) regarding the above query to unblock docker 26.1 support.

**Comment by vivek-shilimkar** [comment]
Tested on rancher v2.9-head(dcf32c2). The default version of the docker install script is as expected - https://releases.rancher.com/install-docker/26.1.sh. RKE1 node driver cluster provisioned also has a correct docker version installed.

Hence, closing the ticket.
