### ISSUE TITLE
Add support for docker 26.0.2

### ISSUE THREAD

**Issue by mitulshah-suse** [rancher/rancher#45440]
The following docker versions are to be added:
v26.0.2

The same approach as https://github.com/rancher/rancher/issues/45291 is to be followed for implementation and testing.

**Comment by rishabhmsra** [comment]
Validated on rancher v2.9-head(7ee02ac)
Validated docker 26.0.2 install script by provisioning node driver as well as custom clusters using below OSes:

- Rocky 9.3, 8.9
- RHEL 9.3, 8.9
- OL 9.3, 8.9
- Ubuntu 24.04, 22.04
- CentOS 7.9

**Comment by kinarashah** [comment]
Released 
- https://releases.rancher.com/install-docker/26.0.2.sh  
- - https://releases.rancher.com/install-docker/26.0.sh points to `26.0.2`

**Comment by mitulshah-suse** [comment]
Closing the issue, since testing and release have been completed.
