### ISSUE TITLE
[BUG] Panic setting password to Azure AD (Entra ID) user

### ISSUE THREAD

**Issue by moio** [rancher/rancher#45451]
**Rancher Server Setup**
- Rancher version: 2.8.3
- Installation option (Docker install/Helm Chart): Helm Chart on AKS

**Information about the Cluster**
- Kubernetes version: AKS 1.27.7
- Cluster Type (Local/Downstream): Local

**User Information**
- What is the role of the user logged in? Admin

**Describe the bug**
Attempting to set a password for a user in the Azure AD authentication provider fails, a panic is produced in pod logs:

```

2024/05/13 12:15:57 [ERROR] Panic serving api request: 
goroutine 104951 [running]:
runtime/debug.Stack()
    /usr/lib64/go/1.21/src/runtime/debug/stack.go:24 +0x5e
github.com/rancher/norman/api.(*Server).ServeHTTP.func1()
    /go/pkg/mod/github.com/rancher/norman@v0.0.0-20240206180703-6eda4bc94b4c/api/server.go:175 +0x6d
panic({0x4150760?, 0xc0079a9350?})
    /usr/lib64/go/1.21/src/runtime/panic.go:914 +0x21f
github.com/rancher/rancher/pkg/auth/api/user.(*Handler).setPassword(0x7?, {0x4b0ef61?, 0x4?}, 0x0?, 0xc006c85560)
    /go/src/github.com/rancher/rancher/pkg/auth/api/user/user_actions.go:142 +0x4b9
github.com/rancher/rancher/pkg/auth/api/user.(*Handler).Actions(0x408ed00?, {0xc00afd9963?, 0x4b0f551?}, 0xc00226d0e0?, 0xc00456e450?)
    /go/src/github.com/rancher/rancher/pkg/auth/api/user/user_actions.go:48 +0x56
github.com/rancher/norman/api.handleAction(0xc006c85560?, 0xc006c85560?)
    /go/pkg/mod/github.com/rancher/norman@v0.0.0-20240206180703-6eda4bc94b4c/api/server.go:263 +0x77
github.com/rancher/norman/api.(*Server).handle(0xc000bc0c60, {0x55f4c80?, 0xc009e22220?}, 0xc003c5e9c0?)
```

**To Reproduce**
 * Follow https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/authentication-config/configure-azure-ad#1-register-rancher-with-azure to configure Azure AD authentication
   * for SUSE employees, use test credentials testuser1 from this table: [Azure AD#Users](https://confluence.suse.com/display/RANQA/Azure+AD#AzureAD-Users)
 * log in as a normal user
   * for SUSE employees, use test credentials testuser3 from this table: [Azure AD#Users](https://confluence.suse.com/display/RANQA/Azure+AD#AzureAD-Users)
 * log in as the admin user again
 * click menu -> Users & Authentication -> normal user name (testuser3) -> three dots -> Edit config -> add a new password, click on Save

**Result**

Nondescriptive error in the UI:
![image](https://github.com/rancher/rancher/assets/250541/55d3702c-06ce-4e96-ad14-2be280d2751a)

Panic above in logs.

**Expected Result**

Operation success

**Screenshots**
See above

**Comment by enrichman** [comment]
Hi @moio, I've managed to replicate the bug, and found the problem. The operation succeeded, and no panic is raised, but you will still be no able to login with the user. That password is the one used as a "local user", and because it's a user generated from the Azure AD login it will not have the `username` field set.

You can workaround this adding manually it in the user resource, but it's a kind of an hack.

If the expected behaviour is just to not panic/fail I would say that my fix is ok.

**Comment by samjustus** [comment]
since we are discouraging use of the local auth - especially when a provider is setup - we can limit the scope to just eliminating the panic

**Comment by enrichman** [comment]
I've added an error that will prevent the panic, and inform the user about this.

![image](https://github.com/user-attachments/assets/d2d1ac71-c0d6-4c49-9c89-ae0769629434)

If we want to go further we can disable the inputs in this case, as we do with the username. This would be a task for the UI team.

**Comment by enrichman** [comment]
# QA Testing

## Root cause

Trying to set a password for an external user will return a "generic" error, caused from a panic in the Rancher server.
Added Azure AD provider for authenticating with kubectl through the Rancher CLI.

## What was fixed, or what changes have occurred

The issue was fixed disabling the set of the password for non-local users, because we want to discourage the use of the local-auth.

## Areas or cases that should be tested

Rancher dashboard trying to set a password for an external user.

## What areas could experience regressions?

None

## Steps

- Enable an external provider
- Login
- Try to set a password for the new external user

With the fix the user should not be able to set the password, and a proper error will be shown.

**Comment by anupama2501** [comment]
Reproduced on 2.8.5
1. Installed rancher on 2.8.5
2. Configured azure AD auth provider. 
3. Logged in as a user from the auth provider.
4. As an admin user, tried to reset the password for the user.
5. Noticed panic in rancher logs:
```
	/go/src/github.com/rancher/rancher/pkg/api/steve/aggregation/aggregation.go:52 +0x4f
net/http.HandlerFunc.ServeHTTP(0xc006857000?, {0x560a108?, 0xc00658c4b0?}, 0x0?)
	/usr/lib64/go/1.21/src/net/http/server.go:2136 +0x29
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0019d0300, {0x560a108, 0xc00658c4b0}, 0xc006856f00)
	/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1c5
github.com/rancher/rancher/pkg/api/steve/proxy.NewProxyMiddleware.func1.1({0x560a108?, 0xc00658c4b0?}, 0xc00283b080?)
	/go/src/github.com/rancher/rancher/pkg/api/steve/proxy/proxy.go:80 +0x55
net/http.HandlerFunc.ServeHTTP(0x3951085?, {0x560a108?, 0xc00658c4b0?}, 0xc00b3990d0?)
	/usr/lib64/go/1.21/src/net/http/server.go:2136 +0x29
github.com/rancher/rancher/pkg/api/steve/proxy.RewriteLocalCluster.func1({0x560a108, 0xc00658c4b0}, 0xc006856f00)
	/go/src/github.com/rancher/rancher/pkg/api/steve/proxy/proxy.go:46 +0x16b
net/http.HandlerFunc.ServeHTTP(0xc000beda10?, {0x560a108?, 0xc00658c4b0?}, 0x4b22a92?)
	/usr/lib64/go/1.21/src/net/http/server.go:2136 +0x29
github.com/rancher/rancher/pkg/websocket.websocketHandler.ServeHTTP({{0x55db5a0?, 0xc00282dea8?}}, {0x560a108, 0xc00658c4b0}, 0xc006856f00)
	/go/src/github.com/rancher/rancher/pkg/websocket/handler.go:35 +0xa3
github.com/rancher/apiserver/pkg/middleware.NoCache.func1({0x560a108, 0xc00658c4b0}, 0xc00f3671e0?)
	/go/pkg/mod/github.com/rancher/apiserver@v0.0.0-20240207153744-69b3c2b56f3f/pkg/middleware/cache.go:33 +0xf0
net/http.HandlerFunc.ServeHTTP(0x461a580?, {0x560a108?, 0xc00658c4b0?}, 0x16?)
	/usr/lib64/go/1.21/src/net/http/server.go:2136 +0x29
github.com/rancher/apiserver/pkg/middleware.ContentTypeOptions.func1({0x560a108, 0xc00658c4b0}, 0xc00f3671e0?)
	/go/pkg/mod/github.com/rancher/apiserver@v0.0.0-20240207153744-69b3c2b56f3f/pkg/middleware/cache.go:47 +0xf6
net/http.HandlerFunc.ServeHTTP(0x461a580?, {0x560a108?, 0xc00658c4b0?}, 0x11?)
	/usr/lib64/go/1.21/src/net/http/server.go:2136 +0x29
github.com/rancher/rancher/pkg/auth.SetXAPICattleAuthHeader.func1({0x560a108, 0xc00658c4b0}, 0xc006856f00)
	/go/src/github.com/rancher/rancher/pkg/auth/server.go:180 +0x19b
net/http.HandlerFunc.ServeHTTP(0xc000fb52d0?, {0x560a108?, 0xc00658c4b0?}, 0x8449ba0?)
	/usr/lib64/go/1.21/src/net/http/server.go:2136 +0x29
github.com/rancher/rancher/pkg/auth/audit.auditHandler.ServeHTTP({{0x55db5a0, 0xc00282def0}, 0xc000fb52d0, 0xc001281ea0, 0xc001d0fbf0, 0xc00170d8c0}, {0x5604858?, 0xc0081540e0}, 0xc006856e00)
	/go/src/github.com/rancher/rancher/pkg/auth/audit/filter.go:83 +0x275
github.com/rancher/rancher/pkg/auth.NewServer.ToAuthMiddleware.ToMiddleware.func2.1({0x5604858, 0xc0081540e0}, 0xc006856d00?)
	/go/pkg/mod/github.com/rancher/steve@v0.0.0-20240411162517-a80bf83f76b4/pkg/auth/filter.go:172 +0x24f
net/http.HandlerFunc.ServeHTTP(0x0?, {0x5604858?, 0xc0081540e0?}, 0x4e1400?)
	/usr/lib64/go/1.21/src/net/http/server.go:2136 +0x29
github.com/rancher/dynamiclistener/server.getTLSListener.wrapHandler.func1({0x5604858, 0xc0081540e0}, 0xc000bed960?)
	/go/pkg/mod/github.com/rancher/dynamiclistener@v0.4.0/server/server.go:199 +0x68
net/http.HandlerFunc.ServeHTTP(0x716a25?, {0x5604858?, 0xc0081540e0?}, 0x7169b9?)
	/usr/lib64/go/1.21/src/net/http/server.go:2136 +0x29
github.com/rancher/dynamiclistener/server.ListenAndServe.HTTPRedirect.func7({0x5604858, 0xc0081540e0}, 0xc006856d00)
	/go/pkg/mod/github.com/rancher/dynamiclistener@v0.4.0/redirect.go:20 +0x1bc
net/http.HandlerFunc.ServeHTTP(0x410bc5?, {0x5604858?, 0xc0081540e0?}, 0xc008154001?)
	/usr/lib64/go/1.21/src/net/http/server.go:2136 +0x29
net/http.serverHandler.ServeHTTP({0x55ec180?}, {0x5604858?, 0xc0081540e0?}, 0x6?)
	/usr/lib64/go/1.21/src/net/http/server.go:2938 +0x8e
net/http.(*conn).serve(0xc006622f30, {0x561cbc8, 0xc00141bf20})
	/usr/lib64/go/1.21/src/net/http/server.go:2009 +0x5f4
created by net/http.(*Server).Serve in goroutine 5829
	/usr/lib64/go/1.21/src/net/http/server.go:3086 +0x5cb
```

**Comment by anupama2501** [comment]
Verified on v2.9-head `8bd2e564f`

**SetPassword:**
1. Enabled openldap auth
2. Logged in as a few users from auth provider.
3. As an admin, updated the password for a user from auth provider.
4. Verified the following error is displayed: `Cannot set password of non-local user`

**Refreshed provider access:**

1. Verified no errors while refreshing the provider accesss

**ChangePassword:**
1. From kubectl edit user <userID>, updated mustChangePassword: true
2. Logged in as user from auth provider.
3. Login returned successful but the user could not actually login to rancher >> this is also the same behavior in 2.8.5 https://github.com/rancher/rancher/issues/46558



**Terraform:**

1. Imported the user via terraform
2. Updated the password 
3. Verified the following error is displayed: ` Body: [baseType=error, code=ServerError, message=Cannot set password of non-local user]`

**Upgrade rancher from 2.8.5 >> 2.9-head**
1. After the repro steps from the above comment, upgraded rancher server to v2.9-head
2. Verified changing password doesnt cause a panic.
3. Verified error is displayed to the users.

**Regression Checks:**

1. Local user mustChangePassword: Successful
2. Set new password: Successful
3. standard user update password: Expected fail 
4. Updated the username on the auth provider user by running k edit user <uid>
     - Updated username: uid3
     - Verified user is switched to user local principalID
     - Updated the password and verified update works.

**Comment by anupama2501** [comment]
Re opening as the validations were done on 2.9-head. waiting for a `main` image.
