### ISSUE TITLE
k8s 1.29 support for aks-operator

### ISSUE THREAD

**Issue by Sahota1225** [rancher/rancher#45467]
Add k8s 1.29 support for aks-operator

**Comment by kkaempf** [comment]
Kubewarden tested with  v1.29.5-k3s1 and v1.30.1-k3s1 - jfyi

**Comment by cpinjani** [comment]
Verified on `v2.9-4ac81b66b0f971548be78f2d1c72ecb906171a0b-head, aks-operator:v1.9.0-rc.6` ✅
Chart install/upgrade and P0 scenarios with k8s v1.29 passed.
