### ISSUE TITLE
k8s 1.29 support for system-upgrade-controller 

### ISSUE THREAD

**Issue by Sahota1225** [rancher/rancher#45462]
Add k8s 1.29 support for  system-upgrade-controller

**Comment by mitulshah-suse** [comment]
This one is being handled as part of https://github.com/rancher/rancher/issues/44922

**Comment by rishabhmsra** [comment]
Validated this against v2.9-head

**ENVIRONMENT DETAILS**
- Rancher install: Docker
- Rancher version: v2.9-head

**TEST RESULT**
|#|Scenario|Test Case|Result
|---|---|---|---|
|1|Validate `system-upgrade-controller` version in freshly-installed RKE2 v1.29 cluster|Provision downstream RKE2 v1.29 cluster and validate the `system-upgrade-controller` chart version|:white_check_mark:|
|2|Validate `system-upgrade-controller` version in upgraded RKE2 v1.29 cluster|Provision downstream RKE2 v1.28 cluster, upgrade to v1.29 cluster and validate the `system-upgrade-controller` chart version|:white_check_mark:|
|3|Validate `system-upgrade-controller` version in an imported RKE2 v1.29 cluster|Provision a standalone RKE2 v1.28 cluster, import it into Rancher, upgrade to v1.29 and validate the `system-upgrade-controller` deployment version|:white_check_mark:|
|4|Validate `system-upgrade-controller` version in K3s cluster after upgrading Rancher|Setup Rancher v2.8, provision a downstream K3s v1.28 cluster, upgrade Rancher, upgrade to v1.29 and validate the `system-upgrade-controller` chart version|:white_check_mark:|
|5|Validate `system-upgrade-controller` version in an imported RKE2 cluster after upgrading Rancher|Provision a standalone RKE2 v1.28 cluster, setup Rancher v2.8, import the cluster into Rancher, upgrade Rancher, upgrade cluster to v1.29 and validate the `system-upgrade-controller` deployment version|:white_check_mark:|
