### ISSUE TITLE
k8s 1.29 support for Harvester-csi-driver

### ISSUE THREAD

**Issue by Sahota1225** [rancher/rancher#45471]
Add k8s 1.29 support for Harvester-csi-driver

**Comment by Vicente-Cheng** [comment]
Hi @Sahota1225, v1.29 support is already done on the PR https://github.com/rancher/charts/pull/3301

Thanks!

**Comment by TachunLin** [comment]
Verified **fixed** on Rancher `v2.9.0-alpha5` with Harvester `v1.3.1` for K8s `v1.29.5`.
Close this issue.

### Result

<details><summary>$\color{green}{\textsf{PASS}}$   Can provision v1.29.5 RKE2 cluster well $~~$</summary>

  ![image](https://github.com/harvester/tests/assets/29251855/195dffd7-42cb-4fa1-b823-0d60dfd9e08f)


</details>

<details><summary>$\color{green}{\textsf{PASS}}$   default csi driver version is <strong>0.1.1700</strong> $~~$</summary>

  ![image](https://github.com/harvester/tests/assets/29251855/13695325-1086-4e2d-9cf4-8302243b9511)


</details>

<details><summary>$\color{green}{\textsf{PASS}}$  Check the default storage class set to `Harvester` $~~$</summary>

  ![image](https://github.com/harvester/tests/assets/29251855/a649599d-91ea-43dc-b5bb-de6ab0c8114b)

</details>


<details><summary>$\color{green}{\textsf{PASS}}$  Can create nginx application pvc correctly $~~$</summary>

  ![image](https://github.com/harvester/tests/assets/29251855/bef57e78-6848-4e34-a004-30e4adad19f1)

</details>

<details><summary>$\color{green}{\textsf{PASS}}$  Can create nginx application pv $~~$</summary>

  ![image](https://github.com/harvester/tests/assets/29251855/f313c72f-e953-4065-8b61-cbf5a3408f5e)
  
</details>

<details><summary>$\color{green}{\textsf{PASS}}$  nginx pvc created one Harvester $~~$</summary>

  ![image](https://github.com/harvester/tests/assets/29251855/5d339672-9515-4309-bdef-e7c4aadc779c)
  
</details>

### Test Information
* Test Environment: Single nodes harvester on local kvm machine
* Harvester version: v1.3.1
* Rancher version: v2.9.0-alpha5
* K8s version: v1.29.5

### Verify Steps
<details><summary>Necessary checks for cloud provider and csi driver</summary>

1. Import Harvester v1.3.1 to Rancher v2.9.0-alpha5
2. Provision the `v1.29.5` RKE2 guest cluster from Rancher
3. Check the RKE2 cluster can provisioned and running well
4. Access the RKE2 clsuter
5. Check the bundled Harvester cloud provider version in the applications
6. Check the bundled Harvester csi driver version in the applications
7. Create a nginx deployment and set Harvester storage type pvc 
8. Check the pvc and pv can created well 
9. Access Harvester volumes page 
10. Check the corresponding volume also created 


</details>
