### ISSUE TITLE
k8s 1.29 support for harvester-cloud-provider

### ISSUE THREAD

**Issue by Sahota1225** [rancher/rancher#45470]
Add k8s 1.29 support for  harvester-cloud-provider

**Comment by FrankYang0529** [comment]
Hi @Sahota1225, v1.29 support is already done on the PR https://github.com/rancher/charts/pull/3928.

Thanks.

**Comment by TachunLin** [comment]
Tested on the Rancher `v2.9.0-alpha4` with Harvester `v1.3.1` integrated.

* After provision the **v1.29.5** RKE2 cluster 
![image](https://github.com/rancher/rancher/assets/29251855/57977ae8-e32c-44c8-9a9f-fc63c2423852)

* We found the default cloud-provider version is **0.2.300**
![image](https://github.com/rancher/rancher/assets/29251855/5908ce46-fd5a-4706-80aa-f3dde09ceaa0)

@FrankYang0529, 
According to the related PR https://github.com/rancher/charts/pull/3928.
I think the default cloud provider version suppose to be `0.2.4`, not sure if my understanding is correct

**Comment by FrankYang0529** [comment]
Hi @TachunLin, thanks for the testing. We found that v1.29.5+rke2r1 still uses 0.2.300. We need to wait next release for v1.29.6+rke2r1. It will be 0.2.400.

v1.29.5+rke2r1: https://github.com/rancher/rke2/blob/v1.29.5%2Brke2r1/charts/chart_versions.yaml
v1.29.6-rc6+rke2r1: https://github.com/rancher/rke2/blob/v1.29.6-rc6%2Brke2r1/charts/chart_versions.yaml

Also thanks @Vicente-Cheng for investigation.

**Comment by TachunLin** [comment]
Verified **fixed** on Rancher `v2.9.0-alpha5` with Harvester `v1.3.1` for K8s `v1.29.5`.
Close this issue.

### Result

<details><summary>$\color{green}{\textsf{PASS}}$   Can provision v1.29.5 RKE2 cluster well $~~$</summary>

  ![image](https://github.com/harvester/tests/assets/29251855/195dffd7-42cb-4fa1-b823-0d60dfd9e08f)


</details>

<details><summary>$\color{green}{\textsf{PASS}}$  Check the default cloud provider version is <strong>0.2.3</strong>  $~~$</summary>

  ![image](https://github.com/harvester/tests/assets/29251855/281d5886-822d-4c1c-9ec4-4d90e36bba31)


</details>

<details><summary>$\color{green}{\textsf{PASS}}$  Can create dhcp loadbalancer and route correctly $~~$</summary>

  ![image](https://github.com/harvester/tests/assets/29251855/dde49bb8-3fe4-4d8b-bc67-818c240b4057)

</details>


<details><summary>$\color{green}{\textsf{PASS}}$  Can create pool loadbalancer and route correctly $~~$</summary>

  ![image](https://github.com/harvester/tests/assets/29251855/ff4c907d-1e6a-4c71-9b24-e52ba201a60f)


</details>




### Test Information
* Test Environment: Single nodes harvester on local kvm machine
* Harvester version: v1.3.1
* Rancher version: v2.9.0-alpha5
* K8s version: v1.29.5

### Verify Steps
<details><summary>Necessary checks for cloud provider and csi driver</summary>

1. Import Harvester v1.3.1 to Rancher v2.9.0-alpha5
2. Provision the `v1.29.5` RKE2 guest cluster from Rancher
3. Check the RKE2 cluster can provisioned and running well
4. Access the RKE2 clsuter
5. Check the bundled Harvester cloud provider version in the applications
6. Check the bundled Harvester csi driver version in the applications
7. Create a nginx deployment and set Harvester storage type pvc 
8. Check the pvc and pv can created well 
9. Access Harvester volumes page 
10. Check the corresponding volume also created 
11. Create a dhcp type load balancer
12. Check the route connectivity to the dhcp loadbalancer
13. Access Harvester from Rancher virtualization management page 
14. Create an ip pool and set to all permission
15. Create a pool type load balancer
16. Check the route connectivity to the dhcp loadbalancer

</details>
