### ISSUE TITLE
k8s 1.29 support for KubeWarden

### ISSUE THREAD

**Issue by Sahota1225** [rancher/rancher#45474]
Add k8s 1.29 support for KubeWarden

**Comment by flavio** [comment]
Nothing special should be done inside of Kubewarden, everything works fine on top of 1.29 and even 1.30. However, assigning @kravciak to this issue

**Comment by kravciak** [comment]
E2E tests on `v1.29.5-k3s1` and `v1.30.1-k3s1` passed, closing.
