### ISSUE TITLE
k8s 1.29 support for Longhorn

### ISSUE THREAD

**Issue by Sahota1225** [rancher/rancher#45472]
Add k8s 1.29 support for Longhorn

**Comment by PhanLe1010** [comment]
Longhorn doesn't use deprecated resources at https://kubernetes.io/docs/reference/using-api/deprecation-guide/#flowcontrol-resources-v129 so it should work on Kubernetes 1.30 by default 

Can QA help to verify @yangchiu @roger-ryao ?

**Comment by roger-ryao** [comment]
> Longhorn doesn't use deprecated resources at https://kubernetes.io/docs/reference/using-api/deprecation-guide/#flowcontrol-resources-v129 so it should work on Kubernetes v1.29/v1.30 by default
> 
> Can QA help to verify @yangchiu @roger-ryao ?

Hi @PhanLe1010 
     Our master-head regression has been updated to k8s v1.30.0, and [the test results](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/951/) show no outstanding issues.

**Comment by roger-ryao** [comment]
**v1.29.5+rke2r1** `v1.6.x` coretest: https://ci.longhorn.io/job/public/job/v1.6.x/job/v1.6.x-longhorn-upgrade-tests-sles-arm64/164/

**v1.29.6+k3s1** `v1.6.2` coretest: https://ci.longhorn.io/job/public/job/master/job/ubuntu/job/arm64/job/longhorn-tests-ubuntu-arm64/492/

The `v1.6.x` core tests have passed.
