### ISSUE TITLE
Adding support for ServiceAccount in kubernetes

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#4548]
Rancher Version:
1.0.1
Docker Version:
1.10.1

Service Account admission controller is not enabled in kubernetes agent, so any pod will be created with no default service account, also creating a manual service account with secret doesn't seem to work:

```
$ cat sa.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default2
  namespace: default
secrets:
imagePullSecrets:
- name: myregistrykey
$ kubectl create -f sa.yaml 
serviceaccount "default2" created
$ kubectl get serviceaccount
NAME       SECRETS   AGE
default    0         36m
default2   0         7s
``` 
Where myregistrykey is the the docker hub registry credentials, then i tried to create a pod with this new service account, but the imagepullsecret was not added to the pod spec hence the pulling failed:

```
$ kubectl create -f pod-awesome.yaml 
pod "awesomeapp" created

$ kubectl get pods
NAME         READY     STATUS         RESTARTS   AGE
awesomeapp   0/1       ErrImagePull   0          5s

$ kubectl get pods/awesomeapp -o yaml
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: 2016-04-25T19:41:55Z
  labels:
    app: awesomeapp
  name: awesomeapp
  namespace: default
  resourceVersion: "568"
  selfLink: /api/v1/namespaces/default/pods/awesomeapp
  uid: c430b686-0b1d-11e6-83d5-029883ea05c4
spec:
  containers:
  - image: husseingalal/awesomeapp
    imagePullPolicy: Always
    name: awesomeapp
    ports:
    - containerPort: 80
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
  dnsPolicy: ClusterFirst
  nodeName: node-02
  restartPolicy: Always
  securityContext: {}
  serviceAccount: default2
  serviceAccountName: default2
  terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2016-04-25T19:41:55Z
    message: 'containers with unready status: [awesomeapp]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  containerStatuses:
  - image: husseingalal/awesomeapp
    imageID: ""
    lastState: {}
    name: awesomeapp
    ready: false
    restartCount: 0
    state:
      waiting:
        message: Back-off pulling image "husseingalal/awesomeapp"
        reason: ImagePullBackOff
  hostIP: 139.59.169.227
  phase: Pending
  podIP: 10.42.145.211
  startTime: 2016-04-25T19:41:55Z
```

**Comment by alena1108** [comment]
@prachidamle should be working now, right?

**Comment by prachidamle** [comment]
@galal-hussein the support for ServiceAccount AdmissionControl was enabled with the SSL kubernetes support . Can you test now against dev5 release?

**Comment by galal-hussein** [comment]
@prachidamle tested with dev5 and build-master:v0.20.0 and service accounts worked, however i have some troubles with generating manual API token, for example:

```
$ cat > /tmp/build-robot-secret.yaml <<EOF
apiVersion: v1
kind: Secret
metadata:
  name: build-robot-secret
  annotations: 
    kubernetes.io/service-account.name: build-robot
type: kubernetes.io/service-account-token
EOF
$ kubectl create -f /tmp/build-robot-secret.yaml
secrets/build-robot-secret
$ kubectl describe secrets/build-robot-secret
secrets "build-robot-secret" not found
```

**Comment by prachidamle** [comment]
@galal-hussein In above /tmp/build-robot-secret.yaml, you are creating a secret manually for an already existing service-account "build-robot".

Do you have this service-account "build-robot"?

If you don't see the account by doing the following, then the secret you are creating manually will not be linked to any account. 

> kubectl get serviceaccounts/build-robot -o yaml
Error from server: serviceaccounts "build-robot" not found
> kubectl get serviceaccounts
NAME      SECRETS   AGE
default   1         27m
>

If you dont have the "build-robot" account, then I dont think this is a valid test.

**Comment by galal-hussein** [comment]
@prachidamle My bad, i guess i forgot to add the service account before trying to assign token to it, the test worked after adding the build-robot service account.
