### ISSUE TITLE
[BUG] Cluster creation fails when vSphere or External Provider selected as Cloud Provider.

### ISSUE THREAD

**Issue by wiredcolony** [rancher/rancher#45505]
**Rancher Server Setup**

-Rancher version: 
 v2.8.3

 -Installation option (Docker install/Helm Chart):  
Helm Chart

- If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
v1.28.9 + k3s1

**Information about the Cluster**

- Kubernetes version:
v1.28.9+rke2r1

- Cluster Type :  Downstream
Infrastructure Provider:
vSphere 8.0u2 (vCenter) Infrastructure Provider = Rancher provisioning the nodes 
Ubuntu 22.04 Cloud (rancher pre-req provisioned) template

**User Information**
Admin

**Describe the bug**
When creating a cluster RKE2 and selecting vSphere (or external) as cloud provider, the cluster creation hangs at "waiting for agent to connect".  There are no problems with the VMs being created in vSphere.  

If I used "RKE2 embedded" as cloud provider, my cluster deploys as expected and works as expected.

**To Reproduce**
Follow steps https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-cloud-providers/configure-out-of-tree-vsphere.  For RKE2 choose "vSphere" or "External" as cloud provider.  Tested with 1 control-plane & worker (etcd) AND 3 control-plane & worker (etcd)

**Result**
All worker (3) and control-plans (3) VMs provisioned in vSphere.  RKE2 hangs after 5 minutes "Waiting for agent to connect".  0 of 6 Machines ready.  No running cluster, however VMs are running and accessible.

**Expected Result**
Cluster provisioned and ready.

**Additional context**
For the sake of moving forward, I would like to install the vSphere CPI and CSI manually, but I can't find any documentation on how to set the cloud provider AFTER cluster is created.  Since I can get a cluster up with cloud provider set to "RKE2 embedded" manually setting the cloud provider "after the fact" would be an acceptable workaround for me.  Thank you.

**Comment by Zappelphilipp** [comment]
What is your log output of:
```
systemctl status rancher-system-agent.service -n 50
journalctl -xeu rke2-server.service
```

**Comment by wiredcolony** [comment]
Hello, thanks for reaching out.  I am no longer able to reproduce this error.  I am not sure what has changed but everything is working as expected.
