### ISSUE TITLE
[SURE-8169] [BUG] high memory usage for the aks.(*aksOperatorController).onClusterChange

### ISSUE THREAD

**Issue by moio** [rancher/rancher#45509]
Internal reference: [SURE-8169](https://jira.suse.com/browse/SURE-8169)

**Rancher Server Setup**
- Rancher version:  SUSE Rancher 2.8.3
- Installation option (Docker install/Helm Chart): Helm on AKS

**Information about the Cluster**
- Kubernetes version: AKS 1.27
- Cluster Type (Local/Downstream): local

**Describe the bug**
Heap profile shows high memory usage on aks.(*aksOperatorController).onClusterChange.

![image](https://github.com/rancher/rancher/assets/250541/fd52b152-32fe-4039-97b5-b734395987f3)

(over 40% usage)

**To Reproduce**
TBD

**Result**

**Expected Result**
No significant memory usage from `aks.(*aksOperatorController).onClusterChange` in flame graphs.

**Comment by moio** [comment]
## Reproducer

### Prerequisites
- Rancher 2.8.3 with a publicly-accessible Internet address (eg. in AKS)
- an Azure account
- its subscription id
- a resource group in that Azure account

### Setup
- import any number of AKS clusters _as managed clusters_
	- add Azure cloud credentials to Rancher ([full docs](https://ranchermanager.docs.rancher.com/reference-guides/cluster-configuration/rancher-server-configuration/aks-cluster-configuration#cloud-credentials)). TL;DR:
      - run:
		```sh
		export SUBSCRIPTION_ID=XXXXXXXX-YYYY-ZZZZ-AAAA-BBBBBBBB
		export GROUP=st-rg
		
		az ad sp create-for-rbac \
		  --scope /subscriptions/$SUBSCRIPTION_ID/resourceGroups/$GROUP \
		  --role Contributor
		```
      - note the JSON output
      - go to ☰ -> Cluster Management -> Cloud Credentials -> Create -> Azure
	  - paste `appId` from the JSON output to Client ID, `password` to Secret, `$SUBSCRIPTION_ID` to Subscription ID
  - import the clusters as _as managed clusters_ ☰ -> Cluster Management -> Import Existing -> Azure AKS

### Test (of base version)

In one terminal with kubeconfig pointing to the upstream cluster run:

```sh
while true
do
	for cluster in $(kubectl get clusters.management.cattle.io --no-headers -o custom-columns=name:.metadata.name | grep -v local)
	do
	  kubectl patch clusters.management.cattle.io ${cluster} --type='json' -p='[{"op": "replace", "path": "/status/serviceAccountTokenSecret", "value":""}]'
  done
done
```

This script forces Rancher to continuously execute a core function of AKS cluster deployment (`generateAndSetServiceAccount`). This emulates the reported environment where clusters are frequently deployed and redeployed without the necessity of really redeploying AKS clusters, which is time intensive.


In another terminal with kubeconfig pointing to the upstream cluster run:
```sh
while true; do
	for pod in $(kubectl -n cattle-system get pods -l app=rancher --no-headers -o custom-columns=name:.metadata.name); do
		kubectl exec -n cattle-system ${pod} -c rancher -- curl -s http://localhost:6060/debug/pprof/heap -o heap
		kubectl cp -n cattle-system -c rancher ${pod}:heap ./heap

		go tool pprof -top --trim=false --show_from=generateAndSetServiceAccount ./heap | grep kubernetes.NewForConfig
	done
done
```

This script monitors one important source of memory usage by `generateAndSetServiceAccount` (`kubernetes.NewForConfig`).

**Expected output** is either:
1. a continuous stream of `ShowFrom expression matched no samples`, which means no memory was allocated or
2. `ShowFrom expression matched no samples` interleaved with lines like the following:
```
         0     0%  7.72%     7.51MB  5.79%  k8s.io/client-go/kubernetes.NewForConfig
```
The fourth number indicates memory usage. It should increase only slightly, if at all, after several minutes. Importantly, **stopping the first script in the other terminal should make usage go down to zero** in some minutes.

**Actual output** is:
`ShowFrom expression matched no samples` interleaved with lines like the following:
```
         0     0%  7.72%     7.51MB  5.79%  k8s.io/client-go/kubernetes.NewForConfig
```
The fourth number indicates memory usage. It is increasing, and **stopping the first script in the other terminal does not make usage go down to zero**.


### Test (of patched version)

When the expected behavior above is reproduced:
 - stop both scripts
 - swap the Rancher image with the patched one: `kubectl set image -n cattle-system deployment/rancher rancher=rancher/rancher:v2.8.3-debug-45509-1`
 - wait for clusters to come back as fully available in the UI, refresh the homepage to double check that is the case
 - re-run the scripts. Expected behavior should be observed

**Comment by gaktive** [comment]
No back port for 2.8.x at this time.

**Comment by MSpencer87** [comment]
Verified on Rancher v2.10.0-alpha3, rke2 v1.30.4+rke2r1

Continuous memory usage increase no longer present when importing Azure AKS clusters 

Steps to reproduce:
1. Bring up HA Rancher v2.8.3
2. Access Azure, create 3 AKS clusters
- Home -> Kubernetes services -> Create+ -> Kubernetes cluster
3. Create Cloud Credentials in Rancher for Azure
- To obtain credentials use:
```
az login

az ad sp create-for-rbac --role Contributor --scopes /subscriptions/{ID FROM LOGIN OUTPUT} --name {YOUR NAME}
```
`id` for Subscription ID, `appId` for Client ID and `password` for Client Secret

4. Import the AKS clusters into Rancher, wait for Active status
- Home -> Cluster Management -> Import Existing -> Azure AKS
5. Set kubeconfig for local/upstream cluster and execute patch script for deployment emulation
```
while true
do
	for cluster in $(kubectl get clusters.management.cattle.io --no-headers -o custom-columns=name:.metadata.name | grep -v local)
	do
	  kubectl patch clusters.management.cattle.io ${cluster} --type='json' -p='[{"op": "replace", "path": "/status/serviceAccountTokenSecret", "value":""}]'
  done
done
```
Downstream AKS clusters can be observed toggling between `Active` and `Unavailable` status as outputs aggregate:
```
cluster.management.cattle.io/c-xxxxx patched
cluster.management.cattle.io/c-xxxxx patched
cluster.management.cattle.io/c-xxxxx patched
cluster.management.cattle.io/c-xxxxx patched
```
6. In a separate terminal, set kubeconfig for local/upstream cluster and execute heap monitor script
```
while true; do
	for pod in $(kubectl -n cattle-system get pods -l app=rancher --no-headers -o custom-columns=name:.metadata.name); do
		kubectl exec -n cattle-system ${pod} -c rancher -- curl -s http://localhost:6060/debug/pprof/heap -o heap
		kubectl cp -n cattle-system -c rancher ${pod}:heap ./heap

		go tool pprof -top --trim=false --show_from=generateAndSetServiceAccount ./heap | grep kubernetes.NewForConfig
	done
done
```

Flame Graph can be view using pprof locally, ensure heap data is not loaded from `ShowFrom expression matched no samples` curl. 

Output indicates increasing memory usage over time while deployment emulation script is running, memory usage does not decrease when script is stopped and clusters hold Active status for several minutes

```
ShowFrom expression matched no samples
ShowFrom expression matched no samples
         0     0% 10.24%    27.54MB  8.28%  k8s.io/client-go/kubernetes.NewForConfig
ShowFrom expression matched no samples
ShowFrom expression matched no samples
         0     0% 10.49%    27.54MB  8.48%  k8s.io/client-go/kubernetes.NewForConfig
ShowFrom expression matched no samples
ShowFrom expression matched no samples
         0     0%  9.57%    28.04MB  7.77%  k8s.io/client-go/kubernetes.NewForConfig
ShowFrom expression matched no samples
ShowFrom expression matched no samples
         0     0% 11.16%    27.54MB  9.03%  k8s.io/client-go/kubernetes.NewForConfig
ShowFrom expression matched no samples
ShowFrom expression matched no samples
         0     0% 10.70%    28.04MB  8.68%  k8s.io/client-go/kubernetes.NewForConfig
ShowFrom expression matched no samples
ShowFrom expression matched no samples
         0     0% 11.79%    28.54MB  9.60%  k8s.io/client-go/kubernetes.NewForConfig
```

A few minutes later with deployment emulation script still running (`ShowFrom expression matched no samples` removed):

```
         0     0% 15.38%    31.54MB 12.58%  k8s.io/client-go/kubernetes.NewForConfig
         0     0% 15.28%    31.54MB 12.50%  k8s.io/client-go/kubernetes.NewForConfig
         0     0% 15.28%    31.54MB 12.50%  k8s.io/client-go/kubernetes.NewForConfig
         0     0% 15.22%    31.54MB 12.45%  k8s.io/client-go/kubernetes.NewForConfig
         0     0% 14.33%    31.54MB 11.72%  k8s.io/client-go/kubernetes.NewForConfig
         0     0% 14.33%    31.54MB 11.72%  k8s.io/client-go/kubernetes.NewForConfig
         0     0% 15.47%    31.54MB 12.66%  k8s.io/client-go/kubernetes.NewForConfig
```

A few minutes later, after deployment emulation script stopped (`ShowFrom expression matched no samples` removed):

```
         0     0% 14.64%    33.04MB 12.08%  k8s.io/client-go/kubernetes.NewForConfig
         0     0% 14.64%    33.04MB 12.08%  k8s.io/client-go/kubernetes.NewForConfig
         0     0% 14.77%    33.04MB 12.18%  k8s.io/client-go/kubernetes.NewForConfig
         0     0% 14.77%    33.04MB 12.18%  k8s.io/client-go/kubernetes.NewForConfig
         0     0% 14.77%    33.04MB 12.18%  k8s.io/client-go/kubernetes.NewForConfig
         0     0% 14.77%    33.04MB 12.18%  k8s.io/client-go/kubernetes.NewForConfig
         0     0% 14.78%    33.04MB 12.19%  k8s.io/client-go/kubernetes.NewForConfig
```


Steps for validation:
1. Bring up HA Rancher v2.10.0-alpha3
2. Access Azure, create 3 AKS clusters
3. Create Cloud Credentials in Rancher for Azure
4. Import the AKS clusters into Rancher, wait for Active status
5. Set kubeconfig for local/upstream cluster and execute patch script for deployment emulation
6. In a separate terminal, set kubeconfig for local/upstream cluster and execute heap monitor script
7. Verify mostly `ShowFrom expression matched no samples` outputs are present, some memory usage can be seen on `aks.(*aksOperatorController).onClusterChange` but the memory usage does not aggregate or persist while script is running or after it has been stopped and the aks clusters return to active status. 
```
ShowFrom expression matched no samples
         0     0%  0.48%     0.50MB  0.23%  k8s.io/client-go/kubernetes.NewForConfigAndClient
ShowFrom expression matched no samples
ShowFrom expression matched no samples
         0     0%  0.48%     0.50MB  0.23%  k8s.io/client-go/kubernetes.NewForConfigAndClient
ShowFrom expression matched no samples
ShowFrom expression matched no samples
ShowFrom expression matched no samples
ShowFrom expression matched no samples
ShowFrom expression matched no samples
ShowFrom expression matched no samples
ShowFrom expression matched no samples
ShowFrom expression matched no samples
```
