### ISSUE TITLE
[BUG] Stopping `rke-server` on ControlPlane node causes other nodes to go `NotReady`

### ISSUE THREAD

**Issue by jakefhyde** [rancher/rancher#45502]
**Rancher Server Setup**
- Rancher version: v2.8.2

**Information about the Cluster**
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): RKE2 

**Describe the bug**

Stopping rke2-server on a control plane node can cause other nodes to go into a NotReady state.

**To Reproduce**

- Provision split roles RKE2 cluster (3 etcd, 2 controlplane, 3 worker)
- `systemctl stop rke2-server.service` on one of the controlplane nodes 
- Check status of the nodes after a few seconds to allow connections to fail
- If other nodes did not change, start it back up and try another node

**Result**

Agents continue to use loadbalancer connection to previous controlplane node, however apiserver is not running causing nodes to go `NotReady`

**Expected Result**

Agents do not go `NotReady`.

**Screenshots**

**Additional context**

- https://github.com/rancher/rke2/issues/5614
- https://github.com/k3s-io/k3s/issues/9910
- SURE-7881

**Comment by jakefhyde** [comment]
Moving to test as issue can be tested with the following versions of RKE2/K3s:
- [v1.28.9+k3s1](https://github.com/k3s-io/k3s/releases/tag/v1.28.9%2Bk3s1)
- [v1.27.13+k3s1](https://github.com/k3s-io/k3s/releases/tag/v1.27.13%2Bk3s1)
- [v1.28.9+rke2r1](https://github.com/rancher/rke2/releases/tag/v1.28.9%2Brke2r1)
- [v1.27.13+rke2r1](https://github.com/rancher/rke2/releases/tag/v1.27.13%2Brke2r1)

**Comment by snasovich** [comment]
Closing this as this is RKE2 standalone issue tracked in https://github.com/rancher/rke2/issues/5614
