### ISSUE TITLE
[RFE] Pagination UI: Clusters List

### ISSUE THREAD

**Issue by strowi** [rancher/rancher#45511]
**Is your feature request related to a problem? Please describe.**
Currently we have ~40 (edge-)clusters in 1 Rancher-instance, will probably be more in the future. This becomes quite a long list.

**Describe the solution you'd like**
Add pagination to the rancher ui - "Clusters"

**Describe alternatives you've considered**
- 

**Additional context**
-

**Comment by richard-cox** [comment]
To confirm, you mean the clusters shown on the `/home` page?

We're hoping to implement this via the new server-side paginated process in 2.10.0 - https://github.com/rancher/dashboard/issues/10283

**Comment by strowi** [comment]
@richard-cox Yes  on "/home" it sprung into my eyes, but pagination is probably useful in all screens when too many resources are shown.
Thx for the infinfo/link somehow missed that one.

**Comment by richard-cox** [comment]
@strowi No problem. Most UI issues are over at https://github.com/rancher/dashboard

Almost all lists in the new ui are paginated, however it's done locally in the browser which does not scale well. We're slowly changing these to paginate in the backend, hopefully we're have more news soon
