### ISSUE TITLE
[BUG] It is nonstop syncing a roletemplate with a clusterrole

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#45517]
**Rancher Server Setup**
- Rancher version: 2.7.5, 2.9.0-head

**Issue description:**

 It's nonstop syncing a roletemplate with a clusterrole that are seemingly the same and have the same 'rules:' section.

**Business impact:**

 A lot of logs

**Troubleshooting steps:**

We compare the rules between the two roles and confirmed that they are same. But, we are seeing this in the logs

rancher-74f4d76887-nw9fm rancher 2023/08/26 01:37:43 [INFO] Updating role rt-4wcnr in c-xkcxk because of rules difference with roleTemplate QL-ClusterAdmin (rt-4wcnr).
rancher-74f4d76887-nw9fm rancher 2023/08/26 01:37:43 [INFO] Updating role rt-4wcnr in c-xkcxk because of rules difference with roleTemplate QL-ClusterAdmin (rt-4wcnr).
rancher-74f4d76887-nw9fm rancher 2023/08/26 01:37:43 [INFO] Updating role rt-4wcnr in c-xkcxk because of rules difference with roleTemplate QL-ClusterAdmin (rt-4wcnr).
rancher-74f4d76887-nw9fm rancher 2023/08/26 01:37:43 [INFO] Updating role rt-4wcnr in c-xkcxk because of rules difference with roleTemplate QL-ClusterAdmin (rt-4wcnr).
rancher-74f4d76887-nw9fm rancher 2023/08/26 01:37:43 [INFO] Updating role rt-4wcnr in c-xkcxk because of rules difference with roleTemplate QL-ClusterAdmin (rt-4wcnr).
rancher-74f4d76887-nw9fm rancher 2023/08/26 01:37:43 [INFO] [mgmt-auth-crtb-controller] Updating role rt-4wcnr in namespace c-xkcxk
rancher-74f4d76887-nw9fm rancher 2023/08/26 01:37:43 [INFO] [mgmt-auth-crtb-controller] Updating role rt-4wcnr in namespace c-xkcxk
rancher-74f4d76887-nw9fm rancher 2023/08/26 01:37:43 [INFO] [mgmt-auth-crtb-controller] Updating role rt-4wcnr in namespace c-xkcxk
rancher-74f4d76887-nw9fm rancher 2023/08/26 01:37:43 [INFO] [mgmt-auth-crtb-controller] Updating role rt-4wcnr in namespace c-xkcxk
rancher-74f4d76887-nw9fm rancher 2023/08/26 01:37:43 [INFO] [mgmt-auth-crtb-controller] Updating role rt-4wcnr in namespace c-xkcxk
rancher-74f4d76887-nw9fm rancher 2023/08/26 01:37:43 [INFO] Updating role rt-4wcnr in c-xkcxk because of rules difference with roleTemplate QL-ClusterAdmin (rt-4wcnr).
rancher-74f4d76887-nw9fm rancher 2023/08/26 01:37:43 [INFO] [mgmt-auth-crtb-controller] Updating role rt-4wcnr in namespace c-xkcxk
rancher-74f4d76887-nw9fm rancher 2023/08/26 01:37:43 [INFO] Updating role rt-4wcnr in c-xkcxk because of rules difference with roleTemplate QL-ClusterAdmin (rt-4wcnr).
rancher-74f4d76887-nw9fm rancher 2023/08/26 01:37:43 [INFO] [mgmt-auth-crtb-controller] Updating role rt-4wcnr in namespace c-xkcxk
rancher-74f4d76887-nw9fm rancher 2023/08/26 01:37:43 [INFO] Updating role rt-4wcnr in c-xkcxk because of rules difference with roleTemplate QL-ClusterAdmin (rt-4wcnr).
rancher-74f4d76887-nw9fm rancher 2023/08/26 01:37:43 [INFO] [mgmt-auth-crtb-controller] Updating role rt-4wcnr in namespace c-xkcxk
rancher-74f4d76887-nw9fm rancher 2023/08/26 01:37:43 [INFO] [mgmt-auth-crtb-controller] Updating role rt-4wcnr in namespace c-xkcxk
rancher-74f4d76887-nw9fm rancher 2023/08/26 01:37:43 [INFO] Updating role rt-4wcnr in c-xkcxk because of rules difference with roleTemplate QL-ClusterAdmin (rt-4wcnr).
rancher-74f4d76887-nw9fm rancher 2023/08/26 01:37:44 [INFO] [mgmt-auth-crtb-controller] Updating role rt-4wcnr in namespace c-xkcxk
rancher-74f4d76887-nw9fm rancher 2023/08/26 01:37:44 [INFO] [mgmt-auth-crtb-controller] Updating role rt-4wcnr in namespace c-xkcxk
rancher-74f4d76887-nw9fm rancher 2023/08/26 01:37:44 [INFO] Updating role rt-4wcnr in c-xkcxk because of rules difference with roleTemplate QL-ClusterAdmin (rt-4wcnr).
rancher-74f4d76887-nw9fm rancher 2023/08/26 01:37:44 [INFO] Updating role rt-4wcnr in c-xkcxk because of rules difference with roleTemplate QL-ClusterAdmin (rt-4wcnr).
rancher-74f4d76887-nw9fm rancher 2023/08/26 01:37:44 [INFO] [mgmt-auth-crtb-controller] Updating role rt-4wcnr in namespace c-xkcxk
rancher-74f4d76887-nw9fm rancher 2023/08/26 01:37:44 [INFO] Updating role rt-4wcnr in c-xkcxk because of rules difference with roleTemplate QL-ClusterAdmin (rt-4wcnr).
rancher-74f4d76887-nw9fm rancher 2023/08/26 01:37:44 [INFO] [mgmt-auth-crtb-controller] Updating role rt-4wcnr in namespace c-xkcxk
rancher-74f4d76887-nw9fm rancher 2023/08/26 01:37:44 [INFO] Updating role rt-4wcnr in c-xkcxk because of rules difference with roleTemplate QL-ClusterAdmin (rt-4wcnr)

**Actual behavior:**
It is comparing the rules when the 2 roles are the same

**Expected behavior:**
Not comparison

[SURE-6824](https://jira.suse.com/browse/SURE-6824)

**Comment by raulcabello** [comment]
# Validation
## Root Cause
Certain resources (clusterscans, catalogtemplates, projects, etc) exist in the management plane but are scoped to clusters or projects. They need special `Roles` called management plane roles because the need to be authorized just inside of the namespace that backs the project or cluster they belong to.

Management plane roles are reconciled in two places. In one place the wrong set of `Rules` is used which leads to a nonstop syncing state.

## What was fixed, or what change has occurred
The reconciliation that was setting the wrong set of `Rules` has been removed, leaving only one reconciliation in place. That means management plane roles will only be updated if there is a `PRTB` or `CRTB` that references them. 


## What areas could experience regressions
I have done some tests, and all `Roles` seem to be updated when `Rules` change in the `RoleTemplate`. We have removed one reconciliation that was updating management plane roles, so that `Roles` (both normal and management plane roles) are updated when something changes in the `RoleTemplate` (both cluster and project context) should be verified.

**Comment by joesims22** [comment]
Validated on v2.9-head `37f6eeb`. 

All test cases in the test plan were validated and successful.
