### ISSUE TITLE
Rancher HA script generator inserts white lines when copy & pasting certificates.

### ISSUE THREAD

**Issue by duffyjay** [rancher/rancher#4552]
Rancher Version: 1.0.1

Docker Version: 1.10.3

OS:  Ubuntu 14.04.3 LTS 

Steps to Reproduce:  We upgraded our Rancher from 1.0.0 to 1.0.1, using that upgraded node as the bootstrap server.  Login to that server and select HA and enable for 5 nodes and copy & paste certificates into the appropriate boxes.  This was done on a Macbook OSX 10.10.5 with Firefox 45.0.2

Results:  Generate script and the resulting script has inserted a white line between every line in all certificates in the script.  Looks like the following:

-----BEGIN CERTIFICATE-----

MIIEgDCCA2igAwIBAgIIRS0mBmfiSFwwDQYJKoZIhvcNAQELBQAwSTELMAkGA1UE

BhMCVVMxEzARBgNVBAoTCkdvb2dsZSBJbmMxJTAjBgNVBAMTHEdvb2dsZSBJbnRl

cm5ldCBBdXRob3JpdHkgRzIwHhcNMTYwNDA3MDgyNTA5WhcNMTYwNjMwMDgyMDAw

WjBoMQswCQYDVQQGEwJVUzETMBEGA1UECAwKQ2FsaWZvcm5pYTEWMBQGA1UEBwwN

TW91bnRhaW4gVmlldzETMBEGA1UECgwKR29vZ2xlIEluYzEXMBUGA1UEAwwOd3d3

........

This results in the certificates not being valid and the load balancers never start because they do not have valid certificates to load.

Expected:  Valid certificates to be generated.  Worked around this by copy pasting the correct certificates into the script after it is generated.

**Comment by LLParse** [comment]
Hi @duffyjay, I have successfully reproduced this with Rancher v1.0.1-rc7 with a Macbook Pro 10.11 running Firefox 45.0.2

I have tried copy/pasting PEM-encoded certificates that use line feeds (0x0A) for line breaks and carriage return line feeds (0x0D 0x0A) for line breaks. I have also tried uploading files in the two formats.

The result is always the same: the generated script has dos-style newlines for the certificates, and unix-style for all other newlines. Mixing newline style is _always_ incorrect, and in this case we expect all unix-style newlines.

**Comment by vincent99** [comment]
The API should convert the certificate text to unix-style LF if that's what it needs, not rely on the client to provide it.

**Comment by deniseschannon** [comment]
With the new HA in 1.2, there is no more script generation so this should no longer be an issue.

**Comment by deniseschannon** [comment]
We've refactored HA to be much simpler and just run additional arguments with the rancher-server command.
