### ISSUE TITLE
Add support for docker 26.1.2

### ISSUE THREAD

**Issue by mitulshah-suse** [rancher/rancher#45523]
The following docker versions are to be added:
v26.1.2

The same approach as https://github.com/rancher/rancher/issues/45291 is to be followed for implementation and testing.

**Comment by vivek-shilimkar** [comment]
Validated on rancher v2.9-head
Docker 26.1.2 validation completed on below OSes with node driver and custom clusters:
- RHEL 9.3
- OL 9.3
- Rocky  9.3
- Ubuntu 24.04
- CentOS 7.9
- SLES 15-SP5 OpenSUSE15.5 shows error : `No update candidate for 'docker-24.0.7_ce-150000.198.2.x86_64'. The highest available version is already installed.`

**Comment by mitulshah-suse** [comment]
Script has been released at the below path.
https://releases.rancher.com/install-docker/26.1.2.sh

Closing the issue.
