### ISSUE TITLE
[Backport v2.8] Unable scale an RKE1 cluster from 1 to 3 etcd nodes or nodes with etcd role

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#45539]
Backport of https://github.com/rancher/rancher/issues/43356 to v2.8.x release line

**Comment by kinarashah** [comment]
RKE PR merged, waiting to tag RC and vendor into Rancher.

**Comment by susesgartner** [comment]
Ticket #45539 - Test Results - ✅ 
---
 
| Scenario | Test Case | Result |
|---|---|---|
| 1. | Scale cluster from 1 to 3 | PASS|
 
---
Verified with docker on Rancher `v2.8-head`:
---
 
Scenario 1: Scale cluster from 1 to 3
---
1. Create an rke1 cluster with split roles
2. Wait for the cluster to provision
3. Scale the cluster from 1-3 nodes
 
Results: Cluster successfully scales.
