### ISSUE TITLE
Duplicated entries for the same instnace in healthcheck config

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#4553]
Steps to reproduce:

* Have a couple of hosts in your system
* Create health check enabled instance on host1. Health check is scheduled on host2 for the instance
* Reconnect host2. HealthcheckInstanceHostMap should be recreated for host2/instance.

Bug: in healthcheck config (/etc/healthcheck/healthcheck.cfg), you see duplicated record for the instance

**Comment by soumyalj** [comment]
Verified this issue and found https://github.com/rancher/rancher/issues/4595
