### ISSUE TITLE
Health check process restarts every hour on network agent

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#4554]
Steps to reproduce:

1) Register host
2) Start health check enabled instance on a host
3) Let the setup be idle for > 1 hour.

Although nothing happens, every hour network agent reports service.events for health check (INIT followed by UP) - cattle.service_event table. Happens because health check process is being restarted every hour on the backend.

**Comment by alena1108** [comment]
@sangeethah to test the fix:

1) Verify that generic health check works - running validation test is enough.
2) Setup 1 service with health check enabled. Let setup run for a > 1 hour. Verify that there are no INIT health check events coming for container every hour (service_event table)

**Comment by sangeethah** [comment]
Tested with build from master:

Validation tests relating to host down scenarios pass.

There is no "INIT" health check events reported every hour for health_check enabled instances.
