### ISSUE TITLE
[SURE-7372] [2.8] Reduce resource usage from Azure AD provider 

### ISSUE THREAD

**Issue by aruiz14** [rancher/rancher#45543]
Internal reference: [SURE-7372](https://jira.suse.com/browse/)

**Is your feature request related to a problem? Please describe.**
After analyzing profiling data, we discovered that Azure AD provider often produced a high resource usage, both memory and CPU, due to the use of a third-party library.

We [submitted a pull request upstream](https://github.com/manicminer/hamilton/pull/271) to improve this, but it didn't get the necessary attention. After discussing it with the responsible teams, we decided to temporarily fork (https://github.com/rancher/hamilton) this dependency to include this patch, while working on a longer-term solution for 2.9 (see https://github.com/rancher/rancher/issues/45009).

**Describe the solution you'd like**
Rancher 2.8 replaces `github.com/manicminer/hamilton` dependency with our own fork `github.com/rancher/hamilton`

**Describe alternatives you've considered**
An alternative solution is being developed for Rancher 2.9, by switching to the official SDK: https://github.com/rancher/rancher/issues/45009

**Comment by aruiz14** [comment]
## Validation Template

## What was fixed, or what change has occurred

High CPU and memory usage when retrieving Azure Active Directory information.

## Areas or cases that should be tested

[Configure authentication for Azure AD](https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/authentication-config/configure-azure-ad) and ensure everything keeps working as expected.

## What areas could experience regressions

None. The dependency bump only includes a changes in the internals to get better performance when using Azure AD as authentication provider.

## Are the repro steps accurate/minimal?

The impact of this change can only be perceived by comparing memory profiling, which was done separately using a debug build.

**Comment by rancher-max** [comment]
This is being used in production today with success, so we are closing the issue out without explicit QA. If there is additional need, feel free to create a new issue or reopen this.
