### ISSUE TITLE
RKE2 and K3S - KDM Update for K8s May 2024 patch release for Rancher 2.7

### ISSUE THREAD

**Issue by rancher-max** [rancher/rancher#45549]
# KDM Updates

| New Kubernetes Version  | Min Rancher Version | Max Rancher Version |
|                  :---:                  |              :---:               |               :---:               |
| v1.27.14+rke2r1                  | v2.7.11-alpha1             | v2.8.99 |
| v1.27.14+k3s1                  | v2.7.11-alpha1             | v2.8.99 |

# KDM Branch
[dev-v2.7-2024-05-patches](https://github.com/rancher/kontainer-driver-metadata/tree/dev-v2.7-2024-05-patches)

# Chart Changelog

| Chart Name  | New Version | Affected Kubernetes Version(s) |
|        :---:        |       :---:        |                     :---:                     |

TBD

# Argument Changelog

| Argument Name  | Affected Kubernetes Version(s) |
|        :---:           |                     :---:                     |

TBD

# Additional Notes

**Comment by ShylajaDevadiga** [comment]
## K3S- v1.27.14-rc1+k3s1 Rancher 2.7.13

<img width="1859" alt="image" src="https://github.com/rancher/rancher/assets/56045581/5e653a88-b2fc-4075-be67-7d161e87ac2b">


## RKE2 v1.27.14-rc2+rke2r1 Rancher 2.7.13
<img width="1904" alt="image" src="https://github.com/rancher/rancher/assets/56045581/b0317030-d8cd-46a7-a286-c3bf97b4cdc3">

<img width="1856" alt="image" src="https://github.com/rancher/rancher/assets/56045581/a499f904-5d6b-4d74-9574-fdc8e07e9509">
<img width="1884" alt="image" src="https://github.com/rancher/rancher/assets/56045581/86efa271-8685-4775-9d2b-f6a92e451e69">

**Comment by mdrahman-suse** [comment]
Validated on branch dev-v2.7-2024-05-patches with URL: https://raw.githubusercontent.com/rancher/kontainer-driver-metadata/dev-v2.7-2024-05-patches/data/data.json

<img width="637" alt="Screen Shot 2024-05-29 at 3 59 52 PM" src="https://github.com/rancher/rancher/assets/91496375/9f484dc3-29ff-49c8-a2d5-6f5b5ede685f">

**Comment by VestigeJ** [comment]
<img width="1067" alt="Screenshot 2024-07-02 at 3 53 30 PM" src="https://github.com/rancher/rancher/assets/8961630/a1b0abb4-0859-4b12-9a83-16735540d40d">
