### ISSUE TITLE
RKE2 and K3S - KDM Update for K8s May 2024 patch release for Rancher 2.8

### ISSUE THREAD

**Issue by rancher-max** [rancher/rancher#45550]
# KDM Updates

| New Kubernetes Version  | Min Rancher Version | Max Rancher Version |
|                  :---:                  |              :---:               |               :---:               |
| v1.27.14+rke2r1                  | v2.8.0-alpha1             | v2.8.99 |
| v1.28.10+rke2r1                  | v2.8.3-alpha1             | v2.8.99 |
| v1.27.14+k3s1                  | v2.8.0-alpha1             | v2.8.99 |
| v1.28.10+k3s1                  | v2.8.3-alpha1             | v2.8.99 |

# KDM Branch
[dev-v2.8-2024-05-patches](https://github.com/rancher/kontainer-driver-metadata/tree/dev-v2.8-2024-05-patches)

# Chart Changelog

| Chart Name  | New Version | Affected Kubernetes Version(s) |
|        :---:        |       :---:        |                     :---:                     |

TBD

# Argument Changelog

| Argument Name  | Affected Kubernetes Version(s) |
|        :---:           |                     :---:                     |

TBD

# Additional Notes

**Comment by ShylajaDevadiga** [comment]
## K3S- v1.28.10-rc1+k3s1 Rancher 2.8.4


<img width="1886" alt="image" src="https://github.com/rancher/rancher/assets/56045581/2677887e-8401-4d2b-9dfd-0c91b371a747">

<img width="1906" alt="image" src="https://github.com/rancher/rancher/assets/56045581/2f53622b-8409-4e9f-88ac-29f9e3fd6db0">


## K3S- v1.27.14-rc1+k3s1 Rancher 2.8.4

<img width="1918" alt="image" src="https://github.com/rancher/rancher/assets/56045581/205a9471-fdd0-4c27-b244-a87fe80f9250">


<img width="1882" alt="image" src="https://github.com/rancher/rancher/assets/56045581/aea09bad-7311-40b8-8e8c-a11a90144af0">

## K3S- v1.27.14-rc1+k3s1 Rancher 2.7.13

<img width="1859" alt="image" src="https://github.com/rancher/rancher/assets/56045581/5e653a88-b2fc-4075-be67-7d161e87ac2b">


## RKE2 v1.28.10+rke2r1 Rancher 2.8.4
<img width="958" alt="image" src="https://github.com/rancher/rancher/assets/56045581/4bf8624a-8647-430a-b9ad-c2feded2fd61">





## RKE2 v1.27.14-rc2+rke2r1 Rancher 2.7.13
<img width="1904" alt="image" src="https://github.com/rancher/rancher/assets/56045581/b0317030-d8cd-46a7-a286-c3bf97b4cdc3">

<img width="1856" alt="image" src="https://github.com/rancher/rancher/assets/56045581/a499f904-5d6b-4d74-9574-fdc8e07e9509">
<img width="1884" alt="image" src="https://github.com/rancher/rancher/assets/56045581/86efa271-8685-4775-9d2b-f6a92e451e69">

**Comment by mdrahman-suse** [comment]
Validated on branch `dev-v2.8-2024-05-patches` with URL: `https://raw.githubusercontent.com/rancher/kontainer-driver-metadata/dev-v2.8-2024-05-patches/data/data.json`
<img width="650" alt="Screen Shot 2024-05-29 at 2 25 52 PM" src="https://github.com/rancher/rancher/assets/91496375/740e5eb2-dcae-4b06-a402-54046220bbd5">
