### ISSUE TITLE
After a service upgrade and change in port number, old and new pool members are displayed on the externalLB portal

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#4555]
Rancher Version:1.0.1

Docker Version:1.11.0

Steps to Reproduce: 
1. Configure an external LB
2. Add a service with two containers, ports, label associated with the external LB
3. Upgrade the service with changing the external port number 
4. Perform a finish upgrade.

Results: 
The pool list with both old and new members(corresponding to the containers) are displayed in the external LB portal for more than 10 minutes. In this new state if a new service is created, the old members get deleted.

Expected:
Only the new pool members should be displayed after the upgrade process. Older members should not linger on the external LB

**Comment by will-chan** [comment]
We should update meta-data for the service post "Finish Upgrade".

**Comment by soumyalj** [comment]
After the upgrade none of the pool members are populated in the external LB portal
[log_4555.txt](https://github.com/rancher/rancher/files/243343/log_4555.txt)
. Please see attached logs

**Comment by soumyalj** [comment]
As seen in the attached logs, the UI changes the VIP name from caps to small after an upgrade.
Reopening #4535. 
Also, when the service is in upgraded state(before the finish upgrade), where the original container is stopped and new container is created, the pool member (corresponding to the stopped container) on the F5 portal is removed. The expected behavior would be for the stopped container to still be a pool member. It should be removed when a finish upgrade is done
This should be in sync with the behavior when we do a STOP service. When we do a STOP service, the pool members on F5 portal continue to be displayed. This is a discrepancy.
