### ISSUE TITLE
Add support for docker 26.1.3

### ISSUE THREAD

**Issue by chiukapoor** [rancher/rancher#45563]
Add support for docker v26.1.3. 
Release notes: https://docs.docker.com/engine/release-notes/26.1/#2613

ref issue: https://github.com/rancher/rancher/issues/45439

Docker versions added: 26.1.3

**Comment by rishabhmsra** [comment]
Validated on rancher v2.9-head(3c48a19)
Validated docker 26.1.3 install script by provisioning node driver as well as custom clusters using below OSes:

- Rocky 9.3, 8.9
- RHEL 9.3, 8.9
- OL 9.3, 8.9
- Ubuntu 24.04, 22.04
- CentOS 7.9

**Comment by mitulshah-suse** [comment]
Script has been released at the below path
https://releases.rancher.com/install-docker/26.1.3.sh
