### ISSUE TITLE
Mysql logging affects db performance

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#4556]
Noticed on a highly active setup where mysql db was running locally (inside rancher-server container) and the processes backlog was big (process_instance/process_execution table had lots of records). 

Mysql reads became really slow, and it slowed down processes execution performance. We suspect it happens due to mysql logging being enabled.

**Comment by vincent99** [comment]
I would say we just disable binlogs in the default image, dobwe know of a single real example of someone using it to replicate out?

/cc @cloudnautique

**Comment by ibuildthecloud** [comment]
I put in a PR to turn it off https://github.com/rancher/rancher/pull/4584/files.  It really impacts performance to a high degree.

**Comment by sangeethah** [comment]
Tested with Release v1.1.0-dev2-rc4

Following 4 settings are not used in /etc/mysql/my.cnf anymore

server-id               = 1 (commented)
log_bin                 = /var/log/mysql/mysql-bin.log(commented)
sync_binlog           = 1
innodb_flush_log_at_trx_commit = 1

This fix is already available with - rancher-server = v1.1.0-dev1
