### ISSUE TITLE
When multiple rancher instances with the same externalLB are configured, pool members get periodically added and deleted on the external LB 

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#4557]
Rancher Version:1.0.1

Docker Version:1.11.0

Steps to Reproduce: 
1. Configure an external LB
2. Create services with two containers, ports, label associated with the external LB using rancher UI
3. Create another rancher instance pointing to the same external LB
4. Refresh the external LB portal to see the pool members getting added and deleted OR observe the logs

Expected: Pool members should not get added and deleted

Attached are the logs:
[extlb_log.txt](https://github.com/rancher/rancher/files/235670/extlb_log.txt)

**Comment by soumyalj** [comment]
The fix does not work for cases when the services in two rancher instances are in their default environments. For all services in default environments the following format is used servicename_environmentUUID_rancher.internal for the f5 pool members

**Comment by prachidamle** [comment]
@janeczku assigning to you to check if this is applicable for external ELB. Please put it back to 1.2.0 if it is and let @deniseschannon know

**Comment by prachidamle** [comment]
moved it 1.2.0

**Comment by janeczku** [comment]
@prachidamle This is because the environment UUID for default environments isn't really an UUID. It's always the string "adminProject". I don't think we can distinguish pools added by external-lb services running in the default environment on different Rancher instances unless this is fixed in Cattle.
