### ISSUE TITLE
[BUG] CRDs for `rancher-monitoring-crd` helm chart are not updated

### ISSUE THREAD

**Issue by nicolas-marin-vwfs** [rancher/rancher#45575]
**Rancher Server Setup**
- Rancher version: 2.8.3
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): EKS 1.25
- Proxy/Cert Details: -

**Information about the Cluster**
- Kubernetes version: 1.25
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? Imported, EKS

**User Information**
- What is the role of the user logged in? Admin

**Describe the bug**

The CRDs for the `rancher-monitoring-crd` helm chart are not updated. The job started by the helm hook succeeds, but the CRDs are not updated. The following error message appears in the logs of the job:
  
```
2024-05-22T08:16:43.513387966Z Error from server (Forbidden): error when replacing "/etc/crd/charts/crds/crd-alertmanagerconfigs.yaml": customresourcedefinitions.apiextensions.k8s.io "alertmanagerconfigs.monitoring.coreos.com" is forbidden: User "system:serviceaccount:cattle-monitoring-system:rancher-monitoring-crd-manager" cannot update resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope
```

**To Reproduce**
1. Deploy `rancher-monitoring-crd`
2. Check if CRD (e.g. `alertmanagerconfigs.monitoring.coreos.com`) is updated

**Result**

**Expected Result**

CRDs are updated.

**Additional context**

We assume that the problem is the [RBAC for the ClusterRole `rancher-monitoring-crd-manager`](https://github.com/rancher/charts/blob/dev-v2.9/charts/rancher-monitoring-crd/103.1.0%2Bup45.31.1/templates/rbac.yaml#L12). It contains the [non-existing verb `replace`](https://kubernetes.io/docs/reference/access-authn-authz/authorization/#request-verb-resource), but it doesn't contain the verb `update`.

**Comment by MKlimuszka** [comment]
This has been fixed and will go out with our next release.
