### ISSUE TITLE
[BUG] Reconciling stuck message when adding a second node 

### ISSUE THREAD

**Issue by davidelvisrosa** [rancher/rancher#45574]
**Rancher Server Setup**
- Rancher version: 2.8.4
- Installation option (Docker install/Helm Chart): Docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2
- Proxy/Cert Details:
Rancher Cert
**Information about the Cluster**
- Kubernetes version: 1.28.9+rke2r1
- Cluster Type (Local/Downstream): Local
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Custom

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Admin

**Describe the bug**
After created a new Rancher server and a new Kubernetes cluster I added a new node successfully, but the second get this message: Waiting for probes: calico, etcd, kube-apiserver, kube-controller-manager, kube-scheduler, kubelet.  

**To Reproduce**
Message when adding the second node, this is stuck.
Waiting for probes: calico, etcd, kube-apiserver, kube-controller-manager, kube-scheduler, kubelet

**Result**
Waiting for probes: calico, etcd, kube-apiserver, kube-controller-manager, kube-scheduler, kubelet
**Expected Result**
No message. 

**Screenshots**
<img width="1166" alt="image" src="https://github.com/rancher/rancher/assets/67168655/599c6924-d4a3-4578-8ca8-1d7127f269d1">

**Comment by anupama2501** [comment]
Hello @davidelvisrosa I noticed that bug does not have a description. Could you please add a brief description of the bug so we can understand the issue better?


I tried reproducing this as well and noticed the nodes in my cluster have come up active. 

<img width="600" alt="2024-05-22_10-08-22" src="https://github.com/rancher/rancher/assets/38144301/5b7a09ea-d791-455d-985a-c7de546ae1b7">

Could you provide any error rancher logs that were noticed that can help us understand the issue better?

**Comment by davidelvisrosa** [comment]
Fixed, slow internet was the issue. thank you.
