### ISSUE TITLE
[BUG] Steve VAI API returns 500 error when filtering secrets by label selectors

### ISSUE THREAD

**Issue by brudnak** [rancher/rancher#45570]
# Rancher Server Setup

| Component                        | Version / Type                      |
| -------------------------------- | ----------------------------------- |
| Rancher version                  | v2.9-vai-temp-5.2.24                |
| Installation option              | Helm (high availability)            |
| RKE binary version used          | v1.5.7                              |
| If Helm Chart k8s cluster        | v1.28.7                             |
| Cert Details                     | external tls `aws acm`              |
| Docker version                   | 20.10.7, build f0df350              |
| Helm version                     | v2.16.8-rancher2                    |
| Downstream cluster type          | n/a                                 |
| Downstream K8s version           | n/a                                 |
| Authentication providers enabled | local                               |
| Logged in user role              | admin                               |
| Browser type                     | Opera GX                            |
| Browser version                  | LVL5 (core: 109.0.5097.93) (x86_64) |
| Dashboard                        | pagination-alpha-dev 96e23ad        |
| Webhook version                  | rancher/rancher-webhook:v0.5.0-rc8  |

# Describe the bug

Steve API secrets endpoint returning 500 error when filtering by label selectors. SQL logic error suggests issue with database query processing the label selectors. Works correctly on v2.9-head, but broken on current version.

# To Reproduce

1. Install Rancher with the following command:

```sh
kubectl create namespace cattle-system

helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=$RANCHER_URL_VAR \
  --set bootstrapPassword=$PASSWORD_VAR \
  --set tls=external \
  --set rancherImageTag=v2.9-vai-temp-5.2.24 \
  --set global.cattle.psp.enabled=false \
  --set rancherImage=rmweir/rancher --set 'extraEnv[0].name=CATTLE_AGENT_IMAGE' --set 'extraEnv[0].value=rmweir/rancher-agent:v2.9-vai-temp-5.2.24'
```

2. In the local cluster create a namespace `namespace2`
3. Create a `Opaque` secret named `secret6` with no data and 2 labels
   1. Label 1: `key1 : value4`
   2. Label 2: `key2 : value3`

4. Run the following curl command to get `secret6`

```sh
 curl -X GET \
  -H "Authorization: Bearer $YOUR_TOKEN_GOES_HERE" \
  "https://$YOUR_RANCHER_URL_GOES_HERE/v1/secrets?filter=metadata.labels.key1=value4&filter=metadata.labels.key2=value3"
```

# Result

Get the following error:

```json
{"type":"error","links":{},"code":"ServerError","message":"Error initializing Store DB: SQL logic error: no such column: f.metadata.labels.key1 (1)","status":500,"type":"error"}
```

# Expected Result

I expected to be returned `secret6`, as this same curl command works on Rancher v2.9-head.

# Tested Versions

| Rancher version                                    | Bug Present on This Version?          |
| -------------------------------------------------- | ------------------------------------- |
| v2.9-vai-temp-5.2.24                               | YES BUG PRESENT ON THIS VERSION       |
| v2.9-3c48a195381ad55f9fef7e9bf32b1593d43368ca-head | NO BUG IS NOT PRESENT ON THIS VERSION |

# Bug Frequency

`Consistent (10/10)`

| Frequency                                                                                          | Selected Option |
| -------------------------------------------------------------------------------------------------- | --------------- |
| Consistent (10/10) - A consistent bug can be replicated every time the test is executed.           | ✅               |
| Frequent (7/10)- A frequent bug can be replicated like 7 out of 10 times when a test is replicated |                 |
| Occasional (5/10) - Occasional bug is more hard to replicate than a frequent bug.                  |                 |
| Once thus far, twice thus far - Few bugs cannot be reproduced every time you run the test.         |                 |

# Associated API Calls & Responses

| #   | Request URL                                                                                    | Request Method | Status Code |
| --- | ---------------------------------------------------------------------------------------------- | -------------- | ----------- |
| 1   | {rancher-url}/v1/secrets?filter=metadata.labels.key1=value4&filter=metadata.labels.key2=value3 | GET            | 500         |

**Comment by moio** [comment]
More builds (v2.9.0-alpha5 and newer) give a better description of what is actually happening:

```
% curl --insecure -X GET \
  -H "Authorization: Bearer token-XXX" \
  "https://localhost:8444/v1/secrets?filter=metadata.labels.key1=value4&filter=metadata.labels.key2=value3"

{"type":"error","links":{},"code":"InvalidBodyContent","message":"column is invalid [metadata.labels.key1]: supplied column is invalid","status":422,"type":"error"}
```

At the moment, Steve does not support filtering by labels - this is expected per the [EPIC](https://github.com/rancher/rancher/issues/45635) issue to come to a later version.

Until then filtering is only supported for a subset of attributes, which currently is:
 - `metadata.name`, `metadata.namespace` and `metadata.timestamp` for any resource kind
 - a short list of hardcoded attributes for a selection of specific types listed here: https://github.com/rancher/steve/blob/22a06dd14f51e09ebfaa6277ec9424d8c1cc40e9/pkg/stores/sqlproxy/proxy_store.go#L52-L58
 - the special string `metadata.fields[N]`, with N starting at 0, for all columns displayed by `kubectl get $TYPE`. For example `secrets` have `"metadata.fields[0]"`, `"metadata.fields[1]"` , `"metadata.fields[2]"`, and `"metadata.fields[3]"` respectively corresponding to `"name"`, `"type"`, `"data"`, and `"age"`
 
 
 Any other column name is expected to return 422.
