### ISSUE TITLE
[BUG] Failed creating new cluster RKE2

### ISSUE THREAD

**Issue by davidelvisrosa** [rancher/rancher#45573]
**Rancher Server Setup**
- Rancher version: 2.8.4
- Installation option (Docker install/Helm Chart): Docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2
- Proxy/Cert Details:
Rancher Cert
**Information about the Cluster**
- Kubernetes version: 12.8.9
- Cluster Type (Local/Downstream): Local
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Custom

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Admin

**Describe the bug**
I have the error when I try to create a new custom cluster.
Failed to create fleet-default/k8s-dr cluster.x-k8s.io/v1beta1, Kind=Cluster for rke-cluster fleet-default/k8s-dr: Internal error occurred: failed calling webhook "default.cluster.cluster.x-k8s.io": failed to call webhook: Post "https://capi-webhook-service.cattle-provisioning-capi-system.svc:443/mutate-cluster-x-k8s-io-v1beta1-cluster?timeout=10s": service "capi-webhook-service" not found

**To Reproduce**
I created a new Rancher server with:
docker run -d --name rancher-server-2.8.4  -v ${PWD}/volume:/var/lib/rancher --restart=unless-stopped -p 80:80 -p 443:443 --privileged rancher/rancher:v2.8.4. After connected to it, I tried to create a cluster using Custom, V1.28.9+rke2r1 and all standard configs and I get the error. 

**Result**
Failed to create fleet-default/k8s-dr cluster.x-k8s.io/v1beta1, Kind=Cluster for rke-cluster fleet-default/k8s-dr: Internal error occurred: failed calling webhook "default.cluster.cluster.x-k8s.io": failed to call webhook: Post "https://capi-webhook-service.cattle-provisioning-capi-system.svc:443/mutate-cluster-x-k8s-io-v1beta1-cluster?timeout=10s": service "capi-webhook-service" not found

**Expected Result**
No errors

**Screenshots**
<img width="1167" alt="image" src="https://github.com/rancher/rancher/assets/67168655/6d50223b-5cc8-4c0b-84cf-5baf0607a412">

**Additional context**

**Comment by anupama2501** [comment]
Hello @davidelvisrosa I noticed that bug does not have a description. Could you please add a brief description of the bug so we can understand the issue better?

Also, after reading through the reproduction steps, I tried recreating the issue but did not notice the error. is it possible you tried creating the cluster before the service `capi-webhook-service` has become active ?

**Comment by davidelvisrosa** [comment]
> Hello @davidelvisrosa I noticed that bug does not have a description. Could you please add a brief description of the bug so we can understand the issue better? Sure.
> 
> Also, after reading through the reproduction steps, I tried recreating the issue but did not notice the error. is it possible you tried creating the cluster before the service `capi-webhook-service` has become active ?
 Where do I check if capi-webhook-service is active ? Because I waited for many hours before create the Cluster.

**Comment by anupama2501** [comment]
You can find the service from the local cluster >> services >> From the namespace: `cattle-provisioning-capi-system` , service name: `capi-webhook-service`

It should be available within a few seconds after rancher webhook is installed. Did the error ever get resolved?

**Comment by davidelvisrosa** [comment]
It is active the service: capi-webhook-service. But the error still persist. 

![image](https://github.com/rancher/rancher/assets/67168655/392c27ed-28aa-4ce2-bfb7-e0e1226e0976)

**Comment by anupama2501** [comment]
Got it. Could you provide any additional rancher logs while this happens?

**Comment by Oats87** [comment]
@davidelvisrosa 

Have you restarted Rancher i.e. `docker restart <rancher-container>`?

The provisioningv2 generating controller that is responsible for creating the CAPI objects is what is erroring -- it can sometimes get stuck and not re-queue the object. You can also try creating a second cluster.

**Comment by davidelvisrosa** [comment]
it looks like some internet issue from my side that was slow, but I could not find any log of time out. Now it is ok, thank you for your support!

**Comment by snegalvarsan** [comment]
@anupama2501 @Sahota1225 @bfbachmann @MbolotSuse @Oats87 @davidelvisrosa  I have the same issue here,
`Failed to create fleet-default/harvercluster cluster.x-k8s.io/v1beta1, Kind=Cluster for rke-cluster fleet-default/harvercluster: Internal error occurred: failed calling webhook "default.cluster.cluster.x-k8s.io": failed to call webhook: Post "[https://webhook-service.cattle-system.svc:443/mutate-cluster-x-k8s-io-v1beta1-cluster?timeout=10s](https://webhook-service.cattle-system.svc/mutate-cluster-x-k8s-io-v1beta1-cluster?timeout=10s)": service "webhook-service" not found, failed to create fleet-default/harvercluster-pool1 cluster.x-k8s.io/v1beta1, Kind=MachineDeployment for rke-cluster fleet-default/harvercluster: Internal error occurred: failed calling webhook "default.machinedeployment.cluster.x-k8s.io": failed to call webhook: Post "[https://webhook-service.cattle-system.svc:443/mutate-cluster-x-k8s-io-v1beta1-machinedeployment?timeout=10s](https://webhook-service.cattle-system.svc/mutate-cluster-x-k8s-io-v1beta1-machinedeployment?timeout=10s)": service "webhook-service" not found`

I'm using harvester version 1.1.3, with rancher running inside a docker container of version 2.6.13.
I'd be very glad if I get help, Thank you.

**Comment by snegalvarsan** [comment]
![Image](https://github.com/user-attachments/assets/e5e31cae-3912-4433-b3af-dded9ec5045a)

@anupama2501 @davidelvisrosa @Sahota1225 @bfbachmann @MbolotSuse @Oats87 

How do I get this error if it is already connected? This has to be lamest bug here. Please help me out here guys.

**Comment by ak47us** [comment]
I was receiving this error because I was running Rancher using Docker Compose. Upon using `kubectl` to check the status of my nodes, I found `DiskPressure` warnings. I resolved this issue for myself by ensuring that my Docker Desktop had free storage.

One additional thing that helped me bootstrap was to wait a couple minutes between bootstrapping the server and creating any clusters.
