### ISSUE TITLE
External DNS should read host tags/env for publishing ips and/or dns name

### ISSUE THREAD

**Issue by Frintrop** [rancher/rancher#4558]
Rancher Version: 1.0.1

For multinetwork environments it would be great that external dns service stacks would  check hosts special host tags/env vars for a) the to be published ip address and b) the to be published dns name( maybe better as tag/env var in lb stack ? ). 
With this improvement rancher get ride off the problem which ip to be published in dns if a hosts has multiple ips ( public / natted public like in amazon aws/ private ).
( This improvement would work for all static hosts and not for autoscaling or dynamic hosts creations, but i think it would face a lot of users having static docker hosts )

**Comment by emcniece** [comment]
I'd appreciate this too. I don't want my Route53 zone polluted with a bunch of records for services that are only performing internal and/or non-public functions. It would also be great to be able to override the record template.

I am currently using [rancher-traefik](https://github.com/rawmind0/rancher-traefik) to manage internal routing, and [rancher/external-dns](https://github.com/rancher/external-dns) to update DNS zones. Rancher-Traefik reads labels to find services to expose, and it works well.

**Comment by bseng** [comment]
I'm just looking through the source code for external-dns and apparently this function is already available in some form here.

https://github.com/rancher/external-dns/blob/master/metadata/metadata.go#L79-L80

So you just need to set io.rancher.service.external_dns to never and for that to never come up and always to always come up

**Comment by aznamier** [comment]
So I would propose that external-dns service would have another optional setting indicating required host labels. For the host to be propagated it would have to have a matching label.

That would solve the problem of Route53 internal and external hosted zones used at the same time.
Right now my setup is that we have:
- internal AWS zone where hosts are assigned internal ip addresses that should be available from internal Route53 DNS

- external AWS zone where hosts are assigned external ip addresses that should be available from External Route53

Ideally we could just deploy two rancher external-dns containers where internal would propagate only services from host of matching label (eg: internal) and external one would propagate external ips only from external host.

So for example: 
Rancher external-dns preference would be:
rancher.io.external-dns.required.host.label=mylabel

and setting on host:
rancher.io.external-dns.required.host.label=mylabel

Then if we have a match and we can propagate only certain hosts to certain Route53 hosted zones.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
