### ISSUE TITLE
[BUG] Rancher after executing backup in different upgraded cluster goes 503

### ISSUE THREAD

**Issue by rgrishi23** [rancher/rancher#45598]
**Rancher Server Setup**
- Rancher version: 2.6.3
- Installation option (Docker install/Helm Chart): helm 
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):eks
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: 2.8.3
* Hosted = EKS
 * Infrastructure Provider =AWS

**User Information**
- What is the role of the user logged in? (Admin)

Issue - 
I have restored the backup into another Rancher cluster which is at 2.6.3 with a slight url changes and upgraded version 2.8.3 in eks 1.28. The Backup deletes the pod and now no pods is created. I cannot find any relevent logs, But logs in rancher-backup pods show - 
restoreResource: Restoring kubeconfig-u-******* of type management.cattle.io/v3, Resource=tokens with multiple namespaces 

To Reproduce -
Take a backup in a Rancher cluster and save it in S3 bucket.
Create a new rancher cluster with a slight changed url with newer version.
Upload the backup for the restore.

**Expected Result**
all the data restored in the new cluster

**Comment by bpedersen2** [comment]
Check https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/backup-restore-and-disaster-recovery/restore-rancher, you cannot restore to a different version. 

See also the correct flow for migrating to  a new cluster: https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/backup-restore-and-disaster-recovery/migrate-rancher-to-new-cluster 

You should : 1)  first  create the  restore
2)  then install  the same rancher version
3) then upgrade rancher
