### ISSUE TITLE
[RFE] 1.29 support

### ISSUE THREAD

**Issue by yybht155** [rancher/rancher#45597]
Please tell me when the k8s1.29 support plan will be released. This is a matter of concern. Thank you.

**Comment by PT-GD** [comment]
This appears to be being tracked in https://github.com/rancher/rancher/issues/43110

**Comment by PT-GD** [comment]
@yybht155 https://github.com/rancher/rancher/releases/tag/v2.9.0 supports 1.29 and the chart has been released in rancher-latest

**Comment by snasovich** [comment]
Closing as duplicate
