### ISSUE TITLE
[RFE] [rancher-monitoring] Provide an easy solution to enable the Prometheus ingress

### ISSUE THREAD

**Issue by Woovie** [rancher/rancher#45596]
**Is your feature request related to a problem? Please describe.**
In scenarios where you may want to connect rancher-monitoring's provided Prometheus instance to an external service, say a Grafana instance that you already have, you have to manually configure the YAML. The utility of Prometheus is fairly high, and there's many tools that interact with it.

**Describe the solution you'd like**
When performing initial deployment of rancher-monitoring or clicking Upgrade, a simple checkbox post the "Customize Helm options before install" to enable the ingress and field to define a hostname would be adequate.

**Describe alternatives you've considered**
Manually configuring the instance can be troublesome if you are not familiar with the Prometheus chart, let alone the Rancher modified variant. It would provide simplistic deployment of a useful feature that otherwise can be more difficult to enable.

**Comment by bpedersen2** [comment]
Just configuring an ingress would not be a good solution, as you also need access control configured, and that would depend on your infrastructure anyway.

**Comment by Woovie** [comment]
Fair point, it is definitely a lot more complex than it would appear at surface level. I did not thoroughly dig into the Prometheus side of this issue.

**Comment by bpedersen2** [comment]
For running an external grafana instance  I would consider using an extra backing store (e.g. mimir) and just configure remote write on the internal prometheus instance (this is possible via the helm chart).

**Comment by Woovie** [comment]
It's still relevant. This issue still sees an ask quite often from users.
