### ISSUE TITLE
Suggestions for external lb: Free netscaler

### ISSUE THREAD

**Issue by Frintrop** [rancher/rancher#4560]
Citrix netscaler vpx can be setup in a free version with free HA option.
Enabled in free license model are also dns based service group for loadbalancing with autoscaling:
Netscaler will resolve a dns entry and all resolved ip´s will be service nodes for the binded virtual service.
I think there is not more much configuration needed to use netscaler with rancher as external ha loadbalancer! 

http://docs.citrix.com/en-us/netscaler/11/traffic-management/load-balancing/load-balancing-manage-large-scale-deployment/autoscale-dns-service-group.html

Netscaler VPX is available on premise ( we are running it on vmware) and also as bring-your-own-(free)-license ami in amazon aws. ( other cloud providers unknown.)

Maybe you only need to implement a dummy loadbalancer provider in your external-lb repository ?

Also Citrix has dockerized his netscaler. I don´t know if there is also a free version, but maybe an option for complex or enterprise scenarios in rancher as internal lb?

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
