### ISSUE TITLE
add helm chart variable to set agent-tls-mode setting

### ISSUE THREAD

**Issue by MbolotSuse** [rancher/rancher#45629]
depends on #45628.

**Comment by mallardduck** [comment]
This has a 2.9 branch PR ready here: https://github.com/rancher/rancher/pull/45522
Will back port down to 2.7 and 2.8 as well.

**Comment by mallardduck** [comment]
both 2.8 and 2.9 PRs are merged and ready to test.

**Comment by nickwsuse** [comment]
Verified on v2.9-head ID: `dd23578` ✅ 
----
### Fresh Install
1. agent-tls-source is correctly defaulted to `Strict`
2. The `--set agent-tls-source` flag does not throw any errors on usage
3. The `--set agent-tls-source` flag correctly sets the value of the agent-tls-source variable

### Upgrade
1. agent-tls-source is correctly kept as `system-store` on upgrade
2. The `--set agent-tls-source` flag does not throw any errors on usage
3. The `--set agent-tls-source` flag correctly sets the value of the agent-tls-source variable

**Comment by ericpromislow** [comment]
Same things I said for  #45938 - Isn't it supposed to be --set agentTLSMode=strict|system-store ?

**Comment by nickwsuse** [comment]
You're right, and looks like I used the correct flag when testing so I'm not sure where I got the agent-tls-source wording from when writing my comment. 

`helm install rancher rancher-latest/rancher --version 2.9.0-rc3 --namespace cattle-system --set hostname=<redacted> --set global.cattle.psp.enabled=false --set ingress.tls.source=secret --set rancherImageTag=v2.9-head  --set agentTLSMode=system-store`

`helm upgrade rancher rancher-latest/rancher --version 2.9.0-rc4 --namespace cattle-system --set hostname=<redacted> --set global.cattle.psp.enabled=false --set rancherImageTag=v2.9-head --set ingress.tls.source=secret --set agentTLSMode=strict`
