### ISSUE TITLE
Cleanup PSP-related Resources from Rancher-Charts

### ISSUE THREAD

**Issue by krunalhinguu** [rancher/rancher#45620]
To ensure compatibility with Kubernetes 1.29 and maintain security standards, we need to remove all Pod Security Policy (PSP) references from the rancher-chart in the r/r project. Although PSP mentions have been removed from [role_data.go]((https://github.com/rancher/rancher/pull/45380/commits/acf719f3cab0f7f6446cd476df69eb5ba3531406#diff-1233e0b4cb129841936b478407cce09e86417b3125fd9e68731243adec2d6003)), residual references may still exist in files like post-delete-hook-psp.yaml and post-delete-hook-cluster-role.yaml. We must thoroughly analyze and eliminate these remaining PSP references to align with Kubernetes 1.29.

https://github.com/rancher/rancher/blob/release/v2.9/chart/templates/post-delete-hook-psp.yaml
https://github.com/rancher/rancher/blob/a1c690ac47aa06d2206d71e2338f812a9d3b4267/chart/templates/post-delete-hook-cluster-role.yaml#L38

### Releated

- https://github.com/rancher/rancher/issues/43110

**Comment by pankajsqe** [comment]
PSP related resources have been removed from rancher chart such as "post-delete-hook-psp.yaml" and "psp_test.yaml" file has been deleted and additionally api-groups, resources and verbs value has been removed from "post-delete-hook-cluster-role.yaml" file.

Rancher : v2.9-head
chart : 2.9 charts
Cluster : v1.29.4+rke2r1
--set global.cattle.psp.enabled=true
