### ISSUE TITLE
[RFE] PrincipalID refactor

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#45624]
When an ADFS user logs into Rancher, under the hood they are assigned a principal ID from the ADFS system, but they are also assigned a Local ID within Rancher. That is, every user entity internally has a list of principal IDs, one from each auth provider that they could potentially use to log in. For most ADFS users, the Local ID isn't active (it has no password assigned) but it is still present in the system. The admin who set up ADFS is an exception, and can somewhat uniquely log in using either method.

When a project is created, Rancher needs to defer creating the initial owner binding, so it stores the username as part of the object. Later that "reconciled" to find the appropriate user. Currently, Rancher always prefers the Local ID when reconciling a user in this way, and this is what we see when re-opening the project. Strictly, this behavior is working as designed, since the Local ID points to the same user, and should grant permissions in the same way. But it does create a confusing user experience.

https://jira.suse.com/browse/SURE-6693

**Comment by samjustus** [comment]
see jira for design doc started by @nflynt

**Comment by pmatseykanets** [comment]
In the light of trying to keep the number of k8s objects to a minimum and desire #24323 to have multiple auth providers enabled at the same time, not sure if we want to follow the proposal of having a single user per auth provider.

**Comment by pmatseykanets** [comment]
More over having a separate user per principal ID IMHO doesn't seem to address the original issue.

**Comment by nflynt** [comment]
My original proposal was meant to address what seemed like a historical design quirk: a system designed to support multiple enabled auth providers, but which does not actually permit this meaningfully. It seemed that we were maintaining unnecessary complexity, and I sought to reduce this complexity by simplifying the User object.

If we **do** wish to enable multiple auth providers, and it sounds like we do, then we should not implement this proposal. Quite the opposite really: Users will need to keep a list of their enabled AuthProvider PrincipalIDs, and the UI will need to correctly present this state to end users and admins.
