### ISSUE TITLE
Dynamic drivers are being saved incorrectly

### ISSUE THREAD

**Issue by jifeon** [rancher/rancher#4563]
I installed rancher, created one environment and add DO node successfully yesterday. Today I cannot create another node on different new environment using absolutely the same credentials.

What I do:

1. go to infrastructure -> add host
2. ![image](https://cloud.githubusercontent.com/assets/384223/14822537/c4d29260-0bd7-11e6-9e75-fa2165647078.png)

What I get:

1. Silence on DO
2. Infinite in progress ![image](https://cloud.githubusercontent.com/assets/384223/14822580/ea483d38-0bd7-11e6-844c-eeb18d3fe9d0.png)
3. 

```
root@Rancher:~# docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                            NAMES
579ae428dbd5        rancher/server      "/usr/bin/s6-svscan /"   5 days ago          Up 5 days           3306/tcp, 0.0.0.0:80->8080/tcp   big_noyce

root@Rancher:~# docker logs 579ae428dbd5
```
see this [gist](https://gist.github.com/jifeon/2c680dd40180ee6dc43bf3d87f0cfc02)

Last lines in logs

```
2016/04/26 10:25:08 http: proxy error: net/http: request canceled
time="2016-04-26T10:29:51Z" level=error msg="Error parsing token." error="token is expired" 
```

have been written several hours ago.

Pls help me to debug the problem.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.0.1` Cattle: `v0.159.7` UI: `v1.0.5` |
|Access|`github` `admin`|
|Route|`authenticated.project.help`|

**Comment by jifeon** [comment]
I've stopped and started `rancher/server` container and now I always get this error:

![image](https://cloud.githubusercontent.com/assets/384223/14823557/a49dc362-0bdb-11e6-9efe-45105155daf2.png)

```
time="2016-04-26T15:19:44Z" level=info msg="Creating Machine" eventId=293d271f-9f99-4ae0-a7aa-b7ae36a7268c resourceId=1ph14 
time="2016-04-26T15:19:44Z" level=info msg="Cmd slice: [create -d digitalocean --engine-install-url https://releases.rancher.com/install-docker/1.10.sh Databases]" 
time="2016-04-26T15:19:44Z" level=info msg="stderr: Error setting machine configuration from flags provided: digitalocean driver requires the --digitalocean-access-token option" resourceId=1ph14 
time="2016-04-26T15:19:44Z" level=info msg="starting cleanup..." machine name=Databases 
time="2016-04-26T15:19:44Z" level=error msg="Error processing event" err="Error setting machine configuration from flags provided: digitalocean driver requires the --digitalocean-access-token option" eventId=293d271f-9f99-4ae0-a7aa-b7ae36a7268c eventName="physicalhost.create;handler=goMachineService" resourceId=1ph14 
```

but I specify DO API token in UI everytime

**Comment by will-chan** [comment]
could be related to how dynamic drivers are being generated.

**Comment by vincent99** [comment]
There is a race-condition or thread-unsafe operation which results in the schema for one driver being saved as that of another.

In my case the `digitaloceanConfig` ended up containing the `resourceFields` of the `genericConfig` driver.  Then none of the fields (like `accessToken`) are in the schema, so they're not saved to the DB, so they're not passed down to the driver, and it complains that the option is mandatory.

**Comment by cuiyz** [comment]
VShpere works not correct either.

**Comment by vincent99** [comment]
@cuiyz This can happen to any (or all) drivers.  Restart the server container.

**Comment by cuiyz** [comment]
@vincent99 Thanks Vincent, and when will be the V1.1.0 got released?

**Comment by sangeethah** [comment]
Tested with  rancher-server version - v1.1.0-dev2-rc4

Able to add Digital Ocean machines multiple times without any problems. Also tried adding Digital ocean after restarting rancher-server multiple times. Did not encounter any issues.
