### ISSUE TITLE
[Vulnerability] missing cookie "Samesite" attribute and Scope

### ISSUE THREAD

**Issue by rajan2** [rancher/rancher#45649]
**Rancher Server Setup**
- Rancher version: 2.8.4
- Installation option (Docker install/Helm Chart): helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): AKS
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: 1.28.5
- Cluster Type (Local/Downstream): local
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information** admin
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:

**Describe the bug**

During vulnerability scan, there 2 vulnerabilities found and are related to R_SESS cookie,

#### R_SESS cookie is defined  without  `SameSite` attribute
**Recommendation**
It is recommended the “SameSite” flag to be added to all “Set-cookie” headers. This can be usually done in the same section where the cookie is issued (either in the  application source code, or within the web server configuration, depending on where the session cookie is generated and managed).

#### R_SESS cookie scope is set to `/`
**Recommendation:** 
It is recommended to limit the cookie scope to the application directory, i.e. dashboard. Setting cookie scope to root directory is not advised and should be avoided whenever possible.

**To Reproduce**

**Result**
Failed during a vulnerability scan
**Expected Result**

Vulnerabilities related to cookies should present

**Screenshots**

![image](https://github.com/rancher/rancher/assets/10000154/8fe53dcf-ebf1-41fb-9fe0-7b0f787ac4c1)
![image](https://github.com/rancher/rancher/assets/10000154/974b6dd4-9c79-4876-923c-aa4aeb246fb7)

**Additional context**

**Comment by pjbgf** [comment]
@rajan2 deleting security sensitive issues from the public repository. Please contact us via the official private channels stated at: https://github.com/rancher/rancher/security/policy
