### ISSUE TITLE
[BUG] Provisioning RKE1 node-driver cluster fails when extra_env is used for the kube-api service

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#45645]
**Rancher Server Setup**
- Rancher version:  v2.8.4 and 2.8-head 
- Installation option (Docker install/Helm Chart): either 
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details: n/a

**Information about the Cluster**
- Kubernetes version: any RKE1 k8s version 
- Cluster Type (Local/Downstream): Downstream RKE1 
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):  any  Infrastructure Provider

**User Information**
- What is the role of the user logged in?  Admin/Cluster Owner 

**Describe the bug**

If we provision or edit an RKE1 node-driver cluster and set the `extra_env` for the `kube-api` server, Rancher will fail to create or update the cluster with an error message like below 

`cluster health check failed: Failed to communicate with AP| server during namespace check: Get "https://xxx.xxx.xxx.xxx:6443/api/v1/namespaces/kube-system?timeout=45s": dial tcp xxx.xxx.xxx.xxx:6443: connect: connection refused:[controlPlanel
Failed to upgrade Control Plane: [[Failed to create [kube-apiserver] container on host [xxx.xxx.xxx.xxx]: Failed to create Docker container [kube-apiserver] on host [xxx.xxx.xxx.xxx]: Error response from daemon: invalid environment`

As a result, it is impossible to set the `extra_env` for the `kube-api` server. 

**To Reproduce**

- create or edit an RKE1 node-driver cluster
- edit the cluster as YAML to set the `extra_env` for `kube-api`
- create or save 

<img width="393" alt="Screenshot 2024-05-30 at 12 15 17 PM" src="https://github.com/rancher/rancher/assets/6218999/37691aa4-4619-40f5-9c71-2bc67fd2e4dd">

**Result**

The cluster will stuck in updating

<img width="1576" alt="Screenshot 2024-05-30 at 12 13 20 PM" src="https://github.com/rancher/rancher/assets/6218999/7c53449b-45be-4010-8a8f-c3cbc7da2328">

**Expected Result**

The creation or update should succeed. 

**Screenshots**

**Additional context**

This is a bug in RKE v1.5.9. See https://github.com/rancher/rke/issues/3587

To workaround the bug, you need to remove the `extra_env` from the cluster configuration.

**Comment by jiaqiluo** [comment]
waiting for RKE RC

**Comment by jiaqiluo** [comment]
This can be validated with the latest v2.9-head tag 

Please check the issue description for steps for reproduction and validation. We'd like to cover both creating a new cluster and updating the existing one.

**Comment by slickwarren** [comment]
tested the following on v2.9-head (d2fa8a7d6116c48a814ee7983af522d614461e49):
* provision an rke1 cluster with no extra_env -- pass
* provision an rke1 cluster with extra_env -- pass
* upgrade an rke1 cluster with no extra_env -> with extra_env -- pass
* upgrade an rke1 cluster with extra_env -> update extra_env -- pass
* upgrade an rke1 cluster with extra_env -> remove extra_env -- pass

tested on both 1.29 and 1.30
