### ISSUE TITLE
Services in stack randomly disappear

### ISSUE THREAD

**Issue by eguswes** [rancher/rancher#4564]
When I update a service inside my stack some of the other services disappear from the GUI, when I reload the stack page they return but it's anoying since I work alot with management of different services inside several stacks.

For example, I run upgrade, when it's ready some other services are just removed from the list of services. I need to hit F5 to get them back.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.0.0` Cattle: `v0.159.2` UI: `v0.100.3` |
|Access|`Disabled`|
|Route|`authenticated.project.help`|

**Comment by deniseschannon** [comment]
I am unable to reproduce. I am running v1.0.1.

After I click on upgrade on a service and click on "Upgrade", I'm brought directly into the detailed stack page. In the detailed stack page, I see all the services.

Is this a cattle environment? Do you have other environments? 

What Docker version? What type of hosts are you running?

**Comment by eguswes** [comment]
Hi!

All cattle, docker 1.10.3 on RHEL 7

How many services do you have in your stack and how many stacks do you have when you try to reproduce it? We have about 5-10 services with several containers and an number of service aliases and external services and 6 stacks.
We’re four-five people working with the gui at the same time and we all experience it when we perform a change on a service, can be deactivate as well. Sometimes it’s fine, and sometimes it occurs every time. In both Firefox and chrome, have not tried IE.

Do you think that we shall upgrade from 1.0.0 to 1.0.1?

/Gustaf

**Comment by deniseschannon** [comment]
So, the services are disappearing from everyone else's GUI while you are doing an upgrade on to the service?

**Comment by eguswes** [comment]
Can I send screenshots? No, when I press play stop upgrade is finished a service research because it's unhealthy. Anything that will cause the gui to update remiss half of the services and the scroll is removed. I need to refresh to get them all back. But if something updates it, they will go away again and again and so on. It's all happening on my screen. The others experience the same thing on their own screens.

/Gustaf


---- Denise skrev ----


So, the services are disappearing from everyone else's GUI while you are doing an upgrade on to the service?

**Comment by deniseschannon** [comment]
Can you capture a screenshot from someone else's screen in regards to the missing services? For example, you perform the upgrade on your screen and take a screenshot on someone else's UI at the different stages of upgrades, so I could see what you mean by missing services? 

I'm assuming that everyone is logged in their own account?

**Comment by eguswes** [comment]
Ok. Guess I confused you a bit, it’s always on my screen that it happens, or on the persons screen who performs an operation. We use the same account, we don’t use extra authorization since it’s a closed environment with limited access.

How to reproduce, have a lot of services, service aliases and containers, press upgrade or stop or have a service that crashes and restarts itself. The list will be shortened

[cid:image001.jpg@01D1A9C8.76382780]

[cid:image002.jpg@01D1A9C8.76382780]


/Gustaf

**Comment by deniseschannon** [comment]
The images didn't come through to Github (as you seemed to have sent them via e-mail). 

Oh, I didn't realize that you use the account (assuming same username). There may be some strange sync issues if you're both using the same account. We don't really test out that use case where 2 people use 1 account  on separate browsers.

**Comment by deniseschannon** [comment]
@eguswes If you're able to have your users have different accounts and still see this issue, please re-open. As I mentioned earlier, we don't really test out having 2 people using 1 account at the same time, so there could be strange scenarios of refreshes in the screen that may be occuring.

**Comment by vincent99** [comment]
This sounds an issue where the subscription socket didn't have a limit set so it was defaulting to 100 and if there were more than 100 things (apparently services in this case) the rest would be "lost".  That was just fixed in master for release in 1.1
