### ISSUE TITLE
[Backport v2.8] rancher machines are not removed from the cluster after actual worker nodes removed

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#45647]
Backport for https://github.com/rancher/rancher/issues/43686

**Comment by johnwc** [comment]
@snasovich @Josh-Diamond Can this be explained in more detail on what object we are supposed to be setting this annotation to, with examples? local cluster, downstream clusters, etc???

**Comment by snasovich** [comment]
@johnwc , it's objects in the local cluster, see below from the release notes - hopefully it's enough to get you going:
> A new annotation `rke.cattle.io/delete-missing-custom-machines-after` exists to enable machine deletion on corresponding Node deletion. Users can set the annotation to the `clusters.provisioning.cattle.io/v1` or `rkecluster.rke.cattle.io` objects, which after being set deletes missing machines after a specified duration (example: `rke.cattle.io/delete-missing-custom-machines-after: '5s'`). See [#45647](https://github.com/rancher/rancher/issues/45647).

**Comment by johnwc** [comment]
@snasovich I already read that, and it doesn't help. On what exact object is this annotation supposed to be applied? Can you give an example kubectl edit command? As far as I can see for kinds of `cluster.provisioning.cattle.io/v1`, there are objects for each downstream cluster as well as one for the local cluster. And, I do not see any kinds that are `clusters.provisioning.cattle.io/v1` but I do see `cluster.provisioning.cattle.io/v1`.

**Comment by snasovich** [comment]
@johnwc , for each downstream cluster there is a corresponding `cluster.provisioning.cattle.io` object in local cluster so you will want to annotate those objects for clusters you want to enable this functionality for. Note there is currently no global setting or anything to enable it across the board (outside of updating all clusters you have and ensuring newly created clusters get this annotation as well).

I believe the below command should work to add annotation for provisioned RKE2 cluster with a given name (`cluster-name`):
```
kubectl annotate cluster.provisioning.cattle.io cluster-name -n fleet-default rke.cattle.io/delete-missing-custom-machines-after=5s
```

Hope this helps.
