### ISSUE TITLE
Haproxy fails to start

### ISSUE THREAD

**Issue by timothysnave** [rancher/rancher#4565]
Rancher Version: 0.4.4

Docker Version: 1.10.1

OS: CentOS 7

Steps to Reproduce:
Create a load balancer exactly as described in the documentation for the "lets-chat" app

Results: 
Load balancer service tries to start, goes blue and says "Activating", then after a few seconds it turns yellow and says "Initializing", and after a few more seconds turns green and says "Active." However, inside the service's only (so far) container, haproxy has failed to start. This is the result when I try to start haproxy manually:

root@a044e092f5df:/# haproxy -f /etc/haproxy/haproxy.cfg
[WARNING] 116/153903 (412) : config : 'option forwardfor' ignored for proxy 'default' as it requires HTTP mode.

And haproxy fails to start. If I delete the 'option forwardfor' line from the global config in the haproxy.cfg file, that warning no longer appears, but haproxy still fails, just silently.
 

Expected:
Haproxy should start and function as normal.

To be fair, I'm not sure that I set haproxy up completely correctly. I did almost nothing other than setting the ports and selecting my lets-chat service. Is that all it's supposed to take? 

Thanks in advance for any input you have.

**Comment by deniseschannon** [comment]
Can you provide the docker-compose.yml of your stack of your lets chat application?

How many hosts do you have? Do you have cross host communication working (if more than 1 host)? Are you able to exec into 1 network agent and ping the `10.42.x.x` IP of another network agent?

**Comment by timothysnave** [comment]
Oh I'm sorry, I forgot to update this. I actually got it running. What I had to do was bind haproxy's listening port to <ip>:<port> rather than just <port> - after I did that, it started behaving exactly as intended. I'm perfectly fine with configuring it this way (actually prefer it, now that I think about it) so I won't be needing help after all. Thanks, though!

**Comment by NeillGiraldo** [comment]
@timothysnave Could you please explain what ':' and '-' means? thanks

**Comment by vincent99** [comment]
@NeillGiraldo their test was in angle brackets and interpreted as HTML; changed..
