### ISSUE TITLE
[Backport v2.8] Reduce reliance on Rancher Git mirror for running CI tests

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#45677]
Backport of https://github.com/rancher/rancher/issues/45676 to `release/v2.8` branch.

Note this will require backporting https://github.com/rancher/rancher/pull/43530 to `release/v2.8` first if the approach suggested on the referenced issue is chosen.

**Comment by snasovich** [comment]
Currently blocked on getting https://github.com/rancher/rancher/pull/43530 backported to `release/v2.8`.
@olblak @kkaempf , is this something your team can take care of or there are concerns with migrating that improvement to v2.8 line of releases?

**Comment by weyfonk** [comment]
> Currently blocked on getting #43530 backported to `release/v2.8`. @olblak @kkaempf , is this something your team can take care of or there are concerns with migrating that improvement to v2.8 line of releases?

See #45699.

**Comment by snasovich** [comment]
Moved to "Actively QAing" while builds are running. Will close as soon there is confirmation CI stability is not negatively affected by this change.

**Comment by snasovich** [comment]
Closing as there are no known reports of this change causing CI issues.
