### ISSUE TITLE
Haproxy doesn't start because of errors

### ISSUE THREAD

**Issue by berts86** [rancher/rancher#4567]
When I start Haproxy on my Synology NAS (DSM 6), I get errors:

`root@NAS: /var/packages/haproxy/scripts/start-stop-start start`

    Starting HAProxy ...
    [ALERT] 116/180520 (24945) : parsing [/usr/local/haproxy/var/haproxy.cfg:34] : 'bind :5443' : unable to load SSL private key from PEM file '/usr/local/haproxy/var/crt/default.pem'.
    [ALERT] 116/180520 (24945) : Error(s) found in configuration file : /usr/local/haproxy/var/haproxy.cfg
    [ALERT] 116/180520 (24945) : Proxy 'https': no SSL certificate specified for bind ':5443' at [/usr/local/haproxy/var/haproxy.cfg:34] (use 'crt').
    [ALERT] 116/180520 (24945) : Fatal errors found in configuration.

Do you have a solution for this?

**Comment by berts86** [comment]
see https://github.com/haproxy/haproxy/issues/67

**Comment by deniseschannon** [comment]
Are you starting an HAproxy container or trying to use our load balancer container which uses haproxy software?

**Comment by andrewmclagan** [comment]
Is it possible to use the "special" rancher HAProxy containers locally for development? seems not?

**Comment by deniseschannon** [comment]
@andrewmclagan Is there a specific reason why you're trying to use the rancher HAproxy container outside of Rancher? It is designed specifically to work with Rancher, so I don't believe it's possible.

**Comment by andrewmclagan** [comment]
@deniseschannon no after more thought we are using a custom HAProxy container in dev

**Comment by deniseschannon** [comment]
@andrewmclagan If you have further questions, please open a new issue. 

@berts86 If you can provide more details (like if this error is cause of the Rancher load balancer (using HAproxy software) or your own HAproxy container, please re-open.
