### ISSUE TITLE
[RFE] Allow specifing a securityContext in rancher helm chart

### ISSUE THREAD

**Issue by kisv-SOPTIM** [rancher/rancher#45698]
**Is your feature request related to a problem? Please describe.**
Currently, the rancher helm chart cannot be installed in a cluster using cri-o in its default configuration, as it requires the MKNOD capability. Please see the following issue: https://github.com/rancher/rancher/issues/27160

**Describe the solution you'd like**
I would like the rancher helm chart to expose the option to to set the securityContext of the deployment, to add the required capability manually, as described here: https://github.com/rancher/rancher/issues/27160#issuecomment-793999996
This would allow installing rancher, without requiring patches to the helm chart, or modification of the default cri-o capabilities.

**Describe alternatives you've considered**
We are currently applying a patchto the helm chart, to adjust the capabilities. Its also possible to modify the global cri-o configuration.

**Additional context**
/

**Comment by nicleary** [comment]
Is it possible for this and the initial PR to be re-revisited? This would be extremely helpful for running in secured environments
