### ISSUE TITLE
How do I can manage load balancer tagets via api

### ISSUE THREAD

**Issue by clicman** [rancher/rancher#4570]
I want to dynamically getList add and remove targets on load balancer. Is any api exposed for it?
![image](https://cloud.githubusercontent.com/assets/1079535/14845469/4055506e-0c80-11e6-9fae-7fcdb1649ed5.png)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.0.1` Cattle: `v0.159.7` UI: `v1.0.5` |
|Access|`github` `admin`|
|Route|`service.containers`|

**Comment by clicman** [comment]
Go it!
To get: https://rancher.clicman.ru/v1/serviceconsumemaps?limit=-1
To set: {{RANCHER_URL}}/v1/loadbalancerservices/1s4/?action=setservicelinks

Set request is simple and clear, but Get is to complicated.

It will be good to see simple load balancer configuration... maybe in rancher-cli?

**Comment by clicman** [comment]
An example of implementation [here](https://github.com/clicman/rancher-cli-addons)

**Comment by deniseschannon** [comment]
Are you still looking for help on this? I wasn't clear on what the current request is.

**Comment by clicman** [comment]
Oh sorry I should close this issue. Iveimplemented my own cli :)
