### ISSUE TITLE
[BUG] GlobalRole with just `inheritedClusterRoles` and no `rules` doesn't give any permissions

### ISSUE THREAD

**Issue by JonCrowther** [rancher/rancher#45714]
**Rancher Server Setup**
- Rancher version: 2.8.2, 2.8.4, 2.9-latest
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version:
- Cluster Type (Local/Downstream): both
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): imported k3s

**Describe the bug**

When you create a global role with `inheritedClusterRoles` but no `rules` and assign it to a user, the `inheritedClusterRoles` don't get applied. The user can't make use of the permissions. 

**To Reproduce**

1. Create a global role like the following: 
```
apiVersion: management.cattle.io/v3
inheritedClusterRoles:
  - nodes-view
kind: GlobalRole
metadata:
  name: test-gr
```
2. Assign it to a user (along with user-base so they can log in)
3. Log in as that user

**Result**
The user can't see nodes in the UI when looking at the downstream cluster

**Expected Result**
The user should be able to log in, see the downstream cluster in the UI and be able to see Nodes for that cluster.

**Comment by stalin4suse** [comment]
SURE-8537

**Comment by JonCrowther** [comment]
Could not reproduce. With that globalrole applied I am able to get nodes on a downstream cluster and view the nodes in the UI.
