### ISSUE TITLE
[RFE] Enhance the secret-synchronization controller from Rancher's management cluster -> downstream clusters 

### ISSUE THREAD

**Issue by thatmidwesterncoder** [rancher/rancher#45718]
**Is your feature request related to a problem? Please describe.**
As a user I would like to manage certain resources (e.g. secrets) in downstream clusters from my rancher management cluster.

A key usecase for this would be creating clusters for developers that will always need a certain secret in the app's namespace. Currently I need to create automation that 1) creates the cluster, then 2) gets the kubeconfig and creates the resource in the downstream cluster which is complex. I would prefer to just create a secret in the upstream cluster with a specific annotation and then rancher would create and manage that secret in the specified downstream cluster. 

**Describe the solution you'd like**
I would like to create a cluster resource and then create a `v1.Secret` resource with a specific annotation `provisioning.rancher.io/sync-to-cluster: foobar`. This secret will be created in the downstream cluster, and then updated anytime the upstream cluster gets updated. 

**Describe alternatives you've considered**
The main alternative is one I've already discussed - more complex automation that would need to fetch kubeconfigs and create resources manually. This adds complexity because I won't be able to just use the rancher-cli/kubectl or a single terraform module.

The other option is to use the `machineSelectorFiles` field on the cluster object to create a manifest on disk which would get applied by RKE2 on startup. Steps are here:
- Create a secret in the upstream cluster to store the credentials, the contents of this secret should be … another secret CR manifest (the secret to be created).
- Edit the cluster yaml and update the `machineSelectorFiles` field to refer to the secret, the path should be `/var/lib/rancher/rke/server/manifests/foo-dev-secret.yml`
- Provision as normal

The main issue with this approach is the potentially secret data is now stored on disk in perpetuity for the life of the cluster - which even though the files are owned by `root:root` and have `0600` permissions will be a huge attack vector if someone has root access to the nodes. 

**Additional context**

Related: SURE-5434

**Comment by bpedersen2** [comment]
Why not just use  fleet to handle this? Create a fleet repo and configure   the clusters and resources you need on all/some downstream clusters?

**Comment by gaktive** [comment]
2.9.x UI backport: https://github.com/rancher/dashboard/issues/11920

**Comment by LucasSaintarbor** [comment]
@Sahota1225  May you provide a summary of what should be added to the 2.8.9 Release Notes for this new feature? Thanks!

**Comment by susesgartner** [comment]
Ticket #45718 - Test Results - ✅ 
---
 
| Scenario | Test Case | Result |
|---|---|---|
| 1. | CSI/CPI provisioning check | PASS |
| 2. | Provisioning regression check | PASS |

---
Verified with HA Helm on Rancher `v2.10-f1aa9fb594e5b14578aff1cd5ddd2064be06eab1-head`:
---

Setup:
1. Create a Vsphere rancher HA setup
2. Enable the "provisioningprebootstrap" feature flag
 
Scenario 1: Verify CSI/CPI cluster provisioning
---
1. Fill out all info for a csi/cpi rke2 cluster
2. In csi/cpi set "generate cloud secret" to true
3. Provision the cluster
4. Verify that the cluster comes up and all pods are in a healthy state.
 
Results: The cluster provisions and all verifications passed
 
---
 
Scenario 2: Provisioning regression check
---
1. Provision an RKE1/RKE2/K3s cluster
2. Verify that they come up active and all pods are in stable state.
 
Results: all clusters came up and all pods were in a stable state

NOTE: additional regressions are being performed as part of release testing.
