### ISSUE TITLE
Racher service start read-only

### ISSUE THREAD

**Issue by elerion** [rancher/rancher#4572]
It's possible to run a service with read only option ?

| application | version |
|---------------|-----------|
|Rancher Version | 1.0.1 |
|Docker Version| 1.11 |
|OS| centos7|

**Comment by deniseschannon** [comment]
You can't do so for individual services, but you could make specific users have read only permissions. 

http://docs.rancher.com/rancher/configuration/environments/#read-only

**Comment by deniseschannon** [comment]
@elerion If there are further questions, please re-open and let me know.
