### ISSUE TITLE
rancher-logging using deprecated fluentbit field in logging crd

### ISSUE THREAD

**Issue by joshmeranda** [rancher/rancher#45722]
The current initial [Logging](https://kube-logging.dev/docs/configuration/crds/v1beta1/logging_types) resource deployed by rancher logging is utilizing the deprecated [fluentbit](https://kube-logging.dev/docs/configuration/crds/v1beta1/logging_types/#loggingspec-fluentbit) field. This field will be removed in future releases and should be replaced as it will become a blocker for the next logging rebase.

**Comment by joshmeranda** [comment]
Work for this is done in https://github.com/rancher/rancher/issues/46035. This issue needs no specific testing other than the regressions done for that one.

**Comment by pankajsqe** [comment]
Regression test has been passed on rancher v2.9.1 with rancher-logging:104.1.0-rc1+up4.8.0. PFA

![Image](https://github.com/user-attachments/assets/005458a1-354c-4d7c-81f6-e54b92d31945)
![Image](https://github.com/user-attachments/assets/09cb66c0-c700-4f09-b6b0-f5d3d0a43d07)
