### ISSUE TITLE
Confirm upgrade after cancel upgrade

### ISSUE THREAD

**Issue by kaos** [rancher/rancher#4573]
Rancher Version: 1.0.1

Docker Version: 1.10

OS: rhel7.2

Steps to Reproduce: 

Create service. Upgrade service (with a scheduling rule that can't be satisfied), Cancel upgrade.

Results: 

I have the option to Finish or Rollback the upgrade.

Expected:

Go back to normal state without upgrade status, or have the option to "retry upgrade". As it is, I pressed "Finish Upgrade" to confirm my current (cancelled) state, and rancher went into upgrading again (I think) trying to commit the upgraded state that I had cancelled. This did not work (due to scheduling issues, which is why I canceled the upgrade) but there were no way to abort the Finishing upgrade state. (managed to get out of this by fixing the underlying scheduling issue, so I could upgrade back the original state once the first bad upgrade was complete).

**Comment by deniseschannon** [comment]
After cancelling an upgrade, you go to `Cancelled-Upgrade` state. In this state, you are still in the middle of choosing between upgrading or going back to your original definition. 

 If you "Rollback", you are still going back to your original service definition. If you "finish upgrade", you are restarting the upgrade.

There has been confusion in the intention of Rollback/Finish Upgrade when in `Cancelled-Upgrade` state. 

@alena1108 @vincent99 Any ideas on how we could clarify it for users in that state?

**Comment by kaos** [comment]
Well, the confusion is one thing, but as I pressed "finish upgrade" it did not restart the upgrade process afresh, but it seemed to skip ahead to a "finishing upgrade" state, which I could not cancel. Or, if that really was the state I was supposed to get, I'd suggest against being able to go directly from a cancelled upgrade state to a finishing upgrade state, as you'll then skip over the upgrade step (which is cancelable).

Also, it would be nice if the little "default action" button in a cancelled upgrade state was rollback rather than finish upgrade.. ;)

**Comment by alex88** [comment]
Just got the same issue, I canceled an upgrade since there was a typo in the new image, in the `Cancelled-upgrade` state I clicked the button near the 3 dots button and rancher deleted my old running containers and kept the new ones in error state. After that I had to delete the service and create it from scratch since the service was impossible to stop

**Comment by alena1108** [comment]
With Rancher 1.1.1, you will be able to cancel upgrade from finishing-upgrade state. So if something goes wrong, you can always recover by cancel-upgrade->rollback:

https://github.com/rancher/cattle/pull/1813

**Comment by sangeethah** [comment]
Tested with v1.1.1:

Create a service with scale 1.
Upgrade this service and set a scheduling rule that will not be satisfied ( like host must have a non existence label)

When upgrade is stuck in "upgrading" state , do cancel-upgrade->rollback.
Once rollback is done , service is back to "active" state. It has containers that was created before upgrade.
