### ISSUE TITLE
websocket connection in UI does not stay open

### ISSUE THREAD

**Issue by leoschweizer** [rancher/rancher#4574]
Steps to reproduce:

- Start a digitialocean droplet with CoreOS 1010.1.0 (fastest way to get Docker 1.10.3, I experienced the same symptoms with Ubuntu 14.04).
- Install Rancher `docker run -d --restart=always -p 8080:8080 rancher/server`
- Wait for it to finish and open the Rancher UI in a browser of your choice (I tried Firefox & Chrome on Windows 7).

The following can be observed in the JS console:
```
Connect socket for 1a5
Socket connect 1 to ws://.../v1/subscribe...
Socket 1 opened
Subscribe connected
Socket closed
Subscribe disconnected
Disconnect socket for 1a5
Socket 1 disconnect
Socket 1 disconnect
Socket connect 2 to ws://.../v1/subscribe...
Socket 2 opened
Subscribe connected (after 1 try, 1.119 sec)
Socket closed
Subscribe disconnected
Disconnect socket for 1a5
Socket 2 disconnect
Socket 2 disconnect
Socket connect 3 to ws://.../v1/subscribe...
Socket 3 opened
Subscribe connected (after 1 try, 1.117 sec)
Socket closed
Subscribe disconnected
Disconnect socket for 1a5
Socket 3 disconnect
Socket 3 disconnect
Socket connect 4 to ws://.../v1/subscribe...
Socket 4 opened
Subscribe connected (after 1 try, 1.123 sec)
Socket closed
Subscribe disconnected
Disconnect socket for 1a5
Socket 4 disconnect
Socket 4 disconnect
Socket connect 5 to ws://.../v1/subscribe...
Socket 5 opened
```
This will go on and on and on, roughly once per second.

A lot of the UI functionality is not working properly for me, and I suspect the websocket issue is the reason for that. Most notably, the Graphs are not working (similar to #4406, but I am running Docker 1.10.3!). Also, if I add a host in the infrastructure section, the host information does not update and I have to refresh the page manually.

Again, I only suspect that this is related to the websockets reconnecting incessantly,but it seems to be obvious.

---
```
docker info
Containers: 4
 Running: 2
 Paused: 0
 Stopped: 2
Images: 2
Server Version: 1.10.3
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.5.0-coreos-r1
Operating System: CoreOS 1010.1.0 (MoreOS)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.958 GiB
Name: coreos-2gb-fra1-01
ID: S4Q5:JEEI:65OX:GRF4:XVEX:3D2F:ETUL:4BN7:RHM4:O7QN:LXJ5:IIVM

```

| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.0.1` Cattle: `v0.159.7` UI: `v1.0.5` |
|Access|`Disabled`|
|Route|`hosts.index`|

**Comment by leoschweizer** [comment]
Update: this does not happen on OSX/Chrome, so this seems to be an issue with the specific setup of my Windows machine. I will try to identify the root cause and keep you posted.

**Comment by leoschweizer** [comment]
It turns out Kaspersky Endpoint Security was causing the problems. Sorry for the noise.

**Comment by digz6666** [comment]
@leoschweizer How did you resolved your issue with Kaspersky Endpoint Security? I've moved my application to trusted but its still blocking.

**Comment by vincent99** [comment]
A simple-ish backend solution would be to put the server behind SSL, then there's nothing for security tools to "inspect".  Unless it MITMs TLS connections to...

**Comment by leoschweizer** [comment]
@digz6666 we no longer use Kaspersky, since it caused numerous other problems as well. So unfortunately, I can't help you with that.

**Comment by digz6666** [comment]
@vincent99 Ok, I will try that. Thanks for the hint!
