### ISSUE TITLE
k8s 1.30 support for system-upgrade-controller

### ISSUE THREAD

**Issue by Sahota1225** [rancher/rancher#45745]
Add k8s 1.30 support for  system-upgrade-controller

**Comment by Josh-Diamond** [comment]
Ticket #45745 - Test Results - ✅ 
---

Verified on Rancher `v2.9-3c4ccdc5bc9fde3510089153b5ad58fdbe604880-head`:

| Scenario | Test Case | Result|
|---|---|---|
| 1. | Provision downstream RKE2 Node driver cluster w/ k8s 1.30 | ✅ |
| 2. | Provision downstream RKE2 Node driver cluster w/ k8s 1.29 => upgrade to k8s 1.30 | ✅ |
| 3. | Import standalone RKE2 cluster w/ k8s 1.29 => upgrade to k8s 1.30 | ✅ |

---

Scenario 1 - ✅ 
1. Fresh install of Rancher `v2.9-head`
2. Provision a downstream RKE2 AWS Node driver cluster w/ k8s `v1.30.2+rke2r1`
3. Once `active`, navigate to `Cluster Explorer > Workloads > Deployments` and observe `system-upgrade-controller`
4. Verified - SUC points to `rancher/system-upgrade-controller:v0.13.4`; as expected
5. Navigate to `Cluster Explorer > Apps > Installed Apps` and observe `system-upgrade-controller` chart
6. Verified - SUC chart points to `system-upgrade-controller:104.0.0+up0.7.0`; as expected

---

Scenario 2 - ✅ 
1. Fresh install of Rancher `v2.9-head`
2. Provision a downstream RKE2 AWS Node driver cluster w/ k8s `v1.29.6+rke2r1`
3. Once `active`, navigate to `Cluster Explorer > Workloads > Deployments` and observe `system-upgrade-controller`
4. Verified - SUC points to `rancher/system-upgrade-controller:v0.13.4`; as expected
5. Navigate to `Cluster Explorer > Apps > Installed Apps` and observe `system-upgrade-controller` chart
6. Verified - SUC chart points to `system-upgrade-controller:104.0.0+up0.7.0`; as expected
7. Upgrade k8s version to `v1.30.2+rke2r1`
8. Once `active`, navigate to `Cluster Explorer > Workloads > Deployments` and observe `system-upgrade-controller`
9. Verified - SUC points to `rancher/system-upgrade-controller:v0.13.4`; as expected
10. Navigate to `Cluster Explorer > Apps > Installed Apps` and observe `system-upgrade-controller` chart
11. Verified - SUC chart points to `system-upgrade-controller:104.0.0+up0.7.0`; as expected

---

Scenario 3 - ✅ 
1. Fresh install of Rancher `v2.9-head`
2. Provision a standalone RKE2 cluster w/ k8s `v1.29.6+rke2r1`
3. Import cluster created in step 2 into Rancher
4. Once `active`, upgrade cluster to k8s `v1.30.2+kre2r1`
5. Once `active`, navigate to `Cluster Explorer > Workloads > Deployments` and observe `system-upgrade-controller`
6. Verified - SUC points to `rancher/system-upgrade-controller:v0.13.4`; as expected
