### ISSUE TITLE
k8s 1.30 support for vSphere CPI

### ISSUE THREAD

**Issue by Sahota1225** [rancher/rancher#45746]
Add k8s 1.30 support for vSphere CPI

**Comment by Josh-Diamond** [comment]
Blocked by:
https://github.com/rancher/rancher/issues/46132

**Comment by Josh-Diamond** [comment]
bumping out to next milestone, as this issue is no longer targeted for `v2.9.0`

**Comment by Josh-Diamond** [comment]
https://github.com/rancher/rke2/issues/6334

**Comment by snasovich** [comment]
Should be ready to test once https://github.com/rancher/kontainer-driver-metadata/pull/1450 is merged

**Comment by Josh-Diamond** [comment]
Ticket #45746 - Test Results - ✅ 
---

Verified on Rancher `v2.9-419f7169084aaf1cceaeae2d6df5d4c227bd8a77-head`:

| Scenario | Test Case | Result |
|---|---|---|
| 1. | Provision a downstream RKE2 Vsphere Cloud Provider enabled cluster w/ k8s `v1.30.3+rke2r1` | ✅ |
| 2. | Provision a downstream RKE1 Vsphere Cloud Provider enabled cluster w/ k8s `v1.30.3-rancher1-1` | ✅ |

---

Scenario 1 - ✅ 
1. Fresh install of Rancher `v2.9-head`
2. Provision a downstream RKE2 Vsphere Cloud provider cluster w/ k8s `v1.30.3+rke2r1`
3. Verified - cluster successfully provisions; all pods `active`; CPI in use `rancher-vsphere-cpi:1.8.000`

---

Scenario 2 - ✅ 
1. Fresh install of Rancher `v2.9-head`
2. Provision a downstream RKE1 Vsphere Cloud provider cluster w/ k8s `v1.30.3-rancher1-1`
3. Verified - cluster successfully provisions; all pods `active`; CPI in use `rancher-vsphere-cpi:104.0.1+up1.8.1`
