### ISSUE TITLE
k8s 1.30 support for Harvester-CSI-driver 

### ISSUE THREAD

**Issue by Sahota1225** [rancher/rancher#45759]
Add k8s 1.30 support for Harvester-CSI-driver

**Comment by Vicente-Cheng** [comment]
Hi @Sahota1225, 

The PR has been created, but I'm not sure who should be the reviewer. Could you help with that?

cc @rebeccazzzz, @bk201

**Comment by Sahota1225** [comment]
@Vicente-Cheng - i see the PR has reviewers added and approved, can we get the PR merged?

**Comment by khushboo-rancher** [comment]
Validated with rke2 1.30.2 on Rancher 2.9.0-alpha5 - Passed
