### ISSUE TITLE
Windows 2016 support

### ISSUE THREAD

**Issue by kvaes** [rancher/rancher#4576]
Rancher Version:

Docker Version:

OS: Windows 2016

Steps to Reproduce: add Windows 2016 as a possible host

Results: manage docker on windows like on Linux 

Expected: heterogenous support

**Comment by rgauny** [comment]
+voting up
Needed for tons of corps... If first to market, it would generate a lot of revenue in enterprise level support. I would actually be on now to get ahead. I know my Corp would beta and help with right now and we are a fortune 50 company.

**Comment by kvaes** [comment]
FYI - There are already products moving into that segment ; containerX, Windocks, ...

**Comment by smw355** [comment]
Good news - looks like this made it into 1.2 goals.

**Comment by kvaes** [comment]
That is great news! Best news of june! ;-)

**Comment by gerich-home** [comment]
Hi, I see that the feature is assigned to October 28 milestone (1.2.0) and has 1st priority, but there are quite a lot items to complete by that date in this milestone.
Can I be sure enough that it will be available on October 28?

**Comment by will-chan** [comment]
We are planning an Experimental build for 1.2 but the fully implemented version won't come out until 1.3.

**Comment by markus2810** [comment]
Is the experimental support now available? How can I activate it?

**Comment by willseward** [comment]
Yes! Please provide instructions

**Comment by willseward** [comment]
@will-chan How do we access the experimental build?

**Comment by kleinsasserm** [comment]
+1
Would be nice to test things out. How are we enable to access the experimental build?

**Comment by kvaes** [comment]
Likewise. Big +1

**Comment by msutter** [comment]
+1
Do you have something to play with ?

**Comment by reneherrero** [comment]
+1
Also part of a fortune 50 company and very interested in getting access to the early bits supporting Windows Containers.

**Comment by kvaes** [comment]
@smw355 or @will-chan ; Can you guys comment on this? I see interest in various areas on this. Mainly to the lack of tooling around Windows containers... :)

**Comment by deniseschannon** [comment]
@kvaes We are adding Windows support as experimental in 1.3.

**Comment by kvaes** [comment]
@deniseschannon tnx for the feedback!

**Comment by deniseschannon** [comment]
@sangeethah Can you please file all bugs in new issues? When basic testing is complete, please close this ticket.

**Comment by sangeethah** [comment]
Tested with rancher-server version - v1.3.0-rc1 with catalog  "library" set to ```vnext``` branch in ```https://github.com/rancher/rancher-catalog```

Able to add "Windows Server 2016 Standard Evaluation" hosts successfully to rancher environment with orchestration set to "windows".

Able to launch containers in "nat" network and "transparent" network.

@kvaes  , Windows 2016 support will be available as experimental feature in rancher-server 1.3.0 release.

**Comment by kvaes** [comment]
@sangeethah 

Thanks for the feedback! I ran a test on my end... Deployed an ubuntu (16.04 TLS) on Azure as my rancher host, and chose the v1.3.0-rc1 version. Immediately, I noticed that there was something wrong with the CSS...

![2016-12-20 19_03_47-rancher](https://cloud.githubusercontent.com/assets/10435278/21362385/787b65b4-c6e8-11e6-8b3b-ae5a4189d95a.png)

Despite that, I disabled to default catalog and entered the one you indicated. 

![2016-12-20 19_08_01-nvidia geforce overlay](https://cloud.githubusercontent.com/assets/10435278/21362394/8032abbe-c6e8-11e6-86aa-902eb4f20e2d.png)

The windows part is shown there. 

![2016-12-20 19_08_26-rancher](https://cloud.githubusercontent.com/assets/10435278/21362398/839d9bc4-c6e8-11e6-9f8a-937a06079384.png)

What is the correct steps to proceed afterwards? The default way of adding (custom) hosts goes bad.

![2016-12-20 19_13_14-kvaesdocker02 - 52 166 184 243_3389 - remote desktop connection](https://cloud.githubusercontent.com/assets/10435278/21362381/75106334-c6e8-11e6-8327-2fe755fac3e1.png)

**Comment by kvaes** [comment]
The windows host was the "Windows 2016 with containers" that comes from the (Azure) gallery.

**Comment by tfiduccia** [comment]
@kvaes - there is currently a bug in the CSS for the UI.  Please select either the light or dark theme and refresh your browser.  That should fix it.
![image](https://cloud.githubusercontent.com/assets/11514927/21362541/11518414-c6a6-11e6-9844-43f8599a230c.png)

**Comment by kvaes** [comment]
@tfiduccia ; thanks, that part has been "fixed", euhr, "works" by choosing light or dark :)

**Comment by tfiduccia** [comment]
@kvaes - For your azure issue.  I setup a windows 2016 with containers.  I didn't have to install docker as it came with it.  Then I just ran the script from Add Host (You can find it in the the UI, infrastructure menu, Hosts, Add Host)  in the power shell and it seem to work fine.  Here is and example of what the script looks like that I ran:

New-Item -Path 'C:\Program Files\rancher' -Type Directory
Invoke-WebRequest -UseBasicParsing 'https://github.com/rancher/agent/releases/download/v0.3.0/agent.exe' -OutFile 'C:\Program Files\rancher\agent.exe'
& 'C:\Program Files\rancher\agent.exe' -register-service http://104.154.111.111:8080/v1/scripts/3EEE6A9B6C1080CD125E:1482256800000:sgs1EryhoZWAH82YGPPs72IjxnQ
Start-Service rancher-agent

**Comment by kvaes** [comment]
Nice! That part worked like a charm...

![2016-12-20 19_42_34-rancher](https://cloud.githubusercontent.com/assets/10435278/21363364/89c84ebe-c6ec-11e6-90f8-04cbf377a792.png)

Now I've added the vnext service

![2016-12-20 19_44_12-nvidia geforce overlay](https://cloud.githubusercontent.com/assets/10435278/21363405/c43790b4-c6ec-11e6-9983-15555300152b.png)

Do I cleanup the other ones?

**Comment by sangeethah** [comment]
@kvaes , Windows hosts can be added to only environment with "windows" orchestration.
When testing with rancher-server version - v1.3.0-rc1 , please follow these steps:

Add a  catalog "library" set to vnext branch in https://github.com/rancher/rancher-catalog
After this you will see "Windows" as one of the orchestration options in "Add Template" option.
You will need to wait for another 5 minutes for the "windows" environment template to be available.

Create a new environment using "windows" template.
You should now be able to add windows host in this environment .

You should be able to create services with "NAT" networking .
If you would want to create services with "transparent" networking, you will need to create transparent network on the host manually using  this command ```docker network create -d transparent transparent``` before you can create containers on this host.

**Comment by kvaes** [comment]
Okay, good to know on the environments. For my current test bed, the removal of the default services will have the same effect then.

Also, good to mention the transparent one! As I just faced that...

![2016-12-20 20_00_04-rancher](https://cloud.githubusercontent.com/assets/10435278/21364099/a64726b6-c6ef-11e6-9d63-490509288ea5.png)

And after the creation of that network (as you suggested), it works ; 

![2016-12-20 20_04_17-kvaesdocker02 1 - 13 95 92 244_3389 - remote desktop connection](https://cloud.githubusercontent.com/assets/10435278/21364110/b8643ea6-c6ef-11e6-8e18-e44030938a86.png)

Kudos on this (experimental) addin! I can imagine such a cross-platform integration is a challenge.

**Comment by sangeethah** [comment]
@kvaes , Thank you. we are planning to add this instruction  ```docker network create -d transparent transparent``` as the first step in the set of commands for running Rancher agent.

**Comment by kvaes** [comment]
For those interested, a blogged summary of the above ; https://t.co/1UHbk9Xjs3 ;-)

**Comment by willseward** [comment]
Thanks, @kvaes! I'll send this up the flag poll. We've been waiting for this feature!

**Comment by deniseschannon** [comment]
@kvaes The title of the blog v1.1.3 not v1.3.0. :)

**Comment by kvaes** [comment]
@deniseschannon thanks, updated! :)
