### ISSUE TITLE
Enable Encrypted SSL Private Keys

### ISSUE THREAD

**Issue by jwhitcraft** [rancher/rancher#4577]
Rancher Version: v0.63.1
Docker Version: 1.10.3
OS: Ubuntu 14.04

Steps to Reproduce:  

- Login as an admin user
- Goto Infrastructure -> Certificates
- Add new Certificate
- Enter a name
- Enter an encrypted private key
- Enter a certificate
- press Save

Results: 

- An error that says `The private key cannot be password-protected.`

Expected:

- It should save the certificate

**Comment by vincent99** [comment]
What would we do with it?  Make you exec into the haproxy container to enter a password?

**Comment by jwhitcraft** [comment]
This can be closed, my IT department gave me the password to decrypt the key.
