### ISSUE TITLE
Snapshots fail during creation in Sle Micro 6

### ISSUE THREAD

**Issue by susesgartner** [rancher/rancher#45815]
**Rancher Server Setup**
- Rancher version: v2.8-head
- Installation option (Docker install/Helm Chart): docker

**Information about the Cluster**
- Kubernetes version: 1.28
- Cluster Type (Local/Downstream): RKE2 node driver
Infrastructure Provider: vSphere 

**User Information**
- What is the role of the user logged in? Admin

**Describe the bug**
When attempting to create a snapshot the cluster fails with the following error: 
![image](https://github.com/rancher/rancher/assets/136753565/f7e4d1e8-2ddd-4bf7-bb9a-225d89419364)
Upon further investigation into the rancher-system agent logs I found the following error: 
`msg="error executing instruction 1: exec: \"rke2\": executable file not found in $PATH"`

I checked the /usr/local/bin and found that the rke2 binary was not present. 

**To Reproduce**
1. Create a downstream rke2 cluster using sle micro 6. 
2. Take a snapshot and watch the nodes to see the error displayed.

**Result**
An error occurs and the snapshot fails

**Expected Result**
The snapshot is taken.

**Comment by snasovich** [comment]
Likely will need RKE2 team involved on this.

**Comment by brandond** [comment]
I believe this has been reported in the past - when /usr/local is read-only or a mount point (btrfs subvolume on SLE), the rke2 binary is installed to /opt/rke2/bin instead of /usr/local/bin. Unfortunately, the various scripts generated internally by the Rancher planner don't include /opt/rke2/bin in the search path.

That was the source of this issue last time I investigated it, at least.

**Comment by cwayne18** [comment]
Would that be addressed by https://github.com/rancher/system-agent/pull/90 ?

**Comment by brandond** [comment]
Yes... which points back to https://github.com/rancher/rancher/issues/40624 which is the original report of this same issue from Rancher 2.7.1.

**Comment by susesgartner** [comment]
Ticket #45815 - Test Results - ✅ 
---
 
| Scenario | Test Case | Result |
|---|---|---|
| 1. | Snapshot create/restore | PASS |
| 2. | Snapshot restore k8s version | PASS |
 
---
Verified with HA Helm on Rancher `v2.9-head`:
---
 
Scenario 1: Snapshot create/restore
---
1.  Provision a Sle micro 6 downstream cluster
2. Create a snapshot
3. Verify that the snapshot is successfully created
4. Restore the snapshot
 
Results: the snapshot successfully restores
 
---

Scenario 2: Snapshot restore k8s version
---
1. Provision a Sle Micro 6 cluster
2. Take a snapshot
3. Upgrade the k8s version
4. Restore the snapshot
 
Results: The k8s version is successfully downgraded and all nodes remain in a stable state
