### ISSUE TITLE
[BUG] Need script | Secrets created via Fleet UI are not being backed up by BRO

### ISSUE THREAD

**Issue by mallardduck** [rancher/rancher#45812]
**Rancher Server Setup**
- Rancher version: 2.7.x (2.7.11) [Valid for all current versions of rancher]
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): k3s
- Proxy/Cert Details: n/a

**Describe the bug**

This bug is related to this one https://github.com/rancher/dashboard/issues/11211 and is intended to track the need for a script to patch existing clusters using fleet. Ultimately this may be something we can automate but the current goal is simply to create a script that accomplishes the goal and then publish directions as a TID.

**To Reproduce**
See original issue.

**Result**

**Expected Result**
We will publish a script (likely in rancher [support tools](https://github.com/rancherlabs/support-tools) repo) and a TID documenting how, when and why to use it.

## Script and How to Test
The script for this can be found named [fleet-secrets-bro-patch](https://github.com/rancherlabs/support-tools/tree/master/fleet-secrets-bro-patch) under the support-tools repo.

This will patch any secrets being used by fleet to ensure they will be backed up in the next Backup taken by Rancher Backups. So this can be run both: as a "one-off" method to fix existing fleet GitRepo secrets, and end-users can regularly run it as needed (if they create secrets and GitRepo objects for Fleet outside the Rancher UI).

**Comment by mallardduck** [comment]
Addressed a bug in the script that was reported via slack over the weekend.
Should be ready for review again now and merged once someone with rights hits the button.

**Comment by mallardduck** [comment]
I've set this as `To Test` just in case we want to have QA do a test of this.
Not sure if necessary here since this issue is just to track the script creation.

**Comment by nickwsuse** [comment]
Verified on v2.9-head ID: `dd23578` ✅ 
----
I validated that dry-running the script is successful and outputs the expected secrets, and actually running the script updates them. Once updated, they are successfully backed up and can be found in the gzip file. Restoring with the backup returns no errors.
