### ISSUE TITLE
[Backport v2.8] [RFE] Improve handling of `dynamicSchemaSpec`

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#45845]
Backport of https://github.com/rancher/rancher/issues/44618 to v2.8.x release line.

**Comment by susesgartner** [comment]
Ticket #45845 - Test Results - ✅ 
---
 
| Scenario | Test Case | Result |
|---|---|---|
| 1. | Dynamic schema repopulation test | PASS |
 
---
Verified with Docker on Rancher `v2.9-3c4ccdc5bc9fde3510089153b5ad58fdbe604880-head`:
---
NOTE: Tested on RKE2/K3s and also tested using terraform.
Scenario 1: Dynamic schema gets repopulated
---
1. Provision an rke2 cluster with the dynamic schema 
2. Wait for the cluster to finish provisioning
3. Remove the dynamic schema
 
Results: the dynamic schema repopulates and the cluster doesn't re-provision.
