### ISSUE TITLE
rancher-compose --confirm-upgrade doesn't appear to work with -d

### ISSUE THREAD

**Issue by ndarilek** [rancher/rancher#4585]
Rancher Version: rancher-compose 0.7.4

Docker Version: 1.11.1

OS: Ubuntu 14.04.4

Steps to Reproduce: 
1. Start an existing Rancher service.
2. With an upgrade ready to go, run `rancher-compose up -d <some-service> --upgrade`
3. Then run `rancher-compose up -d <some-service> --confirm-upgrade`.

Results: 

The upgrade does not appear to confirm. If I remove the `-d` flag and run the exact same command line, the upgrade is confirmed.

Expected:

The upgrade will confirm and the command will return once complete, not blocking.

**Comment by deniseschannon** [comment]
This is fixed in the latest release of Rancher/rancher-compose.

In rancher-compose v0.8.0.
