### ISSUE TITLE
Remove external-rules feature flag

### ISSUE THREAD

**Issue by raulcabello** [rancher/rancher#45863]
`external-rules` feature flag should be removed in Rancher 2.9. It will work as the feature flag is always on, and can't be disabled.

**Comment by raulcabello** [comment]
waiting for https://github.com/rancher/webhook/pull/366

**Comment by joesims22** [comment]
While testing the upgrade scenario for `v2.8.5` -> `v2.9-head` (on commit id `37f6eeb`) I observed that the external rules feature flag is not removed upon upgrading to `v2.9`. 

At first upon upgrading to `v2.9` rancher-webhook was pointing to an older version. I updated it to `104.0.0+up0.5.0` and the external rules feature flag was still present.

Re-opening this ticket as the feature flag should be removed.

**Comment by raulcabello** [comment]
## Release Note

`external-rules` feature flag functionality is removed in Rancher v2.9.0 as the behavior is enabled by default. However, the feature flag is still present when upgrading from 2.8 but enabling/disabling the feature won't have any effect. This will be fixed in the next release.

**Comment by samjustus** [comment]
@sunilarjun you added your label before Raul's latest update so just want to make sure its seen and accounted for

**Comment by sunilarjun** [comment]
> @sunilarjun you added your label before Raul's latest update so just want to make sure its seen and accounted for

Accounted for, thanks for shouting out @samjustus! (The v2.9.0 RN draft should be up for review shortly.)
