### ISSUE TITLE
kubernetes environment initialize error

### ISSUE THREAD

**Issue by logicigam** [rancher/rancher#4586]
my host OS is centos 7-1511,docker 1.11,after I create a kubernnetes environment ,I try to add a host to it, host type is custom,public ip is specified,then I use the command below to start the agent,and here comes the problem:the kubernetes stack can not be fully start.kubelet container keep run into error state with msg:'time="2016-04-28T05:29:16Z" level=fatal msg="Failed to find state.json"' while the other container are all started as normal,any leads?

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.0.1` Cattle: `v0.159.7` UI: `v1.0.5` |
|Access|`Disabled`|
|Route|`authenticated.project.help`|

**Comment by bnusunny** [comment]
I run into the same issue today. How did you solve it?

**Comment by usmanismail** [comment]
@logicigam I am running into the same issue.

**Comment by alena1108** [comment]
@bnusunny @usmanismail what OS is your host? Also Rancher and docker version?

**Comment by alena1108** [comment]
https://github.com/rancher/rancher/issues/5290

**Comment by usmanismail** [comment]
* OS is AWS Standard AMI
* Docker version 1.11.2, build b9f10c9/1.11.2
* Rancher v1.1.2

**Comment by Shyckymn** [comment]
I run into the same issue today...
Trying to install Kubernetes in Rancher environment.
The image "r-Kubernetes_kubelet_1" doesn't start.

Setting up Kubernetes
- Add at least one host
- Waiting for a host to be active
- Creating Kubernetes system stack
- Starting services (7 of 9) (loop...)

The kubelet container logs show this info:
Archive:  certs.zip
inflating: ca.pem
inflating: cert.pem
inflating: key.pem
time="2016-08-17T18:20:34Z" level=fatal msg="Failed to find state.json"

**Comment by usmanismail** [comment]
Down grading the docker version on the machines running rancher-agents to docker 1.9 fixed the issue for me.
