### ISSUE TITLE
Validate SLE Micro 5.5 in Rancher 2.9.0 - Imported Only

### ISSUE THREAD

**Issue by daviswill2** [rancher/rancher#45868]
Request description:
Rancher Manager v2.9.0
Add support for SLE micro 5.5 imported only

**Comment by Josh-Diamond** [comment]
Ticket #45868 - Test Results - 
---

Verified on Rancher `v2.9.0-rc1` using SLE Micro 5.5 community `ami-0bbae1f84573606ad`:

| Scenario | Test Case | Result |
|---|---|---|
| 1. | Import RKE2 w/ k8s 1.29.5+rke2r1 | ✅ |
| 2. | Import RKE2 w/ k8s 1.28.10+rke2r1 => upgrade to 1.29.5+rke2r1 | ✅ |
| 3. |  Reboot RKE2 agent node | ✅ |
| 4. | Import K3s w/ k8s 1.29.5+k3s1 | ✅ |
| 5. | Import K3s w/ k8s 1.28.10+k3s1 => upgrade to 1.29.5+k3s1 | ✅ |
| 6. |  Reboot K3s agent node | ✅ |

---

Scenario 1 - ✅ 
1. Spin up a standalone RKE2 w/ k8s `v1.29.5+rke2r1`
2. Once active, import the cluster into Rancher
3. Verified - cluster successfully imports
4. Deploy downstream workloads and verify cluster functionality
5. Verified - cluster active and functioning as expected

---

Scenario 2 - ✅ 
1. Spin up a standalone RKE2 w/ k3s `v1.28.10+rke2r1`
2. Once active, import the cluster into Rancher
3. Verified - cluster successfully imports
4. Upgrade the k8s version to `v1.29.5+rke2r1` via Rancher UI
5. Verified - cluster successfully upgrades
6. Deploy downstream workloads and verify cluster functionality
7. Verified - cluster and all pods active; as expected

---

Scenario 3 - ✅ 
1. Reboot agent node of imported clusters from Scenario 1 and 2
2. Verified - node reboots; cluster doesn't break; as expected

---

Scenario 4 - ✅ 
1. Spin up a standalone K3s w/ k8s `v1.29.5+k3s1`
2. Once active, import the cluster into Rancher
3. Verified - cluster successfully imports
4. Deploy downstream workloads and verify cluster functionality
5. Verified - cluster active and functioning as expected

---

Scenario 5 - ✅ 
1. Spin up a standalone K3s w/ k3s `v1.28.10+k3s1`
2. Once active, import the cluster into Rancher
3. Verified - cluster successfully imports
4. Upgrade the k8s version to `v1.29.5+k3s1` via Rancher UI
5. Verified - cluster successfully upgrades
6. Deploy downstream workloads and verify cluster functionality
7. Verified - cluster and all pods active; as expected

---

Scenario 6 - ✅ 
1. Reboot agent node of imported clusters from Scenario 4 and 5
2. Verified - node reboots; cluster doesn't break; as expected
