### ISSUE TITLE
RKE2 and K3S - KDM Update for K8s June 2024 patch release for Rancher 2.7

### ISSUE THREAD

**Issue by rancher-max** [rancher/rancher#45889]
# KDM Updates

| New Kubernetes Version  | Min Rancher Version | Max Rancher Version |
|                  :---:                  |              :---:               |               :---:               |
| v1.27.15+rke2r1                  | v2.7.11-alpha1             | v2.8.99 |
| v1.27.15+k3s1                  | v2.7.11-alpha1             | v2.8.99 |

# KDM Branch
[dev-v2.7](https://github.com/rancher/kontainer-driver-metadata/tree/dev-v2.7)

# Chart Changelog

| Chart Name  | New Version | Affected Kubernetes Version(s) |
|        :---:        |       :---:        |                     :---:                     |

TBD

# Argument Changelog

| Argument Name  | Server/Agent Arg | Arg Type | Affected Kubernetes Version(s) |
|        :---:           |               :---:             |      :---:           |   :---:          |
| supervisor-metrics | server | boolean | v1.27.15 |
| write-kubeconfig-group | server | string | v1.27.15 |
| enable-pprof | agent | boolean | v1.27.15 |
| bind-address | agent | string | v1.27.15 |

# Additional Notes

**Comment by VestigeJ** [comment]
<img width="1067" alt="Screenshot 2024-07-02 at 3 53 30 PM" src="https://github.com/rancher/rancher/assets/8961630/acd33b09-e41d-4a61-b266-4a6aedc482f1">
