### ISSUE TITLE
Rancher Catalog unavailable after Upgrade from v1.0 to v1.0.1

### ISSUE THREAD

**Issue by JJediny** [rancher/rancher#4590]
**Rancher Version**
1.0.1
**Docker Version:**
1.10
**OS:**
Ubuntu 14.04
**Steps to Reproduce:**
Upgrading from 1.0 to 1.0.1 from ssh/cmd on host per docs
**Results:**
The external db reloaded the services but the catalog is now giving a 500 error. On inspection `[rancher]/v1-catalog` returns:

```
{
"id": "795d6d93-12eb-46cb-850e-5e1946bc35ef",
"type": "error",
"links": { },
"actions": { },
"status": 500,
"code": "Internal Server Error",
"message": "Internal Server Error",
"detail": null,
}
```

**Comment by deniseschannon** [comment]
Are you still facing this issue? We test upgrades with the internal database, but I don't believe anything should be different for an external DB.

**Comment by deniseschannon** [comment]
@JJediny If you are still facing issues, please re-open.
