### ISSUE TITLE
When binding host IP to a port, the API doesn't show all ports exposed in the image.

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#4592]
Steps to Reproduce: 
1. Create a nginx service with a `host IP:port` bound to 1 port. 
   Example: `1.2.3.4:80` -> `80`
2. Edit the container

Results: 
Only the port that's bound to the host IP is shown. 
The exposed port `443` on the nginx image is not in the API

Expected:

When creating a service with just a port  binding `80` -> `80`, the API will still have the exposed port `443` of the nginx image.

**Comment by cjellick** [comment]
Legit issue with back population. For some reason, we decided to only do full back population for "native" containers, not ones started in rancher, and that causes us to miss certain fields that were defined in the image.

That said, I don't think this is critical for 1.2.0. Can we bump out?
