### ISSUE TITLE
[BUG] unable to upgrade k3s

### ISSUE THREAD

**Issue by mike12806** [rancher/rancher#45929]
**Rancher Server Setup**
- Rancher version: 2.8.2 - stable docker image 
- Installation option (Docker install/Helm Chart): docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details: nginx

**Information about the Cluster**
- Kubernetes version: 128.9
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): imported

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Admin

**Describe the bug**

No option in cluster config view to update from 128.9 to 128.11
**To Reproduce**

**Result**

**Expected Result**

Would’ve expected k3s version upgrade to be available in Rancher UI via system upgrade controller. If 128.9 is the highest supported version, the docs are out of date. 

**Screenshots**

**Additional context**

**Comment by mike12806** [comment]
![IMG_0002](https://github.com/rancher/rancher/assets/80599490/9542d30d-48e2-43ee-8aaa-116ff6a5ed82)

**Comment by mike12806** [comment]
> @mike12806 , Rancher leverages KDM (https://github.com/rancher/kontainer-driver-metadata) for list of supported RKE2/K3s/RKE1 versions, so:
> 
> 1. Just-released https://github.com/k3s-io/k3s/releases/tag/v1.28.11%2Bk3s1 is not added to KDM data for 2.8 yet (`release-v2.8` branch is used - https://github.com/rancher/kontainer-driver-metadata/blob/release-v2.8/channels.yaml#L590-L595 ([permalink](https://github.com/rancher/kontainer-driver-metadata/blob/e7e8ef72be3dfd6b4d9d33d2c23d7c6012c0d08f/channels.yaml#L590-L595)). So the latest available 1.28.x version for 2.8.x at the moment is `v1.28.10+k3s1`.
> 
> 2. Also, Rancher 2.8.2 doesn't actually support K8s 1.28 (the support was added in https://github.com/rancher/rancher/releases/tag/v2.8.3). So running v2.8.2 + downstream K8s 1.28 clusters is not a supported configuration. Please upgrade to v2.8.3+ to run 1.28.x downstream clusters and be able to upgrade them as new patches become released via KDM.
> 
> 
> 
> Closing as "working as expected".

This is helpful, thank you. Any idea why all the docker images for rancher seem to include 2.8.2? I checked both the latest and stable tagged images. If I get on 2.8.3, sounds like I can at least get to 1.28.10.

**Comment by snasovich** [comment]
@mike12806 , I'm seeing both `latest` and `stable` tags pointing to the latest `v2.8.5` release (digest `sha256:4c2eae327f2e41effdddd0d71a4840094ecd9bcbe1c74876e59d184be85779c9` is the same on:
* https://hub.docker.com/layers/rancher/rancher/v2.8.5/images/sha256-20cd423bc7e01026bb35a08e464c26c13857ded0a6164d6518043db89711d052
* https://hub.docker.com/layers/rancher/rancher/stable/images/sha256-20cd423bc7e01026bb35a08e464c26c13857ded0a6164d6518043db89711d052
* https://hub.docker.com/layers/rancher/rancher/latest/images/sha256-20cd423bc7e01026bb35a08e464c26c13857ded0a6164d6518043db89711d052

**Comment by mike12806** [comment]
Interesting - I’m seeing 

[rancher/rancher:stable@sha256:91a26da6b860b5b3a4507db6b30879d74f7d95edf252dce0a4cf86dd52449d74]

I’ll have to dig in why I’m getting a stale image somehow. Thanks!
