### ISSUE TITLE
Can't add exoscale host - all info missing from screen

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4593]
Version - master 4/28 

Steps to Reproduce:
1.  Add host
2.  Click on exoscale icon

Results: Nothing on page.  ember.prod.js:36602 Uncaught RangeError: Maximum call stack size exceeded in dev tools

Expected: exoscale info should show up.

**Comment by deniseschannon** [comment]
Verified with v1.1.0-dev1-rc2 that the exoscale screen is coming up.
