### ISSUE TITLE
[backport v2.8] add helm chart variable to set agent-tls-mode setting

### ISSUE THREAD

**Issue by mallardduck** [rancher/rancher#45938]
This is created as a reminder for me to backport this PR: https://github.com/rancher/rancher/pull/45522
The 2.9 version of this issue: https://github.com/rancher/rancher/issues/45629

**Comment by nickwsuse** [comment]
Verified on v2.8-head ID: `4912b2c` ✅ 
----
### Fresh Install
1. agent-tls-source is correctly defaulted to `system-store`
2. The `--set agent-tls-source` flag does not throw any errors on usage
3. The `--set agent-tls-source` flag correctly sets the value of the agent-tls-source variable

### Upgrade
1. agent-tls-source is correctly kept as `system-store` on upgrade
2. The `--set agent-tls-source` flag does not throw any errors on usage
3. The `--set agent-tls-source` flag correctly sets the value of the agent-tls-source variable

**Comment by ericpromislow** [comment]
Isn't it supposed to be `--set agentTLSMode=strict|system-store` ?

**Comment by nickwsuse** [comment]
You're right, and looks like I used the correct flag when testing so I'm not sure where I got the agent-tls-source wording from when writing my comment. 

`helm install rancher rancher-latest/rancher --version 2.8.6-rc1 --namespace cattle-system --set hostname=<redacted> --set global.cattle.psp.enabled=false --set ingress.tls.source=secret --set agentTLSMode=strict`

`helm upgrade rancher rancher-latest/rancher --version 2.8.6-rc1 --namespace cattle-system --set hostname=<redacted> --set global.cattle.psp.enabled=false --set ingress.tls.source=secret --set agentTLSMode=strict`
