### ISSUE TITLE
Remove Weave support in rke for kubernetes versions >=1.30.0

### ISSUE THREAD

**Issue by vardhaman22** [rancher/rancher#45954]
Weave was deprecated for k8s >=v1.27 (ref [issue](https://github.com/rancher/rancher/issues/42730)) and the support for this needs to be removed now for k8s >=1.30.
1. User should not be able to select weave as a CNI for k8s >=1.30 in the UI. earlier issue which was created for deprecation warning: https://github.com/rancher/dashboard/issues/9556 
2. rke should throw an error if cluster >=1.30 is provisioned with weave.
3. docs needs to be updated accordingly to notify users for weave deprecation.

**Comment by Sahota1225** [comment]
https://github.com/rancher/dashboard/issues/11322

**Comment by rishabhmsra** [comment]
Validated on rancher v2.9-head

Rancher UI fresh install checks :

- Created RKE1 v1.30.2-rancher1-1 node driver cluster(1-cp, 1-e, 1-w)
- Provisioning fails with below error:

![weave-fresh](https://github.com/user-attachments/assets/13dd48c9-8ccc-4a72-ab56-094bc041534d)



Upgrade checks :

  - Create RKE1 v1.29.6-rancher1-1 node driver cluster(1-cp, 1-e, 1-w)
  - Upgraded cluster to v1.30.2-rancher1-1
  - Upgrade fails with following error:

![weave-upgrade](https://github.com/user-attachments/assets/4c78c882-ece8-468d-b2ee-c6f1b28a6cf8)

RKE Standalone checks using v1.6.0-rc10 :

Fresh install and upgrade fails with following error :

```
ERRO[0000] weave CNI support is removed for k8s version >=1.30.0 
FATA[0000] Failed to validate cluster: weave CNI support is removed for k8s version >=1.30.0 
```
