### ISSUE TITLE
[BUG] SAML login does not update groups

### ISSUE THREAD

**Issue by alto-rlk** [rancher/rancher#45956]
**Rancher Server Setup**
- Rancher version: 2.8.5 (2.8.4 does not have this issue)
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): EKS
- Proxy/Cert Details: n/a

**Information about the Cluster**
- Kubernetes version: 1.28
- Cluster Type (Local/Downstream): local

**User Information**
- What is the role of the user logged in? not sure, probably doesn't matter

**Describe the bug**
Rancher fails to update a user's groups from SAML

**To Reproduce**
1. Configure Rancher with a SAML SSO provider
2. Log into Rancher as a user with some groups from the SSO provider
3. In the SSO provider, add an additional group to the user.
4. Log in to Rancher again.

**Result**
The user's groups do not change.

**Expected Result**
The user's groups should contain the newly added one.

**Additional context**
I believe (just from looking at the code, not directly tested) that this is due to the change in [`UserAttributeCreateOrUpdate`](https://github.com/rancher/rancher/compare/v2.8.4...v2.8.5#diff-969595b35e57fdc1e843c73affdcfff4fc30c695d248dc53f385f3b49ad4aecfR574), specifically moving the code that [updates GroupPrincipals](https://github.com/rancher/rancher/compare/v2.8.4...v2.8.5#diff-969595b35e57fdc1e843c73affdcfff4fc30c695d248dc53f385f3b49ad4aecfR580-R583) to before the call to [`m.userAttributeChanged `](https://github.com/rancher/rancher/compare/v2.8.4...v2.8.5#diff-969595b35e57fdc1e843c73affdcfff4fc30c695d248dc53f385f3b49ad4aecfR610) causes that call to always return `false`, as it is now comparing two copies of the new groups, rather than old vs new.

**Comment by anupama2501** [comment]
Re opening for validations

**Comment by thsnielsen** [comment]
Customer has tested on one  broken user the v2.8.5-debug-44760-1 against the issue, and confirmed it worked

**Comment by rverchere** [comment]
May I use `v2.8.5-debug-44760-2` if I need this fix before the v2.8.6 release?

https://github.com/rancher/rancher/compare/v2.8.5...v2.8.5-debug-44760-2

**Comment by dasarinaidu** [comment]
Completed validations on `v2.9-37f6eebf662459addc96bd31f486d8573a281c27-head` and closed with below issues. None of these are introduced with this code change.

[BUG]: Admin user: UserAttributes cleanup is not happening properly after disabling Auth https://github.com/rancher/rancher/issues/46252
[BUG] : Group Principals-> Creation timestamp is coming as nil for the assigned groups in the userAttributes https://github.com/rancher/rancher/issues/46253
