### ISSUE TITLE
Reintroduce monitoring 45.31.1 for release 2.9

### ISSUE THREAD

**Issue by alexandreLamarre** [rancher/rancher#45966]
45.31.1 was accidentally removed in charts during the monitoring rebase to 57.x

**Comment by pankajsqe** [comment]
Rancher-monitoring:104.0.0+up45.31.1 chart is available on for release 2.9 and able to install and successfully.



![Image](https://github.com/rancher/rancher/assets/149133120/0a501740-5968-4124-932f-f8d6d37f36d5)
![Image](https://github.com/rancher/rancher/assets/149133120/5dae0c39-6700-4f4e-a52c-03cb86f66d7e)
