### ISSUE TITLE
Unable to link a standalone container to a pre-existing service

### ISSUE THREAD

**Issue by codespelunker** [rancher/rancher#4597]
Rancher Version: v1.0.0-rc2

Docker Version: 1.10.3

OS: Mac OSX 10.10.5

Steps to Reproduce: 

Hello, Rancher newbie here.  I'm trying to get a standalone container to spin up and attach itself to an existing service.  I'm doing this with selector labels as described here: http://docs.rancher.com/rancher/labels/#selector-labels.

My service (TestService) has a label: io.rancher.service.selector.container=test_selector

![screen shot 2016-04-28 at 15 06 20](https://cloud.githubusercontent.com/assets/2177438/14903203/64052000-0d54-11e6-9c86-01645e85c758.png)

My standalone container (elegant_aryabhata) spins up with a label: test_selector=

Note the host for this container is on a different machine outside the rest of the cluster.  It's been joined to the cluster using the rancher-agent.

![screen shot 2016-04-28 at 15 06 02](https://cloud.githubusercontent.com/assets/2177438/14903207/6dfb06ce-0d54-11e6-9454-5fc5cb019d67.png)

The standalone container is the same image as associated with the service, and in fact the service already has another container, TestService_1, spun up.

![screen shot 2016-04-28 at 15 05 44](https://cloud.githubusercontent.com/assets/2177438/14903185/49472574-0d54-11e6-9803-e8c2bbfe5e14.png)

Results:  The service only reports a single container-- the one it originally spun up with.

![screen shot 2016-04-28 at 15 21 56](https://cloud.githubusercontent.com/assets/2177438/14903309/1811402e-0d55-11e6-9917-a1402c30d2c3.png)

Expected:  My understanding is that when my 2nd container (elegant_aryabhata) spins up, Rancher should link it with the service (TestService) and I should get the benefits of internal DNS.  Any suggestions?

**Comment by deniseschannon** [comment]
@codespelunker Apologies. I forgot that in the UI, we are actually missing the support for using selectorLinks/selectorContainers. The label is only applicable for services launched through rancher-compose.

https://github.com/rancher/rancher/issues/2270

As a workaround, you could export the docker-compose.yml for the service and import it into the UI through the addstack. 

Since the label is defined, it would pick up the container.
