### ISSUE TITLE
Backport : CA check improvements for rancher-agent 

### ISSUE THREAD

**Issue by Sahota1225** [rancher/rancher#45974]

**Comment by markusewalker** [comment]
Validated test cases outlined in Qase test run /RM/1631 (modified to adjust for v2.8). Summary of the scenarios tested provided below:

**ENVIRONMENT DETAILS**
- Rancher install: Docker/Helm
- Rancher version: `v2.8-head` https://github.com/rancher/rancher/commit/d72c5157164a9eb798aab685e23af818f95804e4

|#|Scenario|Result|
|---|---|---|
|1|Validate Rancher is accessible with valid ca-certs|:white_check_mark:|
|2|Validate Rancher is inaccessible with invalid ca-certs|:white_check_mark:|
|3|Validate Rancher is inaccessible with invalid ca-certs and `agentTLSMode=strict`|:white_check_mark:|
|4|Validate Rancher is accessible/usable with valid ca-certs and `agentTLSMode=system-store`|:white_check_mark:|
|5|Upgrade Rancher from v2.7-head -> v2.8-head|:white_check_mark:|
