### ISSUE TITLE
[2.8] SAML login does not update groups

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#45993]
backport #45956

**Comment by brudnak** [comment]
validated on `v2.8-a27b103859a84fe743e05d84c054659945b54e72-head`

1. Enable okta auth
2. Sign in as an Okta user
3. Check that user with `kubectl describe userattributes $RANCHER_USER_ID`
4. Note the groups the user is part of
5. Within Okta, add the user to an additional group
6. Log out as the user
7. Log back in as the user
8. Check the user again with `kubectl describe userattributes $RANCHER_USER_ID`
9. Verified that the new group was added
