### ISSUE TITLE
[BUG] DynamicListener doesn't log panics from handlers

### ISSUE THREAD

**Issue by tomleb** [rancher/rancher#46002]
**Rancher Server Setup**
- Rancher version:
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version:
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:

**Describe the bug**

DynamicListener will not log panics from HTTP handlers that it runs. The panics are recovered by `net/http.Server` (See here: https://pkg.go.dev/net/http#Handler) and they are being logged by the logger configured by the `ErrorLog` field.

Unfortunately, DynamicListener is [configuring a logger that will not log](https://github.com/rancher/dynamiclistener/blob/e590d58b896cc8dd33dde7cec80c52e23ec08189/server/server.go#L50-L51). 

Here's a snippet to show the issue, reusing the same logger configuration from DynamicListener:

```go
package main

import (
	"log"

	"github.com/sirupsen/logrus"
)

func main() {
	logger := logrus.StandardLogger()
	errorLog := log.New(logger.WriterLevel(logrus.DebugLevel), "", log.LstdFlags)
	errorLog.Println("HI")
}

```

This doesn't print anything, because `logrus.StandardLogger()` configures the logger with Info level, but `logger.WriterLevel(logrus.DebugLevel)` gives a logger that logs on Debug.

This affects at least the following endpoints:
- steves' `/v1`

**To Reproduce**

**Result**

**Expected Result**

**Screenshots**

**Additional context**

**Comment by MKlimuszka** [comment]
We want to backport this, but not until it spends some time in 2.10.

**Comment by brudnak** [comment]
<details>
    <summary>🧪 Test Environment... CLICK TO EXPAND! ⬅️</summary>


| Component                        | Version / Type                                      |
| -------------------------------- | --------------------------------------------------- |
| Rancher version starting         | 2.9.2                                               |
| Rancher version upgraded         | v2.10-73a22a6ad6aca91f7817e3507b3b99dc44813cb0-head |
| Installation option              | Docker                                              |
| Cert Details                     | `--acme-domain`                                     |
| Docker version                   | 20.10.7, build f0df350                              |
| Downstream cluster type          | not applicable                                      |
| Downstream K8s version           | not applicable                                      |
| Authentication providers enabled | local                                               |
| Logged in user role              | admin                                               |
| Webhook version                  | rancher/rancher-webhook:v0.3.6                      |

<br>

</details>

<a name="top"></a>

### 🧪 Test Cases

| \#  | Priority | Description & Link                                    | PASS/FAIL |
| --- | -------- | ----------------------------------------------------- | --------- |
| 1   | P0       | [(Regression Check) Steve Integration Tests](#test-1) | ✅ `PASS`  |
| 2   | P0       | [(Regression Check) Steve Validation Tests](#test-2)  | ✅ `PASS`  |
| 3   | P0       | [Ensure Panics Are Logged - Custom Image](#test-3)    | ✅ `PASS`  |
| 4   | P0       | [Upgrade](#test-4)                                    | ✅ `PASS`  |


<details>
    <summary>🚨 4 test cases... CLICK TO EXPAND! (For table links to work) ⬅️</summary>

<br>

# 1 / (Regression Check) Steve Integration Tests Status: ✅ `PASS`

<a name="test-1"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 1 details... Click to expand</summary>

**Test Steps for Validation**

1. Run automated integration tests to ensure no regressions


**✅ Expected Outcome**

Regression checks should pass

**✅ Actual Outcome**

Regression checks passing


</details>
<hr>

# 2 / (Regression Check) Steve Validation Tests Status: ✅ `PASS`

<a name="test-2"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 2 details... Click to expand</summary>

**Test Steps for Validation**

1. Run automated validation tests to ensure no regressions


**✅ Expected Outcome**

Regression checks should pass

**✅ Actual Outcome**

Regression checks passing


</details>
<hr>

# 3 / Ensure Panics Are Logged - Custom Image Status: ✅ `PASS`

<a name="test-3"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 3 details... Click to expand</summary>

**Test Steps for Validation**

1. Start Rancher with custom image: `morspin/rancher:v2.10.0-dev.10`
2. Navigate to `<rancher_url>/v1/events`
3. Check the Rancher logs and find the following:

```log
2024/10/24 09:01:41 [ERROR] 2024/10/24 09:01:41 http: panic serving <REDACTED>:35884: Awp!  Found an events thing.
```

**✅ Expected Outcome**

Panics to be logged as expected

**✅ Actual Outcome**

Panics are now being logged as expected

</details>
<hr>

# 4 / Upgrade Status: ✅ `PASS`

<a name="test-4"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 4 details... Click to expand</summary>

**Test Steps for Validation**

1. step 1
2. step 2

**✅ Expected Outcome**

**✅ Actual Outcome**


</details>
<hr>

</details>

**Comment by brudnak** [comment]
<details>
    <summary>🧪 Test Environment... CLICK TO EXPAND! ⬅️</summary>


| Component                        | Version / Type                                      |
| -------------------------------- | --------------------------------------------------- |
| Rancher version starting         | 2.9.2                                               |
| Rancher version upgraded         | v2.10-73a22a6ad6aca91f7817e3507b3b99dc44813cb0-head |
| Installation option              | Docker                                              |
| Cert Details                     | `--acme-domain`                                     |
| Docker version                   | 20.10.7, build f0df350                              |
| Downstream cluster type          | not applicable                                      |
| Downstream K8s version           | not applicable                                      |
| Authentication providers enabled | local                                               |
| Logged in user role              | admin                                               |
| Webhook version                  | rancher/rancher-webhook:v0.3.6                      |

<br>

</details>

<a name="top"></a>

### 🧪 Test Cases

| \#  | Priority | Description & Link                                    | PASS/FAIL |
| --- | -------- | ----------------------------------------------------- | --------- |
| 1   | P0       | [(Regression Check) Steve Integration Tests](#test-1) | ✅ `PASS`  |
| 2   | P0       | [(Regression Check) Steve Validation Tests](#test-2)  | ✅ `PASS`  |
| 3   | P0       | [Ensure Panics Are Logged - Custom Image](#test-3)    | ✅ `PASS`  |
| 4   | P0       | [Upgrade](#test-4)                                    | ✅ `PASS`  |


<details>
    <summary>🚨 4 test cases... CLICK TO EXPAND! (For table links to work) ⬅️</summary>

<br>

# 1 / (Regression Check) Steve Integration Tests Status: ✅ `PASS`

<a name="test-1"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 1 details... Click to expand</summary>

**Test Steps for Validation**

1. Run automated integration tests to ensure no regressions


**✅ Expected Outcome**

Regression checks should pass

**✅ Actual Outcome**

Regression checks passing


</details>
<hr>

# 2 / (Regression Check) Steve Validation Tests Status: ✅ `PASS`

<a name="test-2"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 2 details... Click to expand</summary>

**Test Steps for Validation**

1. Run automated validation tests to ensure no regressions


**✅ Expected Outcome**

Regression checks should pass

**✅ Actual Outcome**

Regression checks passing


</details>
<hr>

# 3 / Ensure Panics Are Logged - Custom Image Status: ✅ `PASS`

<a name="test-3"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 3 details... Click to expand</summary>

**Test Steps for Validation**

1. Start Rancher with custom image: `morspin/rancher:v2.10.0-dev.10`
2. Navigate to `<rancher_url>/v1/events`
3. Check the Rancher logs and find the following:

```log
2024/10/24 09:01:41 [ERROR] 2024/10/24 09:01:41 http: panic serving <REDACTED>:35884: Awp!  Found an events thing.
```

**✅ Expected Outcome**

Panics to be logged as expected

**✅ Actual Outcome**

Panics are now being logged as expected

</details>
<hr>

# 4 / Upgrade Status: ✅ `PASS`

<a name="test-4"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 4 details... Click to expand</summary>

**Test Steps for Validation**

1. Start with a previously released version of Rancher
2. Upgrade to the version of Rancher with the fix
3. Run all test cases against this upgraded Rancher

**✅ Expected Outcome**

For all test cases to pass against an upgraded Rancher setup

**✅ Actual Outcome**

All test cases passing on the upgraded Rancher setup

</details>
<hr>

</details>
