### ISSUE TITLE
Cannot deploy f5 (external-lb) from catalog 

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#4601]
Rancher Version: v1.1.0-dev1-rc1

Steps to Reproduce: 
1. Add f5 catalog [URL ==> https://github.com/prachidamle/my-rancher-catalog]
2. Deploy the f5 catalog [f5 BigIP LB Stack]

Results: Deployment un-successful.
Activating (yaml: [while parsing a quoted scalar] did not find expected hexdecimal number at line 23, column 24). It remains in this state and the service does not get added.

**Comment by prachidamle** [comment]
Seems like Rancher Compose - v0.8.0-rc3 has stricter yaml validation, causing this failure

**Comment by prachidamle** [comment]
This is fixed now - It was erroring out on a single quote used in rancher-compose.yml file

**Comment by soumyalj** [comment]
Verified after the fix in rancher-compose.yml file.
