### ISSUE TITLE
[RFE] Enhance the `Machine Driver` interface

### ISSUE THREAD

**Issue by votdev** [rancher/rancher#46025]
**Is your feature request related to a problem? Please describe.**
Consider we have a Harvester cluster (e.g. k3s/rke2) in Rancher, there is currently no way to determine whether a cluster has only been modified or deleted because in both cases the `Remove()` method of the [Driver interface](https://github.com/rancher/machine/blob/6108a82e67bceaf7df9e0ff6dd541258369fba6a/libmachine/drivers/drivers.go#L15) is called.

If the cluster configuration has been changed, for example, PVCs must be retained so that [user data is not deleted](https://github.com/harvester/docker-machine-driver-harvester/blob/7a5dd1da7b84f76c9ebc6dd3b538abb7bcbb4b05/harvester/harvester.go#L185). However, if the cluster is deleted permanently, these PVCs that are no longer required should also be deleted.
With the current interface, we cannot distinguish for which action the `Remove()` method is currently being used.

We would therefore like to use this issue to discuss a change to the interface so that these cases can be handled correctly.

**Describe the solution you'd like**
Add or modify a method to bypass the necessary information to the provider that implements this interface.

# Modify the `Remove()` method
```
// Remove a host
Remove(purge bool) error
```
Alternatively use `destroy` instead of `purge`. Depends on what is more common in Rancher.

If a cluster is permanently deleted (e.g. user select `Delete` in the Rancher UI), the `purge` parameter is set to `true`.

# Add a new method
Here are some alternatives that can be added to the interface:
1. Cleanup
```
// Cleanup after a host has been permanently removed.
Cleanup() error
```

2. Destroy
```
// Permanently remove a host. This can simply call `Remove()` if the 
// provider has no special destruction behavior.
Destroy() error
```

**Describe alternatives you've considered**
n/a

**Additional context**
References:
- https://github.com/harvester/harvester/issues/2825
- https://github.com/harvester/harvester/issues/2825#issuecomment-2160931108
- https://github.com/harvester/harvester/issues/2825#issuecomment-2172876600

**Comment by w13915984028** [comment]
The issue https://github.com/harvester/harvester/issues/5522 is also depending on such an interface, it will give the node driver the chance to delete all resources related to this guest cluster.

**Comment by snasovich** [comment]
Following offline discussions we've settled on a different approach to resolve associated Harvester issues so closing this one as "won't do".
