### ISSUE TITLE
Time to rebase logging operator on 4.8.x

### ISSUE THREAD

**Issue by joshmeranda** [rancher/rancher#46035]
rancher-logging is currently 4 minor versions behind the upstream (4.4.0 vs 4.8.0) could be worth rebasing the logging-operator

Will want / need to reintroduce changes made in https://github.com/rancher/charts/pull/4075 (was closed on accident rather than merged 😧)

**Comment by pankajsqe** [comment]
Retest blocked with an issue causing logging chart installation to fail with below error.

rancher v2.9.1-rc1
rancher-logging:104.1.0-rc1+up4.8.0

`Warning  FailedScheduling  5m17s  default-scheduler  0/1 nodes are available: pod has unbound immediate PersistentVolumeClaims. preemption: 0/1 nodes are available: 1 Preemption is not helpful for scheduling.`

**Comment by pankajsqe** [comment]
The blocker issue mentioned above has been resolved and verified. Following that, the rebase of the logging operator on version 4.8.x was completed successfully. The rebase test for the logging operator has also passed.

rancher : v2.9.1-rc3
cluster :( RKE2 -v1.30.1+rke2r1, K3S-v1.30.4-rc1+k3s1)
rancher-logging:104.1.0-rc1+up4.8.0
Local and Downstream cluster.

![Image](https://github.com/user-attachments/assets/f1a3c0db-a740-4630-b6d2-d6b187b6e721)
![Image](https://github.com/user-attachments/assets/3ffc9458-1dbf-4b00-8ce3-0bb6444403b3)
![Image](https://github.com/user-attachments/assets/5467c8e9-ca59-4501-804f-c1ccceba1f14)
![Image](https://github.com/user-attachments/assets/d294b73c-71c8-47b7-89e5-5a0bf640c892)
![Image](https://github.com/user-attachments/assets/65c0ad93-9130-4890-88cf-a1650687acac)
![Image](https://github.com/user-attachments/assets/71a234cc-f47d-41fa-b5bf-c932ae850093)
![Image](https://github.com/user-attachments/assets/8bf75992-ea93-4873-a0b0-766b43a813f2)
