### ISSUE TITLE
Ability to leave old containers running for specified when upgrading with start before stopping

### ISSUE THREAD

**Issue by ingardm** [rancher/rancher#4603]
Rancher Version:
1.0.1
Docker Version:

OS: 

Steps to Reproduce: 

Results: 

Expected:
When serving long running http requests we'd like the containers being upgraded to be able to finish serving the requests. This could be solved by having a user configured interval between starting a new instance and stopping the old. With the new bigip external-lb option it would be accomplished by disabling the old pool member, starting a new instance, and wait to stop/remove the old pool member until $defined_interval

**Comment by deniseschannon** [comment]
![screen shot 2016-05-05 at 1 08 58 pm](https://cloud.githubusercontent.com/assets/11410997/15055682/b9c8cb72-12c2-11e6-8e5e-96b32e54b4f3.png)


By default, during the upgrade, there is a 2 second wait between when containers on the new service have started and when containers on the old service are removed. But you can edit this in the UI. or in rancher-compose. 

Would that satisfy what you are looking to do?

**Comment by ingardm** [comment]
Lets say I have a scale of 3 for one service. I'd like to use the batch interval to set a certain time between each container being upgraded, but i'd also like to be able to keep the old containers for longer than the batch interval. So if batch interval was 1 min, then an upgrad of the 3 containers would be finished in 3 mins. But I'd like to be able to keep the old containers running for maybe 10-15 mins. A use case being for instance to let old (disabled) containers finish serving file up/downloads.

**Comment by deniseschannon** [comment]
Ok, that functionality is not currently supported, so I've converted your issue into an enhancement request.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
