### ISSUE TITLE
Make the GHA image publishing process pin the webhook version

### ISSUE THREAD

**Issue by Priyashetty17** [rancher/rancher#46033]
**Rancher Server Setup**
- Rancher version: `v2.9-75f1e7ec08a8c1513ea6c51a71cd99dd62ea17eb-head`
- Installation option (Docker install/Helm Chart): Helm install 
- Proxy/Cert Details: N/A

**Information about the Cluster**
- Kubernetes version: N/A local cluster only 
- Cluster Type (Local/Downstream): Local

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Admin

**Describe the bug**
The webhook version is not set in the settings, and the environment variable is empty

**To Reproduce**
1. Create a Rancher instance with latest v2.9-head
2. Retrieve the setting for the webhook version: `kubectl get setting rancher-webhook-version -o yaml`

**Result**
env var for webhook version is empty instead of 104.0.0+up0.5.0-rc11:
```
> kubectl get setting rancher-webhook-version -o yaml
apiVersion: management.cattle.io/v3
customized: false
default: ""
kind: Setting
metadata:
  creationTimestamp: "2024-07-05T17:06:01Z"
  generation: 1
  name: rancher-webhook-version
  resourceVersion: "2222"
  uid: 2df724d1-5ea1-40ad-9813-ace92c30b1af
source: env
value: ""
```

**Expected Result**
The env var should be: `104.0.0+up0.5.0-rc11` instead of empty. 

**Screenshots**
N/A.

**Comment by MKlimuszka** [comment]
Blocked on https://github.com/rancher/rancher/issues/45969

**Comment by Priyashetty17** [comment]
Validated with `v2.9-637346f76ea2bb71a82ea6e00a2779f61610a2a4-head`
```
> kubectl get setting rancher-webhook-version -o yaml
apiVersion: management.cattle.io/v3
customized: false
default: ""
kind: Setting
metadata:
  creationTimestamp: "2024-07-17T18:47:00Z"
  generation: 1
  name: rancher-webhook-version
  resourceVersion: "2307"
  uid: 91af2402-a69a-4562-b177-1ed64d5237df
source: env
value: 104.0.0+up0.5.0-rc14
```
