### ISSUE TITLE
Security bug: Rancher loadbalancer leaking port 80 into the open. haproxy.cfg ACL is wrong

### ISSUE THREAD

**Issue by weitzj** [rancher/rancher#4604]
Rancher Version:
v1.0.1
Docker Version:
1.11.0
OS: 
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
```
Steps to Reproduce: 

- Create service (e.g. `webviewer`), which listens on port 80
- Create `loadbalancer` which listens on port 80 (http) and port 443 (http,SSL)
- Add service `webviewer` as a  target to loadbalancer
  - Requesthost: example.com
  - Sourceport 443
  - Target Service: `webviewer`
  - TargetPort: 80

i.e. loadbalancer does TLS termination on 443 and forward the unencrypted traffic to port 80 to the internal service.

![screen shot 2016-04-29 at 11 42 37](https://cloud.githubusercontent.com/assets/829277/14912893/84770bb8-0dff-11e6-93cf-11144cbe7e97.png)

Results: 

Requests on port 80 get forwarded as well:

- `curl http://example.com:80` gets a result! This is bad!
- `curl https://example.com:443` gets a result. As it is expected.

Expected:

`curl http://example.com:80` should yield:

 HTTP/1.0 503 Service Unavailable

Generated haproxy.cfg:

```
frontend ebd87eb0-a59e-4a67-9897-eec9bb988072_443_frontend
        bind *:443  ssl crt /etc/haproxy/certs/
        mode http

        # this acl MUST NOT be here
        acl 8_host hdr(host) -i example.com

        # this acl is expected
        acl 8_host hdr(host) -i example.com:443
        use_backend ebd87eb0-a59e-4a67-9897-eec9bb988072_443_8_backend if 8_host


backend ebd87eb0-a59e-4a67-9897-eec9bb988072_443_8_backend
        mode http

        # this is the `webviewer` server
        server 0c2836b8-dafc-4f0d-a830-918440c8597c 10.42.188.105:80
        http-request add-header X-Forwarded-Proto https if { ssl_fc }
```

**Comment by vincent99** [comment]
This is not a bug.. a request which matches no routing rules is sent to all the target services.

**Comment by weitzj** [comment]
> This is not a bug.. a request which matches no routing rules is sent to all the target services.

But no target service is listening on a public Port 80, but only the private port 80.

**Comment by vincent99** [comment]
The balancer sends traffic to the "internal"/"container"/"private" port of the target container(s).  You don't need to publish or expose container ports to balance to them.  Whether the balancer is listening on a public port or an internal one is a separate option (the dropdown on the right).

The first "Listening Ports" line makes the balancer containers listen on the host's public IP port 80 and send traffic that comes in there over the overlay network to the port 80 of containers of all the target services in this case.  It sounds like you either don't want that line at all, or want it to only work inside the overlay network (which is changing Access to Internal).

**Comment by vincent99** [comment]
Also for the example shown there is no reason to use the advanced routing, the Request Host=example.com, Source Port=443, and Target Port=80 are all redundant because any request will be sent to `webviewer` anyway unless you add more target services.

**Comment by weitzj** [comment]
I guess I will try out rancher some more.
Thank you.

**Comment by cqcwillard** [comment]
This could still be dangerous considering that most web server containers expose port 80 by default.  In our situation we had to manually change all of our containers private ports to prevent the "leakage" issue that @weitzj demonstrated.

I think this still may be an issue and require investigating.

**Comment by cqcwillard** [comment]
Would it be possible to force a 503 if haproxy is using a name based targeted service?

**Comment by ibuildthecloud** [comment]
We are working on a new load balancer API/UI that will have less gotchas like this so that one doesn't accidentally expose a port like this.

**Comment by weitzj** [comment]
@cqcwillard What we do now is:

- Build and use: https://github.com/GoogleCloudPlatform/nginx-ssl-proxy
- This does Port 80 to Port 443 forwarding, TLS Termination at Port 443
- Use this as a service named: `lb-external` inside the rancher stack
- Use the params `-e ENABLE_SSL=true, `-e TARGET_SERVIC'TARGET_SERVICE=lb-internal`
- Inside the Rancher-Stack create a regular Rancher loadbalancer named `lb-internal` just listening on port 80. Make sure to mark it as `internal`
- Hook up all services behind `lb-internal`


![screen shot 2016-06-08 at 16 57 21](https://cloud.githubusercontent.com/assets/829277/15899657/c7cb259a-2d9c-11e6-84a0-006a7f506049.jpg)


Benfit besides fixing this leak:  Fine-grained TLS support.

- Older Android device-browsers cannot handle TLS 1.2 (which Rancher's haproxy uses by default)
- iOS rely on TLS 1.2 only.
