### ISSUE TITLE
Release Wrangler v3.0.0

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#46058]
Release Wrangler v3.0.0. This will need to be updated in every repo that consumes wrangler.
https://github.com/rancher/wrangler/releases/tag/v3.0.0. 

### Repo list: 

- [x] norman
- [x] apiserver
- [x] dynamiclistener
- [x] steve
- [x] webhook
- [x] rancher

**Comment by tomleb** [comment]
For rancher/rancher: https://github.com/rancher/rancher/pull/46029 waiting on CI to go green but having issues with prov tests.

For rancher/webhook: https://github.com/rancher/charts/pull/4196 need one more approval for this to then add to rancher/rancher.

**Comment by tomleb** [comment]
All the repos above are now using wrangler 3.0.0.
