### ISSUE TITLE
[RKE] Bump Components in rke-tools and confd

### ISSUE THREAD

**Issue by vardhaman22** [rancher/rancher#46050]
in rancher/confd
- bump golang version in confd to 1.22 and golang.org/x/net to v0.17.0

in rke-tools
- bump docker to 26.1.4, flannel to v1.5.1-flannel1 and cni plugin version to v1.5.1 and kubectl to v1.28.11

**Comment by snasovich** [comment]
Not much to QA besides ensuring no regressions possibly causes by these bumps. @vardhaman22 ran some initial checks and it looks OK.
```
tested a few scenarios with the KDM changes and it seems to be working fine with all june patch versions
tested provisioning v1.29 with docker 25 and v1.30 with docker 26 on rancher v2.9-head
tested provisioning v1.28 with docker 24 and v1.27 with docker 23 on rancher on v2.8-head
tested provisioning v1.27 with docker 24 and upgrade test from v1.26 to v1.27 on rancher v2.7.14.
also tested etcd snapshot restore on each cluster.
```

Suggesting to keep it open and see if any RKE1 provisioning we may run into can be attributed to this change.

**Comment by rishabhmsra** [comment]
Validated on rancher v2.9-head:

- Created RKE1 v1.30.2-rancher1-1 (-1-cp, 1-e, 1-w) node driver cluster using docker 26.1.3
- Created RKE1 v1.29.6-rancher1-1 (-1-cp, 1-e, 1-w) node driver cluster using docker 25.0.5
- Created RKE1 v1.28.11-rancher1-1 (-1-cp, 1-e, 1-w) node driver cluster using docker 24.0.9
- Created RKE1 v1.27.15-rancher1-1 (-1-cp, 1-e, 1-w) node driver cluster using docker 23.0.6

All clusters provisioned successfully and also verified etcd backup restore on all above clusters and it was successfull.
