### ISSUE TITLE
[BUG] New Rancher CLI binaries are no longer published to releases.rancher.com

### ISSUE THREAD

**Issue by richard-cox** [rancher/rancher#46068]
**Rancher Server Setup**
- Rancher version: 2.9.0 (during dev)

**Describe the bug**
  - Rancher CLI binaries were previously uploaded to releases.rancher.com
  - The latest version then referenced in `settings` resources
  - The UI would then present download links, per arch type, using the two parts above
  - A new version of the CLI was created and settings updated to 2.9.0-rc4, however after the drone migration was now not uploaded to CDN

**To Reproduce**
- Load the UI --> `About` page --> `Download CLI`

**Result**
- 404 when attempting to download an arch type

**Expected Result**

**Screenshots**
(NOTE - this is from an older system using the previous CLI verison)
![image](https://github.com/rancher/rancher/assets/18697775/b27100b4-3f60-48cf-91c0-46e9f4984de6)

**Additional context**
- When 2.9.0 is released these links will be dead without the process to upload to CDN, hence setting to release blocker
- Discussed in slack release channel

**Comment by gaktive** [comment]
In the short term, someone can manually upload the binaries to the Google bucket so UI can test.

**Comment by gaktive** [comment]
@enrichman is currently unavailable so we'd need someone else to help out. @samjustus would this be Collie?

**Comment by enrichman** [comment]
This is affecting also the latest `v2.8` (`v2.8.6`).
