### ISSUE TITLE
[BUG] Provisioning an RKE2 cluster with the data/dir feature enabled causes snapshot restores to fail

### ISSUE THREAD

**Issue by susesgartner** [rancher/rancher#46066]
**Rancher Server Setup**
- Rancher version: 2.9-head
- Installation option: Docker

**Information about the Cluster**
- Kubernetes version: v1.29.6+rke2r1
- Cluster Type: Downstream RKE2 Node Driver
- Infrastructure Provider: AWS

**User Information**
- User: Admin

**Describe the bug**
When doing a etcd snapshot restore after upgrading the rke2 cluster k8s version the cluster hangs and all pods on the control plane remain in a pending state. 

**To Reproduce**
1. Create a downstream cluster with the split roles and the following data dir configuration
   -System-agent dir: /agent
   -Provisioning dir: /provisioning
   -K8s Distro: /k8s
3. Take a snapshot
4. Update the k8s version to 1.30
5. Restore the snapshot

**Result**
The cluster hangs while attempting to restore

**Expected Result**
The etcd restore completes successfully.

**Screenshots**
<img width="1160" alt="image" src="https://github.com/rancher/rancher/assets/136753565/8796a50f-f9b7-4919-a10d-a5b2dc514578">

**Comment by snasovich** [comment]
Should be ready to test once https://github.com/rancher/kontainer-driver-metadata/pull/1450 is merged

**Comment by jakefhyde** [comment]
Apologies, need to merge https://github.com/rancher/rancher/pull/46103 as well.

**Comment by jakefhyde** [comment]
@susesgartner moving to "Ready for QA", but no need to test until all data-dir PRs are merged. I will update once that is the case.

**Comment by jakefhyde** [comment]
Ready for QA

**Comment by susesgartner** [comment]
Ticket #46066 - Test Results - ✅ 
---
 
| Scenario | Test Case | Result |
|---|---|---|
| 1. | Snapshot/Restore | PASS |
| 2. | k8s upgrade/restore | PASS |
 
---
Verified with (HA Helm or Docker) on Rancher `v2.9-head`:
---
 
Scenario 1: Snapshot/Restore test
---
1. Create downstream rke2 cluster
2. Take a snapshot
3. Restore the snapshot
 
Results: the snapshot is successfully restored and the cluster is in a good state
 
---
 
Scenario 2: k8s upgrade/restore
---
1. Create downstream rke2 cluster
2. Take a snapshot
3. Upgrade the K8s version
4. Restore the snapshot
 
Results: the k8s version is successfully downgraded and the cluster is in a good state
