### ISSUE TITLE
[BUG] Users: User Retention Settings: 'Last Login' column in the User table is not populated with value set in 'Default last login' 

### ISSUE THREAD

**Issue by yonasberhe23** [rancher/rancher#46063]
**Rancher Server Setup**
- Rancher version: v2.9-1c2b815c8dd66e141b21630904127adc8e03c3de-head
- Installation option (Docker install/Helm Chart): Docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.28.10+rke2r1
- Cluster Type (Local/Downstream): Local
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? Admin
  - If custom, define the set of permissions:

**Describe the bug**
'Last Login' column in the User table is not populated with the value set in 'Default last login' within User Retention Settings.

**To Reproduce**
1. as an Admin user, go to Users & Authentication
2. create a user
3. click 'User retention settings'
4. check 'Disabled user accounts...'
5. set inactivity period to 2 hours (2h)
6. set cron job schedule to run every minute (*/1 * * * *)
7. set default last login to some time in the past (1720468680000) and save
8. wait 1 minute for cron job to execute
9. notice 'Last Login' column is not populated for the user created in step 2

**Result**
'Last Login' column in the User table is not populated with the value set in 'Default last login' within User Retention Settings.

**Expected Result**
'Last Login' column in the User table is populated with the value set in 'Default last login' within User Retention Settings.

**Screenshots**

https://github.com/rancher/rancher/assets/127343932/4311a791-9450-4265-b8af-7a5681ea78ba

After a couple of minutes:
<img width="1159" alt="Screenshot 2024-07-08 at 3 29 54 PM" src="https://github.com/rancher/rancher/assets/127343932/d66f3b4f-ac0d-420f-aae2-533bf7625797">

**Additional context**

**Comment by pmatseykanets** [comment]
This is not a bug. It's by design. The user-last-login-default doesn't affect the actual last login time but rather used on-the-fly by the user retention process instead of missing last login time.

**Comment by pmatseykanets** [comment]
There is however seemingly an issue/regression with the UI. The `{Disable|Delete}After` columns are not being displayed although user objects contain respective labels.

**Comment by samjustus** [comment]
@gaktive FYI on the regression Peter found.

**Comment by gaktive** [comment]
@yonasberhe23 are you seeing missing columns like @pmatseykanets is?

**Comment by yonasberhe23** [comment]
The `{Disable|Delete} After` columns only display when the `Last Login` column is populated which i believe is expected.

<img width="1285" alt="Screenshot 2024-08-15 at 9 58 50 AM" src="https://github.com/user-attachments/assets/6ef1bd3b-2a00-4c3d-9d26-e08f2a362b0b">

**Comment by pmatseykanets** [comment]
@rak-phillip @yonasberhe23 @gaktive It was negative relative time (duration) that led me to believe that there is a regression with displaying user retention columns. At the moment it's indistinguishable from the missing values.

**Comment by yonasberhe23** [comment]
sounds like its working as expected. closing as by design.
