### ISSUE TITLE
[Feature] [Metrics] Support for Server metrics output other than Graphite

### ISSUE THREAD

**Issue by johnrengelman** [rancher/rancher#4607]
Graphite doesn't have any type of security mechanism on it's protocol (it's just TCP). So the only way to secure is to use IP whitelist.

Would be super helpful to have a way to support different exports (such as InfluxDB directly) (I now Influx has a Graphite connector, but again, security).

I see the code is just configuring JMXTrans to export the JMX statistics to Graphite.

**Comment by johnrengelman** [comment]
Perhaps something in https://github.com/rancher/cattle/blob/master/code/framework/jmx/src/main/java/io/cattle/platform/jmx/JmxPublisherFactory.java that would allow for specifying the type of reporter to use?

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
