### ISSUE TITLE
[BUG] update CLI

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#46094]
https://jira.suse.com/browse/SURE-8659

**Comment by pmatseykanets** [comment]
- https://github.com/rancher/cli/releases/tag/v2.8.6-rc5
- https://github.com/rancher/cli/releases/tag/v2.9.0-rc6

**Comment by anupama2501** [comment]
Automation regression checks for 2.8.6-rc5 and 2.9.0-rc6 rancher CLI versions, have been run for the CLI checks:
1. Create/Delete namespaces
2. Create/Delete projects
3. Create/delete contexts
4. Create/delete catalogs
