### ISSUE TITLE
Data Center and Data Store not being sent for vSphere

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4609]
Version - v1.1.0-dev1-rc1

Steps to Reproduce: 
1.  Fill out all fields for vSphere host
2.  Create

Results: Data Center and Data Store are not being passed

Expected: Fields should be passed

**Comment by deniseschannon** [comment]
Verified with v1.1.0-dev1-rc2 that all commands are passed to the docker-machine command.
