### ISSUE TITLE
Removing Target/Host says text that makes it seem like we are deleting the host/container

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#461]
Version: Build from Master (4/7/15)

When I click on 'Remove Target or Host', it pops up the 'Delete' dialog box. 

As a user, it makes me think I'm deleting the host/container instead of just removing it from the LB. 

We need to change the text to indicate that we're removing it from the LB. 
Also, the ID of the container is shown instead of the name. 

![screen shot 2015-04-07 at 12 35 31 pm](https://cloud.githubusercontent.com/assets/11410997/7031749/cf13618a-dd22-11e4-9a6f-a15d1931a8b9.png)

**Comment by vincent99** [comment]
Technically it's showing the ID of the target, which is what's being removed, and doesn't have a name to display..  1**l**(oad)**b**(alancer)**t**(arget)2.  Will need to not use the generic delete confirmation for these.

**Comment by deniseschannon** [comment]
Oh, so since it's technically a target (regardless of the fact that it's a container that has a name), it's showing the ID. 

That's confusing for the user because in the UI of the list of targets, it shows the name of the container.

**Comment by vincent99** [comment]
Yes it needs a custom delete confirmation that will have a different messages.

**Comment by vincent99** [comment]
This is for the old standalone loadbalancer..
