### ISSUE TITLE
[v2.8] [RKE] Bump Components in rke-tools and confd 

### ISSUE THREAD

**Issue by kinarashah** [rancher/rancher#46117]
Backport of https://github.com/rancher/rancher/issues/46050

**Comment by kinarashah** [comment]
Changes merged in KDM `dev-v2.8` and Tagged RKE RC `v1.5.11-rc5`

**Comment by kinarashah** [comment]
https://github.com/rancher/rancher/pull/46118

**Comment by rishabhmsra** [comment]
Validated on rancher v2.8-head

- Created RKE1 node driver v1.28.11-rancher1-1 cluster(1-cp, 1-e, 1-w) using docker 25
- Created RKE1 node driver v1.27.15-rancher1-1 cluster(1-cp, 1-e, 1-w) using docker 24

Clusters provisioned successfully also validated etcd backup restore on both the clusters and it was successful.
