### ISSUE TITLE
[BUG] LastLogin is not set for SAML providers

### ISSUE THREAD

**Issue by pmatseykanets** [rancher/rancher#46124]
**Rancher Server Setup**
- Rancher version: 2.8.5
- Installation option (Docker install/Helm Chart): N/A
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: N/A
- Cluster Type (Local/Downstream): N/A

**User Information**
N/A

**Describe the bug**

The `lastLogin` user attribute is not set when user logs in using SAML authentication provider.

**To Reproduce**

- Enable a SAML authentication provider
- Login as a user using SAML provider
- Navigate to Users & Authentication -> Users
- Note that Last Login is not set for the user

**Result**

**Expected Result**

The `lastLogin` user attribute is set to the login time.

**Screenshots**

**Additional context**

**Comment by pmatseykanets** [comment]
## Validation Template

## What was fixed, or what change has occurred

When a user logs in uisng a SAML authentication provider the last login time now should be captured.

## Areas or cases that should be tested

- Enable a SAML provider
- Log in with a user using the SAML provider
- Check that the user's lastLogin user attribute and corresponding user label is updated
- Enable user retention
- Make sure that the user retention labels are set/updated correctly

## What areas could experience regressions

N/A.

## Are the repro steps accurate/minimal?

N/A.

**Comment by Priyashetty17** [comment]
Validated with `v2.9-f8c50bfbf0ae5d5008f1fb54d1d970fc1ea3ba36-head`
