### ISSUE TITLE
[2.8] LastLogin is not set for SAML providers 

### ISSUE THREAD

**Issue by pmatseykanets** [rancher/rancher#46125]
Backport #46124

**Comment by anupama2501** [comment]
**Test1:**

- Verified on v2.8-head `ff6ebb`
- Enabled okta auth
- Logged in as a user and verified the last login is updated.

**Test2:**

- Upgrade from v2.8.5 to v2.8-head `ff6ebb`
- Enabled okta on v2.8.5
- Logged in as a user from okta, verified last login is not updated.
- Upgraded rancher server
- Verified on a login of a user, last login is updated.

**Test3:**

- Upgraded from 2.8.5 to v2.9-head `37f6eebf6`
- Verified upon logging in users have last login updated.

**Test4:**

- Verified user attributes have lastLogin updated 
- Verified users have "cattle.io/last-login:" label updated  

**Test%:**

- Created rancher v2.8-head
- Enabled okta and logged in as a few users.
- Upgraded to rancher v2.9-head and verified the last login is updated for the users 

<img width="184" alt="2024-07-18_11-31-46" src="https://github.com/user-attachments/assets/283e0d64-757a-4026-b087-06bdc457c10c">
