### ISSUE TITLE
When creating from catalog, it's adding the port twice

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4613]
Version - v1.1.0-dev1-rc1

Steps to Reproduce: 
1.  Add https://github.com/tfiduccia/qa-catalog as your catalog
2.  Create Multiple services catalog
3.  Go to the catalog and look at the load balancer or the mysql service in the API

Results: It added the port twice

Expected: The port should only be added once

Comment - this is breaking when I try to export then import the yml.  So it really should be fixed

**Comment by deniseschannon** [comment]
Verified with v1.0.1-dev1-rc2 that the duplicate ports are not showing up.
