### ISSUE TITLE
Improve the logging for k3s based upgrader in Rancher

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#46147]
In Rancher, users can upgrade the k8s version of imported rke2/k3s clusters.  
This feature is implemented in the [package k3sbasedupgrade](https://github.com/rancher/rancher/blob/release/v2.9/pkg/controllers/management/k3sbasedupgrade/k3sbased_upgrade_handler.go).  
It is hard to diagnose problems related to this feature because there are no sufficient logging messages in rancher logs. 

Therefore, we would like to improve the logging messages in this area. 

 
SURE-7792

**Comment by jiaqiluo** [comment]
Notes to QA



To validate the enhancement, we will need to 

1. enable debug-level logging in rancher 
2. import an RKE2/k3s cluster
3. upgrade it to a newer version via Rancher UI
4. monitoring Rancher logs at the same time

We expect to see some info-level and debug-level messages whose prefix is `[k3s-based-upgrader]` during the cluster-upgrading process.

**Comment by Josh-Diamond** [comment]
Ticket #46147 - Test Results - ✅ 
---

Verified on Rancher `v2.9-25582765d25f0271f2ea648b3a29cca317b339ef-head`:

| Scenario | Test Case | Result |
|---|---|---|
| 1. | Enable debug level logging => import a standalone k3s cluster into rancher and upgrade k8s version => observe debug level `k3s-based-upgrader` logs | ✅ |

---

Scenario 1 -
1. Fresh install of Rancher `v2.9-head` w/ debug level logging enabled
2. Create a standalone k3s `v1.29.6+k3s2`, then import it into rancher
3. Once imported and `active`, `Edit Config` and upgrade k8s version to `v1.30.2+k3s2`
4. Verified - cluster successfully upgrades, debug level `k3s-based-upgrader` logs are seen and accurate:
```log
[DEBUG] [k3s-based-upgrader] upgrading cluster...
```
