### ISSUE TITLE
Remove old versions from `vsphere-charts`

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#46146]
vSphere CPI/CSI charts shipped with Rancher and RKE2 are based on https://github.com/rancher/vsphere-charts and it defines images to use based on `versionOverrides` mechanism, see below for reference:
* https://github.com/rancher/vsphere-charts/blob/8385f720967658ca982e127243b4e0289ac13b08/charts/rancher-vsphere-cpi/values.yaml#L34
* https://github.com/rancher/vsphere-charts/blob/8385f720967658ca982e127243b4e0289ac13b08/charts/rancher-vsphere-csi/values.yaml#L151

Currently, we define images for K8s versions going as far back as 1.18 which results in these images unnecessarily showing up on `rancher-images.txt` (e.g. https://github.com/rancher/rancher/releases/download/v2.8.5/rancher-images.txt) which not only increases the size of registry setup for airgap but also causes CVE scanning to pick up CVEs from these images that are not actually used.

Proposed solution:
1. Remove entries for K8s versions earlier than 1.27 from https://github.com/rancher/vsphere-charts
2. Update charts used by Rancher for 2.9 (https://github.com/rancher/charts/tree/dev-v2.9) to pull updated `vsphere-charts`
3. Ensure older CPI/CSI images are no longer present in `rancher-images.txt` generated (note this may not actually be true if file generation mechanism picks up transitive dependencies from used RKE2 versions that may still have older images referenced).

Note: At this time it's not expected that we will need to update vSphere charts targeting v2.8 (https://github.com/rancher/charts/tree/dev-v2.8). If a change will somehow be necessary and will need to be based on https://github.com/rancher/vsphere-charts with removed K8s versions, it can be addressed by re-introducing necessary `versionOverrides` for K8s 1.25 and 1.26 still supported by 2.8.x Rancher release line via updating/adding `.patch` files (e.g. https://github.com/rancher/charts/tree/dev-v2.8/packages/rancher-vsphere/rancher-vsphere-csi/generated-changes/patch for CSI chart).

**Comment by Josh-Diamond** [comment]
Ticket #46146 - Test Results - ✅ 
---

Verified on Rancher `v2.9.1-alpha1`:

expected versioning seen for vsphere CPI/CSI images in `rancher-images.txt` for `v2.9.1-alpha1`

CPI images packaged now reflect the following:
- `rancher/mirrored-cloud-provider-vsphere-cpi-release-manager:v1.26.1`
- `rancher/mirrored-cloud-provider-vsphere-cpi-release-manager:v1.27.0`
- `rancher/mirrored-cloud-provider-vsphere-cpi-release-manager:v1.28.0`
- `rancher/mirrored-cloud-provider-vsphere-cpi-release-manager:v1.29.0`
- `rancher/mirrored-cloud-provider-vsphere-cpi-release-manager:v1.30.1`

CSI images packaged now reflect the following:
- `rancher/mirrored-cloud-provider-vsphere-csi-release-driver:v3.0.1`
- `rancher/mirrored-cloud-provider-vsphere-csi-release-driver:v3.1.2`
- `rancher/mirrored-cloud-provider-vsphere-csi-release-driver:v3.2.0`
- `rancher/mirrored-cloud-provider-vsphere-csi-release-driver:v3.3.0`
- `rancher/mirrored-cloud-provider-vsphere-csi-release-syncer:v3.0.1`
- `rancher/mirrored-cloud-provider-vsphere-csi-release-syncer:v3.1.2`
- `rancher/mirrored-cloud-provider-vsphere-csi-release-syncer:v3.2.0`
- `rancher/mirrored-cloud-provider-vsphere-csi-release-syncer:v3.3.0`
