### ISSUE TITLE
Shouldn't be able to create service with two of the same private/public ports

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4614]
Version: v1.0.1

Steps to Reproduce: 
1.  Create a LB or a Service with the two ports with the same private/public number

Results: If you clone you will see that both are saved, if you look in the description you only see one.

Expected: You probably should not be able to have two of the same exact port numbers.  This messes up your export/import config.

**Comment by vincent99** [comment]
LB has validation for this in 1.2, adding for service now.

**Comment by tfiduccia** [comment]
Version - master 12/19
Verified fixed
