### ISSUE TITLE
Kubernetes environment stuck at "Waiting for Kubernetes API"

### ISSUE THREAD

**Issue by aboyett** [rancher/rancher#4615]
Rancher Version:
1.0.1

Docker Version:
1.10.3

OS: 
CoreOS 1010.1.0

Steps to Reproduce: 
Create Kubernetes environment in Rancher.
Stand up machines running CoreOS. Launch rancher-agent with token for above environment.

Results: 
- Rancher creates all kuberenetes service containers on the host(s.)
- Rancher UI never progresses past "Waiting for Kubernetes API"
- Browser debugging console yields a 503 error on api route:
```
Request URL:http://192.168.50.3:8080/r/kubernetes/api
Request Headers:
Accept:application/json
Referer:http://192.168.50.3:8080/env/1a44/kubernetes/waiting
User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36
x-api-csrf:9872A8D19BC54214BFD4B21C0C6655C4
x-api-no-challenge:true
x-api-project-id:1a44
X-Requested-With:XMLHttpRequest
```
- Attaching into the kubectld container and executing kubectl confirms that the Kubernetes API server is running:
```
> kubectl get services
NAME         CLUSTER_IP   EXTERNAL_IP   PORT(S)   SELECTOR   AGE
kubernetes   10.43.0.1    <none>        443/TCP   <none>     20m
> kubectl version
Client Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.7", GitCommit:"e4e6878293a339e4087dae684647c9e53f1cf9f0", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2+", GitVersion:"v1.2.0-rancher-1", GitCommit:"ed6532f975cff184196dbe214de8fa0198b415ef", GitTreeState:"clean"}
```

Expected:
Rancher UI is able to successfully reach the Kubernetes API server and allows use of the Kubernetes environment from a browser.

Or, in the event of errors like this, at least allows the user to bypass the "Waiting for Kubernetes API" /kubernetes/waiting screen, and get access to Kubernetes API keys so they can use kubectl on their machine to debug connectivity from outside of the containers themselves.

**Comment by aboyett** [comment]
Additional info:

IPtables rules from the host running kubernetes api server:
```
# iptables-save | grep 443
-A KUBE-PORTALS-CONTAINER -d 10.43.0.1/32 -p tcp -m comment --comment "default/kubernetes:https" -m tcp --dport 443 -j REDIRECT --to-ports 45131
-A KUBE-PORTALS-HOST -d 10.43.0.1/32 -p tcp -m comment --comment "default/kubernetes:https" -m tcp --dport 443 -j DNAT --to-destination 192.168.50.23:45131
```

Attempting to telnet from rancher-server host to the kubernetes apiserver container host does yield an open socket:
```
andy@brizo:/$ telnet 192.168.50.23 45131
Trying 192.168.50.23...
Connected to 192.168.50.23.
Escape character is '^]'.
GET /

Connection closed by foreign host.
```

**Comment by aboyett** [comment]
FYI, restarting rancher-server resolved the issue in all environments experiencing the issue.

**Comment by alena1108** [comment]
@aboyett could you also attach cattle-debug.log? Want to look at websocket proxy logs that went there

**Comment by aboyett** [comment]
Here's the cattle-debug log for that day. If you recall, we were actively debugging this between 21:30 and 22:30.

[cattle-debug.2016-04-29.log.gz](https://github.com/rancher/rancher/files/243728/cattle-debug.2016-04-29.log.gz)

Let me know if you need any more files.

**Comment by alena1108** [comment]
@aboyett thank you.

I've just hit the same bug myself, and my host wasn't re-added. The error coming from websocket proxy is: 

```
time="2016-05-05T09:48:00-07:00" level=info msg="Invalid backend host requested." hostUuid=53fab1bd-2a55-4107-869a-3b094175bf1b
```
Looks like some bug in websocket proxy

**Comment by jtwebman** [comment]
I have the same issue and restarting the rancher-server isn't getting me past the issue.

**Comment by alena1108** [comment]
@jtwebman if rancher restart doesn't fix it, it would most likely mean that you are hitting a k8s bug that I've described here:

https://github.com/rancher/rancher/issues/4838

You can check "kubernetes" container logs, and if you see panic errors there, that would be the proof tha you are hitting k8s bug. 

In @aboyett case kubernetes api server was serving the response (we've checked it by executing kubectl calls omitting the UI), yet websocket proxy couldn't connect to it.

In both cases UI will present an error "Waiting for Kubernetes API"

**Comment by alena1108** [comment]
@cjellick looks similar to the websocket proxy issue you've fixed. Basically after running for a while, Rancher could no longer communicate to kubectl service via websocket proxy. Websocket proxy restart fixed the issue.

@aboyett the issue is not easy to reproduce, but we've put fixes to websocket proxy for the area responsible for handling server-to-server-over-websocketproxy connections

**Comment by cjellick** [comment]
Should be fixed. The websocket-proxy fixes we provided to our customer were verified and they no longer experience k8s + wsp issues.

Can we close @sangeethah ?

**Comment by sangeethah** [comment]
@aboyett , there are websocket-proxy fixes provided that prevented rancher from being able to communicate with kubectl service via websocket proxy in rancher-server version v1.1.3.

You should not be hitting this issue anymore when testing with rancher-server version v1.1.3 or above.

**Comment by nc-ruth** [comment]
If you came here for a rancher desktop issue, then  try to turn off your VPN (if it is enabled).
