### ISSUE TITLE
[v2.8] [RFE] Add CIS-1.9 (k8s v1.27-1.29) Scan capability 

### ISSUE THREAD

**Issue by krunalhinguu** [rancher/rancher#46154]
CIS Workbench has released [CIS-1.9](https://github.com/aquasecurity/kube-bench/commit/7027b6b2ec63686bd1fb4270485cd9d1e651a6d3) for Kubernetes, This issue tracks the creation and integration of CIS-1.9 into rancher/security-scan. Once the CIS-1.9 profile becomes available upstream, we will proceed with integrating it into rancher/charts cis-benchmark.

previous issue: https://github.com/rancher/rancher/issues/43159

**Comment by mitulshah-suse** [comment]
Closing in favor of https://github.com/rancher/rancher/issues/46881
