### ISSUE TITLE
[Design] Imperative Resource API

### ISSUE THREAD

**Issue by MbolotSuse** [rancher/rancher#46166]
**Is your feature request related to a problem? Please describe.**
When migrating resources to the Rancher Kubernetes API, there are some resources (e.g. tokens) which don't fit within the standard CRD model. For these resources, we need an API which can be imperative, secure, and documented. 

**Describe the solution you'd like**
We should evaluate the feasibility of using a combination of [Kubernetes API Extensions](https://kubernetes.io/docs/tasks/extend-kubernetes/setup-extension-api-server/) and steve. Since not all consumers can configure the API Server to work with API aggregation (e.x. users who are in a public cloud environment), we can make endpoints which are compatible with API extensions, but these endpoints need to be usable outside of that context as well.

Tokens should be used as an example resource, due to the difficulties with that type. The produced design should include a feasible Tokens implementation, but should focus on the API Frameworks required to realize that vision. The actual tokens implementation should be done as a part of another ticket.

**Describe alternatives you've considered**
N/A.

**Additional context**
While we should evaluate the feasibility of tokens in this context, the actual tokens implementation should take place as part of another ticket.

**Comment by tomleb** [comment]
Imperative API RFC has been approved and we're starting the work on this in https://github.com/rancher/rancher/issues/47010.
