### ISSUE TITLE
[BUG] Unable to provision downstream RKE2/K3s clusters, stuck at `waiting for cluster agent to connect`

### ISSUE THREAD

**Issue by markusewalker** [rancher/rancher#46160]
**Rancher Server Setup**
- Rancher version: `v2.9-head`
- Installation option (Docker install/Helm Chart): Docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: `v1.30.2+rke2r1`
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): RKE2/K3s

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Admin/standard
  - If custom, define the set of permissions:

**Describe the bug**

When attempting to provision a downstream RKE2/K3s cluster, it is stuck at the following state:

![image](https://github.com/user-attachments/assets/0cc79ba2-26f3-4309-80ee-765d972720d1)

Additionally, it seems that this may be caused as the Rancher tag is incorrectly shown as `dev`:

![image](https://github.com/user-attachments/assets/c0b954ae-1266-4e1a-bdb7-01262f428747)

This is a blocker and needs to be addressed to properly provision downstream clusters.

**To Reproduce**

1. Setup Rancher v2.9-head.
2. Attempt to provision a downstream RKE2 or K3s cluster.
     - I used 1 etcd, 1 cp, 1 worker (v1.30.2)
3. Note that you get stuck at the message highlighted in the issue description.

**Result**
Unable to provision downstream clusters in latest v2.9-head.

**Expected Result**

Should be able to provision downstream clusters in latest v2.9-head.

**Comment by snasovich** [comment]
Likely the same exact root cause as https://github.com/rancher/rancher/issues/46152

**Comment by snasovich** [comment]
@samjustus , nope. Testing on `v2.9-head` (a402bfa1ff0cc051cfabe3d9380b7eca678443f9) I still see the following in manifest for importing K8s cluster:
```
          image: rancher/rancher-agent:
```

**Comment by gaktive** [comment]
UI QA blocked on this for their provisioning tests for RKE2.

**Comment by markusewalker** [comment]
Validated that this is addressed in https://github.com/rancher/rancher/commit/f8c50bfbf0ae5d5008f1fb54d1d970fc1ea3ba36. I am able to successfully provision downstream RKE1/RKE2/K3S clusters. Marking this as closed.

**Comment by snasovich** [comment]
This should be fixed now in the newest `v2.9-head` (f8c50bfbf0ae5d5008f1fb54d1d970fc1ea3ba36)
Moving to test.

![image](https://github.com/user-attachments/assets/6d33c1b3-747d-4cdd-bb54-283aa7fed682)
![image](https://github.com/user-attachments/assets/7fd3207e-530e-40ba-b8ae-2000b51422d5)
