### ISSUE TITLE
[2.9] Panic setting password to Azure AD (Entra ID) user

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#46161]
backport https://github.com/rancher/rancher/issues/45451

**Comment by anupama2501** [comment]
Verified on v2.9-head `8bd2e564f`

**SetPassword:**
1. Enabled openldap auth
2. Logged in as a few users from auth provider.
3. As an admin, updated the password for a user from auth provider.
4. Verified the following error is displayed: `Cannot set password of non-local user`

**Refreshed provider access:**

1. Verified no errors while refreshing the provider accesss

**ChangePassword:**
1. From kubectl edit user <userID>, updated mustChangePassword: true
2. Logged in as user from auth provider.
3. Login returned successful but the user could not actually login to rancher >> this is also the same behavior in 2.8.5 https://github.com/rancher/rancher/issues/46558



**Terraform:**

1. Imported the user via terraform
2. Updated the password 
3. Verified the following error is displayed: ` Body: [baseType=error, code=ServerError, message=Cannot set password of non-local user]`

**Upgrade rancher from 2.8.5 >> 2.9-head**
1. After the repro steps from the above comment, upgraded rancher server to v2.9-head
2. Verified changing password doesnt cause a panic.
3. Verified error is displayed to the users.

**Regression Checks:**

1. Local user mustChangePassword: Successful
2. Set new password: Successful
3. standard user update password: Expected fail 
4. Updated the username on the auth provider user by running k edit user <uid>
     - Updated username: uid3
     - Verified user is switched to user local principalID
     - Updated the password and verified update works.
