### ISSUE TITLE
[BUG] Error log seen when logging in as azure AD Page Iterator received incorrect value of type *models.DirectoryRole in rancher logs

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#46167]
**Rancher Server Setup**
- Rancher version: v2.9-head `3c4ccdc5bc`
- Installation option (Docker install/Helm Chart): Docker install
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):

**Information about the Cluster**
- Kubernetes version: Local
- Cluster Type (Local/Downstream): `v1.30.2+k3s2`

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Admin

**Describe the bug**
Enabling and logging in as azure AD auth user returns an error log in rancher logs. 

**To Reproduce**
1. Enable azure ad auth on rancher
2. Logout and login as the admin user for which the auth is enabled.

**Result**
Notice the error logged in the rancher logs 
```
2024/07/15 21:36:52 [ERROR] [AZUREAD_PROVIDER] Page Iterator received incorrect value of type *models.DirectoryRole
```
**Expected Result**
Expected no errors in rancher logs.

**Additional context**

- Does not happen with all users only a few users.
- Does not happen on v2.8.5.

**Comment by JonCrowther** [comment]
I have tried a few installs of rancher with AzureAD and I am unable to reproduce this problem. I occasionally see this error the very first time I enable AzureAD, but it goes away quickly.
```
2024/08/01 13:50:25 [ERROR] [AZUREAD_PROVIDER_CACHE] Failed to read the access token from Kubernetes: error getting secret cattle-global-data:azuread-access-token: secrets "azuread-access-token" not found
```
