### ISSUE TITLE
[BUG] Webhook must only accept "true" for setting annotation cattle.io/force

### ISSUE THREAD

**Issue by maxsokolovsky** [rancher/rancher#46189]
**Rancher Server Setup**
- Rancher version: 2.9.0
- Installation option (Docker install/Helm Chart): Any
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: 1.28
- Cluster Type (Local/Downstream): Local

**Describe the bug**

If agent-tls-mode has default or value updated from system-store to strict, then all non-local clusters must have a status condition AgentTlsStrictCheck set to True, unless the new setting has an overriding annotation cattle.io/force=true.

Currently, the webhook just checks for the presence of the annotation, ignoring its value. It should actually only honor the override if the value is "true" and no other.

**To Reproduce**

Have some downstream cluster whose `AgentTlsStrictCheck ` condition is "False". Try to edit the `agent-tis-mode` setting resource using the Rancher UI or kubectl - change the value or default from `system-store` to `strict`. The webhook should reject this. Now try to provide an overriding annotation on the setting `cattle.io/force=false`. The annotation shouldn't help you override the webhook check with this value.

**Result**

The `cattle.io/force=false` annotation is still a valid override (which is a small defect), because the webhook thinks the mere presence of the annotation is enough to signify intent to override, regardless of the value.

**Expected Result**

Any value other than "true" isn't a signal to the webhook to override its check of `agent-tls-mode` setting mutation.

**Additional context**

**Comment by maxsokolovsky** [comment]
Backport issue: https://github.com/rancher/rancher/issues/46190

**Comment by MKlimuszka** [comment]
Required PR: https://github.com/rancher/webhook/pull/462

**Comment by brudnak** [comment]
| Component                        | Version / Type                      |
| -------------------------------- | ----------------------------------- |
| Rancher version starting         | v2.9.1-rc2                          |
| Installation option              | Helm (high availability)            |
| RKE binary version used          | v1.5.10                             |
| Authentication providers enabled | local                               |
| Logged in user role              | admin                               |
| Browser type                     | Firefox Developer Edition           |
| Browser version                  | 129.0b5 (64-bit)                    |
| Dashboard                        | master 102f1e6                      |
| Webhook version                  | rancher/rancher-webhook:v0.5.1-rc.1 |

<details>
    <summary>🏗️ Rancher Installation Details... CLICK TO EXPAND! ⬅️</summary>

```sh
kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.15.0/cert-manager.crds.yaml

# Add the Jetstack Helm repository
helm repo add jetstack https://charts.jetstack.io

# Update your local Helm chart repository cache
helm repo update

# Install the cert-manager Helm chart
helm install cert-manager jetstack/cert-manager \
  --namespace cert-manager \
  --create-namespace \
  --version v1.15.0
```

`https://letsencrypt.org/certificates/` >>> `ISRG Root X1` >>> `pem`

```sh
kubectl -n cattle-system create secret generic tls-ca \
  --from-file=cacerts.pem=./cacerts.pem
```

```sh
helm install rancher rancher-alpha/rancher --devel \
  --namespace cattle-system \
  --set hostname=$REDACTED_URL \
  --set ingress.tls.source=letsEncrypt \
  --set letsEncrypt.email=$REDACTED_EMAIL \
  --set letsEncrypt.ingress.class=nginx \
  --set bootstrapPassword=$REDACTED_PASSWORD \
  --set rancherImage=rancher/rancher \
  --set rancherImageTag=v2.8-head \
  --version 2.9.1-rc2 \
  --set global.cattle.psp.enabled=false \
  --set agentTLSMode=system-store \
  --set privateCA=true
```

</details>

<hr>

<a name="top"></a>

### 🧪 Test Cases

| \#  | Priority | Description & Link                                              | PASS/FAIL |
| --- | -------- | --------------------------------------------------------------- | --------- |
| 1   | P0       | [Set cattle.io/force to expected string](#test-1)               | ✅ PASS    |
| 2   | P0       | [Attempt Setting cattle.io/force to bool](#test-2)              | ✅ PASS    |
| 3   | P0       | [Attempt Setting cattle.io/force to slice](#test-3)             | ✅ PASS    |
| 4   | P0       | [Attempt Setting cattle.io/force to unexpected string](#test-4) | ✅ PASS    |
| 5   | P0       | [Attempt Setting cattle.io/force to int](#test-5)               | ✅ PASS    |
| 6   | P0       | [Upgrade](#test-6)                                              | ✅ PASS    |



<details>
    <summary>🚨 6 test cases... CLICK TO EXPAND! (For table links to work) ⬅️</summary>

<br>

# 1 / Set cattle.io/force to expected string Status: ✅ PASS  

<a name="test-1"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 1 details... Click to expand</summary>

**Test Steps for Validation**

1. Start Rancher with `--set agentTLSMode=strict`
2. Create a downstream cluster
3. Ensure this downstream cluster has `AgentTlsStrictCheck` set to false
   - This can be checked by going to cluster management > edit the downstream cluster as yaml > check under status at the bottom for `AgentTlsStrictCheck`

        ```yaml
        status: 'False'
        type: AgentTlsStrictCheck
        ```
4. Now try changing the agent-tls-mode setting to strict using the Rancher UI
5. This can be accessed from starting at `dashboard/home` > click `Global Settings` (bottom left globe icon) > `Settings` > click the ellipsis (three dots) at the setting `agent-tls-mode` > `Edit Setting` > change the value to Strict > `Save`
6. This should fail as `agentTLSMode` is set to `strict`
7. Now edit the `agent-tls-mode` setting using kubectl > `kubectl edit setting agent-tls-mode`
8. Add this annotation under metadata:

    ```yaml
    metadata:
      annotations:
        cattle.io/force: "true"
    ```
9. After this annotation is added try changing the agent-tls-setting to strict using kubectl
10. Now even if there is a downstream cluster that has `AgentTlsStrictCheck` set to false the webhook will allow it now

**✅ Expected Outcome**

With having the `cattle.io/force: "true"` set, nw even if there is a downstream cluster that has `AgentTlsStrictCheck` set to false the webhook will allow it

**✅ Actual Outcome**

Webhook allows the change now

</details>

<hr>

# 2 / Attempt Setting cattle.io/force to bool Status: ✅ PASS  
<a name="test-2"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 2 details... Click to expand</summary>

**Test Steps for Validation**

1. Edit the `agent-tls-mode` setting using kubectl > `kubectl edit setting agent-tls-mode`
2. Add this annotation under metadata:
3. Try replacing `<add_value_here>` with the following:
   1. `true`
   2. `True`
   3. `false`
   4. `False`
   5. **NOTE: THESE ARE NOT strings E.G. `"true"`

    ```yaml
    metadata:
      annotations:
        cattle.io/force: <add_value_here>
    ```

**✅ Expected Outcome**

An error

**✅ Actual Outcome**

Receive the following error: `The edited file had a syntax error: unable to decode "edited-file": json: cannot unmarshal bool into Go struct field ObjectMeta.metadata.annotations of type string`

</details>

<hr>

# 3 / Attempt Setting cattle.io/force to slice Status: ✅ PASS  

<a name="test-3"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 3 details... Click to expand</summary>

**Test Steps for Validation**

1. Edit the `agent-tls-mode` setting using kubectl > `kubectl edit setting agent-tls-mode`
2. Add this annotation under metadata:
3. Try replacing `<add_value_here>` with the following:
   1. `["true"]`

    ```yaml
    metadata:
      annotations:
        cattle.io/force: <add_value_here>
    ```

**✅ Expected Outcome**

An error

**✅ Actual Outcome**

`# The edited file had a syntax error: unable to decode "edited-file": json: cannot unmarshal array into Go struct field ObjectMeta.metadata.annotations of type string`


</details>

<hr>

# 4 / Attempt Setting cattle.io/force to unexpected string Status: ✅ PASS 

<a name="test-4"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 4 details... Click to expand</summary>

**Test Steps for Validation**

1. Edit the `agent-tls-mode` setting using kubectl > `kubectl edit setting agent-tls-mode`
2. Add this annotation under metadata:
3. Try replacing `<add_value_here>` with the following:
   1. `""`
   2. `"1"`
   3. `"test"`

    ```yaml
    metadata:
      annotations:
        cattle.io/force: <add_value_here>
    ```

**✅ Expected Outcome**

These values are saved, but do not allow the changing of the tls setting 

**✅ Actual Outcome**

Edit goes through but when trying to change the TLS setting get the error: `admission webhook "rancher.cattle.io.settings.management.cattle.io" denied the request: value.default: Forbidden: AgentTlsStrictCheck condition of cluster c-m-7lrcht5m isn't 'True'`

</details>

<hr>

# 5 / Attempt Setting cattle.io/force to int Status: ✅ PASS 

<a name="test-5"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 5 details... Click to expand</summary>

**Test Steps for Validation**

1. Edit the `agent-tls-mode` setting using kubectl > `kubectl edit setting agent-tls-mode`
2. Add this annotation under metadata:
3. Try replacing `<add_value_here>` with the following:
   1. `1`
   2. `0`
   3. `-1`

    ```yaml
    metadata:
      annotations:
        cattle.io/force: <add_value_here>
    ```


**✅ Expected Outcome**

An error

**✅ Actual Outcome**

`# The edited file had a syntax error: unable to decode "edited-file": json: cannot unmarshal number into Go struct field ObjectMeta.metadata.annotations of type string`


</details>

<hr>

# 6 / Upgrade Status: ✅ PASS 

<a name="test-6"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 6 details... Click to expand</summary>

**Test Steps for Validation**

1. Start with a version of Rancher without the fix
2. Upgrade Rancher to a version with the fix
3. Repeat all of the test cases on this setup


**✅ Expected Outcome**

All tests to pass on an upgraded setup

**✅ Actual Outcome**

All tests passing

</details>

<hr>

</details>
