### ISSUE TITLE
If I do a search in processes, it still searches after I left the page.

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4618]
Version - v1.0.1

Steps to Reproduce: 
1.  Open the developer tools
2.  Go to Processes page
3.  Do a search
4.  Leave the processes page

Results: In the dev tools you can see that processes page is still logging even thou I left the page.
processinstances?endTime_null=true&limit=100&sort=id&order=desc/v1

Expected: Should stop searching and logging

**Comment by vincent99** [comment]
I think this was fixed somewhere in 1.2

**Comment by tfiduccia** [comment]
Now this is happening with Audit Log page instead.

**Comment by vincent99** [comment]
Re-checked audit log, processes, and HA, all had race conditions if you leave the page at just while it's reloading.

**Comment by tfiduccia** [comment]
Version - master 12/19
Verified fixed
