### ISSUE TITLE
Enable renovate's auto PR approval for rancher/lasso

### ISSUE THREAD

**Issue by tomleb** [rancher/rancher#46199]
# Summary

Frameworks repos should have a minimum requirement of 2 approvals before a PR can be merged. To speed up the renovate merge process, we want to allow a single approval before merging.

To do so, we'll make use of renovate's [autoApprove](https://docs.renovatebot.com/configuration-options/#autoapprove) setting. (I haven't tested it yet, let's see if renovate is able to approve its own PR).

**Comment by MKlimuszka** [comment]
Closing this and will make a new more general ticket to address the ask.
