### ISSUE TITLE
Adding Replica Sets panel in Kubernetes UI

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#4619]
Rancher Version:
1.0.1
Docker Version:
1.10.1

The [Replicasets](http://kubernetes.io/docs/user-guide/replicasets/) from extensions/v1beta should appear in the UI the same way as the replication controllers, when you create a replica set only the controlled pods appear but not the replica set.

The replica sets are related to "Deployments" which i believe its support is mentioned in this #4431

**Comment by tfiduccia** [comment]
Version - 1.2.0-pre1-rc1
Verified Fixed
