### ISSUE TITLE
[v2.9] No v1.30.x version available for gke cluster

### ISSUE THREAD

**Issue by vardhaman22** [rancher/rancher#46215]
there is no v1.30 version available in rancher  v2.9-head. for gke So testing is blocked for gke cluster for v1.30
![gke](https://github.com/user-attachments/assets/47e94f1d-f5f9-4b04-9392-26ac44d66644)

**Comment by snasovich** [comment]
@kkaempf / @mbologna , sending it to Highlander team to review and determine next steps.
My (very limited) understanding is we're using release channel that doesn't have 1.30 in there yet (https://cloud.google.com/kubernetes-engine/docs/release-schedule). Will 1.30 automatically appear once it's available in that channel?

If so, we should probably move this issue to `v2.9-Next2` milestone and test then when it's available.

**Comment by cpinjani** [comment]
Additional info:
Current versions list on UI seems matching with GKE [NoChannel](https://cloud.google.com/kubernetes-engine/docs/release-notes-nochannel#July_17_2024) versions.

![image](https://github.com/user-attachments/assets/1a8ddb2d-3557-44d5-8425-3283fd596ad6)

**Comment by mjura** [comment]
Everything is fine according to https://cloud.google.com/kubernetes-engine/docs/release-schedule GKE v1.30 will be released in August this year, after releasing it Kubernetes list in Rancher will be updated automatically.

**Comment by mjura** [comment]
Nothing to do it can fixed
