### ISSUE TITLE
Configure `renovatebot` for `rancher/rke-tools`

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#46223]
Configure `renovatebot` for https://github.com/rancher/rke-tools to automate updates like https://github.com/rancher/rke-tools/pull/187 / https://github.com/rancher/rke-tools/pull/184

Exact scope as well as specific tools (though `renovatebot` is the standard) is open to updates/refinement.

**Comment by vardhaman22** [comment]
[PR](https://github.com/rancher/rke-tools/pull/192) for adding renovate workflow to rke-tools is merged.  The workflow is also running fine and automated PRs are being created for various components (like https://github.com/rancher/rke-tools/pull/193 and https://github.com/rancher/rke-tools/pull/201) hence closing the issue
