### ISSUE TITLE
Support `cgroup v2` for v2prov tests

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#46222]
v2prov tests were not working with standard GHA runners and the issue was pinpointed to cgroups v2 being default in `ubuntu-latest` runners (22.04).

To work around this issue, custom runners with cgroups v1 configured instead of cgroups v2 are used: https://github.com/rancher/rancher/blob/7df10c297f33aa92ce57d4e3c162aea44418b9b3/.github/workflows/provisioning-tests.yml#L23

Summary of initial thoughts on this from @jakefhyde:
> My immediate thoughts are related to cgroupsv2. I think 20.04 defaulted to cgroups v1, and 22.04 defaulted to v2. Never had any issues running `make provisioning-tests` on mac, but something about the "systemd in a container in a pod in an embedded k3s cluster inside the rancher binary inside the dapper container" doesn't seem to be playing nice on linux. For a short while (I think until we added either 1.24 or 1.25 (not saying that's related, just thats the milestone I noticed it at)) I was able to run the provisioning-tests when we introduced the cgroups evacuation workaround in CI, but at some point that stopped working and there are so many moving parts I haven't really been able to properly RCA it.

Also from @Oats87:
> lots of log bleed (`systemd-journald` is reporting logs it shouldn't be within the `systemd-node` containers)

> the `noop.service` that we use for `systemd-node` was actually failing because the `journalctl` command would fail. and from what I can tell, it's because `systemd-journald` would get poked _somewhere_ on the host and it would cause all of the instances from a global level to get kicked... so to me it seemed like the "global" `systemd` was kicking all instances of `systemd-journald` it could find.

**Comment by vardhaman22** [comment]
tried to run provisioning-tests on ubuntu 22.04 but the etcd container was exiting and continuously restarting.
i tried removing the custom userdata which was added to force rke2 and k3s tests to run with cgroupfs but that also did not work totally. It did make some progress on one of the nodes for a three node cluster test, pods came up fine on one of the nodes but then after that other nodes were not getting registered.

**Comment by snasovich** [comment]
Closing this as https://github.com/rancher/rancher/pull/47789 was merged and made into `main` (and https://github.com/rancher/rancher/blob/release/v2.10 was branched off after this change was merged) and provisioning tests are working as expected since the merge, e.g. https://github.com/rancher/rancher/actions/runs/11820626909/job/32933375574

FYI @daviswill2 - it's `QA/None`
