### ISSUE TITLE
Non-Admins can't get machine drivers (can't add hosts)

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4623]
Version - v1.1.0-dev1-rc1

Steps to Reproduce: 
1.  Enable Github authentication
2.  Create a environment and add another github member/owner
3.  Log in as other github person
4.  Try to add a host

Results: 404 page.  Since the user is not a "admin", they are not able to get the machine drivers.

Expected: Should be able to add hosts

**Comment by soumyalj** [comment]
Followed the steps above. I was able to successfully add a new host using the second github member and create a new container. Verified on v1.1.0-dev1-rc3
