### ISSUE TITLE
[v2.8] [BUG] MachineHealthCheck Object not deleted properly

### ISSUE THREAD

**Issue by jakefhyde** [rancher/rancher#46237]
Backport of https://github.com/rancher/rancher/issues/46236

**Rancher Server Setup**
- Rancher version: 2.8.5
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: 1.28.9
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Vsphere

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Admin
  - If custom, define the set of permissions:

**Describe the bug**

If you have 2 node pools, and both have a value greater than 0 for Auto Replace , I see a MachineHealthChecks object is created for both as expected. If you change one to 0 it will delete that MachineHealthChecks object. However, if you specify both pools to 0 at the same time, it won't delete any. If you set one pool to 0 and save, and then set another pool to 0 it will delete the first one, but the second one stays. If you change the first pool back to greater than 0, it deletes the other pools MachineHealthChecks object if it is still equal to zero and create the new object for the pool you just changed the value on.
**To Reproduce**

1. Create a Downstream Vsphere Cluster with 2 Node pools
2. Make sure both have Auto Replace with a setting greater than 0
3. Set the first node pool Auto Replace value to 0
4. Check machinehealthchecks objects and see only 1 remains for that cluster
5. Set the second node pool Auto Replace value to 0
6. See that machinehealthchecks object for that pool still exists thus making auto replace still functioning

**Result**
Auto Replace not turned off on remaining node pool
**Expected Result**

Auto Replace is turned off as expected
**Screenshots**

**Additional context**

**Comment by rishabhmsra** [comment]
Validated on v2.8.6 HA setup on AWS with RKE2 v1.28.12+rke2r1 as local cluster and issue is reproducible.

Validated on rancher v2.8.7-rc1 :
-
- Created rancher v2.8.7-rc1 HA setup on AWS with RKE2 v1.28.12+rke2r1 as local cluster. 
- Created RKE2 node driver cluster with Auto Replace value to set to 1 on AWS with 2 machine pools(1-cp,e and 1-w). 
- Validated machinehealthchecks objects created for both the machine pools in local cluster.

![mh](https://github.com/user-attachments/assets/bc29106f-716a-4189-95f9-d639f5bd7fdc)

Case 1 updating Auto Replace value one by one:
- 
- Updated Auto Replace value to 0 for first machine pool and validated that machinehealtcheck object deleted for it:

![mh1](https://github.com/user-attachments/assets/f1d2160f-bd28-4e00-9659-65e3f314daac)

- Now updated Auto Replace value to 0 for second pool and validated machinehealtcheck object deleted for it as well:

![mh2](https://github.com/user-attachments/assets/d2395b2f-1c22-4cea-a596-c5596e439baf)

Case 2 updating Auto Replace value simultaneously :
-
- Updated Auto Replace value to 1 in both machine pools and validated machinehealtcheck object created successful for both the pools.

![mh3](https://github.com/user-attachments/assets/17e1561a-ce60-4ace-890a-2d306d6d3467)

- Now updated Auto Replace value to 0 in both the machine pools and machinehealtcheck object deleted for both the pools in local cluster:

![mh4](https://github.com/user-attachments/assets/62f6275b-afb8-4522-880b-061539c90dd6)
