### ISSUE TITLE
[v2.8] Old Ubuntu 20.04 AMIs are used by default when provisioning downstream clusters in AWS

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#46242]
Backport of https://github.com/rancher/rancher/issues/46241 to v2.8.x release line

**Comment by jiaqiluo** [comment]
The fix can be validated on the latest v2.8-head image

**Comment by markusewalker** [comment]
Validated that this issue, see details below:

**ENVIRONMENT DETAILS**
	- Rancher install: Docker
	- Rancher version: `v2.8-head` https://github.com/rancher/rancher/commit/034572ee4a7c2e5cdb93073bbce3c791fb0cd857

**TEST RESULT**
|#|Scenario|Result
|---|---|---|
|1|Provision RKE1 downstream node driver w/AWS defaults|:white_check_mark:|
|2|Provision RKE2 downstream node driver w/AWS defaults|:white_check_mark:|
|3|Provision K3S downstream node driver w/AWS defaults|:white_check_mark:|

**VALIDATION STEPS**

**Scenario 1**
1. Provisioned downstream RKE1 `v1.28.12-rancher1-1` AWS node driver cluster.
     - Ensured that I used the default AMI.
2. Validated that cluster and nodes came up as `Active`.
3. Validated that the OS used is Ubuntu 22.04 for each node in the cluster.

_____

**Scenario 2**
1. Repeated scenario, but provisioned RKE2 `v1.28.11+rke2r1` AWS node driver cluster instead.

______

**Scenario 3**
Repeated scenario, but provisioned K3S `v1.28.11+k3s2` AWS node driver cluster instead.
