### ISSUE TITLE
[BUG] Agent fails to connect when using `agent-tls-mode` set to `system-store`

### ISSUE THREAD

**Issue by MbolotSuse** [rancher/rancher#46257]
**Rancher Server Setup**
- Rancher version: v2.8-head
- Installation option (Docker install/Helm Chart): Docker install, proxied by Nginx
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): k3s v1.28.6+k3s2
- Proxy/Cert Details: Proxied by nginx, using `ngrok http --inspect=false https://localhost:8081/`

**Information about the Cluster**
- Kubernetes version: 
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):
   k3s v1.28.11+k3s2, digital ocean

**User Information**
- What is the role of the user logged in? Admin
  - If custom, define the set of permissions: N/A

**Describe the bug**
When running rancher in a proxy mode but not providing `--no-cacerts`, Rancher fails to connect with x509 errors and a crashing agent.
 
**To Reproduce**
1. Start rancher with a command like the following: 
```bash
docker run -d --restart=unless-stopped -p 8080:80 -p 8081:443 -p 8082:6060 --name rancher --env CATTLE_PROMETHEUS_METRICS=true --privileged rancher/rancher:v2.8-head
```
2. Using nginx, proxy the docker install of Rancher.
```bash
ngrok http --inspect=false https://localhost:8081/
```
3. Deploy a k3s cluster using the UI on digital ocean.

**Result**

The cluster agent crashes and fails to connect. The logs are as follows:
```
time="2024-07-19T17:27:39Z" level=error msg="Issuer of last certificate found in chain (CN=ISRG Root X1,O=Internet Security Research Group,C=US) does not match with CA certificate Issuer (CN=dynamiclistener-ca@1721409360,O=dynamiclistener-org). Please check if the configured server certificate contains all needed intermediate certificates and make sure they are in the correct order (server certificate first, intermediates after)"
time="2024-07-19T17:27:39Z" level=fatal msg="Certificate chain is not complete, please check if all needed intermediate certificates are included in the server certificate (in the correct order) and if the cacerts setting in Rancher either contains the correct CA certificate (in the case of using self signed certificates) or is empty (in the case of using a certificate signed by a recognized CA). Certificate information is displayed above. error: Get \"https://2dee-75-10-9-42.ngrok-free.app\": tls: failed to verify certificate: x509: certificate signed by unknown authority"
```

**Expected Result**
The cluster successfully connects, since `agent-tls-mode` is set to `system-store` and the proxy is using a cert signed by a CA in the operating system's trust store.

**Screenshots**
N/A

**Additional context**
This also affects 2.9-head (when `agent-tls-mode` is set to `system`).

**Comment by Sahota1225** [comment]
Backport https://github.com/rancher/rancher/issues/46263

**Comment by markusewalker** [comment]
**QA TEST PLAN**

|#|Scenario|
|---|---|
|1|Provision downstream RKE2 cluster in a proxied Rancher environment|
|2|Provision downstream K3s cluster in a proxied Rancher environment with --no-cacerts|
|3|Provision downstream RKE2 cluster in a non-proxied Rancher environment|
|4|Provision downstream K3s cluster in a non-proxied Rancher environment with --no-cacerts|

**Comment by markusewalker** [comment]
Tested on `v2.9.0-alpha8` and am seeing complications. See below:

**ENVIRONMENT DETAILS**
- Rancher install: Docker/Helm
- Rancher version: `v2.9.0-alpha8`

**TEST RESULT**
|#|Scenario|Result|
|---|---|---|
|3|Provision downstream clusters in a non-proxied Rancher environment|:x:|
|4|Provision downstream clusters in a non-proxied Rancher environment with --no-cacerts|:x:|

**TEST STEPS**

**Scenario 3**
1. Setup Rancher `v2.9.0-alpha8`, ensured `agentTLSMode=system-store`.
2. Provisioned downstream RKE1/RKE2/K3S node driver clusters (v1.30, 1 etcd+1 cp+1 worker).
     - RKE2/K3S provision successfully, RKE1 fails with to come up:
```
[INFO ] Initiating Kubernetes cluster
--
10:43:30 am | [INFO ] Successfully Deployed state file at [management-state/rke/rke-2022895401/cluster.rkestate]
10:43:30 am | [INFO ] Building Kubernetes cluster
10:43:30 am | [INFO ] [dialer] Setup tunnel for host [...]
10:43:30 am | [INFO ] [dialer] Setup tunnel for host [...]
10:43:30 am | [ERROR] Failed to set up SSH tunneling for host [...]: Can't retrieve Docker Info: error during connect: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/info": can not build dialer to [c-stwts:m-42xmr]
10:43:30 am | [ERROR] Failed to set up SSH tunneling for host [...]: Can't retrieve Docker Info: error during connect: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/info": can not build dialer to [c-stwts:m-xkj99]
10:43:30 am | [ERROR] Removing host [...] from node lists
10:43:30 am | [ERROR] Removing host [...] from node lists
10:43:30 am | [ERROR] Cluster must have at least one etcd plane host: failed to connect to the following etcd host(s) []
10:47:35 am | [INFO ] Initiating Kubernetes cluster
10:47:35 am | [INFO ] Successfully Deployed state file at [management-state/rke/rke-2666069753/cluster.rkestate]
10:47:35 am | [INFO ] Building Kubernetes cluster
10:47:35 am | [INFO ] [dialer] Setup tunnel for host [...]
10:47:35 am | [INFO ] [dialer] Setup tunnel for host [...]
10:47:35 am | [ERROR] Failed to set up SSH tunneling for host [...]: Can't retrieve Docker Info: error during connect: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/info": can not build dialer to [c-stwts:m-42xmr]
10:47:35 am | [ERROR] Failed to set up SSH tunneling for host [...]: Can't retrieve Docker Info: error during connect: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/info": can not build dialer to [c-stwts:m-xkj99]
10:47:35 am | [ERROR] Removing host [... from node lists
10:47:35 am | [ERROR] Removing host [...] from node lists
10:47:35 am | [ERROR] Cluster must have at least one etcd plane host: failed to connect to the following etcd host(s) []
```

______

**Scenario 4**
1. Repeated scenario 3, but utilized the `--no-cacerts` in my Docker command.
     - Additionally, needed to run `kubectl edit settings agent-tls-mode` and change from `strict` to `system-store`.
2. Noted the same error with RKE1 only.

**Comment by markusewalker** [comment]
Appears that the earlier complications seen during testing was environment-specific. Re-tested and am not seeing issues. See details below:

Tested on `v2.9.0-alpha8` and am seeing complications. See below:

**ENVIRONMENT DETAILS**
- Rancher install: Docker
- Rancher version: `v2.9.0-alpha8`

**TEST RESULT**
|#|Scenario|Result|
|---|---|---|
|1|Provision downstream clusters in a proxied Rancher environment|:white_check_mark:|
|2|Provision downstream clusters in a non-proxied Rancher environment|:white_check_mark:||

**TEST STEPS**

**Scenario 1**
1. Setup Rancher utilizing `ngrok` to serve behind a proxy.
2. Provisioned downstream RKE1/RKE2/K3S downstream clusters (v1.30 for K8s version, 1 etcd/1 cp/1 worker)
3. Validated that the cluster and nodes came up `Active`.
4. Repeated this, but updated `agent-tls-mode` to use `system-store` instead of `strict`.

______

**Scenario 2**
1. Repeated scenario 1, but did not utilize `ngrok` as this is not a proxied environment.
2. All results were successful.
