### ISSUE TITLE
[BUG] LDAP users cannot access project metrics and links of grafana, prometheus,etc are grayed out in project monitoring.

### ISSUE THREAD

**Issue by alegrey91** [rancher/rancher#46268]
## Issue description:
Customer is using project monitoring. Local users are added as project owner to desired project where project monitoring is enabled. With this user they are able to see project metrics and links to Grafana, prometheus are accessible when they select the project monitor. But, the issue with LDAP user is:

* They created project monitor for project 'A'
* Added ldap user 'user1' as project owner to project 'A'.
* Logged out and logged in with 'user1'.
* Clicked on "project monitor". the user can see the project monitor, it does not show project metrics and links to Grafana, prometheus,etc are grayed out.

### Business impact:
Users in their different teams are unable to access the project monitoring stats. 

### Troubleshooting steps:

* Created a test local user. Added the user to the desired project. Created project monitoring for this project and local user can see the project metrics. 
* But, this fails for LDAP user. Confirmed that this LDAP user is also added as project owner/member to the project where project monitoring is enabled.
* Tested with new LDAP user, but issue is persistent. 

### Repro steps:

* Create project monitor for project 'A'
* Add ldap user 'user1' as project owner to project 'A'.
* Log out and logged in with 'user1'.
* Click on "project monitor". the user can see the project monitor, it does not show project metrics and links to Grafana, prometheus,etc are grayed out.

### Workaround:

Is a workaround available and implemented? yes
What is the workaround:  As a workaround they add the LDAP user to rolebinding "cattle-project-p-xxxxx-mon-admin"  and then the user can see the project metrics, links to grafana,prometheus,etc.

### Actual behavior:

LDAP users cannot access the project monitoring metrics and links to Grafana,prometheus,etc are not accessible. 

### Expected behavior:

Like local users, LDAP users should also be able to access project monitoring metrics.

### Additional notes:

The screenshot shows Rancher version as `v2.7.9`, but customer also upgraded it to `v2.7.12` under assumption that it may solve the issue.

**Comment by samjustus** [comment]
https://jira.suse.com/browse/SURE-8665

**Comment by alegrey91** [comment]
The issue was closed since support together with development team was not able to reproduce the bug, so the customer asked to close it.
