### ISSUE TITLE
[BUG] ExternalRules feature flag is not removed upon upgrading

### ISSUE THREAD

**Issue by joesims22** [rancher/rancher#46272]
**Rancher Server Setup**
- Rancher version: v2.9-head

**Describe the bug**
While testing the upgrade scenario for [#45863 ](https://github.com/rancher/rancher/issues/45863) I observed that the external rules feature flag is not removed upon upgrading to v2.9.

**To Reproduce**

1. Deploy Rancher v2.8.5
2. Go to Settings and observe the external rules feature flag is present and enabled
3. Upgrade Rancher to v2.9-head
4. Go to Settings and observe the external rules flag is still present.

**Expected Result**

Upon upgrading Rancher to v2.9 the external rules feature flag should be removed.

**Comment by raulcabello** [comment]
# QA Testing

## Root cause
ExternalRules feature flag is not removed upon upgrading

## What was fixed, or what changes have occurred
Feature flag is remove if present

## Areas or cases that should be tested
ExternalRules feature flag should not be present when upgrading

**Comment by joesims22** [comment]
Verified on upgrade from `v2.8.5` to `v2.9-head 8bd2e56` that ExternalRules feature flag is not present.
