### ISSUE TITLE
[cli] 404 Not found - /v1 url 

### ISSUE THREAD

**Issue by the-greenman** [rancher/rancher#46288]
I have been scripting with the Rancher  CLI for some time now, but have, today found a new issue. I appreciate any assistance, and hope I'm not wasting anyone's time. 

I am able to switch to a rancher server. (we run multiple), I can switch contexts, but attempting to run "rancher project ls" now results in a 404 error. The same applies to any other command. 

The error includes the url that is not being found ... and it ends in /v1.   
I can see in cliclient.go, the url is forced to /v1. 

All /v3 urls are working, but any /v1 url will result in a 404. 
https://github.com/rancher/cli/blob/fbbf20571a909e9fe3c6ced17b39fbbc5dce2ee0/cliclient/cliclient.go#L151

Am I misreading this? 
Is there any way to force /v3 urls? 

Thanks

**Comment by shivakumar5** [comment]
Hi @the-greenman ,

Have you created a rancher cluster using rancher cli?

I'm trying to create a cluster using rancher cli like below:
```rancher cluster create --rke-config cluster.yml```

it is just creating an empty cluster not considering the nodes. I need to register the nodes again.
If you have already created cluster using rancher-cli, please let me know how did you do that?

**Comment by the-greenman** [comment]
> Hi @the-greenman ,
> 
> Have you created a rancher cluster using rancher cli?
> 
> I'm trying to create a cluster using rancher cli like below:
> ```rancher cluster create --rke-config cluster.yml```
> 
> it is just creating an empty cluster not considering the nodes. I need to register the nodes again.
> If you have already created cluster using rancher-cli, please let me know how did you do that?

Hi. I don't actually create the cluster via the cli. I just import the cluster once created. We've got additional terraform for cluster building.
