### ISSUE TITLE
Webapp accessing to other environment's Elasticearch stack once deleted in the current

### ISSUE THREAD

**Issue by ddmng** [rancher/rancher#4628]
Hi.
In my stage environment I have a webapp accessing an elasticsearch instance via an external-link. Once I deleted the elastic stack from my stage environment, the webapp was still showing data like if elastic was still there. Looking at the data I understood that it was accessing the development environment's elasticsearch which wasn't supposed to be accessible from stage.
I could not reproduce again the issue but I will do it in the next days. Both elastic instances were registered with the same names in the respective environments.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.0.0` Cattle: `v0.159.2` UI: `v0.100.3` |
|Access|`localauth` `admin`|
|Route|`environments.index`|

**Comment by deniseschannon** [comment]
Please let me know if you can reproduce. What is your external link set up as? 

Can you share your docker-compose.yml for the webapp stack?

**Comment by ddmng** [comment]
Still can't, sorry. Maybe you could close the issue and I'll come back with more details in case I will reproduce.
