### ISSUE TITLE
[rancher-compose] [proposal] option to download stack(s) configuration

### ISSUE THREAD

**Issue by dariko** [rancher/rancher#4629]
Would it be possible to add a command for downloading a stack configuration to `rancher-compose`?

example:
the command 
`user@hostname:/[...]/stack-name$ rancher-compose download`
should download the `{docker,rancher}-compose.yml` files for the `stack-name` stack in `/[...]/service-name/`

Right now I have a local configuration(versioned on git) which is thus organized:
  ```
environment/
    stack1/
      docker-compose.yml
      rancher-compose.yml
    stack2/
      docker-compose.yml
      rancher-compose.yml
    stackn/
      docker-compose.yml
      rancher-compose.yml
```
but after every service upgrade done on the web interface I need to manually download(export) the stack compose.zip and extract it, which is kinda cumbersome and prone to errors.

Maybe this could also be extended with an option `--all` with creates in the current path a directory `stack-name` for every stack in the environment containing the corresponding `{docker,rancher}-compose.yml` files?

This could simplify a mixed (rancher-compose/UI) workflow and also maybe enable a more consistent versioning via VCS.

**Comment by deniseschannon** [comment]
Instead of adding this into Rancher Compose, we recommend using the new [Rancher CLI](http://docs.rancher.com/rancher/cli/) which supports `rancher export`.
