### ISSUE TITLE
[BUG] provisioning v2 prov clusters `rancher/machine` image in `backOff` state when using private registry

### ISSUE THREAD

**Issue by Josh-Diamond** [rancher/rancher#46316]
**Rancher Server Setup**
- Rancher version: `v2.9.0-rc3`
- Installation option (Docker install/Helm Chart):
HA Helm

**Information about the Cluster**
- Kubernetes version: any supported v2 prov cluster (1.29.6/1.30.2)
- Cluster Type (Local/Downstream):
downstream

**User Information**
- What is the role of the user logged in? Admin

**Describe the bug**
When provisioning a downstream v2 prov cluster using a private registry, `rancher/machine` image is in a `backOff` state when trying to pull `rancher/machine:v0.15.0-rancher114`, which causes provisioning to fail

**To Reproduce**
1. Fresh install of Rancher `v2.9.0-rc3`
2. Provision a downstream rke2/k3s cluster using a private registry
3. Reproduced

**Result**
`rancher/machine` image in `backOff` state

**Expected Result**
Cluster comes up `active`

**Additional context**
When reviewing rancher-images.txt for `v2.9.0-rc3`, `rancher/machine` image points to `rancher/machine:v0.15.0-rancher109` and there is no `rancher/machine:v0.15.0-rancher114` image packaged

**Comment by snasovich** [comment]
This should now be fixed, moving to "Ready for QA" however realistically retest is blocked until new tagged version is available as the repro scenario includes setting up private registry.

**Comment by Josh-Diamond** [comment]
Ticket #46316 - Test Results - ✅ 
---

Verified on Rancher `v2.9.0-rc4`:

| Scenario | Test Result | Status |
|---|---|---|
| 1. | Verify `rancher/machine` image in `rancher-images.txt` | ✅ |
| 2. | Provision a downstream v2 prov cluster using a private registry | ✅ |

---

Scenario 1 - ✅ 
1. Visit pre-release for [v2.9.0-rc4](https://github.com/rancher/rancher/releases/tag/v2.9.0-rc4)
2. Download `rancher-images.txt`
3. Verify `rancher/machine` image
4. Verified - `rancher/machine` image in `v2.9.0-rc4` points to `rancher/machine:v0.15.0-rancher114`; as expected

---

Scenario 2 - ✅ 
1.  Fresh install of Rancher `v2.9.0-rc4`
2. Provision a downstream v2 prov cluster using a private registry
3. Verified - cluster comes up `active`, all pods `active` and stable; as expected

*Scenario 2 was tested against 4 downstream node driver clusters covering the following k8s versions: 
- `v1.29.6+rke2r1`
- `v1.30.2+rke2r1`
- `v1.29.6+k3s2`
- `v1.30.2+k3s2`
