### ISSUE TITLE
Is api response for service links cached?

### ISSUE THREAD

**Issue by clicman** [rancher/rancher#4631]
I`m creating custom command line api client for rancher and faced problem with "/v1/serviceconsumemaps?limit=-1" api request:
**If I remove service link it keeps returning during this request about 1 minute after removing.**
I see what in racnher ui it removes immedeatly.
Why it happens?

P.S. If I add service links - state updates immideatly.
I am add service links via "/v1/loadbalancerservices/1s4/?action=setservicelinks"

You can reproduce it via https://github.com/clicman/rancher-cli-addons

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.0.1` Cattle: `v0.159.7` UI: `v1.0.5` |
|Access|`github` `admin`|
|Route|`environments.index`|

**Comment by vincent99** [comment]
There is no caching; you probably want to filter out ones in `state`=`removed' or `purging`.

**Comment by clicman** [comment]
Hmm. I confirm, if I remove last port from service it not removed immideatly and removes with whole service reference. 
What will be if I creare new one reference when removed current reference will in "removed" state? 
Should I wait until it comletly removed to add it again?

**Comment by clicman** [comment]
Additionally I can create service with duplicate ports. Is this legal?
[{"state": "active", "serviceId": "1s16", "ports": ["site-03.mydomain.com:80=3000"]}, 
{"state": "active", "serviceId": "1s14", "ports": ["mongo.csm-staging-03.mydomain.ru:25=25", "mongo.csm-staging-03.mydomain.ru:25=25"]}]

**Comment by vincent99** [comment]
Multiple routing rules involving the same ports are allowed, but the hostname part is for http listeners  and has no meaning for TCP listeners like SMTP, so your example isn't doing anything beyond just saying 25

**Comment by clicman** [comment]
Got it. Thank you.
