### ISSUE TITLE
[Backport v2.8] Cattle-cleanup job for imported clusters not pulling from configured private registry

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#46336]
Backport of https://github.com/rancher/rancher/issues/40068 to v2.8 line of releases

**Comment by Josh-Diamond** [comment]
awaiting requested alpha to resume testing

**Comment by Josh-Diamond** [comment]
Ticket #46336 - Test Results - ✅ 
---

Verified on Rancher `v2.8.7-rc2`:

| Scenario | Test Case | Result |
|---|---|---|
| 1. | Import downstream RKE1 cluster => delete imported cluster via Rancher => verify `cattle-cleanup` job | ✅ |
| 2. | Import downstream RKE2 cluster => delete imported cluster via Rancher => verify `cattle-cleanup` job | ✅ |

---

Scenario 1 - ✅ 
1. Fresh install of Rancher `v2.8.7-rc2`
2. Provision a standalone cluster - ( I used RKE `v1.5.12` w/ k8s `v1.28.12-rancher1-1` )
3. Once `active`, import the cluster into Rancher
4. Wait for cluster to come up `active` in Rancher UI, then delete the imported cluster
5. Verified - cluster successfully deletes from Rancher UI
6. Using `kubectl`, describe the `cattle-cleanup` job and verify where `cleanup-agent` is pulled, using the following command:
```log
kubectl describe job <job_name_here> -n default
```
7. Verified - `cleanup-agent` image points to globally configured private registry; as expected

---

Scenario 2 - ✅ 
1. Fresh install of Rancher `v2.8.7-rc2`
2. Provision a standalone cluster - ( I used RKE2 w/ k8s `v1.28.11+rke2r1` )
3. Once `active`, import the cluster into Rancher
4. Wait for cluster to come up `active` in Rancher UI, then delete the imported cluster
5. Verified - cluster successfully deletes from Rancher UI
6. Using `kubectl`, describe the `cattle-cleanup` job and verify where `cleanup-agent` is pulled, using the following command:
```log
kubectl describe job <job_name_here> -n default
```
7. Verified - `cleanup-agent` image points to globally configured private registry; as expected
