### ISSUE TITLE
SQLite backed cache: support autorefresh

### ISSUE THREAD

**Issue by moio** [rancher/rancher#46332]
Parent epic: https://github.com/rancher/rancher/issues/46348

**IMPORTANT: this issue is being reconsidered in favor of https://github.com/rancher/rancher/issues/40773 potentially**.

**Problem**: when the SQLite backed cache is enabled, `watch` functionality through Steve is broken in that the returned `resourceVersion` number from `list` calls cannot be used in subsequent `watch` calls to obtain all events since the `resourceVersion` point in time, which is the expected behavior ([Kubernetes equivalent](https://kubernetes.io/docs/reference/using-api/api-concepts/)).

**Proposed solution**: 
- remove current code that implements `watch` in Steve (with the SQLite backed cache turned on). At the moment that results in opening a new Kubernetes `watch` call and forwarding events from Kubernetes to the Steve API consumer. That is not the desired behavior any longer, as Steve has already `watch`es open to keep the SQLite store up-to-date
- instead, reimplement Steve's `watch` by:
  - storing incoming events temporarily from the Kubernetes `watch` in a circular buffer or similar data structure in RAM (in addition to propagating their content to the SQLite store). The buffer is to be limited to a small number of events (eg. 100)
  - forwarding events from the circular buffer to Steve's `watch` API clients
  - keeping a counter of received Kubernetes `watch` events. This counter will be returned as `resourceVersion` in `list` calls so that it can subsequently be used by `watch` clients to request events from a certain point in time on
  - if a client makes a Steve `watch` API call with a `resourceVersion` which is too old (=the circular buffer does not have it any more) return `410 Gone`. UI will fetch a new `list` and open a new `watch` as it does today

**Expected outcome (UI perspective)**:
- the `resourceVersion` `list`+`watch` mechanism works identically to the non-SQLite backed Steve

**Comment by moio** [comment]
@richard-cox please comment if anything sounds incorrect or needs clarification from your perspective

**Comment by richard-cox** [comment]
- To confirm, with vai off the old watch mechanism will remain unchanged?
- When this vai feature comes in we would need to ensure the UI halts the fetch of all requests for resources with high counts. If we get everything in for 2.10.0 this isn't an issue
  - The short lifespan of changes in the circular buffer means the `too old` revision scenario is much more likely (for example when the sockets naturally die / closed by rancher by force and the UI tries to re-watch resources with a stale revision)
  - in the result of `too old` the UI will refresh all resources of that type (ensuring local cache is up to date and valid revision is used)
  - some of the cases for edge computing could cause frequent requests to cluster management based resources with high counts

Note - Keeping the watch message interface the same is greatly appreciated

**Comment by moio** [comment]
> To confirm, with vai off the old watch mechanism will remain unchanged?

Yes.

> The short lifespan of changes in the circular buffer means the too old revision scenario is much more likely (for example when the sockets naturally die / closed by rancher by force and the UI tries to re-watch resources with a stale revision)

Correct. That should be compensated by the fact full `list`ing is now much cheaper, because you only get the needed page. Also, I do not know how short will short actually be - for seldom-changing resources that could still be minutes or hours (I guess we will cap by change count).

> in the result of too old the UI will refresh all resources of that type (ensuring local cache is up to date and valid revision is used)

Yes where "all" means "one page", so relatively cheap.

> some of the cases for edge computing could cause frequent requests to cluster management based resources with high counts

Yes, I still think a debouncing mechanism will be required regardless.

Does that make sense?

**Comment by richard-cox** [comment]
Makes sense! There's still a fair amount of work to remove requests for high resource counts, but it's all scheduled and achievable for the target release.

**Comment by moio** [comment]
@tomleb please take a thorough look at https://github.com/rancher/rancher/issues/40773 and let's discuss the idea there. If confirmed, this issue can potentially be closed right away (and we can split work in some other way).

**Comment by MKlimuszka** [comment]
Might be superseded by https://github.com/rancher/rancher/issues/40773

**Comment by moio** [comment]
Closing in favor of https://github.com/rancher/rancher/issues/40773
