### ISSUE TITLE
SQLite backed cache: investigate writes blocking reads

### ISSUE THREAD

**Issue by moio** [rancher/rancher#46331]
Parent epic: https://github.com/rancher/rancher/issues/46348

**Problem**: when the SQLite backed cache is enabled, after starting Rancher and observing a type with many resources (eg. 10k ConfigMaps), the following log line is produced:

`"DeltaFIFO Pop Process"  ... Reason:slow event handlers blocking the queue`

Moreover the UI will not load as list queries are blocked until the SQLite cache is fully warmed up.

This should not happen, reads should not be blocked by writes.

**Proposed solution**: none known. The root cause is to be identified.

**Expected outcome (UI perspective)**:
- list requests return while writes are in progress

**Comment by moio** [comment]
@richard-cox please comment if anything sounds incorrect or needs clarification from your perspective

**Comment by richard-cox** [comment]
Out of interest, with the issue does the UI show a suitable loading / in progress indicator?

**Comment by moio** [comment]
Not that I have observed so far - will be back to you on that.

**Comment by moio** [comment]
@richard-cox tests done.

AFAICS the load indicator does not appear.

- In normal cases request comes back very quickly (~60 ms for the first page of 10K configmaps in my local setup), so it's correct it should not appear
- In very bad cases (when the Informer cache was not yet warmed up, so it's the very first time any user accesses a resource kind) I also do not see it appearing (~3.5s in the same conditions)

Feel free to open an issue if you want to track that.

**Comment by moio** [comment]
This issue is now fixed, presumably via https://github.com/rancher/lasso/pull/98

# Reproduction instructions
- create 10k ConfigMaps, eg. via 

```
k6 run -e KUBECONFIG=$PATH_TO_KUBECONFIG -e CONTEXT=$CONTEXT -e BASE_URL=$K8S_API_URL -e CONFIG_MAP_COUNT=10000 -e SECRET_COUNT=1 create_k8s_resources.js
```

with create_k8s_resources.js taken from https://github.com/rancher/dartboard/blob/main/k6/create_k8s_resources.js

-  navigate to `https://$RANCHER_ADDRESS/dashboard/c/local/explorer/configmap` or reload that page

*Expected behavior*: log line does not appear in rancher pod logs, page loads in few seconds. Reproduced on current main with main lasso

*Actual behavior as of 2.9.1*: log line appears and page takes minutes to load

cc @tomleb

**Comment by moio** [comment]
cc @brudnak

**Comment by richard-cox** [comment]
Thanks @moio , tracked the ui bug in https://github.com/rancher/dashboard/issues/11979

**Comment by rancher-max** [comment]
It appears the relevant code is not yet in rancher in the required release lines. We need a lasso bump in `main` and `release/v2.9` in order to see and validate this. Ref: https://github.com/rancher/rancher/blob/main/go.mod#L135 and https://github.com/rancher/rancher/blob/release/v2.9/go.mod#L136

**Comment by moio** [comment]
@rancher-max you're right, #47329 should address that
