### ISSUE TITLE
Update kube-api-auth dependencies

### ISSUE THREAD

**Issue by pmatseykanets** [rancher/rancher#46334]
- Bump Rancher to v2.9.0
- Bump bci image to 15.6

**Comment by samjustus** [comment]
@pmatseykanets anything specific that QA should test?

**Comment by pmatseykanets** [comment]
@samjustus We should probably check that there are no issues with authenticating with ACE.

**Comment by joesims22** [comment]
Verified ACE authentication and functionality on v2.9-head `416e5c40`
