### ISSUE TITLE
Convoy-nfs causes Docker to hang

### ISSUE THREAD

**Issue by willseward** [rancher/rancher#4633]
Rancher Version: v1.0.1

Docker Version: 1.10.3

OS: Ubuntu 14.04

Steps to Reproduce: Create a convoy service backed by NFS. Create a stack in which a service uses a volume in convoy. Upgrade the service, so that Rancher attempts to stop the container.

Results: The Docker engine on the host become unresponsive. A manual restart of the Docker service is required, leaving the volume lock files out of sync.

Expected: The service will stop and be recreated on another host.

![screen shot 2016-04-30 at 11 08 49 am](https://cloud.githubusercontent.com/assets/5386568/14937150/f22da79c-0ec3-11e6-8c4f-4211b3fca2cb.png)

**Comment by deniseschannon** [comment]
We are unable to reproduce. There are similar issues around volumes and docker no longer responding. 

https://github.com/rancher/rancher/issues/4463

**Comment by machi1990** [comment]
@willseward  @deniseschannon  Experience the same issue with Convoy-nfs. Docker ps hangs, and I have to either restart the docker service or reboot the HOST several times. Do we have any update regarding this?

**Comment by willseward** [comment]
I was able to fix the problem by creating an entirely new Rancher installation with a new database. Did you ever have another storage pool setup on a <1.2.0 rancher install?

**Comment by machi1990** [comment]
Yes, I was using conyoy-nfs. I have deleted it but I have a problem with rancher-nfs 
_"Failed mount -o proto=tcp,port=2049,nfs vers=4 failed to find protocol tcp"_  I have removed some specifics like IP and mount point.

**Comment by willseward** [comment]
I'm not sure about that specific issue with rancher-nfs. You may try creating another issue because I believe it is unreleated to this one.

**Comment by willseward** [comment]
Closing because convoy is deprecated in 1.2.0
