### ISSUE TITLE
[Windows] System Agent and rke2 startup may conflict with one another

### ISSUE THREAD

**Issue by HarrisonWAffel** [rancher/rancher#46344]
**Rancher Server Setup**
- Rancher version: Any
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: Any
- Cluster Type (Local/Downstream): Downstream, Windows
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: not relevant

**Describe the bug**

Relates to: https://github.com/rancher/rancher/issues/42458

Occasionally, when restarting a windows node, the `system-agent` may fail to apply the one time instruction for executing the `run.ps1` script contained in the `system-agent-installer-rke2` image. This results in the following lines in the `rancher-wins` logs on the node, and an error in the UI.

```
7/25/2024 6:59:37 PM error executing instruction 0: read tcp 10.1.0.4:49830->104.16.101.215:443: wsarecv: An established connection was aborted by the software in your host machine.
7/25/2024 6:59:37 PM error while staging: read tcp 10.1.0.4:49830->104.16.101.215:443: wsarecv: An established connection was aborted by the software in your host machine.
7/25/2024 6:59:34 PM Extracting file Files/bin/run.ps1 to C:\var\lib\rancher\agent\work\20240725-185932\28b22c3d528b8430eee9c628a49336486889c0ee60ca289e902de1cf914280af_0\run.ps1
7/25/2024 6:59:34 PM Extracting file Files/bin/sha256sum-amd64.txt to C:\var\lib\rancher\agent\work\20240725-185932\28b22c3d528b8430eee9c628a49336486889c0ee60ca289e902de1cf914280af_0\sha256sum-amd64.txt
7/25/2024 6:59:33 PM Extracting file Files/bin/rke2.windows-amd64.tar.gz to C:\var\lib\rancher\agent\work\20240725-185932\28b22c3d528b8430eee9c628a49336486889c0ee60ca289e902de1cf914280af_0\rke2.windows-amd64.tar.gz
7/25/2024 6:59:33 PM Extracting file Files/bin/installer.ps1 to C:\var\lib\rancher\agent\work\20240725-185932\28b22c3d528b8430eee9c628a49336486889c0ee60ca289e902de1cf914280af_0\installer.ps1
7/25/2024 6:59:32 PM Pulling image index.docker.io/harrisonwaffel/system-agent-installer-rke2:v1.29.6-rke2r1
7/25/2024 6:59:32 PM Using private registry config file at /etc/rancher/agent/registries.yaml
```

This occurs due to a race condition between the `system-agent`, embedded within `rancher-wins`, and `rke2` when using the Calico CNI. When `rke2` starts and is configured to use Calico, it deletes and recreates HNS networks. This causes a temporary network disruption and blocks / disconnects certain connections. If this occurs at the same time as the `system-agent` is executing its one time instruction of the `run.ps1` script inside of the `system-agent-installer-rke2` image, the plan will be marked as failed. This race condition can be confirmed by cross referencing the timestamps of `rke2` and `rancher-wins` logs. 

`rancher-wins`
```
7/25/2024 6:59:37 PM error executing instruction 0: read tcp 10.1.0.4:49830->104.16.101.215:443: wsarecv: An established connection was aborted by the software in your host machine.
```

`rke2`
```
7/25/2024 6:59:36 PM {Generating HNS networks, please wait}
7/25/2024 6:59:36 PM {Setting up Calico CNI}
```

Because both `rancher-wins` and `rke2` are configured with an automatic start type they both start at the same time post reboot, with no guarantee on which starts first. This can result in `rke2` causing a network disruption at the same as the system agent is pulling the `system-agent-installer-rke2` image. This causes a plan failure and an error message is shown in the Rancher UI. This same error will be observed whenever a service which introduces a temporary network interruption is started at the same time as `rancher-wins` (Such as in vSphere, where the `vmtools` service causes a similar network disruption).

This only happens occasionally. 

**To Reproduce**
Provision a windows node on any provider. After the cluster has become active, RDP onto the windows node and run `restart-computer`. Continue to restart the node until a plan error is observed. Confirm that the given plan error matches the above described error logs. 

**Result**
The plan is marked as failed, and the worker is marked as failed in the Rancher UI. However, the worker continues to function as desired (cluster explorer will work, windows workloads will be rolled out, `kubectl get nodes` will show the worker in a `Ready` state).

**Work Arounds**

The planner / UI error can be resolved by restarting the rancher-wins service. However, this will also restart `rke2`, and you will encounter https://github.com/rancher/rke2/issues/5551. Due to https://github.com/rancher/rke2/issues/5551, the ultimate workaround is setting the start type of the `rke2` service to `AUTOMATIC (DELAYED)`, ensuring that the `rancher-wins` service starts before `rke2`, and then restarting the node. 

**Expected Result**
The `system-agent` does not fail to execute the `system-agent-installer-rke2` plan due to `rke2` starting up at the same time.

**Screenshots**

**Additional context**

**Comment by HarrisonWAffel** [comment]
This issue can be tested alongside the October RKE2 patches, as part of this solution relies on changes in the system-agent-installer-rke2

**Comment by HarrisonWAffel** [comment]
Can be tested using the data.json from this KDM PR https://github.com/rancher/kontainer-driver-metadata/pull/1544

URL: https://raw.githubusercontent.com/rafaelbreno/kontainer-driver-metadata/refs/heads/october_rke2_10_patch/data/data.json

**Comment by markusewalker** [comment]
Validated this against `head` https://github.com/rancher/rancher/commit/fe49760f4e50d0b78ca0102c8475bc93361336b0. Details have been recorded in Qase test run /RM 2661.

**ENVIRONMENT DETAILS**
- Rancher install: Helm
- Rancher version: `head` https://github.com/rancher/rancher/commit/fe49760f4e50d0b78ca0102c8475bc93361336b0

**TEST RESULTS**
|#|Scenario|Result|
|---|---|---|
|1|Validate rancher-wins and sc.exe output shows no errors on highest K8s version|:white_check_mark:|
|2|Validate rancher-wins and sc.exe output shows no errors on upgraded K8s version|:white_check_mark:|
|3|Validate rancher-wins and sc.exe output shows no errors on upgraded Rancher|:white_check_mark:|
