### ISSUE TITLE
[Question] What would happen if we could use Rancher’s 2.9 dependencies in its Dockerfile for Rancher’s 2.8 version or so? 

### ISSUE THREAD

**Issue by developer-guy** [rancher/rancher#46358]
In Rancher’s Dockerfile, there are various dependencies such as partner-agent charts, rancher charts, etc. I am curious about what would happen if we use the versions defined in the Dockerfile for Rancher 2.9 in Rancher 2.8. Would this affect the application’s functionality? 

Because I saw Rancher is on the way to release 2.9 which uses the latest version of these dependencies but according to EOL the latest version for Rancher is 2.8.5 which uses the older versions of these dependencies so I just wanted to ask that what if I could use latest versions of these dependencies in 2.8.5, does that affect Rancher's functionality.

Thanks!

**Comment by Oats87** [comment]
Unexpected things can/(and probably will) occur.

The various Rancher components are internally versioned and are not necessarily backwards compatible with previous versions of Rancher. A great example of this would be around `rancher-machine`, which can have flags added/removed from it. While the various teams do our best to keep backwards compatibility when maintaining the various components, there is no guarantee.

You could always put the leg work into `diff`ing the versions you want to bump from/to and determining if you would expect problems.

**Comment by developer-guy** [comment]
I mean by the dependencies which are downloaded into the /var/lib/rancher-data btw, https://github.com/rancher/rancher/blob/7af1354e9b8900cec6e5360787e291acd376e6d3/package/Dockerfile#L71-L86 I don't think that they matter, right?

**Comment by developer-guy** [comment]
the kontainer-driver-metadata is also one of them https://github.com/rancher/rancher/blob/v2.8.5/package/Dockerfile#L43 but the latest is now v2.9 that means that 2.8.5 version of rancher uses the older version of kontainer-driver-metadata as well

**Comment by bpedersen2** [comment]
Why don't you just run the 2.9-rc4 version if you really need bleeding edge versions?

**Comment by developer-guy** [comment]
according to the EOL https://endoflife.date/rancher the latest is 2.8.5 so as the v2.9 is not a released version (yet), I shouldn't be building it anything besides latest.

**Comment by bpedersen2** [comment]
Well 2.9-rc4 is available as release. And just picking some random never versions in a released and supported version is worse than using a rc version.

**Comment by developer-guy** [comment]
let me ask another question then, does Rancher Agent work without the `/var/lib/rancher-data` folder? 
https://github.com/rancher/rancher/blob/6e9cf233a87796ee9a96e73c096a82101fc9c2ff/package/Dockerfile.agent#L75

**Comment by bpedersen2** [comment]
Again, what you are trying is definitly not supported or recommend, so do it on your own risk.
And the rancher binary does make assumption about the versions the deps, so changing that is very likely to break.

You have 3  options:
 - stay with a stable version (currently 2.8.5)
 -  use a rc version (check https://github.com/rancher/rancher/releases) 
 - build your own from the source
