### ISSUE TITLE
Set minimum docker version in UI as a settings so it's easily changeable

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#4635]
In the UI, we reference the Docker version that is useable in a couple of places (welcome page, host page, etc), As we change minimum docker versions, we should be able to easily change it with 1 setting.

**Comment by vincent99** [comment]
https://github.com/rancher/cattle/pull/1650 `ui.min.docker.version`

**Comment by deniseschannon** [comment]
Can we also update so that it's 1.10.3 everywhere?

<img width="777" alt="screen shot 2016-05-15 at 3 35 17 pm" src="https://cloud.githubusercontent.com/assets/11410997/15277224/a905f5d8-1ab2-11e6-9c26-193573158aca.png">

**Comment by vincent99** [comment]
Yes, the one on the help page was updated but missed this one

**Comment by tfiduccia** [comment]
Version - master 5.19
Verified fixed
