### ISSUE TITLE
[CIS] Ensure that the --DenyServiceExternalIPs is set for RKE, K3s and RKE2

### ISSUE THREAD

**Issue by andypitcher** [rancher/rancher#46350]
Related issue: 
- https://github.com/aquasecurity/kube-bench/issues/1606

RKE, K3s and RKE2 do not enable the `DenyServiceExternalIPs` by default. 

Generally speaking, the use of DenyServiceExternalIPs is to prevent the use of [ExternalIP](https://kubernetes.io/docs/concepts/services-networking/service/#external-ips) parameter in a Kubernetes service, to prevent the exposition of a pod for example, either intentionally or by mistake.

This issue is created to assess the implementation of this parameter for each distribution through --enable-admission-plugins=DenyServiceExternalIPs.

@vardhaman22 could you confirm its applicability in RKE ?
@dereknola could you confirm its applicability in K3s and RKE2 ?

We can then decide if this should be added manually as part of the hardening-guide (with the 1.2.3 check to Manual) Or if this should be added in the bistro's code directly (with the 1.2.3 check to Automated).

**Comment by dereknola** [comment]
For K3S this will always be manual
For RKE2, using the --profile=cis, we would automate it.

This should not have any effect on the existing usage of either distro.

**Comment by andypitcher** [comment]
For RKE, we will mark this check as Manual.

**Comment by andypitcher** [comment]
Closing this issue since https://github.com/rancher/security-scan/pull/243 is now merged.
