### ISSUE TITLE
[FRE] Suggest adding commonly used protocols such as FTP to cluster backup

### ISSUE THREAD

**Issue by xzxiaoshan** [rancher/rancher#46356]
In Rancher's cluster configuration, cluster snapshot backup is currently supported for S3 backup. Because S3 is unreachable in many enterprise networks. Suggest adding support for FTP backup method. The backup function does not require very high protocol requirements. FTP is obviously a good choice, and it is easy to use in both internal and external network scenarios.

![image](https://github.com/user-attachments/assets/7e71cf4c-b190-4ffb-9942-20b11ff384ef)

**Comment by bpedersen2** [comment]
In an enterpise setting you would not want something "open" as ftp for etcdbackups ( that contain all the secrets in the cluster). Setting up an local s3-compatible storage is not that hard...
