### ISSUE TITLE
[BUG] System-agent-upgrader plan removes system-agent data directory

### ISSUE THREAD

**Issue by jakefhyde** [rancher/rancher#46361]
**Rancher Server Setup**
- Rancher version: `v2.9-dd23578d3e3499f54d80c4ed88cc52c44ee69539-head`

**Describe the bug**

The `system-agent-upgrader` SUC plan does not contain the environment variables for the `system-agent` data directory (`CATTLE_AGENT_VAR_DIR`), so when the system upgrade controller applies the plan, the previous configuration is lost and the default of `/var/lib/rancher/agent` is used.

**To Reproduce**

Provision a `v1.30.2+k3s2` cluster on rancher version above.

**Result**
Agent installs correctly, but after plan is run defaults to `/var/lib/rancher/agent`.

**Expected Result**

Specified system agent data directory is used.

**Screenshots**

**Additional context**

**Comment by susesgartner** [comment]
Ticket #46361 - Test Results - ✅ 
---
 
| Scenario | Test Case | Result |
|---|---|---|
| 1. | Validate that custom system-agent data dir is used | PASS |
| 2. | Validate that the default data dir works | PASS |
 
---
Verified with (HA Helm or Docker) on Rancher `v2.9-8bd2e564f63fe6ca23e9ead5499a43e314d1be74-head`:
---
Scenario 1: Validate that custom system-agent data dir is used
---
Note: Tested on node driver/custom and k3s/rke2 

1. Create a 3 node split roles cluster with the system-agent dir set 
2. Wait for the cluster to become active
3. SSH into each node and verify that the correct data dir is utilized
4. Validate that /var/lib/rancher/agent doesn't exist
 
Results: The data directory is correctly utilized and /var/lib/rancher/agent doesn't exist
 
---
 
Scenario 2: Validate that the default data dir works
---
1. Create a 3 node split roles rke2 cluster
2. Wait for the cluster to become active
3. Verify that the cluster is in a healthy state.
 
Results: The cluster is in a healthy state
