### ISSUE TITLE
[BUG] Custom cluster registration command not including system agent data directory

### ISSUE THREAD

**Issue by jakefhyde** [rancher/rancher#46362]
**Rancher Server Setup**
- Rancher version: `v2.9-dd23578d3e3499f54d80c4ed88cc52c44ee69539-head`

**Describe the bug**

When creating a custom cluster with a system agent data directory, the custom cluster registration command does not include the `CATTLE_AGENT_VAR_DIR` env var.

**To Reproduce**

Create a custom cluster with a system-agent data directory

**Result**

Registration command does not use specified directory, defaulting to `/var/lib/rancher/agent` instead.

**Expected Result**

User specified directory is used.

**Screenshots**

**Additional context**

**Comment by jakefhyde** [comment]
It is possible to workaround this limitation by manually specifying the `CATTLE_AGENT_VAR_DIR` in the registration command, like so:
```
curl -fL https://(url)/system-agent-install.sh | sudo CATTLE_AGENT_VAR_DIR="(path)" sh -s - --server https://(url) --label 'cattle.io/os=linux' --token (token) --etcd --controlplane --worker
```
where `(path)` is an absolute path on the node to the desired directory.

**Comment by jakefhyde** [comment]
@susesgartner moving to "Ready for QA", but no need to test until all data-dir PRs are merged. I will update once that is the case.

**Comment by jakefhyde** [comment]
Ready for QA now that all have been merged.

**Comment by Josh-Diamond** [comment]
Ticket #46362 - Test Results - ✅ 
---

Verified on Rancher `v2.9-63ca06b9fb165182ca1063868ef837dfaf84bb31-head`:

| Scenario | Test Case | Result |
|---|---|---|
| 1. | Provision a downstream RKE2 Custom cluster w/ a custom system-agent data directory specified | ✅ |
| 2. | Provision a downstream K3s Custom cluster w/ a custom system-agent data directory specified | ✅ |

---

Scenario 1 - ✅ 
1. Fresh install of Rancher `v2.9-head`
2. Create a downstream RKE2 Custom cluster set a custom system agent data directory by navigating to `Cluster Configuration > Advanced > Data directory configuration`
3. Verified - registration command includes user specified directory
4. Run registration command against linux nodes
5. Verified - Nodes successfully run command, cluster comes up active, and the custom directory is created and in use on all downstream nodes
6. Register a windows worker node
7. Verified - Node successfully runs command, cluster comes up active and custom directory is present and in use; as expected

---

Scenario 2 - ✅ 
1. Fresh install of Rancher `v2.9-head`
2. Create a downstream K3s Custom cluster set a custom system agent data directory by navigating to `Cluster Configuration > Advanced > Data directory configuration`
3. Verified - registration command includes user specified directory
4. Run registration command against linux nodes
5. Verified - Nodes successfully run command, cluster comes up active, and the custom directory is created and in use on all downstream nodes; as expected
