### ISSUE TITLE
2.9.0 Release Note Request

### ISSUE THREAD

**Issue by CamrynCarter** [rancher/rancher#46376]
Please add the following release note to Rancher 2.9.0 and RKE 1.6.0. Thank you! 

"With the release of Rancher Kubernetes Engine (RKE) v1.6.0, we are informing customers that RKE is now deprecated. RKE will be maintained for two more versions, following our [deprecation policy](https://www.suse.com/support/rancher-prime/#Rancher-Prime-Deprecation-Policy). 

Please note, End-of-Life (EOL) for RKE is July 31st, 2025. Prime customers must re-platform from RKE to RKE2 or k3s. 

RKE2 and k3s provide stronger security, and move away from upstream-deprecated Docker machine. Learn more about re-platforming [here](https://www.suse.com/c/rke-end-of-life-by-july-2025-replatform-to-rke2-or-k3s/)."

Note: second link will go live tomorrow.

**Comment by sunilarjun** [comment]
Hello @CamrynCarter! Added a release note to [v2.9.0]() addressing the RKE EOL here: https://github.com/rancherlabs/release-notes/pull/390/commits/26bd0577cbb21c7d8eeedaef405560c40ba67785. (Wanted to call out here as the main RN issue has quite a long thread.) Let me know if it needs any adjustment on placement, thank you!

**Comment by CamrynCarter** [comment]
That's perfect, @sunilarjun, thank you!
