### ISSUE TITLE
Hosts from other environment show up in Infrastructure/hosts view.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#4637]
Rancher Version:v1.1.0-dev1-rc2

Set up had 3 environments with few hosts in each of them.

Added another environment (In my case it was "Mesos" environment).

Added 2 digital Ocean hosts to the environment.

Infrastructure/hosts view shows host from another environment.
On refreshing the page , the host from another environment disappears.
<img width="1062" alt="screen shot 2016-04-30 at 7 16 45 pm" src="https://cloud.githubusercontent.com/assets/4266958/14939743/07a9ab80-0f09-11e6-99ac-c8174efa8b9a.png">

**Comment by ebr** [comment]
perhaps related to https://github.com/rancher/rancher/issues/3639? I also remember seeing (but can't find) an issue where this *may have* happened for admin users only.

**Comment by vincent99** [comment]
I haven't been able to reproduce this, but if you can there is additional logging in dev2:

![image](https://cloud.githubusercontent.com/assets/753917/15372016/3170118c-1cf3-11e6-91eb-fa5f14373a2d.png)

**Comment by tfiduccia** [comment]
Version - master 5-24
Verified fixed
