### ISSUE TITLE
[BUG] [Windows] `STRICT_VERIFY` environment variable is not passed to windows nodes

### ISSUE THREAD

**Issue by HarrisonWAffel** [rancher/rancher#46396]
**Rancher Server Setup**
- Rancher version: 2.9.0-rc7
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: n/a
- Cluster Type (Local/Downstream): downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Custom Windows

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: n/a

**Describe the bug**

Rancher has introduced the `agentTLSMode` setting, which determines if agent connections should perform strict validation of CA certificates before connecting to the local Rancher cluster. The system-agent and related scripts have been updated for Linux nodes to support this feature, however Windows nodes do not yet receive this setting or handle it properly. This is partly due to the environment variable not being provided in the `rancher-wins` install script, as well as the system agent upgrade plan not properly executing on windows nodes. 

**To Reproduce**

This issue cannot be easily reproduced, as the current behavior will ignore the requested `agentTLSMode` and continue without issue. The root issue is that the most recently released version of Wins does not use a version of the system-agent which supports the `agentTLSMode` feature, and that the `STRICT_VERIFY` environment variable is not set or utilized at the time of initial installation and is not properly delivered to downstream nodes post provisioning.

**Result**

**Expected Result**
Rancher provides the relevant environment variables to rancher-wins so that it can start the system-agent plan watcher in the desired mode. Rancher is able to provide plans to `rancher-wins` to further configure the service post provisioning. 

**Screenshots**

**Additional context**

The initial PR did make changes with the expectation that windows nodes would receive the new environment variable, however the [original logic implemented that was updated was improperly validated and does not seem to function as intended](https://github.com/rancher/windows/issues/181). Additionally, other aspects of the provisioning process need to be updated to achieve feature parity with linux nodes, such as the version of the system-agent embedded in `rancher-wins`, the `rancher-wins` install script used during node registration, and potentially the flags offered by rancher-wins.

**Comment by markusewalker** [comment]
**QA TEST PLAN**

`agent-tls-mode` set to `system-store` and Rancher is using self-signed certificate
|#|Scenario|
|---|---|
|1|Validate SUC plans are properly deployed to downstream RKE2 `v1.30` Windows node on fresh install of `main`|
|2|Validate SUC plans are properly deployed to downstream RKE2 `v1.30` Windows node on fresh install of `main` and `agent-tls-mode` set to `strict`|
|3|Validate SUC plans are properly deployed to downstream RKE2 `v1.30` Windows nodes after upgrading Rancher and `agent-tls-mode` setting|
|4|Validate SUC plans are NOT deployed to downstream RKE2 deprecated `v1.27` Windows nodes after upgrading Rancher and `agent-tls-mode` setting|
|5|Validate SUC plans are properly deployed after upgrading downstream RKE2 `v1.27` Windows cluster to `v1.30` after upgrading Rancher and `agent-tls-mode` setting|
|6|Setup Rancher with `no-cacerts`, validate SUC plans are properly deployed to downstream RKE2 `v1.30` Windows nodes after upgrading Rancher and `agent-tls-mode` setting|
|7|Repeat scenario 3, but revert `agent-tls-mode` to `system-store` after initial validations|
|8|Repeat scenario 4, but revert `agent-tls-mode` to `system-store` after initial validations|
|9|Repeat scenario 5, but revert `agent-tls-mode` to `system-store` after initial validations|


`agent-tls-mode` set to `system-store` and Rancher is using private CA certs

_Test plan same as above_

**Comment by markusewalker** [comment]
Validated this issue on `head` 9730485c521689c1765061f1fe8e26d581f7c840. In-depth test results can be found in Qase test run /RM 2231. See below the test scenarios tested:

**ENVIRONMENT DETAILS**
- Rancher install: Helm
- Rancher version: `head` 9730485c521689c1765061f1fe8e26d581f7c840

**TEST RESULTS**
|#|Scenario|Result|
|---|---|---|
|1|[Self-signed certificate] Validate SUC plans are properly deployed to downstream RKE2 v1.29 Windows node on fresh install of main and agent-tls-mode set to strict|:white_check_mark:|
|2|[Self-signed certificate] Validate SUC plans are properly deployed to downstream RKE2 v1.29 Windows nodes after upgrading Rancher and agent-tls-mode setting|:white_check_mark:|
|3|[Self-signed certificate] Validate SUC plans are NOT deployed to downstream RKE2 deprecated v1.27 Windows nodes after upgrading Rancher and agent-tls-mode setting|:white_check_mark:|
|4|[Self-signed certificate] Setup Rancher with no-cacerts, validate SUC plans are properly deployed to downstream RKE2 v1.29 Windows nodes after upgrading Rancher and agent-tls-mode setting|:white_check_mark:|
|5|[Private CA] Validate SUC plans are properly deployed to downstream RKE2 v1.29 Windows node on fresh install of main and agent-tls-mode set to strict|:white_check_mark:|
|6|[Private CA] Validate SUC plans are properly deployed to downstream RKE2 v1.29 Windows nodes after upgrading Rancher and agent-tls-mode setting|:white_check_mark:|
|7|[Private CA] Validate SUC plans are NOT deployed to downstream RKE2 deprecated v1.27 Windows nodes after upgrading Rancher and agent-tls-mode setting|:white_check_mark:|
|8|[vSphere Self-signed certificate] Validate SUC plans are properly deployed to downstream RKE2 v1.29 Windows node on fresh install|:white_check_mark:|
|9|[vSphere Private CA] Validate SUC plans are properly deployed to downstream RKE2 v1.29 Windows node on fresh install|:white_check_mark:|
