### ISSUE TITLE
not displaying info : cpu, memory,...

### ISSUE THREAD

**Issue by duardito** [rancher/rancher#4640]
Rancher Version: latest

Docker Version:  1.11.1

OS: debian 8 , kernel 3.16.0-4-amd64

after update my current debian 8 server, rancher is not showing information no more, I am always seing "Connecting.." in each window inside each container.
I remove rancher container, and followed installation page: http://docs.rancher.com/rancher/quick-start-guide/
and still is not working, attached an image with my problem.

![rancher](https://cloud.githubusercontent.com/assets/5726847/14942561/7e2c22da-0fc0-11e6-8df0-d3e7036e2f13.png)

FIXED:

I have downgrade to docker-engine 1.10.3-0 , and it's working fine again.
regards

**Comment by deniseschannon** [comment]
Dupiclate: https://github.com/rancher/rancher/issues/4406

Currently, we only support Docker 1.10.3 in v1.0.1
