### ISSUE TITLE
[Forwardport] Cattle-cleanup job for imported clusters not pulling from configured private registry

### ISSUE THREAD

**Issue by Sahota1225** [rancher/rancher#46401]
Forwardport for : https://github.com/rancher/rancher/issues/40068

Rancher Server Setup

Rancher version: 2.6.9
Installation option (Docker install/Helm Chart): Helm Chart
If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): Generic, 1.21
Proxy/Cert Details: n/a
Information about the Cluster

Kubernetes version: 1.21
Cluster Type (Local/Downstream): Downstream
If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Imported
User Information

What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
If custom, define the set of permissions:
Describe the bug

When deleting an imported cluster from Rancher Dashboard UI, the cattle-cleanup job that is created in the downstream cluster pulls from Dockerhub instead of the configured private registry.

To Reproduce

Import a generic cluster
Delete the generic cluster
Result

A cattle-cleanup job is created, but it pulls its image from Dockerhub and not the configured private registry for the cluster.

Expected Result

cattle-cleanup job should pull from the configured private registry

Screenshots

image
image

Additional context

SURE-8712

**Comment by Josh-Diamond** [comment]
Ticket #46401 - Test Results - ✅ 
---

Verified on Rancher `v2.10.0-alpha2`:

| Scenario | Test Case | Result |
|---|---|---|
| 1. | Import downstream RKE1 cluster => delete imported cluster via Rancher => verify `cattle-cleanup` job | ✅ |
| 2. | Import downstream RKE2 cluster => delete imported cluster via Rancher => verify `cattle-cleanup` job | ✅ |

---

Scenario 1 - ✅ 
1. Fresh install of Rancher `v2.10.0-alpha2`
2. Provision a standalone cluster - ( I used RKE `v1.6.2` w/ k8s `v1.30.4-rancher1-1` )
3. Once `active`, import the cluster into Rancher
4. Wait for cluster to come up `active` in Rancher UI, then delete the imported cluster
5. Verified - cluster successfully deletes from Rancher UI
6. Using `kubectl`, describe the `cattle-cleanup` job and verify where `cleanup-agent` is pulled, using the following command:
```log
kubectl describe job <job_name_here> -n default
```
7. Verified - `cleanup-agent` image points to globally configured private registry; as expected

---

Scenario 2 - ✅ 
1. Fresh install of Rancher `v2.10.0-alpha2`
2. Provision a standalone cluster - ( I used RKE2 w/ k8s `v1.30.5+rke2r1` )
3. Once `active`, import the cluster into Rancher
4. Wait for cluster to come up `active` in Rancher UI, then delete the imported cluster
5. Verified - cluster successfully deletes from Rancher UI
6. Using `kubectl`, describe the `cattle-cleanup` job and verify where `cleanup-agent` is pulled, using the following command:
```log
kubectl describe job <job_name_here> -n default
```
7. Verified - `cleanup-agent` image points to globally configured private registry; as expected
