### ISSUE TITLE
[Forwardport] [CAPR] Upgrading Rancher during etcd restoration from < v2.7.5 to v2.7.5+ can lead to implausible joined server for entry

### ISSUE THREAD

**Issue by Sahota1225** [rancher/rancher#46403]
Forwardport for : https://github.com/rancher/rancher/issues/42856

**Comment by Josh-Diamond** [comment]
Ticket #46403 - Test Results - ✅ 

Verified on Rancher `v2.10-9730485c521689c1765061f1fe8e26d581f7c840-head`:

| Scenario | Test Case | Result |
|---|---|---|
| 1. | Reproduce issue, then upgrade to `v2.10-head` and watch cluster self-resolve | ✅ |

---

Scenario 1 - ✅ 
1. Fresh install of HA Helm Rancher `v2.7.4`
2. Once `active`, provision a downstream Custom K3s cluster w/ k8s `v1.23.17+k3s1` - [ 1 `etcd/cp` + 1 `wkr` ]
3. Once `active`, take two snapshots
4. Move one to your local machine, and delete the other from `/var/lib/rancher/k3s/server/db/snapshots/` on the `etcd/cp` node
5. Snap/restore to deleted snapshot w/ `etcd only` option selected
6. Observe `operation etcd restore failed` error message
7. Attempt to delete etcd machine from cluster - (mine just hung in same error state)
8. Upgrade Rancher to `v2.7.9`
9. Re-delete etcd machine from cluster - (this time it was successfully removed)
10. Register new `etcd/cp` node to custom cluster
11. Create snapshot directory on newly registered `etcd/cp` node by running the following command:
```log
mkdir -p /var/lib/rancher/k3s/server/db/snapshots
```
12. Move snapshot you're storing locally to directory you created in step 11, on newly registered `etcd/cp` node
13. Edit cluster object for downstream Custom k3s, and modify `.spec.etcdSnapshotRestore.Name` to reflect snapshot from step 12, then `save` yaml.  This should be formatted as shown below:
```yaml
spec:
  rkeConfig:
    etcdSnapshotRestore:
      name: <cluster_name>-<snapshot_name>-local
```
14. Reproduced
15. Upgrade Rancher to `v2.10-head`
16. Once upgraded, observe etcd restore proceed and cluster come up `active`
17. Verified - planner is able to restore the cluster; as expected
