### ISSUE TITLE
Add environment id in rancher metadata

### ISSUE THREAD

**Issue by mishak87** [rancher/rancher#4642]
Please add environment id to rancher metadata.

Currently there is no way to check environment id using rancher-agent CATTLE_\* credentials.

---

When provisioning servers with ansible it is easy to check if rancher-agent is talking to right rancher server.

``` sh
docker exec rancher-agent sh -c 'echo "$CATTLE_URL"'
```

It would be useful to have a way to check if rancher-agent is registered in right environment.

``` sh
docker exec rancher-agent sh -c 'curl -u "$CATTLE_ACCESS_KEY:$CATTLE_SECRET_KEY" "$CATTLE_URL/projects/1a23/"' # returns 404
```

Alternatively rancher metadata service can be accessed from rancher-agent container.

``` sh
docker exec rancher-agent curl 169.254.169.250 # only IP rancher-metadata is not available
```

Having environment id in metadata would be useful for other use-cases like monitoring and logging.

**Comment by ibuildthecloud** [comment]
Making the below work is probably not feasible

    docker exec rancher-agent sh -c 'curl -u "$CATTLE_ACCESS_KEY:$CATTLE_SECRET_KEY" "$CATTLE_URL/projects/1a23/"' # returns 404

Instead we would prefer to add this to metadata such that the below would work

     curl http://169.254.169.250/latest/self/host/environment_id

Also note, you don't have to exec into the agent container to hit 169.254.169.250.  It is accessible from the host, just not under the DNS name rancher-metadata.

**Comment by nunofgs** [comment]
Any word on this? Desperately need access to the "environment_id" parameter *somewhere* on rancher metadata.

**Comment by ekristen** [comment]
+1 to this

**Comment by Ashthos** [comment]
This appears to have been implemented into the MetaData service.

Within a rancher controlled container:

`curl http://rancher-metadata/latest/self/stack/environment_name` and `curl http://rancher-metadata/latest/self/stack/environment_uuid` will return the name and id of the environment.

This is available on my rancher v1.4.2

**Comment by gregkeys** [comment]
@Ashthos `curl http://rancher-metadata/latest/self/stack/environment_uuid` returns the long uuid how do we get the short id that is used for the project id with the api?

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
