### ISSUE TITLE
[Forwardport] System-agent-upgrader plan removes system-agent data directory

### ISSUE THREAD

**Issue by Sahota1225** [rancher/rancher#46429]
Forwardport for https://github.com/rancher/rancher/issues/46361

**Comment by susesgartner** [comment]
Ticket #46429 - Test Results - ✅ 
---
 
| Scenario | Test Case | Result |
|---|---|---|
| 1. | Validate that custom system-agent data dir is used | PASS |
| 2. | Validate that the default data dir works | PASS |
 
---
Verified with HA Helm on Rancher `v2.10-head`:
---
Scenario 1: Validate that custom system-agent data dir is used
---
Note: Tested on node driver and k3s/rke2 

1. Create a 3 node split roles cluster with the system-agent dir set 
2. Wait for the cluster to become active
3. SSH into each node and verify that the correct data dir is utilized
4. Validate that /var/lib/rancher/agent doesn't exist
 
Results: The data directory is correctly utilized and /var/lib/rancher/agent doesn't exist
 
---
 
Scenario 2: Validate that the default data dir works
---
1. Create a 3 node split roles rke2 cluster
2. Wait for the cluster to become active
3. Verify that the cluster is in a healthy state.
 
Results: The cluster is in a healthy state
