### ISSUE TITLE
[Forwardport] Custom cluster registration command not including system agent data directory

### ISSUE THREAD

**Issue by Sahota1225** [rancher/rancher#46428]
Forwadport for https://github.com/rancher/rancher/issues/46362

**Comment by Josh-Diamond** [comment]
Ticket #46428 - Test Results -  ✅ 
---

Verified on Rancher `v2.10-3693ad7f6a87a9fdce4b43a7924bbaf281f801ce-head`:

| Scenario | Test Case | Result |
|---|---|---|
| 1. | Provision a downstream RKE2 Custom cluster w/ a custom system-agent data directory specified | ✅ |
| 2. | Provision a downstream K3s Custom cluster w/ a custom system-agent data directory specified | ✅ |

---

Scenario 1 - ✅ 
1. Fresh install of Rancher `v2.10-head`
2. Create a downstream RKE2 Custom cluster set a custom system agent data directory by navigating to `Cluster Configuration > Advanced > Data directory configuration`
3. Verified - registration command includes user specified directory
4. Run registration command against linux nodes
5. Verified - Nodes successfully run command, cluster comes up active, and the custom directory is created and in use on all downstream nodes
6. Register a windows worker node
7. Verified - Node successfully runs command, cluster comes up active and custom directory is present and in use; as expected

---

Scenario 2 - ✅ 
1. Fresh install of Rancher `v2.10-head`
2. Create a downstream K3s Custom cluster set a custom system agent data directory by navigating to `Cluster Configuration > Advanced > Data directory configuration`
3. Verified - registration command includes user specified directory
4. Run registration command against linux nodes
5. Verified - Nodes successfully run command, cluster comes up active, and the custom directory is created and in use on all downstream nodes; as expected
