### ISSUE TITLE
[Forwardport] v2prov certificate rotation does not follow correct order of operations

### ISSUE THREAD

**Issue by Sahota1225** [rancher/rancher#46434]
Forwardport: https://github.com/rancher/rancher/issues/46034

**Comment by Josh-Diamond** [comment]
Ticket #46434 - Test Results - ✅ 
---

Verified on Rancher `v2.10-7f7897bcce2089c720c7a60846dd9fa4a7eb1d96-head`:

| Scenario | Test Case | Result |
|---|---|---|
| 1. | Execute cert-rotation 3 times on downstream RKE2 w/ 3 etcd, 2 cp, 3 wkr | ✅  |
| 2 . | Execute cert-rotation 3 times on downstream RKE2 w/ 1 etcd, 1 cp, 1 wkr | ✅ |
| 3. | Execute cert-rotation 3 times on downstream K3s w/ 3 etcd, 2 cp, 3 wkr | ✅ |
| 4 . | Execute cert-rotation 3 times on downstream K3s w/ 1 etcd, 1 cp, 1 wkr | ✅ |

---

Scenario 1 - ✅ 
1. Fresh install of Rancher `v2.10-head`
2. Provision a downstream RKE2 cluster w/ k8s `v1.30.4+rke2r1` - [3 etcd, 2 cp, 3 wkr]
3. Initiate cert-rotation + monitor logs
4. Verified - cert-rotation executed `etcd pool => cp pool => wkr pool`, and nodes were brought back up `etcd pool => cp pool => wkr pool`
5. Initiate cert-rotation 2 more times + monitor logs
6. Verified - cert-rotation order as expected each time; 3/3 pass

---

Scenario 2 - ✅ 
1. Fresh install of Rancher `v2.10-head`
2. Provision a downstream RKE2 cluster w/ k8s `v1.30.4+rke2r1` - [1 etcd, 1 cp, 1 wkr]
3. Initiate cert-rotation + monitor logs
4. Verified - cert-rotation executed `etcd pool => cp pool => wkr pool`, and nodes were brought back up `etcd pool => cp pool => wkr pool`
5. Initiate cert-rotation 2 more times + monitor logs
6. Verified - cert-rotation order as expected each time; 3/3 pass

---

Scenario 3 - ✅ 
1. Fresh install of Rancher `v2.10-head`
2. Provision a downstream K3s cluster w/ k8s `v1.30.4+k3s1` - [3 etcd, 2 cp, 3 wkr]
3. Initiate cert-rotation + monitor logs
4. Verified - cert-rotation executed `etcd pool => cp pool => wkr pool`, and nodes were brought back up `etcd pool => cp pool => wkr pool`
5. Initiate cert-rotation 2 more times + monitor logs
6. Verified - cert-rotation order as expected each time; 3/3 pass

⚠️  Note: the following issue was encountered during my testing, https://github.com/rancher/rancher/issues/46992, but the correct order of operations were seen consistently, so validating this issue as resolved now 👍 

---

Scenario 4 - ✅ 
1. Fresh install of Rancher `v2.10-head`
2. Provision a downstream K3s cluster w/ k8s `v1.30.4+k3s1` - [1 etcd, 1 cp, 1 wkr]
3. Initiate cert-rotation + monitor logs
4. Verified - cert-rotation executed `etcd pool => cp pool => wkr pool`, and nodes were brought back up `etcd pool => cp pool => wkr pool`
5. Initiate cert-rotation 2 more times + monitor logs
6. Verified - cert-rotation order as expected each time; 3/3 pass
