### ISSUE TITLE
[Forwardport] air gap RKE2 downstream cluster fails to pull images if the registry mirrors endpoint does not contain a schema

### ISSUE THREAD

**Issue by Sahota1225** [rancher/rancher#46433]
Forwardport: https://github.com/rancher/rancher/issues/46090

**Comment by markusewalker** [comment]
**QA TEST PLAN**

|#|Scenario|
|---|---|
|1|Provision RKE2 air-gap downstream cluster with `https://` schema in mirror endpoint|
|2|Provision RKE2 air-gap downstream cluster without `https://` schema in mirror endpoint|
|3|Provision RKE2 non air-gap downstream cluster with `https://` schema in mirror endpoint|
|4|Provision RKE2 non air-gap downstream cluster without `https://` schema in mirror endpoint|

**Comment by jiaqiluo** [comment]
Closing as a duplicate of https://github.com/rancher/rancher/issues/46400
