### ISSUE TITLE
[Forwardport] Remove old versions from vsphere-charts

### ISSUE THREAD

**Issue by Sahota1225** [rancher/rancher#46439]
Forwardport for https://github.com/rancher/rancher/issues/46146

**Comment by snasovich** [comment]
This already went into https://github.com/rancher/charts/tree/dev-v2.10 as PRs for https://github.com/rancher/rancher/issues/46146 went in `dev-v2.9` before `dev-v2.10` branch was cut. So moving to "Ready for QA".

**Comment by Josh-Diamond** [comment]
Ticket #46439 - Test Results - ✅ 
---

Verified on Rancher `v2.10.0-alpha5`:

expected versioning seen for vsphere CPI/CSI images in `rancher-images.txt` for `v2.10.0-alpha5`

CPI images packaged now reflect the following:
- `rancher/mirrored-cloud-provider-vsphere-cpi-release-manager:v1.27.0`
- `rancher/mirrored-cloud-provider-vsphere-cpi-release-manager:v1.28.0`
- `rancher/mirrored-cloud-provider-vsphere-cpi-release-manager:v1.29.0`
- `rancher/mirrored-cloud-provider-vsphere-cpi-release-manager:v1.30.1`

CSI images packaged now reflect the following:
- `rancher/mirrored-cloud-provider-vsphere-csi-release-driver:v3.2.0`
- `rancher/mirrored-cloud-provider-vsphere-csi-release-driver:v3.3.0`
- `rancher/mirrored-cloud-provider-vsphere-csi-release-driver:v3.3.1`
- `rancher/mirrored-cloud-provider-vsphere-csi-release-syncer:v3.2.0`
- `rancher/mirrored-cloud-provider-vsphere-csi-release-syncer:v3.3.0`
- `rancher/mirrored-cloud-provider-vsphere-csi-release-syncer:v3.3.1`
