### ISSUE TITLE
[Forwardport] Run Operations_Test_SetB_* tests for rancher/kontainer-driver-metadata tests

### ISSUE THREAD

**Issue by Sahota1225** [rancher/rancher#46438]
Forwardport for https://github.com/rancher/rancher/issues/45917

**Comment by jakefhyde** [comment]
Moving to Blocked since dev/release branches have not been created for v2.10 yet.

**Comment by jakefhyde** [comment]
Moving to Done since dev-v2.10 was created from existing dev-v2.9 branch https://github.com/rancher/kontainer-driver-metadata/blob/dev-v2.10/.github/workflows/provisioning-tests.yaml
