### ISSUE TITLE
Elasticsearch container stuck on "Starting" when using Rancher Stack

### ISSUE THREAD

**Issue by xxDECKERxx** [rancher/rancher#4643]
Rancher Version:  1.0.1

Docker Version: 1.11.1

OS: CentOs 7

Steps to Reproduce: 

1. Added 3 host machines connected to rancher.
2. Created a new stack with docker-compose:

> elasticsearch:
>   ports:
>     \- 9200:9200/tcp
>   labels:
>     io.rancher.container.pull_image: always
>   tty: true
>   image: elasticsearch
>   stdin_open: true
>   volume_driver: /data/elasticsearch:/usr/share/elasticsearch/data

3. Waiting to see elasticsearch container created on one of the hosts.

Results: 

After creating the stack a container appears to have been created on one of the host machines, but the container becomes stuck on the state "Starting".  Running a "docker ps -a" on the host does not show that a container was created, and I can't find any errors at the moment.

This started once I started using docker 1.11.1

Expected:
Container starts correctly, and I can see it running on the host machine.

**Comment by deniseschannon** [comment]
Was it working with Docker 1.10.3? 

Currently, Rancher only supports Docker 1.10.3, so if this is a Docker 1.11 issue, we can add it to the support for Docker 1.11.

**Comment by xxDECKERxx** [comment]
Thanks for the quick response!  I did some trial and error and it seems to be related to the volume_driver I defined.  I will go back to using the previous docker version for now.

**Comment by deniseschannon** [comment]
It seems like the volume_driver is a known issue for Docker 1.11, but I'll close this issue in favor of https://github.com/rancher/rancher/issues/4491
