### ISSUE TITLE
[Forwardport] Old Ubuntu 20.04 AMIs are used by default when provisioning downstream clusters in AWS

### ISSUE THREAD

**Issue by Sahota1225** [rancher/rancher#46436]
Forwardport for : https://github.com/rancher/rancher/issues/46241

**Comment by markusewalker** [comment]
**QA TEST PLAN**

|#|Scenario|
|---|---|
|1|Provision RKE1 downstream node driver w/AWS defaults|
|2|Provision RKE2 downstream node driver w/AWS defaults|
|3|Provision K3S downstream node driver w/AWS defaults|

**Comment by jiaqiluo** [comment]
PR is merged, now waiting for the new r/r image

**Comment by markusewalker** [comment]
Validated that this issue, see details below:

**ENVIRONMENT DETAILS**
- Rancher install: Docker
- Rancher version: `main` https://github.com/rancher/rancher/commit/2b955aa0e4823baf6fbaf25c898aeae0273c6b48

**TEST RESULT**
|#|Scenario|Result
|---|---|---|
|1|Provision RKE1 downstream node driver w/AWS defaults|:white_check_mark:|
|2|Provision RKE2 downstream node driver w/AWS defaults|:white_check_mark:|
|3|Provision K3S downstream node driver w/AWS defaults|:white_check_mark:|

**VALIDATION STEPS**

**Scenario 1**
1. Provisioned downstream RKE1 `v1.30.3-rancher1-1` AWS node driver cluster.
     - Ensured that I used the default AMI.
2. Validated that cluster and nodes came up as `Active`.
3. Validated that the OS used is Ubuntu 22.04 for each node in the cluster.

_____

**Scenario 2**
1. Repeated scenario, but provisioned RKE2 `v1.30.3+rke2r1` AWS node driver cluster instead.

______

**Scenario 3**
Repeated scenario, but provisioned K3S `v1.30.3+k3s2` AWS node driver cluster instead.
