### ISSUE TITLE
[Forwardport] Provisioning an RKE2 cluster with the data/dir feature enabled causes snapshot restores to fail

### ISSUE THREAD

**Issue by Sahota1225** [rancher/rancher#46431]
Frowdport: https://github.com/rancher/rancher/issues/46066

**Comment by susesgartner** [comment]
Ticket #46431 - Test Results - ✅ 
---
 
| Scenario | Test Case | Result |
|---|---|---|
| 1. | Snapshot/Restore | PASS |
| 2. | k8s upgrade/restore | PASS |
 
---
Verified with (HA Helm or Docker) on Rancher `v2.10-3693ad7f6a87a9fdce4b43a7924bbaf281f801ce-head`:
---
 
Scenario 1: Snapshot/Restore test
---
1. Create downstream rke2 cluster with all data dirs set
2. Take a snapshot
3. Restore the snapshot
 
Results: the snapshot is successfully restored and the cluster is in a good state
 
---
 
Scenario 2: k8s upgrade/restore
---
1. Create downstream rke2 cluster with all data dirs set
2. Take a snapshot
3. Upgrade the K8s version
4. Restore the snapshot
 
Results: the k8s version is successfully downgraded and the cluster is in a good state
