### ISSUE TITLE
[Forwardport] Snapshots fail during creation in Sle Micro 6

### ISSUE THREAD

**Issue by Sahota1225** [rancher/rancher#46445]
Forwardport for https://github.com/rancher/rancher/issues/45815

**Comment by susesgartner** [comment]
Ticket #46445 - Test Results - ✅ 
---
 
| Scenario | Test Case | Result |
|---|---|---|
| 1. | Snapshot create/restore | PASS |
| 2. | Snapshot restore k8s version | PASS |
 
---
Verified with HA Helm on Rancher `v2.10-head`:
---
 
Scenario 1: Snapshot create/restore
---
1.  Provision a Sle micro 6 downstream cluster
2. Create a snapshot
3. Verify that the snapshot is successfully created
4. Restore the snapshot
 
Results: the snapshot successfully restores
 
---

Scenario 2: Snapshot restore k8s version
---
1. Provision a Sle Micro 6 cluster
2. Take a snapshot
3. Upgrade the k8s version
4. Restore the snapshot
 
Results: The k8s version is successfully downgraded and all nodes remain in a stable state
