### ISSUE TITLE
[Forwardport] k8s 1.30 support for vSphere CSI

### ISSUE THREAD

**Issue by Sahota1225** [rancher/rancher#46447]
Forwardport for https://github.com/rancher/rancher/issues/45747

**Comment by Josh-Diamond** [comment]
Ticket #46447 - Test Results - ✅ 
---

Verified on Rancher `v2.10-a1a0d2edf04548b0a9099f86bcf8c194771db8f8-head`:

| Scenario | Test Case | Result |
|---|---|---|
| 1. | Provision a downstream RKE2 Vsphere Cloud Provider enabled cluster w/ k8s `v1.30.4+rke2r1` | ✅ |
| 2. | Provision a downstream RKE1 Vsphere Cloud Provider enabled cluster w/ k8s `v1.30.3-rancher1-1` | ✅ |

---

Scenario 1 - ✅ 
1. Fresh install of Rancher `v2.10-head`
2. Provision a downstream RKE2 Vsphere Cloud provider cluster w/ k8s `v1.30.4+rke2r1`
3. Verified - cluster successfully provisions; all pods `active`; CSI in use `rancher-vsphere-csi:3.3.0-rancher100`

---

Scenario 2 - ✅ 
1. Fresh install of Rancher `v2.10-head`
2. Provision a downstream RKE1 Vsphere Cloud provider cluster w/ k8s `v1.30.3-rancher1-1`
3. Verified - cluster successfully provisions; all pods `active`; CSI in use `rancher-vsphere-csi:104.0.1+up3.3.0-rancher2`
