### ISSUE TITLE
[Forwardport] Downstream RKE2 Vsphere Cloud Provider clusters pull incorrect versioning for CSI pod images, which result in imagepullbackoff error

### ISSUE THREAD

**Issue by Sahota1225** [rancher/rancher#46449]
Forwardport for https://github.com/rancher/rancher/issues/46132

**Comment by Josh-Diamond** [comment]
Ticket #46132 - Test Results - ✅ 
---

Verified on Rancher `v2.10-a1a0d2edf04548b0a9099f86bcf8c194771db8f8-head`:

| Scenario | Test Case | Result |
|---|---|---|
| 1. | Provision a Vsphere Cloud Provider enabled cluster using k8s `v1.30.4+rke2r1` and the latest available CSI chart | ✅ |

---

Scenario 1 - ✅ 
1. Fresh install of Rancher `v2.10-head`
2. Provision a downstream Vsphere Cloud Provider enabled cluster w/ k8s `v1.30.4+rke2r1`
3. Verified - cluster comes up `active`, all pods `active` and `ready`
4. Verified - all CSI pods are properly tagged and `active`; as expected
