### ISSUE TITLE
[Forwardport] [Maintenance] Bump embedded system-agent within rancher-wins

### ISSUE THREAD

**Issue by Sahota1225** [rancher/rancher#46440]
Forwardport for : https://github.com/rancher/rancher/issues/46219

**Comment by markusewalker** [comment]
**QA TEST PLAN**

|#|Scenario|
|---|---|
|1|Run provisioning automated test suite on fresh install of v2.9-head|
|2|Run nodescaling automated test suite on fresh install of v2.9-head|
|3|Run snapshot automated test suite on fresh install of v2.9-head|
|4|Run upgrade automated test suite on fresh install of v2.9-head|
|5|Run certrotation automated test suite on fresh install of v2.9-head|
|6|Run provisioning automated test suite upgraded Rancher to v2.9-head|
|7|Run nodescaling automated test suite upgraded Rancher to v2.9-head|
|8|Run snapshot automated test suite on upgraded Rancher to v2.9-head|
|9|Run upgrade automated test suite on upgraded Rancher to v2.9-head|
|10|Run certrotation automated test suite on upgraded Rancher to v2.9-head|

**Comment by markusewalker** [comment]
Performed testing below. See results below:

**ENVIRONMENT DETAILS**
- Rancher install: Docker
- Rancher version:
     - Fresh install: main https://github.com/rancher/rancher/commit/2b955aa0e4823baf6fbaf25c898aeae0273c6b48
     - Upgrade: `v2.9.0`

**TEST RESULT**
|#|Scenario|Result
|---|---|---|
|1|Run provisioning automated test suite on fresh install of main|:white_check_mark:|
|2|Run nodescaling automated test suite on fresh install of main|:white_check_mark:|
|3|Run snapshot automated test suite on fresh install of main|:white_check_mark:|
|4|Run upgrade automated test suite on fresh install of main|:white_check_mark:|
|5|Run provisioning automated test suite upgraded Rancher from `v2.9.0` to main|:white_check_mark:|
|6|Run nodescaling automated test suite upgraded Rancher from `v2.9.0` to main|:white_check_mark:|
|7|Run snapshot automated test suite on upgraded Rancher from `v2.9.0` to main|:white_check_mark:|
|8|Run upgrade automated test suite on upgraded Rancher from `v2.9.0` to main|:white_check_mark:|
|9|Perform encryption key rotation|:white_check_mark:|
