### ISSUE TITLE
[Backport] Validation of custom data directories for RKE2/K3s provisioning 

### ISSUE THREAD

**Issue by Sahota1225** [rancher/rancher#46452]
Backport for : https://github.com/rancher/rancher/issues/46381

**Comment by susesgartner** [comment]
Ticket #46452 - Test Results - ✅
---
 
| Scenario | Test Case | Result |
|---|---|---|
| 1. | Invalid entry test | PASS |
 
---
Verified with HA Helm on Rancher `v2.9.2-alpha4`:
---
 
Scenario 1: Invalid entry test 
---
Verify each of the following return scenarios return a webhook error:
1. All data/dirs have the same name 
2. non-absolute paths i.e .. , ., ~, *, $envVar
3. 1 data dir nested in another
 
Results: Webhook returns an error in all invalid cases
