### ISSUE TITLE
Remove default Docker Install URL in UI for vmware vsphere driver

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#4645]
Rancher Version:
v1.1.0-dev1-rc2

Steps to Reproduce: 
1. Add a vmware vsphere host

Results: 
By default, `--engine-install-url` is populated in the Advanced Options.

Error: `Error setting machine configuration from flags provided: --engine-install-url cannot be used with the vmwarevsphere driver, use --vmwarevsphere-boot2docker-url instead`

Expected:
We should not have the `engine-install-url` set in the UI for vmware vsphere if it isn't accepted. 

Workaround:
Make sure to expand the Advanced Options to remove the "Docker Install URL" before creating the host.

**Comment by tfiduccia** [comment]
Version - master 5/13
Verified fixed
