### ISSUE TITLE
[Backport 2.9] Add support for Docker 27.0.x and 27.1.x

### ISSUE THREAD

**Issue by Sahota1225** [rancher/rancher#46455]
Backport: https://github.com/rancher/rancher/issues/46326

**Comment by rishabhmsra** [comment]
Validated on rancher v2.9.1:
- On Oracle linux 8.7, 8.8, 8.9, 8.10. 9.1, 9.2, 9.3, 9.4 and Ubuntu 22 and 24, validated below docker scripts by creating RKE1 node driver as well as custom clusters:
  - https://releases.rancher.com/install-docker-dev/27.1.1.sh
  - https://releases.rancher.com/install-docker-dev/27.0.3.sh 

- On Oracle linux 8.10, and 9.4 and on Ubuntu 22 and 24, validated below docker scripts by creating RKE1 node driver as well as custom clusters:
  - https://releases.rancher.com/install-docker-dev/26.1.4.sh
  - https://releases.rancher.com/install-docker-dev/27.0.1.sh
  - https://releases.rancher.com/install-docker-dev/27.0.2.sh
  - https://releases.rancher.com/install-docker-dev/27.1.0.sh

**Comment by mitulshah-suse** [comment]
@kinarashah testing for the docker 27.0.x, 27.1.x versions is done. Can you please release the versions?
cc: @snasovich

**Comment by kinarashah** [comment]
All versions released, https://releases.rancher.com/install-docker/27.1.sh points to `27.1.1`.

**Comment by mitulshah-suse** [comment]
Moving back to development for updating default versions.

**Comment by vivek-shilimkar** [comment]
The Support for docker v27.0.x and v27.1.x is added in v2.9-head.

![Image](https://github.com/user-attachments/assets/36a03ef4-6d6f-4849-933c-a3fd9315f8be)

Hence closing this issue.
