### ISSUE TITLE
[Backport][Windows] STRICT_VERIFY environment variable is not passed to windows nodes

### ISSUE THREAD

**Issue by Sahota1225** [rancher/rancher#46451]
Backport for https://github.com/rancher/rancher/issues/46396

**Comment by markusewalker** [comment]
Validated this issue on `v2.9-head` https://github.com/rancher/rancher/commit/db81de3553c19f63d92666d13a71ba85a44e2142. In-depth test results can be found in Qase test run /RM 2196. See below the test scenarios tested:

**ENVIRONMENT DETAILS**
- Rancher install: Helm
- Rancher version: `v2.9-head` https://github.com/rancher/rancher/commit/db81de3553c19f63d92666d13a71ba85a44e2142

**TEST RESULTS**
|#|Scenario|Result|
|---|---|---|
|1|[Self-signed certificate] Validate SUC plans are properly deployed to downstream RKE2 v1.29 Windows node on fresh install|:white_check_mark:|
|2|[Self-signed certificate] Validate SUC plans are properly deployed to downstream RKE2 v1.29 Windows node on fresh install of main and agent-tls-mode set to strict|:white_check_mark:|
|3|[Self-signed certificate] Validate SUC plans are properly deployed to downstream RKE2 v1.29 Windows nodes after upgrading Rancher and agent-tls-mode setting|:white_check_mark:|
|4|[Self-signed certificate] Validate SUC plans are NOT deployed to downstream RKE2 deprecated v1.27 Windows nodes after upgrading Rancher and agent-tls-mode setting|:white_check_mark:|
|5|[Self-signed certificate] Setup Rancher with no-cacerts, validate SUC plans are properly deployed to downstream RKE2 v1.29 Windows nodes after upgrading Rancher and agent-tls-mode setting|:white_check_mark:|
|6|[Private CA] Validate SUC plans are properly deployed to downstream RKE2 v1.29 Windows node on fresh install of main and agent-tls-mode set to strict|:white_check_mark:|
|7|[Private CA] Validate SUC plans are properly deployed to downstream RKE2 v1.29 Windows nodes after upgrading Rancher and agent-tls-mode setting|:white_check_mark:|
|8|[Private CA] Validate SUC plans are NOT deployed to downstream RKE2 deprecated v1.27 Windows nodes after upgrading Rancher and agent-tls-mode setting|:white_check_mark:|
