### ISSUE TITLE
[Backport] Windows rke2 custom cluster - nodes stop displaying metrics in Monitoring after upgrading kubernetes version

### ISSUE THREAD

**Issue by Sahota1225** [rancher/rancher#46467]
Backport for https://github.com/rancher/rancher/issues/42414

**Comment by markusewalker** [comment]
Discussed this issue offline. RKE2 team handled validations for this, but wanted to perform a quick smoke test to ensure all was good on Rancher's end. See details below:

**ENVIRONMENT DETAILS**
- Rancher install: Docker
- Rancher version: `v2.9-head` https://github.com/rancher/rancher/commit/93a68b99cae6d4ca90949a15eb7491d97c0e9882

**TEST RESULT**
|#|Scenario|Result
|---|---|---|
|1|Metrics are displaying after upgrading RKE2 Windows cluster|:white_check_mark:|

**VALIDATION STEPS**
1. Provisioned downstream RKE2 `v1.29.8+rke2r1` vsphere cluster (1 etcd, 1 cp, 1 Linux worker, 1 Windows worker)
2. Installed Monitoring chart.
3. Deployed Windows workload with image `mcr.microsoft.com/windows/servercore/iis`.
4. Validated that monitoring metrics are being displayed
5. Upgraded cluster to `v1.30.4+rke2r1`.
6. Validated that monitoring metrics are still being displayed.
