### ISSUE TITLE
Add debug to KDM args for k3s and rke2

### ISSUE THREAD

**Issue by rancher-max** [rancher/rancher#46473]
https://github.com/rancher/rancher/issues/46471

**Comment by snasovich** [comment]
This issue is for 2.10 milestone so depending on when/how we branch KDM and when change for https://github.com/rancher/rancher/issues/46472 gets merged this may be included "automagically".

**Comment by snasovich** [comment]
This is done per https://github.com/rancher/kontainer-driver-metadata/pull/1471, moving "To Test".
@rancher-max , could you have someone validate it?

**Comment by mdrahman-suse** [comment]
## Validated on Rancher v2.10.0-alpha3 on RKE2 v1.31.1+rke2r1
- Added flag `debug: true` on the yaml under `machineGlocalConfig`

### RKE2
- Provisioned RKE2 v1.31.1+rke2r1, added the flag on the yaml after provisioning
<img width="258" alt="Screen Shot 2024-10-21 at 3 11 48 PM" src="https://github.com/user-attachments/assets/b1ec287b-fa26-46dc-92e2-a7fe435a4183">

- All the nodes have the flag
<img width="1740" alt="Screen Shot 2024-10-21 at 3 07 07 PM" src="https://github.com/user-attachments/assets/d8db75c2-9130-41e3-a83e-5a295e9e34eb">

### K3S
- Provisioned K3S v1.31.1+k3s1, added the flag before provisioning
<img width="258" alt="Screen Shot 2024-10-21 at 3 12 37 PM" src="https://github.com/user-attachments/assets/087a1c9c-52c7-4db5-a817-859a03838d93">

- All nodes have the flag
<img width="1753" alt="Screen Shot 2024-10-21 at 3 09 03 PM" src="https://github.com/user-attachments/assets/c22bb326-3ca2-442e-aa43-91a5209901f4">

CC: @ShylajaDevadiga @snasovich
