### ISSUE TITLE
[2.8] Add debug to KDM args for k3s and rke2

### ISSUE THREAD

**Issue by rancher-max** [rancher/rancher#46471]
https://github.com/rancher/kontainer-driver-metadata/pull/1348

**Comment by ShylajaDevadiga** [comment]
Validated on Rancher v2.8-head, updated config with debug set to true

rke2:  Validated debug arg is present on all nodes
<img width="2037" alt="image" src="https://github.com/user-attachments/assets/d6aba8f3-7576-4583-994b-aea15903ffe9">


k3s: Validated debug arg is present on all nodes
<img width="2032" alt="image" src="https://github.com/user-attachments/assets/e1790058-033f-4fd8-8d73-21ca7ff5bc92">
