### ISSUE TITLE
[2.8] AWS region support ca-west-1 [RFE]

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#46488]
backport of https://github.com/rancher/rancher/issues/44214 in the v2.8.x release line

**Comment by snasovich** [comment]
This will be done indirectly as part of bumping `rancher/machine` for https://github.com/rancher/rancher/issues/46242

**Comment by jiaqiluo** [comment]
The fix can be validated on the latest v2.8-head image
