### ISSUE TITLE
[BUG] KDM data (`data.json`) included in v2.9.0 image unintentionally includes July 2024 RKE1 patches

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#46484]
**Rancher Server Setup**
- Rancher version: v2.9.0
- Installation option (Docker install/Helm Chart): Any
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): Any
- Proxy/Cert Details: N/A

**Information about the Cluster**
- Kubernetes version: N/A
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Any

**Describe the bug**
KDM data (`data.json`) included in v2.9.0 image unintentionally includes July RKE1 patches which results in these versions available for provisioning on airgap setups.

**To Reproduce**
1. Deploy Rancher v2.9.0 on the environment with no Internet access (or at least no access to https://releases.rancher.com/kontainer-driver-metadata/release-v2.9/data.json)
2. Open UI to provision new RKE1 cluster

**Result**
Versions `v1.30.3-rancher1-1`, `v1.29.7-rancher1-1`, `v1.28.12-rancher1-1`, `v1.27.16-rancher1-1` are available to be selected.

Note the provisioning of these versions is likely to succeed provided necessary images are loaded to registry setup for the airgapped deployment.

**Expected Result**
Instead, validated versions `v1.30.2-rancher1-1`, `v1.29.6-rancher1-1`, `v1.28.11-rancher1-1`, `v1.27.15-rancher1-1` should be available as default patches.

**Screenshots**
![image](https://github.com/user-attachments/assets/1a99ade0-a92b-4d24-81b4-9262a003a2cc)

**Additional context**
Versions `v1.30.2-rancher1-1`, `v1.29.6-rancher1-1`, `v1.28.11-rancher1-1`, `v1.27.15-rancher1-1` are shown as expected in case Rancher installation has access to update KDM data as the data currently published to https://releases.rancher.com/kontainer-driver-metadata/release-v2.9/data.json has expected (these) patch versions as the latest available.

The current plan is to accelerate release of July patches so this "bug" becomes the intended behavior (see https://github.com/rancher/rancher/issues/46226).

**Comment by markusewalker** [comment]
QA validated that provisioning all listed versions was successful along with automated post cluster provisioning checks. Additionally, standalone RKE was successful with `RKE v1.6.1-rc1` along with post cluster provisioning checks.
