### ISSUE TITLE
Support issystem:true for catalog templates

### ISSUE THREAD

**Issue by will-chan** [rancher/rancher#4648]
Rancher currently uses the "Rancher-Service" category to automatically place templates launched here to appear under the "System" tab in the UI.  We should introduce a field in the catalog "issystem:true" to indicate this instead.

**Comment by sshipway** [comment]
+1 for this.  This would allow community catalogue items -- such as 'Janitor', 'Sysdig' and so on -- to be classified to be in the System section, keeping them away from Environment Members who might cause damage.

This would be even more helpful if the System tab were inaccessible to Restricted Members ....?

**Comment by haswalt** [comment]
+1 I have quite a few services that I run and would class as "System" services.

**Comment by soumyalj** [comment]
Verified in v1.1.0-dev5-rc2. Added the isSystem=True in config.yml of the catalog. Was able to see it in the catalog API [Inspect Tool in Browser]
