### ISSUE TITLE
Update ports without container recreation

### ISSUE THREAD

**Issue by clicman** [rancher/rancher#4650]
It would be nice if will possible to manage exposed ports without container recreation (service upgrade).
It will cover case on fixed exposing tcp ports on same host with load balancer service. Needed for dev ci environments.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.0.1` Cattle: `v0.159.7` UI: `v1.0.5` |
|Access|`github` `admin`|
|Route|`environment.index`|

**Comment by deniseschannon** [comment]
Unfortunately Docker containers are immutable (not changeable) after creation. The only things you can edit are things that we store that aren't really part of the container (name, description) or are accomplished with magic the network agent enables (linked container destinations).

This includes rebooting, it's still the same container if you stop and start it. So you pretty much have to remove and recreate a container to change anything else.
