### ISSUE TITLE
[UI] Feature Request: Search Hotkey

### ISSUE THREAD

**Issue by adamgoose** [rancher/rancher#4651]
Feature Request
Rancher Version: v1.0.1
Docker Version: 1.10.2
OS: Ubuntu 14.04.3 LTS

While browsing the catalog, I'd like to press a hotkey ('/' perhaps) to trigger focus on the search field. @laracasts used to have a great hotkey-triggered search, but I think he removed it. :(

**Comment by vincent99** [comment]
This (and other shortcut keys) are in 2.0.  And I even picked `/`, because as vim users that is the only correct key.
