### ISSUE TITLE
[question] upgraded from v0.59.0 to v1.1.0-dev1. Any issues with that?

### ISSUE THREAD

**Issue by fentas** [rancher/rancher#4652]
Hey there,
I upgraded my rancher/server to latest (v1.1.0-dev1) and now I read the following:
> NOTE: Please do not upgrade any existing deployments with this release as it does not contain all the DB migration scripts for a proper upgrade. Only new installs please. We will explicitly note the RC release that has gone through our normal upgrade testing.

Everything seems to work fine. Only thing I saw in the logs was
```
2016-05-03 06:07:27,467 WARN    [main] [liquibase] modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
```

Do I have to do something special to prevent issues in the future?

**Comment by vincent99** [comment]
@deniseschannon will follow up in the morning, but I think that's just mis-copied from earlier `-rc` release notes.  Upgrades between non-`rc` releases should be supported.

**Comment by deniseschannon** [comment]
@fentas Where did you see that section?

I didn't see it in the release notes for v1.1.0-dev1.

**Comment by deniseschannon** [comment]
@fentas Let me know if you have further questions, but I believe there are some forum posts of others who have done a similar upgrade path as you are asking about. :)

https://forums.rancher.com/t/upgrade-path-from-0-59-1-to-1-0-1/2233
