### ISSUE TITLE
Feature Request: Select docker-composer from list

### ISSUE THREAD

**Issue by JaviSabalete** [rancher/rancher#4653]
Currently, Rancher offers load rancher-composer by two methods, paste or load from file.

The idea here would be to have an admin section where add differents rancher-composer. Admins should be able to select how many environments can load the differents rancher-composer stored.

Thanks in advance

**Comment by vincent99** [comment]
This is basically what the catalog is (and you can define your own)

**Comment by deniseschannon** [comment]
http://docs.rancher.com/rancher/latest/en/catalog/

And creating your own catalogs

http://docs.rancher.com/rancher/latest/en/catalog/#creating-private-catalogs
