### ISSUE TITLE
[2.8] upgrade docker install from 2.8.3 -> 2.8.4 fails

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#46541]
backport #45841

**Comment by nickwsuse** [comment]
Verified on v2.8-head ID: `68e5d43` ✅
----
Fresh Install ✅
Docker upgrade from v2.8.6 -> v2.8-head ✅
Docker upgrade from v2.8.5 -> v2.8-head ✅
Docker upgrade from v2.8.4 -> v2.8.5 -> v2.8-head ✅

HA upgrade from v2.8.6 -> v2.8-head ✅
HA upgrade from v2.8.5 -> v2.8-head ✅
HA upgrade from v2.8.4 -> v2.8.5 -> v2.8-head ✅
