### ISSUE TITLE
Unable to register agents with Active Directory authentication enabled

### ISSUE THREAD

**Issue by jenxie** [rancher/rancher#4655]
Rancher Version: v1.0.1

Docker Version: 1.11.1, build 5604cbe

OS: Ubuntu 16.04

Steps to Reproduce:
- Create 3 node Rancher HA cluster using generated certs, according to documentation, all nodes are on seperate VM's in vSphere including MySQL DB.
- Setup Access Control with Active Directory and login with an AD account.
- Switch to System HA environment and check that everything is green under Infrastructure and Appstack: management
- Go back to Default environment and Add host
- Create 3 hosts using Other, Driver: vmwarevsphere

Results:
- 'Almost there... Waiting for agent connection' on all 3 machines
- docker logs rancher-agent-bootstrap (only container on the machine):

```
INFO: Attempting to connect to: https://rancher.local/v1
ERROR: https://rancher.local/v1 is not accessible
```

From docker VM and it's container I'm able to manually
`curl --insecure https://rancher.local/v1/scripts/DEBCE605998582A02D0:1462262400000:secretkey`
```
#!/bin/sh

export CATTLE_REGISTRATION_ACCESS_KEY="registrationToken"
export CATTLE_REGISTRATION_SECRET_KEY="DEBCE605998582A02D0:1462262400000:secretkey"
export CATTLE_URL="https://rancher.local/v1"
export DETECTED_CATTLE_AGENT_IP="10.46.22.128"
```
Though that agent IP is incorrect, that IP is the SubnetIP in our external loadbalancer (NetScaler)

Expected:
That the agent is able to connect to rancher.local

Found a similar old issue #142 but doesn't seem related since the output is stripped off:
```
print_url()
{
    local url=$(echo "$1"| sed -e 's!/v1/scripts.*!/v1!')
    echo $url
}
```
```
wait_for()
{
    local url="$(print_url $CATTLE_URL)"
    info "Attempting to connect to: ${url}"
    for ((i=0; i < 300; i++)); do
        if ! curl -f -L -s ${CATTLE_URL} >/dev/null 2>&1; then
            error ${url} is not accessible
            sleep 2
            if [ "$i" -eq "299" ]; then
                error "Could not reach ${url}. Giving up."
                exit 1
            fi
        else
            info "${url} is accessible"
            break
        fi
    done
}
```
Hence removing the call for print_url and changing ${url} to ${CATTLE_URL} i can see the full url correctly, but still not more than that.

**Comment by deniseschannon** [comment]
Instead of launching through the other driver, would you be able to spin up something in vmware and then use the command in the custom screen and add in the IP of the address so it modifies the command to add in `-e CATTLE_AGENT_IP=<ip>`.

**Comment by LLParse** [comment]
In addition to what @deniseschannon mentioned, please make sure to copy your ca.crt (management certificate on the UI screen) to /var/lib/rancher/etc/ssl/<ca.crt> before running the Custom registration command.

**Comment by jenxie** [comment]
Yep, that works

**Comment by jenxie** [comment]
Since using self-signed certificates is in beta stage, I changed to a domain we had a wildcard certificate for and that solved the problem.
