### ISSUE TITLE
Rebase monitoring to current latest upstream

### ISSUE THREAD

**Issue by joshmeranda** [rancher/rancher#46551]
Rebase rancher-monitoring to bring it up to date with the upstreamn. This will make is easier to make smaller and more manageable rebases in the future.

QA Notes:
Use [105.1.0-rc1+up61.3.2](https://github.com/rancher/charts/tree/dev-v2.10/charts/rancher-monitoring/105.1.0-rc1%2Bup61.3.2) to test

**Comment by joshmeranda** [comment]
blocked by https://github.com/rancher/image-mirror/pull/687

**Comment by pankajsqe** [comment]
Regression test post Rancher-monitoring rebase was successfully completed.  

Details :
Rancher : v2.10-head
cluster : v1.30.2+k3s2
charts repo : dev-v2.10
monitoring : 105.1.0-rc1+up61.3.2 

![Image](https://github.com/user-attachments/assets/c9a97646-eeee-41b1-99cf-3f49dc043532)
![Image](https://github.com/user-attachments/assets/8400406f-7451-4cc4-8e5b-4890049ed4d6)
![Image](https://github.com/user-attachments/assets/e51a048d-4ccf-40a8-bc64-10e5c7615156)
![Image](https://github.com/user-attachments/assets/e85c3c2f-85aa-4c69-b008-4a6aacc556b3)
![Image](https://github.com/user-attachments/assets/f46033c1-6bfe-46d2-acf4-7324b8656ded)
