### ISSUE TITLE
Bug - Kubernetes agent websocket is closing 

### ISSUE THREAD

**Issue by tsupertramp** [rancher/rancher#4656]
Rancher Version:
1.0.1
Docker Version:
1.10.3
OS: 
ubuntu
Steps to Reproduce: 

Results: 
Expected:3.5.2016 10:46:39time="2016-05-03T08:46:39Z" level=error msg="Kubernetes stream listener exited with error: Error reading from websocket for [ws://master/api/v1/services?watch=true]: websocket: close 1000 "

Rancher Kubernetes-Agent is restarting all the time.
Happening in both of my kubernetes Env (staging, production)

Can't see anything on the master nodes which would help to debug.
Any advice how to debug this?

Added logfile to allow better debugging (removed some secrets/urls and pod definitions)

<pre>
3.5.2016 10:34:17Response <= {"kind":"Namespace","apiVersion":"v1","metadata":{"name":"default","selfLink":"/api/v1/namespaces/default","uid":"3b64560f-0c7a-11e6-b732-02fdcbea54e8","resourceVersion":"10207","creationTimestamp":"2016-04-27T13:16:20Z"},"spec":{"finalizers":["kubernetes"]},"status":{"phase":"Active"}}
3.5.2016 10:34:17
3.5.2016 10:34:17time="2016-05-03T08:34:17Z" level=info msg="Connecting to event stream." url="ws://master/api/v1/replicationcontrollers?watch=true"
3.5.2016 10:34:17time="2016-05-03T08:34:17Z" level=info msg="Received event: [{\"type\":\"ADDED\",\"Removed message
3.5.2016 10:34:17time="2016-05-03T08:34:17Z" level=info msg="Connecting to event stream." url="ws://master/api/v1/pods?watch=true"
3.5.2016 10:34:17time="2016-05-03T08:34:17Z" level=info msg="Received event: [{\"type\":\"ADDED\",\"Removed message
3.5.2016 10:34:17time="2016-05-03T08:34:17Z" level=info msg="Received event: [{\"type\":\"ADDED\",\"Removed message
3.5.2016 10:34:17time="2016-05-03T08:34:17Z" level=info msg="Received event: [{\"type\":\"ADDED\",\"Removed message
3.5.2016 10:34:17time="2016-05-03T08:34:17Z" level=info msg="Initializing event router" workerCount=50
3.5.2016 10:34:17time="2016-05-03T08:34:17Z" level=info msg="Received event: [{\"type\":\"ADDED\",\"Removed message
3.5.2016 10:34:17time="2016-05-03T08:34:17Z" level=info msg="Received event: [{\"type\":\"ADDED\",\"Removed message
3.5.2016 10:34:17time="2016-05-03T08:34:17Z" level=info msg="Received event: [{\"type\":\"ADDED\",\"Removed message
3.5.2016 10:34:17time="2016-05-03T08:34:17Z" level=info msg="Received event: [{\"type\":\"ADDED\",\"Removed message
3.5.2016 10:34:17time="2016-05-03T08:34:17Z" level=info msg="Received event: [{\"type\":\"ADDED\",\"Removed message
3.5.2016 10:34:17time="2016-05-03T08:34:17Z" level=info msg="Received event: [{\"type\":\"ADDED\",\"Removed message
3.5.2016 10:34:17time="2016-05-03T08:34:17Z" level=info msg="Connection established"
3.5.2016 10:34:17time="2016-05-03T08:34:17Z" level=info msg="Received event: [{\"type\":\"ADDED\",\"Removed message
3.5.2016 10:34:17time="2016-05-03T08:34:17Z" level=info msg="Received event: [{\"type\":\"ADDED\",\"Removed message
3.5.2016 10:34:17Request => GET http://master/api/v1/namespaces/default
3.5.2016 10:34:17Response <= {"kind":"Namespace","apiVersion":"v1","metadata":{"name":"default","selfLink":"/api/v1/namespaces/default","uid":"3b64560f-0c7a-11e6-b732-02fdcbea54e8","resourceVersion":"10207","creationTimestamp":"2016-04-27T13:16:20Z"},"spec":{"finalizers":["kubernetes"]},"status":{"phase":"Active"}}
3.5.2016 10:34:17
3.5.2016 10:34:17time="2016-05-03T08:34:17Z" level=info msg="Received event: [{\"type\":\"ADDED\",\"Removed message
3.5.2016 10:34:18time="2016-05-03T08:34:18Z" level=info msg="Received event: [{\"type\":\"ADDED\",\"Removed message
3.5.2016 10:34:18Request => GET http://master/api/v1/namespaces/default
3.5.2016 10:34:18Response <= {"kind":"Namespace","apiVersion":"v1","metadata":{"name":"default","selfLink":"/api/v1/namespaces/default","uid":"3b64560f-0c7a-11e6-b732-02fdcbea54e8","resourceVersion":"10207","creationTimestamp":"2016-04-27T13:16:20Z"},"spec":{"finalizers":["kubernetes"]},"status":{"phase":"Active"}}
3.5.2016 10:34:18
3.5.2016 10:34:30time="2016-05-03T08:34:30Z" level=error msg="Kubernetes stream listener exited with error: Error reading from websocket for [ws://master/api/v1/services?watch=true]: websocket: close 1000 "
3.5.2016 10:34:30time="2016-05-03T08:34:30Z" level=info msg=Exiting.
3.5.2016 10:34:36time="2016-05-03T08:34:36Z" level=info msg="Watching changes for kinds: [namespaces services replicationcontrollers pods]"
3.5.2016 10:34:36time="2016-05-03T08:34:36Z" level=info msg="Listening for health checks on 0.0.0.0:10240/healthcheck"
3.5.2016 10:34:36time="2016-05-03T08:34:36Z" level=info msg="Starting kubernetes event listener configuration: {KubernetesURL:http://master CattleURL:https://rancher-int.somecompany.com/v1 CattleAccessKey:SOMECOOLACCESSKEY CattleSecretKey:SOMEREALLYCOOLSECRET WorkerCount:50 HealthCheckPort:10240}"
3.5.2016 10:34:36time="2016-05-03T08:34:36Z" level=info msg="Connecting to event stream." url="ws://master/api/v1/services?watch=true"
3.5.2016 10:34:36time="2016-05-03T08:34:36Z" level=info msg="Connecting to event stream." url="ws://master/api/v1/namespaces?watch=true"
3.5.2016 10:34:36time="2016-05-03T08:34:36Z" level=info msg="Received event: [{\"type\":\"ADDED\",\"Removed message
3.5.2016 10:34:36Request => GET http://master/api/v1/namespaces/default
3.5.2016 10:34:36time="2016-05-03T08:34:36Z" level=info msg="Connecting to event stream." url="ws://master/api/v1/services?watch=true"
3.5.2016 10:34:36time="2016-05-03T08:34:36Z" level=info msg="Received event: [{\"type\":\"ADDED\",\"Removed message
3.5.2016 10:34:36time="2016-05-03T08:34:36Z" level=info msg="Connecting to event stream." url="ws://master/api/v1/replicationcontrollers?watch=true"
3.5.2016 10:34:36time="2016-05-03T08:34:36Z" level=info msg="Received event: [{\"type\":\"ADDED\",\"Removed message
3.5.2016 10:34:36Response <= {"kind":"Namespace","apiVersion":"v1","metadata":{"name":"default","selfLink":"/api/v1/namespaces/default","uid":"3b64560f-0c7a-11e6-b732-02fdcbea54e8","resourceVersion":"10207","creationTimestamp":"2016-04-27T13:16:20Z"},"spec":{"finalizers":["kubernetes"]},"status":{"phase":"Active"}}
3.5.2016 10:34:36
3.5.2016 10:34:36time="2016-05-03T08:34:36Z" level=info msg="Connecting to event stream." url="ws://master/api/v1/pods?watch=true"
3.5.2016 10:34:36time="2016-05-03T08:34:36Z" level=info msg="Received event: [{\"type\":\"ADDED\",\"Removed message
3.5.2016 10:34:36time="2016-05-03T08:34:36Z" level=info msg="Received event: [{\"type\":\"ADDED\",\"Removed message
3.5.2016 10:34:36time="2016-05-03T08:34:36Z" level=info msg="Received event: [{\"type\":\"ADDED\",\"Removed message
3.5.2016 10:34:36time="2016-05-03T08:34:36Z" level=info msg="Initializing event router" workerCount=50
3.5.2016 10:34:36time="2016-05-03T08:34:36Z" level=info msg="Received event: [{\"type\":\"ADDED\",\"Removed message
3.5.2016 10:34:36time="2016-05-03T08:34:36Z" level=info msg="Received event: [{\"type\":\"ADDED\",\"Removed message
3.5.2016 10:34:36time="2016-05-03T08:34:36Z" level=info msg="Received event: [{\"type\":\"ADDED\",\"Removed message
3.5.2016 10:34:36time="2016-05-03T08:34:36Z" level=info msg="Received event: [{\"type\":\"ADDED\",\"Removed message
3.5.2016 10:34:36time="2016-05-03T08:34:36Z" level=info msg="Connection established"
3.5.2016 10:34:36time="2016-05-03T08:34:36Z" level=info msg="Received event: [{\"type\":\"ADDED\",\"Removed message
3.5.2016 10:34:36time="2016-05-03T08:34:36Z" level=info msg="Received event: [{\"type\":\"ADDED\",\"Removed message
3.5.2016 10:34:36time="2016-05-03T08:34:36Z" level=info msg="Received event: [{\"type\":\"ADDED\",\"Removed message
3.5.2016 10:34:36time="2016-05-03T08:34:36Z" level=info msg="Received event: [{\"type\":\"ADDED\",\"Removed message
3.5.2016 10:34:37time="2016-05-03T08:34:37Z" level=info msg="Received event: [{\"type\":\"ADDED\",\"Removed message
3.5.2016 10:34:37Request => GET http://master/api/v1/namespaces/default
3.5.2016 10:34:37Response <= {"kind":"Namespace","apiVersion":"v1","metadata":{"name":"default","selfLink":"/api/v1/namespaces/default","uid":"3b64560f-0c7a-11e6-b732-02fdcbea54e8","resourceVersion":"10207","creationTimestamp":"2016-04-27T13:16:20Z"},"spec":{"finalizers":["kubernetes"]},"status":{"phase":"Active"}}
3.5.2016 10:34:37
3.5.2016 10:34:37time="2016-05-03T08:34:37Z" level=info msg="Received event: [{\"type\":\"ADDED\",\"Removed message
3.5.2016 10:34:37Request => GET http://master/api/v1/namespaces/default
3.5.2016 10:34:37Response <= {"kind":"Namespace","apiVersion":"v1","metadata":{"name":"default","selfLink":"/api/v1/namespaces/default","uid":"3b64560f-0c7a-11e6-b732-02fdcbea54e8","resourceVersion":"10207","creationTimestamp":"2016-04-27T13:16:20Z"},"spec":{"finalizers":["kubernetes"]},"status":{"phase":"Active"}}
3.5.2016 10:34:37
3.5.2016 10:34:38time="2016-05-03T08:34:38Z" level=error msg="Kubernetes stream listener exited with error: Error reading from websocket for [ws://master/api/v1/namespaces?watch=true]: websocket: close 1000 "
3.5.2016 10:34:38time="2016-05-03T08:34:38Z" level=info msg=Exiting.
3.5.2016 10:35:06time="2016-05-03T08:35:06Z" level=info msg="Watching changes for kinds: [namespaces services replicationcontrollers pods]"
3.5.2016 10:35:06time="2016-05-03T08:35:06Z" level=info msg="Listening for health checks on 0.0.0.0:10240/healthcheck"
3.5.2016 10:35:06time="2016-05-03T08:35:06Z" level=info msg="Starting kubernetes event listener configuration: {KubernetesURL:http://master CattleURL:https://rancher-int.somecompany.com/v1 CattleAccessKey:COOLACCESSKEY CattleSecretKey:COOLSECRET WorkerCount:50 HealthCheckPort:10240}"
3.5.2016 10:35:06time="2016-05-03T08:35:06Z" level=info msg="Connecting to event stream." url="ws://master/api/v1/services?watch=true"
3.5.2016 10:35:06time="2016-05-03T08:35:06Z" level=info msg="Connecting to event stream." url="ws://master/api/v1/namespaces?watch=true"
3.5.2016 10:35:06time="2016-05-03T08:35:06Z" level=info msg="Received event: [{\"type\":\"ADDED\",\"Removed message
3.5.2016 10:35:06Request => GET http://master/api/v1/namespaces/default
3.5.2016 10:35:06time="2016-05-03T08:35:06Z" level=info msg="Connecting to event stream." url="ws://master/api/v1/services?watch=true"
3.5.2016 10:35:06time="2016-05-03T08:35:06Z" level=info msg="Received event: [{\"type\":\"ADDED\",\"Removed message
3.5.2016 10:35:06time="2016-05-03T08:35:06Z" level=info msg="Connecting to event stream." url="ws://master/api/v1/replicationcontrollers?watch=true"
3.5.2016 10:35:06time="2016-05-03T08:35:06Z" level=info msg="Received event: [{\"type\":\"ADDED\",\"Removed message
3.5.2016 10:35:06Response <= {"kind":"Namespace","apiVersion":"v1","metadata":{"name":"default","selfLink":"/api/v1/namespaces/default","uid":"3b64560f-0c7a-11e6-b732-02fdcbea54e8","resourceVersion":"10207","creationTimestamp":"2016-04-27T13:16:20Z"},"spec":{"finalizers":["kubernetes"]},"status":{"phase":"Active"}}
3.5.2016 10:35:06
3.5.2016 10:35:06time="2016-05-03T08:35:06Z" level=info msg="Connecting to event stream." url="ws://master/api/v1/pods?watch=true"
3.5.2016 10:35:06time="2016-05-03T08:35:06Z" level=info msg="Received event: [{\"type\":\"ADDED\",\"Removed message
3.5.2016 10:35:06time="2016-05-03T08:35:06Z" level=info msg="Received event: [{\"type\":\"ADDED\",\"Removed message
3.5.2016 10:35:06time="2016-05-03T08:35:06Z" level=info msg="Received event: [{\"type\":\"ADDED\",\"Removed message
3.5.2016 10:35:06time="2016-05-03T08:35:06Z" level=info msg="Received event: [{\"type\":\"ADDED\",\"Removed message
3.5.2016 10:35:06time="2016-05-03T08:35:06Z" level=info msg="Received event: [{\"type\":\"ADDED\",\"Removed message
3.5.2016 10:35:06time="2016-05-03T08:35:06Z" level=info msg="Initializing event router" workerCount=50
3.5.2016 10:35:06time="2016-05-03T08:35:06Z" level=info msg="Received event: [{\"type\":\"ADDED\",\"Removed message
3.5.2016 10:35:06time="2016-05-03T08:35:06Z" level=info msg="Received event: [{\"type\":\"ADDED\",\"Removed message
3.5.2016 10:35:06time="2016-05-03T08:35:06Z" level=info msg="Connection established"
3.5.2016 10:35:06time="2016-05-03T08:35:06Z" level=info msg="Received event: [{\"type\":\"ADDED\",\"Removed message
3.5.2016 10:35:06time="2016-05-03T08:35:06Z" level=info msg="Received event: [{\"type\":\"ADDED\",\"Removed message
3.5.2016 10:35:06time="2016-05-03T08:35:06Z" level=info msg="Received event: [{\"type\":\"ADDED\",\"Removed message
3.5.2016 10:35:06time="2016-05-03T08:35:06Z" level=info msg="Received event: [{\"type\":\"ADDED\",\"Removed message
3.5.2016 10:35:06Request => GET http://master/api/v1/namespaces/default
3.5.2016 10:35:06time="2016-05-03T08:35:06Z" level=info msg="Received event: [{\"type\":\"ADDED\",\"Removed message
3.5.2016 10:35:06Response <= {"kind":"Namespace","apiVersion":"v1","metadata":{"name":"default","selfLink":"/api/v1/namespaces/default","uid":"3b64560f-0c7a-11e6-b732-02fdcbea54e8","resourceVersion":"10207","creationTimestamp":"2016-04-27T13:16:20Z"},"spec":{"finalizers":["kubernetes"]},"status":{"phase":"Active"}}
3.5.2016 10:35:06
3.5.2016 10:35:07time="2016-05-03T08:35:07Z" level=info msg="Received event: [{\"type\":\"ADDED\",\"Removed message
3.5.2016 10:35:07Request => GET http://master/api/v1/namespaces/default
3.5.2016 10:35:07Response <= {"kind":"Namespace","apiVersion":"v1","metadata":{"name":"default","selfLink":"/api/v1/namespaces/default","uid":"3b64560f-0c7a-11e6-b732-02fdcbea54e8","resourceVersion":"10207","creationTimestamp":"2016-04-27T13:16:20Z"},"spec":{"finalizers":["kubernetes"]},"status":{"phase":"Active"}}
3.5.2016 10:35:07
3.5.2016 10:35:12time="2016-05-03T08:35:12Z" level=error msg="Kubernetes stream listener exited with error: Error reading from websocket for [ws://master/api/v1/pods?watch=true]: websocket: close 1000 "
3.5.2016 10:35:12time="2016-05-03T08:35:12Z" level=info msg=Exiting.
</pre>

**Comment by deniseschannon** [comment]
Where are your hosts located? In the Cloud (if so, what provider)? bare metal? 

When did this start happening? Immediately upon adding hosts or sometime later?

**Comment by tsupertramp** [comment]
The Hosts are created on AWS.
The Setup worked in the beginning. Three Node Setup.

I exchanged the etcd container through a etcd cluster (which seemed to work well and did not cause anything).
Then I exchanged two of three Nodes through an aws autoscaling group. I think it happened afterwards.

**Comment by tsupertramp** [comment]
Thought the Problem was caused through elb problems. Now i am running under 1.0.2 and the problem still exists. After some further research (now no more blinded by elb) i realized that i use a etcd cluster with version 2.2.3 but the kubernetes-agent image is tested with 2.0.9 https://github.com/rancher/kubernetes-agent/blob/671ad8021ad064592eb0301656bfe101c4040d32/scripts/test#L16 - Maybe this is the problem. I will try out with 2.0.9.

**Comment by tsupertramp** [comment]
Closing through problem is no more occuring in latest dev release
