### ISSUE TITLE
[BUG] No rancher v2.8.6 container

### ISSUE THREAD

**Issue by mjschmidt** [rancher/rancher#46562]
title says it all dockerhub is missing rancher's v2.8.6 release
https://hub.docker.com/r/rancher/rancher/tags?page=&page_size=&ordering=&name=2.8

**Comment by jcox10** [comment]
2.8.6 Prime version release (i.e. Paid)

**Comment by mallardduck** [comment]
@jcox10 is correct - that 2.8.6 (and subsequent 2.8.x releases) are Prime only builds. New community builds a found via the 2.9.x release line now after the recent release of 2.9.0.
