### ISSUE TITLE
[v2.9] [BUG] Fips errors on Rancher 2.9

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#46569]
Backport of https://github.com/rancher/rancher/issues/46486 to v2.9.x release line.

**Comment by macedogm** [comment]
PR https://github.com/rancher/rancher/pull/46575

**Comment by bgulla** [comment]
tested on rhel8 & rhel9, no issues.

**Comment by macedogm** [comment]
Closing based on this validation - https://github.com/rancher/rancher/issues/46486#issuecomment-2276205364.
