### ISSUE TITLE
[2.10] Update `ingress-nginx` to the latest applicable version

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#46565]
Currently, new RKE1 versions added to Rancher as part of monthly K8s patch releases references multiple (and outdated) versions of `nginx-ingress-controller`, for example versions [released](https://github.com/rancher/kontainer-driver-metadata/pull/1456) with July 2024 patches reference the following versions:
* `rancher/nginx-ingress-controller:nginx-1.9.4-rancher1`
* `rancher/nginx-ingress-controller:nginx-1.9.6-rancher1`
* `rancher/nginx-ingress-controller:nginx-1.10.1-rancher1`

Note the latest upstream version is currently is `v11.1` and it supports K8s 1.26-1.30 so at a glance seems to be applicable to all versions we currently support in Rancher 2.9.x (refer to https://github.com/kubernetes/ingress-nginx).

It's requested to update `nginx-ingress-controller` to latest applicable version available at the time we add next RKE1 patches.

This will help reduce CVE footprint as currently we ship multiple older versions that contain known CVEs that may be fixed in newer versions and this means the same CVE is counted multiple times in our CVE count tracking.

**Comment by rishabhmsra** [comment]
Validated on rancher v2.10-head:

- Provisioned v1.28.13-rancher1-1, v1.29.8-rancher1-1 and v1.30.4-rancher1-1 clusters.
- Validated ingress-nginx version and it's bumped to `rancher/nginx-ingress-controller:nginx-1.11.2-rancher1`
- Also created nginx deployment with svc clusterIp and port 80
- Created ingress pointing to it. 
- Access ingress and nginx welcome page is accessible.
