### ISSUE TITLE
Add in documentation of what could go in rancher-compose.yml

### ISSUE THREAD

**Issue by doo-gl** [rancher/rancher#4657]
Rancher Version:

Docker Version: 1.10.3

OS: CentOS

Steps to Reproduce: 
1. Start a rancher environment with at least one host
2. Get to the Add Stack menu in the web UI
3. Try use the following docker-compose.yml

```
winning-calculation-service_webserver:
  image: hello-world
```

Results: 
`Activating (Bad response statusCode [422]. Status [422 status code 422]. Body: [code=InvalidCharacters, fieldName=name] from [http://localhost:8080/v1/projects/1a12/services])`

Expected:
Rancher starts the hello world docker app

It appears that the underscore character is not a valid character for naming a service in Rancher.
It is a valid character in docker-compose however.

Also, it does not appear the Rancher supports version 2 of the docker compose file format.

Also also, is there a single place where the rancher-compose.yml file reference is stored?

**Comment by deniseschannon** [comment]
1. Yes, we don't support the `_` as the name needs to be compatible with our [internal DNS](http://docs.rancher.com/rancher/latest/en/rancher-services/internal-dns-service/). 

2. Yes, there is an issue for v2 support. https://github.com/rancher/rancher/issues/3973

3. I'm not exactly sure what you mean by ", is there a single place where the rancher-compose.yml file reference is stored?" Are you looking for documentation on what could be included in it? Are you looking for where you could see it in the UI?

**Comment by doo-gl** [comment]
Hi Denise,

Thank you for the clarification on the underscore character, that makes sense.
I'm also happy to see there is a ticket to look at using version 2 syntax of docker compose.

What I meant by looking for a single place for the rancher-compose.yml reference is I was wanting to know a little more on what is possible to put into a rancher-compose.yml.

For example, on the docker-compose site the there is a very useful [page](https://docs.docker.com/compose/compose-file/) which outlines all the possible values that can be put into a docker-compose.yml along with some explanation as to what they are used for.

I was wondering if there was a similar page that went through all the values that can be placed in a rancher-compose.yml, on one page, with a bit of explanation as to what each value means and what it does?

**Comment by deniseschannon** [comment]
@doo-gl Currently, we don't have a section in the docs that lists out all the items that could go in `rancher-compose.yml`, but that's a great suggestion. I'll change this issue to be that one.

**Comment by guzmo** [comment]
This is greatly missed :)

**Comment by mattdodge** [comment]
For reference, I did some digging and found this schema file which might be a little helpful.

https://github.com/rancher/rancher-compose-executor/blob/master/config/schema.go

**Comment by msansen** [comment]
the schema file was moved, here's the new location 
https://github.com/rancher/rancher-compose-executor/blob/master/parser/schema.go

as json.. : 
https://github.com/rancher/rancher-compose-executor/blob/master/scripts/config_schema_v1.json
https://github.com/rancher/rancher-compose-executor/blob/master/scripts/config_schema_v2.0.json

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

**Comment by anjmao** [comment]
@deniseschannon Hi, this issue should be reopened as it is not related to v1.6. This is general issue that there is no rancher-compose.yml documentation.
