### ISSUE TITLE
[v2.8] [BUG] Fips errors on Rancher 2.9

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#46570]
Backport of https://github.com/rancher/rancher/issues/46486 to v2.8.x release line.

**Comment by macedogm** [comment]
PR is https://github.com/rancher/rancher/pull/46597.

**Comment by macedogm** [comment]
@susesgartner can you please test the v2.8-head image to see if the FIPS will be correctly enabled? We migrated the Agent image to BCI Micro and added the missing FIPS packages, so the same failure behavior that was happening with v2.9 should be fixed now. Thanks!

**Comment by susesgartner** [comment]
Ticket #46486 - Test Results - ✅ 
---

| Scenario | Test Case | Result |
|---|---|---|
| 1. | Enable Fips on a downstream cluster (HA Rancher Setup)  | PASS |
| 2. | Provision a cluster with FIPs enabled (HA Rancher Setup) | PASS |
---
Verified with (HA Helm or Docker) on Rancher `v2.8-head`:
---
Scenario 1: Enable Fips on a downstream cluster (HA Rancher Setup)
---

1. Create a 3 node shared roles rke2 cluster.
2. Wait for the cluster to become active
3. SSH into each node and enable fips
4. Wait for the cluster to update
5. Verify that all pods are in a stable state.
 
Results: All pods remain in a stable state and no crash is observed
 
---

Scenario 2:  Provision a cluster with FIPs enabled (HA Rancher Setup)
---

1. Create a 3 node shared roles rke2 cluster with FIPs enabled on the image used.
2. Wait for cluster to provision
3. Verify that the cluster comes up active and all pods are in a normal state

 
Results: The cluster provisions and all pods are in a normal state.
