### ISSUE TITLE
Load Balancer - version conflict after upgrading rancher server.

### ISSUE THREAD

**Issue by swaroopkundeti** [rancher/rancher#4658]
Rancher Version: 1.0.1
Old version : 0.59.0 
 
Docker Version: 1.9

OS: Ubuntu 14.04

Steps to Reproduce: Not sure

Results: Load balancer unable to spin up on new hosts after upgraded

Expected: load balancer should spin up and added to service stack

We have a rancher-server with 10 hosts running around 250 containers. We faced lots of issues with UI as heap dump and saw in one of the post that heap dump is fixed in version 1.0.1 so we upgraded rancherserver to 1.0.1. Performance has definitely improved but having problems with load balancer.

We have a load balancer and runs each container on each host and has hostname based routing. 

After upgrade when we add new host it spins up agent v0.8.1 but we have hosts which has version 0.8.0. Below is the error I see

<pre>
 Degraded (Waiting for [instance:Default_rancher-lb_1]. Instance status: 500 Server Error: Internal Server Error ("Cannot start container 58fd1a41f3121143d3e5ce41a9706b15ee820f55c233980101af47f9eb93192e: [9] System error: argument list too long"))
Type:
</pre>
![selection_001](https://cloud.githubusercontent.com/assets/4454285/14991106/c998f28e-112d-11e6-8839-553716ce1127.png)

**Comment by swaroopkundeti** [comment]
Anything on this?

**Comment by deniseschannon** [comment]
The different versions of the Load balancer shouldn't matter as we always upgrade the internal software inside the rancher/agent-instance containers, which are the load balancer containers. 

Could you share your docker-compose.yml of the load balancer?

**Comment by swaroopkundeti** [comment]
@deniseschannon I'm unable to generate docker-compose file from stack. Its a load balancer service added from UI to run one container on each host. Now we have 30 hosts 700 containers, load balancer server stopped creating lb containers on newly added hosts. if you can see above image load balancer stopped right there. its not going forward.

**Comment by deniseschannon** [comment]
In the UI, you should be able to click on the stack and then click on View Config of the Stack. Does that not work for you?

**Comment by deniseschannon** [comment]
@swaroopkundeti If you are still having issues and are able to share your docker-compose.yml of your load balacner (from the stack view), please provide it and re-open.
