### ISSUE TITLE
[BUG] RKE1 agents provisionning fails when AWS IMDSv2 is set to required

### ISSUE THREAD

**Issue by tchebe** [rancher/rancher#46582]
**Rancher Server Setup**
- Rancher version: v2.8.4
- Installation option (Docker install/Helm Chart): Helm chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): k3s
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: 1.28.12
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Custom

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Cluster Owner

**Describe the bug**

When provisionning a new custom RKE1 cluster or adding new agents to existing RKE1 cluster using EC2 existing instances with IMDSv2 set to required, rancher agent is not able to retrieve instance metadata.

**To Reproduce**

- Create EC2 instance(s) with IMDSv2 required and set hop limit to 2
- Execute the registration command on the created instance(s)

**Result**
Hostname is ip-xx-xx-xx-xx 
Node name is ip-xx-xx-xx-xx

**Expected Result**

Hostname should be ip-xxx-xxx-xxx-xxx.\<region\>.compute.internal
Node name should be ip-xxx-xxx-xxx-xxx.\<region\>.compute.internal

**Screenshots**

**Additional context**

https://github.com/rancher/rke-tools/blob/master/entrypoint.sh#L25
rke-tools should get a token before trying to get the instance metadata as documented here https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-metadata-v2-how-it-works.html

**Comment by vivek-shilimkar** [comment]
Tested the issue on Rancher v2.9-head and k8s v1.30.

Custom cluster creation with IMDSv2 set to required on an AWS instance is successful. 

Hence the ticket can be closed.
