### ISSUE TITLE
Add ELB as an external load balancer

### ISSUE THREAD

**Issue by will-chan** [rancher/rancher#4659]
Very similar to #4445, add ELB as an external load balancer to Rancher.

**Comment by andrewmclagan** [comment]
Oh man this will be GREAT!!

**Comment by schuylr** [comment]
I would drop Amazon ECS in a heartbeat for this!

**Comment by will-chan** [comment]
We are working on this and should have something soon after 1.1 goes GA.

**Comment by andrewmclagan** [comment]
Woo!

**Comment by mikesir87** [comment]
I see that this was given the 1.2-feature. Does that mean it's part of the 1.2 roadmap, or will be released between 1.1 and 1.2?  Any way I might be able to help, either in code or testing?

As mentioned by others... this would totally change how we're deploying apps (which we're setting up a new deployment within the next few weeks).

**Comment by schuylr** [comment]
This is now somewhat related to #5959

**Comment by raymatos** [comment]
I dont see this in the catalog.  How can i start testing this?

**Comment by janeczku** [comment]
https://github.com/rancher/community-catalog/pull/309

@galal-hussein 
Template depends on `rancher/external-lb:v0.2.1`. I'll let you know when the image is pushed to Docker Hub. You can then validate the "ELB Classic Load Balancer" template from this catalog: https://github.com/janeczku/elbv2-catalog

**Comment by galal-hussein** [comment]
@janeczku Tested and worked on Rancher master image.

**Comment by galal-hussein** [comment]
Merged https://github.com/rancher/community-catalog/pull/309
