### ISSUE TITLE
[RFE] Monitor the logging stack

### ISSUE THREAD

**Issue by jbiers** [rancher/rancher#46591]
**Is your feature request related to a problem? Please describe.**
When having both the monitoring and logging stacks installed in a cluster, there should be an option to monitor the status of the logging components.

**Describe the solution you'd like**

**Additional context**
Suggested in internal issue SURE-3896

**Comment by pankajsqe** [comment]
Test Pass : When both Monitoring v2 and Logging v2 are installed in Rancher AND fluentd/fluentbit have their servicemonitors enabled then automatically two specific grafana dashboard added to monitor fluentd/fluentbit. PFA
(Regression Test Passed As Well)   

**Details** 
Rancher : v2.10-head 
Cluster : v1.30.2+k3s2 
Monitoring : 105.1.0-rc1+up61.3.2  
Enable 	
```
loggingMonitors.fluentd=true
		
loggingMonitors.fluentbit=true
```

Logging :  105.0.0-rc1+up4.8.0 
Enable
```
fluentd.metrics.prometheusRules =true   		
fluentd.metrics.serviceMonitor =true 
fluentbit.metrics.prometheusRules =true       
fluentbit.metrics:serviceMonitor=true
```
Two new prometheus rules gets added to monitoring prometheus rules under cattle-logging-system namespace. 

- rancher-logging-root-fluentbit-monitor
- rancher-logging-root-fluentd-metrics


![Image](https://github.com/user-attachments/assets/906e305e-9eda-4278-a563-f23d208d4285)



Two new grafana dashboard gets added 

- Rancher / Fluentbit
- Rancher / Fluentd


![Image](https://github.com/user-attachments/assets/2b3da6c0-fc8d-42d0-adc2-f665b55c539c)
![Image](https://github.com/user-attachments/assets/7dc30d4f-3c30-465b-83ec-0fa5600c3539)
