### ISSUE TITLE
Scale won't change if Service is in activating state

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4660]
Version - v1.1.0-dev1

Steps to Reproduce: 
1.  Create a Load Balancer that has port set to 80, and a scale of 2.  Have only 1 host available
2.  While Service is in activating state and looking for available port (because it can't find one), change scale to 1 from i screen or from detail screen.  Now go out and come back into info screen or detail screen.

Results: Scale is reset back to 2

Expected: Scale should set to 1

**Comment by vincent99** [comment]
This should work in 2.0

**Comment by tfiduccia** [comment]
version - master 9/19
Verified fixed
