### ISSUE TITLE
`pnap` (PhoenixNAP) node driver update to version 0.5.1

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#46601]
Update built-in version of built-in `pnap` node driver to version 0.5.1.

**Comment by markusewalker** [comment]
Validated that `v2.10-head` https://github.com/rancher/rancher/commit/a50a71479241fa02a3e31f8e2b9a73010264b140. See details:

**ENVIRONMENT DETAILS**
- Rancher install: Helm
- Rancher version: `v2.10-head` https://github.com/rancher/rancher/commit/a50a71479241fa02a3e31f8e2b9a73010264b140

**TEST RESULT**
|#|Scenario|Test Result|
|---|---|---|
|1|Validated that PhoenixNAP version is now set to `0.5.1`|:white_check_mark:|

Please note that as we do not have access to node driver credentials, so QA has simply validated that the node driver has been bumped. We did not provision a cluster with this node driver.
