### ISSUE TITLE
[v2.9] Bump rke-tools for rke1 k8s august 2024 patches 

### ISSUE THREAD

**Issue by vardhaman22** [rancher/rancher#46616]
rke-tools has several dependency bumped after july patch release so august patches needs to be updated with the newer version.

**Comment by vivek-shilimkar** [comment]
Validated RKE tools version on k8s v1.30.4, v1.29.8 and v1.28.13. 
Correct image version (0.1.102) is being used on all these versions.

Hence closing this ticket.
