### ISSUE TITLE
[Backport] [v2.8] Bump rke-tools for rke1 k8s august 2024 patches

### ISSUE THREAD

**Issue by vardhaman22** [rancher/rancher#46617]
backport for issue: https://github.com/rancher/rancher/issues/46616

**Comment by rishabhmsra** [comment]
Validated on rancher v2.8-head

Case 1 : 
- Provisioned RKE1 node driver v1.28.13-rancher1-1 k8s cluster(2-cp, 3-e, 3-w).
- Validated rke-tools version `rancher/rke-tools:v0.1.102`
- Created w1 and ing1.
- Created backup b1
- Created w2 and ing2.
- Created b2
- Restored to b1
- Validated that w2 and ing2 no longer present on cluster.

Case 2 : 
- Provisioned RKE1 node driver v1.27.16-rancher1-1 k8s cluster(2-cp, 3-e, 3-w).
- Validated rke-tools version `rancher/rke-tools:v0.1.102`
- Created w1 and ing1.
- Created backup b1
- Upgrade cluster to v1.28.13-rancher1-1.
- Created w2 and ing2.
- Created b2
- Restored to b1
- Validated that w2 and ing2 no longer present on cluster and k8s version is rolled back to v1.27.16-rancher1-1.
