### ISSUE TITLE
[BUG] system-agent does not respect `maxFailures` if running the same plan post restart

### ISSUE THREAD

**Issue by HarrisonWAffel** [rancher/rancher#46620]
**Rancher Server Setup**
- Rancher version: n/a. Tested latest version of the system-agent, v0.3.7
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details: n/a

**Information about the Cluster**
- Kubernetes version: n/a
- Cluster Type (Local/Downstream): n/a
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): n/a

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: n/a

**Describe the bug**

The system-agent will fail to run a plan multiple times if that plan had previously succeeded, has the same contents, and is configured with a `maxFailures` setting >1.

For example, Rancher will deliver a one-time-plan to the system-agent each time that a node connects to a cluster. This plan invokes the `system-agent-installer-rke2` in order to install or update `rke2` on the node as needed. This will happen on initial registration, as well as after a reboot of the node. In the event that this plan has a `maxFailures` value greater than zero, that value will only be respected the first time that the system agent applies the plan, but not on subsequent applications post reboot.

This is due to the `appliedChecksumKey` not being cleared after the system-agent restarts. The system-agent will always apply the plan [at least once after it restarts](https://github.com/rancher/system-agent/blob/ae76dcf50a17c66c89b2e1e3308e93eb1c8c6804/pkg/k8splan/watcher.go#L214-L218). However, if the content of the plan has not changed, then the system-agent will compute the same checksum that is stored in the `appliedChecksumKey` field. This results in the system agent [skipping further applications of the plan](https://github.com/rancher/system-agent/blob/ae76dcf50a17c66c89b2e1e3308e93eb1c8c6804/pkg/k8splan/watcher.go#L205-L212) as it thinks the plan has already been successfully applied, even if the most recent application has failed. 

This was discovered while investigating how to better handle https://github.com/rancher/rancher/issues/42458 in the planner. In some situations for Windows nodes, the `system-agent-installer-rke2` plan may fail to properly execute post reboot. Ideally, the planner would attempt to retry this plan multiple times before marking it as 'failed', as the initial failure may be transient. 

**To Reproduce**
Reproducing this issue while executing the `system-agent-installer-rke2` plan is difficult to do, as linux nodes reliably execute this plan and Rancher is hard coded to set the `maxFailures` count to `1`. This is more easily reproduced in the context of https://github.com/rancher/rancher/issues/42458. The planner would need to be updated to set a `maxFailure` and `failureThreshold` value of >1 for worker plans, and a Windows worker would need to be provisioned on vSphere. 

**Result**
In the event that the one-time-plan application fails post reboot, the `maxFailures` property will not be respected

**Expected Result**
The plan is reapplied up to either the `maxFailures` or `failureThreshold` values configured for that plan, even if that plan has previously been successfully applied.

**Screenshots**

**Additional context**

**Comment by markusewalker** [comment]
Validated this against `head` https://github.com/rancher/rancher/commit/891b100f6c4873c7d8a7dca329a5854c1ba3763a. The test results have been recorded in Qase test run /RM 2592. The below test scenarios were tested:

**ENVIRONMENT DETAILS**
- Rancher install: Helm
- Rancher version: 
     - Fresh install: `head` https://github.com/rancher/rancher/commit/688f1aff0eda9da28d88fc0167b8ae95378b9575
     - Upgrade: `v2.9.2` -> `head` https://github.com/rancher/rancher/commit/891b100f6c4873c7d8a7dca329a5854c1ba3763a

**TEST RESULT**
|#|Scenario|Result|
|---|---|---|
|1|[Fresh install] Perform graceful restart guest OS on Windows nodes in downstream node driver cluster|:white_check_mark:|
|2|[Fresh install] Replace Windows nodes and perform graceful restart guest OS|:white_check_mark:|
|3|[Upgraded Rancher] Perform graceful restart guest OS on Windows nodes in downstream node driver cluster|:white_check_mark:|
|4|[Upgraded Rancher] Replace Windows nodes and perform graceful restart guest OS|:white_check_mark:|
|5|[Upgraded] Rancher] Add Windows node to pre-existing cluster post-upgrade|:white_check_mark:|
