### ISSUE TITLE
Kube-system page has Services for title

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4662]
Version - v1.1.0-dev1

Steps to Reproduce: 
1.  Create a kubernetes environment & add hosts
2.  Under Namespace, select kube-system

Results: The page title says Services

Expected: Page title should be System or kube-system.  Services is confusing because it looks like we have two services pages with different services on them.

**Comment by tfiduccia** [comment]
Version - 5-24
Fine

**Comment by vincent99** [comment]
`kube-system`is just the name of a special namespace that things are sometimes put into, but that we have to list separately because it doesn't come back in the list of namespaces.  What you're seeing is still Services (or Pods, or RCs) in that namespace
