### ISSUE TITLE
[BUG] [v2.9] cattle-cluster-agent missing linux image resulting in incomplete provisioning of hosted downstream clusters

### ISSUE THREAD

**Issue by cpinjani** [rancher/rancher#46639]
**Rancher Server Setup**
- Rancher version: `v2.9-96046bb3e10d5e3ef92fcf4859f66610ff521c7e-head`
- Installation option: Docker install

**Information about the Cluster**
- Kubernetes version: v1.30
- Cluster Type (Downstream):
- Hosted = EKS, GKE, AKS

**User Information**
- What is the role of the user logged in? Admin

**Describe the bug**
cattle-cluster-agent image for linux is missing on v2.9-head, which results in agent not getting deployed on downstream clusters

Cluster agent pod events:
```
Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  6m28s                  default-scheduler  Successfully assigned cattle-system/cattle-cluster-agent-699b8fd6c5-n76vp to gke-cpinjani-gke1-group-1-dbbc3860-4kjb
  Normal   Pulling    4m57s (x4 over 6m27s)  kubelet            Pulling image "rancher/rancher-agent:v2.9-96046bb3e10d5e3ef92fcf4859f66610ff521c7e-head"
  Warning  Failed     4m57s (x4 over 6m20s)  kubelet            Failed to pull image "rancher/rancher-agent:v2.9-96046bb3e10d5e3ef92fcf4859f66610ff521c7e-head": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/rancher/rancher-agent:v2.9-96046bb3e10d5e3ef92fcf4859f66610ff521c7e-head": no match for platform in manifest: not found
  Warning  Failed     4m57s (x4 over 6m20s)  kubelet            Error: ErrImagePull
  Warning  Failed     4m31s (x6 over 6m19s)  kubelet            Error: ImagePullBackOff
  Normal   BackOff    79s (x20 over 6m19s)   kubelet            Back-off pulling image "rancher/rancher-agent:v2.9-96046bb3e10d5e3ef92fcf4859f66610ff521c7e-head"

```

**To Reproduce**
Provision/Import hosted downstream cluster

**Expected Result**
Provisioning of hosted downstream clusters should complete with agent getting deployed

**Additional context**
Seems last head build with proper images was `v2.9-416e5c404537f6c953dac9a537fa99d15221589a-head`

**Comment by kkaempf** [comment]
should be fixed now 🤞🏻

**Comment by snasovich** [comment]
This should now be fixed, successful build - https://github.com/rancher/rancher/actions/runs/10355637420

**Comment by cpinjani** [comment]
Build: `v2.9-92f15949d71efb11baf63c878cc2f64bcd25b1e8-head`, Validation passed :white_check_mark: 
Cluster agent getting deployed on downstream clusters.

![image](https://github.com/user-attachments/assets/89f7f9bb-4ee0-4e69-989e-7d7445515f00)
