### ISSUE TITLE
Switching to kubernetes environment goes to waiting even if services are created

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4663]
Version - master 5/3 

Steps to Reproduce: 
1.  Create kubernetes environment and fully set it up
2.  Go to cattle environment then switch back to kubernetes environment

Results: Goes to waiting page

Expected: Shouldn't go to waiting page

**Comment by aboyett** [comment]
This sounds the same situation as #4615. Are you seeing a HTTP 503 from /r/kubernetes/api in your browser on that page?

**Comment by tfiduccia** [comment]
Version - v1.2.0-pre3
No longer able to reproduce this problem.
