### ISSUE TITLE
SQLite backed cache: Request for additional indexed fields

### ISSUE THREAD

**Issue by richard-cox** [rancher/rancher#46642]
- management.cattle.io.nodepool
  - spec.clusterName
- management.cattle.io.nodetemplate
  - spec.clusterName 
- cluster.x-k8s.io.machine
  - spec.clusterName 
- provisioning.cattle.io.cluster
  - metadata.labels."provider.cattle.io"
  - status.provider 
  - status.allocatable.cpu
  - status.allocatable.memory
  - status.allocatable.pods

**Comment by richard-cox** [comment]
Update: Additional requests

Event
- _type
- reason (to discuss, for speed / size reasons this could be dropped)
- involvedObject.kind
- message  (to discuss, for speed / size reasons this could be dropped)

**Comment by moio** [comment]
@richard-cox is this blocking you in any way?

**Comment by richard-cox** [comment]
There's a couple of PR's that are blocked, but i don't think they would be merged any time soon.

**Comment by richard-cox** [comment]
Update: Additional Requests

- catalog.cattle.io.clusterrepo
  - spec.gitRepo
  - spec.gitBranch
- catalog.cattle.io.operation
  - status.action
  - status.namespace
  - status.releaseName

**Comment by ericpromislow** [comment]
I don't know if we currently have a way to access `{"status", "conditions", "reason"}` for `management.cattle.io.nodes` because `conditions` is an array, and the cache mechanism doesn't currently handle them.

**Comment by ericpromislow** [comment]
## Validation Template

I did my testing against the `steve` binary (running Rancher Desktop to provide a k8s 1.9 backend)

1. Sample event file (`my-event.yaml`):
```
apiVersion: v1
kind: Event
metadata:
  name: my-custom-event3
  namespace: default
involvedObject:
  apiVersion: v1
  kind: Pod
  name: my-pod
  namespace: default
reason: CustomEventGenerated
message: "This event #1."
type: MyCustomEventType
count: 1
source:
  component: my-custom-source
```

2. Add the event to kubernetes:
```
kubectl -f apply my-event.yaml
```

### Building steve

3. Ensure you can pull down the source that includes the commit for 
`Index more sqlite cache fields (#271)`

```
cd ..../steve
git checkout main
bash scripts/build-bin.sh 
```

4. First run steve without sqlite caching:
```
./bin/steve  --https-listen-port 9443 --http-listen-port 9080 --debug
```

5. Verify that the event doesn't show up when filtering for it:
```
$ curl -sk https://localhost:9443/v1/events?filter=_type=MyCustomEventType" | jq .  
{
  "type": "collection",
  "links": {
    "self": "https://localhost:9443/v1/events"
  },
  "createTypes": {
    "event": "https://localhost:9443/v1/events"
  },
  "actions": {},
  "resourceType": "event",
  "revision": "17642",
  "data": []
}
```

6. Now run steve with sqlite caching:
```
./bin/steve  --https-listen-port 9443 --http-listen-port 9080 --debug --sql-cache
```

In another terminal session:
```
curl -sk https://localhost:9443/v1/events?filter=_type=MyCustomEventType | jq . | vim -
```

And you should see the full YAML for the custom event.

## What about testing this in the Rancher UI?

I haven't done that, but if you can do it, you should test sqlite-caching with a field called `type`,
not `_type`, and Steve should do the conversion from `type` to `_type`.

**Comment by brudnak** [comment]
<details>
    <summary>🧪 Test Environment... CLICK TO EXPAND! ⬅️</summary>


| Component                        | Version / Type                                                                     |
| -------------------------------- | ---------------------------------------------------------------------------------- |
| Rancher version starting         | 2.9.2                                                                              |
| Rancher version upgraded         | v2.10-73a22a6ad6aca91f7817e3507b3b99dc44813cb0-head                                |
| Rancher commit link              | https://github.com/rancher/rancher/commit/73a22a6ad6aca91f7817e3507b3b99dc44813cb0 |
| Installation option              | Helm (high availability)                                                           |
| RKE binary version used          | v1.6.2                                                                             |
| If Helm Chart k8s cluster        | v1.30.4                                                                            |
| Cert Details                     | external tls `aws acm`                                                             |
| Docker version                   | 20.10.7, build f0df350                                                             |
| Helm version                     | v2.16.8-rancher2                                                                   |
| Downstream cluster type          | not applicable                                                                     |
| Downstream K8s version           | not applicable                                                                     |
| Authentication providers enabled | local                                                                              |
| Logged in user role              | admin                                                                              |
| Browser type                     | Opera GX                                                                           |
| Browser version                  | LVL6 (core: 114.0.5282.93) (arm64)                                                 |
| Dashboard                        | master fa2e6dd                                                                     |
| Webhook version                  | rancher/rancher-webhook:v0.6.1-rc.5                                                |

<br>

</details>


<a name="top"></a>

### 🧪 Test Cases

| \#  | Priority | Description & Link                                    | PASS/FAIL |
| --- | -------- | ----------------------------------------------------- | --------- |
| 1   | P0       | [(Regression Check) Steve Validation Tests](#test-1)  | ✅ `PASS`  |
| 2   | P0       | [(Regression Check) Steve Integration Tests](#test-2) | ✅ `PASS`  |
| 3   | P0       | [`v1/catalog.cattle.io.clusterrepo` Filter](#test-3)  | ✅ `PASS`  |
| 4   | P0       | [`v1/catalog.cattle.io.clusterrepo` Sort](#test-4)    | ✅ `PASS`  |
| 5   | P0       | [`/v1/events` `_type` Filter](#test-5)                | ✅ `PASS`  |
| 6   | P0       | [`/v1/events` `_type` Sort](#test-6)                  | ✅ `PASS`  |
| 7   | P0       | [Upgrade](#test-7)                                    | ✅ `PASS`  |


<details>
    <summary>🚨 7 test cases... CLICK TO EXPAND! (For table links to work) ⬅️</summary>

<br>

# 1 / (Regression Check) Steve Validation Tests Status: ✅ `PASS`

<a name="test-1"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 1 details... Click to expand</summary>

**Test Steps for Validation**

1. Run automated validation tests to ensure no regressions


**✅ Expected Outcome**

Regression checks should pass

**✅ Actual Outcome**

Regression checks passing

</details>
<hr>

# 2 / (Regression Check) Steve Integration Tests Status: ✅ `PASS`

<a name="test-2"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 2 details... Click to expand</summary>

**Test Steps for Validation**

1. Run automated integration tests to ensure no regressions


**✅ Expected Outcome**

Regression checks should pass

**✅ Actual Outcome**

Regression checks passing


</details>
<hr>

# 3 / `v1/catalog.cattle.io.clusterrepo` Filter Status: ✅ `PASS`

<a name="test-3"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 3 details... Click to expand</summary>

**Test Steps for Validation**

1. Start a Rancher server with a version with these changes
2. Create an admin token
3. Make a `GET` request to `{{rancherURL}}/v1/catalog.cattle.io.clusterrepo?filter=spec.gitBranch=main`
4. Expect 2 items returned
    - `rancher-partner-charts`
    - `rancher-rke2-charts`
6. These were successfully returned
7. Make a `GET` request to `{{rancherURL}}/v1/catalog.cattle.io.clusterrepo?filter=spec.gitRepo=https://git.rancher.io/partner-charts`
8. Expect 1 item returned
   - `rancher-partner-charts`
9. Make a `POST` request to `{{rancherURL}}/v1/catalog.cattle.io.clusterrepo` with the following body:

    ```json
    {
      "type": "catalog.cattle.io.clusterrepo",
      "metadata": {
        "name": "testing123"
      },
      "spec": {
        "clientSecret": null,
        "gitRepo": "https://github.com/brudnak/linode-ubuntu-setup-dadfish.git",
        "gitBranch": "filterTest"
      }
    }
    ```

10. Expected a `201` response
11. Received that `201` response
12. Filter on that with a `GET` to `{{rancherURL}}/v1/catalog.cattle.io.clusterrepo?filter=spec.gitBranch=filterTest`
13. Expect to received 1 item back
    - Received back: `testing123` as expected
14. Delete that cluster repo with a `DELETE` to `{{rancherURL}}/v1/catalog.cattle.io.clusterrepo/testing123`

**✅ Expected Outcome**

Receive expected filtered results

**✅ Actual Outcome**

Received the expected filtered results

</details>
<hr>

# 4 / `v1/catalog.cattle.io.clusterrepo` Sort Status: ✅ `PASS`

<a name="test-4"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 4 details... Click to expand</summary>

**Test Steps for Validation**

1. Start a Rancher server with a version with these changes
2. Create an admin token
3. Make a `POST` request to `{{rancherURL}}/v1/catalog.cattle.io.clusterrepo` with the following body:

    ```json
    {
      "type": "catalog.cattle.io.clusterrepo",
      "metadata": {
        "name": "filter-test"
      },
      "spec": {
        "clientSecret": null,
        "gitRepo": "https://github.com/brudnak/linode-ubuntu-setup-dadfish.git",
        "gitBranch": "filterTest"
      }
    }
    ```
4. Make a `POST` request to `{{rancherURL}}/v1/catalog.cattle.io.clusterrepo` with the following body:

    ```json
    {
      "type": "catalog.cattle.io.clusterrepo",
      "metadata": {
        "name": "dadfish"
      },
      "spec": {
        "clientSecret": null,
        "gitRepo": "https://github.com/brudnak/linode-ubuntu-setup-dadfish.git",
        "gitBranch": "dadfish"
      }
    }
    ```
5. Make a `POST` request to `{{rancherURL}}/v1/catalog.cattle.io.clusterrepo` with the following body:

    ```json
    {
      "type": "catalog.cattle.io.clusterrepo",
      "metadata": {
        "name": "filter-test5"
      },
      "spec": {
        "clientSecret": null,
        "gitRepo": "https://github.com/brudnak/linode-ubuntu-setup-dadfish.git",
        "gitBranch": "filterTest5"
      }
    }
    ```

6. Make a `POST` request to `{{rancherURL}}/v1/catalog.cattle.io.clusterrepo` with the following body:

    ```json
    {
      "type": "catalog.cattle.io.clusterrepo",
      "metadata": {
        "name": "filter-test6"
      },
      "spec": {
        "clientSecret": null,
        "gitRepo": "https://github.com/brudnak/linode-ubuntu-setup-dadfish.git",
        "gitBranch": "filterTest6"
      }
    }
    ```

7. Sort these with the following `GET` to `{{rancherURL}}/v1/catalog.cattle.io.clusterrepo?filter=spec.gitBranch=filterTest5,spec.gitBranch=filterTest6&sort=spec.gitBranch`
8. Expecting 2 results in this order:
   1. `filter-test5`
   2. `filter-test6`
9. Now sort with the following `GET` to `{{rancherURL}}/v1/catalog.cattle.io.clusterrepo?filter=spec.gitBranch=filterTest5,spec.gitBranch=filterTest6&sort=-spec.gitBranch`
10. Expecting 2 results in this order:
   1. `filter-test6`
   2. `filter-test5`
11. NOTE: the difference between these two `GET`'s is `&sort=spec` vs `&sort=-spec` with the `-` before `spec`


**✅ Expected Outcome**


Expect sorting to function as expected

**✅ Actual Outcome**

Sorting working as expected

</details>
<hr>

# 5 / `/v1/events` `_type` Filter Status: ✅ `PASS`

<a name="test-5"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 5 details... Click to expand</summary>

**Test Steps for Validation**

1. Run the following script with `./script.sh 10`:

    ```sh
    #!/bin/bash

    if [ $# -ne 1 ]; then
        echo "Usage: $0 <number_of_types>"
        exit 1
    fi

    number_of_types=$1

    for i in $(seq 1 $number_of_types); do
        cat <<EOF | kubectl apply -f -
    apiVersion: v1
    kind: Event
    metadata:
      name: my-custom-event$i
      namespace: default
    involvedObject:
      apiVersion: v1
      kind: Pod
      name: my-pod
      namespace: default
    reason: CustomEventGenerated
    message: "This event #$i."
    type: MyCustomEventType$i
    count: 1
    source:
      component: my-custom-source
    EOF
        echo "Created custom event type $i"
    done
    ```

2. Then run the following `GET` >>> `{{rancherURL}}/v1/events?filter=_type=MyCustomEventType7,_type=MyCustomEventType8`
3. Expecting 2 results:
   - `myCustomEventType7`
   - `myCustomEventType8`
4. Received only these 2 event `_type` as expected

**✅ Expected Outcome**

To be able to filter by `_type` successfully

**✅ Actual Outcome**

Was able to successfully filter by `_type`


</details>
<hr>

# 6 / `/v1/events` `_type` Sort Status: ✅ `PASS`

<a name="test-6"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 6 details... Click to expand</summary>

**Test Steps for Validation**


    ```sh
    #!/bin/bash

    if [ $# -ne 1 ]; then
        echo "Usage: $0 <number_of_types>"
        exit 1
    fi

    number_of_types=$1

    for i in $(seq 1 $number_of_types); do
        cat <<EOF | kubectl apply -f -
    apiVersion: v1
    kind: Event
    metadata:
      name: my-custom-event$i
      namespace: default
    involvedObject:
      apiVersion: v1
      kind: Pod
      name: my-pod
      namespace: default
    reason: CustomEventGenerated
    message: "This event #$i."
    type: MyCustomEventType$i
    count: 1
    source:
      component: my-custom-source
    EOF
        echo "Created custom event type $i"
    done
    ```

1. Then run the following `GET` >>> `{{rancherURL}}/v1/events?filter=_type=MyCustomEventType7,_type=MyCustomEventType8&sort=_type`
2. Expect 2 results in the following order:
   1. `MyCustomEventType7`
   2. `MyCustomEventType8`
3. Now run the following `GET` >>> `{{rancherURL}}/v1/events?filter=_type=MyCustomEventType7,_type=MyCustomEventType8&sort=-_type`
4. NOTE: the difference between these two `GET`'s is `&sort=_type` vs `&sort=-_type` with the `-` before `_type`
5. Expect 2 results in the following order:
   1. `MyCustomEventType8`
   2. `MyCustomEventType7`

**✅ Expected Outcome**

Sort to work with `_type` as expected

**✅ Actual Outcome**

Sort working with `_type` as expected

</details>
<hr>





# 7 / Upgrade Status: ✅ `PASS`

<a name="test-7"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 7 details... Click to expand</summary>

**Test Steps for Validation**

1. Start with a Rancher version previous to this release
2. Upgrade Rancher to this version
3. Re-run all test cases against an upgrade Rancher

**✅ Expected Outcome**

Test cases should pass on an upgraded setup

**✅ Actual Outcome**

Tests passing on an upgraded setup


</details>
<hr>

</details>

**Comment by brudnak** [comment]
<details>
    <summary>🧪 Test Environment... CLICK TO EXPAND! ⬅️</summary>


| Component                        | Version / Type                                                                     |
| -------------------------------- | ---------------------------------------------------------------------------------- |
| Rancher version starting         | 2.9.2                                                                              |
| Rancher version upgraded         | v2.10-73a22a6ad6aca91f7817e3507b3b99dc44813cb0-head                                |
| Rancher commit link              | https://github.com/rancher/rancher/commit/73a22a6ad6aca91f7817e3507b3b99dc44813cb0 |
| Installation option              | Helm (high availability)                                                           |
| RKE binary version used          | v1.6.2                                                                             |
| If Helm Chart k8s cluster        | v1.30.4                                                                            |
| Cert Details                     | external tls `aws acm`                                                             |
| Docker version                   | 20.10.7, build f0df350                                                             |
| Helm version                     | v2.16.8-rancher2                                                                   |
| Downstream cluster type          | not applicable                                                                     |
| Downstream K8s version           | not applicable                                                                     |
| Authentication providers enabled | local                                                                              |
| Logged in user role              | admin                                                                              |
| Browser type                     | Opera GX                                                                           |
| Browser version                  | LVL6 (core: 114.0.5282.93) (arm64)                                                 |
| Dashboard                        | master fa2e6dd                                                                     |
| Webhook version                  | rancher/rancher-webhook:v0.6.1-rc.5                                                |

<br>

</details>


<a name="top"></a>

### 🧪 Test Cases

| \#  | Priority | Description & Link                                    | PASS/FAIL |
| --- | -------- | ----------------------------------------------------- | --------- |
| 1   | P0       | [(Regression Check) Steve Validation Tests](#test-1)  | ✅ `PASS`  |
| 2   | P0       | [(Regression Check) Steve Integration Tests](#test-2) | ✅ `PASS`  |
| 3   | P0       | [`v1/catalog.cattle.io.clusterrepo` Filter](#test-3)  | ✅ `PASS`  |
| 4   | P0       | [`v1/catalog.cattle.io.clusterrepo` Sort](#test-4)    | ✅ `PASS`  |
| 5   | P0       | [`/v1/events` `_type` Filter](#test-5)                | ✅ `PASS`  |
| 6   | P0       | [`/v1/events` `_type` Sort](#test-6)                  | ✅ `PASS`  |
| 7   | P0       | [Upgrade](#test-7)                                    | ✅ `PASS`  |


<details>
    <summary>🚨 7 test cases... CLICK TO EXPAND! (For table links to work) ⬅️</summary>

<br>

# 1 / (Regression Check) Steve Validation Tests Status: ✅ `PASS`

<a name="test-1"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 1 details... Click to expand</summary>

**Test Steps for Validation**

1. Run automated validation tests to ensure no regressions


**✅ Expected Outcome**

Regression checks should pass

**✅ Actual Outcome**

Regression checks passing

</details>
<hr>

# 2 / (Regression Check) Steve Integration Tests Status: ✅ `PASS`

<a name="test-2"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 2 details... Click to expand</summary>

**Test Steps for Validation**

1. Run automated integration tests to ensure no regressions


**✅ Expected Outcome**

Regression checks should pass

**✅ Actual Outcome**

Regression checks passing


</details>
<hr>

# 3 / `v1/catalog.cattle.io.clusterrepo` Filter Status: ✅ `PASS`

<a name="test-3"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 3 details... Click to expand</summary>

**Test Steps for Validation**

1. Start a Rancher server with a version with these changes
2. Create an admin token
3. Make a `GET` request to `{{rancherURL}}/v1/catalog.cattle.io.clusterrepo?filter=spec.gitBranch=main`
4. Expect 2 items returned
    - `rancher-partner-charts`
    - `rancher-rke2-charts`
6. These were successfully returned
7. Make a `GET` request to `{{rancherURL}}/v1/catalog.cattle.io.clusterrepo?filter=spec.gitRepo=https://git.rancher.io/partner-charts`
8. Expect 1 item returned
   - `rancher-partner-charts`
9. Make a `POST` request to `{{rancherURL}}/v1/catalog.cattle.io.clusterrepo` with the following body:

    ```json
    {
      "type": "catalog.cattle.io.clusterrepo",
      "metadata": {
        "name": "testing123"
      },
      "spec": {
        "clientSecret": null,
        "gitRepo": "https://github.com/brudnak/linode-ubuntu-setup-dadfish.git",
        "gitBranch": "filterTest"
      }
    }
    ```

10. Expected a `201` response
11. Received that `201` response
12. Filter on that with a `GET` to `{{rancherURL}}/v1/catalog.cattle.io.clusterrepo?filter=spec.gitBranch=filterTest`
13. Expect to received 1 item back
    - Received back: `testing123` as expected
14. Delete that cluster repo with a `DELETE` to `{{rancherURL}}/v1/catalog.cattle.io.clusterrepo/testing123`

**✅ Expected Outcome**

Receive expected filtered results

**✅ Actual Outcome**

Received the expected filtered results

</details>
<hr>

# 4 / `v1/catalog.cattle.io.clusterrepo` Sort Status: ✅ `PASS`

<a name="test-4"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 4 details... Click to expand</summary>

**Test Steps for Validation**

1. Start a Rancher server with a version with these changes
2. Create an admin token
3. Make a `POST` request to `{{rancherURL}}/v1/catalog.cattle.io.clusterrepo` with the following body:

    ```json
    {
      "type": "catalog.cattle.io.clusterrepo",
      "metadata": {
        "name": "filter-test"
      },
      "spec": {
        "clientSecret": null,
        "gitRepo": "https://github.com/brudnak/linode-ubuntu-setup-dadfish.git",
        "gitBranch": "filterTest"
      }
    }
    ```
4. Make a `POST` request to `{{rancherURL}}/v1/catalog.cattle.io.clusterrepo` with the following body:

    ```json
    {
      "type": "catalog.cattle.io.clusterrepo",
      "metadata": {
        "name": "dadfish"
      },
      "spec": {
        "clientSecret": null,
        "gitRepo": "https://github.com/brudnak/linode-ubuntu-setup-dadfish.git",
        "gitBranch": "dadfish"
      }
    }
    ```
5. Make a `POST` request to `{{rancherURL}}/v1/catalog.cattle.io.clusterrepo` with the following body:

    ```json
    {
      "type": "catalog.cattle.io.clusterrepo",
      "metadata": {
        "name": "filter-test5"
      },
      "spec": {
        "clientSecret": null,
        "gitRepo": "https://github.com/brudnak/linode-ubuntu-setup-dadfish.git",
        "gitBranch": "filterTest5"
      }
    }
    ```

6. Make a `POST` request to `{{rancherURL}}/v1/catalog.cattle.io.clusterrepo` with the following body:

    ```json
    {
      "type": "catalog.cattle.io.clusterrepo",
      "metadata": {
        "name": "filter-test6"
      },
      "spec": {
        "clientSecret": null,
        "gitRepo": "https://github.com/brudnak/linode-ubuntu-setup-dadfish.git",
        "gitBranch": "filterTest6"
      }
    }
    ```

7. Sort these with the following `GET` to `{{rancherURL}}/v1/catalog.cattle.io.clusterrepo?filter=spec.gitBranch=filterTest5,spec.gitBranch=filterTest6&sort=spec.gitBranch`
8. Expecting 2 results in this order:
   1. `filter-test5`
   2. `filter-test6`
9. Now sort with the following `GET` to `{{rancherURL}}/v1/catalog.cattle.io.clusterrepo?filter=spec.gitBranch=filterTest5,spec.gitBranch=filterTest6&sort=-spec.gitBranch`
10. Expecting 2 results in this order:
   1. `filter-test6`
   2. `filter-test5`
11. NOTE: the difference between these two `GET`'s is `&sort=spec` vs `&sort=-spec` with the `-` before `spec`


**✅ Expected Outcome**


Expect sorting to function as expected

**✅ Actual Outcome**

Sorting working as expected

</details>
<hr>

# 5 / `/v1/events` `_type` Filter Status: ✅ `PASS`

<a name="test-5"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 5 details... Click to expand</summary>

**Test Steps for Validation**

1. Run the following script with `./script.sh 10`:

    ```sh
    #!/bin/bash

    if [ $# -ne 1 ]; then
        echo "Usage: $0 <number_of_types>"
        exit 1
    fi

    number_of_types=$1

    for i in $(seq 1 $number_of_types); do
        cat <<EOF | kubectl apply -f -
    apiVersion: v1
    kind: Event
    metadata:
      name: my-custom-event$i
      namespace: default
    involvedObject:
      apiVersion: v1
      kind: Pod
      name: my-pod
      namespace: default
    reason: CustomEventGenerated
    message: "This event #$i."
    type: MyCustomEventType$i
    count: 1
    source:
      component: my-custom-source
    EOF
        echo "Created custom event type $i"
    done
    ```

2. Then run the following `GET` >>> `{{rancherURL}}/v1/events?filter=_type=MyCustomEventType7,_type=MyCustomEventType8`
3. Expecting 2 results:
   - `myCustomEventType7`
   - `myCustomEventType8`
4. Received only these 2 event `_type` as expected

**✅ Expected Outcome**

To be able to filter by `_type` successfully

**✅ Actual Outcome**

Was able to successfully filter by `_type`


</details>
<hr>

# 6 / `/v1/events` `_type` Sort Status: ✅ `PASS`

<a name="test-6"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 6 details... Click to expand</summary>

**Test Steps for Validation**

1. Run the following script with `./script.sh 10`:

    ```sh
    #!/bin/bash

    if [ $# -ne 1 ]; then
        echo "Usage: $0 <number_of_types>"
        exit 1
    fi

    number_of_types=$1

    for i in $(seq 1 $number_of_types); do
        cat <<EOF | kubectl apply -f -
    apiVersion: v1
    kind: Event
    metadata:
      name: my-custom-event$i
      namespace: default
    involvedObject:
      apiVersion: v1
      kind: Pod
      name: my-pod
      namespace: default
    reason: CustomEventGenerated
    message: "This event #$i."
    type: MyCustomEventType$i
    count: 1
    source:
      component: my-custom-source
    EOF
        echo "Created custom event type $i"
    done
    ```

2. Then run the following `GET` >>> `{{rancherURL}}/v1/events?filter=_type=MyCustomEventType7,_type=MyCustomEventType8&sort=_type`
3. Expect 2 results in the following order:
   1. `MyCustomEventType7`
   2. `MyCustomEventType8`
4. Now run the following `GET` >>> `{{rancherURL}}/v1/events?filter=_type=MyCustomEventType7,_type=MyCustomEventType8&sort=-_type`
5. NOTE: the difference between these two `GET`'s is `&sort=_type` vs `&sort=-_type` with the `-` before `_type`
6. Expect 2 results in the following order:
   1. `MyCustomEventType8`
   2. `MyCustomEventType7`

**✅ Expected Outcome**

Sort to work with `_type` as expected

**✅ Actual Outcome**

Sort working with `_type` as expected

</details>
<hr>





# 7 / Upgrade Status: ✅ `PASS`

<a name="test-7"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 7 details... Click to expand</summary>

**Test Steps for Validation**

1. Start with a Rancher version previous to this release
2. Upgrade Rancher to this version
3. Re-run all test cases against an upgrade Rancher

**✅ Expected Outcome**

Test cases should pass on an upgraded setup

**✅ Actual Outcome**

Tests passing on an upgraded setup


</details>
<hr>

</details>

**Comment by gaktive** [comment]
@MbolotSuse to file a backport to 2.9.4.
