### ISSUE TITLE
Agent on RancherOS running on AWS could not connect

### ISSUE THREAD

**Issue by mauermbq** [rancher/rancher#4665]
Rancher Version: 1.0.1

Docker Version: 1.10

OS: Rancher (ami-4f50a72f)

Steps to Reproduce: Add Host from UI

Results: Waiting for agent connection 

Expected: Showing state of running Docker host

Hi,

I started with rancher on my local engine (running rancher in a local container on my laptop).
After some successful test on my local maschine I tried to start to run a rancher OS on AWS (details from API output see below). EC2 Management console shows that the engine was successfully started, but the agent could not establish a connection to my Rancher instance.

Best regards
Mark

    "id": "1ph5",
    "type": "machine",
    "links": {
        "self": "…/v1/projects/1a5/machines/1ph5",
        "account": "…/v1/projects/1a5/machines/1ph5/account",
        "hosts": "…/v1/projects/1a5/machines/1ph5/hosts",
        "config": "…/v1/projects/1a5/machines/1ph5/config",
    },
    "actions": {
        "update": "…/v1/projects/1a5/machines/1ph5/?action=update",
        "remove": "…/v1/projects/1a5/machines/1ph5/?action=remove",
    },
    "name": "structr",
    "state": "active",
    "accountId": "1a5",
    "amazonec2Config": {
        "accessKey": "mykey",
        "ami": "ami-4f50a72f",
        "deviceName": null,
        "iamInstanceProfile": null,
        "instanceType": "t2.micro",
        "region": "us-west-2",
        "rootSize": "16",
        "secretKey": "mysecret",
        "securityGroup": "rancher-machine",
        "sessionToken": null,
        "spotPrice": null,
        "sshKeypath": null,
        "sshUser": "rancher",
        "subnetId": null,
        "tags": null,
        "volumeType": null,
        "vpcId": "vpc-18d99a7d",
        "zone": "a",
    },
    "authCertificateAuthority": null,
    "authKey": null,
    "azureConfig": null,
    "created": "2016-05-03T07:12:43Z",
    "createdTS": 1462259563000,
    "description": null,
    "digitaloceanConfig": null,
    "dockerVersion": null,
    "driver": "amazonec2",
    "engineEnv": null,
    "engineInsecureRegistry": null,
    "engineInstallUrl": "https://releases.rancher.com/install-docker/1.10.sh",
    "engineLabel": null,
    "engineOpt": null,
    "engineRegistryMirror": null,
    "engineStorageDriver": null,
    "exoscaleConfig": null,
    "externalId": "4e5bcb9d-62b5-4a83-8cfe-47fd7827b49f",
    "genericConfig": null,
    "googleConfig": null,
    "hypervConfig": null,
    "kind": "machine",
    "labels": { },

**Comment by deniseschannon** [comment]
From the EC2 instance, would the rancher/agent be able to connect to your Rancher server? Since it seems like you are running Rancher on your laptop, I'm guessing not?

http://docs.rancher.com/rancher/latest/en/faqs/agents/#how-to-check-your-host-registration-is-set-correctly

From the EC2 instance, the rancher/agent needs to be able to access your local machine. You could try and reverse the setup, host Rancher on AWS and then add a host as your local machine.

**Comment by deniseschannon** [comment]
@mauermbq If you are still facing issues, please re-open.

**Comment by mauermbq** [comment]
no issue can be closed
on a laptop where the public IP changes, you require a dynDNS, otherwise agents get lost in the public space
