### ISSUE TITLE
[BUG] CIS Benchmark scan for k3s clusters fails on rancher v2.8.6.

### ISSUE THREAD

**Issue by vivek-shilimkar** [rancher/rancher#46663]
**Rancher Server Setup**
- Rancher version: v2.8.6
- Installation option (Docker install/Helm Chart): Docker

**Information about the Cluster**
- Kubernetes version: v1.25.16 and v1.28.11
- Cluster Type (Local/Downstream): Downstream multinode cluster

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Admin

**Describe the bug**
CIS Benchmark permissive scan fails on k3s clusters on rancher v2.8.6. The scans probably fails on on rancher and k8s versions.

**To Reproduce**
1. Create a rancher server v2.8.6
2. Create cluster with any supported k3s version.
3. Once cluster is up and active, install CIS Benchmark chart version 5.3.0-rc1 (security scan image v0.2.17-rc9)
4. Run `k3s-cis-1.8-profile-permissive` or `k3s-cis-1.8-profile-permissive` depending on version of cluster.
5. Observe the results.

**Result**
Tests numbers 1.1.9, 1.1.11 fails and Test number 2.1 to 2.7 shows mixed results. The 2 nodes on which the tests are failing are actually master nodes. These tests shouldn't be running on these nodes. Screenshot attached for reference.

**Expected Result**
All the test should pass.

**Screenshots**
![Screenshot from 2024-08-13 10-37-03](https://github.com/user-attachments/assets/37814d85-3eb4-4fc9-9aa4-1321f58a9fa7)

**Comment by rishabhmsra** [comment]
Validated on rancher v2.8.7-rc10:

- Create  v1.28.11+k3s2 and v1.25.16+k3s4 node driver(1-cp, 1-e, 1-w) and hardened clusters(1-cp, 1-e, 1-w)
- Install CIS benchmark chart v5.3.0 with `rancher/security-scan:v0.2.17-rc11` and `rancher/cis-operator:v1.0.15-rc.1` images.
- Run the v1.7 and v1.8 permissive profile scan on k8s v1.25 and v1.28 node driver clusters respectively and observe below failures.
- Also run v1.7 and v1.8 hardened profile scan on k8s v1.25 and v1.28 hardened clusters respectively and observe below failures.


Result:
- 1.1.11 fails in v1.7 and v1.8 permissive and hardened profile scans.

**Comment by rishabhmsra** [comment]
Validated on rancher v2.8-head(91d1839) :
Installed CIS chart 5.4.0-rc.2 and scans are passing now, hence closing the issue.
