### ISSUE TITLE
Generate and Publish sha256sum.txt in RKE Releases 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#46677]
https://github.com/rancher/rke/issues/3652

There used to be a sha256sum.txt file in RKE's releases, for example [v1.5.10](https://github.com/rancher/rke/releases/tag/v1.5.10).
The sha256sum.txt is missing in the recent releases since we switched from Drone CI to GitHub Action. 
We should generate and add the missing sha256sum.txt back.

**Comment by mitulshah-suse** [comment]
Confirmed, its getting generated and added to the release.
ref: https://github.com/rancher/rke/releases/download/v1.6.2-rc1/sha256sum.txt
Closing the issue.
