### ISSUE TITLE
[RFE] Imperative API

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#46694]
Stub ticket for Imperative API.

**Comment by MKlimuszka** [comment]
We are guessing this is a QA/L, but Andrew will have to confirm when more details arise.

**Comment by prachidamle** [comment]
Also adding Auth team to implement this for the tokens resource once the design for Imperative API is approved.

**Comment by MKlimuszka** [comment]
Closed in favor of https://github.com/rancher/rancher/issues/47010
