### ISSUE TITLE
[BUG] When attempting to provision a downstream RKE2/K3S cluster in v2.10 images, error message `No version info found in KDM` is presented

### ISSUE THREAD

**Issue by markusewalker** [rancher/rancher#46700]
**Rancher Server Setup**
- Rancher version: `v2.10-b6023c4eee4114bb49b9492072b7ffec46a08a23-main`
- Installation option (Docker install/Helm Chart): Docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: N/A
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Custom/Node Driver

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Cluster Owner
  - If custom, define the set of permissions:

**Describe the bug**

When standing up a `v2.10` Rancher, I am unable to even attempt to provision an RKE2/K3S cluster. Going to a custom or node driver cluster results in the following:

![image](https://github.com/user-attachments/assets/8ad91a4e-8224-4810-8a44-60c5ab9e0e0f)

![image](https://github.com/user-attachments/assets/36a166e3-a3f7-4f76-865f-148bed962390)

In the global settings, seems that the UI settings are going to `release/v2.9` as well:

![image](https://github.com/user-attachments/assets/b7644e93-a119-40c2-b265-a8d238ae6d4b)

Additionally, the installed Rancher chart in the local cluster is showing the same:

![image](https://github.com/user-attachments/assets/9729706c-630c-4cb7-878b-96b817eff965)

As a result, v2.10 is unusable until this gets addressed.

**To Reproduce**

1. Setup Rancher v2.10.
2. Attempt to provision a custom or node driver RKE2/K3S cluster.
3. Note the failure shown above.

**Result**
Unable to attempt to provision a downstream RKE2/K3S cluster.

**Expected Result**

I should be able to provision a downstream RKE2/K3S cluster.

**Comment by markusewalker** [comment]
Validated that this is addressed on main commit https://github.com/rancher/rancher/commit/2b955aa0e4823baf6fbaf25c898aeae0273c6b48.

**ENVIRONMENT DETAILS**
- Rancher install: Docker
- Rancher version: `main` https://github.com/rancher/rancher/commit/2b955aa0e4823baf6fbaf25c898aeae0273c6b48

**TEST RESULTS**
|#|Scenario|Result|
|---|---|---|
|1|Provision downstream RKE2 node driver cluster|:white_check_mark:|
|2|Provision downstream K3S node driver cluster|:white_check_mark:|

**Comment by nickderoo-hv** [comment]
@kinarashah @markusewalker 
Is there any workaround to this? my use case is to manage all Custom clusters with rancher, now I cant provision or manage any of my clusters, is there anything I can do beyond rollback my upgrade?
