### ISSUE TITLE
Change Stack and System menu items

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4670]
Version - master 5/3

Changes:

- [x] Change Stack main menu item to say Applications
- [x] Have All, Stacks & System sub-menu items under Applications
- [ ] ~~Remove Add Stack from System stacks page~~

**Comment by vincent99** [comment]
It's now possible to add a stack that will go into System, so the 3rd one doesn't apply

**Comment by tfiduccia** [comment]
Version - master 5/5
Verified fixed
