### ISSUE TITLE
[RFE] [2.8] Bump system-agent to v0.3.8-rc.3

### ISSUE THREAD

**Issue by jakefhyde** [rancher/rancher#46721]
Bump system-agent to v0.3.8-rc.3

**Comment by susesgartner** [comment]
Ticket # - Test Results - ✅ 
---
 
| Scenario | Test Case | Result |
|---|---|---|
| 1. | Provisioning | PASS |
| 2. | Cert Rotation | PASS |
| 3. | Rancher upgrade | PASS |
| 4. | k8s upgrade/restore | PASS |
| 5. | Cluster Scaling | PASS |

NOTE: All downstream cluster tests above were run on RKE1/RKE2/K3S
---
Verified with HA Helm on Rancher `v2.8.7-rc6`:
---
 
Scenario 1: Provisioning
---
1. Provision a 3 node all roles cluster (RKE1/RKE2/K3S)
2. Verify all clusters come up and all pods are in a stable state.
 
Results: The cluster comes up and all pods are in a stable state
 
---

Scenario 2: Cert Rotation
---
1. Rotate the certs on the clusters created in Scenario 1
3. Rotate the certs
 
Results: The cluster rotates the certs and all pods are active.

---

Scenario 3: Rancher upgrade
---
1. Create a rancher instance on 2.8.6
2. Provision a 3 node split roles cluster for RKE1/RKE2/K3S
3. Upgrade the cluster to 2.8.7-rc6
4. Verify all clusters are in a stable state
 
Results: The clusters remain in a stable state after the upgrade

Scenario 4: k8s upgrade/restore
---
1. Take a snapshot on the clusters from scenario 1
2. upgrade the k8s version
3. restore the snapshot taken in step 1
 
Results: The clusters remain in a stable state after the upgrade/restore

Scenario 5: Cluster Scaling
---
1. Scale up the clusters from Scenario 1 
2. Verify the node comes up and all pods remain in an active state
3. Scale down the clusters
4. Verify the node comes up and all pods remain in an active state
 
Results: The clusters remain in a stable state after scaling up/down the nodes
