### ISSUE TITLE
[BUG] [2.8] If project namespace is terminating, creating a CRTB produces an error in the logs

### ISSUE THREAD

**Issue by aruiz14** [rancher/rancher#46736]
backport #42904 

This is specifically about backporting https://github.com/rancher/rancher/pull/42924 to `release/v2.8`

**Comment by aruiz14** [comment]
See https://github.com/rancher/rancher/issues/46735#issuecomment-2296377653

**Comment by aruiz14** [comment]
Copied from https://github.com/rancher/rancher/issues/42904#issuecomment-1821658571

# Validation

## Root Cause

When a namespace is terminating, it deletes all the resources inside it before it gets deleted itself. During this process, it is not possible to create new resources in the namespace. When we attempt to create management plane CRTB and PRTBs we only check that the namespace exists, and if it does, we attempt to create the CRTB and PRTB. This causes errors to show up in the logs while the namespace is terminating.

As a secondary effect, some of the integration tests will fail if the system is slow and API calls happen while a namespace is terminating and the test see errors. This is rare, but happens when the system experiences high load.

## What was fixed, or what change has occurred

A check was added to the management CRTB and PRTBs to only attempt to create them when the namespace is active and not terminating.

## Areas or cases that should be tested

- Creating and deleting projects and namespaces.
- Adding and removing cluster-owners 

## What areas could experience regressions

Unlikely, but any existing tests for CRTB/PRTBs, Namespaces, Projects and Cluster-Owners would be a good check.

## Are the repro steps accurate/minimal?

For testing, I would add the following finalizer for the project namespace:

```
...
finalizers:
  - kubernetes
...
```

**Comment by joesims22** [comment]
<a name="top"></a>

## QA TEST PLAN

The following tests have been executed on v2.8-head to validate the fix:
### Test Cases

| \#  | Priority | Description & Link                                                      | PASS/FAIL |
| --- | -------- | ----------------------------------------------------------------------- | --------- |
| 1   | P0       | [Fresh Install Check: User Addition to Cluster with Terminating Project Namespace](#test-1)  |           |
| 2   | P0       | [Fresh Install Check: User Addition to Project with Terminating Project Namespace](#test-2)  |           |
| 3   | P1       | [Upgrade Check: User Addition to Cluster with Terminating Project Namespace](#test-3)  |           |

<details>
    <summary>🚨 3 test cases... CLICK TO EXPAND! ⬅️</summary>

<br>

# 1 Fresh Install Check: User Addition to Cluster with Terminating Project Namespace  

<a name="test-1"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 1 details... Click to expand</summary>

**Test Steps:**
1. Create a downstream cluster in Rancher.
2. Create a standard user.
3. Create a project "testProject1" in the downstream cluster.
4. Simulate a project stuck in terminating state by adding a finalizer to the project "controller.cattle.io/dummy".
5. Delete the project "testProject1". 
6. Add the user as a cluster-owner to the downstream cluster.
7. Force delete the project stuck in terminating state by removing the finalizer "controller.cattle.io/dummy" from the project 
8. Verify that the project is deleted.
9. Verify that there are no errors logged indicating role/role binding creation when a project is in terminating state

</details>

<hr>

# 2 Fresh Install Check: User Addition to Project with Terminating Project Namespace  

<a name="test-2"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 2 details... Click to expand</summary>

**Test Steps:**
1. Create a downstream cluster in Rancher.
2. Create a standard user.
3. Create a project "testProject1" in the downstream cluster.
4. Simulate a project stuck in terminating state by adding a finalizer to the project "controller.cattle.io/dummy".
5. Delete the project "testProject1". 
6. Attempt to add the user as a project-owner to the project "testProject1". Verify that this fails with 403 Forbidden error.
7. Force delete the project stuck in terminating state by removing the finalizer "controller.cattle.io/dummy" from the project  
8. Verify that the project is deleted.

</details>

<hr>

# 3 Upgrade Check: User Addition to Cluster with Terminating Project Namespace  

<a name="test-1"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 3 details... Click to expand</summary>

**Test Steps:**
1. On Rancher v2.8, Create a downstream cluster in Rancher.
2. Create a standard user.
3. Create a project "testProject1" in the downstream cluster.
4. Simulate a project stuck in terminating state by adding a finalizer to the project "controller.cattle.io/dummy".
5. Delete the project "testProject1". 
6. Add the user as a cluster-owner to the downstream cluster.
7. Verify that there are errors logged indicating creation of role/rolebinding when a project is in terminating state
8. Upgrade Rancher from v2.8 to latest version under test
9. Post upgrade, verify that there are no new errors logged indicating creation of role/rolebinding when the project is in terminating state 
10. Force delete the project stuck in terminating state by removing the finalizer "controller.cattle.io/dummy" from the project  
11. Verify that the project is deleted.

</details>

<hr>

</details>
