### ISSUE TITLE
[BUG]ui-offline-preferred 'dynamic' value not working

### ISSUE THREAD

**Issue by mantis-toboggan-md** [rancher/rancher#46743]
**Rancher Server Setup**
- Rancher version: v2.10-4e2703bb4f157be02dbc2f2828d99a5b1c61bb73-main
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): docker
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version:v1.30.2+k3s2
- Cluster Type (Local/Downstream): local

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) admin

**Describe the bug**
The `ui-offline-preferred` setting is not being respected in Rancher head builds. When set to 'dynamic' (the default value) this setting should cause Rancher to load embedded ui assets in production builds, and load remote assets in dev builds. 

**To Reproduce**
1. Install Rancher using the rancher/rancher:head tag
2. navigate to the UI
3. right-clic, select 'view page source' and note the `src` attribute of the script tag at the bottom of the page.

**Result**
Embedded assets are loaded (src is a relative path) 

**Expected Result**
Assets should be loaded remotely (src should be "https://releases.rancher.com....")

**Additional context**
This appears specific to rancher/rancher:head. Possibly related to version strings ending in `-main` instead of `-head` now.

rancher/rancher:v2.9-head is loading ui assets remotely by default, as expected
rancher/rancher:v2.9.0 is loading embedded ui assets by default, as expected

**Comment by richard-cox** [comment]
I think this bumbles down to https://github.com/rancher/rancher/blob/main/pkg/settings/setting.go#L354

See https://github.com/rancher/rancher/blob/main/pkg/ui/handler.go#L42 and https://github.com/rancher/steve/blob/main/pkg/ui/handler.go#L121

Looking at IsRelease it also affects something catalog related (https://github.com/rancher/rancher/blob/main/pkg/catalogv2/content/content.go#L375)

**Comment by richard-cox** [comment]
Give #46757 this should be fixed (requires validation)

**Comment by Jono-SUSE-Rancher** [comment]
@rancher-max - Do you think we can re-validate this with the PR that Rich fixed? Do we have time for v2.10?

**Comment by rancher-max** [comment]
This shouldn't have any functional problems with the actual release as it appears to only affect `head` builds, but I am testing using `v2.10.0-alpha12` and `head`

**Comment by rancher-max** [comment]
On `head` build:
```
src="https://releases.rancher.com/dashboard/release-2.10/js/chunk-vendors.e10046b1.js"

src="https://releases.rancher.com/dashboard/release-2.10/js/index.238a68aa.js"
```

On `v2.10.0-alpha12` build:
```
src="/dashboard/js/chunk-vendors.f995b492.js"

src="/dashboard/js/chunk-vendors.f995b492.js"
```

This is the expected result -- `head` is loading assets remotely, and `v2.10.x` is loading embedded assets.
