### ISSUE TITLE
for Log Out, light grey text on grey background hard to read

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4675]
Version - master 5/3

Steps to Reproduce: 
1.  Authenticate using Github
2.  In light theme click on user icon (on right)

Results: The Log Out text is light grey on a grey background and hard to read
![image](https://cloud.githubusercontent.com/assets/11514927/15000928/41000c3a-1148-11e6-99b6-93fcc1ce7933.png)

Expected:  Make the text darker then the background

**Comment by lvuch** [comment]
fixed in https://github.com/rancher/ui/pull/649

**Comment by tfiduccia** [comment]
Version - master 5/13
Verified fixed
