### ISSUE TITLE
Switch to this Namespace menu option is not centered properly

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4676]
Version - master 5/3

Steps to Reproduce: 
1.  Create kubernetes environment
2.  Add host and wait for services to setup
3.  Go to Manage Namespace page
4.  Add a namespace
5.  Click on menu for that namespace

Results: The Switch to this Namespace option in menu is not centered properly.  It's too close to the top.
![image](https://cloud.githubusercontent.com/assets/11514927/15001047/2a4ff40e-1149-11e6-9236-3387bb5e8cda.png)

Expected: Center it properly in menu

**Comment by lvuch** [comment]
https://github.com/rancher/ui/pull/721

**Comment by tfiduccia** [comment]
Version - master 6/13
Verified fixed
