### ISSUE TITLE
[Backport 2.8] [Windows] STRICT_VERIFY environment variable is not passed to windows nodes

### ISSUE THREAD

**Issue by Sahota1225** [rancher/rancher#46773]
Backport # https://github.com/rancher/rancher/issues/46396

**Comment by markusewalker** [comment]
Validated this issue on `v2.8-head` https://github.com/rancher/rancher/commit/ad14e0efa3e458787323f4f43847bb0ca8dcf32d. In-depth test results can be found in Qase test run /RM 2231. See below the test scenarios tested:

**ENVIRONMENT DETAILS**
- Rancher install: Helm
- Rancher version: `v2.8-head` https://github.com/rancher/rancher/commit/ad14e0efa3e458787323f4f43847bb0ca8dcf32d

**TEST RESULTS**
|#|Scenario|Result|
|---|---|---|
|1|[Self-signed certificate] Validate SUC plans are properly deployed to downstream RKE2 v1.28 Windows node on fresh install of main and agent-tls-mode set to strict|:white_check_mark:|
|2|[Self-signed certificate] Validate SUC plans are properly deployed to downstream RKE2 v1.28 Windows nodes after upgrading Rancher and agent-tls-mode setting|:white_check_mark:|
|3|[Self-signed certificate] Validate SUC plans are NOT deployed to downstream RKE2 deprecated v1.27 Windows nodes after upgrading Rancher and agent-tls-mode setting|:white_check_mark:|
|4|[Self-signed certificate] Setup Rancher with no-cacerts, validate SUC plans are properly deployed to downstream RKE2 v1.29 Windows nodes after upgrading Rancher and agent-tls-mode setting|:white_check_mark:|
|5|[Private CA] Validate SUC plans are properly deployed to downstream RKE2 v1.28 Windows node on fresh install of main and agent-tls-mode set to strict|:white_check_mark:|
|6|[Private CA] Validate SUC plans are properly deployed to downstream RKE2 v1.28 Windows nodes after upgrading Rancher and agent-tls-mode setting|:white_check_mark:|
|7|[Private CA] Validate SUC plans are NOT deployed to downstream RKE2 deprecated v1.27 Windows nodes after upgrading Rancher and agent-tls-mode setting|:white_check_mark:|
|8|[vSphere Self-signed certificate] Validate SUC plans are properly deployed to downstream RKE2 v1.28 Windows node on fresh install|:white_check_mark:|
|9|[vSphere Private CA] Validate SUC plans are properly deployed to downstream RKE2 v1.28 Windows node on fresh install|:white_check_mark:|

**Comment by HarrisonWAffel** [comment]
For the release notes: 

- This fix only applies for newly provisioned Windows nodes, or existing Windows nodes running rke2 versions 1.30.4, 1.29.8, 1.28.13, 1.27.16 (August patches).

- A workaround will be posted for this issue which gives specific steps on how to use this change on existing nodes not running the August patches.
