### ISSUE TITLE
[RKE1] Update process for rancher/kubernetes tags

### ISSUE THREAD

**Issue by kinarashah** [rancher/rancher#46777]
Simplify the current process so it can then be automated to run whenever a new tag is pushed upstream (https://github.com/kubernetes/kubernetes/releases/tag)

This is possible if we modify how the branches are created, new process will be: 
- create a new branch every time for every k8s version (directly from the tag of the format `release-vX.Y.Z`) 
- apply rancher specific changes via the cherry-pick patch (could be PR or cherry-pick, but I think directly applying cherry-pick is OK cuz there's no need to review if upstream changes are all present) 
- push tag (tag comes directly from the release branch name)

Note: 
There's one thing we need to verify - the vendor commit update. Is `go build` and `go mod vendor` sufficient or would we need to manage this manually? cc @chiukapoor @mitulshah-suse

**Comment by chiukapoor** [comment]
The automation run was completed successfully.

Automation GHA run: https://github.com/rancher/kubernetes/actions/runs/11046387668

Release branches:
- v1.28.14: https://github.com/rancher/kubernetes/tree/release-v1.28.14
- v1.29.9: https://github.com/rancher/kubernetes/tree/release-v1.29.9
- v1.30.5: https://github.com/rancher/kubernetes/tree/release-v1.30.5
- v1.31.0: https://github.com/rancher/kubernetes/tree/release-v1.31.0
- v1.31.1: https://github.com/rancher/kubernetes/tree/release-v1.31.1

Tags:
- v1.28.14: https://github.com/rancher/kubernetes/releases/tag/v1.28.14
- v1.29.9: https://github.com/rancher/kubernetes/releases/tag/v1.29.9
- v1.30.5: https://github.com/rancher/kubernetes/releases/tag/v1.30.5
- v1.31.0: https://github.com/rancher/kubernetes/releases/tag/v1.31.0
- v1.31.1: https://github.com/rancher/kubernetes/releases/tag/v1.31.1

**Comment by chiukapoor** [comment]
September patch run: https://github.com/rancher/kubernetes/actions/runs/11046387668
