### ISSUE TITLE
Stacks menu option showing up for Kubernetes and Swarm

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4677]
Version - master 5/3

Steps to Reproduce: 
1.  Create a Kubernetes or Swarm environment
2.  Switch to that environment
3.  Now go to Manage Environment, Catalog, infrastructure, admin or api pages.

Results: Notice that even thou you are still in kubernetes or swarm environment the main menu items switched to cattle menuing. (Stacks menu item shows up and namespace/kubernetes/swarm menu items disappear)
![image](https://cloud.githubusercontent.com/assets/11514927/15001510/e8ea7ed6-114c-11e6-8d4d-d45cb336ff11.png)

Expected: Should still reflect menu from environment it's in.

**Comment by vincent99** [comment]
Root cause of this was going to the Audit Logs page, which loaded a new copy of the Project resource and wiped out the orchestration state info that controls what buttons should be visible.

**Comment by tfiduccia** [comment]
Going to Accounts or Manage Environments brings back the Application (User) menu

Not fixed

**Comment by vincent99** [comment]
Moved orchestration state somewhere else..

**Comment by tfiduccia** [comment]
Version - master 5.19
Verified fixed
