### ISSUE TITLE
[Backport release/v2.9] [BUG] `CATTLE_AGENT_FALLBACK_PATH` environment variable is way too prominent for custom clusters and can lead to confusion

### ISSUE THREAD

**Issue by Oats87** [rancher/rancher#46775]
**Rancher Server Setup**
- Rancher version: `v2.9.1`/`main`
- Installation option (Docker install/Helm Chart): N/A

**Information about the Cluster**
- Kubernetes version: K3s or RKE2
- Cluster Type (Local/Downstream): Downstream Custom

**Describe the bug**
In order to add SLE Micro 6 support to Rancher for K3s/RKE2 provisioned clusters, a change was made that introduced an environment variable named `CATTLE_AGENT_FALLBACK_PATH` which specifies a fallback path for the `system-agent` in the event that `/usr/local/bin` is not writeable (which is the case on SLE Micro 6).

This environment variable shows up in a very prominent manner for custom cluster registration, and can lead to confusion as the binaries do not end up in that directory for any operating system that does not have a read-only `/usr/local/bin` directory. As such, this environment variable should not be displayed prominently in the manner that it is, and should rather be handled/delivered on the backend with minimal visible impact to the user. 

**To Reproduce**
Create a K3s or RKE2 custom cluster, and view the "Registration" tab

**Result**
The registration command is extensively long and contains the `CATTLE_AGENT_FALLBACK_PATH` environment variable by default.

**Expected Result**
The registration command should remain the way it was prior to `v2.9.1`

**Screenshots**
<img width="1042" alt="Screenshot 2024-08-21 at 12 39 55 PM" src="https://github.com/user-attachments/assets/8d8140f3-5ffc-4840-bd23-9a19174afbd8">

**Additional context**
https://github.com/rancher/rancher/issues/45815
https://github.com/rancher/rancher/pull/46592

**Comment by Jono-SUSE-Rancher** [comment]
@Sahota1225 - Please make 100% sure that this makes it into v2.9-Next1 please. :)

**Comment by susesgartner** [comment]
Ticket #46775 - Test Results - ✅ 
---
 
| Scenario | Test Case | Result |
|---|---|---|
| 1. | Provisioning Test | PASS  |
| 2. | Upgrade restore test | PASS  |
 
---
Verified with (HA Helm or Docker) on Rancher `v2.9-head`:
---

Scenario 1: Verify CATTLE_AGENT_FALLBACK_PATH
---
NOTE: performed on RKE2/K3s and custom/node driver

1. Provision a 3 node cluster with data/dir set
2. Verify the cluster comes up active and all pods are in a stable state
3. Verify that the CATTLE_AGENT_FALLBACK_PATH is not present in the registration command for custom clusters
4. Verify that all data/dir's exist and contain the appropriate files
 
Results: All verification steps passed
 
---

Regression check 
Scenario 2: Upgrade restore test 
---
NOTE: performed on RKE2/K3s and custom/node driver

1. Provision a 3 node cluster with data/dir set
2. Take a snapshot
3. Upgrade the k8s version
4. Restore the snapshot
5. Verify that the cluster comes up active and all pods are in a stable state
6. Verify that all data/dir's exist and contain the appropriate files.

Results: All verification steps passed
