### ISSUE TITLE
Improve lasso caches metrics

### ISSUE THREAD

**Issue by aruiz14** [rancher/rancher#46783]
The current `lasso_controller_total_cached_object` Prometheus metric [registered by `lasso`](https://github.com/rancher/lasso/blob/24ab3dbf26f0bc6484ad2b4c58d4f375910922c0/pkg/metrics/metrics.go#L34-L41) has multiple problems that make it not really useful:
* Labels only differentiate by GVK, not taking into account that there could (and there are) multiple independent caches running at the same time.
* It does not differentiate by upstream vs. downstream usage, or management vs. user context.
* The metrics is only set on `WaitForCacheSync`, which makes the value static despite using a gauge.

**Comment by aruiz14** [comment]
## Validation Template

## Root Cause
Metrics for lasso caches were mixing contexts and their values didn't reflect up-to-date values.

## What was fixed, or what change have occurred
A new label was added to each context, and the collection logic was fixed to make the metrics reflect accurate values.

## Areas or cases that should be tested

Install Rancher [enabling the Performance Dashboard](https://ranchermanager.docs.rancher.com/how-to-guides/advanced-user-guides/monitoring-alerting-guides/enable-monitoring#enabling-the-rancher-performance-dashboard) and [install Rancher Monitoring](https://ranchermanager.docs.rancher.com/how-to-guides/advanced-user-guides/monitoring-alerting-guides/enable-monitoring#install-the-monitoring-application).

Then access the Prometheus Console, and query:
```
sum (lasso_controller_total_cached_object) by (kind, pod, ctx)
```
Which should show a result like this (in the Graph view):

![Screenshot 2024-08-22 at 08 47 33](https://private-user-images.githubusercontent.com/4057165/360317361-386386e3-1817-475f-9e74-1c0435755969.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5NDUzNjUsIm5iZiI6MTcyNzk0NTA2NSwicGF0aCI6Ii80MDU3MTY1LzM2MDMxNzM2MS0zODYzODZlMy0xODE3LTQ3NWYtOWU3NC0xYzA0MzU3NTU5NjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDNUMDg0NDI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDU3MGRlYzY2MDcwNmQ1OGIzNjg4YjNlOWRiZjVkMjhlZGYwYmUxZTIzMDNhMTE0NzVlMWRjYjE4MDE2MzgzYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.rU86cbIDDeR_jDHgzpYza0nrtkewfF6yEWMsM7-Ufig)

## What areas could experience regressions
None.

**Comment by gaktive** [comment]
No back port to 2.8.x at this time.

**Comment by MSpencer87** [comment]
**Verified on Rancher v2.10.0-alpha3, rke2 v1.30.4+rke2r1**

lasso_controller_total_cached_object updates upon changes and displays context data


Steps to reproduce:
1. Bring up HA Rancher v2.10.0-alpha2
2. Edit Rancher deployment and include CATTLE_PROMETHUS_METRICS=true in Environment Variables
Local->Workloads->Deployments->Edit Config
3. Install Monitoring Local->Apps->Charts->Monitoring
4. Open Prometheus Graph Local->Monitoring->Dashboard
5. Search for lasso_controller_total_cached_object, no contexts visible
```
sum (lasso_controller_total_cached_object{kind=~"Secret"}) by (kind, pod, ctx)
```
6. In Rancher, create any random secret Local->Storage->Secret->Create
7. Return to Prometheus Graph and exectue query again, no changes reflected for created secret
<img width="1045" alt="Screenshot 2024-10-23 at 4 08 51 PM" src="https://github.com/user-attachments/assets/3809b28a-f5ff-4c84-9a48-c7b398ecd876">

Steps for validation:
1. Bring up HA Rancher v2.10.0-alpha3
2. Edit Rancher deployment and include CATTLE_PROMETHUS_METRICS=true
3. Install Monitoring & open Prometheus Graph
5. Search for lasso_controller_total_cached_object, verify all contexts are now visible
```
sum (lasso_controller_total_cached_object{kind=~"Secret"}) by (kind, pod, ctx)
```
6. In Rancher, create a random secret
7. Return to Prometheus Graph and exectue query again, added secret is counted
<img width="1003" alt="Screenshot 2024-10-23 at 4 13 12 PM" src="https://github.com/user-attachments/assets/48507c38-2827-42f7-b952-ff5d3d7f0315">
