### ISSUE TITLE
Catalog menu item missing from swarm

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4678]
Version - master 5/3 

Steps to Reproduce: 
1.  Create a swarm environment and set it up

Results: The Catalog menu item is missing

Expected: Catalog menu should be there

**Comment by vincent99** [comment]
Same cause as https://github.com/rancher/rancher/issues/4677

**Comment by tfiduccia** [comment]
Version - master 5/13
Verified fixed
