### ISSUE TITLE
[cli] Linux build instructions confusing

### ISSUE THREAD

**Issue by samcornwell** [rancher/rancher#46780]
I had been trying to build rancher cli for my system since there is no linux/arm64 release.

At some point it was running into an error with the package Dockerfile when running `make`. I spent some time trying to figure out the issue. It was only later that I realized I only needed `make build` and it was successfully building the binary the whole time. It was only failing in the package step because of a cert issue in the SUSE container (because my company's certs).

I believe this should be updated to say `make build` to avoid confusion:

https://github.com/rancher/cli?tab=readme-ov-file#linux-binary

**Comment by enrichman** [comment]
Thanks @samcornwell, it's probably worth to also have a `arm64` build target.

**Comment by samcornwell** [comment]
That would be great, thank you.

**Comment by samcornwell** [comment]
@enrichman would you like me to open an issue about adding that build target
