### ISSUE TITLE
[docs] broken link "security policy" in README.md

### ISSUE THREAD

**Issue by able8** [rancher/rancher#46799]
In the README.md file, the "[security policy](https://github.com/rancher/rancher/blob/main/SECURITY.md)" link is broken:

For security issues, please first check our [security policy](https://github.com/rancher/rancher/blob/main/SECURITY.md)

**Comment by able8** [comment]
Find an open MR to fix this issue: https://github.com/rancher/rancher/pull/44770

**Comment by pdellamore** [comment]
Thanks @able8.

The broken link was fixed!
