### ISSUE TITLE
[docs] document that impersonation, specially around using a lower privileged account in order to drops privileges doesn't work.

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#46790]
related RFE targeted for 2.10 
https://github.com/rancher/rancher/issues/41988

https://jira.suse.com/browse/SURE-7524?focusedId=1350492&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1350492

**Comment by Jono-SUSE-Rancher** [comment]
Closing ticket since I see Sunil was able to get some PRs merged regarding the documentation. Feel free to reopen if this is incorrect @samjustus
