### ISSUE TITLE
Manage existing docker swarm environment

### ISSUE THREAD

**Issue by mavencode01** [rancher/rancher#4680]
Rancher Version:latest

Docker Version:1.9+

OS: Linux

Steps to Reproduce: 
Run Rancher server on existing docker swarm environment.

Results: 
Does not recognize existing docker swarm.

Expected:
Detect docker swarm without manually adding the host.

**Comment by mavencode01** [comment]
I found this article, not sure the status though

http://rancher.com/rancher-support-for-docker-swarm-and-machine/


> Second, we are working with the Docker team to extend Swarm so that a cluster can be created outside of Rancher and automatically imported into Rancher for management.

**Comment by deniseschannon** [comment]
Currently this is not supported, but if there is enough community interest, we could look into prioritizing it.

**Comment by mavencode01** [comment]
+1

**Comment by ViBiOh** [comment]
+1

**Comment by anton-kasperovich** [comment]
+1 please

**Comment by pouicr** [comment]
would be great :+1:

**Comment by rdesgrange-lf** [comment]
would be _really_ great

**Comment by alfirin** [comment]
Would be perfect!

**Comment by wmangano** [comment]
👍

**Comment by alexlessard** [comment]
+1

**Comment by DynaJL** [comment]
:+1: Please! This would be very useful to our company.

**Comment by chainone** [comment]
👍

**Comment by taketnoi** [comment]
+1

**Comment by adouglas** [comment]
+1

**Comment by rossigee** [comment]
:+1:

**Comment by ChristianPejrup3Shape** [comment]
@deniseschannon i'm curious - if i'm reading this right this feature was mentioned back in Jan 2015 (http://rancher.com/rancher-support-for-docker-swarm-and-machine/) as something you are working on - not something that needs community support to be prioritized. Have priorities changed?

"Second, we are working with the Docker team to extend Swarm so that a cluster can be created outside of Rancher and automatically imported into Rancher for management."

**Comment by ibuildthecloud** [comment]
@ChristianPejrup3Shape Priorities haven't really changed, we are just adapting to the progress of swarm.  We initially announced support for Swarm in Rancher based off of "old swarm."  Seeing that "new swarm" was coming and completely different we didn't invest much effort into adding more enhancements to our integration.  Now that "new swarm" was finally released last week we are working on getting it supported in Rancher and dropping "old swarm."  Once we have that done we can look a doing self managed Swarm clusters.

I will say though that "new swarm" does lack some key features needed to make self managed clusters easy.  Namely the ability to run privileged containers and use host resources which is needed for our agent.  We will have to find a trick around that.

**Comment by ArthurasJ** [comment]
+1

**Comment by domasmar** [comment]
:+1:

**Comment by izhilenkov** [comment]
👍

**Comment by allamand** [comment]
+1

**Comment by rafagsiqueira** [comment]
+1

**Comment by kylegordon** [comment]
@ibuildthecloud thanks for the info. Can you comment on whether the 'import' process is going to be included in Release 1.2.0 targeted for October? ( https://github.com/rancher/rancher/milestone/67 )

**Comment by mch1307** [comment]
+1

**Comment by dextervip** [comment]
+1

**Comment by mmisztal1980** [comment]
+1

**Comment by adanba** [comment]
+1

**Comment by mmisztal1980** [comment]
Can we get some attention here please? Having this feature, would allow users, to use rancher in pre-configured environments such as Azure Container Service (which supports swarm/dcos/kubernetes)

**Comment by LLParse** [comment]
First of all, for anyone interested in this feature, please read this very carefully:
https://github.com/docker/swarm#swarm-disambiguation

While Docker doesn't (yet) plan on deprecating the old swarm, we have dropped support for it. The "new" swarm, or swarmkit, is bundled with the Docker Engine 1.12+. [This article](http://rancher.com/rancher-support-for-docker-swarm-and-machine/) is referring to the old, no longer available/supported by us, swarm.

Our new swarmkit support is still experimental - there are some architectural differences from the old swarm which we have yet to address. Once our support of the new product has matured, we will consider edge cases such as adopting preconfigured swarm clusters.

**Comment by kleinsasserm** [comment]
Just dropping in here. Managing an existing swarm would be, as mentioned above, a real benefit because swarm it is marked stable as of 17.x docker-ce.

**Comment by stephenlautier** [comment]
+1

**Comment by gimmemoore** [comment]
+1

**Comment by bramvdklinkenberg** [comment]
Will it be possible to manage Azure Container Service swarm clusters too?

**Comment by tanmng** [comment]
I would like to also voice my interest

**Comment by kvaps** [comment]
+1

**Comment by bhdrk** [comment]
+1

**Comment by SvenAbels** [comment]
+1

**Comment by alexey-boyko** [comment]
+1

**Comment by deanchin** [comment]
+1

**Comment by yolofy** [comment]
+1

**Comment by mukshs** [comment]
👍

**Comment by zzztimbo** [comment]
+1

**Comment by joostaafjes** [comment]
+1

**Comment by fdeschamps** [comment]
+1

**Comment by interactivewebs** [comment]
+1

**Comment by dhawton** [comment]
+1

**Comment by jamespepplinkhouse** [comment]
+1

**Comment by vincent99** [comment]
This is not going to happen for 1.x and 2.0 is  focused on Kubernetes.

**Comment by ThiagoScodeler** [comment]
+1
This feature would be great for people who manage an existing docker swarm cluster and would like to add Rancher.

**Comment by vincent99** [comment]
Swarm has been largely on life-support for a couple years already and now appears to be effectively dead with the Docker acquisition/split.  

We saw Kubernetes was going to win the market and that's why Rancher 2 is based on it. We are not going to have anything to do with Swarm.

**Comment by saulmmendoza** [comment]
Can you help me pointing out which repository or which modules should I read and understand to be able to know how the rancher-k8s integration works?

I feel that Swarm offers a better experience to allow onboarding teams into containers and cloud clusters, and then when you need it you can jump to k8s
