### ISSUE TITLE
[RFE] Respect creator's principal ID when creating projects and clusters

### ISSUE THREAD

**Issue by pmatseykanets** [rancher/rancher#46828]
Currently when a project or a cluster is created by a user who is logged in using an external authentication provider Rancher shows that user's principal ID as the owner in the UI only to be replaced later by it's local user's counterpart.

We want to make it possible to respect the principal ID that was used to create a project/cluster.

In order to do so we may introduce an additional annotation e.g. `field.cattle.io/creator-principal-name` that can cary the creator's principal ID to complement the existing `field.cattle.io/creatorId` that is set when the corresponding project/cluster object is created. There is no need to use this annotation if the user is logged in using the local provider.

Respecting the creator's principal ID can help with the issues like this https://github.com/rancher/rancher/issues/40304

**Comment by pmatseykanets** [comment]
For clusters we'd like to see

![Image](https://github.com/user-attachments/assets/2f9afd7c-1391-4d29-aa04-d44262651d74)

![Image](https://github.com/user-attachments/assets/9b867edc-ee86-4e1a-9db1-e67c8ce0fdb0)

**Comment by pmatseykanets** [comment]
In order for this to work in the UI, the UI needs to add this new annotation when creating a project or a cluster.

```sh
curl https://<rancher-url>/v3/cluster?_replace=true \
...
--data-raw '{
    "type": "cluster",
    "name": "test-cluster",
    "annotations": {
        "field.cattle.io/creator-principle-name": "keycloak_user://testuser1@example.com"
    },
    ...
}'
```

```sh
curl https://<rancher-url>/v3/projects \
...
--data-raw '{
    "type":"project",
    "name":"test-project",
    "annotations": {
        "field.cattle.io/creator-principle-name": "keycloak_user://testuser1@example.com"
    },
    ...
}'
```

It makes sense to add this annotation ONLY if the user is logged in using an external auth provider.

**Comment by samjustus** [comment]
https://jira.suse.com/browse/SURE-6693

**Comment by pmatseykanets** [comment]
## Validation Template

## What was fixed, or what change has occurred

The new annotation `field.cattle.io/creator-principal-name` was introduced in addition to the existing `field.cattle.io/creatorId` annotation that allows to specify the creator's principal name when creating a cluster or a project.
If this annotation is used the `userPrincipalName` field of the corresponding `ClusterRoleTemplateBinding` or `ProjectRoleTemplateBinding` will be set to the specified principal.
The principal should belong to the creator' user, which is enforced by the webhook.

## Areas or cases that should be tested

- Enable an authentication provider
- Login using the authentication provider
- Create a cluster/project using via Rancher api `v3/{projects|clusters}` using the `field.cattle.io/creator-principal-name` annotation
- Navigate to Cluster/Project Memebership view
- Note that the owner's principal is an auth provider's one (not local)

When the webhook changes become available

- Check that if `field.cattle.io/creator-principal-name` annotation is used the `field.cattle.io/creatorId` should also be set.
- Check that the request is rejected if the user specified in `field.cattle.io/creatorId` doesn't exist.
- Check that the request is rejected if the principal in `field.cattle.io/creator-principal-name` doesn't belong to the user specified in `field.cattle.io/creatorId`.

## What areas could experience regressions

N/A

## Are the repro steps accurate/minimal?

N/A.

**Comment by pmatseykanets** [comment]
# Release notes

## Rancher General

### Behavior Changes

The new annotation `field.cattle.io/creator-principal-name` was introduced in addition to the existing `field.cattle.io/creatorId` that allows to specify the creator's principal name when creating a cluster or a project.
If this annotation is used the `userPrincipalName` field of the corresponding `ClusterRoleTemplateBinding` or `ProjectRoleTemplateBinding` will be set to the specified principal. The principal should belong to the creator' user, which is enforced by the webhook.

**Comment by joesims22** [comment]
Validated on head id `b9b2855`. 
All test cases completed successfully. 

Automation for issue: [qa-task 1580](https://github.com/rancher/qa-tasks/issues/1580l)
