### ISSUE TITLE
K8's 1.31 Support for Gengo 

### ISSUE THREAD

**Issue by Sahota1225** [rancher/rancher#46829]
Support Gengo for 1.31

**Comment by ericpromislow** [comment]
This should be done after wrangler has been updated to support k8s 1.31. The only other two frameworks repos that reference this are steve and webhook, and looks like only because they depend on wrangler.

**Comment by ericpromislow** [comment]
There's nothing left to do here.  Issue #47207 covers moving away from gengo (v1)
