### ISSUE TITLE
LoadBalancer dont sets the SSL seetings

### ISSUE THREAD

**Issue by marvinwankersteen** [rancher/rancher#4683]
Rancher Version: 1.0.0
Docker Version: 1.10.3
OS: CentOS7 (4.5.0)

Steps to Reproduce: 
- Start httpd web-Container
- Setup a LoadBalancer with the following setings:
Listening Ports:
```
| Source | Protocol |    SSL   | Default Target Port | Access |
|  443   |   http   |    Set   |        443          | Public |
|   80   |   http   |  Not Set |         80          | Public |
```
- Add the httpd Web-Container as Target Service.
- Choose the Certificate which have Add through the Gui.
- After the LB has started, edit this LB.

Results:
- In the GUI are no SSL sets.
  - "There are no SSL listening ports configured"

If I try to open the Website with https://vhost.domain.tld/ I get the error:
"400 Bad Request"
"The plain HTTP request was sent to HTTPS port"

**Comment by vincent99** [comment]
"Tehre are no SSL listening ports configured" was fixed in 1.0.1: https://github.com/rancher/rancher/issues/4165

The balancer is doing SSL termination, so you want the default target port to be 80 for both.  You're sending a decrypted request (from 443) to the SSL port of the httpd container.

**Comment by marvinwankersteen** [comment]
Okay, thanks for the answer.
I want the traffic between the balancer and the httpd container over SSL. I have tried many settings over the RancherGUI but it is not possible.

Only when I edit the backend in haproxy.conf the communication is fine. I have to append the line "server" with "ssl verify none". Then its working. Is there a solution with the Rancher GUI?
Okay, I could use the tcp-mode but then in the logs of the httpd-Container is the IP-address of the balancer and I need the IP-Address of the clients.

**Comment by deniseschannon** [comment]
In our refactoring of our load balancer (https://github.com/rancher/rancher/issues/2179), we'll be adding the ability to customize the backend in haproxy. 

I'll close this ticket in favor of that one.
