### ISSUE TITLE
Loadbalancer default target port not working as expected

### ISSUE THREAD

**Issue by bacheson** [rancher/rancher#4684]
Rancher Version: 1.0.1

Docker Version: 1.10.3

OS: Ubuntu 14.04 LTS

Steps to Reproduce: 
1) create load balancer that uses SSL
2) add service with request host & target port
3) set default target port to this same port
4) visit another host pointing at lb that is not the request host in step 2

Results: 
503 error

Expected:
It appears the default service is not used when a request host is set. I'd expect the default port to be used regardless.

**Comment by deniseschannon** [comment]
Can you share your docker-compose.yml? Even a dummy version would ensure that I would understand exactly what you're trying to do.

**Comment by deniseschannon** [comment]
@bacheson If you're able to share your docker-compose.yml (even with dummy titles/domains/etc) so that i could understand what you're attempting to do, please re-open with that information. Thanks!
