### ISSUE TITLE
[BUG] Managed RKE2 clusters are broken after upgrade to 2.9.1 when KDM is not updated to `release-v2.9`

### ISSUE THREAD

**Issue by riuvshyn** [rancher/rancher#46855]
**Rancher Server Setup**
- Rancher version: 2.9.1
- Installation option (Docker install/Helm Chart):
   - Helm chart
   - RKE2
   - 1.28.12

**Information about the Cluster**
- Kubernetes version:
- Cluster Type (Local/Downstream):
   - downstream RKE2 custom clusters

**User Information**
- What is the role of the user logged in?: Admin

**Describe the bug**
After upgrade from 2.8.3 rancher to 2.9.1 managed RKE2 custom clusters provisioned using [rancher2_cluster_v2](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster_v2) are broken because `/etc/rancher/rke2/config.yaml.d/50-rancher.yaml` configuration provided is completely ignored and was replaced most likely with a default parameters.

**To Reproduce**
1. provision managed rke2 1.28.x cluster with terraform [rancher2_cluster_v2](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster_v2) resource on rancher 2.8.3
2. Upgrade Rancher to latest 2.9.1

**Result**
After upgrade on a managed cluster rancher agent pods in `cattle-system` namespace getting replaced with new pods version `v2.9.1` and then something happens so `/etc/rancher/rke2/config.yaml.d/50-rancher.yaml` config is being replaced with just a few lines which makes cluster completely broken because it removes configured cilium and other critical components.

**Expected Result**
Rancher upgrade to 2.9.1 does not brake managed RKE2 clusters.

**Additional context**
I have noticed that after upgrade some cluster critical components such as kyverno started failing with this:
```
{"level":"error","ts":1724780897.1700578,"logger":"klog","caller":"leaderelection/leaderelection.go:332","msg":"error retrieving resource lock kyverno/kyverno: Get \"https://100.64.0.1:443/apis/coordination.k8s.io/v1/namespaces/kyverno/leases/kyverno\": tls: failed to verify certificate: x509: certificate is valid for 127.0.0.1, ::1, 172.23.103.172, 172.23.103.172, 10.43.0.1, not 100.64.0.1","stacktrace":"k8s.io/client-go/tools/leaderelection.(*LeaderElector).tryAcquireOrRenew\n\tk8s.io/client-go@v0.29.0/tools/leaderelection/leaderelection.go:332\nk8s.io/client-go/tools/leaderelection.(*LeaderElector).acquire.func1\n\tk8s.io/client-go@v0.29.0/tools/leaderelection/leaderelection.go:252\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\tk8s.io/apimachinery@v0.29.0/pkg/util/wait/backoff.go:226\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\tk8s.io/apimachinery@v0.29.0/pkg/util/wait/backoff.go:227\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tk8s.io/apimachinery@v0.29.0/pkg/util/wait/backoff.go:204\nk8s.io/client-go/tools/leaderelection.(*LeaderElector).acquire\n\tk8s.io/client-go@v0.29.0/tools/leaderelection/leaderelection.go:251\nk8s.io/client-go/tools/leaderelection.(*LeaderElector).Run\n\tk8s.io/client-go@v0.29.0/tools/leaderelection/leaderelection.go:208\ngithub.com/kyverno/kyverno/pkg/leaderelection.(*config).Run\n\tgithub.com/kyverno/kyverno/pkg/leaderelection/leaderelection.go:136\nmain.main.func2\n\tgithub.com/kyverno/kyverno/cmd/kyverno/main.go:462"}
```

Also pods in `cattle-system` ns failing same way:

```
time="2024-08-27T17:48:43Z" level=error msg="error syncing 'cattle-system/apply-system-agent-upgrader-on-ip-172-23-102-146-with-073-56173': handler system-upgrade-controller: Get \"https://100.64.0.1:443/apis/upgrade.cattle.io/v1/namespaces/cattle-system/plans/system-agent-upgrader\": tls: failed to verify certificate: x509: certificate is valid for 127.0.0.1, ::1, 172.23.102.15, 172.23.102.15, 10.43.0.1, not 100.64.0.1, requeuing"
```

**Comment by riuvshyn** [comment]
UPD: broken `/etc/rancher/rke2/config.yaml.d/50-rancher.yaml` is actually coming from rancher, I thought maybe something going on with rke2 but I have checked one of the machine plan secrets for the broken clusters `custom-7adbcc3e9769-machine-plan` and bad config for `/etc/rancher/rke2/config.yaml.d/50-rancher.yaml` is coming from there.
```
    {
      "content": "BAD_CONFIG_HERE",
      "path": "/etc/rancher/rke2/config.yaml.d/50-rancher.yaml"
    },
```

Also I have checked that `clusters.provisioning.cattle.io` resource does have `machineGlobalConfig:` defined with all necessary configuration options that are being completely ignored in machine plan

**Comment by riuvshyn** [comment]
I have compared cluster object before and after upgrade and noticed that after upgrade every cluster object was updated with: 
```
kind: Cluster
spec:
  rkeConfig:
    dataDirectories: {}
```

maybe that is causing this issue?
cc @jakefhyde  I have noticed this issue https://github.com/rancher/rancher/issues/46381 not sure if that is related...

**Comment by jakefhyde** [comment]
@riuvshyn Can you share a sanitized version of the `cluster.provisioning.cattle.io` resource for one of the affected clusters?

**Comment by riuvshyn** [comment]
also here is a sanitized version of config `/etc/rancher/rke2/config.yaml.d/50-rancher.yaml` from the affected cluster:
```
{
  "agent-token": "xxxx",
  "etcd-disable-snapshots": true,
  "etcd-s3": true,
  "etcd-s3-bucket": "etcd-backups-test06",
  "etcd-s3-endpoint": "s3.eu-central-1.amazonaws.com",
  "etcd-s3-folder": "etcd",
  "etcd-s3-region": "eu-central-1",
  "etcd-snapshot-retention": 6,
  "etcd-snapshot-schedule-cron": "0 */4 * * *",
  "kube-controller-manager-arg": [
    "cert-dir=/var/lib/rancher/rke2/server/tls/kube-controller-manager",
    "secure-port=10257"
  ],
  "kube-controller-manager-extra-mount": [
    "/var/lib/rancher/rke2/server/tls/kube-controller-manager:/var/lib/rancher/rke2/server/tls/kube-controller-manager"
  ],
  "kube-scheduler-arg": [
    "cert-dir=/var/lib/rancher/rke2/server/tls/kube-scheduler",
    "secure-port=10259"
  ],
  "kube-scheduler-extra-mount": [
    "/var/lib/rancher/rke2/server/tls/kube-scheduler:/var/lib/rancher/rke2/server/tls/kube-scheduler"
  ],
  "node-label": [
    "cattle.io/os=linux",
    "rke.cattle.io/machine=976d4be8-a32f-4e68-a30b-96be887875ba",
  ],
  "node-name": "ip-xxxx.eu-central-1.compute.internal",
  "node-taint": [
    "node-role.kubernetes.io/control-plane:NoSchedule",
    "node-role.kubernetes.io/etcd:NoExecute"
  ],
  "private-registry": "/etc/rancher/rke2/registries.yaml",
  "system-default-registry": "docker-hub.tw.ee",
  "token": "xxxxx"
}
```

**Comment by jakefhyde** [comment]
If you navigate to `https://<server-url>/v1-rke2-release/release`, what shows up under `v1.28.12+rke2r1` for `minChannelServerVersion`, `maxChannelServerVersion`, `serverArgs` and `agentArgs`? (note: navigating to `https://<server-url>/v1-rke2-release/release/v1.28.12+rke2r1` will return `403`, that is expected).

**Comment by riuvshyn** [comment]
```
{"type":"collection","links":{"self":"https://<server-url>/v1-rke2-release/release"},"actions":{},"resourceType":"release","data":[]}
```

**Comment by riuvshyn** [comment]
Oh, I had my `rke-metadata-config` pointed to `https://releases.rancher.com/kontainer-driver-metadata/release-v2.8/data.json` That is probably why.

**Comment by riuvshyn** [comment]
Validated again, update `rke-metadata-config` to 2-9 before upgrade fixes issues.

**Comment by jakefhyde** [comment]
@riuvshyn No problem, I'm glad we got to the root of the issue. I immediately gravitated towards KDM because of the small # of keys that were actually allowed through, looks like the rest were filtered out. I agree the UX is not great, and will bring that feedback to the team. What is the current state of the cluster? Was it able to recover correctly/are you having any operational issues because of this?

**Comment by riuvshyn** [comment]
@jakefhyde I had to rebuild all managed clusters, there was no recovery way for me. I was validating upgrade in test environment, so I didn't even bothered to try to recover, however from what I have seen the impact was devastating as it reverted all my custom configurations.

**Comment by viktordaniel** [comment]
Hi! We experienced today the same. And - unfortunately with full production outage. We managed to recover the downstream cluster in following steps: 
* fix the rke-metadata to 2.9
* wait until clusters connect to rancher again
* the important helm charts was missing (rke2-cilium, ingress, ...) because default config was deployed (rke2-canal). It was not working as well, because deleting of cilium chart stuck somewhere on finalizers, also
* we deleted rke2-cilium helm chart (kubectl -n kube-system delete helmchart rke2-cilium) and in terminating phase we removed the finalizers,
* afterwards, restart of rke2-server on one controlplane node triggered reinstallation of cilium,
* we have to restart sequentially all controlplane nodes to clean the state of the cluster,
* the downstream clusters recovered completly.

**Comment by Oats87** [comment]
> Validated again, update `rke-metadata-config` to 2-9 before upgrade fixes issues.
> 
> thanks @jakefhyde for pointing to the right direction. I wish rancher agent was abit more careful in case of misconfig like this and did not break managed clusters, ideally if that would just block cluster reconciliation with rancher and some meaningful error message on agent side, that would improve UX alot.

This is quite difficult as we rely on `KDM` to be our source of truth, and it *should* be dynamic. That being said, I believe we need to add some logic checks to the planner to ensure we don't send out a bad config in the case of a misconfigured KDM URL.

@jakefhyde have you fully RCA'ed why the configurations are getting clobbered?

**Comment by susesgartner** [comment]
Ticket #47071 - Test Results - ✅
---
 
| Scenario | Test Case | Result |
|---|---|---|
| 1. | Test upgrade with kdm change | PASS |
 
---
Verified with HA Helm on Rancher `v2.9-d1402ce585dfee99015d0129ad6ddcc598ce8e99-head`:
---
 
Scenario 1: Test upgrade with kdm change
---
1. Create a 2.8.3 rancher instance
2. Change the kdm version
3. Deploy a rke2 cluster
4. Upgrade the rancher instance to 2.9-head
5. Verify that a kdm error is displayed due to the kdm branch being wrong
 
Results: The error is observed
Screenshots:
<img width="909" alt="image" src="https://github.com/user-attachments/assets/4fc771d1-dd76-4da1-a4a8-b2e81a2248bb">


TODO: add testing for 2.8 and main
