### ISSUE TITLE
rancher-ha not loading 

### ISSUE THREAD

**Issue by iDiogenes** [rancher/rancher#4685]
Opening issue per the request of @deniseschannon from issue #4459 

Rancher Version:
  1.0.1
Docker Version:
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      linux/amd64

OS: 
ROS v0.4.4

Steps to Reproduce: 
  Create three hosts on AWS using ROS v0.4.4. The cloud config only has hostname set. On one of the hosts install rancher server. Setup an AWS ELB using AWS certificate manager for the SSL cert. Configure the ELB with the ProxyProtocal settings per the rancher/AWS instructions. Generate the config script and download it. Run the ha-config script on all three hosts. 

One point to mention is the cert for HA is auto generated as the cert for the ELB can't be downloaded because I am using AWS certificate manager and the cert can only be assigned to AWS resources.

[rancher-ha.zip](https://github.com/rancher/rancher/files/249326/rancher-ha.zip)

**Comment by LLParse** [comment]
Hi @iDiogenes it looks like zookeeper isn't achieving quorum, I suspect a Security Group problem.

Could you please provide the security group configuration applied to Rancher UI nodes and your ELB?

**Comment by iDiogenes** [comment]
The original security group was 443, 8080 and 22, which would after reviewing the docs again is not sufficient.  I did update the security group to allow all traffic, and I seem to be having the same ZeeKeeperServer not running issue.

**Comment by iDiogenes** [comment]
@LLParse I realized I also had restrictions on what hosts could access the database. I forgot to permit the two new hosts when going from standalone to HA. Looks like it has come up. Thanks!

**Comment by LLParse** [comment]
I'm glad you figured it out!
