### ISSUE TITLE
Drop internal /metrics/<clusterID> endpoint for downstream object counts

### ISSUE THREAD

**Issue by aruiz14** [rancher/rancher#46860]
**Is your feature request related to a problem? Please describe.**
While working on #41905, I discovered this endpoint used any caches available to populate those figures, often leading to unrealistic and inconsistent values.

**Describe the solution you'd like**
The route `/metrics/{clusterID}` is dropped, only keeping `/metrics`, ultimately removing one of the uses of downstream caches.

**Describe alternatives you've considered**
The initial attempt was to refactor it to stop using the caches (see https://github.com/rancher/rancher/pull/46787), but then we realize it's probably not worth it to maintain this undocumented and internal endpoint it if it's not being used.

Also, there is an overlap with the Diagnostics page, shows much better insights than this one.

**Additional context**
I couldn't find any active user for this feature. According to [this PR](https://github.com/rancher/rancher/pull/31814), which added this functionality, says the original motivation was to make this information available to the support team.
Also, I checked that possible other usages, like [csp-adapter](https://github.com/rancher/rancher/pull/31814), use the Prometheus endpoint (`/metrics`, not `/metrics/{clusterID}`) exclusively.

**Comment by aruiz14** [comment]
## Validation Template

## Root Cause
Undocumented and malfunctioning internal endpoint, with overlap with other feature like the Diagnostics page

## What was fixed, or what change have occurred
The `/metrics/<clusterID>` HTTP endpoint was removed, e.g. `/metrics/local` no longer works.

## Areas or cases that should be tested

### Removed endpoint is no longer accessible
 - [ ] Accessing /metrics/local should show not found.

### Prometheus endpoint remains untouched: serving `/metrics` only for allowed users
 - [ ] Unauthenticated access to `/metrics` should show `401 Unauthorized`.
 - [ ] Non-admin users with no additional permissions accessing `/metrics` should be shown `401 Unauthorized`.
 - [ ] Admin users accessing `/metrics` should be shown Prometheus metrics.
 - [ ] Non-admin users with "View Rancher Metrics" permissions granted accessing `/metrics` should be shown Prometheus metrics.

## What areas could experience regressions
None expected. I researched any possible users for this endpoint but found none.

**Comment by rancher-max** [comment]
### Validated using rancher `head` version

#### Version Information
<img width="747" alt="image" src="https://github.com/user-attachments/assets/46bc1195-9709-4464-a85b-353f7a49e65a">

#### Validations Performed

- Confirmed `/metrics/<clusterID>` is no longer accessible on both local and downstream clusters
- Confirmed navigating to `/metrics` while logged in as admin user successfully retrieves metrics
- Confirmed navigating to `/metrics` while not logged in results in `401 Unauthorized` error
- Confirmed navigating to `/metrics` using non-admin user also results in `401 Unauthorized` error
- Confirmed navigating to `/metrics` using a non-admin user with the `View Rancher Metrics` permission successfully retrieves the prometheus metrics
- Confirmed the old `/metrics/<clusterID>` endpoint is available on `v2.9-head`, and is no longer available after upgrading to v2.10 (`head`). Also confirmed all of the above in the upgraded environment.
