### ISSUE TITLE
No more logs, no more shell execution

### ISSUE THREAD

**Issue by AHaymond** [rancher/rancher#4687]
I would love to offer a bunch of useful insight into my individual circumstance but at the moment I am not sure what data that would be.

Suddenly I am unable to view logs through the rancher UI of any of my containers, and I can also no longer execute an interactive shell for any of my containers. I simply get a flash of the UI and it disappears. Any log windows just display an empty screen. Any help on this would be greatly appreciated.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.1.0-dev1` Cattle: `v0.160.3` UI: `v0.100.3` |
|Access|`localauth` `admin`|
|Route|`admin-tab.settings`|

**Comment by deniseschannon** [comment]
Did you upgrade to Docker 1.11 on the hosts?

**Comment by jiang1095** [comment]
I have the same problem. In my case, I installed Docker 1.11 first, then downgrade to 1.10.3(all data was deleted).

**Comment by LLParse** [comment]
Is your rancher UI behind a load balancer? If there is a firewall anywhere in the picture, could you provide the configuration for servers and agents?

**Comment by deniseschannon** [comment]
Can you check that the time stamp is the same for your server and agents?

http://docs.rancher.com/rancher/latest/en/faqs/troubleshooting/#help-i-cannot-execute-the-shell-or-view-logs-of-the-container-from-the-ui-how-does-rancher-access-the-shelllogs-of-a-container

**Comment by deniseschannon** [comment]
@AHaymond Please re-open if you have are still facing issues and can provide answers to the questions asked.

**Comment by tces1** [comment]
MARK, rancher host exec shell appears flash, logs show disconnected, mostly because the timestamp between the hosts is not synchronized, I spent an afternoon study and found it 😢

**Comment by lucasjkr** [comment]
I am stuck in the same situation. A container failed. When trying to start, the logs would not show in rancher. Deleted the offending container and created a new one. For an hour or so, Rancher would show that containers logs, but now, it shows the logs up until about 30 minutes ago, and then says "Disconnected". The thing is, the container itself is running fine. But I won't be able to tell if its having problems due to this.
