### ISSUE TITLE
[Backport 2.9] use fixed stream server bind address for cri-dockerd

### ISSUE THREAD

**Issue by Sahota1225** [rancher/rancher#46871]
Backport for # https://github.com/rancher/rancher/issues/46870

SURE-8866

**Comment by rishabhmsra** [comment]
RKE standalone checks:
-
Case 1 :
- Using rke binary v1.6.2-rc.2, provisioned v1.30.4-rancher1-1, v1.29.8-rancher1-1 and v1.28.13-rancher1-1 node driver RKE1 cluster(1-cp, 1-e, 1-w)
- Validated the stream server bind address and port, it's set to `localhost:10010 (LISTEN)`

Case 2 :
- Using rke binary v1.6.2-rc.2, provisioned v1.30.4-rancher1-1, v1.29.8-rancher1-1 and v1.28.13-rancher1-1 node driver RKE1 cluster(1-cp, 1-e, 1-w)
- Added following fields `cri_dockerd_stream_server_address: 127.0.0.1` and `cri_dockerd_stream_server_port: 10011` in cluster.yml.
- Updated cluster and re-validated the address and port, it's updated to above new values.

Rancher checks:
-
Case 1 :
- On rancher v2.9-head(eddb8ca2c36856c4b22db038ee209a3567464d9c-head), provisioned RKE1 v1.30.4-rancher1-1, v1.29.8-rancher1-1 and v1.28.13-rancher1-1 node driver cluster.
- Validated the stream server bind address and port, it's set to `localhost:10010 (LISTEN)`

Case 2 :
- On rancher v2.9-head(eddb8ca2c36856c4b22db038ee209a3567464d9c-head), provisioned RKE1 v1.30.4-rancher1-1, v1.29.8-rancher1-1 and v1.28.13-rancher1-1 node driver cluster.
- Added following fields `cri_dockerd_stream_server_address: 127.0.0.1` and `cri_dockerd_stream_server_port: 10011` after editing cluster yaml.
- Updated cluster and re-validated the address and port, it's updated to above new values. Kubelet also restarted.

Case 3 :
- On rancher v2.9.1, provisioned RKE1 v1.30.3-rancher1-1, v1.29.7-rancher1-1 and v1.28.12-rancher1-1 node drvier cluster.
- Validated the stream server bind address and port and it was not set to default value.
- Upgraded rancher server to v2.9-head.
- Upgraded cluster to v1.30.4-rancher1-1, v1.29.8-rancher1-1 and v1.28.13-rancher1-1.
- Validated stream server bind address and port, it's set to default value `localhost:10010 (LISTEN)` and kubelet was restarted.
