### ISSUE TITLE
[BUG] Unable to authenticate with AzureAD to cluster

### ISSUE THREAD

**Issue by idogada-akamai** [rancher/rancher#46879]
**Rancher Server Setup**
- Rancher version: 2.9.1
- Installation option (Docker install/Helm Chart): Helm 
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): AKS 1.30

**Information about the Cluster**
- Kubernetes version: 1.30
- Cluster Type (Local/Downstream):  Local
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): Admin
  - If custom, define the set of permissions:

**Describe the bug**
As described [here](https://ranchermanager.docs.rancher.com/reference-guides/cli-with-rancher/kubectl-utility#authentication-with-kubectl-and-kubeconfig-tokens-with-ttl), I have disabled kubeconfig token generation, and tried to download the cluster kubeconfig.
When inspecting the kubeconfig.yaml file I see the following under `users[0].user.exec`:
```yaml
exec:
  apiVersion: client.authentication.k8s.io/v1beta1
  args:
    - token
    - --server=rancher.mydomain.com
    - --user=local
  command: rancher
``` 
When I use that config I am not able to login, bellow is the output
```
k get pods                   
https://rancher.mydomain.com/v3-public/authProviders 
Auth providers:
0 - azureADProvider
1 - localProvider 
Select auth provider: 0

To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code AXNE6HRDC to authenticate.
 
FATA[0007] oauth2: "invalid_request" "AADSTS900144: The request body must contain the following parameter: 'code'. Trace ID: XXXXXXXXXXX Timestamp: 2024-08-29 11:34:19Z" "https://login.microsoftonline.com/error?code=900144" 
E0829 14:34:19.571450   96500 memcache.go:265] couldn't get current server API group list: Get "https://rancher.mydomain.com/k8s/clusters/local/api?timeout=32s": getting credentials: exec: executable rancher failed with exit code 1
https://rancher.mydomain.com/v3-public/authProviders 
```

**To Reproduce**
* Enable SSO integration with AzureAD
* Disable kubeconfig token generation
* Download a cluster kubeconfig
* Use that kubeconfig to run any `kubectl` command

**Result**
Rancher CLI exits with status code of 1 before I can put my code into https://microsoft.com/devicelogin

**Expected Result**
Rancher can get the token, and the kubectl command completes successfully.

**Comment by dasarinaidu** [comment]
I tried with CLI version v2.9.0 on a rancher version v2.9.1 ; The issue is not reproducible, I am able to connect with CLI and get the token and pods with kubectl commands.

When you run `k get pods` I did not see the config is saving on to cli2.json ; you may have to remove the old cli2.json file and revalidate the issue.

```
kubectl get pods -A
INFO[0000] Saving config to /Users/aaaaaaaa/.rancher/cli2.json
https://rancher.mydomain.com/v3-public/authProviders
Auth providers:
0 - azureADProvider
1 - localProvider
Select auth provider: 0
```

To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code AAAAAAA to authenticate.

**Comment by idogada-akamai** [comment]
@dasarinaidu 
That's what I am trying to do, but I get the error before I have time to do that....

**Comment by idogada-akamai** [comment]
@dasarinaidu 
I also tried to delete the cli2.json file, but I am still getting the same error

```
❯ k get pods
INFO[0000] Saving config to /Users/myuser/.rancher/cli2.json
https://rancher.mydomain/v3-public/authProviders
Auth providers:
0 - azureADProvider
1 - localProvider
Select auth provider: 0

To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code AGCDVTBNC to authenticate.

FATA[0008] oauth2: "invalid_request" "AADSTS900144: The request body must contain the following parameter: 'code'. Trace ID: XXXX Correlation ID: XXXXXX Timestamp: 2024-09-01 09:13:40Z" "https://login.microsoftonline.com/error?code=900144"
E0901 12:13:39.911534   69856 memcache.go:265] couldn't get current server API group list: Get "https://rancher.mydomain/k8s/clusters/local/api?timeout=32s": getting credentials: exec: executable rancher failed with exit code 1
https://rancher.mydomain/v3-public/authProviders
Auth providers:
0 - azureADProvider
1 - localProvider
Select auth provider:
```

**Comment by enrichman** [comment]
HI @idogada-akamai, thanks for reporting this. It could be related to a misconfiguration on the Azure side.  

Have you enabled the [Public Client Flows](https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/authentication-config/configure-azure-ad#4-allow-public-client-flows) in your app?

**Comment by idogada-akamai** [comment]
@enrichman 
Yes, it is enabled and configured as the guide suggests
![image](https://github.com/user-attachments/assets/7c4f02c4-ae21-44e1-a943-b2f133b0a724)

**Comment by enrichman** [comment]
Thanks for confirming it. From the error it looks like the endpoint used to poll the access token requires the `code` parameter. Checking the [Microsoft doc](https://learn.microsoft.com/en-us/entra/identity-platform/v2-oauth2-device-code#protocol-diagram) it should not be mandatory for the device flow, that's why I'm thinking about some configuration issue.

What kind of endpoints are you using (_standard_, _china_ or _custom_)?

**Comment by idogada-akamai** [comment]
@enrichman 
We are using Terraform to setup the AzureAD auth provider, to I can only do custom.
That's how we've set it up:
```
Endpoint:	https://login.microsoftonline.com/
Graph Endpoint:	https://graph.microsoft.com/
Token Endpoint:	https://login.microsoftonline.com/<tenant_id>/oauth2/token
Auth Endpoint:	https://login.microsoftonline.com/<tenant_id>/oauth2/authorize
```

**Comment by idogada-akamai** [comment]
@enrichman 
That's the Terraform code used to create it
```hcl
resource "rancher2_auth_config_azuread" "azuread" {
  application_id     = azuread_application.rancher-reg.client_id
  application_secret = azuread_application_password.client-secret.value
  auth_endpoint      = "https://login.microsoftonline.com/${data.azurerm_client_config.current.tenant_id}/oauth2/authorize"
  graph_endpoint     = "https://graph.microsoft.com"
  rancher_url        = "${var.server_url}/verify-auth-azure"
  tenant_id          = data.azurerm_client_config.current.tenant_id
  token_endpoint     = "https://login.microsoftonline.com/${data.azurerm_client_config.current.tenant_id}/oauth2/token"
}
```

**Comment by enrichman** [comment]
@idogada-akamai what's the output of https://rancher.mydomain.com/v3-public/azureADProviders/azureAD ?

If there is some information missing, or wrong, about the deviceAuthURL we will maybe need to update the Terraform provider. Otherwise I'll try to setup a Rancher instance with Terraform to see if we can replicate this.

**Comment by idogada-akamai** [comment]
@enrichman 
After using the v2 addresses for auth and token it worked!
```
auth_endpoint      = "https://login.microsoftonline.com/<tenant_id>/oauth2/v2.0/authorize"
token_endpoint     = "https://login.microsoftonline.com/<tenant_id>/oauth2/v2.0/token" 
```

The only question left is, how can I set azureAD as the default provider so I don't get asked which one to use?

**Comment by enrichman** [comment]
Glad to hear that. :)

We are discussing about this, and there are a couple of issues about "discouraging" the use of the local provider, if an external one is enabled.

At the moment it should be possible specifying the `--auth-provider` flag, so editing the kubeconfig adding this flag should work:

```yaml
exec:
  apiVersion: client.authentication.k8s.io/v1beta1
  args:
    - token
    - --server=rancher.mydomain.com
    - --user=local
    - --auth-provider=azureAD
  command: rancher
```
