### ISSUE TITLE
[2.10] use fixed stream server bind address for cri-dockerd 

### ISSUE THREAD

**Issue by Sahota1225** [rancher/rancher#46870]
Tracking the rke # https://github.com/rancher/rke/issues/3656

SURE-8866

**Comment by vardhaman22** [comment]
Whenever a branch in rancher/rke is created for v2.10, we need to make sure that fix for this issue exist in that branch.

**Comment by rishabhmsra** [comment]
RKE standalone checks:
-
Case 1 :
- Using rke binary v1.7.0-rc.7, provisioned v1.31.2-rancher2-1 node driver RKE1 cluster(1-cp, 1-e, 1-w)
- Validated the stream server bind address and port, it's set to `localhost:10010 (LISTEN)`

Case 2 :
- Using rke binary v1.7.0-rc.7, provisioned v1.31.2-rancher2-1 node driver RKE1 cluster(1-cp, 1-e, 1-w)
- Waited for cluster to provision successful.
- Added following fields `cri_dockerd_stream_server_address: 127.0.0.1` and `cri_dockerd_stream_server_port: 10011` in cluster.yml.
- Updated cluster and re-validated the address and port, it's updated to above new values.

Case 3:
- Created cluster.yml with k8s v1.31.2-rancher2-1 and rke binary v1.7.0-rc.7, also added following fields `cri_dockerd_stream_server_address: 127.0.0.1` and `cri_dockerd_stream_server_port: 10011`.
- Ran rke up, and after successful provisioning validated address and port, it was set to above values.

Rancher checks:
-
Case 1 :
- On rancher v2.10-1c2de6a7653883093c7b5703cb3d3c19bac4e2e7-head, provisioned RKE1 v1.31.2-rancher2-1 node driver cluster.
- Validated the stream server bind address and port, it's set to `localhost:10010 (LISTEN)`

Case 2 :
- On rancher v2.10-1c2de6a7653883093c7b5703cb3d3c19bac4e2e7-head, provisioned RKE1 v1.31.2-rancher2-1 node driver cluster.
- Once the cluster was Active, added following fields `cri_dockerd_stream_server_address: 127.0.0.1` and `cri_dockerd_stream_server_port: 10011` after editing cluster yaml.
- Updated cluster and re-validated the address and port, it's updated to above new values. Kubelet also restarted.
