### ISSUE TITLE
Update Frameworks Branches for new versioning approach

### ISSUE THREAD

**Issue by MbolotSuse** [rancher/rancher#46899]
In order to better support the new versioning approach, a few Frameworks repos will need to have new branches created for them.  The below list identifies the repos, the old branches, and the new branches which should be created for them. Note that the old branches should not be deleted at this time until we can confirm that there were no errors in the migration.

[Wrangler](https://github.com/rancher/wrangler):
- [x] Change master to main. 
  - [x] Set main as the default branch. 
  - [x] Add main to the branch protection rules.
- [x] Change release-2.2 to release/v2
  - [x] Add release/v* to the branch protection rules.
 
[Lasso](https://github.com/rancher/lasso):
- [x] Change master to main. 
  - [x] Set main as the default branch. 
  - [x] Add main to the branch protection rules.
- [x] Branch release/v0.1 from the commit currently used by the latest release of wrangler 2.2 ([wrangler](https://github.com/rancher/wrangler/blob/release-2.2/go.mod#L11) [lasso](https://github.com/rancher/lasso/commit/d87ec407d9412c4392dc4a88e8baf71b0dc2694d) ).
  - [x]  Add release/v* to the branch protection rules.
 
[API Server](https://github.com/rancher/apiserver):
- [x] Change release/v2.9 to release/v0.3.
- [x] Change release/v2.8 to release/v0.2.
- [x] Change release/v2.7 to release/v0.1.
- [x] Ensure that the new branches are covered by the existing branch protection rule. If they aren't, add a new rule to include them.

[Norman](https://github.com/rancher/norman):
- [x] Change release/v2.9 to release/v0.3.
- [x] Change release/v2.8 to release/v0.2.
- [x] Change release/v2.7 to release/v0.1.
- [x] Ensure that the new branches are covered by the existing branch protection rule. If they aren't, add a new rule to include them.

[Steve](https://github.com/rancher/steve):
- [x] Change release/v2.9 to release/v0.3.
- [x] Change release/v2.8 to release/v0.2.
- [x] Change release/v2.7 to release/v0.1.
- [x] Ensure that the new branches are covered by the existing branch protection rule. If they aren't, add a new rule to include them.

[DynamicListener](https://github.com/rancher/dynamiclistener):
- [x] Change master to main. 
  - [x] Set main as the default branch. 
  - [x] Add main to the branch protection rules.

[RemoteDialer](https://github.com/rancher/remotedialer):
- [x] Change master to main. 
  - [x] Set main as the default branch. 
  - [x] Add main to the branch protection rules.
- [x] Create `release/v0.3` from the last tag for the 0.3 line ([v0.3.2](https://github.com/rancher/remotedialer/tree/v0.3.2)).
  - [x] Ensure that the new branches is covered by the existing branch protection rule. If it isn't, add a new rule to include them.

**Comment by tomleb** [comment]
Tested the following on a norman fork to see the potential impact:

Renamed my norman fork branch `release/v2.9` to `release/v0.3`. This results in:
- The browser automatically redirects links pointing to the release/v2.9 branch to the new release/v0.3 branch
- New git clone has no info about `release/v2.9`. eg: `git checkout release/v2.9` no longer works, which could be a problem for CI.
- Old local git repositories are still able to pull from their local release/v2.9 branch, it will just never update to new code in the release/v0.3 one

It might be less impacting to keep the old branches there and just create new branches pointing at the same commit. We can then add a message to the README of the old branches to let people know we've moved and we could try to add branch protection rules for those old branches to disallow any changes. :shrug:
