### ISSUE TITLE
What are benefits or downsides in using Swarm / Kubernetes / Mesos / Cattle ?

### ISSUE THREAD

**Issue by virtuman** [rancher/rancher#4689]
**Rancher Version**: 1.1.0.dev1

**Docker Version**: 1.11

**OS**: CentOS7

**Question**: 
Is there any benefit in NOT using Cattle as the environment and use other available orchestration mechanisms - or do they exist for support only and not as a fully functional replacement for Cattel and Cattle should be used acorss the board?

I just tried to setup a swarm cluster in Rancher and ran into an issue where I couldn't SCALE any services via Rancher's UI and had no ability to install any Load Balancer Service that would normally be available under "STACKS" items.

Can someone describe limitations of these different orchestration methods within rancher, or am i just missing these functionalities and Scaling, Load Balancing and other neat things are available across all 4 approaches?

Most basic example of what I'm trying to achieve:
- setup load balanced frontend website (ie: wordpress); or,
- setup mariadb galera where each node is a primary server and have one LB access point

i have an infinite pool of examples, but i think it kinda sort of explains what I was missing in the swarm setup.

**Comment by vincent99** [comment]
302 https://forums.rancher.com/t/what-are-benefits-or-downsides-in-using-swarm-kubernetes-mesos-cattle/2693
