### ISSUE TITLE
Add client IP as Template variable [feature req]

### ISSUE THREAD

**Issue by sshipway** [rancher/rancher#4690]
It would be useful to be able to use $CLIENT_IP in a template, and have it replaced by the IP address of the client being used to deploy the template.

The use case for this is X-Windows client applications.  We have a large app, that users currently run by using VNC to remote-control a virtual machine.  This is necessary because of the CPU requirements of the app, and for licensing restrictions.   It is possible to run the app inside a container with XWindows sending the display to the users workstation; however they need to manually specify the address of their workstation on service creation.  It would be helpful if it could be set to default to the client browser IP, for the benefit of users who do not know their IP address or how to find it.

Making the CLIENT_IP exposed to the template would help with any future XWindows app, or any other applications that needs to interact with a desktop.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
