### ISSUE TITLE
Update Norman's CI and Renovate Config

### ISSUE THREAD

**Issue by MbolotSuse** [rancher/rancher#46903]
In order to support the new versioning approach, norman's CI and renovate config needs to be updated to target the correct branches. The below contains a list of the required tasks.

- [x] Change the renovate config to target `main`, `release/v0.4`, `release/v0.3`, `release/v0.2`, and `release/v0.1`. Remove the old branches from the current renovate config.
- [x] Update the CI to produce tagged releases when a tag is pushed.
  - [x] The Github release should include release notes generated from the commit log.
  - [x] RC tags (e.x. `v0.1.2-rc1`) should produce a release with release notes, but this should be marked as a pre-release.
  - [x] Tags produced from `main`, `release/v0.3`, `release/v0.2`, and `release/v0.1` should trigger the CI to create a release. 
- [x] Add a versioning policy in `VERSION.md` for `main`, `release/v0.4`, `release/v0.3`, `release/v0.2`, and `release/v0.1` which contains the following content:

"
Norman follows a pre-release (v0.x) strategy of semver. There is no compatibility between releases, and new releases are meant to be strictly compatible with a single version of Rancher. The current supported versions of Norman are as follows:

The current supported release lines are:

| Norman Branch | Norman Minor version | Matching Rancher Version |
|--------------------------|------------------------------------|------------------------------------------------|
| main | v0.5 | v2.11 |
| release/v0.4 | v0.4 | v2.10 |
| release/v0.3 | v0.3 | v2.9 |
| release/v0.2 | v0.2 | v2.8 |
| release/v0.1 | v0.1 | v2.7 |

"

**Comment by tomleb** [comment]
Done. Closing.
