### ISSUE TITLE
UDP packets do not always cross Rancher 10.42.x.x network between Hosts

### ISSUE THREAD

**Issue by sshipway** [rancher/rancher#4691]
Rancher Version: 1.1.0-dev1
Docker Version: 1.9.1 and 1.10.3
OS:  CoreOS
Steps to Reproduce: 
Create new stack
Start one service "server" with sshipway/xpilot:latest, with command "-server",  1 instance
Start another service "client" with sshipway/xpilot:latest, env vars SERVER=server, DISPLAY=x.x.x.x:0 and linking service server=server.  Make x.x.x.x the IP of your X-Windows workstation.
Results: 
This application communicates via UDP.  Client will connect if both are on the same host, but will usually not connect if on different hosts
Expected:
Client should connect no matter which host it is on, as it shoudl go via the tunnelled network

This may be a coreOS networking issue.  Have tried with CoreOS and Docker 1.9.1 and 1.10.3, and with RancherOS and docker 1.9.1.  Sometimes it works, often it does not.  It seems to be less likely to work when going TO a CoreOS host with Docker 1.10.3, but this may just be anecdotal.   In the cases where it does not work, I am also unable to ping the remote container IP from within the client container

**Comment by ibuildthecloud** [comment]
@sshipway We will address this right after Rancher 1.1 releases.  Unfortunately didn't make it in the 1.1 timeframe, but if your cool with dev builds, you shouldn't have to wait very long.  The issue is because the MTU of the container sending UDP must be lower than the MTU of the network agent.  For TCP, MTU Path discovery adjusts this correctly but for UDP there is no such thing so if you send 1500 MTU UDP packet it gets dropped.  Docker doesn't provide a way for different containers to have different MTU sizes so we must address this with a custom network driver.

**Comment by sshipway** [comment]
Great to know the cause and potential fix is known.  I'm off this project now but the team taking over from me will be keeping an eye on it.  Thanks

**Comment by ArneCoder** [comment]
+1 

Any news on this?

**Comment by leodotcloud** [comment]
This is already in the TODO list for one of the upcoming releases.

**Comment by opHASnoNAME** [comment]
Is there any workaround available until the new release?

**Comment by deniseschannon** [comment]
@opHASnoNAME The workaround would be to schedule the containers on the same host.

**Comment by sshipway** [comment]
@opHASnoNAME As @deniseschannon said, use the scheduling rules to give the containers affinity.  The Xpilot template in the community catalogue does this - sets a label on the server container, and uses a soft affinity scheduling rule to try and put the clients on the same host in order to work around the problem.

**Comment by gevert** [comment]
Does this issue also affect UDP connections from outside of rancher/docker to a port exposed on a rancher host? I'm experiencing similar issues.

**Comment by leodotcloud** [comment]
Changes have been implemented here: https://github.com/rancher/cni/commit/4f858a10ae7c2ce3304b4d422509ca9bd9793a0a

Currently these changes are working for Kubernetes Environment and Cattle Environment will be able to leverage these changes once @ibuildthecloud pulls in CNI support for Cattle.
