### ISSUE TITLE
[2.8] Update ingress-nginx to the latest applicable version

### ISSUE THREAD

**Issue by mitulshah-suse** [rancher/rancher#46928]
Backport of https://github.com/rancher/rancher/issues/46565 to v2.8.x line of releases

**Comment by rishabhmsra** [comment]
Fresh install:
- Validated on rancher v2.8-head(9c45a84)
- Provisioned v1.28.13-rancher1-1 on all CNIs - weave/calico/flannel/canal
- Validated the nginx-ingress-controller version and it's updated to - `rancher/nginx-ingress-controller:nginx-1.11.2-rancher1`
- Also created nginx deployment with clusterip svc and port 80
- Created ingress pointing to nginx pod.
- Accessed worker-node-ip/index.html and got nginx welcome page

Upgrade checks:
- Created rancher v2.8.7
- Provisioned v1.28.12-rancher1-1 on all CNIs - weave/calico/flannel/canal
- Upgrade rancher to v2.8-head(9c45a84)
- Validated the nginx-ingress-controller version and it's updated to - `rancher/nginx-ingress-controller:nginx-1.11.2-rancher1`
- Also created nginx deployment with clusterip svc and port 80
- Created ingress pointing to nginx pod.
- Accessed worker-node-ip/index.html and got nginx welcome page- 

KDM checks also passed successfully.
