### ISSUE TITLE
[RFE]  Openstack Multiple Networks in Machine Template

### ISSUE THREAD

**Issue by zachelnet** [rancher/rancher#46927]
Hi everyone,

**Is your feature request related to a problem? Please describe.**
We use Rancher to deploy Kubernetes in OpenStack and wanted to implement Manila Cephfs with a second external storage network for Cephfs.
For security reasons, it's not possible to route this network into the default OpenStack network.
So, we'll need to attach a second network interface to the machines running in OpenStack. 

**Describe the solution you'd like**
It's possible to add the function to declare multiple networks in the machine template of OpenStack to automatically attach different networks upon deployment.

**Describe alternatives you've considered**
We manually added the storage network in OpenStack.

**Comment by mikejoh** [comment]
We've had the same challenge, we solved it by having a in-cluster controller that attaches storage network ports to each node when they're added to the cluster. 

I _think_ that the limitations would be in [CAPI](https://github.com/kubernetes-sigs/cluster-api) or more specifically in [CAPO](https://github.com/kubernetes-sigs/cluster-api-provider-openstack) and not necessarily in Rancher. With that said i haven't been digging around in CAPI+CAPO enough to understand what we can do with e.g. networks and other resources!

**Comment by zachelnet** [comment]
Hi @mikejoh,

Thanks for your answer, sounds interesting with the in-cluster controller, how did you implement that.

Via CAPI and CAPO I was looking for a way to add multiple networks and found this,

https://cluster-api-openstack.sigs.k8s.io/clusteropenstack/configuration#multiple-networks

But Rancher used the following type of "kind: OpenstackMachineTemplate" with the "apiVersion: rke-machine.cattle.io/v1" and not the one from CAPO.

**Comment by mikejoh** [comment]
> Hi @mikejoh,
> 
> Thanks for your answer, sounds interesting with the in-cluster controller, how did you implement that.
> 
> Via CAPI and CAPO I was looking for a way to add multiple networks and found this,
> 
> https://cluster-api-openstack.sigs.k8s.io/clusteropenstack/configuration#multiple-networks
> 
> But Rancher used the following type of "kind: OpenstackMachineTemplate" with the "apiVersion: rke-machine.cattle.io/v1" and not the one from CAPO.

We used [`kubebuilder`](https://book.kubebuilder.io/) to bootstrap a simple controller that attaches ports from networks we provide via OpenStack. We stripped all of the CRD handling and generation since we want to reconcile on `Node` objects and communicate the result by manipulating `annotations`. This has worked out so far, the code isn't open sourced unfortunately, it probably could be though.

Interesting find! I've not fully understood what's going on between the Rancher OpenStack CRDs and the upstream CAPO ones. But this is definitely worth digging into a bit more!

**Comment by zachelnet** [comment]
I think for the future we goging to capi and capo with Rancher Turtles when this is stable.

For now we used the system-upgrade-controller to exec script for openstack-cli.
