### ISSUE TITLE
Update logging image dependencies to match upstream

### ISSUE THREAD

**Issue by jbiers** [rancher/rancher#46924]
**Is your feature request related to a problem? Please describe.**
Some image dependencies for rancher-logging have recently been updated to fix CVE reports:

https://github.com/rancherlabs/image-scanning/issues/1366
https://github.com/rancherlabs/image-scanning/issues/3143
https://github.com/rancherlabs/image-scanning/issues/2764

The goal for this issue is to make sure all other image versions match up with upstream.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jbiers** [comment]
Blocked by: https://github.com/rancherlabs/eio/issues/2614

**Comment by pankajsqe** [comment]
Pass : addition of new config-reloader image was successful rancher/mirrored-kube-logging-config-reloader:v0.0.5 along with logging chart version updated to 105.0.0-rc.1+up4.8.0.

rancher : v2.10-head
cluster RKE2
rancher-alerting-drivers:105.0.0-rc.1
rancher-logging:105.0.0-rc.1+up4.8.0
![Image](https://github.com/user-attachments/assets/17cec7c1-57bd-400d-a67d-ed2900c689e5)
![Image](https://github.com/user-attachments/assets/186e6a2f-35a4-45fe-a485-e2eb6133dac6)
![Image](https://github.com/user-attachments/assets/3da88c71-faec-4602-91c5-0f6d27e92845)
