### ISSUE TITLE
can't add a host into kubernetes environment

### ISSUE THREAD

**Issue by logicigam** [rancher/rancher#4692]
when I try to add the first host,here comes the errors:
Starting agent for 5494CC11D4413E356006
INFO: Access Key: 5494CC11D4413E356006
INFO: Config URL: http://172.17.32.16:5000/v1
INFO: Storage URL: http://172.17.32.16:5000/v1
INFO: API URL: http://172.17.32.16:5000/v1
INFO: IP: 172.17.32.59
INFO: Port:
INFO: Required Image: rancher/agent:v1.0.1
INFO: Current Image: rancher/agent:v1.0.1
INFO: Using image rancher/agent:v1.0.1
INFO: Downloading agent http://172.17.32.16:5000/v1/configcontent/configscripts
{"id":"7931a764-df68-4267-abfe-218de1dd5ed0","type":"error","links":{},"actions":{},"status":404,"code":"Not Found","message":"Not Found","detail":null}
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

seems like some config file can't be found.
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.1.0-dev1` Cattle: `v0.160.3` UI: `v1.0.7` |
|Access|`localauth` `admin`|
|Route|`k8s-tab.waiting`|

**Comment by deniseschannon** [comment]
@logicigam Are you able to add hosts in other types of environments?

**Comment by alena1108** [comment]
@deniseschannon doesn't look related to k8s; the host is being added just the way it would have been added to a regular cattle setup.

**Comment by deniseschannon** [comment]
@logicigam Please re-open if you are still facing this issue. One test would be to see if you can add hosts in other environments (as it doesn't sound like it will be k8s environment specific).

If you are still facing issues, when you re-open, can you also include how/where you're adding these hosts into Rancher server? 

Where is your Rancher server hosted? What OS are you using?
