### ISSUE TITLE
io.rancher.host.external_dns_ip label drops from host when new host label added

### ISSUE THREAD

**Issue by makhnmik** [rancher/rancher#4695]
Rancher Version:
1.0.1
Docker Version:
1.11.0, build 4dc5990
OS: 
Ubuntu 14.04.4 LTS
Steps to Reproduce: 
Set io.rancher.host.external_dns_ip=your_host_external_ip, setup Amazon route53 service, check that  records in route53 are pointing to external ip's and and any ordinary host label
Results: 
route53 records point to internal ip again.
Expected:
Only external ip is used in route53 records after io.rancher.host.external_dns_ip label setup

**Comment by smazurov** [comment]
Its also worth noting that the `external_dns_ip` label does not show up when editing the host. You have to check the api response for that host to see that its still set. This issue may stem from that (if API expects a `PUT` with all existing labels + new one).

**Comment by deniseschannon** [comment]
This is actually fixed in v1.0.1-dev1. The issue was that the `io.rancher.host` labels were not showing up in the UI (but were still in the API), so when you added a new label, all the `io.rancher.host` labels were being overriden/lost.
