### ISSUE TITLE
[v2.9] [BUG] SAML provider search always returns users

### ISSUE THREAD

**Issue by pmatseykanets** [rancher/rancher#46959]
Backport of #44441

**Comment by joesims22** [comment]
Validated on v2.9-head id `aa0df7e`. 

| \#  | Priority | Description & Link                                        | PASS/FAIL |
| --- | -------- | --------------------------------------------------------- | --------- |
| 1   | P0       | Verify group principle is used when assigning global role to SAML group                        | ✅ PASS    |
| 2   | P0       | Verify user and group principal are used when adding SAML user to cluster                        | ✅ PASS    |
| 3   | P0      | Verify user and group principal are used when adding SAML user to project                                  | ✅ PASS    |
| 4   | P0       | Verify searching by all/group/user principalType returns the correct principalType via API                        | ✅ PASS    |
| 5   | P0       | Verify group principle is used when searching for a group to assign a global role to via API                                  | ✅ PASS    |
| 6   | P0       | Upgrade: Verify group principle is used when assigning global role to SAML group | ✅ PASS    |
| 7   | P0       | Upgrade: Verify user and group principal are used when adding SAML user to cluster upon upgrading Rancher                                      | ✅ PASS    |
| 8   | P0       | Upgrade: Verify user and group principal are used when adding SAML user to project upon upgrading Rancher                                      | ✅ PASS    |
