### ISSUE TITLE
[main] [BUG] CATTLE_AGENT_FALLBACK_PATH environment variable is way too prominent for custom clusters and can lead to confusion

### ISSUE THREAD

**Issue by Oats87** [rancher/rancher#46963]
See original release/v2.9 issue here: https://github.com/rancher/rancher/issues/46775

**Comment by susesgartner** [comment]
Ticket #46963 - Test Results - ✅ 
---
 
| Scenario | Test Case | Result |
|---|---|---|
| 1. | Provisioning Test | PASS  |
| 2. | Upgrade restore test | PASS  |
 
---
Verified with (HA Helm or Docker) on Rancher `v2.10-head`:
---

Scenario 1: Verify CATTLE_AGENT_FALLBACK_PATH
---
NOTE: performed on RKE2/K3s and custom/node driver

1. Provision a 3 node cluster with data/dir set
2. Verify the cluster comes up active and all pods are in a stable state
3. Verify that the CATTLE_AGENT_FALLBACK_PATH is not present in the registration command for custom clusters
4. Verify that all data/dir's exist and contain the appropriate files
 
Results: All verification steps passed
 
---

Regression check 
Scenario 2: Upgrade restore test 
---
NOTE: performed on RKE2/K3s and custom/node driver

1. Provision a 3 node cluster with data/dir set
2. Take a snapshot
3. Upgrade the k8s version
4. Restore the snapshot
5. Verify that the cluster comes up active and all pods are in a stable state
6. Verify that all data/dir's exist and contain the appropriate files.

Results: All verification steps passed
