### ISSUE TITLE
Rancher kubernetes on AWS stuck in pending state

### ISSUE THREAD

**Issue by AlmaasAre** [rancher/rancher#4696]
I have created a auto-scale group in AWS that spawns a rancher-server v1.0.1. The server boots up fine, and i have managed to configure SSL that terminates at the AWS ELB. 

This is the output from kubelet when i register one host:

```
5/5/2016 3:25:04 PMI0505 14:25:04.497298    6111 rancher.go:541] ExternalID [rancher]
5/5/2016 3:25:04 PMI0505 14:25:04.497321    6111 rancher.go:547] InstanceID [rancher]
5/5/2016 3:25:04 PMI0505 14:25:04.590876    6111 rancher.go:547] InstanceID [rancher]
5/5/2016 3:25:04 PMI0505 14:25:04.654997    6111 rancher.go:547] InstanceID [rancher]
5/5/2016 3:25:04 PMI0505 14:25:04.718983    6111 kubelet.go:1086] Adding node label from cloud provider: beta.kubernetes.io/instance-type=rancher
5/5/2016 3:25:04 PMI0505 14:25:04.719048    6111 kubelet.go:1097] Adding node label from cloud provider: failure-domain.beta.kubernetes.io/zone=FailureDomain1
5/5/2016 3:25:04 PMI0505 14:25:04.719061    6111 kubelet.go:1101] Adding node label from cloud provider: failure-domain.beta.kubernetes.io/region=Region1
5/5/2016 3:25:14 PME0505 14:25:14.242718    6111 event.go:202] Unable to write event: 'Post http://master/api/v1/namespaces/default/events: dial tcp 10.42.53.56:80: connection refused' (may retry after sleeping)
5/5/2016 3:25:20 PMI0505 14:25:20.138680    6111 kubelet.go:1165] Successfully registered node rancher
```
However, things get funky when i try to add more hosts. When i try to add more than one host, i get the following error in kubelet:

```
5/5/2016 2:21:03 PMI0505 13:21:03.221047    3224 rancher.go:541] ExternalID [rancher]
5/5/2016 2:21:03 PMI0505 13:21:03.221143    3224 rancher.go:547] InstanceID [rancher]
5/5/2016 2:21:03 PME0505 13:21:03.242902    3224 kubelet.go:1131] Unable to construct api.Node object for kubelet: failed to get external ID from cloud provider: multiple instances found for name: rancher
```

Even though i renamed one of the hosts manually in the UI i get the same error message. Not sure how to name them programmatically tho. Guess it should be done when registering the node.

![image](https://cloud.githubusercontent.com/assets/1777366/15044558/4dc4c8a8-12cd-11e6-88fc-4278808eab56.png)

I tried to create the [default guest-book application](https://github.com/kubernetes/kubernetes/tree/master/examples/guestbook) by kubernetes, but the containers are stuck in pending state.. 

Rancher Version: 1.0.1

Docker Version: 1.10.3

OS:  RancherOS 0.4.4

Environment: Kubernetes

AWS setup:
- VPC with 3 public and private subnets. NAT gateway for all 3 private subnets
- Auto scale groups for the server and nodes with register-scripts in user-data. Every launched instance get a public IP and ends up in one of three availability zones
- Used these templates: https://github.com/acervos/rancher-aws + had to configure ELB with SSL and Proxy.

Not sure if related, but also get this: 
![image](https://cloud.githubusercontent.com/assets/1777366/15045835/a243d688-12d4-11e6-898d-085c8c4b268e.png)

Steps to Reproduce: Create autoscale-group that registers the rancher-server. Create autoscale-group for the nodes with script in "add custom host" in user data.

**Comment by deniseschannon** [comment]
This is related to this bug with RancherOS, that will be fixed int he next release of RancherOS

https://github.com/rancher/os/issues/829

When we release the next version of RancherOS, would you be able to try again?

**Comment by AlmaasAre** [comment]
Didn't have time to play anymore with research, so went back to GKE unfortunately. Could try at a later point in time
