### ISSUE TITLE
[BUG]: 2.9 : Rancher Logs filled with errors related to auth-user-info-resync-cron for every 2mins

### ISSUE THREAD

**Issue by dasarinaidu** [rancher/rancher#46962]
**Rancher Server Setup**
- Rancher version: `v2.9-473c27dcf5682ebf7d064f1189fe4b44d588e17a-head`
- Installation option (Docker install/Helm Chart): Docker

**Describe the bug**
Rancher panic with Azure related errors in Logs.

**To Reproduce**
1. Provision rancher with `v2.9-473c27dcf5682ebf7d064f1189fe4b44d588e17a-head`
2. Check for the logs

**Result**
1. Logs are filled with `auth-user-info-resync-cron` for every 2 mins
2. Logs are filled with `azure-group-cache-size` for every 2 mins

**Expected Result**
1. Logs should not have panic errors

**Note:**
1. I am seeing these errors on `v2.9-head `only, did not see on `v2.9.1`
2. I am seeing these errors after i upgrade from `v2.9.1` TO `v2.9-head`

**Additional context**
2024/09/04 22:05:44 [ERROR] error syncing 'auth-user-info-resync-cron': handler mgmt-auth-settings-controller: error refreshing cron time: refresh cron time must be provided, requeuing
2024/09/04 22:05:44 [ERROR] error syncing 'azure-group-cache-size': handler mgmt-auth-settings-controller: error updating group cache size with azure: azure-group-cache-size must be provided, requeuing
2024/09/04 22:07:44 [ERROR] error syncing 'auth-user-info-resync-cron': handler mgmt-auth-settings-controller: error refreshing cron time: refresh cron time must be provided, requeuing
2024/09/04 22:07:44 [ERROR] error syncing 'azure-group-cache-size': handler mgmt-auth-settings-controller: error updating group cache size with azure: azure-group-cache-size must be provided, requeuing
2024/09/04 22:09:44 [ERROR] error syncing 'auth-user-info-resync-cron': handler mgmt-auth-settings-controller: error refreshing cron time: refresh cron time must be provided, requeuing
2024/09/04 22:09:44 [ERROR] error syncing 'azure-group-cache-size': handler mgmt-auth-settings-controller: error updating group cache size with azure: azure-group-cache-size must be provided, requeuing
2024/09/04 22:11:44 [ERROR] error syncing 'auth-user-info-resync-cron': handler mgmt-auth-settings-controller: error refreshing cron time: refresh cron time must be provided, requeuing
2024/09/04 22:11:44 [ERROR] error syncing 'azure-group-cache-size': handler mgmt-auth-settings-controller: error updating group cache size with azure: azure-group-cache-size must be provided, requeuing
2024/09/04 22:13:44 [ERROR] error syncing 'auth-user-info-resync-cron': handler mgmt-auth-settings-controller: error refreshing cron time: refresh cron time must be provided, requeuing
2024/09/04 22:13:44 [ERROR] error syncing 'azure-group-cache-size': handler mgmt-auth-settings-controller: error updating group cache size with azure: azure-group-cache-size must be provided, requeuing
2024/09/04 22:15:44 [ERROR] error syncing 'azure-group-cache-size': handler mgmt-auth-settings-controller: error updating group cache size with azure: azure-group-cache-size must be provided, requeuing
2024/09/04 22:15:44 [ERROR] error syncing 'auth-user-info-resync-cron': handler mgmt-auth-settings-controller: error refreshing cron time: refresh cron time must be provided, requeuing
2024/09/04 22:17:44 [ERROR] error syncing 'azure-group-cache-size': handler mgmt-auth-settings-controller: error updating group cache size with azure: azure-group-cache-size must be provided, requeuing
2024/09/04 22:17:44 [ERROR] error syncing 'auth-user-info-resync-cron': handler mgmt-auth-settings-controller: error refreshing cron time: refresh cron time must be provided, requeuing
2024/09/04 22:19:44 [ERROR] error syncing 'auth-user-info-resync-cron': handler mgmt-auth-settings-controller: error refreshing cron time: refresh cron time must be provided, requeuing
2024/09/04 22:19:44 [ERROR] error syncing 'azure-group-cache-size': handler mgmt-auth-settings-controller: error updating group cache size with azure: azure-group-cache-size must be provided, requeuing
2024/09/04 22:21:44 [ERROR] error syncing 'azure-group-cache-size': handler mgmt-auth-settings-controller: error updating group cache size with azure: azure-group-cache-size must be provided, requeuing
2024/09/04 22:21:44 [ERROR] error syncing 'auth-user-info-resync-cron': handler mgmt-auth-settings-controller: error refreshing cron time: refresh cron time must be provided, requeuing

**Comment by pmatseykanets** [comment]
This is caused by https://github.com/rancher/rancher/pull/46191.
@alegrey91 We need to undo checks for empty values in `mgmt-auth-settings-controller` controller sync handler.

**Comment by pmatseykanets** [comment]
@alegrey91 Given the release timeline if I understand correctly it needs to be reverted/fixed right away.

> So once it is merged you can rebase this branch with main.

Not sure what you're referring to here.

**Comment by bigkevmcd** [comment]
@pmatseykanets Any idea why the default isn't being used? 

https://github.com/rancher/rancher/blob/3ad7280b8846ff89c1c00fe2b02920b1cb3fd6f1/pkg/auth/settings/settings.go#L4

Which is used by

https://github.com/alegrey91/rancher/blob/f3e561e210e54202137589221647e7b0ba30e5c2/pkg/auth/providerrefresh/daemon.go#L23

**Comment by pmatseykanets** [comment]
@bigkevmcd Changing a setting's default is unsupported and there were conversations about enforcing it with the webhook. This handler reacts specifically to changes in settings' values.

**Comment by dasarinaidu** [comment]
I have validate the log on 
`v2.9-16a6b70592fa81f5ea4b95d93dd010382a356ee6-head` ; I did not see these errors in the logs and closing this ticket.

**Note:**
I do see a warning message which keep coming, this is not introduced from this fix and we already have open tickets for the same.

https://github.com/rancher/rancher/issues/41663
https://github.com/rancher/rancher/issues/44872
https://github.com/rancher/rancher/issues/40834

The warning message

```
W0912 17:37:16.955905      39 transport.go:301] Unable to cancel request for *client.addQuery
W0912 17:37:16.955929      39 transport.go:301] Unable to cancel request for *client.addQuery
W0912 17:37:17.745258      39 transport.go:301] Unable to cancel request for *client.addQuery
W0912 17:37:18.565261      39 transport.go:301] Unable to cancel request for *client.addQuery
W0912 17:37:18.565296      39 transport.go:301] Unable to cancel request for *client.addQuery
W0912 17:37:18.624653      39 transport.go:301] Unable to cancel request for *client.addQuery
```
