### ISSUE TITLE
[2.10]  Rancher Logs filled with errors related to auth-user-info-resync-cron for every 2mins

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#46970]
forwardport #46962

**Comment by dasarinaidu** [comment]
I have validate the log on main(v2.10-313729fc9900d12427a8d401e0815e549870d778-head); I did not see these errors in the logs and closing this ticket.

**Note:** 
I do see a warning message which keep coming, this is not introduced from this fix and we already have open tickets for the same.

https://github.com/rancher/rancher/issues/41663
https://github.com/rancher/rancher/issues/44872
https://github.com/rancher/rancher/issues/40834

The warning message 
```
W0912 17:37:16.955905      39 transport.go:301] Unable to cancel request for *client.addQuery
W0912 17:37:16.955929      39 transport.go:301] Unable to cancel request for *client.addQuery
W0912 17:37:17.745258      39 transport.go:301] Unable to cancel request for *client.addQuery
W0912 17:37:18.565261      39 transport.go:301] Unable to cancel request for *client.addQuery
W0912 17:37:18.565296      39 transport.go:301] Unable to cancel request for *client.addQuery
W0912 17:37:18.624653      39 transport.go:301] Unable to cancel request for *client.addQuery
```
