### ISSUE TITLE
Upgrade gomock dependency

### ISSUE THREAD

**Issue by aruiz14** [rancher/rancher#46972]
`github.com/golang/mock` is no longer maintained (archived since June'23, latest release on June'21). The README suggest to use the fork at `go.uber.org/mock`.
It's a drop-in replacement, so the changes introduced are really minimal.

This library is used in many places, so this will need to applied in different projects:
 - `lasso`
 - `wrangler`
 - `rancher`
 - ...

**Comment by aruiz14** [comment]
lasso and wrangler were merged, but we'll need new versions being released in order to upgrade Rancher.

**Comment by aruiz14** [comment]
@JonCrowther did the rancher part of the upgrade at https://github.com/rancher/rancher/pull/47128, so this can be closed now!

**Comment by brandond** [comment]
Distros teams need to track this as well.
