### ISSUE TITLE
[BUG]In the cluster Dashboard,  Incorrect 'load average' order in Cluster metrics display

### ISSUE THREAD

**Issue by skanakal** [rancher/rancher#46999]
**Rancher Server Setup**
- Rancher version: 2.9.1
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: 1.28
- Cluster Type (Local/Downstream): Local
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): 

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Admin

**Describe the bug**

In the cluster Dashboard, Cluster metrics, summary, hovering of the "load average" shows in the order 5min, 1min, 15min - shouldn't that be 1, 5, 15 min instead?

**To Reproduce**

- Install latest rancher 
- Install rancher-monitoring latest version 
- Go to cluster metrics and check "load average" tab 

**Result**
Cluster metrics, summary, hovering of the "load average" shows in the order 5min, 1min, 15min

**Expected Result**

It should be 1min, 5min, 15min 

**Screenshots**

![image](https://github.com/user-attachments/assets/068d10e0-7b2d-409b-b87c-c19455cf984c)

**Additional context**

**Comment by pankajsqe** [comment]
"Load Average" Order in cluster dashboard has been fixed and verified.

Details
Rancher : v2.10.0-alpha3
cluster : v1.30.1+rke2r1
rancher-monitoring:105.1.0-rc.1+up61.3.2


<img width="1727" alt="Screenshot 2024-10-18 at 2 03 36 PM" src="https://github.com/user-attachments/assets/cf8acedb-6359-4c25-bc7d-79d99668ee95">
