### ISSUE TITLE
Add OpenAPI code generation to wrangler

### ISSUE THREAD

**Issue by tomleb** [rancher/rancher#47007]
# Context

**Parent issue:** https://github.com/rancher/rancher/issues/47010

As part of the Imperative API, we want a way to generate OpenAPI schemas from Go structs to make it easier to implement custom resources.

# Summary

[wrangler](https://github.com/rancher/wrangler) also serves as code generation. It can generate a few things like listers, clientsets, deepcopy, etc. Wrangler exposes them through this [Run() function](https://github.com/rancher/wrangler/blob/f9725ad6a04e725835441bc897b7b637f4c7e5ee/pkg/controller-gen/main.go#L31-L123). The function runs generators both defined in wrangler and also defined in other modules.

[rancher/rancher](https://github.com/rancher/rancher) uses wrangler's code generation when `go generate ./...` is ran in its repo. It calls the `Run()` function [here](https://github.com/rancher/rancher/blob/5f2c9d8ca0c28993788c756713a68f69f65a7af0/pkg/codegen/main.go#L33-L117) with some configuration.

We want to be able to run [openapi-gen](https://github.com/kubernetes/kube-openapi/tree/master/cmd/openapi-gen) in Rancher. To do this, in wrangler:

1. Add a `GenerateOpenAPI` flag to the [group struct](https://github.com/rancher/wrangler/blob/f9725ad6a04e725835441bc897b7b637f4c7e5ee/pkg/controller-gen/args/args.go#L36). This will determine whether to run the openapi generator for a specific custom resource.
2. Make a map of groups that need openapi generation [like here](https://github.com/rancher/wrangler/blob/f9725ad6a04e725835441bc897b7b637f4c7e5ee/pkg/controller-gen/args/args.go#L36).
3. Run the openapi-gen on those groups by using the go modules from k8s.io/kube-openapi directly. See `generateClientSet`, `generateDeepcopy`, `generateInformers` and `generateListers` in that file for example. All of these are based on `k8s.io/gengo/v2` so it should be fairly straightforward. The generated files should go into `<outputpackage>/openapi` where `<outputpackage>` is [given by this](https://github.com/rancher/wrangler/blob/f9725ad6a04e725835441bc897b7b637f4c7e5ee/pkg/controller-gen/args/args.go#L23).
4. Might be useful to add some tests here, not sure what's the state on wrangler's code gen tests.

**Note:** We don't need to generate OpenAPI schemas for types in wrangler itself, this will be done in Rancher in a separate tasks. However this might be useful to test things out / make sure it's working.

**Note:** Some schemas depend on others. For example, all schemas will depend on `k8s.io/apimachinery/pkg/apis/meta/v1`. This list will probably need to be configured (eg: Collie is currently using fields defined in `github.com/rancher/rancher/pkg/apis/management.cattle.io/v3/`) So maybe we'll need a `OpenAPIDependencies []string` or something.

(*): We want to stop using gengo/v2 at some point, I think it's fine to add openapi with it for now, at least gets us moving.

**Comment by MKlimuszka** [comment]
Blocked until https://github.com/rancher/rancher/issues/47032 is merged

**Comment by gehrkefc** [comment]
PR merged, QA of this will happen in [#47032](https://github.com/rancher/rancher/issues/47032). Closing.
