### ISSUE TITLE
After I add host, going to blank waiting page (even thou I have other hosts already setup)

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4700]
Version - master 5/5 

Steps to Reproduce: 
1.  Switch to environment that already has host (this step important, adding host must be first thing you do)
2.  Go to infrastructure page
3.  Add a host

Results: Going to blank waiting page

Expected: Should not go to waiting page

**Comment by vincent99** [comment]
I can't reproduce this, it might have been fixed by other changes to the waiting page, or there are other requirements like the environment you switch to is a certain orchestration type?

**Comment by tfiduccia** [comment]
Version - master 5/13
Verified fixed
