### ISSUE TITLE
[BUG] Project Owner unable to grant users permissions inherited from Kubernetes admin role.

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#47000]
**Rancher Server Setup**
- Rancher version: 2.8.5

**Describe the bug**
The issue should be general to any Role Template and the way you specify the verbs. Rancher is no taking into account that a complete set of verbs is the same as "*".
For example, the Project Owner Role is unable to grant permissions that are inherited as a complete set of verbs from the Kubernetes admin and are assigned to a role using the verb "*"

In this case, a Project Owner is unable to grant the Manage Workloads Role to another standard user, and it is expected to happen based in our documentation:
[Project Role Reference](https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/manage-role-based-access-control-rbac/cluster-and-project-roles#project-role-reference) 

The Kubernetes Admin Role grants each of the specific verbs, but Manage Workloads attempts to grant " * ". There is an issue related to a complete set of possible verbs versus " * ** ".

**To Reproduce**
1. Provision a Rancher v2.8.5, with a single all role node custom cluster (I used github.com/supereb/tf-do-rancher2).
2. Create two standard users foo and bar
3. Grant the user foo the Project Owner role on the Default project in the downstream cluster
4. As user foo attempt to grant the Manage Workloads Role on the Default project in the downstream cluster to user bar, observe error of the format `admission webhook "rancher.cattle.io.projectroletemplatebindings.management.cattle.io" denied the request: user "u-4w2zk" (groups=["system:authenticated" "system:cattle:authenticated"]) is attempting to grant RBAC permissions not currently held:

{APIGroups:[""], Resources:["pods"], Verbs:["*"]}
{APIGroups:[""], Resources:["pods/attach"], Verbs:["*"]} {APIGroups:[""], Resources:["pods/exec"], Verbs:["*"]} {APIGroups:[""], Resources:["pods/portforward"], Verbs:["*"]} {APIGroups:[""], Resources:["pods/proxy"], Verbs:["*"]} {APIGroups:[""], Resources:["replicationcontrollers"], Verbs:["*"]} {APIGroups:[""], Resources:["replicationcontrollers/scale"], Verbs:["*"]} {APIGroups:["apps"], Resources:["daemonsets"], Verbs:["*"]} {APIGroups:["apps"], Resources:["deployments"], Verbs:["*"]} {APIGroups:["apps"], Resources:["deployments/rollback"], Verbs:["*"]} {APIGroups:["apps"], Resources:["deployments/scale"], Verbs:["*"]} {APIGroups:["apps"], Resources:["replicasets"], Verbs:["*"]} {APIGroups:["apps"], Resources:["replicasets/scale"], Verbs:["*"]} {APIGroups:["apps"], Resources:["statefulsets"], Verbs:["*"]} {APIGroups:["apps"], Resources:["statefulsets/scale"], Verbs:["*"]} {APIGroups:["autoscaling"], Resources:["horizontalpodautoscalers"], Verbs:["*"]} {APIGroups:["batch"], Resources:["cronjobs"], Verbs:["*"]} {APIGroups:["batch"], Resources:["jobs"], Verbs:["*"]}

`
5. As admin, clone the Project Owner Role and give a different name (Project Owner Mod Role)

6. In the "Inherit from" tab, assign the "Manage Workloads" built-in Role in addition to the "Kubernetes Admin Role"
7. As user foo attempt to grant the Manage Workload project role on the Default project in the downstream cluster to user bar again, and observe success.

**Result**
Project Owner cannot grant built-in roles with verbs already inherited because they have been specificied as "*".

**Expected Result**
Built-in roles should use explicit verbs for granting permissions instead of " * ". For example, Manage Workloads could grant specific verbs where it currently grants " * ".

 **workaround:** 

As admin, clone the Project Owner Role and give a different name (Project Owner Mod Role)
In the "Inherit from" tab, assign the "Manage Workloads" built-in Role in addition to the "Kubernetes Admin Role"
As user foo attempt to grant the Manage Workload project role and observe success.

**Comment by samjustus** [comment]
https://jira.suse.com/browse/SURE-8795

**Comment by samjustus** [comment]
https://jira.suse.com/browse/SURE-8806 is related

**Comment by samjustus** [comment]
potentially this will come down to just updating the docs

**Comment by raulcabello** [comment]
The problem is that `Manage Workloads` has more permissions in some resources than the `Project Owner`.
For example, for pods:
`Manage Workloads` tries to give *
`Project Owner` (admin inherited `ClusterRole`) has: get, list, watch, create, delete, patch, update (but no *)
Then the webhook reject the requests, which is the expected behavior.

We could change `Project Owner` to inherit `Manage Workloads`

**Comment by enrichman** [comment]
## Release Note

The "Manage Workloads" role template was updated to fix issue #47000. Any custom role inheriting from this template using custom verbs will need to be updated, specifying the used verbs, or adding the * to the impacted resources. The list of the resources can be found in the PR https://github.com/rancher/rancher/pull/47171.

**Comment by Priyashetty17** [comment]
Recreated the issue with v2.9.2. I've validated all scenarios documented in the test plan for this issue with `v2.10-ae9edd7151ea0a2387b0dcf3d9387eff74d9d101-head`
- Fresh install - Verify that the user with Project Owner role can grant the Manage Workloads role to another user
- Fresh install - Verify that the "Manage Workloads" role has specific permissions assigned for resources
- Fresh install - Verify that a user granted the Manage Workloads role by a Project Owner can CRUD pods
- Fresh install - Verify that a user granted the Manage Workloads role by a Project Owner can CRUD deployments
- Fresh install - Verify that a user granted the Manage Workloads role by a Project Owner can CRUD daemonsets
- Fresh install - Verify that a user granted the Manage Workloads role by a Project Owner can CRUD statefulsets
- Fresh install - Verify that a user granted the Manage Workloads role by a Project Owner can CRUD cronjobs
- Fresh install - Verify that a user granted the Manage Workloads role by a Project Owner can CRUD jobs
- Fresh install - Verify that the user with Project Owner role can grant a custom role (inheriting from "Manage Workloads") to another user
- Fresh install - Escalation check - Verify that a user cannot grant a custom project role with RBAC permissions they do not possess
- Fresh install - Verify that the Project Owner can revoke the Manage Workloads role from a user
- Upgrade - Verify that the user with Project Owner role can grant the Manage Workloads role to another user
- RBAC Regression tests - TestProjectRolesTestSuite and TestRBACTestSuite
