### ISSUE TITLE
[v2.9] Backport Audit Log Image bumps

### ISSUE THREAD

**Issue by mallardduck** [rancher/rancher#47001]
PR here: https://github.com/rancher/rancher/pull/47282
Backport of this PR: https://github.com/rancher/rancher/pull/46974

**Comment by deepakpunia-suse** [comment]
Image `mirrored-bci-micro:15.6.24.2` has been validated for below rancher version: PFA

Details :
Rancher : `v2.9.3-alpha6`
cluster : `v1.30.5+rke2r1`

![Image](https://github.com/user-attachments/assets/70ddb2ce-c439-4668-9da4-58613fc98981)
