### ISSUE TITLE
[dev-v2.8] `go get` workflow is missing the `go generate` changes

### ISSUE THREAD

**Issue by chiukapoor** [rancher/rancher#47014]
## Issue:
* `go get` workflow in rancher is missing the `go generate` changes

## Relevant runs:
* `release/v2.9` [CI](https://github.com/rancher/rancher/actions/runs/10786824694/job/29914367500) is failing due to missing `go generate` changes in [go get](https://github.com/rancher/rancher/actions/runs/10786416129) run

## Fix

We need to add `go generate ./...` step in `go-get` script. Additionally, the CI checks are not running on PR created by `go get` workflow, this needs to be fixed as well.

**Comment by vardhaman22** [comment]
the [PR](https://github.com/rancher/rancher/pull/47052) to fix the CI is merged and it successfully created a go get PR for rke: https://github.com/rancher/rancher/pull/47443 hence closing this.
