### ISSUE TITLE
[v2.9] High CPU load due to calico errors on Ubuntu 20.04 - Update to calico needed

### ISSUE THREAD

**Issue by Sahota1225** [rancher/rancher#47024]
Tracking # https://github.com/rancher/rke/issues/3648

**Comment by kinarashah** [comment]
https://github.com/rancher/kontainer-driver-metadata/pull/1490

**Comment by kinarashah** [comment]
https://github.com/rancher/calico-cni/releases/tag/v3.28.1-rancher1

**Comment by kinarashah** [comment]
@mitulshah-suse do we need a separate issue for 2.8? 
v2.8 PR: https://github.com/rancher/kontainer-driver-metadata/pull/1491

**Comment by kinarashah** [comment]
RKE PRs: 
v1.6 - https://github.com/rancher/rke/pull/3686 
v1.5 - https://github.com/rancher/rke/pull/3687

**Comment by mitulshah-suse** [comment]
> @mitulshah-suse do we need a separate issue for 2.8?

Yes, created below for tracking.. 
https://github.com/rancher/rancher/issues/47046

**Comment by vivek-shilimkar** [comment]
Validated the calico version bump as a part of KDM August patch testing:

Fresh install:
- On rancher v2.9-head(eddb8ca), KDM pointing to dev-v2.9.
- Provisioned v1.30.4, v1.29.8, and v1.28.13 clusters.
- Validated calico is bumped to 3.28.1 and 3.27.4:

Upgrade checks:
- On rancher v2.9.1, created v1.30.3, v1.29.7, and v1.28.12 clusters.
- Upgraded rancher to v2.8-head(eddb8ca)
- Upgraded downstream clusters to k8s versions - to Aug patch versions
- Validated calico is bumped to 3.28.1 and 3.27.4:

![Image](https://github.com/user-attachments/assets/25c7ab9a-2be7-438a-86bd-a5731976d2ea)
![Image](https://github.com/user-attachments/assets/1efcdf3b-d55a-4e03-b6f8-79cbcb1a9111)

Hence this ticket can be closed.
