### ISSUE TITLE
[BUG] `C:\etc\rancher\wins\config` shows duplicate entries in a downstream vSphere Windows RKE2 cluster

### ISSUE THREAD

**Issue by markusewalker** [rancher/rancher#47039]
**Rancher Server Setup**
- Rancher version: `v2.8-head` https://github.com/rancher/rancher/commit/ad14e0efa3e458787323f4f43847bb0ca8dcf32d
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): K3s
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: `v1.29.8+rke2r1`
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Node driver

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Cluster Owner
  - If custom, define the set of permissions:

**Describe the bug**

On a Windows vSphere node driver cluster, when looking into the file `C:\etc\rancher\wins\config`, we are seeing duplicate entries as illustrated below:

```
> cat C:\etc\rancher\wins\config
white_list:
  processPaths:
    - C:/etc/rancher/wins/powershell.exe
    - C:/etc/wmi-exporter/wmi-exporter.exe
    - C:/etc/windows-exporter/windows-exporter.exe
  proxyPorts:
    - 9796
agentStrictTLSMode: false
systemagent:
  workDirectory: C:/var/lib/rancher/agent/work
  appliedPlanDirectory: C:/var/lib/rancher/agent/applied
  remoteEnabled: true
  preserveWorkDirectory: false
  connectionInfoFile: C:/var/lib/rancher/agent/rancher2_connection_info.json
csi-proxy:
  url: https://<omitted>/assets/csi-proxy-%[1]s.tar.gz
  version: v1.1.3
  kubeletPath: C:/var/lib/rancher/rke2/bin/kubelet.exe
tls-config:
  certFilePath: c:\etc\rancher\wins\ranchercert
white_list:
  processPaths:
    - C:/etc/rancher/wins/powershell.exe
    - C:/etc/wmi-exporter/wmi-exporter.exe
    - C:/etc/windows-exporter/windows-exporter.exe
  proxyPorts:
    - 9796
agentStrictTLSMode: false
systemagent:
  workDirectory: C:/var/lib/rancher/agent/work
  appliedPlanDirectory: C:/var/lib/rancher/agent/applied
  remoteEnabled: true
  preserveWorkDirectory: false
  connectionInfoFile: C:/var/lib/rancher/agent/rancher2_connection_info.json
csi-proxy:
  url: https://<omitted>/assets/csi-proxy-%[1]s.tar.gz
  version: v1.1.3
  kubeletPath: C:/var/lib/rancher/rke2/bin/kubelet.exe
tls-config:
  certFilePath: c:\etc\rancher\wins\ranchercert
```
In contrast to a custom cluster RKE2 Windows cluster, that one correctly only has one entry and does not duplicate. This behavior does not seem to have any functional impact on the cluster. Functionalities such as nodescaling and upgrading succeeded as expected. However, this should still be fixed.

**To Reproduce**

1. Provision downstream RKE2 vSphere node driver cluster (1 etcd, 1 cp, 1 Linux worker, 1 Windows worker).
2. RDP into the Windows node.
3. Enter Powershell and enter command `cat C:\etc\rancher\wins\config`. Note the duplicate entry.

Additionally, this behavior is happening in 2.9 and head branches; this is not exclusive to v2.8.

**Result**
There are duplicate entries in the file.

**Expected Result**

There should not be duplicate entries in this file.

**Comment by HarrisonWAffel** [comment]
I was able to reproduce this issue on 2.9.1 too. 

This seems to be due to our vSphere nodes running the rancher-wins install script multiple times. Unlike the linux system-agent install script, which [overwrites the contents of the system-agent configuration file](https://github.com/rancher/system-agent/blob/0d64f6e5832177bf8a2d918d4edfb1c8b5ff1f9c/install.sh#L800-L809), rancher-wins only [appends to the file](https://github.com/rancher/wins/blob/8c1fdd9c46b6b936ac345b80e1f0bc492210c128/install.ps1#L480). In the event that the script is run multiple times, the config file will have duplicate entries. This will also reproduce for nodes being added to custom clusters which have the install script run on them multiple times. However, `rancher-wins` is able to handle this scenario and decodes the config without error.

**Comment by HarrisonWAffel** [comment]
Waiting on 2.9-head build to complete before moving into Ready For QA

**Comment by markusewalker** [comment]
Validated on `v2.9-head` https://github.com/rancher/rancher/commit/12322b88813868c2a4679cfa0409ceb4c1255d7c that this has been resolved. See details below:

**ENVIRONMENT**
- Rancher install: Docker
- Rancher version: `v2.9-head` https://github.com/rancher/rancher/commit/12322b88813868c2a4679cfa0409ceb4c1255d7c

**TEST RESULT**
|#|Scenario|Result|
|---|---|---|
|1|Validate that `C:\etc\rancher\wins\config` does not show duplicate entries|:white_check_mark:|
