### ISSUE TITLE
[v2.8] High CPU load due to calico errors on Ubuntu 20.04 - Update to calico needed

### ISSUE THREAD

**Issue by mitulshah-suse** [rancher/rancher#47046]
Tracking # https://github.com/rancher/rke/issues/3648
Backport https://github.com/rancher/rancher/issues/47024

**Comment by rishabhmsra** [comment]
Validated the calico version bump as a part of KDM August patch testing:

Fresh install:
- On rancher v2.8-head(9c45a84), KDM pointing to dev-v2.8.
- Provisioned v1.28.13-rancher1-1 clusters.
- Validated calico is bumped to 3.27.4:

![calico](https://github.com/user-attachments/assets/7ad57a01-0fda-4e7d-8cd8-a0ac95926525)

Upgrade checks:
- On rancher v2.8.7, created v1.28.12-rancher1-1 clusters.
- Upgraded rancher to v2.8-head(a900ab5)
- Upgraded downstream clusters to k8s versions - v1.28.13-rancher1-1
- Validated calico is bumped to 3.27.4:

![calico1](https://github.com/user-attachments/assets/ef929b45-0182-4655-b6c4-a7ed3d4eafef)

v2.8 KDM August patch testing also passed successfully.
