### ISSUE TITLE
[v2.10] High CPU load due to calico errors on Ubuntu 20.04 - Update to calico needed

### ISSUE THREAD

**Issue by mitulshah-suse** [rancher/rancher#47047]
Tracking # https://github.com/rancher/rke/issues/3648
Forward port https://github.com/rancher/rancher/issues/47024

**Comment by rishabhmsra** [comment]
Validated on rancher v2.10-head:
- Provisioned v1.28.13-rancher1-1, v1.29.8-rancher1-1 and v1.30.4-rancher1-1 clusters.
- Validated calico version and it's bumped to `rancher/mirrored-calico-node:v3.28.1` on v1.30 clusters and on v1.28 and v1.29 it's bumped to `rancher/mirrored-calico-node:v3.27.4` version.
