### ISSUE TITLE
[BUG] Only apply "auth-prov-v2-" finalizers to necessary resources

### ISSUE THREAD

**Issue by aruiz14** [rancher/rancher#47045]
At the moment, Rancher monitors every Role, RoleBinding, ClusterRole and ClusterRoleBinding in the upstream cluster, adding a finalizer in order to react in case the object is marked for deletion (in this case, it seems the goal is to prevent unordered deletion of associated resources, which could cause to lose permissions needed for completing the cleanup).

This mechanism of adding a finalizer is performed by using wrangle's `OnRemove` handlers, which first amend all the existing objects to ensure they have the correct finalizer, then executes a callback when the object's `deletionTimestamp` is set.

**Comment by aruiz14** [comment]
## Validation Template

## Root Cause
Rancher adds finalizer to *all* Roles, ClusterRoles, RoleBindings and ClusterRolebindings in the upstream cluster. This combined with a bug in `tigera/operator` causing their controller to remove finalizers in resources owned by them, causes a "controller fight", where both clients will indefinitely add and remove these finalizers causing a big amount of updates on the affected resourcves

## What was fixed, or what change have occurred
Rancher will only add finalizers to a subset of the mentioned kinds.

## Areas or cases that should be tested

On a very basic 1 upstream, no downstreams scenario, and Rancher running with a single replica, we can perform the following check:
* Create a test `ClusterRole`:
```
$ kubectl create clusterrole test --verb=get --resource=pods
clusterrole.rbac.authorization.k8s.io/test created
```
* Ensure `metadata` does not include `finalizers`:
```
$ kubectl get clusterrole test -ojsonpath='{.metadata.finalizers}'
<empty>
```
* Add annotations that change the criteria of the controller over this resource:
```
$ kubectl annotate clusterrole/test cluster.cattle.io/name=test cluster.cattle.io/namespace=test
clusterrole.rbac.authorization.k8s.io/test annotated
```
* Now finalizers should be set:
```
$ kubectl get clusterrole/test -ojsonpath='{.metadata.finalizers}'
["wrangler.cattle.io/auth-prov-v2-crole"]
```
* Removing the annotations will keep the finalizer (mimicking pre-existing objects use case), but still allow deleting the resource:
```
$ kubectl annotate clusterrole/test cluster.cattle.io/name- cluster.cattle.io/namespace-
clusterrole.rbac.authorization.k8s.io/test annotated

$ kubectl get clusterrole/test -ojsonpath='{.metadata.finalizers}'
["wrangler.cattle.io/auth-prov-v2-crole"]

$ kubectl delete clusterrole/test
clusterrole.rbac.authorization.k8s.io "test" deleted
```

## What areas could experience regressions
None expected, since I added backwards compatibility to keep existing objects working too.

**Comment by rancher-max** [comment]
This seems like mostly a functional validation, but the main value comes in performance with the controller fight problem. Therefore, in addition to the above test case, we will do a scale test (assuming it is possible via k6):

- 3 downstreams
- handful of clusterroles, roles, rolebindings, clusterrolebindings
- Do the steps mentioned on all of the resources
- Ensure no "controller fight" happens, finalizers are added but not removed, and resources are removed correctly

**Comment by moio** [comment]
@rancher-max you could teach k6 to repeat PUT calls to remove .metadata.finalizers.

Previous version of Rancher should put them back (with some CPU consumption), while the new version should not.

That should be easily possible by adapting code in https://github.com/rancher/dartboard/blob/main/k6/k8s.js#L31 (that does POST, PUT is very similar) for the update use case.


You will not need any downstream clusters at all.

Default dartboard settings will create roles/clusterroles/bindings/clusterrolebindings - and you just need one.

**Comment by rancher-max** [comment]
Changes should be in 2.10.0, but performing the performance testing as part of 2.10.1 release cycle (unless we finish before this goes out, as it is being actively worked on).

**Comment by MSpencer87** [comment]
#### Verified on Rancher 2.10.0 + v1.30.2-rke2r1

Removed resource finalizers remain deleted

### Steps for reproduction:
1. Bring up HA Rancher 2.9.0 in AWS (5 Nodes, All Roles)
2. Create a custerRole, this can be done using k6 and `http.post`, similar to https://github.com/rancher/dartboard/blob/main/k6/k8s.js#L31
```
    const res = http.post(
        `${baseUrl}/v1/rbac.authorization.k8s.io.clusterroles`,
        JSON.stringify({
            "type": "rbac.authorization.k8s.io.clusterrole",
            "description": "Test Cluster Role",
            "metadata":{"name":"TestClusterRole"},
            "rules":[{"apiGroups":[""],"nonResourceURLs":[],"resourceNames":[],"resources":["pods"],"verbs":["get"]}],
            "undefined":false
        }),
        { cookies: cookies }
    )
```
3. Update clusterRole to remove `wrangler.cattle.io/auth-prov-v2-crole` finalizer, this can be done using k6 and `http.put`
```
    const res = http.put(
        `${baseUrl}/v1/rbac.authorization.k8s.io.clusterrole/TestClusterRole`,
        JSON.stringify({
            "metadata":{"name":"TestClusterRole","resourceVersion":`${resourceVersion}`,"annotations":{"cluster.cattle.io/name":"test", "cluster.cattle.io/namespace":"test"}},
            "rules":[{"apiGroups":[""],"nonResourceURLs":[],"resourceNames":[],"resources":["pods"],"verbs":["get"]}],
        }),
        { cookies: cookies }
    )
```
4. Confirm clusterRole finalizer `wrangler.cattle.io/auth-prov-v2-crole` is added back to configuration after update


### Steps for validation:
1. Bring up HA Rancher 2.10.0 in AWS
2. Create a custerRole using k6 and the `http.post` from above
3. Update clusterRole to remove `wrangler.cattle.io/auth-prov-v2-crole` finalizer using k6 and the `http.put` from above
4. Confirm clusterRole finalizer `wrangler.cattle.io/auth-prov-v2-crole` is removed permanently
