### ISSUE TITLE
Support for scheduling containers with multi AZ High Availability 

### ISSUE THREAD

**Issue by ashishgupta1989** [rancher/rancher#4705]
I have 6 instances running on AWS with 2 instances on each availability zone, so I have 6 hosts in my rancher Dashboard, with labels:
az:us-west-2a(key:value) - 2 instances
az:us-west-ab(key:value) - 2 instances
az:us-west-2c(key:value) - 2 instances

My use case is, I am running a service with 3 containers and I want to schedule it in such a way that at least one container should run on each availability zone i.e.

one container should run on one of the instance having label az:us-west-2a(key:value)
one container should run on one of the instance having label az:us-west-2b(key:value)
one container should run on one of the instance having label az:us-west-2c(key:value)

**Comment by deniseschannon** [comment]
As discussed in the forums, this is an enhancement request to our scheduler.

https://forums.rancher.com/t/how-to-schedule-containers-with-multi-az-high-availability/2670

**Comment by trondvh** [comment]
+1 This would be of great value in a hybrid environment as well.

**Comment by mwelch-ptc** [comment]
I went to the rancher forums to ask this specific question and found that a multi AZ approach wasn't yet feasible. Unfortunately, being able to do this is such a critical requirement for us, that it's absence may end up being a deal breaker. Is there any workaround? Even a manual one we can implement until such time as an automated approach is feasible?

**Comment by trondvh** [comment]
Maybe you could create an environment for each az?  We at least did that for our two private data centers.

**Comment by LLParse** [comment]
You could create host labels that describe availablity zones, for example AZ=west-1 AZ=west-2 etc. At some point in the future, Rancher could then provide AZ info as an [automatically applied host label](http://docs.rancher.com/rancher/latest/en/labels/#automatically-applied-host-labels).

Then use [scheduling labels](http://docs.rancher.com/rancher/latest/en/rancher-compose/scheduling/#table-of-scheduling-labels) to distribute the containers as you see fit. This is a hack, but a good step towards realizing a reusable pattern...

**Comment by ashishgupta1989** [comment]
Or maybe you can have one container on each i srance set up till the time we have this resolved by rancher. I know its not ideal, but only possible solution as of now which i can think of.

**Comment by abhijt-zanak** [comment]
+1

**Comment by viszjag** [comment]
Ya, if we have such mechanism in place it would be of great value.

**Comment by mheiniger** [comment]
maybe this will help: https://github.com/rancher/rancher/issues/7253

**Comment by will-chan** [comment]
Using #7253 to track this as we are looking to implement this soon.
