### ISSUE TITLE
[main] `C:\etc\rancher\wins\config` shows duplicate entries in a downstream vSphere Windows RKE2 cluster

### ISSUE THREAD

**Issue by HarrisonWAffel** [rancher/rancher#47066]
This is a forward port to main of https://github.com/rancher/rancher/issues/47039

**Comment by HarrisonWAffel** [comment]
`rancher-wins` was bumped to `v0.4.19-rc1` in main last week, so this can now be tested

**Comment by markusewalker** [comment]
Validated on `head` https://github.com/rancher/rancher/commit/24d19e205aaed1ca11b572888a6a0c9728b54807 that this has been resolved. See details below:

**ENVIRONMENT**
- Rancher install: Docker
- Rancher version: `head` https://github.com/rancher/rancher/commit/24d19e205aaed1ca11b572888a6a0c9728b54807

**TEST RESULT**
|#|Scenario|Result|
|---|---|---|
|1|Validate that `C:\etc\rancher\wins\config` does not show duplicate entries|:white_check_mark:|
