### ISSUE TITLE
[2.8 Backport] `C:\etc\rancher\wins\config` shows duplicate entries in a downstream vSphere Windows RKE2 cluster

### ISSUE THREAD

**Issue by HarrisonWAffel** [rancher/rancher#47060]
This is a backport issue of https://github.com/rancher/rancher/issues/47039 for the 2.8 release line

**Comment by markusewalker** [comment]
Validated on `v2.8-head` https://github.com/rancher/rancher/commit/a900ab51c9dc79b290b41235d2f2a27a28b59b09 that this has been resolved. See details below:

**ENVIRONMENT**
- Rancher install: Docker
- Rancher version: `v2.8-head` https://github.com/rancher/rancher/commit/a900ab51c9dc79b290b41235d2f2a27a28b59b09

**TEST RESULT**
|#|Scenario|Result|
|---|---|---|
|1|Validate that `C:\etc\rancher\wins\config` does not show duplicate entries|:white_check_mark:|
