### ISSUE TITLE
Automate Test cases for rancher-compose commands.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#4707]
Automate test cases for supported rancher-compose commands and options listed in http://docs.rancher.com/rancher/latest/en/rancher-compose/commands/

There are test cases relating to upgrage/confirm-upgrade/rollback that are already automated - 
https://github.com/rancher/validation-tests/blob/master/tests/validation/cattlevalidationtest/core/test_rancher_compose_inservice_upgrade.py.

**Comment by soumyalj** [comment]
Automated the following commands:
a) create b) up c) start/stop, start/down d)scaleup, e) restart with batchsize, interval options
f) delete g) Few options in security tab h) Few options in Networking tab

**Comment by soumyalj** [comment]
https://github.com/rancher/rancher/issues/4972
