### ISSUE TITLE
[RFE] Create a yaml replacement for Restricted Admin

### ISSUE THREAD

**Issue by JonCrowther** [rancher/rancher#47081]
**Is your feature request related to a problem? Please describe.**
The built in Global Role "Restricted Admin" has been in the process of being deprecated for several versions. It's an important role for certain use cases like Harvester and hosted Rancher. Before fully deprecating we need a replacement.

**Describe the solution you'd like**
Global Roles have had a lot of work done in the last 2 releases to enhance their functionality with new fields. Those fields can completely replicate the restricted admin functionality.

We would like a yaml that can be applied that provides the same experience as Restricted Admin. That way we can simply apply it for use cases where it's necessary.

**Describe alternatives you've considered**
Keeping Restricted Admin is not really an option because it has repeatedly been found to have security issues or bugs.

In 2.10 we don't have the capacity to add the new fields into the UI to allow users to configure it themselves, and that method also could lead to incorrectly made Restricted Admin replacements.

**Additional context**

**Comment by samjustus** [comment]
@raulcabello lets put it here: https://github.com/rancherlabs/engineering-infra/tree/main/docs

I will also create a issue for docs team to add to prime docs

**Comment by mlaguilharre** [comment]
I successfully created a custom role inspired from Restricted Administrator role:
https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/manage-role-based-access-control-rbac/custom-roles
https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/manage-role-based-access-control-rbac/global-permissions

I created custom role without any resource, then I edited as yaml and I added the rules: section from Restricted Administrator yaml, and added

```
inheritedClusterRoles:
- cluster-owner
```

It seems to work.

You can find a resulting new-restricted-admin.yaml example.
[new-restricted-admin.zip](https://github.com/user-attachments/files/17488361/new-restricted-admin.zip)

**Comment by gaktive** [comment]
Related dashboard: https://github.com/rancher/dashboard/issues/12146

**Comment by joesims22** [comment]
Validated on v2.10-head id `14a48bc` successfully.
Added qa-task for automation.

**Comment by samjustus** [comment]
this was resolved in 2.10 but that milestone was closed so I cannot add it to it
