### ISSUE TITLE
[BUG] Syntax error in rancher-monitoring/prometheus-node-exporter charts

### ISSUE THREAD

**Issue by ericpromislow** [rancher/rancher#47092]
- [x] v2.8
- [x] v2.9

The syntax error is in `psp-clusterrole.yaml`  in the charts for rancher-monitoring/prometheus-node-exporter in the above branches.

```
@@ -1,4 +1,4 @@
-{{- if and .Values.rbac.create .Values.rbac.pspEnabled (.Capabilities.APIVersions.Has "policy/v1beta1/PodSecurityPolicy") }}
+{{- if and (or .Values.global.cattle.psp.enable (.Values.rbac.create .Values.rbac.pspEnabled)) (.Capabilities.APIVersions.Has "policy/v1beta1/PodSecurityPolicy") }}
 kind: ClusterRole
 apiVersion: rbac.authorization.k8s.io/v1
 metadata:
```

The second line should be
```
+{{- if and (or .Values.global.cattle.psp.enable (and .Values.rbac.create .Values.rbac.pspEnabled)) 
```

**Comment by deepakpunia-suse** [comment]
We have brainstormed and tested this issue with `Dominic Giebert` in there environment and confirmed that it has been resolved. We are now able to install the chart without errors using the following parameters:

```yaml
nodeExporter:
  global:
    cattle:
      psp:
        enable: false
```

However, `Dominic Giebert` has suggested some improvements to @ericpromislow. We will keep this ticket open until those are addressed.

![Image](https://github.com/user-attachments/assets/96736bec-33e4-46ad-8afd-91093a1edc77)
