### ISSUE TITLE
[v2.8] KubernetesVersions on AKS portal must be available for provisioning on Rancher

### ISSUE THREAD

**Issue by cpinjani** [rancher/rancher#47097]
**Rancher Server Setup**
- Rancher version: v2.8-eb4ea1fdd3bc4c3c98e2d24116de819a216ded76-head, aks-operator:v1.2.5-rc.1

**Information about the Cluster**
- Cluster Type (Downstream):
   - Hosted Provider: AKS

**Describe the issue**
On 2.8, seems kubernetes versions are parsed using [ListOrchestrators](https://github.com/rancher/rancher/blob/release/v2.8/pkg/api/norman/customization/aks/listers.go#L251) API and in 2.9 using [ListKubernetesVersions](https://github.com/rancher/rancher/blob/main/pkg/api/norman/customization/aks/listers.go#L279)

Hence the versions supported by AKS are not avaialble for provisioning. Eg. 1.27 (see screenshot below)

**To Reproduce**
Provision AKS cluster using Rancher UI

**Expected Result**
User should be able to use KubernetesVersions currently supported by AKS

**Screenshots**

Rancher:
![image](https://github.com/user-attachments/assets/6838ea99-3ea9-493d-ad9f-ae9020d5cb89)

AKS:

![image](https://github.com/user-attachments/assets/c33792ad-02b9-4bcc-b6ac-95e1eaa5e41f)

**Comment by cpinjani** [comment]
@mjura @yiannistri Request to triage the issue, thanks.

**Comment by yiannistri** [comment]
In my opinion, the correct call to use is https://learn.microsoft.com/en-us/rest/api/aks/managed-clusters/list-kubernetes-versions?view=rest-aks-2024-09-01&tabs=HTTP , 2.8 seems to be using an older API that likely returned correct results when it was introduced but has since been deprecated: https://pkg.go.dev/github.com/Azure/azure-sdk-for-go@v68.0.0+incompatible/services/containerservice/mgmt/2020-09-01/containerservice#ContainerServicesClient.ListOrchestrators

**Comment by mjura** [comment]
@cpinjani this issue is invalid, the highest supported k8s version on Rancher v2.8 is K8s v1.28
https://www.suse.com/suse-rancher/support-matrix/all-supported-versions/rancher-v2-8-9/

This is validated by KDM.

**Comment by cpinjani** [comment]
> @cpinjani this issue is invalid, the highest supported k8s version on Rancher v2.8 is K8s v1.28 [suse.com/suse-rancher/support-matrix/all-supported-versions/rancher-v2-8-9](https://www.suse.com/suse-rancher/support-matrix/all-supported-versions/rancher-v2-8-9/)
> 
> This is validated by KDM.

Not sure I follow, as mentioned in description v1.27 is indeed supported then.
