### ISSUE TITLE
[RFE] Istio ambient mode installation

### ISSUE THREAD

**Issue by m3nax** [rancher/rancher#47099]
**Is your feature request related to a problem? Please describe.**
Resource consumption derived from istio proxies is very expensive.

**Describe the solution you'd like**
Having an option to install istio in ambient mode directly from the racher interface. 

![image](https://github.com/user-attachments/assets/242a801e-1991-495b-a811-e60aac7c8d60)

**Describe alternatives you've considered**
Remove istio

**Additional context**
- Istio ambient: [https://istio.io/latest/blog/2022/introducing-ambient-mesh](https://istio.io/latest/blog/2022/introducing-ambient-mesh)
- Version 1.23 of istio has a specific helm chart for installing it in ambient mode. (https://istio-release.storage.googleapis.com/charts - istio/ambient)

**Comment by RRadziejewski** [comment]
bump, istio in ambient mode or no istio that is the question
