### ISSUE TITLE
Feature Charts: Add Longhorn 1.7.1 Chart in 2.9.0

### ISSUE THREAD

**Issue by Delta1977** [rancher/rancher#47100]
Longhorn has a release 1.7.1 as stable so we need to add this new release in the feature charts along with Rancher 2.9.0.

Add 1.7.1 LH chart in feature chart 2.9.0 - Cluster Manager/Rancher Marketplace
Cc: @chriscchien @innobead @khushboo-rancher @yangchiu @PhanLe1010 @mantissahz @lucasmlp @nicholasSUSE

**Comment by nicholasSUSE** [comment]
Sorry, I don't understand what this is. 
@Delta1977

**Comment by mantissahz** [comment]
Hi @nicholasSUSE,

This ticket is duplicated to https://github.com/rancher/rancher/issues/47184
