### ISSUE TITLE
Will Support for GCE Hosts be added

### ISSUE THREAD

**Issue by grandmore** [rancher/rancher#4711]
Currently Google Compute Engine is not available inside the Rancher interface. I have been using GCE with Rancher but without the ability to automatically create the Hosts from inside the system some features would not be available. 

I am thinking of auto scaling when load os light or too heavy,  and removing a host when its unhealthy and replacing it with a new one.

Is this on the roadmap for the next version.

**Comment by deniseschannon** [comment]
It already exists today under the "Other" section of Add hosts and it's located as the "Google" driver. This is all based on docker-machine's support of it. If you can create a host in docker-machine for GCE, you should be able to use the section I referenced to create one as well.

Personally, I have never tested this specific machine driver, so let me know how it goes! :)

**Comment by grandmore** [comment]
Thanks for the headsup, I never noticed it there. 

Its not as simple as was etc, but I will see if it works.

Thanks.

**Comment by vincent99** [comment]
The "Other" is very generic support for any drivers that machine claims to have that we don't have nicer screens for.

Google is not very practical to use because they require Oauth login from a browser instead of taking API keys like every single other docker-machine provider.

But it theoretically works if you exec into the container where go-machine-service is running* and login in a way that satisfies their driver it theoretically works, until the Oauth token expires or the machine service container is replaced.

*: inside rancher/server for the basic one command install, or in the machine service containers on each host for HA

**Comment by faddat** [comment]
@googlecloudplatform

**Comment by ibuildthecloud** [comment]
We at Rancher are pretty big GCE users and we never use docker-machine with GCE because of the oauth stuff.  Too much of a pain.

**Comment by frankcarey** [comment]
@ibuildthecloud If your rancher/server is on a GCE instance though, doesn't that avoid the whole oauth thing? https://docs.docker.com/machine/drivers/gce/

**Comment by bradrydzewski** [comment]
@ibuildthecloud what about using service accounts for long-lived tokens? this is what we use with google container registry to avoid the oauth2 refresh token issues
https://cloud.google.com/compute/docs/access/create-enable-service-accounts-for-instances

**Comment by vincent99** [comment]
@bradrydzewski we ultimately call docker-machine  and AFAIK there are no options that deal with how it does with our what it requests/saves.

On the good news/bad need front, the Azure driver in machine v0.7 switched to oauth too.  So it is likely that we will  have you convert up with a way to make them work, which will  probably solve the same problem for GCE

**Comment by thijskaspers** [comment]
+1

**Comment by bradrydzewski** [comment]
@vincent99 thanks for the insight.

I came across this thread because I was having difficultly authenticating docker machine requests for Google Compute with 403 errors. I'm new to their platform, and their documentation can be a bit difficult to navigate, so I figured I'd share how I got it working in case others stumble on this thread like I did.

I eventually found the following on the Google Compute website:

> Some applications might use commands from the gcloud and gsutil tools, which are included by default in most Compute Engine images. These tools automatically recognize an instance's service account and relevant permissions granted to the service account. Specifically, if you have the necessary access scopes defined for the instance's default service account, you can use gcloud and gsutil from your instances without having to use gcloud auth login.

Per the above instructions, I created my rancher compute instance with additional scopes, specifically the `compute-rw` scope, allowing the instance to make API calls to manage compute instances:

```bash
gcloud compute instances create rancher-server \
--image-family gci-stable \
--image-project google-containers \
--machine-type g1-small \
--scopes useraccounts-ro,storage-rw,logging-write,monitoring-write,service-management,service-control,compute-rw,cloud-platform
```

If I look at the instance details in the Google Compute console I see the following:

> This instance has full API access to all Google Cloud services.

I also need the ability to manage instances across multiple Google Compute projects. I found the service account associated with my rancher instance on my IAM settings screen which looks something like `1013109210343-compute@developer.gserviceaccount.com`. I added this account to my other projects' IAM accounts and permissions lists.

I am now able to manage servers across projects using rancher without having to worry about oauth refresh token expiration.

**Comment by hollingsworthd** [comment]
This is definitely possible without oauth. Users could specify their service account json key. And running Rancher within GCE, `gcloud` bin would already be installed and on the path. Command would look like this:

```````
sudo gcloud auth activate-service-account \
a-super-long@google-email-id-for-api-service-account.com \
--key-file <your json file> \
--project your-project-id \
&& \
sudo gcloud compute \
--project "your-project-id" disks create someMachineName --size "10" \
--zone us-somewhere1-a \
--source-snapshot "name-of-linux-image-with-docker-installed" \
--type "pd-ssd" \
&& \
sudo gcloud compute --project "your-project-id" \
instances create someMachineName \
--zone us-somewhere1-a \
--machine-type some-size \
--subnet "default" \
--maintenance-policy "MIGRATE" \
--scopes default="https://www.googleapis.com/auth/devstorage.read_only",\
"https://www.googleapis.com/auth/logging.write",\
"https://www.googleapis.com/auth/monitoring.write",\
"https://www.googleapis.com/auth/servicecontrol",\
"https://www.googleapis.com/auth/service.management.readonly" \
--disk "name=someMachineName,device-name=someMachineName,mode=rw,boot=yes,auto-delete=yes"
````````

Then on the created machine, run: `docker run -d --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:<version> http://<rancher ip>:<rancher port>/v1/scripts/SOMESTRING2:SOMESTRING2:SOMESTRING3`

**Comment by vincent99** [comment]
@hollingsworthd that's fine if you want to create your own machines manually, but does not help integrate with docker-machine.

**Comment by hollingsworthd** [comment]
@vincent99 after running `gcloud auth activate-service-account` Docker Machine works. Yes, none of this is automatic, it would have to be something Rancher integrated. None of these commands require manual intervention though; they could all be run automatically.

**Comment by hollingsworthd** [comment]
````````
sudo gcloud auth activate-service-account \
 a-super-long@google-email-id-for-api-service-account.com \
 --key-file  <your json file> \
 --project <your-project-id> \
&& \
sudo gcloud compute instances create someMachineName \
 --boot-disk-size=10 \
 --boot-disk-type=pd-ssd \
 --machine-type=g1-small \
 --image-family=ubuntu-1604-lts \
 --zone=us-somezone1-b
&& \
docker-machine create --driver google \
 --google-project <your-project-id> \
 --google-zone us-somezone1-a \
 --google-machine-type g1-small \
 --google-disk-type pd-ssd \
 --google-disk-size 10 \
# --google-use-internal-ip \
 --google-machine-image projects/something/something/uri123 \
```````

**Comment by vincent99** [comment]
Rancher is multi-tenant, different users need to be able to create using different credentials.

**Comment by hollingsworthd** [comment]
@vincent99 gcloud auth uses the $HOME variable to choose a place to store creds. Perhaps with `env -i` (which gives a bash command a blank, isolated state) and/or `gcloud config set core/project` with `gcloud config set account` this could support multi-tenant. And if the json file is persisted then gcloud auth could be run before every docker-machine command. Just a thought. I don't know the full complexity of the use cases at all.

**Comment by grandmore** [comment]
I was forced to use `docker-machine` itself to create the instances on GCE, then ssh into them and run the rancher command inside them.

It's not very painful and it's reasonably quick. I had to ensure that I used the Rancher supported docker version, in this case it's 1.10.3.

```bash
machine create --driver google \
  --engine-install-url "https://releases.rancher.com/install-docker/1.10.3.sh" \
  --google-machine-image "https://www.googleapis.com/compute/v1/projects/ubuntu-os-cloud/global/images/ubuntu-1404-trusty-v20160516" \
  --google-project PROJECT_NAME \
  --google-zone europe-west1-d \
  --google-machine-type g1-small \
  --google-disk-size 50 \
  --google-tags rancher-server,http-server,https-server \
  ranch-us-server-01
```
If it fails to complete with a 'certificate' error it can easily be regenerated with 
`docker-machine regenerate-certs  ranch-us-server-01`

**Comment by caoruidong** [comment]
Hey all, what's the status of Google Compute Engine support? I still don't see it in machine drivers in the latest rancher.

**Comment by vincent99** [comment]
Nothing has changed as far as GCP in docker-machine. And also there is little advantage to/demand for paying for etcd/control nodes instead of getting them for free in GKE.  So we have no plans of supporting it.

**Comment by caoruidong** [comment]
@vincent99 Thank you for information.

**Comment by jnicholls** [comment]
@vincent99 That makes sense. However, it would be nice to be able to manage the underlying nodes in a consistent manner and have them all running exactly the same control plane components. This may not be the case for GKE, but with EKS we ran into an issue with the [cluster-signed certificate API](https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/#requesting-a-certificate) where SAN entries were being dropped...something about Amazon not honoring all v3 x509 extensions or something. Little things like this, or the inability to configure kube-api in a consistent fashion makes for a compelling reason not to use the managed Kubernetes services.

In this particular case, I'm interested in having particular node pools with special setups (e.g. NVMe instance storage, raided and mounted and ready to go) that I'm not certain GKE will allow through Rancher, but I'll have to check. Anyways, I thought it would be nice to have node templates setup no matter what the provider was.

**Comment by christianhuening** [comment]
However there's docs here: https://rancher.com/docs/rancher/v2.5/en/cluster-provisioning/rke-clusters/cloud-providers/gce/
