### ISSUE TITLE
Ensure Token is ready for 2.10 or it's completely removed

### ISSUE THREAD

**Issue by tomleb** [rancher/rancher#47119]
# Context

**Parent issue:** https://github.com/rancher/rancher/issues/47010

As part of the Imperative API, frameworks will be providing a dummy `Token` type that doesn't do anything (eg: no fields, etc) to help us develop the Imperative API and test it, and also to help kickstart the Token work for Collie.

If `Token` doesn't make it, we need to make sure that it's completely removed. This ticket tracks this and sets a release blocker to 2.10.

**Comment by tomleb** [comment]
Since we haven't actually done https://github.com/rancher/rancher/issues/47009, there aren't any token types to remove for 2.10. I'm moving this to 2.11 milestone. (we might not even need it at all)

CC: @MKlimuszka

**Comment by MKlimuszka** [comment]
Closing as this is not needed anymore.
