### ISSUE TITLE
[BUG] Stale Secret Fix

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#47126]
follow up to #46537 to automatically clean stale secrets

With the landing of the initial fix for #44347 we need to consider how we'll clean-up the resulting stale secrets.

Affected customers will likely have large numbers of Secret resources in the `cattle-impersonation-system` namespace, with only a tiny-fraction of these actually containing anything useful.

**Comment by Priyashetty17** [comment]
Validated with` v2.11-07fc426551bfcf412d94d51f1860ed23901024f0-head`. The previously reported issue with stale secrets was not observed: https://github.com/rancher/rancher/issues/46894#issuecomment-2347835928
