### ISSUE TITLE
[BUG] Downstream v2 prov clusters fail to come up `active` behind proxy when using individual roles

### ISSUE THREAD

**Issue by Josh-Diamond** [rancher/rancher#47133]
**Rancher Server Setup**
- Rancher version: `v2.9.2-alpha6`
- Installation option (Docker install/Helm Chart): `Helm`

**Information about the Cluster**
- Kubernetes version: `v1.30.4+rke2r1`, `v1.30.4+k3s1`, `v1.29.8+rke2r1` - (doesn't seem k8s specific)
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? `Downstream AWS Node driver`

**User Information**
- What is the role of the user logged in? `Admin`

**Describe the bug**
When provisioning downstream node driver clusters behind a proxy, the cluster fails to come up `active`, with `HTTPS_PROXY`, `HTTP_PROXY`, and `NO_PROXY` agent env vars set.

**To Reproduce**
1. Fresh install of Rancher `v2.9.2-alpha6`
2. Provision a downstream v2 node driver cluster behind a proxy - (issue not k8s specific)
3. Reproduced

**Result**
Cluster fails to come up `active` and hangs in `Updating` state, with the UI displaying the following message:
`Non-ready bootstrap machine(s) jkeslar-k3s-proxy-pool1-<REDACTED>-<REDACTED> and join url to be available on bootstrap node`

Provisioning Logs:
```logs
8:57:00 am | [INFO ] waiting for at least one control plane, etcd, and worker node to be registered
-- | --
8:57:02 am | [INFO ] waiting for viable init node
8:57:14 am | [INFO ] configuring bootstrap node(s) jkeslar-k3s-proxy-pool1-<REDACTED>-<REDACTED>: waiting for agent to check in and apply initial plan
8:57:50 am | [INFO ] non-ready bootstrap machine(s) jkeslar-k3s-proxy-pool1-<REDACTED>-<REDACTED> and join url to be available on bootstrap node
```

Rancher Logs:
```
2024/09/16 17:06:32 [INFO] [planner] rkecluster fleet-default/jkeslar-k3s-proxy: non-ready bootstrap machine(s) jkeslar-k3s-proxy-pool1-<REDACTED>-<REDACTED> and join url to be available on bootstrap node
2024/09/16 17:06:32 [ERROR] error syncing 'c-m-<REDACTED>': handler cluster-deploy: cluster context c-m-<REDACTED> is unavailable, requeuing
2024/09/16 17:06:33 [ERROR] error syncing '_all_': handler user-controllers-controller: userControllersController: failed to set peers for key _all_: failed to start user controllers for cluster c-m-<REDACTED>: ClusterUnavailable 503: cluster not found, failed to start user controllers for cluster c-m-<REDACTED>:  requeuing
```

**Expected Result**
Cluster should come up `active`

**Screenshots**
![image (40)](https://github.com/user-attachments/assets/354e1a13-3ca6-4aea-a7ef-97425af66103)

**Additional context**
Issue not seen with single-node clusters

**Comment by Oats87** [comment]
The nodes that were failing were missing `localhost` from the `NO_PROXY` list.
