### ISSUE TITLE
Unable to rename a sidekick service

### ISSUE THREAD

**Issue by johnrengelman** [rancher/rancher#4715]
**Rancher Version:** 1.0.1

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

*_Steps to Reproduce: *_
Define a service w/ a sidekick and create.
Select service | edit

**Results:** 
Can rename the parent service, but no option to rename the sidekick service

**Expected:**
Be able to select the sidekick service in the edit dialogue and change it's name

When cloning an existing service that has a sidekick, a new unique name has to be selected. You are then unable to change this via the UI.

**Comment by tfiduccia** [comment]
Version - 2.0 master 10/19
We no longer allow you to rename any type of service in 2.0.  This bug is no longer applicable.
