### ISSUE TITLE
[BUG] CLI version is missing in the Versions table in the About page for `v2.8.8-alpha2`

### ISSUE THREAD

**Issue by markusewalker** [rancher/rancher#47151]
**Rancher Server Setup**
- Rancher version: `v2.8.8-alpha2`
- Installation option (Docker install/Helm Chart): Helm 
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: `v1.30.4+rke2r1`
- Cluster Type (Local/Downstream): Local
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Admin
  - If custom, define the set of permissions:

**Describe the bug**

In the about section, `v2.8.8-alpha2` is not showing the CLI version as shown below:

![image](https://github.com/user-attachments/assets/ecc260cf-226b-451e-87ea-81c4b0f5ad35)

In contrast to `v2.9.2-alpha2`, you see that it does appear:

![image](https://github.com/user-attachments/assets/0bff8256-e6b9-43fb-bcd6-7db4b2f5c7cf)

I verified that `v2.8.7` shows the same behavior as `v2.8.8-alpha2`, so it seems that this is has been an issue for some time. Unsure if this is intentional, but if not, there should be the same visual parity between the versions.

**To Reproduce**

1. Setup `v2.8.7` or `v2.8.8-alpha2`.
2. Go to the about section and note that the CLI row is missing in the table.

**Result**
The CLI row is missing in the versions table in the about page.

**Expected Result**

The CLI row should not be missing in the versions table in the about page.

**Comment by pmatseykanets** [comment]
At a first glance seems like a UI issue.

**Comment by pmatseykanets** [comment]
This happens because `cli-version` setting was never defined in v2.8 which is what UI code reads the value from.

**Comment by Jono-SUSE-Rancher** [comment]
Hey @pmatseykanets - didn't we resolve this for v2.10 with the PR we merged on release day?

**Comment by pmatseykanets** [comment]
@Jono-SUSE-Rancher This was never an issue for Rancher v2.9 and higher. In other words this is v2.8 specific issue. We have a tiny fix https://github.com/rancher/rancher/pull/47675 that was created at the time of code freeze for v2.8.8 but was never merged after.

**Comment by Jono-SUSE-Rancher** [comment]
Thanks for clarifying. I moved it into the next 2.8x.

**Comment by pmatseykanets** [comment]
Merged. We should be good for v2.8.11. /cc @Jono-SUSE-Rancher

**Comment by Priyashetty17** [comment]
Recreated the issue with **2.8.10**
<img width="592" alt="image" src="https://github.com/user-attachments/assets/f63fb9ae-8713-48c1-8d7d-56d67b711bf5">


Validated the fix with **v2.8-e9d623a5ff65b883f0b883e99c4477d8a629af43-head**
<img width="754" alt="image" src="https://github.com/user-attachments/assets/5e7ef4e7-7d7a-4d12-aa7a-4fe4572f703f">
