### ISSUE TITLE
[2.9] Add support for docker 27.2.x

### ISSUE THREAD

**Issue by mitulshah-suse** [rancher/rancher#47174]
Backport https://github.com/rancher/rancher/issues/47173

Add support for docker 27.2.x

Release notes:

https://docs.docker.com/engine/release-notes/27.2/
ref issue: https://github.com/rancher/rancher/issues/46326

**Comment by vivek-shilimkar** [comment]
Validated following docker install scripts on RHEL and Rocky (8.7, 8.8, 8.9, 8.10. 9.1, 9.2, 9.3, 9.4) and Ubuntu (22.04, 24.04) with node driver and custom clusters. Docker install scripts works as expected and RKE1 cluster provisions successfully.

`https://releases.rancher.com/install-docker-dev/27.1.2.sh`
`https://releases.rancher.com/install-docker-dev/27.2.0.sh`
`https://releases.rancher.com/install-docker-dev/27.2.1.sh`

**Comment by rishabhmsra** [comment]
On rancher v2.9-head:

- Validated below docker scripts on OL 8.10 and 9.4:
  - https://releases.rancher.com/install-docker-dev/27.1.2.sh
  - https://releases.rancher.com/install-docker-dev/27.2.0.sh
  
- Validated below docker script on OL 8.7, 8.8, 8.9, 8.10, 9.1, 9.2, 9.3, 9.4:
  - https://releases.rancher.com/install-docker-dev/27.2.1.sh

**Comment by mitulshah-suse** [comment]
@kinarashah can you please release these docker versions

**Comment by mitulshah-suse** [comment]
@kinarashah thanks for releasing the versions.. will raise PRs to set it to default version now..

**Comment by rishabhmsra** [comment]
Validated on rancher v2.9-head(a29543)
- Default version is set to 27.2.sh:

![docker-default-version-rancherv29](https://github.com/user-attachments/assets/3ae7c47e-ca47-4c33-b5b8-03dedbcf9435)

- Also provisioned RKE1 node driver cluster and the default docker version is 27.2.1.
