### ISSUE TITLE
[2.10] Add support for docker 27.2.x

### ISSUE THREAD

**Issue by mitulshah-suse** [rancher/rancher#47173]
Add support for docker 27.2.x

Release notes:

https://docs.docker.com/engine/release-notes/27.2/
ref issue: https://github.com/rancher/rancher/issues/46326

**Comment by rishabhmsra** [comment]
Validated on rancher v2.10-head:

- Docker script v27.2.1 validation completed on below OSes:
  - Ubuntu 24, 22
  - RHEL, Rocky and OL -> 8.7, 8.8, 8.9, 8.10, 9.1, 9.2, 9.3, 9.4

**Comment by mitulshah-suse** [comment]
Pending on setting default version to 27.2.x

**Comment by rishabhmsra** [comment]
Validated on rancher v2.10-head(v2.10-b51fb0249037fbd9cc177d4a90eccec47b5095cc-head)
- Default version is set to 27.2.sh:

![docker-default-version-rancherv29](https://github.com/user-attachments/assets/3ae7c47e-ca47-4c33-b5b8-03dedbcf9435)

- Also provisioned RKE1 node driver cluster and the default docker version is 27.2.1.
