### ISSUE TITLE
Remove sidekick button is broken

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4717]
**Version:** Master 0506

**Steps to Reproduce: **
1.  Create a service and Add a sidekick

**Results:** The remove sidekick button is broken
![image](https://cloud.githubusercontent.com/assets/11514927/15084095/1ed332aa-1386-11e6-8ba3-6b2ba9344442.png)

**Expected:**  Should not be broken

**Comment by vincent99** [comment]
i18n
