### ISSUE TITLE
[BUG] Failed to remove etcd+controlplane node from RKE1 cluster

### ISSUE THREAD

**Issue by kinarashah** [rancher/rancher#47185]
**Rancher Server Setup**
- Rancher version: v2.8.6 ≤ version < v2.9.0
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1

**Information about the Cluster**
- Kubernetes version: Any

**To Reproduce**
- Set up an RKE1 cluster with 3 control plane + etcd nodes (using 3 etcd-only nodes should also work, but I reproduced the issue with cp+etcd nodes) and 1 worker node.
- Remove one etcd node (removal via the UI should yield the same results as removing it through the cluster.yml file; I used cluster.yml).

**Result**
-  `[ERROR] [reconcile] Failed to delete etcd member [etcd-cp-etcd3] from etcd cluster `
- Node is removed from `kubectl get nodes` but still shows up under `docker exec etcd etcdctl member list` 

**Workaround**
`docker exec etcd etcdctl member remove 523195162740caa4` 

**Expected Result**
- Node is removed from both `kubectl get nodes` and `docker exec etcd etcdctl member list` 

**Additional context**
- The issue was introduced in Rancher v2.8.6 with RKE v1.5.11 due to an improper closing of the etcd client, which was part of [this change](https://github.com/rancher/rke/pull/3536). This problem does not appear in Rancher v2.9.x with RKE v1.6.x, as the fix was forward-ported after a [refactor of the etcd code](https://github.com/rancher/rke/pull/3573/files#diff-258cab59034848f0d36d759a4a7ba9cf9a96b73ba12d836647b58875e3eaf46d) in the v1.6 branch. Since the refactor addressed the issue in the v1.6.x series, the bug only affects v2.8.x versions starting from Rancher v2.8.6 with RKE v1.5.11. 

SURE-9011

**Comment by kinarashah** [comment]
**QA Steps:**

- Validate the reproduction scenario outlined in the issue description 
- Follow and validate the steps listed in [this comment](https://github.com/rancher/rancher/issues/45309#issuecomment-2181502432)

**Comment by kinarashah** [comment]
RKE PR is merged, will bump RKE in Rancher `release/v2.8` after v2.8.8 is released.

**Comment by kinarashah** [comment]
Available to test with RKE RC `v1.5.14-rc.1` and Rancher `v2.8-head`.

**Comment by Josh-Diamond** [comment]
Ticket #47185 - Test Results - ✅ 
---
 
 Verified with HA Helm on Rancher `v2.8-b35702e0d86bc6e9fa789045fa455ba836886b52-head` using RKE `v1.5.14-rc.1`:

| Scenario | Test Case | Result |
|---|---|---|
| 1. | Remove node from all-roles cluster with etcdctl | ✅ |
| 2. | Remove node from all-roles cluster | ✅ |
| 3. | Remove node from split-roles cluster with etcdctl | ✅ |
| 4. | Remove node from split-roles cluster | ✅ |
 
---
 
Scenario 1 - ✅ 
1. Create a downstream 3 node all-roles rke1 cluster
2. SSH into the node and remove a node using `docker exec etcd etcdctl member remove <member_id>`
3. Delete the node in the UI
4. Verified - The node gets properly deleted and does not hang.

---

Scenario 2 - ✅ 
1. Create a downstream 3 node all-roles rke1 cluster
2. Delete the node in the UI
3. Verified - The node gets properly deleted and does not hang.

---

Scenario 3 - ✅ 
1. Create a downstream 3 node split-roles rke1 cluster
2. SSH into the node and remove a node using `docker exec etcd etcdctl member remove <member_id>`
3. Delete the node in the UI
4. Verified - The node gets properly deleted and does not hang.

---

Scenario 4 - ✅ 
1. Create a downstream 3 node split-roles rke1 cluster
2. Delete the node in the UI
3. Verified - The node gets properly deleted and does not hang.
