### ISSUE TITLE
No stats with docker 1.11.1

### ISSUE THREAD

**Issue by bartoszbednarek** [rancher/rancher#4718]
On two nodes using 1.9.1 there are statistics for every docker container. On both 1.11.1 there are no stats available and there is only "Connecting".

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.1.0-dev1` Cattle: `v0.160.3` UI: `v1.0.7`

**Comment by deniseschannon** [comment]
Duplicate of https://github.com/rancher/rancher/issues/4406
