### ISSUE TITLE
[BUG] Keycloak OIDC configuration forces using obsolete /auth/ path

### ISSUE THREAD

**Issue by tsunamaru** [rancher/rancher#47205]
**Rancher Server Setup**
- Rancher version: 2.9.2
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): v1.30.5+k3s1
- Proxy/Cert Details: N/A

**Information about the Cluster**
- Kubernetes version: v1.30.5+k3s1
- Cluster Type (Local/Downstream): Local
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Admin

**Describe the bug**

Starting from Keycloak v25.0.0, `/auth/` subpath is now removed for authentication endpoint.
Rancher in UI doesn't let user delete `/auth/` from URL and as such, integration with Keycloak OIDC v25.0.0 or higher is now impossible.

**To Reproduce**

1. Navigate to 'Users & Authentication'
2. Select 'Auth provider'
3. Select 'Keycloak OIDC'
4. Enter endpoint URL
5. Select 'Specify'
6. Try delete `/auth/` from 'Issuer' or 'Auth endpoint' field

**Result**
`/auth/` immediately appears back

**Expected Result**

`/auth/` string stays removed

**Screenshots**

https://github.com/user-attachments/assets/d03e2bdc-a7f8-4943-b028-f6324d068113

**Additional context**

**Comment by bpedersen2** [comment]
Duplicate of #38480.

**Comment by tsunamaru** [comment]
@bpedersen2 thanks, closing this one then.
