### ISSUE TITLE
[v2.9] [BUG] rancher deployed on arm machines cannot provision Harvester VM's

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#47238]
`rancher/rancher` tracking issue for https://github.com/harvester/harvester/issues/6053 (for 2.9)

**Comment by Sahota1225** [comment]
Moving the issue to ready for QA, as the PR is merged

**Comment by snasovich** [comment]
Closing as duplicate of https://github.com/rancher/rancher/issues/47547 (same as https://github.com/rancher/rancher/issues/47269#issuecomment-2417682622)
