### ISSUE TITLE
[v2.10] Bump rancher/mirrored-jimmidyson-configmap-reload for rancher-alerting-drivers

### ISSUE THREAD

**Issue by mallardduck** [rancher/rancher#47234]
One the initial chart for 2.10 is merged: https://github.com/rancher/charts/pull/4476

We will need to bump the version of `rancher/mirrored-jimmidyson-configmap-reload` used from `0.8.0` up to `v0.13.1`. We recently mirrored this new version here: https://github.com/rancher/image-mirror/pull/718

We should also backport this change to at least 2.8-2.9; maybe 2.7.

---

To test this image:

1. Install `rancher-alerting-drivers` with `Enable SMS` checked, (this should deploy sachet)
2. Find the deployment named `rancher-alerting-drivers-sachet` then click `View Logs` on pod,
    - May want to tail logs from CLI so it doesn't break log connection like UI can tend to do.
3. In the logs view select `config-reloader` container,
4. Open the `Related Resources` tab and find the `ConfigMap` named `rancher-alerting-drivers-sachet`,
5. Edit the ConfigMap yaml - even just adding a new comment into it then save,
    - I added `# test` into the `data[config.yaml]` field under existing content 
6. Upon hitting save it will modify the configmap and shortly after you should see the log respond in kind.

Successful logs will see from `config-reloader` something similar to this:
```
2024/09/27 16:15:20 config map updated
2024/09/27 16:15:20 performing webhook request (1/1)
2024/09/27 16:15:20 successfully triggered reload
```

Followed by the `sachet` container showing:
```
2024/09/27 16:15:20 handlers.go:103: Loading configuration file /etc/sachet/config.yaml
```

**Comment by pankajsqe** [comment]
Pass : for bump the version of `rancher/mirrored-jimmidyson-configmap-reload` used from 0.8.0 up to v0.13.1 was successfully tested and regression passed as well.

Details
rancher : v2.10-head
cluster RKE2
rancher-alerting-drivers:105.0.0-rc.1
rancher-logging:105.0.0-rc.1+up4.8.0

![Image](https://github.com/user-attachments/assets/fbb84dfb-ee5f-4479-8b52-c0046f9d1688)
![Image](https://github.com/user-attachments/assets/a56c576d-779a-4e9d-bfc6-f39e6d9c37a2)
![Image](https://github.com/user-attachments/assets/2f7edb24-3dca-4345-9a60-6264075cbd93)
