### ISSUE TITLE
[v2.9] Regular Shell version bump

### ISSUE THREAD

**Issue by mallardduck** [rancher/rancher#47245]
Per title, this is just an issue to track QA work on regular shell bump for this dev cycle.

**Comment by pankajsqe** [comment]
Verified rancher shell version bump to v0.2.2-rc.2.

**Details**
Rancher : v2.9-head
Cluster : Local(RKE) and downstream (AKS)
Shell : rancher/shell:v0.2.2-rc.2

![Image](https://github.com/user-attachments/assets/44939a1d-1e88-42bf-8c9b-bf16fd13eb5b)
