### ISSUE TITLE
[Feature] k8s 1.31 Support for `rancher/shell`

### ISSUE THREAD

**Issue by mallardduck** [rancher/rancher#47246]
Add k8's 1.31 support for `rancher/shell`

Depends on: https://github.com/rancher/helm/pull/52

First shell image with support for 1.31 is: [v0.3.0-rc.2](https://github.com/rancher/shell/releases/tag/v0.3.0-rc.2)

**Comment by pankajsqe** [comment]
k8s 1.31 Support for rancher/shell has been validated successfully on 2.10.0-alpha7

![Image](https://github.com/user-attachments/assets/faf87d03-be0a-4fcf-bd7e-cda104e65e4b)
![Image](https://github.com/user-attachments/assets/28c9eb44-9589-449a-8741-fd3590ef6733)
![Image](https://github.com/user-attachments/assets/14fef131-72f4-4406-9765-c3edb619eadf)
