### ISSUE TITLE
Clicking on Vm link from "Virtual Machines" list directs user to  "404 Not Found" page.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#4724]
Rancher Version: Build form master

Deploy VMs ( as standalone / service).
Go to Infrastructure/VirtualMachines page and click on the VM name link.
User is directed to  "404 Not Found" page.

Request Url - http://<ipaddress>:8080/v1/projects/1a5/containers/1i2177?include=services

Url should point to virtualmachines instead of containers

<img width="1377" alt="screen shot 2016-05-06 at 4 14 25 pm" src="https://cloud.githubusercontent.com/assets/4266958/15088267/35a3512a-13a6-11e6-926d-62fa69442cd5.png">

**Comment by sangeethah** [comment]
This issue is also seen when clicking the VM name from Application/Stacks/Selecting VM service and clicking on any of the VM containers.

**Comment by vincent99** [comment]
#4759
