### ISSUE TITLE
[RFE] Cloud Credentials Expiry field support

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#47241]
**Is your feature request related to a problem? Please describe.**
To support https://github.com/rancher/dashboard/issues/11332, corresponding backend changes are needed.

**Describe the solution you'd like**
From RFC 010:
> Rancher’s backend will add an annotation (for example, cattle.io/expiryTime) indicating when the cloud credential will expire. This annotation will be defined as an epoch time, allowing for credentials to be sorted by expiration. Support for this annotation will at first be limited to Harvester Cloud Credentials, but may be expanded to other Cloud Credential types (e.x. Digital Ocean, AWS, Azure) if possible.

**Describe alternatives you've considered**
Service account type based solution is tracked per https://github.com/rancher/rancher/issues/44912 / https://github.com/rancher/dashboard/issues/11271

**Additional context**
N/A

**Comment by khushboo-rancher** [comment]
This is validated as a part of https://github.com/rancher/rancher/issues/47667 and should be okay to close.
@m-ildefons please confirm and reopen if needed.

**Comment by m-ildefons** [comment]
That's correct.
