### ISSUE TITLE
[Backport v2.9] [RFE] Cloud Credentials Expiry field support

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#47243]
Backport of https://github.com/rancher/rancher/issues/47241 to v2.9.x line of releases.

**Comment by irishgordo** [comment]
@jakefhyde  thanks for this addition :smile: :+1:  -> I'm going to go ahead and close this out as this has already been validated in:

- https://github.com/rancher/rancher/issues/47492#issuecomment-2412131230
( Havester v1.3.2 & (Rancher v2.9.3-alpha5 & Rancher v2.9-head (v2.9-9fa98c1a0843dbee3d8ea9ffc2e84a891f2696c3-head) ) )

cc: @khushboo-rancher @bk201
