### ISSUE TITLE
[BUG] Azure AD China auth returning "error status code received from the API"

### ISSUE THREAD

**Issue by JacieChao** [rancher/rancher#47251]
**Rancher Server Setup**
- Rancher version: v2.9.0

**Describe the bug**
When attempting to setup AzureAD authentication and using China Azure, the testAndApply will return an error during the setup.
```
server error while authenticating: getting UserInfo from Azure: getting user by ID: error status code received from the API.
```

**To Reproduce**

1. Deploy Rancher v2.9.0
2. Register Rancher with Azure China and set the Redirect URI to  `<MY_RANCHER_URL>/verify-auth-azure`.
3. Create a new client secret and save it.
4. Set required API permissions for Rancher. 
5. Allow Public Client Flows.
6. Copy Azure China application data to the forms in Rancher AzureAD authentication provider. The endpoints should be selected for China.
7. Click Save and login to Azure account from the popup window. 

**Result**

Setup of Azure AD China Auth provider fails.
![image](https://github.com/user-attachments/assets/247b5d7e-e288-4644-b5a1-732427d3bc59)

**Expected Result**
Setup of Azure AD China Auth provider authenticates successfully and is usable

**Screenshots**

The API permissions list:
![QQ_1727251223031](https://github.com/user-attachments/assets/d6ef0361-b0e9-4837-82b6-fc4e4981caa1)

**Additional context**

I have confirmed this issue does not exist on v2.8.7. The replacement of msgragh client dependency may cause this issue.

I checked issues from Microsoft Graph client SDK and found [this issue](https://github.com/microsoftgraph/msgraph-sdk-go/issues/26). We didn’t set the base url with the China region for [graphClient here](https://github.com/rancher/rancher/blob/v2.9.0/pkg/auth/providers/azure/clients/ms_graph_client.go#L86). In my investigation, the [baseUrl value of the client adapter will be empty](https://github.com/microsoft/kiota-http-go/blob/v1.0.0/nethttp_request_adapter.go#L84) by the way we construct the graphClient. The `graphClient.Users` will [use the global Azure graph API](https://github.com/microsoftgraph/msgraph-sdk-go/blob/v1.0.0/graph_base_service_client.go#L154) which is not available to get users for Azure China.

**Comment by JacieChao** [comment]
https://jira.suse.com/browse/SURE-9069

**Comment by Priyashetty17** [comment]
Das to pick this for QA - QA/S

**Comment by rootwuj** [comment]
Verified on v2.9.5-alpha1  and v2.9.4 >> v2.9.5-alpha1

Verified Azure AD can be successfully connected by selecting China Endpoint.
Verified Azure users can log in and have correct permissions.
Verified that after upgrading from v2.9.4 to v2.9.5-alpha1, Azure AD China can be successfully connected.

Test steps:

1. Register Rancher with Azure China and set the Redirect URI to <MY_RANCHER_URL>/verify-auth-azure.
2. Create a new client secret and save it.
3. Set required API permissions for Rancher.
4. Allow Public Client Flows.
5. Copy Azure China application data to the forms in Rancher AzureAD authentication provider. The endpoints should be selected for China.
6. Click Save and login to Azure account from the popup window.
7. The Azure AD auth provider becomes active.
8. Add Azure user `user1` as [Cluster Member], log in with `user1`, and verify that the user permissions are correct.  
9. Add Azure user `user2` as [Project Owner], log in with `user2`, and verify that the user permissions are correct.

![image](https://github.com/user-attachments/assets/89b899db-ee3d-4371-8879-7ae915051c06)
