### ISSUE TITLE
Do not allow size to be set for "ROOT" volumes when creating VMs.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#4725]
Rancher Version: Build form master

When creating VMs ( as standalone containers/ services) , currently user is allowed to pick a size for ROOT disk. 
Since ROOT volume size is going to be always based off the image , we should not allow users to set a size for ROOT volumes. They should be allowed to set size only for DATA volumes.

**Comment by tfiduccia** [comment]
Version - master 5/13
Verified fixed
