### ISSUE TITLE
can not connect to shell and unable to see status

### ISSUE THREAD

**Issue by duardito** [rancher/rancher#4726]
**Rancher Version:1.1.0-dev1

**Docker Version: 1.10.3

**OS and where are the hosts located?  debian 8, server/rancher is in same host.

I followed getstarted installation steps.

I am having some problems :

1.- I can not see stats in each container, I always see "Connecting.." , I had same problem with latest docker version , but I think I have correct version now.

2.- I can not connect to shell, when I click in "Exceute shell" ,  console opens but it keeps "Initializing.."

Lookoing at chrome console I see errors.
WebSocket connection to 'ws://samuris.com:9595/v1/containerstats...........failed: Invalid frame header

**Comment by deniseschannon** [comment]
We have seen this happen typically with time sync issues. 

http://docs.rancher.com/rancher/latest/en/faqs/troubleshooting/#help-i-cannot-execute-the-shell-or-view-logs-of-the-container-from-the-ui-how-does-rancher-access-the-shelllogs-of-a-container

Can you confirm that your Rancher server and agents have the same time?

**Comment by deniseschannon** [comment]
@duardito If you're still facing issues, please re-open and provide more details.
