### ISSUE TITLE
[Backport v2.7] [BUG] Inadvertent removal of SSH from rancher/machine

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#47268]
Backport of https://github.com/rancher/rancher/issues/45173 for 2.7.x.

**Comment by jiaqiluo** [comment]
The fix can be validated on the lastest rancher v2.7-head image. Please refer to the original issue for more information.

**Comment by susesgartner** [comment]
Ticket #45173 - Test Results - ✅
---
 
| Scenario | Test Case | Result |
|---|---|---|
| 1. | Provision a downstream RKE2 cluster | PASS |

---
Verified with HA Helm on Rancher `
v2.7-bd0bb772b60a447d352789b3d7c4368ffe50eecf-head`:
---
 
Scenario 1: Provision a downstream RKE2 cluster 
---
1. Provision a downstream RKE2 cluster with Centos 9 as the OS
2. Verify that the cluster comes up active 
3. Verify you can ssh to the node through rancher.
 
Results: The cluster came up active and all pods are in a stable state.
