### ISSUE TITLE
Are healthchecks messed up?

### ISSUE THREAD

**Issue by clicman** [rancher/rancher#4727]
I have stack with 3 services. Two of these has healthcheck enabled.
1st service (site) performs GET request to /healthcheck url
2nd one (api) check for tcp port 5099 open
![image](https://cloud.githubusercontent.com/assets/1079535/15091502/94c5bb36-146c-11e6-80cb-d2c607f95105.png)

![image](https://cloud.githubusercontent.com/assets/1079535/15091456/93455b46-146b-11e6-8334-9f2f09660ade.png)

But I can see what apiservice is in unheathly state. And in logs I see:
![image](https://cloud.githubusercontent.com/assets/1079535/15091470/ea1bed4a-146b-11e6-9e51-208b59ca33f3.png)

Here is containers Healtheck tab view:
![image](https://cloud.githubusercontent.com/assets/1079535/15091486/274a6098-146c-11e6-8690-a3b54b8aa79a.png)

At same time I see what it is no healthcheck activity in site container logs.

P.S. Docker version on this host is 1.11.1

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.1.0-dev1` Cattle: `v0.160.3` UI: `v1.0.7` |
|Access|`github` `admin`|
|Route|`service.containers`|

**Comment by clicman** [comment]
Host restart solved the problem.

**Comment by deniseschannon** [comment]
It looks like you had something going on with your networking between your hosts. Please open a new issue if you encounter it again. Typically, if health checks go south, the first thing to check if the networking between your hosts is working by execing into the network agent and pinging the IP (10.42.x.x) of the network agent on another host.
