### ISSUE TITLE
Unable to register host on Arch Linux Latest

### ISSUE THREAD

**Issue by alfonsodg** [rancher/rancher#4728]
**Rancher Version:**
1.0.1

**Docker Version:**
1.11.1

**OS and where are the hosts located? (cloud, bare metal, etc):**
Arch Linux last updated in Bare Metal

**Setup Details: (single node vs. single node, internal DB vs. external DB)**
single node

**Steps to Reproduce: **
Just install rancher with docker run -d --restart=always -p 8080:8080 rancher/server, wait for connect and add a host, the client logs shows: b2016-05-07T11:25:04.687145483Z Error response from daemon: 400 Bad Request: malformed Host header

**Results:**
Can't manage the client

**Expected:**
2 weeks ago i can manage all whitout problems, however some package update modifies the behaviour

**Comment by faddat** [comment]
Rancher Version:
1.1-dev1

Rancher Agent Version:
Tried 1.0.1 & rancher/agent:latest

Docker Version:
1.10.3

OS and where are the hosts located? (cloud, bare metal, etc):
Metal

Setup Details: (single node vs. single node, internal DB vs. external DB)
1 Master, 3 agents, one of which is the master

*Steps to Reproduce: *
Just install rancher with docker run -d --restart=always -p 8080:8080 rancher/server, wait for connect and add a host, the client logs shows: �b2016-05-07T11:25:04.687145483Z Error response from daemon: 400 Bad Request: malformed Host header

My error is EXACTLY  the same as @alfonsodg's.  It's not even a little different. 

Results:
Agent cannot connect to server.  

Expected:
Agent to be able to connect to server.

**Comment by vincent99** [comment]
This sounds just like https://github.com/rancher/rancher/issues/4500#issuecomment-213071348 , are you using the distros package and is it compiled with golang 1.6? (on my phone and can't remember which, but it's in either `docker info` or `docker version`)

**Comment by faddat** [comment]
I am using the distro packages.  Strange, though:  I'd tried the docker packages but something else was amiss-- maybe they were not related, I'll check that and get back to you.

**Comment by faddat** [comment]
Yes, 1.6.1

I guess I will reinstall the docker-provided version and see how that goes!

**Comment by MetalMatze** [comment]
Having the same problem right now on Arch. What's that _docker-provided_ version? AUR?

**Comment by MetalMatze** [comment]
Hey @faddat, do you mind sharing what the _docker-provided_ version is? Thanks!

**Comment by faddat** [comment]
Sorry, I can not-- that VM is long since deleted.  If it happens again, I
will grab it.

**Comment by flypenguin** [comment]
I also have this issue. Kinda annoying :) . Any updates by anyone?

**Comment by MetalMatze** [comment]
I did a work around. Take a look at the AUR. There's an issue for this case. They provided a PKGBUILD to install the docker binary directly from github and not a self compiled. It works, I guess. If you need more infos let me know, not at home right now.

**Comment by masterkorp** [comment]
I have this problem too. @MetalMatze Can you give the name of the package?

**Comment by deniseschannon** [comment]
Now that Rancher suppports Docker 1.11, please re-open if you are still facing this issue.

**Comment by MetalMatze** [comment]
I'm not sure. I could test this with the docker provided by Arch Linux again.

**Comment by darkadan** [comment]
It still has the same error, the build version of go1.6.2 delivering archlinux repository.

![screenshot at 19-07-2016_13 11 23](https://cloud.githubusercontent.com/assets/379136/16961343/ada9fc0a-4db2-11e6-94f7-4508baffcda2.png)

![screenshot at 19-07-2016_13 15 26](https://cloud.githubusercontent.com/assets/379136/16961384/e0c59f4a-4db2-11e6-87a5-5ca6ee19ec59.png)

With direct compiled version of docker can demonstrate the build of go1.5.4 and the agent is connecting properly.

![screenshot at 19-07-2016_13 19 01](https://cloud.githubusercontent.com/assets/379136/16961537/8f8586d0-4db3-11e6-801b-e617b901b0bd.png)
