### ISSUE TITLE
[v2.8] update security-scan version in rancher-cis-benchmark chart

### ISSUE THREAD

**Issue by vardhaman22** [rancher/rancher#47295]
there were some new [changes](https://github.com/rancher/security-scan/pull/248) introduced in security-scan for a few CIS profile checks after last release so we need to update the security-scan version in CIS chart.
profiles impacted
1. rke2-cis-1.7-permissive
2. rke2-cis-1.7-hardened
3. rke2-cis-1.8-permissive
4. rke2-cis-1.24-permissive
5. rke2-cis-1.24-hardened

**Comment by vivek-shilimkar** [comment]
Tested the changes in the 1.8-profile and 1.7 profile on rancher v2.8.8 with CIS Benchmark chart version 5.5.0-rc1. 

Updated profiles show expected results on RKE2 k8s v1.28 and v1.25. Hence, this ticket can be closed.
