### ISSUE TITLE
[v2.9] update security-scan version in rancher-cis-benchmark chart

### ISSUE THREAD

**Issue by vardhaman22** [rancher/rancher#47294]
there were some new [changes](https://github.com/rancher/security-scan/pull/248) introduced in security-scan for a few CIS profile checks after last release so we need to update the security-scan version in CIS chart.
profiles impacted
1. rke2-cis-1.7-permissive
2. rke2-cis-1.7-hardened
3. rke2-cis-1.8-permissive
4. rke2-cis-1.24-permissive
5. rke2-cis-1.24-hardened

**Comment by vivek-shilimkar** [comment]
Tested the changes in the 1.8-profile on rancher v2.9.2 with CIS Benchmark chart version 6.3.0-rc1. 

Updated profiles show expected results on RKE2 k8s v1.30.4. Hence, this ticket can be closed.
