### ISSUE TITLE
2.9-head Validate RKE1 with SUSE OSes and Docker 25

### ISSUE THREAD

**Issue by daviswill2** [rancher/rancher#47302]
**On 2.9-head Rancher**

OS | Private AMI | Public AMI | User
-- | -- | -- | --
SLES 15 SP 6 |   |ami-0371c70ae504994fd|ec2-user
SLES 15 SP 5 |   |ami-03d7a2df9ef09fb52 | ec2-user 
openSUSE 15.6 | | ami-0e0a70fb88abfa825 | ec2-user
openSUES 15.5 |ami-07f08ca3021bfa7be | |ec2-user |

**Comment by rishabhmsra** [comment]
On rancher v2.9-head, provisioned RKE1 node driver and custom clusters using k8s v1.30. All clusters provisioned successfully.
Note : on sles 15sp5 and open suse 15.5, manually upgraded the docker version from 24 to 25 and then provisioned clusters.
All checks passed, hence closing it.
