### ISSUE TITLE
external-dns keep ips of disable host / unhealthy container

### ISSUE THREAD

**Issue by ahfeel** [rancher/rancher#4730]
**Rancher Version: 1.0.1**

**Environment Type: Cattle**

In my understanding, external-dns is supposed to keep the DNS updated with reachable ips for a given service. I therefore thought that disabling an host (through the Rancher UI) would make external-dns remove its IP from the provider (cloudflare in my case), but it didn't. I tried also totally stopping the machine, same result.

I went through the code of external-dns and it seems it takes every container entries returned by the Rancher Metadata API, regardless of the "health_state" field that states whether or not this container is healthy. Shouldn't that be checked ?

To take in account the other case (Host DISABLED), how could we proceed ? It seems the metadata API doesn't provide any information about that. It should be useful to have a state reflected in the container (as there's no host concept in the metadata api) to have for example "health_state": "disabled" or something like that ?

The usecase for me is to deal easily with a machine having an issue by disabling it and then checking what's wrong before putting it back in the pool again, without having to remove it completely from Rancher.

**Comment by ibuildthecloud** [comment]
External DNS does not look at health state as it's basically assumed that if the health state is bad Rancher will take action to delete the bad instance and deploy good ones.  Then external DNS will be updated with the new good addresses.

The specific use case you are looking at will not work as you intended.  If you deactivate a host we do don't consider that host to be bad.  An inactive host only means to Rancher that we shouldn't put new things on that host.  You would have to actually delete that host for rancher to do anything.

**Comment by ahfeel** [comment]
Hi Darren,

Thank's for the quick response ! I understand your point of view, but wouldn't my usecase be also a good idea ?

Secondary question then, how often is the external-dns service supposed to update the DNS ? I just tried to upgrade the concerned service (httpd), so it was not redeployed to the disabled host, but it seems external-dns is not updating anything so far and it's been already ~5mns.

**Comment by deniseschannon** [comment]
@ahfeel Did your services have health checks on them? Without health checks, services will remain on a host (either an `inactive` or `reconnecting` host). If a health check was on the service, then the containers would be re-scheduled to a new host and external-dns should update accurately. 

external-dns should update fairly quickly. 5 minutes seems too long. Which catalog are you using?

**Comment by deniseschannon** [comment]
@ahfeel If you are still facing issues and can provide more details to the questions I had asked, please re-open.
