### ISSUE TITLE
is there a way to modify rancher-compose.yml?

### ISSUE THREAD

**Issue by danlanxiaohei** [rancher/rancher#4731]
i want to modify the scale number in rancher-compose.yml? 

which api can i use?

"…/v1/projects/1a1/environments/1e1/?action=upgrade" dose not work

**Comment by aemneina** [comment]
Hi @danlanxiaohei , looks like you're trying to call scale on a stack rather than a service.... try something like:  ".../v1/projects/1a5/services/1s5". Let me know if that helps.

**Comment by deniseschannon** [comment]
@danlanxiaohei If you still have questions, please re-open.
