### ISSUE TITLE
[Backport v2.9] [BUG] high memory usage for the aks.(*aksOperatorController).onClusterChange

### ISSUE THREAD

**Issue by aruiz14** [rancher/rancher#47317]
Backport #45509

**Comment by gaktive** [comment]
Since we have time, let's get this in for 2.9.3. We will not backport to 2.8.x or before

**Comment by aruiz14** [comment]
## Validation Template

## Root Cause
Recent updates to the `client-go` Kubernetes client [changed the behaviour when caching network clients](https://github.com/kubernetes/kubernetes/issues/125818). This caused our use case to go from never caching clients to add a new cache entry for every client usage, which tied to this cache not having any cleanup mechanism or retention period causes the memory usage to grow indefinitely.

## What was fixed, or what change have occurred
We adapted our Kubernetes client configuration to make the underlying caching possible while keeping the level of customization that our use case requires.

## Areas or cases that should be tested

Creating a new managed cluster from a public cloud provider (AKS, GKE or EKS), then perform basic checks to ensure it works as expected: creation succeeds, it's connected and can be browsed from the Rancher UI.
The [reproducer instructions in the original issue](https://github.com/kubernetes/kubernetes/issues/125818) could also be used to verify the changes cause the desired effect (which was already verified on a customer side via provided hotfix image).

## What areas could experience regressions
Connectivity with provisioned downstream clusters.

**Comment by MSpencer87** [comment]
**Verified on Rancher v2.9.3-alpha6, rke2 v1.28.8+rke2r1**

Continuous memory usage increase no longer present for `aks.(*aksOperatorController).onClusterChange` from Azure AKS cluster deployments

**Steps to reproduce:**
1. Bring up HA Rancher v2.9.2
2. Access Azure, create 3 AKS clusters (_using 1.28.0, 1.27 no longer available in defaults_) 
- Home -> Kubernetes services -> Create+ -> Kubernetes cluster
3. Create Cloud Credentials in Rancher for Azure
- To obtain credentials use:
```
az login

az ad sp create-for-rbac --role Contributor --scopes /subscriptions/{ID FROM LOGIN OUTPUT} --name {YOUR NAME}
```
`id` for Subscription ID, `appId` for Client ID and `password` for Client Secret

4. Import the AKS clusters into Rancher, wait for Active status
- Home -> Cluster Management -> Import Existing -> Azure AKS
5. Set kubeconfig for local/upstream cluster and execute patch script for deployment emulation
```
while true
do
	for cluster in $(kubectl get clusters.management.cattle.io --no-headers -o custom-columns=name:.metadata.name | grep -v local)
	do
	  kubectl patch clusters.management.cattle.io ${cluster} --type='json' -p='[{"op": "replace", "path": "/status/serviceAccountTokenSecret", "value":""}]'
  done
done
```
Downstream AKS clusters can be observed toggling between `Active` and `Unavailable` status as outputs aggregate:
```
cluster.management.cattle.io/c-xxxxx patched
cluster.management.cattle.io/c-xxxxx patched
cluster.management.cattle.io/c-xxxxx patched
cluster.management.cattle.io/c-xxxxx patched
```
6. In a separate terminal, set kubeconfig for local/upstream cluster and execute heap monitor script
```
while true; do
	for pod in $(kubectl -n cattle-system get pods -l app=rancher --no-headers -o custom-columns=name:.metadata.name); do
		kubectl exec -n cattle-system ${pod} -c rancher -- curl -s http://localhost:6060/debug/pprof/heap -o heap
		kubectl cp -n cattle-system -c rancher ${pod}:heap ./heap

		go tool pprof -top --trim=false --show_from=generateAndSetServiceAccount ./heap | grep kubernetes.NewForConfig
	done
done
```

Flame Graph can be viewed using pprof locally, Note: To view `aks.(*aksOperatorController).onClusterChange` ensure heap data is not loaded from `ShowFrom expression matched no samples` curl. 

Output indicates increasing memory usage over time while deployment emulation script is running, memory usage does not decrease when script is stopped and clusters return to holding Active status for several minutes

```
         0     0%  8.65%    10.51MB  5.51%  k8s.io/client-go/kubernetes.NewForConfig
ShowFrom expression matched no samples
ShowFrom expression matched no samples
         0     0%  8.65%    10.51MB  5.51%  k8s.io/client-go/kubernetes.NewForConfig
ShowFrom expression matched no samples
ShowFrom expression matched no samples
         0     0%  9.15%    10.51MB  5.82%  k8s.io/client-go/kubernetes.NewForConfig
ShowFrom expression matched no samples
ShowFrom expression matched no samples
         0     0%  9.15%    10.51MB  5.82%  k8s.io/client-go/kubernetes.NewForConfig
ShowFrom expression matched no samples
ShowFrom expression matched no samples
         0     0%  8.87%    11.01MB  5.74%  k8s.io/client-go/kubernetes.NewForConfig
ShowFrom expression matched no samples
ShowFrom expression matched no samples
         0     0%  8.87%    11.01MB  5.74%  k8s.io/client-go/kubernetes.NewForConfig
ShowFrom expression matched no samples
ShowFrom expression matched no samples
         0     0%  9.31%    11.01MB  6.02%  k8s.io/client-go/kubernetes.NewForConfig
ShowFrom expression matched no samples
ShowFrom expression matched no samples
         0     0%  9.31%    11.01MB  6.02%  k8s.io/client-go/kubernetes.NewForConfig
ShowFrom expression matched no samples
ShowFrom expression matched no samples
         0     0%  8.99%    11.01MB  5.81%  k8s.io/client-go/kubernetes.NewForConfig
```

A few minutes later with deployment emulation script still running (`ShowFrom expression matched no samples` removed):

```
         0     0% 15.34%    21.53MB 10.63%  k8s.io/client-go/kubernetes.NewForConfig
         0     0% 15.34%    21.53MB 10.63%  k8s.io/client-go/kubernetes.NewForConfig
         0     0% 13.96%    21.53MB  9.68%  k8s.io/client-go/kubernetes.NewForConfig
         0     0% 15.35%    21.53MB 10.64%  k8s.io/client-go/kubernetes.NewForConfig
         0     0% 15.35%    21.53MB 10.64%  k8s.io/client-go/kubernetes.NewForConfig
```

Several minutes later, after deployment emulation script stopped (`ShowFrom expression matched no samples` removed):

```
         0     0% 17.55%    25.03MB 11.86%  k8s.io/client-go/kubernetes.NewForConfig
         0     0% 17.36%    25.03MB 11.73%  k8s.io/client-go/kubernetes.NewForConfig
         0     0% 17.36%    25.03MB 11.73%  k8s.io/client-go/kubernetes.NewForConfig
         0     0% 17.36%    25.03MB 11.73%  k8s.io/client-go/kubernetes.NewForConfig
         0     0% 17.36%    25.03MB 11.73%  k8s.io/client-go/kubernetes.NewForConfig
         0     0% 17.36%    25.03MB 11.73%  k8s.io/client-go/kubernetes.NewForConfig
```

**Steps for validation:**
1. Bring up HA Rancher v2.9.3-alpha6
2. Access Azure, create 3 AKS clusters
3. Create Cloud Credentials in Rancher for Azure
4. Import the AKS clusters into Rancher, wait for Active status
5. Set kubeconfig for local/upstream cluster and execute patch script for deployment emulation
6. In a separate terminal, set kubeconfig for local/upstream cluster and execute heap monitor script
7. Verify only `ShowFrom expression matched no samples` outputs are present, `aks.(*aksOperatorController).onClusterChange` was not found in flame graphs
8. Verify flame graphs indicate no increasing memory usage on any aks components over time or while deployment emulation script is running. Memory usage is not impacted from any aks components when script is stopped or after clusters return to holding Active status for several minutes.
