### ISSUE TITLE
[2.8] Backport Logging Rebase

### ISSUE THREAD

**Issue by jbiers** [rancher/rancher#47323]

**Comment by pankajsqe** [comment]
Backport Logging Rebase validated successfully along with chart release of v2.8.9

Details
Details :
Rancher : v2.8.9-alpha10
cluster : v1.28.7+rke2r1
rancher-logging:103.1.2+up4.4.0

**Comment by prachidamle** [comment]
Since it was tested and released on 2.8.9, updating the milestone accordingly
