### ISSUE TITLE
[Question] File config rancher-metadata and internal-dns

### ISSUE THREAD

**Issue by phucvinh52** [rancher/rancher#4732]
Hi rancher team,
I have a question:
Do file answers.yml (rancher-metadata), answers.json (internal-dns) are generated and auto updated by Cattle.
Thanks.

**Comment by ibuildthecloud** [comment]
Yes, cattle generates the config and pushes it down to the containers running metadata and DNS.

**Comment by phucvinh52** [comment]
Hi @ibuildthecloud ,
Thank for your response. Have a good day.
