### ISSUE TITLE
[BUG] etcd snapshot count reported in rancher is incorrect when taking manual snapshot with s3 enabled on rke2 clusters, but is correct in s3

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#47339]
**Rancher Server Setup**
- Rancher version: 2.9.2
- Installation option (Docker install/Helm Chart): helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): k3s 1.30.5+k3s1
- Proxy/Cert Details: rancher certs

**Information about the Cluster**
- Kubernetes version: any (tested with 1.28, 1.29, 1.30
- Cluster Type (Local/Downstream): downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): aws, rancher provisioned

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: tested as admin 

**Describe the bug**

when taking a snapshot on an rke2 cluster with s3 enabled, sometimes rancher reports 1 less snapshot in s3 than etcd nodes I have in my cluster. The next snapshot taken will have 1 more snapshot than etcd nodes in the cluster. 

**To Reproduce**

* setup a cluster with at least 3 etcd nodes and has s3 enabled for snapshots
* take a snapshot

**Result**
* the local count always has been correct
* s3 sometimes takes 1 less than etcd nodes in the cluster
  * when this happens, if you take another snapshot, rancher reports s3 to have taken 1 additional snapshot than expected
* s3 actually is reporting the correct number of snapshots taken with the correct timestamps

**Expected Result**

rancher should report the correct number of snapshots in s3 when the snapshot is taken, with the correct createTimestamp

**Screenshots**

s3 with correct timestamps and counts
![Screenshot from 2024-10-01 12-34-57](https://github.com/user-attachments/assets/eae46033-ed24-49b5-9582-551825a81349)
local snapshot count (correct, always)
![Screenshot from 2024-10-01 12-24-30](https://github.com/user-attachments/assets/68ac0d48-be41-4930-a9ee-c93dd4beeafa)

s3 snapshot count (look a the age column) only 2 snapshots were reported in rancher
![Screenshot from 2024-10-01 12-24-42](https://github.com/user-attachments/assets/9fa79aaf-8116-4cd8-9802-d491133e36ac)

s3 snapshot2 -- taken a few minutes later (look at the age / size column) this time, 4 snapshots were reported to have been taken in rancher. 2 snapshots were reported with the *same age as pr7qj
![Screenshot from 2024-10-01 12-30-52](https://github.com/user-attachments/assets/1c2ff0cf-7817-42a3-a616-bbf18e1199ad)

**Additional context**

this is probably a separate bug, but the s3 list in rancher is sorted by age by default, but sometimes the list is not in order by age. 

this will start affecting automation soon, as I'm adding validation that  local and s3 counts to be the same when a snapshot is taken. 

currently testing more, but not observed for automatic snapshots, only manually taken snapshots so far (which is what we use in automation)

not an issue for rke1 clusters

each time I see the issue in the manual snapshot:
* configmap for snapshots and s3 show data for a snapshot (ending in ltp-1727824617) but not in the snapshot list on the cluster through rancher

**Comment by snasovich** [comment]
@daviswill2 , moving this one to blocked as we will need RKE2 Oct patches to test it on. Please feel free to assign QA to it beforehand.

**Comment by markusewalker** [comment]
Validated that this is addressed on `head` https://github.com/rancher/rancher/commit/e59c50a79bff2b6cc023bdbdb4e825190b7833fb. See details below:

**ENVIRONMENT DETAILS**
- Rancher install: Helm
- Rancher version: `head` https://github.com/rancher/rancher/commit/e59c50a79bff2b6cc023bdbdb4e825190b7833fb

**TEST RESULT**
|#|Scenario|Result|
|---|---|---|
|1|Provision an RKE2 downstream cluster and validate the number of S3 snapshots shown in Rancher matches what is seen in the S3 bucket|:white_check_mark:|
|2|Take 3 snapshots in an RKE2 downstream cluster and validate the number of S3 snapshots shown in Rancher matches what is seen in the S3 bucket|:white_check_mark:|
|3|Provision two RKE2 downstream clusters and take 3 snapshots on the first cluster. Take 1 snapshot on the second cluster and validate the number of total S3 snapshots shown in Rancher matches what is seen in the S3 bucket|:white_check_mark:|
