### ISSUE TITLE
rancher-compose incorrectly states it has rm'd a sidekick - leaving a zombie

### ISSUE THREAD

**Issue by juliangamble** [rancher/rancher#4735]
**Rancher Version:**
Output:

    Rancher	v1.0.1
    Cattle	v0.159.7
    User Interface	v1.0.5
    Rancher Compose	v0.7.4

**Docker Version:**
Client:`docker-compose version: 1.5.1`

**OS and where are the hosts located? (cloud, bare metal, etc):**
Redhat

**Setup Details: (single node vs. single node, internal DB vs. external DB)**

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
`rancher-compose -p mystack rm --force -v`

**Results:** 
    22:55:22.118 time="2016-05-07T22:55:22+10:00" level=info msg="Project [myproject]: Deleting project " 
    22:55:22.119 time="2016-05-07T22:55:22+10:00" level=info msg="[0/3] [service-a]: Deleting " 
    22:55:22.119 time="2016-05-07T22:55:22+10:00" level=info msg="[0/3] [service-primary]: Deleting " 
    22:55:22.119 time="2016-05-07T22:55:22+10:00" level=info msg="[0/3] [sidekick]: Deleting " 
    22:55:22.127 time="2016-05-07T22:55:22+10:00" level=info msg="[0/3] [service-primary]: Deleted " 
    22:55:22.128 time="2016-05-07T22:55:22+10:00" level=info msg="[0/3] [sidekick]: Deleted " 
    22:55:22.139 time="2016-05-07T22:55:22+10:00" level=info msg="[0/3] [service-a]: Deleted " 
    22:55:22.140 Clearing requested, pausing to allow command to complete...

**Subsequent error**
When you try and do a `docker-compose -u ...` you get this error:

    fatal msg="Service service-primary must be state=active or inactive to upgrade, currently: state=updating-active" 
The sidekick service is not deleted. Nor is the stack. 

**Expected:**

The sidekick service **is** deleted. As is the stack.

**Comment by deniseschannon** [comment]
A stack is never deleted during a rm as we delete the services that are listed in the docker-compose.yml. There could be other services in the stack and by default we don't delete the stack. 

We have an open issue to add an option to delete a stack. https://github.com/rancher/rancher/issues/1723

Which sidekick didn't get deleted? It looks like there is something called `nextgen` being referenced in the rancher-compose up, but I don't see anything deleting called that.

**Comment by deniseschannon** [comment]
@juliangamble Please re-open if you have further questions.
