### ISSUE TITLE
[Backport v2.9] Improve lasso caches metrics

### ISSUE THREAD

**Issue by aruiz14** [rancher/rancher#47357]
Backport #46783

**Comment by aruiz14** [comment]
## Validation Template

## Root Cause
Metrics for lasso caches were mixing contexts and their values didn't reflect up-to-date values.

## What was fixed, or what change have occurred
A new label was added to each context, and the collection logic was fixed to make the metrics reflect accurate values.

## Areas or cases that should be tested

Install Rancher [enabling the Performance Dashboard](https://ranchermanager.docs.rancher.com/how-to-guides/advanced-user-guides/monitoring-alerting-guides/enable-monitoring#enabling-the-rancher-performance-dashboard) and [install Rancher Monitoring](https://ranchermanager.docs.rancher.com/how-to-guides/advanced-user-guides/monitoring-alerting-guides/enable-monitoring#install-the-monitoring-application).

Then access the Prometheus Console, and query:
```
sum (lasso_controller_total_cached_object) by (kind, pod, ctx)
```
Which should show a result like this (in the Graph view):

![Screenshot 2024-08-22 at 08 47 33](https://private-user-images.githubusercontent.com/4057165/360317361-386386e3-1817-475f-9e74-1c0435755969.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5NDUzNjUsIm5iZiI6MTcyNzk0NTA2NSwicGF0aCI6Ii80MDU3MTY1LzM2MDMxNzM2MS0zODYzODZlMy0xODE3LTQ3NWYtOWU3NC0xYzA0MzU3NTU5NjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDNUMDg0NDI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDU3MGRlYzY2MDcwNmQ1OGIzNjg4YjNlOWRiZjVkMjhlZGYwYmUxZTIzMDNhMTE0NzVlMWRjYjE4MDE2MzgzYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.rU86cbIDDeR_jDHgzpYza0nrtkewfF6yEWMsM7-Ufig)

## What areas could experience regressions
None.

**Comment by MSpencer87** [comment]
Verified on Rancher v2.9.3-alpha7, rke2 v1.30.4+rke2r1

lasso_controller_total_cached_object updates upon changes and displays context data


Steps to reproduce:
1. Bring up HA Rancher v2.9.2
2. Edit Rancher deployment and include CATTLE_PROMETHUS_METRICS=true in Environment Variables
Local->Workloads->Deployments->Edit Config
3. Install Monitoring Local->Apps->Charts->Monitoring
4. Open Prometheus Graph Local->Monitoring->Dashboard
5. Search for lasso_controller_total_cached_object, no contexts visible
```
sum (lasso_controller_total_cached_object{kind=~"Secret"}) by (kind, pod, ctx)
```
6. In Rancher, create any secret Local->Storage->Secret->Create
7. Return to Prometheus Graph and execute query again, no changes reflected for created secret


Steps for validation:
1. Bring up HA Rancher v2.9.3-alpha7
2. Edit Rancher deployment and include CATTLE_PROMETHUS_METRICS=true
3. Install Monitoring & open Prometheus Graph
5. Search for lasso_controller_total_cached_object, verify all contexts are now visible
```
sum (lasso_controller_total_cached_object{kind=~"Secret"}) by (kind, pod, ctx)
```
5. In Rancher, create a secret with mock data
6. Return to Prometheus Graph and execute query again, confirm added secret is counted
