### ISSUE TITLE
After upgrading from 0.63.1 to 1.0.1 networking Timesout on AgentInstancePostNicActivate

### ISSUE THREAD

**Issue by jwhitcraft** [rancher/rancher#4737]
**Rancher Version:** v1.0.1
**Docker Version:** 1.10.3 on rancher-host and 1.9.1 on all infrastructure hoara.
**OS and where are the hosts located? (cloud, bare metal, etc):** AWS VPC
**Setup Details: (single node vs. single node, internal DB vs. external DB)** Single node, AWS RDS Database
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:**
1. I upgraded to v1.0.1
2. create a stack via the api, it activates
3. create an instance of our app (two containers: one web and one db)
4. wait for them to become Active

**Results:** 
Services are stuck at the networking phase, when I check the processes in rancher, they are timing out repeatedly at the `AgentInstancePostNicActivate` step

**Expected:**
They should not timeout.

**Notes:**
I rolled back to v0.63.1 and the instances provisioned fine.  If i could get some guidance on this it would be helpful.  I can't have this service be down for that long of time, but I can try the upgrade again and pull any logs that may be needed.

Also if needed I can schedule an upgrade of all the hosts docker version next weekend if that were to be the issue.

**Comment by deniseschannon** [comment]
The `AgentInstancePostNicActivate` happens when Rancher can't update the Network Agent. If you could provide Rancher server logs, that would be helpful.

**Comment by jwhitcraft** [comment]
@deniseschannon, I'll run the upgrade tomorrow am when the traffic is low and I can take the servers offline if need be, if the servers don't upgrade for the network agent, i'll manually do it once i pull the logs from the server.

**Comment by jwhitcraft** [comment]
@deniseschannon Here is the only error showing up in the rancher-server log, post upgrade

```
2016-05-14 14:53:30,185 ERROR [:] [] [] [] [ecutorService-5] [.p.c.v.i.ConfigItemStatusManagerImpl] Failed null, exit code [7] output [INFO: Updating hosts
INFO: Downloading http://rancher.qa.sugarcrm.net/v1//configcontent//hosts current=hosts-87993-46bf3f2cd5e10e348cea0a9b2c2f20e1ff10eda99e38ca8db85820b45973a1d8
cat: write error: Broken pipe
INFO: Running /var/lib/cattle/download/hosts/hosts-87995-257aff5cc23042701e4b6e49146ac4f33de95ee93d14f3484f87f4e23b378943/apply.sh
INFO: HOME -> ./
INFO: HOME -> ./etc/
INFO: HOME -> ./etc/cattle/
INFO: HOME -> ./etc/cattle/metadata/
INFO: HOME -> ./etc/cattle/metadata/answers.yml
INFO: HOME -> ./etc/cattle/dns/
INFO: HOME -> ./etc/cattle/dns/answers.json
[[scripts.sh:184] script_env
[[scripts.sh:109] '[' -n http://rancher.qa.sugarcrm.net/v1 ']'
[[scripts.sh:110] return
[[scripts.sh:186] export CATTLE_HOME=/var/lib/cattle
[[scripts.sh:186] CATTLE_HOME=/var/lib/cattle
[[scripts.sh:187] export CATTLE_CONFIG_URL=http://rancher.qa.sugarcrm.net/v1
[[scripts.sh:187] CATTLE_CONFIG_URL=http://rancher.qa.sugarcrm.net/v1
[[scripts.sh:188] export CATTLE_STORAGE_URL=http://rancher.qa.sugarcrm.net/v1
[[scripts.sh:188] CATTLE_STORAGE_URL=http://rancher.qa.sugarcrm.net/v1
[apply.sh:25] DNS=
[[apply.sh:27] cat /etc/resolv.conf
[[apply.sh:27] sed 's/^# nameserver/nameserver/'
[[apply.sh:27] grep '^nameserver'
[[apply.sh:27] awk '{print $2}'
[apply.sh:27] for address in '$(cat /etc/resolv.conf  | sed '\''s/^# nameserver/nameserver/'\'' | grep ^nameserver | awk '\''{print $2}'\'')'
[apply.sh:28] '[' 10.9.1.20 = 169.254.169.250 ']'
[apply.sh:32] '[' -z '' ']'
[apply.sh:33] DNS='"10.9.1.20"'
[apply.sh:27] for address in '$(cat /etc/resolv.conf  | sed '\''s/^# nameserver/nameserver/'\'' | grep ^nameserver | awk '\''{print $2}'\'')'
[apply.sh:28] '[' 10.8.1.30 = 169.254.169.250 ']'
[apply.sh:32] '[' -z '"10.9.1.20"' ']'
[apply.sh:35] DNS='"10.9.1.20", "10.8.1.30"'
[apply.sh:27] for address in '$(cat /etc/resolv.conf  | sed '\''s/^# nameserver/nameserver/'\'' | grep ^nameserver | awk '\''{print $2}'\'')'
[apply.sh:28] '[' 10.25.10.2 = 169.254.169.250 ']'
[apply.sh:32] '[' -z '"10.9.1.20", "10.8.1.30"' ']'
[apply.sh:35] DNS='"10.9.1.20", "10.8.1.30", "10.25.10.2"'
[apply.sh:39] sed -i 's/"PARENT_DNS"/"10.9.1.20", "10.8.1.30", "10.25.10.2"/g' content-home/etc/cattle/dns/answers.json
[apply.sh:41] stage_files
[scripts.sh:77] local monit=false
[scripts.sh:79] '[' -d content-home ']'
[scripts.sh:80] find content-home -name '*.sh' -exec chmod +x '{}' ';'
[scripts.sh:81] tar cf - -C content-home .
[scripts.sh:81] tar xvf - --no-overwrite-dir -C /var/lib/cattle
[scripts.sh:81] sed 's/^/INFO: HOME -> /'
INFO: HOME -> ./
INFO: HOME -> ./etc/
INFO: HOME -> ./etc/cattle/
INFO: HOME -> ./etc/cattle/metadata/
INFO: HOME -> ./etc/cattle/metadata/answers.yml
INFO: HOME -> ./etc/cattle/dns/
INFO: HOME -> ./etc/cattle/dns/answers.json
[scripts.sh:84] '[' -d content ']'
[scripts.sh:102] '[' false = true ']'
[apply.sh:43] ip addr add 169.254.169.250/32 dev eth0
[apply.sh:43] true
[apply.sh:44] ip route show
[apply.sh:44] grep -q 169.254.169.254
[apply.sh:48] reload_service rancher-dns 8113
[apply.sh:7] local service=rancher-dns
[apply.sh:8] local port=8113
[apply.sh:9] '[' '!' -e /etc/init.d/rancher-dns ']'
[[apply.sh:14] pidof rancher-dns
[apply.sh:14] PID=904
[apply.sh:16] '[' -z 904 ']'
[apply.sh:18] '[' -e /var/lib/cattle/etc/cattle/rancher-dns/http-reload ']'
[apply.sh:19] curl -sf -X POST http://localhost:8113/v1/reload
]```

it's repeating itself multiple times.

**Comment by ibuildthecloud** [comment]
There is a problem talking to rancher-dns to reload it.  Restarting the network agents would probably address this.  Have you tried that?

**Comment by jwhitcraft** [comment]
@ibuildthecloud, i can do that. does it matter that i have the network-agents ranging from 0.5.0 to 0.8.1?

**Comment by jwhitcraft** [comment]
@ibuildthecloud, success!  that fixed the issue.  Should I work on getting all the network agents upgraded to v0.8.0 or higher?

**Comment by deniseschannon** [comment]
@jwhitcraft We upgrade the software in the network agents, but you are welcome to upgrade to the latest containers. They should be working the same.

**Comment by jwhitcraft** [comment]
@denisechannon I had to restart the hosts that had network agents of 0.7.0 or earlier as docket froze up when trying to restart the agents.  I'll just remove them and goto the latest.

**Comment by deniseschannon** [comment]
@jwhitcraft Let me know if the rest of the upgrade ended up succeeding after you refreshed the network agents.

**Comment by jwhitcraft** [comment]
@deniseschannon Once i restarted it all started working again.  I didn't have time this weekend to upgrade all the network agents but it's on my schedule for next weekend.

**Comment by deniseschannon** [comment]
@jwhitcraft Let me know if you are still having issues fater upgrading all the network agents.

**Comment by jwhitcraft** [comment]
@deniseschannon, it's been running smooth, I'm gonna close this issue now.
