### ISSUE TITLE
[BUG] Downstream K3s registry rewrites break fallback to upstream registry

### ISSUE THREAD

**Issue by brandond** [rancher/rancher#47379]
**Rancher Server Setup**
- Rancher version: 2.9.x and prior
- Installation option (Docker install/Helm Chart): n/a
- Proxy/Cert Details: n/a

**Information about the Cluster**
- Kubernetes version: n/a
- Cluster Type (Local/Downstream): Downstream RKE2 or K3s

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) n/a

**Describe the bug**

**To Reproduce**
1. Cluster Management -> Create -> Custom (or use a node driver, doesn't really matter) -> Give it a name 
2. Registries -> check "Enable cluster scoped..." -> Show Advanced
3. Registry Hostname: `docker.io` , Mirror Endpoints: `https://registry.example.com`
4. Add Rewrite Config -> Rewrite pattern: `^rancher/(.*)` Rewrite replacement: `mirrorproject/rancher-images/$1`
5. Create

**Result**

Note that the cluster nodes fail to come up due to image pull failures in the rancher-system-agent logs, as it cannot pull the image from registry.example.com, and cannot pull the rewritten image name from docker.io.

**Expected Result**
Rewrite should only be used when pulling from the mirror, and ignored when pulling from default registry endpoint.

**Screenshots**

**Additional context**
Issue comes from wharfie, and affects both rancher-system-agent pulling of rancher/system-agent-installer-rke2 and rke2 pulling of rancher/rke2-runtime.
* https://github.com/rancher/wharfie/issues/25

**Comment by snasovich** [comment]
This was done with https://github.com/rancher/rancher/pull/47378 merged, ready for testing.

**Comment by Josh-Diamond** [comment]
Ticket #47379 - Test Results - ✅ 
---

Verified on Rancher `v2.10.0-alpha3`:

| Scenario | Test Case | Result |
|---|---|---|
| 1. | Downstream K3s with mirrors and rewrites configured | ✅ |
| 2. | Downstream K3s without mirrors and rewrites configured | ✅ |

---

Scenario 1 - 
1. Fresh install of Rancher `v2.10.0-alpha3`
2. Provision a downstream K3s cluster, `v1.30.5+k3s1`, with cluster scoped registry enabled and the following configurations set:
- Registry hostname: `docker.io`
- Mirror endpoints: `https://registry.example.com`
- Rewrite Config -> Rewrite pattern: `^rancher/(.*)`
- Rewrite Config -> Rewrite replacement: `mirrorproject/rancher-images/$1`
3. Verified - cluster successfully provisions
4. Verified - rancher-system-agent logs reveal cluster tried to pull from `registry.example.com` unsuccessfully and then successfully fell back to pulling directly from `docker.io`; as expected
5. Verified - `/etc/rancher/agent/registries.yaml` accurately reflects configured rewrites and mirrors
6. Verified - bumped system-agent seen and functional: `rancher/system-agent:v0.3.10-rc.1-suc`

---

Scenario 2 - 
1. Fresh install of Rancher `v2.10.0-alpha3`
2. Provision a downstream K3s cluster, `v1.30.5+k3s1`, with defaults
3. Verified - cluster successfully provisions
6. Verified - bumped system-agent seen and functional: `rancher/system-agent:v0.3.10-rc.1-suc`
