### ISSUE TITLE
Download CLI

### ISSUE THREAD

**Issue by pascalandy** [rancher/rancher#4739]
Hey guys, 

Following t[his issue ](https://github.com/rancher/rancher/issues/4145#issuecomment-217903124), and [this official doc](http://docs.rancher.com/rancher/latest/en/swarm/#cli), Im' wondering what is exactly the Download CLI at the bottom right of the dashboard:

![screenr 2016-05-09 at 11 50 13 am](https://cloud.githubusercontent.com/assets/6694151/15118984/aad3d946-15dc-11e6-9a62-f8f38a638794.jpg)

When I uncompress it I have a 13Mo file and I really don't know what to do with it:

![screenr 2016-05-09 at 11 54 09 am](https://cloud.githubusercontent.com/assets/6694151/15119019/d66e2624-15dc-11e6-8e9b-b45f54aaaa26.jpg)

As I mentioned in an another thread, **my priority is to be able to use the CLI from my laptop to the VPS host that runs a Swarm master (and the nodes behind it.)**

Cheers!

---

**Rancher Version:1.1.0-dev1**

**Docker Version:1.11**

**OS and where are the hosts located? VPS**

**Setup Details: two nodes, 2GB each**

**Environment Type: Swarm**

**Steps to Reproduce: **

**Results:** 
**Expected:**

**Comment by pascalandy** [comment]
It just looks like the Mac OS X link downloads the Linux version of the package. My 5 cents!

**Comment by Rucknar** [comment]
I've not used the swarm support before, but that link is to the Rancher CLI, the docs for using the CLI can be found [here](http://docs.rancher.com/rancher/latest/en/rancher-compose/). Basically though, you need to give it execute permissions and run it from a terminal of your choice against the rancher server. 

You need to set a API an access key and a secret key, plus a cattle URL. It's in the doc i've linked to above. Apologies if it's not relevant to Swarm, i would think that rancher-compose is agnostic of the scheduling engine used in that environment.

**Comment by deniseschannon** [comment]
As @Rucknar mentioned, the Download CLI is related to downloading our rancher-compose CLI. I use the "Mac OS X" link all the time and it's working correctly for me in v1.1.0-dev1. You need to open a Terminal screen and switch over to where the rancher-compose binary is. You would be able to run commands

```
./rancher-compose up
```

As for using rancher-compose CLI in a swarm environment, the services will be launched in your Swarm environment and it will deploy services on hosts in that environment, but it will not be using the Swarm scheduler. 

Please re-open if you have further questions.

**Comment by vincent99** [comment]
OS X *is* a variant of UNIX.  All executables say kind="Unix executable", you just don't see them for normal apps because they're wrapped in a `.app` bundle.  This doesn't mean that you downloaded the Linux binary.

**Comment by pascalandy** [comment]
Got it @vincent99 !

@deniseschannon Thanks for the info. Will try this and let you know. Cheers!
