### ISSUE TITLE
[BUG] Rancher version displayed as "dev" instead of correct version

### ISSUE THREAD

**Issue by Priyashetty17** [rancher/rancher#47394]
**Rancher Server Setup**
- Rancher version: v2.7-head

**Information about the Cluster**
- Kubernetes version:
- Cluster Type (Local/Downstream): Local

**Describe the bug**
Rancher version is being displayed as "dev" (default value) instead of the correct version when deploying 2.7-head.

**To Reproduce**
- Deploy Rancher v2.7-head or v2.7.16-alpha4
- Check the version displayed in the UI or via the /v3/settings/server-version API or the /v1/management.cattle.io.settings/server-version

**Expected Result**
The correct Rancher version (eg., v2.7-commitID-head) should be displayed in the UI and the /v3/settings/server-version API.

**Screenshots**
![image](https://github.com/user-attachments/assets/0ed57557-aec3-41cc-80a2-ba69c7e50f53)

API output:
```
{
"baseType": "setting",
"created": "2024-10-03T19:24:11Z",
"createdTS": 1727983451000,
"creatorId": null,
"customized": false,
"default": "dev",
"id": ["server-version"](https://temp.qa.rancher.space/v3/settings/server-version),
"links": {
"remove": ["…/v3/settings/server-version"](https://temp.qa.rancher.space/v3/settings/server-version),
"self": ["…/v3/settings/server-version"](https://temp.qa.rancher.space/v3/settings/server-version)
},
"name": "server-version",
"source": "env",
"type": ["setting"](https://temp.qa.rancher.space/v3/schemas/setting),
"uuid": "3a83a08b-7c21-44ea-ab09-ebfc9e3b2952",
"value": ""
}
```

cc @daviswill2

**Comment by jiaqiluo** [comment]
It seems the issue is related to "The server version not being set on the final image" which was addressed by the following PR in the `release/v2.9` branch:  https://github.com/rancher/rancher/pull/46172

**Comment by tashima42** [comment]
I'm investigating this issue.

**Comment by jiaqiluo** [comment]
wait for https://github.com/rancher/rancher/actions/runs/11335650060 to pass

**Comment by jiaqiluo** [comment]
The fix can be validated on the latest `rancher/rancher:v2.7-head` image

**Comment by Priyashetty17** [comment]
Verified that the version is displayed in the **v2.7-commitID-head** format in the UI, the /v3/settings/server-version API, and the /v1/management.cattle.io.settings/server-version endpoint, using `v2.7-cdb80e8716a8e9117760e8a3d363461c38dce8fe-head`
