### ISSUE TITLE
[Backport v2.8] [BUG] Downstream K3s registry rewrites break fallback to upstream registry

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#47396]
Backport of https://github.com/rancher/rancher/issues/47379 to v2.8.x line of releases.

**Comment by snasovich** [comment]
This was done with https://github.com/rancher/rancher/pull/47376 merged; ready for testing.

**Comment by Josh-Diamond** [comment]
Ticket #47396 - Test Results - ✅ 
---

Verified on Rancher `v2.8.9-alpha10`:

| Scenario | Test Case | Result |
|---|---|---|
| 1. | Downstream K3s with mirrors and rewrites configured | ✅ |
| 2. | Downstream K3s without mirrors and rewrites configured | ✅ |

---

Scenario 1 - ✅ 
1. Fresh install of Rancher `v2.8.9-alpha10`
2. Provision a downstream K3s cluster, `v1.28.14+k3s1`, with cluster scoped registry enabled and the following configurations set:
- Registry hostname: `docker.io`
- Mirror endpoints: `https://registry.example.com`
- Rewrite Config -> Rewrite pattern: `^rancher/(.*)`
- Rewrite Config -> Rewrite replacement: `mirrorproject/rancher-images/$1`
3. Verified - cluster successfully provisions
4. Verified - rancher-system-agent logs reveal cluster tried to pull from `registry.example.com` unsuccessfully and then successfully fell back to pulling directly from `docker.io`; as expected
5. Verified - `/etc/rancher/agent/registries.yaml` accurately reflects configured rewrites and mirrors
6. Verified - bumped system-agent seen and functional: `rancher/system-agent:v0.3.10-rc.1-suc`

---

Scenario 2 - ✅ 
1. Fresh install of Rancher `v2.8.9-alpha10`
2. Provision a downstream K3s cluster, `v1.28.14+k3s1`, with defaults
3. Verified - cluster successfully provisions
6. Verified - bumped system-agent seen and functional: `rancher/system-agent:v0.3.10-rc.1-suc`
