### ISSUE TITLE
Support env_file for Rancher Catalog

### ISSUE THREAD

**Issue by will-chan** [rancher/rancher#4740]
rancher-compose already supports env_file which allows users to launch containers with common env variables.  

Adding support in Rancher Catalog would probably need to be better than simply giving the ability for users to specify a env_file since it would be as good as adding the individual key=value pairs themselves on the compose yml file.  We may need to add a Rancher ability to manage a set of common ENV variables and then allow users to specify this to launch a template with.

**Comment by sshipway** [comment]
+1 for this; being able to define a set of common inherited labels and env vars at Environment level would be useful.  It would also be nice if container and host labels were automatically exposed in the environment; so, if the common environment-level variable definitions allow use of symbols such as stack name, container name, or host label this could be very powerful.

**Comment by jjzhangg** [comment]
+1
