### ISSUE TITLE
Automate tests cases for validating supported Kubernetes features.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#4742]
Automate tests cases for validating supported Kubernetes features from - https://github.com/rancher/rancher/issues/4489

Basic workflow for validating Kubernetes is available in PR-  https://github.com/rancher/validation-tests/pull/175 that provides libraries for creating a kubectl client and being able to execute commands from this client.

**Comment by galal-hussein** [comment]
New 8 test cases added to validation-tests PR https://github.com/rancher/validation-tests/pull/177 including:
  - testing secrets.
  - testing namespaces
  - testing rollingupdates
  - testing configmaps
  - testing resourcequota
  - testing deployments
  - testing deploymentsrollback
  - testing jobs

Also adding create, and teardown functions to facilitate the flow of test cases.

**Comment by galal-hussein** [comment]
New 20 test cases added to this PR https://github.com/rancher/validation-tests/pull/181, the PR will test:

- scaling
- daemonsets
- replicasets
- create pod
- delete pod
- edit pod
- podspec (volumes)
- podspec (restartPolicy)
- podspec (activeDeadlineSeconds)
- podspec (terminationGracePeriodSeconds)
- podspec (nodeSelector)
- podspec (nodeName)
- podspec (hostPID)
- replication controller create
- replication controller delete
- replication controller edit
- services creation/deletion
- loadbalancer service
- external IP service
- cluster IP service
- NodePort service

#### TO DO

- Add test cases for kubectl commands.
- Adding failed tests:
  - hostNetwork
  - hostIPC
  - Ingress 
  - Heapster
  - Dashboard
  - kubectl failed cmds (logs, exec)
  - Isolating pods from rc
  - ServiceAccounts
- Pod secuirty context test.

#### Special cases

Some tests weren't possible to be automated, like:

- PersistentVolumes for AWS
This test case requires AWS environment (EC2s and EBS) and credentials to specific aws account.

- PersistentVolumes for GCE
This test case requires Google Compute engines.

- PersistentVolumes for GlusterFS
This test case requires a manual provisioning for Glusterfs environment on the nodes.

- imagePullSecret spec for pods
This spec will depend on a private docker registry that should exist before the test run.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
