### ISSUE TITLE
Rancher compose gives incorrect help for scaling services

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#4743]
**Rancher Version:** v1.1.0-dev1

**OS and where are the hosts located? (cloud, bare metal, etc):**: Cloud

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** : Cattle

*_Steps to Reproduce: *_: 
1. Set up rancher compose environment
2. Issue the following command:
_./rancher-compose -f dc1.yml -r test1.yml -p stack1 scale --help
Usage: rancher-compose scale [OPTIONS]

Scale services

Options:
   --timeout, -t "10"   Specify a shutdown timeout in seconds._

**Expected:****
Rancher compose should provide the correct help for scaling services

**Comment by will-chan** [comment]
@soumyalj is this still happening?

**Comment by deniseschannon** [comment]
Rancher CLI has been updated to add in help, but if anyone needs help, to scale services the command is 

```
rancher-compose scale <servicename>=3
```
