### ISSUE TITLE
API should error out when size is specified for "ROOT" volumes  for VM creation.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#4744]
Rancher Version: Build form master

When creating VMs ( as standalone containers/ services) , currently user is allowed to pick a size for ROOT disk. 
VM gets created and but the ROOT volume size is based off the image of the VM.
Since ROOT volume size is going to be always based off the image , API should error out when size is specified for "ROOT" volumes.

**Comment by will-chan** [comment]
Closing issue as RancherVM is being revisited.
