### ISSUE TITLE
CoreOS Hosts stays in reconnecting after update

### ISSUE THREAD

**Issue by hwinkel** [rancher/rancher#4745]
**Rancher Version:** 1.0.1

**Docker Version:** 1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):** coreOS 1032.0.0 -> 1032.1.0

**Setup Details: (single node vs. single node, internal DB vs. external DB)** single node

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:** Lets CoreOS update by stock update mechanism

**Results:** After a successful CoreOS update the CoreOS is on new version, Rancher shows the Hosts in "reconnecting" state. After a manual Reboot the hosts reconnects to active state. After that Rancher Starts and redeploys all Services.

**Expected:** CoreOS simple Updates, reboots and all services are running again without rescheduling.

**Comment by sshipway** [comment]
I've also had networking issues with CoreOS beta and alpha (which use Docker 1.10.3); however CoreOS stable (Docker 1.9.1) seems fine.  I downgraded all my CoreOS hosts to the latest Stable, upgraded to Rancher 1.1.0-dev1, and problems went away.

**Comment by hwinkel** [comment]
I was using the ones which contains docker 1. 10.3 as I have read docker 1.9 has network and performance issues by self

**Comment by hwinkel** [comment]
Same problem with the Stable Stream, also RECONNECTING state. Ubuntu Hosts with Docker 1.10.3 show no problems

**Comment by sshipway** [comment]
Do you have your rancher server on the same OS?  I played about with the Host OS for a while before I realised that the Rancher server was always on CoreOS beta; when I moved it to stable as well that helped.  May be a problem of communication between containers under different Coreos Docker versions?

**Comment by hwinkel** [comment]
no, the server runs on a seperate  Ubuntu 14.04 host.

**Comment by sshipway** [comment]
FWIW, I run both the Rancher and the Hosts under CoreOS.  It was not until all were using CoreOS stable that the problem went away.  Maybe CoreOS doesn't like talking to anything but CoreOS (of the same version)?

**Comment by deniseschannon** [comment]
Here's what we're seeing with CoreOS. CoreOS auto upgrades and reboots and then after reboot docker isn't running anymore.  For your hosts in reconnecting state, you can log in and  do `ps -ef | grep docker` and you'll see docker isn't running. Not until you try to use docker once will it startup.  So `docker ps` will launch docker.  It's because of socket activation in systemd.

The solution is to create on systemd unit file that pings docker on boot.  Or add `docker ps` to `/etc/rc.local`

**Comment by deniseschannon** [comment]
After applying these recommendations and you still have issues, please re-open.
