### ISSUE TITLE
[RFE] Refactor AccessStore key hashing

### ISSUE THREAD

**Issue by aruiz14** [rancher/rancher#47460]
**Is your feature request related to a problem? Please describe.**
I noticed while working on #47318 that the key of the cache is calculated based on the status of the rules, which are later fetched separately in the case of a cache miss.
This is enough for the happy path, but it could be a problem if the cache changes in between (e.g. if any of the involved resources changes), ending up caching an incorrect value.

**Describe the solution you'd like**
The key/hash should be calculated on the same payload later being used to generate `AccessSets`. 

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by rancher-max** [comment]
This is additional work on top of #47318 so closing this issue in favor of that one for testing purposes.
