### ISSUE TITLE
[v2.10] Update CNI Plugins source in rke-tools

### ISSUE THREAD

**Issue by vardhaman22** [rancher/rancher#47464]
update CNI plugins source from https://github.com/containernetworking/plugins to https://github.com/rancher/image-build-cni-plugins in rancher/rke-tools

**Comment by Sahota1225** [comment]
Need RKE1 October patch to validate

**Comment by rishabhmsra** [comment]
The validations are done as a part of v1.20 KDM Oct patches testing. All the KDM checks passed, hence this can be closed.
