### ISSUE TITLE
[Backport v2.8] Enhance the secret-synchronization controller from Rancher's management cluster -> downstream clusters 

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#47470]
Backport of https://github.com/rancher/rancher/issues/45718 to v2.8.x release line.

Related: SURE-5434

**Comment by susesgartner** [comment]
Ticket #47470 - Test Results - ✅ 
---
 
| Scenario | Test Case | Result |
|---|---|---|
| 1. | CSI/CPI provisioning check | PASS |
| 2. | Provisioning regression check | PASS |

---
Verified with HA Helm on Rancher `v2.8-217214647cd318383c0324e4102c4d637893c980-head`:
---

Setup:
1. Create a Vsphere rancher HA setup
2. Enable the "provisioningprebootstrap" feature flag
 
Scenario 1: Verify CSI/CPI cluster provisioning
---
1. Fill out all info for a csi/cpi rke2 cluster
2. In csi/cpi set "generate cloud secret" to true
3. Provision the cluster
4. Verify that the cluster comes up and all pods are in a healthy state.
 
Results: The cluster provisions and all verifications passed
 
---
 
Scenario 2: Provisioning regression check
---
1. Provision an RKE1/RKE2/K3s cluster
2. Verify that they come up active and all pods are in stable state.
 
Results: all clusters came up and all pods were in a stable state

NOTE: additional regressions are being performed as part of release testing.
