### ISSUE TITLE
Service with start-once sidekick shows service state as 'started once' rather than 'active'

### ISSUE THREAD

**Issue by sshipway** [rancher/rancher#4748]
**Rancher Version:**
1.1.0-dev1
**Docker Version:**
1.9.1
**OS and where are the hosts located? (cloud, bare metal, etc):**
CoreOS-stable
**Setup Details: (single node vs. single node, internal DB vs. external DB)**
Multi-host, single Rnacher, internal DB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
Start Datadog catalogue item.  This creates one service instance per host, with a start-once sidekick
**Results:** 
Service and stack show status as 'started once'
**Expected:**
Service and stack should be in 'Active' state as main container is 'active'.  There is no reason for started-once state on the service sidekick to take priority over the actual service container state, and it gives the incorrect impression that the stack is no longer active when in fact it is.

**Comment by aemneina** [comment]
Reproduced this, where stack is reported started-once. Where there are active containers running. Stack should report active..

**Comment by alena1108** [comment]
@sshipway @aemneina what catalog item have you used to reproduce the issue?

**Comment by deniseschannon** [comment]
Steps to Reproduce:

1. Start Datadog catalog item
2. Click on service containers to view all the status of the containers. 

Service/Stack are "Started once" even though there are containers in "Active" state.

**Comment by alena1108** [comment]
@sshipway @deniseschannon @aemneina that's a great bug :) happens when stars are aligned as follows:

* service should have n >= 1 sidekicks
* service should be global
* number of launch configs having startOnce=true should be greater than number of launchConfigs having startOnce=false

**Comment by sshipway** [comment]
@alena1108  Do I win a cookie? :)

**Comment by alena1108** [comment]
@sshipway 2 cookies :)

**Comment by vincent99** [comment]
Here you go... `Set-Cookie: winner=sshipway; Expires=Wed, 24 Feb 2021 18:42:00 GMT`

**Comment by sshipway** [comment]
@vincent99  Thanks... hey!  Ghostery ate it before I could get my hands on it!  Typical.

**Comment by deniseschannon** [comment]
Verified with v1.1.0-dev4 that datadog shows up as "Active"
