### ISSUE TITLE
[backport v2.8] Rancher monitoring chart is failing with error unknown flag: --logtostderr on rancher-monitoring-prometheus-adapter

### ISSUE THREAD

**Issue by jbiers** [rancher/rancher#47495]
Issue created to track the backport of https://github.com/rancher/rancher/issues/46919 to v2.8

**Comment by pankajsqe** [comment]
Retest passed : Rancher monitoring chart rancher-monitoring:103.2.0-rc.1+up57.0.3 successfully got installed without any failure or error.

Details
rancher : v2.8.9-alpha10
monitoring : rancher-logging:103.1.3-rc.1+up4.8.0
Cluster : RKE2
![Image](https://github.com/user-attachments/assets/cf284359-6341-465a-b1c3-12afe8203318)
