### ISSUE TITLE
rancher-compose image / build overrides 

### ISSUE THREAD

**Issue by andrewmclagan** [rancher/rancher#4749]
**Rancher Version:**

v1.1.0-dev1

**Expected:**

when using a `rancher-compose` file in combination with `docker-compose` file. How can we override a `build: /path/to/Dockerfile` directive in the docker-compose file with a `image: my-docker-user/my-docer-repo` directive in the rancher-compose file? 

This is very handy as we use build for developing locally, and image for the remote build. 

furthermore we would also like to remove/add other directives such as `volumes` etc...

**Comment by Rucknar** [comment]
@andrewmclagan A couple of ways to cut this...

You could use the 'extends' function of docker compose, you could use extends in your docker-compose file and use an environment variable passed at runtime to determine which 'version' of the config you want to run in. https://docs.docker.com/compose/extends/ has some more details, I could always paste some examples if it's of interest.

**Comment by deniseschannon** [comment]
@andrewmclagan Let me know if you have further questions, @Rucknar has some great suggestions.

At this time, you can't have the image in the rancher-compose.yml as we expect that info in the docker-compose.yml files.
