### ISSUE TITLE
API should not allow for LB to be created with a LB configuration that is "Removed"

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#475]
Server - built from master on Apr 7

Steps to reproduce the problem:
Because of - #474 , from UI we are allowed to create LB with a LB configuration that is in "Removed" state.

This action is not prevented by the API.
But configurations relating to this LB config is not applied to the LB Agent.

Expected Behavior:
API should error out when there is an attempt made to create LB with a removed LB config.

**Comment by alena1108** [comment]
I believe for that one, we would need a generic fix for our APIs. API object fields defined as references to other cattle objects, shouldn't accept object that is Removed.

**Comment by alena1108** [comment]
Closing this bug as won't fix as standalone LB is no longer exosed
