### ISSUE TITLE
[Backport v2.9][RFE] Bump Harvester node driver to v0.7.0

### ISSUE THREAD

**Issue by bk201** [rancher/rancher#47508]
Backport of https://github.com/rancher/rancher/issues/47507  to v2.9.x line of releases. Please assign the ticket to @m-ildefons

**Comment by khushboo-rancher** [comment]
Validated with Rancher 2.9-head

Validation - Pass

Scenarios tested:
1. Imported Harvester in Rancher, validated the node driver version at v3/nodeDrivers/harvester
2. Created rke1/rke2 cluster. Scaled up & down the cluster. Deleted the cluster.
3. Expired cloud credential, renewed it, operated with clusters again. All worked fine.
4. Upgraded the Rancher from 2.8.8 to 2.8.9. Operated with clusters. Verified the node driver versions.
