### ISSUE TITLE
Can't find driver named 'postgres' when starting rancher server

### ISSUE THREAD

**Issue by salaerts** [rancher/rancher#4750]
**Rancher Version:**
1.1.0-dev1
**Docker Version:**
1.10.3
**OS and where are the hosts located? (cloud, bare metal, etc):**
VMWare (on-premise), Ubuntu 14 LTS
**Setup Details: (single node vs. single node, internal DB vs. external DB)**
Trying to setup multi-node on external postgres database
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce: **
Starting rancher-server container from a chef recipe: 
docker_container 'rancher-server' do
  image node['rancher']['server']['image']
  tag node['rancher']['server']['version']
  detach true
  container_name 'rancher-server'
  port "#{node['rancher']['server']['port']}:8080"
  volume '/var/run/docker.sock:/var/run/docker.sock'
  env [
    "CATTLE_DB_CATTLE_DATABASE=postgres",
    "CATTLE_DB_CATTLE_USERNAME=#{node['rancher']['server']['db']['user']}",
    "CATTLE_DB_CATTLE_PASSWORD=#{node['rancher']['server']['db']['password']}",
    "CATTLE_DB_CATTLE_POSTGRES_HOST=#{node['rancher']['server']['db']['host']}",
    "CATTLE_DB_CATTLE_POSTGRES_PORT=#{node['rancher']['server']['db']['port']}",
    "CATTLE_DB_CATTLE_POSTGRES_NAME=#{node['rancher']['server']['db']['dbname']}"
  ]
  action :run
end

**Results:** 
Rancher throws an exception during startup saying it cannot find the driver named 'postgres'.

**Expected:**
Rancher to use the specified postgres database for HA.
The postgres database is definitively available and the credentials are correct.
(Image being pulled and run is actually 1.1.0-dev1, if using internal MySQL db it works as expected.)
According to the logs the username, password, host and port are passed in correctly.

**Comment by vincent99** [comment]
MySQL (and variants) is the only supported database.

**Comment by frekele** [comment]
related https://forums.rancher.com/t/rancher-server-ha-and-database-mysql-or-postgres/2074
