### ISSUE TITLE
[RFE] Bump Harvester node driver to v0.7.0

### ISSUE THREAD

**Issue by bk201** [rancher/rancher#47507]
**Is your feature request related to a problem? Please describe.**
The Harvester node-driver is updated and we need to advance the version in Rancher.

**Describe the solution you'd like**
Bump Harvester node driver to v0.7.0.

**Additional context**
Per @innobead's request, I created the issue to track the node driver will be updated in a specific Rancher version. Please assign the ticket to @m-ildefons

**Comment by khushboo-rancher** [comment]
Validated with Rancher v2.10-e4572f8147ba107fae3eea8e3bf73c9306c272b0-head

Validation - Pass

Scenarios tested:
1. Imported Harvester in Rancher, validated the node driver version at v3/nodeDrivers/harvester

Note: All scenarios couldn't be tested as blocked by https://github.com/rancher/rancher/issues/47501. Those scenarios should be covered when the #47501 is resolved and tested.
