### ISSUE TITLE
Ability to add additional kubelet options

### ISSUE THREAD

**Issue by liyimeng** [rancher/rancher#4751]
**Rancher Version:**
v1.0.1
**Docker Version:**
Docker version 1.10.3, build 20f81dd
**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04 TLS in VM
**Setup Details: (single node vs. single node, internal DB vs. external DB)**
single node 
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

Kubernetes allow you customise the cluster with many options, e.g. https://github.com/kubernetes/kubernetes/blob/8a04506546db27bab6b3a58ca88378fadfdb0541/docs/admin/kubelet.md 
But in rancher, there is noy way to set any one of these options.

**Comment by alena1108** [comment]
@liyimeng thank you for raising the issue. We should definitely add it as a feature in the future release.

**Comment by galal-hussein** [comment]
Rancher version: v1.6.6-rc3
Kubernetes version: v1.7.2-rancher1

I was able to add more options to kubelet service, using the additional kubelet flags template field:
```
--authorization-webhook-cache-authorized-ttl=0m30s --authorization-webhook-cache-unauthorized-ttl=0m30s
```

```
kubelet --kubeconfig=/etc/kubernetes/ssl/kubeconfig --api_servers=https://kubernetes.kubernetes.rancher.internal:6443 --allow-privileged=true --register-node=true --cloud-provider=external --healthz-bind-address=0.0.0.0 --cluster-dns=10.43.0.10 --cluster-domain=cluster.local --network-plugin=cni --cni-conf-dir=/etc/cni/managed.d --pod-infra-container-image=gcr.io/google_containers/pause-amd64:3.0 --authorization-webhook-cache-authorized-ttl=0m30s --authorization-webhook-cache-unauthorized-ttl=0m30s
```
