### ISSUE TITLE
[BUG] Default Alert missing from monitoring dashboard and Angular Deprecation Warning message on grafana dashboard

### ISSUE THREAD

**Issue by deepakpunia-suse** [rancher/rancher#47513]
**Rancher Server Setup**
- Rancher version: `v2.8.9-alpha9`
- Monitoring Chart Version: `103.2.0-rc.1+up57.0.3`
- Installation option (Docker install/Helm Chart): `Both`
  - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): `ALL`

**Information about the Cluster**
- Kubernetes version: `v1.28.6+k3s2`
- Cluster Type (Local/Downstream): `Local`

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) `Admin`

**Describe the bug**
Missing Active Alerts from monitoring dashboard and `Angular Deprecation Warning` message on grafana dashboard for Monitoring chart version `v103.2.0-rc.1+up57.0.3`. However it working fine with the previous version `103.1.2+up45.31.1`
On `v1.28.6+k3s2` with Rancher `v2.8.9-alpha9` and Rancher Monitoring `v103.2.0-rc.1+up57.0.3`, no sample active alerts appear upon installation. Creating PrometheusRules with `vector(1)` also fails to generate alerts. The Grafana dashboard displays a deprecated Angular warning, indicating potential plugin or compatibility issues. Logs show database lock & user token not found errors, plugin manifest key retrieval failures, and certificate validation issues for Grafana.

**To Reproduce**

- Install Rancher Monitoring Chart on a Rancher (`v2.8.9-alpha9`) setup running on k3s (`v1.28.6+k3s2`).
- Go to Monitoring tab after installation and wait for it to load.
- Check for Active Alerts – verify if default sample active alerts appear.
- Add PrometheusRules with `vector(1)` expression to manually test alert generation.

**Result**
- Default Alert missing from monitoring dashboard
- Grafana Dashboard shows warning: "`This panel requires Angular (deprecated)`".

**Expected Result**
Sample alerts should be generated by default, and manually created PrometheusRules should trigger alerts. Grafana should not display the Angular deprecation warning, indicating all plugins are updated to supported frameworks.

**Screenshots**
![image](https://github.com/user-attachments/assets/1991c8ce-a54d-4193-a8fd-15b7d8dc78e7)
![image](https://github.com/user-attachments/assets/e802d52e-d72a-4cfa-8359-b432fd780bd6)

**Additional context**
Observed failure Logs:
```
# kubectl logs rancher-monitoring-grafana-6bc7446b55-mdnlg -n cattle-monitoring-system  | grep -i 'Error'
logger=ngalert.state.manager t=2024-10-07T11:24:46.920243622Z level=info msg="Running in alternative execution of Error/NoData mode"
logger=sqlstore.transactions t=2024-10-07T11:24:47.423620631Z level=info msg="Database locked, sleeping then retrying" error="database islocked" retry=0 code="database is locked"
logger=grafana.update.checker t=2024-10-07T11:24:48.014724733Z level=error msg="Update check failed" error="failed to get stable version from grafana.com: Get \"https://grafana.com/api/grafana/versions/stable\": tls: failed to verify certificate: x509: certificate is not valid for any names, but wanted to match grafana.com" duration=1.008368822s
logger=plugin.signature.key_retriever t=2024-10-07T11:24:48.048369916Z level=error msg="Error downloading plugin manifest keys" error="Get \"https://grafana.net/api/plugins/ci/keys\": tls: failed to verify certificate: x509: certificate is not valid for any names, but wanted to match grafana.net"
logger=context userId=0 orgId=1 uname= t=2024-10-07T11:24:57.216411878Z level=info msg="Access denied" namespace=anonymous userID= accessErrorID=ACE6427904022 permissions="action:provisioning:reload scopes:provisioners:dashboards"
logger=plugin.signature.key_retriever t=2024-10-07T11:25:48.629846523Z level=error msg="Error downloading plugin manifest keys" error="Get \"https://grafana.net/api/plugins/ci/keys\": tls: failed to verify certificate: x509: certificate is not valid for any names, but wanted to match grafana.net"
logger=authn.service t=2024-10-07T11:29:14.421128714Z level=warn msg="Failed to authenticate request" client=auth.client.session error="user token not found"
logger=sqlstore.transactions t=2024-10-07T11:39:46.844883296Z level=info msg="Database locked, sleeping then retrying" error="database islocked" retry=0 code="database is locked"
```

Failure observed during Rancher monitoring chart installation :
```
2024-10-07T11:23:37.200738839Z Ignoring delete failure for "rancher-monitoring-crd-create" batch/v1, Kind=Job: jobs.batch "rancher-monitoring-crd-create" not found
Ignoring delete failure for "rancher-monitoring-admission" /v1, Kind=ServiceAccount: serviceaccounts "rancher-monitoring-admission" not found
Ignoring delete failure for "rancher-monitoring-admission" rbac.authorization.k8s.io/v1, Kind=Role: roles.rbac.authorization.k8s.io "rancher-monitoring-admission" not found
Ignoring delete failure for "rancher-monitoring-admission" rbac.authorization.k8s.io/v1, Kind=RoleBinding: rolebindings.rbac.authorization.k8s.io "rancher-monitoring-admission" not found
```

**Comment by deepakpunia-suse** [comment]
Issue is fixed with `v2.8.9-alpha10` or later than this version

**Comment by carlstlaurent** [comment]
Issue present in v2.9.1 as well

**Comment by rak-phillip** [comment]
@deepakpunia-suse can we also confirm if this is an issue in the upcoming `v2.9.3` release as well?

**Comment by deepakpunia-suse** [comment]
Checked in `v2.9.3-rc1`, Alert is working fine, For the deprecated anugalar wanring, that is an upstream issue that should be resolved in newer versions and doesn't cause any known breakages so we don't need to worry about that one
