### ISSUE TITLE
[BUG] Neuvector v104.0.2+up2.8.0 deployment fails on ARM Architecture due to missing image

### ISSUE THREAD

**Issue by rootwuj** [rancher/rancher#47510]
**Rancher Server Setup**
- Rancher version: v2.9.2
- Installation option (Docker install/Helm Chart): Docker install

**Information about the Cluster**
- Kubernetes version: v1.30.4+rke2r1
- OS: Ubuntu Server 24.04 LTS ARM

**Describe the bug**

The Neuvector `v104.0.2+up2.8.0` fails to start the `neuvector-controller-pod` because the `rancher/mirrored-neuvector-compliance-config:1.0.0` image is not available for the ARM architecture.

**To Reproduce**

1. Go to Cluster Tools in Rancher.
2. Select Neuvector and deploy version v104.0.2+up2.8.0.
3. Observe that the `neuvector-controller-pod` fails to start.
4. Check the pod events to see the error related to the missing ARM image.

**Expected Result**

The `neuvector-controller-pod` should start successfully without errors related to missing images.

**Screenshots**

<img width="1791" alt="image" src="https://github.com/user-attachments/assets/01177669-74fd-4152-ad01-8ceed26b127d">

https://hub.docker.com/r/rancher/mirrored-neuvector-compliance-config/tags

<img width="1763" alt="image" src="https://github.com/user-attachments/assets/471e38e9-e3b4-4265-a647-b16163707309">

**Comment by pohanhuangtw** [comment]
Hi @rootwuj,
We plan to support the ARM architecture in version 1.0.1. Currently, we are in the testing phase.

**Comment by rootwuj** [comment]
> Hi @rootwuj, Thank you for your reporting! We plan to support the ARM architecture in version 1.0.1, and we are currently in the testing phase to ensure everything works smoothly.

@pohanhuangtw Thank you for the update! I'm glad to hear that ARM architecture support will be included in version 1.0.1. I look forward to the release.

**Comment by rootwuj** [comment]
Verified in neuvector 5.4.1

<img width="1791" alt="image" src="https://github.com/user-attachments/assets/dd1260a5-e851-4129-87f3-999b376da70b" />
