### ISSUE TITLE
[BUG] Unable to provision RKE1 downstream clusters on v2.10-head

### ISSUE THREAD

**Issue by Priyashetty17** [rancher/rancher#47520]
**Rancher Server Setup**
- Rancher version: **v2.10-24d19e205aaed1ca11b572888a6a0c9728b54807-head**
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1 (**v1.6.3-rc.1**)

**User Information**
- What is the role of the user logged in? Admin

**Describe the bug**
Unable to provision RKE1 downstream clusters because the K8s version is not being set during cluster creation. Additionally, refreshing the Kubernetes metadata results in an error, indicating Rancher cannot find the default K8s version for v1.31.x.

**To Reproduce**

1. Create a Rancher instance with  v2.10-head.
2. Try to create an EC2 node driver provisioned RKE1 downstream cluster. 
**Issue**: Expected the K8s version dropdown to show supported versions for RKE but noticed that the K8s version was not being set in the UI during cluster creation.
     Refreshed the metadata to check if that resolves the issue but observed the following error
     <img width="395" alt="image" src="https://github.com/user-attachments/assets/7b316168-7178-492e-ae15-288738e1a42a">

Note: 
- This issue is observed only for RKE1 clusters. Able to provision RKE2/K3S clusters without any issues
- Also seen with v2.10 head + RKE 1.6.2 

**Could this be because RKE1 does not support K8s version 1.31? According to the [RKE releases page](https://github.com/rancher/rke/releases/tag/v1.6.3-rc.1), the highest supported version appears to be v1.30.5-rancher1-1. Could that be why the default Kubernetes version is not being set?**

**Screenshots**
<img width="1047" alt="image" src="https://github.com/user-attachments/assets/02855693-2fa0-4e61-a9fe-b88b6305c60d">

**From the Rancher log:**
`2024/10/11 15:33:52 [ERROR] error syncing 'rke-metadata-config': handler rke-metadata-handler: failed to refresh from local file path: /var/lib/rancher-data/driver-metadata/data.json: driverMetadata: unable to find default k8s version in current k8s v1.31.x [v1.27.16-rancher1-1 v1.28.14-rancher1-1 v1.29.9-rancher1-1 v1.30.5-rancher1-1], requeuing
`

**Additional context**
- Manually editing the YAML file during cluster creation and specifying "kubernetes_version: v1.30.5-rancher1-1" won't help either and it fails with:
<img width="590" alt="image" src="https://github.com/user-attachments/assets/75c10844-8863-48c3-95a0-30c2b910586b">

**Comment by kinarashah** [comment]
https://github.com/rancher/kontainer-driver-metadata/pull/1515

**Comment by Josh-Diamond** [comment]
Ticket #47520 - Test Results - ✅ 
---

Verified on Rancher `v2.10-13c7bae82c64b32ea68eb8981ee27dd7647c26ec-head`:

| Scenario | Test Case | Result |
|---|---|---|
| 1. | Provision downstream RKE1 AWS Node driver cluster | ✅ |

---

Scenario 1 - ✅ 
1. Fresh install of Rancher `v2.10-head`
2. Provision a downstream RKE1 AWS Node driver cluster w/ k8s `v1.30.5`
3. Verified - All expected k8s versions available in Create: Cluster dropdown
4. Verified - cluster successfully provisions and comes up `active`
5. Verified - all pods `active` and stable; as expected
