### ISSUE TITLE
Save Application state so I can stay in ALL

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4754]
**Version:** master 5/10

**Step:** 
1.  Create a new environment
2.  Add host and at least 1 service
3.  Add a stack/service to system page
4.  Now set Application drop-down to ALL
5.  Switch out of environment and back in

**Results:** 
Goes back to Stacks only

**Expected:** Should stay in ALL

**Comment by westlywright** [comment]
@tfiduccia retest? This workflow isn't valid anymore.

**Comment by tfiduccia** [comment]
Version - console 7/5
Verified fixed
