### ISSUE TITLE
[BUG] [2.9] Linode node driver download causes node driver hangups on arm64

### ISSUE THREAD

**Issue by jakefhyde** [rancher/rancher#47547]
Backport of https://github.com/rancher/rancher/issues/47569

**Rancher Server Setup**
- Rancher version: v2.9-head (sha256:a52e14121a551f2d84901379eed46ddab9f99804e5fa93bd63d3abdc21e8064d)

**Describe the bug**

When spinning up Rancher on an arm64 host, the linode driver attempts to install the amd64 versions, which cannot be run. This causes node driver initialization to get stuck, preventing users from creating cloud credentials and subsequently other node driver clusters.

**To Reproduce**

Spin up an arm64 Rancher server

**Result**

Cannot create cloud credentials in UI. Attempting to create under cluster creation results in following error:
```
{"baseType":"error","code":"MissingRequired","message":"a Config field must be set","status":422,"type":"error"}
```

**Expected Result**

Can create credentials with no problem

**Screenshots**

**Additional context**

Relates to https://github.com/harvester/harvester/issues/6053

**Comment by snasovich** [comment]
Ready for QA as soon as CI producing new `head` image succeeds.
