### ISSUE TITLE
Add Host for Digital Ocean giving me docker version 1.11.1

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4755]
**Version:** Master 5/10

**Steps to Reproduce: **
1.  Add a digital ocean host

**Results:** 
giving me 1.11.1 - docker install URL in advanced is blank.

**Expected:**
Should give me 1.10.3?

**Comment by vincent99** [comment]
https://github.com/rancher/cattle/pull/1659

**Comment by tfiduccia** [comment]
Version - master 5/10
Verified fixed
