### ISSUE TITLE
[Backport] [v2.9] add gke 1.6.0 support in rancher-cis-benchmark chart 

### ISSUE THREAD

**Issue by vardhaman22** [rancher/rancher#47552]
backport issue for https://github.com/rancher/rancher/issues/47551
gke 1.6.0 is available in upstream: https://github.com/aquasecurity/kube-bench/tree/main/cfg/gke-1.6.0
so the current gke 1.2.0 profile needs to be updated to 1.6.0 in rancher-cis-benchmark chart

**Comment by vivek-shilimkar** [comment]
Validated on rancher v2.9-head

- Created GKE v1.30.5-gke cluster.
- Installed CIS chart.
- Ran GKE-1.6.0 profile scans.
- Scans completed with some failure.
