### ISSUE TITLE
Question about correct deployment from git to load balanced nodes?

### ISSUE THREAD

**Issue by virtuman** [rancher/rancher#4756]
**Rancher Version:** 
1.1.0-dev1

**Docker Version:**
1.11

**OS and where are the hosts located? (cloud, bare metal, etc):**
CentOS / bare metal

**Setup Details: (single node vs. single node, internal DB vs. external DB)**
multiple nodes, currently in a swarm, but will switch to anything to support needed functionality

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
swarm and/or cattle

**Issue:**
I can't wrap my head around this: we have multiple nodes, and rancher will spin off nginx+php container on one of the nodes or move nginx from one place to another, etc. 
If we don't have shared storage between multiple nodes - is it possible to have new container inherit same state of codebase from an already running container?

**Expected:**
spin up new instance of nginx + php on a different node where code doesn't exist yet or if codebase is outdated - may be it should pull code from the already running instance to sync code base? or am i talking non-sense? I'm almost sure that Ceph is the tool that i need to use for what i'm describing, but i'm not 100% sure if that's the case and if Ceph will work with Rancher correctly or if there's something else that should be used instead?

**Comment by deniseschannon** [comment]
>If we don't have shared storage between multiple nodes - is it possible to have new container inherit same state of codebase from an already running container?

No, you would need some kind of shared storage between the nodes for the container to have the same state of codebase. 

I haven't used Ceph before, but you could look into our convoy NFS or convoy-gluster solutions. 

http://docs.rancher.com/rancher/latest/en/rancher-services/storage-service/

**Comment by virtuman** [comment]
it doesn't seem to work with 1.11 and from my understanding from other tickets - it is a known issue and someone even proposed a possible fix, but it hasn't been fixed to the best of my knowledge.

**Comment by deniseschannon** [comment]
Correct, we currently only support Docker 1.10.3 with Rancher. Support for Docker 1.11 will come in v1.1. https://github.com/rancher/rancher/issues/4491

**Comment by deniseschannon** [comment]
Let me know if you ahve further questions.

**Comment by deniseschannon** [comment]
@virtuman Please re-open if you have more questions.
