### ISSUE TITLE
[BUG] Linode node driver download causes node driver hangups on arm64

### ISSUE THREAD

**Issue by jakefhyde** [rancher/rancher#47569]
**Rancher Server Setup**
- Rancher version: v2.9-head (sha256:a52e14121a551f2d84901379eed46ddab9f99804e5fa93bd63d3abdc21e8064d)

**Describe the bug**

When spinning up Rancher on an arm64 host, the linode driver attempts to install the amd64 versions, which cannot be run. This causes node driver initialization to get stuck, preventing users from creating cloud credentials and subsequently other node driver clusters.

**To Reproduce**

Spin up an arm64 Rancher server

**Result**

Cannot create cloud credentials in UI. Attempting to create under cluster creation results in following error:
```
{"baseType":"error","code":"MissingRequired","message":"a Config field must be set","status":422,"type":"error"}
```

**Expected Result**

Can create credentials with no problem

**Screenshots**

**Additional context**

Relates to https://github.com/harvester/harvester/issues/6053

**Comment by markusewalker** [comment]
Validated this is validated against `head` https://github.com/rancher/rancher/commit/e59c50a79bff2b6cc023bdbdb4e825190b7833fb. Details below:

**ENVIRONMENT DETAILS**
- Rancher install: Docker
- Rancher version: `head` https://github.com/rancher/rancher/commit/e59c50a79bff2b6cc023bdbdb4e825190b7833fb

**TEST RESULT**
|#|Scenario|Result|
|---|---|---|
|1|Provision downstream RKE1 Linode node driver cluster on ARM64 Rancher server|:white_check_mark:|
|2|Provision downstream RKE2 Linode node driver cluster on ARM64 Rancher server|:white_check_mark:|
|3|Provision downstream K3s Linode node driver cluster on ARM64 Rancher server|:white_check_mark:|
|4|Create AWS cloud credendtial in UI|:white_check_mark:|
|5|Create Azure cloud credential in UI|:white_check_mark:|
|6|Create Google cloud credential in UI|:white_check_mark:|
