### ISSUE TITLE
Proper deployment of production load balancer vs DNS zone configuration 

### ISSUE THREAD

**Issue by virtuman** [rancher/rancher#4757]
**Rancher Version:**
1.1.0-dev1

**Docker Version:**
1.11.*

**OS and where are the hosts located? (cloud, bare metal, etc):**
Centos or any other that would support this functionality

**Setup Details: (single node vs. single node, internal DB vs. external DB)**
Tried with swarm and cattle, but the question is mostly about the architects of HA setup

We have multiple user facing nodes and multiple haproxy physical machines that monitor up/down status of various modes and services and direct traffic accordingly. We do not have access to floating IPs just yet, so what I'm trying to understand is this:

Once the LB in rancher is deployed, it gets assigned a random/available Public IP (whichever has that port and more resources available) and it then directs traffic across all available containers (when scaled to more than 1 container) to balance all traffic and to exclude any Down-containers. 

How do I know which ip is going to be assigned to the ranchers load balancer service to reliably assign a DNS entry to our domain name to take advantage of this LB service in production? 

Same question for setting up multiple LB instances for failover? (I understand that rancher will automatically spin up we instance according to scheduling rules, and in this adrift will also gets new IP address) 

How are we supposed to setup the DNS entry for our domain name to properly take advantage of this?

My assumption is that it's pretty much impossible without a Floating IP, or is there a better/ proper way of getting the HA website through rancher's orchestration?

Thank you.

**Comment by vincent99** [comment]
One place is enough please: https://forums.rancher.com/t/need-help-in-understanding-dynamic-assignment-of-load-balancers/2739/1
