### ISSUE TITLE
[BUG] Migrating `rancher.io/expiration-timestamp` causes crashloop if credential uses expired token

### ISSUE THREAD

**Issue by m-ildefons** [rancher/rancher#47583]
**Rancher Server Setup**
- Rancher version: v2.9.3-alpha6 (upgraded from v2.9.2)
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): helm
- Proxy/Cert Details: N/A

**Information about the Cluster**
- Kubernetes version: k3s:v1.27.16-k3s1
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): vcluster on Harvester

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: admin

**Describe the bug**
Rancher crashloops while initializing

**To Reproduce**
- Install Harvester (v1.3.1)
- Install Rancher via vcluster plugin (v2.9.2)
- Upgrade via Helm
```
│ ~/testing │► helm -n cattle-system upgrade rancher rancher-alpha/rancher --devel -f values.yaml --version=v2.9.3-alpha6
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: ./rancher.yaml
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: ./rancher.yaml
W1017 15:00:02.127906  674871 warnings.go:70] cert-manager.io/v1beta1 Issuer is deprecated in v1.4+, unavailable in v1.6+; use cert-manager.io/v1 Issuer
Release "rancher" has been upgraded. Happy Helming!
NAME: rancher
LAST DEPLOYED: Thu Oct 17 14:59:51 2024
NAMESPACE: cattle-system
STATUS: deployed
REVISION: 3
TEST SUITE: None
NOTES:
Rancher Server has been installed.

NOTE: Rancher may take several minutes to fully initialize. Please standby while Certificates are being issued, Containers are started and the Ingress rule comes up.

Check out our docs at https://rancher.com/docs/

If you provided your own bootstrap password during installation, browse to https://rancher.172.19.108.58.sslip.io/ to get started.

If this is the first time you installed Rancher, get started by running this command and clicking the URL it generates:

echo https://rancher.172.19.108.58.sslip.io/dashboard/?setup=$(kubectl get secret --namespace cattle-system bootstrap-secret -o go-template='{{.data.bootstrapPassword|base64decode}}')

To get just the bootstrap password on its own, run:

kubectl get secret --namespace cattle-system bootstrap-secret -o go-template='{{.data.bootstrapPassword|base64decode}}{{ "\n" }}'

Happy Containering!
│ ~/testing │► cat values.yaml 
bootstrapPassword: password1234
global:
  cattle:
    psp:
      enabled: false
hostname: rancher.172.19.108.58.sslip.io
ingress:
  tls:
    source: rancher
replicas: 1
```

**NOTE**: A harvester credential configured to use a non-existent token must existing prior to upgrading. This can be achieved by deleting the corresponding token after creting the cloud credential.

**Result**
Rancher crashloops while initializing

**Expected Result**
Rancher should not crash

**Screenshots**
N/A

**Additional context**
Full container log:
[rancher-544687ffb-kkdbh-x-cattle-system-x-rancher-vcluster_rancher.log](https://github.com/user-attachments/files/17413384/rancher-544687ffb-kkdbh-x-cattle-system-x-rancher-vcluster_rancher.log)

**Comment by irishgordo** [comment]
@m-ildefons  - note:
- https://github.com/rancher/rancher/pull/47650#issuecomment-2430691929

**Comment by khushboo-rancher** [comment]
Closing this as validated as a part of validation of https://github.com/rancher/rancher/issues/47667.
