### ISSUE TITLE
[RFE] Add ability to set tolerations on Rancher pod via chart

### ISSUE THREAD

**Issue by mallardduck** [rancher/rancher#47584]
**Is your feature request related to a problem? Please describe.**
> chart have no ability to tolerate custom taints leading to chart not installable on tainted nodes

This is a coming from a customer PR, just creating an issue to track.

**Describe the solution you'd like**
>Introduce additional value to add tolerations

**Describe alternatives you've considered**

**Additional context**
https://github.com/rancher/rancher/pull/47038

**Comment by deepakpunia-suse** [comment]
Validation for Add ability to set tolerations on Rancher pod via chart passed successfully. 
Details: 
    rke2: v1.31.2+rke2r1
    rancher Version: v2.10-head

1. Grab the new chart from the git repo or an RC,
2. Use the new extraTolerations field in the values file,
3. Add any arbitrary toleration,
4. Deploy the chart,
5. Once it is up, use kubectl to: kubectl get -n cattle-system deployments.apps rancher -o jsonpath='{.spec.template.spec.tolerations}'
6. Verify the value you see includes the toleration you added.

Step 2 Screen shot
![Selection_172](https://github.com/user-attachments/assets/8ebb5934-bc10-49d2-b4fc-e610748b92ba)


Step 5 screen shot
![Selection_172](https://github.com/user-attachments/assets/690d9826-ecab-4b31-9a4d-6b8ba6559c6d)
