### ISSUE TITLE
Inactive storage pool icon is large red sqare

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4758]
**Version:** Master 5/10

**Steps to Reproduce: **
1.  Create a storage pool
2.  Use the API to deactivate

**Results:** large red box with inactive in white inside
![image](https://cloud.githubusercontent.com/assets/11514927/15166160/fa3f36de-16d0-11e6-85cc-c82a2265be8a.png)

**Expected:** Should probably have the red INACTIVE text instead of large red box

**Comment by lvuch** [comment]
https://github.com/rancher/ui/pull/697

**Comment by tfiduccia** [comment]
Version - master 6/9
Verified fixed
