### ISSUE TITLE
Remove support for K8s 1.27 for Rancher 2.10.0

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#47591]
Rancher 2.10.0 is targeted to support K8s versions range 1.28 - 1.31. This means that K8s 1.27 will no longer be officially supported and we want to remove the ability to provision new k8s 1.27 clusters.

- [x] RKE1 provisioned AND standalone - changes in KDM, to be handled as part of this issue - @mitulshah-suse 
- [x] RKE2/k3s provisioned - changes in KDM, to be handled as part of this issue - @mitulshah-suse 
- [x] Hosted providers - EKS, AKS, GKE
	- [x] https://github.com/rancher/aks-operator/issues/693
	- [x] https://github.com/rancher/eks-operator/issues/893
	- [x] https://github.com/rancher/gke-operator/issues/686
	- I believe we will need UI changes similar to https://github.com/rancher/ui/pull/5071 and https://github.com/rancher/ui/pull/5072 but it looks like Highlander team handles them and not UI team (FYI @gaktive / @nwmac)
- [X] Imported clusters - k3s/RKE2 (covered by "RKE2/k3s provisioned")

Note: See https://github.com/rancher/rancher/issues/42828 for a similar change done for Rancher 2.8.0 for reference.

**Comment by gaktive** [comment]
Dashboard has a PR up for the backup list of k8s versions to be updated: https://github.com/rancher/dashboard/pull/12309

**Comment by rishabhmsra** [comment]
Fresh install checks:

- Validated on rancher v2.10-head.
- v1.27 k8s version is removed from RKE1, RKE2, k3s, EKS, AKS and GKE clusters provisioning drop down list.

Upgrade checks:

- Created rancher server v2.9.3,
- Provisioned RKE1, RKE2 and k3s v1.27 node driver clusters.
- Upgraded rancher server to v2.10-dae07ed09601506420c133a69d6e6d27bb7a53ec-head.
- Upgraded k8s clusters from v1.27 to v1.31, upgrade was successful.
- Also validated k8s v1.27 is removed from RKE1, RKE2, k3s, EKS, AKS and GKE clusters provisioning drop down list.
