### ISSUE TITLE
[BUG] VAI Cache DB Files Not Present in Pods/Breaks Rancher UI

### ISSUE THREAD

**Issue by brudnak** [rancher/rancher#47601]
# Rancher Server Setup

| Component                        | Version / Type                      |
| -------------------------------- | ----------------------------------- |
| Rancher version starting         | v2.9.3-alpha6                       |
| Installation option              | Helm (high availability)            |
| RKE binary version used          | v1.6.2                              |
| If Helm Chart k8s cluster        | v1.30.4                             |
| Cert Details                     | external tls `aws acm`              |
| Docker version                   | 20.10.7, build f0df350              |
| Helm version                     | v2.16.8-rancher2                    |
| Downstream cluster type          | not applicable                      |
| Downstream K8s version           | not applicable                      |
| Authentication providers enabled | local                               |
| Logged in user role              | admin                               |
| Browser type                     | Opera GX                            |
| Browser version                  | LVL6 (core: 114.0.5282.93) (arm64)  |
| Dashboard                        | v2.9.3-alpha2                       |
| Webhook version                  | rancher/rancher-webhook:v0.5.3-rc.1 |

# Describe the bug

Enabling vai gives all deployments a UI status of `unknown`. Unable to see the Rancher pods via the UI.

# To Reproduce

1. Start Rancher HA setup on v2.9.3-alpha6 
2. Enable the VAI feature via the Global Settings >>> Feature Flags
3. Wait for the Rancher pods to restart

# Result

Once Rancher restarts after making this change, all deploymets in the UI have a status of `unknown`. And the Rancher pods aren't visible via the UI anymore. 

The `.db` files are not in the pods.

```log
    vai_test.go:421: Expected file informer_object_fields.db not found in pod rancher-c48878785-lf627
--- FAIL: TestVaiTestSuite/TestVAI/InitialState/TestWithVaiInitiallyEnabled/CheckDBFilesInPods/Checking_pod_rancher-c48878785-lf627 (6.28s)
```

# Expected Result

For Rancher to work as usual once the vai feature is enabled.

# Screenshots

![Screenshot 2024-10-17 at 11 27 30 PM](https://github.com/user-attachments/assets/92edb079-1d78-4df8-9a68-19a0cf3a4722)
![Screenshot 2024-10-17 at 11 27 43 PM](https://github.com/user-attachments/assets/66c7450d-e192-430e-be11-9fa880f0d51d)

# Additional Context

- Enabling server side pagination has no affect on the bug
- Also occurs on an HA rancher where the local cluster is K3s
- P0 pre-vai steve test cases still pass both with vai enabled, and disabled
- Still able to see the Rancher pods via kubectl and they are running, can list their logs as seen below:

```log
2024/10/18 06:11:41 DEBUG: CacheFor STARTS creating informer for cluster.x-k8s.io/v1beta1, Kind=Machine
2024/10/18 06:11:41 DEBUG: CacheFor STARTS creating informer for management.cattle.io/v3, Kind=NodePool
2024/10/18 06:11:41 DEBUG: CacheFor IS DONE creating informer for cluster.x-k8s.io/v1beta1, Kind=Machine (took 104.984656ms)
2024/10/18 06:11:41 DEBUG: CacheFor IS DONE creating informer for management.cattle.io/v3, Kind=NodePool (took 106.777265ms)
2024/10/18 06:11:44 DEBUG: CacheFor STARTS creating informer for management.cattle.io/v3, Kind=FleetWorkspace
2024/10/18 06:11:45 DEBUG: CacheFor IS DONE creating informer for management.cattle.io/v3, Kind=FleetWorkspace (took 104.355102ms)
2024/10/18 06:11:45 DEBUG: CacheFor STARTS creating informer for provisioning.cattle.io/v1, Kind=Cluster
2024/10/18 06:11:45 DEBUG: CacheFor STARTS creating informer for management.cattle.io/v3, Kind=RancherUserNotification
2024/10/18 06:11:45 DEBUG: CacheFor IS DONE creating informer for provisioning.cattle.io/v1, Kind=Cluster (took 104.799826ms)
2024/10/18 06:11:45 DEBUG: CacheFor IS DONE creating informer for management.cattle.io/v3, Kind=RancherUserNotification (took 104.042441ms)
2024/10/18 06:11:47 DEBUG: CacheFor STARTS creating informer for management.cattle.io/v3, Kind=Project
2024/10/18 06:11:47 DEBUG: CacheFor STARTS creating informer for ui.cattle.io/v1, Kind=NavLink
2024/10/18 06:11:48 DEBUG: CacheFor IS DONE creating informer for management.cattle.io/v3, Kind=Project (took 105.127747ms)
2024/10/18 06:11:48 DEBUG: CacheFor IS DONE creating informer for ui.cattle.io/v1, Kind=NavLink (took 112.293293ms)
2024/10/18 06:11:50 DEBUG: CacheFor STARTS creating informer for /v1, Kind=Node
2024/10/18 06:11:50 DEBUG: CacheFor IS DONE creating informer for /v1, Kind=Node (took 106.538014ms)
2024/10/18 06:11:51 DEBUG: CacheFor STARTS creating informer for apps/v1, Kind=Deployment
2024/10/18 06:11:51 DEBUG: CacheFor IS DONE creating informer for apps/v1, Kind=Deployment (took 105.68659ms)
2024/10/18 06:11:57 DEBUG: CacheFor STARTS creating informer for networking.k8s.io/v1, Kind=Ingress
2024/10/18 06:11:57 DEBUG: CacheFor IS DONE creating informer for networking.k8s.io/v1, Kind=Ingress (took 106.900596ms)
W1018 06:12:01.978418      40 reflector.go:470] pkg/mod/k8s.io/client-go@v0.30.1/tools/cache/reflector.go:232: watch of cluster.x-k8s.io/v1beta1, Kind=Machine ended with: very short watch: pkg/mod/k8s.io/client-go@v0.30.1/tools/cache/reflector.go:232: Unexpected watch close - watch lasted less than a second and no items received
W1018 06:12:04.313590      40 warnings.go:70] v1 ComponentStatus is deprecated in v1.19+
2024/10/18 06:12:04 DEBUG: CacheFor STARTS creating informer for /v1, Kind=Namespace
2024/10/18 06:12:04 DEBUG: CacheFor IS DONE creating informer for /v1, Kind=Namespace (took 112.759655ms)
```

```log
2024/10/18 06:27:01 DEBUG: CacheFor IS DONE creating informer for networking.k8s.io/v1, Kind=Ingress (took 105.62943ms)
2024/10/18 06:27:01 DEBUG: CacheFor IS DONE creating informer for /v1, Kind=Pod (took 128.109014ms)
2024/10/18 06:29:26 [ERROR] Error during subscribe websocket: close sent
W1018 06:35:27.560568      40 reflector.go:470] pkg/mod/k8s.io/client-go@v0.30.1/tools/cache/reflector.go:232: watch of /v1, Kind=Event ended with: very short watch: pkg/mod/k8s.io/client-go@v0.30.1/tools/cache/reflector.go:232: Unexpected watch close - watch lasted less than a second and no items received
W1018 06:49:02.097962      40 reflector.go:470] pkg/mod/k8s.io/client-go@v0.30.1/tools/cache/reflector.go:232: watch of /v1, Kind=Event ended with: very short watch: pkg/mod/k8s.io/client-go@v0.30.1/tools/cache/reflector.go:232: Unexpected watch close - watch lasted less than a second and no items received
W1018 06:56:42.784565      40 reflector.go:470] pkg/mod/k8s.io/client-go@v0.30.1/tools/cache/reflector.go:232: watch of /v1, Kind=Event ended with: very short watch: pkg/mod/k8s.io/client-go@v0.30.1/tools/cache/reflector.go:232: Unexpected watch close - watch lasted less than a second and no items received
W1018 07:24:26.027342      40 reflector.go:470] pkg/mod/k8s.io/client-go@v0.30.1/tools/cache/reflector.go:232: watch of /v1, Kind=Event ended with: very short watch: pkg/mod/k8s.io/client-go@v0.30.1/tools/cache/reflector.go:232: Unexpected watch close - watch lasted less than a second and no items received
W1018 07:39:20.523622      40 reflector.go:470] pkg/mod/k8s.io/client-go@v0.30.1/tools/cache/reflector.go:232: watch of /v1, Kind=Event ended with: very short watch: pkg/mod/k8s.io/client-go@v0.30.1/tools/cache/reflector.go:232: Unexpected watch close - watch lasted less than a second and no items received
2024/10/18 07:44:28 DEBUG: CacheFor STARTS creating informer for apps/v1, Kind=Deployment
2024/10/18 07:44:28 DEBUG: CacheFor STARTS creating informer for catalog.cattle.io/v1, Kind=App
2024/10/18 07:44:28 DEBUG: CacheFor IS DONE creating informer for apps/v1, Kind=Deployment (took 109.772619ms)
2024/10/18 07:44:28 DEBUG: CacheFor IS DONE creating informer for catalog.cattle.io/v1, Kind=App (took 112.463158ms)
```

# Workaround

Disabling the vai cache does fix the UI

# Bug Frequency

| Frequency                                                                                          | Selected Option |
| -------------------------------------------------------------------------------------------------- | --------------- |
| Consistent (10/10) - A consistent bug can be replicated every time the test is executed.           | ✅               |
| Frequent (7/10)- A frequent bug can be replicated like 7 out of 10 times when a test is replicated |                 |
| Occasional (5/10) - Occasional bug is more hard to replicate than a frequent bug.                  |                 |
| Once thus far, twice thus far - Few bugs cannot be reproduced every time you run the test.         |                 |

**Comment by richard-cox** [comment]
This is a known bug - https://github.com/rancher/dashboard/issues/12265 and was agreed not a release blocker. I tihnk @MbolotSuse was going to get a fix in for a later version

**Comment by tomleb** [comment]
> vai_test.go:421: Expected file informer_object_fields.db not found in pod rancher-c48878785-lf627

We have removed the db `informer_object_fields.db` in https://github.com/rancher/lasso/pull/97 so only `informer_object_cache.db` should be checked for existence. (In fact now we also actually enable WAL mode so you may want to verify that all three files exist: `informer_object_cache.db`, `informer_object_cache.db-shm`, `informer_object_cache.db-wal`

**Comment by tomleb** [comment]
Verified and agree with @richard-cox it's that same issue. Basically, listing resources contain the state field correctly, but data coming from the watch doesn't. That page is watching the deployments so on initial page load we get the correct state but they quickly become "unknown" when we receive the data from the watch.

**Comment by MbolotSuse** [comment]
PR: rancher/steve#300

**Comment by MbolotSuse** [comment]
## Validation Template

## Root Cause

With rancher/steve#264 support for Transform functions was added to the SQL cache mode. This caused steve to add the metadata.state, metadata.relationships, and id fields before the object was added to the SQL cache. Because of this, the formatter (which previously added these values at a later layer before the request was returned to the user) was changed to no longer add these values when the sql cache was enabled, in order to not duplicate this addition.

However, this change didn't fully work. While the list calls use the SQL cache to return information to the user, the other calls (create/update/delete/get/watch) did not use the cache, and instead returned objects to the user as they are seen by Kuberentes. Since the formatter was no longer adding the metadata.state when the SQL cache is on, this caused objects retrieved by this operation to be missing the metadata.state and metadata.relationships values.

## What was fixed, or what change have occurred

The formatter now will always add the metadata.state and metadata.relationships, like it did before rancher/steve#264.

## Areas or cases that should be tested

1. The dashboard issues which were caused by this bug. This includes:
  - rancher/dashobard#12262
  - rancher/dashboard#12265
  - rancher/dashboard#12266
2. The original issue present in this ticket (note: see [this comment](https://github.com/rancher/rancher/issues/47601#issuecomment-2422402055) for information about the db name, which wasn't related to this change).
3. The presence of metadata.state, id, and metadata.relationships for non-list operations. Note that this value should be the same when compared with list - so if list has the value, so should get (and it should be the same value). But if the value is missing on list, it should also be missing on get. This includes the following operations:
  - Get (single object by name)
  - Create
  - Update
  - Watch
4. Regression checks on how metadata.state and metadata.relationships is calculated for list operations (see below).

## What areas could experience regressions

The calculation of metadata.state and metadata.relationships for list calls. These values should be set on the list calls in the same way as before. They should also be usable for filtering/sorting (when the feature is enabled), like before. Lastly, they should be set to the same values as is visible on the objects when they are retrieved through other operations (note - there may be slight discrepancies here due to cache timing and object state change).

## Are the repro steps accurate/minimal?

Yes, some are included here for convienence.
1. Start rancher.
2. Change `ui-sql-cache` to true.
3. Navigate to the cluster creation screen. Click create.
4. Notice that the node drivers appear for a moment before rapidly vanishing (before, after they should be present).

**Comment by brudnak** [comment]
<details>
    <summary>🧪 Test Environment... CLICK TO EXPAND! ⬅️</summary>
<br>


| Component                        | Version / Type                                      |
| -------------------------------- | --------------------------------------------------- |
| Rancher version starting         | 2.9.2                                               |
| Rancher version upgraded         | v2.10-6e85a811efd6b831c3d49a7336a6d4b3e96c1a93-head |
| Installation option              | Helm (high availability)                            |
| RKE binary version used          | v1.6.2                                              |
| If Helm Chart k8s cluster        | v1.30.4                                             |
| Cert Details                     | external tls `aws acm`                              |
| Docker version                   | 20.10.7, build f0df350                              |
| Downstream cluster type          | not applicable                                      |
| Downstream K8s version           | not applicable                                      |
| Authentication providers enabled | local                                               |
| Logged in user role              | admin                                               |
| Webhook version                  | rancher/rancher-webhook:v0.6.1-rc.9                 |

</details>

<a name="top"></a>

### 🧪 Test Cases

| \#  | Priority | Description & Link                                  | PASS/FAIL |
| --- | -------- | --------------------------------------------------- | --------- |
| 1   | P0       | [Fresh Install `ui-sql-cache` Enabled](#test-1)     | ✅ `PASS`  |
| 2   | P0       | [(Regression check) Validation Automation](#test-2) | ✅ `PASS`  |
| 3   | P0       | [ID Sort, Filter](#test-3)                          | ✅ `PASS`  |
| 4   | P0       | [Metadata Sort, Filter](#test-4)                    | ✅ `PASS`  |
| 5   | P0       | [Upgrade](#test-5)                                  | ✅ `PASS`  |


<details>
    <summary>🚨 5 test cases... CLICK TO EXPAND! (For table links to work) ⬅️</summary>
<br>

# 1 / Fresh Install `ui-sql-cache` Enabled Status: ✅ `PASS`

<a name="test-1"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 1 details... Click to expand</summary>

**Test Steps for Validation**

1. Enable vai
2. Navigate to local cluster >>> Workloads >>> Pods >>> All Namespaces
3. Ensure all pods are visible

**✅ Expected Outcome**

For all pods to be visible

**✅ Actual Outcome**

All pods were visible


</details>
<hr>

# 2 / (Regression check) Validation Automation Status: ✅ `PASS`

<a name="test-2"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 2 details... Click to expand</summary>

**Test Steps for Validation**

1. Enable vai
2. Run validation tests
3. All passing

```log
=== RUN   TestVaiTestSuite
=== RUN   TestVaiTestSuite/TestVaiEnabled
=== RUN   TestVaiTestSuite/TestVaiEnabled/SecretFilters
=== RUN   TestVaiTestSuite/TestVaiEnabled/SecretFilters/Filter_with_negation_and_namespace
time="2024-10-29T20:39:34-07:00" level=info msg="Starting case: Filter with negation and namespace"
time="2024-10-29T20:39:34-07:00" level=info msg="Running with vai enabled: [true]"
time="2024-10-29T20:39:34-07:00" level=info msg="Creating namespace: namespace-tizrhwvm"
--- PASS: TestVaiTestSuite/TestVaiEnabled/SecretFilters/Filter_with_negation_and_namespace (0.69s)
=== RUN   TestVaiTestSuite/TestVaiEnabled/SecretFilters/Filter_by_namespace
time="2024-10-29T20:39:35-07:00" level=info msg="Starting case: Filter by namespace"
time="2024-10-29T20:39:35-07:00" level=info msg="Running with vai enabled: [true]"
time="2024-10-29T20:39:35-07:00" level=info msg="Creating namespace: namespace1-ixyfkfnb"
time="2024-10-29T20:39:35-07:00" level=info msg="Creating namespace: namespace2-ixyfkfnb"
--- PASS: TestVaiTestSuite/TestVaiEnabled/SecretFilters/Filter_by_namespace (0.91s)
=== RUN   TestVaiTestSuite/TestVaiEnabled/SecretFilters/Filter_by_name_and_namespace
time="2024-10-29T20:39:36-07:00" level=info msg="Starting case: Filter by name and namespace"
time="2024-10-29T20:39:36-07:00" level=info msg="Running with vai enabled: [true]"
time="2024-10-29T20:39:36-07:00" level=info msg="Creating namespace: namespace-hmdbbrjk"
--- PASS: TestVaiTestSuite/TestVaiEnabled/SecretFilters/Filter_by_name_and_namespace (0.39s)
--- PASS: TestVaiTestSuite/TestVaiEnabled/SecretFilters (2.00s)
=== RUN   TestVaiTestSuite/TestVaiEnabled/PodFilters
=== RUN   TestVaiTestSuite/TestVaiEnabled/PodFilters/Filter_by_nginx_image
time="2024-10-29T20:39:36-07:00" level=info msg="Starting case: Filter by nginx image"
time="2024-10-29T20:39:36-07:00" level=info msg="Running with vai enabled: [true]"
time="2024-10-29T20:39:36-07:00" level=info msg="Creating namespace: namespace1-esxnsaea"
time="2024-10-29T20:39:36-07:00" level=info msg="Creating namespace: namespace2-esxnsaea"
--- PASS: TestVaiTestSuite/TestVaiEnabled/PodFilters/Filter_by_nginx_image (0.58s)
=== RUN   TestVaiTestSuite/TestVaiEnabled/PodFilters/Filter_by_busybox_image
time="2024-10-29T20:39:37-07:00" level=info msg="Starting case: Filter by busybox image"
time="2024-10-29T20:39:37-07:00" level=info msg="Running with vai enabled: [true]"
time="2024-10-29T20:39:37-07:00" level=info msg="Creating namespace: namespace1-qoludtly"
time="2024-10-29T20:39:37-07:00" level=info msg="Creating namespace: namespace2-qoludtly"
--- PASS: TestVaiTestSuite/TestVaiEnabled/PodFilters/Filter_by_busybox_image (0.60s)
=== RUN   TestVaiTestSuite/TestVaiEnabled/PodFilters/Filter_by_non-existent_image
time="2024-10-29T20:39:37-07:00" level=info msg="Starting case: Filter by non-existent image"
time="2024-10-29T20:39:37-07:00" level=info msg="Running with vai enabled: [true]"
time="2024-10-29T20:39:37-07:00" level=info msg="Creating namespace: namespace1-exfvfxsr"
time="2024-10-29T20:39:37-07:00" level=info msg="Creating namespace: namespace2-exfvfxsr"
--- PASS: TestVaiTestSuite/TestVaiEnabled/PodFilters/Filter_by_non-existent_image (0.76s)
--- PASS: TestVaiTestSuite/TestVaiEnabled/PodFilters (1.94s)
=== RUN   TestVaiTestSuite/TestVaiEnabled/SecretSorting
=== RUN   TestVaiTestSuite/TestVaiEnabled/SecretSorting/Sort_by_name_ascending
time="2024-10-29T20:39:38-07:00" level=info msg="Starting case: Sort by name ascending"
time="2024-10-29T20:39:38-07:00" level=info msg="Running with vai enabled: [true]"
--- PASS: TestVaiTestSuite/TestVaiEnabled/SecretSorting/Sort_by_name_ascending (0.89s)
=== RUN   TestVaiTestSuite/TestVaiEnabled/SecretSorting/Sort_by_name_descending
time="2024-10-29T20:39:39-07:00" level=info msg="Starting case: Sort by name descending"
time="2024-10-29T20:39:39-07:00" level=info msg="Running with vai enabled: [true]"
--- PASS: TestVaiTestSuite/TestVaiEnabled/SecretSorting/Sort_by_name_descending (0.78s)
=== RUN   TestVaiTestSuite/TestVaiEnabled/SecretSorting/Sort_by_namespace_ascending
time="2024-10-29T20:39:40-07:00" level=info msg="Starting case: Sort by namespace ascending"
time="2024-10-29T20:39:40-07:00" level=info msg="Running with vai enabled: [true]"
--- PASS: TestVaiTestSuite/TestVaiEnabled/SecretSorting/Sort_by_namespace_ascending (0.74s)
=== RUN   TestVaiTestSuite/TestVaiEnabled/SecretSorting/Sort_by_namespace_descending
time="2024-10-29T20:39:40-07:00" level=info msg="Starting case: Sort by namespace descending"
time="2024-10-29T20:39:40-07:00" level=info msg="Running with vai enabled: [true]"
--- PASS: TestVaiTestSuite/TestVaiEnabled/SecretSorting/Sort_by_namespace_descending (0.64s)
=== RUN   TestVaiTestSuite/TestVaiEnabled/SecretSorting/Sort_by_name_and_namespace_ascending
time="2024-10-29T20:39:41-07:00" level=info msg="Starting case: Sort by name and namespace ascending"
time="2024-10-29T20:39:41-07:00" level=info msg="Running with vai enabled: [true]"
--- PASS: TestVaiTestSuite/TestVaiEnabled/SecretSorting/Sort_by_name_and_namespace_ascending (0.66s)
=== RUN   TestVaiTestSuite/TestVaiEnabled/SecretSorting/Sort_by_namespace_and_name_ascending
time="2024-10-29T20:39:42-07:00" level=info msg="Starting case: Sort by namespace and name ascending"
time="2024-10-29T20:39:42-07:00" level=info msg="Running with vai enabled: [true]"
--- PASS: TestVaiTestSuite/TestVaiEnabled/SecretSorting/Sort_by_namespace_and_name_ascending (0.64s)
=== RUN   TestVaiTestSuite/TestVaiEnabled/SecretSorting/Sort_by_name_ascending_and_namespace_descending
time="2024-10-29T20:39:42-07:00" level=info msg="Starting case: Sort by name ascending and namespace descending"
time="2024-10-29T20:39:42-07:00" level=info msg="Running with vai enabled: [true]"
--- PASS: TestVaiTestSuite/TestVaiEnabled/SecretSorting/Sort_by_name_ascending_and_namespace_descending (0.67s)
=== RUN   TestVaiTestSuite/TestVaiEnabled/SecretSorting/Sort_by_namespace_descending_and_name_ascending
time="2024-10-29T20:39:43-07:00" level=info msg="Starting case: Sort by namespace descending and name ascending"
time="2024-10-29T20:39:43-07:00" level=info msg="Running with vai enabled: [true]"
--- PASS: TestVaiTestSuite/TestVaiEnabled/SecretSorting/Sort_by_namespace_descending_and_name_ascending (0.68s)
--- PASS: TestVaiTestSuite/TestVaiEnabled/SecretSorting (5.69s)
=== RUN   TestVaiTestSuite/TestVaiEnabled/SecretLimit
=== RUN   TestVaiTestSuite/TestVaiEnabled/SecretLimit/Paginate_50_secrets_with_limit_10
time="2024-10-29T20:39:44-07:00" level=info msg="Starting case: Paginate 50 secrets with limit 10"
time="2024-10-29T20:39:44-07:00" level=info msg="Running with vai enabled: [true]"
--- PASS: TestVaiTestSuite/TestVaiEnabled/SecretLimit/Paginate_50_secrets_with_limit_10 (5.13s)
=== RUN   TestVaiTestSuite/TestVaiEnabled/SecretLimit/Paginate_100_secrets_with_limit_25
time="2024-10-29T20:39:49-07:00" level=info msg="Starting case: Paginate 100 secrets with limit 25"
time="2024-10-29T20:39:49-07:00" level=info msg="Running with vai enabled: [true]"
--- PASS: TestVaiTestSuite/TestVaiEnabled/SecretLimit/Paginate_100_secrets_with_limit_25 (9.00s)
=== RUN   TestVaiTestSuite/TestVaiEnabled/SecretLimit/Paginate_30_secrets_with_limit_50
time="2024-10-29T20:39:58-07:00" level=info msg="Starting case: Paginate 30 secrets with limit 50"
time="2024-10-29T20:39:58-07:00" level=info msg="Running with vai enabled: [true]"
--- PASS: TestVaiTestSuite/TestVaiEnabled/SecretLimit/Paginate_30_secrets_with_limit_50 (2.75s)
--- PASS: TestVaiTestSuite/TestVaiEnabled/SecretLimit (16.88s)
--- PASS: TestVaiTestSuite/TestVaiEnabled (26.51s)
--- PASS: TestVaiTestSuite (41.22s)
PASS
```

**✅ Expected Outcome**

All tests to pass

**✅ Actual Outcome**

All tests were passing

</details>
<hr>

# 3 / ID Sort, Filter Status: ✅ `PASS`

<a name="test-3"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 3 details... Click to expand</summary>

**Test Steps for Validation**

1. Enable vai
2. Run: 

```sh
curl -s https://raw.githubusercontent.com/brudnak/rancher-test-scripts/refs/heads/main/2.10.0/46330/script.sh | bash -s rancher.url token123 local.yaml
```

```log
Test Summary:
Test Run ID: mj5s9c
Namespace: synthetic-test-mj5s9c
Pod Names:
- test-pod-1-4zmk67
- test-pod-2-sutc2u
- test-pod-3-4ojdoy

============== Test Summary ==============
Total tests run: 8
✅ Filter by ID Test
✅ Filter by Multiple IDs Test
✅ Filter Running Pods Test
✅ Filter by IDs AND State Test
✅ Sort Pods by ID Descending Test
✅ Sort Pods by State Test
✅ Limit Pods Test
✅ Combined Operations Test

Results:
Passed: 8
Failed: 0
Success rate: 100%
```

**✅ Expected Outcome**

All tests to pass

**✅ Actual Outcome**

All tests passing

</details>
<hr>

# 4 / Metadata Sort, Filter Status: ✅ `PASS`

<a name="test-4"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 4 details... Click to expand</summary>

**Test Steps for Validation**

1. Enable vai
2. Run: 

```sh
curl -s https://raw.githubusercontent.com/brudnak/rancher-test-scripts/refs/heads/main/2.10.0/46330/script.sh | bash -s rancher.url token123 local.yaml
```

```log
Test Summary:
Test Run ID: mj5s9c
Namespace: synthetic-test-mj5s9c
Pod Names:
- test-pod-1-4zmk67
- test-pod-2-sutc2u
- test-pod-3-4ojdoy

============== Test Summary ==============
Total tests run: 8
✅ Filter by ID Test
✅ Filter by Multiple IDs Test
✅ Filter Running Pods Test
✅ Filter by IDs AND State Test
✅ Sort Pods by ID Descending Test
✅ Sort Pods by State Test
✅ Limit Pods Test
✅ Combined Operations Test

Results:
Passed: 8
Failed: 0
Success rate: 100%
```

**✅ Expected Outcome**

All tests to pass

**✅ Actual Outcome**

All tests passing


</details>
<hr>

# 5 / Upgrade Status: ✅ `PASS`

<a name="test-5"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 5 details... Click to expand</summary>

**Test Steps for Validation**

1. Start Rancher from the previous released version
2. Upgrade to this version of Rancher
3. Repeat all test cases

**✅ Expected Outcome**

All test cases should pass on an upgraded Rancher setup

**✅ Actual Outcome**

All test cases passed on the upgraded Rancher


</details>
<hr>

</details>
