### ISSUE TITLE
[rancher/charts:v2.9] Bump Shell image for prometheus-federator

### ISSUE THREAD

**Issue by mallardduck** [rancher/rancher#47610]
Per title, the 2.9 Branch of `prometheus-federator` should bump the shell version to be matching the one used by Rancher 2.9 by default.

Additionally we need to apply this change (a partial backport of this file change only): https://github.com/mallardduck/rancher-charts/blob/6b0d9587bc045b37bee62f4ef015c7e1c285a860/packages/rancher-monitoring/prometheus-federator/generated-changes/patch/charts/helmProjectOperator/values.yaml.patch

> This includes both fixing the shell version and the additional change. The shell version for 2.9 should use v0.2.2 (or highest 0.2.x); and if we do the same for 2.8 we should use v0.1.26 (or highest 0.1.x).

**Comment by pankajsqe** [comment]
Prometheus Federator chart  104.0.2-rc.1+up0.4.2 has been validated.

![Image](https://github.com/user-attachments/assets/624ca84f-ea11-4412-8b7e-75651a7cfb89)
![Image](https://github.com/user-attachments/assets/971f455e-b93e-46b6-af26-e17265963a42)
![Image](https://github.com/user-attachments/assets/bbd3a9d3-87fa-4126-883b-bbb3350e8fe2)
![Image](https://github.com/user-attachments/assets/264b31bb-e5c9-4101-9f9f-40c539e8c05b)
