### ISSUE TITLE
Containers not reachable using their unique hostname

### ISSUE THREAD

**Issue by Kajvdh** [rancher/rancher#4761]
When I'm deploying a couple of services using a `docker-compose.yml` file using rancher, each instance is given a random unique hostname, which is fine. But how does it come that containers that are linked with each other can not reach each other using their given hostname?

They need to use the alias that was given to the link. Is it somehow possible that they will be able to use the hostname as well?

I'll try to situate the problem: I have a service discovery, and each service registers itself with their unique hsotname at the service discovery. 

An API gateway will try to reach these instances using the hostnames that the services registered theirselves with, but, as addressed above, this does not work.

PS: The services are not always on the same EC2 instance.

**Comment by Rucknar** [comment]
@Kajvdh One possible approach..

You can override the default container name to match the name you see in the GUI.
This is done using labels, see below for a compose file example of such, these can be added in the GUI as well if you so wish:

```
  labels:
    io.rancher.container.hostname_override: container_name
```
So, if you had a stack called `prod` and a service called `webservers` and you had two of them, the container names would be `prod_webservers_1` and `prod_webservers_2`. You should then be able to ping that name either in the same stack or from outside it. 

Some more docs on the DNS: http://docs.rancher.com/rancher/latest/en/rancher-services/internal-dns-service/

**Comment by deniseschannon** [comment]
@Kajvdh If you have further questions, please re-open.
