### ISSUE TITLE
[BUG] SAML logout error reported for a non SAML provider

### ISSUE THREAD

**Issue by pmatseykanets** [rancher/rancher#47630]
**Rancher Server Setup**
- Rancher version: main HEAD
- Installation option (Docker install/Helm Chart): N/A
- Proxy/Cert Details: N/A

**Information about the Cluster**
- Kubernetes version: v1.30.4+k3s1
- Cluster Type (Local/Downstream): local

**User Information**
- What is the role of the user logged in? Any

**Describe the bug**

A fresh rancher install is configured with OpenLDAP auth provider. When a user logs out an error message is produced in logs

```
[ERROR] Unknown error: SAML [logout]: Rancher provider resource `openldap` not configured at all
``` 

Most likely caused by https://github.com/rancher/rancher/pull/45379

**To Reproduce**

- Install rancher
- Enable OpenLDAP provider
- Log in with an LDAP user
- Log out

**Result**

**Expected Result**

SAML logout logic should not be called for non SAML auth providers. Or more generally auth provider specific logic should take into account the provider type.

**Screenshots**

**Additional context**

**Comment by nickwsuse** [comment]
Verified on v2.10-head ID: `212d8b6` ✅ 
----
Verified with two SAML and two non-SAML auth providers, both of which login and logout functions work as expected with no errors.
