### ISSUE TITLE
Error while adding a Softlayer host

### ISSUE THREAD

**Issue by MrDHat** [rancher/rancher#4764]
**Rancher Version:**
Latest

**Docker Version:**
1.11.1

**OS and where are the hosts located? (cloud, bare metal, etc):**
Softlayer Cloud

**Setup Details: (single node vs. single node, internal DB vs. external DB)**
Single Node

**Steps to Reproduce:**
- Click on `Add Host` and select `Other`
- Select the `softlayer` driver from the driver list
- Enter the `SNG01` as the region

**Results:** 
Creation of host fails with an error: `Error in driver during machine creation: Error creating host: "Error in response: A datacenter could not be found with the name SNG01."`

**Expected:**
Creation of host without any issues

**Comment by vincent99** [comment]
We just pass the options to docker-machine.  I don't have an account setup but that appears to be a region..  The default is lowercase (https://docs.docker.com/machine/drivers/soft-layer/) so I'm guessing its case-sensitive in the driver and they expect all lowercase.

**Comment by deniseschannon** [comment]
@MrDHat Please re-open if you have additional questions/need help. 

Another issue is that you can take the command from docker-machine (located in the rancher/server logs) to see if you can launch using docker-machine.
