### ISSUE TITLE
[2.10] Bump calico & canal to support v1.31

### ISSUE THREAD

**Issue by chiukapoor** [rancher/rancher#47641]
- Bump calico & canal to v3.29.0 ([reference](https://docs.tigera.io/calico/latest/getting-started/kubernetes/requirements#kubernetes-requirements)) to support k8s v1.31

**Comment by rishabhmsra** [comment]
Validated on rancher v2.10-d268d218b4bc29b029ae9b3433d1a9ac49a6f370-head

- Provisioned v1.31.3-rancher1-1 using calico and canal CNI.
- Validated calico and canal version and it's bumped to v3.29.0

```
rancher/mirrored-calico-kube-controllers:v3.29.0
rancher/mirrored-calico-node:v3.29.0
```
- All network checks also passed as part of KDM checks.
