### ISSUE TITLE
[Backport v2.9] [BUG] RKE1 Azure node template has Ubuntu 18.04 as default image. Docker fails to install during cluster nodes provision

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#47644]
Backport of https://github.com/rancher/rancher/issues/44944 to v2.9.x line of releases

Note that the change is in https://github.com/rancher/machine which is currently not branched by release line so bumping `rancher/machine` to version with the changes is the only expectation for v2.9.x PR.

**Comment by snasovich** [comment]
Moving this to next milestone to have more time to sort out https://github.com/rancher/rancher/pull/47700#issuecomment-2442291593

**Comment by jiaqiluo** [comment]
This issue can be validated on the last v2.9-head image
