### ISSUE TITLE
Agent cannot register in HA behind plaintext ELB connection

### ISSUE THREAD

**Issue by lekum** [rancher/rancher#4765]
**Rancher Version:** 1.0.1

**Docker Version:** 1.11.1

**OS and where are the hosts located? (cloud, bare metal, etc):**  RHEL 7.2 in AWS

**Setup Details: (single node vs. single node, internal DB vs. external DB)** Multinode, external DB (AWS Aurora), behind ELB, SSL terminated at Rancher Server

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:** 
Followed the [instructions](http://docs.rancher.com/rancher/latest/en/installing-rancher/installing-server/multi-nodes/) for HA. 

Manually edited the `rancher-ha.sh` script to use `http` instead of `https`. The registration URL is the internal ELB FQDN. Also this ELB is configured as described in #4738

Manually created a host in EC2 and run the "add custom host" docker run command.

**Results:** The agent does not complete registration. I attach the rancher agent logs:

[rancher_agent_log.txt](https://github.com/rancher/rancher/files/259586/rancher_agent_log.txt)

**Expected:**

The host to be added to the environment.

**Comment by lekum** [comment]
Hi,

I update with more detailed logs from inside the container (`/var/log/rancher/agent.log`) when tries to register:

[agent.log.txt](https://github.com/rancher/rancher/files/261224/agent.log.txt)

Maybe the repeated message of:

```
119696] [connectionpool.py:242] Resetting dropped connection: ELB-URL
```

gives any hint.

Please note that ELB-URL is a the edited URL of our internal FQDN (the registration URL). That URL is accesible from the agent and running a `curl` on the URL returns a JSON.

**Comment by lekum** [comment]
My mistake, reading again the docs, I spotted that I had to manually create the `/var/lib/rancher/etc/ssl/ca.crt` file in the dockerhost. I have submitted a [pull request](https://github.com/lekum/rancher.github.io/pull/1) to the documentation in case it clarifies it a bit more.

Thanks!

**Comment by will-chan** [comment]
Thanks.  @deniseschannon can we fix the doc?

**Comment by aemneina** [comment]
Actually if you want end to end encryption you'll need your ELB configured to point:
TCP:443->TCP:444
if you want the SSL terminated at the ELB, use:
SSL:443->TCP:81
