### ISSUE TITLE
[BUG] Cloud-init for Nutanix RKE2 is only one line

### ISSUE THREAD

**Issue by Carl-ErikR** [rancher/rancher#47663]
**Rancher Server Setup**
- Rancher version: 2.9.3-alpha6
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version:
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): Admin
  - If custom, define the set of permissions:

**Describe the bug**

When creating an RKE2 cluster you only get one line to enter cloud-init configuration. RKE1 works correctly
**To Reproduce**

**Result**
You hit enter -> no additional line(s)
**Expected Result**

You hit enter -> additional line(s)
**Screenshots**

RKE2:
![rke2_nutanix](https://github.com/user-attachments/assets/ea5d5a4d-185c-4ffe-82a4-6f94fc86890e)
RKE1 Node template:
![rke1_nutanix](https://github.com/user-attachments/assets/5ac25ce2-76a2-402a-8ae0-aec4c5e156e2)

**Additional context**

**Comment by tuxtof** [comment]
with RKE2 you need to use the [nutanix rancher extension](https://github.com/nutanix-cloud-native/nutanix-rancher-extension)

**Comment by Carl-ErikR** [comment]
@tuxtof Thanks! :)
