### ISSUE TITLE
Inject IP address as environment variable

### ISSUE THREAD

**Issue by Kajvdh** [rancher/rancher#4767]
Is it possible to inject the IP address that rancher assigns to a container as an environment variable into the container? (The ip within the **10.42.*.*** range)

I know that I e.g. can inject the hostname using `$HOSTNAME` in my docker-compose.yml file, but is there a way to do the same with the IP address assigned by Rancher?

**Comment by vincent99** [comment]
`io.rancher.container.requested_ip=10.42.x.y` label (http://docs.rancher.com/rancher/latest/en/labels/)

**Comment by Kajvdh** [comment]
@vincent99 If I understand correctly, that is to set a specific pre-defined IP address? I don't mind it being a random IP, I just want my container to know it.

Because now the containers that I've deployed using rancher have 2 ip adresses, a `172.17.0.*` ip adress, given by the docker daemon and a `10.42.*.*` ip address given by rancher. But I want my applications to use (and therefore be aware of) the rancher ip's because they need to communicate with other containers over different EC2 instances.

**Comment by vincent99** [comment]
Yeah, that's what I thought you meant by inject.

It is not possible to use the IP of the container as a variable because the they are interpolated before the container(s) are created and before an IP is assigned.  You can get it at runtime in your entrypoint from `ip addr show` or metadata (`curl http://rancher-metadata/2015-12-19/self/container/ips/0`)

**Comment by kaos** [comment]
In case you're using NodeJS, you can get it from there too (we don't have the `ip` tool in our stripped container):
```
    // get our ip address, prefer one that begins with `prefix`.
    function getIpAddress(prefix) {
      var ifaces = os.networkInterfaces();
      var address = '';

      for (var ifname in ifaces) {
        if (ifname == 'lo') {
          continue;
        }
        for (var ifidx in ifaces[ifname]) {
          var iface = ifaces[ifname][ifidx];
          if ('IPv4' == iface.family && !iface.internal) {
            address = iface.address;
          }
          if (prefix && address.substring(0, prefix.length) == prefix) {
            return address;
          }
        }
      }
      return address;
    }

   ...
  address = getIpAddress('10.42.');
```

inspired by this stackoverflow answer: http://stackoverflow.com/a/8440736/444060

**Comment by deniseschannon** [comment]
@Kajvdh If you have more questions, please re-open.
