### ISSUE TITLE
[BUG]Rancher Azure AD Access Token login issue

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#47672]
Rancher Server Setup

Rancher version: v2.9.2
Installation option (Docker install/Helm Chart): helm chart
If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): eks
Proxy/Cert Details:
Information about the Cluster

Kubernetes version: 1.29
Cluster Type (Local/Downstream):
If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):
AWS
User Information

What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
If custom, define the set of permissions: admin
Describe the bug
The Azure AD access token creates a new entry in the secret stored in the cattle-global-data namespace for each user that logs in. This eventually exceeds the Kubernetes secret size limit, resulting in a malformed access token mapping list and preventing new users from logging in.

To Reproduce

Install a Kubernetes cluster with version 1.29 and deploy Rancher version v2.9.2 using the Helm chart.
Create Azure AD groups for each team/project.
Create separate projects for different application team namespaces and map the respective Azure AD group to each project.
As users log in, monitor the Azure AD access token secret growth in the cattle-global-data namespace.
Result
When users from the app teams log in, they are able to see the namespaces they have access to, as we have mapped their Azure AD group to specific projects. However, with each login, the azuread-access-token secret in the cattle-global-data namespace continues to grow. Over time, this causes the secret to exceed the Kubernetes secret size limit, and new users are unable to log in, receiving the following error message:
"An error occurred logging in: Server error while authenticating."

Command to check the size of the secret:

kubectl get secret azuread-access-token -n cattle-global-data -o json --context ek8s-prd-west-admin | jq '.data' | wc -c

Example result:
3048576

The Kubernetes secret size limit is 1MB (1048576 bytes), and once exceeded, it results in login failures.

Expected Result
Even as more users log in, the secret should not grow indefinitely, and Rancher should handle Azure AD access token mappings in a way that does not cause login issues due to the secret size limit.

Screenshots
Screenshot 2024-10-15 at 7 03 49 PM

**Comment by bigkevmcd** [comment]
## Validation Template

## What was fixed, or what change has occurred

User tokens are no longer cached in the Secret used as a token-cache for access to Azure.

However, a "service account" token is still stored in the cattle-global-data/azuread-access-token Secret

## Areas or cases that should be tested

Logging in via Azure.

If you login with this fix with two different users, the number of users stored in the `access-token` field should not increase.

## What areas could experience regressions

Logging in via Azure

This only impacts the "Login" mechanism which was previously storing extra tokens which caused it to get too big and overflow the Secret size.

## Are the repro steps accurate/minimal?

Yes

**Comment by joesims22** [comment]
Validated on v2.10-head id `fcb4b0e`. 

| \#  | Priority | Description & Link                                        | PASS/FAIL |
| --- | -------- | --------------------------------------------------------- | --------- |
| 1   | P0       | Verify azure-read-access secret size is not growing as users login                        | ✅ PASS    |
| 2   | P1       | Verify Azure AD auth secrets deleted upon disabling Azure AD auth provider                        | ✅ PASS    |
| 3   | P1      | Verify  azure-read-access secret size doesn't grow after a large amount of users login                                 | ✅ PASS    |
| 4   | P0       | Verify azure-read-access secret is not growing upon upgrading Rancher                        | ✅ PASS    |
