### ISSUE TITLE
[rancher-compose] Add in commands to be able to cancel an upgrade 

### ISSUE THREAD

**Issue by artburkart** [rancher/rancher#4768]
**Rancher Version:** rancher-compose version v0.7.3-rc2

**Docker Version:** Docker version 1.10.3, build 20f81dd

**OS and where are the hosts located? (cloud, bare metal, etc):** AWS EC2 Ubuntu instances

**Setup Details: (single node vs. single node, internal DB vs. external DB)**
Create a service that cannot successfully start (i.e., make the app code depend on a config that doesn't exist).

``` docker-compose.yml
web:
  labels:
    io.rancher.container.network: 'true'
    io.rancher.container.hostname_override: container_name
  image: app-name-image
lb:
  ports:
  - 81:8888
  - 444:8888
  labels:
    io.rancher.loadbalancer.ssl.ports:444: ''
  image: rancher/load-balancer-service
  links:
  - web:web
```

``` rancher-compose.yml
web:
  scale: 3
lb:
  scale: 1
  load_balancer_config:
    haproxy_config: {}
  default_cert: example.com
  health_check:
    port: 42
    interval: 2000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 2000
    healthy_threshold: 2
```

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

*_Steps to Reproduce: *_

``` bash
# Try upgrading with a revision of the app that does not work
rancher-compose -f docker-compose.yml -p app-name up --upgrade -d
```

The application gets stuck in an "Upgrading (In Progress)" state.
![image](https://cloud.githubusercontent.com/assets/463528/15190522/4cf5126a-177e-11e6-9d3d-7e338e9d6386.png)

If we try rectifying this by upgrading with code that works, we receive the following error:

``` bash
WARN[0000] A newer version of rancher-compose is available: 0.7.4
INFO[0000] Project [app-name]: Starting project
INFO[0000] [0/2] [web]: Starting
ERRO[0000] Failed Starting web : Service web must be state=active or inactive to upgrade, currently: state=activating
INFO[0000] [0/2] [lb]: Starting
INFO[0000] [1/2] [lb]: Started
ERRO[0000] Failed to start: web : Service web must be state=active or inactive to upgrade, currently: state=activating
FATA[0000] Service web must be state=active or inactive to upgrade, currently: state=activating
```

**Results:** 

The upgrade fails because Rancher is still trying to perform the previous upgrade, which never succeeded because the container keeps restarting. The only workaround that we've found is completely deleting the stack and starting over.

This leads me to a couple questions:
1. Are we supposed to be able to cancel an upgrade from `rancher-compose`?
2. If not, then are we required to use blue-green deployments in order to do upgrades (just prevent Rancher from ever getting into this infinite looping upgrade state)?

**Expected:**

We should be able to cancel an upgrade with `rancher-compose`

**Comment by artburkart** [comment]
I just chatted with @vincent99 on IRC and was informed the cancellation functionality does not currently exist in `rancher-compose`. It sounds like the current solution to this problem is to make a call to the API using the cancelupgrade endpoint.

**Comment by ebr** [comment]
+1

**Comment by ozbillwang** [comment]
Will we have any progress on this feature?

**Comment by mhobotpplnet** [comment]
This also causes all sorts of builds to fail if one of the stacks is stuck in the upgrade process.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
