### ISSUE TITLE
[2.9]Rancher Azure AD Access Token login issue 

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#47688]
backport #47672

**Comment by joesims22** [comment]
Validated on v2.9-head id `c1a3cd5`.

| \#  | Priority | Description & Link                                        | PASS/FAIL |
| --- | -------- | --------------------------------------------------------- | --------- |
| 1   | P0       | Verify azure-read-access secret size is not growing as users login                        | ✅ PASS    |
| 2   | P1       | Verify Azure AD auth secrets deleted upon disabling Azure AD auth provider                        | ✅ PASS    |
| 3   | P1      | Verify  azure-read-access secret size doesn't grow after a large amount of users login                                 | ✅ PASS    |
| 4   | P0       | Verify azure-read-access secret is not growing upon upgrading Rancher                        | ✅ PASS    |
