### ISSUE TITLE
[2.10] Enable metrics in nginx template, bump nginx to 1.11.3

### ISSUE THREAD

**Issue by chiukapoor** [rancher/rancher#47681]
The default behavior of the controller was recently changed to keep metrics disabled by default [[PR 12095](https://github.com/kubernetes/ingress-nginx/pull/12095)]. We need to add a Rancher-specific change, `- --enable-metrics=true`, in the NGINX template for metrics to be enabled by default.
Also, bump ingress-nginx to 1.11.3

**Comment by vivek-shilimkar** [comment]
Tested on rancher v2.10.0-alpha9 and k8s version v1.31.2. 

`nginx-1.11.3-rancher1` image has container argument `--enable-metrics=true` set. Hence issue can be closed.

**Comment by rishabhmsra** [comment]
Validated on rancher v2.10-1c2de6a7653883093c7b5703cb3d3c19bac4e2e7-head

- Provisioned k8s clusters - v1.30.6-rancher1-1, v1.29.10-rancher1-1 and v1.28.15-rancher1-1 
- Validated nginx-ingress-controller has `--enable-metrics=true` container args set.
