### ISSUE TITLE
Missing English Language

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#4769]
- [x] Add Service Alias in dropdown
- [x] Add External Service in dropdown

**Comment by tfiduccia** [comment]
Translations not found in Dev tool:
- [ ] Main Stack page - translation not found: locale='en-us', key='stackSection.add.toggle'.

**Comment by sangeethah** [comment]
Missing Translation in VM console View:

<img width="982" alt="screen shot 2016-05-12 at 5 46 56 pm" src="https://cloud.githubusercontent.com/assets/4266958/15234737/9ec5afd2-1869-11e6-9300-cb328a447148.png">

**Comment by sangeethah** [comment]
Missing Translation in the landing page  when stack is created with docker-compse.yml
<img width="1028" alt="screen shot 2016-05-13 at 9 19 07 am" src="https://cloud.githubusercontent.com/assets/4266958/15254507/028338be-18ec-11e6-897f-35f659be97cb.png">

**Comment by tfiduccia** [comment]
Version - master 5/15
Verified fixed
