### ISSUE TITLE
[v2.9] Enable metrics in nginx template,  bump nginx to 1.11.3

### ISSUE THREAD

**Issue by chiukapoor** [rancher/rancher#47709]
- backport: https://github.com/rancher/rancher/issues/47681

**Comment by rishabhmsra** [comment]
Validated on rancher v2.9-023781e52103c45a9bbdf3cb47d60b9336321daa-head :

- Provisioned v1.30.6-rancher1-1, v1.29.10-rancher1-1, 1.28.15-rancher1-1
- nginx-1.11.3-rancher1 image has container argument `--enable-metrics=true` set.
