### ISSUE TITLE
[BUG] Endpoint /v3/principal returns 500 when the principal can't be found

### ISSUE THREAD

**Issue by pmatseykanets** [rancher/rancher#47702]
**Rancher Server Setup**
- Rancher version:
- Installation option (Docker install/Helm Chart): N/A
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version:
- Cluster Type (Local/Downstream): Local

**User Information**
- What is the role of the user logged in? N/A

**Describe the bug**

The endpoint returns `500 ServerError` when the principal can't be found.

**To Reproduce**

```
curl -H "Authorization: Bearer $RANCHER_TOKEN" https://<rancher-url>/v3/principal/local:%2F%2Ffoo
```

**Result**

```
{
  "baseType": "error",
  "code": "ServerError",
  "message": "users.management.cattle.io \"foo\" not found",
  "status": 500,
  "type": "error"
}
```

**Expected Result**

The endpoint should return 404 Not Found instead
```
{
  "baseType": "error",
  "code": "NotFound",
  "message": "users.management.cattle.io \"foo\" not found",
  "status": 404,
  "type": "error"
}
```

**Screenshots**

**Additional context**

**Comment by Priyashetty17** [comment]
Recreated the issue with **v2.9.3**. Validated the fix with **v2.10-fcb4b0e12dd94e908dcc39c4f941a660f22e5d51-head**.
