### ISSUE TITLE
[Backport v2.9 - Windows] System Agent and rke2 startup may conflict with one another

### ISSUE THREAD

**Issue by HarrisonWAffel** [rancher/rancher#47719]
This is a backport issue of https://github.com/rancher/rancher/issues/46344. The primary change which addresses this issue was done in the `system-agent-installer-rke2`, which will be pulled by both 2.9 and 2.10.

**Comment by HarrisonWAffel** [comment]
Ready for testing as the rancher/rancher PR has been merged. the KDM data included in this PR should be used for testing https://github.com/rancher/kontainer-driver-metadata/pull/1543

URL: https://raw.githubusercontent.com/rafaelbreno/kontainer-driver-metadata/refs/heads/october_rke2_9_patch/data/data.json

**Comment by markusewalker** [comment]
Validated this against `v2.9` https://github.com/rancher/rancher/commit/c1a3cd5fd6d60f2851739d26af862592497ccdbb. Details have been recorded in Qase test run /RM 2661.

**ENVIRONMENT DETAILS**
- Rancher install: Helm
- Rancher version: `v2.9` https://github.com/rancher/rancher/commit/c1a3cd5fd6d60f2851739d26af862592497ccdbb

**TEST RESULTS**
|#|Scenario|Result|
|---|---|---|
|1|Validate rancher-wins and sc.exe output shows no errors on highest K8s version|:white_check_mark:|
|2|Validate rancher-wins and sc.exe output shows no errors on upgraded K8s version|:white_check_mark:|
|3|Validate rancher-wins and sc.exe output shows no errors on upgraded Rancher|:white_check_mark:|
