### ISSUE TITLE
[v2.8] Enable metrics in nginx template, bump nginx to 1.11.3

### ISSUE THREAD

**Issue by chiukapoor** [rancher/rancher#47710]
- backport: https://github.com/rancher/rancher/issues/47681

**Comment by vivek-shilimkar** [comment]
Tested on rancher v2.8.10-alpha1 and k8s version v1.28.15. 

`nginx-1.11.3-rancher1` image has container argument `--enable-metrics=true` set. Hence issue can be closed.
