### ISSUE TITLE
[Backport v2.9] Windows system-agent-install script needlessly reinstalls RKE2 

### ISSUE THREAD

**Issue by HarrisonWAffel** [rancher/rancher#47718]
This is a backport issue of https://github.com/rancher/rancher/issues/45385. The primary change which addresses this issue was done in the `system-agent-installer-rke2`, which will be pulled by both 2.9 and 2.10.

**Comment by markusewalker** [comment]
Validated this against `v2.9-head` https://github.com/rancher/rancher/commit/c1a3cd5fd6d60f2851739d26af862592497ccdbb. Results and more details have been recorded in Qase test run /RM 2664.

**ENVIRONMENT DETAILS**
- Rancher install: Helm
- Rancher version: `v2.9-head` https://github.com/rancher/rancher/commit/c1a3cd5fd6d60f2851739d26af862592497ccdbb

**TEST RESULTS**
|#|Scenario|Result|
|---|---|---|
|1|Validate rancher-wins output shows RKE2 service doesn't restart when cluster does not upgrade or have any configuration changes|:white_check_mark:|
|2|Validate rancher-wins output shows RKE2 service does reinstall when the cluster does upgrade|:white_check_mark:|
|3|Validate rancher-wins output shows RKE2 service does reinstall when the cluster configuration is updated|:white_check_mark:|
|4|Validate rancher-wins output shows RKE2 service does reinstall when the Rancher is upgraded|:white_check_mark:|
