### ISSUE TITLE
[BUG] Unable to upgrade or update cluster using RKE 1 templates

### ISSUE THREAD

**Issue by jnath-nsf** [rancher/rancher#47711]
**Rancher Server Setup**
- Rancher version: 2.9.2
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1-1.29.8
- Proxy/Cert Details: Certificate being managed by Lets Encrypt, no proxy server setup

**Information about the Cluster**
- Kubernetes version: 1.29.9
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster?:  Custom

**User Information**
- What is the role of the user logged in? : Admin
  - If custom, define the set of permissions: NA

**Describe the bug**

We upgrade our RKE 1 downstream clusters using RKE templates . Everytime we perform an upgrade, we first create a new revision and then we edit the downstream cluster config and pick the latest version. With version 2.9.2 when we pick the latest revision of the RKE template, we can no longer see the Cluster Options panel as it automatically hides and we cannot make or see any options nor can we see the save button.
**To Reproduce**

1. Go to Cluster Manager -> RKE 1 Configuration -> RKE Templates
2. Pick the last  revision and then create a new revision clone.
3. Select the new Kubernetes Version
4. Save the template.
5. Go to Cluster Manager and click the options menu for the cluster for which the kubernetes version needs to be upgraded and click Edit Config.
6. Pick the latest revision of RKE template.
**Result**
Cluster Options is hidden or blank and there is no save button. 
**Expected Result**

I should be able to see the Cluster Options and Click on save.
**Screenshots**

![screen-1](https://github.com/user-attachments/assets/0c16a39c-5c34-4cf6-a45b-fc2a5a76b408)
![screen-2](https://github.com/user-attachments/assets/17515e33-d102-4ffd-b84c-769b63cc1cf4)
![screen-3](https://github.com/user-attachments/assets/a3c741bd-b4e1-400d-8eba-d38aefcf569f)

**Additional context**

We have a urgent cluster upgrade operation we are unable to perform

**Comment by zh-zywave** [comment]
This is a real problem and needs to get fixed. We have the same issue.

**Comment by gaktive** [comment]
@torchiaf let me know if you've had a chance to repro this and if this points to UI, I'll transfer this to rancher/dashboard

**Comment by zh-zywave** [comment]
I have done some testing on my end and confirmed this bug is in all Rancher 2.9 releases through 2.9.4.

**Comment by gaktive** [comment]
As noted, this is fixed in 2.10.0.
