### ISSUE TITLE
Anti-affinity to a service name is not respected due to case sensitivity 

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#4775]
Since the UI will no longer be lower casing all labels, we need to verify that the scheduling rules will still work as expected with different variations of cases.

**Comment by soumyalj** [comment]
It fails for one case:
1. Create a service "test1" with one container with scheduling rule:
```
Host must not have a service name "TEST1" [It must be caps]
```
2. Increase the scale

All the containers get created on the same host

**Comment by soumyalj** [comment]
Tested with v1.1.0-dev5-rc1 with the scheduling rule mentioned above. After the scale is increased, the container starts on a different host.
