### ISSUE TITLE
Upgrade Go version to 1.23.2+

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#47760]
- [ ] pushprox-client
- [ ] pushprox-proxy

Edit: Removed all `mirrored-` images as we cannot update Go for those w/o rebuilding them.

**Comment by mallardduck** [comment]
@MKlimuszka - We cannot update Go for anything with `mirroed-` prefix. We can only update the image tag we use from upstream and hop they updated Go.

**Comment by mallardduck** [comment]
PR created for this last week here: https://github.com/rancher/PushProx/pull/26

**Comment by pankajsqe** [comment]
It has been tested successfully via rancher/pushprox with image tag  v0.1.4-rc.2-rancher2 successfully.

Details
Rancher : v2.10-head
Monitoring : 105.1.0+up61.3.2
![Image](https://github.com/user-attachments/assets/69f73e9a-e386-432d-82bd-75ee440dc5ce)
![Image](https://github.com/user-attachments/assets/1469ba89-f6dc-4661-9e2c-cbf54e0dc874)
