### ISSUE TITLE
Rebase pushprox to catch up with upstream 2.0

### ISSUE THREAD

**Issue by mallardduck** [rancher/rancher#47766]
Per title, the upstream PushProx is now at [2.0](https://github.com/prometheus-community/PushProx/releases/tag/v0.2.0).
Lets update our version and changes to incorporate the 2.0 changes.

https://github.com/rancher/PushProx

The main reason to do this is to keep any future rebases easier if we desire to keep things matching upstream. While upstream opted to make the bump to 2.0 I don't believe this is necessary or would be reflective of our fork due to our diverging changes.

The most significant change with this rebase is: "Upstream prometheus project removed custom `promslog` for logging and replaced with slog". So effectively this rebase cleans up tech-debt.

**Comment by mallardduck** [comment]
Fixed by: https://github.com/rancher/PushProx/pull/27

**Comment by mallardduck** [comment]
The rancher/charts PR is here: https://github.com/rancher/charts/pull/4783
Can be tested via the branch the PR is based on - or after merge.

**Comment by pankajsqe** [comment]
Pushprox `v0.1.4-rc.4-rancher2` has been verified along with monitoring chart `105.1.1-rc.1+up61.3.2`

**Details**
rancher : 2.10-head
Monitoring chart : 105.1.1-rc.1+up61.3.2
Pushprox : v0.1.4-rc.4-rancher2


![Image](https://github.com/user-attachments/assets/8ec9c937-7486-467f-bd8b-2283e5ce7c7f)
![Image](https://github.com/user-attachments/assets/147669fb-689c-4803-97b4-340607ed0407)
