### ISSUE TITLE
[BUG] Failed bootstrapping cluster with provisioningprebootstrap and ACE enabled

### ISSUE THREAD

**Issue by edwin-bruurs** [rancher/rancher#47771]
**Rancher Server Setup**
- Rancher version: 2.9.3
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version: RKE2 (v1.30.5+rke2r1)

**Information about the Cluster**
- Kubernetes version: v1.30.5+rke2r1
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? vSphere

**User Information**
- What is the role of the user logged in? Admin
  - If custom, define the set of permissions:

**Describe the bug**
Cluster stucks in Pending state when `provisioningprebootstrap` is enabled. 

**To Reproduce**
Create a cluster using vSphere provider and rancher-vsphere cloud-provider. Use Cilium with `kubeProxyReplacement` set to true (and k8sServiceHost pointing to 127.0.0.1). 
Depending on the Authorized Endpoint enabled kube-api won't start

**Result**
When Authorized Endpoint is enabled, kube-api reports it can't find the file `/var/lib/rancher/rke2/kube-api-authn-webhook.yaml`. Verifying on the host I can conform this file is not there. Creating the file manually will continue booting the cluster, but eventually the cluster still gets stuck with pending pods resultin in the cluster 'Waiting for cluster pre-bootstrap to complete'.

Looking to the pods available it stats the following;
![image](https://github.com/user-attachments/assets/a8a2ad7a-63bd-4934-a71b-9ac5e15025c5)

Inspecting the logs from some pods all report more or less the same error;
![image](https://github.com/user-attachments/assets/cb57bbb0-3ed1-4fae-8a3c-5a1658e5f790)

So my best guess is that this is caused by some combination using Cilium with kubeProxyReplacement enabled and the provisioningprebootstrap. Disabling the provisiongprebootstrap results in the cluster being provisioned without any problems.

**Expected Result**
The newly created cluster is provisioned.

SURE-9298

**Comment by susesgartner** [comment]
Ticket #47771 - Test Results - ✅
---

| Scenario | Test Case | Result |
|---|---|---|
| 1. | ACE test | PASS |
| 2. | cilium kube-proxy-replacement test | PASS |
| 3. | custom calico test | PASS |


Pre-requisite steps:
1. Enable the prebootstrap feature flag


---
Verified with (HA Helm or Docker) on Rancher `v2.10-212d8b6e92992235d791d8f2aaea8436ab4f6b77-head`:
---
 
Scenario 1: ACE test
---

Permutations: 
- Cluster type: RKE1/RKE2/K3s
- Calico/Cilium

1. Provision and a 3 node split roles cluster and ACE enabled
2. Wait for the cluster to come up
3. Verify that the cluster is in a stable state and all pods are active
 
Results: The cluster came up and all pods are in a stable state
 
---
 
Scenario 2: Cilium kube-proxy-replacement test
---
1. Provision an 3 node all roles RKE2 cluster with Cilium and kube-proxy-replacement enabled
2. Verify that the cluster comes up
3. Verify that all pods are in a stable state
 
Results: the cluster came up and all pods were in a stable state.


---

Scenario 3: Customized calico test
---
1. Provision a 3 node all roles RKE2 cluster with an altered Calico add-on config
2. Verify that the cluster comes up 
3. Verify that all pods are in a stable state
 
Results: the cluster came up and all pods were in a stable state.
