### ISSUE TITLE
[BUG] Failed to install system chart rancher-webhook: no chart version found for rancher-webhook-2.0.12+up0.3.12-rc1

### ISSUE THREAD

**Issue by kravciak** [rancher/rancher#47772]
Rancher-webhook is not created on 2.7.16 prime because it references -rc1 chart that does not exist.

**Rancher Server Setup**
- Rancher version: 2.7.16

**Information about the Cluster**
- Kubernetes version: k3d v1.27.16+k3s1

**Logs**
```
~ k get pods -n cattle-system
helm-operation ...
rancher-76946b59fd-m9l5r   1/1     Running

~ k logs -n cattle-system rancher-76946b59fd-m9l5r
[ERROR] Failed to install system chart rancher-webhook: no chart version found for rancher-webhook-2.0.12+up0.3.12-rc1
...
```

**Comment by prachidamle** [comment]
This was fixed with rancher v2.7.17 release
