### ISSUE TITLE
Cannot pull images on Client server. Docker private registry installed on RHEL 7 with selfsigned certificate.

### ISSUE THREAD

**Issue by Bart187** [rancher/rancher#4778]
Hi All,

I wanted to setup Docker private registry with self sign certificate (after that I wanted to add LDAP authorisation to it), but I'm stuck in the first very seems easy problem - I could not pull images with client from registry server. This is what I have done till now:

On Server:
1. Installed Docker with yum (https://docs.docker.com/engine/installation/linux/rhel/)
2. Generated Certificate:
```
mkdir -p /certs && openssl req 
-newkey rsa:4096 -nodes -sha256 -keyout /certs/domain.key 
-x509 -days 365 -out /certs/domain.crt
```
3. Copied cert and updated the ca-trust:
```
cp /certs/domain.crt /etc/pki/ca-trust/source/anchors/myregistrydomain.local.crt
update-ca-trust
```
4. Restarted Docker and installed Docker Registry
`docker run -d -p 5000:5000 --restart=always --name Test_three -v /certs:/certs -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt   -e REGISTRY_HTTP_TLS_KEY=/certs/domain.key registry:2`
5. Then pull/tag/push:
```
docker pull ubuntu
docker tag ubuntu myregistrydomain.local:5000/ubuntu
docker push myregistrydomain.local:5000/ubuntu
```
-> ALL OK till now

On Client:
And when I wanted to pull that image from registry server to client I got:
```
[root@client]# docker pull myregistrydomain.local:5000/ubuntu
Using default tag: latest
Error response from daemon: Get https://myregistrydomain.local:5000/v1/_ping: x509: certificate signed by unknown authority
```

When I wanted to check the problem with curl:

```
[root@client]# curl --verbose https://myregistrydomain.local:5000/v1/_ping
* About to connect() to myregistrydomain.local port 5000 (#0)
*   Trying 10.*.*.11...
* Connected to myregistrydomain.local (10.*.*.11) port 5000 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* Server certificate:
*       subject: E=****************@***********.com,CN=myregistrydomain.local,OU=Web Administration,O=*****,L=*****,C=FI
*       start date: May 11 09:53:21 2016 GMT
*       expire date: May 11 09:53:21 2017 GMT
*       common name: myregistrydomain.local
*       issuer: E=**************@********.com,CN=myregistrydomain.local,OU=Web Administration,O=******,L=***********,C=FI
* NSS error -8172 (SEC_ERROR_UNTRUSTED_ISSUER)
* Peer's certificate issuer has been marked as not trusted by the user.
* Closing connection 0
curl: (60) Peer's certificate issuer has been marked as not trusted by the user.
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```

It seems a really easy problem, but I don't know how to sort it out with the self sign certificate. Should I request for real public suffix domain and get it signed via letsencrypt or maybe there is a really quick troubleshooting for that? Some like root ca coping to client server?

**Rancher Version:**
Linux 3.10.0-327.13.1.el7.x86_64 #1 SMP x86_64 x86_64 x86_64 GNU/Linux

**Docker Version:**
```
docker version
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:42 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:42 2016
 OS/Arch:      linux/amd64
```

**Expected:**
Docker client could pull images from the private repository without certificate error.

**Comment by deniseschannon** [comment]
This seems more like a Docker issue than a Rancher issue. 

Once you get the registry sorted out on the Docker side, here are the Rancher notes on how to incorporate using it into Rancher. 

http://docs.rancher.com/rancher/latest/en/configuration/registries/#self-signed-certificates

**Comment by Bart187** [comment]
Hi,

I have fix the issue. I had to copy the crt file from private registry server to client server to path:

`/etc/pki/ca-trust/source/anchors/myregistrydomain.local.crt`

after that I have executed the command:

`update-ca-trust`

Docker restart could be required, but after that all started to work without any issues :)
