### ISSUE TITLE
[BUG] Partial matching fails for substrings beyond the first in display names

### ISSUE THREAD

**Issue by Priyashetty17** [rancher/rancher#47802]
**Rancher Server Setup**
- Rancher version: `v2.10-6e85a811efd6b831c3d49a7336a6d4b3e96c1a93-head`
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1

**Information about the Cluster**
- Kubernetes version: v1.31.2
- Cluster Type (Local/Downstream): Local

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Admin

**Describe the bug**
This issue was observed while testing https://github.com/rancher/rancher/issues/47465
Partial matching only works for the first substring in the display name but fails for subsequent substrings

**To Reproduce**
1. Create Two Users:
    -  Alice Johnson (username: jalice)
    -  Alicia Johns (username: jalicia)
2. Navigate to Projects/Namespaces -> Create Project -> Add.
3. Search for users using:
    -  "john"
    -  "ali"

**Result**
- Searching for "john" returns no results.
- Searching for "johns" only returns "Alicia Johns", missing "Alice Johnson"

**Expected Result**
- Both "Alice Johnson" and "Alicia Johns" should appear in the search results since both contain the substring "john"

Note:
- Searching for "ali" (first substring) works correctly and returns both "Alice Johnson" and "Alicia Johns"
- Searching for "jal" (username) works correctly and returns both "Alice Johnson" and "Alicia Johns"
- This issue with searching for subsequent substrings is also observed with non-ASCII Latin characters.

**Screenshots**
Search for "john" - No Results:
![image](https://github.com/user-attachments/assets/b58d4d47-edaa-4813-aff0-45e4ac6bd0d3)

Search for "johns" - only "Alicia Johns" is returned:
![image](https://github.com/user-attachments/assets/99bc1f62-72e7-484e-9b3e-7dd8e8628111)

Search for "ali" - both "Alice Johnson" and "Alicia Johns" are returned:
![image](https://github.com/user-attachments/assets/c250c264-508a-4d9c-9384-3ce0f57f9c22)

**Comment by samjustus** [comment]
after kevin's analysis here: https://github.com/rancher/rancher/issues/47465#issuecomment-2449893991

we determined that the functionality delivered was sufficient and the juice of this issue isn't  worth the squeeze
