### ISSUE TITLE
io.rancher.scheduler.global: true not working like it should be.

### ISSUE THREAD

**Issue by jwhitcraft** [rancher/rancher#4780]
**Rancher Version:** 0.63.1
**Docker Version:** 1.10.3
**OS and where are the hosts located? (cloud, bare metal, etc):** Ubuntu 14.04/AWS
**Setup Details: (single node vs. single node, internal DB vs. external DB)** Single Node
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle
**Steps to Reproduce:**
- Create one Host in an environment and add a service with a label of `labels: io.rancher.scheduler.global: 'true'`
- Once the servcie has started
- Spin up another host.

**Results:** 
- The service doesn't spin up on the new host

**Expected:**
- It should spin up on the new host.

**Notes:**
This is happening with the sysdig-cloud template and a few of my custom services.

**Comment by alena1108** [comment]
@jwhitcraft this issue was fixed in 1.0.1:
https://github.com/rancher/rancher/issues/3480

**Comment by jwhitcraft** [comment]
@alena1108,

Thanks for the response.  I'm unable to upgrade becuase of #4737.
