### ISSUE TITLE
[BUG] `provisioningprebootstrap` flag does not restart rancher when toggled

### ISSUE THREAD

**Issue by thatmidwesterncoder** [rancher/rancher#47814]
**Rancher Server Setup**
- Rancher version: head, 2.9.3
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: n/a
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:
admin

**Describe the bug**

When enabling the new `provisioningprebootstrap` flag all existing clusters go into `Upgrading` with status `Waiting for pre-bootstrap to complete`. Restarting rancher fixes this - so the feature flag should be made non-dynamic (to restart rancher when its value is changed.

**To Reproduce**

Create a cluster, let it become active, then activate the `provisioningprebootstrap` flag. 

**Result**

A cluster stuck in `Upgrading` until rancher is restarted.

**Expected Result**

The cluster reconciles and goes back to `Active`.

**Screenshots**

**Additional context**

**Comment by susesgartner** [comment]
Ticket #47814 - Test Results - ✅ 
---
 
| Scenario | Test Case | Result |
|---|---|---|
| 1. | Enable pre-bootstrap feature flag | PASS |
| 2. | Disable pre-bootstrap feature flag | PASS |
---
Verified with (HA Helm or Docker) on Rancher `v2.10-head`:
---
 
Scenario 1: Enable pre-bootstrap feature flag
---
1. Enable the prebootstrap feature flag
2. Wait for the rancher restart pop up to close
3. Confirm that the restart has occurred and pre-bootstrapping is enabled
 
Results: Restart occurs and pre-bootstrapping is enabled

 
---
 
Scenario 2: Disable pre-bootstrap feature flag
---
1. Disable the prebootstrap feature flag
2. Wait for the rancher restart pop up to close
3. Confirm that the restart has occurred and pre-bootstrapping is disabled
 
Results: Restart occurs and pre-bootstrapping is disabled
