### ISSUE TITLE
[Backport v2.8] [BUG] Failed bootstrapping cluster with provisioningprebootstrap and ACE enabled

### ISSUE THREAD

**Issue by thatmidwesterncoder** [rancher/rancher#47810]
This is a backport of #47771 to the 2.8 branch

SURE-9298

**Comment by susesgartner** [comment]
Ticket #47810 - Test Results - ✅
---

| Scenario | Test Case | Result |
|---|---|---|
| 1. | ACE test | PASS |
| 2. | cilium kube-proxy-replacement test | PASS |
| 3. | custom calico test | PASS |


Pre-requisite steps:
1. Enable the prebootstrap feature flag


---
Verified with (HA Helm or Docker) on Rancher `v2.8-859c669b0a5751128281ab8b70278ec5f9420dc0-head`:
---
 
Scenario 1: ACE test
---

Permutations: 
- Cluster type: RKE1/RKE2/K3s
- Calico/Cilium

1. Provision and a 3 node split roles cluster and ACE enabled
2. Wait for the cluster to come up
3. Verify that the cluster is in a stable state and all pods are active
 
Results: The cluster came up and all pods are in a stable state
 
---
 
Scenario 2: Cilium kube-proxy-replacement test
---
1. Provision an 3 node all roles RKE2 cluster with Cilium and kube-proxy-replacement enabled
2. Verify that the cluster comes up
3. Verify that all pods are in a stable state
 
Results: the cluster came up and all pods were in a stable state.


---

Scenario 3: Customized calico test
---
1. Provision a 3 node all roles RKE2 cluster with an altered Calico add-on config
2. Verify that the cluster comes up 
3. Verify that all pods are in a stable state
 
Results: the cluster came up and all pods were in a stable state.
