### ISSUE TITLE
[Backport v2.9] [BUG] `provisioningprebootstrap` flag does not restart rancher when toggled

### ISSUE THREAD

**Issue by thatmidwesterncoder** [rancher/rancher#47815]
This is a backport of #47814 to the 2.9 release line

**Comment by susesgartner** [comment]
Ticket #47815 - Test Results - ✅ 
---
 
| Scenario | Test Case | Result |
|---|---|---|
| 1. | Enable pre-bootstrap feature flag | PASS |
| 2. | Disable pre-bootstrap feature flag | PASS |
---
Verified with (HA Helm or Docker) on Rancher `v2.9-1d1065cd5bf09c23834720420e1153712fa43439-head`:
---
 
Scenario 1: Enable pre-bootstrap feature flag
---
1. Enable the prebootstrap feature flag
2. Wait for the rancher restart pop up to close
3. Confirm that the restart has occurred and pre-bootstrapping is enabled
 
Results: Restart occurs and pre-bootstrapping is enabled

---
 
Scenario 2: Disable pre-bootstrap feature flag
---
1. Disable the prebootstrap feature flag
2. Wait for the rancher restart pop up to close
3. Confirm that the restart has occurred and pre-bootstrapping is disabled
 
Results: Restart occurs and pre-bootstrapping is disabled
