### ISSUE TITLE
EC2 host not completing agent registration through UI in HA environment

### ISSUE THREAD

**Issue by lekum** [rancher/rancher#4781]
**Rancher Version:** 1.0.1

**Docker Version:** 1.11.1

**OS and where are the hosts located? (cloud, bare metal, etc):**  RHEL 7.2 in AWS

**Setup Details: (single node vs. single node, internal DB vs. external DB)** Multinode, external DB (AWS Aurora), behind ELB, SSL terminated at Rancher Server

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:** 
Followed the [instructions](http://docs.rancher.com/rancher/latest/en/installing-rancher/installing-server/multi-nodes/) for HA. 

Manually edited the `rancher-ha.sh` script to use `http` instead of `https`. The registration URL is the internal ELB FQDN. Also this ELB is configured as described in #4738

Filled the _Add host -> Amazon EC2_ forms.

**Results:** 

The new machine's agent is stuck in _Waiting for agent connection..._ state:

![host](https://cloud.githubusercontent.com/assets/2630720/15222557/9656b236-1870-11e6-8f9a-e4ab0a9dda7b.png)

In addition, I cannot access the machine as the _Machine config_ dialog does not allow the download of the machine config files.

_Maybe_ the issue could be related with the fact that the procedure for adding new hosts to an HA environment implies the extra step of copying the `ca.crt` file to `/var/lib/rancher/etc/ssl` in the dockerhost.

**Expected:**

The host to be added.

**Comment by soumyalj** [comment]
@lekum, I just checked this with 1.0.2-dev2 to verify the fix for:
[AWS ELB + Rancher HA Returning HTTP instead of HTTPS #4697 ](https://github.com/rancher/rancher/issues/4697)

You might want to give that a go, or wait for 1.0.2 GA. I didnt have to bother manually adding the ca.crt file to my rancher server hosts. Adding the cert/key/intermediate certs via the UI, and using the provided rancher-ha.sh script took care of that step. I'll look to make suggested changes to the docs as things have changed a bit.

**Comment by lekum** [comment]
Hi,

I have tested with version 1.0.2 and I get stuck in the same _Waiting for agent connection.._ message. However, now I'm using this confitguration:

**Rancher Version:** 1.0.2

**Docker Version:** 1.11.1

**OS and where are the hosts located? (cloud, bare metal, etc):**  RHEL 7.2 in AWS

**Setup Details: (single node vs. single node, internal DB vs. external DB)** Multinode, external DB (AWS Aurora), behind ELB, SSL terminated at Rancher Server with self-signed auto-generated (by Rancher Sever) certificate

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:** 
Followed the [instructions](http://docs.rancher.com/rancher/latest/en/installing-rancher/installing-server/multi-nodes/) for HA. 

Created a self-signed certificate using rancher UI.

 The registration URL is the internal ELB FQDN SSL endpoint. Also this ELB is configured as described in #4738

Filled the _Add host -> Amazon EC2_ forms.

**Results:** 

The new machine's agent is stuck in _Waiting for agent connection..._ state:

![host](https://cloud.githubusercontent.com/assets/2630720/15222557/9656b236-1870-11e6-8f9a-e4ab0a9dda7b.png)

In addition, I cannot access the machine as the _Machine config_ dialog does not allow the download of the machine config files.

_Maybe_ the issue could be related with the fact that the certificate is self-signed (?)

**Expected:**

The host to be added.

**Comment by aemneina** [comment]
@lekum can you describe the network? For example, Is this host local to your rancher server, are they on the same VPC? Is there security group access between these machines on port 22?

**Comment by lekum** [comment]
They are in the same VPC. There are apparently no problems with the security groups because I can manually create a host with the same characteristics and add it via the "Add Host" UI menu and it works. In fact, the moment that the process gets stuck if after the docker-machine has entered the machine and provisioned it to run the rancher agent.

**Comment by lekum** [comment]
Hi,

I have found the `id_rsa` file inside the `/var/lib/docker/volumes/...` of one of the rancher servers, and entered the agent dockerhost from the rancher server.

The container had exited and `docker logs` of the container showed this message:

```
ERROR: https://OUR-ELB-URL.elb.amazonaws.com/v1 is not accessible
```

I have manually tried a curl of that URL from that same dockerhost and the curl fails because the SSL certificate is self-signed (it is the one auto-generated by Rancher). If I run the curl with the `-k` option, to ignore the insecure certificate, it works:

```
{"id":"v1","type":"apiVersion","links":...}
```

It seems that the `rancher-agent` can't work with a registration URL with SSL and a self-signed certificate.

**Comment by aemneina** [comment]
Right, it looks like a bug where the FINGERPRINT environmental password isn't added to the docker run command.

**Comment by aemneina** [comment]
Related:
#4404

**Comment by aemneina** [comment]
Verified this working with rancher/server:v1.1.0-dev5-rc5. Added, removed then added some more ubuntu ec2 hosts via the Rancher docker-machine functionality.
