### ISSUE TITLE
Setting scheduling policy to run all containers on a specific host is not reflected in docker-compose.yml

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#4782]
**Rancher Version:**V1.1.0-dev1

**OS and where are the hosts located? (cloud, bare metal, etc):**Ubuntu, Cloud

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**: Cattle

**Steps to Reproduce:**
1. Create a new service and set the scheduling policy to "Run all containers on a specfic host" 

**Results:** 
This setting is not reflected in docker-compose.yml or rancher-compose.yml

**Comment by vincent99** [comment]
https://github.com/rancher/rancher/issues/3323
