### ISSUE TITLE
 [Backport 2.9] VAI Cache DB Files Not Present in Pods/Breaks Rancher UI 

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#47844]
Backport of https://github.com/rancher/rancher/issues/47601

**Comment by MKlimuszka** [comment]
PR: https://github.com/rancher/steve/pull/312

**Comment by brudnak** [comment]
Can we move the issue status when PRs merge? @MKlimuszka @prachidamle @tomleb 🙏🙏🙏🙏🙏🙏 ...

**Comment by brudnak** [comment]
Issue still present on `v2.9-1d1065cd5bf09c23834720420e1153712fa43439-head`

**Comment by brudnak** [comment]
<details>
    <summary>🧪 Test Environment... CLICK TO EXPAND! ⬅️</summary>
<br>


| Component                        | Version / Type                                     |
| -------------------------------- | -------------------------------------------------- |
| Rancher version starting         | 2.9.2                                              |
| Rancher version upgraded         | v2.9-023781e52103c45a9bbdf3cb47d60b9336321daa-head |
| Installation option              | Helm (high availability)                           |
| RKE binary version used          | v1.6.2                                             |
| Downstream cluster type          | not applicable                                     |
| Downstream K8s version           | not applicable                                     |
| Authentication providers enabled | local                                              |
| Logged in user role              | admin                                              |

</details>

<a name="top"></a>

### 🧪 Test Cases

| \#  | Priority | Description & Link                                  | PASS/FAIL |
| --- | -------- | --------------------------------------------------- | --------- |
| 1   | P0       | [Fresh Install `ui-sql-cache` Enabled](#test-1)     | ✅ `PASS`  |
| 2   | P0       | [(Regression check) Validation Automation](#test-2) | ✅ `PASS`  |
| 3   | P0       | [ID Sort, Filter](#test-3)                          | ✅ `PASS`  |
| 4   | P0       | [Metadata Sort, Filter](#test-4)                    | ✅ `PASS`  |
| 5   | P0       | [Upgrade](#test-5)                                  | ✅ `PASS`  |
| 6   | P0       | [Transform](#test-6)                                | ✅ `PASS`  |



<details>
    <summary>🚨 6 test cases... CLICK TO EXPAND! (For table links to work) ⬅️</summary>
<br>

# 1 / Fresh Install `ui-sql-cache` Enabled Status: ✅ `PASS`

<a name="test-1"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 1 details... Click to expand</summary>

**Test Steps for Validation**

1. Enable vai
2. Navigate to local cluster >>> Workloads >>> Pods >>> All Namespaces
3. Ensure all pods are visible

**✅ Expected Outcome**

For all pods to be visible

**✅ Actual Outcome**

All pods were visible


</details>
<hr>

# 2 / (Regression check) Validation Automation Status: ✅ `PASS`

<a name="test-2"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 2 details... Click to expand</summary>

**Test Steps for Validation**

1. Enable vai
2. Run validation tests
3. All passing

**✅ Expected Outcome**

All tests to pass

**✅ Actual Outcome**

All tests were passing

</details>
<hr>

# 3 / ID Sort, Filter Status: ✅ `PASS`

<a name="test-3"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 3 details... Click to expand</summary>

**Test Steps for Validation**

1. Enable vai
2. Run: 

```sh
curl -s https://raw.githubusercontent.com/brudnak/rancher-test-scripts/refs/heads/main/2.10.0/46330/script.sh | bash -s rancher.url token123 local.yaml
```

```log
---

Test Summary:
Test Run ID: 6ka8jk
Namespace: synthetic-test-6ka8jk
Pod Names:
- test-pod-1-21itua
- test-pod-2-sxqxo6
- test-pod-3-o3dv4t

============== Test Summary ==============
Total tests run: 8
✅ Filter by ID Test
✅ Filter by Multiple IDs Test
✅ Filter Running Pods Test
✅ Filter by IDs AND State Test
✅ Sort Pods by ID Descending Test
✅ Sort Pods by State Test
✅ Limit Pods Test
✅ Combined Operations Test

Results:
Passed: 8
Failed: 0
Success rate: 100%
=========================================
Before cleanup, please verify the test results above.
All curl commands are provided for manual verification.
Do you want to cleanup the test resources? (y/n)
```

**✅ Expected Outcome**

All tests to pass

**✅ Actual Outcome**

All tests passing

</details>
<hr>

# 4 / Metadata Sort, Filter Status: ✅ `PASS`

<a name="test-4"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 4 details... Click to expand</summary>

**Test Steps for Validation**

1. Enable vai
2. Run: 

```sh
curl -s https://raw.githubusercontent.com/brudnak/rancher-test-scripts/refs/heads/main/2.10.0/46330/script.sh | bash -s rancher.url token123 local.yaml
```

```log
Test Summary:
Test Run ID: mj5s9c
Namespace: synthetic-test-mj5s9c
Pod Names:
- test-pod-1-4zmk67
- test-pod-2-sutc2u
- test-pod-3-4ojdoy

============== Test Summary ==============
Total tests run: 8
✅ Filter by ID Test
✅ Filter by Multiple IDs Test
✅ Filter Running Pods Test
✅ Filter by IDs AND State Test
✅ Sort Pods by ID Descending Test
✅ Sort Pods by State Test
✅ Limit Pods Test
✅ Combined Operations Test

Results:
Passed: 8
Failed: 0
Success rate: 100%
```

**✅ Expected Outcome**

All tests to pass

**✅ Actual Outcome**

All tests passing


</details>
<hr>

# 5 / Upgrade Status: ✅ `PASS`

<a name="test-5"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 5 details... Click to expand</summary>

**Test Steps for Validation**

1. Start Rancher from the previous released version
2. Upgrade to this version of Rancher
3. Repeat all test cases

**✅ Expected Outcome**

All test cases should pass on an upgraded Rancher setup

**✅ Actual Outcome**

All test cases passed on the upgraded Rancher


</details>
<hr>

# 6 / Transform Status: ✅ `PASS`

<a name="test-6"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 6 details... Click to expand</summary>

**Test Steps for Validation**

1. Enable vai
2. Run: 

```sh
curl -s https://raw.githubusercontent.com/brudnak/rancher-test-scripts/refs/heads/main/2.10.0/46330/transform.sh | bash -s rancher.url token123 local.yaml
```

```log
============== Test Summary ==============
Total tests run: 6
✅ Verify ID Transform
✅ Filter Multiple IDs
✅ Sort by Transformed ID Descending
✅ Sort by Transformed ID Ascending
✅ Basic Limit Test
✅ Sort and Limit Combined

Results:
Passed: 6
Failed: 0
Success rate: 100%
```

**✅ Expected Outcome**

Transform tests to pass

**✅ Actual Outcome**

Transform tests passing


</details>
<hr>

</details>
