### ISSUE TITLE
Volumes stuck in purging

### ISSUE THREAD

**Issue by jensendw** [rancher/rancher#4785]
**Rancher Version:**
v1.0.1

**Docker Version:**
1.10.3
**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 14.04 / cloud

**Setup Details: (single node vs. single node, internal DB vs. external DB)**
external DB, single node
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Create a storage volume, then try to delete via either API or GUI

**Results:** 
I know there are issues with deleting storage pool volumes from the GUI, in my case I have attempted to delete via the API, but I'm still seeing multiple volumes in a purging state.  These seems to be slowing down the main rancher server due to the sheer amount.  Is there a way I can either kill the tasks inside rancher or properly get the volume our of the purging state via the API? 

Here is a screenshot of my process list.

https://www.evernote.com/l/AQ9vWU-_ZjdFALPTT-xv2QhacH7rn0oOybI

**Comment by deniseschannon** [comment]
The deleting from storage pools API is still not completed yet. That is what this issue is for: https://github.com/rancher/rancher/issues/2918

There are some notes inside that issue from @cjellick on how to clean it up manually. Hope that will help.

**Comment by deniseschannon** [comment]
@jensendw Let me know if you have further questions, but the issue I referenced should help with your questions.
