### ISSUE TITLE
Provide info about the parameters in the health check and Stickiness tabs.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#479]
Server - Build from master

Provide info about the different parameters used in the health check and Stickiness tabs.

**Comment by vincent99** [comment]
Yes, I had to look up most of them.  Unfortunately the haproxy documentation is a [text file](http://www.haproxy.org/download/1.4/doc/configuration.txt) that can't be deep-linked into.

**Comment by vincent99** [comment]
https://cbonte.github.io/haproxy-dconv/configuration-1.6.html will work though

**Comment by deniseschannon** [comment]
http://docs.rancher.com/rancher/concepts/health-checks/#configuration
http://docs.rancher.com/rancher/rancher-ui/applications/stacks/adding-balancers/#stickiness-policy-for-load-balancers
