### ISSUE TITLE
[BUG] Remove mirrored-prometheus-windows-exporter from rancher-images.txt

### ISSUE THREAD

**Issue by jbiers** [rancher/rancher#47912]
**Describe the bug**
When using Rancher in an Air-Gapped environment users need to refer to files such as rancher-images.txt and rancher-windows-images.txt as a source for their images. Currently a windows version is being wrongly inserted into rancher-images.txt causing problems for costumers in a Linux setup.

**Additional context**
SURE-9252

**Comment by pankajsqe** [comment]
validation passed as mirrored-prometheus-windows-exporter image has been removed from rancher-images.txt and added to rancher-windows-images.txt


Details
Rancher : v2.10.1-alpha1
Cluster : RKE2

rancher-images.txt
![Image](https://github.com/user-attachments/assets/6db48d1b-430d-4166-be71-db468ff66814)
![Image](https://github.com/user-attachments/assets/d12bb529-92a5-412a-a565-cf2761804166)

rancher-windows-images.txt
![Image](https://github.com/user-attachments/assets/a09f3fad-d1c5-4317-a534-c4daa769a7b4)
