### ISSUE TITLE
Cannot remove account API keys

### ISSUE THREAD

**Issue by roflmao** [rancher/rancher#4793]
**Rancher Version:**
1.0.1

**Docker Version:**
1.10.2-0~trusty

**OS and where are the hosts located? (cloud, bare metal, etc):**
Bare metal, Ubuntu 14.04 LTS

**Setup Details: (single node vs. single node, internal DB vs. external DB)**
Single node, internal DB
Github auth

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Press API in menu, press advanced options to expand.
Locate a key, press deactivate

**Results:** 
```Deactivate Error
Not Found```

**Expected:**
Removal of API key

**Comment by vincent99** [comment]
This was fixed in v1.1.0-dev1; you can use the View in API action and delete from there for v1.0.x
