### ISSUE TITLE
Deactivating a host doesn't actually stop the host on AWS

### ISSUE THREAD

**Issue by luispabon** [rancher/rancher#4795]
**Rancher Version:**
Latest

**Docker Version:**
1.10

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 15.10, AWS EC2

**Setup Details: (single node vs. single node, internal DB vs. external DB)**
Single node

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
Go to infrastructure > select a host > deactivate

**Results:** 
Host is deactivated on the UI, however on AWS the host is still running and racking up bills

**Expected:**
Host is deactivated both from Rancher server's point of view AND stopped at the cloud provider

**Comment by LLParse** [comment]
Hi @luispabon, deactivating a host merely prevents Rancher scheduler from placing new containers on the host. It doesn't shutdown the host by design.

Once you've deactivated, in the same menu you will have an option to remove the host. Could you try that?

**Comment by deniseschannon** [comment]
The host would only be deleted if you had launched the host through the UI. 

As we had created the host using `docker-machine create`, when we delete the host, we use `docker-machine rm`.

**Comment by deniseschannon** [comment]
@luispabon Let me know if there are more questions as this is expected behavior.

**Comment by esazhin** [comment]
Would be nice to have an option of stopping and starting the host via rancher UI. Not deleting, but just stopping.
