### ISSUE TITLE
[BUG] Clean Uninstall

### ISSUE THREAD

**Issue by manju-rn** [rancher/rancher#47974]
Setup: Rancher running on a docker and connecting to external cluster
Problems:  When an external cluster is imported in rancher, the external cluster (that is imported ) has are various components like agent which provide the real time updates to the rancher. This includes Roles, RoleBinding, ClusterRoles and ClusterRoleBindings that are installed in the external cluster. This is fine since I assume Rancher would need all these details.
However, when the rancher is uninstall in the external clusters, "EVERYTHING" must be removed. I see that lotts of Roles, RoleBinding, ClusterRoles and ClusterRoleBindings, validatingWebhookConfiguration, mutatingWenhookConfiguration are still in the external cluster.  This is undesirable and has a lack of trust on Rancher,  Why can't rancher provide a script to "clean up"  what is installed?

**Comment by skanakal** [comment]
@manju-rn check this out https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/manage-clusters/clean-cluster-nodes?k8s-distro=RKE1#removing-rancher-components-from-a-cluster-manually
and https://github.com/rancher/rancher/blob/main/cleanup/user-cluster.yml

**Comment by manju-rn** [comment]
Thanks, this works. 
However, I think Rancher also install validating and /mutating webhooks? Since this script does not delete them if it does
