### ISSUE TITLE
[Backport 2.10] Chart rancher-provisioning-capi doesn't add tolerations from chart values to post-install hook Job

### ISSUE THREAD

**Issue by Sahota1225** [rancher/rancher#48005]
Backport https://github.com/rancher/rancher/issues/47794

**Comment by Josh-Diamond** [comment]
Ticket #48005 - Test Results - ✅ 
---

Verified on Rancher `v2.10-58e887a871d1377399ff18a4ee95335981f08991-head`:

| Scenario | Test Case | Result |
|---|---|---|
| 1. | Upgrade `rancher-provisioning-capi` app with `NoSchedule` taints added to the nodes of the local cluster | ✅ |

---

Scenario 1 -
1. Fresh install of Rancher `v2.10-head` w/ `rancher-provisioning-capi` set to `105.0.0+up0.4.0`
2. Add a `NoSchedule` taint to each node of the local cluster
3. Redeploy Rancher deployment
4. Navigate to `Cluster Explorer > Apps > Installed Apps` and upgrade `rancher-provisioning-capi` to `105.1.0+up0.6.0`
5. Verified - `rancher-provisioning-capi` is successfully upgraded to `105.1.0+up0.6.0`; helm installation completes successfully without errors; as expected
