### ISSUE TITLE
Welcome page (add host/add service) should be redone for mobile

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4801]
**Version:** master 5/13

**Steps to Reproduce:**
1.  Create a new environment
2.  Resize browser to reflect mobile size
3.  Go to new environment

**Results:** Welcome screen does not look good.
![image](https://cloud.githubusercontent.com/assets/11514927/15264330/f4e40afe-1926-11e6-976c-63bea1995cc2.png)

**Expected:** We might to have a specific welcome page created for mobile

**Comment by lvuch** [comment]
resolved in https://github.com/rancher/ui/pull/665

**Comment by tfiduccia** [comment]
Version - master 5.19
Verified fixed
