### ISSUE TITLE
i18n Issues

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4803]
- [x] Add Load Balancer - translation not found: locale='en-us', key='newBalancer.tabs.schedule'.
subscribe.js:97 Subscribe ping
![image](https://cloud.githubusercontent.com/assets/11514927/15264818/9907017c-192c-11e6-986f-a0321ce0a7e1.png)

- [x] Edit load balancer - 
translation not found: locale='en-us', key='formBalancerListeners.table.access'.
missing-message.js:9
translation not found: locale='en-us', key='editBalancerService.haproxy.default.label'.
missing-message.js:9 
translation not found: locale='en-us', key='editBalancerService.haproxy.default.prompt'.
![image](https://cloud.githubusercontent.com/assets/11514927/15265008/d94580d0-192f-11e6-8484-2d9c69513388.png)
Mobile:
![image](https://cloud.githubusercontent.com/assets/11514927/15265018/f4bb5312-192f-11e6-8b8e-68b48637f125.png)

- [x] Catalog: All question types - translation not found: locale='en-us', key='newCatalog.questionType:'.
11subscribe.js:97 Subscribe ping
![image](https://cloud.githubusercontent.com/assets/11514927/15264851/1ac6947a-192d-11e6-8879-cc328d48ffff.png)

- [x] Stack details page - translation not found: locale='en-us', key='stackSection.add.description'.
![image](https://cloud.githubusercontent.com/assets/11514927/15264979/8ac9b660-192f-11e6-9cf7-f405d4637734.png)

- [x] Add Host: & is showing as &amp (Amazon, packet & Ubiquity)
![image](https://cloud.githubusercontent.com/assets/11514927/15264871/86d2ddea-192d-11e6-9098-fd809ee58b84.png)
![image](https://cloud.githubusercontent.com/assets/11514927/15264904/06cae9ca-192e-11e6-9700-5afc27052efe.png)

- [x] Add Host: Amazon - Security Group section under the Custom radio option - translation not found: locale='en-us', key='machine.driverAmazon.allTraffic'.
![image](https://cloud.githubusercontent.com/assets/11514927/15264918/21b9b752-192e-11e6-9cf8-aed0180d64ef.png)

- [x] Add Host: Exoscale - Security Group section under Automatically - translation not found: locale='en-us', key='machine.driverExoscale.standard'.
![image](https://cloud.githubusercontent.com/assets/11514927/15264948/cddc0b48-192e-11e6-8123-697c0ccd829d.png)

- [x] Add Host: All Rackspace fields
![image](https://cloud.githubusercontent.com/assets/11514927/15264879/a7f198ae-192d-11e6-9e0f-9098f9b8afa7.png)

- [x] Add Host: Azure - translation not found: locale='en-us', key='machine.driverAzure.dockerSwarm:'.
![image](https://cloud.githubusercontent.com/assets/11514927/15264892/d545fe6c-192d-11e6-962e-d2f22cefb518.png)

**Comment by tfiduccia** [comment]
- [ ] Add Host: Amazon - 
translation not found: locale='en-us', key='machine.driverAmazon.securityGroupDot.creating'.
translation not found: locale='en-us', key='machine.driverAmazon.instanceOptionsSection'.
*%MACHINE.DRIVERAMAZON.INSTANCEOPTIONSSECTION%*

**Comment by deniseschannon** [comment]
v1.1.0-dev2-rc2

- [ ] 
<img width="500" alt="screen shot 2016-05-15 at 12 57 18 pm" src="https://cloud.githubusercontent.com/assets/11410997/15276432/c7f7cfae-1a9c-11e6-8bd4-20369206dd3e.png">

- [ ] In Container stats

<img width="602" alt="screen shot 2016-05-15 at 12 25 24 pm" src="https://cloud.githubusercontent.com/assets/11410997/15276434/cc34fb32-1a9c-11e6-99c3-557d1a5ec2c3.png">

**Comment by sangeethah** [comment]
v1.1.0-dev2-rc3

About screen:
<img width="492" alt="screen shot 2016-05-17 at 11 03 50 am" src="https://cloud.githubusercontent.com/assets/4266958/15333578/1338f94c-1c1f-11e6-9b90-5ce28f459acb.png">

**Comment by vincent99** [comment]
@tfiduccia Can you move the error page one to a separate issue, as it's got special problems (like what if the error was with loading the translations...).  The rest are fixed.

**Comment by tfiduccia** [comment]
Version - master 5/19
Verified fixed
