### ISSUE TITLE
[backport v2.9] [BUG] Remove mirrored-prometheus-windows-exporter from rancher-images.txt

### ISSUE THREAD

**Issue by jbiers** [rancher/rancher#48051]
Issue created for tracking the backport of https://github.com/rancher/rancher/issues/47912 for v2.9

**Comment by prachidamle** [comment]
@pankajsqe assigned to you since I am not sure who to assign this ticket from QA

**Comment by deepakpunia-suse** [comment]
Mirrored Prometheus Windows exporter image moved from rancher-images.txt to rancher-windows-images.txt. This change ensures that the image is included in the appropriate list for Windows-based Rancher deployments. Validation passed.

Details
Rancher : v2.9.5-alpha1
Cluster : RKE2

rancher-images.txt
![Image](https://github.com/user-attachments/assets/37125c30-3dec-43d6-b6ce-55a8d3ee2934)

![Image](https://github.com/user-attachments/assets/be15f255-5d1a-4c54-a6fa-8d9b9e9ea5a5)

rancher-windows-images.txt
![Image](https://github.com/user-attachments/assets/a988b394-a3f4-4782-9871-06a70718b628)
