### ISSUE TITLE
[Backport 2.10] [BUG] rancher-provisioning-capi chart version is not being pinned

### ISSUE THREAD

**Issue by Sahota1225** [rancher/rancher#48064]
Backport for https://github.com/rancher/rancher/issues/47848

**Comment by Josh-Diamond** [comment]
Ticket #48064 - Test Results - ✅ 
---

Verified on Rancher `v2.10-58e887a871d1377399ff18a4ee95335981f08991-head`:

| Scenario | Test Case | Result |
|---|---|---|
| 1. | Fresh install of Rancher `v2.10-head` => verify `rancher-provisioning-capi` chart matches version specified in `build.yaml` | ✅ |
| 2. | Set `CATTLE_RANCHER_PROVISIONING_CAPI_VERSION` env var to be different than the version specified in `build.yaml` | ✅ |

---

Scenario 1 - ✅ 
1. Fresh install of Rancher `v2.10-head`
2. Navigate to `Cluster Explorer > Apps > Installed Apps (All Namespaces)` and verify `rancher-provisioning-capi` chart matches `105.1.0+up0.6.0`; as specified in the [build.yaml ](https://github.com/rancher/rancher/blob/release/v2.10/build.yaml) for `release/v2.10`
3. Verified - `rancher-provisioning-capi` chart is deployed and `active`, utilizing version `105.1.0+up0.6.0`; as expected

---

Scenario 2 - ✅ 
1. Spin up Rancher `v2.10-head` and set `CATTLE_RANCHER_PROVISIONING_CAPI_VERSION` env var on Rancher deployment to `105.0.0+up0.4.0`
2. Navigate to `Cluster Explorer > Apps > Installed Apps (All Namespaces)` and verify `rancher-provisioning-capi` chart matches `105.0.0+up0.4.0`
3. Verified - `CATTLE_RANCHER_PROVISIONING_CAPI_VERSION` env var accurately sets `rancher-provisioning-capi` chart to `105.0.0+up0.4.0`; as expected
