### ISSUE TITLE
[Backport 2.9] rancher-provisioning-capi chart version is not being pinned

### ISSUE THREAD

**Issue by Sahota1225** [rancher/rancher#48065]
Backport https://github.com/rancher/rancher/issues/47848

**Comment by Josh-Diamond** [comment]
Ticket #48065 - Test Results - ✅ 
---

Verified on Rancher `v2.9-cbf249751523895d2bbd1c7b0e19cfb79bb09a03-head`:

| Scenario | Test Case | Result |
|---|---|---|
| 1. | Fresh install of Rancher `v2.9-head` => verify `rancher-provisioning-capi` chart matches version specified in `build.yaml` | ✅ |
| 2. | Set `CATTLE_RANCHER_PROVISIONING_CAPI_VERSION` env var to be different than the version specified in `build.yaml` | ✅ |

---

Scenario 1 - ✅ 
1. Fresh install of Rancher `v2.9-head`
2. Navigate to `Cluster Explorer > Apps > Installed Apps (All Namespaces)` and verify `rancher-provisioning-capi` chart matches `104.1.0+up0.3.1`; as specified in the [build.yaml ](https://github.com/rancher/rancher/blob/release/v2.9/build.yaml)for `release/v2.9`
3. Verified - `rancher-provisioning-capi` chart is deployed and `active`, utilizing version `104.1.0+up0.3.1`; as expected

---

Scenario 2 - ✅ 
1. Spin up Rancher `v2.9-head` and set `CATTLE_RANCHER_PROVISIONING_CAPI_VERSION` env var on Rancher deployment to `104.0.0+up0.3.0`
2. Navigate to `Cluster Explorer > Apps > Installed Apps (All Namespaces)` and verify `rancher-provisioning-capi` chart matches `104.0.0+up0.3.0`
3. Verified - CATTLE_RANCHER_PROVISIONING_CAPI_VERSION env var accurately sets `rancher-provisioning-capi` chart to `104.0.0+up0.3.0`; as expected
