### ISSUE TITLE
create stack then remove waiting:  removing in progress

### ISSUE THREAD

**Issue by llitfkitfk** [rancher/rancher#4809]
* Removing (In Progress) *

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.0.1` Cattle: `v0.159.7` UI: `v1.0.5` |
|Access|`localauth` `admin`|
|Route|`environment.index`|

**Comment by llitfkitfk** [comment]
Actions: add stack using docker-compose.yml:
```
...
server:
  image: xxxx
  external_links: 
    - ${stack/service}:db
...

```

**Comment by llitfkitfk** [comment]
finally stack removed

**Comment by Napsty** [comment]
@llitfkitfk How? Just by waiting it out or did you have to do something?
