### ISSUE TITLE
[Backport v2.10] Add managed annotation to Chart.yaml in rancher-provisioning-capi helm chart

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#48094]
Backport of https://github.com/rancher/rancher/issues/44353 to v2.10.x line of releases

**Comment by Josh-Diamond** [comment]
Ticket #48094 - Test Results - ✅ 
---

Verified on Rancher `v2.10-58e887a871d1377399ff18a4ee95335981f08991-head`:

| Scenario | Test Case | Result |
|---|---|---|
| 1. | Ensure `catalog.cattle.io/managed: 'true'` is set as an annotation in `rancher-provisioning-capi` YAML under spec.chart.metadata.annotations` | ✅ |
| 2. | Attempt to delete `rancher-provisioning-capi` app and ensure UI warning modal pops up, warning users about this action | ✅ |

---

Scenario 1 -
1. Fresh install of Rancher `v2.10-head`
2. Navigate to `Cluster Explorer > Apps > Installed Apps` in the local cluster and view YAML for `rancher-provisioning-capi`
3. Check `spec.chart.metadata.annotations` for the following annotation:
```
catalog.cattle.io/managed: 'true'
```
4. Verified - annotation is present and accurately set; as expected

---

Scenerio 2 -
1. Fresh install of Rancher `v2.10-head`
2. Navigate to `Cluster Explorer > Apps > Installed Apps` in the local cluster and attempt to delete `rancher-provisioning-capi`
3. Verified - UI modal pops up warning users of this action, as expected

Screenshot:
<img width="425" alt="Screenshot 2024-12-03 at 1 40 46 PM" src="https://github.com/user-attachments/assets/36f95a98-8822-41dd-a958-7323f69f2275">
