### ISSUE TITLE
[Backport v2.10] Nodes may fail to reconnect after K8s upgrade for K3s clusters with multiple etcd-only nodes

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#48096]
Backport of https://github.com/rancher/rancher/issues/48050 to v2.10.x line of releases

**Comment by snasovich** [comment]
Waiting for RKE2 November release and for it to be added to KDM.

**Comment by snasovich** [comment]
Ready to test since https://github.com/rancher/kontainer-driver-metadata/pull/1559 is merged now.

**Comment by susesgartner** [comment]
Ticket #48096 - Test Results - ✅ 
---
 
| Scenario | Test Case | Result |
|---|---|---|
| 1. | Upgrade k8s version | PASS |
 
---
Verified with (HA Helm or Docker) on Rancher `v2.10.1-alpha1`:
---
 
Scenario 1: Upgrade k8s version
---
1. Provision a 3etcd, 2cp, 3 worker k3s cluster
2. Upgrade the k8s version
3. Verify that the cluster returns to a stable state after the upgrade.
 
Results: The cluster returns to a stable state after the upgrade.
