### ISSUE TITLE
Catalog categories are compared case-sensitive but displayed case-insensitive

### ISSUE THREAD

**Issue by sshipway** [rancher/rancher#4810]
**Rancher Version:** 1.1.0-dev1

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:**
View current Community catalogue.  There are two items: Minecraft (category "Entertainment") and XPilot (Category "entertainment").
Open category selector dropdown.

**Results:** 
You see two separate lines "Entertainment" as they have been grouped case-sensitive but the entries are forced to ucfirst for display

**Expected:**
A single category "Entertainment" containing both items.

A quick fix would be to just change the catalog item category, but a better longterm solution would be for the comparison to work as expected

**Comment by prachidamle** [comment]
@vincent99 do you see this as UI issue?

**Comment by tfiduccia** [comment]
Version - master 9/16
Although we fixed the catalog so there is only 1 Entertainment category, the Issue still exist.
Steps:
1.  Create two catalogs - one with category = test, the other with category = Test.
2.  Upload and go to catalog, refresh
3.  Go to category drop-down

You will see two Test categories
![image](https://cloud.githubusercontent.com/assets/11514927/18604337/505ff5c0-7c30-11e6-8ea8-41c2d16f4e72.png)

**Comment by tfiduccia** [comment]
Version - master 11/06
Verified fixed
