### ISSUE TITLE
[v2.10] CIS: Unexpected Failures in scans for gke 1.6.0 profile

### ISSUE THREAD

**Issue by vardhaman22** [rancher/rancher#48112]
cluster: gke v1.31
scan profile: gke-profile-1.6.0

even though config files have correct permissions the state of the check is failed.
Which is because of some volume mounts missing in cis-operator.
To fix those volume mounts needs to be added for the following files:
1. /home/kubernetes/kubelet-config.yaml
2. /var/lib/kubelet/kubeconfig

Also the default profile should be set to gke-proflie-1.6.0
This should fix the following scans:
**3.1.1, 3.1.2**

**Comment by rishabhmsra** [comment]
Validated on rancher v2.10-head

- Installed CIS 105+7.1.0 chart on GKE v1.31 cluster.
- Ran gke 1.6.0 profile scan.
- 3.1.1 and 3.1.2 passed, but there were 7 failures as below :

```
Fail
3.1.3	Ensure that the kubelet configuration file has permissions set to 600 (Manual)
Fail
3.1.4	Ensure that the kubelet configuration file ownership is set to root:root (Manual)
Fail
3.2.1	Ensure that the Anonymous Auth is Not Enabled (Automated)
Fail
3.2.2	Ensure that the --authorization-mode argument is not set to AlwaysAllow (Automated)
Fail
3.2.3	Ensure that a Client CA File is Configured (Automated)
Fail
3.2.7	Ensure that the --eventRecordQPS argument is set to 0 or a level which ensures appropriate event capture (Automated)
Fail
3.2.9	Ensure that the RotateKubeletServerCertificate argument is set to true (Automated)
```

**Comment by vivek-shilimkar** [comment]
Closing the issue since the failures are expected.
