### ISSUE TITLE
After adding host, going to services page instead of staying on host page

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4812]
**Version:** Master 5/15

**Steps to Reproduce:**
1.  Add a host to already setup environment (an environment that has hosts, services, etc...)

**Results:** After I add the host it goes to services page

**Expected:** Should stay on host page.

**Comment by vincent99** [comment]
`backTo` query param wasn't getting reset (so you had to previously have gone to add host from the waiting screen or somewhere like that)

**Comment by tfiduccia** [comment]
Version - master 6/9
Verified fixed
