### ISSUE TITLE
[Backport] [v2.9]  CIS: Unexpected Failures in scans for gke 1.6.0 profile

### ISSUE THREAD

**Issue by vardhaman22** [rancher/rancher#48123]
backport : https://github.com/rancher/rancher/issues/48112

**Comment by vivek-shilimkar** [comment]
Tested the CIS Scan on GKE cluster v1.30.7-gke.1084000. There are few scan failures however, the scan number **3.1.1, 3.1.2** are fixed. Hence closing the issue.
