### ISSUE TITLE
E1122 07:11:43.035802       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.24.4/tools/cache/reflector.go:167: Failed to watch *v2beta2.HorizontalPodAutoscaler: failed to list *v2beta2.HorizontalPodAutoscaler: the server could not find the requested resource

### ISSUE THREAD

**Issue by hymansj** [rancher/rancher#48150]
After I upgraded Kubernetes from 1.25 to 1.27 in the Rancher Web UI, I noticed that the rancher-monitoring-kube-state-metrics logs show errors like:
E1122 07:11:43.035802       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.24.4/tools/cache/reflector.go:167: Failed to watch *v2beta2.HorizontalPodAutoscaler: failed to list *v2beta2.HorizontalPodAutoscaler: the server could not find the requested resource
W1122 07:12:17.617564       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.24.4/tools/cache/reflector.go:167: failed to list *v2beta2.HorizontalPodAutoscaler: the server could not find the requested resource
...
My Rancher version is 2.7.5, and the monitoring component I installed is rancher-monitoring:102.0.5+up40.1.2. After investigating, I found that Kubernetes 1.27 no longer supports the v2beta2 API version for HorizontalPodAutoscaler.

How can I resolve this issue using the Rancher Web UI?

**Comment by slickwarren** [comment]
hello, rancher 2.7 is EOL. Please try upgrading to a supported version, 2.8, 2.9 or 2.10
