### ISSUE TITLE
[Backport 2.9]  Add managed annotation to Chart.yaml in rancher-provisioning-capi helm chart

### ISSUE THREAD

**Issue by Sahota1225** [rancher/rancher#48164]
Backport for https://github.com/rancher/rancher/issues/44353

**Comment by Josh-Diamond** [comment]
Ticket #48164 - Test Results - ✅ 
---

Verified on Rancher `v2.9-cbf249751523895d2bbd1c7b0e19cfb79bb09a03-head`:

| Scenario | Test Case | Result |
|---|---|---|
| 1. | Ensure `catalog.cattle.io/managed: 'true'` is set as an annotation in `rancher-provisioning-capi` YAML under spec.chart.metadata.annotations` | ✅ |
| 2. | Attempt to delete `rancher-provisioning-capi` app and ensure UI warning modal pops up, warning users about this action | ✅ |

---

Scenario 1 - ✅ 
1. Fresh install of Rancher `v2.9-head`
2. Navigate to `Cluster Explorer > Apps > Installed Apps` in the local cluster and view YAML for `rancher-provisioning-capi`
3. Check `spec.chart.metadata.annotations` for the following annotation:
```
catalog.cattle.io/managed: 'true'
```
4. Verified - annotation is present and accurately set; as expected

---

Scenerio 2 - ✅ 
1. Fresh install of Rancher `v2.9-head`
2. Navigate to `Cluster Explorer > Apps > Installed Apps` in the local cluster and attempt to delete `rancher-provisioning-capi`
3. Verified - UI modal pops up warning users of this action, as expected

Screenshot:
<img width="450" alt="Screenshot 2024-12-03 at 1 54 42 PM" src="https://github.com/user-attachments/assets/e3be6a6f-9c83-4534-a836-f902c05dac09">
