### ISSUE TITLE
[BUG] CLI server ls command is missing format option

### ISSUE THREAD

**Issue by pmatseykanets** [rancher/rancher#48169]
**Rancher Server Setup**
- Rancher version: 
- Installation option (Docker install/Helm Chart): N/A
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version:
- Cluster Type (Local/Downstream): N/A

**User Information**
- What is the role of the user logged in? N/A

**Describe the bug**

The Rancher CLI `server ls` command is missing the `--format` option.

**To Reproduce**

**Result**

**Expected Result**

**Screenshots**

**Additional context**

**Comment by Priyashetty17** [comment]
Validated with CLI version `v2.11.0-rc.3`

- Verify 'server ls' with format - json
- Verify 'server ls' with format - yaml
- Verify 'server ls' with format - custom
- Verify 'server ls' help menu includes format option
