### ISSUE TITLE
[Backport v2.9] [BUG] Unable to provision RKE1 node driver cluster using RHEL 9.2 and 9.0 amis

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#48194]
Backport of https://github.com/rancher/rancher/issues/48143 to v2.9.x release line

Needs branching for `rancher/machine` figured out for v2.9 so not targeting the next v2.9.x release yet.

**Comment by vivek-shilimkar** [comment]
Tested the issue on rancher v2.9-head (from prime repo). The cluster with RHEL OS 9.0 and 9.2 provisions successfully. Hence closing the issue.
