### ISSUE TITLE
[Backport v2.10] [BUG] Unable to provision RKE1 node driver cluster using RHEL 9.2 and 9.0 amis

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#48193]
Backport of https://github.com/rancher/rancher/issues/48143 to v2.10.x release line

**Comment by rishabhmsra** [comment]
Validated on rancher v2.10-head :

- Provisioned RKE1 node driver, k8s v1.31.2-rancher1-1 cluster using RHEL 9.2 and 9.0 and both cluster provisioned successfully.
- Network checks also passed on both of them.
