### ISSUE TITLE
[BUG] rancher-monitoring ignoreNamespaceSelectors has wrong default value

### ISSUE THREAD

**Issue by jbiers** [rancher/rancher#48199]
The value of prometheus.prometheusSpec.ignoreNamespaceSelectors was set to "true" by accident during an old rebase. This diverges from upstream's default behavior seemingly for no special reason so it must be changed back to "false". 

**Additional context**
SURE-9374

**Comment by deepakpunia-suse** [comment]
The bug related to the accidental setting of `prometheus.prometheusSpec.ignoreNamespaceSelectors` to `true` has been verified as resolved. After conducting tests on an RKE2 cluster, I can confirm that the value has been correctly reverted to `false`, aligning with upstream defaults.

**Details:**
- **Rancher Version:** v2.10-head
- **Cluster Version:** v1.31.3-rc1+rke2r1
- **Monitoring Chart Version:** 105.1.1-rc.1+up61.3.2

The attached screenshot verifies the corrected configuration. The cluster and monitoring behavior are now consistent with the expected standards, ensuring no deviations from the upstream specifications.

![Image](https://github.com/user-attachments/assets/1a6120c4-eb13-4560-b73c-ee8c4fcca222)



![Image](https://github.com/user-attachments/assets/48af9d5e-0f24-4b7a-813f-75b6b6467771)
