### ISSUE TITLE
[Backport v2.10] [BUG] The state of the imported K3s cluster alternates between "Ready" and "Upgrading" at the start of the cluster upgrade process

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#48206]
This issue is to track https://github.com/rancher/rancher/issues/48204 backport to v2.10 release line.

**Comment by jiaqiluo** [comment]
The fix can be validated on the lastest v2.10-head image

**Comment by Josh-Diamond** [comment]
Ticket # 48206 - Test Results - ✅ 
---

Verified on Rancher `v2.10-285b54e12a2be58ffd0d0d437463818f863de0eb-head`:

| Scenario | Test Case | Result |
|---|---|---|
| 1. | Import k3s cluster => upgrade k8s version => ensure cluster enters `updating` state and remains in `updating` state until the upgrade is complete and the cluster is `active` and stable | ✅ |

---

Scenario 1 - ✅ 
1. Fresh install of Rancher `v2.10-head`
2. Spin up a standalone k3s cluster w/ k8s `v1.30.6+k3s1`
3. Import the k3s cluster into Rancher
4. Once imported and `active`; `Edit Config` and upgrade k8s version to `v1.31.2+k3s1`
5. Verified - cluster enters `upgrading` state and remains in that state until the upgrade is complete, at which point the cluster state changes to `active`; as expected
