### ISSUE TITLE
[backport v2.9] [BUG] rancher-monitoring ignoreNamespaceSelectors has wrong default value

### ISSUE THREAD

**Issue by jbiers** [rancher/rancher#48200]
Issue created to track the backport of https://github.com/rancher/rancher/issues/48199

**Comment by pankajsqe** [comment]
rancher-monitoring ignoreNamespaceSelectors has wrong default value has been set to false in values.yaml file. Same has been tested and verified.

Details
Rancher : v2.9-head
Monitoring : 104.1.3-rc.1+up57.0.3
Cluster : v1.30.1+rke2r1

![Image](https://github.com/user-attachments/assets/b572e603-1646-499f-b6de-c264df30a173)
