### ISSUE TITLE
Deleting ingress from the kubernetes set up through CLI is not successful

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#4821]
**Rancher Version:** Master

**OS and where are the hosts located? (cloud, bare metal, etc):**Ubuntu, Cloud

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**:Kubernetes

**Steps to Reproduce:**
1. Create multiple ingresses 
2. Delete each of them serially from the CLI
3. The last deletion is not successful

[deletingress.txt](https://github.com/rancher/rancher/files/267168/deletingress.txt)

**Comment by alena1108** [comment]
Elaborate - ingress was removed,but the LB on Rancher side wasn't cleaned up.

**Comment by soumyalj** [comment]
Tested with updated image of ingress controller : alena1108/ingress-controller:v0.1.1. Deletion is successful.
