### ISSUE TITLE
Layer 4 load balancing with domain names

### ISSUE THREAD

**Issue by andrewmclagan** [rancher/rancher#4823]
Are there plans to implement layer 4 (TCP)  balancing in ranchers HAProxy?

For example we would like to have `cache.mydomain.com` be forwarded to redis at port 6379 behind the rancher load balancer

**Comment by deniseschannon** [comment]
We already have L7 load balancing.

http://docs.rancher.com/rancher/latest/en/rancher-ui/applications/stacks/adding-balancers/#advanced-routing-options

http://docs.rancher.com/rancher/latest/en/rancher-compose/rancher-services/#advanced-load-balancing-l7

Is that what you were looking for?

**Comment by andrewmclagan** [comment]
Yes.. :)
