### ISSUE TITLE
rancher run in docker version 1.10.3 can't add hosts docker version  are  1.11.1

### ISSUE THREAD

**Issue by wangweihong** [rancher/rancher#4824]
**Rancher Version:**
v1.0.1
**Docker Version:**
1.10.3
**OS and where are the hosts located? (cloud, bare metal, etc):**
centos7.2
**Setup Details: (single node vs. single node, internal DB vs. external DB)**
single node
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

I run rancher server in host which docker version is 1.10.3.  When I try to add a host which docker version is 1.11.1, it fails.  This is what agent logs :

_time="2016-05-16T21:35:12Z" level="info" msg="Watching state directory: /var/lib/rancher/state/containers" 
time="2016-05-16T21:35:12Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"2eedda3f3937240135c126f03b0bf6304903c6c6c522b67b3a2d88e952883b78\", From:\"-simulated-\", Time:0}" 
time="2016-05-16T21:35:12Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=0 reportedUuid="8fc19665-6ddb-4306-8d72-3c25d794f18c" 
time="2016-05-16T21:35:13Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=1 reportedUuid="8fc19665-6ddb-4306-8d72-3c25d794f18c" 
time="2016-05-16T21:35:14Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=2 reportedUuid="8fc19665-6ddb-4306-8d72-3c25d794f18c" 
time="2016-05-16T21:35:15Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=3 reportedUuid="8fc19665-6ddb-4306-8d72-3c25d794f18c" 
time="2016-05-16T21:35:16Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=4 reportedUuid="8fc19665-6ddb-4306-8d72-3c25d794f18c" 
time="2016-05-16T21:35:17Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=5 reportedUuid="8fc19665-6ddb-4306-8d72-3c25d794f18c" 
time="2016-05-16T21:35:18Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=6 reportedUuid="8fc19665-6ddb-4306-8d72-3c25d794f18c" 
time="2016-05-16T21:35:19Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=7 reportedUuid="8fc19665-6ddb-4306-8d72-3c25d794f18c" 
time="2016-05-16T21:35:20Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=8 reportedUuid="8fc19665-6ddb-4306-8d72-3c25d794f18c" 
time="2016-05-16T21:35:21Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=9 reportedUuid="8fc19665-6ddb-4306-8d72-3c25d794f18c" 
time="2016-05-16T21:35:22Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=10 reportedUuid="8fc19665-6ddb-4306-8d72-3c25d794f18c" 
time="2016-05-16T21:35:23Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=11 reportedUuid="8fc19665-6ddb-4306-8d72-3c25d794f18c" 
time="2016-05-16T21:35:24Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=12 reportedUuid="8fc19665-6ddb-4306-8d72-3c25d794f18c" 
time="2016-05-16T21:35:25Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=13 reportedUuid="8fc19665-6ddb-4306-8d72-3c25d794f18c" 
time="2016-05-16T21:35:26Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=14 reportedUuid="8fc19665-6ddb-4306-8d72-3c25d794f18c" 
time="2016-05-16T21:35:27Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=15 reportedUuid="8fc19665-6ddb-4306-8d72-3c25d794f18c" 
time="2016-05-16T21:35:28Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=16 reportedUuid="8fc19665-6ddb-4306-8d72-3c25d794f18c" 
time="2016-05-16T21:35:29Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=17 reportedUuid="8fc19665-6ddb-4306-8d72-3c25d794f18c" 
time="2016-05-16T21:35:30Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=18 reportedUuid="8fc19665-6ddb-4306-8d72-3c25d794f18c" 
time="2016-05-16T21:35:31Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=19 reportedUuid="8fc19665-6ddb-4306-8d72-3c25d794f18c" 
time="2016-05-16T21:35:32Z" level="fatal" msg="Reached max retry attempts for getting token."_

**Comment by deniseschannon** [comment]
We currently only support Docker 1.10.3, but I'll add this to the issue for Docker 1.11 support.

https://github.com/rancher/rancher/issues/4824
