### ISSUE TITLE
Remove app, catalog, multiclusterapp commands from Rancher CLI

### ISSUE THREAD

**Issue by pmatseykanets** [rancher/rancher#48252]
Multi-cluster apps were deprecated and removed with https://github.com/rancher/rancher/issues/39525
Remove corresponding commands from the CLI.

**Comment by Priyashetty17** [comment]
Validated with CLI version `v2.11.0-rc.3`
- Verify app/apps command is removed
- Verify catalog command is removed
- Verify multiclusterapp/multiclusterapps/mcapp/mcapps command is removed
- Verify removed commands are not listed in --help output
