### ISSUE TITLE
[BUG] Update 2.9.0 -> 2.10.0 Longhorn App missing

### ISSUE THREAD

**Issue by Trekky12** [rancher/rancher#48257]
**Rancher Server Setup**
- Rancher version: v2.10.0
- Installation option: Helm chart, RKE2 , v1.31.2
- Proxy/Cert Details: airgapped with local docker registry

**Information about the Cluster**
- Kubernetes version: v1.30.2 and v1.31.2
- Cluster Type (Local/Downstream): Custom Downstream

**Describe the bug**
When opening the local or downstream cluster the available apps in v2.10.0 are less than in v2.9.0.
Especially Longhorn is missing!

**Comment by skanakal** [comment]
https://github.com/longhorn/longhorn/issues/9814

**Comment by Trekky12** [comment]
Sorry didn’t found this issue, thanks for the hint.
