### ISSUE TITLE
[BUG][2.10] Azure AD China auth returning "error status code received from the API

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#48264]
forwardport #47251

**Comment by rootwuj** [comment]
Verified on v2.10.1-alpha1 and v2.10.0 >> v2.10.1-alpha1

Verified Azure AD can be successfully connected by selecting China Endpoint.
Verified Azure users can log in and have correct permissions.
Verified that after upgrading from v2.10.0 to v2.10.1-alpha1, Azure AD China can be successfully connected.


Test steps:

1. Register Rancher with Azure China and set the Redirect URI to <MY_RANCHER_URL>/verify-auth-azure.
2. Create a new client secret and save it.
3. Set required API permissions for Rancher.
4. Allow Public Client Flows.
5. Copy Azure China application data to the forms in Rancher AzureAD authentication provider. The endpoints should be selected for China.
6. Click Save and login to Azure account from the popup window.
7. The Azure AD auth provider becomes active.
8. Add Azure user `user1` as [Cluster Member], log in with `user1`, and verify that the user permissions are correct.  
9. Add Azure user `user2` as [Project Owner], log in with `user2`, and verify that the user permissions are correct.

![image](https://github.com/user-attachments/assets/ccd3d627-6831-44a3-aba0-4a97296afac2)
