### ISSUE TITLE
[2.11] "Oberved a panic" on Upgrade to 2.10.0

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#48262]
forwardport of #48180

**Comment by nickwsuse** [comment]
Verified on v2.11-head ID: `9b44650` ✅ 
----

Test Cases (All are upgrades from `v2.9.3 -> v2.11-head` and were run on docker single node and HA clusters):
1. Basic Auth | Regular ASCII Characters ✅ 
2. Basic Auth | Non-ASCII Characters ✅ 
3. SAML | Regular ASCII Characters ✅ 
4. SAML | Non-ASCII Characters ✅ 
5. OAuth | Regular ASCII Characters ✅ 
6. OAuth | Non-ASCII Characters ✅ 

The PR only made changes to local auth from the looks of it, but I went ahead and tested SAML and OAuth just to be sure that other providers aren't affected.
