### ISSUE TITLE
Kubernetes stack does not show up in the UI while it is activating

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#4826]
**Rancher Version:** Master

**OS and where are the hosts located? (cloud, bare metal, etc):**Ubuntu, Cloud

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**:Kubernetes

**Steps to Reproduce:**
1. Switch from cattle to Kubernetes environment
2. While Kubernetes system stack is activating, the UI does not show the same.

mysql> select id, name, state from environment;

The following is the state of the database:
+----+------------------------+------------+
| id | name                   | state      |
+----+------------------------+------------+
|  1 | Kubernetes             | activating |
|  2 | default                | active     |
|  3 | kubernetes-ingress-lbs | active     |
+----+------------------------+------------+

**Comment by vincent99** [comment]
No longer applicable in 1.4.
