### ISSUE TITLE
[BUG][2.11] Azure AD China auth returning "error status code received from the API 

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#48265]
forwardport #47251

**Comment by rootwuj** [comment]
Verified on `v2.11-3ce716825fdd85fc05ce5a8fdc97e345455b241b-head`

Verified Azure AD can be successfully connected by selecting China Endpoint.
Verified Azure users can log in and have correct permissions.

Test steps:

1. Register Rancher with Azure China and set the Redirect URI to <MY_RANCHER_URL>/verify-auth-azure.
2. Create a new client secret and save it.
3. Set required API permissions for Rancher.
4. Allow Public Client Flows.
5. Copy Azure China application data to the forms in Rancher AzureAD authentication provider. The endpoints should be selected for China.
6. Click Save and login to Azure account from the popup window.
7. The Azure AD auth provider becomes active.
8. Add Azure user `user1` as [Cluster Member], log in with `user1`, and verify that the user permissions are correct.  
9. Add Azure user `user2` as [Project Owner], log in with `user2`, and verify that the user permissions are correct.
