### ISSUE TITLE
Can't click on Add Service button for stacks created by catalog

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4828]
**Version:** master 5/17

**Steps to Reproduce:**
1.  Add a stack from a catalog (so you will have the "up to date" text in the stack
2.  Change the size of the browser so mobile version comes up
3.  Try to click on Add Service

**Results:** You can't click on the Add Service because it's not in the main stack section but in the first service area.
![image](https://cloud.githubusercontent.com/assets/11514927/15334787/7eac82a2-1c24-11e6-8c5d-bca7bff6fc1e.png)

**Expected:**  Add Service should be up above.

**Comment by lvuch** [comment]
https://github.com/rancher/ui/pull/669

**Comment by tfiduccia** [comment]
version - master 5/24
Not fixed
Now with the mobile size, the Add service button doesn't show up at all
![image](https://cloud.githubusercontent.com/assets/11514927/15514025/f45307de-219b-11e6-968b-7a66fba98359.png)

**Comment by lvuch** [comment]
resolved in https://github.com/rancher/ui/pull/695

**Comment by tfiduccia** [comment]
Version - master 6/9
Verified fixed
