### ISSUE TITLE
etcd in Kubernetes stack is degraded  

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#4829]
**Rancher Version:**Master

**OS and where are the hosts located? (cloud, bare metal, etc):**Ubuntu, Cloud

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**: Kubernetes

**Steps to Reproduce:**
1. Switched from Cattle to Kubernetes after using the ingress-controller image alena1108/ingress-controller:v0.1.1

**Results:** 
1. etcd + 1 Sidekicks sevice is degraded. Specifically etcd-data container is stopped. Logs attached
[kuberneteslog_etcd.txt](https://github.com/rancher/rancher/files/268934/kuberneteslog_etcd.txt)

2. Kubernetes stack is degraded

**Comment by alena1108** [comment]
not a blocker; manual start of etcd container fixed the situation. Also tried disabling/enabling k8s on the environment couple of times, everything worked fine and etcd came green. Punting this bug to release 1.1, @soumyalj please update if you see this issue again.

**Comment by alena1108** [comment]
@soumyalj should be fixed with https://github.com/rancher/cattle/pull/1682

**Comment by soumyalj** [comment]
Verified in v1.1.0-dev2-rc4. etcd is healthy.
