### ISSUE TITLE
Service info popup issues

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4830]
**Version:** master 5/17

- [ ] Dividing lines showing up on right side and looks weird
![image](https://cloud.githubusercontent.com/assets/11514927/15336214/545be5be-1c2a-11e6-8545-7d2920c93372.png)

- [ ] Huge amount of white space between Containers & Port section
![image](https://cloud.githubusercontent.com/assets/11514927/15336231/70cfc8a0-1c2a-11e6-9538-be9bea6526f9.png)

**Comment by vincent99** [comment]
(on small screen)

**Comment by tfiduccia** [comment]
Version - master 6/9
Verified fixed
