### ISSUE TITLE
[BUG] Many stale secrets in the cattle-impersonation-system namespace to be cleaned

### ISSUE THREAD

**Issue by bigkevmcd** [rancher/rancher#48312]
**Rancher Server Setup**
- Rancher version:
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version:
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:

**Describe the bug**

Following on from https://github.com/rancher/rancher/issues/44347 and https://github.com/rancher/rancher/issues/47126 we have installations with many unused stale secrets.

**To Reproduce**

Run versions of Rancher prior to 2.8.8 or 2.9.2 and allow secrets to build up in the `cattle-impersonation-namespace` this will likely involve loading the remote cluster so that it slows and the cache isn't up-to-date enough with the remote version.

**Result**

Large numbers of impersonation secrets build up in the namespace.

**Expected Result**

**Screenshots**

**Additional context**

## Fix Versions

* [x] main https://github.com/rancher/rancher/pull/48014
* [ ] release/2.10
* [ ] release/2.9

**Comment by Priyashetty17** [comment]
Validated with `v2.11-c1904c15f9a221a3c4b75f132b7337f1008c7715-head`. 

| **Test Case**                                                             | **Steps**                                                                                                                                                                                                                      |
|-------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Fresh install: Stress test downstream cluster with 100 users performing random operations and checking for stale secrets | 1. Create a downstream cluster with low memory and CPU. <br> 2. Create 100 Users. <br> 3. Assign Users as Cluster Owners to the downstream cluster. <br> 4. For each created user, perform a login. <br> 5. In a loop for the specified test duration, perform random operations. For each user, after logging in with their token, randomly choose and perform one of the following operations: <br> &nbsp;&nbsp;&nbsp;&nbsp;a. Create a Deployment: Create an nginx deployment. <br> &nbsp;&nbsp;&nbsp;&nbsp;b. List Namespaces: List all namespaces in the cluster. <br> &nbsp;&nbsp;&nbsp;&nbsp;c. Get Pods: Retrieve all pods from the default namespace. <br> &nbsp;&nbsp;&nbsp;&nbsp;d. Sleep for 10 seconds between operations. <br> &nbsp;&nbsp;&nbsp;&nbsp;e. Log out the user after performing the operation. <br> 6. Check for stale secrets for each user. Verify that there are no stale secrets.|
| Upgrade - 2.10.1 -> 2.11-head: Stress test downstream cluster with 100 users performing random operations and checking for new stale secrets | 1. Create a Rancher instance with a released version. <br> 2. Create a downstream cluster with low memory and CPU. <br> 3. Create 100 Users. <br> 4. Assign Users as Cluster Owners to the downstream cluster. <br> 5. For each created user, perform a login. <br> 6. In a loop for the specified test duration, perform random operations. For each user, after logging in with their token, randomly choose and perform one of the following operations: <br> &nbsp;&nbsp;&nbsp;&nbsp;a. Create a Deployment: Create an nginx deployment. <br> &nbsp;&nbsp;&nbsp;&nbsp;b. List Namespaces: List all namespaces in the cluster. <br> &nbsp;&nbsp;&nbsp;&nbsp;c. Get Pods: Retrieve all pods from the default namespace. <br> &nbsp;&nbsp;&nbsp;&nbsp;d. Sleep for 10 seconds between operations. <br> &nbsp;&nbsp;&nbsp;&nbsp;e. Log out the user after performing the operation. <br> 7. Check for stale secrets for each user. Verify that there are stale secrets. <br> 8. Upgrade Rancher to the version under test. <br> 9. Check for stale secrets for each user. <br> 10. Delete all users created in step 3 and resources created in step 6. <br> 11. Repeat steps 3-6 and check for stale secrets for each user. Verify that there are no NEW stale secrets.|
| Upgrade - 2.9.1 -> 2.10.1 -> 2.11-head: Stress test downstream cluster with 100 users performing random operations and checking for old and new stale secrets | 1. Create a Rancher instance with 2.9.1. <br> 2. Create a downstream cluster with low memory and CPU. <br> 3. Create 100 Users. <br> 4. Assign Users as Cluster Owners to the downstream cluster. <br> 5. For each created user, perform a login. <br> 6. In a loop for the specified test duration, perform random operations. For each user, after logging in with their token, randomly choose and perform one of the following operations: <br> &nbsp;&nbsp;&nbsp;&nbsp;a. Create a Deployment: Create an nginx deployment. <br> &nbsp;&nbsp;&nbsp;&nbsp;b. List Namespaces: List all namespaces in the cluster. <br> &nbsp;&nbsp;&nbsp;&nbsp;c. Get Pods: Retrieve all pods from the default namespace. <br> &nbsp;&nbsp;&nbsp;&nbsp;d. Sleep for 10 seconds between operations. <br> &nbsp;&nbsp;&nbsp;&nbsp;e. Log out the user after performing the operation. <br> 7. Check for stale secrets for each user. Verify that there are stale secrets. <br> 8. Upgrade Rancher to 2.10.1. <br> 9. Check for stale secrets for each user. Verify that the stale secrets still exists. <br> 10. Upgrade Rancher to the version under test. <br> 11. Check for stale secrets for each user. Verify that there are NO stale secrets. <br> 12. Delete all users created in step 3 and resources created in step 6. <br> 13. Repeat steps 3-6 and check for stale secrets for each user. Verify that there are no stale secrets.|

**Comment by moio** [comment]
@bigkevmcd do you feel like we should note something about this in docs or release notes?
