### ISSUE TITLE
Upgrading service via UI has lost the Service Links names

### ISSUE THREAD

**Issue by ddmng** [rancher/rancher#4831]
When I try to upgrade a service, the list of original Service Links reports the correct service in the left side dropdown but all the mapped names on the right are not present, except for the first one.
This forces to remember how the service has been mapped in the docker-compose.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.0.0` Cattle: `v0.159.2` UI: `v0.100.3` |
|Access|`localauth` `admin`|
|Route|`service.new`|

**Comment by tfiduccia** [comment]
@ddmng - this should be fixed in the next release.

Version - master 5/17
Verified fixed
