### ISSUE TITLE
When containers are started with "start_once" , it is reported as being in "stopped" state and service is in "Degraded" state.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#4833]
Server version - Build from master

Deploy "Elastic Search" template.

When service is deployed,  it is "Degraded" state because all side-kick containers started with "start_once"  show up as being in "Stopped" state ( like "elasticsearch_elasticsearch-clients_elasticsearch-datavolume-clients_1") instead of "started_once".

start_count for the container is 0 instead of being 1.

<img width="1229" alt="screen shot 2016-05-17 at 3 58 30 pm" src="https://cloud.githubusercontent.com/assets/4266958/15342235/8b26690c-1c48-11e6-9018-a685c5bb7327.png">

<img width="1259" alt="screen shot 2016-05-17 at 4 01 04 pm" src="https://cloud.githubusercontent.com/assets/4266958/15342236/95e13728-1c48-11e6-8dda-4b10858ba023.png">

**Comment by alena1108** [comment]
Should be fixed, but its not a blocker.

**Comment by sangeethah** [comment]
Tested with latest build from master:
When "Elastic Search" template is deployed , services are not in "Degraded" state anymore.

**Comment by nunofgs** [comment]
I'm seeing this on 1.4.0-rc1. Is this a regression?

<img width="412" alt="screen shot 2017-01-12 at 22 49 00" src="https://cloud.githubusercontent.com/assets/92085/21911612/6658ea1c-d919-11e6-9151-e0980a8695a3.png">
<img width="308" alt="screen shot 2017-01-12 at 22 49 04" src="https://cloud.githubusercontent.com/assets/92085/21911613/665a0816-d919-11e6-89d4-482045363f81.png">

FYI: the stopped container is a sidekick data-only container that is correctly configured with the `start_once` label.

This was not happening before upgrading to 1.4.0-rc1 (I was on 1.1.0)

**Comment by mkulumadzi** [comment]
We are seeing this as well with a mongodb data volume, on v1.4.1.

We're having larger issues with the stack crashing intermittently, and it's unclear yet if the issue discussed on this ticket is part of the cause, or just a side effect.

**Comment by mkulumadzi** [comment]
Figured out our issue - the Janitor service was killing these stopped services. We excluded them per instructions on the Janitor service and this resolved things.
