### ISSUE TITLE
[TEST] - This is a test issue to be deleted.

### ISSUE THREAD

**Issue by Jono-SUSE-Rancher** [rancher/rancher#48347]
This is a test issue only, testing a workflow and some notifications.

**Comment by Jono-SUSE-Rancher** [comment]
@samjustus Did you get this?

**Comment by Jono-SUSE-Rancher** [comment]
@caroline-suse-rancher Did you get this?

**Comment by caroline-suse-rancher** [comment]
Yep

**Comment by Jono-SUSE-Rancher** [comment]
@samjustus - Again

**Comment by Jono-SUSE-Rancher** [comment]
OK @caroline-suse-rancher and @samjustus - this concludes our testing. I will be closing this issue now.
Also pinging @MKlimuszka and @Sahota1225 just to see their experience with pings as well.
