### ISSUE TITLE
[Backport v2.9] [BUG] VM of existing RKE1 node is not removed after the node is deleted from the cluster after upgrading to Rancher 2.9.3+

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#48343]
Backport of https://github.com/rancher/rancher/issues/48320 to v2.9.x release line

SURE-9483

**Comment by jiaqiluo** [comment]
The fix can be validated on the latest v2.9-head image.
Please refer to [this comment](https://github.com/rancher/rancher/issues/48320#issuecomment-2529240502) for more details.

**Comment by susesgartner** [comment]
Ticket #48343 - Test Results - ✅ 
---
 
| Scenario | Test Case | Result |
|---|---|---|
| 1. | Upgrade + scaling test | PASS |
| 2. | Post Upgrade scale up test | PASS |
| 3. | Post Upgrade scale down test | PASS |
 
---
Verified with (HA Helm or Docker) on Rancher `v2.9-b8239f00fb45d7bfcfc31b2b6a8d7c8a20f755bf-head`:
---

---
Permutations
---
Provider: Azure/AWS/Linode
Cluster Type: RKE1/RKE2/K3s
Node Config: 1 etcd, 1cp, 2 worker

 
Scenario 1: Upgrade + scaling test
---
1. Create a rancher 2.9.2 instance and provision
2. All cluster permutations listed above 
3. Upgrade to 2.9-head
4. Scale down one of the worker nodes
5. Verify that the cluster remains in a stable state and the instance is removed in the provider
 
Results: the cluster remains in a stable state and the instance is removed in the provider

---
 
Scenario 2: Post Upgrade scale up test
---
1. Create a rancher 2.9.2 instance and provision
2. All cluster permutations listed above 
3. Upgrade to 2.9-head
4. Scale up the worker nodes pool
5. Verify that the new worker provisions properly and the cluster remains in a stable state
 
Results: the new worker provisions properly and the cluster remains in a stable state
 

Scenario 3: Post Upgrade scale down test
---
1. Create a rancher 2.9.2 instance and provision
2. All cluster permutations listed above 
3. Upgrade to 2.9-head
4. Scale down the worker nodes pool
5. Verify that the cluster remains in a stable state and the instance is removed in the provider

Results: the cluster remains in a stable state and the instance is removed in the provider
