### ISSUE TITLE
LB: zero-downtime service upgrade fails

### ISSUE THREAD

**Issue by naartjie** [rancher/rancher#4834]
**Rancher Version:**
`v1.0.1`

**Docker Version:**
`v1.11.1`

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 14.04, DigitalOcean (Docker droplet)

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher, internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
* Create 2 hosts on DigitalOcean
* "Add Service" to Default stack: `nginx` docker image, running on all hosts, default options (don't expose ports)
* "Add Load Balancer" to Default stack. source port = 80, default port = 80. target service = nginx
* run `ab -lr -c 10 -n 10000 http://[ip_of_loadbalancer]`
* upgrade `nginx` service

**Results:** 
ab tests failures > 0

**Expected:**
ab tests failures = 0

**Comment by alena1108** [comment]
@naartjie a couple of things to confirm: 

* when doing upgrade, have you checked "Start before stopping" check box? By default we stop the old container, and only then create a new one. In order for original scale not to drop, you might want to select this check box, so the old container doesn't go down until the new one comes up.
* do you have health check configured for nginx service? Presence of health check would ensure that haproxy don't send a request to the service till its fully ready.

**Comment by naartjie** [comment]
@alena1108 thanks for looking into this

> Start before stopping
It is checked, sorry, I should have mentioned that

> Health check
No health checks, could you let me know how to configure the nginx health check, and I'll re-try with it on

**Comment by alena1108** [comment]
@naartjie in the UI, when add nginx service: go to "Health Check" tab, pick up "Http" option there and there you can configure health check.

**Comment by naartjie** [comment]
@alena1108 I configured an HTTP health check: `path = /` and `port = 80`. 

I am still getting some receive failures, and sometimes `Non-2xx` responses when running `ab`:

<img width="379" alt="screen shot 2016-05-19 at 07 25 45" src="https://cloud.githubusercontent.com/assets/514563/15383410/22c3e42e-1d93-11e6-9f15-b89398978bf0.png">

Are you not seeing the same on your side? Can you not reproduce this? I am just wondering what the best way might be for me to share this. I don't know how to automate this test (any hints?), but I could record a screencast of the steps I take.

**Comment by alena1108** [comment]
@naartjie was the number of failed requests reduced after adding health check? 

Unfortunately there still a chance for small amount of dropped requests (the reasons are covered here: https://github.com/rancher/rancher/issues/2777). Using health checks and "start before stopping" on upgrade should reduce it to the minimum.

**Comment by naartjie** [comment]
> was the number of failed requests reduced after adding health check?

@alena1108 yes, there are definitely less errors after adding the health checks.

I have subscribed to #2777 and am watching it for updates. The description makes sense. Thanks for the info.

**Comment by naartjie** [comment]
Closing this in favor of #2777
