### ISSUE TITLE
[Backport v2.8] [BUG] VM of existing RKE1 node is not removed after the node is deleted from the cluster after upgrading to Rancher 2.9.3+/2.8.9+

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#48342]
Backport of https://github.com/rancher/rancher/issues/48320 to v2.8.x release line (note the issue is likely reproducible on v2.8.9 as the change that caused it on v2.9.3 was also backported to v2.8.9).

SURE-9483

**Comment by jiaqiluo** [comment]
The fix can be validated on the latest v2.8-head image.
Please refer to [this comment](https://github.com/rancher/rancher/issues/48320#issuecomment-2529240502) for more details.
