### ISSUE TITLE
[BUG] Rancher is unable to connect to GKE created via Terraform

### ISSUE THREAD

**Issue by valaparthvi** [rancher/rancher#48358]
**Rancher Server Setup**
- Rancher version: v2.10-33fc602feb5f335943023ce0645e523ed0d2d7e9-head
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): k3s
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.30.5+k3s1
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): EKS

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Admin
  - If custom, define the set of permissions:

**Describe the bug**

For a GKE cluster provisioned with Terraform, rancher is unable to connect to the cluster, and fails to become active.

**To Reproduce**

```terraform
terraform {
  required_providers {
    rancher2 = {
      source  = "rancher/rancher2"
      version = "6.0.0"
    }
  }
}

provider "rancher2" {
  api_url    = "https://<rancher_hostname>/v3"
  access_key = "token-v7frr"
  secret_key = "m5m4f6nwhtrjh4dgd7kqschvns7sqphpdv7b4pbdmmhdz94dvjjg85"
  insecure   = true
}
resource "rancher2_cloud_credential" "foo-google" {
  name = "foo-google"
  description= "Terraform cloudCredential acceptance test"
  google_credential_config {
    auth_encoded_json = file(<GOOGLE_AUTH_ENCODED_JSON>)
  }
}

resource "rancher2_cluster" "foo" {
  name = "foo"
  description = "Terraform GKE cluster"
  gke_config_v2 {
    name = "foo"
    google_credential_secret = rancher2_cloud_credential.foo-google.id
    zone = "us-central1-c" # Zone argument could also be used instead of region
    project_id = <project-id>
    kubernetes_version = "v1.31.3-gke.1056000"
    network = <network>
    subnetwork = <subnet>
    node_pools {
      initial_node_count = 1
      max_pods_constraint = 110
      name = <node-pool-name>
      version = "v1.31.3-gke.1056000"
    }
  }
}
```
Ref: https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster
```sh
terraform init
terraform apply
```
**Result**
The cluster is provisioned, but does not become Active, I am unable to explore it. It is possible to update the cluster though.

**Expected Result**

Rancher agent should successfully connect to the cluster.

**Screenshots**

![image](https://github.com/user-attachments/assets/cd78695e-1881-4745-9bfe-998ebf79be56)

**Additional context**

**Comment by valaparthvi** [comment]
The above bug is not reproduced if `v3` suffix is removed. I will close it.

**Comment by varsha355** [comment]
I am facing the same issue, I have provisioned a GKE Cluster using rancher terraform provider 
Below is the script i have used to provision the cluster:
terraform {
  required_providers {
    rancher2 = {
      source  = "rancher/rancher2"
      version = "6.0.0"
    }
  }
}

provider "rancher2" {
  api_url    = "https://<rancher_hostname>"
  token_key = "<token-key>"
  insecure   = true
}
resource "rancher2_cloud_credential" "gke" {
  name = "gke"
  description= "Terraform cloudCredential acceptance test"
  google_credential_config {
    auth_encoded_json = file(<GOOGLE_AUTH_ENCODED_JSON>)
  }
}

resource "rancher2_cluster" "gke_cluster" {
  name = "gke-zonal-demo"
  description = "Terraform GKE cluster"
  gke_config_v2 {
    name = "foo"
    google_credential_secret = rancher2_cloud_credential.gke.id
    zone = "us-central1-c" # Zone argument could also be used instead of region
    project_id = <project-id>
    kubernetes_version = "v1.31.3-gke.1056000"
    network = <network>
    subnetwork = <subnet>
    node_pools {
      initial_node_count = 1
      max_pods_constraint = 110
      name = <node-pool-name>
      version = "v1.31.3-gke.1056000"
    }
  }
}

now after terraform apply i am also getting the same isue where the agent is disconnected
