### ISSUE TITLE
docker login to Registry server built from Rancher Catalog is not working

### ISSUE THREAD

**Issue by samhitha30** [rancher/rancher#4836]
*Describe your issue here*

docker login to Registry server built from Rancher Catalog is not working

issue : from UI we are able to create users / teams / namespace, and also able to login to the same web interface.

           unable to login using docker login https://imageregistry.virtusacloud.net from docker machine where my private images are there to upload to this registry server.

Please help me to get this resolved.
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.1.0-dev1` Cattle: `v0.160.3` UI: `v1.0.7` |
|Access|`localauth` `admin`|
|Route|`catalog-tab.launch`|

**Comment by deniseschannon** [comment]
If you're using the catalog entry, it will be best if you submit an issue at [rancher/community-catalog](https://github.com/rancher/community-catalog) and tag the maintainer for that template for help. Steve Shipway. He's very active in that repo and was responsible for contributing the entry. Unforunately, we aren't able to directly support all the community catalog entries.
