### ISSUE TITLE
All containers stopping first during stack upgrade, regardless of batch-size

### ISSUE THREAD

**Issue by nextrevision** [rancher/rancher#4837]
**Rancher Version:**
1.0.1

**Docker Version:**
1.10.2

**OS and where are the hosts located? (cloud, bare metal, etc):**
Cloud, BM

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA (external DB)

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Deploy any stack and run an upgrade with `rancher-compose up --upgrade` without `start_first: true` in the rancher-compose.yml.

**Results:** 
All existing containers will stop first, then the new ones will deploy, regardless of batch-size.

**Expected:**
With using data containers, creating a duplicate stack doesn't solve the issue. I am also unable to use the `start_first` flag due to a limited number of hosts being able to run these containers and explicit port mapping (so multiple of the same service cannot run on the same host). Ideally, there would be an option (if not the default) that when upgrading a service, containers (as per the batch-size) would stop, then the same number of new containers would start, wait for the interval period, then continue on with the next batch instead of stopping all the old, starting all the new (causing downtime).

**Comment by deniseschannon** [comment]
I am unable to reproduce. Using v1.1.0-dev3 and rancher-compose v0.8.2. I started a service with 6 containers and did an upgrade. It upgraded using the default batch-size of 2. 

Can you share your docker-compose.yml and rancher-compose.yml?

What was the scale of your service?

**Comment by nextrevision** [comment]
Working in a local environment trying to replicate. We are definitely seeing it consistently in our live stack, but am having an issue replicating locally.

**Comment by nextrevision** [comment]
Can't seem to replicate, hoping we'll see it resolved in 1.1.0. Will open a new ticket if I end up being able to replicate it.
