### ISSUE TITLE
[main] [BUG] RKE cluster upgrade from v1.30 to v1.31 fails when drain is enabled in upgrade strategy option

### ISSUE THREAD

**Issue by vardhaman22** [rancher/rancher#48374]
**Rancher Server Setup**
- Rancher version: head v2.11-3ce716825fdd85fc05ce5a8fdc97e345455b241b-head
 
- Installation option (Docker install/Helm Chart): docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.30.7-rancher1-1 
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Admin
  - If custom, define the set of permissions:

**Describe the bug**

cluster upgrade from v1.30 to v.131 fails when drain is set to true in upgradeStrategy option.

**To Reproduce**

steps
1. provision a k8s v1.30.7 rke  downstrem cluster.
2. upgrade cluster from k8s v1.30.7 to v1.31.x version while upgrading set  `Drain: yes, Delete emptydir data: yes` in the upgrade strategy section.
3. cluster upgrade is not complete. worker nodes is stuck in draining state.
**Result**
cluster upgrade is no complete and worker node is stuck in draining state
**Expected Result**

cluster upgrade should be successful.
**Screenshots**

![drain_error_upgrade](https://github.com/user-attachments/assets/1ba43ff9-9249-4654-976b-e17520774b3b)
![drain_options](https://github.com/user-attachments/assets/b0237dc3-f7fc-4021-a0ec-d2e0da542e19)

**Additional context**

rancher logs 
`
[ERROR] nodeDrain: kubectl error draining node [vardhaman-worker1] in cluster [c-rn8mr]: See 'kubectl drain --help' for usage
`

**Comment by snasovich** [comment]
Ready to test once there is a passing build on https://github.com/rancher/rancher/tree/main that includes this change.

**Comment by susesgartner** [comment]
Ticket #48374 - Test Results - ✅
---
 
| Scenario | Test Case | Result |
|---|---|---|
| 1. | RKE1 upgrade test | PASS |
 
---
Verified with HA HELM on Rancher `v2.11-b435a2d786c50b03bd1ba7279a6a621ebcd19c84-head`:
---
 
Scenario 1: RKE1 upgrade test 
---

1. Create a 1.30.7 rke1 cluster with drain before delete and delete empty dir set to true
2. Upgrade the cluster from 1.30.7 to 1.31.3
3. Verify that the cluster comes up after the upgrade and no errors are observed
 
Results: the cluster comes up after the upgrade and no errors are observed
 
---
