### ISSUE TITLE
Deleting an rc from the UI gives 500 failure error on the server

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#4838]
**Rancher Version:**

**OS and where are the hosts located? (cloud, bare metal, etc):**Ubuntu, cloud

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**: Kubernetes

**Steps to Reproduce:**
1. Create service with rcs
2. Delete the rc in UI and also issue the delete command from the CLI
[kubernetescontrollerlog.txt](https://github.com/rancher/rancher/files/271032/kubernetescontrollerlog.txt)

soumyas-MacBook-Pro:kubernetes soumya$ kubectl delete rc k8testrc2
Error from server: replicationcontrollers "k8testrc2" not found

**Results:** :The UI freezes and gives a 500 failure error.

Attached are the logs from the kubernetes container

**Comment by alena1108** [comment]
Looks like issue in the kubernetes code base. To recover, kill the kubernetes container, it should get recreated and things should go back to normal. Punting the issue to 1.1

**Comment by alena1108** [comment]
Filed ticket for kubernetes: https://github.com/kubernetes/kubernetes/issues/25820

**Comment by alena1108** [comment]
Moving to release "future" as I am not sure when k8s is going to address the issue. The workaround on the rancher side would be - restart k8s API server container

**Comment by alena1108** [comment]
@sangeethah @soumyalj can you watch is it is still happening on k8s 1.3? I haven't seen it, but may be you will as you run tests pretty often.

**Comment by soumyalj** [comment]
Tested with v1.2.0-pre4-rc7. Did not see this issue. Deletion of rc from UI was fine without any errors.
