### ISSUE TITLE
Not able to add Digital Ocean machine without passing sshPort parameter.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#4839]
Rancher Server version - Build from master.

Steps to reproduce the problem:

Try to add Digital Ocean machine by passing only accessToken.
Machine creation fails with exception - "Unsupported type: float64"

```
       create_args = {"name": random_str(),
                       "digitaloceanConfig": {"accessToken": do_access_key},
                       "engineInstallUrl": do_install_url}
        machine = client.create_machine(**create_args)
```

Machine created has sshPort set to - 22.

```
"digitaloceanConfig": {
"accessToken": "221b602502f01ebb9bb06dd916068cf99dec300d6bd1a5d7491bca7d608564b1",
"image": "ubuntu-15-10-x64",
"region": "nyc3",
"size": "512mb",
"sshPort": 22,
"sshUser": "root",
"userdata": "",
},
```

**Comment by ibuildthecloud** [comment]
@sangeethah setting "sshPort" to "22", does that fix it?

**Comment by sangeethah** [comment]
@ibuildthecloud , setting "sshPort" to "22" in the create_machine fixes it.

**Comment by ibuildthecloud** [comment]
@sangeethah Okay, this is a regression.  I'll look at it

**Comment by sangeethah** [comment]
Tested with Rancher server - v1.1.0-dev2-rc4

Able to add Digital Ocean machine by passing only "accessToken" (without passing sshPort parameter)
