### ISSUE TITLE
[v2.8] bump kubectl in rancher-cis-benchmark chart 

### ISSUE THREAD

**Issue by vardhaman22** [rancher/rancher#48412]
bump kubectl to v1.28.15 in rancher-cis-benchmark chart

**Comment by rishabhmsra** [comment]
Validated on rancher v2.8-head(037a0aa)

- Provisioned RKE1, RKE2 and K3s v1.28.15 node driver clusters.
- Installed CIS 5.7.0 chart.
- Ran v1.8 permissive profile scans.
- All scan passed successfully, hence closing this issue.
