### ISSUE TITLE
create host in the openstack. bootstrap failed.

### ISSUE THREAD

**Issue by 2mind** [rancher/rancher#4843]
**rancher server v1.0.1**

**docker 1.10**

**rancher server on vmware vsphere
create hosts in openstack cloud**

**single node rancher**

**cattle**

run rancher server with: CATTLE_AGENT_INSTANCE_IMAGE, CATTLE_BOOTSTRAP_REQUIRED_IMAGE. I use private docker registry. images name: private_registry:5000/agent-instance:v0.8.1. host is created with the specified parameters (from rancher webui) in openstack but is not registered in the rancher

![1](https://cloud.githubusercontent.com/assets/2377203/15395992/c04da7f8-1de2-11e6-9d69-05e6579663a2.png)

![1](https://cloud.githubusercontent.com/assets/2377203/15395959/9703afaa-1de2-11e6-9489-695b02ed7a1e.png)

https://github.com/rancher/go-machine-service/blob/f402cdda8f6def88d0029d539c68bdd4c34d5635/handlers/bootstrap.go

Thank you.

**Comment by deniseschannon** [comment]
You might have hit an error with our dynamic machine drivers. Basically, there was a condition where the different driver options for other cloud providers were getting mixed up. 

Would you be willing to test out v1.1.0-dev2?

**Comment by deniseschannon** [comment]
@2mind please reopen if you face this version with v1.1.2 (our current stable release).
