### ISSUE TITLE
getting Unauthorized when running docker ps from another docker server that doesn't have rancher

### ISSUE THREAD

**Issue by qgriffith** [rancher/rancher#4844]
**Rancher Version:**
1.0.1
**Docker Version:**
1.10.3
**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu bare metal
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA Rancher with externaldb
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
I am trying to run docker --tls -H=tcp://10.6.100.23:2376 ps from a host that doesn't have rancher installed  in order to get a list of all the docker containers running in rancher. 
**Results:** 
Getting this returned Error response from daemon: {"id":"03186117-9ffd-414f-bb1a-f28196b9efaf","type":"error","links":{},"actions":{},"status":401,"code":"Unauthorized","message":"Unauthorized","detail":null}
**Expected:**
Should have a list of containers. Is there some auth code that is needed to do this?

**Comment by bradjones1** [comment]
I am also running in to this error.

**Comment by deniseschannon** [comment]
With the new Rancher CLI coming in this upcoming release (v1.2.0-pre2), you'll be able to use the `rancher ps -c` to list all containers in a Rancher environment across all the hosts.

In your setups that you are trying to use, how many hosts do you have in your setup. I don't believe this is supported and we would recommend using the Rancher CLI.

**Comment by deniseschannon** [comment]
You can also list the docker output of a host using the Rancher CLI `rancher --host <hostID> docker ps`.
