### ISSUE TITLE
changing the password is not working

### ISSUE THREAD

**Issue by qulo** [rancher/rancher#4845]
**Rancher Version:** v1.1.0-dev1
**Docker Version:** 1.11.1
**OS and where are the hosts located? (cloud, bare metal, etc):** bare metal
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** 12 node rancher, internal db
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle
**Access Control** Local Authentication

**Steps to Reproduce:**
try to change the password by clicking in the upper right
**Results:** 
404 https://foo.bar/v1/projects/xxx/accounts/xxx?include=credentials 
**Expected:**
overlay

**Comment by tfiduccia** [comment]
Version - master 5/19
Verified fixed

@qulo - this is fixed in the next release.
