### ISSUE TITLE
Mesos UI has failures after launching Elastic search catalog 

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#4846]
**Rancher Version:** : Master

**OS and where are the hosts located? (cloud, bare metal, etc):**Ubuntu, Cloud

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**Mesos

**Steps to Reproduce:**
1. Set up Mesos environment.
2. Launch Elastic search catalog.
3. Click on Mesos UI.

The Mesos UI has lot of failiures as seen below:
<img width="1920" alt="screen shot 2016-05-18 at 2 41 56 pm" src="https://cloud.githubusercontent.com/assets/18536626/15403185/a28ee762-1dac-11e6-9d71-7fce48df7f4c.png">

**Comment by soumyalj** [comment]
Note:  When Aurora catalog is launched, it turns to unhealthy state after a couple of minutes. This was found in v1.1.0-dev2-rc5 release.

**Comment by LLParse** [comment]
https://github.com/rancher/community-catalog/pull/155

**Comment by soumyalj** [comment]
Tested with v1.1.0-dev2-rc5. Elastic search catalog launch did not have issues.
