### ISSUE TITLE
Remove the configuration options from mesos catalog launch template

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#4847]
**Rancher Version:**: Master

**OS and where are the hosts located? (cloud, bare metal, etc):**Ubuntu, Cloud

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**: Mesos

**Steps to Reproduce:**
1. Create a Mesos environment
2. Click on any of the mesos catalogs and view details. The template has configurations options which should be removed. They are confusing to the user. The configurations should be set automatically.

**Comment by LLParse** [comment]
https://github.com/rancher/community-catalog/pull/153

**Comment by soumyalj** [comment]
Verified in v1.1.0-dev2-rc5. The configuration options are removed.
