### ISSUE TITLE
Getting  Method not allowed error when trying to add custom registry

### ISSUE THREAD

**Issue by qgriffith** [rancher/rancher#4852]
When trying to add a custom registry using the UI I get a 
Method not allowed error. I am able to login to the registry using docker login on the rancher servers.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.0.1` Cattle: `v0.159.7` UI: `v1.0.5` |
|Access|`github` `admin`|
|Route|`registries.new`|

**Comment by deniseschannon** [comment]
I am unable to reproduce. 

I was able to use v1.0.1, add a Docker hub registry by supplying the my dockerhub email, username and password. 

Can you try to refresh the registry page and do it again?

**Comment by qgriffith** [comment]
I am trying to add a custom registry, one that I created, not a dockerhub one.

**Comment by qgriffith** [comment]
More information, I am able to add the registry to the Default Environment. It only fails when I try to add it to the HA Environment.

**Comment by qgriffith** [comment]
Hey @deniseschannon I wanted to see if you have had a chance to try to reproduce adding a custom registry to the HA Environment. I am able to add registries to all other non-ha environments with out any issue.

**Comment by qgriffith** [comment]
I looked at the audit log and it appears a lot more attributes are being passed to the create registry API when a HA Env is used.  For example this is the failing call from the GUI

`{
  "serverAddress": "docker-registry.example.com",
  "created": null,
  "description": null,
  "name": null,
  "removed": null,
  "uuid": null,
  "type": "registry",
  "externalId": null,
  "driverName": null,
  "kind": null
}`

On non HA Env I can add a registry and a far lot less is passed for example

`{
  "serverAddress": "docker-registry.example.com",
  "description": null,
  "name": null
}`

**Comment by deniseschannon** [comment]
We were unable to reproduce this. We had a HA setup and had no issues adding a registry inside the HA environment.

Please note that we don't really recommend adding hosts/services inside the environment that has the HA setup. It'd be better if you created another environment for services/applications.

**Comment by deniseschannon** [comment]
@qgriffith Are you still facing issues with this setup? Please re-open if you are.
