### ISSUE TITLE
[BUG] Sock Bind error in Apache Functions Python in local

### ISSUE THREAD

**Issue by jmalbarran** [rancher/rancher#48539]
**Rancher Server Setup**
- Rancher version: Rancher Desktop 1.16.0
- Installation option (Docker install/Helm Chart): brew install rancher
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details: N/A
- Mac Sequoia 15.1.1

**Information about the Cluster**
- Kubernetes version: N/A - Rancher Desktop
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- Tested starting Rancher Desktop with administrative privileges too, no change

**Describe the bug**
I'm testing Apache Functions and I'm trying to test my function locally

For this, I have started the local server with
```
fn start --log-level DEBUG --port 8080
```

and I'm trying to create, deploy and invoke a test function with

```
fn use context default
fn update context registry mylocalregistry

fn -v init --runtime python fn-local

cd fn-local

fn -v deploy --create-app --app app-local --local
fn invoke app-local fn-local
```

**Result**

The invocation (last line) fails with `Error invoking function. status: 502 message: Container failed to initialize, please ensure you are using the latest fdk and check the logs`

In the server logs I see that the problem is a python socket creation

```
...
time="2024-12-21T19:48:40Z" level=debug msg="  File \"/python/fdk/__init__.py\", line 62, in start\n" app_id=01JFN9NJFZNG8G00GZJ0000001 container_id=01JFNC7J7ZNG8G00GZJ0000003 fn_id=01JFNC6GG1NG8G00GZJ0000001 image="mylocalregistry/fn-local:0.0.2" tag=stderr
time="2024-12-21T19:48:40Z" level=debug msg="    sock.bind(phony_socket_path)\n" app_id=01JFN9NJFZNG8G00GZJ0000001 container_id=01JFNC7J7ZNG8G00GZJ0000003 fn_id=01JFNC6GG1NG8G00GZJ0000001 image="mylocalregistry/fn-local:0.0.2" tag=stderr
time="2024-12-21T19:48:40Z" level=debug msg="PermissionError: [Errno 1] Operation not permitted\n" app_id=01JFN9NJFZNG8G00GZJ0000001 container_id=01JFNC7J7ZNG8G00GZJ0000003 fn_id=01JFNC6GG1NG8G00GZJ0000001 image="mylocalregistry/fn-local:0.0.2" tag=stderr
time="2024-12-21T19:48:40Z" level=info msg="hot function terminated" app_id=01JFN9NJFZNG8G00GZJ0000001 container_id=01JFNC7J7ZNG8G00GZJ0000003 cpus= error="container exit code 1" fn_id=01JFNC6GG1NG8G00GZJ0000001 idle_timeout=30 image="mylocalregistry/fn-local:0.0.2" memory=256

...
```

**Expected Result**
Execution of function

**Screenshots**
N/A

**Additional context**

**Comment by pgonin** [comment]
Sorry you should file this one with Rancher *Desktop* GH
https://github.com/rancher-sandbox/rancher-desktop
