### ISSUE TITLE
[BUG] Rancher-Backups S3 Skip TLS verifications applied but backup object return https response

### ISSUE THREAD

**Issue by seab4ng** [rancher/rancher#48540]
**Rancher Server Setup**
- Rancher version:  v2.10.0
- Installation option Docker install
- Proxy/Cert Details: none

**Describe the bug**
Rancher-Backups configured with insecure "Skip TLS Verifications" checkbox but yet error of: "server gave http response to https client"

**Result**

**Expected Result**
Accepting insecure http from the S3 bucket server. this case Minio

**Comment by mallardduck** [comment]
Hi, I see you set this solved/closed but want to answer for prosperity.  
That way if any others come upon this they will see an explanation.

The rancher-backup tool is intended to require HTTPS between S3 buckets. There are a high chance that the backup data contains sensitive information so this protects the data in transit. The minimal expectation is that one would have a self-signed cert setup on their S3 service. In that scenario the Skip TLS Verifications option could save the effort of verifying the self-signed, or self-operated CA, origin certificate.

**Comment by lucatr** [comment]
I think this decision should be left to the user. There are many different contexts of application and following your argumentation you may as well require a trusted certificate. That's why this is usually configurable.
