### ISSUE TITLE
kubernetes menu hover issue

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4854]
**Version:** 

**Steps to Reproduce:**
- [ ] Move mouse over namespace then environment
![image](https://cloud.githubusercontent.com/assets/11514927/15409796/3be3081c-1dcb-11e6-91a2-c73671cddc8b.png)

- [ ] Move mouse over environment then namespace
![image](https://cloud.githubusercontent.com/assets/11514927/15409824/66b5c80e-1dcb-11e6-96a3-7d531f7011f3.png)

**Comment by tfiduccia** [comment]
Version - master 2-24
Not fixed
When I move from Environment to Namespace or from Namespace to Kubernetes, the second menu item comes up then goes away.

**Comment by vincent99** [comment]
I think this was fixed in dev3

**Comment by deniseschannon** [comment]
Verified in v1.1.0-dev4, that this is no longer happening.
