### ISSUE TITLE
Machine Driver UI changes

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4856]
**Version:** master 5.19

- [x] Move machine drivers out of setting page to own page under Admin
- [ ] New page will look like catalog page.  Each machine driver will be in a box and contain icon, version drop-down (if needed) and Activate/deactivate button.
- [ ] Folder in Git to allow users to add driver & icon to machine page
- [x] Still need a Add machine driver button to allow customers to add individual driver (we can add our own generic icon to those).

**Comment by will-chan** [comment]
Closing feature issue.  File bugs in separate issues.
