### ISSUE TITLE
"connected" text for kubectl is half in and out of box

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4857]
**Version:** master 5.19

**Steps to Reproduce:**
1.  Setup kubernetes environment
2.  Add host and wait for it to fully setup
3.  Go to Kubectl screen and scroll to bottom

**Results:** 
![image](https://cloud.githubusercontent.com/assets/11514927/15410494/ed9ad8a2-1dce-11e6-8355-8b730a884b0e.png)

**Expected:**
Should either be in or out of the white frame box

**Comment by lvuch** [comment]
https://github.com/rancher/ui/pull/697

**Comment by tfiduccia** [comment]
Version - master 6/9
Verified fixed
