### ISSUE TITLE
About box need to be formatted for mobile

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4858]
**Version:** master 5.19

**Steps to Reproduce:**
1.  Resize your browser for mobile
2.  Click on about to bring it up

**Results:** 
![image](https://cloud.githubusercontent.com/assets/11514927/15411020/035b8116-1dd2-11e6-966e-d1acd3bba0a6.png)

**Expected:**  Nicely formatted

**Comment by lvuch** [comment]
https://github.com/rancher/ui/pull/677

**Comment by tfiduccia** [comment]
Version - master 5-24
Verified fixed
