### ISSUE TITLE
kubernetes-ingress-lbs stack created in system folder

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4860]
**Version:** master 5.19

**Steps to Reproduce:**
1.  Add a kubernetes environment & add at least one host
2.  Wait for all services to start
3.  Go to Kubernetes - System screen

**Results:** 
![image](https://cloud.githubusercontent.com/assets/11514927/15412430/46abb59e-1ddc-11e6-85d1-9025b1271857.png)

**Expected:**  The stack should be created on-demand instead of on creation of kubernetes environment

**Comment by will-chan** [comment]
@alena1108 is this still an issue we want to address?

**Comment by tfiduccia** [comment]
Version - master 2/7
This is no longer an issue
