### ISSUE TITLE
Upgrade to Docker Machine v0.7

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#4862]
Per https://forums.rancher.com/t/rancher-created-centos-7-hosts-running-docker-v1-11-1/2838/9

Even with the docker install URL, RHEL/CentOS hosts will be provisioned with latest Docker due to how docker-machine v0.6.

Per @vincent99: In docker-machine 0.6 the redhat provisioner (and only that one, others work) ignores the engine-install-url option entirely and always just uses the standard get.docker.com one, which gives you whatever happens to be the newest release today (1.11.1). This was fixed in machine 0.7 ( https://github.com/docker/machine/issues/31451 ), but we don't package that yet.

0.6: https://github.com/docker/machine/blob/v0.6.0/libmachine/provision/redhat.go#L113
0.7: https://github.com/docker/machine/blob/v0.7.0/libmachine/provision/redhat.go#L118

**Comment by vincent99** [comment]
Note that this also requires rewriting the Azure UI, as the 0.7 provider is completely different (and hopefully better).

**Comment by tfiduccia** [comment]
Version - master 8/25
Retested machine driver - Verified
