### ISSUE TITLE
Failed to load resource: Origin http://domain is not allowed by Access-Control-Allow-Origin.

### ISSUE THREAD

**Issue by Dreampie** [rancher/rancher#4863]
```shell
docker run -d --restart=always -p 8080:8080 rancher/server
```

nginx domain this ip:port,get cross domain error
![v s ynhd41cb9 q 9 5wm](https://cloud.githubusercontent.com/assets/3667080/15421738/7a2e2e94-1ea7-11e6-8345-92c198ebe95a.jpg)

**Comment by deniseschannon** [comment]
Could you provide more details of your setup? 

It sounds like you are trying to set up some kind of nginx in front of Rancher. Can you share your nginx configuration?

**Comment by Dreampie** [comment]
```shell
server {
  listen 80;
  server_name `domain_name`;
  index index.html index.jhtml index.htm default.html default.htm;
  root html;

  access_log /var/log/nginx/rancher_access.log;
  error_log /var/log/nginx/rancher_error.log;

  location / {
    proxy_pass http://192.168.60.61:8080/;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }
}

```

**Comment by vincent99** [comment]
You're not proxying the Host header.  The server generates absolute URLs so it needs to know the entirety of the original request URL.  This is for SSL but the same basics apply, http://docs.rancher.com/rancher/latest/en/installing-rancher/installing-server/basic-ssl-config/#example-nginx-configuration

**Comment by Dreampie** [comment]
yes,it's ok,thanks
