### ISSUE TITLE
 When disable Access Control after adding some new accounts, environment management behave strange.

### ISSUE THREAD

**Issue by wangweihong** [rancher/rancher#4867]
**Rancher Version:**
v1.0.1
**Docker Version:**
1.10.3
**OS and where are the hosts located? (cloud, bare metal, etc):**
centos 7.2
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
1. Enable Local Authentication,and  add some accounts, also add new accounts to default environment.
2. Disable Local Authentication.
3. Edit default environment, change its Description,Click "Save"

**Results:**
  Waring message prints:
  "**There are no active environments. You will need to create or activate one before you can do anything else**."
   All top-level menus(e.g. Application, Catalog) disappear.

**Comment by deniseschannon** [comment]
I was unable to reproduce. Are you sure you didn't accidentally deactivate your environment, which is right next to the "Edit" on the drop down menu?

**Comment by wangweihong** [comment]
@deniseschannon 
1. Enable  Local Authentication
![image](https://cloud.githubusercontent.com/assets/18753267/15446351/b2a82226-1f50-11e6-9124-e750b15f1f65.png)
2. Add some accounts
![image](https://cloud.githubusercontent.com/assets/18753267/15446353/d66d8778-1f50-11e6-86d3-271ab10fe96d.png)
3. Add these accounts to Default environment
![image](https://cloud.githubusercontent.com/assets/18753267/15446354/e27ad822-1f50-11e6-9588-51cb003febf0.png)
4.Disable Local Authenticatoin
![image](https://cloud.githubusercontent.com/assets/18753267/15446355/ec072fe4-1f50-11e6-8634-adb00a90827e.png)
5. Edit Default environment
![image](https://cloud.githubusercontent.com/assets/18753267/15446360/1379915c-1f51-11e6-9258-8d3f499cec62.png)
6. Error appear
![image](https://cloud.githubusercontent.com/assets/18753267/15446361/24e0daae-1f51-11e6-9c35-07ee7a13ef6c.png)

If I click "Swith to this environment" Icon, everything get right.  But once I edit Default environment, error happens again.

**Comment by deniseschannon** [comment]
I am still unable to v1.1.0-dev3. I followed your steps exactly, but my environment doesn't change. 

Can you try with the latest release?

**Comment by deniseschannon** [comment]
@wangweihong Please re-open if you still see this issue.
