### ISSUE TITLE
Uppercase in tag breaks rancher-compose

### ISSUE THREAD

**Issue by guzmo** [rancher/rancher#4868]
I'm sorry if this is stated somewhere but I've tried to find a similar issue or any documentation about this without any luck.

**Rancher Version:**
1.0.1

**Docker Version:**
Tried on both 1.10.3 and 1.11.1

**OS and where are the hosts located? (cloud, bare metal, etc):**

Tested on MAC and Linux from local machines.
Rancher running in datacenter on VSphere6 and CentOS7 VMs

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

HA Rancher with external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

Swarm

**Steps to Reproduce:**

rancher-compose -f some/docker-compose.yml up will fail for ex: image:dev-SNAPSHOT

Tested with rancher-compose version 0.7.4 and v0.8.2-rc1

**Results:** 

ERRO[0005] Failed to start: my-service : Bad response statusCode [422]. 
Status [422 Unprocessable Entity]. Body: [code=InvalidReference, fieldName=imageUuid] from [https://rancher.domain.com/v1/services] 

**Expected:**

That the services should start.

**Comment by guzmo** [comment]
Might be something else wrong with the name, it works with easier names.

repository.repositoryUrl.domainName/image works but 
repository.repositoryUrl.domainName/com/test/image doesn't work

**Comment by deniseschannon** [comment]
Can you share your docker-compose.yml? 

Does your registry actually use uppercase for tags? 

We expect image names to be in the following format:

`[registry-name]/[namespace]/[imagename]:[version]`

**Comment by guzmo** [comment]
I've tried with very easy docker-compose files with only one service and the image tag.

```
  test:
    image: registry-project.registry.url/our/image:dev-SNAPSHOT
```

[registry-name]/[namespace]/[imagename]:[version] is as we have it.

or more like 

[repository].[registry-url]/[namespace]/[imagename]:[version]

**Comment by guzmo** [comment]
This is the error we are getting.

Bad response statusCode [422]. Status [422 Unprocessable Entity]. Body: [code=InvalidReference, fieldName=imageUuid] from [https://rancher.domain.com/v1/projects/1a22/services])

**Comment by guzmo** [comment]
If i run docker pull [registry-project].[registry.domain.local]/our/apps/app-i-want:dev-SNAPSHOT on the HOST I want it on it starts to download the image. So nothing wrong there. Its just when adding it from a Stack(docker-compose file) it gives this error instead

**Comment by deniseschannon** [comment]
Have you tried also this same image in the UI? The error message looks like the API is complaining but I want to confirm it's the API and not rancher-compose specific.

**Comment by guzmo** [comment]
Seems it was the nested namespace.
