### ISSUE TITLE
feature request: mercurial community catalogs

### ISSUE THREAD

**Issue by kkvilekval** [rancher/rancher#4869]
**Rancher Version:**
1.0.1
**Docker Version:**
1.11
**OS and where are the hosts located? (cloud, bare metal, etc):**
debian 
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
cattle
**Steps to Reproduce:**
NA

We're a mercurial house so don't have a git server running.. would it be possible to add mercurial support to the catalog-server https://github.com/rancher/rancher-catalog-service/blob/master/manager/catalog.go

**Comment by will-chan** [comment]
Yes, if you or someone in the community can contribute a catalog item, that would be fantastic.  This is not something we are likely to add ourselves as we are not an expert int his and cannot offer the support.  We can definitely assist placing the app in the catalog assuming there is a Dockerized version of this app readily available.
