### ISSUE TITLE
Missing translation for k8 container name.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#4870]
Rancher Version - v1.1.0-dev2-rc4

<img width="1204" alt="screen shot 2016-05-20 at 10 26 35 am" src="https://cloud.githubusercontent.com/assets/4266958/15436281/ef5dd21e-1e75-11e6-95fe-48fed87ca64a.png">

**Comment by tfiduccia** [comment]
Version - master 2-24
Verified fixed
