### ISSUE TITLE
Proposal: Support topology server, blade, room

### ISSUE THREAD

**Issue by sebglon** [rancher/rancher#4873]
How can i define topology infra and use it to compose scheduling.
I want to scale over two datacenter and be shure that scaling is made on multi server, blade and room or other peace of topology.

I show how Ceph can manage define topology with CrushMap.

Is-it possible to add this new feature to increase High Aviability?

**Comment by deniseschannon** [comment]
You can try to add different host labels to your hosts and schedule based on the labels.

http://docs.rancher.com/rancher/latest/en/rancher-compose/scheduling/

Would that satisfy what you're aiming to do?

**Comment by sebglon** [comment]
This is not exaxtly that i want. Because
If i have this topo
DC1,Room1,Blade1
DC1,Room1,Blade2
DC1,Room2,Blade1
DC1,Room2,Blade2
DC2,Room1,Blade1
DC2,Room1,Blade2
When i scaling, i whant that my service is deployed on DC1 and DC2 but not on Room2 for DC2 and with more complexe topo.

If i scale 10, ia want 7 on DC1 and 3 on DC2 becaude CPU and RAM on DC2 is lower than DC1.

How can i optain this?

**Comment by deniseschannon** [comment]
Currently you won't be able to do that level of detailing for scheduling for a single service. 

Instead, you could create multiple services that are scheduled for your group of hosts that you want and scale those services based on how many containers you want in each datacenter. For example, service1 would be for the hosts in DC1 and service2 would be for the hosts in DC2. This allows you to scale DC1 to 7 containers and DC2 to 3 containers. 

Then, you could add a service alias that point to these different groups of services and use the service alias for load balancer targets. 

In the example,  you could create a service alias that points to service1 and service2. When you load balance against the service alias, we'd target all 10 containers.

**Comment by deniseschannon** [comment]
@sebglon Please let me know if you have additional questions based on my suggestions.

**Comment by azbarcea** [comment]
`erata:`
<s>http://docs.rancher.com/rancher/latest/en/rancher-compose/scheduling/</s> moved to: 
http://docs.rancher.com/rancher/latest/en/cattle/scheduling/
