### ISSUE TITLE
[rancher-compose] up --upgrade retries limit

### ISSUE THREAD

**Issue by artburkart** [rancher/rancher#4875]
**Rancher Version:**

``` bash
rancher-compose --version
rancher-compose version v0.7.3-rc2
```

**Docker Version:**

``` bash
docker --version
Docker version 1.10.3, build 20f81dd
```

**OS and where are the hosts located? (cloud, bare metal, etc):**

``` bash
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.2 LTS
Release:    14.04
Codename:   trusty
```

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Default, no HA

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Create a container that cannot successfully start

**Results:** 
`rancher-compose up -f docker-compose.yml -p app_name up -d --force-upgrade` hangs, trying to start the container forever; requires manual intervention to stop.

**Expected:**
There should be a way to indicate how many times `rancher-compose` should try to restart the container before declaring the upgrade a failure.

Hi, I'm not sure if this is a self-inflicted problem or simply functionality that hasn't been implemented yet. I'm trying to set up an automated pipeline that deploys containers to my rancher hosts using the above `rancher-compose` command, but I need to do some pretty wonky things to get it to rollback. 

For example, I'm wrapping the `rancher-compose` command in a timeout, so I can arbitrarily decide to rollback my attempted upgrade via the Rancher API after the command fails to exit. It would be nice if there was a more event-driven way to do this (perhaps I can check the number of attempts for an upgrade via the API?), so I didn't have to suffer too much downtime. 

This all said, perhaps I should be using blue-green deployments for this? If you have any input, it would be super helpful. I've found Rancher to be a great platform thus far, but this is starting to become a show-stopper for me. I'm happy to work on a PR, if it comes to that. Cheers!

**Comment by deniseschannon** [comment]
Rancher's design has always been to continually try and schedule containers of a service. We never "give up" on scheduling a service but have backed off as it continues to error out. 

Despite our design, I can completely understand your use case and need to "give up" an attempt within rancher-compose. 

We always welcome PRs. :)

**Comment by artburkart** [comment]
For anyone else who is struggling with this, here is the snippet (courtesy of @VDuda) we're using for now to get this off the ground. Please note, the timeout prevents a failed deployment from rolling back for a full 5 minutes (we wanted to minimize false positives), which is an absolute 'mare unless you're using something like blue/green deployments or you have a mechanism to prevent a switch-over at the lb layer until you know, for a fact, your container is up.

```bash
timeout 360 rancher-compose -f docker-compose.yml -p $APPLICATION_NAME up -d --force-upgrade
error_code=$?

if [ "$error_code" -eq "0" ]; then
  echo "SUCCESS: Confirming Upgrade"
  rancher-compose -p $APPLICATION_NAME up -d --upgrade --confirm-upgrade
else
  echo "FAILURE: Rolling back"

  PROJECT_JSON=`curl -s --ssl -u "${RANCHER_ACCESS_KEY}:${RANCHER_SECRET_KEY}" \
    -X GET \
    -H 'Accept: application/json' \
    -H 'Content-Type: application/json' \
  "https://rancher.example.com/v1/projects/{$ENV_ID}/environments?name=${APPLICATION_NAME}&sort=id"`

  # Gets the id for the project from Rancher API
  PROJECT_ID=`echo "$PROJECT_JSON" | jq -r '.data[].id' `

  # Gets the links to the services (containers)
  SERVICES_LINK=`echo "$PROJECT_JSON" | jq -r '.data[].links.services' `

  # Grabs all the services for the project that are stuck in an upgrading state
  SERVICES_TO_CANCEL=`curl -s --ssl -u "${RANCHER_ACCESS_KEY}:${RANCHER_SECRET_KEY}" \
    -X GET \
    -H 'Accept: application/json' \
    -H 'Content-Type: application/json' \
  "${SERVICES_LINK}?state=upgrading" \
  | jq -r '.data[] | select(.state == "upgrading") | .actions.cancelupgrade'`

  # Loop through the services that need to be cancelled, and cancel them
  for i in $(echo "${SERVICES_TO_CANCEL}"); do
    SERVICE=`curl -s --ssl -u "${RANCHER_ACCESS_KEY}:${RANCHER_SECRET_KEY}" \
    -X POST \
    -H 'Accept: application/json' \
    -H 'Content-Type: application/json' \
    -d '{}' \
  "${i}" | jq -r '.id'`
    echo "Sent stop upgrade to $SERVICE"
  done

  # Checks the Rancher API to determine whether the services have been cancelled or not
  CONDITIONAL="curl -s --ssl -u \"${RANCHER_ACCESS_KEY}:${RANCHER_SECRET_KEY}\" \
    -X GET \
    -H 'Accept: application/json' \
    -H 'Content-Type: application/json' \
  \"${SERVICES_LINK}\" \
  | jq -r '.data[] | select(.state == \"canceling-upgrade\")'"

  # When all the services have been cancelled, we stop checking if they've been cancelled
  while [ -n "`eval $CONDITIONAL`" ]; do
    echo "Waiting for canceling-upgrade to finish..."
    sleep 5
  done

  # Get all the services that need to be rolled back
  SERVICES_TO_ROLLBACK=`curl -s --ssl -u "${RANCHER_ACCESS_KEY}:${RANCHER_SECRET_KEY}" \
    -X GET \
    -H 'Accept: application/json' \
    -H 'Content-Type: application/json' \
  "${SERVICES_LINK}" \
  | jq -r '.data[] | select(.state == "canceled-upgrade") | .actions.rollback'`

  # Roll them back
  for i in $(echo "${SERVICES_TO_ROLLBACK}"); do
    SERVICE=`curl -s --ssl -u "${RANCHER_ACCESS_KEY}:${RANCHER_SECRET_KEY}" \
    -X POST \
    -H 'Accept: application/json' \
    -H 'Content-Type: application/json' \
    -d '{}' \
  "${i}" | jq -r '.id'`
    echo "Rolled back $SERVICE"
  done
fi
```

@deniseschannon - I'll take a crack at a PR when I have some room to breathe :) Cheers!

**Comment by borntorock** [comment]
@artburkart Did you got a chance to raise a PR to resolve this issue in the upstream?

**Comment by 0atman** [comment]
Really could use this functionality, we DDOS ourselves whenever machines are bad, and in huge clusters, that's far too often! Any workarounds at the moment? I'm not able to add this functionality to rancher myself, with apologies.

**Comment by 0atman** [comment]
Does rancher overwrite the underlying docker flag in this regard, `--restart=on-failure:10`?
Can we add it back?

**Comment by 0atman** [comment]
Also, a year later, is this still the policy?

> Rancher's design has always been to continually try and schedule containers of a service. We never "give up" on scheduling a service but have backed off as it continues to error out.

**Comment by 0atman** [comment]
"maximumRetryCount" is mentioned in many places, but I can't seem to set it, is it exposed by rancher?

**Comment by borntorock** [comment]
@0atman Where do you see this option `maximumRetryCount`?

**Comment by 0atman** [comment]
Docker config

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
