### ISSUE TITLE
K8s Catalog Header is not showing up automatically after K8s system stack is complete

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#4877]
**Rancher Version:**
v1.1.0-dev2-rc4
**Docker Version:**
1.10.3
**OS and where are the hosts located? (cloud, bare metal, etc):**
ubuntu
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
k8s
**Steps to Reproduce:**
1. add hosts using DO into environment

**Results:** 
 K8S stack finishes but catalog header item never appears

**Expected:**
Catalog header should show up automatically after k8s system stack is up

**Comment by tfiduccia** [comment]
Version - master 5-24
Verified fixed

**Comment by tfiduccia** [comment]
Version - master 5-24
re-opening.
If I'm not on the waiting page when services are finished the catalog menu does not show up.

**Comment by tfiduccia** [comment]
version - master 5-26
Verified fixed - catalog is up all the time and from everywhere.  Exception - if Kubernetes is not finished setting up, clicking on catalog will take you to the waiting page.
