### ISSUE TITLE
ip addresses for deleted services are not removed from RancherDNS in kubernetes cluster

### ISSUE THREAD

**Issue by bnusunny** [rancher/rancher#4878]
**Rancher Version:** 

1.0.0

**Docker Version:** 

1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):** 

rancheros, virtualbox

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** 

single node rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

Kuberentes

**Steps to Reproduce:**

1. setup a Kubernetes environment, wait for kubernetes cluster get ready

2. deploy the guestbook example, verify it works. check the rancher dns answer for redis-master service. 

3. delete redis-master service through kubectl 

4. recreate the redis-master service, and recheck the rancher dns answer for redis-master service.

**Results:** 

2 IP addresses were presented in the answer.json for redis-master service: the one for the deleted service and one for the current service. 

The IP for the deleted service should be removed. Otherwise, the service discovery through DNS will be broken. half of the time the client will get the IP of the deleted service. 

**Expected:**

only one IP address was presented in the answer.json for redis-master service: the one for the current redis-master service. 

We can't use Rancher created kubernetes cluster due to this issue. We have to go through the painful process to create the kubernetes cluster from scratch.

**Comment by alena1108** [comment]
@bnusunny I can't reproduce the issue with the steps given on the latest build; could you check the steps below to see if anything is missing. Also can you check if when you remove redis-master service, it gets removed from rancher db:

```
select id, name, state from service where name='redis-master';
```


1) Created guestbook app from catalog.
2) Checked dns resolution for redis-master service:

```
root@bc2616652247:/# dig redis-master.default.svc.cluster.local.

.............

;; ANSWER SECTION:
redis-master.default.svc.cluster.local.	1 IN A	10.43.246.158

...........
```
3) deleted the service using kubectl:

```
 kubectl delete service redis-master
```

verified that redis-master is no longer resolvable:

```
dig redis-master.default.svc.cluster.local.

; <<>> DiG 9.9.5-3ubuntu0.8-Ubuntu <<>> redis-master.default.svc.cluster.local.
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 50548
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;redis-master.default.svc.cluster.local.	IN A

;; AUTHORITY SECTION:
.			1654	IN	SOA	a.root-servers.net. nstld.verisign-grs.com. 2016052300 1800 900 604800 86400

;; Query time: 0 msec
;; SERVER: 169.254.169.250#53(169.254.169.250)
;; WHEN: Mon May 23 17:46:03 UTC 2016
;; MSG SIZE  rcvd: 131
```

4) Added redis-master service back (via UI, using the service template below):

```
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2016-05-23T17:46:27Z
  labels:
    name: redis-master
  name: redis-master
  namespace: default
  resourceVersion: "469"
  selfLink: /api/v1/namespaces/default/services/redis-master
  uid: 4693db8a-210e-11e6-a8a2-02f81793ba03
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    name: redis-master
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

verified that redis-master service is resolvable to the new ip address now:

```
dig redis-master.default.svc.cluster.local.
...........
;; ANSWER SECTION:
redis-master.default.svc.cluster.local.	1 IN A	10.43.48.198

..........
```

checked answers.json file as well, it has just one ip address for redis-master service:

```
,
		"redis-master.default.svc.cluster.local.": {
			"answer": ["10.43.48.198"]
		},
```

**Comment by alena1108** [comment]
Here is the snippet from rancher db showing that the old rancher-master service was removed, and new one recreated with a different vip. And that vip is the vip I saw in final dns resolution:

```
mysql> select id, name, state, vip from service where name='redis-master' and id > 20;
+----+--------------+---------+---------------+
| id | name         | state   | vip           |
+----+--------------+---------+---------------+
| 22 | redis-master | removed | 10.43.246.158 |
| 23 | redis-master | active  | 10.43.48.198  |
+----+--------------+---------+---------------+
```

**Comment by alena1108** [comment]
@sangeethah could you test it on dev4?

**Comment by soumyalj** [comment]
Followed the above steps and verified on master.
