### ISSUE TITLE
Nvidia Docker

### ISSUE THREAD

**Issue by cusspvz** [rancher/rancher#4883]
[Nvidia's docker](https://github.com/NVIDIA/nvidia-docker) for running CUDA containers on top of their GPUs.
Is it worth to be supported by Rancher so it can target CUDA-based containers?

**Comment by kkvilekval** [comment]
We really need this for our machine-learning containers.   I've been looking around for work-arounds. Do you have suggestions?

**Comment by willseward** [comment]
I agree that this would be useful. The university is looking into Docker solutions for their GPU workloads.

**Comment by ianseyer** [comment]
+1

**Comment by kgk** [comment]
Seems like the people at nvidia are also working on this : 
https://github.com/NVIDIA/nvidia-docker/issues/39

I am trying to use some of the suggestions there, but am running into an issue with 
the external created docker volume.  Rancher-compose is complaining that it cannot find the volume.

version: '2'
volumes:
  nvidia_driver:
    external:
      # name: ${NVIDIA_DRIVER_VOLUME}
      name: nvidia_driver_375.66
services:
  caffe:
    command: caffe   device_query -gpu all
    image: nvidia/caffe
    # These were found with  curl -s localhost:3476/docker/cli on host
    devices:
      - /dev/nvidiactl
      - /dev/nvidia-uvm
      - /dev/nvidia-uvm-tools
      - /dev/nvidia0
      - /dev/nvidia1
      - /dev/nvidia2
      - /dev/nvidia3
    volumes:
      - nvidia_driver: /usr/local/nvidia:ro
    labels:
      io.rancher.scheduler.affinity:host_label: hostname=gpuhost


$rancher-compose up

INFO[0000] Creating stack caffe                         
FATA[0000] Volume nvidia_driver declared as external, but could not be found. Please create the volume manually and try again. 

So the question is.. when does it check the volume .. I did create a volume named nvidia-docker on the host gpuhost.

**Comment by kgk** [comment]
I got something working with rancher-compose

1.  install the nvidia-docker-plugin on your gpu host

2. use curl to get  command line arguments to run a docker command

```
$  curl -s localhost:3476/docker/cli
--volume-driver=nvidia-docker --volume=nvidia_driver_375.66:/usr/local/nvidia:ro --device=/dev/nvidiactl --device=/dev/nvidia-uvm --device=/dev/nvidia-uvm-tools --device=/dev/nvidia0 --device=/dev/nvidia1 --device=/dev/nvidia2
```

 3. use rancher cli to create a named volume based on what you find 

`$ rancher volume create nvidia_driver_375.66 --driver nvidia-docker
`
4.  Specify the the external volume (from a remote host) in docker-compose

```
$ cat docker-compose.yml

version: '2'
volumes:
  nvidia_driver_375.66:
    external: true
services:
  caffe:
    command: caffe   device_query -gpu all
    image: nvidia/caffe
    # These were found with  curl -s localhost:3476/docker/cli on host
    devices:
      - /dev/nvidiactl
      - /dev/nvidia-uvm
      - /dev/nvidia-uvm-tools
      - /dev/nvidia0
      - /dev/nvidia1
    volumes:
      - nvidia_driver_375.66:/usr/local/nvidia:ro
    labels:
      io.rancher.scheduler.affinity:host_label: hostname=caffeine

```

5. use rancher-compose 
```
$ rancher-compose up 
WARN[0000] A newer version of rancher-compose is available: 0.12.5 
INFO[0000] [0/1] [caffe]: Creating                      
INFO[0000] [0/1] [caffe]: Created                       
INFO[0000] [0/1] [caffe]: Starting                      
INFO[0000] [1/1] [caffe]: Started                       
caffe-caffe-1 | 2017-06-21T04:06:47.724041105Z I0621 04:06:47.723844     1 common.cpp:203] Maximum dimension of block:    1024, 1024, 64
caffe-caffe-1 | 2017-06-21T04:06:47.724043890Z I0621 04:06:47.723846     1 common.cpp:206] Maximum dimension of grid:     2147483647, 65535, 65535
caffe-caffe-1 | 2017-06-21T04:06:47.724046895Z I0621 04:06:47.723850     1 common.cpp:209] Clock rate:                    1076000
....

```

**Comment by BohdanTkachenko** [comment]
I was able to do what @kgk suggested, but container stuck in "Activating" phase. However, if I log in into machine manually and see container's logs, I can see that it was started successfully

**Comment by hc000** [comment]
Would like to say we are also looking into this feature.

**Comment by cloud-rocket** [comment]
+1

**Comment by raviv** [comment]
@BohdanTkachenko I have the same problem. Did you manage to solve it?

**Comment by BohdanTkachenko** [comment]
@raviv I was able to do it only in half-automatic way. I mean that after creating a host I need to install some dependencies there manually (actually I think it's possible to create AMI with pre-installed deps). Here is my script to install deps: https://gist.github.com/BohdanTkachenko/ce712410ddff53dad0fdcde1e35c9916

You can install it on your host with a single command: `wget -O - https://git.io/vdM98 | sudo bash`

Also, when running any containers that require GPU on this machine, you need to specify a volume `nvidia_driver_384.90:/usr/local/nvidia:ro`

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

**Comment by guhcampos** [comment]
> With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

This does not answer the question "Does Rancher support deploying a GPU-enabled Kubernetes cluster?" 

I am currently interested in deploying such cluster and Google brings me here, and I still don't know, therefore I'll axe Rancher from my list of possibilities. That's bad for business.

**Comment by user-name-is-taken** [comment]
It's probably worth noting that the rancher docs mention GPUs here https://rancher.com/docs/rancher/v2.x/en/v1.6-migration/schedule-workloads/

**Comment by dericdesta** [comment]
[Here](https://rancher.com/blog/2020/introduction-to-machine-learning-pipeline) is a fairly up to date official blog post about setting up Kubeflow (including CUDA/Nvidia docker) on a Rancher cluster.
