### ISSUE TITLE
Unable to reactivate a deactivated environment through Rancher API

### ISSUE THREAD

**Issue by adaikal** [rancher/rancher#4885]
Rancher Version: 1.0.1

Docker Version:

Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64

OS and Location: Ubuntu 14.04, Openstack kilo

Setup Details: Single node and external DB

Environment Type: Cattle

Steps to Reproduce:
- Just create a cattle environment
- Go to rancher_server/v1/projects
- Select deactivate from actions for one of the environments (http://rancher_server/v1/projects/1a93/?action=deactivate)
- Click deactivate and deactivate the environment
- we get http 200 success message.
- Close it and reload the api page for the project.
- We get "Error loading schema from [http://192.168.54.207/v1/projects/1a93/schemas]: error"
- Now click activate from actions for the same environment we deactivated
- We still get "Error loading schema from [http://192.168.54.207/v1/projects/1a93/schemas]: error" and no option to proceed further

Results:

The deactivated environment could not be activated through API because of the schema error but I'm able to activate it through GUI

![schema_error](https://cloud.githubusercontent.com/assets/9711936/15463498/88e1477c-20e7-11e6-8e5b-ae0f625a7cb4.PNG)

**Comment by vincent99** [comment]
Technically the API call itself works fine, but the API UI doesn't because it's being told to get schemas for the project and they don't exist because it's inactive...

@ibuildthecloud seems like the schemas URL returned should be the root-level one when GETting a project.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
