### ISSUE TITLE
Exposed ports get a non-working IP address in UI link and API data structure

### ISSUE THREAD

**Issue by flypenguin** [rancher/rancher#4886]
**Rancher Version:** 
1.1.0-dev1

**Docker Version:** 
1.9.1

**OS and where are the hosts located? (cloud, bare metal, etc):** 
AWS EC2

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** 
single node, internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** 
Cattle

**Steps to Reproduce:**
- create a project with one service and published port (either with explicit or random port mapping)

**Results:** 
- The UI will show a clickable port number. The link behind the port number will have an IP address of "172...", which is non-routable because container-internal.
- also the API will return this information in the `publicEndpoints` structure

**Expected:**
- A clickable link which gets me to the website on a working link
- An API return value which reflects the reachable IP of the host

**Comment:**
I really don't know if that's a bug or a feature, but I see little sense in returning a link or data field pointing to a non-reachable address to be honest.

**Screenshot:**
see attached screenshot. The mouse hovers over the "5000" link.
![bildschirmfoto von 2016-05-23 15-15-18](https://cloud.githubusercontent.com/assets/5030694/15472668/a526fec6-20fc-11e6-985b-1b958c8f43e2.png)

**Comment by deniseschannon** [comment]
Is that the IP on the host that the service is deployed on? If you go to your hosts screen, do you see that `172.17.0.1` on the host?

**Comment by flypenguin** [comment]
strangely enough, I do. if it's supposed to be the host IP it is plainly wrong as you can see. I have another host now next to it with docker 1.11.1, and ubuntu 16.04 (in contrast to 15.10), where the IP address seems to be right.
<img width="544" alt="bildschirmfoto 2016-05-26 um 23 34 36" src="https://cloud.githubusercontent.com/assets/5030694/15590948/9fec37a0-239a-11e6-8a79-2a7182eb5933.png">

**Comment by vincent99** [comment]
Is the left host also the one that is running the `rancher/server` container?  http://docs.rancher.com/rancher/latest/en/faqs/troubleshooting/#are-the-ips-of-the-hosts-correct-in-the-ui

**Comment by flypenguin** [comment]
Yes it is. Although it does not only happen with the master host, but also with others.
I also did now know about this bug. Does the IP stay constance once you have manually set the host IP? I'm asking because I want to use the API to create a dynamic routing into my services, and if that would be an issue that goal is highly in danger.

**Comment by deniseschannon** [comment]
@flypenguin Yes, the IP will stay the same once you register the host with the correct IP. But if your host were to have their IP change (through reboot or restart), Rancher will not automatically update it. You would need to re-register the host with the new IP. 

After updating the IP of the host, are you able to get your services set up correctly?

**Comment by flypenguin** [comment]
Actually I didn't try yet, cause I want to modify my automation accordingly before. Is the issue the same with a host which is set up from within Rancher? I assume this host would use RancherOS then, correct?

**Comment by deniseschannon** [comment]
When you create a host through the Rancher UI, you are actually just calling a docker-machine command. Depending on the cloud provider or driver that you select the host OS could be whatever you want. If you wanted to go with RancherOS, you could use AWS and select a RancherOS AMI to spin up a host with RancherOS. Make sure you input `rancher` as the ssh user.

List of RancherOS AMIs are located in our [Readme](https://github.com/rancher/os/blob/master/README.md).

**Comment by deniseschannon** [comment]
@flypenguin Please let me know if you still have further issues after you've updated the IP of your host. After that, you should have no issues with your load balancer exposed IP/port.
