### ISSUE TITLE
NPE during k8s environment removal

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#4888]
Steps to reproduce:

1) Create an environment, pick k8s type
2) Add host
3) Delete the environment. 

Bug: environment fails to be removed

**Comment by alena1108** [comment]
@sangeethah @soumyalj we should add to the set of our validation tests

**Comment by deniseschannon** [comment]
Verified in v1.1.0-dev2-rc6 that no NPE is thrown during environment removal for k8s.
