### ISSUE TITLE
Rancher UI gradual slowdown and performace loss as session time increases

### ISSUE THREAD

**Issue by sshipway** [rancher/rancher#4889]
**Rancher Version:** 1.1.0-dev1

**Docker Version:** 1.9.1

**OS and where are the hosts located? (cloud, bare metal, etc):** CoreOS, VMWare

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** Single

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:**

Start a Rancher UI session to an Environment with a number of Hosts and Stacks.  Leave this running for several days (as in a Dashboard scenario). 

**Results:** 

The web browser memory used increases gradually, and the scripts slow down until the web browser (Firefox in this case) pops up 'slow script' warnings.  This would seem to indicate a memory leak in the UI scripts somehow.

**Expected:**

Performance to remain constant over time.

Obviously this is a hard one to track down and replicate; and most people are unlikely to leave a session running for this long.  However operation staff are likely to have a dashboard screen up and running on a constant basis; when the Rancher UI starts to include gauges for usage etc even more so.

**Comment by bacheson** [comment]
+1 The UI is very difficult to use once i'm logged in for more than 10 minutes. Each page becomes sluggish and/or unresponsive. I have to kill my chrome tab and re-login.

**Comment by jthrelfall777** [comment]
I have this problem too.

Desktop OS: Mac OS X 10.11.6

Google Chrome: 54.0.2840.98 (Official Build) (64-bit)
OS: Mac OS X 
JavaScript: V8 5.4.500.41
Flash: 23.0.0.207
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6)

Rancher Server:
Image: rancher/server:v1.1.0

/version returns:
{
  "major": "1",
  "minor": "2+",
  "gitVersion": "v1.2.0-rancher-1",
  "gitCommit": "ed6532f975cff184196dbe214de8fa0198b415ef",
  "gitTreeState": "clean"
}

If there are more than 30+ containers running for a single service the browser stop responding when going to inspect the service.

The longer the rancher UI is used the slower it becomes.

**Comment by aemneina** [comment]
@jthrelfall777 rancher 1.1 is quite old. Can you try this out with rancher 1.2?

**Comment by aemneina** [comment]
you'll also want to make sure all hosts are 'active' and not 'reconnecting' those impact performance negatively.

**Comment by jthrelfall777** [comment]
@aemneina ok no problem, I will look into this today.

**Comment by will-chan** [comment]
is this still happening?

**Comment by jthrelfall777** [comment]
@will-chan Yea I've given up with the web UI, I just use the CLI now. At a 108 containers the UI is unusable.

**Comment by deniseschannon** [comment]
@jthrelfall777 What version of Rancher are you using? There have been improvements and we are doing a new Rancher UI.

**Comment by janeczku** [comment]
@deniseschannon This is still an issue. When leaving a UI browser tab open the memory and CPU usage gradually increases. For example after leaving the container details page open over night, the memory usage for that tab increased from initially 100MB to over 1GB of memory according to Chrome task manager.

**Comment by tfiduccia** [comment]
Performance testing and metrics will have to be redone on 2.0

**Comment by cjellick** [comment]
closing as this is s a 1.6. we are tracking 2.0 performance an scale separtely
