### ISSUE TITLE
Generate config doesnot include pidMode

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#4890]
Rancher Version: Build from master

Steps to reproduce the problem:
From UI , Create a service by setting pid mode to "host".
Generate config for the stack.
docker-compose.yml for the service does not have pidMode set.

**Comment by soumyalj** [comment]
Verified in master. Here is the docker-compose generated with pid:host
<img width="729" alt="screen shot 2016-06-13 at 5 38 36 pm" src="https://cloud.githubusercontent.com/assets/18536626/16027804/e96873de-318d-11e6-8cf7-160a0ffa58b4.png">
