### ISSUE TITLE
k8s ingress controller: custom port, TLS and scale support

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#4892]
First version of ingress controller had some missing features that got enabled by the following PR:

https://github.com/rancher/ingress-controller/pull/1

The features are:

1) custom public port support
2) LB scale support
3) TLS support

Instructions to test for 1 and 2 can be found in the PR description. For TLS, attaching use cases to test:
[TLS testing.gz](https://github.com/rancher/rancher/files/278507/TLS.testing.gz)

**Comment by alena1108** [comment]
@sangeethah could you review the cases for TLS and help @soumyalj? As you've tested this feature for Rancher LB

**Comment by alena1108** [comment]
@soumyalj please test against alena1108/ingress-controller:v0.1.3

**Comment by soumyalj** [comment]
Tested on Master. The features TLS and scale support are working.
Filed https://github.com/rancher/rancher/issues/4967 w.r.t custom port.
