### ISSUE TITLE
how to upgrade a single rancher node to ha mode

### ISSUE THREAD

**Issue by rmops** [rancher/rancher#4893]
**Rancher Version:**
rancher v1.1.0-dev2-rc3
**Docker Version:**
Docker version 1.10.3, build 20f81dd
**OS and where are the hosts located? (cloud, bare metal, etc):**
ubuntu 14.04
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
We have a single node with some service ,and need to be ha
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
1.Run  a single master with extend database
docker run -d --restart=always -p 8080:8080     -e CATTLE_DB_CATTLE_MYSQL_HOST=10.1.0.101   rancher/server:latest

2.add some host and service to that rancher server

3. enable ha, update "Host Registration URL"
Waiting for host and service back... 

**Results:** 

we found all the host be come Reconnection.....
and service become unhealthy

**Expected:**

all host back and service recovery

**Comment by deniseschannon** [comment]
Per the [directions](http://docs.rancher.com/rancher/latest/en/installing-rancher/installing-server/multi-nodes/), it doesn't seem like you've actually turned on HA. 

After you've launched your script generating Rancher server, you need to generate the script and save it. Then you need to stop the first rancher/server instance and then re-launch rancher/server with the script.

Did you do those steps? These should be done BEFORE adding any hosts into Rancher.

**Comment by rmops** [comment]
Done as your say?but before enable ha?we already have losts of host and service in a single rancher server?

We want to upgrade that rancher server?Let all old service and docker host ?connect to a ha rancher cluster without service downtime?

? 2016?5?27??08:08?Denise <notifications@github.com<mailto:notifications@github.com>> ???


Per the directions<http://docs.rancher.com/rancher/latest/en/installing-rancher/installing-server/multi-nodes/>, it doesn't seem like you've actually turned on HA.

After you've launched your script generating Rancher server, you need to generate the script and save it. Then you need to stop the first rancher/server instance and then re-launch rancher/server with the script.

Did you do those steps? These should be done BEFORE adding any hosts into Rancher.

-

**Comment by rmops** [comment]
Done as your say.But before enable ha,we already have losts of host and service in a single rancher server.

We want to upgrade that rancher server.Let all old service and docker host ,connect to a ha rancher cluster without service downtime.

So I create a testing environment,and make sure we can do the same steps in our production environment.

**Comment by deniseschannon** [comment]
Let me re-confirm with our engineering team, but I believe in order to upgrade an existing Rancher instance to a HA enabled instance, there will be some service downtime as you need to spin up a new Rancher server that will HA enabled. 

But it also sounds like you only have 1 single Rancher master, so I'm not clear on how you are trying to make this setup HA without more than 1 Rancher server.

**Comment by rmops** [comment]
I have 1 rancher server with some services and try to enable ha,with other two new rancher server.

**Comment by rmops** [comment]
any updates？

**Comment by deniseschannon** [comment]
Yes, you should be able to take an existin Rancher instance and convert it to HA. 

Have you confirmed that when you try to convert to HA, you stop the currently running old rancher server (That generated the script) and used the script on that machine?

**Comment by deniseschannon** [comment]
@rmops Please re-open if you have further questions.
