### ISSUE TITLE
[UI] fork or ember cli addon for existing machine driver

### ISSUE THREAD

**Issue by runseb** [rancher/rancher#4895]
Hi Folks,

Looking at the UI code, there is an exoscale driver at `app/components/machine/driver-exoscale`
I want to make some changes to it.
Can I submit a PR or are you know only accepting ember cli add ons like mentioned in the README.

thanks

**Comment by vincent99** [comment]
PRs welcome as long it's something generally applicable to users

**Comment by deniseschannon** [comment]
@runseb Please re-open if you have further questions.

**Comment by runseb** [comment]
@vincent99 how about if I want to add features to the exoscale driver:
`/app/components/machine/driver-exoscale`

**Comment by vincent99** [comment]
@runseb again, sure if it's something that is generally applicable to users (of Rancher+Exoscale).

For example if we're missing a field that the driver offers, yes.  If you want to hardcode your credentials or set defaults to arbitrary values you happen to like, no.

**Comment by runseb** [comment]
@vincent99 ok got it. Yes it is general improvement in the advanced view
