### ISSUE TITLE
Kubernetes system stack upgrade

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#4896]
Add support for k8s system stack upgrade to the new versions of kubernetes/kubernetes-agent/ingress-controllers images + other parameters that might get changed in k8s compose templates.

**Comment by alena1108** [comment]
@soumyalj for dev4, we will have to test it by just enabling k8s on the environment.

For 1.1, you should also test:

* deploying k8s in no internet mode. 
* upgrading k8s stack to the latest catalog

We can chat about it in more details.

**Comment by soumyalj** [comment]
For v1.1.0-dev4-rc1, made sure that Kubernetes was deployed from catalog. The Kubernetes system stack API has "externalId": "system-catalog://library:kubernetes:0".

**Comment by will-chan** [comment]
Closing this as a feature.  File bugs as separate issues.
