### ISSUE TITLE
[rancher-compose] Honor the scale: setting in rancher-compose.yml

### ISSUE THREAD

**Issue by Moeser** [rancher/rancher#4897]
**Rancher Version:**  v1.1.0-dev1

**Docker Version:** 1.9.1

**OS and where are the hosts located? (cloud, bare metal, etc):** RancherOS, (mixed vm and bare metal)

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single node rancher with external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** vanilla RancherOS, running rancher/server or rancher/agent

**Steps to Reproduce:**  Put a scale: setting in rancher-compose.yml for an existing service.  Run various rancher-compose commands.

**Results:**   rancher-compose will ignore the scale: setting after a service has been created.

**Expected:** Expecting rancher-compose to honor the scale: setting during 'up', 'upgrade', and 'scale' commands.  At the very least, there should be a way to get the 'scale' command to honor scale: settings in rancher-compose.yml, instead of having to manage the scale through some out of band process.

To help, I'll suggest a possible syntax that would make sense for most people, and should be compatible with the current usage syntax:

No arguments to 'scale', reset the scale for all services in the stack to match rancher-compose.yml:
_rancher-compose scale_

A service name passed to 'scale', reset the scale for just that service to match the scale: in rancher-compose.yml:
_rancher-compose scale service1_

**Comment by deniseschannon** [comment]
We are actually following the way docker-compose handles `docker-compose scale`, so we'd need to do something special if we want to scale respecting the rancher-compose.yml. 

https://docs.docker.com/compose/reference/scale/

I've added it as an enhancement for rancher-compose.

**Comment by Moeser** [comment]
Still looking for this.  Managing the scale property out-of-band from the rest of the service settings is making our deployment process a lot more complex than it needs to be.

**Comment by deniseschannon** [comment]
This needs to be fixed for bindings to work for catalog upgrades.

**Comment by deniseschannon** [comment]
We've decided that to remove scale from bindings and continue to operate scale as a separate command in rancher-compose and separate update in the UI.

**Comment by Moeser** [comment]
I'm not sure if I understand that last update.  Does that mean you won't be adding a way for rancher-compose to set the scale based on the scale: setting in rancher-compose.yml?

**Comment by deniseschannon** [comment]
@Moeser  The last comment was referencing my previous comment saying it was necessary to make bindings to work.

In rancher-compose, the way we recommend changing scale is to use `rancher-compose scale` and not to use it in the rancher-compose.yml.
