### ISSUE TITLE
Select Resource type dropdown in Processes in broken

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4899]
**Rancher Version:** master 5.24

**Steps to Reproduce:** 
1.  Go to Processes screen
2.  Click on Select a Resource type drop-down

**Results:** Drop-down is covering whole screen
![image](https://cloud.githubusercontent.com/assets/11514927/15518008/996c8f16-21af-11e6-842e-cd1a6457f8b8.png)

**Expected:**  Should look same as drop-down in Audit Logs

**Comment by lvuch** [comment]
https://github.com/rancher/ui/pull/697

**Comment by tfiduccia** [comment]
Version - master 6/9
Verified fixed
