### ISSUE TITLE
Namespace from different environment showing up while setting up services

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4902]
**Rancher Version:** master 5-24

**Steps to Reproduce:**
1.  Setup a kubernetes environment fully
2.  Add another namespace for that environment
3.  Switch to that namespace
4.  Create another kubernetes environment and switch to that environment

**Results:** Namespace for previous environment is showing up
![image](https://cloud.githubusercontent.com/assets/11514927/15521115/d3b6c1a0-21be-11e6-8132-ab07d63aef42.png)

**Expected:** Namespace should not show up.

**Comment by deniseschannon** [comment]
Still an issue in v1.1.0-dev4.

Followed @tfiduccia's steps

**Comment by vincent99** [comment]
Stop stealing bugs, not in a release yet :-)

**Comment by tfiduccia** [comment]
Version - master 6/9
Not fixed

**Comment by vincent99** [comment]
No longer applicable in 1.4.
