### ISSUE TITLE
nodeName field is being assigned to a deleted host

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#4904]
**Rancher Version:**
v1.0.1

**Docker Version:**
1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
RancherOS

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
k8s

Host was removed from Rancher and new pod was deployed, the new pod was attempted to be launched on the node that had been terminated. We saw that the pod was stuck in "Pending" and looked at the "View in API" page, where we could see from the nodeName field that it was assigned to the deleted host. We even removed all traces of that deployment (i.e. Service, RC and Pod) from Kubernetes and reran the deployment about an hour later, and it was still assigned to the deleted instance.

**Comment by alena1108** [comment]
To reproduce the issue:

1) Have 2 hosts
2) Manager to have etc, controller-manager on host1, and kuberneres API server on host2. 
3) Deactivate and remove host2. Kubernetes API instance is recreated on host1.

The bug is - controller manager keeps on referencing an ip of an old k8s API server instance - looks like there the IP address is DNS cached (api server url is configured for controller manager as http://master). And given that controller can't contact API server, it can't update the list of Ready nodes, so it continues to show both host1 and host2 as available:

```
Host was removed around 20:33:
E0525 20:33:50.392911       1 nodecontroller.go:229] Error monitoring node status: Get http://master/api/v1/nodes: dial tcp 10.42.67.251:80: i/o timeout
W0525 20:34:00.340916       1 request.go:344] Field selector: v1 - serviceaccounts - metadata.name - default: need to check if this is versioned correctly.
I0525 20:34:00.384078       1 servicecontroller.go:298] LB doesn't need update for service default/kubernetes
E0525 20:34:00.385223       1 nodecontroller.go:771] Error updating node alena-10acre-2: nodes "alena-10acre-2" cannot be updated: the object has been modified; please apply your changes to the latest version and try again

Even after 5 mins controller still continues querying the old ip address:

E0525 20:39:41.432839       1 iowatcher.go:109] Unable to decode an event from the watch stream: read tcp 10.42.67.251:80: connection timed out
E0525 20:39:41.435659       1 iowatcher.go:109] Unable to decode an event from the watch stream: read tcp 10.42.67.251:80: connection timed out
E0525 20:39:41.435722       1 iowatcher.go:109] Unable to decode an event from the watch stream: read tcp 10.42.67.251:80: connection timed out
```

 Only when you a) restart the controller, or b) register new host, or c) restart the existing kubelet (b and c generate new events for controller), the controller starts querying new Api server ip address:

```
New event came, and unblocked things:
I0525 20:50:24.690703       1 event.go:211] Event(api.ObjectReference{Kind:"Node", Namespace:"", Name:"alena-10acre-1", UID:"alena-10acre-1", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'NodeNotReady' Node alena-10acre-1 status is now: NodeNotReady
I0525 20:50:24.700093       1 rancher.go:541] ExternalID [alena-10acre-1]
I0525 20:50:24.700209       1 rancher.go:547] InstanceID [alena-10acre-1]
I0525 20:50:24.724431       1 nodecontroller.go:504] Deleting node (no longer present in cloud provider): alena-10acre-1
I0525 20:50:24.725120       1 event.go:211] Event(api.ObjectReference{Kind:"Node", Namespace:"", Name:"alena-10acre-1", UID:"alena-10acre-1", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'DeletingNode' Node alena-10acre-1 event: Deleting Node alena-10acre-1 because it's not present according to cloud provider
I0525 20:50:25.155520       1 servicecontroller.go:684] Detected change in list of current cluster nodes. New node set: [alena-10acre-2]
I0525 20:50:25.155638       1 servicecontroller.go:692] Successfully updated 1 out of 1 load balancers to direct traffic to the updated set of nodes
I0525 20:50:29.727841       1 event.go:211] Event(api.ObjectReference{Kind:"Node", Namespace:"", Name:"alena-10acre-1", UID:"alena-10acre-1", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'RemovingNode' Node alena-10acre-1 event: Removing Node alena-10acre-1 from NodeController
```

We are going to workaround this issue on the Rancher side by preserving the ip address of kubernetes API (master) container, so it is always accessible by the same ip address:

**Comment by alena1108** [comment]
@soumyalj the initial issue might not be easy to reproduce. As the minimum, following needs to be checked:

* enable k8s
* wait till all the services become active
* delete "kubernetes" service container. Make sure it is recreated using the same ip address

**Comment by soumyalj** [comment]
Reproduced the issue in v1.0.1. Verified the fix in master. After deleting the Kubernetes service container,  it was recreated using the same ip address.
