### ISSUE TITLE
[rancher-compose] Add command to download current docker-compose.yml and rancher-compose.yml

### ISSUE THREAD

**Issue by entropyfarms** [rancher/rancher#4905]
I have more than once forgot to update the local copy of my {docker,rancher}-compose.yml file before running an upgrade.  It would be nice if I can programatically pull in the latest yml files from the rancher server given the rancher_access_key and rancher_secret_key.

**Comment by deniseschannon** [comment]
This is supported in the new [Rancher CLI](http://docs.rancher.com/rancher/cli/) which supports `rancher export`.
