### ISSUE TITLE
Add LDAP members to an environment

### ISSUE THREAD

**Issue by PhanQ** [rancher/rancher#4912]
**Rancher Version:1.0.0

**Docker Version:1.10.2

**OS and where are the hosts located: bare, Centos 7.1 

**Setup Details: single node rancher 

**Environment Type: Cattle

**Steps to Reproduce:**
- Create LDAP access control
- Login with LDAP accounts successfully
- Want to add a LDAP account already logged in (already in rancher accounts list) to an environment
- Action as Rancher guide

 Provide the username and click on the + to add the name to the list of members. If the name is not on the list, then they will not be added to the environment. Alternatively, there is a dropdown button on the right side of the + button, which will show organizations/teams for certain authentication types.

**Results:** 
- Show nothing when click "+" or "drop down button"

**Expected:**
- Show user already logged in Rancher, so that can select to add to an environment.

Thanks

**Comment by PhanQ** [comment]
Hi, anyone can help?

1. Authenticate users to Rancher based on LDAP OUs or a Domain. --> it's OK
2. Add users to an Environment based on their LDAP username or groups. --> can't get user info from LDAP. Why Rancher doesn't simple allow getting user from local DB, who already logged in at step 1

**Comment by deniseschannon** [comment]
Just to confirm, 

1. You are on the edit environment screen. 
2. You are putting the username in the textbox and then clicking on the + sign?
3. After you click on the + sign, what happens? The list below that section should have been updated to include the person that you want to add.

I've recently did this on a LDAP setup with no issues.

**Comment by PhanQ** [comment]
Hi Denise

1. Yes, I'm in  edit environment screen, and want to add a LDAP user, who already logged in to Rancher 
2. After putting the username in textbox, clicking + sign, a banned symbol appear
3. When trying click to drop down list, no list appears, only "Your Groups" text.

Thanks

**Comment by PhanQ** [comment]
Hi Denise

I found the problem is when I tried call API: http://[MY_RANCHER_IP]/v1/identities, it only returns 1 account, ID 1a1, the first account log in to Rancher. That's why I can't add other accounts to environment.

Could you help to check it more.

Thanks

**Comment by LLParse** [comment]
@PhanQ I confirm that only the logged-in account appears at /v1/identities. I can also confirm that users don't appear in the group dropdown on edit environments screen. This shouldn't be an issue, though, because you can still search for other LDAP accounts (regardless of whether or not they've made it to rancher accounts list).

Try this out: /v1/identities?name=UID 
where UID is any inetOrgPerson.uid within your configured search base

If you are unable to see any other identities that you've configured in LDAP, that is the root problem. Could you try this out?

**Comment by deniseschannon** [comment]
@PhanQ Please re-open if you are able to provide more details and still have issues.
