### ISSUE TITLE
VM provisioning via Rancher openstack driver failed

### ISSUE THREAD

**Issue by adaikal** [rancher/rancher#4913]
Tried to provision a host on openstack using Rancher openstack driver. 
The host was created on the openstack and docker was installed.
The rancher agent was also downloaded and container was created as per the logs but clean up happened and the VM was deleted by throwing error "err=API error (500): rpc error: code = 2 desc = "containerd: container did not start before the specified timeout"
 eventId=cce5bb0c-4428-4c28-a0be-cd714549ffcd eventName=physicalhost.bootstrap;handler=goMachineService resourceId=1ph16"

Rancher Version: 1.1.0-dev2

Docker Version:

Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64

OS and location: Ubuntu 14.04, Openstack Kilo

Setup Details: Single node with external database

Environment Type: Cattle

Setps to reproduce:

Just provision a Host using rancher openstack driver.

Error ouptut:

INFO[0137] stdout: Creating CA: /var/lib/cattle/machine/7a3ec841-ee45-4b91-bb6b-46b8d1314c4c/certs/ca.pem  resourceId: =1ph16
INFO[0137] stdout: Creating client certificate: /var/lib/cattle/machine/7a3ec841-ee45-4b91-bb6b-46b8d1314c4c/certs/cert.pem  resourceId: =1ph16
INFO[0137] stdout: Running pre-create checks...          resourceId: =1ph16
INFO[0137] stdout: Creating machine...                   resourceId: =1ph16
INFO[0139] stdout: (is-test) Creating machine...         resourceId: =1ph16
INFO[0162] stdout: Waiting for machine to be running, this may take a few minutes...  resourceId: =1ph16
INFO[0162] stdout: Detecting operating system of created instance...  resourceId: =1ph16
INFO[0162] stdout: Waiting for SSH to be available...    resourceId: =1ph16
INFO[0189] stdout: Detecting the provisioner...          resourceId: =1ph16
INFO[0189] stdout: Provisioning with ubuntu(upstart)...  resourceId: =1ph16
INFO[0283] stdout: Installing Docker...                  resourceId: =1ph16
INFO[2143] stdout: Copying certs to the local machine directory...  resourceId: =1ph16
INFO[2145] stdout: Copying certs to the remote machine...  resourceId: =1ph16
INFO[2145] stdout: Setting Docker configuration on the remote daemon...  resourceId: =1ph16
INFO[2146] stdout: Checking connection to Docker...      resourceId: =1ph16
INFO[2148] stdout: Docker is up and running!             resourceId: =1ph16
INFO[2149] stdout: To see how to connect your Docker Client to the Docker Engine running on this virtual machine, run: docker-machine env is-test  resourceId: =1ph16
INFO[2149] Machine Created                               machineExternalId=7a3ec841-ee45-4b91-bb6b-46b8d1314c4c resourceId=1ph16
INFO[2149] Creating and uploading extracted machine config  resourceId=1ph16
INFO[2149] Machine config file created and encoded.      destFile=/var/lib/cattle/machine/7a3ec841-ee45-4b91-bb6b-46b8d1314c4c/is-test.tar.gz resourceId=1ph16
INFO[2149] Activating Machine                            eventId=cce5bb0c-4428-4c28-a0be-cd714549ffcd resourceId=1ph16
INFO[2157] Pulling rancher/agent:v1.0.1 image.
INFO[3145] Container created for machine                 containerId=dc3cbeb2799d503e74f64a1c2837d32d58264ced8a866f5d3ca1d7dc4664714e machineId=1ph16 resourceId=1ph16
INFO[3169] starting cleanup...                           machine name=is-test
INFO[3170] cleanup successful                            machine name=is-test
ERRO[3170] Error processing event                        err=API error (500): rpc error: code = 2 desc = "containerd: container did not start before the specified timeout"
 eventId=cce5bb0c-4428-4c28-a0be-cd714549ffcd eventName=physicalhost.bootstrap;handler=goMachineService resourceId=1ph16

**Comment by deniseschannon** [comment]
@adaikal Are you still facing issues? I see in the forums that you have been able to provision hosts in the API, so not sure if you still need help.

**Comment by adaikal** [comment]
@deniseschannon yes I can provision hosts on openstack now. But there still exists a bug docker machine openstack driver which has to be dealt separately.
