### ISSUE TITLE
[UI] Load balancer advanced routing broken in v1.1.0-dev2

### ISSUE THREAD

**Issue by nunofgs** [rancher/rancher#4914]
**Rancher Version:** v1.1.0-dev2

**Docker Version:** n/a

**OS and where are the hosts located? (cloud, bare metal, etc):** n/a

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single node rancher.

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle.

**Steps to Reproduce:**
1. Click "Add load balancer" on any stack.
2. Click "Show advanced routing options".

**Results:** 

<img width="1278" alt="screen shot 2016-05-25 at 17 00 24" src="https://cloud.githubusercontent.com/assets/92085/15547163/8129a664-229a-11e6-9d73-2ed33cb0adac.png">

**Expected:**

<img width="976" alt="screen shot 2016-05-25 at 17 03 07" src="https://cloud.githubusercontent.com/assets/92085/15547175/91d8727e-229a-11e6-8880-34141d45230a.png">

**Comment by HackerWilson** [comment]
@deniseschannon
rancher 1.1.0-dev2 use https instead of http in `Host Registration URL`. but when I replaced
```
export CATTLE_HA_HOST_REGISTRATION_URL=https://host:port
```
to
```
export CATTLE_HA_HOST_REGISTRATION_URL=http://host:port
```
then delpoyed.

I found the rancher-agent cannot  connect to the loadbalancer:
```
time="2016-05-26T09:29:06Z" level="info" msg="Connecting to proxy." url="ws://192.168.0.40:8080/v1/connectbackend?token=eyJhbGciOiJSUzI1NiJ9.eyJleHAiOjE0NjQyNTUyNDYsInN1YiI6ImNhdHRsZSIsImlzcyI6Imh0dHA6XC9cL2NhdHRsZS5pbyIsInJlcG9ydGVkVXVpZCI6IjZhOGY4NDVlLTZhM2EtNGE0Ni1iOTM2LTQzYWY4NmVlMDk3MyIsImlhdCI6MTQ2NDI1NDk0Niwia2lkIjoiZGVmYXVsdCJ9.hGFBcoRrPWJRETNMAvCtbZYFHF-bztxcIV1DPfB70rx6o88jX-PlSiA3mrWOveHVRzFdCztwkZLdRlQBb59QRfw8h6vWuf6ICXeA4dePuGxayFz90JYqQyH7Gl808Jvre5Eb_x1Z8NSPlqqB_rzQSP7pkpBC82NaUiy0xvRhFoYc5FG_AzD3swxAGXFgtqv4zOTw5sXjcw_DP1dbuX3c12hxW8NMoGeytB2y61NcVLs9aK7HRLcUMDZkP4hLxxtwEVjktZXYhxKD3zPbRSP-A1Ic9dNe92hErH23CC4ixg2XBV3y5YaH3IOSw05dMk2WDWKqRIzgWmx_j2bj-jsQhw" 
time="2016-05-26T09:29:06Z" level="fatal" msg="Failed to connect to proxy." error="websocket: bad handshake" 
```
the url start with `ws://`, not `http`?

and the release note didn't noticed this change, can you still support `Host Registration URL` with `http protocol` ?

**Comment by tfiduccia** [comment]
@HackerWilson - please create a separate issue.  This issue was referencing a missing translation in the UI and is going to be closed.

**Comment by tfiduccia** [comment]
Version - master 5-26
Verified fixed
