### ISSUE TITLE
Add targets into Detailed Load Balancer view for k8s load balancers

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#4915]
**Rancher Version:**
v1.1.0-dev2

In the summary review of the load balancer, there is this nice view of targets. It doesn't exist in the detailed view of load balancer. 

![screen shot 2016-05-25 at 1 34 04 pm](https://cloud.githubusercontent.com/assets/11410997/15555653/88d46cb2-227e-11e6-9698-cca1dbdf5251.png)

**Comment by vincent99** [comment]
![image](https://cloud.githubusercontent.com/assets/753917/21281060/53e0d660-c3a7-11e6-9456-51ce439fbd3d.png)

![image](https://cloud.githubusercontent.com/assets/753917/21281055/4a8f7116-c3a7-11e6-8b41-e7c4c856cacd.png)
