### ISSUE TITLE
Storage Pools section not working

### ISSUE THREAD

**Issue by pragmaticivan** [rancher/rancher#4916]
**Rancher Version:**
v1.1.0-dev2-rc4
**OS and where are the hosts located? (cloud, bare metal, etc):**
AWS
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
External DB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
I configured gluster fs and convoy gluster using the packages available in the community packages. I went to the menu for Storage Pools, I can see the 3 servers in the right side, but I add a volume and the page doesn't refresh. I refresh the whole page and that shows a "Requested" label in the volume I requested to, and that never changes, after one day still the same label.

<img width="1908" alt="screen shot 2016-05-25 at 2 10 18 pm" src="https://cloud.githubusercontent.com/assets/301291/15556375/71e2b258-2282-11e6-9315-6fddd74643ad.png">

**Comment by tfiduccia** [comment]
@pragmaticivan - The Volume will stay in a requested state until you have a service that actually utilizes that volume.  Once that Service is "Active" the Volume state will move from Requested to Active.  I'm going to close, reopen if after you add service it's still in Requested state.

The refresh bug is already reported - #3208

**Comment by pragmaticivan** [comment]
@tfiduccia this tasks has 2 problems, the first on you didn't solve. After I add a volume the page doesn't refresh. And still happening. Problem with The UI I guess.

**Comment by deniseschannon** [comment]
@pragmaticivan The refresh issue has already been filed as @tfiduccia mentioned. It is #3208.

**Comment by pragmaticivan** [comment]
@deniseschannon thanks, I just tested what @tfiduccia said and the container has problem to start using the volume requested. I'll debug the logs later.
