### ISSUE TITLE
Support Machine Catalog

### ISSUE THREAD

**Issue by will-chan** [rancher/rancher#4919]
Add support for integrating Rancher with a catalog of machine drivers.  Users will be able to submit machine driver URLs to https://github.com/rancher/community-catalog, and allow it to be discoverable and installable by any Rancher deployments.

**Comment by will-chan** [comment]
duplicate of #4856

**Comment by shouze** [comment]
@will-chan how to submit docker machine drivers to  https://github.com/rancher/community-catalog?

**Comment by will-chan** [comment]
@vincent99 @westlywright can you provide the answer for @shouze?
