### ISSUE TITLE
Rancher API creates a host in openstack and then deletes the host saying it already exists

### ISSUE THREAD

**Issue by adaikal** [rancher/rancher#4922]
Recently, I have been trying to provision a host using rancher openstack api and on every try, rancher is provisioning the VM but running into some sort of trouble.

In this case, I launched a VM named "is-asdf" using rancher openstack api and rancher provisoned the VM(I even logged into that provisioned VM).

But rancher did not install docker on that and then as you could find the error logs, rancher cleaned up the VM "is-asdf" saying that it already exists(it just cleaned up the VM, it provisioned).

Following the clean up, I could see rancher making calls to openstack with insufficient parameters.

Rancher Version: 1.1.0-dev2

Docker Version:

Client:
Version: 1.10.3
API version: 1.22
Go version: go1.5.3
Git commit: 20f81dd
Built: Thu Mar 10 15:54:52 2016
OS/Arch: linux/amd64

Server:
Version: 1.10.3
API version: 1.22
Go version: go1.5.3
Git commit: 20f81dd
Built: Thu Mar 10 15:54:52 2016
OS/Arch: linux/amd64

OS and location: Centos 7, Openstack Kilo

Setup Details: Single node with external database

Environment Type: Cattle

Setps to reproduce:

Just provision a Host using rancher openstack driver.

Error output:

INFO[42299] Creating Machine                              eventId=f8f10d60-0ca9-4d59-945c-310c440a86f8 resourceId=1ph20
INFO[42299] Cmd slice: [create -d openstack --openstack-active-timeout 200 --openstack-auth-url http://controller:5000 --openstack-flavor-name custom.1.1.10 --openstack-image-name CentOS7 --openstack-insecure --openstack-ip-version 4 --openstack-keypair-name adaikal_ssh_3 --openstack-net-name public --openstack-password password --openstack-private-key-file /home/ubuntu/.ssh/adaikal_ssh_3.pem --openstack-region RegionOne --openstack-sec-groups default --openstack-ssh-port 22 --openstack-ssh-user centos --openstack-tenant-name demo --openstack-username demo is-asdf]
INFO[42299] stdout: Creating CA: /var/lib/cattle/machine/6ad52fe8-6d98-4bc2-8f25-427ae50cbe55/certs/ca.pem  resourceId: =1ph20
INFO[42299] stdout: Creating client certificate: /var/lib/cattle/machine/6ad52fe8-6d98-4bc2-8f25-427ae50cbe55/certs/cert.pem  resourceId: =1ph20
INFO[42300] stdout: Running pre-create checks...          resourceId: =1ph20
INFO[42300] stdout: Creating machine...                   resourceId: =1ph20
INFO[42300] stdout: (is-asdf) Creating machine...         resourceId: =1ph20
INFO[42309] stdout: Waiting for machine to be running, this may take a few minutes...  resourceId: =1ph20
INFO[42309] stdout: Detecting operating system of created instance...  resourceId: =1ph20
INFO[42309] stdout: Waiting for SSH to be available...    resourceId: =1ph20
INFO[42331] stdout: Detecting the provisioner...          resourceId: =1ph20
INFO[42332] stdout: Provisioning with centos...           resourceId: =1ph20
INFO[43212] Exiting go-machine-service
INFO[43211] Exiting rancher-compose-executor              version=v0.8.2
INFO[0003] Starting rancher-compose-executor             version=v0.8.2
INFO[0001] Setting log level                             logLevel=info
INFO[0001] Starting go-machine-service...                gitcommit=v0.31.4
INFO[0001] Waiting for handler registration (1/2)
INFO[0004] Initializing event router                     workerCount=10
INFO[0006] Connection established
INFO[0004] Initializing event router                     workerCount=10
INFO[0004] Connection established
INFO[0004] Waiting for handler registration (2/2)
INFO[0005] Initializing event router                     workerCount=10
INFO[0005] Connection established
INFO[0005] Installing builtin drivers
INFO[0006] Downloading all drivers
INFO[0008] Copying /var/lib/cattle/machine-drivers/1f7058341420e2f525168052818c3f819ff78e9ca5f57d5a650a049bcd5945e9-docker-machine-driver-packet => /usr/local/bin/docker-machine-driver-packet
INFO[86469] Registering backend for host [7e2b8f72-f854-4aaa-88a9-ce55c3917772]
INFO[0031] Creating Machine                              eventId=a4107aef-505e-4081-9473-a6ae4f26c91d resourceId=1ph20
INFO[0031] Cmd slice: [create -d openstack --openstack-active-timeout 200 --openstack-auth-url http://controller:5000 --openstack-flavor-name custom.1.1.10 --openstack-image-name CentOS7 --openstack-insecure --openstack-ip-version 4 --openstack-keypair-name adaikal_ssh_3 --openstack-net-name public --openstack-password password --openstack-private-key-file /home/ubuntu/.ssh/adaikal_ssh_3.pem --openstack-region RegionOne --openstack-sec-groups default --openstack-ssh-port 22 --openstack-ssh-user centos --openstack-tenant-name demo --openstack-username demo is-asdf]
INFO[0048] Done downloading all drivers
INFO[0059] stderr: Host already exists: "is-asdf"        resourceId=1ph20
INFO[0059] starting cleanup...                           machine name=is-asdf
INFO[0064] cleanup successful                            machine name=is-asdf
ERRO[0064] Error processing event                        err=Host already exists: "is-asdf" eventId=a4107aef-505e-4081-9473-a6ae4f26c91d eventName=physicalhost.create;handler=goMachineService resourceId=1ph20
INFO[0368] Creating Machine                              eventId=a5a289dd-f5f2-4114-bec0-5de280a2152f resourceId=1ph21
INFO[0368] Cmd slice: [create -d openstack --openstack-active-timeout 200 --openstack-ip-version 4 --openstack-ssh-port 22 --openstack-ssh-user root PHPVM]
INFO[0368] stderr: Error setting machine configuration from flags provided: Authentication URL must be specified either using the environment variable OS_AUTH_URL or the CLI option --openstack-auth-url  resourceId=1ph21
INFO[0368] starting cleanup...                           machine name=PHPVM
ERRO[0368] Error processing event                        err=Error setting machine configuration from flags provided: Authentication URL must be specified either using the environment variable OS_AUTH_URL or the CLI option --openstack-auth-url eventId=a5a289dd-f5f2-4114-bec0-5de280a2152f eventName=physicalhost.create;handler=goMachineService resourceId=1ph21

**Comment by deniseschannon** [comment]
In your forum posts, it seems like you were able to get your openstack hosts working. Please let me know if this is still valid and you're still having issues.

**Comment by adaikal** [comment]
I'm able to provision the hosts on openstack. Looks like there still exists a bug in openstack driver but that has to be dealt separately. Thank you.
