### ISSUE TITLE
Adding new host with multiple environments

### ISSUE THREAD

**Issue by dariusgm** [rancher/rancher#4924]
* Started HA Mode on One Host using a mysql db
* Switched to "Default" Env
* Adding Host (Different Server)
* Server shows up in "System HA" Env and not in default as expected. Hosts List is totally Empty in Default

Am I doing something wrong?

I want to add a new Host and see this host on every env because I am logged in as admin with no restrictions configured.

I don't know if this is just an HA Mode Issue. Haven't tested it.

Edit: No, not an HA Mode Issue.
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.1.0-dev2` Cattle: `v0.161.5` UI: `v1.1.2` |
|Access|`Disabled`|
|Orchestration|`Cattle`|
|Route|`hosts.index`|

**Comment by vincent99** [comment]
A host can only belong to a single environment.  If you're doing "Custom" add host (`docker run ... rancher/agent ...`) the registration token at the end is unique for each environment and determies which one the host will register into.

**Comment by dariusgm** [comment]
Found it in the Docs:

> Infrastructure resources cannot be shared across multiple environment.

Thanks @vincent99
