### ISSUE TITLE
Rancher machine deletes keypair in openstack while provisioning VM

### ISSUE THREAD

**Issue by adaikal** [rancher/rancher#4925]
https://forums.rancher.com/t/rancher-openstack-drivers-operation-is-deleting-keypairs-in-openstack/2921

Rancher Version: 1.1.0-dev2

Docker Version: 

Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64

OS and location: Ubuntu 14.04, tested in both kilo and icehouse openstacks

Setup Details:

Single node rancher with external database

Environment type: cattle

Steps to reproduce:

Provision a host on openstack(I tested on kilo and icehouse)

While creating a host on openstack, we give a keypair which will be present on openstack

Rancher will provision the host on openstack but further processes will run into errors(tested about 10 times, no success)

When rancher cleans up the Host, it deletes the keypair in openstack(I confirmed this by having two keypairs active in openstack. The key which I used for openstack got deleted and the other key remained as it is.)

Error_log:

INFO[7127] stdout: Creating CA: /var/lib/cattle/machine/5464cf49-bfa3-4365-8929-1093ff8745ea/certs/ca.pem  resourceId: =1ph10
INFO[7128] stdout: Creating client certificate: /var/lib/cattle/machine/5464cf49-bfa3-4365-8929-1093ff8745ea/certs/cert.pem  resourceId: =1ph10
INFO[7128] stdout: Running pre-create checks...          resourceId: =1ph10
INFO[7128] stdout: Creating machine...                   resourceId: =1ph10
INFO[7129] stdout: (publicdevvm) Creating machine...     resourceId: =1ph10
INFO[7152] stdout: Waiting for machine to be running, this may take a few minutes...  resourceId: =1ph10
INFO[7152] stdout: Detecting operating system of created instance...  resourceId: =1ph10
INFO[7152] stdout: Waiting for SSH to be available...    resourceId: =1ph10
INFO[7212] Purging Machine                               eventId=f38bbf00-63f9-4894-b33a-cfc18c4cf511 resourceId=1ph9
INFO[7212] Machine purged                                machineDir=/var/lib/cattle/machine/cb506dc0-3fff-49f5-b9a2-4278df13fdb1 machineExternalId=cb506dc0-3fff-49f5-b9a2-4278df13fdb1 resourceId=1ph9
INFO[7567] stdout: The default lines below are for a sh/bash shell, you can specify the shell you're using, with the --shell flag.  resourceId: =1ph10
INFO[7567] stdout:                                       resourceId: =1ph10
INFO[7570] stderr: Error creating machine: Error detecting OS: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded  resourceId=1ph10
INFO[7570] starting cleanup...                           machine name=publicdevvm
INFO[7571] cleanup successful                            machine name=publicdevvm
ERRO[7571] Error processing event                        err=Error detecting OS: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded eventId=bd1db040-5716-4565-85cf-f0df6aa75293 eventName=physicalhost.create;handler=goMachineService resourceId=1ph10
INFO[7932] Purging Machine                               eventId=42122ea9-0f7e-47bc-95c7-27120a671c99 resourceId=1ph10
INFO[7932] Machine purged                                machineDir=/var/lib/cattle/machine/5464cf49-bfa3-4365-8929-1093ff8745ea machineExternalId=5464cf49-bfa3-4365-8929-1093ff8745ea resourceId=1ph10

**Comment by vincent99** [comment]
This is a bug in docker-machine... https://github.com/docker/machine/issues/3261

**Comment by adaikal** [comment]
@vincent99 Where Rancher/Docker machine stores the SSH private key. 

I tested provisioning without specifying an already present keypair and Docker machine created its own keypair and injected public key into the VM and with the private key, it installed docker and Rancher agent.

I'd like to know, where rancher stores this private key, because I want to SSH into the VM for activities.

Thank you

**Comment by vincent99** [comment]
Once the host is setup there's a `Machine Config` action which will download a zip file that contains the SSH key among other things.

**Comment by adaikal** [comment]
Thank you @vincent99 . It worked.
