### ISSUE TITLE
When there are large number of containers , containers disappear from the host view when  UI receives event changes  for containers.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#4928]
Rancher Version: Build from master

Rancher server setup with 3 hosts and there were many containers ( ~170 containers / host) on this set up.

Deploy a new service.
Launch the "Hosts" view.
We will see the newly created container show up in the host where it is running.

Wait for some time (30 secs - 1 minute)  ( There should be some events that get pushed to the UI relating to container state changes) . 

Notice that the newly added container is not seen anymore in the host view.
Refresh the page.
The newly added container shows up on the host view.

**Comment by tfiduccia** [comment]
Version - master 5-26
Verified fixed

Sangeetha, not sure if you wanted to try out your test before closing?  I made sure I had 150 containers on a single UI and then forced a change-event through the host.  All containers were still there.
