### ISSUE TITLE
Rancher-Compose "Stop -t " option is not working

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#4935]
**Rancher Version:**v1.0.2-rc2

**Docker Version:**v0.7.4, v0.8.0

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**: Cattle

Steps:
1. rancher-compose stop --help

```
$ ./rancher-compose stop --help
Usage: rancher-compose stop [OPTIONS]

Stop services

Options:
   --timeout, -t "10"   Specify a shutdown timeout in seconds.
```

The time out option is currently not working.

**Comment by joshwget** [comment]
According to @alena1108, Cattle doesn't currently have a concept of forcefully stopping services. This makes implementing this command impossible for now. In the meantime, this flag should be removed so users don't get confused and assume this functionality exists.

**Comment by will-chan** [comment]
@joshwget can we remove this flag if we can't support this?

**Comment by joshwget** [comment]
This flag isn't present in the Rancher CLI.
