### ISSUE TITLE
Firewalling between stacks

### ISSUE THREAD

**Issue by keras** [rancher/rancher#4936]
**Rancher Version:**
v1.0.1

**Docker Version:**
1.11.0

I have noticed that there isn't any kind on firewalling in the rancher network. All containers can connect all other containers without restrictions, even across stacks.

I'd like to see some kind of firewalling feature in rancher.
For example connections between stacks should be prohibited by default except for external_links.
Also connections inside the stacks should be prohibited unless explicitly opened by linking the services.
Firewalling could be also extended to public ports, allowing connections only from predefined IPs.

**Comment by vincent99** [comment]
https://github.com/rancher/rancher/issues/3895
