### ISSUE TITLE
Rancher host gets stuck in inactive state

### ISSUE THREAD

**Issue by etaullaj** [rancher/rancher#4937]
I deleted a stack then for some reason the host went into the reconnecting state. When looking into the storage tab in the UI, I do see a lot of volumes stack in the "purging" state. 

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.0.1` Cattle: `v0.159.7` UI: `v1.0.5` |
|Access|`github` |
|Route|`host.storage`|

**Comment by pwFoo** [comment]
Sometimes different states stuck here with a setup based on three hosts.
Stuck creation, hosts stay deactivated instead of be active.

Maybe related, so I'll follow here...

**Comment by deniseschannon** [comment]
@etaullaj Are you able to consistently reproduce this? 

It sounds like you're using storage pools/volumes? Could you share your docker-compose.yml of your stack so I could see how you're using volumes? 

@pwFoo Do you have any steps to consistently reproduce so we could try?

Iv'e deleted multiple stacks and have yet to hit this issue. Also, could both of you provide your OS for your hosts and your general Rancher setup?

**Comment by deniseschannon** [comment]
@etaullaj @pwFoo If you have reliable steps to reproduce, please re-open.
