### ISSUE TITLE
[feature request] Add a field in UI indicating when a container was created/launched

### ISSUE THREAD

**Issue by jmreicha** [rancher/rancher#4939]
It would be useful to have some indication in the UI of times that containers were upgraded/updated for deployments, etc.  A field in the stack/service view for each container as well as in the container view might make sense?

**Comment by jmreicha** [comment]
Any update on this?  It look a like there are time stamps in the API, would it be feasible to expose them in the UI?

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
