### ISSUE TITLE
Clear out text in search field when coming back to catalog page

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#4941]
**Rancher Version:**
v1.1.0-dev3 

**Steps to Reproduce:**
1. Search for catalog item
2. Switch to a different environment and to catalog header

**Results:** 
The catalog is searching based on the text in the search field.

In my case I went from a cattle to fresh swarm environment and it  said there no templates. 

**Expected:**
The search field should be cleared when coming back to the catalog page so it shows all templates.

**Comment by tfiduccia** [comment]
Version - master 11/06
Verified fixed
