### ISSUE TITLE
[UI] Incorrect translation in advanced load balancer configuration

### ISSUE THREAD

**Issue by nunofgs** [rancher/rancher#4943]
**Rancher Version:** 1.1.0-dev3

**Docker Version:** n/a

**OS and where are the hosts located? (cloud, bare metal, etc):** n/a

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single node

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle.

**Steps to Reproduce:**

1. Add a load balancer.
2. Click the "Show advanced routing options"

**Results:** 

<img width="615" alt="screen shot 2016-05-27 at 22 42 08" src="https://cloud.githubusercontent.com/assets/92085/15621951/94bbddbe-245c-11e6-9787-10efaeef76f0.png">

**Comment by tfiduccia** [comment]
Version - master 5-27 - Verified this is a problem:
This has the wrong I8n label
![image](https://cloud.githubusercontent.com/assets/11514927/15622393/067c6864-241d-11e6-9a66-9026c938d9e7.png)

Should be a Request Path lable
![image](https://cloud.githubusercontent.com/assets/11514927/15622391/fd91fda4-241c-11e6-87c6-d36e7957cf3f.png)

**Comment by lvuch** [comment]
https://github.com/rancher/ui/pull/708

**Comment by tfiduccia** [comment]
Version - master 6/9
Verified fixed
