### ISSUE TITLE
UI erors out with 500 failure error when Kubernetes errors are encountered

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#4946]
**Rancher Version:** Master

**OS and where are the hosts located? (cloud, bare metal, etc):**Ubuntu, Cloud

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Kubernetes

**Steps to Reproduce:**
1. This was encountered when Default environment was enabled to Kubernetes environment.  
Request URL:http://104.197.31.214:8080/r/projects/1a5/kubernetes/api/v1/services
Request Method:GET
Status Code:500 Internal Server Error
Remote Address:104.197.31.214:8080

This issue was also seen in https://github.com/rancher/rancher/issues/4838

**Comment by alena1108** [comment]
@vincent99 there seems to be a bug on k8s side that i've logged as a part of https://github.com/rancher/rancher/issues/4838. To workaround it, kubernetes API container has to be restarted. It would be nice if our UI provided System page overview to take a look at / modify kuberentes system stack, even when k8s APIs is not fully available yet.

**Comment by vincent99** [comment]
I pre-request `.../api/` and make sure it returns ok to see if k8s is ready, does that really work when `.../api/v1/services` will fail?  If so I can make that the test link instead, but that's a lot more data potentially transmitted.

At some point it needs to just be an error if there's an API call that fails, I can't address every combination of calls that might fail and decide whether we can still show part of the page in that situation.  Many things are needed just to show the page header correctly.  The API isn't supposed to fail :smile:

**Comment by vincent99** [comment]
The buttons in the nav tree aren't currently dependent on k8s feature availability, since we're assuming k8s 1.4 for rancher 1.2  And the UI also now shows the errors that occur, below the header, so you can get other places.

**Comment by soumyalj** [comment]
Tested with 1.2.0-pre4-rc7 and also master. Have not seen this issue.
