### ISSUE TITLE
Remove and and re-create containers when they exit (recreate policy)

### ISSUE THREAD

**Issue by ebr** [rancher/rancher#4950]
We can select two restart policies for a service: "Start Once" or "Always". With "Always", if a container has a fatal crash, it will be restarted. With "Start Once", the container will exit and remain in a stopped state (checkered green circle in the UI).

Is it possible to get the the behaviour like "Start Once", but for the exited container to be deleted and a new one to be created in its place?
I tried using health checks for this purpose, but don't think that applies, since Rancher doesn't try to health check exited containers.

**Comment by deniseschannon** [comment]
Can you explain your use case? 

Wouldn't the new container also be exited? Are you saying that you basically want 2 containers to be created and exited?

**Comment by ebr** [comment]
The current situation I'm facing is that a crash-prone service is running in a container, but it crashes after a certain condition that might not occur for a few hours.  
In that time the container accumulates several hundred thousand log entries. If the crashed container restarts, those backlogs are dumped into our log aggregation system all at once. What i would like to do is discard the crashed container and start a fresh one in its place, instead of restarting the existing one. 

I suspect there may be other use cases for this, whereby containers should not be reused after an exit. 

For now i found a sort of an unreliable workaround by switching the service to "start once",  and using a health check with very low thresholds, which happens to trigger *most* times when the service crashes, and deletes/recreates the container when it does. But sometimes the container exits too quickly after a crash, and the health check doesn't catch it. So i have resorted to deleting the exited containers manually every few hours, at which point their replacements are created and started.

**Comment by deniseschannon** [comment]
So maybe something like start X number of times as an option? Where Rancher would attempt to start it X number of times before it stops trying?

**Comment by ebr** [comment]
When you say 'stops trying', do you mean the service will be left in a `stopped` state after trying X times and failing to start? There used to be such an option, but it was removed in 0.59 or thereabouts. It would be great to bring back it back in general, as it's quite useful when troubleshooting 'crashy' services...

In our case it wouldn't help though. Because the logs are stored with the container, the entire log since container creation would be printed on `docker logs`, or in our case, into the `logspout` service.

For our use case (and perhaps others) it would really be preferable to remove and recreate containers. Like the `Health Check -> Re-create` option, but as a "restart policy", recreate container on exit *instead of* restarting it. It would be equivalent to launching a container with `docker run --rm <...>`.

**Comment by will-chan** [comment]
@alena1108 is this doable?

**Comment by alena1108** [comment]
@will-chan to do restart vs recreate based on the container exit state, we should propagate this information from docker to cattle (agent should do it via container events). Today there is no such indication for the service; the only info it sees that the container is Stopped w/o reason why.

**Comment by ebr** [comment]
This is no longer an issue, at least not for us. The reason we wanted this behaviour was to clear all the backlogs from the container to prevent them from being dumped into stdout/stderr and overwhelming our log aggregation. Hence the request for the container to be deleted & re-created, rather than restarted. But that ended up being resolved in a different way (modified `logspout` + `journald`). At this point it would be nice to have different restart behaviour based on container exit state, but not at all critical.

(P.S. I re-read my original post and realized I initially misstated the problem. we *did* want the containers to be started after being re-created - not left in a stopped state. that would make no sense. @deniseschannon you were right, and apologies for the confusion).

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
