### ISSUE TITLE
How can update compose file  and restart stack?

### ISSUE THREAD

**Issue by Dreampie** [rancher/rancher#4952]
noway to edit conpose file

**Comment by deniseschannon** [comment]
You can export the docker-compose.yml and rancher-compose.yml and use the [rancher-compose CLI](http://docs.rancher.com/rancher/latest/en/rancher-compose/) to [upgrade services in a stack](http://docs.rancher.com/rancher/latest/en/rancher-compose/upgrading/).

There is no way to edit the docker-compose.yml directly in the UI and update a stack. You can upgrade specific services in the UI.
