### ISSUE TITLE
upgrade rancher/server to latest, admin/audit-logs got error in safari

### ISSUE THREAD

**Issue by Dreampie** [rancher/rancher#4954]
```java
66ReferenceError: Can't find variable: Intl
compileMessageTextgroup-utils.js:27
compileMessagecomputed-fallback-if-undefined.js:11
compileOptionsgroup-utils.js:8
compileArgumentgroup-utils.js:95
compileMessagegroup-utils.js:1
compilepower-select.js:604
_compilePatterngroup-utils.js:388
ogroup-utils.js:229
o
（匿名函数）power-select.js:604

```

**Comment by deniseschannon** [comment]
Can you give us more details? Where is this error happening? What is your setup?

**Comment by Dreampie** [comment]
<img width="1278" alt="qq20160531-1 2x" src="https://cloud.githubusercontent.com/assets/3667080/15661615/9c3de7be-271b-11e6-9ea7-8cc85b233067.png">

**Comment by deniseschannon** [comment]
As I mentioned in another of your issues, we need more details. 

In this question, what rancher/server version were you previously running? It looks like you have access control on, which one do you have enabled? 

What is your Rancher setup? Is it just running the container? What steps did you take to upgrade?

**Comment by Dreampie** [comment]
yeah,just runing the container,version at left-bottom of image,from v1.1.0-dev1-dev3,upgrade steps: http://docs.rancher.com/rancher/latest/en/upgrading/

**Comment by atombender** [comment]
Getting the same error here. Happens in particular when trying to go into any of the "Admin" menus. Also happens when I click upgrade on a service.

Occurred without access control enabled, and also after I enabled it (local access control).

I started a clean Rancher server from [this](http://docs.rancher.com/rancher/latest/en/quick-start-guide/) tutorial, which seems to be 1.1.0-dev3 at the moment.

**Comment by atombender** [comment]
Seems like you're using the internationalization API (`Intl`), which Safari does not implement.

![screen shot 2016-06-01 at 21 11 37](https://cloud.githubusercontent.com/assets/50314/15730761/78b6fe5c-283d-11e6-92b8-59f47be26920.png)

**Comment by deniseschannon** [comment]
@westlywright Can you take a look at this?

**Comment by tfiduccia** [comment]
Version - 6/9
Verified fixed
