### ISSUE TITLE
core files in network-agent container

### ISSUE THREAD

**Issue by gdiazlo** [rancher/rancher#4955]
**Rancher Version:**

v1.0.1
v0.8.1 network-agent image

**Docker Version:**

1.10.3
1.11.1

**OS and where are the hosts located? (cloud, bare metal, etc):**

AWS RHEL 7

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

Single node rancher, external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

Cattle

**Steps to Reproduce:**

Execute shell in network agent and ls -l /

**Results:** 

A couple of core files

**Expected:**

No core files at all.

We're seeing core files in network agents. 

gdb says:

Core was generated by `/bin/bash /var/lib/cattle/events/config.update'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f3571d0fcc9 in ?? ()

how should we proceed to further debug this behavior?

**Comment by leodotcloud** [comment]
@gdiazlo 
Could you please share the core files and also these files:
 
/var/log/haproxy-monitor.log
/var/log/rancher-net.log
/var/log/charon.log
/var/log/rancher-metadata.log
/var/log/monit.log
/var/log/rancher-dns.log
/var/log/alternatives.log
 
And the container log file too.
docker logs id_of_agent_instance > /tmp/agent_instance.log

**Comment by gdiazlo** [comment]
As we had an issue with some servers and terminated them I cannot recover logs. I have some core files I attached below. I think the issue is related to lack of resources. We were interested to know if anyone saw this.

[core-files.zip](https://github.com/rancher/rancher/files/295803/core-files.zip)

**Comment by leodotcloud** [comment]
@gdiazlo : I looked at the logs, not much information available apart from the back trace. If you happen to hit this issue again, please collect the logs. It would be helpful to know the steps to reproduce them. Can we close the issue for now and reopen if you hit it again?

**Comment by gdiazlo** [comment]
I will. I think we have another issue regarding resource exhaustion that might be related to this. But we need to do a couple of tests first and collect logs to create a new issue about it. We'll update as soon as we can.

**Comment by leodotcloud** [comment]
@gdiazlo : Do you have any updates?

**Comment by gdiazlo** [comment]
@leodotcloud sorry, i answered it by email and forgot to update here. Right now we can't do the test as we need to focus on other matters. As soon as we have the needed resources in order to do the test on a separate environment, etc. we'll update. For now, this will be on hold on our part. If we see anything like this again in our current environments we will update too.

**Comment by leodotcloud** [comment]
@gdiazlo : Sounds good.

**Comment by deniseschannon** [comment]
@gdiazlo If you still see this issue, please re-open and provide more details.
