### ISSUE TITLE
portus registry not work

### ISSUE THREAD

**Issue by Dreampie** [rancher/rancher#4956]
```shell
docker pull registry.xx.com:5000/cloud/log-service-provider:latest
latest: Pulling from cloud/log-service-provider
Digest: sha256:ca0ba088645809e9f36c21e06ee7649fbc3e90629874c0ea1c55ce2405e70eeb
Status: Image is up to date for registry.xx.com:5000/cloud/log-service-provider:latest
```

```java
Name	Repositories	Created At	             Public
cloud	0	            May 27, 2016 14:58	

```

**Comment by deniseschannon** [comment]
Did you add this registry to the registries page? 

Please provide more context of your setup/what you are trying to do as requested in other issues.

**Comment by Dreampie** [comment]
I use catalog default set，registry was catalog created，I only add the namespace

**Comment by deniseschannon** [comment]
This sounds like you were having issues with the Registry catalog entry? If so, you should look to open an issue in our [community-catalog repo](https://github.com/rancher/community-catalog) and tag the maintainer. 

Here as an existing forum post of someone who pinged the maintainer as well.

https://forums.rancher.com/t/docker-login-to-registry-server-built-from-rancher-catalog-is-not-working/2850/4
