### ISSUE TITLE
[UI] How to enable the UI to show all drivers

### ISSUE THREAD

**Issue by runseb** [rancher/rancher#4957]
Hi,

I have rancher server running a container on a docker-machine.
I run the UI locally, it reaches the server in the docker-machine via port forwarding.

Somehow when I try to add a host I only see the custom/aws/azure/do/packet and other drivers.

And the other drivers has nothing in its drop down menu.

I used to see the exoscale driver at least..

-sebastien

**Comment by deniseschannon** [comment]
In the UI on the add host page, there is a link for "Manage available machine drivers", which will bring you to the Admin -> Settings page. At the bottom of the settings page, you can see which machine drivers are active and inactive. 

For the exoscale driver, activate it and then when you go back to the Add Host page, the exoscale driver would be visible. You will be able to activate any of the other drivers in this section as well. 

Note: You must be an admin to be able to add settings.

**Comment by runseb** [comment]
Thanks for the answer...but...not quite there yet.
I am in the default environment (running the UI from source, after a fresh git clone and running `npm start`).

I setup local auth for the admin user.

I don't see anything under Admin/settings, nor do I see a link "manage available machine drivers".

I just followed the readme in github.com/rancher/ui

**Comment by deniseschannon** [comment]
What version of Rancher are you running?

Using v1.1.0-dev3

Under Admin-> Settings (towards the bottom of the page)

![screen shot 2016-06-03 at 9 38 32 am](https://cloud.githubusercontent.com/assets/11410997/15785985/0d291804-296f-11e6-8219-07e760234f46.png)

Under Infrastructure -> Hosts

![screen shot 2016-06-03 at 9 38 45 am](https://cloud.githubusercontent.com/assets/11410997/15785996/18d4ed72-296f-11e6-94d7-76a3d87e5b29.png)

**Comment by runseb** [comment]
ok got it, was on an old version somehow 1.0.7...
thanks @deniseschannon issue closed
