### ISSUE TITLE
Rancher API Key pain

### ISSUE THREAD

**Issue by scriptjs** [rancher/rancher#4961]
A current pain in providing a repeatable Rancher setup for developers, devops, testers, and qa personnel is that you cannot fully script the installation, setting hosts and containers without first having an API key.  

Whether you are starting from vagrant or from native docker, scripting a reproducible Rancher in a completely automated way is not possible since you can only get an API key from the gui once installed.

There is value in finding a solution. Native docker for mac and windows is making it easier for everyone on the team to be running a local Rancher. Rancher is becoming a cross discipline tool that can unite the team around a common understanding of what they are building and to play their part in it.

Hopefully this gets resolved so that we can provide personnel with no more than a link that will run a script to bring everything onto their system, even if at best this becomes an alternate install.

**Comment by aemneina** [comment]
Hey @scriptjs,

You should be able to get the keys to the system with ease. Executing the following using cURL will generate, and return, the API and Secret Keys. This was done on a fresh install/deployment of rancher. No UI required.

```
$ curl -v -X POST -H 'Accept: application/json' -H 'Content-Type: application/json' -d '{"type":"apikey","accountId":"1a5","name":"admin","description":null,"created":null,"kind":null,"removed":null,"uuid":null}' http://URI_FOR_RANCHER_SERVER:8080/v1/projects/1a5/apikey
```

returned:
```
{
	"id": "1c2",
	"type": "apiKey",
	"links": {
		"self": "http://URI_FOR_RANCHER_SERVER:8080/v1/projects/1a5/apikeys/1c2",
		"account": "http://URI_FOR_RANCHER_SERVER:8080/v1/projects/1a5/apikeys/1c2/account",
		"images": "http://URI_FOR_RANCHER_SERVER:8080/v1/projects/1a5/apikeys/1c2/images",
		"instances": "http://URI_FOR_RANCHER_SERVER:8080/v1/projects/1a5/apikeys/1c2/instances",
		"certificate": "http://URI_FOR_RANCHER_SERVER:8080/v1/projects/1a5/apikeys/1c2/certificate"
	},
	"actions": {
		"activate": "http://URI_FOR_RANCHER_SERVER:8080/v1/projects/1a5/apikeys/1c2/?action=activate",
		"remove": "http://URI_FOR_RANCHER_SERVER:8080/v1/projects/1a5/apikeys/1c2/?action=remove",
		"deactivate": "http://URI_FOR_RANCHER_SERVER:8080/v1/projects/1a5/apikeys/1c2/?action=deactivate"
	},
	"name": "admin",
	"state": "registering",
	"accountId": "1a5",
	"created": "2016-05-31T05:42:33Z",
	"createdTS": 1464673353000,
	"description": null,
	"kind": "apiKey",
	"publicValue": "<YOUR_PUBLIC_KEY>",
	"removed": null,
	"secretValue": "<YOUR_SECRET_KEY>",
	"transitioning": "yes",
	"transitioningMessage": "In Progress",
	"transitioningProgress": null,
	"uuid": "083cff37-9059-4cc3-9af6-25c374909907"
}
```

**Comment by vincent99** [comment]
There key here is that access control is disabled so access to the API is unrestricted on initial install.

You probably want an account API key instead of an environment though... /v1/apikeys

**Comment by deniseschannon** [comment]
@scriptjs Please reopen if you have further questions

**Comment by donfirst** [comment]
@aemneina  Thank you for your help.This is exactly what I was looking for :-)
Do you know how to change authentication metod on clean installation  from empty to local and how to set first admin account ?
Pete

**Comment by vincent99** [comment]
http://docs.rancher.com/rancher/v1.2/en/api/access-control/

**Comment by donfirst** [comment]
Thank you :-) One more question  how can I generate Account api key using curl ?

**Comment by donfirst** [comment]
Problem is that there is no working example on their website . And no everyone is a developer :-(

**Comment by donfirst** [comment]
Hi Mate,
After whole day of fighting I  wrote my own solution . Please keep in mind that I'm not a developer , but this solution work in 100%. I need way how to send back the token variables .
If somebody here can improve this script , it would be great.

How to run - just script name and rancher server ip as a parameterr

!/bin/bash
#Get Depenndencies
serverip="http://"$1":8080"
until [[ $(curl -s -o /dev/null -w "%{http_code}" $serverip) == "200" ]]; do sleep 5; done

wget http://stedolan.github.io/jq/download/linux64/jq
#Register Account API Key
curl -u "${RANCHER_ACCESS_KEY}:${RANCHER_SECRET_KEY}" \
-X POST \
-H 'Content-Type: application/json' \
-d '{
        "description": "string",
        "name": "string"
}' $serverip'/v1/apiKeys' > tmp.txt
cat tmp.txt |cut -d ',' -f19,19 | cut -d ':' -f2 |tr -d '"' > public
cat tmp.txt |cut -d ',' -f22,22 | cut -d ':' -f2 |tr -d '"' > secret
read public < public
read secret < secret
echo $public
echo $secret
curl -s -u $public:$secret $serverip/v1/projects | jq -r ".data[0].id" > projectid
read PROJECT_ID < projectid
curl -s -X POST -u $public:$secret $serverip/v1/registrationtokens?projectId=$PROJECT_ID
curl -s -u $public:$secret $serverip/v1/registrationtokens?projectId=$PROJECT_ID | jq -r '.data[0].token' > register
read register < register
docker run -d --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.0.2 $derverip/v1/scripts/$register
