### ISSUE TITLE
Load balancer do not have rancher DNS provisioned

### ISSUE THREAD

**Issue by miv** [rancher/rancher#4962]
**Rancher Version:** v1.1.0-dev3

**OS and where are the hosts located? (cloud, bare metal, etc):** Bare metal

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:**

Create load balancer with label `io.rancher.container.dns: true`

**Results:** 

No rancher dns server in resolv.conf

```
cat /etc/resolv.conf

nameserver 8.8.8.8
nameserver 8.8.4.4
```

**Expected:**

Something like this (taken from ordinary container)

```
search lb.rancher.internal lb.lb.rancher.internal rancher.internal
nameserver 169.254.169.250
```

**Wait. But WHY?!?**

I want to add local, internal syslog for haproxy logs. For example something like: `log my_syslog.rancher.internal local0`

**Comment by deniseschannon** [comment]
By design, we didn't enable internal DNS for load balancers. Instead of using the service name for the DNS, we use their IPs.

I've updated this as an enhancement request.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
