### ISSUE TITLE
custom stack why not upload answers.txt,it's default value?

### ISSUE THREAD

**Issue by Dreampie** [rancher/rancher#4963]

**Comment by deniseschannon** [comment]
What do you mean by custom stack? 

I have noticed that you have asked a lot of questions as issues recently, but it is very hard for us to assist when you provide limited information.

Details that would help in each issue:
1. Rancher version
2. Docker version
3. OS of your hosts

More detailed steps of what you are trying to do. For example, in this issue, I don't know what you mean by "custom stack" and where are you trying to start this custom stack? Are you using the UI or CLI?

**Comment by Dreampie** [comment]
yeah,
rancher version=v1.1.0-dev3
docker version=1.11.1
os=ubuntu 16.04
I using ui add stack,must upload docker-compose,rancher-compose,but stack catalog contains a `answers.txt` to storage variable，custom add stack not this mean that I can't use variable like `${var_name}`

**Comment by deniseschannon** [comment]
This is by design, if you want to customize the stack, you should replace the environment interpolated variables with the value that you'd like. There is no place in add stack for the values.

**Comment by vincent99** [comment]
There's no reason there can't be though, it's an option in the API...

**Comment by vincent99** [comment]
Answers can be provided in 2.0 compose import.
