### ISSUE TITLE
catalog/registry  not support remote mysql connection?

### ISSUE THREAD

**Issue by Dreampie** [rancher/rancher#4964]

**Comment by deniseschannon** [comment]
What do you mean by remote mysql connection?

How are you trying to link the catalog to it?

**Comment by Dreampie** [comment]
I custom regitry stack and rewrite mysql host,use my own databse,not stack own db container,like rancher  like remote mysql host.

**Comment by deniseschannon** [comment]
Can you share your docker-compose.yml of your custom stack?

**Comment by Dreampie** [comment]
only  change database config with my mysql:
```
    PORTUS_PRODUCTION_DATABASE: cloud-portus
    PORTUS_PRODUCTION_HOST: mysql.infra.xx.com 
    PORTUS_PRODUCTION_PASSWORD: godmode
    PORTUS_PRODUCTION_USERNAME: debugger
```

**Comment by deniseschannon** [comment]
I woudl recommend opening an issue in the [community catalog](https://github.com/rancher/community-catalog) and seeing if the maintainer will help you.

Currently, Rancher is not providing direct support on community catalog entries as they are provided by the community. We only directly ssupport the certified templates.
