### ISSUE TITLE
VSphere machine gets wrong ip

### ISSUE THREAD

**Issue by guzmo** [rancher/rancher#4965]
**Rancher Version:**
1.0.1
**Docker Version:**
1.10.3
**OS and where are the hosts located? (cloud, bare metal, etc):**
Datancenter
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA Rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Swarm

When we request new VSpheres we get wrong ip on em. Currently we are getting the loadbalancers ip. If we knew how you got the ip we would be able to debug and see why we get this ip instead of the machines ip.

Any help would be appreciated.

**Comment by lesaux** [comment]
I noticed this as well. I logged into a boot2docker vsphere machine and ran the container with -e CATTLE_AGENT_IP $ip_address and that worked.

**Comment by guzmo** [comment]
Ye that is what we are doing too but would be nice to be able to request them without workarounds.

**Comment by vincent99** [comment]
If the agent is not given an explicit IP (CATTLE_AGENT_IP) then it is auto-registered using the address the request to the server comes in on.
