### ISSUE TITLE
Cross-host networking breaks when >683 containers are launched

### ISSUE THREAD

**Issue by LLParse** [rancher/rancher#4966]
**Rancher Version:**
v1.1.0-dev2-rc5

**Docker Version:**
1.10.0

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 15.10, GCE

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
2nd gen (external) MySQL DB, db-n1-standard-1
Rancher server 2 vCPUs, 4 GB memory, 50 GB disk
1x Host with 8 vCPUs, 52GB memory
3x Host with 6 vCPUs, 30GB memory

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Create the Rancher environment according to setup specifications
Launch >683 containers that communicate with at least one other container on a different host

**Results:** 
When launching the 684th container, DNS resolution breaks and cannot ping the container from various hosts' Network Agents

**Expected:**
Networking works

**Comment by deniseschannon** [comment]
Closing as networking has been re-done to use CNI for 1.2.0.
