### ISSUE TITLE
Should both ports 443 and 80 be accessible when you create an ingress with TLS spec ??

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#4968]
**Rancher Version:**: Master

**OS and where are the hosts located? (cloud, bare metal, etc):** Ubuntu, cloud

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**: Kubernetes

**Steps to Reproduce:**
1. Create a Kubernetes environment
2. Create a secret and an ingress with the secret specified.

**Results:** 
We can access the ingress LB at port 443 and also at port 80.
Should both ports 80 and 443 be accessible when you create an ingress with TLS spec ??

**Comment by alena1108** [comment]
@soumyalj we are going to allow optionally disable access to http port using allow.http annotation (true by default), similar how gce ingress controller does it: [gce controller doc](https://github.com/kubernetes/contrib/tree/master/ingress/controllers/gce), refer to "Blocking HTTP" section

**Comment by alena1108** [comment]
@soumyalj please test using alena1108/ingress-controller:v0.1.4 image

**Comment by soumyalj** [comment]
Verified on Master with the image alena1108/ingress-controller:v0.1.4 image. With annotation      ```allow.http: "false" ``` in the ingress, access to port 80 is disabled.
