### ISSUE TITLE
Repository definitions not working as expected when pulling image, please clarify

### ISSUE THREAD

**Issue by sshipway** [rancher/rancher#4969]
**Rancher Version:** 1.1.0-dev1

**Docker Version:** 1.9.1

**OS and where are the hosts located? (cloud, bare metal, etc):** CoreOS stable; VMware

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single node, internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:**
Set up a local registry (myreg.company.com) and upload an image ( myreg.company.com/me/image:latest ) to a Public namespace.  This namespace/image should NOT already exist in Dockerhub.

In the Rancher Environment, DO NOT define the local registry, only dockerhub.

Create a new service using image me/image:latest.  This fails as expected (as the image does not exist in DockerHub)

Create a new service using image myreg.company.com/me/image:latest.  This works; however since the registry was NOT defined, it should be denied (as this registry is not approved for this Environment).

Now define the local registry in Rancher, so it knows about myreg.company.com, with NO credentials.

Create a new service using image me/image:latest.  This fails; however it should work as Rancher is expected to try the local registry as well when given an imagename without a registry?

**Summary:** it is unclear how Rancher should behave in situations where an imagename includes a registry location, or when multiple registries are defined and an imagename does not include a registry, and when registries are defined but not including Docker Hub.  Is there a way to tell Rancher to NOT use DockerHub?  Is a link to Dockerhub implicit if no registries are defined but required if some are?

We have a specific use case: for our Production Environment, we would like to define our local registry and DISABLE Docker Hub.  Then, we would copy over approved images (including the rancher agent image) from DockerHub to the local registry.  We would like to enforce that only images in our private registry can be used in the environment, but currently it looks like there is no way to do this; moreover we cannot make Rancher invisibly use our registry as a second default search location.

Please clarify exactly how Rancher is designed to behave in these situations, and if the observed behaviour is as intended or not.

Thanks!

**Comment by soumyalj** [comment]
Tested with v1.2.0-pre4-rc4. Whitelist and default registries are supported. 
With a registry on amazon/quay of format 605812495337.dkr.ecr.us-east-1.amazonaws.com/xyzrepo. Image pulls were successful with the registries defined in Rancher.
As described in the summary above, we can create : 
default registry => quay.io
whitelist list registry => quay.io, 605812495337.dkr.ecr.us-east-1.amazonaws.com

Images can be specified using the quay.io/xyz/image or 605812495337.dkr.ecr.us-east-1.amazonaws.com/xyz/image
If no registry is specified, images will be pulled from quay.io
Images cannot be pulled from docker.io in this case
