### ISSUE TITLE
Allow changing system and community catalog urls

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#4970]
We should let user override even default catalog urls - system ("library") and "community" - to the private github repo. This is to support Rancher in no internet mode.

Today UI doesn't display "library"/"community" although I can see API returning it:

```
GET http://localhost:8080/v1/settings/catalog.url
{"id":"1as!catalog.url","type":"activeSetting","links":{"self":"http://localhost:8080/v1/activesettings/1as!catalog.url"},"actions":{},"name":"catalog.url","activeValue":"library=https://github.com/rancher/rancher-catalog.git,community=https://github.com/rancher/community-catalog.git","inDb":false,"source":"Code Packaged Defaults","value":"library=https://github.com/rancher/rancher-catalog.git,community=https://github.com/rancher/community-catalog.git"}
```

@vincent99

**Comment by vincent99** [comment]
On my phone but it should just work if you set them to false and pass them in as custom below.  It might not display right when you come back though.

**Comment by vincent99** [comment]
Checked and this works fine, and emphasizes that you aren't using our repos.. Disable the Rancher ones and add custom `library` and `community` entries with the appropriate URLs.

**Comment by soumyalj** [comment]
Tested with master and able to override system and community catalog( Used the catalog https://github.com/llparse/testing-catalog. )
