### ISSUE TITLE
rancher-compose does not exit on success

### ISSUE THREAD

**Issue by wolli-lenzen** [rancher/rancher#4973]
*Describe your issue here*
I call rancher-compose (v0.8.2) from a linux shell script to setup a stack. All works fine, but after the project is started, rancher-compose does not exit, but keeps on running until I press <CTRL>+C 

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.1.0-dev3` Cattle: `v0.161.5` UI: `v1.1.3` Compose: `v0.8.2` |
|Access|`Disabled`|
|Orchestration|`Cattle`|
|Route|`certificates.index`|

**Comment by samattridge** [comment]
You'll be after the '-d' switch on the 'up' command.  Have a look at this link: http://docs.rancher.com/rancher/latest/en/rancher-compose/commands/

Scroll down to "Command Options" and you'll see all the options there.

**Comment by wolli-lenzen** [comment]
oh, thanks - I didn´t saw that :-)
