### ISSUE TITLE
If username for external database has %, rancher server doesn't work.

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#4979]
**Steps to Reproduce:**
Try to launch Rancher server with an external DB that has a % in the username. 

```
sudo docker run -d --restart=always -p 8080:8080 \
    -e CATTLE_DB_CATTLE_MYSQL_HOST=ranchercluster.cn \
    -e CATTLE_DB_CATTLE_MYSQL_PORT=3306 \
    -e CATTLE_DB_CATTLE_MYSQL_NAME=cattle \
    -e CATTLE_DB_CATTLE_USERNAME=ranchercluster%cattle \
    -e CATTLE_DB_CATTLE_PASSWORD=cattle \
    rancher/server
```

**Results:** 

```
14:50:34.831 [main] ERROR i.c.p.a.sources.LazyJDBCSource - Failed to get connection to database, will retry for 5 minutes
org.apache.commons.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (Could not connect to ranchercluster.cn:3306: Connection reset)
        at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1549) ~[commons-dbcp-1.4.jar:1.4]
        at org.apache.commons.dbcp.BasicDataSource.createDataSource(BasicDataSource.java:1388) ~[commons-dbcp-1.4.jar:1.4]
```

But it seems % is a supported character in mysql username. If we try docker exec to go inside container and use mysql client directly, we can connect successfully. So the problem may be related to the jdbc connection string parse. We have tried several methods but had no luck, which includes:
 
1.     Tried url encoding by setting the username as ranchercluster%25cattle
2.     Tried to add ‘’ or “” around the username with url encoding, just like ‘ranchercluster%25cattle’.

**Expected:**
Rancher external DB to be able to support `%` in the username.

**Comment by cloudnautique** [comment]
I have attempted to reproduce without success.

Which versions of mysql/maria/etc are you using?

Steps I followed:

```
docker run -d --name database mysql  (this pulls 5.7.12)
docker run -d --link database:mysql -e CATTLE_DB_CATTLE_MYSQL_USERNAME=ranchercluster%cattle rancher/server (Pulls v1.1.0-dev3)
```

**Comment by cloudnautique** [comment]
Verified again with Rancher v1.2.0-pre3 and can not reproduce. 

Steps:
1. ) Create MySQL:
`docker run -it -e MYSQL_DATABASE=cattle -e MYSQL_USER=user1%cattle -e MYSQL_PASSWORD=password -e MYSQL_ROOT_PASSWORD=password mysql`

2.) Run Rancher Server:
`docker run -it -e CATTLE_DB_CATTLE_USERNAME=user1%cattle -e CATTLE_DB_CATTLE_PASSWORD=password --link mad_elion:mysql rancher/server:v1.2.0-pre3`

Recommend closing, if QA can not reproduce.

**Comment by cloudnautique** [comment]
If we can get more information from if this happens again:
1. MySQL version
2. Shell the docker command is run from
3. Rancher version

that would be helpful.

**Comment by soumyalj** [comment]
Tested with rancher version v1.2.0-rc4-pre4. Followed the steps above. Used username soumya%cattle for the external mysql database. I was able to run the rancher server successfully. Service/container creation was fine too on a one host setup.
MySQL info:
```
mysql> SHOW VARIABLES LIKE "%version%";
+-------------------------+------------------------------+
| Variable_name           | Value                        |
+-------------------------+------------------------------+
| innodb_version          | 5.6.27                       |
| protocol_version        | 10                           |
| slave_type_conversions  |                              |
| version                 | 5.6.27-log                   |
| version_comment         | MySQL Community Server (GPL) |
| version_compile_machine | x86_64                       |
| version_compile_os      | Linux                        |
+-------------------------+------------------------------+
7 rows in set (0.14 sec)
```
