### ISSUE TITLE
When upgrading LB with rancher-compose get a 500 error

### ISSUE THREAD

**Issue by qgriffith** [rancher/rancher#4980]
When ever I upgrade load balancers using rancher-compose I get a 500 error. I am able to access the URL that gets the 500 error with out a issue using a browser and curl -I to get the header. I always get a 200 when I test the URL. I noticed in the UI there isn't a way to upgrade a load balancer. Is this something that isn't allowed? I am running into the issue because I exported the docker-compose.yml file from the rancher UI and am using it via jenkins to do upgrades to services. The LB config is in the docker-compose.yml so during an upgrade it gets called.  Maybe rancher-compose should ignore any LB in the config?

time="2016-06-01T14:01:30-04:00" level=error msg="Failed to start: consul-lb : Bad response statusCode [500]. Status [500 Server Error]. Body: [code=Internal Server Error, message=Internal Server Error] from [http://rancher.REDTRACTED.com:8080/v1/loadbalancerservices/1s34]" 

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.0.2` Cattle: `v0.159.8` UI: `v1.0.5` |
|Access|`github` `admin`|
|Route|`environments.index`|

**Comment by qgriffith** [comment]
I think I have found the answer. When doing an upgrade I should pass the name of each service versus using everything in the docker-compose.yml file. This will prevent the load balancer from being upgraded.

**Comment by deniseschannon** [comment]
Yes, if you have the LB in your docker-compose and you try to upgrade using rancher-compose CLI, it will try to upgrade all services (including LBs) in your docker-compose.yml. 

Do you still have further questions?

**Comment by deniseschannon** [comment]
@qgriffith Please re-open if you have further questions.
