### ISSUE TITLE
Rancher v1.0.2 fails to register host behind ELB

### ISSUE THREAD

**Issue by bigjhnny** [rancher/rancher#4981]
**Rancher Version:**
v1.0.2

**Docker Version:**
rancher server: 1.11.1
agent host: 1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
ec2

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher, RDS

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
cattle

**Steps to Reproduce:**
1. Install rancher server
2. create ELB and install proxy protocol, put server behind ELB
3. browse the UI fine through the ELB endpoint and see everything is working

**Results:** 
When registering host, agent logs show:
2016-06-01T19:05:50.459327985Z time="2016-06-01T19:05:50Z" level="fatal" msg="Get http://rancher-lb-1393642374.us-east-1.elb.amazonaws.com/v1: dial tcp 52.21.247.172:80: i/o timeout"

I'm able to register new hosts directly through the public IP of the server instance.  But when going through the ELB, things slow down and agent does not seem to be able to communicate with server.  

Server logs show:
2016-06-01T19:26:44.767625003Z 2016-06-01 19:26:44,767 ERROR [:] [] [] [] [ecutorService-5] [i.c.p.a.s.ping.impl.PingMonitorImpl ] Scheduling reconnect for [8]
2016-06-01T19:26:49.766891712Z 2016-06-01 19:26:49,766 ERROR [:] [] [] [] [ecutorService-5] [i.c.p.a.s.ping.impl.PingMonitorImpl ] Failed to get ping from agent [8] count [7]
2016-06-01T19:26:54.767500929Z 2016-06-01 19:26:54,767 ERROR [:] [] [] [] [ecutorService-8] [i.c.p.a.s.ping.impl.PingMonitorImpl ] Failed to get ping from agent [8] count [8]
2016-06-01T19:26:59.768361918Z 2016-06-01 19:26:59,767 ERROR [:] [] [] [] [ecutorService-9] [i.c.p.a.s.ping.impl.PingMonitorImpl ] Failed to get ping from agent [8] count [9]
2016-06-01T19:30:18.619911673Z 2016/06/01 19:30:18 http: proxy error: net/http: request canceled

Note that browsing through the UI, I had occasional timeout errors from the rancher UI.

ELB Configuration:
ubuntu@ip-10-0-0-186:~$ aws elb describe-load-balancers --load-balancer-name rancher-lb --output=json
{
    "LoadBalancerDescriptions": [
        {
            "Subnets": [
                "subnet-07e0c971",
                "subnet-a4e9978e"
            ],
            "CanonicalHostedZoneNameID": "Z3DZXE0Q79N41H",
            "CanonicalHostedZoneName": "rancher-lb-1393642374.us-east-1.elb.amazonaws.com",
            "ListenerDescriptions": [
                {
                    "Listener": {
                        "InstancePort": 8080,
                        "LoadBalancerPort": 80,
                        "Protocol": "TCP",
                        "InstanceProtocol": "TCP"
                    },
                    "PolicyNames": []
                },
                {
                    "Listener": {
                        "InstancePort": 8080,
                        "SSLCertificateId": "arn:aws:acm:us-east-1:273577629809:certificate/fc582d56-6bba-41e4-88d4-e482a1214f60",
                        "LoadBalancerPort": 443,
                        "Protocol": "SSL",
                        "InstanceProtocol": "TCP"
                    },
                    "PolicyNames": [
                        "AWSConsole-SSLNegotiationPolicy-rancher-lb-1464800575747"
                    ]
                }
            ],
            "HealthCheck": {
                "HealthyThreshold": 10,
                "Interval": 30,
                "Target": "HTTP:8080/ping",
                "Timeout": 5,
                "UnhealthyThreshold": 2
            },
            "VPCId": "vpc-2a2bfc4d",
            "BackendServerDescriptions": [
                {
                    "InstancePort": 80,
                    "PolicyNames": [
                        "my-ProxyProtocol-policy"
                    ]
                },
                {
                    "InstancePort": 8080,
                    "PolicyNames": [
                        "my-ProxyProtocol-policy"
                    ]
                }
            ],
            "Instances": [
                {
                    "InstanceId": "i-4ba174d7"
                }
            ],

**Expected:**
Should be able to register host.  Something with proxy protocol isn't working.

**Comment by aemneina** [comment]
Troubleshooting steps taken:
Ran nslookup on the ELB, queried each IP of LB. 
result: One IP would come back unresponsive.

Looked similar to this issue:
https://forums.aws.amazon.com/message.jspa?messageID=535913

@bigjhnny recreated subnets in each AZ, and issue hasn't resurfaced yet.

I'll close the ticket, if it comes back up, we can reopen.

**Comment by bigjhnny** [comment]
Recreating the subnets in AWS worked!  Thanks Almad!
