### ISSUE TITLE
Cannot get agent to connect after upgrading docker

### ISSUE THREAD

**Issue by dnadave** [rancher/rancher#4982]
**Rancher Version:** v1.1.0-dev3

**Docker Version:** 1.11.1

**OS and where are the hosts located? (cloud, bare metal, etc):** OpenSuSE Leap 42.1 on bare metal

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node with server and agent on same host using an external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Upgraded docker from 1.0.9 to 1.11.1 (to handle the new docker.io setup)
Rancher restarted and agent never connected
Stopped server and upgraded server
Agent did not upgrade from 0.11.0 to 1.0.1
Forced stop of agent, pulled new version, and attempted reconnect
Agent does not start

**Results:** 
We have a server running with our old configuration.  No agent, hence no host.  Attached is a copy of the log from the server.  Why us localhost refusing connection?  We do not have Axiohost13 set as the servername, not localhost.  Why is port 8081 requested?  It wasn't before?  When was that announcement made?

**Expected:**
Upgrade to work flawlessly as advertised.

[rancher_error.txt](https://github.com/rancher/rancher/files/294182/rancher_error.txt)

**Comment by dnadave** [comment]
Great.  I can't even do that.  If I start up a server using my data container, I can connect to the server.  If I start up a server with no data container, I get a connection refused error.

So, we're screwed until someone at Rancher decides to actually read the issue board, which could be days from past experience.

**Comment by dnadave** [comment]
Looking at the log of the agent, there is only one line:

`AxioHost13:/home/dnadave # docker logs cc67
Error response from daemon: 400 Bad Request: malformed Host header`

It seems related to this thread:

https://forums.rancher.com/t/on-agent-start-error-response-from-daemon-400-bad-request-malformed-host-header/2522

but I'm not using Ubuntu and I have only one server running 1.11.1.

**Comment by dnadave** [comment]
Or, is this the issue?

https://github.com/rancher/rancher/issues/4500#issuecomment-213071348

`AxioHost13:/home/dnadave # docker version
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.6.1
 Git commit:   9e83765
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.6.1
 Git commit:   9e83765
 Built:        
 OS/Arch:      linux/amd64`

**Comment by ibuildthecloud** [comment]
@dnadave Docker 1.11.x is not yet supported.  It will be supported hopefully in dev4 or dev5.  Having said that I don't believe that is your issue.  If you are getting `400 Bad Request: malformed Host header` that means you have an invalid Docker daemon.  If you are running official Docker binaries from releases.docker.com you won't have this issue.  I assume you are running Docker that is packaged with SuSE?

**Comment by dnadave** [comment]
I don't see how the malformed header could be a docker issue versus a
rancher issue.  We can start/stop/pull/push containers with our current
installation.  So, how is it invalid?  I think we require a better
explanation to believe that.

We're not using the official OpenSuSE Leap installation as that is
currently at 1.9.0 and docker needs us to be at 1.10.0 after yesterday.
So, we are using one of the unofficial official installations from
OpenSuSE.  Given that, we're stuck choosing between 1.9.0 and 1.11.1.
Those are our only options at the moment.

**Comment by vincent99** [comment]
Older versions of docker and and expect a Host header that violates the HTTP spec.. We use an older client on the agent for maximum compatibility.  But whoever compiled the docker you're running did it with Go 1.6, which adds validation that prevents the invalid header from being passed through.

The official docker packages are compiled with 1.5, specifically for this reason.

**Comment by cloudnautique** [comment]
@dnadave, can you verify the version of Go lang docker was compiled with? `docker version` should output Go version. If it was compiled with Golang 1.6, like Ubuntu 16.04 was, see this issue docker/docker#20865 for background.

**Comment by dnadave** [comment]
It is compiled with golang 1.6.

**Comment by deniseschannon** [comment]
@dnadave With the release of v1.1.1 and our support for Docker 1.11, then the golang 1.6 issues should be resolved. 

Please retry and re-open if you have issues.
