### ISSUE TITLE
Adding EC private key to load balancer crashes it

### ISSUE THREAD

**Issue by ruimarinho** [rancher/rancher#4984]
**Rancher Version:**

v1.1.0-dev3

**Docker Version:**

**OS and where are the hosts located? (cloud, bare metal, etc):**

Cloud, Ubuntu 14.04.3.

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

Single node rancher.

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

Cattle

**Steps to Reproduce:**

Go to Infrastructure > Certificates > Add Certificate > Paste an EC private key on the "Private Key" field. E.g.:

```
-----BEGIN EC PARAMETERS-----
…
-----END EC PARAMETERS-----
-----BEGIN EC PRIVATE KEY-----
…
-----END EC PRIVATE KEY-----
```

Launch a Load Balance and select the newly created certificate. 

**Results:** 

Confirm that the HAProxy load balancer has a private `.pem` file with only the following content which it is unable to read (crashes due to "unable to load SSL certificate from pem file"):

```
-----BEGIN EC PARAMETERS-----
…
-----END EC PARAMETERS-----
```

The container is never actually on an error state as the config is endlessly retried, but I think that's a separate issue.

**Expected:**

The private key is correctly set on the container.

**Comment by deniseschannon** [comment]
This error `unable to load SSL certificate from pem file` is coming from haproxy. Are you sure that haproxy (software that we use in our load balancer) is able to support this type of certificate?

**Comment by ruimarinho** [comment]
My guess is that openssl 1.0.1f is not being able to read this file. However, I would like to note that the private key is being stored incorrectly - it is missing content (the actual private key).

**Comment by ruimarinho** [comment]
@deniseschannon were you able to confirm the issue regarding the private key not being correctly copied to the container?

**Comment by roderik** [comment]
Just chiming in, I've got the same problem. The second part of the private key is not in server.pem while it is entered in the gui.

**Comment by roderik** [comment]
Any news on this @deniseschannon ?

**Comment by will-chan** [comment]
@alena1108 can you look into whether this is a real issue or not?

**Comment by alena1108** [comment]
@will-chan this bug should be resolved with refactored LB. Looks like in the past we used to parse the certificate key incorrectly on the cattle side. In refactored code, we just respect whatever is passed via cert.key content: https://github.com/rancher/lb-controller/blob/a51dfa6b8088e91659bd05ca53457b6f6d65ffd4/controller/rancher/rancher.go#L443 and https://github.com/rancher/lb-controller/blob/1bfa8d7d885882beebfd876001f59ed126a1a46f/provider/haproxy/haproxy.go#L120

**Comment by galal-hussein** [comment]
Rancher server: master

I was able to test with a self signed EC certificate, the LB service created and worked as expected with the loaded ec crt/key.
