### ISSUE TITLE
stack create with blocking state

### ISSUE THREAD

**Issue by demohi** [rancher/rancher#4986]
![image](https://cloud.githubusercontent.com/assets/1209159/15768033/09202e6c-2980-11e6-8512-007180c176af.png)

Docker version 1.11.2

rancher with HA

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.1.0-dev3` Cattle: `v0.161.5` UI: `v1.1.3` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`environment.index`|

**Comment by deniseschannon** [comment]
Did you add a docker-compose.yml and rancher-compose.yml when you tried to add a stack? If so, there is most likely a yaml error in your files that is blocking it from succeded. 

You can copy the same yml files and use [rancher-compose](http://docs.rancher.com/rancher/latest/en/rancher-compose/) CLI to test out your yaml files. The errors would surface using the CLI. 

There's an open issue to have the errors from the parsing to surface to Rancher UI when creating stacks. 
https://github.com/rancher/rancher/issues/3950

**Comment by deniseschannon** [comment]
@demohi If you are still facing issues, please re-open and provide the requested information
