### ISSUE TITLE
Require Rancher to allow Kubernetese hooks into cloud platforms to work.

### ISSUE THREAD

**Issue by t5unamie** [rancher/rancher#4988]
**Rancher Version:**

v1.1.0-dev3

**Docker Version:**

Docker version 1.11.2

**OS and where are the hosts located? (cloud, bare metal, etc):**

Ubuntu

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

single node rancher && internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

Kubernetes

**Steps to Reproduce:**

Using a simple Kubernetese template where load balancer is stated or volumes, the system should allow kubernetese to talk to the cloud provider. As shown in an example below.

{code}
apiVersion: v1
kind: Service
metadata:
  name: artifactorysvc
  labels:
    app: artifactory
spec:
  ports:
- port: 9001
  protocol: TCP
  name: http
  targetPort: 8080
  selector:
    app: artifactory
  ---
  apiVersion: v1
  kind: ReplicationController
  metadata:
  name: artifactory
  spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: artifactory
    spec:
      containers:
      - name: artifactory
        image: mattgruter/artifactory
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /artifactory
          name: data
      volumes:
        - name: data
        # This AWS EBS volume must already exist.
          awsElasticBlockStore:
            volumeID: EXAMPLE
            fsType: ext4
  {code}
  **Results:** 

The EBS volume is not mounted or the ELB is not created as expected.

**Expected:**

The EBS volume should be mounted and follow the container or the ELB is should be created and routes requests to all the kubeproxy instances.

**Comment by alena1108** [comment]
@t5unamie EBS support will be enabled in the upcoming Rancher dev4 release. As long as your AWS host has the correct IAM role (allowing to make AWS calls on behalf of your account), the feature should work. See more details here: https://github.com/rancher/rancher/issues/4444

**Comment by deniseschannon** [comment]
@galal-hussein Could you test out EBS + ELB?

**Comment by galal-hussein** [comment]
@deniseschannon I tested EBS mounting in #4444, i don't know how to test the ELB feature, correct me if i am wrong but when creating a service with Type LoadBalancer, Rancher will create load balancer service in the platform itself not in aws.

**Comment by will-chan** [comment]
@wlan0 have we added support for this now?

**Comment by wlan0** [comment]
@will-chan yes. This is supported. EBS volumes can be used if the user chooses cloud-provider=aws when creating a kubernetes environment

**Comment by deniseschannon** [comment]
@wlan0 Could you add some docs on how to do that step to the documentation?

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
