### ISSUE TITLE
Please provide API and GUI option to commit running container and push to registry 

### ISSUE THREAD

**Issue by adaikal** [rancher/rancher#4989]
Hi,

I have been wondering whether it would be possible for you to provide option to commit running container and push it to registry.

USE CASE: Upgrading option is good with app containers as new containers are launched and old containers are removed.

But in the case of databases, we could do the same(outage of few milliseconds to seconds ,might be involved, just a guess). I like the idea of executing into database container shell and do CRUD operations in the DB and then exit. As docker containers are immutable images, I'd like it to get committed through "docker commit" and pushed into registry.

**Comment by deniseschannon** [comment]
I don't completely understand your use case. When you start a new container from an image (and you have the DB in the image), the DB would end up being a brand new DB each time. 

If you are looking to upgrade how your DB is setup, then you'd need to update the Dockerfile that the image is based on. 

At this time, Rancher is not managing the Dockerfiles of the images that containers are run for.

**Comment by adaikal** [comment]
May be I'm not clear enough. Assume a mysql db is running. And assume I have added a new table in the mysql db for the app to use. Now, how do I upgrade my db container which already have client data.

**Comment by Rucknar** [comment]
@adalkai - Are you wanting to store the data within the DB and have it be ported to the registry often? Or is this just schema that changes infrequently?

Typically that's not a use-case i've seen tackled in that way in the past, if it's just the schema stuff, one possible alternative would be have a 'run-once' container with your schema updates in that you could execute on demand to populate a vanilla DB instance?

**Comment by adaikal** [comment]
@Rucknar Definitely not wanting to port db with data to registry. The data will be staying on the server as data volume or data container.

I'm working on an automation, provided an database_initialization script for mysql image, a database image will be created by CI server and pushed to private registry. Then launch the database container using rancher.

Challenge is how to upgrade an existing database container with new schema:
1) Create an updated database image with new schema and then launch a new db container and stop old db container?
2) Exec into existing db container and change schema and then commit that existing container and push it to registry?

I know, first point makes more sense but with current use case I cannot use docker/rancher compose.

Or I may be confusing totally!. How do you upgrade a database container? say from mysql version x to version y, if not schema, without interruption?

**Comment by deniseschannon** [comment]
@adaikal This issue would be better asked in our forums, https://forums.rancher.com, as I don't believe your use case is common and questions like this would be better asked in the forums.
