### ISSUE TITLE
Default Vagrantfile does not expose API/UI port

### ISSUE THREAD

**Issue by cgswong** [rancher/rancher#499]
I had to add port forwarding in the default Vagrantfile to gain access to the UI:

`node.vm.network "forwarded_port", guest: 8080, host: 8080, auto_correct: true`

**Comment by deniseschannon** [comment]
@imikushin Please make sure this is addressed when we update the Vagrantfile. #1361

**Comment by imikushin** [comment]
should be fixed by #1615

**Comment by deniseschannon** [comment]
#1615 was merged.
