### ISSUE TITLE
[rancher-compose] 0.8.2 reporting out of sync for unchanged services

### ISSUE THREAD

**Issue by mishak87** [rancher/rancher#4992]
**Rancher Version:** 1.0.2

**Docker Version:** 1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):** Ubuntu 16.04, bare metal

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single node rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:**

``` yaml
loadbalancer:
  image: rancher/load-balancer-service
  ports:
    - '1000:1000'
  links:
    - httpd:httpd
  labels:
    'io.rancher.loadbalancer.target.httpd': ':1000=80'

httpd:
  image: httpd:2.4

pinger:
  image: alpine
  command: sh -c 'apk --update-cache add curl; while true; do curl -# http://loadbalancer:1000; usleep 100000; done'
  links:
    - loadbalancer:loadbalancer
```

It too gives same result when you switch the versions.

``` sh
> # download rancher-compose 0.7.4
> # create stack
> rancher-compose up -d
...
> # download rancher-compose 0.8.2
> # update stack (no changes)
>  rancher-compose up -d
```

**Results:** 
Creating stack

```
INFO[0000] Creating stack loadbalancer                  
INFO[0000] Creating service httpd                       
INFO[0000] Creating service loadbalancer                
INFO[0000] Creating service pinger                      
INFO[0000] Project [loadbalancer]: Starting project     
INFO[0000] [0/3] [httpd]: Starting                      
INFO[0002] [1/3] [httpd]: Started                       
INFO[0002] [1/3] [loadbalancer]: Starting               
INFO[0005] [2/3] [loadbalancer]: Started                
INFO[0005] [2/3] [pinger]: Starting                     
INFO[0007] [3/3] [pinger]: Started                      
INFO[0007] Project [loadbalancer]: Project started
```

Updating stack

```
INFO[0000] Project [loadbalancer]: Starting project     
INFO[0000] [0/3] [httpd]: Starting                      
WARN[0000] Service httpd is out of sync with local configuration file 
INFO[0000] [1/3] [httpd]: Started                       
INFO[0000] [1/3] [loadbalancer]: Starting               
WARN[0000] Service loadbalancer is out of sync with local configuration file 
INFO[0000] [2/3] [loadbalancer]: Started                
INFO[0000] [2/3] [pinger]: Starting                     
WARN[0000] Service pinger is out of sync with local configuration file 
INFO[0000] [3/3] [pinger]: Started 
```

**Expected:**
No out of sync warning (nothing has changed except rancher-compose).

**Comment by deniseschannon** [comment]
@mishak87 Yes, this is actually a known issue when changing versions of rancher-compose, but I don't believe there is an open issue.

**Comment by mishak87** [comment]
Possible solution: version hash and its function.
Useful workaround:
Implement rancher-compose config [docker-compose|rancher-compose] command like [docker-compose has](https://docs.docker.com/compose/reference/config/). That way deploy script could download current config via API and compare it to the result of rancher-compose config to detect actual changes to deployed services.
I [tried to write pull](https://github.com/mishak87/rancher-compose/commit/feature-config) for rancher-compose config but its code is bit cryptic for me.

**Comment by joshwget** [comment]
@mishak87 There's actually a PR (docker/libcompose#273) to add the `config` command to libcompose. It'll be added to Rancher Compose pretty shortly after it's merged.

**Comment by will-chan** [comment]
@joshwget has this been completed?

**Comment by joshwget** [comment]
@will-chan No, but the logic behind this is changing soon and it'll likely get fixed indirectly.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
