### ISSUE TITLE
Container names revert to UUID after service upgrade

### ISSUE THREAD

**Issue by andyshinn** [rancher/rancher#4993]
**Rancher Version:** 1.0.1

**Docker Version:** 1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):** VMware virtual machines on our own bare-metal

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** Single node, internal DB with external volume mount

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:** Deploy a stack then upgrade a service

**Results:** The container name for that service reverts to a UUID

**Expected:** The container name should stay the same (or increment in some way)

The forum thread for this is at https://forums.rancher.com/t/container-names-changed-back-to-uuid/2884/5. Basically, I'm trying to do log searches based on container names like r-stack_service_*. But after an upgrade to the service it reverts to a UUID name which breaks my log searching.

**Comment by fixe** [comment]
I confirm this bug in Rancher V1.0-dev5. This effectively means that `io.rancher.container.hostname_override: container_name` is not very useful since it will be lost during an upgrade.

**Comment by JaviSabalete** [comment]
With 1.0.1 same problem when I remove container and rancher recreate it (scale 1)

**Comment by alone23** [comment]
Same problem with 1.1.1

**Comment by JaviSabalete** [comment]
Same error with 1.1.1 and 1.1.2

**Comment by blackside** [comment]
We are having the same issue on 1.1.3 and this is a major issue for us...

**Comment by vincent99** [comment]
In 1.2 they will consistently be `r-{container name}-{first segment of uuid}`.

**Comment by ruimarinho** [comment]
Does that mean secrets-bridge will behave correctly in v1.2? Right now it takes 1 out of 5 tries to get it working because the name keeps changing to the uuid (/cc @cloudnautique).

**Comment by soumyalj** [comment]
Tested with v1.2.0-pre4-rc7. The container names remained in the format r-{container name}-{first segment of uuid} before and after upgrade
Before upgrade:
```
4f5ecb717cc6        busybox                         "/.r/r sleep 1000"       25 minutes ago      Up 9 minutes                                    r-logtestnew-test-1-22658493
```
After upgrade:
```
77cde00dcefb        busybox                         "/.r/r sleep 1000"       17 seconds ago      Up 16 seconds                                   r-logtestnew-test-1-3802d326
```
