### ISSUE TITLE
Add in user login attempts into audit logs 

### ISSUE THREAD

**Issue by y8** [rancher/rancher#4996]
Hi.

I just found out that there no information about user sign-in to rancher server in the audit logs. This is really important to keep track of successful and failed sign-in attempts.

**Rancher Version**: 1.0.0

Cheers.

**Comment by will-chan** [comment]
@vincent99 isn't this an API call as well?

**Comment by vincent99** [comment]
It is, but it's not currently logged because it's not a real resource being created/modified and there's no account to associate it with on failure.

**Comment by vthyng** [comment]
+1 We rolled out a rancher instance, announced it, and now want to see who has at least tried logging in so we can follow up and encourage adoption.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

**Comment by y8** [comment]
Closing tickets just because some digits had changed is not the same as closing tickets when issue is resolved or become stale.

If you did some research on this topic and found that failed logging attempts are being logged in some way or there a workaround for this issues, then please tell us. If you put security features outside your scope, fine, but stand up and tell us.

The way you are managing tickets is frustrating and demotivating.
