### ISSUE TITLE
Ingress update for https.port and http.port is not functional

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#4997]
**Rancher Version:** Master

**OS and where are the hosts located? (cloud, bare metal, etc):** Ubuntu, Cloud

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**: Kubernetes

**Steps to Reproduce:**
1. Create a Kubernetes set up
2. Create service, rc, 
3. Create an ingress with https.port specification. Check if it is functional.
4. Update the ingress by providing a different https.port

**Results:** 
The haproxy.cfg still shows the old https.port. The new https.port is not accessible as it is not updated. 

The http.port also cannot be updated in the ingress.

**Comment by alena1108** [comment]
@soumyalj please test against alena1108/ingress-controller:v0.1.5 image

**Comment by soumyalj** [comment]
Verified on Master with image alena1108/ingress-controller:v0.1.5. Ingress update for https.port and http.port are functional.
