### ISSUE TITLE
Running rancher container on new host, unable to get into rancher.

### ISSUE THREAD

**Issue by n1rvana** [rancher/rancher#4998]
**Rancher Version:**
Can't tell, since I can't bring rancher up, but this occurred with both rancher/server:latest and rancher/server:stable as of todays date.

**Docker Version:**
Docker version 1.11.2, build b9f10c9

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 14.04 on Azure

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Trying and initial setup of Rancher on a single node.

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
None yet.

**Steps to Reproduce:**
0. Provision new machine, install docker
1. sudo docker run -d --restart=always -p 8080:8080 rancher/server:stable
2. go to IPADDRESS:8080

**Results:** 
- brief flash of the animated rancher loading image
- end up on blank screen with url: IPADDRESS:8080/env/1a5/waiting

**Expected:**
See rancher.

**Comment by deniseschannon** [comment]
Is there anything in the rancher/server logs? 

Currently, we technically only support Docker 1.10.3, but I don't believe that is the source of your issue.

**Comment by n1rvana** [comment]
Weird.  Deleted all the images and containers, then this morning re-ran step #1 and it worked.

**Comment by thelastinuit** [comment]
Just in case: 
In my case was that I pulled the latest version of rancher. I changed it for stable and everything when smoothly.
