### ISSUE TITLE
memswap_limit is not being exported into the docker-compose.yml

### ISSUE THREAD

**Issue by zhang8473** [rancher/rancher#5001]
**Rancher Version:**
v1.0.0

**Docker Version:**

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu, aws-us-west

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
through Rancher server GUI or rancher-compose

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
   1. in any dockercompose.yml, specify
```
mem_limit: 256000000
memswap_limit: 1000000000
cpu_quota: 20000
```
   2. copy and paste the dockercompose.yml to "Add stack"-> from yml file. After stack is created, select "view config".

**Results:** 
only `mem_limit: 256000000` left. All of the other setups are missing.

**Expected:**
```
mem_limit: 256000000
memswap_limit: 1000000000
cpu_quota: 20000
```
in config

**Comment by prachidamle** [comment]
Added PR to fix the 'memswap_limit'
cpu_quota is not supported by Rancher yet

**Comment by soumyalj** [comment]
Tested with master, mem_limit: 256000000 and memswap_limit: 1000000000 show up in view config.
cpu_quota doesn't show up, which is not supported => https://github.com/rancher/rancher/issues/4708
