### ISSUE TITLE
Carina and Rancher Agent

### ISSUE THREAD

**Issue by andrevtg** [rancher/rancher#5002]
According to #2498 (closed) "--privileged" on agent (and whatever other containers the agent runs) is required to mount the docker socker (/var/run/docker.sock).

Carina currently can mount it without "--privileged" (I use it a lot). Can this requirement be turned off?

**Rancher Version:** agent 1.0.1

**Docker Version:** 1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):** Carina

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
remote agent first connection

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Swarm (I think)

**Steps to Reproduce:**
Trying to run agent without --privileged

**Results:** 
INFO: http://xxxxxxxxx:8080/v1 is accessible
INFO: Inspecting host capabilities
time="2016-06-03T04:11:42Z" level=fatal msg="Error response from daemon: authorization denied by plugin carina-docker-auth: Policy does not allow privileged containers"

INFO: System:
INFO: Host writable:
INFO: Token:
INFO: Running registration
Traceback (most recent call last):
  File "./register.py", line 21, in <module>
    key = sys.argv[1]
IndexError: list index out of range

**Expected:**

**Comment by scriptjs** [comment]
@andrevtg Can you tell me if you are running rancher successfully on Carina. It did not seem to support it last I checked. Is this a single node or are you backing it with HA with sql.

**Comment by andrevtg** [comment]
Nope, I gave up last time I tried. Carina does provide the socket mount, but AFAIK rancher requires "privileged" for other reasons.

Can't remember right now what was the error exactly, but I was in a hurry and had to use another VM-based service (unfortunately).

This is supposed to change, for it makes no sense to have such a no-go for CaaS services.

**Comment by scriptjs** [comment]
Yeah that is this issue. https://community.getcarina.com/t/whats-the-path-to-docker-sock-i-need-it-for-rancher-agent/45/7

**Comment by will-chan** [comment]
We actually require the privileged flag because we want to support RHEL and that requires the flag enabled before allowing socket access.  We currently do not have a separate rancher/agent both RHEL and any other OSes.  Keeping this feature open to support multiple OS builds or to fix the requirement of having the privilege flag if possible for RHEL.

**Comment by youngnicks** [comment]
Could an option be made available to not use the privileged flag when starting up the agent? Ideally this flag would be false by default, but for current backwards compatibility, it could be true.

**Comment by superseb** [comment]
Carina is shut down per April 18th, closing this out.
