### ISSUE TITLE
Haproxy (load balancer) has both log endpoints set by default

### ISSUE THREAD

**Issue by miv** [rancher/rancher#5004]
**Rancher Version:** v1.1.0-dev3

**Steps to Reproduce:**

Try adding another `log` to haproxy global section

**Results:** 

Nothing is written to syslog endpoint

**Expected:**

Logs got written to syslog endpoint

**Explanation**

Currently haproxy config already has two `log` records set:

```
global
        log 127.0.0.1 local0
        log 127.0.0.1 local1 notice
```

As per [`3.1.` of Haproxy Configuration mangual](http://www.haproxy.org/download/1.5/doc/configuration.txt):

```
log <address> [len <length>] <facility> [max level [min level]]
  Adds a global syslog server. Up to two global servers can be defined. They
  will receive logs for startups and exits, as well as all logs from proxies
  configured with "log global".
```

The main part is `Up to two global servers can be defined`.

Because currently we can't specify per proxy log, current defaults exhaust  all log endpoints that haproxy can send to.

There is also no rsyslog on haproxy instance and no way to configure one, to send logs to external syslog.

**Proposed fix**

I have two possible solutions:

1. Add configurable rsyslog facility to haproxy instance
2. Make logs section of haproxy config re-definable

**Comment by alena1108** [comment]
@miv we have an issue for enabling rsyslog: https://github.com/rancher/rancher/issues/2268

Closing this bug in favor of existing one
