### ISSUE TITLE
rancher cluster automation.

### ISSUE THREAD

**Issue by lesaux** [rancher/rancher#5006]
It seems to me that the creation of a rancher cluster is quite difficult to automate.
Say I wanted to deploy my cluster with cloudformation or terraform, how can I do that?

I bootstrap the database as described in the docs, but It is the next step that seems difficult to automate: I don't want to have to login to the UI to enable HA, setup my certs and download the rancher-ha script.

Is there anyway to setup HA and generate the rancher-ha.sh scripts through the API, or is there another way of doing this?

**Comment by deniseschannon** [comment]
Currently, there is no easier way to automate setting up HA. Otherwise, we would have already done that. ;)

We are always looking to improve the experience and will be trying to do so in an upcoming release.

Let me know if you have further specific questions.

**Comment by lesaux** [comment]
I've worked my way around this by using a mysql dump taken after a bootstrap. I'm making my terraform template available here: https://github.com/lesaux/terraform-aws-rancher-ha if its useful to anyone.

**Comment by aemneina** [comment]
@lesaux this is an awesome endeavor. It'll definitely be useful to a lot of folks.

**Comment by fred2697** [comment]
@deniseschannon can you help me with that issue: https://github.com/rancher/rancher/issues/21309 

I want to automate the cluster creation by exporting the yaml from one of my cluster.

Thanks
