### ISSUE TITLE
I Think the UI should be same between ipad and pc

### ISSUE THREAD

**Issue by xrain0610** [rancher/rancher#5007]
I use ipad pro for moblie manager, but , it's terrible , the ui should change to pc's version,
can you add the ipad support ?

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.1.0-dev3` Cattle: `v0.161.5` UI: `v1.1.3` |
|Access|`github` `admin`|
|Orchestration|`Cattle`|
|Route|`environments.index`|

**Comment by tfiduccia** [comment]
Version - master 7/15 
Verified fixed
