### ISSUE TITLE
In v1.1.0-dev3, system stacks that are upgraded move to user stacks

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#5009]
**Rancher Version:**
v1.1.0-dev3

**Docker Version:**
1.10.3

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
1. Deploy older Route53 catalog entry. Find stack in system page.
2. Upgrade to newer Route53 catalog entry. 

**Results:** 
Stack is now under "User" page

**Expected:**
Stack to remain under "System" page

Note: With the introduction of #4648, this might be automatically fixed.

**Comment by vincent99** [comment]
This should have been addressed by the category being sent in https://github.com/rancher/rancher-catalog-service/pull/49/files

**Comment by ibuildthecloud** [comment]
Yep that wasn't included.

**Comment by tfiduccia** [comment]
Version - master 6/9
Verified fixed
