### ISSUE TITLE
Launching Management Server Fails 

### ISSUE THREAD

**Issue by GeoffreyEmery** [rancher/rancher#5011]
**Rancher Version:**
latest

**Docker Version:**
Docker version 1.11.1, build 5604cbe

**OS and where are the hosts located? (cloud, bare metal, etc):**
main computer

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
run 

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
local

**Steps to Reproduce:**
ran $ docker run -d --restart=always -p 8080:8080 rancher/server

**Results:** 
160605  1:13:19 [Warning] Using unique option prefix myisam-recover instead of myisam-recover-options is deprecated and will be removed in a future release. Please use the full name instead.
160605  1:13:19 [Note] Plugin 'FEDERATED' is disabled.
160605  1:13:19 InnoDB: The InnoDB memory heap is disabled
160605  1:13:19 InnoDB: Mutexes and rw_locks use GCC atomic builtins
160605  1:13:19 InnoDB: Compressed tables use zlib 1.2.8
160605  1:13:19 InnoDB: Using Linux native AIO
160605  1:13:19 InnoDB: Initializing buffer pool, size = 128.0M
160605  1:13:19 InnoDB: Completed initialization of buffer pool
160605  1:13:19 InnoDB: highest supported file format is Barracuda.
160605  1:13:19  InnoDB: Waiting for the background threads to start
160605  1:13:20 InnoDB: 5.5.47 started; log sequence number 1595675
160605  1:13:20 [Note] Server hostname (bind-address): '0.0.0.0'; port: 3306
160605  1:13:20 [Note]   - '0.0.0.0' resolves to '0.0.0.0';
160605  1:13:20 [Note] Server socket created on IP: '0.0.0.0'.
160605  1:13:20 [ERROR] /usr/sbin/mysqld: Error writing file '/var/run/mysqld/mysqld.pid' (Errcode: 28)
160605  1:13:20 [ERROR] Can't start server: can't create PID file: No space left on device
160605  1:13:20 [Warning] Using unique option prefix myisam-recover instead of myisam-recover-options is deprecated and will be removed in a future release. Please use the full name instead.
160605  1:13:20 [Note] Plugin 'FEDERATED' is disabled.
160605  1:13:20 InnoDB: The InnoDB memory heap is disabled
160605  1:13:20 InnoDB: Mutexes and rw_locks use GCC atomic builtins
160605  1:13:20 InnoDB: Compressed tables use zlib 1.2.8
160605  1:13:20 InnoDB: Using Linux native AIO
160605  1:13:20 InnoDB: Initializing buffer pool, size = 128.0M
160605  1:13:20 InnoDB: Completed initialization of buffer pool
160605  1:13:20 InnoDB: highest supported file format is Barracuda.
160605  1:13:20  InnoDB: Waiting for the background threads to start
160605  1:13:21 InnoDB: 5.5.47 started; log sequence number 1595675
160605  1:13:21 [Note] Server hostname (bind-address): '0.0.0.0'; port: 3306
160605  1:13:21 [Note]   - '0.0.0.0' resolves to '0.0.0.0';
160605  1:13:21 [Note] Server socket created on IP: '0.0.0.0'.
160605  1:13:21 [ERROR] /usr/sbin/mysqld: Error writing file '/var/run/mysqld/mysqld.pid' (Errcode: 28)
160605  1:13:21 [ERROR] Can't start server: can't create PID file: No space left on device
160605  1:13:21 [Warning] Using unique option prefix myisam-recover instead of myisam-recover-options is deprecated and will be removed in a future release. Please use the full name instead.
160605  1:13:21 [Note] Plugin 'FEDERATED' is disabled.
160605  1:13:21 InnoDB: The InnoDB memory heap is disabled
160605  1:13:21 InnoDB: Mutexes and rw_locks use GCC atomic builtins
160605  1:13:21 InnoDB: Compressed tables use zlib 1.2.8
160605  1:13:21 InnoDB: Using Linux native AIO
160605  1:13:21 InnoDB: Initializing buffer pool, size = 128.0M
160605  1:13:21 InnoDB: Completed initialization of buffer pool
160605  1:13:21 InnoDB: highest supported file format is Barracuda.
160605  1:13:21  InnoDB: Waiting for the background threads to start
160605  1:13:22 InnoDB: 5.5.47 started; log sequence number 1595675
160605  1:13:22 [Note] Server hostname (bind-address): '0.0.0.0'; port: 3306
160605  1:13:22 [Note]   - '0.0.0.0' resolves to '0.0.0.0';
160605  1:13:22 [Note] Server socket created on IP: '0.0.0.0'.
160605  1:13:22 [ERROR] /usr/sbin/mysqld: Error writing file '/var/run/mysqld/mysqld.pid' (Errcode: 28)
160605  1:13:22 [ERROR] Can't start server: can't create PID file: No space left on device
160605  1:13:23 [Warning] Using unique option prefix myisam-recover instead of myisam-recover-options is deprecated and will be removed in a future release. Please use the full name instead.
160605  1:13:23 [Note] Plugin 'FEDERATED' is disabled.
160605  1:13:23 InnoDB: The InnoDB memory heap is disabled
160605  1:13:23 InnoDB: Mutexes and rw_locks use GCC atomic builtins
160605  1:13:23 InnoDB: Compressed tables use zlib 1.2.8
160605  1:13:23 InnoDB: Using Linux native AIO
160605  1:13:23 InnoDB: Initializing buffer pool, size = 128.0M
160605  1:13:23 InnoDB: Completed initialization of buffer pool
160605  1:13:23 InnoDB: highest supported file format is Barracuda.
160605  1:13:23  InnoDB: Waiting for the background threads to start

**Expected:**
site is available on port 8080.

**Comment by deniseschannon** [comment]
Are these logs from `docker logs <rancher_server_container>`? 

Any chance this is Docker on Windows?

**Comment by GeoffreyEmery** [comment]
yes docker on windows

**Comment by GeoffreyEmery** [comment]
PS C:\Program Files\Docker Toolbox> docker run -d --restart=always -p 8080:8080 rancher/server
>>
Unable to find image 'rancher/server:latest' locally
latest: Pulling from rancher/server

5a132a7e7af1: Pull complete
fd2731e4c50c: Pull complete
28a2f68d1120: Pull complete
a3ed95caeb02: Pull complete
3286c13024db: Pull complete
4a932879a44c: Pull complete
b2027edf95db: Pull complete
0a48e30699f5: Pull complete
e31b3b25effe: Pull complete
1b1c25ff5d73: Pull complete
93266f3e469e: Pull complete
8b5f7d9c9ac6: Pull complete
a495c77848b9: Pull complete
3a65541feb39: Pull complete
Digest: sha256:ad84a428fce9873c4277058bb563b6ead4741990e58ca82068ececdfecc517bd
Status: Downloaded newer image for rancher/server:latest
c8620d87cc113d3f98eef11bfe4586108c91f30d35f1c02329a0cf8b37abad2b
PS C:\Program Files\Docker Toolbox> docker run -d --restart=always -p 8080:8080 rancher/server
>>
7c986c916743dd29be9e5083040580788309f73f6b89e0789d65f4e33106805a
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: driver failed programming external connectivity on endpoint serene_liskov (85d39195d8369527cdad03ddb2e717e00690c4cae20250d6dd33332f451cd9c4): Bind for 0.0.0.0:8080 failed: port is already allocated.
PS C:\Program Files\Docker Toolbox>

**Comment by GeoffreyEmery** [comment]
ok ran it again and it booted
