### ISSUE TITLE
WebSocket connection in constants.js

### ISSUE THREAD

**Issue by steevegldev** [rancher/rancher#5013]
After logged on the web portal, in the web debug console i got error for that file constants.js:12:
`WebSocket connection to 'ws://myhost.com/v1/subscribe?eventNames=resource.change&eventNames=service.kubernetes.change&include=hosts&include=services&include=instances&include=instance&include=instanceLinks&include=ipAddresses&projectId=1a5' failed: Error during WebSocket handshake: Unexpected response code: 200`

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.0.2` Cattle: `v0.159.8` UI: `v1.0.5` |
|Access|`github` `admin`|
|Route|`environments.index`|

**Comment by vincent99** [comment]
Are you using a load balancer or SSL termination in front of Rancher?  It looks like it doesn't support websockets, so it's returning 200 instead of 101 and doing an upgrade..

**Comment by westlywright** [comment]
@steevegldev are you using a proxy that does not support websockets? I'm trying to reproduce the problem and can not.

**Comment by steevegldev** [comment]
Nothing special, should I open special port?

I could retry from scratch later this week.

**Comment by vincent99** [comment]
No, a WebSocket starts as a normal HTTP connection with a header that requests upgrading, and the server then responds with a 101.  Getting back a 200 suggests the request is going through something that doesn't know about WebSockets.

**Comment by deniseschannon** [comment]
@steevegldev Please let me know if you have further questions/issues.
