### ISSUE TITLE
How to run a gitlab-ci runner in rancher?

### ISSUE THREAD

**Issue by MaxNoe** [rancher/rancher#5014]
**Rancher Version:**
1.1.0.dev3
**Docker Version:**
1.11.1
**OS and where are the hosts located? (cloud, bare metal, etc):**
One bare-metal Ubuntu 16.04 
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
see above
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

I have a standard gitlab-ce container and a gitlab-ci-runner container running in rancher.
A load balancer routes requests to `http://gitlab` to the gitlab container. 

I want to setup gitlab-ci runners but when I register the runner and want to build something, the docker container launched by the runner cannot resolve the `gitlab` host.

How can I make the containers launched by the gitlab-ci-runner see my `gitlab` container in rancher?

### configuration:

```{yaml}
helloworld:
  labels:
    io.rancher.container.pull_image: always
  tty: true
  hostname: flask
  image: mnoethe/flask-helloworld
  stdin_open: true
LoadBalancerDockerCloud:
  ports:
  - 80:80
  labels:
    io.rancher.loadbalancer.target.helloworld: flask-app:80=5000
    io.rancher.loadbalancer.target.gitlab: gitlab:80=80
  tty: true
  image: rancher/load-balancer-service
  links:
  - gitlab:gitlab
  - helloworld:helloworld
  stdin_open: true
gitlab:
  domainname: gitlab
  labels:
    io.rancher.container.pull_image: always
  tty: true
  hostname: gitlab
  image: gitlab/gitlab-ce:latest
  volumes:
  - /home/max/gitlab-test/config:/etc/gitlab
  - /home/max/gitlab-test/data:/var/opt/gitlab
  - /home/max/gitlab-test/logs:/var/log/gitlab
  stdin_open: true
docker-ci-runner:
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: gitlab/gitlab-runner:latest
  links:
  - gitlab:gitlab
  volumes:
  - /home/max/gitlab-test/gitlab-runner:/etc/gitlab-runner
  - /var/run/docker.sock:/var/run/docker.sock
  stdin_open: true
```

And the rancher-compose:

```{yaml}

helloworld:
  scale: 1
LoadBalancerDockerCloud:
  scale: 1
  load_balancer_config:
    haproxy_config: {}
  health_check:
    port: 42
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000
gitlab:
  scale: 1
docker-ci-runner:
  scale: 1
```

**Comment by bradjones1** [comment]
You need to configure the runner to register itself. So it appears it's less about the name resolution and more that your container needs to register? I've built a runner that has a few extra bells and whistles, but you can see how it takes some environment variables to register when it starts. That would help with scaling up, if you ever want to do that.

https://github.com/BradJonesLLC/gitlab-docker-ci

**Comment by MaxNoe** [comment]
The runner works fine, the containers spawned by the runner to do the actual ci jobs cannot resolv the gitlab domain.

**Comment by bradjones1** [comment]
@MaxNoe Ah, if you are trying to use the internal GitLab DNS services, you will need to spawn them with the appropriate label, so they are configured for the Rancher network. See http://docs.rancher.com/rancher/latest/en/concepts/#networking

**Comment by MaxNoe** [comment]
Another question: Is it possible for rancher to manage the gitlab-ci jobs (distribute them equally on the cluster?) Right now, all jobs are starting on the host where the gitlab-ci service is running.

**Comment by bradjones1** [comment]
The short answer is, not really. I'm sure you could script something, and the provider => consumer model that's part of #2179 could probably help, but not out of the box.

**Comment by deniseschannon** [comment]
@MaxNoe Please re-open if you still have further questions. It looks like @bradjones1 has done a great job helping you out. :)

**Comment by alex88** [comment]
@MaxNoe have you solved this? I'm trying to get the runner working with the regular hosted gitlab.com edition, but when I register it nothing happens

**Comment by alex88** [comment]
Also how do you configure your runners?

**Comment by MaxNoe** [comment]
I did nothing special to solve, just registered the runner and it worked since or server is now reachable from the web. The problem arised only in my test environment.  I'm using the docker backend for the runners.

**Comment by Unode** [comment]
Is this something that could qualify to be part of the Rancher catalog next to the already existing Gitlab setup?

**Comment by alex88** [comment]
@MaxNoe well in my case after I register it nothing happens, gitlab shows it doesn't connect to gitlab, but after you give it access to the docker socket, you won't see docker instances in rancher right? Since they're managed on docker side

**Comment by MaxNoe** [comment]
@alex88 Rancher shows all running docker images, also those not created or managed by it. So you should see the containers spawned by the gitlab-ci-runner.

What is missing is the possibility to load balance those containers to all machines in the rancher cluster, not only to the machine where the gitlab-ci-runner service is running.

**Comment by alex88** [comment]
@MaxNoe what I think gitlab should implements is the ability to just run a container with a daemon that runs the builds in it,  instead of relying on the docker socket on something that you register/unregister

**Comment by tobiasbaehr** [comment]
The solution is to set the host inside of extra_hosts. e.g. extra_hosts = ['gitlab:1.2.3.4']
https://docs.gitlab.com/runner/configuration/advanced-configuration.html#the-runners-docker-section

https://docs.gitlab.com/runner/configuration/advanced-configuration.html#how-clone_url-works should also works.
