### ISSUE TITLE
Override hostname uses underscores

### ISSUE THREAD

**Issue by doo-gl** [rancher/rancher#5017]
**Rancher Version:**
v1.0.1
**Docker Version:**
1.10
**OS and where are the hosts located? (cloud, bare metal, etc):**
rackspace
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
cattle
**Steps to Reproduce:**
1. Start a container with label: io.rancher.container.hostname_override=container_name
2. log in to the container
3. run echo $HOSTNAME
4. observe underscores

So I had previously raised an issue that was asking why underscores were not allowed in container names and the response was because that mean they could be used in the internal DNS. Which seemed reasonable.

What I want to do is set the hostname of my container to be a host that uniquely points to a container in my environment. I tried using io.rancher.container.hostname_override=container_name but find that the container name has a series of underscores in it what means that I cannot call to it from my server using eureka.

Is there a way that i can change this host to use periods instead of underscores?

**Comment by vincent99** [comment]
All hostnames created by recent versions use hyphen instead of underscore.
