### ISSUE TITLE
Duplicate node in hosts list after node reboot

### ISSUE THREAD

**Issue by steevegldev** [rancher/rancher#5018]
Using Other (vSphere driver). After rebooting a node, I got this node listed twice. This node sounds to be a working instance. I got working containers on both. All detail are same on both: Name, IP, etc. Be able to reproduce in Cattle and SWARM.Not tested in Kubernetes (I can't make Kubernetes working btw)

The issue right now is if I delete one, both got deleted.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.0.2` Cattle: `v0.159.8` UI: `v1.0.5` |
|Access|`github` `admin`|
|Route|`hosts.index`|

**Comment by deniseschannon** [comment]
What kind of host is it or how are you running it? 

You might be hitting this issue: https://github.com/rancher/rancher/issues/4698

**Comment by steevegldev** [comment]
Yes it is. I didn't find it in my search. Thanks
