### ISSUE TITLE
Load Balancer API

### ISSUE THREAD

**Issue by leobautista** [rancher/rancher#5020]
When I try to provision a load balancer via the API, the advance option do not show in the console. The request host and target port do not appear.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.0.1` Cattle: `v0.159.7` UI: `v1.0.5` |
|Access|`github` |
|Route|`environments.index`|

**Comment by deniseschannon** [comment]
Can you share your API call? Please hide any sensitive information. I'd like to see how you are trying to send over the hostname routing rules information.

**Comment by leobautista** [comment]
+ * Create a load balancer in rancher with the provided settings
 + *
 + * Options looks like this:
 + * {
 + *   name: String,
 + *   ssl: true/false,
 + *   scheduling: {
 + *     serverLabel: String
 + *   },
 + *   certificateName: '',
 + *   publicPort: '80'
 + *   services: [
 + *      {
 + *        host: '<host>',
 + *        name: '<name>',
 + *        port: '<port>',
 + *      }
 + *   ],
 + *   stack: stackName
 + * }
 + * @param  {String} env     The rancher environment
 + * @param  {Object} options
 + * @param {} [varname] [description]
 + * @return {[type]}         [description]
 + */
 +function createLoadBalancer(env, options) {
 +  const port = options.publicPort ? options.publicPort : (options.ssl ? '443' : '80');
 +  const labels = getSchedulingConfig(options.scheduling);
 +  if (options.ssl) {
 +    // This will be defined as 443 if no publicPort is specified, but we might
 +    // want to do it on a different port for whatever reason
 +    labels['io.rancher.loadbalancer.ssl.ports'] = port;
 +  }

**Comment by leobautista** [comment]
const payload = {
    "assignServiceIpAddress":false,
    "scale":1,
    "startOnCreate":true,
    "type":"loadBalancerService",
    name: options.name,
    description: options.description || null,
    "environmentId":"1e8",
    "launchConfig":{
      "startOnCreate":true,
      "publishAllPorts":false,
      "privileged":false,
      "stdinOpen":true,
      "tty":true,
      "readOnly":false,
      "networkMode":"managed",
      "type":"container",
      "commandArgs":[

      ],
      "environment":{

      },
      "restartPolicy":{
         "name":"always"
      },
      "expose":[

      ],
      ports: [`${port}:8080`],
      labels: labels,
      logConfig: {
        driver: 'syslog',
      },
      "count":null,
      "createIndex":null,
      "created":null,
      "deploymentUnitUuid":null,
      "description":null,
      "externalId":null,
      "firstRunning":null,
      "healthState":null,
      "hostname":null,
      "kind":null,
      "name":null,
      "removed":null,
      "startCount":null,
      "systemContainer":null,
      "uuid":null,
      "volumeDriver":null,
      "workingDir":null,
      "user":null,
      "domainName":null,
      "memorySwap":null,
      "memory":null,
      "cpuSet":null,
      "cpuShares":null,
      "pidMode":null
    },
    "loadBalancerConfig":{
      "type":"loadBalancerConfig",
      "name":"ui-lb-config",
      "haproxyConfig":{
         "type":"haproxyConfig",
         "global":null,
         "defaults":null
      }
    },
    "created":null,
    "externalId":null,
    "fqdn":null,
    "healthState":null,
    "kind":null,
    "removed":null,
    "selectorLink":null,
    "uuid":null,
    "vip":null
  };

**Comment by leobautista** [comment]
we are sending the following to the servicelinks.

serviceLinks: [
  {
    ports:['foo.dispatch.me=8080'],
    serviceId: '1234',
  }
]

**Comment by aemneina** [comment]
Hey @leobautista , I tried using your payload json and was getting validation errors. I cleaned it up a bit and was able to successfully create the lb service. I think youre 99% there, just need to validate/sanitize the data before sending it over. What I ended up sending over:
```
{
	"assignServiceIpAddress": false,
	"scale": 1,
	"startOnCreate": true,
	"type": "loadBalancerService",
	"name": "testmelb",
	"description": "funkydesc",
	"environmentId": "1e3",
	"launchConfig": {
		"startOnCreate": true,
		"publishAllPorts": false,
		"privileged": false,
		"stdinOpen": true,
		"tty": true,
		"readOnly": false,
		"networkMode": "managed",
		"type": "container",
		"commandArgs": [

		],
		"environment": {

		},
		"restartPolicy": {
			"name": "always"
		},
		"expose": [],
		"ports": "80:999",
		"count": null,
		"createIndex": null,
		"created": null,
		"deploymentUnitUuid": null,
		"description": null,
		"externalId": null,
		"firstRunning": null,
		"healthState": null,
		"hostname": null,
		"kind": null,
		"name": null,
		"removed": null,
		"startCount": null,
		"systemContainer": null,
		"uuid": null,
		"volumeDriver": null,
		"workingDir": null,
		"user": null,
		"domainName": null,
		"memorySwap": null,
		"memory": null,
		"cpuSet": null,
		"cpuShares": null,
		"pidMode": null
	},
	"loadBalancerConfig": {
		"type": "loadBalancerConfig",
		"name": "ui-lb-config",
		"haproxyConfig": {
			"type": "haproxyConfig",
			"global": null,
			"defaults": null
		}
	},
	"created": null,
	"externalId": null,
	"fqdn": null,
	"healthState": null,
	"kind": null,
	"removed": null,
	"selectorLink": null,
	"uuid": null,
	"vip": null
}
```

**Comment by vincent99** [comment]
FYI 90%+ of that is nulls or copies of the default value and could be omitted...

**Comment by tfiduccia** [comment]
@leobautista - looks like your question was answered.  If you are still having problem, please reopen.
