### ISSUE TITLE
Stacks are being stuck into Activating state using Rancher HA

### ISSUE THREAD

**Issue by amaranto** [rancher/rancher#5022]
v1.1.0-dev3

Docker version 1.11.2, build b9f10c9

Ubuntu trusty

Rancher HA , external DB RDS

Cattle

I've set up rancher HA using ELB, I have  3/3 nodes connected and the containers don't report issues.

![2](https://cloud.githubusercontent.com/assets/11441945/15835652/55d0a5e6-2c07-11e6-9730-e0d95e0b152b.png)
![nimbus-image-1465239640207](https://cloud.githubusercontent.com/assets/11441945/15835654/58dfaca0-2c07-11e6-86f6-48290c5fcc50.png)

**Comment by amaranto** [comment]
Attaching hosts picture.

![4](https://cloud.githubusercontent.com/assets/11441945/15835757/dd86641c-2c07-11e6-9688-8d7e02dd8109.png)
![3](https://cloud.githubusercontent.com/assets/11441945/15835761/e106591c-2c07-11e6-8f34-aaa5de6b6340.png)

**Comment by amaranto** [comment]
I am able to add services manually to the stack , but i can't  import docker and rancher yml files.

**Comment by amaranto** [comment]
I've configured ssl terminated at ELB and point ssl(tcp) 443 to 81 and it is working fine.  Handling ssl with rancher the issue is still present.

**Comment by aemneina** [comment]
Hey @amaranto what type of certificates are you using on the rancher server, are those self signed? I believe there's a bug with the rancher-ha.sh script that gets generated, it basically omits the certs, can you confirm thats the case? See [here](https://github.com/rancher/rancher/issues/5311) for a workaround.

**Comment by deniseschannon** [comment]
@amaranto If you have further issues/questions, please re-open.
