### ISSUE TITLE
convoy-volume-ebs?

### ISSUE THREAD

**Issue by saphoooo** [rancher/rancher#5023]
**Rancher Version:**
ros version v0.4.5
**Docker Version:**
Docker version 1.10.3, build 20f81dd
**OS and where are the hosts located? (cloud, bare metal, etc):**
ros version v0.4.5, on AWS EC2
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
2 nodes rancher, external DB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
N/A
**Results:** 
N/A
**Expected:**
N/A
Not an issue, but a request for improvement: is there a plan to develop convoy-volume-ebs? I use convoy with ros, but it would be great to have a system stack for this. I've tried to set it up, but convoy only accept gluster, nfs or loghorn.

**Comment by wonderslug** [comment]
+1

**Comment by mathuin** [comment]
+1 as well -- if you'd prefer us to use the emoji additions on the initial issue instead of littering the issue with comments, just let us know!

**Comment by zaubererty** [comment]
+1

**Comment by henrypfhu** [comment]
+1

**Comment by vincent99** [comment]
See rancher-ebs catalog item for 1.2.x.
