### ISSUE TITLE
Automated test case test_k8s.test_k8s_env_podspec_hostPID returns incorrect result

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#5024]
**Rancher Version:**Master

**OS and where are the hosts located? (cloud, bare metal, etc):**Ubuntu, Cloud

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**: Kubernetes

test_k8s_env_podspec_hostPID is checking the result for command "ps" to be "init", whereas the result obtained is "systemd"

**Comment by galal-hussein** [comment]
The pull request https://github.com/rancher/validation-tests/pull/184 should fix this issue.

**Comment by will-chan** [comment]
@soumyalj can we re-test this and close issue if it's no longer there?

**Comment by galal-hussein** [comment]
Tested this test case with latest docker versions and worked as expected.
