### ISSUE TITLE
Don't support multiple namespace in image name

### ISSUE THREAD

**Issue by kala888** [rancher/rancher#5025]
**Rancher Version:** v1.0.1

**Docker Version:** 1.11.1

**OS and where are the hosts located? (cloud, bare metal, etc):** centos7

**Setup Details:** single node

**Environment Type:**  Jfrog(aritfactory) as registry

**Steps to Reproduce:**
1. Create image named  docker.artifactory.xxxxx.net/xxxcommerce/redis/3.2.0:latest
2. Push to artifactory
3. Create service in rancher

**Results:** Validation failed in API: imageUuid
https://forums.rancher.com/t/validation-failed-in-api-imageuuid/2970/1

**Expected:** Rancher can not  support image name format [registry-name]/[namespace1]/[namespace2]/[namespace3]/[imagename]:[version]

**Comment by soumyalj** [comment]
Tested with rancher v1.2.0-pre4-rc7. Able to create containers with private repository images below : 
1. 605812595399.dkr.ecr.us-east-1.amazonaws.com/soumyatestrepo:v1
2. 605812595399.dkr.ecr.us-east-1.amazonaws.com/soumya/namespace1/namespace2:latest
3. localhost:5000/ubuntu
4. localhost:5000/foo/bar/ubuntu
