### ISSUE TITLE
Service link for containers not working

### ISSUE THREAD

**Issue by adaikal** [rancher/rancher#5027]
**Rancher Version:**

**Docker Version:**

**OS and where are the hosts located? (cloud, bare metal, etc):**

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**

**Results:** 

**Expected:**

**Comment by adaikal** [comment]
Rancher Version: 1.0.2

Docker Version:

Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64

 
 OS and location: Ubuntu 14.04 and Openstack Kilo
 
 Setup Details: Rancher single node with external DB
 
 Environmnet type: Cattle
 
 Sets to reproduce:
 
 
 * Launch tutum/mysql and then launch tutum/apache-php with service link to tutum/mysql container
 
 * If you exec into tutum/apache-php container you will find mysql container's environment variables, everything fine in this case
 
 * Now launch tutum/mysql and then launch tutum/apache-php container
 
 * Now edit tutum/apache-php container and add service link to tutum/mysql container

 * If you exec into tutum/apache-php container you will not find mysql container environment variables, service link edit not working properly.
 
 Results:
 
 Environment variables not passed from source container to linked container if we use edit service link after container is launched

**Comment by vincent99** [comment]
Environment variables cannot be changed in a container once created.  The service discovery/DNS entries are updates when a link is changed.

**Comment by deniseschannon** [comment]
If you want the environment variables to change, then you'd need to upgrade the tutum/apache-php container to link to the mysql container. The container that is newly created would have the new environment variables.

Let me know if you have further questions.

**Comment by adaikal** [comment]
@vincent99 and @deniseschannon Thanks, understood.

**Comment by adaikal** [comment]
@deniseschannon how do I link a container with another container in rancher api. For example, assume mysql container is running. How do I link app container to mysql container during launch itself. what is the equivalent of --link in rancher API?

**Comment by deniseschannon** [comment]
You would use "addservicelink". 

http://docs.rancher.com/rancher/latest/en/api/api-resources/service/

**Comment by adaikal** [comment]
@deniseschannon But addservicelink was the issue. When I used addservicelink, the source container did not pass it's environment variables to recipient container.
I did like follow:

Launched db container
Launched app container
Used addservicelink for app container to link to db container. It got linked but no environment variables were passed from db to app container.

I'd like to know how to link to db container when we launch the app container in the first place itself, like

docker run -itdP --link db:appdb tutum/apache-php

How to achieve this?

Or my question should be, do rancher even use "--link", I see it to be a legancy feature. When we use --link, the source container passes it's environment variables to recipient container and also updates its /etc/hosts with dns entry.

But when I exec into rancher launched container, there wasn't a host entry in /etc/host.

**Comment by deniseschannon** [comment]
If you want the environment variables passed from the db to app container, you'd need to set the link upon container creation. After a container is created, environment variables cannot be added to a running container. This is a Docker constraint, where docker containers are immutable. 

To get what you want, you'd start your DB container and then when starting the app container, you'd need to add the link at that time.

**Comment by adaikal** [comment]
@deniseschannon I'm trying to link the app container to db container while app container is being launched but I'm getting error


{
"environmentId": "1e70",
"name": "app03",
"scale": 1,
"launchConfig": {
"capAdd": [ ],
"capDrop": [ ],
"count": null,
"cpuSet": null,
"cpuShares": null,
"dataVolumes": [ ],
"dataVolumesFrom": [ ],
"description": null,
"devices": [ ],
"dns": [ ],
"dnsSearch": [ ],
"domainName": null,
"hostname": null,
"imageUuid": "docker:tutum/apache-php",
"instanceLinks": "1s157",
"kind": "container",
"labels": { },
"logConfig": {
"config": { },
"driver": "",
},
"memory": null,
"memoryMb": null,
"memorySwap": null,
"networkMode": "managed",
"pidMode": null,
"ports": [ ],
"privileged": false,
"publishAllPorts": false,
"readOnly": false,
"requestedIpAddress": null,
"startOnCreate": true,
"stdinOpen": true,
"tty": true,
"user": null,
"userdata": null,
"version": "0",
"volumeDriver": null,
"workingDir": null,
"dataVolumesFromLaunchConfigs": [ ],
"networkLaunchConfig": null,
"vcpu": 1,
},
"secondaryLaunchConfigs": [ ],
"assignServiceIpAddress": false,
"startOnCreate": true,
}
HTTP Response:
HTTP/1.1 422
Date: Mon, 13 Jun 2016 06:28:24 GMT
X-Api-Client-Ip: 192.168.54.113
Server: Jetty(9.2.11.v20150529)
X-Api-Account-Id: 1a107
Content-Type: application/json; charset=utf-8
X-Api-Schemas: http://rancher/v1/projects/1a107/schemas
Content-Length: 177
Expires: Thu, 01 Jan 1970 00:00:00 GMT

{
"id": "905f9e39-1bb8-4719-b724-f961aaf09a62",
"type": "error",
"links": { },
"actions": { },
"status": 422,
"code": "InvalidFormat",
"message": null,
"detail": null,
"fieldName": "instanceLinks",
}

I have passsed db container id in json request "instanceLinks": "1s157". What am I doing incorrectly.

**Comment by pwFoo** [comment]
I tried to add a link to my global MySQL stack, but it doesn't work. Only chance was to edit the stack container to add the link, but NOT upgrade the stack to do it...? Related?

I use the latest Rancher Server running on RancherOS 0.4.5
