### ISSUE TITLE
rancher-ha, AWS private route53 zone and host registration url.

### ISSUE THREAD

**Issue by lesaux** [rancher/rancher#5028]
**Rancher Version:**

v1.1.0-dev4-rc1

**Docker Version:**

1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):**

 RancherOS (4.2.8-ckt4-rancher) in AWS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

rancher-ha with RDS

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

Cattle

**Steps to Reproduce:**

Regular ha setup with ELB CNAME record in private hosted zone. CNAME record is used for host registration.

**Results:** 

go-machine-service cannot resolve CNAME and fails to start. It seems to be using 169.254.169.250 as a dns server.

rancher-compose-executor service cannot start as well.

**Expected:**

both go-machine-service and rancher-compose-executor are able to start.

**Comment by deniseschannon** [comment]
Can you provide logs for these services?

**Comment by deniseschannon** [comment]
Can you also share your security groups for the ELB and for rancher server and hosts?

**Comment by lesaux** [comment]
I'm sorry I moved my dns records from a private to  a public zone in route53 to work around this issue. I don't have the logs handy anymore. All I know is that rancher would not resolve the rancher_registration_url if it was in a private hosted zone in route53.

**Comment by deniseschannon** [comment]
@lesaux If you manage to set this up again and have the same issues and can provide the requested info, please re-open.
