### ISSUE TITLE
Feature/AWS network tags when adding a host.

### ISSUE THREAD

**Issue by lesaux** [rancher/rancher#5029]
**Rancher Version:**

v1.1.0-dev4-rc1

**Docker Version:**

1.10.3

Just a few thoughts I had while deploying some hosts in AWS.

GUI should show some aws tags (VPC subnets) during network selection to make things easier.

GUI should allow to select multiple valid subnets (cross az deployment).

**Comment by vincent99** [comment]
I didn't know subnets had tags but that sounds like it makes sense to show.

The docker-machine interface is a single singlet, so multiple is not possible: https://github.com/docker/machine/blob/master/drivers/amazonec2/amazonec2.go#L86-87

**Comment by lesaux** [comment]
Ha right, I didn't realize docker-machine was being used in AWS as well.
But I don't think one docker-machine run can create multiple docker hosts, which means you must be running it several times.

**Comment by deniseschannon** [comment]
@lesaux We call docker-machine for all the hosts created through our UI and yes, if you select a scale of more than 1, then we call multiple docker-machine commands.

**Comment by tfiduccia** [comment]
@loganhz - I don't see this in the new 2.0 UI.  Can you reverify it's there.

**Comment by loganhz** [comment]
![image](https://user-images.githubusercontent.com/21168270/34971163-e3e3515e-fab3-11e7-8bc9-1c5a52563167.png)
the tag after `ci-validation-tests-subnet (subnet-e9fcc78d)` is a subnet tag

**Comment by tfiduccia** [comment]
Version - 2.0 master 1/16
Verified fixed
