### ISSUE TITLE
Clicking on the main item in the header closes dropdown

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#5031]
**Rancher Version:**
v1.1.0-dev4

**Steps to Reproduce:**
Hover over environment
Click on environment 

**Results:** 
Dropdown collapses

**Expected:**
Dropdown remains open

**Comment by vincent99** [comment]
Changed (for Environment, Namespace, and the User menu only, the others have a default destination so it should close).

**Comment by tfiduccia** [comment]
Version - master 6/15
Verified fixed
