### ISSUE TITLE
Creating a service with scheduling rule of affinity to itself is unsuccessful

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#5032]
**Rancher Version:**: v1.1.0-dev4-rc1

**OS and where are the hosts located? (cloud, bare metal, etc):** Ubuntu, Cloud

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**: Cattle

**Steps to Reproduce:**
1. Create a service "myaff" with scheduling rule: 
```
Host must have service with service name "myaff"
```
The following is the API settings:
"labels": {
"io.rancher.container.pull_image": "always",
"io.rancher.scheduler.affinity:container_label": "io.rancher.stack_service.name=myaff",
},
The scheduling fails and the containers do not start up successfully.
```
Activating (Waiting for [instance:Default_myaff_1]. Instance status: Scheduling failed: io.cattle.platform.allocator.constraint.ContainerLabelAffinityConstraint@6eb61a85)

```

**Comment by soumyalj** [comment]
Tested again with stackname/servicename. The Issue still persists.

**Comment by deniseschannon** [comment]
This use case is not supported.

We do not support affinity to yourself as there will never be a container already scheduled on a host to schedule with.
