### ISSUE TITLE
Can't bind multiple host IP:port pairs to same exposed container port

### ISSUE THREAD

**Issue by bradjones1** [rancher/rancher#5033]
**Rancher Version:**
v1.1.0-dev3

**Docker Version:**
1.11

**OS and where are the hosts located? (cloud, bare metal, etc):**
Bare Metal - Ubuntu 14.04.2 LTS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
2-node cluster plus Rancher node - external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Swarm

**Steps to Reproduce:**
Add a container (e.g., nginx) and attempt to bind two different IPs to the same "private container" port. E.g.:

```
1.2.3.4:80 => 80
1.2.3.5:80 => 80
```

**Results:**
Only the first IP for the given container exposed port is bound.

**Expected:**
Both IP:port combinations are bound to the same exposed container port.

This is tested in the UI; I have not attempted with the Rancher Compose CLI tool.

**Comment by bradjones1** [comment]
@deniseschannon Do you know if this is a known issue for 1.0?

**Comment by deniseschannon** [comment]
@bradjones1 I think you're the first one to attempt this use case. I haven't had a chance to test this as I don't have a host with 2 IPs to try and bind to.

Do you know if this use case is supported in Docker? Have you tried doing a `docker run` command on your host and getting a container to start up?

**Comment by bradjones1** [comment]
Yes, it's definitely supported by `docker run` and Docker Compose... I ran into this as I am working to transition to Rancher from an orchestration tool that used `docker-py` to do the parsing. It's definitely supported.

As far as testing goes, I think you could probably get the same result by just choosing two different ports on the host, mapped to the same container port? That or a virtual interface would probably work for testing as well.

**Comment by nosovk** [comment]
@bradjones1 did you managed to get multiple ip's support somehow?

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
