### ISSUE TITLE
After adding a new namespace, unable to go to any other page in the header

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#5034]
**Rancher Version:**
v1.1.0-dev4

**Steps to Reproduce:**
In a k8s environment, add a new namespace.
Click on "Manage Environments", "Kubernetes", "Infrastructure->Hosts". 

**Results:** 
Nothing happens, you stay on the Manage Namespaces page

**Expected:**
Should navigate to the page you click on.

**Comment by westlywright** [comment]
@deniseschannon can you retest this I was able to add a new name space and navigate with out issue.

**Comment by deniseschannon** [comment]
Verified unable to reproduce in v1.1.0-dev5.
