### ISSUE TITLE
CPUUtilization increase during a daily time window

### ISSUE THREAD

**Issue by lekum** [rancher/rancher#5036]
**Rancher Version:** 1.0.2

**Docker Version:** 1.11.1

**OS and where are the hosts located? (cloud, bare metal, etc):** RHEL 7.2 in AWS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** Single Node external DB (AWS Aurora)

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:** Review the CloudWatch Monitoring of CPUUtilization of either the Rancher Servers or the dockerhosts with the Rancher Agent

**Results:** There is CPU increase every day from the approximate period of 05:55-06:25 UTC, as shown in the chart:

![cloudwatch](https://cloud.githubusercontent.com/assets/2630720/15885158/71fed5f4-2d55-11e6-86a5-73943c538b21.png)

Trying a top or a sysdig, the most CPU consuming process of the machine is:

```
/var/log/rancher/.cadvisor -logstostderr=true -list_ip 127.0.0.1 -port 9344 -hou
sekeeping_interval 1s -docker_root /var/lib/docker
```

Is there any scheduled action in the system that could trigger this CPU increase?

It happens in different AWS Availability Zones and does not happen in machines without Rancher Server / Agent.

**Expected:**

**Comment by aemneina** [comment]
This is related to log rotate running within the rancher agent. Closing the issue.

**Comment by lekum** [comment]
Any ETA for fixing the logrotate issue within the rancher agent?

Thanks!

**Comment by aemneina** [comment]
@lekum this will ship in -pre1, due out early next week. I'll close this, if there are further issues, can you open a new ticket.
