### ISSUE TITLE
[question:loadbalancer] Multiple SSL certificates for Multiple Domains

### ISSUE THREAD

**Issue by create-renegr** [rancher/rancher#5037]
**Rancher Version:** v1.0.1
**Docker Version:** 1.10.3
**OS and where are the hosts located? :** Ubuntu 14.04 / bare metal
**Setup Details:** Single Node Rancher, external DB
**Environment Type:** Cattle

**Question:**

Let's suppose following setup:

![rancher-multiple-ssl-certificates-multiple-domains](https://cloud.githubusercontent.com/assets/273479/15887555/310782f4-2d63-11e6-9d95-8fc4de4f599b.png)

How would a setup for the Loadbalancer look like, if I would like to serve several different applications, accessible by different domains via HTTPS.

I've searched a lot in the internet, but I couldn't find a solution, that would fit the needs.

Thanks in advance,

René

**Comment by bradjones1** [comment]
I've shied from the built-in Load Balancer in this use case... it's basically just a UI around HAProxy, so you could bake your own. Though, you don't get the pretty UI and graphs. Also there's #2179 which aims to refactor the LB, anyway. You may want to provide input there but use your own HAProxy implementation in the meantime. I'm using https://github.com/BradJonesLLC/docker-haproxy-letsencrypt which rolls in Let's Encrypt and dnsmasq, too.

**Comment by create-renegr** [comment]
Thanks for your input!

Do you want to share how you do dynamic configuration of your domains & service discovery when your applications shift nodes upon restart/scaling?

**Comment by EugenMayer** [comment]
@create-renegr you can have it "build in" in rancher. Use a rancher lb like this rancher.com/virtual-host-routing-using-rancher-load-balancer/

and then add the letsencrypt catalog from the community marketplace. You will then be able to simply select the needed certificates in the lb setup - since the certificates are then part of "ranches certificate store" very neat!

I think seperating letsencrypt and the lb makes a lot of sense, having rancher, thats even very convinient.

**Comment by deniseschannon** [comment]
@create-renegr Please re-open if you have further questions, but the Rancher load balancer supports L7 load balancing.

http://docs.rancher.com/rancher/latest/en/cattle/adding-load-balancers/#advanced-routing-options

http://docs.rancher.com/rancher/latest/en/cattle/adding-load-balancers/#advanced-load-balancing-l7
