### ISSUE TITLE
rancher-agent cannot connect host registration url with http protocol

### ISSUE THREAD

**Issue by HackerWilson** [rancher/rancher#5039]
**Rancher Version:**
v1.1.0-dev4

**Docker Version:**
Docker version 1.11.2, build b9f10c9

**OS and where are the hosts located? (cloud, bare metal, etc):**
bare metal

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher
external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**
1. generate rancher-ha.sh scripts
2. replace

```
export CATTLE_HA_HOST_REGISTRATION_URL=https://192.168.0.40:8080
```

to

```
export CATTLE_HA_HOST_REGISTRATION_URL=http://192.168.0.40:8080
```

in rancher-ha.sh then delpoyed

**Results:** 
rancher-agent cannot  connect to the loadbalancer, 

```
time="2016-06-08T17:43:13Z" level="info" msg="Connecting to proxy." url="ws://192.168.0.40:8080/v1/connectbackend?token=eyJhbGciOiJSUzI1NiJ9.eyJleHAiOjE0NjU0MDgwOTMsInN1YiI6ImNhdHRsZSIsImlzcyI6Imh0dHA6XC9cL2NhdHRsZS5pbyIsInJlcG9ydGVkVXVpZCI6ImRjODBlNzYyLTMxNGEtNDkzZC1iZjVjLTBhYWRlOWEzYTE2MyIsImlhdCI6MTQ2NTQwNzc5Mywia2lkIjoiZGVmYXVsdCJ9.TA4ZpNfma4Gk2pDgSguxQQ9bxsNVvfKleQIS1M2e6Lt0ryk8luXkmNbRH2YefG66kBnabfuwoycAMV6KasEZubidP8N7xVQwUhAbD5oGLK2_Cbh7_rRaDyJKW-Vu6PX1N44LFwYxUqAc9LWz00IiRzPOOyLo8e_EpqBQejHh26yX-oXGnrCVtLQVDAiW8Cd4SOK1sW3ZnMaWXRA_Hh_Lx8sXtaZWiwlV2hubJ-jgrwbjsXKa6DK6eZx1mwrXv2vo_XxkklKHl5ImbXAmhEpALDsKs2SAaVnwLxncUtunHqF2lxg-UZAKAJ26F043NC5rebOTvcBCIijNuqNDmH0jtA" 
time="2016-06-08T17:43:13Z" level="fatal" msg="Failed to connect to proxy." error="websocket: bad handshake" 
```

**Expected:**
rancher-agent connect to the host registration url success.

**Comment by HackerWilson** [comment]
Anyone in rancher labs can answer this question?

**Comment by aemneina** [comment]
Hey @HackerWilson what is the host registration URL set to in rancher. Should be visible under Admin->Settings. I think that needs to match with the url/protocol you're using.

**Comment by HackerWilson** [comment]
when rancher deployed with 
```
export CATTLE_HA_HOST_REGISTRATION_URL=http://192.168.0.40:8080
```
host registration URL in rancher also becomes `http://192.168.0.40:8080`. both matched.

**Comment by aemneina** [comment]
What load balancer do you have in front of your HA cluster and how many hosts are in that rancher server pool?

**Comment by HackerWilson** [comment]
load balancer is nginx, 3 hosts there.

**Comment by aemneina** [comment]
I'll look to replicate this setup and see if there are any notables in getting it working.

**Comment by aemneina** [comment]
Hey @HackerWilson I managed to find time to dedicate to getting this working... using nginx 1.10.0 on ubuntu with the following configuration, YMMV. This should be the minimum viable config.

```
user www-data;
worker_processes auto;
pid /run/nginx.pid;

events {
           worker_connections 768;
           multi_accept on;
}

http {
           upstream rancher_srv {
               server <rancher_ha_node_ip>:80;
               server <rancher_ha_node_ip>:80;
               server <rancher_ha_node_ip>:80;
           }

           server {

               listen 80;
               location / {
                   proxy_set_header Upgrade $http_upgrade;
                   proxy_set_header Connection "upgrade";
                   proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                   proxy_set_header Host $host;
                   proxy_http_version 1.1;
                   proxy_pass http://rancher_srv;
               }
           }
}
```

HTH
