### ISSUE TITLE
How can I get the exit code for the standalone container execution?

### ISSUE THREAD

**Issue by kmakowski** [rancher/rancher#5040]
Hi, 

I wanted to run build process for my project as docker container that could be run on any of my nodes in rancher cluster. I am able to use standalone docker container api in order to execute the build process but the issue is I would like to notify my jenkins job if the execution was successful or not. when I run docker -it run on my machine I can see the exit code of the execution. But if I use rancher API I do not see any way to get the desired exit code.

**Rancher Version:**
1.1.0-dev1

**Steps to Reproduce:**
1. I run the standalone container (no specific scheduler rules so can be executed on any runcher host in the cluster)

**Results:** 

After the execution I see that container is stopped but I do not see in container API any information about exit code for the last execution

**Expected:**
Able to see last execution exit code

**Comment by sebradloff** [comment]
We would really appreciate this feature as well for ci pipeline work. Will the status of the container ever be available directly through the rancher api?

**Comment by superseb** [comment]
Closing this in favor of https://github.com/rancher/rancher/issues/5978, stay tuned.
