### ISSUE TITLE
Parse out http/https in the address field when creating custom registries

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#5043]
There have been multiple users who have accidentally put in the http or https in the Address, which has caused their private registry fail to connect.

Add a hint to the user.

**Comment by lvuch** [comment]
https://github.com/rancher/ui/pull/718

**Comment by EugenMayer** [comment]
why not make it even easier - parse the entered URI and strip it yourself if present. No docs, no hint, not possible errors :)

**Comment by tfiduccia** [comment]
Version - master 6/9
Hint added, keeping issue open and moving to 1.2.0 for Parsing addition.

**Comment by vincent99** [comment]
Added to validation

**Comment by tfiduccia** [comment]
Version - master 11/6
Verified fixed
