### ISSUE TITLE
"-" at start of stack name breaks internal DNS

### ISSUE THREAD

**Issue by mgmonteleone** [rancher/rancher#5044]
**Rancher Version:**
v1.1.0-dev4
**Docker Version:**
1.11.1
**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 14.04 hyperv virtuals
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher, internal db
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
This was discovered quite on accident, and is trivial, but thought should add in case anyone else comes across it. In an effort to show stacks which are in full production status first, added a "-" (dash) char in front of the name to have them sort first.

**Results:** 

Service discovery for the stack is broken, no service names will resolve.
After a bit of freaking out and debugging realized that SD is handled by adding search domains to the containers resolv.conf file. Having a dash at the beginning of those search domains ensures that nothing can resolve.

**Expected:**
Validation of stack name to prevent this user error.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
