### ISSUE TITLE
Be able to reboot host from infrastructure tab

### ISSUE THREAD

**Issue by sserrano44** [rancher/rancher#5045]
Would be great to reboot the host machine from the Rancher interface.

**Rancher Version:**
1.0.1

**OS and where are the hosts located? (cloud, bare metal, etc):**
AWS

**Comment by deniseschannon** [comment]
Are you expecting this to happen for the hosts that are created through the UI or just any hosts that are added to Rancher using a custom command. 

For the custom command, this would not be possible as we don't have a way to access it.

For the docker-machine created entries, I think you are looking for something similar to this: https://github.com/rancher/rancher/issues/1858

**Comment by vincent99** [comment]
The agent is privileged so it could call reboot to do a software reboot.  Hardware pulling the plug would require cloud provider integration (through docker-machine) and credentials for the particular VM.

**Comment by vincent99** [comment]
https://github.com/rancher/rancher/issues/1858
