### ISSUE TITLE
When rancher-compose removes all services from the stack, the stack state ends up as Started-Once

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#5048]
**Rancher Version:**
v1.1.0-dev4

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
1. Create a service using rancher-compose
2. Remove the service from rancher-compose using `rancher-compose rm --force`

**Results:** 
The stack is empty (as expected), but the state of the stack is now "Started-Once"

**Expected:**
The state of the stack to remain "Active".

**Comment by deniseschannon** [comment]
Verified that this is working with master build and rancher-compose v0.8.4-rc2

**Comment by zhang8473** [comment]
Was it fixed in 1.1.0? or will it be fixed in 1.2.0?

**Comment by deniseschannon** [comment]
This was fixed in 1.1.0 where the stack will remain as `Active` instead of `Started-Once`

Currently, there is no way to remove the stack completely. We have an enhancement request for it to delete a stack when removing services. 

https://github.com/rancher/rancher/issues/1723

**Comment by zhang8473** [comment]
After I create and delete hundreds of stacks, it becomes a big problem. Hundreds of empty stacks left in Rancher and the rancher server slows down a lot, almost not working.
