### ISSUE TITLE
rancher-compose too many open files

### ISSUE THREAD

**Issue by roderik** [rancher/rancher#5050]
**Rancher Version:** 1.0.2

**Docker Version:** 1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):** AWS t2 medium Ubuntu for rancher, RancherOS 4.2.8-ckt4-rancher for 3 medium aws nodes

*_Setup Details: *_ single single rancher server, 3 nodes, rds mysql for rancher. 

*_Environment Type: *_ Cattle

**Steps to Reproduce:**

creating and starting 1 big stack causes the network agent dns to fail with too many open files

**Results:** 

https://gist.github.com/roderik/2342c67b7b6dcbe4d42cdfc64a6d8eed

**Expected:**

No errors :)

**Comment by vincent99** [comment]
This looks like rancher-compose needs ulimits raised, there is no direct interaction between it and rancher-dns.  How big is a "big stack"?

**Comment by roderik** [comment]
32 services, 34 containers (for now, only the loadbalancer is scaled above 1)

rancher compose (latest version) is run on an El Capitan OSX rMBP i7 16GB

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
