### ISSUE TITLE
Host health check (purge host)

### ISSUE THREAD

**Issue by drundle** [rancher/rancher#5051]
In our cloud provider a host may go down and 1 of 2 things may happen (in this over simplified example)

1. it was just a blip in the host (ie restart, or network issue)
2. the sever went down and new VM has been provisioned.

in the former, doing nothing is fine, but in the latter it would be great to remove the existing host and recreate the containers which was on the dead host onto the new (shiny replacement) host.

it would be great if we could specify the pattern/strategy, ie if server is down more than 5 mins, then purge. I assume the strategy could be applied to a group of hosts (maybe identified by a specified label or host name), similar to how we identify the hosts with scheduling? 

with regards to stateful containers (again over simplified), it would be either clusters, thus new ones would join the cluster and be re-poputated, or it would be using a docker driver (attachable hdd) which would re-attach correctly.

**Comment by deniseschannon** [comment]
You can achieve what you want to happen with scenario 2 (having containers be recreated on another host) by adding in [health checks](http://docs.rancher.com/rancher/latest/en/rancher-services/health-checks/) to a service. The health check would fail and the containers would be recreated on another host. 

By design, Rancher does not want to automatically purge or delete any hosts.

**Comment by drundle** [comment]
@deniseschannon thanks, it makes sense that service health checks will be used to move services if they are found to be unhealthy.

if we expand the the case to hosts which are in a scale set (and can be automatically scaled by the IaaS provider), in this scenario it will leave a manual task to clean up any hosts which are currently not in use any more.

**Comment by deniseschannon** [comment]
Okay, I'm going to close in favor of this one if you just want to clean up hosts automatically: https://github.com/rancher/rancher/issues/3745
