### ISSUE TITLE
Add ability to edit frontend rules on haproxy load balancers

### ISSUE THREAD

**Issue by nunofgs** [rancher/rancher#5052]
**Rancher Version:** 1.1.0-dev3.

**Docker Version:** 1.10.3.

**OS and where are the hosts located? (cloud, bare metal, etc):** aws.

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single node rancher.

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** cattle.

**Steps to Reproduce:**
1. Add a load balancer.

**Results:** 

There is no way to customize the generated "frontend" section of the haproxy config file. In my specific case, I'd like to add a redirect from http to https by adding the following frontend rule:

> redirect scheme https code 301 if !{ ssl_fc }

**Comment by EugenMayer** [comment]
That would be a really handy feature. Not easy to implement i guess, since it is "per frontend" and maybe  and later there will be demand for "per backend"

**Comment by will-chan** [comment]
The latest Rancher should now allow you to edit both frontend and backend.
