### ISSUE TITLE
uri is null in the settings view

### ISSUE THREAD

**Issue by roderik** [rancher/rancher#5053]
**Rancher Version:** 1.0.2

**Docker Version:** 1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):** AWS t2 medium Ubuntu for rancher, RancherOS 4.2.8-ckt4-rancher for 3 medium aws nodes

**Setup Details:** single single rancher server, 3 nodes, rds mysql for rancher. 

**Environment Type:** Cattle

**Steps to Reproduce:**

Going to the settings screen

**Results:** 

![screen shot 2016-06-09 at 14 53 25](https://cloud.githubusercontent.com/assets/16780/15930232/09754920-2e52-11e6-9b02-dac35cb91d80.png)

**Expected:**

I'm running rancher behind an ELB with websocket support
I've destroyed and recreated the elb.
I've upgraded to 1.0.2 before this
I'm not sure if this stopped working with the 1.0.2 upgrade, or after the elb change

**Comment by vincent99** [comment]
Did you upgrade to 1.1.0-devX and then go back to 1.0.X?  It creates database entries that were previously invalid in 1.0 (no `uri`) and are not handled by the 1.0 UI.

**Comment by roderik** [comment]
No, went from 1.0.1 to 1.0.2

**Comment by deniseschannon** [comment]
@roderik Are you still facing issues?

**Comment by roderik** [comment]
Nope, it appears that i went to latest between the upgrade. Happily at 1.1.2 right now :)
