### ISSUE TITLE
Using named volume (in conjunction with convoy/glusterfs) causes path to be expanded

### ISSUE THREAD

**Issue by lewistaylor** [rancher/rancher#5054]
**Rancher Version:**
1.1.0-dev

**Docker Version:**
1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu on AWS EC2

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher, internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
The below is simplified, but effectively running this with rancher-compose up doesn't work as expected, where a convoy-gluster storage solution has been set up as per the tutorial. It wrongly reads the named volume as a relative path to the dir of the docker-compose file.

```
web:
  image: nginx
  volumes:
  - my_app_vol:/app/project/
  volume_driver: convoy-gluster
```

**Results:** 
Path expanded to /home/myuser/work/project/my_app_vol:/app/project

**Expected:**
For the service to make use of the storage pool's volume.

**Comment by vincent99** [comment]
Without specifying a volume driver it is just a relative path.

**Comment by lewistaylor** [comment]
Sorry my bad I am specifying one, just left it out, will update the issue.

On 9 June 2016 at 18:07, Vincent Fiduccia <notifications@github.com> wrote:

> Without specifying a volume driver it is just a relative path.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/rancher/rancher/issues/5054#issuecomment-224961570>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAeWNo6cuTp1cFBerjEmXqk3iReb5n5Qks5qKEhigaJpZM4IyI6H>
> .
>



-- 
*Lewis Taylor*

Managing Director
Danger Farms
lewis@dangerfarms.com
+44 75522 31643

Office 1.05, 1st Floor, 20 Ropemaker Street, London, EC2Y 9AR

**Comment by lewistaylor** [comment]
@vincent99 it becomes apparent when cloning the service. On going to volumes you can see the full path has been copied.

My thoughts are perhaps my volume driver isn't properly recognised somehow, but I can see it in within the storage pool area of rancher.

Any ideas?

**Comment by deniseschannon** [comment]
@lewistaylor I'm unable to reproduce with v1.1.0-dev5. When I use the named volume and clone it, it copies the named volume fine. 

Can you try again?

**Comment by lewistaylor** [comment]
@deniseschannon I just upgraded rancher and tried and the same thing, with the same results.Here is the output from running `up`

```
lewis:~/workspace/dangerfarms/test $ rancher-compose up
WARN[0001] A newer version of rancher-compose is available: 0.8.4
INFO[0001] Creating stack test
INFO[0001] Creating service web
WARN[0001] The mapping "my_app_vol" is ambiguous. In a future version of Docker, it will designate a "named" volume (see https://github.com/docker/docker/pull/14242). To prevent unexpected behaviour, change it to "./my_app_vol".
INFO[0002] Project [test]: Starting project
INFO[0002] [0/1] [web]: Starting
INFO[0005] [1/1] [web]: Started
INFO[0005] Project [test]: Project started
```

What version of docker/rancher-compose are you using?
Also might it be I am not naming the volume correctly? Convoy gluster is the name of the storage pool but I haven't created a volume associated with that pool.

**Comment by deniseschannon** [comment]
I always use the rancher-compose version tied to a release. In this case, it would be rancher-compose v0.8.4.

**Comment by deniseschannon** [comment]
@lewistaylor If you still have questions, please re-open. 

Please note that we have removed GlusterFS and Convoy Gluster from the catalog as users were expecting a robust tool as an alternative persistent storage for Docker volumes.  However, due to lack of active maintenance, we cannot recommend this solution going forward.

Instead, we recommend and certify Convoy NFS, which is actively maintained by Rancher.
