### ISSUE TITLE
Support for Azure SQL

### ISSUE THREAD

**Issue by kvaes** [rancher/rancher#5056]
The HA setup of Rancher indicates the following ; 

"This can be a hosted solution like Amazon RDS or Google Cloud SQL,"

Would it be possible to support MSSQL via the Azure SQL too? Sadly enough Azure does not have a (decent) MariaDB/MySQL offering.

**Comment by PhilipSchmid** [comment]
Any updates on this? I would also need MSSQL support in order to use Rancher in our productive environment. Thanks.

Regards,
Philip

**Comment by will-chan** [comment]
Sadly, this is not something in our priorities right given that the support matrix for the combination or OS to Docker to k8s to DB would grow immensely.  However, we will keep this open in the event we end up implementing and supporting it.

**Comment by SilentHunter124** [comment]
I think this should really get a higher priority if you want to enable your product as "enterprise ready" solution. I also can only offer mssql as database in our datacenter... What do you think?

**Comment by vincent99** [comment]
@SilentHunter124 This may change someday with Docker for Windows Server, but today there is simply not very much demand for an expensive way to run a database on an OS foreign to 99% of Docker installations.

https://forums.rancher.com/t/support-for-microsoft-sql-server/2255/8?u=vincent

> The practicality of this is it's effectively a "PRs accepted" kind of feature. If someone wants to write it we'll take a PR for it. For example, experimental Postgres support was added by a community member and merged into 1.2. But it is not practical for us (as a company) to be spending a bunch of time building support for a DB that is of no use to us personally, without a customer that wants to pay for development and ongoing testing of officially supporting it.

**Comment by vincent99** [comment]
Note that Azure now has MySQL support: https://techcrunch.com/2017/05/10/microsoft-launches-azure-database-for-mysql-and-postgressql/

**Comment by kvaes** [comment]
@vincent99 ; 
For some odd reason... guess which one... I guess you'll run into this issue ; 
https://github.com/rancher/rancher/issues/6576

**Comment by fkollmann** [comment]
Currently get an "this user requires mysql native password authentication" error.  #9018

**Comment by vishnuvpotti** [comment]
I think apart from MySQL, either Oracle/MSSQL support is required (Rancher with exteranl DB). Our corporate policy allows only MSSQL, and they are sceptical about MySQL. This is causing issues as we are blocked from deploying containers in prod environments using Rancher Server.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
