### ISSUE TITLE
[UI/Catalog] radio boxes are not prepopulated

### ISSUE THREAD

**Issue by EugenMayer** [rancher/rancher#5057]
**Rancher Version:**
1.1.0-dev2

**Docker Version:**
Docker version 1.10.3, build 20f81dd

**OS and where are the hosts located? (cloud, bare metal, etc):**
baremeta, rancheros

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
cattle

**Steps to Reproduce:**
1. Use a catalog with a bool type ( radio box ), select true, deploy it
2. create and upgrade for that catalog
3. click on "upgrade" in the stack
4. select the new version

**Results:** 
The form you see does not map the pre-selected values of the last catalog configuration for radio boxes (no value selected at all, that means, wrong value type)

**Expected:**
Radio-Boxes do reflect the value selected the last time the catalog has been deployed

**Comment by vincent99** [comment]
This was fixed in 1.1.0-dev5, https://github.com/rancher/rancher/issues/4085

**Comment by EugenMayer** [comment]
thanks!
