### ISSUE TITLE
New Fields in Docker Machine 0.7

### ISSUE THREAD

**Issue by wlan0** [rancher/rancher#5063]
@vincent99 - Here's a list of changes to the driver fields from v0.6 of DM compared to v0.7 of DM

#### Amazon EC2
-----------------------------

| Added Fields  | Deleted | Changed Fields | 
| ------------------  |  --------- |  -------------------- |
| amazonec2-retries  |              |                           |

#### Azure
-----------------------------

| Added Fields  | Deleted | Changed Fields | 
| ------------------  |  --------- |  -------------------- |
|  azure-environment  | azure-docker-swarm-master-port             |                           |
|  azure-resource-group | azure-password             |                           |
|   azure-ssh-user  | azure-publish-settings-file             |                           |
|   azure-vnet  | azure-ssh-port           |                           |
|   azure-subnet  | azure-subscription-cert   |                           |
|   azure-subnet-prefix  | azure-username  |                           |
|   azure-availability-set  |  |                           |
|   azure-open-port |  |                           |
|   azure-private-ip-address |  |                           |
|   azure-use-private-ip |  |                           |
|   azure-static-public-ip |  |                           |
|   azure-no-public-ip |  |                           |

#### DigitalOcean
-----------------------------

| Added Fields  | Deleted | Changed Fields | 
| ------------------  |  --------- |  -------------------- |
| digitalocean-ssh-key-fingerprint  |              |                           |

#### Exoscale
-----------------------------

| Added Fields  | Deleted | Changed Fields | 
| ------------------  |  --------- |  -------------------- |
| exoscale-ssh-user  |              |                           |
| exoscale-userdata  |              |                           |

#### OpenStack
-----------------------------

| Added Fields  | Deleted | Changed Fields | 
| ------------------  |  --------- |  -------------------- |
|  |              |                           |

#### Rackspace
-----------------------------

| Added Fields  | Deleted | Changed Fields | 
| ------------------  |  --------- |  -------------------- |
| rackspace-active-timeout  |              |                           |

#### VmWare VSphere
-----------------------------------

| Added Fields  | Deleted | Changed Fields | 
| ------------------  |  --------- |  -------------------- |
|   |              |                           |

**Comment by vincent99** [comment]
@westlywright Amazon driver needs to change to be given an array of security groups.. you can make it a list of checkboxes you can check for all the existing security groups, plus a separate option for the standard (`rancher-machine`) group..

Security Groups
-----
[x] {"create a new" or "use the existing"} rancher-machine group

Custom security groups:
[ ] your group 1
[ ] your group 2
[ ] your group 3

**Comment by tfiduccia** [comment]
Version - v1.2.0-pre3-rc3
Verified added field to exoscale & checkbox list for ec2
