### ISSUE TITLE
Host IP in ports is dropped during the cattle transformation from rancher-compose

### ISSUE THREAD

**Issue by bradjones1** [rancher/rancher#5064]
**Rancher Version:**
v1.1.0-dev4

**Rancher-Compose version:**
0.8.3

**Docker Version:**
1.11.1

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 14.04 LTS - cloud

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node Rancher, external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Swarm

**Steps to Reproduce:**
Create a stack with a service containing a `[host-ip:port]:[internal port]` configuration in the UI. It will work. Export the `docker-compose.yml` and `rancher-compose.yml` files with the web UI. Try to create an identical stack with the CLI, and Rancher loses the Host IP and port configuration, and flattens the config to `port:port`.

**Results:** 
Host IP port configuration is lost and service attempts to bind globally to the port in question.

**Expected:**
The service binds the container IP to the specified IP/port combination on the host.

This is basically a continuation of #4425 which was closed as "most likely working," but apparently it's not :-)

I'm also having trouble with service IP configuration on https://github.com/rancher/rancher/issues/5033 and this sounds kinda like #4540. Looks like the rancher-compose support for IP configuration needs some continued love. Let me know what I can do to help move these issues along. Thanks!

**Comment by deniseschannon** [comment]
Reproduced with v1.1.0-dev4 and rancher-compose v0.8.3.

Steps to Reproduce:
1. Cattle stack
2. Create a service with `hostIP:port` as public port 
3. Export the yaml and try to launch using either "Add Stack" or rancher-compose CLI (both use rancher-compose), make sure to change the port so there is no port conflict. 

The host IP is not part of the ports in the API. The parsing in rancher-compose is removing the host IP.

**Comment by joshwget** [comment]
The host IP is being dropped when Rancher Compose calls the Cattle transformation API, so this is likely a Cattle issue.

**Comment by bradjones1** [comment]
It happens on a swarm cluster too, fwiw.

**Comment by alena1108** [comment]
@deniseschannon looks like Rancher compose issue. UI/API generates the ports in seemingly correct format:

```
version: '2'
services:
  alena:
    ports:
    - 1.1.1.1:80:80/tcp
    labels:
      io.rancher.container.pull_image: always
    tty: true
    image: ubuntu:14.04.3
```

I've fed this config file to rancher-compose, and put a debug breakpoint in the service create code. The "port" api field came to the API as ```ports=[80:80/tcp]```: 

```
{stackId=3, scale=1, launchConfig={imageUuid=docker:ubuntu:14.04.3, labels={io.rancher.container.pull_image=always, io.rancher.service.hash=92ecb8e8c6991f7135d0d587005d906d36bb7712}, logConfig={}, networkMode=managed, ports=[80:80/tcp], startOnCreate=true, tty=true, kind=container, privileged=false, publishAllPorts=false, readOnly=false, stdinOpen=false, system=false, version=0, vcpu=1}, name=alena, metadata={io.rancher.service.hash=24607a0e17ffe57b0e8bb0feafd117ba5a50452f}, system=false, assignServiceIpAddress=false, startOnCreate=false}
```

**Comment by deniseschannon** [comment]
@joshwget @alena1108 Can you guys talk about this in the office as it seems like there is no consistency in where the issue actually is. :)

**Comment by will-chan** [comment]
@deniseschannon can we get a resolution to this issue?

**Comment by StrongMonkey** [comment]
@will-chan Not sure how it works in rancher-compose side. Will take a look.

**Comment by tfiduccia** [comment]
Version - master 2/7.

I entered the yaml and it's exporting and importing properly for Main Service type.  Load Balancer HostIP is still broken but documented in #7288.

Tani
