### ISSUE TITLE
Machine Driver UI Issues

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#5066]
**Rancher Version:**
v1.1.0-dev4

- [ ] ~~No place to add name for new machine drivers. I found a valid URL and it autmoatically picked up a name, is this normal for machine-drivers?~~

<img width="969" alt="screen shot 2016-06-09 at 11 20 40 pm" src="https://cloud.githubusercontent.com/assets/11410997/15955830/369b8c42-2e99-11e6-8c6d-18a73886a17d.png">

- [x] After adding a machine driver, it's inactive, but doesn't have the "Inactive" bar on it. This seems to only occur if there is an error in the Download URL. Can we somehow show an error?

<img width="272" alt="screen shot 2016-06-09 at 11 20 54 pm" src="https://cloud.githubusercontent.com/assets/11410997/15955824/2e619c60-2e99-11e6-946c-0e90ed6d4815.png">

- [x] In Infrastructure -> Hosts, cllicking on "Manage available machine drivers" directs back to the Admin->Settings pages instead of the new Admin -> Machine Drivers page

<img width="469" alt="screen shot 2016-06-09 at 11 22 31 pm" src="https://cloud.githubusercontent.com/assets/11410997/15955827/330e9fd8-2e99-11e6-9da8-075f22b0dbff.png">

**Comment by vincent99** [comment]
Name is not a settable field anymore, we get the name from the downloaded driver.

**Comment by tfiduccia** [comment]
Version - master 6/16
Verified fixed
