### ISSUE TITLE
virtual machine options disapeared in the gui

### ISSUE THREAD

**Issue by joostliketoast** [rancher/rancher#5067]
*Describe your issue here*

I am running the latest Rancher installation.
But i am missing the Virtual machine options in the GUI while the latest stable release did have this....
Is this removed on purpose (all the hosts support KVM)?
There is also nothing in the settings page to turn it on.
Is there a way to enable it again cause i am really missing this feature.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.1.0-dev4` Cattle: `v0.162.1` UI: `v1.1.3` |
|Access|`github` `admin`|
|Orchestration|`Cattle`|
|Route|`admin-tab.settings`|

**Comment by deniseschannon** [comment]
The virtual machine options were moved to the environment level. So it can be found for each environment. You can edit an existing environment to enable VMs.
