### ISSUE TITLE
[UI] unable to point Rancher to my custom UI

### ISSUE THREAD

**Issue by dalareo** [rancher/rancher#5068]
I follow the steps to point my index.html to http://myserver.com/latest/index.html changing http://your-rancher:8080/v1/settings/api.ui.index from "local" to //myserver.com/latest but... I get:

HTTP ERROR 404 when trying to access any static asset. Any clue? @vincent99 

If I edit index.html inside Rancher container (/usr/share/cattle/war/index.html) and set assets URL to //myserver.com/latest/assets... I can get my assets to load but I get:

%failWhalePage.header%%failWhalePage.reloadButton%%failWhalePage.logoutButton%

and "my-rancher:8080/fail" URL in my browser

**Comment by dalareo** [comment]
Could I force the value with environment value CATTLE_API_UI_INDEX=http://myserver/latest/index.html ??

**Comment by vincent99** [comment]
@dalareo What are some of the URLs of assets it's trying to load that fail, and what is the actual URL that would load them from your server?

All our developers environments default to pointing to a remote copy that is updated by CI every time rancher/ui master changes, so I know this works..  You could try that copy: `//releases.rancher.com/ui/latest`

**Comment by dalareo** [comment]
Static assets are hosted at https://fricolab.com/educaas/. If I point to //releases.rancher.com/ui/latest everything seems fine, . So... the problem is exporting building static assets of UI!! I am just following UI readme.md steps!

    ./scripts/build-static -v educaas -c 'fricolab.com'

Is it right?

**Comment by dalareo** [comment]
Thanks, @vincent99, I will try to host my static files in another server.

As I told you UI repository is not working anymore!! It redirects to https://0.0.0.0:8000/fail!! I tried with two different machines (Ubuntu 16.04 and Arch Linux) and different versions of Node. Should I open another issue related to this??

**Comment by dalareo** [comment]
You were right, @vincent99, hosting my static files in another server (even localhost with ngrok) is working. But now, what is more important is the issue related with translations. In the console I get:

    translation not found: locale='unknown'

Right now I cannot even build ember server locally. I get this message and only get myrancher:8000/fail url.

**Comment by vincent99** [comment]
@dalareo Try updating and `npm install ember-intl`?  I'm not sure exactly why we don't get it normally but I saw the same issue and updating it (to 2.12.0, which is changed in the below PR) fixed it because it was looking for the config in the wrong path

**Comment by dalareo** [comment]
@vincent99 great! solved the issue
