### ISSUE TITLE
Revert option not shown for snapshots of volumes that are not in use by any VM.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#5071]
Rancher server - Build from master

Steps to reproduce the problem:
Deploy a VM service with ROOT volume in longhorn.
Take few snapshots.
Stop VM service.

After this , I should be given an option to do revertosnapshot for the ROOT volume of this VM to one of the snapshots.

There is no option presented in UI for doing this.

**Comment by cjellick** [comment]
Might be my problem if the action isnt showing up

**Comment by vincent99** [comment]
Revert wasn't implemented at the time, it is now.

**Comment by sangeethah** [comment]
Tested with UI version - v1.1.6

Revert volume to Snapshot option is seen for snapshots when the Volume that they were created from is not in use by any VM.
