### ISSUE TITLE
Restore option not shown for backups of volumes that are not in use by any VM.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#5072]
Rancher server - Build from master

Steps to reproduce the problem:
Deploy a VM service with ROOT volume in longhorn.
Take few snapshots.
Stop VM service.
Create Backup of snasphot.

After this , I should be given an option to do restorefrombackup for the ROOT volume of this VM from this backup.
There is no option presented in UI for doing this.

**Comment by cjellick** [comment]
Might be my problem if the action isnt showing up

**Comment by vincent99** [comment]
Restore wasn't implemented at the time

**Comment by sangeethah** [comment]
Tested with UI version - v1.1.6

Restore volume from Backup option is seen for backups when the Volume that they were created from is not in use by any VM.
