### ISSUE TITLE
Have text in storage view to indicate that the expanded view for volumes is a snapshot list.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#5073]
Rancher-server: Build from master

Currently it is not obvious that the expanded view for volumes that is presented is a snapshot list.
<img width="1091" alt="screen shot 2016-06-10 at 10 29 08 am" src="https://cloud.githubusercontent.com/assets/4266958/15973032/3553b398-2ef6-11e6-8d17-6ae6ebbe0aee.png">

**Comment by vincent99** [comment]
![image](https://cloud.githubusercontent.com/assets/753917/16036371/74be146a-31d0-11e6-9eae-297d5ae60fa8.png)
