### ISSUE TITLE
Set Cookie to Secure on Server Dockerhub Container if TLS enabled

### ISSUE THREAD

**Issue by simon-hardy** [rancher/rancher#5075]
**Rancher Version:**
v1.0.2

**Steps to Reproduce:**
Add SSL Cert to Rancher Server Docker image using docker run.

Create users.

Connect and login over HTTPS
Switch to HTTP.

**Results:** 

Session persists.

**Expected:**

Session should not persist over the HTTP connection as this exposes the session to highjacking which is catastrophic with the level of access Rancher has to an environment.

**Comment by vincent99** [comment]
It's supposed to be, but the options are passed wrong here https://github.com/rancher/ui/blame/master/app/services/access.js#L102-L104

**Comment by tfiduccia** [comment]
Version - v1.2.0-pre3-rc1
Verified fixed
