### ISSUE TITLE
Kubernetes environment stuck at "Starting services (9 of 10)" 

### ISSUE THREAD

**Issue by futuretec** [rancher/rancher#5081]
**Rancher Version:** v1.1.0-dev4

**Docker Version:** v1.10.3 (build 20f81dd)

**OS/Host:** Mac OS X (10.11.5) with VirtualBox (Linux 4.1.19-boot2docker VM)

**Setup Details:** Single node Rancher

**Environment Type:** Kubernetes

**Steps to Reproduce:** Add Host to K8s environment and wait for initialization.

**Results:** Init is stuck at "Starting services (9 of 10)", although it seems that all necessary services and stacks have been fully initialized and started without errors

**Expected:** Successfully start K8s environment

**Comment by bchelli** [comment]
+1

I have the same problem over here
- Single Rancher node
- 3x 2CPU - 4GB DigitalOcean instances

**Comment by bchelli** [comment]
Apparently the latest tag of the docker container is pointing to the dev version.
I'm installing the latest stable version to check if this is solving the issue.

I'll keep you in the loop.

**Comment by futuretec** [comment]
@bchelli 
Yes the stable versions still works.
But in my case I would like to use v1.1.0 (for K8s support of private registries) - so reverting to a stable version (v1.0.2) won't work

**Comment by bchelli** [comment]
@futuretec 👍 
As you mentioned in your response, it is properly working on v1.0.2...
Good luck with v1.1.0

**Comment by gauravve** [comment]
I am having a similar problem with the latest dev release

**Comment by deniseschannon** [comment]
I've launched the latest dev release and had no issues with launching my Kubernetes environment.

I have 3 DO hosts running Docker 1.10.3 in my k8s environment. 

@futuretec How many hosts did you have?

**Comment by futuretec** [comment]
@deniseschannon I did use a single host with 1vCPU and 4GB RAM. No issues in launching rancher/server:v1.1.0-dev3 and manually upgrading to rancher/k8s:v1.2.4-rancher2 (so that I can use private registries with K8s)

**Comment by jmloeffler** [comment]
I had this problem and restarted the discovery container from the rancher UI.  This seemed to get it to recognize that all services were up.  It could be unrelated but it seemed like I had the same situation and I had determined that it was some sort of race condition as things were spinning up.

**Comment by tfiduccia** [comment]
Version - master 6/13
I checked and this is indeed broken.  If you have a single host, the waiting screen thinks it's stuck at 9 of 10 services even though it's done.  Not sure if this is UI or backend problem.  

Steps - create a kubernetes environment with a single host.

**Comment by soumyalj** [comment]
@tfiduccia : This happens even if we have multiple hosts. I have tried with 3 hosts

**Comment by tfiduccia** [comment]
Did a little research and there seems to be a new service that was added to the environment.  	discovery + 1 Sidekicks Service is a started Once service that didn't exist before.  The environment I setup a couple of days ago did not have this service and worked fine.

**Comment by tfiduccia** [comment]
Version - master 6/16
Verified fixed

**Comment by pakuni** [comment]
I am also facing similar issue it hangs up in service 2/10, my docker version is 1.12.6
