### ISSUE TITLE
rancher-compose rm -f force purge 

### ISSUE THREAD

**Issue by guzmo** [rancher/rancher#5082]
Are there anyway to force rancher-compose rm -f to wait until the containers are purged?

Until they are fully purged they still use the Name and this will make conflicts when starting up again before all containers are fully purged.

Cheers!

**Comment by deniseschannon** [comment]
Are you saying that you want the `rancher-compose rm -f`to not exit until the containers are fully purged?

**Comment by guzmo** [comment]
Atleast if I add an extra argument like --purge. Right now it takes like 20 sec after everything is stopped until they starts to be purged and I need to wait for that until I start the system up again.

I dont want the container names to be uuids instead of the name they should have.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
