### ISSUE TITLE
Post fails while deploying to vSphere msg="Error processing event" err="Post https://xx.xxx.x.x:2376/images/create?fromImage=rancher%2Fagent&tag=v1.0.1: Forbidden

### ISSUE THREAD

**Issue by alxndr13** [rancher/rancher#5083]
**Rancher Version:** v1.1.0-dev4 (i also tried it with v1.1.0-dev3)

**Docker Version:**  1.11.1

**OS and where are the hosts located? (cloud, bare metal, etc):** Red Hat Enterprise Linux Server release 7.2 (Maipo) - VM

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single node rancher, internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:**
- Add Host in Rancher
- Choose vSphere as machine Driver
- Deployment starts, machine is visible in vSphere, immediately gets removed.
  See the log here: https://gist.github.com/alxndr13/6d1bf67314e570159ac825e5955b3655

**Results:** The machine cant be used and im getting an error, which is in the log i shared.

**Expected:** vSphere machine should be usable in Rancher. 

Extra info: we're running behind a corporate proxy, but my rancher/server uses the proxy correctly. 
I tried the commands, which rancher creates - manually - and these are working properly.

**Comment by alxndr13** [comment]
Seems like, rancher is cleaning up before the Post can even be executed..

**Comment by Rots** [comment]
Any workarounds for this?

**Comment by aemneina** [comment]
@alxndr13 @Rots are you guys hitting this with rancher 1.4.1? Have you tried this with docker-machine directly? Thats what rancher would use to provision these hosts... it would be good to narrow down what might be going wrong in the process.

**Comment by alxndr13** [comment]
yes i did, i updated in the meanwhile and now it works. cant tell which version did it. 

Am 22. Februar 2017 01:45:24 MEZ schrieb Ahmad E <notifications@github.com>:

**Comment by aemneina** [comment]
awesome news, I'll close this issue out.

**Comment by Rots** [comment]
I still get the problem with latest setup: rancher-server 1.4.1, agent 1.2.0

> Error (Post https://x.x.x.x:2376/images/create?fromImage=rancher%2Fagent&tag=v1.2.0: Forbidden)

When using docker-machine (0.9.0) directly to provision the machine, it does not report problems, it creates the VM and it's usable. Also `docker-machine ls, start, stop, env, ip, url, ssh` commands seem to work, but some with a delay of 5-6 sec.
The `docker-machine ls` reports a timeout

> NAME              ACTIVE   DRIVER          STATE     URL                        SWARM   DOCKER    ERRORS
> docker1                    vmwarevsphere   Timeout    

  
Related topics
https://github.com/docker/machine/issues/3538

Also reported here:
https://github.com/docker/machine/issues/3388
http://serverfault.com/questions/819056/docker-machine-vmwarevsphere-driver-error

**Comment by aemneina** [comment]
@Rots can your rancher server host ssh to the vmware vm's?

**Comment by Rots** [comment]
@aemneina yes, and I double-checked that the rancher/server container can as well

**Comment by Rots** [comment]
@aemneina just to ping in, I just tried with the latest stable rancher server 1.6.0 and I still run into the same issue with vSphere provisioning.

> Post https://x.x.x.x:2376/images/create?fromImage=rancher%2Fagent&tag=v1.2.2: Forbidden

Where x.x.x.x is the IP of the newly created VM.

> Seems like, rancher is cleaning up before the Post can even be executed..

The difference now is that the machine is not cleaned up as it was earlier. Only when I choose to delete the machine on Rancher UI, it is removed.

**Comment by aemneina** [comment]
Can you ssh into that newly created agent host. We need to figure out at what stage of the docker machine provisioning its failing. I'd check to see if docker is installed, then see if the rancher agent ever got launched (`docker ps -a`).

**Comment by Rots** [comment]
Yes, docker is installed and running.
`docker ps -a` gives me an empty list (no containers). `docker images -a` also shows an empty list.

Here's the complete log from rancher server
https://pastebin.com/JCXcUexP

Also, `docker pull rancher/agent:v1.2.2` manually on that machine works.

Oddly enough the `docker-machine` directory reported in the logs does not exist inside the rancher/server container. Or am I looking at the wrong place?
```
# docker exec -it 2c1 bash
root@2c1ff9090e79:/# ls -la /var/lib/cattle/machine/machines/
total 8
drwxr----- 2 root root 4096 Jun  1 17:53 .
drwxr----- 3 root root 4096 May 31 19:32 ..
```
