### ISSUE TITLE
How to modify the cloud-config settings in RancherOS with hosts deployed via the EC2 option in Rancher

### ISSUE THREAD

**Issue by roderik** [rancher/rancher#5084]
I've deployed some hosts with RancherOS via the interface of Rancher on EC2. I need to apply this fix https://github.com/rancher/rancher/issues/1219 to work around some open file issues, but can't find documentation or an option to do so from the RancherUI. Is there a way or do i need to move to the custom option?

**Comment by deniseschannon** [comment]
Are you launching through the UI? If so, thee is no way to apply a cloud-config (through userdata) when launching a docker-machine host (how we deploy through the UI).

**Comment by roderik** [comment]
Ok thanks!

**Comment by andrewcstewart** [comment]
Is there a work around for this?

**Comment by deniseschannon** [comment]
@andrewcstewart Workaround for which one? Docker Machine doesn't support being able to apply a cloud-config through userdata, which is something we can't support. 

But if you're looking for a workaround for #1219, if you're running RancherOS v0.7.0, you can run 

```
sudo ros config set rancher.docker.extra_args '[ --default-ulimit, nofile=1000000:1000000]' 
```

for the limit issue that @roderik had referenced.
