### ISSUE TITLE
[Mesos] Is it possible to point Rancher load balancer to Marathon task by a task name? 

### ISSUE THREAD

**Issue by strobe** [rancher/rancher#5085]
Unfortunately current documentation doesn't has enough information about integration layer between usual mesos frameworks and rancher infrastructure, thereby is not clear how to use LB to dynamically make Marathon/Mesos tasks be available from external networks (service discovery inside Mesos env. can be achieved by some additional components like marathon-lb and mesos-dns, but I think anyway documentation should to recommended some general approaches ).   

For additional information please read this:
https://forums.rancher.com/t/is-it-possible-to-manage-mesos-marathon-tasks-by-rancher-load-balancer-and-few-additional-mesos-related-questions/3085

**Rancher Version:**
v1.1.0-dev3
**Docker Version:**
1.11.1
**OS and where are the hosts located? (cloud, bare metal, etc):**
ubuntu 14.04, local VMs at Ovirt 
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher + 4 nodes
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Mesos

**Comment by LLParse** [comment]
Short answer: it is possible, but not without writing code.

Rancher LB could be used to route/balance Mesos workload traffic. We would need to register [Zookeeper watches](https://zookeeper.apache.org/doc/r3.4.6/zookeeperProgrammers.html#ch_zkWatches) for relevant tasks and generate LB configuration whenever a change is encountered. This would allow us to load balance not only Marathon services, but any Mesos frameworks we see fit.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
