### ISSUE TITLE
Issues in Mobile

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#5088]
**Rancher Version:** Master 6/9

- [x] Can't change environments when menu is dropped-down - Have multiple environments setup and the menu dropped down.  I can't select any environment below bcd in the below image.
![image](https://cloud.githubusercontent.com/assets/11514927/15954602/e1c011bc-2ea6-11e6-9081-b958045405bd.png)

- [x] Lines from menu bleeding into environment drop-down.
![image](https://cloud.githubusercontent.com/assets/11514927/15954613/09bbe4ca-2ea7-11e6-971a-6a61a8b0053d.png)

- [ ] Can't tab to menu drop-down
![image](https://cloud.githubusercontent.com/assets/11514927/15954615/1a458756-2ea7-11e6-9779-ff09948d4c52.png)

- [x] User menu image is missing
![image](https://cloud.githubusercontent.com/assets/11514927/15954628/4cc29336-2ea7-11e6-8d01-316936578aa1.png)

- [x] In Service info popup there are wierd dividing lines showing up on right side
![image](https://cloud.githubusercontent.com/assets/11514927/15336214/545be5be-1c2a-11e6-8545-7d2920c93372.png)

**Comment by lvuch** [comment]
![screen shot 2016-06-13 at 3 10 19 pm](https://cloud.githubusercontent.com/assets/3013118/16024898/1bbb3da4-3179-11e6-96f9-b988abacde5a.png)

When authenticated user info shows in drop down

**Comment by tfiduccia** [comment]
Version - master 6/15
Verified fixed
