### ISSUE TITLE
Missing "(# out of 10)" when starting kubernetes environment

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#5095]
**Rancher Version:** master 6/13

**Steps to Reproduce:**
1.  Create a kubernetes environment
2.  Add host and wait till you get to the Starting services

**Results:** The "1-8 of 10" message is missing
![image](https://cloud.githubusercontent.com/assets/11514927/16020380/b161df1e-3162-11e6-8b42-b4a27e3c90fb.png)

**Expected:** Should have text

**Comment by tfiduccia** [comment]
Version - master 6/15
Verified fixed

**Comment by vincent99** [comment]
This sometimes works and sometimes doesn't, depending on the phase of the moon or something.

**Comment by tfiduccia** [comment]
Many other more specific bugs about this.  I will close and defer to Soumya's more specific issues.
