### ISSUE TITLE
UDP support needed when adding Load Balancer to Stack

### ISSUE THREAD

**Issue by donnlee** [rancher/rancher#5096]
*Describe your issue here*

Seems choices are HTTP or TCP only.
collectd runs on UDP 25826, by default.
Pls support UDP when adding LB.

Is there a workaround?  Maybe I'd have to manually edit the haproxy .conf?

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.1.0-dev4` Cattle: `v0.162.1` UI: `v1.1.4` |
|Access|`Disabled`|
|Orchestration|`Cattle`|
|Route|`environment.index`|

**Comment by vincent99** [comment]
HAProxy does not do UDP balancing.

**Comment by deniseschannon** [comment]
As Rancher uses HAproxy software and HAproxy doesn't support UDP balancing, we wouldn't be able ot add this into the Rancher Load balancer.

**Comment by lgcosta** [comment]
Nginx now support UDP load balance ! add nginx as a alternative to the haproxy ?

https://www.nginx.com/blog/announcing-udp-load-balancing/
