### ISSUE TITLE
Refreshing browser with dev tools on gives Failed to parse SourceMap error

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#5097]
**Rancher Version:** master 6/13

**Steps to Reproduce:**
1.  Open DevTools in Chrome
2.  refresh screen

**Results:** Get a Paused in debugger. In dev tools says: Failed to parse SourceMap: **http://releases.rancher.com/ui/latest/assets/vendor.map**

**Expected:** No pause and failure?

**Comment by guiguan** [comment]
Same here

**Comment by tfiduccia** [comment]
Version - master 9/16
No longer showing "Failed to parse SourceMap"  - Closing
