### ISSUE TITLE
Safari - Announcements never shows up

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#5098]
**Rancher Version:** master 6/13

**Steps to Reproduce:**
1.  In Safari go to help page

**Results:** Nothing but ... shows up in announcement section
![image](https://cloud.githubusercontent.com/assets/11514927/16021550/2b290980-3168-11e6-8294-e64adda9b782.png)

**Expected:** Should have Latest: info and Released: info

**Comment by vincent99** [comment]
I think this was fixed a while ago...

**Comment by tfiduccia** [comment]
Version - v1.2.1-rc2
Verified fixed
