### ISSUE TITLE
Allow configuration of subnet ip address space for managed networking

### ISSUE THREAD

**Issue by will-chan** [rancher/rancher#510]
Currently, 10.42.0.0/16 is the default subnet for Rancher's managed network and is hardcoded in startup seed data population.  Rancher needs to be able to allow the configuration of this subnet.

**Comment by vincent99** [comment]
But..but..42 is the ultimate answer

**Comment by raphink** [comment]
For that reason precisely. May be bad luck, but we have set up our rancher AWS VPC on a 10.42.1.0/24, split into 4 /26, using 3 (1 per eu-west-1 zone). It took me quite a bit of time to understand why it wasn't possible to set up an ELB in front of all the nodes, until I realized rancher used 10.42/8 internally and blocked connections from that network. Because it can't be configured, it seems we have to recreate our VPC and rancher infrastructure.

**Comment by deniseschannon** [comment]
@raphink Please look at this to change the Rancher subnet with the API settings. http://docs.rancher.com/rancher/faqs/#the-subnet-used-by-rancher-is-already-used-in-my-network-how-do-i-change-the-subnet

**Comment by deniseschannon** [comment]
@will-chan Is the docs sufficient (about how to update using API settings) or did you want something else to update the subnet?

**Comment by raphink** [comment]
Ah great, thank you @deniseschannon, I will look into that! We might not be the only ones to choose a 10.42 network, so others might want to find this info easily, too :smile: !

**Comment by raphink** [comment]
@deniseschannon so after I do that change, what can I do about the Default environment? Do I have to delete it and re-create it?

**Comment by deniseschannon** [comment]
Yes @raphink, per the docs, you will need to delete it and re-create it. It's just another environment with the name "Default" so you could make the same one. :)

**Comment by will-chan** [comment]
We should add UI support for this as I assume this is just another setting.

**Comment by vincent99** [comment]
@will-chan but it's a setting that requires restarting the containers and auch to take effect, so it's only really practical to set on initial setup, where you can do it as environment bars...

**Comment by jfornoff** [comment]
Hi there, sorry to resurrect this issue, but is configuration of the subnet IP adress space is causing me bit of a headache while upgrading to 1.2.2.

[FAQ](http://docs.rancher.com/rancher/v1.3/en/faqs/troubleshooting/) is telling me under "THE SUBNET USED BY RANCHER IS ALREADY USED IN MY NETWORK AND PROHIBITING THE MANAGED NETWORK. HOW DO I CHANGE THE SUBNET?":

1 - Export the rancher-compose.yml and docker-compose.yml file for the Ipsec Network Service
2 - Change the `default_network` subnet setting
3 - Redeploy the service

Steps 1 and 2 are workable, but I have no idea how to redeploy the service.
If I attempt to bring it up with `rancher --url <rancherurl> --access-key <key> --secret-key <secret> --env <env-id> up -d`, the deployment works, but it appears as a user stack (expected it to show up as an infrastructure stack) and errors with:
`Failed to allocate instance [container:1i5210]: Bad instance [container:1i5210] in state [removed]: Failed to find network for networkMode ipsec`

Can you help me out on this one?
Thanks a ton!

**Comment by deniseschannon** [comment]
@jfornoff We recently pushed out new ipsec templates so the directions on how to change your subenet have changed.

Please see: http://docs.rancher.com/rancher/v1.3/en/faqs/troubleshooting/#subnet

**Comment by jfornoff** [comment]
Hi Denise, thanks for the heads up! Will try and report back if there's any more problems.

Thanks, Jan

**Comment by asg1612** [comment]
@deniseschannon I upgraded to rancher 1.3 and created a new environment with a custom subnet. It's works!

Thanks!
