### ISSUE TITLE
etcd does not start successfully after powering off the host on which it is running.

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#5103]
**Rancher Version:**: Master

**OS and where are the hosts located? (cloud, bare metal, etc):**: Ubuntu, Cloud

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**: Kubernetes

**Steps to Reproduce:**
1. Create a Kubernetes environment and allow all the system containers to show up successfully
2. Switch off a host on which etcd is running

**Results:** 
The etcd panics does not come up successfully on another host.

```
6/13/2016 4:01:07 PM2016-06-13 23:01:07.626196 E | rafthttp: failed to find member 5d0820f0815a7ae8 in cluster b108023fba99ea85
6/13/2016 4:01:07 PM2016-06-13 23:01:07.634070 E | rafthttp: failed to find member 5d0820f0815a7ae8 in cluster b108023fba99ea85
6/13/2016 4:01:07 PM2016-06-13 23:01:07.679773 E | rafthttp: failed to find member 4a94e9b3cf814b43 in cluster b108023fba99ea85
6/13/2016 4:01:07 PM2016-06-13 23:01:07.684483 I | raft: 499007fe7bb74d98 [term: 0] received a MsgApp message with higher term from 5d0820f0815a7ae8 [term: 2]
6/13/2016 4:01:07 PM2016-06-13 23:01:07.684724 I | raft: 499007fe7bb74d98 became follower at term 2
6/13/2016 4:01:07 PM2016-06-13 23:01:07.685014 I | raft: raft.node: 499007fe7bb74d98 elected leader 5d0820f0815a7ae8 at term 2
6/13/2016 4:01:07 PM2016-06-13 23:01:07.686538 C | raft: tocommit(17617) is out of range [lastIndex(0)]. Was the raft log corrupted, truncated, or lost?
6/13/2016 4:01:07 PMpanic: tocommit(17617) is out of range [lastIndex(0)]. Was the raft log corrupted, truncated, or lost?
6/13/2016 4:01:07 PM
6/13/2016 4:01:07 PMgoroutine 52 [running]:
6/13/2016 4:01:07 PMpanic(0xbeaf00, 0xc820196610)
6/13/2016 4:01:07 PM	/usr/local/go/src/runtime/panic.go:481 +0x3e6
6/13/2016 4:01:07 PMgithub.com/coreos/etcd/Godeps/_workspace/src/github.com/coreos/pkg/capnslog.(*PackageLogger).Panicf(0xc82018a040, 0x10de7a0, 0x5d, 0xc820194740, 0x2, 0x2)
6/13/2016 4:01:07 PM	/home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/coreos/pkg/capnslog/pkg_logger.go:73 +0x191
6/13/2016 4:01:07 PMgithub.com/coreos/etcd/raft.(*raftLog).commitTo(0xc8201988c0, 0x44d1)
6/13/2016 4:01:07 PM	/home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/raft/log.go:194 +0x1a6
6/13/2016 4:01:07 PMgithub.com/coreos/etcd/raft.(*raft).handleHeartbeat(0xc8200ac300, 0x8, 0x499007fe7bb74d98, 0x5d0820f0815a7ae8, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
6/13/2016 4:01:07 PM	/home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/raft/raft.go:771 +0x44
6/13/2016 4:01:07 PMgithub.com/coreos/etcd/raft.stepFollower(0xc8200ac300, 0x8, 0x499007fe7bb74d98, 0x5d0820f0815a7ae8, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
6/13/2016 4:01:07 PM	/home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/raft/raft.go:736 +0x119c
6/13/2016 4:01:07 PMgithub.com/coreos/etcd/raft.(*raft).Step(0xc8200ac300, 0x8, 0x499007fe7bb74d98, 0x5d0820f0815a7ae8, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
6/13/2016 4:01:07 PM	/home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/raft/raft.go:564 +0x3e0
6/13/2016 4:01:07 PMgithub.com/coreos/etcd/raft.(*node).run(0xc820171180, 0xc8200ac300)
6/13/2016 4:01:07 PM	/home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/raft/node.go:310 +0x90e
6/13/2016 4:01:07 PMcreated by github.com/coreos/etcd/raft.RestartNode
6/13/2016 4:01:07 PM	/home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/raft/node.go:215 +0x2e4

```

**Comment by heyitsanthony** [comment]
@soumyalj if this turns out to be an etcd bug would you mind filing this under http://github.com/coreos/etcd/issues along with the version information? Thanks!

**Comment by alena1108** [comment]
@heyitsanthony do you happen to know if this bug exist in any particular version of etcd? If so, we should perhaps switch to using some other version @LLParse

**Comment by heyitsanthony** [comment]
@alena1108 no, this is a new one to me; it appears the etcd data directory is being corrupted in some way.

**Comment by LLParse** [comment]
I do not believe this is an issue with etcd itself. My theory is that our usage of Rancher's `retain_ip: true` feature is giving etcd the impression that the new node is/was the old node, but obviously the raft log for the old node is no longer available. I believe this was missed because not enough legitimate traffic was driven into etcd prior to failure scenario testing.

I hope to prove this theory or arrive at some other conclusion shortly.

**Comment by LLParse** [comment]
Confirmed this is an issue on our side. In a failover scenario, our wrapper script isn't removing the lost etcd node from the cluster. I am working on a fix.

Using `retain_ip: true` allowed a new node to assume the identity of the dead node, which only works if the raft log is empty (brand new cluster).

**Comment by LLParse** [comment]
https://github.com/rancher/catalog-dockerfiles/pull/72
https://github.com/rancher/community-catalog/pull/180
https://github.com/rancher/rancher-catalog/pull/160

**Comment by soumyalj** [comment]
Verfied on v1.1.0-dev5-rc2 with updated catalog https://github.com/rancher/qa-catalog/. After a power off, the etcd container can start on another host.
