### ISSUE TITLE
Can't see host in mobile version

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#5105]
**Rancher Version:** master 6/13

**Steps to Reproduce:**
1.  Go to Host page in mobile version after you have at least one host

**Results:** Can't see or access any host
![image](https://cloud.githubusercontent.com/assets/11514927/16027488/199d0702-318b-11e6-954c-b86bd9bf7d21.png)

**Expected:** Should be able to see them and access their info

**Comment by lvuch** [comment]
https://github.com/rancher/ui/pull/736

**Comment by tfiduccia** [comment]
Version - master 6/16
