### ISSUE TITLE
deploy container with affinity for hosts with one label OR another

### ISSUE THREAD

**Issue by ghost** [rancher/rancher#5110]
**Rancher Version:** 1.0.2

**Docker Version:** 1.11.2

**OS and where are the hosts located? (cloud, bare metal, etc):** RHEL 7 on AWS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** Single node, AWS RDS Aurora DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:** Try to add io.rancher.scheduler.affinity:host_label to deploy a container in hosts with one label **OR** another

**Results:** You cant, the io.rancher.scheduler.affinity:host_label only works with **AND**

**Expected:** The affinity for host_label should have the option to specify **OR** instead of **AND**

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
