### ISSUE TITLE
Container state always "Unhealthy"

### ISSUE THREAD

**Issue by woody3549** [rancher/rancher#5111]
Hello,

I am trying to use a container from existing private Docker repo.
It works fine for the first container but for the second it's always restarting with "Unhealthy" state.
What is that suppose to mean ?
Can you please help me out.

For information, here is my container configuration:
image: @@DOCKER_REPO/videx-enduser:@@DOCKER_TAG
    expose:
     - "3000"
    restart: always
    env_file:
     - ./platform.env
    links:
     - "couchdb:couchdb-enduser"
     - "els:els"
    volumes:
     - "/opt/videx/logs/enduser:/opt/videx/logs"

Thanks

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.1.0-dev4` Cattle: `v0.162.1` UI: `v1.1.4` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`environment.index`|

**Comment by deniseschannon** [comment]
How many hosts do you have in your environment?  If you have more than 1 host, can you exec into one of the network agents on 1 host and ping the IP (10.42.x.x) of another network agent?

Does the container stay in unhealthy or does it ever error out?

**Comment by woody3549** [comment]
Hello,
 
I am using only one host. Running both server and agent on the same host.
When I pull public container images, it works fine.
As soon as I use my own private containers, all are always restarting.
 
Thanks for your help



 
Date: Tue, 14 Jun 2016 15:18:09 -0700

**Comment by deniseschannon** [comment]
What type of private registry is it? Is it a secure or self signed one? 

Have you looked at the docs on registries? http://docs.rancher.com/rancher/latest/en/environments/registries/

**Comment by deniseschannon** [comment]
@woody3549 If you are still facing issues, please re-open.
