### ISSUE TITLE
Can't see menu images when you hover

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#5113]
**Rancher Version:** master 6/14

**Steps to Reproduce:**
1.  Highlight any menu item in light or dark version
![image](https://cloud.githubusercontent.com/assets/11514927/16052589/bddcdb4c-3219-11e6-9f59-0585cfa2c9ff.png)

**Results:** The highlight is a white color and the image also turns a white color, so you can't see the image.  It looks like it dissapears.

**Expected:**  Maybe it should change color like the menu text does.

**Comment by lvuch** [comment]
https://github.com/rancher/ui/pull/771

**Comment by tfiduccia** [comment]
Version - master 7/8
Verified fixed
