### ISSUE TITLE
Cluster manager fails to find correct bridgeIP when using alternative docker bridge IP range (bip)

### ISSUE THREAD

**Issue by CoaxVex** [rancher/rancher#5115]
**Rancher Version:**  1.1.0-dev4 (latest)

**Docker Version:** 1.10.3 (problematic behavior is similar on version 1.11.2)

**OS and where are the hosts located?:** Ubuntu 14/04 + onsite vmware

**Setup Details:** HA rancher

**Environment Type:** Cattle

**Steps to Reproduce:** 

1. Configure docker daemon with the [--bip=cidr option](https://docs.docker.com/engine/userguide/networking/default_network/custom-docker0/) to manually specify the ip range used by dockers default bridge network. (This was necessary for me to avoid a conflict with an existing internal network) For example, put the following in /etc/default/docker and restart docker:

    DOCKER_OPTS="--bip=172.19.10.1/24"

2. Follow [Rancher Documentation on setting up Rancher on multiple nodes](http://docs.rancher.com/rancher/latest/en/installing-rancher/installing-server/multi-nodes/) 

3. Launch the HA script (rancher-ha.sh) and observe output of docker logs -f rancher-ha

**Results:** 

rancher-ha can't get past starting the agent:

    level=info msg="Can not launch agent right now: Server not available at http://172.19.10.2:18080/ping:" component=service

**Expected:**

The URL to ping should be: http://172.19.10.1:18080/ping instead of http://172.19.10.2:18080/ping.

**Why this is happening:**

The [GetBridgeIP function from cluster-manager](https://github.com/rancher/cluster-manager/blob/addcc9f3dadfcc78235142848f3b58f73dcd3436/docker/docker.go#L133) calls the docker API and fetches the Subnet field from IPAM/Config. It then adds one to this network address to determine what is the hosts IP.

Unfortunately, when specifying the --bip option for docker daemon, the "Subnet" is no longer a network address, but the IP specified in --bip. (It is not possible to specify a range, you need to specify the IP address the bridge is to use).

This can be also be witnessed from the output of docker network inspect:
When specifiying --bip:

        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.17.0.1/16",
                    "Gateway": "172.17.0.1"
                }
            ]
        }

With the default configuration:

        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.17.0.0/16"
                }
            ]
        },

**Workaround:** Manually set up the docker bridge using bridge-utils (or OS configuration files) and configure docker daemon with the --bridge= option to use it.

**Proposal for fix:** Perhaps it is a good idea to query the rancher-ha-parent container directly instead of passing through the docker hosts bridge IP, as container IP address can be determined correctly?

**Comment by amachowi** [comment]
I have the same issue here:

/usr/bin/docker daemon --selinux-enabled -H tcp://0.0.0.0:4243 -H unix:///var/run/docker.sock -G dockerroot --bip=192.168.42.1/24 --storage-driver devicemapper --storage-opt dm.fs=xfs --storage-opt dm.thinpooldev=/dev/mapper/VG02-docker--pool --storage-opt dm.use_deferred_removal=true

time="2016-07-27T13:44:41Z" level=info msg="Can not launch agent right now: Server not available at http://192.168.42.2:18080/ping:" component=service
 # curl 192.168.42.1:18080/ping
pong

 A fix for this problem would be appreciated.

**Comment by gifto** [comment]
+1 for fix

**Comment by janeczku** [comment]
Fix will be in v1.2.0-pre2-rc6

**Comment by soumyalj** [comment]
@janeczku : Verified with v1.2.0-pre3-rc1.  As mentioned above, in /etc/default/docker I set 
DOCKER_OPTS="--bip=172.19.10.1/24" and did a docker restart on the hosts. Did not see the issue when running rancher-ha.sh. The HA cluster was set up correctly. I added hosts to the default env and I was able to add services and the docker inspect showed the IP addresses within the allowed range.
```
       "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "3394923709ba21071b7f4dc3a54af951ecce40877710a95009a2bd98527e680a",
                    "EndpointID": "70f21c4c31362db723476e6b2715fc4ce1214fdbed2f78dbea5877a2c500d8c3",
                    "Gateway": "172.19.10.1",
                    "IPAddress": "172.19.10.2",
                    "IPPrefixLen": 24,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:02:1f:ac:9f:58"
                }

```
Is there any other verification required?

**Comment by janeczku** [comment]
@soumyalj Being able to setup HA successfully with ` --bip` option used verified the fix.
