### ISSUE TITLE
No way to remove "Custom" driver information

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#5124]
**Rancher Version:** master 6/14

**Steps to Reproduce:**
1.  Deactivate all drivers except one you added manually
2.  Go to Add Host

**Results:** See Custom & Other available.  If I only want my user to be abel to add machine through my added driver, there is no way to remove the "Custom" option.

**Expected:** Should be a "Custom" driver that I can deactivate in manage machine drivers screen.

**Comment by vincent99** [comment]
For this to be effective there'd have to be an API change that prevents creating registrationTokens if "Custom" is disabled.. hiding the UI just pretends that they users can't add them anymore.

**Comment by tfiduccia** [comment]
Version - master 4/27
Verified fixed
