### ISSUE TITLE
Translation missing for snapshot header.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#5125]
Server version - Build from master

<img width="1243" alt="screen shot 2016-06-14 at 2 29 56 pm" src="https://cloud.githubusercontent.com/assets/4266958/16060437/8f303b9a-323c-11e6-800a-a10a8d4e8a4f.png">

**Comment by vincent99** [comment]
Reload?  They're in http://releases.rancher.com/ui/latest/translations/en-us.json

**Comment by sangeethah** [comment]
This issue is not seen when testing with UI - v1.1.5 .
