### ISSUE TITLE
Allow upgrades to pile up and replace each other until final confirmation

### ISSUE THREAD

**Issue by xaka** [rancher/rancher#5127]
Imagine I have a version v1 of some service. I made a change and now I want to upgrade it. I follow usual procedure, w/o confirmation, and find an issue. Let's say severity doesn't matter to me and I have time for extra changes, or may be I've been running on upgraded version for a while and forgot to confirm, and so I make those extra changes. Now I'm trying to have another upgrade and sure thing it fails due to:

```
Service ... must be state=active or inactive to upgrade, currently: state=upgraded
```

I believe it should be possible (and it seems to be safe enough) to overwrite in-flight upgrade with new one, and finally confirm it. There is an easy workaround for now - rollback or confirm, and apply new upgrade, but I'm too lazy for these extra steps :)

**Comment by deniseschannon** [comment]
Just to confirm, you want to continually upgrade while in an upgraded state due to laziness of not wanting to rollback/confirm and do it again. :) 

I've made it an enhancement.

**Comment by xaka** [comment]
Exactly. You can think of it as continuous upgrading until you finally happy with outcome. Thanks!

**Comment by jhmartin** [comment]
Another way this gets very bad is if an existing service breaks (say, an external dependency changes), and you make a mistake creating the new one. You are then prohibited from upgrading (as you are in a rollback state), and cannot rollback (the old service fails), and cannot even deactivate.  The only way out is to delete the service, and this is a unpalatable for a 'global service'.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
