### ISSUE TITLE
UI Issue with AD restriction page

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#5128]
**Rancher Version:** Master built from Prachi

- [x] Too many different font sizes.  Make headers same size/font as Authentication title text
![image](https://cloud.githubusercontent.com/assets/11514927/16064785/0dac1b58-3259-11e6-9aee-ef8de3f8a736.png)

- [x] When selecting restrict to specific users and groups, the admin should be added automatically.

- [ ] After logging out and logging back in the user's icon image disappear
![image](https://cloud.githubusercontent.com/assets/11514927/16064899/3eebfee4-325a-11e6-9fb9-295b965f0cc3.png)

**Comment by lvuch** [comment]
@tfiduccia is that third bullet still occurring? I can't recreate.

**Comment by tfiduccia** [comment]
Version - master 8/9
Verified fixed
