### ISSUE TITLE
latest tag of rancher/agent on Docker Hub was not updated

### ISSUE THREAD

**Issue by macheins** [rancher/rancher#5130]
It seems that the `latest` tag of the `rancher/agent` repository does not point to the latest version tag (`v1.0.2`). Is there any reason for it, or is it by mistake?

https://hub.docker.com/r/rancher/agent/tags/

**Comment by deniseschannon** [comment]
In each release of Rancher, we actually pin specifically which `rancher/agent` version is compatible with `rancher/server`. We do not expect users to use the `latest` tag for `rancher/agent`.

Also, each release is announced with what version of `rancher/agent` is compatible in the release notes.

**Comment by macheins** [comment]
I am not happy with this answer, because the `rancher/server` has a `stable` and a `latest` tag. For automating `stable` and `latest` deployments it would be very useful to be able to pull the currently matching `rancher/agent`. So, as it is now, a manual lookup step to manually match the versions is needed. Removing this unnecessary step would be very useful.
