### ISSUE TITLE
Add support for Google Container Registry

### ISSUE THREAD

**Issue by Ilya-Kuchaev** [rancher/rancher#5132]
https://cloud.google.com/container-registry/

**Comment by hollingsworthd** [comment]
This works as a custom registry. Create a GCE service account, get the json key Google provides, then add a Custom registry in Racher using the email address connected to the service account, "_json_key" as the user name and the very long json key as the password.

**Comment by areisjunior** [comment]
Hi!
Doesn't works for me! 

@hollingsworthd , Can you explain more detailed, pls?

**Comment by deniseschannon** [comment]
Closing in favor of 6956 due to changes in go-agent.
