### ISSUE TITLE
Environment Name is bleeding into menu text

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#5136]
**Rancher Version:** master 6/15

**Steps to Reproduce:**
1.  have a environment with more than 24 characters

**Results:** Environment name bleeds into menu
![image](https://cloud.githubusercontent.com/assets/11514927/16092824/38ce4370-32ee-11e6-9781-1795d6faa85b.png)

**Expected:**  should not bleed.  Please check namespace as well.

**Comment by lvuch** [comment]
https://github.com/rancher/ui/pull/763

**Comment by tfiduccia** [comment]
Version - master
Verified fixed
