### ISSUE TITLE
"RestoreFromBackup" option should not be shown for backs of volumes that are purged.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#5138]
UI version - v1.1.6

Steps to reproduce the problem:
Create a VM with root and data volumes on longhorn.
Take snapshot of ROOT/DATA volumes.
Take back of this snapshot.

Delete the VM. Delete and purge the root and data volumes.

"RestoreFromBackup" option is shown for backs of volumes that are purged.

<img width="1389" alt="screen shot 2016-06-15 at 1 13 49 pm" src="https://cloud.githubusercontent.com/assets/4266958/16096400/a51c81ae-32fd-11e6-9123-13269a0d4362.png">

**Comment by vincent99** [comment]
n/a to modern versions.
