### ISSUE TITLE
Manual refresh is needed for Revert/Restore options on the snapshot/backups to be shown/hidden correctly.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#5139]
UI version - v1.1.6

Steps to reproduce the problem:

Create a VM service with root and data volumes on longhorn.
Take snapshot of ROOT/DATA volumes.
Take a backup of this snapshot.

Revert/Restore options are not shown for this snapshot as expected.
Stop the VM service.

Go to Infrastructure->Storage->Pools page .
Revert Volume to snapshot/Restore volume from backup options are still not shown for this snapshot.

After a manual refresh , i am able to see Revert Volume to snapshot/Restore volume from backup options for this snapshot.

Now Start the VM service.

Go to Infrastructure->Storage->Pools page .
Revert Volume to snapshot/Restore volume from backup options are still  shown for this snapshot.

This is incorrect. Using these options results in Error - "Validation failed in API:".

After a manual refresh , i am not  able to see Revert Volume to snapshot/Restore volume from backup options for this snapshot which is as expected.

The same behavior is also exhibited for Backups entry in Storage->Backups list view.

**Comment by pwFoo** [comment]
It seems to be a rancher server ui refresh problem at all?

Delete, create or upgrade stacks also need a browser refresh to be finished often.

**Comment by vincent99** [comment]
n/a to modern versions.
