### ISSUE TITLE
Status Field: is being referred to Enabled Field: in UI after Auth

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#5140]
**Rancher Version:** master 6/15

**Steps to Reproduce:**
1.  Authenticate using AD or LDAP

**Results:** In the Authentication section under Users columns, there is a field called "Enabled Field:", this field is called "Status Field:" before you auth.
![image](https://cloud.githubusercontent.com/assets/11514927/16099011/e21e7b72-330a-11e6-8d90-772a565b7a78.png)
![image](https://cloud.githubusercontent.com/assets/11514927/16099021/e99e8996-330a-11e6-8e12-ada86ec9d35f.png)

**Expected:**  Either call both Status Field or Enabled Field

**Comment by westlywright** [comment]
@tfiduccia Looks like it was resolved with commit #413d73b

**Comment by tfiduccia** [comment]
Version - v1.1.0-rc3
Verified fixed
