### ISSUE TITLE
OpenLDAP: Can't log in if restricted mode is set on for LDAP

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#5141]
**Rancher Version:** master 6/15

**Steps to Reproduce:**
1. Authenticate using LDAP
2. Set mode to restricted and add the admin (this should happen automatically, but if not add)
3. Logout and try to log back in

**Results:** Can't log back in
![image](https://cloud.githubusercontent.com/assets/11514927/16099581/de32d280-330d-11e6-9d9b-f8cf2eadd97e.png)

**Expected:** should be able to log in

**Comment:**  In the ldapconfig collection the "allowedIdentities" field is missing.

**Comment by prachidamle** [comment]
This is a missing feature - "accessMode" is not supported for OpenLDAP.

**Comment by prachidamle** [comment]
Moving out after discussing with @will-chan

**Comment by gerardborst** [comment]
@deniseschannon Do you know when this will be implemented in a release candidate?

**Comment by prachidamle** [comment]
@vincent99 We will need SiteAccess UI added to OpenLDAP access control page.
Backend has been implemented to support "accessMode" + "allowedIdentities"

**Comment by will-chan** [comment]
Adding back to 1.5 @deniseschannon request =)

**Comment by tfiduccia** [comment]
Version - master 2/23
Verified fixed
