### ISSUE TITLE
Mobile - All menu items have "Actions" text on each button so it repeats actions three times

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#5142]
**Rancher Version:** Master 5/16

**Steps to Reproduce:**
1.  Add one of each service
2.  Resize your browser to mobile size
3.  go to main stack page
4.  Go to Host page

**Results:** The menus now have the work action on them. 
![image](https://cloud.githubusercontent.com/assets/11514927/16100963/faa765bc-3316-11e6-88d2-c2c4bf655c77.png)
![image](https://cloud.githubusercontent.com/assets/11514927/16100991/3779eed8-3317-11e6-89f8-6ea8491b6697.png)

**Expected:**  remove action text from buttons

**Comment by lvuch** [comment]
https://github.com/rancher/ui/pull/738

**Comment by tfiduccia** [comment]
Version - master 6/16
Verified fixed
