### ISSUE TITLE
too many process at ha cluster

### ISSUE THREAD

**Issue by rmops** [rancher/rancher#5147]
**Rancher Version:**
v1.1.0-dev2-rc4
**Docker Version:**
1.10.3
**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 14.04.4 LTS \n \l
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
find  Too many processes on HA cluster: prancher01,02,03

**Results:** 
318 process like these:
root     29038 21173  0 Jun13 ?        00:00:00 [git-remote-http] <defunct>
root     29133 21173  0 Jun14 ?        00:00:00 [git-remote-http] <defunct>
root     29325 21173  0 Jun13 ?        00:00:00 [git-remote-http] <defunct>
root     29356 21173  0 Jun14 ?        00:00:00 [git-remote-http] <defunct>
root     29540 21173  0 Jun13 ?        00:00:00 [git-remote-http] <defunct>
root     29676 21173  0 Jun14 ?        00:00:00 [git-remote-http] <defunct>
root     29864 21173  0 Jun13 ?        00:00:00 [git-remote-http] <defunct>
root     29886 21173  0 Jun14 ?        00:00:00 [git-remote-http] <defunct>
root     30122 21173  0 Jun13 ?        00:00:00 [git-remote-http] <defunct>
root     30211 21173  0 Jun14 ?        00:00:00 [git-remote-http] <defunct>
root     30229 21173  0 May30 ?        00:00:00 [git-remote-http] <defunct>
root     30407 21173  0 Jun13 ?        00:00:00 [git-remote-http] <defunct>
root     30423 21173  0 Jun14 ?        00:00:00 [git-remote-http] <defunct>
root     30616 21173  0 Jun13 ?        00:00:00 [git-remote-http] <defunct>
root     30708 21173  0 Jun14 ?        00:00:00 [git-remote-http] <defunct>
root     30913 21173  0 Jun13 ?        00:00:00 [git-remote-http] <defunct>
root     30915 21173  0 Jun14 ?        00:00:00 [git-remote-http] <defunct>
root     31164 21173  0 Jun13 ?        00:00:00 [git-remote-http] <defunct>
root     31246 21173  0 Jun14 ?        00:00:00 [git-remote-http] <defunct>
root     31448 21173  0 Jun13 ?        00:00:00 [git-remote-http] <defunct>
root     31463 21173  0 Jun14 ?        00:00:00 [git-remote-http] <defunct>
root     31653 21173  0 Jun13 ?        00:00:00 [git-remote-http] <defunct>
root     31751 21173  0 Jun14 ?        00:00:00 [git-remote-http] <defunct>
root     31938 21173  0 Jun13 ?        00:00:00 [git-remote-http] <defunct>
root     31959 21173  0 Jun14 ?        00:00:00 [git-remote-http] <defunct>
root     32074 21173  0 May26 ?        00:00:00 [git-remote-http] <defunct>
root     32145 21173  0 Jun13 ?        00:00:00 [git-remote-http] <defunct>
root     32253 21173  0 Jun14 ?        00:00:00 [git-remote-http] <defunct>
root     32430 21173  0 Jun13 ?        00:00:00 [git-remote-http] <defunct>
root     32471 21173  0 Jun14 ?        00:00:00 [git-remote-http] <defunct>
root     32632 21173  0 Jun13 ?        00:00:00 [git-remote-http] <defunct>
root     32764 21173  0 Jun14 ?        00:00:00 [git-remote-http] <defunct>

**Expected:**

**Comment by deniseschannon** [comment]
@rmops FYI, we won't usually focus on issues that are filed with releases that are ending with `-rcX` as those are our internal testing release candidates. If you can try to upgrade to a release (either v1.1.0-dev3 or v1.1.0-dev4), that would be ideal. I don't know if your issue would be directly resolved, but it'd be better if it was one that we had already validated.

**Comment by snahelou** [comment]
Same problem here after upgrade to v1.1.0-dev5. I disable catalog and reboot to clear processes. Maybe a proxy problem.

Regards

**Comment by deniseschannon** [comment]
` [git-remote-http]` is related to our catalog service.

**Comment by deniseschannon** [comment]
With the refactoring of processes and HA being refactored, if this is still an issue after v1.2.0, please re-open.
