### ISSUE TITLE
Issues with Cronjob containers on Docker-compose upgrade

### ISSUE THREAD

**Issue by pragmaticivan** [rancher/rancher#5149]
**Rancher Version:**
v1.1.0-dev2-rc4
**OS and where are the hosts located? (cloud, bare metal, etc):**
AWS (Ubuntu)
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node with External DB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
One of the containers of a stack is pretty much to perform Cron Jobs.
The issue is performing `./rancher-compose -p stack-example up -d --upgrade web worker cron`
and `./rancher-compose -p stack-example up -d --upgrade --confirm-upgrade` right after.

I have a cron job that runs every 2 minutes, as you can see when I start deploying something for some reason the contianer with cron job performs that twice, which is impossible since I'm using: 

```
cron:
  scale: 1
redis:
  scale: 1
  upgrade_strategy:
    start_first: true
```

(I'm expecting that when I don't use upgrade_strategy with start_first its false as default.

Here are the logs.

**Results:** 

```
[DEBUG DOCKER ALPHA] Time: (2016-06-16 06:00:15 +0000) - Hostname: a1464018f986
[DEBUG DOCKER ALPHA] Time: (2016-06-16 06:02:09 +0000) - Hostname: a1464018f986
[DEBUG DOCKER ALPHA] Time: (2016-06-16 06:02:09 +0000) - Hostname: a1464018f986
[DEBUG DOCKER ALPHA] Time: (2016-06-16 06:04:09 +0000) - Hostname: a1464018f986
[DEBUG DOCKER ALPHA] Time: (2016-06-16 06:04:09 +0000) - Hostname: a1464018f986
[DEBUG DOCKER ALPHA] Time: (2016-06-16 06:08:07 +0000) - Hostname: cffcf9e5cebe 
[DEBUG DOCKER ALPHA] Time: (2016-06-16 06:10:07 +0000) - Hostname: cffcf9e5cebe
```

**Expected:**
I expect to never have a cronjob being performed twice at the same time, I always have just one contianer.

**Comment by superseb** [comment]
Closing as stale.
