### ISSUE TITLE
X-Forwarded-Port for websocket support

### ISSUE THREAD

**Issue by djcenox** [rancher/rancher#5152]
**Rancher Version: v1.0.2**

**Docker Version: 1.10.3**

**OS and where are the hosts located? bare metal**

**Setup Details: Single node Rancher internal DB**

**Environment Type: Cattle**

**Steps to Reproduce:
1) Have a simple webapp that use WebSocket, and set to use wss:// if over https
2) Set up LB to be ssl terminator for your webapp.
3) Spring WebSocket library try to match origins using forwarded headers, it find out that the request comes from http://demo.example.com:80/webapp
4) It finds the scheme cause haproxy pass the X-Forwarded-Proto
5) Port is 80 get by host so the check fails cause it match something like https://demo.example.com:80/.... 
4) Our backend websocket library returns 403 while validating origin. 

Since the header X-Forwared-Port and X-Forwarded-Host are missing..

Library check prevents untrusted domains to make websocket requests so we don't want to remove Origin header or trust *. 
 

**Results: WebSocket unexpected code 403, but if you add 
http-request set-header X-Forwarded-Port %[dst_port] (in haproxy.conf inside the backend piece)
it works** 

**Expected:**

I'm not really sure is a rancher bug, but i would like to know if there is a way to change the haproyx.cfg.ftl

Thanks

**Comment by djcenox** [comment]
Bump!

**Comment by willseward** [comment]
Agreed.

**Comment by vincent99** [comment]
There is not currently a way to add arbitrary settings to a backend (or anything other than `defaults` and `global`).  See #2179, this is being actively worked on now.

A PR to add `X-Forwarded-Port` to [haproxy.cfg.ftl](https://github.com/rancher/cattle/blob/master/resources/content/config-content/haproxy/content/etc/haproxy/haproxy.cfg.ftl) would seem like a fairly harmless thing to merge in the meantime though.  The `Host` header should be getting passed as-is so I don't think `X-Forwarded-Host` is needed.

**Comment by sangeethah** [comment]
Tested with rancher-server version- v1.2.0-pre1-rc1

When LB is created , we see set-header X-Forwarded-Port being configured in the backend in haproxy.conf

```
backend ff44641c-ae65-4cb5-88a9-c05d4a1cb4dd_8090_0_backend                     
        mode http                                                               
        server c58eac3e-e18d-4861-aa9c-50637bb18ef1 10.42.219.15:80             
        http-request set-header X-Forwarded-Port %[dst_port]       
```

**Comment by sangeethah** [comment]
@djcenox: with version - v1.2.0-pre1-rc1, "http-request set-header X-Forwarded-Port %[dst_port]" is being appended to backend section in haproxy.

Could you confirm, that with this version you are able to use LB services with  webapp using wss.

**Comment by djcenox** [comment]
Yes it's working. Thanks.
