### ISSUE TITLE
AzureAD - Username or Password wrong give unfriendly message

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#5164]
**Rancher Version:** master 6/16

**Steps to Reproduce:**
1.  Setup Azure Auth
2.  Log out
3.  In login screen put garbage in username
4.  In login screen put in good username but bad password

**Results:** Non-200 Response from Azure
![image](https://cloud.githubusercontent.com/assets/11514927/16136022/2159e638-33dc-11e6-9ae3-b26b6a90dbea.png)

**Expected:**  Should say "Username or Password incorrect"

**Comment by vincent99** [comment]
@prachidamle If azure says auth fails the response back to the client should be 401/Unauthorized.

**Comment by prachidamle** [comment]
@vincent99 yup, ofcourse. My bad

**Comment by prachidamle** [comment]
@vincent99 Azure sadly does not provider standard HTTP errors like 401 for unauthorized.
Instead it sends HTTP 400 and a response body like this:

"error=invalid_grant, error_description=AADSTS50034: To sign into this application the account must be added to the ztad.onmicrosoft.com directory.
Trace ID: 04c11d3d-7760-497d-8a97-abc956399dba
Correlation ID: 93167f34-0496-418f-9e37-3bc2d7386384
Timestamp: 2016-06-16 23:44:45Z, error_codes=[50034], timestamp=2016-06-16 23:44:45Z, trace_id=04c11d3d-7760-497d-8a97-abc956399dba, correlation_id=93167f34-0496-418f-9e37-3bc2d7386384}"

And the Azure code AADSTS50034 means User is not registered!

I guess we will have to just log this Azure code and then present 401 to rancher user.

**Comment by vincent99** [comment]
The UI will display "username or password incorrect" if you send back 401, so it doesn't matter what the exact message from MS is.  If you see that error description (or probably the `error=invalid_grant` is a better thing to check), return 401.  If you see any other kind of error, you can return what they said and it will be displayed to the user.

**Comment by prachidamle** [comment]
@vincent99 yeah I am now returning 401, when I see error=invalid_grant.
In other cases I just return the azure error.

**Comment by tfiduccia** [comment]
Version - master 6/16
I'm always seeing the error response from Azure now.  I would still prefer a "Username or Password incorrect" or something.
![image](https://cloud.githubusercontent.com/assets/11514927/16165774/d97b54b8-349a-11e6-926b-405597a2b6fe.png)

**Comment by tfiduccia** [comment]
Version - v1.1.0-rc3
Verified fixed
