### ISSUE TITLE
Static files doesn't show in Grafana dashboard service

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#5165]
**Rancher Version:**
v1.1.0-dev5-rc2
**Docker Version:**
1.10.3
**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 14.04 - cloud
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes
**Steps to Reproduce:**
Run Heapster with influxDB backend and Grafana, i followed the official [example](https://github.com/kubernetes/heapster/blob/master/docs/influxdb.md) 
**Results:** 
Heapster runs normally but when accessing Grafana service the the static files doesn't appear:
```
http://46.101.237.29/api/v1/proxy/namespaces/kube-system/services/monitoring-grafana/public/css/grafana.dark.min.a95b3754.css Failed to load resource: the server responded with a status of 404 (Not Found)

http://46.101.237.29/api/v1/proxy/namespaces/kube-system/services/monitoring-grafana/public/app/app.ca0ab6f9.js Failed to load resource: the server responded with a status of 404 (Not Found)
```
The static files are displayed normally when removing api/v1/proxy/namespaces/kube-system/services/monitoring-grafana from the url
**Expected:**
The Grafana dashboard to show up normally

**Comment by prachidamle** [comment]
@ibuildthecloud Without Grafana UI , is there any other way to validate that heapster is running correctly?

**Comment by galal-hussein** [comment]
@prachidamle @ibuildthecloud I solved this issue by changing the value of grafana controller GF_SERVER_ROOT_URL to 
value: /
instead of 
value: /api/v1/proxy/namespaces/kube-system/services/monitoring-grafana/ 

Grafana dashboard is working now correctly.
