### ISSUE TITLE
Launching a Kubernetes catalog in a specific namespace always goes to default namespace

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#5167]
**Rancher Version:**:v1.1.0-dev5-rc2

**OS and where are the hosts located? (cloud, bare metal, etc):**Ubuntu, Cloud

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**: Kubernetes

**Steps to Reproduce:**
1. Create a Kubernetes setup and a namespace "test"
2. Switch to the namespace "test" and launch a Kubernetes catalog.

**Results:** 
The catalog gets created in the default namespace instead of "test" namespace

**Comment by deniseschannon** [comment]
Verified this is working in v1.1.0-dev5-rc5
