### ISSUE TITLE
Feature request: add-host command and API key generation via command line

### ISSUE THREAD

**Issue by mathuin** [rancher/rancher#5168]
**Rancher Version:** v1.1.0-dev4

**Docker Version:** 1.11.2

**OS and where are the hosts located? (cloud, bare metal, etc):** Ubuntu, bare metal

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single node rancher in VM, single host in additional VM (laptop-as-data-center setup)

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:** Spun up rancher server in VM as per laptop-as-data-center page.  Search for a way to generate that 'add-host' command or API keys from the command line.

**Results:** Can only generate 'add-host' commands and API keys by clicking on the web site.

**Expected:** Ability to generate 'add-host' commands and API keys from rancher server VM's command line.

Before pushing stuff to my production Rancher instance, I test it on a dev instance on a desktop.  I use a script based on the laptop-as-data-center page which creates new VMs for rancher and host1, and does all the configuration -- *except* creating the new 'add host' command and generating API keys.  Both of those tasks can only be done from the website.  If I could do those two things from the CLI, I could put them into my script and automate the testing process.

**Comment by mathuin** [comment]
I have resolved this issue with a bit of scripting.  I can now spin up a new rancher server in a VM, spin up a rancher host in another VM, add the host to the server with the add-host command, and generate API keys for the default environment.  I'm going to close the issue, but if anyone needs help doing this, just ask.

**Comment by drpebcak** [comment]
@mathuin I'm interested in hearing how you solved this.

**Comment by mathuin** [comment]
https://gist.github.com/mathuin/ed0fa5666e4f063b94abb5b1a49d9919

This content is *completely unsupported*.  If it works for you, great.  If it doesn't, you are on your own. :-)
