### ISSUE TITLE
UI should use "isSystem=true" for catalog templates

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#5170]
**Rancher Version:**:v1.1.0-dev5-rc2

**OS and where are the hosts located? (cloud, bare metal, etc):**Ubuntu, Cloud

isSystem=true is supported for Catalog templates which should be used in the UI
https://github.com/rancher/rancher/issues/4648

**Comment by tfiduccia** [comment]
Version - master 8/11
Verified you can add stack when in system menu and it stays there.
