### ISSUE TITLE
Not able to login as github user(member) after an upgrade from v1.0.1 to v1.1.0-dev5-rc2

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#5173]
**Rancher Version:**: v1.1.0-dev5-rc2

**OS and where are the hosts located? (cloud, bare metal, etc):**Ubuntu, Cloud

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**: Cattle

**Steps to Reproduce:**
1. Create a cattle environment with version 1.0.1
2. Enable github user as the owner.
3. Create another environment and give access to user1. Login as user1 in another browser into the new environment.

Upgrade to v1.1.0-dev5-rc2

Results
======
After upgrade we cannot access rancher with user1 credentials

**Comment by prachidamle** [comment]
This was an expected behavior with v1.1.0-dev5-rc2

But since we would have landed in exactly cases like these, the functionality of "required" access Vs "restricted" access was added with following fix:
https://github.com/rancher/rancher/issues/5166

We need to test this scenario again with "rc3".

**Comment by soumyalj** [comment]
Tested with upgrade from v1.1.0-dev4 to v1.1.0-dev5-rc3. Able to login as a github user(member).
[Note: The upgrade from v1.0.1 to v1.1.0-dev5 may not be done by users]
