### ISSUE TITLE
Not able to AWS machine after an upgrade from v1.0.1 to v1.1.0-dev5-rc2

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#5175]
**Rancher Version:**: v1.1.0-dev5-rc2

**OS and where are the hosts located? (cloud, bare metal, etc):**Ubuntu, Cloud

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**: Cattle

**Steps to Reproduce:**
1. Create a cattle environment in v1.0.1. Add AWS hosts to the environment
2. Upgrade to v1.1.0-dev5-rc2
3. Add AWS host again

**Results:** 
Cannot add AWS hosts to the environment:

<img width="275" alt="screen shot 2016-06-16 at 10 18 03 pm" src="https://cloud.githubusercontent.com/assets/18536626/16141409/39afb706-3410-11e6-8d11-6412268e4a6d.png">

**Comment by tfiduccia** [comment]
Amazon only allows for so many machines per region.  The region you are using is out of quota (too many machines in that region).  You will have to use a different region.
