### ISSUE TITLE
English translation missing in deactivate environment

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#5176]
**Rancher Version:** master 6/26

**Steps to Reproduce:**
1.  Click deactivate environment

**Results:** english translations missing
translation not found: locale='en-us', key='modalConfirmDeactiviate.buttons.project.message'.
translation not found: locale='en-us', key='modalConfirmDeactiviate.buttons.project.button'.

![image](https://cloud.githubusercontent.com/assets/11514927/16141994/37c3285a-3416-11e6-900c-c941ccfbaf6d.png)

**Expected:** Should show english translation instead of field names

**Comment by westlywright** [comment]
@tfiduccia can you double check this? I checked out master this morning and am able to see the correct translations 
<img width="782" alt="screenshot 2016-06-17 09 58 11" src="https://cloud.githubusercontent.com/assets/858614/16158460/28bc03e8-3472-11e6-8c73-ab277afd3433.png">

**Comment by vincent99** [comment]
@westlywright For some reason the CI build doesn't ever upload the translation files..  I rebuilt and uploaded locally and they're there now.

**Comment by tfiduccia** [comment]
Version - master 6/17
Verified fixed
