### ISSUE TITLE
Server not available at http://172.17.0.1:18080/ping error

### ISSUE THREAD

**Issue by QkiZMR** [rancher/rancher#5178]
**Rancher Version:**
current stable

**Docker Version:**
1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04, VMware

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher, external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
After deploy rancher like in point 4 on http://docs.rancher.com/rancher/latest/en/installing-rancher/installing-server/multi-nodes/ I generated script for HA. After generating I stop all containers on host. Next run HA script. Load Balancer is already configured. 

**Results:** 
After running container rancher-ha error are appearing:
```
time="2016-06-17T12:20:33Z" level=info msg="Waiting for server to be available" component=cert 
time="2016-06-17T12:20:33Z" level=info msg="Can not launch agent right now: Server not available at http://172.17.0.1:18080/ping:" component=service
```

**Expected:**
Work as is written in docs.

**Comment by QkiZMR** [comment]
ok fixed.

**Comment by ickabrik** [comment]
QkiZMR, How were you able to fix the issue? I am trying to root cause the same message myself.

**Comment by QkiZMR** [comment]
I don't remember because I abandon idea to setup cluster via Rancher. I choose clear Kubernetes solution.
