### ISSUE TITLE
Support Docker 1.12.0

### ISSUE THREAD

**Issue by will-chan** [rancher/rancher#5179]
Add support for Docker Engine 1.12.0.

**Comment by ruimarinho** [comment]
Lots of potential for `HEALTHCHECK` :)

**Comment by techninja1008** [comment]
What's the status of docker 1.12 support?

**Comment by sangeethah** [comment]
Cattle Validation tests run on  rancher server version - v1.2.0-pre4-rc5 using Ubuntu 16.04 hosts with docker version 1.12.2  reported ~97% pass rate with some of the usual known failures which are not specific to docker version 1.12.2. There is 1 issue with test runs taking longer than usual which is tracked in https://github.com/rancher/rancher/issues/6366.

K8s validation test run on Ks8 1.4 and docker version 1.12.2 also pass except for few known failures.
