### ISSUE TITLE
[go-rancher]  double slash chars in catalog service header X-Api-Schemas

### ISSUE THREAD

**Issue by tangfeixiong** [rancher/rancher#5181]
**Rancher Version:** v0.8.3  catalog-service git tag:v0.6.1

**Docker Version:** 1.9.1

**OS and where are the hosts located? (cloud, bare metal, etc):** mac+vbox+vagrant fedora 23

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** 
rancher-catalog-service only, build a standalone image from alpine 3.4. [fork](https://github.com/stackdocker/rancher-catalog-service)

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**Kubernetes

**Steps to Reproduce:**

```
[vagrant@localhost manifests]$ curl -iS http://172.17.4.50:32127
HTTP/1.1 200 OK
Content-Type: application/json
X-Api-Schemas: http://172.17.4.50:32127//schemas
```

**Results:** 

```
diff --git a/api/url.go b/api/url.go
index 65574b3..0e43289 100644
--- a/api/url.go
+++ b/api/url.go
@@ -109,9 +109,7 @@ func (u *urlBuilder) constructBasicUrl(parts ...string) string {
                if part == "" {
                        return ""
                }
-               if raw := buffer.Bytes(); raw[buffer.Len()-1] != byte('/') {
-                    buffer.WriteString("/")
-                }
+               buffer.WriteString("/")
                buffer.WriteString(part)
        }
```

**Expected:**
`X-Api-Schemas: http://172.17.4.50:32127/schemas`

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
