### ISSUE TITLE
Containers not starting when TLS is configured

### ISSUE THREAD

**Issue by Beng89** [rancher/rancher#5182]
**Rancher Version:**
- server: v1.1.0-dev4
- agent: v1.0.1

**Docker Version:**
- 1.11.2

**OS and where are the hosts located? (cloud, bare metal, etc):**
- Red Hat VM

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
- single server node with separate agent node on the same network.

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
- Cattle

**Steps to Reproduce:**
Set up a master and agent following the directions for using a self signed certificate [here](http://docs.rancher.com/rancher/latest/en/installing-rancher/installing-server/basic-ssl-config/)

**Results:** 
Started services/containers stuck at initializing and the rancher server container spams logs similiar to:
``
2016-06-17 17:51:17,028 ERROR [:] [] [] [] [ecutorService-2] [.p.c.v.i.ConfigItemStatusManagerImpl] Failed null, exit code [60] output [INFO: Updating configscripts
INFO: Downloading https://hostname/v1//configcontent//configscripts current=configscripts-1-f0f3fb2e1110b5ada7c441705981f93a480313a324294321cff467f0c3e12319
] 
``

**Expected:**
Containers to start.

**Additional Information:**
- Everything works as expected when not using tls.

**Comment by deniseschannon** [comment]
I had some time to set up a SSL environment but didn't have issues launching containers.

Did a network agent container ever start on one of your hosts? Was this an upgraded setup or a fresh setup?

**Comment by Beng89** [comment]
Hey Denise,

A network agent did start on each of the hosts. 

This was a fresh setup.

I am going to try to deploy with one of the newer Rancher releases in the near future. I will post my results after I do.

**Comment by deniseschannon** [comment]
@Beng89 Please re-open if you have the same issues with a newer Rancher release.
