### ISSUE TITLE
Display labels from image, in addition to container

### ISSUE THREAD

**Issue by bradjones1** [rancher/rancher#5185]
Feature request - display labels from the image, in addition to the existing labels shown for the container. This would be helpful, for instance, in quickly verifying which code version a "latest" image is running (assuming that label was set at build.)

**Comment by deniseschannon** [comment]
When you say label do you actually mean tag?

`ubuntu:14.04.3` and the tag is `14.04.3`?

**Comment by bradjones1** [comment]
Hi @deniseschannon - Actually I mean label. https://docs.docker.com/engine/userguide/labels-custom-metadata/

**Comment by bradjones1** [comment]
This appears to have snuck in at some point? I now see this as a label of kind "User."
