### ISSUE TITLE
Create new cookie part of Stickiness for LB is broken and won't display

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#5187]
**Rancher Version:**Master 6/17

**Steps to Reproduce:**
1.  Open add load balancer screen
2.  Click on Stickiness
3.  Select Create new Cookie

**Results:**  Nothing happens and an error show up in dev tools: ember.prod.js:11745 Uncaught TypeError: Cannot read property 'isHelperInstance' of undefined

**Expected:** Cookie info should show up.

**Comment by deniseschannon** [comment]
Verified with v1.1.0-dev5-rc4 that the cookie info shows up.
