### ISSUE TITLE
Incorrect path to Mesos sandbox being mounted on Docker instances

### ISSUE THREAD

**Issue by bchelli** [rancher/rancher#5188]
**Rancher Version:**
v1.1.0-dev5-rc3 (Can be reproduce with other versions too)

**Docker Version:**
 v1.11.2

**Marathon Version:**
v1.1.1

**OS and where are the hosts located?**
VM on Scaleway.com
Ubuntu 16.04 LTS (4.5.2-docker-2)

**Setup Details:**
Single Rancher Node

**Environment Type:**
Mesos (3 nodes)
2x2.4GHz - 2GB RAM - 50GB SSD

**Steps to Reproduce:**
- Create a Mesos environment through Rancher
- Install the Marathon framework
- Deploy a docker container with fetcher configured (uris / fetch)

``` javascript
  "uris": [
    "https://s3.amazonaws.com/buoyant-dcos/namerd-dcos.yaml"
  ]
```

**Results:** 
On the docker instance on the mount of the Sandbox (`/mnt/mesos/sandbox/`), we should have access to the fetched file but the sandbox folder is empty.

**Debugging:**
By inspecting the docker container we can see where is the sandbox mounted from:

``` javascript
        "Mounts": [
            {
                "Source": "/data/slaves/668d788f-4413-4550-aa6e-8b246ca86b27-S2/frameworks/668d788f-4413-4550-aa6e-8b246ca86b27-0000/executors/namerd.6c882df1-34f3-11e6-8f30-02cf7ece7f7e/runs/7affb60a-0b2a-4f24-8f66-7c900dcf0f00",
                "Destination": "/mnt/mesos/sandbox",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
```
- Source Path: `/data/slaves/668d788f-4413-4550-aa6e-8b246ca86b27-S2/frameworks/668d788f-4413-4550-aa6e-8b246ca86b27-0000/executors/namerd.6c882df1-34f3-11e6-8f30-02cf7ece7f7e/runs/7affb60a-0b2a-4f24-8f66-7c900dcf0f00`
- Actual Path (where I can get the file from): `/var/lib/docker/volumes/bc5cc6fef1e3e17fa44da26b4cc01d78e4574e99e77922471b1919b9bba2e013/_data/slaves/668d788f-4413-4550-aa6e-8b246ca86b27-S2/frameworks/668d788f-4413-4550-aa6e-8b246ca86b27-0000/executors/namerd.6c882df1-34f3-11e6-8f30-02cf7ece7f7e/runs/7affb60a-0b2a-4f24-8f66-7c900dcf0f00`

In one case the base of the path is: `/data` and on the other one it is `/var/lib/docker/volumes/bc5cc6fef1e3e17fa44da26b4cc01d78e4574e99e77922471b1919b9bba2e013/_data`

Thank you

**Comment by bchelli** [comment]
Basically it look like the --work_dir is not properly specified.
http://mesos.apache.org/documentation/latest/sandbox/

Thanks

**Comment by bchelli** [comment]
Hey guys,
Do you think this has something to do with Mesos being containerized?
Thanks,

**Comment by LLParse** [comment]
Hi @bchelli, thanks for bringing this to our attention.

This is a problem related to the containerization of Mesos. For performance, we chose to bind mount the host docker socket into the slave containers instead of running docker inside of docker. We also containerized the data volume using a `-v /data` definition. Consequently, containers launched on our cluster don't have the data directory context necessary for Mesos' fetcher Docker integration to function.

We confirm our findings by inspecting a Mesos slave container's volumes:
`
        "Mounts": [
            {
                "Name": "f94117f9a296f4421562537fbbdd53487f3fbb7d855b177ad71f06a6eec0a969",
                "Source": "/var/lib/docker/volumes/f94117f9a296f4421562537fbbdd53487f3fbb7d855b177ad71f06a6eec0a969/_data",
                "Destination": "/data",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Source": "/var/run/docker.sock",
                "Destination": "/var/run/docker.sock",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
`

The solution is to mount a host directory with the same path as the Mesos slave data volume (`-v /data:/data`). I'll work on getting this fix into an upcoming RC.

**Comment by bchelli** [comment]
Thanks @LLParse

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
