### ISSUE TITLE
Insecure Registry for "other" driver does not get set.

### ISSUE THREAD

**Issue by wlan0** [rancher/rancher#5189]
**Rancher Version:** v1.0.2

**Docker Version:**1.10

**OS and where are the hosts located? (cloud, bare metal, etc):** Cloud

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:**

Just add a host from under the "other" section of the Add host page, and set Insecure registry option to any value.

**Results:** 
Insecure registry is not set in the API/ and does not show up in machine logs

**Expected:**
Insecure registry should be set in the API/ and should show up in machine logs

**Comment by wlan0** [comment]
I tried setting it directly in the API, and it gets set correctly. Its a problem only when done from the UI.

**Comment by westlywright** [comment]
@wlan0 I am seeing the `engineInsecureRegistry` property being passed in the POST call to the API, when viewing the machine in the API I also see `engineInsecureRegistry` set as an array of strings. I rebuilt my test env this morning so the issue seems to be resolved.

**Comment by wlan0** [comment]
thanks @westlywright

**Comment by tfiduccia** [comment]
Version - v1.1.0-rc3
Verified fixed
