### ISSUE TITLE
Kubernetes image pull fails with the qa-catalog 

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#5191]
**Rancher Version:**: v1.1.0-dev5-rc4

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**: Kubernetes

**Steps to Reproduce:**
1. Create a Kubernetes environment with  https://github.com/rancher/qa-catalog/
2. Kubernetes does not start successfully .

Image Pull gives the following error :
Image [rancher/k8s:v1.2.4-fake] failed to pull: Tag v1.2.4-fake not found in repository docker.io/rancher/k8s

**Comment by alena1108** [comment]
please re-test against rc5. rc-4 release didn't include the fix for that.

**Comment by soumyalj** [comment]
Tested with v1.1.0-dev5-rc5.
