### ISSUE TITLE
"Upgrade Available" option shown for a template that does not satisfy minimum version check.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#5192]
Rancher Version: v1.1.0-dev5-rc5
K8 catalog from - https://github.com/rancher/qa-catalog/

Steps to reproduce the problem:
Add catalog "library" with url  https://github.com/rancher/qa-catalog/
Create a kubernetes environment.

Kubernetes environment gets created with the correct template ( image rancher/k8s:v1.2.4-rancher6) .

<img width="1085" alt="screen shot 2016-06-18 at 2 23 32 pm" src="https://cloud.githubusercontent.com/assets/4266958/16173755/55b8158c-3560-11e6-927a-a47449677230.png">

But UI shows "Upgrade Avaialble" option for Kubernetes stack.

<img width="1044" alt="screen shot 2016-06-18 at 2 22 09 pm" src="https://cloud.githubusercontent.com/assets/4266958/16173751/151b521e-3560-11e6-9f82-0bb0cfdb43ec.png">

**Comment by prachidamle** [comment]
@vincent99 I have added the support for the filter for individual template version, to catalog-service

**Comment by tfiduccia** [comment]
Version - 1.1.0-rc3
Verified fixed
