### ISSUE TITLE
Kubernetes stack upgrade is not successful

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#5194]
**Rancher Version:**: v1.1.0-dev5-rc5

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**: Kubernetes

**Steps to Reproduce:**
1. Create a Kubernetes set up of v1.1.0-dev4
2. Create pods/service/rcs
3. Upgrade to v1.1.0-dev5-rc5

**Results:** 
1. Still see only 1 etcd, instead of 3 etcds
2. Old user containers are in stopped state

**Comment by alena1108** [comment]
upgrades are not supported when etcd gets changed. We should support upgrades starting 1.1. I'll provide some diff k8s image to qa-catalog to test

**Comment by alena1108** [comment]
@soumyalj please re-test by creating a fake catalog entry using image alena1108/k8s:v1.2.4-rancher6

**Comment by soumyalj** [comment]
Verified using v1.1.0-dev5, did a Kubernetes stack upgrade using qa-catalog with updated images(library catalog). The upgrade was successful.
