### ISSUE TITLE
Mega Urgent - breaking change in docker 1.12 causes Invalid hostname format

### ISSUE THREAD

**Issue by virtuman** [rancher/rancher#5195]
**Rancher Version:**
1.1.0-dev4

**Docker Version:**
1.12-rc1

**OS and where are the hosts located? (cloud, bare metal, etc):**
CentOS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
multi-node rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
create any container from catalog will cause this error: **invalid hostname format: %s**
https://github.com/docker/docker/blob/6381ed14d13b57873eb985380e52c9ff4fd94b98/integration-cli/docker_cli_run_test.go

**Results:** 
Due to the latest change in docker where hostname is validated again RFC standard - undescore is no longer allowed, but rancher users underscore to generate name for container based on stack_container_1 format by default and it's impossible to fire up new container, it will not be able to active new container
**Invalid hostname format: %s**

**Expected:**
expected to either you "-" instead of "_" or if that is inappropriate then some other character, otherwise cannot use rancher at all

**Comment by thaJeztah** [comment]
Could you open an issue in the Docker issue tracker as well, to discus this? Although validating the hostname may be a good thing, possibly it's too much of a breaking change

**Comment by ibuildthecloud** [comment]
Ah.... this makes me sad.  We will fix accordingly.

**Comment by taktran** [comment]
Is there a workaround for this?

**Comment by deniseschannon** [comment]
@taktran I believe there were some changes made in Docker for 1.12 so that it will no longer break on our side when Docker 1.12 GAs.

**Comment by thaJeztah** [comment]
https://github.com/docker/docker/pull/23740 Was merged, and will be in the next RC (RC4) for docker 1.12

**Comment by taktran** [comment]
So from what I can see in https://github.com/docker/docker/pull/23740, docker 1.12-rc4 will ignore the validation of the hostname, until they release docker v1.24. That means v1.12-rc4 will make rancher work now, but what happens when docker gets to v1.24? What is the plan for hostname naming?

**Comment by thaJeztah** [comment]
@taktran the change in https://github.com/docker/docker/pull/23740 means that Rancher could "pin" the API version to API 1.23 to preserve the old behavior, and switch to 1.24 once the needed changes in Rancher are ready

**Comment by taktran** [comment]
Cool, looks like [rc4 got released](https://github.com/docker/docker/releases/tag/v1.12.0-rc4) and fixes this in the changelog via https://github.com/docker/docker/pull/21641

So what happens now?

**Comment by sangeethah** [comment]
With rancher/server:v1.2.0-pre4-rc2 , instances of services are named as  
env.name + "-" + service.name + "-" + index.
