### ISSUE TITLE
%upgradeBtn.status.notfound% is missing English translation

### ISSUE THREAD

**Issue by frekele** [rancher/rancher#5196]
**Rancher Version:** v1.1.0-dev5

**Cattle Version:** v0.164.1

**User Interface:** v1.1.10

**Rancher Compose:** v0.8.4

**Docker Version:** v1.10.3

**Browser Version:** Google Chrome 51.0.2704.103 m (windows 10)

**OS and where are the hosts located? (cloud, bare metal, etc):** AWS EC2 - Debian 8.5 HVM

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single node rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:** Create Jenkins from catalog.

**Results:** *%upgradeBtn.status.notfound%*

**Expected:** ??? I dont know.

![error](https://cloud.githubusercontent.com/assets/2288215/16176110/37a3f07c-35db-11e6-8ddd-9b09a30a1816.png)

**Comment by deniseschannon** [comment]
We've added in the ability to translate Rancher into different languages, which meant we took every bit of text on the site and made it into a variable that could be replaced by language. 

The English translation is missing for this text.

**Comment by westlywright** [comment]
Issues seems to be resolved locally, @vincent99 you resolved the build issue with translation files not being uploaded correctly?

**Comment by vincent99** [comment]
case-sensitive... `notFound` != `notfound`.

**Comment by tfiduccia** [comment]
Version - 1.1.0-rc3
Verified fixed
