### ISSUE TITLE
Activating containers in batch when launching a service

### ISSUE THREAD

**Issue by ruimarinho** [rancher/rancher#5199]
When adding multiple [Redis Sentinel](http://redis.io/topics/sentinel) containers at once, it is recommended to wait for other Sentinels to already know about the first one before adding the next. This is important to guarantee that majority is only achieved in one side of the network partition.

Would it be possible to schedule a service activation similar to what is currently possible when upgrading? This would allow launching a single Sentinel container (batch=1) every X seconds (e.g. interval=30s) until the scale had been fulfilled.

**Comment by deniseschannon** [comment]
Instead of being catalog specific, I think this is a general enhancement request for when launching services. When it gets added to the cattle side, we could implement a rancher-compose method, which could then be used for catalog entries.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
