### ISSUE TITLE
Rancher events and alerts

### ISSUE THREAD

**Issue by will-chan** [rancher/rancher#52]
Rancher needs to generate events and alerts for integration to notification systems like SMTP, SNMP, etc.:

Events (more TBD):
- Container modify
- Container start
- Container stop
- Container delete
- Host add
- Host remove
- Cluster create
- Cluster delete
- Cluster add host
- Cluster remove host
- Project create
- Project add member/team/org
- Project remove member/team/org
- LB \* actions
- Snapshot \* actions

Alerts (more TBD):
- Container memory capacity threshold
- Container disk capacity threshold
- Container instance unexpected shutdown
- Host unexpected shutdown
- Network agent unexpected shutdown
- Containers added outside of Rancher (i.e. Docker run outside of Rancher API)
- Any Docker creation of resources outside of Rancher that is later imported

Also need to allow users to see a history of webhook event actions.  For example, we should see when a webhook has been activated, for what event/alert, and the HTTP request and response, and whether it succeeded or failed.

**Comment by cloudnautique** [comment]
Based on experience with other tools, we should also have the capability to resend an event when browsing history.

**Comment by fentas** [comment]
would be nice. I do not know If this is valid as "webhook" right away but google cloud uses a simple implementation for their metadata api.

https://cloud.google.com/compute/docs/metadata#waitforchange

Maybe an option not that complicated to implement?

**Comment by mattapperson** [comment]
+1

**Comment by etlweather** [comment]
+1

**Comment by philp** [comment]
+1

**Comment by sshipway** [comment]
+1.  This item came up as a suggestion in a meeting yesterday as a way to integrate Rancher with our existing infrastructure.

For example, we would use the 'Add Host' hook to trigger a call to the F5 Load Balancer API and add the new host to the backing pool, if it has the correct flag set.  Similarly, the 'Remove Host' or 'Modify Host' hooks would be used to maintain this pool.

Another example would be a 'LB Add' and 'LB Remove' event causing creation/deletion of a VIP as required.

The hooks should pass as much information on the relevant object as possible (including the tags) for flexibility, probably as JSON.

The Alert hooks would be useful to link to our Nagios system (or indeed any other system).  While SNMP is ubiquitous, a webhook is far more powerful when you want to identify which monitoring object to route the alert to.

**Comment by philp** [comment]
We were also discussing this in a meeting yesterday. Our use case was to use web hooks for receiving notifications about container activity in our monitoring system. Some simple use case might be:

- Containers unexpectedly shutting down
- Service containers flapping
- Network agents shutting down

Pushing  these kinds of hooks to our activity streams (we currently use Slack) would also be incredibly useful.

**Comment by shakefu** [comment]
+1

**Comment by sshipway** [comment]
Another thought: for security, the webhooks should also be able to pass authentication credentials as well as the json for the objects affected.  If my webhook is maintaining the F5 Pool as hosts are added/removed/modified then I want a bit of verification in there.

**Comment by crunchywelch** [comment]
+1 @will-chan is this in development anywhere, or still just an idea?

**Comment by will-chan** [comment]
We have not started on this yet but we aren't sure this is a must-have feature before we go 1.0 GA.  Again, things could change as we move closer.

**Comment by sshipway** [comment]
FWIW I think that this is a really important one for us; you can't run a system without having monitoring and alerting, and while a certain amount can be done passively ( https://github.com/sshipway/check_rancher ) it is better to have an active notification of issues - hence webhooks.  Having this feature will also do a lot to actively encourage community development of interfaces to other systems and devices.

**Comment by will-chan** [comment]
I have it back as a v1 feature and we will see what can be done.

**Comment by batjko** [comment]
It may be a bit too meta, but perhaps there could be a one-click shortcut added upon installation of rancher server, to add a pre-configured ELK stack service, which rancher then automatically uses for its own logging?

Other than that, I'd love basic Slack and email notifications as well. In a production environment we can't have Systems people watch the rancher UI throughout the day just to be sure not to miss issues.

**Comment by Ilya-Kuchaev** [comment]
+1

**Comment by atrauzzi** [comment]
+1

**Comment by RenzoF** [comment]
+1

**Comment by betawaffle** [comment]
+1 I want to set up notifications for deployments.

**Comment by ebr** [comment]
+1 to webhooks:  Slack, New Relic, CI.... this would be huge

**Comment by egobude** [comment]
+1

**Comment by bilby91** [comment]
+1

**Comment by CoaxVex** [comment]
+1

**Comment by jadsonlourenco** [comment]
+1

**Comment by roflmao** [comment]
+1

**Comment by gowrirajeev** [comment]
+1

**Comment by marcbachmann** [comment]
Please use github reactions for the `+1`
https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments

**Comment by gitnickgit** [comment]
+1

**Comment by qrpike** [comment]
+1

**Comment by wynnfynn** [comment]
+1

**Comment by taketnoi** [comment]
Is there any news on this feature development so far?

**Comment by flaccid** [comment]
+2

**Comment by ibrokethecloud** [comment]
+1

**Comment by igorpejic** [comment]
+3

**Comment by grygoriy** [comment]
any chance this can be implemented?

**Comment by omercnet** [comment]
+1

**Comment by shakefu** [comment]
Any updates from the Devs on this?

Being able to have outbound webhooks for event notifications would allow integration to many platforms via custom HTTP bridges or direct hookups (our case would be for Slack notifications, Datadog, Pagerduty, Sentry, and Sysdig).

As of right now, the only way to get any alerting is to directly monitor containers running on the hosts, which does not provide the same depth of insight or speed of alerting available directly in the Rancher UI, and assumedly in the Rancher Server internal state.

With Rancher-HA being easy and standard in 1.2+, this is the last piece of the puzzle for enterprise ready Rancher for us.

**Comment by VAdamec** [comment]
What about this ? https://github.com/ndelitski/rancher-alarms (I added graphite events and simple Hipchat - https://github.com/VAdamec/rancher-alarms) as for now it's better than nothing at least for me.

**Comment by ket4yii** [comment]
If you add dashboard for alerts with timeline or history, it would be killer feature, really.

**Comment by VAdamec** [comment]
Instead developing own dashboard system with proper logging/eventing we can use standard tools like logstash (or create specific beat) and elastic with kibana.

**Comment by ibrokethecloud** [comment]
I use this https://github.com/ibrokethecloud/rancher-events to stream events and then use logspout to direct them to a greylog.

**Comment by deniseschannon** [comment]
We'll be adding alerting into 2.0 and track the issue here: https://github.com/rancher/rancher/issues/11170

**Comment by marcbachmann** [comment]
Good choice on using prometheus and alertmanager 👏
