### ISSUE TITLE
[rancher-compose] Can't build from source

### ISSUE THREAD

**Issue by dj-hedgehog** [rancher/rancher#5200]
**Rancher Compose Version:** 0.8.4
**OS:** macOS 10.11.6
**GO version:** 1.6.2

**Steps to Reproduce:**

```
git clone https://github.com/rancher/rancher-compose
./scripts/build
```

**Results:** 

```
main.go:8:2: cannot find package "github.com/Sirupsen/logrus" in any of:
	/usr/local/opt/go/libexec/src/github.com/Sirupsen/logrus (from $GOROOT)
	/Users/ali/golang/src/github.com/Sirupsen/logrus (from $GOPATH)
main.go:9:2: cannot find package "github.com/codegangsta/cli" in any of:
	/usr/local/opt/go/libexec/src/github.com/codegangsta/cli (from $GOROOT)
	/Users/ali/golang/src/github.com/codegangsta/cli (from $GOPATH)
main.go:10:2: cannot find package "github.com/docker/libcompose/cli/command" in any of:
	/usr/local/opt/go/libexec/src/github.com/docker/libcompose/cli/command (from $GOROOT)
	/Users/ali/golang/src/github.com/docker/libcompose/cli/command (from $GOPATH)
```

**Expected:**

Building `docker-compose` binary.

Even after installing all required packages but the ones which are already inside the `vendor` folder via `go get` it doesn't consider the packages inside the `vendor` folder.

What am I doing wrong?

**Comment by adrianfalleiro** [comment]
Yes, it looks like the README.md in the rancher-compose repo needs to be updated. 

You should be able to build from source by running `make build`.

**Comment by deniseschannon** [comment]
I've updated the readme accordingly.
