### ISSUE TITLE
(docker 1.12) Add support to docker swarm created by docker engine

### ISSUE THREAD

**Issue by HackerWilson** [rancher/rancher#5201]
With the ability of docker 1.12 to create a swarm cluster by itself and many more features provided, could rancher support directly use swarm cluster created by docker engine itself? [doc](https://github.com/docker/docker/blob/master/docs/swarm/index.md)

**Comment by ruimarinho** [comment]
Would it make sense to eventually deprecate cattle in favor of native docker swarm clustering?

**Comment by biolounge** [comment]
Will Rancher support docker 1.12 with built-in orchestration and DAB in the new release of Rancher? If so, how soon we can expect the next release?

**Comment by bseng** [comment]
If we can model what docker did with swarm cluster and simplify the moving parts needed for a docker cluster (mainly remove the always on mysql instance for cattle and just point to a docker server url) then it will be great

**Comment by ibuildthecloud** [comment]
Rancher will support the new Docker 1.12 swarm mode just the same as we have supported Swarm, Kubernetes, and Mesos environments.  One could make the argument that Cattle should be deprecated in favor of Swarm or Kubernetes.  Only time and users will tell if that is the right direction.  As it stands right now we are making no major changes in the platform except that we will support Docker 1.12 and swarm mode.  Expect to see some features in this area though soon.

**Comment by ibuildthecloud** [comment]
@biolounge DAB is highly experimental right now for us to really do anything with it.  But we will for sure support it as it matures.  As it stands right now it's basically a JSON format of docker-compose YAML but with less fields.  From that perspective it would be trivial to support.  We just need the format to bake a bit.  We have always embraced all things Docker (and containers) and this will be no different.

**Comment by pulberg** [comment]
RE: Swarm (etc) vs. Cattle.  I think it's safe to say that those of us using Cattle didn't choose it accidentally, there were reasons for that decision. I don't really see how Cattle could be deprecated in favor of Swarm, or anything else, it should just be one of the many orchestration options available. We really liked the fact that the orchestration component was built by the same people building Rancher and Rancher OS, this leaves little room for the introduction of massive breaking changes which you could face if you are dependent on a 3rd party orchestration component.

**Comment by bradjones1** [comment]
@pulberg Good explanation, also I have found Cattle to be an acceptable orchestration option for nodes that I do not intend to be part of an HA or other type of production environment (e.g., throwaway CI runners) and more "direct" management of these nodes by Rancher/Cattle is entirely appropriate, without the overhead that comes with some of the other providers.

**Comment by LLParse** [comment]
See https://github.com/LLParse/swarmkit-catalog and observe the readme. Only Docker 1.12.1 is supported

**Comment by LLParse** [comment]
@sangeethah There are 2 scenarios we need to test:
1. Register hosts to an environment and specify CATTLE_AGENT_IP as the Internal IP
2. Register hosts to an environment as usual, provide answer to the `Host Interface Name` question. It must be the interface corresponding to the External IP

Swarm is using the raft protocol behind the scenes for manager communication, so test cases will be very similar. We aren't supporting disaster recovery or backups yet, so just focus on basic resiliency tests:
1. Add 3 hosts, Specify 3 managers, [create a swarm service](https://docs.docker.com/engine/reference/commandline/service_create/), kill a manager host. Wait for containers to reschedule, on another manager host creating/modifying a services should still work. Add a new host to the environment and it should become a manager (UI labels will auto-populate, you can also run `docker node ls` from within a container on manager host)
2. Add 4 hosts, specify 3 managers, create service, kill 1 manager host, create/modify services, wait for worker host to be promoted to manager, create/modify services.
3. Add 5 hosts, specify 5 managers, create service, kill 2 manager hosts, create/modify services, add 2 new hosts and they should become managers, create/modify services.

**Comment by mwaaas** [comment]
@LLParse  Two questions
1. is this fix in this image rancher/server:v1.2.0-pre4-rc2
2. Is the swarm mode going to be a catalog or a separate environment like Kubernets, cattle etc

**Comment by deniseschannon** [comment]
We are moving the container orchestration from a setting in the environment to a choice in our infrastructure catalog and swarm will be available as part of that.

This is still being tested and we do not recommend using any `rc` builds.

**Comment by mwaaas** [comment]
@deniseschannon  thanks for the info

**Comment by Yajo** [comment]
We want to start implementing Rancher from zero today, but want to start using Docker Engine's Swarm mode as soon as it is officially supported... which cluster management engine should we choose today to make the switch as easy as possible in the future?

**Comment by soumyalj** [comment]
Tested with 1.2.0-pre4-rc15. Swarm is supported with only one mode where we register hosts to an environment and specify CATTLE_AGENT_IP as the Internal IP. Creation of swarm cluster was successful and so was creation of services.

**Comment by dexterbt1** [comment]
Sorry, but with this ticket being closed, does this mean swarm mode (docker 1.12+) support landed? Or are you saying it won't be supported?

**Comment by ryanwalls** [comment]
@soumyalj same question. Is this ready now? If not, what is the target release?

**Comment by vincent99** [comment]
When an issue is resolved+closed It's available in the release indicated by the milestone.

The swarm option in 1.2 is the new Docker 1.12 swarmkit.  You need to register hosts with private (RFC 1918) IP addresses instead of public because 1.12 does not support public. 1.13+ do.

**Comment by mwaaas** [comment]
@dexterbt1 @ryanwalls  is supported in this version
