### ISSUE TITLE
[rancher-compose] Unable to specify compose files in other locations from tool?

### ISSUE THREAD

**Issue by Ryuzavi** [rancher/rancher#5202]
**Rancher Version:**

Rancher - `v1.1.0-dev4`
Rancher Compose - `v0.8.3`

**Docker Version:**

`Docker version 1.11.1, build 5604cbe`

**Steps to Reproduce:**

Try to run rancher-compose with the -f and -r flags pointing to their respective docker-compose and rancher-compose files in another location with full filepath

e.g.
`./rancher-compose logs -f blah/docker-compose.yml -r blah/rancher-compose.yml`

**Results:** 

`FATA[0000] flag provided but not defined: -f`

**Expected:**

rancher-compose to read both files and work as expected

**Comment by deniseschannon** [comment]
The command should be `./rancher-compose -f blah/docker-compose.yml -r blah/rancher-compose.yml <command>`. Note that the command should be after the options. 

e.g.
```
./rancher-compose -f blah /docker-compose.yml -r blah/rancher-compose.yml logs
./rancher-compose -f blah /docker-compose.yml -r blah/rancher-compose.yml up
```

**Comment by Ryuzavi** [comment]
Ah before the commands!  Many thanks.
