### ISSUE TITLE
feature: external-lb Ability to specify a F5 bigip pool as the target endpoint instead of virtual server

### ISSUE THREAD

**Issue by ingardm** [rancher/rancher#5203]
**Rancher Version:**

**Docker Version:**

**OS and where are the hosts located? (cloud, bare metal, etc):**

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**

**Results:** 

**Expected:**
A service should be linked to a bigip pool instead of a virtualserver AND pool. This is to support scenarios where there is no default pool for a VIP but traffic is instead routed via irules or policies. Rancher doesn't need to know about the VIP, only the pool in which to place the containers.

**Comment by ingardm** [comment]
Is there any (planned) progress on this issue?

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
