### ISSUE TITLE
Unable to create a Kubernetes environment Ubuntu 14.04LTS Docker 1.10.3 Rancher 1.1.0-dev4

### ISSUE THREAD

**Issue by ltupin** [rancher/rancher#5204]
**Rancher Version:**
1.1.0-dev4

**Docker Version:**
Docker version 1.10.3, build 20f81dd

**OS (same for hosts and Rancher server)**
Ubuntu 14.04.4 LTS trusty
Linux rancher_host_kubernetes_01 4.2.0-27-generic #32~14.04.1-Ubuntu SMP

**Where are the hosts located? (cloud, bare metal, etc):**
VMware VMs on ESXi 5.5.0 Build 2068190 (same for hosts and Rancher server)

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
K8s

**Steps to Reproduce:**
Adding host from Rancher GUI

**Results:** 
Unable to add a hosts to create my first environment K8s.

-Rancher LB (ingress-controller) container in error
-Controller manager, Kubelet and K8s containers are restarting again and again...

**Please notice that everything works good with Mesos, Swarm and Cattle. I have trouble ONLY with Kubernetes environment.**

**Expected:**
K8s env is created

**Logs**
First Rancher agent
[agentlaunchrancher.txt](https://github.com/rancher/rancher/files/323306/agentlaunchrancher.txt)

Rancher Agent
[agentrancher.txt](https://github.com/rancher/rancher/files/323308/agentrancher.txt)

Ingress
[ingress.txt](https://github.com/rancher/rancher/files/323309/ingress.txt)

K8s Agent
[agentk8s.txt](https://github.com/rancher/rancher/files/323310/agentk8s.txt)

**Comment by sangeethah** [comment]
@ltupin: , @vishal-biyani: We have a new version of K8s system template that is not compatible with dev4 release . Could you please upgrade rancher-server to 1.1.0-dev5 release and then update environments "Container Orchestration" to cattle and then back to Kubernetes , so that you get that  K8s system containers  get recreated.

**Comment by ltupin** [comment]
@sangeethah : I use 1.1.0-dev5 and it's working like a charm. 
Many thanks !

If we want to keep the dev4 and use k8s, could you please tell us the right compatible images :

**For rancher 1.1.0-dev5**
rancher/k8s v1.2.4-rancher6
rancher/etcd v2.3.6
rancher/kubectld v0.2.0
rancher/ingress-controller v0.1.3
rancher/kubernetes-agent v0.2.0
rancher/agent v1.0.2
rancher/agent-instance v0.8.1
busybox latest

**For rancher 1.1.0-dev4**
rancher/k8s v???
rancher/etcd v???
rancher/kubectld v???
rancher/ingress-controller v???
rancher/kubernetes-agent v???
rancher/agent v???
rancher/agent-instance v???
busybox latest

**Comment by deniseschannon** [comment]
@ltupin If you have an existing v1.1.0-dev4, you will not be able to create a new k8s environment, as rancher automatically starts up the system-stack images. You will be unable to select which versions of images to select for these system services.

**Comment by ltupin** [comment]
Thanks a lot for this reply @deniseschannon . 
And thanks team for this quick resolution !
