### ISSUE TITLE
Add support for grace period as healthcheck parameter.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#5208]
We encounter - rancher/rancher#5193 for which we would ideally be able to set a graceperiod as healthcheck parameter for etcd containers.

Currently there is no support for grace period for healthcheck -http://docs.aws.amazon.com/sdkfornet1/latest/apidocs/html/P_Amazon_AutoScaling_Model_CreateAutoScalingGroupRequest_HealthCheckGracePeriod.htm

Etcd doesn't respond with successful health checks until the cluster is bootstrapped, so we just need to add a waiting period that is roughly equal to the time it takes Rancher to schedule the containers
Which is about 5s/container, so 30s grace period would be good for a 3-node etcd cluster (k8s)
As it stands, we have 15s from container creation until a health check must succeed, because health checks are sent every 7.5s and we tolerate 2 failures.

**Comment by vincent99** [comment]
How is this different than `initializingTimeout`?

**Comment by LLParse** [comment]
That's a good question, the parameter is [undocumented](http://docs.rancher.com/rancher/v1.0/zh/api/api-resources/instanceHealthCheck/) and there is not a single occurrence of its usage in any catalog, so what does it do?

**Comment by vincent99** [comment]
Pretty much what it sounds like, when a container starts the health state goes to initializing and it sets a limit on how long it can stay there before the healthcheck goes healthy.  If it's exceeded then there container is killed and rescheduded (or according to healthCheckAction).  Ditto for reinitializing.

**Comment by LLParse** [comment]
Thanks for explaining it. So we can calculate initializingTimeout for our desired gracePeriod like this:

```
initializingTimeout = (interval * unhealthyThreshold) + gracePeriod
```

**Comment by LLParse** [comment]
Closing because feature already exists.
