### ISSUE TITLE
rancher-agent not starting on Ubuntu 16.04

### ISSUE THREAD

**Issue by kkeker** [rancher/rancher#5210]
**Rancher Version:** v1.1.0-dev5

**Docker Version:** 1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):** Ubuntu 16.04 LTS (GNU/Linux 4.4.0-22-generic x86_64) Hetzner vServer CX60

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single node

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**
root@sbg-node1 ~ # docker run -d --privileged -v /run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.0.2 http://localhost:8080/v1/scripts/735FD07C0C78FE7436B0:1466452800000:bW9oXYBDJnxOxlcbYR3uePLWdT4
9df797ba6972806641cdcabafdbaec2b2e34362c393adf30ab1590d748bfd717
root@sbg-node1 ~ # docker ps -a
CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS                     PORTS                              NAMES
9df797ba6972        rancher/agent:v1.0.2   "/run.sh http://local"   8 seconds ago       Exited (1) 7 seconds ago                                      loving_northcutt
51f4c9cdccba        rancher/agent          "/run.sh http://local"   11 hours ago        Exited (1) 11 hours ago                                       nostalgic_meitner
461445cef88c        rancher/agent:v1.0.2   "/run.sh http://local"   11 hours ago        Exited (1) 11 hours ago                                       rancher-agent
8e15d6ea333d        rancher/agent:v1.0.2   "/run.sh http://local"   11 hours ago        Exited (1) 11 hours ago                                       nostalgic_ardinghelli
3d27881e8823        rancher/agent:v1.0.2   "/run.sh http://local"   11 hours ago        Exited (1) 11 hours ago                                       nauseous_babbage
973e07766505        rancher/agent:v1.0.2   "/run.sh http://local"   11 hours ago        Exited (1) 11 hours ago                                       hopeful_goldberg
16ad7afd56a7        rancher/agent:v1.0.2   "/run.sh http://local"   11 hours ago        Exited (1) 11 hours ago                                       tender_heisenberg
9b761a444efd        rancher/agent:v1.0.2   "/run.sh http://local"   11 hours ago        Exited (1) 11 hours ago                                       sharp_sammet
2a140f49c8ef        rancher/agent:v1.0.2   "/run.sh http://local"   12 hours ago        Exited (1) 12 hours ago                                       clever_turing
f1fb9d5faec3        rancher/agent:v1.0.2   "/run.sh http://local"   12 hours ago        Exited (1) 12 hours ago                                       pensive_wright
776d43e21e22        rancher/agent:v1.0.2   "/run.sh http://local"   12 hours ago        Exited (1) 12 hours ago                                       suspicious_hoover
3b25bcd3000b        rancher/agent:v1.0.2   "/run.sh http://local"   12 hours ago        Exited (1) 12 hours ago                                       gloomy_banach
9c33cbe079ae        rancher/server         "/usr/bin/s6-svscan /"   12 hours ago        Up 12 hours                3306/tcp, 0.0.0.0:8080->8080/tcp   sharp_kilby
root@sbg-node1 ~ # docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                              NAMES
9c33cbe079ae        rancher/server      "/usr/bin/s6-svscan /"   12 hours ago        Up 12 hours         3306/tcp, 0.0.0.0:8080->8080/tcp   sharp_kilby
**Results:** 
root@sbg-node1 ~ # docker logs 9df797ba6972
Error response from daemon: 400 Bad Request: malformed Host header
**Expected:**

**Notation:**
root@sbg-node1 ~ # cat /etc/issue
Ubuntu 16.04 LTS \n \l

root@sbg-node1 ~ # uname -a
Linux sbg-node1 4.4.0-22-generic #40-Ubuntu SMP Thu May 12 22:03:46 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

root@sbg-node1 ~ # docker info
Containers: 12
 Running: 1
 Paused: 0
 Stopped: 11
Images: 3
Server Version: 1.10.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 48
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.0-22-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.42 GiB
Name: sbg-node1
ID: 3LAN:WI5C:2SII:EC22:WX7K:HXT5:KE2N:JSB6:34ZH:BWDB:J3GO:FWPJ
WARNING: No swap limit support

Docker installed from default Ubuntu repository: debocker - docker-powered package builder for Debian

**Comment by deniseschannon** [comment]
Docker 1.10.3 is not supported on Ubuntu 16.04
https://docs.docker.com/v1.10/engine/installation/linux/ubuntulinux/

If you want to use Ubuntu16.04, you should upgrade to Docker 1.11, which is supported with v1.1.0-dev5.

**Comment by deniseschannon** [comment]
@kkeker Please reopen if you are still facing issues with ubuntu 16.04 and later versions of Docker.
