### ISSUE TITLE
WebGUI bug navigation - Unable to navigate from a specific action

### ISSUE THREAD

**Issue by ltupin** [rancher/rancher#5211]
**Rancher Version:**
1.1.0-dev5

**Docker Version:**
Docker version 1.10.3, build 20f81dd

**OS (same for hosts and Rancher server):**
Ubuntu 14.04.4 LTS trusty
Linux rancher_host_kubernetes_01 4.2.0-27-generic #32~14.04.1-Ubuntu SMP

**Where are the hosts located? (cloud, bare metal, etc):**
VMware VMs on ESXi 5.5.0 Build 2068190 (same for hosts and Rancher server)

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
One of each environment

**Steps to Reproduce:**
From the WebGUI:
1. Click on the K8s environment
2. In KUBERNETES in the top menu click on System
3. Select "View Graph" for the K8s Stack
4. Try to go in another environment

**Results:**
The previous menu to change view show "No actions available" and you can't quit this page. 
If you don't try to go in another env from the k8s View Graph view you won't have the problem.
The only way to quit it is to re-enter the root rancher url server.

**Expected:**
Ability to navigate with the menu.

**Attached file**
A 1 minute video to show you the problem.
[Rancher - 06.21.16.mp4.zip](https://github.com/rancher/rancher/files/325159/Rancher.-.06.21.16.mp4.zip)

**Comment by deniseschannon** [comment]
Reproduced the issue with v1.1.0-dev5.

**Comment by tfiduccia** [comment]
Version - v1.1.0-rc3
