### ISSUE TITLE
Unable to work out how to use azurefile docker volume driver within Rancher

### ISSUE THREAD

**Issue by samattridge** [rancher/rancher#5219]
**Rancher Version:** 1.0.2

**Docker Version:** 1.11.2

**OS and where are the hosts located? (cloud, bare metal, etc):** Ubuntu 14.04 LTS Azure

**Setup Details:** single node rancher, internal DB

**Environment Type:** Cattle

**Steps to Reproduce:** Unable to work out how to use the azurefile docker volume driver within Rancher (https://github.com/Azure/azurefile-dockervolumedriver) or if it is even possible yet.  I've specified the 'azurefile' driver but there doesn't appear to be anywhere to specify driver specific options in order to tell docker to use a particular azure file share.  Normally, in docker cli it would be -o "share=myshare".

**Results:** Can't see anywhere to specify driver specific options when using Volume Driver within Rancher.

**Expected:** Should be able to specify driver specific options when using Volume Driver within Rancher.

**Comment by withinboredom** [comment]
This is a "bad idea" as SMB/CIFS doesn't support case in files. As in `someTHING.txt` and `something.txt` are the same file. This can cause all kinds of subtle havoc. ... not saying this isn't a bug or anything ;)

**Comment by samattridge** [comment]
Thanks for the information! Much appreciated.  However, I would still very much like to know if this is currently possible in Rancher and, if so, how can it be done?

**Comment by cjellick** [comment]
Your assessment is right @samattridge: the UI is lacking the ability to create a volume with options if the driver wasn't deployed by rancher, like convoy-nfs.

The API supports this via a call like:
```
HTTP/1.1 POST /v1/projects/1a5/volumes
Host: 192.168.42.141:8080
Accept: application/json
Content-Type: application/json
Content-Length: 90

{
  "name": "my_vol",
  "driver": "azurefile-dockervolumedriver",
  "driverOpts": {
    "share": "myshare",
  },
}
```
but even that has some usability issues as we don't "where" to put the volume and we might make the wrong choice if you don't have the azure driver running on all hosts.

We'll be revamping our volume support at some point in the future and this should get consideration at that time.

**Comment by deniseschannon** [comment]
Closing in favor of #5522.
