### ISSUE TITLE
feature: Unified logs for a service

### ISSUE THREAD

**Issue by samattridge** [rancher/rancher#5220]
**Rancher Version:**

**Docker Version:**

**OS and where are the hosts located? (cloud, bare metal, etc):**

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**

**Results:** 

**Expected:**
When viewing logs within Rancher, it would be great to have all logs unified for a service instead of having to look at logs for individual containers.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
