### ISSUE TITLE
[rancher-compose] Create a --timeout for `rancher-compose up -d` so that if a service gets stuck, rancher-compose will exit

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#5221]
Currently, if a service is stuck in activating, the cli will never exit out even with `-d`. If there was a timeout, then it could exit rancher-compose CLI.

**Comment by Moeser** [comment]
I'm looking for this too, especially for rancher-compose 'pull' and 'up' commands.  Ideally, rancher-compose would exit with a non-successful exit code if it reached the timeout.
