### ISSUE TITLE
Services cannot be started with "io.rancher.container.hostname_override: container_name" - "invalid hostname format:" error seen.  

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#5222]
Rancher Version: v1.1.0-dev5
Docker version - 1.12.0-rc2

Steps to reproduce the problem:
Create service with  label "io.rancher.container.hostname_override: container_name" . 
Service is stuck in "Activating" state forever.
Container fails to start with  " Error (500 Server Error: Internal Server Error ("invalid hostname format: Default_test3_1")".
This error is very similar to error reported in https://github.com/rancher/rancher/issues/5195.

**Comment by alena1108** [comment]
@sangeethah will get resolved as a part of the fix for https://github.com/rancher/rancher/issues/5195, closing as a duplicate

**Comment by sangeethah** [comment]
Will keep this issue in  open state , to verify this issue once the fix for #5195 is available.

**Comment by sangeethah** [comment]
Closing this issue since this issue is not seen anymore with docker 1.12 .
