### ISSUE TITLE
Deploying a new stack should fetch the most recent version of an image

### ISSUE THREAD

**Issue by lucaspottersky** [rancher/rancher#5223]
**Rancher Version:**
v1.1.0-dev1

**Docker Version:**
Docker version 1.11.1, build 5604cbe

**OS and where are the hosts located? (cloud, bare metal, etc):**
Lubuntu Guest VM

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Running from https://hub.docker.com/r/rancher/server/

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**

1. Deploy a stack using an image (eg: on `docker-compose.yml` use `image: someImage:latest`)
2. Push a new version of the image to the images repository
3. Deploy a new stack using the same `docker-compose.yml`

**Results:** 
Rancher uses the first image version that was available in the 1st deployment.

**Expected:**
Instead, Rancher should pull the newer version of the image that was pushed to the registry.

Maybe related: 
- https://github.com/docker/docker/issues/13331
- https://github.com/docker/docker/issues/4238

**Comment by deniseschannon** [comment]
In your docker-compose.yml, you'll need to make sure that you add in this label

```
service1:
  image: someimage:latest
  labels:
    io.rancher.container.pull_image: always
```

This will ensure that we always pull the image before deploying. Otherwise, it will use the cached images on the host.
