### ISSUE TITLE
store custom data in rancher.yml

### ISSUE THREAD

**Issue by jmls** [rancher/rancher#5224]
**Rancher Version: 1.10.0-dev3**

**Docker Version: 1.10.3**

**OS and where are the hosts located? (cloud, bare metal, etc): ubuntu, AWS**

**Setup Details: single node rancher**

**Environment Type: (Cattle)**

What we want to do was to add custom properties to the config.yml file for a catalog entry to manage extended data about the catalog entry. 

We are using the APIs to get data from catalog and want to be able to have extra properties in our backend solution - but all coming from the catalog.

We have tried to add extra properties to config.yml. The result is that the standard contents of the file do not get shown in the catalog cards. So it looks like adding extra properties breaks the UI.

We have managed to add extra properties to the rancher-compose.yml file - and the ones that Rancher does not look for seem to be ignored. But we have not tested if this breaks lanuched stacks.

We can see extra properties and also extra files that we add to the catalog entry version directory from the API. The problem with this is that this means we can only handle extra stuff on versions of the entries - and not for the actual entry itself.

it would be "nice" to have an official "meta-data" property on the rancher.yml file that is passed along with any api call to the catalog

**Comment by joshwget** [comment]
There's a [metadata key](https://github.com/rancher/rancher-compose/blob/master/rancher/context.go#L72) defined for `rancher-compose.yml` files. I think this is what you're looking for.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
