### ISSUE TITLE
'Error response from daemon: 400 Bad Request: malformed Host header' when trying to connect to server on same host in Ubuntu

### ISSUE THREAD

**Issue by sapslaj** [rancher/rancher#5226]
**Rancher Version:**
v1.1.0-dev5

**Docker Version:**
1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04 Server in a VirtualBox VM with a bridged network adapter

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle v0.164.1

**Steps to Reproduce:**
In a stock Ubuntu 16.04 Server installation, run Rancher server with `sudo docker run -d --restart=always -p 8080:8080 rancher/server`, run the agent by running the command given in the UI (in my case, `sudo docker run -d --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.0.2 https://192.168.20.162:8080/v1/scripts/#{registration_token}`)

**Results:** 
Container exits abruptly. Substituting `-i` for `-d` in the run command produces this output:

```
root@ubuntu-server-16-04:~# docker run -e CATTLE_AGENT_IP="192.168.20.162"  -i --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.0.2 http://192.168.20.162:8080/v1/scripts/3B377F62E57B9AE922F5:1466622000000:oIxQymSyP5xqPetdAZjjgTcPIng
Error response from daemon: 400 Bad Request: malformed Host headerroot@ubuntu-server-16-04:~# 

```

When I enter a shell into the container, I can access 192.168.20.163, but there doesn't seem to be a prompt at all.
```
root@ubuntu-server-16-04:~# docker run -e CATTLE_AGENT_IP="192.168.20.162"  -i --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher --entrypoint=/bin/sh rancher/agent:v1.0.2
curl -ik https://192.168.20.162:8080/v1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6028    0  6028    0     0  73642      0 --:--:-- --:--:-- --:--:-- 74419
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Date: Wed, 22 Jun 2016 20:33:18 GMT
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Server: Jetty(9.2.11.v20150529)
Set-Cookie: PL=rancher;Path=/
Vary: Accept-Encoding, User-Agent
X-Api-Account-Id: 1a1
X-Api-Client-Ip: 172.17.0.1
X-Api-Schemas: https://192.168.20.162:8080/v1/schemas
Transfer-Encoding: chunked

{"id":"v1","type":"apiVersion","links":{"accounts":"https://192.168.20.162:8080/v1/accounts","addOutputsInputs":"https://192.168.20.162:8080/v1/addoutputsinputs","agents":"https://192.168.20.162:8080/v1/agents","amazonec2Configs":"https://192.16...
```

Running `docker version` and docker `info` from the container results in this:

```
docker version
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 4749651
OS/Arch (client): linux/amd64
time="2016-06-22T20:34:01Z" level=fatal msg="Error response from daemon: 400 Bad Request: malformed Host header" 
docker info
time="2016-06-22T20:34:20Z" level=fatal msg="Error response from daemon: 400 Bad Request: malformed Host header" 
```

**Expected:**
Host is added to the Rancher infrastructure.

**Comment by aitorpazos** [comment]
Seems that it has to do with Go version that Docker was compiled with. Check #4500 for more details. A workaround is to run the docker binary released by Docker, not the one packaged by your distribution.

**Comment by RobWin** [comment]
+1.
Would a rancher agent docker image which uses a newer Docker client version help?

**Comment by vincent99** [comment]
That would break compatibility with older versions.  Ubuntu patched it to fix the issue in their package because they don't want to 1.5 in xenial, but it looks like it's still in `-testing`.

**Comment by RobWin** [comment]
What about creating a rancher agent which gives the choice of the Docker version to the user by downloading/installing the Docker client via the run script?

**Comment by deniseschannon** [comment]
With the latest release of Rancher and Docker, this shouldn't be an issue anymore. Please re-open if you are still facing issues.

**Comment by dnadave** [comment]
We started seeing this today on OpenSuSE.  They pushed an update to docker yesterday and that is when we started seeing this same issue.
