### ISSUE TITLE
UI flickering on service upgrade

### ISSUE THREAD

**Issue by mishak87** [rancher/rancher#5231]
**Rancher Version:** 1.0.1

**Browser:** google-chrome 51.0.2704.84 (64-bit) linux (opensuse tumbleweed and ubuntu 16.04)

**Steps to Reproduce:**
* Go to main view `/env/*/apps/stacks`
* Trigger service upgrade
* Expand stack by clicking on plus sign
* Open service detail in main view by clicking on the info icon (second column in stack table).

**Results:** 
Screen will flicker several times during upgrade.

**Expected:**
No flickering.

I first noticed the behaviour when upgrading service with two sidekicks (primary has not changed only one sidekick was upgrading).
I suspect detail is hidden and shown again when service status changes.

**Comment by tfiduccia** [comment]
@mishak87 I was unable to reproduce this issue.  Can you please upgrade to 1.1 and let us know if you are still seeing this issue.

**Comment by mishak87** [comment]
Thanks for trying. :blush: I figured out it was caused by bad support of intel drivers in Google Chrome on Linux.
