### ISSUE TITLE
How to migrate rancher-server to different host?

### ISSUE THREAD

**Issue by dj-hedgehog** [rancher/rancher#5232]
**Rancher Version:** 1.1.0 dev 5
**Docker Version:** 1.11.2
**OS and where are the hosts located? (cloud, bare metal, etc):** bare metal
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single node rancher, internal DB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

I need to migrate rancher-server to a different host without loosing the connection to the other hosts managed by this instance of rancher-server and therefore the stacks. How can I do this?

I did it once by copying the mounted database data and then starting the server on the other host but it wasn't able to connect to the hosts again. I had to re-add them all and upgrade every stack to the new hosts which was a lot of work :(

**Comment by aemneina** [comment]
@dj-hedgehog using an external database would be the best method. Not sure why you had connectivity issues previously, but that sounds more like a network/communication issue. I've managed to separate db's out of the rancher server container without issue. 

The one way you could migrate is if you create an image of your rancher server container, copy it to your desired host, then start it there.

**Comment by deniseschannon** [comment]
@dj-hedgehog Please reopen if you have further questions.
