### ISSUE TITLE
Error adding catalog with a space in the name

### ISSUE THREAD

**Issue by zambon** [rancher/rancher#5234]
**Rancher Version:** 1.0.2

**Docker Version:** 1.11.2

**OS and where are the hosts located? (cloud, bare metal, etc):**
* Ubuntu 16.04 64-bit
* SoftLayer VMs

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

* Single node
* Internal DB
* Behind nginx

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Swarm

**Steps to Reproduce:**

1. Click `Admin` -> `Settings`
2. Click `Add Catalog`
3. Name: `My Catalog` (with a space between `My` and `Catalog`)
4. URL: Valid URL for custom catalog
5. Click `Save`
6. Click `Catalog` -> `My Catalog`

**Results:**

* Template images don't show up
* Click `View Details` -> 400 Error
* Browser console shows 400 errors for `<RANCHER_HOST>/v1-catalog/templates/My%20Catalog:swarm%2A<TEMPLATE_NAME>?image` requests

**Expected:**

None of the above. 😄

**Comment by vincent99** [comment]
This was fixed in 1.1-dev4: https://github.com/rancher/rancher/issues/3124
