### ISSUE TITLE
Rancher and Kubernetes 1.3: enable PetSet support

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#5236]
Once k8s 1.3 is released, we should start leveraging 1.3 features. One of them is PetSet. From the design doc overview [link] (https://github.com/kubernetes/kubernetes/pull/18016) it looks like we have to add changes to rancher internal dns programming to propagate Pod identity records 

@galal-hussein ^^

**Comment by wlan0** [comment]
This requires support for two things - 

 - [x] Network Identity (support added in https://github.com/rancher/cattle/pull/1827)
 - [ ] Sticky Volumes

**Comment by galal-hussein** [comment]
@alena1108 @wlan0 There is a problem when starting Petsets with NFS Persistent Volumes #5607

**Comment by wlan0** [comment]
@galal-hussein Petsets can only work with dynamically provisioned volumes (http://kubernetes.io/docs/user-guide/petset/#alpha-limitations) - NFS does not have a dynamic provisioner.

The volume types with dynamic provisioner are in this doc -  https://github.com/kubernetes/kubernetes/tree/master/examples/experimental/persistent-volume-provisioning


That being said, I just tested PetSet with EBS, on rancher v1.2.0-pre3 and kubernetes from this catalog -  rancher/rancher-catalog@356b24f (Folder number 12). Also, I have updated the docs to show the exact steps for creating Petsets -https://docs.google.com/document/d/1Zzy16IK7vb6dqpGuDumdVBarBu33Fbx1mbhYsDGBx_8/edit

**Comment by wlan0** [comment]
Set cloud provider to aws and tested that EBS works fine.

**Comment by galal-hussein** [comment]
Tested and worked from the PR https://github.com/rancher/infra-catalog/pull/23, and on Rancher master image (21 Oct).
