### ISSUE TITLE
Rancher and Kubernetes 1.3: Cluster Federation (Ubernetes) support

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#5237]
Once k8s 1.3 is released, we should start leveraging 1.3 features. One of them is Ubernetes, or Federated clusters control plane
- [kubernetes blog post on Ubernetes](http://blog.kubernetes.io/2016/03/building-highly-available-applications-using-Kubernetes-new-multi-zone-clusters-a.k.a-Ubernetes-Lite.html)
- [federated services design doc](https://github.com/kubernetes/kubernetes/blob/master/docs/design/)
- [design doc on cluster federation](https://github.com/kubernetes/kubernetes/blob/master/docs/design/federation-phase-1.md)

@galal-hussein ^^

**Comment by alena1108** [comment]
@wlan0 could you link to the "how to set ubernetes on rancher" doc here?

**Comment by wlan0** [comment]
Here are the docs to use Cluster Federation in Rancher
