### ISSUE TITLE
etcd gets recreated on the same host after deleting it 

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#5239]
**Rancher Version:**: v1.1.0-dev5

**OS and where are the hosts located? (cloud, bare metal, etc):** Ubuntu, Cloud

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**: Kubernetes

**Steps to Reproduce:**
1. Create a Kubernetes environment with one host(3 etcds should will start on this host)
2. Add the second host
3. Delete a etcd. 

**Results:** 
 etcd lands up on the same host. It should move to the second host added

**Comment by LLParse** [comment]
This is because the etcd data directory (sidekick) wasn't deleted before deleting the corresponding etcd container. Perhaps we could come up with some automated solution rather than deferring the responsibility to the end user.

**Comment by alena1108** [comment]
Issue is fixed by adding scale policy + put a hard affinity constraint on the service.

**Comment by soumyalj** [comment]
Tested with master. etcd does not get recreated on the same host after deleting it.

**Comment by laszlocph** [comment]
I'm seeing this issue again.
