### ISSUE TITLE
Add Amazon EC2 Host sets wrong CATTLE_AGENT_IP when using private IP

### ISSUE THREAD

**Issue by unki2aut** [rancher/rancher#5241]
**Rancher Version:** v1.0.2

**Docker Version:** 1.11.2

**OS and where are the hosts located? (cloud, bare metal, etc):** Ubuntu 14.04.4 LTS, AWS EC2

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Rancher HA setup with 3 server nodes using AWS RDS

**Environment Type: Cattle**

**Steps to Reproduce:**
Use the UI to add a new Host from Amazon EC2, fill in all required fields and select "Use only private IP address"

**Results:** 
Instance is created correctly and showing in the UI, but it shows the gateway IP. Also `docker inspect rancher-agent` shows `CATTLE_AGENT_IP` is set to the gateway IP. Therefore inter-host communication is not working correctly.

**Expected:**
Agent sets the instances private IP for `CATTLE_AGENT_IP`

**Work around:**
1. log into host over SSH
2. stop rancher agent with `docker stop rancher-agent`
3. go to _Add Host_ and select _Custom_ view in the UI, fill hosts private IP in step 4, copy the generated command from step 5 and run in the shell. After some time the IP is showing correctly in the UI and inter-host communication is working.

**Comment by jclark360** [comment]
Having the exact same issue, inter host communication fails on ec2 hosts due to it getting the gateway ip

**Comment by radu-stefanache** [comment]
:+1: & I have the same issue #5605

**Comment by phedoreanu** [comment]
Create the EC2 instances manually, you also get to specify the ssh key-pair, then ssh in and run:
```sh
docker run \
  -e CATTLE_AGENT_IP="$(ifconfig eth0 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}')"  \
  -d --restart=always --privileged \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v /var/lib/rancher:/var/lib/rancher \
  rancher/agent:v1.0.2 \
  http://<rancher-server>:<rancher-port>/v1/scripts/<token>:<token>:<token>
```

**Comment by prelegalwonder** [comment]
I started to take a look at this but could use some guidance. Would this just be a matter of setting CATTLE_AGENT_IP=$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4) in Rancher UI amazondriver or is this more of a call to the cattle api thing?

**Comment by mwelch-ptc** [comment]
It would be nice to have both options available, however personally, we use the API/CLI for most of these actions so that's where it would be most of use to us. 

If not for this purpose, what does the "use private IP Address" flag in the UI intended to be used for?

**Comment by vincent99** [comment]
All the options in the add host screen map directly to `docker-machine --driver=amazonec2` options:

```
--amazonec2-use-private-address: Use the private IP address for docker-machine, but still create a public IP address.
--amazonec2-private-address-only: Use the private IP address only.
```

**Comment by jrhjr07** [comment]
+1

**Comment by gabordk** [comment]
Seriously guys? I really like Rancher, but this ticket is open for 6 months and not even scheduled to fix, which is ridiculous.
This bug is blocking people use Rancher with AWS provider if your hosts are not public to the internet with a wide open ssh port.
Please fix this.

**Comment by vainkop** [comment]
@vincent99 Actually I'm unable to use an AWS NAT Gateway at all when there's a public ip address assigned to an instance, so without a fix to deploy rancher hosts with private ip only, it's impossible to use some of the AWS functionality & there doesn't seem to be any workaround for that, except using NAT instance instead of NAT Gateway which is a different story.

**Comment by nurtext** [comment]
I totally agree: This should be fixed indeed, because exposing every node to the internet is a really bad idea. Furthermore this is Amazon's statement in terms of auto assigned public IP addresses:

> Requests a public IP address from Amazon's public IP address pool, to make your instance reachable from the Internet. In most cases, the public IP address is associated with the instance until it’s stopped or terminated, after which it’s no longer available for you to use. If you require a persistent public IP address that you can associate and disassociate at will, use an Elastic IP address (EIP) instead. You can allocate your own EIP, and associate it to your instance after launch.

Basically this means: If one of your nodes needs to be stopped (e.g. for maintenance or by mistake) , you will loose the public IP address for that node, making it useless until you modify/reconnect your node by hand.

**Comment by doreplado** [comment]
@vincent99 Do you know if this is addressed with Rancher 2.0? Currently anyone using the custom agent to get around this can't use webhooks to scale.

**Comment by vainkop** [comment]
Actually, it works & here's my setup on AWS, maybe it helps soneone:

VPC has 2 subnets:
1) 172.31.128.0/20 - public
2) 172.31.0.0/20 - private

NAT Gateway is deployed into "public subnet", meaning that this subnet has an Internet Gateway attached to it & routing table in this subnet has Internet Gateway as a gateway for 0.0.0.0/0.

Second private subnet has Nat Gateway as a gateway for 0.0.0.0/0 in it's routing table. Any EC2 instance deployed into it cannot get a public IP.

3 Rancher servers version 1.6.15 are deployed into private subnet & put behind internal classic load balancer with websocket enabled using aws-cli for port 8080.
Rancher server is in HA mode with RDS as it's db.

All other instances/ec2 hosts deployed from rancher ui (default Ubuntu 16.04 + docker 1.13.1) are deployed into private subnet, same as Rancher servers with "Use only private IP address" option enabled (but it doesn't really matter here, as hosts can't get a public ip anyway).

I use network load balancers to direct traffic from outside/internet to the host/ec2 instance & whiich goes to haproxy load balancer & the traffic goes out through NAT Gateway's Elastic IP. Traffic of all ec2 instances in this subnet goes like that of course.

Make sure your firewall/security rules aren't blocking any needed traffic.

**Comment by doreplado** [comment]
@vainkop thanks for sharing! but to say vs saying there's a workaround that requires custom network forwarding are two different things. You've designed your network around this problem. Most of us can't do that.

**Comment by patrick7kelly** [comment]
For anyone experiencing this issue, I'd recommend changing the "Host Registration URL" in the Rancher admin.  Set it to `http://<INSTANCE_PRIVATE_IP>:<PORT>`.

It appears (at least in my case) that when Rancher defaults to the public domain, it uses the public network and ultimately gets the NAT gateway's IP.  When I forced it to use a private IP address, it used the private network and ultimately got the correct private IP of any hosts I added to my environments.

Maybe this is worth documenting - there are quite a few issues related to private subnets that I came across when first researching this issue.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

**Comment by nurtext** [comment]
@deniseschannon Nice way of sitting this out. First let this bug be open for months, then release a new version and mark it as "won't fix". In my opinion this is still a critical one. Even more with currently now way of migrating from 1.6 to 2.0 without rebuilding the whole environment.

**Comment by vincent99** [comment]
We have hundreds of customers and none of them have found this to be a critical issue.  There are workarounds if it affects you, as suggested above or as simple as changing the registration url to something that resolves to an internal IP, or does split DNS and resolves to internal or external depending on the source.  Any automated solution we provide is going to be wrong for some users, and so we are not planning to address it. And most serious users of EC2 end up setting up auto-scaling groups and not using the machine driver at all.

Leaving an issue we're never going to do anything about helps nobody.  And I don't know what this has to do with this issue, but there is never going to be an in-place upgrade to 2.0.

You can have your own opinion but bring personally rude to our employees is  uncalled for and out of line.

**Comment by nurtext** [comment]
> You can have your own opinion but bring personally rude to our employees is uncalled for and out of line.

Never meant to be rude to any of your employees. If I hurt someone's feelings - beg your pardon. But you have to admit that this bug has a long history and many people wanted to have this fixed, but nothing happened in almost 2 years of development. It's kinda frustrating.

> Leaving an issue we're never going to do anything about helps nobody. And I don't know what this has to do with this issue, but there is never going to be an in-place upgrade to 2.0.

It's your own FAQ saying there won't be a upgrade/migrate tool before 2.1 is final.
Source: https://rancher.com/docs/rancher/v2.x/en/faq/

> Upgrading/Migrating
> How would the migration from v1.x to v2.0 work?
> Due to the technical difficulty in transforming a Docker container into a pod running Kubernetes, upgrading will require users to “replay” those workloads from v1.x into new v2.0 environments. We plan to ship with a tool in v2.1 to translate existing Rancher Compose files into Kubernetes YAML files. You will then be able to deploy those workloads on the v2.0 platform.

Just my 2 cents.
