### ISSUE TITLE
Kubernetes dashboard sometimes generates error

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#5244]
**Rancher Version:**
rancher/build-master:v0.20.0
**Docker Version:**
1.11.2
**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes
**Steps to Reproduce:**
by running the following command:
```
kubectl create -f https://rawgit.com/kubernetes/dashboard/master/src/deploy/kubernetes-dashboard.yaml
```

**Results:** 
The dashboard should automatically detect the api server and connect to it, however **sometimes** not always the dashboard pod keeps restarting generating the following error:
```
6/25/2016 12:06:11 AM2016/06/24 21:06:11 Starting HTTP server on port 9090
6/25/2016 12:06:11 AM2016/06/24 21:06:11 Creating API server client for https://10.43.0.1:443
6/25/2016 12:06:11 AM2016/06/24 21:06:11 Error while initializing connection to Kubernetes apiserver. This most likely means that the cluster is misconfigured (e.g., it has invalid apiserver certificates or service accounts configuration) or the --apiserver-host param points to a server that does not exist. Reason: Get https://10.43.0.1:443/version: EOF
```
**Expected:**
The dashboard to be up and running.

**Comment by prachidamle** [comment]
@galal-hussein I cant reproduce this. While you verify the deis workflow, can you test this with that catalog?

https://github.com/prachidamle/my-rancher-catalog

**Comment by galal-hussein** [comment]
@prachidamle I will test and let you know.

**Comment by galal-hussein** [comment]
@prachidamle The test on your catalog resulted in error too:

```
6/28/2016 3:04:36 AMStarting HTTP server on port 9090
6/28/2016 3:04:36 AMCreating API server client for https://10.43.0.1:443
6/28/2016 3:04:36 AMError while initializing connection to Kubernetes apiserver. This most likely means that the cluster is misconfigured (e.g., it has invalid apiserver certificates or service accounts configuration) or the --apiserver-host param points to a server that does not exist. Reason: the server has asked for the client to provide credentials
```

Setup details:

2 DO hosts 4 Gigs each, Docker 1.11.2, Rancher version: build-master:v0.20.0

**Comment by prachidamle** [comment]
@galal-hussein The above error seems to be same one that you got for deis before using a new setup.

Can you re-test this with a new setup, just like the deis?

**Comment by galal-hussein** [comment]
@prachidamle The Dashboard worked with new setup.
