### ISSUE TITLE
Rancher as a CNI plugin for k8s

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#5256]
Today we maintain forked repo for k8s mostly because of the way we integrate with Rancher networking. Related modifications that were done to Kubernetes code make it not eligible for upstreaming.

We should address it by moving all the networking Rancher code to CNI plugin, and provide the plugin as an option on the kubelet start.

**Comment by alena1108** [comment]
you should also be able to use all the standard CNI plugins k8s supports (Flannel, Calico, etc)

**Comment by cuiyz** [comment]
@alena1108 Hi Alena, do you have any tech diagrams that can explain the theory may be?

**Comment by alena1108** [comment]
@leodotcloud could you help @cuiyz and share any network diagram/docs explaining how CNI stuff works?

**Comment by leodotcloud** [comment]
@cuiyz here are some pointers:
- https://github.com/containernetworking/cni/blob/master/SPEC.md
- https://github.com/containernetworking/cni/tree/master/Documentation
- http://kubernetes.io/docs/admin/network-plugins/
- http://www.slideshare.net/kubecon/container-network-interface-network-plugins-for-kubernetes-and-beyond

Most of the information is available in the github repository: https://github.com/containernetworking/cni

**Comment by cuiyz** [comment]
Thanks a lot guys @alena1108 @leodotcloud 👍

**Comment by leodotcloud** [comment]
For 1.2 we will support Calico as one of the networking CNI plugin options along with Rancher. In the following release we plan to bring in Weave too after development/testing.

**Comment by pengjiang80** [comment]
@leodotcloud , may I know when we will have Calico available? Currently in both qa/1.2 branch of infra catalog, didn't see any Calico related items.

**Comment by mpaluru** [comment]
@pengjiang80 the infra changes are still cooking and once those are merged, I will start testing Calico. Once everything is working, will push to Infra Catalog. Just a few more days ...

**Comment by leodotcloud** [comment]
@pengjiang80 the infra changes are still cooking and once those are merged, I will start testing Calico. Once everything is working, will push to Infra Catalog. Just a few more days ...

**Comment by deniseschannon** [comment]
Closing as this has been added into Master. Any bugs related to networking in k8s will be filed separately.

**Comment by electrical** [comment]
Sorry for responding to this old issue. I'm running Rancher 1.2 but i'm unable to find any information to enable calico. Could someone point me in the right direction?

**Comment by leodotcloud** [comment]
@electrical Calico will be available once we are done thorough testing, that's why it's not visible yet.

**Comment by PhilipSchmid** [comment]
Hi there,

Are you still testing this one? Unfortunately the existance of CNI support for Rancher with a Kubernetes backend is a must criteria for our deployment. Otherwise Rancher can't fullfill our networking requirements with just IPsec tunnels.

Is there currently any way to run another networking CNI instead of IPsec using the Rancher Kubernetes setup?

Thanks!

Regards,
Philip

**Comment by leodotcloud** [comment]
@PhilipSchmid I have done some testing and Calico integrates well with Rancher. Here is the catalog item that I had used. https://github.com/leodotcloud/test-calico-catalog-item

The only issue that I ran into was exposing the port on the hosts. There were some conflicts with the iptables rules.

I have tested the above with "Cattle" but not with Kubernetes yet. May be a few more tweaks might be needed to run with Kubernetes.

**Comment by meggarr** [comment]
I have deployed one k8s cluster using Rancher, can I know when I can use calico or weave with Kubennetes ? Thanks!

**Comment by DarkBlaez** [comment]
I've been following this thread , it goes all the way back to June 2016 and yet not one dev has posted a response to emphatically answer the question. So I will restate this and look for a solid response. Using Rancher to deploy a Kubernetes cluster, what method is supported for deploying Calico as the CNI? Is there a production ready template? Has the issue with the port exposure been addressed? Without the port exposure and resolution of the conflict with iptable rules, this is about useless.

DB

**Comment by hqzhang** [comment]
@leodotcloud:  have a successful case of rancher k8s  with external network plugin??

**Comment by liFeixiang** [comment]
@leodotcloud 
any update on this? is it possible to use other other plugin on Rancher2.0?

**Comment by leodotcloud** [comment]
@liFeixiang Yes, currently Rancher 2.0 supports Flannel, Calico and Canal out of the box.
