### ISSUE TITLE
Error provisioning SoftLayer hosts

### ISSUE THREAD

**Issue by zambon** [rancher/rancher#5257]
**Rancher Version:** 1.1.0-rc1

**Docker Version:** Fails to install.

**OS and where are the hosts located? (cloud, bare metal, etc):**

* Ubuntu 16.04 64-bit
* SoftLayer - Virtual machines

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

* Single node rancher
* External database
* Single host (proxy + rancher + db in a Docker Compose file)

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:**

1. Click `Admin` -> `Machine Drivers`
1. Activate `softlayer`
1. Click `Infrastructure` -> `Hosts`
1. Click `Add Host`
1. Using `Other`/`softlayer`, provision 1 node

**Results:** 

Host provisioning fails in the `Installing Docker...` phase.

```
time="2016-06-27T21:02:09Z" level=info msg="stdout: Installing Docker..." resourceId: =1ph9
time="2016-06-27T21:04:34Z" level=info msg="stdout: The default lines below are for a sh/bash shell, you can specify the shell you're using, with the --shell flag." resourceId: =1ph9
time="2016-06-27T21:04:34Z" level=info msg="stdout: " resourceId: =1ph9
time="2016-06-27T21:04:34Z" level=info msg="stderr: Error creating machine: Error running provisioning: error installing docker: " resourceId=1ph9
time="2016-06-27T21:04:34Z" level=info msg="stderr: " resourceId=1ph9
```

**Expected:**

Host are provisioned successfully.

**Note:**

I believe this is a bug in Rancher for 2 reasons:
1) I can successfully provision VMs using `docker-machine create --driver "softlayer"` directly with the same parameters;
2) I can successfully add SoftLayer hosts using Rancher v1.0.2.

**Comment by deniseschannon** [comment]
Just to confirm, you were able to provision using `docker-machine` using the same parameters that you found in the rancher/server logs for when we add a host, right?

What version of docker-machine did you use?

**Comment by zambon** [comment]
That's correct! I used `0.8.0-rc1, build fffa6c9`, but I have used earlier versions too.

Let me know if you would like me to test any specific versions.

**Comment by deniseschannon** [comment]
@zambon In Rancher, we are currently at docker-machine v0.6.0. Have you tested specifically with that version?

**Comment by zambon** [comment]
@deniseschannon Please correct me if I'm wrong, but I was checking the repositories and it looks like both v1.0.2 and v1.1.0 user Docker Compose 0.7.0, don't they?

Either way, I've just tested Docker Machine 0.6.0 and 0.7.0; they both worked!

**Comment by zambon** [comment]
That worked @deniseschannon!
