### ISSUE TITLE
Docker error: Failed to get logging factory: logger: no log driver named 'none' is registered

### ISSUE THREAD

**Issue by makhnmik** [rancher/rancher#5260]
**Rancher Version:** v1.1.0-dev5

**Docker Version:** 1.11.2, build b9f10c9

**OS and where are the hosts located? (cloud, bare metal, etc):** Ubuntu 14.04, Amazon EC2 

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single node external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:** Setup log driver as none in rancher web Gui

**Results:**  massive spam in /var/log/upstart/docker.log with

time="2016-06-28T10:48:30.591892935Z" level=error msg="Handler for GET /containers/9fae260900f1/logs returned error: Failed to get logging factory: logger: no log driver named 'none' is registered"

**Expected:** nothing

**Comment by deniseschannon** [comment]
I'm unable to reproduce on v1.1.0. 

Can you share your docker-compose.yml for the service that causes this?

In the stack, you can look at the configuration of all the services using "View Config" at the stack level options.

**Comment by deniseschannon** [comment]
@makhnmik If you are able to reproduce with our later versions and provide the information above for me, please reopen.
