### ISSUE TITLE
Automate validation of templates from built in catalog.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#5263]
Automate validation of templates from built in catalog.
We need to make sure that we are able to deploy all templates from built in library .
Stack and all services within the stack should get to "Active" state minimally.

There is 1 existing PR that has test cases relating to nfs-catalog and gluster-fs workflows-https://github.com/rancher/validation-tests/pull/173

**Comment by galal-hussein** [comment]
@sangeethah I added the pull request https://github.com/rancher/validation-tests/pull/195 which will add several catalog items, there are several failing tests including:

- owncloud
- gitlab

**Comment by galal-hussein** [comment]
Here are the results of manually testing the catalog items:

#### Working catalogs

- [x] wordpress
- [x] zookeeper
- [x] kafka
- [x] asciinema
- [x] consul
- [x] consul_registrator
- [x] Concrete5
- [x] datadog
- [x] Drone CI server
- [x] Drone Rancher Node Manager
- [x] ecr
- [x] elasticsearch
- [x] elasticsearch 2.x
- [x] logstash
- [x] kibana
- [x] Logspout
- [x] etcd
- [x] fbctf
- [x] ghost
- [x] gocd-server
- [x] gocd-agent
- [x] gogs
- [x] grafana
- [x] hadoop + yarn
- [x] janitor
- [x] jenkins
- [x] jenkins_swarm
- [x] letsencrypt
- [x] Liferay
- [x] galera
- [x] minecraft
- [x] mongodb
- [x] nuxeo platform
- [x] odoo
- [x] openvpn basic authentication
- [x] openvpn basic authentication digest
- [x] openvpn rancher local
- [x] openvpn ldap
- [x] owncloud
- [x] pxc
- [x] adminer
- [x] puppet standalone
- [x] promethus
- [x] rabbit-mq
- [x] rancher_bench_security
- [x] sentry
- [x] sematext
- [x] sysdig
- [x] sysdig cloud
- [x] weavescope
- [x] wekan
- [x] rocketchat
- [x] xpilot

#### Failing Items

- [ ] Traefik https://github.com/rancher/community-catalog/issues/240
- [ ] taiga https://github.com/rancher/community-catalog/issues/202
- [ ] gitlab https://github.com/rancher/community-catalog/issues/239
- [ ] alfresco https://github.com/rancher/community-catalog/issues/238

#### Couldn't test for them

- [ ] ScaleIO NAS/DAS Store
- [ ] F5 LB
- [ ] cloudflare dns
- [ ] dns update
- [ ] dnsimple dns
- [ ] pointhq dns
- [ ] powerdns external
- [ ] registry https://github.com/rancher/community-catalog/issues/195
- [ ] registry-convoy https://github.com/rancher/community-catalog/issues/193
- [ ] rexray plugin
