### ISSUE TITLE
Rewrite python-agent to Go

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#5266]

**Comment by sangeethah** [comment]
With rancher-server version - v1.2.0-pre4-rc2 ,  rancher/agent:v1.1.0-rc1 starts a go service .
```
root@sangeetest1-10acre-3:/home/sangeethahariharan1# ps -eaf | grep agent
root     12192 12127  0 16:56 ?        00:00:36 /var/lib/cattle/pyagent/agent
```
Issue that are seen when testing with the go agent service is logged as separate issues.
Following are the issues seen so far:

https://github.com/rancher/rancher/issues/6173
https://github.com/rancher/rancher/issues/6174
https://github.com/rancher/rancher/issues/6189
https://github.com/rancher/rancher/issues/6191
