### ISSUE TITLE
CNI framework for Rancher (k8s and mesos should also work)

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#5267]

**Comment by nathan2013** [comment]
just want to know if have plans for CNM?

**Comment by deniseschannon** [comment]
With the latest master, the CNI framework has been added in.

**Comment by deniseschannon** [comment]
@sangeethah We should file all new bugs related to CNI in separate bugs. If you're okay with that, we can close the feature to confirm that the framework has been merged into master.
