### ISSUE TITLE
Node labels propagation from Rancher cloud provider to k8s

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#5269]
When labels are set on the host in Rancher, corresponding node in kubernetes should reflect that. 

@wlan0 You might need to check this k8s discussion on a topic to see the best way of implementing it: 

https://github.com/kubernetes/kubernetes/issues/9044

**Comment by sangeethah** [comment]
Tested with Rancher server version - v1.2.0-pre1-rc1 and k8s templates - rancher/k8s:v1.3.0-rancher1

Labels set on hosts from rancher-server UI, gets propagated to corresponding node in kubernetes.
Any updates done to the lables (edit/deletes) are also propagated.
But there is a significant delay in propagating the node labels to k8s which is tracked in - https://github.com/rancher/rancher/issues/5493

**Comment by jbarrajon** [comment]
I'm having this issue in rancher server v1.1.3 with a k8s environment v1.2.4
Could this fix be merged in the v1.1.4 release? thanks
