### ISSUE TITLE
Performance Improvements to Rancher

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#5272]
- [x] metadata
- [x] dns
- [x] api
- [x] event publishing

**Comment by Moeser** [comment]
Any way we can get some of the performance improvements in a minor release to 1.1.0?  We upgraded to 1.1.0 from 1.1.0-dev1 hoping to fix our UI and API performance issues, and they got worse instead of improving.

**Comment by deniseschannon** [comment]
https://github.com/rancher/rancher/issues/4580

**Comment by rawmind0** [comment]
Version 1.2 will come with so many changes to get performance improvements. It would be released end of this month...

Please, be a little bit patience... :)
