### ISSUE TITLE
Parameterized FQDN support

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#5273]
Today we hardcode the way we do fqdn generation in external-dns. It always comes in a format of:

```
serviceName.stackName.envrionmentName.rootDomain
```

there are use cases when it needs to be parameterized. We should allow:

* arbitrary separator
* hardcoded values for fqdn parts
* metadata keys

more on the format can be found in discussion to this PR: https://github.com/rancher/external-dns/pull/41

@janeczku @vincent99

**Comment by janeczku** [comment]
https://github.com/rancher/external-dns/pull/47

**Comment by janeczku** [comment]
To validate:

1. Deploy Route 53 v0.6.0 stack from `rancher/rancher-catalog:qa` specifying a custom name template using placeholders and static text (see README of the template).
2. Check that the records get created with the expected names

**Comment by galal-hussein** [comment]
@janeczku I validated this upgrade on master image (24 Oct) using the test cases you specified in the PR and it worked as expected.
