### ISSUE TITLE
If more then 4 services, can't changed environments from graph view

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#5274]
**Rancher Version:** v1.1.0-rc3

**Steps to Reproduce:**
1.  Create a stack
2.  Add two services, link service2 to service1
3.  Add a External service and a Load Balancer (link the LB to service1)
4.  Click on stack name to go to stack detail's page
5.  Click on graph icon
6.  Try to change environments

**Results:** Graph view gets messed up and doesn't move to new environment.  Error in dev console - create-edge-paths.js:130 Uncaught TypeError: Cannot read property 'length' of undefined

**Expected:** switch to environment I selected

**Comment by westlywright** [comment]
@tfiduccia can you check this out again, i followed the steps on a new build (latest master) today and was not able to reproduce the problem. Thanks!

**Comment by tfiduccia** [comment]
Can reproduce in v1.1.0

docker-compose.yml
service1:
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: ubuntu:14.04.3
  stdin_open: true
lb1:
  ports:
  - 80:80
  tty: true
  image: rancher/load-balancer-service
  links:
  - service1:service1
  stdin_open: true
service2:
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: ubuntu:14.04.3
  links:
  - 'service1:'
  stdin_open: true
es1:
  image: rancher/external-service

rancher-compose.yml
service1:
  scale: 1
lb1:
  scale: 1
  load_balancer_config:
    haproxy_config: {}
  health_check:
    port: 42
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000
service2:
  scale: 1
es1:
  external_ips:
  - 1.1.1.1

**Comment by tfiduccia** [comment]
Version - master 7/12
Verified fixed
