### ISSUE TITLE
Assert expectations on health check response

### ISSUE THREAD

**Issue by ruimarinho** [rancher/rancher#5275]
Currently, health checks only take into account the status code (2xx or 3xx) when configured for HTTP or if the port is open for TCP connections.

Would it be possible to consider asserting expectations on the health check response?  Since the health check is based on haproxy, this could roughly translate into `tcp-check expect string`?

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
