### ISSUE TITLE
Crash when trying to start a container with devices

### ISSUE THREAD

**Issue by cpwais** [rancher/rancher#5279]
I'm trying to make [nvidia-docker](https://github.com/NVIDIA/nvidia-docker) work with Rancher.  One workaround to make Rancher start a container w/out using the `nvidia-docker` executable is to just specify the devices and volumes needed to make things work, as described here: https://github.com/NVIDIA/nvidia-docker/wiki/nvidia-docker-plugin ( `docker run -ti `curl -s http://localhost:3476/v1.0/docker/cli?dev=0\&vol=nvidia_driver` nvidia/cuda`)

So, e.g. my devices entries are:
- /dev/nvidiactl -> /dev/nvidiactl

and so on.  For me, that `curl` results in the string `--volume-driver=nvidia-docker --volume=nvidia_driver_352.63:/usr/local/nvidia:ro --device=/dev/nvidiactl --device=/dev/nvidia-uvm --device=/dev/nvidia0`

So I created a standalone container in Rancher, but specifying devices under the `Device Binding` tab appears to cause a crash in the Rancher agent:

```
Traceback (most recent call last):
  File "/var/lib/cattle/pyagent/cattle/agent/event.py", line 95, in _worker_main
    resp = agent.execute(req)
  File "/var/lib/cattle/pyagent/cattle/agent/__init__.py", line 15, in execute
    return self._router.route(req)
  File "/var/lib/cattle/pyagent/cattle/plugins/core/event_router.py", line 13, in route
    resp = handler.execute(req)
  File "/var/lib/cattle/pyagent/cattle/agent/handler.py", line 34, in execute
    return method(req=req, **req.data.__dict__)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 529, in instance_activate
    self._do_instance_activate(instance, host, progress)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 600, in _do_instance_activate
    self._setup_device_options(create_config['host_config'], instance)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 781, in _setup_device_options
    for dev, options in device_options.iteritems():
AttributeError: 'NoneType' object has no attribute 'iteritems'
```

 I went into the container and added a simple `None` check to avoid the crash and the container launched just fine.  (i.e. set `device_options` to `{}` if it's `None`).  So this looks like a simple python bug that hopefully can get patched up easily.  

**Rancher Version:**
rancher/agent:v1.0.2

**Docker Version:**
Docker version 1.9.1, build a34a1d5

**OS and where are the hosts located? (cloud, bare metal, etc):**
bare metal,  Ubuntu 14.04.4 LTS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
cattle

**Steps to Reproduce:**
Create a container with devices under the `Device Binding` tab (as described above).

**Results:** 
Container crashes due to stack trace cited.

**Expected:**
Container should start (as it does when the agent code is patched and agent container restarted).

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
