### ISSUE TITLE
Active Directory setup fails if Default Domain is specified

### ISSUE THREAD

**Issue by felixbuenemann** [rancher/rancher#5280]
Setting up Active Directory in Rancher in v1.1.0-dev5 fails, if the field Default Domain is specified.

The Web UI displays the Error : "Could not talk to ldap"

If the Default Domain is left blank and instead MY-DOMAIN\username is used as the test user, the setup completes. This works but requires each user to login using MY-DOMAIN\username instead of username.

I tried setting Default Domain to the correct MY-DOMAIN and also tried with my-domain. I also tried with the DNS name my-domain.net, which changed the error message to "Unauthorized".

Here's the generated output from the cattle-debug.log:

```
[io.cattle.platform.pool.PoolConfig  ] Setting Pool [ldap.context.pool] property [jmxNameBase=org.apache.commons.pool2:type=GenericObjectPool,name=]
[io.cattle.platform.pool.PoolConfig  ] Setting Pool [ldap.context.pool] property [jmxNamePrefix=ldap.context.pool]
[io.cattle.platform.pool.PoolConfig  ] Setting Pool [ldap.context.pool] property [maxIdle=50]
[io.cattle.platform.pool.PoolConfig  ] Setting Pool [ldap.context.pool] property [maxTotal=1000]
[io.cattle.platform.pool.PoolConfig  ] Setting Pool [ldap.context.pool] property [maxWaitMillis=1000]
[io.cattle.platform.pool.PoolConfig  ] Setting Pool [ldap.context.pool] property [minEvictableIdleTimeMillis=300000]
[io.cattle.platform.pool.PoolConfig  ] Setting Pool [ldap.context.pool] property [testOnBorrow=true]
[io.cattle.platform.pool.PoolConfig  ] Setting Pool [ldap.context.pool] property [testWhileIdle=true]
[io.cattle.platform.pool.PoolConfig  ] Setting Pool [ldap.context.pool] property [timeBetweenEvictionRunsMillis=60000]
[.i.l.a.LdapServiceContextPoolFactory] Failed to create a service context.
[.i.l.a.LdapServiceContextPoolFactory] [LDAP: error code 49 - 80090308: LdapErr: DSID-0C0903A9, comment: AcceptSecurityContext error, data 52e, v1db1]
```

According to the ActiveDirectory docs LDAP error 49 with data 52e means wrong credentials.

My setup is:
- Ubuntu Xenial Docker Host on Digital Ocean with 1GB RAM exclusive for Rancher
- Nginx SSL Reverse Proxy on Host
- HAProxy LDAPS Proxy on the edge of our internal network with public SSL cert
- Multiple public IPs and DNS failover for external LDAPS access
- HAProxy balances to 3 internal Active Directory servers

We already have multiple internal and external services that successfully authenticate against the AD, most of them use libldap from OpenLDAP under the hood.

**Comment by tfiduccia** [comment]
I use AD through the UI and found
"Could not talk to ldap" error - you will see this if the Service Account Username or Password is not correct.
"Unauthorized" - problem with Default Login Domain, test username or password.

So for Service Account Password you have MY-DOMAIN\username and Default Login Domain set to MY-DOMAIN?

**Comment by felixbuenemann** [comment]
The service account is specified as "CN=LDAP,ou=My Company,dc=my-domain,dc=net".

Are you saying, I should use MY-DOMAIN\LDAP instead?

**Comment by tfiduccia** [comment]
ah LDAP screen not the AD screen.  Sorry, like I said I'm going through the UI and since our LDAP screen does not have a Default Domain field I thought you were talking about AD screen.   Here is what I have:
Hostname = ip of host
Say my Base DN was ou=people, dc=dctest-1, dc=dctest-1, dc=internal
Service account = 'cn=admin, dc=dctest-1, dc=dctest-1, dc=internal'
Search base = 'ou=people, dc=dctest-1, dc=dctest-1, dc=internal'

Still shouldn't have to use domain\username for the username fields.

**Comment by felixbuenemann** [comment]
I am talking about the AD screen.

**Comment by tfiduccia** [comment]
Then yes, I am saying it should be MY-DOMAIN\LDAP instead.

**Comment by felixbuenemann** [comment]
Thanks, that worked. I set Default Domain to MY-DOMAIN and Service Account to LDAP.

It didn't occur to me to try this previously, because all our other integrations with the AD use OpenLDAP based clients, which always use a bind DN instead of a plain username.

**Comment by felixbuenemann** [comment]
I still think this is a bug, because Rancher should either not support DN syntax for the service user or detect that it is a DN and not try to prefix it with the default domain.

I'm pretty sure the problem described a above happens, because Rancher uses "MY-DOMAIN\cn=LDAP,ou=My Company,dc=my-domain,dc=net" as the bind user, which is why it works if the Default Domain field is left blank.

**Comment by vincent99** [comment]
"Happens to work in some case" and "support[s]" are not necessarily the same thing. But we will be moving auth into it's own separate service in 1.2 and can look at this then.

**Comment by hdep** [comment]
Hello,

running rancher 1.6.2 I have the same issue. 
If I feel up the field Default Login Domain I got the error : Could not talk to ldap

**Comment by jonaskello** [comment]
I had the same error message`Could not talk to ldap` but got it working with default domain. There are many settings and the error message is not very helpful. I found out how to debug it:

As explained [here](http://rancher.com/docs/rancher/v1.6/en/faqs/server/#where-can-i-find-detailed-logs-of-the-rancher-server-container), check the contents of `cattle-debug.log` file in your rancher server container:
```
# Exec into the server container
$ docker exec -it <container_id> bash

# Navigate to the location of the cattle logs
$ cd /var/lib/cattle/logs/
$ cat cattle-debug.log
```

In `cattle-debug.log` you should find an entry similar to this:

```
017-08-25 09:48:59,043 INFO  [:] [] [] [] [tp1020391880-16] [.i.l.a.LdapServiceContextPoolFactory] Failed to create a service context: [LDAP: error code 49 - 80090308: LdapErr: DSID-0C090404, comment: AcceptSecurityContext error, data 52e, v1772] 
```

Now look the last part of that and you can see `AcceptSecurityContext error, data 52e, v1772`. The code we want here is `52e`, you may have a different code here.

Then check [this page](http://ldapwiki.com/wiki/Common%20Active%20Directory%20Bind%20Errors) for the translation of the codes.

For example for the code `52e`:

> 52e	1326	ERROR_LOGON_FAILURE	Returns when username is valid but password/credential is invalid.

So in my case I had just mis-spelled a password :-). But with so many configuration options it is not easy to know what is wrong without gettng this detailed information.

**Comment by deniseschannon** [comment]
This is fixed in v2.0. 

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

**Comment by S0LERA** [comment]
Hi,
I am using Rancher 2.7 and I am having problems with the configuration of LDAP. If I set the option _Default Login Domain_ with my domain, the configuration fails and I can't use LDAP. But if I left it empty, I can log as username@domain without problems.

I try to set the option as:

- only domain
- `@domain`
- `domain\`

And none of them works. Is this a bug or am I doing something wrong? It's annoying to have to login always with user@domain.

**Comment by sec252** [comment]
> Hi, I am using Rancher 2.7 and I am having problems with the configuration of LDAP. If I set the option _Default Login Domain_ with my domain, the configuration fails and I can't use LDAP. But if I left it empty, I can log as username@domain without problems.
> 
> I try to set the option as:
> 
>     * only domain
> 
>     * `@domain`
> 
>     * `domain\`
> 
> 
> And none of them works. Is this a bug or am I doing something wrong? It's annoying to have to login always with user@domain.

I'm having this same exact issue. using v2.8

**Comment by alexandra-branco** [comment]
I also had this issue in kubernetes/helm installation scenarios. In my case [this](https://github.com/rancher/rancher/issues/45519#issuecomment-2323508456) workaround worked.
