### ISSUE TITLE
How to clean the stacks without any service?

### ISSUE THREAD

**Issue by zhang8473** [rancher/rancher#5281]
`/rancher/bin/rancher-compose -p stackname -f docker-compose.yml -r rancher-compose.yml rm --force`

It deleted all of the services but the stack is still there. However, how to delete the stack completely by commands?

**Comment by deniseschannon** [comment]
There is no way to delete the stack with the commands. We have an existing enhancement request. 

https://github.com/rancher/rancher/issues/1723
