### ISSUE TITLE
Markdown in stack description

### ISSUE THREAD

**Issue by inwaar** [rancher/rancher#5282]
It would be nice to have such feature, or at least make links clickable if there are some in a stack description.

**Comment by forhot2000** [comment]
👍 +1

**Comment by XciD** [comment]
:+1:

**Comment by vincent99** [comment]
I would be OK with regex to find typical (I.e. not pathological cases or a giant list of every gtld to make naked "blah.io" work) links and make them clickable, but there is nothing to indicate whether a given (existing, especially) description should be rendered as markdown or if we're just going to mess up their intended text.

@loganhz can you make a component which takes text, finds links, wraps them in an A and renders the html.  Then replace all the places that show description with it.

**Comment by duck1123** [comment]
FWIW, that was the use-case that led me to this issue. While I think it could possibly be neat to have more advanced stack pages with status images and whatnot, I understand that there are better places for that.

**Comment by tfiduccia** [comment]
version - 9/19 (2.0 master)
Links working in description field.
Verified added.
