### ISSUE TITLE
The string value of "Chaina North" should be "China North" in Region options of Azure

### ISSUE THREAD

**Issue by Willwil** [rancher/rancher#5283]
**Rancher Version:1.1.0-dev5

**Docker Version:1.11.2

**OS and where are the hosts located? (cloud, bare metal, etc): cloud

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB): single node

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)

**Steps to Reproduce: Adding host to Azure

**Results: "Chaina North"

**Expected: "China North"

**Comment by tfiduccia** [comment]
Version - master 7/8
Verified fixed
