### ISSUE TITLE
Container metadata `state` out of sync

### ISSUE THREAD

**Issue by fixe** [rancher/rancher#5284]
**Rancher Version:**
1.0-dev5

**Docker Version:**
1.11.2

**OS and where are the hosts located? (cloud, bare metal, etc):**
Mac OSX

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**

Inside a container:

- curl -v http://rancher-metadata.rancher.internal/latest/self/stack/services/<service>/containers/0/state

> running

Restart the container using the UI. Wait until it becomes `running` again.

- curl -v http://rancher-metadata.rancher.internal/latest/self/stack/services/<service>/containers/0/state

> starting

**Expected:**
The second curl should return `running`.

**Comment by deniseschannon** [comment]
Confirmed this is a bug.

Steps to Reproduce:
1. Create an ubuntu service
2. Exec into the container
3. Run this command for the metadata service
```
curl 'http://rancher-metadata/latest/self/service/containers/0/state/`
```
4. Restart the container and wait until it is in Running state in the UI.
5. Exec into the container and run command
```
curl 'http://rancher-metadata/latest/self/service/containers/0/state/`
```

Results:
The second curl shows `starting`.

**Comment by alena1108** [comment]
Should be fixed with:

```
commit 6821a79840c7fa9fa6cca95bd0f0b873f2f562c6
Author: Alena Prokharchyk <alena@rancher.com>
Date:   Fri Sep 16 14:51:28 2016 -0700

    update metadata on instancehostmap.activate
```

**Comment by sangeethah** [comment]
Tested with latest build from master:

Steps to Reproduce:
1. Create an ubuntu service
2. Exec into the container
3. Run this command for the metadata service
```
wget http://rancher-metadata/latest/self/service/containers/0/state/
```
Restart the container and wait until it is in Running state in the UI.
Exec into the container and run command
```
wget http://rancher-metadata/latest/self/service/containers/0/state/
```
Results:
The second curl shows container in "running" state.

**Comment by Chris7** [comment]
Is there a workaround for the time being?
