### ISSUE TITLE
[Feature Request] AWS VPC/Subnet list includes names

### ISSUE THREAD

**Issue by bkuhl** [rancher/rancher#5285]
Our DevOps teams uses Rancher to manage all of our applications and they all live on AWS in isolated VPCs.  Currently our list of VPCs is 16 long and will continue to grow as time goes on.  It'd be VERY helpful to have VPCs and Subnets include the name as well as the id in the list when provisioning new hosts on AWS.  Right now we have to keep 2 tabs open and go back and hunt down the right ID.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.0.1` Cattle: `v0.159.7` UI: `v1.0.5` |
|Access|`github` `admin`|
|Route|`environments.index`|

**Comment by millidavids** [comment]
+1 for this request

**Comment by tfiduccia** [comment]
Version - master 8/2
Verified fixed - Name for vpc and subnet added to add host page.
