### ISSUE TITLE
Labels being lost in upgrade (io.rancher.container.create_agent and io.rancher.container.agent.role)

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#5286]
In the UI, we need to add in the equivalent for these Rancher labels

```
io.rancher.container.create_agent: 'true'
io.rancher.container.agent.role: environment
```

If anyone tries to upgrade or clone a service that has these labels, they will be removed.

**Comment by vincent99** [comment]
@deniseschannon lies?  Or old/in 1.0.x?  This should have been fixed a while ago

![image](https://cloud.githubusercontent.com/assets/753917/16751377/cb16c852-478d-11e6-9f59-fa0c987127c4.png)

**Comment by deniseschannon** [comment]
Verified in v1.1.1 that the labels are being copied.
