### ISSUE TITLE
Ability to resolve a service link (via dns) using a custom routing policy

### ISSUE THREAD

**Issue by ruimarinho** [rancher/rancher#5287]
It would be interesting to be able link a service and choose a custom routing policy, similar to what Route53 provides.

For instance, a "latency-based policy" could be useful when one wants to make sure that linking to a service running on the same host would make it a preferable choice. This is particular useful for services which should run co-located.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
