### ISSUE TITLE
Setting up single host Kubernetes fails

### ISSUE THREAD

**Issue by felixbuenemann** [rancher/rancher#5288]
Trying to convert a single host Rancher environment to a single host Kubernetes environment fails, because the services don't come up successfully and continually restart themselves.

Steps to reproduce:

* Start rancher-server container
* Add host running rancher as the only host
* Edit `Default` environment to use Kubernetes instead of Rancher
* Rancher install all the containers for kubernetes, but some of those fail to start

The status page in the Rancher UI shows either starting services 2/10 or 3/10.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.1.0-dev5` Cattle: `v0.164.1` UI: `v1.1.10` |
|Access|`Disabled`|
|Orchestration|`Cattle`|
|Route|`settings.projects.index`|
|Host|Docker for Mac `1.12.0-rc2` (XHyve)|
|OS|Alpine Linux v3.4 (4.4.14-moby)|
|XHyve VM|CPU: `2x 3.1 GHz` RAM: `4GB`|

Screenshot of the container view:

![screenshot 2016-06-29 23 51 00](https://cloud.githubusercontent.com/assets/909587/16470097/89846dbe-3e54-11e6-9038-f0eef6ecfb6a.png)

**Comment by deniseschannon** [comment]
You need more resources if you are only using 1 host in K8S on v1.1.0-dev5. 

From the release notes:
Kubernetes: HA Support through etcd-cluster [#4499] - K8s on Rancher is now highly available through enabling etcd in a cluster mode. Important: In a Kubernetes environment, the amount of RAM needed on any single host will need to be 6 GB.

If you upgrade to v1.1.0, you should be able to use your same hosts and switch to k8s with no issues. 

Let me know if you have any questions.
