### ISSUE TITLE
Icons not showing up on Edge in Windows 10

### ISSUE THREAD

**Issue by RobertKozak** [rancher/rancher#5291]
**Rancher Version:**
v1.1.0-dev5

Icons not showing up in buttons. This is one all screens and I just included this one as an example.

![rancher-ui-bug](https://cloud.githubusercontent.com/assets/85093/16477747/0b628484-3ec7-11e6-8ad8-f81a6fb0a21a.png)

**Comment by tfiduccia** [comment]
Version - v1.1.0
Checked and the images are not showing up.  Console says it doesn't recognize the .woff extension.

**Comment by RobertKozak** [comment]
https://blogs.windows.com/msedgedev/2016/05/03/woff2-fonts-in-microsoft-edge/

Edge will support Woff2

**Comment by vincent99** [comment]
What's weird is even old IE supports woff (not woff2).  Anyway we'll look into it.

**Comment by vincent99** [comment]
This appears to be another manifestation of https://github.com/rancher/rancher/issues/2199 , the content-type is being sent as `application/x-gzip` when served up by Cattle and Edge refuses to use it.

**Comment by RobertKozak** [comment]
![untitled](https://cloud.githubusercontent.com/assets/85093/17347867/60d97f66-58c7-11e6-9834-08e1922fdfa8.png)

using v1.2.0-pre1 issue is still there
