### ISSUE TITLE
No managed network ip assigned with custom docker network (--net=mynet)

### ISSUE THREAD

**Issue by GameScripting** [rancher/rancher#5292]
**Rancher Version:**
v1.0.1

**Docker Version:**
1.11.2

**OS and where are the hosts located? (cloud, bare metal, etc):**
cloud, Ubuntu 14.04.4 LTS (with KVM) (3.13.0-88-generic)

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node, internal db

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
cattle

**Steps to Reproduce:**

Case 1)
`docker network create test`
`docker run -l io.rancher.container.network=true --net=test ubuntu ip addr`

Case 2)
`docker run -l io.rancher.container.network=true ubuntu ip addr`

**Results:** 

Case 1)
Shows only the docker network ip: 172.18.0.3

Case 2)
Shows both the docker network ip: 172.17.0.3
and the rancher managed ip: 10.42.197.210

![image](https://cloud.githubusercontent.com/assets/1827070/16494330/41d9fce6-3ee9-11e6-990a-aaa583655c99.png)

**Expected:**

I expected in both cases to to get a managed container ip assigned and be able to communicate within the rancher managed network

---

Is this a docker 1.11.x-related issue? Will it be fixed in the upcoming rancher release?
We really need support for both seperate docker networks and a rancher managed network!

**Comment by deniseschannon** [comment]
It's not obvious in the docs, but currently, the `io.rancher.container.network=true` only works for containers on the host network.

This would be an enhancement request to be able to use the managed network for custom docker network.

**Comment by GameScripting** [comment]
It might be an enhancement from a technical point of view but for me as a docker-compose user utilizing the new 2.0 format this looks like a bug.

Using docker-compose 2.0 format a new "default" network is always created. So non of the services will be attached to docker0 / host network.

---

Bug or enhancement, can I expect it to be fixed on the next rancher release?

**Comment by GameScripting** [comment]
I would like to try to implement that feature myself on the weekend.

Can someone give a little bit of direction which component I need to look into and what I might have to be aware of while trying to implement that feature?

**Comment by GameScripting** [comment]
As from what I found while running the code in the debugger:

A "hostVnetUri" containing "bridge://docker0" is stored in the database for the rancher managed network for that account/env.

![image](https://cloud.githubusercontent.com/assets/1827070/16707727/2327395c-45d9-11e6-99a9-1aaa0bba160a.png)


So we need to redesign how that works, from a per-rancher-network-host-interface (docker0) to a per-container-host-interface.

Is that host-interface required to setup the ipsec network?
Can we use the host network adapter (e.g. "br-c9949a8eec99") from the docker network or do we have to find the container-host-network-adapter (e.g. "vetha76bedb")?

**Comment by GameScripting** [comment]
One more thing that we need to consider when implemented this feature:

When a container is attached to a non-default docker network the new docker DNS server will resolve DNS names as container names. That may be (?) incompatible with ranchers service discovery DNS.

Example:
When running the following command in a container that is both connected to the non-default docker network and the rancher managed network what will happen?

    ping database

Case 1) It will try to find a container with the name "database" and resolve to that e.g. 172.20.0.2
Case 2) It will try to find a (rancher) service with the name "database" and resolve to that e.g. 10.42.10.3

That problem was also discussed by @ibuildthecloud at https://github.com/docker/docker/issues/19474#issuecomment-173221303

**Comment by leodotcloud** [comment]
Docker's libnetwork is not yet supported in rancher. We are still evaluating the options, will update the community once the plan is finalized.

**Comment by GameScripting** [comment]
I am wondering because @ibuildthecloud mentioned here ( https://forums.rancher.com/t/roadmap-for-docker-1-10-compose-1-6/1643/6 ) back in February that there will be rancher support on the new docker features.

So what is the progress so far? There must be some more that "will update the community once the plan is finalized" since the past 5 month ... ?

**Comment by GameScripting** [comment]
Today I installed rancher v1.2.1 onto fresh VMs with docker 1.12.
Unfortunately it seems like rancher managed network is still incompatible with docker 1.12 networks.

Am I correct? Is this still a feature request or should it working in 1.2.1?

**Comment by leodotcloud** [comment]
@GameScripting: In the latest release of Rancher, we have added support for CNI. So currently we don't support libnetwork.

**Comment by GameScripting** [comment]
https://github.com/rancher/rancher/issues/3895 is what I really need & want, so I close this one.
Thanks for clearing out CNI vs libnetwork.
