### ISSUE TITLE
Kubelet does not register host

### ISSUE THREAD

**Issue by roman0316** [rancher/rancher#5294]
**Rancher Version:** 
v1.1.0-dev5

**Docker Version:** 
1.11.1

**OS and where are the hosts located? (cloud, bare metal, etc):** 
Ubuntu 16.04. Scaleway - Cloud

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** 
Single Node

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
1. Create the Kubernetes Environment
2. Add two or three hosts
3. View the Kubelet log on each node.

**Results:** 
Only the node in which the kubernetes master services are running shows the following line:
_kubelet.go:1150] Node <node name> was previously registered_ 

Alternatively it says "_successfully registered_"

No other nodes show that they were registered in their respective kubelet logs.

`kubectl get nodes`  only shows the master node

**Expected:**
_Node <node name> was successfully registered_ should appear on every log of each kubelet.
`kubectl get nodes` should display all nodes in READY state

Thanks!

**Comment by tfiduccia** [comment]
Are all your host names unique?  For kubernetes to work properly they must be unique.

**Comment by roman0316** [comment]
Yes, the cloud provider generates a random set of 6 alphanumeric chars as a
name for the host.

I used to prepend a common name but after many tries I simply used that
random name when adding hosts.


On Thursday, June 30, 2016, Tani Fiduccia <notifications@github.com> wrote:

> Are all your host names unique? For kubernetes to work properly they must
> be unique.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/rancher/rancher/issues/5294#issuecomment-229825253>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABduYl-aTQ95E16mbzuFrI9oqGFcWpRrks5qRF-ngaJpZM4JCch3>
> .
>


-- 
  Ricardo Román | *INT*
| r.rmn92@gmail.com |

**Comment by roman0316** [comment]
So instead of using Scaleway's docker image, I used a regular Ubuntu 15.10 image and installed docker on it. 

Kubelet and Proxy start on the first try and the node gets registered.

Also tried with CentOS and got same successful results.

Could the image be the problem here?
They provide Ubuntu 16.04 + Docker 1.11.2 + aufs

And if so, how can I test it?

**Comment by tfiduccia** [comment]
Currently Kubernetes doesn't support docker 1.11.  You can try a Scaleway image with a 1.10 version of docker and it should work.  We have a bug already entered that you can track, #4428.  I'm going to close this issue, if after using 1.10 version and if you still aren't registering, please reopen.

**Comment by roman0316** [comment]
Thank you @tfiduccia 

I went ahead and tried it. Here is my current configuration:

Two Ubuntu 16.04 Hosts with Docker 1.10.3 installed. This is what I am seeing:

<img width="530" alt="screen shot 2016-07-02 at 12 38 12 am" src="https://cloud.githubusercontent.com/assets/1535586/16538861/ffc95a4e-3fed-11e6-93b0-c3cc71806bf7.png">

Then the logs from kubelet:

Kubelet on master node -
<img width="971" alt="screen shot 2016-07-02 at 12 40 24 am" src="https://cloud.githubusercontent.com/assets/1535586/16538864/11dffcce-3fee-11e6-8e2d-c009ef97d256.png">


Kubelet on other node - (This one does not output that it registered host)
<img width="970" alt="screen shot 2016-07-02 at 12 40 56 am" src="https://cloud.githubusercontent.com/assets/1535586/16538867/1d0f3dda-3fee-11e6-87bd-abd11bc0654e.png">


And finally, output from kubectl get nodes -
<img width="451" alt="screen shot 2016-07-02 at 12 38 03 am" src="https://cloud.githubusercontent.com/assets/1535586/16538875/31770f00-3fee-11e6-9fda-bd218dd272ae.png">

Deploying a couple of items from catalog results in them being scheduled only on the master node, not the other node.

<img width="547" alt="screen shot 2016-07-02 at 12 46 34 am" src="https://cloud.githubusercontent.com/assets/1535586/16538905/d03c53d4-3fee-11e6-9ecb-dae660c8858d.png">

 Thanks again!
