### ISSUE TITLE
translation broken on fail whale page

### ISSUE THREAD

**Issue by lvuch** [rancher/rancher#5295]
![screen shot 2016-06-30 at 11 30 19 am](https://cloud.githubusercontent.com/assets/3013118/16499655/3cb5bcb0-3eb6-11e6-95a8-6358977caded.png)

en-us.yaml not loading on fail whale page

**Comment by westlywright** [comment]
to reproduce 

1. Add github auth
2. logout after successful auth
3. use the following url https://localhost:8000/login?code=a51bb551882d85f7&state=bar

**Comment by tfiduccia** [comment]
Version - master 8/9
Verified fixed
