### ISSUE TITLE
Refactor python-agent in golang

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#5296]
High level set of tasks:
- Basic Framework for handling events - Not Daishan
- Get project into CI - Not Daishan
- Packaging of project and integration into rancher/cattle - Not Daishan
- Refactor the following processes to be launched by monit (instead of the go-agent launching/owning them) - Not Daishan
  - cadvisor
  - host-api
- Events
  - compute
    - compute.instance.activate
    - compute.intance.deactivate
    - compute.force.stop
    - compute.instance.inspect
    - compute.instance.pull
    - compute.instance.remove
  - storage
    - storage.image.activate
    - storage.volume.activate
    - storage.volume.deactivate
    - storage.volume.remove
  - delegate
    - delegate.request
- Ping logic
  - Dropped ping logic that causes agent to sever connection after N pings are dropped
  - Reporting containers for sync/backpopulation logic
  - Reporting host status using our collectors:
    - cpu
    - disk
    - iops
    - memory
    - operate system
- Implement new/remaining docker api parameters #4708

**Comment by deniseschannon** [comment]
Starting with v1.2.0-pre4-rc2, we've started using the new go agent. Any bugs for it will be filed separately.
