### ISSUE TITLE
[Feature Request] Convert io.rancher.container.requested_ip string to array

### ISSUE THREAD

**Issue by JaviSabalete** [rancher/rancher#5297]
**Rancher Version:**
1.0.1
**Docker Version:**
1.11.1
**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 14.04 - Amazon AWS
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher with external DB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Feature Request:**
I have a rancher stack and docker-compose have io.rancher.container.requested_ip for every container. Works fine, but just with scale = 1, because with scale = 2, container 2 have random ip, because IP is not available.

So, I propose convert io.rancher.container.requested_ip to 'array', like:

io.rancher.container.requested_ip = 10.42.100.100, 10.42.100.101, 10.42.100.102, 10.42.100.103

When I increase scale, rancher assigns next available ip from list.

**Comment by mch1307** [comment]
+1

**Comment by zionwu** [comment]
+1

**Comment by StrongMonkey** [comment]
In favor of @vincent99 's idea "label sucks, why not api fields", we should probably define a service field which includes all the requested IPs.

**Comment by vincent99** [comment]
![1-up](http://i.imgur.com/hd2ut3d.gif)

**Comment by StrongMonkey** [comment]
Available at v1.6. Now api field and label can be accepted as a comma-separated string. For standalone container only label works, and for service.launchconfig it works on both api and label.

**Comment by sangeethah** [comment]
Tested with rancher-server build from v1.6:

Able to pass comma separated ip addresses to ```io.rancher.container.requested_ip``` example ( "10.42.20.1,10.42.20.2,10.42.20.3,10.42.20.4,10.42.20.5") when creating service. 
When service instances are scaled up , every instance of the service gets an ip from the requested ip list as expected.

**Comment by sangeethah** [comment]
@StrongMonkey , When I try to upgrade a service that has ```io.rancher.container.requested_ip``` set , I see that the ips on the upgraded service instances get random Ips.

**Comment by sangeethah** [comment]
Issue seen with upgrade is tracked in - https://github.com/rancher/rancher/issues/9395

**Comment by sangeethah** [comment]
Tested with rancher-server build from v1.6:

Able to create service with requestedIpAddres set as a field in launch config.
```
    launch_config = {"imageUuid": "docker:sangeetha/testnewhostrouting",
                     "requestedIpAddress": "10.42.100.100, 10.42.100.101"
                    }
```
Service instances gets ipaddress from the requestedIpAddress list.

**Comment by sangeethah** [comment]
@JaviSabalete  With the next rancher server release  (v1.6.5) , io.rancher.container.requested_ip will accept  comma separated ip addresses.
