### ISSUE TITLE
Add support for TLSMA to the load balancer

### ISSUE THREAD

**Issue by chrisurwin** [rancher/rancher#5298]
Feature request for a client presenting a valid certificate issued by the same CA as the termination certificate to allow access through the proxy.

The proxy should fail to allow traffic if presented certificate is not valid.

This can be achieved by adding verify required to the bind command in the webfrontend section of the haproxy.cfg

This should be an option when creating a load balancer that is terminating SSL connections

**Comment by alena1108** [comment]
@chrisurwin we already support that by setting ```strict-sni``` parameter when no default certificate is present for haproxy. In this case request will be considered as valid only when (https://www.haproxy.com/doc/aloha/7.0/haproxy/tls.html_:

```
The SSL/TLS negotiation is allowed only if the client provides a SNI which matches a certificate loaded by HAProxy.
```

```verify required``` doesn't do Server Name Indication (SNI), it just validates whether the certificate is present:


```
required: A client certificate is requested by HAProxy, and TLS handshake is aborted if the client doesn’t provide one
```

**Comment by alena1108** [comment]
actually nvm, strict-sni provides SNI name validation, not the client cert validation. Verify requireed does more that just ensuring that the cert is present in the client request. Official haproxy doc (http://www.haproxy.org/download/1.5/doc/configuration.txt):

```
verify [none|optional|required]
  This setting is only available when support for OpenSSL was built in. If set
  to 'none', client certificate is not requested. This is the default. In other
  cases, a client certificate is requested. If the client does not provide a
  certificate after the request and if 'verify' is set to 'required', then the
  handshake is aborted, while it would have succeeded if set to 'optional'. The
  certificate provided by the client is always verified using CAs from
  'ca-file' and optional CRLs from 'crl-file'. On verify failure the handshake
  is aborted, regardless of the 'verify' option, unless the error code exactly
  matches one of those listed with 'ca-ignore-err' or 'crt-ignore-err'
```

so verify-required is the correct flag to use for this purpose

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
