### ISSUE TITLE
Add whitelist to TLSMA on Load Balancer

### ISSUE THREAD

**Issue by chrisurwin** [rancher/rancher#5299]
<issue #5298 >
In order to secure a web resource add a whitelist to the backend section of Haproxy.cfg that allows for a whitelist that contains a list of valid cn's. Only if the cn of the mutually authenticated certificate is in the list should access be allowed.

this can be achieved with adding:
`
acl validcert ssl_c_s_dn(cn) -f /etc/haproxy/authorised_cns
http-request deny if !validcert`
to the backend section of the haproxy.cfg where authorised_cns is a file that contains a list of valid cn's, this may also be achievable using -str instead of -f

**Comment by deniseschannon** [comment]
It sounds like you want to customize the backend of haproxy.cfg.

This is covered in #2179 

Please re-open if I'm mistaken.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
