### ISSUE TITLE
Agent thin pool error - "unable to get fs usage from thin pool for device "

### ISSUE THREAD

**Issue by diogogmt** [rancher/rancher#5303]
**Rancher Version:**
1.1.0
**Docker Version:**
1.11.2
**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu willy
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
cattle
**Steps to Reproduce:**
Add a host to rancher
Tail the rancher-agent logs
**Results:** 
Get this errors on the log:

```
I0630 19:27:15.721986   11989 thin_pool_watcher.go:117] reserving metadata snapshot for thin-pool docker-8:1-491370-pool
E0630 19:27:15.731341   11989 thin_pool_watcher.go:54] encountered error refreshing thin pool watcher: error performing thin_ls on metadata device /dev/loop1: Error running command `thin_ls --no-headers -m -o DEV,EXCLUSIVE_BYTES /dev/loop1`: exec: "thin_ls": executable file not found in $PATH
output:

E0630 19:27:15.868807   11989 handler.go:278] unable to get fs usage from thin pool for device 1359: no cached value for usage of device 1359
E0630 19:27:15.988615   11989 handler.go:278] unable to get fs usage from thin pool for device 12: no cached value for usage of device 12
```

Then after every second it keeps logging:
```
E0630 19:27:46.177876   11989 handler.go:278] unable to get fs usage from thin pool for device 1359: no cached value for usage of device 1359
```

**Expected:**

**Comment by tsupertramp** [comment]
Same happens with ubuntu trusty

**Comment by deniseschannon** [comment]
I just installed an Ubuntu trusty and didn't see the error. I will try with some of the other OS types later.

Just to confirm, is your Rancher agent able to connect to your Rancher server?

**Comment by diogogmt** [comment]
@deniseschannon I haven't tested with Trusty, but if it is working for you I'll give it a try.

Yes, the rancher-agent is connected to the server and I'm able to schedule containers and they can talk on the overlay network.

**Comment by Sxw1212** [comment]
I am also experiencing this message on Ubuntu 15.04 KVM hosts in a multi node cluster. It does not appear to affect cluster operation other than some logging disk space usage. A difference from the OP's post is that the message appears multiple times a second instead of just once.

**Comment by diogogmt** [comment]
@deniseschannon The same problem has also being logged at the cAdvisor issue tracker: https://github.com/google/cadvisor/issues/1360

**Comment by aldarund** [comment]
Same issue on Centos 7/Kubernetes 
Rancher Version:
1.1.0
Docker Version:
1.11.2
Docker logs are spammed with this:
```
E0702 19:20:22.194575   31411 handler.go:278] unable to get fs usage from thin pool for device 30: no cached value for usage of device 30
E0702 19:20:22.730435   31411 handler.go:278] unable to get fs usage from thin pool for device 34: no cached value for usage of device 34
I0702 19:20:23.000603   31411 thin_pool_watcher.go:117] reserving metadata snapshot for thin-pool docker-253:0-67698678-pool
E0702 19:20:23.015050   31411 thin_pool_watcher.go:65] encountered error refreshing thin pool watcher: error performing thin_ls on metadata device /dev/loop1: Error running command `thin_ls --no-headers -m -o DEV,EXCLUSIVE_BYTES /dev/loop1`: exec: "thin_ls": executable file not found in $PATH
output:

E0702 19:20:23.558729   31411 handler.go:278] unable to get fs usage from thin pool for device 16: no cached value for usage of device 16
E0702 19:20:23.763638   31411 handler.go:278] unable to get fs usage from thin pool for device 30: no cached value for usage of device 30
```

**Comment by Thom-x** [comment]
Same issue on Ubuntu 14.04
Rancher Version:
1.1.0
Docker Version:
1.9.1
Docker logs are spammed with this:

```
E0702 18:51:00.956576   15813 handler.go:278] unable to get fs usage from thin pool for device 143: no cached value for usage of device 143
E0702 18:51:01.544518   15813 handler.go:278] unable to get fs usage from thin pool for device 40: no cached value for usage of device 40
E0702 18:51:01.802225   15813 handler.go:278] unable to get fs usage from thin pool for device 91: no cached value for usage of device 91
```

**Comment by djcenox** [comment]
+1

**Comment by deniseschannon** [comment]
I believe this is due to cadvisor. per @diogogmt's comment above. 

Please let me know if this actually prevents any issues with your Rancher set up.

**Comment by kmcgrath** [comment]
I need to re-create my environment, but I noticed this with AWS Linux because the rancher load balancer was not working.  When switched os + version of docker, the load balancer worked again.

**Comment by elevy411** [comment]
I get this error as well: 
Stat fs failed. Error: no such file or directory
unable to get fs usage from thin pool for device ##

Any thoughts on fixing? I looked at the CAadvisor post and didn't really understand its application here. Thank you!

**Comment by djcenox** [comment]
I've figured out this problem by not using standard device mapper loop devices that docker uses.
Check out with "docker info" in your machine.
As loop devices are not usable in prod (not even in test in my opinion)
I'm using AUFS atm (you need kernel-ml-aufs) and is MOAR faster.

**Comment by elevy411** [comment]
djcenox, can you further explain what you mean? I am quite new to docker/rancher in general. Thank you!

**Comment by djcenox** [comment]
I'll try to explain. This is what I found so far and what I have done. So maybe is not the fix, but is a suggestion.

Everything come from this [post]( http://www.projectatomic.io/blog/2015/06/notes-on-fedora-centos-and-docker-storage-drivers)/
Where I finally watched what docker when you check in status and in "docker info" write out. There is a warning  about to not use docker with loop. 
Data file and metadata file (for images) are looped that means are virtually a file that act as filesystem (the short explain, really short).
Anyway i've found that in dmesg i've a lot of problem with one of those file mapped with device mapper (check `lsblk` command ).
Then i went to check in docker documentation: [select a driver](https://docs.docker.com/engine/userguide/storagedriver/selectadriver/)
Here I chose AUFS (due to lazyness to create new docker lvm volumes). 
Things work really better now.

**Comment by elevy411** [comment]
So basically you just change the storage driver type to AUFS? Will that retroactively fix the containers made or should I recreate the stacks (ELK etc.)? Thanks again

**Comment by djcenox** [comment]
Well, to use aufs you have to upgrade kernel with a aufs `kernel-ml-aufs` then you have aufs support (kernel 4.6.4). 
Unfortunately the procedure means `rm -rf /var/lib/docker` so you will lose all images and containers, even if you decide to make new lvm group and bind docker to them.

**Comment by kmcgrath** [comment]
Fresh install of AWS Linux with Docker version 1.11.2, build b9f10c9/1.11.2

still see:

    handler.go:278] unable to get fs usage from thin pool for device 23: no cached value for usage of device 23

I deploy a rancher load balancer that runs on 3 hosts.  The service never moves past initializing.  I don't know enough to dig into the logs of what is going on with haproxy inside the container.  Monit seems to be running fine, but haproxy is not running correctly.

If I change to docker 1.9 on AWS Linux I do not have the problem.

**Comment by deniseschannon** [comment]
@kmcgrath A host stuck in initializing is an issue with cross host networking. The above error should not affect it. 

Can you try exec into one of the network agents and ping the IP of another network agent  (10.42.x.x) on another host? Network agents might be hidden in the UI if you are using v1.1.0 but can be shown if you click on the "Show System" checkbox in the upper right corner of the UI on the hosts page. 

http://docs.rancher.com/rancher/latest/en/faqs/troubleshooting/#cross-host-communication

**Comment by guhcampos** [comment]
I'm currently getting a similar output with CentOS 7 and Docker 1.11., b9f10c9

```
E0715 16:19:01.246915    3298 handler.go:278] unable to get fs usage from thin pool for device 16: no cached value for usage of device 16
E0715 16:19:02.821302    3298 handler.go:278] unable to get fs usage from thin pool for device 16: no cached value for usage of device 16
E0715 16:19:04.476642    3298 handler.go:278] unable to get fs usage from thin pool for device 16: no cached value for usage of device 16
E0715 16:19:05.891279    3298 handler.go:278] unable to get fs usage from thin pool for device 16: no cached value for usage of device 16
E0715 16:19:06.311456    3298 thin_pool_watcher.go:65] encountered error refreshing thin pool watcher: error determining whether snapshot is reserved: unexpected output of dmsetup status command; expected 11 fields, got 11; output: 0 209715200 thin-pool 18 356/524288 8876/1638400 - rw discard_passdown queue_if_no_space
```

On one host, stopping the docker daemon, removing `/var/lib/docker/*` and restarting the machine fixed it. On another one I get the error again even after doing that, so this could be a coincidence.

**Comment by kmcgrath** [comment]
@deniseschannon sorry for the noise.

We had 2 security groups with what I thought were identical configs. But alas, they were not.  The thin provision error is still happening, but there is no LB issue.  That my MY fault.

**Comment by linsheng9731** [comment]
**server info:**
4.4.11-23.53.amzn1.x86_64 
**docker info :**
Server Version: 1.11.2
Storage Driver: devicemapper
 Pool Name: docker-253:0-3670020-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0

got same problem : 
`unable to get fs usage from thin pool for device 201: no cached value for usage of device 201`

**Comment by djcenox** [comment]
@linsheng9731 looks like you are using `/dev/loopX` as filesystem. Check out what I wrote some days ago, maybe can help. (you can use devicemapper-lvm instead AUFS)

**Comment by linsheng9731** [comment]
@djcenox yes ! you are right ! agent only support aufs filesystem,  it's a bug.

**Comment by MarcusSjolin** [comment]
I got this problem as well, after upgrading rancher. Running in AWS with their Centos. 

It has worked fine for a week, and now it appears to deliver this message when I tried to reattach the agent after it had gone unresponsive.

Any ideas?

```
[... ~]$ docker info
Server Version: 1.11.2
Storage Driver: devicemapper
 Pool Name: docker-202:1-5373963-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 848.7 MB
 Data Space Total: 107.4 GB
 Data Space Available: 106.5 GB
 Metadata Space Used: 1.729 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.15-25.57.amzn1.x86_64
Operating System: Amazon Linux AMI 2016.03
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.42 GiB
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
```

**Comment by elevy411** [comment]
I was able to fix the problem by changing Storage driver to AUFS. (DOCKER_OPTS= "--storage-driver=AUFS")

Hopefully that works for you as well!

**Comment by MarcusSjolin** [comment]
I let this be overnight, and it resolved itself. It kept trying to connect and by the morning it just worked.d

**Comment by deniseschannon** [comment]
As this is an issue in cadvisor and Rancher works fine with all the workarounds. I'll close this issue.

**Comment by allhaker** [comment]
On RHEL 7 moving to overlay driver has helped.

**Comment by ddelnano** [comment]
I know this issue is closed but wanted to say when experiencing this issue I switched to aufs one instance at a time.  During this process I accidentally left one host using devicemapper.  What is interesting is that I do not see that container or the host in the Rancher UI at all.  It seems to be functioning perfectly but is just not present at all.
