### ISSUE TITLE
Azure Active Directory Error : Unauthorized

### ISSUE THREAD

**Issue by kvaes** [rancher/rancher#5304]
**Rancher Version:** 1.2.0

**Docker Version:**  1.11.2

**OS and where are the hosts located? (cloud, bare metal, etc):** Bare Metal

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** Single Node / Internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** n/a

**Steps to Reproduce:**

* Create an Azure AD Application using the following script ; https://github.com/kvaes/docker-rancher-scripts/blob/master/azure-ad/rancher-create-azure-ad-principal.ps1
* Add the details provided after the creation in the configuration of Azure AD as authentication provider
* Supply the credentials (username@domain.tld with password) of a user with global admin rights on the azure active directory as "admin user"
* Use the same user credentials to test the configuration

**Results:** 

Login fails with error "Unauthorized"

The following error can be found in the logs

6/30/2016 10:13:19 PM2016-06-30 20:13:19,890 ERROR [:] [] [] [] [tp1320306521-15] [i.c.p.i.a.a.i.azure.AzureRESTClient ] Got error from Azure. io.github.ibuildthecloud.gdapi.exception.ClientVisibleException: null
6/30/2016 10:13:19 PM	at io.cattle.platform.iaas.api.auth.integration.azure.AzureRESTClient.noAzure(AzureRESTClient.java:292) [cattle-iaas-auth-logic-0.5.0-SNAPSHOT.jar:na]
6/30/2016 10:13:19 PM	at io.cattle.platform.iaas.api.auth.integration.azure.AzureRESTClient.getAccessToken(AzureRESTClient.java:154) [cattle-iaas-auth-logic-0.5.0-SNAPSHOT.jar:na]
6/30/2016 10:13:19 PM	at io.cattle.platform.iaas.api.auth.integration.azure.AzureTokenCreator.getToken(AzureTokenCreator.java:36) [cattle-iaas-auth-logic-0.5.0-SNAPSHOT.jar:na]
6/30/2016 10:13:19 PM	at io.cattle.platform.iaas.api.auth.identity.TokenResourceManager.createToken(TokenResourceManager.java:59) [cattle-iaas-auth-logic-0.5.0-SNAPSHOT.jar:na]
6/30/2016 10:13:19 PM	at io.cattle.platform.iaas.api.auth.identity.TokenResourceManager.createInternal(TokenResourceManager.java:45) [cattle-iaas-auth-logic-0.5.0-SNAPSHOT.jar:na]
6/30/2016 10:13:19 PM	at io.github.ibuildthecloud.gdapi.request.resource.impl.AbstractBaseResourceManager.create(AbstractBaseResourceManager.java:115) [cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
6/30/2016 10:13:19 PM	at io.github.ibuildthecloud.gdapi.request.handler.ResourceManagerRequestHandler.generate(ResourceManagerRequestHandler.java:40) [cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
6/30/2016 10:13:19 PM	at io.github.ibuildthecloud.gdapi.request.handler.AbstractResponseGenerator.handle(AbstractResponseGenerator.java:14) [cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
6/30/2016 10:13:19 PM	at io.github.ibuildthecloud.gdapi.request.handler.write.DefaultReadWriteApiDelegate.handle(DefaultReadWriteApiDelegate.java:28) [cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
6/30/2016 10:13:19 PM	at io.github.ibuildthecloud.gdapi.request.handler.write.DefaultReadWriteApiDelegate.write(DefaultReadWriteApiDelegate.java:23) [cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
6/30/2016 10:13:19 PM	at sun.reflect.GeneratedMethodAccessor619.invoke(Unknown Source) ~[na:na]
6/30/2016 10:13:19 PM	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_101]
6/30/2016 10:13:19 PM	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_101]
6/30/2016 10:13:19 PM	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317) [spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
6/30/2016 10:13:19 PM	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183) [spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
6/30/2016 10:13:19 PM	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150) [spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
6/30/2016 10:13:19 PM	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:96) [spring-tx-3.2.4.RELEASE.jar:3.2.4.RELEASE]
6/30/2016 10:13:19 PM	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:260) [spring-tx-3.2.4.RELEASE.jar:3.2.4.RELEASE]
6/30/2016 10:13:19 PM	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94) [spring-tx-3.2.4.RELEASE.jar:3.2.4.RELEASE]
6/30/2016 10:13:19 PM	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) [spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
6/30/2016 10:13:19 PM	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91) [spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
6/30/2016 10:13:19 PM	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) [spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
6/30/2016 10:13:19 PM	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204) [spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
6/30/2016 10:13:19 PM	at com.sun.proxy.$Proxy45.write(Unknown Source) [na:na]
6/30/2016 10:13:19 PM	at io.github.ibuildthecloud.gdapi.request.handler.write.ReadWriteApiHandler.handle(ReadWriteApiHandler.java:20) [cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
6/30/2016 10:13:19 PM	at io.github.ibuildthecloud.gdapi.servlet.ApiRequestFilterDelegate.doFilter(ApiRequestFilterDelegate.java:86) [cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
6/30/2016 10:13:19 PM	at io.cattle.platform.api.servlet.ApiRequestFilter$1.runInContext(ApiRequestFilter.java:90) [cattle-framework-api-0.5.0-SNAPSHOT.jar:na]
6/30/2016 10:13:19 PM	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
6/30/2016 10:13:19 PM	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
6/30/2016 10:13:19 PM	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
6/30/2016 10:13:19 PM	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
6/30/2016 10:13:19 PM	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
6/30/2016 10:13:19 PM	at io.cattle.platform.api.servlet.ApiRequestFilter.doFilter(ApiRequestFilter.java:83) [cattle-framework-api-0.5.0-SNAPSHOT.jar:na]
6/30/2016 10:13:19 PM	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
6/30/2016 10:13:19 PM	at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83) [jetty-servlets-9.2.11.v20150529.jar:9.2.11.v20150529]
6/30/2016 10:13:19 PM	at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:300) [jetty-servlets-9.2.11.v20150529.jar:9.2.11.v20150529]
6/30/2016 10:13:19 PM	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
6/30/2016 10:13:19 PM	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
6/30/2016 10:13:19 PM	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
6/30/2016 10:13:19 PM	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577) [jetty-security-9.2.11.v20150529.jar:9.2.11.v20150529]
6/30/2016 10:13:19 PM	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
6/30/2016 10:13:19 PM	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
6/30/2016 10:13:19 PM	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
6/30/2016 10:13:19 PM	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
6/30/2016 10:13:19 PM	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
6/30/2016 10:13:19 PM	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
6/30/2016 10:13:19 PM	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
6/30/2016 10:13:19 PM	at org.eclipse.jetty.server.Server.handle(Server.java:499) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
6/30/2016 10:13:19 PM	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
6/30/2016 10:13:19 PM	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
6/30/2016 10:13:19 PM	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) [jetty-io-9.2.11.v20150529.jar:9.2.11.v20150529]
6/30/2016 10:13:19 PM	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) [jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
6/30/2016 10:13:19 PM	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) [jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
6/30/2016 10:13:19 PM	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_101]
6/30/2016 10:13:19 PM
Connected

**Expected:**

login test should have succeeded

**Comment by tfiduccia** [comment]
For the username for both admin & test can you try just "username" without the @domain.tld.

**Comment by kvaes** [comment]
Just tried the following username

- rancher@kvaes.be (custom domain)
- rancher@kvaes.onmicrosoft.com (initial aad name)
- rancher

For domain I used both "kvaes.be" and "kvaes.onmicrosoft.com".

I also used alternating user formats for both the admin user & the test user.


To be honest, the flow where you need to provide an admin username feels very "ldap"-alike an counter intuitive when you are accustomed to working with AAD. 
As a reference ; This is typical service principal integration with Azure Active Directory (AAD in short) => http://docs.octopusdeploy.com/display/OD/Creating+an+Azure+Service+Principal+Account
Just putting it out here, which might make something "click" in terms of logic. Offcourse everything depends on the way it's been implemented.

**Comment by tfiduccia** [comment]
So just to be sure, in Azure AD you created a user with the name rancher?

**Comment by kvaes** [comment]
<img width="694" alt="2016-07-01 08_32_27-active directory - microsoft azure" src="https://cloud.githubusercontent.com/assets/10435278/16513688/e6b0bb9c-3f66-11e6-9deb-4f0f5e1dfbf8.png">
<img width="680" alt="2016-07-01 08_32_35-active directory - microsoft azure" src="https://cloud.githubusercontent.com/assets/10435278/16513689/e6b2072c-3f66-11e6-8185-b451886bf074.png">
<img width="690" alt="2016-07-01 08_33_16-active directory - microsoft azure" src="https://cloud.githubusercontent.com/assets/10435278/16513690/e6b5e4d2-3f66-11e6-9221-8303bde45224.png">

**Comment by tfiduccia** [comment]
A couple of things to check in the application configuration - 
1.   When you setup did you choose web application or Native client (mine is a native client)
2.  Check your "Permissions to other applications" and make sure AD has read access

**Comment by kvaes** [comment]
Tani,

That was the golden tip! I would suggest to add that to the documentation. That the application created in the AAD needs to be a native one. This as you need to grant the read access rights, which is not possible via the web app.

> "Azure AD Authentication is enabled
> Rancher is configured to allow access to accounts in Azure AD"

Thanks!

Karim

**Comment by kvaes** [comment]
FYI - Created a walkthrough for this based on your help... ;-)

https://kvaes.wordpress.com/2016/07/02/integrating-azure-active-directory-with-rancher/

**Comment by richbayliss** [comment]
@kvaes thank you for the guide - however when I followed this using the new Azure Portal I am getting the same exception in the logs as well as the "Unauthorised" error message.

Do you know if this guide is suitable given the new Azure Portal?

**Comment by kvaes** [comment]
@richbayliss ; it's the same flow... did you use the native app for the app registration?

**Comment by richbayliss** [comment]
@kvaes yes - in fact it was an issue with permissions in Azure... there is a not-so-obvious way to grant permissions after selecting them, very poor UX in my view. After completing this additional step it worked as per your guide. Perhaps you might like to update the guide to reflect the new UI on Azure? Either way, thanks to your guide I have a working setup.
