### ISSUE TITLE
etcd is stuck in intializing state

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#5306]
**Rancher Version:**1.1.0

**OS and where are the hosts located? (cloud, bare metal, etc):** Ubuntu, Cloud

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**: Kubernetes

**Steps to Reproduce:**
1. Create a Kubernetes environment with with 5 hosts(scale policy: max of 5), 
2. Turn off 2 hosts. Kubernetes is functional, but etcd has error messages in the logs. Refer : https://github.com/rancher/rancher/issues/5305
3. Add another host. etcd scales up correctly.
4. Turn on one host, etcd is stuck in initializing state on this host

Note: In this state, Kubernetes is functional, able to get nodes,  add pods

**Comment by LLParse** [comment]
Relevant PRs:
https://github.com/rancher/catalog-dockerfiles/pull/72
https://github.com/rancher/community-catalog/pull/208
https://github.com/rancher/rancher-catalog/pull/171
