### ISSUE TITLE
Access control specific to stack/services

### ISSUE THREAD

**Issue by garjunan** [rancher/rancher#5309]
**Rancher Version:** 1.0.1

**Docker Version:** 1.11.1

**OS and where are the hosts located? (cloud, bare metal, etc):** CentOS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** Single node rancher 

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:**  Trying to restrict user on particular stack

**Results:** I have only environment access control for any user and user can do any action based on his role to all stacks under that environment. 

**Expected:**  I wanted to restrict an user to particular stack or services.

**Comment by deniseschannon** [comment]
Related to https://github.com/rancher/rancher/issues/1338

**Comment by garjunan** [comment]
Hi, 
Any tentative date for this fix?

**Comment by amsdard** [comment]
Hi,

my company is also in need to have support for access control per stack. Is this is even on development roadmap?

**Comment by Ilya-Kuchaev** [comment]
+1000

**Comment by driesdroesbeke** [comment]
+1

**Comment by tsvtitan** [comment]
+100
Important issue for us.

**Comment by HenryTheSir** [comment]
+1 would be really nice. 
Maybe step 1 restrict access to user stacks or all stacks without infrastructur.

**Comment by garjunan** [comment]
@deniseschannon  Anyone working on this issue?

**Comment by robertpearce** [comment]
i hate to +1 and all, but this is an important defect.

**Comment by amsdard** [comment]
Is this on any roadmap?

**Comment by fhribeiro** [comment]
+1

**Comment by MatthewJohn** [comment]
+1

**Comment by IvanAR** [comment]
+1

**Comment by adam-janis** [comment]
+1

**Comment by spaxxomatic** [comment]
+1

**Comment by schakko** [comment]
+1

**Comment by vetalpaprotsky** [comment]
+1

**Comment by checksrc** [comment]
+1 - @deniseschannon any thoughts on if this will get implemented?

**Comment by vincent99** [comment]
Not in 1.x.  The scope of access control is an environment.

**Comment by hendrakwong** [comment]
+1

**Comment by bohart** [comment]
+1, this is an important issue in terms of security.

**Comment by vincent99** [comment]
This is (indirectly) part of 2.0 and I said not happening in 1.x.

In 2.0 (preview2+, later this month) a namespace (stack) belongs to a project (environment) which has a cluster (set of hosts) and a set of users that have been assigned roles to be able to manipulate it.  So you create as many projects as you need to separate access to namespaces and security is still at that level.  But they can all share the same physical cluster (unlike 1.x) so there is no hardware overhead to separating things.

**Comment by deniseschannon** [comment]
As this has been introduced into our Tech Preview 2, I'm going to close out the issue. Please file new bugs/enhancements. 

Please watch our [Tech Preview 2 meetup](https://www.youtube.com/watch?v=ld7ctOg3waM&t=4s) to learn more about the changes in 2.0 in Tech Preview 2.
