### ISSUE TITLE
Values in API edit dialog are overflowing modal

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#5312]
**Rancher Version:**
1.1.0

**Steps to Reproduce:**
1. Click "View in API" for some service
2. Click "Edit"

**Result:**
Content of the value column bleeds outside the modal
**Expected:**
Content should wrap

![api-modal-overflow](https://cloud.githubusercontent.com/assets/3813921/16526884/d235bef4-3fb3-11e6-954d-066fc73c7e19.png)

**Comment by vincent99** [comment]
API-UI 1.0.6

**Comment by tfiduccia** [comment]
Version - v1.2.0-pre1-rc3
