### ISSUE TITLE
RancherVM in Rancher 1.1.0

### ISSUE THREAD

**Issue by ppiccolo** [rancher/rancher#5314]
**Rancher Version:**
1.1.0
**Docker Version:**
1.10.3
**OS and where are the hosts located? (cloud, bare metal, etc):**
esxi 5.5
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
external DB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Swarm
**Steps to Reproduce:**
Update from 1.0.2 to 1.1.0
**Results:** 
Support for RancherVM is gone away
**Expected:**
Support for RancherVM like in previous version ...

may be I'm missing something :(

Bye

**Comment by vincent99** [comment]
Enabling VMs had moved from a global setting to a per-environment one.  Edit your environment(s) and choose enable.
