### ISSUE TITLE
Adding proxy to rancher-ha.sh script causes HA to fail

### ISSUE THREAD

**Issue by dsvmacdonald** [rancher/rancher#5315]
**Rancher Version:**
1.1.0
**Docker Version:**
1.10.3
**OS and where are the hosts located? (cloud, bare metal, etc):**
RHEL 7.2
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
1. Setup HA as normal
1. Download rancher-ha.sh script
1. Modify script line starting with ID to include "-e http_proxy="XXX" -e https_proxy="YYY" -e no_proxy="ZZZ"
1. Run script on each node
**Results:** 
Multiple services fail to come up.  Stuck in networking.
**Expected:**
All services to come up and work

**Debugging**
I execed into rancher/agent:v1.0.2, rancher/enterprise:v1.1.0 (rancher-ha container) and rancher/agent-instance:v0.8.3.  All containers contain the correct proxy exports except for rancher/agent-instance:v0.8.3.  It's missing the "no_proxy" export

**Comment by deniseschannon** [comment]
Documentation for proxy for HA will need to be updatd:

To test, update environment variables for proxy in the rancher-ha script. 

```
-e http_proxy="XXX" -e https_proxy="XXX" -e no_proxy="XXX" -e NO_PROXY="XXX"
```

The bridge IP must be in both `-e no_proxy` and `-e NO_PROXY`, which is typically `172.17.0.1`

**Comment by deniseschannon** [comment]
Note: Go-Machine-Service will still not work, but everything else should.

**Comment by deniseschannon** [comment]
@chrisurwin validated that the proxy in the rancher-ha-cattle containers were being set properly.
