### ISSUE TITLE
Local auth configs API timeout

### ISSUE THREAD

**Issue by guodong** [rancher/rancher#5317]
**Rancher Version:**
v1.1.0
**Docker Version:**
1.6.2
**OS and where are the hosts located? (cloud, bare metal, etc):**
local, ubuntu14.04
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Fresh installed rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
None
**Steps to Reproduce:**
API  /v1/projects/1a5/localauthconfigs timeout, while other apis works
**Results:** 
Timeout
**Expected:**
return data

**Comment by tfiduccia** [comment]
@guodong Local auth is not set on a project level and is top level.  I think you want /v1/localauthconfigs.  Try that and see if that is what you are looking for.

**Comment by guodong** [comment]
@tfiduccia yes! 3Q~
