### ISSUE TITLE
Unable to launch AWS EC2 host from rancher WebUI

### ISSUE THREAD

**Issue by zhang8473** [rancher/rancher#5318]
After I restart the rancher server, everything is good. However, I launched too many stacks by API and Rancher server got crashed. I restarted the rancher server (with static public IP) and got the following problem:

**Rancher Version:**
1.0.0
**Docker Version:**
1.10

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu @ AWS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**
launch an AWS host through rancher WebUI.

**Results:** 
"Error setting machine configuration from flags provided: amazonec2 driver requires the --amazonec2-access-key option or proper credentials in ~/.aws/credentials"

**Expected:**
Launch the host

I can launch the instance from my aws account without any problem. All steps are OK. I got this error message after I click "CREATE".

**Comment by deniseschannon** [comment]
What version of Rancher are you running? It is in the lower left corner in the UI.

**Comment by zhang8473** [comment]
I am running rancher v1.0.0

**Comment by deniseschannon** [comment]
There is a known issue with machine drivers that you are facing. Can you upgrade to 1.1? We just released it and it has a fix for your issue.

**Comment by zhang8473** [comment]
I will try later.
1. Other bug is that if the stack is not deployed successfully, e.g. no service is running because of no hosts.
If I use "rancher-compose rm --force" to remove the stack, it will actually do nothing. The stack is still there.

2. Other problem is that "rancher-compose rm --force" cannot remove the stack completely from rancher server. It will leave an empty stack there. This is a big trouble while I am using the API to test my apps. I saw that you were asking an option for that. Are you going to implement it in v1.2? or it is already in v1.1?

Thank you.

**Comment by deniseschannon** [comment]
This is by design. We don't remove stacks as we don't know if there are any services. 

We have an enhancement request: https://github.com/rancher/rancher/issues/1723

**Comment by zhang8473** [comment]
v1.1.0 solved the "~/.aws/credentials" issue.
