### ISSUE TITLE
Cant launch any example from kubernetes

### ISSUE THREAD

**Issue by aldarund** [rancher/rancher#5319]
**Rancher Version:**
1.10
**Docker Version:**
1.10
**OS and where are the hosts located? (cloud, bare metal, etc):**
centos 7
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
signle node 
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes
**Steps to Reproduce:**
First i was experiencing this -> https://github.com/rancher/rancher/issues/5316#issuecomment-230128804
After few recreation of node hosts ( using same settings nothing changed) i got a setup that launched and have all service in working state ( well at least thats what rancher saying)
But then i tried to launch guestbook example and rabbitmq example. And it didnt worked.
No errors,but nothing worked.
The proper record appeared in Kubernetes\Services and Kubernetes\Replication Controllers.
E.g.
```
 frontend	LoadBalancer	10.43.31.232	0	80:80/tcp	name=frontend	 
 kubernetes	ClusterIP	10.43.0.1	0	443:443/tcp	None	 
 rabbitmq	ClusterIP	10.43.13.149	0	5672:5672/tcp	provider=rabbitmq	 
 redis-master	ClusterIP	10.43.106.144	0	6379:6379/tcp	name=redis-master	 
 redis-slave	ClusterIP	10.43.120.108	0	6379:6379/tcp	name=redis-slave
```
But they all listing 0 pods. And Kubernetes/pods also show nothing.
Im just trying to see some basic thing and how rancher works, but running into this issues. Is it so unstable? 
In kubectl logs im seeing following:
```
 FailedCreate   Error creating: pods "redis-slave-" is forbidden: no API token found for service account default/default, retry after the
 token is automatically created and added to the service account
```
Dont have idea how to fix it,and what is wrong since all setup was done using rancher web interface..

**Comment by deniseschannon** [comment]
I am able to unproduce this issue. I have no issues with launching examples.

Can you try changing your environment to cattle and changing it back to k8s? It will re-launch the k8s system services to see if that fixes it.

**Comment by deniseschannon** [comment]
@aldarund If you still have issues, please reopen.
