### ISSUE TITLE
Load balancer does not show up on host panel

### ISSUE THREAD

**Issue by truongdo** [rancher/rancher#5320]
The load balancer seems to function properly; it showed up on stack window,
but does not show up on the host window.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.1.0` Cattle: `v0.165.4` UI: `v1.1.12` |
|Access|`github` `admin`|
|Orchestration|`Cattle`|
|Route|`environments.index`|

**Comment by willseward** [comment]
Do you have the "Show System" tick box ticked?

![screen shot 2016-07-03 at 12 45 33 pm](https://cloud.githubusercontent.com/assets/5386568/16546803/13e9da2e-411c-11e6-9e1d-acd60f6f7cdc.png)

**Comment by truongdo** [comment]
Oh, is that a new UI feature from the version 1.1.0? It is not easy to realize that function. Anyway, it works now! Thanks.
