### ISSUE TITLE
API filtering malfunction

### ISSUE THREAD

**Issue by Crazy-Hopper** [rancher/rancher#5321]
Filtering (e.g. for names) in API works for environments (i.e. stacks) but not for services within the stack.

---

| Useful | Info |
| :-- | :-- |
| Versions | Rancher `v1.1.0` Cattle: `v0.165.4` UI: `v1.1.12` |
| Access | `localauth` `admin` |
| Orchestration | `Cattle` |
| Route | `environments.index` |

**Comment by Crazy-Hopper** [comment]
Probably a duplicate of #3847

**Comment by jzakrzeski** [comment]
I've run into this as well. Filtering works fine for projects and environments, but not for services: it just returns the whole stack.

i.e.: http://rancher.local:8080/v1/projects/1a7/environments/1e111/services?name=rate-limit-service will return the same exact data as http://rancher.local:8080/v1/projects/1a7/environments/1e111/services

Info:

Component | Version
--------- | -------
Rancher | v1.1.2
Cattle | v0.165.8
User Interface | v1.1.12
Rancher Compose | v0.8.6

**Comment by vincent99** [comment]
@jzakrzeski yes the sub-resource selection ( services of environment 1e111) is a form of filter and takes precedence instead of intersecting.

/v1/projects/1a7/services?environmentId=1e111&name=rate-limit-service

Will work.

**Comment by EyMaddis** [comment]
Same goes for settings. Both `/v1/settings?name_eq=lb.instance.image` and `/v2-beta/settings?name_eq=lb.instance.image` return all results.

**Comment by vincent99** [comment]
@EyMaddis That's a similar but different problem... but the name is also the ID for settings, so you can use `/v2-beta/settings/lb.instance.image`.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
