### ISSUE TITLE
can not build docker/server image

### ISSUE THREAD

**Issue by mj19910923** [rancher/rancher#5322]
75---> Using cache 
76---> 736d3b3d065a 
**77 Step 16 : COPY target/*static.tar.gz /s6-statics/** 
78 No source files were specified 
79 {"exitCode":8, "message":"docker build failed or timeout "}

**Comment by deniseschannon** [comment]
1. I am assuming you mean rancher/server.
2. Which file are you using?

**Comment by deniseschannon** [comment]
@mj19910923 If you have further questions, please reopen.
