### ISSUE TITLE
Certificate isn't integrated in rancher-ha.sh when it is generated

### ISSUE THREAD

**Issue by saphoooo** [rancher/rancher#5323]
**Rancher Version:**
v1.1.0
**Docker Version:**
Docker version 1.10.3, build 20f81dd
**OS and where are the hosts located? (cloud, bare metal, etc):**
RancherOS v0.4.5
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Sigle or three nodes HA with external DB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
Just trying to enable HA with my company certificate
**Results:** 
The certificate isn't included in the script:
```
# Uncomment below to force HA enabled and not require one to set it in the UI
# export CATTLE_HA_ENABLED=true
EOF




echo Creating /var/lib/rancher/etc/server/encryption.key
if [ -e /var/lib/rancher/etc/server/encryption.key ]; then
    mv /var/lib/rancher/etc/server/encryption.key /var/lib/rancher/etc/server/encryption.key.`date '+%s'`
```
**Expected:**
To have the certificate in the script as expected

**Comment by aemneina** [comment]
duplicate issue: https://github.com/rancher/rancher/issues/5311
we can track progress on that one.
