### ISSUE TITLE
container hostname override not working with network=host

### ISSUE THREAD

**Issue by jloisel** [rancher/rancher#5325]
**Rancher Version:** v1.1.0, v1.0.2, v1.0.1

**Docker Version:** 1.11.2

**OS and where are the hosts located? (cloud, bare metal, etc):** Bare-metal, with server and agent on  the same machine.

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single node rancher with internal DB.

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:**
Create an ubuntu container with the following network settings:
- Network mode: host
- hostname: anything you want

We are also creating containers via the REST api with "hostname" field being set, and "io.rancher.container.hostname_override": "container_name"" label with no success in network=host.

**Results:** 
When sshing into the container, echo $HOSTNAME and "hostname" command show the agent host name, not the previously entered hostname.

**Expected:**
Container $HOSTNAME and hostname command should return the previously configured hostname.

**Comment by cloudnautique** [comment]
Hello, this is actually an underlying Docker'ism. Not sure if its a bug or not, but I'm wondering if docker sets the hostname then processes the workflow for net: host which then overwrites /var/lib/docker/containers/<id>/hostname file. 

 If you were to run `docker run -it --net host --hostname foo ubuntu bash` you will end up with hostname still returning the hosts hostname.

**Comment by jloisel** [comment]
Maybe the best solution would be to gray out / hide hostname override when network=host is selected to avoid any misunderstanding. I thought Rancher was managing the container's hostname.

We ended up switching to bridged network mode to get the proper hostname in the container.

**Comment by deniseschannon** [comment]
Available with `v1.6.15-rc6`

**Comment by tfiduccia** [comment]
Version - v1.6.15-rc6
Verified fixed

**Comment by jloisel** [comment]
Better late than never! :+1:

**Comment by hanyong** [comment]
I have tested docker-ce 17.06.2, which will set hostname correctly with `--net=host`。

```
# docker version
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 20:00:17 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:59:11 2017
 OS/Arch:      linux/amd64
 Experimental: false

# docker run --name=test --rm -ti --net=host --hostname=test ubuntu:16.04 /bin/bash
root@test:/# hostname
test
```

I want use rancher container hostname override for host network mode, but it looks like not work now. could this feature be re-enabled with modern docker version?
