### ISSUE TITLE
gitlab.com registry login not working with rancher ui (docker-compose works)

### ISSUE THREAD

**Issue by ramden** [rancher/rancher#5328]
Rancher Version: v1.1.0-dev5
Docker Version: 1.10.3
OS and where are the hosts located? (cloud, bare metal, etc): bare metal
Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB) sindle node rancher, internal DB
Environment Type: (Cattle/Kubernetes/Swarm/Mesos) Cattle

Possible duplicate of https://github.com/rancher/rancher/issues/5198 (issue still exists)

The setting in rancher registry (repositories->custom) is without http(s):// . 
Upon creation of container gives me : Error (500 Server Error: Internal Server Error ("Get https://registry.gitlab.com/v2/MYUSERNAME/REPOSNAME/manifests/latest: nil"))

To reproduce:
1. Push an image to to a gitlab registry (on a private project)
2. In rancher ui go to registry and add this custom registry with username password email
3. Create a service in rancher using the image url uploaded to gitlab.com
4. Error (500 Server Error: Internal Server Error ("Get https://registry.gitlab.com/v2/MYUSERNAME/REPOSNAME/manifests/latest: nil"))

**Comment by ramden** [comment]
Temporary solution:
1. Pull image locally on host (via terminal)
2. Set "Automatic pull image" on container to off

**Comment by deniseschannon** [comment]
When adding the custom registry, did you make sure to not include `http` or `https` in the address? We automatically prepend the address with it and it won't work if you add it yourself.

**Comment by ramden** [comment]
> The setting in rancher registry (repositories->custom) is without http(s):// .

**Comment by dj-hedgehog** [comment]
Please check for leading or trailing spaces in the repository-adress, username and password.
This used to be my problem. They don't get stripped and are difficult to spot.

I'm running a self-hosted Gitlab instance and its registry with SSL termination through a front-facing Nginx. Rancher can pull from it without any problems.

**Comment by ramden** [comment]
No trailing spaces. I checked it right away, recreated repository, still same error when pulling image. Could it be there is something specific with gitlab.com vs self hosted?

**Comment by ramden** [comment]
How to change this to a bug?

**Comment by xar** [comment]
i'm experiencing same issue. I have selfhosted gitlab and everytime a try to create service from UI i get

Error (500 Server Error: Internal Server Error ("Get https://registry.domain.com:7443/v2/root/jenkins-test/manifests/latest: error parsing HTTP 403 response body: no error details found in HTTP response body: "{\"message\":\"forbidden\",\"status\":\"error\",\"http_status\":403}""))

**Comment by dvanwinkle** [comment]
@ramden I was getting the same thing, but then realized that you actually need to use your username/password and cannot use a personal access token. This is true even if you have 2 factor auth turned on.

**Comment by wadjeroudi** [comment]
woks for me.
Feature request : allow unsigned ssl for custom docker registry. (maybe a checkbox to add on the UI).

**Comment by superseb** [comment]
I believe this has been fixed in later versions, please submit a new issue if you are still experiencing problems on newer versions.
