### ISSUE TITLE
Container names revert from UUID to stack_service name

### ISSUE THREAD

**Issue by roflmao** [rancher/rancher#5329]
**Rancher Version:**
1.0.2

**Docker Version:**
1.11.1

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 14.04, bare metal

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher, internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**

```
7126ee6f61dd        logstash:2.3.2                      "/docker-entrypoint.s"   7 days ago          Up 6 days           0.0.0.0:5140-5141->5140-5141/udp, 0.0.0.0:5144-5156->5144-5156/udp, 0.0.0.0:5142-5143->5142-5143/tcp   e6778b00-63fb-403b-a81d-0f4a31b13b4f
```

Did upgrade of container to export new ports.

```
d6f615c41c91        logstash:2.3.2                      "/docker-entrypoint.s"   1 seconds ago       Up Less than a second   0.0.0.0:5140-5141->5140-5141/udp, 0.0.0.0:5142-5143->5142-5143/tcp, 0.0.0.0:5144-5152->5144-5152/udp, 0.0.0.0:5155-5156->5155-5156/udp, 0.0.0.0:5153-5154->5153-5154/tcp   r-logstash-2_logstash_1
```

**Results:** 
docker container name changed from e6778b00-63fb-403b-a81d-0f4a31b13b4f to r-logstash-2_logstash_1

**Expected:**
Names to always be r-logstash-2_logstash_1 in docker since this is the stackname, containername in Rancher.

**Comment by ebr** [comment]
+1; Have also been seeing this on all versions of Rancher so far - thanks for opening the issue

**Comment by deniseschannon** [comment]
This sounds very similar to https://github.com/rancher/rancher/issues/4993

Had you previously upgraded this service and that's why it originaly had UUID?

**Comment by roflmao** [comment]
This happens in regards of upgrade yes. I will try to locate the pattern in of when the name changes.

**Comment by goffinf** [comment]
Clearly this is a major problem when linking containers which is the issue I face. I need a consistent name that I can use that survives service upgrades (I have noticed the name switch from the elected name to a UUID and then back again on subsequent upgrades but it doesn't appear to be completely repeatable so may be a form of race condition ?). Anyways, really need this one to be fixed ASAP.

**Comment by deniseschannon** [comment]
In 1.2 they will consistently be r-{container name}-{first segment of uuid}.

**Comment by soumyalj** [comment]
Tested with v1.2.0-pre4-rc7. The container names remained in the format r-{container name}-{first segment of uuid} before and after upgrade
Before upgrade:
```
4f5ecb717cc6        busybox                         "/.r/r sleep 1000"       25 minutes ago      Up 9 minutes                                    r-logtestnew-test-1-22658493
```
After upgrade:
```
77cde00dcefb        busybox                         "/.r/r sleep 1000"       17 seconds ago      Up 16 seconds                                   r-logtestnew-test-1-3802d326
```
