### ISSUE TITLE
[rancher-compose] CLI doesnt return prompt when starting stack

### ISSUE THREAD

**Issue by soumypau** [rancher/rancher#5330]
**Rancher Version:*v1.1.0-dev3*

**Docker Version:*1.11.2*

**OS and where are the hosts located? (cloud, bare metal, etc):*Local DC, RHEL 7.2*

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)*Single Node Rancher*

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)*Cattle*

**Steps to Reproduce: **
./rancher-compose --url <rancher url> --access-key <access key> --secret-key <secret key> --file <compose_file.yml> --project-name <environment name> up

**Results:** The stack comes up fine in rancher, however in CLI, the OS prompt never comes back

**Expected:** The OS prompt should come back

**Comment by vincent99** [comment]
This works the same way as docker-compose and shows you the log output of the containers until terminated.  If you want to exit automatically, pass`-d` to the `up`command.
