### ISSUE TITLE
Misspelling in "add project" window 

### ISSUE THREAD

**Issue by kubadawczynski** [rancher/rancher#5331]
In "add Project" window is misspelling.

You have "dcoker-compose.yml" instead docker-compose.yml

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.1.0` Cattle: `v0.165.4` UI: `v1.1.12` |
|Access|`openldap` `admin`|
|Orchestration|`Swarm`|
|Route|`swarm-tab.projects.new`|

**Comment by tfiduccia** [comment]
Version - master 8/2
Verified fixed
