### ISSUE TITLE
Load balancer is not scheduling on all hosts as expected

### ISSUE THREAD

**Issue by pulberg** [rancher/rancher#5332]
**Rancher Version:** 1.1.0

**Docker Version:** 1.11.2

**OS and where are the hosts located? (cloud, bare metal, etc):** RancherOS v0.5.0, AWS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** Single node Rancher, RDS DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:**  In a multi-host env, I have a stack with a service and an LB.  I have a scheduling rule set so that an instance of the service and LB are created on each host.

**Results:** After upgrading a host to RancherOS v0.5.0, the stack comes up, but the LB is stuck "initializing", if I reboot the LB it then disappears from the stack.

**Expected:** LB should not disappear from stack.

![image](https://cloud.githubusercontent.com/assets/11069351/16594062/219a1ea2-42ae-11e6-977a-85a76c7a3924.png)

**Comment by deniseschannon** [comment]
Prior steps:
1. v1.0.2 Rancher set up with v0.4.5 RancherOS hosts. Launched with a global load balancer scheduled using host labels
2. Deactivate host. 
3. Upgrade host in backend from v0.4.5 to v0.5.0 
4. Re-activate host

When a host was inactive state, the label on the host was removed. The only thing changing in the host was that the host was upgraded.

Note: I cannot consistently reproduce this, but saw it happen in this setup.

Upon re-activating the host, the host label still remained in the UI/API, but the host label had been removed in the DB. 

Note: we should look into syncing with the host label map of a host upon re-activation.

**Comment by deniseschannon** [comment]
@pulberg I've been trying to reproduce this issue recently on our master setup for 1.2.0-pre4 and have never seen it after many different combinations of upgrades using different versions of RancherOS with different versions of Docker. 

In 1.2.0, we've implemented a new scheduler. If you see this again, can you please let me know? I'm going to close it. 

Also, let me know if you've had any issues while upgrading to the latest versions of RancherOS.
