### ISSUE TITLE
Add personal ssh keys into docker-machine commands

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#5334]
Add ability to add in your own ssh keys when provisioning hosts through the UI (that calls docker-machine).

**Comment by vincent99** [comment]
How exactly are we planning to do this?  There is no option to use existing keys at all in many of the drivers.  For the ones that do, they take a reference to the key ID in their API, which we would have to keep in sync with the one in our database somehow.

**Comment by inabhi9** [comment]
@vincent99 One way I can think of is to spin up the machine with new ssh key and once the machine is up inject the user key as well

**Comment by vincent99** [comment]
From the future (#14330):

> IF we were to support injecting user supplied public keys, it would be: 
>  - Create a new resource type for sshPublicKey and assod screens to manage them.
>  - Add an option to node(outside of driver config) to select the ones you want to put into the node/host.
>  - Have the docker-machine driver (continue to) generate its own keypair for bootstrapping
>  - Add the selected public keys to authorized_keys as part of the bootstrap process.
