### ISSUE TITLE
Ability to manage/save credentials for various cloud providers

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#5335]
Currently, when adding a host, you need to always provide your access key/secret key (aka API keys) for the different cloud providers.

If you clone an existing host, it would copy them over, but Rancher should have the ability to save and easily retrieve these keys inside of Rancher.

**Comment by machbio** [comment]
Any Progress on this - really improves the security around AWS Environment - we have Key rotation policies - so will have to re-enter the keys every 90 days.
