### ISSUE TITLE
Cancelling out of a system stack action goes back to user stacks

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#5336]
**Rancher Version:**
v1.1.0

**Steps to Reproduce:**
1. Create a system service
2. Go to system stack page
3. Select upgrade for the service
4. Click on Cancel

**Results:** 
Redirects to the user stack page, which is confusing. 

**Expected:**
Redirects to system stack page as it was from a system service.

**Comment by tfiduccia** [comment]
Same with Clone

**Comment by vincent99** [comment]
n/a to 2.0.
