### ISSUE TITLE
Suggestion : Infrastructure Abstraction Layer

### ISSUE THREAD

**Issue by kvaes** [rancher/rancher#5338]
I would see an advantage in having a way to split up the duties of adding hosts.

**Scenario**
One role I would see as an "admin" who has all the technical details (configuration, keys, etc) that (s)he can proactively configure for each environment. This info will then be fed (transparently) to the machine drivers. The other role ("user") will be able to create machines, where (s)he will not see the predefined configuration.

**Value Proposition**
- Security : Your typical "seggregation of duties". Not all users are always granted access to the keys to deploy stuff.
- Ease of use : The configuration will have been validated / tested, so that common errors are not repeated by (new) users.
- Hosting : Will enable hosters to deploy a CaaS based on Rancher.

**Enhancements**
- A configurable quota for each machine driver (budget control)

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
