### ISSUE TITLE
access to client ip in kubernetes on rancher

### ISSUE THREAD

**Issue by colmaengus** [rancher/rancher#5340]
**Rancher Version:**
1.1.0-dev5
**Docker Version:**
1.11
**OS and where are the hosts located? (cloud, bare metal, etc):**
ubuntu 14.04 on AWS
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

What is the correct procedure for accessing a k8s service externally ?
I'm currently using "type: LoadBalancer" in a k8s service and a load balancer has been created and I'm able to access the server externally. The service itself is actually nginx based and is acting as a reverse proxy. I need to be able to access the client ip address. I've configured the following nginx directives:
X-Real-IP -> $remote_addr
X-Forwarded-For -> $proxy_add_x_forwarded_for
Both get 10.42.0.1 (internal k8s ip address)

Is there something else I should be doing ? Or doing something else entirely ?

**Comment by deniseschannon** [comment]
We recommend using [Kubernetes ingress](http://kubernetes.io/docs/user-guide/ingress/), which Rancher has support.

http://docs.rancher.com/rancher/latest/en/kubernetes/ingress/

**Comment by deniseschannon** [comment]
@colmaengus If you have further questions, please re-open.
