### ISSUE TITLE
Rancher Load Balancer Cookie Server Id

### ISSUE THREAD

**Issue by guiguan** [rancher/rancher#5341]
Hi,

I found that those cookie id values (`f18c70cf-f899-457e-ad1a-4c44546cfad9` and `56bb53ff-9f9d-43dd-9ca7-be9a959622ee` in following example) assigned to backend servers are quite random, where they are not corresponding to any Rancher resource id. 

```
backend 4b0bb0b1-267b-45a2-b13d-081e9dc8524e_443_0_backend
        mode http
        cookie sticky insert domain my.domain.com
        server f18c70cf-f899-457e-ad1a-4c44546cfad9 10.42.6.217:8080 cookie f18c
70cf-f899-457e-ad1a-4c44546cfad9
        server 56bb53ff-9f9d-43dd-9ca7-be9a959622ee 10.42.112.237:8080 cookie 56
bb53ff-9f9d-43dd-9ca7-be9a959622ee
        http-request add-header X-Forwarded-Proto https if { ssl_fc }
```

How does Rancher generate them? Can I access them somehow from Rancher's API?

Cheers,
Guan

**Comment by Shuliyey** [comment]
:+1:

**Comment by Shuliyey** [comment]
+1

**Comment by deniseschannon** [comment]
The cookie server Id is the uuid that can be found in the serviceexposemap link of a service.

Click on "View in API" of your target service. Under links, click on "serviceexposemap" and then you should find the uuid in that link.

This will be changed and more clear on what it is after #2179 is completed.

**Comment by guiguan** [comment]
@deniseschannon awesome, thanks!
