### ISSUE TITLE
Non-ascii character support for docker & rancher yml

### ISSUE THREAD

**Issue by BlackTazz89** [rancher/rancher#5342]
**Rancher Version:**
v1.1.0
**Docker Version:**
 1.10.3
**OS and where are the hosts located? (cloud, bare metal, etc):**
centos7
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle v0.165.4
**Steps to Reproduce:**
Set an answer to a non ascii character like "è"
**Results:** 
Rancher during the .yml parsing will throw "Failed to unmarshal Map or Slice: <nil>" and the character will be encoded as "xE?"
If you set the value to \u00e8 (unicode rapresentation of "è") no error will be thrown
**Expected:**
I will expect to set the special character and proper encoding should be performed.

**Comment by BlackTazz89** [comment]
Sorry but I don't think this is an enhancement, I wanted to report it as a bug.
With a non ascii character rancher-compose will always stop working and it's impossible to deploy.

**Comment by djcenox** [comment]
+1

**Comment by tfiduccia** [comment]
For QA - all three hyphens should be supported:

Regular: -
Option + hyphens: –
two hyphens: —

All non-ascii character should be supported for example:
œ∑˙ß®∫ƒ˜†∂˜

**Comment by tfiduccia** [comment]
Make sure to test with Chinese as well - here is the related issue #5414

**Comment by sangeethah** [comment]
Tested with rancher-server version - v1.2.0-pre2-rc2 and rancher-compose version - v0.9.1-rc .

Having Non-ascii characters in docker-compose.yml and rancher-compose.yml works as expected.
Following are some of Non-ascii characters tested with:
"œ∑˙ß®∫ƒ˜†∂˜"
"±èéü−−∠∫∴♥Œ♦‰"
"–a—"
