### ISSUE TITLE
Set authorization on Catalogs

### ISSUE THREAD

**Issue by saphoooo** [rancher/rancher#5343]
**Rancher Version:**
enterprise:v1.1.0
**Docker Version:**
0.10.3
**OS and where are the hosts located? (cloud, bare metal, etc):**
RancherOS 0.45, cloud provider
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
rancher HA
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**RFC**
I have not a multi tenant env. but nearly.
So I avec different Catalog in Cattle, and I would like manage authorizations on Catalogs, who can see kind of catalog, who cannot in the same environnment.

**Comment by deniseschannon** [comment]
A potential use case for RBAC. 

https://github.com/rancher/rancher/issues/1338


Note: we are planning to add in separate catalogs for each environment: https://github.com/rancher/rancher/issues/3158

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
