### ISSUE TITLE
Support AWS Elastic File Store for Convoy Storage

### ISSUE THREAD

**Issue by schuylr** [rancher/rancher#5344]
**Rancher Version:** 1.0.1

**Docker Version:** 1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):** RancherOS on AWS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** External DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:**

AWS provides this command to connect to an EFS:

```
sudo mount -t nfs4 -o nfsvers=4.1 $(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone).fs-abcde12345.efs.us-east-1.amazonaws.com:/ efs
```

I try to set `$(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone).fs-abcde12345.efs.us-east-1.amazonaws.com` as my NFS Server.

**Results:** 

The logs show an error with the `mount` command format. I suspect that `curl` is not installed on `rancher/convoy-agent`. Setting the host manually to my availability zone that I know my one server to be on does work, however.

**Expected:**

I'd like `curl` to be installed so I can work with Amazon's metadata service to connect to the EFS DNS path appropriate for the server's availability zone.

**Comment by alex88** [comment]
This PR seems to fix the problem https://github.com/rancher/convoy-agent/pull/29

If you're in a hurry like me you can use this image https://hub.docker.com/r/alex88/convoy-agent-efs/

**Comment by alex88** [comment]
@deniseschannon related PR has been merged on Aug 10, this issue could be closed
