### ISSUE TITLE
Unable to launch AWS EC2 hosts with RancherOS from WebUIs

### ISSUE THREAD

**Issue by zhang8473** [rancher/rancher#5350]
**Rancher Version:**
1.1.0
**Docker Version:**
not on this step
**OS and where are the hosts located? (cloud, bare metal, etc):**
rancherOS ami-f0f03190 @ AWS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
clone or launch several hosts together e.g. 4-8

**Results:** 
Error running provisioning: Something went wrong running an SSH command!
or
Error checking the host: Error checking and/or regenerating the certs: There was an error validating certificates for host "52.41.198.67:2376": dial tcp 52.41.198.67:2376: i/o timeout

**Expected:**
Host is launched.

I can launch Ubuntu 14.04.3 LTS (AWS suggested OS) without any problem.

**Comment by deniseschannon** [comment]
Did you make sure to update the username as "rancher" if using the RancherOS AMI?

**Comment by zhang8473** [comment]
Of course I did make sure the user is `rancher`. Actually even if I use Ubuntu OS and if I launch 8 hosts, some of the hosts show the same error message.

**Comment by deniseschannon** [comment]
We are just calling `docker-machine` to launch the hosts through the UI. Have you tried going in to the Rancher/server logs to grab the same docker-machine command to see if it works on your host? 

Your errors look like `docker-machine` errors.

**Comment by deniseschannon** [comment]
@zhang8473 If you have further questions, please reopen.
