### ISSUE TITLE
[UI] Infrastructure view for System HA stacks also includes non-system HA hosts

### ISSUE THREAD

**Issue by johnrengelman** [rancher/rancher#5353]
**Rancher Version:** 1.1.0-dev5

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Rancher HA with 3 hosts

**Steps to Reproduce:**
1. Deploy HA cluster with 3 servers
2. Add an environment with at least 1 host
3. Select Admin | High Availability.
4. Select the Infrastructure tab

**Results:** 

The select environment is System HA and hosts are shown.
The list of hosts includes both the HA servers (3 instances) plus the hosts of the previously selected environment.

**Expected:**

Only the HA hosts (servers) should be shown.

I noted that requesting the URL for the System HA stack (https://rancher.mydomain.io/v1/projects/<system ha stack id>/hosts) returns only the System HA hosts. So something else on the Infrastructure tab is requesting hosts from a different environment and they are being merged together.

**Comment by johnrengelman** [comment]
Once on the Infrastructure tab, if I do a browser refresh, then only the System HA hosts are displayed.

**Comment by vincent99** [comment]
Going into the HA page is changing the selected env/project to System HA but not clearing the browser store of all the other records from the previous env...

**Comment by vincent99** [comment]
No longer applies in 1.2, HA is configured by CLI.
