### ISSUE TITLE
[UI] [Catalog] Some catalog templates render README contents incorrectly

### ISSUE THREAD

**Issue by johnrengelman** [rancher/rancher#5354]
**Rancher Version:**
1.1.0

**Docker Version:**

**OS and where are the hosts located? (cloud, bare metal, etc):**
cloud, ubuntu

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA, 3 hosts
Private Catalog using https URL to Github.

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Not sure. Here are `README.md` contents for 2 versions of a template...

rendered wrong

```
# Host Metrics

This stack deploys the Telegraf agent to the host machine to collect metrics.
Telegraf will collect host level metrics such as:
* CPU
* Disk
* Memory

Additionally, Telegraf will attach to the Docker socket and provided container level metrics.
```

rendered correct

```
# Host Metrics

This stack deploys the Telegraf agent to the host machine to collect metrics.
Telegraf will collect host level metrics such as:
* CPU
* Disk
* Memory

Additionally, Telegraf will attach to the Docker socket and provided container level metrics.

The Telegraf instance also configures the UDP input listener to accept arbitrary metrics to forward.
This is useful for applications that are scheduled to this host as they can publish metrics to Telegraf to be forwarded.
The UDP listener by default attaches to host port 8092.
When publishing to this port from a Docker container, the container must publish to the host interface IP address, **not** `localhost`.
This will typically be the IP of the `docker0` bridge: `172.17.0.1`.
```

**Results:** 

Incorrectly rendered markdown
<img width="1905" alt="screen shot 2016-07-07 at 3 41 42 pm" src="https://cloud.githubusercontent.com/assets/1012772/16669104/5fbc7a5c-4459-11e6-8f7e-2c6dc3bfba66.png">

**Expected:**

Correctly rendered markdown
<img width="1903" alt="screen shot 2016-07-07 at 3 41 51 pm" src="https://cloud.githubusercontent.com/assets/1012772/16669115/6e02c166-4459-11e6-8246-f61392299674.png">

**Comment by johnrengelman** [comment]
Hmm, after playing around in the API endpoint (https://rancher.connectedfleet.io/v1-catalog/templates/peoplenet:monitoring-hosts:0?readme), this somehow updated and the UI component is now rendered correctly.

Maybe some type of cache? Though this occurred through an update of the cluster to a new version.

**Comment by deniseschannon** [comment]
@johnrengelman We've had some changes in the UI regarding upgrading templates in our 1.2.0 series, so let me know if see this issue in that version.

**Comment by aemneina** [comment]
closing this issue, if you see this in 1.2 onwards, can you file a new issue or reopen this one @johnrengelman ?
