### ISSUE TITLE
Cross host communication failure

### ISSUE THREAD

**Issue by nunofgs** [rancher/rancher#5365]
**Rancher Version:**
1.1.0.

**Docker Version:**
1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
amazon.

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher.

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
cattle.

**Problem description:**

This is the state of our load balancers today (one lb per host):

<img width="370" alt="screen shot 2016-07-08 at 13 01 20" src="https://cloud.githubusercontent.com/assets/92085/16686747/28a87a8a-450c-11e6-8da7-4a196e37049d.png">

I executed a shell on the "network agent" of that last host and did:

``` sh
$ cat /var/log/rancher-net.log | grep error
time="2016-07-08T11:59:02Z" level=error msg="Failed to add policy: {Dst:10.42.0.
0/16 Src:10.42.121.156/32 Dir:dir fwd Priority:10000 Index:0 Tmpls:[{Dst:172.17.
0.2 Src:172.19.48.75 Proto:esp Mode:tunnel Reqid:1234}]}, file exists"
time="2016-07-08T11:59:07Z" level=error msg="Failed to add policy: {Dst:10.42.12
1.156/32 Src:10.42.0.0/16 Dir:dir out Priority:10000 Index:0 Tmpls:[{Dst:172.19.
48.75 Src:172.17.0.2 Proto:esp Mode:tunnel Reqid:1234}]}, file exists"
time="2016-07-08T11:59:07Z" level=error msg="Failed to add policy: {Dst:10.42.0.
0/16 Src:10.42.121.156/32 Dir:dir fwd Priority:10000 Index:0 Tmpls:[{Dst:172.17.
0.2 Src:172.19.48.75 Proto:esp Mode:tunnel Reqid:1234}]}, file exists"
time="2016-07-08T11:59:07Z" level=error msg="Failed to add policy: {Dst:10.42.0.
0/16 Src:10.42.121.156/32 Dir:dir in Priority:10000 Index:0 Tmpls:[{Dst:172.17.0
.2 Src:172.19.48.34 Proto:esp Mode:tunnel Reqid:1234}]}, file exists"
```

There are hundreds more lines like that.

Any ideas on what the issue could be? Is there any way to get a bit more verbosity on that "file exists" error?

**Comment by nunofgs** [comment]
We managed to fix it. If you'll notice in the log I pasted above, the container ip that is failing is `10.42.121.156`.

We noticed that this container ip is nowhere to be found on that machine. We killed the machine and the error stopped.

It looks like that machine was announcing a container ip multiple times, and that container didn't even exist.

Sounds like a rancher-net/cattle bug, but very hard to reproduce.

**Comment by leodotcloud** [comment]
@nunofgs The latest release of Rancher (1.2.x) has a lot of changes in networking. Could you please try this version and let us know if you are still facing this issue?

**Comment by leodotcloud** [comment]
@nunofgs Ping. (Try 2)

**Comment by nunofgs** [comment]
@leodotcloud: I was never able to reliably reproduce this issue. Please go ahead and close this.
