### ISSUE TITLE
Show container's View Logs window in full screen

### ISSUE THREAD

**Issue by averri** [rancher/rancher#5366]
As a user of Rancher, I would like to see the View Logs window in full screen mode.

---

| Useful | Info |
| :-- | :-- |
| Versions | Rancher `v1.1.0` Cattle: `v0.165.4` UI: `v1.1.12` |
| Access | `localauth` `admin` |
| Orchestration | `Cattle` |
| Route | `container.labels` |

**Comment by vincent99** [comment]
In 2.0.
