### ISSUE TITLE
Show container's Execute Shell window in full screen

### ISSUE THREAD

**Issue by averri** [rancher/rancher#5367]
As a user of Rancher, I would like to see the container's Execute Shell window in full screen.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.1.0` Cattle: `v0.165.4` UI: `v1.1.12` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`container.labels`|

**Comment by tfiduccia** [comment]
Duplicate #2182 - Closing
