### ISSUE TITLE
Trouble getting HA working with AWS ELB with non-standard mysql port

### ISSUE THREAD

**Issue by jclark360** [rancher/rancher#5368]
**Rancher Version:**
latest

**Docker Version:**
Docker version 1.11.2, build b9f10c9

**OS and where are the hosts located? (cloud, bare metal, etc):**
ubuntu 14.04 lts

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
ha rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
none yet 

**Steps to Reproduce:**
Followed this http://docs.rancher.com/rancher/latest/en/installing-rancher/installing-server/multi-nodes/ and get the error below from every node

**Results:** 
time="2016-07-08T12:34:54Z" level=info msg="Can not launch agent right now: Server not available at http://172.17.0.1:18080/ping:" component=service
time="2016-07-08T12:34:59Z" level=info msg="Waiting for server to be available" component=cert

**Expected:**
agent launches and self configures?

**Comment by jclark360** [comment]
Note that I have setup the AWS ELB with the ProxyPort policy for 81 and 444.  We are using a real cert, that has been entered into the rancher admin before generating config and is present on the ELB.  I read through https://github.com/rancher/rancher/issues/4634 but am unsure what in there should be done that isn't in the docs.  I did run the test on zookeeper and get the same issue that is present in that thread where 2181 isn't serving requests.

**Comment by chrisurwin** [comment]
I'm assuming that you are terminating SSL at the ELB in which case you don't need to enter the certs into the UI?
On the ELB you need to have the listener set up as SSL 443 forwarding to TCP 81

**Comment by jclark360** [comment]
I have the cert entered on the elb for ssl 443.  I guess that means is terminating there?  The UI only has 2 options though for HA, generate self signed and enter cert.  I assumed it still wanted the cert there?

**Comment by chrisurwin** [comment]
You can ignore it, if you are running with Rancher 1.1.0 then there is a known issue where it doesn't embed the certs anyway.

**Comment by jclark360** [comment]
Getting this now...

Status: Downloaded newer image for rancher/agent:v1.0.2
time="2016-07-08T15:16:30Z" level=info msg="Container agent is not running in state &types.ContainerState{Status:\"exited\", Running:false, Paused:false, Restarting:false, OOMKilled:false, Dead:false, Pid:0, ExitCode:0, Error:\"\", StartedAt:\"2016-07-08T15:16:16.646696826Z\", FinishedAt:\"2016-07-08T15:16:27.503706577Z\"}" component=docker
time="2016-07-08T15:16:30Z" level=info msg="Deleting container ac72979a61c57e4e98468c40d6125f5550c135ebd9a5441cb3fa0813e055651a" component=docker
time="2016-07-08T15:16:30Z" level=info msg="Can not launch agent right now: Error response from daemon: Unable to remove filesystem for ac72979a61c57e4e98468c40d6125f5550c135ebd9a5441cb3fa0813e055651a: remove /mnt/docker/containers/ac72979a61c57e4e98468c40d6125f5550c135ebd9a5441cb3fa0813e055651a/shm: device or resource busy" component=service

**Comment by jclark360** [comment]
Note that docker was clean before starting no images etc.

**Comment by chrisurwin** [comment]
this is the log from running docker logs -f rancher-ha?
Has it spawned any other containers?

**Comment by jclark360** [comment]
time="2016-07-08T15:15:12Z" level=info msg="Cluster changed, index=0, members=[10.10.18.53, , ]" component=service
time="2016-07-08T15:15:12Z" level=info msg="Creating container rancher-ha-parent" component=docker
time="2016-07-08T15:15:13Z" level=info msg="Creating container rancher-ha-tunnel-redis-1" component=docker
time="2016-07-08T15:15:13Z" level=info msg="Creating container rancher-ha-tunnel-zk-quorum-1" component=docker
time="2016-07-08T15:15:14Z" level=info msg="Creating container rancher-ha-tunnel-zk-leader-1" component=docker
time="2016-07-08T15:15:14Z" level=info msg="Creating container rancher-ha-tunnel-zk-client-1" component=docker
time="2016-07-08T15:15:15Z" level=info msg="Creating container rancher-ha-cattle" component=docker
time="2016-07-08T15:15:15Z" level=info msg="Waiting for server to be available" component=cert
time="2016-07-08T15:15:15Z" level=info msg="Can not launch agent right now: Server not available at http://172.17.0.1:18080/ping:" component=service
time="2016-07-08T15:15:20Z" level=info msg="Cluster changed, index=2, members=[10.10.18.53, 10.10.18.250, 10.10.18.249]" component=service
time="2016-07-08T15:15:20Z" level=info msg="Creating container rancher-ha-tunnel-redis-2" component=docker
time="2016-07-08T15:15:21Z" level=info msg="Creating container rancher-ha-tunnel-zk-quorum-2" component=docker
time="2016-07-08T15:15:22Z" level=info msg="Creating container rancher-ha-tunnel-zk-leader-2" component=docker
time="2016-07-08T15:15:23Z" level=info msg="Creating container rancher-ha-tunnel-zk-client-2" component=docker
time="2016-07-08T15:15:24Z" level=info msg="Creating container rancher-ha-tunnel-redis-3" component=docker
time="2016-07-08T15:15:25Z" level=info msg="Creating container rancher-ha-tunnel-zk-quorum-3" component=docker
time="2016-07-08T15:15:26Z" level=info msg="Creating container rancher-ha-tunnel-zk-leader-3" component=docker
time="2016-07-08T15:15:26Z" level=info msg="Creating container rancher-ha-tunnel-zk-client-3" component=docker
time="2016-07-08T15:15:27Z" level=info msg="Creating container rancher-ha-zk" component=docker
time="2016-07-08T15:15:27Z" level=info msg="Creating container rancher-ha-redis" component=docker
time="2016-07-08T15:15:28Z" level=info msg="Waiting for server to be available" component=cert
time="2016-07-08T15:15:28Z" level=info msg="Can not launch agent right now: Server not available at http://172.17.0.1:18080/ping:" component=service
time="2016-07-08T15:15:33Z" level=info msg="Waiting for server to be available" component=cert
time="2016-07-08T15:15:33Z" level=info msg="Can not launch agent right now: Server not available at http://172.17.0.1:18080/ping:" component=service
time="2016-07-08T15:15:38Z" level=info msg="Waiting for server to be available" component=cert
time="2016-07-08T15:15:38Z" level=info msg="Can not launch agent right now: Server not available at http://172.17.0.1:18080/ping:" component=service
time="2016-07-08T15:15:43Z" level=info msg="Waiting for server to be available" component=cert
time="2016-07-08T15:15:43Z" level=info msg="Can not launch agent right now: Server not available at http://172.17.0.1:18080/ping:" component=service
time="2016-07-08T15:15:48Z" level=info msg="Waiting for server to be available" component=cert
time="2016-07-08T15:15:48Z" level=info msg="Can not launch agent right now: Server not available at http://172.17.0.1:18080/ping:" component=service
time="2016-07-08T15:15:53Z" level=info msg="Waiting for server to be available" component=cert
time="2016-07-08T15:15:53Z" level=info msg="Can not launch agent right now: Server not available at http://172.17.0.1:18080/ping:" component=service
time="2016-07-08T15:15:58Z" level=info msg="Waiting for server to be available" component=cert
time="2016-07-08T15:15:58Z" level=info msg="Can not launch agent right now: Server not available at http://172.17.0.1:18080/ping:" component=service
time="2016-07-08T15:16:04Z" level=info msg="Creating container rancher-ha-agent" component=docker
v1.0.2: Pulling from rancher/agent
5a132a7e7af1: Already exists
fd2731e4c50c: Already exists
28a2f68d1120: Already exists
a3ed95caeb02: Already exists
7fa4fac65171: Pulling fs layer
33de63de5fdb: Pulling fs layer
d00b3b942272: Pulling fs layer
33de63de5fdb: Verifying Checksum
33de63de5fdb: Download complete
d00b3b942272: Verifying Checksum
d00b3b942272: Download complete
7fa4fac65171: Verifying Checksum
7fa4fac65171: Download complete
7fa4fac65171: Pull complete
33de63de5fdb: Pull complete
d00b3b942272: Pull complete
Digest: sha256:b0b532d1e891534779d0eb1a01a5717ebfff9ac024db4412ead87d834ba92544
Status: Downloaded newer image for rancher/agent:v1.0.2
time="2016-07-08T15:16:30Z" level=info msg="Container agent is not running in state &types.ContainerState{Status:\"exited\", Running:false, Paused:false, Restarting:false, OOMKilled:false, Dead:false, Pid:0, ExitCode:0, Error:\"\", StartedAt:\"2016-07-08T15:16:16.646696826Z\", FinishedAt:\"2016-07-08T15:16:27.503706577Z\"}" component=docker
time="2016-07-08T15:16:30Z" level=info msg="Deleting container ac72979a61c57e4e98468c40d6125f5550c135ebd9a5441cb3fa0813e055651a" component=docker
time="2016-07-08T15:16:30Z" level=info msg="Can not launch agent right now: Error response from daemon: Unable to remove filesystem for ac72979a61c57e4e98468c40d6125f5550c135ebd9a5441cb3fa0813e055651a: remove /mnt/docker/containers/ac72979a61c57e4e98468c40d6125f5550c135ebd9a5441cb3fa0813e055651a/shm: device or resource busy" component=service

**Comment by chrisurwin** [comment]
How many nodes are you running ha in? Is this happening on all nodes? Have you tried rebooting the server?

**Comment by jclark360** [comment]
3 node cluster, below is the ELB conf portions.   All nodes are at that same error now, but one of the nodes (I assume master?), got further and then ended at that point.

**Comment by jclark360** [comment]
"ListenerDescriptions": [
                {
                    "Listener": {
                        "InstancePort": 81,
                        "SSLCertificateId": "arn:aws:iam::861290736443:server-certificate/dev-rancherletsencrypt",
                        "LoadBalancerPort": 443,
                        "Protocol": "HTTPS",
                        "InstanceProtocol": "HTTP"
                    },
                    "PolicyNames": [
                        "ELBSecurityPolicy-2015-05"
                    ]
                },
                {
                    "Listener": {
                        "InstancePort": 80,
                        "LoadBalancerPort": 80,
                        "Protocol": "TCP",
                        "InstanceProtocol": "TCP"
                    },
                    "PolicyNames": []
                },
                {
                    "Listener": {
                        "InstancePort": 18080,
                        "LoadBalancerPort": 18080,
                        "Protocol": "TCP",
                        "InstanceProtocol": "TCP"
                    },
                    "PolicyNames": []
                }
            ],


 "BackendServerDescriptions": [
                {
                    "InstancePort": 81,
                    "PolicyNames": [
                        "my-ProxyProtocol-policy"
                    ]
                },
                {
                    "InstancePort": 444,
                    "PolicyNames": [
                        "my-ProxyProtocol-policy"
                    ]
                }
            ],

**Comment by chrisurwin** [comment]
Config needs changing to the following

"Listener": {
"InstancePort": 81,
"SSLCertificateId": "arn:aws:iam::861290736443:server-certificate/dev-rancherletsencrypt",
"LoadBalancerPort": 443,
"Protocol": "**SSL**",
"InstanceProtocol": **"TCP"**

**Comment by jclark360** [comment]
So i rebooted them all, and this is where they are at, which is either the cause of why we can't get to rancher through the https port or it's the reason..

time="2016-07-08T16:05:13Z" level=info msg="Can not launch agent right now: Server not available at http://172.17.0.1:18080/ping:" component=service
time="2016-07-08T16:05:19Z" level=info msg="Waiting for server to be available" component=cert
time="2016-07-08T16:05:19Z" level=info msg="Can not launch agent right now: Server not available at http://172.17.0.1:18080/ping:" component=service
time="2016-07-08T16:05:24Z" level=info msg="Waiting for server to be available" component=cert
time="2016-07-08T16:05:24Z" level=info msg="Can not launch agent right now: Server not available at http://172.17.0.1:18080/ping:" component=service
time="2016-07-08T16:05:29Z" level=info msg="Waiting for server to be available" component=cert
time="2016-07-08T16:05:29Z" level=info msg="Can not launch agent right now: Server not available at http://172.17.0.1:18080/ping:" component=service
time="2016-07-08T16:05:57Z" level=info msg="Can not launch agent right now: Get http://172.17.0.1:18080/v1/settings?name=bootstrap.required.image: net/http: request canceled (Client.Timeout exceeded while awaiting headers)" component=service
time="2016-07-08T16:06:08Z" level=info msg="Can not launch agent right now: Bad response statusCode [409]. Status [409 Conflict]. Body: [code=Conflict, message=Conflict] from [http://172.17.0.1:18080/v1/schemas]" component=service
time="2016-07-08T16:06:29Z" level=info msg="Can not launch agent right now: Get http://172.17.0.1:18080/v1/settings/ha.enabled: net/http: request canceled (Client.Timeout exceeded while awaiting headers)" component=service
time="2016-07-08T16:06:50Z" level=info msg="Can not launch agent right now: Get http://172.17.0.1:18080/v1/registrationtokens?accountId=1a7&removed_null=1: net/http: request canceled (Client.Timeout exceeded while awaiting headers)" component=service
time="2016-07-08T16:07:01Z" level=info msg="Can not launch agent right now: Bad response statusCode [409]. Status [409 Conflict]. Body: [code=Conflict, message=Conflict] from [http://172.17.0.1:18080/v1/settings/ha.enabled]" component=service
time="2016-07-08T16:07:27Z" level=info msg="Can not launch agent right now: Get http://172.17.0.1:18080/v1/settings/ha.enabled: net/http: request canceled (Client.Timeout exceeded while awaiting headers)" component=service
time="2016-07-08T16:07:32Z" level=info msg="Can not launch agent right now: Bad response statusCode [409]. Status [409 Conflict]. Body: [code=Conflict, message=Conflict] from [http://172.17.0.1:18080/v1/settings?name=bootstrap.required.image]" component=service
time="2016-07-08T16:13:42Z" level=info msg="Can not launch agent right now: Get http://172.17.0.1:18080/v1/settings?name=bootstrap.required.image: net/http: request canceled (Client.Timeout exceeded while awaiting headers)" component=service

**Comment by jclark360** [comment]
Currently I can only access the rancher ui from 18080, 80 and 443 both don't respond.

```
"ListenerDescriptions": [
                {
                    "Listener": {
                        "InstancePort": 18080,
                        "LoadBalancerPort": 18080,
                        "Protocol": "TCP",
                        "InstanceProtocol": "TCP"
                    },
                    "PolicyNames": []
                },
                {
                    "Listener": {
                        "InstancePort": 81,
                        "SSLCertificateId": "arn:aws:iam::861290736443:server-certificate/dev-rancherletsencrypt",
                        "LoadBalancerPort": 443,
                        "Protocol": "SSL",
                        "InstanceProtocol": "TCP"
                    },
                    "PolicyNames": [
                        "ELBSecurityPolicy-2015-05"
                    ]
                },
                {
                    "Listener": {
                        "InstancePort": 18080,
                        "LoadBalancerPort": 80,
                        "Protocol": "TCP",
                        "InstanceProtocol": "TCP"
                    },
                    "PolicyNames": []
                }
            ], "BackendServerDescriptions": [
                {
                    "InstancePort": 81,
                    "PolicyNames": [
                        "TFEnableProxyProtocol"
                    ]
                },
                {
                    "InstancePort": 444,
                    "PolicyNames": [
                        "TFEnableProxyProtocol"
                    ]
                }
            ]
```

**Comment by chrisurwin** [comment]
can you check that you can ping the CATTLE_HA_HOST_REGISTRATION_URL address from the host, and also see if you can curl it on port 443?

**Comment by jclark360** [comment]
curl times out on the registration url from a rancher host/server.

If i go into the management ui on 18080, im guessing because the loadbalancers rancher starts up aren't up.

![image](https://cloud.githubusercontent.com/assets/6331228/16694867/8365e450-450a-11e6-98ed-525d3d7d0597.png)

**Comment by chrisurwin** [comment]
whats in the logs from the Websocket-proxy and websocket-proxy-ssl?

**Comment by jclark360** [comment]
Where do you get the logs from?

**Comment by jclark360** [comment]
Does it matter what storage driver docker is using? we're using aufs.

**Comment by aemneina** [comment]
Does the URL provided to generate the rancher HA script resolve to your
ELB? Whats the health status of your elb? are these HA hosts able to
communicate with each other in the same SG?

**Comment by chrisurwin** [comment]
Shouldn't matter
in the UI clock on the service names and it shows the containers (probably stopped), click on the 3 dots at the end and view logs

**Comment by jclark360** [comment]
When i generated the setup script I did so from an individual host url, so no it wasn't through the ELB.  I ensured the host registration url was the ssl address to the elb hostname.  As far as the host security group i have 0-65535 open for tcp and udp within the sec group and from the elb.  The elb only listens on 80/443/18080

**Comment by jclark360** [comment]
@chrisurwin there is no option to view logs.. 

![image](https://cloud.githubusercontent.com/assets/6331228/16696126/77f1d956-4511-11e6-93dc-df722d078198.png)

**Comment by chrisurwin** [comment]
It will need to be in a stopped state, so stop it at the service level and then you should get view logs option

**Comment by jclark360** [comment]
@chrisurwin logs are empty once its stopped, and at the bottom of the log viewer it says disconnected.

**Comment by jclark360** [comment]
I see this all over the rancher-agent logs : time="2016-07-08T17:48:02Z" level="fatal" msg="Failed to connect to proxy." error="unexpected EOF"

**Comment by jclark360** [comment]
Ok, we got this working... I believe there is a bug somewhere in rancher when you aren't using a non-standard mysql port..  Once we changed the mysql port and rebuilt, we're good.
