### ISSUE TITLE
Rancher DNS/Metadata not working with `net:host` with Docker 1.12.0-rc3

### ISSUE THREAD

**Issue by cllunsford** [rancher/rancher#5369]
**Rancher Version:**
1.1.0

**Docker Version:**
1.12.0-rc3

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 14.04.4 LTS - AWS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA Rancher, External DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Launch a container with:

```
app:
  net: host
  labels:
    io.rancher.container.dns: 'true'
```

**Results:** 
Container starts with /etc/resolv.conf with the host dns nameservers.

```
search rancher.internal
nameserver [host dns-1]
nameserver [host dns-2]
nameserver [host dns-3]
```

**Expected:**
With Docker 1.11.2, the host nameservers are commented out and replaced with the metadata server ip and search domains:

```
# nameserver [host dns-1]
# nameserver [host dns-2]
# nameserver [host dns-3]
search app.stack.rancher.internal stack.rancher.internal rancher.internal rancher.internal
nameserver 169.254.169.250
```

For 1.12.0-rc3, a workaround is to launch with explicit DNS parameter pointing at the metadata IP (`--dns 169.254.169.250`) thanks to https://github.com/docker/docker/issues/21976.  However, the workaround causes problems with 1.11.2 and below so it isn't viable for environments with mixed host versions.

**Comment by deniseschannon** [comment]
Just to clarify, this is an issue with Docker 1.12.0-rc3? The last part of your last sentence seemed to make it seem like it was Docker 1.11.2. 

We'll take a look at this when we start testing Docker 1.12.

**Comment by cllunsford** [comment]
Yes, this is only an issue with Docker 1.12.0-rc3.  I've updated the description to clarify, but the gist is that the workaround for 1.12.0 causes issues with 1.11.2 and below.

**Comment by cllunsford** [comment]
Tested again and seeing the same behavior in Docker 1.12.0-rc4.

**Comment by frekele** [comment]
Hi @cllunsford ,
You tested with 1.12.0 and 1.12.1 too? Does the problem persist?

**Comment by deniseschannon** [comment]
We have moved to creating DNS/metadata into microservices, so this may be fixed. 

@sangeethah @soumyalj 

Can you test with the new infrastructure services if you can launch a container using

```
app:
  net: host
  labels:
    io.rancher.container.dns: 'true'
```

Check to see if DNS is correct in the different versions of Docker?

**Comment by deniseschannon** [comment]
We have automation runs working on Docker 1.12.3 with our latest infrastructure services in our v1.2.0-pre4-rcX releases, which have DNS tests with host networking.  We don't recommend running our RC releases as we currently are still going through test cycles. 

Note: we do not officially support Docker 1.12 with Rancher 1.1.4.
