### ISSUE TITLE
Nodes not listed through `kubectl get nodes` on Kunernetes1.3

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#5370]
**Rancher Version:**: 1.1

**Docker Version:**1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):**Ubuntu, Cloud

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Kubernetes

**Steps to Reproduce:**
1. Created a Kubernetes environment using catalog: https://github.com/alena1108/rancher-catalog
2. Environment came up successfully. 
3. After using the environment and running some tests kubectl failed to get the nodes. This happened after using the setup for couple of hours

kubelet logs below:

**Results:** 
```
7/8/2016 10:43:02 AME0708 17:43:02.839574    7806 kubelet.go:2873] Error updating node status, will retry: error getting node "test-849097": nodes "test-849097" not found
7/8/2016 10:43:02 AME0708 17:43:02.841592    7806 kubelet.go:2873] Error updating node status, will retry: error getting node "test-849097": nodes "test-849097" not found
7/8/2016 10:43:02 AME0708 17:43:02.841674    7806 kubelet.go:1218] Unable to update node status: update node status exceeds retry count
7/8/2016 10:43:12 AME0708 17:43:12.845616    7806 kubelet.go:2873] Error updating node status, will retry: error getting node "test-849097": nodes "test-849097" not found
7/8/2016 10:43:12 AME0708 17:43:12.851711    7806 kubelet.go:2873] Error updating node status, will retry: error getting node "test-849097": nodes "test-849097" not found
7/8/2016 10:43:12 AME0708 17:43:12.854129    7806 kubelet.go:2873] Error updating node status, will retry: error getting node "test-849097": nodes "test-849097" not found
7/8/2016 10:43:12 AME0708 17:43:12.857323    7806 kubelet.go:2873] Error updating node status, will retry: error getting node "test-849097": nodes "test-849097" not found
7/8/2016 10:43:12 AME0708 17:43:12.862650    7806 kubelet.go:2873] Error updating node status, will retry: error getting node "test-849097": nodes "test-849097" not found
7/8/2016 10:43:12 AME0708 17:43:12.862806    7806 kubelet.go:1218] Unable to update node status: update node status exceeds retry count
Connected
```

**Comment by roman0316** [comment]
I had a similar issue #5294, where the kubelet would not register the node, unless it was running on the master node. They told me it was an issue with the docker version, but even running on 1.10.3 I get the same results.

I later managed to get it running on Ubuntu 15.10 with docker 1.11, listing all nodes.

**Comment by alena1108** [comment]
Can be related to the bug that we've recently discovered in rancher kubernetes when certificates weren't loaded correctly on restart: https://github.com/rancher/kubernetes/pull/30. I'll update the bug with to-test once the template with the template is published.

**Comment by alena1108** [comment]
We had an issue with our k8s template around the time the bug happened, can you please retest

**Comment by soumyalj** [comment]
Tested with v1.2.0-pre2-rc2. Did not see the issue. 'kubectl get nodes' listed the nodes correctly.

**Comment by MinaDesu** [comment]
Hello,

Docker version: 1.11.2
OS version: coreos 1185.3.0 (digitalocean droplets)
Rancher server 1.2.0
Rancher agent 1.1.0

3 nodes are created and present under the hosts list for the Kubernetes environment, all is green under the Kubernetes infrastructure, but kubectl still returns only the local node.

**Comment by aemneina** [comment]
@MinaDesu are the host names on your nodes unique?

**Comment by timbrand** [comment]
I'm having the same as @MinaDesu 

Docker version: 1.11.2
OS: CoreOS(Stable) (1185.5.0)
latest ranger server and agents

Installed 4 hosts, all indicators of the system nodes are green in hosts page.
All hostnames of all nodes are unique.

When entering "kubectl get nodes" no nodes are displayed.

**Comment by MinaDesu** [comment]
@aemneina Yes, the nodes had a unique name. The solution to this was to add the CATTLE_AGENT_IP on the command line.

**Comment by timbrand** [comment]
@MinaDesu did you enter the public or private IP address? My VMs are running on Azure and the machine has a private IP address assange on the VM itself and van be accessed via an external IP. 
I have entrered the Internal IP.

**Comment by AmreeshTyagi** [comment]
> Solved
Not sure about your scenario, but I was facing similar issue, because my docker cgroup driver was different than kubernetes cgroup driver. 
Just updated it to `cgroupfs` using following commands mentioned in [doc](https://kubernetes.io/docs/setup/independent/install-kubeadm/).
`cat << EOF > /etc/docker/daemon.json
{
  "exec-opts": ["native.cgroupdriver=cgroupfs"]
}
EOF`

Restart docker service `service docker restart`.
Reset kubernetes on slave node: `kubeadm reset`
Joined master again: `kubeadm join <><>`

It was visible on master using `kubectl get nodes`
