### ISSUE TITLE
Connectivity between containers on sub-nets

### ISSUE THREAD

**Issue by brandon-adams** [rancher/rancher#5371]
**Rancher Version:** v1.1.0-dev5/v1.1.0

**Docker Version:** 1.11.2

**OS and where are the hosts located? (cloud, bare metal, etc):** Ubuntu 16.04 on Azure

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** Single node master, three hosts. Each host is on a separate sub-net, with all access (and UDP 500/4500 specifically) granted between sub-nets.

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Kubernetes

**Steps to Reproduce:** Trying to ping between network containers (or Kubernetes containers) on each host.

**Results:** Other containers are unreachable.

**Expected:** Containers should be able to reach each other over the Rancher network.

**Comment by aemneina** [comment]
Hey @brandon-adams , can you access the console for the network agents. From there attempt to ping the network agents present on the other host(s). Are they able to ping?

**Comment by brandon-adams** [comment]
No @aemneina, they can't ping at all. They can reach other containers on the same host, just not other hosts.

**Comment by brandon-adams** [comment]
OK, turns out I should have been using local IPs instead of public facing IPs. The labeling confused me. Once I switched to local addresses, communication worked across sub-nets.
