### ISSUE TITLE
Add first host and first Service pages are missing padding

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#5373]
**Rancher Version:** master 7/8

**Steps to Reproduce:**
1.  Create a new environment & go to that environment (see add first host)
2.  Add host (see Add first Service)

**Results:** Both the Add First Host & Add First Service pages are messed up
![image](https://cloud.githubusercontent.com/assets/11514927/16701738/8dbe8ab8-4516-11e6-8293-39085aab1a11.png)
![image](https://cloud.githubusercontent.com/assets/11514927/16701759/c2b4082e-4516-11e6-9ac5-06d3fb99b460.png)

**Expected:**  Nice looking pages

Mobile View of pages are also messed up:
![image](https://cloud.githubusercontent.com/assets/11514927/16701787/f79a0598-4516-11e6-998c-f0a9238bf07c.png)

**Comment by vincent99** [comment]
Same thing as other issue where all the padding disappeared on "wells"..

**Comment by tfiduccia** [comment]
Version - master 7/12
