### ISSUE TITLE
0 Hosts in HA

### ISSUE THREAD

**Issue by drpebcak** [rancher/rancher#5374]
**Rancher Version:**
enterprise:v1.1.0
**Docker Version:**
v1.11.2
**OS and where are the hosts located? (cloud, bare metal, etc):**
RancherOS v.0.5.0
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher, external DB. HA rancher-server behind an ELB (AWS)
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
Run HA script on 3 hosts, wait for ui to come up. Navigate to HA page
**Results:** 
Says 0 hosts in HA
**Expected:**
It should say 3 hosts in HA.

**Comment by drpebcak** [comment]
Also, I just noticed that according to the Rancher UI, one of my hosts doesn't seem to have any of the 'stack management' stuff running on it, except for the load-balancer and load-balancer-swarm containers.

`docker ps` disagrees though. I can see the services running there, and when I stop/start those containers, I see the logs from the other two showing zookeeper members changing.

**Comment by deniseschannon** [comment]
When you try to refresh the UI, is it still the same? Trying to diagnose if it's a UI issue or something else.

**Comment by drpebcak** [comment]
I managed to get the management containers to run properly across all 3 hosts, but it still says 0 hosts on the HA page.

And yeah its always 0 no matter how many times you refresh the page.

**Comment by aemneina** [comment]
This is typically indicative of inter-host communication being hindered. This is a great reference [here](http://docs.rancher.com/rancher/latest/en/installing-rancher/installing-server/multi-nodes/#requirements). I'd start with ensuring that hosts can communicate, with each other, on those ports.

**Comment by drpebcak** [comment]
@aemneina I've got three instances running rancher server in a VPC. They are sitting behind a public ELB that is accessable from 0.0.0.0/0 on ports (udp) 500, 4500, (tcp) 2181, 2376, 2888, 3888, 6379, 80, 18080. All traffic inside the VPC is permitted (all ports) They all connect via a hostname to that same elb.

Is there another way to test the connectivity besides a quick telnet?

**Comment by aemneina** [comment]
@drpebcak did you enable proxy protocol, and healthcheck, on that elb? thats also a piece you'll need in place... [here](http://docs.rancher.com/rancher/latest/en/installing-rancher/installing-server/basic-ssl-config/#configuration-requirements-for-elb-to-enable-rancher) . If you could post the output from rancher-ha-cattle, that might help pinpoint the issue. Also, does navigating to http://<host_ip>:18080/ system->ha show anything more than 0/3 hosts being connected?

**Comment by drpebcak** [comment]
I did, via terraform.
```
resource "aws_security_group" "rancher-server" {
    name = "rancher-server"
    description = "Gives access to rancher-ui. For vpc ${aws_vpc.default.id}"
    vpc_id = "${aws_vpc.default.id}"
    ingress {
      from_port = 80
      to_port = 80
      protocol = "tcp"
      cidr_blocks = ["0.0.0.0/0"]
  }
  ingress {
    from_port = 18080
    to_port = 18080
    protocol = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
}
ingress {
  from_port = 500
  to_port = 500
  protocol = "udp"
  cidr_blocks = ["0.0.0.0/0"]
}
ingress {
  from_port = 4500
  to_port = 4500
  protocol = "udp"
  cidr_blocks = ["0.0.0.0/0"]
}
ingress {
  from_port = 2181
  to_port = 2181
  protocol = "tcp"
  cidr_blocks = ["0.0.0.0/0"]
}
ingress {
  from_port = 2376
  to_port = 2376
  protocol = "tcp"
  cidr_blocks = ["0.0.0.0/0"]
}
ingress {
  from_port = 2888
  to_port = 2888
  protocol = "tcp"
  cidr_blocks = ["0.0.0.0/0"]
}
ingress {
  from_port = 3888
  to_port = 3888
  protocol = "tcp"
  cidr_blocks = ["0.0.0.0/0"]
}
ingress {
  from_port = 6379
  to_port = 6379
  protocol = "tcp"
  cidr_blocks = ["0.0.0.0/0"]
}

  egress {
      from_port = 0
      to_port = 0
      protocol = "-1"
      cidr_blocks = ["0.0.0.0/0"]
  }
}

resource "aws_elb" "rancher-server" {
  name = "rancher-server"
  instances = ["${aws_instance.rancher-server.*.id}"]
  security_groups = ["${terraform_remote_state.vpc_state.output.rancher-server_sg}"]
  subnets = ["${split(",", terraform_remote_state.vpc_state.output.public_subnets)}"]
  listener {
    instance_port = 81
    instance_protocol = "tcp"
    lb_port = 80
    lb_protocol = "tcp"
  }
  listener {
      instance_port = 18080
      instance_protocol = "http"
      lb_port = 18080
      lb_protocol = "http"
  }
  health_check {
    healthy_threshold = 2
    unhealthy_threshold = 2
    timeout = 4
    target = "TCP:22"
    interval = 5
  }
}

resource "aws_proxy_protocol_policy" "rancher-server_proxy" {
  load_balancer = "${aws_elb.rancher-server.name}"
  instance_ports = ["81"]
}
```

It always shows 0 connected.

Here is the output from one of the nodes. I see a lot of exceptions there...
https://gist.githubusercontent.com/drpebcak/edb72cead807152a20bf3e738e36069a/raw/3d7fb5970e763bacd467de4d727168240cbc3b95/rancher-ha-cattle

**Comment by drpebcak** [comment]
I just redeployed the rancher-server machines in the same infrastructure and here is the rancher-ha-cattle logs from that. I definitely see some errors in there, I'm just not sure what's causing it: https://gist.github.com/drpebcak/0591ba358d8a5af97b55b8ce825f8927

**Comment by cpoole** [comment]
@drpebcak for testing why don't you try:

```
    ingress {
        from_port = 0
        to_port   = 0
        protocol  = "-1"
        self      = true
    }
```

that will allow all communication between any host in that security group.

**Comment by drpebcak** [comment]
@cpoole just added that rule to the security group just to see.. so now the ELB and the instances should all allow all traffic from each other, since they all have that security group.

So far it still says 0 hosts in the UI.

**Comment by drpebcak** [comment]
Hey guys, just wanted to see if anyone had more ideas about this.

**Comment by deniseschannon** [comment]
@drpebcak I just closed #5656 in favor of this one, but in that one it had exact steps on how to reproduce.

```
Steps to Reproduce:
Create a blank database and use a previously generated rancher-ha.sh to stand up a cluster without priming the database.
Results: 
The HA cluster stands up and works fine, but going to the Admin/High-Availability tab always shows 0 hosts
```

Did you set up your database before starting your cluster?

**Comment by cpoole** [comment]
@deniseschannon I thought the ```export CATTLE_HA_ENABLED=true``` flag in the rancher-ha.sh script was for forcing initialization of the DB and autoconfig of HA without clicking in the UI... I swear I've seen this work before.

**Comment by drpebcak** [comment]
I don't believe I did initialize the db first.. I am attempting to automate the setup of this cluster, so manually spinning up an instance, getting the script, etc is all sort of out of the question.

I had heard the same thing @cpoole is mentioning. And I would think even if it doesn't work properly right now, it should be considered a pretty decent bug. Once you have the script (from a past install, a test environment, whatever), why should you ever NEED to manually spin up another single rancher server again? The HA initialization should take care of this for you.

**Comment by drpebcak** [comment]
And that's more or less what it says in the script:
```
# Uncomment below to force HA enabled and not require one to set it in the UI
      export CATTLE_HA_ENABLED=true
```

**Comment by cpoole** [comment]
Alright @drpebcak that flag definitely works. I just stood up a fresh rancher HA instance with a fresh database. 

There might be a caveat with the encryption keys. If you want to do it all through scripting I have found you need to provide the encryption key and encrypted password for this to work. This requires you to have spun up a rancher ha instance before (in order to steal the encryption key and encrypted password format). Or to emulate the encryption using a little java helper using the Aes256Encrypter.java class from the cattle project. 

this issue might be related to https://github.com/rancher/rancher/issues/5459

**Comment by aemneina** [comment]
@drpebcak in the setting table, do you have entries with the name ha.* ?

can you get the output from: `select * from setting where name like “ha%”`

**Comment by drpebcak** [comment]
@aemneina No, that query returns 0 records.

**Comment by aemneina** [comment]
Sorry for lagging, I usually inject the settings into the db with: `insert into setting values (null,'ha.cluster.size','3'),(null,'ha.enabled','true')`.

**Comment by drpebcak** [comment]
@aemneina that seems to have worked, thanks! Is there functionality that might still not be correct because of this? The only other issue I have is that every 30 seconds or so the pages refresh (disconnects from log view, resets metrics, or closes open shell). Is that possibly related to this, or should it be in a different issue?

**Comment by aemneina** [comment]
That would be a different issue. Something between you and rancher is closing idle connections (typically the LB fronting the HA stack). Doesnt help that the load-balancer service with-in the rancher management stack, is configured to timeout idle connections at 50 seconds... I call that out [here](https://github.com/rancher/rancher/issues/6192).

**Comment by drpebcak** [comment]
Could be the ELB, but if I have an open terminal that is streaming logs or something, that isn't really idle, is it?

**Comment by aemneina** [comment]
no, that sounds bad...

**Comment by aemneina** [comment]
@drpebcak I'm going to close this, and we can follow https://github.com/rancher/rancher/issues/6192 for resolution.
