### ISSUE TITLE
Random Port Mapping - Multi-protocol random ports

### ISSUE THREAD

**Issue by tobbbles** [rancher/rancher#5378]
**Rancher Version:**
1.1.0.

**Docker Version:**
Docker version 1.11.2, build b9f10c9.

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04 - bare metal dedi.

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node on same machine as controller, internal DB.

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Spawn a container which exposes the same port on UDP and TCP, IE: 27015/udp + 27015/tcp. Put in the internal ports but leave host blank to get random port mapping.

**Results:** 
Two different port numbers, IE: 6123/udp 8370/tcp.

**Expected:**
The same random port for each protocl, IE: 6123/udp 6123/tcp.

**Comment by deniseschannon** [comment]
All ports are assigned randomly regardless of what's the exposed port, so if you'd want ports of the same port number but different protocol to be randomly assigned to the same port, that would be an enhancement to how we handle random port assignment.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
