### ISSUE TITLE
Can I change the "_" in the hostname of container ? 

### ISSUE THREAD

**Issue by mcsezhj** [rancher/rancher#5379]
**Rancher Version:**
1.1.0
**Docker Version:**
1.19.0

Hello,

I like rancher very much and Im trying to migrate most of my apps and make them running on rancher, but I met a problem this day.

I like to use the managed network of rancher and set the io.rancher.container.hostname_override	to container_name to use the internal DNS. but the hostname of container set to stackname_serivcename_createindex. but in many applications such as websphere and hadoop.. the "_" in the hostname is illeagle... can I change the "_" to "-" ? Many thanks

**Comment by deniseschannon** [comment]
Currently. there is no way to change the`_` to some other character in the container name. I've made this an enhancement request.

**Comment by vincent99** [comment]
This is going to need to change fairly soon anyway with the current remote API for docker 1.12 not allowing underscore anymore..

**Comment by vincent99** [comment]
https://github.com/rancher/rancher/issues/3589
