### ISSUE TITLE
Active Directory configuration - api.auth.ldap.user.enabled.mask.bit

### ISSUE THREAD

**Issue by florck** [rancher/rancher#5380]
**Rancher Version:1.1.0**

**Docker Version:1.11.2**

**OS and where are the hosts located? (cloud, bare metal, etc):Ubuntu 14.04 on VMWare**

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB) single node external DB**

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos) Cattle**

**Steps to Reproduce:Use our AD with some users that have not the  userAccountControl field.**

*_Results: It will do a segfault : *_ 

```
2016-07-10 07:46:22,415 ERROR [:] [] [] [] [qtp952062976-17] [i.g.i.g.r.handler.ExceptionHandler  ] Exception in API for request [http://docker01.*sanitized*:8080/v1/ldapconfigs]. Error id: [4e028832-6e0b-409e-bc72-487f61f0a81e]. java.lang.NullPointerException: null
```

**Expected:This should be supported.**

Work arround : manually in the db do : 

```
MariaDB [cattle]> update setting set value="" where name="api.auth.ldap.user.enabled.attribute";
Query OK, 1 row affected (0.00 sec)
Rows matched: 1  Changed: 1  Warnings: 0

MariaDB [cattle]> update setting set value="" where name="api.auth.ldap.user.enabled.mask.bit";
Query OK, 1 row affected (0.00 sec)
Rows matched: 1  Changed: 1  Warnings: 0

MariaDB [cattle]> commit;
Query OK, 0 rows affected (0.00 sec)
```

Take care, automatically, by adding a new users, those fields are reset, unfortunately...

**Comment by prachidamle** [comment]
Moving out as per discussion with @will-chan

**Comment by prachidamle** [comment]
@florck if your AD does not have the 'userAccountControl' field, then you can set it as empty in the config while configuring AD. This will set the appropriate setting in the DB to "" - you don't have to manually change the db setting.

Check the screenshot of the AD config and the fields to be left empty are circled.

<img width="1393" alt="screen shot 2016-10-27 at 2 11 48 pm" src="https://cloud.githubusercontent.com/assets/1470602/19785974/92decf80-9c50-11e6-8a47-02c31db7d574.png">

**Comment by florck** [comment]
@prachidamle right, but every time you create a suer, those values empty are forced back to their default !

**Comment by deniseschannon** [comment]
@florck Are you saying that even if you configure AD with the blank field, when you create a user the user is still getting the default value?

If it's configured as blank in the access control setup, it shouldn't be configured when adding new users.

**Comment by deniseschannon** [comment]
@florck Based on what @prachidamle has commented, if you leave that field blank when setting up your access control to LDAP., it shouldn't be configured. 

If you still have issues, please re-open.

**Comment by florck** [comment]
As I tried several time to explain, if I set blank, it is reset to the default value each time a user is created.

**Comment by tfiduccia** [comment]
Version - master 1/3
I verified this is indeed a problem in AD.  If you go to the AD screen and remove Status Field information, when you authenticate, it actually puts it back.  I filled out info, removed userAccountControl from Status Field and when I authentication you can see it is actually still there:
![image](https://cloud.githubusercontent.com/assets/11514927/21623051/d434e71a-d1bd-11e6-980b-66e227b30e3e.png)

**Comment by deniseschannon** [comment]
@tfiduccia Can you re-test with v1.6.6-rc4?

**Comment by tfiduccia** [comment]
Version - v1.6.6-rc4
Verified fixed (tested on start and on edit.)
