### ISSUE TITLE
HA websocket-proxy doesn't start cleanly

### ISSUE THREAD

**Issue by haswalt** [rancher/rancher#5383]
**Rancher Version:**
v1.1.0

**Docker Version:**
1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
cloud (scaleway)

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single machine HA with external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Start HA cluster

**Results:** 
Websocket proxy only half starts, Gets stuck in initialising and containers flap. Attempts to resolve by kicking them into the right state fails. Stats, logs and shell not working in UI.

Eventually stopping all websocket proxy containers and forcing into upgrade states gets them to both boot correctly, UI operations now active however stack is now stuck in Finishing-Upgrade

**Expected:**
All services come up clearnly

**Comment by deniseschannon** [comment]
We have had some issues with websocket proxy and have made some better logging and some fixes in the last 1.1.x releases.

Could you try upgrading to v1.1.2? If you face issues after the upgrade, we should be able to better diagnose your issue as we log more details.

**Comment by deniseschannon** [comment]
@haswalt If you still face issues after upgrading to v1.1.2, please reopen.
