### ISSUE TITLE
Audit logs search by a time range in addition to resource type

### ISSUE THREAD

**Issue by gdiazlo** [rancher/rancher#5385]
**Rancher Version:**
1.1.0

**Docker Version:**
1.11.2

**OS and where are the hosts located? (cloud, bare metal, etc):**
RHEL 7.2 in AWS instances

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node, external DB (AWS RDS Aurora)

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

We would like to be able to search audit logs by a time range in addition to resource type, event type. etc. When there are a lot of activity, searching for dates would save us to do it in the DB directly.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
