### ISSUE TITLE
Multiple engine options when creating a host from the UI

### ISSUE THREAD

**Issue by alejandrogr** [rancher/rancher#5386]
**Rancher Version:**  V1.1.0

**Docker Version:** V1.11.2

**OS and where are the hosts located? (cloud, bare metal, etc):** AWS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** Single Node with Aurora DB cluster

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:**
When creating a host from the UI add two engine options with the same name.

- In the UI add this params under the advanced options:
	- Engine Options:
		- storage-opt: dm.thinpooldev=/dev/mapper/docker-thinpool
		- storage-opt: dm.use_deferred_removal=true

We are trying this to configure the engine with direct-lvm as [explained here](https://docs.docker.com/engine/userguide/storagedriver/device-mapper-driver/) 

**Results:** 
The second option is ignored and deleted (if you try to clone the host the second option is missing)

**Expected:**
The engine should be configured with both options

**Comment by deniseschannon** [comment]
@alejandrogr Can you check what's in the API for that host? 

Does it show both engine options or just the 1 in the UI?

**Comment by vincent99** [comment]
The parameter is a map, and maps can't have duplicate keys... so it's lost when POSTing to create the machine.

**Comment by vincent99** [comment]
https://github.com/rancher/rancher/issues/3242

**Comment by alejandrogr** [comment]
There are a lot of engine options that can be specified multiple times. The parameter being a map just prevents using them multiple times: https://docs.docker.com/v1.10/engine/reference/commandline/daemon/

Is there any other way to specify a parameter more than once in the engine options?

**Comment by alejandrogr** [comment]
Sorry, i see now the duplicate issue.

Thanks!
