### ISSUE TITLE
TimeoutException when deactivating a volume

### ISSUE THREAD

**Issue by nunofgs** [rancher/rancher#5388]
**Rancher Version:**
1.1.0.

**Docker Version:**
1.10.3.

**OS and where are the hosts located? (cloud, bare metal, etc):**
AWS.

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher.

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle.

**Steps to Reproduce:**
1. Create a convoy-nfs storage pool.
2. Start a new container that uses a volume with the `convoy-nfs` volume_driver. (for example, a web application).
3. Upgrade the new container. You don't need to change anything, just click "Upgrade".

Every once in a while, the new upgraded container will be stuck "initializing" and will never launch.

If I navigate in Rancher to "Admin" > "Processes", I get this:

<img width="1296" alt="screen shot 2016-07-11 at 14 58 34" src="https://cloud.githubusercontent.com/assets/92085/16733426/6d3e00c4-4779-11e6-9df9-a110fa5b7fd0.png">

That `volume.deactivating` row corresponds to this:

<img width="1213" alt="screen shot 2016-07-11 at 15 10 14" src="https://cloud.githubusercontent.com/assets/92085/16733479/a241c7c4-4779-11e6-8f9d-af31dea379d2.png">

Here's the exception on that `volume.deactivating` row:

<img width="1301" alt="screen shot 2016-07-11 at 14 58 23" src="https://cloud.githubusercontent.com/assets/92085/16733500/be535a72-4779-11e6-99c3-9499da3c71ff.png">

Also, here's the output of the error in the main container:

<img width="1304" alt="screen shot 2016-07-11 at 14 59 03" src="https://cloud.githubusercontent.com/assets/92085/16733529/d019c7e6-4779-11e6-88b5-5f79e942900b.png">

<img width="1244" alt="screen shot 2016-07-11 at 15 12 28" src="https://cloud.githubusercontent.com/assets/92085/16733560/ead07d78-4779-11e6-9d77-c06584217360.png">

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
