### ISSUE TITLE
Kubernetes tab: should auto refresh once k8s environment is up

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#5391]
Today after k8s system stack comes up, you have to manually refresh the UI so not only "System" is available as an option under "Kubernetes" tab. We should think about the way to do it automatically.

@vincent99 is it doable? if not, we should make sure to document it somewhere @deniseschannon

**Comment by tfiduccia** [comment]
Version - 1.2.0-pre4-rc4
Verified fixed
