### ISSUE TITLE
Ability to add LDAP Cert independently of the SSL/TLS cert

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#5393]
Looking for the ability to add a LDAP Cert independently of the  rancher SSL/TLS cert. The issue is that both the Self-Signed Certificate (intermediate one; 3rd text area in HA setup) and LDAP one need to be named ca.crt.  This is the root of the problem as the self-signed certificate and ldap are signed by different roots. Combining both certs into ca.crt doesnt work.

**Rancher Version:**
1.1.0

**Docker Version:**
1.11.x

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
RancherHA

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle.

**Steps to Reproduce:**
Combined TLS cert + LDAP cert int ca.crt, launch rancher-ha.sh.

**Results:** 
TLS certs work, but LDAP wont

**Expected:**
Ideally a method to enable both, or allow for combined certs to work.

**Comment by aemneina** [comment]
similar second request/use case

We want to configure Rancher Server LDAPS to use our company's root certs by deploying the certs via container. The problem is the `rancher/server` service expects the `ca.crt` to be in the root of the file system

If the `rancher/server` instead expected the `ca.crt` file to be in something like `/certs/ca.crt` we could then use use `--volumes-from` and import the certs from a data container.

**Comment by janeczku** [comment]
Related: https://github.com/rancher/rancher/issues/7153

**Comment by aemneina** [comment]
outstanding issue here: is it possible to put multiple certs in /var/lib/rancher/etc/ssl/crt.ca

**Comment by deniseschannon** [comment]
@galal-hussein can you test to see if this works? we've updated how we handle certs.

**Comment by galal-hussein** [comment]
@aemneina @deniseschannon 
Rancher version: v1.4.0-rc2

Steps:
- Combine both the LDAP certificate and Rancher self signed certificate in one file:
```
-----BEGIN CERTIFICATE-----
<LDAP CERT>
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
<RANCHER SSL CERT>
-----END CERTIFICATE-----
```
- Start Rancher server with this combined file
```
docker run -d -p 8080:8080 -v /root/combined.crt:/var/lib/rancher/etc/ssl/ca.crt rancher/server:v1.4.0-rc2
```

- Install Nginx infront of Rancher server with the following configuration:
```
upstream rancher {
    server 127.0.0.1:8080;
}

server {
    listen 443 ssl;
    server_name xxxxx;
    ssl_certificate ssl/nginx.crt; # this is the self signed rancher crt
    ssl_certificate_key ssl/nginx.key;

    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://rancher;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        # This allows the ability for the execute shell window to remain open for up to 15 minutes. Without this parameter, the default is 1 minute and will automatically close.
        proxy_read_timeout 900s;
    }
}

server {
    listen 80;
    server_name hussein.rancher.space;
    return 301 https://$server_name$request_uri;
}
```
- Access the Rancher setup and Enable LDAP with TLS

After following the previous setup i was able to enable LDAP and add/remove users to Rancher server.

**Comment by aemneina** [comment]
This looks great thanks @galal-hussein
