### ISSUE TITLE
HA setup is not waiting long enough for the other hosts to become active

### ISSUE THREAD

**Issue by jggc** [rancher/rancher#5395]
**Rancher Version:**
v1.1.0

**Docker Version:**
Docker version 1.11.2, build b9f10c9

**OS and where are the hosts located? (cloud, bare metal, etc):**
CentOS Linux release 7.2.1511 (Core) 
QEMU VMs

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Rancher HA

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Launch the rancher HA script on three hosts and with some bad luck you'll get in that state

**Results:** 
All three hosts are cycling in destroying the containers, re-creating them and then waiting for one minute outputting 

```
level=info msg="Waiting for 3 host(s) to be active" component=cert 
```

before timing out. One minute is way too short. The destroying and recreating process takes more than that so it never happens that all three hosts are in the waiting period at the same time.

**Expected:**
The waiting time should be increased to something like maybe 10 minutes to make sure that the waiting time is longer than the destroy-create process.

Here is the full output of a loop : 

```
time="2016-07-11T23:15:55Z" level=fatal msg="Failed while waiting for 3 host(s) to be active: Timeout waiting for hosts to be active" component=service 
time="2016-07-11T23:16:01Z" level=info msg="Cluster changed, index=0, members=[10.250.5.100, 10.250.5.101, 10.250.5.102]" component=service 
time="2016-07-11T23:16:01Z" level=info msg="Container agent is not running in state &types.ContainerState{Status:\"exited\", Running:false, Paused:false, Restarting:false, OOMKilled:false, Dead:false, Pid:0, ExitCode:1, Error:\"\", StartedAt:\"2016-07-11T23:00:14.483331662Z\", FinishedAt:\"2016-07-11T23:15:22.781097403Z\"}" component=docker 
time="2016-07-11T23:16:01Z" level=info msg="Deleting container 87d94bcec029ba6c5956ffd8f69d2206d2945c3f3c02352713539fec5a74c56a" component=docker 
time="2016-07-11T23:16:03Z" level=info msg="Creating container rancher-ha-agent" component=docker 
time="2016-07-11T23:16:16Z" level=info msg="Forgetting cluster member" component=manager member={16  4c2ac425-3da6-4d94-890a-4a3859a0903b 10.250.5.101 map[] 0 54 2} 
time="2016-07-11T23:16:16Z" level=info msg="Cluster changed, index=2, members=[10.250.5.100, 10.250.5.101, 10.250.5.102]" component=service 
time="2016-07-11T23:17:32Z" level=info msg="Forgetting cluster member" component=manager member={17  4adeeabb-cde4-4213-80a2-12e8a185f656 10.250.5.100 map[] 0 47 1} 
time="2016-07-11T23:18:53Z" level=info msg="Forgetting cluster member" component=manager member={18  bde64ee3-305f-4e1d-a104-816f0ed5b7b6 10.250.5.102 map[] 0 49 3} 
time="2016-07-11T23:18:53Z" level=info msg="Currently Master: true" component=manager master=true 
time="2016-07-11T23:18:53Z" level=info msg="Assigning d2fc0623-efda-4b93-9467-52cf0c21ad67 10.250.5.102 to index 3" component=manager 
time="2016-07-11T23:18:58Z" level=info msg="Waiting for 3 host(s) to be active" component=cert 
time="2016-07-11T23:19:00Z" level=info msg="Waiting for 3 host(s) to be active" component=cert 
time="2016-07-11T23:19:02Z" level=info msg="Waiting for 3 host(s) to be active" component=cert 
time="2016-07-11T23:19:04Z" level=info msg="Waiting for 3 host(s) to be active" component=cert 
time="2016-07-11T23:19:06Z" level=info msg="Waiting for 3 host(s) to be active" component=cert 
time="2016-07-11T23:19:08Z" level=info msg="Waiting for 3 host(s) to be active" component=cert 
time="2016-07-11T23:19:10Z" level=info msg="Waiting for 3 host(s) to be active" component=cert 
time="2016-07-11T23:19:12Z" level=info msg="Waiting for 3 host(s) to be active" component=cert 
time="2016-07-11T23:19:14Z" level=info msg="Waiting for 3 host(s) to be active" component=cert 
time="2016-07-11T23:19:16Z" level=info msg="Waiting for 3 host(s) to be active" component=cert 
time="2016-07-11T23:19:18Z" level=info msg="Waiting for 3 host(s) to be active" component=cert 
time="2016-07-11T23:19:20Z" level=info msg="Waiting for 3 host(s) to be active" component=cert 
time="2016-07-11T23:19:22Z" level=info msg="Waiting for 3 host(s) to be active" component=cert 
time="2016-07-11T23:19:24Z" level=info msg="Waiting for 3 host(s) to be active" component=cert 
time="2016-07-11T23:19:26Z" level=info msg="Waiting for 3 host(s) to be active" component=cert 
time="2016-07-11T23:19:28Z" level=info msg="Waiting for 3 host(s) to be active" component=cert 
time="2016-07-11T23:19:31Z" level=info msg="Waiting for 3 host(s) to be active" component=cert 
time="2016-07-11T23:19:33Z" level=info msg="Waiting for 3 host(s) to be active" component=cert 
time="2016-07-11T23:19:35Z" level=info msg="Waiting for 3 host(s) to be active" component=cert 
time="2016-07-11T23:19:37Z" level=info msg="Waiting for 3 host(s) to be active" component=cert 
time="2016-07-11T23:19:39Z" level=info msg="Waiting for 3 host(s) to be active" component=cert 
time="2016-07-11T23:19:41Z" level=info msg="Waiting for 3 host(s) to be active" component=cert 
time="2016-07-11T23:19:43Z" level=info msg="Waiting for 3 host(s) to be active" component=cert 
time="2016-07-11T23:19:45Z" level=info msg="Waiting for 3 host(s) to be active" component=cert 
time="2016-07-11T23:19:47Z" level=info msg="Waiting for 3 host(s) to be active" component=cert 
time="2016-07-11T23:19:49Z" level=info msg="Waiting for 3 host(s) to be active" component=cert 
time="2016-07-11T23:19:51Z" level=info msg="Waiting for 3 host(s) to be active" component=cert 
time="2016-07-11T23:19:53Z" level=info msg="Waiting for 3 host(s) to be active" component=cert 
time="2016-07-11T23:19:55Z" level=info msg="Waiting for 3 host(s) to be active" component=cert 
time="2016-07-11T23:19:57Z" level=info msg="Waiting for 3 host(s) to be active" component=cert 
time="2016-07-11T23:19:59Z" level=info msg="Waiting for 3 host(s) to be active" component=cert 
time="2016-07-11T23:20:01Z" level=fatal msg="Failed while waiting for 3 host(s) to be active: Timeout waiting for hosts to be active" component=service 
```

**Comment by aemneina** [comment]
@jggc I'd imagine there is a communication issue between your hosts. Local firewall running on them maybe? Take a look [here](http://docs.rancher.com/rancher/latest/en/installing-rancher/installing-server/multi-nodes/#requirements) for minimal set of ports required.

**Comment by jggc** [comment]
There is no communication problem, there is no firewall between these machines. The problem is that it never happens that all three hosts are waiting for other hosts at the same time since the timeout is too short.

To be clear : 

- 00:00 Host 1 starts waiting
- 00:40 Host 2 starts waiting
- 01:00 Host 1 stops waiting (timeout)
- 01:30 Host 3 starts waiting
- 01:40 Host 2 stops waiting (timeout)
- 02:30 Host 3 stops waiting (timeout)
- 04:00 Host 1 starts waiting 
- ... and so on

So it never happens that all three hosts are waiting at the same time.

**Comment by ls-yann-david** [comment]
I do have the same issue. The timeout if wayyy to short for all 3 nodes to be there at the same time I fail my setup 2 times our of 3.

**Comment by hooperp** [comment]
Was there a solution to this ? I am hitting the same problem ... 3 hosts in the same subnet, all timing out. Can someone tell me, infrastructurally, what happens on HA startup - i.e. which services connect to which and the port that is used.

**Comment by aemneina** [comment]
@hooperp can you enable communication on all ports temporarily, see if that resolves the issue. The root of this is usually intercommunication between hosts is hindered. I posted a link to the doc's in a previous port. Googling those port numbers will allow you to match ports and services.

**Comment by hooperp** [comment]
All ports are open, ingress and egress - 0.0.0.0/0 
Sometimes the service comes up however mostly it doesn't. 
Is the issue with inter-host comms, or cross-host comms ? 
All containers on all 3 hosts seem to be alive, although it would be good to have a definitive list to cross reference against

**Comment by hooperp** [comment]
time="2016-11-08T11:17:33Z" level=fatal msg="Failed while waiting for 3 host(s) to be active: Get http://172.17.0.1:18080/v1/projects/1a7/hosts?state=active: dial tcp 172.17.0.1:18080: getsockopt: connection refused" component=service

**Comment by hooperp** [comment]
It ended up having nothing to do with security groups. Running the below before starting the services fixed it 

rm -rf /var/lib/rancher/state/.physical_host_uuid 
rm -rf /var/lib/rancher/state/.docker_uuid 
rm -rf /var/lib/rancher/state/containers/.healthcheck 
rm -rf /var/lib/rancher/cache/*
