### ISSUE TITLE
Always got 503 error after add custom catalog from a github repo source

### ISSUE THREAD

**Issue by wahyd4** [rancher/rancher#5399]
**Rancher Version:**
v1.1.0
**Docker Version:**
1.11.2
**OS and where are the hosts located? (cloud, bare metal, etc):**
Linux version 3.10.0-123.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.2 20140120 (Red Hat 4.8.2-16) (GCC) )  from China Telecom Chengdu
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
* go to Admin -> Settings
* Add an catalog  with any name and url is: https://github.com/yunlzheng/rancher-catalog.git
* Then you click the catalog you created
**Results:** 
You will got a 503 page. Several minutes later the system will show the correct result

**Comment by tfiduccia** [comment]
Version - v1.2.0-pre3
Verified fixed
