### ISSUE TITLE
Kubernetes won't install on more than one custom host

### ISSUE THREAD

**Issue by tehdeadone** [rancher/rancher#5401]
**Rancher Version:** v1.1.0-dev5

**Docker Version:** 1.10.3, 1.11.2

**OS and where are the hosts located? (cloud, bare metal, etc):** 
Hosts are stored in Amazon, but we're treated them as Custom nodes

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node, Internal DB

**Environment Type:** Kubernetes

**Steps to Reproduce:**
1. Create a new Kubernetes Environment
2. Add 3 Custom hosts
3. Let Kubernetes setup

**Results:** 
Kubernetes never finishes installing. etcd instances seem to be continually spinning. Logs seem to indicate network problems.

**Expected:**
Kubernetes installs across the 3 hosts successfully.

I can work around this by adding just 1 custom host, letting kubernetes install then adding the other 2 hosts.

**Comment by deniseschannon** [comment]
@tehdeadone Please reopen if you can provide more information as requested.
