### ISSUE TITLE
k8s componentstatuses Unhealthy 

### ISSUE THREAD

**Issue by swqMaven** [rancher/rancher#5402]
auto deploy k8s success but run images get error: dial tcp 127.0.0.1:10251: connection refused 

scheduler            Unhealthy   Get http://127.0.0.1:10251/healthz: dial tcp 127.0.0.1:10251: connection refused   
controller-manager   Unhealthy   Get http://127.0.0.1:10252/healthz: dial tcp 127.0.0.1:10252: connection refused   
etcd-0               Healthy     {"health": "true"}

i am deploy in vmhost. how can i resolve this problem?
thanks !

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.1.0` Cattle: `v0.165.4` UI: `v1.1.12` |
|Access|`localauth` `admin`|
|Orchestration|`Kubernetes`|
|Route|`service.containers`|

**Comment by HackerWilson** [comment]
@swqmaven have you resolved this problem? I also meet this, too.

**Comment by HackerWilson** [comment]
@deniseschannon have you ever meet this problem and how to resolve that?

**Comment by deniseschannon** [comment]
@HackerWilson I'm not sure what the original poster's issue was. We are now recommending using Racher 1.2.2 with Kubernetes 1.4.6 

Do you face this issue with those versions?

**Comment by HackerWilson** [comment]
@deniseschannon yes, rancher 1.2.2 with Kubernetes 1.4.6.

I am on  CentOS Linux release 7.2.1511 (Core).
