### ISSUE TITLE
Set $MX in cattle.sh with environment

### ISSUE THREAD

**Issue by kmcgrath** [rancher/rancher#5403]
Request to be able to set $MX in cattle.sh with an environment variable that will override the automatic heap detection here: https://github.com/rancher/rancher/blob/b0992f61f1a02305f20e62039fcc7836c679b915/server/artifacts/cattle.sh#L177

**Rancher Version:** 1.1.0

**Docker Version:** 1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):** AWS Linux on AWS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single node

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Comment by jean-francois-labbe** [comment]
I really need that

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
