### ISSUE TITLE
Should have min size for stack/host drop-down

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#5409]
**Rancher Version:** master 7/12

- [x] Should have a min size for drop-down, but keep resize for larger text
![image](https://cloud.githubusercontent.com/assets/11514927/16702232/94f78e8a-4519-11e6-8076-45f429b93698.png)

**Comment by lvuch** [comment]
https://github.com/rancher/ui/pull/780

**Comment by tfiduccia** [comment]
Version - master 7/15
Verified fixed
