### ISSUE TITLE
recreateOnQuorum sometimes causes container to get recreated resulting in loosing the quorum. 

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#5411]
rancher-server version - v1.1.0

Steps to reproduce the problem:

Create a health check enabled service with scale=3 with recreateOnQuorum and qcount set to 2.

Make 2 of the containers unhealthy.

Unhealthy containers get recreated sometimes.
This issue does not reproduce always.

Expected Behavior is for the containers in "unhealthy" state to continue to remain in "unhealthy" state and not be recreated.

```
Error Message

assert 'removed' == 'running'   - removed   + running
Stacktrace

super_client = <cattle.Client object at 0x7ffbb85280d0>
client = <cattle.Client object at 0x7ffbb8e16890>, socat_containers = None

    def test_service_with_healthcheck_quorum_container_unhealthy_2(
            super_client, client, socat_containers):
        scale = 3
        port = 803
    
        env, service = service_with_healthcheck_enabled(
            client, super_client, scale, port, strategy="recreateOnQuorum",
            qcount=2)
    
        # Make 2 containers unhealthy , so 1 container is healthy state
        container_list = get_service_container_list(super_client, service)
    
        unhealthy_containers = [container_list[1],
                                container_list[2]]
    
        for con in unhealthy_containers:
            mark_container_unhealthy(con, port)
    
        # Validate that the container is marked unhealthy
        for con in unhealthy_containers:
            wait_for_condition(
                client, con,
                lambda x: x.healthState == 'unhealthy',
                lambda x: 'State is: ' + x.healthState)
            con = client.reload(con)
            assert con.healthState == "unhealthy"
    
        # Make sure that the container continues to be marked unhealthy
        # and is in "Running" state
        time.sleep(10)
        for con in unhealthy_containers:
            con = client.reload(con)
            assert con.healthState == "unhealthy"
>           assert con.state == "running"
E           assert 'removed' == 'running'
E             - removed
E             + running

tests/validation/cattlevalidationtest/core/test_services.py:1088: AssertionError
```

**Comment by alena1108** [comment]
double checked with @ibuildthecloud, everything in quorum works as expected. The fact that we take snapshot of instances states in the beginning of the reconcile, can result in the recreate of the very first unhealthy instance. As a part of the test, just make sure that 2 unhealthy containers never get recreated in a case like that:

1) Scale=3, quorum=2
2) Mark 2 instances as unhealthy at the same time.
3) Validate that only i2 or only i3 got recreated, or none got recreated. You should never see both i2 and i3 getting recreated.

**Comment by sangeethah** [comment]
@alena1108: @ibuildthecloud: What I see is the following:
1) Scale=3, quorum=2
2) Mark 2 instances as unhealthy at the same time.
I see both containers getting recreated. This happens in the following scenario:

There are 2 unhealthy instances. one of the "unhealthy" instances gets removed. Once service reconcile kicks in , this instance gets created and gets to "healthy" state. This results in the other "unhealthy" instance to get recreated.

**Comment by sangeethah** [comment]
Closing this issue.I will skip the test case that validates this workflow.
