### ISSUE TITLE
how to add host ip(Environment Variable) for container ?

### ISSUE THREAD

**Issue by Dreampie** [rancher/rancher#5412]
![f2b16e6c-e13f-46df-9df6-1c7f9cba4443](https://cloud.githubusercontent.com/assets/3667080/16799413/51669c02-4923-11e6-894f-133b220e3558.png)

I create labels `local.ip` at machine,and if I add Service(multi container in different machine) ,every container can read host ip on running host

**Comment by Dreampie** [comment]
if use entrypoin  `-eEUREKA_INSTANCE_IP=$(curl rancher-metadata/latest/self/host/agent_ip) `
alway stop

**Comment by Dreampie** [comment]
now  I use `entrypoint.sh` (http://rancher-metadata/latest/self/host/agent_ip),but only can use with  rancher stack,can't use in custom container.

**Comment by cloudnautique** [comment]
The way your getting it from metadata is the way to do it in Rancher. 

An alternate approach would be to use confd to generate some env file to source. That would allow you just launch a container with different prefixes, but query different backends... (http://rancher-metadata/latest/self vs. http://etcd-cluster/v3/). I'd say it is overkill for a single env var though. 

Also, in metadata you can grab /self/host/labels/local.ip if you need to.

**Comment by Dreampie** [comment]
thanks，I have resolved

**Comment by garjunan** [comment]
@Dreampie  How did you resolve this issue? Please share how did you read the host IP from Rancher label?

**Comment by Dreampie** [comment]
@garjunan http://rancher-metadata/latest/self/host/agent_ip

**Comment by garjunan** [comment]
Thanks. I will check this out.
