### ISSUE TITLE
rancher-compose.yml 中不能存在任何中文

### ISSUE THREAD

**Issue by ranmufei** [rancher/rancher#5414]
*Describe your issue here*
v1.1.0的版本 有这问题 老版本没问题

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.1.0` Cattle: `v0.165.4` UI: `v1.1.12` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`environments.index`|

**Comment by deniseschannon** [comment]
1. Can you translate this into English?
2. I had put this into google translate and it seems that you used to be able to Chinese characters in `rancher.compose.yml` but it doesn't work in v1.1.0? 

Where are you putting the chinese in the rancher-compose.yml?

**Comment by tfiduccia** [comment]
This says "Rancher compose in 1.0.1 allowed Chinese characters and 1.1.0 does not"

**Comment by ranmufei** [comment]
yes !
rancher-compose.yml file not have chinese with version 1.1.0。

**Comment by sangeethah** [comment]
Tested with rancher-server version - v1.2.0-pre2-rc2 and rancher-compose version - v0.9.1-rc .

Having chinese characters in docker-compose.yml and rancher-compose.yml works as expected.
Tested with yml files having chinese characters in labels , commands , environment variables and metadata.
