### ISSUE TITLE
Deploy external service / dns alias from compose file..

### ISSUE THREAD

**Issue by kaos** [rancher/rancher#5415]
**Rancher Version:**

server, 1.1.0
rancher-compose        x86_64        1:0.8.5-1 

**Docker Version:**

1.11.2

**OS and where are the hosts located? (cloud, bare metal, etc):**

RedHat 7, bare metal.

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

single node rancher, external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

Cattle.

**Steps to Reproduce:**

Add external service in UI with name `mongo1`.

Run `rancher-compose up -d --upgrade` using a compose file with:

```
mongo1:
  image: rancher/external-service
  hostname: foo.bar
```

**Results:** 

Output from rancher-compose

```
...
time="2016-07-13T14:19:47+02:00" level=error msg="Failed Creating mongo1 : Action [setservicelinks] not available on [&{1s10595 externalService map[self:http://api.rancher.xxx../v1/externalservices/1s10595 
...
```

**Expected:**

To deploy/upgrade an external service using rancher-compose.

**Comment by alena1108** [comment]
Looks like rancher-compose bug. There is no setServiceLinks action for external/alias services, @joshwget can you take a look

**Comment by deniseschannon** [comment]
If hostname is placed in the rancher-compose.yml as expected, then this isn't an issue.

**Comment by kaos** [comment]
@deniseschannon interesting. I was under the impression that that wouldn't matter.. https://github.com/rancher/rancher/issues/2179#issuecomment-171341373
I haven't verified your claim yet, though.

**Comment by joshwget** [comment]
@kaos In general, it doesn't matter. The `hostname` key is the only one that is handled a little differently depending on which file it's in.

**Comment by kaos** [comment]
> The hostname key is the only one that is handled a little differently depending on which file it's in.

Doh. Ouch. Ok, thanks. Will try that, then.

**Comment by deniseschannon** [comment]
@carolynhu @joshwget now that we're giong towards having one file for docker-compose.yml/rancher-compose.yml, we'll need to figure out how to fix this.

**Comment by tfiduccia** [comment]
Version - 2.0 master 8/5
Verified fixed
