### ISSUE TITLE
[UI] Web Shell display unreadable code for filenames with Chinese characters

### ISSUE THREAD

**Issue by Willwil** [rancher/rancher#5417]
**Rancher Version: 1.1.0 and latest**

**Docker Version: 1.11.2**

**OS and where are the hosts located? (cloud, bare metal, etc): AWS EC2**

**Setup Details: single node rancher**

**Environment Type: Cattle**

**Steps to Reproduce:**
1. Put some files into container, and the filenames are in Chinese. And the system/container should support Chinese: 
a. sudo locale-gen zh_CN.UTF-8", and "locale -a" to check whether it is installed
b. set LANG to the value of just installed (displayed in "locale -a")
2. "sudo docker exec -it [containerid] /bin/bash" into container and the directory containing these files
3. "ls"
4. In Rancher UI->Containers, "Execute Shell" for the specified container, and "cd" into the directory containing the files with Chinese filename
5. "ls"

**Results:** 
1. The filenames in step 3 can be displayed correctly
2. The filenames in step 5 are unreadable if they are with Chinese characters
**Expected:**
All the filenames should be displayed correctly.

**Comment by vincent99** [comment]
This seems to work now with updated xterm.js

**Comment by tfiduccia** [comment]
Version - master 8/4
@Willwil I checked and it's working for me in master version.  If you would like to try now.

**Comment by deniseschannon** [comment]
Closing as it's already been verified.
