### ISSUE TITLE
rancher-compose pull doesn't show times images were created (for LATEST)

### ISSUE THREAD

**Issue by juliangamble** [rancher/rancher#5418]
**Rancher Version:** 
1.02
**Docker Version:**
1.10.3
**OS and where are the hosts located? (cloud, bare metal, etc):**
Redhat - cloud
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single-node-rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
`rancher-compose -p my-stack-name -f my-compile-file.yml pull`
**Results:** 

```
16:18:46.784 time="2016-07-14T16:18:46+10:00" level=info msg="Finished pulling docker.cloud.company.com/project/app4" 
```

**Expected:**

```
16:18:46.784 time="2016-07-14T16:18:46+10:00" level=info msg="Finished pulling docker.cloud.company.com/project/app4" **Built: 2016-07-14T12:20:41+10:00**
```

I want some way to debug issues with the _LATEST_ tag.  (I do see this when I look at the image in other locations - so it just becomes a normal expectation).

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
