### ISSUE TITLE
how can set permission(`upgrade`) for every account？

### ISSUE THREAD

**Issue by Dreampie** [rancher/rancher#5422]
add service,add container,run catalog.... every permission

**Comment by vincent99** [comment]
I'm not really sure what you're asking here, but there is only the 4 levels of membership to an Enviornment ("owner", "member", "restricted", and "readonly").

**Comment by Dreampie** [comment]
yes it's，I mean how set someone  only can manage someone machine，and add container for this machine，not like member for all

**Comment by deniseschannon** [comment]
It sounds like you want more detailed RBAC, which is an existing feature.

https://github.com/rancher/rancher/issues/1338
