### ISSUE TITLE
Error response from daemon: 400 Bad Request: malformed Host header

### ISSUE THREAD

**Issue by fedya** [rancher/rancher#5423]
**Rancher Version:**
1.1.0
**Docker Version:**
1.11.2
**OS and where are the hosts located? (cloud, bare metal, etc):**
OpenMandriva 3.0

**Results:** 
when i trying to run

sudo docker run -d --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.0.2 http://server.org:8080/v1/scripts/D5912A724ECC7B3F3621:sdsfsgegegegegege

I got this 

[fedya@fhurry]$ docker logs 16c1cf18969d8f6eb73eec5c5eefab48185ed9e1ce1d490e26d6b2dde5a6c167
Error response from daemon: 400 Bad Request: malformed Host header

As i know last time issue was in docker image in container, but according to release notes
it must be fixed now.

**Comment by vincent99** [comment]
This is the same issue as #4500, your Docker is compiled golang 1.6.x instead of 1.5.x like the official binaries.

**Comment by deniseschannon** [comment]
@fedya Please reopen if you have further questions.
