### ISSUE TITLE
Unknown exception io.cattle.platform.eventing.exception.AgentRemovedException: Agent [####] is removed

### ISSUE THREAD

**Issue by defunctzombie** [rancher/rancher#5429]
**Rancher Version:**
1.1.0

**Docker Version:**
1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
cloud

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

Still seeing tons and tons of this exception in the logs.

```
Unknown exception io.cattle.platform.eventing.exception.AgentRemovedException: Agent [####] is removed
```

**Comment by deniseschannon** [comment]
Is this happening after any particular action?

**Comment by defunctzombie** [comment]
Hard for me to tell explicitly unfortunately. I only come to the logs periodically and that is usually after a number of things have happened.

**Comment by deniseschannon** [comment]
Do you tend to add/remove hosts? How do you launch your hosts? Through the UI which uses docker-machine or do you do something that's already set up?

It'll be a bit trickier for me to reproduce.

**Comment by defunctzombie** [comment]
Understandable.

Hosts are launched manually via AWS and user data adds them to rancher.

For bare metal hosts we ssh in and run the docker launch command to add.

In both cases we are using RancherOS versions 0.4.3 and 0.4.5

Obviously with AWS hosts we will sometimes tear down machines.

**Comment by deniseschannon** [comment]
@defunctzombie In v1.2.0, let me know if you keep seeing these exceptions or if you can reliably reproduce.

**Comment by defunctzombie** [comment]
Ok, once it is released I will try it out and monitor for this error.

**Comment by defunctzombie** [comment]
@deniseschannon any word on when 1.2.0 will be considered released? Is the upgrade path to it from 1.1.4 simply to stop previous server and launch 1.2.0?

**Comment by deniseschannon** [comment]
@defunctzombie We are targeting end of October for 1.2.0. And yes, that is the upgrade path. 

http://docs.rancher.com/rancher/v1.2/en/upgrading/

**Comment by aemneina** [comment]
hey @defunctzombie I'll close this out and if you hit host related issues, can you file a new issue? I know this is a huge area of improvement for rancher... so you shouldnt see anything like this from 1.2 onwards.
