### ISSUE TITLE
Little grey arrow in all drop-downs

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#5430]
**Rancher Version:** master 7/14

**Steps to Reproduce:**
1.  Go to stack, container or host details page

**Results:** Notice in the drop-down there is a little grey arrow
![image](https://cloud.githubusercontent.com/assets/11514927/16852213/f9a4239c-49bb-11e6-9cca-4f8eafa28898.png)

**Expected:**  No grey arrow

**Comment by tfiduccia** [comment]
Version - master 7/15
Incomplete - the arrow is not changing after I click on drop-down, it's stays with the v arrow instead of the ^ arrow.
![image](https://cloud.githubusercontent.com/assets/11514927/16891125/46e95c78-4aaa-11e6-9e20-c2c16a703455.png)

**Comment by lvuch** [comment]
https://github.com/rancher/ui/pull/786

**Comment by tfiduccia** [comment]
Version - v1.2.0-pre1-rc3
