### ISSUE TITLE
Stack stuck on activating

### ISSUE THREAD

**Issue by jclark360** [rancher/rancher#5432]
**Rancher Version:**
Latest

**Docker Version:**
1.11.2

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 14.04

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher 3 nodes, external db

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Deploy our cluster and we're in activating in the stack listing

**Results:** 
Stack has been stuck on activating for days, and it's fine nothing is wrong...

**Expected:**
Activated

**Comment by jclark360** [comment]
Here is the api output for the stack:

```
{
"id": "1e32",
"type": "environment",
"links": {
"self": "…/v1/projects/1a5/environments/1e32",
"account": "…/v1/projects/1a5/environments/1e32/account",
"services": "…/v1/projects/1a5/environments/1e32/services",
"composeConfig": "…/v1/projects/1a5/environments/1e32/composeconfig",
},
"actions": {
"remove": "…/v1/projects/1a5/environments/1e32/?action=remove",
"error": "…/v1/projects/1a5/environments/1e32/?action=error",
"addoutputs": "…/v1/projects/1a5/environments/1e32/?action=addoutputs",
"activateservices": "…/v1/projects/1a5/environments/1e32/?action=activateservices",
"deactivateservices": "…/v1/projects/1a5/environments/1e32/?action=deactivateservices",
"exportconfig": "…/v1/projects/1a5/environments/1e32/?action=exportconfig",
},
"name": "stuff,
"state": "activating",
"accountId": "1a5",
"created": "2016-07-12T00:13:58Z",
"createdTS": 1468282438000,
"description": null,
"dockerCompose": null,
"environment": null,
"externalId": null,
"healthState": "healthy",
"kind": "environment",
"outputs": null,
"previousEnvironment": null,
"previousExternalId": null,
"rancherCompose": null,
"removed": null,
"startOnCreate": null,
"transitioning": "yes",
"transitioningMessage": "In Progress",
"transitioningProgress": null,
"uuid": "64f3a03b-78a4-48fa-8825-5bff5a214531",
}
```

**Comment by jclark360** [comment]
Any ideas?

**Comment by deniseschannon** [comment]
Are all the services green in the stack?

How did you deploy your stack? 

Since you're using HA, are there any system services in HA that are having issues?

**Comment by jclark360** [comment]
Hi @deniseschannon , all services are green, deployed the stack using rancher-compose.   All system services look fine in the HA stack.

Sorry for the late reply, was on vacation.

**Comment by deniseschannon** [comment]
Could you share your docker-compose.yml of your stack so I could try and reproduce?

**Comment by jclark360** [comment]
Wish i could, but a lot of confidential stuff in there.   Ironically, it seems to have sorted itself out... No idea how, as we haven't changed a thing.
