### ISSUE TITLE
when only private port is entered, public port is not set

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#5433]
**Rancher Version:** master 7/14

**Steps to Reproduce:**
1.  Create a service where just the private port number is entered

**Results:** No private port is set

**Expected:**  Just to pick random port and set it.

**Comment by will-chan** [comment]
Is this a regression?

**Comment by tfiduccia** [comment]
Yes.

**Comment by StrongMonkey** [comment]
Does it still happen on pre4-rc2? @tfiduccia

**Comment by deniseschannon** [comment]
Verified with Master 10/14 that this is working as expected
