### ISSUE TITLE
[go-rancher] Can't create registrationToken from Client

### ISSUE THREAD

**Issue by johnrengelman** [rancher/rancher#5434]
**Rancher Version:**
1.1.0

**Steps to Reproduce:**
Trying to create automation for Rancher using Hashicorp's Terraform. 
I started adding automation for Environments (Project in the API) and then
moved on to registration tokens as I want to be able to get the command string and/or token and be able to pass that on to a UserData template.

However, on environment create, no registration tokens exist and the Go client only has a client for dealing with the top level /v1/registrationTokens endpoint which prohibits creation.
However creation is allowed from the nested endpoint at /v1/project/<projectId>/registrationTokens, but nothing in the Go client lib seems to map to this.

Actually, it's apparent that there isn't a mechanism from the Go client lib to access any nested resource features as defined in the /v1/<type>/schema definitions. (only the top level /v1/schema is supported)

**Comment by vincent99** [comment]
The URL you pass into NewRancherClient can be `.../v1/projects/<id>` instead of `/v1` to scope it to a project/environment.

**Comment by johnrengelman** [comment]
ah interesting. Will have to try that. I'll close this for now :)

**Comment by johnrengelman** [comment]
@vincent99 what are your thoughts on adding some methods to RancherBaseClient to return a new client that is scoped to an environment/project?

**Comment by johnrengelman** [comment]
This doesn't seem to work because the schemas doc that is parsed by the client is still the top-level one.

When I do a request to `http://localhost:8080/v1/projects/1a28`, I see in the response a header for `X-Api-Schemas: http://localhost:8080/v1/schemas` which isn't correct.

the correct schema URL should be `http://localhost:8080/v1/projects/1a28/schemas`

**Comment by johnrengelman** [comment]
I was able to make it work by setting the URL for the client to be `http://localhost:8080/v1/projects/1a28/schemas` but this isn't intuitive.

**Comment by aemneina** [comment]
hey @johnrengelman looks like you've solved this, can I close it or is there something I missed.
