### ISSUE TITLE
[Feature Request] kind of image security vulnerabilities scan / Auto Update / UI Folder

### ISSUE THREAD

**Issue by KartoffelToby** [rancher/rancher#5436]
**Rancher Version: 1.1.0**

**Docker Version: 1.12.0**

**OS: Debian 8**

**Setup Details: single node rancher with https domain proxy (caddy)**

**Environment Type: Cattle**

_Feature Request:_
- A kind of Security Vulnerabilities Scan like the Docker Data Center
- Service Auto Update Option (Docker Hub Webhook)
- Service Stack Option in the Services View (UI) / Folder

**Comment by KartoffelToby** [comment]
Is it possible to intigrate Clair in the Frontend?

**Comment by circa10a** [comment]
This would be great to see in Rancher. A view to see if any running containers have known vulnerabilities.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
