### ISSUE TITLE
Proposal: Load Balancers should have highest priority when starting

### ISSUE THREAD

**Issue by withinboredom** [rancher/rancher#5438]
As someone who had a power outage due to some severe storms this past weekend, I'd like to make this proposal.

As machines came back online, services were coming online in random order (likely depending on docker and environment).

In my mind, the load balancers should be one of the first things online as they can route traffic to healthy containers as they come online.

At the same time, this could cause a flood of traffic to the services that aren't fully online yet, and at scale. Personally, I'd rather serve 3-5% of traffic instead of 0% of traffic...

What are the thoughts on this? Is this something worth (and possible?) pursue?

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
