### ISSUE TITLE
[UI] Edit LB Targets

### ISSUE THREAD

**Issue by kaos** [rancher/rancher#5443]
When looking/editing the LB targets, the Host (and path, if used) fields are so short, it doesn't really show the data properly..

See attached snap for example where it is really hard to grasp the various reguest hosts used..:
![image](https://cloud.githubusercontent.com/assets/72965/16873954/b9176fc4-4a96-11e6-9cd7-5065d8029add.png)

**Comment by vincent99** [comment]
![image](https://cloud.githubusercontent.com/assets/753917/20018995/76d426e0-a287-11e6-88fb-6d5f63ce5df6.png)

**Comment by tfiduccia** [comment]
Version - master 11/06
Size is dependent on size of screen now.
Verified fixed

**Comment by kaos** [comment]
Looks nice. Our request hosts are rather long, but I think it might show enough to make sense now..
