### ISSUE TITLE
Duplicate container on service with scale > 1

### ISSUE THREAD

**Issue by nunofgs** [rancher/rancher#5444]
**Rancher Version:**
1.1.0

**Docker Version:**
1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
AWS.

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher.

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle.

**Problem description:**

Today we found that we had a duplicate container for a service which had `scale=3` and apparently was running on the same host and had the same IP address.

I can't confirm if we actually had two different containers running on the docker daemon, or if they were simply duplicated on the Rancher UI.

I did confirm that they were two separate containers as far as Rancher was concerned since they had different id's. (confirmed by clicking "view in api" on both containers).

<img width="745" alt="eb262b68-4a9b-11e6-95e2-d1f43bc6697e" src="https://cloud.githubusercontent.com/assets/92085/16876676/c15212e2-4a9c-11e6-8dc9-2335c83adf55.png">

I can't reproduce this on demand, unfortunately.

**Expected:**

There should never be two containers with the same service index. Also, both containers somehow were reporting the same IP address.

**Comment by deniseschannon** [comment]
Would you be able to share your docker-compose.yml so we could try and reproduce? Did you do anything specific with the service (upgrade)?

I haven't seen this before, so we'll try our best to reproduce.

**Comment by nunofgs** [comment]
@deniseschannon: there's nothing really special about the `docker-compose.yml`, apart from having a zookeeper service with `scale=3`.

We did not explicitly upgrade the service but we do have a setup worth mentioning: we are using AWS spot instances tied to an autoscaling group.

This means that some of our machines are regularly removed from/added to Rancher and our scheduling policies launch containers on the new hosts as needed.

**Comment by deniseschannon** [comment]
@nunofgs When you can reliably reproduce, let me know. It sounds like a bug but will be hard to pinpoint as we don't typically see this issue.

**Comment by deniseschannon** [comment]
@nunofgs As we haven't been able to reproduce this issue and have not seen it ourselves, I'm going to close it. If you see it again, please let us know.
