### ISSUE TITLE
kube-system not created by default but showed in UI

### ISSUE THREAD

**Issue by gitdemo-cn** [rancher/rancher#5445]
When I tried to create a new k8s environment, the system stack was deployed successfully. In the UI, it shows default and kube-system namespaces. But kubectl get namespaces will return default only. kube-system namespace is actually not created. You will get error if trying to deploy guestbook sample from catalog.

Manually create kube-system namespace resolve this , but it will cause two "kube-system" showed in UI.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.1.0` Cattle: `v0.165.4` UI: `v1.1.12` |
|Access|`localauth` `admin`|
|Orchestration|`Kubernetes`|
|Route|`k8s-tab.namespace.services.index`|

**Comment by vincent99** [comment]
This is fixed already for the next Rancher release (1.2-pre1).  `kube-system` used to be "special" in that it always existed but never came back in the list of namespaces, but it's now just normal as of k8s ~1.2.

**Comment by pengjiang80** [comment]
@vincent99 got it, thx. Submitted this by my catalog demo github account.

**Comment by swqMaven** [comment]
i auto deploy k8s used rancher and some components is unhealthy! controller-manager and scheduler! iam first used it . can i get some suggests from you thanks!

**Comment by sangeethah** [comment]
Tested with v1.2.0-pre2-rc5

Create a K8s environment.
By default we get a k8 1.2 version.
UI does not list "kube-system" namespace.

Able to deploy "guestbook" from catalog successfully.

**Comment by sangeethah** [comment]
Tested with v1.2.0-pre2-rc5
Create a K8s environment.
By default we get a k8 1.2 version.
Upgrade K8s system stack to v1.3.

Right after upgrade is successful , I see  "kube-system" namespace in UI.
I am also able to see the  "kube-system" namespace using command  ``` kubectl get namespaces```.
