### ISSUE TITLE
rancher-agent fails on startup with docker 1.11

### ISSUE THREAD

**Issue by sronsiek** [rancher/rancher#5446]
Rancher Version: server 1.1.0, Agent 1.0.2
Docker Version: 1.11.2
OS: Suse SLE 12 SP1, 3 hosts in a private VLAN, no internet access.
Env: Swarm

Having started the rancher server, I try to create a host via the Web-UI. The agent container exits:

```
docker logs modest_roentgen:
Error response from daemon: 400 Bad Request: malformed Host header
```

The symptoms are the same as  #4982 (& other linked issues), however rancher server 1.1.0 is stated to be compatible with docker 1.11.x here: https://github.com/rancher/rancher/releases/tag/v1.1.0

My docker build is from Suse repos, and is built against go 1.6.2.

I tried the official docker 1.11.x binaries (which are compiled against go1.5.4). I sym-linked this docker to /usr/bin, re-start docker daemon. Runs, I can launch containers, ps etc.

But when I start the rancher server:

```
c59149e9421aec1e088566b0ae22a43f68c6f90f6e73f83837ad5221b64de15a
docker: Error response from daemon: rpc error: code = 2 desc = "oci runtime error: conditional filtering requires libseccomp version >= 2.2.1".
```

And as far as I can tell that lib does not exist for suse 12sp1, which seems to be a show-stopper for us.

Is this still the go-version issue or something different?
Are there any workarounds perhaps?

**Comment by deniseschannon** [comment]
I believe this is a go-version issue. 

Can you try with Docker 1.12.1 to see if that solves it?

**Comment by jhmartin** [comment]
CoreOS beta with Docker 1.11.2 experiences this issue: 

Docker version on coreos:
```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.6.3
 Git commit:   bac3bae
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.6.3
 Git commit:   bac3bae
 Built:
 OS/Arch:      linux/amd64
```

https://github.com/docker/docker/issues/20865 describes this behavior as well.   rancher agent 1.0.2 is compiled with go1.4.x.

**Comment by aemneina** [comment]
@sronsiek did you ever get to the bottom of this? Looks like a really old version of rancher being used against a more modern edition of docker. if you use rancher 1.0 (docker 1.10.x), 1.1.x rancher use (docker 1.10.x, 1.11.x). Rancher 1.2 should work well with 1.11 and 1.12 versions of docker.
