### ISSUE TITLE
Ipad issues

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#5447]
**Rancher Version:** master 7/15

- [x] Menu stays up if I click away
![image](https://cloud.githubusercontent.com/assets/11514927/16885258/92058dc6-4a82-11e6-8cbb-2d3bc9fbbc7b.png)

- [x] After clicking on menu once can't click menu again to get to another submenu.  Go to to Infrastructure menu and select host.  Now try to get to the container menu

- [x] On the Storage page, the menu items are off of the screen
![image](https://cloud.githubusercontent.com/assets/11514927/16885716/c55acc5c-4a84-11e6-83ca-3ff572595cf5.png)
- [x] Change the break point for Port Maps and Target links so it doesn't change to stacked tables on medium devices
![image](https://cloud.githubusercontent.com/assets/11514927/16885465/8744d6a2-4a83-11e6-8c47-5c8d9a36d41b.png)

- [x] Extra space at bottom
![image](https://cloud.githubusercontent.com/assets/11514927/16888165/1e7724f8-4a93-11e6-9f35-1841c7508f90.png)
 
- [x] Dismiss x in Access Control ! text, doesn't work
![image](https://cloud.githubusercontent.com/assets/11514927/16888586/dc7dc504-4a95-11e6-97ce-ce8afed6a894.png)

**Comment by tfiduccia** [comment]
The first two issues are still not resolved and should be fixed.
Not fixed

**Comment by westlywright** [comment]
the remaining issues should be resolved by https://github.com/rancher/ui/pull/813

**Comment by tfiduccia** [comment]
Version - master 8/11
Verified fixed
