### ISSUE TITLE
Logging into Rancher after auth causes background to be dark grey

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#5449]
**Rancher Version:** master 7/15

**Steps to Reproduce:**
1.  Authenticate using any of the auth provided
2.  Logout
3.  Log back in

**Results:** The background is dark grey
![image](https://cloud.githubusercontent.com/assets/11514927/16890333/441cea58-4aa2-11e6-9e2e-9c273e7c67c7.png)

**Expected:** Should not be dark grey.  Should be light grey if on light theme and a light black color if on dark theme.

**Comment by vincent99** [comment]
The `farm` class that used to be managed by a view isn't getting removed.

**Comment by tfiduccia** [comment]
Version - master 7/15
Verified fixed
