### ISSUE TITLE
rancher-compose pull freezes

### ISSUE THREAD

**Issue by juliangamble** [rancher/rancher#5453]
**Rancher Version:**

Component	Version
Rancher	v1.0.2
Cattle	v0.159.8
User Interface	v1.0.5
Rancher Compose	v0.7.4

**Docker Version:**

docker-compose version 1.7.1, build 0a9ab35

**OS and where are the hosts located? (cloud, bare metal, etc):**

Redhat

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

Single Node

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

Cattle

**Steps to Reproduce:**

    rancher-compose --verbose -p stackname -f rancher-file-name.yml pull

**Results:** 

    ←[37mDEBU←[0m[0000] Environment Context from file : map[]
    ←[37mDEBU←[0m[0000] Opening compose files: rancher-file-name.yml
    ←[37mDEBU←[0m[0000] Looking for stack stackname 
    ←[37mDEBU←[0m[0000] Found stack: stackname (1e598)
    ←[37mDEBU←[0m[0000] [0/1] [abc]: Adding
    ←[37mDEBU←[0m[0000] Opening rancher-compose file: rancher-compose.yml
    ←[37mDEBU←[0m[0000] Not found: rancher-compose.yml
    ←[37mDEBU←[0m[0000] Launching action for abs
    ←[37mDEBU←[0m[0000] [0/5] [abc]: Pulling

[ie - ie freezes here - on a redhat client and a windows client. ] Docker pull on both clients still work. It is as if the rancher engine freezes at this point. 

**Expected:**

    ←[37mDEBU←[0m[0000] [0/5] [abc]: Pulling
    ←[37mDEBU←[0m[0000] [0/5] [abc]: Pulled

**Comment by deniseschannon** [comment]
Using Rancher-compose v0.8.5, I was unable to reproduce this issue. 

How long did you wait for the pull to occur? There will be no details on the pull progress and you just need to wait until rancher-compose completes the pull.

**Comment by deniseschannon** [comment]
@juliangamble If you're able to reproduce using the latest rancher-compose versions, please re-open.
