### ISSUE TITLE
"Retain IP" setting in networking can't be changed during service upgrade

### ISSUE THREAD

**Issue by pengjiang80** [rancher/rancher#5454]
Create a service with retain ip setting, during service upgrade uncheck this setting then do the upgrade. Although it's showed as unchecked in UI, it actually didn't take effect. The IP is still retained and if you try to upgrade the service again, this option is still enabled.  It's the same behavior vice versa. 

Is it normal?
 
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.1.0` Cattle: `v0.165.4` UI: `v1.1.12` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`environment.index`|

**Comment by vincent99** [comment]
#5410
