### ISSUE TITLE
Create scalable / HA wordpress setup using Rancher - did not worked

### ISSUE THREAD

**Issue by jsinh** [rancher/rancher#5455]
**Rancher Version:**
Current Latest

**Docker Version:**
Current Latest

**OS and where are the hosts located? (cloud, bare metal, etc):**
MAC - El Caption

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Hello Team,
This is the first time I am using Rancher and I am so loving it. The purpose of using this is because, i feel this is a very good solution to create a HA / Scalable Wordpress setup.

I am following and got inspired by this article on your blog:
http://rancher.com/setting-up-a-scalable-and-highly-available-wordpress-environment-with-rancher-and-docker/

I am sure and tried 2 times above article - point-to-point and at the end I see that when I access WP site i get "Error connecting Database / Database Error" error.

I am stuck and not sure what am I missing from the documented article or is the article missing any important piece that I don't know of.

Please guide to get it resolved, Thanks in advance.

**Results:** 
Error connecting Database / Database Error

**Expected:**
Nicely working scalable / HA enabled - Wordpress setup.

**Comment by deniseschannon** [comment]
Are you running Docker for Mac? Or do you have a linux machine running Docker that's running Rancher. 

Currently, we don't support Docker for Mac with Rancher.

**Comment by jsinh** [comment]
I tried both actually. The setup in which I tried and got "Error connecting database / database error" was the second one "Linux machine running docker that's running Rancher".

I tried few other options after that and then it works. Not sure why but based on difference in two approach I think I was doing it wrong the first time. I was creating GlusterFS and Xtra DB cluster but these all containers where hosted on same Linux host and mount to same host folder. This should be a cause of my problem logically, I hope..

Thanks for coming back. I guess we conclude on this thread unless you have something to add?

**Comment by deniseschannon** [comment]
If you only had 1 host, that could be the issue. If you have further questions, please re-open.

**Comment by jdiaz1302** [comment]
Hey there, can someone point me to the updated article http://rancher.com/setting-up-a-scalable-and-highly-available-wordpress-environment-with-rancher-and-docker/ (this is the old one but there it says that there is an updated one)

**Comment by Kalloritis** [comment]
Actually I've set this up with a triple node setup as described in the post and the wordpress instance just keeps dieing with the error "failed to acquire service lock" and flipping into a degraded state causing the HAproxy to never be able to route traffic to any of the containers for wordpress to even begin to set it up.

Post should be either noted that it is out of date/no longer functional, or taken down.

**Comment by jsinh** [comment]
@Kalloritis - I agree. The idea of doing this setup is charming. But the only post that explains it to the point fails due to lack of some minor details and also because of being outdated / non-functional.

Sad to see that no actions is been taken to make it operational since long. 😞

**Comment by Kalloritis** [comment]
I'm going to swap out the WP stack from this with another one I'm going to draft up (nginx, php-fcgi) and see if this solves for things seeing as that is the only current issue. If it does and I'm able to unit test it successfully, I'll post a complete docker-compose.yml and rancher-compose.yml for general consumption.

**Comment by solidsystems** [comment]
@Kalloritis did you ever get this working?
