### ISSUE TITLE
conflict for LDAP users with same name as LDAP group

### ISSUE THREAD

**Issue by cpoole** [rancher/rancher#5457]
**Rancher Version:**
1.1.0
**Docker Version:**
1.11.2
**OS and where are the hosts located? (cloud, bare metal, etc):**
ubuntu 16.04 (aws cloud)
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher (behind ELB), external RDS database
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
create an LDAP user with name testAccount. Create an LDAP group with name testAccount. Attempt to add the user testAccount to an environment.
**Results:** 
 it is only possible to add the group, the user is not selectable
**Expected:**
it would be nice if there was some sort of async dropdown search that presented both options for you to click.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
