### ISSUE TITLE
cannot pass plaintext password to rancher HA config file

### ISSUE THREAD

**Issue by cpoole** [rancher/rancher#5459]
**Rancher Version:**
1.1.0
**Docker Version:**
1.11.2~xenial (from docker repos)
**OS and where are the hosts located? (cloud, bare metal, etc):**
AWS
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
Attempt to stand up rancher-HA without using the UI:

Take the ha-setup.sh script and before running swap out the encrypted password string (looks like: `ef9d168kjhf09asdf6dd15b25f6ae718:laskdfjasdfsf09d8fasdf09sd7fas8d7g0sad9g87as0dgga8g`) with a plain text password. 

Then uncomment the `export CATTLE_HA_ENABLED=true` line. 

**Results:** 
The rancher server containers cannot connect to the database. 

In order to connect you must uncomment the encryption key. Which I believe means communications cross server-cluster are not encrypted? (please correct me if I am wrong).

**Expected:**
It would be nice to be able to tell rancher that the db password you are providing is not encrypted and that rancher shouldn't try and decrypt the string. 

Maybe a flag like `CATTLE_DB_CATTLE_PASSWORD_PLAINTEXT=true`

It looks like this could be processed around line 140 of https://github.com/rancher/cattle/blob/master/code/iaas/api-logic/src/main/java/io/cattle/platform/iaas/api/manager/HaConfigManager.java

Browsing through the rancher code base is a little tricky though. If someone is willing to help point me to the right location I'm happy to put in a PR.

**Comment by cpoole** [comment]
whoops, this should be under cattle.

**Comment by deniseschannon** [comment]
@cpoole This is the correct repo to file this. :)

I've added this as an enhancement request.

**Comment by deniseschannon** [comment]
With the new HA in 1.2, this is no longer applicable as we've refactored HA to be much simpler and just run additional arguments with the rancher-server command. 

The config file no longer exists.
