### ISSUE TITLE
Zero downtime upgrade (services with longer start)

### ISSUE THREAD

**Issue by JanJakes** [rancher/rancher#5460]
When using service that needs some time to start up it seems to be impossible to upgrade (or even just scale up) with zero downtime. Reasons:
1. Rancher seems to add new container to HAProxy immediately when its ENTRYPOINT/CMD is executed (even when exposed ports are not opened yet).
2. Even though health checks are set up some requests fail since new servers in HAProxy are by default considered "up" until the health checks fail and mark server "down".

The above reasons combined cause that there's actually no option to have a zero-downtime upgrade/scale-up since requests get routed to a service that is not ready for some time (until health checks fail). Is there any way to get around this?

(I guess in many cases this problem is just not really visible since many services start in shorter time than Rancher needs to update HAProxy, but it is a general problem that can occur on any upgrade/scale-up from time to time.)

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
