### ISSUE TITLE
catalog page 'There are no compatible templates.' 

### ISSUE THREAD

**Issue by joostliketoast** [rancher/rancher#5461]
after upgrading to rancher  v1.1.10 the catalog page turned out empty with the message:

`There are no compatible templates.`

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `rancher/server` Cattle: `v0.165.7` UI: `v1.1.10` |
|Access|`github` `admin`|
|Orchestration|`Cattle`|
|Route|`catalog-tab.index`|

**Comment by tfiduccia** [comment]
@joostliketoast Can you check your settings and make sure Rancher Certified and Community Contributed options are set to enabled.
If they already are, can you disable, click save then enable and click save again.  See if that brings them back up.

**Comment by averri** [comment]
I have the same issue. 

I am testing the Rancher Catalog with this: https://gitlab.com/averri/ocb-catalog.git

| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.1.1` Cattle: `v0.165.7` UI: `v1.1.12` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`catalog-tab.index`|

**Comment by vincent99** [comment]
@averri: [compose v2](https://gitlab.com/averri/ocb-catalog/blob/master/templates/ocb-services/0/docker-compose.yml#L1) syntax is not supported yet.

**Comment by averri** [comment]
Thanks @vincent99, so I converted the docker-compose to v1, still no success.

**Comment by deniseschannon** [comment]
I think the top level folder should just be `templates` and you need another folder nested in that folder that will be named `ocb-services`.

**Comment by averri** [comment]
@deniseschannon, tried that too using: https://gitlab.com/averri/templates.git

And still getting the same message.

**Comment by vincent99** [comment]
@averri That's a repository named `templates`, not a folder named `templates` inside the repository.

**Comment by averri** [comment]
Hi @vincent99, thanks for informing that. I have added the folder  `templates`, as bellow:

![image](https://cloud.githubusercontent.com/assets/1898447/16999876/0b9ce484-4eb8-11e6-8ae2-ba5f66a7da91.png)

Added the catalog to Rancher:

![image](https://cloud.githubusercontent.com/assets/1898447/16999953/70d97e98-4eb8-11e6-8b56-93660f94b6d7.png)

But it still says:

![image](https://cloud.githubusercontent.com/assets/1898447/16999984/857e7efc-4eb8-11e6-838a-c774f1fbaa0b.png)

**Comment by vincent99** [comment]
Did you give it 5 min for automatic refresh or click the refresh button in the upper-right corner after changing?  They're not updated instantaneously

Unfortunately GitLab is down right now so I can't show a picture of it in the UI, but it was loading in the API now with your last change so it will work in the UI:

![image](https://cloud.githubusercontent.com/assets/753917/17004136/65644f3c-4e88-11e6-8a36-53211d3b6098.png)

**Comment by tfiduccia** [comment]
Tried in version 1.1.1 and I'm seeing your catalog after adding https://gitlab.com/averri/templates in catalog.
![image](https://cloud.githubusercontent.com/assets/11514927/17005146/7d729e08-4e8d-11e6-9a7a-f67aaaebb977.png)

**Comment by tfiduccia** [comment]
@joostliketoast never heard back from you about your catalog issue.  Was your issue resolved?

**Comment by averri** [comment]
Thanks @tfiduccia, but I still have no luck. I reinstalled Rancher Server, and the problem persists. There are some error messages in the Rancher Server:

```
time="2016-07-21T18:05:08Z" level=info msg="Starting Rancher Catalog service"
time="2016-07-21T18:05:08Z" level=info msg="Using catalog library=https://github.com/rancher/rancher-catalog.git"
time="2016-07-21T18:05:08Z" level=info msg="Using catalog community=https://github.com/rancher/community-catalog.git"
time="2016-07-21T18:05:08Z" level=info msg="Using catalog OCB=https://gitlab.com/averri/templates.git"
time="2016-07-21T18:05:08Z" level=error msg="Failed to pull the catalog from git repo https://github.com/rancher/community-catalog.git, error: exit status 1"
time="2016-07-21T18:05:08Z" level=error msg="Git pull for Catalog community failing with error: exit status 1 "
time="2016-07-21T18:05:08Z" level=info msg="Cloning the catalog from git URL https://gitlab.com/averri/templates.git"
Cloning into './DATA/OCB'...
fatal: unable to access 'https://gitlab.com/averri/templates.git/': Failed to connect to apache port 1080: Connection refused
time="2016-07-21T18:05:08Z" level=error msg="Failed to clone the catalog from git err: exit status 128"
time="2016-07-21T18:05:08Z" level=error msg="Failed to pull the catalog from git repo https://github.com/rancher/rancher-catalog.git, error: exit status 1"
time="2016-07-21T18:05:08Z" level=error msg="Git pull for Catalog library failing with error: exit status 1 "
```

**Comment by vincent99** [comment]
It seems you need/have configured a proxy for git that doesn't work?  Nothing is going to show up if it can't clone the repos.

**Comment by averri** [comment]
Hi @vincent99, it is possible to clone any git repo from the host, but not from inside the Rancher container:

From Docker host (ok):

```
[root@vmi77191 ~]# git clone https://gitlab.com/averri/templates.git
Cloning into 'templates'...
remote: Counting objects: 35, done.
remote: Compressing objects: 100% (28/28), done.
remote: Total 35 (delta 5), reused 0 (delta 0)
Unpacking objects: 100% (35/35), done.
```

From Rancher container (fails): 

```
root@fbc4f63eecf4:/# git clone https://gitlab.com/averri/templates.git
Cloning into 'templates'...
fatal: unable to access 'https://gitlab.com/averri/templates.git/': Failed to connect to apache port 1080: Connection refused
```

**Comment by averri** [comment]
I have the container environment variables HTTP_PROXY and HTTPS_PROXY set, and this causes the problem with git inside the Rancher Server container.

**Comment by deniseschannon** [comment]
@averri Were you able to resolve this?

**Comment by deniseschannon** [comment]
@joostliketoast @averri Please reopen if you still have issues.

**Comment by alfredfrancis** [comment]
I'm getting same issue in rancher v1.4.1. 
ive added following catalog url in settings.. https://github.com/alfredfrancis/rancher-catalogs
when i refresh im getting following log only..

`time="2017-03-01T14:39:27Z" level=info msg="Using catalog pdd=https://github.com/alfredfrancis/rancher-catalogs.git" `

**Comment by tuwid** [comment]
getting the same with rancher 1.6.24 and internet access is completely opened
