### ISSUE TITLE
the service type of rancher compsoe template returns unusable "service/stack" string

### ISSUE THREAD

**Issue by pschrammel** [rancher/rancher#5462]
**Rancher Version:**
1.1.1

**Docker Version:**
1.112

**Environment Type: (Cattle)**

**Steps to Reproduce:**
in rancher compose:
`
variable: "postgres_host"
      description: "Postgres Service"
      required: true
      type: "service"

`

**Results:** 
"postgres/postgres94"
**Expected:**
"postgres.postgres94"

the slash notation in unusable in docker compose if I want to pass the hostname directly in an ENV variable.

**Comment by adnan-panalytics** [comment]
+1

**Comment by deniseschannon** [comment]
Can you provide your full docker-compose.yml and rancher-compose.yml? I'm not sure I completely follow what you're expecting and where.

Is your stack name `postgres`?

**Comment by deniseschannon** [comment]
@pschrammel Please re-open if you can provide your full docker-compose.yml and rancher-compose.yml.
