### ISSUE TITLE
VPN/SA Failure

### ISSUE THREAD

**Issue by sjiveson** [rancher/rancher#5463]
**Rancher Version:** 1.01

**Docker Version:** 1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):** RancherOS v0.4.4 on baremetal

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** 1 server, 4 nodes, DB in dedicated container

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:** Unknown

**Results:** VPN Missing

**Expected:** VPN Present

I have a set of four hosts and thus any one host would normally have three VPN connections (or three pairs of SAs) to the other hosts. I have a situation where one SA between two hosts has 'disappeared'. I can't see any obvious reason for this. IPs below changed for the usual reasons.

Using `swanctl --list-conns` shows a `conn-10.11.12.99` that obviously hasn't been established. Using `swanctl --initiate conn-10.11.12.99` just results in an `initiate failed: missing configuration name` error. Perhaps I'm not specifying the correct name or object though?

I'm seeing this in the **/var/log/charon.log** file on one of the hosts that has lost an SA (10.11.12.99 is the other end of the missing SA):

    Jul 18 06:00:23 11[KNL] creating delete job for CHILD_SA ESP/0x00000000/10.11.12.99
    Jul 18 06:00:23 11[JOB] CHILD_SA ESP/0x00000000/10.11.12.99 not found for delete
    Jul 18 06:00:23 08[KNL] creating acquire job for policy 10.42.24.153/32[tcp/54566] === 10.42.155.10/32[tcp/http-alt] with reqid {1234}
    Jul 18 06:00:23 06[CFG] trap not found, unable to acquire reqid 1234

I'm seeing this in the **/var/log/rancher-net.log** file on one of the hosts that has lost an SA (10.11.12.99 is the other end of the missing SA):

    time="2016-07-18T08:07:42Z" level=info msg="Added policy: {Dst:10.42.197.230/32 Src:10.42.0.0/16 Dir:dir out Priority:0 Index:0 Tmpls:[{Dst:10.11.12.99 Src:172.17.0.2 Proto:esp Mode:tunnel Reqid:1234}]}" 

Output of the `swanctl --stats` command on one of the hosts that has lost an SA:

    uptime: 14 days, since Jul 04 01:00:11 2016
    worker threads: 16 total, 11 idle, working: 4/0/1/0
    job queues: 0/0/0/0
    jobs scheduled: 6
    IKE_SAs: 2 total, 0 half-open <<<SHOULD BE 3!
    mallinfo: sbrk 2433024, mmap 0, used 333888, free 2099136

Output of `ip xfrm state` on the same host, note the first SA which should be up but isn't and has some weird values:

    src 172.17.0.2 dst 10.11.12.99
        proto esp spi 0x00000000 reqid 1234 mode tunnel
        replay-window 0 
        sel src 10.42.24.153/32 dst 10.42.204.94/32 proto tcp sport 55510 dport 8080 dev eth0 
    src 172.17.0.2 dst 10.11.12.88
        proto esp spi 0xc9bbb136 reqid 1234 mode tunnel
        replay-window 32 flag af-unspec
        auth-trunc hmac(sha1) 0x77d83c0e6bec06fba2795ceb2780ed4620ad3865 96
        enc cbc(aes) 0xc37aa496ce62520966c60a44d81b1483
        encap type espinudp sport 4500 dport 4500 addr 0.0.0.0

I have some questions while we are here, if anyone can answer them and make this easier to troubleshoot next time:

Q1. Where does the VPN configuration come from and where is it stored? I can't find any file that seems to contain it on any host.

Q2. How do I get the missing SA back up safely? I know I could restart the agent on each end but I'd rather be more specific and have a lower impact.

**Comment by leodotcloud** [comment]
Answer to your Q1: `/var/lib/cattle/etc/cattle/ipsec/config.json`


Snip from the output of `ps -ef`
```
/var/lib/cattle/bin/rancher-net --log /var/log/rancher-net.log -f /var/lib/cattle/etc/cattle/ipsec/config.json -c /var/lib/cattle/etc/cattle/ipsec -i 172.17.0.2/16 --pid-file /var/run/rancher-net.pid --gcm=true
```

**Comment by sjiveson** [comment]
Brilliant, thank you @leodotcloud.

**Comment by sjiveson** [comment]
For everyone else's benefit, I raised a support ticket with Rancher last night. Whilst I wasn't advised of a way to re-establish just the missing SA, this command restarted the Charon process very quickly and thus re-established all the SAs/tunnels: `monit restart charon`. This saved me from the rather longer process of restarting the Network Agents themselves.
