### ISSUE TITLE
Cross-Host Communication Issue

### ISSUE THREAD

**Issue by drdocker** [rancher/rancher#5466]
**Rancher Version:** 1.1.1

**Docker Version:** 1.11.2

**OS and where are the hosts located? (cloud, bare metal, etc):** CentOS 7 on all boxes - Mix between Cloud and Bare Metal servers

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

Single Node Rancher Master
3x Rancher Hosts

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**  Cattle!

**Steps to Reproduce:**

I've encountered a strange issue as it relates to Cross-Host Communications. Today, I created some new boxes. One box was in OVH's VPS (*Rancher Server* and *Host* containers on this box), the other box was on OVH's bare metal server (same data center - *Rancher Host*), and the last box was in Digital Ocean (*Rancher Host*).

Each of the boxes were created from scratch, using a single command to setup the latest version of Docker:  `curl -sSL https://get.docker.com/ | sh`

After starting and enabling Docker, I then went to add the host machines.

*OVH VPS Host*:  For this, from my Rancher administrative page, I selected "Custom" Host, and typed in the command that Rancher provided. This includes entering in the `CATTLE_AGENT_IP`, where I typed in the *public* IP of the VPS.

*OVH Bare Metal Host*: Again, from the administrative page, I selected "Custom" Host, and typed in the command that Rancher provided. I also included the `CATTLE_AGENT_IP` -- the public IP of the Bare Metal Machine.

*Digital Ocean Host*: I selected "Custom" Host, and repeated the above steps, including adding the `CATTLE_AGENT_IP`

All of my hosts were then registered in Rancher/Cattle, as expected. 

I then added the same container on each of the three hosts.

**Results:** 

*OVH VPS Host:* Containers worked as expected, and through the Internal Rancher Network Agent IP (provided by selecting the checkbox on the top right of the Hosts page), I was able to ping the *Digital Ocean Host*, but not the OVH Bare Metal Host.

*OVH Bare Metal Host:* I was able to deploy the container to this host, however, I was *unable* to ping any of the other two hosts. Neither the Digital Ocean Host, nor the OVH VPS Host would reply to my Network Agent ping requests.

*Digital Ocean Host:* Containers worked as expected, and through the Internal Rancher Network Agent IP, I was able to ping the OVH VPS Host, but not the OVH Bare Metal Host.

This unexpected behavior leads to a variety of issues, but namely, I am unable to use a cross-networked load balancer since all of the services on the *OVH Bare Metal Host* come up as a 503 error. 

When using a load balancer directly on the *OVH Bare Metal Host*, I am able to see the services located on the host itself, but I am not able to receive responses from any of the other hosts. The load balancer also stays in a permanent? *Initializing* state (my tests ran for 2 hours). While it works, it's not working as expected since it only can see the services located on the same machine as itself.

Help! Thanks in advance! 👍

**Comment by leodotcloud** [comment]
Generally the first thing to make sure when Cross host networking is not working as expected is to check if the UDP ports (500 and 4500) are open. Does OVH have some kind of security groups or other settings similar to AWS? Do you have to open the ports for every Host that you create? Are both the OVH hosts running the same version of the OS?

**Comment by drdocker** [comment]
@leodotcloud - Thanks so much for your reply. Indeed, I checked to see that the ports are open, and I'm not presently enforcing any additional security settings on the machines (default leaves everything active). 

While looking through the system, I noticed that OVH has a custom kernel that they run on their bare metal machines. This kernel is identified as **CentOS 7-3.14.32-xxxx** 

I reinstalled my system using the standard Kernel provided by CentOS 7 (3.10.0-327). Upon doing this, and repeating the steps above, I was able to successfully *ping* my server through the Network Agent IP.  The load balancer also started working.

This is resolved. 

Thanks.

**Comment by leodotcloud** [comment]
@drdocker : Glad it is working now!

If you get a chance, is it possible to check the settings of the following kernel config flags for the custom kernel of OVH?

```
CONFIG_INET_XFRM_MODE_TRANSPORT=y
CONFIG_BRIDGE=y
CONFIG_FIREWALL=y
CONFIG_NET_ALIAS=y
CONFIG_INET=y
CONFIG_IP_FORWARD=y
CONFIG_IP_MULTICAST=y
CONFIG_IP_FIREWALL=y
CONFIG_IP_FIREWALL_VERBOSE=y
CONFIG_IP_MASQUERADE=y
CONFIG_NET=y
```

It is expected for these flags to be not set to `n`.
