### ISSUE TITLE
Show all listeners, sources, and targets associated with a LB

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#547]
Server version - V0.16.3

Currently , in the Load Balancers list view , we see the list hosts and targets associated with this Load Balancer. It would be also useful to list the all the listener - source and target ports associated with this LB.

**Comment by deniseschannon** [comment]
I believe this view doesn't exist anymore as this was related to standalone load balancers, which no longer exists.

**Comment by vincent99** [comment]
I suppose, but the same is true of lb services

**Comment by vincent99** [comment]
![image](https://cloud.githubusercontent.com/assets/753917/20681757/3d537e46-b562-11e6-861b-e038cc38084a.png)
