### ISSUE TITLE
Provide information about additional ports that need to be opened on Amazon Security group when launching hosts on mesos environment.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#5471]
Rancher Version:v1.1.1

Currently there is no visual indication of the additional ports that need to be opened on Amazon Security group when launching mesos or marathon on Rancher.

@LLParse confirmed that we should open TCP Port 5050 and port 5051 on nodes, and whatever TCP port they use for Marathon (default 8080)

**Comment by LLParse** [comment]
Without making UI changes, we could at least add `expose: {port}` to each container definition in the template so that the port numbers appear in the system stack. We hide the system stack from the user by design, so this may not be sufficient, but it is better than nothing.
