### ISSUE TITLE
Unable to use parameterized service name in catalog entry

### ISSUE THREAD

**Issue by cavemandaveman** [rancher/rancher#5472]
**Rancher Version:** 
v1.1.0

**Docker Version:** 
1.11.2

**OS and where are the hosts located? (cloud, bare metal, etc):** 
Ubuntu VM

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** 
single node, internal db

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Create a catalog item and in the questions section add a string variable, then use that variable in a docker compose file as the name of the service.

rancher-compose.yml:

``` javascript
.catalog:
  questions:
    - variable: "SERVICE_NAME"
      type: string
      required: true
```

docker-compose.yml:

``` javascript
${SERVICE_NAME}:
  labels:
    io.rancher.scheduler.global: true
    io.rancher.container.pull_image: always
  image: ${SERVICE_NAME}:latest
```

**Results:** 
Service is stuck Activating with the following error:
`Invalid service name '${SERVICE_NAME}' - only [a-zA-Z0-9\._\-] characters are allowed`

**Expected:**
Rancher should populate the first instance of ${SERVICE_NAME} like it does the second instance in the example docker-compose.yml before launching the service

**Comment by joshwget** [comment]
Interpolation is only performed on values and not keys. This is how Docker Compose currently behaves and we try to be as compatible as possible with them. It's possible this functionality will be added to Docker Compose in the future, but I don't know of any open issues for it.

**Comment by cavemandaveman** [comment]
In order to not break compatibility with Docker Compose, maybe Rancher can include some kind of override on the service name? 

Something like a label of `io.rancher.service.name.override` where you provide a string value might work. That way, the end user can parameterize the key to the label instead of the service name directly.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
