### ISSUE TITLE
Rancher Node not showing up in web interface after re-install. 

### ISSUE THREAD

**Issue by crobles-ppfa** [rancher/rancher#5473]
*Describe your issue here*

In our development tree. We deleted all nodes due to a mishap of our hosting provider which cloned an existing rancher node and powered it on. This overwrote names in the UI. We deleted and purged the old nodes and attempted to re-initialize, but now that are not showing up in the web interface.

sudo docker run -e CATTLE_AGENT_IP="10.100.0.XXX"  -d --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.0.2 http://10.100.0.XXX:8080/v1/scripts/XXXXX:XXXXX

Rancher and cattle are current versions.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.1.0` Cattle: `v0.165.4` UI: `v1.1.12` |
|Access|`github` `admin`|
|Orchestration|`Cattle`|
|Route|`hosts.index`|

**Comment by deniseschannon** [comment]
Can you try running this on the node and then re-register?

`rm -rf /var/lib/rancher/state; docker rm -fv rancher-agent; docker rm -fv rancher-agent-state`

**Comment by crobles-ppfa** [comment]
I ended up having the node reallocated as we needed it back into rotation. I tried nearly everything but that. I figured it was tied to a UUID or something that was preventing it from re-registering. I will be adding some other nodes in the next few weeks and will try to reproduce this error and try your workaround. Thank you.

**Comment by deniseschannon** [comment]
@crobles-ppfa I'll close until you can reproduce again.

**Comment by raph** [comment]
Had the same problem and it was caused by conflicting hostnames, rancher should throw an error somewhere when a host with an already existing hostname tries to register
