### ISSUE TITLE
Rancher Catalog stops parsing templates if yml syntax error is encountered

### ISSUE THREAD

**Issue by cwundram** [rancher/rancher#5475]
**Rancher Version: 1.0.1**

**Docker Version: 1.10**

**OS and where are the hosts located? (cloud, bare metal, etc):** AWS/Ubuntu 14.04

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** Single Node

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:** 
Create a series of catalog template versions in the same catalog entry.  (say test/1 test/2 & test /3.  
Put a tab or some kind of invalid yml in test/2
Refresh the catalog, select test, and click the drop down list

**Results:** 
only the version in test/1 will appear.   Even if the yml in test/3 is fine, rancher will stop parsing at test/2.

**Expected:**
We should see all the valid catalog entries in the drop down list.

**Comment by tfiduccia** [comment]
Version 1.1.1
@cwundram - I cannot reproduce this in our current build.  Please upgrade to 1.1.1
