### ISSUE TITLE
Ingress controller syncs up with Rancher LB services, not just ones from dedicated stack

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#5477]
Steps to reproduce:

1) Start k8s system stack
2) Create any k8s load balancer service. Corresponding LB service gets created in Rancher. Name the LB service "foo"
3) Create an ingress with name "foo"
4) Restart ingress controller. 

Bug: there are actually 2 issues:

* ingress controller fetches load balancer services from the stack dedicated to the k8s lb services
* ingress controller relies on "-" as a separator in name, so if that doesn't happen, the error is raised. With the steps above, you will see panic error in ingress-controller

**Comment by sangeethah** [comment]
The latest ingress controller used for v1.2 is rancher/ingress-controller:v0.1.3 which was built on  2016-06-03.

@alena1108 , Could you provide a  k8s template that uses latest ingress controller image with the fixes ?

**Comment by alena1108** [comment]
this would be the image: rancher/lb-controller:v0.2.1, and this would be the template: 

https://github.com/rancher/rancher-catalog/tree/master/templates/k8s/7
and https://github.com/rancher/rancher-catalog/tree/master/templates/k8s/10

we would have to backport this issue to 1.2 k8s templates

**Comment by soumyalj** [comment]
Tested with 1.1.3 and reproduced using the the following steps.
1. Create an ingress with name foo
2. Create a Loadbalancer with name foo through rancher UI
3. Delete the ingress through UI in the "kubernetes-ingress-lbs" stack
4. Restart the ingress controller
Observed that ingress does not recreated as there is another loadbalancer with the same name.

Verified using 1.1.4-rc1 using the above steps. The ingress was recreated after restarting the ingress controller.
