### ISSUE TITLE
rancher agent start failed with "ERROR: Please re-register this agent"

### ISSUE THREAD

**Issue by linsheng9731** [rancher/rancher#5479]
**Rancher Version:**
rancher/agent:v1.0.2

**Docker Version:**
Server Version: 1.11.2

**OS and where are the hosts located? (cloud, bare metal, etc):**
aws 
4.4.11-23.53.amzn1.x86_64

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
rancher-server work for other agent

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
cattle 

**Steps to Reproduce:**

**Results:** 
agent start failed  with 

```
> ERROR: Please re-register this agent
> ERROR: Please re-register this agent
> ERROR: Please re-register this agent
> ERROR: Please re-register this agent
> ERROR: Please re-register this agent
> ERROR: Please re-register this agent
> ERROR: Please re-register this agent
> ERROR: Please re-register this agent
> 
```

**Expected:**

**Comment by deniseschannon** [comment]
Can you try this command and then re-register?

```
rm -rf /var/lib/rancher/state; docker rm -fv rancher-agent; docker rm -fv rancher-agent-state
```

Have you used this host before in a Rancher environment?

**Comment by linsheng9731** [comment]
thanks ,it works , i really used this host . May i add this issue to troubleshooting ?https://github.com/rancher/rancher.github.io/blob/master/rancher/v1.0/zh/faqs/troubleshooting/index.md

**Comment by deniseschannon** [comment]
It's in this section:

http://docs.rancher.com/rancher/latest/en/faqs/agents/

**Comment by jmahowald** [comment]
Just as FYI, I ran into the same issue, but the suggested fixes aren't valid.  Also the host wasn't in an environment before .

**Comment by deniseschannon** [comment]
@jmahowald Is this host running rancher/server? It's a brand new host?

**Comment by jmahowald** [comment]
Sorry, should have updated.  I blew everything away and recreated and it was working.

**Comment by orchmaster** [comment]
Hello
I encounter similar issue. I am seeing frequent issue on different nodes within the cluster. I am using Rancher v1.6.5 and Agent running v1.2.5. From my Docker Agent log here's what I see and also the host is getting disconnected from the K8S cluster that was deployed from Rancher UI.

Found state.json: 7bb3c8ba83b9060ff8b1e4f41f389a71c8b30bd12474cd357dc64db126ae0a19
time="2017-08-14T15:26:06Z" level=info msg="Execing [/usr/bin/nsenter --mount=/proc/12829/ns/mnt -F -- /app/docker/overlay/dbbeeece88310d3ad3ced5d6653c52d01c494313879d40e942e6d65bc68e058a/merged/usr/bin/share-mnt --stage2 /var/lib/rancher/volumes /var/lib/kubelet -- norun]" 
ERROR: Please re-register this agent


Thanks
Devarshi

**Comment by jdobyns** [comment]
@deniseschannon  any other ideas? removing /var/lib/rancher/state does not resolve this for me.

running rancher v1.6.25

`root@rancher-2:/var/lib/rancher# rm -rf /var/lib/rancher/state; docker rm -fv rancher-agent; docker rm -fv rancher-agent-state

rancher-agent
Error response from daemon: No such container: rancher-agent-state

root@rancher-2:/var/lib/rancher# sudo docker run -e CATTLE_AGENT_IP="10.10.10.52"  --rm --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.2.11 https://rancher.opsflo.io/v1/scripts/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

INFO: Running Agent Registration Process, CATTLE_URL=https://rancher.opsflo.io/v1
INFO: Attempting to connect to: https://rancher.opsflo.io/v1
INFO: https://rancher.opsflo.io/v1 is accessible
INFO: Configured Host Registration URL info: CATTLE_URL=https://rancher.opsflo.io/v1 ENV_URL=https://rancher.opsflo.io/v1
INFO: Inspecting host capabilities
INFO: Boot2Docker: false
INFO: Host writable: true
INFO: Token: xxxxxxxx
INFO: Running registration

INFO: Printing Environment
INFO: ENV: CATTLE_ACCESS_KEY=043B2CF8FAC5CCA109D3
INFO: ENV: CATTLE_AGENT_IP=10.10.10.52
INFO: ENV: CATTLE_HOME=/var/lib/cattle
INFO: ENV: CATTLE_REGISTRATION_ACCESS_KEY=registrationToken
INFO: ENV: CATTLE_REGISTRATION_SECRET_KEY=xxxxxxx
INFO: ENV: CATTLE_SECRET_KEY=xxxxxxx
INFO: ENV: CATTLE_URL=https://rancher.opsflo.io/v1
INFO: ENV: DETECTED_CATTLE_AGENT_IP=172.17.0.1
INFO: ENV: RANCHER_AGENT_IMAGE=rancher/agent:v1.2.11
INFO: Launched Rancher Agent: 5a7c476fd99c836b2eb9415350f1c8069ad28eb58ec5b212d2eecb6a686ab22f

root@rancher-2:/var/lib/rancher# docker logs -f 5a7c476fd99c
Found container ID: 78e33719feb8181dfec8fa2547c47f726060c9d77efd5037c9544c91ae5bf62e
Checking root: /host/run/runc
Checking file: 5a7c476fd99c836b2eb9415350f1c8069ad28eb58ec5b212d2eecb6a686ab22f
Checking file: 78e33719feb8181dfec8fa2547c47f726060c9d77efd5037c9544c91ae5bf62e
Found state.json: 78e33719feb8181dfec8fa2547c47f726060c9d77efd5037c9544c91ae5bf62e
time="2018-12-14T20:17:03Z" level=info msg="Execing [/usr/bin/nsenter --mount=/proc/27785/ns/mnt -F -- /var/lib/docker/overlay/d95f378d7ab87476ca017041d05024a8deb9407da4243dc11237e41bc09e2026/merged/usr/bin/share-mnt --stage2 /var/lib/rancher/volumes /var/lib/kubelet -- norun]" 
ERROR: Please re-register this agent
`

**Comment by WingsLikeEagles** [comment]
I know this is closed, but a solution might be to add the host again (without removing it).
