### ISSUE TITLE
Implement VPN Overlay Monitoring

### ISSUE THREAD

**Issue by sjiveson** [rancher/rancher#5483]
**Rancher Version:** 1.0.1

**Docker Version:** 1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):** RancherOS v0.4.4 on bare metal

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** 1 server, 4 nodes, DB in dedicated container

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:** VPN Fails for unknown reasons

**Results:** There is currently no way to monitor VPN status or be alerted should a VPN/SA fail (or the entire Charon service for that matter)

**Expected:** Failures can be monitored and alerting possible

Hey,

Based on our experiences with a VPN/SA failure between two of our four container hosts (as detailed in 
https://github.com/rancher/rancher/issues/5463) we've been investigating how we might detect such failures in future. This is proving to be particularly difficult. Even just monitoring the Charon service itself is challenging.

We're hampered by a few things;
- The network agent is a standalone container and thus not part of the managed network or accessible over it. This prevents us from accessing the Monit API/web interface, even through a ranch-eye style proxy (as it only binds to localhost).
- The network agent uses bridge mode networking, preventing us querying the host's TCP/IP stack via `ip xfrm` commands
- We don't want to do anything within the network container itself as a) not standard and b) we'll lose these changes on a restart or upgrade etc.

This only really leaves us with the option of running docker exec commands (such as `docker exec -it rancher-agent /sbin/ip xfrm state count`) against the network agent container, which is far from ideal.

Any ideas anyone? Quite happy to contribute in any way we can.

**Comment by Rucknar** [comment]
It would be really great if we could access this status through another container, we could extend ranch-eye to expose this info on a separate port.

**Comment by superseb** [comment]
Since v1.6.13 we have another sidekick for ipsec checking the tunnels and reporting to when `/connectivity` is hit. It's included in ipsec v0.2.2 and higher.

**Comment by sjiveson** [comment]
Brilliant, many thanks.
