### ISSUE TITLE
LDAP login using rancher behavior change

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#5485]
**Expected:**
Making the login domain visible/a note saying what the default domain is. Possibly a help text denoting domain/user as valid login. Lightweight enhancement, full blown ideal enhancement below.

**Comment by aemneina** [comment]
On the LDAP Domain login experience, ideally users only type user ID and password without the need for providing AD domain. Rancher should be able to bind into active directory at the top forest level and query subdomains.

**Comment by deniseschannon** [comment]
Already exists in v2.0. 

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
