### ISSUE TITLE
GlusterFS daemon containers aren't inheriting network namespaces when they should

### ISSUE THREAD

**Issue by LLParse** [rancher/rancher#5486]
**Rancher Version:** master, 07/20/2016 @ 12:47PM MST

**Docker Version:** 1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):**  Ubuntu 14.04.4 LTS, Digital Ocean

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single node

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:**
1. Create a cattle environment with 3 hosts
2. Launch glusterfs template

**Results:** 
server and daemon containers get different network namespaces

**Expected:**
server and daemon containers share same network namespace

**Comment by LLParse** [comment]
This behavior only manifests itself in master, 1.1.1 functions as expected

**Comment by tfiduccia** [comment]
glusterfs catalog won't work without this being fixed.  There could also be customer's catalogs that will no longer work without this fixed.

**Comment by LLParse** [comment]
We came to the conclusion that this is a non-issue and should instead be fixed by removing the label `io.rancher.container.network: 'true'` from the template for containers trying to inherit network namespaces. Doing so tells a container to inherit another container's network namespace, but also add Rancher networking to the container.

**Comment by LLParse** [comment]
https://github.com/rancher/community-catalog/pull/223

**Comment by sangeethah** [comment]
Tested with v1.2.0-pre1-rc4.
Docker Version: 1.10.3

Able to create stacks from GlusterFs and ConvoyGluster  successfully.
Able to create services tha uses volumes from convoy-gluster volume driver.
