### ISSUE TITLE
Implementing an Admin group within rancher that can be tied to an AD group

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#5488]
have a LDAP group map all users to the admin role within rancher.

**Comment by fuhbar** [comment]
Agree. The concept is quite confusing that the first user which logs into rancher after activating LDAP/AD auth provider is the admin user. This makes is especially difficult for automating the setup process.

**Comment by fuhbar** [comment]
Furthermore, it would be quite helpful for having an admin user beside the particular auth provider enabled. So even if this above mentioned AD/LDAP group resolves to no user, that you are able to manage your setup.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
