### ISSUE TITLE
K8s - If you edit and cancel all expanded items are closed

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#5490]
**Rancher Version:** Version 1.2.0-rc1

**Steps to Reproduce:**
1.  Setup up k8s environment
2.  Add a catalog item (wordpress or something)
3.  Go to Pods and expand wordpress (click on the +)
4.  Edit Container
5.  Cancel

**Results:** expanded pod is no longer expanded.  In all of the k8s pages, if I expand then edit/save or edit/cancel I end up with everything unexpanded again and have to reopen to get back to where I was.

**Expected:**

**Comment by vincent99** [comment]
No longer applicable in 1.4.
