### ISSUE TITLE
k8s - Upgrading is showing all version instead of just the upgradable versions

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#5494]
**Rancher Version:** v1.2.1-pre1-rc1

**Steps to Reproduce:**
1.  Setup kubernetes environment
2.  In settings add the qa-catalog 
3.  Go to catalog and deploy the Deployment Upgrade Catalog (version 1)
4.  Go to Stacks and click on Upgrade for deployment and go to version 2 and click finish upgrade
5.  Click on Upgrade again

**Results:** All versions are showing up.  The upgrade button is not passing the minimum version.

**Expected:** Only valid versions

**Comment by vincent99** [comment]
@mrajashree This happens only when minimumRancherVersion is sent, there are keys with empty URLs sent for upgradeVersionLinks

![image](https://cloud.githubusercontent.com/assets/753917/17007927/818551ac-4ea1-11e6-96a5-f77719a8a55f.png)

**Comment by mrajashree** [comment]
PR for this change: https://github.com/rancher/rancher-catalog-service/pull/61

**Comment by mrajashree** [comment]
Reopening for verficiation

**Comment by tfiduccia** [comment]
Version - master 8/11
Verified fixed
