### ISSUE TITLE
添加自定义catalog， 添加新组件，不能自动刷新

### ISSUE THREAD

**Issue by OliverVin** [rancher/rancher#5496]
添加自定义catalog， 添加新组件，不能自动刷新~

需要注销一次才会成功

**Comment by tfiduccia** [comment]
@OliverVin This is not a bug, the catalog is refreshed every 5 minutes.  There is also a refresh button on the upper right that will pull any updates.

**Comment by OliverVin** [comment]
thank you, i found it
