### ISSUE TITLE
How create data volume rancher 

### ISSUE THREAD

**Issue by RotemEmergi** [rancher/rancher#5497]
Hello , 

How create data volume on with convoy-gluster
On rancher add  volume  ?

**Comment by tfiduccia** [comment]
test setup that works:

1.  Add an Environment (I like to have three hosts in it)
2.  After host setup, go to catalog and deploy glusterfs catalog
3.  After glusterfs service is complete and running, go to Convoy-Gluster catalog 
4.  In GlusterFS Service field select glusterfs-server
5.  Deploy catalog
6.  Two different things:
     A.  create a service and in Volumes tab set
           Volumes to your path/volumename 
           Volumes Driver field set to convoy-gluster
     B.  Add Volume in Storage Pool page & add service and in Volumes Tab use that volumename and still set Volume Driver to convoy-gluster

There is a small bug on the storage pool page where you have to refresh the page to see the volumes.  So refresh browser and everything should show up.  
There are also docs regarding persistent storage service here if you need more info that isn't convoy specific http://docs.rancher.com/rancher/latest/en/rancher-services/storage-service/.
