### ISSUE TITLE
Running state not synchronising after restarting Rancher server

### ISSUE THREAD

**Issue by kevin-thorpe** [rancher/rancher#5498]
**Rancher Version:**
v1.1.0-dev3 (planning upgrade this weekend)

**Docker Version:**
1.10 or 1.11 (not important I think)

**OS and where are the hosts located? (cloud, bare metal, etc):**
Centos 7, KVM VM on Nutanix

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node, Internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Start a container on the cluster.
Back up the Cattle database using mysqldump
Stop the above container.
Restore the Cattle database and restart Rancher server

**Results:** 
The above container is still marked as running

**Expected:**
The above container should be marked as stopped

Full details at https://forums.rancher.com/t/running-state-not-synchronising-after-restarting-rancher-server/3485

**Comment by deniseschannon** [comment]
We should do a sync with the actual host every 5 minutes, so after awhile does the container get reported correctly?

**Comment by kevin-thorpe** [comment]
I don't have an environment I can play with during working hours. Even test gets used by the developers. I am planning to upgrade another Rancher environment this weekend so will re-test this.

**Comment by deniseschannon** [comment]
@kevin-thorpe Keep me updated if you are able to re-test this.

**Comment by aemneina** [comment]
Closing out, if you ever get a repro with a modern version of rancher, please do reopen or file a new issue.
