### ISSUE TITLE
[Load Balancer] Add "send proxy" haproxy funktionality

### ISSUE THREAD

**Issue by tknecht** [rancher/rancher#5500]
**Rancher Version:** latest

**Environment Type:** Cattle

**Feature:** 
Loadbalancer only accepts haproxy config for default and global section of haproxy.conf
To use proxy protocol (https://github.com/horms/haproxy/blob/master/doc/proxy-protocol.txt) it is necessary to add "send proxy" at the end of server settings line. Adding it manually works fine, but it'll not be persistent. It would be great to have an option to activate this function in the frontend.

**Comment by vincent99** [comment]
https://github.com/rancher/rancher/issues/2179 , in progress now.
