### ISSUE TITLE
Feature Request: more stack upgrade options in rancher-compose.yml

### ISSUE THREAD

**Issue by lesaux** [rancher/rancher#5502]
It would be nice to be able to specify upgrade options such as "batch_size" directly in the rancher-compose.yml file.

**Comment by deniseschannon** [comment]
@lesaux Not sure if you know, but we do offer these options in the CLI directly. 

http://docs.rancher.com/rancher/latest/en/cattle/rancher-compose/upgrading/#in-service-upgrade

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
