### ISSUE TITLE
Production environment flag and UX options

### ISSUE THREAD

**Issue by allingeek** [rancher/rancher#5503]
_Rancher UI Feature Request_

In my experience with these systems it is important to have a flag marking an environment as "production" which enables certain UX enhancements designed to warn/remind users. Something as simple as a theme adjustment for marked environments can be enough to prevent common mistakes.

**Comment by vincent99** [comment]
@allingeek We can maybe do something better later, but I can sneak this in now..

In the browser console, run`l('service:prefs').set('bodyBackground','any CSS background value');` (and then reload, it's not dynamic).

**Comment by allingeek** [comment]
Ignoring for a moment the UX enhancements that would be made possible by this addition, there are a substantial number of orchestration features that users might want to enable or disable based on this metadata. Consider account/stack/service deployment linting policies. I think it would be a simple but foundational enhancement even in the absence of the aforementioned UX enhancement.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
