### ISSUE TITLE
Delete not functioning in Kubernetes

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#5505]
**Rancher Version:**: v1.2.0-pre1-rc1

**Docker Version:**: 1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):**: Ubuntu, Cloud

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**: Kubernetes

**Steps to Reproduce:**
1. Create a Kubernetes environment using https://github.com/rancher/qa-catalog/
2. Create a namespace "test1" through UI or through kubectl
3. Delete a namespace using the UI

**Results:** 
Namespace cannot be deleted through UI. Error message below

<img width="1436" alt="screen shot 2016-07-21 at 11 39 07 am" src="https://cloud.githubusercontent.com/assets/18536626/17034525/df5a9076-4f37-11e6-88eb-c700d9badce4.png">

Note: Namespace deletion through kubectl works fine.

**Comment by tfiduccia** [comment]
Error in dev tools for this: 
http://8.35.192.141:8080/r/projects/1a8/kubectld:8091/v1-kubectl/delete?defaultNamespace=default&arg=%5Bobject%20Object%5D&arg=undefined 500 (Internal Server Error)

**Comment by tfiduccia** [comment]
Checked other areas and delete is not working anywhere in Kubernetes environment.  Tried replication sets, deployments, pods, etc....

**Comment by tfiduccia** [comment]
Delete is still not functioning

**Comment by tfiduccia** [comment]
Version - v1.2.0-pre1-rc4
Checked 1.2 and 1.3 k8s delete functional
Verified fixed
