### ISSUE TITLE
Feature request - Add image id to container self metadata

### ISSUE THREAD

**Issue by sra** [rancher/rancher#5506]
It would be exceptionally useful to have access to the image id used to start a container. Both for debugging/troubleshooting and maybe to have access for display.

Something like: 
`curl rancher-metadata/latest/self/container/image_id`

It looks like the data is already in the `Instance` model as `getImageId()` maybe it is as easy as exposing it on the `ContainerMetaData` class?

**Comment by GiGurra** [comment]
This would indeed be very useful.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
