### ISSUE TITLE
Sorting by nfs share on backup target page is not sorting properly

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#5509]
**Rancher Version:** v1.2.0-pre1-rc1

**Steps to Reproduce:**
1.  Create an environment and enable VM
2.  Go to Backup Target page
3.  Create three targets and have
Name = target1, nfs share = nfsshare4
Name = target2, nfs share = nfsshare6
Name = target3, nfs share = nfsshare5
4.  Sort by nfs share

**Results:** Sorting by Name, not by share
![image](https://cloud.githubusercontent.com/assets/11514927/17041568/ad124cb6-4f5b-11e6-872e-8f5f28c067e1.png)

**Expected:** Should either sort by share or remove sorting

**Comment by vincent99** [comment]
n/a to modern versions
