### ISSUE TITLE
Dataonly container dependency error

### ISSUE THREAD

**Issue by nmoturi** [rancher/rancher#5511]
Hi - When a container is being created with volumes-from option which has a dataonly container not running (no need in this case), causing dependency issue and expecting the dataonly container be running. Below is the scenario trying to achieve 

1) docker run -v /var/lib/postgresql -v /var/log/postgresql  --name pgdataonly busybox true

2) docker run --rm --volumes-from pgdataonly --name "pg" xxx/postgresql

Thanks,
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.1.1` Cattle: `v0.165.7` UI: `v1.1.12` |
|Access|`github` `admin`|
|Orchestration|`Cattle`|
|Route|`container.labels`|

**Comment by deniseschannon** [comment]
This is possible today with no need for a running data container. 

How have you tried to set this up in Rancher?

**Comment by nmoturi** [comment]
I got this working in rancher using sidekick option, was testing few options related to volumes..old method and new use of volume-from
