### ISSUE TITLE
Removed host cannot be added again

### ISSUE THREAD

**Issue by kapolos** [rancher/rancher#5514]
**Rancher Version:**

`1.1.1`

**Docker Version:**

````
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:11 2016
 OS/Arch:      linux/amd64
````

**OS and where are the hosts located? (cloud, bare metal, etc):**

CentOS over ESXi

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

single node rancher, 4 hosts, internal db

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

Cattle

**Steps to Reproduce:**

* Power failure on all hosts
* After reboot, all hosts and their containers start normally except the host that rancher server runs (Host A).
* On Host A, containers fail to start. I also notice that the Networking Agent keeps restarting.
* Stopped & removed all the agents on Host A. Upgraded Rancher server from 1.1.0 to 1.1.1 as per the manual's instructions.
* Rancher server works fine on Host A and Network agent does not seem to restart any more. Still, containers fail to initialize (actually all the containers on Host A are Load Balancers connected to container on other hosts). I see that some fail because they can't satisfy their label requirements (they were tied to Host A). The host shows the labels on the UI but clearly not the same is true for the containers.
* I notice that Host A is in Reconnecting status. I disconnect and reconnect manually. Still stuck on Reconnecting.
* I remove the host.
* I cannot add the host again. Following the instructions doesn't make the host appear - I did explicitly specify the IP. `docker ps` shows that the agent is running uninterrupted.

**Results:** 

* Host A never registers again.

**Expected:**

* Host A should have re-appeared on the list

I did `rm -rf /var/lib/rancher/state` as per the instructions on https://github.com/rancher/rancher/issues/225 but no difference.

Any ideas?

**Comment by deniseschannon** [comment]
Can you try running this command before re-registering the host? 

`rm -rf /var/lib/rancher/state; docker rm -fv rancher-agent; docker rm -fv rancher-agent-state`

Also, were your other hosts able to re-register with no issue?

**Comment by kapolos** [comment]
@deniseschannon Thank you for your post!

Neither `rancher-agent` nor `rancher-agent-state` containers where running (only `rancher/server:latest`) So trying to add the host did not make any difference (no new host on the list). I suppose the agent eventually exits on its own if it does not connect (it is currently running after the "add host" process)? No `rancher-agent-state` this time either though.

I haven't tried de-registering any other hosts. If it's necessary I will, please let me know.

**Comment by deniseschannon** [comment]
Are your other hosts connected back to Rancher server? Did the IP change of your host A?

**Comment by kapolos** [comment]
Yes 3 out of 4, with the missing one being the one that runs the Rancher server. The IPs are statically assigned and have not changed. They are fully routable and no firewall exists in any host.

**Comment by deniseschannon** [comment]
Can you do a `docker ps -a` on your Host A for me? And try to run the command and then send me another `docker ps -a`?

**Comment by kapolos** [comment]
Before:

````
[root@localhost ~]# docker ps -a
CONTAINER ID        IMAGE                                     COMMAND                  CREATED             STATUS                      PORTS                              NAMES
9e25ae589d56        rancher/agent:v1.0.2                      "/run.sh http://198.2"   26 minutes ago      Exited (1) 11 minutes ago                                      reverent_hypatia
537f7aeab64e        rancher/agent:v1.0.2                      "/run.sh http://198.2"   3 days ago          Exited (1) 3 days ago                                          goofy_bhaskara
2b510bdfbfc5        rancher/server:latest                     "/usr/bin/s6-svscan /"   3 days ago          Up 3 days                   3306/tcp, 0.0.0.0:8080->8080/tcp   pedantic_kirch
5ad1b13c5e02        2ac1c28a8235                              "/usr/bin/s6-svscan /"   3 days ago          Created                                                        rancher-data
2b0bf46871f9        kapolos/embercli:2.7.0-beta5_node-6.2.2   "bash"                   7 days ago          Exited (0) 4 days ago                                          073999bd-6cd3-4236-90db-a0a85d7e092c
2633bf08c9b3        kapolos/ssh:latest                        "/usr/sbin/sshd -D"      2 weeks ago         Exited (0) 4 days ago                                          r-SunRay_app-main_app-ssh_1
fd2efd174cc2        kapolos/datavol1:latest                   "/bin/true"              2 weeks ago         Exited (0) 2 weeks ago                                         r-SunRay_app-main_app-data_1
de4ea3b516cf        nginx:latest                              "nginx -g 'daemon off"   4 weeks ago         Exited (0) 4 days ago                                          r-nginx_nginx-test_1
````

Command:

````
[root@localhost ~]# rm -rf /var/lib/rancher/state; docker rm -fv rancher-agent; docker rm -fv rancher-agent-state
Error response from daemon: No such container: rancher-agent
Error response from daemon: No such container: rancher-agent-state
````

Adding host:

````
docker run -e CATTLE_AGENT_IP="198.X.X.X"  -d --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.0.2 http://198.X.X.X:8080/v1/scripts/EE0260A19971AAAAAAFF:1469548800000:Cgf1XFDz0FbxhfMnDuaaaaaaaa
````

After:

````
[root@localhost ~]# docker ps -a
CONTAINER ID        IMAGE                                     COMMAND                  CREATED             STATUS                      PORTS                              NAMES
289d571a7692        rancher/agent:v1.0.2                      "/run.sh http://198.2"   35 seconds ago      Up 34 seconds                                                  determined_wozniak
9e25ae589d56        rancher/agent:v1.0.2                      "/run.sh http://198.2"   28 minutes ago      Exited (1) 13 minutes ago                                      reverent_hypatia
537f7aeab64e        rancher/agent:v1.0.2                      "/run.sh http://198.2"   3 days ago          Exited (1) 3 days ago                                          goofy_bhaskara
2b510bdfbfc5        rancher/server:latest                     "/usr/bin/s6-svscan /"   3 days ago          Up 3 days                   3306/tcp, 0.0.0.0:8080->8080/tcp   pedantic_kirch
5ad1b13c5e02        2ac1c28a8235                              "/usr/bin/s6-svscan /"   3 days ago          Created                                                        rancher-data
2b0bf46871f9        kapolos/embercli:2.7.0-beta5_node-6.2.2   "bash"                   7 days ago          Exited (0) 4 days ago                                          073999bd-6cd3-4236-90db-a0a85d7e092c
2633bf08c9b3        kapolos/ssh:latest                        "/usr/sbin/sshd -D"      2 weeks ago         Exited (0) 4 days ago                                          r-SunRay_app-main_app-ssh_1
fd2efd174cc2        kapolos/datavol1:latest                   "/bin/true"              2 weeks ago         Exited (0) 2 weeks ago                                         r-SunRay_app-main_app-data_1
de4ea3b516cf        nginx:latest                              "nginx -g 'daemon off"   4 weeks ago         Exited (0) 4 days ago                                          r-nginx_nginx-test_1
````
````

**Comment by kapolos** [comment]
**Update**:

I thought to clean up the database from any mention of the misbeheaving host:

````
mysql> select id,name,state from host;
+----+-----------+--------+
| id | name      | state  |
+----+-----------+--------+
|  1 | Rancher 1 | purged |
|  2 | Rancher 2 | purged |
|  3 | Rancher 4 | active |
|  4 | Rancher 3 | active |
|  5 | Rancher 2 | active |
+----+-----------+--------+
5 rows in set (0.00 sec)
````

````
mysql> delete from container_event where host_id=1;
mysql> delete from healthcheck_instance_host_map where host_id=1;
mysql> delete from host_ip_address_map where host_id=1;
mysql> delete from host_label_map where host_id=1;
mysql> delete from host_vnet_map where host_id=1;
mysql> delete from instance_host_map where host_id=1;
mysql> delete from storage_pool_host_map where host_id=1;
````

````
mysql> delete from host where id=1;                     
Query OK, 1 row affected (0.00 sec)

mysql> select id,name,state from host; 
+----+-----------+--------+
| id | name      | state  |
+----+-----------+--------+
|  2 | Rancher 2 | purged |
|  3 | Rancher 4 | active |
|  4 | Rancher 3 | active |
|  5 | Rancher 2 | active |
+----+-----------+--------+
4 rows in set (0.00 sec)
````

Then tried to add the host via the usual procedure. Same result. So that wasn' it..

-------

Then I checked the logs from the agent and I see something weird:

Multiple occurences of this entry:
````
ERROR: http://198.x.x.x:8080/v1 is not accessible
````

Doing 
````
#curl http://198.x.x.x:8080/v1

{"id":"--redacted--","type":"error","links":{},"actions":{},"status":401,"code":"Unauthorized","message":"Unauthorized","detail":null}
````

Which means that the endpoint is accessible (but of course my request was unauthorized without a token). So there is no network issue.

Manually calling the url the UI provides:
````
#curl http://198.x.x.x:8080/v1/scripts/--redacted--

#!/bin/sh

export CATTLE_REGISTRATION_ACCESS_KEY="registrationToken"
export CATTLE_REGISTRATION_SECRET_KEY="--redacted--"
export CATTLE_URL="http://198.x.x.x:8080/v1"
export DETECTED_CATTLE_AGENT_IP="198.204.247.91"
````

Could it be that the secret key is not valid somehow? 

I'm out of ideas at this point, any insight would be fantastic :)
