### ISSUE TITLE
Rancher Kubernetes cluster doesn't detect the node failure

### ISSUE THREAD

**Issue by rooty123** [rancher/rancher#5515]
When I shutdown host, in UI it becomes in state Reconnecting, but kubectl shows
NAME          STATUS    AGE
rancherkub1   Ready     1d
rancherkub2   Ready     1d

when rancherkub2 is down. As a result kubernetes doesn't reschedule containers that were running on this host.
---

| Useful | Info |
| :-- | :-- |
| Versions | Rancher `v1.1.1` Cattle: `v0.165.7` UI: `v1.1.12` |
| Access | `localauth` `admin` |
| Orchestration | `Kubernetes` |
| Route | `hosts.index` |

**Comment by deniseschannon** [comment]
I'm unable to reproduce on v1.1.2. 

```
> kubectl get nodes
NAME                 STATUS     AGE
denise-k8stesting1   NotReady   10h
denise-k8stesting2   Ready      10h
denise-k8stesting3   Ready      10h
```

Can you go to the System stack in Kubernetes and share what image tag the `kubernetes` service is running? This would help me know what template you are running on kubernetes.

**Comment by rooty123** [comment]
I also was able to reproduce on 2.0-pre1. Here is screenshot:
![screenshot from 2016-08-03 09 21 54](https://cloud.githubusercontent.com/assets/371690/17355805/eee471a0-595b-11e6-953e-e973bd657239.png)

Perhaps you need to test with 2 nodes (not 3)

**Comment by deniseschannon** [comment]
@rooty123 How did you get Kubernetes to be running v1.3? This version of Kubernetes is not supported in Rancher v1.1.x series. 

I can tell it's running v1.3 with the image being `rancher/k8s:v1.3.0-rancher3`

**Comment by rooty123** [comment]
@deniseschannon I just use latest 1.2.0-pre release, which supports upgrade to 1.3

**Comment by aemneina** [comment]
hey @rooty123 can you check with a more modern version of rancher server? If you hit it again, please do reopen or file a new issue.
