### ISSUE TITLE
Question: Start before Stopping

### ISSUE THREAD

**Issue by drdocker** [rancher/rancher#5519]
Rancher 1.1.1

Hello,

In Rancher 1.1.1, I noticed that there's an option when doing a manual upgrade to "Start before Stopping". This appears to allow my new container to start before stopping the old container. Is it possible for me to set this behavior via the Rancher API?  I didn't see an obvious `json property` in the service API block that indicated how to do this. 

Thanks in advance

**Comment by bacheson** [comment]
I use rancher-compose for CI deployment. You can use the following in your rancher-compose.yml file:

service_name:
    upgrade_strategy:
        start_first: true

**Comment by deniseschannon** [comment]
If you look at `<serverIP:8080>/v1/schemas/inserviceupgradestrategy`, you will be able to see `startFirst`.
