### ISSUE TITLE
External link disappears when linked stack is re-created

### ISSUE THREAD

**Issue by andyshinn** [rancher/rancher#5520]
**Rancher Version:** 1.1.0

**Docker Version:** 1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):** Local vSphere VMs

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** Single node Rancher internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:**

1. Create two stacks (stack A and stack B) with 1 service each.
1. Externally link service in stack A to service in stack B.
1. Re-create stack B using the generating docker-compose.yml and rancher-compose.yml (remove the stack and re-create it).

**Results:** The external link is now broken and never recovers.

**Expected:** The external link should recover to the same named stack and service, regardless if it is removed and re-created.

This bit us in production. I guess it makes sense but we were not prepared for it. We had a problem upgrading one stack and we ended up just having to delete it and deploy again. Another service with an external link to this one never recovered (the docker-compose.yml actually no longer even showed the `external_links` section in YAML).

Is it possible to make external links recover when the linked stack is re-created?

**Comment by deniseschannon** [comment]
This is correct, the link between the services would no longer exist because you've deleted an service and created a brand new service.

If you wanted the services to always be linked, you should look into selectors.

http://docs.rancher.com/rancher/latest/en/cattle/labels/#selector-labels

Selectors are not in the UI yet [#2270] and can either be done using labels in the UI or labels in rancher-compose.

**Comment by andyshinn** [comment]
OK, so if I understand correctly, I would want to do something like:

```
service1:
  labels:
    io.rancher.service.selector.link: io.rancher.stack.name = dsl, io.rancher.stack_service.name = app
```

Instead of:

```
service1:
  external_link: dsl/app
```

?

**Comment by deniseschannon** [comment]
I believe io.rancher.stack_service.name would need to be `dsl/app` as that label is `<stack_name>/<service_name>`

You'd only need 

```
service1:
  labels:
    io.rancher.service.selector.link: io.rancher.stack_service.name = dsl/app
```

And then anytime any service `app` in the `dsl` stack would automatically be DNS linked to service1.

**Comment by tcrossland** [comment]
This is good to know. Is there any way the linked service can be aliased while using selector labels? For example, with `external_links` you can do the following:

```
service1:
  external_link: stack2/service2:alias
```

**Comment by deniseschannon** [comment]
No, there is no way to make an alias for the link through selector labels. Since the selector label can pick up container or services of varying counts, determining when and what the alias to be would be a challenge.

**Comment by IGZalejandropenedo** [comment]
How would we use the selector label inside the container to resolve the link? Whats the DNS domain associated?

I've tried several ways of specifying the label but I don't seem to be able to resolve the linked containers:
`
# using rancher-defined labels
io.rancher.service.selector.link: io.rancher.stack_service.name = service_name
io.rancher.service.selector.link: io.rancher.stack_service.name = stack/service_name

# self-defined labels
io.rancher.service.selector.link: service = service_name
`

If I try to resolve the link as `service_name` I get an unreachable host error. If I try to resolve it as `service_name.stack` it's the rancher internal DNS answering.

Any insight will be welcomed.

**Comment by deniseschannon** [comment]
@icedfiend Are you trying to resolve services that are outside the stack? If so, you would need to use `service_name.stack`. 

http://docs.rancher.com/rancher/v1.2/en/cattle/internal-dns-service/

**Comment by icedfiend** [comment]
@deniseschannon Yes, but I understood that was rancher.internal DNS answering (according to resolve.conf in the container).

Even without the selector labels I can use rancher.internal DNS to resolve other services using `service_name.stack`, and that's the strategy we've adopted for now instead of using links.

Thanks

**Comment by aleksf** [comment]
@deniseschannon 
Given that selectors do auto-linking, is there a reason we can't use docker hosts resolution rather than rancher dns? Can you please clarify if selector linking has anything to do with docker links, or is rather limited to rancher dns only?

**Comment by deniseschannon** [comment]
@aleksf Selector linking has nothing to do with docker links. It's how Rancher's DNS resolves to containers that aren't explicitly linked.
