### ISSUE TITLE
Improve volume functionality

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#5522]
### General

I want to define volumes and their options when I define a stack. This means I should be able to define volumes in the UI when creating a stack and in rancher compose.

I expect to be able to manage "local" volumes in the UI. These are volumes created by the default volume driver.

I want to define what scope a volume should have. The scope should control how volumes are created in relation to the creation and deletion of stacks and the scaling of services within the stack.

For all of the below scenarios, I expect that changing the name of a service or stack to not impact the volumes being used.
### Scope volume to deployment unit

I want to be able to create a stack with a volume that scales with a deployment unit.

If two deployment units for the same service are on the same host, I expect them to use different volumes.

If I scale up, I expect a new volume to be created for the newly create deployment unit.

If I upgrade a service in the DU, I expect the upgraded service to use the same volume.

If I scale down an entire deployment unit, I expect the per-DU volumes that were created for it to be automatically removed.
### Scope volume to stack

I want to be able to create a stack where a volume is scoped to the stack. Meaning I can name a volume "data" in stacks A and B and they will not collide.

When I delete a stack, I expect stack-scoped volumes to be automatically deleted.
### Scope volume to environment

I want to be able to create a stack with a volume that is used throughout the entire environment. Meaning I can define the volume in stack A and then use it in both stack A and stack B.

If I delete the stacks or services using an environment-scoped volume, I expect the volume to _not_ be deleted.
### Scope volume to "Classic Mode"

I want to be able to scale volumes in the same way that rancher 1.1 supports. This means I expect that:

Volumes are not scoped to stack or deployment unit by default.

If the driver is local, a volume with a matching name should be used if it already exists on the host where the unit is deployed or created if it does not exist.

If the driver is global (like convoy-nfs), the same volume should be used everywhere.

If I delete the stack or scale down a service, no volumes should be deleted.

**Comment by cjellick** [comment]
Another consideration: volume drivers that are not managed by rancher.

rancher/rancher/5219

**Comment by cjellick** [comment]
We also need to really think through all the snaphsot and backup use cases. Right now, the API is supporting the Longhorn use case of snapshots and backups based off of those snapshots, but what if a storage provider supports backups but not snapshots?

Does convoy-nfs fall into this category or does it technically support snapshots by way of full copies of the fs?

**Comment by deniseschannon** [comment]
The new volume functionality is part of v1.2.0. Assigning to QA to test. But any new bug should be opened separately.

**Comment by sangeethah** [comment]
Following are the test cases that were validated for v1.2 release:

Create volumes with Environment scope (external: True) when volume name exists in “requested” mode
Create volumes with Environment scope (external: True) when volume name exists in “active” mode
Create volumes with Environment scope (external: True) when volume name does not exist
Delete all services that use external volume
Create volumes with Stack scope (external: False) when stackname_volumename does not exist
Create volumes with Stack scope (external: False) when stackname_volumename exists
Delete stack that has volumes associated with it.
Create volumes with Container scope (per_container: True)
Delete container (that has container scope volume) by scaling down service.
Delete container (that has container scope volume) by making it unhealthy.
Delete container (that has container scope volume) manually.

**Comment by deniseschannon** [comment]
Any new issues related to volumes should be opened separately.
