### ISSUE TITLE
New EC2 hosts not getting correct agent IP (since 1.1.0)

### ISSUE THREAD

**Issue by rossigee** [rancher/rancher#5525]
Since upgrading rancher-server to v1.1.0, on firing up new EC2 hosts (using the 0.5.0 image), they appear in the Rancher UI with their 10.42.x.x internal IP addresses. Prior to the upgrade, they would appear using their public IP addresses, and everything would work as expected.

As a workaround, I am firing up the RancherOS instances using my own SSH key, supplying the given public IP in the Rancher UI 'Add Host' dialog, and running up the agent using the command supplied.
---

| Useful | Info |
| :-- | :-- |
| Versions | Rancher `v1.1.0` Cattle: `v0.165.4` UI: `v1.1.12` |
| Access | `openldap` `admin` |
| Orchestration | `Cattle` |
| Route | `settings.projects.detail` |

**Comment by deniseschannon** [comment]
I am unable to reproduce what you're seeing with v1.2.0-pre2. When I launch a RancherOS AMI using the UI, the IP is the external one. 

I'm a bit confused at how you are getting 10.42.x.x IPs as that is part of the Rancher overlay network and shouldn't be related to host IPs.

**Comment by aemneina** [comment]
hey @rossigee does this happen with a more modern version of rancher (1.1.4+)? If so please reopen or file a new issue.
