### ISSUE TITLE
Suggestion: Action log page

### ISSUE THREAD

**Issue by sorenroug** [rancher/rancher#5527]
**Rancher Version:** 1.1.0

We have health checks on a couple of containers, which we suspect that the health checker is recreating daily. We also have several users in the same environment who don't necessarily inform each other. To have a handle on what is happening it would be useful to have a page in the Rancher UI that can be seen by the member role and which lists in reverse chronological order the actions that have been taken on the containers in the environment. The actions would be stop, start, recreate and upgrade. The actors would be the users and the health check system.

I suggest to replace the 'API' link at the top with an 'Operations' menu, and put this action log and the API keys on the menu.

**Comment by deniseschannon** [comment]
Are you looking for something like the audit log page?

http://docs.rancher.com/rancher/latest/en/rancher-services/audit-log/

**Comment by sorenroug** [comment]
I don't know. I'm not one of the people who have admin rights and your page doesn't have a screen shot. From the text on that page it looks like I need a subset. I'm not particularly interested in knowing if an action was done through the API or the UI. More like, did a colleague upgrade a container, did the system recreate one?

**Comment by deniseschannon** [comment]
The information in Audit Logs is exactly what you are looking for. It shows who did what API calls. 

Currently, this is only provided to Admins.
