### ISSUE TITLE
多容器相互link， 发起主机的hosts文件并没有增加记录

### ISSUE THREAD

**Issue by OliverVin** [rancher/rancher#5535]
关于使用rancher 相互link多容器， 在 /etc/hosts 下没有生存对应的解析记录 ，这是为什么

**Comment by yunspace** [comment]
I don't think rancher uses `/etc/hosts` for it's linking. It's got it's own DNS service + Overlay Network which works out the list of IP addresses of healthy containers.

See http://docs.rancher.com/rancher/latest/en/rancher-services/dns-service/

**Comment by deniseschannon** [comment]
@OliverVin Let me know if you have further questions, but @yunspace has answered correctly.
