### ISSUE TITLE
Pods are recreated after  Kubernetes stack upgrade

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#5541]
**Rancher Version:**: v1.2.0-pre1-rc4

**Docker Version:**:1.10.3

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**: Kubernetes

**Steps to Reproduce:**
1. Created a Kubernetes environment with v1.2.0-pre1-rc4 using  https://github.com/ibuildthecloud/rancher-catalog
2. Create pods/service/rcs
3. Click on upgrade available option shown on the system stack. Upgrade to v1.3.0-rancher3 is available.

**Results:** 
1. Upgrade is successful, pods/rcs/services are active. But the pods are recreated after an upgrade.

**Comment by soumyalj** [comment]
Looks like a known issue in Kubernetes: https://github.com/kubernetes/kubernetes/issues/23104

**Comment by alena1108** [comment]
Moving the release target as it has to be fixed on k8s side

**Comment by alena1108** [comment]
@soumyalj @sangeethah could you check if it still happening for 1.4-1.5 k8s upgrade?

**Comment by galal-hussein** [comment]
I upgraded kubernetes from 1.4 to 1.5 on Rancher v1.2.3 and i don't see this problem happening.
