### ISSUE TITLE
Installation Failed on Docker 1.11.2-cs3

### ISSUE THREAD

**Issue by jsilberm** [rancher/rancher#5544]
**Rancher Version:**
N/A

**Docker Version:**
 Version:      1.11.2-cs3

**OS and where are the hosts located? (cloud, bare metal, etc):**
Linux PX-SM1 3.19.3-1.el7.elrepo.x86_64 #1 SMP Thu Mar 26 10:57:36 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux

Baremetal, on-prem

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
docker run -d --restart=always -p 8080:8080 rancher/server

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
N/A
**Steps to Reproduce:**
docker run -d --restart=always -p 8080:8080 rancher/server

**Results:** 
docker: failed to register layer: devicemapper: Error running deviceResume dm_task_run failed.

**Expected:**

**Comment by deniseschannon** [comment]
I don't have this specific version of Docker, but haven't had any issues with running rancher on Docker 1.11.2. 

Just to confirm, you have no issues running other services on your host?

**Comment by jsilberm** [comment]
Confirmed, no other issues.

Thanks

**Comment by deniseschannon** [comment]
@jsilberm I am closing this as this seems more like a Docker issue than a Rancher issue.
