### ISSUE TITLE
Rancher compose timeout on ubuntu 

### ISSUE THREAD

**Issue by aneesv** [rancher/rancher#5546]
**Rancher Version:**
v1.1.1
**Docker Version:**
1.11.2
**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
`rancher-compose up`
**Results:** 
`ERRO[0010] Failed to open project dashboard: Get http://url:8080/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers) 
FATA[0010] Failed to read project: Get http://url:8080/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)`

(URL Masked)
**Expected:**
Create stack

It's working fine on OSX with same URL , API access details

**Comment by deniseschannon** [comment]
I understand your URL is mased, but is there a `:` after your URL.

it should only be `http://url:8080/`

**Comment by aneesv** [comment]
@deniseschannon 

I have not given : after URL 

```bash
export RANCHER_URL=http://url/ 
export RANCHER_ACCESS_KEY=key
export SECRET_KEY=secrect
```

**Comment by deniseschannon** [comment]
can you try doing the same command and pass in the options instead of relying on the environment variables?

`rancher-compose --url http://url/ --access-key key --secret-key up`

**Comment by aneesv** [comment]
@deniseschannon already tried , No luck :(

**Comment by deniseschannon** [comment]
what kind of api key are you using? I am trying to figure out what could have caused your issues.

**Comment by aemneina** [comment]
@aneesv are you still hitting this issue? if so feel free to reopen or create a new issue.
