### ISSUE TITLE
Deleting container rancher-agent

### ISSUE THREAD

**Issue by averri** [rancher/rancher#5547]
I have updated Rancher server to 1.1.12, and the rancher agent cannot start, please see the logs bellow.

```
INFO: Attempting to connect to: https://domain/v1
INFO: https://domain/v1 is accessible
INFO: Inspecting host capabilities
INFO: Systemd: true
INFO: Boot2Docker: false
INFO: Host writable: true
INFO: Token: xxxxxxxx
INFO: Running registration
INFO: Printing Environment
INFO: ENV: CATTLE_ACCESS_KEY=zzz
INFO: ENV: CATTLE_AGENT_IP=yyy
INFO: ENV: CATTLE_HOME=/var/lib/cattle
INFO: ENV: CATTLE_REGISTRATION_ACCESS_KEY=registrationToken
INFO: ENV: CATTLE_REGISTRATION_SECRET_KEY=xxxxxxx
INFO: ENV: CATTLE_SECRET_KEY=xxxxxxx
INFO: ENV: CATTLE_SYSTEMD=true
INFO: ENV: CATTLE_URL=https://domain/v1
INFO: ENV: DETECTED_CATTLE_AGENT_IP=yyy
INFO: ENV: RANCHER_AGENT_IMAGE=rancher/agent:v1.0.2
INFO: Deleting container rancher-agent
```

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.1.2` Cattle: `v0.165.8` UI: `v1.1.12` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`hosts.index`|

**Comment by deniseschannon** [comment]
What version did you upgrade from? 

What is the state of your current rancher/agents?

Can you log into the host and just re-run the registration agent command? Does that resolve it?

**Comment by deniseschannon** [comment]
@averri If you could give me more details, please re-open.
