### ISSUE TITLE
Suggestion : Have a "stable" tag for the docker image of the agent agent

### ISSUE THREAD

**Issue by kvaes** [rancher/rancher#5549]
Source : https://hub.docker.com/r/rancher/agent/

At the moment, the only "dynamic" one is the "latest"-tag. it would be great to have a "stable"-tag, just like with the server ( https://hub.docker.com/r/rancher/server/tags/ )

**Comment by deniseschannon** [comment]
Every rancher/agent is tagged specifically to a release version. In our release notes, we always reference which rancher/agent tag is to be used with that release as well as in our command (in the add host->custom page), we always use a specific tagged version of the rancher/agent.

**Comment by kvaes** [comment]
if the stable tag of the agent matches the server one... then people can use this in automated deployments
