### ISSUE TITLE
Stack description not displayed anywhere

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#555]
v0.16.3
Steps:
1.  Create an Stack and add a description

Results:
Description not displayed anywhere

Expected:
Should be displayed somewhere

**Comment by westlywright** [comment]
@tfiduccia @vincent99 do we want to stack description just on the individual stack view page? Or do we want descriptions on the stacks overview page as well?

**Comment by hwinkel** [comment]
At least part of the description? And a more...  Link to the details page?

**Comment by vincent99** [comment]
Seems like there's room for a clipped line in the overview boxes..

**Comment by tfiduccia** [comment]
Version - master 3/15
Verified fixed
