### ISSUE TITLE
Ability to select k8s version when creating a k8s environment

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#5552]
As we add in support for multiple k8s versions, we should allow users to select which version of k8s they want to deploy in Rancher.

Currently, we will default to k8s v1.2 and users can upgrade their k8s system stack to upgrade to k8s v1.3.

**Comment by sangeethah** [comment]
Tested with rancher-server version - v1.2.0-pre4-rc2

When user choose to deploy "kubernetes" from "Infrastructure" catalog , he is presented with list of available K8s templates that he can choose from.
