### ISSUE TITLE
Respect a) serviceIndex b) hostId when mark instance for rollback

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#5561]
On service upgrade, we do:

1) mark instance v0 for upgrade and stop it
2) wait till its v1 version is recreated by calling service.reconcile

On service rollback, we:

1) destroy one of the v1 instances
2) unmark v0 instance
3) call reconcile that would start v0 instance

and so on.

When we destroy new/unmark old instance for the rollback to pick it up, we do care to pick up a particular instance only in case when:

the upgrade is partial - when not all launch configs get upgraded. Then we pick a deployment unit to rollback based on deployment unit uuid
But for cases like global service (and perhaps anti affinity constraint use case) it is also important that instance that is being destroyed, has the same hostId as the instance we rollback to. So the constraint never breaks. Otherwise all kinds of collision can possible happen.

We should also respect serviceIndex in the same context

**Comment by alena1108** [comment]
With the latest master, we:

* save deployment unit information even for services having 0 sidekicks
* serviceindex is bound to the deployment unit

Marking the issue as resolved

**Comment by alena1108** [comment]
@sangeethah to verify the test, you can do this:

1) Start service with scale=4
2) upgrade the service with batchSize=1
3) Once upgraded, rollback. Make sure that:

* the upgraded instance that is being stopped, has the same service index as the old one (the one you are rolling back to)

**Comment by sangeethah** [comment]
Tested with v1.2.0-pre4-rc3.

1) Start service with scale=4
2) upgrade the service with batchSize=1
3) Once upgraded, rollback. Make sure that:

the upgraded instance that is being stopped, has the same service index as the old one (the one you are rolling back to)
