### ISSUE TITLE
LoadBalancer stuck in "initializing"

### ISSUE THREAD

**Issue by EugenMayer** [rancher/rancher#5563]
**Rancher Version:**
1.1.2
**Docker Version:**
 1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
rancheros, kvm

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
no how, single node rancher server, single host, internal DB, 

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
cattle

**Steps to Reproduce:**
Creating a load-balancer with port 443, ssl, add a certificate, add one destination in advanced mode

**Results:** 
Load balancer will stuck initialize
```

7/27/2016 2:47:08 AMINFO: Sending haproxy applied 3-d2f842d7d67d6531622dd524b6403ee66414b3b1264684299f4d5574ecaeb32a
7/27/2016 2:47:08 AMINFO: HOME -> ./
7/27/2016 2:47:08 AMINFO: HOME -> ./etc/
7/27/2016 2:47:08 AMINFO: HOME -> ./etc/cattle/
7/27/2016 2:47:08 AMINFO: HOME -> ./etc/cattle/startup-env
7/27/2016 2:47:08 AMINFO: ROOT -> ./
7/27/2016 2:47:08 AMINFO: ROOT -> ./etc/
7/27/2016 2:47:08 AMINFO: ROOT -> ./etc/init.d/
7/27/2016 2:47:08 AMINFO: ROOT -> ./etc/init.d/agent-instance-startup
7/27/2016 2:47:08 AMINFO: Sending agent-instance-startup applied 1-27397a5ab99f10ff81793e569df68fbbda1d8722fc47aa4014c98d9a1bc82958
7/27/2016 2:47:08 AMmonit: generated unique Monit id 21a546ad8a38aa962399ccf24172d1a4 and stored to '/var/lib/monit/id'
7/27/2016 2:47:08 AMStarting monit daemon with http interface at [localhost:2812]
```

**Expected:**
Load balancer comes up.
I had this load balancer up and running beforehand, i just remade it due to certificate processes, and the same settings do not work anymore.

A second, TCP only loadbalancer, comes up without issues.

I do neither think this is related to HA: https://github.com/rancher/rancher/issues/4634
nor probably related to https://github.com/rancher/rancher/issues/3462

**Comment by EugenMayer** [comment]
Important thing to reproduce it: You need to add a https (SSL) port, non ssl 80 works without issues. So adding

ip:443 (ssl) -> advanced configuration -> somedomain:443 on somecontainer:someport

does reliable cause this issue

**Comment by EugenMayer** [comment]
I just ensured it is not certificate related. The certificates i added are working in other containers without issues. i also readded the old certificates which have been working and tried that, same outcome. 

What is not related to the issue:
 - advanced or simple mode
 - the port ( change the source port to 10443 and the default port to 10443 instead of 443 )
 - the target container
 - the SSL certificate in general ( with our without a chain certificate )

**Comment by EugenMayer** [comment]
Could it be, that after upgrading rancher to 1.1.2 and this agent 1.0.2 and generally agent-instance-0.8.3 the main instance was not upgraded automatically:

```
rancher/agent-instance:v0.8.1        "/etc/init.d/agent-in"   8 weeks ago         Up 8 hours          0.0.0.0:500->500/udp, 0.0.0.0:4500->4500/udp   a216ab16-fdbd-4ac3-b56d-e4f52813bacd
```

Still is 0.8.1 - can this be related?

**Comment by EugenMayer** [comment]
After fiddling arround, i found the cause. Due to the suggestions here http://docs.rancher.com/rancher/latest/en/faqs/troubleshooting/#cross-host-communication i checked by agent for this host ( host is the same rancher-server runs on ). I double checked that the IP / hostname configured is correct and it was right.

I checked the bash history to see how the server was started and it was exactly like expected. The rancher-agen was like expected upgraded to 1.0.2 automatically wen i upgraded rancher from 1.1.0-dev3 to 1.2.1

Now, eventhough it did not make sense, i stopped the agent, removed it and used the old command to recreate it ( same token ) and only changed the version of the image to 1.0.2 

After that, LB are initializing again. **this is not a fix - it seems that there is an upgrade issue**

The agent was working beforehand, using the exact same configuration, token and volume storage. The host was all healthy in the GUI->infrastructure->hosts.

So eventhough it is solved for me, this issue seems to be either a upgrade issue from 1.1.0 or in general?

**Comment by EugenMayer** [comment]
Finally confirming, this is an upgrade issue to rancher-server 1.1.2 - due to a complete data-loss when running rancheros upgrade ( what the .. ) i tried to today, isolatd, based on the old 1.1.0-beta3. Only upgrading rancher server, which will upgrade the agent and then the agent-instances (of the loadbalaner, the HTTPS based lb does not come up anymore.

Just tell me, if creating issue here is nonsense any. I can safe my time and you do not get flooded with things you do not care anyway about. Win-win, or lose lose, whatever you call it.

**Comment by pwFoo** [comment]
I have also problems with load balancers (custom ssh lb, catalog mariadb galera lb, ...).
It worked one time (don't know the version) and stucks in initializing state on each other (older, newer and current) version.

**Comment by EugenMayer** [comment]
i could finally pin that one down to the certificate. It seems like my class 1, Startssl 5 domain certificate is stopping the haproxy to finish initializing. Is there any way to debug this in haproxy to see what the reason is?

**Comment by deniseschannon** [comment]
@EugenMayer Can you do the following? SSH into the haproxy lb instance and execute `service haproxy restart`. See if there is any error reported.

If there is no error, can you check the health check for the load balancer? On the container that is having the issue, click on View in API. Under links, click on the `healthcheckInstanceHostMaps`. For each item, check the `healthState` and confirm that they all report `healthy`.

**Comment by ibuildthecloud** [comment]
> Just tell me, if creating issue here is nonsense any. I can safe my time and you do not get flooded with things you do not care anyway about. Win-win, or lose lose, whatever you call it.

Please continue to file issues.  We really do care and track all issues.  We might not be immediate to respond.  We will try to improve here.  You have to understand the complexity of supporting a tool like this in an open source capacity.  A tool like this has huge amount of permutations and there are a lot of moving parts.

One thing you can try to see why your haproxy might be having issues is open a shell to the container and run

```
/var/lib/cattle/download.sh --force haproxy
```

NOTE: this approach will stop working once we release 1.2 as the LB is being refactored as we speak.

The other thing you can do is add `log` keyword to the globals section of haproxy. http://cbonte.github.io/haproxy-dconv/configuration-1.6.html#3-log  The odwnside of that is that you have to setup a rsyslog server to accept the syslog.

**Comment by vincent99** [comment]
> ip:443 (ssl) -> advanced or simple configuration -> somedomain:443 on somecontainer:someport

The health check is failing because this is wrong, which has nothing to do with what Rancher version  or agent you're using.

You're telling there balancer to terminate the SSL connection and send the plaintext http request to the target container's port 443.  The target container is probably not listening on 443 at all, but if it is it will be expecting a SSL request and not getting one.  So the health check request does not get a successful response, and the state never leaves initializing.

The target container port should be 80 (probably, depending on the image).  And the UI even explicitly sets it to that for this exact case of 443+ SSL if you haven't set a target port yet.

**Comment by EugenMayer** [comment]
@vincent99 it was just an quick example. Of course the receiving target port is plain text. Please remember, i am not trying to get "some load balancer configuration up and running". I am trying to get something running which have been working under 1.1.0-beta3.

**Comment by EugenMayer** [comment]
@deniseschannon it seems like one of the certificates is the cause: 

```
root@00c324591acc:/# service haproxy restart
 * Restarting haproxy haproxy                                                                                                                                                                                                                           [ALERT] 209/185322 (1709) : parsing [/etc/haproxy/haproxy.cfg:59] : 'bind *:10443' :
  inconsistencies between private key and certificate loaded from PEM file '/etc/haproxy/certs/default.pem'.
  inconsistencies between private key and certificate loaded from PEM file '/etc/haproxy/certs/server1.pem'.
[ALERT] 209/185322 (1709) : Error(s) found in configuration file : /etc/haproxy/haproxy.cfg
[WARNING] 209/185322 (1709) : config : 'option forwardfor' ignored for proxy 'default' as it requires HTTP mode.
[ALERT] 209/185322 (1709) : Proxy '58420f53-3f46-45c4-89cf-0f190c54ac3f_10443_frontend': no SSL certificate specified for bind '*:10443' at [/etc/haproxy/haproxy.cfg:59] (use 'crt').
[ALERT] 209/185322 (1709) : Fatal errors found in configuration.
```

I would say, thats a missmatching private key, right. I will confirm that this is no configuration issue in the certificates

**Comment by EugenMayer** [comment]
@deniseschannon thank you for pointing me into that direction. The issue was in fact, that the private-key did not belong the the certificate..so really blame this one on me.

Its a pitty that the balancer log does not show the output above, it would have saved a lot of time debugging. But i guess that is the payback of my own stupidity making such a mistake.

I created a feature-request to maybe save others from this https://github.com/rancher/rancher/issues/5584 .. but maybe its just me

**Comment by xlight** [comment]
perhaps you can remove the node which stucked and remove the agent-container , then re-add the host

**Comment by polinchw** [comment]
Check your firewall rules.  If you don't allow UDP on allow on ports 500 and 4500 on ALL servers involved (rancher server, and hosts) then you can get this behavior.
