### ISSUE TITLE
kubectl CLI unable to connect to remote server

### ISSUE THREAD

**Issue by Yermouth** [rancher/rancher#5564]
**Rancher version:** 1.1.1

**Docker Version:** 1.11.1

**Rancher cluster:** a list of ubuntu 14.04 instance in GCE

**OS with kubectl installed:** Windows 7 professional

**Steps to Reproduce:**

1. Created a 4-host kubernetes cluster

2. Generate and Copy config from kubectl page to local machine (i.e. placed config under C:\Users\XXXXX\.kube ).

3. run `kubectl` command 

**Results:** `Unable to connect to the server: http: server gave HTTP response to HTTPS client`

and when I change the server address from https:// to http:// , I get 

**Results:** `error: couldn't read version from server: an error on the server has prevented the request from succeeding`

I am currently using http for the rancher server. I have tried v1.3.0 for both windows/amd64 and windows/386 but get the same error.

**Expected:**
I remember that I have successfully use command like `kubectl get pod` with my remote cluster before using HTTP, but when I enable the access control and change the config, `kubectl` cannot function anymore. 

May I know if this problem is related to SSL or other config issues? Is it similar to the issue #3953 ? Thanks.

**Comment by Yermouth** [comment]
Found out that running command `sudo docker run -d --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.0.2` in a host which already has a rancher/agent will result in the above error. I am able to connect to rancher k8s after recreating the whole environment, but the problem cannot be solved by deleting problematic hosts solely.

**Comment by Yermouth** [comment]
I reopened this issue as I find out that by disabling Local Authentication, I can immediately use `kubectl` command again to control k8s.

**Comment by deniseschannon** [comment]
Currently Kubernetes doesn't support Docker 1.11.

If you use 1.10.3 and still have these issues, please re-open.

**Comment by jinmatt** [comment]
@Yermouth is right, kubectl is having issues to work with the generated `~/.kube/config` credentials when Local Authentication is enabled

@deniseschannon please reopen the issue

**Comment by deniseschannon** [comment]
@jinmatt What version of Rancher are you using? I did this with Rancher v1.2.0 in my monthly training session using local authentication and using the generated config. It had no issues.

**Comment by jinmatt** [comment]
@deniseschannon v1.2.1

**Comment by HackerWilson** [comment]
I do also meet this problem, when Local Authentication is disabled, I can reach my it now, thanks for the way to walk around.

**Comment by neethi-shashidhar** [comment]
how should local auhentication be disabled?
