### ISSUE TITLE
Incorrect Disk Size Reporting with RancherOS

### ISSUE THREAD

**Issue by giezi** [rancher/rancher#5566]
**Rancher Version:**
v1.1.2

**Docker Version:**
1.11.2

**OS and where are the hosts located? (cloud, bare metal, etc):**
RancherOS 0.5.0

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node Rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Add a Host with RancherOS

**Results:** 
Host is added, but it displays a incorrect disk size:

<img width="287" alt="screen shot 2016-07-27 at 11 06 39" src="https://cloud.githubusercontent.com/assets/1326203/17169954/45f61402-53ea-11e6-998e-ec11f669ad3a.png">

**Expected:**
The device size is only 93 GB, instead 187GB:

[root@rancher-host01-zrh1 rancher]# df -h
Filesystem                Size      Used Available Use% Mounted on
overlay                  93.6G      1.1G     88.4G   1% /
tmpfs                     4.9G         0      4.9G   0% /dev
tmpfs                     4.9G         0      4.9G   0% /sys/fs/cgroup
/dev/sda1                93.6G      1.1G     88.4G   1% /mnt
/dev/sda1                93.6G      1.1G     88.4G   1% /opt
none                      4.9G    568.0K      4.9G   0% /run
/dev/sda1                93.6G      1.1G     88.4G   1% /media
/dev/sda1                93.6G      1.1G     88.4G   1% /home
/dev/sda1                93.6G      1.1G     88.4G   1% /usr/lib/modules
none                      4.9G    568.0K      4.9G   0% /var/run
/dev/sda1                93.6G      1.1G     88.4G   1% /usr/sbin/halt
/dev/sda1                93.6G      1.1G     88.4G   1% /usr/sbin/iptables
/dev/sda1                93.6G      1.1G     88.4G   1% /usr/sbin/reboot
/dev/sda1                93.6G      1.1G     88.4G   1% /etc/selinux
/dev/sda1                93.6G      1.1G     88.4G   1% /usr/sbin/shutdown
/dev/sda1                93.6G      1.1G     88.4G   1% /usr/sbin/poweroff
/dev/sda1                93.6G      1.1G     88.4G   1% /etc/docker
devtmpfs                  4.9G         0      4.9G   0% /host/dev
shm                      64.0M         0     64.0M   0% /host/dev/shm
/dev/sda1                93.6G      1.1G     88.4G   1% /usr/lib/firmware
/dev/sda1                93.6G      1.1G     88.4G   1% /var/log
/dev/sda1                93.6G      1.1G     88.4G   1% /usr/bin/docker.dist
/dev/sda1                93.6G      1.1G     88.4G   1% /usr/bin/user-docker
/dev/sda1                93.6G      1.1G     88.4G   1% /usr/share/ros
/dev/sda1                93.6G      1.1G     88.4G   1% /usr/bin/dockerlaunch
/dev/sda1                93.6G      1.1G     88.4G   1% /usr/bin/docker-runc.dist
/dev/sda1                93.6G      1.1G     88.4G   1% /usr/sbin/wait-for-docker
/dev/sda1                93.6G      1.1G     88.4G   1% /var/lib/rancher
/dev/sda1                93.6G      1.1G     88.4G   1% /var/lib/docker
/dev/sda1                93.6G      1.1G     88.4G   1% /usr/bin/ros
/dev/sda1                93.6G      1.1G     88.4G   1% /usr/bin/docker-containerd-shim.dist
/dev/sda1                93.6G      1.1G     88.4G   1% /usr/bin/respawn
/dev/sda1                93.6G      1.1G     88.4G   1% /usr/bin/system-docker
/dev/sda1                93.6G      1.1G     88.4G   1% /usr/sbin/netconf
/dev/sda1                93.6G      1.1G     88.4G   1% /usr/bin/cloud-init
/dev/sda1                93.6G      1.1G     88.4G   1% /usr/bin/switch-console
/dev/sda1                93.6G      1.1G     88.4G   1% /usr/bin/docker-containerd.dist
/dev/sda1                93.6G      1.1G     88.4G   1% /var/lib/rancher/cache
/dev/sda1                93.6G      1.1G     88.4G   1% /etc/ssl/certs/ca-certificates.crt.rancher
/dev/sda1                93.6G      1.1G     88.4G   1% /var/lib/rancher/conf
/dev/sda1                93.6G      1.1G     88.4G   1% /etc/resolv.conf
/dev/sda1                93.6G      1.1G     88.4G   1% /etc/hostname
/dev/sda1                93.6G      1.1G     88.4G   1% /etc/hosts
shm                      64.0M         0     64.0M   0% /dev/shm
devtmpfs                  4.9G         0      4.9G   0% /dev
shm                      64.0M         0     64.0M   0% /dev/shm
overlay                  93.6G      1.1G     88.4G   1% /var/lib/docker/overlay/76efacb371c8242f3f6ca94245a43c6e7a9db87f37ded142b9c183bc61d5bd8c/merged
shm                      64.0M         0     64.0M   0% /var/lib/docker/containers/91903307d50d9267ea9cf009f0cf1c583d4d7dfbf578f626f6e44042cd738643/shm

Many thanks for your investigation.

Best regards
Reto

**Comment by kelchm** [comment]
Also seeing this issue on my EC2 hosts.

**Comment by tfiduccia** [comment]
Version - master 8/11
Confirm that disk size is not being reported properly if you use rancherOS.  Added two host.  One using ubuntu and other RancherOS.  Both with root size of 93.  Ubuntu shows correct disk size but RancherOS does not. 
![image](https://cloud.githubusercontent.com/assets/11514927/17600790/f4c77ffe-5fb9-11e6-8e68-d47123a21864.png)

**Comment by nayena** [comment]
This is still an issue, also with newest 0.6.0 AMI of RancherOS

**Comment by will-chan** [comment]
@joshwget can you see if this is a ROS problem or our agent that isn't making the right calls to get the correct storage size.

**Comment by joshwget** [comment]
According to @StrongMonkey cadvisor is currently responsible for disk stats. Once there is a release of the new agent without cadvisor I'll retest to see if it fixes the issue.

**Comment by deniseschannon** [comment]
Re-reading this issue, this is an issue with resizing not working in RancherOS, which is https://github.com/rancher/os/issues/1237. 

Closing in favor of the issues in RancherOS as it is not a Rancher issue.

**Comment by joshwget** [comment]
@deniseschannon I think the original issue here is that disk size is being reported as twice what it should be. When @tfiduccia tested her instance wasn't resized properly, but even if she had manually resized it the disk would be reported incorrectly.

**Comment by deniseschannon** [comment]
Verified in v1.2.0-pre4-rc2. 

As we have moved away from cadvisor, I tested with the new stats and disk size is being reported correctly when it is resized correctly in RancherOS.
