### ISSUE TITLE
cadvisor reporting inaccurate memory usage (and potentially other stats) on host

### ISSUE THREAD

**Issue by schuylr** [rancher/rancher#5567]
**Rancher Version:** 1.1.1

**Docker Version:** 1.11.2

**OS and where are the hosts located? (cloud, bare metal, etc):** RancherOS 4.5.0, AWS EC2

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** Single node, external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:**

Start a large instance (in our case, m4.2xlarge), run lots of different containers on it. The following screenshots is our result (cropped to avoid posting sensitive info).

**Results:** 

This reported 447 MiB:
![screen shot 2016-07-27 at 12 11 48 pm](https://cloud.githubusercontent.com/assets/12628715/17182946/843ea8c4-53f3-11e6-87f6-13f6ff822284.png)

Many of these containers are reporting around or over 1 GiB each:

![screen shot 2016-07-27 at 12 12 50 pm](https://cloud.githubusercontent.com/assets/12628715/17182971/9ee83fd2-53f3-11e6-8c95-5c797927f60b.png)

**Expected:**

Statistics that represent what we would see if we ran `top` on the host machine itself:

![screen shot 2016-07-27 at 12 23 53 pm](https://cloud.githubusercontent.com/assets/12628715/17183414/5231fa82-53f5-11e6-8449-c4aa6316bd2d.png)

That's 24 GiB of actual usage!

**Comment by ccatlett2000** [comment]
Reproduced with the following circumstances:
Host: Both VirtualBox and KVM virtual machine
OS: RancherOS `v0.5.0`
Rancher Versions: Rancher `v1.1.3` Cattle: `v0.165.8.1` UI: `v1.1.12`

In both of my cases the Rancher server host is also the only host.

**Comment by joshwget** [comment]
This is probably similar to #5566 in that it's just a general cadvisor. It's likely this is fixed in v1.2.0-pre4-rc2.

**Comment by schuylr** [comment]
@joshwget I'm on 1.2.0-pre3 now, was the fix done sometime between that and pre4-rc2?

**Comment by deniseschannon** [comment]
@schuylr Yes, we got rid of cadvisor in pre4. Please do not upgrade to v1.2.0-pre4 until the rc tag is removed.

**Comment by schuylr** [comment]
Okay, will verify and close this issue once v1.2.0-pre4 fully comes out.

**Comment by deniseschannon** [comment]
We are no longer using cadvisor as of v1.2.0 instead we're using docker stats for container stats and https://github.com/shirou/gopsutil for host stats.

@schuylr If you still face a stats issue, please open a new issue.

**Comment by schuylr** [comment]
Thanks @deniseschannon :)
