### ISSUE TITLE
In k8s system stack, etcd service is marked as "Started-Once" instead of "Active"

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#5569]
**Rancher Version:**
v1.2.0-pre1

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
1. Launch a Kubernetes environment with 3 hosts
2. The system stack comes up

**Results:** 
The etcd service is marked as `Started-Once` despite having the primary service has running containers 

![screen shot 2016-07-27 at 1 25 01 pm](https://cloud.githubusercontent.com/assets/11410997/17191157/8dc8a138-53fd-11e6-874e-6980eb416934.png)

**Expected:**
The etcd service to be marked as `Active` like other services that have sidekicks with `started-once` data containers (Example is elastic-search and how they all have started-once data containers but the service is active)

![screen shot 2016-07-27 at 1 25 01 pm](https://cloud.githubusercontent.com/assets/11410997/17191159/90faa284-53fd-11e6-8159-08bb4ea22258.png)

**Comment by alena1108** [comment]
@deniseschannon in elastic search, what is the state of the sidekick containers? If it is running, then it the service will be marked as Active. If the state of the service's launch config/startedOnce containers are stopped (they were started once, then stopped), then the state of the service would become StartedOnce

**Comment by deniseschannon** [comment]
In v1.2.0-pre3, I am not seeing this anymore when starting a kubernetes environment.
