### ISSUE TITLE
TCP only based load-balancers are not upgraded

### ISSUE THREAD

**Issue by EugenMayer** [rancher/rancher#5572]
no matter if you restart or change any configuration in there, they the agent-instance will not be upgraded. When you have any http based configuration, it will get upgraded on rancher-server upgrade

**Comment by deniseschannon** [comment]
Similarly to my answer in this issue,  https://github.com/rancher/rancher/issues/5573.

But basically the containers running `rancher/agent-instance` is never automatically upgraded to a new container using the new image.
