### ISSUE TITLE
Host-Network agent is not upgraded on rancher-server upgrade

### ISSUE THREAD

**Issue by EugenMayer** [rancher/rancher#5573]
upgraded from 1.1.0-dev3 to 1.1.2.
 - http lb agent-instance has been upgraded to 0.8.3
 - tcp based lb still are at 0.8.1
 - the host-network agent is also still on 0.8.1

Host-Network-Agent:
```
[rancher@rancher ~]$ docker ps | grep 0.8.1
90dd44cd39c3        rancher/agent-instance:v0.8.1         "/etc/init.d/agent-in"   6 weeks ago         Up 4 minutes                                  r-Infrastructure_MainAuthRouter_1
220f000c1fbf        rancher/agent-instance:v0.8.1         "/etc/init.d/agent-in"   8 weeks ago         Up 20 hours         0.0.0.0:500->500/udp, 0.0.0.0:4500->4500/udp             a216ab16-fdbd-4ac3-b56d-e4f52813bacd
````

HTTP LB:
```
[rancher@rancher ~]$ docker ps | grep 0.8.3
9ed86ef73662        rancher/agent-instance:v0.8.3         "/etc/init.d/agent-in"   12 minutes ago      Up 12 minutes
```

**Comment by EugenMayer** [comment]
running
```
docker kill a216ab16-fdbd-4ac3-b56d-e4f52813bacd
docker rm a216ab16-fdbd-4ac3-b56d-e4f52813bacd
```

the host-network agent is recreated, but still 0.8.1

```
f47b3be71c25        rancher/agent-instance:v0.8.1         "/etc/init.d/agent-in"   About a minute ago   Up About a minute   0.0.0.0:500->500/udp, 0.0.0.0:4500->4500/udp             a216ab16-fdbd-4ac3-b56d-e4f52813bacd
```
Different container id, as you see

**Comment by EugenMayer** [comment]
i think this old bug is related, but it seems not fixed https://github.com/rancher/rancher/issues/3609

**Comment by EugenMayer** [comment]
Probably https://github.com/rancher/rancher/issues/2837 but this docs http://docs.rancher.com/rancher/latest/en/upgrading/#rancher-agents would be wrong

**Comment by EugenMayer** [comment]
Interestingly, when removing the network-agent and purging it using the ui, not the cli, the network-agent was not recreated. After i removed my outdated LB 0.8.1 ( TCP ) and created it once again, both came up as 0.8.3 - maybe the TCP lb forced the network-manager to stay in 0.8.1

**Comment by deniseschannon** [comment]
@EugenMayer There should be no issues when your `rancher/agent-instance` is running different versions. Those are internally upgrade. 

As the docs on the link that you said indicates:

```
For anything using the rancher/agent-instance image, the running container gets upgraded even if the image of the container is not updated to the latest version. For the Network Agent, this occurs when there is a trigger regarding networking (e.g. adding another container, deleting a container). For the Load Balancers, the upgrade occurs by the next load balancer configuration update (e.g. target instance gets restarted, new target service is added, hostname routing rules change, load balacner instance restart, etc).
```

All load balancers/network agents use the `rancher/agent-instance` image, so they could be running different images, but inside will have the same updates as long as something has triggered the update (per the docs). 

If you don't believe that the container is not getting updated correctly (Even though it has the old version), you can delete the existing container and a new one should be created with the latest image version that is tagged with the release.

**Comment by EugenMayer** [comment]
@deniseschannon i understand. The reason i was looking into that is, that the network-agent is very crucial to of services getting configured properly, including the load balancer. Since, after upgrading to 1.1.2 (server) things broke ( lb ) and i have seen that the corresponding version of the agent to 1.1.2 is 0.8.3 probably, i was thinking about this getting stuck in a version not fully compatible.

Thanks for clarifying that it is not critical, probably
