### ISSUE TITLE
Cannot connect to the rancher LB

### ISSUE THREAD

**Issue by RotemEmergi** [rancher/rancher#5574]
Hello , 

I configured a LB with the UI and trying to get to it but it's not working .

Best regards

**Comment by kaos** [comment]
Does your LB service come up OK?

I.e. do you see that it gets its port registered on the host, something like:

![image](https://cloud.githubusercontent.com/assets/72965/17213200/a04e04d4-54d3-11e6-9956-7f2ba2229663.png)

**Comment by deniseschannon** [comment]
Can you share your docker-compose.yml and rancher-compose.yml for the stack? You can click on "View Config" from the Stack dropdown menu.

This would provide more insight on how you've set up your load balancer. Also, is your load balancer service in an active state?

**Comment by RotemEmergi** [comment]
We fix it ..no problem.
Thanks alot

בתאריך 28 ביול' 2016 18:41,‏ "Denise" <notifications@github.com> כתב:
