### ISSUE TITLE
Set description from compose file

### ISSUE THREAD

**Issue by kaos** [rancher/rancher#5575]
Perhaps I've just missed it, but it would be nice to be able to set the service description (and maybe the stack description as well) directly from the compose file.

**Comment by cmeury** [comment]
Yes, we set-up our services from compose files and it looks so ugly without the nice grey labels. Have not found a way either.

**Comment by nicholasdille** [comment]
I would love to be able to set the description of stacks and services from the compose file. We are using automated deployments and I'd like to record which build number in our CD tool performed the deployment/upgrade

**Comment by jhoffmann** [comment]
+1, we have a limited space dev environment and it's frustrating not being able to populate the description programmatically when the developer creates a new stack.

On a related note, on the stack edit in the UI there's a 'tags' field, has anyone found a way to populate that via docker/rancher-compose?

**Comment by joergi** [comment]
original starting request is quite old...
are there any plans to change it?

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
