### ISSUE TITLE
Changing Reuse IP for existing containers

### ISSUE THREAD

**Issue by lenzenmi** [rancher/rancher#5576]
When upgrading an existing container in a stack, the option `Networking->Reuse IP address when upgrading or replacing ` has no effect.

I can only set this option when I create a new container.

**Rancher Version:**
v1.1.1
**Docker Version:**
1.11.2
**OS and where are the hosts located? (cloud, bare metal, etc):**
Debian stable, vps
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node, internal DB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
1. Create any new container. Do not check `Networking->Reuse IP address when upgrading or replacing`
2. Upgrade the container. This time check `Networking->Reuse IP address when upgrading or replacing` 

**Results:** 
No change to the UI, nor the stack's rancher-compose.yml file, and a new IP address is assigned when upgrading or replacing the container.

**Expected:**
The option to be checked in the UI, the rancher-compose.yml file to have "retain_ip: true", and the IP address to be reused during subsequent upgrades.

**Comment by deniseschannon** [comment]
Verified in v1.2.0-pre1 when trying to select the "Retain IP" checkbox, it doesn't get saved during upgrade. 

It looks like in the `inServiceUpgradeStrategy` the API doesn't contain any place for `retainIP`.

**Comment by tfiduccia** [comment]
duplicate #5410
