### ISSUE TITLE
Image [rancher/agent-instance:v0.8.3] failed to pull

### ISSUE THREAD

**Issue by hachiko21** [rancher/rancher#5577]
**Rancher Version:**1.1.0

**Docker Version:**1.11.2

**OS and where are the hosts located? (cloud, bare metal, etc):**

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**cattle

**Steps to Reproduce:**

**Results:** 

**Expected:**

```
 ERROR agent [140186854965488] [event.py:112] Error in request : 4e18a5e3-e1e6-4927-b509-ffb56c5ee937
Traceback (most recent call last):
  File "/var/lib/cattle/pyagent/cattle/agent/event.py", line 95, in _worker_main
    resp = agent.execute(req)
  File "/var/lib/cattle/pyagent/cattle/agent/__init__.py", line 15, in execute
    return self._router.route(req)
  File "/var/lib/cattle/pyagent/cattle/plugins/core/event_router.py", line 13, in route
    resp = handler.execute(req)
  File "/var/lib/cattle/pyagent/cattle/agent/handler.py", line 34, in execute
    return method(req=req, **req.data.__dict__)
  File "/var/lib/cattle/pyagent/cattle/storage/__init__.py", line 27, in image_activate
    action=lambda: self._do_image_activate(image, storage_pool,
  File "/var/lib/cattle/pyagent/cattle/agent/handler.py", line 72, in _do
    action()
  File "/var/lib/cattle/pyagent/cattle/storage/__init__.py", line 28, in <lambda>
    progress)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/storage.py", line 162, in _do_image_activate
    raise e
ImageValidationError: Image [rancher/agent-instance:v0.8.3] failed to pull: Network timed out while trying to connect to https://index.docker.io/v1/repositories/rancher/agent-instance/images. You may want to check your internet connection or if you are behind a proxy.
```

**Comment by deniseschannon** [comment]
This is a time out issue and related to your host not being able to pull the image. Are you able to pull the image when ssh-ing into the box of the host from the command line? Rancher is just doing a `docker run` command with that image.

**Comment by hachiko21** [comment]
i am using image that already present on the host. Rancher UI is not adding container or services...
It shows all the time in Activating .... mode.

**Comment by deniseschannon** [comment]
Can you do a docker images on your host?

Specifically, you need the `rancher/agent-instance:v0.8.3` image as that is what is used for the `Network Agent` container which gets deployed on every host so that cross host communication can occur.

**Comment by hachiko21** [comment]
Whatever i am doing on backend is reflecting on rancher UI  But through rancher UI  i am unable to do like adding container or services... In backend everything is working fine

**Comment by deniseschannon** [comment]
Please show me a `docker images` on your host. Specifically, anything prefixed with `rancher`.

**Comment by hachiko21** [comment]
Right now i can't cauz i am out of the office . After 12-13 hrs later i will show u

**Comment by hachiko21** [comment]
manager.go:146] unable to connect to Rkt api service: rkt: cannot tcp Dial rkt api service: dial tcp 127.0.0.1:15441: getsockopt: connection refused
I0729 08:50:12.330873   11334 fs.go:119] Filesystem partitions: map[/dev/disk/by-label/cloudimg-rootfs:{mountpoint:/var/lib/docker/aufs major:253 minor:1 fsType:ext4 blockSize:0}]
I0729 08:50:12.344982   11334 manager.go:192] Machine: {NumCores:1 CpuFrequency:2666760 MemoryCapacity:2099126272 MachineID:3714c2ec5d6259d0eb356dd7565e0689 SystemUUID:C2B7D42C-C404-4341-970F-988D553B674A BootID:68bd7c3d-3424-4bad-96cb-ed0d02570ba8 Filesystems:[{Device:/dev/disk/by-label/cloudimg-rootfs Capacity:10000928768 Type:vfs Inodes:2566400}] DiskMap:map[253:0:{Name:vda Major:253 Minor:0 Size:10737418240 Scheduler:none}] NetworkDevices:[{Name:br-46f13c9b1bfb MacAddress:02:42:31:e7:8b:14 Speed:0 Mtu:1500} {Name:eth0 MacAddress:fa:16:3e:80:03:50 Speed:0 Mtu:1450}] Topology:[{Id:0 Memory:2099126272 Cores:[{Id:0 Threads:[0] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:4194304 Type:Unified Level:2}]}] Caches:[]}] CloudProvider:Unknown InstanceType:Unknown InstanceID:None}
I0729 08:50:12.345916   11334 manager.go:198] Version: {KernelVersion:3.13.0-71-generic ContainerOsVersion:Ubuntu 14.04.3 LTS DockerVersion:1.11.2 CadvisorVersion:0.23.2 CadvisorRevision:}
I0729 08:50:12.352255   11334 factory.go:217] registering Docker factory
E0729 08:50:12.352280   11334 manager.go:240] Registration of the rkt container factory failed: unable to communicate with Rkt api service: rkt: cannot tcp Dial rkt api service: dial tcp 127.0.0.1:15441: getsockopt: connection refused

**Comment by hachiko21** [comment]
it seems problem with cattle api registration

**Comment by hachiko21** [comment]
Rancher agent log
Registration of the rkt container factory failed: unable to communicate with Rkt api service: rkt: cannot tcp Dial rkt api service: dial tcp 127.0.0.1:15441: getsockopt

**Comment by hachiko21** [comment]
unable to connect to Rkt api service: rkt: cannot tcp Dial rkt api service: dial tcp 127.0.0.1:15441: getsockopt: connection refused

**Comment by hachiko21** [comment]
Network agent :
 Removed (Image [rancher/agent-instance:v0.8.3] failed to pull: Error while pulling image: Get https://index.docker.io/v1/repositories/rancher/agent-instance/images: http: error connecting to proxy http://127.0.0.1:3128/: dial tcp 127.0.0.1:3128: getsockopt: connection refused)

**Comment by hachiko21** [comment]
rancher UI
while running container through UI 



 Removed (Image [rancher/agent-instance:v0.8.3] failed to pull: Error while pulling image: Get https://index.docker.io/v1/repositories/rancher/agent-instance/images: http: error connecting to proxy http://127.0.0.1:3128/: dial tcp 127.0.0.1:3128: getsockopt: connection refused)

**Comment by hachiko21** [comment]
CONTAINER ID        IMAGE                                         COMMAND                  CREATED             STATUS              PORTS                                          NAMES
9aeb480f32d2        CTSC00339320901.cts.com:18444/tomcat:latest   "/bin/sh -c '${CATALI"   13 minutes ago      Up 13 minutes       8080/tcp                                       r-tomcat
c0f549035e40        rancher/agent-instance:v0.8.3                 "/etc/init.d/agent-in"   13 minutes ago      Up 13 minutes       0.0.0.0:500->500/udp, 0.0.0.0:4500->4500/udp   c215d253-60e6-4259-adb4-5dcd4894d681
c8e23fdbf81d        rancher/agent:v1.0.2                          "/run.sh run"            31 minutes ago      Up 16 minutes                                                      rancher-agent

**Comment by hachiko21** [comment]
resolved

**Comment by baillieny** [comment]
How did you resolve this?

**Comment by hachiko21** [comment]
pulled that image manually and tagged it the name it was looking for.
