### ISSUE TITLE
Kubernetes Horizontal Pod Autoscaler (kubectl get hpa) fails to get CPU utilization 

### ISSUE THREAD

**Issue by yunspace** [rancher/rancher#5578]
**Rancher Version:**
1.2.0-pre1
**Docker Version:**
1.11
**OS and where are the hosts located? (cloud, bare metal, etc):**
Azure
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node Rancher with local file volume
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes
**Steps to Reproduce:**

1. Create a brand new Kubernetes environment
2. Update the Kubernetes stack to 1.3 via the Stack upgrade button
3. Follow the steps here: http://blog.kubernetes.io/2016/07/autoscaling-in-kubernetes.html:

```
>kubectl run php-apache --image=gcr.io/google_containers/hpa-example --requests=cpu=500m,memory=500M --expose --port=80
service "php-apache" created 
deployment "php-apache" created

> kubectl get deployment                                                                                                
NAME           DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE                                                         
php-apache     1         1         1            1           23m                                                  

>kubectl autoscale deployment php-apache --cpu-percent=50 --min=1 --max=10  
deployment "php-apache" autoscaled 

> kubectl get hpa                                                                                                       
```

**Results:** 
CPU utilization doesn't appear:
```
NAME         REFERENCE               TARGET    CURRENT     MINPODS   MAXPODS   AGE                                      
php-apache   Deployment/php-apache   50%       <waiting>   1         10        13m     
```

**Expected:**
CPU utilization should appear:
```
NAME         REFERENCE               TARGET    CURRENT     MINPODS   MAXPODS   AGE                                      
php-apache   Deployment/php-apache   50%       0%   1         10        13m     
```

**Comment by bonifaido** [comment]
You have to install Heapster in order to get Pod Autoscaling to work. In order to get Heapster to work with current Rancher Kubernetees (1.3.0-rancher3) I suggest you to deploy my version of Heapster: https://github.com/bonifaido/heapster
```
git clone https://github.com/bonifaido/heapster.git
cd heapster
kubectl apply -f deploy/kube-config/standalone/
```

**Comment by yunspace** [comment]
Thanks for the tip, will try it out

**Comment by bonifaido** [comment]
Instructions updated, sorry I missed out a step.

**Comment by will-chan** [comment]
Closing issue as it seems like question answered.
