### ISSUE TITLE
Rancher can't pull images from "library/docker" when it is short named

### ISSUE THREAD

**Issue by chvanikoff** [rancher/rancher#5581]
**Rancher Version:**
`1.1.1`
**Docker Version:**
`1.11.2`
**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04, both bare metal and cloud
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher, internal DB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
1. click "Add container"
2. fill in only "name" and "image" fields. name: `test`, image: `docker:dind`
3. click "Create"
4. Observe error during image pull
**Results:** 
Rancher is trying to pull `dind:latest` image
**Expected:**
Rancher should pull `docker:dind` image which is `library/docker:dind`

**More info:**
- This is true for all tags in `library/docker`
- This only happens if short name - `docker:dind` - is given, but works fine with long one - `library/docker:dind`
- Everything is fine with other images from `library`, tested with `nginx:stable` and `alpine`

**Comment by vincent99** [comment]
This is because of some vestigial code from when we expected image names to start with `docker:` to identify them as docker vs other image sources... https://github.com/rancher/rancher/issues/2801
