### ISSUE TITLE
Allow catalog "upgrade" to the current templateVersion

### ISSUE THREAD

**Issue by vincent99** [rancher/rancher#5582]
Allow catalog upgrade to "upgrade" to the same version you are currently on, so that you can change answers.

![image](https://cloud.githubusercontent.com/assets/753917/17226124/b9f51380-54bc-11e6-8d40-de819ece606c.png)

![image](https://cloud.githubusercontent.com/assets/753917/17226115/b084011c-54bc-11e6-809c-83809f391168.png)

**Comment by tfiduccia** [comment]
Version - master 8/2
Verified fixed
