### ISSUE TITLE
[Feature] Catalog - Default "random" value or type "random-password"

### ISSUE THREAD

**Issue by EugenMayer** [rancher/rancher#5583]
Most of the frameworks nodays need a salt, from registry, every rails app and many more.
Letting a user enter it is not really useful, so most of the catalogs currently provide a default value.

This ends up being a security issue since a lot of users doe not change it, since they expect it to be generated, since its is a password field ( hidden ) and its pre-populated. This results in a lot of instances with the same salt.

What about adding either a type "random-password" or adding a macro for default like generate_string(15) - 15 being the length?

**Comment by vincent99** [comment]
![image](https://cloud.githubusercontent.com/assets/753917/17227016/2806f65a-54c1-11e6-8c23-6fec49845a00.png)

**Comment by tfiduccia** [comment]
Version - master 10/10
Verified fixed
