### ISSUE TITLE
**Swarm Environment** Any detail document about how rancher deploy swarm/mesos internally?

### ISSUE THREAD

**Issue by kiwiwin** [rancher/rancher#5587]
**Rancher Version:** lastest version

**Docker Version:** lastest version

**OS and where are the hosts located? (cloud, bare metal, etc):** azure

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single node

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Swarm

**Steps to Reproduce:** Follow instructions from deploy swarm environment

**Results:** 

**Expected:**

**Comment by deniseschannon** [comment]
We currently don't have any documentation on this. With the new swarm support in Docker 1.12, we are refactoring the framework of how we handle different container orchestration types, so any documentation will need to be after this refactor is completed.

**Comment by kiwiwin** [comment]
@deniseschannon thank you, : ）
