### ISSUE TITLE
Overview of features supported by different container orchestration frameworks

### ISSUE THREAD

**Issue by dj-hedgehog** [rancher/rancher#5589]
It's currently difficult to choose which orchestration framework to use with Docker.
It would be awesome to have a Wiki page or post on the homepage showing an overview which features are supported using which orchestration framework.

For example I tested Swarm a while back just to notice that upgrading stacks and a bunch of other things do not exist.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
