### ISSUE TITLE
Swarm Agent container stuck on initializing

### ISSUE THREAD

**Issue by vikas027** [rancher/rancher#5590]
**Rancher Version:**
1.1.2

**Docker Version:**
1.12

**OS and where are the hosts located? (cloud, bare metal, etc):**
CentOS 7 (Virtual Machine on VMware Fusion)

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node Rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Swarm

**Steps to Reproduce:**
- Install Docker v1.12 on a CentOS 7 as shown [here](https://forums.docker.com/t/unable-to-install-docker-1-12-on-centos-7-insted-its-installing-version-1-11-2/16096/6)
- Run Rancher Server as below
  `docker run -d --restart=always -p 8080:8080 rancher/server`
- Navigate to http://<IP>:8080 and add a Swarm Environment, then add a host which is also a CentOS 7 machine by pasting he below command (generated automatically) 
  `bash sudo docker run -d --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.0.2 http://192.168.1.1:8080/v1/scripts/9C50B4ED144FC2A96554:1469808000000:IzwMXP3bPU9AYgxxPjbLjWv1Bs`

**Results:** 
Swarm Agent container stuck on initializing
![2016-07-30_03-19-32](https://cloud.githubusercontent.com/assets/6998650/17257226/7b180b1a-5604-11e6-8106-9b89b0a51198.png)

I have checked the logs of the container, it is stuck here 

``` bash
root@box71:~# docker logs 9a2b36a708b0
time="2016-07-29T16:51:01Z" level=info msg="Listening for health checks on 0.0.0.0:10240/healthcheck"
time="2016-07-29T16:51:01Z" level=info msg="Initializing event router" workerCount=50
time="2016-07-29T16:51:01Z" level=info msg="Connection established"
time="2016-07-29T16:51:01Z" level=info msg="Starting websocket pings"
```

**Expected:**
Swarm Agent container should start up properly

**Comment by michi88** [comment]
+1 having the exact same problem

**Comment by ibuildthecloud** [comment]
What is currently released is "Old Swarm," and not the new Docker 1.12 swarm.  Support for 1.12 and new swarm will come in one of the 1.2 pre releases.

**Comment by vikas027** [comment]
Thanks @ibuildthecloud, we are looking forward to that release.

**Comment by bradjones1** [comment]
@ibuildthecloud I am running into this with "old swarm." Engine v. 1.11.1, Rancher v.1.1.2. So this isn't related to Docker 1.12? Any thoughts?

**Comment by bradjones1** [comment]
FWIW, I was able to get this working again by deactivating hosts, then re-activating them. That seemed to get the swarm initialization to successfully pass through all four status indicators.

**Comment by dkhaws77** [comment]
Having this issue as well.  I tried the deactivate/reactivate method by @bradjones1 without any luck.  We are running Swarm 1.11.2 and Rancher 1.1.3.  Is there any anticipated time frame for the resolution?  This issue prevents us from getting to the Catalog as well.

**Comment by aemneina** [comment]
Closing in favor of 1.2 docker swarm feature. If you guys find issues with that please create a new issue.
