### ISSUE TITLE
[Feature Request] Improve confd affinity scripting with metadata service

### ISSUE THREAD

**Issue by blaggacao** [rancher/rancher#5592]
## http://rancher-metadata/latest

`http://rancher-metadata/latest/self/host/containers` returning container objects running on self/host

would greatly help with affinity programming of confd configuration files.

This is a feature request.

At present the only available link is:
- /self/host/uuid
- /stacks/%s/services/%s/containers/*/host_uuid

**Comment by blaggacao** [comment]
I mean to avoid something awkwards like this:
```
{{ $host_container := getv "/self/host/uuid" }}
{{ gets "/stacks/*/services/*/labels/co.devco.nginx" }}
{{ range gets "/stacks/*/services/*/labels/co.devco.nginx" }}{{ $elem := split .Key "/" }}
  {{ range gets (printf "/stacks/%s/services/%s/containers/*/host_uuid" (index $elem 2) (index $elem 4))  }}{{ $elem := split .Key "/" }}
    {{ if eq $host_container .Value }}
      name-of-nginx-containers-on-this-host: {{getv (printf "/stacks/%s/services/%s/containers/%s/name" (index $elem 2) (index $elem 4) (index $elem 6))}}
    {{end}}
  {{end}}
{{end}}
```

**Comment by blaggacao** [comment]
I link: https://github.com/kelseyhightower/confd/issues/469

**Comment by blaggacao** [comment]
@mishak87 I've seen you on this as well in the forum.
https://forums.rancher.com/t/sidekick-how-detect-primary-service-container/1992

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
