### ISSUE TITLE
[Feature Request] Rancher AppName Metadata Selector Label

### ISSUE THREAD

**Issue by blaggacao** [rancher/rancher#5596]
Ok, title's confusing. I'll explain, starting with the end, end explaining why I come to this conclusion.
# Claim

Rancher needs a `io.rancher.metricsinterface` system label. In the UI, this system label should be an optional dropdown on every service, also on sidekicks. We should be able to add custom items to the dropdown on the fly.

Obviously, naming is just tentative, and should be more adequate.
# Reasoning
#5592 is related.

Imagine the following task: You want to build a flexible and well integrated monitoring stack into a Rancher Environment. In future, possibly as a system Catalogue which in turn interacts with the api itself.
- A typical stack has some kind of gatherer.
- Typically, you would deploy the gatherer as part of the monitoring stack in the form of a service with the global flag set to true, so that it can do it's work once on every host and send results home to daddy.
- Therefore, you need a flexible configuration based on host specific environment (this is why #5592 is so useful). Yes, it's probably one of the rare use cases, where you need to script something in the host context as opposed to stack, service, etc. The latter being already very well handled by the metadata service.
- Then you will want to deploy conditional configurations based on labels of container present on that host. Eg. you want to switch on postgres monitoring only on hosts where postgres is running so that the metrics collection itself does not consume on the networking stack or in order to use local sockets. Whatever, this is very sensible to do.
### Using the confd pattern...

Ok I can just invent my own labels such as `co.devco.appname=psql`. Then I invest half a week in building a rancher catalogue item which is deploying nicely and stuff, but then when I decide to share, it's usefulness is limited because other people do not use `co.devco.appname=psql` to mark their psql services (the label trickles down to the container, btw).

Rather than that, the UI could specify a selection of app names which can be selected as a drop down, possibly adding new ones on the fly and pow, `io.rancher.metricsinterface=psql` suddenly is a well behaving standard which any metrics stack can draw on to configure the specific interface in the gatherer's configuration.

The underlying issue is, that metrics deployment rely on reliable and dynamic information about the collectable instances, as it is an external stack seeking to interact with the existing once. And you want your metrics system to catch up automatically as new services are deployed, of course.
### Why not Image Names:

Image names are not a relaible identificator as in:
`psql:9.5`, `psql:latest`, `rancher/psql` all referring possibly to the same metrics interface.
### Why not Service Names:

Stack names may or may not be consistent with the represented metrics interface as in:
`psql-prod` and `psql-metadata`.
### Why not simply labels "as is":

A minimal dynamically morphing metrics stack implementation needs a basic set of well defined, well known identifiers in order to be able to deploy it's magic. A well integrated standard as proposed herein, both, enforces and encourages its proper use: Supercharging Rancher with a comprehensive tightly integrated monitoring stack is just a stone's throw away. It would be that simple: interfaces supported by the respective stack and present in the dropdown list are supported by default.

Customizing a stack or including more interfaces would naturally be done in a standard way and, once we are there, a PR to improve the world is the most likely option.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
