### ISSUE TITLE
[cli] Add ability to use existing SSH key pairs for launching AWS instances 

### ISSUE THREAD

**Issue by upayavira** [rancher/rancher#5597]
**Rancher Version:**
Rancher 1.2
CLI v0.0.1 and Git hash bc5c09f.

**Docker Version:**
1.10.2 locally. 1.12.0 on Rancher host.

**OS and where are the hosts located? (cloud, bare metal, etc):**
Workstation: MacOS
Rancher Server: Ubuntu 15.10 (created with docker-machine)

**Steps to Reproduce:**
Execute the Rancher CLI:

```
rancher  --url http://rancher.example.com/v1 \
--access-key xxxxxxxxxxxxx \
--secret-key XXXXXXXXXXXXXXXXXXXXXXXXX \
host create \
--driver amazonec2 \
--amazonec2-access-key XXXXXXXXXXXXXXXX \
--amazonec2-secret-key XXXXXXXXXXXXXXXXXXXXXXXXXX \
--amazonec2-vpc-id vpc-xxxxxxxx \
--amazonec2-instance-type t2.small \
--amazonec2-security-group management-tools \
--amazonec2-region us-east-1 \
--amazonec2-zone b \
--amazonec2-subnet-id subnet-xxxxxxxxxxx \
--amazonec2-tags name=management-tools \
--amazonec2-ssh-keypath /id_rsa \
--amazonec2-ssh-user ubuntu
```

**Results:** 
For the above scenario, with access/secret keys provided, it will only work if your SSH keys are available in the root (/id_rsa) of your Rancher server container.

(note, there's other issues behind this which I will continue to work through, but the SSH keys for sure is a major issue.)

**Expected:**
I expected the --amazonec2-ssh-keypath param to refer to the location of SSH keys on my workstation.

**Comment by deniseschannon** [comment]
After some thinking, I think the behavior of this is correct. Rancher is just calling a `docker-machine create` command inside the Rancher server container. All the options that you are using are Docker Machine options. 

If you want to re-use an existing SSH key pair, then the ssh key pair would have to be wherever the command is run, which would be inside the Rancher server container.

We'd have to make some kind of new option to be able to support what you are looking for.

**Comment by upayavira** [comment]
I agree that in a certain way, it makes sense. However, it also makes the feature (rancher host create with aws) basically unusable, and in an unintuitive way. It tells you that your keys are not there, when you know they are.

If there was a way to upload keys to Rancher, and the cli then referenced those, that would achieve the desired effect of allowing the user to create aws hosts and keeping docker-machine using local keys.

Alternatively, have rancher host create upload the keys so that rancher has them available.

Or is there a way to create aws hosts with the cli that I am missing?

**Comment by deniseschannon** [comment]
@upayavira You don't need to pass in a key pair. By default, docker-machine will create a new key pair and you can download the key pair in the UI.

http://docs.rancher.com/rancher/v1.2/en/hosts/#accessing-hosts-from-the-cloud-providers

**Comment by iBobik** [comment]
If Rancher allows to use SSH key pasted in the parameter (as a string, not as a path to file) then we can use CLI or UI to pass our own keys.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

**Comment by salla2** [comment]
@deniseschannon does  Rancher 2.0 have the option to use existing key pair, I'm not seeing that option yet. If yes could you point me where I can read docs? Thanks!
