### ISSUE TITLE
Websockets failing after upgrade to 1.1.1 and 1.1.2

### ISSUE THREAD

**Issue by philmes** [rancher/rancher#5598]
**Rancher Version:** 1.1.2

**Docker Version:** 1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):** Amazon EC2

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** HA rancher (external DB)

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

After an upgrade to Rancher 1.1.1, host stats, container stats, container logs and shell execution stopped working.

The console contains lots of logs like this:

```WebSocket connection to 'ws://host/v1/logs/?token=<long token value>' failed: Connection closed before receiving a handshake response```

This doesn't seem to be a general websocket configuration problem because other sockets (eg. ping) seem to work ok.

We use an ELB, but this is set to TCP mode.

**Comment by cjellick** [comment]
Can you share the logs from the websocke-proxy containers?

What version did you upgrade from? 

Is it 100% down and unrecoverable? Does a restart of the websocket-proxy service correct the issue?

**Comment by philmes** [comment]
So, only one host has a websocket-proxy / websocket-proxy-ssl container (presumably the master?) 

The logs for that one are filled with:

```
time="2016-08-01T16:25:28Z" level=error msg="Failed handling TCP forwarding: dial tcp 10.42.68.36:8080: getsockopt: no route to host"
time="2016-08-01T16:25:28Z" level=error msg="Failed handling TCP forwarding: dial tcp 10.42.68.36:8080: getsockopt: no route to host"
time="2016-08-01T16:25:28Z" level=error msg="Failed handling TCP forwarding: dial tcp 10.42.68.36:8080: getsockopt: no route to host"
```

Just that IP address. The strange thing is that there isn't a container anywhere with that IP.

**Comment by philmes** [comment]
I've sort of fixed it. I stopped and deleted the proxy containers on that host and restarted the ha parent container. Now it works.

This his how the proxy containers are now arranged over my three Rancher hosts. Is this correct?

**HOST              CONTAINERS**
rancher-0:          r-management_websocket-proxy-ssl_1
rancher-1:          r-management_websocket-proxy_2           r-management_websocket-proxy-ssl_2
rancher-2:          r-management_websocket-proxy_1

**Comment by philmes** [comment]
Going to close this - all working fine now.
