### ISSUE TITLE
CONVOY-NFS stuck on Initializing

### ISSUE THREAD

**Issue by danipolo** [rancher/rancher#5599]
**Rancher Version:** v1.1.2

**Docker Version:** Docker version 1.11.2, build b9f10c9 (on host), On Server: Docker version 1.9.1, build a34a1d5

**OS Server**: OVH VPS, 1GB, Debian Ubuntu Kernel 3.19.0-22-generic. 

**OS Host:** RancherOS - Dedicated server, 32 Gb. RAM. rancheros-os 4.4.10-rancher 

**Environment Type:** Cattle

**Steps to Reproduce:** With a "Clean install" in the both sides (server and host), I go to catalog and try to add CONVOY NFS. The pool container goes OK but the volume-agent-nfs stuck on "Initializing" and goes up and down. I didn't do absolutly anything to the both sides. I've reinstalled multiple times and same problem. I invest lot of time in install it RancherOS on the dedicated (it's hard to install it on OVH).

**Results:**  It just move the status between Initializing, Stopping and Starting.... Not working.

**Expected:** Just stay running.

**Comment by cjellick** [comment]
Can you share the logs from the volume-agent container that is flapping? If the logs are super long and repetitive, you can just share a portion of them.

**Comment by danipolo** [comment]
Thanks Craig,

This is the output:

```
1/8/2016 20:39:01Waiting for metadata
1/8/2016 20:39:02time="2016-08-01T18:39:02Z" level=info msg="Execing [/usr/bin/nsenter --mount=/proc/30826/ns/mnt -F -- /var/lib/docker/overlay/3fd2e0b8131bc5b6ace122f46e49facfb0fa0d40f45f441be5349955aacf3e1d/merged/var/lib/rancher/convoy-agent/share-mnt --stage2 /var/lib/rancher/convoy/convoy-data-cc5cc4ef-c7c3-43bf-a332-b4cdfbb0cf7f -- /launch volume-agent-nfs-internal 30826]"
1/8/2016 20:39:02Registering convoy socket at /var/run/convoy-convoy-data.sock
1/8/2016 20:39:02Mounting at: /var/lib/rancher/convoy/convoy-data-cc5cc4ef-c7c3-43bf-a332-b4cdfbb0cf7f/mnt
1/8/2016 20:39:02Mounting nfs. Command: mount -t nfs  convoy-data:/srv/convoy /var/lib/rancher/convoy/convoy-data-cc5cc4ef-c7c3-43bf-a332-b4cdfbb0cf7f/mnt
1/8/2016 20:39:02mount.nfs: Failed to resolve server convoy-data: No address associated with hostname
```

**Comment by cjellick** [comment]
It is trying to resolve `convoy-data` and cannot. Is convoy-data an external service you setup in rancher?

If it is, here's the problem: we have to enter the host's network namespace to mount the nfs share. In doing so, we lose rancher-dns. So, if convoy-data is meant to be resolved by rancher-dns, it won't be.

**Comment by danipolo** [comment]
`convoy-data` is the name I've put when I created this. Doesn't matter what I put there, never works for me. I didn't create an external service called `convoy-data`.

Do I need to do anything else than click "Install" on the catalog?

**Comment by cjellick** [comment]
The ip address or hostname you put in the field where you put "convoy-data" needs to resolve to an accessible, pre-existing nfs server.

**Comment by danipolo** [comment]
Thanks Craig,

I created the NFS server and now it still running.

The documentation about this it's little bit outdated. Now I'm in the phase of prepare backups for all and it will be great if you can finish the process from the UI (including the S3 connection and sync).

Congrats for this awesome software :)
