### ISSUE TITLE
Reference automatic link wiring does not work correctly

### ISSUE THREAD

**Issue by hibooboo2** [rancher/rancher#560]
When a link is generated to access other resources based on a foreign key relationship in cattle if there are multiple references to the same table it will fail. 

EX:
accounts has a link for projectMembers and the projectMembers table has two columns account_id and project_id
Both columns are foreign keys to the account table. This will make the collection always 404. A possible fix is to have a link for each resouce/column.

**Comment by will-chan** [comment]
Not sure what the consequence of this is but you should at least look.
