### ISSUE TITLE
Support adding of sidekicks as part of upgrading service

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#5603]
Rancher Version:v1.1.2

Steps to reproduce the problem:
Create a k8s set up with v1.1.1 setup.

Upload new kubernetes templates by adding a catalog-library - https://github.com/LLParse/testing-catalog.

When "Upgrade Available" option is presented to the user , choose to upgrade to "v1.2.4-rancher8".
 Upgrade is stuck in " Upgrading (Existing service etcd does not have a sidekick named etcd-hc)  "  forever.

**Comment by alena1108** [comment]
Closing as this issue no longer relevant - we moved out of using etcd-hc sidekick
