### ISSUE TITLE
"Upgrade Available" option is presented for an older version of the template.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#5604]
Rancher Version:v1.1.2

Steps to reproduce the problem:
Create a k8s set up with v1.1.1 setup.

Upload new kubernetes templates by adding a catalog-library - https://github.com/LLParse/testing-catalog.

When "Upgrade Available" option is presented to the user , user is presented the option to upgrade to "v0.1.0-rancher1" and "v1.2.4-rancher8".

Expected Behavior:
User should not be presented with option to upgrade to "v0.1.0-rancher1" version.

**Comment by vincent99** [comment]
Template 0 (`v0.1.0-rancher1`) now has a minimum_rancher_version, which makes it not show up.  Also back-ported the changes to always send minimumRancherVersion from the UI, and filter out versions with empty URLs.

**Comment by soumyalj** [comment]
W.r.t the latest 1.1.3 release and template version v1.2.4-rancher9, user is presented with the right options for upgrade.
