### ISSUE TITLE
Docker pull progress

### ISSUE THREAD

**Issue by guiguan** [rancher/rancher#5609]
**Rancher Version:**
v1.1.1
**Docker Version:**
1.10.3, build 3cd164c
**OS and where are the hosts located? (cloud, bare metal, etc):**
CoreOS, QingCloud

Hi, I have a rancher managed host in China. When I tried to set up a new rancher service on the host which would pull a large docker image from outside of China, the service status was kind of stuck at "Starting" indefinitely. So my question is: how can I view the pulling progress?

**Comment by deniseschannon** [comment]
There is no way to directly view the pulling progress. 

Did you click on the service name to see if there is any status on the specific containers?

**Comment by aemneina** [comment]
closing issue.
