### ISSUE TITLE
Same service index within the deployment unit

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#5611]
Today instances within the same deployment unit, can have diff service indexes (master can have _1, sidekick can have _2). It was done this way originally because unhealthy instances used to stick around till their healthy replacements were created, and we wanted to avoid the duplicates. As now we cleanup unhealthy instances beforehand, we can stick to choosing the same service_index within the deployment unit.

**Comment by alena1108** [comment]
https://github.com/rancher/cattle/pull/1986

**Comment by sangeethah** [comment]
Tested with latest build from master:
Created a service with sidekick having scale=3.

Tried following scenarios multiple times , where the DU ended up having the same service_index:

1. Scale down service by 1 and then delete one of the containers.

2. Delete few containers in parallel.

3. Scale down and scale up services.
