### ISSUE TITLE
Readme.yml and rancher-compose.yml description field on launch/upgrade not always showing up

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#5614]
**Rancher Version:** master 8/2

**Steps to Reproduce:**
1.  Create a catalog template with two versions.
2.  In version 1 in the readme.md enter
# Test1
### Info:  This is the info for version1
1.  In version 1 in the rancher-compose.yml description enter
   description: description from rancher-compose version1
2.  In version 2 in the readme.md enter
   #Test1
   ###Info:  This is the info for version2
3.  In version 2 in the rancher-compose.yml description enter
   description: description from rancher-compose version2
4.  Push the catalog
5.  Go to the catalog and select that template (notice that the info under the main title is coming from the readme.md and no description info from rancher-compose is showing up.
6.  Launch version 1
7.  Click on upgrade

**Results:** Now the info from the description field from the readme is showing up under the main title.

**Expected:**  I think both the Information from the readme and the description from the rancher-compose should always show up or never show up, no matter which version or upgrade sceanario you choose.

**Comment by loganhz** [comment]
Hi @tfiduccia @vincent99 , the expected behavior should be that find and show the `description` from the `rancher-compose.yml` field via API under the main title ?
