### ISSUE TITLE
rancher-machine docs link is broken in rancher/server Machine driver UI.

### ISSUE THREAD

**Issue by nrvale0** [rancher/rancher#5617]
**Rancher Version:**
v1.2.0-pre1

**Docker Version:**
Docker version 1.11.2, build b9f10c9

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04 LTS on laptop

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Singe node rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
N/A

**Steps to Reproduce:**
Infrastructure/Host/Add Host/...

**Results:** 
The "Learn more about the ports that will be opened." link for rancher-machine docs is broken. 404. Screenshot attached.

![screenshot from 2016-08-02 13-34-41](https://cloud.githubusercontent.com/assets/3616282/17344155/044346bc-58b6-11e6-878d-312fdce790c8.png)

**Expected:**
Link should point to docs.

**Comment by tfiduccia** [comment]
Ok, just checked and this page is just missing in 1.1 version of docs.

**Comment by deniseschannon** [comment]
Fixed the docs link.

Verified that it's working with v1.2.0-pre1
