### ISSUE TITLE
Possibility to import existing kubernetes cluster into rancher

### ISSUE THREAD

**Issue by dawidmalina** [rancher/rancher#5624]
I'm not sure whether this question was asked before but is it possible to import existing kubernetes cluster into rancher?

If yes, how we can do it?

If not, is it possible to setup dedicated ha setup like this:
- 3 dedicated nodes for admin nodes where etcd and kubertentes component will be deployed (only kube-system namespace)
- 3 dedicated nodes (or more) as a workers where new deployments can be only deployed

**Comment by dawidmalina** [comment]
Anyone?

**Comment by will-chan** [comment]
At the moment, it is not possible but we are working to remove Rancher specific components inside our distribution of k8s so that it could be possible in the future.  The reason why it's not something we have done yet is because we do manage kubernetes etcd and other components and have added sidekick components to help with that.

**Comment by Haybu** [comment]
is this still not supported ?

**Comment by InAnimaTe** [comment]
Also interested in this. With other enterprise wrappers around kubernetes like Tectonic, it would be nice to merely give Rancher details about my already existent deployment and gain some visibility/mgmt abilities over the cluster. This would be especially nice for still being able to utilize catalog entries for easy deployment on my k8s.

**Comment by anugnes** [comment]
I'd love to see this happening as well. Could it maybe be easier to add a procedure that, upon being given the details of a Kubernetes/Smarm cluster simply installs the necessary Rancher specific components and starts managing the cluster?

**Comment by LLParse** [comment]
Depends on https://github.com/rancher/rancher/issues/7705

This will be achievable for Kubernetes 1.6 clusters using Etcdv3. Migration process will look similar to this:
1. Create a cattle environment and register existing k8s nodes
2. Run container that creates a backup of the etcdv3 datastore and persists to a Rancher persistent volume
3. Tear down external kubernetes components
5. Launch Kubernetes template, providing the persistent volume name in the `restore from` field.

**Comment by anugnes** [comment]
Thanks for the update, looking forward to trying it!

**Comment by sgeffken** [comment]
Any news on this? Would love to use this with an enterprise wrapper around kubernetes as well.

**Comment by vincent99** [comment]
Importing an existing k8s cluster is part of 2.0, which you can try preview releases of now; and not coming to 1.x.

**Comment by sgeffken** [comment]
Just one last question regarding this: Do you have a documentation on how to perform the inclusion of the kubernetes cluster into Rancher using the 2.0 alpha?

**Comment by vincent99** [comment]
It's the giant right-half of the screen you first land on.

![image](https://user-images.githubusercontent.com/753917/31331716-54abee24-ac98-11e7-8ed7-532bd3391232.png)
