### ISSUE TITLE
Upgrading a primary service via the API gets stuck in a loop

### ISSUE THREAD

**Issue by mandrean** [rancher/rancher#5625]
**Rancher Version:**
v1.1.2
**Docker Version:**
v1.11.2
**OS and where are the hosts located? (cloud, bare metal, etc):**
AWS EC2 instance running RancherOS v0.5.0
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node Rancher, internal DB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
1) Set up an environment in Rancher with a stack that has a primary service with side-kick services (for example App Container + some kind of Server Container that uses volumes from the App)
2) Set up a CI environment running [Drone](https://github.com/drone/drone) with the [Rancher Plugin](http://readme.drone.io/plugins/rancher/) configured to access the Rancher API
3) Run a build that results in a Drone deploy using the Rancher Plugin.
**Results:** 
The primary service (with side-kicks) that is supposed to be upgraded gets stuck in a never-ending loop.
**Expected:**
The primary service should be upgraded without getting stuck in a loop.

Note: When upgrading (either just the primary service or all of them) through the Web GUI, it works smoothly, but from Drone Rancher it gets stuck.

I have a _vague_ memory of everything working on an earlier version of Rancher and that this isn't specific to Drone Rancher, therefore I post the issue here. But maybe I'm wrong.

**Comment by aemneina** [comment]
hey @mandrean did you manage to get to the bottom of this? going to close this, feel free to reopen.
