### ISSUE TITLE
new external-lb docker image

### ISSUE THREAD

**Issue by warroyo** [rancher/rancher#5627]
I noticed that the rancher external-lb service has not been rebuilt since apr. 28 . would it be possible to get a new build of this since there have been many fixes and updates to the go-bigip library that this heavily relies on?

**Comment by deniseschannon** [comment]
we welcome PRs. :)

**Comment by deniseschannon** [comment]
I've just released external-lb and a new image `rancher/external-lb:v0.3.0` was released.
