### ISSUE TITLE
Not able to get "Upgrade Available" option to get to v1.3 kubernetes.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#5628]
Rancher Version:v1.2.0-pre1

Create a kubernetes environment.
We get a kubernetes v1.2 with etcd containers using "rancher/etcd:v2.3.7-6".
User is not presented with "Upgrade Available" option to get to v1.3 kubernetes anymore.

Expected Behavior:
User should get kubernetes v1.2 with etcd containers using "rancher/etcd:v2.3.6-4".
He should be presented with "Upgrade Available" option to get to v1.3 kubernetes.

This has started happening after a new template (7) was pushed to - https://github.com/rancher/rancher-catalog/tree/master/templates/kubernetes

**Comment by vincent99** [comment]
The UI changes the template externalId to the `k8s` one as soon as you load it.  Updating the `kubernetes` template does nothing for Rancher v1.2-pre1+.

We have a new problem coming of needing to have a new revision for both k8s 1.2 and 1.3.  The current catalog definition of "upgrade" is "higher number".  So if you're on template 6 (k8s 1.3) and we push a 7 (updated k8s 1.2) and 8 (updated k8s 1.3) both will be available upgrades, which is not great.

**Comment by sangeethah** [comment]
With latest build from master:
Create a kubernetes environment.
User get kubernetes v1.2 with etcd containers using "rancher/etcd:v2.3.6-4" image.
User is  presented with "Upgrade Available" option to get to v1.3 kubernetes as expected.

**Comment by sangeethah** [comment]
Closing this issue.
@vincent99 , for the issue relating to having to support new template versions of both kubernetes v1.2 and v1.3 is tracked in https://github.com/rancher/rancher/issues/5691
