### ISSUE TITLE
Cattle capacity

### ISSUE THREAD

**Issue by onehao** [rancher/rancher#5632]
**Rancher Version:** latest

**Docker Version:** 

**OS and where are the hosts located? (cloud, bare metal, etc):**

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Type: cattle

do we have a capacity analyse of how may host machines that the cattle could manage without the sharp performance decrease?

**Comment by demarant** [comment]
I asked same question in Rancher Forum
https://forums.rancher.com/t/what-is-the-max-nr-of-hosts-and-containers-rancher-is-able-to-manage/3681

**Comment by aemneina** [comment]
I dont think there are any guidelines at this point, and that will improve v1.2.0 so not necessarily worth doing now. Is it fair to say youre looking for a deployment/environment sizing guideline?
@demarant @onehao

**Comment by aemneina** [comment]
closing for now.
