### ISSUE TITLE
Rancher doesn't clean old volumes

### ISSUE THREAD

**Issue by juliangamble** [rancher/rancher#5633]
Rancher Version: 
1.02
Docker Version:
1.10.3
OS and where are the hosts located? (cloud, bare metal, etc):
Redhat - cloud
Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)
single-node-rancher
Environment Type: (Cattle/Kubernetes/Swarm/Mesos)
Cattle

**Steps to Reproduce:**
1. Rancher compose a new stack. 
2. Stop it
3. Run `docker volume ls` on the docker-engine machine. 

**Results:** 
Lots of unused volumes. 

**Expected:**
Rancher would clean up old volumes and stop the disk from filling up.

**Comment by cjellick** [comment]
We are working on revamping our handling of volumes. See #5522.

It sounds like your use case falls into the "Scope volume to stack" scenario.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
