### ISSUE TITLE
support for multiple services to be added for a backend.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#5636]
Rancher Version: cattle build from lbrefactormetadata from https://github.com/alena1108/cattle.git

Steps to reproduce the problem:
Create Lb service with following host name routing rules:
<img width="961" alt="screen shot 2016-08-04 at 6 40 55 pm" src="https://cloud.githubusercontent.com/assets/4266958/17423853/23234ab4-5a73-11e6-86dd-a29ecd83a588.png">

When trying to reach LB ip using hostname header - "www.abc1.com" and path "/service1.html" , traffic is routed only to instances from service - test950297 and not to instances from service -test591785

Expected Behavior:
LB ip should redirect traffic to instances from both the services.

**Comment by francoishill** [comment]
Perhaps point "www.abc1.com" with path "/service1.html" to another load balancer that points to the two separate services...?

**Comment by alena1108** [comment]
@francoishill that would be ideal. But we should still support the use case when user wants to place 2 services under the same port/rule

**Comment by sangeethah** [comment]
@alena1108 , tested with latest image - alena1108/lb-controller-haproxy - 10ca4310e14f.

LB is able to direct traffic to instances from 2 different services. But I see few of the backends missing in haproxy cinfiguration resulting in some hostname routing rules giving "503 Service Unavailable" error.
<img width="947" alt="screen shot 2016-08-05 at 10 19 00 am" src="https://cloud.githubusercontent.com/assets/4266958/17444672/18d53512-5af6-11e6-9445-1bbf88894677.png">

haproxy configuration is missing configuration for www.abc2.com as well as www.abc4.com.

**Comment by sangeethah** [comment]
Tested with Rancher Version: latest cattle build from lbrefactormetadata from https://github.com/alena1108/cattle.git

Hostname routing rules get applied correctly when there are rules that direct traffic to instances from 2 different services.
