### ISSUE TITLE
Will rancher-metadata have stack status?

### ISSUE THREAD

**Issue by zhang8473** [rancher/rancher#5637]
**Rancher Version:**
1.1.0

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
curl http://rancher-metadata/.../stack/app/status

**Expected:**
display the status of the stack (active/stopped/initializing)

Now the meta-data of a stack has:

environment_name
environment_uuid
name
services/
uuid

Will it have status?

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
