### ISSUE TITLE
infinit.sh integration

### ISSUE THREAD

**Issue by 5an1ty** [rancher/rancher#5638]
Infinit (https://infinit.sh/) looks like a good persistent storage solution for convoy.
Their docker volume plugin should be released within days.

**Comment by eelcocramer** [comment]
Looks like the plugin is available now: https://infinit.sh/documentation/docker/volume-plugin

**Comment by 5an1ty** [comment]
Boom, they're acquired by docker. I knew they were going to prove useful! Keep an eye on developments, I think this would be a great addition to rancher!

**Comment by omercnet** [comment]
:+1:

**Comment by easyrasta** [comment]
+1

**Comment by mathieu-gilloots** [comment]
:+1:

**Comment by vberetti** [comment]
Volume name validation in Rancher UI prevents using infinit volumes format : \<user\>/\<volume name\>
I've created an issue https://github.com/rancher/rancher/issues/8646 and corresponding pull requests.

**Comment by subhransusekhar** [comment]
+1

**Comment by mikaelmeulle** [comment]
+1

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
