### ISSUE TITLE
UI issues with new container details page

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#5643]
**Rancher Version:** master 8/4

**Steps to Reproduce:**

- [x] Can we make font type and size match inside each tab and also across the tabs?
![image](https://cloud.githubusercontent.com/assets/11514927/17422613/839affb4-5a68-11e6-8185-6b59ce0cf8b4.png)
![image](https://cloud.githubusercontent.com/assets/11514927/17422628/a5508ca0-5a68-11e6-81ef-44f7edc4510f.png)

- [x] Health Check - Health Check: and Port: should be separated by a line
![image](https://cloud.githubusercontent.com/assets/11514927/17422454/03c3dcb2-5a67-11e6-85df-97b602933def.png)

- [x] All pages  - Can the "None" field result be light grey and all lowercase "none".  So it matches the n/a type of field result.
![image](https://cloud.githubusercontent.com/assets/11514927/17422505/950e3e6a-5a67-11e6-8247-3f3790bca903.png)

- [ ] Command - the User: results is grey?
![image](https://cloud.githubusercontent.com/assets/11514927/17422650/c88602ae-5a68-11e6-910e-e486e0532ab7.png)

- [x] Scheduling - Change text to simply say "No scheduling rules" 
![image](https://cloud.githubusercontent.com/assets/11514927/17446646/0a44ecdc-5aff-11e6-8d29-f29c2a8afbc6.png)

- [x] Scheduling - change format of how rules are displayed so it looks nicer
![image](https://cloud.githubusercontent.com/assets/11514927/17446692/45e8009e-5aff-11e6-90dd-6e74ea5d7b4a.png)

**Comment by lvuch** [comment]
https://github.com/rancher/ui/pull/809

**Comment by tfiduccia** [comment]
Version - master 8/9
Verified fixed
