### ISSUE TITLE
Checkbox text is bold

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#5645]
**Rancher Version:** master 8/5

**Steps to Reproduce:**
1.  Go to Add Service
2.  Go to Networking tab

**Results:**  the text after checkboxes is bold now.  You can see the Always pull image, and the Retain IP.  This is just two instances, there are others.
![image](https://cloud.githubusercontent.com/assets/11514927/17450375/a7bce14e-5b14-11e6-892f-b3614e265e9b.png) 

**Expected:**  Should not be bold

**Comment by lvuch** [comment]
https://github.com/rancher/ui/pull/809

**Comment by tfiduccia** [comment]
Hey lauren, the networking one is fixed but the DNS, Always pull image before creating and volumes from are still not fixed.  Sorry I though they were a single class that would be fixed if you fixed one of them.  Below are images from other places that need to be fixed.

- [ ] Main Add page - Always pull image
![image](https://cloud.githubusercontent.com/assets/11514927/17535403/1b9c1446-5e43-11e6-8f18-c0722ff35b7b.png)

- [ ] Volumes tab - Volumes from
![image](https://cloud.githubusercontent.com/assets/11514927/17535426/3000ea24-5e43-11e6-8746-67fa45ee3846.png)

- [ ] Networking tab - DNS, the text is bold and on line below checkbox
![image](https://cloud.githubusercontent.com/assets/11514927/17535445/5da899e0-5e43-11e6-9f3c-ebfbdb290baf.png)

**Comment by tfiduccia** [comment]
Version - master 8/25
Verified fixed
