### ISSUE TITLE
"rancher restart/stop/start" commands is picking up 2 services for single service when passing in --type

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#5648]
**Rancher Version:**: Master

**Docker Version:**:1.12.0

**Rancher CLI version:** v0.0.1

**OS and where are the hosts located? (cloud, bare metal, etc):**: Ubuntu, Cloud

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**:Cattle

**Steps to Reproduce:**
1. Set up a rancher-cli client
2. Create a service called newservice in your rancher setup with multiple containers. Ensure there is only one service with the name "newservice"
3. Enter the command to restart the service
```
soumyas-MacBook-Pro:rancher-v0.0.1 soumya$ ./rancher restart --type service newservice --batch-size 2
Multiple resources named newservice: service:1s13, service:1s13
Not found: --batch-size
Not found: 2
FATA[0002] Not found: 2                  
```
```
soumyas-MacBook-Pro:rancher-v0.0.1 soumya$ ./rancher stop --type=service newservice
Multiple resources named newservice: service:1s13, service:1s13
FATA[0001] Multiple resources named newservice: service:1s13, service:1s13 
```

```
soumyas-MacBook-Pro:rancher-v0.0.1 soumya$ ./rancher start --type service newservice
Multiple resources named newservice: service:1s13, service:1s13
FATA[0001] Multiple resources named newservice: service:1s13, service:1s13 
```

Note: "./rancher restart/start/stop newservice" functions correctly without any options

**Comment by deniseschannon** [comment]
@soumyalj First example is user error. All options need to be before the arguments. 

```
$ rancher restart --type service --batch-size 2 newservice
```

Second example is user error. There should be no `=` between type and service.

Last example is the only valid example. 
```

**Comment by soumyalj** [comment]
Tested with v0.1.0-rc2. rancher restart/stop/star commands function correctly with --type option.
```
soumyas-MacBook-Pro:rancher-v0.1.0-rc2 soumya$ ./rancher stop --type service newstack/test2
1s2
soumyas-MacBook-Pro:rancher-v0.1.0-rc2 soumya$ ./rancher start --type service newstack/test2
1s2
soumyas-MacBook-Pro:rancher-v0.1.0-rc2 soumya$ ./rancher restart --type container newstack_test2_1
1i3

```
