### ISSUE TITLE
GHE auth integration stalls when not authorized

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#5649]
**Rancher Version:**
1.1.2

**Docker Version:**
1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
bare metal ROS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
When a team member is not in the configured organization within Rancher for the GHE SSO, the UI returns after Github authentication and just sits on the spinner screen

**Results:** 
spinner screen

**Expected:**
spinner goes away and error is shown.

**Comment by aemneina** [comment]
![ui_spinner](https://cloud.githubusercontent.com/assets/474978/17451935/9445f5be-5b1f-11e6-8c11-d60b0dc0f5b4.png)

**Comment by tfiduccia** [comment]
Version - v1.2.0-pre3-rc3
Verified fixed
