### ISSUE TITLE
Stacks - Activating (In Progress)

### ISSUE THREAD

**Issue by chrisneal** [rancher/rancher#5651]
Stacks never stop showing as "Activating (In Progress)".

It is an HA setup, with 3 servers. Brand new installation. This is the second time this has happened. The first time was earlier today with the exact same setup, though I thought that I would just start again from scratch before I filled an issue, incase something weird happened while I was getting everything setup.

Once the HA environment was setup, and all 3 services showed as "InService" (I'm using ELB's), I created a new Environment and then created a new, empty stack. https://www.dropbox.com/s/1wf2uy5ak4jw3w2/Screenshot%202016-08-06%2019.10.58.png?dl=0

I read in another ticket that a guy solved this issue by restarting each HA instance one at a time. I tried that the first time this happened, though that didn't solve it for me.

Yesterday, I setup v1.1.0 though I had issues with the LB's constantly 503'ing, so I decided to start from scratch with v1.1.2 to see if that fixed the 503 issue.

Let me know if there is any more info I can give you. I really need to get a solid Rancher setup working, before we use it in any production environments.

Thank you.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.1.2` Cattle: `v0.165.8` UI: `v1.1.12` |
|Access|`github` `admin`|
|Orchestration|`Cattle`|
|Route|`admin-tab.ha`|

**Comment by chrisneal** [comment]
Looking at the "System HA" Environment, the "go-machine-service" and the "rancher-compose-executor" were both Stopped. I removed the containers, and then edited/saved the service. This rebooted the containers, and then everything went back to normal. Incase that helps.

**Comment by aemneina** [comment]
@chrisneal sounds like your issue is solved (solved itself?). I'll close this.

**Comment by chrisneal** [comment]
I figured out the root issue. Updating the Rancher URL in the admin, doesn't update the "CATTLE_URL" env for the go-machine-service (https://github.com/rancher/go-machine-service/blob/ca6cb63e0e2df2e2a3bfa9c755bbf3795bd0c4fc/main.go#L23). So the go-machine-services won't ever boot, as it says it can't connect to the CATTLE_URL.

**Comment by aemneina** [comment]
I can see that by restarting the container it wont get the updated CATTLE_URL. I think a simple delete of the container will prompt rancher to recreate it with the newly updated url.

**Comment by chrisneal** [comment]
That doesn't work either, tried that a few times.
