### ISSUE TITLE
is dc/os in rancher's future plan?

### ISSUE THREAD

**Issue by kiwiwin** [rancher/rancher#5653]
**Rancher Version:** na

**Docker Version:** na

**OS and where are the hosts located? (cloud, bare metal, etc):** na

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**na

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**na

**Steps to Reproduce:**na

**Results:** na

**Expected:**na

**Comment by will-chan** [comment]
It's possible given they have open sourced it.  However, it is not in the immediate roadmap (1.3 timeframe next 3 months) unless there is a very strong demand for it.

**Comment by pvcon13** [comment]
Mesos Marathon in Rancher is great. It would be very helpful if the Mesos DNS component of DC/OS could be added in  the Mesos catalog. Right now without it there are some issues when containers fails and move between hosts when the app is launched by Marathon. So for that reason DC/OS is more immediately usable inside Rancher.
