### ISSUE TITLE
Rancher HA showing incorrect number of hosts

### ISSUE THREAD

**Issue by chrisurwin** [rancher/rancher#5656]
**Rancher Version:**
All
**Docker Version:**
All
**OS and where are the hosts located? (cloud, bare metal, etc):**
AWS Rancher OS 0.4.5
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
3 node HA
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
N/A
**Steps to Reproduce:**
Create a blank database and use a previously generated rancher-ha.sh to stand up a cluster without priming the database.
**Results:** 
The HA cluster stands up and works fine, but going to the Admin/High-Availability tab always shows 0 hosts.
**Expected:**
In my instance it should show 3 hosts not 0

**Comment by deniseschannon** [comment]
Duplicate of https://github.com/rancher/rancher/issues/5374
