### ISSUE TITLE
Adding CATTLE_CADVISOR_OPTS to agent.conf not working

### ISSUE THREAD

**Issue by roflmao** [rancher/rancher#5657]
**Rancher Version:**
1.1.2

**Docker Version:**
1.12.0

**OS and where are the hosts located? (cloud, bare metal, etc):**
Bare metal, ubuntu 14.04

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Add line to /var/lib/rancher/etc/agent.conf:

```
CATTLE_CADVISOR_OPTS='-storage_driver=statsd -storage_driver_host="192.168.67.15:8125"'
```

Restart rancher agent

**Results:** 
cadvisor still run without opts in agent.conf:

```
root     19075  0.0  0.0  17968  1528 ?        S    14:00   0:00 /bin/bash /var/lib/cattle/bin/cadvisor.sh cadvisor -logtostderr=true -listen_ip 127.0.0.1 -port 9344 -housekeeping_interval 1s -docker_root /var/lib/docker
```

**Expected:**
Expected cadvisor to be run with $CATTLE_CADVISOR_OPTS

**Comment by xeroo** [comment]
Maybe you should use `export CATTLE_CADVISOR_OPTS='-storage_driver=statsd -storage_driver_host="192.168.67.15:8125"'`, this works for me.

**Comment by vincent99** [comment]
As of 1.2.0 we use docker stats instead of bundling cAdvisor, so this is no longer relevant.
