### ISSUE TITLE
"rancher exec" does not provide output if an output comes from exec unless -i is included 

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#5662]
**Rancher Version:**Master

**Docker Version:**1.10.3 and 1.12.0

**Rancher CLI version:** v0.0.1

**OS and where are the hosts located? (cloud, bare metal, etc):** Ubuntu, Cloud

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**: Cattle

**Steps to Reproduce:**
1. Create a rancher-cli set up and create a container on one of the hosts
2. There is no response to the commands below: 
./rancher exec Default_mycont_1 ls

./rancher exec Default_mycont_1 echo hi

**Comment by deniseschannon** [comment]
@soumyalj Have you tried testing these same commands on a running docker container?

Are these valid commands?

```
$ docker exec containerID ls
$ docker exec containerID echo hi
```

**Comment by deniseschannon** [comment]
```
rancher_darwin-amd64 exec -i -t 1i8 bash
root@d5542b159bed:/# 
```

```
# Provides an output as expected
$ rancher exec -i 1i9  echo hi
hi
```

@ibuildthecloud the `-i` is not required for a `docker exec container echo hi`, so why is it required for `rancher exec` to get the output?

**Comment by soumyalj** [comment]
Verified with rancher-v0.1.0-rc1 ( -i option is not required)
