### ISSUE TITLE
rancher-cli complaining about missing /v1 in RANCHER_URL

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#5667]
**Rancher Version:**
Rancher Server: v1.2.0-pre1
Rancher CLI: v0.0.1
**Docker Version:**

**Steps to Reproduce:**
set environtment variable for RANCHER_URL=<server_ip>

there is no trailing /v1

**Results:** 
rancher cli complaints about missing path:
mudboxR:rancher-cli ahmad$ ./rancher stack help
FATA[0000] Invalid URL http://127.0.0.1:8080/, must contain /v1

**Expected:**
no need to add trailing /v1 to the environment variable, maintain consistency with rancher-compose.

Example of inconsistency:

mudboxR:rancher-compose ahmad$ export RANCHER_URL=http://127.0.0.1:8080/
mudboxR:rancher-compose ahmad$ rancher-compose up -u
WARN[0000] A newer version of rancher-compose is available: 0.9.0
INFO[0000] Project [rancher-compose]: Starting project
INFO[0000] [0/1] [ubuContainer]: Starting
INFO[0000] [1/1] [ubuContainer]: Started
INFO[0000] Project [rancher-compose]: Project started

...

mudboxR:rancher-cli ahmad$ ./rancher stack
FATA[0000] Invalid URL http://127.0.0.1:8080/, must contain /v1

**Comment by deniseschannon** [comment]
Verified with v0.1.0-rc2

**Comment by clescot** [comment]
i encounter this issue with rancher v1.2.0-pre3, rancher-cli v0.2.0, docker 1.12.1, when i execute `rancher catalog `. But `rancher env`, `rancher hosts` ,  `rancher stacks`or other commands works.

**Comment by clescot** [comment]
adding /v1 to rancher-url like explained in the doc (http://docs.rancher.com/rancher/v1.2/en/cli/) solves this issue.

**Comment by deniseschannon** [comment]
Thanks @clescot. I've opened up this issue for what you found. https://github.com/rancher/rancher/issues/6046
