### ISSUE TITLE
Not able to use dataVolumesFrom links in the docker-compose.yml when containers don't exist in the local machine

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#567]
Server version - V0.16.3

Steps to reproduce the problem:

Create Environment.
Create a service with scale1 specifying the host (h1) in "Security/Host" section and having volumes mounted from a container that is in a different host (dataVolumesFrom option).

Activate service.

Use "Export Config" for Environment to generate the docker-compose.yml

Use this docker-compose.yml file to create the instances.

Following error is seen:

Sangeethas-MacBook-Pro:~ sangeethahariharan1$ docker-compose up
Service "test-366326" mounts volumes from "ad8cd8ae-c73c-4ca3-9597-ae86dbda5cf3", which is not the name of a service or container.

**Comment by alena1108** [comment]
Regular docker-compose will also have this problem if you try to re-use the docker-compose.yml on a diff host where referenced volumes are not present.

**Comment by deniseschannon** [comment]
This is an issue with Docker as well, so we won't fix.
