### ISSUE TITLE
LDAP group DN 

### ISSUE THREAD

**Issue by asanami** [rancher/rancher#5670]
**Rancher Version:**

1.1.1

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

single node rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

Cattle

**Steps to Reproduce:**

Configure access control through OpenLDAP

**Expected:**

Is it possible to support authentication through LDAP groups, so users in a particular DN can log in rather than the entire organisation.  And also Admin users set through a similar DN group.

**Comment by frleb** [comment]
+1

**Comment by fuhbar** [comment]
@asanami If you are asking for authentication an user based on LDAP credentials and authorization based on LDAP group membership, then the answer is: this has already been implemented.

Try enabling OpenLDAP via the "Admin" -> "Access Control" menu entry. For being successful at that you need to know the DN and password of an existing service account in your LDAP tree which rancher uses to bind onto your LDAP tree. After that you are able to permit/restrict access to particular environments based on LDAP groups (See Manage Environments). 

The second part of your question, i think, is referring to something discussed in issue #5488

**Comment by flypenguin** [comment]
when did that land? because I also think that you can't do group-based authentication - my last test, which is about 5 weeks old, resulted in full access for EVERY ldap user. so the authentication basically mutated to a "are you in LDAP so you may pass" thing.

**Comment by prachidamle** [comment]
I think what @flypenguin is asking for setting restricted access to Rancher based on groups in ldap. This will deny login to any users out of the groups. 

This is implemented for Active Directory - not yet for OpenLDAP access.

I think this is same as issue https://github.com/rancher/rancher/issues/5141

**Comment by flypenguin** [comment]
Well, not only login / not login, but to be able to have the full group-based management what is done when using GitHub authentication. At least environment-based access for different groups, and admin / non-admin access, etc. :)

**Comment by prachidamle** [comment]
@flypenguin environment-based access for different groups is already supported, that is what @funbar mentioned in his comment.

 And login / not login will be taken care of by https://github.com/rancher/rancher/issues/5141

Can you describe what other functionality you are looking for  other than the two above?

**Comment by deniseschannon** [comment]
Closing in favor of #5141. 

@flypenguin The admin functionality based on groups would be this ticket. Basically,  being able to give admin access to an entire group instead of individually. https://github.com/rancher/rancher/issues/5488
