### ISSUE TITLE
HA setup-When github/local authentication is enabled,user is brought back to a page where authentication is still not on.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#5673]
Rancher Version: v1.1.2

3 Rancher server hosts in HA setup.

Enable github/local authentication.
Once authentication is turned on, user is brought back to a page which indicates that "Access Control" is still off.

Once user refreshes manually ,set authentication is acknowledged.

**Comment by tfiduccia** [comment]
Comment - the token is being written to database but the other host do not seem to be seeing that immediately.

**Comment by sangeethah** [comment]
When re-enabling github authentication (enable github auth , disable auth , re-enable gihub) , first attempt to authenticate fails.

<img width="1416" alt="screen shot 2016-08-09 at 1 07 16 pm" src="https://cloud.githubusercontent.com/assets/4266958/17532726/d2bd5bec-5e36-11e6-96ca-fb38e76e72ca.png">

But on retry it succeeds.

**Comment by kmcgrath** [comment]
We also receive the following error often, but not always, when enabling Local Auth on a fresh HA setup.  Clicking "Enable Local Auth" again will move the process forward where we run into the same issue that you describe in the ticket.

![rancher](https://cloud.githubusercontent.com/assets/821709/17556590/edca60a0-5ee1-11e6-802d-c70dbf63912d.png)

**Comment by will-chan** [comment]
Are we caching something in Rancher?

**Comment by deniseschannon** [comment]
With the new HA in 1.2, this is no longer applicable as we've refactored HA to be much simpler and just run additional arguments with the rancher-server command.

@sangeethah Did you want to test it?

**Comment by galal-hussein** [comment]
Tested all the cases on Rancher HA on version 1.2.0, i didn't encounter any of the mentioned problems.
