### ISSUE TITLE
./rancher events displays only events on hosts that are active, no other events are displayed.

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#5675]
Rancher Version:Master

Docker Version:1.10.3, 1.12.0

Rancher CLI version: v0.0.1

OS and where are the hosts located? (cloud, bare metal, etc):Ubuntu, Cloud

Environment Type: (Cattle/Kubernetes/Swarm/Mesos): Cattle

Steps to Reproduce:
1. Create a rancher-cli set up and create stacks, services 

```
soumyas-MacBook-Pro:rancher-v0.0.1 soumya$ ./rancher events
host 1h3 active [] 
host 1h4 active [] 
host 1h5 active [] 
host 1h3 active [] 
host 1h4 active [] 
host 1h5 active [] 
```
We should be able to obtain events specific to a service or a specific event type or all the events similar to the feature provided in the UI.
The help does not provide detailed information on how to use this command:
```
soumyas-MacBook-Pro:rancher-v0.0.1 soumya$ ./rancher events --help
Usage: rancher events [OPTIONS] [arg...]

Show services/containers

Options:
   
   --reconnect, -r  Reconnect on error

```

**Comment by deniseschannon** [comment]
@soumyalj I am able to get more than active host events. 

```
port 1p6112 purged [] 
port 1p6113 removed [] 
instanceLink 1il6155 removed [] 
volume 1v6306 purged [] 
instanceLink 1il6154 purged [] 
container 1i6222 purged [newtest_test_1] 
volume 1v6307 removed [] 
serviceExposeMap 1sem6262 removed [] 
container 1i6223 removed [newtest_test_1] 
serviceExposeMap 1sem6263 active [] 
container 1i6224 creating [newtest_test_1] In Progress
volume 1v6308 inactive [] 
port 1p6115 inactive [] 
instanceLink 1il6157 inactive [] 
container 1i6224 error [newtest_test_1] Scheduling failed: host needs ports 80/tcp available
host 1h3 active [] 
host 1h2 active [] 
host 1h1 active [] 
port 1p6114 removed [] 
instanceLink 1il6156 removed [] 
volume 1v6307 purged [] 
port 1p6113 purged [] 
instanceLink 1il6155 purged [] 
container 1i6223 purged [newtest_test_1
```

It's only showing resources events that are currently going on. Since we check hosts every 5-15 minutes, it will keep repeating the active hosts.
 
Please try again and add stacks/services while the command is running. 

If you want to search for a specific item, please try

`rancher events | grep foo`

**Comment by soumyalj** [comment]
Verified with rancher-cli v0.0.2. Other events are displayed when any service/contaner is created.
