### ISSUE TITLE
Enhancement Support CPU Quota and CPU period from compose/UI

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#5677]
Cattle doesn't support cpu_quota and cpu_period from compose. We need to add these to our launch configs.

It looks like libcompose is already able to support CPUQuota, it doesn't make it to the host though.

**Comment by deniseschannon** [comment]
Closing in favor of the PRs that will allow us to support the missing cattle fields:

Cattle Changes: https://github.com/rancher/rancher/issues/4708
Rancher-compose: https://github.com/rancher/rancher/issues/6280
Exporting yml: https://github.com/rancher/rancher/issues/6281
UI: https://github.com/rancher/rancher/issues/6282
