### ISSUE TITLE
[Layout Issue] Environment cut off on navigation bar

### ISSUE THREAD

**Issue by bkuhl** [rancher/rancher#5680]
Environment name is so long it extends into the other menu items.

![screen shot 2016-08-10 at 7 36 29 am](https://cloud.githubusercontent.com/assets/524933/17552329/4c9b1788-5ecd-11e6-91b5-c3227021a0ac.png)

Here's the dimensions of my browser:

![screen shot 2016-08-10 at 7 38 41 am](https://cloud.githubusercontent.com/assets/524933/17552358/813eb490-5ecd-11e6-9619-b2b97a3032a1.png)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.1.1` Cattle: `v0.165.7` UI: `v1.1.12` |
|Access|`github` `admin`|
|Orchestration|`Cattle`|
|Route|`authenticated.project.waiting`|

**Comment by tfiduccia** [comment]
@bkuhl This has been fixed in our current build.
