### ISSUE TITLE
Can't configure rancher in HA mode.

### ISSUE THREAD

**Issue by amsdard** [rancher/rancher#5681]
**Rancher Version:** 
1.12

**Docker Version:** 
 1.11.2

**OS and where are the hosts located? (cloud, bare metal, etc):** 
virtualbox with: ubuntu/trusty64, debian/wheezy64, bento/centos-7.1

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
 HA rancher and external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Swarm

**Steps to Reproduce:**
Follow steps to setup multi-node rancher: http://docs.rancher.com/rancher/v1.2/en/installing-rancher/installing-server/multi-nodes/

Configure haproxy on 4th node (ip: 172.28.128.100)

> global
>         log /dev/log local2
>         maxconn 4096
>         maxpipes 1024
>         uid 99
>         gid 99
>         daemon
> 
> defaults
>         log     global
>         mode    tcp
>         option  tcplog
>         option  dontlognull
>         option  redispatch
>         option http-server-close
>         retries 3
>         timeout connect 5000
>         timeout client 50000
>         timeout server 50000
> 
> frontend rancher_80_frontend
>     bind *:80
>     mode http
> 
>     default_backend rancher_80_backend
> 
> frontend rancher_443_frontend
>     bind *:443
>     mode tcp
> 
>     default_backend rancher_443_backend
> 
> frontend rancher_18080_frontend
>     bind *:18080
>     mode http
> 
>     default_backend rancher_18080_backend
> 
> backend rancher_80_backend
>         mode http
>         server rancher_01  172.28.128.200::80
>         server rancher_02  172.28.128.211::80
>         server rancher_03  172.28.128.221::80
> 
> backend rancher_443_backend
>         mode tcp
>         server rancher_01 172.28.128.200:443 check
>         server rancher_02 172.28.128.211:443 check
>         server rancher_03 172.28.128.221:443 check
> 
> backend rancher_18080_backend
>         mode http
>         server rancher_01 172.28.128.200:18080
>         server rancher_02 172.28.128.211:18080
>         server rancher_03 172.28.128.221:18080

Run rancher-ha.sh on 3 different nodes with host registration url set to haproxy node: https://172.28.128.100 and auto generated certificates.

Before I have run rancher-ha.sh I have removed all previous containers.

netstat -tunlp before running script:
> Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
> tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      981/sshd
> tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      1321/master
> tcp6       0      0 :::2376                 :::*                    LISTEN      13392/docker
> tcp6       0      0 :::22                   :::*                    LISTEN      981/sshd
> tcp6       0      0 ::1:25                  :::*                    LISTEN      1321/master
> udp        0      0 0.0.0.0:53188           0.0.0.0:*                           11722/dhclient
> udp        0      0 0.0.0.0:68              0.0.0.0:*                           11722/dhclient
> udp6       0      0 :::8979                 :::*                                11722/dhclient

No firewall, all ports are open.

**Results:** 

Nothing works, redis, ha-zk, ha-tunnel are spawned multiple times and keep restarting. 
 
Docker ps on all nodes shows something like this:

> CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                          PORTS                                                                                                                                   NAMES
> 4a47ba859b19        rancher/server      "tunnel -d -s [0.0.0."   57 seconds ago      Restarting (1) 5 seconds ago                                                                                                                                            rancher-ha-tunnel-zk-leader-1
> a8583513ecd5        rancher/server      "tunnel -d -s [0.0.0."   57 seconds ago      Restarting (1) 5 seconds ago                                                                                                                                            rancher-ha-tunnel-zk-quorum-1
> 2be2416781f9        rancher/server      "tunnel -d -s [0.0.0."   57 seconds ago      Restarting (1) 5 seconds ago                                                                                                                                            rancher-ha-tunnel-redis-1
> bd8869f69ebe        rancher/server      "cattle"                 3 minutes ago       Up 45 seconds                                                                                                                                                           rancher-ha-cattle
> 70f8b8cfa24c        rancher/server      "tunnel -d -s [0.0.0."   3 minutes ago       Up 3 minutes                                                                                                                                                            rancher-ha-tunnel-zk-leader-2
> 43a8005fb3e3        rancher/server      "tunnel -d -s [0.0.0."   3 minutes ago       Up 3 minutes                                                                                                                                                            rancher-ha-tunnel-zk-quorum-2
> 077d5d7b437c        rancher/server      "tunnel -d -s [0.0.0."   3 minutes ago       Up 3 minutes                                                                                                                                                            rancher-ha-tunnel-redis-2
> 6b277a6481e4        rancher/server      "tunnel -d -s [0.0.0."   4 minutes ago       Up 3 minutes                                                                                                                                                            rancher-ha-tunnel-zk-client-2
> 35ce0dd81499        rancher/server      "parent"                 4 minutes ago       Up 4 minutes                    3306/tcp, 0.0.0.0:18080->8080/tcp, 0.0.0.0:2181->12181/tcp, 0.0.0.0:2888->12888/tcp, 0.0.0.0:3888->13888/tcp, 0.0.0.0:6379->16379/tcp   rancher-ha-parent
> 7fa178a9c610        rancher/server      "ha"                     4 minutes ago       Restarting (1) 56 seconds ago                                                                                                                                           rancher-ha
> db3738f7c6ab        rancher/server      "tunnel -d -s [0.0.0."   14 minutes ago      Restarting (1) 14 minutes ago                                                                                                                                           rancher-ha-tunnel-redis-3

docker logs rancher-ha:

> time="2016-08-09T08:11:33Z" level=info msg="Cluster changed, index=0, members=[10.0.2.15, , 10.0.2.15]" component=service
> time="2016-08-09T08:11:33Z" level=info msg="Deleting container db3738f7c6aba86818a27f952ed72d15c85ed9eb8ea5437e03b842d0119aec2f" component=docker
> time="2016-08-09T08:11:33Z" level=info msg="Creating container rancher-ha-parent" component=docker
> time="2016-08-09T08:11:34Z" level=info msg="Creating container rancher-ha-tunnel-redis-1" component=docker
> time="2016-08-09T08:11:34Z" level=info msg="Creating container rancher-ha-tunnel-zk-quorum-1" component=docker
> time="2016-08-09T08:11:34Z" level=info msg="Creating container rancher-ha-tunnel-zk-leader-1" component=docker
> time="2016-08-09T08:11:35Z" level=info msg="Creating container rancher-ha-tunnel-zk-client-1" component=docker
> time="2016-08-09T08:11:35Z" level=info msg="Container tunnel-redis-3 is not running in state &types.ContainerState{Status:\"restarting\", Running:true, Paused:false, Restarting:true, OOMKilled:false, Dead:false, Pid:0, ExitCode:1, Error:\"\", StartedAt:\"2016-08-09T08:02:01.273780197Z\", FinishedAt:\"2016-08-09T08:02:01.283250091Z\"}" component=docker
> time="2016-08-09T08:11:35Z" level=info msg="Deleting container db3738f7c6aba86818a27f952ed72d15c85ed9eb8ea5437e03b842d0119aec2f" component=docker
> time="2016-08-09T08:11:35Z" level=info msg="Creating container rancher-ha-tunnel-redis-3" component=docker
> time="2016-08-09T08:11:35Z" level=fatal msg="Failed to create manager" err="Error response from daemon: Conflict. The name \"/rancher-ha-tunnel-redis-3\" is already in use by container db3738f7c6aba86818a27f952ed72d15c85ed9eb8ea5437e03b842d0119aec2f. You have to remove (or rename) that container to be able to reuse that name."
> time="2016-08-09T08:11:35Z" level=info msg="Cluster changed, index=0, members=[10.0.2.15, , 10.0.2.15]" component=service
> time="2016-08-09T08:11:35Z" level=info msg="Container tunnel-redis-3 is not running in state &types.ContainerState{Status:\"restarting\", Running:true, Paused:false, Restarting:true, OOMKilled:false, Dead:false, Pid:0, ExitCode:1, Error:\"\", StartedAt:\"2016-08-09T08:02:01.273780197Z\", FinishedAt:\"2016-08-09T08:02:01.283250091Z\"}" component=docker
> time="2016-08-09T08:11:35Z" level=info msg="Deleting container db3738f7c6aba86818a27f952ed72d15c85ed9eb8ea5437e03b842d0119aec2f" component=docker
> time="2016-08-09T08:11:35Z" level=info msg="Creating container rancher-ha-tunnel-redis-3" component=docker
> time="2016-08-09T08:11:35Z" level=fatal msg="Failed to create manager" err="Error response from daemon: Conflict. The name \"/rancher-ha-tunnel-redis-3\" is already in use by container db3738f7c6aba86818a27f952ed72d15c85ed9eb8ea5437e03b842d0119aec2f. You have to remove (or rename) that container to be able to reuse that name."
> time="2016-08-09T08:11:35Z" level=info msg="Cluster changed, index=0, members=[10.0.2.15, , 10.0.2.15]" component=service
> time="2016-08-09T08:11:35Z" level=info msg="Container tunnel-redis-3 is not running in state &types.ContainerState{Status:\"restarting\", Running:true, Paused:false, Restarting:true, OOMKilled:false, Dead:false, Pid:0, ExitCode:1, Error:\"\", StartedAt:\"2016-08-09T08:02:01.273780197Z\", FinishedAt:\"2016-08-09T08:02:01.283250091Z\"}" component=docker
> time="2016-08-09T08:11:35Z" level=info msg="Deleting container db3738f7c6aba86818a27f952ed72d15c85ed9eb8ea5437e03b842d0119aec2f" component=docker
> time="2016-08-09T08:11:35Z" level=info msg="Creating container rancher-ha-tunnel-redis-3" component=docker
> time="2016-08-09T08:11:35Z" level=fatal msg="Failed to create manager" err="Error response from daemon: Conflict. The name \"/rancher-ha-tunnel-redis-3\" is already in use by container db3738f7c6aba86818a27f952ed72d15c85ed9eb8ea5437e03b842d0119aec2f. You have to remove (or rename) that container to be able to reuse that name."
> time="2016-08-09T08:11:36Z" level=info msg="Cluster changed, index=0, members=[10.0.2.15, , 10.0.2.15]" component=service
> time="2016-08-09T08:11:36Z" level=info msg="Container tunnel-redis-3 is not running in state &types.ContainerState{Status:\"restarting\", Running:true, Paused:false, Restarting:true, OOMKilled:false, Dead:false, Pid:0, ExitCode:1, Error:\"\", StartedAt:\"2016-08-09T08:02:01.273780197Z\", FinishedAt:\"2016-08-09T08:02:01.283250091Z\"}" component=docker
> time="2016-08-09T08:11:36Z" level=info msg="Deleting container db3738f7c6aba86818a27f952ed72d15c85ed9eb8ea5437e03b842d0119aec2f" component=docker
> time="2016-08-09T08:11:36Z" level=info msg="Creating container rancher-ha-tunnel-redis-3" component=docker
> time="2016-08-09T08:11:36Z" level=fatal msg="Failed to create manager" err="Error response from daemon: Conflict. The name \"/rancher-ha-tunnel-redis-3\" is already in use by container db3738f7c6aba86818a27f952ed72d15c85ed9eb8ea5437e03b842d0119aec2f. You have to remove (or rename) that container to be able to reuse that name."
> time="2016-08-09T08:11:37Z" level=info msg="Cluster changed, index=0, members=[10.0.2.15, , 10.0.2.15]" component=service
> time="2016-08-09T08:11:37Z" level=info msg="Container tunnel-redis-3 is not running in state &types.ContainerState{Status:\"restarting\", Running:true, Paused:false, Restarting:true, OOMKilled:false, Dead:false, Pid:0, ExitCode:1, Error:\"\", StartedAt:\"2016-08-09T08:02:01.273780197Z\", FinishedAt:\"2016-08-09T08:02:01.283250091Z\"}" component=docker
> time="2016-08-09T08:11:37Z" level=info msg="Deleting container db3738f7c6aba86818a27f952ed72d15c85ed9eb8ea5437e03b842d0119aec2f" component=docker
> time="2016-08-09T08:11:37Z" level=info msg="Creating container rancher-ha-tunnel-redis-3" component=docker
> time="2016-08-09T08:11:37Z" level=fatal msg="Failed to create manager" err="Error response from daemon: Conflict. The name \"/rancher-ha-tunnel-redis-3\" is already in use by container db3738f7c6aba86818a27f952ed72d15c85ed9eb8ea5437e03b842d0119aec2f. You have to remove (or rename) that container to be able to reuse that name."
> time="2016-08-09T08:11:38Z" level=info msg="Cluster changed, index=0, members=[10.0.2.15, , 10.0.2.15]" component=service
> time="2016-08-09T08:11:38Z" level=info msg="Container tunnel-redis-3 is not running in state &types.ContainerState{Status:\"restarting\", Running:true, Paused:false, Restarting:true, OOMKilled:false, Dead:false, Pid:0, ExitCode:1, Error:\"\", StartedAt:\"2016-08-09T08:02:01.273780197Z\", FinishedAt:\"2016-08-09T08:02:01.283250091Z\"}" component=docker
> time="2016-08-09T08:11:38Z" level=info msg="Deleting container db3738f7c6aba86818a27f952ed72d15c85ed9eb8ea5437e03b842d0119aec2f" component=docker
> time="2016-08-09T08:11:38Z" level=info msg="Creating container rancher-ha-tunnel-redis-3" component=docker
> time="2016-08-09T08:11:38Z" level=fatal msg="Failed to create manager" err="Error response from daemon: Conflict. The name \"/rancher-ha-tunnel-redis-3\" is already in use by container db3738f7c6aba86818a27f952ed72d15c85ed9eb8ea5437e03b842d0119aec2f. You have to remove (or rename) that container to be able to reuse that name."
> time="2016-08-09T08:11:42Z" level=info msg="Cluster changed, index=0, members=[10.0.2.15, , 10.0.2.15]" component=service
> time="2016-08-09T08:11:42Z" level=info msg="Container tunnel-redis-3 is not running in state &types.ContainerState{Status:\"restarting\", Running:true, Paused:false, Restarting:true, OOMKilled:false, Dead:false, Pid:0, ExitCode:1, Error:\"\", StartedAt:\"2016-08-09T08:02:01.273780197Z\", FinishedAt:\"2016-08-09T08:02:01.283250091Z\"}" component=docker
> time="2016-08-09T08:11:42Z" level=info msg="Deleting container db3738f7c6aba86818a27f952ed72d15c85ed9eb8ea5437e03b842d0119aec2f" component=docker
> time="2016-08-09T08:11:42Z" level=info msg="Creating container rancher-ha-tunnel-redis-3" component=docker
> time="2016-08-09T08:11:42Z" level=fatal msg="Failed to create manager" err="Error response from daemon: Conflict. The name \"/rancher-ha-tunnel-redis-3\" is already in use by container db3738f7c6aba86818a27f952ed72d15c85ed9eb8ea5437e03b842d0119aec2f. You have to remove (or rename) that container to be able to reuse that name."
> time="2016-08-09T08:11:48Z" level=info msg="Cluster changed, index=0, members=[10.0.2.15, 10.0.2.15, 10.0.2.15]" component=service
> time="2016-08-09T08:11:48Z" level=info msg="Creating container rancher-ha-tunnel-redis-2" component=docker
> time="2016-08-09T08:11:48Z" level=info msg="Creating container rancher-ha-tunnel-zk-quorum-2" component=docker
> time="2016-08-09T08:11:49Z" level=info msg="Creating container rancher-ha-tunnel-zk-leader-2" component=docker
> time="2016-08-09T08:11:49Z" level=info msg="Creating container rancher-ha-tunnel-zk-client-2" component=docker
> time="2016-08-09T08:11:49Z" level=info msg="Container tunnel-redis-3 is not running in state &types.ContainerState{Status:\"restarting\", Running:true, Paused:false, Restarting:true, OOMKilled:false, Dead:false, Pid:0, ExitCode:1, Error:\"\", StartedAt:\"2016-08-09T08:02:01.273780197Z\", FinishedAt:\"2016-08-09T08:02:01.283250091Z\"}" component=docker
> time="2016-08-09T08:11:49Z" level=info msg="Deleting container db3738f7c6aba86818a27f952ed72d15c85ed9eb8ea5437e03b842d0119aec2f" component=docker
> time="2016-08-09T08:11:49Z" level=info msg="Creating container rancher-ha-tunnel-redis-3" component=docker
> time="2016-08-09T08:11:49Z" level=fatal msg="Failed to create manager" err="Error response from daemon: Conflict. The name \"/rancher-ha-tunnel-redis-3\" is already in use by container db3738f7c6aba86818a27f952ed72d15c85ed9eb8ea5437e03b842d0119aec2f. You have to remove (or rename) that container to be able to reuse that name."
> time="2016-08-09T08:12:02Z" level=info msg="Cluster changed, index=0, members=[10.0.2.15, 10.0.2.15, 10.0.2.15]" component=service
> time="2016-08-09T08:12:02Z" level=info msg="Container tunnel-redis-2 is not running in state &types.ContainerState{Status:\"restarting\", Running:true, Paused:false, Restarting:true, OOMKilled:false, Dead:false, Pid:0, ExitCode:1, Error:\"\", StartedAt:\"2016-08-09T08:12:02.071436089Z\", FinishedAt:\"2016-08-09T08:12:02.073674866Z\"}" component=docker
> time="2016-08-09T08:12:02Z" level=info msg="Deleting container 73f4d70a4265c754c0de2e69ed0e5549287ce7f0f64d1d5e1a5d4bafc57c906f" component=docker
> time="2016-08-09T08:12:02Z" level=info msg="Creating container rancher-ha-tunnel-redis-2" component=docker
> time="2016-08-09T08:12:03Z" level=info msg="Container tunnel-zk-quorum-2 is not running in state &types.ContainerState{Status:\"restarting\", Running:true, Paused:false, Restarting:true, OOMKilled:false, Dead:false, Pid:0, ExitCode:1, Error:\"\", StartedAt:\"2016-08-09T08:12:02.357690081Z\", FinishedAt:\"2016-08-09T08:12:02.364094009Z\"}" component=docker
> time="2016-08-09T08:12:03Z" level=info msg="Deleting container 6f7d8721c8aa8c520e132f0f10b723c9dd8265b220ba6cde22feab272132547b" component=docker
> time="2016-08-09T08:12:03Z" level=info msg="Creating container rancher-ha-tunnel-zk-quorum-2" component=docker
> time="2016-08-09T08:12:03Z" level=info msg="Container tunnel-zk-leader-2 is not running in state &types.ContainerState{Status:\"restarting\", Running:true, Paused:false, Restarting:true, OOMKilled:false, Dead:false, Pid:0, ExitCode:1, Error:\"\", StartedAt:\"2016-08-09T08:12:02.64143165Z\", FinishedAt:\"2016-08-09T08:12:02.645306701Z\"}" component=docker
> time="2016-08-09T08:12:03Z" level=info msg="Deleting container 8f8536cdd68c572552e7e2c56fe479149a6a9ad518081b1728707ecd73c70d52" component=docker
> time="2016-08-09T08:12:03Z" level=info msg="Creating container rancher-ha-tunnel-zk-leader-2" component=docker
> time="2016-08-09T08:12:03Z" level=info msg="Container tunnel-zk-client-2 is not running in state &types.ContainerState{Status:\"restarting\", Running:true, Paused:false, Restarting:true, OOMKilled:false, Dead:false, Pid:0, ExitCode:1, Error:\"\", StartedAt:\"2016-08-09T08:12:02.980823807Z\", FinishedAt:\"2016-08-09T08:12:03.008581756Z\"}" component=docker
> time="2016-08-09T08:12:03Z" level=info msg="Deleting container c7eb8633df48ca67ed17b437c30a0ac8f1ca5aeaefd244a895283e69a0d42e61" component=docker
> time="2016-08-09T08:12:03Z" level=info msg="Creating container rancher-ha-tunnel-zk-client-2" component=docker
> time="2016-08-09T08:12:04Z" level=info msg="Container tunnel-redis-3 is not running in state &types.ContainerState{Status:\"restarting\", Running:true, Paused:false, Restarting:true, OOMKilled:false, Dead:false, Pid:0, ExitCode:1, Error:\"\", StartedAt:\"2016-08-09T08:02:01.273780197Z\", FinishedAt:\"2016-08-09T08:02:01.283250091Z\"}" component=docker
> time="2016-08-09T08:12:04Z" level=info msg="Deleting container db3738f7c6aba86818a27f952ed72d15c85ed9eb8ea5437e03b842d0119aec2f" component=docker
> time="2016-08-09T08:12:04Z" level=info msg="Creating container rancher-ha-tunnel-redis-3" component=docker
> time="2016-08-09T08:12:04Z" level=fatal msg="Failed to create manager" err="Error response from daemon: Conflict. The name \"/rancher-ha-tunnel-redis-3\" is already in use by container db3738f7c6aba86818a27f952ed72d15c85ed9eb8ea5437e03b842d0119aec2f. You have to remove (or rename) that container to be able to reuse that name."
> time="2016-08-09T08:12:29Z" level=info msg="Cluster changed, index=0, members=[, 10.0.2.15, ]" component=service
> time="2016-08-09T08:12:30Z" level=info msg="Container tunnel-redis-2 is not running in state &types.ContainerState{Status:\"restarting\", Running:true, Paused:false, Restarting:true, OOMKilled:false, Dead:false, Pid:0, ExitCode:1, Error:\"\", StartedAt:\"2016-08-09T08:12:29.243438681Z\", FinishedAt:\"2016-08-09T08:12:29.247944829Z\"}" component=docker
> time="2016-08-09T08:12:30Z" level=info msg="Deleting container 78a8358b8e64507be894fab653aebd3273acd0a93a1da356ff911c564fd1c35c" component=docker
> time="2016-08-09T08:12:30Z" level=info msg="Creating container rancher-ha-tunnel-redis-2" component=docker
> time="2016-08-09T08:12:30Z" level=info msg="Container tunnel-zk-quorum-2 is not running in state &types.ContainerState{Status:\"restarting\", Running:true, Paused:false, Restarting:true, OOMKilled:false, Dead:false, Pid:0, ExitCode:1, Error:\"\", StartedAt:\"2016-08-09T08:12:29.479454922Z\", FinishedAt:\"2016-08-09T08:12:29.484310856Z\"}" component=docker
> time="2016-08-09T08:12:30Z" level=info msg="Deleting container 03fcfe66030ae4310f53da5c67bcdf04de1a6522d515612b6d51f8629d10906e" component=docker
> time="2016-08-09T08:12:30Z" level=info msg="Creating container rancher-ha-tunnel-zk-quorum-2" component=docker
> time="2016-08-09T08:12:30Z" level=info msg="Container tunnel-zk-leader-2 is not running in state &types.ContainerState{Status:\"restarting\", Running:true, Paused:false, Restarting:true, OOMKilled:false, Dead:false, Pid:0, ExitCode:1, Error:\"\", StartedAt:\"2016-08-09T08:12:29.729916927Z\", FinishedAt:\"2016-08-09T08:12:29.736218712Z\"}" component=docker
> time="2016-08-09T08:12:30Z" level=info msg="Deleting container 3d4fbe1ae2f0a029bb191f46dcc3b60a5d209ea0e929f56881ed2f100128dc3b" component=docker
> time="2016-08-09T08:12:30Z" level=info msg="Creating container rancher-ha-tunnel-zk-leader-2" component=docker
> time="2016-08-09T08:12:31Z" level=info msg="Creating container rancher-ha-cattle" component=docker
> time="2016-08-09T08:12:31Z" level=info msg="Waiting for server to be available" component=cert
> time="2016-08-09T08:12:31Z" level=info msg="Can not launch agent right now: Server not available at http://172.17.0.1:18080/ping:" component=service
> time="2016-08-09T08:12:36Z" level=info msg="Cluster changed, index=3, members=[10.0.2.15, 10.0.2.15, 10.0.2.15]" component=service
> time="2016-08-09T08:12:36Z" level=info msg="Creating container rancher-ha-tunnel-redis-1" component=docker
> time="2016-08-09T08:12:36Z" level=info msg="Creating container rancher-ha-tunnel-zk-quorum-1" component=docker
> time="2016-08-09T08:12:36Z" level=info msg="Creating container rancher-ha-tunnel-zk-leader-1" component=docker
> time="2016-08-09T08:12:37Z" level=info msg="Creating container rancher-ha-tunnel-zk-client-1" component=docker
> time="2016-08-09T08:12:37Z" level=info msg="Container tunnel-redis-3 is not running in state &types.ContainerState{Status:\"restarting\", Running:true, Paused:false, Restarting:true, OOMKilled:false, Dead:false, Pid:0, ExitCode:1, Error:\"\", StartedAt:\"2016-08-09T08:02:01.273780197Z\", FinishedAt:\"2016-08-09T08:02:01.283250091Z\"}" component=docker
> time="2016-08-09T08:12:37Z" level=info msg="Deleting container db3738f7c6aba86818a27f952ed72d15c85ed9eb8ea5437e03b842d0119aec2f" component=docker
> time="2016-08-09T08:12:37Z" level=info msg="Creating container rancher-ha-tunnel-redis-3" component=docker
> time="2016-08-09T08:12:37Z" level=fatal msg="Failed to create manager" err="Error response from daemon: Conflict. The name \"/rancher-ha-tunnel-redis-3\" is already in use by container db3738f7c6aba86818a27f952ed72d15c85ed9eb8ea5437e03b842d0119aec2f. You have to remove (or rename) that container to be able to reuse that name."

docker logs rancher-ha-tunnel-zk-client-1

> spiped: error binding socket: Address already in use
> spiped: error binding socket: Address already in use
> spiped: error binding socket: Address already in use
> spiped: error binding socket: Address already in use
> spiped: error binding socket: Address already in use
> spiped: error binding socket: Address already in use
> spiped: error binding socket: Address already in use
> spiped: error binding socket: Address already in use
> spiped: error binding socket: Address already in use
> spiped: error binding socket: Address already in use

docker logs rancher-ha-tunnel-zk-leader-1

> spiped: error binding socket: Address already in use
> spiped: error binding socket: Address already in use
> spiped: error binding socket: Address already in use
> spiped: error binding socket: Address already in use
> spiped: error binding socket: Address already in use
> spiped: error binding socket: Address already in use
> spiped: error binding socket: Address already in use
> spiped: error binding socket: Address already in use
> spiped: error binding socket: Address already in use
> spiped: error binding socket: Address already in use

docker logs rancher-ha-tunnel-redis-1

> spiped: error binding socket: Address already in use
> spiped: error binding socket: Address already in use
> spiped: error binding socket: Address already in use
> spiped: error binding socket: Address already in use
> spiped: error binding socket: Address already in use
> spiped: error binding socket: Address already in use
> spiped: error binding socket: Address already in use

docker logs rancher-ha-cattle:

> Waiting for Zookeeper at localhost:2181
> Waiting for Zookeeper at localhost:2181
> Waiting for Zookeeper at localhost:2181
> Waiting for Zookeeper at localhost:2181
> Waiting for Zookeeper at localhost:2181
> Waiting for Zookeeper at localhost:2181
> Waiting for Zookeeper at localhost:2181
> Waiting for Zookeeper at localhost:2181
> Waiting for Zookeeper at localhost:2181
> Waiting for Zookeeper at localhost:2181
> Waiting for Zookeeper at localhost:2181
> Waiting for Zookeeper at localhost:2181
> Waiting for Zookeeper at localhost:2181
> Waiting for Zookeeper at localhost:2181
> Waiting for Zookeeper at localhost:2181
> Waiting for Zookeeper at localhost:2181
> Waiting for Zookeeper at localhost:2181
> Waiting for Zookeeper at localhost:2181
> Waiting for Zookeeper at localhost:2181
> Waiting for Zookeeper at localhost:2181
> Waiting for Zookeeper at localhost:2181
> Waiting for Zookeeper at localhost:2181
> Waiting for Zookeeper at localhost:2181
> Waiting for Zookeeper at localhost:2181
> Waiting for Zookeeper at localhost:2181
> Waiting for Zookeeper at localhost:2181
> Waiting for Zookeeper at localhost:2181
> Waiting for Zookeeper at localhost:2181
> Waiting for Zookeeper at localhost:2181
> Waiting for Zookeeper at localhost:2181
> Waiting for Zookeeper at localhost:2181
> Failed waiting for Zookeeper at localhost:2181

**Expected:**
Rancher server working in HA mode. Obviously I'm doing something totally wrong, but I read docs 10times, also checked other tutorials like https://thisendout.com/2016/05/04/deploying-rancher-with-ha-using-rancheros-aws-terraform-letsencrypt/ and still no luck. The only thing I have different is custom haproxy with the config provided.

Any help?

**Comment by aemneina** [comment]
Couple issues I see is that you should point the backend to either 80 or 443 and not 18080. Second I'm guessing virtual box hates inter-vm communication, esp on UDP ports. I haven't had success that route. Almost certain if you used this with a first class hypervisor, cloud provider or bare metal... you'll have a better chance.

**Comment by amsdard** [comment]
Thanks for update! You can close this thread.
