### ISSUE TITLE
Load Balancer drops requests during upgrades

### ISSUE THREAD

**Issue by willrstern** [rancher/rancher#5682]
**Rancher Version:**
1.12
**Docker Version:**

**OS and where are the hosts located? (cloud, bare metal, etc):**
AWS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node, external DB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle v0.165.8
**Steps to Reproduce:**
• Setup a hello-world service with a LB
• Run siege against the LB
• Upgrade the hello-world service

**Results:** 
requests are dropped whenever HAProxy reloads it's config

**Expected:**
no requests are dropped...perhaps implement something [like this fix?](https://medium.com/@Drew_Stokes/actual-zero-downtime-with-haproxy-18318578fde6#.bm5t2tqaq)

**Comment by alena1108** [comment]
Similar to https://github.com/rancher/rancher/issues/2777. Dropping existing connections is fixed for LB v1 with https://github.com/rancher/cattle/pull/2038
