### ISSUE TITLE
serviceId is not obfuscated when retrieving portRules for a Balancer service.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#5690]
Rancher Version: latest cattle build from lbrefactormetadata from https://github.com/alena1108/cattle.git

steps to reproduce the problem:
Create a balancer service with 1 target service.
Try to add another target by adding an additional portRule by appending to the existing portRule of the service. Service update fails with following error:
```
self = <cattle.Client object at 0x1099b1510>
text = '{"id":"c86e5009-982e-41f5-83e3-ff9f8bc2f93d","type":"error","links":{},"actions":{},"status":422,"code":"InvalidReference","message":null,"detail":null,"fieldName":"serviceId"}'

    def _error(self, text):
>       raise ApiError(self._unmarshall(text))
E       ApiError: (ApiError(...), "InvalidReference : None\n{'status': 422, 'code': u'InvalidReference', 'links': {}, 'detail': None, 'actions': {}, 'fieldName': u'serviceId', 'message': None, 'type': u'error', 'id': u'c86e5009-982e-41f5-83e3-ff9f8bc2f93d'}")
```

This is because of the serviceId in portRange being stored id not obfuscated.
serviceId appears as "1479" in portRules.

```
port rules:[{'sourcePort': 9011, 'protocol': u'http', 'serviceId': 1479, 'targetPort': 80}, {'sourcePort': '9011', 'protocol': 'http', 'serviceId': u'1s1481', 'targetPort': '80'}]
```

**Comment by alena1108** [comment]
Closing in favor of https://github.com/rancher/rancher/issues/5690
