### ISSUE TITLE
HOWTO rancher-agent on osx with latest docker-osx *hack*

### ISSUE THREAD

**Issue by pvdyck** [rancher/rancher#5692]
If you try to install Rancher-agent on your osx hosted docker it will not work because the container tries to access the configuration script on your local machine by using "localhost". 

To solve, use this hack (replace <IP> by your osx IP & xxxxxxxxxxxxx by the cut&paste from Rancher UI):

sudo docker run -e CATTLE_AGENT_IP="<IP>" --add-host=localhost:<IP>  --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.0.2 http://localhost:8080/v1/scripts/xxxxxxxxxxxxxxxxx

Don't hesitate to solve this or improve the hack ;-)

P.

**Comment by dsantmajor** [comment]
If anyone is still facing issues adding a Rancher Agent to the MacOsX (10.12.6 Siera) 
I was seeing the below error message " level=fatal msg="mkdir /var/lib/rancher/volumes: permission denied"
The below worked for me.
# sudo mkdir -p /private/var/lib/rancher/volumes
# sudo docker run --rm --privileged -e CATTLE_AGENT_IP=<IP of your Rancher Server> -v /var/run/docker.sock:/var/run/docker.sock -v /private/var/lib/rancher:/var/lib/rancher rancher/agent:v1.2.7 http://<IP of your Racher Server>/v1/scripts/<key from UI>:<Key from UI>

Key take aways
1. In the Docker--> Preferences-->FileSharing-->
   Add (+) /private/var/lib/rancher 
2. Apply the changes that will restart the docker daemon 
3. Run the above two commands 
    a) # sudo mkdir -p /private/var/lib/rancher/volumes
    b) # when running the command from the Rancher Add Host UI ,modify it with 
           -e CATTLE_AGENT_IP=<IP of your Rancher Server>
                          and instead of -v /var/lib/rancher make use of /private
           -v /private/var/lib/rancher:/var/lib/rancher
