### ISSUE TITLE
High CPU usage by 'monit' at the same time everyday

### ISSUE THREAD

**Issue by samattridge** [rancher/rancher#5693]
Rancher Version: 1.0.2

Docker Version: 1.11.2

OS and where are the hosts located? Ubuntu 14.04 LTS in cloud (Azure)

Setup Details: Single node rancher, internal DB

Environment Type: Cattle

Each morning at 7am BST we see high CPU on two of our VMs for exactly 30 minutes caused by the process '/usr/bin/monit' which appears to be internal to the Rancher HA Proxy based Load Balancers.  Following this 30 minute period, everything goes back to normal but during this time we see poor performance on the servers.

We would like to understand why this happens and how it can be fixed.  

![twtwtwtwtw](https://cloud.githubusercontent.com/assets/15816609/17585443/b1710e4c-5fb3-11e6-858b-2c32a3459502.png)

Many thanks in advance.

Sam

**Comment by aemneina** [comment]
I believe this is due to log rotate running... there seems to be a fix in rancher v.1.2.0-pre1. See here for the original: https://github.com/rancher/rancher/issues/5036

Care to verify this?

**Comment by samattridge** [comment]
Looks like exactly the issue we're seeing.  Thanks for the link.  Great to see it's in-hand.

Thanks.
Sam
