### ISSUE TITLE
In environment details, show that VM is enabled/disabled

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#5700]
**Rancher Version:** master 8/11

**Steps to Reproduce:**
1.  Create and environment with Virtual Machine Support enabled
2.  Go to details page

**Results:** There is nothing to show you enabled this support

**Expected:**  maybe show it's on in details page

**Comment by vincent99** [comment]
n/a in 1.2, and VMs will eventually be an infra stack you'll be able to see.
