### ISSUE TITLE
Adding service to system stack, causes service to temporarily go to User stack page

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#5702]
**Rancher Version:** Master 8/11

**Steps to Reproduce:**
1.  Go to System stack page
2.  Create a stack
3.  Add a Service to that stack
4.  Click on Stacks menu (notice it's pointing to User instead of System now)
4.  Click on Stack link in service detail page

**Results:** Going to User Stack page

**Expected:**  This should always stay in the System Stack

**Comment by amsdard** [comment]
I have the same problem.

**Comment by vincent99** [comment]
Not applicable in 1.2

**Comment by tfiduccia** [comment]
Version - master 11/10
Verified it will no longer matter.  All system stacks and such will go to user.  removing system option.
