### ISSUE TITLE
Not able to deploy zookeeper catalog in cattle  environment.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#5705]
Rancher Version:v1.2.0-pre2-rc2

Steps to reproduce the problem:
Deploy zookeeper template from catalog.
Service is stuck in "activating" state forever with following error - "Activating (yaml: unmarshal errors: line 68: cannot unmarshal !!str `3` into int) "

**Comment by deniseschannon** [comment]
Verified ability to deploy in v1.2.0-pre2-rc3.
