### ISSUE TITLE
Cannot add anything on kubernetes stack

### ISSUE THREAD

**Issue by danielschlegel** [rancher/rancher#5706]
I've added kubernetes env and tried to add a replication controller. It does not depend if i choose a catalog item or if i want to add something manually. The only thin i get is this error in the interface:

Unexpected token u in JSON at position 0

Rancher is running inside a VM with CentOS 7
Rancher is on different host than agent
Both hosts are inside a private network with vpn only connection from the outside
Both hosts can talk to each other
---

| Useful | Info |
| :-- | :-- |
| Versions | Rancher `v1.1.1` Cattle: `v0.165.7` UI: `v1.1.12` |
| Access | `Disabled` |
| Orchestration | `Kubernetes` |
| Route | `catalog-tab.launch` |

**Comment by danielschlegel** [comment]
with kubectl get pods is see that there are no nodes but kubernetes is up and running if i take a look at the UI of rancher all is green.

**Comment by deniseschannon** [comment]
so the kubernetes system stack is all green?

how many hosts are in your k8s env?

and can you share the image name of your `kubernetes` service in the system stack?

**Comment by danielschlegel** [comment]
Yes the kubernetes system stack is all green.
I have two hosts at the moment but it also happens with one.
The kubernetes service has the image: rancher/k8s:v1.2.4-rancher9

Here are some screenshots. 
http://screencast.com/t/I8NF0WrAsu
http://screencast.com/t/Sx6izhVz0c
http://screencast.com/t/EIuWRbhj

Im very into rancher and really want to keep it but i need to have a production ready setup soon. so im very thankful for any help because otherwise i need to switch to different solution.

**Comment by danielschlegel** [comment]
I was able to solve the problem with some firewall rules to accept outgoing traffic to port 8091. In Documentation i did not found this port so it would be good to add this...
From my side you can close this issue.
