### ISSUE TITLE
Rancher CLI beta links don't work

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#5707]
**Rancher Version:** v1.2.0-pre2-rc2

**Steps to Reproduce:**
1.  Click on the Download CLI link on the bottom right
2.  Select andy of the Rancher CLI (bets) links

**Results:** Nothing happens

**Expected:** Should get the download

**Comment by deniseschannon** [comment]
When we make the first official release for the version, we'll add the version to releases.rancher.com so that it can be downloaded (like how rancher-compose is handled)

**Comment by vincent99** [comment]
The files are there, but the URLs are wrong in settings (`compose` vs `cli`)

**Comment by tfiduccia** [comment]
Verison - v1.2.0-pre2-rc7
Verified fixed
