### ISSUE TITLE
Digital Ocean machine creation fails when image is not passed.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#5710]
Rancher-server version - v1.2.0-pre2-rc2
Steps to reproduce the problem:
Try to create a Digitial Ocean machine without passing image (validation test scripts) , image gets defaulted  to ubuntu-15-10-x64  which results in machine creation to fail since DO does not have a "ubuntu-15-10-x64" as supported image anymore.

```
time="2016-08-02T19:05:35Z" level=info msg="Cmd slice: [create -d digitalocean --engine-install-url https://releases.rancher.com/install-docker/1.10.sh --digitalocean-access-token ********************** --digitalocean-image ubuntu-15-10-x64 --digitalocean-region nyc3 --digitalocean-size 512mb --digitalocean-ssh-port 22 --digitalocean-ssh-user root test-702194]

time="2016-08-02T19:05:43Z" level=error msg="Error processing event" err="Error in driver during machine creation: POST https://api.digitalocean.com/v2/droplets: 422 You specified an invalid image for Droplet creation." eventId=13220454-f4cc-4ad0-8105-b5f92caed4ad eventName="physicalhost.create;handler=goMachineService" resourceId=1ph2
```

We still use DM 0.6 which has "ubuntu-15-10-x64" as default image. 
DM 0.8  has the default changed to "ubuntu-16-04-x64".

**Comment by wlan0** [comment]
With DM 0.8 added, this should be fixed.

**Comment by sangeethah** [comment]
Tested with latest Rancher server build from master .
Able to create digital Ocean machine  by passing only access key and not passing  image.
Machine gets deployed with  image - Ubuntu 16.04.1 x64.
