### ISSUE TITLE
Load balancers not appearing on Hosts in Infrastructure

### ISSUE THREAD

**Issue by ebr** [rancher/rancher#5711]
**Rancher Version:**
1.1.2

**Docker Version:**
1.12.0

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 14.04 / AWS 

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node, external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
1. Create a stack with a service and a load balancer
2. Globally schedule both the load balancer and service

**Results:** 
- In the Infrastructure tab, examine the Hosts. The Load Balancer is not appearing in the Stack.
- the number of load balancer containers is still correct, if getting the "info" on the LB service from the Stacks page.
- confirmed by SSHing into the host that the LB is in fact running on that host

**Expected:**
- Load Balancers should appear on their respective hosts on the Infrastructure page.

Another observation to add: if the service of the stack is NOT globally scheduled (but the LB is), then the hosts that don't have any containers for the service running, don't even have this Stack displayed on them either. The hosts that DO have the service running, show the Stack, the container for the service, but not the LB.

Not sure if this is related to #5332

**Comment by ebr** [comment]
OMG. nevermind...

![rancher](https://cloud.githubusercontent.com/assets/2433541/17635361/dc5ea014-60a4-11e6-8ade-2527cce030f6.png)

I ❤️  you guys, but sometimes the UI changes you introduce are frustratingly non-obvious. :)

**Comment by tfiduccia** [comment]
Glad you found it. :-)
