### ISSUE TITLE
Is there any OVF template for VMWare to build VM

### ISSUE THREAD

**Issue by mohanrao** [rancher/rancher#5712]
**Rancher Version:**
0.5.0

**OS and where are the hosts located? (cloud, bare metal, etc):**
VMWare

**Steps to Reproduce:**
When I create a virtual machine in vmware with OS as other linux 64 bit and boot from the Rancher OS ISO, after the reboot if remove the ISO from vmware(vSphere) then the Virtual machine is not getting rebooted then it can not find the boot device to boot from

Without doing the above step Also if I change the dns and network interface changes as per the documentation http://docs.rancher.com/os/configuration/networking/ and after reboot all changes are lost i cannot do the dns lookup and i don't see the network interface in the ifconfig and even the changes also lost 

**Results:** 

**Expected:**
Provide a way how to create a Rancher OS virtual machine in Vmware

**Comment by aemneina** [comment]
there are a couple suggestions, one is to install rancher to disk. seconnd is to create a volume with a name label RANCHER_STATE. Both these methods will persist the configuration. Not sure why vsphere is ejecting the iso on reboots (probably expected), that would have to be re-mounted if you are not installing rancher to disk.

**Comment by mohanrao** [comment]
@aemneina  is there any documentation for vmware with vSphere?

**Comment by aemneina** [comment]
I think the question is geared towards documentation of rancherOS running specifically on vmware/vsphere... which doesn't exist. Where you run ROS shouldn't matter too much, it's similar to running other linux hosts in a cloudy environment.

**Comment by aemneina** [comment]
closing this out.
