### ISSUE TITLE
'rancher docker' does not work when options are specified

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#5716]
**Rancher Version:** v1.2.0-pre2-rc2

Rancher CLI version: v0.0.2

**Docker Version:**1.12.0

**OS and where are the hosts located? (cloud, bare metal, etc):**Ubuntu, Cloud

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**: Cattle

**Steps to Reproduce:**
1. Create a rancher-cli set up.
2. Run the command:
./rancher --host host1 docker run --name mytest nginx
```
soumyas-MacBook-Pro:rancher-v0.0.2 soumya$ ./rancher --host host1 docker run --name mytest nginx
Incorrect Usage.

Run docker CLI on a host

Uses the $RANCHER_DOCKER_HOST to run docker commands. Use `--host <hostID>` or `--host <hostName>` to select a different host.

Example:
  $ rancher --host 1h1 docker ps

Usage: rancher [global options] docker [arg...]


FATA[0000] flag provided but not defined: -name      

```
Another example
```
 ./rancher --host host1 docker run --name mytest -it nginx
```

**Comment by deniseschannon** [comment]
This is not `rancher docker run` specific but in general any docker CLI command that uses options is not parsing the options correctly.

**Comment by soumyalj** [comment]
Tested with rancher-v0.1.0-rc1. Options are functional.
