### ISSUE TITLE
rancher env create/update need better error messages when using an environment API key

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#5718]
Rancher Version: v1.2.0-pre2-rc2

Rancher CLI version: v0.0.2

Docker Version:1.12.0

OS and where are the hosts located? (cloud, bare metal, etc):Ubuntu, Cloud

Environment Type: (Cattle/Kubernetes/Swarm/Mesos): Cattle

Steps to Reproduce:
1. Create a rancher-cli set up.
2. Run the commands:

```
soumyas-MacBook-Pro:rancher-v0.0.2 soumya$ ./rancher env create cattleenv1
FATA[0000] Resource type [project] is not creatable    

soumyas-MacBook-Pro:rancher-v0.0.2 soumya$ ./rancher env create -o kubernetes testk8
FATA[0000] Resource type [project] is not creatable   

```

```
soumyas-MacBook-Pro:rancher-v0.0.2 soumya$ ./rancher env update -o cattle 1a5
FATA[0000] Resource type [project] is not updatable    
```

**Comment by deniseschannon** [comment]
I am unable to reproduce using v0.0.2. 
```
$ rancher env create test2
test2 (1a14)
```

**Comment by deniseschannon** [comment]
@soumyalj Using an environment API key, you cannot create other environments or change environment types. 

There should be a better error when trying to create/update environments when you don't have access.

**Comment by deniseschannon** [comment]
The help has been updated to clarify that account API keys are needed, but the error message should be improved.

**Comment by soumyalj** [comment]
Tried with v0.1.0-rc2 using environment api keys. The error messages are still the same. 

soumyas-MacBook-Pro:rancher-v0.1.0-rc2 soumya$ ./rancher env create cattle2
FATA[0000] Resource type [project] is not creatable
