### ISSUE TITLE
./rancher env ls does not list all environments in the setup

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#5719]
Rancher Version: v1.2.0-pre2-rc2

Rancher CLI version: v0.0.2

Docker Version:1.12.0

OS and where are the hosts located? (cloud, bare metal, etc):Ubuntu, Cloud

Environment Type: (Cattle/Kubernetes/Swarm/Mesos): Cattle

Steps to Reproduce:
1. Create a rancher-cli set up. Create 2 environments in your rancher setup
2. Run the command:
```
soumyas-MacBook-Pro:rancher-v0.0.2 soumya$ ./rancher env ls 
ID        NAME      ORCHESTRATION   STATE     CREATED
1a5       Default   Kubernetes      active    2016-08-12T03:55:01Z
```
Only default environment is listed.

**Comment by deniseschannon** [comment]
I am unable to reproduce using v0.0.2.

```
$ rancher env ls
ID        NAME      ORCHESTRATION   STATE     CREATED
1a5       Default   Cattle          active    2016-08-12T05:39:20Z
1a13      test      Cattle          active    2016-08-12T23:55:11Z
1a14      test2     Cattle          active    2016-08-12T23:56:07Z
```

**Comment by deniseschannon** [comment]
@soumyalj It looks like you were using an environment API key, which would only list the environment you are in and not have access to other environments.

In the docs (still being written), it is documented that you should be using account API keys.
