### ISSUE TITLE
Mobile UI issue (container details & other pages)

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#5722]
**Rancher Version:** v1.2.0-pre2-rc2

**Results:**

**Container Details**
- [x] Do you want tabs to have two rows? If so, shouldn't the selected tab be on the bottom and connected to it's details?
![image](https://cloud.githubusercontent.com/assets/11514927/17639787/af52f11e-60aa-11e6-9662-0e710548b984.png)

- [x] Empty port text is on bottom of box
![image](https://cloud.githubusercontent.com/assets/11514927/17639779/8e77cd84-60aa-11e6-9ee7-7ba2098d43b0.png)

- [x] Command tab, Environment variables section has lots of white space and the variarable is not associated to the value
![image](https://cloud.githubusercontent.com/assets/11514927/17639969/3677e1ac-60ad-11e6-9adc-7945a1ad5ce5.png)

- [x] Volumes if empty, show Error: text and the "This container has no volumes text is on bottom".
![image](https://cloud.githubusercontent.com/assets/11514927/17640071/6f6bb488-60ae-11e6-9fe5-ba5cd8926d83.png)

- [x] Networking Resolving Servers has a bunch of white space on bottom
![image](https://cloud.githubusercontent.com/assets/11514927/17639808/f5be3b36-60aa-11e6-8f62-8d7e3a278a19.png)

- [x] Networking Search Domains are separated by white space.
![image](https://cloud.githubusercontent.com/assets/11514927/17639804/dfee94e0-60aa-11e6-831d-0ba8c26a1c7c.png)

- [x] Security - Privileged, PID Mode, Memory Limit, +Swap Limit, CPU PInning and Shares are separate things and should not be together?
![image](https://cloud.githubusercontent.com/assets/11514927/17639825/3e32d49e-60ab-11e6-9391-4a318cb7a405.png)

**Host Details**
- [x] OS section has no white space between it and the CPU graph
![image](https://cloud.githubusercontent.com/assets/11514927/17640230/7dcd3a90-60b0-11e6-904b-517df15b9e25.png)

**Setting**

- [x] Text wraps in middle of words
![image](https://cloud.githubusercontent.com/assets/11514927/17640004/b45b6fd0-60ad-11e6-8d41-386dec6f91e7.png)

- [x] Catalog section, the Enable/Disabled for Rancher Certified vs Community Contributed are not aligned properly
![image](https://cloud.githubusercontent.com/assets/11514927/17640017/d22a3208-60ad-11e6-870f-137ee60641b2.png)

**Catalog**

- [x] The search field and the search icon are not in the correct place?
![image](https://cloud.githubusercontent.com/assets/11514927/17640144/595c9f26-60af-11e6-8066-1d3153636781.png)

**Comment by vincent99** [comment]
@tfiduccia FYI the fix for "text wraps in the middle of words" is going to have been added for a header somewhere else where there's a long word with no breakable characters and it wasn't wrapping, which will now be broken again... so find that and we'll look at that separate.

**Comment by tfiduccia** [comment]
Version - v1.2.0-pre2-rc5
