### ISSUE TITLE
[cli] - ERRO[0000] websocket: bad handshake

### ISSUE THREAD

**Issue by SydOps** [rancher/rancher#5725]
**Rancher Version:**

rancher/server:stable
rancher/agent:v1.0.2
rancher/cli:v0.0.2

**Docker Version:**

Server Version: 1.12.0

**OS and where are the hosts located? (cloud, bare metal, etc):**

MacOS 10.11.5 (15F34)

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

single node rancher 
internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

Cattle

**Steps to Reproduce:**

1) Successfully start rancher/server container, and add one host to rancher server.

2) config rancher cli

```
rancher --url https://172.19.8.100:8080 config
# assigned "Account API Keys"  (not environment API keys)
$ cat ~/.rancher/cli.json
{"accessKey":"xxxx","secretKey":"xxxx","url":"http://172.19.8.100:8080/v1/schemas","environment":"1a5"}
```

3) run fine with below command: 

```
rancher --host 1h1 docker ps
rancher env
```

4)  not successful with below commands

```
$ rancher events -r
ERRO[0000] websocket: bad handshake
ERRO[0001] websocket: bad handshake
ERRO[0002] websocket: bad handshake

$ rancher catalog
FATA[0000] Bad response statusCode [401]. Status [401 Unauthorized]. Body: [code=Unauthorized, message=Unauthorized] from [http://172.19.8.100:8080/v1-catalog/schemas]
```

**Results:** 

```
$ rancher --debug events -r
ERRO[0000] websocket: bad handshake
ERRO[0001] websocket: bad handshake
ERRO[0002] websocket: bad handshake
```

**Expected:**

ranche cli should report the events

**Comment by deniseschannon** [comment]
Can you try with v0.1.0 and let me know if you still have issues? 

Can you run `rancher config` again?

**Comment by ddelnano** [comment]
I tried with v0.1.0 and received the same output. I can't post my versions of everything else right now but I will the next chance I am at my computer.

**Comment by aemneina** [comment]
@ddelnano please reopen if you can provide logs and versions on a modern version of rancher.
