### ISSUE TITLE
When hundreds of services created in one environment, services start very slow

### ISSUE THREAD

**Issue by niusmallnan** [rancher/rancher#5733]
**Environment Type: Cattle**

**Steps to Reproduce:**
Create hundreds of services, maybe 300

**Results:** 
At the beginning, the service starts soon(1~2s)
With the increase in the number of services, the time to start a new service has become very long(7-9s)

I guess it could be due to the following reasons.
Metadata file and DNS file size increases because hundreds of services.Metadata file size is 2M in each host:

```
$ ll -hl /var/lib/cattle/etc/cattle/metadata/answers.yml
-rw-r--r-- 1 root root 2.0M Aug 15 07:09 /var/lib/cattle/etc/cattle/metadata/answers.yml
```

These files downloaded from rancher-server(cattle):

```
$ cat /var/lib/cattle/download/hosts/current
hosts-145365-257aff5cc23042701e4b6e49146ac4f33de95ee93d14f3484f87f4e23b378943

$ cd /var/lib/cattle/download/hosts/hosts-145365-257aff5cc23042701e4b6e49146ac4f33de95ee93d14f3484f87f4e23b378943/ && ls
SHA1SUMS  SHA1SUMSSUM  apply.sh  content-home  version

$ cd content-home/etc/cattle/metadata/ && ls
answers.yml
```

Any state of the service changes will trigger event, then metadata file or DNS file will refresh(download again) in each host.File on each host is different,this means that cattle will generate many times for one event.Therefore, the more the number of services the slower start-up time.

**Questions:**
My analysis is correct?
What is the solution it?

**Comment by veered** [comment]
I am experiencing this issue as well. For us, it greatly decreases the usability of Rancher.

**Comment by will-chan** [comment]
We are making improvements in performance as part of 1.2 but will keep this bug around because DNS and MD population is still one we have not gotten to.

**Comment by deniseschannon** [comment]
@niusmallnan Can you re-test with 1.5 as we have made some improvements with metadata?

**Comment by aemneina** [comment]
Can we include adding hosts to the considerations here. Use case being bring up a large batch of hosts to deal with an increase demand (i.e. grow an autoscale group).
