### ISSUE TITLE
Need more verbosity when launching containers with errors

### ISSUE THREAD

**Issue by schuylr** [rancher/rancher#5734]
**Rancher Version:** 1.1.1

**Docker Version:** 1.11.2

**OS and where are the hosts located? (cloud, bare metal, etc):** AWS, RancherOS 0.4.5

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** External DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:**

Try to start a container through Rancher on a host or service. Do something intentionally incorrect, like try to run `alpine` without a command.

**Results:** 

You get either a container stuck on "Starting (Starting)" indefinitely, or you get to see that the container has "Stopped" without any insight in the logs. Rancher server logs have errors like this:

```
2016-08-16 14:23:15,368 ERROR [:] [] [] [] [orService-11144] [i.c.p.e.e.i.ProcessEventListenerImpl] Unknown exception running process [instance.start:133645] on [1636] io.cattle.platform.eventing.exception.EventExecutionException: 500 Server Error: Internal Server Error ("No command specified")
```

**Expected:**

If I were to try this locally I get much better insight

```
[rancher@ip-10-0-6-47 ~]$ docker run alpine
docker: Error response from daemon: No command specified.
See 'docker run --help'.
```

Can we start relaying these types of errors to the Rancher UI instead of burying them in the Rancher Server logs?

**Comment by deniseschannon** [comment]
The same error message exists at the container level. As we try to start up containers, the container will error out and stick around for a bit before being removed and restarted. 

![screen shot 2016-08-17 at 11 42 28 am](https://cloud.githubusercontent.com/assets/11410997/17748748/b087780c-646f-11e6-86b4-3f5b5381ba14.png)

**Comment by schuylr** [comment]
Weird, I never saw that no matter how long I waited! It was just stuck on "Restarting" while the Rancher server logs did show that. Maybe there's something broken in between?

**Comment by deniseschannon** [comment]
Are you looking at the contianer or service?

**Comment by schuylr** [comment]
Container. If I see the problem again I'll grab some more logs from both the UI and server and try to get some better insight for you.
