### ISSUE TITLE
Is there any scheduler option in rancher app catalog so one can select particular host to deploy app? 

### ISSUE THREAD

**Issue by hachiko21** [rancher/rancher#5741]
**Rancher Version:*1.1.0*

**Docker Version:*1.2*

**OS and where are the hosts located? (cloud, bare metal, etc):**

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**

**Results:** 

**Expected:**

**Comment by tfiduccia** [comment]
@hachiko21 Currently there is not a way to do this.  there is an issue already entered.  Duplicate #2852
