### ISSUE TITLE
Misspelling

### ISSUE THREAD

**Issue by steevegldev** [rancher/rancher#5744]
**Rancher Version:** 1.1.2

**Environment Type:** Swarm

**Steps to Reproduce:** In SWARM > Projects > Click Add project

**Results:** Can read "dcoker-compoe.yml"

**Expected:** Read "docker-composer.yml"

![image](https://cloud.githubusercontent.com/assets/6455947/17719423/63a80420-63e8-11e6-862d-8db0967d0e3b.png)

**Comment by tfiduccia** [comment]
@steevegldev This has already been fixed for the next release
