### ISSUE TITLE
using Rancher, HostConfig.Link is always empty.

### ISSUE THREAD

**Issue by DxCx** [rancher/rancher#5752]
Hi,

First of all, i'm a new Rancher user, and i must say, you guys did an amazing work! :+1: 
now, i've migrated my stack to use rancher,
in my stack i have a cronjob that is running periodically, and running docker inspect
on the containers to determinate dependencies.
however, since start using rancher, the HostConfig.Links is always empty (null)

**Rancher Version:** 1.1.2

**Docker Version:** 1.12

**OS and where are the hosts located? (cloud, bare metal, etc):** coreOs @ DO

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
3 hosts, running total of 11 containers.

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:**
1. Run a stack with links
db:
  image: 'mongo:latest'

db-2:
  image: 'mongo:latest'
  links:
    - "db:db"

db-3:
  image: 'mongo:latest'
  links:
    - "db-2:db"
2. Inspect each one of them.

**Results:** 
HostConfig.Link is null for all containers.

**Expected:**
db: HostConfig.Link should be null.
db-2: HostConfig.Link should have an array with [db] in it.
db-3: HostConfig.Link should have an array with [db-2] in it.

**Comment by aemneina** [comment]
@DxCx we emulate links in rancher, we dont use docker links. I believe those are deprecated, so docker plans on dropping them as well.
