### ISSUE TITLE
rancher-ha: Unable to remove filesystem for <container>: remove /var/lib/docker/containers/<id>/shm: device or resource busy" component=service

### ISSUE THREAD

**Issue by amachowi** [rancher/rancher#5753]
**Rancher Version:**
rancher-ha 1.1.2, new setup

**Docker Version:**
1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
RHEL7 as VM. I can also reproduce this problem with a VM running within Vagrant/Virtualbox

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Docker daemon options, especially devicemapper setup with thinprovisioning:

/usr/bin/docker daemon --selinux-enabled -H tcp://0.0.0.0:4243 -H unix:///var/run/docker.sock -G dockerroot --bridge=docker1 --storage-driver devicemapper --storage-opt dm.fs=xfs --storage-opt dm.thinpooldev=/dev/mapper/VG02-docker--pool --storage-opt dm.use_deferred_removal=true

Setup rancher-ha as described in docs. 

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
setup docker as described above on rhel7 or centos7 vm with thinprovisioning.
Let rancher-agent run into timeout by starting additional cluster members deferedly.

**Results:** 
time="2016-08-17T10:02:44Z" level=fatal msg="Failed while waiting for 3 host(s) to be active: Timeout waiting for hosts to be active" component=service
time="2016-08-17T10:02:45Z" level=info msg="Cluster changed, index=0, members=[172.26.175.11, 172.26.175.12, 172.26.175.13]" component=service
time="2016-08-17T10:02:45Z" level=info msg="Container agent is not running in state &types.ContainerState{Status:\"exited\", Running:false, Paused:false, Restarting:false, OOMKilled:false, Dead:false, Pid:0, ExitCode:0, Error:\"\", StartedAt:\"2016-08-17T10:01:41.473084764Z\", FinishedAt:\"2016-08-17T10:01:56.76359739Z\"}" component=docker
time="2016-08-17T10:02:45Z" level=info msg="Deleting container aca1d280b2f7080860af5d89994c515e76010035af2dcf78a2c184802e8ee576" component=docker
time="2016-08-17T10:02:45Z" level=info msg="Creating container rancher-ha-agent" component=docker
time="2016-08-17T10:02:56Z" level=info msg="Forgetting cluster member" component=manager member={8  37e3d806-bfa8-4f35-98d4-9fee3524dd84 172.26.175.11 map[] 0 38 1}
time="2016-08-17T10:02:57Z" level=info msg="Cluster changed, index=1, members=[172.26.175.11, 172.26.175.12, 172.26.175.13]" component=service
time="2016-08-17T10:02:57Z" level=info msg="Container agent is not running in state &types.ContainerState{Status:\"exited\", Running:false, Paused:false, Restarting:false, OOMKilled:false, Dead:false, Pid:0, ExitCode:0, Error:\"\", StartedAt:\"2016-08-17T10:02:46.560187095Z\", FinishedAt:\"2016-08-17T10:02:55.904054161Z\"}" component=docker
time="2016-08-17T10:02:57Z" level=info msg="Deleting container 4886d2e989c354683dab36971faddc2b96e1afc599a31957a2e2605313b0bf03" component=docker
time="2016-08-17T10:02:57Z" level=info msg="Can not launch agent right now: Error response from daemon: Unable to remove filesystem for 4886d2e989c354683dab36971faddc2b96e1afc599a31957a2e2605313b0bf03: remove /var/lib/docker/containers/4886d2e989c354683dab36971faddc2b96e1afc599a31957a2e2605313b0bf03/shm: device or resource busy" component=service

**Expected:**
I would not expect any error when agent gets restarted internally

**Comment by aemneina** [comment]
I believe the fact this is logged doesnt constitute an issue that prevents rancher from running. Closing this out.
