### ISSUE TITLE
Not able to deploy catalog because of yaml: unmarshal errors.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#5755]
Server version - v1.2.0-pre2-rc4

Tried to deploy  Route53 template-rancher/external-dns:v0.5.0 hosted in catalog https://github.com/janeczku/my-rancher-catalog.git

catalog fails to deploy with following errors:
```Activating (yaml: unmarshal errors: line 54: cannot unmarshal !!str `15000` into int64)```

**Comment by galal-hussein** [comment]
Etcd catalog template has the same problem:
```
error: yaml: unmarshal errors: line 37: cannot unmarshal !!str `3` into int64
```

**Comment by joshwget** [comment]
@galal-hussein rancher/rancher-compose#188 should fix that problem as well

**Comment by galal-hussein** [comment]
bind9 catalog item also has the same error.

**Comment by sangeethah** [comment]
Tested with rancher-server version - v1.2.0-pre2-rc5

Able to deploy route53 template-rancher/external-dns:v0.5.0 hosted in catalog https://github.com/janeczku/my-rancher-catalog.git successfully. Also able  deploy Etcd catalog template successfully.
No yaml unmarshal errors encountered when deploying bind9 catalog item.
