### ISSUE TITLE
http.port override for ingress is not reflected in ports field for ingress returned using kubectl get ingress command.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#5757]
Rancher server version - v1.2.0-pre2-rc4

Steps to reproduce the problem:
Create k8s environment.
Upgrade to k8s 1.3 version.
Create ingress rule by providing http.port override for ingress .
This is not reflected in ports field for ingress returned using kubectl get ingress command.

<img width="1007" alt="screen shot 2016-08-17 at 2 31 24 pm" src="https://cloud.githubusercontent.com/assets/4266958/17754068/ad6ae7cc-6487-11e6-82b1-be18d10aec8e.png">
<img width="974" alt="screen shot 2016-08-17 at 2 39 41 pm" src="https://cloud.githubusercontent.com/assets/4266958/17754252/790c0802-6488-11e6-88e3-9e89fce4b030.png">

**Comment by sangeethah** [comment]
This issue is also seen in v1.2

**Comment by alena1108** [comment]
Changing the target to 1.2. If I remember correctly, port was introduced to ingress only in k8s 1.3.

**Comment by sangeethah** [comment]
This is also an issue with k8s v1.2 in which we support http.override.

**Comment by alena1108** [comment]
1.2 doesn't display the ingress port on ingress list/describe, and it wasn't allowed to set it using 1.2 Apis:

```
kubectl get ingress
NAME      RULE      BACKEND            ADDRESS   AGE
test      -         nginx-service:80             1s
```

```
> kubectl describe ingress test
Name:                   test
Namespace:              default
Address:                127.0.0.1
Default backend:        nginx-service:80 (10.42.48.203:80)
Rules:
  Host  Path    Backends
  ----  ----    --------
Annotations:
Events:
  FirstSeen     LastSeen        Count   From                            SubobjectPath   Type            Reason  Message
  ---------     --------        -----   ----                            -------------   --------        ------  -------
  1m            1m              1       {loadbalancer-controller }                      Normal          CREATE  default/
test
  42s           42s             1       {loadbalancer-controller }                      Normal          CREATE  ip: 127.
0.0.1
  42s           42s             1       {loadbalancer-controller }                      Normal          UPDATE  default/
test

```

Will have to investigate to see if k8s lets you set it for 1.3. Moving the release target back to Rancher 1.2

**Comment by alena1108** [comment]
@sangeethah @deniseschannon ^^

**Comment by alena1108** [comment]
@sangeethah this port field is not enabled on the Kubernetes Ingress API. It is kubectl client populating it based on the certificate presence in ingress resource: 

https://github.com/kubernetes/kubernetes/blob/5eb75e4eb9d8a045e4d9cfbd1ff7bb84ef6d8f36/pkg/kubectl/resource_printer.go#L1180


```
func formatPorts(tls []extensions.IngressTLS) string {
	if len(tls) != 0 {
		return "80, 443"
	}
	return "80"
}
```

Lets keep this bug open for the future in case Kubernetes will allow to set the port on ingress. Today's Rancher's ingress annotation that lets you add the port to LB that is diff from 80/443, is a backdoor, and the information about it should be read from annotations as well.

**Comment by alena1108** [comment]
Closing, will reopen if k8s allows to set port fields to custom values via API
