### ISSUE TITLE
Missing scroll bar in the "API Reqest" page.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#5758]
Rancher server version - v1.2.0-pre2-rc4
User Interface -	v1.2.8

<img width="840" alt="screen shot 2016-08-17 at 4 27 15 pm" src="https://cloud.githubusercontent.com/assets/4266958/17756846/875970ca-6497-11e6-81fb-bef5fff3f5fc.png">

**Comment by tfiduccia** [comment]
Version - master 9/8
Verified fixed
