### ISSUE TITLE
Suggestion : Advanced scaling / scheduling options

### ISSUE THREAD

**Issue by kvaes** [rancher/rancher#5760]
At points I reach a limit where I would like to see more options in regards to scaling.

For example ; 
For several design's, I want to scale in terms of physical resources by adding (virtual/cloud) machines. I've setup my services so that they a container runs on each host. This renders me a template/blueprint per host, of the services that should run on it. Though this has the disadvantage that I can only run 1 container per service per host. I've often pondered if having the option to select # containers per host wouldn't solve that for me.

Another approach would be to enhance the scheduling rules and allow mathematic formula's. Where one could say to run a minimum & maximum amount of containers of X services. The drawback would be that you would have to have an additional setting at the service, where you would say "fill to max" (or something like that), as otherwise the service might always run in degraded mode.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
