### ISSUE TITLE
Rancher DNS does not resolve Docker Container ID

### ISSUE THREAD

**Issue by stephan2012** [rancher/rancher#5761]
**Rancher Version:** 1.1.2

**Docker Version:** 1.12.0

**OS and where are the hosts located? (cloud, bare metal, etc):** CentOS 7 (VM)

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** Single Rancher server (internal DB) with 3 hosts

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:** Start two services (containers) within a stack and set the hostname to the Docker Container ID. Try to resolve the other's container hostname.

**Results:** Rancher DNS cannot resolve Docker container ID as hostname.

**Expected:** Rancher DNS should resolve Docker container ID as hostname to its IP address.

**Comment by aemneina** [comment]
containers are meant to be immutable, so this usecase seems very niche. Your containers should be able to resolve each other by service-name as a hostname.
