### ISSUE TITLE
Rancher-UI new-select default value null

### ISSUE THREAD

**Issue by radu-stefanache** [rancher/rancher#5762]
**Rancher Version:**
1.1.2
**Docker Version:**
1.12
**OS and where are the hosts located? (cloud, bare metal, etc):**
CentOS 7, Cloudstack/VMWare
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
Create a custom ui-driver based on https://github.com/rancher/ui-driver-skel and configure drop-down using [new-select](https://github.com/rancher/ui/blob/master/app/components/new-select/component.js).
`{{new-select classNames="form-control" content=var optionLabelPath='name' optionValuePath='id' value=model.%%DRIVERNAME%%Config.variable }}`
**Results:** 
If the desired value appears in the drop-down as the first option and you don't have to click and change it (onChange) the value will be set to `null` https://github.com/rancher/ui/blob/master/app/components/new-select/component.js#L96
**Expected:**
If the desired value appears in the drop-down as the first option it should be used without having to trigger a change event.

The workaround so far is to define a prompt that would trigger a change event.

**Comment by vincent99** [comment]
@loganhz Can you verify if this is still the case (you can use something built-in, it has nothing to really do with machine drivers and custom UI), and if it is it should be easy to fix.

**Comment by loganhz** [comment]
@vincent99 
yes, it's still the case in master.
created a PR to fix it.
Not sure if my fix is a good solution. But it did work.
If the default value doesn't match any option, it will use the first option.
If the default value matches some option, it will use the desired option.
