### ISSUE TITLE
Intermediate "Timeout: running state" status  when service with sidekicks are being activated.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#5763]
Rancher Version: v1.2.0-pre2-rc5

Intermediate "Timeout: running state" status  when service with sidekicks are being activated. This was seen when K8s system stack was starting.

audit logs for event - reconcile.service for k8s services:

<img width="1608" alt="screen shot 2016-08-18 at 9 59 59 am" src="https://cloud.githubusercontent.com/assets/4266958/17782940/9ebc58d4-652a-11e6-9e55-e6636497de8d.png">

**Comment by andrewmclagan** [comment]
+ 20

**Comment by andrewmclagan** [comment]
me also

**Comment by alena1108** [comment]
@sangeethah this bug is no longer relevant as we don't have audit logs for service.reconcile; we have service logs instead. Please reopen against the service logs if you see this behavior again.

**Comment by sangeethah** [comment]
Tested with latest build from master:

I still see the following intermediate messages show up when starting services with sidekicks - ```Activating (Timeout: container starting [container:1i399])```. Audit log does not show this error for reconcile.service anymore.

**Comment by alena1108** [comment]
@sangeethah could you please retest it on the latest. There were some changes made around wait for sidekicks area.

**Comment by galal-hussein** [comment]
Tested and verified on Rancher v1.2.0, the error doesn't appear anymore.
