### ISSUE TITLE
rancher cli commands not functional as member of an environment

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#5769]
Rancher Version:v1.2.0-pre2-rc5

Docker Version:1.12.1, 1.10.3

Rancher CLI version: v0.1.0-rc2 

OS and where are the hosts located? (cloud, bare metal, etc):Ubuntu, Cloud

Environment Type: (Cattle/Kubernetes/Swarm/Mesos): Cattle

Steps to Reproduce:
1. Create a rancher-cli set up 
2. Enable github authentication on the ranchersetup.
3. Create a new environment in rancher and provide access to newuser.
4. Use the newuser's account access/secret key on rancher cli and run commands. Error seen as below:
```
soumyas-MacBook-Pro:rancher-v0.1.0-rc2 soumya$ ./rancher hosts
FATA[0000] Bad response statusCode [403]. Status [403 Forbidden]. Body: [message=Forbidden, code=Forbidden] from [http://104.197.18.83:8080/v1/projects/1a16/schemas/schemas] 

rancher env list is empty
soumyas-MacBook-Pro:rancher-v0.1.0-rc2 soumya$ ./rancher env
ID        NAME      ORCHESTRATION   STATE     CREATED

```
Note: Rancher CLI does not work for accounts added as owner of an environment too.

**Comment by deniseschannon** [comment]
Verified with v1.2.0-pre2-rc7 and rancher CLI v0.1.0-rc3. 

As a user and member of environment, I am able to see only my environments.
