### ISSUE TITLE
MachineConfig gets downloaded as .tar file (instead of .tar.gz) in firefox and safari browsers

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#577]
Server version - V0.16.3

Add a Digital Ocean(or Amazon EC2) hosts.
Try to download machine config using "Machine Config" option.

In case of firefox and safari browsers , the downloaded machine config is a *.tar file.

In case of chrome , the downloaded machine config is a *.tar.gz file.

Ideally , we would want the downloaded machine config file to be a *.tar.gz file in case of  firefox and safari browsers as well.

**Comment by vincent99** [comment]
Not the UI...  It also downloads correctly so not what I would really call a bug.  

The API is sending back `Content-Encoding: gzip`, and some browsers choose to automatically decompress it because of that, leaving you with the `.tar`

**Comment by vincent99** [comment]
@will-chan Do you want to fix this?  Tarballs are not particularly friendly to Windows-folk.

**Comment by cjellick** [comment]
This randomly came up today. @vincent99 and @ibuildthecloud expressed their desire again for zips instead of tars

**Comment by vincent99** [comment]
While you're in that area, if it's easy can you add a `README.txt` to the archive that points to the docs for someone who doesn't know what to do with the files they just downloaded.  https://github.com/rancherio/rancher/issues/313#issuecomment-109382696
