### ISSUE TITLE
Deadlock in websocket proxy

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#5770]
**Rancher Version:**
v1.1.2

**Docker Version:**
all

**OS and where are the hosts located? (cloud, bare metal, etc):**
all

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
any

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
k8s

**Steps to Reproduce:**
Extremely hard to reproduce consistently as it is caused by a race condition, but here's a description of the problem: 
- The symptoms are that logs, exec, stats, and all kubectl commands fail or hang indefinitely.
- The cause is a bug in the k8s code path of websocket-proxy that causes complete deadlock.

_Note:_ I was able to reproduce consistently by adding a sleep in the appropriate place in websocket-proxy and was thus able to test our fix.

**Comment by sangeethah** [comment]
Fresh install of rancher-server version - v1.1.2 on a 3 node HA cluster.
Had 3 hosts in  k8s environment .
Deployed few service/RC/pods.

Upgraded to v1.1.3.

After upgrade , host stats, container logs, exec, stats, and  kubectl commands to list/create service/RC/pods works as expected.

System was left idle for 2 days.

After 2 days ,  host stats, container logs, exec, stats, and  kubectl commands to list/create service/RC/pods continue to work as expected
