### ISSUE TITLE
Unable to see container stats (monitoring)

### ISSUE THREAD

**Issue by geeknam** [rancher/rancher#5771]
**Rancher Version:**
1.1.2

**Docker Version:**
1.12.1

**OS and where are the hosts located? (cloud, bare metal, etc):**
bare metal + RHEL7.2

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
- HA rancher + external DB
- Storage Driver: devicemapper with thinpool

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Join 3 hosts to cluster. Check container on /env/.../infra/containers/.../labels

**Results:** 
Cannot see container stats

Browser shows:

- Request URL: ws://10.132.238.190/v1/containerstats/6b86719b2a755b29ffba02
- Status Code: 101 Switching Protocols

Host stats are showing CORRECTLY:

- Request URL: ws://10.132.238.190/v1/hoststats?token=eyJhbGciOi
- Status Code: 101 Switching Protocols

Apart from that I can also View Container Logs and Execute Shell in the container

> docker logs -f rancher-agent

`time="2016-08-19T06:19:53Z" level="error" msg="Error getting container info." error="request \"http://127.0.0.1:9344/api/v1.3/containers/system.slice/docker-6b86719b2a755b29ffba023e6e91b27ce2fca39202be5d4c77b11a6b5276ec0e.scope\" failed with error: \"failed to get container \\\"/system.slice/docker-6b86719b2a755b29ffba023e6e91b27ce2fca39202be5d4c77b11a6b5276ec0e.scope\\\" with error: unknown container \\\"/system.slice/docker-6b86719b2a755b29ffba023e6e91b27ce2fca39202be5d4c77b11a6b5276ec0e.scope\\\"\"" id="6b86719b2a755b29ffba023e6e91b27ce2fca39202be5d4c77b11a6b5276ec0e"
E0819 16:19:53.961406   12200 fs.go:291] Stat fs failed. Error: no such file or directory
E0819 16:19:53.961432   12200 fs.go:291] Stat fs failed. Error: no such file or directory
E0819 16:19:53.961455   12200 fs.go:291] Stat fs failed. Error: no such file or directory
E0819 16:19:53.961461   12200 fs.go:291] Stat fs failed. Error: no such file or directory
`

I execed inside `rancher-agent` container to debug:

> docker exec -ti rancher-agent bash
> curl http://127.0.0.1:9344/api/v1.3/containers/  --> returned json
> curl http://127.0.0.1:9344/api/v1.3/containers/system.slice/ --> returned json
> curl -v http://127.0.0.1:9344/api/v1.3/containers/system.slice/docker-6b86719b2a755b29ffba023e6e91b27ce2fca39202be5d4c77b11a6b5276ec0e.scope

`
> User-Agent: curl/7.35.0
> Host: 127.0.0.1:9344
> Accept: */*
>
< HTTP/1.1 500 Internal Server Error
< Content-Type: text/plain; charset=utf-8
< X-Content-Type-Options: nosniff
< Date: Fri, 19 Aug 2016 06:24:35 GMT
< Content-Length: 242
<
failed to get container "/system.slice/docker-6b86719b2a755b29ffba023e6e91b27ce2fca39202be5d4c77b11a6b5276ec0e.scope" with error: unknown container "/system.slice/docker-6b86719b2a755b29ffba023e6e91b27ce2fca39202be5d4c77b11a6b5276ec0e.scope"
`

**It looks like cAdvisor is failing to get information about storage**

> /var/lib/cattle/bin# ./cadvisor --version
cAdvisor version 0.23.2 ()

**Expected:**
I should see container stats

**Comment by geeknam** [comment]
probably related to https://github.com/rancher/rancher/issues/5428

**Comment by janeczku** [comment]
@geeknam I am going to close this since it appears to be the same issue as reported in #5428.
