### ISSUE TITLE
Add Azure AD Multi-factor Authentication Support

### ISSUE THREAD

**Issue by samattridge** [rancher/rancher#5772]
**Rancher Version:** 1.1.2

It's great to see support for Azure AD but we have enabled multi-factor authentication on our Azure AD accounts which doesn't appear to be supported by Rancher.  Without this support we will have to revert to handling accounts in Rancher manually.

**Comment by davebown** [comment]
Don't understand why AAD authentication isn't done using OAuth 2 like Github one is. That way multi-factor authentication works and surely this could have leveraged common code.

**Comment by chookie** [comment]
Is there any progress on this?  We have multi-factor enabled so when we try to log in we get the error:

Response
```
{"id":"19a2f155-6e57-4172-a113-619a55ce6299","type":"error","links":{},"status":503,"code":"AzureError","message":"Error from Azure: 400","detail":"Details: interaction_required, Description: AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '00000002-0000-0000-c000-000000000000'.\r\nTrace ID: 4a00f4b7-261f-40a8-bd01-20321c28f03a\r\nCorrelation ID: f5657a2e-cffb-4783-b6f0-15d8ce3acef6\r\nTimestamp: 2017-01-23 11:19:31Z","baseType":"error","actionLinks":{}}
```

Request
```
Request URL:http://x.x.x.x:8080/v2-beta/token
Request Method:POST
Status Code:503 Service Unavailable
```

When implementing Active Directory in our apps we have to use the Azure login screens (redirects) because of MF.  We tried many ways and contacted Microsoft but it seems this is the only supported way to use AD with MF.  Happy to chat more or get some ideas if you have any?

**Comment by zimmertr** [comment]
@chookie I'm experiencing this even without multi-factor on right now with Azure AD.

**Comment by chookie** [comment]
We had to register a native application in Azure, not a web app, as that is how Rancher works.  Then we had to whitelist the application in AD so it does not use MF like the tenant default.

**Comment by deniseschannon** [comment]
This authentication method for Azure AD is in 2.0.

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

**Comment by dabeck** [comment]
> We had to register a native application in Azure, not a web app, as that is how Rancher works. Then we had to whitelist the application in AD so it does not use MF like the tenant default.

Do you have a hint where or how to add this native app to the "whitelist"?

**Comment by chookie** [comment]
@dabeck I am afraid we could not get the AD to work and move to GitHub.  Sorry.
