### ISSUE TITLE
Adding many catalogs

### ISSUE THREAD

**Issue by zambon** [rancher/rancher#5773]
**Rancher Version:** 1.1.2

**Docker Version:** 1.11.2

**OS and where are the hosts located? (cloud, bare metal, etc):**

* Ubuntu 16.04 64-bit
* SoftLayer - Virtual machines

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

* Single node rancher
* External database
* Single host (proxy + rancher + db in a Docker Compose file)

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:**

1.  Click `ADMIN` -> `Settings`.

1. In `Catalog`, add many different catalogs, so that the combined length of all names and URLs (including _library_ and _community_, if enabled) is greater than 1024 characters.

**Results:** 

The UI shows _Saved!_, but the catalog does not show up. Looking at the browser developer tools, there's a 409 error.

Investigating the error down to Rancher logs, @lgfa29 and I were able to track the problem down to the 1024 length of the `value` column of the `setting` table in Cattle's database.

**Comment by tfiduccia** [comment]
Version v1.2.0-pre2
This is an issue

**Comment by shawnHartsell** [comment]
Can confirm the same on v1.1.1

While a simple schema change on the setting table would fix this (and it's what we're planning to do as a work around) maybe this data should be modeled so it is not stored as a comma delimited list? I can imagine that parsing that on the client side would become inefficient over time

**Comment by sangeethah** [comment]
Tested with rancher-server version - v1.2.0-pre4-rc3
We are allowed to set catalog.url values that are larger than 1024 now.

```mysql> select id,name,length(value) from setting where name ="catalog.url";
+----+-------------+---------------+
| id | name        | length(value) |
+----+-------------+---------------+
|  3 | catalog.url |          2043 |
+----+-------------+---------------+
1 row in set (0.00 sec)```

**Comment by tfiduccia** [comment]
Version - v1.2.0-pre4-rc4
Verified fixed from UI
