### ISSUE TITLE
As admin in cli you only see environment you are member/owner of

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#5776]
**Rancher Version:** v1.2.0-pre2-rc7

**Steps to Reproduce:**
1.  setup CLI
2.  Authenticate through Github
3.  Add user and make them an admin
4.  Create a bunch of environments, but only add the user to 1
5.  run ./rancher env ls

**Results:** Only see 1 environment.  There is currently not a way to see all of them.

**Expected:**  Need a way to see all environment if I'm a admin

**Comment by deniseschannon** [comment]
Verified fixed with Rancher CLI v0.4.0-rc1, and rancher in v1.2.0-rc2.

`./rancher env ls -a` shows all environments
