### ISSUE TITLE
Deleting Swarm environment doesn't delete hosts

### ISSUE THREAD

**Issue by leebenson** [rancher/rancher#5777]
**Rancher Version:**

1.1.2

**Docker Version:**

1.11

**OS and where are the hosts located? (cloud, bare metal, etc):**

AWS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

- Single Node Rancher
- External DB (RDS)
- No HA proxy setup

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

Swarm

**Steps to Reproduce:**

1. Create Swarm environment
2. Add host (name it 'staging')
3. Add a couple of random Docker images under 'System' stack
4. Clone original host - give it a new name
5. Go to Environments -> Manage Environments
6. Hold down CMD + click 'Deactivate'
7. Hold down CMD + click 'Delete'

**Results:** 

In the AWS EC2 list, the 'staging' server and the second host created are still there, running.

**Expected:**

That the underlying instances be terminated on delete.

**Comment by tfiduccia** [comment]
@leebenson - How long did you wait until you manually deleted the instances?  It takes a couple of minutes before the instance started to shut down and terminate.  I was not able to reproduce this, when I waited, the instances and the keypairs were deleted from AWS EC2.  If you wait and can still reproduce, reopen issue.

Tried on 1.1.2 and on master - not able to reproduce.
