### ISSUE TITLE
Keypairs not removed from old hosts

### ISSUE THREAD

**Issue by leebenson** [rancher/rancher#5778]
**Rancher Version:**

1.1.2

**Docker Version:**

1.11

**OS and where are the hosts located? (cloud, bare metal, etc):**

AWS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

- Single node Rancher
- External DB (RDS)
- No HA proxy

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

Any

**Steps to Reproduce:**

1. Create any new environment, and add 2x machines, named staging1 & staging2
2. Delete the machines and the environment
3. Create a new environment, and add the same 2 machines (same names)

**Results:** 

<img width="715" alt="screen shot 2016-08-20 at 10 46 27" src="https://cloud.githubusercontent.com/assets/719722/17830454/6226c1b2-66c3-11e6-8d50-6eccb7d2e544.png">

**Expected:**

Keys to be removed when machines are removed, so that those re-creating new instances with the same name won't conflict with old names

**Comment by leebenson** [comment]
Note: I don't have the steps to reproduce exactly how the machines were removed in the first place. It could be because I simply deleted the environment (assuming the machines would go down with it), and then later removed the hosts manually - which would make sense why keypairs weren't removed with them.

This probably relates to #5777

**Comment by tfiduccia** [comment]
You are correct, if you remove the host manually, AWS does not remove the keypairs.  Associated to #5777.
