### ISSUE TITLE
etcd disaster recovery should display only data.current option

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#5779]
**Rancher Version:**1.1.3

**Docker Version:**1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):**Cloud

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**Kubernetes

**Steps to Reproduce:**
1. Create a Kubernetes environment in Resilient Separated-Planes set up
2. Turn off two hosts.
3. Perform disaster recovery (Type disaster). The following shows up
```
Which backup do you want to recover
It says which backup do you want to recover?
1) data.current
2) events
```
events should not be displayed as an option.

**Comment by LLParse** [comment]
Fixed in `etcd-v2.3.7-8`. The `disaster` command no longer accepts user input and rebuilds the cluster from data.current
