### ISSUE TITLE
Support adding of sidekicks as part of upgrading service.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#5780]
Rancher Version:v1.1.3

Add support adding of sidekicks as part of upgrading service.

**Comment by sangeethah** [comment]
Closing this issue .
This issue is not needed anymore for 1.1.x since the new kubernetes system stack templates are not introducing any new sidekicks.

If there is a need to add new sidekicks for any future  kubernetes system stack templates relating to v1.2 , will reopen this issue.

**Comment by drdaeman** [comment]
Was this something Kubernetes-specific?

Maybe this can be reopened and turned into a stack-independent feature request? I had a case (using Cattle) when my nginx image grew up from a simple standalone container to a slightly more complex one, that wants a sidekick. A feature to add sidekicks "on the fly", while surely not important, would be still nice to have.

**Comment by sangeethah** [comment]
@drdaeman , This feature is already supported in v1.2.0-pre2 release.
