### ISSUE TITLE
[cli] rancher export options

### ISSUE THREAD

**Issue by jrottenberg** [rancher/rancher#5783]
**Rancher Version:** 1.1.2

**Docker Version:** 1.12

**OS and where are the hosts located? (cloud, bare metal, etc):** Amazon Linux,  AWS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** Single node rancher + external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:**

rancher export ${STACK}

**Results:** 

A tar file with two files : docker-compose.yml & rancher-compose.yml

**Expected:**

An extra option to display one or the other :

rancher export --docker ${STACK} # docker-compose.yml in stdout

rancher export --rancher ${STACK} # rancher-compose.yml in stdout

It's convenient to be able to extract the docker-compose.yml, and even better to stdout to pipe it to other process to adjust fields like image, etc.

**Comment by jrottenberg** [comment]
cherry on the cake if I can pass a format option as well to get a json file


rancher export  --format json --rancher ${STACK} # rancher-compose.json in stdout

That simplifies update of values using jq, etc.

**Comment by bdentino** [comment]
for docker-compose: `rancher export ${STACK} | tar xvO --exclude rancher-compose.yml | yaml2json | jq .`
for rancher-compose: `rancher export ${STACK} | tar xvO --exclude docker-compose.yml | yaml2json | jq .`

get yaml2json: https://github.com/bronze1man/yaml2json

**Comment by jrottenberg** [comment]
yep that's pretty much what I ended up doing (minus the --exclude rancher-compose.yml)
which is pretty nice, thanks

**Comment by ibuildthecloud** [comment]
TBH, I think I'd prefer to leave the command as is because you can just easily pipe to tar to get what you want as @bdentino showed.
