### ISSUE TITLE
Upgrading process: No rollback for metadata

### ISSUE THREAD

**Issue by juandavidgc** [rancher/rancher#5784]
Hello! I have a problem rolling back an upgraded stack. I have a template with two versions: "version one" saves a field in the metadata in the Rancher compose, as following:

...
metadata:
    prd_version: "1.14.2"
...

And "version two":
...
metadata:
    prd_version: "1.15"
...

When I deploy the "version one", Rancher shows me "Upgrade available". If the upgrade the stack, the process fails and I select "Rollback upgrade", all of the services were rolled back to "version one" but the metadata didn't update. It stills shows _prd_version: "1.15"_

**Rancher Version:** 1.1.3

**Docker Version:** 1.11.1

**OS and where are the hosts located? (cloud, bare metal, etc):** Ubuntu and cloud

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** Single node rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:** Upgrade an stack and rollback.

**Results:** The metadata shows prd_version: "1.15"

**Expected:** The metadata shows prd_version: "1.14.2", because the stack was rolled back.

Thanks!!

**Comment by deniseschannon** [comment]
Can you provide the full docker-compose.yml and rancher-compose.yml for your original stack and upgraded stack? How are you setting `metadata` in your stack?

**Comment by juandavidgc** [comment]
Hello Denise! Of course, below is the link of the files.

[Templates.zip](https://github.com/rancher/rancher/files/434652/Templates.zip)

Thanks!

**Comment by vincent99** [comment]
Recheck for 2.0 but I doubt this still applies...

**Comment by tfiduccia** [comment]
@deniseschannon - Hey Denise, thought we were going to handle upgrades and such for 2.0 and not allow people to stay on older versions, etc... is this still true?

**Comment by deniseschannon** [comment]
The metadata referred to in this post is in the `rancher-compose.yml` of a load balancer image. This key doesn't exist under our load balancer, so I'm not sure what the original user's expectation of what to happen on the ky. 

@juandavidgc sorry for responding so late. it's not updating cause it's not a key that's expected to be managed by a load balancer.
