### ISSUE TITLE
Containers not being purged when deleting kubernetes environment

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#5785]
**Rancher Version:** Version - master

**Steps to Reproduce:**
1.  Create kubernetes environment (I upgraded to 1.3)
2.  Add wordpress catalog
3.  Wait until everything is fully setup and active
4.  Delete kubernetes environment (wait a while until everything should have deleted)
5.  Go to API /v1/containers
6.  Look up wordpress

**Results:** 
Notice there is still a wordpress container that is in a "stopped" state but associated to environment that is purged.

**Expected:**
Should not leave containers around.

**Comment by drauschenbach** [comment]
I also notice that after I delete a Replication Controller, I have to manually delete its pods.

**Comment by alena1108** [comment]
@drauschenbach those would be 2 different issues. Removing RC not causing pods to be cleaned up, is related to: https://github.com/rancher/rancher/issues/4359. Issue @tfiduccia reported is most likely caused by some bug in the account.purge code

**Comment by thosvesta** [comment]
I also notice a simlar issue
