### ISSUE TITLE
Rancher health checks not starting for some services

### ISSUE THREAD

**Issue by bdentino** [rancher/rancher#5789]
**Rancher Version:**
v1.1.2
**Docker Version:**
1.11.2
**OS and where are the hosts located? (cloud, bare metal, etc):**
RancherOS 4.4.10 - AWS
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node, external DB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
Bring up a new stack w/ at least ~15 health-checked services on one rancher host
**Results:** 
Services eventually come up, but health checks never start for some of them. Seems random which ones it doesn't start for. Looking at the container logs, these services are healthy and simply not receiving health-check requests from rancher. Because of this, some services are never actually marked healthy and are stuck in an activating/removing cycle
**Expected:**
Service healthchecking should start after the grace period

This is happening to me pretty reliably when a new host comes online or new stack is deployed and 10-20 services are being brought up at once. Usually at least 1/3 of them never actually start receiving health checks and so they are eventually terminated and restarted by rancher because it considers them unhealthy when they aren't. This cycle seems impossible to get out of until I manually delete the containers in these services, and often times that doesn't even work. I have also noticed that even though these services are never marked healthy, rancher still starts routing internal traffic to them, which is making things worse as active requests are then being dropped when rancher decides to terminate the container because it thinks it's unhealthy. Is this expected?

Happy to provide logs if someone could tell me where to look. Rancher health-checking seems like a bit of a black box right now.

**Comment by deniseschannon** [comment]
Can you provide the docker-compose.yml and rancher-compose.yml of your stack?

**Comment by bdentino** [comment]
Unfortunately it's a lot of private images. I'll try and reproduce with a similar stack though and share that if I see the same issues.

**Comment by asthomasdk** [comment]
We are seeing a similar issue with stacks we are starting that need health checks for the traefik load balancer to pick up the backend of the service. 

This is on Rancher 1.1.4 with Docker 1.1.12

Once our stack is started, I can upgrade the primary service, and add the same health check settings that I have in my rancher-compose.yml file - and it then works. 

Any ideas on where to look ?

**Comment by asthomasdk** [comment]
I should add that the health checks I am having issues with are defined in rancher-compose.yml files that are part of a custom catalog that we are launching instances from. 

If I add health checks to the launched instance with exactly the same settings, they are added and enabled correctly.

**Comment by vincent99** [comment]
Please comment or reopen if someone has a reproducible way to cause this on a modern release.
