### ISSUE TITLE
Add `COMMAND` protocol for health-checks

### ISSUE THREAD

**Issue by francoishill** [rancher/rancher#5790]
**Rancher Version:**
1.1.3

**Docker Version:**
1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
CoreOS stable 1068.10.0 on GCE

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node, External DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Create a Service that does not have a tcp port on which to do health-checks. For example sentry-worker 
or sentry-cron (https://hub.docker.com/_/sentry/).

**Results:** 
If a Host becomes unhealthy the worker/cron container does not get "health-checked" or rescheduled.

**Expected:**
To be able to add `COMMAND` health-checks. If the command is executed inside the container and returns a non-zero exit code it must become "unhealthy". Refer to Marathon which has HTTP/TCP/COMMAND health-checks: https://mesosphere.github.io/marathon/docs/health-checks.html

**Comment by vincent99** [comment]
2.0 supports command healthchecks.  1.x will not.
