### ISSUE TITLE
Question: View all log lines for a container

### ISSUE THREAD

**Issue by pwhittlesea** [rancher/rancher#5794]
**Rancher Version:** v1.1.2

One of the major factors of my team using an orchestration solution is the ability to debug any issues that occur in production.
A sticking point with Rancher is that we cannot see all the logs for a container if lots of log lines are being generated. As such, if there was an issue higher up in the log then we cannot see it which makes supporting production failures harder.

If this is the case, it means that Racher is less attractive to us as a solution for our production deployments.

Am I correct or is there a way to see all the log lines that I have not found?

**Comment by aemneina** [comment]
The log window does have a scrollback buffer. If you're looking for all logs, that can be done on the host or even better using log aggregation and centralization tools like [logspout](https://github.com/gliderlabs/logspout). Hope that helps.
