### ISSUE TITLE
Question: Number of container restarts and previous logs

### ISSUE THREAD

**Issue by pwhittlesea** [rancher/rancher#5795]
**Rancher Version:** v1.1.2

One of the major factors of my team using an orchestration solution is to be able see container restarts and the logs from those restarts.
A sticking point with Rancher is that when a container is restarted we cannot see the logs for the previous execution or how many times the container is restarted.
This is important because if a container is restarting then there may be a production issue to look into (such as a memory leak).

If this is the case, it means that Racher is less attractive to us as a solution for our production deployments.

Am I correct or is there a way to see the number of restarts for a container and the logs from previous runs?

**Comment by aemneina** [comment]
you should be able to query the auditlogs api and filter based on eventType = api.container.restart... (something like https://RANCHER_URL/v1/auditlogs?eventType=api.container.restart. HTH
