### ISSUE TITLE
Support for default Docker and whitelisted registries

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#5799]
Add a new feature to:
1. restrict pulling images to a specific provided registry
   prepend registry to images that dont have registry specified in the image definition

2. allow creation of whitelist containing multiple registries

**Comment by soumyalj** [comment]
Image pulls not successful in the following case:
default registry = quay.io 
Whitelist registry = "quay.io, index.docker.io"
image is pulled with appending the index.docker.io tag [Eg:  index.docker.io/ubuntu]
Error below:
```
(Expected state running but got error: ImageActivate: failed to do image activate: Failed to pull image: Error response from daemon: error parsing HTTP 404 response body: invalid character '<' looking for beginning of value: "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 3.2 Final//EN\">\n<title>404 Not Found</title>\n<h1>Not Found</h1>\n<p>The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.</p>\n") 
```
Also, if the whitelist contains a space, image pull gives errors. It needs to be trimmed.

**Comment by soumyalj** [comment]
Tested with 1.2.0-pre4-rc4. 
Image pulls were successful for the issue mentioned above:
default registry = quay.io 
Whitelist registry = "quay.io, index.docker.io"
