### ISSUE TITLE
Can't edit Environment ACL when a deleted GitHub Account is part of it

### ISSUE THREAD

**Issue by 0rax** [rancher/rancher#5801]
**Rancher Version:**
1.1.0

**Docker Version:**
1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
RancherOS on AWS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA Rancher with External RDS MariaDB and GitHub authentication Backend

**Steps to Reproduce:**
- Create a GitHub account and allow it to access your Rancher Instance
- In one Environment add an Access Control Rule with this GitHub account
- Remove the account from GitHub
- Access your ACL for this Environment
- Check the account in Admin/Accounts

**Results:**
- The ACL Page of the Environment will throw a 503 with the error message `GitHub Error 503`
- This is generated error originate from the /v1/projects/:id/projectmembers endpoint which generate this error as:

``` json
{
"id": "278a371e-ae29-4224-bff2-5ee7005b87c0",
"type": "error",
"links": { },
"actions": { },
"status": 503,
"code": "GitHubError",
"message": "Non-200 Response from Github",
"detail": "Status code from Github: 404",
}
```
- In the Admin/Accounts listing the user will be shown as a "ghost" user which you can edit to get its Name, Account Type and Description but no Identity is present.
  - Ghost Account
    <img width="1609" alt="ghost" src="https://cloud.githubusercontent.com/assets/2822534/17952891/45c37528-6a66-11e6-9550-2ee346f19103.png">
  - No Identity
    <img width="988" alt="identity" src="https://cloud.githubusercontent.com/assets/2822534/17952890/45aa4b5c-6a66-11e6-8e5f-32daaa41a5d2.png">

**Expected:**
- This should not cause the environment ACL list to trigger a 503 error
- Maybe a way remove the user automaticly if the account was deleted

**Comment by prachidamle** [comment]
Moving out as per discussed with @will-chan

**Comment by prachidamle** [comment]
With the lastest we no longer throw a 503 error, while accessing the environment's Access Control page.
Instead we list the project members and the account deleted is listed as (User not found).

Also in the Admin/Accounts view the User gets listed as (User not found).

I dont think Rancher should auto delete the account, the admin can deactivate and delete the account.

**Comment by prachidamle** [comment]
screenshot of environment ACL, not throwing 503, listing members:
<img width="1077" alt="screen shot 2016-12-13 at 7 00 58 pm" src="https://cloud.githubusercontent.com/assets/1470602/21204307/af60ce3e-c20b-11e6-9699-5621eabbbd05.png">

**Comment by prachidamle** [comment]
screenshot of Admin -> Accounts listing.
<img width="1407" alt="screen shot 2016-12-14 at 2 39 16 pm" src="https://cloud.githubusercontent.com/assets/1470602/21204339/d45100d8-c20b-11e6-9dfc-d6cf3bcf0532.png">

**Comment by galal-hussein** [comment]
Rancher version: master build

Steps:
- Enabled Github authentication
- Added a user to environment as a member
- Deleted this github user
- Navigated to edit environment tab

the edit environment tab didn't throw 500 error and i was able to see the deleted user as `(USER not found) null`, also the same in the account listing.

**Comment by ebr** [comment]
@prachidamle Is it possible to find out (even by looking at the DB?) who are members of that environment? at least this way I can add them back in Github, remove them from Rancher, then remove them again from Github. The way it is right now, I can't edit any of my Rancher environments, and have no idea which account is causing it. (#6955)
