### ISSUE TITLE
Api view doesn't work in offilne environment

### ISSUE THREAD

**Issue by clicman** [rancher/rancher#5802]
**Rancher Version:** 1.1.2
**Docker Version:** 1.10.3 on thinpool
**OS and where are the hosts located? (cloud, bare metal, etc):** RHEL7 OpenStack VM

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node w/o internet access

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Try to view in API something

**Results:** 
Blank page

**Expected:**
Api view oened successfully

As I see it tries to fetch some scripts and assets from internet:
https://releases.rancher.com/api-ui/1.0.4/ui.min.css
https://releases.rancher.com/api-ui/1.0.4/ui.min.js
https://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css
https://netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js
https://netdna.bootstrapcdn.com/bootstrap/3.1.1/fonts/glyphicons-halflings-regular.woff

As Rancher support offline setups - it should be bundled inside Rancher server.

**Comment by vincent99** [comment]
This is already changed in 1.2.0-dev1 or 2.
