### ISSUE TITLE
Built-in machine driver schemas do not update on server upgrade

### ISSUE THREAD

**Issue by vincent99** [rancher/rancher#5803]
Upgrading between rancher versions where the docker-machine build changes does not update the schemas for the built-in drivers.  For 1.2.0-pre3 azure is completely different and amazonec2 and other drivers have smaller changes that need to be reflected for the UI to work right.

**Comment by jloisel** [comment]
Will this impact the API as well? I think about amazonec2Config fields in machine.

**Comment by vincent99** [comment]
Yes, the [driver]Config schemas reflect the options available in the drivers.  So azureConfig schema will be pretty much completely different, and amazonec2 security groups will change to an array

**Comment by jloisel** [comment]
Thanks, we'll change our backend accordingly.

**Comment by soumyalj** [comment]
Tested with upgrade from 1.1.4 to 1.2.0-pre4-rc14. Added Digital Ocean and EC2 machines after the upgrade. The driver was set correctly in API. Host addition was successful. 
@tfiduccia : Can you please try with Azure ?

**Comment by tfiduccia** [comment]
Version - v1.2.0-pre4-rc14
Created Azure machine/host on upgrade from 1.1.4, and let it setup.  
Verified fixed
