### ISSUE TITLE
Kubernetes components land in hosts where etcd=true

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#5804]
**Rancher Version:**1.1.3

**Docker Version:**1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):**Ubuntu, Cloud

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**: Kubernetes

**Steps to Reproduce:**: 
1. Create a Kubernetes set up with template https://github.com/llparse/testing-catalog.
2. Ensure 3 hosts have etcd=true, 2 hosts have orchestration=true and one host without label

**Results:** 
1. As per the template with plane seperations, Kubernetes components should land on hosts where orchestration = True. But some of the components land in a host were etcd=true.

**Comment by LLParse** [comment]
It is a hard requirement to support both overlapping and separated-plane deployments in a single template. We must use soft contraints to acheive this. Upon creation of a 'Kubernetes' environment, the system stack is launched immediately... so a race condition manifests where containers are sometimes scheduled to hosts before they are labelled.

The solution is to label hosts before launching the system stack, which is not currently an option, but will be possible with the upcoming infrastructure catalog.
