### ISSUE TITLE
Can't edit machine driver

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#5808]
**Rancher Version:** master 8/25

**Steps to Reproduce:**
1.  Add a new machine driver
2.  Edit the machine driver an dadd to the url or add something to Custom/Checksum

**Results:** Validation failed in API: externalId must be set

**Expected:** No error

**Comment by ibuildthecloud** [comment]
https://github.com/rancher/cattle/pull/1973

**Comment by tfiduccia** [comment]
Version - v1.2.0-pre3-rc2
Verified fixed
