### ISSUE TITLE
Add check for Azure Name field

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#5810]
**Rancher Version:** master 8/25

*\* Comment:*\* Azure machines must be
- Lowercase alphanumeric
- More than 3 characters and less then 63 (so 4-62 characters)

**Comment by vincent99** [comment]
This was added a while ago.. https://github.com/rancher/ui/blob/master/app/components/machine/driver-azure/component.js#L121-L128

**Comment by tfiduccia** [comment]
Version - master 11/29
Verified fixed
