### ISSUE TITLE
Deleting kubernetes container for migration, results in rancher-ingress-controller and rancher-kubernetes-agent being recreated.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#5811]
Rancher Version:v1.1.3

Steps to reproduce the problem:

Create Kubernetes env with 3 hosts with no etcd/orchestration labels using K8s system stack template version - v1.2.4-rancher9 from https://github.com/llparse/testing-catalog.

In the attempt to convert the deployment from overlapping Planes - > seperated Planes , add "orchestration=true" label to one of the existing hosts.

Attempt to delete kubernetes container  for migration.
This results in see rancher-ingress-controller as well as rancher-kubernetes-agent getting destroyed and recreated.

Is it expected that rancher-ingress-controller and  rancher-kubernetes-agent be destroyed and recreated in this case ?

**Comment by LLParse** [comment]
These components make connections to 'kubernetes' container (apiserver), so their getting destroyed/recreated indicates an absence of reconnect logic in rancher-ingress-controller and rancher-kubernetes-agent.

**Comment by deniseschannon** [comment]
Yes, the rancher-ingress-controller and kubernetes agent would be deleted and recreated as its lost its connection to the kubernetes api server container.
