### ISSUE TITLE
During K8s template upgrade , all services under kubernetes-loadbalancers get deleted and recreated.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#5812]
Rancher Version:v1.1.3

Steps to reproduce the problem:
Create Kubernetes env with 3 hosts using K8s system stack template version - v1.2.4-rancher8.

Create few pods , ingress rules and Lb services.

Upgrade Kubernetes system stack to k8s template version - v1.2.4-rancher9 from https://github.com/llparse/testing-catalog.

After Kubernetes system stack upgrade , all the services under kubernetes-loadbalancers get deleted and recreated. Lb service is functional after upgrade. But is it expected for the kubernetes-loadbalancers to get deleted and recreated during upgrade ?

```
mysql> select id,name,state,created,removed,start_count from instance where name like "%kubernetes-loadbalancers%";                                                                                                                                  
+-----+----------------------------------------------------------------+---------+---------------------+---------------------+-------------+
| id  | name                                                           | state   | created             | removed             | start_count |
+-----+----------------------------------------------------------------+---------+---------------------+---------------------+-------------+
| 729 | kubernetes-loadbalancers_lb-a2722ba5d6b0b11e695bb023ce26ac11_1 | purged  | 2016-08-25 21:30:43 | 2016-08-25 21:46:21 |           1 |
| 744 | kubernetes-loadbalancers_lb-a2722ba5d6b0b11e695bb023ce26ac11_1 | running | 2016-08-25 21:46:31 | NULL                |           1 |
+-----+----------------------------------------------------------------+---------+---------------------+---------------------+-------------+
```

**Comment by alena1108** [comment]
@sangeethah it happens because ingress healthcheck depends on its communication with Rancher/k8s. And when k8s goes down during the upgrade, ingress-controller becomes unhealthy. Would have to re-think health check strategy.
