### ISSUE TITLE
[cli] 

### ISSUE THREAD

**Issue by mrproper** [rancher/rancher#5814]
It seems that you cannot have multiple environment api keys in the cli.json file

It assumes that you only have 1 api key for 1 environment
{"env":"foo", "accessKey": "key", "secretKey": "secret", "url": "http://rancher_fqdn/v1/schemas" }

I would like to have several of these, ie:
{"env":"foo1", "accessKey": "key1", "secretKey": "secret1", "url": "http://rancher_fqdn/v1/schemas" },
{"env":"foo2", "accessKey": "key2", "secretKey": "secret2", "url": "http://rancher_fqdn/v1/schemas" }

I had a brief look at the code that parses this config, its just assuming a single hash

**Comment by deniseschannon** [comment]
You should use account API keys if you want to access the environments that you have access to.

http://docs.rancher.com/rancher/v1.2/en/cli/#configuring-the-rancher-command-line-interface
