### ISSUE TITLE
Pods running on "orchestration" hosts where kubelet and proxy are not running.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#5815]
Rancher Version:v1.1.3

Steps to reproduce the problem:

Create Kubernetes env with 4 hosts with no etcd/orchestration labels using K8s system stack template version - v1.2.4-rancher9 from https://github.com/llparse/testing-catalog.

In a host that has few pods running , add label ```orchestration=true``` . 
Migrate system stack containers to this host. Note that at this point , kubelet and proxy are still running on this host.

Now make this Kubernetes env a cattle environment. Then update this environment back to Kubernetes env.

Once system stack is "active" , notice that the host with label ```orchestration=true``` has no kubelet /proxy container running in it and it is not listed in ```kubectl get nodes```.
 
But the pods on these hosts continue to run on the host.

They are not listed in ```kubectl get pods```.

**Comment by LLParse** [comment]
The [migration procedure for overlapping -> separated-planes deployments](https://github.com/rancher/rancher/wiki/Kubernetes-Management#overlapping-planes-to-separated-planes) needs to be followed to prevent pods from being orphaned.
