### ISSUE TITLE
Virtual Machine Support text to close to access control

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#5816]
**Rancher Version:** Master 8/25

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**
1.  Go to Add environment with Authentication off

**Results:** Virtual Machine Support text to close to access control
![image](https://cloud.githubusercontent.com/assets/11514927/17989772/a58ee590-6ae4-11e6-8731-00e0b72745fd.png)

**Expected:**  Should not be that close to the line.

**Comment by vincent99** [comment]
n/a in new infra catalog..
