### ISSUE TITLE
Can't creat stack in rest api

### ISSUE THREAD

**Issue by dreamOW** [rancher/rancher#5820]
**Rancher API Version:**  v1

Hello, I want to practice using rancher rest api, but I find that I can't create a stack (or environment in api), Do I not find way or there is no api for creating stack, by the way, Host too, I will be very thankful if you give me some advise.

**Comment by vincent99** [comment]
Everything the UI, rancher-compose, etc do is 100% through the API.

- Creating a Stack is `POST /v1/projects/<id>/environments`.
- The custom add host script is a `registrationToken` (`POST /v1/projects/<id>/registrationTokens` or reuse one that already exists)
- All the cloud provider stuff is `machine` (`POST /v1/projects/<id>/machines` with one of the *Config fields filled out)

**Comment by dreamOW** [comment]
sorry, I can't find out POST /v1/project/<id>/environments,there just are POST /v1/projects/<id>/environmentupgrades

**Comment by dreamOW** [comment]
sorry, I find it out...............
