### ISSUE TITLE
Add global setting of "service create retry time" for when met errors on service creation, to avoid of unlimited retry.

### ISSUE THREAD

**Issue by cuiyz** [rancher/rancher#5821]
**Rancher Version:**
v1.1.1
**Docker Version:**
1.10.3
**OS and where are the hosts located? (cloud, bare metal, etc):**
ubuntu 12.04 on vm
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
create service -> type a wrong image name which dose not exist on docker hub -> create service -> 
**Results:** 
rancher will keep try to create the service with that wrong image name, which will cause CPU goes high
**Expected:**
set a limitation of retry time for stack creation, make it into global setting and let the customer decide how many times they will allow to retry.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
