### ISSUE TITLE
rancher  start  stop  Loading config-defaults 

### ISSUE THREAD

**Issue by Dreampie** [rancher/rancher#5822]
```
06:29:00.460 [main] INFO  ConsoleStatus - [1/6] [0ms] [1ms] Loading config-bootstrap
06:29:00.745 [main] INFO  ConsoleStatus - [2/6] [288ms] [283ms] Loading base-config
06:29:01.023 [main] INFO  ConsoleStatus - [3/6] [566ms] [278ms] Loading config
06:29:01.030 [main] INFO  ConsoleStatus - [4/6] [573ms] [6ms] Starting config-bootstrap
06:29:01.342 [main] INFO  ConsoleStatus - [5/6] [885ms] [312ms] Starting base-config
06:29:01.342 [main] INFO  ConsoleStatus - [6/6] [885ms] [0ms] Starting config
2016-08-26 06:29:01,832 INFO    [main] [ConsoleStatus] [1/32] [0ms] [0ms] Loading bootstrap 
2016-08-26 06:29:02,025 INFO    [main] [ConsoleStatus] [2/32] [193ms] [189ms] Loading config-defaults 
```

docker :1.12.1
rancher: 1.1.12
os: ubuntu 14.04

**Comment by deniseschannon** [comment]
is this a fresh install or upgraded setup?

**Comment by Dreampie** [comment]
yes，use an external database to run Rancher server, happened

**Comment by SantoDE** [comment]
I updated today my setup as well and I now have this issue as well :(

**Comment by deniseschannon** [comment]
@SantoDE @Dreampie  can you give more details?

what is your setup? where is the DB? 

what version are you upgrading from and to? 
can you share your upgrade commands?

**Comment by SantoDE** [comment]
@deniseschannon I just pulled a new docker image. However, I fixed it. My LOCK table was blocked, so rancher could not accquire a lock. Releasing a previous lock solved my issue and rancher was able to boot up again :)

**Comment by aemneina** [comment]
@Dreampie have you implemented the workaround @SantoDE mentions?

**Comment by aemneina** [comment]
closing this out.

**Comment by DavidBadura** [comment]
I have the same problem with externel DB. @SantoDE can you describe what do you do to solve this problem?

**Comment by DavidBadura** [comment]
Have it resolved with https://github.com/rancher/rancher/issues/6334

```
docker exec -it rancher-server bin/bash

mysql

use cattle;

UPDATE DATABASECHANGELOGLOCK SET LOCKED=FALSE, LOCKGRANTED=null, LOCKEDBY=null where ID=1;
```
