### ISSUE TITLE
No events generated when stack is created/deleted.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#5824]
Rancher Version: Build from master

Steps to reproduce the problem:
Create a stack (with v1 or v2 api).
There are no events being generated resulting in UI showing the stack to be in "Activating" state forever unless refreshed.
Delete a stack (with v1 or v2 api).
There are no events being generated resulting in UI showing the stack to be in "Removing" state forever unless refreshed.

**Comment by tfiduccia** [comment]
Version - master 9/1
Verified fixed
