### ISSUE TITLE
K8S : kubernetes_1 does not spawn on the first node and displays an error while unzipping certs.zip

### ISSUE THREAD

**Issue by ThomasSchweizer** [rancher/rancher#5827]
**Rancher Version:**
Rancher	v1.1.3 - Cattle	v0.165.8.1 - User Interface	v1.1.12 - Rancher Compose	v0.8.6

**Docker Version:**
Docker version 1.12.1, build 23cf638

**OS and where are the hosts located? (cloud, bare metal, etc):**
Dedicated Servers

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
External Database (on a private network) - Three Rancher nodes + One Rancher "Master" server
Servers are communicating between them through a fully private network (172.x.x.x)

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
Start a Kubernetes environment
Adding the first server spawns Kubernetes and etcd on it
Adding the two other servers only spawns etcd on it

**Results:** 
Kubernetes_kubernetes_1 - rancher/k8s:v1.2.4-rancher9 is restarting every minute or so.
The cluster is never fully spawned and the deployment information keeps showing  Starting services (1 of 9)

![k8s_2016-08-27_14-01-23](https://cloud.githubusercontent.com/assets/5364364/18026956/22e1111e-6c5f-11e6-9f6f-43c863e1604a.png)

![k8s_2016-08-27_14-08-45](https://cloud.githubusercontent.com/assets/5364364/18026975/d2ae864e-6c5f-11e6-9363-731d88448309.png)

Kubernetes_kubernetes_1 on the first node shows this in the logs : 
`27/08/2016 13:56:25Archive:  certs.zip
27/08/2016 13:56:25  End-of-central-directory signature not found.  Either this file is not
27/08/2016 13:56:25  a zipfile, or it constitutes one disk of a multi-part archive.  In the
27/08/2016 13:56:25  latter case the central directory and zipfile comment will be found on
27/08/2016 13:56:25  the last disk(s) of this archive.
27/08/2016 13:56:25unzip:  cannot find zipfile directory in one of certs.zip or
27/08/2016 13:56:25        certs.zip.zip, and cannot find certs.zip.ZIP, period.
27/08/2016 13:58:25  End-of-central-directory signature not found.  Either this file is not
27/08/2016 13:58:25  a zipfile, or it constitutes one disk of a multi-part archive.  In the
27/08/2016 13:58:25  latter case the central directory and zipfile comment will be found on
27/08/2016 13:58:25  the last disk(s) of this archive.
27/08/2016 13:58:25unzip:  cannot find zipfile directory in one of certs.zip or
27/08/2016 13:58:25        certs.zip.zip, and cannot find certs.zip.ZIP, period.
`

_**Precision :**_ I am able to ping (~ 6 ms) from one host to another via the 10.x which are attributed to containers and from the nodes to the master and vice versa. All ports are open between the hosts since it's a dedicated internal network.

**Expected:**
Kubernetes environment should spawn fully without any errors.

**Comment by LLParse** [comment]
Hi @ThomasSchweizer,

Certificate generation (which is done by Rancher server) doesn't appear to be working. Could you please provide logs from Rancher server?

In your picture, etcd containers are in an initializing state. Do these containers ever enter a running state? If not, providing the logs for those containers would also be helpful.

**Comment by ThomasSchweizer** [comment]
Hello @LLParse 
Actually they stay in the initializing state for hours and never go Running (but maybe I missed some Running state for some seconds). But the general consensus it that it stays on initializing.

Please find the logs attached
"docker logs" on the master container : export_ranchermaster.log
https://gist.githubusercontent.com/ThomasSchweizer/b8c7d7550d8a6c10b0c618b376b7e380/raw/d2b5ecb778fc6167b56efc49af8838f8450959c7/gistfile1.txt 

"cattle-error.log"
https://gist.githubusercontent.com/ThomasSchweizer/e160bc9d4e9e182a23f6845ccc64f0e9/raw/17caeec8a55a8018e3ca795f55bc0eea58c9a097/gistfile1.txt

"cattle-debug.log"
https://gist.githubusercontent.com/ThomasSchweizer/14eab5f7820ef7051a8e286e7b47d03c/raw/ebc9efa691e4002444f17ca1fb7df970e9c2b34e/gistfile1.txt

Regards,
Thomas

**Comment by ThomasSchweizer** [comment]
Hello,

Some update : 
It seems like that Rancher managed to start more K8S containers than on the first screenshoot.
The states are as bad though.

![screenshot_20160829_144633](https://cloud.githubusercontent.com/assets/5364364/18050488/89872144-6df7-11e6-93c4-c03ea70b05d3.png)

The etcd logs are here : 
https://gist.githubusercontent.com/ThomasSchweizer/682bcce471a648371f75d7d8a3ceb7ef/raw/1268b84334d954009e9576598359cd6193ed2d0a/gistfile1.txt

I got into some containers and I can ping and access ports from one host to another on the 10.x Rancher IPs

Regards,
Thomas

**Comment by ThomasSchweizer** [comment]
After further research our node servers were containing in the search section of resolv.conf ourcompanydomainname.com and we had a * wildcard on our domain name which caused internal DNS resolution issues.

I moved the domain name of our node servers to some kind of internal domain and the K8S cluster is now ok.

**Comment by LLParse** [comment]
@ThomasSchweizer, I'm glad you got it figured out.

Would providing fully qualified DNS paths have prevented this issue in the first place? In some places we append `.rancher.internal`, but in other places we do not...I am wondering if we might need to adjust that for interoperability.

**Comment by ThomasSchweizer** [comment]
@LLParse 

Hi,
It is something to test.
Basically on our nodes for the resolv.conf file we had : search ourcompanyname.com

When the containers are started it appends automatically ourcompanyname.com in the containers resolv.conf BUT it appends it at the start of the line so it looks like this (after my fix) : 

`root@025389ddc2c6:/# cat /etc/resolv.conf                                                                                                                                                                                                                                     
search local ourcompany.someinternaltld kubernetes.rancher.internal kubernetes.kubernetes.rancher.internal rancher.internal
nameserver 169.254.169.250`

So I think if I stayed with our public domain name that it would be easier for Rancher to append the node resolv.conf search config at the end of the line for example (after the Rancher DNS search paths) when the containers are created but I didn't looked into Rancher code if it was possible so it avoid us to use some other TLD (because of the wildcard requirement we have on our main domain for a specific need).

Regards,
Thomas

**Comment by LLParse** [comment]
Ah, makes sense. Thanks for explaining it to me. If that's the case, I have my doubts that naming the TLD explicitly would've fix the original problem...we may need to adjust the logic that generates the resolv.conf file. 

Anyway, glad you were able to work around it.
