### ISSUE TITLE
Move hosts between environments (new UI term)

### ISSUE THREAD

**Issue by pakfur** [rancher/rancher#583]
It would be very useful to be able to move a host between projects.  There does not appear to be any UI or API support for this at present.

**Comment by vincent99** [comment]
This wouldn't be trivial to implement but does seem like a useful idea.  In the meantime, some of the enhancements to projects in 0.17 (later today) might mitigate your need for this somewhat, as you can now have multiple owners/members of a project.  More info in https://github.com/rancherio/rancher/issues/160#issuecomment-94979744

**Comment by bscott** [comment]
+1

**Comment by andreis** [comment]
:+1: 

Or make it possible to have the same host in multiple environments.

**Comment by defunctzombie** [comment]
Having a host exist on multiple environments would solve the following use-case for us:

Provision hosts and allocate them to teams (teams can with within their environment). Separately, have an "infrastructure" environment where we can deploy monitoring tools and have an overview of all hosts we have allocated to teams.

Right now, if I setup multiple environments (for resource isolation) it becomes harder to deploy monitoring tools and get an idea of our host fleet without visiting each environment.

**Comment by marsmensch** [comment]
The option to have a host exist on multiple environments would be great.

**Comment by PhanQ** [comment]
Agree! Let's consider if we can isolate user by environment in a same hosts. It's very practical.

**Comment by arkka** [comment]
+1

**Comment by brightbulbnz** [comment]
+1! Must have

**Comment by wfleurant** [comment]
a possible solution might be to re-register any host to any new environment. i'm guessing this would blow away `/var/lib/rancher/state/`

**Comment by amsdard** [comment]
I have similar needs, but access permissions per stack would do me as good as sharing host across environments.

**Comment by deviousgeek** [comment]
This would be a great feature to have. Just need to work out a way to manage all of the infra services. Some sort of isolation.

**Comment by 08ski11s** [comment]
this would be a great feature in rancher..

**Comment by junkiebev** [comment]
I, too, would like the ability to migrate entire environments. Our initial evaluation used a beta server but now I've set up a HA cluster on production hardware and would like to migrate without having stacks break.

+1

**Comment by NiggyWizzyWoz** [comment]
Yes, please. This is the first thing that I tried while playing around with Rancher, which completely screwed things up. The current model is okay if you can provision hosts on the fly using a docker-machine-driver and you get billed by the hour, But when your provider is not as flexible or when you have dedicated servers things get a little bit weird. Say I have a bunch of dedicated machines doing some heavy lifting task either on premise or some dedicated provider, How would I efficiently transfer these hosts to another environment or share the same hosts between multiple environments without breaking the stack which I already have? In order to migrate would I have to go and delete the host on the previous environment and re-add it for the newer environment?  I think that it's a major problem with Rancher in the aforementioned use-case.

**Comment by PhilCorney** [comment]
+1

**Comment by sayume** [comment]
+1, logical stack should not bind to physic hosts.

**Comment by duchy** [comment]
+1

**Comment by lbardelli** [comment]
+1

**Comment by jimdelois** [comment]
+1

**Comment by XavierBoubert** [comment]
:+1:

**Comment by jralmaraz** [comment]
+1

**Comment by build-failure** [comment]
+1

**Comment by chendo** [comment]
Would there be any issues with trying to do this by using Docker in Docker, so the host machine would boot up a container, each with its own Docker instance?

**Comment by KaelBaldwin** [comment]
+1

**Comment by vasmancs** [comment]
+1

I would like to have a local and a swarm manager environments on a host but it is not possible at the moment as a host can only be attached to one of them..

**Comment by edux** [comment]
+1

**Comment by prashant68** [comment]
+1

**Comment by jblamotte-fa** [comment]
+1

**Comment by matesito** [comment]
+1

**Comment by KevinMaschke** [comment]
+1

**Comment by raviv** [comment]
+1

**Comment by RichardoC** [comment]
+1

**Comment by spijker** [comment]
+1

**Comment by Chuckame** [comment]
+1

**Comment by spawnia** [comment]
Dear +1 commenters, please use GitHubs thumbs up feature instead to voice your approval. Thanks

**Comment by vincent99** [comment]
Moving is not going to happen for 1.x.  In 2.0 hosts (nodes) belong to clusters and multiple environments (projects) can share the same cluster (and therefore nodes), so there should be little need to "move" one.
