### ISSUE TITLE
Can not resolve external domain in container

### ISSUE THREAD

**Issue by strahe** [rancher/rancher#5832]
**Rancher Version:** 1.1.3

**Docker Version:**1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):**CentOS7.2，bare metal

**Setup Details:** single node

**Environment Type:** Kubernetes

**Steps to Reproduce:**

**Results:** 

**Expected:**

in docker container, cat /etc/resolv.conf:

search fudao.svc.cluster.local svc.cluster.local cluster.local kubelet.kubernetes.rancher.internal kubernetes.rancher.internal rancher.internal rancher.internal
nameserver 169.254.169.250
options ndots:5

I ping google.com or any external domain, always get 127.0.0.1.

**Comment by tinque** [comment]
I have the same issue ... How did you resolve that ?

**Comment by strahe** [comment]
@tinque I found it is not rancher problem(maybe)，just do not use alpinelinux image，if you have to， delete `options ndots:5` in /etc/resolv.conf.

**Comment by Shubhankitmishra** [comment]
Here is the solution https://github.com/jderusse/docker-dns-gen/issues/21?_pjax=%23js-repo-pjax-container
