### ISSUE TITLE
API Environment Keys

### ISSUE THREAD

**Issue by kaos** [rancher/rancher#5833]
**Rancher Version:**
1.1.2

**Docker Version:**
1.12

**OS and where are the hosts located? (cloud, bare metal, etc):**
Bare, RHEL

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node, external DB.

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Create several environments, and add a few api keys in each.

**Results:** 
List all api keys, regardless of selected environment.
https://rancher.example.net/env/1a666/api

**Expected:**
Only see keys that apply to current environment. Or, at least show which environment each key works for.
We have a few different tools, that all interact with each environment, so they tend to have the same key name and description in each env, so there's no way to tell which key is for which environment from the UI (that I've found, at least).

**Comment by kaos** [comment]
Or, there was a bug in the UI, because now it seems to only show the api keys for the current environment. Could toss this into the `glitches` bin.

**Comment by kaos** [comment]
Ok, I managed to reproduce this now.

** Steps to reproduce **

As above, then go to _Admin/Accounts_ then to _API_, it now shows ALL api keys for ALL environments, not just the current one. Reloading the page will get the list back down to show only the current environments API keys again.

**Comment by tfiduccia** [comment]
Version - 1.2.0-pre4-rc10 : This is still reproducible.  By going to accounts page then API, I can see all environment keys in the environment section.

**Comment by tfiduccia** [comment]
Version - v1.2.0-pre4-rc14
Verified fixed
