### ISSUE TITLE
Make BACKUP_PERIOD and BACKUP_RETENTION configurable parameters.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#5834]
Rancher Version:v1.1.3
K8s system stack template version - v1.2.4-rancher9 from https://github.com/llparse/testing-catalog

Currently BACKUP_PERIOD and BACKUP_RETENTION are hardcoded in the template. They should be made as configurable parameters. 

If BACKUP_PERIOD and BACKUP_RETENTION are made variables , user will be prompted  for these values when upgrading to this K8s template. 
Currently during  K8s  environment, user is not presented with the K8s templates details to allow for Users to be able to provide values when presented with questions.

**Comment by LLParse** [comment]
Added questions for BACKUP_PERIOD and BACKUP_RETENTION to the template.
URL: https://github.com/llparse/testing-catalog
Branch: config-backup-param

The questions work when launched as a cattle template. In kubernetes environment upgrade scenario, user can select the template version but the screen is stuck in a loading phase.

**Comment by LLParse** [comment]
To configure these parameters in a fresh environment would require the infra catalog - is this slated for 1.2.0?

**Comment by sangeethah** [comment]
Tested with Rancher Version: v1.2.0-pre4-rc3 and K8s 1.4 version from - https://github.com/rancher/infra-catalog
User is now provided with BACKUP_PERIOD and BACKUP_RETENTION parameters that can be overridden by users.

Logged bug for including more field description  - https://github.com/rancher/rancher/issues/6295
