### ISSUE TITLE
How add azure machine with --azure-static-public-ip

### ISSUE THREAD

**Issue by Negashev** [rancher/rancher#5836]
**Rancher Version:v1.1.3**

**Docker Version:N/A**

**OS and where are the hosts located? (cloud, bare metal, etc): Azure cloud**

**Setup Details: single node rancher, external DB**

**Environment Type: Cattle**

**Steps to Reproduce: add host with azure drive**

**Results: host is added, but without static ip** 

**Expected: add host from azure with static ip and with open ports**

**Comment by vincent99** [comment]
The current release uses the "Classic" VMs which do not have this option;  `1.2.0-pre3` will update to docker-machine 0.8.x, which uses the new VMs and has an option for this in the UI.
