### ISSUE TITLE
Stale copy of backups remain on host even after the leader etcd container is deleted from the host. 

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#5837]
Rancher Version:v1.1.3

k8s template version - v1.2.4-rancher9 from https://github.com/llparse/testing-catalog

Steps to recreate the problem:

Create a K8s setup with 3 hosts h1,h2,h3.
Add 1 more host - h4.
Power down the host where the leader etcd container is hosted.
A new etcd instance will created on h4 and a new leader will be elected for the etcd cluster.
Power on the host that was powered down.

etcd container running on this host will get deleted. But the  stale /var/etcd/backups directory containing the backup data continues to be present in the host.

We should be able to delete this stale /var/etcd/backups directory  in this case ?

**Comment by will-chan** [comment]
This should be a documention issue of how to clean up hosts to prepare it for etcd.

**Comment by LLParse** [comment]
@sangeethah We've [documented](https://github.com/rancher/rancher/wiki/Kubernetes-Management#configuring-remote-backups) that network storage is to be mounted at `/var/etcd/backups`. If this process is followed for all hosts that are running (or will run) etcd, then any new leader will expire backups outside of the BACKUP_RETENTION period after each subsequent backup. Is this sufficient documentation?

**Comment by sangeethah** [comment]
@LLParse , The scenario mentioned in the bug is the case where user did not choose tp configure Remote Backups using persistent storage.

**Comment by LLParse** [comment]
Added documentation on [tearing down](https://github.com/rancher/rancher/wiki/Kubernetes-Management#tearing-down) to address this.

Added question to enable/disable backups:
URL: https://github.com/llparse/testing-catalog
Branch: config-backup-param

Similar to https://github.com/rancher/rancher/issues/5834, we will not be able to test until infra catalog is available.

**Comment by sangeethah** [comment]
@LLParse , Can you get the changes done on the catalog side put in qa branch of   https://github.com/rancher/infra-catalog/ ? Folder number 12 is k8s 1.4 version which needs to have this change.

**Comment by sangeethah** [comment]
Tested with Rancher Version: v1.2.0-pre4-rc3 and K8s 1.4 version from - https://github.com/rancher/infra-catalog

User has the ability to disable backups. In this case we will still see /var/etc/backups folder getting created on the hosts. But no backups will be taken by any of the etcd containers.
