### ISSUE TITLE
Link selector not working. Rancher internal dns goes crazy

### ISSUE THREAD

**Issue by JaviSabalete** [rancher/rancher#5840]
**Rancher Version:**
1.1.1
**Docker Version:**
1.12
**OS and where are the hosts located? (cloud, bare metal, etc):**
Debian 8, Ubuntu 14 and Ubuntu 16
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node Rancher and External DB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
Environment with 1 stack. Stack contains 2 containers (apache and mysql). Mysql scale 2 o more. Select mysql container with select in apache container.
**Results:** 
root@54ae31327b93:/# ping mysql
PING mysql.full.rancher.internal (10.42.146.166) 56(84) bytes of data.
64 bytes from 10.42.146.166: icmp_seq=1 ttl=64 time=0.116 ms
^C
--- mysql.full.rancher.internal ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.116/0.116/0.116/0.000 ms
root@54ae31327b93:/# ping mysql
PING mysql.full.rancher.internal (10.42.150.100) 56(84) bytes of data.
64 bytes from 10.42.150.100: icmp_seq=1 ttl=64 time=0.033 ms
^C
--- mysql.full.rancher.internal ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.033/0.033/0.033/0.000 ms
root@54ae31327b93:/# ping mysql
PING mysql.full.rancher.internal (10.42.150.100) 56(84) bytes of data.
64 bytes from 10.42.150.100: icmp_seq=1 ttl=64 time=0.058 ms
64 bytes from 10.42.150.100: icmp_seq=2 ttl=64 time=0.072 ms
^C
--- mysql.full.rancher.internal ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 0.058/0.065/0.072/0.007 ms
root@54ae31327b93:/# ping mysql
PING mysql.full.rancher.internal (10.42.150.100) 56(84) bytes of data.
64 bytes from 10.42.150.100: icmp_seq=1 ttl=64 time=0.046 ms
64 bytes from 10.42.150.100: icmp_seq=2 ttl=64 time=0.047 ms
^C
--- mysql.full.rancher.internal ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 0.044/0.053/0.062/0.009 ms
root@54ae31327b93:/# ping mysql
PING mysql.full.rancher.internal (10.42.146.166) 56(84) bytes of data.
64 bytes from 10.42.146.166: icmp_seq=1 ttl=64 time=0.060 ms
64 bytes from 10.42.146.166: icmp_seq=2 ttl=64 time=0.052 ms
^C
--- mysql.full.rancher.internal ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 0.046/0.046/0.047/0.006 ms
root@54ae31327b93:/# ping mysql
PING mysql.full.rancher.internal (10.42.150.100) 56(84) bytes of data.
64 bytes from 10.42.150.100: icmp_seq=1 ttl=64 time=0.044 ms
64 bytes from 10.42.150.100: icmp_seq=2 ttl=64 time=0.062 ms
^C
--- mysql.full.rancher.internal ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 0.052/0.056/0.060/0.004 ms

**Expected:**
Same ip for every ping command

**Comment by vincent99** [comment]
The DNS entry for a service returns the IPs of _all_ the (healthy) containers in that service.  Client applications (ping) will then generally pick one at random.

If you want a 1:1 mapping between the two service's containers, define `mysql` as a sidekick of the `apache` service instead of being standalone.

**Comment by alone23** [comment]
Thanks for reply @vincent99 

I have 2 sidekicks, but not for mysql containers. I just want scale mysql containers only, this is reason to not use sidekick. I use different mysql containers for test different databases

**Comment by JaviSabalete** [comment]
Thanks for reply @vincent99

I have 2 sidekicks, but not for mysql containers. I just want scale mysql containers only, this is reason to not use sidekick. I use different mysql containers for test different databases

**Comment by JaviSabalete** [comment]
Just done another test

Clonning service mysql container and link to new container. Ping not returns new ip

**Comment by vincent99** [comment]
A service with a scale > 1 implies that all the containers of that service are interchangeable.  If you expect those to be *different* databases with different content then they need to be separate services (or standalone containers).

**Comment by JaviSabalete** [comment]
Thanks for your reply @vincent99 you right!

Close this issue
