### ISSUE TITLE
Retrieving service host name from rancher catalog question

### ISSUE THREAD

**Issue by emilebosch** [rancher/rancher#5841]
I can't seem to find in the documentation the way to actually retrieve the service host name from a question in the rancher catalog.

for instance

```
    - variable: DATABASE_URL
      label: Database URL
      required: true
      type: service
```

returns the service name `Infra/DB` for instance. but what i want is the actual dns name. or hostname so i can ping it.

Any ideas?

Thanks

**Comment by aemneina** [comment]
@emilebosch have you solved this? I believe if the value is going to be input by the user launching the catalog, you'd reference it in this manner `${database_url}`. Have you taken a look at how existing catalog items are doing this, if not here's a link to the current [catalog-templates](https://github.com/rancher/community-catalog/tree/master/templates). Let me know if that helps.

**Comment by aemneina** [comment]
@emilebosch I'll close this out, if you have more questions feel free to open a new ticket.
