### ISSUE TITLE
Stopped containers with sidekicks not showing up on host page

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#5844]
**Rancher Version:** v1.2.0-pre2

**Steps to Reproduce:**
1.  Deploy a catalog with a service that contains a sidekick & an upgrade that upgrades the primary service
2.  Upgrade the Stack

**Results:** The stopped primary Service is not showing up on the host page, but is showing up on main stack page and container page.

**Expected:**  Should be consistent and show up on host page as well.

**Comment by tfiduccia** [comment]
Version - master 12/20
Now the stopped container from upgrade is showing up as a sidekick which is confusing.

**Comment by vincent99** [comment]
#6998
