### ISSUE TITLE
Network agent stuck in starting state

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#5849]
**Rancher Version:**1.1.3

**Docker Version:**1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):**Ubuntu, Cloud

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**: Kubernetes

**Steps to Reproduce:**
1. Create a Kubernetes 3 host set up with template https://github.com/rancher/qa-catalog
2. Create pods, turn OFF 3 hosts and after few minutes turn ON only one host

**Results:** 
Network agent is stuck in starting state and other Kubernetes containers are also stuck in starting state.

**Comment by alena1108** [comment]
Not going to fix for 1.2 as we are gonna do major refactoring for our system services, and the health check will be run as a separate service so this problem won't happen in this case.

**Comment by will-chan** [comment]
retest this with latest 1.2

**Comment by soumyalj** [comment]
Tested with 1.2.0-pre4-rc4 following the steps above. Did not see the network agent stuck in starting state.
