### ISSUE TITLE
Stops receiving UDP packets to container after Upgrade

### ISSUE THREAD

**Issue by roflmao** [rancher/rancher#5853]
**Rancher Version:**
1.0.2

**Docker Version:**
1.11.1

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 12.04, Bare Metal

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node Rancher, external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Setup logstash container (which receives UDP packets)
tcpdump and see packets incoming on both host and container (`tcpdump -w - -s0 -A -l -n  port 5147`)
Do upgrade of container (ex to add extra ports)
tcpdump on host shows packets incoming, tcpdump inside container shows no packets incoming.

**Results:** 
After upgrade UDP packets arent sent to new container.

**Expected:**
UDP packets sent to new container as before upgrade.

**Comment by aemneina** [comment]
@roflmao did you ever manage to get to the bottom of this?

**Comment by roflmao** [comment]
Yes, this is related to iptables/conntrack.
https://github.com/docker/docker/issues/8795

After deploy i do this on the host to clear the conntrack table:
```/usr/sbin/conntrack -D -p udp```

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
