### ISSUE TITLE
Entrypoint option does not support multiple commands separated by && or ;

### ISSUE THREAD

**Issue by santagada** [rancher/rancher#5855]
**Rancher Version:**
Rancher v1.1.3
Cattle  v0.165.8.1
User Interface  v1.1.12
Rancher Compose v0.8.6

**Docker Version:**

**OS and where are the hosts located? (cloud, bare metal, etc):**
Amazon linux on EC2

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
type a long set of commands in the entrypoint field when creating a service eg:
make migrate && gunicorn -b 0.0.0.0:8000 app.wsgi --access-logfile -
**Results:** 
error out while trying to pass everything as parameters to make

**Expected:**
run make and then gunicorn, normal Dockerfile/shell behaviour

**Comment by deniseschannon** [comment]
Can you share what the equivalent `docker run` command would be so I can try to reproduce?

**Comment by santagada** [comment]
docker run -ti --entrypoint sh alpine:latest -c "true && echo hi"

apparently --entrypoint on the command line only lets you override using the non shell version of entrypoint. if this is the case for the ui it should say so and only accepts a binary name... but usually if you are overriding is because you need something more complex

**Comment by vincent99** [comment]
This was a bug in the UI parsing the command into an array to pass to the API..

**Comment by santagada** [comment]
it still should be documented that it will parse it into an array and not be the shell version of entrypoint.

**Comment by tfiduccia** [comment]
Version 1.2 - not fixed?
UI changes && to \&\& and it doesn't seem to work

**Comment by patsissons** [comment]
I have solved this (in `v1.3.1`) with an **Entry Point** of `/bin/sh -c` and a **Command** of something like this: `'echo "asdf" > /tmp/test1 && cp /tmp/test1 /tmp/test2 && cat /tmp/test2 && /bin/sh'`

**Comment by vincent99** [comment]
Yes it was mostly fixed in 1.3 but cloning brought back all the control character escaped (`e.g. echo hello \&\& echo world`)

**Comment by tfiduccia** [comment]
Version - v1.4.0-rc6
Verified fixed.

**Comment by naisanza** [comment]
Is having an Entrypoint necessary in the UI?

If i just want to run `touch /success`

Do I need the full path? `/usr/bin/touch /success`
Do I need to wrap the command in quotations? `"/usr/bin/touch /success"`

**Comment by ChristopherLClark** [comment]
I'm having this issue with exit code 127. My Entrypoint in dockerfile is

`ENTRYPOINT ["/bootstrap.sh", "cd /app/myproject/output && dotnet myproject.dll"]`

and my bootstrap.sh does end with `exec "$@"`

**Comment by laxmanpradhan** [comment]
Did anyone fine a solution to this? I'm running rancher 2.3.3. I have an alpine image that has crontab already installed. I have a crontab file that is passed into the container at /etc/cron.d/crontab via a config map. If I just leave it at that and open a shell into the container, I can run 'crontab /etc/cron.d/crontab' and it loads the file with no problem. 

If however I run that same command into the command section of the Deploy screen, I get this error. 
`/usr/bin/mysqld: Too many arguments (first extra is 'crontab')`

If I add /bin/busybox as the entrypoint and keep the command the same, I get the following event:
`CrashLoopBackOff: back-off 20s restarting failed container=mariadb-alp`
with no logs shown.  Note again that I can open the console into the container and run 
`/bin/busybox crontab /etc/cron.d/crontab`
and it works correctly

I suspect in the second case, the command is actually running correctly, however after the command is done, it seems to think the pod has failed and it tries to restart it.

So how do we pass commands into the container? Has anyone gotten this to work?
