### ISSUE TITLE
pulling from private repo fails

### ISSUE THREAD

**Issue by EugenMayer** [rancher/rancher#5856]
**Rancher Version:**
1.1.2
**Docker Version:**
1.11.2
**OS and where are the hosts located? (cloud, bare metal, etc):**
bare metal

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
internal, no ha
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
cattle

**Steps to Reproduce:**
- Setup a https based registry with a bearer-token auth like portus ( either the community registry or https://github.com/EugenMayer/docker-rancher-extra-catalogs/tree/master/templates/registry-slim )
  Make the general "namespace"
- register that registry in rancher

**Results:** 
any catalog referencing private images or using `docker pull` on the cli will fail, due to authentication issues. Either the Bearer tokens are issues ( scope based tokens ) or something else

**Expected:**
pulling private images works

I can pull out of those registries using docker on my OSX / linux without any issues.

**Comment by EugenMayer** [comment]
In addition, if i run `docker login myprivaterepo.tld` on the rancher bash and the try to `docker pull` it works

**Comment by EugenMayer** [comment]
using `docker login privreg` on the cli enabled the rancher catalog service triggered in the UI to pull images correctly - so there must be somehting in the way registrys are registered using the gui

**Comment by jclif** [comment]
I'm also having trouble pulling my private Dockerhub image.

**Comment by superseb** [comment]
Please re-open if you still experience issues using the documentation: http://rancher.com/docs/rancher/v1.6/en/environments/registries/
