### ISSUE TITLE
Upgrade of private catalog template completes via API, but is still listed in GUI as "upgrade available"

### ISSUE THREAD

**Issue by jliu70** [rancher/rancher#5859]
**Rancher Version:**
1.2.0-pre2

**Docker Version:**
1.11.2

**OS and where are the hosts located? (cloud, bare metal, etc):**
RancherOS v0.5.0   - VMs

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Make curl calls to API

```
UPGRADE_TIMEOUT=60
UPGRADE_BATCH_SIZE=1
UPGRADE_INTERVAL_MILLIS=2000
UPGRADE_START_FIRST="false"
UPGRADE_URL=$(echo $SERVICE_JSON | jq -r '.data[0].actions .upgrade' | sed -e 's/^"//'  -e 's/"$//')
UPGRADE_SLC=$(echo $SERVICE_JSON | jq -r '.data[0].secondaryLaunchConfigs')

CURRENT_LC=$(echo $SERVICE_JSON | jq -r '.data[0].launchConfig' )
CURRENTSVCHASH=$( echo $CURRENT_LC | jq -r '.labels["io.rancher.service.hash"]' | awk -F: '{print $NF}' )
CURRENTIMG=$( echo $CURRENT_LC | jq -r .imageUuid | awk -F: '{print $NF}' )
CURRENTVER=$( echo $CURRENT_LC | jq -r .version | awk -F: '{print $NF}' )
UPGRADE_LC=$(echo $SERVICE_JSON | jq -r '.data[0].launchConfig' | sed -e "s/${CURRENTIMG}/${CI_BUILD_REF_NAME}_${APP_VERSION}_${COMMITCOUNT}_${COMMITHASH}/" | sed -e 's/\"0\"/\"1\"/' )

BODY="{ \"inServiceStrategy\": { \
  \"batchSize\": $UPGRADE_BATCH_SIZE, \
  \"intervalMillis\": $UPGRADE_INTERVAL_MILLIS, \
  \"startFirst\": $UPGRADE_START_FIRST, \
  \"launchConfig\": $UPGRADE_LC, \
  \"secondaryLaunchConfigs\": $UPGRADE_SLC } }"

echo "[Upgrading $SERVICE_NAME]"
RESPONSE=$($CURL -H "Content-Type: application/json" -X POST -d "$BODY" $UPGRADE_URL)

wait4upgrade() {
  CNT=0
  STATE=""
  until [[ $STATE == "upgraded" ]]; do
    STATE=$($CURL --silent $SELF | jq -r '.state' | sed -e 's/^"//'  -e 's/"$//')
    echo "Service state: $STATE"
    if [ $((CNT++)) -gt $UPGRADE_TIMEOUT ]; then
        echo "Upgrade timed out, state: $STATE"
        exit 1
    else
        sleep 1
    fi
  done
}
wait4upgrade

FINISH_UPGRADE_URL=$($CURL $SELF | jq -r '.actions.finishupgrade' | sed -e 's/^"//'  -e 's/"$//')
echo "[Confirming upgrade via $FINISH_UPGRADE_URL]"
RESPONSE=$($CURL -X POST $FINISH_UPGRADE_URL)

echo "[Waiting for service $SERVICE_NAME to finish upgrade]"
wait4finishupgrade() {
  CNT=0
  STATE=""
  until [[ $STATE == "active" ]]; do
    STATE=$($CURL --silent $SELF | jq -r '.state' | sed -e 's/^"//'  -e 's/"$//')
    echo "Service state: $STATE"
    if [ $((CNT++)) -gt $UPGRADE_TIMEOUT ]; then
        echo "Confirm Upgrade timed out, state: $STATE"
        exit 1
    else
        sleep 1
    fi
  done
}
wait4finishupgrade

echo "[ALL DONE]"

```

**Results:** 

```
[Upgrading vote-demo-vote-app]
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3594  100  2768  100   826  84108  25098 --:--:-- --:--:-- --:--:-- 86500
[Waiting for service vote-demo-vote-app to upgrade]
Service state: upgrading
Service state: upgrading
Service state: upgrading
Service state: upgrading
Service state: upgrading
Service state: upgrading
Service state: upgrading
Service state: upgrading
Service state: upgrading
Service state: upgraded
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4149    0  4149    0     0   259k      0 --:--:-- --:--:-- --:--:--  253k
[Confirming upgrade via http://rancher-dr.lightcloudit.com:8080/v1/services/1s203/?action=finishupgrade]
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4164  100  4164    0     0   112k      0 --:--:-- --:--:-- --:--:--  116k
[Waiting for service vote-demo-vote-app to finish upgrade]
Service state: finishing-upgrade
Service state: active
[ALL DONE]

```

GUI still reports that "upgrade available"

NOTE: logs from rancher server do not report anything when using the curl API calls.

The following logs are reported when clicking on the upgrade button in the GUI

```
time="2016-08-31T17:56:54Z" level=info msg="Upgrade Stack Event Received" eventId=1060cb37-555f-423f-aa96-41f10d3a1cc0 resourceId=1e123 
time="2016-08-31T17:57:03Z" level=info msg="Stack Upgrade Event Done" eventId=1060cb37-555f-423f-aa96-41f10d3a1cc0 resourceId=1e123 
time="2016-08-31T17:57:47Z" level=info msg="Finish Upgrade Stack Event Received" eventId=9b52be29-3862-40ac-a575-2f7fe253cb75 resourceId=1e123 
time="2016-08-31T17:57:47Z" level=info msg="Finish Stack Upgrade Event Done" eventId=9b52be29-3862-40ac-a575-2f7fe253cb75 resourceId=1e123 


```

**Expected:**
GUI concurs that upgrade is completed.

**Comment by deniseschannon** [comment]
This looks like you are upgrading the stack and not necessary calling the templates of the stack to be used for upgrade. Have you tried upgrading through the UI to see what API calls are made using the developer tools? 

Our catalog/templates use our catalog-service to upgrade and look at what upgrades are available.

**Comment by jliu70** [comment]
I took another look at the UI API calls via developer tools, but from what I can see it seems to be the same calls that I'm making in the script above.   

Here's a screen grab of the developer tools output.  
I'm not a real developer, so I would appreciate it if someone could let me know if I'm missing something.

Thanks!!
![screen shot 2016-09-23 at 4 47 57 pm](https://cloud.githubusercontent.com/assets/3439337/18790070/a6c8dea4-81ad-11e6-9dce-ae5268f66495.png)

**Comment by vincent99** [comment]
You seem to be confusing two separate things here...

Stacks deployed via the catalog have an `externalId` field that records what version of the template was deployed.  When you upgrade a catalog item (by clicking the "Upgrade Available" button) the new YAML definition of the service and a new `externalId` are sent to the `upgrade` action of the **stack**.

What you are showing in your picture (and code) is upgrading an individual **service**, which does not change the version of the template we think is installed and therefore does not change the "Upgrade Available" button.

**Comment by jliu70** [comment]
Thanks.  I also think I was confused because I did not notice that there is a new "v2-beta" API which does make a reference to stacks with the action "upgrade".  

I had originally found a variation of the script online which probably worked for v1 of the API.   I upgraded to Rancher 1.2.0 and didn't notice the new API.  I recall that there were many changes announced by Darren Shepherd when he introduced the new rancher CLI back in the July 2016 meet up.

So before I close this issue, I'd like to verify that the screen shot shows the API call that I can make on the stack.   Would this be called in lieu of the old API call to upgrade the service?  Or should it be called after the service upgrade?    Thanks again for your help!

<img width="680" alt="screen shot 2016-09-23 at 10 07 08 pm" src="https://cloud.githubusercontent.com/assets/3439337/18799827/201600d0-81da-11e6-9294-56a4c7a85df6.png">

**Comment by vincent99** [comment]
This doesn't really relate to API v1 vs v2, except that stacks are called environments in v1...

To upgrade a catalog item you get the new yaml from the catalog API (`/v1-catalog`) and send that in the `upgrade`action on the stack, along with the updated `externalId` ("catalog://"+ the new template version's `id`).

You do not not call upgrade on individual services.

**Comment by jliu70** [comment]
Thanks. 

On a side note, I found this documentation which also states similar to what you mentioned. 
http://docs.rancher.com/rancher/v1.2/en/cattle/rancher-compose/upgrading/

I'll need to experiment and give your suggestions a try.  I'm not quite sure how to craft the API calls.  I'll try on Monday. 

Thanks again!

**Comment by aemneina** [comment]
closing this out.
