### ISSUE TITLE
Question: Docker 1.12 Features

### ISSUE THREAD

**Issue by cgarciae** [rancher/rancher#5861]
Hi, I used Rancher and loved how easy it is to set up a multi-host environment with load-balancing. I was curious if Rancher uses or will use the new Docker Swarm Mode capabilities introduced in `1.12`? 

https://docs.docker.com/engine/swarm/

It seems these feature could lift a huge weight out of Rancher, which could focus more on its awesome UI and monitoring capabilities now that Docker handles multi-host distribution, load balancing, etc.

**Comment by jimmyye** [comment]
see #5201

**Comment by deniseschannon** [comment]
Closing in favor of #5201
