### ISSUE TITLE
"Finish upgrade" will start an inactive service

### ISSUE THREAD

**Issue by hagr** [rancher/rancher#5864]
**Rancher Version:**
v1.1.0

**Docker Version:**
1.11.2

**OS and where are the hosts located? (cloud, bare metal, etc):**
Bare metal, Ubuntu 16.04 LTS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Create/import docker-compose.yml with a set of linked services. Untick "Start services after creating". All services are inactive.

Upgrade one of the services (e.g. volume mapping, image), and then finish the upgrade. Rancher tries to start the new container even though the service was inactive.

**Results:** 
If the container requires a linked service to be running and fails to start, the service might end up in a reboot loop. There is no way to stop the service as we're waiting for "Finish-Upgrade (In Progress)"

**Expected:**
Rancher should not try to start the service after upgrading an inactive one, or at least provide an option to stop the service while doing "Finish-Upgrade".

**Comment by deniseschannon** [comment]
Note: This is expected behavior. After any upgrade, the service is automatically started as part of the upgrade process. Otherwise, there is no way to validate if your upgraded service is working as expected.

**Comment by hagr** [comment]
Fair enough, but the only way to stop the upgrade process, if it fails to start, seems to be to delete the service.

**Comment by ddelnano** [comment]
@hagr you need to upgrade the service with the `start before stopping` option enabled.  This way if the new containers fail to start it never stops the old one.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
