### ISSUE TITLE
Stacks Will Not Deploy from Catalog - Stuck in Activating, Not Creating Services

### ISSUE THREAD

**Issue by ThatsNinja** [rancher/rancher#5868]
I don't expect that the @rancher folks would jump all over this. Mainly, I wanted to get it documented in case someone else runs across it...

**Rancher Version:**
1.1.0

**Docker Version:**
1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
RancherOS (4.2.8-ckt4-rancher)

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
3-host Rancher HA, External DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Issue:**
In our situation, operating in AWS, our issue began while making a change to a routing table associated with our VPC subnets. There was some type of error Amazon-side during the save operation which un-associated our subnets from their Internet gateway. A stack was being created at the time, and while this operation completed successfully (once we were able to get access to our EC2 instances again), all subsequent attempts to add stacks from catalog items were simply not working.

There were no errors being returned anywhere. We'd see the empty stack, sitting and spinning, reporting that it was Activating, and not creating any stacks.

Interestingly, during this time I created a Rancher Load Balancer service in one of the existing stacks, no problem. It was only creating from Catalog items that was failing.

**Workaround:** 
After some head scratching, I decided to look in on the Rancher System HA environment, and check the health of the `management` stack. It was green across the board.

Still, I hypothesized that there might be an issue in the `rancher-compose-executor` service. Upon further investigation, I discovered that the last messages in the logs for both instances (which I no longer have, as I destroyed the offending instances in the process of fixing) in the service were reporting that the service had encountered a problem calling the front-end listener for the HA cluster.

I scaled the service out, and verified that the new instances had no issue. I stopped the broken instances, scaled back down, restarted the service, and this fixed the issue. I'm thinking I might have gotten away with a simple restart.

**Expected:**
Graceful handling of this type of situation which wouldn't render the `rancher-compose-executor` inoperable.

**Comment by will-chan** [comment]
We have added service journals to 1.2.0-pre3 that should hopefully better shed light on why services don't start.

**Comment by deniseschannon** [comment]
With the new HA in 1.2, this is no longer applicable as we've refactored HA to be much simpler and just run additional arguments with the rancher-server command.

Rancher-compose-executor is a process that runs just like in a standalone single container of Ranher.
