### ISSUE TITLE
Stacks with same name being created on rancher when namespaces with same names are deleted and recreated.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#5869]
Rancher Version: v1.2.0-pre2

Steps to reproduce the the problem:
Create a k8s env with default 1.2 version.
Create a namespace with any name say "hello123".
Create service in this namespace.
This results in a stack being created with name "hello123".
Delete this namespace. (This does not result in the stack being deleted .We have this issue to tarck it -  https://github.com/rancher/rancher/issues/5508).

Create a namespace with same name "hello123".
Create service in this namespace.

This results in another stack being created with same name "hello123".

Seems like kubernetes code does not enforce all the checks that API does when creating a stack.

```
mysql> select id,name,state,created,removed,account_id from environment;
+----+------------------------+---------+---------------------+---------------------+------------+
| id | name                   | state   | created             | removed             | account_id |
+----+------------------------+---------+---------------------+---------------------+------------+
| 15 | hello123               | active  | 2016-09-01 15:11:36 | NULL                |         36 |
| 16 | hello123               | active  | 2016-09-01 15:13:02 | NULL                |         36 |
+----+------------------------+---------+---------------------+---------------------+------------+
16 rows in set (0.00 sec)
```

**Comment by wlan0** [comment]
@sangeethah This issue is fixed by https://github.com/rancher/cattle/commit/8ef32384fcfa592e011802cb49e785078e1ea8fb 

It is in v0.169.0 onwards.

**Comment by sangeethah** [comment]
@soumyalj, when you verify this issue , include the K8s version ( and template version) that was used to validate this issue since the fixes may not be available for k8s 1.3 version.

**Comment by wlan0** [comment]
Note to self: Uniqueness constraint on the environment name is not being enforced by k8s agent-event-cattle channel. This needs to be fixed.

**Comment by alena1108** [comment]
As long as https://github.com/rancher/rancher/issues/5508 is fixed, we are fine. Punting this one for now.
