### ISSUE TITLE
Activating environment, fails to start instances for services when service has dataVolumesFromService

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#587]
Server Version - V0.16.3

Steps to reproduce the problem:

Add Environment.
Add service - S1. Did not activate this service.
Add another service S2.Did not activate this service.
Added another service S3 which has dataVolumesFromService to S1.

Activate environment.

Expected Behavior:
S1 and S2 were activated first.
After this , there is an attempt made to activate S3 but it is stuck in "Activating" state forever.
There is repeated attempt made to start instances that fail with error -  "Failed to find a placement"

The 2 instances from service S2 (whose volumes need to be mounted) are placed in 2 different hosts.

**Comment by alena1108** [comment]
Generic Allocators problem. @sonchang - we should include it in our TODO for allocators - when instances/services are linked via volumesFrom (container/service) parameter, they should be placed on the same host. Today I believe its ignored even for stand alone container use case.

**Comment by alena1108** [comment]
The feature is already in master (except for the UI).

**Comment by sangeethah** [comment]
Tested with server version - v0.27.0-rc1.

We are able to create services which has dataVolumesFromLaunchConfigs linked to secondary launch config names.

Activating environment,  will result in containers from secondary launch config to be placed in the same host as container from primary launch config.
