### ISSUE TITLE
Exporting yaml for stacks should support exporting in v2 format.

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#5870]
Currently, we have support to take in v2 files, but the export yaml only displays it in v1 format.

**Comment by deniseschannon** [comment]
Without exporting in v2 format, you'll lose certain keys that are new to v2. For example, `network_mode` and `depends_on`.

**Comment by alena1108** [comment]
@deniseschannon yml export already had all params in v2 format (I believe I've changed network_mode to network on the export), just "version v2" tag was missing. Please correct me if more stuff are still displayed in "v1 way"

**Comment by soumyalj** [comment]
Tested for different keys in v2 format. They are working except for logging key which is tracked in 
https://github.com/rancher/rancher/issues/6279
