### ISSUE TITLE
Empty selection in Catalog's Category drop-down that is selectable

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#5872]
**Rancher Version:** Master 9/1

**Steps to Reproduce:**
1.  Go to Catalog page
2.  Click on Category drop-down

**Results:** Notice under the All and before the Agile, there is a blank space that is selectable.  If I click on it, it give me the rancher-bench-security catalog
![image](https://cloud.githubusercontent.com/assets/11514927/18180839/79a47ff4-703d-11e6-8afc-256f7547e96d.png)

**Expected:**  Should not be able to click on blank section of drop-down and have catalog come up

**Comment by vincent99** [comment]
This was either fixed earlier, or comes from data in an added-on catalog because I don't see it with the standard two..

**Comment by tfiduccia** [comment]
Version - 1.2.1
Verified fixed
