### ISSUE TITLE
Problem running the rancher agent in a host with no access to Internet

### ISSUE THREAD

**Issue by jesusjavierdediego** [rancher/rancher#5874]
**Rancher Version:1.0.2 (agent)

**Docker Version:1.10.x

**OS and where are the hosts located? (cloud, bare metal, etc): CentOS, VM

**Setup Details: Single node

**Environment Type: Cattle

**Steps to Reproduce: 
Push agent image to private registry. The resulting image will be <IP of registry>:5000/rancher/agent:v1.0.2
Run the agent run command (referencing the agent image in the private registry) in a VM without access to Internet, only to the private registry.

**Results:
The agent container is alive but it does not start. 
Go into the logs of the container. It tries to update to the rancher/agent:v1.0.2 image.

**Expected:
Since the image is the same one (with different name) it is expected the upgrade step was not needed.

Workaround:
By tagging the image in the host to the expected image name (rancher/agent:v1.0.2) the agent works fine again (it is the expected image name).

**Comment by aemneina** [comment]
Looks like the doc's or the process is broken, I experienced this with an air-gapped install as well.

**Comment by deniseschannon** [comment]
You need to start rancher server with an environment variable

` -e CATTLE_BOOTSTRAP_REQUIRED_IMAGE=<Private_Registry_Domain>:5000/<NAME_OF_LOCAL_RANCHER_AGENT_IMAGE>`

http://rancher.com/docs/rancher/v1.6/en/installing-rancher/installing-server/no-internet-access/#launching-rancher-server-with-private-registry
