### ISSUE TITLE
Help page is broken in multiple places

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#5877]
**Rancher Version:** 1.2.0-pre2

**Steps to Reproduce:**
1.  Go to help page

**Results:** 
1.  Announcements is spelled improperly
2.  The announcement section is broken
3.  The Forums section is broken

**Expected:**
Should not be broken

**Comment by vincent99** [comment]
The forum software changed their API and no longer have the info we need in one call.  Changed to make multiple calls.

**Comment by tfiduccia** [comment]
Version - master 9/8
Verified fixed
