### ISSUE TITLE
Removing a Service that is never started doesn't update stack state

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#5884]
**Rancher Version:** v1.2.0

**Steps to Reproduce:**
1.  Import a stack with 1 service and uncheck "Start services after creating"
2.  Start the service so Stack is "Active"
3.  Clone the Service (stack will now be unhealthy because Service is not started)
4.  Remove the Service that was never started

**Results:** The Stack still says Unhealthy even thou the only service in there is active and running fine.

**Expected:**  Stack should switch back to Active once Never Started Service is removed.

**Comment by alena1108** [comment]
Resolved with 8b5462a868bfab136d9ec88807b14afee1961794

**Comment by tfiduccia** [comment]
Version - v1.2
Verified fixed
