### ISSUE TITLE
Service with sidekick creates and shows weird scheduling rule

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#5886]
**Rancher Version:** master 9/2

**Steps to Reproduce:**
1.  Create a service with a sidekick
2.  Go to the service container details and click on Scheduling tab
3.  Go to the sidekicks' container details and click on scheduling tab

**Results:** Says "No Scheduling rules" but there is a weird looking rule showing up
![image](https://cloud.githubusercontent.com/assets/11514927/18217592/8cf30d20-7112-11e6-93da-d5475bd3f5ed.png)

**Expected:** NO strange looking rule that I didn't enter?

**Comment by vincent99** [comment]
This is put in by Cattle and is how the sidekick is always scheduled next to the primary container.
