### ISSUE TITLE
Can't add a Amazon host

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#5887]
**Rancher Version:** master 9/2

**Steps to Reproduce:**
1.  Try to add amazon host

**Results:**  Error saying - TypeError: Cannot read property 'name' of undefined

**Expected:** No error and should be able to create amazon hosts

**Comment by vincent99** [comment]
Fixed issue with /v2-beta/proxy

**Comment by tfiduccia** [comment]
Version - v1.2.0-pre3-rc1
Verified fixed
