### ISSUE TITLE
Can't create kubernetes stacks from catalog or Swarm Catalog

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#5888]
**Rancher Version:** master 9/2

**Steps to Reproduce:**
1.  Build a kubernetes environment
2.  Try to build wordpress from catalog (or any other catalog item)
3.  Build a swarm enviornment
4.  Try to build wordpress from catalog

**Results:** Stack/Project get created but no services or anything else is created

**Expected:**  Should work

**Comment by ibuildthecloud** [comment]
https://github.com/rancher/cattle/pull/1973

**Comment by tfiduccia** [comment]
Version - v1.2.0-pre3-rc2
