### ISSUE TITLE
Feature - Provide an external endpoint to fetch HA bootstrap script

### ISSUE THREAD

**Issue by damniamgood** [rancher/rancher#5889]
It would be really helpful to download HA script from an external endpoint (without any authentication) via REST call. 
## 2 step process:
1. Send HTTP request to some endpoint to get HA script. Request should have following information
   -   RancherServer version 
   -   RancherAgent version (not sure if this is needed)
2. As response, it provides a template bash script which requires  arguments (or as environment variable) needed to setup HA. Eg. cert, registrationURL etc..
### Sample REQUEST

GET /rancher-ha/v1?server_version=1.2.0
HOST: api.rancher.io

**Comment by vincent99** [comment]
POST /v1/haconfigs/haconfig?action=createscript
```json
{
  "hostRegistrationUrl":"https://asdf",
  "clusterSize":"3",
  "httpsPort":"443",
  "httpPort":"80",
  "swarmPort":"2376",
  "ppHttpsPort":"444",
  "ppHttpPort":"81",
  "redisPort":"6379",
  "zookeeperClientPort":"2181",
  "zookeeperQuorumPort":"2888",
  "zookeeperLeaderPort":"3888"
}
```

**Comment by damniamgood** [comment]
Hey @vincent99 
I was looking for a shared/open URL like https://api.rancher.io/v1/haconfigs/haconfig?action=createscript&server_version=1.1.0 This would help the community to have one source of truth and not rely on custom/local setup.

**Comment by damniamgood** [comment]
Closing this issue as it's not required anymore. Bootstrapping rancher server cluster is much simpler now
