### ISSUE TITLE
When "publish all ports" is used for services , this flag is not honored for the deployed containers. Also docker-compose.yml/rancher.yml does not have details on this

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#589]
Server Version - V0.16.3

Create Environment.
Create service with "publish all ports"  enabled with unmanaged network.
When service is activated , containers that get launched do not have random ports exposed on the host.

Since docker-compose does not extend support for "publish all ports" , should this information be recorded in rancher.yml ?

**Comment by vincent99** [comment]
This option should be hidden for services.

**Comment by sangeethah** [comment]
We should not allow for "NETWORK" to be anything other than "managed" for services.

When in "managed" network , "publish all ports" option should not be presented to the user , since we do not support this.

**Comment by vincent99** [comment]
There's nothing wrong with other networkModes on services that I know of, other than `=container` doesn't work (and is hidden in the UI).  

Publish all ports is just completely removed in UI master.  Per @ibuildthecloud:
> can you just drop "Publish all ports to random host port' from the UI. it doesn't work, but it is also stupid

**Comment by sangeethah** [comment]
If you have other network modes , LB/DNS services will not work.

**Comment by vincent99** [comment]
But regular loadbalancers don't balance regular containers in other networkModes either...

**Comment by sangeethah** [comment]
I have a bug logged for LB on  regular containers - #506

**Comment by will-chan** [comment]
Can just leave it available for now. We can just explain that using any modes other than rancher's managed network prevents you from using any rancher features like LB, DNS, etc.

**Comment by vincent99** [comment]
:+1: .  Compose can create `--net=host`, etc containers, and so should we.  #506 is not allowed through the UI any more, though it is still possible through the API apparently.

**Comment by vincent99** [comment]
Publish all ports checkbox was removed from the UI a while ago
