### ISSUE TITLE
Deleted kuberentes stacks don't get removed from Stack page until refresh

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#5890]
**Rancher Version:** master 9/2

**Steps to Reproduce:**
1.  Add a kubernetes catalog item (wordpress is good)
2.  Delete the stack and wait

**Results:** the stack doesn't get removed from the page until you refresh the browser

**Expected:**  Should remove on delete

**Comment by will-chan** [comment]
Is this UI or backend?

**Comment by tfiduccia** [comment]
Probably backend missing a simple change event.

**Comment by tfiduccia** [comment]
Version - master 11/19
Verified fixed
