### ISSUE TITLE
Drop downs fail to show in chrome / chromium for touch screen laptops

### ISSUE THREAD

**Issue by kbrownlees** [rancher/rancher#5891]
Rancher Version: 1.2.0-pre2
Docker Version: 1.11.2

Ubuntu 15.10 / VPS host
Single node internal DB

Chromium version 52.0.2743.116-1
Chrome version 53.0.2785.92-1

After upgrading to 1.2.0-pre2 from 1.1.2 the drop downs in the UI (environemnt / stacks / infrastructure) no longer function in Chrome or Chromium, Firefox works as expected.

Here is a screenshot of me hovering over the environment menu item (chromium):
![screenshot_20160904_134521](https://cloud.githubusercontent.com/assets/641520/18228520/f8edaaaa-72a5-11e6-8359-b2407df0d32c.png)

**Comment by pwFoo** [comment]
Testes with RancherOS host and 1.2.0-pre2. Same problem. Downgrade rancher server solved the dropdown problem.

**Comment by pwFoo** [comment]
Same with pre3

**Comment by vincent99** [comment]
We all use Chrome and have not seen this... Is there anything in the browser console?

**Comment by rossigee** [comment]
I get the same as pwFoo since upgrading to 1.2 series, and have had to use Firefox as a workaround. It's reproducible in Chromium...

Version 52.0.2743.116 Built on Ubuntu , running on Ubuntu 16.04 (64-bit)

**Comment by pwFoo** [comment]
Checked the console. Just see the websocket connect successfully... No errors. No dropdowns.

**Comment by kbrownlees** [comment]
Can confirm I still see this on v1.2.0-pre3-rc1 with a fresh database. Same as @pwFoo - the only console messages are about the websocket.

What version of chrome @pwFoo?

**Comment by pwFoo** [comment]
Tested with Chrome 52.0.2743.116 m (64-bit) and  53.0.2785.101 m (64-bit) @ Win10

**Comment by hadri3n** [comment]
Same error with Chrome 53.0.2785.101 (64-bit) on ubuntu 15.10 (no dropsdown, no error message in the console)

**Comment by tfiduccia** [comment]
Tested with official Chrome Version 53.0.2785.116 (64-bit) and I'm seeing the drop-downs.

**Comment by blueo** [comment]
I'm pretty sure this is to do with having a touch screen enabled desktop. I'm using chrome 53.0.2785.116 m and I can see the dropdown when hovering. But in Firefox it works. The difference is that chrome detects my touchscreen and tags the body element with the 'touch' class where as firefox does not. 

the `ui/app/mixins/hover-dropdowns.js` on line 21 looks for the touch class and then basically thinks chrome is a large tablet. Maybe there needs to be another breakpoint to detect a desktop vs tablet?

**Comment by rossigee** [comment]
I can concur that I am having the problem when running a touchscreen enabled laptop, but it works fine on another machine with an ordinary screen.

**Comment by kbrownlees** [comment]
I have a touch screen laptop as well.

If you are like me and don't use the touch screen much you can force chrome to disable touch events in chrome://flags ('Enable touch events' -> disabled). Just tested it and the drop downs work again.

**Comment by vincent99** [comment]
Thanks @blueo @rossigee @kbrownlees, that was the missing piece of info and why nobody with a normal laptop/VM could reproduce.

**Comment by tfiduccia** [comment]
Version - master 11/10 UI - 1.2.21
@westlywright 
The drop-down for environment no longer works on the iphone/ipad.  When I first get into the app, it takes me to Manage environment, and if I try to select the environment drop-down it just keeps taking me to Manage environment.

**Comment by tfiduccia** [comment]
Version - master 11/15
Still going to manage environment instead of User stack when starting or selecting a environment from the drop-down.

**Comment by vincent99** [comment]
@tfiduccia That is a bug in iOS9 Safari that is causing some of the API calls made on load to fail somewhat randomly.  Triggered by a change since 1.1.x to make multiple calls in parallel on initial load instead of 1 at a time.

When one of them fails you're currently sent to the Environments page (which is a separate problem, it should really be sending you to the error screen here...)

Added in hack to limit loading to 1 request at a time for Safari on iOS <= 9.

**Comment by tfiduccia** [comment]
Version - master 11/18
Verified fixed
