### ISSUE TITLE
Health Check > When Unhealthy > Re-Start 

### ISSUE THREAD

**Issue by PicoCreator** [rancher/rancher#5892]
"Re-Start" as an in between of "Take no action" and "Re-create"

Subsequently, perhaps even a more complex "Re-start [X] times, then Re-create when at least [Y] is healthy".

These is actually my instance debugging steps, for several installation where re-create, is a less then ideal option. Especially if it re-downloads its "cluster data" in GB's

A mock-up is as bellow

![rancher-restart-option](https://cloud.githubusercontent.com/assets/17175484/18232306/88b67f00-72ff-11e6-89ab-6944c0769d04.jpg)

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
