### ISSUE TITLE
rancher kubernetes etcd issue & add host status wrong

### ISSUE THREAD

**Issue by nenggangpan** [rancher/rancher#5894]
**Rancher Version: v1.2.0-pre1

**Docker Version: 1.2.1

**OS and where are the hosts located? Ubuntu 14.04/Tencent cloud

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single node rancher, internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Kubernetes

**Steps to Reproduce:**
Add hosts in kubernetes environment.
**Results:** 
3 etcd container. containers with name Kubernetes_etcd_3 status is 'Initializing'. rancher UI shows 5 hosts added successfully in the environment, however, only 3 hosts can be listed with command 'kubectl get node', logs from it:
         Get http://Kubernetes_etcd_2:2379/health: net/http: request canceled while waiting for  connection (Client.Timeout exceeded while awaiting headers)
and in 'Execute Shell', I run 'ping Kubernetes_etcd_2', seems the dns is correct, but the ip can't be reached, however, ping 'Kubernetes_etcd_1' is correct. 
**Expected:**
all three etcd instances run correctly

**Comment by aemneina** [comment]
@nenggangpan can you try this with the latest... this should work now. Please reopen if you encounter the same issue.
