### ISSUE TITLE
Add new host ubuntu 16.04 ami fails

### ISSUE THREAD

**Issue by coozy** [rancher/rancher#5897]
**Rancher Version:**
Rancher	v1.1.3
Cattle	v0.165.8.1
User Interface	v1.1.12
Rancher Compose	v0.8.6

**Docker Version:**
Trying to provision an EC2 node

**OS and where are the hosts located? (cloud, bare metal, etc):**
Trying to provision ami-4f680658 us-east-1 (Ubuntu 16.0.4)

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**
Add a host -> ec2 -> us-east-1 -> ami-4f680658

**Results:** 

Fails with "Error running provisioning: error installing docker:"

**Expected:**
A new host running ubuntu 16.0.4 and docker 1.12

**Comment by vincent99** [comment]
The default docker is 1.10, which there are not Xenial packages for..  choose 1.11 (or in Rancher 1.2.0-pre2+, 1.12) from the docker install url under advanced options.

**Comment by coozy** [comment]
Thanks.. that worked :)
Except that I get a systemd file that is different from the one I get if I install it by hand:
```
add  - deb https://apt.dockerproject.org/repo ubuntu-xenial main to /etc/apt/sources.list.d/docker.list
apt-get update
apt-get install docker-engine
```
Specifically, If I install it by hand: Systemd file gets installed in: /lib/systemd/system/docker.service and doesn't have MountFlags set

Through Rancher - systemd file in /etc/systemd/system/docker.service has the MountFlags set

**Comment by vincent99** [comment]
The releases.rancher.com/install/1.{11,12}.sh script is basically the same as https://get.docker.com, plus a few tweaks to pin to a particular release (as theirs always installs whatever latest is this second).

It appears we do not have a couple of their more recent changes to it, and should probably update the 1.12 one.

**Comment by wlan0** [comment]
@vincent99 I created a new script - https://gist.githubusercontent.com/wlan0/10ebc0997e71ac436830ed1635745553/raw/9f803f08271d0f7bb3b11e9f219467574b2d27e2/gistfile1.txt

**Comment by soumyalj** [comment]
Tested with v1.2.0-pre4-rc5. I was able to :
1. Add a host -> ec2 -> us-east-1 -> ami-4f680658 
The host was added successfully with Docker 1.12.2
Container creation worked fine too.
