### ISSUE TITLE
something wrong while using rancher server with ssl connection 

### ISSUE THREAD

**Issue by nenggangpan** [rancher/rancher#5899]
**Rancher Version: v1.2.0-pre1

**Docker Version: 1.2.1

**OS and where are the hosts located? Ubuntu 14.04/Tencent cloud

Setup Details: single node rancher, internal DB, ssl connection(nginx+rancher server)

Environment Type: (Cattle/Kubernetes/Swarm/Mesos) Cattle

Steps to Reproduce:
    After setup ssl connection with self signed certificate, deploy a busybox statck in cattle. 
Results: 
    'Execute Shell' can't launch successfully, always show "Connecting", 'View Logs' always show "disconnected", and the resource monitoring of CPU, Memory, Network, Storage always 'Connecting'.
Expected:
    Everything works well

**Comment by aemneina** [comment]
@nenggangpan can you try this with the latest 1.2.0? I believe there have been a lot of changes going into 1.2.0. Please reopen if you can reproduce.
