### ISSUE TITLE
Wrong convoy.sock path

### ISSUE THREAD

**Issue by danipolo** [rancher/rancher#5900]
**Rancher Version:**
Rancher v1.1.3

**Docker Version:**
Docker version 1.12.1, build 23cf638

**OS and where are the hosts located? (cloud, bare metal, etc):**

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node, internal DB. 

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle v0.165.8.1

**Steps to Reproduce:**
I followed the guide you published to create a NFS and deploy CONVOY-NFS in the catalog with a fresh install (Ubuntu on the server and RancherOS in the host).

All works as expected on the guide (I'm able to create volumes and it works). When I try to shell acces the convoy-nfs container and do: `convoy list` I get the following response:

```
root@8d252f06877f:/# convoy list
ERRO[0000] Get http:///var/run/convoy/convoy.sock/v1/volumes/list: dial unix /va
r/run/convoy/convoy.sock: no such file or directory
{
        "Error": "Get http:///var/run/convoy/convoy.sock/v1/volumes/list: dial u
nix /var/run/convoy/convoy.sock: no such file or directory"
}
```

I checked the logs and found the socket is in:

`6/9/2016 13:42:16time="2016-09-06T11:42:16Z" level=info msg="Socket file: /host/var/run/convoy-convoy-nfs.sock"`

Look at the **/host** before the correct path.

**Results:** 

I can't do backups or snapshots. I know I can specify the socket with `convoy -s /host/var/run/convoy-convoy-nfs.sock list` but it's this correct? Maybe this is causing less functionalities on the UI?

**Expected:**

I can make snapshots and backups of my NFS server on the Rancher UI.

**Comment by tfiduccia** [comment]
Reproduced this issue in master.

**Comment by chrisfelix82** [comment]
same issue here

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
