### ISSUE TITLE
Haproxy config is reloaded too often for k8s ingress resource

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#5901]
K8s ingress controller sends service links updates to the corresponding Rancher LB regardless whether service links set was changed or not. The update should be sent only when there were changes in the service links set.

**Comment by alena1108** [comment]
This issue should be fixed for both 1.2 and 1.3 k8s templates

**Comment by soumyalj** [comment]
Verified with v1.1.4-rc1. With a change in port number in the ingress, there is LB recreation and the ingress logs display "need to recreate"
With a change in service, the logs show "9/14/2016 4:56:37 PMtime="2016-09-14T23:56:37Z" level=info msg="Resetting service links"

**Comment by sangeethah** [comment]
@soumyalj , can you make sure that when ingress update is done with no changes , that there is no Haproxy config reloads happening ?

**Comment by soumyalj** [comment]
Verified with v1.1.4-rc1. Using the same ingress file and doing an update using 
" kubectl replace ing --filename ingress.yml", there is no haproxy config reload. There is no ingress controller log w.r.t ingress update
Scaling up/down the replication controller results in haproxy reload 
Deleting an instance of the pod, will result in haproxy config reload
