### ISSUE TITLE
Question: How do I specify shm-size?

### ISSUE THREAD

**Issue by coozy** [rancher/rancher#5905]
**Rancher Version:**
Rancher	v1.1.3
Cattle	v0.165.8.1
User Interface	v1.1.12
Rancher Compose	v0.8.6
**Docker Version:**
1.12.1
**Question **
 How do I do the equivalent of docker run --shm-size when I launch a container from Rancher UI

Thanks

**Comment by deniseschannon** [comment]
It isn't supported yet.

https://github.com/rancher/rancher/issues/4708

**Comment by bestksw** [comment]
I solved it by mounting from /dev/shm of host to /dev/shm of target container.
