### ISSUE TITLE
[rancher-dns] "go get github.com/rancher/external-dns" fails

### ISSUE THREAD

**Issue by mathuin** [rancher/rancher#5907]
**Rancher Version:** v1.1.2

**Docker Version:** v1.12.1

**OS and where are the hosts located? (cloud, bare metal, etc):** Ubuntu, bare metal

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single node Rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:**
Run the following command on a system with Go installed:
`go get github.com/rancher/external-dns`

**Results:** 
```
# github.com/rancher/external-dns/metadata
go/src/github.com/rancher/external-dns/metadata/metadata.go:26: m.GetSelfStack undefined (type *metadata.Client is pointer to interface, not interface)
go/src/github.com/rancher/external-dns/metadata/metadata.go:43: cannot use m (type metadata.Client) as type *metadata.Client in argument to getEnvironmentName:
	*metadata.Client is pointer to interface, not interface
go/src/github.com/rancher/external-dns/metadata/metadata.go:49: cannot use m (type metadata.Client) as type *metadata.Client in field value:
	*metadata.Client is pointer to interface, not interface
go/src/github.com/rancher/external-dns/metadata/metadata.go:55: m.MetadataClient.GetVersion undefined (type *metadata.Client is pointer to interface, not interface)
go/src/github.com/rancher/external-dns/metadata/metadata.go:55: not enough arguments to return
go/src/github.com/rancher/external-dns/metadata/metadata.go:68: m.MetadataClient.GetContainers undefined (type *metadata.Client is pointer to interface, not interface)
go/src/github.com/rancher/external-dns/metadata/metadata.go:92: m.MetadataClient.GetHost undefined (type *metadata.Client is pointer to interface, not interface)
```

**Expected:**
I expected no errors.

**Comment by vincent99** [comment]
Do you have an outdated go-rancher-metadata installed?

```bash
mercury:rancher vincent$ git clone https://github.com/rancher/external-dns
Cloning into 'external-dns'...
remote: Counting objects: 1168, done.
remote: Total 1168 (delta 0), reused 0 (delta 0), pack-reused 1168
Receiving objects: 100% (1168/1168), 670.42 KiB | 435.00 KiB/s, done.
Resolving deltas: 100% (325/325), done.
Checking connectivity... done.
mercury:rancher vincent$ cd external-dns
mercury:external-dns vincent$ godep go build
mercury:external-dns vincent$ ./external-dns -h
INFO[0000] Starting Rancher External DNS service
Usage of ./external-dns:
  -debug
       	Debug
  -log string
       	Log file
  -provider string
       	External provider name (default "route53")
mercury:external-dns vincent$
```

**Comment by mathuin** [comment]
Interesting.  The checkout of `go-rancher-metadata` has as its most recent commit `6d9307f` which is indeed one step behind.  When I am in that checkout and try to pull from master, I am told that it is up to date.  The remote is `https://github.com/rancher/go-rancher-metadata`.  I removed all Rancher projects from my Go path, then reran the `go get` command, and got the same failure, and the same checkout of that project.

What's *really* interesting is when I make a new checkout of that project -- using that exact remote --outside my Go path.  It has the correct value for master.

What happens when you run `go get`?

**Comment by mathuin** [comment]
I figured it out.  The godeps stuff for the other repository was not updated in this one, causing the wrong checkout to be made.
