### ISSUE TITLE
Started-once service detail page tries to continually get container stats

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#5908]
**Rancher Version:** master 9/6

**Steps to Reproduce:**
1.  Create a service with the started-once flag set on
2.  Wait for service to get to started-once state (or stop service to get it to this state)
3.  Go to details page

**Results:** Notice using the dev tools the container status is continually trying to pull

**Expected:**  Should not try and pull stats for started-once container.

**Comment by vincent99** [comment]
I think this was fixed by the new host agent, and the UI now shows `n/a` for containers where stats aren't available.

**Comment by tfiduccia** [comment]
Version - master 10/20
Verified fixed
