### ISSUE TITLE
Join Kubernetes environment using LoadBalancer (HA rancher) makes nodes talk using public ip

### ISSUE THREAD

**Issue by ls-yann-david** [rancher/rancher#5909]
**Rancher Version:**
1.1.3

**Docker Version:**
1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
Cloud AWS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
3 nodes ha rancher with external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
- Start a new Kubernetes environment
- Add custom host with command `docker run blablabla https://XXXXX/v1/scriptsBLABLABLA`

**Results:** 
Host is joined to the rancher environment with Public IP and use the Public IP for Kubernetes internal communication

**Expected:**
I would have expected Kubernetes nodes to join the environment but use their private IP for internal communications.

Using their public ip is not a big deal but there's no nice way of allowing traffic between nodes as when using private ip you can limit the subnet. So I ended up using `CATTLE_AGENT_IP` when starting the agent on the Kubernetes nodes.

Ref: https://forums.rancher.com/t/kubernetes-environment/3860/1

**Comment by aemneina** [comment]
using CATTLE_AGENT_IP is the way to go here. closing issue.
