### ISSUE TITLE
Include certs in new hosts via API ( rancheros )

### ISSUE THREAD

**Issue by guzmo** [rancher/rancher#5912]
We use a private registry and would like to add certs to our new hosts we add to Rancher environments. Is it possible to add this via a cloud-config when booting up the host? How are we supposed to add the cloud-config via the api when creating new hosts?
Or should we build our own rancheros.iso with builtin certs? In that case how to do that? I looked at rancheros code and I've tried adding it to Dockfiler.dapper but it has not effect.
Currently we are using a boot2docker.iso which we can build with certs included but we would rather like to use rancheros.

Quick answer is much appreciated!

/ Andreas

**Comment by joshwget** [comment]
Have you tried out the docs on [private registries](http://docs.rancher.com/os/configuration/private-registries/)?

**Comment by guzmo** [comment]
I would like that but how do we send the cloud-config via the api when creating hosts from VSphere? And its not even possible to use Rancheros when using the VSphere engine. I've put a question on docker-machine about this but it seems the only problem is that the username and password is hardcoded so if I could change that in a cloud-config to docker/tcuser, rancheros would work.

**Comment by joshwget** [comment]
It doesn't look like Docker Machine supports passing userdata for vSphere. I think your best bet is to provision RancherOS instances without Docker Machine and then add the instances to your Rancher environment.

**Comment by guzmo** [comment]
Yepp, thats one possibility but I rather not create them outside with scripts, and if I do I have to cleanup after myself as well. Rancher will not delete machines Rancher hasn't created. We will have ALOT of environments and if machines stops to get erased we will have some problems :P For now I solved it with a compose file that points to an inhouse Dockerfile that polls a script to get our certificates but a cloud-config would be sweet.

**Comment by deniseschannon** [comment]
Since the Rancher UI calls a Docker Machine command to create hosts, the cloud-config won't help you until Docker Machine supports that ability.  I'll close this issue as it's a Docker Machine issue.

**Comment by aemneina** [comment]
@guzmo this is an interesting problem. You could boot your vsphere vm's and attach an ISO containing an image of your cloud init. See [here](https://cloudinit.readthedocs.io/en/latest/topics/datasources.html#vsphere) but using docker-machine, I dont believe docker-machine is rich enough yet to support this where would could have an automated solution end-to-end.

**Comment by guzmo** [comment]
Ye I've had thoughts of building our own rancheros image with cloud-config included and changed username/password. Someone done that?
