### ISSUE TITLE
[external-dns] rfc2136

### ISSUE THREAD

**Issue by npjonath** [rancher/rancher#5914]
**Rancher Version:**
v1.2.0-pre2

**Docker Version:**
 10.12.1

**OS and where are the hosts located?**
 VMWare ESXi on Ubuntu 16.04.1 LTS (4.4.0-36-generic)

**Setup Details:**
4 nodes, external db on dedicated mysql ubuntu host, running convoy-nfs and gogs and dnsupdate-rfc2136 (0.5.0), DNS hosted on Mac OS 10.11.6 via OS X Server DNS

**Environment Type: Cattle**

**Steps to Reproduce:**
all my services is running well, but still not get dynamic service discovery bind to my DNS. So I decided to launch dnsupdate-rfc2136 because can't use zone53 or other external service.

```
RFC2136_HOST = prod.my_server_dns_running_on_os_X.com
RFC2136_PORT = 53
RFC2136_TSIG_KEYNAME = rndc-key
RFC2136_TSIG_SECRET= xKn9XX6mXi6XsklAK+DZiA==
ROOT_DOMAIN = subdomain.mydomain.com
TTL = 299
```

I would like to get my services like : service.stack.env.subdomain.mydomain.com

**Results:** 

```
07/09/2016 16:38:59time="2016-09-07T14:38:59Z" level=info msg="Adding dns record: {mysql.gogs.default.subdomain.mydomain.com. [192.168.100.157] A 10800}"
07/09/2016 16:38:59time="2016-09-07T14:38:59Z" level=error msg="Failed to add DNS record to provider {mysql.gogs.default.subdomain.mydomain.com. [192.168.100.157] A 10800}: RFC2136 query failed: Bad return code: REFUSED"
07/09/2016 16:38:59time="2016-09-07T14:38:59Z" level=info msg="Adding dns record: {gogs.gogs.default.subdomain.mydomain.com. [192.168.100.154] A 10800}"
07/09/2016 16:38:59time="2016-09-07T14:38:59Z" level=error msg="Failed to add DNS record to provider {gogs.gogs.default.subdomain.mydomain.com. [192.168.100.154] A 10800}: RFC2136 query failed: Bad return code: REFUSED"
```

**Expected:**
The provider refused my query, but I'm not sure that the problem is comming from the OS X Server because my firewall (Pfsense) is actually well updating my OS X Server DNS (for other purpose I need my firewall to update DNS too).

I double check information about TSIG : 

```
key "rndc-key" {
    algorithm hmac-md5;    // <-- I suspect that the problem is comming from the algorithm...
    secret "xKn9XX6mXi6XsklAK+DZiA==";
};
```

**Comment by digitalLumberjack** [comment]
Hi, did you check that both client and server have the same time ?

**Comment by npjonath** [comment]
I'm currently using NTP server to sync my OS X Server. 
Same for docker environment

**Comment by digitalLumberjack** [comment]
Could you try to make a manual update with nsupdate? 
Could you try to get a bind9 container running from the community catalog and plug your rfc2136 container on it? 
Could you try to reference the dns server with the ip and not the FQDN?

**Comment by npjonath** [comment]
> Could you try to make a manual update with nsupdate? 

Done on all my host. No change. All host was already ntp sync to 0.fr.pool.ntp.org

> Could you try to get a bind9 container running from the community catalog and plug your rfc2136 container on it?

Yes it works if I set like this : `RFC2136_TSIG_SECRET=H1Pl33tksEAXbEHq9rEfsVqxS7cCm8ie2W2Aa6UYTIGEGtXuhVFRGaIkjd6B`

If I try with the key given by my OS X Server on the BIND9 container then it's not working anymore. `RFC2136_TSIG_SECRET=xKn9XX6mXi6XsklAK+DZiA==`

> Could you try to reference the dns server with the ip and not the FQDN?

No change using IP or FQDN. same output. I try to ping `prod.my_server_dns_running_on_os_X.com ` from my container. It's working without problems. the host is reacheable.

**Comment by digitalLumberjack** [comment]
Hi, i meant nsupdate http://linux.die.net/man/8/nsupdate
That way you will be sure it come from the server configuration or from the container one.

**Comment by janeczku** [comment]
@npjonath If you still having this issue, please post the result of doing a manual update using nsupdate utility on one of your nodes as suggested by @digitalLumberjack. There might also be some information in the OS X Server logs on why it refused the update request.

**Comment by aemneina** [comment]
@npjonath please reopen with new info.
