### ISSUE TITLE
Failed to register the host with Rancher

### ISSUE THREAD

**Issue by serv** [rancher/rancher#5915]
**Rancher Version:**
v1.1.3

**Docker Version:**
v1.1.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
Mac OSX 10.11.6 Local machine

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
None. Just docker.

**Steps to Reproduce:**
1. $ git clone https://github.com/rancher/rancher.git
2. $ cd rancher
3. $ docker run -d --restart=always -p 8080:8080 rancher/server
4. Go to localhost:8080
5. On "Adding your first host", Click on Add Host
6. On "Custom" tab, copy step 5:
`sudo docker run -d --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.0.2 http://localhost:8080/v1/projects/1a5/scripts/0A8F9C5022B9E31A1B54:1473274800000:HP1iZa94EwdJMFCNYM5Erlw9ig`
7. Run it.

**Results:** 
```
$ sudo docker run -d --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.0.2 http://localhost:8080/v1/scripts/313757F94E51711D2ACF:1473271200000:IItuw8awr69IebBZEIZr0wjeM8
Password:
Unable to find image 'rancher/agent:v1.0.2' locally
v1.0.2: Pulling from rancher/agent
5a132a7e7af1: Already exists
fd2731e4c50c: Already exists
28a2f68d1120: Already exists
a3ed95caeb02: Already exists
7fa4fac65171: Pull complete
33de63de5fdb: Pull complete
d00b3b942272: Pull complete
Digest: sha256:b0b532d1e891534779d0eb1a01a5717ebfff9ac024db4412ead87d834ba92544
Status: Downloaded newer image for rancher/agent:v1.0.2
963c83d344e5fb28fd826860e15bcf7d34674ec5815b432cb6037984cfbb4c6a
docker: Error response from daemon: Mounts denied:
The path /var/lib/rancher
is not shared from OS X and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.
..
```

**Expected:**
It should add a new host to Rancher

**Comment by serv** [comment]
I needed to use actual public ip address rather than `localhost`
This should be made more obvious during host addition process in the rancher app itself.

**Comment by robertcsakany** [comment]
I have the same problem. What was your solution? I've tried some mount magics, but it haven't worked.

**Comment by serv** [comment]
@robertcsakany Here are two things I did.

1. Use actual public IP address rather than `localhost`. Read [Add Hosts](http://docs.rancher.com/rancher/v1.2/en/quick-start-guide/#add-hosts) why this should be done.
2. In the command you have to run, change from `-v /var/lib/rancher:/var/lib/rancher` to `-v /repository_where_rancher_is_stored:/var/lib/rancher`

**Comment by blackbelt-oss** [comment]
Thank you. The custom directory makes sense.

**Comment by robertcsakany** [comment]
Thank you. The custom directory makes sense.

**Comment by wanghaisheng** [comment]
@serv  what do you mean by repository_where_rancher_is_stored ?rancher source code or mysql data ?

**Comment by serv** [comment]
@wanghaisheng Rancher source code that you cloned from this repo

**Comment by wanghaisheng** [comment]
@serv  are u saying if i want to run a rancher agent on physical machine or virtual machine ,i need to clone the source code and point to this directory in the "sudo docker run -d --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.0.2 http://localhost:8080/v1/scripts/41378FF43526C55B72AD:1474819200000:qyh6fdvTlecx9ALCCU2M0FZVnyo"

**Comment by serv** [comment]
Yes, I believe so. At least that's what I've done to make it work

**Comment by wanghaisheng** [comment]
@serv what about " http://localhost:8080/v1/scripts/41378FF43526C55B72AD:1474819200000:qyh6fdvTlecx9ALCCU2M0FZVnyo" should i change localhost to host ip where rancher server setup ?

**Comment by serv** [comment]
Ya, don't use localhost. Use explicit IP address.

**Comment by ufukomer** [comment]
Btw, does anyone know how to choose public IP (CATTLE_AGENT ip value) in here. Because when I create it randomly (something like 172.0.2.1) _load balancer_ can not redirect to the application via this IP address.

```
docker run -e CATTLE_AGENT_IP=172.17.0.3 -d --privileged -v /var/run/docker.sock:/var/run/docker.sock rancher/agent:v0.7.9 http://172.17.0.3:8080/v1/scripts/DB121CFBA836F9493653:1434085200000:2ZOwUMd6fIzz44efikGhBP1veo
```

**Comment by ununseptium** [comment]
As already told, you've to choose an actual "public" ip address of your system to make this work. If you just type a random IP in there it's obvious why it cannot redirect to the application.

Anyhow...

I still have the exact same issue as the person who created this very issue. The only difference is that i used the docker image to create the management server. So i do not have Sourcecode which i could and should (cmon' this is kinda super-weird) use for the volume mount.

Any advice?

**Comment by flaccid** [comment]
1. Goto your Rancher env, Hosts | Add Host, select Custom
2. Copy the command, replace the `/var/lib/rancher` mount to `-v /private/var/lib/rancher:/var/lib/rancher` and `sudo mkdir -p /var/lib/rancher`
3. Add `/private/var/lib` to Docker -> Preferences... -> File Sharing
4. Run the custom command in terminal to connect the agent

Should do the trick!

**Comment by perryprog** [comment]
@flaccid hate to necro, but I have the same problem as OP. I replaced `/var/lib/rancher` with `/private/var/lib/rancher` and now I get the error:
```
docker: Error response from daemon: error while creating mount source path '/private/var/lib/rancher': mkdir /private/var/lib/rancher: permission denied.
```
I assume this has something to do with `sudo mkdir -p /var/lib/rancher` but I'm not sure where to put this.

**Comment by cpoole** [comment]
@perryprog I ran `sudo mkdir -p /private/var/lib/rancher` and it worked

**Comment by perryprog** [comment]
@cpoole After running that, I get an error from the container that starts:
```
INFO: Running Agent Registration Process, CATTLE_URL=http://192.168.65.2:8080/v1
INFO: Attempting to connect to: http://192.168.65.2:8080/v1
INFO: http://192.168.65.2:8080/v1 is accessible
INFO: Inspecting host capabilities
INFO: Boot2Docker: false
INFO: Host writable: true
INFO: Token: xxxxxxxx
INFO: Running registration
Traceback (most recent call last):
  File "./register.py", line 11, in <module>
    secret_key=os.environ['CATTLE_REGISTRATION_SECRET_KEY'])
  File "/usr/local/lib/python2.7/dist-packages/cattle.py", line 45, in from_env
    return gdapi.from_env(prefix=prefix, factory=Client, **kw)
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 613, in from_env
    return _from_env(prefix=prefix, factory=factory, **args)
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 632, in _from_env
    return factory(**result)
  File "/usr/local/lib/python2.7/dist-packages/cattle.py", line 12, in __init__
    super(Client, self).__init__(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 197, in __init__
    self._load_schemas()
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 315, in _load_schemas
    response = self._get_response(self._url)
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 264, in _get_response
    headers=self._headers)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /v1 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fea8e0df850>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

Mostly new to docker and brand new to Rancher.

My setup was: 
- run `sudo docker run -d --restart=unless-stopped -p 8080:8080 rancher/server`
- open [localhost:8080](localhost:8080)
- Enable access control (local)
- Add custom host with an ip of `192.168.*.*` (I also tried localhost)
- Run `sudo mkdir -p /private/var/lib/rancher`
- Run the command from Rancher to add a new host replacing `/var/lib/rancher` with `/private/var/lib/rancher`
- Run `sudo docker logs -f Container ID`

And that's where I get the error. The host never shows up in the host list.

**Comment by vincent99** [comment]
The host registration URL is wrong, the container if trying to connect to localhost to get to the server API but localhost in the container is itself.

**Comment by perryprog** [comment]
@vincent99 that makes sense. I'll try and do that in a bit.

**Comment by perryprog** [comment]
@vincent99 Erm... how would I do this? I assume I would do this at the `Host Registration URL` but I'm not sure how. What would I set it to?

**Comment by vincent99** [comment]
A name or IP that the server container is reachable at.

**Comment by perryprog** [comment]
@vincent99 Awesome, thank you! I just wish rancher made this a bit easier...

**Comment by slonob** [comment]
I found that installing docker from snap was an issue. Got a similar error. Removed docker from snap then installed with apt-get, and it's running fine as a rancher host.
