### ISSUE TITLE
CSRF header and cookie do not match

### ISSUE THREAD

**Issue by liliyongleo** [rancher/rancher#5919]
**Rancher Version:v1.1.2

**Docker Version:1.12

**OS and where are the hosts located? (cloud, bare metal, etc):bare metal ubuntu 

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB) single server node with internal DB.

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)   Cattle.

**Steps to Reproduce: using POSTMAN or API to POST request to Rancher. 

**Results:

hello, I got the same problem with "CSRF header and cookie do not match".

Get Method is working fine. but not for POST.

Here is my HTTP POST request output:
Request URL: http://192.168.1.56:2403/v1/projects/1a5/services/1s370/?action=activate
Request Method: POST
Status Code: HTTP/1.1 403 Forbidden

Request Headers:
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:38.0) Gecko/20100101 Firefox/38.0
Referer: http://192.168.1.56:2403/
Pragma: no-cache
Host: 192.168.1.56:2403
Content-Length: 0
Connection: keep-alive
Cache-Control: no-cache
Authorization: Basic NEZGRDM0OEMzOTc4QjVGOTBGRjM6dzdiQzlYelQ5QWpKV2laemszNnUyY0x6azJnWGRjaHpRVXBiSjhRZA==
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Accept: application/json

Sent Cookie:
PL: rancher
NSID: 26a01c21314009ba5b5748ce0c52a923
CSRF: 6394D5918EFA13F55198BDDB6D06401B

**Comment by vincent99** [comment]
If you make a request that looks like it's from a browser (user-agent contains Mozilla) then the value of the `CSRF` cookie must be sent as the value of a `x-api-csrf` header for non-GET requests.

**Comment by liliyongleo** [comment]
Thanks a lot. Vincent. I managed to successfully POST now.
