### ISSUE TITLE
Feature Request: display free disk space on host page

### ISSUE THREAD

**Issue by pugnascotia** [rancher/rancher#5921]
**Rancher Version:** v1.1.0-dev1

It would be useful to be able to see the used / free disk space for a given host in the UI. It currently displays the sizes of the any attached storage, but not how full they are. I can currently see how much space CPU and memory I have, but not storage.

**Comment by aemneina** [comment]
It'd be good to get a warning as well if the host is close to having its docker root volume full.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
