### ISSUE TITLE
[cli] Cannot pass anything to a container via STDIN using rancher exec or rancher docker exec/run

### ISSUE THREAD

**Issue by stunndard** [rancher/rancher#5922]
**Rancher Version:**
rancher version 1.1.3
rancher cli version v0.1.0-rc3

**Docker Version:**
Docker version 1.10.3, build 20f81dd

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 14.04.5 LTS, Digital Ocean

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher, internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
First lets try to test if we can get STDOUT from the container:

```
root@rancher:~# rancher exec -i mystack/db echo "test"
test
root@rancher:~#
```

It works.

Now, let's pass something to the container via STDIN:

```
root@rancher:~# echo "test" | rancher exec -i mystack/db cat
```

**Results:** 

```
Nothing
```

**Expected:**

```
test
```

**Using bare docker on the docker host for the same container works as expected:**

```
root@docker01:~# echo "test" | docker exec -i a4946c02-ed31-45d3-84a9-fb8798619471 cat
test
root@docker01:~#
```

where a4946c02-ed31-45d3-84a9-fb8798619471 is being the same container, just renamed by rancher after upgrade command

**If using rancher exec, or rancher docker exec, or rancher docker run, the container doesn't seem to get any data passed to it via STDIN.**

**Comment by deviousgeek** [comment]
This __is__ possible, you just need to suffix the command with `-`.

e.g.:

```
cat dump.sql |  rancher exec stack/service bash -c 'mysql -uuser --password=pw db' -

echo "create database foo" |  rancher exec stack/service bash -c 'mysql -uuser --password=pw db' -
```

Got this working in order to automate database setups.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
