### ISSUE TITLE
CentOS Atomic has SELINUX enabled by default.  Cannot start a new k8s cluster.

### ISSUE THREAD

**Issue by MattMencel** [rancher/rancher#5925]
**Rancher Version:**

1.2.0-pre2

**Docker Version:**

1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):**

Running on VMs in VMware.

Rancher Server:  CentOS 7 (Linux rancherserver 3.10.0-327.28.3.el7.x86_64 #1 SMP Thu Aug 18 19:05:49 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux)

Rancher Agents:  CentOS Atomic 7 (Linux kube01 3.10.0-327.28.2.el7.x86_64 #1 SMP Wed Aug 3 11:11:39 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux)

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

Single node rancher server with external (running on localhost) MySQL DB.

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

Kubernetes

**Steps to Reproduce:**

Installing k8s agents on a default install of CentOS Atomic, which has SELINUX enabled/enforcing.  

**Results:** 

Rancher agent etcd container just constantly reset and the k8s services would never start.

I solved it by disabling SELINUX.

**Expected:**

Rancher agents will start and the k8s cluster will go green.

**Comment by deniseschannon** [comment]
This was released as part of Rancher v1.6.

**Comment by deniseschannon** [comment]
@MattMencel If you still have issues, please re-open, but our latest release and k8s version should work with SElinux enabled.
