### ISSUE TITLE
Rancher CLI validation against v2 API

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#5926]
Rancher CLI should be validated against v2 API.

**Comment by deniseschannon** [comment]
Rancher CLI v0.2.0+ is now only compatible with Rancher v1.2.0-pre3+ as we are starting to use the v2-beta API in the CLI.

**Comment by soumyalj** [comment]
Validated with Rancher v1.2.0-pre4-rc4. Some issues found :
https://github.com/rancher/rancher/issues/6367
https://github.com/rancher/rancher/issues/6369
