### ISSUE TITLE
Missing action icons in "View in Api" pages.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#5929]
Rancher Version:    v1.2.0-pre3-rc1
Missing action icons in "View in Api" pages when using "View in Api" action from any page.

<img width="385" alt="screen shot 2016-09-08 at 4 20 07 pm" src="https://cloud.githubusercontent.com/assets/4266958/18370200/330f9080-75e0-11e6-8710-742fbcd7a269.png">
pi

**Comment by tfiduccia** [comment]
This is a build issue, as the image always appear in master version but not in production versions.

**Comment by vincent99** [comment]
Fixed in https://github.com/rancher/api-ui/releases/tag/v1.1.0 which ships with 2.0 (and maybe current versions of 1.6)
