### ISSUE TITLE
Exception/Errors seen in service logs resulting in clientApiError.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#5930]
Rancher Version:v1.2.0-pre3-rc1

There are many automated test cases that report failure because of clientApiError encountered when waiting for service activation to be completed.

These errors/exceptions are also seen in service logs:

 
```
        # Confirm service is active and the containers are running
>       service1 = client.wait_success(service1, 300)

tests/v2_validation/cattlevalidationtest/core/test_rancher_compose_commands.py:200: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <cattle.Client object at 0x7f044923f150>
obj = {'createdTS': 1473361065000, 'launchConfig': {'tty': True, 'networkMode': u'managed', 'vcpu': 1, 'labels': {'test1': u...'test1', 'created': u'2016-09-08T18:57:45Z', 'scalePolicy': None, 'fqdn': None, 'createIndex': 4, 'selectorLink': None}
timeout = 300

    def wait_success(self, obj, timeout=DEFAULT_TIMEOUT):
        obj = self.wait_transitioning(obj, timeout)
        if obj.transitioning != 'no':
>           raise gdapi.ClientApiError(obj.transitioningMessage)
E           ClientApiError: Canceling upgrade
```

 ```
       env, service, consumed_service, consumed_service1, dns = \
            create_environment_with_dns_services(
>               admin_client, client, service_scale, consumed_service_scale, port)

tests/v2_validation/cattlevalidationtest/core/test_dns_services.py:57: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/v2_validation/cattlevalidationtest/core/test_dns_services.py:32: in create_environment_with_dns_services
    service = client.wait_success(service, 120)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <cattle.Client object at 0x7f044ab4fa10>
obj = {'createdTS': 1473359537000, 'launchConfig': {'tty': False, 'networkMode': u'managed', 'vcpu': 1, 'kind': u'container'...540948', 'created': u'2016-09-08T18:32:17Z', 'scalePolicy': None, 'fqdn': None, 'createIndex': 1, 'selectorLink': None}
timeout = 120

    def wait_success(self, obj, timeout=DEFAULT_TIMEOUT):
        obj = self.wait_transitioning(obj, timeout)
        if obj.transitioning != 'no':
>           raise gdapi.ClientApiError(obj.transitioningMessage)
E           ClientApiError: Timeout: container starting [container:1i24]
```

In service logs:

<img width="1061" alt="screen shot 2016-09-08 at 5 21 51 pm" src="https://cloud.githubusercontent.com/assets/4266958/18371432/2a4103fe-75e9-11e6-8e34-bbca593b19f9.png">

In service logs:

<img width="997" alt="screen shot 2016-09-08 at 5 21 01 pm" src="https://cloud.githubusercontent.com/assets/4266958/18371436/303099d2-75e9-11e6-856b-a7208b7a516b.png">

**Comment by tfiduccia** [comment]
I also get an exception for one of my services as well.  
![image](https://cloud.githubusercontent.com/assets/11514927/18371674/08be9726-75eb-11e6-9f3d-2bc62ae6396d.png)

Docker-compose.yml
healthcheckfail:
  log_driver: ''
  labels:
    io.rancher.container.pull_image: always
  tty: true
  log_opt: {}
  image: nginx
  stdin_open: true

rancher-compose.yml
.catalog:
  name: "Health check"
  version: "1.0.0"
  description: "Services"
  uuid: health-check-0
  minimum_rancher_version: v0.46.0
healthcheckfail:
  scale: 1
  health_check:
    port: 80
    interval: 2000
    recreate_on_quorum_strategy_config:
      quorum: 1
    initializing_timeout: 60000
    unhealthy_threshold: 3
    strategy: recreateOnQuorum
    request_line: 'GET "/404" "HTTP/1.1\r\nHost: blah.com"'
    healthy_threshold: 2
    response_timeout: 2000
    reinitializing_timeout: 50000

**Comment by sangeethah** [comment]
Following are all the "ClientApiError:" exceptions seen when running automation tests:

ClientApiError: Timeout: container starting [container:1i24]
ClientApiError: Failed to acquire lock [SERVICE.80]
ClientApiError: Canceling upgrade
ClientApiError: Failed to do service reconcile for service [414]

**Comment by tfiduccia** [comment]
Version - master 9/10
checked my healthcheck service and it is not throwing error in today's master build.

**Comment by sangeethah** [comment]
Validation test on master builds did not report any of the ClientApiErrors tracked in this issue.
2 issues seen in validation runs are now tracked in https://github.com/rancher/rancher/issues/5944 and https://github.com/rancher/rancher/issues/5941.
