### ISSUE TITLE
Errors relating to service.update.wait.exception and service.instance.delete exception seen in service logs.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#5942]
Server version: v1.2.0-pre3-rc1

Steps to reproduce the problem:
Set up had 3 hosts.
Create a service with exposed port and scale policy: 
```
"scalePolicy": {
"increment": 1,
"max": 5,
"min": 1
},
```

3 instances gets deployed and service is in "Active" state as expected.
But there are  Errors relating to service.update.wait.exception and service.instance.delete exception seen in service logs.

<img width="1188" alt="screen shot 2016-09-09 at 10 59 00 am" src="https://cloud.githubusercontent.com/assets/4266958/18397527/80b3ec08-767d-11e6-8b06-4a0863b05d5f.png">

**Comment by alena1108** [comment]
@sangeethah those errors are inevitable in this case. With the scale policy, we try our best to scale up to the max. And if there any allocation errors, we scale down to the latest locked scale (that is >=min scale). Therefore you see the erros in the autid logs: 1) first one for instance allocation 2) second one on service saying that it removed instance that failed to allocate.
