### ISSUE TITLE
Choosing custom/default for Amazon EC2 shows no security group in UI

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#5945]
**Rancher Version:** master 9/10

**Steps to Reproduce:**
1.  Go to Add Host & select Amazon EC2
2.  Fill out Account Access, Availability Zone sections
3.  In Security Group section click on Custom and leave it on Default, click Next

**Results:**   Looks like there is no Security Group selected
![image](https://cloud.githubusercontent.com/assets/11514927/18404635/a84c415c-76a0-11e6-87e0-4a580ad84cd1.png)

**Expected:**  Should say default (sg-1919567c)

**Comment by vincent99** [comment]
@westlywright It needs to take/set an array now instead of a single group.

**Comment by tfiduccia** [comment]
Version - v1.2.0-pre3-rc3
Verified fixed
