### ISSUE TITLE
Kubernetes in Rancher does not support SkyDNS service discovery

### ISSUE THREAD

**Issue by usmanismail** [rancher/rancher#5948]
The kubernetes environment can support both docker style environment variables for service discover as well as DNS. Once of the shortcomings of environment based approach is that services have to be launched in the order for dependence. With DNS based discovery they can be launched in any order. Kubernetes inside Rancher should support DNS Add on. http://kubernetes.io/docs/user-guide/services/#dns

**Comment by galal-hussein** [comment]
Tested and verified skydns on Rancher master build and vnext branch of rancher-catalog.
