### ISSUE TITLE
agent-instance cannot start automatically on Ubuntu 16.04.X

### ISSUE THREAD

**Issue by JaviSabalete** [rancher/rancher#5951]
**Rancher Version:**
1.1.1
**Docker Version:**
1.12.1
**OS and where are the hosts located? (cloud, bare metal, etc):**
Local PC, Ubuntu 16.04.1 LTS
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher with external DB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
Create stack and reboot.
**Results:** 
rancher/agent:v1.0.2 -> started
rancher/agent-instance:v0.8.3 -> not started
**Expected:**
rancher/agent:v1.0.2 -> started
rancher/agent-instance:v0.8.3 -> started
**Logs from agent-instance container**

```
INFO: Sending rancher-net applied 1-4ff638972a3b918bd129626f79ba289baf0e8912c39c46f9870d1a2b5f6cb299
INFO: HOME -> ./
INFO: HOME -> ./etc/
INFO: HOME -> ./etc/cattle/
INFO: HOME -> ./etc/cattle/startup-env
INFO: ROOT -> ./
INFO: ROOT -> ./etc/
INFO: ROOT -> ./etc/init.d/
INFO: ROOT -> ./etc/init.d/agent-instance-startup
INFO: Sending agent-instance-startup applied 12-2f801599d8e5c376c74840f1e7ffff3fa6ad1af0339ad7e76edfa4a83c006d70
Starting monit daemon with http interface at [localhost:2812]
The system is going down NOW!
Sent SIGTERM to all processes
Sent SIGKILL to all processes
Requesting system reboot
```

**How fix manually:**
service docker restart
docker start ID-FROM-rancher/agent-instance:v0.8.3
**Notes**
Works perfectly on Debian 8.X and Ubuntu 14.04.X

**Comment by aemneina** [comment]
Hey @JaviSabalete does this work using docker 1.11 or 1.10? I ask because rancher 1.1 isnt intended to work with docker 1.12 at this time.

**Comment by sfenzke-smava** [comment]
I just tried this on Ubuntu 16.04.1 LTS with docker version 1.11.2 and got the same beaviour.

**Comment by JaviSabalete** [comment]
@aemneina tested with docker 1.11.x and 1.10.x, same behaviour on Ubuntu 16.04

No problems with Ubuntu 14.04 and Debian 8

**Comment by aemneina** [comment]
Can you share the docker logs from the agent host? If possible with debug mode enabled... Does the rancher server log have anything at this point?

**Comment by Tigraine** [comment]
@aemneina What is your recommendation for a AWS EC2 based docker-ha setup regarding which ubuntu version and docker version seems most stable? Thanks!

**Comment by aemneina** [comment]
I personally use RancherOS 0.4.5 (shameless plug), but I've had success with ubuntu 14.04 and centos 7.2 (using docker 1.10.3), in production. I only stray from that kind of config when I absolutely want to try some new feature/fix in a dev/test sandbox.

**Comment by aemneina** [comment]
closing this out, feel free to reopen if you still have issues...
