### ISSUE TITLE
Nomad support

### ISSUE THREAD

**Issue by gfrivolt** [rancher/rancher#5958]
Are there plans to add the Nomad scheduler from HashiCorp to rancher? Can we anyhow help to make it happen?

**Comment by dev-mraj** [comment]
+1

**Comment by diceone** [comment]
+1

**Comment by darrin-wortlehock** [comment]
+1

**Comment by juliangamble** [comment]
+1

**Comment by bogdanov1609** [comment]
+1

**Comment by ozlevka-ericom** [comment]
+1

**Comment by odinsy** [comment]
+1

**Comment by vincent99** [comment]
Realistic answer: no, we have not seen significant commercial interest in Nomad that I'm aware of and we are unlikely to dedicate time to this.

**Comment by chriswue** [comment]
If we were interested in possibly adding this ourselves: I've had a look through the various rancher repos but struggling to see clear hook-in points for 3rd party orchestration tools. From what I've been able to determine so far I guess this is what needs doing:
* Create custom Nomad agent similar to rancher/kubernetes-agent
* Add the required docker/rancher templates required to run the Nomad infrastructure to the rancher/catalog repo (infra-templates, project-templates, templates) 
* Add UI frontend/proxy for Nomad to rancher/UI
* Add command wrapper for Nomad CLI to rancher/cli

Does that sound about right?

**Comment by vincent99** [comment]
They are all different degrees of one-off and there is not really a framework to add additional ones. 

But with 2.0 we are focusing on the Rancher ("cattle" orchestration in 1.x) experience on top of a kubernetes cluster (which we manage, or using an external one like how), which together make up the vast majority of user interest.

So there is no longer an "orchestration type" or core code or UI for mesos/swarm and those will be deployed as catalog items for the minority that want them.  So you should probably look more in that direction.

**Comment by chriswue** [comment]
Hm ok, but then I don't really have a way to select a job from the catalog and then schedule it with Nomad - right? I'm currently struggling to find something which offers the "deploy from catalog" functional rancher has and allows me to use Nomad as a scheduler.

Nomad is the only scheduler I've found so far which can schedule non-docker jobs (in our environment I'd like to be able to schedule some native windows jobs due to legacy software reasons)

**Comment by markrey** [comment]
@chriswue I am currently looking for the same. Were you able to find a good architecture for it?

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
