### ISSUE TITLE
Validate "AWS ELB Application Load Balancer" catalog.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#5959]
Validate "AWS ELB Application Load Balancer" catalog entry - https://github.com/janeczku/elbv2-catalog

**Comment by galal-hussein** [comment]
@sangeethah I tested the catalog on the following setup

Rancher v1.1.3
Two nodes on AWS

I launched the catalog template and two nginx containers with the mentioned label and exported port 80 on both nodes, the load balancer was automatically created:

![screenshot from 2016-09-13 19-06-10](https://cloud.githubusercontent.com/assets/3309968/18483924/91c227dc-79e6-11e6-8436-bde6f70b3c11.png)

And the load balancer automatically removed when removing the service, however I noticed that the target group didn't get removed automatically.

**Comment by DorrinPk** [comment]
Is there any documentation on setting the ALB up with rancher from the AWS console?

**Comment by janeczku** [comment]
@galal-hussein There should be an error about the target group not having been removed. Could you post that?

@DorrinPk This catalog service sets up ALB for you using the configuration passed by service labels. There is nothing to do on the AWS console, except maybe creating an IAM token.

**Comment by DorrinPk** [comment]
@janeczku 

I got a `There are no compatible templates.` error when I uploaded my template. I think it's a rancher issue because I provided the repo in this format : `https://github.com/janeczku/elbv2-catalog` and I get that error.


Looking at logs from the rancher container I see 

`time="2016-09-15T19:44:13Z" level=info msg="Starting Rancher Catalog service" 
time="2016-09-15T19:44:13Z" level=info msg="Using catalog library=https://github.com/rancher/rancher-catalog.git" 
time="2016-09-15T19:44:13Z" level=info msg="Using catalog community=https://github.com/rancher/community-catalog.git" 
time="2016-09-15T19:44:13Z" level=info msg="Using catalog RancherALB=https://github.com/janeczku/elbv2-catalog" 
time="2016-09-15T19:44:15Z" level=info msg="Cloning the catalog from git URL https://github.com/janeczku/elbv2-catalog" 
Cloning into './DATA/RancherALB'...
`

so I'm assuming it was cloned properly. I did the same with the community catalog and it worked fine.

**Comment by janeczku** [comment]
@DorrinPk The ELB template requires Rancher v1.1.0 or later. You probably have a previous version.

**Comment by galal-hussein** [comment]
@janeczku I didn't get an error, i only saw that target group still exist.

**Comment by janeczku** [comment]
@galal-hussein This should be fixed in the latest image.

**Comment by schuylr** [comment]
@janeczku Great work so far. I have the ALB working for my application. The ability to specify the VPC and region was also very important and useful for us.

Two big caveats in my books:

1. Can we please have the ability to specify the health check location? Currently `/` is just a static page on our server, whereas we've created `/health` _specifically for an application-exposed test_ so we're not exposing overloaded applications whereas the reverse-proxy caching nginx is fine.

2. Can we expose multiple ports from the listener to the same service backend? I'd have to run a separate container just to forward HTTP traffic to HTTPS on my service.

**Comment by janeczku** [comment]
Thanks a lot for your input @schuylr. Good point on the health check location. I'll add a label allowing the user to specify the protocol, port and path to use for the health check.

To clarify the second point: You want to forward traffic to multiple ports of the same service with each one mapped to another listener? We would need to come up with a label scheme that allows users to specify multiple listeners/frontends and service/backend ports. Maybe you have a suggestion?

**Comment by schuylr** [comment]
Thanks!

What about commas? e.g.

```
io.rancher.service.external_lb.frontend_protocols = HTTP,HTTPS
io.rancher.service.external_lb.frontend_ports = 80,443
io.rancher.service.external_lb.backend_protocols = HTTP,HTTPS
io.rancher.service.external_lb.backend_ports = 80,443
```

I think all of the labels would need that scheme though, so maybe not the best. I don't have an alternative in mind but it is how I've seen other environment variables passed around i.e. LetsEncrypt list of domains to generate certs for. I couldn't imagine a service using more than 2 or 3 exposed ports.

There's also [documentation on comma-separated lists in Rancher](http://docs.rancher.com/rancher/v1.1/en/cattle/labels/#example-of-a-comma-separated-list).

What do you think?

**Comment by schuylr** [comment]
@janeczku Another point of contention:

I like that I can specify the VPCs and regions that the manager will set up load balancers in, however how will I specify which service gets assigned to certain managers?

Could there be another label that makes sure the ELB manager only captures the region it's working for? I have everything for production in one environment.

For example, I have one service in eu-central-1, and another in us-east-1. It wouldn't be helpful to have the eu-central-1 service be assigned to a load balancer in us-east-1.

**Comment by schuylr** [comment]
I'm knee-deep in the code for Rancher's `external-lb` and am seeing that the whole fundamental service really hasn't been built around the consideration that there could be multiple managers in a single environment. Refactoring all of that looks like a huge headache. I'll probably consider this as not in my use-case unless I make multiple environments for each AWS Region.

**Comment by ampedandwired** [comment]
I tried this out today and came across a few problems.

First is a panic cause by (I'm guessing) the fact that the instance being load balanced does not have a public IP address:
```
time="2016-10-10T00:10:55Z" level=info msg="Starting Rancher External LoadBalancer service" 
time="2016-10-10T00:10:55Z" level=info msg="Environment variable 'LB_POLL_INTERVAL' not set. Using default interval 1000" 
time="2016-10-10T00:10:55Z" level=info msg="Configured AWS Application Load Balancer provider in region ap-southeast-2 and VPC vpc-d30d0cb6" 
time="2016-10-10T00:10:55Z" level=info msg="Healthcheck handler is listening on :1000" 
time="2016-10-10T00:10:56Z" level=info msg="LB configs to add: 1" 
time="2016-10-10T00:10:56Z" level=info msg="Adding LB config: {rancher-dev-default [{80 HTTP  [{nginx_elbv2-test_a3479d0e-b6c3-41d4-af04-e7bada6c4381 8060 HTTP  [10.3.5.181 10.3.7.145] false 8060}]}]}" 
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x73d986]

goroutine 1 [running]:
github.com/rancher/external-lb/providers/elbv2/elbsvc.(*ELBService).LookupInstancesByFilter(0xc820114780, 0xc8204170c0, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/Janek/go/src/github.com/rancher/external-lb/providers/elbv2/elbsvc/ec2.go:82 +0x786
github.com/rancher/external-lb/providers/elbv2/elbsvc.(*ELBService).LookupInstancesByIPAddress(0xc820114780, 0xc820418220, 0x2, 0x2, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/Janek/go/src/github.com/rancher/external-lb/providers/elbv2/elbsvc/ec2.go:48 +0x235
github.com/rancher/external-lb/providers/elbv2.(*AWSELBv2Provider).getEC2Instances(0xc8200450a0, 0xc82042b3c0, 0x13, 0xc820491200, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/Janek/go/src/github.com/rancher/external-lb/providers/elbv2/aws_elbv2.go:982 +0x45f
github.com/rancher/external-lb/providers/elbv2.(*AWSELBv2Provider).AddLBConfig(0xc8200450a0, 0xc82042b3c0, 0x13, 0xc820491200, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
	/Users/Janek/go/src/github.com/rancher/external-lb/providers/elbv2/aws_elbv2.go:260 +0x471
main.updateProvider(0xc8204ad8c0, 0x1, 0x1, 0x0, 0x1)
	/Users/Janek/go/src/github.com/rancher/external-lb/external-lb.go:115 +0x2d6
main.addMissingConfigs(0xc8204accf0, 0xc8204ad860, 0xc8204ad890)
	/Users/Janek/go/src/github.com/rancher/external-lb/external-lb.go:80 +0x325
main.UpdateProviderLBConfigs(0xc8204accf0, 0xc8204accf0, 0x0, 0x0)
	/Users/Janek/go/src/github.com/rancher/external-lb/external-lb.go:24 +0x195
main.main()
	/Users/Janek/go/src/github.com/rancher/external-lb/main.go:129 +0x528
```

The second issue is that there seems to be no way to specify the subnets that you wish the load balancer placed into. We have a public/private/restricted subnet setup within our VPC, and need to be able to control which VPC the ELBv2 ends up in.

Also I agree with @schuylr above. There needs to be some flexibility in being able to make load balancers in different regions, VPCs or subnets within the one Rancher environment. For example, I need both a private and a public load balancer in different subnets, and this service needs to use the public/private IP address accordingly.

One possible way to provide some flexibility for users with these sorts of requirements might be to allow the ELB instance to be created outside this service. That way we can create the ELB out-of-band in a region/vpc/subnet that meets our needs, but then rely on this service to manage its target groups.

Anyway, good stuff so far, looking forward to seeing this released.

**Comment by jsalva** [comment]
I'm getting the same `panic: runtime error: invalid memory address or nil pointer dereference` error on the master branch of `rancher/external-lb` launched from the catalog directly. Does this simply not work with instances that have been launched in private subnets? I have the `ELBV1_USE_PRIVATE_IP: 'true'` included in my docker-compose.yml; any guidance on troubleshooting this would be helpful

**Comment by agalpin** [comment]
what policies does it need? it appears to only do something when given Full Access (Administrator), i was attempting to restrict the IAM to only ELB/ALB stuff, once it had admin permissions it starting looking at other ALB's that it shouldn't care about and fails with 

While parsing HealthCheckPort: strconv.ParseInt: parsing \"traffic-port\": invalid syntax"

Health port on the ALB is "traffic port" (this is the default AWS/ALB value if not changed) and path is /, but either way it shouldn't care about ones that don't involve it.

**Comment by agalpin** [comment]
Just thinking out aloud here but couldn't this just manage assigning instances/containers to target groups, and leave creation of ALB and assignment of ALB target groups to the aws admin?
This would basically be the same as what the current elbv1 provider does?
This would also allow for cleaner naming, for example in my case i currently have 3 identical environments and using this results with target groups of the same name with a hex identifier key.

When running multiple to handle both http and https i get a couple of ALB's which could easily be assigned to a single ALB with two target groups.
