### ISSUE TITLE
Disabling community & certified catalogs causes Machine Driver page to crash

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#5960]
**Rancher Version:** v1.2.0-pre3-rc2

**Steps to Reproduce:**
1.  Go to settings an disable Rancher Certified and Community catalog
2.  Go to Machine Driver page and refresh

**Results:** Internal Error 500 page
From Dev tools: http://104.198.194.216:8080/v1-catalog/templates?minimumRancherVersion_lte=….2.0-pre3-rc2&category_ne=system&minimumRancherVersion_lte=v1.2.0-pre3-rc2 500 (Internal Server Error)
Application Error undefined

**Expected:** No error page

**Comment by vincent99** [comment]
Changed in the UI to not blow up if the catalog returns an error.  @mrajashree Can you make the catalog-service work if it's configured with no URLs instead of dying with

time="2016-10-07T19:43:00Z" level=fatal msg="Halting Catalog service, Catalog git repo url not provided"

**Comment by tfiduccia** [comment]
Version - master 10/10
When I disable all catalogs, the catalog templates are still showing up.

**Comment by tfiduccia** [comment]
Version - 1.2.0-pre4-rc4
Verified fixed
