### ISSUE TITLE
Scheduler v3 

### ISSUE THREAD

**Issue by will-chan** [rancher/rancher#5962]
- [ ] Add ability to tag hosts as "non-schedulable" unless there is an explicit host affinity rule to place containers on those hosts.
- [ ] Add ability to tag pools of hosts (i.e. as a zone or region) and be able to schedule containers evenly across those pool of hosts.

**Comment by digitalLumberjack** [comment]
Hi :)
I just reported this bug : https://github.com/rancher/rancher/issues/5962
Maybe this refactor corrects it too ?

**Comment by cjellick** [comment]
@digitalLumberjack you copied the wrong link. Putting reference to correct issue:
https://github.com/rancher/rancher/issues/6453

**Comment by digitalLumberjack** [comment]
Thanks @cjellick i fixed it :)

**Comment by cjellick** [comment]
We weren't aware of this particular bug, but definitely one we would like not _not_ have. See the issue for my follow up question regarding the bug.

**Comment by deniseschannon** [comment]
Closing in favor of #7253 and #7254

**Comment by kmcgrath** [comment]
With this update would there be an affinity to also spread evenly across zones/regions?  For instance I have 3 AZs  I have three pools of hosts and want a services to spread evenly across the 3 zones.  Or is this for only spreading evenly within a single zone?
