### ISSUE TITLE
Cloning host to Scaleway with new name not working

### ISSUE THREAD

**Issue by asthomasdk** [rancher/rancher#5964]
**Rancher Version:**
1.1.3

**Docker Version:**
1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu
Bare metal on Scaleway

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA Rancher using Galera DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle. 

**Steps to Reproduce:**
Create a host using the Scaleway docker-machine driver. 
Server type: C2L
Ubuntu 16.04

Once the host been created, provisioned etc. - select the running host and choose "clone". Change the Rancher host name and the Scaleway name as the only fields being changed - and select Create.

**Results:** 
All going well, the new host is created ok - but with the same name in Scaleway as the host it was cloned from. 

The hostname in Rancher is changed as expected. 

As the host is given a different IP address and underlying ID - the host is functional. However, it does make it difficult to select the correct servers from the Scaleway UI. 

**Expected:**
I would expect the name of the host be the same in both Rancher and on Scaleway. 

I am not sure at this point if this is an issue with Rancher's call to clone the host - or the underlying docker-machine driver being used.

**Comment by aemneina** [comment]
@asthomasdk Is the clone functionality executed from scaleways' UI/API? Sounds like the hostname within the host didnt change with the cloning, so I would assume the host is not setting the hostname dynamically from cloud-init, or DHCP.

**Comment by asthomasdk** [comment]
The clone is being executed from the Rancher UI - and cloning a host that was created with the Scaleway docker-machine driver.

**Comment by vincent99** [comment]
I thought this was fixed but apparently not.. https://github.com/rancher/rancher/issues/2226
