### ISSUE TITLE
kubectl version shows invalid values for GitVersion and GitCommit

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#5968]
Server version - v1.2.0-pre3-rc3

K8s template from "qa" branch of "https://github.com/rancher/rancher-catalog/"

<img width="960" alt="screen shot 2016-09-13 at 6 39 34 pm" src="https://cloud.githubusercontent.com/assets/4266958/18497273/ab581300-79e1-11e6-8ef2-5b52168ffefb.png">

**Comment by wlan0** [comment]
This is beacuse of how i compiled kube-apiserver in my build. It wont be a problem in the official images.
