### ISSUE TITLE
k8s etcd_data container shown as being in "stopped" state instead of "started-once".

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#5969]
Server version - v1.2.0-pre3-rc3
K8s template from "qa" branch of "https://github.com/rancher/rancher-catalog/"

Had an "cattle" environment with 2 hosts.
Updated environment to "kubernetes",
Once the K8s system stack is up and running ,one of the k8s etcd_data container shown as being in "stopped" state instead of "started-once". 
<img width="1031" alt="screen shot 2016-09-13 at 6 50 04 pm" src="https://cloud.githubusercontent.com/assets/4266958/18497476/6d9efa36-79e3-11e6-9f12-f962de2d7370.png">

**Comment by alena1108** [comment]
@sangeethah it means that it was never started (start_count = 0). @LLParse have you observed this behavior? when the sidekick fails to start, yet corresponding etcd primary container runs normally

**Comment by LLParse** [comment]
@alena1108 I've been using 1.1.3 for quite some time and haven't seen this happen.

**Comment by alena1108** [comment]
@sangeethah see if it still happening

**Comment by galal-hussein** [comment]
@alena1108 @sangeethah The problem doesn't happen anymore, tested on v1.2.0
