### ISSUE TITLE
Duplicated users (from UI view) can be created by API call

### ISSUE THREAD

**Issue by jayhding** [rancher/rancher#5970]
**Rancher Version:**
1.1.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
RHEL 7.2

**Setup Details**
External DB. MySQL 5.5

**Environment Type:**
Cattle

**Background:**

Due to unresolved #3875, we need to use API call to set same individual user roles across various environments.
Also because `setmembers` action will clear existing user roles so current role list need to be combined with new role list before post to `setmembers` action

**Steps to Reproduce:**
1. Add user1 from UI as **member**
2. Get current user list from API `http://$rancher_url/v1/projects/$proj_id/projectmembers`
3. Prepare new user list where user1 role is **owner**
4. Combine current and new user lis
5. Post the combined user list to `http://$rancher_url/v1/projects/$proj_id/?action=setmembers`

**Results:** 
- After step 5 two user1 can be seen from UI with both role as **owner**
- Deleting one of duplicated user from UI will end up delete both so it might be just UI display issue

**Expected:**

There will be only one user1 with new role assigned from UI.

**Workaround:**

`jq 'unique'` can be used to remove duplicated users in existing list before posting to Rancher API

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
