### ISSUE TITLE
rancher cli : Activate and deactivate environment results in "Bad response statusCode [403]"

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#5974]
**Rancher Version:**v1.2.0-pre3-rc3

Rancher CLI version: v0.2.0-rc1

**OS and where are the hosts located? (cloud, bare metal, etc):**: Cloud

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**: Cattle

**Steps to Reproduce:**
1. Create a rancher cli setup
2. Create few environments
2. Run the env deactivate and activate commands

```
soumyas-MacBook-Pro:rancher-v0.2.0-rc1 soumya$ ./rancher env ls
ID        NAME        ORCHESTRATION   STATE      CREATED
1a17      newcattle   Cattle          inactive   2016-09-14T04:25:36Z
1a19      kubeenv     Kubernetes      active     2016-09-14T04:28:10Z
1a18      kubeenv     Kubernetes      active     2016-09-14T04:26:07Z
1a20      cattleenv   Cattle          active     2016-09-14T04:33:44Z
soumyas-MacBook-Pro:rancher-v0.2.0-rc1 soumya$ ./rancher env deactivate 1a18
FATA[0000] Bad response statusCode [403]. Status [403 Forbidden]. Body: [code=Forbidden, message=Forbidden] from [http://130.211.194.0:8080/v2-beta/projects/1a17/schemas/schemas]

soumyas-MacBook-Pro:rancher-v0.2.0-rc1 soumya$ ./rancher env activate 1a20
FATA[0000] Bad response statusCode [403]. Status [403 Forbidden]. Body: [code=Forbidden, message=Forbidden] from [http://130.211.194.0:8080/v2-beta/projects/1a17/schemas/schemas] 
```

**Comment by deniseschannon** [comment]
Narrowed this down.

If you have selected an environment in the `rancher config` that becomes inactive, you are unable to run any environment commands.

Workaround: Reset your RANCHER_ENVIRONMENT by running `rancher config` or using `--env `  for a different active environment.
