### ISSUE TITLE
Better error notification if web socket not available

### ISSUE THREAD

**Issue by ebuildy** [rancher/rancher#5975]
*\* Level **

Not an issue at all, but I think this could help people to adopt Rancher if they have this kind of error.

**Rancher Version:**

1.3.3

**Docker Version:**

1.10

**OS and where are the hosts located? (cloud, bare metal, etc):**

RancherOS on AWS EC2

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

`docker run rancher/server` **behind a Nginx proxy (not well configured)**

**Steps to Reproduce:**

Run Rancher behind a misc-configured HTTP proxy, go to the web console.

**Results:** 

"I can browse to Rancher web ui, but as soon as I click on menu, I got an error saying 'Reload or logout'"

**Expected:**

If web UI cannot access to web socket, an explicit error should be throw saying "Hey Bob, please check that you know how to configure an HTTP proxy ;-)"

**Comment by loganhz** [comment]
This notification has been added.
