### ISSUE TITLE
Can't delete Hosts

### ISSUE THREAD

**Issue by jsilberm** [rancher/rancher#5984]
Tried through both the UI and the API.
Likely issue is that the (cloud) hosts had been deleted out-of-band.
(All such hosts show up in "Reconnecting" state in the UI).

But Rancher should still allow a "delete" or a "delete w/ force" option.   Right?

**Rancher Version:** 1.1.3

**Docker Version:** 1.12

**OS and where are the hosts located? (cloud, bare metal, etc):**  Ubuntu 16 / EC2

![rancher](https://cloud.githubusercontent.com/assets/5834578/18595132/39da71be-7bf8-11e6-850b-f11976445279.png)

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**

**Results:** 

**Expected:**

**Comment by tfiduccia** [comment]
@jsilberm - before you hit the Delete operation, try selecting deactivate under the action section.  Once the state of host is Inactive, you should be able to select Delete and it should work.
