### ISSUE TITLE
when secret bridge agent is configured with bridge-url url having "/" at the end , it fails to contact  secrets-bridge server.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#5986]
Rancher Version:v1.1.4-rc1

Set up secrets-bridge-server and secret-bridge-agent by following instruction in https://github.com/rancher/secrets-bridge/blob/master/docs/setup.md for k8s environment.

When starting secret bridge agent provide a bridge-url url having "/" at the end .
It fails to contact  secrets-bridge server.

**Comment by cloudnautique** [comment]
Fix is in docker image rancher/secrets-bridge:v0.1.2 which is part of the community catalog now.

**Comment by sangeethah** [comment]
Tested with rancher/secrets-bridge:v0.1.2
This issue is not seen anymore.
