### ISSUE TITLE
Unicode character 'µ' in catalog template causes yaml parse to fail

### ISSUE THREAD

**Issue by ahaynssen** [rancher/rancher#5988]
**Rancher Version:** v1.1.3

**Docker Version:** 1.11.2

**OS and where are the hosts located? (cloud, bare metal, etc):** Ubuntu, AWS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** HA Rancher, internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:** Add µ character anywhere in rancher-compose.yml catalog template, in our case it was in a commented block describing precision in seconds. 

**Results:** Stack stuck at activating, displays (yaml: [while parsing a quoted scalar] did not find expected hexadecimal number at line <number>)

FYI - This line number didn't actually correspond to where it was in our document.

**Expected:** Stack would be activated and started up as normal.

**Comment by tfiduccia** [comment]
@ahaynssen - this is currently fixed in our rancher v1.2.0-pre3 release as part of #5414 fix.
