### ISSUE TITLE
Not able to get permanent key when containers are deployed with secrets.bridge.enabled: "true" but without "secrets.bridge.k8s.path" label.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#5990]
Rancher Version:v1.1.4-rc1

Set up secrets-bridge-server and secret-bridge-agent by following instruction in https://github.com/rancher/secrets-bridge/blob/master/docs/setup.md for k8s environment.

Create pods with label - secrets.bridge.enabled: "true" but without "secrets.bridge.k8s.path" label.

Following error seen when trying to fetch the permanent token:

```
root@test17:/tmp# curl -H "X-Vault-Token: $TEMP_TOKEN " -X GET $CUBBY_PATH
<a href="/v1/cubbyhole/k8s/default/d530fc2f395222526e9d216e5933b60bd1edc14aea663
85a7e399e270ae38501">Moved Permanently</a>.

```
CUBBY_PATH url has "//" like http://<vault-ip>:8200/v1/cubbyhole/k8s/default//d530fc2f39
5222526e9d216e5933b60bd1edc14aea66385a7e399e270ae38501

**Comment by sangeethah** [comment]
Tested with rancher/secrets-bridge:v0.1.3 version.

This issue is not seen any more.
Able to get permanent key when containers are deployed with secrets.bridge.enabled: "true" but without "secrets.bridge.k8s.path" label.

**Comment by cloudnautique** [comment]
Should we call this one resolved?
