### ISSUE TITLE
Purge process_execution, instance and instance_label_map data?

### ISSUE THREAD

**Issue by dj-hedgehog** [rancher/rancher#5991]
**Rancher Version:** 1.1.3
**Docker Version:** 1.12.1
**OS and where are the hosts located? (cloud, bare metal, etc):** 
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single node rancher with internal DB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

I've read about purging old database entries here http://docs.rancher.com/rancher/v1.2/en/faqs/server/#rancher-server-database-is-growing-too-quickly
and changed the setting `audit_log.purge.after.seconds`.

However for the other big players `process_execution`, `instance_label_map` and `instance` there is no such setting. How can I purge data from those?

Also can I start the cleaning process manually?

![node ssh 2016-09-17 01-48-04](https://cloud.githubusercontent.com/assets/7140800/18604173/953b1884-7c79-11e6-915a-9bc4206771e5.png)

**Comment by will-chan** [comment]
@LLParse id this part of your housekeeping scripts?

**Comment by LLParse** [comment]
@will-chan Yes, this will be resolved at the same time as https://github.com/rancher/rancher/issues/5129

**Comment by deniseschannon** [comment]
Closing in favor of #5129
