### ISSUE TITLE
Can't view logs or execute shell on Ubuntu 16.04 hosts

### ISSUE THREAD

**Issue by dj-hedgehog** [rancher/rancher#5992]
**Rancher Version:** 1.1.3
**Docker Version:** 1.12.1 & 1.11.1
**OS and where are the hosts located? (cloud, bare metal, etc):** cloud
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single node rancher with internal DB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

I'm using two CentOS hosts and two Ubuntu hosts. One has 14.04 installed, the other one 16.04.

I can neither view the logs nor execute a shell from the 16.04 one. This is what I see when I click on "Execute Shell" on a running container.

**_What might be causing this issue?**_

![rancher 2016-09-17 02-29-45](https://cloud.githubusercontent.com/assets/7140800/18604596/c62ac688-7c7e-11e6-818d-3893057fbb44.png)

**Comment by aemneina** [comment]
Docker 1.12 isn't supported with rancher 1.1.x code line. Can you downgrade docker and try again? Reopen if it's resurfaces on a supported platform.

**Comment by dj-hedgehog** [comment]
Please re-open it. I just upgraded to Docker 1.12 and had the same problem with Docker 1.11 before.
I migrated all my hosts to Overlay2 today (to get rid of that damn devicemapper) so I can't downgrade anymore.

**Comment by aemneina** [comment]
Are you connecting directly to the rancher server? Is there any LB/firewall in between?

**Comment by dj-hedgehog** [comment]
There is nothing inbetween. I can also connect to the other three hosts as expected.

**Comment by aemneina** [comment]
If you're using chrome can you share any logs from the dev tools console?

**Comment by dj-hedgehog** [comment]
On trying `Execute Shell` I get:

> VM49:35 WebSocket connection to 'ws://rancher.example.cm:8080/v1/exec/?token=eyJhbGci2...-mR9hoZrEzmTB0PjaBAWvG5u1tRbi6NjVQ0tQ' failed: HTTP Authentication failed; no valid credentials available

Note: I shortened the token greatly.

Its the same for "View Logs", just with the `/logs` endpoint.

**Comment by tfiduccia** [comment]
Have tried this and can't reproduce.  I have a machine using Amazon EC2, with docker version 1.12.1, and Ubuntu 16.04.1 and I can view logs and execute shell on all my containers.  Can you tell us which hosting service you are using and the image.

**Comment by aemneina** [comment]
@dj-hedgehog pretty weird you're getting an authentication error. You have auth enabled? Can you do a hard refresh on your browser or try on another browser. Maybe there's some stale auth persisting...

**Comment by dj-hedgehog** [comment]
@aemneina I tried two other browsers and even re-created the services. It still doesn't work.

**Comment by aemneina** [comment]
@dj-hedgehog, @tfiduccia asks a good question, where are your machines hosted? I also havent been able to repro your issue using: rancher 1.1.x + ubuntu 16.04 + docker 1.11.2

**Comment by jgreat** [comment]
I also have this issue intermittently. Rebooting the agent vm resolves the issue for a while.

I have multiple agent servers in an environment, and it will happen on one (or more) of the servers independently from the others.

Rancher	v1.1.1
Cattle	v0.165.7
User Interface	v1.1.12
Rancher Compose	v0.8.6

Ubuntu 16.04 kernel 4.4.0-31-generic
Docker version 1.11.2, build b9f10c9

I have checked agent system time vs the server system time and they are in sync (ntp) 
Tried clearing out browser cookies, doesn't help.

I have a couple of agents in a dev environment it is actively happening on right now. I can leave them in the broken state and provide logs and try things out.  Please let me know if there is anything I can provide.

**Comment by cjellick** [comment]
@jgreat what type of environments are you runing? cattle, kubernetes, or swarm?

**Comment by jgreat** [comment]
Cattle

**Comment by dj-hedgehog** [comment]
The troubling machine is a dedicated server at http://www.server4you.com/
We're also using Cattle.

**Comment by aemneina** [comment]
@dj-hedgehog are all your hosts, including the working ones, using that provider? we might be able to eliminate that as being the issue and narrow down on what could be causing the problem.

**Comment by dj-hedgehog** [comment]
I've got four hosts currently.
Two of them are hosted with another hoster.
Two are hosted with server4you

The one running  Ubuntu 14.04.4 LTS (with KVM) is working fine and doesn't show this error
The one running Ubuntu 16.04.1 LTS (with KVM) shows the problem above.

**Comment by aemneina** [comment]
what version of docker on each?

**Comment by dj-hedgehog** [comment]
Version 1.10.2 on both.

**Comment by cpoole** [comment]
I see the same behavior. Ubuntu 16.04 AWS 
Docker 1.11.2
Rancher 1.1.1

error in chrome console:
```
socket.js:50 WebSocket connection failed: HTTP Authentication failed; no valid credentials available
```

hard refresh didnt work, clearing cache for page and entire domain didnt work. incognito mode didnt work. 

A restart of the rancher/agent container on the instance _solved_ the problem

looking through the rancher agent logs reveals nothing out of the ordinary. The only thing that has changed on this host was one of the my EBS block devices attached to xvdc became full yesterday... unfortunately I'm not sure when this behavior started on this host.

**Comment by aemneina** [comment]
@cpoole did you get to the bottom of this? You need to make sure ports 81 and 444 are proxied to the backend from the LB in an HA case.

@dj-hedgehog did you locate what was interfering with your websocket connections? Typically 'application aware' firewalls and LB's dont play nice.

**Comment by cpoole** [comment]
@aemneina yep both ports are proxied. For me it was actually just disk space. I noticed this again the other day and it turned out one of my rancher server hosts had a full disk. 

maybe coincidental, but for me each time I see this I also have disk space issues

**Comment by superseb** [comment]
Please comment if you are still experiencing issues, we can investigate.
