### ISSUE TITLE
Lb service started for secrets-bridge-server links to incorrect port.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#5993]
Tested with rancher/secrets-bridge:v0.1.3
LB services started for servicing secrets-bridge links to 8081 instead of 8181 for secrets-bridge service.

**Comment by cloudnautique** [comment]
This is fixed in rancher/community-catalog#287

**Comment by sangeethah** [comment]
Tested with latest secrets-bridge-server catalog entry.
LB services started for servicing secrets-bridge links to 8181 and is functional.
