### ISSUE TITLE
Search path in container doesn't reflect hosts /etc/resolv.conf

### ISSUE THREAD

**Issue by dj-hedgehog** [rancher/rancher#5994]
**Rancher Version:** 1.1.3
**Docker Version:** 1.11.1
**OS and where are the hosts located? (cloud, bare metal, etc):** cloud, CentOS 7
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single node rancher, internal DB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

I've changed my hosts `etc/resolv.conf` file and removed the entry `search happysrv.de` but it keeps appearing in my containers like here:

```
root@357ff2c64150:/usr/src/app# cat /etc/resolv.conf
search happysrv.de myproject.rancher.internal backend.myproject.rancher.
internal rancher.internal
nameserver 121.253.169.250
```

**_How do I get rid of the search domain happysrv.de**_

EDIT: This problem only occurs with containers created with Rancher. Those created directly with Docker contain the correct search path.

**Comment by Joeasaurus** [comment]
I was seeing this issue as well, in the end I just started all over again 😲  I tried putting the rancher.internal domains in there manually so I could force them to go first but it seemed not to fix anything. 

I have resorted temporarily to not specifying any search domains on the host and enforcing that all my services use FQDNs. I'd like to see you find a fix here @dj-hedgehog!

**Comment by dj-hedgehog** [comment]
@Joeasaurus Thanks for chiming in.
I requested a quote for professional Rancher support since the support via GitHub issues is not what I want to build my business on any further.
If there's anything new I'll also write a comment here.

**Comment by vincent99** [comment]
The hosts's resolv.conf is read when the Network Agent container starts up.. so if you're changing it you'll need to restart the container too.

**Comment by kkvilekval** [comment]
I hit this issue today with nodes on my network matching before service names in my docker-compose file.
It appears that it should at least add the host search to the *end* and not the beginning.
I think this should be labelled as a bug..

**Comment by ecliptik** [comment]
@vincent99 stack containers or the network-agent container needs a restart? We recently updated our DHCP options, and while the Rancher hosts (Running RancherOS v0.4.5) picked up the new ones from DHCP, the network-agent containers did not, and therefore all stack containers did not.

Restarting the network-agent container resulted in the RancherOS host going into a disconnected state (which is expected) and required use to fully reboot the host. After reviewing the documentation and code for the rancher-dns service, it seems that all containers point to an internal nameserver, which is running on the network-agent.

So in theory, if the network-agent is updated, shouldn't all the stack containers subsequently also use the new nameservers and domain?

Is it possible to have the network-agent container poll the host configuration and update itself dynamically, much like a dhcp lease? This would save a lot of frustration of having to restart/reboot all of the hosts in an environment whenever we make changes to our DHCP options.

**Comment by aemneina** [comment]
looks like this is an enhancement for (forced or timed) refreshes made to dns.

**Comment by superseb** [comment]
No longer relevant
