### ISSUE TITLE
rancher balancer issue

### ISSUE THREAD

**Issue by zfjoy520** [rancher/rancher#5997]
_Describe your issue here_

1，rancher balancer with  rancher/agent-instance:v0.8.3  ,
haproxy no log

2，can't Additional haproxy.cfg configuration 
   E.g：global secion:
           maxconn  60000
          maxpipes 20000

  but  haproxy.cfg  Parameter repetition。
---

| Useful | Info |
| :-- | :-- |
| Versions | Rancher `v1.1.3` Cattle: `v0.165.8.1` UI: `v1.1.12` |
| Access | `localauth` `admin` |
| Orchestration | `Cattle` |
| Route | `environment.index` |

**Comment by alena1108** [comment]
Fixed in refactored LB v2

**Comment by sangeethah** [comment]
Tested with latest build from master.
This issue is the similar to the issue  reported in  https://github.com/rancher/rancher/issues/5745 which was verified and closed.

@zfjoy520 , fix for this issue will be available in 1.2 release.
