### ISSUE TITLE
Rancher ingress and Traefik: How to properly disable `rancher-ingress-controller`

### ISSUE THREAD

**Issue by Fridus** [rancher/rancher#5999]
**Rancher Version:**
v1.2.0-pre2
**Docker Version:**
1.12.1

Let's try to be simple and comprehensive :wink: It will be about Rancher with Kubernetetes. I am a beginner in k8s and rancher so if you think I misunderstood some points.
I want to use Rancher+k8s for deploying a bunch of different apps. I will use namespaces for isolate each others. 
Hosts are in a private cloud and public traffic will be routed by a historic nginx, configured by hand.

For exposing the app, I am thinking to create one or more Ingress in each namespace/app that should be exposed.
With Rancher ingress, it will create a new container binding a host port for each `Ingress`.
I would use host based rules for being able to bring all the rules together (all rules from all namespaces), expose a single port and is scaled at the number of hosts.

It is possible to accomplish with Rancher Ingress ?

I was able to produce that with [Træfɪk, a modern reverse proxy](https://github.com/containous/traefik). I simply deployed a template like this [k8s.rc.yaml](https://raw.githubusercontent.com/containous/traefik/master/examples/k8s.rc.yaml).
But it conflict with Rancher Ingress controller, for each Ingress created, Rancher create a load balancer and bind a host port.

It is possible to disable Rancher Ingress ?

I tried to stop `rancher-ingress-controller` in the system stack but, 1. it seems hacky, 2. it makes the Rancher UI display view "Setting up Kubernetes..." view.

The question on the forum (asked by my colleague): https://forums.rancher.com/t/rancher-ingress-and-traefik/3930

Thanks

**Comment by alena1108** [comment]
@Fridus stopping an individual container won't help as service reconcile will restart it. You can stop ingress-controller service, and it will disable rancher ingress controller. Note that if you decide to upgrade k8s system stack to the latest template version, the service will be restarted, and you might need to start it again.

**Comment by danielschlegel** [comment]
But if i disable rancher ingress controller the kubernetes view disappear and kubernetes installation get active because this service is not running.

**Comment by rezonant** [comment]
Does rancher ingress obey `kubernetes.io/ingress.class` ?Perhaps that could be used? https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx#running-multiple-ingress-controllers
https://github.com/kubernetes/contrib/blob/master/ingress/controllers/gce/BETA_LIMITATIONS.md#disabling-glbc

**Comment by rezonant** [comment]
Looks like in v.1.1.4 it does not.

**Comment by rezonant** [comment]
I think this should be revisited -- it appears there is no way to disable Rancher's k8s ingress integration without causing Catalog to fail (it returns to the "Setting up Kubernetes" screen)

**Comment by deniseschannon** [comment]
In the latest k8s catalog (k8s v1.6.2), we add in a configuration option to remove the ingress controller.

**Comment by laszlocph** [comment]
@deniseschannon I see an option "Enable Kubernetes Add-ons", that disables all services.

Is there an other option with finer granularity to disable only the ingress controller?

**Comment by deniseschannon** [comment]
@laszlocph This will be available when our template for k8s 1.6.x is released.

**Comment by mcedica** [comment]
I just updated Rancher to 1.6.2 to have this. However I don't see the option ( 'ENABLE_RANCHER_INGRESS_CONTROLLER') in the UI when configuring a template env. ( not a problem in the end)
I edited the template in the API and set this:

> _"type": "catalogTemplate",
> "answers": {
> 
>     "CONSTRAINT_TYPE": "none",
>     "CLOUD_PROVIDER": "aws",
>     "REGISTRY": "",
>     "ENABLE_RANCHER_INGRESS_CONTROLLER": "false",_

However the rancher-ingress-controller still started by default.

**Comment by oskapt** [comment]
@mcedica - support for disabling the ingress controller is in Rancher 1.6.3, released 4 days ago (and not yet tagged stable). This issue is closed, so continuing conversation in it does not notify the Rancher team. If you find that you're still having issues when running 1.6.3 or later, please open a new issue.

**Comment by dweidenfeld** [comment]
How can we set the option?

**Comment by laszlocph** [comment]
Just want to confirm that this works for me.

You can edit the the Kubernetes environment template. 

- Click the first dropdown with your environments and click "Manage Environments". 

- On the environments view on the bottom you see the Environment Templates section, where click edit on the Kubernetes one.

- On this view you can rename your template, etc, change orchestration type. Click "Edit Config".

- Make sure it says "Kubernetes 1.6.6" on the top. You need Rancher v1.6.3 for this. Then find the "Enable Rancher Ingress Controller" radiobutton.

Once you updated this, the next deployment, or your next upgrade will adhere to this setting.

If you watch what the browser send to the Rancher API you will see that it's the ENABLE_RANCHER_INGRESS_CONTROLLER answer in the /v2-beta/projectTemplates/#{kubeTemplateId} endpoint.

**Comment by mcedica** [comment]
Thx! Yes, I was testing with rancher 1.6.2 initially. In Rancher 1.6.4 I can not edit the default Kuberentes template, I see the option, but I get a 404 when saving the template with a PUT at https://ranchertest.io.nuxeo.com/v2-beta/projecttemplates/1pt1. 
However I  have created a new  k8s template and I can disable the rancher ingress controller in the new template

**Comment by tfiduccia** [comment]
@mcedica - I can't reproduce your 404 problem.  Which browser were you using?  Did you change anything else in the config or template beside setting ingress to false?

**Comment by trondhindenes** [comment]
@laszlocph Its unclear to me how I would apply an updated template to an existing environment. I never understood the "templating" stuff in Rancher. Maybe I haven't found the documentation. 
Anyway, I have followed your instructions to disable the Rancher ingress controller. How do I get my current k8s environment updated so that these changes will take effect?

**Comment by laszlocph** [comment]
Go to Kuberetes / Infrastructure Stacks. Under the "kubernetes" collapsable group, click on the "Up to date" or "Upgrade available" buttons on the right side. 

It let's you pick a newer template if there is any, or allows you to fiddle with the settings of the current one. Now I have only upgraded in the past, so I don't know if changing the existing template's params will trigger a reconfiguration, but upgrade does. Hope it will turn the ingress off for you. You might have to delete the ingress controller manually after changing the template. If you do it now without changing the template, it will always redeploy it :)

**Comment by trondhindenes** [comment]
Thanks! What threw me is that the button is actually called "up to date". I'd never thought of that being an entrypoint into changing things up. I'll add a separate bug for that, but I managed to remove the Rancher controller so I'm happy.
