### ISSUE TITLE
UI doesn't show metrics (cpu, storage) for node (agent) on fedora 20 - it just shows "processing"

### ISSUE THREAD

**Issue by abonas** [rancher/rancher#6]
docker version -  1.3

Running rancher/server:latest is successful and it is an active running container. (it shows on docker ps)
However running the second command to bring up the rancher/agent fails with:
"Invalid URL [http://<IP>:9090] or not authorized
Will retry in another second"

Notes - 9090 was set in rancher/server also because 8080 is occupied on that machine.
it was set as 9090:9090

both containers are ran as "root".
firewall is off.

**Comment by MaxNoe** [comment]
I have the same problem running on ubuntu 16.04. 4 machines, multiple containers deployed. No metrics. Just the wheel of death.
