### ISSUE TITLE
Deleting a config causes Choose an existing Balancer Config to be blank

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#600]
v0.17.0
Steps:
1.  Create a Config and name it a
2.  Create another config and name it b
3.  Go to Add Load Balancer page and click on Re-use existing Configuration (notice a is in drop-down)
4.  Click on Cancel
5.  Go back to Configurations list page and delete a
6.  Go to Add Load Balancer page and click on Re-use existing Configuration

Results:
Drop-down is blank

Expected:
b should show up in drop-down as selected

**Comment by vincent99** [comment]
Standalone balancer and configs removed..

**Comment by tfiduccia** [comment]
Config page removed from UI
