### ISSUE TITLE
Sidekick containers that share the primary service's network fail to start

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#6001]
**Rancher Version:**
Rancher	v1.1.3
Cattle	v0.165.8.1
User Interface	v1.1.12
Rancher Compose	v0.8.6

**Docker Version:**
1.10.3

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Deploy the following stack: https://github.com/janeczku/rancher-ts-catalog/tree/master/templates/glusterfs/0

**Results:** 
Some sidekicks always end up stuck in stopped state and are never started thereafter. They can be started manually. An exception is logged for Instance Start. [See here](https://gist.githubusercontent.com/janeczku/d13db4415806f8604a7dc8e461cbb493/raw/7b588b2c0c44e2bad01c44251ff1409210da0da7/InstanceStartException).
**Expected:**
All sidekicks should be running.

This is a regression from v1.1.0 where this stack can be deployed without issues. The same instance start exception can be notices there as well, but after that the container is started successfully.

**Comment by janeczku** [comment]
https://github.com/rancher/rancher/issues/5337

**Comment by alena1108** [comment]
@janeczku 
> Some sidekicks always end up stuck in stopped state and are never started thereafter

Can you elaborate which sidekicks (their names) fail to be restarted?

**Comment by tfiduccia** [comment]
@alena1108 - I added their catalog and built the stack.  It seems to be glusterfs_gluster-node_gluster-volume_1 & 2.  But it's fixed in v1.2.0-pre3 and looks to be working correctly.

@janeczku - This is fixed in 1.2.0-pre3.  So it should work fine when you upgrade.  If you still are having issues, reopen and let me know.

**Comment by janeczku** [comment]
Confirmed that upgrading to v1.2.0-pre3 fixes this issue.
