### ISSUE TITLE
Cannot remove bad named Convoy volume and cannot start Convoy storage pool or agents

### ISSUE THREAD

**Issue by andyshinn** [rancher/rancher#6002]
**Rancher Version:** 1.2.0-pre2

**Docker Version:** 1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):** Ubuntu 14.04 on VMware

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** Single node internal DB on volume mount

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:** Request convoy volume named `${something.something}` via `docker-compose.yml` file

**Results:** Volume gets requested. But Convoy agent and storage pool cannot start because of bad name. Removing / purging the bad named volume also failes with the following error in the storage pool log:

```
time="2016-09-19T18:27:59Z" level=error msg="Error processing event" err="Cannot delete volume 131054. Name: ${bamboo.mi.email.service.volume}. Error: Invalid name ${bamboo.mi.email.service.volume}\n" eventId=ce355c44-b2f3-4611-9e5c-28c714a71408 eventName=storage.volume.remove resourceId=1vspm92614
```

Convoy is now in a broken state and new agents cannot start.

**Expected:** If the name is actually bad, then the volume should be rejected and never requested. Allow removal of the same names that are allowed to be requested.

**Comment by andyshinn** [comment]
The immediate issue is solved by renaming the volume name in the `volume` table of the database. This allows the purge process to finish which gets the storage pool container running again. So, I think the bug here is to just make sure that erroneous volume names get rejected earlier on.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
