### ISSUE TITLE
Not able to deploy Secrets Bridge Server catalog since catalog creation fails with "Cattle Secret Key is required" even though access key is passed.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6003]
Rancher Version: Build from master

Set up:

Try  to deploy Secrets Bridge Server catalog .
Catalog creation fails with "Cattle Secret Key is required" even though access key is passed.

<img width="1566" alt="screen shot 2016-09-19 at 1 30 14 pm" src="https://cloud.githubusercontent.com/assets/4266958/18647978/68b76a74-7e6d-11e6-928a-9575ccaf5916.png">

**Comment by vincent99** [comment]
@sangeethah seems fine to me, the validation for that field goes away if there is a value entered.

**Comment by sangeethah** [comment]
Tested with Rancher-server version - v1.2.0-pre4-rc2
Issue reported in the bug is not reproducible anymore.
