### ISSUE TITLE
K8s system stack not able to start successfully because of 2 instances of etcd being launched in same host.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6004]
Rancher Version: Build from master

K8s templates from - https://github.com/rancher/qa-catalog

Steps to reproduce the problem:
Have a K8s environment with 2 hosts.

K8s system stack is not able to start successfully because of 2 instances of etcd being launched in same host.

etcd containers have the following antiaffinity rule scheduled - ```io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}```

<img width="1289" alt="screen shot 2016-09-19 at 1 55 01 pm" src="https://cloud.githubusercontent.com/assets/4266958/18648712/b39963a0-7e70-11e6-8bd3-7404c7411cd9.png">

<img width="793" alt="screen shot 2016-09-19 at 1 51 25 pm" src="https://cloud.githubusercontent.com/assets/4266958/18648672/88e259aa-7e70-11e6-92c3-6da741076535.png">

**Comment by alena1108** [comment]
@cjellick fixed the bug in services/scalePolicy code. So the only remaining fix is - incorrect labels constraints propagation

**Comment by sangeethah** [comment]
Able to launch 1.4 K8s stack successfully using v1.2.0-pre4-rc3 .
