### ISSUE TITLE
[cli] Can only see one Env that I created, most other commands fail

### ISSUE THREAD

**Issue by IanVaughan** [rancher/rancher#6006]
**Rancher Version:**
Rancher 	v1.1.3
Cattle 	v0.165.8.1
User Interface 	v1.1.12
Rancher Compose 	v0.8.6

**Docker Version:**
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:13:28 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:30:25 2016
 OS/Arch:      linux/amd64

**OS and where are the hosts located? (cloud, bare metal, etc):**
Server : Ubuntu 14.04.4 LTS, Bare metal
Me : OSX 10.11.6

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Rancher on 1 node, 2 hosts added

**Steps to Reproduce:**
Downloaded v0.2.0 from https://github.com/rancher/cli/releases

```
$ rancher config
URL: http://rancher.company.com:8080/v1
Access Key: <from application key>
Secret Key: <from application key>
$ < exits here, no Environments selection, even though there are two envs
```
Can see the new env I created, so I can see access works
```
$ rancher env
ID        NAME                   ORCHESTRATION   STATE     CREATED
1a754     loving-chandrasekhar   Cattle          active    2016-09-06T21:10:56Z
```
But most other commands fail
```
$ rancher hosts
FATA[0000] Failed to find schema at [http://rancher.company.com:8080/v2-beta/projects/1a754/schemas/schemas]
```
I have full access via the Web UI, and can create/remove stacks/envs/etc via that.

Attempting to set it to use another known env (with more stacks in) still fails
```
$ export RANCHER_ENVIRONMENT=1a5
$ rancher stack
FATA[0000] Failed to find schema at [http://rancher.company.com:8080/v2-beta/projects/1a5/schemas/schemas]
$ rancher hosts
FATA[0000] Failed to find schema at [http://rancher.company.com:8080/v2-beta/projects/1a5/schemas/schemas]
```

I cannot see what is missing from my setup or config server side.

**Comment by deniseschannon** [comment]
It sounds like you are using an environment API key instead of an account API key.

**Comment by IanVaughan** [comment]
> It sounds like you are using an environment API key instead of an account API key.

Nope, I created account keys, and recycled them to be sure, same issue.

<img width="1093" alt="screen shot 2016-09-20 at 08 00 10" src="https://cloud.githubusercontent.com/assets/158600/18660494/a98f4594-7f08-11e6-9b23-72d2350345a7.png">

<img width="1883" alt="screen shot 2016-09-20 at 08 03 17" src="https://cloud.githubusercontent.com/assets/158600/18660531/e3f18c42-7f08-11e6-8c18-94ed64695ad3.png">

```
$ rancher --url http://rancher.company.com:8080/v1 --access-key FF605AA5FAA248873C84 --secret-key e3DgYmELP4zjMJMQ51EsQdh25iuY33pNnH2Qd49z env
ID        NAME                   ORCHESTRATION   STATE     CREATED
1a754     loving-chandrasekhar   Cattle          active    2016-09-06T21:10:56Z

$ rancher --url http://rancher.company.com:8080/v1 --access-key FF605AA5FAA248873C84 --secret-key e3DgYmELP4zjMJMQ51EsQdh25iuY33pNnH2Qd49z  stack
FATA[0000] Failed to find schema at [http://rancher.company.com:8080/v2-beta/projects/1a5/schemas/schemas]

$ rancher --url http://rancher.company.com:8080/v1 --access-key FF605AA5FAA248873C84 --secret-key e3DgYmELP4zjMJMQ51EsQdh25iuY33pNnH2Qd49z hosts
FATA[0000] Failed to find schema at [http://rancher.company.com:8080/v2-beta/projects/1a5/schemas/schemas]

$ rancher --url http://rancher.company.com:8080/v1 --access-key FF605AA5FAA248873C84 --secret-key e3DgYmELP4zjMJMQ51EsQdh25iuY33pNnH2Qd49z --env 1a5 hosts
FATA[0000] Failed to find schema at [http://rancher.company.com:8080/v2-beta/projects/1a5/schemas/schemas]
```

`1a5` has all the stacks/hosts on it, `1a754` is a empty env that I created just to prove general API access.

**Comment by deniseschannon** [comment]
As stated in the [release notes](https://github.com/rancher/rancher/releases/tag/v1.2.0-pre3), v0.2.0 is only compatible with v1.2.0-pre3+. 

But I tihnk I need to update the release notes for CLI.
