### ISSUE TITLE
Rancher HA: management stack doesnt show in UI

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#6008]
**Rancher Version:**
1.2.0-pre3

**Docker Version:**
1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
ROS 4.5 EC2 instances

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Rancher HA

**Steps to Reproduce:**
Deployed a fresh rancher HA setup using 1.2.0-pre3. I can see all the containers in the management stack up and running in the host and container views

**Expected:**
GUI should show management stack in the stacks view for the System HA environment.

**Comment by vincent99** [comment]
UI just reports what it sees...

**Comment by aemneina** [comment]
I'll close this and test HA again. Will reopen if I see this and make sure there's a management stack created. Understandably this is NOT a UI issue.
