### ISSUE TITLE
Rancher CLI upgrade service must use compose file?

### ISSUE THREAD

**Issue by Dreampie** [rancher/rancher#6009]
if I want upgrade service image version,why must write a  compose file, `--image/-i xx/tag` will ok?

**Comment by deniseschannon** [comment]
This is currently by design. There is an enhancement request to not pass in files for when the label `io.rancher.container.pull_image: always` is used. 

Since there are multiple services, we most likely wouldn't add in support for `--image/-i xx/tag`

https://github.com/rancher/rancher/issues/3571
