### ISSUE TITLE
The caret character is not read by rancher-compose

### ISSUE THREAD

**Issue by adnan-panalytics** [rancher/rancher#6011]
**Rancher Version:**
v1.1.2
**Docker Version:**
1.12.1
**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 14.04.4 LTS Virtual box 
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Rancher Compose Version**
v0.8.6
**Steps to Reproduce:**
1. Setup rancher and rancher agent 
2. Add the following config to default value for logstash filter question in rancher-compose.yml 
[Logstash rancher](https://github.com/rancher/catalog-dockerfiles/blob/master/logstash/0.2.0/rancher-compose.yml):

```
   label: "Logstash filters"
       type: "multiline"
       required: true
       default: |
          mutate {
            gsub => [ 
              "extra_tags","^\[","",
              "extra_tags","\]$",""]

            add_tag => "GSub"
          }
```

Try to bring up the container with "rancher-compose up" using CLI

**Results:** 
It throws the following error: 
FATA[0000] Failed to read project: Invalid interpolation format for "questions" option in service ".catalog"
ERRO[0000] Failed to open project dev-logging: Invalid interpolation format for "questions" option in service ".catalog": 
**Expected:**
To be parsed correctly and put in logstash.

Interesting sidenote: This filter config works perfectly well if you copy and paste it into the rancher GUI. But you cannot give it as default value for the question and then do a "rancher-compose up" from CLI.

Also, this issue goes away if you remove the caret(^) from the filter. I am not exactly sure why this is occuring. I have tested the YAML for lint and it shows me that is a perfectly valid yaml.

**Comment by slavniyteo** [comment]
rancher-compose v0.12.5 still fails to parse it.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
