### ISSUE TITLE
--swarm errors when trying to create a new Azure host

### ISSUE THREAD

**Issue by taktran** [rancher/rancher#6012]
**Rancher Version:**
v1.2.0-pre3

**Docker Version:**
Docker version 1.11.2, build b9f10c9

**OS and where are the hosts located? (cloud, bare metal, etc):**
Azure on Ubuntu 14.04

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**

I upgraded to `v1.2.0-pre3` from `v1.1.0-dev2` using these [instructions](http://docs.rancher.com/rancher/v1.2/en/upgrading/) (incl creating `rancher-data`), then tried to create a new Azure instance with the following settings
- Name: `something-2016-09-15`
- Environment: [left blank]
- Region: `West Europe`
- Availability Set: [left blank]
- Resource Group: [left blank]
- Subscription ID: `my-id`
- Client ID/Client Secret: `my-id`
- Network: [left blank]
- Image: [left blank]
- Storage: Standard LRS
- Size: `Medium`
- Docker port: `2376`
- Open port: [left blank]
- SSH user: `someone`

**Results:** 

I get the error `--swarm Configure Machine to join a Swarm cluster`.

I've also gotten `--swarm-addr addr to advertise for Swarm (default: detect and use the machine IP)`, and `--swarm-experimental Enable Swarm experimental features` from changing some of the fields around. Can try and replicate if need be. If I change Environment to `AzureCloud`, I get `exit status 1`.

**Expected:**

Machine to be create.

**Comment by tfiduccia** [comment]
@taktran When you say [left blank] do you mean you took out the default information or you just left it alone?

**Comment by tfiduccia** [comment]
So I am unable to reproduce your bug (I am going through the UI) but there are a few suggestion I have for you to try:

1.  Azure machine names but be lowercase alphanumeric and between 4-62 characters.  You can't use uppercase characters or less than 4 characters for the name.
2. I would not leave most of those fields blank. I removed the fields in the UI and they did not use the placeholder info, it sent them through as blank.  Here is what my Placement, Network and Instance sections look like.
![image](https://cloud.githubusercontent.com/assets/11514927/18761484/fe6ed87e-80b9-11e6-8347-21a08d3b232a.png)
![image](https://cloud.githubusercontent.com/assets/11514927/18761497/08ea58dc-80ba-11e6-9637-058a80440f26.png)
![image](https://cloud.githubusercontent.com/assets/11514927/18761505/11480db2-80ba-11e6-9127-395e36a22293.png)
3.  Check the Access in Azure to make sure you have the proper permissions set.

**Comment by tfiduccia** [comment]
@taktran - found a new issue with Azure machine, please see issue #6048.  If you find you need to remove that Azure password - Exec into the server container (`docker exec -it <container id> bash`) and `rm -rf ~/.docker/machine/credentials/azure`
