### ISSUE TITLE
Cannot View Stack Configs

### ISSUE THREAD

**Issue by pythianarceri** [rancher/rancher#6016]
Account set as Admin, can see and do everything else except using the "View Config" link on any of the stacks, getting a red message on the top right corner of the screen showing 
"Exportconfig Error
Unknown action: exportconfig"

and a big error (which i think is the result of the previous error) in the middle of the screen showing:

ERROR Cannot read property 'dockerComposeConfig' of undefined, Reload to try again or log out"
Other admin users are able to see the configs just fine

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.1.3` Cattle: `v0.165.8.1` UI: `v1.1.12` |
|Access|`github` `admin`|
|Orchestration|`Cattle`|
|Route|`environments.index`|

**Comment by tfiduccia** [comment]
I am unable to recreate this error.  Can you give me a little bit more information on the setup:
1.  What type of site access do you have set on the Access Control page?
2. When you do an edit on the environment, what access control (permission level) does this user have?

**Comment by pythianarceri** [comment]
1)My account is authenticated against Githb, 
2) Access Control is set to "Allow members of Environments, plus Authorized Users and Organizations", 
3) I can edit other users accounts so i'm pretty sure my admin rights are there,

PS: There is another user whose account was created at the same time as mine with the same problem

**Comment by pythianarceri** [comment]
The accounts had not bee added as admins to the environments.
