### ISSUE TITLE
Rancher cross-host networking - missing iptables rules

### ISSUE THREAD

**Issue by daankets** [rancher/rancher#6017]
Rancher v1.1.3
Cattle  v0.165.8.1
User Interface  v1.1.12
Rancher Compose v0.8.6
Docker 1.12.1
Ubuntu 16.04.1 LTS
ProxMox KVM hosts with bridged network on primary interface eth0 (192.168.20.0/24)
Single Node Rancher on 192.168.20.10
First host on 192.168.20.20
Second host on 192.168.20.30
Catle environment
Setup the rancher host, and add two agents using a specific host IP (otherwise the network agent will detect the docker0 interface as the primary interface).
Result: the hosts appear in the infrastructure/hosts view, and appear to work.
Setup any stack that requires cross-host communication, and behold: the load balancer remains in 'initializing' state. It seems that monit process causes this.

Exec into one of the network agent shells, and try to ping the other agent at 10.42.x.x: 100% packet loss. Pinging the other host over the docker subnet works though.

`sudo iptables -L -n --line-numbers -t nat`

Shows a lot of these lines:

`280  MARK       all  -- !10.42.0.0/16         169.254.169.250      MAC 02:64:FE:CD:2F:31 MARK set 0x315e8`

But does not seem to produce the correct NAT rules.

`sudo iptables -F -t nat` and then a restart of the network agent causes the following to appear:

```
Chain POSTROUTING (policy ACCEPT)
num  target     prot opt source               destination         
1    MASQUERADE  udp  --  172.17.0.2           172.17.0.2           udp dpt:4500
2    MASQUERADE  udp  --  172.17.0.2           172.17.0.2           udp dpt:500

Chain CATTLE_POSTROUTING (0 references)
num  target     prot opt source               destination         
1    SNAT       all  -- !10.42.0.0/16         169.254.169.250      mark match 0x315e8 to:10.42.202.216

Chain CATTLE_PREROUTING (0 references)
num  target     prot opt source               destination         
1    MARK       all  -- !10.42.0.0/16         169.254.169.250      MAC 02:64:FE:CD:2F:31 MARK set 0x315e8

Chain DOCKER (0 references)
num  target     prot opt source               destination         
1    DNAT       udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:4500 to:172.17.0.2:4500
2    DNAT       udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:500 to:172.17.0.2:500
```

**Expected:**
I would have expected to see DNAT rules for IPSEC traffic on the 10.42.X.X network? Anyway: cross-host communications keep failing, and adding containers etc. does not change anything. All agents were started with the CATTLE_AGENT_IP option. I believe this issue is also the reason why my convoy-nfs agents have been stuck in initialising since they started.

**Comment by aemneina** [comment]
@daankets did you manage to sort this? Sometimes i find the order of firewall rules being programmed prevents docker communication. i typically restart iptables, then docker. Please do reopen if this is still an issue.

**Comment by daankets** [comment]
@aemneina No, I didn't succeed. I've tried restarting iptables, docker in various orders, but without a breakthrough. In the end, I've shutdown the VMs, and started over using the latest RancherOS image. I've in the meantime deleted the old VMs.
