### ISSUE TITLE
rancher/agent-instance:v0.8.3

### ISSUE THREAD

**Issue by zfjoy520** [rancher/rancher#6018]
*Describe your issue here*

env:rancher/agent-instance:v0.8.3

LB：haproxy  maxconn is too less,but How to settle the problem?

i wan't  maxconn = 60000

Additional haproxy.cfg but not effective.

 thank you! 
 from china

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.1.3` Cattle: `v0.165.8.1` UI: `v1.1.12` |
|Access|`Disabled`|
|Orchestration|`Cattle`|
|Route|`hosts.index`|

**Comment by deniseschannon** [comment]
You can customize this in the `global` section of the  load balancer.
http://docs.rancher.com/rancher/v1.2/en/cattle/adding-load-balancers/#custom-haproxycfg

We'll be adding in customization of the `backend` with our [load balancer refactor](#2179)

**Comment by zfjoy520** [comment]
thanks.

In Rancjer Console, Additional haproxy.cfg:

global section ：  maxconn = 60000 

restart balancer

execute shell:  cat  /etc/haproxy/haproxy.cfg


global
        log 127.0.0.1 local0
        log 127.0.0.1 local1 notice
        maxconn 4096
        maxpipes 1024
        chroot /var/lib/haproxy
        user haproxy
        group haproxy
        daemon
        maxconn = 60000


There are two identical arguments   maxconn 

Entry container and restart haproxy like this:

[ALERT] 265/072716 (524) : parsing [/etc/haproxy/haproxy.cfg:10] : 'maxconn' can
not handle unexpected argument '60000'.

this global section ：  maxconn = 60000 is issue！
In Rancjer Console don't Additional haproxy.cfg

**Comment by deniseschannon** [comment]
Please review the [haproxy manual](https://cbonte.github.io/haproxy-dconv/1.6/configuration.html) on how you need to put in custom configurations.

When I search `maxconn`, it looks like it needs to be

```
maxconn 6000
```

Note: There is no `=` in it.

**Comment by zfjoy520** [comment]
oh my god!! 

thank you，thank very much!!

**Comment by zfjoy520** [comment]
but why maxconn variables have not been replaced
??
