### ISSUE TITLE
removed convoy gluster but still visible in GUI

### ISSUE THREAD

**Issue by joostliketoast** [rancher/rancher#6019]
I removed the convoy gluster stack under `system`, but when i navigate to `infrastructure` > `storage` it still shows up there (see screenshot)

![rancher](https://cloud.githubusercontent.com/assets/5398047/18705234/b6e001e4-7fed-11e6-93f8-a630618049e6.png)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.1.3` Cattle: `v0.165.8.1` UI: `v1.1.12` |
|Access|`github` `admin`|
|Orchestration|`Cattle`|
|Route|`storagepools.pools`|

**Comment by deniseschannon** [comment]
Currently, we don't have the ability to delete storage pools.

https://github.com/rancher/rancher/issues/2918
