### ISSUE TITLE
using virtual machines now convoy gluster has been removed

### ISSUE THREAD

**Issue by joostliketoast** [rancher/rancher#6020]
I read that gluster convoy has been removed from the catalog because it wasnt maintained anymore. But how can i now create new virtual machines disks, does it support convoy nfs?
---

| Useful | Info |
| :-- | :-- |
| Versions | Rancher `v1.1.3` Cattle: `v0.165.8.1` UI: `v1.1.12` |
| Access | `github` `admin` |
| Orchestration | `Cattle` |
| Route | `storagepools.pools` |

**Comment by aemneina** [comment]
Convoy nfs should still work, I believe it requires an external NFS server available to the hosts within the environment.

**Comment by aemneina** [comment]
closing this out.
