### ISSUE TITLE
All containers stopping first during stack upgrade, regardless of batch-size

### ISSUE THREAD

**Issue by dmgawel** [rancher/rancher#6021]
**Rancher Version:**
v1.1.1

**Docker Version:**
1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
Rancher on Azure, hosts on DigitalOcean

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node, internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Deploy any stack with `rancher-compose` and S3 build (important part) then run an upgrade with `rancher-compose up --upgrade` without `start_first: true` in the `rancher-compose.yml`.

**Results:** 
All existing containers will stop first, then the new ones will deploy, regardless of batch-size.

**Expected:**
Batch-size should be respected.

Related:
#4837

**Comment by aemneina** [comment]
@dmgawel have you looked into starting new containers before the old ones stop? Take a look [here](http://docs.rancher.com/rancher/v1.2/en/cattle/rancher-compose/upgrading/#starting-new-containers-before-stopping-old-containers) for some reference.

**Comment by aemneina** [comment]
closing issue.
