### ISSUE TITLE
What is the command line to scale app in Rancher/Cattle environment?

### ISSUE THREAD

**Issue by Shyckymn** [rancher/rancher#6022]
Hi everyone!

What is the command line to scale an app in Rancher/Cattle environment?
I want to create a script to check some metrics and take the decision to scale up/down one app, just as in Openshift.
Is it possible?

Regards.

**Comment by deniseschannon** [comment]
Using [Rancher-compose](http://docs.rancher.com/rancher/v1.2/en/cattle/rancher-compose/commands/#examples)

```
rancher-compose scale serviceName=5
```

Using [RancherCLI](http://docs.rancher.com/rancher/v1.2/en/cli/commands/#rancher-scale-reference)

```
 rancher scale <stackName>/<serviceName>=5 <serviceID>=3
```

**Comment by Shyckymn** [comment]
@deniseschannon How can I execute this commands? When I log in my rancher-server container, there's no rancher or rancher-compose command line...

**Comment by aemneina** [comment]
@Shyckymn 

[Rancher CLI](https://github.com/rancher/cli/releases)

[Rancher Compose](https://github.com/rancher/rancher-compose/releases)

**Comment by Shyckymn** [comment]
@aemneina @deniseschannon 
I run rancher config to set the environment variables for the CLI, but when I try to execute rancher command, I got:
```
$ ./rancher stacks
FATA[0000] Failed to find schema at [http://10.8.7.213:8080/v2-beta/projects/1a5/schemas/schemas]
```

**Comment by Shyckymn** [comment]
Same issue with rancher-compose:

```
$ ./rancher-compose up
ERRO[0000] Failed to open project rancher-compose-v0.9.3-rc2: Failed to find schema at [http://10.8.7.213:8080/v2-beta]
FATA[0000] Failed to read project: Failed to find schema at [http://10.8.7.213:8080/v2-beta]
```

**Comment by aemneina** [comment]
@Shyckymn you're probably using a rancher-compose newer than the server can support. In the UI for your rancher server, somewhere in the bottom, you should see a download link with a compatible rancher-compose.

**Comment by Shyckymn** [comment]
@aemneina 
OK, now it works with version 0.8.6. But I didn't find rancher cli available for download. Only rancher-compose.

**Comment by aemneina** [comment]
Rancher CLI is pretty new, I dont think it's in the UI yet, or it might be in the 1.2.0-preX releases...

**Comment by Shyckymn** [comment]
@aemneina 
Ok, I understood...
I made some tests with scale up and down with success.
Is it possible to get the number of containers being executed in a project via CLI, to support a decision for scale up/down?

**Comment by deniseschannon** [comment]
With Rancher CLI, you can get the list of running containers. 

http://docs.rancher.com/rancher/v1.2/en/cli/commands/#rancher-ps-reference

Rancher CLI v0.2.0 is only compatible with 1.2.0-pre3+

**Comment by aemneina** [comment]
i think the rancher cli would report that but not rancher-compose. you might need to experiment with the application and their commands.
