### ISSUE TITLE
Missing /var/lib/cattle in rancher/agent:v1.0.2

### ISSUE THREAD

**Issue by picoCreator** [rancher/rancher#6024]
**Rancher Version:**
Rancher v1.1.3
Cattle  v0.165.8.1
User Interface  v1.1.12
Rancher Compose v0.8.6

**Docker Version:**
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   b9f10c9/1.11.2
 Built:  
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   b9f10c9/1.11.2
 Built:  
 OS/Arch:      linux/amd64

**OS and where are the hosts located? (cloud, bare metal, etc):**
Amazon Linux AMI on AWS EC2

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher, external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle 

**Steps to Reproduce:**
Restarted host server, by recreating a snapshot AMI

**Results:** 

1) rancher/agent:v1.0.2 failed to start

2) tried to manually start it `sudo docker start rancher-agent` but outputs 
`Error response from daemon: get 1c07ab7e9d874945a3258df9e8318a28008591d4ed79345df9317cdc1a6b9554: volume not found` 
`Error: failed to start containers: rancher-agent`

3) Went into `/var/lib/docker/containers`checked for `1c07ab7e9d874945a3258df9e8318a28008591d4ed79345df9317cdc1a6b9554` does not exists (same for `sudo docker volume ls`)

4) Went into `/var/lib/docker/containers/#rancher-agent-hash-here#` checked `config.v2.json`

```
{
...
    "MountPoints":{
        ...
        "/var/lib/cattle":{
            "Source":"","Destination":"/var/lib/cattle","RW":true,
            "Name":"1c07ab7e9d874945a3258df9e8318a28008591d4ed79345df9317cdc1a6b9554",
            "Driver":"local","Relabel":"","Propagation":"","Named":false
        },
        ...
    }
...
}
```

5) First expectation was to assume the volume `1c07ab7e` unexpectedly deleted / removed / etc in this host. However on checking 3 other hosts in the same "rancher infrastructure". Found that each of them points to a "MountPoints" for "/var/lib/cattle" that does not exists. All same format, different ID.

6) Do i assume I CANNOT restart my other 3 host?

**Expected:**
Rancher Agent to auto start up and reconnect

**Follow-up:**

1) Can i safely remove this missing mountpoint?

2) OR can i download an image with /var/lib/cattle and manually mount this back by editing config.

3) Additionally it will be really helpful, if i could in the rancher admin interface. Regenerate the command to re-mount an existing host. That way if such errors occur, i can just remove the "agent" containers, and recreate them.

**Comment by aemneina** [comment]
@picoCreator sounds like you were using the epel (rhel/centos) provided docker rpm. Have you tried this with upstream docker distribution? Can you try that and reopen if the issue is present there.

**Comment by picoCreator** [comment]
@aemneina : Unfortunately i have already long terminated the machine involved. So i am unable to check that.
