### ISSUE TITLE
Port conflict not handled correctly when there is sidekick service

### ISSUE THREAD

**Issue by pengjiang80** [rancher/rancher#6029]
Add a service with following configuration:
1. Primary service has a host port map.
2. Sidekick service just share data volume.
3. Scale number set as 3.

Deploy this service to a env with 3 hosts and 2 of them are loaded and 1 has no container.  It seems the scheduler will schedule the sidekick containers to the same host as it has no container. Then the primary service container failed to start due to port conflict.

Expected behavior: scheduler should detect the primary service port conflict before scheduling the sidekick containers to one host. 

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.1.2` Cattle: `v0.165.8` UI: `v1.1.12` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`container.labels`|

**Comment by tfiduccia** [comment]
@pengjiang80 - was able to reproduce this problem in 1.1.3, but we resolved some port conflict issues in our 1.2.0-pre3 release and it will no longer hang up creating the primary container.  It will still create the sidekick in the wrong host, but will fix itself and recreate the container & sidekick into another host with an open port.  I'm closing this bug, if you continue to have problems after upgrading to 1.2.0, reopen and let me know.
