### ISSUE TITLE
support IAM credentials from EC2 metadata service

### ISSUE THREAD

**Issue by flypenguin** [rancher/rancher#6032]
**Rancher Version:**
all

**Docker Version:**
N/A

**OS and where are the hosts located? (cloud, bare metal, etc):**
EC2

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
N/A

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
N/A

**Steps to Reproduce:**
Do something in Rancher (e.g. create a machine) which requires AWS credentials. 

**Results:** 
Currently you have to provide explicit credentials.

**Expected:**
The EC2 metadata service should be queries in absence of explicit credentials, and if found those should be used.

**Explanation:**
That basic mechanism is supposed to be used in a couple of issues it seems, with at least ...
- 2833
- 3126
  Also you can't create machines using Rancher in EC2 without explicitly providing credentials, which is not the way AWS recommends doing things, and it is cumbersome if the system is already set up.
  My use case right now is to create a machine from the Rancher UI. Maybe it should be a generic interface to EC2 metadata to be used in several function blocks (ECR, create machine, DNS, etc.)

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
