### ISSUE TITLE
make subnet selection readable when creating a machine in AWS EC2

### ISSUE THREAD

**Issue by flypenguin** [rancher/rancher#6033]
**Rancher Version:**
1.1.x

**Docker Version:**
N/A

**OS and where are the hosts located? (cloud, bare metal, etc):**
AWS EC2

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
N/A

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
N/A

**Steps to Reproduce:**
Create a host with Rancher on AWS EC2. You will need to select a subnet. 

**Results:** 
The subnet is _only_ given as "subnet-12541263" value, which is annoying cause you have to look into AWS to figure out which subnet is which (see image below)

![bildschirmfoto von 2016-09-22 14-55-43](https://cloud.githubusercontent.com/assets/5030694/18748984/1bb4e8b8-80d5-11e6-9501-6015de32ea9d.png)

**Expected:**
A netmask (10.10.13.0/24) next to each subnet so know what I am actually doing.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
