### ISSUE TITLE
"Overview" page in Mesos env for readonly user

### ISSUE THREAD

**Issue by aleksejlopasov** [rancher/rancher#6036]
**Rancher Version:**
v1.1.3
**Docker Version:**
v1.12.1
**OS and where are the hosts located? (cloud, bare metal, etc):**
CentOS 7.2
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node/internal DB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Mesos
**Steps to Reproduce:**
- create working mesos enviroment, so you can access Mesos > Overview
- create readonly user for this enviroment
- login to rancher using RO user's credentials
  **Results:** 
  You are going to see "waiting" page instead of Overview. And there is no 'Overview' bookmark in Mesos menu, only 'System'
  You see smth like this:
  Setting up Mesos
  Add at least three hosts
  Waiting for hosts to be active
  Creating Mesos system stack
  Starting services
  Waiting for leading Mesos Master

**Expected:**
You have to see overview page in order to push 'Mesos UI' button and proceed to mesos user interface and inspect current running jobs

How can I see Overview page using readonly user for Mesos?

**Comment by tfiduccia** [comment]
Verified with v1.2.0-pre3
Should go to Mesos Overview page.

**Comment by vincent99** [comment]
This issue seems to have fallen through the cracks..

**Comment by tfiduccia** [comment]
I'm not sure this is right.  The environment is finished setting up.  But the Setting Up box stays up if my user is read-only.  If he has any other permission, the setting up is not there.
![image](https://cloud.githubusercontent.com/assets/11514927/20764616/2ea0f438-b6ec-11e6-84cb-6c396d2479c6.png)

**Comment by oddperfect** [comment]
Same thing happens if Environment Type is kubernetes

**Comment by vincent99** [comment]
Old and n/a to 2.0.
