### ISSUE TITLE
Not able to get temp token after container restart.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6037]
Rancher server version - v1.1.4-rc3

Set up secrets-bridge-server and secret-bridge-agent by following instruction in https://github.com/rancher/secrets-bridge/blob/master/docs/setup.md for k8s environment.

rancher/secrets-bridge version - v0.1.4

Create pods with label - secrets.bridge.enabled: "true".
Once container was up, made sure that /tmp/secrets.txt was present and was able to create permanent token and able to use this token to fetch secrets.

Restart this container.

After the container is restarted , /tmp/secrets.txt that was created has no TEMP_TOKEN set in it.

```
9/22/2016 9:57:42 AMtime="2016-09-22T16:57:42Z" level=debug msg="Sending events to: http://104.154.255.202:8000"
9/22/2016 9:57:42 AMtime="2016-09-22T16:57:42Z" level=info msg="Entering event listening Loop"
9/22/2016 10:26:30 AMtime="2016-09-22T17:26:30Z" level=debug msg="Received action: start, from container: f3486677db4b35077c0c3042b2f9ca177a2a2f0f16ff6f6b387c4e31e7c26148"
9/22/2016 10:26:30 AMtime="2016-09-22T17:26:30Z" level=debug msg="Container type is Kubernetes"
9/22/2016 10:26:30 AMtime="2016-09-22T17:26:30Z" level=debug msg="Pod Name: finaltest2"
9/22/2016 10:26:30 AMtime="2016-09-22T17:26:30Z" level=debug msg="Pod Namespace: finaltest2"
9/22/2016 10:26:30 AMtime="2016-09-22T17:26:30Z" level=debug msg="Labels found: map[string]string(nil)"
9/22/2016 10:26:30 AMtime="2016-09-22T17:26:30Z" level=debug msg="Warning: Secrets bridge key not found"
9/22/2016 10:26:33 AMtime="2016-09-22T17:26:33Z" level=debug msg="Received action: start, from container: c5512b392c1cf54023b397c2aaa7e8792e4413e66386b017ccf20a0d76ab4a08"
9/22/2016 10:26:33 AMtime="2016-09-22T17:26:33Z" level=debug msg="Container type is Kubernetes"
9/22/2016 10:26:33 AMtime="2016-09-22T17:26:33Z" level=debug msg="Pod Name: finaltest2"
9/22/2016 10:26:33 AMtime="2016-09-22T17:26:33Z" level=debug msg="Pod Namespace: finaltest2"
9/22/2016 10:26:33 AMtime="2016-09-22T17:26:33Z" level=debug msg="Labels found: map[string]string(nil)"
9/22/2016 10:26:33 AMtime="2016-09-22T17:26:33Z" level=debug msg="Warning: Secrets bridge key not found"
```

**Comment by cloudnautique** [comment]
In docker container v0.1.5 the agent will wait until labels are populated in metadata for the container.

**Comment by sangeethah** [comment]
With rancher/secrets-bridge:v0.1.5 agent, TEMP_TOKEN in secrets.txt is always empty.

**Comment by sangeethah** [comment]
With rancher/secrets-bridge:v0.1.6 agent, TEMP_TOKEN in secrets.txt gets a value as expected. Able to retrieve secrets using the permanent key that gets generated for contents from  secrets.txt.
