### ISSUE TITLE
Support for k8s network policies 

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#6039]
We should add support for k8s network policies for Rancher network:

http://kubernetes.io/docs/user-guide/networkpolicies/

**Comment by laszlocph** [comment]
Wondering if this will be prioritized in the near future?

As I see Cattle has network policies, so I suppose the basics are in place. Anyways, would be highly appreciated!

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

In 2.0, we've added the ability to turn on/off network policies for canal.
