### ISSUE TITLE
where is rancher/agent-instance:v0.8.3  haproxy logs?

### ISSUE THREAD

**Issue by zfjoy520** [rancher/rancher#6042]
*Describe your issue here*

where is rancher/agent-instance:v0.8.3  haproxy  logs?

i can't find it!

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.1.3` Cattle: `v0.165.8.1` UI: `v1.1.12` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`service.containers`|

**Comment by deniseschannon** [comment]
Duplicate of https://github.com/rancher/rancher/issues/2414
