### ISSUE TITLE
"Failed to find schema" when using rancher-compose since upgrading to Rancher 1.1.3

### ISSUE THREAD

**Issue by dj-hedgehog** [rancher/rancher#6047]
**Rancher Version:** 1.1.3
**Docker Version:** 1.11.3
**OS and where are the hosts located? (cloud, bare metal, etc):** root server
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single node rancher, internal DB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

I've recently upgraded my Rancher server to 1.11.3. Ever since I can't deploy anymore using `rancher-compose`.  I always get the errors logged below.

**Steps to Reproduce:**
rancher-compose --url "http://rancher.example.com:8080/" --access-key $RANCHER_ACCESS_KEY --secret-key $RANCHER_SECRET_KEY --project-name project-test --verbose up --pull -d --upgrade apidocs

**Results:** 

```
time="2016-09-23T14:36:49Z" level=debug msg="Environment Context from file : map[]" 
time="2016-09-23T14:36:49Z" level=debug msg="Opening compose files: docker-compose.yml" 
time="2016-09-23T14:36:49Z" level=debug msg="Opening rancher-compose file: /builds/myproject/api-docs/rancher-compose.yml" 
time="2016-09-23T14:36:49Z" level=debug msg="Not found: /builds/myproject/api-docs/rancher-compose.yml" 
time="2016-09-23T14:36:49Z" level=debug msg="[0/1] [apidocs]: Adding " 
time="2016-09-23T14:36:49Z" level=error msg="Failed to open project project-test: Failed to find schema at [http://rancher.example.com:8080/v2-beta]" 
time="2016-09-23T14:36:49Z" level=fatal msg="Failed to read project: Failed to find schema at [http://rancher.example.com:8080/v2-beta]" 
ERROR: Build failed: exit code 1
```

**Comment by vincent99** [comment]
Where did you download rancher-compose from?  You're using a version that requires Rancher 1.2.x (the v2-beta API)

**Comment by ibuildthecloud** [comment]
The best approach is to download `rancher-compose` from the download link in the UI of the current Rancher installation.  That will always get you the correct version.  We will update rancher-compose to get a more helpful error message in this situation.

**Comment by dj-hedgehog** [comment]
@vincent99 & @ibuildthecloud
I was using a Docker image which installed v0.10.0 of rancher-compose. I'm now building my own image with an older version.
Thanks for pointing me in the right direction.

**Comment by akhy** [comment]
Just ran to similar issue. I'm using `rancher-compose` from homebrew that seems incompatible with my Rancher instance.

Ends up writing a wrapper script that automatically download `rancher-compose` version used by Rancher master defined in `$RANCHER_URL`, similar to gradle wrapper (gradlew)

https://gist.github.com/akhy/1f3efcd32a8b207fa6ba300aa11a4558
