### ISSUE TITLE
Changing client ID & Secret will cause Azure host to fail if new one is valid or create if invalid

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#6048]
**Rancher Version:**v1.2.0-pre3

**Steps to Reproduce:**
1.  Setup an Azure host with all the proper credentials
2.  Setup another Azure host, leave the subscription ID in, but change the Client ID and Secret to aaa

**Results:** Second Azure host setups.

**Expected:** Should not setup

**Comment by vincent99** [comment]
This is an issue with how machine manages credentials, https://github.com/docker/machine/issues/3782

**Comment by tfiduccia** [comment]
This is also causing my Azure host setup to fail as well.  When I entered a different valid client ID & Secret for same subscriptionID, I get an error when it tries to create saying invalid Client.

**Comment by tfiduccia** [comment]
Version - master 11/29
Verified fixed
