### ISSUE TITLE
New labels set for the pod using edit , is not reflected in the contianer's metadata even after container restart.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6049]
Rancher Version:v1.1.4-rc1

Set up secrets-bridge-server and secret-bridge-agent by following instruction in https://github.com/rancher/secrets-bridge/blob/master/docs/setup.md for k8s environment.

Create pod without label secrets.bridge.enabled: "true".
/tmp/secrets.txt is not created as expected.

Edit pod and add abel secrets.bridge.enabled: "true". 

This does not currently result in new labels being added to the container.

Restart container.

After this container has the new labels set ( at the API level) but container metadata still does not see it.

Because of this , /tmp/secrets.txt is still not created on the containers after restart.

**Comment by cloudnautique** [comment]
This would be bad practice for running systems in a real use case. Under normal circumstances the pod would be redeployed under a new version.

**Comment by alena1108** [comment]
Should be fixed with https://github.com/rancher/cattle/pull/2402

**Comment by alena1108** [comment]
@sangeethah not urgent to be validated as it is not very common use case as @cloudnautique already pointed out; feel free to move the target.

**Comment by galal-hussein** [comment]
Rancher server: v1.5.0-alpha1

Steps to validate:
- Run nginx pod.
- Add a new label to the running pod.
- Restart the pod to see the changes in the API
- Check that labels exist in the Rancher API.
- Check container's metadata for the label.

I can see the changes reflected in both the API and the metadata after the restart of the container.
