### ISSUE TITLE
New labels set for the pod using edit is not reflected in the container until restarted.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6050]
Rancher Version: v1.1.4

Create a K8s pod with labels.
This label is reflected in the container in labels field.

Edit pod and add 1 more label.
This label is not reflected in the container in labels fields.

Restarting the container manually , results in the newly added labels being set in the container.

**Comment by alena1108** [comment]
Closing as docker disallows changing labels for running containers: https://github.com/docker/docker/issues/21721
