### ISSUE TITLE
UI is unresponsive and buggy : cluster is unusable

### ISSUE THREAD

**Issue by clescot** [rancher/rancher#6053]
**Rancher Version: 1.2-pre1 to 1.2-pre3**

**Docker Version:*1.11.2 on agents and 1.12.1 on my laptop*

**OS and where are the hosts located? (cloud, bare metal, etc):**
ubuntu on baremetal servers 
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher, external db in a container on the same host than the server.
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
upgrade a rancher server from 1.1 to 1.2-pre-X (firstly tested on 1.2-pre3, but also present on 1.2-pre1 and 1.2-pre-2). 
**Results:** 
UI is unresponsive: the CPU is very high, the browser (firefox and chrome), launch a warn pop up saying that the script run a slow script, and propose to kill it.
when we try to continue, either a blank page is displayed, or the CPU continue to be at top, and the ui is displayed, but we cannot do any action....

when i try to revert to 1.1.3 or 1.1.4, an error page is displayed (with a plane moving around the page).
So, my cluster is **unusable**, unless a fix is provided in the next 1.2-pre-4..... 
Vincent from the rancher team has confirmed the bug from the UI layer  (excerpt from his answer on the forum): 

> The two biggest things are typeify as you've already found (converting plain objects into Ember models) and filtered-sorted-array-proxy's updateContent (sorting & filtering removed/purged resources from most screens). A combination of UI and [backwards compatible] API changes will allow typeify to do less work (recursing over only the fields that have a type that could be another model) and eliminate most filtered arrays (by not returning things we don't to show in the first place).

**Expected:**
Provide quickly a fix to permit to use the UI, or provide a way to rollback to 1.1.X version.

**Comment by jmatsushita** [comment]
Same problem here and I agree it's very painful. I have to wait for several minutes and it only loads sometimes for me. Other members of the team can't access Rancher anymore which has a negative impact on our productivity.

Any updates on the fix? Would be happy to test an early release ;)

**Comment by vincent99** [comment]
There are changes going into a branch today but they require cattle from master and various things are still broken.. You'll want to wait for -pre4.

**Comment by lucacri** [comment]
Same problem for me. It's very frustrating, and I already had 2 outages that I couldn't fix in time because the UI is basically impossible to reach.

If it helps, I have a big deployment (115 servers), and I'm open to answer any question to fix this!

**Comment by clescot** [comment]
Hi,
i think the only possible fix is to stop your 1.2-pre-X rancher server, rollback your mysql database to a previous state (when your rancher server was running a 1.1 release), and launch a 1.1 rancher server.
hope it helps,
Charles.

**Comment by lucacri** [comment]
@clescot How do I roll back the DB? I had a lot of changes in the infrastructure/services since i switched to 1.2-pre-X..

Is there a way to just roll back the schemas changed during the 1.2-pre upgrade?

**Comment by clescot** [comment]
@lucacri , i don't know some way to only rollback  schemas changes done after the 1.2-pre upgrade.
To rollback your db, you need to have previously put a backup mechanism with some kind of retention.
i use with success this mysql backup to aws image : https://hub.docker.com/r/nickbreen/mysql-backup-cron/ 

cheers,
Charles.

**Comment by clescot** [comment]
You should note that a 1.2-pre4-RC1 release is out since few hours, but i don't know if it fix, although partially, our problem......

Charles.

**Comment by deniseschannon** [comment]
Please do not use v1.2.0-pre4-rc1, there are lots of infrastructure changes that still need to be tested.

**Comment by lucacri** [comment]
@deniseschannon I installed the pre4-rc1 just because my cluster is for all intents and purposes useless at the moment. Rc1 is still unusable.. Any way I can revert to 1.1.3?

I can't rebuild the server from scratch because I have 118 hosts

**Comment by vincent99** [comment]
Various changes are in 1.2 to do less work to keep track of changes, spend less time rendering, load less data from the server, etc.  Post-1.2.0 will do paging to render less, as that is now the bulk of the time on the client side.

**Comment by tfiduccia** [comment]
Version - master 10/19
Verified fixed
Still a few refresh issues need to be resolved, those will be entered separately.  Reopen if you are still having issues in next release.
