### ISSUE TITLE
agent fails to connect (aws ec2)

### ISSUE THREAD

**Issue by Dmitry1987** [rancher/rancher#6055]
**Rancher Version:**
v1.2.0-pre3
**Docker Version:**
1.11.2
**OS and where are the hosts located? (cloud, bare metal, etc):**
AWS EC2,  Amazon linux (Centos 6, is closest relative)
**Setup Details:**
single node rancher
**Environment Type:**
cattle I guess?  (adding new host to rancher)

**Steps to Reproduce:**
1. New EC2 amazon linux.
2. `docker run -d --restart=always -p 8080:8080 rancher/server:v1.2.0-pre3`
3. another new EC2 (to add as host) created, logged in
4. run ` docker run -e CATTLE_AGENT_IP="<my new host ip>"  -d --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.0.2 http://<my rancher host public dns>:8080/v1/scripts/B2D3Exxxxxxxxxxxxxxx:yyyyyyyyyyyyyyy`

P.S.  Both EC2 instances have shared security group that allows "All traffic" to itself. Which means those 2 instances can connect to each other on any port both ways.

**Results:** 
**docker log shows (on that new agent creation attempt):**

INFO: Running Agent Registration Process, CATTLE_URL=http://[my rancher host public dns]:8080/v1
INFO: Checking for Docker version >= 1.6.0
INFO: Found Server version: 1.11.2
INFO: docker version: Client version: 1.6.0
INFO: docker version: Client API version: 1.18
INFO: docker version: Go version (client): go1.4.2
INFO: docker version: Git commit (client): 4749651
INFO: docker version: OS/Arch (client): linux/amd64
INFO: docker version: Server version: 1.11.2
INFO: docker version: Server API version: 1.23
INFO: docker version: Go version (server): go1.5.3
INFO: docker version: Git commit (server): b9f10c9/1.11.2
INFO: docker version: OS/Arch (server): linux/amd64
INFO: docker info: Containers: 2
INFO: docker info: Images: 1
INFO: docker info: Storage Driver: devicemapper
INFO: docker info: Pool Name: docker-202:1-263588-pool
INFO: docker info: Pool Blocksize: 65.54 kB
INFO: docker info: Base Device Size: 10.74 GB
INFO: docker info: Backing Filesystem: xfs
INFO: docker info: Data file: /dev/loop0
INFO: docker info: Metadata file: /dev/loop1
INFO: docker info: Data Space Used: 573.8 MB
INFO: docker info: Data Space Total: 107.4 GB
INFO: docker info: Data Space Available: 6.109 GB
INFO: docker info: Metadata Space Used: 1.348 MB
INFO: docker info: Metadata Space Total: 2.147 GB
INFO: docker info: Metadata Space Available: 2.146 GB
INFO: docker info: Udev Sync Supported: true
INFO: docker info: Deferred Removal Enabled: false
INFO: docker info: Deferred Deletion Enabled: false
INFO: docker info: Deferred Deleted Device Count: 0
INFO: docker info: Data loop file: /var/lib/docker/devicemapper/devicemapper/data
INFO: docker info: Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
INFO: docker info: Library Version: 1.02.93-RHEL7 (2015-01-28)
INFO: docker info: Execution Driver:
INFO: docker info: Kernel Version: 4.4.11-23.53.amzn1.x86_64
INFO: docker info: Operating System: Amazon Linux AMI 2016.03
INFO: docker info: CPUs: 2
INFO: docker info: Total Memory: 7.8 GiB
INFO: docker info: Name: ip-172-20-0-157
INFO: docker info: ID: TLBL:HDL6:G7MD:HBZR:RLDW:K3PD:JPBB:B5AT:SS3V:X6DM:72VV:QPWQ
INFO: docker info: Http Proxy:
INFO: docker info: Https Proxy:
INFO: docker info: No Proxy:
INFO: Attempting to connect to: http://[my rancher host public dns]:8080/v1
INFO: http://[my rancher host public dns]:8080/v1 is accessible
INFO: Inspecting host capabilities
INFO: Systemd: false
INFO: Boot2Docker: false
INFO: Host writable: true
INFO: Token: xxxxxxxx
INFO: Running registration
Traceback (most recent call last):
  File "./register.py", line 11, in <module>
    secret_key=os.environ['CATTLE_REGISTRATION_SECRET_KEY'])
  File "/usr/local/lib/python2.7/site-packages/cattle.py", line 45, in from_env
    return gdapi.from_env(prefix=prefix, factory=Client, **kw)
  File "/usr/local/lib/python2.7/site-packages/gdapi.py", line 608, in from_env
    return _from_env(prefix=prefix, factory=factory, **args)
  File "/usr/local/lib/python2.7/site-packages/gdapi.py", line 627, in _from_env
    return factory(**result)
  File "/usr/local/lib/python2.7/site-packages/cattle.py", line 12, in __init__
    super(Client, self).__init__(*args, **kw)
  File "/usr/local/lib/python2.7/site-packages/gdapi.py", line 195, in __init__
    self._load_schemas()
  File "/usr/local/lib/python2.7/site-packages/gdapi.py", line 313, in _load_schemas
    response = self._get_response(self._url)
  File "/usr/local/lib/python2.7/site-packages/gdapi.py", line 262, in _get_response
    headers=self._headers)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 437, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='54.70.61.152', port=8080): Max retries exceeded with url: /v1 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f4137359e50>: Failed to establish a new connection: [Errno 110] Connection timed out',))

**Expected:**
proper new host bootstrap

Most interesting part are those 2 lines:

> INFO: Attempting to connect to: http://[my rancher host public dns]:8080/v1
> INFO: http://[my rancher host public dns]:8080/v1 is accessible

It verifies it has access to that host and port!  And then "fails to connect" during "INFO: Running registration" stage.  What it might be?

Thank you

**Comment by Dmitry1987** [comment]
UPDATE: 
tried to use RancherOS from AWS marketplace, master runs ok with no issues.
tried to connect the "host" (another RancherOS instance), they have ports open to each other with a security group.

Got similar error, this time on "connection test" stage.  Weird thing is:  I can ping master from that host, which means my security group rule of "All traffic" between those 2 instances is working.  (Why only ping, because I didn't find any curl/nc/wget tools in there, and was lazy to install manually...)

the error on agent start is: 


INFO: Running Agent Registration Process, CATTLE_URL=http://[my master ip].us-west-2.compute.amazonaws.com:8080/v1
INFO: Checking for Docker version >= 1.6.0
INFO: Found Server version: 1.12.1
INFO: docker version: Client version: 1.6.0
INFO: docker version: Client API version: 1.18
INFO: docker version: Go version (client): go1.4.2
INFO: docker version: Git commit (client): 4749651
INFO: docker version: OS/Arch (client): linux/amd64
INFO: docker version: Server version: 1.12.1
INFO: docker version: Server API version: 1.24
INFO: docker version: Go version (server): go1.6.3
INFO: docker version: Git commit (server): 23cf638
INFO: docker version: OS/Arch (server): linux/amd64
INFO: docker info: Containers: 4
INFO: docker info: Images: 1
INFO: docker info: Storage Driver: overlay
INFO: docker info: Backing Filesystem: extfs
INFO: docker info: Execution Driver:
INFO: docker info: Kernel Version: 4.4.19-rancher
INFO: docker info: Operating System: RancherOS v0.6.1
INFO: docker info: CPUs: 4
INFO: docker info: Total Memory: 15.67 GiB
INFO: docker info: Name: slave-ip-xxxxx.us-west-2.compute.internal
INFO: docker info: ID: FFQ6:6L2M:QTK3:SPYV:2HKB:WU6V:7MOJ:FE3R:2TMF:GIIA:HISC:SRXY
INFO: docker info: Http Proxy:
INFO: docker info: Https Proxy:
INFO: docker info: No Proxy:
INFO: Attempting to connect to: http://[my master ip].us-west-2.compute.amazonaws.com:8080/v1
ERROR: http://[my master ip].us-west-2.compute.amazonaws.com:8080/v1 is not accessible
ERROR: http://[my master ip].us-west-2.compute.amazonaws.com:8080/v1 is not accessible
...

**Comment by aemneina** [comment]
@Dmitry1987 a quick test that could help is to change the source ip in your security group to be more permissive or fully open temporarily. Can the host add in that case?

**Comment by Dmitry1987** [comment]
@aemneina - I temporarily did "allow from all" in SG.  But it was the same:

INFO: docker info: Operating System: RancherOS v0.6.1
INFO: docker info: CPUs: 4
INFO: docker info: Total Memory: 15.67 GiB
INFO: docker info: Name: ip-172-31-xx-xx.us-west-2.compute.internal
INFO: docker info: ID: FFQ6:6L2M:QTK3:SPYV:2HKB:WU6V:7MOJ:FE3R:2TMF:GIIA:HISC:SRXY
INFO: docker info: Http Proxy:
INFO: docker info: Https Proxy:
INFO: docker info: No Proxy:
INFO: Attempting to connect to: http://ec2-52-xx-xxx-xx.us-west-2.compute.amazonaws.com:8080/v1
ERROR: http://ec2-52-xx-xxx-xx.us-west-2.compute.amazonaws.com:8080/v1 is not accessible
ERROR: http://ec2-52-xx-xxx-xx.us-west-2.compute.amazonaws.com:8080/v1 is not accessible


(The "allow all" SG attached to both master and host, so it seems like a bug)
P.S. This is RancherOS from latest AMI  0.6.1,  ami-46fe2c26
Master node and container works ok... 
**latest master container logs are:**   (master seems to work, i can browse the web GUI)

time="2016-09-26T03:15:18Z" level=info msg="Waiting for handler registration (2/2)"
time="2016-09-26T03:15:18Z" level=info msg="Installing builtin drivers"
time="2016-09-26T03:15:18Z" level=info msg="Starting websocket pings"
time="2016-09-26T03:15:18Z" level=info msg="Initializing event router" workerCount=10
time="2016-09-26T03:15:18Z" level=info msg="Connection established"
time="2016-09-26T03:15:18Z" level=info msg="Starting websocket pings"
time="2016-09-26T03:15:18Z" level=info msg="Downloading all drivers"
time="2016-09-26T03:15:18Z" level=info msg="Copying /var/lib/cattle/machine-drivers/1f7058341420e2f525168052818c3f819ff78e9ca5f57d5a650a049bcd5945e9-docker-machine-driver-packet => /usr/local/bin/docker-machine-driver-packet"
time="2016-09-26T03:15:18Z" level=info msg="Done downloading all drivers"

**Comment by Dmitry1987** [comment]
Also I noticed I can easily reach any master ports, using either EIP or public dns (in example above) from the instance itself.  So it's something with agent container/application that causes the glitch.

Most interesting is the 1st pasted log, where the container itself can connect to master - and right after this little 'health check', it fails to register! :)  Totally weird.

I mean this one: 

**INFO: Attempting to connect to: http://[my rancher host public dns]:8080/v1**
**INFO: http://[my rancher host public dns]:8080/v1 is accessible**  :+1: 
INFO: Inspecting host capabilities
INFO: Systemd: false
INFO: Boot2Docker: false
INFO: Host writable: true
INFO: Token: xxxxxxxx
INFO: Running registration
.....   **and after python error dump we see:**
_"requests.exceptions.ConnectionError: HTTPConnectionPool(host='54.70.61.152', port=8080): Max retries exceeded with url: /v1 (Caused by NewConnectionError(': **Failed to establish a new connection: [Errno 110] Connection timed out'**,))"_ :-1:

**Comment by Dmitry1987** [comment]
omg i am completely useless :D ... 
it appears that I have to go through "add host" in web GUI, to get proper link with correct "secret" for that new host, like in Jenkins ... I thought I can use the same link again and again so just copy pasted it between the attempts, on different hosts.  So stupid of me  ...   I was able to add all hosts now :+1:   

Hope it helps someone else if they google up this issue :D 
I think it could be very helpful to distinct between error codes of "unable to connect" and "wrong secret for host" in that error message I got there....  If it was written something about the "token/secret" I'd instantly realize I need to generate new "docker run .."  link through the web "add host" page.

Thanks  =)

**Comment by aemneina** [comment]
awesome, glad its sorted! I'll close it out.
