### ISSUE TITLE
cannot create aws ec2 host

### ISSUE THREAD

**Issue by opichon** [rancher/rancher#6056]
_Describe your issue here_

I am trying to create a kubernetes environment with an AWS EC2 host.

Rancher is stuck "waiting for a host to be active".

The host has been created in EC2. 

After a while the host gets terminated in EC2.

---

| Useful | Info |
| :-- | :-- |
| Versions | Rancher `v1.1.3` Cattle: `v0.165.8.1` UI: `v1.1.12` |
| Access | `localauth` `admin` |
| Orchestration | `Kubernetes` |
| Route | `authenticated.project.waiting` |

**Comment by tfiduccia** [comment]
I cannot reproduce this issue.  Can you check the logs for errors and let us know what it says?  Also check to make sure your security group has:
1.  From the Rancher server to TCP port 22 (SSH to install and configure Docker)
2.  From and To all other hosts on UDP ports 500 and 4500 (for IPsec networking)

**Comment by nrvale0** [comment]
I've not tried to repro this with k8s but I'm able to reproduce something similar with Cattle. I think it might boil down to docker-machine amazonec2 driver having a bug whereby it does *not* pick up the requested SG if specified as an envvar but *does* if specified as a cmdline parameter.

**Comment by vincent99** [comment]
@nrvale0 the only interface we expose is API -> CLI exec...  How would you set environment variables relevant to go-machine-service?

**Comment by nrvale0** [comment]
@vincent99 The bug I'm seeing, which may or may be related to the above issue, would be if Rancher CLI or go-machine is feeding config options to docker-machine via envvars as opposed to cmdline params or some library function call its possible for the SG info to get lost and cause symptoms similar to the above. I've not had time to look at either the Rancher CLI or go-machine code to see how config data is being handed to docker-machine.

**Comment by nrvale0** [comment]
@tfiduccia Can you share a little more info about how you are provisioning the node? Would this be via  the Infrastructure/Host/Add Host route in the Rancher web console? Or perhaps Rancher CLI?

Also, any chance you could login to the agent node, run:

```ShellSession
$ docker inspect <container id> 
```

and post the **FILTERED** contents here? **BEWARE** - this file contains AWS creds you'll want to remove before posting!

**Comment by opichon** [comment]
I've been using the rancher UI (Host/Add host). I cannot add hosts in DigitalOcean nor in AWS EC2. I believe I follow the instructions and provide correct values for the various fields (DO API key, AWS access key id and secret key).

**Comment by opichon** [comment]
If I create the hosts directly in DO or AWS, I can then add them using the "custom" driver.

**Comment by mediatainment** [comment]
Have the same issue.  

    Almost there…
     Waiting for agent connection
 


Component	Version
Rancher	v1.1.4
Cattle	v0.165.8.4
User Interface	v1.1.14
Rancher Compose	v0.8.6

Deleted all instances and volumes from my AWS demo account. Also deleted "security-group" (rancher-machine). Rancher recreates itself successfully).

<img width="822" alt="bildschirmfoto 2016-10-24 um 16 34 41" src="https://cloud.githubusercontent.com/assets/1597621/19650031/240d7e02-9a08-11e6-9864-4ff54141075b.png">
 Using a User Name (rancher),Access Key Id,Secret Access Key, which is momentary a full access key. Also using the provided ami-7720d918 for my region (eu-central-1).
EC2 is starting up (all green). Did I miss something? I am quite new to AWS and Rancher. Something like loadbalancers or ip addresses?


<img width="1001" alt="bildschirmfoto 2016-10-24 um 16 32 59" src="https://cloud.githubusercontent.com/assets/1597621/19649844/94b2ba42-9a07-11e6-92dd-129cca10613d.png">



<img width="820" alt="bildschirmfoto 2016-10-24 um 16 38 46" src="https://cloud.githubusercontent.com/assets/1597621/19650104/6285d17a-9a08-11e6-9f92-d0e1fd4c4671.png">


I dont know how to get further. Please help!

**Comment by aemneina** [comment]
@mediatainment where is your rancher server? Is it somewhere the agent host can route to?

**Comment by mediatainment** [comment]
@aemneina in a "linode.com" server... accessible over ip and a subdomain

**Comment by aemneina** [comment]
@mediatainment can you try with a RancherOS 0.4.5 image? Not sure if docker 1.12 could be preventing your rancher server cluster from operating properly... or downgrade user docker in the instance.

**Comment by mediatainment** [comment]
I searched in the EC2 AMI list: found these 0.4.5 images:

 **ami-32e9055d**
rancheros-v0.4.5-0-amazon-ecs-optimized-e5e5ad54-a7ab-429a-9f04-c8b8ef7e7a1d-ami-6529c708.3
**Error:**
 ```
      Almost there…
        Waiting for agent connection
```

and this:

**ami-b241acdd**
rancheros-v0.4.5-0-amazon-ecs-optimized - ami-b241acdd
**Error:**
`Error in driver during machine creation: Error launching instance: InvalidAMIID.NotFound: The image id '[ami-4574e036]' does not exist`

then this:

**ami-e4ef038b**
rancheros-v0.4.5-hvm-0-3e977279-1fad-4ebf-bb68-5d6e0d2d0b37-ami-812ec0ec.3

**ERROR**
`Error in driver during machine creation: Error launching instance: InvalidAMIID.NotFound: The image id '[ami-e4ef038b]' does not exist`

and last but not least:

**ami-8740ade8**
rancheros-v0.4.5-hvm-0

**ERROR**
hangs on:
```
Almost there…
 Waiting for agent connection
```


another one
`Error detecting OS: Too many retries waiting for SSH to be available. Last error: Maximum number of retries (60) exceeded`


Do I have to do anything additional?

**Comment by aemneina** [comment]
@mediatainment did you mange to get this working? that last error looks security group related.

**Comment by aemneina** [comment]
@mediatainment if you're still facing this, could you reopen and provide more details?

**Comment by vishal-biyani** [comment]
Using Docker 1.12.3 and AWS I always get time out when adding hosts from EC2 option. 

```
2016-11-14T13:08:04.176938334Z time="2016-11-14T13:08:04Z" level=info msg="stdout: The default lines below are for a sh/bash shell, you can specify the shell you're using, with the --shell flag." resourceId: =1ph10 
2016-11-14T13:08:04.177085158Z time="2016-11-14T13:08:04Z" level=info msg="stdout: " resourceId: =1ph10 
2016-11-14T13:08:04.199576643Z time="2016-11-14T13:08:04Z" level=info msg="cleanup successful" machine name=kube02 
2016-11-14T13:08:04.199607559Z time="2016-11-14T13:08:04Z" level=error msg="Error processing event" err="Error detecting OS: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded" eventId=aeece627-af4f-41b3-8f26-0f4a9b809bb0 eventName="physicalhost.create;handler=goMachineService" resourceId=1ph11 
2016-11-14T13:08:04.268023707Z time="2016-11-14T13:08:04Z" level=info msg="stderr: Error creating machine: Error detecting OS: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded" resourceId=1ph10 
2016-11-14T13:08:04.268077983Z time="2016-11-14T13:08:04Z" level=info msg="starting cleanup..." machine name=kube01 
```
I have tried at least 4/5 times and could not get this going

**Comment by aemneina** [comment]
@vishal-biyani can you reopen a new issue for this. If/when you reproduce this, can you let us know what security group inbound permissions (specifically inbound ports) you're using?

**Comment by vishal-biyani** [comment]
Thanks @aemneina I created https://github.com/rancher/rancher/issues/6622
