### ISSUE TITLE
Rancher-HA unstable ha-initialization

### ISSUE THREAD

**Issue by egrist** [rancher/rancher#6058]
**Rancher Version:** v1.1.3 & v1.1.4

**Docker Version:** 1.10.3

**OS and where are the hosts located?:** vSphere 6 with CentOS 7 OS vm's

**Setup Details:** 3-node Rancher with external 3-node galera cluster

**Environment Type:** This is before using rancher-ha ui

**Steps to Reproduce:** At the first step of http://docs.rancher.com/rancher/v1.2/en/installing-rancher/installing-server/multi-nodes/#launching-rancher-in-ha when I run the script ./rancher-ha rancher/server:v1.1.4

**Results:** Running docker logs -f rancher-ha sometimes (very often and randomly) producing a Go stack trace
Full trace: http://pastebin.com/RfhE8rE3

**Expected:** That no errors occur

**Solution:** Googling around other issues this problem seems to be related to statically linked binaries. Testing compiling with removing "-extldflags -static" from line 9 at https://github.com/rancher/cluster-manager/blob/master/scripts/build and replacing the cluster-manager binary in the rancher/server:v1.1.4 images, this problem cannot any longer be reproduced.

**Note:** Personally I don't code in Golang so I do not know if this might produce any unwanted side effects.

**Comment by guzmo** [comment]
This is very important for our installation of Rancher, without this fix it may fail to setup the cluster ALOT but with this fix it worked 10 out of 10 times. (Y)

No one else having this problem when bootstrapping the cluster?

**Comment by boskiv** [comment]
I also have this in logs. And my cluster continuously get fail/healthy...
```
time="2016-09-30T06:57:34Z" level=info msg="Deleting container af754061735493128ef76f88e1cbc90aa3b97a7d5623b231767081d88c11ee07" component=docker
time="2016-09-30T06:57:34Z" level=info msg="Creating container rancher-ha-tunnel-zk-leader-2" component=docker
time="2016-09-30T06:57:34Z" level=info msg="Container tunnel-zk-client-2 command is different [tunnel -e -s [127.0.0.1]:2182 -t [10.129.4.111]:2181] != [tunnel -d -s [0.0.0.0]:12181 -t [127.0.0.1]:2182]" component=docker
time="2016-09-30T06:57:34Z" level=info msg="Deleting container f4a8dc4c5f629b674440560ff09c755274c646d758ca49395c84118a54cad246" component=docker
time="2016-09-30T06:57:35Z" level=info msg="Creating container rancher-ha-tunnel-zk-client-2" component=docker
time="2016-09-30T06:57:48Z" level=info msg="Forgetting cluster member" component=manager member={250  1f0de2e3-44b0-4c74-8ea7-bb71f4510ea3 10.129.4.110 map[] 0 0 2}
time="2016-09-30T06:57:48Z" level=info msg="Cluster changed, index=0, members=[10.129.4.110, , 10.129.4.109]" component=service
time="2016-09-30T06:57:54Z" level=info msg="Forgetting cluster member" component=manager member={249  4efc19ed-a7b1-46cd-944f-e6b04195a48a 10.129.4.111 map[] 0 43 0}
time="2016-09-30T06:57:59Z" level=info msg="Forgetting cluster member" component=manager member={257  1fecf6f7-06ef-469d-b1e2-f7dac9447db9 10.129.4.111 map[] 0 0 0}
time="2016-09-30T06:57:59Z" level=info msg="Cluster changed, index=0, members=[10.129.4.110, 10.129.4.111, 10.129.4.109]" component=service
time="2016-09-30T06:57:59Z" level=info msg="Creating container rancher-ha-tunnel-redis-2" component=docker
time="2016-09-30T06:57:59Z" level=info msg="Creating container rancher-ha-tunnel-zk-quorum-2" component=docker
time="2016-09-30T06:58:00Z" level=info msg="Creating container rancher-ha-tunnel-zk-leader-2" component=docker
time="2016-09-30T06:58:00Z" level=info msg="Creating container rancher-ha-tunnel-zk-client-2" component=docker
time="2016-09-30T06:58:51Z" level=info msg="Cluster changed, index=0, members=[10.129.4.110, 10.129.4.111, ]" component=service
time="2016-09-30T06:59:10Z" level=info msg="Forgetting cluster member" component=manager member={260  a64181c6-ff04-4323-8eff-b999a6c2fa3e 10.129.4.111 map[] 0 14 2}
time="2016-09-30T06:59:10Z" level=info msg="Cluster changed, index=0, members=[10.129.4.110, , ]" component=service
```

**Comment by egrist** [comment]
Yep, the latter seems to be a consequence. Makes it really hard to setup the cluster.

**Comment by egrist** [comment]
@ibuildthecloud could you shed some light on this issue?

**Comment by deniseschannon** [comment]
With the new HA in 1.2, this is no longer applicable as we've refactored HA to be much simpler and just run additional arguments with the rancher-server command.
