### ISSUE TITLE
Disable externally dependent Machine drivers by default

### ISSUE THREAD

**Issue by chrisurwin** [rancher/rancher#6061]
**Rancher Version:**
All

There are issues with companies that block access to github by default, which causes the go-machine-service problems as it will constantly attempt to download a couple of our default enabled machine drivers.

Would it be possible by default to only enable drivers that are embedded in the Rancher image to stop the attempts and allow people to turn it on by the UI or via the API if they require it?

**Comment by vincent99** [comment]
https://github.com/rancher/rancher/issues/6040
