### ISSUE TITLE
rancher vm hairpin NAT not working

### ISSUE THREAD

**Issue by Oro** [rancher/rancher#6065]
**Rancher Version:**
1.1.3
**Docker Version:**
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64

**OS and where are the hosts located? (cloud, bare metal, etc):**
DISTRIB_ID=RancherOS
DISTRIB_RELEASE=v0.6.0
Bare metal
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher, internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Start a new VM ( rancher/vm-ubuntu ) and port forward 80, login via ubuntu/ubuntu

sudo apt-get update && sudo apt-get install -y nginx
curl externalip:externalport

**Results:** 
curl: (56) Recv failure: Connection reset by peer

**Expected:**
Nginx start page

curl localhost:80 works, doing the same steps with a docker container instead of a VM works as well.
I suspect the issues described in https://github.com/rancher/rancher/issues/1920 is surfacing on the VM containers as well

**Comment by aemneina** [comment]
hey @Oro have you tried this with rancher OS v0.4.5? docker 1.12 and rancher 1.1.x dont generally play nice. I'd be interested in seeing if a known good combination works in this scenario.

**Comment by Oro** [comment]
Hi @aemneina , thanks for the reply.
I have just now tried it on docker 1.11 and 1.10 (via `ros engine switch`, according to https://forums.rancher.com/t/rancheros-release-v0-5-0/3285 one cannot downgrade to 0.4.5), both with the same result as above unfortunately.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
