### ISSUE TITLE
Use AWS EC2 available key pair to provision agent host

### ISSUE THREAD

**Issue by cafeliker** [rancher/rancher#6066]
**Rancher Version:**
1.1.3
**Docker Version:**
1.10.3
**OS and where are the hosts located? (cloud, bare metal, etc):**
AWS EC2
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
ALL
**Steps to Reproduce:**
When I used Racher UI to provision a new agent host, Rancher would generate a new SSH key pair for each box, and if I want to SSH to the agent host, I have to download the machine config 1 by 1 - it's too complex.
**Expected:**
Can Rancher allow users to select an available AWS EC2 key pair and use it to provision all agent hosts? It will be much easier for operation purpose.

**Comment by will-chan** [comment]
We are looking to add some type of first class "cloud provider" object that can include SSH certs, API keys and passed into DockerMachine to be reused.

**Comment by ibuildthecloud** [comment]
Support for this has been added to the API in 1.5.x but remains undocumented and experimental.  Full support in the UI/CLI should come in the following release.

**Comment by maestrofx** [comment]
Hi @ibuildthecloud , is this issue solve in v1.6.3? https://github.com/rancher/rancher/releases/tag/v1.6.3
And where can I find the roadmap for the next release?

Thank you.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
