### ISSUE TITLE
OVH not predefined Machine Driver

### ISSUE THREAD

**Issue by larsmagnusherland** [rancher/rancher#6068]
Rancher Version: 1.14
Docker Version: 1.12
OS: cloud / VPS / Ubuntu 16.04 LTS
Setup Details: Single node rancher
Environment Type: Cattle

**Steps to Reproduce:**
Try to provision a server to OVH cloud with "Add host", no choice for OVH.
Try to enable Machine Driver, no choice for OVH.
Manually try to add, hard to set up and all "gits" available doesn't work in all cases of Operating System.

**Results:** 
No machine drivers, and setting them up towards the API is hard.

**Expected:**

Large providers (France, Canada) which are used for Docker and other cloud software, should have already set Machine Drivers like DigitalOcean etc.

**Comment by deniseschannon** [comment]
Rancher uses docker-machine to launch machines. 
When docker-machine supports OVH, then Rancher would be able to support it as well.

**Comment by vincent99** [comment]
There is a 3rd party driver you can try:  https://github.com/yadutaf/docker-machine-driver-ovh

**Comment by StefB** [comment]
For ovh you can use the openstack driver
