### ISSUE TITLE
Can't use swarm in remote (bad cert) 

### ISSUE THREAD

**Issue by izhilenkov** [rancher/rancher#6069]
**Rancher Version:** 1.1.4

**Docker Version:** 1.12

**OS and where are the hosts located? (cloud, bare metal, etc):** ubuntu 14.04 DigitalOcean

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single node/internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Swarm

**Steps to Reproduce:**
1. Create Swarm env
2. Generate certs
3. Install certs on local machine
4. Trying to see continuers (docker ps)
**Results:** 
An error occurred trying to connect: Get https://**.**_.__._**:8080/v1.24/containers/json: x509: certificate is valid for 127.0.0.1, not **.**_._****
**Expected:**
Watching running containers

**Comment by vincent99** [comment]
This is presumably not relevant with 1.2+ and new swarm[kit]
