### ISSUE TITLE
CatalogIcon doesn't update on refresh catalog

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#6071]
**Rancher Version:** v1.2.0-pre3

**Steps to Reproduce:**
1.  Create a template with catalogicon and view it in the UI
2.  Replace the catalogicon, upload it and click on the refresh catalog button

**Results:** Still shows old image

**Expected:** Should show new image

**Comment by westlywright** [comment]
@prachidamle Is there a trick to getting the catalog service to pull the updated catalog? When selecting the refresh icon from the UI it fires off the get catalogs call correctly. The only way I was able to update the image of a catalog item was by removing my catalog in the ui and adding it with a different name. If I gave it the same name as my previous catalog the old version of the templates exists. This indicates to me that catalog service is caching the catalog and I do not see a way to tell the catalog service that it needs to fetch the user added catalog again. 

cc @vincent99

**Comment by westlywright** [comment]
@prachidamle it seems the api is not letting the browser know that it needs to clear the cache of the image. @vincent99 indicated this could be done with "etags" and the "last-modified" header.

**Comment by prachidamle** [comment]
@mrajashree can you check with @vincent99 what needs to be set in the response

**Comment by mrcamp** [comment]
I'm on 1.1.4 and am having the same issue, but with the entire Catalog entry itself. If I push updates to the docker/rancher-compose files (such as adding a new question), Rancher Catalog will take several minutes to detect these changes. The only guaranteed way to have Rancher Catalog update is to remove my repo from the Settings and re-add it.

**Comment by deniseschannon** [comment]
@mrcamp Have you used the refresh button to update the catalog entries? It's located on the catalog page in the upper right hand corner.

**Comment by mrcamp** [comment]
Heh, I feel pretty dumb for not noticing that button by now. Thanks!
