### ISSUE TITLE
Catalog doesn't get removed when removed from settings

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#6072]
**Rancher Version:** v1.2.0-pre3

**Steps to Reproduce:**
1.  Add a catalog through settings
2. Remove the catalog through settings

**Results:** Even thou you can't see it in the UI anymore, it is still stored on disk.  And if you readd it using the same Name, it will pull the cached version.

**Expected:**  Should remove the catalog.

**Comment by vincent99** [comment]
It seems clear we should delete the entries on disk when a catalog is removed.  But we will need to special case the ones embedded into the build (infra/rancher/community) or they won't work offline after disabling/re-enabling.  Something like checking for a `.nopurge` file in the root of the repo

**Comment by mrajashree** [comment]
@vincent99 so should I start by adding this `.nopurge` file in the embedded catalogs? Also we're sure that the users don't need to see the cached versions of deleted catalogs that aren't embedded if they add them back in non internet mode right?

**Comment by tfiduccia** [comment]
Version - v1.2.0-pre4-rc5
Verified fixed
