### ISSUE TITLE
Add in upgradeFrom and maximum_rancher_version in rancher-compose for catalog service

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#6073]
Added new fields into rancher's catalog service, which need to be added into rancher-compose

**Comment by mrajashree** [comment]
The `upgradeFrom` field can hold three types of values
1. Just a number: `1.0.0`, 2.0.0`
2. Number with an operator: `>=1.0.0.`, `<=2.0.0`
3. Range: `>1.0.0 <2.0.0 || >3.0.0`

**Comment by sangeethah** [comment]
Tested with rancher-server version - v1.2.0-pre4-rc1
Rancher catalog service now supports for upgrade_from and  maximum_rancher_version fields to be added in the rancher-compose.yml.

UI needs to pass maximumRancherVersion_gte=<currrent rancher server version> to http://<server-version>:8080/v1-catalog/templates/ to use the maximum_rancher_version fields set on rancher-compose.yml.

**Comment by tfiduccia** [comment]
Version - master 10/27
Verified fixed
