### ISSUE TITLE
Healthcheck with headers

### ISSUE THREAD

**Issue by guzmo** [rancher/rancher#6076]
Hey!

Is it possible to add headers to healthchecks? Alot of our applications need a specific header to be present to return a 2xx/3xx http respons. If we can't add headers we will not be able to use healthchecks until we add some other health endpoint in our applications.

Thanks

**Comment by guzmo** [comment]
I'm currently trying with OPTIONS requests instead of GET. Maybe this will be a workaround for now

**Comment by vincent99** [comment]
Not in the UI, but the request line and host header are actually one field in the API because that's how haproxy takes it.  So you should be able to set it to `GET /blah HTTP/1.1\r\nHost: blah.com\r\nAny-Other-Header: value\r\n...`in the API or compose.  (Literal backslashes need to appear in the string, not an actual CR/LF, so you may need to escape them).

**Comment by guzmo** [comment]
Ok, thanks! Would be nice if this got documented in the healthcheck section :)

**Comment by guzmo** [comment]
Oh btw, it has to be HTTP/1.1?

**Comment by vincent99** [comment]
You can do HTTP/1.0, maybe even 2.0 but I dunno if haproxy would know how to parse the response.  The requestLine is given directly to haproxy and that's what it writes out when the connection opens.

**Comment by guzmo** [comment]
When i try it I get 

`
time="2016-09-30T20:27:18+02:00" level=fatal msg="Failed to read project: yaml: line 153: mapping values are not allowed in this context" 
`

requestLine 
`    
request_line: GET /school/rest/v1/roles HTTP/1.1\r\ntest: test
`

I've also tried 
`    
request_line: GET /school/rest/v1/roles HTTP/1.1\\r\\ntest: test
`

Something you seen before?

**Comment by guzmo** [comment]
It seems it doesn't like the : in the yml file. I'm running with rancher-compose, anyway to escape it?

**Comment by vincent99** [comment]
That's invalid YAML because you have an unquoted string with a colon in it

**Comment by guzmo** [comment]
Oh gosh, ofc it is, thanks :P

**Comment by guzmo** [comment]
If someone looks for the answer this is how I solved it.

`request_line: "GET /healthcheck HTTP/1.0\\r\\nheader:\ myheader"`

Its not allowed with whitespace in in the header / after semicolon so if you want one you have to escape it with a \ or remove the whitespace.
