### ISSUE TITLE
Inter host networking with --iptables=false

### ISSUE THREAD

**Issue by svensp** [rancher/rancher#6077]
**Rancher Version:**
v1.2.0-pre3 currently, first started in 1.1.0

**Docker Version:**
v1.12.1

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu Xenial on Kernel 4.4 - vhost
Debian Jessie on Kernel 4.7 - vhost and bare metal both act the same, vhost in most recent attempt

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node Rancher with external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Fresh debian jessie install with sources:
- backports -> Kernel 4.7
- docker -> 1.12.1
Add docker option: --iptables=false
Install ufw

Set in /etc/default/ufw: DEFAULT_FORWARD_POLICY="DROP" -> "ACCEPT"
Set in /etc/ufw/before.rules:

*nat
:POSTROUTING ACCEPT [0:0]
-A POSTROUTING ! -o docker0 -s 172.17.0.0/16 -j MASQUERADE
COMMIT

Add ufw Rules:
ufw allow 500udp
ufw allow 4500/udp
ufw allow from RANCHERHOST
ufw allow from DIFFERENTHOST

**Results:** 
If the new host and the DIFFERENTHOST both have set --iptables=false then the inter-host networking does not connect. Uppon restarting the other network container instance each server says "NO_PROPOSAL_CHOSEN" and "Could not start, no trap chosen"

Interestingly, if only one host has --iptables=false then a connection is established

**Expected:**
The inter host networking connects despite --iptables=false being set for docker OR the documentation states what iptables rules have to be set to allow inter host networking through rancher

**Comment by aemneina** [comment]
hey @svensp as you noticed running with --iptables=false breaks networking for nat'ed containers and rancher in general. if you were really interested in the basic set of rules to accomplish this I suggest you get a baseline working setup, take a look at the iptables-save output, then recreate it with iptables disabled on docker. As of today this is a non-supported case. Closing the issue.
