### ISSUE TITLE
Perf branch Services & Volumes issues

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#6083]
**Rancher Version:** Performance

**Steps to Reproduce:**
1.  Try to create a service

**Results:** 

Stacks:
- [x] Cloning first service in stack list, causes services to be in different order after cancelling.
- [ ] **(API)** Services don't show up unless I refresh (main stack and stack detail pages) - looks like just Service Alias and External service now.

Add Service:
- [ ] tty is always true (Console options are not changing)

Add Load Balancer
- [x] Load Balancer won't create, First target isn't recognized so won't let me add says "Choose one or more targets to send traffic to"

Add Service Alias:
- [x] If you only have one target, it's not saved (serviceLinks not sent)

Volumes:
- [ ] Purging Volumes gives me a "Purge Error Validation failed in API: Action" red box in upper right.
  ![image](https://cloud.githubusercontent.com/assets/11514927/19009541/dab9311a-8729-11e6-86f3-5bbf884ef606.png)

**Comment by vincent99** [comment]
@tfiduccia I think these have all been addressed in other issues; leaving the ones that are unchecked that way so you know

**Comment by tfiduccia** [comment]
Version - master 11/06
Verified fixed
