### ISSUE TITLE
test_virtual_machine_create_cpu_memory fails on Drone due to Deadlock while updating config_item status

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#609]
Observed test_virtual_machine_create_cpu_memory failing on Drone couple of times with "Failed to find a placement" error caused by DeadLock during the config_item update

![screen shot 2015-04-24 at 10 01 52 am](https://cloud.githubusercontent.com/assets/1562176/7324172/b2ee9026-ea68-11e4-8d07-fbf1d9bd8fff.png)

![screen shot 2015-04-24 at 10 05 23 am](https://cloud.githubusercontent.com/assets/1562176/7324223/2ff00c1c-ea69-11e4-9eb6-71e3d53bfcd7.png)

**Comment by alena1108** [comment]
Never had this error when run integration tests locally; happens on Drone only

**Comment by sonchang** [comment]
Yeah.  I've seen this deadlock error occur in drone multiple times too.  A
lot of times it seems to cause a lot of other test failures downstream.

**Comment by alena1108** [comment]
Haven't seen this problem for a while; with all the refactoring done for config items there is a high chance it was fixed along the way. Closing for now
