### ISSUE TITLE
Swarm Cluster did not up

### ISSUE THREAD

**Issue by boskiv** [rancher/rancher#6091]
**Rancher Version:**
1.1.4
**Docker Version:**
1.12
**OS and where are the hosts located? (cloud, bare metal, etc):**
ubuntu 16.04
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node vs external 
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
swarm
**Steps to Reproduce:**
add hosts to swarm env
**Results:** 
![2016-09-30 16 52 52](https://cloud.githubusercontent.com/assets/1939783/18993974/7dc9d73e-872e-11e6-9136-2156aa4e2a0f.png)

**Expected:**

**Comment by boskiv** [comment]
https://gist.github.com/boskiv/af0ea719f9236e0810d765c074ac5bff

**Comment by vincent99** [comment]
Assuming this is not revevant in 1.2+ / new swarmkit, if it is please reopen.
