### ISSUE TITLE
give better (fqdn) domain names to services rancher controls

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#6093]
Seen this a couple times where there would be a service resolving to 'master' in an environment preventing ranchers k8s stack to launch. 

this might apply to more than ranchers k8s. can system templates use fqdn's like blah.rancher.internal, to avoid these potential traps.

**Comment by aemneina** [comment]
Targeting this for rancher 1.2.0 and kubernetes 1.4+. All future fixes are going there, as there is no concept/support of rolling back.

**Comment by LLParse** [comment]
This isn't resolved yet, there are kubernetes template changes and kubernetes image changes dependent on the cattle PR just recently merged.

**Comment by sangeethah** [comment]
Tested with Rancher Version: v1.2.0-pre4-rc3 and
K8s 1.4 version from - https://github.com/rancher/infra-catalog

K8s templates dont have referrances to http://master  like before. Instead we have  referrances to 
http://kubernetes.kubernetes.rancher.internal .

We should be able to remove the dependency of having to name the stack as "kubernetes" which is tracked in https://github.com/rancher/rancher/issues/6300
