### ISSUE TITLE
Double load balancer broken if only the first LB handles https

### ISSUE THREAD

**Issue by scytacki** [rancher/rancher#6099]
**Rancher Version:** 1.1.4

**Docker Version:** 1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):** AWS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single node, external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:**
1. setup a simple app that prints out the URL used for accessing the app
2. setup a rancher load balancer
3. setup a AWS load balancer that handles https requests and only sends http to the rancher load balancer
4. make an https request to the AWS load balancer with https://example.com

**Results:** 
The app will return https://example.com:80

**Expected:**
The app should return https://example.com

This used to work fine in an earlier version of Rancher. 
The problem is caused by this PR: https://github.com/rancher/cattle/pull/1799
That PR sets `X-Forwarded-Port` to the port of the request. 
In the scenario above the AWS load balancer has already set the `X-Forwarded-Port` to 443. The rancher load balancer then overrides that setting, which messes things up.

I'm not sure the correct haproxy config for this, but what it should do is:
If X-Forwarded-Port is set, don't change it.
Else set X-Fowarded-Port to the request port (dst_port in haproxy terms)

**Comment by vincent99** [comment]
Yes, that should be add-header; @alena1108 can you patch if it still applies to refractored balancer?

**Comment by alena1108** [comment]
@vincent99 I'd have to patch both, v1 and v2 balancers, thanks @scytacki

**Comment by alena1108** [comment]
https://github.com/rancher/lb-controller/pull/15/commits/56f4654022aa3830221bd30123b95c67f5784e5c

**Comment by deniseschannon** [comment]
@scytacki After 1.2 ships, would you be able to test that this works for your setup? In the release notes, we'll be adding in upgrade instructions or you can try a fresh install to test it as well.

**Comment by deniseschannon** [comment]
@scytacki If after 1.2, you still face issues, please reopen and let me know.
