### ISSUE TITLE
Reverse DNS

### ISSUE THREAD

**Issue by johnhoran** [rancher/rancher#6104]
Rancher Version: v1.1.4

Just wondering if it would be possible to add support for rDNS queries.  I see rancher-dns supports PTR records, so I hope it wouldn't be too hard.  It would be useful for running hadoop inside rancher.

Thanks

**Comment by frol** [comment]
Is there a way to workaround enabling reverse DNS support for Rancher services?

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
