### ISSUE TITLE
Can't ping pods/containers by their hostname - Cent OS

### ISSUE THREAD

**Issue by raveekiran** [rancher/rancher#6105]
**Rancher Version:v1.1.4

**Docker Version:1.12.1

**OS and where are the hosts located? (cloud, bare metal, etc):Centos 7, Bare Metal

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB): Single node rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos):Kubernetes

**Steps to Reproduce: Create multiple pods via RC or deployment and  ping pods/containers by their hostnames

**Results: When I ping containers by their hostname, I am getting an unknown host exception,

**Additional Info:/etc/resolve.conf contents
[root@cisdev-node-i2ecf /]# more /etc/resolv.conf
search default.svc.cluster.local svc.cluster.local cluster.local ranch
er.internal kubelet.kubernetes.rancher.internal kubernetes.rancher.internal
nameserver 169.254.169.250

**Expected:I expect DNS to resolve the hostname and provide an ip associated with that hostname
<img width="1394" alt="rancher" src="https://cloud.githubusercontent.com/assets/22513991/19028115/695d9de2-8906-11e6-8811-ff8075247fd0.png">

**Comment by wlan0** [comment]
@raveekiran Can you check and confirm that you can ping the hosts from outside the container?

**Comment by raveekiran** [comment]
Yes I can ping hosts outside the containers

**Comment by wlan0** [comment]
@raveekiran We are looking into this.

**Comment by wlan0** [comment]
This needs to be fixed before we can verify that hostnames can be pinged - https://github.com/rancher/rancher/issues/6326

**Comment by raveekiran** [comment]
Thanks!

**Comment by galal-hussein** [comment]
the pod's name was resolved to the Pod's IP successfully in kubernetes 1.4.6, however i wasn't able to resolve "pod-ip-address.my-namespace.pod.cluster.local"

**Comment by wlan0** [comment]
@raveekiran We've moved to SkyDNS from RancherDNS, and i tested that pod-ip-address.my-namespace.pod.cluster.local is resolvable.

Here's the documentation for SkyDNS resolution - http://kubernetes.io/docs/admin/dns/
