### ISSUE TITLE
Unable to add service using EFS volume

### ISSUE THREAD

**Issue by bkuhl** [rancher/rancher#6107]
I provisioned an EFS volume with all default settings on the same VPC/subnets as my hosts.  I launched the EFS catalog item and it's in a "Requested" state.  When I look at the log output for `rancher/convoy-agent:v0.10.0` I can see that the mount command is is using the correct URL for EFS but the error `mount.nfs: Connection timed out` appears.  The default security group on the EFS volume is wide open, so there shouldn't be any connectivity issues between EFS and the hosts.

![screen shot 2016-10-03 at 10 37 47 am](https://cloud.githubusercontent.com/assets/524933/19042029/6dc3faa0-8958-11e6-8cbb-cc66b64e3f08.png)

Despite the containers stuck at Initializing, the storage pool shows as `Active` within the storage section.

![screen shot 2016-10-03 at 10 59 32 am](https://cloud.githubusercontent.com/assets/524933/19042042/7a490c98-8958-11e6-9542-6dcc80cd6fc7.png)

What can I check to determine why this is timing out?  

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.1.4` Cattle: `v0.165.8.4` UI: `v1.1.14` |
|Access|`github` `admin`|
|Orchestration|`Cattle`|
|Route|`service.containers`|

**Comment by bkuhl** [comment]
I've followed the steps defined in https://docs.aws.amazon.com/efs/latest/ug/security-considerations.html#network-access for making sure my `rancher-machine` security group can talk to EFS.

**Comment by bkuhl** [comment]
Putting EFS in the `rancher-machine` security group appears to have resolved the issue.  Now I'm seeing the mount failing because `reason given by server: No such file or directory` which is a different issue I'll investigate.

**Comment by bkuhl** [comment]
Using `/` as the mount directory resolved the issue.

**Comment by ltutar** [comment]
Thank you for the instructions. It helped me getting EFS working.

**Comment by rodrigdav** [comment]
@bkuhl thanks for the help.  Mine ended up working after I set `/` as the mount directory.  Is there anywhere that is documented or should be documented?
