### ISSUE TITLE
Kubernetes Environment Broken When docker.network.subnet.cidr Setting Is Not 10.42.0.0/16

### ISSUE THREAD

**Issue by MattMencel** [rancher/rancher#6113]
See this thread for more details:  https://forums.rancher.com/t/could-not-determine-network-mode-for-container-using-none-networking/3981/3

**Rancher Version:**
1.2.0-pre3

**Docker Version:**
1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):**

VMware ESXi (with vCenter).  VMs are running CentOS Atomic.

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

Single node rancher server.  Three node kubernetes environment.

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

Kubernetes

**Steps to Reproduce:**
1. Modify default docker.network.subnet.cidr
2. Start a new Kubernetes environment
3. Attempt to deploy an app from the catalog

**Results:** 

Docker server logs show errors like below over and over.  The service deployed from the catalog never starts.  Even though a different subnet was configured in docker.network.subnet.cidr, the k8s environment brings services up in 10.43.0.0/16.

Could not determine network mode for container [externalId: 05f38d3f25c1e239a3a0b3dec4f71252404e0b81f78bda13e33e2c26d3bc8d31]. Using none networking.

**Expected:**

New services start in the CIDR defined in docker.network.subnet.cidr.

**Comment by will-chan** [comment]
@janeczku Didn't you add a fix to address this?

**Comment by janeczku** [comment]
@will-chan Looks like a cattle issue as OP is overriding the default Rancher Managed Network subnet (`docker.network.subnet.cidr`). The mentioned fix is unrelated (overriding the Docker bridge IP).

**Comment by janeczku** [comment]
ping @alena1108

**Comment by alena1108** [comment]
@leodotcloud could you look at it?

**Comment by leodotcloud** [comment]
@alena1108 I have a totally different issue, even though I changed the subnet using this `http://<rancher_server_ip>:8080/v1/settings/docker.network.subnet.cidr` be it cattle/k8s the containers are still using 10.42.0.0/16 subnet.

**Comment by alena1108** [comment]
@MattMencel @leodotcloud there are 2 ip address spaces that are managed separately:

1) POD cidr (10.42.0.0/16 by default), managed on Rancher side,can be changed using docker.network.subnet.cidr)
2) K8s service cluster ip cidr, (10.43.0.0/16 by default), managed on Kubernetes side

>though a different subnet was configured in docker.network.subnet.cidr, the k8s environment brings services up in 10.43.0.0/16.

changing pod subnet in Rancher, is not going affect Service cluster ip subnet of k8s.

Currently cluster ip range for k8s is hardcoded in the template, but it is possible to make it configurable in the future:

https://github.com/rancher/infra-catalog/blob/master/infra-templates/k8s/11/docker-compose.yml#L81

@leodotcloud docker.network.subnet.cidr  change not taking affect is a separate issue. I don't think you can change it on the fly, after 10.42.x.x is already configured, and there are containers using this CIDR. Once first network/vnet/subnet is created, I believe you can't change it and it has to be preconfigured on Rancher first launch. 

@ibuildthecloud would network refactoring allow to reconfigure subnet cidr for managed network?

**Comment by alena1108** [comment]
@leodotcloud we should debug this error:

> Docker server logs show errors like below over and over. The service deployed from the catalog never starts
> Could not determine network mode for container [externalId: 05f38d3f25c1e239a3a0b3dec4f71252404e0b81f78bda13e33e2c26d3bc8d31]. Using none networking.

can you check if CNI plugin relies on 10.42.x.x address format? The container deployment shouldn't fail. It should start with the address of 10.42.x.x space, or whatever address configured on the subnet.

**Comment by leodotcloud** [comment]
So the step that I missed earlier was to create a new environment to be able to use the new cidr. This time things worked as expected.

Here is the screenshot with the new cidr range(`10.99.0.0/16`)
![screen shot 2016-10-19 at 4 02 19 pm]
(https://cloud.githubusercontent.com/assets/19392926/19540622/96611aa0-9615-11e6-8c0e-4300fd0f5e32.png)

Created a new environment, launched the wordpress app from the catalog and it deploys fine. You can see the container IPs from the new `10.99.0.0/16` subnet.

![screen shot 2016-10-19 at 4 01 45 pm](https://cloud.githubusercontent.com/assets/19392926/19540627/9d8a4360-9615-11e6-8f1c-e0c3e782cd78.png)
![screen shot 2016-10-19 at 4 01 55 pm](https://cloud.githubusercontent.com/assets/19392926/19540626/9d8a5e54-9615-11e6-8f1e-9c2113a6018e.png)

@alena1108 We don't have any hard coded assumptions in the CNI plugin regarding the format of the IP address. We fetch the IP address from the metadata and use it.

@MattMencel So how do I reproduce the issue?

**Comment by leodotcloud** [comment]
ping @MattMencel

**Comment by leodotcloud** [comment]
ping @MattMencel, can you please let me know on how to reproduce this issue?

**Comment by MattMencel** [comment]
Sorry for the delay getting back to you on this.  I've changed the way I am deploying nodes, using CoreOS instead of CentOS Atomic, and I'm using the default networks.  I don't know that I can reproduce the issue at the moment so I'm going to close this issue for now.  If I run into it again in the future I will try to get some better debugging.
