### ISSUE TITLE
Swarm-kit container stuck in initializing state after adding a new custom host 

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#6114]
**Rancher Version:**Master

**Docker Version:**1.12.1

**OS and where are the hosts located? (cloud, bare metal, etc):**Ubuntu 16.0.4, Cloud

**Steps to Reproduce:**
1. Create a 3 host swarm cluster by using the catalog https://github.com/LLParse/swarmkit-catalog
While launching the catalog specify the interface name "Ex: ens4/eth0". Once the catalog is launched, ensure the swarm cluster comes up correctly.
2. Delete one of the hosts and ensure cluster is functional
3. Add a custom host. 
4. Once the custom host is added, the swarm-kit_mon container is stuck in initializing state.
After around 3 minutes the host changed from active to "Reconnecting" state and then to "Disconnected" state.

Logs attached:

[host1_failing_networkagent.txt](https://github.com/rancher/rancher/files/507386/host1_failing_networkagent.txt)
[host2_networkagent.txt](https://github.com/rancher/rancher/files/507388/host2_networkagent.txt)
[host3_networkagent.txt](https://github.com/rancher/rancher/files/507387/host3_networkagent.txt)

**Comment by LLParse** [comment]
Did not reproduce for me:
1. Added 3 GCE hosts with Docker 1.12.1 and created swarm using latest swarmkit template
2. Launched a service with scale=5
3. Terminated a host and observed service reconciliation
4. Added a new host, observed it join the swarm
5. Terminated another host, observed service reconciliation
6. Added another host, observed it join the swarm

Attached logs do not indicate any errors. Can you please retest with the latest template?

**Comment by soumyalj** [comment]
Tested with v1.2.0-pre4-rc5 using the catalog https://git.rancher.io/infra-catalog.git in qa branch (version v1.12-rancher0). Followed the steps mentioned above and  did not see the issue. Swarm was functional.
