### ISSUE TITLE
Joining external machine with no docker to Rancher managed network

### ISSUE THREAD

**Issue by gerich-home** [rancher/rancher#6115]
**Rancher Version:** v1.2.0-pre3

**Docker Version:** 1.12.1

**OS and where are the hosts located? (cloud, bare metal, etc):** Ubuntu 16.04.1 LTS (with KVM) 

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single node rancher, internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

Hi,

I have Rancher deployed on one of my servers and it manages a set of 4 rancher hosts.

There is also a selenium grid instance (hub + 4 chrome + 4 firefox nodes) deployed to rancher + many temporary short-living instances of my web application (deployed on each commit for this test run only) that are getting tested with this grid. There can be multiple instances of my application deployed that are tested at the same time (when developers do frequent commits).

Hub node is exposed to the public world via port 4444, so I use the url to http://myhost.internal.corp:4444/grid/console to access it and view the list of browsers connected to it.

All selenium nodes, hub node and applications are deployed to the same rancher environment, so they share the same Rancher's managed network and can ping each other.

Thus I do not expose any ports of my web application on the running host, but I use internal rancher's DNS to point selenium nodes to the currently tested web site. So in fact each node opens a browser and types into the url something like that: http://web.test-run-34.rancher.internal/ where 34 is the number of the build (read: commit)

I want to enable testing of my application with Internet Explorer (or any other non-linux/non-rancher compatible environment, android for example).

As I have grid exposed at http://myhost.internal.corp:4444/grid/console I see the possibility to connect additional selenium nodes that run on external hosts (that are not managed via Rancher) to it.
But those nodes will not have access to internal web application instances via the url http://web.test-run-34.rancher.internal/ as they are not joined to the Rancher's internal overlay network.

I see 2 solutions for it:
1. Adjust the testing procedure to expose web application to the public world and let Rancher choose the port and host for my web application.
It means that instead of using http://web.test-run-34.rancher.internal/ I should wait Rancher to deploy the application for me and query it for the name of the host and the port that it assigns to my application. Then I should use the url of the form: http://some-of-rancher-hosts.internal.corp:54623/
2. Join external machine (possibly running Windows) to Rancher's internal network for that environment so that it could ping any instance of application using url http://web.test-run-34.rancher.internal/

Before taking the 1st path I want to know if it is possible to follow the 2nd path

**Comment by aemneina** [comment]
solution 1 sounds like the best bet. I'll close this issue out, feel free to reopen if you have further questions.

**Comment by gerich-home** [comment]
Yes, I took the 1st solution already, but anyway is the 2nd solution possible in Rancher?

**Comment by aemneina** [comment]
2 sounds slightly difficult to do, and could possibly cause ip address conflicts. I wouldn't recommend that.
