### ISSUE TITLE
Duplicated hosts after reboot

### ISSUE THREAD

**Issue by boskiv** [rancher/rancher#6117]
**Rancher Version:**
1.1.4
**Docker Version:**
1.12
**OS and where are the hosts located? (cloud, bare metal, etc):**
VSphere
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single rancher external db (maria galera)
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
reboot hosts with agents installed
**Results:** 
![2016-10-04 12 36 35](https://cloud.githubusercontent.com/assets/1939783/19069378/5ddd3638-8a2f-11e6-8a5b-ff13e94fdbd7.png)

**Expected:**

**Comment by cjellick** [comment]
Boot2Docker's disk outside of /var/lib/docker is an in-memory ramdisk. As such, Rancher's persisted state that allows a host to be identified upon reboot gets wiped out.

@vincent99 added a workaround for this, but maybe it is not in the 1.1.X branch. @vincent99?

**Comment by jclark360** [comment]
I get the same thing where hosts are duplicated and rancher appears to be trying to reconnect them, even though the same host/ip is up?

![image](https://cloud.githubusercontent.com/assets/6331228/19123706/af0fbdb8-8afd-11e6-8a7a-b4d361c7b68d.png)

**Comment by vincent99** [comment]
The agent change for boot2docker is only in 1.2
