### ISSUE TITLE
No graphs in Service

### ISSUE THREAD

**Issue by boskiv** [rancher/rancher#6118]
**Rancher Version:**
1.2.0-pre3
**Docker Version:**
1.12.1
**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
Create consul from catalog
**Results:** 
![2016-10-04 18 00 15](https://cloud.githubusercontent.com/assets/1939783/19079480/6cdfa706-8a5c-11e6-8ef7-77a9151a75f8.png)
![2016-10-04 18 00 08](https://cloud.githubusercontent.com/assets/1939783/19079483/710f5506-8a5c-11e6-9674-a7187b512585.png)

```
VM825:35 WebSocket connection to 'ws://rancher.dev.exness.local/v1/containerstats/9bf612f6911e9f69dbcec6e6823952254f34853d7dfc863e011970840e974131?token=eyJhbGciOiJSUzI1NiJ9.eyJleHAiOjE0NzU1OTMzMjMsInN1YiI6ImNhdHRsZSIsImlzcyI6Imh0dHA6XC9cL2NhdHRsZS5pbyIsImhvc3RVdWlkIjoiZjVmYmZkMDItNDQxMi00ZDhhLWJhNTktNmZhZDIxMTdkMTBhIiwiY29udGFpbmVySWRzIjp7IjliZjYxMmY2OTExZTlmNjlkYmNlYzZlNjgyMzk1MjI1NGYzNDg1M2Q3ZGZjODYzZTAxMTk3MDg0MGU5NzQxMzEiOiIxaTEyIn0sImlhdCI6MTQ3NTU5MzAyMywia2lkIjoiZGVmYXVsdCJ9.GcDOzHWgdE10wVcQc0olZYTVZKmelYBtLbXfXx-6x7vFktbTKpugKnPAycgWfozBN1Ww0947j0Y9_DCf2PEB35F3Y6JMiU3RTXLSFu2sO9W5uMPsjEh8nGmlzzB4xwMwVj3UscusknozRhVHgwIzd8K3VYbaNjDSeAJABE1zdC_7Qa6KKGSjg_w5Sx9UqHqsnOn6oIanA5282hk83z2GQE0qTQG-oRDDyROZfj0JblXUvabVd4WddYV2HIHuSa1aezdgq_OfnSejeFGyf4s_V_vWymgEUjRKgxF56u-3R7TKl4icldPjG8DiilJibxY4O8NDIAwUQ0hC75A5cU_fWQ&sockId=62' failed: HTTP Authentication failed; no valid credentials availableWrappedWebSocket @ VM825:35connect @ socket.js:50e @ ember.prod.js:497invoke @ ember.prod.js:991flush @ ember.prod.js:1055flush @ ember.prod.js:863end @ ember.prod.js:177run @ ember.prod.js:299_runExpiredTimers @ ember.prod.js:686_boundRunExpiredTimers @ ember.prod.js:146
socket.js:217 Socket error (state=connecting, id=62)
socket.js:169 Socket 62 closed
subscribe.js:131 Subscribe ping (projectId=1a7, sockId=54)
```

I have tried to logout/login but no success

**Expected:**

**Comment by StrongMonkey** [comment]
@cjellick  what might cause it failed to connect to the websocket in this case?

**Comment by aemneina** [comment]
Typically firewalls or loadbalancers in front of rancher prevent websocket connections. @boskiv were you able to get this working?

**Comment by aemneina** [comment]
@boskiv were you able to resolve this? If you could check this with the latest -pre release, avoiding an -rc candidate, feel free to reopen.
