### ISSUE TITLE
Adding Audit logs in kubernetes 1.4

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#6119]
**Rancher Version:**
rancher/server:master
**Docker Version:**
1.11.2
**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes 1.4

Audit logs can be enabled in Kubernetes 1.4 by adding the following option to the kube-api server:

`audit-log-path`

**Comment by hiscal2015** [comment]
@wlan0 @alena1108 @galal-hussein Is this feature in progress?

**Comment by hiscal2015** [comment]
@wlan0 Is it possible to prioritize this feature? I think it is not difficult but very important for Enterprise use. Thanks.

**Comment by Joeskyyy** [comment]
+1 Just curious on the status of this.

For what it's worth, you can run an update to the kube-api container to include this in its runtime options, but it'd be much better to be able to define this in the kubernetes service definition.

**Comment by galal-hussein** [comment]
@deniseschannon We are currently support adding flags to kubelet not the kubernetes api service, this will require catalog changes to add the following option:
```
--audit-log-path string                                   If set, all requests coming to the apiserver will be logged to this file.  '-' means standard out.
```
Its also something that not necessarily needed by all users so we will need to add another variable to enable/disable this feature.

**Comment by galal-hussein** [comment]
@moelsayed can be tested with kubernetes in v1.6.8-rc5

**Comment by moelsayed** [comment]
Tested using v1.6.8-rc5:
* deploy rancher server
* create a new environment template based on k8s.
* enable audit logging
* create new k8s environment based on the new template

Results:
* k8s api container command has `--audit-log-path=-` option added.
* k8s api container logs show audit logs.
