### ISSUE TITLE
When I select project from drop-down, it always takes me back to Hosts page

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#612]
v0.17.1
Steps:
1.  create a project
2.  Go to any page but the Host page'
3.  Use the drop-down to switch projects

Results:
Changes projects and moves you back to Hosts page

Expected:
Should stay on the same page but just switch projects.

**Comment by vincent99** [comment]
It takes you to the "default page", which is currently hosts.  It can't take you to the same page in a different project in general because if you're looking at anything specific (a container, a host, etc) that resource is no longer accessible as the new project.

**Comment by tfiduccia** [comment]
Takes you back to main Stack page.  Which is what it should do.
