### ISSUE TITLE
Can't use volume dynamic provisioning using Storageclasses in kubernetes 1.4

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#6121]
**Rancher Version:**
rancher/server:master
**Docker Version:**
1.11.2
**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes 1.4
**Steps to Reproduce:**
storageclass.yml

```
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: slow
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  zone: us-central1-f
```

pvc.json

```
{
  "kind": "PersistentVolumeClaim",
  "apiVersion": "v1",
  "metadata": {
    "name": "claim1",
    "annotations": {
        "volume.beta.kubernetes.io/storage-class": "slow"
    }
  },
  "spec": {
    "accessModes": [
      "ReadWriteOnce"
    ],
    "resources": {
      "requests": {
        "storage": "1Gi"
      }
    }
  }
}
```

**Results:** 
Run the previous files using kubectl create:

```
$ kubectl create -f storageclass.yml 
storageclass "slow" created
$ kubectl create -f pvc.json 
persistentvolumeclaim "claim1" created
$ kubectl describe pvc
Name:       claim1
Namespace:  default
Status:     Pending
Volume:     
Labels:     <none>
Capacity:   
Access Modes:   
Events:
  FirstSeen LastSeen    Count   From                SubobjectPath   Type        Reason      Message
  --------- --------    -----   ----                -------------   --------    ------      -------
  30s       9s      3   {persistentvolume-controller }          Warning     ProvisioningFailed  no volume plugin matched
```

**Expected:**

After creating a storage class and a claim including that storage class, we should see a new PV is created and automatically bound to the claim requesting storage.

**Comment by jimengliu** [comment]
The cloud provider needs to be aws, in order for k8s storage-class feature to work.

**Comment by alena1108** [comment]
We are tracking picking up cloud provider in a separate bug (assigned to Sid), so removing Sid as an assignee from this one

https://github.com/rancher/rancher/issues/6172

**Comment by Dmitry1987** [comment]
Hello, I had an issue using StorageClass on AWS too, my steps were exact as @galal-hussein did here https://github.com/rancher/rancher/issues/6172  , just with another image. How do I need to modify Rancher setup to make AWS dynamic provisioning work? I'm stuck at "ProvisioningFailed no volume plugin matched" error, can't figure out how to allow k8s to provision AWS volumes :( .
Thanks in advance!

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
