### ISSUE TITLE
Infrastructure Catalog should be enabled by default

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#6124]
**Rancher Version:** master 10/4

**Steps to Reproduce:**
1.  Setup a brand new Rancher 
2.  Click on Configure for kubernetes

**Results:** Get an error cause Infrastructure catalog is off by default

**Expected:**  Should be on

**Comment by vincent99** [comment]
Backend, part of https://github.com/rancher/rancher/issues/6157
