### ISSUE TITLE
If infrastructure catalog is off in setting, get a 404 error when selecting orchestration engine

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#6125]
**Rancher Version:** master 10/4

**Steps to Reproduce:**
1.  Create a new environment
2.  Make sure infrastructure catalog is disabled
3.  Go to Stack's page
4.  Click on Configure for any orchestration

**Results:** 404 error
![image](https://cloud.githubusercontent.com/assets/11514927/19085826/a500d88a-8a20-11e6-876b-6382959184b4.png)

**Expected:**  Do not show Infrastructure catalog items if it is disabled.

**Comment by vincent99** [comment]
Buttons shouldn't show up if infra is off now.

**Comment by tfiduccia** [comment]
Version - master 10/10
Buttons not showing if catalog is off.
Verified fixed
