### ISSUE TITLE
Long name for stacks, hosts, catalog templates, container is causing drop-down to change height

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#6127]
**Rancher Version:** master 10/4

**Steps to Reproduce:**
1.  Go to Catalog page
2.  Click on a template
3.  Go to host and click on a container with a long name

**Results:** Notice the drop-down to change templates is huge
![image](https://cloud.githubusercontent.com/assets/11514927/19087056/8486f09e-8a25-11e6-8da9-550ca53416ca.png)
![image](https://cloud.githubusercontent.com/assets/11514927/19175370/bfcdfe6a-8bea-11e6-9fa2-dee75a2d3431.png)

**Expected:**  Should be regular size

**Comment by tfiduccia** [comment]
Version - master 10/10
Verified fixed

**Comment by tfiduccia** [comment]
Ok, I lied, this is not fixed.
![image](https://cloud.githubusercontent.com/assets/11514927/19579257/7cac3026-96d4-11e6-8dbf-86fba25490c4.png)

**Comment by westlywright** [comment]
@tfiduccia can you test this again? I merged master this morning as was not able to duplicate very long names?

**Comment by tfiduccia** [comment]
Version - v1.2.0-pre4-rc9
Verified fixed
