### ISSUE TITLE
Project orchestration is sometimes null

### ISSUE THREAD

**Issue by vincent99** [rancher/rancher#6128]
The orchestration field of a project is null for the default `1a5` project and possibly others.

**Comment by ibuildthecloud** [comment]
@vincent99 This should be fixed.  I addressed the cases I knew of but not 100% confident it addressed everything.

**Comment by sangeethah** [comment]
@ibuildthecloud , Could you provide some information on what scenarios we were seeing project orchestration field to be null before this fix , so I can validate these workflows in particular ?

**Comment by vincent99** [comment]
A new environment just always started out with `orchestration: null`.. but this is changing again today so don't test it for now.

**Comment by deniseschannon** [comment]
Will reopen if this is seen again, but has been fixed.
