### ISSUE TITLE
Hosts are not listed in storage driver view.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6133]
Rancher Version: Build from master- oct 4

Steps to reproduce the problem:
Create a stack from convoy-nfs catalog entry.

Once the  convoy-nfs stack is deployed successfully , I see "convoy-nfs" being listed in storage drivers 
list view. But there are no hosts that are associated with this storage driver.

<img width="1397" alt="screen shot 2016-10-04 at 12 23 11 pm" src="https://cloud.githubusercontent.com/assets/4266958/19089014/67d77b46-8a2d-11e6-8a51-8029737b34b0.png">

Note - I am able to create services which uses convoy-nfs as volume drivers successfully.

**Comment by vincent99** [comment]
https://github.com/rancher/rancher/issues/6097
