### ISSUE TITLE
[rancher-dns] PowerDNS 4.0 uses different API path

### ISSUE THREAD

**Issue by praseodym** [rancher/rancher#6136]
[PowerDNS 4.0 changed the API path](https://doc.powerdns.com/md/authoritative/upgrading/) to `/api/v1` instead of `/`. Rancher external-dns is not updated for this and will try to make requests to `/servers/localhost/zones/xyz` instead of `/api/v1/servers/localhost/zones/xyz`. This breaks the external DNS integration.

**Comment by janeczku** [comment]
@praseodym The upstream library used by the PowerDNS provider (https://github.com/jgreat/powerdns) doesn't support the 4.0 API yet.
Pinging @jgreat to see if he is going to implement this.

**Comment by jgreat** [comment]
I will take a look. If there is an easy way to detect version and the calls to PowerDNS haven't changed too much I will try and get an update soon. I would also gladly accept a PR if someone can get to it sooner.

In the mean time PowerDNS 3.x does work really well. I have had zero issues with it.  In our set up we us Microsoft DNS and I delegate the Rancher External DNS Subdomain to a PowerDNS server that only runs that subdomain.    

I have a 3.4.8 image published here with instructions and Rancher Catalog example in the README: 
https://hub.docker.com/r/jgreat/powerdns/

**Comment by janeczku** [comment]
Thanks @jgreat

**Comment by Toonix** [comment]
@jgreat 
Your old PowerDNS 3.4.8 isn't running anymore with Rancher 1.2.0 and latest network-services. When you try to start the container he can't connect to the database.

**Comment by janeczku** [comment]
@Toonix Thanks for bringing this up. Could you share the error line from the log?

**Comment by jgreat** [comment]
Well that stinks. We will be building out a test Rancher 1.2 instance sometime in the next couple weeks to work out our migration plan. If someone else doesn't get to it first, I'll post a new and improved catalog entry for powerdns.

As a side note, I'm pretty disappointed with lack of backwards compatibility in Rancher 1.2  We're looking at a complete rebuild and migration cause we can't afford that much downtime across our 30+ environments and we can't do all of our production environments at the same time :frowning_face: That said a rebuild and migration is annoying, but not that painful for us since the majority of it is templated and automated.

**Comment by Toonix** [comment]
Is still still the right path to go? I will try powerdns with rfc2136.

Jason Greathouse <notifications@github.com> schrieb am Mo., 5. Dez. 2016,
17:30:

**Comment by jgreat** [comment]
If we can simplify and maybe deprecate the powerdns web api provider, it won't hurt my feelings.  I'm actually moving away from it.

I've modified a version of the rfc2136 provider and removed the auth bits so we can put entries directly into a zone hosted on our Active Directory DNS (have to allow "insecure updates" and zone transfers). I'd love to write a provider to do it securely, but there doesn't seem to be a go dns lib that supports Krb5/GSS-TSIG (thanks MS).

**Comment by Toonix** [comment]
Well I found my solutions. I now use dnsupdate-rfc2136 with PowerDNS4. 

beside some error with AXFR evelope error: dns no SOA it works well now...I bet as soon i fixed the soa records it should be quite and working.

**Comment by dmportella** [comment]
I am updating jgreat code now

**Comment by dmportella** [comment]
I have pushed the change awaiting to be accepted.... you could if you guys want change to use mine fork while it is not accepted.

**Comment by Toonix** [comment]
I have problem with DNS Update (RFC2136) though I try if it is fixed now...but looks like it isn't or?

**Comment by dmportella** [comment]
done a new provider for powerdns4 left the the existing powerdns provider (version 3) unchanged. so now it supports both versions
