### ISSUE TITLE
Should be able to create volumes when used with create option.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6138]
Rancher server - Latest build from master
rancher-compose version v0.11.0-rc1

Steps to reproduce the problem:
Have convoy-nfs volume driver set up for the environment.

Use the following yml with create command , followed by up command to create the service with volumes in nfs store:

```
version: 'v2'
services:
  nginx:
    image: nginx
    volumes:
    - foo:/tmp

volumes:
  foo:
    driver: nfs
    external: false
```

```
Sangeethas-MacBook-Pro:rancher-compose-v0.11.0-rc1 sangeethahariharan1$ ./rancher-compose -p new1 -f test-stack.yml create
INFO[0000] [0/1] [nginx2]: Creating                     
INFO[0000] Creating service nginx2                      
INFO[0001] [0/1] [nginx2]: Created                      
INFO[0001] [0/1] [nginx2]: Creating                     
INFO[0001] [0/1] [nginx2]: Created                      
Sangeethas-MacBook-Pro:rancher-compose-v0.11.0-rc1 sangeethahariharan1$ ./rancher-compose -p new1 -f test-stack.yml up
INFO[0000] [0/1] [nginx2]: Creating                     
INFO[0000] [0/1] [nginx2]: Created                      
FATA[0000] Volume "foo" needs to be recreated - driver has changed 
```

This should result in volume -new1_foo being created and service having this volume mounted at /tmp.

**Comment by joshwget** [comment]
Fixed by a recent libcompose bump (https://github.com/docker/libcompose/pull/392).

**Comment by sangeethah** [comment]
Tested with rancher-compose version v0.12.3. Able to create new volumes when using up comamnd.

./rancher-compose -p new1 -f test.yml up
INFO[0000] Creating stack new1                          
INFO[0000] Creating volume template foo                 
INFO[0000] [0/1] [nginx]: Creating                      
INFO[0001] Creating service nginx                       
INFO[0001] [0/1] [nginx]: Created                       
INFO[0001] Existing volume template found for foo       
INFO[0001] [0/1] [nginx]: Starting                      
INFO[0019] [1/1] [nginx]: Started                       
^C

**Comment by fredleger** [comment]
Seems that this is still the case at least on macos X (rancher-compose 1.12.5) and rancher version 1.6.5

```
rancher-compose -p supervision up
INFO[0005] Existing volume template found for icinga2_var
INFO[0005] Existing volume template found for icinga2_conf_classicui
INFO[0005] Existing volume template found for icinga2_firstboot
INFO[0006] Existing volume template found for icinga2_conf
INFO[0006] Existing volume template found for icinga2_confweb
FATA[0006] Volume "icinga2_confweb" needs to be recreated - driver has changed
```

**Comment by bizmate** [comment]
Are rancher cli and rancher-compose different?

```
rancher up --stack App-Elk --upgrade --force-upgrade -c -d --prune
INFO[0000] Existing volume template found for app-elk-data 
FATA[0000] Volume "app-elk-data" needs to be recreated - driver has changed 
```
