### ISSUE TITLE
Configuring out of resources handling in Kubernetes

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#6142]
**Rancher Version:**
rancher/server:master
**Docker Version:**
1.11.2
**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

Kubernetes should have eviction policy by configuring kubelet to preserve node stability when available compute resources are low, kubelet should be configured by soft and hard eviction thresholds, for more information see http://kubernetes.io/docs/admin/out-of-resource/

**Comment by vincentchen** [comment]
I am searching the feature,too. When this will be supported?

**Comment by rldourado** [comment]
+1

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
