### ISSUE TITLE
Kubernetes: Non resolvable DNS when the pods are set to hostNetwork=true

### ISSUE THREAD

**Issue by andylmtang** [rancher/rancher#6147]
**Rancher Version:**
Ranch Server 1.1.4

**Docker Version:**
Docker 1.12.1

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04.1 LTS in DigitalOcean

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node Rancher w external DB.

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes. 1.2.4-rancher10. Three Nodes

**Steps to Reproduce:**
I have been trying to get Prometheus Monitoring to work in my Env. Most services can communicate with each other correctly. The only exception is ranch-eye. Ranch-eye, under the default configuration from the Prometheus catalog, would return 505 when I try to hit the service port at http://ranch-eye:9104/metrics

In order to get it to work I have to change the image to infinityworks/ranch-eye:03 (the same image been used for Prometheus Cattle Catalog) and set hostNetwork to true (According to Prometheus Cattle Catalog ranch-eye should be running with -network=host). Once I do that then ranch-eye can return metrics correctly

But if I do that, then it seems that kubernetes/rancher no longer creates the correct dns entry for http://ranch-eye. I verify this by docker exec into the prometheus container and do a nslookup on ranch-eye, which it cannot resolve. Note that the dns is resolvable when i have hostNetwork=false, but then ranch-eye doesn't return any metrics.

**Results:** 
/prometheus # nslookup ranch-eye
Server:    (null)
Address 1: ::1 localhost
Address 2: 127.0.0.1 localhost

nslookup: can't resolve 'ranch-eye': Name does not resolve

**Expected:**
nslookup ranch-eye is resolvable and point to the correct cluster IP address.

**Comment by will-chan** [comment]
@wlan0 can you look into this?

**Comment by alena1108** [comment]
@andylmtang there is no support for dns for host level containers yet, they are discussing it right now:

https://github.com/kubernetes/kubernetes/issues/17406

Keeping this bug open for the next Rancher release.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
