### ISSUE TITLE
Production deployment is practically dead. Tried everything, can't resolve, rancher keeps on failing

### ISSUE THREAD

**Issue by virtuman** [rancher/rancher#6148]
Production deployment is practically dead. Tried everything, can't resolve, rancher keeps on failing and not able to schedule anything new. DNS cannot be resolved from inside rancher server container and after adding it manually it only renders some of the rancher functions to open, but nothing works.

I tried to restart the rancher server node and it didn't want to start rancher up, numerious restarts eventually started up the server container but it feels very risky to continue to run on rancher and not knowing what the problem is for over a week now. 

Wondering if there's any quick fix or some direction that anyone could suggest to investigate this further, otherwise the entire production deployment is hanging by the thread and possibly won't recover.

**Rancher Version:**
rancher/server:v1.2.0-pre3

**Docker Version:**
Server Version: 1.12.1

**OS and where are the hosts located? (cloud, bare metal, etc):**
3 x Dedicated bare metal servers
PRETTY_NAME="Ubuntu 16.04.1 LTS"

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
single network interfaces on all 3 servers
external mysql DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
on rancher server 1.1.3 everything was working correctly, but after the upgrade to 1.2.0-pre3 DNS stopped working.
Tried to downgrade back to 1.1.3 - DNS didn't begin to work
Erased rancher server docker container completely (mysql is running as external service) - re-created container, still no DNS.
Tried to upgrade from 1.1.3 to 1.1.4 still no DNS
Upgraded and re-created containers for latest 1.2.0-pre3 - still no DNS
Not able to get DNS in rancher server container to work

I am not sure at this point, but while troubleshooting docker swarm services, I may have changed some of these properties from 0 to 1, but i can't imagine that it's affecting internal DNS resolution?

```
net.bridge.bridge-nf-call-arptables = 1
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
```

**Results:** 
Since DB and LDAP services run as external services - rancher server is unable to connect to the MYSQL DB servers, and unable to connecto LDAP server.

When I modify /etc/resolv.conf inside the rancher server container to add `nameserver 8.8.8.8` - I'm able to get to the login page, and if i sign in - it takes about 2-10 minutes to actually get into the rancher UI, but if I click anywhere in the UI - it just hangs, and eventually shows that session timed out and throws me back to login page.

**Expected:**
expected for things to continue to play well with DNS resolution after the upgrade, or at least some info on possible reasons why it could stop working

**Comment by vincent99** [comment]
Need much more specific information.. 
  - What does "DNS doesn't work" mean?
    - You say inside rancher server container but service discovery names (`service.stack.rancher.internal`) are not supposed to be resolvable inside the server container, it's not part of any particular environment.
    - And the server container should not be pointed at the network agent/internal DNS in the first place (169.254.169.250).
  - Or is it resolving public DNS entries (e.g. google.com)?
  - Does it not return at all?  Return SERVFAIL?  Return ISP DNS hijacking pages?
  - What are the host (/etc/resolv.conf) and Docker configured to use?

See also what I said in https://github.com/rancher/rancher/issues/5916#issuecomment-251576733 .  You should not have multiple agents.

**Comment by virtuman** [comment]
I should have been a lot more specific:

**DNS doesn't work**
means that it can't resolve any public DNS at all, ie it will just hang forever:
```
root@de ~ # docker exec -it 
![screen shot 2016-10-05 at 4 18 39 pm](https://cloud.githubusercontent.com/assets/1087996/19135161/8573c2fa-8b17-11e6-8e2b-0562a8085bf4.png)
system_rancher_1 ping google.com
ping: unknown host google.com
```

and as described in the original ticket - we use external LDAP server and MYSQL services, hence the DNS for these services cannot be resolved and rancher is just idling when I try to login. In case cases, when I open rancher UI - and on the login page it will say that LDAP server is not reachable. 

And if I add `nameserver 8.8.8.8` - domains become resolvable (at least that's what I can tell from docker exec'ing into the container) and on the login the error message disappears, it will actually take my username and password, and if i wait long enough (over 2 minutes) it used to be able to display my stacks; oftentimes, javascript debugger would popup asking if I want to continue to wait or stop execution (in any browser: google chrome, safari, firefox) but clicking anywhere after the Stacks page is open will start the request and will never open any of the pages. Since the time of my original ticket - I am no longer able to login and access rancher UI interface at all.
![Uploading Screen Shot 2016-10-05 at 4.18.39 PM.png…]()

It never happened before, but since the DNS issue came to life - javascript takes up all 100% of the client machine that i use for connecting to the rancher UI.

As far as being able to ping a stack by name - i never had to do that before so I dont' remember all stacknames that we have and since I can't login to rancher UI I cant' try pinging any of the stacksby name ie. `service.stack.rancher.internal` ... i tried a few names, the way I think the stacks are called, and wasn't able to get any of them resolved, so I'm not sure if I didn't get the names right, or if it's actually not resolving.

**Comment by virtuman** [comment]
Another interesting fact:
I just now was able to login and browse a few pages in the UI - tried to enable High Availability to quickly add a few more hosts to the environment, and as soon as I clicked on Activate - rancher switched to new environment and things started to work absolutely normal, within this New Environment. As soon as I switched back to my real environment in rancher UI - web UI froze up again and doesn't want to work.

Tried all the same steps with removing and re-creating containers, made sure to 
`docker update --restart=no rancher-agent`
tried to `service ufw restart` and all the other things and still to no avail :(

**Comment by aemneina** [comment]
have you restarted docker after doing the firewall restart? That should reinstate some firewall rules relating to docker.

**Comment by virtuman** [comment]
Yes restarted then in various order along with restarting the host system and the entire process multiple times in all different orders

**Comment by aemneina** [comment]
@virtuman did the services restore, or are you still facing issues?

**Comment by aemneina** [comment]
@virtuman let us know if you sorted this out, feel free to reopen if issues still persist.
