### ISSUE TITLE
DnsSearch path is broken with wildcard domains

### ISSUE THREAD

**Issue by ajacques** [rancher/rancher#6149]
I have a domain name `example.com` that has a wildcard record such that `*anything*.example.com` returns an A/AAAA record `1.2.3.4`. (i.e. I have a record defined `*.example.com IN A 198.x.y.z`.)

I have a Rancher configured with 2 unique hosts on that domain name: (`host1.example.com` and `host2.example.com`.)

I have a Rancher stack using the Managed network adapter:

```
redis:
  image: redis:3.0.7-alpine
Example:
  tty: true
  image: ubuntu:latest
  links:
  - redis:redis
  stdin_open: true
```

From inside the Example container I install ping and attempt to resolve the redis container (as I assume this works):

```
root@d182d02f4716:/# cat /etc/resolv.conf
search example.com test.rancher.internal agent.test.rancher.internal rancher.internal
nameserver 169.254.169.250
root@d182d02f4716:/# ping redis
PING host1.example.com (198.x.y.z [external_ip]) 56(84) bytes of data.
64 bytes from host1.example.com (198.x.y.z [external_ip]): icmp_seq=1 ttl=64 time=0.1
52 ms
```

The DNS server (Note: that Rancher is functioning as my DNS server) is returning the external public IP for the Docker's host server (198.x.y.z) instead of the expected internal Rancher network IP (a 10.x.y.z). This means that all of the containers attempt to connect to the wrong IP address.

I believe this is because the search domain order attempts to resolve `redis.example.com` instead of `redis.test.rancher.internal` causing it to find the wrong DNS server. Is my understanding correct? I feel like this is a bug.

docker inspect of Example container:

```
"Dns": [
  "169.254.169.250"
],
"DnsOptions": null,
"DnsSearch": [
   "example.com",
   "test.rancher.internal",
   "agent.test.rancher.internal",
   "rancher.internal"
],
"ExtraHosts": null,
```
## Docker Daemon: `v1.12.1`

| Useful | Info |
| :-- | :-- |
| Versions | Rancher `v1.1.4` Cattle: `v0.165.8.4` UI: `v1.1.14` |
| Access | `github` `admin` |
| Orchestration | `Cattle` |
| Route | `service.containers` |

**Comment by vincent99** [comment]
Your search path is first because you (or your network) have explicitly configured the hosts to have that.  It is much safer to assume that unqualified names work the same as they do on the ready if your network than to allow one user to potentially accidentally overwrite a name other containers use.

Obviously this doesn't mix well with a wildcard entry, but it is not currently configurable, other than not providing that search domain.

**Comment by ajacques** [comment]
The search path is just using the default search path provisioned by Rancher and I didn't explicitly configure the search path in the Rancher UI (Note no custom search path defined in the docker-compose.yml file). 

Where is it pulling the `example.com` search path from if not from the Rancher service configuration?

**Comment by vincent99** [comment]
resolv.conf on the host

**Comment by zambon** [comment]
> It is much safer to assume that unqualified names work the same as they do on the rest of your network than to allow one user to potentially accidentally overwrite a name other containers use.

@vincent99 Could you elaborate on that? I'm by no means a networking expert, but I'm not sure I agree with that.

**Comment by vincent99** [comment]
There is a label to choose whether prefixes are before or after the host search path as of a while ago.
