### ISSUE TITLE
Switch from K8s back to cattle causes rancher ps to dump json

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#6150]
**Rancher Version:**
v1.2.0-pre3
**Docker Version:**
1.12.1
**OS and where are the hosts located? (cloud, bare metal, etc):**
Laptop
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
K8s->Cattle
**Steps to Reproduce:**
Create environment
Deploy K8s
Then change back to cattle

**Results:** 
`rancher ps` gets error that it can't unmarshal string as json.
Observed the k8s ingress controller was left behind.
**Expected:**
`rancher ps` works as planned.

**Comment by deniseschannon** [comment]
Unable to reproduce with v0.3.1 and v1.2.0-pre4-rc11.

Due to the change of environment templates, the only way to change from k8s to cattle is to remove the k8s stack. 

@cloudnautique Please reopen if you see it again.
