### ISSUE TITLE
Traefik catalog entry broken - produces a empty unhealthy stack

### ISSUE THREAD

**Issue by roffe** [rancher/rancher#6151]
**Rancher Version:**
1.1.4

**Docker Version:**
1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
CoreOS v1122.2.0

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA Rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Try to install Traefik through catalogue

**Results:** 
Unhealthy and no containers created in stack

**Expected:**
A simple 1-2-3 install to get admin ui up and running as described in your blog and on Traefik homepage.

![screen shot 2016-10-05 at 10 13 04](https://cloud.githubusercontent.com/assets/5434736/19105856/90aaa77a-8ae4-11e6-9ff9-e30debb870b4.png)
![screen shot 2016-10-05 at 10 13 16](https://cloud.githubusercontent.com/assets/5434736/19105854/90a76a10-8ae4-11e6-83e9-32f7f59b2d2c.png)
![screen shot 2016-10-05 at 10 13 28](https://cloud.githubusercontent.com/assets/5434736/19105855/90a7bdc6-8ae4-11e6-83bf-0e0f70a76201.png)

`{
"id": "1s75",
"type": "service",
"links": {
"self": "…/v1/projects/1a5/services/1s75",
"account": "…/v1/projects/1a5/services/1s75/account",
"consumedbyservices": "…/v1/projects/1a5/services/1s75/consumedbyservices",
"consumedservices": "…/v1/projects/1a5/services/1s75/consumedservices",
"environment": "…/v1/projects/1a5/services/1s75/environment",
"instances": "…/v1/projects/1a5/services/1s75/instances",
"serviceExposeMaps": "…/v1/projects/1a5/services/1s75/serviceexposemaps",
"containerStats": "…/v1/projects/1a5/services/1s75/containerstats",
},
"actions": {
"update": "…/v1/projects/1a5/services/1s75/?action=update",
"restart": "…/v1/projects/1a5/services/1s75/?action=restart",
"remove": "…/v1/projects/1a5/services/1s75/?action=remove",
"setservicelinks": "…/v1/projects/1a5/services/1s75/?action=setservicelinks",
"removeservicelink": "…/v1/projects/1a5/services/1s75/?action=removeservicelink",
"upgrade": "…/v1/projects/1a5/services/1s75/?action=upgrade",
"addservicelink": "…/v1/projects/1a5/services/1s75/?action=addservicelink",
"deactivate": "…/v1/projects/1a5/services/1s75/?action=deactivate",
},
"name": "traefik",
"state": "active",
"accountId": "1a5",
"assignServiceIpAddress": false,
"createIndex": null,
"created": "2016-10-05T08:13:09Z",
"createdTS": 1475655189000,
"currentScale": 0,
"description": null,
"environmentId": "1e33",
"externalId": null,
"fqdn": null,
"healthState": "unhealthy",
"kind": "service",
"launchConfig": {
"environment": {
"CONF_INTERVAL": "60",
"TRAEFIK_HTTPS_ENABLE": "false",
},
"healthCheck": {
"healthyThreshold": 2,
"interval": 5000,
"port": 8000,
"requestLine": "GET /dashboard/# HTTP/1.0",
"responseTimeout": 5000,
"strategy": "recreate",
"unhealthyThreshold": 3,
},
"imageUuid": "docker:rawmind/alpine-traefik:1.0.1-1",
"kind": "container",
"labels": {
"io.rancher.container.hostname_override": "container_name",
"io.rancher.scheduler.affinity:container_label_ne": "io.rancher.stack_service.name=${stack_name}/${service_name}",
"io.rancher.scheduler.affinity:host_label": "traefik_lb=true",
"io.rancher.scheduler.global": "true",
"io.rancher.service.hash": "fff254b0cabd58f265086bb13405d94b51e24d7a",
"io.rancher.sidekicks": "traefik-conf",
},
"logConfig": { },
"networkMode": "managed",
"ports": [ 3 items
"8000:8000/tcp",
"8080:8080/tcp",
"8443:8443/tcp",
],
"privileged": false,
"publishAllPorts": false,
"readOnly": false,
"startOnCreate": true,
"stdinOpen": false,
"tty": true,
"version": "0",
"dataVolumesFromLaunchConfigs": [
"traefik-conf",
],
"vcpu": 1,
},
"metadata": {
"io.rancher.service.hash": "d0f95f9ed80f9cc8fd8c51499b668012233abf57",
"traefik": {
"ssl_crt": "",
"ssl_key": "\n",
},
},
"publicEndpoints": null,
"removed": null,
"retainIp": true,
"scale": 1,
"scalePolicy": null,
"secondaryLaunchConfigs": [
{
"imageUuid": "docker:rawmind/rancher-traefik:0.3.4",
"labels": {
"io.rancher.container.start_once": "true",
"io.rancher.scheduler.affinity:container_label_ne": "io.rancher.stack_service.name=${stack_name}/${service_name}",
"io.rancher.scheduler.affinity:host_label": "traefik_lb=true",
"io.rancher.scheduler.global": "true",
"io.rancher.service.hash": "93e9a4524e7654c6f53d0059dd837328c748fe6d",
},
"logConfig": { },
"name": "traefik-conf",
"networkMode": "none",
"startOnCreate": true,
"tty": true,
"kind": "container",
"privileged": false,
"publishAllPorts": false,
"readOnly": false,
"stdinOpen": false,
"vcpu": 1,
"version": "0",
},
],
"selectorContainer": null,
"selectorLink": null,
"startOnCreate": false,
"transitioning": "no",
"transitioningMessage": null,
"transitioningProgress": null,
"upgrade": null,
"uuid": "68d289fa-1fb7-4b41-98b5-87229cb4170a",
"vip": null,
}`

**Comment by will-chan** [comment]
@galal-hussein can you take a look at this?

**Comment by galal-hussein** [comment]
@roffe There is an already issue opened for this template item, you can follow the progress on it in https://github.com/rancher/community-catalog/issues/240
