### ISSUE TITLE
rancher-agent failed to start after upgraded ubuntu to 16.04.1

### ISSUE THREAD

**Issue by tonythian** [rancher/rancher#6153]
I can't start rancher-agent on my ubuntu VM after it has been upgraded from 15.04 to Ubuntu 16.04.1 LTS (4.2.0-42-generic) this morning.  The docker logs shows the following:

INFO: Running Agent Registration Process, CATTLE_URL=http://office.oncloud.tech:8080/v1
INFO: Checking for Docker version >= 1.6.0
INFO: Found Server version: 1.11.2
INFO: docker version: Client version: 1.6.0
INFO: docker version: Client API version: 1.18
INFO: docker version: Go version (client): go1.4.2
INFO: docker version: Git commit (client): 4749651
INFO: docker version: OS/Arch (client): linux/amd64
INFO: docker version: Server version: 1.11.2
INFO: docker version: Server API version: 1.23
INFO: docker version: Go version (server): go1.6.2
INFO: docker version: Git commit (server): b9f10c9
INFO: docker version: OS/Arch (server): linux/amd64
INFO: docker info: Containers: 28
WARNING: No swap limit support
INFO: docker info: Images: 181
INFO: docker info: Storage Driver: aufs
INFO: docker info: Root Dir: /var/lib/docker/aufs
INFO: docker info: Backing Filesystem: extfs
INFO: docker info: Dirs: 296
INFO: docker info: Dirperm1 Supported: true
INFO: docker info: Execution Driver:
INFO: docker info: Kernel Version: 4.4.0-38-generic
INFO: docker info: Operating System: Ubuntu 16.04.1 LTS
INFO: docker info: CPUs: 4
INFO: docker info: Total Memory: 7.789 GiB
INFO: docker info: Name: ubuntu14
INFO: docker info: ID: X3E5:ELA2:X64X:U3ZK:KP2J:3N4M:PIB6:2LSZ:SJMI:IDEK:NMNM:ELZQ
INFO: docker info: Http Proxy:
INFO: docker info: Https Proxy:
INFO: docker info: No Proxy:
INFO: Attempting to connect to: http://office.oncloud.tech:8080/v1
INFO: http://office.oncloud.tech:8080/v1 is accessible
INFO: Inspecting host capabilities
INFO: Systemd: true
INFO: Boot2Docker: false
INFO: Host writable: true
INFO: Token: xxxxxxxx
INFO: Running registration
INFO: Printing Environment
INFO: ENV: CATTLE_ACCESS_KEY=33BA556040D8432465F5
INFO: ENV: CATTLE_AGENT_IP=192.168.1.165
INFO: ENV: CATTLE_HOME=/var/lib/cattle
INFO: ENV: CATTLE_REGISTRATION_ACCESS_KEY=registrationToken
INFO: ENV: CATTLE_REGISTRATION_SECRET_KEY=xxxxxxx
INFO: ENV: CATTLE_SECRET_KEY=xxxxxxx
INFO: ENV: CATTLE_SYSTEMD=true
INFO: ENV: CATTLE_URL=http://office.oncloud.tech:8080/v1
INFO: ENV: DETECTED_CATTLE_AGENT_IP=192.168.1.1
INFO: ENV: RANCHER_AGENT_IMAGE=rancher/agent:v1.0.2
invalid value "." for flag -v: . is not an absolute path
See 'docker run --help'.

The command to run rancher-agent is as follow:

sudo docker run -d --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.0.2 http://office.oncloud.tech:8080/v1/scripts/09223B875CBF8D1DCA1C:1475658000000:yXnr7r13LWAdu12AYHwRbKaketc

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.2.0-pre3` Cattle: `v0.169.5` UI: `v1.2.11` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`hosts.new.index`|

**Comment by will-chan** [comment]
@StrongMonkey I know we are moving to our new agent so make sure this doesn't break with our new agent.

**Comment by StrongMonkey** [comment]
@tonythian Can you make sure if rancher-agent-state image is running in your host?

**Comment by StrongMonkey** [comment]
@tonythian please make sure to remove rancher/agent and rancher-agent-state. And then do a `rm -f /var/lib/rancher/*` to remove all the state files in the host. Then you will be able to re-register the host.
