### ISSUE TITLE
Rancher HA cluster random errors when using Percona XTRA DB Cluster ( Galera )

### ISSUE THREAD

**Issue by roffe** [rancher/rancher#6154]
**Rancher Version:**
1.1.14
**Docker Version:**
1.10.3
**OS and where are the hosts located? (cloud, bare metal, etc):**
CoreOS V1122.2.0 for docker, Ubuntu 16.04 for DB

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Rancher HA 3 nodes

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Try to setup Rancher using a Percona XtraDB 5.7 cluster, 3 nodes and then use 1 for write / reads to avoid race conditions

**Results:** 
2016-10-05T13:29:08.582278Z 13445 [Note] WSREP: cluster conflict due to certification failure for threads:
2016-10-05T13:29:08.582292Z 13445 [Note] WSREP: Victim thread:
   THD: 13445, mode: local, state: executing, conflict: cert failure, seqno: -1
   SQL: update `process_instance` set `process_instance`.`start_time` = ?, `process_instance`.`end_time` = ?, `process_instance`.`data` = ?, `process_instance`.`priority` = ?, `process_instance`.`process_name` = ?, `process_instance`.`resource_type` = ?, `process_instance`.`resource_id` = ?, `process_instance`.`result` = ?, `process_instance`.`exit_reason` = ?, `process_instance`.`phase` = ?, `process_instance`.`start_process_server_id` = ?, `process_instance`.`running_process_server_id` = ? where `process_instance`.`id` = ?
2016-10-05T13:29:08.586305Z 13445 [Note] WSREP: cluster conflict due to certification failure for threads:
2016-10-05T13:29:08.586442Z 13445 [Note] WSREP: Victim thread:
   THD: 13445, mode: local, state: executing, conflict: cert failure, seqno: -1
   SQL: update `process_instance` set `process_instance`.`start_time` = ?, `process_instance`.`end_time` = ?, `process_instance`.`data` = ?, `process_instance`.`priority` = ?, `process_instance`.`process_name` = ?, `process_instance`.`resource_type` = ?, `process_instance`.`resource_id` = ?, `process_instance`.`result` = ?, `process_instance`.`exit_reason` = ?, `process_instance`.`phase` = ?, `process_instance`.`start_process_server_id` = ?, `process_instance`.`running_process_server_id` = ? where `process_instance`.`id` = ?
2016-10-05T13:29:08.586655Z 13411 [Note] WSREP: cluster conflict due to certification failure for threads:
2016-10-05T13:29:08.586682Z 13411 [Note] WSREP: Victim thread:
   THD: 13411, mode: local, state: executing, conflict: cert failure, seqno: -1
   SQL: update `process_instance` set `process_instance`.`start_time` = ?, `process_instance`.`end_time` = ?, `process_instance`.`data` = ?, `process_instance`.`priority` = ?, `process_instance`.`process_name` = ?, `process_instance`.`resource_type` = ?, `process_instance`.`resource_id` = ?, `process_instance`.`result` = ?, `process_instance`.`exit_reason` = ?, `process_instance`.`phase` = ?, `process_instance`.`start_process_server_id` = ?, `process_instance`.`running_process_server_id` = ? where `process_instance`.`id` = ?
2016-10-05T13:29:08.590787Z 13539 [Note] WSREP: cluster conflict due to certification failure for threads:
2016-10-05T13:29:08.590833Z 13539 [Note] WSREP: Victim thread:
   THD: 13539, mode: local, state: executing, conflict: cert failure, seqno: -1
   SQL: update `process_instance` set `process_instance`.`start_time` = ?, `process_instance`.`end_time` = ?, `process_instance`.`data` = ?, `process_instance`.`priority` = ?, `process_instance`.`process_name` = ?, `process_instance`.`resource_type` = ?, `process_instance`.`resource_id` = ?, `process_instance`.`result` = ?, `process_instance`.`exit_reason` = ?, `process_instance`.`phase` = ?, `process_instance`.`start_process_server_id` = ?, `process_instance`.`running_process_server_id` = ? where `process_instance`.`id` = ?
2016-10-05T13:29:08.593225Z 13411 [Note] WSREP: cluster conflict due to certification failure for threads:
2016-10-05T13:29:08.593244Z 13411 [Note] WSREP: Victim thread:
   THD: 13411, mode: local, state: executing, conflict: cert failure, seqno: -1
   SQL: insert into `process_instance` (`start_time`, `end_time`, `data`, `priority`, `process_name`, `resource_type`, `resource_id`, `result`, `exit_reason`, `phase`, `start_process_server_id`, `running_process_server_id`) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
2016-10-05T13:29:08.595012Z 13445 [Note] WSREP: cluster conflict due to certification failure for threads:
2016-10-05T13:29:08.595049Z 13445 [Note] WSREP: Victim thread:
   THD: 13445, mode: local, state: executing, conflict: cert failure, seqno: -1
   SQL: update `process_instance` set `process_instance`.`start_time` = ?, `process_instance`.`end_time` = ?, `process_instance`.`data` = ?, `process_instance`.`priority` = ?, `process_instance`.`process_name` = ?, `process_instance`.`resource_type` = ?, `process_instance`.`resource_id` = ?, `process_instance`.`result` = ?, `process_instance`.`exit_reason` = ?, `process_instance`.`phase` = ?, `process_instance`.`start_process_server_id` = ?, `process_instance`.`running_process_server_id` = ? where `process_instance`.`id` = ?
2016-10-05T13:29:08.602927Z 13411 [Note] WSREP: cluster conflict due to certification failure for threads:
2016-10-05T13:29:08.602955Z 13411 [Note] WSREP: Victim thread:
   THD: 13411, mode: local, state: executing, conflict: cert failure, seqno: -1
   SQL: update `process_instance` set `process_instance`.`start_time` = ?, `process_instance`.`end_time` = ?, `process_instance`.`data` = ?, `process_instance`.`priority` = ?, `process_instance`.`process_name` = ?, `process_instance`.`resource_type` = ?, `process_instance`.`resource_id` = ?, `process_instance`.`result` = ?, `process_instance`.`exit_reason` = ?, `process_instance`.`phase` = ?, `process_instance`.`start_process_server_id` = ?, `process_instance`.`running_process_server_id` = ? where `process_instance`.`id` = ?
2016-10-05T13:29:08.603064Z 13589 [Note] WSREP: cluster conflict due to certification failure for threads:
2016-10-05T13:29:08.603082Z 13589 [Note] WSREP: Victim thread:
   THD: 13589, mode: local, state: executing, conflict: cert failure, seqno: -1
   SQL: update `process_instance` set `process_instance`.`start_time` = ?, `process_instance`.`end_time` = ?, `process_instance`.`data` = ?, `process_instance`.`priority` = ?, `process_instance`.`process_name` = ?, `process_instance`.`resource_type` = ?, `process_instance`.`resource_id` = ?, `process_instance`.`result` = ?, `process_instance`.`exit_reason` = ?, `process_instance`.`phase` = ?, `process_instance`.`start_process_server_id` = ?, `process_instance`.`running_process_server_id` = ? where `process_instance`.`id` = ?
2016-10-05T13:29:08.609301Z 13589 [Note] WSREP: cluster conflict due to certification failure for threads:
2016-10-05T13:29:08.609321Z 13589 [Note] WSREP: Victim thread:
   THD: 13589, mode: local, state: executing, conflict: cert failure, seqno: -1
   SQL: update `process_instance` set `process_instance`.`start_time` = ?, `process_instance`.`end_time` = ?, `process_instance`.`data` = ?, `process_instance`.`priority` = ?, `process_instance`.`process_name` = ?, `process_instance`.`resource_type` = ?, `process_instance`.`resource_id` = ?, `process_instance`.`result` = ?, `process_instance`.`exit_reason` = ?, `process_instance`.`phase` = ?, `process_instance`.`start_process_server_id` = ?, `process_instance`.`running_process_server_id` = ? where `process_instance`.`id` = ?
2016-10-05T13:29:08.615958Z 13453 [Note] WSREP: cluster conflict due to certification failure for threads:
2016-10-05T13:29:08.615980Z 13453 [Note] WSREP: Victim thread:
   THD: 13453, mode: local, state: executing, conflict: cert failure, seqno: -1
   SQL: update `process_instance` set `process_instance`.`start_time` = ?, `process_instance`.`end_time` = ?, `process_instance`.`data` = ?, `process_instance`.`priority` = ?, `process_instance`.`process_name` = ?, `process_instance`.`resource_type` = ?, `process_instance`.`resource_id` = ?, `process_instance`.`result` = ?, `process_instance`.`exit_reason` = ?, `process_instance`.`phase` = ?, `process_instance`.`start_process_server_id` = ?, `process_instance`.`running_process_server_id` = ? where `process_instance`.`id` = ?
2016-10-05T13:29:08.623772Z 13534 [Note] WSREP: cluster conflict due to certification failure for threads:
2016-10-05T13:29:08.623801Z 13534 [Note] WSREP: Victim thread:
   THD: 13534, mode: local, state: executing, conflict: cert failure, seqno: -1
   SQL: insert into `process_execution` (`process_instance_id`, `uuid`, `log`, `created`) values (?, ?, ?, ?)

**Expected:**

**Comment by vincent99** [comment]
"cluster conflict due to certification failure..." means that there MySQL cluster had lost quorum and wires are disabled until the cluster is recovered.  So rancher is just trying to write and getting denied.

**Comment by roffe** [comment]
The quornum was lost due to Rancher doing strange things. It works with Percona 5.6 cluster so i suspect Rancher is not compatible with the new PXC strict modes. 

Is Rancher doing experimental functions in query that cannot be certified by a PXC cluster?

**Comment by vincent99** [comment]
All the querying is done through an abstraction library that supports multiple  servers (h2,  posters, oracle, etc) and produces very basic lowest common denominator queries  like the  one in the error you posted.   We don't do anything "strange", and an unprivileged client being able to make the server break quorum at will would be a serious bug in the DB server.
