### ISSUE TITLE
Feature: CLI HA Setup

### ISSUE THREAD

**Issue by jhmartin** [rancher/rancher#6156]
Generating and downloading the HA configuration seems to be only accessible in the GUI, which is very awkward to automate.  It looks like the interaction is done via websockets so reproducing the commands with something like Curl is also not feasible.

Please provide a mechanism to generate and download the HA configuration outside of the GUI. 

(1.1.4)

**Comment by andreimc** [comment]
👍  I created a script that automates HA well drives the gui to generate ha script downloads it and runs in on the servers. 

https://github.com/andreimc/rancher-ansible-ha

**Comment by deniseschannon** [comment]
This is no longer needed as we've refactored HA to be much simpler and just run additional arguments with the rancher-server command.
