### ISSUE TITLE
Infra catalog migrations needed

### ISSUE THREAD

**Issue by vincent99** [rancher/rancher#6157]
Exactly once after upgrade to 1.2, we need some data migrations to support new catalogs:
- Update catalog setting:
  - Change any entries with a value of `https://github.com/rancher/rancher-catalog(.git)?` to `https://git.rancher.io/rancher-catalog`
  - Change any entries with a value of `https://github.com/rancher/community-catalog(.git)?` to `https://git.rancher.io/community-catalog`
- Change orchestration stack externalIds:
  - `(system-)?catalog://library:(kubernetes|k8s):${num}` to `catalog://library:infra*k8s:${num}`.
    - Additionally, if $num  == 7, change it to 8, because reasons.
  - `(system-)?catalog://library:swarm:${num}` to `catalog://library:infra*swarm:${num}`.
  - `(system-)?catalog://library:mesos:${num}` to `catalog://library:infra*mesos:${num}`.
- Set Project orchestration fields

@deniseschannon These will not un-migrate on rollback, so the docs may need a warning or manual instructions to undo if the user wants to go back.

**Comment by vincent99** [comment]
`route53` also moved from `templates` to `infra-templates`, so its externalId needs to be migrated too.  And all the other external-dns templates should also probably be moved to infra for consistency (and then migrated).

**Comment by ibuildthecloud** [comment]
@vincent99 Can you tell me exactly what needs to be migrated?  I can add it to the existing list.

**Comment by vincent99** [comment]
```
templates := [
  "bind9",
  "cloudflare",
  "dnsimple",
  "dnsupdate-rfc2136",
  "pointhq",
  "powerdns-external-dns"
]

for k in range templates {
  replace(
    "(system-)?catalog://library:${k}:${num}",
    "catalog://library:infra*${k}:${num}"
  )
}
```

**Comment by rancherdev** [comment]
On an upgraded setup( from v1.1.4 -> v1.2.0-pre4-rc10) , existing K8s stack is showing as "upto date" and when hovered on shows "current:undefined" . Expect to be presented with option to upgrade to k8s 1.4.x.

**Comment by sangeethah** [comment]
On an upgraded setup( from v1.1.4 -> v1.2.0-pre4-rc10) , existing K8s stack is showing as "upto date" and when hovered on shows "current:undefined" . Expect to be presented with option to upgrade to k8s 1.4.x.

**Comment by ibuildthecloud** [comment]
@sangeethah this is an issue in the catalog service.  The catalog entry was migrated correctly.

**Comment by deniseschannon** [comment]
Created #6704 for the catalog service issue.

**Comment by deniseschannon** [comment]
@sangeethah 

Can you test the k8s upgrade migration as well as the DNS ones? 

Route 53 and the other external DNS providers in community catalog have been migrated to infra-templates.

**Comment by soumyalj** [comment]
Tested with upgrade from 1.1.4 to 1.2.0-pre4-rc14. K8s catalog migration is fixed. "Upgrade available" option is seen to upgrade to K8s1.4.6. 

I was able to see "Upgrade available" option for Route 53 DNS catalog item. The Route 53 DNS containers upgraded successfully

**Comment by deniseschannon** [comment]
did you test any o the other dns providers @soumyalj? they come from a different catalog, so need to be tested separately.

**Comment by deniseschannon** [comment]
Can you please test one of the external providers since it's coming form a different catalog starting point (community-catalog versus rancher-catalog)?

**Comment by deniseschannon** [comment]
The specific test should be launch catalogs in 1.1.4, upgrae to 1.2.0/upgrade environment. 

Check external ID of stacks are now coming from the new template source, which should be `library:infra` or `community:infra`

<img width="380" alt="screen shot 2016-11-23 at 2 17 28 pm" src="https://cloud.githubusercontent.com/assets/11410997/20580534/a54ae734-b187-11e6-8c25-47f1a6549fd2.png">

**Comment by deniseschannon** [comment]
Using v1.2.0-pre4-rc14 - DNS/External DNS/k8s migrations are good.

Mesos/Swarm migration did not work. 

Apparently in 1.1.4 mesos and swarm's externalId was `system://mesos` and `system://swarm`, so those don't get handled by `migrateLibraryStacks()` (Because they were never actually deployed by the catalog..)

What @vincent99 said above.

**Comment by deniseschannon** [comment]
We won't be migrating the swarm service as the previous stack was using Docker's original swarm implementation and our new swarm service will be using the one packaged in Docker 1.12.

**Comment by tfiduccia** [comment]
Version - 1.1.4 -> 1.2.0-pre4-rc15
Verified fixed
