### ISSUE TITLE
2 entries shown in hosts view for every host added.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6160]
Rancher server version - v1.2.0-pre4-rc1

Steps to reproduce the problem:
Add a Digital Ocean host.
There is 1 host entry that appears immediately which does not have any info about the host and where containers cannot be deployed .

After some time I see the real host entry show up where containers can be deployed.

<img width="1370" alt="screen shot 2016-10-05 at 1 04 36 pm" src="https://cloud.githubusercontent.com/assets/4266958/19129505/6694dfec-8afc-11e6-8f70-9e3ed74e8b5f.png">

**Comment by vincent99** [comment]
This was a backend bug that should be fixed now

**Comment by sangeethah** [comment]
This issue is not seen anymore with v1.2.0-pre4-rc3.
