### ISSUE TITLE
have rancher-metadata environment object available for standalone containers

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#6161]
Currently the environment metadata can only be queried by containers that reside in a stack. It might be helpful to move the environment object to containers, or self, path.

**Comment by davidwindell** [comment]
Please I can I add my vote for this. We want to use traefik with metadata to manage containers launched directly on the node (by other containers) but these don't appear to work at the moment :(

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
