### ISSUE TITLE
Editing hosts to add labels fails with error message - "Name" is required

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6162]
Rancher server version - 

Steps to reproduce the problem:
Edit host and add a new label and click on "Save".

<img width="978" alt="screen shot 2016-10-05 at 1 38 29 pm" src="https://cloud.githubusercontent.com/assets/4266958/19130679/15034876-8b01-11e6-853a-0e0e398f4829.png">

**Comment by vincent99** [comment]
Part of https://github.com/rancher/rancher/issues/6193
