### ISSUE TITLE
ear

### ISSUE THREAD

**Issue by Droxyum** [rancher/rancher#6164]
**Rancher Version:**

**Docker Version:**

**OS and where are the hosts located? (cloud, bare metal, etc):**

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**

**Results:** 

**Expected:**

**Comment by willseward** [comment]
I hear ya...
