### ISSUE TITLE
Safari Browser back button doesnt allow selecting versions from drop down

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#6166]
**Rancher Version:**
1.2.0-pre3
**Docker Version:**
1.12.1
**OS and where are the hosts located? (cloud, bare metal, etc):**
Baremetal/cloud
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node Rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
With safari browser
1. Click on catalog
2. Select kibana
3. Select version 4.1.1
4. Click back button
5. Click kibana again in catalog
6. Try to select 4.1.1 from the drop down
**Results:** 
You can no longer select 4.1.1
**Expected:**
you can still select 4.1.1

**Comment by tfiduccia** [comment]
Version - master 10/27
Verified fixed
