### ISSUE TITLE
Cosmetic/usability bugs in 1.2.0-pre4-rc1

### ISSUE THREAD

**Issue by rlex** [rancher/rancher#6167]
**Rancher Version:**
1.2.0-pre4-rc1

Should i split them in separate tickets?

1) Go to catalog, choose any catalog but "all", you will see "Catalog: All" on any page. I suspect that should show current catalog rather than "all". For example, i've chosen "mediadepot" catalog, but it still says "All".

<img width="568" alt="screen shot 2016-10-06 at 3 58 53 pm" src="https://cloud.githubusercontent.com/assets/84462/19153221/3d52bafe-8bde-11e6-8b2e-d3c908d64f72.png">

2) If you have balancer forwarded to multiple endpoints, there will be extra spaces between containers and ports, that looks a bit odd:
<img width="239" alt="screen shot 2016-10-06 at 3 52 24 pm" src="https://cloud.githubusercontent.com/assets/84462/19152945/13b63f3c-8bdd-11e6-83ef-ca7d0b3bfafd.png">

3) If you try to edit balancer, it will not fit monitor on some configurations, and you can't scroll it:

<img width="1916" alt="screen shot 2016-10-06 at 3 55 36 pm" src="https://cloud.githubusercontent.com/assets/84462/19153032/6a3ce7de-8bdd-11e6-9184-0b1ff0901f0a.png">

So the only way to reach "save/cancel" buttons is to use tab button.
This applies to "edit service" modal as well.

UPD: Chrome Version 53.0.2785.143, Mac OS X, adblock / userstyles / etc disabled for rancher.

**Comment by vincent99** [comment]
@rlex most of these are fixed in master already, but FYI you really don't want to be using rc1; a lot is broken, including cross host networking in general.

**Comment by rlex** [comment]
this is test installation "for fun". So if i want to test new things, i want to use -pre without -rc?
