### ISSUE TITLE
Show system requirements in README.md

### ISSUE THREAD

**Issue by adamkdean** [rancher/rancher#617]
Rancher management server uses between 400 and 500 MB of memory, and running this on a 512 MB droplet can cause the server to become very slow and unresponsive (obviously). A Rancher agent uses ~120 MB of memory to begin with, so running this along with the management server can kill a small droplet.

It'd would therefore be nice to see that the management server requires > 512 MB of ram, preferably 1 GB.

**Comment by keyscores** [comment]
+1 
wish I had known that

**Comment by vincent99** [comment]
This is on http://docs.rancher.com/rancher/installing-rancher/installing-server/ and https://github.com/rancher/rancher
