### ISSUE TITLE
Rancher UI token collides with token on different subdomain

### ISSUE THREAD

**Issue by bdentino** [rancher/rancher#6170]
**Rancher Version:**

Rancher 1.2.0-pre2

**Docker Version:**

v1.11.2

**OS and where are the hosts located? (cloud, bare metal, etc):**

RancherOS on AWS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

Single Node, External DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

Cattle

**Steps to Reproduce:**

We host our rancher UI at `https://rancher.<domain>`, and our app at `https://<domain>`. Our subdomain also uses cookie-based authentication, and puts the token in a cookie named 'token', which is shared across all other subdomains. This collides with rancher's 'token' cookie, so if I log into our app at `https://<domain>`, I essentially get logged out of rancher and have to clear my cookies before I can log back in (and vice-versa when I log into rancher). This is a minor inconvenience, but could be avoided by prefixing the cookie name for rancher to something a little less generic, e.g. 'io.rancher.token'. After realizing what the problem is, we will probably prefix our own token as well, but I wanted to put this here since I don't see the harm in getting a fix in rancher as well.

**Results:** 

See 'Steps to Reproduce'. Here's a discussion about the underlying problem of cookie collision: https://github.com/jshttp/cookie/issues/18

**Expected:**

Not sure how many rancher users have similar setups, but it would be nice if the token were prefixed so that this type of collision were less likely.

**Comment by vincent99** [comment]
This is unfortunately more effort than I think it's worth for this edge case to update all the services expecting `token`, handle backwards compatibility, carefully avoid potential security problems with the backwards compatibility code handling two fields and two perennially different tokens in each project in several languages, etc. 

It also doesn't solve the underlying problem in generall, and still  exposes your app's cookies to the Rancher UI, where they could be read or used maliciously by whoever controls the Rancher install (or, from your perspective, me).  A better solution is running both on neighboring subdomains (or a different domain entirely) so neither can read each other's cookies.
