### ISSUE TITLE
Use docker bundle to create stack / services

### ISSUE THREAD

**Issue by alfirin** [rancher/rancher#6171]
**Rancher Version:**
1.2 / 1.3

**Docker Version:**
1.12

**Improvement**
Could we use the new `docker bundle` command in order to package our services.

It could be useful in order to create / upgrade / delete a particular stack.

See [here](https://github.com/docker/docker/issues/26876) in order to view the `docker bundle` documentation.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
