### ISSUE TITLE
Host waiting page not showing up for new environments

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#6175]
**Rancher Version:** master 10/6

**Steps to Reproduce:**
1.  Create a new environment
2.  Switch to this environment

**Results:** Get Adding your first stack

**Expected:** Should get Adding your first host

**Comment by vincent99** [comment]
Changed to always show on the header instead of forcing you to waiting page.

**Comment by tfiduccia** [comment]
Version - master 10/10
Verified fixed
