### ISSUE TITLE
rancher agent should log /var/log/rancher/agent.log in host.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6191]
Rancher Version: v1.2.0-pre4-rc2

Currently there is no agent.logs generated by rancher agent .
rancher agent should log /var/log/rancher/agent.log in host.

**Comment by ibuildthecloud** [comment]
@sangeethah I don't think I want this anymore.  It has always been confusing for people to troubleshoot because the docker logs and /var/log/rancher/agent.log have different information.  I would prefer to just put everything in the docker logs.

**Comment by StrongMonkey** [comment]
@sangeethah According to the comment from @ibuildthecloud, i ll close this issue. The logs are still available from `docker logs`.
