### ISSUE TITLE
Execute shell windows stay open for only a short period of time

### ISSUE THREAD

**Issue by kenluberts** [rancher/rancher#6192]
_Describe your issue here_

Our users make use the the Execute Shell feature quite a bit.  We've noticed that with version 1.1.3 we are seeing an issue where these windows stay open only for a short period of time.  Also, the length of time seems to be very random as to how long the window (shell) does stay open.  

---

| Useful | Info |
| :-- | :-- |
| Versions | Rancher `v1.1.3` Cattle: `v0.165.8.1` UI: `v1.1.12` |
| Access | `github` `admin` |
| Orchestration | `Cattle` |
| Route | `admin-tab.settings` |

**Comment by aemneina** [comment]
I believe there is nothing in the UI that actually closes the window. Its more the byproduct of something terminating the connection, after inactivity, and timing out.

**Comment by vincent99** [comment]
Yes, the UI does not close the connection.  A load balancer, proxy, or other device is closing the connection.

**Comment by smazurov** [comment]
I have this issue as well, possibly related to #4983 ?

**Comment by aemneina** [comment]
If thats the case @smazurov can you try extending the ELB timeout by following this doc: https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/config-idle-timeout.html#config-idle-timeout-console

**Comment by aemneina** [comment]
I also noticed in an HA stack that the load balancer has a client and server connection timeout of 50. That can be modified manually, but if one of those containers gets recreated, the configuration for that container would revert.

**Comment by drpebcak** [comment]
Following @aemneina over here... I've been hitting this issue too. Is there an ETA on the fix?

**Comment by ecliptik** [comment]
We had this issue too when accessing the Rancher UI through an AWS ELB.

Increasing the **Idle Timeout** to _1200_ seconds fixed the issue for us.

**Comment by Napsty** [comment]
When you're running a self-hosted Rancher behind a HAProxy, it helps to set "timeout client 1h" in the frontend and "timeout server 1h" in the backend. After this change the "Execute Shell" window stays open. Before that it would disappear, more or less after 1min (which is the default timeout in my HAProxy setup).

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

**Comment by peternann** [comment]
For the benefit of future Googlers like me: There is a hack you can use to work around your Rancher pod shells timing out... Just run this in the shell you want to keep alive:
$ `while sleep 30 ; do echo -en "\025" ; done &`

All this does is occasionally put traffic on the terminal websocket, so it doesn't auto-close.
\025 is ASCII 'NAK' which doesn't seem to affect the terminal.

Seems to work. Happy days!

**Comment by aghanchi** [comment]
> For the benefit of future Googlers like me: There is a hack you can use to work around your Rancher pod shells timing out... Just run this in the shell you want to keep alive: $ `while sleep 30 ; do echo -en "\025" ; done &`
> 
> All this does is occasionally put traffic on the terminal websocket, so it doesn't auto-close. \025 is ASCII 'NAK' which doesn't seem to affect the terminal.
> 
> Seems to work. Happy days!

This worked. Thanks !
