### ISSUE TITLE
Combined machine->host bugs

### ISSUE THREAD

**Issue by vincent99** [rancher/rancher#6193]
- `hostname` needs to be creatable but not editable
- `name` should not be required
- Hosts in some states (`provisioning`, possibly others?) can't be deleted

**Comment by deniseschannon** [comment]
Note: This is preventing swarm testing as labels are not able to be set onto hosts for swarm deployment as the `name is required`.

**Comment by sangeethah** [comment]
With latest build from master, I am not able to add Digital Ocean machine. User is presented with - "Name" is required  error message even after name is provided.

**Comment by sangeethah** [comment]
Tested with latest build from master:

1.Able to add Digital Ocean machine successfully.
2.Able to edit host and add labels successfully.
3. Not allowed to edit host name , but name is editable.

I am still having problems when trying to delete a host when it is provisioning state.
I see it get deleted ( or atleast removed from the host view) for sometime. But it reappears again in  host list view in "registering" state.
When listing host using API , the deleted host is not listed. But it is still listed in machine list API in "active" state,

**Comment by sangeethah** [comment]
Tested with rancher-server version - v1.2.0-pre4-rc5

When deleting a host that is  still in provisioning state, host gets to "removing" state and then disappears from the UI.
Machine entry associated with this host continues to remain in DB in "removing" state for a while and then gets to "removed" state.
