### ISSUE TITLE
Unable to add new host to fresh rancher (v1.2.0-pre4-rc2) install

### ISSUE THREAD

**Issue by MadOtis** [rancher/rancher#6194]
**Rancher Version:**
v1.2.0-pre4-rc2

**Docker Version:**
Docker version 1.11.2, build bac3bae

**OS and where are the hosts located? (cloud, bare metal, etc):**
CoreOS 1185.1.0 - rancher server and hosts are all VMware (ESXi 6.0) VMs

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher w/ default internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
None, yet... can't register any hosts to set one up

**Steps to Reproduce:**
1) Perform bare-metal coreos installs of 5 hosts (1 rancher server, 4 hosts) on VMware ESXi 6
2) Launch rancher server with: 'docker run -d --restart=unless-stopped -p 8080:8080 rancher/server:v1.2.0-pre4-rc2'
3) set up auth services to A/D or OpenLDAP
4) Add host (copy URL)
5) Paste onto node/host
6) Wait for hours and never see a host register

**Results:** 
None of the 4 hosts registered ever show up in Rancher Server UI

**Expected:**
4 hosts should be displayed in the Rancher Server UI

** NOTES: **
* I have confirmed that there IS communication between the 4 "host" machines and the "server" machine and CAN curl between them all.
* I have confirmed that I can step back to 1.1.4 server and 1.0.2 agent and successfully register hosts on the same VMware ESXi hosts with the same CoreOS VM image.

**Comment by vincent99** [comment]
This is the same as https://github.com/rancher/rancher/issues/4500 ; CoreOS now packages a version of Docker compiled with Golang 1.6 instead of the binaries from Docker (that are 1.5) and this breaks older Docker clients.

**Comment by vincent99** [comment]
Scratch that...

```
ime="2016-10-07T22:09:08Z" level=error msg="Error processing event" err="Ping: failed to do ping action: DoPingAction: failed to add resource: AddResource: failed to get physical host: PhysicalHost: failed to get hostname: HostName: : GetFQDNLinux: : exit status 1" eventId=e1f32f61-d7db-49fb-9c06-a7b5fc71386e eventName=ping resourceId=1a46
```

`hostname -f` doesn't work on CoreOS and is new to the agent.

**Comment by StrongMonkey** [comment]
In new agent we use `hostname -f` to get fqdn and if failed we will not be able to register the host. i Will try to get a workaround for that.

**Comment by kbrownlees** [comment]
Using ubuntu 16.04 and v1.2.0-pre4-rc2 my hosts get added but something else is not configured correctly - attempting to configure kubernets bumps me to the 'adding your first host screen' even though I have three hosts available under infrastructure -> hosts.

**Comment by tfiduccia** [comment]
@kbrownlees - this is a known issue.  Both the Add host screen and kubernetes issues have been reported.  Should be fixed in the next release.

**Comment by soumyalj** [comment]
Tested with v1.2.0-pre4-rc5. Used CoreOS 1185.2.0 server and 3 hosts [Docker 1.11.2]. 
1. Started rancher server using the following command
docker run -d --restart=unless-stopped -p 8080:8080 rancher/server:v1.2.0-pre4-rc5
2. Added the hosts using the URL from "add host" button
3. After a minute, the hosts were registered successfully
4. Container creation was fine too
