### ISSUE TITLE
Excessive number of volumes in mysql DB could be the cause to freeze up web UI ?

### ISSUE THREAD

**Issue by virtuman** [rancher/rancher#6196]
**Rancher Version:**
rancher/server:v1.2.0-pre4-rc1

**Docker Version:**
Server Version: 1.12.1

**OS and where are the hosts located? (cloud, bare metal, etc):**
3 x Dedicated bare metal servers
PRETTY_NAME="Ubuntu 16.04.1 LTS"

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
single network interfaces on all 3 servers
external mysql DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
We had rancher running for a few months, just never had problem with the UI until recently.
Recently we noticed that client machines that we use to access Rancher UI get really overloaded on rancher ui session login.

It's taking over 20 seconds to get to the response on Ajax request to:
/v2-beta/projects/1a5/mounts?limit=-1&sort=name

**Results:** 
I'm just interested if this number of volumes is what's causing the client machines to go bananas on rancher ui session init:

This query makes me wander if something in my distribution is just going insanely wrong:
`SELECT table_name, table_rows, data_length, index_length FROM information_schema.TABLES WHERE table_schema = 'rancher' AND table_rows > 1000`

granted I like labels, but this ditribution is running very-very few services, these row counts seem excessively high?

```
table_name                                     table_rows  data_length  index_length  
instance_label_map                             187698      28884992     45252608      
mount                                          49139       8929280      14811136      
volume                                         30477       9977856      22331392      
volume_storage_pool_map                        28736       4734976      8929280       
nic                                            19553       3686400      5242880       
image                                          19272       12075008     6569984       
instance_host_map                              18837       4734976      4030464       
label                                          17169       3686400      4816896       
image_storage_pool_map                         17030       2637824      3620864       
container_event                                16636       77168640     2359296       
ip_address_nic_map                             16616       2637824      3768320       
ip_address                                     16578       2637824      4636672       
instance                                       11470       232374272    9240576       
process_execution                              10709       119635968    4554752       
port                                           10667       2637824      3358720       
process_instance                               9671        7356416      1785856       
audit_log                                      6024        34127872     966656        
service_expose_map                             5398        1589248      1245184       
instance_link                                  4716        2637824      1261568       
service_log                                    2351        1523712      245760        
external_handler_external_handler_process_map  2214        393216       475136        
healthcheck_instance_host_map                  1343        262144       491520        
service_index                                  1145        212992       376832        
```

**Expected:**
not sure if described above is an appropriate behaviour or if something is wrong. but the distribution is practically unusable, very-very slow with just 3 nodes, and maybe 12-15 stacks of services with 2-3 containers in each stack

**Comment by aemneina** [comment]
@virtuman 1.2.0-pre4(*) has some destabilizing changes in it. It's not recommended for use outside of test. Can you revert to a known good setup (might involve restoring your db from a previous backup). Closing the issue.
