### ISSUE TITLE
Certificate issue while adding host - need Intermediate CA

### ISSUE THREAD

**Issue by albenshao** [rancher/rancher#6201]
**Rancher Version:**
1.1.4

**Docker Version:**
1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 14.04.4 LTS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
AWS ELB + HA rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
   1. Setup 3 rancher following [this guide](http://docs.rancher.com/rancher/v1.2/en/installing-rancher/installing-server/multi-nodes/) , and also added AWS ELB. The rancher server (access via ELB) runs successfully.
   2. Tried to "add host" to the rancher environment, got the ssl certificate error. **Note: the certificate for my "https" url need an ["Intermediate CA"](https://knowledge.symantec.com/support/ssl-certificates-support/index?page=content&actp=CROSSLINK&id=AR2064)**
       a) When "add host", I got "is not accessible" error reported from "curl" which was acturally is the SSL certificate issue. 
       b) Then I imported the "Intermediate CA" (copy CA to /usr/local/share/ca-certificates/ and run "sudo update-ca-certificates". The above curl error is solved. But got the SSL error from resolve_url.py: 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed'

**Results:** 
'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed'

**Expected:**
"add host" can be OK.

**Comment by aemneina** [comment]
@albenshao I think you need to be following these instructions here: http://docs.rancher.com/rancher/v1.2/en/installing-rancher/installing-server/basic-ssl-config/#using-self-signed-certs-beta 

Take note of the adding hosts section.

**Comment by albenshao** [comment]
Thanks Aemneina! 
It works when I put all required certificates in /var/lib/rancher/etc/ssl/ca.crt.

BR/Alben

**Comment by aemneina** [comment]
Excellent news, I'll close out this issue.

**Comment by redb** [comment]
@albenshao hi could you tell me what youput exactly in ca.crt ? or you only a ca.crt empty file ?
thank you
