### ISSUE TITLE
How can upload config file  when add stack?

### ISSUE THREAD

**Issue by Dreampie** [rancher/rancher#6202]

**Comment by aemneina** [comment]
@Dreampie can you give more details? What type of service is this? You might want to bind mount the file into the container.

**Comment by Dreampie** [comment]
https://github.com/Dreampie/docker-elk  like this，how can  convert stack？

**Comment by aemneina** [comment]
take a look here: https://github.com/rancher/community-catalog/tree/master/templates/elasticsearch-2/0

closing issue.
