### ISSUE TITLE
I can't add host to Rancher Server 1.1.4

### ISSUE THREAD

**Issue by tonythian** [rancher/rancher#6204]
"Docker logs rancher-agent" shown the following error:

INFO: Starting agent for 2794E6302BCEBD0A48C3
INFO: Access Key: XXX
INFO: Config URL: http://server.com:8080/v1
INFO: Storage URL: http://server.com:8080/v1
INFO: API URL: http://server.com:8080/v1
INFO: IP: x.x.x.x
INFO: Port:
INFO: Required Image: rancher/agent:v1.0.2
INFO: Current Image: rancher/agent:v1.0.2
INFO: Using image rancher/agent:v1.0.2
INFO: Downloading agent http://server.com:8080/v1/configcontent/configscripts
{"id":"04aab79f-cbdd-47a2-9e5b-a6d915740dc6","type":"error","links":{},"actions":{},"status":422,"code":"MissingRequired","message":null,"detail":null,"fieldName":"agentId"}
gzip: stdin: not in gzip format
tar: Child returned status 1

---

| Useful | Info |
| :-- | :-- |
| Versions | Rancher `v1.1.4` Cattle: `v0.165.8.4` UI: `v1.1.14` |
| Access | `localauth` `admin` |
| Orchestration | `Cattle` |
| Route | `hosts.index` |

**Comment by aemneina** [comment]
Hi @tonythian is your rancher server accessible from the agent host, can it route to it?

**Comment by clouderding** [comment]
i have the problem also. How to solve?

**Comment by clouderding** [comment]
参考这个帖子。https://github.com/rancher/rancher/issues/1370

**Comment by aemneina** [comment]
@tonythian did the solution in Ding's post solve it for you?

**Comment by tonythian** [comment]
@aemneina My rancher server & rancher agent is in LAN environment so server accessibility is no problem.  It was working fine previously until I upgraded ubuntu from 15.04 to 16.04.1 LTS (4.2.0-42-generic).

Ding's post didn't solve my problem, I tried to remove the /var/lib/rancher/state folder and it still failed with same error:

INFO: ENV: RANCHER_AGENT_IMAGE=rancher/agent:v1.0.2
invalid value "." for flag -v: . is not an absolute path
See 'docker run --help'.

**Comment by aemneina** [comment]
@tonythian are you still facing this?

**Comment by tonythian** [comment]
Yes, still facing this issue with rancher-agent:v1.0.2

**Comment by aemneina** [comment]
can you provide the output of `docker info` and what is the host operating system?

**Comment by tonythian** [comment]
docker info output:
Containers: 44
 Running: 4
 Paused: 0
 Stopped: 40
Images: 262
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 376
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.0-45-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.789 GiB
Name: ubuntu14
ID: X3E5:ELA2:X64X:U3ZK:KP2J:3N4M:PIB6:2LSZ:SJMI:IDEK:NMNM:ELZQ
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support

**Comment by aemneina** [comment]
from the rancher agent host can you curl http(s)://RANCHER_URL(:port)/v1? can you also post the full logs from the rancher-agent container?

**Comment by aemneina** [comment]
I'll close this out, if you can provide the info requested in the last comment, and are still facing the issue fee free to reopen.
