### ISSUE TITLE
Manage additional container networks with Rancher

### ISSUE THREAD

**Issue by ahoeg** [rancher/rancher#6205]
With rancher server I'm able to manage one network interface. It isn't possible to add additional interfaces  from UI (docker network connect ...).

If I add additional networks / interfaces the additional interfaces lost during stack upgrade.

Any plans to add support to manage additional interfaces with rancher server?

**Comment by willseward** [comment]
I believe you are looking for this: https://github.com/rancher/rancher/issues/5715

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
