### ISSUE TITLE
Service upgrade doesnt work if Sidekicks are present

### ISSUE THREAD

**Issue by toughIQ** [rancher/rancher#6207]
**Rancher Version:**
v1.2.0-pre4-rc2
**Docker Version:**
1.12.2-rc3
**OS and where are the hosts located? (cloud, bare metal, etc):**
Linux Mint 18 4.4.0-21-generic / Local VM
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node Rancher, external MariaDB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
Run any service from catalog, which uses sidekick containers. Eg. Jenkins or Drone.
After service is deployed, choose "Upgrade".

**Results:** 
A blank page with just the headline: "Upgrade X services"  (X=number of services, with Jenkins its 3)
![rancher1 2 0-pre4-rc2_upgradeerror](https://cloud.githubusercontent.com/assets/6234362/19243258/2800125a-8f17-11e6-85ac-9050ad51cfdd.png)

**Expected:**
Get upgrade page to change values as desired. At v1.1.x there were checkboxes to choose, which container(s) to upgrade.
![rancher1 1 3_upgradeerror](https://cloud.githubusercontent.com/assets/6234362/19243163/bc661c6a-8f16-11e6-8dbd-0afc4caa0907.png)

**Comment by tfiduccia** [comment]
Version - master 10/10
Easy steps to just create a service with sidekick.  Doesn't have to be from catalog.

**Comment by alena1108** [comment]
@vincent99 when I click Upgrade, the UI sends this request that never finishes:

GET http://localhost:8080/v2-beta/projects/1a5/services?limit=-1&sort=name

I can execute this request manually fine. @vincent99 what do you think could cause it?

**Comment by alena1108** [comment]
Seeing these UI errors on the list request:

```
component.js:169 Uncaught TypeError: l.get is not a function(anonymous function) @ component.js:169(anonymous function) @ component.js:166f.get @ ember.prod.js:14029r @ ember.prod.js:18663t.compute @ ember.prod.js:12122t.value @ ember.prod.js:11997e.value @ ember.prod.js:40501e @ ember.prod.js:11828e.create @ ember.prod.js:10213t.evaluate @ ember.prod.js:41229e.execute @ ember.prod.js:47710t.handleException @ ember.prod.js:48160e.handleException @ ember.prod.js:48340e.throw @ ember.prod.js:48057t.evaluate @ ember.prod.js:43555e.execute @ ember.prod.js:48044e.rerender @ ember.prod.js:47983s.render @ ember.prod.js:9562f @ ember.prod.js:9511e._renderRoots @ ember.prod.js:9822e._renderRootsTransaction @ ember.prod.js:9860e._revalidate @ ember.prod.js:9899invoke @ ember.prod.js:328flush @ ember.prod.js:396flush @ ember.prod.js:520end @ ember.prod.js:590(anonymous function) @ ember.prod.js:1156
firebug-lite.js:18877 Uncaught InvalidStateError: Failed to read the 'responseText' property from 'XMLHttpRequest': The value is only accessible if the object's 'responseType' is '' or 'text' (was 'blob').
```

**Comment by vincent99** [comment]
@alena1108 This is because the `type` is missing from the `secondaryLaunchConfig` entries

**Comment by virtuman** [comment]
having exact same issue, any way to be able to upgrade service in version 1.2.0-pre4-rc2 or will building from master help with upgrading functionality? or do we need to wait for the next version to try it out?

**Comment by tfiduccia** [comment]
Version - v1.2.0-pre4-rc4
Verified fixed
