### ISSUE TITLE
"machine config" option not seen for hosts added using machine drivers. 

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6211]
Rancher Version: Build from master

Steps to reproduce the problem:

Add Digitial Ocean Machine.
There in no "machine config" option on the host presented to user for being able to download the machine config.

**Comment by deniseschannon** [comment]
Not able to reproduce from master on 10/12. 

@sangeethah Can you test again?

**Comment by sangeethah** [comment]
"Machine Config" options are shown now when adding Digitial Ocean Machine .Able to download machine config and use it to access the hosts.

**Comment by sangeethah** [comment]
Reopening this issue.

We encounter this issue more often now on automated deployment of rancher-server (v1.6.8-rcx).

**Comment by sangeethah** [comment]
Reopened a wrong issue by mistake. Closing this issue.
