### ISSUE TITLE
Stopping Docker Containers Gracefully

### ISSUE THREAD

**Issue by PCXDME** [rancher/rancher#6214]
Some of my containers need more time to stop after receiving `SIGTERM` signal.
When stop using `docker stop`, we can specify seconds to wait for stop before killing the container using `docker stop -t {time} {container}`.
https://docs.docker.com/engine/reference/commandline/stop/
I think this should be configurable in `Command` tab, something like this.
![image](https://cloud.githubusercontent.com/assets/6277471/19248625/784b5230-8f5b-11e6-8820-c59c83391190.png)

**Comment by will-chan** [comment]
@StrongMonkey will this be made available in your work in adding the remaining docker options?

**Comment by StrongMonkey** [comment]
@will-chan I think there is already a field in cattle that is passed to agent to specify timeout in stopping container but it is not added in UI.

**Comment by westlywright** [comment]
@tfiduccia I've added a new modal to containers for the stop action. You should be able to set a stop timer or leave empty for default of 10 seconds. Additionally you can by pass the stop container modal with the alt action (e.g. deactivate, delete, etc).

**Comment by tfiduccia** [comment]
Not sure how useful this will be:
1.  The input field is in the container's stop modal.  So to get this working you have to go to each specific container and click stop then enter the amount of seconds, then stop the container.  The information is not saved and must be done every time you stop.
2.  Most containers are created by a service.  Since the service is not stopped, the container will not really ever stop.  The service will just reactivate it.  Since this does not exist on the service level, it's not really useful unless you create a stand-alone container.

But, I did verify that the timeout field exist in container's stop modal, and it's being posted.  So I can close if you like.

**Comment by will-chan** [comment]
I agree with you Tani so please close if this works.

**Comment by vincent99** [comment]
Doing anything beyond simple container action is going to be cattle and possibly host-api change... The timeout is not an actual property of a Docker container.

**Comment by deniseschannon** [comment]
The actual fix should be the ability define a timeout at the service level since this is how we start/manage all containers. 

Currently, we've added a workaround so that you could individually set this for each container, which will be in 1.2.0.

**Comment by giovannicandido** [comment]
Will the remove catalog action respect this timeout?

I remove a server stack which has a postgresql container. It's container has a persistent volume, which gets corrupted after the action.

**Comment by vincent99** [comment]
@giovannicandido This is an open issue so not something that is actually implemented.  There is an option to set the timeout at the time that you stop it, but not one to set the default or apply it for delete.

**Comment by ekristen** [comment]
I'd like to see a config option that can be set via label or something else per service/container.

We have some services that rely on interacting with physical hardware and we have to exit cleanly.

**Comment by Flowman** [comment]
I'm trying to build a new PXC image for the catalog. I'm run in to this issue when I trying to stop the service PXC adds an extra 10sec delay before stopping the services. So rancher goes in a kills all containers before they have shutdown gracefully and will put all host in non-primary state and kills the cluster.

It would be nice to have a flag in the UI for the docker stop timer as it cannot be that hard to add.

**Comment by peterloron** [comment]
This is a serious issue for us! Please expose this at least as a global setting or in the compose files so we can adjust the timeout.

**Comment by borntorock** [comment]
Any update on this issue? When shall we expect to have closure on this, so that everyone using Rancher in production is able to mention the timeout per service / container level in either docker-compose.yml or rancher-compose.yml config file, for the clean exit of docker containers.

**Comment by borntorock** [comment]
@vincent99 `The timeout is not an actual property of a Docker container.` --> the timeout is indeed an actual property of a docker container and is present with both docker stop command and docker-compose stop command. 

Even there's an option to mention the stop grace period in docker-compose.yml file `https://docs.docker.com/compose/compose-file/compose-file-v2/#stop_grace_period`

**Comment by vincent99** [comment]
The stop timeout, signal, upgrade batch size/interval/strategy and any other related options I'm forgetting are fields that can be set and are retained on containers/services in 2.0.

I think stop_timeout specifically is in the api/compose for 1.6.9, but UI for it and the others in general will not be coming before 2.0.

**Comment by gkawamoto** [comment]
@vincent99 do you mean that Rancher pre-2.0 won't be supporting this feature at all or simply that the change request won't be considered before all the 2.0 work is done?
It's a key feature for us since we're working with transactional features in our company and a unexpected SIGKILL is simply not acceptable in those, so we'll need to find another solution for either the orchestrator or our logic.

Thanks in advance.

**Comment by tarantegui** [comment]
Any news on this? Are you releasing this feature on v2 or on v1.6? We need this so bad for production environments.

**Comment by ekristen** [comment]
There’s no concept of stopping containers in v2, it’s not a feature of kubernetes.

**Comment by vincent99** [comment]
2.0 at the time that was written was more like a new version of cattle and just k8s.

The options in current 2.x are what k8s has and we don't implement new capabilities it doesn't have in general.  There is no "stop"/"start"/"restart" but pods still go through a life cycle which has timeouts and hooks:

https://kubernetes.io/docs/concepts/workloads/pods/pod/

1.x is in maintenance mode and not going to be getting new features.

**Comment by jgimenez** [comment]
I found this, not sure if it's going to work https://docs.docker.com/compose/compose-file/compose-file-v2/#stop_grace_period

**Comment by jgimenez** [comment]
> I found this, not sure if it's going to work https://docs.docker.com/compose/compose-file/compose-file-v2/#stop_grace_period

I tried, it seems like it didn't work
