### ISSUE TITLE
Clicking kubernetes menu option during setup causes weird button and errors to show up

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#6218]
**Rancher Version:** master 10/10

**Steps to Reproduce:**
1.  Create an environment and add hosts
2.  Go to stacks and select kubernetes orchestration
3.  (refresh if needed to see kubernetes menu items)
4.  Click on kubernetes menu

**Results:** Weird button and error text showing up
![image](https://cloud.githubusercontent.com/assets/11514927/19253382/8579f3be-8eff-11e6-954d-ea2dadd2670b.png)

**Expected:** NO button or error text.

**Comment by vincent99** [comment]
The errors are no longer shown

**Comment by vincent99** [comment]
The errors are no longer shown
