### ISSUE TITLE
Switching out of kubernetes environment is causing errors in UI

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#6219]
**Rancher Version:** master 10/10

**Steps to Reproduce:**
1.  Create a cattle environment & add host
2.  Create a kubernetes environment
3.  After kubernetes is fully setup, switch back to cattle environment and go to host

**Results:** Host page is empty.  Have to refresh to see them.  Problems on other pages in that environment as well until refresh.  Getting errors in dev tools
![image](https://cloud.githubusercontent.com/assets/11514927/19254077/eff9ea14-8f04-11e6-9a5b-29c8c6ea9348.png)

**Expected:** Should be able to see everything.

**Comment by vincent99** [comment]
Latest was building with a newer beta of Ember than it should.  Pinned to a version we know works now.

**Comment by tfiduccia** [comment]
Version - master 10/10
Verified fixed
