### ISSUE TITLE
ERROR: unable to unmarshal container

### ISSUE THREAD

**Issue by ungarida** [rancher/rancher#622]
I'm running on CoreOS:
-  rancher/agent:v0.6.1 
-  rancher/server:v0.17.1 

I see host datails, CPU and so on. I can use container shell correctly. Strangely in container view there is a never ending "connecting" message. When I call via http the url called by the websocket this is the error message: 

```
ERROR: unable to unmarshal container info for "docker/5cabc6ac98a613a5bc2ce51aa61103e1cdb9d7d10acd60c3a9b7d19b8674fb52" (failed to get container "/docker/5cabc6ac98a613a5bc2ce51aa61103e1cdb9d7d10acd60c3a9b7d19b8674fb52" with error: unknown container "/docker/5cabc6ac98a613a5bc2ce51aa61103e1cdb9d7d10acd60c3a9b7d19b8674fb52"
): invalid character 'i' in literal false (expecting 'l')
```

**Comment by deniseschannon** [comment]
We fixed cadvisor awhile ago, which does the stats and I'm now able to see the stats of the container on a CoreOS host.
