### ISSUE TITLE
Save/Cancel in Edit stack doesn't close Edit modal

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#6221]
**Rancher Version:** Master 10/10

**Steps to Reproduce:**
1.  Create a stack
2.  Edit the stack and click on Cancel/Save

**Results:** Modal does not close

**Expected:** Modal should close

**Comment by vincent99** [comment]
Updated lacsso lib

**Comment by tfiduccia** [comment]
Version - master 10/10
Verified fixed
