### ISSUE TITLE
Services are no longer added to stack immediately

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#6222]
**Rancher Version:** master 10/10

**Steps to Reproduce:**
1.  Create a stack
2.  Add a service

**Results:** Once you add service, the stack is empty for quite a while.  The service eventually shows up.  But it used to show up immediately.

**Expected:**  Show up immediately on create

**Comment by vincent99** [comment]
@ibuildthecloud Still not seeing change events for stacks when the serviceIds array changes

**Comment by tfiduccia** [comment]
version - 1.2.0-pre4-rc5
Verified fixed
