### ISSUE TITLE
Custom certificates are not propagated to rancher-agent hosts

### ISSUE THREAD

**Issue by Chris7** [rancher/rancher#6224]
**Rancher Version:**
1.1.4

**Docker Version:**
1.12.1

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 14.04, Open Nebula 5.02

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA Rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
1. Create a HA setup with a custom certificate (I self signed and provided this cert to the HA setup, I did not use the 'self-signed' option)
2. Create a custom host
3. Spawn the host with:
`sudo docker run -e CATTLE_HOST_LABELS='HOSTSIZE=small' -v /var/lib/docker/ca.crt:/var/lib/rancher/etc/ssl/ca.crt -d --privileged -e CA_FINGERPRINT="1F:2E:4B:81:46:C7:BF:6F:A4:0C:59:B2:78:51:20:30:7D:A5:7E:C5" -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.0.2 url_with_token`

**Results:** 
Agent will get in an endless `INFO: Starting agent for xxx`

**Expected:**
I get a host!

The issue is my custom certificate is not being placed in rancher-agent-state, and the curl request in run_bootstrap is failing because the certificate is missing. You can see here:

https://github.com/rancher/rancher/blob/master/agent/run.sh#L135

that the custom cert is lost at this stage, and because volumes are inherited from rancher-agent-state, my custom certs are not present when rancher-agent is trying to curl the bootstrap script.

**Comment by Chris7** [comment]
Well, if I overwrite `/var/lib/rancher/etc/ssl/ca.crt` on the host machine, it works. This is somewhat inconsistent with the docs which state to use `-v` however in `docker run`.

**Comment by aemneina** [comment]
@Chris7 can you share with me the link to the docs where `-v` is suggested for the certificate?

**Comment by Chris7** [comment]
I misread, I assumed the section here would apply equally to hosts: http://docs.rancher.com/rancher/v1.2/en/installing-rancher/installing-server/basic-ssl-config/

**Comment by aemneina** [comment]
I think this specifically is what you were looking to do: http://docs.rancher.com/rancher/v1.2/en/installing-rancher/installing-server/basic-ssl-config/#adding-hosts
