### ISSUE TITLE
Update display when host labels change

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6225]
Rancher Version: Build from master

Steps to reproduce the problem:
Edit Host and add a label.
When user is brought back to the "Hosts" page , the added labels are not reflected in the host.

After a manual refresh of the page , the labels show up.

**Comment by Toonix** [comment]
v1.1.4 too

**Comment by Toonix** [comment]
I found the problem. The issue is when I use Port 80 instead of 8080. 
( sudo docker run -d --restart=unless-stopped -p 80:8080 rancher/server)

**Comment by janeczku** [comment]
Same issue for stacks: After adding a service it doesn't show in the UI until after a manual refresh.

**Comment by deniseschannon** [comment]
These are the lack of change events that are being sent form the backend.

 https://github.com/rancher/rancher/issues/6129

**Comment by ibuildthecloud** [comment]
@vincent99 Specifically this one I am sending a change event on host `PUT` and I seen in the websocket message the new host label.  I think the UI is not updating even though the data changed.

**Comment by tfiduccia** [comment]
Version - master 10/20
Verified fixed
