### ISSUE TITLE
Read-only API keys

### ISSUE THREAD

**Issue by ebr** [rancher/rancher#6229]
I'm looking to create some services that pull info from Rancher API (like slack bots, backup scripts, etc). But I'd like to apply least-privilege principles to those services. Currently I can create Environment- and Account-scoped keys, but they all have write access. Ideally I'd like read-only Account-scope keys that would have read access to all Environments. Is this possible and/or planned?

**Comment by sangeethah** [comment]
@ebr: You should be able to generate Account-scoped API keys for "Read-only" users. You can do the following:
1. Have authentication enabled for rancher-server instance.
2. Add users to an Environment with Role set to "Read Only"
3. When logged in as this user , you will have the ability to generate "Account API Keys" for this user.
