### ISSUE TITLE
Storage Volume Created by Rancher is not in a good state

### ISSUE THREAD

**Issue by jimengliu** [rancher/rancher#6230]
Steps:
1. add Rancher NFS infra catalog v0.0.3
2. In Rancher UI, choose a host and click Add Container for that host
3. fill out the volume tab with rancher-nfs driver and "test:/test" volume mount details
4. click create

results:
- volume with name "test" shows up in storagepool with State="Requested"
- click on the link of the volume, the resource lacks of "Update" action
- from the plugin logs, I see the volume can’t be updated at create call. Errors:
  ```Bad response statusCode [409]. Status [409 Conflict]. Body: [message=Conflict, baseType=error, code=Conflict] from [http://104.198.247.20:8080/v2-beta/volumes/1v67]"

```
From above steps, I suspect, the Rancher side created a half usable resource at the first stage during Add Container step, but it does not finishing up with mature resource.

Can you check ?

ibuildthecloud [4:41 PM]  
what state was it in?

[4:42]  
was it requested?

jimeng [4:42 PM]  
yes

ibuildthecloud [4:42 PM]  
okay, that's a bug

jimeng [4:42 PM]  
This link does not have Update action, but it still has Create action and click on it, the resource state changes to inactive, then Docker plugin could update it during create call.

```

**Comment by sangeethah** [comment]
Tested with v1.2.0-pre4-rc9 and rancher/storage-nfs:v0.3.0.

"requested" state is not supported for volumes anymore.

When a volume gets created , its state is in "inactive" state now.
Once the volume is attached to container , its state gets to "active" state. 
Volume is actually created in the nfs server.
When the volume is not attached to any container anymore , it gets to "inactive" state.
We have the ability to delete volumes in "inactive" state at which point they get removed from the nfs server.
