### ISSUE TITLE
Rancher scheduler failed to schedule a single container if it requests volume

### ISSUE THREAD

**Issue by jimengliu** [rancher/rancher#6231]
steps:
1. set up a 2 hosts Rancher setup with rancher/server:v1.2.0-pre4-rc2
2. enable infra catalog
3. create Rancher NFS stack
4. schedule a single container with volume(using rancher-nfs driver, "t1:/t1" mount) on one host1, which actually is scheduled. However, do the same thing,  schedule another on another host2, it failed to schedule immediately, with error  “Error (Scheduling failed: valid host(s) [2])"

expect:
we can schedule a single container on any host with volume driver.

After detailed inspect of the failed container, docker did not even start a container at all. So basically Rancher side already failed the scheduling, it seems.

**Comment by deniseschannon** [comment]
how are you scheduling this?

how are you picking which host?

**Comment by sangeethah** [comment]
Blocked on https://github.com/rancher/rancher/issues/6158 .
Assigning it to @LLParse to take a look.

**Comment by nicolinux** [comment]
This happens even if you just want to start a service manually which uses the convoy-nfs driver. So the Convoy NFS stack from infra is broken and can't be used at all right now.
I have reported it here and on the forums but nobody cares :(

rancher/convoy: [#173](https://github.com/rancher/convoy/issues/173)
forums: [post](https://forums.rancher.com/t/convoy-nfs-failed-to-allocate-instance-bad-instance-scheduling-failed/4544)

**Comment by LLParse** [comment]
Cannot reproduce on master, scheduler issue appears to be fixed.
