### ISSUE TITLE
Catalog templates are not exporting the rancher-compose.yml

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#6233]
**Rancher Version:**
Master 10/11

**Steps to Reproduce:**
Launch a catalog entry
Go to view config

**Results:** 
Rancher-compose.yml shows

```
version: '2'
```

**Expected:**
Rancher-compose.yml should export what was in the template.

**Comment by alena1108** [comment]
@deniseschannon does this catalog entry have non-empty rancher compose?

**Comment by deniseschannon** [comment]
@alena1108 Yes, the rancher-compose.yml file has stuff for this catalog entry.

**Comment by alena1108** [comment]
Works for me. Note that we never export Questions section. We only export services/volumes, etc

**Comment by deniseschannon** [comment]
Verified that this is working as expected.
