### ISSUE TITLE
Health Check Interval not being followed

### ISSUE THREAD

**Issue by stepsawayuser** [rancher/rancher#6234]
**Rancher Version:**
1.1.0
**Docker Version:**
1.10.3
**OS and where are the hosts located? (cloud, bare metal, etc):**

The Rancher server is ubuntu 14.04 and the hosts are RancherOS 4.5. They are located on AWS.

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Rancher server is single node with RDS as the database

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Mostly occurs at random, but have only seen the issue when there are more than two or more containers responding to the health check.

**Results:** 

The number of health checks for a service will spontaneously go out of control. Seeing as many as 7K requests per min for an application on two hosts. Moreover, I also consistently see an issue when the number of containers for a service is scaled. For example, I had a service with 15 containers responding to a health check with an interval of 10 seconds showing 10K requests per min. 

**Expected:**

The health check requests should be consistent with what is stated in the interval. For example, if the interval is set to be 10 seconds and there are two containers responding to the health check the total requests per min as it relates to the health check should be 12.

More details of this can be seen on the forum issue: https://forums.rancher.com/t/healthcheck-interval-not-being-followed/4189/7

**Comment by alena1108** [comment]
Should be fixed as we've changed the way we manage our healthcheck service. Now it is going to be launched as a standalone microservice, and we've paid a particular attention to making sure that there are no zombie haproxy processes. I suspect that's what caused healthcheck requests spam. When there are several haproxy processes, the requests are gonna be multiplied. 

https://github.com/rancher/healthcheck/pull/1

We will test it in house once the microservice is shipped

**Comment by iDiogenes** [comment]
This sounds great @alena1108, thank you. It looks like the healthcheck microserver is going to be part of the 1.2.0 release at the end of the month?

**Comment by sangeethah** [comment]
Tested with rancher-server build from master and using rancher/healthcheck:v0.1.0 (from https://github.com/rancher/rancher-catalog , 1.2 branch).

The health check requests sent to the health check enabled instances are consistent (at the expected interval)  even when service scales are changed ( Tried changing the scale from 10 - 20 and then to 25 ).

@stepsawayuser , This fix will be available in rancher-server 1.2 release.

**Comment by iDiogenes** [comment]
Great news. Thank you @sangeethah and @alena1108
