### ISSUE TITLE
How to decleare a container but not to start it?

### ISSUE THREAD

**Issue by pschrammel** [rancher/rancher#6235]
I think this is more a feature request than bug (or perhaps I missed sth. in the docu):

I'd like to declare containers but don't start them. I have two use cases for this:
- using rancher-cron is nice but at deployment all containers are started even those which should be started by rancher-cron
- setup or other maintainance processes which should only be started manually (setup scripts, db cleanups skripts,....)

possible implementation:
instead of start_once: true you could introduce sth like start_strategy: "once" | "never" | "restart" | ....

**Comment by pschrammel** [comment]
BTW: My current workaround is to wrap these entry point into sth like:

`if File('first_run').exists? 
   real_entry_point
else
  touch('first_run')
end
`
but it feels wrong.

**Comment by alena1108** [comment]
@pschrammel have you tried passing "startOnCreate=false" flag to container start? I believe it should just create a container w/o starting it. Let us know if it works for you.

**Comment by pschrammel** [comment]
sorry for late reply. where to put this? same place as batch_size in rancher-compose.yml?

**Comment by alena1108** [comment]
@pschrammel thats a good question, I've tried it using APIs directly. Don't know if rancher-compose supports this flag @joshwget?

**Comment by joshwget** [comment]
Each service in a `rancher-compose.yml` file has a `start_on_create` field. I think this is what you're looking for.

**Comment by deniseschannon** [comment]
You should be able to use `start_on_create: false`, but there is an issue with it: https://github.com/rancher/rancher/issues/7287
