### ISSUE TITLE
Config.User field on docker containers is not set.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6237]
Rancher Version: Build from master - oct 10

Following 2 automated  tests cases report failure:
```
cattlevalidationtest.core.test_container_run_option.test_container_run_with_options_1 (from pytest)

Failing for the past 2 builds (Since Failed#38 )
Took 45 sec.
add description
Error Message

assert '' == 'root'   + root
Stacktrace

client = <cattle.Client object at 0x7f25d81dcfd0>, test_name = 'test-933034'
socat_containers = None

    def test_container_run_with_options_1(client, test_name,
                                          socat_containers):
    
        hosts = client.list_host(kind='docker', removed_null=True)
        assert len(hosts) > 0
        host = hosts[0]
    
        volume_in_host = "/test/container"
        volume_in_container = "/test/vol1"
        docker_vol_value = volume_in_host + ":" + volume_in_container + ":ro"
    
        env_var = {"name1": "value1"}
        host_name = "host1"
        domain_name = "abc.com"
        dns_name = ["test.com"]
        dns_search = ["8.8.8.8"]
        cap_add = ["CHOWN"]
        cap_drop = ["KILL"]
        user = "root"
        restart_policy = {"maximumRetryCount": 5, "name": "on-failure"}
        memory = 16000000
        memory_swap = 16000000
        cpu_set = "0"
        cpu_shares = 400
        command = ["sleep", "450"]
    
        # Create a container to link the data volume of the container for
        # validate dataVolumesFrom
    
        con_vol = client.create_container(name=test_name + "-forvolume",
                                          networkMode=MANAGED_NETWORK,
                                          imageUuid=TEST_IMAGE_UUID,
                                          requestedHostId=host.id
                                          )
        con_vol = client.wait_success(con_vol, 120)
        assert con_vol.state == "running"
    
        docker_vol_from_value = con_vol.externalId
    
        # Create container with different docker options and validate the option
        # testing with docker inspect command
    
        c = client.create_container(name=test_name,
                                    networkMode=MANAGED_NETWORK,
                                    imageUuid=TEST_IMAGE_UUID,
                                    requestedHostId=host.id,
                                    dataVolumes=docker_vol_value,
                                    dataVolumesFrom=con_vol.id,
                                    publishAllPorts=False,
                                    privileged=False,
                                    environment=env_var,
                                    hostname=host_name,
                                    domainName=domain_name,
                                    stdinOpen=False,
                                    tty=False,
                                    dns=dns_name,
                                    dnsSearch=dns_search,
                                    capAdd=cap_add,
                                    capDrop=cap_drop,
                                    user=user,
                                    memory=memory,
                                    memorySwap=memory_swap,
                                    cpuSet=cpu_set,
                                    cpuShares=cpu_shares,
                                    restartPolicy=restart_policy,
                                    command=command
                                    )
    
        c = client.wait_success(c, 120)
        assert c.state == "running"
    
        docker_client = get_docker_client(host)
        inspect = docker_client.inspect_container(c.externalId)
        print inspect
    
        dns_name.append(RANCHER_DNS_SERVER)
        dns_search.append(RANCHER_DNS_SEARCH)
    
        assert inspect["HostConfig"]["Binds"] == [docker_vol_value]
        assert inspect["HostConfig"]["VolumesFrom"] == [docker_vol_from_value]
        assert inspect["HostConfig"]["PublishAllPorts"] is False
        assert inspect["HostConfig"]["Privileged"] is False
        assert inspect["Config"]["OpenStdin"] is False
        assert inspect["Config"]["Tty"] is False
        assert inspect["HostConfig"]["Dns"] == dns_name
        assert inspect["HostConfig"]["DnsSearch"] == dns_search
        assert inspect["Config"]["Hostname"] == host_name
        assert inspect["Config"]["Domainname"] == domain_name
>       assert inspect["Config"]["User"] == user
E       assert '' == 'root'
E         + root

tests/v2_validation/cattlevalidationtest/core/test_container_run_option.py:96: AssertionError
```
Error Message

assert '' == 'root'   + root
Stacktrace

admin_client = <cattle.Client object at 0x7f25ccc48490>
client = <cattle.Client object at 0x7f25ccd57590>, socat_containers = None

    def test_services_docker_options(admin_client, client, socat_containers):
    
        hosts = client.list_host(kind='docker', removed_null=True, state="active")
    
        con_host = hosts[0]
    
        vol_container = client.create_container(imageUuid=TEST_IMAGE_UUID,
                                                name=random_str(),
                                                requestedHostId=con_host.id
                                                )
    
        vol_container = client.wait_success(vol_container)
    
        volume_in_host = "/test/container"
        volume_in_container = "/test/vol1"
        docker_vol_value = volume_in_host + ":" + volume_in_container + ":ro"
    
        cap_add = ["CHOWN"]
        cap_drop = ["KILL"]
        restart_policy = {"maximumRetryCount": 10, "name": "on-failure"}
        dns_search = ['1.2.3.4']
        dns_name = ['1.2.3.4']
        domain_name = "rancher.io"
        host_name = "test"
        user = "root"
        command = ["sleep", "9000"]
        env_var = {"TEST_FILE": "/etc/testpath.conf"}
        memory = 8000000
        cpu_set = "0"
        cpu_shares = 400
    
        launch_config = {"imageUuid": TEST_SERVICE_OPT_IMAGE_UUID,
                         "command": command,
                         "dataVolumes": [docker_vol_value],
                         "dataVolumesFrom": [vol_container.id],
                         "environment": env_var,
                         "capAdd": cap_add,
                         "capDrop": cap_drop,
                         "dnsSearch": dns_search,
                         "dns": dns_name,
                         "privileged": True,
                         "domainName": domain_name,
                         "stdinOpen": True,
                         "tty": True,
                         "memory": memory,
                         "cpuSet": cpu_set,
                         "cpuShares": cpu_shares,
                         "restartPolicy": restart_policy,
                         "directory": "/",
                         "hostname": host_name,
                         "user": user,
                         "requestedHostId": con_host.id
                         }
    
        scale = 2
    
        service, env = create_env_and_svc(client, launch_config,
                                          scale)
    
        env = env.activateservices()
        service = client.wait_success(service, 300)
        assert service.state == "active"
    
        check_container_in_service(admin_client, service)
    
        container_list = get_service_container_list(admin_client, service)
    
        dns_name.append(RANCHER_DNS_SERVER)
        dns_search.append(env.name+"."+RANCHER_DNS_SEARCH)
        dns_search.append(service.name+"."+env.name+"."+RANCHER_DNS_SEARCH)
        dns_search.append(RANCHER_DNS_SEARCH)
    
        for c in container_list:
            docker_client = get_docker_client(c.hosts[0])
            inspect = docker_client.inspect_container(c.externalId)
    
            assert inspect["HostConfig"]["Binds"] == [docker_vol_value]
            assert inspect["HostConfig"]["VolumesFrom"] == \
                [vol_container.externalId]
            assert inspect["HostConfig"]["PublishAllPorts"] is False
            assert inspect["HostConfig"]["Privileged"] is True
            assert inspect["Config"]["OpenStdin"] is True
            assert inspect["Config"]["Tty"] is True
            assert inspect["HostConfig"]["Dns"] == dns_name
            assert inspect["HostConfig"]["DnsSearch"] == dns_search
            assert inspect["Config"]["Hostname"] == host_name
            assert inspect["Config"]["Domainname"] == domain_name
>           assert inspect["Config"]["User"] == user
E           assert '' == 'root'
E             + root

tests/v2_validation/cattlevalidationtest/core/test_services.py:163: AssertionError

```

**Comment by StrongMonkey** [comment]
https://github.com/rancher/agent/pull/57

**Comment by sangeethah** [comment]
Waiting on a new release of agent to test this one.

**Comment by sangeethah** [comment]
Tested with latest build from master.

This test case now succeeds.
