### ISSUE TITLE
No scroll bar in "Edit Load Balancer" page resulting  in "Save" button not shown to the user.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6240]
Rancher Version: Build from master

<img width="1068" alt="screen shot 2016-10-11 at 11 50 52 pm" src="https://cloud.githubusercontent.com/assets/4266958/19300190/c63117a2-900d-11e6-8a1d-a1b01f6ff72d.png">

**Comment by tfiduccia** [comment]
Version -  master 10/19
If a modal is bigger then the background page, it still doesn't have a scrollbar to get to bottom.  Easiest way to see this is to have a single stack with 1 service and lb on an environment and edit the lb service.

**Comment by tfiduccia** [comment]
Version - master 10/20
Verified fixed
