### ISSUE TITLE
Removing Environment does not remove IP 10.42.X.X

### ISSUE THREAD

**Issue by caio2k** [rancher/rancher#6242]
**Rancher Version:** 1.1.4

**Docker Version:** 1.12.2 build bb80604

**OS and where are the hosts located?** Debian Jessie / bare metal

**Setup Details:** single node rancher

**Environment Type:** Cattle

**Steps to Reproduce:** 
1. Add a service from catalog
2. Delete it
3. Delete environment

**Results:** 
IP 10.42.0.1 still on docker0 interface

```
3: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
      link/ether 02:42:98:5f:a5:9f brd ff:ff:ff:ff:ff:ff
      inet 172.17.42.1/16 scope global docker0
         valid_lft forever preferred_lft forever
      inet 10.42.0.1/16 scope global docker0
         valid_lft forever preferred_lft forever
      inet6 fe80::42:98ff:fe5f:a59f/64 scope link 
         valid_lft forever preferred_lft forever
```

**Expected:** 
IP 10.42.0.1 removed from docker0 interface as it is not used anymore (and conflicts with my external network)

**Comment by aemneina** [comment]
as a workaround you could remove the interface `ip link del docker0` usually does the trick. Make sure to restart the docker daemon to recreate docker0.

**Comment by caio2k** [comment]
As a workaround I removed only the IP 10.42.0.1 from the interface. Then you shouldn't restart anything :)
`ip addr del 10.42.0.1 dev docker0`

**Comment by superseb** [comment]
I don't really see a way to make this cleanup work, when we delete an environment (and the added hosts) they either get removed (cloud provided) or nothing is done. Best way to handle this is to mention it in the docs under "Removing hosts"? What do you think @aemneina ?

**Comment by aemneina** [comment]
@superseb Sounds good, we can document this as a step under cleaning up hosts

**Comment by superseb** [comment]
https://github.com/rancher/rancher.github.io/pull/811
