### ISSUE TITLE
[agent-instance]Launch stack: Client.Timeout exceeded while awaiting headers

### ISSUE THREAD

**Issue by albenshao** [rancher/rancher#6243]
**Rancher Version:**
v1.1.4

**Docker Version:**
1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 14.04.4 LTS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA (3 nodes), external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Setup 3 Nodes HA, and then launch stack

**Results:** 
FATA[1181] Get https://myserver.domain.name/v1/services/1s76: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

**Expected:**
stack can be launched sucessfully.

**My docker-compose.yaml**
ECRCredentials:
  image: objectpartners/rancher-ecr-credentials

**Rancher Compose output**
DEBU[0000] Environment Context from file : map[]  
DEBU[0000] Opening compose files: docker-compose.yaml  
DEBU[0000] Opening rancher-compose file: rancher-compose.yaml 
DEBU[0000] [0/1] [zookeeper]: Adding  
DEBU[0002] Looking for stack refresh-ecr-token2  
INFO[0004] Creating stack refresh-ecr-token2  
DEBU[0005] Launching action for zookeeper  
DEBU[0005] Project [refresh-ecr-token2]: Creating project  
DEBU[0005] [0/1] [zookeeper]: Creating  
DEBU[0005] Finding service zookeeper  
INFO[0005] Creating service zookeeper  
DEBU[0005] Creating service zookeeper with hash: digest.ServiceHash{Service:"47631b46ae720d3d7abf9e02a9cbb4d4403aaa1f", LaunchConfig:"8c6eaaa0009af0f6049b9473da0ee60c466dfb16", SecondaryLaunchConfigs:map[string]string(nil)} 
DEBU[0006] Finding service zookeeper  
DEBU[0007] Found service zookeeper  
DEBU[0008] [0/1] [zookeeper]: Created  
DEBU[0008] Project [refresh-ecr-token2]: Project created  
DEBU[0008] Launching action for zookeeper  
DEBU[0008] Project [refresh-ecr-token2]: Starting project  
INFO[0008] [0/1] [zookeeper]: Starting  
DEBU[0008] Finding service zookeeper  
DEBU[0009] Found service zookeeper  
DEBU[0009] Comparing hashes for zookeeper: old: digest.ServiceHash{Service:"47631b46ae720d3d7abf9e02a9cbb4d4403aaa1f", LaunchConfig:"8c6eaaa0009af0f6049b9473da0ee60c466dfb16", SecondaryLaunchConfigs:map[string]string{}} new: digest.ServiceHash{Service:"47631b46ae720d3d7abf9e02a9cbb4d4403aaa1f", LaunchConfig:"8c6eaaa0009af0f6049b9473da0ee60c466dfb16", SecondaryLaunchConfigs:map[string]string(nil)} 
ERRO[1181] Failed Starting zookeeper : Get https://myserver.domain.name/v1/services/1s76: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers) 
ERRO[1181] Failed to start: zookeeper : Get https://myserver.domain.name/v1/services/1s76: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers) 
FATA[1181] Get https://myserver.domain.name/v1/services/1s76: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

**Comment by albenshao** [comment]
I found if I go to the rancher host, and restart the container "agent-instance" (the container using image rancher/agent-instance:v0.8.3), all the "red" stack/service can be "active".
Then, new stack will still be red until restart the agent-instance next time.

Can anyone help? What happened?

**Comment by guzmo** [comment]
Have the same problem, recently it's very common it fails to run rancher-compose. The other times it works so its nothing wrong with the docker-compose/rancher-compose files.

**Comment by aemneina** [comment]
sounds like the rancher-compose-executor service, or the web-socket-proxy service might have suffered an outage. Restarting those should resolve your issue. Please reopen if youre still facing this.

**Comment by guzmo** [comment]
But it does restart by itself? Cant continue to restart it? That is not an solution

**Comment by aemneina** [comment]
In 1.2.0 they should be more robust.
