### ISSUE TITLE
HAproxy count out of control on rancher server

### ISSUE THREAD

**Issue by jclark360** [rancher/rancher#6245]
**Rancher Version:**
1.1.4
**Docker Version:**
1.11.2
**OS and where are the hosts located? (cloud, bare metal, etc):**
aws ubuntu 14.04LTS
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher, external db
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
cattle
**Steps to Reproduce:**
we have a single stack running and over time one of the rancher servers seems to add more and more haproxy processes until the box becomes unresponsive.

**Results:** 
haproxy process count ends up in the hundreds

**Expected:**
That haproxy process count is stable?

**Comment by jclark360** [comment]
landsca+  6827  0.0  0.0  35260   892 ?        Ss   15:05   0:00 /usr/sbin/haproxy -f /etc/healthcheck/healthcheck.cfg -D -p /var/run/haproxy.pid
landsca+ 10582  0.0  0.0  35260   900 ?        Ss   15:05   0:00 haproxy -p /var/run/haproxy.pid -f /etc/healthcheck/healthcheck.cfg -sf
landsca+ 11551  0.0  0.0  35260  1056 ?        Ss   15:05   0:00 haproxy -p /var/run/haproxy.pid -f /etc/healthcheck/healthcheck.cfg -sf
landsca+ 12636  0.0  0.0  35260  1056 ?        Ss   15:06   0:00 /usr/sbin/haproxy -f /etc/healthcheck/healthcheck.cfg -D -p /var/run/haproxy.pid
landsca+ 12911  0.0  0.0  35260  1056 ?        Ss   15:06   0:00 /usr/sbin/haproxy -f /etc/healthcheck/healthcheck.cfg -D -p /var/run/haproxy.pid
landsca+ 12994  0.0  0.0  35260  1060 ?        Ss   15:07   0:00 /usr/sbin/haproxy -f /etc/healthcheck/healthcheck.cfg -D -p /var/run/haproxy.pid
landsca+ 13078  0.0  0.0  35260  1056 ?        Ss   15:07   0:00 /usr/sbin/haproxy -f /etc/healthcheck/healthcheck.cfg -D -p /var/run/haproxy.pid
landsca+ 13134  0.0  0.0  35260  1056 ?        Ss   15:08   0:00 /usr/sbin/haproxy -f /etc/healthcheck/healthcheck.cfg -D -p /var/run/haproxy.pid
landsca+ 13207  0.0  0.0  35260  1056 ?        Ss   15:08   0:00 /usr/sbin/haproxy -f /etc/healthcheck/healthcheck.cfg -D -p /var/run/haproxy.pid
landsca+ 13236  0.0  0.0  35260  1056 ?        Ss   15:09   0:00 /usr/sbin/haproxy -f /etc/healthcheck/healthcheck.cfg -D -p /var/run/haproxy.pid
landsca+ 13467  0.0  0.0  35260  1056 ?        Ss   15:10   0:00 /usr/sbin/haproxy -f /etc/healthcheck/healthcheck.cfg -D -p /var/run/haproxy.pid

**Comment by jclark360** [comment]
The count seems to grow every minute or so.

**Comment by jclark360** [comment]
Only other thing I see that could be related is a bunch of volumes spawning errors on volume.activate in the processes area of the ui.

**Comment by aemneina** [comment]
hey @jclark360 did you manage to get to the bottom of this? I'd imagine the containers you were trying to loadbalance couldnt stay in a healthy state for long, spawning more containers... which in turn caused haproxy config to be updated frequently.

**Comment by aemneina** [comment]
I'll close this out.... feel free to reopen if youre still hitting this issue. If you solved it, it would be great to hear how.
