### ISSUE TITLE
How to set volume properly? 

### ISSUE THREAD

**Issue by andreinechaev** [rancher/rancher#6246]
**Rancher Version: 1.1.4**

**Docker Version: 1.12.1**

**OS: Ubuntu 14, AWS**

**Setup Details: single node Rancher**

**Environment Type: Cattle, Kafka, Zookeeper**

**Steps to Reproduce: Set up a volume for containers. Tried to add volume in configurations like /data/kafka:/otp/kafka/logs** but got infinite initialization. So, both containers (Kafka and Zookeeper) are in initialization stage for an hour... Am I doing something wrong?

**Comment by aemneina** [comment]
@andreinechaev did /data/kafka reside on the host? Can you supply the container/docker daemon logs for your attempt?

**Comment by aemneina** [comment]
I'll close this, if you're still hitting this issue could you please share your docker/rancher-compose.yml files?
