### ISSUE TITLE
Problem binding specific IP per container.

### ISSUE THREAD

**Issue by danipolo** [rancher/rancher#6247]
**Rancher Version:**
1.1.4
**Docker Version:**
Docker version 1.11.2, build b9f10c9
**OS and where are the hosts located? (cloud, bare metal, etc):**
Bare Metal, Ubuntu 16
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node, fresh install.
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
For example, specify 111.222.333.444:80 in a service.
**Results:** 
When you press OK in the UI, it just save 111 (not the full IP and port). Of course, I can't specify the IP and it doesn't listen.

**Expected:**
Multiple IP's working (1 external IP per container).

**Comment by aemneina** [comment]
part of the issue i believe is that you need to specify <ip_address>:<external_port>:<container_port> but I dont believe ip address can be the host address directly, or anything outside the 10.42.0.0/16 address space, unless your using host networking. Your best bet is to bind ports, use host labels so it lands on your desired host... then you'll be able to hit host_ip:port and access your service.

**Comment by aemneina** [comment]
might also be related to [this issue](https://github.com/rancher/rancher/issues/5064#issuecomment-253654669) closing in favor of that.
