### ISSUE TITLE
Error message seen when adding members to an environment.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6248]
Rancher server version - Build from master

Steps to reproduce the problem:
In local auth enabled setup , try to add a user to an existing environment.

Following error is seen:

<img width="1237" alt="screen shot 2016-10-12 at 11 33 35 am" src="https://cloud.githubusercontent.com/assets/4266958/19323003/fe479a14-906f-11e6-994e-23b76e8bcaff.png">

**Comment by deniseschannon** [comment]
@vincent99 @westlywright Is this UI?

**Comment by vincent99** [comment]
Yes, it looks like a remnant or bad merge from an earlier version of infra catalog where you created the stacks on this screen

**Comment by galal-hussein** [comment]
The error doesn't appear anymore, tested on master build (20 Oct)
