### ISSUE TITLE
Error message is misleading when allocation fails due to not being to allocate cpu/memory.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6249]
Rancher Version: Build from master

Steps to reproduce the problem:
Deploy Rancher Scheduler.

Scenario 1:
Start a service with port and memoryReservation/milliCpuReservation when there is not enough memory/cpu.
Containers fails to get created with error message - ```Failed to allocate instance [container:1i722]: Bad instance [container:1i722] in state [error]: Scheduling failed: host needs ports 8092/tcp available)``` even though there are hosts with port 8092 available.

Scenario 2:
Start a service with host label affinity and memoryReservation/milliCpuReservation when there is not enough memory/cpu and there are hosts with the specified labels.

Containers fails to get created with error message - ```Activating (Failed to allocate instance [container:1i456]: Bad instance [container:1i456] in state [error]: Scheduling failed: needs host with label test1: value1```

We should be able to provide error message that indicate that we were not able to allocate cpu/memory instead.

**Comment by cjellick** [comment]
Fixed, I think. When I create a service with the following launch config:
```
{
  "imageUuid": <img>,
   "ports": ["8080:8080"],
   "milliCpuReservation": 2000
}
```
and I don't have any hosts with 200 cpu available, I get the following error message:
```
Scheduling failed: No healthy hosts meet the resource constraints: [Resource: cpuReservation, amount: 2000]
```

That said, if you have a combination of issues where you _do_ have a host with enough cpu but that host doesn't have specified port available, then the message reported will be "host needs port..."

**Comment by sangeethah** [comment]
Tested with Rancher server build from master.
Infra catalog - https://github.com/rancher/infra-catalog.git from branch 1.2

Order in which allocator works is - external scheduler. then ports, labels .

1. When there are no hosts with enough resources but with required host labels  , then we see the "No healthy hosts meet the resource constraints" error message
2. When there are  hosts with enough resources but no required host labels  , then we see  error message indicating the unavailability of host with required labels.
3. When there are no hosts with enough resources but with required host ports , then we see the "No healthy hosts meet the resource constraints" error message
4. When there are  hosts with enough resources but no required host ports, then we see  error message indicating the unavailability of host ports.
