### ISSUE TITLE
Not able to clone services with sidekick

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6251]
Rancher Version: Build from master

When cloning a service with sidekick, user is directed to "/fail" page with following error message:

```
e.serializeForNew is not a function

Reload to try again or log out
```

**Comment by tfiduccia** [comment]
This was the same issue as #6207 and has been fixed.  You can recheck if you like but I verified it through the UI.
Version - 1.2.0-pre4-rc4
Verified fixed

**Comment by sangeethah** [comment]
This issue is not seen anymore when testing with Version - 1.2.0-pre4-rc3.
