### ISSUE TITLE
Validate host stats and container stats

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6254]
Validate host stats and container stats works for the following supported os/docker version combinations:

1.10,1.11and 1.12 docker versions on Ubuntu 14.04/Ubuntu 16.04/rhel 7.2/centos 7.2/ros 0.6.1

**Comment by soumyalj** [comment]
The following have been completed:
1. Centos 7.2 -> Docker 1.10.3, Docker 1.12.2
2. Ubuntu 16.04 -> Docker 1.12.2
