### ISSUE TITLE
Is it possible to run rancher-compose [start just one service] from the yml file?

### ISSUE THREAD

**Issue by juliangamble** [rancher/rancher#6257]
Rancher Version: 
1.02
Docker Version:
1.10.3
OS and where are the hosts located? (cloud, bare metal, etc):
Redhat - cloud
Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)
single-node-rancher
Environment Type: (Cattle/Kubernetes/Swarm/Mesos)
Cattle

**Steps to Reproduce:**
docker-compose start <servicename>

**Results:** 
Everything in the yml file started. 

**Expected:**
Just the service given to the parameter started.

**Comment by deniseschannon** [comment]
Yes, you would do `rancher-compose start <servicename>`

For example, if you have a docker-compose.yml that looks like this:

```
test1:
    image: nginx
test2:
    image: nginx
test3:
    image: nginx
```

You could run `rancher-compose start test2` to only start the `test2` service.

**Comment by juliangamble** [comment]
Your doco doesn't say this. It says you can only run all. Can you please update the documentation?

**Comment by deniseschannon** [comment]
Where in the documentation does it say that we can only start all?

As rancher compose is based on docker compose, this is standard practice where if you don't specify a service, then it will do all the services in the yaml, but you can always specify specific services.

**Comment by juliangamble** [comment]
If you look at the doco here - there is an absence of service specific starts - there is only language that implies "all services" https://github.com/rancher/rancher-compose

**Comment by deniseschannon** [comment]
@juliangamble Are you talking about the usage section, which is just an export of `rancher-compose --help` ? 

The `up` says all services, but the help for `start` matches how it is shown in docker-compose. Both show `Start services`.
