### ISSUE TITLE
Processes: physicalhost.error CANCELED frequently appearing

### ISSUE THREAD

**Issue by thekiwi** [rancher/rancher#6258]
**Rancher Version:**
1.1.4

**Docker Version:**
1.9.1

**OS and where are the hosts located? (cloud, bare metal, etc):**
Amazon Linux AMI 2015.09, AWS EC2

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher, external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Unsure - deleting hosts in an older Rancher server (1.0.1), and upgrading to newer Rancher server (1.1.4)?

**Results:** 
Frequent 'CANCELED' messages appearing in Processes list

**Expected:**
No 'CANCELED' messages appearing in Processes list

---

We appear to be having an issue in the latest stable Rancher where it is attempting to update older deleted hosts (and of course, failing). 

Here's the processes list, which is updated every few seconds with new entries:
![chrome_2016-10-13_11-34-58](https://cloud.githubusercontent.com/assets/710204/19346320/a6836c06-913a-11e6-89e0-5f4e1e528ee3.png)

and here's the information on one of the process instances:
![chrome_2016-10-13_11-46-54](https://cloud.githubusercontent.com/assets/710204/19346356/cf6ccf86-913a-11e6-8946-c7b963ab88d8.png)

Any ideas on how we can resolve this? We're worried that as we delete more hosts, this will have a more significant impact on the performance of Rancher Server. 

Thanks!

**Comment by aemneina** [comment]
hey @thekiwi you should be able to query /v1/hosts and determine the hosts that have long since disappeared from your deployment. You should then be able to remove those hosts. Let us know if that resolves your issue.

**Comment by thekiwi** [comment]
Thanks @aemneina - unfortunately the host in question doesn't appear in the /v1/hosts endpoint, only in the /v1/physicalHosts one. 

Also, there has been a slight change in the above - it only seems to be occurring to a single physicalHost now, it appears as if the others have been cleaned up. 

How can I remove a host from the physicalHosts collection via the API? Is that the correct thing to do in this case?

**Comment by thekiwi** [comment]
Also, this is what appears in our "Running Processes" tab:
![chrome_2016-11-11_08-26-03](https://cloud.githubusercontent.com/assets/710204/20208821/8fbfd184-a7e8-11e6-900e-50b35cbb85c4.png)

As you can see, the `physicalhost.remove` process has been running on the same problematic host (1ph14) for apparently 6 months.

**Comment by aemneina** [comment]
is there anything returned from the following sql query?:

`select resource_id, start_time, exit_reason from process_instance where process_name='agent.reconnect' and end_time is null and resource_id in (select id from agent where id not in (select agent_id from host) and removed is null and state='reconnecting');`

**Comment by thekiwi** [comment]
Apologies for the slow reply. For that query, I get `Empty set (0.00sec)`.

I also get an empty set from `select id from agent where state='reconnecting';`

**Comment by vincent99** [comment]
Please comment or reopen if this is still relevant to modern versions.  There have been a lot of bugs with stuck processes fixed since 1.1.x.
