### ISSUE TITLE
how to export the logs of rancher server

### ISSUE THREAD

**Issue by clouderding** [rancher/rancher#6259]
Usually, we launch the rancher server with the command like `docker run -d --restart=unless-stopped -p 8080:8080 rancher/server`  and get the server log with the command `docker logs XXXX`, but how can i export the server logs in host machine? Because the logs is very big and it is very difficult to  locate problems. 
thank you.

**Comment by aemneina** [comment]
There are a lot of strategies out there to manage, centralize logging. I think you'd probably benefit by using --tail=<n_lines> when looking at docker logs. Please refer to the man pages for that.
