### ISSUE TITLE
Application of sidekicks in rancher

### ISSUE THREAD

**Issue by pruthviraj08** [rancher/rancher#6260]
I am currenlty using rancher for the cloud deployments. I have service A, service B and service C. 'A' should communicate with B on a specific port, and they should act like a single service and "B" should load the configuration file(volumes from different image) from "C". According to my understanding of side kicks. "A" should be my primary service and "B" should be the sidekick. Is there any possible way to accommodate "C" as a sidekick or as a different container.

Thanks in advance!!!

**Comment by aemneina** [comment]
Sounds like A and B can reference each other by their 'names', dns should resolve them, as they'll be in the same stack/environment. You'll want B to use volumes from C. A good example of side-loading config could be found [here](https://github.com/rancher/community-catalog/blob/master/templates/MongoDB/1/docker-compose.yml)... mongo-base provides the config for mongo-cluster.

**Comment by pruthviraj08** [comment]
Thanks!!!! 
It actually works.

**Comment by aemneina** [comment]
excellent, closing issue.
