### ISSUE TITLE
Admin tab is responding with 500 error

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#6261]
**Rancher Version:**
master image
**Docker Version:**
1.12.1
**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04 cloud
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes
**Steps to Reproduce:**
Install Rancher server from master image and then click on any item from the Admin tab
**Results:** 
the url responds with 500 Error

**Comment by prachidamle** [comment]
@ibuildthecloud this is because rancher-auth-service is OFF by default.
Admin tab UI tries to load /v1-auth/schemas and gets a 500 since no service is listening for /v1-auth/

We should have auth service on by default.

**Comment by prachidamle** [comment]
Another option is UI not loading /v1-auth/schemas unless "Admin tab -> Access Control -> Github/Saml" is loaded

Currently UI loads the schemas way earlier(at Admin tab) than it is actually used

**Comment by sangeethah** [comment]
This issue is not seen anymore with v1.2.0-pre4-rc3
