### ISSUE TITLE
Rancher server hangs after deploying k8s stack

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#6262]
**Rancher Version:**
master image
**Docker Version:**
1.12
**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes
**Steps to Reproduce:**
Install rancher server image and then deploy k8s 1.4 from the infra catalog
**Results:** 
the url is only showing the wait logo and hanging.

**Comment by tfiduccia** [comment]
Galal can you retest this with newest version

**Comment by galal-hussein** [comment]
I tested it again, and this problem doesn't happen anymore
