### ISSUE TITLE
convoy-nfs leaves behind 'storage' pools after its stack is deleted 

### ISSUE THREAD

**Issue by disappearinjon** [rancher/rancher#6263]
To repro:
- Create a new convoy-nfs stack from the catalog
- Delete the stack
- Navigate to Infrastructure -> Storage. Observe pool remains behind.

I have found no obvious way to delete the pool via the UI.

(Note that I'm running into problems deploying convoy-nfs, so I have repeated this multiple times with the same result--but my containers have never fully & correctly deployed first.)

---

| Useful | Info |
| :-- | :-- |
| Versions | Rancher `v1.1.2` Cattle: `v0.165.8` UI: `v1.1.12` |
| Access | `openldap` |
| Orchestration | `Cattle` |
| Route | `storagepools.pools` |

**Comment by fjoesne** [comment]
any workaround possible for this issue? I'm guessing it has something to do with stale entries in the rancher-db

**Comment by michaellopez** [comment]
@fjoesne After having removed all services, stacks and volumes related to `convoy-nfs` in the UI, I did a few daring raw SQL statements with the mysql CLI against the database. Note that I tried this on a non-production setup I had access to. So YMMV. Use at your own risk. Backup your database before doing this. <insert all other disclaimers about losing data here>, etc. 

The following SQL queries removed `convoy-nfs` from the UI in my installation, I have no clue what other (good or **bad**) effects it might have had on the system. I'd wait for an official fix if you can stand seeing `convoy-nfs` in the UI until then. If not, I leave this here for discussion...again; USE AT YOUR OWN RISK.

```sql
DELETE FROM volume_storage_pool_map WHERE storage_pool_id IN (SELECT id FROM storage_pool WHERE name="convoy-nfs");
DELETE FROM storage_pool_host_map WHERE storage_pool_id IN (SELECT id FROM storage_pool WHERE name="convoy-nfs");
DELETE FROM storage_pool WHERE name="convoy-nfs";
```

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
