### ISSUE TITLE
No way to change a Kubernetes environment to cattle.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6265]
Rancher Version: Build from master

Once  K8s system stack is deployed from Infra catalog , I see orchestration set to "kubernetes".
How can I change the orchestration back to "cattle".
Is it  just by deleting the K8s system stack ? If yes , I dont see the system stacks being listed anywhere in the UI for users to be able to delete this stack.

**Comment by alena1108** [comment]
@sangeethah it is under stacks->infrastructure

**Comment by alena1108** [comment]
and yes, the way to get back to cattle - delete k8s stack

**Comment by sangeethah** [comment]
@alena1108 , Thanks .I do see stacks->infrastructure where I can delete the k8s system stack to make it cattle environment.
