### ISSUE TITLE
Host provisioning under openstack failing (certificates)

### ISSUE THREAD

**Issue by asanami** [rancher/rancher#6269]
**Rancher Version:**  1.14

**Docker Version:**

**OS and where are the hosts located? (cloud, bare metal, etc):** Openstack

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**  single node rancher , internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**  Kubernetes

**Steps to Reproduce:**
1. Install rancher server under docker
2. Install hosts through openstack driver
3. I've disable TLS when provisioning new host(s)

**Results:** 

It provisions the VM's correctly under openstack, but fails to correctly configure docker-machine with the follow error messages:

```
time="2016-10-14T14:22:06Z" level=info msg="stdout: Checking connection to Docker..." resourceId: =1ph2 
time="2016-10-14T14:22:10Z" level=info msg="stdout: The default lines below are for a sh/bash shell, you can specify the shell you're using, with the --shell flag." resourceId: =1ph2 
time="2016-10-14T14:22:10Z" level=info msg="stdout: " resourceId: =1ph2 
time="2016-10-14T14:22:10Z" level=info msg="stderr: Error creating machine: Error checking the host: Error checking and/or regenerating the certs: There was an error validating certificates for host \"X.X.X.X:Y\": dial tcp X.X.X.X:Y: i/o timeout" resourceId=1ph2 
time="2016-10-14T14:22:10Z" level=info msg="stderr: You can attempt to regenerate them using 'docker-machine regenerate-certs [name]'." resourceId=1ph2 
time="2016-10-14T14:22:10Z" level=info msg="starting cleanup..." machine name=ads 
time="2016-10-14T14:22:10Z" level=info msg="stderr: Be advised that this will trigger a Docker daemon restart which will stop running containers." resourceId=1ph2 
time="2016-10-14T14:22:11Z" level=info msg="cleanup successful" machine name=ads 
time="2016-10-14T14:22:11Z" level=error msg="Error processing event" err="Error checking the host: Error checking and/or regenerating the certs: There was an error validating certificates for host \"X.X.X.X:Y\": dial tcp X.X.X.X:Y: i/o timeout" eventId=43c0ddd9-4586-4884-a5d0-f5a2aa73abbb eventName="physicalhost.create;handler=goMachineService" resourceId=1ph2 
```

**Expected:**

Node is set up correctly under an openstack cloud.

**Comment by deniseschannon** [comment]
Are you able to take the same command that is in the Rancher server logs (typically starts with `cmd slice: create` and use that command with Docker Machine to correctly provision a host. 

The error looks more like a Docker Machine error and not a Rancher one. We are just running Docker Machine and once the host is up and running we will SSH in to install the Rancher agent.

**Comment by asanami** [comment]
Yes, it does look like a docker-[machine] issue, but I'm unable to see what command it is running.  I'm running the rancher server under docker in interactive mode, but I do not see any 'cmd slice' commands with anything docker related.  Do I need to increase verbosity?   The only cmd slice related thing I see is:

```
Cmd slice: [create -d openstack - ....
```

After it has run, it also cleans down the VM so from that perspective I'm unable to jump on to the VM and reproduce.

**Comment by deniseschannon** [comment]
That is the `cmd slice` that I was referring to.

If you try `docker-machine create -d openstack ....` and take everything up the next bracket. Try launching your VM using docker machine to see if it works. If it also fails, then this is a Docker Machine bug and not a Rancher one in terms of provisioning your host.

**Comment by asanami** [comment]
Why is rancher using docker-machine to set slaves in vm's under openstack?  My target vm is ubuntu 14.04.

**Comment by vincent99** [comment]
Before you edited out the IP (which was non-routable anyway) and port  the error said timeout connecting to the docker socket port, which probably means you're missing opening the port in the security group configured.

You asked for a VM and docker-machine is what we use to create them and install docker.  If you want to create the VM yourself or already have them, use the custom add host command to register them to Rancher.

**Comment by aemneina** [comment]
@asanami did you manage to resolve this? Please reopen if you still face the issue.
