### ISSUE TITLE
Github organization authorization access failed  

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#6272]
**Rancher Version:**
master image
**Docker Version:**
1.12.2
**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
- Enable github authentication
- follow instructions to add client id and secret
- select "Restrict access to only Authorized Users and Organizations"
- add organization with one or more member
- save and try to authenticate and login with any user in this organization.

**Results:** 
Can't login with this user, and it is responding with "Unauthorized"

**Comment by prachidamle** [comment]
This is what is causing the login failure:

When a new org is created on Github, by default the access to this org is restricted. So any member's application that tries to list that org will not find it under that member account.

So for the newly created org, the owner of the org should set the Policy to No restrictions:
1. Login on GIthub as the owner of that org
2. Go to the Organization Settings for that org
3. Go to: 
https://github.com/organizations/<your org name>/settings/oauth_application_policy
4. Change the "Third-party application access policy" to No restrictions
5. Make sure it shows: 
Policy: No restrictions 
6. Now this org should get listed for all members 
7. Try login to Rancher as a member of this org an dit should work (assumed here that this org is given access in Rancher)

**Comment by prachidamle** [comment]
@galal-hussein @sangeethah let us document the above "about new org creation" in the Github Test plan.

**Comment by galal-hussein** [comment]
Github test plan is updated with those steps .. and the steps tested and worked, thanks.
