### ISSUE TITLE
Kubectl logs/exec failed on k8s 1.4

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#6278]
**Rancher Version:**
master image
**Docker Version:**
1.12.2
**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes 1.4
**Steps to Reproduce:**
- Install kubernetes 1.4 from infra catalog
- run nginx pod:

```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
```
- try to run kubectl logs/exec on the pod
**Results:** 
```
$ kubectl logs nginx     
Error from server: Get https://hussein-10acre-3:10250/containerLogs/default/nginx/nginx: dial tcp: lookup hussein-10acre-3 on 169.254.169.250:53: no such host

$ kubectl exec nginx bash
Error from server: dial tcp: lookup hussein-10acre-3 on 169.254.169.250:53: no such host
```
**Expected:**
To see logs for the nginx container and to exec bash into the container.

**Comment by wlan0** [comment]
This is because hosts are registered by hostname and not fqdn. 

When kubelet starts, it tries to register itself with the fqdn, and if the fqdn is not found, then hostname is used.

In this case, fqdn cannot be found. After investigating, I found that /etc/resolv.conf somehow loses the rancher serach domain. Maybe a docker 1.12 bug/GCE bug. Investigating further...

**Comment by wlan0** [comment]
@StrongMonkey

**Comment by galal-hussein** [comment]
Tested on Rancher master image (24 Oct) on Kubernetes 1.4 on nginx pod:
```
$ kubectl exec -it nginx /bin/bash
root@nginx:/# exit
exit

$ kubectl logs nginx
127.0.0.1 - - [24/Oct/2016:18:11:01 +0000] "GET / HTTP/1.1" 200 612 "-" "curl/7.38.0" "-"
127.0.0.1 - - [24/Oct/2016:18:11:02 +0000] "GET / HTTP/1.1" 200 612 "-" "curl/7.38.0" "-"
```
