### ISSUE TITLE
Kubernetes Ingress LB stack and Kubernetes LB stacks are not displayed in the UI

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#6279]
**Rancher Version:** Master

**Docker Version:**1.12.1

**OS and where are the hosts located? (cloud, bare metal, etc):**Ubuntu, Cloud

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** Single node

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**Kubernetes

**Steps to Reproduce:**
1. Create a Kuberentes Environment 
2. Kubernetes Lb stack and Ingress Lb stacks are not displayed in the UI. 
They are not in the Infrastructure stacks link or any other location.
3. Create a service and Ingress for that service. The ingress will not displayed in the stack. They can be accessed only through the host tab

**Comment by vincent99** [comment]
The stacks should have `system:true` set.

**Comment by tfiduccia** [comment]
Version - master 10/19
Verified fixed
