### ISSUE TITLE
Adding a host that is in "inactive" state to Load balancer results in add host being stuck in "activating" state. 

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#628]
Server version - V0.17.1

Steps to reproduce the problem:
Create a LB and add a host , say H1 with 2 targets.
Deactivate another host H2.
Try to add this host to LB (UI restricts adding hosts in inactive state to LB)
This results in the host addition to be stuck in "activating".

| 138 | NULL | loadBalancerTarget | 8f707dc3-172f-4efa-b2c2-ccc7ec654dee | NULL | activating | 2015-04-28 15:06:58 | NULL | NULL | {"fields":{}} | NULL | 274 | 59 | 5 |

 It would be better to not allow for addition/deletion of hosts to LB when hosts are in inactive state and error out at the API level.

**Comment by alena1108** [comment]
Closing as won't fix as standalone LB support is disabled.
