### ISSUE TITLE
When launching stacks in the UI with invalid yml for 1 of the services ( and valid yml for other services), service get created with "stack" in error state. 

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6284]
Server version - Build from master:

When launching stacks in the UI with invalid yml for 1 of the services ( and valid yml for other services) , user is presented with the error message about the error like Error (Unsupported config option for test1 service: 'label') for the service with invalid yml. 
Stack is created  in "error" state.
Services with valid yml get created in "inactive" state. Should we not even be creating this service because it is under a stack that is in "error" state ?

This issue tracks one of  the scenarios that was not addressed in - https://github.com/rancher/rancher/issues/3950

**Comment by emzein** [comment]
I am trying to create a stack and its taking forever to activate. how can i fix this?
