### ISSUE TITLE
Route53 DNS service fails to set DNS records if host has custom labels

### ISSUE THREAD

**Issue by adammwood** [rancher/rancher#6285]
If an instance is created with one or more custom labels, the Route53 catalog service fails to set DNS records with the error:

> json: cannot unmarshal array into Go value of type string

We can consistently replicate this:

**Create a host without any labels, output of Route53 DNS service:**

> 15/10/2016 17:55:14time="2016-10-15T16:55:13Z" level=info msg="Starting Rancher External DNS service"
> 15/10/2016 17:55:19time="2016-10-15T16:55:19Z" level=info msg="Configured Route 53 with hosted zone 'foo.com.' in region 'eu-west-1' "
> 15/10/2016 17:55:19time="2016-10-15T16:55:19Z" level=info msg="Healthcheck handler is listening on :1000"
> 15/10/2016 17:55:19time="2016-10-15T16:55:19Z" level=info msg="DNS records to add: [{test-app.test-app.testing.foo.com. [SECRET] A 300}]"
> 15/10/2016 17:55:19time="2016-10-15T16:55:19Z" level=info msg="Adding dns record: {test-app.test-app.testing.foo.com. [SECRET] A 300}"

**Create a host with one label (foo=bar), output of Route53 DNS service:**

> 15/10/2016 18:02:04time="2016-10-15T17:02:04Z" level=info msg="Starting Rancher External DNS service"
> 15/10/2016 18:02:11time="2016-10-15T17:02:11Z" level=info msg="Configured Route 53 with hosted zone 'foo.com.' in region 'eu-west-1' "
> 15/10/2016 18:02:11time="2016-10-15T17:02:11Z" level=info msg="Healthcheck handler is listening on :1000"
> 15/10/2016 18:02:11time="2016-10-15T17:02:11Z" level=info msg="json: cannot unmarshal array into Go value of type string"
> 15/10/2016 18:02:12time="2016-10-15T17:02:12Z" level=info msg="json: cannot unmarshal array into Go value of type string"

**Create a host with two labels (foo=bar, bar=foo), output of Route53 DNS service:**

> 15/10/2016 18:07:41time="2016-10-15T17:07:41Z" level=info msg="Starting Rancher External DNS service"
> 15/10/2016 18:07:47time="2016-10-15T17:07:47Z" level=info msg="Configured Route 53 with hosted zone 'foo.com.' in region 'eu-west-1' "
> 15/10/2016 18:07:47time="2016-10-15T17:07:47Z" level=info msg="Healthcheck handler is listening on :1000"
> 15/10/2016 18:07:47time="2016-10-15T17:07:47Z" level=info msg="json: cannot unmarshal array into Go value of type string"
> 15/10/2016 18:08:14time="2016-10-15T17:08:14Z" level=info msg="json: cannot unmarshal array into Go value of type string"

All hosts are AWS EC2 instances with RancherOS (v0.6.1 (4.4.19)), and we haven't tested it with other DNS services.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.2.0-pre4-rc2` Cattle: `v0.170.1` UI: `v1.2.13` Route53 Service: `v0.5.0` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`host.containers`|

**Comment by janeczku** [comment]
@adammwood Can not reproduce this. Could you get the hosts metadata from within a container and paste the output? ie. `curl --header 'Accept: application/json' 'http://rancher-metadata/2015-12-19/hosts'`

**Comment by adammwood** [comment]
@janeczku Thanks, I think this shows the problem. I've just created a new host with a custom label to get this output.

```
[
  {
    "agent_ip": "SECRET",
    "hostId": 29,
    "hostname": "test--1",
    "labels": {
      "foo": [
        "bar"
      ],
      "io.rancher.host.agent_image": "rancher/agent:v1.1.0-rc1",
      "io.rancher.host .docker_version": "1.12",
      "io.rancher.host.linux_kernel_version": "4.4"
    },
    "memory": 1040187392,
    "name": "test--1",
    "uuid": "b757ae0d-0089-47d8-9aef-acd7f9b78679"
  }
]
```
I'm guessing that the label's value should be string, but it's in an array.

**Comment by janeczku** [comment]
@adammwood Yes there is the problem indeed. Was the host added using custom host method or with the EC2 integration?

**Comment by adammwood** [comment]
@janeczku All our hosts are added through the EC2 integration. This probably explains some other strange behaviour that we've seen recently when using labels... The Route53 service was the only issue that we noticed was directly affected by using them.

I've created another host with a few labels and see the following in the API:

```
{
  "labels": {
    "foo1": "bar1",
    "foo2": "bar2",
    "foo3": "bar3"
  }
}
```

... but when I get the host metadata from a container I get this:

```
[
  {
    "labels": {
      "foo1": [
        "bar1"
      ],
      "foo2": [
        "bar2"
      ],
      "foo3": [
        "bar3"
      ],
      "io.rancher.host.agent_image": "rancher/ agent:v1.1.0-rc1",
      "io.rancher.host.docker_version": "1.12",
      "io.rancher.host.linux _kernel_version": "4.4"
    }
  }
]
```

Should I close this issue and open one specifically about the labels?

**Comment by janeczku** [comment]
@adammwood I have created an issue for this here https://github.com/rancher/rancher/issues/6287.
Could you add your observation about label values showing as strings in API but as arrays in Metadata there?
