### ISSUE TITLE
Labels assigned when adding hosts have array values instead of string values

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#6287]
**Rancher Version:**
Rancher v1.2.0-pre4-rc2
Cattle v0.170.1
User Interface v1.2.13
Rancher Compose v0.11.0-rc2

**Steps to Reproduce:**
1. Click on "Add Host" and choose on of the provider integrations
2. Click on "Add Label" and add a label with key "foo" and value "bar".
3. Click on "Create"
4. Check the label data in the host's API resource

**Results:** 
The "foo" label value is an array type

**Expected:**
Label values should be string type

![hostlabels](https://cloud.githubusercontent.com/assets/3813921/19413558/240daed2-9331-11e6-9028-919491f0afb2.png)

**Comment by adammwood** [comment]
Here is some background information from #6285:

> I've created another host with a few labels and see the following in the API:
> 
> ```
> {
>   "labels": {
>     "foo1": "bar1",
>     "foo2": "bar2",
>     "foo3": "bar3"
>   }
> }
> ```
> ... but when I get the host metadata from a container I get this:
> ```
> [
>   {
>     "labels": {
>       "foo1": [
>         "bar1"
>       ],
>       "foo2": [
>         "bar2"
>       ],
>       "foo3": [
>         "bar3"
>       ],
>       "io.rancher.host.agent_image": "rancher/agent:v1.1.0-rc1",
>       "io.rancher.host.docker_version": "1.12",
>       "io.rancher.host.linux _kernel_version": "4.4"
>     }
>   }
> ]
> ```

**Comment by janeczku** [comment]
Verified fixed in master 10/16
1. Custom host labels have string values in API
2. Custom host labels have string values in Metadata
