### ISSUE TITLE
Please support ap-south-1 (mumbai) for AWS

### ISSUE THREAD

**Issue by arvindr21** [rancher/rancher#6288]
**Rancher Version:**
v1.1.4

**Docker Version:**
Docker version 1.12.2, build bb80604

**OS and where are the hosts located? (cloud, bare metal, etc):**
x86_64 x86_64 x86_64 GNU/Linux and AWS 

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
From UI
Infrastructure (menu) > Hosts > Add New > AWS
Region Field does not contain AWS ap-south-1 region

**Results:** 
<img width="1250" alt="screen shot 2016-10-16 at 08 38 41" src="https://cloud.githubusercontent.com/assets/2562992/19414942/22809eda-937c-11e6-82c3-ebb1abfffbfd.png">

**Expected:**
Please add ap-south-1 to the list.

**Comment by vincent99** [comment]
This is already in 1.2.. https://github.com/rancher/ui/blob/master/app/components/machine/driver-amazonec2/component.js#L58

**Comment by arvindr21** [comment]
Thanks. Picked up the RC release. Works fine now!

**Comment by deniseschannon** [comment]
@arvindr21 Which RC did you pick up?

We do not recommend any RC release as it hasn't been validated by QA. Particularly v1.2.0-pre4-rc2 is very broken.

**Comment by arvindr21** [comment]
@deniseschannon I have picked up : `v1.2.0-pre4-rc2` :(

Any other (stable) version which supports ap-south-1?

**Comment by deniseschannon** [comment]
@arvindr21 There is no current stable version, but you could try out our latest development build v1.2.0-pre3. This has been through our automated tests and passes, but is not something we recommend for production.

http://docs.rancher.com/rancher/v1.2/en/installing-rancher/installing-server/#rancher-server-tags

**Comment by arvindr21** [comment]
Thanks @deniseschannon I am still exploring Rancher if it fits our needs. I will work with  v1.2.0-pre3 for that.
