### ISSUE TITLE
Can't start rancher agent on osx

### ISSUE THREAD

**Issue by Vinceveve** [rancher/rancher#6289]
**Rancher Version:**
1.1.4

**Docker Version:**
INFO: docker version: Server version: 1.12.1
INFO: docker version: Server API version: 1.24

**OS and where are the hosts located? (cloud, bare metal, etc):**
local macbook pro

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Demo node, latest docker osx version, agent and server on same node

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**

```
docker run -e CATTLE_AGENT_IP="192.168.65.2"  -d --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.0.2 http://127.0.0.1:8080/v1/scripts/xxxxxx
```

**Results:** 

```
...
INFO: docker info: Https Proxy:
INFO: docker info: No Proxy: *.local,169.254/16
INFO: Attempting to connect to: http://192.168.65.2:8080/v1
INFO: http://192.168.65.2:8080/v1 is accessible
...
INFO: Running registration
Traceback (most recent call last):
  File "./register.py", line 11, in <module>
    secret_key=os.environ['CATTLE_REGISTRATION_SECRET_KEY'])
...
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f8121e02e50>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

**Expected:**
Tried with `--add-host=localhost:192.168.65.2`, also with my external network, with `--link=rancher-server:rancher-server`

Can't make it work

**Comment by deniseschannon** [comment]
Are you using docker for mac? If so, it's currently not supported in Rancher.

**Comment by senica** [comment]
Any work on this?

**Comment by vincent99** [comment]
Docker for Mac is not supported because of the way it creates a VM and handles networking to it.  I use https://github.com/rancher/10acre-ranch#docker-machine-on-macos to run on my laptop, and we may someday have more of a polished "Rancher for Mac".

**Comment by senica** [comment]
I think I kind of got it working. Perhaps I'll run into problems in just a little bit :)

# Setting up for local development testing

## Clone Rancher
On your Mac:

Run `git clone https://github.com/rancher/rancher.git`

Run `cd ./rancher`

Run `pwd` and input this as the **local directory** in the agent command below.


## Network
Create a new docker network

Run `docker network create --subnet=172.18.0.0/16 rancher`

## Rancher Server
Create *rancher server* on *rancher network*

Run `sudo docker run -d --restart=unless-stopped -p 8585:8080 --net rancher --ip 172.18.0.2 rancher/server:stable`

Run `ifconfig` to get your Mac's local ip address.
Access with `http://<mac's local ip address>:8585`. *Important to access with this ip address* and **NOT** *localhost* or *127.0.0.1*

In the web browser, click **add host**

![screen shot 2017-10-05 at 12 14 06 pm](https://user-images.githubusercontent.com/954952/31248714-958a9958-a9c9-11e7-9d3f-704f6918a842.jpg)

For the **Host Registration URL** select **Something Else** and input `http://docker.for.mac.localhost:8585`

![screen shot 2017-10-05 at 12 19 12 pm](https://user-images.githubusercontent.com/954952/31248723-9b1f3aae-a9c9-11e7-8b16-30697cb3e3e8.jpg)

[docker.for.mac.localhost](https://docs.docker.com/docker-for-mac/networking/#use-cases-and-workarounds) is a special host name that Docker will resolve to your host machine.

### Rancher Agent
While still adding a host in the rancher web manager, specify an ip address of `172.18.0.3`.

![screen shot 2017-10-05 at 12 25 23 pm](https://user-images.githubusercontent.com/954952/31248742-b228a140-a9c9-11e7-9ba6-a6d6323c5ad4.jpg)

Your command will look like `sudo docker run -e CATTLE_AGENT_IP="172.18.0.3"  --rm --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.2.6 http://docker.for.mac.localhost:8585/v1/scripts/488A0A9BF22498C6DF67:1483142400000:SAoITuNodirQspJstjdBmgxil0`

Replace the first `/var/lib/rancher` to point to **local directory** of rancher and specify the **network** and **ip address** to use so the final command might look like:

`sudo docker run -e CATTLE_AGENT_IP="172.18.0.3"  --rm --privileged --net rancher --ip 172.18.0.3 -v /var/run/docker.sock:/var/run/docker.sock -v <local rancher directory>:/var/lib/rancher rancher/agent:v1.2.6 http://docker.for.mac.localhost:8585/v1/scripts/488A0A9BF22498C6DF67:1483142400000:SAoITuNodirQspJstjdBmgxil0`

Seems to work

![screen shot 2017-10-05 at 12 27 34 pm](https://user-images.githubusercontent.com/954952/31248763-c2f2f4c6-a9c9-11e7-843b-6c784bfe5ef0.jpg)

**Comment by vincent99** [comment]
The next set of problems will be publishing a port and being able to get to it.
