### ISSUE TITLE
Service scheduling rules not working

### ISSUE THREAD

**Issue by pulberg** [rancher/rancher#6291]
**Rancher Version:**
v1.2.0-pre4-rc2

**Docker Version:**
1.12.2

**OS and where are the hosts located? (cloud, bare metal, etc):**
RHEL7.2, AWS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node, internal db

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Create new stack
add service (nginx:alpine)
add scheduling rule (host "must" have a "host label" of "app" = "nginx")
![screenshot 2016-10-16 22 47 52](https://cloud.githubusercontent.com/assets/11069351/19424960/78058498-93f3-11e6-8d7b-79ea11ff6b29.png)

**Results:** 
service error - (Failed to allocate instance [container:1i1367]: Bad instance [container:1i1367] in state [error]: Scheduling failed: needs host with label app:nginx)
![screenshot 2016-10-16 21 18 34](https://cloud.githubusercontent.com/assets/11069351/19424934/420115b0-93f3-11e6-80ca-59a166dd09df.png)
**Expected:**
service scheduling on hosts with applicable label

![screenshot 2016-10-16 21 27 07](https://cloud.githubusercontent.com/assets/11069351/19424951/621ad106-93f3-11e6-8a8a-a5c2c8254326.png)

**Comment by deniseschannon** [comment]
@pulberg Please don't use v1.2.0-pre4-rc2. It has many known broken things including host labels/scheduling. These have been resolved in master, but we haven't cut a new RC yet. In general, we'd recommend not to use the RC and only stick with one without the `rc` in the release name.

**Comment by pulberg** [comment]
@deniseschannon Ok, but we're sooooo excited about the new features!!!! :)
