### ISSUE TITLE
rancher-agent:v1.0.2 failed to run...

### ISSUE THREAD

**Issue by tonythian** [rancher/rancher#6293]
Add rancher-agent:v1.0.2 failed:

INFO: Starting agent for F47E82B4F797498B1812
INFO: Access Key: F47E82B4F797498B1812
INFO: Config URL: http://my.server.com:8080/v1
INFO: Storage URL: http://my.server.com:8080/v1
INFO: API URL: http://my.server.com:8080/v1
INFO: IP: 13.67.xxx.xxx
INFO: Port:
INFO: Required Image: rancher/agent:v1.0.2
INFO: Current Image: rancher/agent:v1.0.2
INFO: Using image rancher/agent:v1.0.2
INFO: Downloading agent http://my.server.com:8080/v1/configcontent/configscripts
{"id":"580a6e63-1235-4ab7-945e-fa3fd206ef09","type":"error","links":{},"actions":{},"status":422,"code":"MissingRequired","message":null,"detail":null,"fieldName":"agentId"}
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
---

| Useful | Info |
| :-- | :-- |
| Versions | Rancher `v1.1.4` Cattle: `v0.165.8.4` UI: `v1.1.14` |
| Access | `localauth` `admin` |
| Orchestration | `Cattle` |
| Route | `hosts.index` |

**Comment by aemneina** [comment]
@tonythian did you ever manage to resolve this?

**Comment by tonythian** [comment]
I was able to resolve it after restarting the docker service, I remove the rancher-agent image and remove /var/lib/rancher folder.
