### ISSUE TITLE
Catalog Page breaks when unchecking "Start services after creating"

### ISSUE THREAD

**Issue by toughIQ** [rancher/rancher#6296]
**Rancher Version:**
v1.2.0-pre4-rc4
**Docker Version:**
1.12.1
**OS and where are the hosts located? (cloud, bare metal, etc):**
RHEL7.2 Vmware Host
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node, external DB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
Choose any item out of catalog. At down left uncheck "Start services after creating".
**Results:** 
All the option fields, Launch button and Preview area disappear. Only "Template Version" is left.
**Expected:**
No changes on the page and the forms. Just unchecking the checkbox.

**Comment by tfiduccia** [comment]
Verified this is broken in master 10-19

**Comment by tfiduccia** [comment]
Version - master 10/23
Verified fixed
