### ISSUE TITLE
[cli] Renaming project

### ISSUE THREAD

**Issue by franciscocpg** [rancher/rancher#6297]
Well, one of the options for installing the rancher go client is `go get github.com/rancher/cli`, but this creates a bad name file called `cli` at my $GOBIN path.

IMO this project should be renamed to `rancher-cli` so `go get github.com/rancher/rancher-cli` is going to create a file named `rancher-cli` at $GOBIN path and voila!

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
