### ISSUE TITLE
Can't delete Kubernetes object using the REST API

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#6298]
**Rancher Version:**
master image
**Docker Version:**
1.12.2
**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

Trying to delete replication controller, and i am having this error:

```
$ curl -XDELETE -d '{"apiVersion":"v1","kind":"ReplicationController","gracePeridSeconds": 0,"orphanDependents": true}' $APISERVER/api/v1/namespaces/default/replicationcontrollers/nginx -H "Content-Type: application/json" --header "Authorization: Bearer $TOKEN" --insecure
{
  "code": 500,
  "message": "converting (v1.ReplicationController) to (api.DeleteOptions): GracePeriodSeconds not present in src",
  "status": "Failure",
  "metadata": {},
  "apiVersion": "v1",
  "kind": "Status"
}
```

**Comment by wlan0** [comment]
The request is wrong. The data portion should be empty in the curl request above. 

The below is my request which works - 
```
curl -X DELETE $APISERVER/api/v1/namespaces/default/replicationcontrollers/guestbook -H "Content-Type: application/json" --header "Authorization: Bearer $TOKEN" —insecure
```

**Comment by galal-hussein** [comment]
Tested and worked on master image (24 Oct) using the "kind: DeleteOptions"
