### ISSUE TITLE
Parameterize stack-name in K8s catalog.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6300]
Tested with Rancher Version: v1.2.0-pre4-rc3 and
K8s 1.4 version from - https://github.com/rancher/infra-catalog

K8s templates have references to http://kubernetes.kubernetes.rancher.internal which rely on stack name being "kubernetes". Currently it is not a problem, since UI workflow does not allow for stack name to be picked.  
For the catalog entry itself to be functional outside of UI workflow , we would need the stack-name to be parameterized.

**Comment by alena1108** [comment]
stack name for kubernetes should be kubernetes. We rely on this name everywhere in the code, not just in microservices.
