### ISSUE TITLE
using "esc" in container shell causes it to exit the shell.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6302]
Rancher Version:v1.2.0-pre4-rc3

Steps to reproduce the problem:
Launch a service.
Exec into the container using "Execute Shell" option.
User is taken to the containers shell.
Use "esc" button.
Notice that you exit the shell.

**Comment by vincent99** [comment]
@westlywright new modals..

**Comment by westlywright** [comment]
This will have two parts, the commit referenced above and this commit in lacsso rancher/lacsso@9810208c229e20779793c88064ebac3d9fc57e71

**Comment by tfiduccia** [comment]
Version - master 10/19
Verified fixed
