### ISSUE TITLE
Preserving client source IP for external traffic in Kubernetes 1.4

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#6307]
**Rancher Version:**
master image
**Docker Version:**
1.12.2
**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes 1.4

To preserve the client source IP when creating Load balancer services, an annotation should be added, for example:

```
{
      "kind": "Service",
      "apiVersion": "v1",
      "metadata": {
        "name": "example-service",
        "annotations": {
            "service.alpha.kubernetes.io/external-traffic": "OnlyLocal"
        }
      },
      "spec": {
        "ports": [{
          "port": 8765,
          "targetPort": 9376
        }],
        "selector": {
          "app": "example"
        },
        "type": "LoadBalancer"
      }
    }
```

This is not yet implemented in LB created in Rancher environment.
http://kubernetes.io/docs/user-guide/load-balancer/

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
