### ISSUE TITLE
Saml: Updating bad config does not take effect

### ISSUE THREAD

**Issue by prachidamle** [rancher/rancher#6309]
**Rancher Version:** 1.2.0-pre4-rc4

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single node rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:**

1. Admin -> Access Control
2. Configure Shibboleth provider
3. Add the configuration data with some bad data as invalid cert or key etc
4. Saml auth does not work
5. Correct the bad data and save the config again
6. The corrected config does not take effect

**Results:** 
Saml auth fails to get configured if the config set is not correct. Updating bad config does not take effect

**Expected:**
Updating bad config should take effect and give admin chance to correct the config

**Comment by galal-hussein** [comment]
Tested on the master image (24 Oct):

- I added a wrong private key
- Saved and tested, then SAML auth didn't work
- I corrected the key and saved again and tested, and SAML authentication worked!
