### ISSUE TITLE
Cannot use image in a registry if port is specified

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#6311]
**Rancher Version:**
v1.2.0-pre4-rc4
**Docker Version:**
1.12.1
**OS and where are the hosts located? (cloud, bare metal, etc):**
RancherOS v0.6.1 on AWS
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
Infrastructure -> Containers -> Add Container
Name: dummy
Image: `<ip>:<port>/<imagename>`,`10.0.0.1:4567/dummy`
Create
**Results:** 
`Error (ImageActivate: failed to do image activate: Failed to pull image: invalid reference format)`

**Expected:**
Launch as I wouldn't set a port. `docker pull 10.0.0.1:4567/dummy`  on the hosts works fine. 

Would love to debug this more, if someone can point me to the right part of the code.

**Comment by wstudios2009** [comment]
same issue for me even when using the default registry port

**Comment by superseb** [comment]
True, adjusted the title to reflect this. Any port specification triggers the error.

**Comment by soumyalj** [comment]
Verified with v1.2.0-pre4-rc7. Created a local registry <localhost:5000> and pushed an ubuntu image to this registry on host1. On host2, configured --insecure-registry <ipaddress of host1>:5000.
Created a container on host2 using image <ipaddress>:5000/ubuntu successfully.
