### ISSUE TITLE
Container Stats Not showing

### ISSUE THREAD

**Issue by akbarfreq** [rancher/rancher#6312]
**Rancher Version: 1.1.4**

**Docker Version: docker-engine-1.12.2-1.el7.centos.x86_64**

**OS : CentOS Linux release 7.2.1511 (Core)**

**Setup Details: single node rancher , internal DB**

**Environment Type: ( Cattle )**

**Steps to Reproduce:**

**Results:** 

**Expected:**

Hi , After installing Docker with LVM Support, I am not getting container stats. where i am getting Host node stats.

below i have detailed configuration done from the links.
After installing docker, I followed below link for LVM 
https://docs.docker.com/engine/userguide/storagedriver/device-mapper-driver/

[root@docker-node ~]# docker info
Containers: 7
 Running: 7
 Paused: 0
 Stopped: 0
Images: 10
Server Version: 1.12.2
Storage Driver: devicemapper
 Pool Name: docker-thinpool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: 
 Metadata file: 
 Data Space Used: 5.123 GB
 Data Space Total: 102 GB
 Data Space Available: 96.88 GB
 Metadata Space Used: 1.839 MB
 Metadata Space Total: 1.07 GB
 Metadata Space Available: 1.068 GB
 Thin Pool Minimum Free Space: 10.2 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local DataVolume
 Network: overlay bridge null host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.36.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 9.609 GiB
Name: docker-node.f1soft.com
ID: LKBQ:WJDJ:HB4S:OYMN:M4OJ:AT2R:HWME:2P2I:DQG3:FTH2:2BDY:D2QE
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8

**Comment by deniseschannon** [comment]
We are moving away from cadvisor (what is used up until the 1.2.0-pre3 release) to using `docker stats`. 

This has been already verified in our latest rcs for the upcoming release. 
https://github.com/rancher/rancher/issues/6254
