### ISSUE TITLE
1.2.0-pre4-rc4

### ISSUE THREAD

**Issue by andruwa13** [rancher/rancher#6314]
in v1.2.0-pre4-rc4 no Russian language
![rancher_2016-10-18_19-23-12](https://cloud.githubusercontent.com/assets/5846351/19486829/9be6bb68-9568-11e6-93df-e05d3e417431.png)

v1.2.0-pre3:
![rancher 2016-10-18 19-27-25](https://cloud.githubusercontent.com/assets/5846351/19486970/33c65c22-9569-11e6-9c49-20e5be526fb0.png)

**Comment by vincent99** [comment]
The language name field got dropped, fixed in next build.

**Comment by tfiduccia** [comment]
Version - master 10/19
Verified fixed
