### ISSUE TITLE
Can't disable Shibboleth authentication from the UI

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#6315]
**Rancher Version:**
v1.2.0-pre4-rc4
**Docker Version:**
1.12.2
**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
- Enable Shibboleth authentication.
- Try to disable it from the Access control tab.

**Results:** 
Can't be done.

**Comment by tfiduccia** [comment]
Hussein - this is fixed in master build

**Comment by galal-hussein** [comment]
Tested and worked, thanks!
