### ISSUE TITLE
Enabling Unsafe Sysctls within kubernetes 1.4

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#6316]
**Rancher Version:**
v1.2.0-pre4-rc4
**Docker Version:**
1.12.2
**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes 1.4

In order to enable(whitelist) Unsafe sysctls and run them within pods, kubelet must be started with the following option:

```
$ kubelet --experimental-allowed-unsafe-sysctls 'kernel.msg*,net.ipv4.route.min_pmtu' ...
```

**Comment by superseb** [comment]
Closing in favor of https://github.com/rancher/rancher/issues/4751
