### ISSUE TITLE
Enabling pod security policy in k8s 1.4

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#6320]
**Rancher Version:**
master image
**Docker Version:**
1.12.2
**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes 1.4

Pod security policies have some prerequisites in order to work in kubernetes environment:
- Enable api type extensions/v1beta1/podsecuritypolicy
- Enable the admission controller PodSecurityPolicy

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
