### ISSUE TITLE
Ports isn't up to date when containers go unhealthy in service

### ISSUE THREAD

**Issue by schuylr** [rancher/rancher#6324]
**Rancher Version:** 1.2.0-pre3

**Docker Version:** 1.11.2

**OS and where are the hosts located? (cloud, bare metal, etc):** AWS EC2

**Setup Details:** Single Instance External DB

**Environment Type:** Cattle

**Steps to Reproduce:**

1. Start a service with a health check
2. Kill the endpoint in the container, causing the service to eliminate the container as unhealthy
3. Ports still show the host of a removed container

**Results:** 

See the incorrect 6 exposed ports here: 

![screen shot 2016-10-18 at 7 04 51 pm](https://cloud.githubusercontent.com/assets/12628715/19499735/0bf5de6e-9566-11e6-8e38-259fecdb5c0b.png)

Even though there's 5 containers running:

![screen shot 2016-10-18 at 7 07 14 pm](https://cloud.githubusercontent.com/assets/12628715/19499744/1bb4dfc6-9566-11e6-9ec8-dc072472adce.png)

**Expected:**

Eliminated containers shouldn't show up in the `publicEndpoints` parameter for the service. This breaks my Capistrano deploys as they use the `publicEndpoints` array to determine the available hosts for deploying.

The workaround is to force a service update by restarting a container or cycling a host between inactive and active.

**Comment by schuylr** [comment]
Maybe this is accentuated with lots of hosts and services? I'm running 60 hosts in a single environment at this point, but my process list is pretty lean aside from some timing out volume.activate ones.

**Comment by sangeethah** [comment]
Tested the following scenario with server version - v1.2.0-pre4-rc5:

Start a service with a health check
Kill the endpoint in the container, causing the service to eliminate the container as unhealthy
Ports tab under the service (service.publicEndpoints) reflects the correct list of host ips which does not have the host entry of the deleted container but has the host where the new (reconcolied) container is running.

**Comment by sangeethah** [comment]
The 1 issue I see that the host gets added to the service.publicEndpoints , even before the container is fully started (even when it is in starting state).

**Comment by sangeethah** [comment]
@schuylr  , I am not able to reproduce the issue where host entries of the removed (unhealthy) containers are still present in the publicEndpoints parameter for the service when testing on a setup that had 6 hosts and service with scale 5.

Could you retest with server version - v1.2.0-pre4 when it is available to see if you still face this issue?

**Comment by schuylr** [comment]
@sangeethah Thanks - let's hope for this.
