### ISSUE TITLE
Container IP not displayed on the container info/stats page

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#6325]
**Rancher Version:**v1.2.0-pre4-rc4

**Docker Version:**1.12.2

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**Single Node

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**: Cattle

**Steps to Reproduce:**
1. Create a Cattle environment
2. Create a service with one or more containers. Click on the container and the container info page is displayed. The container IP is not displayed in this page.

**Expected:**
Container IP should be displayed.

**Comment by tfiduccia** [comment]
Version - master 10/20
Verified fixed
