### ISSUE TITLE
Wrong POD ip address.

### ISSUE THREAD

**Issue by omegarus** [rancher/rancher#6327]
Rancher Version: 1.1.4
Docker Version: 1.10.2
OS and where are the hosts located? (cloud, bare metal, etc): VMware Ubuntu 14.04.4 LTS
Setup Details: Single node rancher
Environment Type: Kubernetes with 2 hosts/nodes
Steps to Reproduce:
Deploy k8s Example Wordpress from community-catalog.
Results:
After deploy i got two POD's in Kubernetes with Pod ip on 172.17.0.0 subnet. 
One mysql on node1 and wordpress on node2
Expected:
Pod's ip's should be in cluster subnet 10.42.0.0 so they can communicate with each other.

**Comment by omegarus** [comment]
In rancher 1.2.0.-pre3 Kubernetes v1.3.0-rancher3 everything works fine and my pods receive the correct ip addresses from cluster subnet.

**Comment by aemneina** [comment]
@omegarus sounds like you have a fix/workaround. Closing the issue...
