### ISSUE TITLE
Rancher & WAF incompatibility : OWASP rule missing/empty accept header

### ISSUE THREAD

**Issue by kvaes** [rancher/rancher#6328]
**Rancher Version:** 1.1.4

When implementing the Azure Application Gateway with WAF functionality, the hosts go into "reconnecting" state. When debugging the log files, the following message is shown ;

```
    {
         "resourceId": "*redacted*",
         "operationName": "ApplicationGatewayFirewall",
         "time": "2016-10-19T11:30:05.4391397Z",
         "category": "ApplicationGatewayFirewallLog",
         "properties": {"instanceId":"ApplicationGatewayRole_IN_0","clientIp":"13.81.210.68","clientPort":54316,"requestUri":"/v1/subscribe?eventNames=storage.image.activate&eventNames=storage.volume.activate&eventNames=storage.volume.deactivate&eventNames=storage.volume.remove&eventNames=ping&eventNames=config.update&eventNames=delegate.request&eventNames=compute.instance.activate&eventNames=compute.instance.deactivate&eventNames=compute.instance.force.stop&eventNames=compute.instance.inspect&eventNames=compute.instance.pull&eventNames=compute.instance.remove","ruleId":"OWASP_960015","message":"Request Missing an Accept Header","action":"Blocked","site":"Global","message":"Request Missing an Accept Header","details":{"message":" Access denied with code 403 (phase 2). Operator EQ matched 0 at REQUEST_HEADERS.","file":"/owasp_crs/base_rules/modsecurity_crs_21_protocol_anomalies.conf","line":"47"}}
    }
```

The error occurs on many urls, so the subscribe one isn't the only one affected... All however have the link towards => /owasp_crs/base_rules/modsecurity_crs_21_protocol_anomalies.conf

A quick google brings me to ; https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/master/base_rules/modsecurity_crs_21_protocol_anomalies.conf
# 
# Missing/Empty Accept Header
# 
# -=[ Rule Logic ]=-
# These rules will first check to see if an Accept header is present.
# The second check is to see if an Accept header exists but is empty.
# 

SecMarker BEGIN_ACCEPT_CHECK

```
SecRule REQUEST_METHOD "!^OPTIONS$" \
        "skipAfter:END_ACCEPT_CHECK,chain,phase:2,rev:'1',ver:'OWASP_CRS/2.2.9',maturity:'9',accuracy:'9',t:none,block,msg:'Request Missing an Accept Header',severity:'5',id:'960015',tag:'OWASP_CRS/PROTOCOL_VIOLATION/MISSING_HEADER_ACCEPT',tag:'WASCTC/WASC-21',tag:'OWASP_TOP_10/A7',tag:'PCI/6.5.10'"
    SecRule &REQUEST_HEADERS:Accept "@eq 0" "t:none,setvar:'tx.msg=%{rule.msg}',setvar:tx.anomaly_score=+%{tx.notice_anomaly_score},setvar:tx.%{rule.id}-OWASP_CRS/PROTOCOL_VIOLATION/MISSING_HEADER-%{matched_var_name}=%{matched_var}"
SecRule REQUEST_METHOD "!^OPTIONS$" \
        "chain,phase:2,rev:'1',ver:'OWASP_CRS/2.2.9',maturity:'9',accuracy:'9',t:none,block,msg:'Request Has an Empty Accept Header',severity:'5',id:'960021',tag:'OWASP_CRS/PROTOCOL_VIOLATION/MISSING_HEADER_ACCEPT'"
    SecRule REQUEST_HEADERS:Accept "^$" "t:none,setvar:'tx.msg=%{rule.msg}',setvar:tx.anomaly_score=+%{tx.notice_anomaly_score},setvar:tx.%{rule.id}-OWASP_CRS/PROTOCOL_VIOLATION/MISSING_HEADER-%{matched_var_name}=%{matched_var}"
```

SecMarker END_ACCEPT_CHECK

**Comment by vincent99** [comment]
That's a pretty dumb rule... Accept is optional and there's no reason a client needs to send it when it knows the API defaults to JSON.

Also it's meaningless for an upgrade request, and the headers sent when creating a  WebSocket are entirely up to the browser so there's nothing that can be done to make them send it.

**Comment by kvaes** [comment]
Despite the view that it's a dumb rule, be aware that this is the way certain WAFs will take a look at the traffic.

**Comment by aemneina** [comment]
@kvaes I think we can retire this in favor of https://github.com/rancher/rancher/issues/6396 , does that work?

**Comment by kvaes** [comment]
Those are different issues... This issue is when the Application Gateway is "upgraded" with WAF capabilties. Issue #6396 is even when it is "limited" to "SSL Termination Only" (without any WAF capabilties).

**Comment by kvaes** [comment]
In relation to the this issue, earlier this week I did the following setup ; https://kvaes.wordpress.com/2016/11/09/azure-a-poor-mans-ssl-termination-by-leveraging-cloudflare/

My experience when doing this ; hosts get added without a problem, but... they go into "reconnecting" state on a regular basis. I also notice that the portal was unreachable on a regular basis. 

Now in the past I always used a "basic" nginx as reverse proxy in front of rancher. That solution did work... Despite that I don't like it as it requires more operational effort in its entire lifecycle. The Application Gateway and Cloudflare solution are services, which are managed and frankly cheaper when looking towards the entire lifecycle.

So I'm "stuck" in my quest to find an SSL terminator for Rancher which meets my needs...
@vincent99 ; Any insight if SSL capabilities will become a part of the Rancher core? Thus not needing an external terminator for it?

**Comment by vincent99** [comment]
As I've said this is a poor and arbitrary rule and there is nothing that we can do to change the headers sent by the browser WebSocket client.

Built-in SSL termination is likely, later in the 2.0 cycle.
