### ISSUE TITLE
Issues with mapping ports to 8080 in a container when agent is on same host as server

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#633]
v0.17.1

Steps to Reproduce:
1. Start rancher server on host A
2. On Host A, launch an agent for rancher server using the Add Host command.
3. Create a container that binds to port `8080` on the "Public" port. 

Rancher will stop working.

**Comment by ibuildthecloud** [comment]
@deniseschannon Don't do that.

**Comment by deniseschannon** [comment]
@ibuildthecloud Are you saying that we should just document and say that you aren't allowed to have a container or service bind to port 8080?

**Comment by will-chan** [comment]
We should just say that if both rancher server and agent are on the same host and you created a container that binds to the host port 8080, it won't work.  You either have to change the Rancher server port or do launch a container with port 8080.  You can't really fix this.

**Comment by vincent99** [comment]
It's not really anything to do with port 8080 specifically.. If you map a port it takes priority anything that's running on the host.  You could just as easily mess up SSH on the host, or a web server running on 80.  So.. "don't try to bind to ports that are already running things"?

I still think we should make the default Rancher server port something that isn't incredibly common...

**Comment by ibuildthecloud** [comment]
Actually, due to native docker this could be fixed.  We know the rancher server is running on 8080.  We just don't evaluate port conflicts when you add a container directly to the host.

**Comment by ibuildthecloud** [comment]
But in short, we can address this post-Beta

**Comment by will-chan** [comment]
We should still FAQ this as the container won't then be usable, rather than rancher.  We could also just do what Vince says and launch rancher in an uncommon port.  This will still fail but just not as likely.

**Comment by deniseschannon** [comment]
I've documented and re-assigned to @ibuildthecloud as he says it could be fixed post-Beta.

**Comment by vincent99** [comment]
We do "own" 9345/tcp... http://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=9345

**Comment by ibuildthecloud** [comment]
Okay, this isn't possible anymore because Docker won't allow you to launch two containers sharing the same public port.

**Comment by ibuildthecloud** [comment]
This is resolved by the fact that we started passing the ports we manage to Docker.

**Comment by deniseschannon** [comment]
Verified in v0.63.1 that the container is thrown into error state with the port conflict message.
