### ISSUE TITLE
[cli] Add/change host label 

### ISSUE THREAD

**Issue by Kamaradeivanov** [rancher/rancher#6330]
According to the forum ticket (https://forums.rancher.com/t/add-change-host-label-via-rancher-cli/4256), I create an issue for the following feature.

I would like to add or update a label on a existing host. Actually I can only add labels during the host creation.

**Comment by Gmentsik** [comment]
Any update on this? This would be really usefull....

**Comment by anjia0532** [comment]
This is really really really usefull.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
