### ISSUE TITLE
Can't deploy docker-compose.yml on swarm cluster

### ISSUE THREAD

**Issue by Nefelim4ag** [rancher/rancher#6331]
**Rancher Version:** - 1.1.4
**Docker Version:** - 1.12.2
**OS and where are the hosts located? (cloud, bare metal, etc):** Debian 8, KVM VM
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** HA rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Swarm
**Steps to Reproduce:**
1. Make swarm cluster
2. Try add project with this docker-compose.yml:
version: '2'
volumes:
  teamcity_server_data: {}
  teamcity_server_logs: {}
services:
  teamcity-server:
    image: jetbrains/teamcity-server
    volumes:
      - teamcity_server_data:/data/teamcity_server/datadir
      - teamcity_server_logs:/opt/teamcity/logs
    ports:
      - 8111:8111
    env_file: .env
    restart: always
  teamcity-agent:
    image: jetbrains/teamcity-minimal-agent
    env_file: .env
    restart: always
**Results:** 
Error (exit status 1: Couldn't find env file: /tmp/docker-compose733850782/.env )
**Expected:**
Created project

thanks.

**Comment by vincent99** [comment]
`env_file: .env` refers to a path that does not exist inside the container that is running your request.
