### ISSUE TITLE
Set  maxRancherVersion and upgradeFrom for existing 1.2 /1.3 entries for K8s templates in infra.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6332]
Tested with Rancher Version: v1.2.0-pre4-rc3 and
K8s 1.4 version from - https://github.com/rancher/infra-catalog and branch "qa"

Fresh Install:
We should be restricting to showing only k8s 1.4 for fresh installs.

Upgrade from 1.1.x:
Support upgrade from 1.2 - > 1.4 ( There should be no need to support upgrades to 1.3)

Upgrade from 1.2.0-pre releases (before pre4):
Support upgrade from 1.3 - > 1.4 .
Is there a need to support this upgrade path at all. Should we ask users to just delete and recreate existing K8s system stacks?

**Comment by alena1108** [comment]
@deniseschannon is working on it

**Comment by deniseschannon** [comment]
Address in the 1.2 branch of rancher-catalog.

**Comment by soumyalj** [comment]
Tested with upgrade from 1.1.4 to 1.2.0-pre4-rc14. K8s "Upgrade available" option shows v1.4.6-racher1 as expected.
Tested with upgrade from 1.2.0-pre3 to 1.2.0-pre4rc14. K8s Kubernetes "Upgrade available" option shows v1.4.6-racher1 as expected.
