### ISSUE TITLE
Improve DATABASECHANGELOGLOCK behavior/logging

### ISSUE THREAD

**Issue by cmosetick** [rancher/rancher#6334]
**Rancher Version:**
1.1.3
**Docker Version:**
1.12, with storage driver ZFS
**OS and where are the hosts located?:**
Ubuntu 16.04, EC2

**Setup Details:**
single node rancher, with mysql database on shared host volume

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Restart underlying VM host after a fresh pull of rancher/server

**Results:** 
- Rancher server web gui does not load at all in browser. Appears to not even be running.
- Rancher server container is actually running, but restarts once every 4-5 minutes.
- Liquibase lock error in docker logs indicate that a lock has been set. This "lock" seems to completely prevent the web gui from serving requests, even though "something" is still running on port 8080. I personally don't see why I would need the database to serve a simple error page indicating that their is a problem.
- A MUCH better behavior would be to figure out how to make the web gui serve a page that says: "Database is currently locked, to correct please run X command to resolve."
- The command that I had to run in MySQL to "unlock" the database is:  
  `UPDATE DATABASECHANGELOGLOCK SET LOCKED=FALSE, LOCKGRANTED=null, LOCKEDBY=null where ID=1;`

**Expected:**
rancher/server container restarts, with the new version of rancher upon host reboot.

**Comment by dbsanfte** [comment]
Even better than this would be some logic to automatically unlock the database after a certain amount of time. As it stands, Rancher will just die permanently if all agents go offline for some reason and a lock is still in place. It will never recover until this command is run.

**Comment by dbsanfte** [comment]
I've added an init_connect query to my MySQL database config that checks for any Liquibase lock older than 20 minutes and removes it. Kinda hacky but it keeps Rancher from getting itself stuck.

`UPDATE cattle.DATABASECHANGELOGLOCK set LOCKED=FALSE, LOCKGRANTED=null, LOCKEDBY=null where ID=1 and LOCKGRANTED is not null and TIMESTAMPDIFF(MINUTE, LOCKGRANTED, CURRENT_TIMESTAMP) > 20;`

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
