### ISSUE TITLE
Saml: Enabling any option from the access control page creates an error

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#6339]
**Rancher Version:**
master image
**Docker Version:**
1.12.2
**OS and where are the hosts located? (cloud, bare metal, etc):**
Cloud - Ubuntu 16.04
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
- Enable SAML authentication
- Go to access control page
- Enable any option from the access control page:
  - Allow any valid user
  - Allow members of Environments, plus Authorized Users and Organizations
  - Restrict access to only Authorized Users and Organizations
- Click save
- Log out and try to authenticate again

**Results:** 

A http basic authentication page appears when trying to authenticate and requires to enter username/password:

![r](https://cloud.githubusercontent.com/assets/3309968/19537154/9e50cfc0-9657-11e6-8fda-de0c553705b0.png)

The traffic shows that there is a 500 error response from a request to the following page:

http://130.211.134.160:8080/v1-auth/saml/login?redirectBackBase=http%3A%2F%2F130.211.134.160%3A8080&redirectBackPath=%2Flogin%2Fshibboleth-auth%2F

**Expected:**
To authenticate with the SAML server.

**Comment by prachidamle** [comment]
The root cause of this issue is same as: https://github.com/rancher/rancher/issues/6309
It is solved by the same fix.

**Comment by galal-hussein** [comment]
@prachidamle The issue is fixed on the master image (24 Oct)
