### ISSUE TITLE
Chrome/Firefox: Copy/Paste on Shell doesn't work when page is loaded with higher zoom levels

### ISSUE THREAD

**Issue by rezonant** [rancher/rancher#6342]
**Rancher Version:**
1.1.4

**Docker Version:**
1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu / Cloud

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Rancher host + 2 nodes, internal DB, no HA

**Browsers tested:** 
Google Chrome 54.0.2840.59
Mozilla Firefox 47.0.1 

**Steps to Reproduce:**
1. In Chrome, increase zoom to at least 150%
2. Open rancher shell (ie via kubectl or container execute shell)
3. right click on the terminal

**Results:** 
Most of the time, Copy and Paste options are not available. Sometimes, they are mysteriously there, but their availability is fleeting; often seconds later in the same shell session they will no longer be available. Both Chrome and Firefox exhibit the issue, but it only happens in Firefox with zoom >= 220% which is quite large.
In Chrome, if you zoom down to 100% and then back to 150%, Copy and Paste work fine.
In Firefox, no zoom level will fix it if the page was loaded with >= 220%

**Expected:**
Copy/Paste should work on reasonable zoom levels

**Workaround:**
In Chrome, temporarily reduce your zoom to 100% and back before attempting to paste. The Copy/Paste will then work for the rest of the session. Returning to a shell will reset the bug, and so the zoom trick would need to be repeated.
In Firefox you must reload the page with a lower zoom level in order for Copy/Paste to return.

**Comment by vincent99** [comment]
The terminal emulator is a 3rd-party library (https://github.com/sourcelair/xterm.js) so this would have to be fixed in there.  The way copy/paste works involves an overlapping layer that is synced with the content so it's not terribly surprising that it doesn't line up when the scale is changed.

**Comment by rezonant** [comment]
Initial testing with 1.2.0 final is not showing the problem for me.

**Comment by rezonant** [comment]
However there are other shell problems now, sometimes I cannot use arrow keys in vim and other ncurses programs

**Comment by rezonant** [comment]
I'm going to close this one as I think a newer version of xterm.js helped to resolve most of the copy/paste issues and will eventually file a bug on the arrow keys issues as I learn more about it.
