### ISSUE TITLE
[UI] 

### ISSUE THREAD

**Issue by cybertan** [rancher/rancher#6347]
**Rancher Version:**
v1.1.4
**Docker Version:**
1.10.3, build e03ddb8/1.10.3
**OS and where are the hosts located? (cloud, bare metal, etc):**
 bare metal
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
1: git clone https://github.com/rancher/ui.git
2: git checkout -b v1.1.14 v1.1.14
3: ./scripts/update-dependencies 
4: ./scripts/build-static -c 'winrancher.com'
5: run a nginx container using docker with the web dist dist/static
6: Change the value of http://my-rancher:8080/v1/settings/api.ui.index to //yourserver.com/latest
7: docker restart myrancherserver 
**Results:** 
the http://my-rancher:8080 cannot display correctly.
**Expected:**
the  http://my-rancher:8080  can work
![rancherserver](https://cloud.githubusercontent.com/assets/7135443/19556081/07f8159c-96f2-11e6-9cb9-e50b7db33f3f.jpg)

**Comment by vincent99** [comment]
The browser is blocking the responses from `winrancher.com` from being used, probably because it's a SSL request and the cert is not valid.
