### ISSUE TITLE
HAProxy loadbalancer support for regular expression path

### ISSUE THREAD

**Issue by eerootsus** [rancher/rancher#6348]
**Rancher Version: 1.1.4**
**Environment Type: Cattle**

Would love a possibility to define regular expression for HAProxy path rules. Currently all path definitions are set up as `path_beg` rules.

I suspect this happens here: `cattle/resources/content/config-content/haproxy/content/etc/haproxy/haproxy.cfg.ftl`

If so it seems quite an easy change. Either handle everything as a regular expression eg. `acl ${backend.uuid}_path path_reg -i ^${backend.portSpec.path}` or some style of syntax to differentiate between rules.

Sadly I need this quite shortly in my current project so I would be happy to fork if you point me to the right direction.

**Comment by nelsonomuto** [comment]
We need this asap!

**Comment by jamrizzi** [comment]
This would be so useful

**Comment by parin921996** [comment]
Really it will reduce the number of rules we need to put drastically.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

**Comment by codejamninja** [comment]
Make sense
