### ISSUE TITLE
API extends supports for adding ip,ip6,isolation and net-alias.  But they are not currently set in containers.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6349]
Rancher server version - v1.2.0-pre4-rc4 

Create Service API extends supports for creating serviced with ip,ip6,isolation and net-alias.  
But containers are not getting deployed with this option.

**Comment by StrongMonkey** [comment]
@deniseschannon  ip, ip6, and netalias require us to create a new isolated network. It need to be discussed as it is not as easy as passing the parameter to a container. Can you move this to 1.3? Isolation is just for windows container.
