### ISSUE TITLE
Rancher doesn't seem to obey Dockerfile HEALTHCHECK

### ISSUE THREAD

**Issue by sylvesterjakubowski** [rancher/rancher#6354]
**Rancher Version:**
`Latest.`
**Docker Version:**
`Docker version 1.12.1, build 23cf638`
**OS and where are the hosts located? (cloud, bare metal, etc):**
`Centos 7, Vmware.`
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
`Single node rancher.`
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
`Cattle`
**Steps to Reproduce:**
Create a container with a dockerfile with `HEALTHCHECK CMD exit 1;`
Will report unhealthy shortly.
**Results:** 
Rancher doesn't leverage the health state from docker. Container will never restart. 
**Expected:**
Rancher uses docker's health status in addition to it's own healthchecks.

With the new HEALTHCHECK in 1.12 you can do more than just port checking, and http 2xx/3xx codes.

Thanks. (rancher is pretty cool still...)

**Comment by aemneina** [comment]
@sylvesterjakubowski which version of rancher is this?

**Comment by sylvesterjakubowski** [comment]
`v1.1.4` thanks! @aemneina

**Comment by geertvanheusden** [comment]
Is this something that will be put back on the roadmap?

**Comment by aemneina** [comment]
@geertvanheusden have you tried this with the latest rancher? This is a docker image construct, right?

**Comment by geertvanheusden** [comment]
Hi @aemneina, didn't try it yet because the **milestone version** was updated to Unscheduled again...

**Comment by ecliptik** [comment]
Any updates on this? We ran into the issue with `HEALTHCHECK` in a container causing issues with Rancher 1.2, but are now on 1.5 and want to re-implement it.

It would be nice if the [Rancher Healthcheck](https://docs.rancher.com/rancher/v1.5/en/cattle/health-checks/) could do more than just http, and leverage the Docker [HEALTHCHECK](https://docs.docker.com/engine/reference/builder/#healthcheck) feature. Then you could get more than just a up/down status for a stack.

> A service is in the green (or “up”) state if all the containers implementing that service are in the green state, and alternatively, in the red (or “down”) state if all the containers are subsequently in the red state.

**Comment by vincent99** [comment]
Each container, service, and stack has a health state that bubbles up.  The stack state is just a summary of the lower levels.

Healthchecks also work for services in a leaf balancer, and check that they are reachable across multiple hosts.  Docker healthchecks would provide neither.

**Comment by Kemyke** [comment]
At least is it possible to show somehere the full docker status on the UI? I would like to see if the container docker status is Running (State: Starting) or Running (State: Healthy) as i can see it from the docker cli.

**Comment by vincent99** [comment]
No, we do not do anything with docker health checks.

**Comment by DaveOHenry** [comment]
+1 for this. The Rancher healthchecks are very limited. We have many containers that do not have a listening port, therefore no http / tcp connect is possible.
With Docker healthchecks we could just call a command to verify the healthiness of our application.

**Comment by superseb** [comment]
Merging this into https://github.com/rancher/rancher/issues/5790
