### ISSUE TITLE
Build not supported in catalog with build

### ISSUE THREAD

**Issue by JeanDaniel-Fischer** [rancher/rancher#6357]
Rancher Version: v1.1.0-dev4
Docker Version: 1.12.1
Using one host with rancher-server image launch and agent container on same machine

Is there anyway to support docker compose file with "build: ." from private catalog entry ?
According to this ((http://docs.rancher.com/rancher/v1.2/en/cattle/rancher-compose/build/) it is possible with s3. I have successfully connected to aws s3 within rancher-server container installing python awscli inside it but can't manage to make it work from rancher ui, i keep getting the following error:
time="2016-10-21T15:30:18Z" level=info msg="[uptime2:uptime-mongodb-service]: Created " eventId=09a1a9de-5f01-48e8-ba7d-dce2b19a08e1 resourceId=1e19
time="2016-10-21T15:30:18Z" level=info msg="[uptime2:uptime-server-service]: Creating " eventId=09a1a9de-5f01-48e8-ba7d-dce2b19a08e1 resourceId=1e19
time="2016-10-21T15:30:18Z" level=info msg="Creating service uptime-server-service"
time="2016-10-21T15:30:18Z" level=error msg="Failed Creating uptime-server-service : Build not supported"
time="2016-10-21T15:30:18Z" level=error msg="Failed to start: uptime-server-service : Build not supported"
time="2016-10-21T15:30:18Z" level=error msg="Stack Create Event Failed: Build not supported" eventId=09a1a9de-5f01-48e8-ba7d-dce2b19a08e1 resourceId=1e19

**Comment by aemneina** [comment]
hey @JeanDaniel-Fischer can you share the docker/rancher-compose.yml files you used here?

**Comment by deniseschannon** [comment]
@aemneina @JeanDaniel-Fischer Correct, build is not supported when launching catalogs as it's expected to be used with a local filesystem. Inside the rancher server container, we don't have support for build for services.
