### ISSUE TITLE
[go-rancher] client/generated_service.go returns nil error on error

### ISSUE THREAD

**Issue by cjworden** [rancher/rancher#6359]
client/generated_service.go inside of go-rancher contains the following function for retrieving a service by its ID. In the case of the if statement checking if the status code is 404 shouldn't an actual error be returned instead of nil so you can check for failure using the `if err != nil` pattern?

``` go
func (c *ServiceClient) ById(id string) (*Service, error) {
    resp := &Service{}
    err := c.rancherClient.doById(SERVICE_TYPE, id, resp)
    if apiError, ok := err.(*ApiError); ok {
        if apiError.StatusCode == 404 {
            return nil, nil
        }
    }
    return resp, err
}
```

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
