### ISSUE TITLE
api.auth.local.validate.description when set should be displayed as help text for password fields.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6362]
Rancher Version: v1.2.0-pre4-rc4

Steps to reproduce the problem:
Set api.auth.local.validate.url to the password valiator url and set api.auth.local.validate.description to some text indicating password length/format restrictions. 
Enable local auth.
api.auth.local.validate.description is not currenly used any where.

When adding new accounts/changing password for existing accounts , the contents of this settings should be used as helper text for the password fields.

**Comment by vincent99** [comment]
@westlywright Can you display the `api.auth.local.validate.description` setting if present as the help block under the password field for add/edit local account and change password.

Requires https://github.com/rancher/cattle/pull/2110/files for the setting to be readable, or add to the list manually yourself for now.

**Comment by sangeethah** [comment]
Tested with Rancher Version: v1.2.0-pre4-rc5
api.auth.local.validate.description is shown as helper text for password when creating new accounts, edit account/change password screens.
This helper text is still not shown when the system admin user gets created in "access control" page as part of enabling local auth.
Reopening this issue to get fixed in this work flow.

**Comment by vincent99** [comment]
@sangeethah This seems to have gotten lost a while ago when I marked to-test but forgot to send back..

**Comment by sangeethah** [comment]
Tested with v1.2.0-pre4-rc14
api.auth.local.validate.description content is shown as helper text for creation of admin users in "Access Control" page.
