### ISSUE TITLE
kubernetes stack fails to come up when started by an admin user who is not the owner of the environment.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6365]
Rancher server version: v1.2.0-pre4-rc4

Steps to reproduce the problem:
Create a local auth enabled setup.
Create an admin user - user1.

When logged in as admin user - user1 ,  try to start kubernetes from Infra catalog.
"system" flag for the kubernetes gets set to "false"
kubernetes stack fails to come up with following errors in kubernetes container:

```
10/21/2016 3:31:29 PM+ curl -s -u 052A2D860EE100C8E09F:4GARdBPbcnndZ3MyVenQSjpvTTaqvKDwEZRMrnZm -X POST null
10/21/2016 3:31:29 PM25edf090-9403-4cb3-950d-964b93487b48
10/21/2016 3:31:59 PM+ curl -s -f http://rancher-metadata/2015-12-19/stacks/Kubernetes/services/kubernetes/uuid
10/21/2016 3:31:59 PM++ curl -s http://rancher-metadata/2015-12-19/stacks/Kubernetes/services/kubernetes/uuid
10/21/2016 3:31:59 PM+ UUID=25edf090-9403-4cb3-950d-964b93487b48
10/21/2016 3:31:59 PM++ jq -r '.data[0].actions.certificate'
10/21/2016 3:31:59 PM++ curl -s -u 052A2D860EE100C8E09F:4GARdBPbcnndZ3MyVenQSjpvTTaqvKDwEZRMrnZm 'http://104.198.221.91:8080/v1/services?uuid=25edf090-9403-4cb3-950d-964b93487b48'
10/21/2016 3:31:59 PM+ ACTION=null
10/21/2016 3:31:59 PM+ KUBERNETES_URL=https://kubernetes.kubernetes.rancher.internal:6443
10/21/2016 3:31:59 PM+ '[' -n null ']'
10/21/2016 3:31:59 PM+ mkdir -p /etc/kubernetes/ssl
10/21/2016 3:31:59 PM+ cd /etc/kubernetes/ssl
```

**Comment by sangeethah** [comment]
The same issue is also seen when , member of an environment who is a user ( not "admin) , tries to deploy kubernetes template from Infra catalog.

**Comment by prachidamle** [comment]
@alena1108 questions:

steps to reproduce:
- try to start kubernetes from Infra catalog.
     Just checking - Is infra catalog going to go away? or is it getting replaced by some other catalog?
- "system" flag for the kubernetes gets set to "false"
     Who sets this flag and where is it read from?

**Comment by alena1108** [comment]
@deniseschannon is infra-catalog goes away? 

@prachi UI/rancher-cli set this flag. But you can as well test it manually by creating stack with system flag by owner/admin user.

**Comment by deniseschannon** [comment]
`infra-catalog` is replaced with `rancher-catalog`  and the same templates are in `infra-templates`

@prachidamle 

To test in rc6, 
```
1. set `library` to `https://github.com/rancher/rancher-catalog/` on the 1.2 branch  
2. remove the `infra` catalog
```

**Comment by sangeethah** [comment]
@prachi , The same issue is also seen when k8s automation script tries to start a K8s environment with client/admin client:
After using the following create_stack api (with system=True) , the system stack still gets created with system set to "false" and k8s system stack is not able to start successfully.

```
    env = client.create_stack(name=k8s_stackname,
                              dockerCompose=dockerCompose,
                              rancherCompose=rancherCompose,
                              environment=environment,
                              startOnCreate=True,
                              system=True)
```

**Comment by prachidamle** [comment]
Update so far is:
With the latest code, the observation is that, if a user is not "owner" of the environment, even if he is an admin, he cannot see the k8s templates in the catalog.

This list templates restriction is put by UI, by looking at the stack schema for that environment. If the schema lists the "system" flag as false, the templates are hidden. 
/v2-beta/projects/:id/schemas/stack is the schema checked by the UI.

Fix is to fix this schema to have the system flag as true for admins i.e - treat admins as owners.

@ibuildthecloud I could not find where we generate the role specific schemas. Can you provide pointers?

**Comment by sangeethah** [comment]
Tested with v1.2.0-pre4-rc8:

set up - local auth enabled setup.

Create environment -env1 using "cattle" template.
Add an admin user
As this admin user (who is not added as member to env1), able to add Kubernetes stack successfully. system flag is set on the stack as expected.
