### ISSUE TITLE
Validation tests take longer to run  in 1.2 pre releases

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6366]
Rancher Version: Builds from master

Validation tests take longer to run in v1.2.0-pre4 builds.They take about 3 hours and 15 minutes to execute. Until v1.2.0-pre3 builds , they were taking about 2 hours and 30 minutes.

In general every test suite seem to take a little longer then before.

**Comment by sangeethah** [comment]
With latest build from master , automation runs take ~4 hours to complete.

**Comment by sangeethah** [comment]
With the latest build from master - Nov/15 
Rancher Version: Build from master
rancher/dns:v0.10.5
rancher/healthcheck:v0.1.0
rancher/net:v0.7.0
rancher/metadata:v0.6.3
rancher/plugin-manager:v0.2.1
rancher/scheduler:v0.1.2

Validation run takes ~5 hours .

**Comment by deniseschannon** [comment]
@sangeethah I believe this is now fixed in 1.5.x with some networking fixes. Back to 2.5 hours.

**Comment by sangeethah** [comment]
Automation runs using 1.5.4 builds is taking ~2.5 hours to execute.
