### ISSUE TITLE
rancher cli: "./rancher catalog ls" fails to display the catalogs

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#6367]
Rancher Version:v1.2.0-pre4-rc4

Rancher CLI version: v0.3.0-rc3

OS and where are the hosts located? (cloud, bare metal, etc):: Cloud

Environment Type: (Cattle/Kubernetes/Swarm/Mesos): Cattle

Steps to Reproduce:
1. Create a rancher cli setup
2. Run the command ./rancher catalog ls

```
soumyas-MacBook-Pro:rancher-v0.3.0-rc3 soumya$ ./rancher catalog ls.
The command fails as below
NAME      CATEGORY   ID
FATA[0000] Invalid URL http://35.161.8.175:8080/v2-beta/schemas, must contain /v1 
```

**Comment by deniseschannon** [comment]
Verified fixed with Rancher CLI v0.4.0-rc1, and rancher in v1.2.0-rc2.
