### ISSUE TITLE
rancher cli: env create does not work with -o option 

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#6369]
Rancher Version:v1.2.0-pre4-rc4

Rancher CLI version: v0.3.0-rc3

OS and where are the hosts located? (cloud, bare metal, etc):: Cloud

Environment Type: (Cattle/Kubernetes/Swarm/Mesos): Cattle

Steps to Reproduce:
1. Create a rancher cli setup and use account API keys
2. Run the command "./rancher env create -o kubernetes newk8senv"

```
soumyas-MacBook-Pro:rancher-v0.3.0-rc3 soumya$ ./rancher env create -o kubernetes newk8senv
Incorrect Usage.
Create an environment

By default, an environment with cattle orchestration framework will be created. This command only works for Account API keys.

Example:

  $ rancher env create newEnv

To add an orchestration framework do TODO
  $ rancher env create -o kubernetes newK8sEnv
  $ rancher env create -o mesos newMesosEnv
  $ rancher env create -o swarm newSwarmEnv
Usage: rancher [global options] create [NEWENVNAME...]

FATA[0000] flag provided but not defined: -o            

```

**Comment by deniseschannon** [comment]
No longer use `-o`, but uses templates (ie `-t`)

```
./rancher env create -t kubernetes newk8stesting
```

Verified fixed with Rancher CLI v0.4.0-rc1, and rancher in v1.2.0-rc2.
