### ISSUE TITLE
Clustering Containers in Rancher with 10.42 Network

### ISSUE THREAD

**Issue by bscott** [rancher/rancher#637]
Hello,

I'm trying to cluster 3 Consul Servers using this example, [Github](https://github.com/progrium/docker-consul) across 3 Rancher Hosts. In the arguments for the container command that I'm using to launch the server, I must pass a [advertise](https://www.consul.io/docs/agent/options.html#_advertise) Address using the 10.42 address which is routable otherwise by default Consul uses the 172 address. 

How might I be able to statically define a 10.42 address for a container as it gets created after the container is already running. I've tried $RANCHER_IP and it's seems that ENV is empty right when the container starts. 

This might be a issue for any software needing a routable IP across hosts when the container is started.

**Comment by yogin** [comment]
I'm trying to do the same thing here, and was also wondering if `advertise` should be the container's IP or the host's IP? 

I'm mappings the exposed ports to the host, and since the host IP should be known when rancher starts the container, it might be easier to pass that down to the `docker-compose.yml` file? But couldn't find any information about this.

**Comment by cloudnautique** [comment]
@yogin, now that Rancher metadata service is available, you can query `/self/host/agent_ip` to get the host IP that rancher knows about. However, there is now a route53 service that can be deployed via catalog to make these types of updates.

**Comment by cloudnautique** [comment]
@bscott, not sure if you are still running into this one. I'm sure you have seen Rancher metadata, hopefully that addresses this. The one thing that we still need to address is IP reuse so that if a container drops off it can come back with the same IP.

**Comment by will-chan** [comment]
@alena1108 this is done right?

**Comment by alena1108** [comment]
@will-chan yes, you can read 10.42 ip address from metadata
