### ISSUE TITLE
Reverse proxy stuck at "Initializing"

### ISSUE THREAD

**Issue by Dremor** [rancher/rancher#6371]
I uses Rancher reverse proxy in order to serve 2 website (My Rancher instance, and a Gitlab instance), both being on the same server. The proxy works fine, but is stuck at "Initializing", preventing me to restart it as a service (I still can restart each individual container).

---

| Useful | Info |
| :-- | :-- |
| Versions | Rancher `v1.1.4` Cattle: `v0.165.8.4` UI: `v1.1.14` |
| Access | `localauth` `admin` |
| Orchestration | `Cattle` |
| Route | `hosts.index` |

**Comment by aemneina** [comment]
@Dremor can you collect the container logs for the reverse proxy and gitlab?

**Comment by aemneina** [comment]
I'll close this out, if you can provide logs feel free to reopen.
