### ISSUE TITLE
Misspelling in Rancher admin interface

### ISSUE THREAD

**Issue by pcgeek86** [rancher/rancher#6372]
Misspelled "dckoer-compose.yml" in UI, under "Add Project" page.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.1.4` Cattle: `v0.165.8.4` UI: `v1.1.14` |
|Access|`localauth` `admin`|
|Orchestration|`Swarm`|
|Route|`swarm-tab.projects.new`|

**Comment by pcgeek86** [comment]
![image](https://cloud.githubusercontent.com/assets/466713/19628919/fbe3d8da-991d-11e6-8576-2e473fae7959.png)

**Comment by vincent99** [comment]
https://github.com/rancher/ui/commit/931dae873f4a996ea2d0f2069fb579f422943876
