### ISSUE TITLE
Cannot see Kubernetes deployments  in Rancher UI

### ISSUE THREAD

**Issue by RahulMahale** [rancher/rancher#6373]
**Rancher Version:** :-  1.1.4

**Docker Version:** :-  1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):**  :- Ubuntu 15.10 Hosted on AWS EC2

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** :- Single node rancher with internal DB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** :-  Kubernetes

**Steps to Reproduce:**  : Check the Rancher UI

**Results:**  :- Cannot see deployment and replica sets in Rancher Dashboard
![rancherdeployment](https://cloud.githubusercontent.com/assets/1124617/19635088/76e6a9e4-99dd-11e6-87bf-6bee039ef499.png)

**Expected:** :- Should be able to manage the Kubernetes Deployment using Rancher Dashboard.

I can see and manage the deployments using the kubectl using following command

```
$ kubectl get deployments
NAME      DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
cl        2         2         2            2           4d
$ kubectl get rs
NAME            DESIRED   CURRENT   READY     AGE
cl-3155146318   0         0         0         4d
cl-3465072546   0         0         0         2d
cl-4198874562   2         2         0         2d
cl-900512661    0         0         0         3d
````

If I have to edit the deployment I need to do it using kubectl, there should be a way to manage it using dashboard as well.

**Comment by vincent99** [comment]
Deployments are in [Rancher] 1.2.x.
