### ISSUE TITLE
Saml: Logging in with SAML user creates a new environment with name "-Default"

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#6377]
**Rancher Version:**
Master image
**Docker Version:**
1.12.2
**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
cattle
**Steps to Reproduce:**

- Enable SAML Authentication
- Choose “Allow any valid User” as “Site Access”
- Login with any SAML user.

**Results:** 

A new environment is created for this user but with name "-Default" instead of "testuser3-Default"

**Comment by deniseschannon** [comment]
This is actually default behavior for all auth providers. If you aren't invited to any environments, we will create a default user environment for you.
