### ISSUE TITLE
Host labels (ie docker version) are not recognized on docker-machine created hosts (example swarm)

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#6379]
**Rancher Version:**: 1.2.0-pre4-rc5

**Docker Version:**:1.12.2

**OS and where are the hosts located? (cloud, bare metal, etc):**: Ubuntu, Cloud

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**Single node rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**: Cattle

**Steps to Reproduce:**
1. Create a 3 host set up 
2. Add the infra catalog with https://git.rancher.io/infra-catalog.git in qa branch(version v1.12-rancher0)
3. Launch the swarm catalog

**Results**
Swarm does not start up. No containers are created. 

<img width="1370" alt="screen shot 2016-10-24 at 12 22 04 pm" src="https://cloud.githubusercontent.com/assets/18536626/19660451/a75c6e86-99e4-11e6-9581-dcdc5c6dc0ef.png">

**Comment by deniseschannon** [comment]
I hit this issue when adding machines through the UI (docker-machine). Per @ibuildthecloud, it seems as if the hosts are not being recognized as having the label `io.rancher.host.docker_version=1.12` for its scheduling rule. 

Steps to Reproduce
1. Add 3 hosts using docker-machine (aka through the UI)
2. Try to launch the swarm catalog entry (please note that master and QA branch are the same entry so no need to switch the qa branch of infra-catalog)

Note: I did not hit any issue launching swarm with my 10 acre set up where hosts are NOT added through docker-machine. So therefore, it looks like a label scheduling issue

**Comment by deniseschannon** [comment]
Separate test for theory:

1. Add a host through UI
2. Schedule a service to launch based on host label `io.rancher.host.docker_version=1.12`, which is on the host. 

Result:
```
Activating (Failed to allocate instance [container:1i14]: Bad instance [container:1i14] in state [error]: Scheduling failed: needs host with label io.rancher.host.docker_version: 1.12)
```
Service cannot find a host with the label, even though a host exists with that label.

<img width="790" alt="screen shot 2016-10-24 at 8 01 59 pm" src="https://cloud.githubusercontent.com/assets/11410997/19671603/c6358154-9a24-11e6-9ae3-229703c4190d.png">

**Comment by alena1108** [comment]
@deniseschannon It is because allocator reads the labels from "labels" table, and for digital ocean host of yours, the labels table has only custom labels (set via cattle), and doesn't have labels that came with the host registration:

```
mysql> select * from host_label_map where host_id=8;
+----+------+------------+--------------+--------------------------------------+-------------+---------+---------------------+---------+-------------+------+---------+----------+
| id | name | account_id | kind         | uuid                                 | description | state   | created             | removed | remove_time | data | host_id | label_id |
+----+------+------------+--------------+--------------------------------------+-------------+---------+---------------------+---------+-------------+------+---------+----------+
| 13 | NULL |         22 | hostLabelMap | 6584fb74-c532-429f-bb45-50f2c9c30b97 | NULL        | created | 2016-10-25 02:53:53 | NULL    | NULL        | {}   |       8 |       75 |
+----+------+------------+--------------+--------------------------------------+-------------+---------+---------------------+---------+-------------+------+---------+----------+
1 row in set (0.00 sec)

mysql> select * from label where id=75;
+----+------+------------+-------+--------------------------------------+-------------+---------+---------------------+---------+-------------+------+------+------+-------+
| id | name | account_id | kind  | uuid                                 | description | state   | created             | removed | remove_time | data | type | key  | value |
+----+------+------------+-------+--------------------------------------+-------------+---------+---------------------+---------+-------------+------+------+------+-------+
| 75 | NULL |         22 | label | 46fd92bf-dfa3-4ccb-b12b-25202d32cfc3 | NULL        | created | 2016-10-25 02:53:53 | NULL    | NULL        | {}   | host | foo  | bar   |
+----+------+------------+-------+--------------------------------------+-------------+---------+---------------------+---------+-------------+------+------+------+-------+
1 row in set (0.00 sec)
```

@cjellick could you look at it? I'm not sure if it should be fixed so Allocator reads the labels from the "host" object, or we should fix the host registration to store the labels properly.

**Comment by soumyalj** [comment]
Tested with master. Added a digital ocean host through UI. Created a label with key value foo=bar on the host. Scheduled a service to be created on host with label "foo=bar". Container created successfully on the host.

**Comment by deniseschannon** [comment]
@soumyalj Please re-test. The specific use case was the fact that the automatically created host labels (e.g. docker/kernel versions) on a host were not being scheduled correctly for docker-machine hosts.

1. Add a host through DO. You must have hosts of different docker versions.
2. Schedule a service that must match the docker version label. 
3. Confirm that we only schedule on hosts that match the docker version.

Adding your own label has always worked fine.

**Comment by soumyalj** [comment]
Tested with master. Added a host with docker version 1.11. Scheduled a service to be created on a host with label ```io.rancher.host.docker_version = 1.11 ```. Service was created successfully on the host with the label as ```io.rancher.host.docker_version = 1.11 ```
<img width="885" alt="screen shot 2016-11-16 at 2 12 01 pm" src="https://cloud.githubusercontent.com/assets/18536626/20367945/99e2a0de-ac06-11e6-80f8-f63a3e54d950.png">
