### ISSUE TITLE
When Canceling upgrade of container, the previous settings are not used (broken persistant storage)

### ISSUE THREAD

**Issue by leroy0211** [rancher/rancher#6382]
**Rancher Version:** 1.1.4

**Docker Version:** 1.12.2

**OS and where are the hosts located? (cloud, bare metal, etc):** 
3 Virtual machines on bare-metal in VM-Ware Ubuntu server 14.04 (1 vm contains rancher, and 2 vm's are hosts)

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** 
Basic Rancher setup with 2 hostst, all running on same VM Ware

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle (default)

**Steps to Reproduce:**
Add and configure Convoy-NFS to the storage, create a volume
Upgrade a service to use this new volume (but put something wrong in the name)
Click on upgrade
Now you "discover" that someting was wrong, so cancel the upgrade
The upgrade is cancelled, but the volume setting was not removed. 
Click Finish upgrade. Now the service will try to respawn with the wrong settings. 

**Results:** 
Services which are "hanging" in a "Finishing upgrade" loop.  

**Expected:**
Previously applied settings to be removed, so that services can respawn with the previously working settings.

PS:
Current fix would be to clone a service and alter the volume settings. So the new service will spawn, and the old one can be deleted.

**Comment by deniseschannon** [comment]
After you cancel upgrade, you actually want to "rollback" as you still want to go back to your previous state. 

Finishing upgrading in a `cancelled-upgrade` state is still going forward with the upgrade. For v1.2.0, we've changed this state/options so it's less confusing.
