### ISSUE TITLE
Swarm kit removes label swarm=manager on the hosts after starting up the containers

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#6383]
Rancher Version:: 1.2.0-pre4-rc5

Docker Version::1.12.2

OS and where are the hosts located? (cloud, bare metal, etc):: Ubuntu, Cloud

Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)Single node rancher
Environment Type: (Cattle/Kubernetes/Swarm/Mesos): Cattle

Steps to Reproduce:
1. Create a 3 host set up using gce hosts
2. Add the infra catalog with https://git.rancher.io/infra-catalog.git in qa branch (version v1.12-rancher0)
3. Launch the swarm catalog

The swarm stack starts up initially with swarm=manager label, but after a few seconds, the swarm=manager label is removed automatically on two of the hosts but remains intact for the third host. Logs attached below.
[swarmhost1.txt](https://github.com/rancher/rancher/files/549261/swarmhost1.txt)
[swarmhost2.txt](https://github.com/rancher/rancher/files/549262/swarmhost2.txt)
[swarmhost3.txt](https://github.com/rancher/rancher/files/549263/swarmhost3.txt)

**Comment by LLParse** [comment]
This problem manifested as a result of our changing the hostname field in metadata to be a FQDN.

**Comment by LLParse** [comment]
https://github.com/rancher/infra-catalog/pull/29

**Comment by soumyalj** [comment]
Tested with 1.2.0-pre4-rc5 and the updated catalog  https://git.rancher.io/infra-catalog.git in qa branch. The swarm=manager label on the hosts do not get deleted. Swarm is functional.
