### ISSUE TITLE
Kubernetes "Add catalog" from stacks tab displays all the catalogs instead of just the K8s community catalogs

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#6384]
**Rancher Version:**v1.2.0-pre4-rc5

**Docker Version:**1.12.2

**OS and where are the hosts located? (cloud, bare metal, e`tc):**Ubuntu, Cloud

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**: Single node

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**: Kubernetes

**Steps to Reproduce:**
1. Create a Kubernetes environment using with infra catalog https://git.rancher.io/infra-catalog.git, qa branch(v1.4.0-rancher1)
2. From the stacks tab, click on "Add from catalog" 

**Results:** 
All the catalogs(including rancher NFS/EBS/EFS ) are displayed, but instead only Kubernetes community catalogs should be displayed

**Comment by vincent99** [comment]
The catalog also includes `infra` services that an environment owner should be allowed to deploy regardless of what orchestration is used for that environment.
