### ISSUE TITLE
Rancher cli docker exec exit code without -i

### ISSUE THREAD

**Issue by gyalai** [rancher/rancher#6385]
**Rancher Version:**
1.2.0-pre3, CLI 0.2.0 and CLI 0.3.0-rc3
**Docker Version:**
1.12
**OS and where are the hosts located? (cloud, bare metal, etc):**
bare metal, Ubuntu 16.04
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node Rancher with external DB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**

Make a shell script into the container with exit code, like 

`#!/bin/bash
exit 11`

Run `rancher docker exec container script`
**Results:** 
 Run 'echo $?' print 0
**Expected:**
It should print 11

If you run the command `rancher docker exec -i container script`. It returns with exit code 11.

The simple docker exec command support to run this without -i. It would be nice to have with rancher also because the Jenkins can not run script with -i with it's shall plugin.

**Comment by deniseschannon** [comment]
@gyalai Can try again with Rancher CLI v0.4.1 against Rancher v1.2.2?

**Comment by deniseschannon** [comment]
@gyalai If this is still an issue with the latest CLI, please re-open.
