### ISSUE TITLE
convoy efs not getting proper metadata

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#6387]
Opening this issue for tracking purposes

See: 
- https://forums.rancher.com/t/convoy-initializing-stuck/4350/4
- https://github.com/rancher/convoy-agent/pull/35

**Comment by superseb** [comment]
Closing this out, convoy is unsupported since v1.3+. Alternatives are Storage Service (http://rancher.com/docs/rancher/v1.6/en/rancher-services/storage-service/)
