### ISSUE TITLE
In a github blocked setup, Very first template to view any template from any catalog takes a very long time to load.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6388]
Tested with rancher-server version -- v1.2.0-pre4-rc5

In the rancher-server setup, I have blocked access to git.rancher.io by adding the following iptables rules:

```
iptables -I FORWARD -d <git.rancher.io>-j DROP
iptables -I FORWARD -s <git.rancher.io>-j DROP
```

Catalog gets presented to the user immediately from the cache.
The very first template to view any template from any catalog from UI takes about 2 mts to load. 
After this , every other template in that catalog will load immediately.
Expected Behavior:
It should be able to load the template details immediately from the cache.

**Comment by cjellick** [comment]
Moving out of 1.2. There a few simple work arounds:
- refresh the page that is loading slowly
- Add `-e DEFAULT_CATTLE_CATALOG_URL=""` (or a valid catalog url if blank wont do) to the `docker run ...rancher/server` command if you know you are going to be in an environment where that cannot be reached.

**Comment by mrajashree** [comment]
Cannot be tested until the next RC

**Comment by sangeethah** [comment]
Tested rancher-server version - v1.2.0-pre4-rc7.
This issue is not reproducible anymore.

There is no delay when viewing templates from catalog in a set up where github access is blocked.
