### ISSUE TITLE
Rancher-compose v2 a empty space instead of version number shows up in drop-down

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#6390]
**Rancher Version:** version 1.2.0-pre4-rc5

**Steps to Reproduce:**
1.  Create a catalog template that uses version: 2 in rancher and docker compose
2.  Add catalog and go to that template

**Results:** Version number is missing in drop-down, I can select the empty spot that it should be and the template is there.
![image](https://cloud.githubusercontent.com/assets/11514927/19701922/559623b6-9ab2-11e6-8932-dc95928e2460.png)

In the API it looks like this:
![image](https://cloud.githubusercontent.com/assets/11514927/19702348/f762ef2a-9ab3-11e6-9bd0-787e57b921c5.png)

**Expected:**  Should see the number

**Comment by mrajashree** [comment]
Seems to work if `.catalog` is included under services for v2

**Comment by deniseschannon** [comment]
Closing in favor of https://github.com/rancher/rancher/issues/6210. We should re-test after it's fixed.

**Comment by deniseschannon** [comment]
@mrajashree `.catalog` is now made for the root level of v2 compose files.

**Comment by tfiduccia** [comment]
Version - master 11/17
The root level works but the version is not showing up in drop-down.

**Comment by tfiduccia** [comment]
Looks like this may have been cause because in v1 for catalog we use .catalog and in v2 the . is not supported.  Please add . support so it's consistent?

**Comment by deniseschannon** [comment]
Added @tfiduccia QA catalog and was able to see all 4 versions in the v2 test catalog. 

Verified in v1.2.0-pre4-rc9
