### ISSUE TITLE
Using version: 2 in catalog causes only 1 version to show up

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#6391]
**Rancher Version:**version - 1.2.0-pre4-rc5

**Steps to Reproduce:**
1.  Create a catalog template with two versions
2.  Go to template in rancher

**Results:** Only the last version is showing up.  This could be related to #6390. 

**Expected:**  Should see all versions

**Comment by mrajashree** [comment]
Seems to work if `.catalog` is included under services for v2

**Comment by deniseschannon** [comment]
Closing in favor of https://github.com/rancher/rancher/issues/6210
