### ISSUE TITLE
Upgrade: Finish Upgrade text stays after you click it, until you refresh

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#6392]
**Rancher Version:** v1.2.0-pre4-rc5

**Steps to Reproduce:**
1.  Have a catalog template with at least 2 version
2.  Add the template version 1
3.  Click on upgrade available
4.  Upgrade to version 2
5.  Click on Upgrade: Finish Upgrade

**Results:** The upgrade finishes, but the button doesn't change it still says Upgrade: Finish Upgrade until you refresh the page (happens in stack detail and main stack page)
![image](https://cloud.githubusercontent.com/assets/11514927/19704065/23ccd196-9abb-11e6-9e16-1bfdd51899a0.png)

**Expected:**  Should switch to "Upgrade available" or "Up to date"

**Comment by mrajashree** [comment]
@tfiduccia I tried with the kubernetes template of infra-catalog, it had two versions
1) I clicked on upgrade available
2) then on upgrade
3) then without refresh it changed to `Upgraded`

**Comment by tfiduccia** [comment]
@mrajashree - not using kubernetes environment.  Just plain cattle with standard catalog template.

**Comment by mrajashree** [comment]
@vincent99 I don't think it's a catalog-service bug since the calls corresponding to upgrade and finishUpgrade go to `v2-beta/projects/1a5/stacks`.

**Comment by tfiduccia** [comment]
Version - master 11/06
Verified fixed
