### ISSUE TITLE
Rancher unable to add hosts when using SSL termination (in combination with the Azure Application Gateway)

### ISSUE THREAD

**Issue by kvaes** [rancher/rancher#6396]
**Rancher Version:** 1.1.4

**Docker Version:** 1.12.2

**OS and where are the hosts located? (cloud, bare metal, etc):** 
Rancher running on an Ubuntu host which is running on Azure 

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

Rancher is published to the outside world via an azure application gateway.
This has been done as the component to do the SSL terminitation/offloading.
Rancher is sitting behind this application gateway and is only accesible via the azure application gateway.

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

Cattle

**Steps to Reproduce:**

In the above setup, add a custom host ;

sudo docker run -d --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.0.2 https://demo.kvaes.be/v1/scripts/tokenA:tokenB

**Results:** 

The following messages are in the logs of the agent instance ; 

time="2016-10-25T20:07:43Z" level="fatal" msg="Reached max retry attempts for getting token."
time="2016-10-25T20:07:45Z" level="info" msg="Starting event router."
time="2016-10-25T20:07:45Z" level="info" msg="Watching state directory: /var/lib/rancher/state/containers"
time="2016-10-25T20:07:45Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=0 reportedUuid="9a3909ab-421a-4877-911d-3d455fba3408"
time="2016-10-25T20:07:46Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=1 reportedUuid="9a3909ab-421a-4877-911d-3d455fba3408"
time="2016-10-25T20:07:47Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=2 reportedUuid="9a3909ab-421a-4877-911d-3d455fba3408"
time="2016-10-25T20:07:48Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=3 reportedUuid="9a3909ab-421a-4877-911d-3d455fba3408"
time="2016-10-25T20:07:49Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=4 reportedUuid="9a3909ab-421a-4877-911d-3d455fba3408"
time="2016-10-25T20:07:50Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=5 reportedUuid="9a3909ab-421a-4877-911d-3d455fba3408"
time="2016-10-25T20:07:51Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=6 reportedUuid="9a3909ab-421a-4877-911d-3d455fba3408"
time="2016-10-25T20:07:52Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=7 reportedUuid="9a3909ab-421a-4877-911d-3d455fba3408"
time="2016-10-25T20:07:53Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=8 reportedUuid="9a3909ab-421a-4877-911d-3d455fba3408"
time="2016-10-25T20:07:54Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=9 reportedUuid="9a3909ab-421a-4877-911d-3d455fba3408"
time="2016-10-25T20:07:55Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=10 reportedUuid="9a3909ab-421a-4877-911d-3d455fba3408"
time="2016-10-25T20:07:56Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=11 reportedUuid="9a3909ab-421a-4877-911d-3d455fba3408"
time="2016-10-25T20:07:57Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=12 reportedUuid="9a3909ab-421a-4877-911d-3d455fba3408"
time="2016-10-25T20:07:58Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=13 reportedUuid="9a3909ab-421a-4877-911d-3d455fba3408"
time="2016-10-25T20:07:59Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=14 reportedUuid="9a3909ab-421a-4877-911d-3d455fba3408"
time="2016-10-25T20:08:00Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=15 reportedUuid="9a3909ab-421a-4877-911d-3d455fba3408"
time="2016-10-25T20:08:01Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=16 reportedUuid="9a3909ab-421a-4877-911d-3d455fba3408"
time="2016-10-25T20:08:02Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=17 reportedUuid="9a3909ab-421a-4877-911d-3d455fba3408"
time="2016-10-25T20:08:03Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=18 reportedUuid="9a3909ab-421a-4877-911d-3d455fba3408"
time="2016-10-25T20:08:04Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=19 reportedUuid="9a3909ab-421a-4877-911d-3d455fba3408"
time="2016-10-25T20:08:05Z" level="fatal" msg="Reached max retry attempts for getting token."
time="2016-10-25T20:08:07Z" level="info" msg="Starting event router."
time="2016-10-25T20:08:07Z" level="info" msg="Watching state directory: /var/lib/rancher/state/containers"
time="2016-10-25T20:08:08Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=0 reportedUuid="9a3909ab-421a-4877-911d-3d455fba3408"
time="2016-10-25T20:08:09Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=1 reportedUuid="9a3909ab-421a-4877-911d-3d455fba3408"
time="2016-10-25T20:08:10Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=2 reportedUuid="9a3909ab-421a-4877-911d-3d455fba3408"
time="2016-10-25T20:08:11Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=3 reportedUuid="9a3909ab-421a-4877-911d-3d455fba3408"
time="2016-10-25T20:08:12Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=4 reportedUuid="9a3909ab-421a-4877-911d-3d455fba3408"
time="2016-10-25T20:08:13Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=5 reportedUuid="9a3909ab-421a-4877-911d-3d455fba3408"
time="2016-10-25T20:08:14Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=6 reportedUuid="9a3909ab-421a-4877-911d-3d455fba3408"

**Expected:**

The host should have been added to the console

**Sidenote:**

The application gateway works, as I'm able to work with the management interface via this path.
Only 443 is accessible from the outside world on the url used for the registration (internet => internal).
The host is has full access to the outside world (internal => internet).
The Application Gateway is setup in a seperate subnet from the rancher host ("DMZ").

**Workaround:**

Publish the rancher node directly outside, via HTTP on port 8080... Though I don't accept this from a security point of view, as I want the sensitive information between master & nodes to be encrypted.

**Comment by kvaes** [comment]
Debugging attempt #2 ;
When I add an additional listener to the application gateway on port 80 => HTTP & No SSL Termination

Next up, I use http:// instead of https://, then it works (again) from a mgmt perspective. When I try to add the host, same situation as mention above...

When checking the logs of the agent, I do notice that the first part of the log doesn't shop anything odd when contacting the API. It's able to ;
- updating pyagent
- updating host-api
- updating agent-binaries
etc


026 12:31:26.871312   16131 manager.go:198] Version: {KernelVersion:4.4.0-38-generic ContainerOsVersion:Ubuntu 16.04.1 LTS DockerVersion:1.12.2 CadvisorVersion:0.23.2 CadvisorRevision:}
I1026 12:31:26.938558   16131 factory.go:217] registering Docker factory
E1026 12:31:26.938714   16131 manager.go:240] Registration of the rkt container factory failed: unable to communicate with Rkt api service: rkt: cannot tcp Dial rkt api service: dial tcp 127.0.0.1:15441: getsockopt: connection refused
I1026 12:31:26.938812   16131 factory.go:54] Registering systemd factory
I1026 12:31:26.944098   16131 factory.go:86] Registering Raw factory
I1026 12:31:26.948396   16131 manager.go:1072] Started watching for new ooms in manager
I1026 12:31:26.950521   16131 oomparser.go:185] oomparser using systemd
I1026 12:31:26.954174   16131 manager.go:281] Starting recovery of all containers
time="2016-10-26T10:31:27Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=0 reportedUuid="c7a8c543-44cf-46e2-8c10-c6790e20b573"
I1026 12:31:27.271004   16131 manager.go:286] Recovery completed
I1026 12:31:27.638154   16131 cadvisor.go:151] Starting cAdvisor version: 0.23.2- on port 9344
2016-10-26 10:31:27,887 ERROR agent [140206298332208] [event.py:112] Error in request : 3e779b70-33a5-426d-b080-a8fc09c9b5f8
Traceback (most recent call last):
  File "/var/lib/cattle/pyagent/cattle/agent/event.py", line 95, in _worker_main
    resp = agent.execute(req)
  File "/var/lib/cattle/pyagent/cattle/agent/__init__.py", line 15, in execute
    return self._router.route(req)
  File "/var/lib/cattle/pyagent/cattle/plugins/core/event_router.py", line 13, in route
    resp = handler.execute(req)
  File "/var/lib/cattle/pyagent/cattle/plugins/core/event_handlers.py", line 32, in execute
    type.on_ping(event, resp)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 125, in on_ping
    self._add_resources(ping, pong)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 272, in _add_resources
    resolved_ip = socket.gethostbyname(DockerConfig.docker_host_ip())
gaierror: [Errno -2] Name or service not known
time="2016-10-26T10:31:28Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=1 reportedUuid="c7a8c543-44cf-46e2-8c10-c6790e20b573"
time="2016-10-26T10:31:29Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=2 reportedUuid="c7a8c543-44cf-46e2-8c10-c6790e20b573"
time="2016-10-26T10:31:30Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=3 reportedUuid="c7a8c543-44cf-46e2-8c10-c6790e20b573"
time="2016-10-26T10:31:31Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=4 reportedUuid="c7a8c543-44cf-46e2-8c10-c6790e20b573"
time="2016-10-26T10:31:32Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=5 reportedUuid="c7a8c543-44cf-46e2-8c10-c6790e20b573"
time="2016-10-26T10:31:33Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=6 reportedUuid="c7a8c543-44cf-46e2-8c10-c6790e20b573"

**Comment by vincent99** [comment]
I'm not familiar with the Azure service, but this sounds like websockets aren't working.  Does the UI stay connected to `/v1/projects/<id>/subscribe` and show received frames?

**Comment by kvaes** [comment]
When I browse to it from a client (windows 10 / chrome), I'm able to load the page with the following source ;

<!DOCTYPE html>

<link rel="stylesheet" type="text/css" href="https://releases.rancher.com/api-ui/1.0.4/ui.min.css" />
<script src="https://releases.rancher.com/api-ui/1.0.4/ui.min.js"></script>
<script>
var user = "Personal Labo - kvaes";
var curlUser='${CATTLE_ACCESS_KEY}:${CATTLE_SECRET_KEY}';
var schemas="https://mgmt.kvaes.be/v1/projects/1a7/schemas";
//var docs = "http://url-to-your-docs/site";
var docJson = 'https://mgmt.kvaes.be/v1/projects/1a7/typedocumentations';
var data = 
{"type":"collection","resourceType":"subscribe","links":{"self":"https:\/\/mgmt.kvaes.be\/v1\/projects\/1a7\/subscribe"},"createTypes":{},"actions":{},"data":[],"sortLinks":{"eventNames":"https:\/\/mgmt.kvaes.be\/v1\/projects\/1a7\/subscribe?sort=eventNames"},"pagination":null,"sort":null,"filters":{"eventNames":null},"createDefaults":{}};
</script>

**Comment by kvaes** [comment]
When setting the host url back to the HTTP listener, I setup a tcpdump to see what was going on...

[screenshot01](https://i.imgsafe.org/0e60a242fa.png)
[screenshot02](https://i.imgsafe.org/0e60ba6c67.png)

**Comment by vincent99** [comment]
Open up the chrome dev tools -> network tab, reload the page, look for the subscribe request.  The status should be `101 Switching Protocols` and once you click on it have a Frames tab that shows at least a ping every 5 seconds.  If it says `200 OK` or something else then you're not establishing a websocket.  (The agent also uses websockets).

![image](https://cloud.githubusercontent.com/assets/753917/19737135/1e3be062-9b67-11e6-9c62-c12f6d29beb8.png)

**Comment by kvaes** [comment]
Looks good? (test with http over the application gateway)

<img width="1075" alt="2016-10-26 19_34_11-for follow up - karim vaes xylos com - outlook" src="https://cloud.githubusercontent.com/assets/10435278/19737364/74865dac-9bb3-11e6-84b4-54fed78d7c8e.png">
<img width="499" alt="2016-10-26 19_35_08-developer tools - http___mgmt kvaes be_" src="https://cloud.githubusercontent.com/assets/10435278/19737363/74830aa8-9bb3-11e6-8d53-265fe40d7424.png">

**Comment by aemneina** [comment]
Azures App Gateway doesn't play nice with websockets. I've run into this recently and reverted to their regular LB.

**Comment by kvaes** [comment]
@aemneina ; thanks for the tip, though websockets should be supported ... https://azure.microsoft.com/en-us/documentation/articles/application-gateway-websocket/

The disadvantage of the LB is that it can't do SSL offloading, which is something that is a feature lacking in Rancher itself.

**Comment by kvaes** [comment]
Out of curiosity, I tried all older versions up to the v1.0.0 release and all have the same effect.

**Comment by vincent99** [comment]
That does look fine from the browser side, I'm not sure why the agent connection has problems then, maybe the Go client uses a different version or extensions than browsers send.

**Comment by aemneina** [comment]
@kvaes can we reword the subject to Azure Application Gateway not working with rancher? That way we can change this to a feature request (assuming the issue is on ranchers side, and not the ALG).

**Comment by kvaes** [comment]
Updated

**Comment by kvaes** [comment]
It seems the Azure docs got an update on the Azure Application Gateway ;

https://docs.microsoft.com/en-us/azure/application-gateway/application-gateway-websocket

"Your backend must have a HTTP/HTTPS web server running on the configured port (usually 80/443) for WebSocket to work. This requirement is because WebSocket protocol requires the initial handshake to be HTTP with Upgrade to WebSocket protocol as a header field."

So running Rancher in the backend on port 8080 makes the application gateway do not so funky stuff in Websocket traffic.
I've tested this by deploying rancher with -p 80:8080 in the backend, and I see that this test lab is running stable. In the past my nodes would go into "reconnecting"-mode and now they seem to remain stable.
