### ISSUE TITLE
Rancher private catalog not working

### ISSUE THREAD

**Issue by DirkBrand** [rancher/rancher#6397]
**Rancher Version:** v1.1.4

**Docker Version:** 1.12.1

**OS and where are the hosts located? (cloud, bare metal, etc):** RHEL nodes in the cloud (Azure)

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** Single node rancher connected to 3 clustered hosts.

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:** I added a private catalog from bitbucket running with the rancher node in a private cloud.  I checked the docker logs and it seems to clone the repo from my bitbucket repo, but then it is inaccessible in the rancher UI. 

**Results:** 
Cannot see my catalog in the rancher UI.

The docker logs:
level=info msg="Cloning the catalog from git URL http://<internal_ip>:7990/scm/cap/docker-applications.git"
Cloning into './DATA/apps'...
level=error msg="Error v is not in dotted-tri format loading semver for version string v"
level=error msg="Error loading version with semver v is not in dotted-tri format"
level=error msg="Error v is not in dotted-tri format loading semver for version string v"
level=error msg="Error loading version with semver v is not in dotted-tri format"
.
.
.

**Expected:**
To see my catalog applications in the rancher UI or at least a more suitable error.

**Comment by aemneina** [comment]
@DirkBrand can you remove and readd the registry without prepending the http://

**Comment by DirkBrand** [comment]
@aemneina I fixed it by making my repository public, so that Rancher does not need to do authentication.  This is, however, not ideal, but it does work.

**Comment by aemneina** [comment]
Got it, I'll close this out.

**Comment by raeesaa** [comment]
Even I am not being able to access catalog saved as private repo. Any way to import it?
