### ISSUE TITLE
No hosts in storage pool after installing NFS-Convoy from catalog

### ISSUE THREAD

**Issue by boskiv** [rancher/rancher#6399]
**Rancher Version:**
1.2.0-pre4-rc4
**Docker Version:**
1.12.1
**OS and where are the hosts located? (cloud, bare metal, etc):**
vmware esxi vm's on ubuntu 16
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Swarm
**Steps to Reproduce:**
Setup NFS on Ubuntu server
Install Convoy-NFS from catalog (use /exports/rancho as Directory mount path and dns name as server name)
**Results:** 
No hosts in storage list
**Expected:**
![2016-10-26 13 46 18](https://cloud.githubusercontent.com/assets/1939783/19723291/4491fb54-9b83-11e6-94d8-072e9fa61172.png)
![2016-10-26 13 46 27](https://cloud.githubusercontent.com/assets/1939783/19723292/44945b92-9b83-11e6-80b2-65e4db5099ac.png)
![2016-10-26 13 49 15](https://cloud.githubusercontent.com/assets/1939783/19723290/448e2bc8-9b83-11e6-9f2f-0b9466f10ed6.png)

**Comment by boskiv** [comment]
I have upgraded to 1.2.0-pre4-rc5 but still no effect. As I remember in Cattle cluster I have no this issue.

**Comment by tfiduccia** [comment]
This is a duplicate #6097
