### ISSUE TITLE
503 Service Unavailable when trying to access Catalog or Machine Drivers

### ISSUE THREAD

**Issue by meons** [rancher/rancher#6400]
I have the following issue with Rancher 1.1.4. When I'm trying to access Catalog or Admin->Machine Drivers I always get a 503 Service Unavailable error. I see nothing about this 503 error in /var/lib/cattle/logs inside rancher-server container.

I'm confused because I have exactly the same installation on another host with same Docker version (1.12.2) and it works perfectly.

How can I fix that ?

---

| Useful | Info |
| :-- | :-- |
| Versions | Rancher `v1.1.4` Cattle: `v0.165.8.4` UI: `v1.1.14` |
| Access | `ldap` `admin` |
| Orchestration | `Cattle` |
| Route | `environments.index` |

**Comment by aemneina** [comment]
hey @meons does the docker logs for the rancher server container have any relevant output? What about docker daemon logs? They might provide clues, can you share those?

**Comment by meons** [comment]
Yop @aemneina, it's pretty strange because when I tryied again 1 hour later, it worked... I really don't understood what happened and I never got this issue again.
If it could help you, that's the only warning log (no error logs) in docker daemon log (/var/log/upstart/docker.log):
`.time="2016-10-26T13:24:39.379652115+02:00" level=warning msg="Running modprobe bridge br_netfilter failed with message: modprobe: WARNING: Module br_netfilter not found.\ninsmod /lib/modules/3.13.0-45-generic/kernel/net/llc/llc.ko \ninsmod /lib/modules/3.13.0-45-generic/kernel/net/802/stp.ko \ninsmod /lib/modules/3.13.0-45-generic/kernel/net/bridge/bridge.ko \n, error: exit status 1"`
And there is docker container logs in relation with catalog:
`time="2016-10-26T12:06:51Z" level=error msg="Failed to pull the catalog from git repo https://github.com/rancher/rancher-catalog.git, error: exit status 1"
time="2016-10-26T12:06:51Z" level=error msg="Git pull for Catalog library failing with error: exit status 1 "
time="2016-10-26T12:11:54Z" level=error msg="Failed to pull the catalog from git repo https://github.com/rancher/community-catalog.git, error: exit status 1"
time="2016-10-26T12:11:54Z" level=error msg="Git pull for Catalog community failing with error: exit status 1 "
time="2016-10-26T12:21:54Z" level=error msg="Failed to pull the catalog from git repo https://github.com/rancher/rancher-catalog.git, error: exit status 1"
time="2016-10-26T12:26:54Z" level=error msg="Failed to pull the catalog from git repo https://github.com/rancher/community-catalog.git, error: exit status 1"`

**Comment by aemneina** [comment]
on your server host, can you curl https://github.com? does that require a proxy to get out? Looks like access is blocked.

**Comment by meons** [comment]
Hmm nope I don't think that was a proxy or firewall issue because it worked later without any change.

**Comment by aemneina** [comment]
so this is no longer an issue for you?

**Comment by aemneina** [comment]
closing this out...

**Comment by meons** [comment]
Sorry fot the late reply @aemneina. Yes you can close this issue. Thank you
