### ISSUE TITLE
OpenLDAP: Can't add groups to evironments

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#6402]
**Rancher Version:**
master image (26 Oct)
**Docker Version:**
1.12.2
**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
- Enable LDAP authentication
- Go to manage environments
- Add a valid group as a member of any environment.

**Results:** 
getting `Identity not found: group-name` error.

**Expected:**
The group to be added.

**Comment by prachidamle** [comment]
Use groups class as 'groupOfNames' and test.

**Comment by galal-hussein** [comment]
tested with 'groupOfNames' and worked, thanks!
