### ISSUE TITLE
Deletion of service/rc/pods within a namespace is unsuccessful through UI

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#6405]
**Rancher Version:**v.1.2.0-pre4-rc5

**Docker Version:**1.12.2

**OS and where are the hosts located? (cloud, bare metal, etc):**Ubuntu, Cloud

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**Single node

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**Kubernetes

**Steps to Reproduce:**
1. Create a Kuberentes(1.4.4) set up with infra catalog qa branch
2. Create service/rc/pods within a namespace "test"
3. Delete the service/rc/pod through UI

The service/rc/pods created within a namespace do not get deleted. 

```
UI Error:
Error deleting
Cannot read property 'exitCode' of undefined
```

```
API error:
{"exitCode":1,"stdOut":"","stdErr":"Error from server: replicationcontrollers \"k8testrc1\" not found\n","error":{"Stderr":null}}
```

**Comment by danielschlegel** [comment]
I have exactly the same issue with rancher 1.2 final.

**Comment by adaughterson** [comment]
Same 1.2.0
Is there a manual workaround I can employ to remove the unwanted pod outside of the UI?

**Comment by rezonant** [comment]
You can still delete the pod via the Kubectl user interface or kubectl on your local machine with `kubectl delete pod <pod-name>`

**Comment by electrical** [comment]
I've hit the same problem. Would be nice if it could be solved in a dot release. ( 1.2.1 )

**Comment by vincent99** [comment]
@rezonant 1.3 is not months away.

@alena1108 It looks like handling the `defaultNamespace` doesn't work anymore.  Deleting something in the default NS works, in another one says not found.

**Comment by alena1108** [comment]
@soumyalj please test with kubectld image rancher/kubectld:v0.5.1 (last build in vnext branch, the one with skydns and helm)

**Comment by soumyalj** [comment]
Tested with rancher 1.3.0-rc1 with Kubernetes template v1.5.1-rancher1-1. Deletion of services/rc/pods within a namespace is successful through UI.
