### ISSUE TITLE
upgrades from catalog ignore upgrade_strategy

### ISSUE THREAD

**Issue by pschrammel** [rancher/rancher#6407]
**Rancher Version:** 1.12

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node, external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
cattle

**Steps to Reproduce:**

excerpt from rancher-compose.yml of a catalog entry:
haproxy:
  scale: 1
  upgrade_strategy:
    start_first: true
    batch_size: 20

**Results:** 

the upgrade ignores any setting in upgarde_strategy

**Expected:**

should behave like rancher-compose CLI or at least the stack should remember how the last upgrade was done and run the next upgrade the same.

**Comment by aemneina** [comment]
are you using rancher-compose to upgrade the catalog item? if so whats the command youre using?

**Comment by superseb** [comment]
@pschrammel Thanks for reporting. Could you please try to reproduce and if so, report a new issue with used Rancher and rancher-compose versions?
