### ISSUE TITLE
Update the gif for "Rancher Scheduler" template

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6410]
Rancher Server version - From master
Infra catalog - https://github.com/rancher/infra-catalog.git from branch 1.2
"Rancher Scheduler" template from Infra catalog has "Rancher NFS" gif.

**Comment by deniseschannon** [comment]
@sangeethah This is fixed in the new `infra-templates` folder in the `library` catalog. I don't believe you'll be able to see it until the next RC

**Comment by sangeethah** [comment]
Tested with library catalog - https://github.com/rancher/rancher-catalog.git from branch 1.2.
 "Rancher Scheduler" template has the correct gif now.
