### ISSUE TITLE
Services in "Upgraded" state do not restart crashed containers

### ISSUE THREAD

**Issue by ebr** [rancher/rancher#6411]
**Rancher Version:**
1.1.2

**Docker Version:**
1.12.1

**OS and where are the hosts located? (cloud, bare metal, etc):**
AWS, Ubuntu 16.04

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node, ext db

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
- Create a service (in our case: globally scheduled, restart Always, but not really important).
- Upgrade the service.
- Leave it in "Upgraded" state and wait for some event that causes the process inside container to exit. E.g. a NodeJS runtime error.

**Results:** 
Container stays in the "stopped" state

**Expected:**
Container is restarted.

(I could not find another issue open about this; if one does exist, sorry about the duplicate)

**Comment by deniseschannon** [comment]
Is there a reason why you're leaving your service in upgraded state versus finishing the upgrade so the service is in `Active` state?

**Comment by ebr** [comment]
This is an easy rollback route in case we see issues with the upgraded service. Someone (anyone) can just go in and click "rollback" at a moment's notice, as opposed to trying to find and deploy a previous version of the image.

Currently, as a matter of policy, no one is supposed to leave an `Upgraded` service unattended. But this is not reliable, as there may be a myriad of reasons a service is left as `Upgraded` anyway (mostly by omission, due to distraction, etc). We've had a couple of serious downtime incidents due to this, especially because this behaviour is totally not obvious, so it took a few incidents before we noticed the pattern.

**Comment by will-chan** [comment]
Perhaps we can add an option to automatically move the state to "Upgraded" when you perform the upgrade process.

**Comment by ebr** [comment]
it would be good if the upgraded container inherited the restart policy while still providing a rollback option.
alternatively, an auto-rollback (after n restarts within t seconds?) would be also nice. but sounds more complicated.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
