### ISSUE TITLE
Spread containers by default if there is no resource request

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#6412]
**Rancher Version:** master 10/27

**Comments:** 
Currently if resource based scheduling is on but no cpu or memory resource is given, container placement is random.  We should spread containers by default in this instance.

**Comment by cjellick** [comment]
@tfiduccia I'm assigning back to you since you opened, but feel free to assign to @sangeethah since she's done the scheduler testing

**Comment by tfiduccia** [comment]
I did a quick test that three services spread evenly.  But not sure what else I would test here, so sending to you per Craig.

**Comment by sangeethah** [comment]
Tested with rancher/scheduler:v0.1.2 . When deploying containers with no reservation requirements , containers get distributed equally across all the nodes in the host.
