### ISSUE TITLE
Swarm container is stuck in initializing state after the swarm manager is powered OFF and powered ON

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#6413]
**Rancher Version:**v1.2.0-pre4-rc5

**Docker Version:**v1.12.3/1.12.2

**OS and where are the hosts located? (cloud, bare metal, etc):**Ubuntu, Cloud

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**Single node

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**Swarm

**Steps to Reproduce:**
1. Create a swarm setup with 4 hosts (3 manager setup)
2. Create a few services using "docker service create"
3. Power OFF a manager, the worker node becomes a manager
4. Power ON the old manager host

**Results**
Swarm container does not startup on the host which was just powered ON

**Expected**
The container should come up successfully and it should be demoted to a worker node.

**Comment by LLParse** [comment]
Context: Old manager came back online, was unable to communicate with the other managers (since it was removed) and got stuck in a `pending` state:
```
Swarm: pending
 NodeID: c9cgm9mh7v6h584jg548pb6rn
 Error: rpc error: code = 4 desc = context deadline exceeded
 Is Manager: true
```
We should add logic to detect nodes stuck in `pending` state. After a certain period of time passes, force remove it from the swarm.

**Comment by LLParse** [comment]
Further notes: sometimes `docker swarm leave --force` will timeout due to known deadlock issues. In this scenario, our automation will not be able to repair the host and should notify the user by setting a label on the bad host: `swarm=deadlock`

**Comment by LLParse** [comment]
https://github.com/rancher/rancher-catalog
1.2 branch

**Comment by deniseschannon** [comment]
now available on master branch

**Comment by soumyalj** [comment]
Tested with rancher release v1.2.1 using docker 1.12.5 hosts. Still see the issue. The swarm container does not startup on the host which was powered ON. It is in a deadlock trying to leave swarm.
```
12/19/2016 3:42:34 PMtime="2016-12-19T23:42:34Z" level=info msg="Listening on port: 2378"
12/19/2016 3:42:54 PMrpc error: code = 4 desc = context deadline exceeded
12/19/2016 3:42:54 PMRetrying set host label swarm=wait_leaving
12/19/2016 3:42:55 PMRetrying set host label swarm=wait_leaving
12/19/2016 3:42:55 PMRetrying set host label swarm=wait_leaving
12/19/2016 3:42:56 PMRetrying set host label swarm=wait_leaving
12/19/2016 3:42:56 PMFailed to set host label swarm=wait_leaving (5 tries)
12/19/2016 3:43:19 PMtime="2016-12-19T23:43:19Z" level=info msg="Listening on port: 2378"
12/19/2016 3:43:39 PMrpc error: code = 4 desc = context deadline exceeded
12/19/2016 3:43:39 PMSet host label swarm=wait_leaving
12/19/2016 3:43:39 PMLeaving old swarm
12/19/2016 3:44:09 PMError response from daemon: context deadline exceeded
12/19/2016 3:44:09 PMSet host label swarm=deadlock
12/19/2016 3:44:09 PMDeadlocked trying to leave swarm. Please restart Docker daemon.
12/19/2016 3:49:12 PMtime="2016-12-19T23:49:12Z" level=info msg="Listening on port: 2378"
12/19/2016 3:49:13 PMDeleted host label swarm
```
Need the deadlock fix from docker.

**Comment by LLParse** [comment]
Looks like this is fixed in Docker 1.13.0, which is slated for release on 2017-01-10.
https://github.com/docker/docker/issues/29180

**Comment by deniseschannon** [comment]
@soumyalj Please re-test with Docker 1.13.0

**Comment by soumyalj** [comment]
Tested on v1.5.0-alpha1 with Docker 1.13.0 following the steps below:

1. Create a swarm setup with 4 hosts (3 manager setup). Used digital ocean hosts. 
2. Create a few services using "docker service create"
3. Power OFF a manager, the worker node becomes a manager
4. Power ON the old manager host

Swarm container starts up correctly on the host which was just powered ON(old manager host)
and is demoted to a worker node as expected.
