### ISSUE TITLE
Spelling error under add project in gui - dcoker

### ISSUE THREAD

**Issue by roffe** [rancher/rancher#6416]
**Rancher Version:**
1.1.4

Spelling error in the frontend-ui

says dcoker-compose.yml under add project

<img width="372" alt="screen shot 2016-10-28 at 11 41 56" src="https://cloud.githubusercontent.com/assets/5434736/19802357/939a6368-9d03-11e6-9b13-df094d124710.png">

**Comment by tfiduccia** [comment]
Version - v1.2.0-pre4-rc6
This was fixed in newer versions quite a while ago.
