### ISSUE TITLE
Impossible to start kubernetes cluster on azure

### ISSUE THREAD

**Issue by AlexGrs** [rancher/rancher#6417]
**Rancher Version:**
Rancher v1.1.4
User Interface  v1.1.14
Rancher Compose v0.8.6

**Docker Version:**
Docker version 1.12.3, build 6b644ec

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04 - Azure A2 machine - Resource Group

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node Rancher (used for testing purpose)

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
- Add a new Kubernetes environment in Rancher 
- Add a new VM in azure resource group ( same resource group where rancher machine is installed)
- In rancher, go to Add Host -> Custom and copy and paste the command in the terminal of the new VM created
- Service begin to be created but stuck at 7/9

**Results:** 

No logs in kubelet and proxy. So it's impossible to get any information about the origin of the problem.

![capture d ecran 2016-10-28 a 12 58 28](https://cloud.githubusercontent.com/assets/12913892/19804387/41cddc30-9d0e-11e6-82cd-503e081a3c74.png)

**Expected:**
kubelet and proxy containers should be able to start to create an available Kubernetes Cluster on Azure.

**Comment by timbordemann** [comment]
Same here, although not on Azure. I try to build a kubernetes cluster on KVM and RancherOS 0.70, but the kubernetes-proxy- and kubelet-containers are stuck. Since there are no logs it's very hard to debug.

**Comment by aemneina** [comment]
@AlexGrs can you share the output from the etcd logs?

**Comment by aemneina** [comment]
@AlexGrs also k8s 1.2.4 requires docker 1.10.3... it also looks like the host is registered with its public ip address, rather than the private IP, subjecting it to restrictive firewall rules. If you reregister your hosts with internal ip addresses you'd have better luck.

**Comment by aemneina** [comment]
@timbordemann ROS 0.7.0 uses a more modern version of docker than what rancher 1.1.4's version of k8s (1.2.4) supports. You should be able to either downgrade user docker in ROS or go with ROS 0.4.5... let me know if that gets you up and running. I'll close this out for now, if you guys have further issues after aligning versions, feel free to reopen or open a new issue.

**Comment by cloudnautique** [comment]
In ROS 0.7.0 you can do:

 ```
#cloud-config
rancher:
   ...
   docker:
      engine: docker-1.10.3
  ...
```

To swap User Docker versions.
