### ISSUE TITLE
Docker ps hangs when convoy-nfs cannot mount a volume

### ISSUE THREAD

**Issue by Chris7** [rancher/rancher#6419]
**Rancher Version:**
1.1.4

**Docker Version:**
1.12.2

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 14.04 VM in OpenNebula cloud

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
This is a slightly strange bug as it is not quite "reproducible" but I have encountered this a few times.
0) Have some network problem maybe. Not sure what the initial event is that starts this.
1) Start a container that needs a volume in convoy-nfs

**Results:** 
Here is the output from docker events:

```
2016-10-28T13:08:52.817272208Z image pull louvre:5000/jupyterhub:staging (name=louvre:5000/jupyterhub)
2016-10-28T13:08:55.835965617Z container create fe497b8fe1089368904ac8137e2f5c34bba2aa3b9f82bd37eaaca6b3abad0911 (image=louvre:5000/jupyterhub:staging, io.rancher.container.ip=10.42.211.208/16, io.rancher.container.name=jupyter-staging_jupyter_1, io.rancher.container.pull_image=always, io.rancher.container.uuid=2826305e-9be5-4d19-96db-b1b962ef3e56, io.rancher.project.name=jupyter-staging, io.rancher.project_service.name=jupyter-staging/jupyter, io.rancher.scheduler.global=true, io.rancher.service.deployment.unit=bfb4a323-d4a3-4ea1-9b1f-73cd8a5313bc, io.rancher.service.launch.config=io.rancher.service.primary.launch.config, io.rancher.service.requested.host.id=15, io.rancher.stack.name=jupyter-staging, io.rancher.stack_service.name=jupyter-staging/jupyter, name=r-jupyter-staging_jupyter_1)
2016-10-28T13:08:55.912775175Z network connect e22ac04559dfeb24af389e5f5ff7db3e467a7c5cfb79bca146975170070cabf8 (container=fe497b8fe1089368904ac8137e2f5c34bba2aa3b9f82bd37eaaca6b3abad0911, name=bridge, type=bridge)
```

Here is the log from convoy-NFS:

```
10/28/2016 9:08:55 AMtime="2016-10-28T13:08:55Z" level=debug msg="Handle plugin mount volume: POST /VolumeDriver.Mount" pkg=daemon
10/28/2016 9:08:55 AMtime="2016-10-28T13:08:55Z" level=debug msg="Request from docker: &{jupyter-staging-secrets map[]}" pkg=daemon
10/28/2016 9:08:55 AMtime="2016-10-28T13:08:55Z" level=debug msg="Mount volume: jupyter-staging-secrets for docker" pkg=daemon
10/28/2016 9:08:55 AMtime="2016-10-28T13:08:55Z" level=debug msg= event=mount object=volume opts=map[MountPoint:] pkg=daemon reason=prepare volume=jupyter-staging-secrets
```

**Expected:**
A running container. On the host, docker ps is unresponsive. The only way I have found to fix this is to restart the docker daemon.

**Comment by aemneina** [comment]
@Chris7 can you share the output of the docker logs? Sounds like docker could have crashed on or before this point.

**Comment by Chris7** [comment]
Could you be more specific to what logs you are referring to?

**Comment by aemneina** [comment]
Looking for the docker daemon log file output, possibly here: '/var/log/upstart/docker.log'

**Comment by aemneina** [comment]
@Chris7 I'd also be interested to know if this works with docker 1.10.3...

**Comment by aemneina** [comment]
@Chris7 feel free to reopen with the details requested.

**Comment by Chris7** [comment]
I cannot reopen this. But here is the info:

```

**Comment by machi1990** [comment]
I am running through the same problem in my environment and the only solution I have right now is to restart the docker daemon. @Chris7 @aemneina did you find  anything interesting regarding this? 
Thanks

**Comment by aemneina** [comment]
@machi1990 whats the output for your `docker info` on the hosts that have this issue?

**Comment by machi1990** [comment]
`Containers: 9
 Running: 8
 Paused: 0
 Stopped: 1
Images: 29
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 401
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host overlay null bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 4.4.0-51-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.905 GiB
Name: HOST2
ID: xxxxxx
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8`

That's the sample output from one of my hots..

**Comment by Chris7** [comment]
I have found a way to recover the host without restarting docker -- restart the container running the `volume-agent-nfs` command.

**Comment by machi1990** [comment]
@Chris7 the problem is detecting/knowing when the docker daemon hangs. In my case, the application I was running was passing the health-check. I have changed the plugin from convoy-nfs to rancher-nfs, will see how this one behaves.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
