### ISSUE TITLE
UI shows "Creating Kubernetes system stack.." page and no access to pods/rc/kubectl shell even after k8s system stack is deployed successfully.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6424]
UI shows "Creating Kubernetes system stack.." page and no access to pods/rc/kubectl shell even after k8s system stack is deployed successfully.

Steps to reproduce the problem:
Create an environment template with K8s service enabled.
Add an environment with this template.
K8s system stack comes up successfully in this environment. 
But UI continues to show "Creating Kubernetes system stack.." page and no access to pods/rc/kubectl shell even after k8s system stack is deployed successfully.

<img width="1298" alt="screen shot 2016-10-28 at 10 28 24 am" src="https://cloud.githubusercontent.com/assets/4266958/19815818/76bdd342-9cf9-11e6-83eb-d1fafad6b2f2.png">

**Comment by vincent99** [comment]
Updated to find stack with the appropriate templateBase+name instead of more specific exact `externalId` (also Mesos and Swarm)

**Comment by sangeethah** [comment]
Tested with latest build from master.
This issue is not seen anymore.
