### ISSUE TITLE
grid lines are missing on main and detail service pages

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#6425]
**Rancher Version:** v1.2.0-pre4-rc6

**Steps to Reproduce:**
1.  Add a catalog that will add a bunch of services

**Results:** Notice the grid lines for the bottom two services are missing.  Also when it's done, it makes the last service both grey and white.
![image](https://cloud.githubusercontent.com/assets/11514927/19816853/d8b2e142-9cfd-11e6-9a17-32ae1f6c2f0b.png)
![image](https://cloud.githubusercontent.com/assets/11514927/19816913/18e94990-9cfe-11e6-8226-453f7456bc8b.png)

**Expected:**  Should always see the grid line and shouldn't be white and grey

**Comment by westlywright** [comment]
Tested on master on 11-08-16 and could not reproduce. 
<img width="152" alt="screenshot 2016-11-08 09 14 17" src="https://cloud.githubusercontent.com/assets/858614/20106888/de514ae6-a593-11e6-99a5-d72c5702b547.png">

**Comment by vincent99** [comment]
It's still there, some sort of rendering glitch with the browser while there are CSS animations going on in that column.

**Comment by westlywright** [comment]
@vincent99 thanks that's helpful

**Comment by tfiduccia** [comment]
Version - master 11/10
Verified fixed
