### ISSUE TITLE
Host detail page constantly throwing error in development tools

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#6426]
**Rancher Version:** v1.2.0-pre4-rc6

**Steps to Reproduce:**
1.  Open dev tools
2.  Go to host detail page

**Results:** Error is constantly throwing.
ember.prod.js:18000 Uncaught TypeError: Cannot read property 'indexOf' of undefined(…)

**Expected:**  Shouldn't have error.

**Comment by vincent99** [comment]
I think this is the same as https://github.com/rancher/rancher/issues/6498 , stats coming back with no `id`.

**Comment by tfiduccia** [comment]
Version - master 11/06
Verified fixed

**Comment by natami** [comment]
Is this fix available in pre4-rc7?

- I'm still seeing massive TypeError: Cannot read property 'indexOf' of undefined and Uncaught TypeError: Cannot read property 'outlets' of undefined(…)

**Comment by deniseschannon** [comment]
@natami This fix is v1.2.0-pre4-rc11, but we don't recommend using RC versions. These are for our internal testing purposes.
