### ISSUE TITLE
Swarm logs should be shortened

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#6429]
**Rancher Version:**v.1.2.0-pre4-rc5

**Docker Version:**1.12.2/1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):**Ubuntu, Cloud

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**Swarm

**Steps to Reproduce:**
1. Create a swarm setup with 3 hosts [version v1.12-rancher0]
2. Obtain the logs from the hosts.

The logs are very huge and difficult to use them.

**Comment by LLParse** [comment]
https://github.com/rancher/rancher-catalog
1.2 branch

**Comment by deniseschannon** [comment]
now available on master branch

**Comment by soumyalj** [comment]
Verified with v1.2.0 [Swarm template version v1.12.3].  The ```set -x``` flag is removed in the logic which logs every script line executed. The logs are brief now.
