### ISSUE TITLE
Swarm container is stuck in initializing state when the manager is turned OFF

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#6432]
Rancher Version:: 1.2.0-pre4-rc5

Docker Version::1.12.3

OS and where are the hosts located? (cloud, bare metal, etc):: Ubuntu, Cloud

Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)Single node rancher
Environment Type: (Cattle/Kubernetes/Swarm/Mesos): Swarm

Steps to Reproduce:
1. Create a 4 host Swarm set up using Digital Ocean hosts with CATTLE_AGENT_IP=Internal IP(Swarm version v1.12-rancher0)
Ensure the set up is swarm with 3 managers and one worker node
2. Power off one manager. 
3. The container on the 4th host should become a manager, but it is stuck in initializing state. 

**Expected:**
Once the power is turned off on the manager host, the worker node should become the manager.
Swarm should be functional.

**Comment by LLParse** [comment]
In this scenario, we observed a functional swarm with 2 managers. Our automation executed a `docker promote` on the worker. It became unresponsive and `docker info` returned swarm status `pending` with reason `context deadline exceeded`. There was no indication in the logs why the functional worker locked up during the promotion.

**Comment by LLParse** [comment]
https://github.com/rancher/rancher-catalog
1.2 branch

**Comment by deniseschannon** [comment]
now available on master branch

**Comment by soumyalj** [comment]
Tested on v1.2.0 with digital ocean hosts(Docker 1.12.2) with CATTLE_AGENT_IP = Internal IP on a 4 host setup. After a manager host was turned off, the worker node was promoted to Manager node. The swarm container on the worker node was deleted and a new container was created in the process.
