### ISSUE TITLE
Quick Start Guide doesn't work if the Docker Host's /etc/resolv.conf specifies the search parameter

### ISSUE THREAD

**Issue by stefanlasiewski** [rancher/rancher#6440]
**Summary:**

The "Quick Start Guide" provided at http://docs.rancher.com/rancher/v1.2/en/quick-start-guide doesn't work at some environments, due to how Docker or Rancher handles /etc/resolv.conf from the host. At many organizations, /etc/resolv.conf will commonly list the organization's domain in the `search` list parameter, like so.

```
[rancher1 ~]$ cat /etc/resolv.conf
search example.org
```

However, this common configuration will break the examples used by the Quick Start Guide.

Workarounds are possible, but each workaround is rather ugly and sort of a rough introduction to the elegance of containers.

As someone new to Rancher, I don't really know what the correct fix would be. There are a couple bugs which already talk about /etc/resolv.conf, like #5351 #3572 & #3460.

But this ticket is about the Getting Started Guide which doesn't work out of the box. The Guide, and possibly and the Rancher Documentation, should include a caveat about the proper configuration for the host's /etc/resolv.conf .

**Rancher Version:**

1.1.4

**Docker Version:**

1.12

**OS and where are the hosts located? (cloud, bare metal, etc):**

CentOS 6. Bare metal & VMware VMs.

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

HA Rancher, external DB.

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

Cattle

**Steps to Reproduce:**
1. Install OS & Docker onto a host
2. On the host, add an `/etc/resolv.conf` which contains a search domain, which is a common configuration directive:

```
[rancher1 ~]$ cat /etc/resolv.conf
search example.org
nameserver ...
nameserver ...
```
1. Follow instructions for http://docs.rancher.com/rancher/v1.2/en/quick-start-guide/#create-a-multi-container-application . Note this step which says to reference the name 'mysql':

>  In the Service Links, add the database service and provide the name mysql. Just like in Docker, Rancher will link the necessary environment variables in the WordPress image from the linked database when you select the name as **mysql**. Click Create.
1. Spin up MySQL and Wordpress containers.

**Results:** 
1. Wordpress containers fail repeatedly, with this error:

[rancher1 ~]# docker logs --tail 10 stack1_mywordpress_1
Warning: mysqli::mysqli(): (HY000/2002): php_network_getaddresses: getaddrinfo failed: Name or service not known in - on line 19
MySQL Connection Error: (2002) php_network_getaddresses: getaddrinfo failed: Name or service not known
1. Log into container. Note the search path in /etc/resolv.conf. In this case, if `mysql.example.org` already exists, the containers will try to use that instead of the internal container, and will fail.

```
root@c1fc85b64f93:/var/www/html# cat /etc/resolv.conf   
search example.org stack1.rancher.internal mywordpress.stack1.rancher.internal rancher.internal   
nameserver 169.254.169.250  
root@c1fc85b64f93:/var/www/html#
```
1. View /entrypoint.sh . See that the hostname `mysql` is expected at line 5:

```
#!/bin/bash
set -e

if [[ "$1" == apache2* ]] || [ "$1" == php-fpm ]; then
        : "${WORDPRESS_DB_HOST:=mysql}"
...
```

**Expected:**

I expected the wordpress containers to be able to talk to the container named 'mysql' without any connection errors.

**Workaround:**
1. As a workaround, try hardcoding the name `mysql` into /etc/hosts, within each wordpress container. 

```
root@c1fc85b64f93:/var/www/html# 
echo "10.42.11.115 mysql mysql.stack1.rancher.internal" >> /etc/hosts && cat /etc/hosts
...
172.17.0.3      76fc1781bda4
10.42.11.115 mysql mysql.stack1.rancher.internal
# exit
```

Another workaround would be to hardcode the variable "WORDPRESS_DB_HOST" into a container's definition.
1. Now the containers work:

```
[rancher1 ~]# docker logs --tail 10 stack1_mywordpress_1
[Tue Oct 25 21:51:00.014896 2016] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.10 (Debian) PHP/5.6.27 configured -- resuming normal operations
```

**Comment by aemneina** [comment]
@stefanlasiewski did you spin up the containers using the UI or rancher-compose? I copy pasted the docker/rancher-compose.yml definitions and the example worked as expected. Mysql was pingable without any manual intervention.

**Comment by stefanlasiewski** [comment]
@aemneina, this happened with both the UI and via rancher-compose, using the docker/rancher-compose.yml definitions.

On your Docker host in /etc/resolv.conf, are you using the `search` list parameter?

**Comment by stefanlasiewski** [comment]
I should note, if I remove search example.org` from the `/etc/resolv.conf` file on my Docker hosts, the examples work fine.

**Comment by aemneina** [comment]
I do have a search domain:

search us-west-2.compute.internal

**Comment by aemneina** [comment]
Looks like you've gotten to the bottom of this. Can we close it out?

**Comment by aemneina** [comment]
it actually makes sense that example.com would break resolution for mysql as the fqdn would turn into mysql.example.com which doesnt resolve 👍

**Comment by stefanlasiewski** [comment]
My point here is that the Rancher Documentation is missing an important topic.

It's very common for organizations to use a search domain on their Docker hosts. But due to how Rancher handles the search domain by default, the Quick Start Guide will not work with this very common configuration.

The Rancher documentation, or at least the quick start guide, should include a notice about using a search domain in resolv.conf. Then the ticket can be closed.

Really, I think Rancher should make the search domain a configurable parameter. But that's a separate issue, and there's already a ticket about that.

**Comment by aemneina** [comment]
makes sense @stefanlasiewski changed this to a doc bug, to reflect that.

**Comment by superseb** [comment]
This was when Rancher added the search domains after the configured ones, now we configure them as first and it's configure using `io.rancher.container.dns.priority: service_last`
