### ISSUE TITLE
No container and host stats, stuck on connecting

### ISSUE THREAD

**Issue by larsmagnusherland** [rancher/rancher#6441]
**Rancher Version:** 1.1.4
**Rancher Agent Version:** 0.8.3
**Docker Version:** 1.12.3 / 1.12.2
**OS and where are the hosts located:** OVH VPS, Ubuntu 16.04.1 LTS
**Ubuntu Kernel Version:** 4.4.0-45-generic
**Setup:** single node rancher with internal DB
**Environment Type:** Cattle
**Storage driver:** aufs / devicemapper:loop

Any custom added hosts doesn't show any container or host stats.
The screen is stuck at "connecting"
Doesn't matter if the storage driver is aufs or devicemapper:loop
Rancher-agent shows cAdvisor version 0.23.2 ()

**Expected:**
Stat's to show as in earlier version of Ubuntu like Ubuntu 14.04.5 LTS (works)

**Comment by aemneina** [comment]
@larsmagnusherland can you check this with docker 1.10 or 1.11? You also want to avoid using the loopback driver for devicemapper.

**Comment by larsmagnusherland** [comment]
I only have 1 machine running devicemapper:loop
All the others are running aufs.

I will see if I can try with a older version of Docker, but that will require some altering and adjustments to get it working.

**Comment by aemneina** [comment]
I'll close this out, if you can repro this on a 'supported' docker version feel free to reopen.

**Comment by pbaezab** [comment]
Any news?

**Comment by jstdoit** [comment]
any news?

**Comment by pbaezab** [comment]
Yes, review websocket comunication: page stats (via ip or dns A type) <- node client

**Comment by jstdoit** [comment]
@pbaezab sorry?

**Comment by larsmagnusherland** [comment]
Same issue with later versions of Docker and Rancher.
Tried all from 1.12.0 -> 1.12.6
And same with Rancher 1.12 -> 1.3

All running on Ubuntu 16.04

**Comment by jstdoit** [comment]
add ssl support fixed the problem.

**Comment by MichelDiz** [comment]
I know this is an old post. I'm sorry if this fills up your messaging box.

I think I managed to "solve" part of the problem.

1 - The "client" instance you should do "Prune" from Docker. (I think it may be optional - But to know more Look for "Prune System" in the Docker documentation). Do not prune the "Rancher Server" instance.

2 - Update the instances time (clock) with your machine (the one you use to access the Rancher UI) I have this reference for this https://github.com/rancher/rancher/issues/10770

PS. All instances need to be with time in "sync".

3 - How you cleaned thoroughly with Docker Prune System. Raise a new Rancher client. As usual.

4 - Open "Developer Tools" in Chrome. (I think it gives different aproachs in different browsers for this process) Then you go to the "Application" tab and then in the sidebar go search again for "Application" and then you will see a "Clear Storage" option. Click "Clear Site Data".

Extra: This way you will clear everything related to the Rancher UI. Any cookie or whatever. This also works for issues related to other services. Like Youtube, it sometimes "bug" it and gives a grotesque server error. Claiming that you did something prohibited. Just do the fourth step that solves this. You'll just have the job of re-entering all Google accounts again. Cuz clean of all Google services.

Good luck.
