### ISSUE TITLE
Impossible to see a container log when it fails or it is stopped for some reason. not possible to debug.

### ISSUE THREAD

**Issue by demarant** [rancher/rancher#6442]
**issue**
As a member of a Rancher environment when deploying stacks / containers via Rancher UI it is very very hard to see the logs of containers while starting and when they are failing.

When a container fails to start because of some error, it is difficult to see the error if you don’t manage to click on logs the very second it starts and crashes, because after is stops, the Logs are disconnected and not available anymore. This is sometimes really less than a second and you can get the logs only by luck. Rancher currently does not provide the same logs output experience as docker-compose logs does, which can be invoked even on stopped containers.

This is prevents adoption of Rancher from many developers used with docker-compose or just plain docker. Developers prefers fast feedback, real-time logs output while the launch their application stacks.

**Rancher Version:**
the issue applies to all rancher versions.

**Docker Version:**
the issue applies to all docker versions.

**OS and where are the hosts located? (cloud, bare metal, etc):**
all

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
all

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
all

**Steps to Reproduce:**
create a container that starts and than fails for some reasons.
OR simply create a container. start, view logs and stop it. 

**Results:** 
View logs is not available. You cannot view the logs anymore.

**Expected:**
same behaviour as docker logs, docker-compose logs. to always be able to view the logs of a container. For example the dropdown on a container, should always have ""view logs" no matter of the state of the container. same as docker-compose logs.

**Comment by demarant** [comment]
related to the issue in #6318

**Comment by valipod** [comment]
What, no more cat and mouse play with the logs? Joke aside, this would really be a helper.

**Comment by deniseschannon** [comment]
In v1.2, I am able to see logs on a stopped container. Now that we will stop a service and the container so it doesn't continually retry, it is possible to see the logs of the stopped container.

**Comment by deniseschannon** [comment]
@demarant Let me know if you still see this issue in v1.2.
