### ISSUE TITLE
MongoDB Cluster Secondary Nodes not readable

### ISSUE THREAD

**Issue by arvindr21** [rancher/rancher#6443]
**Rancher Version:**
1.1.14

**Docker Version:**
1.12

**OS and where are the hosts located? (cloud, bare metal, etc):**
Cloud

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
1. Create cluster from catalog (mongo 3.2, 3 node)
2. Add a [mongo-express](https://hub.docker.com/_/mongo-express/) service
3. Link mongo-express with mongo-cluster

``` yml
# snipp..
links:
  - mongo-cluster:mongo
# snipp..
```
1. Open mongo-express dashboard, click on db and an error pops up as
   <img width="1197" alt="screen shot 2016-10-29 at 17 52 08" src="https://cloud.githubusercontent.com/assets/2562992/19829480/74976e86-9e00-11e6-9999-12f74b0552be.png">
2. Tried things listed here : https://github.com/mongo-express/mongo-express/issues/220

**Results:** 
<img width="1197" alt="screen shot 2016-10-29 at 17 52 08" src="https://cloud.githubusercontent.com/assets/2562992/19829480/74976e86-9e00-11e6-9999-12f74b0552be.png">

**Expected:**
Able to perform reads on secondary db as well.

Kindly let me know if I need to anything else to get the secondary read working. 

PS: If I log in to the secondary DBs using mongo shell and run `rs.slaveOk(true)` I am able to run `show dbs;` and once I quit the shell and come out, I am seeing the same error again.

**Comment by aemneina** [comment]
hey @arvindr21 have you modeled your mongo deployment on the catalog item, if not it might be a good place to start: https://github.com/rancher/community-catalog/tree/master/templates/MongoDB/1

**Comment by aemneina** [comment]
Also providing container logs might help get to the bottom of this quicker. I'll close this for now, if you can explore the links I sent, and are still facing issues, provide logs... feel free to reopen.

**Comment by arvindr21** [comment]
Thanks @aemneina I figured out the issue. I had to update my connection string based on [strange mongodb and mongoose error: not master and slaveOk=false error](http://stackoverflow.com/a/34133235/1015046) to `mongodb://mongo:27017?replicaSet=rs-0` and I was able to connect.
