### ISSUE TITLE
Unable to create event router

### ISSUE THREAD

**Issue by SnertSnert** [rancher/rancher#6448]
**Rancher Version:**
sudo docker run -d  --name=ben -p 8080:8080    rancher/server:latest
**Docker Version:**
sudo docker version
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:  
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:  
 OS/Arch:      linux/amd64
**OS and where are the hosts located? (cloud, bare metal, etc):**
bare metal fedora 24 
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher , internal DB 
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle ????
**Steps to Reproduce:**
start ranger 
**Results:** 
net/http.(_Transport).getConn.func4(0xc8200c6000, 0x0, 0xa3ae70, 0x4, 0xc820010045, 0xe, 0xc82031c780)
    /usr/local/go/src/net/http/transport.go:706 +0x66
created by net/http.(_Transport).getConn
    /usr/local/go/src/net/http/transport.go:708 +0x262
time="2016-10-29T22:31:04Z" level=fatal msg="Exiting go-machine-service: Get http://localhost:8080/v1: EOF" 
time="2016-10-29T22:31:04Z" level=fatal msg="Unable to create event router" error="Get http://localhost:8080/v1: EOF" 

**Expected:**
started ranger

**Comment by blackwellops** [comment]
I'm getting the same issue on CentOS and on Debian. However, it works fine on MacOS. 

```
time="2016-11-01T03:15:49Z" level=fatal msg="Exiting go-machine-service: Get http://localhost:8080/v1: EOF"
time="2016-11-01T03:15:49Z" level=info msg="Starting rancher-compose-executor" version=v0.8.6
time="2016-11-01T03:15:49Z" level=fatal msg="Unable to create event router" error="Get http://localhost:8080/v1: dial tcp [::1]:8080: getsockopt: connection refused"
```

**Comment by jcherqui** [comment]
:+1:

**Comment by aemneina** [comment]
Can you try this with upstream docker (1.10 or 1.11) with rancher 1.1.x? Anything outside of that YMMV.

**Comment by aemneina** [comment]
if you can repro with the suggested docker versions on rancher 1.1.x, please reopen.
