### ISSUE TITLE
Rancher agent - ability to define name/location of ca.key

### ISSUE THREAD

**Issue by natami** [rancher/rancher#6450]
Does the Rancher agent support defining name/location of ca.key?
- My use case is the following:
  I build my own rancher-agent docker image and add multiple keys like dev.key, test.key and prod.key, so my new image contains multiple keys for each environment.

Expected functionality:
rancher agent loads the specified key at startup from the name/location defined.

**Comment by aemneina** [comment]
I dont believe this exists today, changing this to an enhancement request.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
