### ISSUE TITLE
Question about licensing

### ISSUE THREAD

**Issue by clicman** [rancher/rancher#6451]
Hello! I found EULA at http://rancher.com/eula/
And I don't understand how it connects with apache2 license?
Could you explain when I should use this EULA and when apache2 license?

**Comment by will-chan** [comment]
This Github rancher project is under the apache2 license.  You are welcome to use the open source project under the agreement of the apache2 license however you choose.  If you choose to purchase a support service agreement with Rancher Labs, then the EULA applies for the rancher software.

**Comment by clicman** [comment]
Thank you for answer.
