### ISSUE TITLE
Chown permission denied using convoy-nfs 

### ISSUE THREAD

**Issue by keepwn** [rancher/rancher#6452]
**Rancher Version:** 1.1.4

**Docker Version:** 1.12.1

**OS and where are the hosts located? (cloud, bare metal, etc):** RancherOS, ESXI

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single node rancher, internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:**

1. create a `test` volume using convoy-nfs
2. `in rancher ui`, create a container `Test1` from ubuntu, and `-v test:/data`
  - success
3. `use rancher ui`, create a container `Test2` from ubuntu, and `-v test:/tmp`
  - error, msg is `chown xxxx operation not permitted`
3. `not use rancher`, create a container `Test3` from ubuntu, and `-v /mnt/test:/tmp`
  - success

I guess convoy-nfs maybe try to chown membership of mounted volume when mounting volume.
But, my nfs server's config is `all_squash=nobody` that means could not use `chown` in client.

It is a bug or feature? And how to fix this?
Thanks!

**Comment by aemneina** [comment]
I believe this is expected in that /tmp is an immutable folder and convoy-nfs does try to [chown the mount point.](https://github.com/rancher/convoy-agent/blob/master/scripts/entry#L4) . @cjellick  does that sound about right?

**Comment by aYuan** [comment]
nfs-server:
/volume1/nfs    *(rw,async,no_wdelay,crossmnt,insecure,all_squash,insecure_locks,sec=sys,anonuid=0,anongid=0)

Turn off root squashing. This option is mainly useful for diskless clients.
