### ISSUE TITLE
Host scheduling do not load balance the containers

### ISSUE THREAD

**Issue by digitalLumberjack** [rancher/rancher#6453]
**Rancher Version:**
1.2.0-pre3-rc1

**Docker Version:**
1.12

**OS and where are the hosts located? (cloud, bare metal, etc):**
rancheros + ubuntu bare metal

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Create **2 hosts** with **same label** for scheduling (ex : role=build), and start stacks with rancher cli, with affinity on services like : 
io.rancher.scheduler.affinity:host_label: role=build

**Results:** 
All services run on one of the host, the second never run any service.

**Expected:**
I would like to see a load balancing of the containers.

**Comment by cjellick** [comment]
@digitalLumberjack do you have a docker/rancher compose file that reproduces this issue?

**Comment by digitalLumberjack** [comment]
I'll provide that as soon as possible

**Comment by tfiduccia** [comment]
Version: master 11/1

Craig I was able to reproduce this by simply:
1.  Add same label to two host (I added foo=bar)
2. Create a service with scale = 2, scheduling rule: host label of foo=bar

Both services went to same host.

**Comment by cjellick** [comment]
@tfiduccia and they _never_ go to the second host or are they just not predictably spread (because of the spread bug that I just addressed)

**Comment by digitalLumberjack** [comment]
@tfiduccia my situation is a little bit idfferent as i scale only one service in my stack, but i create many stacks :

Here is a test on rancher 1.1.0 : 

docker-compose.yml:
```
www:
  image: nginx
  labels:
    io.rancher.scheduler.affinity:host_label: role=run
```

rancher-compose.yml:
```
www:
  scale: 1
```

for i in {1..10}; do rancher up -d -s schedule-$i; done

**On the 1.1.0 version of rancher (that is one of my both environments) it works as intended.**


I'll keep you in touch when i can test on the 1.2.0-pre3-rc1 environment.

**Comment by deniseschannon** [comment]
@tfiduccia Could you retest as @cjellick had addressed the spread issue in the new scheduler?

@digitalLumberjack We are introducing a new scheduler in 1.2.0, which isn't in the 1.2.0-pre3 releases.

**Comment by digitalLumberjack** [comment]
I tested on 1.2.0-pre3-rc1 with the simple docker-compose.yml of my previous post. It works as intended as i had 4 stacks on one host and 6 on the other.

So i don't know why my specific stack (that starts only one service too) doesn't react the same, because I started 4 stacks of this just after, and all containers were put on the same host.

Maybe i'll test with the new scheduler when it's out :)

**Comment by tfiduccia** [comment]
Version - 1.2.0-pre4-rc7 UI - v1.2.20
Verified fixed (with scheduler plug-in installed)

**Comment by erikbotta** [comment]
Have rancher 1.6.7 UI (stable)
scheduler - 0.5.1
and when I give same label to 2 hosts, I make rule for scheduling as:
`
The host  must  have a host label  key=value
`
than I can rescale to 2 or 3 containers and all are on first host in UI only. I checked typos ets. Dunno wheres problem.
I also checked when I delete label from first host and rescale all goes to the second host. That's good ... 
But what the hell is wrong with scheduling to more hosts with same label?

**Comment by cjellick** [comment]
Does the second host (where none get scheduled) have more total containers than the first host? The scheduler by default just balances based on total containers, not containers in a particular service.

You could add a soft anti-affinity rule to your service to force it to spread across hosts when its possible:
```
io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
```
http://rancher.com/docs/rancher/v1.6/en/cattle/scheduling/#example-1

**Comment by erikbotta** [comment]
Thx a lot, it is working!
