### ISSUE TITLE
proposal: use shfmt for all shell files

### ISSUE THREAD

**Issue by mvdan** [rancher/rancher#6454]
I've recently written [shfmt](https://github.com/mvdan/sh), a formatter for bash/shell programs. rancher is a pretty active project with lots of contributors, so I think it would benefit from its use.

I ran `shfmt -l -w -i 4 .` and these are the diffs. This does all the files that either have a bash/shell extension or have no extension and a valid bash/shell shebang. `-i 4` is to indent with four spaces.

`git diff` - https://clbin.com/5RXCE
`git diff -w` - https://clbin.com/ygORa

If you have any questions or issues, I'm happy to help. I can also provide a pull request if that would be better.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
