### ISSUE TITLE
When lb instance is restarted ,it gets marked "unhealthy" , deleted and a new lb instance gets created.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6459]
Rancher Version: Build from master

**Steps to Reproduce:**

Create a LB service with scale2 having couple of targets.
Restart one of he Lb instances.
When the Lb instance gets  stopped ,it gets marked "unhealthy" , deleted and a new lb instance gets created.

Expected Behavior:
Existing LB instance should get restarted successfully.

**Comment by alena1108** [comment]
@sangeethah could you test again with the latest rancher/lb-service-haproxy:latest

**Comment by sangeethah** [comment]
Tested with latest build from master (Nov 6):

When lb instance is restarted , it get stopped and started. But after it starts , it gets stuck in "Initializing" state forever.

Following message seen in logs repeatedly.

```
11/6/2016 3:18:02 PMtime="2016-11-06T23:18:02Z" level=info msg="Syncing up LB"
11/6/2016 3:18:02 PMtime="2016-11-06T23:18:02Z" level=error msg="Failed to get lb config: Error 404 accessing /self/service path"
11/6/2016 3:18:02 PMtime="2016-11-06T23:18:02Z" level=info msg="Syncing up LB"
11/6/2016 3:18:02 PMtime="2016-11-06T23:18:02Z" level=error msg="Failed to get lb config: Error 404 accessing /self/service path"
```

**Comment by alena1108** [comment]
@sangeethah please test with the latest

**Comment by sangeethah** [comment]
Automation runs using the latest master build did not report this issue.
