### ISSUE TITLE
Unknown certificate authority warnings

### ISSUE THREAD

**Issue by Matty9191** [rancher/rancher#6466]
**Rancher Version:**

"CATTLE_RANCHER_SERVER_VERSION=v1.1.4",
"CATTLE_RANCHER_COMPOSE_VERSION=v0.8.6",
"CATTLE_CATTLE_VERSION=v0.165.8.4",

**Docker Version:**

Server Version: 1.12.2

**OS and where are the hosts located? (cloud, bare metal, etc):**

Virtualbox instances running Fedora 25beta

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

single node

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

Cattle

**Steps to Reproduce:**

I used the following official document to get rancher up and running:

http://docs.rancher.com/rancher/v1.2/en/installing-rancher/installing-server/

After the docker containers were installed I followed the "add host" instructions. This resulted in the following error on the agent:

requests.exceptions.SSLError: ("bad handshake: Error([('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')],)",)

And an unknown certificate authority on the server:

2016/10/31 19:45:01 http: TLS handshake error from 10.104.152.248:39692: remote error: unknown certificate authority

When I enabled CATTLE_SCRIPT_DEBUG in /run.sh I  noticed that curl and the Python request module were both showing SSL vertificate validation failures. I can successfully connect to the rancher server TCP port from the container so I'm guessing this issue is related to the certificates that were generated when the containers came up? If I'm reading the following correctly I should be able to start the rancher server and add hosts w/o doing any additional configuration:

"Once the UI is up and running, you can start by adding hosts or select a container orchestration from the Infrastructure catalog. By default, if a different container orchestration type is not selected, the environment will be using cattle. After the hosts are added into Rancher, you can start adding services or launch templates from the Rancher catalog."

Any idea what is going on? If I need to follow the ssl config document after the server is started it might be worth noting that on the installation page.

**Comment by aemneina** [comment]
@Matty9191  Are you running the server and the agent on the same host?

**Comment by aemneina** [comment]
@Matty9191 just installed fedora 24 with the latest docker 1.12.3 and was able to launch rancher server and add an agent without issue. For the vbox config i had each fedora host attached to the network in bridged mode... youre right in that nothing special need to be done besides run the rancher server and agent containers.

**Comment by aemneina** [comment]
@Matty9191 can you reopen this if you can reproduce with a non-beta fedora? Also if your host is on the same server as your agent, can you try using by specifying CATTLE_AGENT_IP. There's an example [here](https://github.com/andreimc/rancher-ansible-ha).
