### ISSUE TITLE
Rancher single node reverse-proxy with ssl not working on other ports than 8080

### ISSUE THREAD

**Issue by natami** [rancher/rancher#6469]
I'm having trouble setting up a nginx reverse proxy with self signed ssl certs.

Problem is I need to change rancher UI port from port 8080 to eg. 5222 - the UI is available at port 5222 like http://myrancher:7000

After installing the nginx revers proxy and listen on port 5222, all i get is a 502 Bad Gateway.

Reverting Rancher back to port 8080, and adjusting nginx for the same port, makes the reverse proxy work again.

**Rancher Version:**
v1.2.0-pre4-rc6

**Docker Version:**
Docker version 1.12.2, build bb80604

**OS and where are the hosts located? (cloud, bare metal, etc):**
CoreOS, bare metal, packet.net

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node, internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Swarm

**Steps to Reproduce:**
Install rancher server:
docker run -d -v /mnt/rancher:/var/lib/mysql --restart=unless-stopped -p 5222:8080 --name=rancher-server rancher/rancher-server

Install nginx reverse proxy:
docker run -d --restart=always --name nginx 
    -v /etc/rancher/rancher-nginx.conf:/etc/nginx/conf.d/default.conf
    -v /etc/rancher/test.com.crt:/etc/rancher/test.com.crt
    -v /etc/rancher/test.com.key:/etc/rancher/test.com.key
    -p 80:80 -p 443:443 --link=rancher-server nginx

default.conf:
upstream rancher {
    server rancher-server:5222;
}

server {
    listen 443 ssl;
    server_name test.com;
    ssl_certificate /etc/rancher/test.com.crt;
    ssl_certificate_key /etc/rancher/test.com.key;

    access_log /var/log/nginx/access.log;
    error_log  /var/log/nginx/error.log;

    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://rancher;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        # This allows the ability for the execute shell window to remain open for up to 15 minutes. Without this parameter, the default is 1 minute and will automatically close.
        proxy_read_timeout 900s;
    }
}

server {
    listen 80;
    server_name test.com;
    return 301 https://$server_name$request_uri;
}

**Results:** 
Nginx responds with 502 Bad Gateway.

**Expected:**
Browser was forwarded correctly to UI.

**Comment by aemneina** [comment]
Hey @natami can you try setting `proxy_pass http://rancher;` to use https, let us know if that helps?

**Comment by natami** [comment]
Same result when changing to use https.

**Comment by natami** [comment]
I also tried setting up a Apache as proxy - with same result.

**Comment by aemneina** [comment]
@natami What does the backend configuration look like?

**Comment by natami** [comment]
The backend is a simple CoreOs on bare-metal, running the following docker:

sudo docker run -d -v /mnt/rancher:/var/lib/mysql --restart=unless-stopped -p 5222:8080 --name=rancher-server rancher/rancher-server

**Comment by aemneina** [comment]
can you hit the rancher server directly with the host ip, on port 5222?

**Comment by natami** [comment]
Yes, i can.

**Comment by aemneina** [comment]
so if youre just proxying through, terminating ssl at the nginx, why not use the unsecured port between nginx and rancher?

**Comment by aemneina** [comment]
regardless it looks like an issue between nginx and rancher, since rancher is responding.

**Comment by natami** [comment]
I think you're right.

Might try setting up a Apache and try the same and see if it works.

**Comment by aemneina** [comment]
Cool I'll close this out... Also not sure if you took a peek here for an [example haproxy config here](http://docs.rancher.com/rancher/v1.2/en/installing-rancher/installing-server/basic-ssl-config/#example-haproxy-configuration), it might help.
