### ISSUE TITLE
Stale data when changing catalog template from dropdown.

### ISSUE THREAD

**Issue by piotron** [rancher/rancher#6470]
**Rancher Version:**
v.1.2.0-pre4-rc2 -- v1.2.0-pre4-rc6
**Docker Version:**
1.12.1
**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04 cloud ovh
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node, external db
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**

1. Go to catalog, choose tepmlate(for example Convoy EFS) 
2. Without going back choose another template(for example Drone) from dropdown. 
3. Choose version of template and then go back with dropdown to previous template.
**Results:** 
on step 2 until you choose version you will see Drone template with Convoy EFS template configuration, and convoy-efs docker-compose,rancher-compose, and answers.txt.
on step 3 you will see Drone stale data everywhere(expect logo) until you refresh or choose template version.

**Expected:**
When changing from dropdown stale data are cleaned, and new data is loaded only after choosing template version.

**Comment by tfiduccia** [comment]
Version - master 12/19
Not fixed

**Comment by alexanderdalloz** [comment]
Still not fixed in version 1.6.2

**Comment by tfiduccia** [comment]
Version - 1.6 master build
Not fixed.  As you can see, I have selected a different template from the drop-down and it's still showing the Alfresco description information.
![image](https://user-images.githubusercontent.com/11514927/31637174-4f079488-b282-11e7-823d-8d3fa03d8c38.png)

**Comment by loganhz** [comment]
hi @tfiduccia ,
I guess it is fixed in master build. Could you please try again?

I can reproduce it in `1.6.10` by the following steps, but I can not reproduce it with master UI and `1.6.10` as backend.

 step 1. Go to catalog list page and select `Alfresco `
 step 2. Search `infulxdb` in drop-down and select it.

**Comment by tfiduccia** [comment]
@loganhz - I only have the dev version of the UI and backend :)

**Comment by loganhz** [comment]
Thanks @tfiduccia 
I tried the UI build from `http://releases.rancher.com/ui/master` and looked at into js files.
It doesn't have my change. Maybe we should test it on next 1.6 master build.

**Comment by tfiduccia** [comment]
@loganhz 

So in the newest RC, the Data is changing.  But now when I switch there is a weird refresh issue, first when I switch there will be a flash of the title but it will say Add <title of new template> Stack.  Then it will refresh again and say just the title.  I don't think we want weird info flashing.

**Comment by tfiduccia** [comment]
Version - v1.6.11-rc6
Verified fixed!  woohoo!
