### ISSUE TITLE
Add Stack:ContainerName Information When Executing a Shell in Audit Log

### ISSUE THREAD

**Issue by ecliptik** [rancher/rancher#6474]
When executing a shell into a container, it shows up in the Audit Log as a `api.container.execute` event type. There isn't much other information though and isn't very useful to see if a user was accessing a specific container or stack.

Here is an example of executing a shell into a running container, but the audit log not saying any information about what container or stack was used. 

<img width="1221" alt="screen shot 2016-11-01 at 2 57 53 pm" src="https://cloud.githubusercontent.com/assets/1261742/19909200/bfb3693e-a043-11e6-98b7-d680b96cf978.png">

Instead of `container` something like `$stack:$containername` is more helpful.

This would provide additional visibly in how users are accessing running resources.

**Rancher Version:**
v1.1.4

**Docker Version:**
1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
RancherOS on AWS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single rancher node using external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
cattle

**Steps to Reproduce:**

**Results:** 

**Expected:**

**Comment by vincent99** [comment]
Container ID needed to determine this is missing from the API:

```
requestObject": "{\"follow\":true,\"lines\":500}",
"resourceId": null,
"resourceType": "container",
"responseCode": 200,
```

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
