### ISSUE TITLE
Support recreating swarm stack on top of a cluster of hosts already in a swarm

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#6476]
**Rancher Version:**1.2.0-pre4-rc6

**Docker Version:**1.12.2

**OS and where are the hosts located? (cloud, bare metal, etc):**Ubuntu, Cloud

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**Swarm (v1.12-rancher0)

Recreation of stack would be useful to create a new stack using the same hosts. Currently when a swarm stack is deleted and started again, hosts may not join the swarm cluster and swarm may not function correctly as it has the previous state.

**Comment by LLParse** [comment]
https://github.com/rancher/rancher-catalog
1.2 branch

**Comment by deniseschannon** [comment]
now available on master branch

**Comment by soumyalj** [comment]
Tested with rancher v1.2.0. Created a swarm setup with 3 hosts. Added services to the cluster. Deleted the swarm stack and the hosts were not deleted. A new swarm stack was created again on the same hosts and it was successful. The hosts were able to join the new swarm cluster.
