### ISSUE TITLE
kubernetes & other environments are showing cow icon instead of their own

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#6478]
**Rancher Version:** master 11/01

**Steps to Reproduce:**
1.  Create a kubernetes, mesos and cattle environments
2.  go to cattle environment and add a host
3.  Go to manage environments and add environment

**Results:** All icons are cows until I refresh screen
![image](https://cloud.githubusercontent.com/assets/11514927/19910874/1cecff94-a04d-11e6-862a-22657bea777c.png)

**Expected:**  Should not be cows

**Comment by vincent99** [comment]
Switching environments was the key piece here..

**Comment by tfiduccia** [comment]
Version - master 11/10
Verified fixed
