### ISSUE TITLE
After adding first template, default cattle template disappears but is still selected

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#6479]
**Rancher Version:** master 11/1

**Steps to Reproduce:**
1.  Create a kubernetes templates
2.  Click on add environment

**Results:** Notice under the templates it says "Orchestration: Cattle"  Even though the cattle icon image is now missing (it was there before I added k8s template).  After i add more templates, this is still the case.

**Expected:**  If it's selected, it should be visible.

**Comment by vincent99** [comment]
Selects the first project template by default now instead of none.

**Comment by tfiduccia** [comment]
Version - master 11/06
Verified fixed
