### ISSUE TITLE
Add ability to see/edit which template I used in environments page

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#6481]
**Rancher Version:** master 11/01

** Comments: **  I should be able to see which template I used when I created an environment.  I should also be able to change the templates.

**Comment by vincent99** [comment]
See yes, edit not supported.  The template is only used once on creation of the environment.

![image](https://cloud.githubusercontent.com/assets/753917/19976949/06320610-a1af-11e6-9965-dbbe3046d90d.png)

**Comment by tfiduccia** [comment]
Version - master 11/06
Verified fixed
