### ISSUE TITLE
rancher-agent (agent, bootstrap, state) containers are showing up in UI

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#6483]
**Rancher Version:** master 11/01

**Steps to Reproduce:**
1.  Deploy a environment
2.  Go to host & click on Show System or go to container page

**Results:** All the rancher-agent containers are showing up
![image](https://cloud.githubusercontent.com/assets/11514927/19911790/03ceb916-a053-11e6-8c73-8b5c32371d55.png)

**Expected:**  Should not show up.

**Comment by deniseschannon** [comment]
Instead of hiding the containers, we will be preventing users from deleting the rancher/agent container.

**Comment by deniseschannon** [comment]
We are not going to change this behavior and will now always show up.
