### ISSUE TITLE
Swarm cannot find AGENT_IP from metadata

### ISSUE THREAD

**Issue by gegenschall** [rancher/rancher#6489]
**Rancher Version:** rancher/agent:v1.1.0-rc10 and rancher/server:v1.2.0-pre4-rc6

**Docker Version:** 1.12.3
 
**OS and where are the hosts located? (cloud, bare metal, etc):** Rancher server: Debian 8, Rancher Agent and Hosts: created via Exoscale Machine Driver

**Setup Details:** single node, internal DB

**Environment Type:** Swarm

**Steps to Reproduce:** Add new Swarm host via Exoscale Driver

**Results:** swarm-swarmkit-mon-1 doesn't come up, Logs show the following lines repeating forever:
```

11/2/2016 1:57:26 PM++ curl -s http://rancher-metadata.rancher.internal/2015-12-19/self/host/agent_ip
11/2/2016 1:57:26 PM+ AGENT_IP=
11/2/2016 1:57:26 PM+ '[' '' == '' ']'
11/2/2016 1:57:26 PM+ sleep 1
11/2/2016 1:57:27 PM++ curl -s http://rancher-metadata.rancher.internal/2015-12-19/self/host/agent_ip
11/2/2016 1:57:27 PM+ AGENT_IP=
11/2/2016 1:57:27 PM+ '[' '' == '' ']'
11/2/2016 1:57:27 PM+ sleep 1
11/2/2016 1:57:28 PM++ curl -s http://rancher-metadata.rancher.internal/2015-12-19/self/host/agent_ip
11/2/2016 1:57:28 PM+ AGENT_IP=
11/2/2016 1:57:28 PM+ '[' '' == '' ']'
11/2/2016 1:57:28 PM+ sleep 1
11/2/2016 1:57:29 PM++ curl -s http://rancher-metadata.rancher.internal/2015-12-19/self/host/agent_ip
11/2/2016 1:57:29 PM+ AGENT_IP=
11/2/2016 1:57:29 PM+ '[' '' == '' ']'
11/2/2016 1:57:29 PM+ sleep 1
```
CATTLE_AGENT_IP is set to the correct external IP address of the agent.

**Expected:**
Swarm initializes correctly.

**Comment by vincent99** [comment]
Assuming this was fixed in later RCs for swarmkit...
