### ISSUE TITLE
Feature Request: Log Commands in Execute Shell to Audit Log or External Service

### ISSUE THREAD

**Issue by ecliptik** [rancher/rancher#6492]
Requesting the ability to log all commands executed within a running container via the `Execute Shell` method in the Rancher UI or CLI. In addition to the Audit Log, this would give a full picture of how authorized users are interacting with running containers and stacks.

If Rancher is between a user and a container, logging the stream to an external service would be beneficial in keeping a history of all activity within an environment and avoid tampering.

**Justification**

While it's considered an anit-pattern to shell into a running container, if there is an unknown bad-actor in an organization with access to an environment, they could disrupt a stack by running commands via `Execute Shell`.

**Rancher Version:**
v1.1.4

**Docker Version:**
v1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
RancherOS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Rancher using AWS RDS external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**

**Results:** 

**Expected:**

**Comment by vincent99** [comment]
This isn't very practical as it's just a TTY.  The best you could do is get the equivalent of a keystroke recorder, with no context.  Or record both sides and play it back as a TTY, like iTerm can do, but that's considerably more complicated.

I feel like something simpler such as a `taintedByMeatbags: true` flag on containers that gets automatically set if a shell is ever opened on a container could be almost as effective.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
