### ISSUE TITLE
In Add Environment, service discovery and plug-in text says Undefined

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#6495]
**Rancher Version:** master 11/2

**Steps to Reproduce:**
1.  Create a template that has the Service Discovery plug-ins
2.  Go to Add Environment and select that template

**Results:** The service discovery text and plug-in text all say undefined
![image](https://cloud.githubusercontent.com/assets/11514927/19949178/860eb844-a10d-11e6-9c84-40bc08cf44b8.png)

**Expected:**  Should display proper text

**Comment by vincent99** [comment]
This happens if the catalog template referenced in the project template isn't found... changed to show Unknown and the stack name (which is sorta like the template name...)

**Comment by tfiduccia** [comment]
Version - 1.2.0-pre4-rc7 UI 1.2.20
Verified fixed
