### ISSUE TITLE
Incorrect server version reported in kubectl 

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6496]
Rancher server version - Build from master
k8s template (v1.4.4-rancher1)  from 1.2 branch of rancher-catalog .

kubectl server version shows server as  v1.2.0-alpha.1.17071+0fe26bc6339a86-dirty (edited)

 ```
> kubectl version
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.4", GitCommit:"3b417cc4ccd1b8f38ff9ec96bb50a81ca0ea9
d56", GitTreeState:"clean", BuildDate:"2016-10-21T02:48:38Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"
}
Server Version: version.Info{Major:"1", Minor:"2+", GitVersion:"v1.2.0-alpha.1.17071+0fe26bc6339a86-dirty", GitCommit:"0
fe26bc6339a860096bc30c5c0fa29e9f669edc1", GitTreeState:"dirty", BuildDate:"2016-10-31T18:07:28Z", GoVersion:"go1.6.3", C
ompiler:"gc", Platform:"linux/amd64"}
>
```

In previous K8s template , server version was reported correctly:

<img width="1423" alt="screen shot 2016-11-02 at 3 24 21 pm" src="https://cloud.githubusercontent.com/assets/4266958/19949731/aa1d1f84-a110-11e6-876c-144071a2351f.png">

<img width="1211" alt="screen shot 2016-11-02 at 3 24 47 pm" src="https://cloud.githubusercontent.com/assets/4266958/19949725/a55c0578-a110-11e6-8a77-13b99560f24f.png">

**Comment by alena1108** [comment]
Download a new alena1108/k8s:dev; it should report the correct server version

**Comment by soumyalj** [comment]
Tested with master. The server version reported is 1.4.5-rancher2 as shown below:
```
> kubectl version
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.4", GitCommit:"3b417cc4ccd1b8f38ff9ec96bb50a81ca0ea9
d56", GitTreeState:"clean", BuildDate:"2016-10-21T02:48:38Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"
}
Server Version: version.Info{Major:"1", Minor:"4+", GitVersion:"v1.4.5-rancher2", GitCommit:"4b5664eb051eadd7916d8af4b0f
e29377f13f18b", GitTreeState:"clean", BuildDate:"2016-11-10T23:10:06Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"li
nux/amd64"}

```
