### ISSUE TITLE
hoststats api returns container without id

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#6498]
The `hoststats` api returns a container frame that does not contain an ID. After talking to @StrongMonkey we think this is the agent container and should not be returned with the stats call. 

**Rancher Version:**
latest

**Docker Version:**

**OS and where are the hosts located? (cloud, bare metal, etc):**
cloud
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
cattle
**Steps to Reproduce:**
Start a host.
Visit host details page
Inspect the console in the browser
**Results:** 
JS error about an undefined id
**Expected:**
No js error

**Comment by deniseschannon** [comment]
Could this be related to this issue where agent containers are showing up in Rancher where they should actually be hidden? https://github.com/rancher/rancher/issues/6483

**Comment by StrongMonkey** [comment]
it is a bug in host-api @deniseschannon

**Comment by StrongMonkey** [comment]
I forget that now we have rancher-agent showing in our UI, Can you test whether the system container(rancher/agent) has an assigned id now?

**Comment by StrongMonkey** [comment]
@westlywright nvm, it is still a bug. I opened a PR

**Comment by sangeethah** [comment]
Tested with v1.2.0-pre4-rc8 .

@westlywright , I see a lot of these error in "console" view when in "Host detail" page:

<img width="1445" alt="screen shot 2016-11-18 at 10 49 17 am" src="https://cloud.githubusercontent.com/assets/4266958/20442220/bd379edc-ad7c-11e6-98b6-b9c9f4b5939b.png">

**Comment by StrongMonkey** [comment]
@westlywright  Can you take a look? it seems unrelated with stats data frame.

**Comment by westlywright** [comment]
@StrongMonkey I just built a new rancher/server:master, removed the code that I put in to protect against the error that originally caused me to raise this bug, and verified on the detail page I was not seeing any JS errors as I was before.

@sangeethah I am not seeing the errors you are seeing, either before or after removing my temporary changes. I do not believe they are related to this bug. 

To Verify: 

1. Navigate to an active host detail page
2. Open Chromes developer tools, select the network tab, select the WS filter, and finally select the `hoststats` call
3. Verify that host frames frames are not being sent with an empty id parameter

**Comment by westlywright** [comment]
@sangeethah I built a server with v1.2.0-pre4-rc8 and still am not seeing the problem you posted here.

**Comment by tfiduccia** [comment]
Version - v1.2.0-pre4-rc9
Verified fixed
