### ISSUE TITLE
ExternalDNS failing to operate on 1.2.0-pre4-rc6

### ISSUE THREAD

**Issue by miv** [rancher/rancher#6500]
*Describe your issue here*

ExternalDns (route53) service failing to enumerate stacks after upgrading to rancher 1.2.0-pre4-rc6 from 1.2.0-pre3

```
level=info msg="Starting Rancher External DNS service"
level=error msg="Error reading stack info: Error 404 accessing /self/stack path...will retry"
```

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.2.0-pre4-rc6` Cattle: `v0.171.0` UI: `v1.2.19` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`stack.index`|

**Comment by aznamier** [comment]
Works for me on 1.2.0-pre4-rc5

**Comment by vincent99** [comment]
All the microservices were changing around this time so I'm assuming this works for you in newer builds, if not please reopen.
