### ISSUE TITLE
Configure web UI background as a visual reminder of environment

### ISSUE THREAD

**Issue by nrvale0** [rancher/rancher#6503]
Relayed user feature request from NYC Container Days...

"We have 10 different environments, from devtest to UAT to prod, and we would like a visual reminder of which environment we are logged into to prevent accidentally mucking up something in the wrong environment. I think the easiest and most difficult to miss reminder could come via the ability to configure an environment to have a specific background color and/or background image."

Customer is considering the idea of a browser plugin with CSS mods a la Greasemonkey etc but would prefer that we provide the functionality natively.

**Comment by pulberg** [comment]
This would be great, I have been asked several times about "branding" environments for specific teams.

**Comment by underyx** [comment]
Yes, we need this as well, though perhaps coloring the navigation bar is enough.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
