### ISSUE TITLE
Chrome browser freezes when viewing container log with large output

### ISSUE THREAD

**Issue by roffe** [rancher/rancher#6506]
**Rancher Version:**
1.1.4

**Docker Version:**
1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
CoreOS 1122.3 in OpenStack

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Rancher-HA 3 nodes, Percona XtraDB cluster with 3 nodes

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Swarm

**Steps to Reproduce:**
Launch nginx container, open the logs for the container, make lots of requests to the container.

**Results:** 
Chrome tab with rancher stops responding and i have to hardkill it.
Chrome Version 54.0.2840.71 (64-bit) for Mac

**Expected:**
See a tail of the logfile

**Comment by pasientskyhosting-docker-hub** [comment]
I suggest to show only the last 300 log entires, and an option to show "more" / download the log file.

**Comment by woopstar** [comment]
I suggest to show only the last 300 log entires, and an option to show "more" / download the log file.

**Comment by vincent99** [comment]
We load 1000 lines which should be adequate.  This should be better with the rendering in 1.2+.
