### ISSUE TITLE
Cancelling an upgrade terminates the working container

### ISSUE THREAD

**Issue by sorenroug** [rancher/rancher#6508]
**Rancher Version:** 1.1.4
**Docker Version:** 1.10.3
**OS and where are the hosts located? (cloud, bare metal, etc):** CentOS 7 in cloud
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** Single node Rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle
**Steps to Reproduce:**
The issue occurs when the upgrade strategy is to start first, and the image to upgrade to doesn't launch.
The initial steps are done with rancher-compose, the following docker-compose.yml file
```
example:
  image: busybox:1
  tty: true
  stdin_open: true
```
and this rancher-compose.yml file:
```
example:
  upgrade_strategy:
    start_first: true
```
With these two files do a `rancher-compose up -d` to create the initial service.
Then change the `busybox:1` in the docker-compose file into `busybox:2` (a version that doesn't exist) and do `rancher-compose up --force-upgrade -d`.

After a while you see that `busybox:2` causes errors:
```
Error (Image [busybox:2] failed to pull: Tag 2 not found in repository docker.io/library/busybox)
```
Click on **Cancel Upgrade**, then click on **Finish Upgrade**.

**Results:** 
The original `busybox:1` container is stopped and removed. A new container with the image `busybox:2` is started - which will fail. The finish upgrade gets stuck.

**Expected:**
The original container has been working up until the click on **Finish Upgrade**. It should just continue and the failed `busybox:2` containers be removed.

**Comment by deniseschannon** [comment]
When you are in "Cancelled-Upgrade" state, the behavior is not intuitive. You actually need to rollback to go back to your original service. Finish Upgrade goes to your new service. 

This has already been fixed in our next major release 1.2 where in "Cancelled-Upgrade" state, you only have the option to rollback.
