### ISSUE TITLE
Preserve folder name case when creating stack from CLI

### ISSUE THREAD

**Issue by beatcracker** [rancher/rancher#6514]
#### Enhancement
It would be nice if CLI preserved folder name case when creating stack. Currently, all newly created stacks are in the lowercase.

**Comment by vincent99** [comment]
Stack names should be case-insensitive, but -preserving.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
