### ISSUE TITLE
If I finish upgrade through service, it's not reflected on stack level

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#6515]
**Rancher Version:** master 11/04

**Steps to Reproduce:**
1.  Create a catalog template with multiple version & just 1 service inside it.
2.  Install the catalog item with first version
3.  Upgrade to 2nd version
4.  Instead of Finish Upgrade on stack level, do it through the service menu

**Results:** The stack stays in a "Upgraded" state even though the service is now active.
![image](https://cloud.githubusercontent.com/assets/11514927/20019739/fa9e8706-a28a-11e6-9f9d-6bda9c66338c.png)

**Expected:**  Stack should know state and be active.

**Comment by joshwget** [comment]
Catalog service isn't really aware of stacks, so I'm thinking the fix for this is elsewhere. Cattle or Rancher Compose seems more likely. Any idea @vincent99?
