### ISSUE TITLE
Rancher CLI : Cannot create a host with a specific docker version using CLI

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#6518]
**Rancher Version:**1.2.0-pre4-rc6

**Rancher CLI Version:** v0.3.0-rc3

**OS and where are the hosts located? (cloud, bare metal, etc):**Ubuntu, Cloud

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**Single node

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:**
1. Create a cattle environment 
2. Using rancher CLI, add a Digital Ocean host with the below command which includes the --engine-install-url to be used for the host

```
./rancher hosts create soumyaclihost3 --driver "digitalocean"  --digitalocean-ssh-user "root" --digitalocean-ssh-port "22" --digitalocean-region "nyc3" --digitalocean-image "ubuntu-14-04-x64" --digitalocean-size "1gb" --digitalocean-access-token "f0b....477e" --engine-install-url "https://releases.rancher.com/install-docker/1.11.sh"
```
**Results:** 
The host is created successfully with Docker 1.12.3, but the requested docker version is not installed on the host

**Expected:**
The host should be created with required the docker version

**Comment by deniseschannon** [comment]
Verified fixed with Rancher CLI v0.4.0-rc1, and rancher in v1.2.0-rc2.

Was able to use the docker 1.11 script and host came up with Docker 1.11.
