### ISSUE TITLE
Add role into list of environments view

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#652]
v0.18.1

It would be nice to see the role that you have on the list of projects. Currently, you don't know what role you have unless you click into the project.

**Comment by deniseschannon** [comment]
![screen shot 2016-02-04 at 10 51 32 am](https://cloud.githubusercontent.com/assets/11410997/12825880/445ea0e6-cb2d-11e5-9d30-89a8eb856f3b.png)

**Comment by vincent99** [comment]
This would need to be added to the API to get efficiently.. If there are one or more member entries which apply to the authenticated user for each project, the highest privilege they have on it.
