### ISSUE TITLE
Rancher CLI : Inspecting a newly created environment by name is not successful

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#6520]
Rancher Version:v1.2.0-pre4-rc6

Rancher CLI version: v0.3.0-rc3

OS and where are the hosts located? (cloud, bare metal, etc):: Ubuntu, Cloud

Environment Type: (Cattle/Kubernetes/Swarm/Mesos): Cattle

Steps to Reproduce:
1. Create a rancher cli setup and use account API keys
2. Create a new environment using: 
```
soumyas-MacBook-Pro:rancher-v0.3.0-rc3 soumya$ ./rancher env create cattleenv
1a20
```
3. Inspect the newly created environment by name.
```
soumyas-MacBook-Pro:rancher-v0.3.0-rc3 soumya$ ./rancher inspect --type project cattleenv
error cattleenv: Not found: cattleenv
```
Note: 
Inspecting the new environment by id is successful
Inspecting the Default environment by name is successful

**Comment by deniseschannon** [comment]
Inspect by name is not currently supported for inspect.
