### ISSUE TITLE
Missing Required","message":null,"detail":null,"field Name":"port"

### ISSUE THREAD

**Issue by goluzdravi** [rancher/rancher#6522]
*Describe your issue here*

I`m unable to create a new service over rancher API with error: 
Missing Required","message":null,"detail":null,"field Name":"port"
There is no such field when I access API over UI and go to create service. There is no such field in generated request
 

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.1.4` Cattle: `v0.165.8.4` UI: `v1.1.14` |
|Access|`Disabled`|
|Orchestration|`Cattle`|
|Route|`environment.index`|

**Comment by vincent99** [comment]
The error messages don't show which sub-object the field is missing on, but in this case it's probably the port for healthcheck that is missing.
