### ISSUE TITLE
Docker compose version 2 not supported. 

### ISSUE THREAD

**Issue by pe2mbs** [rancher/rancher#6524]
**Rancher Version:**
   Rancher	v1.1.4
   Cattle	v0.165.8.4
   User Interface	v1.1.14
   Rancher Compose	v0.8.6

**Docker Version:**
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 21:44:32 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 21:44:32 2016
 OS/Arch:      linux/amd64  

**OS and where are the hosts located? (cloud, bare metal, etc):**
  Bare metal / ubuntu 14.04 LTS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
   single node rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
   Cattle
**Steps to Reproduce:**
   any version 2 docker-compose file, it breaks on the line version: '2' 
**Results:** 
   in web ui: Activating (Unknown resolution for '2' using <config.RawService Value> at line 0, column 9)
**Expected:**
   normal execution

**Comment by deniseschannon** [comment]
This is a duplicate issue: https://github.com/rancher/rancher/issues/3973

Support for services and volumes will be added in 1.2.0.
