### ISSUE TITLE
volume.activate processes stuck for 6 months, rancher must not try forever on very old processes

### ISSUE THREAD

**Issue by demarant** [rancher/rancher#6526]
**Rancher Version**: 1.1.4
**Docker Version**: 1.10.3
**OS and where are the hosts located? (cloud, bare metal, etc)**: 
"kernelVersion": "3.10.0-327.13.1.el7.x86_64",
"operatingSystem": "CentOS Linux 7 (Core)",
on Openstack VMs
**Setup Details**: Rancher server on one host and external mysql on another host.
**Environment Type**: Cattle

**issue**:
after months of running rancher we have seen processes stuck forever under admin > processes.
I have managed to remove the agent.reconnect processes that were stuck...but many others are stuck for months not able to delete. For example see image, i am not able to delete the processes volume.activate ...these are 6 months old! maybe these are slowing down the server.
There is no point for rancher to try forever on these.

![rancher-volume activate](https://cloud.githubusercontent.com/assets/320440/20036297/3288c4da-a405-11e6-992b-918b8cb78ce3.png)
 
**Steps to Reproduce**: Run Rancher for months and you will start seeing accumulated failed processes that are months old and cannot be removed.

**Expected**:
There is no point for Rancher to try forever smth that has been failing for months ...
rather it should still report them and mark them as "dead", instead of having continuous exceptions in the logs and to avoid performance degradation in the longer run.

related issues: 
https://github.com/rancher/rancher/issues/4974
https://github.com/rancher/rancher/issues/5349
https://github.com/rancher/rancher/issues/6374

forum:
https://forums.rancher.com/t/how-to-use-the-processes-information-for-admin-documentation-needed/4161

**Comment by akurkin** [comment]
experiencing the same problem, very annoying. Would love to have a button in UI to kill processes

**Comment by STRML** [comment]
Is there no official way to stop a stuck process?

**Comment by tknecht** [comment]
Rancher Version: 1.2
Docker Version: 1.2.12
OS and where are the hosts located? (cloud, bare metal, etc): digitalocean server
"kernelVersion": 4.4.0-53-generic,
"operatingSystem": #74-Ubuntu SMP,
Environment Type: Cattle

Same issue here. See link: https://monosnap.com/file/NRRBFWqwLbLx2NfYDsbKgXLM7U0Hor
API links end up in a 404.

How do we get rid of those?

**Comment by vincent99** [comment]
Rancher is an orchestration system which continually reconciles what the state of the world is vs what it should be.  "Processes" are not actual compute processes, but things the orchestration system thinks need to be done.  So "cancelling" a process does not really have any meaning, the disparity between desired and actual needs to be corrected.

Most of these should be fixed in 1.3+ and running the DB cleanup script (see `docker run --rm rancher/cleanup-1-1` for usage).
