### ISSUE TITLE
Not able to access exposed ports once the service is restarted.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6528]
Rancher Version: Build from master

Steps to reproduce the problem:
Create a service with port.
Access on the exposed port works as expected.
Restart service.
After service restart , not able to access the exposed port works anymore.

The same behavior is also noted 
1. When environment is deactivate and activated.
2. When container of the service is stopped (and it gets restarted).

Following are the 3 automated tests that fail because of this issue:

test_dns_deactivate_activate_environment
test_dns_service_deactivate_activate
test_dns_services_restart_instance
test_extservice_deactivate_activate_environment
test_dns_discovery_services_restart_instance
test_sidekick_deactivate_activate_environment
test_link_services_stop_start_instance
test_link_service_deactivate_activate

**Comment by alena1108** [comment]
@ibuildthecloud caused by 10.42.x.x address change for a container on its restart. During this change, there is a split of a second when the link nic-> ip is broken. And instance doesn't get programmed to meta

**Comment by sangeethah** [comment]
This issue is not seen anymore when testing with latest builds.
