### ISSUE TITLE
Accessing service Alias from a  service with host network does not resolve to ip address of the containers that are targets of service Alias.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6529]
Rancher server version - Build from master

Steps to reproduce the problem:
Create 2 services (cs1,cs2)  with "host" network / "managed" network.
Create a service alias - WEB1 with the above 2 targets.
Create another service - S1 with "host" network and link it to this service alias.

From containers of service S1 , ```dig WEB1 +short``` does not return ip address of containers from cs1 and cs2.

But i am abel to access WEB1 using wget commands.

```
root@sangeemaster-10acre-3:/# dig WEB1 +short
root@sangeemaster-10acre-3:/# wget http://WEB1:80/name.html
--2016-11-06 22:02:28--  http://web1/name.html
Resolving web1 (web1)... 104.154.142.112, 104.198.158.135
Connecting to web1 (web1)|104.154.142.112|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 22 [text/html]
Saving to: 'name.html'

100%[======================================>] 22          --.-K/s   in 0s

2016-11-06 22:02:28 (2.81 MB/s) - 'name.html' saved [22/22]

root@sangeemaster-10acre-3:/# cat name.html
sangeemaster-10acre-2
root@sangeemaster-10acre-3:/#
```

**Comment by sangeethah** [comment]
Following automation runs fails because of this issue:
test_dns_svc_hostnetwork_cosumed_service_managednetwork
test_dns_svc_hostnetwork_cosumed_service_hostnetwork

**Comment by deniseschannon** [comment]
Fix is in 
ipsec: rancher/net:v0.6.3
netowrk manager: plugin-manager:v0.1.5

**Comment by sangeethah** [comment]
Tested with latest build from master.
rancher/dns:v0.10.2
rancher/healthcheck:v0.1.0
rancher/net:v0.7.0
rancher/metadata:v0.6.3
rancher/plugin-manager:v0.2.0
rancher/storage-nfs:v0.1.1
rancher/scheduler:v0.1.2

Host network test cases relating to DNS resolution was  modified to use FQDN for dig to return expected ipaddresses.

Host network test cases relating to access service links by name was removed , since we do not support these cases anymore.

With the above changes , all the host network related test cases in automation run succeed.
