### ISSUE TITLE
External service pointing to cname does not resolve.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6530]
Rancher Version: Build from master
Steps to reproduce the problem:
Create an external service pointing to "google.com".
Create a service with link to this external service.
From within this container , try to ping external service name.
This does not resolve to google.com

Automated test that fails:
test_extservice_with_cname

**Comment by deniseschannon** [comment]
Released in Rancher-DNS v0.10.4

**Comment by sangeethah** [comment]
Tested with rancher/dns:v0.10.4.

I am still able to reproduce this issue.

**Comment by alena1108** [comment]
@sangeethah could you test with rancher/dns:v0.10.5

**Comment by sangeethah** [comment]
Tested with latest build from master and  rancher/dns:v0.10.5.
This issue is fixed now.
