### ISSUE TITLE
DNS resolution takes longer than 5 secs.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6532]
Rancher Version: Build from master

Steps to reproduce the problem:
Create couple of services (s1 and s2) and have a DNS Alias created with these 2 services as targets.
From containers of another service , try to access the DNS alias name.
DNS resolution for the DNS alias name to work takes more than 5 secs.

When services (s1/s2) get deactivated and activated , for the changes to be reflected on the DNS resolution takes longer.

The time taken for DNS resolution seems to significantly increase in a rancher-server setup with has lot more services deployed.

Even increasing the delay of accessing services by name/links to 10 seconds is not enough sometimes.

**Comment by bacheson** [comment]
I have had to run service discovery check loops on startup to get around this. Sometime with a lot of fast moving containers it can take 5 minutes for DNS to become fully available.

**Comment by sangeethah** [comment]
When automation is run with 5 sec sleep before access exposed ports , ports are not available yet.

Tested with master build with commit 0c9c663a6e67c8c14be0bf067807db8ebb621169
rancher/dns:v0.10.2
rancher/healthcheck:v0.1.0
rancher/net:v0.6.2
rancher/metadata:v0.6.3
rancher/plugin-manager:v0.1.4
rancher/scheduler:v0.1.2

**Comment by sangeethah** [comment]
Tested with v1.2.0-pre4-rc11 .Automation runs execute fine with a 5 sec delay for accessing exposed ports.
