### ISSUE TITLE
On rollback, load balancers stuck in Reinitializing

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#6534]
**Rancher Version:** master 11/06

**Steps to Reproduce:**
1.  Create a load balancer
2.  Upgrade the load balancer by changing the port
3.  Rollback the upgrade

**Results:** Container stuck in Reinitializing which is causing Service to stay in initializing

**Expected:**  Should be able to roll them back

**Comment by alena1108** [comment]
@tfiduccia could you retest this on the latest? LB stuck in initializing/reinitializing was caused by the bug when ip address was changed for the instance that was restarting

**Comment by tfiduccia** [comment]
Version - master 11/06
Verified fixed
