### ISSUE TITLE
dnsupdate-rfc2136 not working on rancher 1.2.0-pre4-rc6

### ISSUE THREAD

**Issue by ruzarowski** [rancher/rancher#6538]
**Rancher Version:**
1.2.0-pre4-rc6
**Docker Version:**
1.11.2
**OS and where are the hosts located? (cloud, bare metal, etc):**
CentOS7, VMWare VM
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA Rancher, external DB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
Create dnsupdate-rfc2136 stack
Create a stack with loadbalancer in same environment
**Results:** 
No records are created in the dedicated bind DNS zone
**Expected:**
DNS records are created for the services in the environment

**Comment by ruzarowski** [comment]
Also, the plugin triggers an AXFR every 2 seconds, which is a little too much.
I have tested AXFR with dig from the same host, works without problems.

**Comment by Toonix** [comment]
pretty annoying

6.12.2016 11:49:39time="2016-12-06T10:49:39Z" level=error msg="AXFR envelope error: dns: no SOA"
6.12.2016 11:49:41time="2016-12-06T10:49:41Z" level=error msg="AXFR envelope error: dns: no SOA"
6.12.2016 11:49:42time="2016-12-06T10:49:42Z" level=error msg="AXFR envelope error: dns: no SOA"
6.12.2016 11:49:44time="2016-12-06T10:49:44Z" level=error msg="AXFR envelope error: dns: no SOA"
6.12.2016 11:49:46time="2016-12-06T10:49:46Z" level=error msg="AXFR envelope error: dns: no SOA"
6.12.2016 11:49:47time="2016-12-06T10:49:47Z" level=error msg="AXFR envelope error: dns: no SOA"
6.12.2016 11:49:49time="2016-12-06T10:49:49Z" level=error msg="AXFR envelope error: dns: no SOA"
6.12.2016 11:49:51time="2016-12-06T10:49:51Z" level=error msg="AXFR envelope error: dns: no SOA"
6.12.2016 11:49:52time="2016-12-06T10:49:52Z" level=error msg="AXFR envelope error: dns: no SOA"
6.12.2016 11:49:54time="2016-12-06T10:49:54Z" level=error msg="AXFR envelope error: dns: no SOA"
6.12.2016 11:49:56time="2016-12-06T10:49:56Z" level=error msg="AXFR envelope error: dns: no SOA"
6.12.2016 11:49:57time="2016-12-06T10:49:57Z" level=error msg="AXFR envelope error: dns: no SOA"
6.12.2016 11:49:59time="2016-12-06T10:49:59Z" level=error msg="AXFR envelope error: dns: no SOA"
6.12.2016 11:50:01time="2016-12-06T10:50:01Z" level=error msg="AXFR envelope error: dns: no SOA"
6.12.2016 11:50:02time="2016-12-06T10:50:02Z" level=error msg="AXFR envelope error: dns: no SOA"

**Comment by Toonix** [comment]
I have a serious issue with this AXFR...it's spams my rancher-host and drive cpu and db up.....this could be the reason for my rancher crashes

**Comment by janeczku** [comment]
@ruzarowski I was unable to replicate this with a well configured Bind9 DNS server.
FYI, the "no SOA" error could actually mean one of two things:
1) Your DNS server does not send a SOA record in the AXFR transfer
2) Your DNS server refused or failed to handle the AXFR request (SERVFAIL/REFUSED return code)

If you are still seeing this issue, please provide information about your Bind configuration:
1) zone file
2) whether you are using TSIG authentication and which algorithm

Also provide the output of the following command:

> dig @<SERVER_IP> <ZONE_NAME> axfr +all

and for TSIG authentication

> dig -y <TSIG_KEY>:<TSIG_SECRET> @<SERVER_IP> <ZONE_NAME> axfr +all

**Comment by Toonix** [comment]
@janeczku 


`root@ed265583799c:/# dig dol.pax.ch @192.168.60.201 axfr +all

; <<>> DiG 9.10.3-P4-Ubuntu <<>> dol.pax.ch @192.168.60.201 axfr +all
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 45770
;; flags: qr aa; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1680
;; QUESTION SECTION:
;dol.pax.ch.                    IN      AXFR

;; ANSWER SECTION:
dol.pax.ch.             86400   IN      SOA     dns.dol.pax.ch. zone.dol.pax.ch. 2017021702 2400 360 1209600 300

;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 45770
;; flags: qr aa; QUERY: 1, ANSWER: 31, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1680
;; QUESTION SECTION:
;dol.pax.ch.                    IN      AXFR

;; ANSWER SECTION:
dns.dol.pax.ch.         300     IN      A       192.168.60.201
dokuwiki-server.dokuwiki.dol.pax.ch. 300 IN A   192.168.60.203
dokuwiki-server.dokuwiki99.dol.pax.ch. 300 IN A 192.168.60.202
dokuwiki-server.dokuwiki99.dol.pax.ch. 300 IN A 192.168.60.203
external-dns-adminproject.dol.pax.ch. 300 IN TXT "dokuwiki-server.dokuwiki.dol.pax.ch."
external-dns-adminproject.dol.pax.ch. 300 IN TXT "dokuwiki-server.dokuwiki99.dol.pax.ch."
external-dns-adminproject.dol.pax.ch. 60 IN TXT "ipsec.ipsec.dol.pax.ch."
external-dns-adminproject.dol.pax.ch. 300 IN TXT "openvpn-httpbasic-server.openvpn-httpbasic.dol.pax.ch."
external-dns-adminproject.dol.pax.ch. 300 IN TXT "owncloud.owncloud.dol.pax.ch."
external-dns-adminproject.dol.pax.ch. 300 IN TXT "powerdns.powerdns.dol.pax.ch."
external-dns-adminproject.dol.pax.ch. 60 IN TXT "wordpress.guido.dol.pax.ch."
external-dns-adminproject.dol.pax.ch. 60 IN TXT "wordpress.meinwordpress.dol.pax.ch."
external-dns-adminproject.dol.pax.ch. 300 IN TXT "wordpress.wordpress.dol.pax.ch."
external-dns-adminproject.dol.pax.ch. 300 IN TXT "wordpress.wordpress3.dol.pax.ch."
external-dns-adminproject.dol.pax.ch. 300 IN TXT "wordpress.wordpress6.dol.pax.ch."
external-dns-adminproject.dol.pax.ch. 300 IN TXT "wordpress.wordpress99.dol.pax.ch."
ipsec.ipsec.dol.pax.ch. 60      IN      A       192.168.60.201
ipsec.ipsec.dol.pax.ch. 60      IN      A       192.168.60.202
ipsec.ipsec.dol.pax.ch. 60      IN      A       192.168.60.203
openvpn-httpbasic-server.openvpn-httpbasic.dol.pax.ch. 300 IN A 192.168.60.201
openvpn-httpbasic-server.openvpn-httpbasic.dol.pax.ch. 300 IN A 192.168.60.202
openvpn-httpbasic-server.openvpn-httpbasic.dol.pax.ch. 300 IN A 192.168.60.203
owncloud.owncloud.dol.pax.ch. 300 IN    A       192.168.60.201
powerdns.powerdns.dol.pax.ch. 300 IN    A       192.168.60.201
wordpress.guido.dol.pax.ch. 60  IN      A       192.168.60.202
wordpress.meinwordpress.dol.pax.ch. 60 IN A     192.168.60.203
wordpress.wordpress.dol.pax.ch. 300 IN  A       192.168.60.202
wordpress.wordpress.dol.pax.ch. 120 IN  A       192.168.60.203
wordpress.wordpress3.dol.pax.ch. 300 IN A       192.168.60.203
wordpress.wordpress6.dol.pax.ch. 300 IN A       192.168.60.201
wordpress.wordpress99.dol.pax.ch. 300 IN A      192.168.60.202

;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 45770
;; flags: qr aa; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1680
;; QUESTION SECTION:
;dol.pax.ch.                    IN      AXFR

;; ANSWER SECTION:
dol.pax.ch.             86400   IN      SOA     dns.dol.pax.ch. zone.dol.pax.ch. 2017021702 2400 360 1209600 300

;; Query time: 25 msec
;; SERVER: 192.168.60.201#53(192.168.60.201)
;; WHEN: Wed Mar 01 07:55:04 UTC 2017
;; XFR size: 33 records (messages 3, bytes 1363)
`

The dig with TSIG Key is indeed failing! Pretty strange for me, is that nonless the dns server get the updates!?!? So it seams it is working for updating but not for AXFR? 

`root@ed265583799c:/# dig -y nada:nada dol.pax.ch @192.168.60.201 axfr +all
01-Mar-2017 07:58:43.397 the key 'nada' is too short to be secure
;; Couldn't verify signature: expected a TSIG or SIG(0)

; <<>> DiG 9.10.3-P4-Ubuntu <<>> -y nada dol.pax.ch @192.168.60.201 axfr +all
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOTAUTH, id: 40304
;; flags: qr aa; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1680
;; QUESTION SECTION:
;dol.pax.ch.                    IN      AXFR

; Transfer failed.
`

**Comment by Toonix** [comment]
Just to clarify I was using this:

https://doc.powerdns.com/md/authoritative/tsig/

insert into tsigkeys (name, algorithm, secret) values ('test', 'hmac-md5', 'kp4/24gyYsEzbuTVJRUMoqGFmN3LYgVDzJ/3oRSP7ys=');

and dig is now working, after i changed the password to a more secure one. external-dns is not working with it...complains about base64 not able to axfr.

But hey I found the insecure switch :-) Since it is internal I can life with that.

**Comment by Gmentsik** [comment]
I get the same error, how can this be resolved?

**Comment by Toonix** [comment]
Use insecure if you can.

```
version: '2'
services:
  rfc2136dns:
    image: rancher/external-dns:v0.6.2
    environment:
      NAME_TEMPLATE: '%{{service_name}}.%{{stack_name}}'
      RFC2136_HOST: 172.16.16.134
      **RFC2136_INSECURE: 'true'**
      RFC2136_PORT: '53'
      RFC2136_TSIG_KEYNAME: ''
      RFC2136_TSIG_SECRET: ''
      ROOT_DOMAIN: test.example.com
      TTL: '60'
    expose:
    - '1000'
    command:
    - -provider=rfc2136
    labels:
      io.rancher.container.agent.role: external-dns
      io.rancher.container.create_agent: 'true'
```

**Comment by Gmentsik** [comment]
I have activated the insecure radio button.

The Domains are created in the Domain Controller (Windows Server) but they won't get deleted. The updater is trying to create them constantly (even if it already created them)

![image](https://cloud.githubusercontent.com/assets/11612884/25179549/ac0f6a58-250a-11e7-9e7c-3f466ab71719.png)

**Comment by Toonix** [comment]
Can't help you with that. I use PowerDNS and have then a forwared in the windows DNS to Powerdns.

`version: '2'
volumes:
  PowerDB:
    external: true
    driver: rancher-nfs
services:
  PowerDNS:
    image: argosy/pdns-server:5
    environment:
      DB_ENV_MYSQL_ROOT_PASSWORD: fsdkfdfdsjfhfkjfhs
      PDNS_ALLOW_UNSIGNED_NOTIFY: 'yes'
      PDNS_API: 'yes'
      PDNS_API_KEY: changeme
      PDNS_CACHE_TTL: '20'
      PDNS_DISTRIBUTOR_THREADS: '3'
      PDNS_RECURSIVE_CACHE_TTL: '10'
      PDNS_UPDATE: 'yes'
    stdin_open: true
    tty: true
    links:
    - PowerDB:db
    ports:
    - 53:53/tcp
    - 53:53/udp
    - 8080:80/tcp
    - 8081:8081/tcp
    labels:
      io.rancher.scheduler.affinity:host_label: dns=yes
      io.rancher.container.pull_image: always
  PowerDB:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: fsdkfdfdsjfhfkjfhs
    stdin_open: true
    volumes:
    - PowerDB:/var/lib/mysql
    tty: true
    labels:
      io.rancher.container.pull_image: always
`

**Comment by Gmentsik** [comment]
Ok got it:
The Problem was with Windows DNS, you need to have "DNS Zone Transfer" enabled.
Otherwise the updated can't read the already assigned domains i guess.
![image](https://cloud.githubusercontent.com/assets/11612884/25179914/2afd99b0-250c-11e7-8abd-d02e7345affe.png)
