### ISSUE TITLE
container's port links does not have port information.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6539]
Rancher Version: Build from master

Steps to reproduce the problem:
Create a container with image name "nginx".
container's port links does not have port information.
Expected Result:
This should result in port links of the container having 2 ports 80 and 443.

Automation tests failing:
cattlevalidationtest.core.test_container.test_dynamic_port
cattlevalidationtest.core.test_container.test_linking

**Comment by deniseschannon** [comment]
Unable to reproduce in latest master 11/8 (afternoon) and latest rancher-catalog (11/8 afternoon)

**Comment by sangeethah** [comment]
Tested with latest build from master.
Port information is now available but public port information is not available when ports are exposed resulting cattlevalidationtest.core.test_container.test_dynamic_port and cattlevalidationtest.core.test_container.test_linking still failing. Will log a new issue to track this
