### ISSUE TITLE
When adding new members to a project, if the GitHub user is already logged into the instance, a hard refresh is required to have the project appear in the drop down.

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#654]
v0.18.1

Steps to Reproduce
Enable person A to your Rancher instance
Have person A open the instance
Add a project including the person A. 
If person A clicks around Rancher (goes to a different page and back), the drop down menu doesn't refresh.

Expected result: If I clicked on a different page in Rancher, I'd expect the project to appear in the drop down.

**Comment by vincent99** [comment]
There's currently no websocket events for project changes to preemptively tell me that a new project should appear, and I don't want to poll constantly to see if the list of projects has changed.  We can add an event eventually.

I know this probably isn't what you meant, but a regular click of the reload button will suffice, it doesn't have to be a "hard" reload (holding modifier keys to force the browser to re-request all the cached resources).  Clicking around different sections of the page isn't reloading at all.
