### ISSUE TITLE
ipsec service shows up as 1 service with zero containers in the UI

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#6550]
**Rancher Version:**1.2.0-pre4-rc7

**Docker Version:**1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):**Ubuntu, Cloud

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:**
1. Create a Cattle environment. Ensure all the microservices (dns, metadata, ipsec, network-manager, scheduler, healthcheck) are enabled and start successfully.
2. The ipsec service shows up as 1 service and 0 containers in the Infrastructure stacks page, although ipsec containers show up on each host as expected.
<img width="1351" alt="screen shot 2016-11-07 at 7 54 34 pm" src="https://cloud.githubusercontent.com/assets/18536626/20086374/88d2ba24-a524-11e6-8608-e3e21f73e3bd.png">

**Comment by deniseschannon** [comment]
It might just be a refresh issue? Mine shows up fine:

![screen shot 2016-11-14 at 9 48 47 am](https://cloud.githubusercontent.com/assets/11410997/20276074/9eb09534-aa4f-11e6-9d1a-a6f791fe1ec9.png)

**Comment by soumyalj** [comment]
Tested with master. The issue above is not seen anymore. The ip sec service shows up as 1 service and 6 containers.
