### ISSUE TITLE
Upgrading duplicates or removes service links from the upgrade page

### ISSUE THREAD

**Issue by IanVaughan** [rancher/rancher#6552]
**Rancher Version:**
rancher/server:v1.2.0-pre4-rc6 host1
rancher/agent:v1.1.0-rc7 on hosts1 and host2

**Docker Version:**
host1:1.12.1 / host2:1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04.1 LTS, bear metal

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
2 hosts, host1 server and agent, host2 agent.

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
1. Select Upgrade
1. View Service Links, see that either one is missing/dropped, or a duplicate entry is listed :
    <img width="1523" alt="screen shot 2016-11-08 at 23 03 54" src="https://cloud.githubusercontent.com/assets/158600/20133898/3f54a432-a661-11e6-8719-95e3995e9a8e.png">
1. Re-add missing service link / remove duplicate 
    <img width="1517" alt="screen shot 2016-11-08 at 23 04 08" src="https://cloud.githubusercontent.com/assets/158600/20133891/380af776-a661-11e6-8d52-95f9f8ffa273.png">
1. Upgrade and Finish Upgrade
1. goto 1

**Expected:**
It to keep the same Service Links as the previous Upgrade.

**Comment by deniseschannon** [comment]
Could you share your docker-compose.yml of your stack?

**Comment by vincent99** [comment]
I believe this was fixed in cattle in a later RC..
