### ISSUE TITLE
When rolling back during upgrade for LB, changes stay in place

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#6554]
**Rancher Version:** v1.2.0-pre4-rc7 UI - v1.2.20

**Steps to Reproduce:**
1.  Create two services
2.  Create a load balancer that targets both services
3.  Upgrade load balancer and remove one of the services
4.  Roll back upgrade

**Results:** The service is still removed.

**Expected:** It should have rolled back to original state

**Comment by alena1108** [comment]
@vincent99 @tfiduccia with the latest master, load balancer service "launchConfig.ports" field gets updated with "update", not "upgrade". So both "launchConfig.ports" and "launchConfig.portRules" are being updated with "update" now. 

@vincent99 just to double check that our UI would make this decision based on "u" flag on the field? The API changes are: launchConfig has "u" attribute added, but just for one field - "ports".

**Comment by vincent99** [comment]
@alena1108 No I just wrote code to determine if it needs upgrade based on ports/expose/labels changing.  Removed ports/expose, but I assume you'll still need to upgrade if you change labels (and scheduling/other things that are labels).

**Comment by vincent99** [comment]
(Fixed in master, after rc9)

**Comment by tfiduccia** [comment]
Version - v1.2.0-pre4-rc10
Verified fixed - Service rule moved to edit and no longer requires an upgrade
