### ISSUE TITLE
I can't run rancher-agent

### ISSUE THREAD

**Issue by tonythian** [rancher/rancher#6557]
This is a host that was connecting to a rancher before, and now I am trying to connect it to another rancher server on the different server.

Rancher-agent failed to start, I tried delete /var/lib/rancher/state but same problem. 

log as follow:

INFO: Running Agent Registration Process, CATTLE_URL=http://x.x.x.x:8080/v1
INFO: Checking for Docker version >= 1.6.0
INFO: Found Server version: 1.11.2
INFO: docker version: Client version: 1.6.0
INFO: docker version: Client API version: 1.18
INFO: docker version: Go version (client): go1.4.2
INFO: docker version: Git commit (client): 4749651
INFO: docker version: OS/Arch (client): linux/amd64
INFO: docker version: Server version: 1.11.2
INFO: docker version: Server API version: 1.23
INFO: docker version: Go version (server): go1.6.2
INFO: docker version: Git commit (server): b9f10c9
INFO: docker version: OS/Arch (server): linux/amd64
INFO: docker info: Containers: 43
INFO: docker info: Images: 262
INFO: docker info: Storage Driver: aufs
INFO: docker info: Root Dir: /var/lib/docker/aufs
INFO: docker info: Backing Filesystem: extfs
INFO: docker info: Dirs: 374
INFO: docker info: Dirperm1 Supported: true
INFO: docker info: Execution Driver:
INFO: docker info: Kernel Version: 4.4.0-45-generic
INFO: docker info: Operating System: Ubuntu 16.04.1 LTS
INFO: docker info: CPUs: 4
INFO: docker info: Total Memory: 7.789 GiB
INFO: docker info: Name: ubuntu14
INFO: docker info: ID: X3E5:ELA2:X64X:U3ZK:KP2J:3N4M:PIB6:2LSZ:SJMI:IDEK:NMNM:ELZQ
INFO: docker info: Http Proxy:
INFO: docker info: Https Proxy:
INFO: docker info: No Proxy:
WARNING: No swap limit support
INFO: Attempting to connect to: http://x.x.x.x:8080/v1
INFO: http://x.x.x.x:8080/v1 is accessible
INFO: Inspecting host capabilities
INFO: Systemd: true
INFO: Boot2Docker: false
INFO: Host writable: true
INFO: Token: xxxxxxxx
INFO: Running registration
INFO: Printing Environment
INFO: ENV: CATTLE_ACCESS_KEY=6AB7A12B5F356274EFBD
INFO: ENV: CATTLE_AGENT_IP=y.y.y.y
INFO: ENV: CATTLE_HOME=/var/lib/cattle
INFO: ENV: CATTLE_REGISTRATION_ACCESS_KEY=registrationToken
INFO: ENV: CATTLE_REGISTRATION_SECRET_KEY=xxxxxxx
INFO: ENV: CATTLE_SECRET_KEY=xxxxxxx
INFO: ENV: CATTLE_SYSTEMD=true
INFO: ENV: CATTLE_URL=http://x.x.x.x:8080/v1
INFO: ENV: DETECTED_CATTLE_AGENT_IP=y.y.y.y
INFO: ENV: RANCHER_AGENT_IMAGE=rancher/agent:v1.0.2
invalid value "." for flag -v: . is not an absolute path
See 'docker run --help'.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.1.4` Cattle: `v0.165.8.4` UI: `v1.1.14` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`hosts.index`|

**Comment by tonythian** [comment]
docker info output:

Containers: 51
 Running: 4
 Paused: 0
 Stopped: 47
Images: 262
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 390
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 4.4.0-45-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.789 GiB
Name: ubuntu14
ID: X3E5:ELA2:X64X:U3ZK:KP2J:3N4M:PIB6:2LSZ:SJMI:IDEK:NMNM:ELZQ
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support

**Comment by vincent99** [comment]
Sounds like you modified the `docker run ... rancher/agent ...` command provided in a way that is not valid.  If you still have this issue please post exactly what you're running.
