### ISSUE TITLE
"Lb Config" is required - Error Creating Rancher Load Balancer

### ISSUE THREAD

**Issue by ThatsNinja** [rancher/rancher#6558]
**Rancher Version:**
v1.2.0-pre4-rc7

**Docker Version:**
1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
Rancher Server on generic boot2docker image, VMware-virtualized
Cattle hosts running RancherOS (4.2.8-ckt4-rancher), VMware-virtualized

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Stand-alone Rancher Server

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
1. Upgraded stand-alone Rancher from v1.1.3 to v1.2.0-pre4-rc7 per Rancher-provided [standard method](https://docs.rancher.com/rancher/v1.2/en/upgrading/);
2. Noticed error reconciling deployment in existing Rancher Load Balancer service;
3. Attempted to delete and replace Load Balancer service.

**Results:** 
The Load Balancer would not create. Upon clicking 'Create' an error message is flashed stating, `"LB Config" is required`.

I rolled back and bumped to v1.1.4, and the issue was alleviated. However, there are multiple features in v1.2.0 that we're really clamoring for, and we'd love to be able to roll it back forward.

I have retained the container, and can provide any requested information.

**Expected:**
A Rancher Load Balancer :smiley:

**Comment by vincent99** [comment]
The load balancer API has changed in a way that's requires a migration, which hasn't been finished yet.  For today you'd need to recreate the balancer.

**Comment by ThatsNinja** [comment]
@vincent99 I had destroyed the faulty Load Balancer service and attempted to re-create. Same issue creating a Load Balancer service from scratch.

**Comment by toughIQ** [comment]
Saw same behavior as described by @ThatsNinja. 
Difference: I upgraded from rc6 to rc7.
Since I couldnt get my LB running with rc7, I rolled back to rc6.

**Comment by vincent99** [comment]
I think rc 7 had the new API but not UI to talk to it yet... Anyway in the current build it should work, as should upgrading a 1.1 balancer.
