### ISSUE TITLE
Updating `catalog.refresh.interval.seconds` through API doesn't change the refreshInterval in Catalog service

### ISSUE THREAD

**Issue by mrajashree** [rancher/rancher#6561]
Rancher Version: Rancher Master

Environment Type: Cattle

Steps to Reproduce:
1. Start cattle
2. Change `catalog.refresh.interval.seconds` through cattle API
3. Check server logs for refresh catalog messages

Results:
Catalog is still refreshed based on old interval

Expected:
Refresh should take place on new interval set through API

**Comment by joshwget** [comment]
The change should be reflected if the value is set and then catalog service is restarted. I'm not sure if there's much value in making it update without a restart.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
