### ISSUE TITLE
storage plugin: Deleting a volume doesn't delete the underlying data

### ISSUE THREAD

**Issue by LLParse** [rancher/rancher#6565]
**Rancher Version:** master

**Docker Version:** 1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):** n/a

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** n/a

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** cattle

**Steps to Reproduce:**
1. Create a cattle environment and register 1+ hosts
2. Create a nfsv4 server that is reachable by registered hosts
3. Launch the rancher-nfs template with host/export configuration
4. Create a stack with at least one rancher-nfs volume. [This sample](https://github.com/LLParse/rancher-catalog/tree/nfs-prototype/infra-templates/nfs/prototype) will create a backup every second.
5. Verify data is persisted to the nfs server
6. Delete the stack from UI, then delete the volume from UI

**Results:** Volume path is unmounted, but the data is never deleted. In the logs, rancher-nfs volume plugin never receives the Remove request.

**Expected:** Volume path is unmount, data is deleted

**Comment by LLParse** [comment]
The rancher-nfs, rancher-efs and rancher-ebs plugins are all afflicted by this bug. I believe it is a symptom of https://github.com/rancher/rancher/issues/6566. Leaving the issue open for now.

**Comment by superseb** [comment]
@LLParse Please re-open if this still needs testing
