### ISSUE TITLE
storage plugin: Container sometimes stuck in 'activating' state

### ISSUE THREAD

**Issue by LLParse** [rancher/rancher#6566]
**Rancher Version:** master

**Docker Version:** 1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):** n/a

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** n/a

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** cattle

**Steps to Reproduce:**
1. Create a cattle environment and register 1+ hosts
2. Create a nfsv4 server that is reachable by registered hosts
3. Launch the rancher-nfs template with host/export configuration
4. Create a few stacks with rancher-nfs volumes defined. [This sample](https://github.com/LLParse/rancher-catalog/tree/nfs-prototype/infra-templates/nfs/prototype) may be used.

**Results:** Some containers are in starting/activating state. Behind the scenes, the containers and their volumes are functional.

**Expected:** Containers are in running state.

**Comment by deniseschannon** [comment]
What does the API show versus UI?

**Comment by LLParse** [comment]
API shows state=starting, UI shows the same

**Comment by LLParse** [comment]
@cjellick rancher-nfs, rancher-efs and rancher-ebs are all afflicted by this bug. It only sometimes happens.

If the container gets stuck, there will be 2 rows for a single volume, one in `Inactive` state and another in `Detached` state. This can be seen on the storage screen. Deleting this container will cause the `Inactive` volume to be deleted - the deletion logic is not triggered. Deleting the other `Detached` volume doesn't trigger the deletion logic either.

If the container enters running state, there is only 1 row for the volume in `Active` state. Deleting this container triggers the deletion logic (tested in rancher-ebs).

**Comment by LLParse** [comment]
Figured this one out, changes are part of https://github.com/rancher/storage/pull/18/files. I plan to finish the refactor and test everything at once.

**Comment by LLParse** [comment]
Duplicate of https://github.com/rancher/rancher/issues/3150
