### ISSUE TITLE
rancher-nfs: Unclean plugin removal / Docker thinks volumes are still present

### ISSUE THREAD

**Issue by LLParse** [rancher/rancher#6567]
**Rancher Version:** master

**Docker Version:** 1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):** n/a

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** n/a

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** cattle

**Steps to Reproduce:**

1. Create a cattle environment and register 1+ hosts
2. Create a nfsv4 server that is reachable by registered hosts
3. Launch the rancher-nfs template with host/export configuration
4. Create a few stacks with rancher-nfs volumes defined. This sample may be used.
5. Delete the stacks and corresponding volumes from the UI.
6. Delete the nfs stack.
7. On the agent host, execute `docker volume ls`

**Results:** Some volumes of driver type `rancher-nfs` are listed, client times out trying to communicate to rancher-nfs.sock

**Expected:** No volumes of driver type `rancher-nfs` are listed, response is timely

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
