### ISSUE TITLE
user api keys expire, when using github auth, after ~16 hours

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#6568]
after talking to @prachidamle, seems the user account token in rancher is the problem here (expires in 16 hours). api keys shouldnt invalidate over time.

**Comment by aemneina** [comment]
I'd imagine decoupling api keys from user auth token is the way to go here. @prachidamle can you assess the work involved and schedule the right release for this. I tentatively put 1.2.0, being optimistic here 😃

**Comment by shawnHartsell** [comment]
I submitted the support issue associated with this, let me know if I can help in any way (PRs, testing, etc)

**Comment by galal-hussein** [comment]
Tested on master build (21 Nov), the steps are:

- Enable Github auth
- Create api key with for github user
- Verify that the key can be used to access the API
- Edit the auth_token table and change the expiry date for the token and make sure you are past the expiration date.
- Verify that you can still use the key to access the API.
