### ISSUE TITLE
no connection/ping between rancher hosts

### ISSUE THREAD

**Issue by twobombs** [rancher/rancher#6571]
**Rancher Version:**
1.1.4
**Docker Version:**
1.12.3
**OS and where are the hosts located? (cloud, bare metal, etc):**
ubuntu 14.04 @vcloud, esx & virtualbox
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
internal DB, no HA rancher, two nodes
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle ( default mode )
**Steps to Reproduce:**
install ubuntu 14.04, docker & rancher, add 2 hosts
**Results:** 
no ping between hosts on 10.x network on different hosts ( same host does ping )
**Expected:**
should connect, ping for traffic to route

**Comment by twobombs** [comment]
never mind, it was a user error ( when adding host forgot to enter the IP of that host in the field )

case can be closed

**Comment by aemneina** [comment]
closing issue out.
