### ISSUE TITLE
TypeError: Cannot read property 'EMBEDDED_BACKUPS' of null

### ISSUE THREAD

**Issue by LoicMahieu** [rancher/rancher#6572]
**Rancher Version:**
v1.2.0-pre4-rc7

**Docker Version:**
1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
VM

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
1. Create new environment with Kubernetes stack.
2. Go to Infrastructure Stacks
3. Update `kubernetes` stack
4. Choose a template version

Note: my stack is buggy at this time and has not finish to be setting up...

**Results:** 
The loading spinner is visible. A javascript error is thrown:
```
TypeError: Cannot read property 'EMBEDDED_BACKUPS' of null at /assets/ui-9b137bda111dca3dc8e0311859fdb15a.js:28:17717 at Array.forEach (native) at /assets/ui-9b137bda111dca3dc8e0311859fdb15a.js:28:17571 at C (/assets/vendor-e6fbfdbdd14a475427f5ef269d0cddba.js:21:5492) at A (/assets/vendor-e6fbfdbdd14a475427f5ef269d0cddba.js:21:5578) at k (/assets/vendor-e6fbfdbdd14a475427f5ef269d0cddba.js:21:5395) at invoke (/assets/vendor-e6fbfdbdd14a475427f5ef269d0cddba.js:5:27660) at s.flush (/assets/vendor-e6fbfdbdd14a475427f5ef269d0cddba.js:5:28196) at u.flush (/assets/vendor-e6fbfdbdd14a475427f5ef269d0cddba.js:5:28966) at h.end (/assets/vendor-e6fbfdbdd14a475427f5ef269d0cddba.js:5:29311)
 /assets/vendor-e6fbfdbdd14a475427f5ef269d0cddba.js:9
```

**Expected:**
Variables form to be visible.

**Comment by vincent99** [comment]
This should have been fixed, please try again in the current RC.
