### ISSUE TITLE
Kubernetes: medata: x509: failed to load system roots and no roots provided"

### ISSUE THREAD

**Issue by LoicMahieu** [rancher/rancher#6574]
**Rancher Version:**
v1.2.0-pre4-rc7

**Docker Version:**
1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
Bare metal

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node, external db

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
1. Create a new environment with Kubernetes
2. Add 3 hosts
3. Waiting setting up...
4. metadata stack is in error:
service `metadata` is `Activating`...

**Results:** 
The logs of `metadata` containers output:
10/11/2016 11:47:03time="2016-11-10T10:47:03Z" level=info msg="Subscribing to events"
10/11/2016 11:47:03time="2016-11-10T10:47:03Z" level=fatal msg="Failed to subscribeGet https://rancher.mydomain.com/v2-beta: x509: failed to load system roots and no roots provided"

**Expected:**
Kubernetes stack to be setting up

**Comment by andreimc** [comment]
I get the same thing. @LoicMahieu how did you fix this ?

**Comment by LoicMahieu** [comment]
I couldn't find any workaround right now... Adding `ca-certificates` dependency will certainly fix the issue but I didn't test it.

Can't wait 1.2.0 stable ;)

**Comment by andreimc** [comment]
@LoicMahieu I have it has fixed the issue

**Comment by LoicMahieu** [comment]
Retried with v1.2.0-pre4-rc8 : `rancher-metadata` starts well but now it's the `scheduler` that show the same error:
```
... level=info msg="Connecting to cattle event stream."
... level=info msg="Subscribing to metadata changes."
... level=error msg="Exiting scheduler with error: Cattle event subscriber exited.: Get https://rancher.mysuperdomain.com/v1: x509: failed to load system roots and no roots provided"
```

Source repository for `rancher/scheduler:v0.1.2` is well https://github.com/rancher/scheduler/blob/master/Dockerfile.dapper#L8 ?
Seems that `ca-certificates` is installed...

**Comment by LoicMahieu** [comment]
I should be wrong about the source, `docker run --rm -it rancher/scheduler:v0.1.2 dpkg --get-selections | grep ca-certificates` results nothing !

**Comment by LoicMahieu** [comment]
Ok... get it :) https://github.com/rancher/scheduler/pull/10
