### ISSUE TITLE
Question: Whats The Difference of Using rancher and rancherOS

### ISSUE THREAD

**Issue by g0ld3lux** [rancher/rancher#6575]
Hi Im using windows 10 Pro with HyperV enable...
I find it hard to use rancherOS since it is causing issue with virtual box...
unlike rancher which i can install as a container in my docker-machine...

I dont know why is there 2 Software...
rancher as container and RancherOS 

Can Anyone Explain the Pro  and Cons
Which one do you think is much preferable to use?

Thanks

**Comment by deniseschannon** [comment]
This would be better as a forum question if you are looking for feedback from the community, but Rancher is a platform for managing containers where as RancherOS is an operating system built out of containers. 

They have very different purposes so there is not a direct comparison.

Rancher - http://rancher.com/rancher/
RancherOS - http://rancher.com/rancher-os/
