### ISSUE TITLE
machine won't reconnect after I bump it (rancher-agent)

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#6578]
**Rancher Version:** master 11/10

**Comments**
Machine went down and after i tried to restart it would not reconnect.

**Comment by ibuildthecloud** [comment]
It should reconnect now :)

The agent was exiting and hitting Dockers exponential backoff behavior.  Now the rancher doesn't exit on failure.

**Comment by tfiduccia** [comment]
Version - master 11/22
Verified fixed
