### ISSUE TITLE
metadata logs everything and never rotates

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#6579]
**Rancher Version:** master 11/10

**Comment**
Metadata was logging everything and took up over 6 gigs of my google machine.

**Comment by vincent99** [comment]
https://github.com/rancher/rancher-metadata/pull/30

**Comment by deniseschannon** [comment]
Fixed in metadata v0.6.4

**Comment by tfiduccia** [comment]
Metadata still logging every couple seconds.  Thus filling up logs.
11/18/2016 12:09:16 PMtime="2016-11-18T19:09:16Z" level=debug msg="Searching for: /version" client=10.42.64.228 maxWait=0 oldValue= version=2015-12-19 wait=false
11/18/2016 12:09:16 PMtime="2016-11-18T19:09:16Z" level=debug msg="OK: /version" client=10.42.64.228 version=2015-12-19

**Comment by vincent99** [comment]
Well they're `debug` level now, but we apparently run it on `--debug`...

**Comment by tfiduccia** [comment]
Version - v1.2.0-pre4-rc9
Verified fixed
