### ISSUE TITLE
After I stopped and started machine, new IP did not show up in rancher

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#6580]
**Rancher Version:** master 11/10

**Steps to Reproduce:**
1.  Stop the machine on host side (went to google console and stopped)
2. Wait for host to disconnect on Rancher side
3. Start machine (notice it gets a new IP)
4.  Wait for host to reconnect

**Results:** Host still has old IP showing on rancher UI

**Expected:** Should show new IP

**Comment by sangeethah** [comment]
Tested with rancher-server version - v1.2.0-pre4-rc14

Added "AWS host" as docker-machine host.

Deployed few containers.
Power off the host from AWS console.
Wait for the host to go to "Disconnected" state.
Power on the host.

Once the host gets to "Active" state , we still see the same Ip address for the host in the UI. 
Cross host networking is broken for the container in this service and the health-check container is stuck in "Initializing" state.
