### ISSUE TITLE
Container links are not resolvable.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6584]
Rancher Version: Build from master

Steps to reproduce the problem:
Create a container c1 linked to another container c2 with link name as "client".
From container c1 , not able to reach c2 using linkname "client".

**Comment by ddelnano** [comment]
Does DNS resolution still work if you use the convention service-name.stack-name??  Or what is the workaround for this? I imagine if all service discovery via dns was broken this wouldn't have been pushed back to 1.2.

**Comment by johnrengelman** [comment]
Is there more info on this? It's list as a Major issue for 1.2.0 and from this description is seems incredibly problematic to existing deployments.

**Comment by deniseschannon** [comment]
@ddelnano @johnrengelman This is an issue only with adding standalone containers. If you launch services, then there is no issue. Most users are using services and not standalone containers. If you are using standalone containers, please move to using a service with scale 1 for a workaround.

**Comment by ddelnano** [comment]
Thanks for the clarification, not as big of an issue as I previously thought.

**Comment by mccricardo** [comment]
Lauching `Server` and `Agent on the same host, I've experienced this issue even when launching a stack with multiple services. DNS resolution usoing the convention `service-name.stack-name` works though.

**Comment by deniseschannon** [comment]
In network-services v0.0.6, which uses rancher/dns:v0.10.9. This is located in the `vnext` branch of rancher-catalog.

**Comment by sangeethah** [comment]
Tested with rancher-server - v1.3.0-rc1 with rancher/dns:v0.10.9
Container links are resolvable.
Automation runs relating to container links succeeds.

```
    hosts = client.list_host(kind='docker', removed_null=True)
    assert len(hosts) > 2

    random_val = random_str()
    random_val2 = random_str()

    link_server = client.create_container(name=test_name + '-server',
                                          imageUuid=TEST_IMAGE_UUID,
                                          networkMode=MANAGED_NETWORK,
                                          hostname=test_name + '-server',
                                          environment={
                                              'VALUE': random_val
                                          },
                                          requestedHostId=hosts[2].id)
    link_server2 = client.create_container(name=test_name + '-server2',
                                           imageUuid=TEST_IMAGE_UUID,
                                           networkMode=MANAGED_NETWORK,
                                           hostname=test_name + '-server2',
                                           environment={
                                               'VALUE': random_val2
                                           },
                                           requestedHostId=hosts[1].id)
    link_client = client.create_container(name=test_name + '-client',
                                          imageUuid=TEST_IMAGE_UUID,
                                          networkMode=MANAGED_NETWORK,
                                          ports=['3000:3000'],
                                          hostname=test_name + '-client1',
                                          instanceLinks={
                                              'client': link_server.id
                                          },
                                          requestedHostId=hosts[0].id)

    link_client = client.wait_success(link_client)
    link_client = admin_client.reload(link_client)
    link_server = client.wait_success(link_server)
    link_server = admin_client.reload(link_server)

    ping_link(link_client, 'client', var='VALUE', value=random_val)

    link_server2 = client.wait_success(link_server2)

    link = link_client.instanceLinks()[0]
    link = client.update(link, targetInstanceId=link_server2.id)
    client.wait_success(link)

    ping_link(link_client, 'client', var='VALUE', value=random_val2)

    delete_all(client, [link_client, link_server, link_server2])
```

**Comment by sangeethah** [comment]
When testing with rancher/dns:v0.11.0 , container links are not resolvable.

**Comment by alena1108** [comment]
@sangeethah please test against cattle 1.3

**Comment by sangeethah** [comment]
Tested with rancher-server version - v1.3.0-rc2
This issue is not seen anymore.
