### ISSUE TITLE
Container Network graph does not work (never shows data)

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#6588]
**Rancher Version:** master 11/10 

**Steps to Reproduce:**
1.  Create a container
2. Go to shell and upload large file (install curl, something)

**Results:** Network graph doesn't work

**Expected:** Network graph should work

**Comment:** Network graph works on host

**Comment by vincent99** [comment]
This is only on some containers, like those with managed network

**Comment by tfiduccia** [comment]
Version - 1.2.0-pre4-rc8
Verified fixed
