### ISSUE TITLE
New Catalog items don't show up in Catalog list until browser refresh

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#6589]
**Rancher Version:** master 11/10

**Steps to Reproduce:**
1.  Create a new catalog item (a whole new folder)
2.  Click on the catalog refresh button on catalog page

**Results:** The new catalog item doesn't show up.  I have to hit the browser refresh to see it.

**Expected:**  New catalog should show up when I click on catalog refresh button.

**Comment by vincent99** [comment]
Clears the cache copy when you click refresh now.

**Comment by tfiduccia** [comment]
Version - master 11/15
Verified fixed
