### ISSUE TITLE
removing port rules will cause error even if I have one port left

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#6590]
**Rancher Version:** Version - master 11/10

**Steps to Reproduce:**
1.  Go to load balancer page
2.  Add two more rules
3.  Delete top two
4.  Fill out all information to create load balancer

**Results:** Error that says "Choose one or more port rules to listen on"

**Expected:** Should not get error

**Comment by vincent99** [comment]
FYI it's actually because you were using the move up/down arrows, not adding/removing...

**Comment by tfiduccia** [comment]
Version - master 11/15
Verified fixed
