### ISSUE TITLE
Should  be allowed to create LB services without certificates when protocol is set to TLS/SNI for port rules.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6591]
Rancher Version: Build from master

Steps to reproduce the problem:
Try to create LB services without certificates with protocol set to SNI for port rules.
UI prevents us from doing this:
<img width="1279" alt="screen shot 2016-11-10 at 4 54 50 pm" src="https://cloud.githubusercontent.com/assets/4266958/20200604/ed83bcc2-a766-11e6-8dd3-4603520495e1.png">

**Comment by vincent99** [comment]
oops, yup

**Comment by tfiduccia** [comment]
Version - master 11/15
Verified fixed
