### ISSUE TITLE
Name should be required field in Add Host

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#6595]
**Rancher Version:** master 11/11

**Steps to Reproduce:**
1.  Add Host without Name

**Results:** Able to go through steps, but it will fail because it needs it.

**Expected:** Make Name required

**Comment by tfiduccia** [comment]
Version - master 11/15 - This is "fixed" through the UI.  But we should make it required through the API as well.

**Comment by wlan0** [comment]
I don't know the cattle api well. @cjellick, could you help with the change?

**Comment by vincent99** [comment]
note: It's the **hostname** field that should be required on create; **name** is for the user and optional.

**Comment by wlan0** [comment]
*Name* is required because docker-machine *requires* a name while creating the machine.

**Comment by sangeethah** [comment]
@ibuildthecloud , When "Add Host" is done form UI , in the add host API only hostname is set (name is null ). name is not a requited field in for add host API. the hostname is used when sending request to docker machine.
