### ISSUE TITLE
rancher-ebs: 11 EBS volume limit isn't enforced by scheduler, volume attach fails

### ISSUE THREAD

**Issue by LLParse** [rancher/rancher#6596]
**Rancher Version:** master

**Docker Version:** 1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):** aws

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single node

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** cattle

**Steps to Reproduce:**
1. Create an environment with one AWS instance
2. Launch the `rancher-ebs` template
3. Launch a stack with 12 ebs volumes

**Results:** All containers are scheduled and racher-ebs plugin fails to attach the 12th volume

**Expected:** Scheduler prevents scheduling container(s) such that the 11 EBS volume limit is not exceeded

**Comment by LLParse** [comment]
This one will be the hardest to implement; and the LoE might outweigh the effort. I've scheduled it as lowest possible priority.

Our current design for micro-schedulers involves gathering system information from metadata (pertaining to hosts and/or containersr) in order to make decisions. Currently, metadata does not provide any information about volumes - that would have to change.

To prevent race conditions, the scheduler would also need to track the state of its previous decisions that may not yet be manifested as metadata.

It may be best to defer the requirement of not exceeding 11 vols/host to the end user.

**Comment by StrongMonkey** [comment]
@LLParse I think the limit is 40 http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/volume_limits.html. And the 11 limit is set in this block of code https://github.com/rancher/storage/blob/master/package/ebs/rancher-ebs#L61 😄

**Comment by LLParse** [comment]
Why don't you try 12 and see what happens? ;-)

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
