### ISSUE TITLE
Virtual Machine missing from menu

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#6603]
**Rancher Version:** master 11/11

**Steps to Reproduce:**
1.  Go to infrastructure menu

**Results:** Virtual machine is missing (also missing from services)

**Expected:**  Should be there.

**Comment by vincent99** [comment]
Not supported in 1.2.0 backend...

**Comment by tfiduccia** [comment]
Version - Removed VMs and when we add them back in there will be a full test pass.  So don't need this bug anymore.
