### ISSUE TITLE
Orchestration is always showing as cattle in telemetry

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#6605]
**Rancher Version:** master 11/11

**Steps to Reproduce:**
1.  Create a cattle, mesos, k8s, and swarm environments
2.  Run telemetry report
3.  View telemetry report

**Results:** In environment section all are going under cattle in the orch section.

**Expected:** Should recognize that they are not cattle and report accordingly

**Comment by vincent99** [comment]
https://github.com/rancher/telemetry/pull/8

**Comment by tfiduccia** [comment]
Version - v1.2.0-pre4-rc8
Verified fixed
