### ISSUE TITLE
Rancher stuck forever trying to delete/stop non-existent container

### ISSUE THREAD

**Issue by bradjones1** [rancher/rancher#6608]
**Rancher Version:**

Server 1.2.0-pre3, agent 1.0.2

**Docker Version:**

1.12.1 (on host with agent)

**OS and where are the hosts located? (cloud, bare metal, etc):**

Ubuntu 14.04.4, on the Softlayer Cloud.

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

Single-node rancher server, external dB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

Cattle stack on a swarm environment

**Steps to Reproduce:**

Create or scale up a stack. In my case, the container in question never started because it was stuck in the Starting (Networking) state. Attempt to delete the container.

**Results:** 

Rancher endlessly tries to delete the container, but can't, either reporting an error on the process with `RESOURCE_BUSY` status or stalling at volume.deactivate.

![screenshot from 2016-11-12 14-19-31](https://cloud.githubusercontent.com/assets/981966/20240957/b5f737ba-a8e3-11e6-888f-d051420c19cd.png)

![screenshot from 2016-11-12 14-25-12](https://cloud.githubusercontent.com/assets/981966/20240959/d86781a6-a8e3-11e6-9a32-d90c86e2de49.png)

**Expected:**

Rancher should recognize the container doesn't exist on the host, reconcile the service stack, and not stall on attempting to stop or delete. I think this could be similar to the issues described in https://github.com/rancher/rancher/issues/4974

**Comment by vincent99** [comment]
This should be fixed in 1.3+ and running the 1.1 cleanup script, see `docker run --rm rancher/cleanup-1-1` for usage.
