### ISSUE TITLE
ipsec container not able to start successful on docker 1.10/1.11 hosts.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6610]
Rancher server version - Build from master

Rancher server setup with hosts having docker 1.10/1.11 versions.

Set catalog - library to https://github.com/rancher/community-catalog , 1.2 branch.

wait for the infrastructure stacks to come up.

healthcheck/ipsec/network-manager/scehduler stacks are all stuck in "Activating" state forever.

ip sec container fails to start with the following error message:

 ```Activating (Expected state running but got error: Timeout getting IP address)```

**Comment by MihaiSandor** [comment]
Docker Windows?

**Comment by sangeethah** [comment]
Tested with latest builds from master:

Infra structure stacks are able to start successfully using rancher server setup with hosts having docker 1.10/1.11 versions.
