### ISSUE TITLE
Adding a new host through UI throws an error "Name is required"

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#6616]
**Rancher Version:**Master

**Docker Version:**1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):**Ubuntu, Cloud

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** Single node

**Steps to Reproduce:**
1. Create a Cattle/Kubernetes environment.
2. Add a digital ocean/AWS host using the UI 
3. Clicking on 'create' gives an error "Name is required".
Host addition is not successful. 

<img width="1234" alt="screen shot 2016-11-14 at 3 23 07 pm" src="https://cloud.githubusercontent.com/assets/18536626/20287470/8b647dec-aa81-11e6-8117-2dafc35d6c52.png">

**Comment by tfiduccia** [comment]
Looks like Vincent fix it.

**Comment by soumyalj** [comment]
Tested with master. The issue above is not seen. Able to create one and multiple hosts successfully.
