### ISSUE TITLE
When hosts are powered down and then powered back on , they are not getting added for health check monitoring.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6618]
Rancher Version: Build from master

Steps to reproduce the problem:
Setup has 3 hosts  (h1,h2,h3)
Create health check enabled services.
Pick an instance running on h1 and make sure its health is being monitored by h2 and h3.
Power down h2.
This instance is now being monitored by h3 only as expected.
Power on host h2.
Even after host gets to "Active" state and the health-check container is started successfully on this host, it never starts to perform health check monitoring for existing instances.

**Comment by franciscocpg** [comment]
I am facing this problem right now.
Is there any workaround?

**Comment by sangeethah** [comment]
Tested with latest build from master.
This issue is not seen anymore.
Host that was powered down and back up , is now getting added back to monitor health of instances.
