### ISSUE TITLE
CPU/Memory/Storage moniter unavaliable on alpine containers

### ISSUE THREAD

**Issue by twoeo** [rancher/rancher#6621]
**Rancher Version:** 
1.1.4

**Docker Version:**
1.12.0

**OS and where are the hosts located? (cloud, bare metal, etc):**
CentOS Linux 7.2.1511
Cloud (Aliyun)

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
DockerFile:
FROM alpine:edge

**Results:** 
CPU/Memory/Storage moniter unavaliable (no data)
Network moniter works

**Expected:**
All 4 moniter works

**Comment by deniseschannon** [comment]
Container stats in 1.1.4 are reliant on cadvisor, which has been as of our v1.2.0-pre4-rcX releases. 

In the next stable version release of Rancher, container stats will be using `docker stats`
