### ISSUE TITLE
EC2 add hosts does not work

### ISSUE THREAD

**Issue by vishal-biyani** [rancher/rancher#6622]
**Rancher Version:**
v 1.1.4

**Docker Version:**
1.12.3 and API version 1.24

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04.1 LTS (Xenial Xerus) on AWS 

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node Rancher master, internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
From kubernetes environment, add hosts with "Amazon EC2" as option and enter all required details. 

**Results:** 

![image](https://cloud.githubusercontent.com/assets/1167948/20296205/7d552716-ab2f-11e6-8806-7d9154c3c5f5.png)

With "rancher" as user:
```
Error checking the host: Error checking and/or regenerating the certs: There was an error validating certificates for host "52.91.217.147:2376": tls: DialWithDialer timed out
```

With Ubuntu user:

```
Error detecting OS: Too many retries waiting for SSH to be available. Last error: Maximum number of retries (60) exceeded
```
The logs with rancher user:
```
time="2016-11-15T07:00:24Z" level=info msg="stdout: (kube01) Launching instance..." resourceId: =1ph15 
time="2016-11-15T07:00:48Z" level=info msg="stdout: Waiting for machine to be running, this may take a few minutes..." resourceId: =1ph15 
time="2016-11-15T07:00:48Z" level=info msg="stdout: Detecting operating system of created instance..." resourceId: =1ph15 
time="2016-11-15T07:00:48Z" level=info msg="stdout: Waiting for SSH to be available..." resourceId: =1ph15 
time="2016-11-15T07:02:49Z" level=info msg="stdout: Detecting the provisioner..." resourceId: =1ph15 
time="2016-11-15T07:02:49Z" level=info msg="stdout: Provisioning with rancheros..." resourceId: =1ph15 
time="2016-11-15T07:02:50Z" level=info msg="stdout: Copying certs to the local machine directory..." resourceId: =1ph15 
time="2016-11-15T07:02:52Z" level=info msg="stdout: Copying certs to the remote machine..." resourceId: =1ph15 
time="2016-11-15T07:02:53Z" level=info msg="stdout: Setting Docker configuration on the remote daemon..." resourceId: =1ph15 
time="2016-11-15T07:03:10Z" level=info msg="stdout: Checking connection to Docker..." resourceId: =1ph15 
time="2016-11-15T07:03:14Z" level=info msg="stdout: The default lines below are for a sh/bash shell, you can specify the shell you're using, with the --shell flag." resourceId: =1ph15 
time="2016-11-15T07:03:14Z" level=info msg="stdout: " resourceId: =1ph15 
time="2016-11-15T07:03:14Z" level=info msg="stderr: Error creating machine: Error checking the host: Error checking and/or regenerating the certs: There was an error validating certificates for host \"52.91.217.147:2376\": tls: DialWithDialer timed out" resourceId=1ph15 
time="2016-11-15T07:03:14Z" level=info msg="stderr: You can attempt to regenerate them using 'docker-machine regenerate-certs [name]'." resourceId=1ph15 
time="2016-11-15T07:03:14Z" level=info msg="starting cleanup..." machine name=kube01
```

The logs with Ubuntu user:

```
time="2016-11-15T07:20:20Z" level=info msg="stdout: (kube01) Launching instance..." resourceId: =1ph16 
time="2016-11-15T07:20:44Z" level=info msg="stdout: Waiting for machine to be running, this may take a few minutes..." resourceId: =1ph16 
time="2016-11-15T07:20:44Z" level=info msg="stdout: Detecting operating system of created instance..." resourceId: =1ph16 
time="2016-11-15T07:20:44Z" level=info msg="stdout: Waiting for SSH to be available..." resourceId: =1ph16 
time="2016-11-15T07:25:40Z" level=info msg="stdout: The default lines below are for a sh/bash shell, you can specify the shell you're using, with the --shell flag." resourceId: =1ph16 
time="2016-11-15T07:25:40Z" level=info msg="stdout: " resourceId: =1ph16 
time="2016-11-15T07:25:40Z" level=info msg="stderr: Error creating machine: Error detecting OS: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded" resourceId=1ph16 
time="2016-11-15T07:25:40Z" level=info msg="starting cleanup..." machine name=kube01 
time="2016-11-15T07:25:40Z" level=info msg="cleanup successful" machine name=kube01 
time="2016-11-15T07:25:40Z" level=error msg="Error processing event" err="Error detecting OS: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded" eventId=77c88c29-6014-4487-af38-349245540e87 eventName="physicalhost.create;handler=goMachineService" resourceId=1ph16 
```

**Expected:**
EC2 hosts should be added seamlessley and should not time out. Once I tried adding 12-15 hosts and only 2-3 got added eventually

**Comment by aemneina** [comment]
can you share the zone and ami youre using? Also are you using 'ubuntu' or 'Ubuntu' as the user? Can you also confirm the security group youre using? Are your rancher server AND rancher agents in AWS, or only agents?

**Comment by nano2yk** [comment]
I'm having the exact same issue.
**AMI ID**
ubuntu/images/hvm-ssd/ubuntu-wily-15.10-amd64-server-20151116.1 (ami-16b1a077)
**Availability zone**
us-west-2a
**User**
ubuntu
**Security groups**
rancher-machine
Also opened all traffic on all ports for both servers (both in same zone in AWS)

Thanks for the help.

**Comment by aemneina** [comment]
@nano2yk I did a quick deployment from rancher using the EC2 machine driver with that AMI and was able to provision. Can you confirm that the outbound traffic on the security groups are open? Does the outbound sec group use anywhere (0.0.0.0/0) as the destination? Was the host stuck on 'waiting to ssh' from the rancher UI?

**Comment by vishal-biyani** [comment]
@aemneina 
region us-east-1

I used "ubuntu" as user

Security group on source (Rancher server) as well as target (Agent) machines was kept all ports open from all sources. Used AMI ami-dfdff3c8. Also rancher server and agent all are in same region and in AWS.

**Comment by vishal-biyani** [comment]
@aemneina can you please confirm your settings and I can try with same settings!

**Comment by deniseschannon** [comment]
These seem like they are  all docker-machine related issues, nothing directly to Rancher. 

Are you able to use the same docker-machine command to create hosts  using Docker Machine? In the logs, you should be able to get the docker machien command, it starts something like "cmd slice ["create ..."].

If you can try using the to do `docker-machine create..." to see if it works locally, that'd be the first step.

**Comment by aemneina** [comment]
@vishal-biyani the user for rancheros is rancher... can you also try provisioning with a rancheros v0.4.5 as a sanity check.

**Comment by vishal-biyani** [comment]
@aemneina Thanks, tried with 0.4.9 AMI (us-east-1 and ami-812ec0ec) and also rancheros-v0.7.1-hvm-1 (ami-dfdff3c8) and both worked with rancher user. Appreciate it.

**Comment by vishal-biyani** [comment]
Also worked without specifying the AMI and using ubuntu user.
