### ISSUE TITLE
do not let users delete the running rancher/agent container

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#6626]
we will no longer be hiding the rancher/agent containers by default (#6483). instead we will no longer allow being able to delete the running rancher/agent container.

**Comment by sangeethah** [comment]
Tested with v1.2.0-pre4-rc12.
UI does not given option to "restart"/"stop"  rancher/agent containers by default. When attempting using api , we get the following error 
``` code": "ActionNotAvailable",
"message": "Can not delete rancher-agent"```
