### ISSUE TITLE
Sort templates in some sort of alphabetic order

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#6629]
**Rancher Version:** Master 11/15

**Steps to Reproduce:**
1.  Add a bunch of new environment templates
2.  go to Create environment

**Results:** Templates are not sorted by type or name.

**Expected:**  Sort by type (Cattle, Mesos...) then by Name?

**Comment by tfiduccia** [comment]
couple of issues here:

1.  Should probably sort on template type first then name
2.  First time I enter a template, it always goes to the last space no matter type or name.  Until refresh

**Comment by vincent99** [comment]
Updates sorting now

**Comment by tfiduccia** [comment]
Version - master 11/22
