### ISSUE TITLE
When I turn off Authentication, the Stacks drop-down no longer works (doesn't think I'm an owner for environment)

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#6632]
**Rancher Version:** master 11/15

**Steps to Reproduce:**
1.  Turn on authentication (I turned on github)
2.  Turn off authentication
3.  Hover over Stacks drop-down

**Results:** Infrastructure stacks missing.  Looks like the environment no longer thinks I'm an owner so things are broken.

**Expected:**  Should not still have owners/members to environments when I turn off auth.

**Comment by prachidamle** [comment]
@vincent99 isnt this a UI issue? After auth is off, I see UI correctly removing the user profile from top right corner, so why not revert to Stacks default dropdown

**Comment by vincent99** [comment]
@prachidamle I think this was the same issue where admins didn't get treated like owner (stack.system field createable)

**Comment by prachidamle** [comment]
@tfiduccia is the issue that the Infrastructure stacks are first seen when auth is on and then it is not seen when auth is off?

If yes, then @vincent99 I think this is not same issue as if it was then Infrastructure stacks wont be seen anytime

**Comment by tfiduccia** [comment]
Version - master 11/18
Verified fixed
