### ISSUE TITLE
Windows supports

### ISSUE THREAD

**Issue by StrongMonkey** [rancher/rancher#6638]
For supporting windows container in Cattle, the following task list needs to be finished:

- [ ] https://github.com/rancher/agent/pull/87 should be merged. This PR addressed the point that host-api should be migrated into agent code and can be run inside agent process.

- [ ] agent runs in container and the way it talks to the daemon in the host is by using network stack. This means that users have to explicitly configure their docker daemon before registering their host in rancher.By default windows container talks to a named pipe and that named pipe can not be bind into container. Not sure if it is good to run agent.exe directly on the host.

- [ ] we need a clean template for windows environment, the infra stack doesn't apply to window. So for windows environment, maybe don't add any infrastructure stack to it now.

- [ ] add network mode `nat`,  `transparent` to cattle API, hide other linux network mode when in windows environment

- [ ] Add parsing volume support in windows style. (C:/foo:C:/bar)

- [ ] agent is still receiving `config.update` in windows host. Maybe we could stop sending this event by telling different host OS types.

- [ ] https://github.com/StrongMonkey/agent-image. Dockerfile for rancher/agent on windows is ready to be reviewed.

- [ ] fix UI for windows environment(Changing the registration command, hiding linux specific fields and windows container stats until it get supported in 1.13)

- [ ] LB refactor for windows.

- [ ] Add CI for windows

**Comment by StrongMonkey** [comment]
@cjellick @ibuildthecloud @will-chan @deniseschannon

**Comment by StrongMonkey** [comment]
@sangeethah Can you follow the steps in UI and start testing some basic functions(like start container, stop container and remove container) in Windows?

**Comment by sangeethah** [comment]
Tested with latest build from master:
Able to add Windows hosts successfully.
Able add/delete services. 
Able to do exec contaners , container stats and logs.
Host stats are also functional.


Following are some issues seen when testing this feature:

https://github.com/rancher/rancher/issues/7098
https://github.com/rancher/rancher/issues/7097
https://github.com/rancher/rancher/issues/7101
