### ISSUE TITLE
Upgrading services - always wait for container to start before proceeding to another one

### ISSUE THREAD

**Issue by JendaPlhak** [rancher/rancher#6640]
**Rancher Version:**
v1.1.4
**Docker Version:**
1.12
**OS and where are the hosts located? (cloud, bare metal, etc):**
Linux, bare metal
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
Upgrade >> Batch size 1. 
**Results:** 
When upgrading with specific batch size, say 1. I would expect rancher to go one by one, upgrade one container and then wait for it to start again - it should make sure, that the container is actually up and running. Even if health-check is not set. It happened couple of times to me that rancher just shut down all containers. This behaviour is very unfortunate and can very easily cause service outage which is highly undesirable. 
**Expected:**
If batch size is k, total number of containers is n, there always should be at least n-k containers running.

**Comment by blackside** [comment]
This has happened to me too.
Randomly on an upgrade rancher shuts down both instances of my application while starting the first upgrade instance....

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
