### ISSUE TITLE
Invalid reference format while starting services

### ISSUE THREAD

**Issue by aimartin** [rancher/rancher#6641]
**Rancher Version:** 1.2.0-pre4-rc6

**Docker Version:**
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 22:01:48 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 22:01:48 2016
 OS/Arch:      linux/amd64

**OS and where are the hosts located? (cloud, bare metal, etc):** 
cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.1 LTS"
Running over a Mac Mini 2013

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node Rancher with External DB running in a Synology NAS as docker container

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:**
1. Inside a stack, add a Service
2. Set any name
3. Set image from private registry: hub.domain.ltd:5000/name
4. Click on Create

**Results:** 
New service is added, with image changed to hub.domain.ltd:5000/name:latest. It tries to start, but ends in error: Expected state running but got error: Invalid reference format
![bug](https://cloud.githubusercontent.com/assets/7315747/20357006/a03a9f16-ac26-11e6-9653-eccb8a37cc07.png)

**Expected:**
New service is added, and starts successfully

**Extra Information:**
Even if you try to upgrade an existing (and working) service, using the same image, it ends in the error. However, rollback works as expected.
I've checked docker ps during the startup, and the container is never started.
Logs from server shows this:
2016-11-16 17:04:29,114 ERROR [486b0191-0d3b-41a7-b642-c67e7e620d05:56192] [instance:3357-&gt;instanceHostMap:448] [instance.start-&gt;(InstanceStart)-&gt;instancehostmap.activate] [] [cutorService-41] [c.p.e.p.i.DefaultProcessInstanceImpl] Agent error for [compute.instance.activate.reply;agent=51]: invalid reference format
I've tested it with rc7 and doesn't work either (and I got more errors doing other stuff)

**Comment by tfiduccia** [comment]
We probably broke the ability to have port in url.

**Comment by StrongMonkey** [comment]
i believe the fix was in rc7. I tested it locally and it works fine. @aimartin  Can you try with rc7? or could you show me the error msg in rc7?

**Comment by aimartin** [comment]
I've tested it with 1.2.0-pre3-rc2 (the version I had before the pre4-rc6) and I can confirm my setup and image works. I will try again with RC7 and let you know :).

Regards

**Comment by deniseschannon** [comment]
@aimartin Would you be willing to wait until rc8? rc7 out of the box doesn't work, incorrect UI tag, an  incorrect branch for library catalog, and no infra services automatiocally started for the default environment.

**Comment by aimartin** [comment]
I was about to say that I wasn't able to even start the service, the UI is not working fine (not create button, if I click in primary service it restarts...).

I will wait and test with RC8, and in the meantime, I will go back to the version I had before :). Do you have a tentative date for RC8?

Regards

**Comment by deniseschannon** [comment]
@aimartin Would you be able to test with rc9? it's now available

**Comment by deniseschannon** [comment]
@aimartin If this is still an issue after 1.2 ships, please reopen.

**Comment by aimartin** [comment]
Sorry for the late answer. Tested in 1.2.0, seems to be working fine.

Thanks!
