### ISSUE TITLE
No Swarm or Kubernetes options in Add Environment page

### ISSUE THREAD

**Issue by jclif** [rancher/rancher#6643]
**Rancher Version:**
v1.2.0-pre4-rc7

**Docker Version:**
1.10

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 12.06 on EC2

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node with MySQL

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
N/A

**Steps to Reproduce:**
1. Run new instance.
2. Enable Github Auth.
3. Click on Add Environment from the Manage Environments page.

**Results:** 
Cattle is the only option:
<img width="962" alt="screen shot 2016-11-16 at 1 50 25 pm" src="https://cloud.githubusercontent.com/assets/3463691/20360938/bcd68612-ac03-11e6-9306-c18e25f9dd26.png">

**Expected:**
The options include: Cattle, Kubernetes, and Swarm

**Comment by deniseschannon** [comment]
rc7 out of the box doesn't work, incorrect UI tag, an incorrect branch for library catalog, and no infrastructure services automatically started for the default environment.

In the next rc version, these issues should be fixed and hte default environment templates will be available.
