### ISSUE TITLE
Going to empty stack for tag that was removed

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#6651]
**Rancher Version:** master 11/16

**Steps to Reproduce:**
1.  Create a stack and give it a tag (tag1)
2.  Go to Stacks menu and select tag1
3.  Edit the stack and remove the tag and save

**Results:** Still in "tag1" stack even though it actually gone now.
![image](https://cloud.githubusercontent.com/assets/11514927/20370457/0759a6f2-ac1c-11e6-82ac-1279c9a39cb1.png)

**Expected:**  Should go back to user stack

**Comment by vincent99** [comment]
![image](https://cloud.githubusercontent.com/assets/753917/20410528/ba234928-acda-11e6-9ae4-a6fa816697fe.png)

**Comment by tfiduccia** [comment]
Version - v1.2.0-pre4-rc8
Verified fixed
