### ISSUE TITLE
Does Rancher support private Dockerhub repos?

### ISSUE THREAD

**Issue by jclif** [rancher/rancher#6654]

**Comment by vincent99** [comment]
Yes.

**Comment by jclif** [comment]
I've tried to add both Dockerhub and Quay credentials, but when I try to create containers from private Dockerhub images, it says the image can't be found, and when I try to create Quay private images, it throws 403. Are there any additional things that need to happen besides going to the Registries tab and adding a set of credentials?

**Comment by jclif** [comment]
@vincent99 It appears that I can execute `docker login` from the CLI, using the exact same credentials that I used on the Registries page, and successfully pull the image manually, then adding the private image as a project in my swarm works find. I'm not sure why the GUI isn't working.

**Comment by tfiduccia** [comment]
@jclif which version of rancher are you using?

**Comment by jclif** [comment]
@tfiduccia I believe I am using the image tagged as 'latest'. Here are all of my Cattle path variables:

<img width="1012" alt="screen shot 2016-11-17 at 8 34 56 am" src="https://cloud.githubusercontent.com/assets/3463691/20391324/e5f4392a-aca0-11e6-9f15-a02777ed20bd.png">

**Comment by jclif** [comment]
@tfiduccia @vincent99 It's definitely understandable if nothing looks out of place, but if any suggestions come to mind, I would greatly appreciate it. After Thanksgiving, I'll be demo-ing Rancher to the DevOps guild at my company (we are currently looking for services to assist us in moving to a swarm infrastructure), so it'd be super awesome to have this piece working, but definitely not necessary.

**Comment by jclif** [comment]
After trying a Cattle environment, interestingly, the registry functionality works just fine.
