### ISSUE TITLE
Rancher UI env_file vs volume path

### ISSUE THREAD

**Issue by adi90x** [rancher/rancher#6663]
**Rancher Version:**
v1.2.0-pre3
**Docker Version:**
1.12.3
**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04.1 LTS - Cloud Server
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher , internal DB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
Starting a docker-compose project from the rancher UI 
env_file variable seems to look in the rancher-server containers
while volumes are mount from host.

Let say : 

On host I have  : /home/username/data/{several files}
and /home/username/data/.env

rancher-server is started with a volume : /home/username/data/:/data

then on the ui if I want to start a container using environment value from .env and mounting volume /home/username/data/ to /data the only working way seems to put in docker-compose.yml textbox : 

env_file: /data/.env
volumes:  /home/username/data/:/data

**Expected:**
 Is this a normal behavior ? ie :  mounting volume from host but using env_file from rancher-server containers ? 

Thanks a lot, 
Regards,

**Comment by vincent99** [comment]
The Rancher compose executor service runs in the server container and interprets the environment file.  For a HA setup there is no actual guarantee that the compose file will be interpreted on any one host in particular, so using env_file is not very practical.

The actual container being run is scheduled to a host and volumes come from that host.
