### ISSUE TITLE
Health check containers stuck in "Initializing" state forever because of ip inject failure.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6665]
Rancher Version: v1.2.0-pre4-rc8

Rancher server set up with 3 hosts added.

Even though , catalog - library was set to "1.2" brach of https://github.com/rancher/rancher-catalog/ automatically , infra structure stacks did not deploy automatically. 

Triggered their deployment by doing a manual upgrade of "Default" environment.

All infra stacks came up successful , but 1 instance of health check is stuck in "Initializing" forever.

ip inject on health check containers failed
```
11/17/2016 6:46:24 PMtime="2016-11-18T01:46:24Z" level=info msg="Evaluating state from retry" cid=25d7caf80078314fca04b5b5732b4d196e31af31b06de81f8a8c660bc69ade6c
11/17/2016 6:46:24 PMtime="2016-11-18T01:46:24Z" level=info msg="CNI up" cid=25d7caf80078314fca04b5b5732b4d196e31af31b06de81f8a8c660bc69ade6c networkMode=ipsec
11/17/2016 6:46:24 PMtime="2016-11-18T01:46:24Z" level=error msg="Failed to evaluate networking: Bringing up networking: failed to find plugin \"rancher-bridge\" in path [/opt/cni/bin /var/lib/cni/bin /usr/local/sbin /usr/sbin /sbin /usr/local/bin /usr/bin /bin]"
11/17/2016 6:46:25 PMtime="2016-11-18T01:46:25Z" level=info msg="Evaluating state from retry" cid=25d7caf80078314fca04b5b5732b4d196e31af31b06de81f8a8c660bc69ade6c
11/17/2016 6:46:25 PMtime="2016-11-18T01:46:25Z" level=info msg="CNI up" cid=25d7caf80078314fca04b5b5732b4d196e31af31b06de81f8a8c660bc69ade6c networkMode=ipsec
11/17/2016 6:46:25 PMtime="2016-11-18T01:46:25Z" level=error msg="Failed to evaluate networking: Bringing up networking: failed to find plugin \"rancher-bridge\" in path [/opt/cni/bin /var/lib/cni/bin /usr/local/sbin /usr/sbin /sbin /usr/local/bin /usr/bin /bin]"
11/17/2016 6:46:26 PMtime="2016-11-18T01:46:26Z" level=info msg="Evaluating state from retry" cid=25d7caf80078314fca04b5b5732b4d196e31af31b06de81f8a8c660bc69ade6c
11/17/2016 6:46:26 PMtime="2016-11-18T01:46:26Z" level=info msg="CNI up" cid=25d7caf80078314fca04b5b5732b4d196e31af31b06de81f8a8c660bc69ade6c networkMode=ipsec
11/17/2016 6:46:26 PMtime="2016-11-18T01:46:26Z" level=error msg="Failed to evaluate networking: Bringing up networking: failed to find plugin \"rancher-bridge\" in path [/opt/cni/bin /var/lib/cni/bin /usr/local/sbin /usr/sbin /sbin /usr/local/bin /usr/bin /bin]"
11/17/2016 6:46:31 PMtime="2016-11-18T01:46:31Z" level=info msg="Applying new port rules"
11/17/2016 6:46:31 PMiptables: No chain/target/match by that name.
```

**Comment by sangeethah** [comment]
Rancher Version: v1.2.0-pre4-rc9

This issue is not seen anymore.
In a setup with 3 hosts ,health check instances come up successfully and get to "healthy" state.
Added 1 more host ,health check instances come up successfully and get to "healthy" state on the newly added host.
powered down 1 of the host and powered it back on. ,health check instances come up successfully when the host is powered back on and get to "healthy" state.

**Comment by johnculviner** [comment]
Just in case anyone else has this issue (was the first link on Google I found). I had this issue in OpenStack because I was using the public IPs of servers when I did "add host" and I didn't have wide open ingress and egress rules setup (for TCP, UDP and IMCP). Not sure which are actually required and wide open is fine with me: Did that and everything is golden!

**Comment by wmbutler** [comment]
@johnculviner do you have any more detail on the ports that you opened? According to rancher's docs, only 500 and 4500 UDP need to be opened.

**Comment by johnculviner** [comment]
Just did wide open, probably not an ideal situation. Perhaps a ```netstat``` or ```lsof``` when rancher is running could help you diagnose?

**Comment by simon-hardy** [comment]
This problem is still seen in Rancher v1.5.5

![error](https://cloud.githubusercontent.com/assets/9372609/25234705/d44930d2-25da-11e7-82d2-22a1f25d4aff.JPG)

**Comment by pdefert** [comment]
the problem still exist in 1.5.5
see the log of healthcheck

> 24/04/2017 16:31:39time="2017-04-24T14:31:39Z" level=info msg="Scheduling apply config"
24/04/2017 16:31:39time="2017-04-24T14:31:39Z" level=info msg="healthCheck -- reloading haproxy config with the new config changes\n[WARNING] 113/143139 (186) : config : 'option forwardfor' ignored for proxy 'web' as it requires HTTP mode.\n[WARNING] 113/143139 (186) : config : 'option forwardfor' ignored for backend 'cattle-a2c7d960-d392-425f-8e05-c9bbcb098ade_7bc8f6eb-0cee-4adf-98a7-e06613bcf674_1' as it requires HTTP mode.\n"
24/04/2017 16:31:40time="2017-04-24T14:31:40Z" level=info msg="Scheduling apply config"
24/04/2017 16:31:40time="2017-04-24T14:31:40Z" level=info msg="healthCheck -- reloading haproxy config with the new config changes\n[WARNING] 113/143140 (193) : config : 'option forwardfor' ignored for proxy 'web' as it requires HTTP mode.\n[WARNING] 113/143140 (193) : config : 'option forwardfor' ignored for backend 'cattle-a2c7d960-d392-425f-8e05-c9bbcb098ade_7bc8f6eb-0cee-4adf-98a7-e06613bcf674_1' as it requires HTTP mode.\n"
24/04/2017 16:31:40time="2017-04-24T14:31:40Z" level=info msg="Scheduling apply config"
24/04/2017 16:31:40time="2017-04-24T14:31:40Z" level=info msg="healthCheck -- no changes in haproxy config\n"
24/04/2017 16:31:40time="2017-04-24T14:31:40Z" level=info msg="Scheduling apply config"
24/04/2017 16:31:40time="2017-04-24T14:31:40Z" level=info msg="healthCheck -- no changes in haproxy config\n"
24/04/2017 16:31:41time="2017-04-24T14:31:41Z" level=info msg="Monitoring 2 backends"
24/04/2017 16:31:43time="2017-04-24T14:31:43Z" level=info msg="a2c7d960-d392-425f-8e05-c9bbcb098ade_f831d50b-3279-4246-b905-f7dca6e2a5ca_10=DOWN"
24/04/2017 16:31:50time="2017-04-24T14:31:50Z" level=info msg="Scheduling apply config"
24/04/2017 16:31:50time="2017-04-24T14:31:50Z" level=info msg="healthCheck -- no changes in haproxy config\n"
24/04/2017 16:32:00time="2017-04-24T14:32:00Z" level=info msg="Scheduling apply config"
24/04/2017 16:32:00time="2017-04-24T14:32:00Z" level=info msg="healthCheck -- reloading haproxy config with the new config changes\n[WARNING] 113/143200 (209) : config : 'option forwardfor' ignored for proxy 'web' as it requires HTTP mode.\n[WARNING] 113/143200 (209) : config : 'option forwardfor' ignored for backend 'cattle-a2c7d960-d392-425f-8e05-c9bbcb098ade_7bc8f6eb-0cee-4adf-98a7-e06613bcf674_1' as it requires HTTP mode.\n"
24/04/2017 16:32:00time="2017-04-24T14:32:00Z" level=info msg="Scheduling apply config"
24/04/2017 16:32:00time="2017-04-24T14:32:00Z" level=info msg="healthCheck -- no changes in haproxy config\n"
24/04/2017 16:32:00time="2017-04-24T14:32:00Z" level=info msg="Scheduling apply config"
24/04/2017 16:32:00time="2017-04-24T14:32:00Z" level=info msg="healthCheck -- no changes in haproxy config\n"
24/04/2017 16:32:01time="2017-04-24T14:32:01Z" level=info msg="Scheduling apply config"
24/04/2017 16:32:01time="2017-04-24T14:32:01Z" level=info msg="Monitoring 1 backends"
24/04/2017 16:32:01time="2017-04-24T14:32:01Z" level=info msg="healthCheck -- reloading haproxy config with the new config changes\n[WARNING] 113/143201 (222) : config : 'option forwardfor' ignored for proxy 'web' as it requires HTTP mode.\n[WARNING] 113/143201 (222) : config : 'option forwardfor' ignored for backend 'cattle-a2c7d960-d392-425f-8e05-c9bbcb098ade_7bc8f6eb-0cee-4adf-98a7-e06613bcf674_1' as it requires HTTP mode.\n"
24/04/2017 16:32:02time="2017-04-24T14:32:02Z" level=info msg="Scheduling apply config"
24/04/2017 16:32:02time="2017-04-24T14:32:02Z" level=info msg="healthCheck -- reloading haproxy config with the new config changes\n[WARNING] 113/143202 (229) : config : 'option forwardfor' ignored for proxy 'web' as it requires HTTP mode.\n[WARNING] 113/143202 (229) : config : 'option forwardfor' ignored for backend 'cattle-a2c7d960-d392-425f-8e05-c9bbcb098ade_7bc8f6eb-0cee-4adf-98a7-e06613bcf674_1' as it requires HTTP mode.\n"
24/04/2017 16:32:02time="2017-04-24T14:32:02Z" level=info msg="Scheduling apply config"
24/04/2017 16:32:02time="2017-04-24T14:32:02Z" level=info msg="healthCheck -- no changes in haproxy config\n"
24/04/2017 16:32:02time="2017-04-24T14:32:02Z" level=info msg="Scheduling apply config"
24/04/2017 16:32:02time="2017-04-24T14:32:02Z" level=info msg="healthCheck -- no changes in haproxy config\n"
24/04/2017 16:32:03time="2017-04-24T14:32:03Z" level=info msg="Monitoring 2 backends"
24/04/2017 16:32:05time="2017-04-24T14:32:05Z" level=info msg="a2c7d960-d392-425f-8e05-c9bbcb098ade_f831d50b-3279-4246-b905-f7dca6e2a5ca_11=DOWN"
24/04/2017 16:32:14time="2017-04-24T14:32:14Z" level=info msg="Scheduling apply config"
24/04/2017 16:32:14time="2017-04-24T14:32:14Z" level=info msg="healthCheck -- no changes in haproxy config\n"

**Comment by emcniece** [comment]
Possibly related: https://github.com/rancher/rancher/issues/8383

**Comment by aequasi** [comment]
able to figure anything out @pdefert ? This issue is definitely still seen @sangeethah. Can you please re-open.

**Comment by Meowbeast** [comment]
I'm having the same problem here.  Health check on my second host never initializes.

**Comment by ReidWeb** [comment]
I'm also having this issue, a documented fix would be much appreciated

**Comment by zhangalex** [comment]
Same issue.

**Comment by wmbutler** [comment]
What's really funny in true Rancher style is that this bug has been closed... without fixing it.

**Comment by vincent99** [comment]
@wmbutler Your snark is not productive or welcome here.

The health check containers check each other.  When there is exactly one host it can only check itself, which doesn't require networking, so it works no matter how networking is setup.  Once there is a 2nd host, they check each other and cross-host networking has to actually work.  This means each host has a unique, mutually-reachable IP and 500/udp and 4500/udp are open between them.  Less-commonly if you're doing restrictive firewalling on the host (e.g. setting the default output chain to drop), containers need to be able to talk to each other within the host, including on the link-local subnet for metadata.

This issue was created, by us, for a specific problem with a configuration where everything was setup right.  It was fixed and closed 10 months ago.  It is not a magical solution to every possible problem where healthchecks won't initialize, because there are infinite ways you can create a situation that doesn't work.

Virtually every time it's not meeting one of the things I said above, and people check and swear up and down that everything's fine, then discover it's not and quietly disappear, usually without saying "oh right it was actually my bad".

IF you believe you have a problem
  - AND you are running the current stable release
  - AND each host has a unique IP
  - AND they are all in the same subnet or you are positive every one of those IPs can reach every other
  - AND you have checked and double checked that ports are open
  - AND preferably you have tried disabling firewalls/security groups entirely (or allowing "all on all" or similar)

Then create a new issue with as much detail as possible.  Digging up this old issue and saying "me too" because you see the same result is not helpful to anybody.
