### ISSUE TITLE
Kubernetes environment is degraded after upgrading rancher server from 1.1.4 to 1.2.0-pre4-rc8

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#6667]
**Rancher Version:**1.1.4 to 1.2.0-pre4-rc8

**Docker Version:**1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):**Ubuntu, cloud

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**Kuberenetes

**Steps to Reproduce:**
1. Create a kubernetes env in 1.1.4 with pod/ingress
2. Upgrade rancher to 1.2.0-pre4-rc8. Do not do a "project.upgrade" through API

**Results:** 
The rancher ingress controller and kubernetes agent do not start successfully. They are stuck in intializing state. Kubernetes env is degraded

**Comment by alena1108** [comment]
@deniseschannon we should document the fact that any containers that get recreated after the 1.1 to 1.2 upgrade (due to failed health check), are not gonna be programmed to dns/healthcheck/lb config. The workaround - upgrade the environment.

**Comment by deniseschannon** [comment]
Added to RN for 1.2
