### ISSUE TITLE
Upgrading environments in v1.2.0-pre4-rc8 using project.upgrade through API denies access to the environments

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#6669]
**Rancher Version:**1.2.0-pre4-rc8

**Docker Version:**1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):**Ubuntu, Cloud

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**: Cattle and Kubernetes

**Steps to Reproduce:**
1. Create Cattle and Kubernetes environments in rancher v1.1.4 with auth enabled
2. Upgrade to rancher v1.2.0-pre4-rc8
3. Do a project.upgrade through API for both the environments to launch the micro-services
4. Disabled the auth

**Results:** 
There is no access to both Cattle and Kubernetes environments. 
<img width="1280" alt="screen shot 2016-11-18 at 11 20 54 am" src="https://cloud.githubusercontent.com/assets/18536626/20443548/22662dfa-ad82-11e6-8bf7-59d6ec5663d5.png">

Clicking on the environments from the "Manage Environments" page results in Auth error(503)

<img width="771" alt="screen shot 2016-11-18 at 11 36 57 am" src="https://cloud.githubusercontent.com/assets/18536626/20443789/3414a76a-ad83-11e6-9f2b-43b895772f09.png">

**Comment by vincent99** [comment]
Upgrade support is in `latest` now (not in RC8).

The 2nd picture is an unrelated issue with the auth service.

**Comment by soumyalj** [comment]
Tested with upgrading from 1.1.4 to 1.2.0-pre4-rc10. Upgrade proceeded without doing project.upgrade. Access to different environments was successful.
