### ISSUE TITLE
cant create an unnamed volume in conjunction with volume-driver

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#6672]
doing the equivalent of
```
docker run --volume-driver rancher-nfs -v /tmp ...
```
in cattle will not create a /tmp as a rancher-nfs volume

**Comment by sangeethah** [comment]
Tested with v1.2.0-pre4-rc10 and  rancher/storage-nfs:v0.4.0

Able to create a service when volume provide as "/<dir name>" or "/<dir name>:<mode>" using rancher-nfs volume driver .
volumes gets created with a self generated name like ```8d901dc6-9332-43d1-832d-4867c292aa75``` .
