### ISSUE TITLE
Not able to use rancher-nfs with out having "insecure" option in nfs mounts.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6673]
Server version - Build from master
rancher/storage-nfs:v0.2.0

Steps to reproduce the problem:
When I did not have "insecure" option for my mount point in nfs server , containers having volume drivers set to rancher-nfs failed to start with error message -

Error (Error response from daemon: VolumeDriver.Mount: Failed mount 104.131.67.71:/var/nfs/test11_foo1_1f77e /var/lib/rancher/volumes/rancher-nfs/test11_foo1_1f77e: Running in chroot, ignoring request. mount.nfs: rpc.statd is not running but is required for remote locking. mount.nfs: Either use '-o nolock' to keep locks local, or start statd. mount.nfs: mounting 104.131.67.71:/var/nfs/test11_foo1_1f77e failed, reason given by server: No such file or directory)
When i added "insecure" option for my mount point in nfs server , I was able to start couple of instances successfully.

Expected Behavior:
We should be able to work with out having to add "insecure" option.

**Comment by cjellick** [comment]
Image used should be rancher/storage-nfs:v0.4.0

**Comment by sangeethah** [comment]
Tested with rancher/storage-nfs:v0.4.0. Able to use rancher-nfs with out having "insecure" option in nfs mounts.
