### ISSUE TITLE
Rancher catalog does not allow for more than 10 versions

### ISSUE THREAD

**Issue by truongdo** [rancher/rancher#6679]
When I use more than 10 versions in Cattle catalog, the upgrade button next to the stack is not displayed anymore.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.1.0` Cattle: `v0.165.4` UI: `v1.1.12` |
|Access|`github` `admin`|
|Orchestration|`Cattle`|
|Route|`hosts.index`|

**Comment by tfiduccia** [comment]
@truongdo This was fixed in version 1.0.1 and tested in both 1.1.0 and our current version.  I am unable to replicate your problem.  Please check to ensure that your version shows up in the catalog at all and that there is nothing wrong with your template.
