### ISSUE TITLE
[cli] rancher wait or rancher events throw FATA[0000] websocket: bad handshake

### ISSUE THREAD

**Issue by darrenscerri** [rancher/rancher#6680]
**Rancher Version:**
rancher/v1.2.0-pre3 - rancher/v1.2.0-pre4-rc8

**Docker Version:**
1.12.2

**OS and where are the hosts located? (cloud, bare metal, etc):**
Centos 7.2 Hyper-V

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher, internal DB
rancher agent on port 8080, SSL terminated using nginx

```
upstream rancher {
  server 127.0.0.1:8080; # rancher
}

server {
    listen 443 ssl;
    server_name <name>;
    ssl_certificate <pem>;
    ssl_certificate_key <key>;

    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://rancher;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        # This allows the ability for the execute shell window to remain open for up to 15 minutes. Without this parameter, the default is 1 minute and will automatically close.
        proxy_read_timeout 900s;
    }
}

server {
    listen 80;
    server_name <name>;
    return 301 https://$server_name$request_uri;
}
```

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
rancher wait <id>
rancher events

**Results:** 
rancher CLI returns: FATA[0000] websocket: bad handshake
rancher agent logs: http: proxy error: net/http: request canceled

**Expected:**
These commands should work

**Comment by darrenscerri** [comment]
I have spun up a separate Rancher instance using v1.2.0-pre3 without using nginx and the mentioned commands seem to be working. So it must be a problem with the reverse proxy. Is there something I'm missing in the nginx config?

**Comment by darrenscerri** [comment]
I realised that even if I switch off reverse proxying and connecting directly using port 8080, I still get the bad handshake. After a lot of troubleshooting I realised that I can get the commands working if I disable Access Control in Rancher (using LDAP currently). Re-enabling Access Control would break the commands again.

**Comment by vincent99** [comment]
I believe this was fixed in later RCs, please reopen if you're still having a problem in 1.3+.
