### ISSUE TITLE
source ports are defaulting to tcp instead of http

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#6681]
**Rancher Version:**
v1.2.0-prer-rc9

**Docker Version:**
1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
ubuntu 16.04, GCE

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
 10 acre setup

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
cattle

**Steps to Reproduce:**

1. Add a load balancer with http protocol

**Results:** 

In the UI/API, the load balancer comes up with ports using tcp. The source ports wouldn't show tcp so it'd be http.

```
"ports": [ 2 items
"90:90/tcp",
"91:91/tcp"
],
```

**Expected:**

```
"ports": [ 2 items
"90:90",
"91:91"
],
```

**Comment by alena1108** [comment]
@deniseschannon there is no "http" proto on "ports" field, only tcp/udp (it is L3). Only in "portRules" we support L7 protocols
