### ISSUE TITLE
Github users added as members of envs do not have access to the envs after upgrade

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#6683]
**Rancher Version:**1.1.4 to 1.2.0-pre4-rc9

**Docker Version:**1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):**Ubuntu, Cloud

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**Cattle/Kubernetes

**Steps to Reproduce:**
1.Create an env in rancher v1.1.4 and enable github authorization. Add another user1 to the access control list
2. Add the user1 to the environment as member
3. Upgrade from rancher1.1.4 to rancher v1.2.0-pre4-rc9
4. Upgrade the environment

**Results:** 
The user1 is not listed in the access control page after upgrade and cannot access the environment.

**Expected:**
The user1 should be able to access the environment after upgrade.

**Comment by deniseschannon** [comment]
There might be too things going on here
1. There is an issue where authorized users are not being saved if they had not logged in: https://github.com/rancher/rancher/issues/6686
2. There was issues with auth access due to the `upgrading` state of environments.

**Comment by prachidamle** [comment]
@soumyalj as mentioned by @deniseschannon above this seems related to two issues.
Both of which are now resolved/closed. Can you retest this case?

Also just to confirm: I hope in both these steps:
1.Create an env in rancher v1.1.4 and enable github authorization. Add another user1 to the access control list
2. Add the user1 to the environment as member

You explicitly hit the "Save" button after adding the user to the list/environment.

**Comment by soumyalj** [comment]
Tested with upgrade from 1.1.4 to 1.2.0-pre4-rc10. The member added to the env is able to access the env after upgrade.
