### ISSUE TITLE
A member (non-admin) of an environment can upgrade the environment

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#6684]
**Rancher Version:**
v1.2.0-pre4-rc9

**Docker Version:**
docker 1.12

**OS and where are the hosts located? (cloud, bare metal, etc):**
ubuntu 16.04

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node 

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
cattle

**Steps to Reproduce:**
1. 1.1.4 setup with someone added to the environment as a member
2. Upgrade to v1.2.0-pre4-rc9

**Results:** 
The member of the environment iss able to upgrade the environment.

**Expected:**

The member of the environment is not able to upgrade the environment.

**Comment by alena1108** [comment]
the API call is account.upgrade

**Comment by prachidamle** [comment]
Shouldn't the action to upgrade the env not even be available to a member, in the UI? @vincent99 @alena1108

**Comment by prachidamle** [comment]
After talking to @vincent99 server needs to present the "upgrade" action in the response of the list project API, only for project owners.

Changed the project.json to allow upgrade for owners(and admins) only.

**Comment by prachidamle** [comment]
Assigning to @vincent99 to change UI to not let project members do "upgrade" action.

**Comment by deniseschannon** [comment]
Fix for API has been merged. @soumyalj @sangeethah can you verify? i've left it assigned to @vincent99 for UI updates

**Comment by vincent99** [comment]
(after rc10)

**Comment by tfiduccia** [comment]
Version - master 11/22
Now says to contact admin to upgrade.  Can't access until that happens
Verified fixed
