### ISSUE TITLE
ipsec containers stuck in "starting" state for a long time (about 15 mts) when host is rebooted.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6685]
Rancher Version: v1.2.0-pre4-rc9

Steps to reproduce the problem:
Deploy a global health check enabled servic e.
reboot one of the hosts.

ipsec containers stuck in "starting" state for a very long time.
Container keeps getting restarted  and finally after about 15 mts , it starts successfully

Log from ipsec container when it kept restarting:
```
00[KNL] querying policy failed: No such file or directory (2)
00[KNL] unable to query policy 0.0.0.0/0 === 0.0.0.0/0 in
00[KNL] querying policy 0.0.0.0/0 === 0.0.0.0/0 fwd
00[KNL] sending XFRM_MSG_GETPOLICY 4990: => 80 bytes @ 0x7fff112432f0
00[KNL]    0: 50 00 00 00 15 00 01 00 7E 13 00 00 18 00 00 00  P.......~.......
00[KNL]   16: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
00[KNL]   32: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
00[KNL]   48: 00 00 00 00 00 00 00 00 02 00 00 00 00 00 00 00  ................
00[KNL]   64: 00 00 00 00 00 00 00 00 00 00 00 00 02 00 00 00  ................
00[KNL] received (2) 4990: => 100 bytes @ 0x8c25f0
00[KNL]    0: 64 00 00 00 02 00 00 00 7E 13 00 00 18 00 00 00  d.......~.......
00[KNL]   16: FE FF FF FF 50 00 00 00 15 00 01 00 7E 13 00 00  ....P.......~...
00[KNL]   32: 18 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
00[KNL]   48: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
00[KNL]   64: 00 00 00 00 00 00 00 00 00 00 00 00 02 00 00 00  ................
00[KNL]   80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
00[KNL]   96: 02 00 00 00                                      ....
00[KNL] querying policy failed: No such file or directory (2)
00[KNL] unable to query policy 0.0.0.0/0 === 0.0.0.0/0 fwd
00[KNL] querying SAD entry with SPI c26cf6e2
00[KNL] sending XFRM_MSG_GETSA 4991: => 40 bytes @ 0x7fff11243290
00[KNL]    0: 28 00 00 00 12 00 01 00 7F 13 00 00 18 00 00 00  (...............
00[KNL]   16: 8A C5 02 87 00 00 00 00 00 00 00 00 00 00 00 00  ................
00[KNL]   32: C2 6C F6 E2 02 00 32 00                          .l....2.
00[KNL] received XFRM_MSG_NEWSA 4991: => 380 bytes @ 0x8c25f0
00[KNL]    0: 7C 01 00 00 10 00 00 00 7F 13 00 00 18 00 00 00  |...............
00[KNL]   16: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
00[KNL]   32: 00 00 00 00 00 00 00 00 00 00 
```

**Comment by tfiduccia** [comment]
For me it's saying that "Expected state running but got stopped: Timeout getting IP address"

**Comment by sangeethah** [comment]
Rancher Version: v1.2.0-pre4-rc15

I am still able to see this issue where ipsec containers keeps restarting for a very long time ( ```"startCount": 75```) . This time it happened in the scenario where host was powered down , waited for the state of host to go from "Active"-> "Reconnecting"->"Disconnected" . After that powered on host.

 ipsec containers keeps restarting for a very long time (~15 mts) after which it is able to start successfully.

**Comment by leodotcloud** [comment]
These two fixes together should fix the problem:
- https://github.com/rancher/rancher-net/pull/27
- https://github.com/rancher/cattle/pull/2253/commits/abb04b719a58e5a49bc4847745cb7c25f1b87a49

**Comment by deniseschannon** [comment]
Please test with rancher-net v0.7.4

**Comment by sangeethah** [comment]
Tested with v1.2.0-rc1 and rancher/net:v0.7.4

This issue is not seen any more.

After host reboot , ipsec containers get to starting state once the host connectivity is restored.
I see the ipsec containers go to "stopped" state and then when it starts it is able to start successfully.
