### ISSUE TITLE
github auth: authorized user disappears after upgrade (if user has never logged in)

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#6686]
**Rancher Version:**
v1.1.4 - v1.2.0-pre4-rc9

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
cattle - 10acre setup

**Steps to Reproduce:**
1. start v1.1.4
2. add authorized user
3. upgrade to v1.2.0-pre4-rc9

**Results:** 
Authorized user is no longer on list.

Note: If the user had previously logged in, they would stay on the list. 

**Expected:**
Authorized user to stay on list

**Comment by prachidamle** [comment]
In a new test with @deniseschannon we could not reproduce the issue. @deniseschannon is going to test this further.

**Comment by deniseschannon** [comment]
This is working as expected. In previous test case, I must not have hit "save"
