### ISSUE TITLE
"Route 53" from rancher server 1.1.4 is not upgradable after upgrading rancher-server to 1.2

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6688]
Fresh install of  rancher server - 1.1.4 

Deploy "v0.4.1-rancher1" of "Route53 DNS". 
"Upgrade Available" option is presented to user. Do not upgrade.

Upgrade rancher-server to v1.2.0-pre4-rc9.
Upgrade "Default" environment.

After upgrade is completed, "Route53 DNS" entry does not show "Upgrade Available" option anymore.
It shows "current:undefined" where catalog version needs to be presented.

**Comment by vincent99** [comment]
https://github.com/rancher/rancher/issues/6157 and
https://github.com/rancher/rancher/issues/6653
