### ISSUE TITLE
[Bug] Expected state running but got error: Timeout getting IP address

### ISSUE THREAD

**Issue by andreimc** [rancher/rancher#6689]
**Rancher Version:**

v1.2.0-pre4-rc9

**Docker Version:**
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:
 OS/Arch:      linux/amd64

**OS and where are the hosts located? (cloud, bare metal, etc):**

Scaleway - CentOS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

Single node external db

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

k8s

**Steps to Reproduce:**

Create an environment with single node, set up k8s as a stack and add 3 agents

**Results:** 

<img width="1902" alt="screen shot 2016-11-20 at 5 23 13 pm" src="https://cloud.githubusercontent.com/assets/1446134/20460945/a1f5982e-af46-11e6-815a-9fe4cd60c5fb.png">

**Expected:**

No errors

**Comment by deniseschannon** [comment]
@andreimc Thanks for always willing to test bleeding edge RCs. :)

1. CentOS/RHEL OSes have issues: https://github.com/rancher/rancher/issues/6658

I'm going to close this in favor of the other one.

**Comment by jeanlouisboudart** [comment]
Same here with with Ubuntu 16.04, v1.2.0-pre4-rc10, Cattle.

**Comment by grayprince** [comment]
Same issue with Ubuntu 14.04,v1.2.0-pre4-rc15, K8s Env.

**Comment by omegarus** [comment]
Same issue with Ubuntu 14.04 v1.2.0-pre4-rc15, 2 hosts K8s env. With single host everything works as expected.
