### ISSUE TITLE
Update sidekick by API

### ISSUE THREAD

**Issue by psyhonut** [rancher/rancher#6692]
**Rancher Version:** 1.1.4

**Docker Version:** 1.12

**OS and where are the hosts located? (cloud, bare metal, etc):** CentOS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single node rancher, internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

I don't know how to upgrade sidekick by API. I can only upgrade main service, but when I try to upgrade it's sidekick, Rancher answered there is no service by this name (name of sidekick service).

**Comment by vincent99** [comment]
Sidekicks are upgraded with the main service by updating `secondaryLaunchConfigs`.

**Comment by anlek** [comment]
Interested in this as well, but I am not at all aware what `secondaryLaunchConfigs`. I'm trying to upgrade a sidekick via `rancher-compose`.

**Comment by psyhonut** [comment]
@anlek this is my first-step realization https://github.com/psyhonut/rancher-gitlab-deploy/commit/44958373a5fa98d6239134025f261d7a9cfe957b
