### ISSUE TITLE
Failure to access container.mounts()

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6695]
Rancher server version - v1.2.0-pre4-rc9

Steps to reproduce the problem in automation run:
From host , create a container with volumes.
wait for container to sync to rancher-server.
Trying to access container.mounts() gives the following error:
```
Error Message

TypeError: 'list' object is not callable
```

When I try to manually , follow the mounts link for the container , i see information about all the volumes.

Putting sleep of 5 secs and reloading the container , before trying to access the mounts() link is also not helping. 

```
Stacktrace

socat_containers = None, client = <cattle.Client object at 0x7effdd9d6710>
native_name = 'native-test-429534', pull_images = None

    def test_native_volumes(socat_containers, client, native_name, pull_images):
        docker_client = get_docker_client(host(client))
        docker_container = docker_client. \
            create_container(NATIVE_TEST_IMAGE,
                             name=native_name,
                             volumes=['/foo',
                                      '/host/var',
                                      '/host/tmpreadonly'])
        docker_client.start(docker_container,
                            binds={'/var': {'bind': '/host/var'},
                                   '/tmp1': {'bind': '/host/tmpreadonly',
                                             'ro': True}})
    
        rancher_container = wait_on_rancher_container(client, native_name)
    
        assert rancher_container.externalId == docker_container['Id']
        assert rancher_container.state == 'running'
>       mounts = rancher_container.mounts()
E       TypeError: 'list' object is not callable

```

**Comment by cjellick** [comment]
@ibuildthecloud refactored mounts so that they are embedded in the instance. So, mounts is a property, not a method now and you need to access it like: `container.mounts` instead of `container.mounts()`. The method version is now renamed as `container.mounts_link()`. You can use either `.mounts` or `.mounts_link()` but using `.mounts` will be more efficient since it does not require another http request.

**Comment by deniseschannon** [comment]
@cjellick From what I read, the automation tests just need to be updated with the new method?

**Comment by sangeethah** [comment]
Fixed automation to access volume mount details using .mounts.
test_native_volumes tests now report success.
