### ISSUE TITLE
"Edit Environment" option should not be shown for member of an environment.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6698]
Rancher Version: v1.2.0-pre4-rc9

In a github enabled setup, switch to environment where the current user is a member (not owner).
Notice that "Edit <Env>" option is provided to the user.
When he tries to edit environment  , edit is not allowed as expected.

"Edit <Env>" option should not be provided to the user when he is a member of an environment.

**Comment by tfiduccia** [comment]
Version - v1.2.0-pre4-rc14
Verified fixed
