### ISSUE TITLE
cpuSetMems, KernelMemory, sysctl are missing in generated config and lack rancher-compose support

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6700]
Rancher Version: v1.2.0-pre4-rc10

Steps to reproduce the problem:
Create a service with cpuSetMems and KernelMemory set in launch_config.
In the "View Config" option for stack , the generated config is missing cpuSetMems and KernelMemory parameter.

**Comment by StrongMonkey** [comment]
https://github.com/rancher/rancher/issues/6280 According to what @joshwget addressed in this issue `cpusetmems`, `kernelMems` and `sysctl` are dropped from `launch_config`.

**Comment by deniseschannon** [comment]
@sangeethah These fields have not been defined in Docker Compose, which is why they are not being generated in the export yaml and rancher-compose doesn't have support to read them. 

I'm updating this issue for adding in rancher compose support for these keys whenever it's added in Docker Compose.

**Comment by deniseschannon** [comment]
@sangeethah You will need to update your automation tests until these fields are officially supported.

**Comment by sangeethah** [comment]
@josh, I have assigned this issue to you for extending support for these fields in rancher-compose.

**Comment by joshwget** [comment]
Moving to unscheduled until we have an idea of what these keys will be in Docker Compose.

**Comment by eesprit** [comment]
Shouldn't it be rescheduled now that this is known ?
https://docs.docker.com/compose/compose-file/#resources (for all memory/kernel/cpu params)
https://docs.docker.com/compose/compose-file/#sysctls

**Comment by sangeethah** [comment]
"--pid-limits" is another parameter we now support from ```rancher run``` command . But exported config for this service that was created by setting "--pid-limits"using ```rancher run``` command does not have this config parameter set in rancher-compose yml.
