### ISSUE TITLE
Kubernetes not showing up in "library" catalog.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6701]
Rancher Version: v1.2.0-pre4-rc10

On fresh install of rancher-server , Kubernetes is not showing up in "library" catalog.

On an upgraded setup( from v1.1.4 ->  v1.2.0-pre4-rc10)  , existing K8s stack is showing as "upto date" and when hovered on shows "current:undefined" . Expect to be presented with option to upgrade to k8s 1.4.x.

**Comment by sangeethah** [comment]
@deniseschannon , in fresh install we see k8s now.

But upgraded setup, still has the same issue.

On an upgraded setup( from v1.1.4 -> v1.2.0-pre4-rc10) , existing K8s stack is showing as "upto date" and when hovered on shows "current:undefined" . Expect to be presented with option to upgrade to k8s 1.4.x.

**Comment by rancherdev** [comment]
closing this issue .

Tracking in https://github.com/rancher/rancher/issues/6157
