### ISSUE TITLE
SSL Load balancer not working

### ISSUE THREAD

**Issue by sankaet** [rancher/rancher#6703]
Seems like when I am trying to run an SSL Load Balancer, its not running.

I tried to manually run HAproxy `haproxy -f /etc/haproxy/haproxy.cfg` and I am getting the following error:

```
[ALERT] 325/042428 (549) : parsing [/etc/haproxy/haproxy.cfg:36] : 'bind *:443'
:
  unable to load SSL private key from PEM file '/etc/haproxy/certs/default.pem'.
  unable to load SSL private key from PEM file '/etc/haproxy/certs/server.pem'.
[ALERT] 325/042428 (549) : Error(s) found in configuration file : /etc/haproxy/h
aproxy.cfg
[WARNING] 325/042428 (549) : config : 'option forwardfor' ignored for proxy 'def
ault' as it requires HTTP mode.
[ALERT] 325/042428 (549) : Proxy 'ce09599b-5bd0-427d-82b8-4cc7227fcca2_443_front
end': no SSL certificate specified for bind '*:443' at [/etc/haproxy/haproxy.cfg
:36] (use 'crt').
[ALERT] 325/042428 (549) : Fatal errors found in configuration.
```

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.1.4` Cattle: `v0.165.8.4` UI: `v1.1.14` |
|Access|`github` `admin`|
|Orchestration|`Cattle`|
|Route|`container.labels`|

**Comment by sankaet** [comment]
Hi, any feedback on this?

**Comment by sankaet** [comment]
Nevermind I figured it out

**Comment by ArgonQQ** [comment]
How did you resolve this issue? Struggling with the error message 

`unable to load SSL certificate from PEM file`
