### ISSUE TITLE
Network communication between container is blocked

### ISSUE THREAD

**Issue by chrisdupuy** [rancher/rancher#6705]
**Rancher Version:**
1.1.4
**Docker Version:**
1.11.2
**OS and where are the hosts located? (cloud, bare metal, etc):**
CoreOS stable (1185.3.0) installed on cloud (OVH)
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA-Rancher, external Galera Cluster.
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
Create one stack with two containers A and B. A is linked to B. B accept connection from anyone.
**Results:** 
Sometime immediately, sometime only on upgrade or restart container, A cannot ping B. 
Inside A, making a dsn lookup or dig B gives the correct ID of the container B. But ping or trace ends in timeout. The only solution is to reboot the hosts and all goes OK.
**Expected:**
A can ping B.

**Comment by janeczku** [comment]
Hi @chrisdupuy in order to troubleshoot this could you provide the docker-compose.yml for the stack (stack > context menu > show config).
Also, are container A and container B running on the same host or different host?

**Comment by chrisdupuy** [comment]
@janeczku here is the simple docker-compose.yml 
`front:
  image: nginx:alpine
  links:
  - 'postgre:'
postgre:
  environment:
    POSTGRES_DB: test
    POSTGRES_PASSWORD: test
    POSTGRES_USER: test
  image: mdillon/postgis`

I've seen the issue when Container A and Container B are running on the same host, and separate host too.
Kindly,

**Comment by mccricardo** [comment]
We've seen this happening several times. It has been more prevalent in containers running in a cron like setup, where containers are restarted periodically.

**Comment by janeczku** [comment]
@mccricardo Are these Alpine Linux based containers?

**Comment by mccricardo** [comment]
@janeczku Yes.

**Comment by janeczku** [comment]
@mccricardo If `ping service-name` fails with "bad address" but `ping service-name.stack-name.rancher.internal` works, then it's a known issue with Alpine Linux.

**Comment by mccricardo** [comment]
Not the case. We have instances where the **ip** is correctly resolved but there's no connection. 

For example, a service that runs every minute, performs some arbitrary task and then connects to a database to save some information. The **ip** of the database is correctly resolved using **service-name** but the connection fails. Next time it runs there's no issue.

**Comment by janeczku** [comment]
@mccricardo 
> Next time it runs there's no issue.

Does this occur only on the first connection right after container start or does this happen later on during container lifetime as well?

**Comment by mccricardo** [comment]
It's each time the container is started. The use case I'm describing starts the container on a cron fashion, for example every minute, to perform some arbitrary task. Every once in a while those task fail because of this issue.

**Comment by janeczku** [comment]
@mccricardo Thanks for the detailed info. Last question: Which version of Rancher are you on?

**Comment by mccricardo** [comment]
Thank you @janeczku. I'm using Rancher 1.1.4

**Comment by janeczku** [comment]
@mccricardo These issues with overlay networking should be solved by upgrading to Rancher v1.3.3 (current stable).

**Comment by janeczku** [comment]
We have switched to use CNI for container networking in v1.2. Please upgrade to the latest stable release of Rancher and reopen the ticket if you are still having issues.

**Comment by mccricardo** [comment]
Thank you @janeczku.
