### ISSUE TITLE
Error while pulling image: Get [...] authenticationrequired

### ISSUE THREAD

**Issue by ununseptium** [rancher/rancher#6706]
**Rancher Version:**
?

**Docker Version:**
1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
RHEL7 as underlying system (for now)

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
 - Hosts
 - Add Hosts
 - vSphere
    - OS ISO URL: Internal Link to boot2docker iso
    - Network: Custom Network
    - Data Store: Custom Data Store
    - Also Added Environment Variables (HTTP_PROXY & HTTPS_PROXY)

**Results:** 
`Error while pulling image: Get https://index.docker.io/v1/repositories/rancher/agent/images: authenticationrequired`

**Expected:**
I expected the hosts to come up alive.

**Comment by aemneina** [comment]
can your hosts do a `docker pull` without authenticating? You might have a proxy in your environment preventing connecting directly to dockerhub?

**Comment by ununseptium** [comment]
Docker pull works fine but we upgraded to the new ESXi, creating everything again and facing new issues now. I'm not able to reproduce the issue myself for now, so i guess this can be closed.
