### ISSUE TITLE
Cannot configure HA using Ha-script from rancher

### ISSUE THREAD

**Issue by siawai** [rancher/rancher#6708]
**Rancher Version:**  
-V1.1.4 

**Docker Version:**   
-  1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):** 
- ubuntu, Openstack vm

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** -
 multi node and external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
-cattle

**Steps to Reproduce:**
-Trying to create HA  and cattle is not taking proper IP address 

**Results:** 

time="2016-11-21T13:39:33Z" level=info msg="Deleting container aa2a6997561fef643ae194687397f9099c911f1ee27b8e0183a057c768b61166" component=docker
time="2016-11-21T13:39:33Z" level=info msg="Creating container rancher-ha-agent" component=docker
time="2016-11-21T13:39:42Z" level=info msg="Waiting for 3 host(s) to be active" component=cert
time="2016-11-21T13:39:44Z" level=info msg="Waiting for 3 host(s) to be active" component=cert
time="2016-11-21T13:39:46Z" level=info msg="Waiting for 3 host(s) to be active" component=cert
time="2016-11-21T13:39:49Z" level=info msg="Waiting for 3 host(s) to be active" component=cert
time="2016-11-21T13:39:51Z" level=info msg="Waiting for 3 host(s) to be active" component=cert
time="2016-11-21T13:39:53Z" level=info msg="Waiting for 3 host(s) to be active" component=cert
time="2016-11-21T13:39:55Z" level=info msg="Waiting for 3 host(s) to be active" component=cert
time="2016-11-21T13:39:57Z" level=info msg="Waiting for 3 host(s) to be active" component=cert
time="2016-11-21T13:39:59Z" level=info msg="Waiting for 3 host(s) to be active" component=cert
time="2016-11-21T13:40:01Z" level=info msg="Waiting for 3 host(s) to be active" component=cert
time="2016-11-21T13:40:03Z" level=info msg="Waiting for 3 host(s) to be active" component=cert
time="2016-11-21T13:40:03Z" level=info msg="Waiting for 3 host(s) to be active" component=cert
time="2016-11-21T13:40:05Z" level=fatal msg="Failed while waiting for 3 host(s) to be active: Get http://172.17.0.1:18080/v1/projects/1a19/hosts?state=active: dial tcp 172.17.0.1:18080: getsockopt: connection refused" component=service

**Expected:**
HA on all three nodes

**Comment by ramramu3433** [comment]
even i had the same exact issue

**Comment by bobashley** [comment]
Hello
Even i am facing the same issue. Why does rancher take a private IP Address (172.17.x.x)?
Can somebody help me on this ?

**Comment by vincent99** [comment]
Is the registration URL set to something that resolves to a public IP?

The HA system is completely revamped and significantly simpler in 1.2.0, so at this point anyone having problems with it in 1.1.x should probably just wait a couple days for 1.2.

**Comment by siawai** [comment]
Hey Vincent, 

Yes, I am using a public IP address. But still it takes local IP address.
