### ISSUE TITLE
[rancher-dns] DNS records added for purged hosts

### ISSUE THREAD

**Issue by jensendw** [rancher/rancher#6711]
**Rancher Version:**
v1.1.4

**Docker Version:**

1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 14.04 AWS
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher w/External DB 
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
We have been running rancher with around 80 separate services for about 6 months and things were working perfectly until about a week ago when we started seeing inconsistencies from the external-dns service.  As far as I can tell the external-dns service pulls its data from http://rancher-metadata/2015-12-19, I have verified that the metadata returned from this endpoint is correct.  However, we keep seeing purged hosts being added as DNS records for various services.  We are using route53 with external DNS from the catalog v.0.5.1.  

**Results:** 
We are seeing IP addresses of purged hosts being added to DNS records for services, they then get removed again, and so we have flapping going on in regards to our DNS records. 

If we look at the route53 external-dns service running it is constantly updating records, it seems that with one run its getting the erroneous data (stale hosts) and the next run its getting correct data.  

We are also seeing that for services that have been scaled, say from 2 to 3 instances, we are seeing the same flapping behavior.  For example, querying the DNS record for a service that was scaled from 2 to 3 shows 2 records sometimes, and then 3 records other times.

**Expected:**

Consistent DNS results.

**Comment by vincent99** [comment]
I believe this was fixed in later releases of external-dns.
