### ISSUE TITLE
Cannot swith to the Mesos Environment

### ISSUE THREAD

**Issue by funkydorian** [rancher/rancher#6712]
**Rancher Version: v1.2.0-pre4-rc11**

**Docker Version:  1.12.3 **

**OS and where are the hosts located? (cloud, bare metal, etc):**
GCP

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Rancher with 3 nodes

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Mesos

**Steps to Reproduce:**
Create a new environment
Choose mesos
Select Mesos

**Results:** 
Error
Reload to try again or log out

**Expected:**
Switch to Mesos

**Comment by funkydorian** [comment]
<img width="1181" alt="screen shot 2016-11-22 at 01 29 10" src="https://cloud.githubusercontent.com/assets/8745804/20503378/4c58d364-b053-11e6-8d1f-5515e6b9a945.png">

**Comment by vincent99** [comment]
https://github.com/rancher/ui/commit/167b33a2402e968c7192319becbaad3c6d4daa2b

**Comment by tfiduccia** [comment]
Version - master 11/22
@funkydorian Saw it yesterday and we fixed it.  Should be in the next build
Verified Fixed
