### ISSUE TITLE
Containers with service having volumes from rancher-efs error out multiple times before they come up successfully

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6713]
Rancher server version - v1.2.0-pre4-rc10

Steps to reproduce the problem:
Deploy rancher-efs.

Create a service with volume in volume driver "rancher-efs".

Containers start and then error out with the following message.
```
 Activating (Expected state running but got error: Error response from daemon: VolumeDriver.Mount: Failed to mount us-west-2a.***.us-west-2.amazonaws.com:/ at /var/lib/rancher/volumes/rancher-efs/sangeetest4. mount.nfs4: Failed to resolve server us-west-2a.f***.efs.us-west-2.amazonaws.com: Name or service not known)
```
This happens couple of times after which it is able to start successfully.

**Comment by deniseschannon** [comment]
updated in storage v0.5.0

**Comment by sangeethah** [comment]
Tested with v1.2.0-pre4-rc14 and  rancher/storage-efs:v0.6.0

Steps to reproduce the problem:
Deploy rancher-efs - rancher/storage-efs:v0.6.0

Create a service with volume in volume driver "rancher-efs" wiith scale 3.
2 of the containers started fine and the 3rd one errored out  with error message - ```Error (Error response from daemon: create sangeenewefs1: VolumeDriver.Create: Failed in create: An error occurred (FileSystemAlreadyExists) when calling the CreateFileSystem operation: None)```

After this all 3 hosts keep going to "reconnecting" state . 
Containers keep trying to restart and all host go to "reconnecting" state  and this happens in a loop.

**Comment by sangeethah** [comment]
The above issue was happening because  VPC that was used was   configured to enable mounting using DNS names. Once this was enabled , host reconnecting issue was not seen.

In general it takes ~4-5 minutes for the instance to start , if the volume has to get created as part of container creation.
In such cases , container get deleted and then recreated  multiple times.

I saw this error once:

```
   Activating (Expected state running but got error: Error response from daemon: create sangeenewefs3: VolumeDriver.Create: Failed in create: An error occurred (FileSystemAlreadyExists) when calling the CreateFileSystem operation: None)
```
The other time , it was some message thet stated "Expected running but got removed" .


``` 
mysql> select id,name,created, removed from instance where name like "%testefs2%";
+-----+------------------+---------------------+---------------------+
| id  | name             | created             | removed             |
+-----+------------------+---------------------+---------------------+
| 251 | test1-testefs2-1 | 2016-11-24 04:55:56 | 2016-11-24 04:59:40 |
| 252 | test1-testefs2-2 | 2016-11-24 04:55:56 | 2016-11-24 04:59:40 |
| 253 | test1-testefs2-3 | 2016-11-24 04:55:56 | 2016-11-24 04:59:40 |
| 254 | test1-testefs2-1 | 2016-11-24 05:00:09 | NULL                |
| 255 | test1-testefs2-2 | 2016-11-24 05:00:09 | NULL                |
| 256 | test1-testefs2-3 | 2016-11-24 05:00:09 | NULL                |
+-----+------------------+---------------------+---------------------+
6 rows in set (0.00 sec)
```

```
mysql> select id,name,created, removed from instance where name like "%testefs4%";
+-----+------------------+---------------------+---------------------+
| id  | name             | created             | removed             |
+-----+------------------+---------------------+---------------------+
| 261 | test1-testefs4-1 | 2016-11-24 05:14:00 | 2016-11-24 05:14:05 |
| 262 | test1-testefs4-2 | 2016-11-24 05:14:00 | 2016-11-24 05:17:55 |
| 263 | test1-testefs4-3 | 2016-11-24 05:14:00 | 2016-11-24 05:14:39 |
| 264 | test1-testefs4-1 | 2016-11-24 05:14:06 | 2016-11-24 05:14:39 |
| 265 | test1-testefs4-1 | 2016-11-24 05:14:40 | 2016-11-24 05:17:55 |
| 266 | test1-testefs4-3 | 2016-11-24 05:14:40 | 2016-11-24 05:15:54 |
| 267 | test1-testefs4-3 | 2016-11-24 05:15:55 | 2016-11-24 05:17:09 |
| 268 | test1-testefs4-3 | 2016-11-24 05:17:10 | NULL                |
| 269 | test1-testefs4-1 | 2016-11-24 05:18:24 | NULL                |
| 270 | test1-testefs4-2 | 2016-11-24 05:18:24 | NULL                |
+-----+------------------+---------------------+---------------------+
10 rows in set (0.00 sec)

mysql> 
```

**Comment by LLParse** [comment]
The long wait time that you experience is an unfortunate reality of AWS's EFS implementation, and something out of our control.

FileSystemAlreadyExists indicates we are receiving multiple Create requests for a volume with the same name (should be globally unique), @sangeethah can you please provide information on how to reproduce this?

**Comment by sangeethah** [comment]
@LLParse , Create a service with volume (new volume) in volume driver "rancher-efs" wiith scale 3 by doing the following steps in UI:
From UI - Create service by setting "volume driver" as "rancher-efs" and volume as "sangeenewefs1:/mydata in "Volume" tab with scale 3.

**Comment by gauravarora** [comment]
I was able to duplicate this problem also by launching a service and then just deleting the ec2 host the service was running on. It appears that the volume was already created but because the host was killed before the efs api could reply rancher's internal state was not updated. Perhaps if the volume already exists rancher should just use it?

**Comment by jclark360** [comment]
@sangeethah I have the same error, but mine never come up successfully.   

Failed in create: An error occurred (FileSystemAlreadyExists) when calling the CreateFileSystem operation: None)

Is this a the same issue?

**Comment by superseb** [comment]
rancher-efs is deprecated per v1.6.6 (https://github.com/rancher/rancher/releases/tag/v1.6.6), alternative is rancher-nfs (http://rancher.com/docs/rancher/v1.6/en/rancher-services/storage-service/rancher-nfs/#using-the-rancher-nfs-driver-on-amazon-efs)
