### ISSUE TITLE
LB with selector: target service with no port rules is not being registered

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#6717]
Steps to reproduce:
======================
1) Create lb service with port rules that have everything, but the serviceId defined:
```
"portRules": [
{
"type": "portRule",
"priority": 2,
"protocol": "http",
"selector": "foo=bar",
"sourcePort": 90,
"targetPort": 80
}
]
```
2) Create target service with the label matching the selector of the port rule. Target service has 0 port rules, it should just get registered to the LB port rule as it has targetPort already defined.

Bug: service doesn't get registered to the LB

@deniseschannon @vincent99

**Comment by sangeethah** [comment]
Tested with v1.2.0-pre4-rc12

Create a service - s1 with label "foo=bar".
Create a Lb service , with portRule having selector as "foo=bar", source port and target port.

When LB service is accessed , all the containers of service s1 are reachable.
