### ISSUE TITLE
DNS resolution fails in Kubernetes after upgrade from 1.1.4 to 1.2.0-pre4-rc11

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#6718]
**Rancher Version:**1.1.4 to 1.2.0-pre4-rc11

**Docker Version:**1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):**Ubuntu, Cloud

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**Single node

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**Kuberneres

**Steps to Reproduce:**
1. Create a Kubernetes env in v1.1.4
2. Upgrade rancher to 1.2.0-pre4-rc11
3. Upgrade environment

**Results:** 
DNS resolution fails. kubectl cannot get nodes/pods
```
> kubectl get nodes
Unable to connect to the server: dial tcp: lookup master on 169.254.169.250:53: no such host
```
ping from user pods does not work
```
root@k8testrc1-j22ro:/# ping www.google.com
ping: unknown host

```

**Comment by alena1108** [comment]
based on debugging info, removing the 169.x.x.x route from the set of routes inside k8s containers, helps to restore the dns functionality:

```
root@k8testrc12-55c6z:/# ip route show
default via 172.17.0.1 dev eth0
10.42.0.0/16 dev eth0  proto kernel  scope link  src 10.42.90.24
169.254.169.250 dev eth0  scope link  src 10.42.90.24
172.17.0.0/16 dev eth0  proto kernel  scope link  src 172.17.0.8
```

**Comment by soumyalj** [comment]
Tested with upgrade from 1.1.4 to 1.2.0-pre4-rc12. DNS resolution works in Kubernetes after upgrade from 1.1.4 to 1.2.0-pre4-rc12.
