### ISSUE TITLE
Support moving volumes from one host to another for EBS.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6720]
Rancher-server version - v1.2.0-pre4-rc10
Deploy "rancher-ebs" stack.

Steps to reproduce the problem:
1. Create a volume - "hello" in "Storage pool" of rancher-ebs.
2. Start a container on host 1 with vol - "hello".
3. Exec to container and write some data in this volume.
4. Delete this container .
5.  Start another container on host 2 with the same vol - "hello"  

Exec into the container and read the contents of this volume.
We do not see the contents written in step 2.

Expected Behavior:
We should have been able to  see the same volume from step2 being used for bringing up the new container.

**Comment by LLParse** [comment]
I tried this for 2 hosts in the same region but different availability zones. I got this error when mount was called:
`Failed to attach ebs volume-id vol-a72bbf21 as device:/dev/sdf to aws instance-id i-254aa2b3. \nAn error occurred (InvalidVolume.ZoneMismatch) when calling the AttachVolume operation: The volume 'vol-a72bbf21' is not in the same availability zone as instance 'i-254aa2b3'`

EBS volumes may only be attached to instances within the same availability zone.

I retried this for 2 hosts in the same region and availability zone and successfully reproduced. The block device is formatted as `ext4` during mount call but not in an idempotent fashion, as a result the filesystem is reformatted during each subsequent mount. Creating the filesystem should occur exactly once as part of the create phase.

**Comment by LLParse** [comment]
There is a very similar use case that will require scheduler changes:

1. Create an environment with 2 AWS hosts in same AZ
2. Create a service comprised of 1 container with an EBS volume attached
3. Deactivate the host that the container is running on
4. Delete the container to force it to be placed on the other host

Expected: Scheduler will schedule container on the other host (hopefully it is in the same AZ)

Result: Scheduler refuses to schedule container with this error message:
`Unhealthy (Failed to allocate instance [container:1i20553]: Bad instance [container:1i20553] in state [stopping]: Scheduling failed: valid host(s) [5], volume [1536] must have exactly these pool(s): [21], volume [3986] must be one of pool(s) [21], valid host(s) [5])`

**Comment by cjellick** [comment]
This behavior is confusing but intended. The failure to allcoate is actually not because of the EBS volume but because of the local volume you defined. By defining that local volume explicitly in the volumes section of the yaml, you basically said “create a globally unique volume using the local driver”. That volume is only on a single host and it is the hsot you deactivated.

**Comment by LLParse** [comment]
Confirmed, if I remove all named volumes using local storage driver (explicitly or otherwise), I see the container is rescheduled on the other host. Thanks for looking at this @cjellick

**Comment by sangeethah** [comment]
Rancher-server version - v1.2.0-pre4-rc14
Deploy "rancher-ebs" stack - rancher/storage-ebs:v0.6.0

Steps to reproduce the problem:

1. Create a volume - "hello" in "Storage pool" of rancher-ebs.
2. Start a container on host 1 with vol - "hello".
3. Exec to container and write some data in this volume.
4. Delete this container .
5. Start another container on host 2 with the same vol - "hello"
6. Exec into the container and read the contents of this volume.
7. Contents written in step3 is are present in this volume as expected.
