### ISSUE TITLE
Cross host networking is broken for "vxlan" networking mode.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6722]
Rancher Version: v1.2.0-pre4-rc11

Steps to reproduce the problem:
Created a "cattle" default environment.
Deleted healthcheck and scheduler stacks and then deleted ipsec stack.

Deployed vxlan.
After this added healthcheck and scheduler stacks.
healthcheck and scheduler container are stuck in "Initializing" state forever.

Cross host networking is broken between containers.

**Comment by deniseschannon** [comment]
Must use vxlan using rancher/net:v0.7.2 for testing.

**Comment by sangeethah** [comment]
Tested with rancher/net:v0.7.3 and rancher/plugin-manager:v0.2.9 with  rancher-server version - v1.2.0-pre4-rc14

Infra stack comes up successfully (including healthcheck and scheduler). Able to start health check enabled services successfully.
