### ISSUE TITLE
pulling private images and have already added my docker hub registry

### ISSUE THREAD

**Issue by mwaaas** [rancher/rancher#6723]
Racher unable to pull private repos from an organisation I have been invited. I have already added my registry

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.2.0-pre3` Cattle: `v0.169.5` UI: `v1.2.11` |
|Access|`github` `admin`|
|Orchestration|`Swarm`|
|Route|`swarm-tab.projects.index`|

**Comment by tfiduccia** [comment]
Version - v1.2.0-pre4-rc11
I can't reproduce your problem.  I added a registry and was able to use it.  Please provide more information.  What registry are you using?  If it's private are you sure you have the correct username and Password?

**Comment by mwaaas** [comment]
@tfiduccia Thanks for checking

Try this method to reproduce.

- create an organisation dockerhub account
- invite dockerhub uses to that account
- add one of the invited users to rancher registry
- trying pulling a private image

**Comment by tfiduccia** [comment]
Can you please to to v1/projects/<projectid>/registrycredentials and tell me how many active credentials you have in there.  There is currently a bug that will create multiple credentials and will give you a problem pulling the image.

**Comment by mwaaas** [comment]
@tfiduccia  Have reproduced the issue. so In dockerhub I can log in with my email and password. was using my email as the user name thats why it was not working. Have changed and used my username instead of email and it has worked
