### ISSUE TITLE
Rancher on AWS Production

### ISSUE THREAD

**Issue by geostant** [rancher/rancher#6724]
**Rancher Version:**
Latest (2016-11-22)

**Docker Version:**
1.12.1

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04 LTD @ AWS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA with External RDS MySQL (4 CPU / 16G RAM)

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
1. Launched 3 instances on AWS
2. Installed docker 1.12 on each instance
3. Created MySQL instance in RDS
4. Created AWS ELB with HTTP 80:80 and HTTPS 443:443 *****
5. Ran the initial rancher machine to generate the HA script and gave it my ELB endpoint
6. Removed the rancher container
7. Launched the HA script on the first node ONLY

In the rancher-ha logs I can see this:
```
time="2016-11-22T06:11:04Z" level=info msg="Cluster changed, index=0, members=[172.31.35.84, , ]" component=service
time="2016-11-22T06:11:04Z" level=info msg="Waiting for server to be available" component=cert
time="2016-11-22T06:11:04Z" level=info msg="Can not launch agent right now: Server not available at http://172.17.0.1:18080/ping:" component=service
time="2016-11-22T06:11:14Z" level=info msg="Forgetting cluster member" component=manager member={2 790d399c-500e-4153-afd0-f0c0fc0cfca1 172.31.35.84 map[] 0 11 1}
time="2016-11-22T06:11:14Z" level=info msg="Currently Master: true" component=manager master=true
time="2016-11-22T06:11:14Z" level=info msg="Assigning 374088da-e912-4213-b7ec-4f57fa73e2ac 172.31.35.84 to index 1" component=manager
time="2016-11-22T06:11:19Z" level=info msg="Cluster changed, index=1, members=[172.31.35.84, , ]" component=service
```

Then I've found an old issue in rancher's git: https://github.com/rancher/rancher/issues/4634
I've tried some of the suggestions in that post.

My current setup is:
**ELB** 
TCP 80:81
SSL 443:444
HTTP 18080:18080

In addtion, I've change the CATTLE HOST URL to `http` instead of `https` in the HA script.

**Results:** 
The logs now looks like this:

```
time="2016-11-22T07:43:23Z" level=info msg="Waiting for API keys for service account" component=db
time="2016-11-22T07:43:23Z" level=info msg="Can not launch agent right now: Waiting for server to create service API key" component=service
```

**Expected:**
flawless 3 nodes HA

**Comment by vincent99** [comment]
HA is completely revamped in newest RCs and significantly simpler, please give it a try.
