### ISSUE TITLE
Only one service link is shown upon saving in service editor and stack graph view.

### ISSUE THREAD

**Issue by deviousgeek** [rancher/rancher#6725]
**Rancher Version:**

v1.2.0-pre4-rc11

**Docker Version:**

Docker version 1.12.3, build 6b644ec

**OS and where are the hosts located? (cloud, bare metal, etc):**

Ubuntu 16.04LTS x64, Bare Metal.

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

Single Node Rancher / Internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

Cattle

**Steps to Reproduce:**

1. Add a service with more than one link (in my example, redis and mariadb).
2. Click save, the services will be linked up.

**Results:** 
1. Go back to edit the service, only one is shown although both are actually linked up in the backend.

![2016-11-22-195835_1013x434_scrot](https://cloud.githubusercontent.com/assets/4342988/20517184/1133f174-b0ee-11e6-9562-2b8555371730.png)

2. Look at the graph, only one link is shown for the service.

![2016-11-22-195359_1686x591_scrot](https://cloud.githubusercontent.com/assets/4342988/20517194/1d90b9a2-b0ee-11e6-9288-83798650913d.png)

3. Going to edit the container within the service shows that both are actually linked up in operation.
![2016-11-22-195743_967x432_scrot](https://cloud.githubusercontent.com/assets/4342988/20517209/2f5e0f18-b0ee-11e6-8973-51c0211cdea7.png)

**Expected:**

I would expect both to be shown after closing (and saving) in the edit service modal and also on the view graph page.

![2016-11-22-195734_1004x494_scrot](https://cloud.githubusercontent.com/assets/4342988/20517227/462fc9de-b0ee-11e6-8c1a-eccb369d2e66.png)

Thanks!

**Comment by tfiduccia** [comment]
Version - v1.2.0-pre4-rc11
Checked and this is indeed broken and a bug.  I took a look and it's only giving me 1 service in the API as well instead of two.  So not a UI bug.
![image](https://cloud.githubusercontent.com/assets/11514927/20534099/1ab0bcb0-b09d-11e6-96e1-7ed1b47af0bc.png)

**Comment by sangeethah** [comment]
Tested with  Rancher server - v1.2.0-pre4-rc12
When services are linked to multiple services , all the links are shown in service edit view and stack graph view.
