### ISSUE TITLE
Swarm CLI fails to launch through UI

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#6728]
**Rancher Version:**1.2.0-pre4-rc11

**Docker Version:**1.12.2

**OS and where are the hosts located? (cloud, bare metal, etc):**Ubuntu, Cloud

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**Single node

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**Cattle

**Steps to Reproduce:**
1. Create a Swarm setup by launching the swarmkit catalog
2. After the swarm stack comes up, click on CLI from "Swarm" tab

**Results:** 
CLI does not launch. Error screen below:

<img width="970" alt="screen shot 2016-11-22 at 11 30 55 am" src="https://cloud.githubusercontent.com/assets/18536626/20539043/85286e0c-b0a8-11e6-9aa2-ff19ba705f60.png">

**Comment by LLParse** [comment]
This is probably because swarm mode (current) != swarm (old).

With swarm mode, we will need the `Swarm CLI` link in the UI to point to a swarmkit container on a host with label `swarm=manager`. If there are no hosts, return `No manager available at this time` error response.

**Comment by tfiduccia** [comment]
Version - v1.2.0-rc2
Verified fixed
