### ISSUE TITLE
In edit environment template, edit config doesn't remember previous info I entered

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#6729]
**Rancher Version:** Version - v1.2.0-pre4-rc11

**Steps to Reproduce:**
1.  Create environment template and enable a catalog and put data in it
2.  Edit the environment template and then edit config

**Results:** The info I entered is no longer there

**Expected:** The info should be there.

**Comment by vincent99** [comment]
[after rc14]

**Comment by tfiduccia** [comment]
Version - v1.2.0-pre4-rc15
Verified fixed
