### ISSUE TITLE
For LBs with "selector rules" , the "To" field in the Stack view is show as "/"

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6730]
Rancher server version - v1.2.0-pre4-rc12

Steps to reproduce the problem:
Create an LB with selector rules.

The "To" field in the Stack view for this LB is show as "/"
<img width="1509" alt="screen shot 2016-11-22 at 6 12 09 pm" src="https://cloud.githubusercontent.com/assets/4266958/20549218/3c9a362a-b0df-11e6-9db5-20ab3b7ab819.png">

**Comment by tfiduccia** [comment]
Version - v1.2.0-pre4-rc14
Verified fixed
