### ISSUE TITLE
Pods created before upgrade cannot be pinged by their names after an upgrade

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#6733]
**Rancher Version:**1.1.4 to 1.2.0-pre4-rc12

**Docker Version:**1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):**Ubuntu, Cloud

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**Single node

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**Kubernetes

**Steps to Reproduce:**
1. Create a Kubernetes env in v1.1.4. Create services/rcs/pods
2. Upgrade rancher to v1.2.0-pre4-rc12. 
3. Upgrade Kubernetes env to K8s1.4.6

**Results:**
Pods created before upgrade cannot be pinged by their names after an upgrade 
Ping by name for pods created after upgrade is successful
```
root@k8testrc1-4l9a2:/# ping k8testrc2-ztbls
ping: unknown host
```

**Comment by alena1108** [comment]
Pods are pingable by podName.serviceName.namespace.cluster.internal. Only if pinged from containers of the same service, pinging just by name works. I've tested it on your setup, it works:

```
ping k8testrc2-ztbls.k8test2
PING k8testrc2-ztbls.k8test2.default.svc.cluster.local (10.42.152.233): 48 data
bytes
56 bytes from 10.42.152.233: icmp_seq=0 ttl=64 time=0.258 ms
56 bytes from 10.42.152.233: icmp_seq=1 ttl=64 time=0.168 ms
^C--- k8testrc2-ztbls.k8test2.default.svc.cluster.local ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
```


Please retest

**Comment by soumyalj** [comment]
ok. Tried with ping k8testrc1-4l9a2.k8test1.default.svc.cluster.local
```
root@k8testrc2-d01e7:/# ping k8testrc1-4l9a2.k8test1.default.svc.cluster.local
PING k8testrc1-4l9a2.k8test1.default.svc.cluster.local (10.42.185.150): 48 data
bytes
56 bytes from 10.42.185.150: icmp_seq=0 ttl=64 time=0.415 ms
56 bytes from 10.42.185.150: icmp_seq=1 ttl=64 time=0.170 ms
56 bytes from 10.42.185.150: icmp_seq=2 ttl=64 time=0.147 ms
56 bytes from 10.42.185.150: icmp_seq=3 ttl=64 time=0.187 ms
56 bytes from 10.42.185.150: icmp_seq=4 ttl=64 time=0.373 ms
56 bytes from 10.42.185.150: icmp_seq=5 ttl=64 time=0.249 ms
```
