### ISSUE TITLE
Hostname entry to self IP is not being added

### ISSUE THREAD

**Issue by darrenscerri** [rancher/rancher#6736]
**Rancher Version:**
rancher-1.2.0-rc13

**Docker Version:**
1.12.2

**OS and where are the hosts located? (cloud, bare metal, etc):**
Hyper-v, Centos 7.2

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Create a container. Entry for container's hostname is not present in rancher-1.2.0-rc13

Rancher 1.1.4
![screen shot 2016-11-23 at 14 13 35](https://cloud.githubusercontent.com/assets/729230/20563060/163bf7fe-b187-11e6-9a6f-23c552af5c24.png)

Rancher 1.2.0-rc13
![screen shot 2016-11-23 at 14 13 39](https://cloud.githubusercontent.com/assets/729230/20563059/163b697e-b187-11e6-85cd-e02657cff0ae.png)

**Results:** 
Host entry is not present for container hostname

**Expected:**
Host entry is present for container hostname

**Comment by vincent99** [comment]
Containers are configured to point to ranchers dns server, which will have an answer for the container name; we do not manage host files.

**Comment by darrenscerri** [comment]
If the container tries to ping its hostname, the hostname does not resolve to the container's ip.
