### ISSUE TITLE
VMs created in 1.1.0 are not showing up on host

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#6738]
**Rancher Version:** v1.2.0-pre4-rc12

**Steps to Reproduce:**
1.  go to 1.1.4 and create a VM service and VM from the Virtual Machine page
2.  Upgrade to 1.2.0
3.  Upgrade the environment that the VMs were on

**Results:** The service is still on the service page.  But not on host.  The VM that was created by the VM page is also not showing up on host.

**Expected:**  Both should show up.

**Comment by vincent99** [comment]
[after rc14]

**Comment by tfiduccia** [comment]
Version - v1.2.0-pre4-rc15
Verified fixed
