### ISSUE TITLE
Log spam "Error during Unmarshal for file ...  cannot unmarshal !!str `2` into config.RawService\n"

### ISSUE THREAD

**Issue by typia** [rancher/rancher#6742]
**Rancher Version:**

1.2pre3

**Docker Version:**

Docker 1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):**

Debian 8 VMs in a datacenter

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

Single Node Rancher External DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

Cattle

**Steps to Reproduce:**

Everything is ok by my side every stack are green, but my logs are spammed and can't find out where it comes from

**Results:** 

logs are spammed :

`time="2016-11-23T19:08:50+01:00" level=error msg="Skipping the template version: efs/0, error: yaml: unmarshal errors:\n  line 1: cannot unmarshal !!str `2` into config.RawService"
time="2016-11-23T19:08:50+01:00" level=error msg="Error during Unmarshal for file DATA/library/infra-templates/healthcheck/0/docker-compose.yml : yaml: unmarshal errors:\n  line 1: cannot unmarshal !!str `2` into config.RawService\n"
time="2016-11-23T19:08:50+01:00" level=error msg="Skipping the template version: healthcheck/0, error: yaml: unmarshal errors:\n  line 1: cannot unmarshal !!str `2`
into config.RawService"
time="2016-11-23T19:08:50+01:00" level=error msg="Error during Unmarshal for file DATA/library/infra-templates/ipsec/0/docker-compose.yml : yaml: unmarshal errors:\n  line 1: cannot unmarshal !!str `2` into config.RawService\n"
time="2016-11-23T19:08:50+01:00" level=error msg="Skipping the template version: ipsec/0, error: yaml: unmarshal errors:\n  line 1: cannot unmarshal !!str `2` into config.RawService"
time="2016-11-23T19:08:50+01:00" level=error msg="Error during Unmarshal for file DATA/library/infra-templates/network-services/0/docker-compose.yml : yaml: unmarshal errors:\n  line 1: cannot unmarshal !!str `2` into config.RawService\n"
time="2016-11-23T19:08:50+01:00" level=error msg="Skipping the template version: network-services/0, error: yaml: unmarshal errors:\n  line 1: cannot unmarshal !!str `2` into config.RawService"
time="2016-11-23T19:08:50+01:00" level=error msg="Error during Unmarshal for file DATA/library/infra-templates/nfs/0/docker-compose.yml : yaml: unmarshal errors:\n
line 1: cannot unmarshal !!str `2` into config.RawService\n"
time="2016-11-23T19:08:50+01:00" level=error msg="Skipping the template version: nfs/0, error: yaml: unmarshal errors:\n  line 1: cannot unmarshal !!str `2` into config.RawService"
time="2016-11-23T19:08:50+01:00" level=error msg="Error during Unmarshal for file DATA/library/infra-templates/scheduler/0/docker-compose.yml : yaml: unmarshal errors:\n  line 1: cannot unmarshal !!str `2` into config.RawService\n"
time="2016-11-23T19:08:50+01:00" level=error msg="Skipping the template version: scheduler/0, error: yaml: unmarshal errors:\n  line 1: cannot unmarshal !!str `2` into config.RawService"
time="2016-11-23T19:08:50+01:00" level=error msg="Error during Unmarshal for file DATA/library/infra-templates/swarm/0/docker-compose.yml : yaml: unmarshal errors:\n  line 1: cannot unmarshal !!str `2` into config.RawService\n"
time="2016-11-23T19:08:50+01:00" level=error msg="Skipping the template version: swarm/0, error: yaml: unmarshal errors:\n  line 1: cannot unmarshal !!str `2` into config.RawService"
time="2016-11-23T19:08:50+01:00" level=error msg="Error during Unmarshal for file DATA/library/infra-templates/vxlan/0/docker-compose.yml : yaml: unmarshal errors:\n  line 1: cannot unmarshal !!str `2` into config.RawService\n"
time="2016-11-23T19:08:50+01:00" level=error msg="Skipping the template version: vxlan/0, error: yaml: unmarshal errors:\n  line 1: cannot unmarshal !!str `2` into config.RawService"` 

**Expected:**

**Comment by deniseschannon** [comment]
What catalog are you pointing to for your `library` catalog?

**Comment by typia** [comment]
HI @deniseschannon I had a custom catalog pointing to our private git, I already tried to remove it before posting but still spamming.

**Comment by deniseschannon** [comment]
It sounds like you have a v2 syntax for docker-compose.yml, which isn't supported yet. This would be supported post-v1.2.0-pre3.

**Comment by typia** [comment]
Hi Denise,
ok but how can I know which docker-compose is impacted ?
And I'm pretty sure I did not use any of my docker-compose since 1 week and this happens since 2 or 3 days ?

Thanks

**Comment by deniseschannon** [comment]
any files that are using v2 syntax would be causing this.

Basically any file that starts with this at the top:

```
version: `2`
```

**Comment by typia** [comment]
I checked every stacks by watching their config, none is using v2.

Btw, I'm pretty sure v2 was supported because the first stacks created were used copying v2 docker.-compose files.
Rancher then created the stacks and converted it somehow because I could not find any trace of it in my configs.

Please forgive me if I'm searching the wrong place :)

**Comment by vincent99** [comment]
@deniseschannon it's coming from our infra vxlan template for pre4 (`Error during Unmarshal for file DATA/library/infra-templates/vxlan/0/docker-compose.yml`)

I think the rancher-compose for pre3 supported v2 already, but the catalog service did not.

**Comment by deniseschannon** [comment]
@vincent99 is right. Our catalog-service wasn't able to read `v2` for templates from the catalog until after. These are benign errors and shouldn't affect your Rancher setup.
