### ISSUE TITLE
Kubernetes environment stuck at "Starting services (1 of 10)"

### ISSUE THREAD

**Issue by geostant** [rancher/rancher#6745]
**Rancher Version:**
1.1.4

**Docker Version:**
1.12.1

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04 on AWS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node HA (ext. db [rds])

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes (3 R3.8XL AWS instances)

**Steps to Reproduce:**
Setup HA
Run rancher's kubernetes bootstrap command on the nodes

**Results:** 
stuck at 1/9

**Expected:**
Functional cluster

**Comment by deniseschannon** [comment]
Did you add hosts into your kubernetes environment?

Also, Rancher doesn't officially support Docker 1.12 on 1.1.4.

**Comment by geostant** [comment]
@deniseschannon the process won't start without hosts being added, so that not the case.
which docker ver. do you recommend ?
thanks :)

**Comment by deniseschannon** [comment]
We recommend Docker 1.10.3 with Rancher 1.1.4

**Comment by geostant** [comment]
I've tried that out yesterday (1.10.3)
but unfortunately that didn't helped.

This time the HA server (single node) didn't came up at all.
I've run the initial rancher HA generator,
downloaded the script and removed the generator container.
Ran the script, got a UI after 10-20 minutes but in HA I couldn't see my host listed.

I've decided to give up on rancher and run kubernetes directly.


Thanks for the support so far.

**Comment by deniseschannon** [comment]
Ok, I'll close this out then. A couple of options are to run a single instance of Rancher to get k8s up. There are lots of complexity in HA that could be preventing you from getting set up, but we do have users who have HA and k8s running together. 

We are updating HA in our 1.2 release so please come try us again. :)

**Comment by pakuni** [comment]
I am also facing similar issue it hangs up in service 2/10, my docker version is 1.12.6

**Comment by aemneina** [comment]
@pakuni youre commenting in closed tickets. Can you open a new ticket with rancher deployment details?
