### ISSUE TITLE
upgraded environment hosts don't delete on provider side

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#6750]
**Rancher Version:** version 1.1.4 -> 1.2.0-pre4-rc14

**Steps to Reproduce:**
1.  Create a 1.1.4 setup
2.  Add a environment and add a couple of EC2 machines through the Add Host (add a few digital ocean as well)
3.  Add some services
4.  After they are all setup, upgrade rancher from 1.1.4 to 1.2.0
5.  Go to host page, and deactivate and delete host from that page

**Results:** Hosts are removed from Host list page, but they aren't removed on the provider side.

**Expected:**  Should be removed from provider side.

**Comment by tfiduccia** [comment]
Comment: this looks to be a amazon EC2 issue only.  Digital Ocean and Packet machine delete

**Comment by deniseschannon** [comment]
This will remain as a known issue for 1.1.x upgrade to 1.2+ but as it's been 6 months since releasing 1.2, most of our users have already moved to 1.2. 

We will not be fixing this use case as upgrades from 1.2 to any later version does not have this issue.
