### ISSUE TITLE
Rancher server stuck in "Upgrading Environment.." (1.1.4 to rc14,  external db) - no infra services deployed in infra stacks

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#6751]
**Rancher Version:**
1.1.4 --> rc14
**Docker Version:**
1.12
**OS and where are the hosts located? (cloud, bare metal, etc):**
RancherOS 0.7.1 on AWS
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
External DB (MySQL 5.7) on DO
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
- Start rancher server 1.1.4 with external db (MySQL 5.7) 
```
 sudo docker run -d --restart=unless-stopped -p 8080:8080     -e CATTLE_DB_CATTLE_MYSQL_HOST=xxxxx     -e CATTLE_DB_CATTLE_MYSQL_PORT=3306     -e CATTLE_DB_CATTLE_MYSQL_NAME=cattle     -e CATTLE_DB_CATTLE_USERNAME=cattle     -e CATTLE_DB_CATTLE_PASSWORD=cattle     rancher/server:v1.1.4
```
- register one host to the rancher server
- deploy any service (in my case wordpress stack from catalog)
- stop the old rancher server container and start a new rancher server version (v1.2.0-pre4-rc14) with the same parameters:
```
sudo docker run -d --restart=unless-stopped -p 8080:8080     -e CATTLE_DB_CATTLE_MYSQL_HOST=xxxxxxx     -e CATTLE_DB_CATTLE_MYSQL_PORT=3306     -e CATTLE_DB_CATTLE_MYSQL_NAME=cattle     -e CATTLE_DB_CATTLE_USERNAME=cattle     -e CATTLE_DB_CATTLE_PASSWORD=cattle     rancher/server:v1.2.0-pre4-rc14
```
**Results:** 
The server start with upgrade button, after clicking on the upgrade button the server is stuck in "Upgrade Environment..." state and no infra containers are starting

**Comment by alena1108** [comment]
Note: infra stacks got created, but they have 0 services created. Might be related to rancher-compose

**Comment by galal-hussein** [comment]
I replicated the setup but this time with Rancher server and Database server are in the same AZ, the upgrade finished successfully and i was able to see the infra containers starting and hosts registered successfully.

**Comment by ibuildthecloud** [comment]
We should increase the timeout in event-subscriber to something greater.  Ideally it would be better to remove the dynamic external handler registration.  Those things can be addressed later.  Right now this isn't a blocker.  People really shouldn't have high latency connections to the DB.

**Comment by deniseschannon** [comment]
@galal-hussein Can you retest?

**Comment by deniseschannon** [comment]
Closing in favor of 6753
