### ISSUE TITLE
"Upgrade Error- Validation failed in API"  messages seen in UI after upgrading from 1.2.0-pre3 to 1.2.0-pre4-rc14

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#6752]
**Rancher Version:** 1.2.0-pre3 to 1.2.0-pre4-rc14

**Docker Version:**1.11.2

**OS and where are the hosts located? (cloud, bare metal, etc):**Ubuntu, Cloud

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**Cattle and Kubernetes

**Steps to Reproduce:**
1. Create a Cattle and Kuberentes setup in 1.2.0-pre3
2. Upgrade to 1.2.0-pre4-rc14

**Results:** 
Upgrade Error- Validation failed in API:action messages are seen in the UI. 
<img width="1920" alt="screen shot 2016-11-23 at 2 58 18 pm" src="https://cloud.githubusercontent.com/assets/18536626/20585930/1b871202-b1b4-11e6-8e6f-da1f2c176326.png">

<img width="1324" alt="screen shot 2016-11-23 at 3 02 30 pm" src="https://cloud.githubusercontent.com/assets/18536626/20585952/5e60168c-b1b4-11e6-84dc-0a825881bd34.png">

The messages persisted in Cattle even after upgrade

**Comment by vincent99** [comment]
These types of error messages never go away automatically in the UI, so that part is normal.

**Comment by soumyalj** [comment]
Tested with upgrade from 1.2.0-pre3 to rc15. The above error messages did not show up.
