### ISSUE TITLE
Rhel 7.2 docker 1.12 - Not able to exec into container.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6756]
Rancher Version: v1.2.0-pre4-rc14
Docker Version: docker 1.12 

Steps to reproduce the problem:
Create a service.
Try to exec into any one of the container.
User is presented with "connecting.." shell which self dismisses very quickly.

**Comment by StrongMonkey** [comment]
It seems that if container is in managed network mode, we can not even exec into container in `docker cli`.

**Comment by deniseschannon** [comment]
@sangeethah I believe this is a docker/RHEL issue and not a Rancher one. As @StrongMonkey has mentioned even on the host, even if you log into a host and try to `docker exec` into the container, it doesn't work. 

I was able to start the same container on an Ubuntu 16.04 host and `docker exec` into the host as well as be able to exec into the host through Rancher's UI. 

I'm closing as it's a Docker/RHEL bug and not a Rancher one.

**Comment by psyhonut** [comment]
But Rancher 1.1.4 works fine.

**Comment by psyhonut** [comment]
@deniseschannon But Rancher 1.1.4 works fine.

**Comment by StrongMonkey** [comment]
@psyhonut This might be related to our new network design. This only happens in rancher managed network containers where rancher set its network mode to `none` and have some special volume bind to it.

**Comment by pulberg** [comment]
@StrongMonkey I am having this issue on RHEL7.2/Docker 1.12.3 with Rancher 1.2.0 - 

Container network - "Managed"
Volumes - 
None
Exec shell in Rancher stuck at "Connecting..."
Docker CLI working correctly - 
```
docker exec -it r-centos-b10e7cfb bash
[root@851e33ee22c6 /]#
```


Container network - "None"
Volumes - 
/var/run/docker.sock:/var/run/docker.sock
/var/lib/docker:/var/lib/docker
Exec shell in Rancher stuck at "Connecting..."
Docker CLI working correctly - 
```
docker exec -it r-janitor-cleanup-1-35bf1675 bash
bash-4.3#
```

Container network - "Managed"
Volumes - 
None
Exec shell in Rancher stuck at "Connecting..."
Docker CLI not working - 
```
docker exec -it r-nginx-39a131e3 bash
rpc error: code = 13 desc = invalid header field value "oci runtime error: exec failed: cannot exec a container that has run and stopped\n"
```

**Comment by StrongMonkey** [comment]
@pulberg Thank you for providing the info, i ll look into it

**Comment by brutus333** [comment]
I am seeing this issue too. It is related to containers with command starting with /.r/r. All the others are working fine. What cause the container to be started this way? I did not configured such a prefix for command in docker-compose or Dockerfile...

**Comment by StrongMonkey** [comment]
@brutus333 It is the new network design for rancher managed network containers. we have special volumes binding to our rancher managed container to make it work.

**Comment by psyhonut** [comment]
@StrongMonkey so what is workaround?

**Comment by StrongMonkey** [comment]
@psyhonut I can't provide an answer now, but we will try to fix the case where `docker cli` works but `rancher exec` doesn't work.

**Comment by romangallego** [comment]
I think the rancher agent running on the added host (in my case is rancher/agent:v1.1.3) is not able to write into the /var/run/docker.sock

time="2017-01-31T17:42:49Z" level=error msg="Error writing EOT message." error="write unix @->/var/run/docker.sock: write: broken pipe
