### ISSUE TITLE
Rhel 7.2 docker 1.12 - Not able to get container stats.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6757]
Rancher Version: v1.2.0-pre4-rc14
Docker Version: docker 1.12

Steps to reproduce the problem:
Create a service.
All container stats are empty .

**Comment by sangeethah** [comment]
automation test - ```test_host_api_containerstats``` hangs forever

**Comment by StrongMonkey** [comment]
We now launch our container as managed network and this equals to setting `networkMode=none` to container. In docker if container is set as none `docker stats` will not return any info about it. Need a workaround for this.

**Comment by deniseschannon** [comment]
@StrongMonkey containers launched in the managed network should be `networkMode=managed`. This is what happens in an ubuntu setup.

**Comment by deniseschannon** [comment]
I checked in the RHEL setup, and this is also happening, where the container is getting `networkMode=managed`.

**Comment by StrongMonkey** [comment]
@deniseschannon NetworkMode set in managed container inspect is set as none instead, we just just used cni plugin to inject network interface. If you inspect into managed container the network mode will be none and `docker stats` won't give none container stats.

**Comment by deniseschannon** [comment]
@StrongMonkey But that's the same case as in the ubuntu hosts where networkmode is none on the `docker inspect`. I don't believe the `networkMode` is causing the issue. 

@sangeethah I think this is actually an issue with docker on RHEL hosts. `docker stats` isn't showing anything, which is how we show container stats. Therefore, there's no stats for Rancher to show. 

I'm closing as there is nothing that Rancher can do.
