### ISSUE TITLE
Add label to identify system containers

### ISSUE THREAD

**Issue by rlex** [rancher/rancher#6760]
Hello, maybe i'm just can't find proper info, but it will useful to have some tag, for example "io.rancher.container.infrastructure = true" for all of those rancher-provided containers (dns, metadata, agent, networkmanager, etc)
This can be useful when building graphs with, for example, grafana to display only actual app containers.

UPD: labels, not tags.

**Comment by vincent99** [comment]
If you're using the API they are marked with a `system: true`, but not as a label...

**Comment by rlex** [comment]
i'm using docker socket to monitor all containers, so labels are exported as tags.

**Comment by cjellick** [comment]
Hm, not a bad idea. We could add a label to the infra catalog entries.

@rlex I'm not sure if or when that would get done. In the meantime, could you key off the image name where organization is rancher, ie **rancher**/healthcheck?
