### ISSUE TITLE
Kubernetes Catalog templates failed to be recreated on non-default namespaces after upgrading Rancher

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#6761]
**Rancher Version:**
v1.1.4 --> v1.2.0-pre4-rc14
**Docker Version:**
1.10.3
**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 14.04
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node Rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes 1.2 --> 1.4.6
**Steps to Reproduce:**
- Install Rancher server v1.1.4 and register hosts.
- Install kubernetes 1.2 on this environment.
- Create a namespace (`kubectl create ns test-namespace`).
- Run a catalog template on this namespace (eg. Ghost template)
- Run custom pod on the namespace as well.
- Run catalog template and custom pod on the **default** namespace.
- Upgrade Rancher server from 1.1.4 to  v1.2.0-pre4-rc14
- Wait until all infra containers to be up and running and then upgrade kubernetes to 1.4.6

**Results:** 

All the created components on both namespaces got recreated except for the pods of the **catalog** template that was created on the `test-namespace` didn't get recreated on the new kubernetes after upgrade.

**Comment by alena1108** [comment]
@galal-hussein the know issue is - pods are being destroyed as a part of k8s upgrade:

https://github.com/rancher/rancher/issues/5541

and recreated if the port is created as a part of Replication controller (which people would normally do to ensure if something goes wrong - pod will be restarted by RC). Ghost catalog item by some reason doesn't have the RC, and has POD created as a standalone object. 

Closing this bug as a dup of https://github.com/rancher/rancher/issues/5541
