### ISSUE TITLE
Upgrading/Editing a LB scale does not reflect change for inactive LBs. 

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#6766]
**Rancher Version:**
v1.2.0-pre4-rc14

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
1. Create a LB with scale 2. Let it become active and then stop it so it's inactive
2. Upgrade/Edit in the UI to a new scale of 1. 

**Results:** 
 UI still shows 2 containers for the inactive service. 

**Expected:**
UI to show that the LB will be 1 container instead of 2.

**Comment by vincent99** [comment]
I doubt this applies in 2.0
