### ISSUE TITLE
Traffic is not directed when there is a port conflicts and stopping an old LB to allow a new LB use the same port

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#6767]
**Rancher Version:**
v1.2.0-pre4-rc14

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Note: I only have 3 hosts.
1. Create 1 service (nginx)
2.  Start 3 Load balancers using the same source port pointing to the service 
3. Start 4th load balancer using the same source port pointing to the service. 
4. As expected, there is a scheduling conflict as there is no available port so the 4th LB doesn't start up.
5. Stop 1 of the 3 active load balancers. 
6. 4th LB starts as expected as there is a port available. 
7. Click on the link to the port. 

**Results:** 
I am not directed to the service. Not even 503. 

**Expected:**
I should be directed to the target service. 

Note: I checked haproxy.cfg and it looks like it was programmed correctly for the target service with the correct source port. 

If I restart the service, traffic is now directed to the target service, but the initial container doesn't work.

**Comment by sangeethah** [comment]
This issue is also reproducible with services having exposed ports.
I tried this use case:

Set up with 3 hosts:
Create 3 services - s1,s2,s3 with exposed port  say  - 8777
Try to start another service - s4 with exposed port - 8777
Service fails to come up as expected.
Stop one of the existing services say s2 .
Now s4 start successfully , but the exposed port is not reachable.
I see the port "8777" being bound to both container of service s2 and s4.
```
root@sangeepre4rc14now-10acre-2:/home/sangeethahariharan1# iptables-save | grep 8787
-A CATTLE_PREROUTING ! -i docker0 -p tcp -m tcp --dport 8787 -j MARK --set-xmark 0x1068/0xffffffff
-A CATTLE_PREROUTING ! -i docker0 -p tcp -m tcp --dport 8787 -j DNAT --to-destination 10.42.47.116:80
-A CATTLE_PREROUTING ! -i docker0 -p tcp -m tcp --dport 8787 -j MARK --set-xmark 0x1068/0xffffffff
-A CATTLE_PREROUTING ! -i docker0 -p tcp -m tcp --dport 8787 -j DNAT --to-destination 10.42.104.189:80
```

On stopping containers with exposed ports , the port should be released on the host.

**Comment by leodotcloud** [comment]
https://github.com/rancher/plugin-manager/pull/24

**Comment by deniseschannon** [comment]
In plug-in-manager v0.2.10

**Comment by sangeethah** [comment]
Tested with v1.2.0-pre4-rc15 and  plug-in-manager v0.2.10

set up has 3 hosts:

Scenario1:
1. Create 1 service 
2. Start 3 Load balancers using the same source port pointing to the service
Start 4th load balancer using the same source port pointing to the service.
As expected, there is a scheduling conflict as there is no available port so the 4th LB doesn't start up.
3. Stop 1 of the 3 active load balancer services.
4th LB starts as expected as there is a port available and is also functional.

Scenario2:
Create 3 services - s1,s2,s3 with exposed port say - 8777
Try to start another service - s4 with exposed port - 8777
Service fails to come up as expected.
Stop one of the existing services say s2 .
Now s4 start successfully , exposed ports are reachable as expected.

On stopping containers with exposed ports , the port  gets  released on the host.
