### ISSUE TITLE
Start-once services become 'Unhealthy' when launching

### ISSUE THREAD

**Issue by jpdffonseca** [rancher/rancher#6768]
When launching services from a catalog with the label `start-once` set to `true`, while the container is in state `Starting` the respective service gets `Unhealthy`. This happens most of the time, tough not always. This is a _short living container_ that starts, does its job and stops.

Couldn't figure out yet the reason. Although the container starts and stops correctly, the service resolves its state to `Unhealthy` at startup. Could it be because the container takes a little longer to start? 

BTW this also happens with a `hello-world` container.

Any thoughts on this?

**Rancher Version:**
v1.1.4

**Docker Version:**
Version 1.12.3 (13776)

**Steps to Reproduce:**
Start or restart `start-once` containers and watch its service state. 

**Results:** 
The states flow is `Started-once` -> `Unhealthy` -> `Active` -> `Started-once`

**Expected:**
The states flow should be `Started-once` -> `Active` -> `Started-once`

**Comment by tfiduccia** [comment]
We saw this in our 1.2.0 pre4 builds and have fixed some of the reason this was happening.  I'm going to mark this a duplicate in favor of #6586.  We will continue to track it there.
