### ISSUE TITLE
Environment ID should be part of the URL so that bookmarks work better

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#677]
v0.18.2
Steps:
1.  Create a project
2.  Switch to that project
3.  Go to Services page
4.  Create Environment
5.  Copy Url that goes to that environment (example http://104.197.27.230:8080/static/environments/1e1)
6.  Paste that Url into new browser window

Results:
404 page
![image](https://cloud.githubusercontent.com/assets/11514927/7435669/7406767a-effa-11e4-9f9c-9875a76d446a.png)

Expected:
Should go to that service page

Additional info:
This is because the projectID is not in the URL and since it doesn't exist in Default project it can't find it.

**Comment by vincent99** [comment]
Any URL can cause this, the current environment ID is not part of the URL so if the rest of it is to a resource that isn't in the active project it will be 404.

**Comment by kaos** [comment]
+1

**Comment by tfiduccia** [comment]
Version - master 2/18
Verified fixed
