### ISSUE TITLE
Containers in same Network partition

### ISSUE THREAD

**Issue by guzmo** [rancher/rancher#6770]
**Rancher Version:**
1.1.3

**Docker Version:**
1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
CentOS7

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA Rancher external galera MariaDB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Started a RabbitMQ cluster

**Results:** 
2016-11-23 02:40:46Mnesia(rabbit@infrastructure_rabbitmq_1): ** ERROR ** mnesia_event got {inconsistent_database, running_partitioned_network, rabbit@infrastructure_rabbitmq_3}

**Expected:**
Should be reliable

How can we run the RabbitMQ containers in the same network partition? RabbitMQ needs a reliable network to be stable.

Quick feedback would be appreciated
Cheers!

**Comment by vincent99** [comment]
There is only one network address space per environment.  That message means that some of the hosts were isolated from each other and quorum was lost.  The overlay network is only as reliable as the hosts and underlying network it is running on top of.
