### ISSUE TITLE
AddServiceLink Action in API

### ISSUE THREAD

**Issue by nereliz** [rancher/rancher#6771]
**Rancher Version:**
V 1.1.4

**Docker Version:**
Docker version 1.10.3,

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 14.04.4 LTS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
MySQL external DB.

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
1. Create a few services.
2. Create load balancer.
3. Add few domains in load balancer pointing to new services.
4. Open service A add some Service Links to the load balancer making sure names are not unique.
5. Switch to API mode ( I was using cURL and PHP-cURL )
6. Try to make a call **http://${RANCHER_URL}/v1/services/${ServiceA_ID}?action=addservicelink** data: **{"servicelink":{"name":"unique","serviceId":"loadbalancer_id"}}**
7. You will get an error: **{"id":"9bbf2d8e-f722-4cd9-a091-e5eba81009cf","type":"error","links":{},"actions":{},"status":422,"code":"NotUnique","message":null,"detail":null,"fieldName":"serviceId"}**
8. If you pull everything down using API call  **serviceconsumemaps** build the map as appropriate append the array with **{"name":"unique","serviceId":"loadbalancer_id"}**
9. Make the a call **http://${RANCHER_URL}/v1/services/${ServiceA_ID}?action=setservicelinks** providing new made array.
10. Status is ok and service link is added. So it where should be no errors in first API call. Steps 8-9 I'm using as work around for now.

The issue is then I want to add Service Link to the existing service and the link is pointing to a load balancer using api key.

**Results:** 
{"id":"9bbf2d8e-f722-4cd9-a091-e5eba81009cf","type":"error","links":{},"actions":{},"status":422,"code":"NotUnique","message":null,"detail":null,"fieldName":"serviceId"}

**Expected:**
200 OK as where should not be a problem different names pointing to the same load balancer.

**Comment by vincent99** [comment]
@nereliz Is this still a problem in 1.3.x?
