### ISSUE TITLE
Failed to pull the catalog from git repo

### ISSUE THREAD

**Issue by smith64fx** [rancher/rancher#6772]
**Rancher Version:**
1.7.1

**Docker Version:**

**OS and where are the hosts located? (cloud, bare metal, etc):**
cloud (Google Cloud)

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**

**Results:** 

**Expected:**

**RancherOS Version: (ros os version)**
1.7.1

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
GCE

Hey guys,
I just deployed ROS on GCE using this script: https://github.com/rancher/os-packer

I used
```
make release
gsutil cp ./rancheros-${RANCHEROS_VERSION}.tar.gz gs://ros-images/
```
After that I created the image and finally the instance.
Everything worked fine.

But everytime I try to start the rancher
```

```

I get this error
```
049bcd5945e9-docker-machine-driver-packet => /usr/local/bin/docker-machine-driver-packet"
time="2016-11-25T15:42:05Z" level=info msg="Creating schema machine, roles [admin user readAdmin]" id=1ds14
time="2016-11-25T15:42:05Z" level=info msg="Creating schema machine, roles [readonly]" id=1ds15
time="2016-11-25T15:42:05Z" level=info msg="Creating schema packetConfig, roles [service member owner project admin user readAdmin readonly restricted]" id=1ds16
time="2016-11-25T15:42:06Z" level=info msg="Updating machine jsons for  [packet packet amazonec2 azure digitalocean]"
time="2016-11-25T15:42:07Z" level=info msg="Creating schema machine, roles [service]" id=1ds17
time="2016-11-25T15:42:07Z" level=info msg="Creating schema machine, roles [project member owner]" id=1ds18
time="2016-11-25T15:42:07Z" level=info msg="Creating schema machine, roles [admin user readAdmin]" id=1ds19
time="2016-11-25T15:42:08Z" level=info msg="Creating schema machine, roles [readonly]" id=1ds20
time="2016-11-25T15:42:09Z" level=error msg="Failed to pull the catalog from git repo https://github.com/rancher/community-catalog.git, error: exit status 1"
time="2016-11-25T15:42:09Z" level=error msg="Git pull for Catalog community failing with error: exit status 1 "
```

Anyone got some idea?

**Comment by deniseschannon** [comment]
Based on https://github.com/rancher/os/issues/1423, I'll close this issue. 

Glad it's working now!

**Comment by smith64fx** [comment]
hi @deniseschannon 
unfortunately, after restarting the google container, I got the same error again :/

![image](https://cloud.githubusercontent.com/assets/3246782/20676205/4ab09088-b58f-11e6-8f7b-7eadbd0e357b.png)

And the website isn't loading.. Seems like rancher is stuck downloading the catalog thus isn't delivering the frontend. I wish I knew what to do!

**Comment by deniseschannon** [comment]
I'm not sure why it isn't pulling from catalog, but the website should be running.

Do you have your ports open on GCE to expose `8080`?

**Comment by smith64fx** [comment]
@deniseschannon yes I do!

Now it's working. My solution was: Chaning vom GCE to Amazon AWS :) Worked instantly and I had no problems.
