### ISSUE TITLE
Infrastructure services not showing any service logs

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#6774]
**Rancher Version:** master 11/25

**Steps to Reproduce:**
1.  Setup cattle environment
2.  Click on any of the infrastructure services
3.  Click on Log tab

**Results:** Nothing is in there

**Expected:** Should have logs

**Comment by sangeethah** [comment]
@tfiduccia When testing with  - v1.2.0-pre4-rc15 / v1.2.0-pre4-rc14 , I see service logs for services in Infrastucture stacks.

**Comment by deniseschannon** [comment]
Per @ibuildthecloud, service logs are only kept around for 1 day, which is why we didn't see them in the setups.
