### ISSUE TITLE
Question: Alternatives for running agent in privileged mode

### ISSUE THREAD

**Issue by dminca** [rancher/rancher#6776]
Are there any alternatives available to avoid running the **agent** on `--privileged` mode? From what I know that's not a very *secure* :unlock: option. It's like giving Mallory full access to your system.

What `cgroups`, `ulimits` or even `SELinux/Apparmor` limitations could I apply so that I don't affect the correct functionality of Rancher?

**Comment by vincent99** [comment]
You **are** explicitly giving full control over your system to Rancher.

The agent bind mounts the docker socket and uses it to create arbitrary user-defined containers.  Those can themselves be privileged and do whatever they want.  

Some distros actually need the elevated privilege to allow the mount, and some don't.   But all are giving complete control to the agent.

**Comment by dminca** [comment]
Thank you @vincent99 for the quick-reply :simple_smile:

So I guess there are no other alternatives for granting limited access? Has anyone used this in production?

**Comment by vincent99** [comment]
Again, the *purpose* of the agent is to run whatever containers are requested by the `rancher/server` container.  For most OSes that aren't RHEL you can remove `--privileged` from the command if it makes you feel better, but write access to the Docker socket to be able to do it's job is still the functional equivalent of root on the host.

Yes, many customers and community users use Rancher in production.
