### ISSUE TITLE
SSL Error in creating multi-stack

### ISSUE THREAD

**Issue by l0ris** [rancher/rancher#6782]
**Rancher Version:**
1.1.4

**Docker Version:**
1.10.3,

**OS and where are the hosts located? (cloud, bare metal, etc):**
VirtualBox VM

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Simple Docker Environment

**Steps to Reproduce:**
./rancher-compose -p NewWordpress up using docker-compose.yml and rancher-compose.yml as explained in http://docs.rancher.com/rancher/v1.1/en/

**Results:** 
Containers doesn't starts
**Expected:**

**Comment by vincent99** [comment]
@l0ris this is not really enough information for anyone to be able to help you.. are there error messages?  What did running rancher-compose output? V do containers show up in the UI?  Etc.

**Comment by l0ris** [comment]
@vincent99 My apologies it-s my first approach with Rancher :)
Output of ./rancher-compose -p NewWordpress up using docker-compose.yml and rancher-compose.yml:

ERRO[0000] Failed to open project newwordpress: Get https://172.17.0.1:8080: x509: certificate is valid for 127.0.0.1, not 172.17.0.1 
FATA[0000] Failed to read project: Get https://172.17.0.1:8080: x509: certificate is valid for 127.0.0.1, not 172.17.0.1 

The container doesn't appear on UI  because isn't running , "docker ps -l" doesn't show the container.

**Comment by vincent99** [comment]
Assuming you have figured this out by now or given up, but you have configured rancher-compose to talk to the API as SSL but not set that up (or set it up properly with a valid cert).
