### ISSUE TITLE
Rancher HA 1.2.0 dbdump hardcoded to use local mysql

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#6785]
Executing this:

`"dbdump": "…/v2-beta/haconfigs/haconfig/dbdump"`

Gave me this:
mysqldump: Got error: 2002: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) when trying to connect

**Comment by vincent99** [comment]
This was only intended for migrating out of the single container install in the UI, which is no longer there...

**Comment by deniseschannon** [comment]
Would we want to add it back in? It seems like it'd be helpful to be able to migrate the DB out of your single container install?

**Comment by vincent99** [comment]
Since the rest of HA setup is in the CLI there's really not much reason to vs just adding something like `docker exec <ID of server> mysqldump cattle > dump.sql` to the docs..

**Comment by deniseschannon** [comment]
Updated FAQs with this tid bit.
