### ISSUE TITLE
Rancher HA 1.2.0

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#6786]
I have a HA setup running... everything appears to be chugging along happily. proof?
`xxx INFO    [main] [ConsoleStatus] Cluster membership changed [x.x.x.33:9345, x.x.x.34:9345, x.x.x.35:9345]`

looking at the v2-beta/haconfigs endpoint yields

```
"data": [
{
"id": "haConfig",
"type": "haConfig",
"links": {
"self": "…/v2-beta/haconfigs/haconfig",
"dbdump": "…/v2-beta/haconfigs/haconfig/dbdump"
},
"actions": {
"createscript": "…/v2-beta/haconfigs/haconfig/?action=createscript"
},
"baseType": "haConfig",
"dbHost": "**redacted to protect the innocent**",
"enabled": false,
"clusterSize": 0
}
],
```

the worrying part is enabled: false.

**Comment by vincent99** [comment]
`haconfig` is no longer relevant.. https://github.com/rancher/rancher/issues/6784
