### ISSUE TITLE
Can LB Agents be named to reflect the environment/service they are part of?

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#679]
Server Version - V0.18.2

Lb Agents that are created as part of LB services are name "LB Agent". It will be more clear to name the LB Agents to reflect the environment/service they are part of similar to the instances in part of a regular service.

**Comment by alena1108** [comment]
Not in the first version. The only parameter we respect from launchConfig is the port. In the future version we might support more.

**Comment by sangeethah** [comment]
Tested with build from master- Nov 19

LB Agents now are named as stackname_servicename_{n}  like any other container that is part pf a service.
