### ISSUE TITLE
Network agent not updated after removed host

### ISSUE THREAD

**Issue by kaos** [rancher/rancher#6792]
This is only a minor glitch I noticed once, and which I don't find important enough to investigate further on our end.

**Rancher Version:**

1.1.0

**Docker Version:**

1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):**

RHEL 7, bare metal

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

single node, external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

cattle

**Steps to Reproduce:**

(this is roughly from memory of what I did, haven't re-applied the steps to verify that I get same outcome again)

Add two nodes. Deploy a few services.

Add third node.
Remove third node.

N.B.
The network were most likely never setup properly between the first two nodes and the third, due to firewall rules. The third node was a mistake, it shouldn't join this particular environment.
I noticed a lot of denied traffic on UDP 500, first later. I simply removed the Network Agent container on the afflicted nodes in the environment, and then the blocked traffic disappeared.

**Results:** 

The Network Agent still attempts to setup the IPSec network with the third node.

**Expected:**

No UDP traffic between the third node and the other two nodes.

**Comment by kaos** [comment]
Oh, come to think of it. As apparently, the network agent was attempting to setup a network, which was failing, but there were no feedback of this in the UI... so, perhaps a network status page or some such, could be informative ;)

**Comment by vincent99** [comment]
Network components are their own stacks that you can see the upgrade status of in 1.2+.
