### ISSUE TITLE
UI style glitch

### ISSUE THREAD

**Issue by kaos** [rancher/rancher#6795]
**Rancher Version:**

1.1.0

When upgrading, the alternating background for service status column is lost...
![image](https://cloud.githubusercontent.com/assets/72965/20670733/9908c918-b57a-11e6-9cf5-ea6f167d1f21.png)

After the upgrade completes, it gets ok again.

**Comment by vincent99** [comment]
This is actually a browser rendering bug caused by using GPU acceleration for the spinner, but is worked around already in 1.2.
