### ISSUE TITLE
Service name and "as name" should be valid DNS label

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#680]
v0.18.2
Steps:
1.  Go to Services page
2.  Click on Add Environment
3.  Enter éee as Name

Results:
Validation failed: name

Expected:
Should be able to use extended/international character in name?

**Comment by vincent99** [comment]
No, service names become DNS labels so the name is heavily restricted to what DNS allows.  The rules are (or probably aren't, but should be):
  - 1-63 characters long
  - Consisting only of A-Z, 0-9, and hyphen
  - Can't start of end with a hyphen
  - Can't contain 2 consecutive hyphens

**Comment by tfiduccia** [comment]
v0.20.1
Failed
Currently Name can have two consecutives hypens and be longer than 63 characters.

**Comment by vincent99** [comment]
@alena1108 can you add these validations to the API schema (length) / validation (hyphens)?

**Comment by vincent99** [comment]
Apparently underscore is common enough that it works in host files and DNS libraries even though it's not technically allowed by RFC.. So we can take that too, especially because docker names things `sad_einstein`...

**Comment by alena1108** [comment]
Similar to https://github.com/rancherio/rancher/issues/1315

**Comment by deniseschannon** [comment]
Whenever the validation is added for service name, please also make sure to take in account the "as name" part of a service. Going to close the other issue to consolidate the issues. 

https://github.com/rancher/rancher/issues/1174

**Comment by sangeethah** [comment]
Tested with latest build from master:

All the below rules are applied for service_name and service link names:
1-63 characters long
Consisting only of A-Z, 0-9, and hyphen
Can't start of end with a hyphen
Can't contain 2 consecutive hyphens

When I have a service name with length 63 , containers of this service will have names > 63 and I am not able to ping them.

In oder fro this to not happen , may be we should  add a check that serviceName.length+containerName.length + 2 underscores + 3 or 4 or 5 digits for scale or so <= 63.

**Comment by prachidamle** [comment]
@vincent99 @ibuildthecloud Is this check enough?
serviceName.length+containerName.length + 2 underscores + 3 or 4 or 5 digits for scale or so <= 63.

Can there be any more parts to the containerName? example  @sangeethah mentions rancher_internal

**Comment by sangeethah** [comment]
@prachidamle , there is also sidekick services which need to be treated as special case. In this case , containers of sidekick are named with the format <stackname>_<primary service name>_<sidekick servicename>_<nn>

**Comment by janeczku** [comment]
Same issue with stack names: https://github.com/rancher/rancher/issues/5044
