### ISSUE TITLE
kubectl 1.4.x not able to talk to Rancher Server v1.2.0-rc1

### ISSUE THREAD

**Issue by nrvale0** [rancher/rancher#6800]
**Rancher Version:**
v1.2.0-rc1

**Docker Version:**
1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04 on AWS (Server: m4.large, Agents: t2.medium)

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
* Single-node Rancher Server layer
* 3 Rancher Agents
* local auth configured
* kubectl config generated via Rancher console

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
k8s

**Steps to Reproduce:**
Install kubectl version 1.4.6 (latest release at this time)

**Results:** 
```
$ kubectl get pod
Unable to connect to the server: http: server gave HTTP response to HTTPS client
```

**Expected:**
Accurate list of pods. 

@deniseschannon

**Comment by nrvale0** [comment]
@soumyalj

**Comment by deniseschannon** [comment]
Test with v1.2.0-rc2

**Comment by deniseschannon** [comment]
Verified with v1.2.0-rc2
