### ISSUE TITLE
Lots of volumestoragepoolmap.remove process timing out when hosts are in "Disconnected" state.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6808]
Rancher Version: v1.2.0-rc1

Steps to reproduce the problem:
Deploy a global health check enabled services.
Deploy a global services with no health check enabled.
power down one of the hosts.
Wait for the host to go from Active->Reconnecting->Disconnected.
global service instance with no health check enabled is stuck in "starting" state forever.

I see lot of volumestoragepoolmap.remove process timing out

<img width="1234" alt="screen shot 2016-11-28 at 10 21 33 pm" src="https://cloud.githubusercontent.com/assets/4266958/20698933/392e13c4-b5b9-11e6-9f25-dc6aac6ba5ff.png">

**Comment by cjellick** [comment]
This is expected and not a bug. There are some process/events that go to the host to complete. If the host is disconnected, theyll timeout. Bringing back or completely removing the host should cause them to go away.

**Comment by pulberg** [comment]
I am experiencing a similar issue even though my hosts are active, and have not been off/bounced/disconnected - 

Fresh install v1.2.1-rc2 - 

![screen shot 2016-12-14 at 4 07 49 pm](https://cloud.githubusercontent.com/assets/11069351/21203320/922a3362-c217-11e6-923f-545bb0ab4fa8.png)

`mysql> select data,process_name,resource_type,result,exit_reason,running_process_server_id from process_instance where exit_reason like '%unknown%' order by execution_count desc limit 50;
+------------------------------------------------------------------+-----------------------------+----------------------+--------+-------------------+---------------------------+
| data                                                             | process_name                | resource_type        | result | exit_reason       | running_process_server_id |
+------------------------------------------------------------------+-----------------------------+----------------------+--------+-------------------+---------------------------+
| {"reconcileState":true,"instance.stop::chain":"instance.remove"} | volumestoragepoolmap.remove | volumeStoragePoolMap | NULL   | UNKNOWN_EXCEPTION | NULL                      |
| {}                                                               | volumestoragepoolmap.remove | volumeStoragePoolMap | NULL   | UNKNOWN_EXCEPTION | NULL                      |
| {"reconcileState":true,"instance.stop::chain":"instance.remove"} | volumestoragepoolmap.remove | volumeStoragePoolMap | NULL   | UNKNOWN_EXCEPTION | NULL                      |
| {}                                                               | volumestoragepoolmap.remove | volumeStoragePoolMap | NULL   | UNKNOWN_EXCEPTION | NULL                      |
| {"reconcileState":true,"instance.stop::chain":"instance.remove"} | volumestoragepoolmap.remove | volumeStoragePoolMap | NULL   | UNKNOWN_EXCEPTION | NULL                      |`

**Comment by sangeethah** [comment]
Tested with v1.3.0-rc1
Once the host that is "Disconnected" state is powered on , and the host gets to "Active" state there are no more  active volumestoragepoolmap.remove process .
