### ISSUE TITLE
Manually refreshing catalog doesn't pull updated compose files

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#6809]
**Rancher Version:**
v1.2.0-rc1

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
1. Using the library (which is a git mirror)
2. Refresh catalog to see your templates
3. Add a `maximum_rancher_version` to one of the existing entries so that it should be hidden as an entry. 
4. Manually refresh the catalog.

**Results:** 
The template with the max version stays. 

**Expected:**
The template with the max version to be hidden. 

Note: eventually this template will refresh and correctly hide the template, but I would have expected it to be immediate if I click on the refresh button in the catalog page.

When I'm "refreshing", I'm clicking on this in the UI:

<img width="96" alt="screen shot 2016-11-28 at 11 14 01 pm" src="https://cloud.githubusercontent.com/assets/11410997/20700146/7176c616-b5c0-11e6-8d00-6c75a36af2df.png">

**Comment by cloudnautique** [comment]
It should be noted that there might be some delay between the primary and the mirrors. Up to 5 minutes.

**Comment by mrajashree** [comment]
@deniseschannon can I close this?

**Comment by LLParse** [comment]
We installed git webhooks for rancher-catalog and community-catalog, so the delay should be only a few seconds, assuming GH is sending us realtime events.

If events stop for whatever reason, the delay will be up to 5 minutes.

**Comment by deniseschannon** [comment]
As only Rancher employees will face this issue due to impatience, I'll close this. :)

Note: when using your own private catalog, manually refreshing updates immediately.
