### ISSUE TITLE
Error message should show allowable characters for Name

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#681]
v0.18.2
Steps:
1.  Create an Environment or Service  with an extended character in it

Results:
Validation failed: name

Expected:
Name field only allows characters A-Z, a-z and - (or whatever our standard is for this type of message)

**Comment by vincent99** [comment]
![image](https://cloud.githubusercontent.com/assets/753917/13715603/12389392-e793-11e5-898a-e1998af73e5f.png)

![image](https://cloud.githubusercontent.com/assets/753917/13715605/1aa44fda-e793-11e5-8710-1bae009527d5.png)

**Comment by tfiduccia** [comment]
Version - master 3/15
Verified fixed
