### ISSUE TITLE
Multiply loading a docker-compose file into a stack

### ISSUE THREAD

**Issue by Toonix** [rancher/rancher#6810]
Rancher Version: 1.2.0-rc1

Docker Version:1.12.3

RancherOS 0.7.1

Multiply loading a compose file dosn't work. 

1. Create a Stack.
2. Name the Stack
3. Load from File
4. Delete the content in the text fiel. (Docker-Compose-File)
5. Load from file (doesn't work anymore)

Environment Type: (Cattle)

**Comment by deniseschannon** [comment]
I am unable to reproduce this. 

I assume you are talking about this screen. I was able to load a file and delete the content and then upload again. Are you sure you had deleted all the white space? I noticed that if i have a space in the file, it doesn't re-upload. 

<img width="859" alt="screen shot 2016-11-29 at 10 31 27 am" src="https://cloud.githubusercontent.com/assets/11410997/20723350/01c50314-b61f-11e6-9a65-db30fbfa38f9.png">

We could improve to allow uploads if there are only white spaces in the text box.

**Comment by vincent99** [comment]
The critical bit is you have to pick **the same file** (or at least a different file with the same filename).  Nothing happens because the value of the form input is the filename.  The new value is the same as the old one so it "didn't change" and no event is triggered to re-read it.

**Comment by deniseschannon** [comment]
Trying to pick the same file name didn't work in v1.2.0-rc2

**Comment by deniseschannon** [comment]
Verified that I was able to select the same file in v1.2.0-rc3
