### ISSUE TITLE
unable to create new cattle env

### ISSUE THREAD

**Issue by lkoenigsberger** [rancher/rancher#6811]
**Rancher Version:**
v1.2.0-rc1

**Docker Version:**
1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
RancherOS v0.7.1 (4.4.24), bare metal

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher, internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
create a new rancher server from scratch and add one host.

**Results:** 
rancher-network manager is showing the following error:
```
29.11.2016 09:43:41Creating metadata client: Get http://rancher-metadata/2016-07-29/version: dial tcp 169.254.169.250:80: getsockopt: no route to host
29.11.2016 09:43:43time="2016-11-29T08:43:43Z" level=info msg="Waiting for metadata"
```

**Expected:**
running cattle env

**Comment by lkoenigsberger** [comment]
Hi here is the command I used:
```
docker run -d --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.1.0-rc16 https://domain.yy/v1/scripts/6DED3B21CC189B644F40:148044...4TAvoE37GPKA3POjjNo
```
and no, the rancher/server is running on an other host.

**Comment by leodotcloud** [comment]
@lkoenigsberger could you please collect the logs for the following containers on your host:

2 containers running the image: rancher/net
1 container running the image: rancher/metadata
1 container running the image: rancher/plugin-manager
1 container running the image: rancher/dns
1 container(in Up state) running the image: rancher/agent

docker logs <container_id> > somefile.log 2>&1

**Comment by leodotcloud** [comment]
@lkoenigsberger if you prefer, you can email me the zipped logs file.

**Comment by lkoenigsberger** [comment]
Hi @leodotcloud,

here you go
[logs.tar.gz](https://github.com/rancher/rancher/files/620014/logs.tar.gz)

**Comment by ibuildthecloud** [comment]
@lkoenigsberger Can you run `ip route` on the host and share the output?  I'm looking for a route that has `169.254.169.250/32` in it.  Are you by chance using a system where the docker bridge is not `docker0`?  We need the bridge to be named `docker0` unfortunately.

**Comment by lkoenigsberger** [comment]
@ibuildthecloud here is the output for the rancher-server:
```
default via 10.8.70.200 dev eth0
10.8.70.200/31 dev eth0  proto kernel  scope link  src 10.8.70.201
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.0.1 linkdown
```
and here the one for the rancher-host which should be added:
```
default via xxx.xxx.xxx.xxx dev eth0  src xxx.xxx.xxx.xxx  metric 202
10.42.0.0/16 dev docker0  proto kernel  scope link  src 10.42.0.1
xxx.xxx.xxx.xxx/29 dev eth0  proto kernel  scope link  src xxx.xxx.xxx.xxx  metric 202
169.254.169.250 dev docker0  scope link
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.0.1
172.18.0.0/16 dev docker_gwbridge  proto kernel  scope link  src 172.18.0.1
```

**Comment by lkoenigsberger** [comment]
fixed the error. deleted the link local route and restarted the server.
Was a testing server so with all the rc`s of 1.2 installed. Maybe that caused the issues.
