### ISSUE TITLE
No visibility of node count in 1.2.0 HA

### ISSUE THREAD

**Issue by chrisurwin** [rancher/rancher#6814]
**Rancher Version:**
v1.2.0-dev

In 1.1.4 HA you could see from the UI how many nodes were up and participating in the Rancher Server HA stack, due to the changes in HA in 1.2.0 there is now no way to know from the UI how many nodes there are in the HA cluster.

**Comment by cjellick** [comment]
And legitimate unhealthiness of things like go-machine-service, rancher-compose-executor is obfuscated.

**Comment by vincent99** [comment]
This is theoretically in but I haven't seen a working API accessible to a normal admin yet...

**Comment by tfiduccia** [comment]
Version -master 11/13 
Not fixed

**Comment by tfiduccia** [comment]
version - master 11/14
Verified fixed
