### ISSUE TITLE
Infrastructure stack services can't be pulled without internet

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#6816]
Trying to install Rancher on an environment without internet, and the images needed for the infrastructure stack (healthcheck/net/metadata/plugin-manager/scheduler) are pulled from the Hub because they are prefixed with `rancher/`. I setup Rancher by using the guide for `Launching Rancher Server with No Internet Access`.

Can this be configured some other way?

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.2.0-rc1` Cattle: `v0.174.0` UI: `v1.2.32` |
|Access|`Disabled`|
|Orchestration|`Cattle`|
|Route|`stacks.index`|

**Comment by deniseschannon** [comment]
The updated docs for 1.2 state that you also need to pull whatever infrastructure services you want to use.

http://docs.rancher.com/rancher/v1.2/en/installing-rancher/installing-server/no-internet-access/

```
It is very important that all images (e.g.. rancher/server, rancher/agent, and any infrastructure service images) are distributed before attempting to install/upgrade Rancher Server. If these versions are not available in your private registry, Rancher Server will become unstable.
```

**Comment by superseb** [comment]
Fair enough, but I do get these automatically when I set up Rancher and there is a possibility to configure the private registry in `rancher/server` and `rancher/agent`. Now I have to pre-pull the Rancher infrastructure images and re-tag them locally to make it work, because the infrastructure services are configured to origin from the Hub. Is this the way to deploy Rancher without internet? Would be nice to have a variable which can be configured to point to your local registry like with server/agent.

**Comment by stefanvangastel** [comment]
I was going to investigate this some further using my hypothesis as stated here: https://forums.rancher.com/t/available-env-config-params-for-no-internet-access-install/4606/5?u=stefanvangastel

Though I don't seem to be able to start a v1.1.4 server since v1.2 was released.

**Comment by kaos** [comment]
@deniseschannon The docs for 1.2 only states how to start the rancher server using a private registry, and adding hosts will use the private registry for the agent image. However, the infrastructure service images does NOT use the private registry, and I have not found any reference in the documentation as to how to go about getting rancher to pull them from a private registry.

It does look like this is supposed to work, based on the doc you referred to:
> ... and any infrastructure service images ...

as it wouldn't serve any point in doing so, unless they were going to be used.

So the big question is, what piece of information are we missing? 

Would really like being able to get our rancher deployments up to 1.2 ;)

**Comment by superseb** [comment]
Yep, hopefully we can make the registry configurable for infrastructure service images so that we can run it on-prem more easily. Till then you can preload the images and re-tag them so that you fake them coming from the Docker Hub.

**Comment by stefanvangastel** [comment]
@kaos @superseb @deniseschannon It seems this is the way: https://forums.rancher.com/t/rancher-kubernetes-in-an-offline-infratstructure/3917/3 though it is not documented yet. 

Already have 2 people saying it works using a cloned and modified version of the Rancher Certified Catalog and using Rancher Server env var to set it. 

Going to test it myself in the next few weeks.

**Comment by kaos** [comment]
thanks, yes, we were considering trying that. Thanks for the heads up that it's a viable work-around.

**Comment by deniseschannon** [comment]
We have actually introduced a concept of a `default registry`, but there is no availability in the UI. Through the API under `/v2-beta/settings`, we can set the `registry.default` setting. If `registry.default` is set, then all images that do not have any user specified registry (i.e `ubuntu:14.04`) will get the default registry prepended to them. Other images with user provided registries such as 'quay.io/account/image' will not change.

With this default registry setting, you can use the current default catalogs, and update your private registries to contain the required images for the infrastructure stacks. 

I've updated the docs with the same information. http://docs.rancher.com/rancher/v1.2/en/installing-rancher/installing-server/no-internet-access/#configuring-the-default-registry-for-infrastructure-stacks

@sangeethah Can you test that using the default registry setting, we would be able to pull/launch infrastructure stacks?

**Comment by kaos** [comment]
@deniseschannon Thanks, that was the missing piece of information 😄  I knew there was supposed to exist something like that ;)

**Comment by soumyalj** [comment]
Tested with 1.3.0-rc3. Created a private registry localhost:5000. Started a rancher server using the below command. 
```
sudo docker run -d --restart=unless-stopped -p 8080:8080 -e CATTLE_BOOTSTRAP_REQUIRED_IMAGE=localhost:5000/<NAME_OF_LOCAL_RANCHER_AGENT_IMAGE>:v1.1.3  localhost:5000/<NAME_OF_LOCAL_RANCHER_SERVER_IMAGE>:v1.3.0-rc3
```
Set the default registry to ``` localhost:5000``` 
Created a new environment . On the host, pushed all the infrastructure images to the localhost registry and added the custom host to the new environment:
```
sudo docker run -d --privileged -v /var/run/docker.sock:/var/run/docker.sock localhost:5000/<NAME_OF_LOCAL_RANCHER_AGENT_IMAGE>:v1.1.3 http://<SERVER_IP>:8080/v1/scripts/<security_credentials>
```
