### ISSUE TITLE
[cli] v2-beta endpoint issue

### ISSUE THREAD

**Issue by ununseptium** [rancher/rancher#6823]
I downloaded the `rancher-v0.3.1` darwin binary and tried to connect to the rancher server like this:
```
$ ./rancher --url http://{IP}:8080 config
URL [http://{IP}:8080]:
Access Key []: {KEY}
Secret Key []: {SECRET}
FATA[0021] Failed to find schema at [http://{IP}:8080/v2-beta]
```

Version Info:
```
Rancher: v1.1.4
Cattle: v0.165.8.4
User Interface: v1.1.14
Rancher Compose: v0.8.6
```
I guess that's enough information since the v2-beta doesn't exist in this version of rancher.

**Comment by deniseschannon** [comment]
As of CLI v0.2.0, we only support v1.2.0-pre3+.

https://github.com/rancher/cli/releases/tag/v0.2.0

**Comment by ununseptium** [comment]
A little note somewhere on the rancher/cli readme would be nice i guess?

**Comment by benfavre** [comment]
I'm glad google is a thing.
A notice would be good indeed ;)
Works now I updated, all good
