### ISSUE TITLE
HA Upgrade: healthcheck and ipsec containers are timing out on one of the hosts

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#6831]
**Rancher Version:**
1.1.4 --> v1.2.0-rc1
**Docker Version:**
1.12
**OS and where are the hosts located? (cloud, bare metal, etc):**
RancherOS 0.7.1
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
- Setup HA on rancher 1.1.4
- deploy catalog where port 80 is exposed
- register two hosts on the setup
- Upgrade the setup to v1.2.0-rc1

**Results:** 
network-manager is throwing the following error:
```
nsenter: cannot open /proc/16377/ns/ipc: No such file or directory
11/30/2016 3:02:12 AMtime="2016-11-30T01:02:12Z" level=error msg="Failed to evaluate networking: Bringing up networking: netplugin failed but error parsing its diagnostic message \"\": unexpected end of JSON input"
11/30/2016 3:02:14 AMtime="2016-11-30T01:02:14Z" level=error msg="Error reading metadata version: invalid character '<' looking for beginning of value"
11/30/2016 3:02:14 AMtime="2016-11-30T01:02:14Z" level=error msg="Error reading metadata version: invalid character '<' looking for beginning of value"
11/30/2016 3:02:14 AMtime="2016-11-30T01:02:14Z" level=info msg="Evaluating state from retry" cid=e327f336bbf67a2aae65d818522feb650fdbddbcfb6fb72649589df041b3777a
```
and healthcheck and ipsec are timing out to find ip address.

**Comment by deniseschannon** [comment]
Can you re-test with plugin manager v0.2.12 (which will be in v1.2.0-rc2)?

**Comment by galal-hussein** [comment]
I tested the on v1.2.0-rc2, the system containers were up and running.
