### ISSUE TITLE
./rancher catalog ls fails in the new version

### ISSUE THREAD

**Issue by ignacio-ibanez** [rancher/rancher#6834]
**Rancher Version:** v1.2.0-rc2
**Rancher CLI Version:** v0.3.1

**Steps to Reproduce:**
      1-Create a rancher cli setup
      2-Run the command ./rancher catalog ls

**Results:** 
    Command introduced: ./rancher catalog ls

    
    NAME      CATEGORY   ID
    FATA[0001] Invalid URL http://185.21.3.170:8080/v2-beta/schemas, must contain /v1

**Comment by tfiduccia** [comment]
This is a known issue and duplicate.  Closing in favor of #6367
