### ISSUE TITLE
let rancher-agent deploy cAdvisor instead of baking this in

### ISSUE THREAD

**Issue by flypenguin** [rancher/rancher#6835]
**Summary**
It seems you have a cAdvisor instance running inside a rancher-agent container. I *also* run a cAdvisor instance for my prometheus-based monitoring. This is not optimal because ...

* cAdvisor takes a lot of CPU sometimes
* now I run two of them, because I can't access your one.

It would be super helpful if you would just use rancher-agent to deploy a cAdvisor instance next to the rancher-agent, so other monitoring systems could use the same information.

**Rancher Version:**
<1.2

**Docker Version:**
1.11.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
EC2

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node Rancher setup, external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Deploy simple Rancher setup

**Results:** 
rancher-agent is running, using an internal cAdvisor instance which cannot be reached from "outside"

**Expected:**
use rancher-agent to externally deploy a cAdvisor instance which is usable from everybody

**Comment by vincent99** [comment]
We don't use (or deploy) cAdvisor as of 1.2, so you can continue deploying your own if you still want it.
