### ISSUE TITLE
[rancher-catalog] Errors starting new Server

### ISSUE THREAD

**Issue by CallMeRoot** [rancher/rancher#6837]
**Rancher Version:** latest/stable (v1.1.4)

**OS and where are the hosts located? (cloud, bare metal, etc):** RancherOS (0.7.1)

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** Google Compute Engine

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** none

**Steps to Reproduce:** starting new server with default settings and port binding 8080:8080

**Results:** web-panel not starting and errors in log

`time="2016-11-30T12:39:00Z" level=error msg="Error unmarshalling config.yml under template: DATA/library/infra-templates/ebs, error: yaml: unmarshal errors:\n  line 7: cannot unmarshal !!map into string"
time="2016-11-30T12:39:00Z" level=error msg="Error unmarshalling config.yml under template: DATA/library/infra-templates/efs, error: yaml: unmarshal errors:\n  line 7: cannot unmarshal !!map into string"
time="2016-11-30T12:39:00Z" level=error msg="Error unmarshalling config.yml under template: DATA/library/infra-templates/healthcheck, error: yaml: unmarshal errors:\n  line 7: cannot unmarshal !!map into string"
time="2016-11-30T12:39:00Z" level=error msg="Error unmarshalling config.yml under template: DATA/library/infra-templates/ipsec, error: yaml: unmarshal errors:\n  line 5: cannot unmarshal !!map into string"
time="2016-11-30T12:39:00Z" level=error msg="Error unmarshalling config.yml under template: DATA/library/infra-templates/k8s, error: yaml: unmarshal errors:\n  line 5: cannot unmarshal !!map into string"
time="2016-11-30T12:39:00Z" level=error msg="Error unmarshalling config.yml under template: DATA/library/infra-templates/network-services, error: yaml: unmarshal errors:\n  line 5: cannot unmarshal !!map into string"
time="2016-11-30T12:39:00Z" level=error msg="Error unmarshalling config.yml under template: DATA/library/infra-templates/nfs, error: yaml: unmarshal errors:\n  line 7: cannot unmarshal !!map into string"
time="2016-11-30T12:39:00Z" level=error msg="Error unmarshalling config.yml under template: DATA/library/infra-templates/route53, error: yaml: unmarshal errors:\n  line 7: cannot unmarshal !!map into string"
time="2016-11-30T12:39:00Z" level=error msg="Error unmarshalling config.yml under template: DATA/library/infra-templates/scheduler, error: yaml: unmarshal errors:\n  line 7: cannot unmarshal !!map into string"
time="2016-11-30T12:39:00Z" level=error msg="Error unmarshalling config.yml under template: DATA/library/infra-templates/vxlan, error: yaml: unmarshal errors:\n  line 7: cannot unmarshal !!map into string"`

**Comment by danielschlegel** [comment]
same here.

**Comment by biolounge** [comment]
I am also getting the same error.

**Comment by vincent99** [comment]
These are from the catalog service in v1.1 not knowing how to parse some of the newer options that are used for catalog items for v1.2.  The errors are harmless, but if you want to not see them you can change the catalog config to point to a copy we've made that doesn't include the problematic templates:

Disable "Rancher Certified", and add a "Custom" for `library` = `https://github.com/rancher/rancher-catalog-v1.1.git`

![image](https://cloud.githubusercontent.com/assets/753917/20762908/42747b12-b6e5-11e6-8763-e460eba915ba.png)

**Comment by deniseschannon** [comment]
Note If you update your catalog to this other catalog, you will need to revert to the exisiting rancher-catalog, prior to upgrading to v1.2.0.
