### ISSUE TITLE
[cattle] healthcheck and scheduler Not Activating

### ISSUE THREAD

**Issue by ThatsNinja** [rancher/rancher#6839]
**Rancher Version:**
v1.2.0-rc1

**Docker Version:**
1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
Boot2Docker 1.12.3 - HEAD: 7fc7575

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
- Standalone Rancher Server
- External Database (Galera Cluster)
- Cattle hosts configured via vmwarevsphere Machine Driver

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
1. Start Rancher Server in stand-alone mode;
2. Create three hosts via vmwarevsphere Machine Driver, and;
3. Observe that `scheduler` and `healthcheck` Infrastructure Stacks stay stuck in 'Activating' state.

**Results:** 
The `scheduler-scheduler-1` container and `healthcheck-healthcheck-[1, 2]` containers end up being shuffled from host to host, getting as far as 'Networking' and failing:

```
{
  [...]
  "transitioning": "error",
  "transitioningMessage": "Timeout getting IP address",
  "transitioningProgress": 64
  [...]
}
```

I'm still in process of troubleshooting from my end, and will continue to update this ticket as my understanding of what's happening behind the scenes improves. Still, figured I'd open early in case @rancher peeps are aware of this and can easily point out how I'm being an idiot.

**Expected:**
Uncertain precisely what to expect as this is our first experience trying to do anything useful with this new version. That said, I'd say I might reasonably expect the `scheduler` and `healthcheck` stacks to go green.

**Comment by ThatsNinja** [comment]
Meanwhile, the `ipsec` stack is now struggling as well. It started initially, but seems to have fallen over while my back was turned.

The `ipsec-ipsec-cni-driver` sidekick starts fine, but the `ipsec-ipsec` containers are now stuck in 'Starting'. When I de-activated the service a moment ago, the 'Starting' containers failed with the same 'Timeout getting IP address' error as above.

**Comment by ThatsNinja** [comment]
The `network-services-network-manager` instances are reporting some interesting stuff:

```
time="2016-11-30T15:36:16Z" level=error msg="Failed to evaluate networking: Bringing up networking: netplugin failed but error parsing its diagnostic message \"\": unexpected end of JSON input"
11/30/2016 9:36:18 AMtime="2016-11-30T15:36:18Z" level=info msg="Evaluating state from retry" cid=d5c906bf558eec1d0f42a0842c85a80bca5637c3d19ba63dd6b51cca8e5b8233
11/30/2016 9:36:18 AMtime="2016-11-30T15:36:18Z" level=info msg="CNI up" cid=d5c906bf558eec1d0f42a0842c85a80bca5637c3d19ba63dd6b51cca8e5b8233 networkMode=ipsec
11/30/2016 9:36:18 AMnsenter: cannot open /proc/26954/ns/ipc: No such file or directory
```

... as well as these guys...

```
11/30/2016 9:38:48 AMtime="2016-11-30T15:38:48Z" level=error msg="Failed to evaluate networking: Bringing up networking: Get http://rancher-metadata/2015-12-19/version: dial tcp: lookup rancher-metadata on <our_external_dns_server>:53: no such host"
11/30/2016 9:38:50 AMtime="2016-11-30T15:38:50Z" level=info msg="Evaluating state from retry" cid=dd7ec6b9d37ab907cd76836cbe5c6267da502f32ba5a8512caadc959bb226103
```

**Comment by deniseschannon** [comment]
Could you try with rc2? 

I am not sure if rc1 is working with the most recent plugin-manager that is known to be working with rc2.

**Comment by ThatsNinja** [comment]
Hi, @deniseschannon. Thanks for getting back so quickly.

So, I spun down v1.2.0-rc1, left it in place, and spun up v1.2.0-rc2 connecting to the same backend database. No change in the stacks being unable to start, but I'm now seeing this in the service status just before the 'Timeout getting IP address' is thrown:

```
Failed to acquire lock [SERVICE.54]
```

The numeric designator changes from one occurrence to the next (e.g. `SERVICE.62`, etc.), but I'm seeing the 'Failed to acquire lock' consistently.

**Comment by deniseschannon** [comment]
@ThatsNinja It might take a bit to resolve if you're using the same DB. Usually having 2 rancher servers pointing to the same DB is not good cause if anything happens they might stomp on each other. 

Any chance you can do a fresh install on a fresh DB :) I know that's a lot to ask but I appreciate you testing out our RCs!

**Comment by ThatsNinja** [comment]
No problem, @deniseschannon. We depend on Rancher every day, and we're very excited about any number of features and improvements in v1.2.0. Testing release candidates is a matter of our due diligence, and thoroughly reporting our progress is about the least we can do for @rancher and the community.

Just so there's no confusion: I stopped the v1.2.0-rc1 instance and spun up v1.2.0-rc2 in its place, so  there was only ever one server instance using this database at any given time.

Now, I killed the stand-alone v1.2.0-rc2 server referenced in my last comment, dropped all the database tables, and spun up a new instance of v1.2.0-rc2. The database created from scratch, no problem.

Next, I used the vmwarevsphere Machine Driver to create three brand new Cattle hosts. Following along in the logs on the Server instance, I saw this while the last of the three hosts was provisioning:

```
time="2016-11-30T20:06:56Z" level=info msg="Registering backend for host 70201b5e-039a-4327-8ab9-75b6423f2e1e with session ID 95366fa9-d336-4aa4-8d7b-9d90c027b8d3."
2016-11-30 20:06:57,630 ERROR [:] [] [] [] [ecutorService-3] [o.a.c.m.context.NoExceptionRunnable ] Uncaught exception org.jooq.exception.DataChangedException: Database record has been changed
	at org.jooq.impl.UpdatableRecordImpl.checkIfChanged(UpdatableRecordImpl.java:550) ~[jooq-3.3.0.jar:na]
	at org.jooq.impl.UpdatableRecordImpl.storeUpdate0(UpdatableRecordImpl.java:291) ~[jooq-3.3.0.jar:na]
	at org.jooq.impl.UpdatableRecordImpl.access$200(UpdatableRecordImpl.java:90) ~[jooq-3.3.0.jar:na]
	at org.jooq.impl.UpdatableRecordImpl$3.operate(UpdatableRecordImpl.java:260) ~[jooq-3.3.0.jar:na]
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:123) ~[jooq-3.3.0.jar:na]
	at org.jooq.impl.UpdatableRecordImpl.storeUpdate(UpdatableRecordImpl.java:255) ~[jooq-3.3.0.jar:na]
	at org.jooq.impl.UpdatableRecordImpl.update(UpdatableRecordImpl.java:149) ~[jooq-3.3.0.jar:na]
	at io.cattle.platform.servicediscovery.dao.impl.ServiceExposeMapDaoImpl.createServiceInstance(ServiceExposeMapDaoImpl.java:66) ~[cattle-iaas-service-discovery-server-0.5.0-SNAPSHOT.jar:na]
```

Here's a sample of the log output server-side while the Infrastructure stacks are sloshing around:

```
2016-11-30 20:32:20,422 ERROR [acc8e27a-4bd8-4447-a3e6-af3e56d253d4:7305] [instance:306->instanceHostMap:303] [instance.start->(InstanceStart)->instancehostmap.activate] [] [ecutorService-9] [c.p.e.p.i.DefaultProcessInstanceImpl] Agent error for [compute.instance.activate.reply;agent=3]: Timeout getting IP address
2016-11-30 20:32:20,422 ERROR [acc8e27a-4bd8-4447-a3e6-af3e56d253d4:7305] [instance:306] [instance.start->(InstanceStart)] [] [ecutorService-9] [i.c.p.process.instance.InstanceStart] Failed [1/2] to Starting for instance [306]
2016-11-30 20:32:20,550 ERROR [acc8e27a-4bd8-4447-a3e6-af3e56d253d4:7305] [instance:306->instanceHostMap:303] [instance.start->(InstanceStart)->instancehostmap.activate] [] [ecutorService-9] [c.p.e.p.i.DefaultProcessInstanceImpl] Agent error for [compute.instance.activate.reply;agent=3]: Timeout getting IP address
2016-11-30 20:32:20,551 ERROR [acc8e27a-4bd8-4447-a3e6-af3e56d253d4:7305] [instance:306] [instance.start->(InstanceStart)] [] [ecutorService-9] [i.c.p.process.instance.InstanceStart] Failed [2/2] to Starting for instance [306]
2016-11-30 20:32:22,526 ERROR [78afa3c0-227c-48bf-a948-c9168c4ecd49:447] [service:9] [service.activate] [] [ecutorService-3] [c.p.e.p.i.DefaultProcessInstanceImpl] Expected state running but got error: Timeout getting IP address
2016-11-30 20:32:22,603 ERROR [:] [] [] [] [ecutorService-3] [.e.s.i.ProcessInstanceDispatcherImpl] Expected state running but got error: Timeout getting IP address
```

It may be worth noting that these Cattle hosts are being created in an environment that's already battle-tested with Rancher. We've been operating previous Rancher versions for almost a year in this very same network.

**Comment by deviousgeek** [comment]
Having the same problem! Keen to help out with any info if needed. :)

**Comment by deniseschannon** [comment]
@ThatsNinja @deviousgeek Eventually your infrastructure services should come up. It might just take some time. 

The DB record change exception is a known issue. It's harmless.

**Comment by deviousgeek** [comment]
A few hours pass and nothing yet, just threw up a 1.2.0 (stable release) stack too see if things change. 

This is with k8s, remote agent.

**Comment by ThatsNinja** [comment]
@deniseschannon Sixteen hours here with no love. Default Infrastructure stacks are still not activating, still throwing the same errors as above.

No point continuing to do this with a pre- version, so I'll spin up v1.2.0 on a fresh database, and we can see if I've still got these issues.

**Comment by ThatsNinja** [comment]
So, I flipped over to discard that server instance (which, thankfully, had been running the entire time, tailing logs in a recorded shell session), and I was **definitely** having database issues, starting here:

```
2016-12-01 10:14:51,048 ERROR [:] [] [] [] [p1830712962-955] [i.g.i.g.r.handler.ExceptionHandler  ] Exception in API for request [http://192.168.92.180:8080/v2-beta/publish]. Error id: [13a112dc-d0c6-4c7b-994b-96dbb9227da1]. org.jooq.exception.DataAccessException: SQL [select `credential`.`id`, `credential`.`name`, `credential`.`account_id`, `credential`.`kind`, `credential`.`uuid`, `credential`.`description`, `credential`.`state`, `credential`.`created`, `credential`.`removed`, `credential`.`remove_time`, `credential`.`data`, `credential`.`public_value`, `credential`.`secret_value`, `credential`.`registry_id` from `credential` where (`credential`.`state` = ? and `credential`.`public_value` = ? and `credential`.`kind` in (?, ?, ?))]; Too many connections
```

... and proceeding to a whole series of these:

```
2016-12-01 10:15:17,235 ERROR [438f9b5b-7ed9-40c3-bbf5-aecb660a0640:366114] [instance:12951] [instance.stop] [] [cutorService-10] [c.p.e.p.i.DefaultProcessInstanceImpl] Unknown exception org.jooq.exception.DataAccessException: SQL [update `config_item_status` set `config_item_status`.`requested_version` = (`config_item_status`.`requested_version` + ?), `config_item_status`.`requested_updated` = ? where (`config_item_status`.`name` = ? and `config_item_status`.`resource_type` = ? and `config_item_status`.`resource_id` = ?)]; Got error 35 "Resource deadlock avoided" during COMMIT
```

... and finally dying thus:

```
2016-12-01 10:24:48,394 ERROR   [pool-3-thread-1] [ConsoleStatus] Check-in failed org.jooq.exception.DataAccessException: SQL [update `cluster_membership` set `cluster_membership`.`heartbeat` = ? where `cluster_membership`.`uuid` = ?]; Could not connect to external-db:3306: unexpected end of stream, read 0 bytes from 4
[ . . . ]
FATAL: Exiting due to failed cluster check-in
time="2016-12-01T10:24:48Z" level=info msg="Exiting rancher-compose-executor" version=v0.11.0
time="2016-12-01T10:24:48Z" level=info msg="Exiting go-machine-service"
```

The server container restarted at that time.

In the end, it ran for fifteen hours and disintegrated completely over the course of ten minutes when it overran the database's connection limit and the Galera cluster started refusing its connections.

So, I'm going to do a few things at once here... This actually killed one node of our database cluster, and we're picking through the rubble to piece together what was happening from that perspective best we can. Also, I'm going to stand up a v1.2.0 stand-alone server against this Galera cluster, and stand one up that's fully self-contained, with the internal DB server.

**Comment by cjellick** [comment]
You've had an evolution of problems here, so I want to make sure we aren't conflating some of your earlier issues with your present ones. So, to clarify, In your last attempt with v1.2.0 (no pre, no RC):
1. Which infrastructure containers were coming up and which ones were failing?
2. Was this a from-scratch environment where you just added three new, empty hosts?
3. Do the hosts have unrestricted network access between them? Meaning no port restrictions.

**Comment by lucacri** [comment]
Having this same issue in 1.2.0. It baffles me that you had a breaking issue open and unresolved, and yet decided to push the 1.2 as stable. Incredible.

**Comment by deniseschannon** [comment]
@ThatsNinja It sounds like you are hitting this: https://github.com/rancher/rancher/issues/6874

**Comment by deniseschannon** [comment]
Can you try the workaround in the issue and see if that solves your issue?

We'll be pushing out a fix in a new network manager tonight.

**Comment by ThatsNinja** [comment]
@cjellick Sorry for the confusion. I'll try to alleviate some of it.

# Executive Summary
In answer to your questions:

1. Only the `network-services` stack activates successfully and remains standing. The `ipsec` stack activates initially, and the gear-shaped idiot light for the stack remains in the green 'Activated' state, but the underlying `ipsec` service reverts to the 'Activating' state a couple minutes after starting, and never comes up. The `healthcheck` and `scheduler` stacks never complete activation.
2. Yes. Every one of my attempts was from scratch.
3. Again, yes. [As stated](https://github.com/rancher/rancher/issues/6839#issuecomment-263989254), this is a network segment in which we've successfully run multiple previous Rancher Agent versions for many months.

# Attempts to Date
I'll sum up my activities to this point, as well as the results.

**v1.2.0-rc1**
The original installation which occasioned my [opening this issue](https://github.com/rancher/rancher/issues/6839#issue-192595185); In short: Rancher Server stand-alone pointing at a Galera back end.

**v1.2.0-rc1 to v1.2.0-rc2 Upgrade**
Pursuant to discussions with @deniseschannon, I stopped the v1.2.0-rc1 container - leaving the back-end database in place, pulled rancher/server:v1.2.0-rc2, and spun up a container at v1.2.0-rc2 pointing at the v1.2.0-rc1 database ([see here](https://github.com/rancher/rancher/issues/6839#issuecomment-263975535)).

The outward [result](https://github.com/rancher/rancher/issues/6839#issuecomment-263975535) was unchanged.

**v1.2.0-rc2 Clean Install**
I destroyed the v1.2.0-rc2 instance from the upgrade and the three Cattle hosts I'd created, dropped all of the database tables, and spun up a fresh instance of v1.2.0-rc2 and let it generate a new database. I created three new Cattle hosts. No change. ([see here](https://github.com/rancher/rancher/issues/6839#issuecomment-263989254))

I left this server instance running overnight, and the Infrastructure stacks never stood up. [I came back](https://github.com/rancher/rancher/issues/6839#issuecomment-264167932) this morning, intent upon trying the full v1.2.0 release, and [discovered](https://github.com/rancher/rancher/issues/6839#issuecomment-264174413) that my Galera master had been hammered offline by Rancher during the night.

**v1.2.0 with Galera Back-end**
I stopped the v1.2.0-rc2 instance, we got the Galera cluster put back together, and I stood up an instance of GA v1.2.0. I provisioned three new Cattle hosts. There was no change in the behavior of the Infrastructure stacks after two hours, so I shut the Server instance down.

**v1.2.0 with Self-contained Database**
Next, considering that all of the previous instances had been using the Galera back-end, and further considering the issues I'd had with Galera, I elected to try a Server instance using the database internal to the container. I started the container, provisioned three new Cattle hosts, and observed no change in the behavior of the Infrastructure stacks.

# Additional Information, Perhaps of Note

- The Galera cluster in question is currently servicing a Rancher HA cluster, v1.1.4, with no problems.
- There are four perfectly well-behaved Cattle hosts in the network segment at issue. They're running v0.8.3 Agents provisioned against the above Rancher HA Server.
- For all of the attempts in this series I've used the vmwarevsphere Machine Driver to provision the Cattle hosts, and have provided the Boot2Docker 1.12.3 ISO from [this source](https://github.com/boot2docker/boot2docker/releases/download/v1.10.3/boot2docker.iso).

I've preserved the last three server instances, and can extract any logs you're interested in. I would welcome the chance to enact any suggestions you think might yield useful information or provide a solution. I'm understanding that your task is difficult and often enough thankless, so please let me know what I can do to be of assistance, and thank you in advance for your help!

**Comment by ThatsNinja** [comment]
@deniseschannon Your reply landed while I was slowly typing on my last. All due gratitude and respect, but you're a little quick on the 'Close issue' button :smile:

Of interest to anyone coming at this thread via the Googles, I've enacted the [referenced work-around](https://github.com/rancher/rancher/issues/6874), and it's resolved my issue!

**Comment by deniseschannon** [comment]
Whoops! I didn't mean to close it. :)

**Comment by deniseschannon** [comment]
Sorry @ThatsNinja!

**Comment by deniseschannon** [comment]
Ha! I just read the rest of what you wrote and realized that you did get it resolved. I'll let you close it. ;)
