### ISSUE TITLE
HA upgrade: inconsistencies when accessing the upgraded setup

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#6844]
**Rancher Version:**
v1.1.4 --> v1.2.0-rc2
**Docker Version:**
1.12.1
**OS and where are the hosts located? (cloud, bare metal, etc):**
ROS 0.7.1
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes, Cattle
**Steps to Reproduce:**
- Run HA setup on Rancher 1.1.4
- Create two environments (Cattle, Kubernetes)
- Register multiple hosts with each environment.
- Deploy several stacks on both environment from Rancher catalog.
- Set up Github authentication.
- Upgrade from 1.1.4 to v1.2.0-rc2

**Results:** 
After upgrading the environment, I couldn't see the kubernetes stack, instead its stuck in `Waiting for Kubernetes API` also the logs and shell of any containers are not working:

```
WebSocket connection to 'wss://xxxxx/v1/logs/?token=eyJhbGciOiJSUzI1NiJ9.eyJzdWIiO…XOQ7-o_CWF27IxitMlfbnID4MWYv1I-RMrPFi4iiuV1kEbNjYyuQQqztvpV4-BuzWMxbxh_xiw' failed: Error during WebSocket handshake: Unexpected response code: 404
```

**Comment by deniseschannon** [comment]
Can you retest with v1.2?

**Comment by galal-hussein** [comment]
@deniseschannon I retested with v1.2.0 and i can't see the problem anymore.
