### ISSUE TITLE
cross host networking broken when both vxlan and ipsec are enabled.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6851]
Rancher Version: v1.2.0-rc2

Steps to reproduce the problem:
Create an Environment with a cattle template that has both vxlan and ipsec enabled.
Add few hosts.
When Infrastructure stacks comes up, ipsec and vxlan infra stacks come up successfully but cross-host networking is broken. scheduler and healthcheck container are stuck in "Initializing" state forever.

**Comment by leodotcloud** [comment]
@sangeethah @deniseschannon this is not a supported scenario. Can we close this?
