### ISSUE TITLE
Cannot execute shell on CentOS 7.2

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#6861]
**Rancher Version:**
v1.2.0
**Docker Version:**
1.12.3
**OS and where are the hosts located? (cloud, bare metal, etc):**
CentOS 7.2, Digitalocean (but also on-prem)
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher, internal DB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
* Install Rancher by starting the `rancher/server` container, and join a `rancher/agent` container
* Wait for infrastructure stack to become active, Execute shell on the `scheduler` container

**Results:** 
Popup opens and closes immediately
**Expected:**
Popup with a running shell

**More info:**
Tried to debug this today. Haven't gotten the root cause but filing a ticket early. Tried to reproduce on Ubuntu 16.04, it's working fine there. This is what I get on the commandline:
```
[root@centos-02 ~]# docker ps | grep scheduler
a49f85151ae2        rancher/scheduler:v0.4.0                       "/.r/r scheduler"        14 minutes ago      Up 14 minutes                               r-scheduler-scheduler-1-5ed5a22e
[root@centos-02 ~]# docker exec -ti a49 bash
rpc error: code = 13 desc = invalid header field value "oci runtime error: exec failed: cannot exec a container that has run and stopped\n"
```
This was fixed in https://github.com/docker/docker/issues/27540 but still appears in this situation. As I dug a little deeper, I found out that only the containers with a Path of `/.r/r` seem to be affected. For a clean install this is:

```
22b7df37bf0c        rancher/healthcheck:v0.1.0                     "/.r/r /tini -- healt"   14 minutes ago      Up 14 minutes                           r-healthcheck-healthcheck-1-3ccae477
a49f85151ae2        rancher/scheduler:v0.4.0                       "/.r/r scheduler"        15 minutes ago      Up 15 minutes                           r-scheduler-scheduler-1-5ed5a22e
701043eecb1c        rancher/net:v0.7.5                             "/.r/r start.sh"         15 minutes ago      Up 13 minutes                           r-ipsec-ipsec-1-48f985f7
```

If you try to diagnose this the same way as in the Docker ticket, you get the same results. For instance for the scheduler:

```
[root@centos-02 ~]# docker ps | grep scheduler
a49f85151ae2        rancher/scheduler:v0.4.0                       "/.r/r scheduler"        17 minutes ago      Up 17 minutes                           r-scheduler-scheduler-1-5ed5a22e
[root@centos-02 ~]# ps -ef | grep a49f
root      3126  9121  0 19:40 pts/0    00:00:00 grep --color=auto a49f
root     11291  9280  0 19:23 ?        00:00:00 docker-containerd-shim a49f85151ae25475d1d77945f03e5e1862f1d964b1d5f03b02ea61b31af03628 /var/run/docker/libcontainerd/a49f85151ae25475d1d77945f03e5e1862f1d964b1d5f03b02ea61b31af03628 docker-runc
[root@centos-02 ~]# docker-runc state a49f85151ae25475d1d77945f03e5e1862f1d964b1d5f03b02ea61b31af03628
{
  "ociVersion": "1.0.0-rc2-dev",
  "id": "a49f85151ae25475d1d77945f03e5e1862f1d964b1d5f03b02ea61b31af03628",
  "pid": 0,
  "status": "stopped",
  "bundle": "/run/docker/libcontainerd/a49f85151ae25475d1d77945f03e5e1862f1d964b1d5f03b02ea61b31af03628",
  "rootfs": "/var/lib/docker/devicemapper/mnt/e506c366628e380183932d047e7d4b9e60af64d59e3ab977cf13576df7c1ae17/rootfs",
  "created": "2016-12-01T19:23:21.019392097Z"
}
```

Haven't had the time to go deeper, I need a way to reproduce on vanilla Docker to open a new issue there, maybe someone can help out.

**Comment by superseb** [comment]
Docker 1.12.2 also has this problem, Docker 1.12.1 is working fine.

**Comment by cjellick** [comment]
Thanks for the debugging @superseb. I don't have an answer, but we'll look into this.

**Comment by blackside** [comment]
Same issue and setup. 
Docker 1.2.3
Rancher 1.2.0
Hosts are CentOS 7

**Comment by sangeethah** [comment]
@superseb @blackside  This issue you are seeing is very similar to  https://github.com/rancher/rancher/issues/6756

**Comment by looztra** [comment]
same problem for me, in the same context (rancher v1.2.0, docker 1.12.3 on centos 7).

Besides, I have some containers with Path of `/.r/r` that can be accessed.

**Comment by stefanlasiewski** [comment]
Same problem here, also Rancher 1.2.0, Docker 1.12 and CentOS 7.2.

I can access some containers with a Path of /.r/r , but not some others. I also cannot access some generic containers, 

This Rancher Infrastructure container works:

```
[root@node4 ~]# docker ps |grep r/r |grep healthcheck
c76cd2e6f0f5        rancher/healthcheck:v0.1.0          "/.r/r /tini -- healt"   32 hours ago        Up 32 hours                                            r-healthcheck-healthcheck-1-ba5235ea
[root@node4 ~]# docker exec -it c76cd2e6f0f5 sh
# cat /etc/issue
Ubuntu 16.04.1 LTS \n \l
# exit
[root@node4 ~]#
```

This Rancher Infrastructure container cannot be accessed:

```
[root@node4 ~]## docker ps |grep r/r |grep ipsec
775e89a278e9        rancher/net:v0.7.5                  "/.r/r start.sh"         47 hours ago        Up 47 hours                                            r-ipsec-ipsec-1-ad10290e
[root@node4 ~]# docker exec -it 775e89a278e9 sh
rpc error: code = 13 desc = invalid header field value "oci runtime error: exec failed: cannot exec a container that has run and stopped\n"
[root@node4 ~]#
```

**Comment by superseb** [comment]
Ok quick update of something I just thought of checking out as it only happens on CentOS7. As it seems that there is some mismatch in /proc or in combination with runC lookups I wondered about kernel version. CentOS/RHEL always keep their base version the same, and backport kernel updates. So I updated the 3.10 kernel to the kernel-ml from elrepo which contains `4.8.12-1.el7.elrepo.x86_64`, rebooted and this fixed the problem. On containers I cannot exec into on 3.10 I can exec into on `4.8.12-1.el7.elrepo.x86_64`. I know this is not a real solution for production machines but it might help in debugging to find the root cause, as I just thought of this now.

**Comment by beatcracker** [comment]
I'm affected too:

- Rancher 1.2.2
- CentOS Linux release 7.2.1511 (Core)
- Docker version 1.12.5, build 7392c3

Could we please have an ETA on when this issue will be fixed? This makes my deployment unusable (need to peek inside containers a lot), so I'd like to know if this is not high-priority issue, so I can go with kernel update route (thanks, @superseb !).

Thanks in advance.

**Comment by deniseschannon** [comment]
@beatcracker Have you tried going on your host to attempt to exec into the container using the `docker exec` command? My understanding has been that it doesn't work with Docker, which is why Rancher is unable to exec into the container.

**Comment by beatcracker** [comment]
@deniseschannon Yep, looks like a docker issue - `exec` doesn't work. Sorry for bringing it up, guess it kernel update then. Thank you!

**Comment by deniseschannon** [comment]
As thi sis a docker issue, I'm going to close it. Anyone who can actually `docker exec` on the host and cannot do it in Rancher, please let me know and we can investigate.

**Comment by superseb** [comment]
@deniseschannon Just to get things clear I want to have another go at this. In my opinion the ```docker exec``` fails on a Rancher initiated container. I believe that your statement on ```docker exec``` on the host vs in Rancher is the same as ```docker exec``` vs a Rancher initiated container. The problem occurs on a Rancher initiated container, which happens through the agent and the a go package. It would be nice to get a reproducible case to create an issue in the Docker project? Or should this be a community initiative in your opinion?

**Comment by superseb** [comment]
For sake of completeness, I can successfully open shell with Rancher v1.2.2 on```CentOS Linux release 7.3.1611 (Core)``` with stock kernel ```3.10.0-514.2.2.el7.x86_64```.

**Comment by ecliptik** [comment]
@deniseschannon you asked if you could `docker exec` on the host but not in Rancher, and we're having that issue.

Rancher Version: 1.2.2
Rancher Host OS: Amazon Linux 2016.09
Docker Version: 1.11.2

I think this is related to how `docker exec` in the Rancher UI is calling a shell. Most of our containers are using `FROM alpine` and we do not install the `bash` package, so `/bin/sh` is the only available shell.

With Rancher 1.1.4 using the UI to exec into a container worked fine, but with 1.2 it immediately errors out. When I try to `docker exec` into the container from the host, I get:

```
[ec2-user@ip-10-9-2-201 ~]$ sudo docker exec -it 2030471e1d67 /bin/bash
rpc error: code = 2 desc = "oci runtime error: exec failed: exec: \"/bin/bash\": stat /bin/bash: no such file or directory"[ec2-user@ip-10-9-2-201 ~]$ sudo docker exec -it 2030471e1d67 /bin/sh
```

However, when I do `sudo docker exec -it 2030471e1d67 /bin/sh` it works.

Was there a change in 1.2 where `/bin/bash` is the default shell to exec into from the UI? I searched through the code base but didn't find anything.

If this is the case, and `/bin/bash` is default now, could we put in a feature request to make an option to change the default exec shell in the Admin section.

**Comment by tobowers** [comment]
just noting that I'm still having this problem with docker v1.13.0 and rancher 1.3.4 just running an ubuntu container. When I run an ubuntu container from the docker CLI, I can exec into. However, I cannot exec into the running container (using docker cli or rancher)

**Comment by deniseschannon** [comment]
@tobowers Can you create a new issue for this for your OS? Please note that the exec works in Docker CLI.

Also, Rancher currently doesn't support 1.13.0, but we can look into the issue for when we want to add in support for it.

**Comment by tobowers** [comment]
@deniseschannon the exec does *not* work in docker cli for the container started by rancher. It *does* work in docker cli for the same container created with docker cli.

**Comment by tobowers** [comment]
I'm in centos 7.2 as well

**Comment by deniseschannon** [comment]
@tobowers I misread ubuntu and thought it was your OS. :)

**Comment by superseb** [comment]
@tobowers You're having the exact same issue as described in this ticket right?

@ecliptik I would definitly create a new issue as this is a different error and sort of different OS (still derived) but this ticket describes the "oci runtime error: exec failed: cannot exec a container that has run and stopped\n". Agree @deniseschannon ?

**Comment by vincent99** [comment]
Yes, this issue is "Docker has decided this running container isn't and won't let you do exec regardless of the command".  That is a completely separate issue from "It tries to exec but bash doesn't exist, even though the command run specifically looks for its existence before trying to call it" (#7727).

**Comment by tobowers** [comment]
Sorry... the problem I'm having is  "oci runtime error: exec failed: cannot exec a container that has run and stopped\n"

**Comment by superseb** [comment]
Ok @tobowers , so the workarounds for now are downgrading to Docker 1.21.1 or upgrading to 7.3 or get a newer kernel for 7.2.

**Comment by morlay** [comment]
@superseb @tobowers 
For docker@1.3.0 we can update kernel to `3.10.0-514.6.1.el7.x86_64` first, it works for me.

**Comment by alena1108** [comment]
@deniseschannon could you reassign?

**Comment by superseb** [comment]
This can be closed, newer kernel fixes this and a lot of other problems. This is also on docs.rancher.com now.
