### ISSUE TITLE
Openstack Cattle Cloud stopped working after upgrade

### ISSUE THREAD

**Issue by JoelESvensson** [rancher/rancher#6863]
After upgrading to cattle 1.2, from the previous version, everything stopped working. I'm using Cattle with a Openstack provider that runs host with the latest stable CoreOS. My solution to get things working was to tear everything down and rebuild the cloud from scratch.

Edit: I ended up reverting to Rancher 1.1.3

**Comment by pschirch** [comment]
@JoelESvensson On which Docker version your nodes working?

**Comment by JoelESvensson** [comment]
All nodes are running 1.11.2

**Comment by JoelESvensson** [comment]
I think this is a duplicate of #6858 so i'm closing the issue

**Comment by deniseschannon** [comment]
@JoelESvensson As per the issue comments in #6858, can you please run these commands and share? Are you using b2d hosts? If so, please look at this issue: https://github.com/rancher/rancher/issues/6874

```
mkdir -p support
rancher hosts -a > support/hosts
rancher logs --tail=-1 ipsec/ipsec > support/ipsec 2>&1
rancher logs --tail=-1 network-services/metadata > support/metadata 2>&1
rancher logs --tail=-1 network-services/network-manager > support/network-manager 2>&1
```

Please be advised the files will have all your hosts and IP in them.

**Comment by JoelESvensson** [comment]
What does b2d mean in this context? I'm probably going to create a staging cloud in the weekend to test things. I'll get back to you when that happens

**Comment by pschirch** [comment]
@JoelESvensson `b2d` means boot2Docker.

**Comment by JoelESvensson** [comment]
No I'm using the latest stable CoreOS (1185.3.0)
