### ISSUE TITLE
Consider service as LB if lb config has at least one port rule with source port present

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#6865]
Today rancher-compose assumes that this is an lb service based on the lb_config presence. But target service can have this field too, when it joins selector based lb and carries his own targetport/hostname/path. We should instead rely on sourcePort presence in one of the lbconfig.portRules to make this decision. 

@deniseschannon

**Comment by sangeethah** [comment]
Tested with rancher-compose version - rancher-compose-v0.12.1-rc1

Able to create Lb Service using rancher-compose by having at least 1 portRule having sourcePort and selector/sourcePort,targetPort and service.
