### ISSUE TITLE
rancher/agent:latest is not up2date

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#6866]
**Rancher Version:**
N/A
**Docker Version:**
N/A
**OS and where are the hosts located? (cloud, bare metal, etc):**
N/A
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
N/A
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
N/A
**Steps to Reproduce:**
docker pull rancher/agent
**Results:** 
docker pull rancher/agent will get you rancher/agent:v0.11.0
**Expected:**
Noboby likes the latest tag, but because rancher/server is up2date with latest so should agent in my opinion. Of course, this is just minor but important to get right in the build/publish tooling.

**Comment by vincent99** [comment]
Fair enough, [sold](https://hub.docker.com/r/rancher/agent/tags/)
