### ISSUE TITLE
Upgrade from 1.1.4 to 1.2.0 fails when upgrading environment, with "Duplicate mount point '/var/lib/rancher/etc')'"

### ISSUE THREAD

**Issue by stefanlasiewski** [rancher/rancher#6868]
**Rancher Version:**

1.2.0

**Docker Version:**

Docker version 1.12.2, build bb80604

**OS and where are the hosts located? (cloud, bare metal, etc):**

CentOS 7.2, VMware ESXi VMs

Storage driver: Devicemapper with direct-lvm, following https://docs.docker.com/engine/userguide/storagedriver/device-mapper-driver/#/configure-direct-lvm-mode-for-production

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

single node rancher with external DB, and 4 Rancher custom hosts (e.g. The VM hosts running rancher/agent).

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

Cattle

**Steps to Reproduce:**

I was running Rancher 1.1.4. One Rancher server node, 4 Rancher worker nodes. Rancher-server was running with these settings:

    docker run rancher-server --restart=always -e CATTLE_DB_CATTLE_MYSQL_HOST=db01 -e other database settings --name rancher-server rancher/server

I followed the upgrade instructions at https://forums.rancher.com/t/rancher-release-v1-2-0/4750
1.  `docker stop rancher-server`
2. Backup the external MySQL database
3. `docker pull rancher/server`
4. `docker run rancher-server --restart=always -e CATTLE_DB_CATTLE_MYSQL_HOST=db01 -e other database settings --name rancher-server rancher/server`
5. Log into Rancher WebUI
6. Click on the "Upgrade environment" button for the Default environment.

**Results:** 

See the attached screenshot for a view.

Rancher starts to upgrade the environment, but was still not finished after 30 minutes. When I check on "Stacks > Infrastructure", I see that the 'healthcheck' and 'scheduler' containers are both failed with this error:

(Expected state running but got stopped: Error response from daemon: Duplicate mount point '/var/lib/rancher/etc')

![image](https://cloud.githubusercontent.com/assets/142752/20817140/b3556f62-b7da-11e6-91db-2eb6f7dee8d8.png)

**Expected:**

n/a

**Comment by stefanlasiewski** [comment]
I restarted the Rancher server, per recommendation on the IRC channel. That made the `Duplicate mount point '/var/lib/rancher/etc'` error go away.

Now the 'healthcheck' and 'scheduler' containers are failing with `Timeout getting IP address` (Looks like #6864 ).

I also restarted a couple of the Rancher worker nodes, but no luck.

**Comment by deniseschannon** [comment]
Are you using b2d hosts? @stefanlasiewski

**Comment by stefanlasiewski** [comment]
b2d, meaning boot2docker? No. These are fairly vanilla CentOS 7 hosts, running Docker 1.1.2 (From the upstream Docker repo).

**Comment by stefanlasiewski** [comment]
I've noticed that a number of infrastructure containers are failing with errors like 'Timeout getting IP address'. Even the `rancher-agent container is failing.

I wonder this related to the DNS service?

**Comment by lucacri** [comment]
@stefanlasiewski how many hosts do you have? The issue is similar to mine: if you have many hosts (in my case, 120 bare metal servers), a concurrency issue happens. The metadata service doesn't start because the sidekick is not started yet, or otherwise. Rinse and repeat

**Comment by cjellick** [comment]
@stefanlasiewski can you follow the instructions to grab all the relevant logs that @ibuildthecloud outlined here: https://github.com/rancher/rancher/issues/6858#issuecomment-264314609?

**Comment by cjellick** [comment]
Regarding the originally reported Duplicate Mountpoint issue: I did some searching and it seems that that is an error state that docker can get into, perhaps under race conditions. I think the reference count for a volume gets out of sync with reality. This would explain why rebooting the hosts resolved the problem. I don't think there is much we could have done to recover, but we should keep an eye out for this problem happening to others.

I'm basing this analysis off of the following bug reports:
- https://github.com/docker/docker/issues/25772
- https://bugzilla.redhat.com/show_bug.cgi?id=1331781
- https://github.com/docker/docker/issues/22093
None of these are a smoking gun or the exact same problem, but the point to a general possibility of the map of mount points getting out of sync in docker.

@stefanlasiewski, I'd like to not conflate the original mount point issue with your current "Timeout getting IP", so would you mind continuing the conversation regarding that problem in #6864?

**Comment by stefanlasiewski** [comment]
Sure, let's continue the discussion of "Timeout getting IP" in  #6864.

This mount point issue appears to be resolved for me, since I rebooted the master.

**Comment by stefanlasiewski** [comment]
Unfortunately, I don't think I collected enough information on this to aid in troubleshooting.

I'm going to close this ticket.

**Comment by stefanlasiewski** [comment]
Unfortunately, I don't think I collected enough information on this to aid in troubleshooting.

I'm going to close this ticket.
