### ISSUE TITLE
dns stack missing after update to 1.2.0

### ISSUE THREAD

**Issue by svensp** [rancher/rancher#6870]
**Rancher Version:**
1.2.0

**Docker Version:**
1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
vhost+bare metal, Hetzner

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Update 1.1.4 -> 1.2.0
Hosts locked up due to "waiting for lo to become free" docker / linux kernel issue
Reset hosts
Rollback to 1.1.4 Database
Start fresh 1.2.0 container

**Results:** 
Loadbalancers do not work.
Exec into a container showed successful ping to a container on a different host
Infrastructure Stacks show
- Healthcheck
- ipsec
- network-services
- scheduler
The DNS Stack mentione here seems to be missing:
http://docs.rancher.com/rancher/v1.2/en/faqs/troubleshooting/#how-can-i-see-if-my-dns-is-set-up-correctly

"Add from Catalog"  has the other present services listed, but looking for dns only shows external services. Is it not possible to add this missing stack?

**Comment by stefanlasiewski** [comment]
I noticed this also. I think this is just a documentation bug.

The DNS service is a "Sidekick" container, I believe. To see it, go to Stacks > Infrastructure, open the  'network-services' stack, open the 'metadata' service, and you should see services named like this:

network-services_metadata_1              rancher/metadata:v0...
network-services_metadata_2             rancher/metadata:v0...
**network-services_metadata_dns_1       rancher/dns:v0.10.8
network-services_metadata_dns_2      rancher/dns:v0.10.8**
network-services-metadata-1              ...
network-services-metadata-2             ...
**network-services-metadata-dns-1      rancher/dns:v0.10.8...
network-services-metadata-dns-2     rancher/dns:v0.10.8...**

**Comment by deniseschannon** [comment]
Yes, we moved DNS into the network services, but after I documented it. 

It's updated now in the docs.
