### ISSUE TITLE
Should rancher-agent's network mode be "host" or "bridged"?

### ISSUE THREAD

**Issue by PotterDai** [rancher/rancher#6873]
**Rancher Version:** 
1.2.0
**Docker Version:** 
1.11.2
**OS and where are the hosts located? (cloud, bare metal, etc):**
CoreOS
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
cattle
**Steps to Reproduce:**

Add a host in a local network.

**Results:** 
rancher-agent's network mode displayed as "Host"
docker inspect in CoreOS shows network mode as "Bridged"

Should rancher-agent's network mode be "host" or "bridged"?
Currently multiple rancher-agent on different machine cannot ping each other, since they all get a local IP which is 172.17.0.2 under docker bridged network mode.

**Comment by vincent99** [comment]
`rancher/agent` connects the host to the server and executes the changes it's told to make.  It does not have any reason to communicate with other hosts.  

Cross-host communication is handled by the `rancher/net` "ipsec" service containers deployed onto each host.
