### ISSUE TITLE
Boot2Docker hosts - network manager v0.2.12 - Infrastructure Stacks stuck in Activating

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#6874]
**Rancher Version:**
1.2.0

Boot2Docker hosts are unable to get their infrastructure stacks in activating. You will most likely see 'Timeout getting IP address' error on healthcheck and ipsec containers.

**Workaround:**

To confirm that this is your issue, run `ln -s / /mnt/sda1` in the network-manager container. After a bit the ipsec container will come up.

**Comment by deniseschannon** [comment]
Available to test as network services v0.0.2, which is currently in the `vnext` branch of rancher-catalog.

**Comment by sangeethah** [comment]
Tested with fresh install of rancher-server - v1.2.0 with 1 b2d host.
ipsec container fails to start with error- 'Timeout getting IP address'. health-check and scheduler services also fail to come up.

Add catalog -"library" pointing to https://git.rancher.io/rancher-catalog.git branch- vnext.

There is an upgrade available option that is presented to the network-services in "Infrastructure Stacks".
Upgrade the service.
Once service is upgraded, network-manager uses rancher/network-manager:v0.2.13 .

ipsec containers are able to start successfully.
 health-check and scheduler service containers also eventually get to running state.

When  new hosts are added to the setup , ipsec health-check and scheduler containers are able to start successfully.
