### ISSUE TITLE
rancher v1.2.0 environment describle cannot use chinese

### ISSUE THREAD

**Issue by HackerWilson** [rancher/rancher#6876]
**Rancher Version:**
rancher v1.2.0

**Docker Version:**
Docker version 1.12.3, build 6b644ec

**OS and where are the hosts located? (cloud, bare metal, etc):**
bare metal

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Swarm

**Steps to Reproduce:**
Add Environment -> fill in describle with chinese like “开发”

**Results:** 
Internal Server Error

rancher logs：
2016-12-02 05:10:54,855 ERROR [:] [] [] [] [p1830712962-191] [i.g.i.g.r.handler.ExceptionHandler  ] Exception in API for request [http://192.168.0.40/v2-beta/project]. Error id: [6f62987f-691b-4ab3-877b-d5eeff6b93cd]. org.jooq.exception.DataAccessException: SQL [insert into `account` (`name`, `kind`, `uuid`, `description`, `state`, `created`, `data`, `project_template_id`, `version`) values (?, ?, ?, ?, ?, ?, ?, ?, ?)]; Incorrect string value: '\xE6\xB5\x8B\xE8\xAF\x95...' for column 'description' at row 1
...

**Expected:**
success

**Comment by HackerWilson** [comment]
when I delete the describle and create the swarm env, set the swarm env as the default env, go back to the index page, then nothing shows here: http://192.168.0.40/env/1a8/swarm/console

only the initial env could show me the page to add host.

**Comment by deniseschannon** [comment]
i have been unable to reproduce. 

Where in the Add environment screen have you been putting in chinese characters? I put them in name and description and am able to navigate to them. 

![screen shot 2016-12-02 at 11 19 00 am](https://cloud.githubusercontent.com/assets/11410997/20847043/2fc4062a-b881-11e6-893a-ab7ca22c2c2f.png)

If I set the environment with the description that has chinese characters as my default, when i navigate to http://<ip>:port, i am redirected to that environment. 


Is this a fresh install or upgraded setup?

**Comment by HackerWilson** [comment]
@deniseschannon just like this:
<img width="651" alt="default" src="https://cloud.githubusercontent.com/assets/7730203/20873131/9329c8e8-badf-11e6-8bd9-41b598605128.png">

**Comment by vincent99** [comment]
@HackerWilson I suspect your external DB was not configured with the [charset set to UTF-8](http://docs.rancher.com/rancher/v1.2/en/installing-rancher/installing-server/#launching-rancher-server---single-container---external-database).

**Comment by HackerWilson** [comment]
@vincent99 oh, yes. thanks for your help.
