### ISSUE TITLE
Is it possible to make dockercloud/haproxy play nice with rancher-managed stacks and containers?

### ISSUE THREAD

**Issue by virtuman** [rancher/rancher#6877]
**Rancher Version:**
1.2.0

**Docker Version:**
1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04 baremetal

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node, server has multiple IPs

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
start service on a host locally and then start another service that would use this port on a different IP address

**Results:** 
service that is publishing port on docker will kill all access to the service that is running on host on a different IP address on the same post

**Expected:**
Since the IP field has been removed in version 1.2.0 I was wondering if it is at all possible to use service like dockercloud/haproxy to manage published ports?

I tried using rancher and docker-compose to try to start up the dockercloud/haproxy, but for some reason I couldn't figure out how to link containers executed from rancher with this proxy container. Here's an example docker-compose.yml file that I tried to use:

version: '2'
services:
  lb:
    image: dockercloud/haproxy
    labels:
      io.rancher.container.network: 'true'
    external_links:
      - mongo/mongo:mongo
      - rocketchat/chat:chat
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 83:83
      - 84:84

but despite external_links - i was still unable to access / ping the containers that were in theory supposed to become linked based on external_links rule

**Comment by vincent99** [comment]
1.4 has support for scheduling multiple IPs per host.  The IP field was never really "removed" but is "back" in later versions.  And I don't think there's much we can (or at least, are planning to) do to change what happens if you ask for conflicting ports in native docker vs rancher.

**Comment by virtuman** [comment]
thank you. it's funny how unfortunate i am at trying to use rancher. this time around I was set on deploying kubernetes cluster, and it didn't want to play well with my existing docker 1.13.1 infrastructure ... I guess I'll try it after 1.6 is out. But thank you for letting know that you're re-added the IP field, we already switched over to docker swarm mode though
