### ISSUE TITLE
[rancher-dns] Failed to add DNS record to provider ... i/o timeout

### ISSUE THREAD

**Issue by marcelosousaalmeida** [rancher/rancher#6881]
**Rancher Version:**
1.1.4
**Docker Version:**
1.12.1
**OS and where are the hosts located? (cloud, bare metal, etc):**
Debian Jessie (bare metal)
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
I've alreary faced this issue on every time of setup
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
Add 39 or more services with one or more exposed ports to that way external-dns grab records and try to add these records do DNS server. One real setup is to add 39 hosts to a single environment and after that launch Prometheus stack present on Rancher catalog (https://github.com/rancher/community-catalog/tree/master/templates/Prometheus)
**Results:** 
Failed to add DNS record to provider {ranch-eye.prometheus.live.mydomain.internal. [192.168.101.26 192.168.101.103 192.168.101.104 192.168.101.109 192.168.101.111 192.168.101.24 192.168.101.110 192.168.101.102 192.168.101.114 192.168.101.115 192.168.101.123 192.168.101.116 192.168.101.101 192.168.101.106 192.168.101.105 192.168.106.4 192.168.101.14 192.168.101.16 192.168.101.22 192.168.101.107 192.168.101.122 192.168.101.124 192.168.101.126 192.168.101.108 192.168.101.112 192.168.101.113 192.168.101.117 192.168.101.118 192.168.101.120 192.168.101.121 192.168.101.119 192.168.101.15 192.168.101.125 192.168.101.23 192.168.101.27 192.168.101.21 192.168.101.17 192.168.101.18 192.168.101.19] A 300}: RFC2136 query failed: read udp 172.17.0.3:44332->192.168.201.1:53: i/o timeout" 
**Expected:**
Add A records above to DNS server

**Comment by janeczku** [comment]
@marcelosousaalmeida This might be an issue with Docker iptables dropping UDP packets (see https://github.com/docker/docker/issues/8795). Please upgrade to the current stable Rancher release as we have changed how we provide networking to containers in v1.2. Feel free to reopen if the issue persists!
