### ISSUE TITLE
rancher gui is not presenting the actual container state

### ISSUE THREAD

**Issue by gyalai** [rancher/rancher#6884]
**Rancher Version:**
1.2.0-pre3
**Docker Version:**
1.12.3
**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04 Bare metal, Chrome browser

**Steps to Reproduce:**
The convoy-nfs-agent container wasn't able to start and it made lost of  retries on the web interface. The page was opened and these retries was follow-able. However, the issue has been fixed on the host and the container actually started but the initialize-retry-stop state changes was still going on the interface. 

A browser refresh fixed the issue, but it was still very unpleasant experience.

**Comment by tfiduccia** [comment]
Version - 1.2.0
We have made quite a few changes in the final 1.2.0 change event process, so this should be fixed.  If you still see it when you move to 1.2.0, please re-open.

Also - FYI, we have stopped supporting convoy-nfs in 1.2.0.  But have created a rancher-nfs which we fully support.
