### ISSUE TITLE
[UI] Environment templates description is equal to environment description

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#6887]
**Rancher Version:**
v1.2.0
**Docker Version:**
N/A
**OS and where are the hosts located? (cloud, bare metal, etc):**
N/A
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
N/A
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
N/A
**Steps to Reproduce:**
Click on Default Environment and choose Manage Environments
**Results:** 
Description of Environments and Environment Templates is the same.
**Expected:**
Correct description for Environment Templates

**Comment by superseb** [comment]
https://github.com/rancher/ui/pull/930

**Comment by tfiduccia** [comment]
Version - master 11/13
Verified fixed
