### ISSUE TITLE
Do not sort user provided custom config for haproxy; add support for "userlist" directive

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#6888]
Today we alphabetically sort the custom config parameters given by the user, and it can break stuff where order of the parameters actually matters. Use case example:

```
userlist UsersFor_Ops
  group AdminGroup users userone,usertwo
  user userone password $6$yMgsow58.g/Z$mBjHfdVzqcF/LN.iwV23Eyqg.yGPTsp9pOwaStsJ6c4I4zL7BhucVVAkv5guf7OVRr8Pw0mHF4NrWBRCG5ci7/
  user usertwo password $6$RZ86vRkQ$aRKN1HOsk6bDHBbMhS7jSo/p1NGFl4PvwY3KpU.72i./LvITi41nL84EkxOFXl.6Bmhynj/L7pYbfF0rUHtOB0

```

https://forums.rancher.com/t/add-basic-auth-to-a-load-balancer/4780/3

**Comment by alena1108** [comment]
Also need to add support for userlist directive

**Comment by alena1108** [comment]
@sangeethah to test, just put this in the custom config, and validate that config apply doesn't fail:

```
global
 userlist L1
   group G1 users tiger,scott
   group G2 users xdb,scott
   user tiger password mypass
   user scott insecure-password elgato
   user xdb insecure-password hello
```

**Comment by alena1108** [comment]
@sangeethah should be tested on upgraded LB (v0.4.5)

**Comment by soumyalj** [comment]
Tested with v1.2.1-rc1 and v1.2.1-rc2. Created a stack with Lb and Service with the Userlist directive as mentioned above. The Lb was funtional. The ha-proxy config was populated with the Userlist directive and the custom config was not sorted as expected. Here is a snippet of the /etc/haproxy/haproxy.cfg file with UserList : 
```
defaults
    balance first
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http
    maxconn 4096
    mode tcp
    option forwardfor
    option http-server-close
    option redispatch
    retries 3
    timeout client 50000
    timeout connect 5000
    timeout server 50000

userlist L1
         group G1 users tiger,scott
         group G2 users xdb,scott
         user tiger password mypass
         user scott insecure-password elgato
         user xdb insecure-password hello
```

**Comment by djskinner-sky** [comment]
Still can't get basic auth to work:

```
userlist L1
         user xdb insecure-password hello

backend myApp
         acl AuthOkay_UsersAuth http_auth(L1)
         http-request auth realm UserAuth if !AuthOkay_UsersAuth
```

The container doesn't complain about the config and starts now but I don't get the basic auth prompt.

Where am I going wrong?

**Comment by djskinner-sky** [comment]
```
userlist L1
         user xdb insecure-password hello

frontend
         acl AuthOkay_UsersAuth http_auth(L1)
         http-request auth
```

Doesn't work either

**Comment by greg0ire** [comment]
@djskinner-sky here is my config, it works : 

```
global
 userlist DB
   user me insecure-password redacted

backend 80_redacted_
  acl AuthOK_DB http_auth(DB)
  http-request auth realm DB if !AuthOK_DB
```

**Comment by vincent99** [comment]
If you have existing balancers from 1.2.0 they will need to have their images upgraded (the little orange up arrow) or be recreated.

**Comment by djskinner-sky** [comment]
@greg0ire that works. I was missing the `global`. I did have to manually delete the container first though. Straight upgrading the existing container didn't seem to work. I'd already clicked the little orange up arrow as @vincent99 suggested when I initially upgraded Rancher itself.

**Comment by greg0ire** [comment]
Glad to learn that did the trick for you. I faced this problem myself today and was really happy to learn it was fixed with the 1.2.1 release only 3 days ago !

**Comment by proligde** [comment]
I'm running Rancher 1.3.0 with current lb-service-haproxy:v0.4.9

It didn't work with any configuration I tried. I also tried @greg0ire 's version (including "global") but still:

Failed to apply lb config on provider: error reloading  -- reloading haproxy config with the new config changes\n[ALERT] 010/072144 (62) : parsing [/etc/haproxy/haproxy.cfg:32] : unable to find userlist 'DB' referenced in arg 1 of ACL keyword 'http_auth' in proxy

Am I missing sth. important here?

**Comment by ebreton** [comment]
Rancher	v1.3.2
Cattle	v0.175.8
User Interface	v1.3.6
Rancher Compose	v0.12.1

Using Rancher sandbox with coreOS host (stable 1235.6.0)

I am trying to have basic auth with https. 

<img width="1012" alt="capture d ecran 2017-01-22 a 16 03 39" src="https://cloud.githubusercontent.com/assets/490665/22183361/973be6e8-e0bc-11e6-87cb-df66f6409407.png">


I used the config given by @greg0ire above. The LB does not start and I have the following error in the logs:

```
time="2017-01-22T14:58:29Z" level=info msg="KUBERNETES_URL is not set, skipping init of kubernetes controller" 
time="2017-01-22T14:58:30Z" level=info msg="Starting Rancher LB service" 
time="2017-01-22T14:58:31Z" level=info msg="LB controller: rancher" 
time="2017-01-22T14:58:31Z" level=info msg="LB provider: haproxy" 
time="2017-01-22T14:58:31Z" level=info msg="starting rancher controller" 
time="2017-01-22T14:58:31Z" level=info msg="Healthcheck handler is listening on :10241" 
time="2017-01-22T14:58:33Z" level=info msg=" -- starting haproxy\n[ALERT] 021/145832 (32) : Starting frontend GLOBAL: cannot bind UNIX socket [/run/haproxy/admin.sock]\n" 
time="2017-01-22T14:58:34Z" level=info msg=" -- reloading haproxy config with the new config changes\n[ALERT] 021/145834 (43) : parsing [/etc/haproxy/haproxy.cfg:32] : unable to find userlist 'DB' referenced in arg 1 of ACL keyword 'http_auth' in proxy '80_redacted_'.\n[WARNING] 021/145834 (43) : config : 'option forwardfor' ignored for backend '80_redacted_' as it requires HTTP mode.\n[WARNING] 021/145834 (43) : config : 'option forwardfor' ignored for proxy 'default' as it requires HTTP mode.\n[ALERT] 021/145834 (43) : Fatal errors found in configuration.\n" 
time="2017-01-22T14:58:34Z" level=error msg="Failed to apply lb config on provider: error reloading  -- reloading haproxy config with the new config changes\n[ALERT] 021/145834 (43) : parsing [/etc/haproxy/haproxy.cfg:32] : unable to find userlist 'DB' referenced in arg 1 of ACL keyword 'http_auth' in proxy '80_redacted_'.\n[WARNING] 021/145834 (43) : config : 'option forwardfor' ignored for backend '80_redacted_' as it requires HTTP mode.\n[WARNING] 021/145834 (43) : config : 'option forwardfor' ignored for proxy 'default' as it requires HTTP mode.\n[ALERT] 021/145834 (43) : Fatal errors found in configuration.\n: exit status 1" 
```

it does not find the user list...

Any tip ?

**Comment by podorozhny** [comment]
@ebreton, I have same issue. Did u find the solution?)

**Comment by greg0ire** [comment]
Does the generated `haproxy.cfg` look good?

**Comment by ebreton** [comment]
@podorozhny nope. moved back to nginx-proxy for now

**Comment by marcovn** [comment]
I have this config and it works great

```
global
    userlist L1
         user hello insecure-password world

backend myapp
         acl AuthOkay http_auth(L1)
         http-request auth realm UserAuth if !AuthOkay```

**Comment by phal0r** [comment]
I can confirm that @marcovn solution works, but it will still fail with rancher v1.5 when using more than 1 userlist. So this seems like a bug to me. Can the others confirm this?

**Comment by marcovn** [comment]
Hey @phal0r I did a quick test on our setup and can confirm your findings with multiple user lists.

I setup the custom haproxy like this:

```yaml
        global
            userlist L1
                 user hello insecure-password world
            userlist L2
                 user john insecure-password doe

        backend claim
          acl rule1 http_auth(L1)
          acl rule2 http_auth(L2)
          http-request auth realm mystuff if !rule1
          http-request auth realm mystuff if !rule2`
```

The result is that only the last userlist is rendered in the resulting config in the container at /etc/haproxy/haproxy.cfg

Seems a bug to me. Not affected by it as we use just one userlist in our config.

**Comment by phal0r** [comment]
Thanks for coming back on this @marcovn 

@alena1108 Can you also confirm this, so we can make a bug report out of this finding?

**Comment by gregori-goossens** [comment]
@phal0r 
Hi,

i can confirm that only last userlist is in the generated /etc/haproxy/haproxy.cfg.

actually i use group to manage users auth by backend 
``` 
global
  userlist L1
    group G1 users test1
    group G2 users test2,test1
    user test1 insecure-password hello
    user test2 insecure-password bonjour

backend custombk1
  acl AuthOkay http_auth_group(L1) G1
  http-request auth realm UserAuth if !AuthOkay

backend custombk2
  acl AuthOkay http_auth_group(L1) G2
  http-request auth realm UserAuth if !AuthOkay
```

NB : be carefull no space in users directive list after comma : group G1 users test2,test1

**Comment by mdymel** [comment]
I was struggling to get it to work too, but found out what was the problem. 

It turned out to be important to name the `backend` section exactly as it is in the config file. I have checked the `/etc/haproxy/haproxy.cfg` file, found the section responsible for my site, ex. `backend 443_domain_com_` and then added custom config: 

```
userlist L1
    user admin insecure-password asd123

backend 443_domain_com_
	acl AuthOkay http_auth(L1)
	http-request auth realm UserAuth if !AuthOkay
```

And it finally worked fine.

**Comment by marvinwankersteen** [comment]
I still have sometimes trouble that the config wont be reloaded.
```
[ALERT] 260/174410 (591) : parsing [/etc/haproxy/haproxy.cfg:306] : unable to find userlist 'FHEM' referenced in arg 1 of ACL keyword 'http_auth' in proxy 'fhem'.
[ALERT] 260/174410 (591) : parsing [/etc/haproxy/haproxy.cfg:321] : unable to find userlist 'FHEM' referenced in arg 1 of ACL keyword 'http_auth' in proxy 'fhem2'.
```

```
global
userlist FHEM
user user1 password $6$asL......
user user2 password $6$asL......

backend fhem
..
..
acl AuthOkay_FHEM http_auth(FHEM)
http-request auth realm FHEM if !AuthOkay_FHEM

backend fhem2
..
..
acl AuthOkay_FHEM http_auth(FHEM)
http-request auth realm FHEM if !AuthOkay_FHEM
```

I have no idea what is the problem. I use rancher v1.6.7. All stacks and loadbalancers are updated.
