### ISSUE TITLE
Rancher CLI fails to install catalog by name

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#6889]
**Rancher Version:**1.2.0

**Rancher CLI version**: v0.4.0

**Docker Version:**1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):**Ubuntu, Cloud

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**Single node

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**Cattle

**Steps to Reproduce:**
1. Setup rancher CLI v0.4.0
2. Issue the command to install a catalog by name. 

Results
The command fails
```
soumyas-MacBook-Pro:rancher-v0.4.0 soumya$ ./rancher catalog install Wordpress
FATA[0001] Failed to find template Wordpress            

```

Note: Catalog install by id succeeds
```
soumyas-MacBook-Pro:rancher-v0.4.0 soumya$ ./rancher catalog install community/wordpress:v0.1-educaas1
public port to access the wordpress site
Public Port public_port[80]: 
1st53

```

**Comment by deniseschannon** [comment]
We wouldn't be able to install by name, as there is no guarantee that name will be unique. 

I'll make a PR to update the help for this command.
