### ISSUE TITLE
Web UI, catalog, combo box app selection bug

### ISSUE THREAD

**Issue by Dmitry1987** [rancher/rancher#6890]
A bug in web UI as seen on those screenshots:
![image](https://cloud.githubusercontent.com/assets/9369080/20850030/051f6fe8-b8e2-11e6-9660-55baf2855749.png)
![image](https://cloud.githubusercontent.com/assets/9369080/20850061/269040f8-b8e2-11e6-9c68-f49a4eb2d084.png)

**Rancher Version:**
1.2.0
**Docker Version:**
1.12.3
**OS and where are the hosts located? (cloud, bare metal, etc):**
RancherOS AMI, latest from AWS marketplace
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node master, test with 1 additional slave node.  internal DB, simple docker run install.
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Probably unrelated but K8s, link looks like this: http://xx.xxx.xxx.xx:8080/env/1a16/catalog/community:kubernetes*rabbitmq 
**Steps to Reproduce:**
Open some random app in catalog, I opened Zookeeper, then use combo box with app name to select other apps, without going back to main catalog page.
**Results:** 
Description always stays the one of 1st used app (Zookeeper as in screenshot)
**Expected:**
Description to be relevant to selected app from combo box.

I'm a big fan of Rancher btw :) will soon attempt a large scale production migration there :+1: keep up the great job!

**Comment by tfiduccia** [comment]
Version - 1.2.0
Checked this with the latest version and it is easily reproducible and indeed a bug.

**Comment by vincent99** [comment]
#6470
