### ISSUE TITLE
Github auth times out, can't log in

### ISSUE THREAD

**Issue by emcniece** [rancher/rancher#6893]
**Rancher Version:**
1.2.0

**Docker Version:**
1.12.3, build 6b644ec

**OS and where are the hosts located? (cloud, bare metal, etc):**
CoreOS, Packet.net

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node Rancher, internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Set up Github authorization, log out, log in

**Results:** 
Login action hangs for a minute, then fails. An error message is displayed in the UI: "Error Response from Auth service".

**Expected:**
Login succeeds

**Details:**

This started happening very recently after having the system running well for a few days. I am not aware of any changes within the Rancher admin, especially to the Github auth settings (and I am the only one working on this system).

During login, http://rancher.company.ca:8080/v2-beta/token hangs for a while before returning with a JSON response:

```
{"id":"9e67f41d-5688-4677-884d-fc79a0340266","type":"error","links":{},"status":503,"code":"AuthError","message":"Error Response from Auth service","detail":"Status code from Auth Service: 500","baseType":"error","actionLinks":{}}
```

Rancher logs reveal IO timeout:

```
time="2016-12-02T21:53:09Z" level=error msg="Failed to pull the catalog from git repo https://git.rancher.io/infra-catalog.git, error: exit status 1"
time="2016-12-02T21:53:09Z" level=error msg="Received error from github: Post https://github.com/login/oauth/access_token: dial tcp 192.30.253.112:443: i/o timeout"
time="2016-12-02T21:53:09Z" level=error msg="Github getAccessToken: GET url https://github.com/login/oauth/access_token received error from github, err: Post https://github.com/login/oauth/access_token: dial tcp 192.30.253.112:443: i/o timeout"
time="2016-12-02T21:53:09Z" level=error msg="Error generating accessToken from github Post https://github.com/login/oauth/access_token: dial tcp 192.30.253.112:443: i/o timeout"
time="2016-12-02T21:53:09Z" level=error msg="GetToken failed with error: Post https://github.com/login/oauth/access_token: dial tcp 192.30.253.112:443: i/o timeout"
2016-12-02 21:53:09,586 ERROR [:] [] [] [] [tp1830712962-16] [.a.a.i.e.ExternalServiceAuthProvider] Got error from Auth service. statusCode: 500
```

**Comment by vincent99** [comment]
It seems like the outbound connections are just going to a blackhole somehow.. DNS resolution is working since it gets an IP for github.com but it's just not able to conenct to github.

If you `docker exec -it <id of rancher/server> bash` and run `curl -v https://github.com/login/oauth/access_token` do you get a response back?

**Comment by emcniece** [comment]
Very interesting, thanks for the pointer. Seems like this might be a networking issue.

```
root@b3dd3643d47f:/# curl -v https://github.com/login/oauth/access_token
* Hostname was NOT found in DNS cache
*   Trying 192.30.253.113...
* connect to 192.30.253.113 port 443 failed: Connection timed out
*   Trying 192.30.253.112...
* After 86278ms connect time, move on!
* connect to 192.30.253.112 port 443 failed: Connection timed out
* Failed to connect to github.com port 443: Connection timed out
* Closing connection 0
curl: (7) Failed to connect to github.com port 443: Connection timed out

root@b3dd3643d47f:/# curl --version
curl 7.35.0 (x86_64-pc-linux-gnu) libcurl/7.35.0 OpenSSL/1.0.1f zlib/1.2.8 libidn/1.28 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smtp smtps telnet tftp
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP

root@b3dd3643d47f:/# uname -a
Linux b3dd3643d47f 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by emcniece** [comment]
Restarting the host machine solved the problem.

Some searching indicated that the network interfaces may have been hung. Restarting Docker with `service restart docker` worked, but the network interfaces at `ifconfig` did not come back up with all of the containers and I was still not able to `curl` out from the Rancher container. A full system reboot brought both Docker and the network back up.

Thanks for the help!

Reading material:

- http://stackoverflow.com/questions/38962676/docker-hostname-was-not-found-in-dns-cache
- http://serverfault.com/questions/642981/docker-containers-cant-resolve-dns-on-ubuntu-14-04-desktop-host/642984#642984
- https://gitlab.com/gitlab-org/gitlab-ci-multi-runner/issues/977

**Comment by noogen** [comment]
This just happened to me.  Made an assumption that maybe github auth is down so I waited a while but it still didn't work.  Did some googling of  "Error Response from Auth service" and saw this thread.  Restarted my host and it work.  Just FYI.  Hopefully, I didn't wake up any zombie...
