### ISSUE TITLE
Kubernetes kubectl not showing all nodes

### ISSUE THREAD

**Issue by MinaDesu** [rancher/rancher#6894]
**Rancher Version:**
rancher/server latest
CATTLE_RANCHER_SERVER_VERSION		v1.2.0

**Docker Version:**
1.11.2

**OS and where are the hosts located? (cloud, bare metal, etc):**
Cloud DigitalOcean - CoreOS 1185.3.0 (with KVM) (4.7.3)

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single rancher master with 3 nodes (one being on the master)

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
Add the hosts as a Kubernetes environment
Wait for everything to turn green under Kubernetes Infrastructure
Execute: kubectl get nodes

![rancher_01](https://cloud.githubusercontent.com/assets/14047116/20852498/254c9558-b8b4-11e6-83b4-8745dd859620.jpg)

![rancher_02](https://cloud.githubusercontent.com/assets/14047116/20852500/2551598a-b8b4-11e6-9e65-235ecffb92f3.jpg)

**Results:** 
Only one node present

![rancher_03](https://cloud.githubusercontent.com/assets/14047116/20852499/254e27c4-b8b4-11e6-9d6b-05a2ca019f1a.jpg)

**Expected:**
3 nodes present

**Comment by MinaDesu** [comment]
After checking my first screenshot, it appears the master node is not on the same network as the other 2.
Each node was created with the "Add host" under Infrastructure, on the Kubernetes project. Master node was the last one to be installed.

**Comment by MinaDesu** [comment]
I deleted every container and every image then proceeded to reinstall everything.
First, on the master node: sudo docker run -d --restart=unless-stopped -p 8080:8080 rancher/server
Then agent on the first node, after clicking on "Add Host" in a new Kubernetes environment.
Then agent on the second node, after clicking on "Add Host" in the Kubernetes environment.
Lastly on the master node, after clicking on "Add Host" in the Kubernetes environment.

I waited for each node to complete before adding a new one.

When I added the master as a node, it grabbed an IP address outside the range of the ones used for the other nodes, it cannot join the kubernetes cluster.

kubectl get nodes --> reporting the other 2 nodes, but not the master

**Comment by deniseschannon** [comment]
@MinaDesu I noticed in your first screen shot, the harley-quinn host has the docker bridge IP instead of the server IP. On any host that shows that, you should use the server's IP using the `CATTLE_AGENT_IP`. 

Do you have a screenshot of your current hosts?

**Comment by MinaDesu** [comment]
@deniseschannon you mean that I should set the host's server IP as CATTLE_AGENT_IP on all new hosts that I add?

**Comment by deniseschannon** [comment]
It should be the own public IP address of the host that is being added. 

There is no master IP.

**Comment by MinaDesu** [comment]
Ok I'm gonna recreate it all and set the host's IP for each node and keep you posted here.
However, without that, the cluster works on the 2 nodes at present (I didn't add the master on my last install).

**Comment by MinaDesu** [comment]
@deniseschannon I did as you said and set the hosts real IP as the CATTLE_AGENT_IP and now kubectl reports all correctly

![rancher_04](https://cloud.githubusercontent.com/assets/14047116/20854453/49d891ac-b8c2-11e6-9bf1-830b736bb92f.jpg)

Thanks for your advice on this point.

**Comment by MinaDesu** [comment]
Basically, what I observe here is that on the nodes that are not on the same host as the server, the bridge IP is set to a given range, but on the host that has the server running, it's set to another range.

**Comment by deniseschannon** [comment]
Yes, this is known issue with starting agents on the same node that is running rancher server. 

http://docs.rancher.com/rancher/v1.2/en/faqs/troubleshooting/#are-the-ips-of-the-hosts-correct-in-the-ui

 http://docs.rancher.com/rancher/v1.2/en/faqs/agents/#how-does-the-host-determine-ip-address-and-how-can-i-change-it-what-do-i-do-if-the-ip-of-my-host-has-changed-due-to-reboot

It sounds like this is just a known issue and I'll close.

**Comment by jujes** [comment]
Hi @deniseschannon and @MinaDesu I have the same issue, I follow the **own public IP address of the host** advice for each node deployed and kubectl show only one node...

what I am doing wrong?

thank in advance,

**Comment by AmreeshTyagi** [comment]
> Solved

: I was facing this issue, because my docker cgroup driver was different than kubernetes cgroup driver. 
Just updated it to `cgroupfs` using following commands mentioned in [doc](https://kubernetes.io/docs/setup/independent/install-kubeadm/).
`cat << EOF > /etc/docker/daemon.json
{
  "exec-opts": ["native.cgroupdriver=cgroupfs"]
}
EOF`

Restart docker service `service docker restart`.
Reset kubernetes on slave node: `kubeadm reset`
Joined master again: `kubeadm join <><>`

It was visible on master using `kubectl get nodes`
