### ISSUE TITLE
CPU graph not functioning correctly

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#6895]
**Rancher Version:** v1.2.0

**Steps to Reproduce:**
1.  Create a service
2.  Ping the CPU of the container

**Results:** Graph shows very little CPU being used.  But shell show 98%
![image](https://cloud.githubusercontent.com/assets/11514927/20853442/23b08764-b8a9-11e6-9537-2b2d055591a6.png)

**Expected:**  Graph should reflect correct amount

**Comment by tfiduccia** [comment]
Additional Info - Now the CPU is going from 0 to 100% for no apparent reason.
 
![image](https://cloud.githubusercontent.com/assets/11514927/21275832/cdc06fc0-c38b-11e6-8383-0da3c3d39e7d.png)

**Comment by deniseschannon** [comment]
Can you try this test and see if docker stats does the same thing? Since we're getting our info from docker stats, I'm wondering if it's docker stats showing this or something in between.

**Comment by LLParse** [comment]
I've also noticed that the CPU usage appears to be erroneous at the host level. CPU usage at the container level seems to line up with docker stats with a few second delay. Rounding to the nearest percent also seems a bit lossy, moreso when differentiating between system and user CPU.

What happened to cAdvisor? The metrics coming from that product seemed more precise.

**Comment by StrongMonkey** [comment]
It might be my bad. The unit of cpu usage for host may be different than containers.  In UI it use the same method to calculate percentage and that might be the reason it apppears erroneous.

**Comment by StrongMonkey** [comment]
To fix it, we probably need a re-write on the stats code in host-api.

**Comment by tfiduccia** [comment]
Version - master 2/21
Verified Fixed
