### ISSUE TITLE
Not require docker bridge to be docker0 

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#6896]
**Rancher Version:**
1.2

Currently, 1.2 only works if the docker bridge is docker0.

**Comment by emcniece** [comment]
Yeah, my networks are all over the place... containers aren't coming up with IPs anymore.

**Comment by deniseschannon** [comment]
Added ability to configure the docker bridge in the catalog templates for network-services, ipsec and vxlan

**Comment by galal-hussein** [comment]
Rancher version: v1.2.1-rc2 
rancher-catalog - vnext branch

I added different bridge other than docker0 and started docker both on rancher server and hosts with the new bridge, and i was able to deploy the infra stacks (ipsec, network-service) with setting the bridge option to the new bridge's name.
The infra containers came up successfully and i was able to deploy and run several services containers.
