### ISSUE TITLE
Support other directories for where docker is installed. 1.2 only works with var/lib/docker

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#6897]
**Rancher Version:**
1.2

Allow support for docker to be installed in a different directory.

**Comment by pulberg** [comment]
Thanks @deniseschannon, this explains my "timeout getting ip address" errors.  And to clarify, are you making a distinction between where docker is "installed" (RHEL7 is /usr/bin/docker) or where a user may specify the docker "working" directory is (in docker options, we specify a separate xfs mounted volume /mnt/dockerdata)

**Comment by ibuildthecloud** [comment]
The history here is that Rancher has never really fully worked when Docker wasn't set to use `/var/lib/docker`, but it mostly worked.  In 1.2 we basically made it a hard requirement to use `/var/lib/docker` because otherwise you'd have a semi-broken install.  In short, that was a bad decision so we are going to go the other way and make non-standard roots work.  To be clear we can probably make this work for Cattle in 1.2.1, but maybe not Kubernetes also.

**Comment by clouderding** [comment]
+1 Same issue here.

**Comment by deniseschannon** [comment]
Found this workaround in the other main issue from @swartel-fa

A workaround I found to solve the issue related to /var/lib/docker is to use a mount point instead of a symlink.
For example:
````
stop docker service
rm -f /var/lib/docker && mkdir -p /var/lib/docker
echo "</path/src>        /var/lib/docker         auto    rw,bind        0       0" >> /etc/fstab
mount -a
start docker service
```

**Comment by flaccid** [comment]
We also always create a new volume and mount it at `/var/lib/docker`. https://github.com/flaccid/rightscripts/blob/master/initialise_and_mount_docker_dir_volume.bash maybe a little handy, just ignore the rs specific part which creates the volume. We have not had any issues with Btrfs and separate volume directly mounted to `/var/lib/docker`.

**Comment by galal-hussein** [comment]
Rancher version: v1.2.1-rc2 

Tested a setup with both rancher server and rancher agent's docker daemon was started with **non** /var/lib/docker runtime directory `/usr/bin/dockerd -g /var/runtime-docker -H fd://` 

The setup was up and running and i was able to deploy containers and services.
