### ISSUE TITLE
Enabling local auth logs "No Auth provider configured"

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#6899]
**Rancher Version:**
v1.2

**Steps to Reproduce:**
1. Enable local auth
2. Check Rancher Server Logs

**Results:** 

```
time="2016-12-02T23:33:09Z" level=info msg="No Auth provider configured" 
time="2016-12-02T23:33:11Z" level=info msg="No Auth provider configured" 
time="2016-12-02T23:33:11Z" level=info msg="No Auth provider configured"
```

**Expected:**

No messages about no auth provider configured.

Note: This is coming from the new auth microservice that we've created in v1.2 that only works with Github and SAML.

**Comment by prachidamle** [comment]
@sangeethah  @deniseschannon we will need a new release of rancher-auth-service to test this, and also change to cattle to point to the new release

**Comment by galal-hussein** [comment]
Tested with master build (14 Dec) and can't see the error messages anymore.

**Comment by galal-hussein** [comment]
@deniseschannon @prachidamle @sangeethah after enabling github authentication, i disabled it and enabled local access, here is what i found in the logs:

```
time="2016-12-13T22:57:44Z" level=info msg=" Auth provider configured githubconfig" 
time="2016-12-13T22:57:45Z" level=info msg=" Auth provider configured githubconfig" 
time="2016-12-13T22:57:46Z" level=info msg=" Auth provider configured githubconfig"
```

**Comment by deniseschannon** [comment]
@galal-hussein We don't support authenticating one provider and then another, so this info message is fine for me.
