### ISSUE TITLE
swarm initialization stuck

### ISSUE THREAD

**Issue by mwaaas** [rancher/rancher#6900]
I have tried to upgrade to rancer v1.2.0 and got stuck at attached screen shot
<img width="826" alt="screen shot 2016-12-03 at 8 46 30 am" src="https://cloud.githubusercontent.com/assets/6207932/20857193/5ff452d2-b935-11e6-99b9-c355f818f5eb.png">

Am seeing this error `exceptionBusy processing [SERVICE.67] will try later`

seeing this error in the logs: 

12/3/2016 11:22:31 AMPublic Swarm not supported. Please re-register this host by setting CATTLE_AGENT_IP to a private IP address.
12/3/2016 11:22:31 AMRetrying set host label swarm=public_unsupported
12/3/2016 11:22:32 AMRetrying set host label swarm=public_unsupported
12/3/2016 11:22:33 AMRetrying set host label swarm=public_unsupported
12/3/2016 11:22:34 AMRetrying set host label swarm=public_unsupported
12/3/2016 11:22:35 AMFailed to set host label swarm=public_unsupported (5 tries)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.2.0` Cattle: `v0.174.3` UI: `v1.2.34` |
|Access|`github` `admin`|
|Orchestration|`Swarm`|
|Route|`swarm-tab.console`|

**Comment by superseb** [comment]
As you stated you upgraded triggered me to this:
```
Known Limitations with Upgrade

Upgrading Swarm environments are not supported. Due to the change from Docker regarding moving Swarm into the Docker engine, we have updated our original Swarm support to the latest Docker 1.12 Swarm.
```

**Comment by mwaaas** [comment]
@superseb  was tying to create a new swarm

**Comment by superseb** [comment]
What Docker version are you running?

**Comment by mwaaas** [comment]
1.12.3

**Comment by mwaaas** [comment]
@superseb Have killed everything (including the host) and created an new environment. still stuck at starting swarm stack. 

checking at the logs of the container that is stuck keep on getting this error.

12/3/2016 12:27:11 PMPublic Swarm not supported. Please re-register this host by setting CATTLE_AGENT_IP to a private IP address.
12/3/2016 12:27:11 PMRetrying set host label swarm=public_unsupported
12/3/2016 12:27:11 PMRetrying set host label swarm=public_unsupported
12/3/2016 12:27:12 PMRetrying set host label swarm=public_unsupported
12/3/2016 12:27:13 PMRetrying set host label swarm=public_unsupported
12/3/2016 12:27:14 PMFailed to set host label swarm=public_unsupported (5 tries)

**Comment by superseb** [comment]
I'm trying to reproduce at the moment, waiting for the machines to come up. I took a look at the catalog and it states it needs to have a private address configured as CATTLE_AGENT_IP. Where are you running and over what interfaces/IP are your hosts configured?

**Comment by mwaaas** [comment]
@superseb  am not sure how to answer that. 

Am running rancher using this docker-compose stack file
db:
  environment:
    - MYSQL_DATABASE=cattle
    - 'MYSQL_PASSWORD=9118z2*9I6&746C6'
    - 'MYSQL_ROOT_PASSWORD=9118z2*9I6&746C6'
    - MYSQL_USER=cattle
  image: 'mysql:5.5'
server:
  environment:
    - CATTLE_DB_CATTLE_MYSQL_HOST=db
    - CATTLE_DB_CATTLE_MYSQL_NAME=cattle
    - CATTLE_DB_CATTLE_MYSQL_PORT=3306
    - 'CATTLE_DB_CATTLE_PASSWORD=9118z2*9I6&746C6'
    - CATTLE_DB_CATTLE_USERNAME=cattle
  image: 'rancher/server:stable'
  links:
    - db
  ports:
    - '80:8080'
  volumes:
    - '/var/run/docker.sock:/var/run/docker.sock'

and have added azure host.

**Comment by superseb** [comment]
Remove your passwords just in case :)

**Comment by mwaaas** [comment]
@superseb  thanks, have removed.

**Comment by superseb** [comment]
Ok, so reproduced on Amazon. You can't create a Swarm over a public network as stated https://github.com/rancher/community-catalog/tree/master/infra-templates/swarm. For your case you'll need to configure "Private IP" and tick "Use Private IP To Connect". Is your server also running on Azure? If you created it through the Azure portal you should already have a private network available which is connected to your server.

**Comment by mwaaas** [comment]
Have created a new instance ticked "Use Private IP" Its now stuck here 
<img width="294" alt="screen shot 2016-12-03 at 1 21 06 pm" src="https://cloud.githubusercontent.com/assets/6207932/20858655/4b784338-b95b-11e6-89c0-b43a69f4bfd0.png">

**Comment by superseb** [comment]
Same here, trying to figure out what's going wrong.
```
time="2016-12-03T10:25:06Z" level=info msg="stderr: Error creating machine: Error detecting OS: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded" resourceId=1ph2
time="2016-12-03T10:25:06Z" level=info msg="starting cleanup..." machine name=host02
time="2016-12-03T10:25:07Z" level=info msg="cleanup successful" machine name=host02
time="2016-12-03T10:25:07Z" level=error msg="Error processing event" err="Error detecting OS: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded" eventId=aa4f5f59-3281-4382-8a66-0f1cc1f
da8d8 eventName="physicalhost.create;handler=goMachineService" resourceId=1ph2
```

**Comment by superseb** [comment]
Mine is getting registered with the public IP, can you paste the logging of the agent in here so I can compare?

I only got it to work to manually create a second machine in Azure, install Docker on it and add it through Add host -> Custom and specify the private IP in the "Optional: Public IP" box so it gets added to CATTLE_AGENT_IP when registering the agent.

**Comment by mwaaas** [comment]
Mine is stuck at waiting to ssh.
Here are the logs


[server-1]2016-12-03T11:21:14.972542600Z time="2016-12-03T11:21:14Z" level=info msg="Creating Machine" eventId=6d1fd71f-eae1-4583-983e-a8911cad006a resourceId=1ph6 
[server-1]2016-12-03T11:21:14.985646700Z time="2016-12-03T11:21:14Z" level=info msg="Cmd slice: [create -d azure --engine-install-url https://releases.rancher.com/install-docker/1.12.sh --azure-availability-set docker-machine --azure-client-id 8644b2f3-b416-43d9-8dfa-7d7b3fa80cc8 --azure-client-secret 7bjzhUwRBQh0VL8CIXKOzll4Zgm+dU+a --azure-docker-port 2376 --azure-environment AzurePublicCloud --azure-image canonical:UbuntuServer:16.04.0-LTS:latest --azure-location northeurope --azure-open-port 500/udp --azure-open-port 4500/udp --azure-resource-group docker-machine-swarm --azure-size Standard_D2_v2 --azure-ssh-user docker-user --azure-storage-type Standard_LRS --azure-subnet docker-machine --azure-subnet-prefix 192.168.0.0/16 --azure-subscription-id dc24e90c-cbd1-4ea2-8ab9-53a34f483b6b --azure-use-private-ip --azure-vnet docker-machine-vnet swarm-host-1]" 
[server-1]2016-12-03T11:21:15.190793800Z time="2016-12-03T11:21:15Z" level=info msg="stdout: Creating CA: /var/lib/cattle/machine/289224f6-b88b-4898-939b-af5e0c63b66f/certs/ca.pem" resourceId: =1ph6 
[server-1]2016-12-03T11:21:15.899475800Z time="2016-12-03T11:21:15Z" level=info msg="stdout: Creating client certificate: /var/lib/cattle/machine/289224f6-b88b-4898-939b-af5e0c63b66f/certs/cert.pem" resourceId: =1ph6 
[server-1]2016-12-03T11:21:16.417796600Z 2016-12-03 11:21:16,417 ERROR [6ca38a34-1638-4570-8e7f-c90664b71600:7205] [instance:358] [instance.start->(InstanceStart)] [] [ecutorService-2] [i.c.p.process.instance.InstanceStart] Failed to Scheduling for instance [358] 
[server-1]2016-12-03T11:21:17.246586300Z time="2016-12-03T11:21:17Z" level=info msg="stdout: Running pre-create checks..." resourceId: =1ph6 
[server-1]2016-12-03T11:21:18.114827100Z time="2016-12-03T11:21:18Z" level=info msg="stdout: (swarm-host-1) Completed machine pre-create checks." resourceId: =1ph6 
[server-1]2016-12-03T11:21:18.115362700Z time="2016-12-03T11:21:18Z" level=info msg="stdout: Creating machine..." resourceId: =1ph6 
[server-1]2016-12-03T11:21:18.123508200Z time="2016-12-03T11:21:18Z" level=info msg="stdout: (swarm-host-1) Querying existing resource group.  name=\"docker-machine-swarm\"" resourceId: =1ph6 
[server-1]2016-12-03T11:21:18.254634100Z time="2016-12-03T11:21:18Z" level=info msg="stdout: (swarm-host-1) Creating resource group.  name=\"docker-machine-swarm\" location=\"northeurope\"" resourceId: =1ph6 
[server-1]2016-12-03T11:21:18.781587600Z time="2016-12-03T11:21:18Z" level=info msg="stdout: (swarm-host-1) Configuring availability set.  name=\"docker-machine\"" resourceId: =1ph6 
[server-1]2016-12-03T11:21:19.148177400Z time="2016-12-03T11:21:19Z" level=info msg="stdout: (swarm-host-1) Configuring network security group.  name=\"swarm-host-1-firewall\" location=\"northeurope\"" resourceId: =1ph6 
[server-1]2016-12-03T11:21:23.807871500Z 2016-12-03 11:21:23,807 ERROR [6d5e838d-3e8b-4db9-8e27-8917bec3026d:7216] [instance:359] [instance.start->(InstanceStart)] [] [ecutorService-2] [i.c.p.process.instance.InstanceStart] Failed to Scheduling for instance [359] 
[server-1]2016-12-03T11:21:38.731784200Z 2016-12-03 11:21:38,731 ERROR [1806f761-fe4f-403e-91ab-bcbcdd3b7268:7226] [instance:360] [instance.start->(InstanceStart)] [] [ecutorService-3] [i.c.p.process.instance.InstanceStart] Failed to Scheduling for instance [360] 
[server-1]2016-12-03T11:21:39.509801300Z time="2016-12-03T11:21:39Z" level=info msg="stdout: (swarm-host-1) Querying if virtual network already exists.  name=\"docker-machine-vnet\" rg=\"docker-machine-swarm\" location=\"northeurope\"" resourceId: =1ph6 
[server-1]2016-12-03T11:21:39.541325900Z time="2016-12-03T11:21:39Z" level=info msg="stdout: (swarm-host-1) Creating virtual network.  name=\"docker-machine-vnet\" rg=\"docker-machine-swarm\" location=\"northeurope\"" resourceId: =1ph6 
[server-1]2016-12-03T11:21:45.822903300Z time="2016-12-03T11:21:45Z" level=info msg="stdout: (swarm-host-1) Configuring subnet.  name=\"docker-machine\" vnet=\"docker-machine-vnet\" cidr=\"192.168.0.0/16\"" resourceId: =1ph6 
[server-1]2016-12-03T11:21:49.046664200Z 2016-12-03 11:21:49,046 ERROR [e89ecec7-4b14-436c-86e4-d20796518047:7269] [instance:361] [instance.start->(InstanceStart)] [] [ecutorService-1] [i.c.p.process.instance.InstanceStart] Failed to Scheduling for instance [361] 
[server-1]2016-12-03T11:21:52.061095500Z time="2016-12-03T11:21:52Z" level=info msg="stdout: (swarm-host-1) Creating public IP address.  name=\"swarm-host-1-ip\" static=false" resourceId: =1ph6 
[server-1]2016-12-03T11:21:52.994290500Z 2016-12-03 11:21:52,992 ERROR [7c9b4996-bae9-4af2-b59b-8c9355661e79:7288] [instance:362] [instance.start->(InstanceStart)] [] [ecutorService-1] [i.c.p.process.instance.InstanceStart] Failed to Scheduling for instance [362] 
[server-1]2016-12-03T11:21:58.582005700Z time="2016-12-03T11:21:58Z" level=info msg="stdout: (swarm-host-1) Creating network interface.  name=\"swarm-host-1-nic\"" resourceId: =1ph6 
[server-1]2016-12-03T11:21:59.592527600Z time="2016-12-03T11:21:59Z" level=info msg="stdout: (swarm-host-1) Creating storage account.  location=\"northeurope\" sku=Standard_LRS name=\"vhdse6g83mhxn2l5fjc9wh0b\"" resourceId: =1ph6 
[server-1]2016-12-03T11:22:08.180522300Z 2016-12-03 11:22:08,180 ERROR [9541effb-5b39-4afd-ba51-ed15350d17bf:7299] [instance:363] [instance.start->(InstanceStart)] [] [ecutorService-1] [i.c.p.process.instance.InstanceStart] Failed to Scheduling for instance [363] 
[server-1]2016-12-03T11:22:15.251315200Z 2016-12-03 11:22:15,251 ERROR [90694faf-e39d-41b5-a0d8-d0aa8c6479c1:7310] [instance:364] [instance.start->(InstanceStart)] [] [ecutorService-1] [i.c.p.process.instance.InstanceStart] Failed to Scheduling for instance [364] 
[server-1]2016-12-03T11:22:23.141333900Z 2016-12-03 11:22:23,141 ERROR [bac1d839-cc0b-4166-bbb3-b09b6ebb833c:7321] [instance:365] [instance.start->(InstanceStart)] [] [ecutorService-1] [i.c.p.process.instance.InstanceStart] Failed to Scheduling for instance [365] 
[server-1]2016-12-03T11:22:38.344767100Z time="2016-12-03T11:22:38Z" level=info msg="stdout: (swarm-host-1) Creating virtual machine.  name=\"swarm-host-1\" location=\"northeurope\" size=\"Standard_D2_v2\" username=\"docker-user\" osImage=\"canonical:UbuntuServer:16.04.0-LTS:latest\"" resourceId: =1ph6 
[server-1]2016-12-03T11:22:39.351171800Z 2016-12-03 11:22:39,351 ERROR [d390a242-4368-4c32-9562-83cd94ad53e8:7339] [instance:366] [instance.start->(InstanceStart)] [] [ecutorService-6] [i.c.p.process.instance.InstanceStart] Failed to Scheduling for instance [366] 
[server-1]2016-12-03T11:22:46.510015900Z 2016-12-03 11:22:46,509 ERROR [4dd70ed3-3075-45ba-a6e3-dd22003df625:7355] [instance:367] [instance.start->(InstanceStart)] [] [ecutorService-6] [i.c.p.process.instance.InstanceStart] Failed to Scheduling for instance [367] 
[server-1]2016-12-03T11:22:53.321212900Z 2016-12-03 11:22:53,321 ERROR [f0e4f044-d24e-415d-acf4-b7f833a35028:7412] [instance:368] [instance.start->(InstanceStart)] [] [ecutorService-6] [i.c.p.process.instance.InstanceStart] Failed to Scheduling for instance [368] 
[server-1]2016-12-03T11:23:07.376481100Z 2016-12-03 11:23:07,376 ERROR [c99c52e6-4355-450c-a60a-62cec9fa437e:7423] [instance:369] [instance.start->(InstanceStart)] [] [ecutorService-6] [i.c.p.process.instance.InstanceStart] Failed to Scheduling for instance [369] 
[server-1]2016-12-03T11:23:15.584029800Z 2016-12-03 11:23:15,583 ERROR [081ea6fb-51b7-4460-a4c3-0a8c2bee2c3e:7434] [instance:370] [instance.start->(InstanceStart)] [] [ecutorService-6] [i.c.p.process.instance.InstanceStart] Failed to Scheduling for instance [370] 
[server-1]2016-12-03T11:23:24.457917100Z 2016-12-03 11:23:24,457 ERROR [3d2af60c-4907-416a-9332-050bfe110841:7445] [instance:371] [instance.start->(InstanceStart)] [] [ecutorService-6] [i.c.p.process.instance.InstanceStart] Failed to Scheduling for instance [371] 
[server-1]2016-12-03T11:23:37.603764000Z 2016-12-03 11:23:37,603 ERROR [d7a37d09-1830-4259-8635-0c09148c15b8:7456] [instance:372] [instance.start->(InstanceStart)] [] [ecutorService-6] [i.c.p.process.instance.InstanceStart] Failed to Scheduling for instance [372] 
[server-1]2016-12-03T11:23:45.606277600Z 2016-12-03 11:23:45,606 ERROR [d50e03e8-61dd-491d-8792-9834a16f694d:7467] [instance:373] [instance.start->(InstanceStart)] [] [ecutorService-6] [i.c.p.process.instance.InstanceStart] Failed to Scheduling for instance [373] 
[server-1]2016-12-03T11:23:53.610556200Z 2016-12-03 11:23:53,610 ERROR [b1bad1ca-5b14-4c1d-a4ca-2dc2e1cb761e:7514] [instance:374] [instance.start->(InstanceStart)] [] [ecutorService-5] [i.c.p.process.instance.InstanceStart] Failed to Scheduling for instance [374] 
[server-1]2016-12-03T11:23:58.912519200Z time="2016-12-03T11:23:58Z" level=info msg="stdout: Waiting for machine to be running, this may take a few minutes..." resourceId: =1ph6 
[server-1]2016-12-03T11:23:59.151930600Z time="2016-12-03T11:23:59Z" level=info msg="stdout: Detecting operating system of created instance..." resourceId: =1ph6 
[server-1]2016-12-03T11:23:59.152040000Z time="2016-12-03T11:23:59Z" level=info msg="stdout: Waiting for SSH to be available..." resourceId: =1ph6 
[server-1]2016-12-03T11:24:08.860742100Z 2016-12-03 11:24:08,860 ERROR [e4872e56-eb77-427f-bb2a-3ccaf047f1a8:7537] [instance:375] [instance.start->(InstanceStart)] [] [ecutorService-6] [i.c.p.process.instance.InstanceStart] Failed to Scheduling for instance [375] 
[server-1]2016-12-03T11:24:15.787277800Z 2016-12-03 11:24:15,787 ERROR [4bc0b603-7d4c-4d7c-be2c-2f2789a205b5:7550] [instance:376] [instance.start->(InstanceStart)] [] [ecutorService-6] [i.c.p.process.instance.InstanceStart] Failed to Scheduling for instance [376] 
[server-1]2016-12-03T11:24:26.662164200Z 2016-12-03 11:24:26,661 ERROR [a7f8a846-1653-44b0-9ca9-ef6563b0d8f0:7566] [instance:377] [instance.start->(InstanceStart)] [] [ecutorService-9] [i.c.p.process.instance.InstanceStart] Failed to Scheduling for instance [377] 
[server-1]2016-12-03T11:24:37.974488000Z 2016-12-03 11:24:37,966 ERROR [6b255029-19c8-45c2-8d1b-b6e5ed43082c:7579] [instance:378] [instance.start->(InstanceStart)] [] [ecutorService-9] [i.c.p.process.instance.InstanceStart] Failed to Scheduling for instance [378]

**Comment by superseb** [comment]
Remove the azure credentials :)

**Comment by superseb** [comment]
The server is also running on Azure right? You'll need to enter the correct information when creating the host so it gets created in the correct subnet. Now it's creating all the defaults which won't be sufficient I guess. You can see all the needed information in the Azure portal.

But still, I tried this and creating the machine works but registering the agent registers the public IP as far as I can see.

**Comment by mwaaas** [comment]
The server is running in Azure but I had provision it using docker-cloud.

**Comment by superseb** [comment]
Ok so I tried from scratch and this works:

- Set the Host Registration URL on your rancher server to the private IP address of the server.
- Add Azure host through the GUI and match all the fields (i.e. Resource Group, Subnet, VNet etc) with the current server, enter a free private IP address and tick "Use Private IP To Connect".
- Wait for the machine to be provisioned and registered with the Private IP.
- Swarm will be created.

If this is how it should work it's not a bug, Swarm mode over public IP is not (yet) supported.

**Comment by superseb** [comment]
Need any more help @mwaaas ?

**Comment by mwaaas** [comment]
@superseb  No thanks am good

**Comment by ifeelingz** [comment]
I see this issue as well.
Droplets on using CentOS 7.3

**Comment by superseb** [comment]
@ifeelingz Can you create a new issue with the issue template? Just hit new issue to get the template.

**Comment by LLParse** [comment]
@ifeelingz @superseb @mwaaas Docker 1.13 will allow us to make use of swarm over public networks. That release is slated for January 10th - we will release the new swarm template shortly thereafter.

**Comment by ifeelingz** [comment]
I solve this problem now By connecting via Private Network.

Thank you very much

**Comment by mwaaas** [comment]
@LLParse  how do you know docker 1.13 will allow use of swarm over public network and its not mentioned in this change release https://github.com/docker/docker/blob/master/CHANGELOG.md#swarm-mode

**Comment by LLParse** [comment]
@mwaaas https://github.com/docker/docker/issues/27647 Docker relaxed some validation which allows us to specify advertise address while still auto-detecting the listen address. I would assume this is not interesting enough to include in release notes - users manually setting up swarm over public IPs would identify and set the listen address manually. Rancher lacks this information (all we know is CATTLE_AGENT_IP, which usually is not the listen address), and it felt dirty ripping out the autodetection code from swarm, just to pass the result back to the swarm init/join call.

As for your second question - Rancher will provide a catalog and authentication. Additionally, Rancher will maintain your swarm setup by promoting/demoting workers/manager to maintain resilience which ultimately prevents downtime without user intervention. Portainer may end up being part of the product in the future.

**Comment by mwaaas** [comment]
Thanks @LLParse  so you would advice to use Portainer

**Comment by LLParse** [comment]
@mwaaas Hang tight...
