### ISSUE TITLE
 Occupation cpu too high

### ISSUE THREAD

**Issue by wiki-qi** [rancher/rancher#6902]
**Rancher Version:1.2

**Docker Version:1.11.2

**OS and where are the hosts located? (cloud, bare metal, etc):centos7 

问题 ：
root      5163  5161 99 19:20 ?        00:01:29 java -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -Xms128m -Xmx4g -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/var/lib/cattle/logs -Dlogback.bootstrap.level=WARN -cp /usr/share/cattle/b1798fc003d579eeafb723fc2a958c61:/usr/share/cattle/b1798fc003d579eeafb723fc2a958c61/etc/cattle io.cattle.platform.launcher.Main

占用cpu太大

**Comment by vincent99** [comment]
@wiki-qi this is not enough information for us to do anything with.  How high, doing what, what does the processes tab show , etc?  Also 1.2.0 had some specific performance issues so you will want to at least upgrade to the newest 1.2.x, if not 1.3 or 1.4.
