### ISSUE TITLE
rancher 1.2: create custom overlay network for a stack

### ISSUE THREAD

**Issue by derDieDasJojo** [rancher/rancher#6903]
with docker you can create custom overlay networks to encapsulate services from each other.
With rancher 1.2 and docker1.12 basically the possibilities should be there to also to that.

i tried deploying an second ipsec system stack within an cattle environment and hoped it would show up as a possible network option when creating a new Service.
But it is not possible to simply deploy ipsec a second time from the catalog.
So i made a copy of the docker-compose.yml and rancher-compose.yml and tried it.
But it did not work.
What changes are neede to be able to deploy a second isolated ipsec overlay network ?

**Rancher Version:** 1.2

**Docker Version:** 1.12

**OS and where are the hosts located? (cloud, bare metal, etc):** coreos

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** cattle or swarm

**Comment by vincent99** [comment]
Rancher supports one overlay network per environment.  Future versions will have options to control what things inside of that network can talk to each other, rather than creating multiple physical networks and the overhead associated with that.

**Comment by derDieDasJojo** [comment]
al rights. sounds like great plans.
exited to see them :+1:
