### ISSUE TITLE
1.2.0 : Stacks page not displaying in french

### ISSUE THREAD

**Issue by Dremor** [rancher/rancher#6904]
The stack page does not display when using the french localization.

Steps : 
-> switch to french from any page (other than the "stack" page)
-> go to the "stack" page

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.2.0` Cattle: `v0.174.3` UI: `v1.2.34` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`host.containers`|

**Comment by vincent99** [comment]
There's some errors in the translation file, and unfortunately some kinds of errors can prevent the page from rendering.  Will be fixed in the next release.

**Comment by tfiduccia** [comment]
Version - master 11/13
Verified fixed
