### ISSUE TITLE
1.2.0 : ghost containers

### ISSUE THREAD

**Issue by Dremor** [rancher/rancher#6905]
Some ghost containers randomly appear, no matter for any setting. On this image, the Gitlab service should limited to the host with a "backend=true" label, and should only have 1 container.same goes for the balancer, which is limited to hosts with a "backend=true" label.

![](https://framapic.org/wRhf95clgWxi/znQeWgO5bR6L)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.2.0` Cattle: `v0.174.3` UI: `v1.2.34` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`hosts.index`|

**Comment by vincent99** [comment]
Did you remove and re-add that host?  `r-name-stack-num-uuid` comes from Rancher and us what containers are actually named if you look at `docker ps`, but the only way you'd see it in the UI was if they were imported on host as an existing container.  They're not really part of a stack but still have the labels that makes the UI think they are.

**Comment by Dremor** [comment]
No, the two host are freshly (re-)installed.

**Comment by aemneina** [comment]
on a fresh re-install, did you happen to remove `/var/lib/rancher` folder on those hosts? I believe there's some cached state in that folder that might interfere here.

**Comment by StrongMonkey** [comment]
I also saw the ghost containers when i re-added my host to cattle.

**Comment by IsaacJT** [comment]
I am also seeing this issue with an environment upgraded to 1.2.0 from 1.1.4.

**Comment by vincent99** [comment]
Can anyone reproduce this in 1.4?

**Comment by IsaacJT** [comment]
@vincent99 yes I'm still seeing this issue in v1.4.0.

![bildschirmfoto von 2017-02-07 14-51-05](https://cloud.githubusercontent.com/assets/1284322/22693758/e3c0a8d4-ed44-11e6-8bd7-14ca72722c5c.png)

**Comment by yoonation** [comment]
Hello, 
First time user of rancher and just testing on my local environment on my mac machine using https://github.com/rancher/10acre-ranch to get things up and running. Thanks vincent99 for that script. I also just want to note that I see these ghost containers in v1.4.0. Also some random containers generated by some script. Not sure if this is something with 10acre-ranch. Attached screenshots.
![screen shot 2017-02-12 at 2 33 54 pm](https://cloud.githubusercontent.com/assets/1483341/22866284/f12d22aa-f130-11e6-83e8-bcc261e15c39.png)
![screen shot 2017-02-12 at 2 34 03 pm](https://cloud.githubusercontent.com/assets/1483341/22866285/f12d901e-f130-11e6-9b13-e98eb4f1639d.png)

**Comment by aemneina** [comment]
These are either boot strap containers, stale data in `/var/lib/rancher` (when a host is reused), or containers spun up outside of rancher. They could also be stopped containers that should/need be deleted. For the most part a non-issue. Going to close this out.
