### ISSUE TITLE
unable to start rancher server --- fresh install

### ISSUE THREAD

**Issue by ka2er** [rancher/rancher#6906]
**Rancher Version:**
latest / 1.2.0
**Docker Version:**
```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 21:51:24 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 21:51:24 2016
 OS/Arch:      linux/amd64
```
**OS and where are the hosts located? (cloud, bare metal, etc):**
Debian
```
cat /etc/debian_version
7.11
```

Linux 3.16.0-0.bpo.4-amd64 #1 SMP Debian 3.16.36-1+deb8u2~bpo70+1 (2016-10-19) x86_64 GNU/Linux
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node, internal DB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
cattle
**Steps to Reproduce:**
Try to launch a fresh rancher server for the first time (installation process)
**Results:** 
```
sudo docker -D run -p 8181:8080 rancher/server:latest
DEBU[0010] framesize: 100
161203 20:41:21 [Note] /usr/sbin/mysqld (mysqld 5.5.53-0ubuntu0.14.04.1) starting as process 24 ...
DEBU[0010] framesize: 191
161203 20:41:21 [Warning] Using unique option prefix myisam-recover instead of myisam-recover-options is deprecated and will be removed in a future release. Please use the full name instead.
DEBU[0010] framesize: 55
161203 20:41:21 [Note] Plugin 'FEDERATED' is disabled.
DEBU[0010] framesize: 53
/usr/sbin/mysqld: Table 'mysql.plugin' doesn't exist
DEBU[0010] framesize: 98
161203 20:41:21 [ERROR] Can't open the mysql.plugin table. Please run mysql_upgrade to create it.
DEBU[0010] framesize: 232
161203 20:41:21 InnoDB: The InnoDB memory heap is disabled
161203 20:41:21 InnoDB: Mutexes and rw_locks use GCC atomic builtins
161203 20:41:21 InnoDB: Compressed tables use zlib 1.2.8
161203 20:41:21 InnoDB: Using Linux native AIO
DEBU[0010] framesize: 15
161203 20:41:21DEBU[0010] framesize: 49
 InnoDB: Initializing buffer pool, size = 128.0M
DEBU[0010] framesize: 64
161203 20:41:21 InnoDB: Completed initialization of buffer pool
DEBU[0010] framesize: 374
161203 20:41:21  InnoDB: Operating system error number 2 in a file operation.
InnoDB: The error means the system cannot find the path specified.
InnoDB: If you are installing InnoDB, remember that you must create
InnoDB: directories yourself, InnoDB does not create them.
InnoDB: File name ./ibdata1
InnoDB: File operation call: 'create'.
InnoDB: Cannot continue operation.
DEBU[0010] framesize: 74
s6-svscanctl: fatal: unable to control /service: supervisor not listening
DEBU[0011] Corrupted prefix: []
DEBU[0011] [hijack] End of stdout
```
---
```
sudo docker ps -a
CONTAINER ID        IMAGE                      COMMAND                  CREATED             STATUS                      PORTS                    NAMES
9dc1b0b0927c        rancher/server:latest      "/usr/bin/entry /usr/"   40 seconds ago      Exited (0) 28 seconds ago
```
unable to start
**Expected:**

rancher server start

---
additionnal infos 
```
cat /etc/resolv.conf
search local
nameserver 192.168.1.1
```
```
cat /etc/nsswitch.conf
# /etc/nsswitch.conf
#
# Example configuration of GNU Name Service Switch functionality.
# If you have the `glibc-doc-reference' and `info' packages installed, try:
# `info libc "Name Service Switch"' for information about this file.

passwd:         compat
group:          compat
shadow:         compat

hosts:          files mdns4_minimal [NOTFOUND=return] dns mdns4
networks:       files

protocols:      db files
services:       db files
ethers:         db files
rpc:            db files

netgroup:       nis
```

host IP is **192.168.1.68** and the server is bare metal on NATed network

**Comment by muthiyalu** [comment]
I am having issues with install as well:

On Digital Ocean and Google Compute . It gets stuck here :

ime="2016-12-03T21:24:37Z" level=info msg="Creating schema machine, roles [service]" id=1ds29 
time="2016-12-03T21:24:38Z" level=info msg="Creating schema host, roles [service]" id=1ds30 
time="2016-12-03T21:24:38Z" level=info msg="Creating schema machine, roles [project member owner]" id=1ds31 
time="2016-12-03T21:24:39Z" level=info msg="Creating schema host, roles [project member owner]" id=1ds32 
time="2016-12-03T21:24:39Z" level=info msg="Creating schema machine, roles [admin user readAdmin]" id=1ds33 
time="2016-12-03T21:24:39Z" level=info msg="Creating schema host, roles [admin user readAdmin]" id=1ds34 
time="2016-12-03T21:24:39Z" level=info msg="Creating schema machine, roles [readonly]" id=1ds35 
time="2016-12-03T21:24:40Z" level=info msg="Creating schema host, roles [readonly]" id=1ds36

**Comment by Dmitry1987** [comment]
+1  https://github.com/rancher/rancher/issues/7068  ,  in my case I try to launch with external DB for HA.. also doesn't work. Totally weird, because I just installed another cluster 2 weeks ago and it was ok.

**Comment by vincent99** [comment]
@ka2er What is the full command you're using to start the server container?  Does this still happen in 1.4?  What makes you think it has anything to do with DNS?

**Comment by jakubknejzlik** [comment]
@vincent99 in my case I'm running this on AWS EC2 Ubuntu AMI (ami-3f1bd150)

The commands are:

- `curl -fsSL https://get.docker.com/ | sh`

- `sudo docker run -d --restart=unless-stopped -p 80:8080 rancher/server`

The container stops at:
`level=info msg="Creating schema host, roles [readonly]" id=1ds36`

**Comment by jakubknejzlik** [comment]
@muthiyalu On latest version `v1.5.1` this is the latest log message for installation...maybe some sort of "server is up and running" should make thinks clear :)

**Comment by vincent99** [comment]
There is one, it's just not there last line because other things happen after that.
