### ISSUE TITLE
[rancher-ebs failure]:  Upgrading (Expected state running but got error: Error response from daemon: create znc-data: VolumeDriver.Create: size is required)

### ISSUE THREAD

**Issue by stormerider** [rancher/rancher#6908]
**Rancher Version:**
1.2.0
**Docker Version:**
1.12.3
**OS and where are the hosts located? (cloud, bare metal, etc):**
RancherOS v0.7.1 in AWS
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher with external RDS DB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
1. Add the Rancher EBS catalog item and wait for the stack to finish coming online.
2. Create a new EBS volume from Infrastructure > Storage.
3. Take an existing ZNC service that was using an EFS volume and update it with the new EBS volume.

**Results:** 
Service shows error: Upgrading (Expected state running but got error: Error response from daemon: create znc-data: VolumeDriver.Create: size is required)
AWS shows no new EBS volume created.
**Expected:**
Volume is created successfully. If a size requirement is necessary when creating the storage volume, it's totally not apparent as to how to do so.

**Comment by kl4n4** [comment]
+1 the current EBS volume creation in rancher 1.2.0 does not show any information how to properly create one - neither are the any blog posts or other documentation on how to use these new storage drivers

**Comment by mccricardo** [comment]
f you're using `rancher-compose` CLI, you'll need to add to your `docker-compose.yml`:

```
volumes:
  volume-name:
    driver: rancher-ebs
    external: false
    driver_opts:
      size: <integer-value>
```

**Comment by stormerider** [comment]
I was just using the rancher UI, but I assume i can just set a size key
there. The bigger problem I see that needs to be addressed is that if this
is required to work, it should be explicitly defined in the catalog, not
just available to set as an advanced option. And since there's no
documentation around this (at least that I could find), I had no way of
knowing that that was what needed to be done.

**Comment by longwuyuan** [comment]
@mccricardo , hi, humble request for screenshot on precisely where and how to add that "size" in Rancher-GUI. Not sure if it is a label or appended to mount etc.. Stuck on implementation because of this (understand it is experimentatl)

**Comment by peetasan** [comment]
@longwuyuan 
Finally I found out. When you create a volume in Infrastructure/Storage/Add Volume you need to specify the driver option `size`. 

<img width="1245" alt="screen shot 2017-04-26 at 17 11 57" src="https://cloud.githubusercontent.com/assets/2129354/25441980/11382d0e-2aa4-11e7-8a94-7f566691a9e7.png">

**Comment by aemneina** [comment]
Will close this out, holler if you think otherwise.

**Comment by truedat101** [comment]
size units are MB?  GB?  This could be useful to add to the Rancher EBS docs.

**Comment by matfiz** [comment]
It is in GB, see https://github.com/rancher/convoy/blob/master/ebs/ebs.go#L323. I agree docs should be updated.
