### ISSUE TITLE
not showing all docker containers

### ISSUE THREAD

**Issue by dcnl1980** [rancher/rancher#6911]
**Rancher Version:**
1.2.0
**Docker Version:**
1.11.2
**OS and where are the hosts located? (cloud, bare metal, etc):**
CoreOS
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Just Rancher with mysql backend
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
Clean installation, deleted the /var/lib/rancher and /var/lib/docker
**Results:** 
Not showing all containers
**Expected:**
Showing all containers

I install the agent on the same server as Rancher and used the public 'internet' IP. With docker-compose I install some extra service, the containers are starting, but they are not visible in Rancher.

**Comment by joceluss** [comment]
Same problem here... was ok before Rancher 1.2

**Comment by dcnl1980** [comment]
I think we are the only one which have that, since the rest is not responding ;-). I will try v1.2.0-rc1 tonight to see if this will be changed. It would be great if it's working so I can see my stacks and attach haproxy on this from the Rancher interface. So other readers, please help us !!

**Comment by dcnl1980** [comment]
Still the same with the 1.2.0-rc1 candidate. I notice that their are also r_ containers. Is there an easy way to detect the containers between Rancher and Docker, or to delete the cache? 

![screen shot 2016-12-07 at 21 36 09](https://cloud.githubusercontent.com/assets/8920270/20985613/816b79e8-bcc5-11e6-9749-f35efd2ad214.png)

**Comment by fprieur** [comment]
+1

**Comment by juocal** [comment]
Same problem here! Docker Images started via compose are not detected by rancher at all.

**Comment by joceluss** [comment]
Downgraded to previous version... and now it's ok!

**Comment by StrongMonkey** [comment]
I tested with master and found agent is doing reporting the status for those containers. Wondering if it is a bug in cattle somewhere else.

**Comment by dcnl1980** [comment]
Is it possible to try this with an old agent and see if there is a difference? It's mostly with containers which are created with docker-compose.

**Comment by tbohnen** [comment]
@dcnl1980 happy to try downgrading agent, would it be possible to downgrade agent without downgrading rancher?

I did see a flicker of a container in the ui and then it went away again.

**Comment by MartinBucko** [comment]
+1
```
Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2+deb8u3 (2016-07-02) x86_64 GNU/Linux
Docker version 1.13.1, build 092cba3 - also not working on previous docker version ~1.13.0
Containers started with two docker-compose files.. 
CATTLE_RANCHER_SERVER_VERSION=v1.4.0
CATTLE_CATTLE_VERSION=v0.176.8
CATTLE_RANCHER_COMPOSE_VERSION=v0.12.2
....
```

**Comment by cjellick** [comment]
@MartinBucko @tbohnen @dcnl1980 @juocal @fprieur are you all on rancher 1.2.X or have any of you seen this in 1.3/1.4

Also, if you could post a full docker-compose/rancher-compose for a service that is falling victim to this bug or otherwise give more detailed steps to reproduce, that would be helpful.

**Comment by StrongMonkey** [comment]
@sangeethah The fix is in master now.

**Comment by sangeethah** [comment]
Tested with rancher server build from master.

Created containers using  ```docker-compose up``` command with the following docker-compose.yml
```
version: '2'
services:
  web:
    image: nginx
    depends_on:
      - db
      - redis
  redis:
    image: redis
  db:
    image: postgres
```

nginx/redis/postgres containers from this host get synced to rancher-server as standalone containers on this host.

Changes made to these containers from host (stop/start/delete) are reflected correctly on the rancher-server.

Changes made to these containers from rancher-server UI (stop/start/delete) are reflected correctly on the host.

**Comment by juocal** [comment]
@sangeethah 
Verified with rancher/agent:v1.5.0-rc4 and rancher/agent:v1.2.1  
Works now! Thanks!
