### ISSUE TITLE
Cannot add new host "Failed to subscribeGet ..." 

### ISSUE THREAD

**Issue by truongdo** [rancher/rancher#6912]
This is a newly created rancher server 1.2.0.

When I added a new host, which run docker 1.12.1 ubuntu 16.10, I got the following error on meta-data containers,

12/5/2016 10:08:36 AMtime="2016-12-05T01:08:36Z" level=fatal msg="Failed to subscribeGet http://url/v2-beta: dial tcp: lookup rurl on 127.0.1.1:53: read udp 127.0.0.1:35758->127.0.1.1:53: read: connection refused"

Noted that 3 other hosts have been added successfully, the problem only happened when I added the fourth one.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.2.0` Cattle: `v0.174.3` UI: `v1.2.34` |
|Access|`github` `admin`|
|Orchestration|`Cattle`|
|Route|`hosts.index`|

**Comment by vincent99** [comment]
The DNS server for the container is set to a loopback IP (127.0.1.1), so it can't resolve anything.  Later releases of Rancher have defense against this and will use default servers if none of the provided are valid.
