### ISSUE TITLE
Expected state running but got error: Timeout getting IP address

### ISSUE THREAD

**Issue by truongdo** [rancher/rancher#6914]
Start once container cannot get IP address, the error is

Expected state running but got error: Timeout getting IP address

It does not always happen, and sometimes it automatically fixed after reconcile several times. 

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.2.0` Cattle: `v0.174.3` UI: `v1.2.34` |
|Access|`github` `admin`|
|Orchestration|`Cattle`|
|Route|`stack.index`|

**Comment by adammwood** [comment]
We're also experiencing this issue with 1.2.

Prior to 1.2, services on new hosts would come up within 2-3 minutes, however we're now seeing delays of up to 20 minutes with services trying to start but failing with 'Timeout getting IP'. The issue appears to rectify itself after around 15-20 minutes of containers restarting.

**Comment by clouderding** [comment]
+1

**Comment by BNUZ-YLSY** [comment]
It seems this issue has been fixed with **v1.2.1**, tried to upgrade your Rancher version. -> #6897

**Comment by mcanevet** [comment]
Still having the issue with 1.2.1...

**Comment by defunctzombie** [comment]
Also seeing this issue *after* upgrading to 1.2.1 (was not seeing it before with 1.2.0)

**Comment by DanielDent** [comment]
I'm seeing this on 1.2.1 while upgrading the 'network-services' stack from catalog version v0.0.5 to v0.0.6. The upgrade simply isn't completing.

**Comment by defunctzombie** [comment]
The network services stack upgrade is what got me.

Anyone reading this *DO NOT* upgrade network services, you will spend hours migrating that environment over to a new one as it will be (in my experience) un-recoverable.

**Comment by justsml** [comment]
Thx @defunctzombie I wish I'd seen your message when you originally posted 😿 🔮

**Comment by JaviSabalete** [comment]
+1

**Comment by pschrammel** [comment]
still seeing this in 1.3.2

**Comment by arnekaiser** [comment]
For all people with a catchall dns entry: https://github.com/rancher/rancher/issues/7379#issuecomment-275896610

**Comment by maclonghorn** [comment]
My issue was that Networking Services was version 0.0.5 (the default) so I upgraded to 0.1.0....and...Booyah!  Spent half a day working on that one.  Thanks

**Comment by aemneina** [comment]
network-services should be way more robust in 1.6. Will close this out, feel free to file a new issue if you find any issues around this area with a more modern version of rancher.
