### ISSUE TITLE
Can't pull docker image from private registry (GCR) after upgrading 1.2

### ISSUE THREAD

**Issue by khanhicetea** [rancher/rancher#6916]
**Rancher Version:**
1.2
**Docker Version:**
1.12.3
**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04.1
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node (external DB)
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
After upgrading Rancher from v1.1 to v1.2, it can't pull docker image from GCR (Google Container Registry), I retried setting Registries again but still not works.
Note: I tried login successfully with same credential in my local pc
**Results:** 
![image](https://cloud.githubusercontent.com/assets/4528223/20872923/37a51fd6-bad5-11e6-8d4d-24f22214a27c.png)

**Expected:**
Pull successfully docker image from private registry.

**Comment by khanhicetea** [comment]
Btw, I think the issue caused by wrong processing repository name from image name

Image name : `asia.gcr.io/[project_name]/[image_name]:[tag_name]` => Repository name shoudb be `asia.gcr.io` instead of `asia.gcr.io/[project_name]/[image_name]`

**Comment by StrongMonkey** [comment]
@khanhicetea `asia.gcr.io` is defined as hostname by docker. In the case i believe that we are doing the right things in parsing image name. Can you make sure your credential is used by rancher? Usually this kind of error comes from an invalid credential.

**Comment by khanhicetea** [comment]
It worked fine in version 1.1 but caused error after upgrading to Rancher 1.2.
I retried login and pull successfully on my local pc.
I have ~10 hosts in Cattle cluster and can't pull private image in any host.

**Comment by khanhicetea** [comment]
After upgrading, I saw some stopped containers in each host. Is it right ?

![image](https://cloud.githubusercontent.com/assets/4528223/20894522/62e87314-bb48-11e6-833e-6131a68e867c.png)

**Comment by StrongMonkey** [comment]
@khanhicetea It is expected. Those containers are just system-containers. Did you try to add your credential to rancher? In UI infrastructure stacks there is an option called registry and that stores credential in rancher which will be used to pull private images on any host by rancher.

**Comment by khanhicetea** [comment]
Hm, as I already added it 3 weeks ago (in v1.1) and everything worked fine. You can see the second screenshot in above comment ( I updated )

**Comment by StrongMonkey** [comment]
thank you for the info. I ll investigating more

**Comment by khanhicetea** [comment]
Thank you very much, btw could I revert version because all my services are down today :(

**Comment by deniseschannon** [comment]
@khanhicetea If you had backed up your database before upgrading, you can revert Rancher server to the previous version, but due to the changes in 1.2.0, you will not be able to just revert using the same database.

**Comment by StrongMonkey** [comment]
@khanhicetea in the meantime, can you try to add registry with oauth2 and token(https://cloud.google.com/container-registry/docs/advanced-authentication)? just fyi, this way works for me to pull the private image and might be a workaround for you right now.

**Comment by StrongMonkey** [comment]
For using `keyfile.json`, you need to copy the **exact** raw contents of your keyfile.json into password fields. This means that you need to replace all the newline character with `\n`. (Cause we are not allowed to pass <CR> or <LF> in UI). Sorry for the inconvenience but we made a lot of change in 1.2 so it might break something it used to work in 1.1.

**Comment by khanhicetea** [comment]
Using oauth2 token as password solved the issue, I can pull image now. Thank you !

Btw, after that, it can't resolve DNS inside container (ref #6934) , so my services are still down :(

**Comment by khanhicetea** [comment]
Sorry but after pulling successful in 1 service, next pulling didn't work and it was stuck again.

Same issue here : #6947

I think Rancher should have a document about big picture of Rancher stacks (how many system services in Rancher ? what they do and which specs they based on ? How they work ?), so the users (dev guys) can understand clearly about bugs and try to fix it instead of posting the issues. I can see a short document about Rancher infrastructure [here](http://docs.rancher.com/rancher/v1.2/en/rancher-services/) . That is what I feel as an end-user and a developer. Sorry about complain but I had bad experience when believed and upgraded to a `stable` version, then the services down whole day. Now, I will learn and dive into Ansible or Fabric because I can control it myself at least.

**Comment by StrongMonkey** [comment]
@khanhicetea thank you so much for your feedback.
1. your token might be expired cause they are short-lived. You can refresh your token to make it work. I could say this is only a workaround for you to pull image in the short term.
2.  Since you are using the json file as your private key, we do have a problem in uploading the  contents of your key(we are stripping off the newline in password fields), which cause the wrong secret key to be uploaded and then failed to pull image. We have rewritten our service in go so it might break something.
3. we have logged a separate issue for you in this case to add support for it. https://github.com/rancher/rancher/issues/6956
