### ISSUE TITLE
New service can not use an existing global load balancer by selector rule

### ISSUE THREAD

**Issue by pschirch** [rancher/rancher#6920]
**Rancher Version:**
1.2.0

**Docker Version:**
1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04.1

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node, internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**

Steps based on [official docs](https://docs.rancher.com/rancher/v1.2/zh/cattle/adding-load-balancers/#selector).

1. Create global load balancer. 
```yaml
# docker-compose.yml
version: '2'
services:
  http-load-balancer:
    image: rancher/lb-service-haproxy
    ports:
      - 80
```
```yaml
# rancher-compose.yml
version: '2'
services:
  http-load-balancer:
    scale: 1
    lb_config:
      port_rules:
      - source_port: 80
        protocol: http
        selector: foo=bar
```
```bash
rancher-compose -p global-load-balancers up -d
```
2. Create simple web stack that want to use the already created global load balancer.
```yaml
# docker-compose.yml
version: '2'
services:
  web1:
    image: nginx:stable
    labels:
      foo: bar
```
```yaml
# rancher-compose.yml
version: '2'
services:
  web1:
    scale: 1
    lb_config:
      port_rules:
        - target_port: 80
          hostname: test.com
```
```bash
rancher-compose up -d
```
**Results:** 
```bash
INFO[0000] Creating stack web1                          
INFO[0000] [0/1] [web1]: Creating                       
INFO[0000] Creating service web1                        
ERRO[0000] Failed Creating web1 : Bad response statusCode [422]. Status [422 status code 422]. Body: [code=MissingRequired, fieldName=sourcePort, baseType=error] from [http://192.168.99.100:8080/v2-beta/loadbalancerservices] 
ERRO[0000] Failed to start: web1 : Bad response statusCode [422]. Status [422 status code 422]. Body: [code=MissingRequired, fieldName=sourcePort, baseType=error] from [http://192.168.99.100:8080/v2-beta/loadbalancerservices] 
FATA[0000] Bad response statusCode [422]. Status [422 status code 422]. Body: [code=MissingRequired, fieldName=sourcePort, baseType=error] from [http://192.168.99.100:8080/v2-beta/loadbalancerservices] 
```
**Expected:**

App stack starts and  uses the gloabal load balancer.

Any advice?

**Comment by aemneina** [comment]
@pschirch have you tried manually creating these via the UI? From there you can view the config and diff to see what v1.2.0 is doing differently. I think the doc's might be dated at this point.

**Comment by sangeethah** [comment]
Rancher-server version - Build from master

Tested with rancher-compose version v0.12.1-rc1

When using the following ymls to create service with lb_config , service gets created without any errors being seen. But the service created does not have lb_config set.

```
Sangeethas-MacBook-Pro:rancher-compose-v0.12.1-rc1 sangeethahariharan1$ cat dc-con.yml 
version: '2'
services:
  web2:
    image: nginx:stable
    labels:
      foo: bar
Sangeethas-MacBook-Pro:rancher-compose-v0.12.1-rc1 sangeethahariharan1$ cat rc-con.yml 
version: '2'
services:
  web2:
    scale: 1
    lb_config:
      port_rules:
        - target_port: 80
Sangeethas-MacBook-Pro:rancher-compose-v0.12.1-rc1 sangeethahariharan1$ 
```

**Comment by sangeethah** [comment]
Tested the same use case with rancher-server version - v1.2.1-rc1

We are able to create a service with portrules and they get created with correct portRules in lbConfig.
But LB service is not able to start successfully after this. This issue is tracked in https://github.com/rancher/rancher/issues/6892

**Comment by sangeethah** [comment]
This issue has been validate and close - https://github.com/rancher/rancher/issues/6892
