### ISSUE TITLE
[rancher-dns] external-dns / DNS Update (RFC2136) - substituting IP address

### ISSUE THREAD

**Issue by wbuczak** [rancher/rancher#6925]
**Rancher Version:**  v.1.1.2

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** : Cattle

Dear All

It's a question rather than an issue: 

Each of our rancher machines have two network interfaces, let's call it technical (TN) and generic (GN). All hosts configured in Rancher are assigned TN's IP addresses (10.0.3.x) and GN (192.168.12.X)
Rancher hosts where our containers get deployed use TN (10.0.3.x) 

The DNS updater would extract the TN IP addresses (from rancher metadata) and update my Bind DNS with these IPs.  I need, however to alter that behavior, as for me the goal is to make possible for some of our legacy services (running in GN (192.168...) ) to access containerized services running on rancher hosts (no matter on which of the rancher hosts they get deployed). So I need my RFC2136 DNS updater to somehow "replace on the fly" address 10.0.3 with 192.168.12 when it is updating my Bind DNS.  I'm guessing that in order to achieve this I'd need to fork and change a bit the Go code of the external-dns ? 
Since I have never written a single line of code in Go (yet;-)) I'd be grateful thanks a lot for any hints/ideas.

Best regards
Wojtek

**Comment by janeczku** [comment]
Witam @wbuczak, you can use the `io.rancher.host.external_dns_ip` label to achieve this. Add this label to each of your host with the GN IP address as value. By doing so, external-dns service will use that IP address for the DNS records.

**Comment by janeczku** [comment]
Closing this as answered.
