### ISSUE TITLE
Popup Window - Execute Shell does not open

### ISSUE THREAD

**Issue by markus2810** [rancher/rancher#6927]
**Rancher Version:** 1.2

**Docker Version:** 1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):** AWS: centos 7.2 - ami-7abd0209 eu-west1

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single node, external DB (galera cluster)

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** cattle

**Steps to Reproduce:** From Catalog create a new stack (e.g. ecr updateer), click "execute shell" from host view or stack view. Tried this with Chrome,  FireFox and Edge. Before upgrade to 1.2 everything worked. Also tried in fresh installation of rancher. Also tried launching shell in a different browser windows by using STRG key without success

**Results:** Shell Windows pops up short and closes immediately

**Expected:** Shell Window stays open and I can run commands within the container

**Comment by markus2810** [comment]
Update: Tried with ubuntu 16 as host and it worked. Seems to be a centos specific

**Comment by superseb** [comment]
See https://github.com/rancher/rancher/issues/6861

**Comment by markus2810** [comment]
should be same issue.
