### ISSUE TITLE
Scheduler in initializing mode

### ISSUE THREAD

**Issue by XciD** [rancher/rancher#6928]
**Rancher Version:**
v.1.2.0
**Docker Version:**
1.12.3
**OS and where are the hosts located? (cloud, bare metal, etc):**
Debian
Dedicated Server

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node Rancher with docker storage for database (Following Upgrading Rancher tutorial)
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
I've added 16 new agents to the cluster.
**Results:** 
Scheduler seem to don't initialize him self, I had to scale the service (2), in order to have a instance running.
![capture du 2016-12-05 14 28 24](https://cloud.githubusercontent.com/assets/6586344/20886597/232a2e08-baf7-11e6-880d-14d328b2f2f6.png)

Also, 13 HealthCheck is on initializing too... (on my 16 machines)

**Expected:**
One running instance of Scheduler...

I don't know wich log you need to have more informations

**Comment by aemneina** [comment]
are there any errors thrown in the logs for the container itself?

**Comment by XciD** [comment]
At the bottom : 

```06/12/2016 01:38:06time="2016-12-06T00:38:06Z" level=info msg="Adding resource pool [storageSize] with total 14029770 and used 0 for host 70d8357c-9487-41a0-b631-54961dd180c0"
06/12/2016 01:38:06time="2016-12-06T00:38:06Z" level=info msg="Adding resource pool [instanceReservation] with total 1000000 and used 8 for host 11638315-d832-49dd-b5da-d31e08a908fc"
06/12/2016 01:38:06time="2016-12-06T00:38:06Z" level=info msg="Adding resource pool [cpuReservation] with total 8000 and used 0 for host 11638315-d832-49dd-b5da-d31e08a908fc"
06/12/2016 01:38:06time="2016-12-06T00:38:06Z" level=info msg="Adding resource pool [memoryReservation] with total 33767292928 and used 31457280000 for host 11638315-d832-49dd-b5da-d31e08a908fc"
06/12/2016 01:38:06time="2016-12-06T00:38:06Z" level=info msg="Adding resource pool [storageSize] with total 9008799 and used 0 for host 11638315-d832-49dd-b5da-d31e08a908fc"
06/12/2016 01:38:06time="2016-12-06T00:38:06Z" level=info msg="Adding resource pool [instanceReservation] with total 1000000 and used 8 for host b0eee6e7-b5d5-495a-8d63-34d6ef3cb449"
06/12/2016 01:38:06time="2016-12-06T00:38:06Z" level=info msg="Adding resource pool [cpuReservation] with total 8000 and used 0 for host b0eee6e7-b5d5-495a-8d63-34d6ef3cb449"
06/12/2016 01:38:06time="2016-12-06T00:38:06Z" level=info msg="Adding resource pool [memoryReservation] with total 33767292928 and used 31457280000 for host b0eee6e7-b5d5-495a-8d63-34d6ef3cb449"
06/12/2016 01:38:06time="2016-12-06T00:38:06Z" level=info msg="Adding resource pool [storageSize] with total 14068678 and used 0 for host b0eee6e7-b5d5-495a-8d63-34d6ef3cb449"
06/12/2016 01:38:06time="2016-12-06T00:38:06Z" level=info msg="Initializing event router" workerCount=100
06/12/2016 01:38:06time="2016-12-06T00:38:06Z" level=info msg="Connection established"
06/12/2016 01:38:06time="2016-12-06T00:38:06Z" level=info msg="Starting websocket pings"`

**Comment by mckn** [comment]
I have the same issue. My only instance of Scheduler is stuck in initializing and my logs for that service looks the same.

Also all of mine health services is stuck in initializing mode.

**Comment by XciD** [comment]
Any update on this ?

**Comment by gitlab-pano** [comment]
I am having the same issue: 

```
2/18/2016 2:56:42 PMtime="2016-12-18T22:56:42Z" level=info msg="Initializing event router" workerCount=100
12/18/2016 2:56:42 PMtime="2016-12-18T22:56:42Z" level=info msg="Connection established"
12/18/2016 2:56:42 PMtime="2016-12-18T22:56:42Z" level=info msg="Starting websocket pings"
12/19/2016 2:57:12 AMtime="2016-12-19T10:57:12Z" level=error msg="Exiting scheduler with error: <nil>"
12/19/2016 2:57:21 AMtime="2016-12-19T10:57:21Z" level=info msg="Listening for health checks on 0.0.0.0:80/healthcheck"
12/19/2016 2:57:21 AMtime="2016-12-19T10:57:21Z" level=info msg="Connecting to cattle event stream."
12/19/2016 2:57:21 AMtime="2016-12-19T10:57:21Z" level=info msg="Subscribing to metadata changes."
12/19/2016 2:57:22 AMtime="2016-12-19T10:57:22Z" level=info msg="Adding resource pool [memoryReservation] with total 4143972352 and used 0 for host 8727794e-8f52-491e-8306-e8e81ce3b41c"
12/19/2016 2:57:22 AMtime="2016-12-19T10:57:22Z" level=info msg="Adding resource pool [storageSize] with total 8184446 and used 0 for host 8727794e-8f52-491e-8306-e8e81ce3b41c"
12/19/2016 2:57:22 AMtime="2016-12-19T10:57:22Z" level=info msg="Adding resource pool [instanceReservation] with total 1000000 and used 10 for host 8727794e-8f52-491e-8306-e8e81ce3b41c"
12/19/2016 2:57:22 AMtime="2016-12-19T10:57:22Z" level=info msg="Adding resource pool [cpuReservation] with total 2000 and used 0 for host 8727794e-8f52-491e-8306-e8e81ce3b41c"
12/19/2016 2:57:22 AMtime="2016-12-19T10:57:22Z" level=info msg="Adding resource pool [instanceReservation] with total 1000000 and used 17 for host 8b9a3b1f-89fd-4943-85b1-b124df8f592b"
12/19/2016 2:57:22 AMtime="2016-12-19T10:57:22Z" level=info msg="Adding resource pool [cpuReservation] with total 2000 and used 0 for host 8b9a3b1f-89fd-4943-85b1-b124df8f592b"
12/19/2016 2:57:22 AMtime="2016-12-19T10:57:22Z" level=info msg="Adding resource pool [memoryReservation] with total 4143972352 and used 0 for host 8b9a3b1f-89fd-4943-85b1-b124df8f592b"
12/19/2016 2:57:22 AMtime="2016-12-19T10:57:22Z" level=info msg="Adding resource pool [storageSize] with total 35298553 and used 0 for host 8b9a3b1f-89fd-4943-85b1-b124df8f592b"
12/19/2016 2:57:22 AMtime="2016-12-19T10:57:22Z" level=info msg="Adding resource pool [instanceReservation] with total 1000000 and used 17 for host 5edc1c97-3128-49ab-bfe6-c0ad9c9a3c16"
12/19/2016 2:57:22 AMtime="2016-12-19T10:57:22Z" level=info msg="Adding resource pool [cpuReservation] with total 2000 and used 0 for host 5edc1c97-3128-49ab-bfe6-c0ad9c9a3c16"
12/19/2016 2:57:22 AMtime="2016-12-19T10:57:22Z" level=info msg="Adding resource pool [memoryReservation] with total 4143972352 and used 0 for host 5edc1c97-3128-49ab-bfe6-c0ad9c9a3c16"
12/19/2016 2:57:22 AMtime="2016-12-19T10:57:22Z" level=info msg="Adding resource pool [storageSize] with total 35273973 and used 0 for host 5edc1c97-3128-49ab-bfe6-c0ad9c9a3c16"
12/19/2016 2:57:22 AMtime="2016-12-19T10:57:22Z" level=info msg="Adding resource pool [instanceReservation] with total 1000000 and used 17 for host 3d606c6e-cbd7-470d-8c03-27d3aca541f5"
12/19/2016 2:57:22 AMtime="2016-12-19T10:57:22Z" level=info msg="Adding resource pool [cpuReservation] with total 2000 and used 0 for host 3d606c6e-cbd7-470d-8c03-27d3aca541f5"
12/19/2016 2:57:22 AMtime="2016-12-19T10:57:22Z" level=info msg="Adding resource pool [memoryReservation] with total 4143972352 and used 0 for host 3d606c6e-cbd7-470d-8c03-27d3aca541f5"
12/19/2016 2:57:22 AMtime="2016-12-19T10:57:22Z" level=info msg="Adding resource pool [storageSize] with total 35261718 and used 0 for host 3d606c6e-cbd7-470d-8c03-27d3aca541f5"
12/19/2016 2:57:22 AMtime="2016-12-19T10:57:22Z" level=info msg="Adding resource pool [instanceReservation] with total 1000000 and used 10 for host bdec68b4-391e-426c-8fbc-a1bfb7bd9c10"
12/19/2016 2:57:22 AMtime="2016-12-19T10:57:22Z" level=info msg="Adding resource pool [cpuReservation] with total 1000 and used 0 for host bdec68b4-391e-426c-8fbc-a1bfb7bd9c10"
12/19/2016 2:57:22 AMtime="2016-12-19T10:57:22Z" level=info msg="Adding resource pool [memoryReservation] with total 1040187392 and used 0 for host bdec68b4-391e-426c-8fbc-a1bfb7bd9c10"
12/19/2016 2:57:22 AMtime="2016-12-19T10:57:22Z" level=info msg="Adding resource pool [storageSize] with total 9017171 and used 0 for host bdec68b4-391e-426c-8fbc-a1bfb7bd9c10"
12/19/2016 2:57:22 AMtime="2016-12-19T10:57:22Z" level=info msg="Adding resource pool [instanceReservation] with total 1000000 and used 11 for host 52739ddf-4f66-4777-afdf-ef7eb4f4d144"
12/19/2016 2:57:22 AMtime="2016-12-19T10:57:22Z" level=info msg="Adding resource pool [cpuReservation] with total 1000 and used 0 for host 52739ddf-4f66-4777-afdf-ef7eb4f4d144"
12/19/2016 2:57:22 AMtime="2016-12-19T10:57:22Z" level=info msg="Adding resource pool [memoryReservation] with total 2097152000 and used 0 for host 52739ddf-4f66-4777-afdf-ef7eb4f4d144"
12/19/2016 2:57:22 AMtime="2016-12-19T10:57:22Z" level=info msg="Adding resource pool [storageSize] with total 11047923 and used 0 for host 52739ddf-4f66-4777-afdf-ef7eb4f4d144"
12/19/2016 2:57:22 AMtime="2016-12-19T10:57:22Z" level=info msg="Adding resource pool [instanceReservation] with total 1000000 and used 9 for host 672dbc93-7602-491c-894d-fe08760fb85f"
12/19/2016 2:57:22 AMtime="2016-12-19T10:57:22Z" level=info msg="Adding resource pool [cpuReservation] with total 1000 and used 0 for host 672dbc93-7602-491c-894d-fe08760fb85f"
12/19/2016 2:57:22 AMtime="2016-12-19T10:57:22Z" level=info msg="Adding resource pool [memoryReservation] with total 2097152000 and used 0 for host 672dbc93-7602-491c-894d-fe08760fb85f"
12/19/2016 2:57:22 AMtime="2016-12-19T10:57:22Z" level=info msg="Adding resource pool [storageSize] with total 11830935 and used 0 for host 672dbc93-7602-491c-894d-fe08760fb85f"
12/19/2016 2:57:22 AMtime="2016-12-19T10:57:22Z" level=info msg="Adding resource pool [instanceReservation] with total 1000000 and used 10 for host 49ac2d69-36dd-41ac-a245-496ff361204a"
12/19/2016 2:57:22 AMtime="2016-12-19T10:57:22Z" level=info msg="Adding resource pool [cpuReservation] with total 2000 and used 0 for host 49ac2d69-36dd-41ac-a245-496ff361204a"
12/19/2016 2:57:22 AMtime="2016-12-19T10:57:22Z" level=info msg="Adding resource pool [memoryReservation] with total 4143972352 and used 0 for host 49ac2d69-36dd-41ac-a245-496ff361204a"
12/19/2016 2:57:22 AMtime="2016-12-19T10:57:22Z" level=info msg="Adding resource pool [storageSize] with total 11429584 and used 0 for host 49ac2d69-36dd-41ac-a245-496ff361204a"
12/19/2016 2:57:22 AMtime="2016-12-19T10:57:22Z" level=info msg="Initializing event router" workerCount=100
12/19/2016 2:57:22 AMtime="2016-12-19T10:57:22Z" level=info msg="Connection established"
12/19/2016 2:57:22 AMtime="2016-12-19T10:57:22Z" level=info msg="Starting websocket pings"
```

**Comment by eldadfux** [comment]
I had the same issue and noticed that after the host reboot an older rancher version container started working on my host. Probably forgot to remove it after upgrading. Just removed the old container and started the new one to solve this.

**Comment by lezi1022** [comment]
+1

**Comment by TotalLag** [comment]
+1

**Comment by gitlab-pano** [comment]
I am fixed. My problem seemed to be two separate issues.  One was that one of my rancher hosts had the a different Docker Version than the others.  That one had 1.13, while all my others had 1.12.  The other problem was that I had launched two hosts that were behind a NAT.  Both hosts were reporting their IP address as the IP address of my NAT host.  

I needed to add the **-e CATTLE_AGENT_IP=x.x.x.x** to the rancher agent install script.  In order to be used you have to either know the IP of the host ahead of time or have some kind of way to enter it as a variable.  In my case, I use Scalr to launch and manage my hosts.  So I added it just as you see here. **-e CATTLE_AGENT_IP='%internal_ip%'**.  Scalr is able to provide the instance ip dynamically.  Once both hosts were properly reporting their IP address, my problems were resolved.

**Comment by inventionlabsSydney** [comment]
+1 I am also experiencing the same problem.

Six RancherOS nodes running + 2 control nodes on OpenStack Cluster

**Comment by aemneina** [comment]
is the health check service okay, or does it do the same type of flapping?

**Comment by aemneina** [comment]
also can the agent hosts talk to each other fine? are they in the same subnet, or routable from the subnets theyre in?

**Comment by inventionlabsSydney** [comment]
@aemneina Subnets are routable, there's communication between all of them.

What's the best way to check the "health check"?

Please refer to screenshot of current nodes in rancher:
Hosts start saying "Disconnected" at random and also executing "docker ps" on any of those disconnected nodes just hangs.... infinitely.
shutdown -r now doesn't even seem to operate after....

![screen shot 2017-03-08 at 11 12 50 am](https://cloud.githubusercontent.com/assets/2543079/23684005/35dbe5e0-03f0-11e7-8383-728a6d2938f9.png)

**Comment by aemneina** [comment]
@inventionlabsSydney looks like youre using a modern docker (1.12.3) and rancher 1.1.x. Not a good combo. Can the rancher-agents ping each other? Exec into the container on host6, and ping host 3 or 4. What hosting provider are you using, and is there a reason youre using an old version of rancher?

**Comment by aemneina** [comment]
@inventionlabsSydney disregard my last comment... can the ipsec-router containers ping each other?

**Comment by joshbenner** [comment]
I'm seeing the same issue. My ipsec-router contains _cannot_ ping each other.

**Comment by joshbenner** [comment]
Manually restarting the ipsec-router sidekicks on the hosts seems to have cleared this up. How do the hosts get into this state?

**Comment by aemneina** [comment]
@inventionlabsSydney can you post your healthcheck container logs. They might be complaining about something specific.

**Comment by aemneina** [comment]
curious if this issue still is observed in rancher 1.5.9+? If someone can reproduce it there it will go a long way in improving the ipsec stack. We've recently pushed a handful of improvements to that and network-services. If the issue persists with a newer rancher/ipsec/network services, please file a new issue.

**Comment by dniel** [comment]
I have the same trouble, health check and scheduler stuck in initializing + host  2 host container managed  network not working.

Rancher 1.6.3 + debian 9 running as LXC container in Proxmox, no network trouble between hosts or lxc containers in proxmox.
rancher/scheduler:v0.8.1
rancher/healthcheck:v0.3.1

Hosts has correct ips, the host ip has been detected correctly. 
Network communcation between rancher hosts works as expected with udp ports accessible in both directions. I have tried both ipsec and vxlan network and nothing helps.

I have two Hosts, A and B, and one Rancher Server, each on different hardware.
Containers on A can ping each other with IP and rancher internal DNS name.
Containers on A can ping ipsec/vxlan container on A.
IPsec container on A can ping IPSec container on B.
Containers on A can't ping Containers on B.

Health check logs says 
`
10.7.2017 20:08:56time="2017-07-10T18:08:56Z" level=info msg="Scheduling apply config"
10.7.2017 20:08:56time="2017-07-10T18:08:56Z" level=info msg="healthCheck -- no changes in haproxy config\n"
`

VXLan container says 
`
10.7.2017 20:08:56time="2017-07-10T18:08:56Z" level=info msg="Metadata OnChange received, version: 2465-4f3c5c96fb170da7fa8781d4ac55192c"
10.7.2017 20:08:56time="2017-07-10T18:08:56Z" level=info msg="vxlan: Reload"
10.7.2017 20:08:56time="2017-07-10T18:08:56Z" level=info msg="vxlan: configure"
`

Scheduler says
`
10.7.2017 20:09:58time="2017-07-10T18:09:58Z" level=info msg="Initializing event router" workerCount=100
10.7.2017 20:09:58time="2017-07-10T18:09:58Z" level=info msg="Connection established"
10.7.2017 20:09:58time="2017-07-10T18:09:58Z" level=info msg="Starting websocket pings"
`

I have recreated the environments with fresh hosts and rancher server a couple of times, with both vxlan and ipsec. Every time the same problems, healthcheck, scheduler stuck inititializing, and managed network between hosts not working.

**Comment by clok** [comment]
+1

**Comment by wmphang** [comment]
Hi @dniel 
 I also having the similar issue. I am using Ubuntu lxd container. I finally found out the issue, the docker require ip_forwarding to be enable. Since the lxd container share the same kernel with the host. The host also have to enable ip_forward. Once this parameter is enabled on the host the healthcheck and scheduler is up and running.
I have spend many day and night on this. Hope this will help others

Thank you
