### ISSUE TITLE
Running a container with >3 links fails to start

### ISSUE THREAD

**Issue by joehumphries** [rancher/rancher#6931]
**1.2.0:**

**Docker Version: 1.12.1**

**Rancher OS: 4.4.19-rancher**

**Setup Details: On Openstack 1 server + 2 hosts**

**Environment Type: (Cattle)**

**Steps to Reproduce: Start 4 couchdb base images couch1-4 then start a base nginx passing in couch1-4 as links**

**Results: fails with error : Expected state running but got error: Error sending reply 931ec09e-7a8d-42fb-9192-4c84ff7419a3: Post http://192.168.50.110:8080/v1/publish: net/http: request canceled (Client.Timeout exceeded while awaiting headers))** 

**Expected: starts**

On version 1.1.4 this all works fine, I can start a stack up with 4 couchdb's and then put a proxy on top (ha/nginx), taking the running config onto 1.2.0 (or manually creating the stack) fails everything.

With 3 links it works.. 4.. it never does.. However if you really quickly exec into the servers (rare as no logs/feedback really appear) you can ping all the servers.

Thanks

**Comment by alena1108** [comment]
@joehumphries were couchdb and nginx started as standalone containers? or as a part of the service

**Comment by joehumphries** [comment]
Both ways.. as part of a stack, or If I start a new stack with 4 nodes, then attempt to start another container(any) with >3 links it spins forever.

**Comment by alena1108** [comment]
@joehumphries tried different scenarios on latest master, no luck reproducing the issue. This is what I've tried:

1) Creating target service with 4 instances, then referencing this service via service link from client service. Client service's instance starts fine.
2) Creating 4 standalone containers, and referencing them via 4 container links from the client standalone container, works good as well.

Could you share your exported stack config where containers are started as  a part of the service? I'd like to test it using your images/configuration.

**Comment by alena1108** [comment]
Please reopen if you see the issue again
