### ISSUE TITLE
Rancher v1.2.0 breaks name resolution for hostname

### ISSUE THREAD

**Issue by nicholasdille** [rancher/rancher#6933]
**Rancher Version:**
1.2.0

**Docker Version:**
1.23.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
AWS instances running Ubuntu 16.04 LTS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Rancher server with an external database and four dedicated hosts

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Execute the following command in a container inside a stack: `nslookup $(hostname)`

**Results:** 
```
bash-4.3$ nslookup $(hostname)
nslookup: can't resolve 'd45c33125423': Name does not resolve
```

**Expected:**
```
bash-4.3$ nslookup $(hostname)
Name:      484d0c71ceaf
Address 1: 172.17.0.3 484d0c71ceaf
```

**More information:**
- When running the same command inside the same container started from the command line (`docker run -it <image> bash`), it works!
- The image is based on `alpine:3.4`

**Comment by darrenscerri** [comment]
#6855

**Comment by nicholasdille** [comment]
@darrenscerri yes, this is a duplicate, closing.
