### ISSUE TITLE
No DNS resolution inside containers

### ISSUE THREAD

**Issue by jloisel** [rancher/rancher#6934]
**Rancher Version:** 1.2.0

**Docker Version:** 1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):** 3 Bare-metal hosts running Ubuntu 16.04 LTS Kernel 4.4.0.51. Machines are firewall with custom IpTable rules. UDP 500 and 4500 are open, as well as port 8080 where rancher server is running. All machines are setup equally through Ansible.

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** Single node + internal DB, migrated from Rancher 1.1.3

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:**
After migrating the environment, containers are unable to make DNS resolutions. I tried resolving google.com from inside the containers without success. It works absolutely fine with Rancher v1.1.3.

**Results:** 
No DNS resolution inside containers. Containers are able to ping each other (so ipsec networking is working fine). Also, on one machine the networking-manager keeps logging CNI up then down.

I tried to reproduce the issue on a setup with 3 Amazon machines, from scratch and by using our v1.1.3 DB, without success. 

**Expected:**
containers should be able to make DNS resolution.

How can I investigate such an issue and find the root cause? (which logs to inspect, which system containers to look at) Is there a documentation explaining the role of each microservice container?

**Comment by deniseschannon** [comment]
Are all your infrastructure stacks green? 

DNS microservice is within the `network-services` stack.  It is a sidekick service to the `metadata` service.

**Comment by aemneina** [comment]
Do you have nscd, or any name caching services, running on your node host?

**Comment by khanhicetea** [comment]
I had the same issue after upgrading v1.2. Can't resolve hostname of linked service inside container.

```
$ cat /etc/resolv.conf
search portal.rancher.internal portal.portal.rancher.internal rancher.internal
nameserver 169.254.169.250
```

```
/var/www # nslookup google.com 169.254.169.250
Server:    169.254.169.250
Address 1: 169.254.169.250

Name:      google.com
Address 1: 74.125.68.138 sc-in-f138.1e100.net
Address 2: 74.125.68.102 sc-in-f102.1e100.net
Address 3: 74.125.68.101 sc-in-f101.1e100.net
Address 4: 74.125.68.113 sc-in-f113.1e100.net
Address 5: 74.125.68.139 sc-in-f139.1e100.net
Address 6: 74.125.68.100 sc-in-f100.1e100.net
Address 7: 2404:6800:4003:c02::71 sc-in-x71.1e100.net
/var/www # nslookup mysql1 169.254.169.250
Server:    169.254.169.250
Address 1: 169.254.169.250

nslookup: can't resolve 'mysql1': Name does not resolve
```

which `mysql1` is my linked service name

**Comment by jloisel** [comment]
Everything is green. Ipsec is properly working. nscd is not installed on any of the machine. What are the ports needed by Rancher to have dns working? I have opened UDP 500 and 4500 for ipsec, as well as 8080 for rancher server.

**Comment by sdelrio** [comment]
I had same issue, but after manually installing `network-services` (Catalog > Library) it resolves,(don't even need to restart the containr having the issues). 
I also was testing in that rancher environment all the 1.2-rc versions before the final one, so probably any update didn't work 100%.

**Comment by jloisel** [comment]
I have tried to remove the hosts, clean all docker containers, volumes and images then re-add them with no effect. network-services was properly running on every host, but I guess the issue seems related to metadata side-kick which is the dns container.

**Comment by sdelrio** [comment]
Before installing `network-services` I could not even `curl` or `telnet` to the external IP inside the container (runing another container with nginx listening on 80). 

@jloisel, can you telnet or curl to the IP ?

**Comment by jloisel** [comment]
I had to rollback  the changes as the issues where occuring in production. I cannot reproduce those issues on our pre-production environment which runs on Amazon. Also tried a local setup with local machines, everything is fine. I can't figure out why it's failing on our production machines which are configured the same way as pre-production (through ansible).

**Comment by oomathias** [comment]
I have the exact same problem.
Everything is green. So basically nothing works without the DNS working, this is quite critical.

```
root@container:~# nslookup google.com 169.254.169.250
Server:         169.254.169.250
Address:        169.254.169.250#53

** server can't find google.com: REFUSED
```

```
root@container:~# nslookup google.com 8.8.8.8
Server:         8.8.8.8
Address:        8.8.8.8#53

Non-authoritative answer:
Name:   google.com
Address: 216.58.204.110
```


**Rancher Version:** 1.2.1
**Docker Version:** 1.12.4
**OS and where are the hosts located?:** 2 Bare-metal hosts running Ubuntu 16.04.1 LTS (with KVM) (4.4.0).
**Setup Details:** Single node + internal DB (mounted volume), migrated from Rancher 1.1.3
Environment Type: Cattle

`ip show route` on host
```
10.42.0.0/16 dev docker0  proto kernel  scope link  src 10.42.0.1
x.x.x.x/24 dev eth0  proto kernel  scope link  src x.x.x.x
169.254.169.250 dev docker0  scope link
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.0.1
```
`/etc/resolv.conf` on host
```
nameserver 213.251.128.136
nameserver 213.186.33.102
nameserver 8.8.8.8
nameserver 8.8.4.4
search ovh.net
```

**Comment by jloisel** [comment]
I think it will take several fix releases for the v1.2.x branch to get things operational again. There are just too many regressions. We will wait until 1.3.x is out to migrate to 1.2.x, it's simply not enough stable right now to be usable in production.

**Comment by oomathias** [comment]
@deniseschannon Any news here?

Without DNS, I have to patch /etc/resolv.conf on each container to add a public DNS (like 8.8.8.8).
Are you aware of this? My production environment encounters this bug, so it's critical.

**Comment by jloisel** [comment]
Same here, we are unable to migrate to v1.2.x until this issue is fixed.

**Comment by JaviSabalete** [comment]
+1

**Comment by dustinvanbuskirk** [comment]
+1 on this after solving issue with rancher-net now i have ran into this.  this upgrade has been a terrible experience been working on it for about 16 hours now. 12 hours straight today.

**Comment by dustinvanbuskirk** [comment]
I was able to get this working.  I was originally on Docker 1.10.3.  I removed the affected hosts we had several.  Then removed all containers and images then upgraded Docker to 1.12.6 we also tried 1.12.3 and after rejoining the host to the server we picked up DNS resolution name against the service names again internal to our stack.

**Comment by aemneina** [comment]
Closing this issue. There have been a lot of changes in this area since 1.2.x. If the issue persists with rancher 1.6+ please file a new issue.
