### ISSUE TITLE
Rancher 1.2.0 upgrade agent re-adding throws fatal error

### ISSUE THREAD

**Issue by sven-codeculture** [rancher/rancher#6935]
**Rancher Version:**
1.2.0

**Docker Version:**
1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
- Alpine Linux 3.3 running on scaleway bare metal server
- /var/lib/docker running on device 2 (folder is mount point to ndb2)

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Rancher with multiple environments

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Re-Adding host with usual command (shown on Add-Hosts)

**Results:** 
Getting errors in Agent log:
```
time="2016-12-05T16:51:13Z" level=fatal msg="Failed to find container id:\n1:cpuset,cpu,cpuacct,blkio,memory,devices,freezer,net_cls,perf_event,net_prio,pids:/docker/952e74bc576e8822c1dddb3893467e46cfe777fa9e941f350775cc21b6d2285e\n"
time="2016-12-05T16:51:15Z" level=fatal msg="Failed to find container id:\n1:cpuset,cpu,cpuacct,blkio,memory,devices,freezer,net_cls,perf_event,net_prio,pids:/docker/18124c9ebce8265a38718f3c3c7bfb53606bae4ae7e0803ff5a12a937e79d034\n"
time="2016-12-05T16:51:16Z" level=fatal msg="Failed to find container id:\n1:cpuset,cpu,cpuacct,blkio,memory,devices,freezer,net_cls,perf_event,net_prio,pids:/docker/d169b653e1d89f3c1c396443512b41176bee2acdfa58360a1e6da56103648d14\n"
time="2016-12-05T16:51:18Z" level=fatal msg="Failed to find container id:\n1:cpuset,cpu,cpuacct,blkio,memory,devices,freezer,net_cls,perf_event,net_prio,pids:/docker/aced91fa1c7eab12e54b26a0293dfa4ac6538791ccb20c2f03f40f52657c9e3d\n"
time="2016-12-05T16:51:20Z" level=fatal msg="Failed to find container id:\n1:cpuset,cpu,cpuacct,blkio,memory,devices,freezer,net_cls,perf_event,net_prio,pids:/docker/a39ad2b623061116ebec5d532e825134dd96b0684ac24a0e6e8b325a642b882f\n"
time="2016-12-05T16:51:23Z" level=fatal msg="Failed to find container id:\n1:cpuset,cpu,cpuacct,blkio,memory,devices,freezer,net_cls,perf_event,net_prio,pids:/docker/6eac9ed375e5b92c9d9c95b835ef1435f7c84b3cdf5062374b6c3b7f5a75f22f\n"
time="2016-12-05T16:51:27Z" level=fatal msg="Failed to find container id:\n1:cpuset,cpu,cpuacct,blkio,memory,devices,freezer,net_cls,perf_event,net_prio,pids:/docker/0bfae0e974e672034c423b0aaee68803800e11f568d52543f7cc16a148ce6872\n"
time="2016-12-05T16:51:35Z" level=fatal msg="Failed to find container id:\n1:cpuset,cpu,cpuacct,blkio,memory,devices,freezer,net_cls,perf_event,net_prio,pids:/docker/d89f97e6fee4464fa00b7aea2506e94f704f9492e39bed3c043a4a04f20bef57\n"
time="2016-12-05T16:51:49Z" level=fatal msg="Failed to find container id:\n1:cpuset,cpu,cpuacct,blkio,memory,devices,freezer,net_cls,perf_event,net_prio,pids:/docker/db5b70169d1a785b85b16a7b23e97c2ca466a166beb00c5305fe7732614f1e5a\n"
time="2016-12-05T16:52:16Z" level=fatal msg="Failed to find container id:\n1:cpuset,cpu,cpuacct,blkio,memory,devices,freezer,net_cls,perf_event,net_prio,pids:/docker/606414ffcf61cb5cb99f40d4c76e354685d53ed26679995cd03100aabe2a5c7b\n"
``` 

**Expected:**
Host gets re-added to my envirorment

My second envirorment running on an RancherOS together with the Rancher Server itself works just fine. I just need a fast solution for this environment if possible.

Greetings Sven

**Comment by aemneina** [comment]
are there more logs than this? I think this is just failing to get stats for containers not running?

**Comment by sven-codeculture** [comment]
The agent is only spamming this and then ends itself. The Server does not show anything.

**Comment by aemneina** [comment]
hey @sven-codeculture what does `docker ps -a` show?

**Comment by sven-codeculture** [comment]
docker ps -a shows the following:
http://pastebin.com/hBJ9VW7i

I have tryed with both, deleting the /var/lib/rancher and not deleting it. Its the same error.
Do i have any other ways to give you some more logs from the container (such as a debug flag or so?)

**Comment by sven-codeculture** [comment]
Not mounting the /var/lib/docker directory and just having it on the System drive produced the same result. I have also tryed to use differend docker versions. Still the same problem.

I have migrated all my data to an ububtu:16:04 environment now, this seems to work fine, so the bug seems to have something to do with alpine (3.3?).

**Comment by aemneina** [comment]
yeah makes sense @sven-codeculture , we dont test or claim alpine support. I'm going to close this out.
