### ISSUE TITLE
Kubernetes Environment: UI keeps redirecting me back to Stacks

### ISSUE THREAD

**Issue by adaughterson** [rancher/rancher#6937]
I'm trying to provision a Kubernetes cluster through Rancher, and the UI keeps kicking me back to the Stacks topic, while I'm trying to search around in the infrastructure/hosts topic.

I've created a pod, which appears to be working correctly.  The infrastructure stacks are all green and presumably healthy.

Not sure exactly why the UI is doing this, but it is making triage and troubleshooting nearly impossible through the UI.

What sort of info can I provide to get a look at this issue?

Thanks,

Adam Daughterson

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.2.0` Cattle: `v0.174.3` UI: `v1.2.34` |
|Access|`Disabled`|
|Orchestration|`Kubernetes`|
|Route|`k8s-tab.namespace.stacks.index`|

**Comment by biolounge** [comment]
I also have the same issue: https://github.com/rancher/rancher/issues/6930

**Comment by adaughterson** [comment]
It seems like once I can get at least one replication controller up, the problem goes away.

**Comment by vincent99** [comment]
I don't think this applies to 1.6 anymore, but it definitely doesn't for 2.0..
