### ISSUE TITLE
Rancher 1.2.0 - TLS handshake timeout github access control

### ISSUE THREAD

**Issue by mckn** [rancher/rancher#6939]
**Rancher Version:**
1.2.0

**Docker Version:**
1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
I have tried with ubuntu 16.04 and CentOS 7

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
internal db

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
none

**Steps to Reproduce:**
start the rancher contianer and try to add the github integration

**Results:** 
I am getting errors like this during start of rancher:

```bash
time="2016-12-05T20:41:16Z" level=error msg="Error processing event" err="Get https://github.com/packethost/docker-machine-driver-packet/releases/download/v0.1.2/docker-machine-driver-packet_linux-amd64.zip: net/http: TLS handshake timeout" eventId=a1eacac7-f046-48ca-9876-732fd7985539 eventName="machinedriver.activate;handler=goMachineService-machine" resourceId=1md1 
```
and this when I am trying to add the github access control:
```bash
time="2016-12-05T20:46:41Z" level=error msg="Received error from github: Post https://github.com/login/oauth/access_token: net/http: TLS handshake timeout" 
time="2016-12-05T20:46:41Z" level=error msg="Github getAccessToken: GET url https://github.com/login/oauth/access_token received error from github, err: Post https://github.com/login/oauth/access_token: net/http: TLS handshake timeout" 
time="2016-12-05T20:46:41Z" level=error msg="Error generating accessToken from github Post https://github.com/login/oauth/access_token: net/http: TLS handshake timeout" 
time="2016-12-05T20:46:41Z" level=error msg="GetToken failed with error: Post https://github.com/login/oauth/access_token: net/http: TLS handshake timeout" 
2016-12-05 20:46:41,843 ERROR [:] [] [] [] [tp1830712962-15] [.a.a.i.e.ExternalServiceAuthProvider] Got error from Auth service. statusCode: 500 
```

**Expected:**
github integration should successfully be added.

**Comment by superseb** [comment]
GitHub Authentication works fine here. As you are also experiencing this with the download of a machine driver, are you sure it's not on your network end? Seems like a unstable internet connection /proxy/firewall situation?

**Comment by mckn** [comment]
hmm, I just tried to spin up a new machine without any firewall or restrictions on the internet connection. I still got the TLS handshake issues. So that did not help. Any more suggestions on what to try?

@superseb what os and which docker version are u running?

**Comment by mckn** [comment]
hmm..it did work locally on my laptop (OSX). So it might be the underlying OS or the internet connection since I am running my laptop on a different network.

**Comment by superseb** [comment]
Just tried on AWS with Ubuntu 16.04 and Docker 1.12.3. Where are your hosts running?

**Comment by mckn** [comment]
Hmm..I am running on a openstack provider called citycloud. If i do `docker exec -ti <container-id> bash` and then do a curl to the url that is timing out everything seems to work just fine. So I dont think it is the network.

Are you running the latest, stable or v1.2.0 tag? I am running the v1.2.0 tag.

**Comment by mckn** [comment]
Maybe some certificate issues? Does anyone know if there is a way of getting more detailed information about the error? Like enabling debug or something.

**Comment by mckn** [comment]
Seems to be some kind of issue with the ca-certificates. If I did the following everything seems to work (at least for CentOS7):

```bash
sudo docker run -d -v /etc/pki/tls/certs/ca-bundle.crt:/etc/ssl/certs/ca-certificates.crt:ro --restart=unless-stopped --name rancher rancher/server:v1.2.0
```

**Comment by mckn** [comment]
I close this one, seems like @superseb where correct. I recreated the whole network-stack at our openstack provider and now everything seems to work. ⛈
