### ISSUE TITLE
swarm catalogs cannot be deployed under swarm mode

### ISSUE THREAD

**Issue by HackerWilson** [rancher/rancher#6943]
After I deployed swarm cluster success, I click the launch button in wordpress catalog, but failed.
It says: `There is no route named swarm-tab.projects`.
so was other catalogs including my test catalog.
<img width="980" alt="default" src="https://cloud.githubusercontent.com/assets/7730203/20916638/be490e24-bbc7-11e6-8f88-250db7a7789e.png">

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.2.0` Cattle: `v0.174.3` UI: `v1.2.34` |
|Access|`localauth` `admin`|
|Orchestration|`Swarm`|
|Route|`catalog-tab.launch`|

**Comment by seankf** [comment]
I have seen this as well on 1.2.0 Release with a custom catalogue with a swarm-template.

Access: LDAP
Orchestration: Swarm
Route catalog-tab.launch

**Comment by tfiduccia** [comment]
Version - 1.2.0 - Verified that this is an issue.

**Comment by vincent99** [comment]
There has been minimal interest in the catalog for swarm and it doesn't actually work with the new swarmkit for 1.2, so support for this will no longer be available.  Removing the catalog option was just missed in 1.2.0.

**Comment by tfiduccia** [comment]
Version - master 11/13
Catalog removed - verified fixed.

**Comment by HackerWilson** [comment]
@vincent99 swarm catalog is really removed from rancher 1.2.1, so swarm mode in rancher is just a children tool now?

how do you think about support the docker compose bundle?

```
Compose does not use swarm mode to deploy services to multiple nodes in a swarm. All containers will be scheduled on the current node.

To deploy your application across the swarm, use the bundle feature of the Docker experimental build.

More info:
https://docs.docker.com/compose/bundles
``
