### ISSUE TITLE
Mount options for rancher-nfs catalog results in error

### ISSUE THREAD

**Issue by machi1990** [rancher/rancher#6945]
**Rancher Version:**
1.2
**Docker Version:**
1.12
**OS and where are the hosts located? (cloud, bare metal, etc):**
cloud
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
internal DB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
Adds a rancher-nfs from the catalog  with the following mount options : 
```
proto=tcp,port=2049,nfsvers=4 
```
**Results:** 
```log
level=error msg="Failed to mount test_volume: Failed mount -o proto=tcp,port=2049,nfsvers=4 nfs_server:/mnt/test_volume /var/lib/rancher/volumes/rancher-nfs/test_volume: mount.nfs: Failed to find 'tcp' protocol" 
```
**Expected:**
The mount point to be mounted. The options used to work correctly with convoy-nfs.

**Comment by galindro** [comment]
Same with me

**Comment by machi1990** [comment]
Convoy options do not work anymore. Basically, I used the options provided in this link [NFS](https://linux.die.net/man/8/mount) e.g timeo, actimeo, rsize and wsize, to name the least worked. The used options were passed as a string, with a comma separating one option from the other.   

Closing this.
