### ISSUE TITLE
Amazon EC2 Host stuck "Installing Rancher Agent"

### ISSUE THREAD

**Issue by richbos** [rancher/rancher#6946]
**Rancher Version:**
1.2.0

**Docker Version:**
1.11.2

**OS and where are the hosts located? (cloud, bare metal, etc):**
AWS eu-west-1
Amazon Linux EC2 (for the Rancher Server)
EC2 hosts tried = Amazon Linux, Ubuntu 16.04, Centos7 and Rancheros7

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node Rancher server, internal DB with Docker vol mount for MySQL

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
EC2 host deployment to public or private subnet (with nat-gw) using internal or external Rancher server host registration URL (IP or DNS name).
Rancher created rancher-machine EC2 security group used for hosts, concurrently nested with an entry in a security group used for Rancher server allowing all traffic (to the sg)

**Results:** 
Hosts get stuck on provisioning stage 'Installing Rancher Agent' (see screen grab)

**Expected:**
Host nodes should install and register with the Rancher server

![screen shot 2016-12-06 at 08 05 05](https://cloud.githubusercontent.com/assets/1983458/20918393/a6d9b0c4-bb8e-11e6-931a-3453276906be.png)

**Comment by jloisel** [comment]
I have tested this on my personal machine and it works fine. Double check your rancher server is accessible from those machines. Also, during this step, the rancher agent image is downloaded from Docker Hub, which might be slow at some hours of the day.

**Comment by richbos** [comment]
Hi, many thanks for taking a look. After nothing all yesterday afternoon or from first attempts this morning I can confirm that it has now started working, yet I changed no configuration so that's somewhat intriguing.

Ah well, another mystery but at least it's up an running. I shall close the issue.

**Comment by jloisel** [comment]
Docker HUB has errating behavior, you should not rely on it to launch machines and have a local docker registry which caches the images.

**Comment by richbos** [comment]
That's a great tip, I shall certainly do just that for production purposes. Many thanks.

**Comment by jloisel** [comment]
That's what we do because Docker Hub is completely unreliable.
