### ISSUE TITLE
Not all commands on rancher-cli supported under Windows

### ISSUE THREAD

**Issue by chrisurwin** [rancher/rancher#6949]
The Windows-cli doesn't appear to support the 
```rancher --host <name> docker ps``` command
It returns with error 
```[31mFATA[0m[0000] listen unix C:\Users\test\AppData\Local\Temp\docker-sock981066123: socket: An address incompatible with the requested protocol was used.```

Trying to run the linux version under Ubuntu bash on Windows fails too with
```FATA[0000] listen unix /tmp/docker-sock959895108: setsockopt: invalid argument``` but this isn't too surprising

**Comment by metabrain** [comment]
+1

Having same issue here.

**Comment by jbdk** [comment]
I use the Windows 10 built in bash. Works perfectly.

**Comment by WoLfulus** [comment]
@jbdk which version of CLI do you use? I'm on Windows 10 too and logs is not just like @metabrain

**Comment by kingsd041** [comment]
Tested with rancher/server:v1.6.14 with rancher CLI v0.6.8-rc4
I can't close this issue because if the rancher agent is a windows host, the following error will appear:
```
root@ip-172-31-35-76:~/rancher-v0.6.8-rc4# ./rancher hosts
ID        HOSTNAME          STATE     CONTAINERS   IP               LABELS    DETAIL
1h13      EC2AMAZ-SOK7AM2   active    2            x.x.x.x

root@ip-172-31-35-76:~/rancher-v0.6.8-rc4# ./rancher --host 1h13 docker ps
error during connect: Get http://%2Ftmp%2Fdocker-sock470415277/v1.18/containers/json: EOF
```

**Comment by kingsd041** [comment]
I submitted a new issue #12100, so close this issue
