### ISSUE TITLE
Metadata in v1.2.0 for old API (2015-12-19) has "-" separators instead of "_"...breaks old metadata searchs

### ISSUE THREAD

**Issue by dsvmacdonald** [rancher/rancher#6951]
**Rancher Version:**
v1.2.0

**Docker Version:**
v1.2.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
Mac (local dev); Servers with RedHat 7.2

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

Rancher single instance (local); Rancher HA (cloud)

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

Cattle

**Steps to Reproduce:**
`curl http://rancher-metadata.rancher.internal/2015-12-19/containers` 
3=minerva-prod_equipment-query_1

**Results:** 
On Rancher v.1.1.0, it returns: _3=minerva-prod_equipment-query_1_

On Rancher v1.2.0, it returns 3=minerva-prod-equipment-query-1

**Expected:**

_3=minerva-prod_equipment-query_1_

**Comment by deniseschannon** [comment]
We had to move to using `-` instead of `_` due to Docker changes that caused Rancher to no longer work with the names with `_`.

Here are some of the old issues about it:

https://github.com/rancher/rancher/issues/5195
https://github.com/docker/docker/pull/23740

**Comment by dsvmacdonald** [comment]
@deniseschannon is there a way to determine what version of Rancher is running from Metadata service?

**Comment by deniseschannon** [comment]
@dsvmacdonald I don't believe there is a way to determine the Rancher version from the metadata service. I'm not sure how you're tooling is setup, but would you be able to access the Rancher API to figure it out from the API?

**Comment by dsvmacdonald** [comment]
I'm accessing the metadata service within my container in the entrypoint.sh script.  I really don't want to add rancher access keys to container to query api from container.  I have requested a feature enhancement to add this data to the metadata service.

**Comment by vincent99** [comment]
There is a label you can set which will cause you to be provided with the API URL and a set of keys to access it from the container of you want to talk to the API, they don't have to be manually maintained.

But as I said in #6984 you can probably use labels, create_index, or uuids to accomplish what you're trying to do without assuming a particular name for the container.
