### ISSUE TITLE
Mac Spacebar does not working in shell under v1.2.0

### ISSUE THREAD

**Issue by dsvmacdonald** [rancher/rancher#6952]
**Rancher Version:**

v1.2.0

**Docker Version:**

v1.2.3

**OS and where are the hosts located? (cloud, bare metal, etc):**

Mac (local)

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

Single

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

Cattle

**Steps to Reproduce:**

Open shell and type "curl "
  
**Results:** 

"curl" no space;

**Expected:**

"curl" followed by space. 

FYI - to get space, need to hit Command key first...this unlocks spacebar

**Comment by vincent99** [comment]
Works fine for me...

**Comment by superseb** [comment]
Can't reproduce on macOS 10.12.1 and Chrome or Safari.

**Comment by dsvmacdonald** [comment]
macOs 10.12.1

Problem on Chrome: 54.0.2840.98 and 55.0.2883.75 (both 64-bit)

Works correctly on 

- Firefox 49.02
- Safari 10.0.1

**Comment by marcovn** [comment]
On Chrome 54.0.2840.98 and macOS 10.12.1 and cannot reproduce it either...

Running cattle on Digital Ocean hosts.

**Comment by dsvmacdonald** [comment]
Closing ... must be one of my browser extensions
