### ISSUE TITLE
Failed to setup network for pod: No IP address found

### ISSUE THREAD

**Issue by MinaDesu** [rancher/rancher#6954]
**Rancher Version:**
rancher/server: v1.2
rancher/agent: v1.1.0

**Docker Version:**
Docker version 1.11.2, build bac3bae
**OS and where are the hosts located? (cloud, bare metal, etc):**
CoreOS 1185.3.0 (with KVM) (4.7.3) on DigitalOcean

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher server
3 agent nodes (one being on the same server than the server)

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
1. Create the replication controller:
apiVersion: v1
kind: ReplicationController
metadata:
  name: default-http-backend
spec:
  replicas: 1
  selector:
    app: default-http-backend
  template:
    metadata:
      labels:
        app: default-http-backend
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: default-http-backend
        image: gcr.io/google_containers/defaultbackend:1.0
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        ports:
        - containerPort: 8080

2. Get the status:

$ kubectl get pods
NAME                                   READY     STATUS              RESTARTS   AGE
default-http-backend-0yy8y             0/1       ContainerCreating   0          6m
.... 8< SNIP >8 ....

$ kubectl describe pod default-http-backend-0yy8y
Name:           default-http-backend-0yy8y
Namespace:      default
Node:           catwoman/138.197.2.76
Start Time:     Tue, 06 Dec 2016 11:12:05 -0500
Labels:         app=default-http-backend
Status:         Pending
IP:
Controllers:    ReplicationController/default-http-backend
Containers:
  default-http-backend:
    Container ID:
    Image:              gcr.io/google_containers/defaultbackend:1.0
    Image ID:
    Port:               8080/TCP
    State:              Waiting
      Reason:           ContainerCreating
    Ready:              False
    Restart Count:      0
    Liveness:           http-get http://:8080/healthz delay=30s timeout=5s period=10s #success=1 #failure=3
    Volume Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-kzefl (ro)
    Environment Variables:      <none>
Conditions:
  Type          Status
  Initialized   True
  Ready         False
  PodScheduled  True
Volumes:
  default-token-kzefl:
    Type:       Secret (a volume populated by a Secret)
    SecretName: default-token-kzefl
QoS Class:      BestEffort
Tolerations:    <none>
Events:
  FirstSeen     LastSeen        Count   From                    SubobjectPath   Type            Reason          Message
  ---------     --------        -----   ----                    -------------   --------        ------          -------
  6m            6m              1       {default-scheduler }                    Normal          Scheduled       Successfully assigned default-http-backend-0yy8y to catwoman
  4m            38s             3       {kubelet catwoman}                      Warning         FailedSync      Error syncing pod, skipping: failed to "SetupNetwork" for "default-http-backend-0yy8y_default" with SetupNetworkError: "Failed to setup network for pod \"default-http-backend-0yy8y_default(ba961a10-bbce-11e6-9723-9690e6282b4d)\" using network plugins \"cni\": No IP address found; Skipping pod"

**Results:** 

Failed to setup network for pod: No IP address found; Skipping pod

**Expected:**

Pod creation successful

**Comment by MinaDesu** [comment]
By the way, the idea is to follow this guide to create a nginx ingress controller:
https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx

**Comment by MinaDesu** [comment]
I scaled up to 2 replicas, and the second one was assigned to another node and is working.
Scaling down to 1 replica, removed the stale one.

**Comment by MinaDesu** [comment]
After rebooting the node, creation succeeds.

**Comment by aemneina** [comment]
@MinaDesu if this is solved, can you close the ticket?

**Comment by MinaDesu** [comment]
Closing for now, though I'm wondering why the node had to be rebooted.
