### ISSUE TITLE
Containers stuck in "Starting (Scheduling)" state

### ISSUE THREAD

**Issue by gjongenelen** [rancher/rancher#6964]
**Rancher Version:**
1.2.0

**Docker Version:**
1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
RancherOS 0.7.1 on AWS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node, external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Add a new service/container

**Results:** 
Container gets stuck in starting-state. ("Scheduling")
Error logs of rancher/scheduler:v0.4.0:
`time="2016-12-01T19:04:37Z" level=info msg="Initializing event router" workerCount=100
time="2016-12-01T19:04:37Z" level=info msg="Connection established"
time="2016-12-01T19:04:37Z" level=info msg="Starting websocket pings" 
time="2016-12-01T19:05:22Z" level=info msg="Hit websocket pong timeout. Last websocket ping received at 2016-12-01 19:05:07.535255015 +0000 UTC. Closing connection." 
time="2016-12-01T19:05:22Z" level=error msg="Exiting scheduler with error: <nil>" `

**Expected:**
Container starts

**Comment by marminthibaut** [comment]
:+1:

**Comment by aemneina** [comment]
Closing in favor of #7482 would also be good to know if youre seeing this with a newer version of rancher.
