### ISSUE TITLE
rancher-compose results in "Check API key"

### ISSUE THREAD

**Issue by blamh** [rancher/rancher#6965]
**Rancher Version:**
v1.2.0

**Docker Version:**
Docker version 1.12.3, build 6b644ec

**OS and where are the hosts located? (cloud, bare metal, etc):**
4.4.24-rancher on EC2

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher. One host containing both server and agent/host. External DB on same host.

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
1.
```bash
sudo mkdir -p /opt/mysql_data && sudo chown rancher:rancher /opt/mysql_data
docker run -d --name=mysql --restart=always -v /opt/mysql_data:/var/lib/mysql \
    -e MYSQL_ROOT_PASSWORD=root -p 127.0.0.1:3306:3306 \
    mariadb
docker exec -it mysql mysql --password=root -e "CREATE DATABASE rancher"

sudo docker run -d --name=rancher-server --restart=always -p 8000:8080 --link mysql:mysql \
    -e CATTLE_DB_CATTLE_MYSQL_HOST=mysql \
    -e CATTLE_DB_CATTLE_MYSQL_NAME=rancher \
    -e CATTLE_DB_CATTLE_USERNAME=root \
    -e CATTLE_DB_CATTLE_PASSWORD=root \
    rancher/server:latest
```

2. Manually adding an Account API Key.
3. Creating an `docker-compose.yml`file containing :
 ```text
version: '2'
services:
  Httpd:
    image: xx/drupal:test
```
4. `RANCHER_URL="http://<MY IP>:8000" RANCHER_ACCESS_KEY="449E26A86E76F4B70109" RANCHER_SECRET_KEY="<SECRET KEY>" rancher-compose --debug up`

**Results:** 
```
DEBU[0000] Environment Context from file : map[]
DEBU[0000] Opening compose files: docker-compose.yml
DEBU[0000] Opening rancher-compose file: /Users/.../env-status/rancher-compose.yml
DEBU[0000] Not found: /Users/.../env-status/rancher-compose.yml
DEBU[0000] [0/1] [Httpd]: Adding
ERRO[0000] Failed to open project env-status: Can not create a stack, check API key [449E26A86E76F4B70109] for [http://52.210.195.220:8000]
FATA[0000] Failed to read project: Can not create a stack, check API key [449E26A86E76F4B70109] for [http://52.210.195.220:8000]
```

**Expected:**
That `ranger-compose` would be able to talk to the API by using an Account API key. But for some reason it is not able to do that.

Have looked at the comm and ranger-compose makes two GET requests; one to `http://<MY IP>:8000/v2-beta` and one to `http://<MY IP>:8000/v2-beta/schemas`.

When doing a `ranger env` I get an overview of my stacks as expected. So the Account API key is working for something..

`rancher-compose -v` returns `rancher-compose version v0.12.0` and `rancher -v` returns `rancher version v0.4.0`.

**Comment by deniseschannon** [comment]
Rancher CLI uses account API keys as you can manipulate any environment. 

Rancher Compose uses environment API keys, which are hidden under the "advanced options" in API keys as you need to specify which environment you want to use within Rancher.

Rancher CLI also allows you to do `rancher up` which is the same as `rancher-compose up`.

**Comment by blamh** [comment]
Great. That fixed it. The error message could be more helpful about this. I made a change proposal to the doc to make this even more explicit. Thank you for the help :-)

**Comment by justsml** [comment]
Hey @blamh - Thanks!
Can you link to the PR/branch?

**Comment by blamh** [comment]
@justsml  https://github.com/rancher/rancher.github.io/pull/566

**Comment by cat24max** [comment]
There is no Advanced Options under API keys???

**Comment by vincent99** [comment]
![image](https://user-images.githubusercontent.com/753917/39089283-a27930c0-4578-11e8-880f-77bdae7a4660.png)

**Comment by aa-aahmed** [comment]
guys i am using following built but when i click on account and then Api ^ keys there is no option for advance?

am i looking at wrong place?



Component | Version
-- | --
Rancher | v2.2.3
User Interface | v2.2.41
Helm | v2.10.0-rancher10
Machine | v0.15.0-rancher6-1

**Comment by vincent99** [comment]
This is a multiple year old issue for 1.x and is completely not relevant for  2.x.  There is no rancher-compose for 2.x.

**Comment by aa-aahmed** [comment]
Thanks for your reply I was wondering if you can  give me a guide to deploy
ELK stack. I'm new to rancher ...
