### ISSUE TITLE
Issue on creation of stacks using Rancher API v2-beta - Method not allowed

### ISSUE THREAD

**Issue by newmips** [rancher/rancher#6967]
Hi,

An issue on creation of stacks using API v2-beta:

**Rancher Version:**
v1.2.0

**Docker Version:**
1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu - OVH Cloud Public

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node Rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Send the following request to Rancher API v2-beta using NodeJS:

curl -u "B97CA240526F7EFA475B:AWLuZ6NGN7MCnGPjCnYHd2SGkNx2rMp9xuDWQyda" \
-X POST \
-H 'Content-Type: application/json' \
-d '{
  "environment": {
    "mysql_database": "mysql_database",
    "mysql_user": "mysql_user",
    "mysql_password": "mysql_password",
    "mysql_root_password": "mysql_root_password",
    "domain": "newmips.cloud"
  },
  "system": false,
  "startOnCreate": true,
  "name": "subdomain",
  "externalId": "catalog://newmips:newmips:2",
  "rancherCompose": "version: '2'\nservices:\n  designer:\n    scale: 1\n    health_check:\n      port: 1337\n      interval: 2000\n      initializing_timeout: 60000\n      unhealthy_threshold: 3\n      strategy: recreate\n      response_timeout: 2000\n      request_line: GET \"/\" \"HTTP/1.0\"\n      healthy_threshold: 2\n  lb:\n    scale: 1\n    lb_config:\n      port_rules:\n      - source_port: 80\n        target_port: 1337\n        service: designer\n        hostname: \"$${stack_name}.${domain}\"\n        path: /1\n.catalog:\n  name: Newmips\n  version: \"v2.0.1\"\n  description: \"Newmips Application\"\n  uuid: newmips-0\n  minimum_rancher_version: v0.51.0\n  questions:\n    - variable: mysql_database\n      description: \"Database Name\"\n      label: \"Mysql Database\"\n      required: true\n      default: \"newmips\"\n      type: \"string\"\n    - variable: mysql_user\n      description: \"mysql user\"\n      label: \"Mysql User\"\n      required: true\n      default: \"newmips\"\n      type: \"string\"\n    - variable: mysql_password\n      description: \"mysql password\"\n      label: \"Mysql Password\"\n      required: true\n      default: \"newmips\"\n      type: \"string\"\n    - variable: mysql_root_password\n      description: \"mysql root password\"\n      label: \"Mysql Root Password\"\n      required: true\n      default: \"root_password\"\n      type: \"string\"\n    - variable: domain\n      description: \"Domain Name\"\n      label: \"Domain name\"\n      required: true\n      default: \"newmips.cloud\"\n      type: \"string\"",
  "dockerCompose": "version: '2'\nservices:\n  designer:\n    labels:\n      io.rancher.sidekicks: workspace\n    image: newmipsdockside/newmips\n    links: \n      - database:database\n    ports:\n      - \"1337\"\n    volumes_from:\n      - workspace\n  database:\n    image: newmipsdockside/percona-server\n    environment:\n      MYSQL_DATABASE: ${mysql_database}\n      MYSQL_USER: ${mysql_user}\n      MYSQL_PASSWORD: ${mysql_password}\n      MYSQL_ROOT_PASSWORD: ${mysql_root_password}\n    labels:\n      io.rancher.sidekicks: seed\n    volumes_from:\n      - seed\n  seed:\n    image: newmipsdockside/newmips-seed\n    labels:\n      io.rancher.container.start_once: 'true'\n  workspace:\n    image: newmipsdockside/workspace\n    labels:\n      io.rancher.container.start_once: 'true'\n  lb:\n    image: rancher/lb-service-haproxy\n    ports:\n      - 80\n\n"
}' 'http://newmips.cloud:8080/v2-beta/stacks'

**Results:** 
{
  "id": "5dbcf44b-8d70-4279-ac20-1fffd914af61",
  "type": "error",
  "links": {},
  "actions": {},
  "status": 405,
  "code": "Method not allowed",
  "message": "Method not allowed",
  "detail": null,
  "baseType": "error"
}

**Expected:**
Creation of stack is expected.

Note: requests in GET mode are working well. For instance, I achieve to get the list of stacks calling GET /stacks...

Any idea ? I think we are missing a parameter.

Thank you very much for your support.

**Comment by newmips** [comment]
OK resolved. Endpoint was wrong. Now using:
http://newmips.cloud:8080/v2-beta/projects/1a5/stacks

**Comment by vincent99** [comment]
You should probably delete that API key if your install is on the public internet...

**Comment by newmips** [comment]
Yes. I did it. Thx :-)

**Comment by shoutcool** [comment]
I just stumbled over the same error. It would be helpful if you also update the api documentation at http://docs.rancher.com/rancher/v1.2/en/api/v2-beta/api-resources/stack/#create
