### ISSUE TITLE
404's for fonts on API page

### ISSUE THREAD

**Issue by marcovn** [rancher/rancher#6969]
**Rancher Version:** 1.2.0

**Docker Version:** 1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):** cloud

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single node, external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:** Access the API page at /v2-beta or /v1. Open the developers console (Chrome or Firefox) and note the following:

**Results:** 
https://rancher.local/fonts/glyphicons-halflings-regular.woff2 Failed to load resource: the server responded with a status of 404 (Not Found)
https://rancher.local/fonts/glyphicons-halflings-regular.woff Failed to load resource: the server responded with a status of 404 (Not Found)
https://rancher.local/fonts/glyphicons-halflings-regular.ttf Failed to load resource: the server responded with a status of 404 (Not Found)

Also in the UI: the glyps used for the actions like up, reload, clear, etc. are not rendered correctly.

**Expected:** No errors. BTW this works fine in our 1.1.4 instance.

As we are using Rancher with an SSL enabled reverse proxy (nginx) I also enabled access on the http port 8080 - bypassing the reverse proxy. However the results are identical.

**Comment by tfiduccia** [comment]
Version - 1.2 : the errors are indeed happening in the dev tools.  The actions gylps are squares instead of icons:
![image](https://cloud.githubusercontent.com/assets/11514927/21030798/a259b67c-bd5d-11e6-8a07-1c044ed7953c.png)

**Comment by sangeethah** [comment]
similar to this issue - https://github.com/rancher/rancher/issues/5929

**Comment by vincent99** [comment]
This is the same as #5929.
