### ISSUE TITLE
Projects API says it supports sort & filter but doesn't

### ISSUE THREAD

**Issue by vincent99** [rancher/rancher#697]
Remove the `sortLinks` and `filters` from the response, `collectionFilters` from the schema.

**Comment by mattrochon** [comment]
I would prefer if sorting/filtering worked for this resource.

**Comment by sangeethah** [comment]
Tested with build from master .

/v1/projects  still exposes "Filter" and "Sort By" actions but we have no options to choose from for "Filter"/"Sort By".
