### ISSUE TITLE
api.machine.create doesn't create host

### ISSUE THREAD

**Issue by jloisel** [rancher/rancher#6970]
**Rancher Version:** 1.2.0

**Docker Version:** 1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):** Ubuntu 16.04 LTS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** Single Node, internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:**
Call api.machine.create via curl to create an AWS machine.

**Results:** 
The machine never appears in the UI. It should have created a host associated to this machine.

**Expected:**
In Rancher v1.1.x, this create a host which is visible in the UI.

**Comment by jloisel** [comment]
Switched to v2-beta, where I need to call api.host.create with adequate settings to create the AWS / DigitalOcean host correctly. Would be nice to have API changes being documented somewhere, to avoid any surprise when upgrading Rancher.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
