### ISSUE TITLE
Rancher Scheduling for new host extremely slow

### ISSUE THREAD

**Issue by ddelnano** [rancher/rancher#6973]
I am currently seeing issues when scheduling begins on new hosts.  As we have grown our use of Rancher (adding more hosts) this problem seems to have worsened.  As it currently stands, from the time a host is registered with the Rancher master to when all the containers are started it takes anywhere from 15-60 mins.  I have captured the logs of the rancher-agent and master as I bring up a new host and wait for that host to receive its scheduled containers.  Since these logs contain some sensitive information I would be happy to share them upon request.  These logs corresponded with the following events.  The following instance was only a 15 min delay but as I said it varies greatly.

- ASG increased desired count by 1  9:02 AM
- Host was recognized in Rancher hosts UI 9:05 AM
- Containers running 9:21 AM

**Rancher Version:**
v1.1.4

**Docker Version:**
1.11.1

**OS and where are the hosts located? (cloud, bare metal, etc):**
AWS EC2

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher w/ external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Bump autoscaling desired count by one and watch it take ~1 hour for a container besides the rancher-agent to get started on the host.
 
**Results:** 
Takes anywhere from 30-60mins+ to get the host in a state that can receive traffic.

**Expected:**
The scheduling should happen in a reasonable amount of time after the host is registered with the master.

**Comment by aemneina** [comment]
There have been significant performance improvements since 1.1. @ddelnano if this is still an issue for you in 1.5.+ please file a new issue and we can investigate from there, since so much has changed.
