### ISSUE TITLE
Port  Mappings not working properly

### ISSUE THREAD

**Issue by tknecht** [rancher/rancher#6974]
**Rancher Version:**
1.2
**Docker Version:**
Docker version 1.12.1, build 23cf638
**OS and where are the hosts located? (cloud, bare metal, etc):**
Linux <hostname> 4.4.0-53-generic #74-Ubuntu SMP Fri Dec 2 15:59:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher, external DB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**

Service uses "Managed Network"

Dockerfile states:
EXPOSE 25 587 8080 3128 1080

docker-compose.yml states:
ports:
    - 25:25/tcp
    - 587:587/tcp
    - 8080:8080/tcp
    - 1080:1080/tcp
    - 3128:3128/tcp

docker ps states:
CONTAINER ID        IMAGE           COMMAND                  CREATED             STATUS              PORTS               NAMES
66c3e7f2c373        image:develop   "/.r/r /sbin/my_init"    4 days ago          Up 5 hours                              r-image-develop-12-2-ae8394ca

docker inspect <container id> states:

"NetworkSettings": {
[...],
"Ports": {},
[...]
}

In Docker "netstat -tulpen" states:

[...]
tcp6       0      0 :::587                  :::*                    LISTEN 0          43112       29/node
tcp6       0      0 :::22                   :::*                    LISTEN 0          40661       28/sshd
tcp6       0      0 :::1080                 :::*                    LISTEN 0          42644       29/node
tcp6       0      0 :::3128                 :::*                    LISTEN 0          42643       29/node
tcp6       0      0 :::25                   :::*                    LISTEN 0          43111       29/node
[...]

**Results:** 

Port 8080 is not available in Docker although its configured as all other ports that work, but are neither in docker ps nor in docker inspect. 

**Expected:**

To work as expected based on docker standards. 
It worked fine on 1.2RC5

**Comment by blackside** [comment]
Got the same problem on 

**Rancher Version:**
1.3
**Docker Version:**
Docker version 1.12.1, 1.12.3 and 1.12.6
**OS and where are the hosts located? (cloud, bare metal, etc):**
Centos 7.3 3.10.0-327.el7.x86_64 and 3.10.0-514.el7.x86_64
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher, external DB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

Probably going to rollback to rancher 1.14 soon since I cant find what is causing this...

**Comment by vincent99** [comment]
CNI networking  plugins in Rancher 1.2+ map ports using iptables instead of letting docker do it.  Therefore as far as docker is concerned there are no ports mapped, but that doesn't mean they are not working.

**Comment by blackside** [comment]
Hmm.. but if docker cant report the ports as per usual my gliderlabs/registrator cant find the mapped ports to report to our consul cluster.
