### ISSUE TITLE
Service Links change when automatically when upgrading service

### ISSUE THREAD

**Issue by tknecht** [rancher/rancher#6976]
Rancher Version:
1.2
Docker Version:
Docker version 1.12.1, build 23cf638
OS and where are the hosts located? (cloud, bare metal, etc):
Linux 4.4.0-53-generic #74-Ubuntu SMP Fri Dec 2 15:59:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)
HA rancher, external DB
Environment Type: (Cattle/Kubernetes/Swarm/Mesos)
Cattle
Steps to Reproduce:

When upgrading a existing service with a service link in some cases the "As Name" field changes to the full link.

Example:
Original Setting:
Destination Service : Stack redis-cluster - redis
As Name: redis

Click upgrade and the settings changes to:
Destination Service : Stack redis-cluster - redis
As Name: redis-cluster/redis

Results:

Error: Setservicelinks Error
Validation failed in API: name contains invalid characters

Expected:

To keep settings as set.

**Comment by flantel** [comment]
I'm experiencing the same problem. As well as this, service/external links are not resolving within the containers.

**Comment by tfiduccia** [comment]
@tknecht and @flantel - This is a bug in 1.2.  We were saving an extra slash and it is fixed in 1.2.1.  Please upgrade.

**Comment by flantel** [comment]
OK, but I am experiencing this on a clean 1.2.1 install. Running 1.2.1 on Ubuntu 16.04. The only thing linking a previous version is the docker-compose and rancher-compose files, which were copy/paste from a 1.14 installation.

**Comment by tfiduccia** [comment]
@flantel - Can you please give me an example docker-compose so I can try it for myself?

**Comment by flantel** [comment]
@tfiduccia I can do that, but the images it uses are mainly on an internal registry so you would not be able to load it directly. 
[compose.zip](https://github.com/rancher/rancher/files/668562/compose.zip)
