### ISSUE TITLE
Cross host networking broken for VXLAN networking with hostPorts for network set to "false"

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6977]
Rancher server version - v1.2.0

Steps to reproduce the problem:

Create a template with network service provider as - "Vxlan-Internal" from - https://github.com/deniseschannon/rancher-catalog and branch vxlantest

Create environment with this template.

Create service with expose ports.

hostPorts for vxlan network is still set to"true" in DB -- https://github.com/rancher/rancher/issues/6958.
Set hostPorts for vxlan network to "false" is DB.
Add restart any existing container ( just to trigger the new metadata changes to the vxlan cnontainers)

No exposed port get programmed on the host.
Even port 4789 which is needed for cross host communication is not exposed , resulting in  health-check containers and scheduler containers to be stuck in "Initializing" state forever.

This is true for other health check enabled services as well.

**Comment by deniseschannon** [comment]
Test with Rancher v1.3.0 and latest network-services.

**Comment by sangeethah** [comment]
Tested with rancher-server master builds and rancher/network-manager:v0.2.14.
health check enabled instances are able to start successfully and get to "healthy" state.
