### ISSUE TITLE
Should be allowed to start multiple containers with same exposed port on the same host when networking has hostPorts set to "false"

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6979]
Rancher server version - v1.2.0

Steps to reproduce the problem:

Create a template with network service provider as - "Vxlan-Internal" from - https://github.com/deniseschannon/rancher-catalog and branch vxlantest

Create environment with this template.

Create service with expose ports.

hostPorts for vxlan network is still set to"true" in DB -- #6958.
Set hostPorts for vxlan network to "false" is DB.
Add restart any existing container ( just to trigger the new metadata changes to the vxlan cnontainers)
No exposed port get programmed on the host as expected.

Note - Set up has 2 hosts.
Try to start a service  S1 with exposed port - 7878 and scale 2.

Try to start a service  S2 with same exposed port - 7878 and scale 2.
S2 fails to start because of not able to find host with available port.

Expected Behavior:

Should be allowed to start multiple containers with same exposed port on the same host when networking has hostPorts set to "false"

**Comment by StrongMonkey** [comment]
@deniseschannon My changes for the scheduler have not touched the service port part(nodePort). Not sure i can fix it in 1.4.

**Comment by cjellick** [comment]
Seems very odd to me to change the behavior of the scheduler based off of this backdoor hostPorts=false feature.

Think about the user flow for this:
User specifies the equivalent of `-p 80:8080` but we just quietly ignore that in the network provider. To me, the quietly ignoring it part needs to change, not the scheduler. Scheduler should continue to do its job of not allowing duplicate host port consumption. If we want to preen this use case, the cattle API should add validation to not allow public ports.

**Comment by cjellick** [comment]
Confirmed with @ibuildthecloud - he agrees this doesn't need fixed changed. If a container says it is publishing port 80, then that port should be reserved for that host.

**Comment by deniseschannon** [comment]
@cjellick but if you have hostports set as `false`, why are we reserving it? you should be able to schedule as many containers to whatever host since the ports aren't actually published.

**Comment by cjellick** [comment]
No, these are separate concerns. The user is requesting that that port be reserved, so it is. The implementation details of network plugin should not impact this. Per @ibuildthecloud, hostPorts=false does not mean that we are completely ignoring host ports. It is an indication to the plugin that it should not manage them (that is not to say that something else isn't managing them).
