### ISSUE TITLE
add one more host ,Host stop working

### ISSUE THREAD

**Issue by zk4** [rancher/rancher#6981]
**Rancher Version:**
1.1.3
**Docker Version:**
1.12.3
**OS and where are the hosts located? (cloud, bare metal, etc):**
ubuntu 14.04.5
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
cattle 
**Steps to Reproduce:**
I have 2 hosts.
one business service is running, with haproxy  on every  host.
business service scales fine

but problems comes follow these steps, the new-adding host would stop working:
1.  added  one more ubuntu(same version) host to the host cluster
2. docker add agent.
3. scaling business service to this new host.
4. browse service from out network. 
5. boom, new-adding host stop working, even I can`t loin in by SSH. 

there are some signs I find strange.
1. when out network is comming. even with one single connection. the netcark spike to 25M/s
2. cpu flys.
3. then host stop working.

Belows are some Network Agent logs, I don`t if it helps.

**Network Agent  log Results:** 

## Network Agent  log:
12/8/2016 3:08:06 PMgithub.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization(0xc82005d630, 0x7fe408b05728, 0xc820162ee0)
12/8/2016 3:08:06 PM	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:277 +0x5b1
12/8/2016 3:08:06 PMmain.glob.func8(0xc82007aa00, 0x0, 0x0)
12/8/2016 3:08:06 PM	/go/src/github.com/opencontainers/runc/main_unix.go:26 +0x68
12/8/2016 3:08:06 PMreflect.Value.call(0x7448a0, 0x8f0bd0, 0x13, 0x839998, 0x4, 0xc8200ff268, 0x1, 0x1, 0x0, 0x0, ...)
12/8/2016 3:08:06 PM	/usr/local/go/src/reflect/value.go:435 +0x120d
12/8/2016 3:08:06 PMreflect.Value.Call(0x7448a0, 0x8f0bd0, 0x13, 0xc8200ff268, 0x1, 0x1, 0x0, 0x0, 0x0)
12/8/2016 3:08:06 PM	/usr/local/go/src/reflect/value.go:303 +0xb1
12/8/2016 3:08:06 PMgithub.com/urfave/cli.HandleAction(0x7448a0, 0x8f0bd0, 0xc82007aa00, 0x0, 0x0)
12/8/2016 3:08:06 PM	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:487 +0x2ee
12/8/2016 3:08:06 PMgithub.com/urfave/cli.Command.Run(0x83c828, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x8d0180, 0x51, 0x0, ...)
12/8/2016 3:08:06 PM	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/command.go:191 +0xfec
12/8/2016 3:08:06 PMgithub.com/urfave/cli.(*App).Run(0xc820001e00, 0xc82000a100, 0x2, 0x2, 0x0, 0x0)
12/8/2016 3:08:06 PM	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:240 +0xaa4
12/8/2016 3:08:06 PMmain.main()
12/8/2016 3:08:06 PM	/go/src/github.com/opencontainers/runc/main.go:137 +0xe24
12/8/2016 3:08:20 PMpanic: standard_init_linux.go:175: exec user process caused "exec format error" [recovered]
12/8/2016 3:08:20 PM	panic: standard_init_linux.go:175: exec user process caused "exec format error"
12/8/2016 3:08:20 PM
12/8/2016 3:08:20 PMgoroutine 1 [running, locked to thread]:
12/8/2016 3:08:20 PMpanic(0x7ddea0, 0xc820174ee0)
12/8/2016 3:08:20 PM	/usr/local/go/src/runtime/panic.go:481 +0x3e6
12/8/2016 3:08:20 PMgithub.com/urfave/cli.HandleAction.func1(0xc8201172e8)
12/8/2016 3:08:20 PM	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:478 +0x38e
12/8/2016 3:08:20 PMpanic(0x7ddea0, 0xc820174ee0)
12/8/2016 3:08:20 PM	/usr/local/go/src/runtime/panic.go:443 +0x4e9
12/8/2016 3:08:20 PMgithub.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization.func1(0xc820116bf8, 0xc82001e080, 0xc820116d08)
12/8/2016 3:08:20 PM	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:259 +0x136
12/8/2016 3:08:20 PMgithub.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization(0xc82005c780, 0x7f93ca505470, 0xc820174ee0)
12/8/2016 3:08:20 PM	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:277 +0x5b1
12/8/2016 3:08:20 PMmain.glob.func8(0xc82007a780, 0x0, 0x0)
12/8/2016 3:08:20 PM	/go/src/github.com/opencontainers/runc/main_unix.go:26 +0x68
12/8/2016 3:08:20 PMreflect.Value.call(0x7448a0, 0x8f0bd0, 0x13, 0x839998, 0x4, 0xc820117268, 0x1, 0x1, 0x0, 0x0, ...)
12/8/2016 3:08:20 PM	/usr/local/go/src/reflect/value.go:435 +0x120d
12/8/2016 3:08:20 PMreflect.Value.Call(0x7448a0, 0x8f0bd0, 0x13, 0xc820117268, 0x1, 0x1, 0x0, 0x0, 0x0)
12/8/2016 3:08:20 PM	/usr/local/go/src/reflect/value.go:303 +0xb1
12/8/2016 3:08:20 PMgithub.com/urfave/cli.HandleAction(0x7448a0, 0x8f0bd0, 0xc82007a780, 0x0, 0x0)
12/8/2016 3:08:20 PM	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:487 +0x2ee
12/8/2016 3:08:20 PMgithub.com/urfave/cli.Command.Run(0x83c828, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x8d0180, 0x51, 0x0, ...)
12/8/2016 3:08:20 PM	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/command.go:191 +0xfec
12/8/2016 3:08:20 PMgithub.com/urfave/cli.(*App).Run(0xc820001980, 0xc82000a100, 0x2, 0x2, 0x0, 0x0)
12/8/2016 3:08:20 PM	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:240 +0xaa4
12/8/2016 3:08:20 PMmain.main()
12/8/2016 3:08:20 PM	/go/src/github.com/opencontainers/runc/main.go:137 +0xe24
12/8/2016 3:08:36 PMpanic: standard_init_linux.go:175: exec user process caused "exec format error" [recovered]
12/8/2016 3:08:36 PM	panic: standard_init_linux.go:175: exec user process caused "exec format error"
12/8/2016 3:08:36 PM
12/8/2016 3:08:36 PMgoroutine 1 [running, locked to thread]:
12/8/2016 3:08:36 PMpanic(0x7ddea0, 0xc82015aee0)
12/8/2016 3:08:36 PM	/usr/local/go/src/runtime/panic.go:481 +0x3e6
12/8/2016 3:08:36 PMgithub.com/urfave/cli.HandleAction.func1(0xc8200f72e8)
12/8/2016 3:08:36 PM	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:478 +0x38e
12/8/2016 3:08:36 PMpanic(0x7ddea0, 0xc82015aee0)
12/8/2016 3:08:36 PM	/usr/local/go/src/runtime/panic.go:443 +0x4e9
12/8/2016 3:08:36 PMgithub.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization.func1(0xc8200f6bf8, 0xc82001e0c8, 0xc8200f6d08)
12/8/2016 3:08:36 PM	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:259 +0x136
12/8/2016 3:08:36 PMgithub.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization(0xc82005d630, 0x7fe360405728, 0xc82015aee0)
12/8/2016 3:08:36 PM	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:277 +0x5b1
12/8/2016 3:08:36 PMmain.glob.func8(0xc82007aa00, 0x0, 0x0)
12/8/2016 3:08:36 PM	/go/src/github.com/opencontainers/runc/main_unix.go:26 +0x68
12/8/2016 3:08:36 PMreflect.Value.call(0x7448a0, 0x8f0bd0, 0x13, 0x839998, 0x4, 0xc8200f7268, 0x1, 0x1, 0x0, 0x0, ...)
12/8/2016 3:08:36 PM	/usr/local/go/src/reflect/value.go:435 +0x120d
12/8/2016 3:08:36 PMreflect.Value.Call(0x7448a0, 0x8f0bd0, 0x13, 0xc8200f7268, 0x1, 0x1, 0x0, 0x0, 0x0)
12/8/2016 3:08:36 PM	/usr/local/go/src/reflect/value.go:303 +0xb1
12/8/2016 3:08:36 PMgithub.com/urfave/cli.HandleAction(0x7448a0, 0x8f0bd0, 0xc82007aa00, 0x0, 0x0)
12/8/2016 3:08:36 PM	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:487 +0x2ee
12/8/2016 3:08:36 PMgithub.com/urfave/cli.Command.Run(0x83c828, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x8d0180, 0x51, 0x0, ...)
12/8/2016 3:08:36 PM	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/command.go:191 +0xfec
12/8/2016 3:08:36 PMgithub.com/urfave/cli.(*App).Run(0xc820001b00, 0xc82000a100, 0x2, 0x2, 0x0, 0x0)
12/8/2016 3:08:36 PM	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:240 +0xaa4
12/8/2016 3:08:36 PMmain.main()
12/8/2016 3:08:36 PM	/go/src/github.com/opencontainers/runc/main.go:137 +0xe24
12/8/2016 3:08:50 PMpanic: standard_init_linux.go:175: exec user process caused "exec format error" [recovered]
12/8/2016 3:08:50 PM	panic: standard_init_linux.go:175: exec user process caused "exec format error"
12/8/2016 3:08:50 PM
12/8/2016 3:08:50 PMgoroutine 1 [running, locked to thread]:
12/8/2016 3:08:50 PMpanic(0x7ddea0, 0xc82017aee0)
12/8/2016 3:08:50 PM	/usr/local/go/src/runtime/panic.go:481 +0x3e6
12/8/2016 3:08:50 PMgithub.com/urfave/cli.HandleAction.func1(0xc82011f2e8)
12/8/2016 3:08:50 PM	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:478 +0x38e
12/8/2016 3:08:50 PMpanic(0x7ddea0, 0xc82017aee0)
12/8/2016 3:08:50 PM	/usr/local/go/src/runtime/panic.go:443 +0x4e9
12/8/2016 3:08:50 PMgithub.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization.func1(0xc82011ebf8, 0xc82001e088, 0xc82011ed08)
12/8/2016 3:08:50 PM	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:259 +0x136
12/8/2016 3:08:50 PMgithub.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization(0xc82005c7d0, 0x7feb85af1428, 0xc82017aee0)
12/8/2016 3:08:50 PM	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:277 +0x5b1
12/8/2016 3:08:50 PMmain.glob.func8(0xc82007a780, 0x0, 0x0)
12/8/2016 3:08:50 PM	/go/src/github.com/opencontainers/runc/main_unix.go:26 +0x68
12/8/2016 3:08:50 PMreflect.Value.call(0x7448a0, 0x8f0bd0, 0x13, 0x839998, 0x4, 0xc82011f268, 0x1, 0x1, 0x0, 0x0, ...)
12/8/2016 3:08:50 PM	/usr/local/go/src/reflect/value.go:435 +0x120d
12/8/2016 3:08:50 PMreflect.Value.Call(0x7448a0, 0x8f0bd0, 0x13, 0xc82011f268, 0x1, 0x1, 0x0, 0x0, 0x0)
12/8/2016 3:08:50 PM	/usr/local/go/src/reflect/value.go:303 +0xb1
12/8/2016 3:08:50 PMgithub.com/urfave/cli.HandleAction(0x7448a0, 0x8f0bd0, 0xc82007a780, 0x0, 0x0)
12/8/2016 3:08:50 PM	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:487 +0x2ee
12/8/2016 3:08:50 PMgithub.com/urfave/cli.Command.Run(0x83c828, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x8d0180, 0x51, 0x0, ...)
12/8/2016 3:08:50 PM	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/command.go:191 +0xfec
12/8/2016 3:08:50 PMgithub.com/urfave/cli.(*App).Run(0xc820001980, 0xc82000a100, 0x2, 0x2, 0x0, 0x0)
12/8/2016 3:08:50 PM	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:240 +0xaa4
12/8/2016 3:08:50 PMmain.main()
12/8/2016 3:08:50 PM	/go/src/github.com/opencontainers/runc/main.go:137 +0xe24
**Expected:**

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
