### ISSUE TITLE
Is volumes should not be purged since 1.2?

### ISSUE THREAD

**Issue by clicman** [rancher/rancher#6982]
**Rancher Version:** 1.2

**Docker Version:** 1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):** Ubuntu 16.04

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single node

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:**
Delete volume from storage tab

**Results:** 
Volume removed from ui

**Expected:**
Volume exists in state Deleted.

A still can purge it from api. Is it new behavior?

**Comment by tfiduccia** [comment]
@clicman - the previous behavior where removed volumes where still able to be seen in the UI was a bug.  Once you remove any volume, container, service, host it should not remain in the UI.  Also we will do an automatic purge of any removed (deleted) items.  It's time based so it can take up to 10 minutes for the purge to happen.  If this is not automatically happening after 10 minutes, please reopen issue as Volumes not automatically purging.
