### ISSUE TITLE
Provide more Meaningful API Validation Messages for Stack Names Conflicts

### ISSUE THREAD

**Issue by VincenzoFerme** [rancher/rancher#6983]
**Rancher Version:**

1.12

**Docker Version:**

1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):**

Bare metal, Ubuntu 16.04 LTS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

Single Node, Internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

Cattle

**Steps to Reproduce:**

1. Create a user stack named NFS
2. Add the Rancher NFS Infrastructure Service

**Results:** 

Get: "Validation failed in API: name is not unique"

**Expected:**

Get a more meaningful message, or pick an unique Stack name automatically.

**Comment by tfiduccia** [comment]
version - 1.2
Two issues here:
1.  Maybe we shouldn't name the Rancher NFS stack just NFS as user may want to use that.  Rancher NFS may be better.
2.  Can we add the word "stack" to the error.  So it says "stack name is not unique" and gives the user a better sense of what they need to change?

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
