### ISSUE TITLE
load balancer scheduling host drop-down not functioning

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#6988]
**Rancher Version:** v1.2

**Steps to Reproduce:**
1.  Add labels to host
2.  Add load balancer
3.  Go to scheduling and click on drop-down for host

**Results:** Nothing in there

**Expected:**  Should reflect host labels.

**Comment by SamMousa** [comment]
This seems to work in 1.4.1, tested when creating a new load balancer:

![image](https://cloud.githubusercontent.com/assets/547021/23296110/e67c7f80-fa73-11e6-8dea-c8aa9538f670.png)
