### ISSUE TITLE
CATTLE_URL partly ignored in agent registration

### ISSUE THREAD

**Issue by zyounker** [rancher/rancher#6989]
**Rancher Version:**
v1.2
**Docker Version:**
1.12.1
**OS and where are the hosts located? (cloud, bare metal, etc):**
ubuntu 16.04
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA Rancher, external db
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
Pass CATTLE_URL and watch it ignore it during host registration

So i am setting up a rancher environment in AWS. Rancher is available via a public ELB that is not accessible to the nodes. because of this i am trying to make use of CATTLE_URL to point it to an internal working node i looked up in the API.

Problem is it uses this for the initial connection which goes fine. but then it pulls down a new registration url that will not work:

NFO: Running Agent Registration Process, CATTLE_URL=http://10.0.2.142:8080/v1
INFO: Attempting to connect to: http://10.0.2.142:8080/v1
INFO: http://10.0.2.142:8080/v1 is accessible
INFO: Inspecting host capabilities
INFO: Boot2Docker: false
INFO: Host writable: true
INFO: Token: xxxxxxxx
INFO: Running registration
Traceback (most recent call last):
 File "./register.py", line 11, in <module>
   secret_key=os.environ['CATTLE_REGISTRATION_SECRET_KEY'])
 File "/usr/local/lib/python2.7/dist-packages/cattle.py", line 45, in from_env
   return gdapi.from_env(prefix=prefix, factory=Client, **kw)
 File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 613, in from_env
   return _from_env(prefix=prefix, factory=factory, **args)
 File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 632, in _from_env
   return factory(**result)
 File "/usr/local/lib/python2.7/dist-packages/cattle.py", line 12, in __init__
   super(Client, self).__init__(*args, **kw)
 File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 197, in __init__
   self._load_schemas()
 File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 315, in _load_schemas
   response = self._get_response(self._url)
 File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 264, in _get_response
   headers=self._headers)
 File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 501, in get
   return self.request('GET', url, **kwargs)
 File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
   resp = self.send(prep, **send_kwargs)
 File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
   r = adapter.send(request, **kwargs)
 File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 487, in send
   raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='zyounker-rancher-ui.dev.aws.unicornmedia.com', port=443): Max retries exceeded with url: /v1 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fd486b96710>: Failed to establish a new connection: [Errno 110] Connection timed out',))

Is there another variable i can pass to stop it from using the external elb? Or is this a bug? I kinda expect it to use the URL i provide.

**Comment by vincent99** [comment]
The URL for the agents to connect to to reach the server is the Host Registration URL in Admin -> Settings.  That ends up becoming the last piece of the registration command:

sudo docker run -d --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.1.0 **proto://your-registration-url:8080**/v1/scripts/*..token..*

("proto" would be `http` or `https`, but that makes github autolink it)

**Comment by zyounker** [comment]
Is this URL also used for github access control? i believe it was set when i setup access-control. If that is the case, it will break access-control if i change to an internal DNS url for registration.


Below is the command that was executed. I will try changing the url in the admin settings. I kinda expected it would just keep the URL i gave it.

sudo docker run -e 'CATTLE_HOST_LABELS=instance-id=i-464124d3&availability-zone=us-west-2a&instance-type=t2.medium' -e CATTLE_AGENT_IP=10.0.1.62 -e CATTLE_URL=http://10.0.1.62:8080/v1 -d --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.1.0 http://10.0.2.142:8080/v1/scripts/$TOKEN
