### ISSUE TITLE
Kubelet logs have error messages :"NetworkPlugin cni failed on the status hook for pod"

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#6990]
**Rancher Version:**v1.2

**Docker Version:**1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):**Ubuntu, Cloud

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**Single node

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Kubernetes

**Steps to Reproduce:**
1. Create a Kubernetes environment.
2. Create pods

**Results:** 
Kubelet logs have the below error messages for each pod created:
```
NetworkPlugin cni failed on the status hook for pod 'xyz' - Unexpected address output
```

**Comment by leodotcloud** [comment]
The error message mentioned in the issue is harmeless, but it's misleading.
This could be due to potential race condition in kubelet: https://github.com/kubernetes/kubernetes/issues/25281

**Comment by leodotcloud** [comment]
@soumyalj Not sure if you are still seeing this issue in the latest releases of Rancher/k8s? Probably we can close this issue?
