### ISSUE TITLE
Rancher with selfsigned Certificates doesn't work

### ISSUE THREAD

**Issue by JuergenBoe** [rancher/rancher#6993]
**Rancher Version:**
1.2.0 and 1.1.4
**Docker Version:**
1.10.3
**OS and where are the hosts located? (cloud, bare metal, etc):**
RedHat Server Release 7.2  Datacenter
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA Rancher, internal DB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
Following these instructions:
http://docs.rancher.com/rancher/v1.2/en/installing-rancher/installing-server/basic-ssl-config/#using-self-signed-certs-beta
**Results:** 
All works fine until you want to add your first stack. It gets stuck in "Networking":
"Timeout getting IP-Adress" in the IPSec Container

**Comment by tfiduccia** [comment]
@JuergenBoe this is a duplicate.  Closing in favor of #6891.  In the meantime you can manually fix this issue.  Here are the steps:
1.  Export the cert from the CA as a Base 64 encoded cert.
2.  Attach the cert to the container as normal.
3.  Get inside the Rancher Server container and navigate to the java security directory
4.  Run the keytool utility to add the cert to the trusted Java cacert keystore. keytool -import -trustcerts -file /ca.crt -alias myca -keystore ./cacerts
5.  Restart the rancher container.

**Comment by aemneina** [comment]
This works for the past few major versions. If you have issues with 1.5+, please create a new ticket.
