### ISSUE TITLE
[K8S] Applications deployed from catalog showed in both stacks and infra stacks view

### ISSUE THREAD

**Issue by pengjiang80** [rancher/rancher#6994]
Steps to repro:

1. Build a k8s environment.
2. Deploy application from catalog. For example, prometheus or guestbook.
3. Applications showed in both stack view and infra stacks, which should only be showed in stack view. 

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.2.0` Cattle: `v0.174.3` UI: `v1.2.34` |
|Access|`Disabled`|
|Orchestration|`Kubernetes`|
|Route|`stacks.index`|

**Comment by tfiduccia** [comment]
Version - v1.2.0
We are showing empty infrastructure stacks.  Need to hide Stacks where kind = kubernetesStack

![image](https://cloud.githubusercontent.com/assets/11514927/21060838/cb6eca26-be06-11e6-88f1-d7af74315ec5.png)

![image](https://cloud.githubusercontent.com/assets/11514927/21060828/c17c600a-be06-11e6-9107-bd4b3a6dceb0.png)

**Comment by tfiduccia** [comment]
Version - master 11/19
Verified fixed
