### ISSUE TITLE
UI Freeze  / executor of rancher/server is under water

### ISSUE THREAD

**Issue by GregoireW** [rancher/rancher#6995]
**Rancher Version: 1.2.0**

**Docker Version: 1.12.3**

**OS and where are the hosts located? : RHEL7 on AMZ**

**Setup Details: single node rancher  with external DB**

**Environment Type: Cattle**

**Steps to Reproduce: create environment / do multiple add/remove of (same?) host**

**Results: UI will freeze, host will not synchronize anymore if something goes wrong on host (like docker restart, rancher main service restart...)** 

**Expected: everything good....**

I think the main issue come when we delete / add host again and again because we tested stuff.
It seems that  when the master - host link is lost, then resync become slower and slower and everything finish  to be stuck (host cannot synchronize anymore ...)

When this happen, UI is not responding,  the endpoint "identities" is blocked indefinitely.  

I trace the issue to the executorService that is too slow to process task (2 task added to list when executor process only 1).

I proposed the #https://github.com/rancher/cattle/pull/2294  PR to fix the UI issue. 

Now the core issue is not resolved.  
We could force to set a timeout on every task we put in the executor ( via  io/cattle/platform/async/utils/AsyncUtils.java  for instance) but anyway, some task are added directly in the executor waiting list. 
We could also force full async use on task but seems a big task...

I join a stack  of the VM with executor full  to show you the slow task,  On my end, I'm worried to make some change that can impact core stuff.
 
[stack.txt](https://github.com/rancher/rancher/files/642350/stack.txt)

**Comment by ibuildthecloud** [comment]
Thank you for the thread dump, that helps a lot.

**Comment by ibuildthecloud** [comment]
The root cause is basically that the UI (frontend) async tasks are being scheduled to a pool that is blocked by backend tasks.  This shouldn't happen.  It appears some backend tasks are getting scheduled to the wrong thread pool.

**Comment by GregoireW** [comment]
Can it be because we migrate from 1.0 to 1.1 then 1.2 ?   so that some db stuff get mixed up?

**Comment by ibuildthecloud** [comment]
@GregoireW This is basically just a bug introduced in 1.2.  The thread pools were changed and this one task type seemed to be misplaced.

**Comment by sangeethah** [comment]
Tested the following scenarios using v1.2.1-rc1:

Had a K8s env with 3 hosts.
Had few Service/RC/pods running.
Deleted all the hosts.

UI took ~20 secs to respond. But it loaded successfully after that.

Had a cattle env where there were 30 services that were stuck in "activation" state because of allocation failures.
Able to launch UI successfully.

Issue I see is the following:
Adding new host is stuck in "provisioning" state.
Starting new container is stuck in "registering" state.
