### ISSUE TITLE
OpenLDAP integration not searching nested subtree

### ISSUE THREAD

**Issue by beenanner** [rancher/rancher#6997]
http://www.novell.com/support/kb/doc.php?id=7006929

 Search

Dec  5 14:38:55 sles10sp3 slapd[29566]: SRCH "o=novell" 2 3
Dec  5 14:38:55 sles10sp3 slapd[29566]:     0 0 0
Dec  5 14:38:55 sles10sp3 slapd[29566]:     filter: (cn=admin)
Dec  5 14:38:55 sles10sp3 slapd[29566]:     attrs:
Dec  5 14:38:55 sles10sp3 slapd[29566]:  sn
Dec  5 14:38:55 sles10sp3 slapd[29566]:  cn

The first line consists of four arguments.

Field 2 - Search base

Field 3 - Scope

0 - base
1 - one
2 - subtree

Field 3 is the important part. It doesn't appear to be searching the subtrees in the "Scope"

584ad56e SRCH "dc=example,dc=com" 0 3    0 0 0
vs
584ad527 SRCH "dc=example,dc=com" 2 0    0 0 0

**Rancher Version:**

1.2

**Docker Version:**

1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):**

Ubuntu 14.04 - VM

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

Single node rancher - internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

N/A

**Steps to Reproduce:**
- Setup OpenLDAP via the Web UI

**Results:** 

```
* Not Working * rancher ldap connection

584ad56e <<< dnPrettyNormal: <dc=example,dc=com>, <dc=example,dc=com>
584ad56e SRCH "dc=example,dc=com" 0 3    0 0 0
ber_scanf fmt (m) ber:
584ad56e     filter: (objectClass=*)
ber_scanf fmt ({M}}) ber:
```
**Expected:**
```
* Working * ldapsearch

584ad527 <<< dnPrettyNormal: <dc=example,dc=com>, <dc=example,dc=com>
584ad527 SRCH "dc=example,dc=com" 2 0    0 0 0
ber_scanf fmt ({mm}) ber:
584ad527     filter: (objectClass=*)
```

**Comment by rocketeer125** [comment]
Same issue here.

Rancher Server v1.2.1, 3-node HA, external DB.
This was originally working in v1.1.4.

**Comment by aemneina** [comment]
@prachidamle @mrajashree not sure if you guys know if this works in more modern versions of rancher? I'm suspecting it might.
