### ISSUE TITLE
Allow custom certified flags with a different color

### ISSUE THREAD

**Issue by vincent99** [rancher/rancher#6999]
Allow users to put in their own certified label with a different color to distinguish from ours.

- Yellow: `rancher` - Rancher-certified only, displays "Certified".  Must come from the `library` catalog.
- Green: `partner` - Partner-certified only, displays "Parter".  May come from any catalog name.
- Blue: `Arbitrary string provided by the user`, displays that string.
- Custom string cannot be "Certified" or "Rancher".

**Comment by tfiduccia** [comment]
Version - master 11/13
Verified fixed
