### ISSUE TITLE
UI: More than 120 containers and hosts page doesn't load

### ISSUE THREAD

**Issue by bacheson** [rancher/rancher#7000]
**Rancher Version:**
1.2 

**Docker Version:**
1.12.1

**OS and where are the hosts located? (cloud, bare metal, etc):**
Bare metal / Ubuntu 16.04 LTS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
cattle

**Steps to Reproduce:**
spin up 120 containers and navigate back and forth to hosts page

**Results:** 
ui locks up

**Expected:**
not lockup

**Comment by GregoireW** [comment]
Hello,

Check if it is the  "identities" endpoint that is the one that is slow. If so guessing it is linked to https://github.com/rancher/rancher/issues/6995

**Comment by aemneina** [comment]
@bacheson is this reproducible for you on 1.5.9+? The UI/API's have undergone optimizations.

**Comment by bacheson** [comment]
nope...it's loads now and never becomes unresponsive...i'd still call it sluggish but it's working so that's the important thing

**Comment by aemneina** [comment]
awesome, going to close this out.
