### ISSUE TITLE
Allow being able to send `rancher/none` as image and not try to pull image (without selector)

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#7001]
Currently to create some of our other types of services without actually creating containers, we have sent special image names or `rancher/none` and a selector. 

We should be able to just use `rancher/none` and it shouldn't try to pull an image.

**Comment by alena1108** [comment]
@deniseschannon should be resolved in 2.0

**Comment by deniseschannon** [comment]
@alena1108 in 2.0, if I  pass in a simple compose file using the `rancher/none` image, I get this error: 
```
Bad response statusCode [422]. Status [422 Unprocessable Entity]. Body: [code=InvalidOption, fieldName=Image is required when selector is not passed in, baseType=error] from [http://localhost:8080/v3/projects/1a5/services]
```

Compose file
```
test:
  image: rancher/none
```

**Comment by deniseschannon** [comment]
No longer applicable for 2.0.
