### ISSUE TITLE
Null Propertie secondaryLaunchConfigs after creating service.

### ISSUE THREAD

**Issue by jagarzone6** [rancher/rancher#7002]
After a Service is created using rancher GUI in Cattle orchestration,
when trying to read service config and upgrade the service from the API,
the upgrade fails because secondaryLaunchConfigs property comes null from the API get service. 

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.1.4` Cattle: `v0.165.8.4` UI: `v1.1.14` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`environments.index`|

**Comment by aemneina** [comment]
@jagarzone6 Is this issue present in a newer version of rancher?

**Comment by jagarzone6** [comment]
just confirmed is in version :
![selection_304](https://user-images.githubusercontent.com/16311777/29292134-9a8e5908-810b-11e7-8526-9e9b4ef4bc26.png)


Component | Version
-- | --
Rancher | v1.5.10
Cattle | v0.178.14
User Interface | v1.5.9
Rancher CLI | v0.5.3
Rancher Compose | v0.12.5

**Comment by jagarzone6** [comment]
Now is not failing but is setting to default all service properties previous load when i created the stack from exported file.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
