### ISSUE TITLE
Bundle helm and dashboard with rancher kubernetes

### ISSUE THREAD

**Issue by wlan0** [rancher/rancher#7003]
When rancher kubernetes starts, then helm and dashboard should be running on it as a core service.

**Comment by galal-hussein** [comment]
The dashboard is up and running on kubernetes successfully.

@wlan0 please let me know when this bug is resolved https://github.com/rancher/rancher/issues/7005 to be able to test Helm properly.

**Comment by wlan0** [comment]
Addressed by 
https://github.com/rancher/kubernetes-package/pull/19
https://github.com/rancher/kubectld/pull/14/files

**Comment by galal-hussein** [comment]
Rancher version: master version
Rancher catalog - branch v1.3.0-rc2
kubernetes version: rancher/k8s:v1.5.1-rancher1-6

Validated helm by installing Deis workflow and installing a custom helm chart.
