### ISSUE TITLE
Deleting service linked to load balancer causes API error

### ISSUE THREAD

**Issue by accoleon** [rancher/rancher#7004]
**Rancher Version:**
v.1.2.0
**Docker Version:**
1.12.3
**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04.1, VMs on Hyper-V and ESXi (3 nodes)
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node, internal db
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
1. Create any 2 services in one or more stacks
2. Create a "global" load balancer in a separate stack
3. Setup service rules for the 2 services
4. Remove one of the services created in step 1
5. Attempt to Upgrade/Edit the load balancer

**Results:** 
Attempting to Edit the load balancer will produce an API Error: Name must be set, even if you didn't make any changes to the service rules.
**Expected:**
Successful edit of load balancer service rules
![image](https://cloud.githubusercontent.com/assets/115630/21069925/9b0c560a-be33-11e6-9243-2ec3c5f229b4.png)

My suspicion is the removal of a service does not remove the corresponding service rule in the (global) load balancer, despite the UI not showing it (name must be filled probably references a null entry when the service is deleted).

So far, the only way I could get past this is to delete the load balancer service and recreate it.

**Comment by alena1108** [comment]
@accoleon are you changing any field on the step 5) upgrade/edit?  I can't reproduce the issue on the latest. @deniseschannon could you give it a try too?

**Comment by accoleon** [comment]
@alena1108 It happens whether or not I change any fields in step 5. I'll add more screenshots when I get off work.

**Comment by alena1108** [comment]
@accoleon thank you! Could you also get:

1)  the output of the following API on the LB service after the target service is removed? 

http://localhost:8080/v2-beta/projects/1a5/loadbalancerservices/<lb service id>

I'm interested in portRules section

2) The API request that UI sends on update.

We'd like to address this issue in the upcoming release, and could use all the above info to nail it down.

**Comment by deniseschannon** [comment]
@alena1108 @accoleon I was unable to reproduce on my v1.2.0 setup. I followed the directions per the original post. 

When you added the service rules what kind of rules were made?

**Comment by accoleon** [comment]
This is my starting configuration, C1 and C2 stack each having 1 service:
![image](https://cloud.githubusercontent.com/assets/115630/21126277/1699e4e0-c0a0-11e6-8088-f6ebded95d24.png)
I add 2 HTTPS service rules to a global load balancer, pointing to C1 and C2 respectively, cert from LetsEncrypt stack:
![image](https://cloud.githubusercontent.com/assets/115630/21126352/788485d4-c0a0-11e6-80ac-1bf3f4f123b7.png)
Stickiness being the only other customization:
![image](https://cloud.githubusercontent.com/assets/115630/21126367/93727d24-c0a0-11e6-9f55-6cba90516d89.png)
Delete C1:
![image](https://cloud.githubusercontent.com/assets/115630/21126415/d1e9756c-c0a0-11e6-9a0e-8b4ba854e0da.png)
Leaving only C2:
![image](https://cloud.githubusercontent.com/assets/115630/21126426/e4f330d0-c0a0-11e6-8a5b-7d5e6bac0bdb.png)
This is how the load balancer looks like when I Upgrade/Edit it:
![image](https://cloud.githubusercontent.com/assets/115630/21126440/f896b0f8-c0a0-11e6-8d7d-62f1b60c7324.png)
Clicking on Edit...:
![image](https://cloud.githubusercontent.com/assets/115630/21126445/0514d3f0-c0a1-11e6-86f7-9edce657e180.png)
Output from v2-beta/projects/1a5/loadbalancerservices:
https://gist.github.com/accoleon/629b122ca4d1c4db05a886766a2aca66
API request on update:
https://gist.github.com/accoleon/3f3d2de0945d001ab91e59572acd26e3
API response on update:
https://gist.github.com/accoleon/bb760be6524a55473c8e2798308c6c20

**Comment by alena1108** [comment]
@accoleon this issue is caused by some api field not being nullable (while it should be) for cookie policy. Thanks for helping to debug!

**Comment by sangeethah** [comment]
@alena1108 , tested with v1.2.1-rc2
I am still able to reproduce the issue.
Editing LB service fails with the following error -
```
{"id":"8a06a8d4-7651-4da0-8801-26948fd06406","type":"error","links":{},"status":422,"code":"NotNullable","message":null,"detail":null,"fieldName":"name","baseType":"error","actionLinks":{}}
```

**Comment by alena1108** [comment]
Looks like the commit wasn't cherry-picked to 1.2.1 branch:

```
commit fc8a74dcb13907411c6dd01fbef5f5761aad80b5
Author: Alena Prokharchyk <alena@rancher.com>
Date:   Tue Dec 13 11:28:24 2016 -0800

    cookie policy name is nullable
```

**Comment by sangeethah** [comment]
Tested with v1.2.1-rc3.
Able to edit Lb service with cookie policy set after one of the targets linked to it was deleted.
