### ISSUE TITLE
Kubernetes fails on fresh install 

### ISSUE THREAD

**Issue by alexanderdavidsen** [rancher/rancher#7006]
Rancher Version: 1.2.0
Docker Version: 1.12.3
OS and where are the hosts located? (cloud, bare metal, etc): rancherOS on VMWare (2 vCPUs 2GiB memory)

Setup Details: 
- Single node rancher
- Five rancherOS hosts, three with tag etcd and two with orchestration=true

Environment Type: Kubernetes

Steps to Reproduce: 
 - Clean install, trying to deploy kubernetes. All services except kubelets are starting. Kubelets fails on all hosts. 

Results: Kubelet containsers fails with the following error:

> 10.12.2016 17.53.48[signal 0xb code=0x1 addr=0x0 pc=0x128d595]
> 10.12.2016 17.53.48
> 10.12.2016 17.53.48goroutine 96 [running]:
> 10.12.2016 17.53.48panic(0x30c29e0, 0xc8200160c0)
> 10.12.2016 17.53.48	/usr/local/go/src/runtime/panic.go:481 +0x3e6
> 10.12.2016 17.53.48k8s.io/kubernetes/pkg/cloudprovider/providers/rancher.(*CloudProvider).InstanceID(0xc82027bb00, 0x7ffd43a25454, 0x7, 0x0, 0x0, 0x0, 0x0)
> 10.12.2016 17.53.48	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/cloudprovider/providers/rancher/rancher.go:651 +0x175
> 10.12.2016 17.53.48k8s.io/kubernetes/pkg/cloudprovider/providers/rancher.(*CloudProvider).ExternalID(0xc82027bb00, 0x7ffd43a25454, 0x7, 0x0, 0x0, 0x0, 0x0)
> 10.12.2016 17.53.48	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/cloudprovider/providers/rancher/rancher.go:640 +0x13c
> 10.12.2016 17.53.48k8s.io/kubernetes/pkg/kubelet.(*Kubelet).initialNode(0xc8201e6000, 0x7ffd43a25454, 0x0, 0x0)
> 10.12.2016 17.53.48	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet_node_status.go:226 +0x94c
> 10.12.2016 17.53.48k8s.io/kubernetes/pkg/kubelet.(*Kubelet).getNodeAnyWay(0xc8201e6000, 0x0, 0x0, 0x0)
> 10.12.2016 17.53.48	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet_getters.go:208 +0xb3
> 10.12.2016 17.53.48k8s.io/kubernetes/pkg/kubelet.(*Kubelet).initializeModules(0xc8201e6000, 0x0, 0x0)
> 10.12.2016 17.53.48	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1120 +0x434
> 10.12.2016 17.53.48k8s.io/kubernetes/pkg/kubelet.(*Kubelet).Run(0xc8201e6000, 0xc820a84a80)
> 10.12.2016 17.53.48	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1162 +0x2d9
> 10.12.2016 17.53.48k8s.io/kubernetes/cmd/kubelet/app.startKubelet.func1()
> 10.12.2016 17.53.48	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubelet/app/server.go:721 +0x3f
> 10.12.2016 17.53.48k8s.io/kubernetes/pkg/util/wait.JitterUntil.func1(0xc820163a80)
> 10.12.2016 17.53.48	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:84 +0x19
> 10.12.2016 17.53.48k8s.io/kubernetes/pkg/util/wait.JitterUntil(0xc820163a80, 0x0, 0x0, 0x1, 0xc82001c600)
> 10.12.2016 17.53.48	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:85 +0xb4
> 10.12.2016 17.53.48k8s.io/kubernetes/pkg/util/wait.Until(0xc820163a80, 0x0, 0xc82001c600)
> 10.12.2016 17.53.48	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:47 +0x43
> 10.12.2016 17.53.48created by k8s.io/kubernetes/cmd/kubelet/app.startKubelet
> 10.12.2016 17.53.48	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubelet/app/server.go:721 +0xb8
> 10.12.2016 17.55.01+ curl -s -f http://rancher-metadata/2015-12-19/stacks/Kubernetes/services/kubernetes/uuid
> 10.12.2016 17.55.01+ echo Waiting for metadata
> 10.12.2016 17.55.01Waiting for metadata
> 10.12.2016 17.55.01+ sleep 1
> 10.12.2016 17.55.02+ curl -s -f http://rancher-metadata/2015-12-19/stacks/Kubernetes/services/kubernetes/uuid
> 10.12.2016 17.55.02++ curl -s http://rancher-metadata/2015-12-19/stacks/Kubernetes/services/kubernetes/uuid
> 10.12.2016 17.55.02+ UUID=bdc7c654-005e-4ed0-bda3-b9fe3f44b04d
> 10.12.2016 17.55.02++ jq -r '.data[0].actions.certificate'
> 10.12.2016 17.55.02++ curl -s -u XXX:XXX 'http://XXX:9090/v1/services?uuid=bdc7c654-005e-4ed0-bda3-b9fe3f44b04d'
> 10.12.2016 17.55.02+ ACTION='http://XXX:9090/v1/services/1s37/?action=certificate'
> 10.12.2016 17.55.02+ KUBERNETES_URL=https://kubernetes:6443
> 10.12.2016 17.55.02+ '[' -n 'http://XXX:9090/v1/services/1s37/?action=certificate' ']'
> 10.12.2016 17.55.02+ mkdir -p /etc/kubernetes/ssl
> 10.12.2016 17.55.02+ cd /etc/kubernetes/ssl
> 10.12.2016 17.55.02+ curl -s -u XXX:XXX -X POST 'http://XXX:9090/v1/services/1s37/?action=certificate'
> 10.12.2016 17.55.02+ unzip -o certs.zip
> 10.12.2016 17.55.02bdc7c654-005e-4ed0-bda3-b9fe3f44b04dArchive:  certs.zip
> 10.12.2016 17.55.02  inflating: ca.pem
> 10.12.2016 17.55.02  inflating: cert.pem
> 10.12.2016 17.55.02  inflating: key.pem
> 10.12.2016 17.55.02+ cd /
> 10.12.2016 17.55.02+ cat
> 10.12.2016 17.55.02+ '[' kubelet == kubelet ']'
> 10.12.2016 17.55.02+ mount --rbind /host/dev /dev
> 10.12.2016 17.55.02++ hostname --fqdn
> 10.12.2016 17.55.02+ FQDN=rancher
> 10.12.2016 17.55.02+ exec kubelet --kubeconfig=/etc/kubernetes/ssl/kubeconfig --api_servers=https://kubernetes.kubernetes.rancher.internal:6443 --allow-privileged=true --register-node=true --cloud-provider=rancher --healthz-bind-address=0.0.0.0 --cluster-dns=169.254.169.250 --cluster-domain=cluster.local --network-plugin=cni --network-plugin-dir=/etc/cni/managed.d --hostname-override rancher
> 10.12.2016 17.55.03Flag --api-servers has been deprecated, Use --kubeconfig instead. Will be removed in a future version.
> 10.12.2016 17.55.03I1210 16:55:03.401457    7189 docker.go:375] Connecting to docker on unix:///var/run/docker.sock
> 10.12.2016 17.55.03I1210 16:55:03.402476    7189 docker.go:395] Start docker client with request timeout=2m0s
> 10.12.2016 17.55.03I1210 16:55:03.417836    7189 manager.go:143] cAdvisor running in container: "/docker/c2476d9b452752073f8d979228624321d3dac2184b47fa47fa4195039007a21e/docker/f6cd6f9cf27fd82c32b0f8466475e3592bbeeed4fe55b97753d923e58f640e78"
> 10.12.2016 17.55.03W1210 16:55:03.438386    7189 manager.go:151] unable to connect to Rkt api service: rkt: cannot tcp Dial rkt api service: dial tcp [::1]:15441: getsockopt: connection refused
> 10.12.2016 17.55.03I1210 16:55:03.450513    7189 fs.go:117] Filesystem partitions: map[/dev/sda1:{mountpoint:/var/lib/docker/overlay major:8 minor:1 fsType:ext4 blockSize:0}]
> 10.12.2016 17.55.03I1210 16:55:03.454345    7189 manager.go:198] Machine: {NumCores:2 CpuFrequency:2397223 MemoryCapacity:2098987008 MachineID:f3e41f31b6024d84806ddf3a54075add SystemUUID:420F5260-0562-9BFA-20A1-2D89233736D6 BootID:af33b6aa-16d9-465d-80b6-0ebb7dfdcb3f Filesystems:[{Device:/dev/sda1 Capacity:19995947008 Type:vfs Inodes:5242880 HasInodes:true} {Device:overlay Capacity:19995947008 Type:vfs Inodes:5242880 HasInodes:true}] DiskMap:map[8:0:{Name:sda Major:8 Minor:0 Size:21474836480 Scheduler:cfq}] NetworkDevices:[{Name:eth0 MacAddress:00:50:56:8f:1d:b1 Speed:1000 Mtu:1500}] Topology:[{Id:0 Memory:2098987008 Cores:[{Id:0 Threads:[0] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]}] Caches:[{Size:15728640 Type:Unified Level:3}]} {Id:2 Memory:0 Cores:[{Id:0 Threads:[1] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]}] Caches:[{Size:15728640 Type:Unified Level:3}]}] CloudProvider:Unknown InstanceType:Unknown InstanceID:None}
> 10.12.2016 17.55.03I1210 16:55:03.455691    7189 manager.go:204] Version: {KernelVersion:4.4.24-rancher ContainerOsVersion:Debian GNU/Linux 8 (jessie) DockerVersion:1.12.3 CadvisorVersion: CadvisorRevision:}
> 10.12.2016 17.55.03I1210 16:55:03.458517    7189 kubelet.go:262] Watching apiserver
> 10.12.2016 17.55.03W1210 16:55:03.461165    7189 kubelet_network.go:71] Hairpin mode set to "promiscuous-bridge" but configureCBR0 is false, falling back to "hairpin-veth"
> 10.12.2016 17.55.03I1210 16:55:03.461210    7189 kubelet.go:513] Hairpin mode set to "hairpin-veth"
> 10.12.2016 17.55.03I1210 16:55:03.470453    7189 docker_manager.go:242] Setting dockerRoot to /var/lib/docker
> 10.12.2016 17.55.03I1210 16:55:03.490376    7189 server.go:714] Started kubelet v1.4.6-rancher1
> 10.12.2016 17.55.03E1210 16:55:03.490659    7189 kubelet.go:1091] Image garbage collection failed: unable to find data for container /
> 10.12.2016 17.55.03I1210 16:55:03.491091    7189 kubelet_node_status.go:203] Setting node annotation to enable volume controller attach/detach
> 10.12.2016 17.55.03I1210 16:55:03.491170    7189 rancher.go:639] ExternalID [rancher]
> 10.12.2016 17.55.03I1210 16:55:03.491223    7189 rancher.go:645] InstanceID [rancher]
> 10.12.2016 17.55.03I1210 16:55:03.498040    7189 server.go:118] Starting to listen on 0.0.0.0:10250
> 10.12.2016 17.55.03panic: runtime error: invalid memory address or nil pointer dereference
> 10.12.2016 17.55.03[signal 0xb code=0x1 addr=0x0 pc=0x128d595]

Expected: Kubelet containsers should start.

**Comment by alexanderdavidsen** [comment]
Did some more testing, running rancherOS v0.6.1 seems to be working. The kubelet container starts without any issues.

**Comment by alexanderdavidsen** [comment]
I just tested with the latest version of CoreOS (CoreOS stable (1185.5.0)), and kubelet is starting just fine...

**Comment by deniseschannon** [comment]
One of the use cases tested is Kubernetes on RancherOS v0.7.1. 

How are you deploying kubernetes? Through the kubernetes environment templates? or through the catalog?

**Comment by alexanderdavidsen** [comment]
I tried deploying via the environment templates.

**Comment by alexanderdavidsen** [comment]
Tried to deploy again on a fresh install using Kubernetes from the Catalog. Got the same issues. I also tried to deploy without setting etcd=true and orchestration=true on some of the nodes. I still get the same error. 

This seems to be a problem with the kubelet container it self. Which template version where you using?

**Comment by alexanderdavidsen** [comment]
Fully patched CentOS 7 with latest docker for docker.io works just fine.

**Comment by alexanderdavidsen** [comment]
Making sure no hosts had the same hostname seems to have fixed the issue...

**Comment by deniseschannon** [comment]
So you're up and running now?

**Comment by alexanderdavidsen** [comment]
Almost. I'm not able to get heapster running. But that's probably not related to Rancher...

**Comment by aemneina** [comment]
This should be more robust as of 1.5+. Closing this out.
