### ISSUE TITLE
DNS Issue with 1.2.0

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#7010]
@DomiStyle pointed out this in another issue (https://github.com/rancher/rancher/issues/6858) a

I  was able to find the cause of this problem and solve it. Since Rancher keeps reporting it can't get some IP address I started sniffing all DNS queries on my DNS server and found the following:

Dec 9 19:13:46 	unbound 	51000:0 	info: 192.168.1.xxx rancher-metadata.example.org. A IN
Dec 9 19:13:42 	unbound 	51000:0 	info: 192.168.1.xxx rancher-metadata.example.org. A IN
(where example.org is my internal domain)

Obviously this isn't supposed to happen, *.example.org will always resolve to my public IP unless it is overwritten by the local DNS server. I never bothered changing this since I didn't think it would cause any issues.

Anyways, *.example.org will not resolve on my internal network anymore unless it is defined internally. This fixed the issue. Rancher will still issue the useless DNS request but won't get a valid response anymore.

I still think this probably should be fixed? I doesn't look like this DNS lookup should reach the network.

**Comment by nhumrich** [comment]
Not sure if this is related or not. But there appears to be an issue with dns for the same host as well.

In rancher 1.1.4 if I exec into any container and run:
```
nslookup $(hostname)
```
I get an ip address. 

If I run this in rancher 1.2, I get the following.

```
Can't resolve 'xxxx'. Name does not resolve.
```
This really should work for any container in the stack, but I cant even get it to work for the same container that I am on.

**Comment by vincent99** [comment]
@nhumrich Separate problem, https://github.com/rancher/rancher/issues/6855 .

**Comment by deniseschannon** [comment]
We added a new label, io.rancher.container.dns.priority: service_last`. 

By default the Rancher service discovery domain`*.rancher.internal` will be searched before the path(s) configured on the host.  Set this label to use the search path of the host before the Rancher domain

**Comment by sangeethah** [comment]
Tested with v1.2.1-rc3

On the GCE hosts:
```search c.rancher-qa.internal google.internal``

container on v1.2.1-rc3
```search default.rancher.internal hellotest.default.rancher.internal rancher.inter
nal c.rancher-qa.internal google.internal```

container on v1.2.1-rc2
```search c.rancher-qa.internal google.internal test1.test.rancher.internal test.ra
ncher.internal rancher.internal```

container on v1.1.4
```search c.rancher-qa.internal google.internal hello.rancher.internal test1.hello.
rancher.internal rancher.internal```

**Comment by ibuildthecloud** [comment]
@sangeethah Something is wrong because the service domains shouldn't be in a different order.

**Comment by ibuildthecloud** [comment]
@sangeetha.  Okay, rc2 was bad but rc3 is right.  I don't know what was up with rc2, but from 1.1.4 to rc3 you can see that just the host search was moved from front to back

**Comment by sangeethah** [comment]
Tested with v1.2.1-rc3

On the GCE hosts:
search c.rancher-qa.internal google.internal

When container are deployed with label - ```io.rancher.container.dns.priority: service_last```:

```search c.rancher-qa.internal google.internal default.rancher.internaltestoldway.default.rancher.internal rancher.internal```

When container are deployed without  dns priority label:
 ```
search default.rancher.internal testnew.default.rancher.internal rancher.internal c.rancher-qa.internal google.internal
```
