### ISSUE TITLE
ipsec stack fails to init for k8s on rancher 1.2.0

### ISSUE THREAD

**Issue by flaccid** [rancher/rancher#7014]
**Rancher Version:**
1.2.0

**Docker Version:**
1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04 on AzureRM

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single rancher server, 1 host

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
Setup a basic Rancher server, single node. Create an environment in Rancher and add the host to the environment. Watch service containers and spin up with quite a few fail, in particular this ticket is for ipsec stack (rancher-net).

**Results:** 
Container exits after a failed PUT.
```
+ trap 'exit 1' SIGTERM SIGINT
+ export CHARON_PID_FILE=/var/run/charon.pid
+ CHARON_PID_FILE=/var/run/charon.pid
+ rm -f /var/run/charon.pid
+ export PIDFILE=/var/run/rancher-net.pid
+ PIDFILE=/var/run/rancher-net.pid
+ GCM=false
+ (( i=0 ))
+ (( i<6 ))
+ ip xfrm state add src 1.1.1.1 dst 1.1.1.1 spi 42 proto esp mode tunnel aead 'rfc4106(gcm(aes))' 0x0000000000000000000000000000000000000001 128 sel src 1.1.1.1 dst 1.1.1.1
+ GCM=true
+ ip xfrm state del src 1.1.1.1 dst 1.1.1.1 spi 42 proto esp
+ break
+ mkdir -p /etc/ipsec
+ curl -f -u B196D6A3D4F3E467B8A1:BDsT6ttB1YdNFWeinDbTdjpKKkD66AeCkN5Mt4zA http://myrancher.com/v1/configcontent/psk
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    32  100    32    0     0   1696      0 --:--:-- --:--:-- --:--:--  1777
+ curl -f -X PUT -u B196D6A3D4F3E467B8A6:BDsT6ttB1YdNFWeinDbTdjpKKkD66AeCkN5Mt4zA 'http://myrancher.com/v1/configcontent/psk?version=latest'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 411 Length Required
```

**Expected:**
Container runs and stack goes green.

From what I can see, https://github.com/rancher/rancher-net/blob/master/package/start.sh#L24 should probably be a `GET` and not a `PUT` ? A `GET` will return a value such as `8828ddde95d346a10720ba7eeb54a612`. Note that it looks like the curl output isn't redirected to a file currently either.

**Comment by vincent99** [comment]
Do you have a proxy/balancer/etc in front of your server container?  This should just trigger an update, does not need a body, and returns 200 for me..

```
root@bf6dd06b9e42:/# curl -v -f -X PUT -u ${CATTLE_ACCESS_KEY}:${CATTLE_SECRET_K
EY} ${CATTLE_URL}/configcontent/psk?version=latest
*   Trying a.b.c.d...
* Connected to a.b.c.d (a.b.c.d) port 8080 (#0)
* Server auth using Basic with user '<user>'
> PUT /v1/configcontent/psk?version=latest HTTP/1.1
> Host: a.b.c.d:8080
> Authorization: Basic <base64>
> User-Agent: curl/7.47.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Length: 0
< Date: Mon, 12 Dec 2016 06:37:28 GMT
< Expires: Thu, 01 Jan 1970 00:00:00 GMT
< Server: Jetty(9.2.11.v20150529)
< Set-Cookie: PL=rancher;Path=/
< X-Api-Account-Id: 1a11
< X-Api-Client-Ip: a.b.c.d
< X-Api-Schemas: http://a.b.c.d:8080/v1/schemas
< Content-Type: text/plain; charset=utf-8
<
* Connection #0 to host a.b.c.d left intact
root@bf6dd06b9e42:/# echo $?
0
root@bf6dd06b9e42:/#
```

**Comment by flaccid** [comment]
Great point, I should of thought of that. An Azure App LB is in front. @writeameer let's check into it.

**Comment by vincent99** [comment]
So I'm guessing there's some arbitrary "security" rule that incorrectly thinks a body is required for a PUT, or strips out the`Content-Length: 0`...  There were other Azure-specific balancer problems in the 1.1.x HA setup (or maybe it was the same problem?)

Can you run the curl again with `-v`from an ipsec container shell?  Curious to see if it has headers that indicate the response is coming from cattle (Jetty server, X-Api-*, etc) or if it never makes it there.

Curl sends Content-Length so returning `411` doesn't really make any sense (it's for a request that does not have a defined length, and one is being explicitly sent).

**Comment by flaccid** [comment]
Looks like you are spot in, to be it short. Using `-d ""` with `curl` to give a body length works. This request comes back with `Server: Microsoft-IIS/8.5` as header, whereis with 0 length returns `Server: Microsoft-HTTPAPI/2.0` - kind of interesting. We are going to re-create the app gateway in azure to be sure and re-test - we are trying to see if there is a way to avoid the blank param.

**Comment by flaccid** [comment]
It's possible that some curl versions may add in `Content-Length: 0` however we can see that this one doesn't by looking at the request headers via `curl -v`. Much appreciated if you could add `-d ""` for v1.2.1 :)

**Comment by vincent99** [comment]
Oops, I was looking at the one in the response section.  With none in the request it is valid (though still odd) to return `411`.

**Comment by flaccid** [comment]
Its probably like app gateway trying to drop what it thinks are dud requests even though its not in WAF mode. After all, its a production from one of our favorite standards providers :)

**Comment by vincent99** [comment]
https://github.com/rancher/rancher-net/pull/30

**Comment by aemneina** [comment]
Closing, fix is in. If this occurs in rancher 1.5.9+ please file a new ticket.
