### ISSUE TITLE
Can't start osixia/openldap container from rancher 1.2 (was working with 1.2pre3 and ok from docker run command)

### ISSUE THREAD

**Issue by typia** [rancher/rancher#7015]
**Rancher Version:**
1.2
**Docker Version:**
1.12.3
**OS and where are the hosts located? (cloud, bare metal, etc):**
Debian 8
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node rancher external DB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
Since 1.2 upgrde, I can't launch osixia/openldap container.
I tried to launch it directly from with docker run and it's ok. launching it with 1.2 gives the logs below.
Was working with 1.2 pre3
**Results:** 
the container is bootlooping giving logs below 👍 

`*** CONTAINER_LOG_LEVEL = 3 (info)
*** Search service in CONTAINER_SERVICE_DIR = /container/service :
*** link /container/service/:ssl-tools/startup.sh to /container/run/startup/:ssl-tools
*** failed to link /container/service/:ssl-tools/startup.sh to /container/run/startup/:ssl-tools: [Errno 17] File exists
*** link /container/service/slapd/startup.sh to /container/run/startup/slapd
*** failed to link /container/service/slapd/startup.sh to /container/run/startup/slapd: [Errno 17] File exists
*** link /container/service/slapd/process.sh to /container/run/process/slapd/run
*** directory /container/run/process/slapd already exists
*** failed to link /container/service/slapd/process.sh to /container/run/process/slapd/run : [Errno 17] File exists
*** Set environment for startup files
*** Environment files will be proccessed in this order :
Caution: previously defined variables will not be overriden.
/container/environment/99-default/default.startup.yaml
/container/environment/99-default/default.yaml

To see how this files are processed and environment variables values,
run this container with '--loglevel debug'
*** Running /container/run/startup/:ssl-tools...
*** Running /container/run/startup/slapd...
Start OpenLDAP...
*** /container/run/startup/slapd failed with status 1

*** Killing all processes... ``

**Expected:**

Container start

**Comment by aemneina** [comment]
@typia have you seen this issue with more modern versions of rancher?

**Comment by Cygnust** [comment]
Hi @aemneina to be honest I took it out from rancher and launched it directly from the host using docker-compose.
I'm gonna try again when I have time to do some refactoring.
