### ISSUE TITLE
Service activation fails (before it eventually succeeds) when trying to start container with new image (that needs to be pulled in hosts). 

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#7017]
Rancher Version: Build from master - Dec12

Docker Version: 1.12.3

Steps to reproduce the problem:
Created a service with image - sangeetha/testupgrade:v1 (this image is not present in the host).
Container gets to "Error" state when trying to pull image.
At this point service fails to activate with this error message - ```Expected state running but got error: Image [index.docker.io/r<image name>] failed to pull: Download complete```

After couple of attempts , the new container that deployed for the service comes up successfully.

**Comment by StrongMonkey** [comment]
https://github.com/rancher/agent/pull/106

**Comment by sangeethah** [comment]
This issue is not seen when testing with v1.2.1-rc2.
