### ISSUE TITLE
agent fails to propagate NO_PROXY envs

### ISSUE THREAD

**Issue by StrongMonkey** [rancher/rancher#7019]
https://forums.rancher.com/t/rancher-agent-and-environment-variables-on-docker-run/4888

**Comment by deniseschannon** [comment]
make sure to check for case types for `http_proxy`, `https_proxy`, and `no_proxy`.

**Comment by galal-hussein** [comment]
Rancher version: v1.2.1-rc2

Tested registration of rancher/agent with the following envs:

NO_PROXY
HTTP_PROXY
HTTPS_PROXY
no_proxy
http_proxy
https_proxy

All environment variables are propagated to the rancher-agent successfully.
