### ISSUE TITLE
k8s:v1.2.4 version gets deployed when using v1.2.0-1 rancher-server.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#7021]
Rancher Version:v1.2.0-1

Create a new environment with "orchestration" set to -"kubernetes"
Add 3 hosts to the setup.
K8s infra stack comes up with version - v1.2.4-rancher10
kubelet containers are not able to start successfully and they keep restarting.

Expected behavior:
K8s infra stack should be launched with version - v1.4.6-rancher1.

There is a min version for v1.4.6-rancher1 set to  "v1.2.0-pre4-rc1” which is not working as expected.

**Comment by superseb** [comment]
Closing as stale
