### ISSUE TITLE
Rancher Server 1.2.0 SLow

### ISSUE THREAD

**Issue by artemus717** [rancher/rancher#7022]
**Rancher Version:**
1.2.0
**Docker Version:**
1.11.2
**OS and where are the hosts located? (cloud, bare metal, etc):**
CentOS Linux release 7.0.1406 (Core)
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
external DB
with Aliyun SLB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**

**Results:** 
![image](https://cloud.githubusercontent.com/assets/16465173/21126286/3dd5f8e2-c126-11e6-9c2e-785ab155c3ec.png)
Large amount of service can not start properly . When activating , the rancher agent seems do not create any container .
And the external mysql db get a high presure .
![image](https://cloud.githubusercontent.com/assets/16465173/21126427/07208870-c127-11e6-95c3-6139584125ca.png)
![image](https://cloud.githubusercontent.com/assets/16465173/21126439/144c228e-c127-11e6-9d90-4efd59c85255.png)

**Expected:**

**Comment by jashtsserie** [comment]
i want to report the same problem.
using rancher 1.2.0 on a dedicated server/host 1GB/s neet, 64GB Ram, Up to 12Cores just to lauch a container with already pulled image rancher need 5-10+ minutes! 
is there anything launched/installed wrong or this problem is for everyone?
from cli all what i need to deploy is 1-2 sec why rancher take this time?!
+' i can't delete containers! i stop them i click remove they disappear i refresh page they come back O.o!

**Comment by artemus717** [comment]
i update form rancher server 1.1.2
Now i restart docker deamon on the host , it seems better and docker-engine 1.11.0 is not good enough.

**Comment by Gmentsik** [comment]
Same here.

We operated a rancher environment for about 3 days, restarts took longer and longer, in the end no service could start up after 8 hours of waiting.

Bare metal, 32GB Ram 8-Core with SSDs

**Comment by mccricardo** [comment]
Experiencing the same issue with 1.1.4. Is very very slow. Containers take hours to start.

**Comment by vincent99** [comment]
This should be better in `1.2.1` (or if you don't want to do another upgrade soon, wait for `1.2.2` tomorrow).  @mccricardo you may have a different problem as this is specific to 1.2.0, but 1.2.x is faster in general.

**Comment by mccricardo** [comment]
We found out the issue and it was due to a large number of agents that were no longer active still showing up as reconecting.

**Comment by artemus717** [comment]
@Gmentsik I spend about 48 hours . Just a simpe action will take a long time to finish during this time . It was a nightmare.
When rancher server get ready , it's also very fast.

**Comment by artemus717** [comment]
@vincent99 1.2.1 has a good perfermance .
