### ISSUE TITLE
Random 503 Service Unavailable from Load Balancer after upgrading service or manually restarting the LB container

### ISSUE THREAD

**Issue by cjjcsu** [rancher/rancher#7024]
After upgrading a service that is a target of a load balancer service the load balancer randomly returns error 503 Service Unavailable.

It looks like the load balancer isn't updated after the service is upgraded and some connections go to the old container IP resulting in a 503 error and some connections go to the new container IP.

After stopping an starting again the load balancer service the random 503 errors stop happening.

This started happening after upgrading to rancher 0.51.0, it didn't happen in the version we had before.
see also [rancher/#3360](https://github.com/rancher/rancher/issues/3360)

**Rancher Version:**
v1.2.0
**Docker Version:**
1.12.3
**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04 LTS (4.4.0)  local machine
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**

Create a Service
Create a Load Balancer Service and add the previous service as a target
Upgrade the service (Finishing the Upgrade doesn't make a difference, the error 503 is still returned randomly after finishing the upgrade)
Connect multiple times to the load balancer IP/port linked to the target service. Some connections will succeed and some will return error 503 Service Unavailable
Restart the load balancer service
Connect multiple times to the load balancer IP/port linked to the target service. All the connections will now succeed.

**Results:** 

**Expected:**

**Comment by ebreton** [comment]
Similar here except that restarting the LB do not solve entirely the issue. I will try to get steps to reproduce on basic configuration

**Comment by igp-tech** [comment]
We are having the same issue....

**Comment by boshido** [comment]
I faced the same problem after I update rancher to 

Rancher service info
 - docker -v : Docker version 1.13.0
 - rancher : v1.5.4
 - lb image : rancher/lb-service-haproxy:v0.6.4

**Comment by deniseschannon** [comment]
The underlying issues is that we're not draining the HAProxy connections during an upgrade. This issue is tracked here: https://github.com/rancher/rancher/issues/2777
