### ISSUE TITLE
External links not working

### ISSUE THREAD

**Issue by mccricardo** [rancher/rancher#7026]
**Rancher Version:**
1.2.0

**Docker Version:**
1.12.4

**OS and where are the hosts located? (cloud, bare metal, etc):**
Metal (laptop), Ubuntu 16.04

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node Rancher. Server and Agent  running on the same host.

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Deploy `stacka` with a `servicea`. Deploy `stackb` with a `serviceb` which has an external link to a `servicea`, e.g. 
```
external_links:
 - stacka/servicea:somealias
```

**Results:** 
Using `somealias` to reference `servicea` does not work. Using the global DNS (`servicea.stacka`) works though.

**Expected:**
From `serviceb` I can reference `servicea` using `somealias`.

**UPDATE**

It seems the problem only exists when using `alpine:3.4` images: https://github.com/rancher/rancher/issues/5041. Tested using `debian:jessie` and links work correctly.

**Comment by alena1108** [comment]
@mccricardo This is a known issue with alpine images: https://github.com/gliderlabs/docker-alpine/issues/8. To workaround, you do need to append "stackName" to the link name (somealias.stacka)

**Comment by mccricardo** [comment]
Thank you @alena1108. It was working perfectly fine with Rancher 1.1.x.

**Comment by andruwa13** [comment]
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.2.1` Cattle: `v0.174.8` UI: `v1.2.39` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`stack.code`|



docker-compose.yml

>version: '2'
services:
  phpmyadmin:
    mem_limit: 268435456
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_ARBITRARY: '1'
    stdin_open: true
    external_links:
    - bankoved/db:db
    ports:
    - 4444:80/tcp
    memswap_limit: 536870912
    cpu_shares: 200
    labels:
      io.rancher.container.pull_image: always 


not work 
![phpmyadmin 2016-12-23 02-14-52](https://cloud.githubusercontent.com/assets/5846351/21444401/ab5034c8-c8b5-11e6-927b-859b5adafd52.png)

**Comment by andruwa13** [comment]
not work v1.3.0-rc3
![rancher 2016-12-30 22-04-27](https://cloud.githubusercontent.com/assets/5846351/21571872/1e94e27c-cedc-11e6-9863-ce0d0988b65d.png)
  
![phpmyadmin 2016-12-30 22-04-17](https://cloud.githubusercontent.com/assets/5846351/21571876/23da7ef4-cedc-11e6-9b78-7a1ef94b6d4d.png)

**Comment by andruwa13** [comment]
Please fix the problem

**Comment by nhumrich** [comment]
@andruwa13 There was a workaround posted by @alena1108 all you have to do is set the link name to something with a dot in it. 
So you could set your link to `mysql.db` and set the env var `PMA_HOST` to `mysql.db` and that should fix your problem.

**Comment by andruwa13** [comment]
fix to add

dns_search:
  - rancher.internal

**Comment by puttpotsawee** [comment]
@andruwa13 That actually worked for me too!

**Comment by superseb** [comment]
Seems to be working with `alpine:3.5` and `alpine:3.6`. Please file a new issue when this occurs again.
