### ISSUE TITLE
Feature Request - Add stack name to services API in addition to stackid

### ISSUE THREAD

**Issue by Rucknar** [rancher/rancher#7030]
The addition of the field would make it easier to monitor the state of the services without having to translate the stackID to a named value. 

**Rancher Version:**
1.2
**Docker Version:**
1.12
**OS and where are the hosts located? (cloud, bare metal, etc):**
RancherOS
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node Rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
Access Rancher API for services
**Results:** 
`"stackId": "1st4",` is listed.
**Expected:**
`"stackId": "1st4",`
`"stackName": "Blah",`

**Comment by aemneina** [comment]
There's a link to the stack of the service from within the service that should give you that info (checked on 1.5.9). Closing this out.
