### ISSUE TITLE
Web fonts failing to load in Firefox ("invalid version tag")

### ISSUE THREAD

**Issue by jcmcken** [rancher/rancher#7035]
**Rancher Version:**

Latest ``rancher/server`` docker image as of writing.

Specifics:

```
Component        Version
Rancher          v1.2.0
Cattle           v0.174.3
User Interface   v1.2.34
Rancher Compose  v0.12.0
```
**Docker Version:**

1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):**

RHEL7.3 instance on EC2

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

Single node rancher, launched on docker container (image: rancher/server) according to rancher.com 'Getting Started' instructions

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

N/A

**Steps to Reproduce:**

Open the web UI in Firefox after launching docker container.

**Results:** 

Web fonts show fallback unicode code point characters instead of font glyphs. Web console shows error messages such as:

```
downloadable font: invalid version tag (font-family: "rancher-icons" style:normal weight:normal stretch:normal src index:1)
source: http://<ipaddress>:8080/assets/fonts/rancher-icons-96d6a106fbfeec91978f3a3c3e7af437.woff?vvhhzm vendor-63de433e160dba7ab9a923c8a29dbb75.css
downloadable font: rejected by sanitizer (font-family: "rancher-icons" style:normal weight:normal stretch:normal src index:1)
source: http://<ipaddress>:8080/assets/fonts/rancher-icons-96d6a106fbfeec91978f3a3c3e7af437.woff?vvhhzm vendor-63de433e160dba7ab9a923c8a29dbb75.css
downloadable font: no supported format found (font-family: "rancher-icons" style:normal weight:normal stretch:normal src index:3)
source: (end of source list)
```

Looking at the network tab of the web console, all of the relevant assets appear to download successfully.

**Expected:**

Web fonts are displayed correctly.

**Comment by aemneina** [comment]
Not sure if youve tried this recently @jcmcken , would be good to know if this is still an issue for you. I'll close this, if you holler and can reproduce on a newer version, we can reopen.
