### ISSUE TITLE
(null): Name is required error showing up for sidekicks without names

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#7038]
**Rancher Version:** v1.2.0

**Steps to Reproduce:**
1.  Add service
2.  Add two sidekicks but don't fill out name
3.  Click on create

**Results:** (null): Name is required error showing up 
![image](https://cloud.githubusercontent.com/assets/11514927/21160031/a35915a4-c140-11e6-9424-4f317053ac7e.png)

**Expected:**  Might want to replace null with sidekick1, sidekick2.  Or just maybe sidekick so they where to look.

**Comment by vincent99** [comment]
Changed in 2.0..

**Comment by tfiduccia** [comment]
Version - master 9/15
Verified
