### ISSUE TITLE
Dashboard is failing on kubernetes 1.5

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#7044]
**Rancher Version:**
master build (14 Dec)
**Docker Version:**
1.12
**OS and where are the hosts located? (cloud, bare metal, etc):**
ubuntu 16.04
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes 1.5 (vnext branch)
**Steps to Reproduce:**

- Set the library catalog to rancher-catalog with branch vnext.
- install kubernetes 1.5

**Results:** 
dashboard container is failing with the following error message:
```
12/14/2016 2:36:17 AMUsing HTTP port: 9090
12/14/2016 2:36:17 AMUsing apiserver-host location: http://Kubernetes.kubernetes:80
12/14/2016 2:36:17 AMCreating API server client for http://Kubernetes.kubernetes:80
12/14/2016 2:36:47 AMError while initializing connection to Kubernetes apiserver. This most likely means that the cluster is misconfigured (e.g., it has invalid apiserver certificates or service accounts configuration) or the --apiserver-host param points to a server that does not exist. Reason: Get http://Kubernetes.kubernetes:80/version: dial tcp: i/o timeout
12/14/2016 2:36:47 AMRefer to the troubleshooting guide for more information: https://github.com/kubernetes/dashboard/blob/master/docs/user-guide/troubleshooting.md
```

**Comment by wlan0** [comment]
Steps to check - 

1. Launch rancher/k8s:v1.5.1-rancher1-1 
2. Choose kube-system namespace
3. Navigate to Service UI
4. Click on the port (link) mentioned in the row for "kubernetes-dashboard"
5. Ensure that the UI loads and you can see the various services and namespaces etc.

**Comment by galal-hussein** [comment]
Rancher version: master build
Rancher-catalog - vnext branch
Kubernetes version: rancher/k8s:v1.5.1-rancher1-1

Tested kubernetes dashboard and i can see all namespaces, services, and pods.
