### ISSUE TITLE
[rancher-dns] Allow configurable selector rules

### ISSUE THREAD

**Issue by InAnimaTe** [rancher/rancher#7046]
This is an enhancement request to have configurable services for which external dns entries are created. Instead of just "every service which has a host port", why not enable this to be configurable based on the needs of the environment and its services.

In example, containers deployed that must be referenced by a domain name that points to a host utilizing a load balancer is one case where the containers behind the load balancer aren't actually obtaining a host port, and don't need to. But there needs to be some dns record pointing to wherever that service lives.

It would be ideal if this worked like the new LB in 1.2.0 whereas you could setup a simple selector rule that says "all services with label `foo=bar` must have external dns entries created for the host they preside on.

**Comment by janeczku** [comment]
QA steps:

1. Deploy Route53 template v0.6.2 from `rancher-catalog:v1.4.0-rc5`
2. Make sure the `io.rancher.host.external_dns` and `io.rancher.service.external_dns` labels work as intended (see [README](https://github.com/rancher/rancher-catalog/tree/v1.4.0-rc5/infra-templates/route53/10)).

**Comment by galal-hussein** [comment]
Rancher server v1.4.0-rc6
my steps:

- Deploy route53 v0.6.2
- Add the host label `io.rancher.host.external_dns=false` to one of the agent (for eg. host1)
- Add a new service and expose a port for this service and schedule it on host1

The route53 service didn't create a record for this service

- Create a service with label `io.rancher.service.external_dns=never` and expose a port for it and schedule it on host2

The route53 service didn't create a record for this service

- Create a service with label `io.rancher.service.external_dns=always` and **don't** expose a port for this service and schedule it on host2

The route53 service created a record for this service.
