### ISSUE TITLE
Failed pull images from gitlab with rancher-server 1.2.0

### ISSUE THREAD

**Issue by lgaticaq** [rancher/rancher#7048]
**Rancher Version:** 1.2.0

**Docker Version:** 1.12.4

**OS and where are the hosts located? (cloud, bare metal, etc):** Ubuntu 14.04.3 LTS (digitalocean)

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**: single node rancher, internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:**
![seleccion_010](https://cloud.githubusercontent.com/assets/661958/21169295/bd49ca2c-c199-11e6-8906-ba0e29587221.png)
![seleccion_011](https://cloud.githubusercontent.com/assets/661958/21169296/c05e5d7c-c199-11e6-8af0-ca588da0fde4.png)
![seleccion_012](https://cloud.githubusercontent.com/assets/661958/21169336/0a48fd48-c19a-11e6-8591-1734a9773a5d.png)

**Results:** 

**Expected:**

**Comment by StrongMonkey** [comment]
@lgaticaq can you pull image using `docker pull`?

**Comment by lgaticaq** [comment]
```bash
root@personal-api:~# docker pull registry.gitlab.com/escaleno-ltda/personal-api:latest
latest: Pulling from escaleno-ltda/personal-api

3690ec4760f9: Already exists 
bb9e85564b7d: Pull complete 
3c0bb18247d3: Pull complete 
4661f11dd36f: Pull complete 
83d0a76bf7d9: Pull complete 
6dfbed438150: Pull complete 
bc447e0a39be: Pull complete 
Digest: sha256:c32ae0ecf38f40dc64dc94ed88ea26f4b8b1239255ffc6be9c81540206ea09f0
Status: Downloaded newer image for registry.gitlab.com/escaleno-ltda/personal-api:latest
root@personal-api:~#
```

**Comment by superseb** [comment]
Can't reproduce this with v1.2.1, but can't find any issue in the changelog fixing this either. Can you try with v1.2.1 @lgaticaq ?

**Comment by lgaticaq** [comment]
Thanks, everything works fine with v1.2.1
