### ISSUE TITLE
v1.2.0-1 Kubernetes env set up display oddities

### ISSUE THREAD

**Issue by pulberg** [rancher/rancher#7057]
**Rancher Version:**
v1.2.0-1
**Docker Version:**
1.12.4
**OS and where are the hosts located? (cloud, bare metal, etc):**
RHEL7.2, vmware
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node Rancher server, separate mysqld on Rancher server
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes
**Steps to Reproduce:**
Go through the process of setting up a new Kubernetes env
**Results:** 
v1.2.0-1 env set up screen -

![screen shot 2016-12-14 at 10 25 00 am](https://cloud.githubusercontent.com/assets/11069351/21190880/044076a2-c1e9-11e6-8fdb-b773820b13f7.png)
![screen shot 2016-12-14 at 10 25 50 am](https://cloud.githubusercontent.com/assets/11069351/21190900/11f06a0a-c1e9-11e6-8f30-3c96603a1603.png)

**Expected:**
v1.2.0 env set up screen -

![screen shot 2016-12-14 at 9 40 42 am](https://cloud.githubusercontent.com/assets/11069351/21190931/31a82234-c1e9-11e6-85b3-fe53b095c4d1.png)

**Comment by tfiduccia** [comment]
@pulberg - has already been resolved in the latest build.
