### ISSUE TITLE
Kubedns service didn't start on k8s 1.5

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#7058]
**Rancher Version:**
master build
**Docker Version:**
1.12
**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes 1.5
**Steps to Reproduce:**
- Deploy kubernetes 1.5 from vnext branch from rancher-catalog

**Results:** 
The kubedns pods got started however the kubedns **service**  didn't start.

**Comment by imikushin** [comment]
I've put in a couple PRs to fix this:
- rancher/kubernetes-package#13
- rancher/rancher-catalog#341

**Comment by galal-hussein** [comment]
Rancher version: master build
rancher catalog - vnext branch
kubernetes version: rancher/k8s:v1.5.1-rancher1-1

Kubedns started successfully, and all dns validation test cases passed successfully.
