### ISSUE TITLE
[UI] - Surfacing a new UI driver within Rancher

### ISSUE THREAD

**Issue by matfin** [rancher/rancher#7061]
Hi,

I have written a [standalone rancher-ui driver](https://github.com/profitbricks/ui-driver-profitbricks) for the provider ProfitBricks and would like to have this included as part of the default rancher installation as other providers have done.

We want to make it as easy as possible for our customers to start using Rancher. Are there any particular requirements we need to take care of (aside from submitting a PR)?

cc (@vincent99)

**Comment by vincent99** [comment]
@matfin The next thing to do would be to host the compiled version somewhere, and then make a catalog entry for it. (e.g. like this one: https://github.com/rancher/community-catalog/tree/master/machine-templates/aliyunecs)

**Comment by matfin** [comment]
Ok - I will do that now. Thanks.

**Comment by matfin** [comment]
Hi Vincent,

From the example you have posted above, I have created a PR as follows https://github.com/rancher/community-catalog/pull/371.

With that done, will I now be able to edit the source code for the rancher ui project, adding in some code for ProfitBricks? 

From my understanding, I will need to clone the [Rancher ui](https://github.com/rancher/ui) project, then do the following:

- create a directory inside ```app/components/machine/``` and call it something like ```driver-profitbricks```.

- add my ```component.js``` and ```template.hbs``` files in there. 

- commit changes to the master branch of my fork of rancher ui, then create a PR with my changes.

I would like to confirm that I am on the right track with the above. Many thanks.

**Comment by vincent99** [comment]
I'm [assuming](https://github.com/rancher/community-catalog/tree/master/machine-templates/profitbricks) you figured this out or I talked to you on slack/irc... please reach out if you still have questions.
