### ISSUE TITLE
Not able to provision new hosts/create new containers when there are lot of services stuck in "activating" state.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#7062]
Rancher server version -  v1.2.1-rc1:

Had a K8s env with 3 hosts.
Had few Service/RC/pods running.
Deleted all the hosts.

UI took ~20 secs to respond. But it loaded successfully after that.

Had a cattle env where there were 30 services that were stuck in "activation" state because of allocation failures.
Able to launch UI successfully.

Issues seen in this set up:
Adding new host is stuck in "provisioning" state.
Starting new container is stuck in "registering" state.

**Comment by ibuildthecloud** [comment]
Processes have priority and stuff now.

**Comment by sangeethah** [comment]
Tested with Rancher server version - v1.4.0-rc3
Had a K8s env with 3 hosts.
Had few Service/RC/pods running.
Deleted all the hosts.

There is no retry to get infra service containers up anymore.

Had a cattle env where there were ~50 services with scale 3 that were stuck in "activation" state because of allocation failures.

When this was the state , I am able to to add new host successfully.
Starting new services also succeeds.
