### ISSUE TITLE
Global loadbalancer becomes a single container loadbalancer after upgrade

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#7063]
**Rancher Version:**1.2.0 to 1.2.1-rc2

**Docker Version:**1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):**Ubuntu, Cloud

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**Single node

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**Catle

**Steps to Reproduce:**
1. Create a cattle env in 1.2.0 setup and add few services and global LB
2. Upgrade rancher to 1.2.0-rc2
3. Upgrade the LBs from 0.4.2 to 0.4.6

**Results:** 
The global LB is not a global anymore. There is only one LB container. 
 
**Expected:**
The LB should remain global

**Comment by alena1108** [comment]
@soumyalj could you please provide the calls executed by the UI on the upgrade? I believe it will be 2 calls: update and upgrade

**Comment by alena1108** [comment]
@vincent99 might be a UI issue. Looks like we are not sending all the labels on lbService update/upgrade. Here is the set of labels that were set originally on the service:

```
"io.rancher.container.agent.role": "environmentAdmin",
"io.rancher.container.create_agent": "true",
"io.rancher.container.pull_image": "always",
"io.rancher.scheduler.global": "true",
"io.rancher.service.hash": "a48ca67e1170db2ea8b7cff6b0750dd7a7785de5",
"io.rancher.service.selector.link": "io.rancher.glb=true",
```

And these are the labels that UI is sending out:

```
labels
Object {...}
io.rancher.container.agent.role
"environmentAdmin"
io.rancher.container.create_agent
"true"
io.rancher.service.selector.link
"io.rancher.glb=true"
logConfig
Object {type="logConfig", ...}
```

**Comment by tfiduccia** [comment]
Version - v1.2.1-rc3 UI tag 1.2.38
Verified fixed
