### ISSUE TITLE
Stacks screen buggued with v1.2.0

### ISSUE THREAD

**Issue by cedvan** [rancher/rancher#7064]
Hi,

I start rancher v1.2.0: 
- I add first host, it's ok. 
- I create first stack with use `docker-compose.yml` and `rancher-compose.yml`. Immediately after save my screen stacks got error, it stay always blank, same after reconnect account. Message error : 
    - console browser display : `SyntaxError: Expected "date", "number", "plural", "select", "selectordinal" or "time" but "p" found.`

PS : My first stack are correctly saved in API
PS 2 : First stack containers correctly launched and works on my host

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.2.0` Cattle: `v0.174.3` UI: `v1.2.34` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`hosts.index`|

**Comment by vincent99** [comment]
Can you put up a copy or gist of the failing compose files?

**Comment by cedvan** [comment]
Yes : https://gist.github.com/cedvan/b1c97ada0ffe993d021317c4ad7d0497

**Comment by bla-ckbox** [comment]
Hello, i have a similar problem, impossible to upgrade an existing service: blank screen and same error in Firefox.
I use Rancher 1.2.2 but I think that it can come from language becose i reproduce ce problem only with french setting.

**Comment by dstackowiak** [comment]
I confirm, same issue with :

- rancher 1.4.0
- language french
- fresh jenkins stack from catalog
- click on `upgrade` button and screen bugged (blank);  in javascript console i can see : `Expected "date", "number", "plural", "select", "selectordinal" or "time" but "p" found.`

Workaround : set language to "English"

**Comment by tfiduccia** [comment]
@cedvan - I wasn't able to reproduce your issue.  I tried adding the docker & Rancher compose through the add stack and it worked fine.  But there was a problem in upgrade for french.  Translation person mispelled "plural".  We fixed that and it will be released in next release.

Version - master 2/13
Verified fixed

**Comment by cedvan** [comment]
hi @tfiduccia, my problem was the bug related with the French language, thank you ;)
