### ISSUE TITLE
can not dynamically add portRules to load Balanacers

### ISSUE THREAD

**Issue by jwhitcraft** [rancher/rancher#7065]
**Rancher Version:** 1.2.0+

**Docker Version:** 1.12.0

**OS and where are the hosts located? (cloud, bare metal, etc):** AWS/Ubuntu

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** External DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

Prior to version 1.2 of Rancher we could use addServiceLink to link a load balancer, but this is no longer the case with 1.2.0, and as such it has broken our system.

Can this be fixed?

**Comment by clicman** [comment]
Same for me. Workarounded using v2-beta api with 'loadbalancerservices' PUT request
Python example: https://github.com/clicman/rancher-cli-addons/blob/master/rancher/service.py#L122

Example with rancher-cli-addons:
```
rancher-cli --action=update-lb --data="{\"lbConfig\":{\"portRules\":[{\"protocol\":\"http\",\"type\":\"portRule\",\"priority\":1,\"hostname\":\"api.${SERVICE_DOMAIN}\",\"sourcePort\":80,\"targetPort\":5099,\"serviceId\":\"${API_SVC_ID}\"},{\"protocol\":\"http\",\"type\":\"portRule\",\"priority\":1,\"hostname\":\"site.${SERVICE_DOMAIN}\",\"sourcePort\":80,\"targetPort\":3000,\"serviceId\":\"${SITE_SVC_ID}\"}]}}"
```

**Comment by kaos** [comment]
I can confirm that the v1 api is broken, on Rancher v1.3.0.

When we try to call `addServiceLink` on a LB service using the `v1` api, the `ports` part gets stripped, when inspecting the audit log.

This request:
```
HTTP/1.1 POST /v1/projects/1a2887/loadbalancerservices/1s433/?action=addservicelink
Host: rancher.test.example.net
Accept: application/json
Content-Type: application/json
Content-Length: 78

{
"serviceLink": {
"serviceId": "1s475",
"ports": [
"dummy.test=3000"
]
}
}
```

Gives a proper response (the service object):
```
HTTP/1.1 200
Date: Thu, 02 Feb 2017 11:37:05 GMT
X-Api-Client-Ip: 172.xx.yy.zz
Server: nginx/1.9.10
X-Api-Account-Id: 1a2887
Transfer-Encoding: chunked
Content-Type: application/json; charset=utf-8
X-Api-Schemas: https://rancher.test.example.net/v1/projects/1a2887/schemas
Connection: keep-alive
X-Rancher-Version: v1.3.0
Expires: Thu, 01 Jan 1970 00:00:00 GMT

{
"id": "1s433",
"type": "loadBalancerService",
"links": {
"self": "…/v1/projects/1a2887/loadbalancerservices/1s433",
"account": 
...
```

However, the link does not show up in the UI for the LB service, and the audit log shows this request:
```
7 minutes ago	  api.loadBalancerService.addservicelink 	None	ExampleEnv	loadBalancerService: 1s433	 UI Session
172.xx.yy.zz
```

With this request object:
```
{
  "serviceLink": {
    "serviceId": 475
  }
}
```

**Comment by kaos** [comment]
@clicman your line ref is probably off by now, as master has changed since you pasted that... better to paste to the current version of a file when you refer to specific lines in it ;)

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
