### ISSUE TITLE
Unable to access kubernetes service by service name

### ISSUE THREAD

**Issue by ist0ne** [rancher/rancher#7066]
**Rancher Version:**
1.2.0
**Docker Version:**
1.12.3
**OS and where are the hosts located? (cloud, bare metal, etc):**
Centos 7 and bare metal
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher internal DB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes
**Steps to Reproduce:**
Deploy K8s Example Guestbook
**Results:** 

[root@rancher-node1 ~]# kubectl get svc
NAME           CLUSTER-IP      EXTERNAL-IP    PORT(S)    AGE
frontend       10.43.228.70    10.101.1.163   80/TCP     19h
kubernetes     10.43.0.1       <none>         443/TCP    2d
redis-master   10.43.92.51     <none>         6379/TCP   19h
redis-slave    10.43.191.192   <none>         6379/TCP   19h

[root@rancher-node1 ~]# kubectl describe svc redis-master
Name:			redis-master
Namespace:		default
Labels:			io.rancher.stack.uuid=e169756c-1a6b-4614-8536-e09169d5cb1d
			name=redis-master
Selector:		name=redis-master
Type:			ClusterIP
IP:			10.43.92.51
Port:			<unset>	6379/TCP
Endpoints:		10.42.187.216:6379
Session Affinity:	None
No events.

[root@rancher-node1 ~]# kubectl describe svc redis-slave
Name:			redis-slave
Namespace:		default
Labels:			io.rancher.stack.uuid=e169756c-1a6b-4614-8536-e09169d5cb1d
			name=redis-slave
Selector:		name=redis-slave
Type:			ClusterIP
IP:			10.43.191.192
Port:			<unset>	6379/TCP
Endpoints:		10.42.185.29:6379,10.42.63.133:6379
Session Affinity:	None

[root@rancher-node1 ~]# docker exec -ti 6a60 bash
root@redis-slave-fwz4z:/data# redis-cli -h redis-master
Could not connect to Redis at redis-master:6379: Connection timed out
not connected>
not connected> exit

root@redis-slave-fwz4z:/data# ping redis-master
PING redis-master.default.svc.cluster.local (10.43.92.51): 56 data bytes
^C--- redis-master.default.svc.cluster.local ping statistics ---
1 packets transmitted, 0 packets received, 100% packet loss

**Unable to access kubernetes service by service name **

**Comment by aemneina** [comment]
@ist0ne have you tried this with a newer version of rancher/k8s? Also is your redis image based on alpine? If so you might have to use the fqdn for name resolution. I'll close this out, let me know if you still face issues, we can open a new ticket with more details.
