### ISSUE TITLE
Unable to add rancher (agent) host to rancher ( 3 server node) cluster

### ISSUE THREAD

**Issue by ptarpan** [rancher/rancher#7067]
**Rancher Version:**
v1.2.0

**Docker Version:**
1.12.4

**OS and where are the hosts located? (cloud, bare metal, etc):**
Amazon Web Services EC2
16.04 Ubuntu Xenial 

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher with external (MySQL v5.6x DB on AWS RDS)

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
1. Three (AWS EC2) node cluster with rancher/server installed. The command used to bring up rancher/server: 
docker run -d --restart=unless-stopped -p 8080:8080 -p 9345:9345 rancher/server --db-host <mysql_db_fqdn> --db-port 3306 --db-user <db_user> --db-pass <db_pass> --db-name cattle --advertise-address <ec2-instance-privateIP> 
2. Create a public AWS ELB and attach the three rancher nodes listed in step one. The ELB allows tcp/https. Once the rancher/server containers are running, the elb health check should pass allowing you to access the Rancher UI. Note: Proxy protocol on the ELB is enabled (http://docs.aws.amazon.com/elasticloadbalancing/latest/classic/enable-proxy-protocol.html)
3. In the Rancher UI, click on Infrastructure -> Host. Add a "Custom" host. Note: install the rancher agent on the same node/s running rancher/server. The command to add the rancher/agent:
docker run -e CATTLE_AGENT_IP="<public_ip_of_ec2_instance>"  -d --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.1.0 https://<aws_elb_uri>/v1/scripts/<registration_token>

**Results:** 
evel=error msg="Error subscribing to events: websocket: bad handshake" subscribeUrl="wss://rancher.devcrun.ch/v1/subscribe?eventNames=storage.image.activate&eventNames=storage.volume.remove&eventNames=compute.instance.activate&eventNames=compute.instance.deactivate&eventNames=compute.instance.force.stop&eventNames=compute.instance.inspect&eventNames=compute.instance.pull&eventNames=compute.instance.remove&eventNames=config.update&eventNames=storage.volume.activate&eventNames=ping"
time="2016-12-15T05:03:38Z" level=error msg="Got error response" responseHeaders=map[Expires:[Thu, 01 Jan 1970 00:00:00 GMT] Set-Cookie:[PL=rancher;Path=/] Vary:[Accept-Encoding, User-Agent] X-Api-Account-Id:[1a7] X-Api-Schemas:[https://rancher.devcrun.ch/v1/schemas] Content-Length:[1228] Content-Type:[application/json; charset=utf-8] Date:[Thu, 15 Dec 2016 05:03:38 GMT] Server:[Jetty(9.2.11.v20150529)] X-Api-Client-Ip:[35.166.55.166] Connection:[keep-alive]] status="200 OK" statusCode=200
time="2016-12-15T05:03:38Z" level=error msg="Error response: {\"type\":\"collection\",\"resourceType\":\"subscribe\",\"links\":{\"self\":\"https:\\/\\/<aws_elb_uri>\\/v1\\/subscribe\"},\"createTypes\":{},\"actions\":{},\"data\":[],\"sortLinks\":{\"eventNames\":\"https:\\/\\/<aws_elb_uri>\\/v1\\/subscribe?eventNames=storage.image.activate&eventNames=storage.volume.remove&eventNames=compute.instance.activate&eventNames=compute.instance.deactivate&eventNames=compute.instance.force.stop&eventNames=compute.instance.inspect&eventNames=compute.instance.pull&eventNames=compute.instance.remove&eventNames=config.update&eventNames=storage.volume.activate&eventNames=ping&sort=eventNames\"},\"pagination\":null,\"sort\":null,\"filters\":{\"eventNames\":[{\"modifier\":\"eq\",\"value\":\"storage.image.activate\"},{\"modifier\":\"eq\",\"value\":\"storage.volume.remove\"},{\"modifier\":\"eq\",\"value\":\"compute.instance.activate\"},{\"modifier\":\"eq\",\"value\":\"compute.instance.deactivate\"},{\"modifier\":\"eq\",\"value\":\"compute.instance.force.stop\"},{\"modifier\":\"eq\",\"value\":\"compute.instance.inspect\"},{\"modifier\":\"eq\",\"value\":\"compute.instance.pull"
time="2016-12-15T05:03:38Z" level=fatal msg="Exiting. Error: websocket: bad handshake"

**Expected:**
Hosts should show up in the Rancher UI.

**Comment by vincent99** [comment]
ELB does not support websockets.  Use ALB.

**Comment by ptarpan** [comment]
Got it. So, replacing the ELB with an ALB should solve this issue? FYI, we are implementing a load balancer to avoid "hitting" a rancher (server) node directly. Let me know if this doesn't make sense.

**Comment by aemneina** [comment]
Closing, this should work with ELB and enabling proxy protocol for the ELB.
