### ISSUE TITLE
Update docker-machine for new AWS regions

### ISSUE THREAD

**Issue by vincent99** [rancher/rancher#7071]
ca-central-1
eu-west-2

https://github.com/rancher/machine-package/blob/master/scripts/package + UI

**Comment by tfiduccia** [comment]
Canada central and EU west 2 does not work and not in machine.  moving it out of 1.3

**Comment by vincent99** [comment]
https://github.com/rancher/machine-package/pull/19

**Comment by vincent99** [comment]
eu-west-2 is merged now.  https://github.com/rancher/machine-package/pull/19

**Comment by tfiduccia** [comment]
Version - master 3/2
Verified fixed/added
