### ISSUE TITLE
i/o timeout in networks-servers-network-manager.

### ISSUE THREAD

**Issue by jwhitcraft** [rancher/rancher#7073]
**Rancher Version:**
1.2.1-rc2
**Docker Version:**
1.12.3
**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 14.04/ AWS
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
AWS RDS
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

I brought up a new host, but the networking layer never comes up, it only hever has this in the log for the `network-services-network-manager` container.

```
12/15/2016 2:53:35 PMCreating metadata client: Get http://rancher-metadata/2016-07-29/version: dial tcp: lookup rancher-metadata on 169.254.169.250:53: read udp 172.17.0.1:54199->169.254.169.250:53: i/o timeout
12/15/2016 2:53:38 PMtime="2016-12-15T19:53:38Z" level=info msg="Waiting for metadata"
```

**Comment by ibuildthecloud** [comment]
@jwhitcraft Can you make sure there isn't two rancher-metadata processes running?

**Comment by jwhitcraft** [comment]
Hrmm, i dropped the hosts and re-added the rancher-agent instance to it and it came up fine.

If i happens again i'll make sure to check to see what is running.
