### ISSUE TITLE
rancher CLI multiple profiles

### ISSUE THREAD

**Issue by ict4ngo** [rancher/rancher#7075]
rancher cli is really cool I don't like to "click" much so it's great. One improvement would be  to have multiple profiles I can use 

$ rancher -c ~/.rancher/cli.json

but it would be nicer to have something along : 

$ rancher -c test (pointing to ~/.rancher/test.json)
$ rancher -c prod (pointing to ~/.rancher/prod.json)

**Comment by qrpike** [comment]
This would be pretty nice

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
