### ISSUE TITLE
Incredibly high traffic between containers

### ISSUE THREAD

**Issue by ZGF4** [rancher/rancher#7076]
**Rancher Version:**
1.2

**Docker Version:**
1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
AWS Ubuntu

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Setup several services behind a load balancer that communicate with each other.

**Results:** 
Traffic on the containers average around 300-400mbps

**Expected:**
Traffic should be under 20mbps.  If we analyze the incoming traffic on the host it rarely ever even eaches 20mbps.  The data between the services is pretty simple, we're not sending huge messages between them, it should be close to what are incoming and outgoing traffic are.  Traffic on the loadbalancer is reported way higher as well

This started to happen after our upgrade to 1.2

**Comment by tfiduccia** [comment]
@dax0 - care to check #6857 to see if duplicate.  If so, should be fixed in next release.

**Comment by dax0** [comment]
No, I don't think it is.  Our CPU usage hasn't changed

**Comment by dax0** [comment]
Is the measurement megabytes or megabits?

**Comment by aemneina** [comment]
@ZGF4 have you tried this recently. Curious to know if its resolved or not.
