### ISSUE TITLE
Add check option to container.pull_image

### ISSUE THREAD

**Issue by InAnimaTe** [rancher/rancher#7081]
This is a request to extend the `io.rancher.container.pull_image` option to provide a value `check` where an image will be re-pulled only if the existent image ID doesn't match the upstream ID. This is one of the best ways users can ensure that even if the use the :latest tag, they'll truly have the latest image.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
