### ISSUE TITLE
Scheduling a container to different host does not work when upgrading

### ISSUE THREAD

**Issue by InAnimaTe** [rancher/rancher#7082]
**Rancher Version:**
1.2.0

**Docker Version:**
1.12.5

**OS and where are the hosts located? (cloud, bare metal, etc):**
rancherOS, baremetal

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
2 node cluster, single Rancher Server (internal DB)

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle Environment

**Steps to Reproduce:**

Start a service with one container. It gets placed on host x in an active state.

Now update/upgrade that service selecting Schedule -> Only one Host -> Select a different host.

**Results:** 

The update process completes, but merely starts up another instance of the container on the same host.

**Expected:**

The update process to spawn the new container on the host I explicitly defined on the update page.

**Comment by InAnimaTe** [comment]
Note that If I launch a stack unticking "start services on creation" I can then "upgrade" the service, select the host I want, and then spawn it.

**Comment by tfiduccia** [comment]
Version - 1.2.1 - Checked and this is still an issue in the current release.

**Comment by tfiduccia** [comment]
@vincent99 - not sure what we can do here.  Do we want to remove the option to go directly to a specific host?

**Comment by InAnimaTe** [comment]
Hmm. I don't really mind how its handled, so long as there is something there letting me know that functionality won't actually work the way I'd expect it to (maybe just a little note or something). Maybe it is best you remove that option entirely or maybe gray/shadow it out so people understand its not a supported action when doing an upgrade.

**Comment by joshbenner** [comment]
1.2.1: I just tried editing a service, adding a host label rule to change which host a run-once service runs on -- no effect.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
