### ISSUE TITLE
Add CIFS as volume driver to rancher storage

### ISSUE THREAD

**Issue by Negashev** [rancher/rancher#7087]
How about to collect driver cifs on based nfs?

**Comment by Negashev** [comment]
https://github.com/rancher/rancher-catalog/pull/612

**Comment by AndrewSav** [comment]
@superseb I've seen this before. I think it's azure specific. Not everyone uses azure.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
