### ISSUE TITLE
Container stats not showing up in host or service detail view.

### ISSUE THREAD

**Issue by qrpike** [rancher/rancher#7089]
**Rancher Version:**
1.2.1

**Docker Version:**
1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
Bare Metal, PXE Boot, CoreOS 1235.2.0

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node, Internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Inside of an Environment, go to "Infrastructure" tab, then click on a host. In the "Containers" tab hover over a containers Network, Memory, Storage or CPU graphs.

**Results:** 
Nothing

**Expected:**
Previously it shows how much that container was using of the hovered resource. This was very helpful when trying to see how much memory all the containers were using without having to click into every one of them.

**Comment by tfiduccia** [comment]
Version - 1.2.1 Current version is not showing the hover information for containers in both the host view and the container view.  Checked previous 1.1.0 release and this is what it looked like:
![image](https://cloud.githubusercontent.com/assets/11514927/21274955/e7c118ec-c387-11e6-9f4a-686eadd70dcb.png)

**Comment by tfiduccia** [comment]
Version - master 1/17
Verified fixed
