### ISSUE TITLE
[UI] ui-auto.css 404: v1.2.1

### ISSUE THREAD

**Issue by willseward** [rancher/rancher#7090]
**Rancher Version:** v1.2.1

**Docker Version:** v1.12.4

**OS and where are the hosts located? (cloud, bare metal, etc):** RHEL 7, vSphere

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** Single Node, External DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:**

Update to v1.2.1

**Results:** 

No CSS loaded.

Failed to load resource: the server responded with a status of 404 (Not Found)...https://xxx/assets/ui-auto.css?1.2.39 

**Expected:**

CSS is found.

**Comment by vincent99** [comment]
D'oh.. This broke in the PR to add right-to-left language support, the `auto` should be rewritten to `light` or `dark` depending on the time.  Click the unstyled `Light` or `Dark` button for now to get CSS back.

**Comment by tfiduccia** [comment]
Version - master 11/20
Verified fixed.
