### ISSUE TITLE
Enable random public port for LB 

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#7093]
Today randomly public ports functionality is disabled for LB service. And although it is not very common use case, we should probably add this functionality in. Here are a couple of examples for LB ports definitions:

1) LB is internal, source port is not exposed:

```
services
  lb:
    image: <lb image>
    portRules:
      -sourcePort:80
        targetPort:8080
        service: foo
```

2) LB is public, source port is published to the same public port on the host:

```
services
  lb:
    image:<lb image>
    ports: 
      - 80:80
    portRules:
      -sourcePort:80
        targetPort:8080
        service: foo
```

3) LB is public, source port 80 is published to the random port on the host:

```
services
  lb:
    image:<lb image>
    ports: 
      -80
    portRules:
      -sourcePort:80
        targetPort:8080
        service: foo
```

UI should also support all 3 models.

@vincent99 let me know if it looks good.

**Comment by noamkachko** [comment]
Hi can you please help us and implement this it is blocking us from upgrade to newer version .
this was capability we used in 1.1.3 version and in 1.2 was removed.
Thanks

**Comment by flypenguin** [comment]
I also think this is highly useful :) . We did rely on this, and now we need to hand-code all the LB configs. Possible, but annoying, and stops us from migrating.

**Comment by flypenguin** [comment]
4 months later, rancher 1.6.3 out now, and I thought I'd ask again: any updates? (or timelines? decisions? ideas? :)

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
