### ISSUE TITLE
Unable to create Kubernetes project with v1 API

### ISSUE THREAD

**Issue by nextrevision** [rancher/rancher#7094]
**Rancher Version:**
v1.2.1

**Docker Version:**
1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
AWS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA w/ external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
Create a Kubernetes project using the `/v1` API and see that the project is instead created with cattle orchestration.

```
$ curl -s -X POST \
  -H 'Accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{"description":"k8stest", "name":"k8stest", "swarm":false, "kubernetes":true, "mesos":false}' \
  http://rancher.acme.com/v1/projects/ | jq '.id'
"1a161"
$ curl -s http://rancher.acme.com/v1/projects/1a161 | jq '.kubernetes'
true
$ curl -s http://rancher.acme.com/v2-beta/projects/1a161 | jq '.orchestration'
"cattle"
```

**Results:** 
The environment does not get created with kubernetes orchestration.

**Expected:**
The environment is created with kubernetes orchestration.

**Comment by tombmurphy** [comment]
Hi, this is having an impact on other tools which depends on API v1 such as terraform (https://github.com/hashicorp/terraform/issues/11392) which has a rancher provider. Any ETA on getting this working or any workarounds ? 

Thanks

**Comment by aemneina** [comment]
There's a PR for this here @tombmurphy https://github.com/hashicorp/terraform/pull/13908 I'm guessing you can build terraform with that commit included and run against modern versions of rancher.

**Comment by aemneina** [comment]
Going to close this ticket out
