### ISSUE TITLE
passing in NO_PROXY as a container environment variable doesnt work

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#7095]
**Rancher Version:**
v1.2.0

repro steps
* launch a container with an environment variable NO_PROX and specify arguments (e.g. `https://testdomain`)
* exec into the container and issue the printenv command

expected:
printenv should show NO_PROXY values from the arguments passed in to the container.

actual:
inside container NO_PROXY would be blank, it seems to inherit the rancher/agent, or host, NO_PROXY arguments. Docker inspect shows two NO_PROXY values being passed into the container, second one seems to override what the user is trying to pass in.

**Comment by StrongMonkey** [comment]
https://github.com/rancher/agent/pull/114

**Comment by galal-hussein** [comment]
Rancher version: master build

Tested running a container with NO_PROXY set to `https://testdomain`, and the environment variable passed to the container correctly:
```
root@6896e561c143:/# printenv NO_PROXY
https://testdomain
```
