### ISSUE TITLE
HA mode does not work when ALB is on public subnets

### ISSUE THREAD

**Issue by thiagonache** [rancher/rancher#7096]
**Rancher Version:**
v1.2.1

[rancher@ip-172-16-3-168 ~]$ docker ps; docker images | grep 5a9
CONTAINER ID        IMAGE                   COMMAND                  CREATED             STATUS              PORTS                                                      NAMES
145418d3c183        rancher/server:latest   "/usr/bin/entry --db-"   22 minutes ago      Up 22 minutes       0.0.0.0:8080->8080/tcp, 3306/tcp, 0.0.0.0:9345->9345/tcp   kickass_fermat
rancher/server      latest              5a9f3387a325        13 hours ago        931.6 MB
rancher/server      v1.2.1              5a9f3387a325        13 hours ago        931.6 MB
[rancher@ip-172-16-3-168 ~]$ 

**Docker Version:**
[rancher@ip-172-16-3-168 ~]$ docker -v
Docker version 1.12.1, build 23cf638

**OS and where are the hosts located? (cloud, bare metal, etc):**
AWS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
3 master nodes in HA mode using RDS as database

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Deploy new vpc with public and private subnets
Note: VPC use nat gateways instead of nat instances

Deploy rancher server and agents in private subnet
Deploy ALB in public subnet
Use ALB endpoint as registration URL

(if you do same steps and just deploy internal ALB in private subnets it will work)

**Results:** 
Healthcheck container does not start. All other containers are running.

12/16/2016 8:03:18 PMtime="2016-12-16T22:03:18Z" level=info msg="Starting haproxy listener"
12/16/2016 8:03:18 PMtime="2016-12-16T22:03:18Z" level=info msg="healthCheck -- starting haproxy\n * Starting haproxy haproxy\n   ...done.\n"
12/16/2016 8:03:18 PMtime="2016-12-16T22:03:18Z" level=info msg="Scheduling apply config"
12/16/2016 8:03:18 PMtime="2016-12-16T22:03:18Z" level=info msg="healthCheck -- reloading haproxy config with the new config changes\n[WARNING] 350/220318 (31) : config : 'option forwardfor' ignored for proxy 'web' as it requires HTTP mode.\n"
12/16/2016 8:03:23 PMtime="2016-12-16T22:03:23Z" level=info msg="Scheduling apply config"
12/16/2016 8:03:23 PMtime="2016-12-16T22:03:23Z" level=info msg="healthCheck -- no changes in haproxy config\n"
12/16/2016 8:03:28 PMtime="2016-12-16T22:03:28Z" level=info msg="Scheduling apply config"
12/16/2016 8:03:28 PMtime="2016-12-16T22:03:28Z" level=info msg="healthCheck -- no changes in haproxy config\n"
12/16/2016 8:03:33 PMtime="2016-12-16T22:03:33Z" level=info msg="Scheduling apply config"
12/16/2016 8:03:33 PMtime="2016-12-16T22:03:33Z" level=info msg="healthCheck -- no changes in haproxy config\n"
12/16/2016 8:03:38 PMtime="2016-12-16T22:03:38Z" level=info msg="Scheduling apply config"
12/16/2016 8:03:38 PMtime="2016-12-16T22:03:38Z" level=info msg="healthCheck -- no changes in haproxy config\n"
12/16/2016 8:03:43 PMtime="2016-12-16T22:03:43Z" level=info msg="Scheduling apply config"
12/16/2016 8:03:43 PMtime="2016-12-16T22:03:43Z" level=info msg="healthCheck -- no changes in haproxy config\n"
12/16/2016 8:03:48 PMtime="2016-12-16T22:03:48Z" level=info msg="Scheduling apply config"
12/16/2016 8:03:48 PMtime="2016-12-16T22:03:48Z" level=info msg="healthCheck -- no changes in haproxy config\n"
12/16/2016 8:03:53 PMtime="2016-12-16T22:03:53Z" level=info msg="Scheduling apply config"
12/16/2016 8:03:53 PMtime="2016-12-16T22:03:53Z" level=info msg="healthCheck -- reloading haproxy config with the new config changes\n[WARNING] 350/220353 (57) : config : 'option forwardfor' ignored for proxy 'web' as it requires HTTP mode.\n[WARNING] 350/220353 (57) : config : 'option forwardfor' ignored for backend 'cattle-6c6d8ae5-fed0-4d6c-beff-2350f4df77b9_a9d926ac-7db3-4220-8cd9-24d0c6f6b24e_1' as it requires HTTP mode.\n[WARNING] 350/220353 (57) : config : 'option forwardfor' ignored for backend 'cattle-6c6d8ae5-fed0-4d6c-beff-2350f4df77b9_8f780143-615f-4116-bcc9-cfa543215e76_1' as it requires HTTP mode.\n[WARNING] 350/220353 (57) : config : 'option forwardfor' ignored for backend 'cattle-6c6d8ae5-fed0-4d6c-beff-2350f4df77b9_2bf7681c-53c7-48ea-9d04-c08110f800d7_1' as it requires HTTP mode.\n"
12/16/2016 8:03:54 PMtime="2016-12-16T22:03:54Z" level=info msg="Monitoring 3 backends"
12/16/2016 8:03:56 PMtime="2016-12-16T22:03:56Z" level=info msg="6c6d8ae5-fed0-4d6c-beff-2350f4df77b9_a9d926ac-7db3-4220-8cd9-24d0c6f6b24e_1=DOWN"
12/16/2016 8:03:56 PMtime="2016-12-16T22:03:56Z" level=info msg="6c6d8ae5-fed0-4d6c-beff-2350f4df77b9_8f780143-615f-4116-bcc9-cfa543215e76_1=DOWN"
12/16/2016 8:03:58 PMtime="2016-12-16T22:03:58Z" level=info msg="Scheduling apply config"
12/16/2016 8:03:58 PMtime="2016-12-16T22:03:58Z" level=info msg="healthCheck -- no changes in haproxy config\n"
12/16/2016 8:03:58 PMtime="2016-12-16T22:03:58Z" level=info msg="6c6d8ae5-fed0-4d6c-beff-2350f4df77b9_2bf7681c-53c7-48ea-9d04-c08110f800d7_1=DOWN"
12/16/2016 8:04:03 PMtime="2016-12-16T22:04:03Z" level=info msg="Scheduling apply config"
12/16/2016 8:04:03 PMtime="2016-12-16T22:04:03Z" level=info msg="healthCheck -- no changes in haproxy config\n"
12/16/2016 8:04:08 PMtime="2016-12-16T22:04:08Z" level=info msg="Scheduling apply config"
12/16/2016 8:04:08 PMtime="2016-12-16T22:04:08Z" level=info msg="healthCheck -- no changes in haproxy config\n"
12/16/2016 8:04:13 PMtime="2016-12-16T22:04:13Z" level=info msg="Scheduling apply config"
12/16/2016 8:04:13 PMtime="2016-12-16T22:04:13Z" level=info msg="healthCheck -- no changes in haproxy config\n"

**Expected:**
Healthcheck container running

**Comment by thiagonache** [comment]
Hi there,

When nodes are in private subnets and ALB in public subnets, cattle agent IP becomes NAT gateway EIP. So, we need to specify CATTLE_AGENT_IP to make it work.

I guess it's a good idea add it to documentation.

**Comment by aemneina** [comment]
https://docs.rancher.com/rancher/v1.5/en/faqs/troubleshooting/#are-the-ips-of-the-hosts-correct-in-the-ui Closing this out.
