### ISSUE TITLE
Do not provide option for adding health check parameters when launching containers in Windows environment.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#7098]
Rancher Version: Build from master - Dec 16 afternoon

library from rancher/rancher-catalog , branch - vnext

Steps to reproduce the problem:
Create Environment with windows template.
Add couple of Windows host.

Add service with health check enabled.
Containers are stuck in "Initializing" state forever , since health check service is not available for windows template.

UI should not present users the ability to set these health check parameters when starting service.

**Comment by tfiduccia** [comment]
Version - master 11/20
Verified fixed

![image](https://cloud.githubusercontent.com/assets/11514927/21361879/2b8ca668-c6a3-11e6-89d1-689c8c183192.png)
