### ISSUE TITLE
Feature: Download Rancher logs and info for support

### ISSUE THREAD

**Issue by will-chan** [rancher/rancher#71]
Rancher needs to support a script or API that will allow the root admin (or even on a per user level) to create a packaged file that should contain the following information:
- Rancher logs
- Rancher version and other pertinent system info (host version, OS, etc.)
- Docker version
- All other external version #s of services that Rancher may use (i.e. MySQL, etc.)
- Individual Rancher agent logs - can specify on a per agent basis or "all"
- Individual Service logs that Rancher manages (Swarm-server, Machine-server, HAProxy)

The idea is that when issues or bugs are found, someone can easily create a support or GitHub issue and upload this packaged information where it can be used to more easily identify root cause.

**Comment by deniseschannon** [comment]
We're adding logging support into 2.0 and will track the issue here: https://github.com/rancher/rancher/issues/11167
