### ISSUE TITLE
Should we allow scale up/down on an inactive service using webhooks ?

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#7103]
**Rancher Version:**Master

**Docker Version:**1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):**Ubuntu, Cloud

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**Single node

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:**
1. Create a cattle setup with webhook enabled DEFAULT_CATTLE_WEBHOOK_SERVICE_EXECUTE=true

2. On an inactive service, should we allow a scale up/down ? 

Currently, a token can be generated for an inactive service and we can scale up/down using the token. The scale goes up/down in the UI first. When the service becomes active, the number of containers get adjusted accordingly.

**Comment by deniseschannon** [comment]
It makes sense to have webhooks for active services at this time. If the community finds value in this type, we could look into adding it in.
