### ISSUE TITLE
[UI] "Global" misspelled

### ISSUE THREAD

**Issue by willseward** [rancher/rancher#7105]
**Rancher Version:** v1.2.1

**Docker Version:** 1.11.2

**OS and where are the hosts located? (cloud, bare metal, etc):** Ubuntu 16.04, DO

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** External DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:** Create a globally scheduled load balancer

**Results:** "Global" is spelled "Globl"

**Expected:** "Global" should be spelled "Global"

<img width="343" alt="screen shot 2016-12-16 at 11 30 01 pm" src="https://cloud.githubusercontent.com/assets/5386568/21284653/bcd7474a-c3e7-11e6-816a-2b86241ded24.png">

@tfiduccia FYI

**Comment by tfiduccia** [comment]
Version - master 12/19
Verified fixed
