### ISSUE TITLE
Error Provisioning EC2 Hosts with longer AWS resource ids

### ISSUE THREAD

**Issue by billywhizz** [rancher/rancher#7109]
**Rancher Version:**
1.1.4

**Docker Version:**
1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
AWS EC2

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Launch a new EC2 Host. Issue noticed on 17th December

**Results:** 
Host will not launch. Error communicating with Docker. We noticed that AWS is now using longer instance id's and wondering if this could be cause of issue?

https://dl.dropboxusercontent.com/s/h74v9f2xj5eklay/chrome_2016-12-18_02-00-53.png

**Comment by bishalkc** [comment]
I have encountered the same issue. I have got different errors, 

1. Could not verify OS (when provisioned with RancherOS) and
2. Waiting for SSH to be available (when provisioned with ubuntu)

**Comment by aemneina** [comment]
which AMI are you using? can you launch that AMI in the same VPC subnet and add the host that route? That would ensure the vpc can reach out to the rancher server.

**Comment by billywhizz** [comment]
Hi. We are using Ubuntu 15 LTS ami. AMI id is ami-8aa67cf9

**Comment by billywhizz** [comment]
We have not had an issue with this AMI previously. When we try to clone an existing host in rancher we have the issue so no difference between ones that are successfully deployed and running.

**Comment by billywhizz** [comment]
Docker version is actually 1.10.3 not 1.12.3 as stated above

**Comment by billywhizz** [comment]
We have captured logs from rancher management host when trying to provision. Maybe this sheds some light?

**Comment by bishalkc** [comment]
RancherOS ami-c6d073a5 (ap-southeast-1 region), yes the Rancher server and rancher host are in subnet, all the NACL and SG's are in place for server <-> client communications. If I build the instance via Terraform and run the agent everything works as expected.

**Comment by aemneina** [comment]
This should have been resolved in a more modern version of rancher. If you can reproduce the issue there, please do file an issue.
