### ISSUE TITLE
dig on <link name>.rancher.internal resolves to only 1 ipaddress when  it is linked to service with scale 2.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#7110]
Rancher Version: v1.3.0-rc1

Steps to reproduce the problem:
Create a service S1 and link in to service S2 with scale 2 with link name as "mylink".
From containers of service S1 , "mylink" resolves to both containers of S2. 
But "mylink.rancher.internal"  resolves to only 1 of the containers of S2. 
```
root@6838259bcbe4:/# dig mylink +short
10.42.148.128
10.42.91.157
root@6838259bcbe4:/# dig mylink.rancher.internal +short
10.42.148.128
root@6838259bcbe4:/#
```

**Comment by deniseschannon** [comment]
Please test with rancher/dns:v0.11.0 in network-services v0.0.6 on the vnext branch of rancher-catalog.

**Comment by sangeethah** [comment]
This issue is fixed and not seen when testing with rancher/dns:v0.11.0
