### ISSUE TITLE
catalog cannot update automatically

### ISSUE THREAD

**Issue by dreamOW** [rancher/rancher#7111]
**Rancher Version:1.20

**Docker Version:1.12.0

**Environment Type: Cattle

**Steps to Reproduce: Well, I create a catalog named Test, Then I want to update it, and I already change my code in git, but there is not change in my catalog after a whole day, Then I delete this catalog and rename it to a new name(fortest), at last, it show that "There are no compatible templates", I found that there is no code in my file (/var/lib/cattle/DATA),and I have no any clue to deal with this problem. Overall, it cannot automatically update.

**Results:** 

**Expected:**

**Comment by deniseschannon** [comment]
Catalogs are automatically updated every 5 min. Did you check the rancher server logs to see if there were any errors occurring during the refresh?

Also, you can manually refresh your catalog by clicking on the refresh button in the Catalog page. It is in the upper right hand corner under the menu bars.

**Comment by dreamOW** [comment]
Well, Thank you so much,I found this problem is caused by git problems.
