### ISSUE TITLE
Suggestion: Use go binary file directly when build docker image

### ISSUE THREAD

**Issue by PotterDai** [rancher/rancher#7112]
**Rancher Version:**
1.2.0

Build within docker container generates image with very large footprint. 
For example "rancher-net" image took 259mb.

A much size efficient way can be achieved by building docker image directly using go binary file.
For example: https://github.com/containous/traefik/blob/master/Dockerfile
traefik's docker image size is only 6mb.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
