### ISSUE TITLE
Rancher scheduler (1.2.0) unexpected behaviour

### ISSUE THREAD

**Issue by dbones** [rancher/rancher#7115]
As mentioned here: https://forums.rancher.com/t/rancher-scheduler-1-2-0-unexpected-behaviour/4904

**Rancher Version:** 1.2.0

**Docker Version:** 1.2.1

**OS and where are the hosts located? (cloud, bare metal, etc):** ubuntu

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** simple (single host)

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:**

**scenario 1:**

* 1 app server, with a number of containers running on it
* start a 2nd app server
* delete a container (which will make rancher create another instance)

rancher creates it on the same server, even though there is a new empty app server. (it used to try and spread containers across servers, i would expect rancher 1.2 to try and spread the instances)

**scenario 2 (increment on the first scenario, scheduling rules)**

* 1 app server, with a service called vote running (5 instances)
* voting service has a scheduling rule

**Key:** io.rancher.scheduler.affinity:container_label_soft_ne 
**Value:** io.rancher.stack_service.name=voting/vote

* start 2nd app server (+1 if it re-balanced at this point, but it did not do that before.)
* delete instance(s) of the Vote service

rancher schedules the newly created instances on the same server. when scheduling the "new" (replacement) instance it does not take into account the scheduling rules.

this does not seem correct, and differs from the previous behaviour (i guess there would be some changes), however i used this to balance containers across the servers.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
