### ISSUE TITLE
Documentation on Rancher 1.2 / Swarm does not seem right

### ISSUE THREAD

**Issue by bergtwvd** [rancher/rancher#7117]
**Rancher Version:**
1.2.1

**Docker Version:**
Docker version 1.12.3, build 6b644ec

**OS and where are the hosts located? (cloud, bare metal, etc):**
bare metal.

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Server and 3 slaves (see also https://github.com/rancher/rancher/issues/7116),

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Swarm

**Steps to Reproduce:**
Create Swarm environment as per manual: http://docs.rancher.com/rancher/v1.2/en/swarm.

**Results:** 
Missing UI elements.

````
After a Swarm environment has been created, you can navigate to the environment by either selecting the name of the environment in the environment’s dropdown in the upper right hand corner or by selecting Switch to this Environment in the specific environment’s drop down.
````

However, there is no ``environment’s dropdown in the upper right hand corner``.

Further down on the page it says:

````
Rancher provides full CRUD capability of creating projects. In the Swarm tab, click on the Projects and click Add Project. When adding a project, you can input your docker-compose.yml either by reading a file or copying and pasting the contents directly into the UI. If your compose-template contains any environment interpolation, you will need to declare the variables by adding variable substitution. Click on Create.
````

Here there is no ``Projects`` to click on and no possibility to add a project.

**Expected:**
Expect items as per user manual.

**Comment by tfiduccia** [comment]
@deniseschannon 
Can we fix the documentation?  We moved the environment drop-down to the upper-left instead of right.  And we removed the project menu item when we redid swarm.  Actually that whole section may need to be rewritten.

**Comment by deniseschannon** [comment]
Docs updated.

**Comment by bergtwvd** [comment]
I see that the documentation is/will be updated and that the issue is closed, but what happened to some of the functionality?
- how can I enter a docker compose script to fire up containers?
- the help doc mentions ``Swarm -> CLI -> Generate Config``, but this missing in my version of Rancher... where is this?

**Comment by LLParse** [comment]
@bergtwvd The documentation referenced the old swarm implementation. Docker redesigned swarm (now referred to as "swarm mode") - they behave differently and we haven't yet updated the UI.
