### ISSUE TITLE
Is there a better way to install infrastructure service for 1.2.0+

### ISSUE THREAD

**Issue by lion200816** [rancher/rancher#7119]
**Rancher Version:**
1.2.1

**Docker Version:**
1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
Internal 

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node and external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**

**Results:** 
After upgraded to 1.2.1, due to our servers has no internet access, so for the infrastructure service, it is not easy for us to install or upgrade them from now on. 

**Expected:**
Is there any suggested solution for the infrastructure service installation ? Manually push the images to private registry and pull them to all agent servers , then run a self-edited docker-compose.yml and rancher-compose.yml ?

**Comment by superseb** [comment]
Check https://github.com/rancher/rancher/issues/6816 for progress on this @lion200816

**Comment by lion200816** [comment]
@superseb Thanks very much for guiding me there..

**Comment by superseb** [comment]
No problem, if this matches your usecase please close this issue to keep the issue list clean.

**Comment by lion200816** [comment]
@superseb  Yes,thanks.
