### ISSUE TITLE
use compose bundle to replace the swarm catalog

### ISSUE THREAD

**Issue by HackerWilson** [rancher/rancher#7120]
**Rancher Version:**
v1.2.1

**Docker Version:**
1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
bare metal

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher
external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Swarm

**Steps to Reproduce:**
1. create swarm mode cluster
2. swarm catalog is missing

**Results:** 
swarm catalog was removed in rancher v1.2.1

**Expected:**
Could you please support the compose bundle to deploy services on swarm mode cluster?
Or swarm mode is of no use in rancher any more.

```
Compose does not use swarm mode to deploy services to multiple nodes in a swarm. All containers will be scheduled on the current node.

To deploy your application across the swarm, use the bundle feature of the Docker experimental build.

More info:
https://docs.docker.com/compose/bundles
```

**Comment by ibuildthecloud** [comment]
@HackerWilson This is really just too much a moving target.  As such we've really had to decrease the scope of what we support with anything related to Swarm.  We just don't really know where things are going and they change with each Docker release.  On this topic specifically, I do not think "bundles" or "dabs" will be a user level concept if not dropped completely.  In Docker 1.13 compose files are now supported natively https://github.com/docker/docker/pull/27998.  Those compose files are also "v3" which a new format with 1.13.  We will let something stick for at least one minor release before we support it :)  Any attempt at guessing where Docker is going has largely backfired.
