### ISSUE TITLE
rancher-compose requires more than service name for upgrade

### ISSUE THREAD

**Issue by dissonanz** [rancher/rancher#7121]
**Rancher Version:**
1.2.1

**Rancher-compose Version:**
v0.12.0

**Docker Version:**
1.12.5

**OS and where are the hosts located? (cloud, bare metal, etc):**
virtualbox (boot2docker)

**Setup Details:**
Single-container rancher server

**Environment Type:**
Cattle

**Steps to Reproduce:**
- create a service using rancher-compose
- try to upgrade the service using a new service name in docker compose file and empty docker-compose config for old service. Per instruction in https://docs.rancher.com/rancher/v1.0/en/rancher-compose/upgrading/#rolling-upgrade, "Nothing needs to actually be placed in the file as the service is already running".

docker-compose.yml:
```
---
service1:

service2:
  image: nginx
```

**Results:**
```
I, [2016-12-19T09:44:11.465723 #42518]  INFO -- : time="2016-12-19T09:44:11+03:00" level=fatal msg="Failed to read project: Service 'service1' has neither an image nor a build path specified. Exactly one must be provided."
```

**Expected:**
Upgrade should complete without errors.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
