### ISSUE TITLE
Configurable prefix in graphite output

### ISSUE THREAD

**Issue by sevenval-admins** [rancher/rancher#7123]
**Rancher Version:**
1.2.0

**Docker Version:**
1.11.2

**OS and where are the hosts located? (cloud, bare metal, etc):**
CentOS7 in VM

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Activate graphite output bei setting value in /v1/activesettings/1as28

**Results:** 
Alle metrics are written to servers.<hostname>....

**Expected:**
It would be great to make the prefix servers configurable. Actually the namespace conflicts with another application in our stack, which already uses this prefix.

Thanks.

Regards,
Erwin

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
