### ISSUE TITLE
Does racher Cattle only support dnsrr mode for service?

### ISSUE THREAD

**Issue by kingsqv** [rancher/rancher#7126]
**Rancher Version:**
1.2.1
**Docker Version:**
1.12
**OS and where are the hosts located? (cloud, bare metal, etc):**
ubuntu

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
service:nginx   scale=3  and a busybox 
**Results:** 
when i in busybox run command: wget -O- nginx  it worked well but then 
stop  the container of nginx service which busybox used ,  wget -O- nginx will timeout until rancher start the container again  the dnsrr mode couldn't support  load balancing well
**Expected:**
will you plan to support vip mode in Cattle

**Comment by vincent99** [comment]
#3495
