### ISSUE TITLE
Container that publishes port can't access itself via the host IP

### ISSUE THREAD

**Issue by mcanevet** [rancher/rancher#7128]
**Rancher Version:**

1.2.1

**Docker Version:**

1.11.2

**OS and where are the hosts located? (cloud, bare metal, etc):**

Ubuntu 16.04 on AWS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

single node rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

Cattle

**Steps to Reproduce:**

* Create a container that publishes a port.
* Scale it
* from one container that publishes a port, try to connect to another container of the service via the IP of the host => it works
* from one container that publishes a port, try to connect to itself via the IP of the host => it does NOT work

**Results:** 

**Expected:**

A container that publishes a port should be able to join itself via the IP of the host. It used to work in Rancher 1.1

**Comment by ibuildthecloud** [comment]
I can confirm this is an issue.  Will fix.

ping @leodotcloud

**Comment by deniseschannon** [comment]
Available in Rancher v1.2.2-rc2 in network-manager v0.2.19 on the rancher-catalog `1.2.2-rc2`

**Comment by sangeethah** [comment]
Tested with v1.2.2-rc2

Create a service with exposed port.
From within the container , able to access itself using the host's private Ip address and its exposed port.

**Comment by mcanevet** [comment]
Thanks

**Comment by yeruisen** [comment]
@mcanevet 
Do you have the same issues as me.
#7297

**Comment by yeruisen** [comment]
@sangeethah 
I came across a similar issue.
#7297
Please help me. Thank you.

**Comment by garjunan** [comment]
+1
same issue here..

I am using latest rancher version. 1.4.1 and docker version is 1.12.6. I upgraded kernel to 4.10.
ex: container1 - container port 80 and exposed port is 80
 curl/wget of container-IP:80 working from same container or different container of same Host
 curl/wget of container-host-IP:80 not working from same container or different container of same Host

But it is working outside Rancher when i browse it from my laptop or from different rancher stacks.

**Comment by garjunan** [comment]
@sangeethah  this issue closed on Dec 2016 but it is occurring in current stable release also.

**Comment by yeruisen** [comment]
@sangeethah 
see #7297
