### ISSUE TITLE
go-machine-service and rancher-compose-executor restarting every minute

### ISSUE THREAD

**Issue by nextrevision** [rancher/rancher#7129]
**Rancher Version:**
v1.2.1 (upgraded from v1.1.4)

**Docker Version:**
1.11.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu Trusty, AWS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA w/ external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
After upgrading to v1.2.1 (and also upgrading all of all of our cattle environments), I'm seeing the go-machine-service and rancher-compose executor restarting frequently (maybe multiple times a minute). I'm also seeing containers fail to start (every one of our scheduler instances is failing as well).

**Results:** 
```
time="2016-12-19T17:13:35Z" level=fatal msg="Unable to start event router" error="Timed out waiting for transtion."
time="2016-12-19T17:13:35Z" level=info msg="Starting rancher-compose-executor" version=v0.12.1
time="2016-12-19T17:13:52Z" level=fatal msg="Unable to start event router" error="Timed out waiting for transtion."
time="2016-12-19T17:13:54Z" level=info msg="Starting rancher-compose-executor" version=v0.12.1
time="2016-12-19T17:14:11Z" level=fatal msg="Unable to start event router" error="Timed out waiting for transtion."
time="2016-12-19T17:14:12Z" level=info msg="Starting rancher-compose-executor" version=v0.12.1
time="2016-12-19T17:14:29Z" level=fatal msg="Exiting go-machine-service: Timed out waiting for transtion."
time="2016-12-19T17:14:30Z" level=info msg="Setting log level" logLevel=info
time="2016-12-19T17:14:30Z" level=info msg="Starting go-machine-service..." gitcommit=v0.34.1
time="2016-12-19T17:14:30Z" level=info msg="Waiting for handler registration (1/2)"
time="2016-12-19T17:14:37Z" level=info msg="Stats auth failed: Error parsing stats token. Failing auth. Error: token is expired"
time="2016-12-19T17:14:44Z" level=fatal msg="Exiting go-machine-service: Timed out waiting for transtion."
time="2016-12-19T17:14:46Z" level=info msg="Setting log level" logLevel=info
time="2016-12-19T17:14:46Z" level=info msg="Starting go-machine-service..." gitcommit=v0.34.1
time="2016-12-19T17:14:46Z" level=info msg="Waiting for handler registration (1/2)"
```

**Expected:**

Those services to not restart as frequently.

What is the transition it is waiting for?

**Comment by nextrevision** [comment]
Possibly related to #6753

**Comment by aemneina** [comment]
@nextrevision I'd imagine this has been resolved. I'll close this out, feel free to create a new issue if you see issues again.
