### ISSUE TITLE
Health check stays on initialising

### ISSUE THREAD

**Issue by matthijsvdr** [rancher/rancher#7130]
**Rancher Version:**
1.2.1

**Docker Version:**
1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
rancheros (vm)

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
2 master in HA, external database, 2 agents.
masters behind nginx proxy, setup copied from here: http://docs.rancher.com/rancher/v1.2/en/installing-rancher/installing-server/basic-ssl-config/ (Only difference is that nginx runs on a separate server)

Network:
![untitled diagram](https://cloud.githubusercontent.com/assets/1271035/21326359/9258e966-c62a-11e6-97b3-7b18b36a9651.png)

Note: when directing the agents directly to the internal ip addresses of a master they work as expected.

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Setup ranger according to documentation

**Results:** 
scheduler and health check infrastructure stacks are stuck in Initialising.
Sometimes the scheduler and 1 health check manage to finish, but others are stuck for ever.

**Expected:**
They should not be stuck

// Edit some logs of the healthcheck

> 12/19/2016 8:19:32 PMtime="2016-12-19T19:19:32Z" level=info msg="Monitoring 2 backends"
> 12/19/2016 8:19:34 PMtime="2016-12-19T19:19:34Z" level=info msg="977ece20-f208-4337-bfed-beba012c6aeb_e3c0529c-1392-4074-b02d-7a596dba947e_2=DOWN"
> 12/19/2016 8:19:34 PMtime="2016-12-19T19:19:34Z" level=info msg="977ece20-f208-4337-bfed-beba012c6aeb_49312f91-179f-4b8e-9973-a307085b9e74_1=DOWN"
> 12/19/2016 8:19:35 PMtime="2016-12-19T19:19:35Z" level=info msg="Scheduling apply config"
> 12/19/2016 8:19:35 PMtime="2016-12-19T19:19:35Z" level=info msg="healthCheck -- no changes in haproxy config\n"
> 12/19/2016 8:19:46 PMtime="2016-12-19T19:19:46Z" level=info msg="Starting haproxy listener"
> 12/19/2016 8:19:46 PMtime="2016-12-19T19:19:46Z" level=info msg="healthCheck -- starting haproxy\n[WARNING] 353/191946 (18) : config : 'option forwardfor' ignored for proxy 'web' as it requires HTTP mode.\n[WARNING] 353/191946 (18) : config : 'option forwardfor' ignored for backend 'cattle-977ece20-f208-4337-bfed-beba012c6aeb_49312f91-179f-4b8e-9973-a307085b9e74_1' as it requires HTTP mode.\n"
> 12/19/2016 8:19:46 PMtime="2016-12-19T19:19:46Z" level=info msg="Scheduling apply config"
> 12/19/2016 8:19:46 PMtime="2016-12-19T19:19:46Z" level=info msg="healthCheck -- no changes in haproxy config\n"
> 12/19/2016 8:19:48 PMtime="2016-12-19T19:19:48Z" level=info msg="977ece20-f208-4337-bfed-beba012c6aeb_e3c0529c-1392-4074-b02d-7a596dba947e_2=DOWN"
> 12/19/2016 8:19:48 PMtime="2016-12-19T19:19:48Z" level=info msg="Monitoring 2 backends"
> 12/19/2016 8:19:50 PMtime="2016-12-19T19:19:50Z" level=info msg="977ece20-f208-4337-bfed-beba012c6aeb_49312f91-179f-4b8e-9973-a307085b9e74_1=DOWN"
> 12/19/2016 8:19:51 PMtime="2016-12-19T19:19:51Z" level=info msg="Scheduling apply config"
> 12/19/2016 8:19:51 PMtime="2016-12-19T19:19:51Z" level=info msg="healthCheck -- no changes in haproxy config\n"
> 12/19/2016 8:20:11 PMtime="2016-12-19T19:20:11Z" level=info msg="Scheduling apply config"
> 12/19/2016 8:20:11 PMtime="2016-12-19T19:20:11Z" level=info msg="healthCheck -- reloading haproxy config with the new config changes\n[WARNING] 353/192011 (31) : config : 'option forwardfor' ignored for proxy 'web' as it requires HTTP mode.\n[WARNING] 353/192011 (31) : config : 'option forwardfor' ignored for backend 'cattle-977ece20-f208-4337-bfed-beba012c6aeb_ea8bc3df-de01-4bcb-a70a-ae0b7c8dea1f_1' as it requires HTTP mode.\n"
> 12/19/2016 8:20:14 PMtime="2016-12-19T19:20:14Z" level=info msg="977ece20-f208-4337-bfed-beba012c6aeb_ea8bc3df-de01-4bcb-a70a-ae0b7c8dea1f_1=DOWN"

**Comment by matthijsvdr** [comment]
Update:

Deactivating all hosts but 1, then deleting the scheduler and the healthchecks. This will restart the containers on the last "healthy" host, scheduler will start normally, so does the healthcheck on that host.

Then activating a second host, will schedule the healthcheck there as well, but it will never get out of initialising.

**Comment by matthijsvdr** [comment]
just noticed something (not sure if its part of the same issue), all nodes seem to add them selfs with the gateway address instead of there actual IP address.

![screen shot](https://cloud.githubusercontent.com/assets/1271035/21328819/f92bb230-c635-11e6-93fa-27df8510ad89.png)

**Comment by jclark360** [comment]
I've tried the same, re-adding hosts etc.  The wierd thing is, there are no error logs of any kind indicating there is an issue.  Sigh.

**Comment by matthijsvdr** [comment]
@jclark360 I have just been adding stacks, everything seems to be working normally (except all links in the rancher ui link to the wrong ip).

**Comment by leodotcloud** [comment]
@jclark360 @matthijsvdr can you check the logs of containers and sidekicks of network-manager and ipsec?

**Comment by jclark360** [comment]
@leodotcloud if you want, I can get you into our environment to take a look.

**Comment by matthijsvdr** [comment]
@leodotcloud Here are some logs, if you need more I could give you access to rancher server

Networkmanager

level=info msg="Setting up resolv.conf for ContainerId [f7a662cc8be1173c2f7c8cae6d7b267caba6aeb2c33e957e134a5753cf027524]"
level=info msg="Setting up resolv.conf for ContainerId [242c328625866b29abaae6e9c6385b2d56d508ea67d1ce5c74eed9fc68ab005e]"
level=info msg="CNI up" cid=f7a662cc8be1173c2f7c8cae6d7b267caba6aeb2c33e957e134a5753cf027524 networkMode=ipsec
level=info msg="CNI up" cid=242c328625866b29abaae6e9c6385b2d56d508ea67d1ce5c74eed9fc68ab005e networkMode=ipsec
level=info msg="Setting up resolv.conf for ContainerId [1cf2ae0cc970f856f99f9113139e22677ee7c14428b1ce04d238b0908f1b5150]"
level=info msg="Setting up resolv.conf for ContainerId [43492dca4094c6146663180feaa02b36022ed08990fce626914533e6386b085b]"
tch by that name.
tch by that name.
level=error msg="Failed to evaluate network state for 242c328625866b29abaae6e9c6385b2d56d508ea67d1ce5c74eed9fc68ab005e: Bringing up networking: failed to set bridge IP: failed to add IP addr to \"docker0\": file exists"
level=error msg="Error processing event &docker.APIEvents{Action:\"\", Type:\"\", Actor:docker.APIActor{ID:\"\", Attributes:map[string]string(nil)}, Status:\"start\", ID:\"242c328625866b29abaae6e9c6385b2d56d508ea67d1ce5c74eed9fc68ab005e\", From:\"-simulated-\", Time:0, TimeNano:0}. Error: Bringing up networking: failed to set bridge IP: failed to add IP addr to \"docker0\": file exists"
level=info msg="CNI up done" cid=65c4f7e864f8f436b0bbafe8cb35ca3ed6828eb2ed4df703db655a217d4e0a34 networkMode=ipsec result=IP4:{IP:{IP:10.42.237.80 Mask:ffff0000} Gateway:10.42.0.1 Routes:[{Dst:{IP:169.254.169.250 Mask:ffffffff} GW:<nil>} {Dst:{IP:0.0.0.0 Mask:00000000} GW:10.42.0.1}]}, DNS:{Nameservers:[] Domain: Search:[] Options:[]}
level=info msg="CNI up done" cid=f7a662cc8be1173c2f7c8cae6d7b267caba6aeb2c33e957e134a5753cf027524 networkMode=ipsec result=IP4:{IP:{IP:10.42.27.79 Mask:ffff0000} Gateway:10.42.0.1 Routes:[{Dst:{IP:169.254.169.250 Mask:ffffffff} GW:<nil>} {Dst:{IP:0.0.0.0 Mask:00000000} GW:10.42.0.1}]}, DNS:{Nameservers:[] Domain: Search:[] Options:[]}
level=info msg="CNI up done" cid=cd73d45212ec2115fa83f14d4177d5651cfe1124ddb9d264d24689bbde94f917 networkMode=ipsec result=IP4:{IP:{IP:10.42.117.133 Mask:ffff0000} Gateway:10.42.0.1 Routes:[{Dst:{IP:169.254.169.250 Mask:ffffffff} GW:<nil>} {Dst:{IP:0.0.0.0 Mask:00000000} GW:10.42.0.1}]}, DNS:{Nameservers:[] Domain: Search:[] Options:[]}
level=info msg="Evaluating state from retry" cid=242c328625866b29abaae6e9c6385b2d56d508ea67d1ce5c74eed9fc68ab005e
level=info msg="CNI up" cid=242c328625866b29abaae6e9c6385b2d56d508ea67d1ce5c74eed9fc68ab005e networkMode=ipsec
level=info msg="CNI up done" cid=242c328625866b29abaae6e9c6385b2d56d508ea67d1ce5c74eed9fc68ab005e networkMode=ipsec result=IP4:{IP:{IP:10.42.220.1 Mask:ffff0000} Gateway:10.42.0.1 Routes:[{Dst:{IP:169.254.169.250 Mask:ffffffff} GW:<nil>} {Dst:{IP:0.0.0.0 Mask:00000000} GW:10.42.0.1}]}, DNS:{Nameservers:[] Domain: Search:[] Options:[]}
level=info msg="Applying new port rules"
tch by that name.
level=info msg="Applying new port rules"
tch by that name.
level=info msg="Setting up resolv.conf for ContainerId [47460b1551689e751105c54bca3ced261d6dc389deb62811441618407cfaa32c]"
level=info msg="CNI up" cid=47460b1551689e751105c54bca3ced261d6dc389deb62811441618407cfaa32c networkMode=ipsec
level=info msg="CNI up done" cid=47460b1551689e751105c54bca3ced261d6dc389deb62811441618407cfaa32c networkMode=ipsec result=IP4:{IP:{IP:10.42.185.169 Mask:ffff0000} Gateway:10.42.0.1 Routes:[{Dst:{IP:169.254.169.250 Mask:ffffffff} GW:<nil>} {Dst:{IP:0.0.0.0 Mask:00000000} GW:10.42.0.1}]}, DNS:{Nameservers:[] Domain: Search:[] Options:[]}
level=info msg="Setting up resolv.conf for ContainerId [2daec190892ab95e8de14f1aa31de9310dd81ec9d14e85476389e7f65875f103]"
level=info msg="CNI up" cid=2daec190892ab95e8de14f1aa31de9310dd81ec9d14e85476389e7f65875f103 networkMode=ipsec
level=info msg="CNI up done" cid=2daec190892ab95e8de14f1aa31de9310dd81ec9d14e85476389e7f65875f103 networkMode=ipsec result=IP4:{IP:{IP:10.42.225.0 Mask:ffff0000} Gateway:10.42.0.1 Routes:[{Dst:{IP:169.254.169.250 Mask:ffffffff} GW:<nil>} {Dst:{IP:0.0.0.0 Mask:00000000} GW:10.42.0.1}]}, DNS:{Nameservers:[] Domain: Search:[] Options:[]}
level=info msg="Applying new port rules"
level=info msg="CNI down" cid=f7a662cc8be1173c2f7c8cae6d7b267caba6aeb2c33e957e134a5753cf027524 networkMode=ipsec
level=info msg="Applying new port rules"
level=info msg="Setting up resolv.conf for ContainerId [f7a662cc8be1173c2f7c8cae6d7b267caba6aeb2c33e957e134a5753cf027524]"
level=info msg="CNI up" cid=f7a662cc8be1173c2f7c8cae6d7b267caba6aeb2c33e957e134a5753cf027524 networkMode=ipsec
level=info msg="CNI up done" cid=f7a662cc8be1173c2f7c8cae6d7b267caba6aeb2c33e957e134a5753cf027524 networkMode=ipsec result=IP4:{IP:{IP:10.42.27.79 Mask:ffff0000} Gateway:10.42.0.1 Routes:[{Dst:{IP:169.254.169.250 Mask:ffffffff} GW:<nil>} {Dst:{IP:0.0.0.0 Mask:00000000} GW:10.42.0.1}]}, DNS:{Nameservers:[] Domain: Search:[] Options:[]}
level=info msg="Applying new port rules"
level=info msg="Applying new port rules"
level=info msg="CNI down" cid=65c4f7e864f8f436b0bbafe8cb35ca3ed6828eb2ed4df703db655a217d4e0a34 networkMode=ipsec
level=info msg="Applying new port rules"
level=info msg="CNI down" cid=47460b1551689e751105c54bca3ced261d6dc389deb62811441618407cfaa32c networkMode=ipsec
level=info msg="CNI down" cid=cd73d45212ec2115fa83f14d4177d5651cfe1124ddb9d264d24689bbde94f917 networkMode=ipsec


ipsec-ipsec-cni-driver

level=info msg="rancher-cni-ipam: got ip: 10.42.149.166"
level=info msg="rancher-cni-ipam: r: &types.Result{IP4:(*types.IPConfig)(0xc8200666c0), IP6:(*types.IPConfig)(nil), DNS:types.DNS{Nameservers:[]string(nil), Domain:\"\", Search:[]string(nil), Options:[]string(nil)}}"
level=info msg="rancher-cni-ipam: got ip: 10.42.107.138"
level=info msg="rancher-cni-ipam: r: &types.Result{IP4:(*types.IPConfig)(0xc820106300), IP6:(*types.IPConfig)(nil), DNS:types.DNS{Nameservers:[]string(nil), Domain:\"\", Search:[]string(nil), Options:[]string(nil)}}"
level=info msg="rancher-cni-ipam: got ip: 10.42.233.28"
level=info msg="rancher-cni-ipam: r: &types.Result{IP4:(*types.IPConfig)(0xc820010b40), IP6:(*types.IPConfig)(nil), DNS:types.DNS{Nameservers:[]string(nil), Domain:\"\", Search:[]string(nil), Options:[]string(nil)}}"


ipsec-ipsec
This one keeps spamming

level=debug msg="Local: 10.42.81.137"
level=debug msg="Arp request for 10.42.143.254"
level=debug msg="Local: 10.42.143.254"
level=debug msg="Arp request for 10.42.81.137"
level=debug msg="Local: 10.42.81.137"
level=debug msg="Arp request for 10.42.143.254"
level=debug msg="Local: 10.42.143.254"
level=debug msg="Arp request for 10.42.81.137"
level=debug msg="Local: 10.42.81.137"

network-services-metadata
level=info msg="Downloaded in 607.303655ms"
level=info msg="Loading answers"
level=info msg="Loaded answers"
level=info msg="Applied https://EXTERNAL-URL-HERE/v1/configcontent/metadata-answers?version=2855-8c3c62a605f204e6726515e8122e1268"
level=info msg="Downloaded in 239.631797ms"
level=info msg="Loading answers"
level=info msg="Loaded answers"
level=info msg="Applied https://EXTERNAL-URL-HERE/v1/configcontent/metadata-answers?version=2855-8c3c62a605f204e6726515e8122e1268"
level=info msg="Downloaded in 85.629881ms"
level=info msg="Loading answers"
level=info msg="Loaded answers"
level=info msg="Applied https://EXTERNAL-URL-HERE/v1/configcontent/metadata-answers?version=2855-8c3c62a605f204e6726515e8122e1268"

network-services-metadata-dns
level=info msg="Reloading answers"
level=info msg="Reloaded answers"
level=info msg="Reloading answers"
level=info msg="Reloaded answers"
level=info msg="Reloading answers"
level=info msg="Reloaded answers"
level=info msg="Reloading answers"
level=info msg="Reloaded answers"
level=info msg="Reloading answers"
level=info msg="Reloaded answers"


scheduler
level=info msg="Adding resource pool [storageSize] with total 46641115 and used 0 for host 4431a763-0397-4ce4-8888-b4ec31056248"
level=info msg="Initializing event router" workerCount=100
level=info msg="Connection established"
level=info msg="Starting websocket pings"
level=info msg="Hit websocket pong timeout. Last websocket ping received at 2016-12-20 09:44:40.293806732 +0000 UTC. Closing connection."
level=warning msg="websocket closed: websocket: close sent"
level=error msg="Exiting scheduler with error: <nil>"
level=info msg="Listening for health checks on 0.0.0.0:80/healthcheck"
level=info msg="Connecting to cattle event stream."
level=info msg="Subscribing to metadata changes."
level=info msg="Adding resource pool [instanceReservation] with total 1000000 and used 10 for host 977ece20-f208-4337-bfed-beba012c6aeb"
level=info msg="Adding resource pool [cpuReservation] with total 2000 and used 0 for host 977ece20-f208-4337-bfed-beba012c6aeb"
level=info msg="Adding resource pool [memoryReservation] with total 4145020928 and used 0 for host 977ece20-f208-4337-bfed-beba012c6aeb"
level=info msg="Adding resource pool [storageSize] with total 46633652 and used 0 for host 977ece20-f208-4337-bfed-beba012c6aeb"
level=info msg="Adding resource pool [instanceReservation] with total 1000000 and used 12 for host ec9e3ca9-1137-4ff6-b483-1c40b8268503"

**Comment by jclark360** [comment]
I tried changing over from an elb to alb, deleted and re-added hosts, same thing scheduler and health check stuck.  Furthermore any load balancer created also is stuck initializing.

**Comment by leodotcloud** [comment]
@matthijsvdr Can you please check your LB infront of the rancher/server? Please ALB instead of ELB. The hosts being registered with the same source IP address is a problem.

@jclark360 I am assuming your issue is resolved: https://github.com/rancher/rancher/issues/7132#issuecomment-268530775

**Comment by matthijsvdr** [comment]
@leodotcloud I'm not running on aws

**Comment by matthijsvdr** [comment]
@leodotcloud Been trying some things, when connecting directly to the rancher master -> no issues
When connecting via a nginx lb -> errors
When specifying CATTLE_AGENT_IP and connecting via the nginx lb -> no errors 

Looks like rancher does not pickup the correct ip adres.

**Comment by deniseschannon** [comment]
@matthijsvdr Rancher does a best effort in trying to pick up the IP address. If it is picked up incorrectly, then you would need to use CATTLE_AGENT_IP.

**Comment by matthijsvdr** [comment]
I solved my issue by using the CATTLE_AGENT_IP, so I guess this could be closed

**Comment by gaieges** [comment]
Encountered the same issue on hosts in Digital Ocean with Rancher 1.3 and Agent 1.1.3.  Solution was to disable auto-IP detection by setting the CATTLE_AGENT_IP to the **internal** droplet IP address, not the external one (although, YMMV as setting it to the external host worked in other clusters).

**Comment by ElPsyCongro** [comment]
Hi I'm having an issue like this...I have a rancher-server on a local server. What I'm trying to do is add my AWS host with his public IP but they can reach my local server only by VPN connection. (When I execute the command generated by the UI of Rancher to add a host the detected cattle agent IP is his IP of the VPN even when use the public IP of the host for cattle agent IP).
Every host has a OpenVPN client that is running on background providing a tun0 interface, I have a VPN server on AWS that allows connection between clients and redirect all the traffic through the VPN. Also my local server is connected to that VPN.
The AWS hosts get added but when the second host is added the health check stays on initializing and there is no connection between hosts. Any idea of what is happening? What I'm doing is wrong?
