### ISSUE TITLE
load balancer stuck in initializing

### ISSUE THREAD

**Issue by jclark360** [rancher/rancher#7131]
**Rancher Version:**
1.2.1

**Docker Version:**
1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
ubuntu 14.04

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher 3 nodes in AWS, external db

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Install 1.2.1 and deploy a load balancer

**Results:** 
load balancer stuck initializing

**Expected:**
load balancer started

Load balancer log: 

12/19/2016 2:35:44 PMINFO[0000] KUBERNETES_URL is not set, skipping init of kubernetes controller 
12/19/2016 2:35:45 PMINFO[0001] Starting Rancher LB service                  
12/19/2016 2:35:46 PMINFO[0001] LB controller: rancher                       
12/19/2016 2:35:46 PMINFO[0001] LB provider: haproxy
12/19/2016 2:35:46 PMINFO[0001] starting rancher controller                  
12/19/2016 2:35:46 PMINFO[0001] Healthcheck handler is listening on :10241   
12/19/2016 2:35:47 PMINFO[0002]  -- starting haproxy
12/19/2016 2:35:47 PM[ALERT] 353/193546 (31) : Starting frontend GLOBAL: cannot bind UNIX socket [/run/haproxy/admin.sock]
12/19/2016 2:35:47 PM 
12/19/2016 2:35:48 PMINFO[0003]  -- reloading haproxy config with the new config changes
12/19/2016 2:35:48 PM[WARNING] 353/193548 (42) : config : 'option forwardfor' ignored for proxy 'default' as it requires HTTP mode.
12/19/2016 2:35:48 PM

**Comment by matthijsvdr** [comment]
Because you had the same issue as me https://github.com/rancher/rancher/issues/7130 and https://github.com/rancher/rancher/issues/7132

I tried to start a new stack with only a load balancer, same issue, same logs

**Comment by tmiklas** [comment]
I can confirm the same - identical configuration as above with exception I run all worker nodes on RancherOS v0.7.1 (4.4.24).

`12/20/2016 9:06:17 AMtime="2016-12-20T09:06:17Z" level=info msg="KUBERNETES_URL is not set, skipping init of kubernetes controller"
12/20/2016 9:06:17 AMtime="2016-12-20T09:06:17Z" level=info msg="Starting Rancher LB service"
12/20/2016 9:06:17 AMtime="2016-12-20T09:06:17Z" level=info msg="LB controller: rancher"
12/20/2016 9:06:17 AMtime="2016-12-20T09:06:17Z" level=info msg="LB provider: haproxy"
12/20/2016 9:06:17 AMtime="2016-12-20T09:06:17Z" level=info msg="starting rancher controller"
12/20/2016 9:06:17 AMtime="2016-12-20T09:06:17Z" level=info msg="Healthcheck handler is listening on :10241"
12/20/2016 9:06:19 AMtime="2016-12-20T09:06:19Z" level=info msg=" -- starting haproxy\n[ALERT] 354/090618 (34) : Starting frontend GLOBAL: cannot bind UNIX socket [/run/haproxy/admin.sock]\n"
12/20/2016 9:06:20 AMtime="2016-12-20T09:06:20Z" level=info msg=" -- reloading haproxy config with the new config changes\n[WARNING] 354/090620 (45) : config : 'option forwardfor' ignored for proxy 'default' as it requires HTTP mode.\n"`
