### ISSUE TITLE
Crash in Rancher Agent while processing an event causes it to restart constantly

### ISSUE THREAD

**Issue by rezonant** [rancher/rancher#7136]
**Rancher Version:**
1.2.0

**Docker Version:**
1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu Xenial for Rancher server and hosts

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node, internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes Combined Planes (3 node)

**Steps to Reproduce:**
??

**Results:** 
```
time="2016-12-19T22:11:45Z" level=info msg="Received event: Name: compute.instance.activate, Event Id: 043e0484-7c02-4e51-938a-8587c81d9fe8, Resource Id: 1ihm1606"
...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x57a114]

goroutine 35 [running]:
panic(0x834aa0, 0xc42000c070)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/rancher/agent/core/compute.setupNetworkMode(0x76, 0xc42047805a, 0x6, 0x15901060d78, 0xc42046a300, 0x34, 0x0, 0xc42028f940, 0x4, 0x4, ...)
        /go/src/github.com/rancher/agent/core/compute/compute_unix.go:189 +0x364
github.com/rancher/agent/core/compute.setupNetworking(0x76, 0xc42047805a, 0x6, 0x15901060d78, 0xc42046a300, 0x34, 0x0, 0xc42028f940, 0x4, 0x4, ...)
        /go/src/github.com/rancher/agent/core/compute/compute_unix.go:101 +0xd2
github.com/rancher/agent/core/compute.DoInstanceActivate(0x76, 0xc42047805a, 0x6, 0x15901060d78, 0xc42046a300, 0x34, 0x0, 0xc42028f940, 0x4, 0x4, ...)
        /go/src/github.com/rancher/agent/core/compute/compute.go:81 +0xae1
github.com/rancher/agent/handlers.(*ComputeHandler).InstanceActivate(0xc4201fb680, 0xc420126270, 0xc4202a1400, 0x3, 0x3)
        /go/src/github.com/rancher/agent/handlers/compute.go:44 +0x34a
github.com/rancher/agent/handlers.(*ComputeHandler).InstanceActivate-fm(0xc420126270, 0xc4202a1400, 0xc42029bc98, 0x3)
        /go/src/github.com/rancher/agent/handlers/common.go:32 +0x3e
github.com/rancher/agent/handlers.logRequest.func1(0xc420126270, 0xc4202a1400, 0xc42030dd60, 0x5e1101)
        /go/src/github.com/rancher/agent/handlers/common.go:49 +0x14a
github.com/rancher/agent/handlers.cleanLog.func1(0xc420126270, 0xc4202a1400, 0xc4204ee1c0, 0x19)
        /go/src/github.com/rancher/agent/handlers/common.go:55 +0x59
github.com/rancher/agent/vendor/github.com/rancher/event-subscriber/events.doWork(0xc420126270, 0xc4204f08a0, 0xc4202a1400, 0xcb9ac0, 0xc42044a790)
        /go/src/github.com/rancher/agent/vendor/github.com/rancher/event-subscriber/events/worker.go:94 +0x2a4
github.com/rancher/agent/vendor/github.com/rancher/event-subscriber/events.(*skippingWorkerPool).HandleWork.func1(0xc42028c2e0, 0x2, 0xc420126270, 0xc4204f08a0, 0xc4202a1400)
        /go/src/github.com/rancher/agent/vendor/github.com/rancher/event-subscriber/events/worker.go:47 +0x9e
created by github.com/rancher/agent/vendor/github.com/rancher/event-subscriber/events.(*skippingWorkerPool).HandleWork
        /go/src/github.com/rancher/agent/vendor/github.com/rancher/event-subscriber/events/worker.go:48 +0x19f
```
**Expected:**
It shouldn't do that :-)

Discovered this while investigating issue #3596 -- being unable to shell into containers on node 1 (other nodes remained fine), noticed that rancher/agent container was crashing and restarting itself.

I believe problems with the websocket proxy were simply one symptom of Rancher Agent continually crashing on the compute spinup event, so I decided to open a new issue to track this particular cause directly, since it should be easier to fix. Please let me know if you need any diagnostics from the affected node (reading the code referred to in the stack trace shows that things probably shouldn't have been null, so somethings went sideways).

**Comment by StrongMonkey** [comment]
https://github.com/rancher/agent/pull/107

**Comment by StrongMonkey** [comment]
fixed it in this pr but craig and I would suspect that there may be a bigger problem in cattle side.

**Comment by StrongMonkey** [comment]
https://github.com/rancher/rancher/issues/6910

**Comment by rezonant** [comment]
Indeed, this problem is now returning on the same host. The short of the other issue is that Rancher 1.2.1 fixes the crash. I will do an upgrade. Thanks!

**Comment by deniseschannon** [comment]
Sounds good. We'll close it as this issue is resolved. 

As for the bigger issue that might occur, we would need more details on what could trigger it and with the additional agent fixes, we need it to re-occur.

**Comment by rezonant** [comment]
Yep that's fine, I have not seen this crash on Rancher 1.2.1, holding up great. Thanks for all the great ranchery goodness this year guys, happy holidays :-D
