### ISSUE TITLE
Not able to start containers on windows host - ```Expected state running but got error: Error response from daemon: unauthorized: authentication required``

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#7137]
Rancher Version: v1.3.0-rc1

library from rancher/rancher-catalog , branch - vnext

Steps to reproduce the problem:
Create Environment with windows template.

Add a Windows host - Windows Server 2016 Standard Evaluation . ( Used the agent which had extra logs enabled for logging when there is a panic)

Once the host gets to "Active" state , start a service with image ```microsoft\iis```

Container is not able to start and following exception is seen in logs:

```Expected state running but got error: Error response from daemon: unauthorized: authentication required```

**Comment by StrongMonkey** [comment]
@sangeethah can you close it now?

**Comment by sangeethah** [comment]
@StrongMonkey , yes. I have not been able to reproduce this issue anymore. 
Able to start a service with image ``microsoft\iis`` which results in the image being downloaded successfully on the host and container getting launched successfully.
