### ISSUE TITLE
Namespace drop-down has scroll bar on bottom

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#7139]
**Rancher Version:** master 12/19

**Steps to Reproduce:**
1.  Create a kubernetes environment
2.  Click on the Namespace drop-down

**Results:** Weird bottom scrollbar?
![image](https://cloud.githubusercontent.com/assets/11514927/21333261/d5085d92-c60b-11e6-8a3a-816d162a1172.png)

**Expected:**  No scrollbar

**Comment by vincent99** [comment]
No longer applicable

**Comment by tfiduccia** [comment]
Version - master 1/11
Verified it's been removed
