### ISSUE TITLE
Infrastructure dns service running error

### ISSUE THREAD

**Issue by pixyonly1** [rancher/rancher#7140]
**Rancher Version:1.2.1

**Docker Version:1.11.2

**OS and where are the hosts located? (cloud, bare metal, etc):centos7.1 kernel 4.6.0 vm

**Setup Details: single node , internal DB 

**Environment Type: Cattle

**Steps to Reproduce:Create a new stack with 2 services,server and agent. Agent links server as hcs-server.

docker-compose.yml
server:
  image: docker-registry:5000/hcs/server:v2.1
  volumes:
    - /etc/localtime:/etc/localtime

agent:
  image: docker-registry:5000/hcs/agent:v2.1
  privileged: true
  pid: host
  net: host
  stdin_open: true
  links:
    - server:hcs-server
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.container.dns: true
    io.certus.hcs.agent.service.name: hcs-agent
    io.rancher.scheduler.affinity:container_label_ne: io.certus.hcs.agent.service.name=hcs-agent
  volumes:
    - /etc/localtime:/etc/localtime
    - /var/run/docker.sock:/var/run/docker.sock
  entrypoint: /start-agent.sh

**Results:network-services stack dns service running error.Log as follows

2016/12/20 上午9:34:12time="2016-12-20T01:34:12Z" level=info msg="Starting rancher-dns v0.10.8"
2016/12/20 上午9:34:12time="2016-12-20T01:34:12Z" level=info msg="Loaded answers"
2016/12/20 上午9:34:12time="2016-12-20T01:34:12Z" level=info msg="Listening for Reload on 127.0.0.1:8113"
2016/12/20 上午9:34:12time="2016-12-20T01:34:12Z" level=info msg="Listening on :53"
2016/12/20 上午9:34:12time="2016-12-20T01:34:12Z" level=info msg="Reloading answers"
2016/12/20 上午9:34:12time="2016-12-20T01:34:12Z" level=info msg="Reloaded answers"
2016/12/20 上午9:34:12panic: runtime error: invalid memory address or nil pointer dereference
2016/12/20 上午9:34:12[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x40d82d]
2016/12/20 上午9:34:12
2016/12/20 上午9:34:12goroutine 16 [running]:
2016/12/20 上午9:34:12panic(0x7d6a00, 0xc4200140a0)
2016/12/20 上午9:34:12	/usr/local/go/src/runtime/panic.go:500 +0x1a1
2016/12/20 上午9:34:12main.route(0xbd6920, 0xc420124150, 0xc42027e1b0)
2016/12/20 上午9:34:12	/go/src/github.com/rancher/rancher-dns/main.go:321 +0x90d
2016/12/20 上午9:34:12github.com/rancher/rancher-dns/vendor/github.com/miekg/dns.HandlerFunc.ServeDNS(0x863038, 0xbd6920, 0xc420124150, 0xc42027e1b0)
2016/12/20 上午9:34:12	/go/src/github.com/rancher/rancher-dns/vendor/github.com/miekg/dns/server.go:82 +0x44
2016/12/20 上午9:34:12github.com/rancher/rancher-dns/vendor/github.com/miekg/dns.(*ServeMux).ServeDNS(0xc420014950, 0xbd6920, 0xc420124150, 0xc42027e1b0)
2016/12/20 上午9:34:12	/go/src/github.com/rancher/rancher-dns/vendor/github.com/miekg/dns/server.go:186 +0x61
2016/12/20 上午9:34:12github.com/rancher/rancher-dns/vendor/github.com/miekg/dns.(*Server).serve(0xc42016e000, 0xbd20e0, 0xc4203e4600, 0xbcf5e0, 0xc420014950, 0xc42015c200, 0x1c, 0x200, 0xc42015e028, 0xc420154480, ...)
2016/12/20 上午9:34:12	/go/src/github.com/rancher/rancher-dns/vendor/github.com/miekg/dns/server.go:535 +0x4e6
2016/12/20 上午9:34:12created by github.com/rancher/rancher-dns/vendor/github.com/miekg/dns.(*Server).serveUDP
2016/12/20 上午9:34:12	/go/src/github.com/rancher/rancher-dns/vendor/github.com/miekg/dns/server.go:489 +0x2c8
2016/12/20 上午9:34:22time="2016-12-20T01:34:22Z" level=info msg="Starting rancher-dns v0.10.8"
2016/12/20 上午9:34:22time="2016-12-20T01:34:22Z" level=info msg="Loaded answers"
2016/12/20 上午9:34:22time="2016-12-20T01:34:22Z" level=info msg="Listening for Reload on 127.0.0.1:8113"
2016/12/20 上午9:34:22time="2016-12-20T01:34:22Z" level=info msg="Listening on :53"
2016/12/20 上午9:34:22time="2016-12-20T01:34:22Z" level=info msg="Reloading answers"
2016/12/20 上午9:34:22time="2016-12-20T01:34:22Z" level=info msg="Reloaded answers"
2016/12/20 上午9:34:24panic: runtime error: invalid memory address or nil pointer dereference
2016/12/20 上午9:34:24[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x40d82d]
2016/12/20 上午9:34:24
2016/12/20 上午9:34:24goroutine 15 [running]:
2016/12/20 上午9:34:24panic(0x7d6a00, 0xc4200140a0)
2016/12/20 上午9:34:24	/usr/local/go/src/runtime/panic.go:500 +0x1a1
2016/12/20 上午9:34:24main.route(0xbd6920, 0xc420198000, 0xc42014e240)
2016/12/20 上午9:34:24	/go/src/github.com/rancher/rancher-dns/main.go:321 +0x90d
2016/12/20 上午9:34:24github.com/rancher/rancher-dns/vendor/github.com/miekg/dns.HandlerFunc.ServeDNS(0x863038, 0xbd6920, 0xc420198000, 0xc42014e240)
2016/12/20 上午9:34:24	/go/src/github.com/rancher/rancher-dns/vendor/github.com/miekg/dns/server.go:82 +0x44
2016/12/20 上午9:34:24github.com/rancher/rancher-dns/vendor/github.com/miekg/dns.(*ServeMux).ServeDNS(0xc420014950, 0xbd6920, 0xc420198000, 0xc42014e240)
2016/12/20 上午9:34:24	/go/src/github.com/rancher/rancher-dns/vendor/github.com/miekg/dns/server.go:186 +0x61
2016/12/20 上午9:34:24github.com/rancher/rancher-dns/vendor/github.com/miekg/dns.(*Server).serve(0xc420178000, 0xbd20e0, 0xc420280ba0, 0xbcf5e0, 0xc420014950, 0xc42012c400, 0x22, 0x200, 0xc420160028, 0xc4202cfa80, ...)
2016/12/20 上午9:34:24	/go/src/github.com/rancher/rancher-dns/vendor/github.com/miekg/dns/server.go:535 +0x4e6
2016/12/20 上午9:34:24created by github.com/rancher/rancher-dns/vendor/github.com/miekg/dns.(*Server).serveUDP
2016/12/20 上午9:34:24	/go/src/github.com/rancher/rancher-dns/vendor/github.com/miekg/dns/server.go:489 +0x2c8

**Expected:**

**Comment by aemneina** [comment]
@pixyonly1  have you tried this with a recent version of rancher? I'm going to close this out, if its reproducible there please raise another ticket.
