### ISSUE TITLE
Reference to add linux hosts in "windows" environment

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#7141]
Rancher Version: v1.3.0-rc1

<img width="956" alt="screen shot 2016-12-19 at 7 51 49 pm" src="https://cloud.githubusercontent.com/assets/4266958/21337735/ab72078a-c624-11e6-95c8-626610dcfbb9.png">

**Comment by tfiduccia** [comment]
Version - v1.3.0-rc2
Now say Window's host
Verified fixed
