### ISSUE TITLE
Rancher agent starts containers with wrong MTU (1500)

### ISSUE THREAD

**Issue by charliefd** [rancher/rancher#7143]
**Rancher Version:**
1.2.0
**Docker Version:**
1.10.3
**OS and where are the hosts located? (cloud, bare metal, etc):**
CentOS
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node external DB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
Install rancher server 1.2.0. Register to  a cattle environment a docker host configured with default bridge mtu lower than 1500. The Server will start deploying the infrastructure stacks. Afterwards deploy a user stack.
**Results:** 
All but first container on the host will have a MTU of 1500. that includes some of the infrastructure containers and all user stacks.
**Expected:**
All containers should have the mtu of the default bridge (docker0). 

With rancher 1.1.4 all used to work correctly in this respect. The 1.2.0 version introduced this bug not allowing us to deploy in an environment where the host uses --mtu=1450 for docker daemon

**Comment by isp14** [comment]
I have the same problem.

Rancher Version:
1.2.0
Docker Version:
1.12.3, build 6b644ec

**Comment by leodotcloud** [comment]
Please test with ipsec template: v0.0.3 (rancher/net:v0.8.2), vxlan template: v0.0.3 (rancher/net:v0.8.2), network-services v0.0.9 (rancher/network-manager:v0.4.1)

**Comment by charliefd** [comment]
upgraded ipsec to rancher/net:v0.8.2 (still the cni-driver and router services report using v0.8.1), and the network-services to rancher/network-manager:v0.4.1. After docker restart the mtu of one of the containers is correct and equal to docker0 mtu but everything else still starts with 1500

**Comment by charliefd** [comment]
upgraded ipsec to rancher/net:v0.8.2, and network-services to rancher/network-manager:v0.4.1.

After docker restart the mtu of one of the containers is correct (agent) and equal to docker0 MTU but everything else still starts with 1500. If you need specific info let me know

**Comment by deniseschannon** [comment]
@charliefd how did you upgrade?

**Comment by charliefd** [comment]
@deniseschannon from the UI, changed the image version for the ipsec and network-services to the ones specified. In the case of ipsec I did this for all its components (also called services, confusing terminology here): ipsec-ipsec, ipsec-ipsec-cni-driver and ipsec-ipsec-router

**Comment by deniseschannon** [comment]
Changing just the image name doesn't guarantee that you'll get the updated template. The updated template is in a different branch right now for testing. 

If you would like to test it out, you'd need to point your default library catalog to our testing catalog.

Name: library
Git URL: https://github.com/rancher/rancher-catalog
Branch: v1.4.0-rc2

**Comment by charliefd** [comment]
thanks! I replaced the infrastructure stacks with the ones from v1.4.0-rc2, migrated to vxlan with this occasion, and I can confirm that the correct MTU is used!

**Comment by galal-hussein** [comment]
Rancher version: v1.4.0-rc3 

I verified the fix using ipsec/vxlan (rancher/net:v0.8.6) and (rancher/network-manager:v0.4.5)

I adjusted MTU for ipsec/vxlan to less than 1500 and got the correct MTUs for the containers:

MTU(1450) - linkMTUOverhead(98 for ipsec) = 1352
MTU(1450) - linkMTUOverhead(50 for vxlan) = 1400
