### ISSUE TITLE
Balancer: Wildcard host behavior wrong

### ISSUE THREAD

**Issue by vincent99** [rancher/rancher#7145]
In 1.1.x, `*.host.com` correctly turned into `hdr_end(.host.com)`.  In 1.2 it turns into `hdr_end(host.com)`, which matches other things like `otherhost.com`.

https://github.com/rancher/lb-controller/blob/master/controller/rancher/rancher.go#L223-L231

Also we should add a way to do `host.com` + `*.host.com` in one rule, like `**.host.com`.

**Comment by alena1108** [comment]
@vincent99 for 1.4, I'm going to address the first part of the issue. We can figure out the format for the ```host.com``` + ```*host.com``` in the future release separately.

**Comment by sangeethah** [comment]
Tested with rancher-server version - v1.4.0-rc5

Created LB with following port Rule:

<img width="1493" alt="screen shot 2017-01-30 at 2 39 54 pm" src="https://cloud.githubusercontent.com/assets/4266958/22444935/058b79b8-e6fa-11e6-97e4-dcb30e97ee50.png">


haproxy config gets configured with  hdr_end(host.com)

```
frontend 8090
bind *:8090
mode http
acl 8090_host_com__host hdr_end(host) -i .host.com
acl 8090_host_com__host hdr_end(host) -i .host.com:8090
use_backend 8090_host_com_ if 8090_host_com__host
```
When accessing the LB with host set to "abchost.com" , it gets ```503 Service Unavailable``` as expected.

```
Sangeethas-MBP:testwget sangeethahariharan1$ wget  --header="host: abchost.com" http://45.55.67.19:8090/name.html
--2017-01-30 14:47:02--  http://45.55.67.19:8090/name.html
Connecting to 45.55.67.19:8090... connected.
HTTP request sent, awaiting response... 503 Service Unavailable
2017-01-30 14:47:02 ERROR 503: Service Unavailable.

Sangeethas-MBP:testwget sangeethahariharan1$ wget  --header="host: abc.host.com" http://45.55.67.19:8090/name.html
--2017-01-30 14:47:07--  http://45.55.67.19:8090/name.html
Connecting to 45.55.67.19:8090... connected.
HTTP request sent, awaiting response... 200 OK
Length: 13 [text/html]
Saving to: ‘name.html’

100%[==================================================================================================================================================================>] 13          --.-K/s   in 0s      

2017-01-30 14:47:07 (1.03 MB/s) - ‘name.html’ saved [13/13]
```
