### ISSUE TITLE
show only hosts in "active" state in "Run all containers on a specific host" option when creating services.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#7147]
Rancher-server version - v1.3.0-rc1

UI currently show hosts in  "inactive"/"reconnecting" state in "Run all containers on a specific host" option when creating services. 
This list of host should include only hosts in "active" state.

**Comment by vincent99** [comment]
Scheduling to them is valid.. The state is shown if it's not active.

![image](https://user-images.githubusercontent.com/753917/30314158-b2a1f298-9754-11e7-93fb-7f9268f77941.png)
