### ISSUE TITLE
SSH bug almost certain across subnets

### ISSUE THREAD

**Issue by longwuyuan** [rancher/rancher#7155]
**Rancher Version:**
1.2.1
**Docker Version:**
1.12
**OS and where are the hosts located? (cloud, bare metal, etc):**
RancherOS on AWS
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
SingleNode-Rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes
**Steps to Reproduce:**
- Create VPC with public private subnet in AWS ap-northeast-1 region with NAT-Gateway using EIP
- Launch instance with debian jessie in public subnet and install get the SSL reverseproxy Nginx going as per this docs here
http://docs.rancher.com/rancher/v1.2/en/installing-rancher/installing-server/basic-ssl-config/
- Set DNS entry to EIP of debian jessie instance in public subnet 
- Launch Instance with ami-be5bf2df in private (not public) subnet
- Fireup rancher/server container with bind mount MySQL
- Connect over SSL to Nginx and to access Rancher GUI in browser
- Enable local admin
- Set registration URL to private http://<private-subnet-ip-address>:8080
- Create Kubernetes environ. Switch to Kubernetes environ and Delete default cattle environ. 
- Add host with ami-be5bf2df in private subnet with all other defaults
- Watch ..... an wait and wait and wait and wait and wait
**Results:** 
- New node will perennially wait for SSH connection
**Expected:**
- Node should complete install and init of agent etc

** Note it worked once so I must have screwed up **
- I can give remote access over shared screen
- We need to go into production
- We are betting big on rancher/server
- If there is a threat to use Rancher on AWS, we beg you humbly to flag us
- Willing to look into incident support payment
- I need to run services by weekend as Monday is deadline for customer demo

**Comment by bishalkc** [comment]
Same issue here, I was creating host with RancheOS ami-c6d073a5 (ap-southeast-1 region)

**Comment by longwuyuan** [comment]
Hi @ibuildthecloud & @vincent99 ,

In a AWS VPC with public & private subnet, if the rancher-server host is in public-subnet and the node-host is launched in private-subnet, then node creation fails and waits for ever in "Waiting for ssh to be available", even though the security-group config is allowing 2 way ssh between rancher-server container in public subnet and node host in private subnet. In example below X.X.10.X/0 is publicsubnet  and X.X.20.X/0 is private subnet. It shows I can ssh both ways ;

_**[rancher@ip-X-X-10-X ~]$ ssh -i .<key> rancher@X.X.20.X
The authenticity of host 'X.X.20.X (X.X.20.X)' can't be established.
ECDSA key fingerprint is SHA256:inDe5LNxm28e3kaoHYakGVZ8hJTDZ1WxOyawCx11eQ8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'X.X.20.X' (ECDSA) to the list of known hosts.
[rancher@ip-X-X-20-X ~]$ ssh X.X.10.X
The authenticity of host 'X.X.10.X (X.X.10.X)' can't be established.
ECDSA key fingerprint is SHA256:mYGADlfW9EZx19I0TfLwRUNdnLl/q4hrsUGV54GZgM8.
Are you sure you want to continue connecting (yes/no)?**_ 

This likely means that the custom docker-networking of rancher is not working across subnets of a CIDR. I have tested this 10 times or more.

The impact for me at least is that cluster-ip needs to be in public-subnet so I can FQDN to multiple serrvices in the cluster but the nodes are forced to be in the public-subnet as well and end up with a AWS-Public-IP-Address (not a EIP) meaning my containers are on a Internet-Public-IP-Address (although with security-groups and other port open/close functions).

Nauseating to think my containers are on a Internet-Public-IP-Address.

If I put the rancher-server-container host also in the Private-Subnet then have to deal with a reverse-proxy and SSL configuration with HAProxy example in docs is wrong it seems. The HAProxy example here  http://docs.rancher.com/rancher/v1.2/en/installing-rancher/installing-server/basic-ssl-config/  connects to the backend over SSL but the Nginx example connects to the backend without SSL.

I am a noob so please forgive me for asking but this is what I am trying to accomplish ;

- SingleNode rancher with SSL
- Nodes not having internet-public-ip-address

Please advise what I am doing wrong.

**Comment by vincent99** [comment]
The Rancher overlay network is not involved at all in host creation.

What we do is literally call `docker-machine` in the server container with the parameters you configured in the API/UI.  It then calls the provider API to create (in this case) an EC2 instance.  The provider code gets the IP address of the newly created host and machine attempts to SSH to it using the key it created.

So all that matters is that the host's IP is reachable from the server container.  And server container does not participate in the overlay network at all.

**Comment by longwuyuan** [comment]
Thanks a lot @vincent99 .
What kind of test beyond the ssh attempt I copy/pasted above can help me simulate what docker-machine is doing. Maybe docker-machine executable in the rancher-server container !

**Comment by vincent99** [comment]
You can definitely exec into the server container and run `docker-machine -D create --dricer=amazonec2 ...etc...`.  If it does complete successfully the host won't be added to Rancher since you didn't run it with the right user data, but otherwise this is the same up to the point of having docker installed on the host and being ready to go.

**Comment by longwuyuan** [comment]
ok thanks. i will try and update. i  guess we are a corner use case. but if you have info that public-subnet-rancher-server-host and private-subnet-nodes work ..... then please tell me so that i decidedly know that it is my fault someplace here

**Comment by longwuyuan** [comment]
turns out a non-issue as packet filter config needs to change per host changes
