### ISSUE TITLE
WebSocket connection to 'wss://rancher.example.net' failed: HTTP Authentication failed; no valid credentials available

### ISSUE THREAD

**Issue by Sharuru** [rancher/rancher#7157]
**Rancher Version:**
Rancher v1.2.1
**Docker Version:**
1.12.5, build 7392c3b
**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04.1 LTS (GNU/Linux 4.4.0-53-generic x86_64), VMs in VMware ESXi.
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Rancher server on Host A, Agent on Host B, just one node.
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
After normal installation, everythings seems good.
Then setting something like Nginx for proxy pass.
Everything still works fine.
**Results:** 
Suddenly, websocket connection failed in Chrome console, make graph or shell show nothing.
**My try:**
Revert config, using HTTP connection.
Revert confing, using IP connection.
Upgrade server from v1.2.0 to v1.2.1.
Restart both server and agent container.
Restart system.
**Other may help:**
Nginx config:
```
upstream rancher {
    server 172.17.0.2:8080;
}

server {
    listen 443 ssl;
    server_name rancher.example.net;
    ssl_certificate /home/user/ssl/example.net/example.net.crt;
    ssl_certificate_key /home/user/ssl/example.net/example.net.key;

    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://rancher;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        # This allows the ability for the execute shell window to remain open for up to 15 minutes. Without this parameter, the default is 1 minute and will automatically close.
        proxy_read_timeout 900s;
    }
}

server {
    listen 80;
    server_name rancher.example.net;
    return 301 https://$server_name$request_uri;
}
```
Chrome console log:
```
WebSocket connection to 'wss://rancher.example.net/v1/containerstats/service/?token=secret&sockId=40' failed: HTTP Authentication failed; no valid credentials available
```
Screenshot:
![image](https://cloud.githubusercontent.com/assets/3275627/21376154/124de788-c776-11e6-9aa0-92d2606aadf2.png)

Please help me, thank you!

**Comment by Sharuru** [comment]
Update:
After tracing logs of server and agent, found:
Server:
```
time="2016-12-21T04:06:45Z" level=info msg="Invalid HostUuid." hostUuid=3ac1622f-7bc1-46b0-549e-1f72b64e9b1a 
time="2016-12-21T04:06:45Z" level=info msg="Stats auth failed: could not find host uuid" 
```
Agent:
```
time="2016-12-21T04:07:28Z" level="info" msg="Starting event router." 
time="2016-12-21T04:07:28Z" level="info" msg="Connecting to proxy." url="wss://rancher.example.net/v1/connectbackend?token=secret" 
time="2016-12-21T04:07:28Z" level="fatal" msg="Failed to connect to proxy." error="x509: certificate signed by unknown authority" 
time="2016-12-21T04:07:28Z" level=error msg="exit status 1" 
```

I am using self-signed certs, found simulate issues in tracker :cry:

**Comment by Sharuru** [comment]
After disable all https setting and change Host Registration URL to http, everything works fine...

Any plan about support on self-signed certs? :rose: 

Sorry for disturb.

**Comment by Sharuru** [comment]
Seems solved in 1.3.0 :clinking_glasses:

**Comment by TotalLag** [comment]
Sorry to hijack, but I am also running into this issue in the latest 1.3.4 when I have no issues on 1.3.0.  @Sharuru have you upgraded and are you still getting old issues?

**Comment by Sharuru** [comment]
@TotalLag Yes, upgraded to 1.3.4 already. 
But as our team using rancher in private network, we are using HTTP instead of HTTPS.
Can not confirm this issue for you, Sorry 😞

**Comment by kuhnroyal** [comment]
Running into this on 1.4.0 with a 'real' wildcard certificate.

```
wss://rancher.example.com/v1/containerstats/abc?token=xyz
```

**Comment by kuhnroyal** [comment]
Actually this turned out to be a missing Connection/Upgrade header for me.

**Comment by rpcragesh** [comment]
.AddJwtBearer(options =>
            {
                // options.RequireHttpsMetadata = false;
                **options.SaveToken = true;
                options.TokenValidationParameters = new TokenValidationParameters
                {
                    ValidateIssuerSigningKey = true,
                    IssuerSigningKey = new SymmetricSecurityKey(key),
                    ValidateIssuer = false,
                    ValidateAudience = false
                };**

                //options.Authority = "https://192.168.1.10:5001"; /* TODO: Insert Authority URL here */

                options.Events = new JwtBearerEvents
                {
                    OnMessageReceived = context =>
                    {

                        var accessToken = context.Request.Query["access_token"];
                        var authToken = context.Request.Headers["Authorization"].ToString();

                        var token = !string.IsNullOrEmpty(accessToken) ? accessToken.ToString() : !string.IsNullOrEmpty(authToken) ? authToken.Substring(7) : String.Empty;

                        // If the request is for our hub...
                        var path = context.HttpContext.Request.Path;
                        if (!string.IsNullOrEmpty(accessToken) &&
                            (path.StartsWithSegments("/WebrtcHub")))
                        {
                            context.Token = accessToken;
                            //context.Request.Headers.Add("Authorization", "Bearer " + accessToken);
                        }
                        return Task.CompletedTask;
                    }
                };

            });
