### ISSUE TITLE
kubelet cannot access rancher-metadata

### ISSUE THREAD

**Issue by Flowman** [rancher/rancher#7160]
**Rancher Version:**
1.2.1
**Docker Version:**
1.12.5
**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04 LTS
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single nod rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes 1.4.6
**Steps to Reproduce:**
Create a new environment
Add a host to environment
**Results:** 
Everything is green but 'kubectl get nodes' returns null.

Looks like the kubelet service cannot access internal dns so is just loops on:

21/12/2016 18:29:39+ curl -s -f http://rancher-metadata/2015-12-19/stacks/Kubernetes/services/kubernetes/uuid
21/12/2016 18:29:39Waiting for metadata
21/12/2016 18:29:39+ echo Waiting for metadata
21/12/2016 18:29:39+ sleep 1
21/12/2016 18:29:40+ curl -s -f http://rancher-metadata/2015-12-19/stacks/Kubernetes/services/kubernetes/uuid
21/12/2016 18:29:40Waiting for metadata

Tried to do a nslookup on 
**Expected:**
The environment to start up and work.

**Comment by Flowman** [comment]
So I get this issue when I run it in Azure. A specify the agent ip on install to the local ip address of the vm. 
The weird thing is that all the other services like proxy and scheduler can find the internal dns for rancher-metadata.

If I run it locally on my virtualbox everything works fine.

**Comment by Flowman** [comment]
After some more digging dns works but cannot get to the host.
![image](https://cloud.githubusercontent.com/assets/212680/21445772/615695a4-c8f8-11e6-9cd1-7e81ec4bf1fa.png)

Example of the working proxy container.
![image](https://cloud.githubusercontent.com/assets/212680/21445776/6d9016e2-c8f8-11e6-8791-eb48782702ba.png)

**Comment by janeczku** [comment]
@Flowman in the kubelet container please run 'nslookup rancher-metadata' (without the rancher.internal part) and paste the content of resolv.conf.

**Comment by Flowman** [comment]
@janeczku here is the info you wanted.

![image](https://cloud.githubusercontent.com/assets/212680/21514183/1780aa1a-ccfd-11e6-87ad-470864cd84b0.png)

I have updated to rancher 1.2.2 and still the same issue.

**Comment by antmanler** [comment]
Same problem.

It seems that curl used the nameservers in /run/resolvconf/resolv.conf, since it is mounted from host's /run

**Comment by zzp8164** [comment]
Same problem , is there any way to walk around?

**Comment by zzp8164** [comment]
Temporarily walk around by pasting /run/resolvconf/resolv.conf in the host machine with /etc/resolv.conf in the container.

**Comment by zzp8164** [comment]
Still same problem after updating to Rancher v1.4.1

**Comment by niusmallnan** [comment]
@all 
I think I have find the essential reason. https://github.com/rancher/rancher/issues/8038

**Comment by aemneina** [comment]
Should be resolved with the latest 1.5. Closing this out. If anyone hits this in a recent version of 1.5, please holler.
