### ISSUE TITLE
network-services catalog v0.0.6 is breaking network in rancher v1.2.0

### ISSUE THREAD

**Issue by Toonix** [rancher/rancher#7163]
Rancher Version: 1.2.0

Docker Version: 1.12.3

OS and where are the hosts located? RancherOS on ESX

Setup Details: single node, internal DB

Environment Type: (Cattle)

Network Service Upgrade from v.0.0.5 to v0.0.6

Results:

After Upgrade Container with a Service Link aren't working anymore. (No Connection to Database).

**Comment by deniseschannon** [comment]
Can you try updating to Rancher 1.2.2 with the updated network-service v0.0.7?
