### ISSUE TITLE
Healthcheck container dies frequently

### ISSUE THREAD

**Issue by yoerayo** [rancher/rancher#7165]
**Rancher Version:** 1.2.1

**Docker Version:** 1.12.5

**OS and where are the hosts located? (cloud, bare metal, etc):** CentOS 7 in VMware

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node with mounted DB path, one host with server and agent, and one host with just an agent.

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Create an environment per the above setup details.  

**Results:** 
The healthcheck container on the host with just the agent dies and restarts about every 10 minutes.  This also causes any services with healthchecks to be marked unhealthy until after the healthcheck container finishes getting recreated.

**Expected:**
Healthcheck containers on both hosts stay up and don't incorrectly mark services as unhealthy.

**Comment by sra** [comment]
Could this be related to ICMP access? I am seeing this behavior on one host that is part of an environment mostly on AWS. This host is not on AWS and doesn't have ICMP yet. It takes an act of god to get the firewall changed.

I think it is the only one in this environment that keeps falling over (the oddball host).

**Comment by yoerayo** [comment]
I don't think so. Both hosts are VMs in the same internal environment and subnet and can ping each other just fine.

**Comment by pulberg** [comment]
same issue here, RHEL7.2, VMware ESX

**Comment by pulberg** [comment]
This is now resolved for me after updating the kernel on my RHEL7.2 hosts to -

3.10.0-514.2.2.el7.x86_64

**Comment by yoerayo** [comment]
Same here, upgrading the kernel seems to have resolved my issue.
