### ISSUE TITLE
Feature Request: add ability exclude hosts from default scheduler

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#7168]
I think it would be good to be able to enforce or per-populate default scheduling rules per environment. For example, in my production or staging environment set scheduling rule by default to deploy on servers with label purpose=apps, this way apps can't accidentally get deployed to management servers for example. 

To further explain my point, my environment consists of different types of servers, like management, edge router, applications, services, workers, etc ... basically want/need the ability to say by default (if no options are changed) that stacks can only be deployed to the application servers. Edge router should only have reverse proxies, services should only have databases or backend worker services. 

## Use Case 
I want rancher to control all my servers, but I need some dedicated name servers for running cluster services like consul server. This sort of setup requires that there be at least 3 consul servers or more and odd number. These servers can't change, they need to remain consistent so that other servers in the environment can have the consul agent installed and register with 1 or more of the consul servers.

However these management servers shouldn't have other apps scheduled on them by default, for example if I am going to deploy 2 or 3 stacks, the management servers should always be excluded unless manually overridden.

**Comment by vincent99** [comment]
Discussion in #7169.
