### ISSUE TITLE
Scheduling doesn't count properly when adding a new service or adding scale

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#7170]
**Rancher Version:** master 2/21

**Steps to Reproduce:**
1.  Create a new cattle environment with 2 hosts and wait for everything to setup (the extra scheduler container is on the first host)
2.  Create a new service with a scale of 6 (first container will go to host1, even though it already has an extra container)
3.  Click on info and scale the service 1 at a time. (wait between to make sure container is active and should be part of count, notice it never evens out)
4.  Create another service with scale of 2. (notice it puts 1 on each host, instead of putting them both on host2 to try to even out containers)

**Results:** Notice the count is uneven and not matter how many time I try to even it out, it never does.  Host1 will always at least 2 more container then other host.
![image](https://cloud.githubusercontent.com/assets/11514927/21403799/9891f820-c77b-11e6-931c-a3cf2532f34a.png)

**Expected:**  Host should even out.

**Comment by tfiduccia** [comment]
Version - master 2/27
Verified fixed

**Comment by StrongMonkey** [comment]
oh it is not fixed!!
