### ISSUE TITLE
Stats for Load Balancer container not showing up in LB service details

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#7172]
**Rancher Version:**  master 11/21

**Steps to Reproduce:**
1.  Create a load balancer service
2.  Once it's fully started,  go to the Service details page and click on Containers tab

**Results:** Container Stats says n/a
![image](https://cloud.githubusercontent.com/assets/11514927/21408305/93f933d0-c791-11e6-90ba-2b925101ae52.png)

**Expected:** Stats should show up.

**Comment by vincent99** [comment]
@ibuildthecloud `containerStats` link is missing on `loadBalancerService` resources.

**Comment by tfiduccia** [comment]
Version - 1/17
Verified fixed
