### ISSUE TITLE
Rancher service is "unhealthy" without a healthcheck

### ISSUE THREAD

**Issue by nhumrich** [rancher/rancher#7175]
**Rancher Version:**
1.1.4

**Docker Version:**
1.10

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu/AWS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single master with external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

I have a deployment script for rancher that starts a deploy by using the upgrade api, then it waits for the service to be done upgrading and finishes the upgrade. While its waiting for the upgrade to complete, it checks the `healthState` of the service every 3 seconds to see if the new container is working correctly, if the service ever becomes `unhealthy` it cancels the upgrade and prints the logs of the "bad" container. The upgrade always uses the "start before stop" feature, so that the new container should be up before the old one goes away. 
If I deploy multiple services at once, the services can get into a state where it is considered "unhealthy". However, when I check the new container, it started up just fine. The weird thing is I turned off healthchecks and I still saw that behaviour. Why would a service without healthchecks be considered unhealthy during a deploy? 
Is there anyway to get more information of why its unhealthy?
I have found that if I dont let my script automatically roll-back, everything ends up working correctly if I just wait long enough.

**Comment by aemneina** [comment]
@nhumrich do you know if this issue exists in a recent version of rancher? A lot has changed since 1.1.x, it'd be good to know if you can reproduce in 1.5.6+.
