### ISSUE TITLE
Swarm environment not setting up - swarmkit-mon stuck in initializing

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#7178]
**Rancher Version:** v1.2.2-rc1

**Steps to Reproduce:**
1.  Create three DO machine with private IP
2.  Install docker 1.12.3 
3.  Add those host to swarm environment

**Results:** The main swarmkit-mon container logs keeps saying "12/21/2016 5:16:23 PMRetrying publishing tokens".  the second and third host swarmkit-mon are stuck in initializing.

**Expected:**  Should setup.

**Comment by LLParse** [comment]
First environment functioned correctly. Second environment reproduced the bug.

The API call to Rancher that should write the worker/manager tokens to the service is failing. Performed a packet capture and observed the service UUID read from metadata was null. This is a known race condition where metadata isn't always populated to the host before the container begins exection.

Temporary workaround is to add a loop to wait for metadata to become available.

**Comment by deniseschannon** [comment]
Available in community catalog, branch `swarmtest` with swarmkit:v1.12.3-2

**Comment by tfiduccia** [comment]
Version - v1.2.2-rc2 swarmkit 1.12.3-2
Verified fixed.
