### ISSUE TITLE
Change backend server name to be random string, like 1.1.x behavior.

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#7179]
**Rancher Version:**
v1.2.1

Is there a way to change backend server name to be a random string like earlier, because even if we inject another cookie the cookie exposes our container IP’s. Considering our application is internet facing, we would obviously like to hide as much environment information as possible.

**Comment by alena1108** [comment]
It can't be random as we sort the things in haproxy config based on the uuids' of backends/frontend/servers. We can hash the string though.

**Comment by sangeethah** [comment]
Tested with racher-server build from master and using rancher/lb-service-haproxy:v0.5.1 .
backend server name names in the haproxy config file has random string.

```
mode http
server 9057e65b9b03f83122b68d0957a053f9a86dd396 10.42.50.49:80
server 7a8679e9a00990fe287bd4c3034f8ae9ec3f5ccc 10.42.41.101:80
server 5f2d8f478a0d14ce356a0bea87c45fb3b61c4704 10.42.19.58:80
```

Automation runs using this haproxy image rancher/lb-service-haproxy:v0.5.1did not report any regressions.
