### ISSUE TITLE
[CLI] Authentication failure when trying to create stack from custom catalog template

### ISSUE THREAD

**Issue by michielrensen** [rancher/rancher#7182]
**Rancher Version:**
v1.2.1

**Docker Version:**
v1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
AWS EC2

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher + RDS DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
`rancher --url <URL> --access-key <ACCESS_KEY> --secret-key <SECRET_KEY> catalog install --name <STACK_NAME> <TEMPLATE_NAME>`

Where 
URL=/v2-beta/projects/<PROJECT_ID>
ACCESS_KEY/SECRET_KEY=account API keys from an Admin user

**Results:** 
`FATA[0004] Bad response 401 looking up <DOMAIN_NAME>/v1-catalog/templates/<TEMPLATE_ID>`

Looking at local proxy details it only shows `Unauthorized` but no further details.

**Expected:**
The stack being created

Since the originating URL is different from the actual URL being called (i.e. `/v2-beta/projects/PROJECT_ID` vs `/v1-catalog/templates/<TEMPLATE_ID>`), maybe there's an issue with passing the auth credentials?

**Comment by michielrensen** [comment]
Extra info from the request:
```
GET /v1-catalog/templates/ecom:cluster:0 HTTP/1.1
Host: <HOSTNAME>
User-Agent: Go-http-client/1.1
Accept-Encoding: gzip
```

**Comment by michielrensen** [comment]
Final piece of information I could dig up was: https://github.com/rancher/cli/blob/master/cmd/catalog.go#L321

**Comment by deniseschannon** [comment]
We don't allow installing based on names. Only IDs.

I've created a PR to update the help for `rancher catalog install`

**Comment by michielrensen** [comment]
@deniseschannon well it does work except for the authentication part that is. In any case, I made a PR for that, how does it further?

**Comment by kapaggar** [comment]
same 401 response is coming when trying to install from rancher-cli (Version: v0.4.1)
` rancher catalog install private/app:0.0.1 --name stack_name -a answers.txt `
`FATA[0000] Bad response 401 looking up https://rancher.wizeapps.io/v1-catalog/templates/private:app:0 `
