### ISSUE TITLE
Not able to create containers with volumes in rancher-nfs without having to set nfs version.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#7186]
Rancher sever version - v1.2.2-rc2

Setup has Ubuntu 16.04.1 LTS (4.4.0) with docker 1.12.5 
On cattle environment , deploy rancher-nfs (rancher/storage-nfs:v0.6.0)

Create a service volume in  rancher-nfs.

Container fails to start with the following exception:
``` Activating (Expected state running but got error: Error response from daemon: VolumeDriver.Mount: Failed mount 104.236.204.123:/var/nfs1/hello1 /var/lib/rancher/volumes/rancher-nfs/hello1: Running in chroot, ignoring request. mount.nfs: rpc.statd is not running but is required for remote locking. mount.nfs: Either use '-o nolock' to keep locks local, or start statd. mount.nfs: mounting 104.236.204.123:/var/nfs1/hello1 failed, reason given by server: No such file or directory)```

Seems like we defaulted to nfsv3 client.

To workaroud the issue , I had to manually set ```MOUNT_OPTS: nfsvers=4``` when deploying rancher-nfs.

**Comment by LLParse** [comment]
Since our containerized nfsv3 client didn't work, we dropped support for it. Since that is the case, we need to hard-code the `nfsvers=4` parameter to ensure we never attempt an nfsv3 mount.

**Comment by LLParse** [comment]
Fix in v1.3.0-rc3 branch of rancher-catalog

Please also test setting nfsvers=3 in mount options, and observe that the value is ignored.

**Comment by sangeethah** [comment]
Tested with v1.3.0-rc3 branch of rancher-catalog using rancher-server - v1.3.0-rc2.
nfsversion needs to be explicitly set now (can only be set to 4 now) and is a required parameter.

**Comment by doreplado** [comment]
Has anyone seen this post 1.3 ? I'm seeing this exact behavior in 1.3.2 using rancher-nfs. Just curious if there was a possible regression.

**Comment by doreplado** [comment]
disregard, I figured out what needs to be done.
