### ISSUE TITLE
Single Rancher Node Unable to Use External DB

### ISSUE THREAD

**Issue by ptarpan** [rancher/rancher#7188]
**Rancher Version:**
1.1.4
**Docker Version:**
1.12.5
**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04 Xenial 
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher with external DB (MySQL 5.6.xx on AWS RDS)
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
Launch a single rancher/server with the versions above and MySQL RDS instance in AWS. The rancher/server container config is as follows: 
docker run -d --restart=always -p 8080:8080 rancher/server:v1.1.4 <<EOF
-e CATTLE_DB_CATTLE_MYSQL_HOST=<rds_hostname>
-e CATTLE_DB_CATTLE_MYSQL_PORT=3306
-e CATTLE_DB_CATTLE_MYSQL_NAME=cattle
-e CATTLE_DB_CATTLE_USERNAME=<db_user>
-e CATTLE_DB_CATTLE_PASSWORD=<db_password>
EOF 
**Results:** 
Rancher server uses internal DB. Cross referenced/confirmed that no connections have been established on RDS (even though the container starts as expected) and the HA Rancher UI page shows that HA is not configured. 
**Expected:**
RDS should show the rancher/server connection when the "show processlist" query is ran.

**Comment by vincent99** [comment]
`-e` has to go before the image name for environment variables.  You're passing a bunch of arguments that mean nothing to the server container.

**Comment by deniseschannon** [comment]
Please follow the guide on how to set up HA. Note that how we set up an external DB has changed. 


http://docs.rancher.com/rancher/v1.2/en/installing-rancher/installing-server/#multi-nodes

**Comment by vincent99** [comment]
@deniseschannon ..but they're doing 1.1.4, so http://docs.rancher.com/rancher/v1.1/en/installing-rancher/installing-server/#using-an-external-database .

**Comment by ptarpan** [comment]
Thanks @vincent99. That was the trick. The next steps are to add three (rancher/server) nodes in an HA cluster. I am in the process of generating the HA script. My question is: Can the HA config script use "http" instead of "https" for the host registration URL? If so, where should this setting be changed/applied. The host registration URL in the rancher UI is already pointing to the load-balancer (http://< fqdn_name>).
