### ISSUE TITLE
volumestoragepoolmap.remove issue still happening on v1.2.2

### ISSUE THREAD

**Issue by pulberg** [rancher/rancher#7194]
**Rancher Version:**
v1.2.2
rancher/lb-service-haproxy:v0.4.6
rancher/healthcheck:v0.1.0       
httpd:latest                     
meltwater/docker-cleanup:1.8.0   
rancher/healthcheck:v0.1.0       
rancher/net:v0.7.5               
rancher/net:v0.7.5               
rancher/dns:v0.11.0              
rancher/metadata:v0.6.8          
rancher/network-manager:v0.2.19  
rancher/agent:v1.1.2             
rancher/agent:v1.1.2
**Docker Version:**
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:
 OS/Arch:      linux/amd64
**OS and where are the hosts located? (cloud, bare metal, etc):**
RHEL7.2, vmware ESX
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node, separate mysqld on Rancher server
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
Add hosts, create a stack with a service with and LB, add scheduling rule to run on hosts with specific label (httpd in this case).  
**Results:** 
After a few minutes, observe the healthcheck and stack LB have restarted, view the "Processes" list and find entries for volumestoragepoolmap.remove with and "exit reason" of "unknown exception" and viewing container info on the host reveals dead containers - 

```
docker ps -a | grep rancher | grep Dead
d8feddc5911a    rancher/healthcheck:v0.1.0     "/.r/r /tini -- healt"   32 minutes ago      Dead   r-healthcheck-healthcheck-2-0ae1e3b7
```

![screen shot 2016-12-23 at 3 06 19 pm](https://cloud.githubusercontent.com/assets/11069351/21462392/70b64822-c921-11e6-999b-f8854b6aeee4.png)

**Expected:**
containers are removed

**Comment by pulberg** [comment]
**Update**  I forgot to add that I added the "Janitor" catalog item.  I have since removed Janitor and the errors are clearing, I'll keep monitoring for changes.

**Comment by pulberg** [comment]
**Update 2 **  Looks like it is the Janitor catalog item that is causing this issue.

**Comment by ibuildthecloud** [comment]
@pulberg anything that has `/var/lib/docker` as a volume is going to cause dead containers and hang things up.  We are trying to see if we can mitigate this but it's really more of a upstream Docker issue.
