### ISSUE TITLE
Agent fails to re-connect after moving server to new domain

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#7195]
**Rancher Version:**
v1.2.2

**Steps to Reproduce:**
1. Setup Rancher server with the host registration URL `http://domain-foo:8080` and enable authentication.
2. Add custom host
3. Migrate DB to new rancher server instance and change the host registration URL to `https://domain-bar`.
3. Setup a reverse proxy in front of the new server that redirects requests to `http://domain-foo:8080` to `https://domain-bar` using HTTP 301.

**Results:** 
`ERROR: Credentials are no longer valid, please re-register this agent`

**Expected:**
Rancher agent should follow HTTP redirects for the server URL

The first issue here is that the run_bootstrap() function in the agent run.sh script is missing `-L` flag to follow redirect. There was a previous (but obviously incomplete) attempt to fix this in https://github.com/rancher/rancher/pull/4064.

But even after enabling redirects in curl the command fails to authenticate to the new server using the previous registration URL:

```
# curl -i -L -u <KEY>:<SECRET> http://domain-foo:8080/v1                      
HTTP/1.1 301 Moved Permanently
Content-length: 0
Location: https://domain-bar/v1
Connection: close

HTTP/1.1 401 Unauthorized
Content-Type: application/json; charset=utf-8
Date: Fri, 23 Dec 2016 23:37:36 GMT
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Server: Jetty(9.2.11.v20150529)
Set-Cookie: PL=rancher;Path=/
Www-Authenticate: Basic realm="Enter API access key and secret key as username and password"
X-Api-Schemas: https://domain-bar/v1/schemas
Content-Length: 177

{"id":"93c259cb-c091-4b76-b8d0-535de0eea8d0","type":"error","links":{},"actions":{},"status":401,"code":"Unauthorized","message":"Unauthorized","detail":null,"baseType":"error"}#

```

But when using the new registration URL the agent authenticates successfully:

```
# curl -i -L -u  <KEY>:<SECRET> https://domain-bar/v1/schemas/configcontent
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Date: Fri, 23 Dec 2016 23:31:10 GMT
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Server: Jetty(9.2.11.v20150529)
Set-Cookie: PL=rancher;Path=/
Vary: Accept-Encoding, User-Agent
X-Api-Account-Id: 1a7
X-Api-Client-Ip: 104.238.133.64
X-Api-Schemas: https://domain-bar/v1/schemas
Content-Length: 687

{"id":"configContent","type":"schema","links" ...
```

**Comment by vincent99** [comment]
@janeczku you'd have to use `--location-trusted` instead of `-L` if your want the Authorization header you be sent to the followed locations.

**Comment by janeczku** [comment]
@vincent99 Good find!

**Comment by janeczku** [comment]
The Go HTTP client too strips authentication headers when following redirects which means that at least some of the infrastructure services won't probably work with a Cattle URL that is redirected.

**Comment by vincent99** [comment]
It's also not going to be really remembered because the agent container has the old URL in the command and will go through redirects again on restart.  So that redirect effectively has to be supported in DNS and something to respond to it forever.

So I'm not really convinced supporting following redirects to indirectly change the registration URL is a really great idea in the first place...

**Comment by deniseschannon** [comment]
No longer needed.
