### ISSUE TITLE
Wireguard for inter rancher comms?

### ISSUE THREAD

**Issue by SoreGums** [rancher/rancher#7196]
https://www.wireguard.io/performance/

Currently IPSec is used for secure rancher to rancher managed containers networking, maybe performance could be increased with wireguard?

FYI :)

**Comment by vincent99** [comment]
> Warning: WireGuard is currently under heavy development, and therefore any installation steps here should be considered as experimental. Please do not rely on WireGuard at this stage

**Comment by vincent99** [comment]
They don't actually seen to say what IPSec server they're even benchmarking...

Anyway, you can implement this as a CNI plugin and put it in the catalog if you are interested, the networking implementation is pluggable add of 1.2.
