### ISSUE TITLE
Exiting go-machine-service: Timed out waiting for transtion."

### ISSUE THREAD

**Issue by jwhitcraft** [rancher/rancher#7197]
**Rancher Version:** 1.2.1
**Docker Version:** 1.12.3
**OS and where are the hosts located? (cloud, bare metal, etc):** AWS EC2 behind an ALB
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** Single Node, RDS
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

I tried removing old hosts today and they have been in a removing state for a while,  now all i get is this in the rancher logs

```
time="2016-12-24T15:19:04Z" level=info msg="Setting log level" logLevel=info
time="2016-12-24T15:19:04Z" level=info msg="Starting go-machine-service..." gitcommit=v0.34.1
time="2016-12-24T15:19:04Z" level=info msg="Waiting for handler registration (1/2)"
time="2016-12-24T15:19:12Z" level=fatal msg="Unable to start event router" error="Timed out waiting for transtion."
time="2016-12-24T15:19:14Z" level=info msg="Starting rancher-compose-executor" version=v0.12.1
time="2016-12-24T15:19:15Z" level=fatal msg="Exiting go-machine-service: Timed out waiting for transtion."
2016/12/24 15:19:15 http: proxy error: net/http: request canceled
```

Even after a restart that is all i see.

**Comment by jwhitcraft** [comment]
While this may be related to this, https://github.com/rancher/rancher/issues/6753  Mine are both in the same VPC with the RDS instance is in us-east-1c subnet and my and my instance is in use-east-1b subnet.

**Comment by aemneina** [comment]
go-machine has gone through quite a bit of improvements since rancher 1.2.1. This should since have been resolved. Going to close this out, please open a new issue if there are any further issues found
