### ISSUE TITLE
Feature request: UI experience improvements

### ISSUE THREAD

**Issue by yeta-io** [rancher/rancher#7199]
Hi, 

I spent a week for configuring rancher with all docker instances and wiring between them. So there I want to share my experience with UI.

I'd like to have an option to configure how the container actions should be presented - as list in menu or as buttons. Every time when I needed to see logs or run shell to debug container I have to click on ... button, then choose appropriate action.

![untitled](https://cloud.githubusercontent.com/assets/23072552/21471161/cccb8cae-cab0-11e6-9a1d-2268da571071.png)

When you do it once at month its - ok, but when you have to setup whole datacenter from scratch its very annoying and waste my time for unnecessary clicking. We have a lot of space near menu button, where possible to fit all the action buttons - execute shell, see logs, reload, etc...

**Comment by vincent99** [comment]
We've tried this all sorts of ways  before in older versions with all, several common, and one most likely actions and none of them have really worked will.  2.0 has just the `[:]`all the time and generally more useful rows.  Also bulk actions where applicable (I.e. restart/stop/delete, not exec).
