### ISSUE TITLE
Feature request: Download before stopping

### ISSUE THREAD

**Issue by chauffer** [rancher/rancher#7200]
New images can sometimes take a long time to download, especially when none of the layers are cached.

During a normal upgrade:
Stop old container -> pull container image -> start new container

Start before stop:
pull container image -> start new container -> stop old container

Download before stopping:
pull container image -> stop old container -> start new container

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
