### ISSUE TITLE
Can't add container in Russian lang on ui

### ISSUE THREAD

**Issue by Negashev** [rancher/rancher#7202]
**Rancher Version:** 1.2.0 - 1.2.2

**Docker Version:** N/A

**OS and where are the hosts located? (cloud, bare metal, etc):** N/A

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** N/A

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:** I select russian lang

**Results:** can't add container on host

**Expected:**

you can see console log in my browser on this [Uncaught Error: A value must be provided for: имя](https://drive.google.com/file/d/0B6IiVIx2WQdeTFBHaldKQUlKOGc/view)

**Comment by tfiduccia** [comment]
Version - master 12/27
Checked and this is indeed a problem.  I can add a service but I can't add a stand-alone container in Russian.  English and other languages are fine.

**Comment by tfiduccia** [comment]
Version - v1.3.0-rc2
Verified fixed
