### ISSUE TITLE
After Rancher upgrade containers don't have 10.42.x.x address assigned

### ISSUE THREAD

**Issue by beatcracker** [rancher/rancher#7203]
### Details
- Rancher Version: **v1.2.2** (upgrade from 1.1.4)
- Docker Version: **Docker version 1.12.5, build 7392c3b**
- OS and where are the hosts located: **CentOS Linux release 7.2.1511 (Core), 4.9.0-1.el7.elrepo.x86_64, Google Compute Engine VM**
- Setup Details: **Single Rancher node with one host, external MySQL DB**
- Environment Type: **Cattle**
### Steps to Reproduce

1. Install Rancher 1.1.4
2. Add host
3. Create service (use `Managed` network)
4. Upgrade Rancher to 1.2.2
5. Upgrade host
6. Verify that Rancher reports `10.42.x.x` IP for the containers in UI.

### Results
Although Rancher reports that container has `10.42.x.x IP` assigned, the container itself doesn't respond to `ping` and load balancer can't access container.

Here is network info from affected container:

```shell
docker exec -it  r-xxx_yyy_1_a1b2c3de ifconfig
eth0      Link encap:Ethernet  HWaddr 02:AA:2D:5B:74:B2
          inet addr:172.17.0.5  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::aa:2dff:fe5b:74b2%32626/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:5 errors:0 dropped:0 overruns:0 frame:0
          TX packets:18 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:418 (418.0 B)  TX bytes:1328 (1.2 KiB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1%32626/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
```
### Expected
Container should have 10.42.x.x IP assigned.

### Additional details

Restarting container doesn't help. Containers in newly created services work fine. Upgrading service twice in a row (Networking:  `Managed` -> `None` -> `Managed`) assigns correct IP address.

Network info from host:

```shell
ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1460 qdisc pfifo_fast state UP qlen 1000
    link/ether 42:01:0a:84:00:04 brd ff:ff:ff:ff:ff:ff
    inet 10.111.0.4/32 brd 10.111.0.4 scope global dynamic eth0
       valid_lft 48881sec preferred_lft 48881sec
3: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP
    link/ether 02:42:41:75:cc:00 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 scope global docker0
       valid_lft forever preferred_lft forever
    inet 10.42.0.1/16 scope global docker0
       valid_lft forever preferred_lft forever
```

**Comment by pwFoo** [comment]
upgrade to 1.2 breaks my docker-gen based web loadbalancer because of missing ip address :(
```
"IPAddress": "",
```

I hope it will be fixed soon?

**Comment by beatcracker** [comment]
FYI: I'm still keeping one affected container in case you need me to get some debug info from it.

**Comment by pwFoo** [comment]
A fix would be needed to use it because my custom loadbalancer is broken after upgrade and the rancher lb with lets encrypt delivers the wrong certificate after container upgrade (#7346).

**Comment by aemneina** [comment]
This should have been resolved in subsequent network-services and ipsec fixes. Closing, please file a new issue if there are any issues encountered.
