### ISSUE TITLE
network-services-metadata start fails with Cert signed by Company CA

### ISSUE THREAD

**Issue by HenryTheSir** [rancher/rancher#7206]
**Rancher Version:**
1.2.2 with rancher/metadata:v0.6.8 and rancher/network-manager:v0.2.19
**Docker Version:**
1.12.5
**OS and where are the hosts located? (cloud, bare metal, etc):**
VMware - Ubuntu 16.04.01
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node Rancher with External DB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle 
**Steps to Reproduce:**
Deploy Rancher Server behind nginx SSL Frontend and connect agents via https to rancher-server. The agent itself comes up without any problems, but the network-services-metadata container fails with SSL Cert not trusted every 2 minutes. (The volume with the CA Cert is mapped to the network-services-metadata container (checked in the rancher GUI)
**Results:** 
Container does not come up and migration fails until the rancher-agent connection is downgraded to http only. network-services-metadata container now starts without problem and migration works fine and all Stacks come up.
**Expected:**
Container starts without problem and connects to rancher-server via SSL and trusts company root CA.

**Comment by HenryTheSir** [comment]
Is probably a duplicate of  #6122 
Can someone update the documentation?
http://docs.rancher.com/rancher/v1.2/en/installing-rancher/installing-server/basic-ssl-config/

**Comment by deniseschannon** [comment]
@HenryTheSir Yes, self signed certs are known issue right now for 1.2.x. This is now fixed in v1.3.0.

We have updated the documentation.
