### ISSUE TITLE
Cannot add host in AWS Ohio region us-east-2

### ISSUE THREAD

**Issue by nassifnassif** [rancher/rancher#7208]
**Rancher Version:1.2.2**

**Docker Version:1.12.5**

**OS and where are the hosts located? (cloud, bare metal, etc): AWS linux.amd64 Ubuntu 16.04.1 LTS (GNU/Linux 4.4.0-57-generic x86_64)**

**Setup Details: single node rancher **

**Environment Type: Kubernetes**

**Steps to Reproduce: add host, select AWS, enter AWs keys, select vopc, secgrp,.... once I hit create I'm getting the following error: Error setting machine configuration from flags provided: Invalid region specified**

Detailed log:
time="2016-12-28T15:29:37Z" level=info msg="Cmd slice: [create -d amazonec2 --engine-install-url https://get.docker.com --amazonec2-access-key XXXXXXXXXXXX --amazonec2-device-name /dev/sda1 --amazonec2-instance-type t2.micro --amazonec2-region us-east-2 --amazonec2-retries 5 --amazonec2-root-size 16 --amazonec2-secret-key XXXXXXXXXXXXXXXXXXXl --amazonec2-security-group rancher-machine --amazonec2-spot-price 0.50 --amazonec2-ssh-user ubuntu --amazonec2-subnet-id subnet-8d5cb6f6 --amazonec2-volume-type gp2 --amazonec2-vpc-id vpc-bd16dcd4 --amazonec2-zone b host02]"
time="2016-12-28T15:29:37Z" level=info msg="stderr: Error setting machine configuration from flags provided: Invalid region specified" resourceId=1ph2
time="2016-12-28T15:29:37Z" level=info msg="starting cleanup..." machine name=host02
time="2016-12-28T15:29:37Z" level=error msg="Error processing event" err="Error setting machine configuration from flags provided: Invalid region specified" eventId=ca95f6d3-1aec-4324-bef1-f4d223a563cf eventName="physicalhost.create;handler=goMachineService" resourceId=1ph2

**Comment by vincent99** [comment]
The list of regions docker-machine supports is hardcoded into the release, which is then packaged into a Rancher release.  https://github.com/rancher/rancher/issues/7071
