### ISSUE TITLE
rancher-compose up --pull should update the images to the latest version in the registry

### ISSUE THREAD

**Issue by urbany** [rancher/rancher#7209]
**Rancher Version:**
v1.2.2

**Docker Version:**
Docker version 1.12.5, build 7392c3b

** Rancher Compose Version:**
rancher-compose version v0.12.1

**OS and where are the hosts located? (cloud, bare metal, etc):**
Rancher-Server: Ubuntu 14.04.5 @ Linode
Services-Server: Ubuntu 14.04.5 @ Linode

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
`rancher-compose up --force-upgrade --pull --confirm-upgrade -d`

**Private Registry:**
Provided by latest version of Gitlab-CE

**Results:** 
```
INFO[0000] [0/2] [appointments]: Creating               
INFO[0000] [0/2] [appointments]: Created                
INFO[0000] [0/2] [bundle-appointments]: Creating        
INFO[0000] [0/2] [bundle-appointments]: Created         
INFO[0000] [0/2] [appointments]: Starting               
INFO[0001] Finished pulling registry.xxxxx.com/yyyyy/zzzzz:staging
INFO[0001] Finished pulling busybox                     
INFO[0002] Updating appointments                        
INFO[0024] Upgrading appointments                       
INFO[0045] [1/2] [appointments]: Started                
INFO[0045] [1/2] [bundle-appointments]: Starting        
INFO[0045] [2/2] [bundle-appointments]: Started         
````
Everything working but registry.xxxxx.com/yyyyy/zzzzz:staging is not updated

**Expected:**
Although it says `Finished pulling registry.xxxxx.com/yyyyy/zzzzz:staging` it does not update the image. In rancher v1.4 when using the --pull option the images were updated if the cached version is different from the registry version.
`rancher-compose pull`doesn't work either, the only way I managed to update the image to the latest version in the registry is to go to my host machine where the containers run and `docker rmi registry.xxxxx.com/yyyyy/zzzzz:staging` or `docker images pull registry.xxxxx.com/yyyyy/zzzzz:staging`and then doing `rancher-compose up --force-upgrade --pull --confirm-upgrade -d`

If I upgrade though the rancher UI selecting `Always pull image before creating` correctly updates the image to the latest version.

**Comment by guzmo** [comment]
Same issue

**Comment by chessracer** [comment]
+1 
Major problem for us - have spent considerable time since our Rancher v1.2.x update chasing down issues related to not actually having the containers upgraded as expected.

**Comment by chessracer** [comment]
I've been able to workaround this for now by adding `labels:
    io.rancher.container.pull_image: always
`
to each service definition in my docker-compose.yml file(s)

**Comment by rstuven** [comment]
I got the same issue using Rancher CLI. 

Apparently, the agent is pulling the image only when creating the container. If the container already exists, the agent won't pull anything (see [here](https://github.com/rancher/agent/blob/b5a565c66a1dd8a0da5b447574293f642c0217c1/core/compute/compute.go#L107) and [here](https://github.com/rancher/agent/blob/b5a565c66a1dd8a0da5b447574293f642c0217c1/core/compute/compute_common.go#L37) and their context in the source code of the agent), which is not the behavior I would expect when using the option `--pull` (especially with `--upgrade`, even if the compose files have no changes).

**Comment by urbany** [comment]
@rstuven I agree with you, if --pull is used the image should be pulled, event if it already exists.
@chessracer thanks for that workaround, it works! Where did you find it? I looked for how to set that  option on the YAML but couldn't find the correct label name.

**Comment by chessracer** [comment]
@urbany since upgrade through the UI worked, I looked at the API call for that, and found the io.rancher.container.pull_image: always label in there.

**Comment by danielpalstra** [comment]
I did not run in to this issue when using Rancher 1.3.3.

**Comment by rstuven** [comment]
Still having the issue in 1.3.3.

**Comment by mKeRix** [comment]
Making Rancher always pull images works for now, but I dislike having to set the option. I deploy everything using Gitlab CI and therefor I want to control exactly when new images are pulled and when using the cache is fine.

I don't think ignoring the `--pull` option and using the cache anyway is the intended behavior. And if it is I vote for a `--force-pull` option of some sort that upgrades with the newest registry image!

**Comment by ryudice** [comment]
Any plans to fix this? it's breaking our whole CI environment, and we have to do manual work to fix the issue.

**Comment by Sebisnow** [comment]
In which rancher-compose version will this bugfix be available so that the --pull actually pulls the newer images?

RancherOS v0.9.1 (4.9.18) 
docker version 1.12.6
rancher-compose version v0.12.4

```
$ rancher-compose -f deploy/docker-compose.yml -p test_suite up --pull --force-recreate -c --interval 5000
INFO[0000] [0/1] [test]: Creating                       
INFO[0000] [0/1] [test]: Created                        
INFO[0000] [0/1] [test]: Starting                       
INFO[0001] Finished pulling example.com/project/test_suite 
INFO[0002] Updating test                                
INFO[0002] Upgrading test                               
INFO[0016] [1/1] [test]: Started

```

Even though it says it finished pulling the image it did not pull at all.

**Comment by imikushin** [comment]
Still an issue. Reproduced w/ both `rancher-compose` and `rancher` CLI:

```
rancher-compose up --force-upgrade --pull --confirm-upgrade -d
```
and
```
rancher up --pull --upgrade --force-upgrade --confirm-upgrade -d
```
both do not pull the image.

**Comment by imikushin** [comment]
@StrongMonkey ^^
Rancher v1.6.0-rc1

**Comment by StrongMonkey** [comment]
The problem is that when using a customized registry, the server name is not passed in instance.pull.(that will cause a failed pull so image is not updated). https://github.com/rancher/agent/pull/165 should address it.

**Comment by StrongMonkey** [comment]
@imikushin Can you plz re-test this? the fix should be in cattle master now.

**Comment by imikushin** [comment]
Checked w/ Rancher v1.6.0-rc4: the fix seems to work!

**Comment by scomma** [comment]
Does anyone know if this is supposed to work in the new "rancher" CLI as well? I'm still getting the old "up" behavior (i.e. no re-pulling despite pull_image: always)

**Comment by deniseschannon** [comment]
Yes, this should work with CLI. What version of CLI are you using and Rancher version?

**Comment by phlegx** [comment]
@StrongMonkey @deniseschannon To me this is still not working correctly with rancher cli 6.2.1 and a private repository.

```rancher -f stacks/example_stack/docker-compose.yml up -d --upgrade --pull example-service```

Sometimes works and sometimes not. It seems to be related to the flag 

``` io.rancher.container.pull_image: always```

When I disable it in my docker-compose file then it works. But the second time with a newer image again it does not work anymore. Only when I comment it in again it pulls the image.  The third time it does not pull again. Only when I comment it out again and so forth.

**Comment by StrongMonkey** [comment]
@phlegx Thanks for reporting this. I will test your cases.

**Comment by rstuven** [comment]
@phlegx @StrongMonkey @deniseschannon In a [previous comment](https://github.com/rancher/rancher/issues/7209#issuecomment-269748115), I pointed out a possible source of the issue.

**Comment by StrongMonkey** [comment]
@phlegx Have you ever tried with `--force-upgrade` option? AFAIK `--upgrade` will only work only if the service has [changed.()](http://rancher.com/docs/rancher/v1.6/en/cli/commands/#rancher-up-reference). Also in the agent log there should be something related to pulling images.

**Comment by phlegx** [comment]
@StrongMonkey yes a `--force-upgrade` does work indeed I tried it today. However this is not a solution to the problem I think since `--pull` should always do pull it, the wiki states; `Before doing the upgrade do an image pull on all hosts that have the image already`. So I thought that a new image would be indeed a `service change`.

Tomorrow I'll check the service logs and then post here what I have found.

**Comment by joshwget** [comment]
Those following this issue should probably be aware of #5516. Services will upgrade _only_ if something in their Compose definition has changed.

**Comment by phlegx** [comment]
@joshwget Hmm ok I see. How to update then the service when an image has changed? Is there a strategy with `rancher cli` resp. `rancher-compose` as well? Should one use `--force-upgrade` as @StrongMonkey suggested?

**Comment by akaipham** [comment]
Any updates on this issue guys ? It's still not working for me with Rancher-CLI via my command:
~~~
rancher-compose --url <> \
            --access-key <> \
            --secret-key <> --verbose \
            -p <> \
            up --force-upgrade --pull --confirm-upgrade -d
~~~
My current version:
~~~
Docker version 17.03.0-ce, build 60ccb22
docker-compose version 1.12.0, build b31ff33
rancher version v0.6.2
rancher-compose version v0.12.5
~~~
