### ISSUE TITLE
Can't get a service to go to 0 using webhook

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#7211]
**Rancher Version:** master 12/28

**Steps to Reproduce:**
1.  Create a service with a scale of 2
2.  Create a webhook to that service that will scale down 2
3.  Run the webhook
4.  Go to service and edit

**Results:** Nothing happened

**Expected:** Should allow a service to scale to 0, just not below 0.

**Comment by vincent99** [comment]
I think this should stop at 1 and not let you go down to 0 either.. Accidentally calling the hook too many times will cause your service to not be running at all.

**Comment by cjellick** [comment]
Hm. I can see both sides of this argument. Not sure what to do.
@mrajashree can you start by figuring out why you cannot scale to zero?
Then, fix it so that you can scale to zero. In the meantime, we'll think about what the right behavior should be.

**Comment by cjellick** [comment]
@mrajashree I mean put in the fix so that it scales to zero and we'll take it from there.

**Comment by mrajashree** [comment]
Since we have minimum value 1 now, can I close this?

**Comment by tfiduccia** [comment]
Version - master 1/17
Verified fixed and negative numbers also not allowed.
