### ISSUE TITLE
Name for webhooks should be unique

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#7213]
**Rancher Version:** master 12/26

**Steps to Reproduce:**
1.  Create a webhook
2.  Create another one with same name

**Results:** Can create two webhooks with same name

**Expected:** Should not be able to create webhooks with same name.

**Comment by cjellick** [comment]
I disagree. The name is arbitrary, users should be able to input whatever they want. We only enforce name uniqueness when it impacts how how rancher behaves, ie we use the stack name effectively as a namespace in rancher and _need_ it to be unique but we allow containers to have duplicate names.

**Comment by cjellick** [comment]
Was conviced by @tfiduccia and @vincent99 that name should be unique. Let's do it.

**Comment by tfiduccia** [comment]
Version - master 1/17
Verified fixed
