### ISSUE TITLE
UI Issues with webhooks

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#7215]
**Rancher Version:** master 12/26

**Steps to Reproduce:**

- [ ] Trigger URL sorting makes no sense
- [ ] Detail sorting text should say Service, since it's actually sorting on service not on the exact details (like Scale up, Scale down text)
- [ ] Is there any other state besides Active?  Do we even need this?
- [ ] Scale goes up to 11 instead of an even number like 10?  Is that cause it's 1 louder?
- [ ] Service link in Details column goes to main Stack page, should go to that particular service's detail page.

**Comment by vincent99** [comment]
1. Removed
2. Also removed, this won't make sense when there's more than one kind
3. Yes, activating -> active -> removing -> removed.
4. ![image](https://cloud.githubusercontent.com/assets/753917/21532861/e990373c-cd11-11e6-8b8c-b5402cd81ea0.png)

5. Fixed

**Comment by tfiduccia** [comment]
Version - master 12/30
Verified fixed
