### ISSUE TITLE
If I'm in service detail and scale up, stats are throwing error and showing n/a

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#7216]
**Rancher Version:** master 12/26

**Steps to Reproduce:**
1.  Create a service
2.  Click on service to go to service detail page
3.  Click on menu in right corner and edit
4.  Increase scale and Save

**Results:** Stats for new container says n/a and Error is being thrown in dev tools - Uncaught TypeError: Cannot read property 'indexOf' of null

**Expected:**  Stats should show up and no Error.

**Comment by vincent99** [comment]
New container stats are not automatically sent, so the UI has to reconnect (and lose all the history) or the server needs to start sending the data for the new containers.

**Comment by vincent99** [comment]
Fixed  the error thought.

**Comment by tfiduccia** [comment]
Version - master 1/11
Verified fixed
