### ISSUE TITLE
Cleanup Kubernetes UI

### ISSUE THREAD

**Issue by sheng-liang** [rancher/rancher#7218]
As of 1.3, Rancher can show the native Kubernetes dashboard but it is not easy to find. In the next release we should do the following:

1. Remove Kubernetes namespaces tab
2. Remove Stacks, Deployments, Services, Replication Controllers, Replica Sets, and Pods from the Kubernetes tab
3. Add a new menu item called "Dashboard" into the Kubernetes tab, so the Kubernetes tab contains three items: Dashboard, kubectl, and Infrastructure Stacks.
4. Deploy heapster so graphs show up in Kubernetes UI.
5. The Catalog tab should go away since we support Helm/Tiller through CLI now. So in an Kubernetes environment, we'll only see four major tabs: Environments, Kubernetes, Infrastructure, and API.

**Comment by Dmitry1987** [comment]
@sheng-liang  omg, the "execute shell" and "logs" menus will be removed?
![image](https://cloud.githubusercontent.com/assets/9369080/21636907/35bc73fe-d26d-11e6-815e-d94485611c6a.png)
we will not be able to see pods from Rancher menu and inspect them with 'execute shell' ? :( 

I really like current menus, all pods/deployments/services pages are useful to quickly navigate from "service" for example into "which pods it points to", and quickly see its logs or ssh (in K8s dashboard things are different, and not everything is as good as in Rancher UI).  

Please consider leaving current UIs optional to those who like it?    

K8s dashboard is good, but not in all aspects. When both options available, it'll be a win win for all :)  (especially those who already got used to current Rancher UI with K8s environment)

**Comment by sheng-liang** [comment]
The Rancher infrastructure view will not be removed. Only the pod/replica set view will be removed as it is done better in native Kubernetes UI.

**Comment by weikinhuang** [comment]
Pod stats need `cadvisor` I think

**Comment by wlan0** [comment]
@weikinhuang context?

**Comment by weikinhuang** [comment]
Ah, gotcha, I tried running heapster/grafana/influxdb but couldn't get container (pod) stats working, I was only able to get node stats working. (Using Rancher 1.3.0/CoreOS/Kube 1.5.1)

**Comment by weikinhuang** [comment]
@wlan0 I just tried deploying your heapster add-on, same issue. I was only able to see node stats and not pod stats. The section that lists namespaces only show `default` and `kube-system`, and no pods within those namespaces are available.

**Comment by tfiduccia** [comment]
Version - master 1/11
All menu items are removed.  If you have other issues, please add separate bug.
