### ISSUE TITLE
unable to add a host in Rancher 1.2.2

### ISSUE THREAD

**Issue by hmeftah** [rancher/rancher#7222]
**Rancher Version:**  1.2.2

**Docker Version:**   1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):**  rancher os bare metal packet.net

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**  single node rancher, server on one host , try to add an other host , different ip address

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**    i guess it's the default one; cattle

**Steps to Reproduce:**  
Try to add a host and got 
 https://IP_ADDRESS/v1 is not accessible
in docker logs in the host machine 
enable iptable to udp 500 and 4500 
did a curl -k and got export command on display
Read lot of answers on this issue but I don't understand  how to fix it. 
That should be so simple but seems so complicated 

**Results:** 
failed 
**Expected:**
a registered host

**Comment by deniseschannon** [comment]
Is port 8080 accessible on the host that has your Rancher server? Ports 500 and 4500 are only required when you are expecting communication between the hosts in Rancher.

**Comment by JelleHissink** [comment]
Hi, I had the same issue when using the ip address. The https certificate was not valid for the url used to download.
There are a number of options:
* setup a correct certificate for rancher, also if self signed the agent-os should trust it
* -or- use http instead of https for the trafic from the agent

**Comment by superseb** [comment]
Thanks for reporting, see https://github.com/rancher/rancher/issues/7416
