### ISSUE TITLE
Not able to access Kubernetes Dashboard UI

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#7226]
Rancher server version - v1.3.0-rc2

Setup:
Kubernetes setup with 1host.
Try to access Kubernetes/Dashboard/"Kubernetes UI".
Directed to error page - 404 - ```The page you were looking for doesn't exist! ```

"/#" needs to be appended to the existing Url needs to append "/#"  . This url launches the Dashboard UI fine - ```http://<ip-address>:8080/r/projects/1a50/kubernetes-dashboard:9090/#```

**Comment by tfiduccia** [comment]
Version - master 12/30
Verified fixed
