### ISSUE TITLE
Do not show "Upgraded:Finish Upgrade" option when stack is stuck in "upgrading" state.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#7233]
Rancher Version: Build from master

Do not show "Upgraded:Finish Upgrade" option when stack is stuck in "upgrading" state.
<img width="1537" alt="screen shot 2016-12-30 at 10 50 22 am" src="https://cloud.githubusercontent.com/assets/4266958/21571322/fdc479f8-ce82-11e6-9af3-1c424a6604c7.png">

**Comment by vincent99** [comment]
This is not UI.. The stack says it's in state upgraded.
