### ISSUE TITLE
rancher storage drivers don't work with some older OSes

### ISSUE THREAD

**Issue by LLParse** [rancher/rancher#7237]
**Rancher Version:** 1.2.2

**Docker Version:** 1.11.2

**OS and where are the hosts located? (cloud, bare metal, etc):** Amazon Linux AMI 2016.09 (4.4.35)

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single node, internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** cattle

**Steps to Reproduce:**
1. Launch the Rancher EBS/EFS/NFS template

**Results:** 
time="2016-12-30T19:52:41Z" level=fatal msg="Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?"

**Expected:**
Plugin can communicate with the Docker daemon

This was reported in the [forums](https://forums.rancher.com/t/neither-rancher-nfs-nor-rancher-efs-will-successfully-spin-up/4921)

**Comment by LLParse** [comment]
Available in v1.3.0-rc3 branch of rancher-catalog

**Comment by sangeethah** [comment]
For NFS , nfs version needs to be explicitly set now (can only be set to 4 now) and is a required parameter which was verified as part of closing - https://github.com/rancher/rancher/issues/7186

**Comment by galal-hussein** [comment]
Rancher: v1.4.0-rc3
OS: Amazon Linux AMI 2016.09

I verified that (NFS/EFS/EBS) plugins can communicate with Docker daemon, the services started up successfully.
