### ISSUE TITLE
yaml that has no port info for LB changing LB to service

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#7239]
**Rancher Version:** v1.3.0-rc3

**Steps to Reproduce:**
1.  import docker/rancher yml that has a service and a lb (have the lb have no port info)

**Results:** The Load Balancer is changed into a regular service.
![image](https://cloud.githubusercontent.com/assets/11514927/21574583/c4ed2ab4-ceb2-11e6-9403-3254877ba775.png)

**Expected:**  Should still be Load balancer

**Comments:** Imported yml in 1.2.0 works properly.
[docker-compose.txt](https://github.com/rancher/rancher/files/679374/docker-compose.txt)
[rancher-compose.txt](https://github.com/rancher/rancher/files/679373/rancher-compose.txt)

**Comment by joshwget** [comment]
I'm not sure how I'd distinguish between a standard service and load balancer in this case. Standard services can have an `lb_config` for target ports so its presence isn't enough to make it a load balancer service.

cc @alena1108 @deniseschannon
