### ISSUE TITLE
[API] Container environment field doesnt properly support valueless entries

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#724]
The docker api/cli allows for env vars like this: `-e FOO` (as opposed to -e FOO="").
In the docker inspect, such a var will look like this `'FOO'` (as opposed to `'FOO='`).

The rancher api does not allow for this functionality. The closest we can get is a variable with a blank string as a value.

Its worth noting that a valueless environment variable does not show up inside a container when you run the printenv command.

**Comment by vincent99** [comment]
The valueless `-e FOO` takes the current value of `$FOO` from the host you're running `docker run` on.  So what would that mean to us... take the value of a variable on the host we happen to have scheduled the container on to?

**Comment by deniseschannon** [comment]
@cjellick @vincent99 is this fixed and can be closed? do you still need something answered @vincent99?

**Comment by vincent99** [comment]
I believe it's still relevant, we can talk about what valueless keys should do.
