### ISSUE TITLE
rancher_efs support using the same volume_name in different environments

### ISSUE THREAD

**Issue by hanboo** [rancher/rancher#7247]
**Rancher Version:** v1.2.2

**Docker Version:** 1.12.5

**OS and where are the hosts located? (cloud, bare metal, etc):** Amazon

**Setup Details:** single node rancher

**Environment Type:** Cattle

**Steps to Reproduce:** 
- create 2 environments
- deploy rancher EFS in each environment
- in environment 1: mount rancher-efs volume (test:/opt/test) for test container ubuntu
- in environment 2: mount rancher-efs volume (test:/opt/test) for test container ubuntu

**Results:** 
 (Failed to allocate instance [container:1i1097]: Bad instance [container:1i1097] in state [removed]: Could not process named volume test. More than one volume with that name exists.)
New EFS volume for environment 2 is NOT created

**Expected:**
new EFS volume created for environment 2. 
As Rancher-EFS is bound to the environment, I would expect Rancher to use the EFS file system ID (and not the name)

**Update:**
after some experimenting I suggest a solution to create an EFS file system for each environment and use the volume name as a directory on the EFS file system. I used convoy-efs that way and it worked fine. 
By replacing convoy-efs with rancher-efs I got the error mentioned above and I created too many EFS file systems, so got AWS errors: toomanyfilesystems

**Comment by hanboo** [comment]
**another solution**
Create an EFS file system for each environment instead of for each volume name

that way, volume name can be used as an EFS directory:
EFS ID/volume name/

**Comment by superseb** [comment]
We deprecated rancher-efs in favor of rancher-nfs since v1.6.6.
