### ISSUE TITLE
Can not assign IP Address

### ISSUE THREAD

**Issue by swarmier** [rancher/rancher#7248]
Hello,
   This is the first time I have had to do this, so it might be user error:  Trying to bind the port to a secondary IP ('10.32.100.102:80') and Rancher only insert's 10. The format in the container's portmap setting says [IP:]Port.   Only '10' gets saved in the port field, tried in Chrome and Safari.   From log:

Time 	Event Type 	Description 	Environment 	Resource Time:Id 	Identity 	Auth & IP
5 minutes ago	api.port.update 	None	Production	port: 1p48	
admin
None
10.32.200.3

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.1.4` Cattle: `v0.165.8.4` UI: `v1.1.14` |
|Access|`Disabled`|
|Orchestration|`Cattle`|
|Route|`container.ports`|

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
