### ISSUE TITLE
Within rancher-nfs driver, volumes are not assigned (random issue)

### ISSUE THREAD

**Issue by typia** [rancher/rancher#7249]
**Rancher Version:**
1.2.2
**Docker Version:**
1.12.3
**OS and where are the hosts located? (cloud, bare metal, etc):**
Debian 8
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node rancher external DB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
Sometimes rancher-nfs volumes are not assigned / created properly.
It's random.
On the same service I have 2  volumes, one assigned properly, the other is not ..
Please help me to give logs about it, nothing weird in rancher server logs.
**Results:** 
Volumes are not assigned
**Expected:**
Volumes assigned

**Comment by aemneina** [comment]
@typia are you still facing this issue?

**Comment by superseb** [comment]
We need some reproducible case, and logging from the rancher-nfs container would be helpful. Please file a new issue with this information.
