### ISSUE TITLE
Overlay Network: racoon not started not configured

### ISSUE THREAD

**Issue by xinity** [rancher/rancher#725]
using agent v0.6.4 and agent-instance v0.3.0 i have a strange log message: 
racoon - IKE keying daemon will not be started as /proc/net/pfkey is not
         available or a suitable 2.6 (or 2.4 with IPSEC backport)
         kernel with af_key.[k]o module installed.

the effect is racoon not started nor configured correctly :(

**Comment by ibuildthecloud** [comment]
What is your host environment ?  Can you share docker version/info output.  That message typically means your kernel doesn't have netkey/pf_key support.

**Comment by xinity** [comment]
nodes are based on latest core alpha vagrant

**Comment by ibuildthecloud** [comment]
Can you just try "modprobe af_key" on the host?  I'm not sure why that
module wouldn't load on it's own.  Can you run

    docker inspect rancher-agent | grep -vE 'KEY|URL'

and send the output?  I'll see if I can spin up a CoreOS vagrant cluster
and reproduce the issue.

Darren

**Comment by xinity** [comment]
here is it:
[{
    "AppArmorProfile": "",
    "Args": [
        "run"
    ],
    "Config": {
        "AttachStderr": false,
        "AttachStdin": false,
        "AttachStdout": false,
        "Cmd": [
            "run"
        ],
        "CpuShares": 0,
        "Cpuset": "",
        "Domainname": "",
        "Entrypoint": [
            "/run.sh"
        ],
        "Env": [
            "CATTLE_PHYSICAL_HOST_UUID=",
            "CATTLE_SCRIPT_DEBUG=",
            "CATTLE_AGENT_IP=172.17.8.102",
            "CATTLE_HOST_API_PROXY=",
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "RANCHER_AGENT_IMAGE=rancher/agent:v0.6.1"
        ],
        "ExposedPorts": null,
        "Hostname": "core-02",
        "Image": "rancher/agent:v0.6.1",
        "Labels": {},
        "MacAddress": "",
        "Memory": 0,
        "MemorySwap": 0,
        "NetworkDisabled": false,
        "OnBuild": null,
        "OpenStdin": false,
        "PortSpecs": null,
        "StdinOnce": false,
        "Tty": false,
        "User": "",
        "Volumes": null,
        "WorkingDir": ""
    },
    "Created": "2015-05-06T14:10:06.105800074Z",
    "Driver": "overlay",
    "ExecDriver": "native-0.2",
    "ExecIDs": null,
    "HostConfig": {
        "Binds": [
            "/lib/modules:/lib/modules:ro",
            "/var/lib/docker:/var/lib/docker",
            "/proc:/host/proc",
            "/var/run/docker.sock:/var/run/docker.sock"
        ],
        "CapAdd": null,
        "CapDrop": null,
        "CgroupParent": "",
        "ContainerIDFile": "",
        "CpuShares": 0,
        "CpusetCpus": "",
        "Devices": [],
        "Dns": null,
        "DnsSearch": null,
        "ExtraHosts": null,
        "IpcMode": "",
        "Links": null,
        "LogConfig": {
            "Config": null,
            "Type": "json-file"
        },
        "LxcConf": [],
        "Memory": 0,
        "MemorySwap": 0,
        "NetworkMode": "host",
        "PidMode": "host",
        "PortBindings": {},
        "Privileged": true,
        "PublishAllPorts": false,
        "ReadonlyRootfs": false,
        "RestartPolicy": {
            "MaximumRetryCount": 0,
            "Name": "always"
        },
        "SecurityOpt": null,
        "Ulimits": null,
        "VolumesFrom": [
            "rancher-agent-state"
        ]
    },
    "HostnamePath": "/var/lib/docker/containers/950e0a53dab1c8c8bea6f6ede7d8d6186d2c0fc05b61398bb37141695e5f9d1d/hostname",
    "HostsPath": "/var/lib/docker/containers/950e0a53dab1c8c8bea6f6ede7d8d6186d2c0fc05b61398bb37141695e5f9d1d/hosts",
    "Id": "950e0a53dab1c8c8bea6f6ede7d8d6186d2c0fc05b61398bb37141695e5f9d1d",
    "Image": "aadcaa9101403d671a9f44af8ccdacb37626958ba14c797f606a7d19ca2e662f",
    "LogPath": "/var/lib/docker/containers/950e0a53dab1c8c8bea6f6ede7d8d6186d2c0fc05b61398bb37141695e5f9d1d/950e0a53dab1c8c8bea6f6ede7d8d6186d2c0fc05b61398bb37141695e5f9d
1d-json.log",
    "MountLabel": "",
    "Name": "/rancher-agent",
    "NetworkSettings": {
        "Bridge": "",
        "Gateway": "",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "IPAddress": "",
        "IPPrefixLen": 0,
        "IPv6Gateway": "",
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "MacAddress": "",
        "PortMapping": null,
        "Ports": null
    },
    "Path": "/run.sh",
    "ProcessLabel": "",
    "ResolvConfPath": "/var/lib/docker/containers/950e0a53dab1c8c8bea6f6ede7d8d6186d2c0fc05b61398bb37141695e5f9d1d/resolv.conf",
    "RestartCount": 0,
    "State": {
        "Dead": false,
        "Error": "",
        "ExitCode": 0,
        "FinishedAt": "0001-01-01T00:00:00Z",
        "OOMKilled": false,
        "Paused": false,
        "Pid": 1625,
        "Restarting": false,
        "Running": true,
        "StartedAt": "2015-05-06T14:10:06.133708533Z"
    },
    "Volumes": {
        "/host/proc": "/proc",
        "/lib/modules": "/usr/lib64/modules",
        "/var/lib/cattle": "/var/lib/docker/vfs/dir/13e55fa30af10a5e5e491e417a36d2b79603e94dd4b7c6bf436ce0a3d05c2f44",
        "/var/lib/cattle-legacy": "/var/lib/cattle",
        "/var/lib/docker": "/var/lib/docker",
        "/var/lib/rancher": "/var/lib/rancher",
        "/var/log/rancher": "/var/log/rancher",
        "/var/run/docker.sock": "/run/docker.sock"
    },
    "VolumesRW": {
        "/host/proc": true,
        "/lib/modules": false,
        "/var/lib/cattle": true,
        "/var/lib/cattle-legacy": true,
        "/var/lib/docker": true,
        "/var/lib/rancher": true,
        "/var/log/rancher": true,
        "/var/run/docker.sock": true
    }
}
]

i'll try and spin up too a cluster using ubuntu 14.04 and see as well

regards

**Comment by xinity** [comment]
@ibuildthecloud :
overlay network seems to be working after rebuilding everything based on ubuntu/trusty64
must be something wrong with coreOS then.

**Comment by ibuildthecloud** [comment]
Oddly enough, I believe this has to do with a bug in overlayfs.  https://github.com/docker/docker/issues/13108  CoreOS recently switched to overlay (from btrfs).  Ubuntu by default uses aufs.

We've added a workaround to Rancher and we'll test on CoreOS.  The good thing is that we we're able to reproduce your issue.

**Comment by deniseschannon** [comment]
@ibuildthecloud This issue is also present in CentOS7 hosts.

Docker version 1.6.1
Rancher Agent: v0.7.6
Rancher Agent-Instance: v0.3.1

**Comment by xinity** [comment]
@deniseschannon nice! 
i was just about to test using latest release :)

i'll wait a little then, basically coreos base seems to be "lighter" than ubuntu/debian base

**Comment by deniseschannon** [comment]
@xinity Docker released 1.6.2 and CentOS 7 is now working with the latest Rancher/Server version.

I haven't tested on CoreOS yet.

**Comment by xinity** [comment]
@deniseschannon if i have a moment this week-end, i'll try it and let you know how it goes :)

btw nice changes in the UI:)

**Comment by deniseschannon** [comment]
@xinity it's been awhile, but just curious if you're having these issues with our latest. we just tagged a new one this morning. :)

**Comment by ebuildy** [comment]
Got this problem too, I am using Rancher on Ubuntu 14.04 hosts, hosted at OVH (a french provider). 

I can only ping containers that are on the same hosts ;-( Here my **/var/log/racoon.log**

````
root@bd10e240e513:/# tail /var/log/racoon.log                                   
2015-07-27 18:23:22: WARNING: no outbound policy found: 10.42.118.148/32[0] 10.4
2.0.0/16[0] proto=any dir=out                                                   
2015-07-27 18:23:54: [172.17.0.6] ERROR: phase2 negotiation failed due to time u
p waiting for phase1. ESP 172.17.0.6[0]->172.17.0.4[0]                          
2015-07-27 18:24:13: ERROR: phase1 negotiation failed due to time up. fe01e511ba
6d8409:0000000000000000                                                         
2015-07-27 18:24:26: [172.17.0.6] ERROR: phase2 negotiation failed due to time u
p waiting for phase1. ESP 172.17.0.6[0]->172.17.0.4[0]                          
2015-07-27 18:25:23: [172.17.0.6] ERROR: phase2 negotiation failed due to time u
p waiting for phase1. ESP 172.17.0.6[0]->172.17.0.4[0]                          
2015-07-27 18:25:42: ERROR: phase1 negotiation failed due to time up. b438621a27
e17e53:0000000000000000                                                         
2015-07-27 18:25:56: [172.17.0.6] ERROR: phase2 negotiation failed due to time u
p waiting for phase1. ESP 172.17.0.6[0]->172.17.0.4[0]                          
2015-07-27 18:26:28: [172.17.0.6] ERROR: phase2 negotiation failed due to time u
p waiting for phase1. ESP 172.17.0.6[0]->172.17.0.4[0]                          
2015-07-27 18:26:47: ERROR: phase1 negotiation failed due to time up. b3203f09f1
d8d51d:0000000000000000                                                         
2015-07-27 18:27:57: [172.17.0.6] ERROR: phase2 negotiation failed due to time u
p waiting for phase1. ESP 172.17.0.6[0]->172.17.0.4[0] 
````

The strange thing is Rancher UI doesnt not complain, I can see 10.42.*** IPs for containers in hosts. Hosts can see UDP port 500 & 4500

````
root@vps0001:# nc -vzu ****** 500
Connection to ***** 500 port [udp/isakmp] succeeded!
root@vps0001:# nc -vzu **** 4500
Connection to ******* 4500 port [udp/ipsec-nat-t] succeeded!
````

Do you think this could be due to OVH Ubuntu image? I am using their new cloud based on Open-Stack.

Thanks you,

**Comment by ebuildy** [comment]
I have done this on each hosts:

````
sudo modprobe af_key
sudo echo "af_key" >> /etc/modules
````

Reboot all hosts, re-re-re-re-re-re-(x10)-install rancher-server, add hosts and now I can ping containers across hosts (woaouuuuu).

BTW In Rancher, adding API key, hosts should be possible using CLI or a beautiful **rancher-infra.yml"

**Comment by deniseschannon** [comment]
@ebuildy I'm wondering if your issue is related to #486. Basically, if you only have 1 container on a host, then it might not be able to ping other containers. Adding a second container or restarting the container (not network agent) helps resolve it and enables the ability to ping again.

**Comment by webfrank** [comment]
I'm using 0.34 with 4 hosts with ubuntu 14.04.3 and I have similar problem, sometimes it works but major of time it doesn't. I have 2 hosts on OVH and other two on premise.

**Comment by ibuildthecloud** [comment]
The message about af_key typically does not indicate a failure.  The message is misleading.  If you can see that af_key is loaded on your server (by doing lsmod) then you can ignore this message.  If networking never works and you see these errors in racoon then typically that means that

1. Ports 4500 and 500 for UDP (not TCP) are not open between servers
2. The IP the host is registered with is not accessible by other machines

If you see the above error and it happens only for a period of 12 hours and then networking works again, this is an issue we are currently investigating.  There is a race condition between sending IPsec traffic and setting up the SPD that causes a bad state to be cached.

There is currently a lot of work in progress to make our networking more robust as now Docker 1.9 has proper network drivers.  Look forward to some major enhancements coming.

**Comment by deniseschannon** [comment]
This is no longer applicable as we switched to charon as of v0.56.0. 

If you see issues with networking as of v0.56.0, please open a new issue.
