### ISSUE TITLE
Scheduling rule fails to be met

### ISSUE THREAD

**Issue by kapolos** [rancher/rancher#7251]
**Rancher Version:**
1.2.2
**Docker Version:**
1.12.3
**OS and where are the hosts located? (cloud, bare metal, etc):**
Centos 7, Esxi
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node, internal db, upgraded from 1.1.x
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
Try to add a scheduling rule to a load balancer
**Results:** 
Upgrade failed, can't meet scheduling rule
**Expected:**
Upgrade to work

**Screenshots:**
* LB at start
![image](https://cloud.githubusercontent.com/assets/10794126/21595809/b38ca8aa-d13a-11e6-8a64-5ea9a0719924.png)
* Host label for testing
![image](https://cloud.githubusercontent.com/assets/10794126/21595823/e4c90102-d13a-11e6-9e30-e93045c75974.png)
* Upgrading
![image](https://cloud.githubusercontent.com/assets/10794126/21595845/1b523f36-d13b-11e6-86eb-529fe5dcb5ca.png)
* Fails
![image](https://cloud.githubusercontent.com/assets/10794126/21595848/23e5c636-d13b-11e6-9e2c-6eb97b21106e.png)

**Notes:**
* I have tried restarting the server, disabling cache, same results.
* No XHR failing responses or any kind of console errors.

**Comment by tfiduccia** [comment]
Version - 1.3.0
Labels are completely broken.

**Comment by vincent99** [comment]
Fixed the dropdown, but if there's a problem with the labels actually being used that's going to be a separate problem in the scheduler..

**Comment by tfiduccia** [comment]
Version - master 1/11
This has been fixed.  The labels are now in the drop-down and I can move the load balancer to another host using upgrade.  @kapolos This fix should be in the 1.4.0 build.

**Comment by kapolos** [comment]
Awesome news, thank you both!

**Comment by twoeo** [comment]
Still met this in 1.3.3

**Comment by vincent99** [comment]
@twoeo the milestone is 1.4.0 for a reason.

**Comment by twoeo** [comment]
@vincent99 1.4.0 works.
But why can not specify host ? (Remember can specify in 1.1)
