### ISSUE TITLE
Kubelet failt to start

### ISSUE THREAD

**Issue by bergtwvd** [rancher/rancher#7252]
**Rancher Version:**
Server 1.2.2  +  1.3

**Docker Version:**
1.12.4

**OS and where are the hosts located? (cloud, bare metal, etc):**
Bare metal, Ubuntu 16.04

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
1 master node (running server as per example @ http://docs.rancher.com/rancher/v1.2/en/quick-start-guide/)
3 slave nodes

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
Start Rancher server on master
Add nodes one by one

**Results:** 
Kubelet fails to start (keeps on restarting on all 3 nodes).

Log output of kubelet on node 1:

````

3-1-2017 00:16:08+ true
3-1-2017 00:16:08+ for m in '$(tac /proc/mounts | awk '\''{print $2}'\'' | grep ^${i}/)'
3-1-2017 00:16:08+ umount /run/lxcfs/controllers/name=systemd
3-1-2017 00:16:08umount: /run/lxcfs/controllers/name=systemd: mountpoint not found
3-1-2017 00:16:08+ true
3-1-2017 00:16:08+ for m in '$(tac /proc/mounts | awk '\''{print $2}'\'' | grep ^${i}/)'
3-1-2017 00:16:08+ umount /run/lxcfs/controllers/cpuset
3-1-2017 00:16:08umount: /run/lxcfs/controllers/cpuset: mountpoint not found
3-1-2017 00:16:08+ true
3-1-2017 00:16:08+ for m in '$(tac /proc/mounts | awk '\''{print $2}'\'' | grep ^${i}/)'
3-1-2017 00:16:08+ umount /run/lxcfs/controllers/net_cls,net_prio
3-1-2017 00:16:08umount: /run/lxcfs/controllers/net_cls,net_prio: mountpoint not found
3-1-2017 00:16:08+ true
3-1-2017 00:16:08+ for m in '$(tac /proc/mounts | awk '\''{print $2}'\'' | grep ^${i}/)'
3-1-2017 00:16:08+ umount /run/lxcfs/controllers/hugetlb
3-1-2017 00:16:08umount: /run/lxcfs/controllers/hugetlb: mountpoint not found
3-1-2017 00:16:08+ true
3-1-2017 00:16:08+ for m in '$(tac /proc/mounts | awk '\''{print $2}'\'' | grep ^${i}/)'
3-1-2017 00:16:08+ umount /run/lxcfs/controllers/devices
3-1-2017 00:16:08umount: /run/lxcfs/controllers/devices: mountpoint not found
3-1-2017 00:16:08+ true
3-1-2017 00:16:08+ for m in '$(tac /proc/mounts | awk '\''{print $2}'\'' | grep ^${i}/)'
3-1-2017 00:16:08+ umount /run/lxcfs/controllers/cpu,cpuacct
3-1-2017 00:16:08umount: /run/lxcfs/controllers/cpu,cpuacct: mountpoint not found
3-1-2017 00:16:08+ true
3-1-2017 00:16:08+ for m in '$(tac /proc/mounts | awk '\''{print $2}'\'' | grep ^${i}/)'
3-1-2017 00:16:08+ umount /run/lxcfs/controllers/pids
3-1-2017 00:16:08umount: /run/lxcfs/controllers/pids: mountpoint not found
3-1-2017 00:16:08+ true
3-1-2017 00:16:08+ for m in '$(tac /proc/mounts | awk '\''{print $2}'\'' | grep ^${i}/)'
3-1-2017 00:16:08+ umount /run/lxcfs/controllers/freezer
3-1-2017 00:16:08umount: /run/lxcfs/controllers/freezer: mountpoint not found
3-1-2017 00:16:08+ true
3-1-2017 00:16:08+ for m in '$(tac /proc/mounts | awk '\''{print $2}'\'' | grep ^${i}/)'
3-1-2017 00:16:08+ umount /run/lxcfs/controllers/memory
3-1-2017 00:16:08umount: /run/lxcfs/controllers/memory: mountpoint not found
3-1-2017 00:16:08+ true
3-1-2017 00:16:08+ for m in '$(tac /proc/mounts | awk '\''{print $2}'\'' | grep ^${i}/)'
3-1-2017 00:16:08+ umount /run/lxcfs/controllers/blkio
3-1-2017 00:16:08umount: /run/lxcfs/controllers/blkio: mountpoint not found
3-1-2017 00:16:08+ true
3-1-2017 00:16:08+ for m in '$(tac /proc/mounts | awk '\''{print $2}'\'' | grep ^${i}/)'
3-1-2017 00:16:08+ umount /run/lxcfs/controllers/perf_event
3-1-2017 00:16:08umount: /run/lxcfs/controllers/perf_event: mountpoint not found
3-1-2017 00:16:08+ true
3-1-2017 00:16:08+ for m in '$(tac /proc/mounts | awk '\''{print $2}'\'' | grep ^${i}/)'
3-1-2017 00:16:08+ umount /run/lxcfs/controllers
3-1-2017 00:16:08umount: /run/lxcfs/controllers: not mounted
3-1-2017 00:16:08+ true
3-1-2017 00:16:08+ for m in '$(tac /proc/mounts | awk '\''{print $2}'\'' | grep ^${i}/)'
3-1-2017 00:16:08+ umount /run/lock
3-1-2017 00:16:08umount: /run/lock: not mounted
3-1-2017 00:16:08+ true
3-1-2017 00:16:08+ for i in '$(DOCKER_API_VERSION=1.22 ./docker info 2>&1  | grep -i '\''docker root dir'\'' | cut -f2 -d:)' /var/lib/docker /run /var/run
3-1-2017 00:16:08++ grep '^/var/run/'
3-1-2017 00:16:08++ awk '{print $2}'
3-1-2017 00:16:08++ tac /proc/mounts
3-1-2017 00:16:08+ mount --rbind /host/dev /dev
3-1-2017 00:16:08++ hostname --fqdn
3-1-2017 00:16:08+ FQDN=ranch-slave1
3-1-2017 00:16:08+ exec kubelet --kubeconfig=/etc/kubernetes/ssl/kubeconfig --api_servers=https://kubernetes.kubernetes.rancher.internal:6443 --allow-privileged=true --register-node=true --cloud-provider=rancher --healthz-bind-address=0.0.0.0 --cluster-dns=169.254.169.250 --cluster-domain=cluster.local --network-plugin=cni --network-plugin-dir=/etc/cni/managed.d --hostname-override ranch-slave1
3-1-2017 00:16:09Flag --api-servers has been deprecated, Use --kubeconfig instead. Will be removed in a future version.
3-1-2017 00:16:09I0102 23:16:09.391106   20483 docker.go:375] Connecting to docker on unix:///var/run/docker.sock
3-1-2017 00:16:09I0102 23:16:09.393281   20483 docker.go:395] Start docker client with request timeout=2m0s
3-1-2017 00:16:09I0102 23:16:09.402476   20483 manager.go:143] cAdvisor running in container: "/docker/93908581c09d185142d04a596f7a1766c101a4bc0858555f707b5afd52b4b34f"
3-1-2017 00:16:09W0102 23:16:09.420769   20483 manager.go:151] unable to connect to Rkt api service: rkt: cannot tcp Dial rkt api service: dial tcp [::1]:15441: getsockopt: connection refused
3-1-2017 00:16:09I0102 23:16:09.465619   20483 fs.go:117] Filesystem partitions: map[/dev/mapper/ranch--slave1--vg-root:{mountpoint:/var/lib/docker major:252 minor:0 fsType:ext4 blockSize:0}]
3-1-2017 00:16:09I0102 23:16:09.469260   20483 manager.go:198] Machine: {NumCores:1 CpuFrequency:2598647 MemoryCapacity:4108836864 MachineID:16e25f4d8dbe4e219f5011854772e32c SystemUUID:5A0AA906-836A-F743-9743-587C18AA12DF BootID:f7172677-a6ba-407a-80e8-220cfcfbc859 Filesystems:[{Device:/dev/mapper/ranch--slave1--vg-root Capacity:128813199360 Type:vfs Inodes:8003584 HasInodes:true} {Device:none Capacity:128813199360 Type:vfs Inodes:8003584 HasInodes:true}] DiskMap:map[252:0:{Name:dm-0 Major:252 Minor:0 Size:131004891136 Scheduler:none} 252:1:{Name:dm-1 Major:252 Minor:1 Size:4290772992 Scheduler:none} 8:0:{Name:sda Major:8 Minor:0 Size:136365211648 Scheduler:deadline}] NetworkDevices:[{Name:eth0 MacAddress:00:15:5d:38:01:58 Speed:-1 Mtu:1500}] Topology:[{Id:0 Memory:4108836864 Cores:[{Id:0 Threads:[0] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]}] Caches:[{Size:8388608 Type:Unified Level:3}]}] CloudProvider:Azure InstanceType:Unknown InstanceID:5A0AA906-836A-F743-9743-587C18AA12DF}
3-1-2017 00:16:09I0102 23:16:09.470007   20483 manager.go:204] Version: {KernelVersion:4.4.0-57-generic ContainerOsVersion:Debian GNU/Linux 8 (jessie) DockerVersion:1.12.4 CadvisorVersion: CadvisorRevision:}
3-1-2017 00:16:09I0102 23:16:09.471102   20483 kubelet.go:262] Watching apiserver
3-1-2017 00:16:09W0102 23:16:09.474383   20483 kubelet_network.go:71] Hairpin mode set to "promiscuous-bridge" but configureCBR0 is false, falling back to "hairpin-veth"
3-1-2017 00:16:09I0102 23:16:09.474459   20483 kubelet.go:513] Hairpin mode set to "hairpin-veth"
3-1-2017 00:16:09I0102 23:16:09.490634   20483 docker_manager.go:242] Setting dockerRoot to /var/lib/docker
3-1-2017 00:16:09I0102 23:16:09.509416   20483 server.go:714] Started kubelet v1.4.6-rancher2
3-1-2017 00:16:09E0102 23:16:09.547208   20483 kubelet.go:1091] Image garbage collection failed: unable to find data for container /
3-1-2017 00:16:09I0102 23:16:09.547528   20483 kubelet_node_status.go:203] Setting node annotation to enable volume controller attach/detach
3-1-2017 00:16:09I0102 23:16:09.547572   20483 rancher.go:639] ExternalID [ranch-slave1]
3-1-2017 00:16:09I0102 23:16:09.547585   20483 rancher.go:645] InstanceID [ranch-slave1]
3-1-2017 00:16:09I0102 23:16:09.547766   20483 server.go:118] Starting to listen on 0.0.0.0:10250
3-1-2017 00:16:09I0102 23:16:09.571579   20483 rancher.go:645] InstanceID [ranch-slave1]
3-1-2017 00:16:09I0102 23:16:09.622738   20483 rancher.go:645] InstanceID [ranch-slave1]
3-1-2017 00:16:09I0102 23:16:09.670804   20483 kubelet_node_status.go:245] Adding node label from cloud provider: beta.kubernetes.io/instance-type=rancher
3-1-2017 00:16:09I0102 23:16:09.670898   20483 kubelet_node_status.go:256] Adding node label from cloud provider: failure-domain.beta.kubernetes.io/zone=FailureDomain1
3-1-2017 00:16:09I0102 23:16:09.670921   20483 kubelet_node_status.go:260] Adding node label from cloud provider: failure-domain.beta.kubernetes.io/region=Region1
3-1-2017 00:16:09E0102 23:16:09.715696   20483 kubelet.go:2124] Failed to check if disk space is available for the runtime: failed to get fs info for "runtime": unable to find data for container /
3-1-2017 00:16:09E0102 23:16:09.715730   20483 kubelet.go:2132] Failed to check if disk space is available on the root partition: failed to get fs info for "root": unable to find data for container /
3-1-2017 00:16:09I0102 23:16:09.722128   20483 fs_resource_analyzer.go:66] Starting FS ResourceAnalyzer
3-1-2017 00:16:09I0102 23:16:09.722159   20483 status_manager.go:129] Starting to sync pod status with apiserver
3-1-2017 00:16:09I0102 23:16:09.722169   20483 kubelet.go:2226] Starting kubelet main sync loop.
3-1-2017 00:16:09I0102 23:16:09.722184   20483 kubelet.go:2237] skipping pod synchronization - [network state unknown container runtime is down]
3-1-2017 00:16:09I0102 23:16:09.722584   20483 volume_manager.go:239] Starting Kubelet Volume Manager
3-1-2017 00:16:09I0102 23:16:09.771998   20483 factory.go:295] Registering Docker factory
3-1-2017 00:16:09W0102 23:16:09.772632   20483 manager.go:247] Registration of the rkt container factory failed: unable to communicate with Rkt api service: rkt: cannot tcp Dial rkt api service: dial tcp [::1]:15441: getsockopt: connection refused
3-1-2017 00:16:09I0102 23:16:09.772674   20483 factory.go:54] Registering systemd factory
3-1-2017 00:16:09I0102 23:16:09.772968   20483 factory.go:86] Registering Raw factory
3-1-2017 00:16:09I0102 23:16:09.773217   20483 manager.go:1106] Started watching for new ooms in manager
3-1-2017 00:16:09I0102 23:16:09.773928   20483 oomparser.go:185] oomparser using systemd
3-1-2017 00:16:09I0102 23:16:09.774339   20483 manager.go:288] Starting recovery of all containers
3-1-2017 00:16:09I0102 23:16:09.774405   20483 manager.go:293] Recovery completed
3-1-2017 00:16:09F0102 23:16:09.774423   20483 kubelet.go:1146] Failed to start cAdvisor inotify_add_watch /run/lxcfs/controllers/cpu,cpuacct: no such file or directory
````

and the server log on the master shows:

````
...
2017-01-03 00:10:55,911 ERROR [:] [] [] [] [cutorService-38] [o.a.c.m.context.NoExceptionRunnable ] Expected state running but got stopped
2017-01-03 00:11:09,113 ERROR [:] [] [] [] [cutorService-27] [o.a.c.m.context.NoExceptionRunnable ] Expected state running but got stopped
2017-01-03 00:12:09,203 ERROR [:] [] [] [] [cutorService-12] [o.a.c.m.context.NoExceptionRunnable ] Expected state running but got stopped
2017-01-03 00:12:13,239 ERROR [bd5338a5-ed77-46c7-a4c5-0bddcb3ba76d:18175] [service:15] [service.update] [] [ecutorService-7] [c.p.e.p.i.DefaultProcessInstanceImpl] Expected state running but got stopped
2017-01-03 00:12:13,295 ERROR [:] [] [] [] [ecutorService-7] [.e.s.i.ProcessInstanceDispatcherImpl] Expected state running but got stopped
2017-01-03 00:12:26,533 ERROR [:] [] [] [] [ecutorService-6] [o.a.c.m.context.NoExceptionRunnable ] Expected state running but got stopped
2017-01-03 00:12:52,295 ERROR [ba081cc5-9dde-4c50-a5e0-0a32a92e0bbf:18419] [service:15] [service.update] [] [ecutorService-8] [c.p.e.p.i.DefaultProcessInstanceImpl] Expected state running but got stopped
2017-01-03 00:12:52,343 ERROR [:] [] [] [] [ecutorService-8] [.e.s.i.ProcessInstanceDispatcherImpl] Expected state running but got stopped
2017-01-03 00:13:10,285 ERROR [:] [] [] [] [cutorService-38] [o.a.c.m.context.NoExceptionRunnable ] Expected state running but got stopped
2017-01-03 00:13:29,347 ERROR [:] [] [] [] [cutorService-26] [o.a.c.m.context.NoExceptionRunnable ] Expected state running but got stopped
2017-01-03 00:14:00,473 ERROR [:] [] [] [] [cutorService-33] [o.a.c.m.context.NoExceptionRunnable ] Expected state running but got stopped
2017-01-03 00:14:31,536 ERROR [:] [] [] [] [cutorService-48] [o.a.c.m.context.NoExceptionRunnable ] Expected state running but got stopped
2017-01-03 00:14:43,621 ERROR [:] [] [] [] [cutorService-43] [o.a.c.m.context.NoExceptionRunnable ] Expected state running but got stopped
2017-01-03 00:14:53,588 ERROR [:] [] [] [] [cutorService-15] [o.a.c.m.context.NoExceptionRunnable ] Expected state running but got stopped
2017-01-03 00:15:08,582 ERROR [:] [] [] [] [cutorService-44] [o.a.c.m.context.NoExceptionRunnable ] Expected state running but got stopped
2017-01-03 00:15:27,589 ERROR [:] [] [] [] [cutorService-28] [o.a.c.m.context.NoExceptionRunnable ] Expected state running but got stopped
time="2017-01-03T00:15:46Z" level=info msg="Refresh for this catalog library is already in process, skipping"
time="2017-01-03T00:15:47Z" level=info msg="Refresh for this catalog community is already in process, skipping"
2017-01-03 00:15:54,608 ERROR [:] [] [] [] [cutorService-46] [o.a.c.m.context.NoExceptionRunnable ] Expected state running but got stopped
2017-01-03 00:16:11,680 ERROR [9f4d68be-a73d-400c-9c48-7ea935987026:19506] [service:15] [service.update] [] [ecutorService-1] [c.p.e.p.i.DefaultProcessInstanceImpl] Expected state running but got stopped
2017-01-03 00:16:11,705 ERROR [:] [] [] [] [ecutorService-1] [.e.s.i.ProcessInstanceDispatcherImpl] Expected state running but got stopped
2017-01-03 00:16:28,705 ERROR [:] [] [] [] [cutorService-16] [o.a.c.m.context.NoExceptionRunnable ] Expected state running but got stopped
2017-01-03 00:16:50,503 ERROR [:] [] [] [] [cutorService-46] [o.a.c.m.context.NoExceptionRunnable ] Expected state running but got stopped
...
````

**Expected:**
Kubelet should start.

**Comment by danielfn** [comment]
I'm experiencing a similar issue, in my case using the containerized rancher-agent in a VirtualBox machine provisioned with docker-machine:
```
F0104 15:00:51.208254    2299 kubelet.go:1210] Failed to start cAdvisor inotify_add_watch /var/lib/docker/aufs/mnt/cbaeb865bfa6e38404123fffed4f240161c1e4c42d0bdd3aa9e84e4f77e59a5d/sys/fs/cgroup/memory: no such file or directory

```
Here is the full log: [r-kubernetes-kubelet-1-6fb28f96.txt](https://github.com/rancher/rancher/files/685056/r-kubernetes-kubelet-1-6fb28f96.txt)

**Comment by danielfn** [comment]
It seems that the entry.sh script is unmounting directories which kubelet needs. I believe that this bug is related with this recent commit in kubernetes-package:

https://github.com/rancher/kubernetes-package/commit/6471676a7ed98b910813447628abe81c3e73375a

**Comment by bergtwvd** [comment]
Just did a fresh/clean install of Rancher 1.3 (Ubuntu 16.04, Docker 1.12.5).
Created Kubernetes environment, with 3 nodes, 1 master.

Still, Kubulet fails to start (repeatedly goes through subset of states: None - Starting - Networking - In Progress). Kubernetes is unusable.

**Comment by Rchood** [comment]
I have the same issue on CentOS7 Docker version 1.12.6, build 78d1802

Anyone got a solution?

**Comment by mjrudnik** [comment]
I am experiencing the same problem.
Are there any solutions now?

My kubelet logs:

`26.1.2017 19:12:08umount: /run/lxcfs/controllers/name=systemd: mountpoint not found
26.1.2017 19:12:08+ true
26.1.2017 19:12:08+ for m in '$(tac /proc/mounts | awk '\''{print $2}'\'' | grep ^${i}/)'
26.1.2017 19:12:08+ umount /run/lxcfs/controllers/net_cls,net_prio
26.1.2017 19:12:08umount: /run/lxcfs/controllers/net_cls,net_prio: mountpoint not found
26.1.2017 19:12:08+ true
26.1.2017 19:12:08+ for m in '$(tac /proc/mounts | awk '\''{print $2}'\'' | grep ^${i}/)'
26.1.2017 19:12:08+ umount /run/lxcfs/controllers/memory
26.1.2017 19:12:08umount: /run/lxcfs/controllers/memory: mountpoint not found
26.1.2017 19:12:08+ true
26.1.2017 19:12:08+ for m in '$(tac /proc/mounts | awk '\''{print $2}'\'' | grep ^${i}/)'
26.1.2017 19:12:08+ umount /run/lxcfs/controllers/cpuset
26.1.2017 19:12:08umount: /run/lxcfs/controllers/cpuset: mountpoint not found
26.1.2017 19:12:08+ true
26.1.2017 19:12:08+ for m in '$(tac /proc/mounts | awk '\''{print $2}'\'' | grep ^${i}/)'
26.1.2017 19:12:08+ umount /run/lxcfs/controllers/cpu,cpuacct
26.1.2017 19:12:08umount: /run/lxcfs/controllers/cpu,cpuacct: mountpoint not found
26.1.2017 19:12:08+ true
26.1.2017 19:12:08+ for m in '$(tac /proc/mounts | awk '\''{print $2}'\'' | grep ^${i}/)'
26.1.2017 19:12:08+ umount /run/lxcfs/controllers/hugetlb
26.1.2017 19:12:08umount: /run/lxcfs/controllers/hugetlb: mountpoint not found
26.1.2017 19:12:08+ true
26.1.2017 19:12:08+ for m in '$(tac /proc/mounts | awk '\''{print $2}'\'' | grep ^${i}/)'
26.1.2017 19:12:08+ umount /run/lxcfs/controllers/blkio
26.1.2017 19:12:08umount: /run/lxcfs/controllers/blkio: mountpoint not found
26.1.2017 19:12:08+ true
26.1.2017 19:12:08+ for m in '$(tac /proc/mounts | awk '\''{print $2}'\'' | grep ^${i}/)'
26.1.2017 19:12:08+ umount /run/lxcfs/controllers/devices
26.1.2017 19:12:08umount: /run/lxcfs/controllers/devices: mountpoint not found
26.1.2017 19:12:08+ true
26.1.2017 19:12:08+ for m in '$(tac /proc/mounts | awk '\''{print $2}'\'' | grep ^${i}/)'
26.1.2017 19:12:08+ umount /run/lxcfs/controllers/pids
26.1.2017 19:12:08umount: /run/lxcfs/controllers/pids: mountpoint not found
26.1.2017 19:12:08+ true
26.1.2017 19:12:08+ for m in '$(tac /proc/mounts | awk '\''{print $2}'\'' | grep ^${i}/)'
26.1.2017 19:12:08+ umount /run/lxcfs/controllers/perf_event
26.1.2017 19:12:08umount: /run/lxcfs/controllers/perf_event: mountpoint not found
26.1.2017 19:12:08+ true
26.1.2017 19:12:08+ for m in '$(tac /proc/mounts | awk '\''{print $2}'\'' | grep ^${i}/)'
26.1.2017 19:12:08+ umount /run/lxcfs/controllers/freezer
26.1.2017 19:12:08umount: /run/lxcfs/controllers/freezer: mountpoint not found
26.1.2017 19:12:08+ true
26.1.2017 19:12:08+ for m in '$(tac /proc/mounts | awk '\''{print $2}'\'' | grep ^${i}/)'
26.1.2017 19:12:08+ umount /run/lxcfs/controllers
26.1.2017 19:12:08umount: /run/lxcfs/controllers: not mounted
26.1.2017 19:12:08+ true
26.1.2017 19:12:08+ for m in '$(tac /proc/mounts | awk '\''{print $2}'\'' | grep ^${i}/)'
26.1.2017 19:12:08+ umount /run/lock
26.1.2017 19:12:08umount: /run/lock: not mounted
26.1.2017 19:12:08+ true
26.1.2017 19:12:08+ for i in '$(DOCKER_API_VERSION=1.22 ./docker info 2>&1  | grep -i '\''docker root dir'\'' | cut -f2 -d:)' /var/lib/docker /run /var/run
26.1.2017 19:12:08++ tac /proc/mounts
26.1.2017 19:12:08++ awk '{print $2}'
26.1.2017 19:12:08++ grep '^/var/run/'
26.1.2017 19:12:08+ mount --rbind /host/dev /dev
26.1.2017 19:12:08++ hostname --fqdn
26.1.2017 19:12:08+ FQDN=cloud4-vm226.de-nserver.de
26.1.2017 19:12:08+ exec kubelet --kubeconfig=/etc/kubernetes/ssl/kubeconfig --api_servers=https://kubernetes.kubernetes.rancher.internal:6443 --allow-privileged=true --register-node=true --cloud-provider=rancher --healthz-bind-address=0.0.0.0 --cluster-dns=10.43.0.10 --cluster-domain=cluster.local --network-plugin=cni --network-plugin-dir=/etc/cni/managed.d --hostname-override cloud4-vm226.de-nserver.de
26.1.2017 19:12:08Flag --api-servers has been deprecated, Use --kubeconfig instead. Will be removed in a future version.
26.1.2017 19:12:08I0126 18:12:08.845087    2885 feature_gate.go:181] feature gates: map[]
26.1.2017 19:12:08I0126 18:12:08.980725    2885 docker.go:356] Connecting to docker on unix:///var/run/docker.sock
26.1.2017 19:12:08I0126 18:12:08.980751    2885 docker.go:376] Start docker client with request timeout=2m0s
26.1.2017 19:12:08I0126 18:12:08.985663    2885 manager.go:143] cAdvisor running in container: "/docker/aac04be461a9670af858a3dcf3fa5d30a25aaa51aa3d2638200b1e73e19a5148"
26.1.2017 19:12:08W0126 18:12:08.993413    2885 manager.go:151] unable to connect to Rkt api service: rkt: cannot tcp Dial rkt api service: dial tcp [::1]:15441: getsockopt: connection refused
26.1.2017 19:12:09I0126 18:12:09.001250    2885 fs.go:117] Filesystem partitions: map[/dev/mapper/cloud4--vm226--vg-root:{mountpoint:/var/lib/docker major:252 minor:0 fsType:ext4 blockSize:0}]
26.1.2017 19:12:09I0126 18:12:09.002407    2885 manager.go:198] Machine: {NumCores:6 CpuFrequency:2499996 MemoryCapacity:67560845312 MachineID:16e25f4d8dbe4e219f5011854772e32c SystemUUID:197B8212-453C-4450-8D3D-89E444735C4F BootID:85dc1f21-9115-4c8d-bc1e-d0dc4babd1f3 Filesystems:[{Device:/dev/mapper/cloud4--vm226--vg-root Capacity:143062409216 Type:vfs Inodes:8880128 HasInodes:true} {Device:none Capacity:143062409216 Type:vfs Inodes:8880128 HasInodes:true}] DiskMap:map[8:0:{Name:sda Major:8 Minor:0 Size:214748364800 Scheduler:deadline} 252:0:{Name:dm-0 Major:252 Minor:0 Size:145479434240 Scheduler:none} 252:1:{Name:dm-1 Major:252 Minor:1 Size:68715282432 Scheduler:none}] NetworkDevices:[{Name:ens18 MacAddress:c6:2e:93:7d:32:76 Speed:0 Mtu:1500} {Name:ens19 MacAddress:fa:e4:4c:f1:55:6e Speed:0 Mtu:1500}] Topology:[{Id:0 Memory:67560845312 Cores:[{Id:0 Threads:[0] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:4194304 Type:Unified Level:2}]} {Id:1 Threads:[1] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:4194304 Type:Unified Level:2}]} {Id:2 Threads:[2] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:4194304 Type:Unified Level:2}]} {Id:3 Threads:[3] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:4194304 Type:Unified Level:2}]} {Id:4 Threads:[4] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:4194304 Type:Unified Level:2}]} {Id:5 Threads:[5] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:4194304 Type:Unified Level:2}]}] Caches:[]}] CloudProvider:Unknown InstanceType:Unknown InstanceID:None}
26.1.2017 19:12:09I0126 18:12:09.002717    2885 manager.go:204] Version: {KernelVersion:4.4.0-21-generic ContainerOsVersion:Debian GNU/Linux 8 (jessie) DockerVersion:1.12.6 CadvisorVersion: CadvisorRevision:}
26.1.2017 19:12:09W0126 18:12:09.004184    2885 container_manager_linux.go:205] Running with swap on is not supported, please disable swap! This will be a fatal error by default starting in K8s v1.6! In the meantime, you can opt-in to making this a fatal error by enabling --experimental-fail-swap-on.
26.1.2017 19:12:09I0126 18:12:09.004339    2885 kubelet.go:252] Watching apiserver
26.1.2017 19:12:09W0126 18:12:09.007004    2885 kubelet_network.go:69] Hairpin mode set to "promiscuous-bridge" but kubenet is not enabled, falling back to "hairpin-veth"
26.1.2017 19:12:09I0126 18:12:09.007028    2885 kubelet.go:477] Hairpin mode set to "hairpin-veth"
26.1.2017 19:12:09I0126 18:12:09.013184    2885 docker_manager.go:257] Setting dockerRoot to /var/lib/docker
26.1.2017 19:12:09I0126 18:12:09.013216    2885 docker_manager.go:260] Setting cgroupDriver to cgroupfs
26.1.2017 19:12:09I0126 18:12:09.013932    2885 server.go:770] Started kubelet v1.5.1-rancher1
26.1.2017 19:12:09I0126 18:12:09.014000    2885 server.go:123] Starting to listen on 0.0.0.0:10250
26.1.2017 19:12:09E0126 18:12:09.014020    2885 kubelet.go:1145] Image garbage collection failed: unable to find data for container /
26.1.2017 19:12:09I0126 18:12:09.014175    2885 kubelet_node_status.go:204] Setting node annotation to enable volume controller attach/detach
26.1.2017 19:12:09I0126 18:12:09.014529    2885 rancher.go:641] ExternalID [cloud4-vm226.de-nserver.de]
26.1.2017 19:12:09I0126 18:12:09.014539    2885 rancher.go:648] InstanceID [cloud4-vm226.de-nserver.de]
26.1.2017 19:12:09I0126 18:12:09.074721    2885 rancher.go:648] InstanceID [cloud4-vm226.de-nserver.de]
26.1.2017 19:12:09I0126 18:12:09.134021    2885 rancher.go:648] InstanceID [cloud4-vm226.de-nserver.de]
26.1.2017 19:12:09I0126 18:12:09.193195    2885 kubelet_node_status.go:246] Adding node label from cloud provider: beta.kubernetes.io/instance-type=rancher
26.1.2017 19:12:09I0126 18:12:09.193220    2885 kubelet_node_status.go:257] Adding node label from cloud provider: failure-domain.beta.kubernetes.io/zone=FailureDomain1
26.1.2017 19:12:09I0126 18:12:09.193230    2885 kubelet_node_status.go:261] Adding node label from cloud provider: failure-domain.beta.kubernetes.io/region=Region1
26.1.2017 19:12:09E0126 18:12:09.259344    2885 kubelet.go:1634] Failed to check if disk space is available for the runtime: failed to get fs info for "runtime": unable to find data for container /
26.1.2017 19:12:09E0126 18:12:09.259376    2885 kubelet.go:1642] Failed to check if disk space is available on the root partition: failed to get fs info for "root": unable to find data for container /
26.1.2017 19:12:09I0126 18:12:09.260438    2885 fs_resource_analyzer.go:66] Starting FS ResourceAnalyzer
26.1.2017 19:12:09I0126 18:12:09.260478    2885 status_manager.go:129] Starting to sync pod status with apiserver
26.1.2017 19:12:09I0126 18:12:09.260498    2885 kubelet.go:1714] Starting kubelet main sync loop.
26.1.2017 19:12:09I0126 18:12:09.260505    2885 kubelet.go:1725] skipping pod synchronization - [container runtime is down]
26.1.2017 19:12:09I0126 18:12:09.260511    2885 volume_manager.go:242] Starting Kubelet Volume Manager
26.1.2017 19:12:09I0126 18:12:09.267934    2885 factory.go:295] Registering Docker factory
26.1.2017 19:12:09W0126 18:12:09.267954    2885 manager.go:247] Registration of the rkt container factory failed: unable to communicate with Rkt api service: rkt: cannot tcp Dial rkt api service: dial tcp [::1]:15441: getsockopt: connection refused
26.1.2017 19:12:09I0126 18:12:09.268239    2885 factory.go:54] Registering systemd factory
26.1.2017 19:12:09I0126 18:12:09.268550    2885 factory.go:86] Registering Raw factory
26.1.2017 19:12:09I0126 18:12:09.268759    2885 manager.go:1106] Started watching for new ooms in manager
26.1.2017 19:12:09I0126 18:12:09.270559    2885 oomparser.go:185] oomparser using systemd
26.1.2017 19:12:09I0126 18:12:09.271062    2885 manager.go:288] Starting recovery of all containers
26.1.2017 19:12:09I0126 18:12:09.271094    2885 manager.go:293] Recovery completed
26.1.2017 19:12:09F0126 18:12:09.271104    2885 kubelet.go:1210] Failed to start cAdvisor inotify_add_watch /run/lxcfs/controllers/cpu,cpuacct: no such file or directory
`

**Comment by techninja1008** [comment]
Workaround working so far on Ubuntu 16.04:

Go to hosts tab and click on kubernetes stack

Update kubelet service and change the number at end of image tag from 7 to 1

Wait.

Everything should work.

**Comment by SCBbestof** [comment]
Is there any plan to fix this issue in the next patch? The workaround only works on Ubuntu systems.

**Comment by SCBbestof** [comment]
Small update: I stopped encountering any issues with Kubernetes when I upgraded to Rancher 1.5.3.

**Comment by baskinsy** [comment]
I'm experiencing the same issue when upgrading from rancher 1.5.6 to 1.5.7. Didn't had any issue until now and kubelet is stuck on upgrading.

**Comment by aemneina** [comment]
@baskinsy youre most likely hitting a different issue. Can you file a new issue and include kubelet logs there?

**Comment by baskinsy** [comment]
@aemneina I had to discard my Kubernetes env and now I'm on 1.5.9. I'll try to re-test and update or file an new issue in case of problem...

**Comment by robodude666** [comment]
As @dchambers pointed out in #7536, downgrading to `rancher/k8s:v1.5.1-rancher1-1` seems to fix the issue for me as well. Currently running `rancher/server:stable` v1.6.7.

**Comment by zaakiy** [comment]
Still having issue with the latest versions of all software. Refer to my comment here: https://github.com/rancher/rancher/issues/7536#issuecomment-341852235
