### ISSUE TITLE
rancher some containers stats n/a

### ISSUE THREAD

**Issue by Chenpipi** [rancher/rancher#7255]
*Describe your issue here*

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.2.1` Cattle: `v0.174.8` UI: `v1.2.39` |
|Access|`Disabled`|
|Orchestration|`Cattle`|
|Route|`service.containers`|

Docker version 1.12.3, build 6b644ec

System: CentOS 7

I use the single rancher, add the host and container, found some containers for the stats n/a, Some containers are in a normal stats.The container use the same image.
Stats normal containers can execute shells, and state n/a containers can not execute shells.
![123](https://cloud.githubusercontent.com/assets/9670781/21599975/483edbce-d1b0-11e6-9031-327b1b61cca8.jpg)

**Comment by deniseschannon** [comment]
We collect stats from `docker stats`. This seems to be a docker issue centos. 

Have you tried logging onto your host and doing `docker stats` for those containers? We return `n/a` when docker doesn't return anything. 

It looks like it's a kernel issue based on this docker bug: https://github.com/docker/docker/issues/28373
