### ISSUE TITLE
Ability to "pad" host serial numbers for creation of new hosts.

### ISSUE THREAD

**Issue by lonix** [rancher/rancher#7257]
When adding new hosts to rancher, enable the ability to pad the serialnumber to x digits 

e.g. rather than 

aws-host1
... 
aws-host9

I want the result of 

aws-host001
...
aws-host009

This helps with inventorying and sorting.

**Comment by vincent99** [comment]
The UI does exactly that  if you enter `aws-host001` as the name.  And next time you can continue with `aws-host010`.
