### ISSUE TITLE
Change auth method by config files

### ISSUE THREAD

**Issue by mati75** [rancher/rancher#7258]
**Rancher Version:**
1.1.2
**Docker Version:**
1.12.5
**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04 LTS on HyperV VM
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Multi node rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
I have active directory auth configuration. After changes on Windows Server rancher have missing connect to active directory. I want back to login for local admin account and change login settings to active directory. Now web interfaces is complete unless, I can't log in any way. How I can change login method by config file? Is exist that solution?
**Results:** 
Problem with login to any admin account after changes on active directory server.
**Expected:**
Change login settings by config file.

**Comment by vincent99** [comment]
There USD no config file, you can turn off access control in the database: http://docs.rancher.com/rancher/v1.2/en/faqs/troubleshooting/#authentication
