### ISSUE TITLE
Load Balancer sends http requests instead of https requests

### ISSUE THREAD

**Issue by typia** [rancher/rancher#7260]
**Rancher Version:**
1.2.2
**Docker Version:**
1.12.3
**OS and where are the hosts located? (cloud, bare metal, etc):**
Debian 8
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node rancher external DB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
Create a load balancer to xxx.mydomain.com with https protocol, port 443 to a nginx container
**Results:** 
ngninx give a "400 bad request The plain HTTP request was sent to HTTPS port" error.
When I try to access https directly within the host ip with a port redirection (4443 ->443) it's ok so I guess the issue is with load balancer sending requests with http protocol instead of https
**Expected:**
website displays correctly

**Comment by vincent99** [comment]
`https` is SSL *termination*.  If you want the SSL connection passed all the way down to the target container then you want `tcp` or `sni`.

http://docs.rancher.com/rancher/v1.2/en/cattle/adding-load-balancers/#protocol

**Comment by typia** [comment]
Hi @vincent99, thanks a lot for your answer and sorry for the misunderstanding.

I can't use TCP as I would like have multiple ssl websites and seems like TCP allow me to redirect 443 port only to 1 service.
Regarding SNI, should I add it on top of ssl termination ? or alone ?

Many thanks again

**Comment by vincent99** [comment]
Modern TLS includes a handshake field called SNI (Server Name Indication) which allows the client to tell the server what hostname the request is for (and therefore what certificate it should respond with) before decrypting the message.

The`sni` protocol option looks at that and allows you to do host-based routing to different services without terminating the TLS connection.

Just `sni`, don't mix with `https`

**Comment by typia** [comment]
You're right I just tried and it was just awfully slow because of caching and my ssl configuration on nginx side.
I made a rancher-nfs volume with my certs as all my domains are wildcarded subdomains declared it in nginx conf and everything is ok.

Don't know if it's the proper way to do but it's working.
Many thanks

**Comment by typia** [comment]
@vincent99 Sorry to add another question, but don't want to open an issue for nothing.
Don't know if SNI is meant to be used like that but it doesn't work with wildcards domains.
As long as I use sub.domain.com it's ok but when I switch to *.domain.com it fails with ERR_CONNECTION_CLOSED, it doesn't seem to go until my nginx container as nginx log is empty.
is a load balancer bug or SNI limitation ?

**Comment by vincent99** [comment]
That sounds like a bug/missing feature for SNI, @alena1108?

As a side-note, unless you have some regulatory rule specifically requiring SSL all the way to the container, it's a lot simpler to use SSL termination at the load balancer.  The "plaintext" request is still encrypted over the wire on the IPSec overlay network.  And then you can have the certs on the balancer instead of needing them on every host.

**Comment by typia** [comment]
@vincent99
My needs are simple but same is my mind :)
I just have 3 webservers in 3 containers managed by rancher, and each one has to be protected with SSL.

The way you describe seems the way I configured my load balancer on first approach, thats why I'm lost !
When I used https termination, my nginx server was seen https requests as http request.
Could you please detail the setup and / or tell me if it's not the proper place for this.
Tell me also if I should raise a new Issue for wildcard on SNI

**Comment by vincent99** [comment]
You'd have to change nginx to listen on regular http, and then the containers no longer need the SSL certificates because they're managed at the balancer.

**Comment by typia** [comment]
Thanks a lot @vincent99 !

I upgraded my balancers to redirect 80 port on http and 443 on https
On nginx side I redirect 80 to https within the config and made nginx listen on 443 without specifying ssl and everything seems ok.
