### ISSUE TITLE
Docker stats shows no net-metrics for containers deployed in managed network

### ISSUE THREAD

**Issue by salvax86** [rancher/rancher#7261]
**Rancher Version:**
v1.2.2
**Docker Version:**
v1.11.2-v1.12.5
**OS and where are the hosts located? (cloud, bare metal, etc):**
cloud with Ubuntu 15.10(4.2.0)
VMs (Vagrant) with RancherOS (4.4.10)
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher and internal DB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
Deploying a stack with managed network
**Results:** 
docker stats shows no metrics for NET I/O for containers in managed network. A look on `docker inspect none` shows that containers in managed network are deployed with NetworkMode=none
**Expected:**
Metrics for NET I/O where traffic is going through containers

**Comment by willmasters** [comment]
This is indeed true of Rancher 1.3 as well. I'm using Telegraf and InfluxDB to access data from the Docker stats api and if your Cattle stack is managed there is no such networking metadata. I assumed this was by design. When changing the network from managed to bridged, it becomes available.

**Comment by salvax86** [comment]
Yes but I have an use case where i cannot change network mode from managed to bridged

**Comment by willmasters** [comment]
Yes so do I, I think most use cases based on Rancher probably require managed.

**Comment by eesprit** [comment]
+1 having network stats provided in a standard way (via docker stats) is a real need, as it could then be used by standard tools (like Telegraf).

The rancher stats API which provides those network metrics (by the use of network namespace calls) is actually pretty hard to manipulate/use (websocket, needs to renew the token frequently, does not see new containers appearing during the current session, fixed refresh rate of 1 second, etc.) and not easily usable with existing tools.

**Comment by garceri** [comment]
We need a way to monitor container network usage, this is a big issue for us, would it be possible for rancher to expose these metrics in an easy format that can be read by most monitoring tools ?

**Comment by garceri** [comment]
+1 on having the network stats provided in an easy to access way that can be consumed by monitoring tools

**Comment by parin921996** [comment]
Any progress on this ?

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
