### ISSUE TITLE
Scheduler Crashed and now won't re-create it's self

### ISSUE THREAD

**Issue by jwhitcraft** [rancher/rancher#7267]
**Rancher Version:** 1.2.2
**Docker Version:** 1.12.5
**OS and where are the hosts located? (cloud, bare metal, etc):** AWS
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** Single node, RDS Db
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

I went in to check on things this am and noticed that the scheduler agent was throwing these errors:

```
Activating (Failed to allocate instance [container:1i330653]: Bad instance [container:1i330653] in state [error]: Scheduling failed: No healthy hosts with sufficient resources available)
```

I don't see anything the logs and all of my hosts are responding as normal.

**Comment by jclark360** [comment]
I have the same issue. 1.2.1

**Comment by chrisdupuy** [comment]
Same issue with this environment : 
Rancher	v1.2.1
Cattle	v0.174.8
User Interface	v1.2.39
Rancher Compose	v0.12.1

Also one of our other environments has dropped down with this first alerting message, and we are unable to remount it correctly. Others environments are all ok.
The only differences we see is that upgrades are available in the interface for healthchek, ipsec, scheduler and network-service. 
Environments that work well are up to date. Do we need to run update even if "No healthy hosts with sufficient resources available" ?

**Comment by superseb** [comment]
Closing in favor of https://github.com/rancher/rancher/issues/7482
