### ISSUE TITLE
Add/Cancel Environment going to middle of Manage Environment page

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#7268]
**Rancher Version:** master 1/3

**Steps to Reproduce:**
1.  Go to Manage environment
2.  Click on Add Environment
3.  Click on Add or Cancel

**Results:** The Add or Cancel always goes to the middle of the Manage environment page.  Which is strange.
![image](https://cloud.githubusercontent.com/assets/11514927/21622228/b575ae62-d1b9-11e6-9d04-7d6c30e7eeb8.png)

**Expected:**  Should not just default to middle of page?

**Comment by westlywright** [comment]
@tfiduccia I think this can be closed. The page was updated to use a tab select for the different sections. Side effect was fixing this issue.

**Comment by tfiduccia** [comment]
I agree.  Closing
