### ISSUE TITLE
storage: Container-scoped volumes are deleted in failure scenarios

### ISSUE THREAD

**Issue by LLParse** [rancher/rancher#7271]
**Rancher Version:** 1.2.2

**Docker Version:** 1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):** Ubuntu 16.04, GCE

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single node, internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** cattle

**Steps to Reproduce:**
1. Configure and launch the Rancher NFS driver (or any other driver)
2. Create a service with scale > 1 with a container-scoped volume
3. Delete a host (or delete a container) to observe reconciliation

**Results:** Container rescheduled onto new host, old volume unmounted/removed, new volume created/mounted

**Expected:** Container rescheduled onto new host, old volume is mounted, execution continues

**Comment by sangeethah** [comment]
Tested with build from master from Mar 17

Scenario 1:

Create a service with volumes(from NFS) having container scope with scale 3.
Write contents to the volume of one of the instances.
Delete this instance.
Wait for instance to get recreated (by service reconcile)

The new instance created will have the sane volume as the deleted instance (reused from the DU). Verified that the contents of the volumes have the changes made before the instance was deleted. 

scenario 2:
Create a health service with volumes(from NFS) having container scope with scale 3.
Write contents to the volume of one of the instances.
Make this instance unhealthy by  powering down host
Wait for instance to get recreated (by service reconcile)

The new instance created will have the same volume (reused from the DU). Verify that the contents of the volumes have the changes made before the instance was deleted.

**Comment by sangeethah** [comment]
Reopening this issue.

Need to retest this issue when the fixes are made available in master build again as part of rancher-server 1.7 release.

**Comment by tfiduccia** [comment]
re-test when Volumes are implemented

**Comment by nenggangpan** [comment]
what's the status of the this bug? when are you planning to fix this bug and release it?

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
