### ISSUE TITLE
Unable to start Rancher agent using docker_container Ansible module

### ISSUE THREAD

**Issue by ChienHuey** [rancher/rancher#7272]
**Rancher Version:**
v1.2.2

**Docker Version:**
1.12.5-cs5, build f7aca07

**OS and where are the hosts located? (cloud, bare metal, etc):**
Amazon AWS, Ubuntu 14.04 LTS, AMI: ami-1081b807

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher, internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Target Environment is Swarm but the problem has to do with adding custom hosts to Rancher.

**Steps to Reproduce:**

<I'm trying to run this Ansible play in order to automate adding hosts to Rancher>
  - name: run docker to add hosts
    vars:
      registration_url: "{{ (registrationtokens.content | from_json) | json_query('data[*].registrationUrl[]') }}"
    docker_container:
      name: rancher_agent
      image: rancher/agent
      docker_host: unix://var/run/docker.sock
      volumes:
        - /var/lib/rancher:/var/lib/rancher
      detach: true
      privileged: true
      env:
        CATTLE_AGENT_IP: "{{ansible_ec2_public_ipv4}}"
      command:
        "{{registration_url}}"
    become: true
    become_method: sudo

**Results:** 
TASK [add-rancher-host : run docker to add hosts] ******************************
changed: [54.157.8.247] => {"ansible_facts": {}, "changed": true}
Hosts do not appear in the Rancher UI. The rancher_agent eventually exits out.

**Expected:**
Host gets added to the Rancher UI. Agent launches all Rancher agent services.

**Comment by jurajseffer** [comment]
@ChienHuey Check docker logs for the container and daemon/syslog in /var/log/ on the host.

**Comment by ChienHuey** [comment]
INFO: Running Agent Registration Process, CATTLE_URL=[http://x.x.x.x:8080/v1
INFO: Attempting to connect to: [http://x.x.x.x:8080/v1
ERROR: [http://x.x.x.x:8080/v1 is not accessible

Not sure why it is showing as not accessible as I can curl htttp://x.x.x.x:8080/v1 without problem.

**Comment by jurajseffer** [comment]
I assume you're curling from the ec2 host and getting 200. I had bad security groups setup as well as missing VPC<->VPC routing when I had these problems. The agent uses web sockets as far as I know so make sure you can connect like that as well in case you're running via ELB.

**Comment by ChienHuey** [comment]
It appears that something with the way networking happens when using the docker_container ansible module is preventing the Rancher IP from being reached. My security groups are wide open to each EC2 instance and right now we're not using ELBs.

**Comment by aemneina** [comment]
@ChienHuey apologies for such a late reply, have you sorted this out?

**Comment by martinm82** [comment]
Actually I have a similar issue. Already tried to run an 1.2.2, 1.2.4 and 1.2.5 Rancher agent. The funny thing is that there are no errors in the daemon logs visible.
Running the docker run command directly on the host works like a charm but using the docker_container module from Ansible it just silently fails. Only the Docker image gets pulled.

**Comment by superseb** [comment]
It does not run the container at all? Can you share the debug output (`-vvv`)

**Comment by martinm82** [comment]
Ok, I managed to quickly see the container and these are the logs:
```
docker logs f4

INFO: Running Agent Registration Process, CATTLE_URL=http://rancher.mydomain.com/v1
INFO: Attempting to connect to: http://rancher.mydomain.tt3.com/v1
INFO: http://rancher.mydomain.com/v1 is accessible
INFO: Inspecting host capabilities
INFO: Boot2Docker: false
INFO: Host writable: true
INFO: Token: xxxxxxxx
INFO: Running registration
INFO: Printing Environment
INFO: ENV: CATTLE_ACCESS_KEY=6D3F7B5DE63B571039F9
INFO: ENV: CATTLE_HOME=/var/lib/cattle
INFO: ENV: CATTLE_HOST_LABELS=cloud=on-premise&environment=dev&type=raw
INFO: ENV: CATTLE_REGISTRATION_ACCESS_KEY=registrationToken
INFO: ENV: CATTLE_REGISTRATION_SECRET_KEY=xxxxxxx
INFO: ENV: CATTLE_SECRET_KEY=xxxxxxx
INFO: ENV: CATTLE_URL=http://rancher.mydomain.com/v1
INFO: ENV: DETECTED_CATTLE_AGENT_IP=10.117.225.49
INFO: ENV: RANCHER_AGENT_IMAGE=rancher/agent:v1.2.5
INFO: Deleting container rancher-agent
```

**Comment by superseb** [comment]
So it's deleting itself as far as I can tell, are you naming your container `rancher-agent` by any chance? Because that won't work.

**Comment by martinm82** [comment]
Yes, indeed, I am naming the container `rancher-agent`

**Comment by superseb** [comment]
Yep, thanks for reporting back.
