### ISSUE TITLE
1.2 to 1.3 migration very slow

### ISSUE THREAD

**Issue by underyx** [rancher/rancher#7273]
**Rancher Version:** uhhhh…

**Docker Version:** 1.12.1

**OS and where are the hosts located? (cloud, bare metal, etc):** RancherOS 0.6.1 on Scaleway VPS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single node, single agent, MySQL has a volume on the VPS's disk

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:** launch 1.2.2, stop it (after using it for a while), launch 1.3.0

**Results:** See lines like the following for a *veeeeery* long time (update took 27 minutes total, 14 minutes of which were just printing lines like the ones below, on a tiny Rancher instance, with 1 host, ~10 stacks and ~15 services total):

```
time="2017-01-03T23:54:35Z" level=info msg="Updating machine jsons for  [digitalocean amazonec2 azure digitalocean]"
time="2017-01-03T23:54:40Z" level=info msg="Creating schema machine, roles [service]" id=1ds384
time="2017-01-03T23:54:45Z" level=info msg="Creating schema host, roles [service]" id=1ds385
time="2017-01-03T23:54:47Z" level=info msg="Creating schema machine, roles [project member owner]" id=1ds386
time="2017-01-03T23:54:49Z" level=info msg="Creating schema host, roles [project member owner]" id=1ds387
time="2017-01-03T23:54:50Z" level=info msg="Creating schema machine, roles [admin user readAdmin]" id=1ds388
time="2017-01-03T23:54:51Z" level=info msg="Creating schema host, roles [admin user readAdmin]" id=1ds389
time="2017-01-03T23:54:52Z" level=info msg="Creating schema machine, roles [readonly]" id=1ds390
time="2017-01-03T23:54:54Z" level=info msg="Creating schema host, roles [readonly]" id=1ds391
time="2017-01-03T23:54:55Z" level=info msg="Updating machine jsons for  [azure amazonec2 azure digitalocean]"
time="2017-01-03T23:55:01Z" level=info msg="Creating schema machine, roles [service]" id=1ds392
time="2017-01-03T23:55:07Z" level=info msg="Creating schema host, roles [service]" id=1ds393
time="2017-01-03T23:55:10Z" level=info msg="Creating schema machine, roles [project member owner]" id=1ds394
time="2017-01-03T23:55:11Z" level=info msg="Creating schema host, roles [project member owner]" id=1ds395
time="2017-01-03T23:55:13Z" level=info msg="Creating schema machine, roles [admin user readAdmin]" id=1ds396
time="2017-01-03T23:55:14Z" level=info msg="Creating schema host, roles [admin user readAdmin]" id=1ds397
time="2017-01-03T23:55:16Z" level=info msg="Creating schema machine, roles [readonly]" id=1ds398
time="2017-01-03T23:55:17Z" level=info msg="Creating schema host, roles [readonly]" id=1ds399
time="2017-01-03T23:56:20Z" level=info msg=Event eventId=8013ecf2-50a9-49d4-b905-1c460c39f5e6 name="machinedriver.reactivate;handler=goMachineService-machine" resourceId=1md3
time="2017-01-03T23:56:22Z" level=info msg="Creating schema azureConfig, roles [service member owner project admin user readAdmin readonly restricted]" id=1ds400
time="2017-01-03T23:56:23Z" level=info msg="Updating machine jsons for  [azure amazonec2 azure digitalocean]"
time="2017-01-03T23:56:27Z" level=info msg="Creating schema machine, roles [service]" id=1ds401
time="2017-01-03T23:56:34Z" level=info msg="Creating schema host, roles [service]" id=1ds402
time="2017-01-03T23:56:35Z" level=info msg="Creating schema machine, roles [project member owner]" id=1ds403
time="2017-01-03T23:56:37Z" level=info msg="Creating schema host, roles [project member owner]" id=1ds404
time="2017-01-03T23:56:38Z" level=info msg="Creating schema machine, roles [admin user readAdmin]" id=1ds405
time="2017-01-03T23:56:40Z" level=info msg="Creating schema host, roles [admin user readAdmin]" id=1ds406
time="2017-01-03T23:56:42Z" level=info msg="Creating schema machine, roles [readonly]" id=1ds407
time="2017-01-03T23:56:43Z" level=info msg="Creating schema host, roles [readonly]" id=1ds408
```

**Expected:** I guess it should be faster? If it takes this long to migrate, that has to mean something is really unoptimized.

**Comment by deniseschannon** [comment]
If you are seeing those logs, then you already should be upgraded. This happens after the UI is completed.

**Comment by underyx** [comment]
I *think* I wasn't able to log in while these lines were being printed. I tried to, at least 3 times, and I kept getting redirected back to the login page.

Once these lines stopped being printed, I managed to log in normally.

**Comment by frekele** [comment]
See my logs of migration, many errors in this migration in my case.

Rancher server 1.2.2 to 1.3.0 with docker 1.12.5 + debian 8 64x(HVM) into aws ec2 + RDS (mysql 5.7.16) and slow.

I have 3 environments (catle) and upgrade all my infrastructure stacks, newtwork-service, healthcheck, scheduler and ipsec.

I hope this helps with the investigation.

rancher-server logs:
[rancher-migration-from-1.2.2-to-1.3.0-logs.txt](https://github.com/rancher/rancher/files/684856/rancher-migration-from-1.2.2-to-1.3.0-logs.txt)

**Comment by underyx** [comment]
@frekele your issue seems unrelated to this one

@deniseschannon as no more slowness reports came in, I'm not against closing this issue

**Comment by dimkk** [comment]
Same here, but it's fresh docker run
