### ISSUE TITLE
Easy way to add Authentication to kibana

### ISSUE THREAD

**Issue by sankaet** [rancher/rancher#7274]
Hi,

I am using Kibana from the Rancher catalog and I was wondering if there is an easy way to add basic authentication to it while deploying the service? 

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.2.2` Cattle: `v0.174.13` UI: `v1.2.40` |
|Access|`github` `admin`|
|Orchestration|`Cattle`|
|Route|`catalog-tab.index`|

**Comment by VAdamec** [comment]
Create your own catalog item with Kibana v5 and than authentication is part of product (X-Pack). If you need 2.x ELK just simple add Nginx/Apache as a proxy (LDAP/volume with pass hashes). Or you can buy Shield licence which will give you AA for legacy versions.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
