### ISSUE TITLE
Containers using convoy volumes (devicemapper) stuck in starting

### ISSUE THREAD

**Issue by djcenox** [rancher/rancher#7281]
**Rancher Version:1.2.2**

**Docker Version:1.12.5**

**OS and where are the hosts located? (cloud, bare metal, etc): VM, Centos7**

**Setup Details: Single Node**

**Environment Type: Cattle**

**Steps to Reproduce: Using covnoy volume driver for some services, work perfectly on 1.1.X, after upgrade looks unable to find out that container is Running**

**Results: Stuck in "Starting", unable to perform stack upgrades** 

**Expected: Container running **

**Comment by djcenox** [comment]
#6583 looks like same problem as this: the container are running with  /.r/r before entrypoint (ex. Postgres).

**Comment by djcenox** [comment]
With more testing I've found that having v1 .yml after started the catalog the converted v2 have in volumes the flag external:true. If I set external:false the container get the right state. In my environment the databases are hosted in a labelled host that runs convoy service on the host itself.

**Comment by aemneina** [comment]
@djcenox assuming this is resolved now? Please chime in if you want this reopened
