### ISSUE TITLE
[ui] 'Add a host' link in notification bar when no hosts are present after enabling auth does not work

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#7283]
**Rancher Version:**
1.3.0
**Docker Version:**
1.12.5
**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04, AWS
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node, internal DB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
n/a
**Steps to Reproduce:**
1) Start container of rancher/server:stable image
2) Open webinterface
3) Note the notification bar about 'Adding your first host' and the link on 'Add a host' is valid (http://ipaddress:8080/env/1a5/infra/hosts/add)
4) Go to Admin -> Access Control
5) Pick Local and create some dummy credentials
6) Click Enable Local Auth
7) It reloads to log you in and that breaks the 'Add a host' link (http://ipaddress:8080/env/undefined/infra/hosts/add)

**Results:** 
Invalid 'Add a host' link
**Expected:**
Valid 'Add a host' link. Another reload fixes the issue.

**Comment by tfiduccia** [comment]
Version - master 1/11
Verified fixed
