### ISSUE TITLE
Add a host link text disappears into background when you hover over it. 

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#7286]
**Rancher Version:** v1.3.0

**Steps to Reproduce:**
1.  Add new environment
2.  Go to Stacks page
3.  Hover over the "Add a host" link in the notification bar.

**Results:** Notice the link disappears because the hover color is same as the light blue background.

**Expected:**  Should probably not blend into background

**Comment by lvuch** [comment]
https://github.com/rancher/ui/pull/965 I've added a fix here, but I fixed this within lacsso a while back.
![screen shot 2017-01-04 at 2 34 32 pm](https://cloud.githubusercontent.com/assets/3013118/21660059/fcefa6ea-d28a-11e6-9267-38d1d8cdeb2a.png)

**Comment by lvuch** [comment]
https://github.com/rancher/lacsso/blob/master/app/styles/base/_color.scss line 35

**Comment by tfiduccia** [comment]
Version - master 1/17
Verified fixed
