### ISSUE TITLE
start_on_create: false does not work; services are started 

### ISSUE THREAD

**Issue by jzakrzeski** [rancher/rancher#7287]
**Rancher Version:** v1.2.2

**Docker Version:** 1.12.2

**OS and where are the hosts located? (cloud, bare metal, etc):** Ubuntu 14.04.4 LTS (3.13.0), cloud (AWS EC2, custom host)

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** Single-node, external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:**
`rancher stack create stack-name -f docker-compose.yml -r rancher-compose.yml`
Note that these are not v2 compose files, if that bears any effect

**Results:** 
Observe that services in the compose file will start regardless of `start_on_create: false` in rancher-compose.yml or lack of `--start` option in command

**Expected:**
Expect a stack to be created, but not started.

**Comment by peterloron** [comment]
Is there any update on this?

**Comment by Joeasaurus** [comment]
Next milestone maybe? :)

**Comment by vincent99** [comment]
This should work in 2.0 previews, though it's renamed `createOnly: true`.

**Comment by darkblinded** [comment]
@vincent99 can you provide me with an example for that? Or any documentation on this flag. I could not find anything and setting it like

```
services:
    container_name:
        (...)
        create_only: true
```

does not work for me.

**Comment by anjia0532** [comment]
how to fix this ? back to v1.6.10? or only net component ? or lb?

**Comment by flybd5** [comment]
ping. some of us are not yet planning to move to 2.0 and this is significant problem for us in 1.6.14.

**Comment by treyd** [comment]
Same issue for us as well, on 1.6, and need to create stacks with services and not start them immediately.

**Comment by StrongMonkey** [comment]
Can you try `rancher stack create --start=false` to see if that works for you?

**Comment by deniseschannon** [comment]
Similar to how docker compose was originally implemented, `rancher stack create` creates services. By passing in the `--start=false`, you can create services that are not automatically started in a stack. You should not use the `start_on_create` field in rancher-compose.

**Comment by flybd5** [comment]
"It's broken, don't use it that way."? No wonder we're moving away from Rancher. Sorry, but that's a lame way of dealing with this.

**Comment by AndrewSav** [comment]
@flybd5, well if you are a paying customer, I'm sure they'll be able to accommodate you, otherwise you get what you paid for. They are closing all 1.x non-critical issues now, as there is no point supporting 1.x when 2.x is out.

**Comment by flybd5** [comment]
That is an even lamer excuse. Care to bet on the odds this will become a
successful commercial product with this attitude? Not everything that goes
through your head should come out of your mouth.

**Comment by Joeasaurus** [comment]
Hahahah this is a joke. I guess it's a good thing rancher is moving to kubernetes so we can have less rancher in the way!
