### ISSUE TITLE
Edit/Upgrade load balancer with a HostIP, causes HostIP to be removed

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#7288]
**Rancher Version:** 1.3.0

**Steps to Reproduce:**
1.  Create a load balancer with a hostip
2.  Edit/Upgrade load balancer

**Results:** Notice the hostip is no longer visible. If you click the link for it to show up again, you will also notice that it's blank.

**Expected:**  HostIP should show up on edit/upgrade.

**Comment by tfiduccia** [comment]
Version - master 2.0 (8/2)
Verified fixed

**Comment by andrewsav-datacom** [comment]
@tfiduccia is it going to be fixed in 1.x?

**Comment by linkvt** [comment]
I would really appreciate if this could get fixed in the latest stable version and not only in the unreleased 2.0, as the [documentation](http://rancher.com/support-maintenance-terms/) also suggests that Rancher 1.6 will receive full maintenance support til Dec 1, 2018.
Thanks in advance.

**Comment by AndrewSav** [comment]
Well it's been three months since it's "Verified fixed" and it does not appear working in the latest 1.x May be @vincent99 can comment if @tfiduccia is not available?

**Comment by nosovk** [comment]
In v2 it's not fixed if you use workload instead of load balancer. HostIP in workload settings ignored/
[screen](https://monosnap.com/direct/cjH45RyasYjESXYATqHZdOnB3Yidga)

**Comment by wzrdtales** [comment]
@nosovk This is a different issue then. This is about container binding, the issue here is about the lb, which is a totally different thing. And the ingress in v2 works way better than the lb from rancher 1.6 though.
