### ISSUE TITLE
system containers should not call kubernetes-agent to get labels

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#7289]
**Rancher Version:**
1.2.2

**OS and where are the hosts located? (cloud, bare metal, etc):**
ROS 7.1

there seems to be a dependency chicken-egg problem where rancher-kubernetes-agent is queried for additional labels, by meta-data service, and meta-data couldnt start because the kubernetes-agent was failing to query metadata.

This prevents network services from being upgraded in k8s environments.

workaround:
stop rancher-kubernetes-agent
upgrade metadata-services
start up rancher-kubernetes-agent

**Comment by galal-hussein** [comment]
Rancher version: v1.4.0-rc3
Kubernetes: rancher/k8s:v1.5.2-rancher1-2

Verified the fix by stopping the rancher-kubernetes-agent and then tried to restart all system containers including the metadata service, and all the services restarted successfully.
