### ISSUE TITLE
[UI] LB state pill lacks left padding

### ISSUE THREAD

**Issue by willseward** [rancher/rancher#7290]
**Rancher Version:** 1.3.0

Chrome 55.0.2883.95 macOS

![screen shot 2017-01-04 at 12 50 08 pm](https://cloud.githubusercontent.com/assets/5386568/21654735/7ed1a460-d27c-11e6-98af-d036fca4d83f.png)

**Comment by tfiduccia** [comment]
Version - 1.3.0
For some reason this changed between 1.2.2 and 1.3.0 (and yes I checked 1.2.2 to make sure).  But it is indeed now cut off, all states are moved to the left, but you can really see it during activation and upgrading cause those have a blue background.

**Comment by lvuch** [comment]
https://github.com/rancher/ui/pull/965

**Comment by tfiduccia** [comment]
Version - master 1/17
Verified fixed
