### ISSUE TITLE
Give the option to pull docker images before stopping/recreating containers when upgrading stacks

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#7291]
**Rancher Version:**
1.2.2

upgrading stacks can be unpredictable at times in terms of maintenance windows. doing this can shrink the downtime significantly when cutting over (stopping container and starting a new one).

**Comment by chauffer** [comment]
Duplicate of #7200

**Comment by will-chan** [comment]
Using #7200 to track this enhancement.
