### ISSUE TITLE
[Machine] Launching Amazon Instance is very slow

### ISSUE THREAD

**Issue by jloisel** [rancher/rancher#7292]
**Rancher Version:** 1.3.1, 1.4.0-rc2, 1.2.2 (all affected ones)

**Docker Version:** 1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):**
Bare-metal

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node + Internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Start a new amazon machine. It's painfully slow, takes more than 10min to launch a single m4.xlarge machine with Docker and Rancher Agent image already preinstalled. (Custom AMI)

Once the API call to launch a new Amazon host is issued, it already takes 1 min to launch the instance on Amazon.

**Results:** 
It takes approximatively 4min with Rancher 1.1.4.

**Expected:**
It should not take longer than before. 

I guess this is linked to the Docker-machine package upgrade. As you said before, you just call docker-machine and let it do the job for you.

Which version is bundled with Rancher? Not sure you guys can do anything about this, but just in case let me know.

**Comment by jloisel** [comment]
I've made some investigations, and it seems like **the issue comes from Rancher, not docker-machine**. Here are some logs when launching an Amazon machine through Rancher. 

When launching an Amazon machine:
- through Rancher, it takes 7 minutes,
- Using docker-machine v0.9.0-rc2 directly, it takes 2 minutes.

I have used exactly the same command-line in both cases (taken from rancher/server logs). I have attached rancher server logs (with sensitive information removed). Please also note, i'm using a custom AMI which docker preinstalled, and the agent docker image has already been pulled.

[log.txt.zip](https://github.com/rancher/rancher/files/711399/log.txt.zip)

**Comment by ibuildthecloud** [comment]
@jloisel Can you by chance try rancher/server:v1.4.0-rc2?

**Comment by jloisel** [comment]
Did another interesting test, launching an amazon instance with the docker-machine inside the rancher/server container: it also takes 7min to launch an instance!

It's exactly the same version as the one used on my local machine directly (docker-machine version 0.9.0-rc2, build 7b19591).

**Comment by ibuildthecloud** [comment]
@jloisel well thats odd...

**Comment by jloisel** [comment]
Okay, going to try right now.

Sure, is it possible that having both the server and a node on my local machine somehow makes the network calls docker-machine sends "slow"?

**Comment by ibuildthecloud** [comment]
@jloisel Shouldn't make any difference.

**Comment by jloisel** [comment]
Okay, i'm going to try this now. Give me a couple of minutes :)

**Comment by jloisel** [comment]
Right now testing on v1.4.0-rc2, still dead slow:

> time="2017-01-17T15:28:50Z" level=info msg="Creating Machine" eventId=f67fe418-b987-4148-b0cc-c0572f819579 resourceId=1ph13 
time="2017-01-17T15:28:50Z" level=info msg="Cmd slice: [create -d amazonec2 --amazonec2-access-key xxxx --amazonec2-ami ami-ed5f9382 --amazonec2-block-duration-minutes 0 --amazonec2-device-name /dev/sda1 --amazonec2-instance-type t2.medium --amazonec2-region eu-central-1 --amazonec2-retries 5 --amazonec2-root-size 16 --amazonec2-secret-key xxx --amazonec2-security-group rancher-machine --amazonec2-spot-price 0.50 --amazonec2-ssh-user ubuntu --amazonec2-subnet-id subnet-d3ab07ba --amazonec2-volume-type gp2 --amazonec2-vpc-id vpc-98bb63f1 --amazonec2-zone a essential-defendant]" 
time="2017-01-17T15:29:03Z" level=info msg="stdout: Creating CA: /var/lib/cattle/machine/ec24d2a5-670e-4893-9dff-7ae3f39981fc/certs/ca.pem" resourceId: =1ph13 
time="2017-01-17T15:29:04Z" level=info msg="stdout: Creating client certificate: /var/lib/cattle/machine/ec24d2a5-670e-4893-9dff-7ae3f39981fc/certs/cert.pem" resourceId: =1ph13 
time="2017-01-17T15:29:04Z" level=info msg="stdout: Running pre-create checks..." resourceId: =1ph13 
time="2017-01-17T15:29:09Z" level=info msg="stdout: Creating machine..." resourceId: =1ph13 
time="2017-01-17T15:29:14Z" level=info msg="stdout: (essential-defendant) Launching instance..." resourceId: =1ph13 
time="2017-01-17T15:30:15Z" level=info msg="stdout: Waiting for machine to be running, this may take a few minutes..." resourceId: =1ph13 
time="2017-01-17T15:30:20Z" level=info msg="stdout: Detecting operating system of created instance..." resourceId: =1ph13 
time="2017-01-17T15:30:20Z" level=info msg="stdout: Waiting for SSH to be available..." resourceId: =1ph13 
time="2017-01-17T15:30:55Z" level=info msg="stdout: Detecting the provisioner..." resourceId: =1ph13 
time="2017-01-17T15:31:00Z" level=info msg="stdout: Provisioning with ubuntu(systemd)..." resourceId: =1ph13 
time="2017-01-17T15:32:14Z" level=info msg="stdout: Installing Docker..." resourceId: =1ph13 
time="2017-01-17T15:32:48Z" level=info msg="stdout: Copying certs to the local machine directory..." resourceId: =1ph13 
time="2017-01-17T15:33:07Z" level=info msg="stdout: Copying certs to the remote machine..." resourceId: =1ph13

**Comment by jloisel** [comment]
Finally running after 8 minutes:

> time="2017-01-17T15:34:03Z" level=info msg="stdout: Setting Docker configuration on the remote daemon..." resourceId: =1ph13 
time="2017-01-17T15:34:55Z" level=info msg="stdout: Checking connection to Docker..." resourceId: =1ph13 
time="2017-01-17T15:35:18Z" level=info msg="stdout: Docker is up and running!" resourceId: =1ph13 
time="2017-01-17T15:35:18Z" level=info msg="stdout: To see how to connect your Docker Client to the Docker Engine running on this virtual machine, run: docker-machine env essential-defendant" resourceId: =1ph13 
time="2017-01-17T15:35:18Z" level=info msg="Machine Created" machineExternalId=ec24d2a5-670e-4893-9dff-7ae3f39981fc resourceId=1ph13 
time="2017-01-17T15:35:18Z" level=info msg="Creating and uploading extracted machine config" resourceId=1ph13 
time="2017-01-17T15:35:18Z" level=info msg="Machine config file created and encoded." destFile="/var/lib/cattle/machine/ec24d2a5-670e-4893-9dff-7ae3f39981fc/essential-defendant.tar.gz" resourceId=1ph13 
time="2017-01-17T15:35:18Z" level=info msg="Activating Machine" eventId=bc01b1b0-f07c-4acf-99e4-ba6b9552ba1c resourceId=1ph13 
time="2017-01-17T15:35:29Z" level=info msg="pulling rancher/agent:v1.1.3 image." 
time="2017-01-17T15:35:30Z" level=info msg="Container created for machine" containerId=aa1010719b7d1f15d1a098fa73049f1c3be57183fcb75319a4328785ed88ac0c machineId=1ph13 resourceId=1ph13 
time="2017-01-17T15:35:32Z" level=info msg="Rancher-agent for machine started" containerId=aa1010719b7d1f15d1a098fa73049f1c3be57183fcb75319a4328785ed88ac0c machineExternalId=ec24d2a5-670e-4893-9dff-7ae3f39981fc resourceId=1ph13 
time="2017-01-17T15:35:32Z" level=info msg="Creating and uploading extracted machine config" resourceId=1ph13 
time="2017-01-17T15:35:32Z" level=info msg="Machine config file created and encoded." destFile="/var/lib/cattle/machine/ec24d2a5-670e-4893-9dff-7ae3f39981fc/essential-defendant.tar.gz" resourceId=1ph13 
2017-01-17 15:36:06,553 ERROR [:] [] [] [] [TaskScheduler-2] [i.c.p.a.s.ping.impl.PingMonitorImpl ] Failed to get ping from agent [44] count [3] 
time="2017-01-17T15:36:10Z" level=info msg="Handling backend connection request." 
time="2017-01-17T15:36:10Z" level=info msg="Registering backend for host ec24d2a5-670e-4893-9dff-7ae3f39981fc with session ID 6cf4d129-711a-47ec-8dc9-3fea50eba99f."

Remember it's a custom AMI with latest docker (1.12.6) and agent v1.1.3 already pulled to speed up machine launch.

Also, I don't have any problem when launching a digitalocean instance. Those instances show up usually in less than 4 minutes.

**Comment by jloisel** [comment]
The issue has first appeared in v1.2.0. This is why we are still stuck with v1.1.4 right now.

**Comment by jloisel** [comment]
Trying right now from an Amazon EC2 instance used a rancher server. It's way faster. It seems like the issue is related to my local machine, but I cannot explain what's happening.

**Comment by jloisel** [comment]
Tested again with rancher hosted on an Amazon EC2 instance, v1.4.0-rc2. It starts the machine in a whopping 1min52sec. I'm going to try to figure out why it's slow on my local machine. I'm closing this bug for now as it seems to be a configuration issue on my local machine.

**Comment by vincent99** [comment]
Would be interested to hear what it was if you figure it out. There is a `--debug` flag  that might be  some help.

The only thing I can think of is maybe there's some issue with DNS resolution using cgo vs native... As you noted it is the standard rc2 code, but we do compile it ourselves (since most of the time we end up shipping from a random master commit).

Sidebar: I'd like to get the rest of the AWS regions into 1.4 but nobody seems interested in merging your (or any) PRs there anymore...

**Comment by jloisel** [comment]
Maybe it's because I have updated docker0 bridge CIDR (was trying to figure out how to change it for a client). There is no firewall, no iptables mess.

Would like new AWS regions in docker-machine too, nathan seems in vacation since he didn't merged any PR for a while.
