### ISSUE TITLE
Public Endpoints from user LB is not removed even after the user project is not linked to the admin project anymore.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#7293]
Rancher Version: Build from master

Steps to reproduce the problem:
Create an admin env - "admin".
Deploy a GLB.
Create a user env - "user1".
For "admin" env , create a project link to "user1".
Create a user LB for a service.

This results in the targets being programmed in GLB and public endpoints of user LB being updated with host and port of GLB as expected.

For "admin" env , remove the existing project link to "user1".  
This results in the programmed targets from this project being removed from GLB as expected.
But the public endpoints on user LB continues to be present.

Expected Behavior:
Public endpoints on user LB should be deleted.

**Comment by alena1108** [comment]
Closing as we are dropping support for account links in 2.0
