### ISSUE TITLE
Public Endpoints from user LB is not removed when service is deactivated.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#7294]
Rancher Version: Build from master

Steps to reproduce the problem:
Create an admin env - "admin".
Deploy a GLB.
Create a user env - "user1".
For "admin" env , create a project link to "user1".
Create a user LB for a service - s1.

This results in the targets being programmed in GLB and public endpoints of user LB being updated with host and port of GLB as expected.

Deactivate the service S1. In GLB , the backend continues to be programmed with no targets attached to it.
But the public endpoints on user LB continues to be present.

Expected Behavior:
Public endpoints on user LB should be deleted at this point.

**Comment by withinboredom** [comment]
Best bug ever! Finally, it behaves as expected...

**Comment by alena1108** [comment]
@sangeethah test with alena1108/lb-service-haproxy:test

**Comment by sangeethah** [comment]
Tested with Rancher server build from master
LB image - alena1108/lb-service-haproxy:test

This issue is still reproducible.
Public Endpoints from user LB is not removed when service is deactivated.
The one change I see now is that in GLB , the backend is removed ( Earlier the backend usedto be programmed with no targets attached to it).But the public endpoints on user LB continues to be present.

**Comment by alena1108** [comment]
@sangeethah the fix will be just for LB being deactivated. Public endpoints will be removed only when LB service is deactivated.

**Comment by alena1108** [comment]
Closing as "works as expected"
