### ISSUE TITLE
Lb continues to be functional(targets continue to be programmed in GLB) even after it is deactivated.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#7295]
Rancher Version: Build from master

Steps to reproduce the problem:
Create an admin env - "admin".
Deploy a GLB.
Create a user env - "user1".
For "admin" env , create a project link to "user1".
Create a user LB for a service S1.

This results in the targets being programmed in GLB and public endpoints of user LB being updated with host and port of GLB as expected.

Deactivate user LB.
Targets continue to be programmed in GLB and the Lb ip address is functional.

Expected Behavior:
Targets should be removed from GLB and the Lb should not be functional.

**Comment by alena1108** [comment]
@sangeethah test with alena1108/lb-service-haproxy:test

**Comment by sangeethah** [comment]
Rancher server version - Build from master
Lb image used - alena1108/lb-service-haproxy:test

When user Lb is deactivated , frontend and backend entries are removed from the GLB and LB is not functional. When Lb is accessed , we get a "Connection refused." error.

Also Public Endpoints pointing to GLB is not present for the user LB anymore.

When user Lb is activated again ,frontend and backend entries for this user LB get programmed in GLB and LB is functional.Public Endpoints pointing to GLB is now present for the user LB.
