### ISSUE TITLE
In the same host, the container cannot access the exposed ports of the other container  or itself via the host's IP

### ISSUE THREAD

**Issue by yeruisen** [rancher/rancher#7297]
**Rancher Version:**

1.2.2

**Docker Version:**

1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):**

bare metal

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

Swarm

**Steps to Reproduce:**

- Create a container A that publishes a port.
- Create another container B and `docker run exec` into the container.
- In the B try to connect to A of the service via the IP of the host .it does NOT work
- In the A try to connect to itselt via the host IP.

**Results:** 

In the same host, the container cannot access the exposed ports of the other container  or itself via the host's IP.

**Expected:**

**Comment by deniseschannon** [comment]
What version of network services are you running? We made some fixes that should resolve this.

**Comment by yeruisen** [comment]
@deniseschannon 
![image](https://cloud.githubusercontent.com/assets/12295648/21670531/d8a08b54-d34f-11e6-935e-a3e3151e5617.png)
![image](https://cloud.githubusercontent.com/assets/12295648/21670557/048efba6-d350-11e6-8441-2d2610bbfc52.png)

**Comment by FishGel** [comment]
@deniseschannon  the same with me.

**Rancher Version:**

`1.2.2`

**Docker Version:**

`1.12.3`

**OS and where are the hosts located? (cloud, bare metal, etc):**

bare metal

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

Swarm

**Steps to Reproduce:**

1、click  **Add Stack** button
2、prase below docker-compose.yml file content
3、click **Create** button
4、can's not telnet itsself port 8001 by command｀192.168.1.23 8001  ｀

![image](https://cloud.githubusercontent.com/assets/7518880/21673052/7441346c-d361-11e6-84c9-b8ce8bc17608.png)

![image](https://cloud.githubusercontent.com/assets/7518880/21673005/31294e58-d361-11e6-91cd-530f3f0d7def.png)

**Results:**

can's not telnet itsself port 8001 by telnet ｀192.168.1.23 8001  ｀

**Expected:**


## docker-componse content 
```

version: '2'
services:
  wordpress:
    image: wordpress:latest
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: wordpress
    ports:
    - 8001:80/tcp
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_USER: wordpress
```
## run docker inspect command result
```
[root@node-1 ~]# docker inspect d8e00352ce1d
[
    {
        "Id": "d8e00352ce1df94e52c8186bc11f77686f6dc0f2c5efc00b6b92a1280f248b46",
        "Created": "2017-01-05T07:11:41.450717405Z",
        "Path": "/.r/r",
        "Args": [
            "docker-entrypoint.sh",
            "apache2-foreground"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 9219,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2017-01-05T07:28:07.825039289Z",
            "FinishedAt": "2017-01-05T07:28:07.196549741Z"
        },
        "Image": "sha256:c2898ebe21b8c955a7e961c156ef9de92fecd9ee61804db336e974b878c8f42d",
        "ResolvConfPath": "/var/lib/docker/containers/d8e00352ce1df94e52c8186bc11f77686f6dc0f2c5efc00b6b92a1280f248b46/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/d8e00352ce1df94e52c8186bc11f77686f6dc0f2c5efc00b6b92a1280f248b46/hostname",
        "HostsPath": "/var/lib/docker/containers/d8e00352ce1df94e52c8186bc11f77686f6dc0f2c5efc00b6b92a1280f248b46/hosts",
        "LogPath": "/var/lib/docker/containers/d8e00352ce1df94e52c8186bc11f77686f6dc0f2c5efc00b6b92a1280f248b46/d8e00352ce1df94e52c8186bc11f77686f6dc0f2c5efc00b6b92a1280f248b46-json.log",
        "Name": "/r-wd-wordpress-1-e7aae6c2",
        "RestartCount": 0,
        "Driver": "devicemapper",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "rancher-cni:/.r:ro"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "none",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": [],
            "CapDrop": [],
            "Dns": [
                "169.254.169.250"
            ],
            "DnsOptions": null,
            "DnsSearch": [
                "wd.rancher.internal",
                "wordpress.wd.rancher.internal",
                "rancher.internal"
            ],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 2,
            "Memory": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": -1,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0
        },
        "GraphDriver": {
            "Name": "devicemapper",
            "Data": {
                "DeviceId": "4156",
                "DeviceName": "docker-253:0-8610282247-d46b49dd80178d1a876ee3539ccf8937f909d586bc9d2ff2c144c5db05ecda61",
                "DeviceSize": "10737418240"
            }
        },
        "Mounts": [
            {
                "Name": "rancher-cni",
                "Source": "/var/lib/docker/volumes/rancher-cni/_data",
                "Destination": "/.r",
                "Driver": "local",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            },
            {
                "Name": "5bd8ab09a559cd5dd56ce08ea72d3d46f60982818c0abe5c6dc40aeed901c974",
                "Source": "/var/lib/docker/volumes/5bd8ab09a559cd5dd56ce08ea72d3d46f60982818c0abe5c6dc40aeed901c974/_data",
                "Destination": "/var/www/html",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],
        "Config": {
            "Hostname": "d8e00352ce1d",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "80/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "WORDPRESS_DB_PASSWORD=wordpress",
                "WORDPRESS_DB_HOST=db:3306",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "PHPIZE_DEPS=autoconf \t\tfile \t\tg++ \t\tgcc \t\tlibc-dev \t\tmake \t\tpkg-config \t\tre2c",
                "PHP_INI_DIR=/usr/local/etc/php",
                "APACHE_CONFDIR=/etc/apache2",
                "APACHE_ENVVARS=/etc/apache2/envvars",
                "PHP_EXTRA_BUILD_DEPS=apache2-dev",
                "PHP_EXTRA_CONFIGURE_ARGS=--with-apxs2",
                "PHP_CFLAGS=-fstack-protector-strong -fpic -fpie -O2",
                "PHP_CPPFLAGS=-fstack-protector-strong -fpic -fpie -O2",
                "PHP_LDFLAGS=-Wl,-O1 -Wl,--hash-style=both -pie",
                "GPG_KEYS=0BD78B5F97500D450838F95DFE857D9A90D90EC1 6E4F6AB321FDC07F2C332E3AC2BF0BC433CFC8B3",
                "PHP_VERSION=5.6.29",
                "PHP_URL=https://secure.php.net/get/php-5.6.29.tar.xz/from/this/mirror",
                "PHP_ASC_URL=https://secure.php.net/get/php-5.6.29.tar.xz.asc/from/this/mirror",
                "PHP_SHA256=0ff352a433f73e2c82b0d5b283b600402518569bf72a74e247f356dacbf322a7",
                "PHP_MD5=190bf5b52d1fc68d5500a8cdc7e33164",
                "WORDPRESS_VERSION=4.7",
                "WORDPRESS_SHA1=1e14144c4db71421dc4ed22f94c3914dfc3b7020"
            ],
            "Cmd": [
                "apache2-foreground"
            ],
            "Healthcheck": {},
            "Image": "wordpress:latest",
            "Volumes": {
                "/var/www/html": {}
            },
            "WorkingDir": "/var/www/html",
            "Entrypoint": [
                "/.r/r",
                "docker-entrypoint.sh"
            ],
            "OnBuild": null,
            "Labels": {
                "io.rancher.cni.network": "ipsec",
                "io.rancher.cni.wait": "true",
                "io.rancher.container.ip": "10.42.243.23/16",
                "io.rancher.container.name": "wd-wordpress-1",
                "io.rancher.container.uuid": "e7aae6c2-9598-4182-bda2-76c6797da43a",
                "io.rancher.project.name": "wd",
                "io.rancher.project_service.name": "wd/wordpress",
                "io.rancher.service.deployment.unit": "c721e447-72ec-47e0-971d-5fbcd528e39f",
                "io.rancher.service.launch.config": "io.rancher.service.primary.launch.config",
                "io.rancher.stack.name": "wd",
                "io.rancher.stack_service.name": "wd/wordpress"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "39a474b8c24fb16397cbf4a283a37d21cf75d7abbfdbb0d3133e90c032de2dd0",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "/var/run/docker/netns/39a474b8c24f",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "none": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "84cbafc10200befa2de882c0a9e6075a5c48256892fd40867045742e31ac2c81",
                    "EndpointID": "5dd089efcb136374a31e4c20745dbc4fc518aeeff0db61e076d05e642c71ca1f",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": ""
                }
            }
        }
    }
]
```

## run docker info result
```
[root@node-1 ~]# docker version
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        
 OS/Arch:      linux/amd64
[root@node-1 ~]# docker info
Containers: 19
 Running: 18
 Paused: 0
 Stopped: 1
Images: 216
Server Version: 1.12.3
Storage Driver: devicemapper
 Pool Name: docker-253:0-8610282247-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 35.03 GB
 Data Space Total: 107.4 GB
 Data Space Available: 72.35 GB
 Metadata Space Used: 38.97 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.109 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.135-RHEL7 (2016-09-28)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host overlay bridge
Swarm: active
 NodeID: 20bxwgfa4g94v2ulutpxs4c6n
 Is Manager: true
 ClusterID: 01w3v659roomcfcfhibhmtne5
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.1.23
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.9.0-1.el7.elrepo.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 32
Total Memory: 62.87 GiB
Name: node-1
ID: MVS5:YUPK:UWOK:JFWK:GG4X:JSJF:AAUN:574K:AZKA:6CVB:EGFQ:BCAA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Comment by leodotcloud** [comment]
@yeruisen I tested with your `docker-compose.yml` file and it's working as expected. Can you finish the wordpress installation from the UI and then try `curl http://your_ip:8001`? You should be able to see the wordpress page. 

Is this an upgraded setup from previous version? Can you login to your host and get the output of the `iptables-save` command?

**Comment by yeruisen** [comment]
@leodotcloud 
yes,  `curl http://your_ip:8001`,it is ok.
but when you telnet `hostIP  8001` in container wordpress , it is not work.

**Comment by yeruisen** [comment]
@leodotcloud 
my problem is `In the same host, the container cannot access the exposed ports of the other container or itself via the host's IP`，not  `Outside the container access the exposed ports`

**Comment by yeruisen** [comment]
@leodotcloud 
@deniseschannon 
**I think the reason for this is that the container is not routed to the host. Please pay attention to this problem**

**Comment by yeruisen** [comment]
@leodotcloud 
It is not work in Cattle env, too.

![image](https://cloud.githubusercontent.com/assets/12295648/21756815/1d5af482-d661-11e6-9ac7-835c6f30a36d.png)

![image](https://cloud.githubusercontent.com/assets/12295648/21756858/70fbd5f2-d661-11e6-9a03-89f14871503a.png)


![image](https://cloud.githubusercontent.com/assets/12295648/21756826/3812e8ac-d661-11e6-8ed6-2e26f086147d.png)

![image](https://cloud.githubusercontent.com/assets/12295648/21756875/94853a7c-d661-11e6-8120-1de347b940f7.png)

**Comment by tiangolo** [comment]
I will cross-post my solution for a similar problem that I posted here: https://github.com/docker/docker/issues/16137#issuecomment-271615192 as it seems it could also be relevant in this issue (this is one of the issues I found and followed while investigating my problem).

I'm sorry if any of you consider it "spam", but as it is a possible solution I think it's best to share it.

---

**Note**: How I fixed it is a section below.

I was having issues with `firewalld` and Docker, specifically with Rancher v1.2 in CentOS 7.

Rancher needs a container to be able to communicate to the host via it's external (possibly local) IP address.

It was a requirement to have `firewalld` enabled and working.

## Environment

**OS**: `CentOS Linux release 7.3.1611 (Core)`

**Kernel** updated manually using "elrepo" to be able to use Overlay2 (`devicemapper` gave us several problems), although I don't think the kernel or the back end store is related to the problem: `4.9.0-1.el7.elrepo.x86_64`

**Docker**: 

```
Containers: 9
 Running: 9
 Paused: 0
 Stopped: 0
Images: 29
Server Version: 1.12.5
Storage Driver: overlay2
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.9.0-1.el7.elrepo.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 56
Total Memory: 125.7 GiB
Name: node19
ID: 3SC3:MCMU:PYSL:IBPE:4LPY:OYAG:RUUF:QMQ7:JWDS:5VRI:V7IS:KUYC
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8
[root@node19 cerebro]# uname -r
4.9.0-1.el7.elrepo.x86_64
[root@node19 cerebro]# docker info
Containers: 9
 Running: 9
 Paused: 0
 Stopped: 0
Images: 29
Server Version: 1.12.5
Storage Driver: overlay2
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.9.0-1.el7.elrepo.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 56
Total Memory: 125.7 GiB
Name: node19
ID: 3SC3:MCMU:PYSL:IBPE:4LPY:OYAG:RUUF:QMQ7:JWDS:5VRI:V7IS:KUYC
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8
```

**`firewalld` is enabled**: 

```
systemctl status firewalld.service
● firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/usr/lib/systemd/system/firewalld.service; enabled; vendor preset: enabled)
   Active: active (running) since jue 2017-01-05 18:04:12 COT; 4 days ago
     Docs: man:firewalld(1)
 Main PID: 24584 (firewalld)
   Memory: 46.5M
   CGroup: /system.slice/firewalld.service
           └─24584 /usr/bin/python -Es /usr/sbin/firewalld --nofork --nopid

ene 10 10:08:23 node19 firewalld[24584]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t nat -D PREROUTING' failed:
ene 10 10:08:23 node19 firewalld[24584]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t nat -D OUTPUT' failed:
ene 10 10:08:23 node19 firewalld[24584]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t filter -X DOCKER' failed:
ene 10 10:08:23 node19 firewalld[24584]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t filter -X DOCKER-ISOLATION' failed:
ene 10 10:08:23 node19 firewalld[24584]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t nat -n -L DOCKER' failed:
ene 10 10:08:23 node19 firewalld[24584]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t filter -C DOCKER-ISOLATION -j RETURN' failed:
ene 10 10:08:23 node19 firewalld[24584]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t nat -C DOCKER -i docker0 -j RETURN' failed:
ene 10 10:08:23 node19 firewalld[24584]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -D FORWARD -i docker0 -o docker0 -j DROP' failed:
ene 10 10:08:23 node19 firewalld[24584]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t nat -C PREROUTING -m addrtype --dst-type LOCAL -j DOCKER' failed:
ene 10 10:08:23 node19 firewalld[24584]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t nat -C OUTPUT -m addrtype --dst-type LOCAL -j DOCKER ! --dst 127.0.0.0/8' failed:
```

...but those errors in `firewalld` are expected as pointed out in: https://github.com/docker/docker/issues/16137#issuecomment-269398488


## The problem

`firewalld` uses `iptables` and IPtables rules under the hood, but the way it "works" is with different "zones", with different levels of access (as I understand, different sets of `iptables` rules for each "zone").

The `docker0` network interface is not assigned to any zone, so, some of its communications are blocked.

In my case, running the Rancher "agent" (a Docker container) with `firewalld` active gives errors about not being able to connect to the Rancher server (via it's external IP, in where the Rancher server, another container, is listening to). But with `firewalld` inactive, it works normally.

To make it worse, in all the systems I have tested (bare metal and Linode VPS) the `docker0` interface's `firewalld` zone cannot be modified using `firewalld` commands, because it is "controlled" by the "NetworkManager".

## The fix

* Check the `firewalld` "zone" asigned to the Docker interface:

```bash
firewall-cmd --get-zone-of-interface=docker0
```

* If it says "no zone", you need to add it to the `trusted` zone

```bash
firewall-cmd --permanent --zone=trusted --change-interface=docker0
```

* If the previous command returns a message like:

```
The interface is under control of NetworkManager, setting zone to 'trusted'.
success
```

...it means that `firewalld` cannot control the zone of the interface (even if it says "success").

You can check that the zone was not assigned by running again:

```bash
firewall-cmd --get-zone-of-interface=docker0
```

* If that's the case, you need to use the "NetworkManager" and restart the `docker0` interface, so first stop the `docker` daemon:

```bash
systemctl stop docker
```

* Now use the "NetworkManager" command line interface to set the zone of the `docker0` interface to `trusted`:

```bash
nmcli connection modify docker0 connection.zone trusted
```

* Now turn the `docker0` interface off:

```bash
ifdown docker0
```

* And turn it on again:

```bash
ifup docker0
```

* And check that the `firewalld` zone assigned to the interface `docker0` is "trusted":

```bash
firewall-cmd --get-zone-of-interface=docker0
```
...now it should return `trusted` instead of `no zone`

* Now you can start Docker again:

```bash
systemctl start docker
```

* Check if the problem you had was solved

## References

http://unix.stackexchange.com/a/225845/90829

[Introduction to FirewallD on CentOS - Linode](https://www.linode.com/docs/security/firewalls/introduction-to-firewalld-on-centos)

[RedHat forums (in the comments is mentioned the `nmcli`)](https://access.redhat.com/discussions/1455033)

[RedHat docs for `nmcli`](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Networking_Guide/sec-Using_the_NetworkManager_Command_Line_Tool_nmcli.html)

**Comment by yeruisen** [comment]
@tiangolo 
Thank you.
I will try it.

**Comment by yeruisen** [comment]
@tiangolo 
I met an interesting things.
When I use centos 7.2 of linux kernel 3.10 and docker version 1.11, everything is ok. but in docker version 1.12.x , #6861 this problem has emerged. and when I upgrade kernel to 4.9, the issue  #6861 does not appear , Meanwhile，this issue #7297 is emerge.

To sum it up.
rancher 1.2.x + centos 7.2 + kernel 3.10 + docker version 1.11 ,all is work.

rancher 1.2.x + centos 7.2 + kernel 3.10 + docker version 1.12.x  , #6861

rancher 1.2.x + centos 7.2 + kernel 4.9 + docker version 1.12.x , #7297

**Comment by morlay** [comment]
@yeruisen #6861 is another issue, same as #6922, so we have to downgrade docker to 1.12.1 after docker team fix it. (1.12.6 still have it 😢 )

Rancher 1.2.x or 1.3.x + CentOS 7.x + Kernel 3.10 + docker version 1.12.1 works well,
following settings provided by @tiangolo

**Comment by tiangolo** [comment]
Very interesting to know @yeruisen, thanks for sharing your findings.

I'm glad it worked for you @morlay!

**Comment by leodotcloud** [comment]
@yeruisen I have posted my test results here for similar setup using expose ports: https://github.com/rancher/rancher/issues/7474#issuecomment-273909724

**Comment by yeruisen** [comment]
@leodotcloud 
Thank you for your test results. Now I have solved the problem. I think it`s due to kernel.

**Comment by warroyo** [comment]
I am having this same issue on rancher v1.3.1 docker version 1.12.1 and centos7.2 kernel 3.10.

I was using docker 1.12.6 but downgraded per @morlay advice. I am not running firewalld but still I am unable to connect to other containers runnning on the same host using the host ip:port.

any idea why this might be? it looks like @tiangolo solution is only applicable if firewalld is running.

**Comment by leodotcloud** [comment]
@warroyo Per @aemneina's experience with other customer setups and issues, here is some info:

bad kernel: `3.10.0-327.10.1.el7.x86_64`
good kernel: `3.10.0-514.2.2.el7.x86_64`

So is your kernel version > good kernel's version?

**Comment by warroyo** [comment]
@leodotcloud thanks for the information I am unfortunately running `3.10.0-327.36.2.el7.x86_64`. I will try upgrading, thank you

**Comment by gad0lin** [comment]
It doesn't work on my side :/ I don't see 1514 or 9200 ports open for container: sebp/elk:520.

My setup:
Centos, build from Centos 7 1611 (build from: "http://ftp.usf.edu/pub/centos/7.3.1611/isos/x86_64/CentOS-7-x86_64-Minimal-1611.iso",
"27bd866242ee058b7a5754e83d8ee8403e216b93d130d800852a96f41c34d86a")

Kernel: 3.10.0-514.6.1.el7.x86_64

Rancher Server: 1.4.0rc6
rancher/net:v0.8.7
rancher/net:holder
rancher/healthcheck:v0.2.3
rancher/net:v0.8.7
rancher/dns:v0.13.3
rancher/network-manager:v0.4.5
rancher/metadata:v0.7.0
rancher/agent:v1.2.0

Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:20:01 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:20:01 2017
 OS/Arch:      linux/amd64

**Comment by gad0lin** [comment]
@tiangolo i have stopped firewalld with 
```
 systemctl stop firewalld.service
```
and restarted docker and still don't see the port open. I have even rebuilt and installed docker-engine-1.10.3-1.el7.centos on it and still see the issue.  I don't see port open on the host (tested with netstat -nlp and telnet).


I have also installed 1.11. But rancher was showing that this version is not supported, so I have switched to 1.10.3 (I see now in forums that people are using 1.11 version and its working).

**Comment by yeruisen** [comment]
@gad0lin Okay, it is weird.you can try my opinion.

**Comment by tiangolo** [comment]
How are you checking the ports @gad0lin ? With something like:

```bash
netstat -plutn 
```
?

Because Rancher doesn't attach any container directly to the host ports, Rancher creates IPTables rules that redirect the traffic and adapt to the changes live.

So you won't see containers managed by Rancher attach directly to ports.

**Comment by leodotcloud** [comment]
@gad0lin Are you still seeing this issue?

**Comment by superseb** [comment]
Please report back if you are still experiencing issues.
