### ISSUE TITLE
Suggest adding a `user` on the page of Swarm

### ISSUE THREAD

**Issue by yeruisen** [rancher/rancher#7300]
![image](https://cloud.githubusercontent.com/assets/12295648/21673366/8dc11ab8-d363-11e6-9267-20e639ce8662.png)

**like this:**

![image](https://cloud.githubusercontent.com/assets/12295648/21673408/b7ff5eac-d363-11e6-85c5-7d350717a9dd.png)

**Comment by superseb** [comment]
Everything will be launched/managed through Portainer, not much we can do here.
