### ISSUE TITLE
Execute shell from Host view to a Kubernetes container fails

### ISSUE THREAD

**Issue by chrisurwin** [rancher/rancher#7302]
**Rancher Version:**
1.3
**Steps to Reproduce:**
Run a pod under Kubernetes and go to the host view, choose execute shell
**Results:** 
![image](https://cloud.githubusercontent.com/assets/13744596/21675780/ef5b6794-d32a-11e6-9adf-142e883e45ab.png)

**Expected:**
It to go to shell, this works if going to the same container from the container view
![image](https://cloud.githubusercontent.com/assets/13744596/21675808/108c20f2-d32b-11e6-9b13-915f5b5834d5.png)

**Comment by tfiduccia** [comment]
Version 1.3.0
I checked with both wordpress and guestbook and the main containers are having this problem.  The sidekick containers work ok, just the main container is erring.

**Comment by wlan0** [comment]
This is the shim container, and users are not supposed to execute into this container.
