### ISSUE TITLE
Rancher cannot recognise local tiller image

### ISSUE THREAD

**Issue by HackerWilson** [rancher/rancher#7303]
when I pulled tiller:v2.1.3 and taged it as `gcr.io/kubernetes-helm/tiller:v2.1.3`, the tiller container status is still `Waiting`.

the message is:
```
Error syncing pod, skipping: failed to "StartContainer" for "tiller" with ErrImagePull: "image pull failed for gcr.io/kubernetes-helm/tiller:v2.1.3, this may be because there are no credentials on this request.  details: (Error response from daemon: {\"message\":\"Get https://gcr.io/v1/_ping: dial tcp 64.233.189.82:443: i/o timeout\"})"
```
when I delete the tiller deployment and pods, then init success.
```
$ helm  init
$HELM_HOME has been configured at $HOME/.helm.

Tiller (the helm server side component) has been installed into your Kubernetes Cluster.
Happy Helming!
```
but I still cannot use helm...
```
$ helm version
Client: &version.Version{SemVer:"v2.1.3", GitCommit:"5cbc48fb305ca4bf68c26eb8d2a7eb363227e973", GitTreeState:"clean"}
Error: cannot connect to Tiller

$ helm list
Error: forwarding ports: error upgrading connection: Upgrade request required
```

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.3.0` Cattle: `v0.175.2` UI: `v1.3.5` |
|Access|`Disabled`|
|Orchestration|`Kubernetes`|
|Route|`k8s-tab.namespace.pods.pod`|

**Comment by HackerWilson** [comment]
@ibuildthecloud Could you help solve this GFW problem? thx.

**Comment by HackerWilson** [comment]
finally I got it worker by these steps:
1. expose the tiller-deploy deployment to service as NodePort
```
$ kubectl --namespace=kube-system expose deployment tiller-deploy --type=NodePort
service "tiller-deploy" exposed
```
2. get the host and port of tiller-deploy service
```
$ kubectl --namespace=kube-system get pod -o wide
$ kubectl --namespace=kube-system get service
```
3. set $HELM_HOST in helm
```
$ export HELM_HOST=host:port
```
4. check
```
$ helm version
Client: &version.Version{SemVer:"v2.1.3", GitCommit:"5cbc48fb305ca4bf68c26eb8d2a7eb363227e973", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.1.3", GitCommit:"5cbc48fb305ca4bf68c26eb8d2a7eb363227e973", GitTreeState:"clean"}
```

It's because the tiller didn't expose when helm init.

**Comment by nrvale0** [comment]
@HackerWilson Are you by chance running these nodes in AWS with --cloud-provider=aws specified in the k8s infrastructure catalog?

**Comment by nrvale0** [comment]
@HackerWilson This may be related to an outstanding incompatibility between images pushed with Docker 1.10.x and Docker 1.13.x. At least it was in my case. Are you perhaps using Docker 1.13.x on the Rancher Agent nodes?

**Comment by nrvale0** [comment]
May be related to https://github.com/kubernetes/helm/issues/1838

**Comment by ryanwalls** [comment]
Looks like updating to the latest release candidate of Docker may fix this.  See https://github.com/kubernetes/helm/issues/1838#issuecomment-277021528
