### ISSUE TITLE
Migrate enrivonment from Cattle to Docker Swarm

### ISSUE THREAD

**Issue by bigfoot90** [rancher/rancher#7304]
**Rancher Version:** v1.3.0
**Docker Version:** 1.12.5
**OS and where are the hosts located?:** local
**Setup Details:** single node rancher
**Environment Type:** Cattle

Previously I have created an environment with` Cattle`, today I have upgraded `Rancher` to `v1.3.0`, and now I want to try the new integration with `Docker Swarm` mode.

Is there a way to migrate the enrivonment from `Cattle` to `Docker Swarm` without recreating the entire setup?

**Comment by bigfoot90** [comment]
Maybe I'm wrong, but I think it's not an impossible thing.

You have the an api to create containers which is orchestration agnostic, so it's the same api for `Cattle` and for `Docker Swarm`.
You only need to re-run the same calls on the new orchestration service.

**Comment by superseb** [comment]
Migrating is not possible, basically you can save some time by cleaning the hosts (`docker rm -f $(docker ps -qa)`, `docker volume rm -f rancher-agent-state`, `rm -rf /var/lib/rancher/state`) and re-adding them to the new environment.
