### ISSUE TITLE
Rancher inter container communication not working.  Also ipsec-router constantly restarts

### ISSUE THREAD

**Issue by srinisubramanian** [rancher/rancher#7306]
**Rancher Version:** 1.3.0

**Docker Version:** 1.12.5, , build 7392c3b

**OS and where are the hosts located? (cloud, bare metal, etc):** Centos 7 / BareMetal/ OVH Dedicated server

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** Single Node, internal MySQL with volume mount
NOTE: Agent and Rancher Server on same server.

Network - I have Centos 7 with 1 main public IP and 3 additional public IP (added as ipalias).  rancher is listening exclusively on an ipalias..  IPV6 is disabled.

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**  Cattle

**Steps to Reproduce:** Upgraded to 1.3.0 from 1.1.  Environment etc was migrated.  Subsequently when my user stacks were started communication between containers was not working.  When I checked the different stacks, found that in the Infra section, the ipsec stack, the ipsec-ipec-router-1 container is constantly restarting.  In between I copied the logs and the logs from the ipsec-router container.

----- Log --
1/5/2017 5:13:00 PM00[LIB] loading feature SIGNER:HMAC_SHA1_128 in plugin 'hmac'
1/5/2017 5:13:00 PM00[LIB] loading feature SIGNER:HMAC_SHA1_160 in plugin 'hmac'
1/5/2017 5:13:00 PM00[LIB] loading feature SIGNER:HMAC_MD5_96 in plugin 'hmac'
1/5/2017 5:13:00 PM00[LIB] loading feature SIGNER:HMAC_MD5_128 in plugin 'hmac'
1/5/2017 5:13:00 PM00[LIB] loading feature SIGNER:HMAC_SHA2_256_128 in plugin 'hmac'
1/5/2017 5:13:00 PM00[LIB] loading feature SIGNER:HMAC_SHA2_256_256 in plugin 'hmac'
1/5/2017 5:13:00 PM00[LIB] loading feature SIGNER:HMAC_SHA2_384_192 in plugin 'hmac'
1/5/2017 5:13:00 PM00[LIB] loading feature SIGNER:HMAC_SHA2_384_384 in plugin 'hmac'
1/5/2017 5:13:00 PM00[LIB] loading feature SIGNER:HMAC_SHA2_512_256 in plugin 'hmac'
1/5/2017 5:13:00 PM00[LIB] loading feature SIGNER:HMAC_SHA2_512_512 in plugin 'hmac'
1/5/2017 5:13:00 PM00[LIB] loading feature AEAD:AES_GCM_8-16 in plugin 'gcm'
1/5/2017 5:13:00 PM00[LIB] loading feature AEAD:AES_GCM_8-24 in plugin 'gcm'
1/5/2017 5:13:00 PM00[LIB] loading feature AEAD:AES_GCM_8-32 in plugin 'gcm'
1/5/2017 5:13:00 PM00[LIB] loading feature AEAD:AES_GCM_12-16 in plugin 'gcm'
1/5/2017 5:13:00 PM00[LIB] loading feature AEAD:AES_GCM_12-24 in plugin 'gcm'
1/5/2017 5:13:00 PM00[LIB] loading feature AEAD:AES_GCM_12-32 in plugin 'gcm'
1/5/2017 5:13:00 PM00[LIB] loading feature AEAD:AES_GCM_16-16 in plugin 'gcm'
1/5/2017 5:13:00 PM00[LIB] loading feature AEAD:AES_GCM_16-24 in plugin 'gcm'
1/5/2017 5:13:00 PM00[LIB] loading feature AEAD:AES_GCM_16-32 in plugin 'gcm'
1/5/2017 5:13:00 PM00[LIB] loading feature CUSTOM:attr in plugin 'attr'
1/5/2017 5:13:00 PM00[LIB] loading feature CUSTOM:resolve in plugin 'resolve'
1/5/2017 5:13:00 PM00[LIB] loading feature CUSTOM:stroke in plugin 'stroke'
1/5/2017 5:13:00 PM00[LIB]   feature CUSTOM:stroke in plugin 'stroke' has unmet soft dependency: PRIVKEY:DSA
1/5/2017 5:13:00 PM00[LIB]   feature CUSTOM:stroke in plugin 'stroke' has unmet soft dependency: PRIVKEY:BLISS
1/5/2017 5:13:00 PM00[CFG] loading ca certificates from '/usr/local/etc/ipsec.d/cacerts'
1/5/2017 5:13:00 PM00[LIB] opening directory '/usr/local/etc/ipsec.d/cacerts' failed: No such file or directory
1/5/2017 5:13:00 PM00[CFG]   reading directory failed
1/5/2017 5:13:00 PM00[CFG] loading aa certificates from '/usr/local/etc/ipsec.d/aacerts'
1/5/2017 5:13:00 PM00[LIB] opening directory '/usr/local/etc/ipsec.d/aacerts' failed: No such file or directory
1/5/2017 5:13:00 PM00[CFG]   reading directory failed
1/5/2017 5:13:00 PM00[CFG] loading ocsp signer certificates from '/usr/local/etc/ipsec.d/ocspcerts'
1/5/2017 5:13:00 PM00[LIB] opening directory '/usr/local/etc/ipsec.d/ocspcerts' failed: No such file or directory
1/5/2017 5:13:00 PM00[CFG]   reading directory failed
1/5/2017 5:13:00 PM00[CFG] loading attribute certificates from '/usr/local/etc/ipsec.d/acerts'
1/5/2017 5:13:00 PM00[LIB] opening directory '/usr/local/etc/ipsec.d/acerts' failed: No such file or directory
1/5/2017 5:13:00 PM00[CFG]   reading directory failed
1/5/2017 5:13:00 PM00[CFG] loading crls from '/usr/local/etc/ipsec.d/crls'
1/5/2017 5:13:00 PM00[LIB] opening directory '/usr/local/etc/ipsec.d/crls' failed: No such file or directory
1/5/2017 5:13:00 PM00[CFG]   reading directory failed
1/5/2017 5:13:00 PM00[CFG] loading secrets from '/usr/local/etc/ipsec.secrets'
1/5/2017 5:13:00 PM00[CFG] opening secrets file '/usr/local/etc/ipsec.secrets' failed: No such file or directory
1/5/2017 5:13:00 PM00[LIB] loading feature CUSTOM:vici in plugin 'vici'
1/5/2017 5:13:00 PM00[LIB] loading feature CUSTOM:updown in plugin 'updown'
1/5/2017 5:13:00 PM00[LIB] loading feature XAUTH_SERVER:generic in plugin 'xauth-generic'
1/5/2017 5:13:00 PM00[LIB] loading feature XAUTH_CLIENT:generic in plugin 'xauth-generic'
1/5/2017 5:13:00 PM00[LIB] loaded plugins: charon aesni aes des rc2 sha2 sha1 md5 random nonce x509 revocation constraints pubkey pkcs1 pkcs7 pkcs8 pkcs12 pgp dnskey sshkey pem fips-prf gmp xcbc cmac hmac gcm attr kernel-netlink resolve socket-default stroke vici updown xauth-generic
1/5/2017 5:13:00 PM00[LIB] unable to load 7 plugin features (7 due to unmet dependencies)
1/5/2017 5:13:00 PM00[JOB] spawning 16 worker threads
1/5/2017 5:13:00 PM01[LIB] created thread 01 [31]
1/5/2017 5:13:00 PM02[LIB] created thread 02 [32]
1/5/2017 5:13:00 PM03[LIB] created thread 03 [33]
1/5/2017 5:13:00 PM04[LIB] created thread 04 [34]
1/5/2017 5:13:00 PM05[LIB] created thread 05 [35]
1/5/2017 5:13:00 PM06[LIB] created thread 06 [36]
1/5/2017 5:13:00 PM07[LIB] created thread 07 [37]
1/5/2017 5:13:00 PM08[LIB] created thread 08 [38]
1/5/2017 5:13:00 PM09[LIB] created thread 09 [39]
1/5/2017 5:13:00 PM10[LIB] created thread 10 [40]
1/5/2017 5:13:00 PM11[LIB] created thread 11 [41]
1/5/2017 5:13:00 PM12[LIB] created thread 12 [42]
1/5/2017 5:13:00 PM13[LIB] created thread 13 [43]
1/5/2017 5:13:00 PM14[LIB] created thread 14 [44]
1/5/2017 5:13:00 PM15[LIB] created thread 15 [45]
1/5/2017 5:13:00 PM16[LIB] created thread 16 [46]
1/5/2017 5:13:01 PMtime="2017-01-05T11:43:01Z" level=debug msg="About to start server and listen on port: :8111"
1/5/2017 5:13:01 PMtime="2017-01-05T11:43:01Z" level=debug msg="Reloading ..."
1/5/2017 5:13:01 PMtime="2017-01-05T11:43:01Z" level=info msg="Listening on :8111"
1/5/2017 5:13:01 PMtime="2017-01-05T11:43:01Z" level=error msg="couldn't get self container from metadata: Error 404 accessing /self/container path"
1/5/2017 5:13:01 PMtime="2017-01-05T11:43:01Z" level=error msg="couldn't reload the overlay: Error 404 accessing /self/container path"
1/5/2017 5:13:01 PMtime="2017-01-05T11:43:01Z" level=fatal msg="Error 404 accessing /self/container path"
1/5/2017 5:13:01 PM15[NET] waiting for data on sockets
1/5/2017 5:13:01 PM13[CFG] vici client 1 connected
1/5/2017 5:13:01 PM03[CFG] vici client 1 registered for: list-conn
1/5/2017 5:13:01 PM12[CFG] vici client 1 requests: list-conns
1/5/2017 5:13:01 PM16[CFG] vici client 1 unregistered for: list-conn
1/5/2017 5:13:01 PM03[CFG] vici client 1 disconnected
1/5/2017 5:13:01 PM00[DMN] signal of type SIGTERM received. Shutting down
1/5/2017 5:13:01 PM00[MGR] going to destroy IKE_SA manager and all managed IKE_SA's
1/5/2017 5:13:01 PM00[MGR] set driveout flags for all stored IKE_SA's
1/5/2017 5:13:01 PM00[MGR] wait for all threads to leave IKE_SA's
1/5/2017 5:13:01 PM00[MGR] delete all IKE_SA's
1/5/2017 5:13:01 PM00[MGR] destroy all entries
1/5/2017 5:13:01 PM00[KNL] sending RTM_GETRULE 205: => 36 bytes @ 0x7ffd33a61c90
1/5/2017 5:13:01 PM00[KNL]    0: 24 00 00 00 21 00 05 00 CD 00 00 00 1E 00 00 00  $...!...........
1/5/2017 5:13:01 PM00[KNL]   16: 02 00 00 00 DC 03 00 01 00 00 00 00 08 00 06 00  ................
1/5/2017 5:13:01 PM00[KNL]   32: DC 00 00 00                                      ....
1/5/2017 5:13:01 PM00[KNL] received (2) 205: => 36 bytes @ 0x6331e0
1/5/2017 5:13:01 PM00[KNL]    0: 24 00 00 00 02 00 00 00 CD 00 00 00 1E 00 00 00  $...............
1/5/2017 5:13:01 PM00[KNL]   16: 00 00 00 00 24 00 00 00 21 00 05 00 CD 00 00 00  ....$...!.......
1/5/2017 5:13:01 PM00[KNL]   32: 1E 00 00 00                                      ....
1/5/2017 5:13:01 PM00[KNL] sending RTM_GETRULE 206: => 36 bytes @ 0x7ffd33a61c90
1/5/2017 5:13:01 PM00[KNL]    0: 24 00 00 00 21 00 05 00 CE 00 00 00 1E 00 00 00  $...!...........
1/5/2017 5:13:01 PM00[KNL]   16: 0A 00 00 00 DC 03 00 01 00 00 00 00 08 00 06 00  ................
1/5/2017 5:13:01 PM00[KNL]   32: DC 00 00 00                                      ....
1/5/2017 5:13:01 PM00[KNL] received (2) 206: => 56 bytes @ 0x62eb80
1/5/2017 5:13:01 PM00[KNL]    0: 38 00 00 00 02 00 00 00 CE 00 00 00 1E 00 00 00  8...............
1/5/2017 5:13:01 PM00[KNL]   16: 9F FF FF FF 24 00 00 00 21 00 05 00 CE 00 00 00  ....$...!.......
1/5/2017 5:13:01 PM00[KNL]   32: 1E 00 00 00 0A 00 00 00 DC 03 00 01 00 00 00 00  ................
1/5/2017 5:13:01 PM00[KNL]   48: 08 00 06 00 DC 00 00 00                          ........
1/5/2017 5:13:01 PM00[KNL] received netlink error: Address family not supported by protocol (97)
---- End log ----

**Results:** 

**Expected:**

**Comment by srinisubramanian** [comment]
Logs sent to @ibuildthecloud

**Comment by srinisubramanian** [comment]
I just created a new Rancher setup with 1.3 and same problem .. nothing to do with upgrade.  The Infrastructure stack starts up and only the ipsec route container keeps restarting.  Due to this no inter-container communication is possible.  This is a showstopper for me and I am unable to proceed.  Any help is appreciated.

**Comment by dustinvanbuskirk** [comment]
+1 upgraded from 1.0.2 to 1.2.2 and I'm having the same issue.  ipsec-ipsec-router on two of my Cattle hosts keeps restarting.

**Comment by aemneina** [comment]
Can you try this with the centos/rhel kernel version: `kernel-3.10.0-514.2.2.el7`

**Comment by dustinvanbuskirk** [comment]
I found I needed this change here. https://github.com/rancher/rancher-net/pull/30

I upgraded ipsec service to rancher-net 0.8.2, I had to delete the old router container to get upgrade to start but after upgrading all my issues with ipsec, heathcheck and my load balancers are resolved.

**Comment by srinisubramanian** [comment]
@dustinvanbuskirk I tried what you said .. but no joy.  Still the router keeps restarting.  Note that only the ipsec-service I upgraded from holder to v0.8.2 .. the sidekicks were still running v0.8.1

**Comment by dustinvanbuskirk** [comment]
Oh no, you don't need to upgrade holder.  You want to upgrade the sidekicks to 0.8.2.  Go ahead and go back to holder and upgrade the sidekicks.

**Comment by srinisubramanian** [comment]
@dustinvanbuskirk Oops .. my bad.  OK, another question.  When I clicked on ipsec in the UI I have an option to only upgrade the ipsec .. how do I upgrade the sidekicks?

**Comment by srinisubramanian** [comment]
@dustinvanbuskirk Did that now .. I upgraded the sidekicks and dropped service back to holder.  Same issue.  I am thinking it could be something with my linux kernel on OVH (right now on 4.8.15-xxxx-std-ipv6-64)

**Comment by andreikabeliy** [comment]
same for me, 3.10.0-327.36.3.el7.x86_64
ipsec-ipsec-router restarting all the time with the same log.

**Comment by leodotcloud** [comment]
@andreikabeliy as per @aemneina suggestion, please upgrade your kernel and try again.

**Comment by leodotcloud** [comment]
@srinisubramanian @andreikabeliy any updates on this?

**Comment by slaschinski** [comment]
I had the same issues because I had masquarading activated on the "FedoraServer"-Zone which contains the network interface.

**Comment by phouverneyuff** [comment]
Same here with Centos 7 - Kernel 3.10.0-514.6.1 - Docker 17.03.0-ce

**Comment by dankeder** [comment]
Yep, the above workaround from @slaschinski helped in my case too.
```
firewall-cmd --zone public --remove-masquerade
firewall-cmd --zone public --remove-masquerade --permanent
```
It seems that the masquerade is preventing only the startup of ipsec-router. I re-enabled masquerade on the public zone after ipsec-router started up and so far everything seems to be running well.

**Comment by srinisubramanian** [comment]
I haven't yet tried the masquerading disable. But additional info on my landscape. I have ipalias enabled and rancher is listening on the secondary ip. Masquerading is enabled.

**Comment by srinisubramanian** [comment]
Tried disabling masquerading and installing the stable rancher and all is good :)  Not sure what the issue is but at least it works now!

**Comment by srinisubramanian** [comment]
The masquerading work around does not help entirely.  This is what happened:
1.  Disable masquerade - Rancher starts, IPSec containers are all fine
2. Enable masquerade.  Start the user stacks.
3.  All user stacks without any port forwards from the host work.  Any container that needs a port forward does not start (rancher just throws the instance resources are not available error), look into var/log/messages shows the iptables error in adding the port forward and the container does not start

Had to therefore go back to the earlier version

**Comment by leodotcloud** [comment]
@srinisubramanian do you still have the same problem with the latest rancher releases? A lot of networking fixes went in the past couple of months.

**Comment by srinisubramanian** [comment]
@leodotcloud Just tried today, same issues.  Log from the ipsec-router container attached although the error is same, the logs look different.

7/21/2017 4:12:34 PM
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
7/21/2017 4:12:34 PM++ ip route get 8.8.8.8
7/21/2017 4:12:34 PM++ awk '{print $3}'
7/21/2017 4:12:34 PM+ GATEWAY=10.42.0.1
7/21/2017 4:12:34 PM+ iptables -t nat -I POSTROUTING -o eth0 -s 10.42.0.1 -j MASQUERADE
7/21/2017 4:12:34 PM++ ip route get 8.8.8.8
7/21/2017 4:12:34 PM++ grep via
7/21/2017 4:12:34 PM++ awk '{print $7}'
7/21/2017 4:12:34 PM+ exec rancher-net -i 10.42.28.57/16 --pid-file /var/run/rancher-net.pid --gcm=true --use-metadata --charon-launch --ipsec-config /etc/ipsec
7/21/2017 4:12:34 PMtime="2017-07-21T10:42:34Z" level=info msg="Writing pid 1 to /var/run/rancher-net.pid"
7/21/2017 4:12:34 PMtime="2017-07-21T10:42:34Z" level=info msg="Using backend: ipsec"
7/21/2017 4:12:34 PMtime="2017-07-21T10:42:34Z" level=info msg="Using metadata: true"
7/21/2017 4:12:34 PMtime="2017-07-21T10:42:34Z" level=info msg="Reading info from metadata"
7/21/2017 4:12:34 PMtime="2017-07-21T10:42:34Z" level=error msg="couldn't get self container from metadata: Error 404 accessing /self/container path"
7/21/2017 4:12:35 PMtime="2017-07-21T10:42:35Z" level=info msg="Listening on :8111"
7/21/2017 4:12:35 PMtime="2017-07-21T10:42:35Z" level=error msg="couldn't get self container from metadata: Error 404 accessing /self/container path"
7/21/2017 4:12:35 PMtime="2017-07-21T10:42:35Z" level=error msg="couldn't reload the overlay: Error 404 accessing /self/container path"
7/21/2017 4:12:35 PMtime="2017-07-21T10:42:35Z" level=fatal msg="Error 404 accessing /self/container path"
7/21/2017 4:12:35 PM00[DMN] Starting IKE charon daemon (strongSwan 5.5.1, Linux 4.4.8-xxxx-std-ipv6-64, x86_64)
7/21/2017 4:12:35 PM00[CFG] loading ca certificates from '/usr/local/etc/ipsec.d/cacerts'
7/21/2017 4:12:35 PM00[LIB] opening directory '/usr/local/etc/ipsec.d/cacerts' failed: No such file or directory
7/21/2017 4:12:35 PM00[CFG]   reading directory failed
7/21/2017 4:12:35 PM00[CFG] loading aa certificates from '/usr/local/etc/ipsec.d/aacerts'
7/21/2017 4:12:35 PM00[LIB] opening directory '/usr/local/etc/ipsec.d/aacerts' failed: No such file or directory
7/21/2017 4:12:35 PM00[CFG]   reading directory failed
7/21/2017 4:12:35 PM00[CFG] loading ocsp signer certificates from '/usr/local/etc/ipsec.d/ocspcerts'
7/21/2017 4:12:35 PM00[LIB] opening directory '/usr/local/etc/ipsec.d/ocspcerts' failed: No such file or directory
7/21/2017 4:12:35 PM00[CFG]   reading directory failed
7/21/2017 4:12:35 PM00[CFG] loading attribute certificates from '/usr/local/etc/ipsec.d/acerts'
7/21/2017 4:12:35 PM00[LIB] opening directory '/usr/local/etc/ipsec.d/acerts' failed: No such file or directory
7/21/2017 4:12:35 PM00[CFG]   reading directory failed
7/21/2017 4:12:35 PM00[CFG] loading crls from '/usr/local/etc/ipsec.d/crls'
7/21/2017 4:12:35 PM00[LIB] opening directory '/usr/local/etc/ipsec.d/crls' failed: No such file or directory
7/21/2017 4:12:35 PM00[CFG]   reading directory failed
7/21/2017 4:12:35 PM00[CFG] loading secrets from '/usr/local/etc/ipsec.secrets'
7/21/2017 4:12:35 PM00[LIB] loaded plugins: charon aesni aes des rc2 sha2 sha1 md5 random nonce x509 revocation constraints pubkey pkcs1 pkcs7 pkcs8 pkcs12 pgp dnskey sshkey pem fips-prf gmp xcbc cmac hmac gcm attr kernel-netlink resolve socket-default stroke vici updown xauth-generic
7/21/2017 4:12:35 PM00[JOB] spawning 16 worker threads
7/21/2017 4:12:35 PM00[DMN] signal of type SIGTERM received. Shutting down
7/21/2017 4:12:54 PM+ trap 'exit 1' SIGTERM SIGINT
7/21/2017 4:12:54 PM+ curl http://localhost:8111
7/21/2017 4:12:54 PM+ export CHARON_PID_FILE=/var/run/charon.pid
7/21/2017 4:12:54 PM+ CHARON_PID_FILE=/var/run/charon.pid
7/21/2017 4:12:54 PM+ rm -f /var/run/charon.pid
7/21/2017 4:12:54 PM+ export PIDFILE=/var/run/rancher-net.pid
7/21/2017 4:12:54 PM+ PIDFILE=/var/run/rancher-net.pid
7/21/2017 4:12:54 PM+ GCM=false
7/21/2017 4:12:54 PM+ (( i=0 ))
7/21/2017 4:12:54 PM+ (( i<6 ))
7/21/2017 4:12:54 PM+ ip xfrm state add src 1.1.1.1 dst 1.1.1.1 spi 42 proto esp mode tunnel aead 'rfc4106(gcm(aes))' 0x0000000000000000000000000000000000000001 128 sel src 1.1.1.1 dst 1.1.1.1
7/21/2017 4:12:54 PM+ GCM=true
7/21/2017 4:12:54 PM+ ip xfrm state del src 1.1.1.1 dst 1.1.1.1 spi 42 proto esp
7/21/2017 4:12:54 PM+ break
7/21/2017 4:12:54 PM+ '[' false == true ']'
7/21/2017 4:12:54 PM+ DEBUG=
7/21/2017 4:12:54 PM+ mkdir -p /etc/ipsec
7/21/2017 4:12:54 PM+ curl -f -u 30462A96F7E11CD525B9:EvnDu8SQtuqs2PVjHSkqybsUqVZ8reU1PqzD5KCq https://<rancher_url>/v1/configcontent/psk
7/21/2017 4:12:54 PM  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
7/21/2017 4:12:54 PM                                 Dload  Upload   Total   Spent    Left  Speed
7/21/2017 4:12:54 PM
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    32  100    32    0     0    318      0 --:--:-- --:--:-- --:--:--   320
7/21/2017 4:12:54 PM+ curl -f -X PUT -d '' -u 30462A96F7E11CD525B9:EvnDu8SQtuqs2PVjHSkqybsUqVZ8reU1PqzD5KCq 'https://<rancher_url>/v1/configcontent/psk?version=latest'
7/21/2017 4:12:54 PM  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
7/21/2017 4:12:54 PM                                 Dload  Upload   Total   Spent    Left  Speed
7/21/2017 4:12:54 PM
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
7/21/2017 4:12:54 PM++ ip route get 8.8.8.8
7/21/2017 4:12:54 PM++ awk '{print $3}'
7/21/2017 4:12:54 PM+ GATEWAY=10.42.0.1
7/21/2017 4:12:54 PM+ iptables -t nat -I POSTROUTING -o eth0 -s 10.42.0.1 -j MASQUERADE
7/21/2017 4:12:54 PM++ ip route get 8.8.8.8
7/21/2017 4:12:54 PM++ grep via
7/21/2017 4:12:54 PM++ awk '{print $7}'
7/21/2017 4:12:54 PM+ exec rancher-net -i 10.42.28.57/16 --pid-file /var/run/rancher-net.pid --gcm=true --use-metadata --charon-launch --ipsec-config /etc/ipsec
7/21/2017 4:12:54 PMtime="2017-07-21T10:42:54Z" level=info msg="Writing pid 1 to /var/run/rancher-net.pid"
7/21/2017 4:12:54 PMtime="2017-07-21T10:42:54Z" level=info msg="Using backend: ipsec"
7/21/2017 4:12:54 PMtime="2017-07-21T10:42:54Z" level=info msg="Using metadata: true"
7/21/2017 4:12:54 PMtime="2017-07-21T10:42:54Z" level=info msg="Reading info from metadata"
7/21/2017 4:12:54 PMtime="2017-07-21T10:42:54Z" level=error msg="couldn't get self container from metadata: Error 404 accessing /self/container path"
7/21/2017 4:12:55 PMtime="2017-07-21T10:42:55Z" level=info msg="Listening on :8111"
7/21/2017 4:12:55 PMtime="2017-07-21T10:42:55Z" level=error msg="couldn't get self container from metadata: Error 404 accessing /self/container path"
7/21/2017 4:12:55 PMtime="2017-07-21T10:42:55Z" level=error msg="couldn't reload the overlay: Error 404 accessing /self/container path"
7/21/2017 4:12:55 PMtime="2017-07-21T10:42:55Z" level=fatal msg="Error 404 accessing /self/container path"
7/21/2017 4:12:55 PM00[DMN] Starting IKE charon daemon (strongSwan 5.5.1, Linux 4.4.8-xxxx-std-ipv6-64, x86_64)
7/21/2017 4:12:55 PM00[CFG] loading ca certificates from '/usr/local/etc/ipsec.d/cacerts'
7/21/2017 4:12:55 PM00[LIB] opening directory '/usr/local/etc/ipsec.d/cacerts' failed: No such file or directory
7/21/2017 4:12:55 PM00[CFG]   reading directory failed
7/21/2017 4:12:55 PM00[CFG] loading aa certificates from '/usr/local/etc/ipsec.d/aacerts'
7/21/2017 4:12:55 PM00[LIB] opening directory '/usr/local/etc/ipsec.d/aacerts' failed: No such file or directory
7/21/2017 4:12:55 PM00[CFG]   reading directory failed
7/21/2017 4:12:55 PM00[CFG] loading ocsp signer certificates from '/usr/local/etc/ipsec.d/ocspcerts'
7/21/2017 4:12:55 PM00[LIB] opening directory '/usr/local/etc/ipsec.d/ocspcerts' failed: No such file or directory
7/21/2017 4:12:55 PM00[CFG]   reading directory failed
7/21/2017 4:12:55 PM00[CFG] loading attribute certificates from '/usr/local/etc/ipsec.d/acerts'
7/21/2017 4:12:55 PM00[LIB] opening directory '/usr/local/etc/ipsec.d/acerts' failed: No such file or directory
7/21/2017 4:12:55 PM00[CFG]   reading directory failed
7/21/2017 4:12:55 PM00[CFG] loading crls from '/usr/local/etc/ipsec.d/crls'
7/21/2017 4:12:55 PM00[LIB] opening directory '/usr/local/etc/ipsec.d/crls' failed: No such file or directory
7/21/2017 4:12:55 PM00[CFG]   reading directory failed
7/21/2017 4:12:55 PM00[CFG] loading secrets from '/usr/local/etc/ipsec.secrets'
7/21/2017 4:12:55 PM00[LIB] loaded plugins: charon aesni aes des rc2 sha2 sha1 md5 random nonce x509 revocation constraints pubkey pkcs1 pkcs7 pkcs8 pkcs12 pgp dnskey sshkey pem fips-prf gmp xcbc cmac hmac gcm attr kernel-netlink resolve socket-default stroke vici updown xauth-generic
7/21/2017 4:12:55 PM00[JOB] spawning 16 worker threads
7/21/2017 4:12:55 PM00[DMN] signal of type SIGTERM received. Shutting down

**Comment by leodotcloud** [comment]
@srinisubramanian can you please share your current version of rancher/server, OS and kernel version?
Looking at the logs of ipsec, metadata is not accessible.

Also the other logs indicate you are using firewalld, some of our users had their problems resolved when they disabled firewalld. Can you give it a try?

**Comment by srinisubramanian** [comment]
@leodotcloud Your pointer was bang on.  When I stopped firewalld and migrated to iptables, the issue went away and Rancher and all its services are running normally.  I also upgraded from 1.3.0 successfully.  You can consider this issue closed.

I have a new issue now (was not there in 1.3.0) for which I raised issue #9441.  Please let me know how I can resolve that.
