### ISSUE TITLE
Catalog item AWS ELB 'max 20 ELB' issue

### ISSUE THREAD

**Issue by Dmitry1987** [rancher/rancher#7307]
**Rancher Version:**
1.2.2
**OS and where are the hosts located? (cloud, bare metal, etc):**
AWS, rancherOS
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
Have 20+  ELBs in AWS region where you want to work with Rancher ELB catalog app (that should dynamically update particular ELB instances list pointing to where services deployed)
**Results:** 
Has AWS SDK error during startup (seen in logs)
```
time="2017-01-05T11:37:53Z" level=error msg="Failed to update provider: Failed to get LB configs from provider: Failed to lookup load balancer tags: DescribeTags SDK error: ValidationError: 1 validation error detected: Value '[..._about-40-our-other-ELBs_..., rancher-lb-test]' at 'loadBalancerNames' failed to satisfy constraint: Member must have length less than or equal to 20\n\tstatus code: 400, request id: 65289bf1-d33b-11e6-a205-d32380b90303"
```

**Expected:**
Catalog item to work, and update ELB instances list.

**(the item is:  rancher/external-lb:v0.2.1 )**

The issue is with "DescribeTags"  SDK command used in this catalog item probably, discussed here:  https://github.com/aws/aws-sdk-go/issues/717

quoting from that thread, the related post of @raphtheb  (thanks for sharing solution @raphtheb ! )
```
The problem actually laid in the 'DescribeTags' call instead of the 'DescribeLoadBalancers' call, from first glance.

Turns out that the API call: elb.DescribeTags(...) only allows for 20 loadbalancers worth of tags to be queried at once. This limitation is not described anywhere in the AWS SDK documentation, nor the source code.

http://docs.aws.amazon.com/sdk-for-go/api/service/elb/#example_ELB_DescribeTags

After being puzzled for the longest time, found myself on the API doc itself for the ELB service and it was actually documented there instead: http://docs.aws.amazon.com/ElasticLoadBalancing/latest/APIReference/API_DescribeTags.html
```

how we can solve this?   can I submit a pull request if i find how to fix it?

**Comment by galal-hussein** [comment]
@Dmitry1987 A PR is most welcomed if you find a solution to this issue.

**Comment by janeczku** [comment]
@Dmitry1987 The fix should be done in the `DescribeLBTags()` method 
https://github.com/rancher/external-lb/blob/master/providers/elbv1/elbv1svc/elb_classic.go#L62
you probably need to make an extra API call for every additional set of 20 load balancers.

**Comment by Dmitry1987** [comment]
thanks @janeczku , I'll try to find the time to check this. 
btw, when you're developing some parts of rancher, or catalog items like this one, how to test it?  i will recompile, rebuild docker image and upload to my own docker repo, then use my custom URLs in manifest/spec files that run it, is that correct way to work on such things, or may you share some tips/tricks?  :)    which IDE do you use? (i use Atom for small golang stuff, for now just wrote a few handy cli tools we use at work. but never worked with large projects)

**Comment by Dmitry1987** [comment]
@janeczku  I've read some of the code, want to ask if it's necessary to pass "all ELBs in region" to getTags [here](https://github.com/rancher/external-lb/blob/dff0e00671b1432c201f60b0355b1c930a87443c/providers/elbv1/aws_elbv1.go):  
```
	allNames := make([]string, len(allLb))
	for i, lb := range allLb {
		allNames[i] = *lb.LoadBalancerName
	}
	lbTags, err := p.svc.DescribeLBTags(allNames)
```
or we can limit this "list" of names first, to only those ELBs that need our management?  because some may have 500+ ELBs in their accounts... (I just found out we have around 150 in one region :) )

**Comment by whiteadam** [comment]
+1 on this issue. Just tried using the catalog item for the first time and started getting this error.

**Comment by loganhz** [comment]
Hi @Dmitry1987 , thank you for the very detailed solution.
I have made a simple change to fix it.
Would you mind having a try?
you can update the image id of `elbv1` service to `registry.cn-hangzhou.aliyuncs.com/logan/external-lb:5bcb3a0`.

**Comment by Dmitry1987** [comment]
Thanks @loganhz , but we're not using Rancher at the moment. Definitely it'll be useful for all others who run ELB :)

**Comment by yasker** [comment]
@loganhz `rancher/external-lb:v0.3.3` has been released for this fix.

**Comment by kingsd041** [comment]
Tested with rancher-server version- v1.6.10 with rancher/external-lb:v0.3.3

Test passed.
