### ISSUE TITLE
[rancher-compose] Question: Environment variable substitution order different compared to docker compose

### ISSUE THREAD

**Issue by lghakamo** [rancher/rancher#7308]
**Rancher Version:** v1.2.1

**Docker Version:** v1.12.5

**OS and where are the hosts located? (cloud, bare metal, etc):** Linux Mint 18, docker-machine

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single node rancher, internal db

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:**
$ export VAR1=shell
$ cat application.env
VAR1=file
$ cat docker-compose.yml
version: '2'
services:
  test-service:
    image: nginx
    environment:
      VAR1: "${VAR1}"

deploy stack using rancher-compose:
$ rancher-compose --debug --url $RANCHER_URL --access-key $RANCHER_API_ACCESS_KEY --secret-key $RANCHER_API_SECRET_KEY --env-file application.env -p test-service up -d --force-upgrade --confirm-upgrade --pull --batch-size "1"

**Results:** 
Value of VAR1 = file

**Expected:**
Value of VAR1 = shell

docker compose overrides values in the .env file with values provided from the shell (https://docs.docker.com/compose/compose-file/#variable-substitution: "Values set in the shell environment will override those set in the .env file.") while rancher-compose does the opposite (http://docs.rancher.com/rancher/v1.2/en/cattle/rancher-compose/commands/: "If the environment variable is set in the file and on the machine, Rancher Compose will use the value in the file.").

What's reasoning behind changing the behavior compared to docker compose?

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
