### ISSUE TITLE
Cattle: Doesn't follow scheduling rules when upgrading service

### ISSUE THREAD

**Issue by withinboredom** [rancher/rancher#7309]
**Rancher Version:**
1.3.0
**Docker Version:**
1.12
**OS and where are the hosts located? (cloud, bare metal, etc):**
digital ocean, ubuntu 16
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single rancher node, internal db
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
cattle
**Steps to Reproduce:**

1. deploy 3 rancher hosts
1. Deactivate node 3, so no services get scheduled to it
1. Create a service, across 3 nodes, no specific scheduling (test_stack/service1) with a scale of 6
1. Reactivate node 3
1. upgrade service, add a scheduling rule: should not have a service named `test_stack/service1`

**Results:** 

Service upgrades in-place, ignoring scheduling rule

**Expected:**

Prior to 1.2.x, this would rebalance the service across the cluster. This is no longer the case.

**Comment by withinboredom** [comment]
As a matter a fact, you used to be able to delete a container on the hosts screen, and it would follow the scheduling rule, and move it somewhere else. It recreates the container on the same host, despite the rule.

**Comment by tfiduccia** [comment]
Version - 1.3.0
I recreated the steps and verified that this is actually a bug.  During upgrade the new container is always going to the same host and never goes to the new/reactivated host.
![image](https://cloud.githubusercontent.com/assets/11514927/21692045/5189e712-d338-11e6-9f31-e6497966178d.png)

**Comment by bradjones1** [comment]
It appears this is also the case when scaling a service.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
