### ISSUE TITLE
When kuberenetes is first launch have to refresh browser or I get sent to Stacks page

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#7312]
**Rancher Versions:** v1.3.0

**Steps to Reproduce:**
1.  Create a kuberenetes environment
2.  Add three hosts
3.  Wait for kubernetes to fully setup
4.  Click on Go to Catalog button from stacks page
5.  Click on Catalog item

**Results:** Until you actually refresh, you can't get to the catalog page.

**Expected:**  Should be able to get to catalog without having to refresh

**Comment by tfiduccia** [comment]
This is not just with catalog page.  I noticed that I'm being redirected back to Stacks page when clicking on buttons or going to certain pages.  Refreshing the browsers seems to fix this problem.

**Comment by vincent99** [comment]
Removed the redirecting with the new more limited k8s..

**Comment by tfiduccia** [comment]
Version - master 1/11
Verified fixed
