### ISSUE TITLE
Environments show as degraded after deactivating/disabling stacks

### ISSUE THREAD

**Issue by garceri** [rancher/rancher#7313]
**Rancher Versions:**
Server: 1.2.2
healthcheck:0.2.0
ipsec:0.8.1
network-services:0.4.0
scheduler:0.5.0
kubernetes (if applicable):N/A

**Docker Version:**
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64

**OS and where are the hosts located? (cloud, bare metal, etc):**
AWS 
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node rancher with externaldb (RDS)
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
Upgrade Rancher from 1.1.2 to 1.2,2 
**Results:** 
-Under Environments / Manage environment our main environment shows up as Degraded
-Stacks are all running without issues, so we are not sure where the "Degrade" state comes from
**Expected:**
Environment should not show up as degraded, and/or there should be a way to identify the source of that status.

**Comment by deniseschannon** [comment]
Degraded for environment is the same concept of degraded for stacks. 

If any of your stacks have any issues and are not green/active, environment will be degraded.

**Comment by pythianarceri** [comment]
All our stacks are green and healthy except for two that are marked as Inactive? does this mean that these Inactive stacks cause the environment state to be Degraded ?

**Comment by deniseschannon** [comment]
Yes, those would cause them to be degraded. Just like how an inactive service causes a stack to appear degraded.

**Comment by goffinf** [comment]
Really ?. A stack that has been explicitly set to inactive causes the whole environment to show as degraded, why ?  Degraded to me suggests that something is not working or exhibiting unexpected behaviour. If I deliberately stop a service for whatever reason, that *is* the behaviour I expect right ?

**Comment by pythianarceri** [comment]
I agree, if a service was delierately stopped it should not show the environment as degraded. It's just confusing

**Comment by janeczku** [comment]
@pythianarceri i have updated the title of this ticket to better reflect whats the issue discussed here.

@deniseschannon This issue makes the healthState property of environments useless as to determining whether all the services in those environments are healthy.

Imagine having to monitor 10+ environments. Instead of being able to rely on this aggregated view to get insight into the health of environments

![manageenv](https://cloud.githubusercontent.com/assets/3813921/24967935/ec5224ca-1fab-11e7-83d3-3249c29768ca.png)


one needs to navigate through each of the environments and check whether any stacks/services are actually unhealthy or just contain one or more deactivated stacks.

**Comment by ekristen** [comment]
I completely agree, if a stack has been purposefully stopped, it should not be marked as `unhealthy` it should be marked as `inactive` and it should not degrade the entire environment.

**Comment by jjscarafia** [comment]
:+1: Stopped stacks should not mark environment as degraded

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
