### ISSUE TITLE
Misspelled DO machine configuration

### ISSUE THREAD

**Issue by sheng-liang** [rancher/rancher#7314]
**Rancher Versions:**
Server: 1.3.0
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker Version:**
N/A

**OS and where are the hosts located? (cloud, bare metal, etc):**
DigitalOcean

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Rancher 1.3.0
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes
**Steps to Reproduce:**
Add hosts from DigitalOcean in Kubernetes
**Results:** 
Machine config options show "1 RAM, 30gb Disk, 1 vCPU"
**Expected:**
Should be "1GB RAM, 30GB Disk, 1 vCPU"

**Comment by tfiduccia** [comment]
Version - 1.3.0
In the Add host screen for Digital Ocean, under the instance section this is indeed lower case and should be uppercase.

**Comment by vincent99** [comment]
@sheng-liang It says "1gb" in actual 1.3, it looks like you're looking at `try.` which has basically UI from master.  I was changing it to group the High mem ones together and lost the unit.  @tfiduccia will change to capital.

![image](https://cloud.githubusercontent.com/assets/753917/21692630/f9e722d8-d33a-11e6-90cc-487f6e92fc59.png)

**Comment by tfiduccia** [comment]
Version - master 1/11
Verified fixed
