### ISSUE TITLE
Users are redirected from Hosts page to Stacks page when Kubernetes environment becomes unhealthy

### ISSUE THREAD

**Issue by sheng-liang** [rancher/rancher#7315]
**Rancher Versions:**
Server: Rancher 1.3
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker Version:**
1.12.x
**OS and where are the hosts located? (cloud, bare metal, etc):**
DigitalOcean, Ubuntu
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Rancher 1.3
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
A Kubernetes environment with 4 hosts on DigitalOcean
**Steps to Reproduce:**
On the Hosts page, I delete some hosts, causing Rancher to reconcile Kubernetes infrastructure services to other hosts.
**Results:** 
Rancher UI redirects me back to the Stacks page with `https://<server>/env/1a39456/kubernetes/default/stacks?error_description=The%20redirect_uri%20MUST%20match%20the%20registered%20callback%20URL%20for%20this%20application.&state=0.5483969863717566`
**Expected:**
I should stay on the Hosts page.

**Comment by vincent99** [comment]
I think this was fixed already, but it definitely doesn't apply in 2.0.
