### ISSUE TITLE
DNS resolution for <stack-name>.<service-name> results in ip adress resolving to services from multiple environment.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#7321]
Rancher Version: Build from master

Steps to reproduce the problem:
Create an admin env - "admin".
Deploy a GLB.

Create a user env - "user1".
For "admin" env , create a project link to "user1".

Create a user env - "user2".
For "admin" env , create a project link to "user2".

In env - "user1" , Create a stack test1 and deploy user lb and service - foo.
In env - "user2" , Create a stack test1 and deploy user lb and service - foo.

From GLB container (in "admin" env) , try to resolve foo.test1 . It resolves to containers from service - "foo" in both the environments.

Should the fqdn for services now include environment name as well ?

**Comment by alena1108** [comment]
Fixed as a part of v0.13.1 rancher/dns
