### ISSUE TITLE
Kubernetes Stack Upgrade Button does not work

### ISSUE THREAD

**Issue by bscott** [rancher/rancher#7323]
**Rancher Versions:**
Server: v1.3.0
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable): 

**Docker Version:**

**OS and where are the hosts located? (cloud, bare metal, etc):**

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**
Visit "Infrastructure Stacks" in a Kubernetes Environment. Click "Upgrade Available" Button
![image](https://cloud.githubusercontent.com/assets/191290/21700515/a749a58a-d355-11e6-8d02-aa1c15c7107c.png)

**Results:** 
Redirects you to the default stack instead of the Upgrade Kubernetes page.
![image](https://cloud.githubusercontent.com/assets/191290/21700521/b8135dde-d355-11e6-9fb2-feab811131a8.png)

**Expected:**

**Comment by tfiduccia** [comment]
@bscott - Hello, I noticed we currently have a bug where after you first create a kubernetes environment, when you click on buttons or certain pages, it redirects you back to Stacks page.  Can you please refresh your browser and try again.  This seems to fix the problem for me.

**Comment by bscott** [comment]
@tfiduccia This is an existing Kubernetes environment from v1.2.2, I've refreshed a few times and still sends me to the Stacks page

**Comment by bscott** [comment]
Now it seemed to work

**Comment by tfiduccia** [comment]
@bscott - Glad it's finally working.  We have a few issues already in about the redirection back to stacks page.  I'm going to mark this one duplicate and associate it to previous bug, then close it.  I'll make sure to test this scenario when we get a fix in.

Duplicate #7312
