### ISSUE TITLE
Upgrading a service with memory constraints

### ISSUE THREAD

**Issue by 5an1ty** [rancher/rancher#7324]
Version:

Rancher 1.3

Feature Used:

This issue occurs when using Memory Reservation for services.

Issue:

When you have a Rancher cluster with two hosts, both have 4GB of ram and you have a service running on **both** hosts that takes 3GB of memory (Each host still has 1GB of memory free). If you would upgrade this service Rancher throws an error that not a single host is capable of running this service with the provided memory constraint.

I think this is due to rancher still reserving the memory for the service during upgrade for the container that is currently in a stopped state, I don't think Rancher should be doing this and only have memory constraints for actual running containers.

**Comment by jean-francois-labbe** [comment]
I have this issue and this is super annoying. I order to upgrade a service you need to kill containers, this makes rollback impossible.

If I wan't it to always work I have to set lower memory reservation that do not reflect what's needed and risk to crash a server. 

I need memory restrictions but I also need proper service upgrade.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
