### ISSUE TITLE
All hosts are visible from linked projects , even when it does not have any cross linked services running in it.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#7325]
Rancher Versions: Build from master

Steps to reproduce the problem:
Create an admin env - "admin". Add 2 hosts.
Deploy a GLB. 
Create a user env - "user1".

For "admin" env , create a project link to "user1".

In "user1" env , create a user LB for a service - s1. 
From any container in this environment, able to see all the hosts in "admin" env (even the ones where GLB containers are not running) using rancher-metadata - ```wget http://rancher-metadata/latest/hosts```

Expected:
We should see only the hosts that have linked service container from the linked projects.

**Comment by alena1108** [comment]
@sangeethah @deniseschannon it is because every host in every linked environment has vxlan service instance (the service is global), and vxlan services are linked cross environments. Closing the issue.
