### ISSUE TITLE
"Couldn't find frontend channel..." filling logs rapidly

### ISSUE THREAD

**Issue by jloisel** [rancher/rancher#7327]
**Rancher Versions:**
Server: v1.3.0
healthcheck: none
ipsec: none
network-services: none
scheduler: none
kubernetes (if applicable): no

All system services have been removed (I don't need them).

**Docker Version:**
1.12.5

**OS and where are the hosts located? (cloud, bare metal, etc):**
Bare-metal Ubuntu 16.04 LTS:
> Linux desktop 4.4.0-57-generic #78-Ubuntu SMP Fri Dec 9 23:50:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Not sure how this happened.

**Results:** 
Logs filled with these messages at high speed:

> ey a7ef671c-684b-4a20-9d74-3241d198decc. Closing frontend connection." 
time="2017-01-05T15:42:25Z" level=info msg="Couldn't find frontend channel for key a7ef671c-684b-4a20-9d74-3241d198decc. Closing frontend connection." 
time="2017-01-05T15:42:25Z" level=info msg="Couldn't find frontend channel for key a7ef671c-684b-4a20-9d74-3241d198decc. Closing frontend connection." 
time="2017-01-05T15:42:25Z" level=info msg="Couldn't find frontend channel for key a7ef671c-684b-4a20-9d74-3241d198decc. Closing frontend connection." 
time="2017-01-05T15:42:25Z" level=info msg="Couldn't find frontend channel for key a7ef671c-684b-4a20-9d74-3241d198decc. Closing frontend connection." 
time="2017-01-05T15:42:25Z" level=info msg="Couldn't find frontend channel for key a7ef671c-684b-4a20-9d74-3241d198decc. Closing frontend connection." 
time="2017-01-05T15:42:25Z" level=info msg="Couldn't find frontend channel for key a7ef671c-684b-4a20-9d74-3241d198decc. Closing frontend connection." 
time="2017-01-05T15:42:25Z" level=info msg="Couldn't find frontend channel for key a7ef671c-684b-4a20-9d74-3241d198decc. Closing frontend connection." 
time="2017-01-05T15:42:25Z" level=info msg="Couldn't find frontend channel for key a7ef671c-684b-4a20-9d74-3241d198decc. Closing frontend connection." 
time="2017-01-05T15:42:25Z" level=info msg="Couldn't find frontend channel for key a7ef671c-684b-4a20-9d74-3241d198decc. Closing frontend connection." 
time="2017-01-05T15:42:25Z" level=info msg="Couldn't find frontend channel for key a7ef671c-684b-4a20-9d74-3241d198decc. Closing frontend connection." 
time="2017-01-05T15:42:25Z" level=info msg="Couldn't find frontend channel for key a7ef671c-684b-4a20-9d74-3241d198decc. Closing frontend connection." 
time="2017-01-05T15:42:25Z" level=info msg="Couldn't find frontend channel for key a7ef671c-684b-4a20-9d74-3241d198decc. Closing frontend connection." 
time="2017-01-05T15:42:25Z" level=info msg="Couldn't find frontend channel for key a7ef671c-684b-4a20-9d74-3241d198decc. Closing frontend connection." 
time="2017-01-05T15:42:25Z" level=info msg="Couldn't find frontend channel for key a7ef671c-684b-4a20-9d74-3241d198decc. Closing frontend connection." 
time="2017-01-05T15:42:25Z" level=info msg="Couldn't find frontend channel for key a7ef671c-684b-4a20-9d74-3241d198decc. Closing frontend connection." 
time="2017-01-05T15:42:25Z" level=info msg="Couldn't find frontend channel for key a7ef671c-684b-4a20-9d74-3241d198decc. Closing frontend connection." 
time="2017-01-05T15:42:25Z" level=info msg="Couldn't find frontend channel for key a7ef671c-684b-4a20-9d74-3241d198decc. Closing frontend connection." 
time="2017-01-05T15:42:25Z" level=info msg="Couldn't find frontend channel for key a7ef671c-684b-4a20-9d74-3241d198decc. Closing frontend connection." 
time="2017-01-05T15:42:25Z" level=info msg="Couldn't find frontend channel for key a7ef671c-684b-4a20-9d74-3241d198decc. Closing frontend connection."

**Expected:**
Should log it only once.

**Comment by goffinf** [comment]
We are seeing this too. Same Rancher server version (1.3.0), cattle orchestration, RHEL 7.3 on AWS

**Comment by morlay** [comment]
Same too. with 1.3.1

**Comment by otsuarez** [comment]
Same here with 1.3.1

**Comment by ccesara** [comment]
Same here...

time="2017-01-18T13:38:52Z" level=info msg="Couldn't find frontend channel for key a5fb7c08-2a7a-4952-6b48-b6d9a30047b7. Closing frontend connection." 
time="2017-01-18T13:39:22Z" level=info msg="Couldn't find frontend channel for key a5fb7c08-2a7a-4952-6b48-b6d9a30047b7. Closing frontend connection." 
time="2017-01-18T13:39:22Z" level=info msg="Couldn't find frontend channel for key a5fb7c08-2a7a-4952-6b48-b6d9a30047b7. Closing frontend connection." 
time="2017-01-18T13:39:52Z" level=info msg="Couldn't find frontend channel for key a5fb7c08-2a7a-4952-6b48-b6d9a30047b7. Closing frontend connection." 
time="2017-01-18T13:39:52Z" level=info msg="Couldn't find frontend channel for key a5fb7c08-2a7a-4952-6b48-b6d9a30047b7. Closing frontend connection." 
time="2017-01-18T13:40:22Z" level=info msg="Couldn't find frontend channel for key a5fb7c08-2a7a-4952-6b48-b6d9a30047b7. Closing frontend connection." 
time="2017-01-18T13:40:22Z" level=info msg="Couldn't find frontend channel for key a5fb7c08-2a7a-4952-6b48-b6d9a30047b7. Closing frontend connection." 
time="2017-01-18T13:40:52Z" level=info msg="Couldn't find frontend channel for key a5fb7c08-2a7a-4952-6b48-b6d9a30047b7. Closing frontend connection." 
time="2017-01-18T13:40:52Z" level=info msg="Couldn't find frontend channel for key a5fb7c08-2a7a-4952-6b48-b6d9a30047b7. Closing frontend connection." 
time="2017-01-18T13:41:22Z" level=info msg="Couldn't find frontend channel for key a5fb7c08-2a7a-4952-6b48-b6d9a30047b7. Closing frontend connection." 
time="2017-01-18T13:41:22Z" level=info msg="Couldn't find frontend channel for key a5fb7c08-2a7a-4952-6b48-b6d9a30047b7. Closing frontend connection." 
time="2017-01-18T13:41:52Z" level=info msg="Couldn't find frontend channel for key a5fb7c08-2a7a-4952-6b48-b6d9a30047b7. Closing frontend connection." 
time="2017-01-18T13:41:52Z" level=info msg="Couldn't find frontend channel for key a5fb7c08-2a7a-4952-6b48-b6d9a30047b7. Closing frontend connection." 
time="2017-01-18T13:42:22Z" level=info msg="Couldn't find frontend channel for key a5fb7c08-2a7a-4952-6b48-b6d9a30047b7. Closing frontend connection." 
time="2017-01-18T13:42:22Z" level=info msg="Couldn't find frontend channel for key a5fb7c08-2a7a-4952-6b48-b6d9a30047b7. Closing frontend connection." 
time="2017-01-18T13:42:52Z" level=info msg="Couldn't find frontend channel for key a5fb7c08-2a7a-4952-6b48-b6d9a30047b7. Closing frontend connection." 
time="2017-01-18T13:42:52Z" level=info msg="Couldn't find frontend channel for key a5fb7c08-2a7a-4952-6b48-b6d9a30047b7. Closing frontend connection." 
time="2017-01-18T13:43:22Z" level=info msg="Couldn't find frontend channel for key a5fb7c08-2a7a-4952-6b48-b6d9a30047b7. Closing frontend connection." 
time="2017-01-18T13:43:22Z" level=info msg="Couldn't find frontend channel for key a5fb7c08-2a7a-4952-6b48-b6d9a30047b7. Closing frontend connection." 
time="2017-01-18T13:43:29Z" level=info msg="Refresh for this catalog library is already in process, skipping" 
time="2017-01-18T13:43:52Z" level=info msg="Couldn't find frontend channel for key a5fb7c08-2a7a-4952-6b48-b6d9a30047b7. Closing frontend connection." 
time="2017-01-18T13:43:52Z" level=info msg="Couldn't find frontend channel for key a5fb7c08-2a7a-4952-6b48-b6d9a30047b7. Closing frontend connection." 
time="2017-01-18T13:44:22Z" level=info msg="Couldn't find frontend channel for key a5fb7c08-2a7a-4952-6b48-b6d9a30047b7. Closing frontend connection." 
time="2017-01-18T13:44:22Z" level=info msg="Couldn't find frontend channel for key a5fb7c08-2a7a-4952-6b48-b6d9a30047b7. Closing frontend connection." 
time="2017-01-18T13:44:52Z" level=info msg="Couldn't find frontend channel for key a5fb7c08-2a7a-4952-6b48-b6d9a30047b7. Closing frontend connection." 
time="2017-01-18T13:44:52Z" level=info msg="Couldn't find frontend channel for key a5fb7c08-2a7a-4952-6b48-b6d9a30047b7. Closing frontend connection." 
time="2017-01-18T13:45:22Z" level=info msg="Couldn't find frontend channel for key a5fb7c08-2a7a-4952-6b48-b6d9a30047b7. Closing frontend connection." 
time="2017-01-18T13:45:23Z" level=info msg="Couldn't find frontend channel for key a5fb7c08-2a7a-4952-6b48-b6d9a30047b7. Closing frontend connection." 
time="2017-01-18T13:45:52Z" level=info msg="Couldn't find frontend channel for key a5fb7c08-2a7a-4952-6b48-b6d9a30047b7. Closing frontend connection." 
time="2017-01-18T13:45:53Z" level=info msg="Couldn't find frontend channel for key a5fb7c08-2a7a-4952-6b48-b6d9a30047b7. Closing frontend connection." 
time="2017-01-18T13:46:22Z" level=info msg="Couldn't find frontend channel for key a5fb7c08-2a7a-4952-6b48-b6d9a30047b7. Closing frontend connection." 
time="2017-01-18T13:46:23Z" level=info msg="Couldn't find frontend channel for key a5fb7c08-2a7a-4952-6b48-b6d9a30047b7. Closing frontend connection."

**Comment by soumyalj** [comment]
Tested with v1.3.2-rc2. Created a container which prints hello every second. After browsing the container logs, closed the browser. The same procedure was  followed for rancher-agent logs too. The  messages ```Couldn't find frontend channel for key a5xxxxxxxxxxx. Closing frontend connection. ``` are not seen in rancher/server logs.

**Comment by jstdoit** [comment]
is this bug solved? I am using `Rancher 1.3.2` & `Docker 1.12.3` & `CentOS 7`, and logs shown in the rancher/server.

> time="2017-01-23T16:25:17Z" level=info msg="Stats auth failed: Error parsing stats token. Failing auth. Error: token is expired" 
time="2017-01-23T16:25:23Z" level=info msg="Stats auth failed: Error parsing stats token. Failing auth. Error: token is expired" 
time="2017-01-23T16:25:30Z" level=info msg="Stats auth failed: Error parsing stats token. Failing auth. Error: token is expired" 
time="2017-01-23T16:25:38Z" level=info msg="Stats auth failed: Error parsing stats token. Failing auth. Error: token is expired" 
time="2017-01-23T16:25:47Z" level=info msg="Stats auth failed: Error parsing stats token. Failing auth. Error: token is expired" 
time="2017-01-23T16:25:52Z" level=info msg="Couldn't find frontend channel for key 8c8cfd18-1f38-493c-7810-6f830e35eb96. Closing frontend connection." 
time="2017-01-23T16:25:52Z" level=info msg="Couldn't find frontend channel for key 8c8cfd18-1f38-493c-7810-6f830e35eb96. Closing frontend connection." 
time="2017-01-23T16:25:52Z" level=info msg="Couldn't find frontend channel for key 8c8cfd18-1f38-493c-7810-6f830e35eb96. Closing frontend connection." 
time="2017-01-23T16:25:52Z" level=info msg="Couldn't find frontend channel for key 8c8cfd18-1f38-493c-7810-6f830e35eb96. Closing frontend connection." 
time="2017-01-23T16:25:52Z" level=info msg="Couldn't find frontend channel for key 8c8cfd18-1f38-493c-7810-6f830e35eb96. Closing frontend connection." 
time="2017-01-23T16:25:52Z" level=info msg="Couldn't find frontend channel for key 8c8cfd18-1f38-493c-7810-6f830e35eb96. Closing frontend connection." 
time="2017-01-23T16:25:52Z" level=info msg="Couldn't find frontend channel for key 8c8cfd18-1f38-493c-7810-6f830e35eb96. Closing frontend connection." 
time="2017-01-23T16:25:52Z" level=info msg="Couldn't find frontend channel for key 8c8cfd18-1f38-493c-7810-6f830e35eb96. Closing frontend connection." 
time="2017-01-23T16:25:57Z" level=info msg="Stats auth failed: Error parsing stats token. Failing auth. Error: token is expired" 
time="2017-01-23T16:26:08Z" level=info msg="Stats auth failed: Error parsing stats token. Failing auth. Error: token is expired" 
time="2017-01-23T16:26:20Z" level=info msg="Stats auth failed: Error parsing stats token. Failing auth. Error: token is expired" 
time="2017-01-23T16:26:33Z" level=info msg="Stats auth failed: Error parsing stats token. Failing auth. Error: token is expired" 
time="2017-01-23T16:26:35Z" level=info msg="Stats auth failed: Error parsing stats token. Failing auth. Error: token is expired"
