### ISSUE TITLE
Stacks API UI form is broken

### ISSUE THREAD

**Issue by mostafahussein** [rancher/rancher#7328]
**Rancher Versions: 1.2.1**

**Steps to Reproduce:**
1- Open this API url: `/v1/projects/1a5/environments`
2- Open Web Inspector (Tested on Chrome and Firefox)
3- Click Create then Choose "stack"

**Results:** 
The stack form won't load correctly and you will see the following error:
```
Uncaught TypeError: Cannot read property 'resourceFields' of null   environments:1
```
**Expected:**
The stack form should be loaded.

**Comment by vincent99** [comment]
`createTypes` has `stack` in it instead of `environment`, and `stack` is not a schema type in v1.  JS error is just a side-effect of it referring to a type that doesn't exist.
