### ISSUE TITLE
[NetworkManager] EL Atomic mounting issues

### ISSUE THREAD

**Issue by willseward** [rancher/rancher#7332]
**Rancher Versions:**
Server: 1.3.0
healthcheck: n/a
ipsec: n/a
network-services: 0.0.8
scheduler: n/a
kubernetes (if applicable):

**Docker Version:** 1.12.5
 
**OS and where are the hosts located? (cloud, bare metal, etc):** fedora-atomic/25/x86_64/docker-host (4.8.15)

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** internal db

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

I get this error when starting the network-manager container. 

```txt
Error (Error response from daemon: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:359: container init caused \\\"rootfs_linux.go:54: mounting \\\\\\\"/var/lib/docker/containers/5320b87cb4fb6d0ae1dc5b67efa8650be88e01f9a68496254b6ed5d10155f656/secrets\\\\\\\" to rootfs \\\\\\\"/var/lib/docker/devicemapper/mnt/210b31c85b3d46f8f4f7ad8a7016be828ea2b93423f41533608c3a924bb477ae/rootfs\\\\\\\" at \\\\\\\"/var/lib/docker/devicemapper/mnt/210b31c85b3d46f8f4f7ad8a7016be828ea2b93423f41533608c3a924bb477ae/rootfs/run/secrets\\\\\\\" caused \\\\\\\"mkdir /var/lib/docker/devicemapper/mnt/210b31c85b3d46f8f4f7ad8a7016be828ea2b93423f41533608c3a924bb477ae/rootfs/run/secrets: read-only file system\\\\\\\"\\\"\"\n")
```

**Comment by willseward** [comment]
```
Containers: 8
 Running: 4
 Paused: 0
 Stopped: 4
Images: 8
Server Version: 1.12.5
Storage Driver: devicemapper
 Pool Name: atomicos-docker--pool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file:
 Metadata file:
 Data Space Used: 1.046 GB
 Data Space Total: 2.147 GB
 Data Space Available: 1.101 GB
 Metadata Space Used: 659.5 kB
 Metadata Space Total: 8.389 MB
 Metadata Space Available: 7.729 MB
 Thin Pool Minimum Free Space: 214.4 MB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.136 (2016-11-05)
Logging Driver: journald
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: host bridge null overlay
Swarm: inactive
Runtimes: oci runc
Default Runtime: oci
Security Options: seccomp selinux
Kernel Version: 4.8.15-300.fc25.x86_64
Operating System: Fedora 25 (Atomic Host)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 2
CPUs: 1
Total Memory: 992.7 MiB
Name: atomic-2.localdomain
ID: JWTI:UOUR:K4HZ:D6L3:QGA3:Y7VS:LXDN:XQUC:XQR4:STD3:UY2T:VYAL
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
Registries: docker.io (secure)
```

**Comment by superseb** [comment]
Can you supply the steps to reproduce? Where are your hosts located? Are the server and the agent running on same infra and OS?

**Comment by willseward** [comment]
I had three atomic hosts running in virtualbox all attached to a host-only network. One ran the Rancher server, and the other two were agents.

**Comment by stoehrm5** [comment]
I can see the same error on a XEN VM. It happens approx in 50% of the tests I did so far. 

VM-OS:
        CentOS Linux release 7.3.1611 (Core)
        Linux 3.10.0-514.6.2.el7.x86_64
        docker 1.12.5
        rancher 1.4.1
        rancher-client on the same host as rancher-server

Steps done:

docker run -d --restart=always --name=rancher-server -v /var/lib/rancher:/var/lib/rancher -p 8080:8080 rancher/server
docker run -e CATTLE_AGENT_IP="........"  -d --privileged \
        -v /var/run/docker.sock:/var/run/docker.sock \
        -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.2.0 \
        http://.......:8080/v1/scripts/.....

Scenario 1: reboot + 'xe vm-shutdown force=true (== unplug power)' 
Scenario 2: reboot
Scenario 3: service docker stop; wait some seconds; pkill -f docker

**Comment by leodotcloud** [comment]
@willseward are you still having this problem, especially with the latest rancher releases?

**Comment by willseward** [comment]
Hmm... This was a long time ago, and I've since abandon atomic with Rancher.

Sorry that I can't be of more help.

**Comment by leodotcloud** [comment]
Please feel free to open a new issue if you face any problems.
