### ISSUE TITLE
Rancher Failing to Handle downed Hosts

### ISSUE THREAD

**Issue by InAnimaTe** [rancher/rancher#7335]
**Rancher Versions:**
Server: 1.3.0
healthcheck: nope
ipsec: default
network-services: default
scheduler: default (cattle)
kubernetes (if applicable): Nope, cattle.

**Docker Version:** 
Docker version 1.11.2, build bac3bae

**OS and where are the hosts located? (cloud, bare metal, etc):**
CoreOS 1185.5.0 (4.7.3) VPS on Vultr

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

Single Node, internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Create a couple hosts, spawn containers on them, kill destroy them (halt/shutdown), add another host.

**Results:** 

![screenshot from 2017-01-06 14-04-17](https://cloud.githubusercontent.com/assets/1192726/21729744/6a6d4d18-d41a-11e6-939b-21e7145d5dcb.png)

See more imagery [here](http://imgur.com/a/Ba9j4).

**Expected:**
A world where failures are recognized and re-mediated.

**Notes:**

I'm filing this issue to raise awareness about how Rancher acts in this scenario but also to alert the Rancher developers to how unorthodox this looks. Not trying to put down the platform or anything, but handling failures well is pretty important for a modern scheduler and I think a large amount of work needs to be done in this space to really see Cattle become more robust.

To give some context, we've written our own scripts for spawning a massive set of containers on Rancher called "*slaughterhouse*" (yes, we'll open source it soon hopefully). We did some testing last night on a few Vultr nodes. After we were done, we left the environment alone and destroyed the Vultr nodes themselves, then hit the sack. 

Today, Rancher still shows all the services as happy with both hosts disconnected. Adding another host doesn't see any services re-balanced on it, so everything stays exactly how it is. AFAIK from other issues I've seen, I believe a combo of healthchecks and/or manually deactivating hosts solves this problem. However, in my mind (and albeit others`), it doesn't seem right that manual work is necessary for a scheduler to handle host failures.

Finally, I want to note that the Rancher developers, community and other aspects of the platform are fantastic. We've been using Rancher for a while even writing a libcloud [driver](http://libcloud.readthedocs.io/en/latest/container/drivers/rancher.html) for it and contributing other PR's etc.. We plan to continue using it in some capacity and recommend it to almost everyone we talk with, but are definitely looking at other solutions for larger scale SaaS needs.

**Comment by vincent99** [comment]
The agent being disconnected does not mean the containers are no longer running.  This sounds dumb but it is of critical importance for some use-cases.

So if you want containers to be automatically rescheduled the services need to have healthchecks defined.

**Comment by vincent99** [comment]
2.0 shows things as `Unknown` in this situation.
