### ISSUE TITLE
Why does Rancher start a swarmkit container in 1.2+?

### ISSUE THREAD

**Issue by mrcamp** [rancher/rancher#7336]
I might be misunderstanding something here, but I thought the Rancher 1.2+ was switching Swarm functionality to using the new native Swarm Mode in Docker 1.12+, replacing swarmkit. In Rancher 1.2.2 and 1.3.0, each host in a Swarm environment sees a swarmkit container automatically launched. Further, the "Swarm Mode" variable on the hosts remains False.

Shouldn't the Swarm environments in Rancher be able to work natively with Swarm Mode in the docker engine?

**Comment by LLParse** [comment]
The swarmkit container includes the docker client and a script that automates the process of building the swarm by sending commands to the underlying Docker daemon. It includes other features such as automatically joining/removing hosts to a swarm as an environment's hosts are modified, maintaining resiliency by promoting/demoting managers/workers in the face of host failure/removal. Such operations would normally require manual user intervention (along with a basic understanding of the administration process).

**Comment by LLParse** [comment]
You can verify this by allowing the swarmkit containers to enter running state (green circle), then deleting the swarm stack. The hosts will still be joined together in a swarm, but the operational automation will no longer function.

**Comment by deniseschannon** [comment]
@mrcamp If you still have questions, please re-open.
