### ISSUE TITLE
Rancher UI Unable to Pull AWS ECR Image

### ISSUE THREAD

**Issue by ptarpan** [rancher/rancher#7338]
**Rancher Versions:**
Server:1.1.4
healthcheck:
ipsec:n/a
network-services:n/a
scheduler:n/a
kubernetes (if applicable):n/a

**Docker Version:**
1.12.5
**OS and where are the hosts located? (cloud, bare metal, etc):**
AWS EC2
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node 
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
Launch a single node that runs the rancher (server and agent) container on a single node. 
**Results:** 
Activating (Waiting for [instance:<instance_name>]. Instance status: Image [<ecr_uri>] failed to pull: unauthorized: authentication required)
**Expected:**
All services up 

Note: If a "docker pull" to AWS ECR is ran through ssh, the command succeeds and the services through the UI get deployed. So, the question is, even though the server/agent containers are launched using root which UI user does rancher use to talk to the "agent"?

**Comment by ptarpan** [comment]
In addition to the above, we are unable to launch an "ECR service" as the following error is being thrown: 
"Activating (Failed to allocate instance [204]: Object [instance:204] failed to satisfy predicate [15000] millis)"

**Comment by goffinf** [comment]
Have you set up ECR as a private registry. That's where you specify both your ECR repository name, user-name (AWS) and AWS access key. Also be aware that the password will expire every 12 hours so you need to implement an approach to updating it.

**Comment by LoicMahieu** [comment]
We use ECR outside of AWS infra (so no magic authentication) and we use https://github.com/objectpartners/rancher-ecr-credentials which works pretty well.

**Comment by superseb** [comment]
If you configure this using the docs, do you still experience issues? http://rancher.com/docs/rancher/v1.6/en/environments/registries/#using-amazons-ecr-registry

**Comment by superseb** [comment]
Please reply if you need help on this.
