### ISSUE TITLE
Container DNS Fails under Load

### ISSUE THREAD

**Issue by schuylr** [rancher/rancher#7340]
**Rancher Versions:**
Server: 1.2.2
healthcheck: 0.2.0
ipsec: 0.8.1
network-services: 0.4.0
scheduler: 0.5.0

**Docker Version:** 1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):** AWS EC2

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** Single Node External DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:**

I have a workhorse server that performs imports and mass uploads to an Elasticsearch container on another server. To allow for faster imports, I have 16-24 processes that perform the importing, and then indexing to Elasticsearch. Naturally, I use service links to resolve the path to the elasticsearch server. (e.g. `http://elasticsearch:9200`)

**Results:** 

Here's the error:

```
A Faraday::ConnectionFailed occurred in background at 2017-01-06 23:42:07 UTC :

  Failed to open TCP connection to elasticsearch:9200 (Hostname not known: elasticsearch)
  /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/http.rb:882:in `rescue in block in connect'
```

With a single thread, the hostname resolves. I can also do `curl http://elasticsearch:9200` with no issues, however with more than 8 threads, the above occurs across nearly all of the processes.

**Expected:**

Before the upgrade to Rancher 1.2, this was not an issue. I would expect to be able to make multiple concurrent DNS requests and not have this issue.

I can reproduce this reliably and provide logs wherever needed.

**Comment by aemneina** [comment]
@schuylr have you seen this in more modern versions of rancher?

**Comment by schuylr** [comment]
@aemneina I've been using container IPs as a workaround. I will try the service links again and report back soon.
