### ISSUE TITLE
Environment state will stay in degraded after deleting stack that is unhealthy

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#7341]
**Rancher Versions:** v1.3.0

**Steps to Reproduce:**
1.  Create two stack and add a service to them
2. Stop one of the services (so now if you go to manage environment the environment will say degraded)
3. Delete stack that has stopped service (so now you have 1 stack that is active)
4. Go to manage environment

**Results:** Environment will show up as degraded until you restart the lone service and get the current stack switch out of active state back to active.  Or if you do anything that will create a new active stack.  Basically the state only changes on add/restart but not on delete.

**Expected:** Environment should change to active if all stacks are active.  Even if it's because I deleted unhealthy stack.

**Comment by vincent99** [comment]
This appears to be wrong in the API..

**Comment by tfiduccia** [comment]
Version - master 1/24
This is still not fixed.  My environment still says degraded although all my stacks are healthy
![image](https://cloud.githubusercontent.com/assets/11514927/22261839/bc91802c-e22b-11e6-8e49-cd813a66efb2.png)

![image](https://cloud.githubusercontent.com/assets/11514927/22261853/c8e2a946-e22b-11e6-88d8-6ab5dad0f706.png)

**Comment by tfiduccia** [comment]
Version - 1.4.0-rc3
Verified fixed
