### ISSUE TITLE
Add --advertise-address "awslocal" ?

### ISSUE THREAD

**Issue by PicoCreator** [rancher/rancher#7343]
**Rancher Versions:**
 v1.2 HA deployment

**Details:**
Add support --advertise-address "awslocal".

This can be used to automatically detect AWS instance local host IP addresses, within an AWS host / ECS cluster.

A local host IP is useful, as users may have different security address or host binding for local IP's, and external IP's for security reasons.

Also added more details into help documentation command.

**Pull Request Done:**
#7250

**Comment by PicoCreator** [comment]
Closed with https://github.com/rancher/rancher/commit/76d2ef623ed59497debce1612c842e4a4151564f merge.

**Comment by obenziane2** [comment]
This only works if you the userdata to manage the rancher docker images
