### ISSUE TITLE
Expect the system upgrade all containers at the same time

### ISSUE THREAD

**Issue by artemus717** [rancher/rancher#7344]
**Rancher Versions:**
Server: 1.2.2
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker Version:**
1.11.2
**OS and where are the hosts located? (cloud, bare metal, etc):**
CentOS 7.2
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher  external DB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**

**Results:** 
I put a service  in two environment ,like  Env-A, Env-B.
When upgrade a service , the system upgrade containers one by one.
**Expected:**
In emergency situation , i expect the system upgrade all containers at the same time .

**Comment by vincent99** [comment]
You can set the batch size to a big number if you want all the containers to be upgraded at the same time; breaking the service is generally not desired behavior.
