### ISSUE TITLE
Deploy / delete stacks fails

### ISSUE THREAD

**Issue by pwFoo** [rancher/rancher#7345]
RancherOS 0.7.1
RancherServer 1.3 (updated from older versions)

Created an stack by docker-compose / rancher-compose file failed (for example missing env file, not moved to inline env vars before creation) failed with an empty stack which can't be deleted.

**Comment by pwFoo** [comment]
Also certificates can't be deleted anymore?

**Comment by pwFoo** [comment]
No service / stack can't be deletet since Rancher Server >= 1.3.x?

Try to delete a stack / service I get an transparent overlay, the context menu keeps open and that's it. Click again at context menu it closes, but transparent, empty overlay is still there. Click at the overlay during context menu hangs the overlay is closed without an action.

**Comment by pwFoo** [comment]
Any update here?

RancherOS 0.7.1 should be supported from Rancher Server.

```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 23:26:11 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 23:26:11 2016
 OS/Arch:      linux/amd64
```

Deleted all container and volumes. Clean fresh install done with Rancher 1.3.3.

- can't add hosts
- can't delete stacks (same problem as described above...)

Rancher server mysql log

bootstrap.log 
```
root@8c8e22264f4d:/# tail -f /var/log/bootstrap.log 
gpg: key EFE21092: public key "Ubuntu CD Image Automatic Signing Key (2012) <cdimage@ubuntu.com>" imported
gpg: Total number processed: 4
gpg:               imported: 4  (RSA: 2)
Setting up libstdc++6:amd64 (4.8.2-19ubuntu1) ...
Setting up readline-common (6.3-4ubuntu2) ...
Setting up libapt-pkg4.12:amd64 (1.0.1ubuntu2) ...
Setting up libreadline6:amd64 (6.3-4ubuntu2) ...
Setting up gnupg (1.4.16-1ubuntu2) ...
Setting up apt (1.0.1ubuntu2) ...
Processing triggers for libc-bin (2.19-0ubuntu6) ...
tail: unrecognized file system type 0x794c7630 for â€˜/var/log/bootstrap.logâ€™. please report this to bug-coreutils@gnu.org. reverting to polling
```

```
root@8c8e22264f4d:/# tail -f /var/log/mysql.log 
tail: unrecognized file system type 0x794c7630 for â€˜/var/log/mysql.logâ€™. please report this to bug-coreutils@gnu.org. reverting to polling
```
host (RancherOS) fs type is **ext4**

So Rancher Server isn't compatible to RancherOS ?! Or is Rancher Server buggy / broken ?!

@deniseschannon

**Comment by pwFoo** [comment]
fs type error seems to be fixed with rancher server v1.4.0-rc6 and add hosts work again, but still stacks by compose file doesn't work. Won't be deployed (stack stays emtpy) and stack can't be deleted.

**Comment by pwFoo** [comment]
**Deploy stack with compose file**
It was exported by Rancher Server 1.3.3 and isn't compatible with 1.4 (rc)? So deploy with Rancher Server UI should work again with 1.4.

**Delete stack**
Works with CentOS 7, Docker 1.13! Confirmation popup doesn't open at RancherOS 0.7.1. Is it a OS releated Rancher UI bug...?

**Comment by pwFoo** [comment]
Tested with **1.5.0-rc6**
Fresh install, added owncloud from catalog, tried to delete.
Bug still there... 👎 

Screenshot after click delete:
![rancherui_bug](https://cloud.githubusercontent.com/assets/333408/23556026/4d65fd4a-002b-11e7-9532-d37e8f78748d.png)

**Comment by vincent99** [comment]
I don't remember ever seeing this issue before but highly doubt it had anything to do with RancherOS.  There's probably an invalid translation in the language you're on (German?).

**Comment by pwFoo** [comment]
German was auto selected... I switched to English and it seems to work! Thanks.
