### ISSUE TITLE
Rancher LB wrong certificate, correct backend server

### ISSUE THREAD

**Issue by pwFoo** [rancher/rancher#7346]
- Rancher 1.3, RancherOS 0.7.1 
- Certificates get from Lets Encrypt by https://github.com/tozny/rancher-lets-encrypt.

After upgrade service the Rancher LB deliver the correct backend contents but with the wrong certificate.

Tested with Firefox, Chrome, Edge @ Win10

Any idea why haproxy send me the wrong certificate after backend container is upgraded?

Also restarted / upgraded LB to solve it, without success.

**Comment by pwFoo** [comment]
Workaround is to change the default certificate to another / the needed one. Then both domains work fine again...

**Comment by aemneina** [comment]
@pwFoo do you have a sample docker|rancher-compose yamls that reproduce this?

**Comment by pwFoo** [comment]
It isn't one stack, but two different / independent backends which added to the global web lb (http/s).

The first is a gogs container / stack. Second is the rancher server itself. 
Same domain, but different subdomain. 

Certificates get by lets encrypt (https://github.com/tozny/rancher-lets-encrypt).

**Comment by pwFoo** [comment]
Moved back to custom reverse proxy with lets encrypt.
