### ISSUE TITLE
HAProxy Example is wrong

### ISSUE THREAD

**Issue by longwuyuan** [rancher/rancher#7351]
**Rancher Versions:**1.3
Server:
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker Version:**

**OS and where are the hosts located? (cloud, bare metal, etc):**

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**
Go to https://docs.rancher.com/rancher/v1.3/en/installing-rancher/installing-server/basic-ssl-config/
**Results:** 
See that NGINX example uses 8080 for backend but HAProxy example uses SSL as well as 443 for backend
**Expected:**
HAProxy example also use 8080 and NON-SSL for backend

Hi,

The HAProxy example at https://docs.rancher.com/rancher/v1.3/en/installing-rancher/installing-server/basic-ssl-config/  seems to conflict with the NGINX example on the backend connection for port & protocol.

Thanks,

**Comment by aemneina** [comment]
created pr [614](https://github.com/rancher/rancher.github.io/pull/614) to address the changes to haproxy config for 1.2.x+ installs. @longwuyuan care to test those changes?

**Comment by longwuyuan** [comment]
@aemneina, thnks, i will test and update

**Comment by aemneina** [comment]
hey @longwuyuan  did you manage to get this working?

**Comment by longwuyuan** [comment]
@aemneina I did not know that I can use Global HTTP mode and One frontend in TCP mode in HAProxy. I switched to using Nginx for multiple SSL terminations because there are multiple software services using one single reverseproxy in our infrastructure. I am setting up a pilot environment to test this HAProxy config and will update here asap.

**Comment by longwuyuan** [comment]
@aemneina , I keep getting thrown back to login page after i submit credentials but If I put nginx in front, all is perfect.

Beg to know if this config in the docs is working in your QA/CI environment. Also, the TCP mode is disturbing because the need for HAProxy is the unique http/https headers related options in haproxy (which may be near impossible in nginx)

**Comment by longwuyuan** [comment]
@aemneina , just fyi, besides the hostname and ipaddress+portnumber, i just appended the precise documented config into a default install of haproxy from ubuntu repos, on xenial. I did not  delete the default parameters but now I will try to empty the default config file and test with a replica of what is documented

**Comment by longwuyuan** [comment]
@aemneina ... below worked (xenial  apt-get install haproxy );

lobal
	log /dev/log	local0
	log /dev/log	local2 info
	chroot /var/lib/haproxy
	pidfile     /var/run/haproxy.pid
	stats socket /run/haproxy/admin.sock mode 660 level admin
	stats timeout 30s
    # max per-process number of connections
    	maxconn 2048
	user haproxy
	group haproxy
	daemon

	ssl-server-verify none
    	tune.ssl.default-dh-param 2048

	# Default SSL material locations
	ca-base /etc/ssl/certs
	crt-base /etc/ssl/private

	# Default ciphers to use on SSL-enabled listening sockets.
	# For more information, see ciphers(1SSL). This list is from:
	#  https://hynek.me/articles/hardening-your-web-servers-ssl-ciphers/
	ssl-default-bind-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:RSA+3DES:!aNULL:!MD5:!DSS
	ssl-default-bind-options no-sslv3

defaults
	log	global
	mode	http
	balance roundrobin
	option redispatch
	option forwardfor
	option http-server-close
	option	httplog
	option	dontlognull
        timeout connect 10s
	timeout queue 10s
        timeout client  30s
        timeout server  30s
	errorfile 400 /etc/haproxy/errors/400.http
	errorfile 403 /etc/haproxy/errors/403.http
	errorfile 408 /etc/haproxy/errors/408.http
	errorfile 500 /etc/haproxy/errors/500.http
	errorfile 502 /etc/haproxy/errors/502.http
	errorfile 503 /etc/haproxy/errors/503.http
	errorfile 504 /etc/haproxy/errors/504.http
	stats enable
   		stats uri /stats
   		stats realm Haproxy\ Statistics
   		stats auth uzer:poss	

frontend https-in
	mode http
    	bind *:443 ssl crt /etc/ssl/private/haproxy.pem
#	reqadd X-Forwarded-Proto:\ https
	http-request add-header X-Forwarded-Proto https if { ssl_fc }
	default_backend rancher_servers

backend rancher_servers
	mode http
    	server rancherserver ip.ip.ip.ip:8080 check

-------------------------------------------------------------------------------------------------------------------------

root@dlp:~# vi /etc/rsyslog.conf
# line 18,19: uncomment, line 20: add
module(load="imudp")
input(type="imudp" port="514")
$AllowedSender UDP, 127.0.0.1
root@dlp:~# vi /etc/rsyslog.d/50-default.conf
# line 9: change and add like follows
*.*;auth,authpriv.none;local2.none              -/var/log/syslog
local2.*                        /var/log/haproxy.log

root@dlp:~# systemctl restart rsyslog

**Comment by longwuyuan** [comment]
Ignore "reqadd X-Forwarded-Proto:\ https" ... supposedly old-syntax as per #haproxy on freenode

**Comment by longwuyuan** [comment]
@aemneina @deniseschannon should I close the issue or wait for changes (if any) to docs
