### ISSUE TITLE
Are there any docs for custom LBs yet?

### ISSUE THREAD

**Issue by wzrdtales** [rancher/rancher#7352]
As I can't find any reference anywhere about that topic I am opening an issue here :)

So the question is really about everything that is essential when going to build own load balancers that use e.g. NGINX. I know there is a API doc, but there does seem to be no docs at all about stuff like how a custom LB should handle the service discovery.

Am I just overseeing those docs, if so please post me a link to it :), if not are there some docs in work? I guess for now I will fight through the source of the default lb.

Thank you!

**Comment by wzrdtales** [comment]
As Ic right now, it is intended to really build upon the lb-controller and add a provider to it. I guess there really aren't any docs there yet?

**Comment by vincent99** [comment]
The information you need is available in metadata, so you basically watch for changes and apply the relevant configuration.  Implementing a new provider in lb-controller manages the watching part for you so you just have to implement a few methods to configure, reload, etc.

The UI doesn't show a field to change the balancer image but you can update `/v2-beta/settings/  lb.instance.image` to point somewhere else.
