### ISSUE TITLE
Feature Request: Add ability to look host up in metadata service by UUID

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#7354]
**Rancher Versions:**
Server: 1.3.0

I can get the host_uuid from a container that's apart of my service, but I can't lookup the host by its uuid, so I have to restort to looping through.

I need a way using confd and rancher metadata service to be able to lookup the agent_ip of the host that another container is on.

For example I use consul for locking and k/v purpose, its a clusterable service and I need to run the consul server on named servers who's IPs cannot change and hostname cannot change either, I also need to be able to join them together into a cluster. Using confd container as a sidekick gets me really close, save for that I cannot get the IP addresses of the hosts where the other containers are running.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
