### ISSUE TITLE
[AWS EC2 Docker Machine Driver] Key Pair Not Removed on Host Delete When Host Creation Fails

### ISSUE THREAD

**Issue by ThatsNinja** [rancher/rancher#7357]
**Rancher Versions:**
Server: _v1.2.1_
healthcheck: _N/A_
ipsec: _N/A_
network-services: _N/A_
scheduler: _N/A_
kubernetes (if applicable): _N/A_

**Docker Version:**
_N/A_

**OS and where are the hosts located? (cloud, bare metal, etc):**
_AWS EC2, Provisioned via Docker Machine driver_

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
_Rancher HA, 3 hosts_

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
_Cattle_

**Steps to Reproduce:**
1. Create RancherOS-based AMI from snapshot of a 40G volume;
2. Click 'Add Host' from w/in Rancher Server UI, use Amazon Docker Machine driver to provision hosts, and configure host volume smaller than 40G;
3. See resulting error;
4. Click 'Delete' from the fly-out context menu for the hosts which failed to create;
5. Attempt to provision hosts with the same name;
6. See error related to creation of key pair.

**Results:** 
When host creation fails, keys are created but not removed.

**Expected:**
Key pair should always be removed when 'Delete' is clicked for a given host.

**Comment by ThatsNinja** [comment]
@deniseschannon seems you typically triage my issues. sorry if i'm tagging you inappropriately.
did this one fall through the cracks?

**Comment by vincent99** [comment]
This would be bug in [docker/machine](https://github.com/docker/machine], we're pretty much just calling it with the options passed in and then hook in to register the host at the end.

**Comment by ThatsNinja** [comment]
thanks @vincent99! great work, everyone! rancher 1.4 rocks my world!
