### ISSUE TITLE
Service Links - When accessing service links , only 1 instance from the linked service is being accessed all the time.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#736]
Service Links - When accessing service links , only 1 instance from the linked service is being accessed all the time.

Version - V0.19.1

Create service1 with 2 instances.
Create service2 with 3 instances.
Link service2 to service1.

From instances of service1 , tried to access service2 multiple times.
I see that only 1 instance (the first instance from the resolved list of container ips) is being accessed all the time.

**Comment by alena1108** [comment]
@ibuildthecloud @vincent99 in rancher DNS, are we supposed to roundrobin or do random picks from the instance resolved list? Looks like we are always picking up the first one from the list

**Comment by vincent99** [comment]
DNS returns multiple A records, and the client is supposed to pick a random one.  Maybe some libraries don't though and we should randomize the list in rancher-dns before returning them.  Even if your DNS library does pick a random one it's likely going to be cached for the 10 min default TTL so you will keep using that IP.  DNS roundrobin is not load balancing.

@sangerthah what are you making these requests with?

**Comment by sangeethah** [comment]
I am doing a wget request to nginx containers that return their container names.

**Comment by sangeethah** [comment]
When using dig command ,we are able to see that DNS resolution for a service name with scale 3 returns all 3 ip address of the containers . Also the order in which the ip address are returned are random , so when dig is done multiple times we see the ip address list being shuffled. This confirms that rancher DNS returns multiple records in random order.
