### ISSUE TITLE
Sync k8s services with Rancher on kubernetes-agent startup

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#7360]
@ibuildthecloud hit the condition when Dashboard service was started before kubernetes-agent was up (the service responsible for syncing k8s services with rancher = creating corresponding k8s service in Rancher). It resulted in Dashboard not being available in Rancher although it was present on k8s side.

Looks like the fix should be - do some sort of full sync on the kubernetes-agent init (and perhaps run it once in 10 mins - configurable - when kubernetes-agent is up)

**Comment by galal-hussein** [comment]
Rancher version: v1.3.1-rc1

Steps used to validate the fix:

- Create a catalog template for k8s with no rancher-kubernetes-agent
- Deploy this version of kubernetes
- Create few services
- The services shouldn't appear in v2-beta/projects/1a5/kubernetesservice and dashboard shouldn't be working.
- Upgrade kubernetes to the newer version v1.5.1-rancher1-8 with rancher-kubernetes-agent v0.5.2
- Make sure that services are now appearing in v2-beta/projects/1a5/kubernetesservice and the dashboard is working.
- Any new services should appear in v2-beta/projects/1a5/kubernetesservice as well.

**Comment by pulberg** [comment]
@galal-hussein "Image [index.docker.io/rancher/k8s:v1.5.1-rancher1-8] failed to pull: Pulling repository docker.io/rancher/k8s"  i looked and there is no image tagged as 1-8, 1-7 is the most recently available.

**Comment by wlan0** [comment]
@pulberg The k8s image was not update. The version that @galal-hussein mentioned was the rancher-catalog version. 

Ref - https://github.com/rancher/rancher-catalog/blob/v1.3.1-rc1/infra-templates/k8s/17/rancher-compose.yml#L3

**Comment by pulberg** [comment]
@wlan0 ok, but if the "steps used to validate" says - 

"Upgrade kubernetes to the newer version v1.5.1-rancher1-8", then what do you think a user is going to do?, we are going to click on "upgrade" next to the affected service, and change the "select image" attribute to the one in which it says to upgrade to.  The rancher-kubernetes-agent upgrade worked this way.

**Comment by wlan0** [comment]
@pulberg - that's why i clarified above.
