### ISSUE TITLE
Download links for compose and CLI are old version

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#7361]
**Rancher Versions:**
Server: v1.3.0

**Steps to Reproduce:**

Use download links to download compose/CLI, but old versions are downloaded.

**Results:** 

rancher-compose v0.12.0
cli: v0.4.0 

**Expected:**

rancher-compose v0.12.1
cli: v0.4.1

**Comment by soumyalj** [comment]
Tested with v1.3.1-rc1. Rancher-compose download links point to v0.12.1 for Mac/Linux/Windows
Rancher CLI download links point to v0.4.1 for Mac/Linux/Windows
