### ISSUE TITLE
k8s dns reflected ip address of previously destroyed service

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#7363]
**Rancher Versions:**
Server: 1.1.4
kubernetes (if applicable): 1.2.4

**Docker Version:**
1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
ROS 0.4.5

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA

**Steps to Reproduce:**
TBD, but possibly a race condition where services were deployed/destroyed/recreated in fast succession.

**Results:** 
DNS had the ip address of previously created service ip, and wouldnt be cleared with destroying/recreation of subsequent instances of service.

**Expected:**
DNS to reflect what is currently present in k8s environment.

Logs for server on request.

**Comment by aemneina** [comment]
the workaround was to identify the bogus entry, locate it using the rancher api, and deleting it there.

**Comment by aemneina** [comment]
identify entry using nslooup svcname.svc.cluster.local and noticed multiple entries, only one would resolve. `/var/lib/cattle/etc/cattle/dns/answers.json` had stale and valid entries. DB had active vip's for valid and invalid service ip's `select id,name,state,kind,vip from service where vip in ("bogus ip", "valid ip")`. Navigate to environment/service via the rancher api, removed the invalid service from the API resolved the issue.

**Comment by rsuniev** [comment]
Seeing the same problem in Rancher Server: **1.2.2**.

**Comment by aemneina** [comment]
Should be resolved. Closing this out.
