### ISSUE TITLE
rabbitmq catalog item has no healthchecks

### ISSUE THREAD

**Issue by ookongo** [rancher/rancher#7364]
Hi,

I've run into an issue where one of the hosts (5 hosts - 1 of them is running rancher/server) 
became unresponsive and caused the rabbitmq cluster to get into a continously trying to restart state.

How do I get healthchecks enabled for it.

Fix required a restart of the entire cluster after getting the "down" host back up and restarting the rabbitmq cluster. :-(
No joy for a rabbitmq cluster starting to support production workloads.....

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.2.2` Cattle: `v0.174.13` UI: `v1.2.40` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`stacks.index`|

**Comment by vincent99** [comment]
You can put a PR in to the community-catalog for it, and/or upgrade you service to add a health check in the meantime.
