### ISSUE TITLE
rancher-cli export environnment template not working

### ISSUE THREAD

**Issue by jeanlouisboudart** [rancher/rancher#7367]
**Rancher Versions:**
Server: 1.3.0 
Rancher-cli : 0.4.1

**Docker Version:**
1.12
**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04 baremetal && cloud

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
external db

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
* Export an environnement template via rancher-cli (v0.4.1).
* Store the template as a file 
* Import the file as a new environnement template

**Results:** 

The template is imported without errors, but no stack are available

**Expected:**
Have export/import environnement template working :)

**Comment by jeanlouisboudart** [comment]
Looks like the cli export "template_id" instead of "templateId". 

I tried to fix the typo manually in the exported version and imported back and it works?

**Comment by jeanlouisboudart** [comment]
Any update on this ?

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
