### ISSUE TITLE
Get /v2-beta/accounts won't return result if you are not in first 100 results

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#7368]
**Rancher Versions:** v1.3.0

**Steps to Reproduce:**
1.  Log into OpenLDAP (or any other authentication)
2. Have more than 100 user accounts (non-admin)
3.  Log into account 101 or greater
4.  Go to API and go to /v2-beta/accounts

**Results:** No results

**Expected:**  Should have results

**Comment by galal-hussein** [comment]
@tfiduccia Tested with version 1.4.0-rc2, the steps i followed:

- Have more than 100 users in OpenLDAP setup
- Enable LDAP authentication with Rancher
- Logged in with user 101
- Went to /v2-beta/accounts with the user101

I can found the account information for the 101 user in /v2-beta/accounts.
