### ISSUE TITLE
MountVolume.SetUp failed, Output: mount: special device /var/lib/kubelet/plugins/kubernetes.io/aws-ebs/mounts/vol-* does not exist

### ISSUE THREAD

**Issue by emk** [rancher/rancher#7370]
This appears to be very similar to #4444 except that it occurs with current Rancher & Kubernetes. See also https://github.com/rancher/rancher/issues/4444#issuecomment-266211104, which appears to be another user hitting this bug.

**Rancher Versions:**
Server: 1.3.0
healthcheck: ?
ipsec: ?
network-services: ?
scheduler: ?
kubernetes (if applicable): rancher/k8s:v1.5.1-rancher1-7

**Docker Version:** 1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):** Rancher is running in a container on an AWS ECS server.

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** Single node Rancher run in test mode with internal data storage.

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Kubernetes

**Steps to Reproduce:**

1. Create a new EBS volume.
2. Using the same manifest from #4444, edit the volumeID to match your EBS volume, and deploy it to the cluster.
3. Set up the kubernetes nodes with the following IAM policy at creation time:

```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "ec2:AttachVolume",
        "ec2:DetachVolume"
      ],
      "Resource": "arn:aws:ec2:us-east-1:xxxxxxxxxxxx:instance/*"
    },
    {
      "Effect": "Allow",
      "Action": [
        "ec2:AttachVolume",
        "ec2:DetachVolume"
      ],
      "Resource": "arn:aws:ec2:us-east-1:xxxxxxxxxxxx:volume/*"
    }
  ]
}
```

I can also reproduce the problem using `EC2FullAccess`:

```json
 {
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": "ec2:*",
      "Effect": "Allow",
      "Resource": "*"
    },
    {
      "Effect": "Allow",
      "Action": "elasticloadbalancing:*",
      "Resource": "*"
    },
    {
      "Effect": "Allow",
      "Action": "cloudwatch:*",
      "Resource": "*"
    },
    {
      "Effect": "Allow",
      "Action": "autoscaling:*",
      "Resource": "*"
    }
  ]
}
```

**Results:** The EBS volume cannot be attached, and it gives the following error:

> MountVolume.SetUp failed for volume "kubernetes.io/aws-ebs/adc7c136-d77a-11e6-978a-b6d2eaf5775b-html-volume" (spec.Name: "html-volume") pod "adc7c136-d77a-11e6-978a-b6d2eaf5775b" (UID: "adc7c136-d77a-11e6-978a-b6d2eaf5775b") with: mount failed: exit status 32 Mounting command: mount Mounting arguments: /var/lib/kubelet/plugins/kubernetes.io/aws-ebs/mounts/vol-xxxxxxxxxxxxxxxx /var/lib/kubelet/pods/adc7c136-d77a-11e6-978a-b6d2eaf5775b/volumes/kubernetes.io~aws-ebs/html-volume [bind] Output: mount: special device /var/lib/kubelet/plugins/kubernetes.io/aws-ebs/mounts/vol-xxxxxxxxxxxxxxxx does not exist

**Expected:** The EBS volume should attach normally.

**Comment by LLParse** [comment]
@emk You will need to upgrade your kubernetes stack and select AWS as your cloud provider. To do so:
1. Navigate to Kubernetes > Infrastructure Stacks
2. Click the *Up to date* button and select your current version from the dropdown
3. Change cloud provider to AWS
4. Click *Upgrade*

After doing this, your stack should be capable of using the aws-ebs plugin.

@deniseschannon Can we add this to the documentation somewhere? The associated error message is rather cryptic.

**Comment by LLParse** [comment]
https://github.com/rancher/rancher/issues/7455

**Comment by tfiduccia** [comment]
As we have a bug already #7455 to document the additional steps for this to work.  I'm going to close this bug.  @emk - if you are still having problems after this, please re-open.

**Comment by seamusabshere** [comment]
awesome thanks @LLParse and @tfiduccia !
