### ISSUE TITLE
OpenLDAP - Group sync issue when memberOf property is not exposed by LDAP

### ISSUE THREAD

**Issue by prachidamle** [rancher/rancher#7371]
**Rancher Versions:**
Server: 1.3
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
1) Enable Access Control and configure openLDAP
2) Have few groups with users in the directory
3) LDAP should not have memberOf property exposed in user schema
4) Make sure groups of a user are synced during login
5) Make sure environments can be shared between users by making groups a member

**Results:** 
When memberOf property is absent in user schema, group sync is not working.

**Expected:**
Group sync and environment sharing should be supported.

**Comment by tfiduccia** [comment]
Version - master 1/24
Verified fixed
