### ISSUE TITLE
Fresh API credentials cannot provision new stacks

### ISSUE THREAD

**Issue by pedrommone** [rancher/rancher#7372]
I'm just creating API Tokens as usually but they cannot be used to create new stacks.

##### Token created
![](http://i.imgur.com/K2Xzm6s.png)

##### Using with Postman
![](http://i.imgur.com/xGYnFvL.png)

##### Using with Rancher Compose
```
➜  masked git:(hotfix/headers-cache) ~/Downloads/rancher-compose-v0.12.1/rancher-compose --access-key=587A43BF93215C040BA8 --secret-key=y5PTb9Wjhr5cezj58qdfg6RSkR5D3LfAFvGzxB7T --url http://rancher.masked.com/v1 up
ERRO[0001] Failed to open project masked: Can not create a stack, check API key [587A43BF93215C040BA8] for [http://rancher.masked.com/v1] 
FATA[0001] Failed to read project: Can not create a stack, check API key [587A43BF93215C040BA8] for [http://rancher.masked.com/v1] 
```

As you can see, they dont work :(

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.2.2` Cattle: `v0.174.13` UI: `v1.2.40` |
|Access|`github` `admin`|
|Orchestration|`Cattle`|
|Route|`admin-tab.settings`|

**Comment by vincent99** [comment]
You're probably creating an account API key instead of one for a particular environment.  rancher-compose only works with environment keys.

**Comment by pedrommone** [comment]
@vincent99 released it before but... made some tests and still doest work. Even created the API Key with the API.

**Comment by nayyden** [comment]
@pedrommone Hi, i had the same problem, make sure you create an environment key (check the image)
![image](https://cloud.githubusercontent.com/assets/325479/21854304/ea3cb4e6-d822-11e6-80e2-0b543314a7d4.png)

**Comment by pedrommone** [comment]
Thanks for reply. Solved this one :).
