### ISSUE TITLE
Service links across stacks are not resolvable

### ISSUE THREAD

**Issue by JoelESvensson** [rancher/rancher#7377]
**Rancher Versions:**
Server: 1.3.0
healthcheck: v0.2.0
ipsec: v0.8.1
network-services: v0.4.0
scheduler: v0.5.0

Docker Version: 1.12.3

OS and where are the hosts located? Openstack with latest stable CoreOS (currently 1235.6.0)

Setup Details: Single node

Environment Type: Cattle

Steps to Reproduce: Create `service1` in `stack1. Create `service2` in `stack2`, which is linked to `service1` in `stack1` with the default alias of `service1`. Then try resolving the hostname of `service1`

Results: Hostname won't resolve.

Expected: Resolved IP of hostname

**Comment by ephillipe** [comment]
Same with me.

**Comment by sgrunt91** [comment]
Me too...
I use `external_links` between two stacks it's not working:
```
services:
  stack1:
    blah blah
    external_links:
    - stack2/service2:alias
```

**Comment by aemneina** [comment]
is this still reproducible? What image are you using thats facing issues?

**Comment by flantel** [comment]
Hi @aemneina  I have just checked this on v1.5.9 and it appears to work as expected now.
