### ISSUE TITLE
Error if I upgrade without making changes

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#7381]
**Rancher Versions:** master 1/11

**Steps to Reproduce:**
1.  Create a service
2.  After it Activates, click on upgrade menu option for service
3.  Go to bottom and click Upgrade without making any changes
4.  Click on finish upgrade in menu

**Results:** Finishupgrade error shows up
![image](https://cloud.githubusercontent.com/assets/11514927/21860694/04ec4e5c-d7ef-11e6-9922-df53a514f2f0.png)

**Expected:** No error.  Or maybe we should dim Upgrade button until change is made?

**Comment by alena1108** [comment]
@tfiduccia even when there are no changes, the upgrade still goes through if the at least one launch config is passed to the command (and UI has check box for primary launch Config set automatically). So it might take time for the service to go from active to upgraded state, and finishUpgrade is available only for services in "upgraded" (for all the rest the error that you see is going to be thrown).

FinishUpgrade button should be presented only when the service is in "Upgraded" state. @tfiduccia could you check if the UI shows this option only for valid service's states?

**Comment by tfiduccia** [comment]
re-ran this test case and the error is no longer showing up and the upgraded state completes.  So I'm closing.
Version - master 2/21
Verified fixed
