### ISSUE TITLE
Feature Request: Timestamps available from the Audit Log view

### ISSUE THREAD

**Issue by crielly** [rancher/rancher#7382]
Rancher Versions:
Server: 1.2

As of 1.2 I cannot find a way to do this - the Audit Log view does not provide sufficient granularity in my opinion. By its vary nature an Audit Log needs timestamps - I need to know more than that this API call was made "3 hours ago", I need to know exactly when it happened. What was the time difference between this deactivate and this remove call?

An option to display the actual timestamp in at least UTC is essential - and in my opinion should be the default.

**Comment by westlywright** [comment]
This will be resolved by the 2.0 release. Hovering over the time ago will reveal the utc timestamp.

**Comment by tfiduccia** [comment]
Version - master 8/9
Verified fixed
