### ISSUE TITLE
Error Connecting to Websocket

### ISSUE THREAD

**Issue by ecliptik** [rancher/rancher#7389]
**Rancher Versions:**
Server: 1.2.2
healthcheck: v0.1.0
ipsec: v0.7.5
network-services: metadata:v0.6.8 network-manager:v0.2.19
scheduler: v0.4.0
kubernetes (if applicable):

**Docker Version:**
1.11.2 and 1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):**
AWS Amazon Linux 2016.09

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node, external DB in AWS RDS

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**

1. Create new AWS ALB Rancher server behind AWS ALB with HTTP 80 and HTTPs 443 going to the same Target Group (ARN removed from screenshot)

<img width="1167" alt="screen shot 2017-01-11 at 5 31 30 pm" src="https://cloud.githubusercontent.com/assets/1261742/21873719/6e7e67e8-d825-11e6-8f0f-f4e92190372d.png">

Target Group going to Rancher server on port 8080

<img width="1199" alt="screen shot 2017-01-11 at 5 33 42 pm" src="https://cloud.githubusercontent.com/assets/1261742/21873602/86fa47ca-d824-11e6-9a01-443cab1cdec2.png">

2. Create A record with ALIAS=ALB_Name in Route53

3. Setup Github OAuth and use callback URL of the Route53 record, in this case https://rancher.demandbase.com

4. Go to URL and the Authenticate Gitbub dialog comes up, but then redirects and it comes up again. After doing this twice you can access Rancher.

**Results:** 

Rancher is accessible from both http and https, however the UI acts strangely and gives odd URLs with arguments like:

`https://rancher.demandbase.com/env/1a2557/apps/stacks?error_description=The%20redirect_uri%20MUST%20match%20the%20registered%20callback%20URL%20for%20this%20application.&state=0.3028898913894047`

Errors occasionally appear in the UI with `Error Connecting to Websocket`

<img width="310" alt="screen shot 2017-01-11 at 4 46 51 pm" src="https://cloud.githubusercontent.com/assets/1261742/21873671/08162b80-d825-11e6-9259-d91619a6c411.png">

The UI overall is sluggish, not updating quickly, and occasionally the entire page refreshes itself. This happens with multiple accounts and is easily reproducible.

**Expected:**

No callback errors, no websocket errors, no UI sluggishness. This did not happen with Rancher 1.1.4 with behind a ELB with websocket support and only started when we upgraded to Rancher 1.2 and put it behind a ALB

**Comment by vincent99** [comment]
Nothing has changed in Rancher and there's nothing we can do about this.  You must be using a different certificate, missing an intermediate cert, don't have it installed on your Mac anymore, or similar.

As the message says, Safari does not allow `wss://` connections with a certificate it doesn't consider valid.  And without websockets you get no stats, logs, shell, or auto-updating of the UI.

**Comment by ecliptik** [comment]
@vincent99 thank you for responding, and the certificate should be valid from GoDaddy and is not self-signed. We use it on all of our *.demandbase.com domains with AWS ELBs and ALBs and it doesn't have issues elsewhere.

Stats, logs, shell, and auto-updating does still work about 97% of the time, it's intermittent when it doesn't work and that message shows up.

I'm wondering if it has to do with how the ALB is setup, with port 80 and 443 both going to the target group. Is there a recommended AWS ALB configuration for how to setup target groups for http and https?

Before when we were using AWS ELB with websockets and tcp-proxy, we had a nginx container running on the Rancher server that would just do a 301 redirect to https for any http requests. I removed it when we upgraded since it appears the ALB was suppose to handle these redirects so https is always used.

The other message about `The%20redirect_uri%20MUST%20match%20the%20registered%20callback%20URL%20for%20this%20application` almost makes me wonder if this is a http -> https redirect issue.

**Comment by vincent99** [comment]
There's no special config needed for ALB like there was for ELB..

GoDaddy certs do require an intermediate cert (and the right one, Starfield vs GD) to validate correctly.  Easy way to check is `curl -v https://domain`, you should get back 401 and a JSON error (since github auth is apparently on).

The redirect_uri message comes from GitHub auth and means that the URL configured in the github application doesn't match the domain your trying to login from.  When we send you to github from a domain not matching the configured client ID they redirect back to the URL that **is** configured for that ID and it adds that to the query string. (This is the redirect you mentioned that I didn't notice reading the first time)

So so I suspect your problem is related to that redirect from $expected_url -> $configured_in_github_that_happens_to_resolve_to_same_IP.  And the times it randomly works you're actually on non-SSL.  The safari issue is very deterministic, if the cert is not valid it throws an error trying to establish a `wss://`connection, even if you say to ignore the cert error at some point.

**Comment by trondhindenes** [comment]
We use a TCP listener in ELB instead of HTTP, using that config websockets works perfectly.

**Comment by HenryTheSir** [comment]
A german IT News Site published an article about 6000 revoked Certs because of an Bug:
https://www.heise.de/newsticker/meldung/Einige-SSL-TLS-Zertifikate-von-GoDaddy-wegen-Software-Bug-ungueltig-3594320.html

Are you affected maybe?

**Comment by ecliptik** [comment]
Tried turning off the HTTP listener on the ALB last night and it fixed the Github redirect issue, but some co-workers still mentioned they were getting websocket error messages like in the screenshot.

I did a curl against the domain and things look good, the one thing that jumps out at me is `server certificate status verification SKIPPED` in the output. For comparison this message also appears when doing a curl against https://www.rancher.com.

As mentioned before, this certificate is used on almost all of our domains and we haven't had any issues with it so I doubt it's revoked or invalid, otherwise we'd hear about it from other engineers or customers.

Here's the full output of the `curl -v` from my MacBook which is giving the expected `401`,

```
🐳  curl -v https://rancher.demandbase.com
* Rebuilt URL to: https://rancher.demandbase.com/
*   Trying 52.9.70.86...
* Connected to rancher.demandbase.com (52.9.70.86) port 443 (#0)
* found 1 certificates in /usr/local/MacGPG2/share/sks-keyservers.netCA.pem
* found 172 CA certificate(s) in system trust store
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
*        server certificate verification OK
*        server certificate status verification SKIPPED
*        common name: *.demandbase.com (matched)
*        server certificate expiration date OK
*        server certificate activation date OK
*        certificate public key: RSA
*        certificate version: #3
*        subject: OU=Domain Control Validated,CN=*.demandbase.com
*        start date: Tue, 20 Sep 2016 16:07:38 GMT
*        expire date: Mon, 19 Nov 2018 15:23:43 GMT
*        issuer: C=US,ST=Arizona,L=Scottsdale,O=GoDaddy.com\, Inc.,OU=http://certs.godaddy.com/repository/,CN=Go Daddy Secure Certificate Authority - G2
*        compression: NULL
* ALPN, server accepted to use http/1.1
> GET / HTTP/1.1
> Host: rancher.demandbase.com
> User-Agent: curl/7.49.1
> Accept: */*
> 
< HTTP/1.1 401 Unauthorized
< Date: Thu, 12 Jan 2017 17:12:29 GMT
< Content-Type: application/json; charset=utf-8
< Content-Length: 177
< Connection: keep-alive
< Expires: Thu, 01 Jan 1970 00:00:00 GMT
< Server: Jetty(9.2.11.v20150529)
< Set-Cookie: PL=rancher;Path=/
< Www-Authenticate: Basic realm="Enter API access key and secret key as username and password"
< X-Api-Schemas: https://rancher.demandbase.com/v1/schemas
< 
* Connection #0 to host rancher.demandbase.com left intact
{"id":"535fe306-b8bd-4d7b-ba21-a694f9c7e7ce","type":"error","links":{},"actions":{},"status":401,"code":"Unauthorized","message":"Unauthorized","detail":null,"baseType":"error"}
```

**Comment by timothystewart6** [comment]
Same here.  I am using a wildcard cert from namecheap for my domain on a Sophos XG firewall. It works on all of my subdomains except rancher websockets.

**Comment by ecliptik** [comment]
After upgrading to Rancher 1.5.2 and putting the master behind a AWS ELB, and not an ALB, this appears to have resolved.

**Comment by ecliptik** [comment]
Spoke too soon, this appears to still be happening even behind an ELB.

**Comment by iBobik** [comment]
This error appears even if connection was corrupted by bad cellular conectivity, by Mac sleep or by proxy without support for websockets.

**Comment by JigSawFr** [comment]
It's strange, I'm facing exactly the same problem ...
I'm using a Bare-metal server with RancherOS and Rancher Server Management.
Rancher GUI is accessible by a Nginx proxy with configuration specified in Rancher docs.
And is under SSL (provided by Let's Encrypt).
Gui is working 97% of the time, and sometimes websocket errors appears.
I'm accessing GUI with a Mac (Sierra) and Safari.

**Comment by iBobik** [comment]
It seems like the error appears and hot close always when network is offline. On macOS it is common state after wake up or when switching WiFi.

If GUI will close error when network is online again, most of this false alarms will me solved I think.

Jan Pobořil
http://honza.poboril.cz/

23. 7. 2017 v 9:59, JigSaw <notifications@github.com>:

**Comment by ecliptik** [comment]
Still seeing this message in the Rancher 2.0 Preview on Safari 11.

The instance is behind a AWS ALB forwarding port 443 -> 8080.

I'll keep an eye on it and see if it happens whenever the laptop/network goes to sleep or changes wifi, etc to see if it's just a network connection like @iBobik mentioned.

<img width="1429" alt="screen shot 2017-09-26 at 11 33 35 am" src="https://user-images.githubusercontent.com/1261742/30877441-991ecea8-a2ae-11e7-9a4c-ae406ad635a4.png">

**Comment by vincent99** [comment]
@loganhz Can you change:

- Move the safari message to a translation key so it can be localized.
- Only show the safari error case if `window.navigator.onLine === true`.
- Automatically show & hide a (different) growl when the subscribe socket is disconnected, or doesn't successfully connect after the page loads. (#7389)
- If the subscribe socket is disconnected for too long (add a constant for it, say 30 sec), reload the page.  If `window.navigator.onLine === false`, wait for it to become true before reloading (`window.ononline`)

**Comment by tfiduccia** [comment]
Sending to Vincent.  Looked at it and it seems like it might be incomplete, he's going to check.

**Comment by deniseschannon** [comment]
With TP2, it seems that most of these websocket issues have been addressed. If further issues arise, let's re-open a new issue.

**Comment by joehoeller** [comment]
Im having same issue in rancher 2.4

**Comment by joehoeller** [comment]
@deniseschannon: nevermind, after a few refreshes of browser it renewed the certs on its own i think, problem went away.
