### ISSUE TITLE
Service Links - When service name are edited, service links does not honor the changed service name.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#739]
Version - V0.19.1

Create service - test1 with 2 instances.
Create service - test2 with 3 instances.
Link test2 to test1.

From instances of service test1 , tried to access test2 , using hostname as "test2". This redirects request to one of the instances in test2.

Edit the service name to "test123".

From instances of service test1 , tried to access test2 , using hostname as "test123".
DNS  resolution for this fails:

root@57c8dfddb3b1:/# wget http://test23:80/name.html
--2015-05-07 18:19:17--  http://test23/name.html
Resolving test23 (test23)... failed: Name or service not known.
wget: unable to resolve host address `test23'
root@57c8dfddb3b1:/# wget http://test2:80/name.html

The older service name - test2 continues to work.

Expected Behavior:
DNS resolution for the older service name should stop working and DNS resolution for the current service name should work.

**Comment by alena1108** [comment]
Should be fixed in master; @sangeethah could you pls retest?

**Comment by sangeethah** [comment]
Tested with server version - V0.24.0-rc1
I am still able to reproduce this issue.

**Comment by alena1108** [comment]
@sangeethah its because the UI currently sets the link name = service.name behind the scenes. So changing the target service name won't change anything on the dns side. Could you please test this use case using APIs? There is some refactoring planned to be done on the UI side after PR https://github.com/rancherio/cattle/pull/635 gets in. After that, you can test the use case using API as well.

**Comment by vincent99** [comment]
@sangeethah I don't think this applies anymore...

**Comment by sangeethah** [comment]
Tested with server version -V0.29.0-rc1

Create service - test1 with 2 instances.
Create service - test2 with 3 instances.
Link test2 to test1 (without providing link name).

From containers on service test1 , DNS resolution for test2 works as expected.

Edit service name of test2 to "test2upd"

DNS resolution for the older service name  stops working and DNS resolution for the current service name - test2upd works.
