### ISSUE TITLE
Implicit (or side-kick) Load Balancers

### ISSUE THREAD

**Issue by darrenscerri** [rancher/rancher#7391]
We often find the need to create a load balancer for nearly every service in a stack, to enable each service to scale up while allowing consumers to use the scaled service. Scaling up a service without a dedicated load balancer, load balancing would only rely on the consumer with the assumption that the service is able to use DNS round-robin load balancing.

Would it be possible to somehow add a feature to expose an implicit load-balancer automatically for a scaleable service, for which consumers can directly link to the load balancer rather than the scaled-up service? Is this somehow currently possible with something like side-kicks?

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
