### ISSUE TITLE
Can't access primary host port mapping from a sidekick container in V1.3

### ISSUE THREAD

**Issue by lapep** [rancher/rancher#7392]
**Rancher Versions:**
Server: 1.3

**Docker Version:**
1.12.1

**OS and where are the hosts located? (cloud, bare metal, etc):**
Centos 7, Datacentre VMs.

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher, external mysql DB.

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Docker compose:

```version: '2'
services:
  test:
    image: ubuntu:14.04.2
    stdin_open: true
    tty: true
    volumes_from:
    - test-data
    ports:
    - 8060:8060/tcp
    labels:
      io.rancher.sidekicks: test-data
  test-data:
    image: ubuntu:14.04.2
    stdin_open: true
    tty: true
    ports:
    - 8050:8050/tcp
    command:
    - cat
```

**Results:** 
If you shell onto the primary or sidekick telnetting to the mapped host port of the other container makes it hang.

**Expected:**
We expect to hit a mapped host port on any host, especially on the same host. This worked in v1.1 we have recently upgraded. We use this feature as we have a proxy sidekick service which is tightly coupled with a main web service. The proxy should only talk to the local main instance. We do this by using the rancher metadata service to find the local IP of the sidekick then we hit the local IP with the mapped port of the main service.

**Comment by deniseschannon** [comment]
Is this a fresh install of 1.3?

Can you make sure all your infrastructure stacks are up to date? There were some Hairpin NAT issues in older network-services/ipsec that have been addressed.

**Comment by lapep** [comment]
Yes, this was a completely fresh install.

Could you explain what do you mean by  infrastructure stacks, do we need to update them separately?

**Comment by kaos** [comment]
What happened to this issue?

We're in the middle of upgrading from 1.1.4, and run into something that feels very much like a hairpin issue.

Using the example compose services from @lapep, I've run some tests on two rancher systems. One v1.1.4, and the other 1.4.1. (did also try this locally on latest, 1.5, with similar results as those for 1.4.1)

I used curl to test connectivity from each container to the exposed ports on the host. N.b. as there is not in fact any service listening on the ports in question, the expected result is "connection refused", and was verified from a third node (i.e. curl to each node on 8050 and 8060 all gave connection refused from the third node).

| Server | Service | Running on node | Connect to | Outcome |
| :-- | :-- | :-- | :-- | :-- |
| 1.1.4 | test | A | A:8050 | connection reset by peer |
| 1.1.4 | test | A | A:8060 | connection reset by peer |
| 1.1.4 | test | A | B:8050 | connection refused |
| 1.1.4 | test | A | B:8060 | connection refused |
| 1.1.4 | test-data | A | A:8050 | connection reset by peer |
| 1.1.4 | test-data | A | A:8060 | connection reset by peer |
| 1.1.4 | test-data | A | B:8050 | connection refused |
| 1.1.4 | test-data | A | B:8060 | connection refused |
| >> 1.4.1 | test | B | B:8050 | **hangs until aborted** << |
| 1.4.1 | test | B | B:8060 | connection refused |
| 1.4.1 | test | B | A:8050 | connection refused |
| 1.4.1 | test | B | A:8060 | connection refused |
| 1.4.1 | test-data | B | B:8050 | connection refused |
| >> 1.4.1 | test-data | B | B:8060 | **hangs until aborted** << |
| 1.4.1 | test-data | B | A:8050 | connection refused |
| 1.4.1 | test-data | B | A:8060 | connection refused |

The highlighted outcomes of connections that hang are the suspect ones.

**Comment by kaos** [comment]
ping @deniseschannon 

we're still having hairpin issues on rancher 1.4, which I believe is what is going on here so any news would be appreciated.

If you think this is something else, we could create a new issue, detailing our hairpin issues (which would pretty much be a copy paste of the research done in my previous comment.)

**Comment by leodotcloud** [comment]
@kaos For the sidekick container you have used `command: -cat`. This overrides the command of the the nginx container, hence there is no nginx process running and listening on port 80 inside the container. It's for this reason you cannot access the exposed port 8050.

Here is the compose file used for testing:
```
version: '2'
services:
  bravo:
    image: nginx
    stdin_open: true
    tty: true
    ports:
    - 9020:80/tcp
    labels:
      io.rancher.container.pull_image: always
  alpha:
    image: nginx
    stdin_open: true
    tty: true
    volumes_from:
    - bravo
    ports:
    - 9010:80/tcp
    labels:
      io.rancher.container.pull_image: always
      io.rancher.sidekicks: bravo
```

From both containers, I can successfully access the exposed ports.
(`apt update && apt install curl && curl http://${HOST_IP}:9010 && curl http://${HOST_IP}:9020`)

**Comment by kaos** [comment]
@leodotcloud thanks for your input. You missed this part in my comment, however:

> N.b. as there is not in fact any service listening on the ports in question, the expected result is "connection refused"

What was not expected was the hanging connections. However, that it does work for you, is some kind of indication that it could be related to our hosts.. or something else outside of rancher. However, it is somehow related to rancher any way, as it *does* work as expected in rancher 1.1.4. 

We have redhat 7.2 physical hosts. What were you testing on?

I re-ran the test with your compose file, with the same results as before. That is, I get the nginx page when queried from another host, or when the qeuried host port maps to the same container that I run the curl from. But when I run curl from container alpha trying to access port 9020 in bravo, I get no response (curl just waits for the connection to go through, but it doesn't.)

```
[root@0591fc2cc5fe /]# curl --max-time 10 --head ${HOST_IP}:9010
HTTP/1.1 200 OK
Server: nginx/1.9.10
Date: Thu, 30 Mar 2017 11:00:49 GMT
Content-Type: text/html
Content-Length: 612
Last-Modified: Tue, 26 Jan 2016 15:51:10 GMT
Connection: keep-alive
ETag: "56a795ee-264"
Accept-Ranges: bytes

[root@0591fc2cc5fe /]# curl --max-time 10 --head ${HOST_IP}:9020
curl: (28) Connection timed out after 10001 milliseconds
[root@0591fc2cc5fe /]#
```

**Comment by leodotcloud** [comment]
@kaos 

> You missed this part in my comment
Thanks for pointing out, I did miss reading your comment.

> We have redhat 7.2 physical hosts. What were you testing on?
Ubuntu 16.04

Some of our customers running RHEL/CentOS ran into few problems in the past. @aemneina did some testing and figured:
```
bad kernel: `3.10.0-327.10.1.el7.x86_64`
good kernel: `3.10.0-514.2.2.el7.x86_64`
```

If it's not the latest kernel, can you please upgrade and give it a shot?

Also if you check the iptables, you should be able to see rules related to these ports. That would confirm the programming went fine.

```
iptables-save | grep 9010; iptables-save | grep 9020
```

**Comment by kaos** [comment]
Thanks for the kernel version info. I do see we have a host on the older bad kernel version, but as it turned out, I wasn't running my tests on that one..

I still have the same issues, on a machine running `3.10.0-514.10.2.el7.x86_64` recently rebooted too, just in case ;)

The iptables seems to be in order, too, I suppose:
```
[root@tsy04 ~]# iptables-save  | grep '90[1,2]0'
-A CATTLE_OUTPUT -p tcp -m tcp --dport 9020 -m addrtype --dst-type LOCAL -j DNAT --to-destination 10.42.254.165:80
-A CATTLE_OUTPUT -p tcp -m tcp --dport 9010 -m addrtype --dst-type LOCAL -j DNAT --to-destination 10.42.234.167:80
-A CATTLE_PREROUTING ! -i docker0 -p tcp -m tcp --dport 9020 -j MARK --set-xmark 0x1068/0xffffffff
-A CATTLE_PREROUTING ! -i docker0 -p tcp -m tcp --dport 9020 -j DNAT --to-destination 10.42.254.165:80
-A CATTLE_PREROUTING -p tcp -m tcp --dport 9020 -m addrtype --dst-type LOCAL -j DNAT --to-destination 10.42.254.165:80
-A CATTLE_PREROUTING ! -i docker0 -p tcp -m tcp --dport 9010 -j MARK --set-xmark 0x1068/0xffffffff
-A CATTLE_PREROUTING ! -i docker0 -p tcp -m tcp --dport 9010 -j DNAT --to-destination 10.42.234.167:80
-A CATTLE_PREROUTING -p tcp -m tcp --dport 9010 -m addrtype --dst-type LOCAL -j DNAT --to-destination 10.42.234.167:80
```

Perhaps some other rule in the iptables that trips this setup up.. I'll dig around that area for a bit.

**Comment by leodotcloud** [comment]
@lapep @kaos A lot of networking fixes have been done since this issue has been created. Can you please check with the latest releases of the rancher and create new issues if you are having any problems?

**Comment by kaos** [comment]
I'll take a look after the holidays.. end of august/september..

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
