### ISSUE TITLE
Agent error on Windows Server - Error getting local storage usage: The system cannot find the path specified

### ISSUE THREAD

**Issue by msandbu** [rancher/rancher#7393]
**Rancher Versions:**
Server: 1.3

**Docker Version:** 1.12.2-cs2-ws-beta

**OS and where are the hosts located? (cloud, bare metal, etc):**
Windows Server 2016 in Azure Cloud

The Rancher agent is generating event logs on the Guest OS every 15 seconds and getting generating this error message

The following information was included with the event: 

Error getting local storage usage: The system cannot find the path specified.

The specified image file did not contain a resource section

**Comment by msandbu** [comment]
Also the Rancher agent stops without notice and will not restart and it leaves the hosts in a disconnected state, I need to manually restart the Rancher agents.

**Comment by Ashthos** [comment]
I also have this issue. Docker containers are kept running throughout and appear correctly in the rancher UI when the agent is restarted manually.

Agents running on Physical Tin Windows 2016 Server.

Just before they die, I get the following in the event log:

```Received event: Name: config.update, Event Id: de9cf26c-78cd-429e-9b57-540aa0ea3989, Resource Id: 1a27```

then

```Reply: de9cf26c-78cd-429e-9b57-540aa0ea3989, config.update, 1a27:agent, transitioning: no: config update failed```

Rancher: 1.4.2
Docker: 1.14.0-dev

**Comment by rliberoff** [comment]
I have the very same issue.

Any luck with it?

Did you find a solution or a workaround?

Thank you.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
