### ISSUE TITLE
Rancher V1.3 etcd services not starting as expected...

### ISSUE THREAD

**Issue by ravikanthb** [rancher/rancher#7395]
**Rancher Versions:**
Server:v1.3
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):k8s

**Docker Version:**
1.10.3
**OS and where are the hosts located? (cloud, bare metal, etc):openstack cloud

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)single node

**Environment Type: Kubernetes

**Steps to Reproduce:**
Install rancher v1.3 with 3 rancher nodes with kubernetes
**Results:** 
etcd-1 runs on first node and another two nodes it is in intializing phase with error "Get http://10.42.191.187:2379/health: dial tcp 10.42.191.187:2379: getsockopt: no route to host"
![image](https://cloud.githubusercontent.com/assets/22937829/21896776/81261c68-d90d-11e6-9ff8-b039642804da.png)

*Expected:**
All three  etcd-1,2,3 should be running....

**Comment by ravikanthb** [comment]
As all the three etcd containers are in different subnets, they are not able to ping each other from within containers and i am not able to add routes.....

bash-4.3# route add -net 10.42.191.187 netmask 255.255.255.255  gw 10.42.0.1 eth0
route: ioctl 0x890b failed: Operation not permitted

**Comment by Dmitry1987** [comment]
@ravikanthb  seems like you need to fix connection between hosts, check the routing table (are you on AWS?)

**Comment by LLParse** [comment]
Closing due to age. Please try newer versions and ensure udp ports 500 and 4500 are open between hosts. If you still encounter problems with the overlay network, please open a new issue.
