### ISSUE TITLE
Catalog entry upgrades are not consistent

### ISSUE THREAD

**Issue by willseward** [rancher/rancher#7397]
**Rancher Versions:**
Server: 1.3.0

**Docker Version:**

v1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):**

RHEL 7.2

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

External DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**

1. Create a catalog entry with version: '0.1', uuid: '0', and template number: 0.
1. Deploy
1. Create a revision entry with version: '0.1', uuid: '1', and template number: 1.

**Results:** 

Deploying a new stack will deploy uuid 1, but the previously deployed stack will not upgrade to uuid 1.

**Expected:**

The option to upgrade to the new revised version is given. Frequently we QA versions and make revisions.

**Comment by tfiduccia** [comment]
@willseward - Version field must increase, the UUID isn't used anymore.
