### ISSUE TITLE
Rancher 1.3: Unable to add host using Azure driver 

### ISSUE THREAD

**Issue by cnadeau** [rancher/rancher#7398]
**Rancher Versions:**
Server: 1.3
healthcheck: 
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker Version:**
1.12

**OS and where are the hosts located? (cloud, bare metal, etc):**
Linux VM on Azure

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single docker container running rancher 1.3 linked to a mysql db container

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**
- New Environment
- Add Host using Azure Driver
- Default parameters + size Extra Small + subscription/client id/client secret
- Create

**Results:** 
An error seems to occur in docker-machine but it's not stopping the creation which fails and eventually times out:

![image](https://cloud.githubusercontent.com/assets/453012/21898836/2248dc40-d8bc-11e6-9574-d0bccac5644c.png)

Error displayed is from docker-machine:
https://github.com/docker/machine/blob/master/libmachine/shell/shell.go

**Expected:**
error message and rollback VM creation

**Comment by cnadeau** [comment]
Looking at the logs, this is a more reasonable answer to the problem:

Error creating machine: Error in driver during machine creation: compute.VirtualMachinesClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code=\"InvalidParameter\" Message=\"__The requested VM size ExtraSmall is not available in the current region. The sizes available in the current region are__: Standard_A0,Standard_A1,Standard_A2,Standard_A3,Standard_A5,Standard_A4,Standard_A6,Standard_A7,Basic_A0,Basic_A1,Basic_A2,Basic_A3,Basic_A4,Standard_D1_v2,Standard_D2_v2,Standard_D3_v2,Standard_D4_v2,Standard_D5_v2,Standard_D11_v2,Standard_D12_v2,Standard_D13_v2,Standard_D14_v2,Standard_D15_v2,Standard_F1,Standard_F2,Standard_F4,Standard_F8,Standard_F16,Standard_A1_v2,Standard_A2m_v2,Standard_A2_v2,Standard_A4m_v2,Standard_A4_v2,Standard_A8m_v2,Standard_A8_v2,Standard_DS1_v2,Standard_DS2_v2,Standard_DS3_v2,Standard_DS4_v2,Standard_DS5_v2,Standard_DS11_v2,Standard_DS12_v2,Standard_DS13_v2,Standard_DS14_v2,Standard_DS15_v2,Standard_F1s,Standard_F2s,Standard_F4s,Standard_F8s,Standard_F16s,Standard_H8,Standard_H16,Standard_H8m,Standard_H16m,Standard_H16r,Standard_H16mr,Standard_D1,Standard_D2,Standard_D3,Standard_D4,Standard_D11,Standard_D12,Standard_D13,Standard_D14,Standard_DS1,Standard_DS2,Standard_DS3,Standard_DS4,Standard_DS11,Standard_DS12,Standard_DS13,Standard_DS14,Standard_NC6,Standard_NC12,Standard_NC24,Standard_NC24r,Standard_A8,Standard_A9,Standard_A10,Standard_A11. Find out more on the available VM sizes in each region at https://aka.ms/azure-regions.\"" resourceId=1ph15

**Comment by tfiduccia** [comment]
@cnadeau - Use Standard_A0 for ExtraSmall

@vincent99 - The ExtraSmall through ExtraLarge are not really supported in the MS's new VM section.  Supported MS sizes.  https://docs.microsoft.com/en-us/azure/virtual-machines/virtual-machines-windows-sizes

They replaced those with the Standard_A0 - A4.
Standard_A0 is ExtraSmall
Standard_A1 is Small (Need to add this one as it's not in the list)
Standard_A2 is Medium
Standard_A3 is Large
Standard_A4 is ExtraLarge

**Comment by tfiduccia** [comment]
Version - master 1/17
Verified invalid options are no longer available through the UI.
