### ISSUE TITLE
Rancher Penetrates DNS Servers

### ISSUE THREAD

**Issue by HenryTheSir** [rancher/rancher#7403]
**Rancher Versions:**
Server: 1.3
healthcheck: 0.2
ipsec: v0.8.1
network-services: v0.4
scheduler: v.0.5

All Services UpToDate regarding GUI.

**Docker Version:**
1.12.6
**OS and where are the hosts located? (cloud, bare metal, etc):**
2x Ubuntu LTS 16.04 on VMWare for Agents and 1x Ubuntu LTS 16.04 for RancherServer
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
SingleNode Rancher external DB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
Restart Ubuntu Host or Docker Service so that all Containers restart
**Results:** 
DNS Server which resolves NOT .rancher.internal (e.g. Windows DNS Server for 'normal' DNS resolving) gets more than 50 Requests per Sec
**Expected:**
Send just one DNS Request per DNS Name and use the given TTL from the DNS Server.

**Comment by vincent99** [comment]
The Rancher DNS server  does have a small cache in it but exists mainly to provide service discovery answers, not to be a general per-host public DNS cache for containers.

Exactly the same thing would happen if Rancher was not involved  at alland you just had vanilla docker containers running and restarted the host/daemon.

**Comment by HenryTheSir** [comment]
I do not think that this would happen with vanilla docker containers. 
In the Environment with just 1 Host the rate of DNS requests is far lower than on the Environment with 2 nodes. 

As a workarround I added the IPs to the hosts file this seems to lower the requests.
