### ISSUE TITLE
[cli] rancher stop <stack> creates an empty stack called Default

### ISSUE THREAD

**Issue by jdel** [rancher/rancher#7405]
**Rancher Versions:**
Server: enterprise 1.2.2
healthcheck: 0.2.0
ipsec: 0.8.1
network-services: 0.7.0/0.4.0
scheduler: 0.5.0

**Docker Version:**
Docker version 1.12.1, build 23cf638

**OS and where are the hosts located? (cloud, bare metal, etc):**
ROS 0.7.1 on VirtualBox

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
3 rancher-ha over an external 3 node galera cluster

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
```
[15:36:45] jdel ~ > > rancher stacks
[15:37:13] jdel ~ > > rancher stop <any stack>
[15:37:22] jdel ~ > > rancher stacks
```
**Results:** 
```
[15:36:45] jdel ~ > > rancher stacks
ID        NAME                     STATE     CATALOG                                        SERVICES   SYSTEM    DETAIL
1st18     rancher-bench-security   healthy   catalog://community:rancher-bench-security:0   2          false
1st21     externalLb               healthy                                                  1          false
[15:37:13] jdel ~ > > rancher stop 1st18
1st18
[15:37:22] jdel ~ > > rancher stacks
ID        NAME                     STATE       CATALOG                                        SERVICES   SYSTEM    DETAIL
1st18     rancher-bench-security   unhealthy   catalog://community:rancher-bench-security:0   2          false
1st21     externalLb               healthy                                                    1          false
1st42     Default                  healthy                                                    0          false
```
**Expected:**
```
[15:36:45] jdel ~ > > rancher stacks
ID        NAME                     STATE     CATALOG                                        SERVICES   SYSTEM    DETAIL
1st18     rancher-bench-security   healthy   catalog://community:rancher-bench-security:0   2          false
1st21     externalLb               healthy                                                  1          false
[15:37:13] jdel ~ > > rancher stop 1st18
1st18
[15:37:22] jdel ~ > > rancher stacks
ID        NAME                     STATE       CATALOG                                        SERVICES   SYSTEM    DETAIL
1st18     rancher-bench-security   unhealthy   catalog://community:rancher-bench-security:0   2          false
1st21     externalLb               healthy                                                    1          false
```

**Comment by slimatic** [comment]
I am seeing this behaviour as well. any thoughts?

**Comment by kelchm** [comment]
I'm also seeing a this behavior, but with the `rancher wait` CLI command.

**Comment by iljaweis** [comment]
The syntactically wrong `rancher rm some/thing` will do something similar, give an error message but create an empty stack `some`.

**Comment by Gmentsik** [comment]
Exact same thing here...

**Comment by se42** [comment]
I'm also seeing the creation of an empty Default stack with ```rancher inspect <id>``` where ```id``` is a container id.  Passing the ```--type container``` flag prevents the behavior.  The Default stack is not created when I run ```rancher inspect <stackName>/<serviceName>```.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
