### ISSUE TITLE
Health check stuck on initializing for AWS EC2 hosts

### ISSUE THREAD

**Issue by richbos** [rancher/rancher#7406]
**Rancher Versions:**
Server: v1.2.2 & v1.3.0
healthcheck: rancher/healthcheck:v0.2.0
ipsec: rancher/net:holder
network-services: rancher/network-manager:v0.4.0
scheduler: rancher/scheduler:v0.5.0
kubernetes (if applicable):

**Docker Version:**
1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
Rancher server OS : Amazon Linux in AWS (eu-west-1 or eu-central)
Hosts OS : Ubuntu, CentOS, RancherOS - AWS regions eu-west-1, eu-central

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node Rancher launched from an EC2 scaling group/launch config behind an AWS ELB on 8080 with ELB health check/listeners on 8080.
External DB in AWS RDS.
Server security group grants 8080 access to the ELB security group.
Hosts launched using Rancher UI & default rancher-machine security group.

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Launch Rancher server from a launch config/autoscaling group behind an AWS ELB.
Deploy Ubuntu or RancherOS hosts from within Rancher to EC2 in either eu-west-1 or eu-central using config as detailed.

**Results:** 
Health check stuck on initializing

**Expected:**
Health check to activate and go live/green

![screen shot 2017-01-13 at 14 48 04](https://cloud.githubusercontent.com/assets/1983458/21934035/ccc88402-d99f-11e6-975e-bc42251a0c9b.png)

![screen shot 2017-01-13 at 14 50 58](https://cloud.githubusercontent.com/assets/1983458/21934049/da895d82-d99f-11e6-8b9e-652f8db62842.png)

**Comment by aemneina** [comment]
What ports do you have exposed on the agent hosts security group?

**Comment by aemneina** [comment]
You also need to use he AWS ALB for rancher server 1.2.+

**Comment by richbos** [comment]
To update, yes, switching to ALB (from ELB) appears to have resolved the issue. RancherOS hosts in eu-west-1 from Rancher server in eu-west-2 are showing as healthy.

It took some time to re-work out our Terraform configuration until we realised that the EC2 autoscaling group needed to reference the ALB target group, and we are currently using EC2 health checks as there was/is no option for ALB (only EC2 or ELB).

![screen shot 2017-01-15 at 09 22 29](https://cloud.githubusercontent.com/assets/1983458/21961592/a8889778-db05-11e6-82e2-a6f9eb47e550.png)
