### ISSUE TITLE
API filter not working on instances type

### ISSUE THREAD

**Issue by bla-ckbox** [rancher/rancher#7408]
**Rancher Versions:**
Server: 1.2.2 
healthcheck: v0.1.0
ipsec: v0.7.5
network-services: v0.6.8
scheduler: v0.4.0
kubernetes (if applicable):

**Docker Version:** 1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):** self hosted

**Setup Details:** single node rancher

**Environment Type:** Cattle

**Steps to Reproduce:** Make an api request on instances type with an filter

**Results:** filter is not applicated

`# curl -s -u "${ACCESS_KEY}:${ACCESS_SECRET}"   -X Get -H 'Accept: application/json' -H 'Content-Type: application/json'   "${RANCHER_API}/projects/1a5/hosts/1h54/instances?name_ne=int1_gearmand_1" 
{
  "type": "collection",
  "resourceType": "instance",
  "links": {
    "self": "http://ranche:8080/v2-beta/projects/1a5/hosts/1h54/instances"
  },
  "data": [
    {
      "id": "1i151433",
      "type": "container",
      ...
      "name": "int1_gearmand_1",
      "state": "running",
    }
  ],
  .....
  "filters": {
    "name": [
      {
        "modifier": "ne",
        "value": "int1_gearmand_1"
      }
    ],
  },
}
`

**Comment by vincent99** [comment]
#5321
