### ISSUE TITLE
[Question] Launch multiple stacks at once

### ISSUE THREAD

**Issue by JaviSabalete** [rancher/rancher#7410]
**Rancher Versions:**
1.1.4

**Docker Version:**
1.11

**OS and where are the hosts located? (cloud, bare metal, etc):**
bare metal

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Question**
I have 2 stacks, one with databases and another one with php projects. It's possible launch at once?

Thanks!

**Comment by aemneina** [comment]
I think templates solve this. I dont think theyre intended for user stacks at this point.
