### ISSUE TITLE
[Question] It's possible disable services with catalog template?

### ISSUE THREAD

**Issue by JaviSabalete** [rancher/rancher#7411]
**Rancher Versions:**
1.1.4

**Docker Version:**
1.11

**OS and where are the hosts located? (cloud, bare metal, etc):**
bare metal

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Question**
I have a big cattle template, with 9 services with 27 containers (9x3). It's possible disable someone with checkbox (for example) from template? Maybe someuser no need all services, now I deleted some services after stack has been created

**Comment by joshwget** [comment]
This is a use case of #3239. Not precisely a duplicate, but solving that issue would likely provide what you're looking for.

**Comment by aemneina** [comment]
seems to be resolved in 1.5.0. please create a new issue if you see problems using the latest.
