### ISSUE TITLE
ERROR: https://${SERVER_IP}:8080/v1 is not accessible - when adding any custom host

### ISSUE THREAD

**Issue by danielbjornadal** [rancher/rancher#7416]
**Rancher Versions:**
Server: 1.3.1

**Docker Version:**
Docker version 1.12.6, build 78d1802

**OS and where are the hosts located? (cloud, bare metal, etc):**
Debian 8.6 (3.16.0-4-amd64) running on VMplayer

If i do a clean install of Debian 8 and docker 1.12.6, and run the commands as shown, the agent on the second server cannot connect to the server on the first host, even tho i can connect using curl to and from any host and container.

**Host 1**
```
root@host1:~# ifconfig
docker0   Link encap:Ethernet  HWaddr 02:42:40:d9:39:e1  
          inet addr:172.17.0.1  Bcast:0.0.0.0  Mask:255.255.0.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:41516 errors:0 dropped:0 overruns:0 frame:0
          TX packets:38853 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:16399887 (15.6 MiB)  TX bytes:13008285 (12.4 MiB)

eth0      Link encap:Ethernet  HWaddr 00:0c:29:04:e8:2b  
          inet addr:192.168.96.138  Bcast:192.168.96.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:388072 errors:0 dropped:0 overruns:0 frame:0
          TX packets:71876 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:511302795 (487.6 MiB)  TX bytes:27192589 (25.9 MiB)
```

`docker run -d --restart=unless-stopped -p 8080:8080 rancher/server:stable`

```
root@host1:~# docker ps
CONTAINER ID        IMAGE                   COMMAND                  CREATED             STATUS              PORTS                              NAMES
2948d00503db        rancher/server:stable   "/usr/bin/entry /usr/"   13 minutes ago      Up 13 minutes       3306/tcp, 0.0.0.0:8080->8080/tcp   sharp_ride

root@host1:~# netstat -luntp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      446/sshd        
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      26292/docker-proxy
udp        0      0 0.0.0.0:20161           0.0.0.0:*                           433/dhclient    
udp        0      0 0.0.0.0:68              0.0.0.0:*                           433/dhclient  
```
```
root@host1:~# curl -k -i https://172.17.0.2:8080/v1
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Date: Sat, 14 Jan 2017 14:17:37 GMT
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Server: Jetty(9.2.11.v20150529)
Set-Cookie: PL=rancher;Path=/
Vary: Accept-Encoding, User-Agent
X-Api-Account-Id: 1a1
X-Api-Client-Ip: 172.17.0.1
X-Api-Schemas: https://172.17.0.2:8080/v1/schemas
X-Rancher-Version: v1.3.1
Transfer-Encoding: chunked

root@host1:~# curl -k -i https://192.168.96.138:8080/v1       
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Date: Sat, 14 Jan 2017 14:18:59 GMT
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Server: Jetty(9.2.11.v20150529)
Set-Cookie: PL=rancher;Path=/
Vary: Accept-Encoding, User-Agent
X-Api-Account-Id: 1a1
X-Api-Client-Ip: 192.168.96.138
X-Api-Schemas: https://192.168.96.138:8080/v1/schemas
X-Rancher-Version: v1.3.1
Transfer-Encoding: chunked
```

Retrieving code from GUI.
**Host 2**

`root@host2:~# docker run -d --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.1.3 https://192.168.96.138:8080/v1/scripts/A48E39A209002D5165BE:1484402400000:3BcRvb2XUQLFhgObpdWAxqBKIc
`

```
root@host2:~# docker ps
CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS              PORTS               NAMES
74a61e30f9e7        rancher/agent:v1.1.3   "/run.sh https://192."   2 seconds ago       Up 1 seconds                            stupefied_mayer
```

```
root@debian:~# docker logs 74a61e30f9e7

INFO: Running Agent Registration Process, CATTLE_URL=https://192.168.96.138:8080/v1
INFO: Attempting to connect to: https://192.168.96.138:8080/v1
ERROR: https://192.168.96.138:8080/v1 is not accessible
ERROR: https://192.168.96.138:8080/v1 is not accessible
ERROR: https://192.168.96.138:8080/v1 is not accessible
ERROR: https://192.168.96.138:8080/v1 is not accessible
ERROR: https://192.168.96.138:8080/v1 is not accessible
ERROR: https://192.168.96.138:8080/v1 is not accessible
```

```
root@host2:~# curl -k -i https://192.168.96.138:8080/v1 
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Date: Sat, 14 Jan 2017 14:22:19 GMT
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Server: Jetty(9.2.11.v20150529)
Set-Cookie: PL=rancher;Path=/
Vary: Accept-Encoding, User-Agent
X-Api-Account-Id: 1a1
X-Api-Client-Ip: 192.168.96.139
X-Api-Schemas: https://192.168.96.138:8080/v1/schemas
X-Rancher-Version: v1.3.1
Transfer-Encoding: chunked
```

```
root@host2:~# docker exec -it 74a61e30f9e7 bash
root@74a61e30f9e7:/# curl -k -i https://192.168.96.138:8080/v1                                                                           
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Date: Sat, 14 Jan 2017 14:26:01 GMT
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Server: Jetty(9.2.11.v20150529)
Set-Cookie: PL=rancher;Path=/
Vary: Accept-Encoding, User-Agent
X-Api-Account-Id: 1a1
X-Api-Client-Ip: 192.168.96.139
X-Api-Schemas: https://192.168.96.138:8080/v1/schemas
X-Rancher-Version: v1.3.1
Transfer-Encoding: chunked
```

**Comment by yeruisen** [comment]
I've had the same problem that when you add  custom host in the same host of rancher server. but in the other host ,it `s work well.

**Comment by mcanevet** [comment]
I also have this issue when trying to run an agent on the rancher server host but on RHEL only, it works fine on Ubuntu LTS. @yeruisen did you find a workaround?

**Comment by lezi1022** [comment]
+1

**Comment by danielbjornadal** [comment]
Any update on this issue?
Think it is a problem whit the SSL. **Changing to regular http when adding the agent does the trick.**

**Comment by aemneina** [comment]
@danielbjornadal if you're using self signed certs, you need to add the certificate on the agent host as well. Take a look at the instructions here and let us know if it helps: https://docs.rancher.com/rancher/v1.5/en/installing-rancher/installing-server/basic-ssl-config/#adding-hosts

**Comment by danielbjornadal** [comment]
@aemneina Thanks for the reply.
Just to be clear, all certificates generated by rancher server and agent are self signed until changed?
Should this not work regardless?

**Comment by aemneina** [comment]
The rancher server doesnt terminate SSL in modern releases... So if you're not using a LB in front of rancher server that's terminating SSL, you're not using SSL in the way rancher expects. Just a quick test, change the registration url to http, add hosts using http and see if that gets you further.

**Comment by danielbjornadal** [comment]
It works if you change to http.

But what is very misleading, is that i connect to the rancher portal using https, and the portal provides me with an ssl url when adding a custom host. (using self signed certificates)

It really should be noted in the application, or at least changed to http if a selfsigned certificate is detected.

`docker run -d --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.1.3 https://192.168.96.138:8080/v1/scripts/A48E39A209002D5165BE:1484402400000:3BcRvb2XUQLFhgObpdWAxqBKIc`

changed to

`docker run -d --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.1.3 http://192.168.96.138:8080/v1/scripts/A48E39A209002D5165BE:1484402400000:3BcRvb2XUQLFhgObpdWAxqBKIc`

**Comment by sigfrid** [comment]
@danielbjornadal it seems to me the trick doesn't work anymore.

```
Traceback (most recent call last):
  File "./register.py", line 11, in <module>
    secret_key=os.environ['CATTLE_REGISTRATION_SECRET_KEY'])
  File "/usr/local/lib/python2.7/dist-packages/cattle.py", line 45, in from_env
    return gdapi.from_env(prefix=prefix, factory=Client, **kw)
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 613, in from_env
    return _from_env(prefix=prefix, factory=factory, **args)
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 632, in _from_env
    return factory(**result)
  File "/usr/local/lib/python2.7/dist-packages/cattle.py", line 12, in __init__
    super(Client, self).__init__(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 197, in __init__
    self._load_schemas()
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 315, in _load_schemas
    response = self._get_response(self._url)
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 264, in _get_response
    headers=self._headers)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
```

**Comment by superseb** [comment]
@danielbjornadal The portal shows the HTTPS URL because you are visiting the portal over HTTPS. (Host Registration URL, This site's address).

There has been some work on using self-signed certificates (http://docs.rancher.com/rancher/v1.6/en/installing-rancher/installing-server/basic-ssl-config/#using-self-signed-certs-beta). Getting it done and with proper documentation, this should be clear to users, would you agree?

**Comment by danielbjornadal** [comment]
@superseb
The documentation around this is not clear. 
Also, the documentation mix ca.crt (Certificate Authority (Chain?)) and cert.crt (Certificate) - and provides no information about the private key.

If you are to use Rancer in a PCI environment - all server-to-server communication must be encrypted.

**Comment by sandeepg21** [comment]
The reason the URL is not accessible is you might have enabled the Access control to particular user. Disable the access control from Admin>Access Control>Disable then you'll be able to add the centos machine. Once you have added you can enable the access control. Access control limits the Rancher/server access to the host. Thanks

**Comment by ramtej** [comment]
+1 same issue..

**Comment by danielbjornadal** [comment]
Any update on this? 
Could the documentation be updated with the following:
* Where to put the Certificate Private Key on rancher/server.
* ca.crt on rancher/server - please specify what to include. certificate + chain in a PEM format? (Certificate, InterCA, RootCA (in that order?))
* ca.crt on rancher/agent - please specify what to include. same as rancher/server? ca.crt is not a propper name if you only need the server certificate from rancher/server.

**Comment by denysvitali** [comment]
@danielbjornadal http://rancher.com/docs/rancher/v1.6/en/installing-rancher/installing-server/basic-ssl-config/#using-self-signed-certs-beta

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

**Comment by danielbjornadal** [comment]
Just leaving a comment here for whomever might want a quick fix.
Created a Docker image w/nginx and Let's Encrypt that automatically will setup a Reverse Proxy with a valid certificate. (remember to specify the backend port :8080)

https://hub.docker.com/r/bjornadalno/nginx-rp-letsencrypt/
