### ISSUE TITLE
Stuck adding custom host at INFO: Starting agent for ...

### ISSUE THREAD

**Issue by Schinti95** [rancher/rancher#7417]
**Rancher Versions:**
Server: v1.3.1
healthcheck:  v0.2.0
ipsec: rancher/net:holder
network-services: v0.4.0
scheduler: v0.5.1
kubernetes (if applicable):

**Docker Version:**
Docker version 1.12.6, build 78d1802

**OS and where are the hosts located? (cloud, bare metal, etc):** 
Ubuntu 16.04.1 LTS (with KVM) (4.4.0)

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node, internal

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle v0.175.6

**Steps to Reproduce:**
I created a new server, single node, and tried to add the same host as a rancher-agent as well.
The Rancher-Server is SSL-Protected by a nginx proxy.

Nginx-Config: 

    upstream rancher {
        server 127.0.0.1:8080;
    }
    
    server {
        listen <PUBLIC-HOST-IP>:8080 ssl default_server;
        server_name _;
        ssl_certificate /etc/nginx/ssl.crt;
        ssl_certificate_key /etc/nginx/ssl.key;
    
        location / {
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Port $server_port;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_pass http://rancher;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            # This allows the ability for the execute shell window to remain open for up to 15 minutes. Without this parameter, the default is 1 minute and will automatically close.
            proxy_read_timeout 900s;
        }
    }

The command to create the server: 
`sudo docker run -d --restart=unless-stopped --name=rancher-server -p 127.0.0.1:8080:8080 rancher/server:stable`

The command to add the first host (the same host that runs the server):
`sudo docker run -e CATTLE_AGENT_IP="<PUBLIC-HOST-IP>"  -d --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.1.3 https://<DOMAIN_OF_PUBLIC-HOST-IP>:8080/v1/scripts/ECF386957E13D0B0A2B5:1484398800000:ExAtzPHAsBdthkUptSeOD9zSXrA`

**Results:** 
The host is not added even after one hour, in the audit log i can see a Event of type "api.register.create", 
in the  logs of the rancher-agent i find:

> INFO: Starting agent for 65FBAF9752BC980D5314
> INFO: Starting agent for 65FBAF9752BC980D5314
> INFO: Starting agent for 65FBAF9752BC980D5314
> INFO: Starting agent for 65FBAF9752BC980D5314
> INFO: Starting agent for 65FBAF9752BC980D5314
> (over and over, always the same line )

**Expected:**
The host should be added to the rancher server so its visible in the Hosts-Page

**Comment by victort** [comment]
having same issue :+1:

**Comment by aemneina** [comment]
is this an agent host you reused? Can you wipe out `/var/lib/rancher` on the agent host and try re-registering?

**Comment by Schinti95** [comment]
No not reused, I even reinstalled the hosts OS ones. It always works with custom hosts unless i try to add a rancher-agent to the server running rancher-server.

**Comment by appacea** [comment]
Hi. I´m having the same problem. Anyone solve it?

**Comment by superseb** [comment]
@appacea Are you running `rancher/server` and `rancher/agent` on the same host, with specifying `CATTLE_AGENT_IP` ?

**Comment by appacea** [comment]
@superseb naw I´m not running on same host but I am trying to run the agent and server on a swarm overlay network, and maybe that´s not recommended. 

I basically have a cluster of 4 swarm hosts, with one overlay network. On 3 hosts I´m running 3 rancher servers (HA) and on another host I´m running the rancher agent. All rancher server and rancher agent containers are attached to the same overlay network so they can communicate with each other. To load balance the rancher servers I have a replica set of nginx containers also on the same overlay network, which is what the agent communicates with. In theory it seems like it should work, but instead the rancher agent gets stuck at "INFO: Starting agent for", after connecting to the rancher server.

**Comment by vincent99** [comment]
The agent container needs `--privileged`, which isn't supported by swarmkit.

**Comment by superseb** [comment]
That, and the repeated `INFO: Starting agent for 65FBAF9752BC980D5314` usually means something with the LB. i.e. nginx not responding correctly during all the requests when registering a host. 

Going to close this as not-a-bug, you can continue if there is still a Rancher issue we can help you with.

**Comment by appacea** [comment]
ok feel free to close it, I´m going to set it my environment up a different way. 

However, just so you know, I did test without routing through nginx by running the agent against only one rancher server service (referenced by service name, ex http://rancher-server-service01) and I had the same result. So it would seem that nginx is not the problem. But maybe there´s a problem with the built in swarm service discovery.

thanks

**Comment by vincent99** [comment]
As I said swarmkit doesn't support privileged, which the agent needs, so the setup script which you are running (`docker run ... rancher/agent`) can't start the real agent container.

**Comment by appacea** [comment]
@vincent99  thanks for clarifying. I´ll configure it without swarm.
