### ISSUE TITLE
[UI] fetch/XHR requests loose the port number at request time

### ISSUE THREAD

**Issue by activenode** [rancher/rancher#7419]
**Rancher Versions:**
Server: v1.3.0

**Docker Version:**
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   23cf638
 Built:        Tue, 27 Sep 2016 12:25:38 +1300
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   23cf638
 Built:        Tue, 27 Sep 2016 12:25:38 +1300
 OS/Arch:      linux/amd64

**OS and where are the hosts located? (cloud, bare metal, etc):**
Baremetal, Ubuntu 16.04 LTS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
No setup yet, the problem occurs when rancher/server is installed.

**Steps to Reproduce:**
1. When you start a rancher/server container and proxy it with an nginx container (see here: https://docs.rancher.com/rancher/v1.2/zh/installing-rancher/installing-server/basic-ssl-config/) then everything will work fine because the example uses the standard ports :80 and :443 .

2. Now I did map the SSL-Port (:443) of the NGINX proxy to 553 so that with `docker ps` you see something like:
`[...] 80/tcp, 0.0.0.0:5530->443/tcp   nginxcdocker_rancherserver_proxy_1`.

3. Now that the Proxy and the Rancherserver is running I can access the RancherUI on https://myhost:553. 

But nothing else than the startpage is accessible. This is because some of the requests just throw away the Port.

E.g.:
- https://myhost:553/v2-beta/projects/1a5/schema - is a correct request and works.
- https://myhost:553/v2-beta/projects?all=true&limit=-1&sort=name - works too.

But for the following requests the port is abandoned by the UI and therefore the whole UI does not work anymore:
- https://myhost/v2-beta/identities?limit=-1&sort=name
- https://myhost/v2-beta/projects/1a5/instances?limit=-1&sort=name

I did add a picture where the red request are all portless.
<img width="538" alt="bildschirmfoto 2017-01-15 um 15 29 14" src="https://cloud.githubusercontent.com/assets/9058762/21963246/97741cf0-db37-11e6-91cb-1d740af03c51.png">

**Results:** 
UI is not working at all. Startpage is showing though.

**Expected:**
Whatever host and port Rancherserver is running on, all requests should use these values.

**Comment by vincent99** [comment]
Sounds like `X-Forwarded-Port` and/or the original `Host` header aren't making it to the server container.  The server generates absolute URLs and needs to receive enough information to do so.

The UI In general follows the links returned by the API (which are missing the port in this case).   Schemas tell it what link to go to to get redirected.  A few  of the requests are working because we cheat a little and hardcode them so that several things can load in parallel instead of all of them having to wait for schemas to load.

**Comment by activenode** [comment]
Indeed. Here, needless to say: You made my day. Thanks sir 💪🏽

For all the others with similiar problems I now want to add more troubleshooting information:

The following is _proposed_ as nginx configuration in the **Rancher Docs**:

```
upstream rancher {
    server rancher-server:8080;
}

server {
    listen 443 ssl;
    server_name <server>;
    ssl_certificate <cert_file>;
    ssl_certificate_key <key_file>;

    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://rancher;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        # This allows the ability for the execute shell window to remain open for up to 15 minutes. Without this parameter, the default is 1 minute and will automatically close.
        proxy_read_timeout 900s;
    }
}
```

Using this configuration will work fine if you want to publish Port 443 on your host like so:
**`docker run -d -p 443:443 your-nginx`**

**But as soon as you want to do something like this:**
`docker run -d -p 530:443 your-nginx` to not block your hosts :443 port => THIS WILL NOT WORK.
The reason (thanks @vincent99 for the hints) is that your container port will still say that the forwarded port is 443 which then leads to scrambled requests because what you want is to tell that the forwarded port is 530.

Solutions for the latter one:

1. You can leave the above nginx configuration but change the ssl port it is listening to:
```
server {
    listen YOUR_PORT ssl; #instead of listen 443 ssl
    #.. rest of the configuration goes here
}
```
and this would be your docker command:**`docker run -d -p YOUR_PORT:YOUR_PORT your-nginx`**

2. You can change the nginx configuration so that the "final" port is not set by nginx variables:
```
server {
#....
  proxy_set_header        X-Forwarded-Host   $host:YOUR_PORT;
  proxy_set_header        X-Forwarded-Port  YOUR_PORT;
#....
}
```

This should solve the problem completely.
