### ISSUE TITLE
Upgrading option for infrastructure services is always shown (if using registry.default setting)

### ISSUE THREAD

**Issue by shoutcool** [rancher/rancher#7421]
**Rancher Versions:**
Server: 1.3.0

We use a private registry as a proxy for accessing docker hub. Because of that, we set the `registry.default ` setting, and everything works as expected. But on the Rancher UI there is now always an upgrading icon beside of the infrastructure services (e.g. load balancers).

after clicking the icon following text is shown: 

> The balancer software image will be upgraded from **myprivateregistry.foo.com/rancher/lb-service-haproxy:v0.4.9** to **rancher/lb-service-haproxy:v0.4.9**.

If we click on the upgrade button below, Rancher is restarting the infastructure service with the recommended image. But as we use the `registry.default ` setting, the upgrading icon is shown again. There is no way to get rid of Ranchers upgrading recommendation.

**Expected behaviour**
Rancher should not show the upgrading option if the `registry.default ` setting is used and the only difference in the image identifier is the registry's hostname

**Comment by kaos** [comment]
Indeed, we have the same issue: 
![screen shot 2017-02-01 at 15 48 43](https://cloud.githubusercontent.com/assets/72965/22511619/88f96182-e896-11e6-88e0-18d15a229f54.png)

Not a big deal, but annoying.

**Comment by vincent99** [comment]
This was changed to contains instead of starts with a while ago...
