### ISSUE TITLE
Rancher v1.3.0/v1.3.1 not adding ca.crt

### ISSUE THREAD

**Issue by hiscal2015** [rancher/rancher#7422]
**Rancher Versions:** v1.3.0/v1.3.1

**Docker Version:** 1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):** Ubuntu16.04, cloud

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single node ranche

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Any

**Steps to Reproduce:**
docker run -d -v /rancherdb/v1.3.0:/var/lib/mysql -v /rancherdata/certs/cert.crt:/ca.crt --restart=unless-stopped --name=rancher-server -p 8080:8080 rancher/server:v1.3.0

**Results:** 
It should add ca.crt but no related logs from "docker logs rancher-server" command, and actually cert.crt was not loaded.

**Expected:**

**Comment by vincent99** [comment]
The appropriate location is `/var/lib/rancher/etc/ssl/ca.crt` [for 1.3](https://docs.rancher.com/rancher/v1.3/en/installing-rancher/installing-server/basic-ssl-config/#rancher-server).
