### ISSUE TITLE
Starting new server results in "Invalid character 'c' looking for beginning of value"

### ISSUE THREAD

**Issue by darrenscerri** [rancher/rancher#7424]
**Rancher Versions:**
Server: 1.3.1

**Docker Version:**
1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):**
Centos 7.2 VM

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node Rancher + 4 hosts

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Start Rancher server and 4 hosts from scratch. Hosts cannot connect to server. Hosts screen is empty.

**Results:** 
```
time="2017-01-16T10:09:36Z" level=error msg="invalid character 'c' looking for beginning of value"
time="2017-01-16T10:09:42Z" level=error msg="invalid character 'i' in literal false (expecting 'a')"
time="2017-01-16T10:09:47Z" level=error msg="invalid character 'c' looking for beginning of value"
time="2017-01-16T10:09:52Z" level=error msg="invalid character 'c' looking for beginning of value"
time="2017-01-16T10:09:57Z" level=error msg="invalid character 'i' in literal false (expecting 'a')"
time="2017-01-16T10:10:02Z" level=error msg="invalid character 'b' looking for beginning of value"
time="2017-01-16T10:10:07Z" level=error msg="invalid character 'c' looking for beginning of value"
time="2017-01-16T10:10:12Z" level=error msg="invalid character 'b' looking for beginning of value"
time="2017-01-16T10:10:17Z" level=error msg="invalid character 'c' looking for beginning of value"
time="2017-01-16T10:10:22Z" level=error msg="invalid character 'i' in literal false (expecting 'a')"
```

**Expected:**
Hosts should manage to connect to server

**Comment by darrenscerri** [comment]
Was an internal DNS problem unrelated to Rancher.

**Comment by GuillaumeM69** [comment]
I have the same error, how did you solve, can you explain more ?

**Comment by georgevazj** [comment]
Hi! We're getting the same error too. Please, could you explain how you solved it?

Thanks!

**Comment by darrenscerri** [comment]
The issue was that the Rancher server was hosted internally on "rancher.<company>.com" and the DNS server was down so the domain couldn't be resolved.
