### ISSUE TITLE
Dot in volume name restriction breaking IP endpoints

### ISSUE THREAD

**Issue by ixis-andrew** [rancher/rancher#7426]
Hi,

We've recently upgraded to Rancher 1.3 and are having issues when using an NFS volume driver in conjunction with Rancher. When using the following example volume:

``` 123.123.123.123/dir/to/mount:/mount/to/here ```

we now get the message:

>Volume names can only contain letters, numbers, hyphen, underscore, and dot.

and is preventing us from mounting any of our old mounts that use IP addresses when using existing rancher/docker compose files. 

Doing the same test on a 1.1.4 installation of Rancher allows the volume to be created successfully as usual.

Thanks,

Andrew

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.3.0` Cattle: `v0.175.2` UI: `v1.3.5` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`containers.index`|

**Comment by ixis-andrew** [comment]
Have just been doing more testing. Rancher seems to accept the volume name if it starts with a slash e.g

123.123.123.123/dir/to/mount:/mount/to/here - doesn't work
/123.123.123.123/dir/to/mount:/mount/to/here - does work

So bug mustn't be to do with dots or restrictions as originally thought. Something seems strange still though as the top example does work with earlier versions.

Thanks,

Andrew

**Comment by ephillipe** [comment]
Because this error I do not can use Rancher EFS Volume Plugin.

**Comment by erickponce** [comment]
In fact, you cannot use other plugins like docker-volume-netshare as well, the same validation accurs for all drivers and as slashs are not permited, you cannot especify paths like fs-xxxxx/custom_path:mount/here to.

**Comment by superseb** [comment]
This validation was removed when `volumerDriver` is set in this commit (https://github.com/rancher/ui/commit/c9c0b550d29118a8750d0da81487f3df1463319d)
