### ISSUE TITLE
Problem to deploy hosts in Msft Azure

### ISSUE THREAD

**Issue by rafnijs** [rancher/rancher#7429]
**Rancher Versions:**
Server:v 1.3.1
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):
Cattle: v0.175.2

**Docker Version: 1.12.5

**OS and where are the hosts located? (cloud, bare metal, etc):**
Msft Azure

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
 Cattle
  Swarm

Unable to deploy new hosts to a Cattle of Swarm environment

The message on the hosts
Provisioning
 catllehost6 
The default lines below are for a sh/bash shell, you can specify the shell you're using, with the --shell flag. 

Creating machine... 
-shell flag. 

**Expected: deploy successfully a new host

Extra: If you create a new host in new environment in Msft Azure Rancher will create 3 address spaces in each Vnet in Microsoft Azure for each environment:
192.168.0.0/16
10.0.0.0/8
172.16.0.0/12

This configuration give IP-overlap? If you want to use VNET-Peering you are unable to connect different Vnets to each other
![1](https://cloud.githubusercontent.com/assets/18165345/21990251/61f7cd9c-dc0e-11e6-89b1-fd3e514d8563.png)
![2](https://cloud.githubusercontent.com/assets/18165345/21990252/61fde1fa-dc0e-11e6-900c-bf00829afaf2.png)
![3](https://cloud.githubusercontent.com/assets/18165345/21990248/61f66902-dc0e-11e6-850a-6e46e1da679e.png)
![4](https://cloud.githubusercontent.com/assets/18165345/21990250/61f75628-dc0e-11e6-9e25-e080b06a946d.png)
![5](https://cloud.githubusercontent.com/assets/18165345/21990249/61f6ddce-dc0e-11e6-8363-a1cc40e83d1d.png)

.

**Comment by tfiduccia** [comment]
Which size are you using?  I have seen this message before and it's because the person was using ExtraSmall size.  The ExtraSmall through ExtraLarge was for classic Azure VM and will be removed from the UI in the next release.  Instead please use Standard_A0 - A4.
Standard_A0 is ExtraSmall
Standard_A1 is Small (Need to add this one as it's not in the list)
Standard_A2 is Medium
Standard_A3 is Large
Standard_A4 is ExtraLarge

**Comment by rafnijs** [comment]
issue is solved:
the issue was related on Azure core limits:
Get-AzureRmVMUsage
Location: northeurope

Name                         Current Value Limit  Unit
----                         ------------- -----  ----
Availability Sets                        3  2000 Count
Total Regional Cores                    19   100 Count
Virtual Machines                        10 10000 Count
Virtual Machine Scale Sets               0  2000 Count
Standard A0-A7 Family Cores             18   100 Count

**Comment by tfiduccia** [comment]
@rafnijs - Glad you were able to figure it out.  I'm going to close the bug.  Let us know if you have other issues.
