### ISSUE TITLE
Any idea of how can I allow to a container with `host network` ping a container with rancher network in a vxlan setup?

### ISSUE THREAD

**Issue by criloz** [rancher/rancher#7430]
like the title said, I am not a network expert guy.

 I have installed vxlan in rancher,

(yes) I can ping between container on different hosts.
(yes) I can ping from a container with host network to a container in the same host using the rancher net CIDR

**(NO)** I can not ping between a container with host network to a other container(that use the rancher network) in **OTHER HOST**

how can I do this?, I can do it my self but need some help, do I need to use iptables?, or router the trafic to the interface in which the hosts are connected?, I can write a script that maintain those iptables/ router updates. 

thanks

**Comment by leodotcloud** [comment]
This got fixed by https://github.com/rancher/rancher/issues/6755.
@criloz please try again and open an issue if you are still having problems.
