### ISSUE TITLE
Create access and secret key on ranger/server container starting

### ISSUE THREAD

**Issue by AnthonySendra** [rancher/rancher#744]
Hello,

In order to use tools like ansible, we have to set the access key (CATTLE_ACCESS_KEY) and the secret key (CATTLE_ACCESS_KEY) for access to the api when the container ranger/server is started.

Something like that could be very useful:
```
$ docker run -d -p 8080:8080 rancher/server \
-e CATTLE_ACCESS_KEY=xxx
-e CATTELE_SECRET_KEY=yyy
```

With this trick, ansible is able with one deployment file to create server, create registry, add each hosts to the server and POST container creation on the right host. And no action is needed in the backoffice (in order to allow automatic deployment without any human intervention, except for run ansible script)

Or if you have an alternative solution ;)
Thanks

**Comment by deniseschannon** [comment]
We have this implemented with the concept of service accounts. 

http://docs.rancher.com/rancher/latest/en/rancher-services/service-accounts/
