### ISSUE TITLE
How to upgrade service via api

### ISSUE THREAD

**Issue by mc388** [rancher/rancher#7440]
I am working on a CI/CD setup with jenkins. My pipeline is nearly complete. Just the rancher service upgrade is missing. 

How can I trigger a service upgrade via the rancher api? I use the following curl command but got an error and I don't how to configure the upgrade strategy. 

```
curl -u "${CATTLE_ACCESS_KEY}:${CATTLE_SECRET_KEY}" \
-X POST \
-H 'Accept: application/json' \
-H 'Content-Type: application/json' \
-d '{"inServiceStrategy":null, "toServiceStrategy":null}' \
'http://myrancherip/v2-beta/projects/1a5/services/1s18/?action=upgrade'
```

And here the error:

```
{"id":"88336e9e-fdb7-432e-9296-9150a48d672b","type":"error","links":{},"actions":{},"status":422,"code":"MissingRequired","message":null,"detail":null,"fieldName":"Upgrade strategy needs to be set","baseType":"error"}
```

The goal is to upgrade the service with sidekick container and the option "start before stopping".

One additional question is, how do I get the docker container name from one service container to exec into it?

**Comment by fabiomontefuscolo** [comment]
To prevent my existing containers stopping while upgrade I did

```
{ "inServiceStrategy": { "startFirst": true } }
```
