### ISSUE TITLE
Change name of exported config files to be useful

### ISSUE THREAD

**Issue by ianseyer** [rancher/rancher#7442]
Currently, Rancher exports config files in a zip called `compose`. This results in a user having several `compose (n).zip` files on their system.

Why not have the exported config be something useful such as `<stack name> config.zip`?

I am willing to do this myself, but want feedback first.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
