### ISSUE TITLE
Setting minimum scale to 0 in webhooks results in ugly 404 error

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#7443]
**Rancher Versions:** master 1/17

**Steps to Reproduce:**
1.  Go to webhooks page
2.  Fill in Name and Service
3.  Set minimum to 0 and create

**Results:** Ugly 404 error
![image](https://cloud.githubusercontent.com/assets/11514927/22033748/f1644c7e-dca6-11e6-9dc7-fc0e40fd1e12.png)

**Expected:** No error and message saying "Minimum be at least 1"

**Comment by mrajashree** [comment]
@tfiduccia But it's a 400 error and the message also says "Minimum scale not provided/invalid"

**Comment by tfiduccia** [comment]
@mrajashree - this should give the same message as if it's a negative number.  Vince can parse the message out, I think, but why should the message be any different?
![image](https://cloud.githubusercontent.com/assets/11514927/22034184/9f7c6e44-dca8-11e6-8d2c-004396e41f44.png)

**Comment by mrajashree** [comment]
@tfiduccia Actually the above message "Min should be at least 1 character" is not from webhook-service.
@cjellick the reason for this message: "Minimum scale not provided/invalid" is that even providing no  Min makes the value of `config.Min` 0, so providing 0 and not providing any value will give the same error.

**Comment by tfiduccia** [comment]
@soumyalj - I can no longer reproduce this through the UI as Vincent has it impossible to add a 0 to either the min or max scale.  Can you check it through the API and make sure it's giving the correct error.

**Comment by soumyalj** [comment]
Tested with master. With minimum scale set to 0, the "Minimum scale not provided/invalid" message is displayed as expected with a ```400 Bad request``` error
```
soumyas-MacBook-Pro:notes soumya$ curl -i -H 'Accept: application/json' -H 'Content-Type: application/json' http://104.154.51.183:8080/v1-webhooks/receivers?projectId=1a5 -X POST -d '{"name": "scaleservicesup2", "driver": "scaleService", "scaleServiceConfig": {"action": "up", "amount": 1, "serviceId": "1s6", "min": 0, "max": 4}}'
HTTP/1.1 400 Bad Request
Content-Length: 186
Content-Type: application/json
Date: Wed, 25 Jan 2017 22:07:59 GMT
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Server: Jetty(9.2.11.v20150529)
Set-Cookie: PL=rancher;Path=/
X-Api-Account-Id: 1a5
X-Api-Schemas: http://104.154.51.183:8080/v1/schemas
X-Api-User-Id: 1a1

{"actions":{},"links":{"self":"http://104.154.51.183:8080/v1-webhooks/receivers"},"message":"Minimum scale not provided/invalid","status":"Server Error","statusCode":400,"type":"error"}

```

**Comment by pim-Den** [comment]
Hoi Soumyali,

Sorry, but I accidently touched an URI in tour report. The result was a screen filled with your data. This is obviously a security breach. My abject appologies for causing this breach. I hope you will forgive me.

Greetings,

Pim Dennendal

T: 070-70.0.242
M: 06-38.18.20.69

SysAdmin Clubnix [.net]

Breezandstraat 58
2583 KV 'sGravenhage
The Netherlands
