### ISSUE TITLE
Changing Scale for cloned webhook throwing error

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#7445]
**Rancher Versions:** Master 1/17

**Steps to Reproduce:**
1.  Create a webhook
2.  Clone webhook and change name and change either the Minimum or Maximum scale (I changed the max to 5, I also tried just changing the minimum scale to 3) and click Create

**Results:** Error "Bad reque3st body: jason: cannot unmarshal string into Go value of type float64"
![image](https://cloud.githubusercontent.com/assets/11514927/22035008/98328d28-dcab-11e6-964f-e9d2b7272965.png)

**Expected:** No error

**Comment** Although after the initial problem is fixed I won't be able to reproduce.  We should be parsing this error so the code is not showing up (I think that is Vincent).

**Comment by mrajashree** [comment]
After changing the scale, the request has min/max as type string.
This is request payload I see in dev tools:
<img width="1061" alt="screen shot 2017-01-17 at 11 00 15 am" src="https://cloud.githubusercontent.com/assets/10672776/22035396/b115dd60-dca4-11e6-917b-f6f6e2ec6960.png">

**Comment by vincent99** [comment]
@mrajashree That is because it doesn't go through the validator, which is because there's no `type` on the `scaleServiceConfig` when it starts from one returned by the API instead of an empty one I generate.  Can you return `type: "scaleService"` on them?

**Comment by vincent99** [comment]
@mrajashree Also the type on min/max/amount in schemas should be `int` instead of `float`.

**Comment by mrajashree** [comment]
@vincent99 The PR to change min/max/amount to int was merged yesterday but there wasn't a release of webhook-service since then. I'll do the return  `type: "scaleService"` change

**Comment by tfiduccia** [comment]
Version - master 1/24
Verified fixed
