### ISSUE TITLE
Deleting webhook with long name has text running outside of delete box

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#7447]
**Rancher Versions:** master 1/17

**Steps to Reproduce:**
1.  Create a webhook with a really long name
2.  Delete webhook

**Results:** text runs out of box
![image](https://cloud.githubusercontent.com/assets/11514927/22036381/8be6c0f2-dcb0-11e6-8205-87c021a49838.png)

**Expected:** Should not

**Comment by vincent99** [comment]
Not sure if this still applies to 2.0 but break-word @lvuch

**Comment by tfiduccia** [comment]
Version - 2.0 master 10/16
Verified fixed.
