### ISSUE TITLE
404 for v1 API WebSockets

### ISSUE THREAD

**Issue by mattdodge** [rancher/rancher#7448]
**Rancher Versions:**
Server: 1.3.1
healthcheck: 0.2.0
ipsec: 0.0.2
network-services: 0.0.8
scheduler: 0.3.0
kubernetes (if applicable): n/a

**Docker Version:** 1.12

**OS and where are the hosts located? (cloud, bare metal, etc):** AWS RancherOS for hosts, Server running on AWS CoreOS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** HA External DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:**
 - Fresh install of Rancher server (new DB) and creation of hosts
 - HA Rancher server running behind an AWS ALB with HTTP/HTTPS both forwarding to 8080
 - Try to view a host's logs or host statistics (i.e. `https://<rancher-server>/env/1a7/infra/hosts/1h3/containers`)

**Results:** 
No host statistics or logs can be viewed. The javascript console shows the following:
```
WebSocket connection to 'wss://<rancher-server>/v1/hoststats?token=<my-token>&sockId=19' failed: Error during WebSocket handshake: Unexpected response code: 404
```
Screenshot of Server UI:
![screenshot 2017-01-17 12 23 01](https://cloud.githubusercontent.com/assets/797259/22036159/c8fb527e-dcaf-11e6-9437-496b82c77e03.png)

**Expected:**
Websockets to connect and for CPU stats or logs to load

It appears that all of the `v1` websockets are affected. I know `wss://` is working with my ALB because I'm able to connect to some `v2-beta` API websockets like `v2-beta/projects/1a7/subscribe`.

I've seen errors for the following websockets:
 - `v1/containerstats`
 - `v1/logs`
 - `v1/hoststats`
 - `v1/exec`

I've seen successful websocket connections for the following:
 - `v2-beta/projects/XXX/subscribe`

**Comment by mattdodge** [comment]
FYI, the same errors occur if I switch everything to use http and insecure websockets (`ws://`) too. It looks as if the API endpoint isn't being found for some reason? I can access v1 API endpoints via HTTP though (i.e. this works-> `https://<rancher-server>/v1/containerevents`).

**Comment by mattdodge** [comment]
**Update**:
In my ALB I had both HTTP and HTTPS forwarding to port 8080 for the Rancher servers. Removing the HTTP one and only leaving HTTPS has caused the 404s to stop. 

However, there's still something weird with the web sockets. I restarted the servers and tried to reconnect. At first, I got some failed connections because of `failed: HTTP Authentication failed; no valid credentials available`. After a little while, those stop (best guess is an old JWT was cached somewhere) and the web sockets start working! For a while at least. As time goes on (a few hours later) I actually start to see some 504 errors (not 404) coming back from the Rancher server. Along with a handful of these in the rancher server logs:
```
level=info msg="Couldn't find frontend channel for key 94458125-193e-4536-621b-dca44b96c2ef. Closing frontend connection.
```

**Comment by Moeser** [comment]
I'm seeing similar symptoms, but different response codes.  v2-beta websockets working fine.   v1 websockets returning 502 (Bad Gateway) or 401 (HTTP Authentication failed; no valid credentials available).  I'm not using https, but the console shows that these are ws:// connections, not wss://.  I've tried both directly accessing the host, and having an ALB in front, but I get the same behavior either way.  Since this affects v1 websockets and not v2-beta, and the behavior seems to be switching between different response codes, I believe it's related to the same root cause.

More info: I'm using v1.3.0 in HA mode with 3 Rancher servers, and it was upgraded from v1.1.4 HA.  It's also configured with Access Control disabled.  I didn't notice any log messages for the 502 responses, but for the 401 responses I'm seeing this in the Rancher server logs:
`time="2017-01-18T23:26:52Z" level=info msg="Invalid HostUuid." hostUuid=<guid-omitted-here>`
I removed the guid before pasting, but it appeared to be a real guid, not a syntax error or anything.  The rancher servers are running on RancherOS 0.7.1.

**Comment by michaellopez** [comment]
We are having the same issue, been debugging this for a few days too. We use Rancher 1.3.0 in single container, bind mounted volume db on AWS with ALB in front with HTTPS enabled. Whats weird for us is pointing directly to the Rancher server IP and port without HTTPS the websockets connections work as they should. It points to ALB doing something that is messing up Rancher. Will try a test where I remove ALB from the stack and see if it works then...

**Comment by aemneina** [comment]
@mattdodge anything thrown back in the rancher server logs while the UI is being uncooperative?

**Comment by mattdodge** [comment]
I also had a few of the same response codes that @Moeser had. And I can confirm that my server logs contain a few of the `Invalid HostUuid` messages. No guarantee that they occurred at the same time as when I saw the `502` or `401` responses, but the timestamp is close to around the time I was seeing issues.

@aemneina I had some of the `Couldn't find frontend channel` messages I posted above. Also a few of these scattered throughout:
```
Shutting down backend 17e54367-b1dc-43b1-6b22-cfdccc567d5f. Connection closed because: websocket: close 1006 unexpected EOF.
```

**Comment by Moeser** [comment]
In my case, I noticed that the 401 responses were all coming from the same Rancher server, so I restarted the Rancher server container.  The restart at least brought the host to the same state as the rest, and now all three are giving 502 (Bad Gateway) responses to v1 websocket calls.

So far all three of us are using ALB, but I should point out that I also tested this *without ALB* by talking directly to the host, and experienced the same behavior.

**Comment by michaellopez** [comment]
@Moeser For us, we can go directly to the EC2 instance that is running the rancher/server container on port 8080 and all `v1` ws connections work as expected, UI works perfect. So as far as I can tell, it must be an incompatibility between Rancher and ALB that is causing this. Just gotta figure out what...

**Comment by mattdodge** [comment]
I reenabled the HTTP portion of my ALB (80 -> 8080) and things seemed fine for a while. But now I'm seeing sporadic behavior again and a lot of these:

JS Console error:
```
WebSocket connection to 'wss://<rancher-host>/v1/containerstats?token=<token>&sockId=6' failed: HTTP Authentication failed; no valid credentials available
```

Rancher Server Logs (with host uuid subbed out):
```
level=info msg="Invalid HostUuid." hostUuid=<uuid>
level=info msg="Stats auth failed: could not find host uuid"
level=info msg="Stats auth failed: Error parsing stats token. Failing auth. Error: token is expired"
```

It works some of the time and certain screens seem to work better than others but we're still not at 100%. I also enabled stickiness on the ALB, not sure if that's needed or not, but figured it was worth mentioning.

**Comment by janeczku** [comment]
Reproduced on v1.3.3 HA with ALB in front (HTTPS listener). v1 stat and log websocket requests throw 404 errors.

> time="2017-02-03T16:41:00Z" level=info msg="Shutting down backend feb09df4-3181-4cba-87ec-1038c38ae640. Connection closed because: websocket: close 1006 unexpected EOF."

Issue gone after replacing the ALB with a classic ELB load balancer (LB proto: SSL, backend proto: TCP, proxy-protocol: enabled)

**Comment by aemneina** [comment]
As of 1.3.3 we're recommending ELB over ALB due to transient issues like this.

**Comment by mattdodge** [comment]
So we should switch to an ELB (Classic Load Balancer) then? These docs probably need to be updated: http://docs.rancher.com/rancher/v1.4/en/installing-rancher/installing-server/#running-rancher-server-behind-an-application-load-balancer-alb-in-aws

> We recommend using an Application Load Balancer (ALB) in AWS over using an Elastic Load Balancer (ELB).

**Comment by aemneina** [comment]
thanks for pointing that out, I've submitted a PR to change that. @deniseschannon

**Comment by Moeser** [comment]
I mentioned this further up, but at one point we were seeing the errors to endpoints not behind an ELB or ALB.  However, that went away when we upgraded from 1.3.0 to 1.3.3.  Now it only happens if an ALB is in place.

**Comment by aemneina** [comment]
Cool, good to know @Moeser.
