### ISSUE TITLE
Service links not working (in same stack)

### ISSUE THREAD

**Issue by floranger** [rancher/rancher#7451]
**Rancher Versions:**
Server: 1.3.0
healthcheck: 0.2.0
ipsec: 0.8.1
network-services: 0.4.0
scheduler: 0.5.1
kubernetes (if applicable):

**Docker Version:**
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 22:01:48 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 22:01:48 2016
 OS/Arch:      linux/amd64

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04.1 LTS - Baremetal

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Create a stack
Create service foo:
foo:
    image: nginx:latest
    hostname: foo
    stdin_open: true
    network_mode: bridge
    tty: true
    ports:
    - 8080:80/tcp
    labels:
      io.rancher.container.pull_image: always

Create service bar (linked to foo):
bar:
    image: nginx:latest
    hostname: bar
    stdin_open: true
    network_mode: bridge
    tty: true
    links:
    - foo:foo
    ports:
    - 8081:80/tcp
    labels:
      io.rancher.container.pull_image: always

docker exec -it _foo_ /bin/bash
root@foo:/# ping bar

docker exec -it _bar_ /bin/bash
root@bar:/# ping foo

**Results:** 
root@foo:/# ping bar
ping: unknown host

root@bar:/# ping foo
ping: unknown host

**Expected:**
Ping command should resolve hostnames. Using ping with IPs is fine.

Maybe a duplicate of #7377

**Comment by aemneina** [comment]
@floranger have you tried this with the new v2 rancher compose syntax? Here's a reference to that: http://docs.rancher.com/rancher/v1.3/en/cattle/adding-service-alias/

**Comment by floranger** [comment]
@aemneina just did and work efficiently. I will create a docker-compose.yml file to suit my needs. However, I was creating everything from UI and copy-pasted the auto-generated docker-compose.yml file in this issue. So even if solution is working, UI does not.

**Comment by miensol** [comment]
When we launched `docker-compose` file with `network_mode: bridge` it turned out that the dns server was not configured inside containers. Further the `docker inspect dockerServiceId` revealed empty `HostConfig.Dns`. The Rancher UI also displays empty Resolving Servers.

Is this expected and the `dns` should be manually specified in case someone uses `network_mode: bridge` in `docker-compose`?

**Comment by inabhi9** [comment]
Any update on this? I'm facing this issue too. I want to limit service linking to same host

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
