### ISSUE TITLE
[external-lb] Does not work with private hosts (lacking public IP address)

### ISSUE THREAD

**Issue by jsalva** [rancher/rancher#7453]
**Rancher Versions:**
Server: v1.2.1
healthcheck: :v0.2.0
ipsec: v0.8.1
network-services: 
- metadata: v0.7.0
- dns: v0.13.0
- network-manager: v0.4.0

scheduler: v0.5.1
kubernetes (if applicable): N/A

**Docker Version:**
1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):**
EC2: Amazon Linux AMI 2016.09.1 (HVM), SSD Volume Type - ami-b73d6cd7

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher, RDS DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
- Launch rancher hosts on AWS in a private VPC subnet without public IP address
- Run rancher/external-lb with `ELBV1_USE_PRIVATE_IP: 'true'` in environment (alongside valid AWS key/secret)
- Follow [rancher guidelines](http://rancher.com/inside-the-external-elb-catalog-template/) to create an ELB Classic Load Balancer, configure health checks, security groups, etc
- Start an nginx service with `io.rancher.service.external_lb.endpoint: <elb_name>` on host without public IP

**Results:** 
```
1/17/2017 2:52:41 PM panic: runtime error: invalid memory address or nil pointer dereference
1/17/2017 2:52:41 PM [signal 0xb code=0x1 addr=0x0 pc=0x6e00bc]
1/17/2017 2:52:41 PM
1/17/2017 2:52:41 PM goroutine 1 [running]:
1/17/2017 2:52:41 PM panic(0xb6b2c0, 0xc8200160d0)
1/17/2017 2:52:41 PM	/usr/local/go/src/runtime/panic.go:481 +0x3e6
1/17/2017 2:52:41 PM github.com/rancher/external-lb/providers/elbv1/elbv1svc.(*ELBClassicService).LookupInstancesByFilter(0xc820344040, 0xc820365d00, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0)
1/17/2017 2:52:41 PM	/go/src/github.com/rancher/external-lb/providers/elbv1/elbv1svc/ec2.go:82 +0x78c
1/17/2017 2:52:41 PM github.com/rancher/external-lb/providers/elbv1/elbv1svc.(*ELBClassicService).LookupInstancesByIPAddress(0xc820344040, 0xc820365c40, 0x1, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
1/17/2017 2:52:41 PM	/go/src/github.com/rancher/external-lb/providers/elbv1/elbv1svc/ec2.go:48 +0x235
1/17/2017 2:52:41 PM github.com/rancher/external-lb/providers/elbv1.(*AWSELBv1Provider).getEC2Instances(0xc820013440, 0xc820372ea0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
1/17/2017 2:52:41 PM	/go/src/github.com/rancher/external-lb/providers/elbv1/aws_elbv1.go:338 +0x27e
1/17/2017 2:52:41 PM github.com/rancher/external-lb/providers/elbv1.(*AWSELBv1Provider).AddLBConfig(0xc820013440, 0xc82037e4f6, 0x9, 0xc8202f4940, 0x3a, 0xc82037e660, 0x4, 0xc820372ea0, 0x1, 0x1, ...)
1/17/2017 2:52:41 PM	/go/src/github.com/rancher/external-lb/providers/elbv1/aws_elbv1.go:197 +0x514
1/17/2017 2:52:41 PM main.updateProvider(0xc82036bb30, 0x1, 0x1, 0x0, 0x1)
1/17/2017 2:52:41 PM	/go/src/github.com/rancher/external-lb/external-lb.go:145 +0x250
1/17/2017 2:52:41 PM main.addMissingConfigs(0xc820325230, 0xc8202564e0, 0xc820256510)
1/17/2017 2:52:41 PM	/go/src/github.com/rancher/external-lb/external-lb.go:85 +0x304
1/17/2017 2:52:41 PM main.UpdateProviderLBConfigs(0xc820325230, 0xc820325230, 0x0, 0x0)
1/17/2017 2:52:41 PM	/go/src/github.com/rancher/external-lb/external-lb.go:25 +0x195
1/17/2017 2:52:41 PM main.main()
1/17/2017 2:52:41 PM	/go/src/github.com/rancher/external-lb/main.go:126 +0x50f
```

Error at https://github.com/rancher/external-lb/blob/master/providers/elbv1/elbv1svc/ec2.go#L82 since instance does not provide a public ip address (it is in a private subnet and never gets a public IP assigned; vpc internal ips should be used instead)

**Expected:**
Container should successfully attach instances running the service to the configured external EC2 Classic LB.
Most importantly: No error on instances with no public IP.

**Comment by jsalva** [comment]
My PR to fix this passed tests, but I can't seem to build this myself and ship it to ECS. I don't really grok dapper, or the proper way to build this repo from scratch. 

When I forked the repo and cloned it locally, I ran `make` and shipped the resulting image to a repository in ECS. My rancher hosts can pull this image, but it ends up throwing an error in the entrypoint

```
1/17/2017 4:51:25 PM./scripts/entry: line 8: exec: -p: invalid option
1/17/2017 4:51:25 PMexec: usage: exec [-cl] [-a name] [command [arguments ...]] [redirection ...]
```

**Comment by NickClark** [comment]
I think this is similar to an issue we are having. We are using a VPC, with all but three nodes on a private subnet. The three public nodes do have Elastic IPs, and we were hoping that there was a way to have the load balancer use a node selector of sorts to ensure that we always have three load balancers, one on each. Is there another ways that is preferred/intended?

**Comment by jsalva** [comment]
`make release` from within the repo worked. My updated image fixes this issue.

**Comment by jsalva** [comment]
[My fork](
https://github.com/jsalva/external-lb) has this patched. Waiting on a PR, but feel free to use my version
