### ISSUE TITLE
How to properly set up AWS ALB Health Checks on HA Rancher Server?

### ISSUE THREAD

**Issue by mattdodge** [rancher/rancher#7454]
**Rancher Versions:**
Server: 1.3.1

**OS and where are the hosts located? (cloud, bare metal, etc):** AWS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** HA, behind an AWS Application Load Balancer

This is maybe not so much an issue as it is a question. We run our rancher server install behind an Application Load Balancer (ALB) on AWS. Ideally, we could rely on the ALB target group health checks to keep an eye on whether the rancher/server docker container is running on the hosts. However, we have GitHub access control set up so when you hit `https://<rancher_host>/` or any other API endpoint you get a 401 response code back. That tells the load balancer's health checker that the host is not working.

Right now, we're working around it by also running an nginx container alongside the rancher server on a different port and redirecting our health checks there. But that won't tell us if the rancher/server container dies for some reason. Is there any kind of API endpoint or maybe another port that doesn't require authentication and can return a 200 if it's up and running? I would even go with creating an API key for the health check and somehow passing it in the health check API request.

I have to believe other users running behind ALB have encountered a similar situation but I couldn't find any mention of it in the docs or issues. Granted, any google search involving "rancher" and "load balancer" almost always refers to load balancers *within* Rancher, where in this case I'm curious about Rancher *behind* a load balancer. But I assume someone's figured out something better than I have.

**Comment by cloudnautique** [comment]
There is `/ping` that will return a pong + http 200. Though, I sometimes prefer `/v1/scripts/api.crt` because it hits the DB and proves out that path a bit better.

**Comment by mattdodge** [comment]
Perfect! This is exact type of answer I was looking for, thanks.
