### ISSUE TITLE
Document: in order to use AWS ELB/EBS "aws" provider has to be chosen instead of "rancher" in k8s environment template

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#7455]
We should document the fact that in order to use AWS LB/Persistent volumes - ELB/EBS - "aws" has to be chosen as a Cloud provider instead of Rancher when create k8s environment template.

**Comment by tfiduccia** [comment]
@deniseschannon 
These are the more detailed steps provided to customer from @LLParse 

Steps:
Navigate to Kubernetes > Infrastructure Stacks
Click the Up to date button and select your current version from the dropdown
Change cloud provider to AWS
Click Upgrade
After doing this, your stack should be capable of using the aws-ebs plugin.

**Comment by paulosuzart** [comment]
Hi, after updating the kubernetes stack to aws provider, get permanent:

    time="2017-01-31T19:23:03Z" level=error msg="Error looking up token." error="HTTP error: 404 Not Found, 404" 

No way to get it back to work. Maybe there is a definitive solution to come?

**Note:** _RancherOS v0.7.1, Rancher 1.3.3 on AWS aim ami-ab3192cb_

**Comment by alena1108** [comment]
We should document the entire flow including IAM policy setup. @galal-hussein could you take over @galal-hussein could you work with @deniseschannon on documenting it?

**Comment by galal-hussein** [comment]
@alena1108 @deniseschannon I will make sure to document the whole process of using AWS as the provider and I will include the IAM policy settings.

**Comment by wlan0** [comment]
@galal-hussein Also include in the document the practice of adding hosts only via "Custom Add Host" and not via machine driver. Thanks!

**Comment by deniseschannon** [comment]
Can we also add documents on how to use/enable nfs as well? @galal-hussein

**Comment by galal-hussein** [comment]
@deniseschannon https://github.com/rancher/rancher.github.io/pull/681

**Comment by galal-hussein** [comment]
@deniseschannon https://github.com/rancher/rancher.github.io/pull/682 - NFS docs
