### ISSUE TITLE
Option to limit CPU when installing a new stack

### ISSUE THREAD

**Issue by mortenhartvig** [rancher/rancher#7456]
Wouldn't it be nice, if you at least had the option to limit/cap CPU usage upon installation of a new stack/container.

If you are adding containers/stacks to a production environment, there could be a need for slow installation (to stop cpu usage hitting 100%, slowing down other services).

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.3.0` Cattle: `v0.175.2` UI: `v1.3.5` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`admin-tab.settings`|

**Comment by nheinemans** [comment]
We are also looking for this option. Some stacks are running high-cpu containers, causing the rancher agent container to stop responding.

Also, giving system stacks might even be a better solution, if at all possible.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
