### ISSUE TITLE
[external-lb] Support for AWS ALB (elbv2)

### ISSUE THREAD

**Issue by agalpin** [rancher/rancher#7457]
**Rancher Versions:**
Server: 1.3.0
healthcheck: 0.2.0
ipsec: 0.8.1
network-services: 0.7.0 (meta), 0.4.0 (manager)
scheduler: 0.5.1
kubernetes (if applicable):

**Docker Version:**
1.12.3
**OS and where are the hosts located? (cloud, bare metal, etc):**
AWS, ubuntu 16.04

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node, internal db, volume container

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

Would it be possible to get support for aws alb (elbv2) with the external-lb service via the catalog if possible?

**Comment by ampedandwired** [comment]
Seems like this was started on in #5959 but progress seems to have been stalled. I too would love to see a supported ELBv2 external LB.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
