### ISSUE TITLE
Open home page of rancher is very slow

### ISSUE THREAD

**Issue by yeruisen** [rancher/rancher#7458]
rancher version: 1.3.1
2 node
external DB
100 container

**Comment by yeruisen** [comment]
![image](https://cloud.githubusercontent.com/assets/12295648/22056358/be896ff6-dd9a-11e6-84b4-683eb4d209d3.png)

**Comment by aemneina** [comment]
Is this reproducible on a newer version of rancher? There have been optimizations made in this area.

**Comment by danielschlegel** [comment]
its better, still not fast though.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
