### ISSUE TITLE
Registry not being passed to host if registry added after host was already added

### ISSUE THREAD

**Issue by chrisurwin** [rancher/rancher#7461]
**Rancher Versions:**
Server: 1.3.0
**Docker Version:**
1.10.3 & 1.12.6
**OS and where are the hosts located? (cloud, bare metal, etc):**
Virtual
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes
**Steps to Reproduce:**
Set up a k8s environment and add hosts
Add a private registry
try to deploy an image from that registry to the k8s environment
**Results:**
doing kubectl get pods shows error *ErrImagePull* 

Removing the host and then re-adding it fixes the problem but isn't a practical solution.

**Comment by wlan0** [comment]
kubelet calls the rancher credential provider for credentials only on startup. That's why new credentials get pulled whenever you re-add the host(it forces kubelet restart). 

This is a kubernetes quirk by design. There's nothing we can do about it. For now at least!

**Comment by cjellick** [comment]
Thanks for the explanation @wlan0

**Comment by deniseschannon** [comment]
@StrongMonkey Can you look into trying to force a restart for the `kubelet` service when a registry is added for k8s environments?

**Comment by deniseschannon** [comment]
When we add this in, we should add in UI that tells users that `kubelets` will be restarted.

**Comment by StrongMonkey** [comment]
@deniseschannon There is a way to dynamically pull registry credential when pulling image. It is called LazyProvide as @wlan0 suggested. If this is implementable, i think it will be a better way. Otherwise we can then add a hook to restart kubelet service when adding a registry.

**Comment by StrongMonkey** [comment]
@sangeethah This is ready to test. The fix is available in k8s 1.5.4.

**Comment by galal-hussein** [comment]
Rancher server: v1.5.2-rc2
K8s: 1.5.4

I was able to test using private registry, k8s pods were able to pull and run the private images successfully.
