### ISSUE TITLE
Trouble with logs and shell - fresh install, not displayed

### ISSUE THREAD

**Issue by bringha1** [rancher/rancher#7462]
**Rancher Versions:**
Server: 1.3.1
healthcheck: 0.2.0
ipsec: 0.81
network-services: 0.81
scheduler: ??
kubernetes (if applicable): is Cattle

**Docker Version:**
1.12.6
**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04 cloud based on Openstack, m1.medium (4 GB, 2 vcpus)
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node with external db, mysql 5.7
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
Fresh Install, bring up server, add host, try to show logs, shell
**Results:** 
Shell, log windows don't pop up

I made a fresh install of a rancher server on an openstack vm based on ubuntu 16.04 cloud image.
An external database runs on the same VM than rancher server, is configured with more than 150 connections. Overall installation and self config ran 75 min. (!!), but finally came up.

Still, I can't see Logs and Shell popup window in UI. 

- Main screen gets light, but window does not pop up. 

- Checked time sync, but on all nodes chrony is running and syncing against the same server. 

- Logs do not contain any hints about failed socket connections. 

- Host traffic and cpu graphs work so that I assume that basically websocket interface is up

Does someone has any idea?

Thanks!

Br br

**Comment by aemneina** [comment]
@bringha1 are you still facing this issue?

**Comment by superseb** [comment]
Best way to track this down is using Developer Tools in your browser to see what's failing. Also, 75mins to start does not sounds like a really good performing machine. Please file a new issue if you still experience problems with newer versions.
