### ISSUE TITLE
volumestoragepoolmap.remove processes are growing because volumes cant be deleted

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#7464]
**Rancher Versions:**
Server: 1.3.1

**Docker Version:**
1.12.2

**OS and where are the hosts located? (cloud, bare metal, etc):**
ubuntu 14.04

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA setup

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
upgrade from 1.1.2 -> 1.3.1

**Results:** 
There is a growing number of volumestoragepoolmap.remove processes. On the backend there might be a docker bug thats not able to remove volumes. Rancher cant process these fast enough.

**Comment by galal-hussein** [comment]
Rancher version: 1.3.2-rc2
OS: Ubuntu 16.04
Docker: 1.12

Validated the following steps:

1. In cattle create a container (either standalone or in a service) that uses an anonymous volume, meaning it must do the rancher equivalent of `docker run -v /foo ...`
2. Go to the host where that container started, find the anonymous volume. Use the command `docker volume ls`. The rancher container UI shows the volume name, so you can correlated from there.
3. Still on the host, using the docker cli *create* _(dont start)_ a container that uses the anonymous volume. Command will look like `docker create -v <big log string>:/foo ubuntu`
4. Back in rancher, delete and purge the container.

There are no errors on the rancher server or agent, and there is no volumestoragepoolmap.remove processes stuck in Rancher server.
