### ISSUE TITLE
service link aliases (somtimes) auto-prefixed with stack name

### ISSUE THREAD

**Issue by arnold-graf** [rancher/rancher#7466]
**Rancher Versions:**
Server: 1.2.0
UI: 1.2.34

Hi there,
first off: really love what you’re doing with rancher.
I noticed that sometimes, when i hit upgrade or clone in a service, aliases ("As Name") for service-links seem to get prefixed with their original stack name ("stack-name/service-name"). However, when I finish the upgrade (or the cloning), an error is thrown:
"Validation failed in API: name contains invalid characters"
Yet, the service still updates with the new configuration and the container link-alias does not actually work. When I update again, deleting "stack-name/" from the alias, everything works fine.

any help appreciated

**Comment by tfiduccia** [comment]
@arnold-graf - Hello this was reported before and has already been fixed in 1.2.1 and 1.3.0.  Please upgrade and if you find you are still having issues, reopen the issue.

**Comment by arnold-graf** [comment]
oh. silly me. thanks a lot for the quick answer!
