### ISSUE TITLE
kubectl exec fails (through ALB)

### ISSUE THREAD

**Issue by TylerRick** [rancher/rancher#7470]
**Rancher Versions:**
Server: Rancher v1.3.1
healthcheck: v0.2.0
ipsec: v0.0.2
network-services: v0.0.08
scheduler: v0.3.0
kubernetes:v1.5.1-rancher1-8

**Docker Version:** 1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):** AWS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single node rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Kubernetes

**Steps to Reproduce:**
1. Kubernetes environment
2. Add AWS hosts in VPC
3. Create Application Load Balancer for ports 80/443 that terminates SSL and routes to our single Rancher instance on port 8080)
4. Download `kubectl` config from https://something.com/env/1a220/kubernetes/kubectl
5. Run `kubectl exec -it container_name bash`

**Results:** 
```
Error from server (BadRequest): Upgrade request required
```

`kubectl logs` appears to also not work (may be related?)

(`kubectl get`, etc. work fine)

**Expected:**
kubectl exec works

**See also**:
- #7425 (for Rancher HA/traefik)

**Comment by TylerRick** [comment]
Here's screenshots of our load balancer config in case that's helpful:

![image](https://cloud.githubusercontent.com/assets/14151/22086588/3c2db1f4-dd8e-11e6-9767-aae9248edfc9.png)

![image](https://cloud.githubusercontent.com/assets/14151/22086600/54dc945e-dd8e-11e6-8a24-7bea32bf66f5.png)

**Comment by TylerRick** [comment]
I think we can rule out ALB being the problem. I was able to reproduce it by using curl directly inside of my rancher server:

```
> ssh rancher.example.com

rancher@ip-10-0-1-31:~$ curl --user 7...:W... 'http://localhost/r/projects/1a220/kubernetes/api/v1/namespaces/exp/pods/echo-text/exec?command=bash&container=echo-text&stderr=true&stdout=true'
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "Upgrade request required",
  "reason": "BadRequest",
  "code": 400
}
```

**Comment by TylerRick** [comment]
Actually, I may have spoken too soon. After reading [here](http://stackoverflow.com/questions/37349440/upgrade-request-required-when-running-exec-in-kubernetes), I tried `curl -H "Connection: upgrade" -H "Upgrade: SPDY/3.1"` and now there's no `Upgrade request required` error but it just hangs there. What is it supposed to do when you curl it?

**Comment by ibuildthecloud** [comment]
@TylerRick This will be fixed shortly (less than a week).  Quite unfortunately ALB does not support SPDY (well, it's deprecated, so really it's unfortunate that k8s uses it).  As such the only option will be to use ELB, which is much more difficult than ALB because it requires setting up proxy protocol.  This is why we dropped ELB support to begin with is that most users struggle to configure proxy protocol properly.  Unfortunately we missed this use case where kubectl exec needs it.  Right now `kubectl exec` will only work if you are running Rancher single node (non-HA) and you hit port 8080 directly.

We need to reenable our proxy protocol support, so this will be in 1.3.3.

**Comment by TylerRick** [comment]
Thanks for the update, @ibuildthecloud! :+1:

**Comment by galal-hussein** [comment]
Validated the fix on Rancher v1.2.3, and v1.3.3, here are the steps:

- Run Rancher HA setup with ELB
- The ELB should be configured to use proxy protocol
```
$ aws elb create-load-balancer-policy --load-balancer-name my-elb --policy-name myorg-ProxyProtocol-policy --policy-type-name ProxyProtocolPolicyType --policy-attributes AttributeName=ProxyProtocol,AttributeValue=true
$ aws elb set-load-balancer-policies-for-backend-server --load-balancer-name my-elb --instance-port 81 --policy-names myorg-ProxyProtocol-policy
$ aws elb set-load-balancer-policies-for-backend-server --load-balancer-name my-elb --instance-port 444 --policy-names myorg-ProxyProtocol-policy
$ aws elb set-load-balancer-policies-for-backend-server --load-balancer-name my-elb --instance-port 8080 --policy-names myorg-ProxyProtocol-policy
```
- Register few agents with Rancher
- Install kubernetes stack
- Deploy few pods and services
- Test kubectl exec and logs from remote kubectl client

Both kubectl exec and logs work from remote client.

**Comment by TylerRick** [comment]
Thanks, @galal-hussein. Just to clarify, this issue was for the non-HA setup. (#7425 was the one for HA)

We tried upgrading and setting up ELB as described and it did seem to resolve the "Upgrade request required" error but `kubectl exec` still doesn't work for us (it just hangs).

**Comment by maradwan** [comment]
I solved the issue, see my article 
https://dev.to/aws-builders/kubectl-execport-forward-with-aws-alb-and-nginx-ingress-controller-4fn0

**Comment by ajaydevtron** [comment]
@maradwan , We can do natively with ALB only without introducing nginx controller?
