### ISSUE TITLE
fail to upgrade service in stack during docker registry wait-period

### ISSUE THREAD

**Issue by cmosetick** [rancher/rancher#7471]
**Rancher Versions:**
Server: 1.1.4
healthcheck: 0.1.0
network-manager: 0.2.17
scheduler: 0.4.0
agent: 1.1.2

**Docker Version:**
1.13.0

**OS and where are the hosts located? (cloud, bare metal, etc):**
AWS EC2, Ubuntu 16.04

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node Rancher Server, DB in docker volume.

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Push image to hub.docker.com, try to deploy image from Rancher Server after `index.docker.io` manifest has been updated, but before image is actually able to be `docker pull`ed.

**Results:** 
Rancher Server stack goes into infinite loop trying to pull the image. Any attempts in Rancher Server GUI to cancel the upgrade does not succeed. It appears based on the below log message that the docker engine itself fails to pull the image:tag, and Rancher Server does not acknowledge this failure, and instead hangs indefinitely.

`Jan 18 23:37:26 ip-192-168-0-61 dockerd[7868]: time="2017-01-18T23:37:26.750275532Z" level=error msg="Handler for GET /v1.22/images/index.docker.io/user/repo-name:tag-name/json returned error: No such image: index.docker.io/user/repo-name:tag-name"`

This could be because of a wait period in the docker hub CDN, or similar. I suspect that the meta-data was present for the tag, but the image was still "unavailable".

Note: This Rancher Server behavior does not occur when the a tag does simply not exist at all.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
