### ISSUE TITLE
Pods stuck in "pending" and kubectl get nodes said: "no resources found"

### ISSUE THREAD

**Issue by responsable1989** [rancher/rancher#7472]
**Rancher Versions:**
v1.3.1
**Docker Version:**
1.12.5
**OS and where are the hosts located? (cloud, bare metal, etc):**
SUSE Linux Enterprise Server 12 SP2
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node Rancher 
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes 1.5.1
**Steps to Reproduce:**
Set up rancher v1.3.1 with proxy env's -> Set up New Environment Kubernetes 1.51. After the complete infrastructure stack is active create any stack from the catalog e.g. K8s Example Guestbook. 

**Results:** 
The pods will never start and 'kubectl get nodes' says "no resources found" but the confusing part is, that the whole infrastructure stack stays green (active).

![unbenannt](https://cloud.githubusercontent.com/assets/25218356/22097528/d9b84a4a-de21-11e6-92ca-1c55666e6e4e.PNG)

![unbenannt1](https://cloud.githubusercontent.com/assets/25218356/22097569/09c67d7e-de22-11e6-8d30-3e2c9c7bfea2.PNG)

**Comment by jianxintan** [comment]
I have rancher/enterprise and Docker v1.12.5 and see exactly the same issue.

**Comment by bweston92** [comment]
Any update?

**Comment by aemneina** [comment]
What do you have for your nodes host name(s)?

**Comment by mafzst** [comment]
Up! Any news ?

**Comment by aemneina** [comment]
if this is reproducible on the latest version of rancher/k8s (1.5.9+) please let us know.
