### ISSUE TITLE
Rancher v1.3.1 Kubernetes Dashboard not working

### ISSUE THREAD

**Issue by ttinman** [rancher/rancher#7473]
Hi,

I try to install Rancher v1.3.1 and enable Kubernetes Environment, the install seem OK but when i navigate to Dashboard but result is blank page, i check 2 deployment :kubernetes-dashboard and  tiller-deploy restart every time with log:

Error while initializing connection to Kubernetes apiserver. This most likely means that the cluster is misconfigured (e.g., it has invalid apiserver certificates or service accounts configuration) or the --apiserver-host param points to a server that does not exist. Reason: Get https://10.43.0.1:443/version: dial tcp 10.43.0.1:443: i/o timeout

I dont know why, Please help me

I dont know why kubernetes service for expose 10.43.0.1:443 belong different namespace(default) with others(kube-system)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.3.1` Cattle: `v0.175.6` UI: `v1.3.5` |
|Access|`Disabled`|
|Orchestration|`Kubernetes`|
|Route|`k8s-tab.namespace.pods.index`|

**Comment by jlalouette** [comment]
Same issue here...

**Comment by wzhliang** [comment]
Seeing same thing with rancher 1.5.1 + kubernetes 1.5.2

**Comment by iain17** [comment]
try this: https://gist.github.com/joshwget/ac657afebc6260514adbfb4de76622c1

that worked for me. The only I did differently was: kubectl -n kube-system delete services --all

then restart the whole k8s stack and it'll re-create the services, which should make it all work again 👍

**Comment by aemneina** [comment]
This should be more robust in the latest versions of rancher 1.5.9+. Feel free to create a new issue if the problem is seen there.
