### ISSUE TITLE
Can't bind on 127.0.0.1

### ISSUE THREAD

**Issue by miv** [rancher/rancher#7474]
Using managed network, trying to create port mapping like 127.0.0.1:24004:24004 opens port on 0.0.0.0 

Using host network - port fails to open on both 127.0.0.1 and any other ip.

Use case: I want to create a proxy for logs from docker containers. But because log driver from docker runs on daemon it knows nothing about managed network. I want to create a proxy, running on localhost, that other containers can write to. This proxy will aggregate logs and ship them to other facilities accessible via internal network/internal dns/etc.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.2.2` Cattle: `v0.174.13` UI: `v1.2.40` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`stack.index`|

**Comment by leodotcloud** [comment]
I have created a test cluster with three hosts. Deployed Wordpress catalog item and picked 10001 port to expose the service.

**Summary:** Exposed ports are working as expected.


**Here are the detailed test results:**

### Environment Information:

#### Cattle: 1.2.2

#### OS:
```
root@aa-leo-h2:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
root@aa-leo-h2:~#
```

#### Cluster Screenshot:
![screen shot 2017-01-19 at 11 44 23 am](https://cloud.githubusercontent.com/assets/19392926/22126357/a7bedbc0-de54-11e6-81d1-efa638bfe9ef.png)

#### Stack Screenshot:
![screen shot 2017-01-19 at 11 45 09 am](https://cloud.githubusercontent.com/assets/19392926/22126411/c975c440-de54-11e6-9cd1-2eef707fd44b.png)

#### Running Wordpress Screenshot:
![screen shot 2017-01-19 at 11 45 18 am](https://cloud.githubusercontent.com/assets/19392926/22126432/da89559e-de54-11e6-9b3c-2b83bbdaba32.png)

**Relevant iptables rules programmed correctly on the host:**
```
root@aa-leo-h2:~# iptables-save | grep 10001
-A CATTLE_OUTPUT -p tcp -m tcp --dport 10001 -m addrtype --dst-type LOCAL -j DNAT --to-destination 10.42.84.168:80
-A CATTLE_PREROUTING ! -i docker0 -p tcp -m tcp --dport 10001 -j MARK --set-xmark 0x1068/0xffffffff
-A CATTLE_PREROUTING ! -i docker0 -p tcp -m tcp --dport 10001 -j DNAT --to-destination 10.42.84.168:80
-A CATTLE_PREROUTING -p tcp -m tcp --dport 10001 -m addrtype --dst-type LOCAL -j DNAT --to-destination 10.42.84.168:80
root@aa-leo-h2:~#
```


### Running tests from the host:
I am running different type of tests to access the exposed port from the command line of the host.

#### Using 127.0.0.1:10001
![screen shot 2017-01-19 at 11 59 46 am](https://cloud.githubusercontent.com/assets/19392926/22126496/1e8d1708-de55-11e6-8167-7d9fb9906ba9.png)

#### Using localhost:10001
![screen shot 2017-01-19 at 12 00 24 pm](https://cloud.githubusercontent.com/assets/19392926/22126520/3899eaf4-de55-11e6-9d86-f944f8783dce.png)


#### Using the host IP address
![screen shot 2017-01-19 at 12 03 44 pm](https://cloud.githubusercontent.com/assets/19392926/22126536/49f96068-de55-11e6-8fae-4180d718215f.png)

### Running tests from the Containers:
![screen shot 2017-01-19 at 12 05 49 pm](https://cloud.githubusercontent.com/assets/19392926/22126586/761eb468-de55-11e6-847e-59c9a1ef12a6.png)

#### Checking the port from the other container (DB) of the service
![screen shot 2017-01-19 at 2 28 51 pm](https://cloud.githubusercontent.com/assets/19392926/22126615/94bb4d96-de55-11e6-9bc1-693e891baca0.png)

![screen shot 2017-01-19 at 2 29 33 pm](https://cloud.githubusercontent.com/assets/19392926/22126621/9bbc6904-de55-11e6-9732-c8302e88c3c1.png)


#### Checking from the same container using the host IP address

![screen shot 2017-01-19 at 2 25 30 pm](https://cloud.githubusercontent.com/assets/19392926/22126643/bc41725a-de55-11e6-814a-2e028ca1f16b.png)

#### Checking from the same container using the localhost/127.0.0.1
This is a weird behavior by the container that there is no output! I tested the same with a nginx container, when I use either localhost/127.0.0.1, I can see the nginx default page. So this behavior seems specific to this wordpress container.
 
![screen shot 2017-01-19 at 2 26 25 pm](https://cloud.githubusercontent.com/assets/19392926/22126664/d7d290c6-de55-11e6-88bc-9ca27ffae5a1.png)

#### Checking from the same container using the localhost/127.0.0.1 using telnet
![screen shot 2017-01-19 at 2 26 52 pm](https://cloud.githubusercontent.com/assets/19392926/22126713/0e7aa10e-de56-11e6-8b90-eebaa3565002.png)

#### Checking from the same container using the host IP address using telnet
![screen shot 2017-01-19 at 2 27 21 pm](https://cloud.githubusercontent.com/assets/19392926/22126727/1f468fac-de56-11e6-8662-30e76e7b93ff.png)

**Comment by miv** [comment]
@leodotcloud Thank you for investigation. But i do not see port mapping rule. 

Container should be bound **ONLY** on 127.0.0.1, not accessible from other hosts. Take for example this service:

```
version: '2'
services:
  nginx-test:
    image: nginx
    stdin_open: true
    tty: true
    ports:
    - 127.0.0.1:3000:80/tcp
    labels:
      io.rancher.container.pull_image: always
```

It should bind on 127.0.0.1 and only on 127.0.0.1, instead it is bound to 0.0.0.0

Accessing from other hosts (via public ip, on eth0):

```
➜  projects  curl "http://gen1:3000"
<!DOCTYPE html>
<html>
...
```

Same host:

```
~$ curl "http://127.0.0.1:3000"
<!DOCTYPE html>
<html>
...
```

And here is ip tables rules:


```
-A OUTPUT -p tcp -m tcp --dport 3000 -m addrtype --dst-type LOCAL -j DNAT --to-destination 10.42.24.230:80
-A CATTLE_PREROUTING -d 127.0.0.1/32 ! -i docker0 -p tcp -m tcp --dport 3000 -j MARK --set-xmark 0x1068/0xffffffff
-A CATTLE_PREROUTING -d 127.0.0.1/32 ! -i docker0 -p tcp -m tcp --dport 3000 -j DNAT --to-destination 10.42.24.230:80
-A CATTLE_PREROUTING -p tcp -m tcp --dport 3000 -m addrtype --dst-type LOCAL -j DNAT --to-destination 10.42.24.230:80
```

It is actually not accessible from managed network's other hosts:

```
➜  ~  curl "http://nginx-test.default.rancher.internal:3000"
curl: (7) Failed to connect to nginx-test.default.rancher.internal port 3000: Connection refused
```



For contrary example take plain docker port mapping:

Running nginx like so: `docker run -it --rm -p 127.0.0.1:3000:80 nginx`

```
➜  projects  docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                             NAMES
fb821f5e1017        nginx               "nginx -g 'daemon off"   27 seconds ago      Up 26 seconds       443/tcp, 127.0.0.1:3000->80/tcp   sleepy_montalcini
```

It is not available from other hosts:

```
➜  projects  curl "http://$(docker-machine ip):3000"
curl: (7) Failed to connect to 192.168.99.100 port 3000: Connection refused
```

But it is available from within a host itself:

```
➜  projects  docker-machine ssh
                        ##         .
                  ## ## ##        ==
               ## ## ## ## ##    ===
           /"""""""""""""""""\___/ ===
      ~~~ {~~ ~~~~ ~~~ ~~~~ ~~~ ~ /  ===- ~~~
           \______ o           __/
             \    \         __/
              \____\_______/
 _                 _   ____     _            _
| |__   ___   ___ | |_|___ \ __| | ___   ___| | _____ _ __
| '_ \ / _ \ / _ \| __| __) / _` |/ _ \ / __| |/ / _ \ '__|
| |_) | (_) | (_) | |_ / __/ (_| | (_) | (__|   <  __/ |
|_.__/ \___/ \___/ \__|_____\__,_|\___/ \___|_|\_\___|_|
Boot2Docker version 1.12.3, build HEAD : 7fc7575 - Thu Oct 27 17:23:17 UTC 2016
Docker version 1.12.3, build 6b644ec
docker@default:~$ curl "http://127.0.0.1:3000"
<!DOCTYPE html>
<html>
<head>
```

**Comment by nicolinux** [comment]
Is there an update on this issue? With Rancher 1.6.1 the problem still persists. Rancher ignores the "Public Host IP (Optional)" field when mapping ports via the UI.

**Comment by MihaiAnei** [comment]
Any updates guys? Binding on localhost (127.0.0.1) should be a simple feature since 0.0.0.0 is working by default. There are a lot of reasons here (security for example) and maybe the feature can be extended to binding on a specific IP on a host with multiple LANs to cover all of the use cases. Cheers!

**Comment by zot24** [comment]
I'm experiencing a similar issue where I got the following configuration (that was working on Rancher 1.2.2)

```
version: 2
services:
  fluentd:
    image: localhost/fluentd
    env_file: .env
    ports:
      - "127.0.0.1:24224:24224"
```

But with Rancher Server 1.6.7 I just get the following error

```
 Upgrading (Failed to allocate instance [container:1i126]: Bad instance [container:1i126] in state [error]: Allocation failed: No healthy hosts meet the resource constraints: [127.0.0.1:24224:24224/tcp portReservation, instanceReservation: 1])
Type:
```

**Comment by MihaiAnei** [comment]
@zot24 I found a workaround to that by adding in the edit page of the host the ip: 127.0.0.1. I really don't know if this is the expected behavior but it works for me now.

![selection_002](https://user-images.githubusercontent.com/6485811/29607065-bc3fe528-87f8-11e7-93db-63314f6f051e.png)

**Comment by teknologist** [comment]
@MihaiAnei  This solved it for me and should be as a default or available in the docs.
IMHO in a public cloud environment you'd bind containers ports to localhost and then expose them through some sort of secured proxy.

I wonder how many rancher installs are setup with all ports directly available to the world...

**Comment by th0th** [comment]
Any updates on this? Issue seems to be still existing on 1.16.10. We are running a service that needs to proxied on the host but this exposes the service to the internet.

**Comment by dankeder** [comment]
I run into this issue - rancher binding containers to 0.0.0.0 by default and no obvious way to bind them to localhost or a private IP. I "solved" it using the same workaround as @MihaiAnei.

I think it's even the proper way of doing it -- the "Host IP" field in the service upgrade dialog doesn't make sense. When creating or upgrading the service it's not known where its containers will run - that's the scheduler's job to decide later. The "Host IP" field probably doesn't work for this reason.

**Comment by fabn** [comment]
Found this after researching and cannot apply @MihaiAnei solution in rancher 1.6.13.

Also I found out that rancher ui is exposed on 8080 as well, no matter what I configure in ufw (using ubuntu).

In my setup I'd like to bind services on localhost and expose what I want using a haproxy instance serving all resources through https, because of this issue I'm not able to achieve that.

Any other workaround?

Imho it's fundamental to allow 127.0.0.1 binding and it should be the default option in some cases.

**Comment by vincent99** [comment]
The server container (which serves the UI, which is just static html/js/css files) is published wherever you set it to, with vanilla docker directly in the `docker run ... -p 8080:8080 rancher/server` command.  It is not managed _by_ Rancher at all, because it _is_ Rancher.

Containers inside the managed network can all talk to each other without publishing any ports.  The "normal" Rancher Way™ of doing this is to have all your containers publish nothing, and then have one load balancer/nginx/whatever that publishes a host port and routes requests to target service containers.

**Comment by fabn** [comment]
> The server container (which serves the UI, which is just static html/js/css files) is published wherever you set it to, with vanilla docker directly in the docker run ... -p 8080:8080 rancher/server command. It is not managed by Rancher at all, because it is Rancher.

Yes, you're right about that. My mistake.

> Containers inside the managed network can all talk to each other without publishing any ports. The "normal" Rancher Way™ of doing this is to have all your containers publish nothing, and then have one load balancer/nginx/whatever that publishes a host port and routes requests to target service containers.

Yes, but in my case I want that the service that I'm exposing is accessible for a process running in the host and not the whole world. Also I'm using ufw in the host machine, but since `CATTLE_PREROUTING` chain comes before UFW rules they are ineffective and all exposed ports are visible in the outside word.

In my case I'm doing SSL termination in a process running outside docker and in this way http services provided by my rancher stacks are exposed without HTTPS.

**Comment by kivervinicius** [comment]
@MihaiAnei where is this option, I do not find ... use version 1.6.14

**Comment by janeczku** [comment]
@fabn do you still experience this issue on v1.6.13?

It seems to work as expected here.

1. Create stack via docker-compose:
```
version: 2
services:
  web:
    image: nginx
    ports:
      - "127.0.0.1:80:80"
```
2. Rancher maps container port to localhost:
![screen shot 2018-02-01 at 14 59 57](https://user-images.githubusercontent.com/3813921/35682404-e8f0e152-0760-11e8-96a7-297d4694918e.png)


3. Port is not accessible on the host public IP:
```Shell
 ~$ nc -z -v 52.15.xxx.xxx 80
nc: connectx to 52.15.xxx.xxx port 80 (tcp) failed: Connection refused
```

**Comment by fabn** [comment]
Tried your compose file on 1.6.13 with a different port because 80 is already bound in my host

![image](https://user-images.githubusercontent.com/324213/35738020-d23fd53a-082d-11e8-9eb5-4690ed78ed0a.png)

Unfortunately the result is this:

![image](https://user-images.githubusercontent.com/324213/35738045-e8175aa4-082d-11e8-808b-edf00df8da4f.png)

i.e. service cannot be started with these logs

![image](https://user-images.githubusercontent.com/324213/35738088-0c729832-082e-11e8-91f1-b48776fa5664.png)

Maybe I'm doing something wrong

**Comment by nb-git** [comment]
So is there anything new about this issue? I have the same problem at the moment. This makes using a reverse proxy some kind of useless for me.

**Comment by nb-git** [comment]
So i found a workaround for Rancher 1.6.15 you can expose ports to 127.0.0.1 when you set a specific host under the scheduling tab. So i guess this will be useless for multihost setups.

**Comment by stonecold123** [comment]
I have the same problem as @fabn with docker-compose.yml

**Comment by stonecold123** [comment]
@nb-git @MihaiAnei 
I've followed your suggestion. But there's a problem. 
If I add a load balancer via the UI, it'll open on 127.0.0.1 instead of the host IP.
I have to add the host ip as well in the scheduling tab to avoid that problem. Any one got the same issue?

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
