### ISSUE TITLE
[UI] Protocol field on load balancer service not correct size

### ISSUE THREAD

**Issue by jannyg** [rancher/rancher#7475]
**Rancher Versions:**
Server: 1.3.1
healthcheck: N/A
ipsec: N/A
network-services: N/A
scheduler: N/A
kubernetes (if applicable): N/A

**Docker Version:**

N/A

**OS and where are the hosts located? (cloud, bare metal, etc):**

N/A

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

N/A

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

Cattle

**Steps to Reproduce:**

Reporting this small issue/UI glitch on behalf of a Windows user and i'm able to reproduce the issue in a VM:

Click "Upgrade" on the "Load balancer" service and click "Add Service Rule". Select "HTTPS" in the dropdown menu and notice that the field not contains all of the text.

This is shown correctly in OS X with Chrome/Firefox but with Windows with Firefox/Chrome it dosen't have room for all the text (see screenshot below).

OS: Windows 7 and 10
Chrome: 55.0.2883.87 m
Firefox: 50.0.2

**Results:** 

The dropdown field does not show HTTPS entirely and can make it possible to mix HTTP and HTTPS if not paying closely attention. This might also be the case with other fields in Rancher when running Windows.
![screen shot 2017-01-19 at 16 14 05](https://cloud.githubusercontent.com/assets/387004/22112207/685a6176-de62-11e6-9f42-e97867e80336.png)

**Comment by tfiduccia** [comment]
Version - master 1/19
Yes this is indeed a problem in Windows, but also Firefox on Mac.

**Comment by jannyg** [comment]
Thanks for confirming. I only tested with Safari and Chrome on OS X.

**Comment by lonix** [comment]
Also applys to Other parts of the ui, like the host scheduler.

**Comment by vincent99** [comment]
These were widened at some point..
