### ISSUE TITLE
Docker stable label for rancher/lb-service-haproxy should match the version gui wants

### ISSUE THREAD

**Issue by sra** [rancher/rancher#7476]
**Rancher Versions:**
Server: 1.3.1
healthcheck: 0.2.0
ipsec:
network-services: 0.4.0
scheduler: 0.5.1
kubernetes (if applicable): no

**Docker Version:**
1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):**

AWS RancherOS 0.7.1

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

Single rancher server with RDS database

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

Cattle

Currently, the rancher/lb-service-haproxy:latest is set lower than v0.4.9. This seems wrong. We should either use :stable (missing tag) which should track whatever version the GUI keeps requesting the stack be updated to, or at least :latest. Otherwise we keep having to check the GUI to see what version it wants and then update all the deployment definitions.

**Comment by sra** [comment]
Also, release notes would be spiffy - I checked the lb project and there are no releases there so I'm not sure where to look to see what is going to change.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
