### ISSUE TITLE
For --net=host, rancher.internal added at end of search path instead of beginning

### ISSUE THREAD

**Issue by vincent99** [rancher/rancher#7480]
A container with `--net=host` and `io.rancher.container.dns=true` gets the Rancher search domains added to the end of the search path instead of the beginning, regardless of `io.rancher.container.dns.priority`.

**Comment by leodotcloud** [comment]
Fix will be available in `rancher/network-manager:v0.4.8`

**Comment by sangeethah** [comment]
Tested with Rancher server build from master and rancher/network-manager:v0.4.8

Managed Network services with io.rancher.container.dns.priority=service_last	

1. Have  search domains set on hosts where containers get deployed	
    Service containers  have  domains from host are listed in the beginning ( in /etc/resolv.conf Search)
2. Have search domains  set when adding service .
    Search domains from host are not listed. 
   Service containers  have  Search domains provided in the service is listed in the beginning  ( in /etc/resolv.conf Search)

Managed Network services with label io.rancher.container.dns.priority not set 
1. Have  search domains set on hosts where containers get depplyed	
    Search domains from host are listed at the end  ( in /etc/resolv.conf Search)
2. Have search domains set when adding service .
    Search domains from host are not listed. Search domains provided in the service is listed in the begining  ( in /etc/resolv.conf Search)

services in Host Network with io.rancher.container.dns.priority=service_last	

1. Have  search domains set on hosts where containers get deployed	.
     Service containers  have  Search domains from host are listed in the beginning ( in /etc/resolv.conf Search)
2. Have search domains  set when adding service.
   Search domains from host are not listed. 
   Service containers  have Search domains provided in the service is listed in the beginning  ( in /etc/resolv.conf Search)

services in Host Network with io.rancher.container.dns.priority label not set.

1. Have  search domains set on hosts where containers get deployed	
     Service containers  have Search domains from host are listed at the end  ( in /etc/resolv.conf Search)
2. Have search domains set when adding service 
   Search domains from host are not listed. 
    Service containers  have Search domains provided in the service is listed in the beginning  ( in /etc/resolv.conf Search)

**Comment by vincent99** [comment]
Host's search | Service's search | => | With `service_last` | With label not set
--------------|------------------|----|--------------------|---
`<empty>`     | `<empty>`          | => | `Svc`                       | `Svc`
`<empty>`     | `A`                       | => | `A` `Svc`                | `Svc` `A`
`B`                  | `<empty>`          | => | `B` `Svc`                | `Svc` `B`
`C`                  | `D`                      | => | `D` `Svc` ("C" is ignored)               | `Svc` `D` ("C" is ignored)

`Svc` == `<stack>.rancher.internal`, `<service>.<stack>.rancher.internal`, `rancher.internal`

Note that the `Host's search` comes from the `/etc/resolv.conf` of the agent container, which is not changed when you change the file on the host.  So if you change the host you must restart the agent container for it to take effect.

**Comment by sangeethah** [comment]
@vincent99, when dns is set at service level , they are always included in the beginning of the list irrespective of  whether this label is set or not -  io.rancher.container.dns.priority=service_last.

**Comment by vincent99** [comment]
@sangeethah Apparently that's intended because the user is setting an explicit search path.  So this is correct for now.  Eventually we should probably have a `service_first` option to enable the opposite.  Updated above.
