### ISSUE TITLE
Kubernetes stuck at 6 / 10 because etcd container won't start

### ISSUE THREAD

**Issue by dchambers** [rancher/rancher#7481]
**Rancher Versions:**
Server: `1.3.0`
healthcheck: `0.2.0`
ipsec:
network-services:
scheduler:
kubernetes (if applicable):
The offending container is `rancher/etcd:v2.3.7-11`

**Docker Version:**
`1.12.5`

**OS and where are the hosts located? (cloud, bare metal, etc):**
AWS EC2 instance add as 'Custom' host.

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Not sure?

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes.

**Steps to Reproduce:**
Start a Kubernetes environment (on a single node?). I tried stopping all previously running docker containers on the host before adding it again, and it still happens.

**Results:** 
The environment is stuck at 6 / 10, and if I click through I can see this error message for the etcd container:

```
etcd + 1 Sidekick (Failed to allocate instance [container:1i838]: Bad instance [container:1i838] in state [error]: Scheduling failed: host must not have a container with label io.rancher.stack_service.name=kubernetes/etcd) 
```

The `host must not have a container with label io.rancher.stack_service.name=kubernetes/etcd` part seems like an odd error, but I can't figure out what it's getting at!

This was working until we upgraded to Rancher 1.3.0 (from 1.1.x I believe).

Is there anything I can do to help diagnose this further?

**Comment by galal-hussein** [comment]
@dchambers I couldn't reproduce the problem, one possible cause of this problem is having another container on the host that has the same label `io.rancher.stack_service.name=kubernetes/etcd`, make sure to remove this container and check again.

**Comment by dchambers** [comment]
That worked!

Whereas I previously only stopped all running containers (using ``sudo docker stop `sudo docker ps -q` ``), this time I also deleted all containers off of the machine too (via ``sudo docker rm `sudo docker ps -qa` ``), in addition to deleting and recreating both the _host_ and the _environment_ using the UI.

Thanks so much for the timely help 👍
