### ISSUE TITLE
Instances are not purged immediately, which do not release host ports during scheduling

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#7484]
After deleting instances that use a port, if you re-create and the new instance needs to use the same port, a scheduling error will occur as  the port will not be released.

**Comment by soumyalj** [comment]
The issue happens when you delete an instance of a service with ports exposed.
<img width="1376" alt="screen shot 2017-01-27 at 1 29 17 pm" src="https://cloud.githubusercontent.com/assets/18536626/22388224/5a55cfba-e494-11e6-8112-7f7a2cbfbfb2.png">

**Comment by cjellick** [comment]
We are addressing by deallocating ports on instance.stop, not instance.purge

**Comment by deniseschannon** [comment]
@sangeethah Can we test that we could delete an instance (not purge) and try to deploy a new instance using the same port so that there is no scheduling conflict?

**Comment by soumyalj** [comment]
Tested with v1.4.0-rc7. Created instance with exposed port. Deleted the instance and created another one with the same port. Container got created with no conflicts.
