### ISSUE TITLE
Show warnings for unsupported Docker versions

### ISSUE THREAD

**Issue by vincent99** [rancher/rancher#7485]
Controlled by `supported.docker.range` and `newest.docker.version` settings (which are viewable in advanced settings in the UI now...)

![image](https://cloud.githubusercontent.com/assets/753917/22137746/1a7d7046-de9a-11e6-86e7-27f43379903d.png)

**Comment by SamMousa** [comment]
The warnings seem to work just fine. What I'm missing though is an explanation in the documentation.
When clicking on the warnings you get a list of supported versions, but it is unclear what the consequences are.

Does rancher do anything differently for unsupported versions or can I continue to use them as normal if I want to take a chance?

**Comment by aemneina** [comment]
@SamMousa you should be able to use them... theyre usually not as well tested as 'supported' versions. Rancher wont go out of its way to hinder functionality of untested or unsupported docker versions.

**Comment by deniseschannon** [comment]
@SamMousa For k8s, only specific versions will work as k8s itself doesn't support some of the later Docker version (v1.13+)

**Comment by tfiduccia** [comment]
Version - master 5/17
Verified fixed - the warning work and @SamMousa here is the link for documentation
http://docs.rancher.com/rancher/v1.6/en/hosts/#supported-docker-versions
