### ISSUE TITLE
pulll catalog?

### ISSUE THREAD

**Issue by joshuacox** [rancher/rancher#7486]
I've been experimenting with creating catalogs and I was wondering if it might be a good idea to have a pull catalog button?   Most of the time I can just hit reload, and the new changes come in, but many times I'll hit reload a couple of times and it refuses to trigger, and I'll go in settings remove my catalog and hit save, and then re-add the catalog.  It might be nice to have a rebuild catalog button, or an api call that I curl in?

**Comment by tfiduccia** [comment]
@joshuacox - After thinking about it, if you click on the reload and it doesn't update with the changes you made, then that is a bug.  Next time can you make a note of what didn't update properly and add it to this issue.  If you can give me an example I can reproduce, then I might be able to get a dev to fix it :).

**Comment by joshuacox** [comment]
Something to note is that I am incrementing the `version` everytime now.  Another behavior I've adopted is hitting a hard reload on the catalog page and not the catalog item itself.   Most of the time this works, but every now and then I do have to "go in settings remove my catalog and hit save, and then re-add the catalog" as above.  I have waited a few times (gone to bed, and wait for morning), and it will still be on the old version and I'll have to do the above procedure to 'kick' it.  But for the most part it is working as intended, and I consider this an edge case.  I'm going to close as my workaround does indeed force it to update, feel free to reopen.

**Comment by joshuacox** [comment]
this is still a major issue.  I was going through some of the behaviour I go through to comply with Rancher not wanting to pull my catalogs and @jamessmoore was astounded at how many times you must reload a page before a catalog will update.

**Comment by joshuacox** [comment]
there needs to be a "pull catalogs" button somewhere for catalog developing sanity

**Comment by joshuacox** [comment]
I have also notice that this sentence "Alternatively, you could update the templates in the 0 folder and just re-deploy the entry." on this [page](http://rancher.com/docs/rancher/v1.6/en/catalog/private-catalog/) is not true.  For example,

create a template
deploy in rancher
edit yml files in place inside 0
git commit and push
redeploy
changes are almost never carried over unless I reload `stacks/user` an insane amount of times (insane because I have no clue what this number is, sometimes once, sometimes 500 times and still will not update)

**Comment by vincent99** [comment]
You're missing wait ≥ 5 min for polling or click refresh part...

![image](https://user-images.githubusercontent.com/753917/28095289-84bd3d6c-6656-11e7-99bc-bda7973bb68f.png)

**Comment by joshuacox** [comment]
'click refresh'  thank you for the pic!  I would've assumed you were talking about ctrl-shift-R or similar.  Hopefully that eliminates my issues.
