### ISSUE TITLE
"Add a Host" link has the wrong URI shortly after environment creation

### ISSUE THREAD

**Issue by sdlevi27** [rancher/rancher#7488]
**Rancher Versions:**
Server: 1.3.1
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker Version:**
1.1.12

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 14.04, private cloud

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA Rancher, external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
1) Create new Environment
2) Immediately click on the environment name
3) Click "Add a Host"

**Results:** 
The link in "Add a host" contains an "undefined" environment, ie:
https://server/env/undefined/infra/hosts/add

Wait about 10 seconds for the environment to get an envid, go back into the Environments tab, click "Add a Host" and the link will have the correct environment ID

**Comment by tfiduccia** [comment]
@sdlevi27 - this has been fixed and will be in the next release.  Verified in master, so I'm going close it and after our next release if you still see the issue, reopen and let me know.
