### ISSUE TITLE
vSphere Docker Volumes under Rancher

### ISSUE THREAD

**Issue by tsvtitan** [rancher/rancher#7494]
Rancher Versions
Server: 1.2.1
healthcheck: 0.2.0
ipsec: 0.8.1
network-services: meta 0.7.0 / manager 0.4.0
scheduler: 0.5.1

Docker Version: 1.12.5
OS and where are the hosts located? (cloud, bare metal, etc): Ubuntu 16.04 / vSphere
Setup Details: HA rancher / external DB
Environment Type: Cattle

We have 2 storages named as storage1 & storage2 under ESXi. 
First VM (lies under storage1), Second VM (lies under storage2).
Each host has docker volume: https://github.com/vmware/docker-volume-vsphere

Steps:

1.First VM: docker create volume --drive r=vmdk --name=TestVolume1 -o size=10gb

2.Second VM: docker create volume --drive r=vmdk --name=TestVolume2 -o size=10gb

3.First VM: docker volume ls
vmdk                TestVolume1
vmdk                TestVolume2@storage2

4.Second VM: docker volume ls
vmdk                TestVolume1@storage1
vmdk                TestVolume2

5. Trying to upgrade service that lies under Second VM and should use TestVolume1@storage1 leads to:

![screenshot_2017-01-20_22-14-41](https://cloud.githubusercontent.com/assets/10025555/22162033/e32248e6-df5d-11e6-9660-81c03588d92f.png)

If it uses TestVolume2 without @storage.. it works.

It would be perfect to extend Rancher for this kind of volumes (https://github.com/vmware/docker-volume-vsphere) by avoiding checks @ sign

**Comment by vincent99** [comment]
How do you actually use this in native docker?  We added this validation in the UI because docker checks those specific rule, and `@` is not a valid character for a volume name.

```
$ docker run -it -v foo@bar:/blah ubuntu
docker: Error response from daemon: create foo@bar: "foo@bar" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intented to pass a host directory, use absolute path.
```

**Comment by msterin** [comment]
@vincent99  - Name validation is driver-specific, and the the limitations mentioned above apply to local volume driver names only.

```shell
root@photon-1 [ ~ ]# docker volume create -d vmdk --name=myVol@vsanDatastore -o size=10gb
myVol@vsanDatastore
root@photon-1 [ ~ ]# docker volume ls 
DRIVER              VOLUME NAME
vmdk                myVol@vsanDatastore
vmdk                ty1
root@photon-1 [ ~ ]# docker volume inspect  myVol@vsanDatastore
[
    {
        "Name": "myVol@vsanDatastore",
        "Driver": "vmdk",
        "Mountpoint": "/mnt/vmdk/myVol@vsanDatastore",
        "Status": {
            "access": "read-write",
            "attach-as": "independent_persistent",
            "capacity": {
                "allocated": "192MB",
                "size": "10GB"
            },
            "created": "Thu Oct 20 13:32:56 2016",
            "created by VM": "photon-1",
            "datastore": "vsanDatastore",
            "diskformat": "thin",
            "fstype": "ext4",
            "status": "detached"
        },
        "Labels": {},
        "Scope": "global"
    }
]

root@photon-1 [ ~ ]# docker run --rm -v myVol@vsanDatastore:/vsan busybox touch /vsan/YesItDoes
root@photon-1 [ ~ ]# docker run --rm -v myVol@vsanDatastore:/vsan busybox ls -k /vsan          
YesItDoes
lost+found
```

**Comment by tsvtitan** [comment]
Guys, any news on this issue?

**Comment by pdhamdhere** [comment]
@tsvtitan Do you want to discuss alternatives in absence of fix from Rancher? Please reach out to us @ containers@vmware.com

**Comment by ibuildthecloud** [comment]
@tsvtitan I believe we can relax the name validation logic.  From what you've see is really just the `@` that is causing a problem?

**Comment by msterin** [comment]
@ibuildthecloud @tsvtitan  FWIW a volume plugin may introduce it's own name validation logic, Docker does not care.
What you have in the current product is really local driver names validation, which is already correct. 
Would it make sense to keep the current logic for local volumes, and drop validation for other volumes and just bubble up failures if any, which I suspect you have to do anyways ?

**Comment by vincent99** [comment]
Bubbling up failures from the daemon after a service has been created and containers attempted to be created for it is far too late to be useful to the user, which is why this particular validation message is from the UI.

**Comment by ibuildthecloud** [comment]
@msterin The problem is there still has to be some validation, /, \, or : will cause issues.  The volume mount string is incredibly complex (when you consider windows) so I don't really want to relax all validation.  We need to figure out exactly what is required.  Until we find that out, adding @ is simple enough.

**Comment by msterin** [comment]
Fair enough. With enabling '@'  the problem will be gone, and limiting the choice for volume names (compared to what a plugin alllows) is most likely not a problem. At least for vSphere plugin :)

**Comment by tsvtitan** [comment]
Adding  @ is enough to resolve the issue

**Comment by vincent99** [comment]
Added in 1.5.2.
