### ISSUE TITLE
OpenLDAP: Expose existing ldap config attributes in UI 

### ISSUE THREAD

**Issue by prachidamle** [rancher/rancher#7495]
**Rancher Versions:**
Server: 1.3.x

**Steps to Reproduce:**
1. Setup Rancher and go to Admin ->Access Control
2. Choose OpenLDAP
3. The config page should provide a way to configure following 2 ldapconfig fields:
'groupMemberMappingAttribute'
'userMemberAttribute'

4. Currently the POST request to set the config, uses default values for these two:
Request URL:/v2-beta/openldapconfig
Request Method:POST
Request Payload:
{"id":null,"type":"openldapconfig","baseType":"openldapconfig","accessMode":"unrestricted","connectionTimeout":1000,"domain":"dc=us-west-2,dc=compute,dc=internal","enabled":false,"groupDNField":"entryDN",**"groupMemberMappingAttribute":"memberUid"**,"groupMemberUserAttribute":"entryDN","groupNameField":"cn","groupObjectClass":"groupofNames","groupSearchField":"cn","loginDomain":null,"name":"openldapconfig","port":389,"server":"52.41.23.7","serviceAccountPassword":"cattle","serviceAccountUsername":"cn=admin,dc=us-west-2,dc=compute,dc=internal","tls":false,"userDisabledBitMask":0,"userEnabledAttribute":null,"userLoginField":"uid",**"userMemberAttribute":"memberOf"**,"userNameField":"givenName","userObjectClass":"inetOrgPerson","userSearchField":"uid"}

**Results:** 
Please expose them in UI so that they can be configured easily since every ldap setup can have custom values.

**Comment by tfiduccia** [comment]
Version - master 1/24
Verified fixed
