### ISSUE TITLE
Restart container only so many times.

### ISSUE THREAD

**Issue by nhumrich** [rancher/rancher#7496]
Version of rancher: 1.1.4

Every once in a while someone in my org (usually me) deploys a container thats not actually good. The container fails on startup. When the container dies, rancher tries to start it up again, and before you know it the container is just cycling. It keeps dying -> rancher keeps starting it. 
This is good in the sense that rancher is trying to keep it up. I love that. But its bad when the container is just flat out bad. Usually, this behaviour is noticed right away and its not much of an issue, but everyonce in a while it goes unnoticed. This ends up causing the rancher master and the host to die on my cheap setup because I am running on AWS t2's which have CPU credits. However, even without cpu credits this can be a problem regardless. The point is that CPU load is increased, just trying to cycle this container (mostly on the rancher master instance). As you go to bigger hosts, it just requires more containers at a given time for you to notice the CPU load increase. 
Is there a way to have rancher restart a container only so many times before just giving up completely? If this feature doesnt exist yet, in my mind, the ideal would be if it gave up on a service if the containers fails X times in Y minutes.

Come weird caveats with this issue in regards to adding healthchecks:
1) Enabling healthchecks for the container mostly solves this problem. However I have containers that dont listen to tcp/http on any port at all, so healthchecks are not possible. 
2) When healthchecks ARE enabled, it becomes impossible to upgrade a "bad-state" stopped service if your upgraded state is also bad. This has actually caught me a couple times. I will add a new service, forget an env var, so it goes bad. I stop it, then try to upgrade, only I messed up again on the upgrade. Once you get here, its impossible to do anything except delete the service entirely. This is because it tries to rollback from a unhealthy state, then the rollback causes unhealthiness, so it tries to rollback that, back and forth, never completing a rollback.

**Comment by janeczku** [comment]
@nhumrich In more recent versions the service reconcile applies an exponential backoff when attempting to restart a container. Eventually it will wait for 2 mins between restarts.
With regards to the unrecoverable state when upgrading a bad service with a bad service i was unable to reproduce this on 1.5.x. so this seems to be fixed. Please reopen when you continue to see these issues on the current stable release. Thanks!
