### ISSUE TITLE
[Feature Request] Ability to define multiple categories for a template

### ISSUE THREAD

**Issue by zambon** [rancher/rancher#7497]
Currently in a template's `config.yml`, you can set a single category. For example:

```
category: Database Server
```

It would be very useful, especially in large catalogs, to be able to set multiple categories (as a comma-separated list, array, or equivalent). For example:

```
categories:
  - Database Server
  - Data Warehouse
```

**Comment by sputnik62** [comment]
There has to be a corresponding enhancement in the Catalog UI so that multiple categories can be selected.

**Comment by vincent99** [comment]
@joshwget This should be easy to add for new catalog service..

**Comment by joshwget** [comment]
@vincent99 Should we just change `catalog` and `catalog_ne` to support a list of comma separated strings?

**Comment by vincent99** [comment]
@joshwget Talking about `category` here, not `catalog`?

The field in the API should change to be an array, and `category=foo` should return entries which have an entry which matches (vice versa for `_ne`)

To search for multiple categories I would just send separate filters, `category=foo&category=bar`.  All filters are ANDed together.  If you want to support logical OR instead (which I probably won't use in the UI) you'd need a [new modifier](https://github.com/rancher/api-spec/blob/master/specification.md#schema) like `category_in=foo,bar`.

**Comment by joshwget** [comment]
@vincent99 Yeah sorry, meant `category` and `category_ne`. Thanks!

**Comment by tfiduccia** [comment]
Tried and got error:
""Errors while parsing repo:  [cache/global/55f47aa645f79623cc0d9b00d2dfc4b6/templates/multiple-category-test-1/config.yml: yaml: unmarshal errors:\n  "

**Comment by tfiduccia** [comment]
Version - master 2/23
Verified implemented.  Any bugs will be entered separately, but high level pass shows this is working.
