### ISSUE TITLE
rancher-nfs silently fails to create volume if a local volume of the same name already exists

### ISSUE THREAD

**Issue by patsissons** [rancher/rancher#7502]
**Rancher Versions:**
Server: `1.3.1`
healthcheck: `0.2.0`
ipsec: `0.0.2`
network-services: `0.0.8`
scheduler: `0.3.0`

**Docker Version:**
`1.12.3`

**OS and where are the hosts located? (cloud, bare metal, etc):**
`RancherOS`

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
`Single Node`

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
`Cattle`

**Steps to Reproduce:**
1. Create a local volume (either directly or via a container)
1. Create an nfs volume of the same name
1. Start a container that uses the nfs volume

**Results:** 
* nfs volume is created in rancher but remains in `Inactive` state
* container will actually use the local volume
* nfs storage is not used

The main issue is visibility. It was not very clear why all my nfs volumes were working except one. A left over local volume of the same name was sitting on the host and had not been cleaned up yet. Once I realized the volume name was already taken I removed the old local volume (`docker volume rm ...`) and my nfs volume was then created after restarting the owning container.

**Comment by mleczakm** [comment]
I had same issue, it is really difficult to find a cause, especially when "rancher-compose" ignores "rancher-nfs" during running environment "up" and then we have "locked" state, without possibility to upgrade containers to nfs...

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
