### ISSUE TITLE
Kubernetes API direct access

### ISSUE THREAD

**Issue by Ilya-Kuchaev** [rancher/rancher#7504]
**Rancher Versions:**
Server:
Rancher	v1.3.2
Cattle	v0.175.8
User Interface	v1.3.5
Rancher Compose	v0.12.1
kubernetes (if applicable): k8s:v1.5.1-rancher1-7

How I can access the Kubernetes API directly with the third party software? For example GitLab.
I want to use the Kubernetes / Openshift integration feature there but can't connect to Kubernetes environment:

```
We tried to send a request to the provided URL but an error occurred: HTTP status code 503, 503 Service Unavailable
```
I'm using the Kubernetes service account credentials from the Kubernetes Dasboard.
I thing that GitLab just can't connect to Rancher environment without the credentials but I just can't configure them from GitLab UI.

Thanks!

**Comment by Ilya-Kuchaev** [comment]
Anybody?

**Comment by kelchm** [comment]
I've run into the same issue, but haven't really dug into it too far.

The Kubernetes API appears to be deferring authentication to Rancher, which obviously prevents integrations meant to work with Kubernetes from being able to be used. This is a pretty pressing issue for me over the next week, so I will continue to dig into solutions/workarounds.

**Comment by kelchm** [comment]
Just as a quick followup to this -- If you map the port for the kubernetes service (the one that runs kube-apiserver) as 6443:6443 the kubernetes API is then accessible externally without running into issues with Rancher authentication.  Additionally for testing purposes you could map the insecure (default 80), but keep in mind this removes both SSL and all authentication/authorization from the API.

**Comment by edbergavera** [comment]
Hello,

I am not sure if we are on the same boat. We are having issues activating kubernetes/openshift integration in GitLab 8.16.6 with following error below:

`We tried to send a request to the provided URL but an error occurred: HTTP status code , SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed`

On the GitLab's integration page if the API URL is set to HTTPS  I get the error above. If using HTTP and Rancher is configured with access control via Github I get the error you encountered:

`We tried to send a request to the provided URL but an error occurred: HTTP status code 503, 503 Service Unavailable`

The only thing it is working is to disable Access Control and use HTTP as API URL.

**Comment by jgallucci32** [comment]
Not sure if this is related or not, but I was attempting to integrate OpenShift on top of Kubernetes, but when doing so I get the following error:
```
error: kubernetes url may not include a path: '/r/projects/1a111349/kubernetes:6443'
```
This tells me I need to setup some type of load balancer to that path directly. It could be something in the GitLab code which is failing to hit the Kubernetes API because it has a specific path to hit.

**Comment by timwebster9** [comment]
I think we have a similar issue - trying to use the Jenkins Kubernetes plugin with a Rancher/Kubenetes environment, with Access Control turned on.  It looks like the connection from Jenkins is being redirected to the login page, preventing it from working.

**Comment by timwebster9** [comment]
Just an update if anyone else runs into this.  I have found a solution, although 

Our use case is accessing the Kubernetes cluster from Jenkins externally, with Rancher Access Control enabled.

- Turn on Kubernetes RBAC in your Kubernetes environment (either edit the env. template or upgrade the Kubernetes infra stack and enable it).
- Create and use a Rancher environment API key as credentials when accessing the Kubernetes endpoint.
- configure Kubernetes RBAC to allow the group 'system:unauthencated' access to the pods via roles, role bindings and cluster role bindings.  There are good examples in the docs: https://kubernetes.io/docs/admin/authorization/rbac/

For whatever reason the user 'k8s' that is created in the cluster by Rancher translates to 'system:anonymous' in Kubernetes, which I think is just an unauthenticated user.  The actual group is 'system:unauthenicated'.  I don't understand fully why the 'k8s' user is 'unauthenticated', but that's another thing to look at.

The key takeaway here is the use of the Rancher API key to access the cluster (which corresponds to the 'k8s' user).  

I haven't tried mapping Rancher Access control to Kubernetes access control (explained here: https://rancher.com/docs/rancher/v1.6/en/kubernetes/rbac/) but that might a way to tighten it up a little.

**Comment by TheCodeNinja** [comment]
Was having a similar issue to @timwebster9 where we needed to use a Jenkins plugin  (https://github.com/jenkinsci/kubernetes-plugin)
but could not authenticate correctly. We found that we were able to simply make a Jenkins credential of type "Openshift Oauth Token", populate it with the kubectl token obtained from the Rancher UI for the user we wanted to use and we were golden. 

Just wanted to share in case anyone else was having the same problem. It's a little bit safer than allowing system:anonymous what would have essentially been admin privileges in our case.

**Comment by ChrisHaPunkt** [comment]
From outside rancher, one can access the Kubernetes API directly with the credentials generated within the CLI Page (Generate Config).
The endpoint is as follows (example):
`server: "https://<rancher_host>:8080/r/projects/1a345/kubernetes:6443"` + `/api/v1/`

For authentication one has to provide the  `token` as described in here: https://kubernetes.io/docs/admin/authentication/#putting-a-bearer-token-in-a-request

**Comment by neonima** [comment]
Any news on that?

**Comment by avoidik** [comment]
@ChrisHaPunkt the idea of this issue is delegation of authentication directly to k8s api, instead of rancher api

**Comment by avoidik** [comment]
@kelchm your approach requires modifications to kubernetes templates, any hints how?

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

**Comment by avoidik** [comment]
If someone would have stumbled on this issue, there is now a solution available to that, called Authorized Cluster Endpoint

https://rancher.com/docs/rancher/v2.5/en/cluster-admin/cluster-access/ace/
