### ISSUE TITLE
Deleted project still shows active in member's screen

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#751]
Steps:
1.  Authenticate with Access set to Allow any GitHub user
2.  Log in as another user in different browser
3.  Create a project (this should be his only project, make sure you delete his default)
4.  Go to Services page
5.  Go back to Admin and delete the project that user just created
6.  Go back to user and go to Manage Projects screen

Results:
Deleted project is still showing up and as active.

Expected:
Project should not show up

**Comment by westlywright** [comment]
@lvuch and I checked this out locally. seems to be fixed already. Can you retest?

**Comment by tfiduccia** [comment]
Version - master 3/15
Verified fixed
