### ISSUE TITLE
Rancher CLI exec and docker commands confused if you have docker env set

### ISSUE THREAD

**Issue by sra** [rancher/rancher#7513]
**Rancher Versions:**
Server: 1.3.2

**Docker Version:**
1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
AWS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher, external RDS db

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
If you have previously set your docker environment to point to a specific host:

`eval $(docker-machine env some-host)`

Then `rancher exec` and `rancher --host some_other_host_id docker` will use that host instead of the one specified, despite talking to the correct rancher server.

You can correct it by using:

`eval $(docker-machine env -u)`

```
❯ eval $(docker-machine env dev1)
❯ rancher exec -it alertmanager sh
Error response from daemon: No such container: 8fdb771353bb62633282114ab37ee67508bfaa4ccb524b28fa376a136246d34c
❯ eval $(docker-machine env -u)
❯ rancher exec -it alertmanager sh
/alertmanager #
```

**Comment by scornea** [comment]
@sra I am not sure this is related as when I am running docker-machine ls i haven't got any docker machines and no default ones.  Also i've run the command that you've specified eval $(docker-machine env -u) but no luck

**Comment by scornea** [comment]
Any progress on this? :(

**Comment by IanVaughan** [comment]
I also see this problem, many thanks to the OP for a work around!

See also https://github.com/rancher/rancher/issues/7971

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
