### ISSUE TITLE
Rancher server unusable after triggering a restart of rancher_server from Rancher UI

### ISSUE THREAD

**Issue by domtoupin** [rancher/rancher#7514]
**Rancher Versions:**
Server: v1.3.2 (stable)
healthcheck: 0.2.0
ipsec: 0.8.1
network-services: 0.8.1
scheduler: 0.5.1

**Docker Version:**
 1.13.0, build 49bf474

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04, located in a virtual environment (Xen)

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher with internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
- Define a Cattle environment with one host, i.e. the host on which Rancher is running
- Trigger a container restart for `rancher_server`

**Results:** 
The `rancher_server` container is stopped but never restarted.
A manual attempt at restarting it using `docker start rancher_server` indeed start the container but just long enough to be able to go to the container details and see that it gets in a "Stopping (In Progress)" state just before it stop.

How can I _"cancel"_ the restart request so that my instance is back to normal? For what it is worth, I am able to attach to the container and perform SQL queries on the `cattle` database.

**Comment by domtoupin** [comment]
Running this SQL delays the container shutdown but does not fix it:

```
use cattle;
update instance set state = 'running', health_state = 'running' where name = 'rancher_server';
```

**Comment by aemneina** [comment]
@domtoupin have you tried this with the latest rancher server?

**Comment by Xstoudi** [comment]
Could be related to #9795

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
