### ISSUE TITLE
[Feature Request] IP address copy on click

### ISSUE THREAD

**Issue by bkuhl** [rancher/rancher#7515]
Whenever I see an ip address, I'd really like to be able to click the "link" icon next to the ip address and/or the address itself to copy the ip address to the clipboard.

![screen shot 2017-01-23 at 2 12 44 pm](https://cloud.githubusercontent.com/assets/524933/22218816/7da93068-e176-11e6-887c-183f74ff8732.png)

DigitalOcean does this really well.

**Rancher Versions:**
Server:
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker Version:**

**OS and where are the hosts located? (cloud, bare metal, etc):**

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**

**Results:**

**Comment by superseb** [comment]
Reusing the container IP copy mechanism would do just fine here I guess?

**Comment by vincent99** [comment]
@loganhz This is on the list view but not the box/dot views, can you add.  `{{#copy-inline}}`

**Comment by vincent99** [comment]
In 2.0.
