### ISSUE TITLE
Failover host allocation for service

### ISSUE THREAD

**Issue by kaos** [rancher/rancher#7521]
**Rancher Versions:**
Server: 1.3.0
healthcheck: 0.1.0
ipsec: 0.7.5
network-services: 0.2.15 (metadata 0.6.8)
scheduler: 0.4.0
kubernetes (if applicable):

**Docker Version:**
1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):**
RHEL 7.3, baremetal

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node, external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Not sure exactly how to make it happen by design, but I'll describe what was going on.

When upgrading a service (the scheduler in this case), the response from docker daemon when attempting to the remove the old container failed ("Error response from daemon" is the error message in rancher UI), rancher is unable to bring the service back online, on this host.

In this case, docker daemon failed to remove the container due to "Device busy" for the container file system. So it was an underlying docker issue. 

**Results:** 

The service remains unhealthy.

We would liked to have seen rancher mark this host as unusable for this service, and move on to deploy the service on the next available host. Rancher should go out of its way to bring the service back online, despite malfunctioning docker daemons.

As we see it, in this scenario, a single faulty docker daemon can fail an entire service regardless of the number of potential nodes to deploy to.

We may have missed critical points here, but I'd rather have this discussion lead to a resolution on our end, than not having it at all ;)

We've been so quiet for a long time now, only because we're so busy implementing stuff around rancher - without too much issues :)

**Comment by aemneina** [comment]
have you seen this recently @kaos? I think this affected older versions of rancher and has since been fixed.

**Comment by kaos** [comment]
No, I haven't. So I hope it's been fixed ;)

fre 19 maj 2017 kl. 05:05 skrev Ahmad E <notifications@github.com>:

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
