### ISSUE TITLE
Nameservers in containers

### ISSUE THREAD

**Issue by VAdamec** [rancher/rancher#7526]
**Rancher Versions:**
Server: v1.3.3
healthcheck: v0.2.0
ipsec: rancher/net:holder
network-services: v0.7.0 
network-manager: v0.4.0
scheduler: v0.5.1
kubernetes (if applicable):

**Docker Version:**
1.13.0

**OS and where are the hosts located? (cloud, bare metal, etc):**
OpenStack, CentOS 7 64b

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher, internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle 

**Steps to Reproduce:**
Run Nomad as container

```
docker run -d -v /mnt/nfs/rancher/database:/var/lib/mysql --restart=unless-stopped -p 80:8080 rancher/server
```

add hosts
...

run for example Selenium, see https://gist.github.com/VAdamec/610ddd4a65f7e7fd97c812f3125cda88

use Managed, Bridge or Host network (with Rancher discovery). Only setup where Rancher use hosts/defined dns is 'Host network' with ```disabled discovery```.

**Results:** 
resolv.conf contains only Rancher nameserver

```
$ cat /etc/resolv.conf

search rancher.internal openstacklocal firefox.selenium.rancher.internal selenium.rancher.internal
nameserver 169.254.169.250
```

- If you add DNS servers to docker-compose Rancher comment them out.

```
$ cat /etc/resolv.conf

search rancher.internal openstacklocal firefox.selenium.rancher.internal selenium.rancher.internal
# nameserver 10.0.0.1
# nameserver 10.0.0.2
nameserver 169.254.169.250
```

```Expected behaviour``` will be to use Host nameservers or defined dns as secondary, tertiary, ... eg. something like this:

```
$ cat /etc/resolv.conf

search rancher.internal openstacklocal firefox.selenium.rancher.internal selenium.rancher.internal
nameserver 169.254.169.250
nameserver 10.0.0.1
nameserver 10.0.0.2
```

**Comment by vincent99** [comment]
Secondary nameserver entries do not work the way you are suggesting.  The response from the first one is used as long as 169.254.169.250 returns *any kind of answer*, including not found/NXDOMAIN.  The 2nd and 3rd line would never be used except if the rancher DNS server on that host were completely unresponsive.

Instead the nameservers you provide become part of the config for the Rancher DNS server and  we use them to do recursive lookups of any   name that is requested outside of `rancher.internal`.

**Comment by VAdamec** [comment]
Ok, so how to use our internal nameservers instead hardcoded (Google ?) ones ?

**Comment by VAdamec** [comment]
Ahh, sorry, my mistake (our nameservers has some issue). All is working as expected ;-)
