### ISSUE TITLE
rancher-nfs & NFS 4.1 -> "rpc.statd is not running"

### ISSUE THREAD

**Issue by VikKayPumb** [rancher/rancher#7527]
I'm trying to setup rancher-nfs, setup is ok, but then when I try to use volumes from rancher-nfs, on container creation, I see an error:

"Activating (Expected state running but got error: Error response from daemon: create foo: VolumeDriver.Create: Failed mount -o nfsvers=4 172.17.105.236:/ /tmp/bay53: Running in chroot, ignoring request. mount.nfs: rpc.statd is not running but is required for remote locking. mount.nfs: Either use '-o nolock' to keep locks local, or start statd. mount.nfs: mounting 172.17.105.236:/ failed, reason given by server: No such file or directory)"

on the same time, 
>mount -t nfs4 -o minorversion=1 172.17.105.236:/NFS4 /var/nfs4 -v

from the same host works fine

172.17.105.236 - NFS server on Windows Server 2012R2, supports NFS 4.1 (not 4.0).

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.3.2` Cattle: `v0.175.8` UI: `v1.3.5` |
|Access|`Disabled`|
|Orchestration|`Cattle`|
|Route|`service.containers`|

**Comment by doreplado** [comment]
I was experiencing the same symptom and I believe I understand why I was seeing this error. 

### First a note about FSID=0
I do not think rancher-nfs can work if you're exporting your filesystems with fsid=0. At least through the catalog Web-UI. 

In the Web-UI for Rancher-NFS Catalog Item, Rancher has the fields:
- A. NFS Server  (IP / FQDN of where NFS export is)
- B. Mount Directory (this is "/" if you're doing FSID=0)
- C. Mount Options 
- D. NFS Version
- E. Debug Mode

If you're deploying the catalog and you use / for B. then for some reason, rancher-nfs and hosts don't populate in the Infrastructure -> Storage Dialog. 
_(A workaround is to deploy with B. being "/something" and then doing an upgrade on the NFS service and changing it to "/" )_

### Make it work
When you create your volume under Rancher-NFS in the Infrastructure -> Storage dialog, it must be the name of a directory in the root of that specified export path. 

**Example:**
On your NFS Server if your /etc/exports looks like this:
/exports/myshare 10.0.0.0/24(rw,insecure,fsid=0,no_subtree_check,async)

and in /exports/myshare it looks like - 
drwxr-xr-x 25 root staff 4096 Jan 21 18:53 .
drwxr-xr-x  5 root root       48 Jul 13  2016 ..
drwxr-xr-x  6  515 staff   73 Sep 12  2013 somedir
drwxr-xr-x  4  509 staff   25 Mar 23  2015 otherdir
drwxr-xr-x  4  512 staff   25 Oct 31  2014 thirddir


Then B. above should be / 
And your Volume name in the Infrastructure -> Storage dialog for rancher-nfs should be one of (somedir, otherdir, thriddir). 

If you're NOT using fsid=0 then B. above would be /exports/myshare

This is all assuming things like your ports are opened and you've done an exportfs -ra after updating your exports on the nfs server. 

I hope this helps someone. I wasn't able to find more detailed documentation than [this](http://docs.rancher.com/rancher/v1.3/en/rancher-services/storage-service/#using-storage-drivers-in-the-ui) but I could have missed it.

**Comment by aemneina** [comment]
thanks for the pointers @doreplado going to close this issue out.
