### ISSUE TITLE
Ldap groups have no access to environments

### ISSUE THREAD

**Issue by amsdard** [rancher/rancher#7528]
**Rancher Versions:**
Server: 1.3.3
healthcheck: 0.2
ipsec: 0.8.1?
network-services: 0.7 & 0.4
scheduler: 0.5.1
kubernetes (if applicable):

**Docker Version:**
1.12

**OS and where are the hosts located? (cloud, bare metal, etc):**
ubuntu 14.04, bare metal

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
cattle

**Steps to Reproduce:**
Enable Access control through OpenLdap using posixGroups. Settings provided below
`
api.auth.ldap.openldap.access.mode	unrestricted
api.auth.ldap.openldap.domain	dc=ldap,dc=company,dc=com
api.auth.ldap.openldap.group.name.field	cn
api.auth.ldap.openldap.group.object.class	posixGroup
api.auth.ldap.openldap.group.search.field	cn
api.auth.ldap.openldap.group.member.mapping.attribute	memberUid
api.auth.ldap.openldap.login.domain	
api.auth.ldap.openldap.port	389
api.auth.ldap.openldap.server	ldap.company.com
api.auth.ldap.openldap.service.account.password	pass
api.auth.ldap.openldap.service.account.user	cn=manager,dc=ldap,dc=company,dc=com
api.auth.ldap.openldap.tls	true
api.auth.ldap.openldap.user.enabled.mask.bit	0
api.auth.ldap.openldap.user.enabled.attribute	

api.auth.ldap.openldap.user.login.field	cn
api.auth.ldap.openldap.user.member.attribute	gidNumber
api.auth.ldap.openldap.user.name.field	givenName
api.auth.ldap.openldap.user.object.class	inetOrgPerson
api.auth.ldap.openldap.user.search.field	uid
api.auth.ldap.openldap.connection.timeout	1000
api.security.enabled	true
api.auth.provider.configured	openldapconfig
api.auth.ldap.openldap.group.dn.field	entryDN
api.auth.ldap.openldap.group.member.user.attribute	entryDN
telemetry.opt	in
`
**Results:** 
Groups are available but users beloning to given group has no access to environment at all. Everything was working in version 1.1.3, after upgrade new fields appeard api.auth.ldap.openldap.group.dn.field and api.auth.ldap.openldap.group.member.user.attribute where I've tried couple combintations of (cn, uid etc) but none of them worked.

Any idea what should I set there to make it work again?

**Comment by tfiduccia** [comment]
@amsdard 
Try setting api.auth.ldap.openldap.group.object.class to groupOfNames

**Comment by amsdard** [comment]
Thing is that in openLDAP server I use posixGroups, so far it was working. It broke after update to 1.3.3

**Comment by tfiduccia** [comment]
Do your members have the memberof attribute set?  If not we just had an issue that will be fixed in 1.4.  I had to set api.auth.ldap.openldap.group.member.user.attribute to member and then it worked.  But you would have to wait until 1.4 for the fix.  Should be out by end of month.

**Comment by amsdard** [comment]
Unfortunately I do not see option to set such attribute in inetOrgPerson object.

**Comment by tfiduccia** [comment]
For me I had to Fetch - Operational Attributes to see additional attributes.  If you have that on and don't see that option, that probably means you don't have that attribute set on individual users. You can either add the attribute or you will have to wait for 1.4 for the fix.

**Comment by amsdard** [comment]
Do you mean that I need to set all group in my user object instead of adding user to group? This is insane..

Anyway I've tried groupOfUnique names and still no luck :|

**Comment by gerardborst** [comment]
MemberOf is activated with an overlay http://www.openldap.org/doc/admin24/overlays.html. But for me this isn' t an option.

But group access to environment is working with v1.4.0-rc2.

**Comment by tfiduccia** [comment]
@amsdard - Sound like the group member bug.  It is fixed in 1.4.0-rc2 and will be fixed in our next upcoming release.

**Comment by amsdard** [comment]
Works in 1.4  but only with groupOfNames and groupOfUnique names. I think someone can close this issue.

**Comment by tfiduccia** [comment]
@amsdard - thanks for getting back to us.
