### ISSUE TITLE
Allow interpolate of stack_name into docker_compose files

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#7529]
Using the rancher or rancher-compose or the UI you can launch a catalog entry into a stack, within the docker-compose definition you can have affinity labels.

To be able to properly use the affinity labels certain variables should be available by default.

- stack_name
- service_name
- host_name

**Comment by joshwget** [comment]
Closing since #3393 and #4478 pretty much cover this. `host_name` isn't possible since a service could be rescheduled on a different host. Please reopen if you disagree!
