### ISSUE TITLE
1.3.x deployment getting into immobilized state 

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#7535]
**Rancher Versions:**
Server: 1.3.2

**Docker Version:**
1.12.6

**Steps to Reproduce:**
Symptoms:
Seems to affect deployments that have been upgraded from 1.1 -> 1.2 then to 1.3
active running processes low
large backlog of processes

setting `process.replay.batch.size` to a large number, say 100k, gets the server to pull in an actionable number of processes for it to work on.

**Results:**

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
