### ISSUE TITLE
instances that are not health check enabled , gets deleted and recreated on healthy hosts when the host in which it is running is powered down.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#7540]
Rancher Versions: Build from master with catalog from branch - https://github.com/rancher/rancher-catalog branch - v1.4.0-rc2

Docker Version: 1.12.6
Deploy "policy-manager" from catalog - https://github.com/leodotcloud/test-policy-manager.
Set defaultPolicyAction to "Deny" and policy to ```{"type":"networkPolicyRule","action":"allow","within":"stack"}``` to allow for traffic within stacks to succeed but cross stack traffic to be restricted.

Have 2 stacks with few services that are not health check enabled.
Power down the host some of the service instances (that are not health check enabled) is running.
Notice that the instances that are not health check enabled , get deleted and recreated in healthy state when the host transitions from Active->Reconnecting->Disconnected.
When host is still in "Active" state , we see the containers stuck  in "stopping" state with error -```Cannot connect to the Docker daemon at unix:///var/run/docker.sock``` . 
After this the container gets deleted and recreated in other hosts.

Expected Behavior:
Instances that are not health check enabled should not get recreated in other hosts. Once the host that was down is powered back on , service reconcile should trigger instance start.

**Comment by deniseschannon** [comment]
@sangeethah can you let me know if this is related to network policy or not?

**Comment by sangeethah** [comment]
@deniseschannon , This issue is not seen when testing in a setup with no network policy deployed.

**Comment by deniseschannon** [comment]
@leodotcloud something with network policy is causing this. please investigate.

**Comment by sangeethah** [comment]
This issue is not seen Rancher Versions: v1.4.0-rc5.  

Have 1 stacks with few services that are not health check enabled.
Power down one of the host where some of the service instances (that are not health check enabled) is running.
Instances are shown as being in "running" state when host goes from "active"->"reconnecting"->"disconnected"  as expected.

Power on the host.
When host gets to "active" state , instances get marked as being in "stopped" state.
service reconcile does not get triggered and Instances of this service continue to remain in "stopped" state. This issue is tracked in  https://github.com/rancher/rancher/issues/7604

**Comment by sangeethah** [comment]
Tested with rancher-server version - v1.4.0-rc8

Docker Version: 1.12.6

Deploy service that is not health check enabled.
Power down the host  where some of the service instances (that are not health check enabled) is running.
Notice that the instances that are not health check enabled , get deleted and recreated in healthy state when the host transitions from Active->Reconnecting->Disconnected.

Even when the hosts are still in "active" state (and host is powered down) , we see containers moving to stopping state.
Eventually they get destroyed and recreated in new hosts.

Note - I dont see this behavior for every instance in the host .But some of them get recreated.

**Comment by alena1108** [comment]
If you power off in DO UI it will do a VM shutdown which will stop docker which will stop the containers which the agent will see as a stop event and stop the containers in rancher.  So containers will go to stopped or stopping.

Once container goes to stopped state, service reconcile tries to restart it. But as agent is in "reconnnecting" at this point, reconcile will revoke all instances that are stuck in transitioning states from those hosts. So we end up removing/recreating the instance on another host.

This behavior is acceptable for instances with no health check enabled. It might happen more frequently with docker 1.13
