### ISSUE TITLE
NFS v4.1 is not suported by rancher-nfs, only v4.0 can be used

### ISSUE THREAD

**Issue by VikKayPumb** [rancher/rancher#7543]
It is impossible to mount and use NFS v4.1 (hosted on Windows Server 2012R2 as an example) with rancher/storage-nfs:v0.6.0

Details: 1) Windows supports only v2, v3, v4.1 and does not support v4
2) rancher-nfs expects only v4
3) tcpdump shows, that rancher sends request with "minorversion: 0"
------------- begin ------
Network File System, Ops(1): SETCLIENTID
    [Program Version: 4]
    [V4 Procedure: COMPOUND (1)]
    Tag: <EMPTY>
        length: 0
        contents: <EMPTY>
    minorversion: 0
    Operations (count: 1): SETCLIENTID
----------------- end ------
and NFS server responds with error " NFS4ERR_MINOR_VERS_MISMATCH (10021)"
------------- begin ------
Network File System, Ops(0):
    [Program Version: 4]
    [V4 Procedure: COMPOUND (1)]
    Status: NFS4ERR_MINOR_VERS_MISMATCH (10021)
----------------- end ------

4) all further error messages in ranchers look inadequate, see related issue https://github.com/rancher/rancher/issues/7527

5) adding "minorversion=1" to MOUNT_OPTS just ignored

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.3.2` Cattle: `v0.175.8` UI: `v1.3.5` |
|Access|`Disabled`|
|Orchestration|`Cattle`|
|Route|`stacks.index`|

**Comment by VikKayPumb** [comment]
Windows Server 2012R2 NFS settings:
![image](https://cloud.githubusercontent.com/assets/20070349/22298171/3c3d045c-e328-11e6-9b9e-36378c3ee252.png)

**Comment by junkiebev** [comment]
Are there any plans to support nfs 4.1 in the future? Is the Docker image it uses just not compatible with 4.1?

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
