### ISSUE TITLE
Allow export of audit log

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#7544]
I use splunk heavily, it would be nice to be able to have Rancher send the audit logs to an HTTP receiver or write them to a file so it can be consumed by Splunk.

**Comment by tuwid** [comment]
Any update on this ? I would really need a way to have audit logs exported somewhere..

**Comment by superseb** [comment]
Going to close this in favor of https://github.com/rancher/rancher/issues/5384, let me know if you don't agree.

**Comment by ekristen** [comment]
Makes sense, thanks.
