### ISSUE TITLE
Feature: configurable password question

### ISSUE THREAD

**Issue by joshuacox** [rancher/rancher#7546]
**Rancher Versions:**
Server: 1.2.2

I think it would be nice to have a configurable length and possibly composition of the password question.  This could possibly be done with more types i.e.

```
password16   = 16 character length password uses all characters
password16alphanum = 16 character length password uses only alphanumeric characters
password32   = 32 character length password uses all characters
password32alphanum = 32 character length password uses only alphanumeric characters
```

and then you specify that as your 'type'

```
type: password32alphanum
```

or by specifying more fields before the type:

```
passwordlength: 32
passwordchars: alphanum
type: password
```

or even one where you pass in an array of chars, but they seems a bit overboard for the moment.  Feel free to just close this issue if it's out of scope

**Comment by joshuacox** [comment]
just going nutty with it, how about give the user a dropdown caret which let's them choose some of this stuff themselves right beside the `generate` button.  Just throwing ideas out there, feel free to ignore this and concentrate on more important stuff.  I tend to generate my passwords anyhow as it is not the right length or has characters I'm suspicious about breaking things (postgres in particular I think does not like rancher generated passwords )

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
