### ISSUE TITLE
Cannot use Kubernetes environment with Read-Only role

### ISSUE THREAD

**Issue by zambon** [rancher/rancher#7547]
**Rancher Versions:**
Server: 1.3.3
![Infra Versions](http://i.imgur.com/XqNXiiG.png)

**Docker Version:** 1.11.2

**OS and where are the hosts located? (cloud, bare metal, etc):** Ubuntu 16.04, cloud (IBM SoftLayer)

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** Single node, external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Kubernetes

**Steps to Reproduce:**

1. Create Kubernetes environment (Kub)
1. Add hosts (I added 4)
1. Wait for setup to complete
1. Deploy Redis (or any other template, for the sake of testing)
1. ADMIN -> Accounts -> Add Account: create a new user (account type _User_)
1. Add the new to the Kub environment with membership role _Read-Only_
1. Log out and log in as the new user

**Results:** 

![Setting up](http://i.imgur.com/tAIcfDl.png)

Even though the environment is up and running, the new user with _Read-Only_ role sees that.

Changing the role to any other value "fixes" the problem.

**Comment by qamalbcgdv** [comment]
I am seeing this in 1.3.2 as well. :+1:

**Comment by superseb** [comment]
This is still the case in 1.6.0

**Comment by reyesvindas** [comment]
v1.6.4 and I have the same issue

**Comment by joshwget** [comment]
This could be a UI issue. If the UI isn't able to access the infra stacks it might appear as if Kubernetes is still initializing. What do you think @vincent99?

**Comment by tfiduccia** [comment]
Version - v1.6.6-rc2
This is still an issue.  Console says:
fetch.js:404 GET http://<ip address>/r/projects/1a12/kubernetes/version 503 (Service Unavailable).  not sure if that is helpful or not

**Comment by vincent99** [comment]
@joshwget The server's returning the 503... I need to be able to talk to the `kubernetes`, `kubectld`, and `kubernetes-dashboard` services to provide the UI.

**Comment by xiboy** [comment]
Still have the issue with rancher 1.6.9
I have these errors into rancher server's log:

> "log":"time=\"2017-11-06T16:01:46Z\" level=error msg=\"Error looking up token.\" error=\"HTTP error: 405 Method Not Allowed, 405\" \n","stream":"stderr","time":"2017-11-06T16:01:46.499031309Z"}
> {"log":"time=\"2017-11-06T16:01:47Z\" level=error msg=\"Error looking up token.\" error=\"HTTP error: 405 Method Not Allowed, 405\" \n","stream":"stderr","time":"2017-11-06T16:01:47.149210561Z"}
> {"log":"time=\"2017-11-06T16:01:48Z\" level=error msg=\"Error looking up token.\" error=\"HTTP error: 405 Method Not Allowed, 405\" \n","stream":"stderr","time":"2017-11-06T16:01:48.911734576Z"}

**Comment by will-chan** [comment]
@vincent99 Instead of the loading page, for RO users, can we simply just show the user the kubeconfig details for kubectl?  Obviously, it will give a RO user full access unless RBAC is enabled on k8s side.

**Comment by vincent99** [comment]
- The kubeconfig generated depends on the version of k8s that it's for, which comes from talking to k8s, which is the part that's not working in the first place.

- Showing the kubeconfig requires generating a new API key (since I don't have the secret to any existing ones), which a readonly user doesn't have permission to do.

- I can't even know if the buttons for dashboard, kubectl and shell should be active without knowing if the k8s api is up and usable.

**Comment by will-chan** [comment]
Ok, if the RO can't even get keys, then this can't work unless we allow that.  I was under the impression, you could which meant that although the UI may not have an easy way to do this, the kubeconfig can be recreated with the current access level of the RO user.

**Comment by strowi** [comment]
running into the same issue, is there any timeline or workaround ?
I don't want to give every developer access to the infra-stack (every other role member,owner, retricted can remove hosts/containers..).

regards,
Roman

**Comment by devarti** [comment]
Any update on this issue?

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

In 1.6, if you want to achieve this, you can provide restricted access to a member and turn on k8s rbac to limit them to read only roles.
