### ISSUE TITLE
Rancher UI login extermely slow 

### ISSUE THREAD

**Issue by jamiebuxxx** [rancher/rancher#7548]
We are experiencing issues with our Rancher Web UI, which is behaving slowly during logins and has been affecting user's browser performance during the login process. I have a attached a screenshot of what we see when logging into Rancher. 
![screen shot 2017-01-25 at 10 41 17 am](https://cloud.githubusercontent.com/assets/1173214/22306639/caf6f088-e2f4-11e6-9e06-0410d3e94193.png)

It will stay on this screen for 2-3mins.

We _think_ the issue is LDAP related, but its hard to pen point since we can't find any auth related log data from the rancher-server container. We had tried different domain controllers with same results. However, it does appears that auth is happening because if you enter in a wrong password, you will be denied access.

Our current setup is rancher-server container with a external MySQL database running on the host. I have also setup HTTPS and using a nginx container to proxy from port 8000 to 433.

Please let us know if we can provide any further info. 

Thanks,

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.3.2` Cattle: `v0.175.8` UI: `v1.3.5` |
|Access|`ldap` `admin`|
|Orchestration|`Kubernetes`|
|Route|`k8s-tab.namespace.stacks.index`|

**Comment by aemneina** [comment]
@jamiebuxxx is there anything telling in the browsers developer tools output? You might find clues relating to pending queries or failed connections. Posting a sanitized version of your proxy config might also be helpful.

**Comment by jamiebuxxx** [comment]
@aemneina 

The only thing that seemed interesting from the developer browsers console tool was the following:
```
GET 
XHR https://rancher.host.com/v2-beta/projects/1a7/mounts [HTTP/1.1 200 OK 512ms]
Depaginate, requesting "https://rancher.host.com/v2-beta/projects/1a7/mounts?limit=-1&marker=m15000"  vendor-45897e50be27cdd43c606e3ffcf6a893.js:54
GET 
XHR 
https://rancher.host.com/v2-beta/projects/1a7/mounts [HTTP/1.1 200 OK 437ms]
Depaginate, requesting "https://rancher.host.com/v2-beta/projects/1a7/mounts?limit=-1&marker=m18000"  vendor-45897e50be27cdd43c606e3ffcf6a893.js:54
```
This message continues to repeat until the actually WebUI comes up. Here's a copy of the our nginx conf we are using on the nginx container:

https://gist.github.com/jamiebuxxx/613c09c854a218e448886e0d551d4137

**Comment by aemneina** [comment]
so the rancher server has the mysqldb on the same host, is that host
struggling with resources? Whats the spec of that box?

**Comment by jamiebuxxx** [comment]
Yes, the MySQL is running on the same host. Its an Ubuntu 16.04 VM with 4 core vCPU and 32GB of RAM with 100GB HD. The server is not breaking a sweat.

**Comment by aemneina** [comment]
Okay thats a capable host... It also looks like your query is choking on the amount of volumes/mounts. Can you share the output of: `SELECT table_name AS "Table", round(((data_length + index_length) / 1024 / 1024), 2) as TEST FROM information_schema.TABLES WHERE table_schema = "<cattle_db_name>" ORDER BY TEST;`

**Comment by jamiebuxxx** [comment]
Ok. Yea, I thought the mounts stuff looked interesting. Here's the output of the MySQL query.

```
+-----------------------------------------------+--------+
| Table                                         | TEST   |
+-----------------------------------------------+--------+
| DATABASECHANGELOGLOCK                         |   0.02 |
| task                                          |   0.03 |
| config_item                                   |   0.03 |
| dynamic_schema_role                           |   0.03 |
| data                                          |   0.03 |
| setting                                       |   0.03 |
| task_instance                                 |   0.03 |
| cluster_membership                            |   0.05 |
| volume_template                               |   0.06 |
| storage_driver                                |   0.06 |
| load_balancer_certificate_map                 |   0.08 |
| external_event                                |   0.08 |
| backup                                        |   0.09 |
| external_handler_process                      |   0.09 |
| external_handler                              |   0.09 |
| zone                                          |   0.11 |
| ip_pool                                       |   0.11 |
| certificate                                   |   0.11 |
| machine_driver                                |   0.11 |
| backup_target                                 |   0.11 |
| global_load_balancer                          |   0.11 |
| user_preference                               |   0.11 |
| agent_group                                   |   0.11 |
| service_log                                   |   0.11 |
| offering                                      |   0.11 |
| service_index                                 |   0.13 |
| host_vnet_map                                 |   0.13 |
| network_service_provider_instance_map         |   0.13 |
| subnet_vnet_map                               |   0.13 |
| network_driver                                |   0.13 |
| network_service_provider                      |   0.13 |
| host_ip_address_map                           |   0.13 |
| network                                       |   0.13 |
| cluster_host_map                              |   0.13 |
| ip_address_nic_map                            |   0.13 |
| storage_pool_host_map                         |   0.13 |
| deployment_unit                               |   0.13 |
| project_member                                |   0.13 |
| healthcheck_instance                          |   0.13 |
| vnet                                          |   0.13 |
| credential_instance_map                       |   0.13 |
| snapshot_storage_pool_map                     |   0.13 |
| load_balancer_listener                        |   0.13 |
| generic_object                                |   0.13 |
| snapshot                                      |   0.13 |
| credential                                    |   0.13 |
| physical_host                                 |   0.13 |
| load_balancer_config                          |   0.13 |
| service_consume_map                           |   0.14 |
| service_expose_map                            |   0.14 |
| host_label_map                                |   0.14 |
| environment                                   |   0.14 |
| subnet                                        |   0.14 |
| network_service                               |   0.14 |
| ip_association                                |   0.14 |
| project_template                              |   0.14 |
| load_balancer_target                          |   0.14 |
| load_balancer_host_map                        |   0.14 |
| load_balancer_config_listener_map             |   0.14 |
| config_item_status                            |   0.14 |
| account                                       |   0.16 |
| load_balancer                                 |   0.16 |
| service_event                                 |   0.16 |
| DATABASECHANGELOG                             |   0.16 |
| dynamic_schema                                |   0.16 |
| storage_pool                                  |   0.16 |
| instance_link                                 |   0.16 |
| external_handler_external_handler_process_map |   0.16 |
| resource_pool                                 |   0.17 |
| ip_address                                    |   0.17 |
| auth_token                                    |   0.17 |
| host                                          |   0.19 |
| healthcheck_instance_host_map                 |   0.19 |
| agent                                         |   0.20 |
| service                                       |   0.22 |
| image_storage_pool_map                        |   0.25 |
| nic                                           |   0.30 |
| port                                          |   0.31 |
| label                                         |   0.38 |
| process_instance                              |   1.27 |
| instance_host_map                             |   1.30 |
| volume_storage_pool_map                       |   1.66 |
| audit_log                                     |   2.09 |
| container_event                               |   4.19 |
| process_execution                             |   4.20 |
| image                                         |   6.34 |
| volume                                        |   6.41 |
| instance_label_map                            |   8.55 |
| mount                                         |  15.05 |
| instance                                      | 274.92 |
+-----------------------------------------------+--------+
90 rows in set (0.06 sec)
```

**Comment by aemneina** [comment]
Mount is large, but not terrifying. We have a cleanup script that should prune unused mounts, can you give that a go and see if it resolves the issue?

`docker run --rm rancher/cleanup-1-1:v0.1.2` should give you the usage... just point it at your db.

**Comment by jamiebuxxx** [comment]
That worked!! Is there a particular reason this is happening? We did recently update the rancher-server version. And should we run the cleanup container periodically? Like on a once a week cronjob?

**Comment by vincent99** [comment]
It's to clean up cruft created by previous versions and before there was automatic cleanup of most of the tables.  You shouldn't need to run it again.

**Comment by jamiebuxxx** [comment]
Got it! Thanks for the help @aemneina and @vincent99

**Comment by cdomigan** [comment]
How would I run this cleanup on a single container instance? ie no external database

**Comment by jamiebuxxx** [comment]
@aemneina @vincent99 
Our Rancher server recently started showing the previous behavior I reported in the issue. I ran the cleaner container and everything is back to normal. Nothing with our setup has changed. I'm just curious if anyone has any further information about whats causing the Web UI/Database cruff issues?

**Comment by klausmeyer** [comment]
@cdomigan this is how I did it just now:

1. Create backup of database and verify dump completeness:

```
[deploy@docker01 ~]$ docker exec -it <id-of-server-container> mysqldump cattle > cattle.sql
[deploy@docker01 ~]$ head cattle.sql 
-- MySQL dump 10.13  Distrib 5.5.53, for debian-linux-gnu (x86_64)
--
-- Host: localhost    Database: cattle
-- ------------------------------------------------------
-- Server version       5.5.53-0ubuntu0.14.04.1

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
[deploy@docker01~]$ tail cattle.sql 

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2017-03-03  9:09:18
```

2. Run cleanup:

```
[deploy@docker01 ~]$ docker run --rm --link <id-of-server-container>:mysql rancher/cleanup-1-1:v0.1.2 --db-host mysql
```

**Comment by rzfoxify** [comment]
Hi. I tried the solution from this topic. Didn't help. First the problem appeared on Rancher v.1.4.1 (or 1.4.2 I don't remember) and it took around 5 minutes to log in. Today I updated to 1.5.5 and now it takes from 30 sec to 1 min to log in, which is still pretty slow. This is the output of Chrome console: Depaginate, requesting http://185.170.114.43:8080/v2-beta/projects/1a198/volumes?limit=-1&sort=name&marker=m48000 in file collection.js:57

We use single Non-HA container with built-in DB.
Rancher/cleanup didn't help.
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.5.5` Cattle: `v0.178.3` UI: `v1.5.8` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`authenticated.project.help`|

**Comment by jamiebuxxx** [comment]
Since upgrading to Rancher 1.5.6 this issue has since be resolved for us. I will close this issue since I re-opened. If folks are still having issues, you can re-open or reference this in separate issue. Good luck!
