### ISSUE TITLE
Rancher Agent Does not Run, Docker retunrs "container did not start before the specified timeout"

### ISSUE THREAD

**Issue by gsideri** [rancher/rancher#7551]
**Rancher Versions:**
Server: v.1.2.3
healthcheck: n/a
ipsec: n/a
network-services: n/a
scheduler: n/a
kubernetes (if applicable):

**Docker Version:** 1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 14.04 in OpenStack
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node Rancher, Internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Swarm & Cattle

**Steps to Reproduce:**
1) I go to my first node called Rancher & Run the rancher server:
` sudo docker run -d --restart=unless-stopped -p 80:8080 rancher/server:v1.2.3`
Everything goes ok here.

2)Setup an Swarm or Cattle environment.
3)
Go to Node 1 and run the agent with the following command:

`sudo docker run -d --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.1.2 http:/xxx/v1/scripts/D822D98E34752A28BAB0:1485381600000:tRVOtA1DjGAPFUYsRABPHQuybzE`

**Results:** 
Dockers returns 
`docker: Error response from daemon: containerd: container did not start before the specified timeout.`
And the Agent does not run.

My IPtables (just in case) is:

`-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
-N CATTLE_FORWARD
-N DOCKER
-N DOCKER-ISOLATION
-A FORWARD -j DOCKER-ISOLATION
-A FORWARD -p tcp -m tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu
-A FORWARD -j CATTLE_FORWARD
-A FORWARD -o docker0 -j DOCKER
-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i docker0 ! -o docker0 -j ACCEPT
-A FORWARD -i docker0 -o docker0 -j ACCEPT
-A FORWARD -o docker_gwbridge -j DOCKER
-A FORWARD -o docker_gwbridge -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i docker_gwbridge ! -o docker_gwbridge -j ACCEPT
-A FORWARD -i docker_gwbridge -o docker_gwbridge -j DROP
-A CATTLE_FORWARD -m mark --mark 0x668a0 -j ACCEPT
-A DOCKER-ISOLATION -i docker_gwbridge -o docker0 -j DROP
-A DOCKER-ISOLATION -i docker0 -o docker_gwbridge -j DROP
-A DOCKER-ISOLATION -j RETURN`

Could you please help me? I don't know what is going wrong.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
