### ISSUE TITLE
Plaintext passwords in audit logs

### ISSUE THREAD

**Issue by cdancette** [rancher/rancher#7552]
**Rancher Versions:**
v1.1.0

**Steps to Reproduce:**
Change your password
Go to admin -> audit logs
Password is available when clicking on api.password.changesecret

**Comment by cdancette** [comment]
This seems critical, as a user I don't expect my password to be displayed somewhere in plain text.

**Comment by sangeethah** [comment]
Tested with v1.5.7-rc6

Have local auth enabled.
Change your password
Go to admin -> audit logs
There is no password exposed in the api  api.password.changesecret
