### ISSUE TITLE
LB stuck in "Initializing" state when it has https listeners.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#7555]
Rancher Versions: v1.4.0-rc3

Steps to reproduce the problem:
Create a LB service with few "https" port rules with default certificate.
LB service is stuck in "Initializing" state forever with the following error message in logs:
```
1/25/2017 9:50:58 PMtime="2017-01-26T05:50:58Z" level=error msg="Failed to get lb config: Coudln't get certificate by name [test-889917]. Error: Unknown schema type [certificate]"
1/25/2017 9:51:02 PMtime="2017-01-26T05:51:02Z" level=error msg="Failed to get lb config: Coudln't get certificate by name [test-889917]. Error: Unknown schema type [certificate]"
```

**Comment by sangeethah** [comment]
Tested with v1.4.0-rc4
This issue is not seen any more.

All validation tests relating to LB with https listeners pass.

**Comment by cedvan** [comment]
@hi, I use rancher server v1.5.3 and I have this problem :disappointed:

**Comment by fjoesne** [comment]
same here with 1.5.6 on 1.12.3 ...

**Comment by SergioMBS** [comment]
This issues still happens on v1.6.10 when a host restarts

**Comment by BastianHofmann** [comment]
@sangeethah could you reopen the issue, since people are still experiencing this issue. Important to note is that this issue does not occur deterministically (at least for me). It only happens once in a while.
