### ISSUE TITLE
Is it normal for rancher schedule to just fail

### ISSUE THREAD

**Issue by hadyrashwan** [rancher/rancher#7559]
**Rancher Versions:**
Server:v0.5.1
healthcheck:v0.2.0
ipsec:v0.8.1
network-services::v0.4.0
scheduler:v0.5.1

**Docker Version:**
rancher server : 1.12.1, build 23cf638
racher agent : 1.12.6, build 7392c3b/1.12.6
**OS and where are the hosts located? (cloud, bare metal, etc):**
rancher server: Azure   ubuntu 16.04  Standard_A1 
rancher agent : Amazon Linux AMI 2016-9 t2.micro

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
rancher server : single node rancher + DB volume(on the same machine)
rancher agent : drone CI 0.4 (from catalog bitbuket + sqllit3 no external DB)
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
make commit on my repo
build starts 
.drone.yml file: https://gist.github.com/hadyrashwan/c422c20a77c7acb3c7bba493f4026236

build fails with the following error
```sh
npm info lifecycle compression@1.6.2~install: compression@1.6.2
npm info lifecycle express@4.14.0~install: express@4.14.0
npm info lifecycle nodeadmin@0.1.2~install: nodeadmin@0.1.2
npm info lifecycle vizion@0.2.13~install: vizion@0.2.13
npm info lifecycle websocket@1.0.24~install: websocket@1.0.24

> websocket@1.0.24 install /drone/src/bitbucket.org/assesstm/assessboard/node_modules/websocket
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory '/drone/src/bitbucket.org/assesstm/assessboard/node_modules/websocket/build'
 CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
```
drone freeze and gives me 503 

**Results:** 
the scheduler fails(needed manual restart)
drone fails and restarted

when trying again
 the schedule didn't fail
rancher agent(AWS t2.micro) is disconnected and then went back again after some time

![screenshot from 2017-01-26 10-29-29](https://cloud.githubusercontent.com/assets/10724548/22326359/f78d2d94-e3ba-11e6-9961-53af1a9d7e13.png)
![screenshot from 2017-01-26 10-30-04](https://cloud.githubusercontent.com/assets/10724548/22326368/03013850-e3bb-11e6-8fe8-bc3abf682132.png)

my questions are:  
Is it normal for the schedule to just fail shouldn't it be responsible for booting/managing containers across many environments  ??
if I got something else besides drone on that machine does it mean that I can't communicate to it and wait for the system to heal itself ??
are the machine sizes too small to handle the load, in general, do I need bigger machines??

**Comment by vincent99** [comment]
If you're doing any kind of sustained work like compiling on a t2.micro it will run out of CPU credits, then not be able to get even enough CPU time to keep up with pings to the server.  When those aren't happening the host goes into disconnected state.

**Comment by hadyrashwan** [comment]
I see thanks
