### ISSUE TITLE
Rancher CPU stats confused

### ISSUE THREAD

**Issue by jstdoit** [rancher/rancher#7560]
**Rancher Versions:**
Server: CentOS 7.1
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker Version:**
Docker 1.13
**OS and where are the hosts located? (cloud, bare metal, etc):**

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**

**Results:** 
![image](https://cloud.githubusercontent.com/assets/1089041/22327066/517c1128-e3f0-11e6-8f49-e87dafe42dd2.png)

As shown in the image above, the Y axis show annoying. Is there anyone who knows how to adjust it? Thanks.

**Comment by tfiduccia** [comment]
@jstdoit - what version of rancher are you using?  I seem to remember that we fixed this particular issue, but there is still another bug for CPU that is outstanding.  #6895.  So I'm going to close this in favor of that bug.
