### ISSUE TITLE
[rancher-compose] Rancher ignore AWS CLI  plugin endpoint

### ISSUE THREAD

**Issue by ahmet2mir** [rancher/rancher#7561]
I use S3 compatible storage ([Minio](https://github.com/minio/minio)), aws-cli works well thanks to this [plugin ](https://github.com/wbinglee/awscli-plugin-endpoint).
Now i'm getting 403 on upload because rancher try to contact aws instead of my custom endpoint.

**Rancher Versions:**
Server: 1.3.0
healthcheck: 0.2.0
ipsec: net:holder bb516596ce5a
network-services: metadata:0.7.0 network-manager:0.4.0
scheduler:0.5.1
kubernetes (if applicable):

**Docker Version:** 1.13.0

**OS and where are the hosts located? (cloud, bare metal, etc):** RHEL 7.2 on VM (vmware)

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** HA rancher + external mysl

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** cattle

**Steps to Reproduce:**

Run a S3 server

	[me@slave01]$ docker run -d -p 9000:9000 --name minio minio/minio server /export

Get access and secret keys

	[me@slave01]$ docker logs minio | grep -E 'Endpoint|AccessKey|SecretKey|Region'

Install deps

	[me@slave01]$ pip install --user awscli awscli-plugin-endpoint

Configure

	[me@slave01]$ mkdir ~/.aws
	[me@slave01]$ cat ~/.aws/config
	[default]
	output = table
	region = us-east-1
	s3 =
           endpoint_url = http://slave01:9000
 	s3api =
           endpoint_url = http://slave01:9000

	[plugins]
	endpoint = awscli_plugin_endpoint

	[me@slave01]$ cat ~/.aws/credentials
	[default]
	aws_access_key_id = ********
	aws_secret_access_key = ********

Create a bucket

	[me@slave01]$ aws s3api create-bucket --bucket rancher
	--------------------------
	|      CreateBucket      |
	+-----------+------------+
	|  Location |  /rancher  |
	+-----------+------------+

Copy file

	[me@slave01]$ aws s3 cp Dockerfile s3://rancher
	upload: ./Dockerfile to s3://rancher/Dockerfile                   

Show content

	[me@slave01]$ aws s3 ls  s3://rancher
	2017-01-26 10:09:19        340 Dockerfile

Everything is ok. Now I try a rancher-compose up with build in my compose, I got

	status code: 403, request id: [] 

Using strace (I have to run it 5 times to see the connection), Rancher seems to contact aws directly ignoring endpoint plugin

	[me@slave01]$ strace -e trace=network rancher-compose --debug up
	...
	DEBU[0000] Looking for stack 0                          
	DEBU[0000] Found stack: 0(1st104)                       
	DEBU[0000] [0/0] [nginx_data_y]: EventType: 31          
	DEBU[0000] [0/0] [nginx]: Adding                        
	DEBU[0000] Opening rancher-compose file: templates/nginx/0/rancher-compose.yml 
	DEBU[0000] [0/2] [nginx-lb]: Adding                     
	INFO[0000] Existing volume template found for nginx_data_y 
	DEBU[0000] Launching action for nginx                   
	DEBU[0000] Launching action for nginx-lb                
	DEBU[0000] Project [0]: Creating project                
	INFO[0000] [0/2] [nginx]: Creating                      
	DEBU[0000] Finding service nginx                        
	INFO[0000] Creating service nginx                       
	INFO[0000] Uploading build for nginx using provider S3  
	socket(PF_INET, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, IPPROTO_IP) = 8
	setsockopt(8, SOL_SOCKET, SO_BROADCAST, [1], 4) = 0

	**connect(8, {sa_family=AF_INET, sin_port=htons(443), sin_addr=inet_addr("54.231.48.160")}, 16) = -1 EINPROGRESS (Operation now in progress)**

	ERRO[0001] Failed Creating nginx : : 
		status code: 403, request id: [] 
	DEBU[0001] Finding service nginx-lb                     
	INFO[0001] [0/2] [nginx-lb]: Creating                   
	INFO[0001] Creating service nginx-lb                    
	DEBU[0001] Finding service nginx

The DNS record for 54.231.48.160

	[me@slave01]$ host 54.231.48.160
	160.48.231.54.in-addr.arpa domain name pointer s3-1-w.amazonaws.com.

**Results:** 

status code: 403, request id: []

**Comment by ahmet2mir** [comment]
It's on the go sdk. Endpoint is a cli option and not from file.
So may update rancher to support it ? with var env for example ?

**Comment by abeMedia** [comment]
I'm using minio as s3 storage, however I'm getting the same error. I think using an env var is indeed the way forward. Am happy to submit a PR if you guys are willing to merge something like that...

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
