### ISSUE TITLE
[cli] "rancher up" segfault

### ISSUE THREAD

**Issue by drzero42** [rancher/rancher#7562]
**Rancher Versions:**
Server: 1.3.3
healthcheck: 0.2.0
ipsec: 0.8.1
network-services: 0.4.0
scheduler: 0.5.1
kubernetes (if applicable):

**Docker Version:**
Client:
 Version:      1.13.0
 API version:  1.24
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24 (minimum version )
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 23:26:11 2016
 OS/Arch:      linux/amd64
 Experimental: false

**OS and where are the hosts located? (cloud, bare metal, etc):** 
docker-machine provisioned RancherOS 0.7.1

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Host-machine is Ubuntu 16.04 64-bit, rancher/server:stable is running on docker-machine/RancherOS 0.7.1 and rancher/agent:v1.1.3 on another docker-machine/RancherOS

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Trying to deploy our own app which works with docker-compose to rancher by basically just adding a rancher-compose.yml file which sets scale: 1 for all services. No labels have been added to docker-compose.yml. I just run "rancher up"

**Results:** 
$ rancher up 
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x7d3c73]

goroutine 1 [running]:
panic(0xa182e0, 0xc420010100)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/rancher/cli/vendor/github.com/urfave/cli.HandleAction.func1(0xc4204c8a80)
	/go/src/github.com/rancher/cli/vendor/github.com/urfave/cli/app.go:472 +0x29e
panic(0xa182e0, 0xc420010100)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/rancher/cli/vendor/github.com/rancher/rancher-compose/rancher.(*RancherVolumesFactory).Create(0xc42002e660, 0xc4203464c2, 0x5, 0xc420346390, 0xc42033d500, 0x1, 0x12, 0xc420348000, 0x78d, 0x98d)
	/go/src/github.com/rancher/cli/vendor/github.com/rancher/rancher-compose/rancher/volume.go:21 +0x1b3
github.com/rancher/cli/vendor/github.com/docker/libcompose/project.(*Project).load(0xc4200dca80, 0xaf5f95, 0x12, 0xc420348000, 0x78d, 0x98d, 0xc420182298, 0x4119c8)
	/go/src/github.com/rancher/cli/vendor/github.com/docker/libcompose/project/project.go:247 +0x4ae
github.com/rancher/cli/vendor/github.com/docker/libcompose/project.(*Project).Parse(0xc4200dca80, 0x0, 0x0)
	/go/src/github.com/rancher/cli/vendor/github.com/docker/libcompose/project/project.go:112 +0x15a
github.com/rancher/cli/vendor/github.com/rancher/rancher-compose/rancher.NewProject(0xc4200daa80, 0xaed8d6, 0x4, 0x300)
	/go/src/github.com/rancher/cli/vendor/github.com/rancher/rancher-compose/rancher/project.go:46 +0x1ad
github.com/rancher/cli/vendor/github.com/rancher/rancher-compose/app.(*ProjectFactory).Create(0xc4204c84c8, 0xc4202e37c0, 0xaed7ba, 0x4, 0xc42033a510, 0x0)
	/go/src/github.com/rancher/cli/vendor/github.com/rancher/rancher-compose/app/app.go:66 +0x7a0
github.com/rancher/cli/cmd.(*projectFactory).Create(0xe46ff8, 0xc4202e37c0, 0x0, 0x8, 0x8, 0xc42033ca60)
	/go/src/github.com/rancher/cli/cmd/up.go:63 +0x390
github.com/rancher/cli/vendor/github.com/docker/libcompose/cli/app.WithProject.func1(0xc4202e37c0, 0x0, 0x0)
	/go/src/github.com/rancher/cli/vendor/github.com/docker/libcompose/cli/app/app.go:45 +0x4e
reflect.Value.call(0x9d7b40, 0xc42029d920, 0x13, 0xaed4fe, 0x4, 0xc4204c8a20, 0x1, 0x1, 0x49e2c8, 0xad3d60, ...)
	/usr/local/go/src/reflect/value.go:434 +0x5c8
reflect.Value.Call(0x9d7b40, 0xc42029d920, 0x13, 0xc4204c8a20, 0x1, 0x1, 0x0, 0x140, 0x140)
	/usr/local/go/src/reflect/value.go:302 +0xa4
github.com/rancher/cli/vendor/github.com/urfave/cli.HandleAction(0x9d7b40, 0xc42029d920, 0xc4202e37c0, 0x0, 0x0)
	/go/src/github.com/rancher/cli/vendor/github.com/urfave/cli/app.go:481 +0x1e0
github.com/rancher/cli/vendor/github.com/urfave/cli.Command.Run(0xaecdb7, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0xaf7dd6, 0x15, 0x0, ...)
	/go/src/github.com/rancher/cli/vendor/github.com/urfave/cli/command.go:186 +0xc26
github.com/rancher/cli/vendor/github.com/urfave/cli.(*App).Run(0xc4202d0180, 0xc42000a660, 0x2, 0x2, 0x0, 0x0)
	/go/src/github.com/rancher/cli/vendor/github.com/urfave/cli/app.go:235 +0x60c
main.mainErr(0x0, 0xc4202f73c0)
	/go/src/github.com/rancher/cli/main.go:149 +0x2065
main.main()
	/go/src/github.com/rancher/cli/main.go:37 +0x26

I have been able to get the letschat app from the Quickstart Guide up and running fine on this setup. I would expect the CLI to complain about missing stuff, rather than just segfault like this.

**Comment by joshwget** [comment]
Can you give an example `docker-compose.yml`/`rancher-compose.yml` that can reproduce this?

**Comment by drzero42** [comment]
I experimented a bit, and found it that it was related to named volumes in docker-compose.yml. The problem was observed on rancher-compose 0.12.1. I just updated to 0.12.3 and the problem seems to be gone. Issue closed :)

**Comment by drzero42** [comment]
For future reference, I believe this bug was related to a bug in libcompose: https://github.com/docker/libcompose/issues/430
