### ISSUE TITLE
[ipsec] router logs have repeated message about - "querying policy failed: No such file or directory"

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#7571]
**NOTE: There is no  functional impact of these messages on the regular operations of ipsec.**  

Rancher server version - v1.4.0-rc3
ipsec template version: v0.0.4(rancher/net:v0.8.6)

Steps to reproduce the problem:
Deploy few services

ipsec-ipsec-router-1 logs have repeated message about - "querying policy failed: No such file or directory" :

```
1/26/2017 1:49:11 PM16[KNL] querying policy failed: No such file or directory (2)
1/26/2017 1:49:11 PM16[IKE] sending keep alive to 104.198.249.177[4500]
1/26/2017 1:49:11 PM09[KNL] querying policy failed: No such file or directory (2)
1/26/2017 1:49:11 PM09[IKE] sending keep alive to 35.184.95.198[4500]
1/26/2017 1:49:11 PM10[KNL] querying policy failed: No such file or directory (2)
1/26/2017 1:49:11 PM10[IKE] sending keep alive to 35.184.95.198[4500]
1/26/2017 1:49:11 PM15[KNL] querying policy failed: No such file or directory (2)
1/26/2017 1:49:11 PM15[IKE] sending keep alive to 104.198.249.177[4500]
1/26/2017 1:49:11 PM16[KNL] querying policy failed: No such file or directory (2)
1/26/2017 1:49:11 PM16[IKE] sending keep alive to 104.198.249.177[4500]
1/26/2017 1:49:11 PM09[KNL] querying policy failed: No such file or directory (2)
1/26/2017 1:49:11 PM09[IKE] sending keep alive to 35.184.95.198[4500]
1/26/2017 1:49:11 PM10[KNL] querying policy failed: No such file or directory (2)
1/26/2017 1:49:11 PM10[IKE] sending keep alive to 35.184.95.198[4500]
1/26/2017 1:49:11 PM15[KNL] querying policy failed: No such file or directory (2)
1/26/2017 1:49:11 PM15[IKE] sending keep alive to 104.198.249.177[4500]
1/26/2017 1:49:11 PM16[KNL] querying policy failed: No such file or directory (2)
1/26/2017 1:49:11 PM16[IKE] sending keep alive to 104.198.249.177[4500]
1/26/2017 1:49:11 PM09[KNL] querying policy failed: No such file or directory (2)
1/26/2017 1:49:11 PM09[IKE] sending keep alive to 35.184.95.198[4500]
1/26/2017 1:49:11 PM10[KNL] querying policy failed: No such file or directory (2)
1/26/2017 1:49:11 PM10[IKE] sending keep alive to 35.184.95.198[4500]
1/26/2017 1:49:11 PM15[KNL] querying policy failed: No such file or directory (2)
1/26/2017 1:49:11 PM15[IKE] sending keep alive to 104.198.249.177[4500]
1/26/2017 1:49:11 PM16[KNL] querying policy failed: No such file or directory (2)
```

**Comment by JerryVerhoef** [comment]
We are experiencing some problems which might be caused by this bug. We have similar entries in our logs. We also opened a forum topic https://forums.rancher.com/t/ipsec-network-fails-silently-on-a-host/5471/3 (this was before we were aware of this ticket)

**Comment by dionisiolopez** [comment]
We are experiencing the same issue with the same log messages.

**Comment by salvax86** [comment]
We also have the same issue (on 1.3 too) but only the tunnels, where traffic is relative heavy, are randomly going down

**Comment by iDiogenes** [comment]
@salvax86 what version of docker engine are you running? I though I had the same issue as stated here, but mine was only the tunnels as well. It occurred to me that the issue started happening after I updated my version of CoreOS from one running docker 1.12.3 to 1.12.6. Once I rolled back to 1.12.3 my IPSec troubles stopped. If you look at the change log for docker engine 1.12.4 there are a lot of network changes, so it is possible something was introduced that caused the tunnels to be less stable.

**Comment by salvax86** [comment]
@iDiogenes we have at the moment 1.12.6. We look for a downgrade. Thanks for the advice

**Comment by iDiogenes** [comment]
@salvax86 - Please let me know your outcome after the downgrade.

**Comment by kimgust** [comment]
```

Feb 22 20:49:29 5eced91dec35 r-ipsec-ipsec-router-2-b5028e04:  08[KNL] querying policy failed: No such file or directory (2)
Feb 22 20:49:29 5eced91dec35 r-ipsec-ipsec-router-2-b5028e04:  08[KNL] unable to query policy 0.0.0.0/0 === 0.0.0.0/0 out
Feb 22 20:49:29 5eced91dec35 r-ipsec-ipsec-router-2-b5028e04:  08[KNL] querying SAD entry with SPI c2b9ecaf
Feb 22 20:49:29 5eced91dec35 r-ipsec-ipsec-router-2-b5028e04:  08[KNL] sending XFRM_MSG_GETSA 28597: => 40 bytes @ 0x7f4ec7102800
```
```
kim@docker1:~$ docker --version
Docker version 1.12.1, build 23cf638
```
```
kim@docker1:~$ fgrep VERSION= /etc/os-release
VERSION="14.04.4 LTS, Trusty Tahr"
```

rancher/server:v1.3.0
rancher/net:v0.8.1

**Comment by teamon** [comment]
I'm getting the same error messages with rancher 1.4.1

#### Rancher Server
```
OS: Ubuntu 16.04.2 LTS (Xenial Xerus)
Docker: 1.12.6
Image: rancher/server:stable (a00ee3070422)
```

#### Rancher Hosts
```
OS: CoreOS 1235.9.0
Docker: 1.12.6
Image: rancher/net:v0.8.7
```

#### rancher/net logs (host IPs masked) 

```
27/02/2017 19:26:0609[IKE] sending keep alive to A.A.A.A[4500]
27/02/2017 19:26:0610[KNL] querying policy failed: No such file or directory (2)
27/02/2017 19:26:0610[IKE] sending keep alive to B.B.B.B[4500]
27/02/2017 19:26:0613[KNL] querying policy failed: No such file or directory (2)
27/02/2017 19:26:0613[IKE] sending keep alive to B.B.B.B[4500]
27/02/2017 19:26:0614[KNL] querying policy failed: No such file or directory (2)
27/02/2017 19:26:0614[IKE] sending keep alive to C.C.C.C[4500]
27/02/2017 19:26:0609[KNL] querying policy failed: No such file or directory (2)
27/02/2017 19:26:0609[IKE] sending keep alive to D.D.D.D[4500]
27/02/2017 19:26:0606[KNL] querying policy failed: No such file or directory (2)
```

We've set up a new cluster with rancher 1.4.1 mostly because of networking issues with rancher 1.1 (and upgrade was not an option) and we've planned to switch to new cluster today, but now I am not sure about the stability of networking. However the system seems to be functioning properly, so the question is should we worry about this and can it be ignored?

**Comment by leodotcloud** [comment]
@teamon These messages do not have an impact on the regular operations of ipsec, otherwise this issue would have been marked "blocker" by our QA team. I haven't gotten a chance to debug this issue further yet.

Please go ahead with your cluster setup, you should be fine.

**Comment by teamon** [comment]
@leodotcloud thanks for that! 

Btw, I have tried to add RANCHER_DEBUG=true and upgrade the ipsec stack - this ended up with total disaster and all hosts lockdown - can't ssh. In the VNC console I see `unregistered_netdevice: waiting for lo to become free` error messages. So, I'm setting up everything from scratch just now. 

Is the ipsec stack basically unupgradable?

**Comment by teamon** [comment]
Anyway, with just three hosts and little to no traffic I get this.

```
08[KNL] querying policy failed: No such file or directory (2)
08[KNL] unable to query policy 0.0.0.0/0 === 0.0.0.0/0 out
08[KNL] querying SAD entry with SPI c2b7be35
08[KNL] sending XFRM_MSG_GETSA 273: => 40 bytes @ 0x7fb3527fb800
...
08[KNL] received XFRM_MSG_NEWSA 273: => 380 bytes @ 0x7fb3340008f0
...
08[IKE] sending keep alive to X.X.X.X[4500]
08[MGR] checkin IKE_SA conn-X.X.X.X[2]
08[MGR] checkin of IKE_SA successful
04[NET] sending packet: from 10.42.169.61[4500] to X.X.X.X[4500]
10[MGR] checkout IKEv2 SA with SPIs fde673ec1779f879_i 0000000000000000_r
10[MGR] IKE_SA conn-A.A.A.A[3] successfully checked out
10[IKE] retransmit 5 of request with message ID 0
10[NET] sending packet: from 10.42.169.61[500] to A.A.A.A[500] (500 bytes)
10[MGR] checkin IKE_SA conn-A.A.A.A[3]
10[MGR] checkin of IKE_SA successful
04[NET] sending packet: from 10.42.169.61[500] to A.A.A.A[500]
03[NET] received packet => 448 bytes @ 0x7fb35974d520
...
12[KNL] querying policy failed: No such file or directory (2)
12[KNL] unable to query policy 0.0.0.0/0 === 0.0.0.0/0 out
12[IKE] peer supports MOBIKE
12[IKE] activating new tasks
12[IKE] nothing to initiate
12[MGR] checkin IKE_SA conn-A.A.A.A[3]
12[MGR] checkin of IKE_SA successful
10[MGR] checkout IKEv2 SA with SPIs f0428581ab24f252_i 77eae834938d40d6_r
10[MGR] IKE_SA conn-X.X.X.X[1] successfully checked out
10[KNL] querying policy 0.0.0.0/0 === 0.0.0.0/0 out
...
10[KNL] querying policy failed: No such file or directory (2)
10[KNL] unable to query policy 0.0.0.0/0 === 0.0.0.0/0 out
```

I hope it somehow helps :)

**Comment by leodotcloud** [comment]
@teamon Our QA team members do a lot of "Upgrade" tests specifically trying to make sure any kind of service upgrades do not have problems. @sangeethah @soumyalj can you please confirm?
Is this issue reproducible? Could you please share what steps you followed to hit this issue?

BTW did you do an upgrade from 1.1 to 1.4.1?
What kind of OS and docker version are you using?

Thanks for the logs.

**Comment by teamon** [comment]
No, we didn't upgrade from 1.1 (since upgrading 1.1 to 1.2 mean downtime). We've set up entire infrastructure from ground up, separately, with rancher 1.4.1. 

The failed upgrade happened when I clicked the "up to date" button in ipsec stack, chose the version 0.0.4 (the only one available) and set RANCHER_DEBUG value to true. After that rancher had issues with starting/stopping ipsec containers which eventually led to the error mentioned above. 
After removing all hosts I managed to stabilise it. Then, after adding just three hosts I've checked the ipsec upgrade once again, this time changing RANCHER_DEBUG from true to false and it went smoothly with no issues, so it might have been some one time error before.

As for the versions please see my previous comment - https://github.com/rancher/rancher/issues/7571#issuecomment-282808065

If you need any more information/logs just let me know.

**Comment by leodotcloud** [comment]
@teamon The workflow that you mentioned is something that I use personally and I never had any issue so far though I acknowledge you ran into an issue doing the same.

**Comment by mkulumadzi** [comment]
We recently upgraded our Rancher server to a new host and version 1.4.1 and are also experiencing this issue. Symptoms are that services work after initial launch, but eventually go down due to network failure. router logs have same message reported in this issue:

```
3/7/2017 7:01:57 AM16[KNL] querying policy failed: No such file or directory (2)
3/7/2017 7:01:57 AM16[IKE] sending keep alive to 54.245.4.160[4500]
```

Network manager logs have errors as well:

```
3/7/2017 6:28:49 AMnet.ipv4.conf.docker0.route_localnet = 1
3/7/2017 6:28:57 AMtime="2017-03-07T13:28:57Z" level=info msg="CNI down" cid=fef6cce8f5eb4e0c4ca3ac9f68841b6199ffa8a6b5a7731dfe988d80dbafe07c networkMode=ipsec
3/7/2017 6:28:58 AMtime="2017-03-07T13:28:58Z" level=info msg="Applying new port rules"
3/7/2017 6:28:59 AMtime="2017-03-07T13:28:59Z" level=info msg="Setting up resolv.conf for ContainerId [ede119334be234102189c523f225ab1a558a370ef4082a52379250a8fb758e60]"
```

*Rancher server*
```
Rancher Server: v1.4.1
Docker: 1.13.0-rc4, build 88862e7
Rancher OS: v0.8.1
```

*Hosts*
```
Rancher OS v 0.4.4
Docker:  1.10.3, build 20f81dd
```

Thinking docker version on server might need to be downgraded and/or hosts might need to be upgraded. Any info others have is appreciated though.

**Comment by salvax86** [comment]
Hi
I was on holiday these two weeks. My problem is another one then "querying policy failed: No such file or directory"

@iDiogenes We had the problem already with docker 1.12.3 version (since rancher 1.2)

**Comment by smazurov** [comment]
Have this issue as well. I did upgrade from 1.1 to 1.5. Not 100% certain its not causing issues as I'm seeing weird connectivity problems with etcd cluster from the catalog.

**Comment by hilkeheremans** [comment]
We are also having this issue. I bumped into this error when I was diagnosing issues similar to @mkulumadzi  -- random network failures. 

It's unclear if this is the actual cause for the problem we are having now: at one point today our containers failed to start with 'timeout getting IP address', despite us using the latest infrastructure services (= including network services v0.0.16) available. [We do not have a catchall domain configured as described in #7379]

Docker: 1.12.3
Hosts running Ubuntu 16.04
Rancher Server: v1.4.1

Our servers are now experiencing random connectivity issues resulting in containers going down, unable to restart and as a result, downtime in production.

**Comment by gaieges** [comment]
Seeing something very similar, and I believe this is related to random network connectivity issues reported in #7537

**Comment by jean-francois-labbe** [comment]
I've got the same issue

```
Apr 18 11:59:20 3a8587e999a7 r-ipsec-ipsec-router-2-865cde54:  14[IKE] sending keep alive to 52.211.160.yyy[4500]
Apr 18 11:59:20 3a8587e999a7 r-ipsec-ipsec-router-2-865cde54:  16[KNL] querying policy failed: No such file or directory (2)
Apr 18 11:59:26 3bfbadc34b11 r-ipsec-ipsec-router-7-b8579788:  07[IKE] sending keep alive to 52.215.44.xxx[4500]
Apr 18 11:59:26 3bfbadc34b11 r-ipsec-ipsec-router-7-b8579788:  10[KNL] querying policy failed: No such file or directory (2)
```

How can we fix this?

**Comment by LoicMahieu** [comment]
Same logs here.
```
Docker version 1.12.6, build 78d1802
rancher/server:v1.6.0
ipsec stack: v0.1.0
kubernetes stack: v1.5.4-rancher1-4.1
```

I have random networking issue specially when downloading files from S3.

**Comment by superseb** [comment]
Thanks for reporting, please see the note at the bottom of this issue: **NOTE: There is no functional impact of these messages on the regular operations of ipsec.**

Please search the issues (and emoji +1) or create a new issue with the info needed to help you out.

**Comment by hongxiaolu** [comment]
Hi, I also had a similar problem, 
docker:1.12.3 
rancher server:1.6.2 
rancher/scheduler:v0.8.0 
rancher/network-manager:v0.7.1 
rancher/dns:v0.15.1 
rancher/healthcheck:v0.3.1 
rancher/net:v0.11.2 
rancher/agent:v1.2.2 
rancher/metadata:v0.9.1 
rancher/net:holder

the IPSec-route log:
017/10/16 下午4:36:3609[KNL] querying policy failed: No such file or directory (2)
2017/10/16 下午4:36:3609[IKE] sending keep alive to 10.100.136.104[1024]
2017/10/16 下午4:36:3614[KNL] querying policy failed: No such file or directory (2)
2017/10/16 下午4:36:3614[IKE] sending keep alive to 10.100.136.107[1024]
2017/10/16 下午4:36:3610[KNL] querying policy failed: No such file or directory (2)
2017/10/16 下午4:36:3610[IKE] sending keep alive to 10.100.17.157[4500]
2017/10/16 下午4:36:3607[KNL] querying policy failed: No such file or directory (2)
2017/10/16 下午4:36:3607[IKE] sending keep alive to 10.100.17.161[4500]
2017/10/16 下午4:36:3604[KNL] querying policy failed: No such file or directory (2)
2017/10/16 下午4:36:3604[IKE] sending keep alive to 10.100.136.104[4500]
2017/10/16 下午4:36:3608[KNL] querying policy failed: No such file or directory (2)
2017/10/16 下午4:36:3608[IKE] sending keep alive to 10.100.17.156[4500]
2017/10/16 下午4:36:3611[KNL] querying policy failed: No such file or directory (2)
2017/10/16 下午4:36:3611[IKE] sending keep alive to 10.100.136.108[1024]
2017/10/16 下午4:36:3606[KNL] querying policy failed: No such file or directory (2)
2017/10/16 下午4:36:3606[IKE] sending keep alive to 10.100.17.157[1025]
2017/10/16 下午4:36:3605[KNL] querying policy failed: No such file or directory (2)
2017/10/16 下午4:36:3605[IKE] sending keep alive to 10.100.17.164[4500]
2017/10/16 下午4:36:3603[KNL] querying policy failed: No such file or directory (2)
2017/10/16 下午4:36:3603[IKE] sending keep alive to 10.100.17.165[4500]
2017/10/16 下午4:36:3613[KNL] querying policy failed: No such file or directory (2)
2017/10/16 下午4:36:3613[IKE] sending keep alive to 10.100.136.105[1024]
2017/10/16 下午4:36:3612[KNL] querying policy failed: No such file or directory (2)
2017/10/16 下午4:36:3612[IKE] sending keep alive to 10.100.136.103[1024]
2017/10/16 下午4:36:3609[KNL] querying policy failed: No such file or directory (2)
2017/10/16 下午4:36:3604[KNL] querying policy failed: No such file or directory (2)
2017/10/16 下午4:36:3609[IKE] sending keep alive to 10.10

**Comment by leodotcloud** [comment]
The log is being printed from the following line in file `src/libcharon/plugins/kernel_netlink/kernel_netlink_ipsec.c`:

```
2595                 case NLMSG_ERROR:
2596                 {
2597                     struct nlmsgerr *err = NLMSG_DATA(hdr);
2598                     DBG1(DBG_KNL, "querying policy failed: %s (%d)",
2599                          strerror(-err->error), -err->error);
2600                     break;
2601                 }
```

Currently the log level in rancher/ipsec is set to `1`.

Reading through the code, for every ipsec connection, charon is periodically trying to find if there was any traffic destined to a policy with the given traffic selector ... in Rancher's use case, ipsec polices are managed outside of charon. Due to this, every time there is a policy lookup, it fails and the debug message is printed.

```
Thread 4 "charon" hit Breakpoint 1, query_policy (this=0x662640, id=0x7fbc5590cc70, data=0x7fbc5590cc98, use_time=0x7fbc5590cc98) at kernel_netlink_ipsec.c:2598
2598    in kernel_netlink_ipsec.c
(gdb) bt
#0  query_policy (this=0x662640, id=0x7fbc5590cc70, data=0x7fbc5590cc98, use_time=0x7fbc5590cc98) at kernel_netlink_ipsec.c:2598
#1  0x00007fbc5bdbf814 in query_policy (this=0x637e80, id=0x7fbc5590cc70, data=0x7fbc5590cc98, use_time=0x7fbc5590cc98) at kernel/kernel_interface.c:492
#2  0x00007fbc5bdc8cb7 in update_usetime (this=0x7fbc3c006660, inbound=true) at sa/child_sa.c:570
#3  0x00007fbc5bdc8e6c in get_usestats (this=0x7fbc3c006660, inbound=true, time=0x7fbc5590cd60, bytes=0x0, packets=0x0) at sa/child_sa.c:623
#4  0x00007fbc5bdcbab7 in get_use_time (this=0x7fbc38000ec0, inbound=true) at sa/ike_sa.c:340
#5  0x00007fbc5bdccbb0 in send_dpd (this=0x7fbc38000ec0) at sa/ike_sa.c:771
#6  0x00007fbc5bdc65e4 in execute (this=0x7fbc28000e60) at processing/jobs/send_dpd_job.c:57
#7  0x00007fbc5c088036 in process_job (this=0x6355d0, worker=0x66cac0) at processing/processor.c:235
#8  0x00007fbc5c088338 in process_jobs (worker=0x66cac0) at processing/processor.c:321
#9  0x00007fbc5c09f82a in thread_main (this=0x66cc70) at threading/thread.c:331
#10 0x00007fbc5b8656ba in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#11 0x00007fbc5b39782d in clone () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) detach
```

**Comment by EugenMayer** [comment]
@leodotcloud while this is printed, thats not only some debug line without any effect.

The connection is lost periodically, again and again.

**Comment by superseb** [comment]
@EugenMayer Please search the issues or open a new one, this issue is regarding fixing the noisy error messages and not any functional impact. There have been a lot of fixes in the latest releases, if you still encounter issues, please file a new issue with steps to reproduce so we can investigate.

**Comment by sangeethah** [comment]
Tested with rancher server version - v1.6.15-rc1 with rancher/net:v0.13.9.

Error logs mentioned in this issue is not seen anymore in router logs.
