### ISSUE TITLE
Wildcard SNI loadbalancing - haproxy configuration

### ISSUE THREAD

**Issue by svensp** [rancher/rancher#7576]
**Rancher Versions:**
Server: 1.3.1
healthcheck: 0.2.0
ipsec: 0.8.1
network-services: metadata:v0.7.0 network-manager:v0.4.0
scheduler: scheduler:v0.5.1
kubernetes (if applicable): -

The SNI loadabalancing rule `*.example.com` is translated into `req_ssl_sni -i example.com` using the LB Interface with haproxy.
It should be `req.ssl_sni -m example.com` according to http://stackoverflow.com/questions/24839318/haproxy-reverse-proxy-sni-wildcard

We'd like to use the SNI Loadbalancing to cascade test and production domains to different loadbalancers: 
- *.test.example.com -> Test-LB
- *.example.com -> Production-LB
so having to add every subdomain to the SNI loadbalancer makes for (unnecessary) double administration effort

**Comment by PhilippeGeek** [comment]
Any news about that issue ?

**Comment by PhilippeGeek** [comment]
This part of code should be edited, but I don't know how: https://github.com/rancher/lb-controller/blob/master/provider/haproxy/config/haproxy_template.cfg#L32

**Comment by PhilippeGeek** [comment]
@aemneina Any news about this?

**Comment by zmetcalf** [comment]
+1

**Comment by wtayyeb** [comment]
@alena1108 could you please tell us if this issue will resolved in next version?

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
