### ISSUE TITLE
When service that was scaled up and then scaled down , is deactivated/activated, UI shows the previously "purged" instances in "running" state.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#758]
Server Version - V0.19.2

Steps to reproduce the problem:

Created a service with scale 2.
Scale up to 5.
Scale down to 2 , so that there are 3 instances in "Purged" state.

Deactivate this instance.
UI shows the existing 2 instances being stopped . But notice that the 3 instances that were in "Purged" state also show up in the UI.
If you refresh the UI , the purged instances are not shown anymore.

The same behavior is also seen when the de activated instance is activated.
 
mysql> select id,name,state from instance where name like "%test1_test2_%";     
+-----+---------------+---------+
| id  | name          | state   |
+-----+---------------+---------+
| 167 | test1_test2_1 | running |
| 168 | test1_test2_2 | running |
| 169 | test1_test2_3 | purged  |
| 170 | test1_test2_4 | purged  |
| 171 | test1_test2_5 | purged  |
+-----+---------------+---------+
5 rows in set (0.00 sec)

![screen shot 2015-05-08 at 7 48 09 pm](https://cloud.githubusercontent.com/assets/4266958/7548384/40de132c-f5bb-11e4-8aa5-212c5c7f24ab.png)

**Comment by vincent99** [comment]
@tfiduccia Can you recheck this, I assume it doesn't apply anymore..

**Comment by tfiduccia** [comment]
Version - master jan 07
This is no longer applicable.  The container count is correct and individual containers do not show up anymore
