### ISSUE TITLE
[FEATURE REQUEST] Add server's reported version in the High Availability page

### ISSUE THREAD

**Issue by johnrengelman** [rancher/rancher#7580]
Current version 1.3.2

Would be nice to have the server's reported version displayed along with the other clustering information. Have seen some instances were a cluster was built up with one server having a different version (v1.3.0) (which didn't seem to cause problems).

**Comment by aemneina** [comment]
Doesnt look like the server versions are returned using `/v2-beta/clustermemberships`

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
