### ISSUE TITLE
Auth framework should invalidate session tokens on logout/timeout

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#7581]
Expected behavior:

1. There should be a timeout for user sessions
2. On user logout or timeout the session token should be invalidated

Actual behavior:
1. Sessions don't time out
2. Session token is not invalidated on logout and can be reused to gain access

Based on discussion with @vincent99 
/cc @prachidamle

**Comment by mrajashree** [comment]
When access control is configured or any user logs in, a token is generated for the user. This token can be provided in cookies for sending requests after auth is turned on. Once the user logs out, this token should be deleted so as to avoid token misuse. So current code stores multiple tokens in db for each user depending on the number of times the user logs in/out. Any of these tokens for a user can be used till they expire (by default they expire after 16 hours). With the enhancement, only one token per user can be used to gain access. User logout will call DELETE api on /token.

**Comment by galal-hussein** [comment]
@mrajashree I was able to validate that i can't reuse the token after the DELETE request to the current token:
```
➜  ~ curl -XDELETE -H "Cookie: token=XbzXPfsGL5UYa5VDqSr7yJ2qEdWUmmFeeXo3cFaJ" http://x.x.x.x:8080/v2-beta/token/current
➜  ~ curl -H "Cookie: token=XbzXPfsGL5UYa5VDqSr7yJ2qEdWUmmFeeXo3cFaJ" http://x.x.x.x:8080 -IL
HTTP/1.1 401 Unauthorized
Content-Type: application/json; charset=utf-8
Date: Thu, 20 Apr 2017 17:20:13 GMT
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Server: Jetty(9.2.11.v20150529)
Set-Cookie: PL=rancher;Path=/
Www-Authenticate: Basic realm="Enter API access key and secret key as username and password"
X-Api-Schemas: http://104.154.70.220:8080/v1/schemas
```

however the UI logout doesn't work as expected and i can reuse the tokens after logout from the UI.

**Comment by mrajashree** [comment]
@galal-hussein thanks, the UI for this isn't done yet. Since you've tested the api call I'll assign it to @vincent99

**Comment by tfiduccia** [comment]
version - master 4/26
verified fixed
