### ISSUE TITLE
Stack Reports Up to Date but Custom Catalog has Higher Versions

### ISSUE THREAD

**Issue by kareed44** [rancher/rancher#7582]
**Rancher Versions:**
Server: 1.3.2

**Docker Version:**
1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 14.04 LTS, AWS EC2

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher with external host agent

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

After upgrading to rancher server version 1.3.2, a few of our existing stacks that had available upgrades now report "up to date". If you browse to the catalog there are higher versions available, however if you click on the "up to date" link it brings you to an upgrade page with only the current version in the drop down.

Thoughts?

**Comment by vincent99** [comment]
Without seeing the catalog, my first guess would be the versions that don't show up have `min_rancher_version`  and/or `max_rancher_version` that are not satisfied by 1.3.2.

**Comment by kareed44** [comment]
Thanks for the response vincent. Would these attributes be in the rancher_compose definition? We do not explicitly set those in there.

**Comment by vincent99** [comment]
They go in the `.catalog`/`catalog` section (along with question definitions) and can technically be in either file.

Also depending on what version you're upgrading from, at some point between 1.1 and 1.2 we switched from considering any higher folder number an "upgrade" to semver comparison of the version of the templates vs the one currently installed.  So those versions need to be a) present and b) increasing.

**Comment by kareed44** [comment]
In both working (says upgrade available) and non working stacks (says "up to date") the version attribute is defined in rancher compose in the .catalog section:

Working (deployed version = 0.14.43):
**.catalog:
  name: "test-stack"
  version: "0.15.45"
  description: "blah blah"
  uuid:**

Not Working (deployed version = 1.1.0.96):
**.catalog:
  name: "AnotherTestStack"
  version: "1.1.0.116"
  description: "blah blah"
  uuid:**

**Comment by kareed44** [comment]
In addition, if we deploy the same version of that stacks that wont show up as potential upgrade targets, the questions are not flowing through to the environment variables in the container. Is it fair to say this is a stack definition issue despite the fact that the catalog load process does not complain about them?

**Comment by kareed44** [comment]
https://github.com/rancher/rancher-catalog-service/blob/master/manager/catalog_manager.go

In this manager,  the 4th position of the version is ignored in getVersionFromRancherCompose(). I find it misleading that the catalog entry would load without warning when part of the version is ignored in comparisons.

**Comment by vincent99** [comment]
[Semver](http://semver.org/)  is `major.minor.patch` only.

**Comment by kareed44** [comment]
Thanks for that info. Perhaps there is some way to make this clear to the end user. While browsing a catalog with 4 part versions it's not clear that 1.0.0.1 can't be upgraded to 1.0.0.2. Just a thought... to prevent the same confusion I went through, even if it was partly due to my own ignorance.
