### ISSUE TITLE
ipsec containers fail to start.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#7586]
Rancher Versions: v1.4.0-rc3

Steps to reproduce the problem:
Set up with 3 hosts.

Ipsec service is stuck in "Activating" state forever.
ipsec and router containers keeping getting into "error" state and constantly attempting to get recreated.

**Comment by kareed44** [comment]
We see the ipsec router restart issue in 1.3.2. It only occurs in one environment. When we clean and join the host to another environment it works as expected.

**Comment by leodotcloud** [comment]
@kareed44 This particular issue has been caused by a bad build. Please feel free to file a different issue and share your logs/findings. (Logs from network-service containers and ipsec containers)

**Comment by sangeethah** [comment]
Rancher Versions: v1.4.0-rc5 and rancher/net:v0.8.7.
Ipsec service is able to start successfully.
