### ISSUE TITLE
[rancher-catalog] 

### ISSUE THREAD

**Issue by fabriziotorelli-wipro** [rancher/rancher#7588]
**Rancher Versions:**
Server: latest
healthcheck: v0.2.0
ipsec: v0.2.0
network-services: v0.2.0
scheduler: v0.2.0
kubernetes (if applicable): 

**Docker Version:**
1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):**
locally (test)

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
RANCHER OS : 0.8.0-rc3
(1) single rancher server node, (2) single slave node

UBUNTU 16.04 :
(3) Single ubuntu slave node, with my nfs server and rancher agent - docker 1.13.0

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
(1)(2) Cattle
(1)(2) Kubernetes
(1)(2) Microsoft
(3) Cattle
(3) Swarm

**Steps to Reproduce:**
Trying to lookup in the rancher catalog -> No Convoy-NFS in the list, but it's in the repo

**Results:** 
I couldn't install ConvoyNFS on Rancher -> RancherOS 0.8.0-rc3

**Comment by deniseschannon** [comment]
Convoy NFS is no longer supported as of v1.2. Instead, we recommend using Rancher NFS.

**Comment by vincent99** [comment]
It is specifically disabled on 1.2+ by setting [maximum_rancher_version](https://github.com/rancher/rancher-catalog/blob/master/templates/convoy-nfs/3/rancher-compose.yml#L5)
