### ISSUE TITLE
Load balancer logs are empty - error during parsing file /etc/haproxy/rsyslogd.conf

### ISSUE THREAD

**Issue by jmoscato** [rancher/rancher#7591]
The HAProxy logs in /var/log/haproxy/ are empty in the load balancer container. From the error messages in /var/log/messages it looks like those parenthesis on the if-then lines in rsyslogd.conf should be curly braces. Please see the example at the end of this page: [RSYSLOG if then](http://www.rsyslog.com/tag/if-then/)

Also see recent comments in [issue 2414](https://github.com/rancher/rancher/issues/2414).

**Rancher Versions:**
Server: v1.4.0-rc5 (also in v1.3.3)
healthcheck: v0.2.3
ipsec: holder
network-services: ?
scheduler: v0.6.1
kubernetes (if applicable): n/a

**Docker Version:**
1.13.0

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04, bare metal

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher, internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
* fresh install of Rancher server
* add a host
* create a new stack in the default environment
* add a service (rawmind/web-test for example)
* add a load balancer and configure a port with its target pointing to the service
* make some requests to the load balancer's port

**Results:** 

Navigate to load balancer container in rancher ui and select Execute Shell

haproxy logs:
```
root@8d303d0449d6:/# ls -l /var/log/haproxy/
total 0
-rw-r--r-- 1 root root 0 Jan 24 22:27 errors
-rw-r--r-- 1 root root 0 Jan 24 22:27 events
-rw-r--r-- 1 root root 0 Jan 24 22:27 traffic
root@8d303d0449d6:/#
```

/var/log/messages output:
```
root@8d303d0449d6:/# tail -n 50 /var/log/messages
Jan 29 23:13:04 8d303d0449d6 rsyslogd: [origin software="rsyslogd" swVersion="8.
16.0" x-pid="28" x-info="http://www.rsyslog.com"] start
Jan 29 23:13:04 8d303d0449d6 rsyslogd-2207:error during parsing file /etc/haprox
y/rsyslogd.conf, on or before line 7: invalid character '(' - is there an invali
d escape sequence somewhere? [v8.16.0 try http://www.rsyslog.com/e/2207 ]
Jan 29 23:13:04 8d303d0449d6 rsyslogd-2207:error during parsing file /etc/haprox
y/rsyslogd.conf, on or before line 9: invalid character ')' - is there an invali
d escape sequence somewhere? [v8.16.0 try http://www.rsyslog.com/e/2207 ]
Jan 29 23:13:04 8d303d0449d6 rsyslogd-2207:error during parsing file /etc/haprox
y/rsyslogd.conf, on or before line 10: invalid character '(' - is there an inval
id escape sequence somewhere? [v8.16.0 try http://www.rsyslog.com/e/2207 ]
Jan 29 23:13:04 8d303d0449d6 rsyslogd-2207:error during parsing file /etc/haprox
y/rsyslogd.conf, on or before line 12: invalid character ')' - is there an inval
id escape sequence somewhere? [v8.16.0 try http://www.rsyslog.com/e/2207 ]
Jan 29 23:13:04 8d303d0449d6 rsyslogd-2207:error during parsing file /etc/haprox
y/rsyslogd.conf, on or before line 14: invalid character '(' - is there an inval
id escape sequence somewhere? [v8.16.0 try http://www.rsyslog.com/e/2207 ]
Jan 29 23:13:04 8d303d0449d6 rsyslogd-2207:error during parsing file /etc/haprox
y/rsyslogd.conf, on or before line 16: invalid character ')' - is there an inval
id escape sequence somewhere? [v8.16.0 try http://www.rsyslog.com/e/2207 ]
```

haproxy's rsyslogd configuration:
```
root@8d303d0449d6:/# cat /etc/haproxy/rsyslogd.conf
$ModLoad imudp.so
$UDPServerRun 8514
$template CustomFormat,"%timegenerated% %HOSTNAME% %syslogtag%%msg%\n"
$ActionFileDefaultTemplate CustomFormat

/* info */
if $programname contains 'haproxy' and $syslogseverity == 6 then (
    action(type="omfile" file="/var/log/haproxy/traffic")
)
if $programname contains 'haproxy' and $syslogseverity-text == 'err' then (
    action(type="omfile" file="/var/log/haproxy/errors")
)
/* notice */
if $programname contains 'haproxy' and $syslogseverity <= 5 then (
    action(type="omfile" file="/var/log/haproxy/events")
)

*.* /var/log/messages
```

**Comment by ebreton** [comment]
Same issue with image: rancher/lb-service-haproxy:v0.4.9

**Comment by allhaker** [comment]
@jmoscato, I was able to resolve it in my setup by adding this code to rancher-compose.yml

       lb_config:
         certs: []
         config: |-
           global
             log 127.0.0.1:8514 local0

           defaults
             log global
             mode    tcp
             option  tcplog

`log 127.0.0.1:8514 local0` - 8514 is the rsyslog listening port in Rancher's HAProxy container. I think this should be added to the documentation.

**Comment by jmoscato** [comment]
Thanks @allhaker, your solution works for me too!

If I understand correctly, it looks like the rsyslogd.conf errors were unrelated to the empty haproxy log files, but instead it was a matter of needing to configure logging for haproxy itself, right?

Does it make sense to keep this issue open? Or is there a better way to get the documentation updated as you mentioned?

**Comment by vkruoso** [comment]
Had the same problem and @allhaker is right. I would be nice if this could be fixed so we can have the default behavior again.

**Comment by VAdamec** [comment]
Same for rancher/lb-service-haproxy:v0.6.2

```
Mar  8 08:23:14 6cd03af8204d rsyslogd-2207:error during parsing file /etc/haproxy/rsyslogd.conf, on or before line 16: invalid character ')' - is there an invalid escape sequence somewhere? [v8.16.0 try http://www.rsyslog.com/e/2207 ]
```

- /etc/haproxy/rsyslogd.conf

```
$ModLoad imudp.so
$UDPServerRun 8514
$template CustomFormat,"%timegenerated% %HOSTNAME% %syslogtag%%msg%\n"
$ActionFileDefaultTemplate CustomFormat

/* info */
if $programname contains 'haproxy' and $syslogseverity == 6 then (
    action(type="omfile" file="/var/log/haproxy/traffic")
)
if $programname contains 'haproxy' and $syslogseverity-text == 'err' then (
    action(type="omfile" file="/var/log/haproxy/errors")
)
/* notice */
if $programname contains 'haproxy' and $syslogseverity <= 5 then (
    action(type="omfile" file="/var/log/haproxy/events")
)

*.* /var/log/messages
```

**Comment by sra** [comment]
According to the rsyslog docs, the `if` lines should be delimited with curly braces like so:

```
if $programname contains 'haproxy' and $syslogseverity == 6 then {
    action(type="omfile" file="/var/log/haproxy/traffic")
}
```

Changing this in the file and `SIGHUP`ing rsyslog produces no syntax errors.

http://www.rsyslog.com/doc/v8-stable/configuration/basic_structure.html#flow-control-statements

**Comment by tgjamin** [comment]
Any updates on this? I am seeing `Apr  7 19:05:13 dfde93741290 rsyslogd-2207:error during parsing file /etc/haproxy/rsyslogd.conf, on or before line 16: invalid character ')' - is there an invalid escape sequence somewhere? [v8.16.0 try http://www.rsyslog.com/e/2207 ]` in my `rancher/lb-service-haproxy:v0.5.9` containers. All of my logs are empty in `/var/log/haproxy/*`

I also have the same config as others above, such as @VAdamec 
```
$ModLoad imudp.so
$UDPServerRun 8514
$template CustomFormat,"%timegenerated% %HOSTNAME% %syslogtag%%msg%\n"
$ActionFileDefaultTemplate CustomFormat

/* info */
if $programname contains 'haproxy' and $syslogseverity == 6 then (
    action(type="omfile" file="/var/log/haproxy/traffic")
)
if $programname contains 'haproxy' and $syslogseverity-text == 'err' then (
    action(type="omfile" file="/var/log/haproxy/errors")
)
/* notice */
if $programname contains 'haproxy' and $syslogseverity <= 5 then (
    action(type="omfile" file="/var/log/haproxy/events")
)

*.* /var/log/messages
```

**Comment by mbernasocchi** [comment]
Same syntax error and empty logs with 1.6.0 and
```
lb_config:
     config: |-
       defaults
       log 127.0.0.1:8514 local0 debug
```

**Comment by mbernasocchi** [comment]
@superseb is there a way to get logs at the moment at all?

**Comment by mbernasocchi** [comment]
adding 
```
defaults
       log 127.0.0.1:8514 local0 debug
```
in the custom haproxi.cfg field works

**Comment by adamtrousdale** [comment]
I've got this and only this in my custom haproxy.cfg
```
defaults
       log 127.0.0.1:8514 local0 debug
```
but can't see any access logs.

I haven't added anything elsewhere, do I need to?

**Comment by mbernasocchi** [comment]
no, was enougn for me to see the logs in /var/logs/haproxy/traffic in the container

**Comment by obenziane2** [comment]
But i think they're useless if we can't expose them to the host for archiving logs ?

**Comment by claytonsilva** [comment]
Where is source of lb-service-haproxy. 

rsyslog will be fixed switch "(" and ")" for "{" and "}" in rsyslogd "if" sentences.

```
/* info */
if $programname contains 'haproxy' and $syslogseverity == 6 then {
    action(type="omfile" file="/var/log/haproxy/traffic")
}
if $programname contains 'haproxy' and $syslogseverity-text == 'err' then {
    action(type="omfile" file="/var/log/haproxy/errors")
}
/* notice */
if $programname contains 'haproxy' and $syslogseverity <= 5 then {
    action(type="omfile" file="/var/log/haproxy/events")
}
```
i tested in my environment with debug :

```
defaults
       log 127.0.0.1:8514 local0 debug
```

and is there all ok

**Comment by deniseschannon** [comment]
@claytonsilva The source code is located https://github.com/rancher/lb-controller

**Comment by kinarashah** [comment]
A quick summary - 

This issue talks about parsing error user sees in /var/log/messages. Ideally, the logging must be started by user to access rsyslogd logging. 

Which is why this can be confirmed in two steps -
1. Without enabling logging (no changes in custom config) -> /var/log/messages should just show informational messages (eg. start, stop) and no parsing errors. 
A sample message - 
```
Jul 14 19:17:59 ab6118b225bb rsyslogd: [origin software="rsyslogd" swVersion="8.16.0" x-pid="22" x-info="http://www.rsyslog.com"] start
```

/var/log/haproxy/events|errors|traffic should be empty. 

2. After enabling logging -> /var/log/messages as before. /var/log/haproxy/events|errors|traffic should get populated. To enable logging, add the following in the custom configurations of the load balancer - 

```
defaults
log 127.0.0.1:8514 local0 debug
```

**Comment by sangeethah** [comment]
Tested with rancher/server: Build from V1.6 branch
Lb image - rancher/lb-service-haproxy:v0.7.6

Scenario 1:
Create a service
Add a load balancer and configure a port with its target pointing to this service (without enabling logging).
Make some requests to the load balancer's port
No logs are generated for haproxy traffic a.  /var/log/haproxy/events|errors|traffic are empty.


Scenario 2:
Create a service
Add a load balancer and configure a port with its target pointing to this service with following custom config for enabling logs:
```
defaults
log 127.0.0.1:8514 local0 debug
```

Make some requests to the load balancer's port

Haproxy events and traffic related messages get logged in both - /var/log/haproxy/traffic and /var/log/haproxy/events .
https://github.com/rancher/rancher/issues/9369 - logged for redundant logging.

**Comment by djskinner** [comment]
Awesome. Is this documented somewhere?

**Comment by aemneina** [comment]
Add ability to log haproxy to /dev/stdout and stderr for access and error logs

**Comment by randomorder** [comment]
I am running rancher/lb-service-haproxy:v0.7.15 and Rancher Server v.1.6.12 and still cannot get HAProxy to log requests.

I've added the suggested config statements to the custom configuration box:
```
defaults
log 127.0.0.1:8514 local0 debug
```
and restarted / upgraded the load balancer service but log files in /var/log/haproxy/* are still empty

Should this fix be available in the versions that I am currently using?

**Comment by kinarashah** [comment]
@randomorder sometime after this, https://github.com/rancher/rancher/issues/9616, logs from those files were redirected to UI. 
are you able to see events and traffic getting logged in Standard Out and  Errors in Standard Error under "View Logs"?

**Comment by randomorder** [comment]
Hi @kinarashah 
Thanks for your feedback.
I tried to send some requests through the load balancer (a few tens of them) but get  very little information from stderr and stdout:
```
2/15/2018 9:25:24 AMtime="2018-02-15T08:25:24Z" level=info msg=" -- starting haproxy\n * Starting haproxy haproxy\n[WARNING] 045/082523 (41) : config : 'option forwardfor' ignored for proxy 'default' as it requires HTTP mode.\n[WARNING] 045/082523 (42) : config : 'option forwardfor' ignored for proxy 'default' as it requires HTTP mode.\n   ...done.\n"
2/15/2018 9:25:37 AMFeb 15 08:25:37 localhost haproxy[43]: Connect from 10.134.45.21:8750 to 10.42.75.129:443 (443/HTTP)
2/15/2018 9:25:37 AMFeb 15 08:25:37 localhost haproxy[43]: Connect from 10.134.45.21:8752 to 10.42.75.129:443 (443/HTTP)
2/15/2018 9:25:37 AMFeb 15 08:25:37 localhost haproxy[43]: Connect from 10.134.45.21:8747 to 10.42.75.129:443 (443/HTTP)
2/15/2018 9:25:37 AMFeb 15 08:25:37 localhost haproxy[43]: Connect from 10.134.45.21:8748 to 10.42.75.129:443 (443/HTTP)
2/15/2018 9:25:37 AMFeb 15 08:25:37 localhost haproxy[43]: Connect from 10.134.45.21:8751 to 10.42.75.129:443 (443/HTTP)
2/15/2018 9:25:37 AMFeb 15 08:25:37 localhost haproxy[43]: Connect from 10.134.45.21:8749 to 10.42.75.129:443 (443/HTTP)
2/15/2018 9:27:44 AMFeb 15 08:27:44 localhost haproxy[43]: Connect from 10.134.45.21:8765 to 10.42.75.129:443 (443/HTTP)
2/15/2018 9:27:44 AMFeb 15 08:27:44 localhost haproxy[43]: Connect from 10.134.45.21:8766 to 10.42.75.129:443 (443/HTTP)
2/15/2018 9:27:44 AMFeb 15 08:27:44 localhost haproxy[43]: Connect from 10.134.45.21:8767 to 10.42.75.129:443 (443/HTTP)
2/15/2018 9:27:44 AMFeb 15 08:27:44 localhost haproxy[43]: Connect from 10.134.45.21:8768 to 10.42.75.129:443 (443/HTTP)
2/15/2018 9:27:44 AMFeb 15 08:27:44 localhost haproxy[43]: Connect from 10.134.45.21:8769 to 10.42.75.129:443 (443/HTTP)
2/15/2018 9:27:44 AMFeb 15 08:27:44 localhost haproxy[43]: Connect from 10.134.45.21:8770 to 10.42.75.129:443 (443/HTTP)
```
All these messages are reporting is the IP of the machine where the requests are coming from (10.134.45.21) and the IP of the load balancer container (10.42.75.129):

> Connect from 10.134.45.21:8750 to 10.42.75.129:443 (443/HTTP)

But there is no information about connection to the backend containers and status of the requests going through

**Comment by randomorder** [comment]
Solved this by explicitly [setting the log format for the frontends in HAProxy](https://cbonte.github.io/haproxy-dconv/1.7/configuration.html#8.2.3) with  **option httplog**

```
defaults
log 127.0.0.1:8514 local0 debug

frontend 8080
option httplog

frontend 443
option httplog
```
Entries in the log file now look like this:

`5/25/2018 12:20:46 PMMay 25 10:20:46 localhost haproxy[351]: 10.134.45.21:15810 [25/May/2018:10:20:35.465] 443~ 443_application_cluster/123436406cec0b9217672c7306ba9b6f2 9496/0/1/1827/11327 200 1022 - - ---- 6/6/0/1/0 0/0 "GET /application/test? HTTP/1.1"`

With HTTP status, backend name, server name, ecc..
