### ISSUE TITLE
Load balancer session cookie leaks sensitive information (service IP)

### ISSUE THREAD

**Issue by sra** [rancher/rancher#7593]
**Rancher Versions:**
Server: 1.3.3
healthcheck: 0.2.0
network-services:
scheduler: 0.5.1

**Docker Version:**
1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
Rancher OS 0.7.1 on AWS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

Single server external RDS

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Create a rancher load balancer with session sticky settings. and the value of the cookie for the services will be the internal hostname of the service. This is a security vulnerability that is immediately flagged by all enterprise security scanners as information leakage. While it doesn't directly help an attacker because they are non public facing addresses, they do help an attacker who has gained some access via another vector by showing IP addresses to then further probe and attack. 

I noticed this change when the new style LB code happened (which incidentally fixed a ton of our session issues, yay) and then we got flagged by security scanning. 

Maybe it would be possible to go back to the big hash (instance ID?) or whatever the hash was before?

**Results:** 

Cookies should not reveal internal network information to clients.

**Comment by sra** [comment]
UPDATE: I see this has been addressed in an updated version of the lb code by https://github.com/rancher/lb-controller/pull/43

*However* this again broke our site requiring 1 instance. The issue is that ALL services use the same cookie name. In this installation requests from the same "main" application that should have a cookie. Sometimes resources on pages generated by that application get directed to other services in the stack (static images, etc...) and they have the same cookie name with their own cookie values. Bad things happen based on timing. For us, we need the different automatic cookie names but hashed IPs for security - the pull request listed above fixed the hash but removed the cookie-by-service names.

If I could add a cookie via custom config to the one backend, this would be fine, but I have no way to modify the "server..." lines. Thoughts?

**Comment by vincent99** [comment]
You can modify the server line to do whatever you want.  http://docs.rancher.com/rancher/v1.2/en/cattle/adding-load-balancers/#custom-haproxy-configuration
