### ISSUE TITLE
Rollback of infrastructure service gone crazy

### ISSUE THREAD

**Issue by miv** [rancher/rancher#7594]
During UPGRADE of ipsec we did't fully considered how disturbing it will be and after the first host we've pushed rollback. It did't go well:

![image](https://cloud.githubusercontent.com/assets/9864/22422288/a2c5aabc-e6fc-11e6-92a4-55668442dfa7.png)

It's starting and then stopping new versions of ipsec on two hosts. As if it trying to "rollback" to current version, after "rollbacking" one hosts it sees "whoa, what this new version of service doing here - i need to start old version", but starts a new version again.

What are my options? Can it forcefully change state (in db or in api) from rollbacking? Can i remove ipsec and then install again? Or i will need to recreate whole environment?

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.3.3` Cattle: `v0.175.9` UI: `v1.3.5` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`service.containers`|

**Comment by anthonyav** [comment]
Did yoou solved your problem @miv ?

**Comment by miv** [comment]
Nope. I've rolled back rancher server db to known state from a backup (aws rds snapshot) and rancher has restored it's infra services.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
