### ISSUE TITLE
cascaded load balancers forget rules

### ISSUE THREAD

**Issue by svensp** [rancher/rancher#7595]
Load balancers which are cascaded behind other load balancers forget rules when the rule target is upgraded using rolling-upgrade.

**Rancher Versions:**
Server: 1.2.0
healthcheck: healthcheck:v0.1.0
ipsec: net:v0.7.5
network-services: metadata:v0.6.8 plugin-manager:v0.2.12
scheduler: scheduler:v0.4.0
kubernetes (if applicable): -

**Docker Version:**
1.10.3
1.12.1

**OS and where are the hosts located? (cloud, bare metal, etc):**
Debian 8, VHost and Bare metal

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node, external db

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Set up environment load balancer with internal ports
Set up SNI + http frontend loadbalancer with external ports, route to environment load balancer
Set up service using docker-compose.yml and `rancher-compose-0.12.1 up`
Set up loadbalancing from environment load balancer to the new service. Does not matter whether it is service link based or rule based.
Create new version of the service in docker.compose.yml
Start rolling upgrade using `rancher-compose-0.12.1 upgrade OLDSTACK NEWSTACK`

**Results:** 
The loadbalancing rule from the environment load balancer -> SERVICE is gone.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
