### ISSUE TITLE
Rancher CLI : No such container

### ISSUE THREAD

**Issue by ghost** [rancher/rancher#7596]
**Rancher Versions:**
Server: 1.2.0
healthcheck: 0.2.0
ipsec:
network-services:
scheduler:
kubernetes (if applicable): N/A

**Docker Version:** 
Docker version 1.12.3, build 6b644ec

**OS and where are the hosts located? (cloud, bare metal, etc):**
Debian

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Rancher CLI 0.3.0 and Rancher CLI 0.4.1

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
I am trying to run rancher --url $RANCHER_URL_API --access-key $RANCHER_ACCESS_KEY --secret-key $RANCHER_SECRET_KEY exec -i -t <rancher_id> ls from my Gitlab CI pipeline

Please note that the RANCHER_URL_API is https and not http as the server doesn't accept traffic on http

**Results:** 
Error response from daemon: No such container: aaaaaaaaaaaa

**Comment by sra** [comment]
See #7513

**Comment by dchambon** [comment]
Is there any update on this one? I have exactly the same issue and in my environment, none of the workaround mentioned in #7513 work.

**Comment by tecbird** [comment]
here exactly the same

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
