### ISSUE TITLE
wrong representation of found pods by kubernetes replica sets

### ISSUE THREAD

**Issue by Dmitry1987** [rancher/rancher#7598]
**Rancher Versions:**
Server: 1.3.1
kubernetes (if applicable):1.5.1   latest update that was available
**OS and where are the hosts located? (cloud, bare metal, etc):**
AWS
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
3 nodes HA, external DB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes
**Steps to Reproduce:**
shut down and delete all worker nodes in environment. then create new hosts and attach to environment.
**Results:** 
plenty of pods, old and new, displayed in "deployment" / "replica sets" ,  but dashboard says "3/0 up" or similar.

![image](https://cloud.githubusercontent.com/assets/9369080/22433867/87300272-e722-11e6-8adc-8faf5da39eef.png)

some kind of UI bug where dashboard representation is wrong. happened after i closed all spotinst worker nodes with running pods, and started new servers (old servers were DELETED, and new CREATED, not same hosts).  probably also Kubernetes bug, where it thinks it has so many live pods  (ALL those pods and containers are shown as ALIVE and ready in Rancher -  but are all **nonexistent** containers!)

![image](https://cloud.githubusercontent.com/assets/9369080/22434132/8edc3508-e723-11e6-9482-92477d5f64e1.png)

P.S. one thing to learn from this:  never turn off all your worker minions on kubernetes :)  
P.S.2. It was kinda disaster recovery test, to know if masters will reschedule the correct pods after new worker nodes come back and cluster can be recovered.  well the test failed i guess? :)

**Comment by aemneina** [comment]
etcd docker volume still present on recycled hosts. See here https://docs.rancher.com/rancher/v1.5/en/kubernetes/deleting/#cleaing-up-persistent-data
