### ISSUE TITLE
Azure AD integration doesn't work when directory is ADFS-integrated

### ISSUE THREAD

**Issue by trondhindenes** [rancher/rancher#7601]
**Steps to Reproduce:**
ADFS-integrated directories require that the client application redirect the client to Azure AD (which again will redirect the user to the correct adfs endpoint in order to authenticate). When using the "regular" auth api's for Azure AD all this is builtin and handled by the default client flow.

However, it looks as if rancher doesn't do this, since it never redirects the client to azure ad - which means that Azure AD integration won't be guaranteed to work.

I would ask that the Azure AD integration is rewritten so that it complies with the standard Azure AD auth flows, which in turn will allow the usage of adfs-backed Azure AD Directories.

**Comment by trondhindenes** [comment]
probably same root cause as #5772

**Comment by trondhindenes** [comment]
and #5952

**Comment by aemneina** [comment]
we can track with #5772
