### ISSUE TITLE
Instances of a service continue to remain in "stopped" state after host in which it was running was powered down and then powered on.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#7604]
Tested with Rancher Version - v1.4.0-rc5

Set up has 3 hosts with Docker Version: 1.12.6

Deploy "policy-manager" from catalog - https://github.com/leodotcloud/test-policy-manager.
Set defaultPolicyAction to "Deny" and policy to {"type":"networkPolicyRule","action":"allow","within":"stack"} to allow for traffic within stacks to succeed but cross stack traffic to be restricted.

Have 1 stacks with few services that are not health check enabled.
Power down one of the host where some of the service instances (that are not health check enabled) is running.
Instances are shown as being in "running" state when host goes from "active"->"reconnecting"->"disconnected" .

Power on the host.
When host gets to "active" state , instances get marked as being in "stopped" state.

service reconcile does not get triggered and Instances of this service continue to remain in "stopped" state 

<img width="1530" alt="screen shot 2017-01-30 at 3 27 35 pm" src="https://cloud.githubusercontent.com/assets/4266958/22446297/bf0d1292-e700-11e6-9745-c0c478dddb88.png">

<img width="1526" alt="screen shot 2017-01-30 at 3 27 44 pm" src="https://cloud.githubusercontent.com/assets/4266958/22446311/c9bca05e-e700-11e6-955b-e9ce2badb15b.png">

**Comment by alena1108** [comment]
@ibuildthecloud looks like some race condition, need your help to figure out what is going on. Given the service log's last line, the update came via config update (triggered by instance.stop), and scheduleOnly was passed as true to the "deploy" call:

https://github.com/rancher/cattle/blob/master/code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/DeploymentManagerImpl.java#L292

But when I look at the process_instance table, the process exited on "REQUESTED" state with "ALREADY_DONE" reason:

```
mysql> select process_name, start_time, end_time from process_instance where resource_id=137 and resource_type='service';
+------------------+---------------------+---------------------+
| process_name     | start_time          | end_time            |
+------------------+---------------------+---------------------+
| service.create   | 2017-01-30 21:49:30 | 2017-01-30 21:49:30 |
| service.activate | 2017-01-30 21:49:30 | 2017-01-30 21:49:53 |
| service.update   | 2017-01-30 21:58:01 | 2017-01-30 21:58:01 |
+------------------+---------------------+---------------------+
3 rows in set (0.01 sec)



mysql> select * from process_instance where id=16848;
+-------+---------------------+---------------------+------+----------+----------------+---------------+-------------+---------+--------------+-----------+-------------------------+---------------------------+-----------------+---------------------+------------+
| id    | start_time          | end_time            | data | priority | process_name   | resource_type | resource_id | result  | exit_reason  | phase     | start_process_server_id | running_process_server_id | execution_count | run_after           | account_id |
+-------+---------------------+---------------------+------+----------+----------------+---------------+-------------+---------+--------------+-----------+-------------------------+---------------------------+-----------------+---------------------+------------+
| 16848 | 2017-01-30 21:58:01 | 2017-01-30 21:58:01 | {}   |        0 | service.update | service       | 137         | SUCCESS | ALREADY_DONE | REQUESTED | 172.17.0.2              | NULL                      |               0 | 2017-01-30 21:53:01 |          5 |
+-------+---------------------+---------------------+------+----------+----------------+---------------+-------------+---------+--------------+-----------+-------------------------+---------------------------+-----------------+---------------------+------------+
1 row in set (0.00 sec)
```
