### ISSUE TITLE
Secret Management: Can't mount the secret inside the container

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#7607]
**Rancher Versions:**
Server: v1.4.0-rc5
healthcheck: v0.2.3
ipsec: rancher/net:v0.8.7
network-services: rancher/network-manager:v0.4.5
scheduler:rancher/scheduler:v0.6.1
kubernetes (if applicable):

**Docker Version:**
1.12
**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node Rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
- Run the secret catalog driver.
- Create a new secret.
- Create a new container and specify the secret you just created with any name.

**Results:** 
The secret is not mounted under /run/secrets/`name` however the secret driver is showing the following error:

```
1/30/2017 8:58:04 PMtime="2017-01-30T18:58:04Z" level=error msg="Unsuccessful request: 500 Internal Server Error"
1/30/2017 8:58:04 PMtime="2017-01-30T18:58:04Z" level=info msg=mount.response mountpoint="/var/lib/rancher/volumes/rancher-secrets/872b4eb3d9bbbce9b2ee2e694cb57f16011b04485923753b421fdd5ad2184622"
```

**Comment by cloudnautique** [comment]
The next release of the agent will have the key fix.

**Comment by galal-hussein** [comment]
on v1.4.0-rc6, whenever i try to add a secret to a container, i am getting the following error

`Error (Scheduling failed: volume [73] must be one of pool(s) [4], valid host(s) [1])`

**Comment by sangeethah** [comment]
This issue is seen when  attempting to create container with secrets in a set up with more than 1 host where we see the container fail to start with  ```Error (Scheduling failed: volume [73] must be one of pool(s) [4], valid host(s) [1])``` error.

Subsequent attempt to create another container with secrets may succeed, if it ends up 
ends up in 1 particular host (not sure which one) in the setup . After this , we are able to create multuple containers with secrets successfully as long as these containers land on this 1 host.

**Comment by sangeethah** [comment]
Tested with rancher-server version - v1.4.0-rc8

Had a rancher-server setup with 3hosts.

Able to start containers with secrets on all 3 hosts of the setup. Also able to access the secrets from with in the container.

**Comment by galal-hussein** [comment]
Rancher version 1.4.0-rc8

steps:

- Register 3 agents with Rancher
- create a secret with value foo=bar
- deploy the secrets catalog template
- create a global service where a container will run on each host and select the secret "foo" with the name "foo"
- exec into the container on each host and make sure that /run/secrets/foo has the content "bar"

I was able to validate the steps with both localkey and vault backend
