### ISSUE TITLE
Docs: Not sure how to create volumes.

### ISSUE THREAD

**Issue by keyscores** [rancher/rancher#761]
Spending a lot of time learning about volumes and how to create and destroy them. 
Would be nice to have docs in the app, like you have with Load Balancer.

**Comment by deniseschannon** [comment]
In 1.2, there will be more information about creating volumes. It will be updated from our 1.2 branch into master in the next couple of days. 

http://docs.rancher.com/rancher/v1.2/en/rancher-services/storage-service/
