### ISSUE TITLE
Catalog service refactoring

### ISSUE THREAD

**Issue by joshwget** [rancher/rancher#7610]
- Switch to being database-backed. Catalog service currently uses a combination of storing repos on disk and keeping in memory data structures. The latter can cause problems with HA since it's not truly RESTful. Using a database also allows us to store more complicated metadata easily which makes future features easier to add.

- Multitenancy in mind. Global catalogs (shared between all environments) should only be able to be modified by an admin. All other catalogs should be specific to environment.

Progress is tracked in the https://github.com/joshwget/catalog-service repo.

Issues that will be solved either directly or indirectly by the refactoring.
- #7582 
- #6702 
- #5342
- #3158

**Comment by vincent99** [comment]
@joshwget how exactly are you addressing #7582?

**Comment by joshwget** [comment]
@vincent99 I'm not using the semantic version library anymore. Basically split by `.-` and compare the numbers by left to right. This allows for an arbitrary number of versions.

https://github.com/rancher/catalog-service/blob/master/utils/version.go#L22

#7582 is basically the same issue as #6702.

**Comment by vincent99** [comment]
Hmm, not sure that's a great idea.. For example, `v1.4.0-rc2` is a prerelease tag and less than `v1.4.0`, but greater than `v1.4.0-rc1`.  There's also `+metadata` which shouldn't affect comparison, etc.

**Comment by joshwget** [comment]
@vincent99 I guess I was being a little too literal there. The process has a bit more to it. I'm pretty sure I have [tests](https://github.com/rancher/catalog-service/blob/master/utils/version/version_test.go#L60) to cover all of the cases you mention. Wouldn't mind some feedback to see if I'm missing anything though.

**Comment by vincent99** [comment]
And you're going to do the range parsing/satisfying too?  https://github.com/rancher/catalog-service/blob/master/utils/version.go

**Comment by joshwget** [comment]
I'm using the semver library to handle the parsing, but I don't use their comparison function (https://github.com/joshwget/semver/tree/custom-comparator-functions)

**Comment by deniseschannon** [comment]
Closed as new catalog service is merged. Any new bugs will be filed separately.
