### ISSUE TITLE
Health checks from Aliases don't get added to Haproxy Loadbalancer 

### ISSUE THREAD

**Issue by miv** [rancher/rancher#7612]
Test case: Create service with healthcheck, add it to lb, check Haproxy stats page and see that Haproxy configuration is indeed has helthchecks (green line on service). 

Now create alias to that service and put it to lb instead of service itself. Check stats pages and see that there is no health checks on lb anymore.

Use case: Our CI creates new stacks, pass health checks and then change alias, and that alias is already set in lb. That way we can ensure that lb config is not disturbed. But using aliases disable health checks on lb side.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.3.3` Cattle: `v0.175.9` UI: `v1.3.5` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`stacks.index`|

**Comment by loganhz** [comment]
Close it as there is a `status/autoclosed` label
