### ISSUE TITLE
Rancher Server stdout log grows indefinitely

### ISSUE THREAD

**Issue by ghost** [rancher/rancher#7615]
**Rancher Versions:**
Server: 1.3.3

**Docker Version:**
1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 14.04 LTS VM

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA Rancher, External DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Any

**Steps to Reproduce:**
1) Start Rancher Server
2) Run let it run for a week
3) Stdout log keeps growing until it fills your host file system

**Results:** 
```
/apps/docker-data/containers/c0c8b1009c85c970689b4dafa5ea8a3a720df6a57c6309047a7992cb4f415c51# ls -la
total 21459540
drwx------ 3 root root        4096 Jan 31 09:43 .
drwx------ 4 root root        4096 Jan 27 09:47 ..
-rw-r----- 1 root root 21974495232 Jan 31 09:43 c0c8b1009c85c970689b4dafa5ea8a3a720df6a57c6309047a7992cb4f415c51-json.log
```

Should the Rancher Docs recommend passing "-log-opt max-size=XXX" to the Rancher Server start command to avoid this?

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
