### ISSUE TITLE
Feature: Managing Infrastructure -> Storage

### ISSUE THREAD

**Issue by joostliketoast** [rancher/rancher#7617]
The ability to remove storage drivers that no longer exist. (preferably via the GUI)
i have some old one's lingering around dating back from when gluster was still a thing ;)

p.s. is there a less user friendly way at the moment to get rid of them safely?
they containers are already removed.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.3.3` Cattle: `v0.175.9` UI: `v1.3.5` |
|Access|`github` `admin`|
|Orchestration|`Cattle`|
|Route|`stacks.index`|

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
