### ISSUE TITLE
Feature: Multiple Rancher NFS drivers in the same environment

### ISSUE THREAD

**Issue by joostliketoast** [rancher/rancher#7618]
I have some environments that have multiple projects running within them.
And they would ideally connect to different NFS servers/locations.

There used to be a naming field in the Convoy-nfs catalog, not that i got that working with using different names.

Also since updating to version 1.2 or 1.3 i don't see convoy-nfs under `Stacks > Infrastructure` anymore.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.3.3` Cattle: `v0.175.9` UI: `v1.3.5` |
|Access|`github` `admin`|
|Orchestration|`Cattle`|
|Route|`stacks.index`|

**Comment by aemneina** [comment]
@joostliketoast modified the subject to update its relevancy.

**Comment by LLParse** [comment]
@deniseschannon  Please test with Rancher v1.6.2

URL: https://github.com/rancher/rancher-catalog
Branch: nfsv083

**Comment by LLParse** [comment]
@joostliketoast We implemented this a while back in a different way. By setting the driver_opts `host` and `export` in the volume section of your stack, you can use multiple nfs servers/exports using the same driver. A problem existed where the behavior differed slightly from what you are probably expecting. With the newest NFS release, the driver_opts `host` and `exportBase` are what you are looking for. Example usage will be provided in the catalog readme.

**Comment by soumyalj** [comment]
Tested using rancher/storage-nfs:v0.8.3. Created volume vol1 using host/exportBase driver_opts. 
Ex: host - IP address of the NFS server
      exportBase - /home/test
Created services using this volume vol1. Data write and reads were successful. On the NFS server, a sub directory vol1 will be created in /home/test and data will be stored there. 
Multiple volumes using host/exportBase driver_opts can be created and used during service creation.

**Comment by Ramblurr** [comment]
@LLParse How exactly do you specify multiple host/export pairs when using rancher-nfs from the catalog?
![rancher](https://user-images.githubusercontent.com/14830/28677798-e6498c9e-72ee-11e7-951e-b12ee00d6980.png)

It doesn't seem possible.

**Comment by LLParse** [comment]
You don't from the catalog, how would the driver decide which to use? A volume's `driver_opts` may be configured to point to any host/export. The [readme](https://github.com/rancher/rancher-catalog/tree/v1.6-development/infra-templates/nfs/4) explains how to do so.

Any further questions, feel free to open a new issue, thanks.

**Comment by Ramblurr** [comment]
@LLParse Understand now :D thanks for the pointer. I got it working.

**Comment by shadowbq** [comment]
This is still unclear to me. 

Someone please explain how to have multiple NFS locations mounted as different volume labels or point me to the docs where I am clearly not understanding.

My Environment Cattle has 3 NFS Servers that I would like to be able to expose as named storage services.. 
```
1 Rancher SRV

1 Cattle ENV

20 Wrkload Hosts with ROS
10.0.0.101
10.0.0.102
10.0.0.103
10.0.0.104
..
10.0.0.120

NFS Servers
10.0.1.2 /media/store1(rw,sync)
10.0.1.3 /media/store2(rw,sync)
10.0.1.5 /media/store3(rw,sync)
```

**Comment by joshiegy** [comment]
I to would like to have the same info as what @shadowbq is requesting

**Comment by agrieco** [comment]
@shadowbq @joshiegy did you figure this out?  I'm perplexed as well...
