### ISSUE TITLE
entered secret with file mode = 444, but file gets 674

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#7623]
**Rancher Versions:** v1.4.0-rc6

**Steps to Reproduce:**
1.  Create a secret with File Mode = 444
2.  Go to shell and change dir to /run/secrets and 'll'

**Results:** 
![image](https://cloud.githubusercontent.com/assets/11514927/22479227/308cc800-e7aa-11e6-969f-443581173259.png)

**Comment by cloudnautique** [comment]
The catalog with storage container v0.6.7 has the fix for this.

**Comment by tfiduccia** [comment]
Version - 1.4.0-rc7
Verified fixed
![image](https://cloud.githubusercontent.com/assets/11514927/22562475/e699f074-e939-11e6-8e7d-3f3d4cd9803e.png)
