### ISSUE TITLE
UI Error when trying to upgrade some services

### ISSUE THREAD

**Issue by djskinner** [rancher/rancher#7632]
**Rancher Versions:**
Server: 1.3.3
healthcheck: 0.2.0
ipsec: holder ?
network-services: metadata 0.7.0, network-manager: 0.4.0
scheduler: 0.5.1 
kubernetes (if applicable): N/A

**Docker Version:** 2 hosts: 1.12.3 and 1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):** 2x  Ubuntu 14.04.5 Linode

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** Single node internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:**

Attempt to upgrade some particular services within a stack. Only seems to happen with two services (redis and postgresql) in a stack of 5 services.

**Results:** 

Error page:

<img width="418" alt="screen shot 2017-02-01 at 12 04 07" src="https://cloud.githubusercontent.com/assets/2514172/22506103/914da6d8-e876-11e6-9eab-8013b2706595.png">

Reloading, logging out and in etc does not make a difference.

JS Stack trace:

```
Application Error TypeError: Cannot read property 'forEach' of null
    at n.setUiId (http://rancher.atomx.io:8080/assets/ui-b5780557163d8810a506ff3639e78bc4.js:99:3354)
    at n.afterModel (http://rancher.atomx.io:8080/assets/ui-b5780557163d8810a506ff3639e78bc4.js:99:3275)
    at Object.m [as applyHook] (http://rancher.atomx.io:8080/assets/vendor-45897e50be27cdd43c606e3ffcf6a893.js:18:7208)
    at runSharedModelHook (http://rancher.atomx.io:8080/assets/vendor-45897e50be27cdd43c606e3ffcf6a893.js:17:17479)
    at runAfterModelHook (http://rancher.atomx.io:8080/assets/vendor-45897e50be27cdd43c606e3ffcf6a893.js:17:17191)
    at http://rancher.atomx.io:8080/assets/vendor-45897e50be27cdd43c606e3ffcf6a893.js:18:5719
    at y (http://rancher.atomx.io:8080/assets/vendor-45897e50be27cdd43c606e3ffcf6a893.js:18:10918)
    at b (http://rancher.atomx.io:8080/assets/vendor-45897e50be27cdd43c606e3ffcf6a893.js:18:11013)
    at g (http://rancher.atomx.io:8080/assets/vendor-45897e50be27cdd43c606e3ffcf6a893.js:18:10821)
```

Points to this code:

```
        afterModel: function(e) {
            e.set("service.secondaryLaunchConfigs", this.setUiId(e.get("service.secondaryLaunchConfigs")))
        },
        setUiId: function(e) {
            return e.forEach(function(e) {
                var t = a.default.randomStr();
                e.uiId = t
            }),
            e
        },
```

Which suggests `service.secondaryLaunchConfigs` is missing for these services.

In the API (`/v2-beta/projects/1a5/stacks/1st51/services`) I see `"secondaryLaunchConfigs": null` for these services. Other services in the stack have an empty array instead of null.

This stack has been with me since 1.0 days.

**Comment by djskinner** [comment]
Any idea how I can fix this? It's currently preventing me from upgrading services in a production environment.

**Comment by djskinner** [comment]
Still unable to upgrade these services in 1.4.0

**Comment by vincent99** [comment]
By 1.0 do you mean pre-1.0?  As far as I can remember the field was never nullable, but if the service is from before sidekicks existed it would probably be null now.

If you open up the browser console and run ```
s.getById('service','1s42').set('secondaryLaunchConfigs',[])
```

(with the correct service ID in place of `1s42`) you should be able to upgrade it and have it saved as empty array instead of null.

**Comment by djskinner** [comment]
:+1: that worked perfectly. Yeah it was probably pre-1.0 to be honest. Many thanks.
