### ISSUE TITLE
Unable to provision DigitalOcean host - exit status 1/2

### ISSUE THREAD

**Issue by bkuhl** [rancher/rancher#7633]
I'm attempting to spin up a new host on Digital Ocean in a new environment that I created and I get the error "exit status 1" or "exit status 2" and it fails.  I'm using the small, 1GB VM.  The VM never shows within DigitalOcean.

![screen shot 2017-02-01 at 9 02 20 am](https://cloud.githubusercontent.com/assets/524933/22509706/2c64a50a-e85d-11e6-80de-b6d526fd2fc5.png)

The API token I'm using has both read and write permissions.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.3.1` Cattle: `v0.175.6` UI: `v1.3.5` |
|Access|`github` `admin`|
|Orchestration|`Cattle`|
|Route|`hosts.index`|

**Comment by tfiduccia** [comment]
@bkuhl - I'm unable to reproduce your problem and can setup Digital Oceans hosts. Did you change any of the defaults in the Add host?

**Comment by bkuhl** [comment]
I did not

**Comment by tfiduccia** [comment]
We remove machines if we cannot complete the setup.  So if you could have DO open during the add and make sure it's never being created.

If it's not ever being created, then it has something to do with the authentication process.  Can you custom add a DO machine?

**Comment by bkuhl** [comment]
Earlier today I was able to provision a DO host fine.  This evening I'm seeing the same issue again where it's related to the exist status.

**Comment by bkuhl** [comment]
Here's some api info about one of the hosts that failed:

```
"baseType": "host",
"name": null,
"state": "error",
"accountId": "1a21",
"agentIpAddress": null,
"agentState": null,
"amazonec2Config": null,
"authCertificateAuthority": null,
"authKey": null,
"azureConfig": null,
"computeTotal": 1000000,
"created": "2017-03-25T01:31:27Z",
"createdTS": 1490405487000,
"description": null,
"digitaloceanConfig": {
"accessToken": "c8a24ce385880f9491c47691b34e0dde8d9b630192ee5b67f1115011fa6817ac",
"image": "ubuntu-16-04-x64",
"region": "nyc3",
"size": "512mb",
"sshKeyFingerprint": "",
"sshKeyPath": "",
"sshPort": "22",
"sshUser": "root",
"userdata": ""
},
"dockerVersion": null,
"driver": "digitalocean",
"engineEnv": null,
"engineInsecureRegistry": null,
"engineInstallUrl": "https://releases.rancher.com/install-docker/1.12.sh",
"engineLabel": null,
"engineOpt": null,
"engineRegistryMirror": null,
"engineStorageDriver": null,
"hostname": "production-charity-02",
"info": null,
"instanceIds": null,
"kind": "host",
"labels": { },
"localStorageMb": null,
"memory": null,
"milliCpu": null,
"packetConfig": null,
"physicalHostId": "1ph9",
"publicEndpoints": null,
"removed": null,
"transitioning": "error",
"transitioningMessage": "exit status 2",
"transitioningProgress": null,
"uuid": "b2d1c61d-dfde-44d5-947c-d4f8cdb64ac8"
```

**Comment by vincent99** [comment]
@bkuhl I've edited it out of your message but you should revoke that DO API key...

`exit status X` just means that docker-machine exited with an error code.  You can look at the rancher/server container's log to see the full output of it, there is probably something useful there before it exits.

**Comment by bkuhl** [comment]
@vincent99 Doh!  Dang I didn't realize that was there, thank you.  It has been deactivated.

I can't prove that this fixed it, but without more clarity on what the exit status is referring to I'm forced to guess.  The rancher master was listed in a Rancher node, I was going to use it to manage a mysql backup container for my master.  I began to wonder if maybe it didn't have enough memory (1GB) to provision a new host.  So I deactivated it, then went into the server and still saw all the containers running:

```
CONTAINER ID        IMAGE                            COMMAND                  CREATED             STATUS              PORTS                            NAMES
862f09bf0a28        rancher/net:v0.8.1               "/rancher-entrypoint."   7 hours ago         Up 4 hours                                           r-ipsec-ipsec-router-1-349783d1
e92781e7f703        rancher/dns:v0.13.0              "/rancher-entrypoint."   7 hours ago         Up 7 hours                                           r-network-services-metadata-dns-1-1e2059e3
0a67d279a91d        rancher/healthcheck:v0.2.0       "/.r/r /rancher-entry"   7 hours ago         Up 7 hours                                           r-healthcheck-healthcheck-1-5fa7bb14
ed62d5ba91c3        rancher/network-manager:v0.4.0   "/rancher-entrypoint."   7 hours ago         Up 7 hours                                           r-network-services-network-manager-1-cbe2bfe3
833ae72329bc        rancher/net:holder               "/.r/r /rancher-entry"   7 hours ago         Up 7 hours                                           r-ipsec-ipsec-1-d6d76e87
0346d3af6771        rancher/net:v0.8.1               "/rancher-entrypoint."   7 hours ago         Up 7 hours                                           r-ipsec-ipsec-cni-driver-1-d1b9b0ab
6e97cbd91f32        rancher/metadata:v0.7.0          "/rancher-entrypoint."   7 hours ago         Up 7 hours                                           r-network-services-metadata-1-5bc3585a
f645e97e7bde        rancher/agent:v1.1.3             "/run.sh run"            7 hours ago         Up 7 hours                                           rancher-agent
7c74ef31b62d        rancher/server:v1.3.1            "/usr/bin/entry /usr/"   9 weeks ago         Up 4 hours          3306/tcp, 0.0.0.0:443->8080/tcp   hopeful_knuth
```

So I stopped each container manually and then was able to provision a node in Digital Ocean.

**Comment by bkuhl** [comment]
Looking through the recent master logs it's not immediately clear to me which relate to the issue I encountered.  I do see this which suggests my original theory is correct that the master was out of memory:

```
time="2017-03-25T01:28:18Z" level=error msg="Git checkout failure from git err: fork/exec /usr/bin/git: cannot allocate memory"
time="2017-03-25T01:28:18Z" level=error msg="Failed to pull the catalog from git repo https://git.rancher.io/rancher-catalog.git, error: fork/exec /usr/bin/git: cannot allocate memory"
```
