### ISSUE TITLE
rancher agent not seen by rancher server

### ISSUE THREAD

**Issue by lastnod** [rancher/rancher#7634]
**Rancher Versions:1.3.3
Server:
healthcheck: ?
ipsec: ?
network-services: ?
scheduler: ?
kubernetes (if applicable): ?

**Docker Version:** 1.13.0

**OS and where are the hosts located? (cloud, bare metal, etc): bare metal / ubuntu

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB) single node

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** don't care

**Steps to Reproduce: installed rancher => set authentification  => set environment 
=> changed settings
![capture du 2017-02-01 16-48-29](https://cloud.githubusercontent.com/assets/8791187/22514044/5974e4ce-e89e-11e6-850e-bdc649202822.png)

=>tried to set host 2 times....
![capture du 2017-02-01 16-45-46](https://cloud.githubusercontent.com/assets/8791187/22513904/ee13fbe8-e89d-11e6-9b21-3c51a8ccd878.png)

=> copy/paste in terminal as root
=>docker ps -a
![capture du 2017-02-01 16-47-15](https://cloud.githubusercontent.com/assets/8791187/22513976/260c2df4-e89e-11e6-878e-1202abdee1dc.png)
====> But hosts are not seen by rancher
![capture du 2017-02-01 16-50-46](https://cloud.githubusercontent.com/assets/8791187/22514121/9a769314-e89e-11e6-8408-9f07e44c41e6.png)
don't really understand what's going wrong because agent are up !
**Results:**

**Comment by aemneina** [comment]
@lastnod can you provide logs from the rancher agent container(s)?

**Comment by lastnod** [comment]
yes, i tried some network address nothing worked
![capture du 2017-02-02 17-32-01](https://cloud.githubusercontent.com/assets/8791187/22558951/d2ca6a84-e96f-11e6-9cc2-b98e66fa2673.png)

the message is clear....
i tried to go on the new API Address http://192.168.1.4:8484/v1 it didn't worked same for http://192.168.1.101:8484/v1

i have restart rancher server and agent did nothing

**Comment by aemneina** [comment]
When you launched the agent, did you specify CATTLE_AGENT_IP? I believe when running server and agent on the same host, thats required. Dont think you'll be able to add more than one agent on the same host.

**Comment by aemneina** [comment]
Also the port you launched the server with is bound to 8080, but in your registration url you're specifying port 8484.

**Comment by lastnod** [comment]
don't think it's the problem. i made a VM install docker on it, launch an agent and it works.
I have an other problem now but it is not about DNS. so i close this issue.
