### ISSUE TITLE
Unable to access Rancher UI after about 2 weeks of uptime

### ISSUE THREAD

**Issue by pebreo** [rancher/rancher#7635]
Rancher Versions: 1.3.3? ( rancher/server:latest as of 2/1/2017)
Docker Version: 1.12.5
OS and where are the hosts located? cloud
Setup Details: single node rancher 
Environment Type: Cattle

Steps to Reproduce:
The symptoms are very similar to this issue: https://github.com/rancher/rancher/issues/1702 
except in my case, I **never** rebooted my machine. I setup my machine 2 weeks ago and added some Hosts on digital ocean (Ubuntu 14.04, 1GB ram) but I tried logging in to the UI this morning and   I get an `ERR_CONNECTION_TIME_OUT`.

I can run  `curl http://127.0.0.1:8080/v1` from the host machine and  I get JSON no problem.
Also, when I run `curl http://127.0.0.1:8080/login` I get the login page as expected.

**What I did to restart the rancher server**
This is the commands I ran to try to fix the problem:
```bash
$ docker stop <mycontainerid>
$ docker run -d -v rancher_datavolume:/var/lib/mysql --restart=always -p 8080:8080 rancher/server:latest
```

**More information**
I don't really know what I'm looking at but hopefully someone can see if there is a problem that I'm not seeing.
```bash
$ docker inspect c18 |grep IPAddress
            "SecondaryIPAddresses": null,
            "IPAddress": "172.17.0.2",
                    "IPAddress": "172.17.0.2",

$ iptables -L -n -t nat | grep 8080
MASQUERADE  tcp  --  172.17.0.2           172.17.0.2           tcp dpt:8080
DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:8080 to:172.17.0.2:8080

$ sudo iptables -L -n --line-numbers -t nat

Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
1    DOCKER     all  --  0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL

Chain INPUT (policy ACCEPT)
num  target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         
1    DOCKER     all  --  0.0.0.0/0           !127.0.0.0/8          ADDRTYPE match dst-type LOCAL

Chain POSTROUTING (policy ACCEPT)
num  target     prot opt source               destination         
1    MASQUERADE  all  --  172.17.0.0/16        0.0.0.0/0           
2    MASQUERADE  tcp  --  172.17.0.2           172.17.0.2           tcp dpt:8080

Chain DOCKER (2 references)
num  target     prot opt source               destination         
1    RETURN     all  --  0.0.0.0/0            0.0.0.0/0           
2    DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:8080 to:172.17.0.2:8080

```

**Running `docker ps`**
```
          COMMAND                  CREATED             STATUS              PORTS                              NAMES
c18c1d305403        rancher/server:latest   "/usr/bin/entry /usr/"   55 minutes ago      Up 55 minutes       3306/tcp, 0.0.0.0:8080->8080/tcp   determined_blackwell
```

Is there any more information I can provide?

Thanks.
-Paul

**Comment by aemneina** [comment]
Looks like rancher is up and listening but you cant access it from its public IP? Ha the public IP changed?

**Comment by vincent99** [comment]
I would not be paying too much attention to a year and a half old bug...

If you're getting JSON and the login page then iptables is not involved, that is the only port used.

Check docker logs for the server container?

p.s. Using `--restart=always` is going to cause trouble one day when you do reboot the host, any old server containers not `rm`ed will all start up again.  Use `--restart=unless-stopped`.

**Comment by pebreo** [comment]
When I do `docker-machine ip mymachine`, the IP address matches the address in my Digital Ocean dashboard for that machine. I copy and paste so I don't think I'm doing anything obviously silly :) Am I missing something? I'm on a school wifi. I wonder if my school is preventing IP address via HTTP?

**Comment by vincent99** [comment]
They could certainly be blocking port 8080 for whatever reason.. if `docker-machine ssh` works, you could use SSH port forwarding to get to it,

docker-machine ssh rs -L 8080:localhost:8080

and then go to http://localhost:8080 on your laptop.

**Comment by joehumphries** [comment]
Do you have a host running on the same machine as the Rancher Server? But I suspect a reboot will fix this..

**Comment by pebreo** [comment]
It is definitely my school network since everything works now that I'm back home. Thanks for everyone's help and thanks to vincent99 for the trick using the SSH forwarding command!!!
