### ISSUE TITLE
Kubernetes setup failing at Starting Services phase

### ISSUE THREAD

**Issue by karnatip** [rancher/rancher#7637]
Hi, 

Kubernetes setup is stuck at starting services phase of the setup. I noticed that one of the containers part of the kube setup -- 'rancher/kubernetes-agent:v0.5.2' is continuously restarting. I see the following error in it's logs --- 

time="2017-02-01T20:24:59Z" level=error msg="Error getting node: [redacted FQDN] by name from kubernetes, err: [Get http://kubernetes.kubernetes.rancher.internal/api/v1/nodes/redacted FQDN: dial tcp <redacted IP>:80: getsockopt: no route to host]" 
time="2017-02-01T20:24:59Z" level=error msg="Error getting node: [redacted FQDN] by name from kubernetes, err: [Get http://kubernetes.kubernetes.rancher.internal/api/v1/nodes/redacted FQDN: dial tcp <redacted IP>:80: getsockopt: no route to host]" 
time="2017-02-01T20:24:59Z" level=error msg="Error requesting for list of objects Get http://kubernetes.kubernetes.rancher.internal/api/v1/services: dial tcp <redacted IP>:80: getsockopt: no route to host" 
Request => GET http://kubernetes.kubernetes.rancher.internal/api/v1/nodes/redacted FQDN
time="2017-02-01T20:24:59Z" level=error msg="kubernetes Sync and stream listener exited with error: Get http://kubernetes.kubernetes.rancher.internal/api/v1/services: dial tcp <redacted IP>:80: getsockopt: no route to host" 
time="2017-02-01T20:24:59Z" level=info msg=Exiting

While I understand the problem, I'm not sure how to address it. I made sure all the required ports are open. I have kubernetes on the same host as Rancher. The same setup on the same hosts woked couple days back.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.3.3` Cattle: `v0.175.9` UI: `v1.3.5` |
|Access|`github` `admin`|
|Orchestration|`Kubernetes`|
|Route|`k8s-tab.error`|

**Comment by superseb** [comment]
Can you supply some more info on your setup? OS/Docker version, Cloud/on-prem.

Is this still occurring?

**Comment by superseb** [comment]
Please file a new ticket if you're still experiencing issues.
