### ISSUE TITLE
[rancher-compose] 

### ISSUE THREAD

**Issue by drpebcak** [rancher/rancher#7639]
**Rancher Versions:**
Server: 1.3.1
healthcheck: 0.2.0
ipsec: 0.0.2
network-services: 0.0.8
scheduler: 0.3.0
kubernetes (if applicable): n/a

**Docker Version:**
1.11

**OS and where are the hosts located? (cloud, bare metal, etc):**
AWS, RancherOS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA Rancher (3 nodes)

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

When using rancher-compose, there should be a way to update services to a new version of a container, and make sure the new containers are in a running state before exiting.

Currently, you can use `-d` to detach, but then you get no feedback if there was an issue launching a container (cannot pull, out of disk space, etc). If you do NOT specify `-d` the command never exits automatically. This makes it hard to script a deploy.

I would like for some way to verify the service you are modifying gets to a healthy `Upgraded` state, rather than continuously failing to start the new image.

**Comment by aemneina** [comment]
@drpebcak have you tried using the `-w` flag? According to this [doc](https://docs.rancher.com/rancher/v1.6/en/cattle/upgrading/#upgrading-services-with-rancher-compose) it might do the trick in conjunction with `--confirm-upgrade`

**Comment by drpebcak** [comment]
Unfortunately, `-w` is only good with the `upgrade` command, which doesn't take the rest of the options I want.
It looks like `upgrade` is only really good for doing things like scaling a service or updating links.

The actual update functionality I'm looking for is only available through the `up` command (modifying a service in place based on the contents of a docker-compose file).

**Comment by deniseschannon** [comment]
Closing in favor of https://github.com/rancher/rancher/issues/8492

By fixing `-w` for `rancher up`, that should fix your original issue.
