### ISSUE TITLE
[Req] Show Rancher CLI Version on Versions Modal

### ISSUE THREAD

**Issue by adamgoose** [rancher/rancher#7643]
I'd like to be able to view the Rancher CLI Version in the Versions Modal. Maybe in 1.4?

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.3.0` Cattle: `v0.175.2` UI: `v1.3.5` |

**Comment by SamMousa** [comment]
The CLI is not part of rancher, how would the GUI know which version you have locally, if any?
Or do you mean that it should show the latest version available only?

**Comment by adamgoose** [comment]
Looks like this was added in v1.4.1. 👍

**Comment by vincent99** [comment]
@SamMousa It's the version that corresponds with the version of Rancher you're looking at.  Not the version you *do have*, the version you *should* have.
