### ISSUE TITLE
High load on Rancher server and DB when starting/stopping containers

### ISSUE THREAD

**Issue by pschrammel** [rancher/rancher#7644]
**Rancher Versions:**
Server: 1.3.3
healthcheck: 0.2.0
ipsec: 0.0.2
network-services: 0.0.8
scheduler: 0.3.0
kubernetes (if applicable):-

**Docker Version:**
1.12.6, overlayfs

**OS and where are the hosts located? (cloud, bare metal, etc):**
AWS, Ubuntu 16.04 LTS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
external DB Aurora db.r3.large , HA and single (1-2x c4.xlarge), 26 m4.xlarge nodes, 800 containers avg.

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Start and stop containers

**Results:** 
High load on Rancher sevrer (+ lots of DB querries)

We are constantly starting/stopping containers (rancher-cron and a AWS lambda like system to run arbitrary scripts in well defined environments). We are starting around 15 containers per minute. The CPU of the server  is around 381% (4 cores). The RDS Aurora DB gets 1650 req/s constantly.

I'd say this needs some tuning as we're running into scaling problems ( see https://github.com/rancher/rancher/issues/6858#issuecomment-276465779 ). 

THX

**Comment by aemneina** [comment]
@pschrammel have you seen this in more recent versions of rancher? This should have been improved dramatically in later releases.

**Comment by superseb** [comment]
Let us know if this is still seen in recent versions.
