### ISSUE TITLE
Environment variables name consistency between docker machine and rancher hosts

### ISSUE THREAD

**Issue by banh-gao** [rancher/rancher#7647]
When creating a new host from rancher cli using the openstack driver the expected env variable for the driver use the prefix OPENSTACK_ while the common prefix for Openstack, also adopted by docker-machine is OS_.

Since the variable are commonly exported by sourcing the openrc.sh from openstack, here is required to change the prefix of all those variables in order to be seen by the rancher cli.

**Rancher Versions:**
Server: 1.3.3
Rancher CLI: v0.4.1

**OS and where are the hosts located? (cloud, bare metal, etc):**
Debian 8 on Openstack VMs

**Steps to Reproduce:**
> export OS_AUTH_URL='myOpenStackauthurl'
> rancher hosts create rancher-node1

**Results:**
``
Error setting machine configuration from flags provided: Authentication URL must be specified either using the environment variable OS_AUTH_URL or the CLI option --openstack-auth-url
``

**Expected Results:**
The Openstack environment variables (with OS_ prefix) has to be seen by the docker-machine driver without the need to change their prefix.

**Comment by banh-gao** [comment]
I update this discussion since I noticed that the problem is more general. The variables names mismatch also occurs for example with OS_NETWORK_NAME in docker machine, which becomes OPENSTACK_NET_NAME in rancher hosts.
Could such inconsistencies be addressed in some way?

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
