### ISSUE TITLE
Allow tags on environments

### ISSUE THREAD

**Issue by nheinemans** [rancher/rancher#7648]
**Rancher Versions:**
Server: 1.3.3

**Docker Version:**
Docker 12.6

**OS and where are the hosts located? (cloud, bare metal, etc):**
RancherOS 0.7.0 on vmware

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher with external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Feature request:**
We would like to be able to add tags to environments. In our specific use case, we need to make some decisions when adding hosts to this environment (e.g. which vsphere folder to place the VM in) and we would like to automate these decisions based on the tags on the environment.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
