### ISSUE TITLE
Loadbalancer host IP is not saved to yaml and is lost when upgrading

### ISSUE THREAD

**Issue by dren-dk** [rancher/rancher#7649]
**Rancher Versions:**
Server: 1.3.3

**Steps to Reproduce:**
* Edit a loadbalancer
* Click the Show host IP address options link
* Add a service rule and fill out an IP address in the Host IP field.
* Complete the edit by clicking the edit button
* Edit the load balancer again
* Click the Show host IP address options link

**Results:** 

* The the previously filled Host IP field is now empty.
* The host IP is also missing from the rancher-compose.yml file.

What am I doing wrong?

**Comment by tfiduccia** [comment]
@dren-dk - You are not doing anything wrong.  There is a bug on upgrade/edit.  It's already been reported #7288.  If you edit/upgrade a load balancer, you will have to re-enter that information until this issue has been resolved.  If you re-enter it, it is being saved and the rule will work.
