### ISSUE TITLE
Load Balancer Rules not working in 1.3.2

### ISSUE THREAD

**Issue by kareed44** [rancher/rancher#7651]
**Rancher Versions:**
Server: 1.3.2

**Docker Version:**
1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 14.04 - Amazon AWS EC2

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node server

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

We have a stack with various containers and a load balancer (rancher/lb-service-haproxy:v0.4.9). The load balancer has a set of rules that route various distinct paths to their respective containers. It appears that only 2 of the 7 rules are working. I can't diagnose why due to empty logs in the lb container:  https://github.com/rancher/rancher/issues/7591. 

This was all working on version 1.1.2 but has since stopped since we upgraded to 1.3.2.

Thoughts?

**Comment by HenryTheSir** [comment]
According to http://rancher.com/support-maintenance-terms/ you habe to update your docker Version to 1.12.x . Maybe this will fix your error. Are you working with links or with full Rancher DNS names?

**Comment by kareed44** [comment]
We have narrowed it down to the load balancer rule priorities. When the stack is created from our catalog the priorities defined in rancher-compose are lost. However, when created manually through "Add Stack" the priorities remain.

**Comment by aemneina** [comment]
@kareed44 dont think this is docker version specific. Do you see the same problem with later versions of rancher?

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
