### ISSUE TITLE
Secrets: the volume names are too long

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#7654]
**Rancher Versions:**
Server: v1.4.0-rc7

Secrets volumes has long names, instead of readable names:

![secrets-volume](https://cloud.githubusercontent.com/assets/3309968/22561497/27077266-e981-11e6-8566-6aecbce3f5f4.png)

```
# docker volume ls
DRIVER              VOLUME NAME
rancher-secrets     304de79e196e098602339bfdeaa46e5d73b32ef367e069dd0350f7a7b4d58fad
rancher-secrets     91e45e1c54d75d8926cdf7c667de8c158b5596b82d66a35b7b9359b4bee75610
 ```

**Comment by cloudnautique** [comment]
The name is passed to the volume driver. If its going to be something else it would be in cattle.

Thoughts @ibuildthecloud

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
