### ISSUE TITLE
Container spreading completely broke

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#7656]
**Rancher Versions:**
Server: 1.4.0-rc7
scheduler: v0.6.2

**Steps to Reproduce:**
1. Create two hosts
2. From container page, start adding containers
3. Observe that they all land on the same host.

**Results:** 
Actual
All containers go to the same host
Expected
Containers should spread between the two as you add them

**Comment by sangeethah** [comment]
Rancher Versions:
Server: 1.4.0-rc8
rancher/scheduler:v0.6.2

Set up with 3 hosts:

Added few services with different scales and standalone containers. Instances of the sevices and standalone container spread across all hosts .

<img width="1059" alt="screen shot 2017-02-02 at 9 25 46 pm" src="https://cloud.githubusercontent.com/assets/4266958/22580552/3abd818a-e98e-11e6-9476-a19a220b9e3a.png">
