### ISSUE TITLE
kubectld trips over a ConfigMap

### ISSUE THREAD

**Issue by errordeveloper** [rancher/rancher#7657]
**Rancher Versions:**
Server: 1.3.3
kubernetes (if applicable): 1.5.1

**OS and where are the hosts located? (cloud, bare metal, etc):**
rancheros-v0.7.1-hvm-1 (ami-c62170b5)

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**

Add custom catalogue with URL
`https://github.com/errordeveloper/community-catalog` and branch `issue-7657`.

Try installing `weave-cloud`. You can obtain a token from https://cloud.weave.works, if you want to test it end-to-end, but you enter any string instead of an actual token in order to reproduce this issue.

**Results:** 
```
"replace variables: Invalid interpolation format for \"cortex-configmap.yaml\" option in service \"files\": \"apiVersion: v1\nkind: ConfigMap...
```

**Comment by errordeveloper** [comment]
@alena1108 I've worked out a solution that by-passes this problem, it also avoid having to vendor a copy of upstream manifest, PTAL https://github.com/rancher/community-catalog/pull/422. This is still a bug, of course.

**Comment by superseb** [comment]
With the switch to Helm and upgraded kubectl, this should be fine now.
