### ISSUE TITLE
network policy issues due to underlying ipsec problem

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#7658]
Rancher Versions: v1.4.0-rc7

Setup has 3 hosts.
Deployed network-policy-manager.

Was altering "defaultNetworkPolicy" and "Policy" settings to different settings and connectivity between containers were working as expected.

Then last i did was to switch from "defaultNetworkPolicy" set to "deny" and "Policy" set to "Allow within stack" to "defaultNetworkPolicy" set to "allow" and "Policy" set to nothing.

After this , connectivity between containers in 2 of the hosts works as expected following the "Allow" policy. 
But connectivity to one of the hosts (from other 2 hosts) in the setup is broken.

I see the following errors in the network-policy-manager-network-policy-manager-1 container on the host:

```
2/2/2017 2:41:37 AMtime="2017-02-02T10:41:30Z" level=error msg="Error reading metadata version: Get http://169.254.169.250/2016-07-29/version?wait=true&value=7892-5cc6db6887beb3525be1bd696730805e&maxWait=5: dial tcp 169.254.169.250:80: getsockopt: connection refused"
2/2/2017 2:41:37 AMtime="2017-02-02T10:41:35Z" level=error msg="Error reading metadata version: Get http://169.254.169.250/2016-07-29/version?wait=true&value=7892-5cc6db6887beb3525be1bd696730805e&maxWait=5: dial tcp 169.254.169.250:80: getsockopt: connection refused"
```

**Comment by leodotcloud** [comment]
@sangeethah Summary of our offline discussion:
- The network policy programming looks fine, there are no issues with that.
- There was some problem with the underlying ipsec connectivity. For some reason the first host was not able to reach the other two hosts.
- To test this, I just restarted the ipsec container of host 3 and it was able to reach host 1.
