### ISSUE TITLE
rancher-catalog-service unsafe interface conversion of config.yml values

### ISSUE THREAD

**Issue by LLParse** [rancher/rancher#7659]
**Rancher Versions:**
rancher-catalog-service: v0.15.0

**Steps to Reproduce:**
1. Create a catalog entry with a `values.yml` that includes a value that can be interpreted as an int/float. For example:
```
name: Zammad
description: |
  Zammad is a web based open source helpdesk/customer support system
version: 1.2
category: Ticketsystems
maintainer: "Zammad Project <info@zammad.org>"
projectURL: https://github.com/zammad/zammad
license: AGPL-3.0
```
2. Launch rancher-catalog-service with the repository configured to serve the newly created catalog entry: `./rancher-catalog-service -catalogUrl library=https://github.com/monotek/community-catalog`
3. Make an API call to get the template details: `http://localhost:8088/v1-catalog/templates/library:zammad`

**Results:** The non-string value `version` appears as an empty string in the API. This is due to unsafe interface conversion: https://github.com/rancher/rancher-catalog-service/blob/master/manager/catalog.go#L261-L281

**Expected:** The yaml parser is given an **out** object that contains typed fields so interface conversion logic is not necessary

This bug was caught by our community-catalog CI system which performs some basic validation of template objects served from rancher-catalog-service API:
https://github.com/rancher/community-catalog/pull/411

**Comment by tfiduccia** [comment]
Version - master 2/21
Verified fixed
