### ISSUE TITLE
Service transition from "registering"-> "inactive" state , when ports are made available.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#7660]
Rancher-server version - v1.4.0-rc7

Steps to reproduce the problem:

1. Set random port range to 6 ports for default environment.
2. Exhaust 5 of them by creating a service - S1 that has 5 random ports exposed
3. Create a service - S2 that has 2 random exposed ports when there is only 1free port available in the random port range
4. Service fails to get created and is stuck in "registering" state with error message ```Not enough environment ports to create service. Needed: 2, available: 0)```
5. Delete service S1.
6. After sometime , S2 gets to "Inactive" state.

Expected Behavior:
S2 should get to "active" state and service containers should get deployed successfully.

**Comment by alena1108** [comment]
@sangeethah tested with the latest master (and the latest UI). I see that the failed service goes to inactive, followed by activating->active states. As long as startOnCreate flag is passed (which UI does by default). Can you retest with the latest?

**Comment by sangeethah** [comment]
Tested with latest build from master

Set random port range to 6 ports for default environment.
Exhaust 5 of them by creating a service - S1 that has 5 random ports exposed
Create a service - S2 that has 2 random exposed ports when there is only 1free port available in the random port range (This was created from UI where  startOnCreate flag is true)
Service fails to get created and is stuck in "registering" state with error message (Not enough environment ports to create service. Needed: 2, available: 0)
Delete service S1.
After sometime , S2 gets from "registering" to "active" state as expected.
