### ISSUE TITLE
Agent is leaking FDs

### ISSUE THREAD

**Issue by StrongMonkey** [rancher/rancher#7661]
Agent is leaking File Descriptors when a docker event is created.
Steps to reproduce that:
1. Launch rancher server with one host.
2. Ssh into the host, find the pid of agent, and do `lsof -a -p $(pidof agent)` to find the  FDs agent is using.
3. Launch several container in rancher, compare the number of FDs used by agent before and after starting containers.
4. Should be a significant amount of increment.(4 or 5 per container)

**Comment by StrongMonkey** [comment]
@sangeethah  With the fix, FDs shouldn't grow when docker events come. And the total number of FDs which agent uses should retain in a relatively low number and should not grow too fast among time.

**Comment by StrongMonkey** [comment]
https://github.com/rancher/agent/pull/138

**Comment by StrongMonkey** [comment]
https://github.com/rancher/cattle/pull/2459

**Comment by sangeethah** [comment]
Tested with rancher-server version -  v1.4.0-rc8

Had a rancher-server setup with 3hosts.

Added ~5 containers to one of the hosts. FD count taken up by agent hovers around 20.
Added ~20 more containers to one of the hosts.Stopped and started containers.
FD count taken up by agent continues to hovers around 20.

```
root@sangeerc8-10acre-1:/home/sangeethahariharan1# lsof -a -p 29565 | wc -l
20
root@sangeerc8-10acre-1:/home/sangeethahariharan1# ps -eaf | grep agent
root      3436 30684  0 02:11 pts/0    00:00:00 grep --color=auto agent
root     29565 29449  0 01:40 ?        00:00:05 /var/lib/cattle/pyagent/agent
root@sangeerc8-10acre-1:/home/sangeethahariharan1# 

```
