### ISSUE TITLE
Service names not resolving

### ISSUE THREAD

**Issue by ihackalot** [rancher/rancher#7663]
**Rancher Versions:**
Server: 1.3.3
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker Version:**
1.12.6
**OS and where are the hosts located? (cloud, bare metal, etc):**
DigitalOcean cloud
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
internal DB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
Connecting to database instance with a client like SQL Pro or Querious using database service name.
 **Results:** 
Connection is refused. Only way to connect is by using service IP.

**Comment by superseb** [comment]
Can you describe the steps to reproduce, what are you launching, service with one container or multiple, loadbalancer yes/no? From where are you connecting to where?

So I can understand the problem better.

**Comment by superseb** [comment]
Please comment or file a new issue if you are still experiencing issues.
