### ISSUE TITLE
rancher healthcheck container stuck Initializing state

### ISSUE THREAD

**Issue by Chenpipi** [rancher/rancher#7664]
*Describe your issue here*
Host info:
system: centos7.2/centos7.3/redhat7.3
rancher:
HA(two nodes) / loadbalance(nginx)
docker version:
Docker version 1.12.5, build 7392c3b / Docker version 1.13.0, build 49bf474

I use rancher to add three hosts, using the cattle vxlan, which healthcheck and scheduler containers have been stuck in the initializing state. they get the IP address, the other works fine. The rancher proxy logs no errors. 
Who can give guidance?
![schedule](https://cloud.githubusercontent.com/assets/9670781/22585242/c57de866-ea31-11e6-824d-cc58bdf60bf1.jpg)
![healthcheck](https://cloud.githubusercontent.com/assets/9670781/22585249/cfa84f84-ea31-11e6-8fe6-8949e1fbb4bb.jpg)
![all](https://cloud.githubusercontent.com/assets/9670781/22585335/3e6edb2c-ea32-11e6-8a45-49aa5df0fec3.jpg)

### rancher proxy logs:
rancher proxy 01:
`time="2017-02-03T16:34:20+08:00" level=info msg="Request to refresh catalog" 
time="2017-02-03T16:34:20+08:00" level=info msg="Using catalog community=https://git.rancher.io/community-catalog.git" 
time="2017-02-03T16:34:20+08:00" level=info msg="Using catalog library=https://git.rancher.io/rancher-catalog.git" 
time="2017-02-03T16:34:22+08:00" level=fatal msg="Failed to configure cattle client: Get http://localhost:8080/v1: dial tcp [::1]:8080: getsockopt: connection refused" 
time="2017-02-03T16:34:22+08:00" level=info msg="Downloading key from http://localhost:8081/v1/scripts/api.crt" 
time="2017-02-03T16:34:22+08:00" level=info msg="Webhook service listening on 8085" 
time="2017-02-03T16:34:22+08:00" level=info msg="Starting websocket proxy. Listening on [:8080], Proxying to cattle API at [localhost:8081], Monitoring parent pid [9]." 
time="2017-02-03T16:34:22+08:00" level=info msg="Master config file: master.conf" 
time="2017-02-03T16:34:22+08:00" level=info msg="Master address: 10.50.131.132:8080" 
time="2017-02-03T16:34:23+08:00" level=info msg="Downloading certificate from http://localhost:8081/v1/credentials/1c1/certificate" 
time="2017-02-03T16:34:24+08:00" level=info msg="Starting Rancher Auth service" 
time="2017-02-03T16:34:24+08:00" level=info msg="No Auth provider configured" 
time="2017-02-03T16:34:24+08:00" level=info msg="Listening on :8090" 
time="2017-02-03T16:34:25+08:00" level=error msg="Failed to pull the catalog from git repo https://git.rancher.io/community-catalog.git, error: exit status 1" 
time="2017-02-03T16:34:28+08:00" level=error msg="Failed to pull the catalog from git repo https://git.rancher.io/rancher-catalog.git, error: exit status 1" 
time="2017-02-03T16:35:01+08:00" level=info msg="No Auth provider configured" 
time="2017-02-03T16:35:01+08:00" level=info msg="No Auth provider configured" 
time="2017-02-03T16:39:28+08:00" level=info msg="Refresh for this catalog community is already in process, skipping" 
time="2017-02-03T16:39:29+08:00" level=info msg="Refresh for this catalog library is already in process, skipping" 
time="2017-02-03T16:44:28+08:00" level=info msg="Refresh for this catalog community is already in process, skipping" 
time="2017-02-03T16:44:29+08:00" level=info msg="Refresh for this catalog library is already in process, skipping" 
time="2017-02-03T16:49:28+08:00" level=info msg="Refresh for this catalog community is already in process, skipping" 
time="2017-02-03T16:49:29+08:00" level=info msg="Refresh for this catalog library is already in process, skipping" 
time="2017-02-03T16:54:29+08:00" level=info msg="Refresh for this catalog community is already in process, skipping" 
time="2017-02-03T16:59:28+08:00" level=info msg="Refresh for this catalog community is already in process, skipping" 
time="2017-02-03T16:59:29+08:00" level=info msg="Refresh for this catalog library is already in process, skipping"`

rancher proxy 02:
`time="2017-02-03T16:36:42+08:00" level=info msg="Stack Create Event Done" eventId=d82733a8-1bc1-455b-9f1b-9827c19b7e46 resourceId=1st6 
time="2017-02-03T16:36:42+08:00" level=info msg="Stack Create Event Done" eventId=640412a7-6c10-451d-bb75-4a7c0a9c1daf resourceId=1st5 
time="2017-02-03T16:36:42+08:00" level=info msg="[vxlan:vxlan]: Created " eventId=43c7e528-27a3-4729-af10-0f3174b88a12 resourceId=1st7 
time="2017-02-03T16:36:42+08:00" level=info msg="[vxlan:cni-driver]: Creating " eventId=43c7e528-27a3-4729-af10-0f3174b88a12 resourceId=1st7 
time="2017-02-03T16:36:42+08:00" level=info msg="[vxlan:cni-driver]: Created " eventId=43c7e528-27a3-4729-af10-0f3174b88a12 resourceId=1st7 
time="2017-02-03T16:36:42+08:00" level=info msg="[vxlan:]: Project created " eventId=43c7e528-27a3-4729-af10-0f3174b88a12 resourceId=1st7 
time="2017-02-03T16:36:42+08:00" level=info msg="[vxlan:]: Creating project " eventId=43c7e528-27a3-4729-af10-0f3174b88a12 resourceId=1st7 
time="2017-02-03T16:36:42+08:00" level=info msg="[vxlan:vxlan]: Creating " eventId=43c7e528-27a3-4729-af10-0f3174b88a12 resourceId=1st7 
time="2017-02-03T16:36:42+08:00" level=info msg="[vxlan:vxlan]: Created " eventId=43c7e528-27a3-4729-af10-0f3174b88a12 resourceId=1st7 
time="2017-02-03T16:36:42+08:00" level=info msg="[vxlan:cni-driver]: Creating " eventId=43c7e528-27a3-4729-af10-0f3174b88a12 resourceId=1st7 
time="2017-02-03T16:36:42+08:00" level=info msg="[vxlan:cni-driver]: Created " eventId=43c7e528-27a3-4729-af10-0f3174b88a12 resourceId=1st7 
time="2017-02-03T16:36:42+08:00" level=info msg="[vxlan:]: Project created " eventId=43c7e528-27a3-4729-af10-0f3174b88a12 resourceId=1st7 
time="2017-02-03T16:36:42+08:00" level=info msg="Stack Create Event Done" eventId=43c7e528-27a3-4729-af10-0f3174b88a12 resourceId=1st7 
time="2017-02-03T16:38:57+08:00" level=info msg="Creating Machine" eventId=150f46a8-3f3d-424a-ba06-06f5fcb42cd0 resourceId=1ph1 
time="2017-02-03T16:38:57+08:00" level=info msg="Activating Machine" eventId=a2672f71-e70f-490e-beb0-cfbb4963a97d resourceId=1ph1 
time="2017-02-03T16:38:59+08:00" level=info msg="Handling backend connection request." 
time="2017-02-03T16:38:59+08:00" level=info msg="Registering backend for host 26da2490-5ac7-4ce6-47f3-30f64e43ae9a with session ID 416032e6-4e8a-4d6b-b5ab-6a32d879e818." 
time="2017-02-03T16:39:19+08:00" level=info msg="Creating Machine" eventId=8513b970-12d5-4110-bb35-45db25b283ae resourceId=1ph2 
time="2017-02-03T16:39:19+08:00" level=info msg="Activating Machine" eventId=ab1a135c-42a0-4fa4-9b52-330420208563 resourceId=1ph2 
time="2017-02-03T16:39:24+08:00" level=info msg="Handling backend connection request." 
time="2017-02-03T16:39:24+08:00" level=info msg="Registering backend for host c63a6cb6-7d2c-40a3-6aff-fb501300fc22 with session ID 01502a25-1c20-4269-91e4-b946e630f34d." 
time="2017-02-03T16:39:49+08:00" level=info msg="Creating Machine" eventId=d12d9124-af86-4aec-878d-565783db7de7 resourceId=1ph3 
time="2017-02-03T16:39:49+08:00" level=info msg="Activating Machine" eventId=23d67238-043c-4afc-8e2b-f172768e7527 resourceId=1ph3 
time="2017-02-03T16:39:51+08:00" level=info msg="Handling backend connection request." 
time="2017-02-03T16:39:51+08:00" level=info msg="Registering backend for host af8f6240-f5ed-4e8c-64ef-bd2b769e9485 with session ID 68c78aee-4fb9-454a-905d-50908bec7c1e`

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.3.3` Cattle: `v0.175.9` UI: `v1.3.5` |
|Access|`Disabled`|
|Orchestration|`Cattle`|
|Route|`hosts.index`|

**Comment by Chenpipi** [comment]
Supplement:
Delete the initializing state of the container, let it regenerate, the state will be normal. very strange.

**Comment by einfallstoll** [comment]
Have the same issue running a two server setup using Ubuntu 16.04. Both the healthcheck and the scheduler are stuck on initializing. Regenerating the containers or redeploying the whole service doesn't help.

**Comment by einfallstoll** [comment]
Possible duplicate of #7493?

**Comment by Chenpipi** [comment]
@einfallstoll  I redeployed all the environment after normal.
The unified docker version (Docker version 1.12.6, build 78d1802)
Using the latest version of rancher HA (rancher 1.4.0), 3 nodes
Synchronization of all the host time, time zone, hardware clock.
OS: centos7.1/7.3 rhel7.3.

**Comment by iclouding** [comment]
Have the same issue running a two server setup using CentOS7.2 / Docker 12.6
Regenerating the containers or redeploying the whole service doesn't help.
https://github.com/rancher/rancher/issues/8557

**Comment by Rucknar** [comment]
It might be worth checking the state of the encrypted tunnels between the hosts. If you've got 3 hosts (A,B,C) then it will check the status of the service you configure from up to three hosts excluding the one your running the service on. So if it was running on A then servers B & C would perform the healthcheck. 

Though it's a good design, this does mean that issues with the tunnels between hosts can incorrectly present themselves as healthcheck issues. I'm on the road now but if you dig around, there should be some useful tips for diagnosing inter-host connectivity. Just pinging between containers on two different hosts should verify it's working. (Make sure those containers are on a managed network of course.)

**Comment by iclouding** [comment]
@Rucknar Pinging between containers on two different hosts can not work. But the corresponding ports haved been opened.

**Comment by Rucknar** [comment]
Okay so it sounds like that might be the issue. When you say the corresponding ports have been opened, which ports specifically? The docs require `From and to all other hosts on UDP ports 500 and 4500 (for IPsec networking)`

**Comment by iclouding** [comment]
```bash
[op@localhost ~]$ sudo iptables -L -n
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
ACCEPT     udp  --  0.0.0.0/0            0.0.0.0/0            udp dpts:1:65535
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpts:1:65535
ACCEPT     udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:53
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:53
ACCEPT     udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:67
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:67
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:6789
ACCEPT     udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:500
ACCEPT     udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:4500
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:2376
```
All port have been opened.

**Comment by Rucknar** [comment]
Okay, next step is to diagnose now we think it's a network issue. To save me typing, might be worth running through the steps here: https://docs.rancher.com/rancher/v1.5/en/faqs/troubleshooting/

If they don't resolve it then i'll dig out the commands to check the IPSEC tunnels themselves.

**Comment by iclouding** [comment]
[Troubleshooting](https://docs.rancher.com/rancher/v1.5/en/faqs/troubleshooting/) also can not help.

**Comment by Rucknar** [comment]
Was the status of the healthcheck stack green?

**Comment by iclouding** [comment]
![](http://i1.piimg.com/567571/f224bb5aa60e92eb.png)

**Comment by Rucknar** [comment]
Could you paste the full text of that line that runs off the screen? I can see a WARNING but not what is output.

**Comment by iclouding** [comment]
ok
healthcheck-healthcheck-4 logs:
```
2017/4/25 下午4:08:44time="2017-04-25T08:08:44Z" level=info msg="Starting haproxy listener"
2017/4/25 下午4:08:44time="2017-04-25T08:08:44Z" level=info msg="healthCheck -- starting haproxy\n * Starting haproxy haproxy\n   ...done.\n"
2017/4/25 下午4:08:44time="2017-04-25T08:08:44Z" level=info msg="Scheduling apply config"
2017/4/25 下午4:08:44time="2017-04-25T08:08:44Z" level=info msg="healthCheck -- reloading haproxy config with the new config changes\n[WARNING] 114/080844 (35) : config : 'option forwardfor' ignored for proxy 'web' as it requires HTTP mode.\n[WARNING] 114/080844 (35) : config : 'option forwardfor' ignored for backend 'cattle-0c1e1bac-f6c2-4bd5-86fa-123d43d26842_da3af8c6-212a-4872-a95f-79748528650a_1' as it requires HTTP mode.\n[WARNING] 114/080844 (35) : config : 'option forwardfor' ignored for backend 'cattle-0c1e1bac-f6c2-4bd5-86fa-123d43d26842_8b80c0e3-777a-40de-b53b-ed036f6b2430_1' as it requires HTTP mode.\n[WARNING] 114/080844 (35) : config : 'option forwardfor' ignored for backend 'cattle-0c1e1bac-f6c2-4bd5-86fa-123d43d26842_41678d18-246b-45bb-a134-1cc3980accc4_3' as it requires HTTP mode.\n[WARNING] 114/080844 (35) : config : 'option forwardfor' ignored for backend 'cattle-0c1e1bac-f6c2-4bd5-86fa-123d43d26842_0a50b395-8989-44f6-ba2b-32ecb51de500_1' as it requires HTTP mode.\n[WARNING] 114/080844 (35) : config : 'option forwardfor' ignored for backend 'cattle-0c1e1bac-f6c2-4bd5-86fa-123d43d26842_021d7d9c-d7e2-413e-87bc-23a630f74be5_3' as it requires HTTP mode.\n"
2017/4/25 下午4:08:45time="2017-04-25T08:08:45Z" level=info msg="Scheduling apply config"
2017/4/25 下午4:08:45time="2017-04-25T08:08:45Z" level=info msg="healthCheck -- no changes in haproxy config\n"
2017/4/25 下午4:08:45time="2017-04-25T08:08:45Z" level=info msg="Scheduling apply config"
2017/4/25 下午4:08:45time="2017-04-25T08:08:45Z" level=info msg="healthCheck -- no changes in haproxy config\n"
2017/4/25 下午4:08:46time="2017-04-25T08:08:46Z" level=info msg="Scheduling apply config"
2017/4/25 下午4:08:46time="2017-04-25T08:08:46Z" level=info msg="healthCheck -- no changes in haproxy config\n"
2017/4/25 下午4:08:46time="2017-04-25T08:08:46Z" level=info msg="0c1e1bac-f6c2-4bd5-86fa-123d43d26842_da3af8c6-212a-4872-a95f-79748528650a_1=INIT"
2017/4/25 下午4:08:46time="2017-04-25T08:08:46Z" level=info msg="0c1e1bac-f6c2-4bd5-86fa-123d43d26842_8b80c0e3-777a-40de-b53b-ed036f6b2430_1=INIT"
2017/4/25 下午4:08:46time="2017-04-25T08:08:46Z" level=info msg="0c1e1bac-f6c2-4bd5-86fa-123d43d26842_0a50b395-8989-44f6-ba2b-32ecb51de500_1=INIT"
2017/4/25 下午4:08:46time="2017-04-25T08:08:46Z" level=info msg="Monitoring 6 backends"
2017/4/25 下午4:08:48time="2017-04-25T08:08:48Z" level=info msg="0c1e1bac-f6c2-4bd5-86fa-123d43d26842_da3af8c6-212a-4872-a95f-79748528650a_1=UP"
2017/4/25 下午4:08:48time="2017-04-25T08:08:48Z" level=info msg="0c1e1bac-f6c2-4bd5-86fa-123d43d26842_8b80c0e3-777a-40de-b53b-ed036f6b2430_1=UP"
2017/4/25 下午4:08:48time="2017-04-25T08:08:48Z" level=info msg="0c1e1bac-f6c2-4bd5-86fa-123d43d26842_4e818d68-8ea8-416c-979e-5128dc0f4d1c_5=DOWN"
2017/4/25 下午4:08:48time="2017-04-25T08:08:48Z" level=info msg="0c1e1bac-f6c2-4bd5-86fa-123d43d26842_0a50b395-8989-44f6-ba2b-32ecb51de500_1=UP"
2017/4/25 下午4:08:52time="2017-04-25T08:08:52Z" level=info msg="0c1e1bac-f6c2-4bd5-86fa-123d43d26842_41678d18-246b-45bb-a134-1cc3980accc4_3=DOWN"
2017/4/25 下午4:08:55time="2017-04-25T08:08:55Z" level=info msg="0c1e1bac-f6c2-4bd5-86fa-123d43d26842_021d7d9c-d7e2-413e-87bc-23a630f74be5_3=DOWN"
2017/4/25 下午4:09:49time="2017-04-25T08:09:49Z" level=info msg="0c1e1bac-f6c2-4bd5-86fa-123d43d26842_41678d18-246b-45bb-a134-1cc3980accc4_3=DOWN 1/2"
2017/4/25 下午4:09:51time="2017-04-25T08:09:51Z" level=info msg="0c1e1bac-f6c2-4bd5-86fa-123d43d26842_4e818d68-8ea8-416c-979e-5128dc0f4d1c_5=DOWN 1/2"
2017/4/25 下午4:09:51time="2017-04-25T08:09:51Z" level=info msg="0c1e1bac-f6c2-4bd5-86fa-123d43d26842_021d7d9c-d7e2-413e-87bc-23a630f74be5_3=DOWN 1/2"
2017/4/25 下午4:09:53time="2017-04-25T08:09:53Z" level=info msg="0c1e1bac-f6c2-4bd5-86fa-123d43d26842_4e818d68-8ea8-416c-979e-5128dc0f4d1c_5=INIT"
2017/4/25 下午4:09:55time="2017-04-25T08:09:55Z" level=info msg="0c1e1bac-f6c2-4bd5-86fa-123d43d26842_4e818d68-8ea8-416c-979e-5128dc0f4d1c_5=UP"
2017/4/25 下午4:09:55time="2017-04-25T08:09:55Z" level=info msg="0c1e1bac-f6c2-4bd5-86fa-123d43d26842_41678d18-246b-45bb-a134-1cc3980accc4_3=INIT"
2017/4/25 下午4:09:55time="2017-04-25T08:09:55Z" level=info msg="0c1e1bac-f6c2-4bd5-86fa-123d43d26842_021d7d9c-d7e2-413e-87bc-23a630f74be5_3=INIT"
2017/4/25 下午4:09:56time="2017-04-25T08:09:56Z" level=info msg="Scheduling apply config"
2017/4/25 下午4:09:56time="2017-04-25T08:09:56Z" level=info msg="healthCheck -- no changes in haproxy config\n"
2017/4/25 下午4:09:57time="2017-04-25T08:09:57Z" level=info msg="0c1e1bac-f6c2-4bd5-86fa-123d43d26842_41678d18-246b-45bb-a134-1cc3980accc4_3=UP"
2017/4/25 下午4:09:57time="2017-04-25T08:09:57Z" level=info msg="0c1e1bac-f6c2-4bd5-86fa-123d43d26842_021d7d9c-d7e2-413e-87bc-23a630f74be5_3=UP"
```

**Comment by Rucknar** [comment]
Just having a read through this ticket: https://github.com/rancher/rancher/issues/8276
I'm wondering if one of the rancher nodes might not have the right auto-detected IP. 

I'm not 100% sure how to check this from logs, it's worth checking the IP's that are listed though when on the hosts screen. Each host should have it's `cattle_ip` listed in the description. This is *I think* the IP rancher uses for host>host communication when initiates the tunnels. Worth checking those are correct and showing the IP you'd expect. If that fails, it's probably worth doing a search on open issues, see if anyone else has logged an error that matches what you see. I've not troubleshooted the inter-host networking since it was updated to work with drivers etc.

**Comment by steve-todorov** [comment]
@Rucknar you might be on the right track. I started having the same issue and our setup has 2 hosts (one on the same machine as rancher and one on a remote network). After stopping the remote host Rancher's infrastructure went back to normal without me doing anything more. I don't have time to investigate it more right now but in case you need any help in the debugging this issue - please let me know how I could help or what to do if it reappears.

**Comment by deniseschannon** [comment]
@steve-todorov If you have a host that is on the same machine on Rancher server, it has been known to have issues auto-detecting the IP address of the host. You can check in the UI if the IP is correct. We typically request users to set the IP when running the rancher/agent container on the same machine as rancher/server:

This can be done in the UI through the custom command and adding the IP so that the command updates to include `-e CATTLE_AGENT_IP=<ip>`

http://docs.rancher.com/rancher/v1.6/en/faqs/troubleshooting/#are-the-ips-of-the-hosts-correct-in-the-ui

**Comment by sirius1024** [comment]
same issue here
ubuntu 16.04
rancher 1.6.3
docker 17.06.2-ce
When I have only 1 host it's allright. Adding more it doesn't work anymore.

**Comment by superseb** [comment]
Please create a new issue, this one is old and closed. Couple of things to check:

- Are the correct IPs shown in the Infrastructure -> Hosts view? (if not, register with `CATTLE_AGENT_IP`
- Ports needed for overlay networking (UDP/500 + UDP/4500 for IPsec and 4789 for VXLAN) are open between these IPs
- Check logging of network-manager and ipsec-router
