### ISSUE TITLE
Editing host ip list is not recognized by scheduler

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#7669]
**Rancher Versions:** v1.4.0-rc8

**Steps to Reproduce:**
1.  Add host
2.  Edit host and add 2 IPs
3.  Create load balancer to use both IPs

**Results:** Load balancer fails cause it thinks there is only 1 ip

**Comment by soumyalj** [comment]
Tested with v1.4.0-rc9. Adding/Editing scheduler IPs from the edit host option works correctly.
The IPs are reflected correctly in the UI and API and are recognized by the scheduler.
