### ISSUE TITLE
View in API & Edit from Actions drop-down don't work

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#7672]
**Rancher Versions:** v1.4.0-rc8

**Steps to Reproduce:**
1.  Create a secret
2.  Select that secret
3.  Under Actions drop-down try to select View in API or Edit

**Results:** Nothing happens.  Error is console - Uncaught TypeError: this.get(...)[e] is not a function

**Comment by vincent99** [comment]
This is the same as https://github.com/rancher/rancher/issues/7787 , actions that apply only to a single resource don't work.

**Comment by tfiduccia** [comment]
Version - master 2/23
This is still broken

**Comment by westlywright** [comment]
@tfiduccia `View in Api` and `Delete` actions are working, edit has been removed. According to the schema secrets name fields are not editable.

**Comment by tfiduccia** [comment]
Version - 6/12 (2.0 alpha)
Verified fixed
