### ISSUE TITLE
When PublicHostIp is set for exposed ports for a service, it does not land on the correct host.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#7675]
Rancher Versions: v1.4.0-rc8

Have a set up with 3 hosts out of which one of the host has scheduler ip set to "ip1".

Steps to reproduce the problem:
Create a service with PublicHostIp set for exposed port to "ip1" like ```<ip1>:9898:80/tcp```.
Instances of the service start on host that do not have this scheduler ip set.

**Comment by StrongMonkey** [comment]
@sangeethah  the fix was in 1.5.0-alpha

**Comment by sangeethah** [comment]
Tested with rancher-server version - v1.5.0-alpha1 and rancher/scheduler:v0.7.0

When PublicHostIp is set for exposed ports for a service, it  lands on the correct host which has the scheduler ip and is bound to the requested ip.
