### ISSUE TITLE
[Feature Request] Option to start after creating for Service

### ISSUE THREAD

**Issue by cavemandaveman** [rancher/rancher#7677]
When adding a stack, there is an option to "start services after creating".
A similar option for services, "start after creating", does not seem possible. A service always runs when created or upgraded. We cannot launch a service defaulting to an inactive state.

For example, I have a service that I run on a schedule using the help of [rancher-cron](https://github.com/SocialEngine/rancher-cron). When I first launch the service (as a start-once), it runs immediately and stops, then runs on the schedule from rancher-cron. What I would like is to launch the service, but have it lay dormant until it needs to run, foregoing the initial run.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
