### ISSUE TITLE
Scheduler IPs set from UI are lost after scheduler restart/ping

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#7678]
**Rancher Versions:**
v1.4.0-rc8

**Docker Version:**1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):**Cloud

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**Single host

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**Cattle

**Steps to Reproduce:**
1.  Create a setup with CATTLE_SCHEDULER_IPS = "IP1, IP2"
2. From edit host, add scheduler IPs and SAVE. The IPs are listed correctly in the UI and API
3. Restart scheduler. The IPs lost from the API and UI and not available to be used by the scheduler.
Note: This happens for every agent ping

**Comment by StrongMonkey** [comment]
https://github.com/rancher/agent/pull/140

**Comment by soumyalj** [comment]
Tested with v1.4.0-rc9. Scheduler IPs set from UI are retained after scheduler restart/ping.
Containers can be launched successfully on these IPs
