### ISSUE TITLE
Do not allow for scheduler ips to be removed/edited when ip is in use by containers.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#7679]
Rancher Versions: v1.4.0-rc8

Currently we are allowed to edit hosts and remove/edit scheduler ips that are being assigned to containers.
Do not allow for scheduler ips to be removed/edited when ip is in use by containers.

**Comment by StrongMonkey** [comment]
Need to discuss with @cjellick about this.

**Comment by cjellick** [comment]
I don't agree that this is a bug or that the behavior should be changed. The IPs on the host are just used for  the scheduling of containers in the future. Don't see any reason to impose this limitation.

**Comment by cjellick** [comment]
@sangeethah I want to further explain my reasoning in the last comment:

The fact that an IP is in use by a container should have no impact on whether the user chooses to continue to schedule new containers against that IP address. The fact that it is removed from the scheduler will have no impact on the container running, starting, or stopping. In fact, a user could even create a new container using that IP after removing the IP from the host, we just wouldn't know where to put it, which is what the behavior has always been.

I'm going to assign back to you. If you agree with my logic, please close the issue. If not, feel free to assign back to me with an explanation and then we can discuss.

**Comment by sangeethah** [comment]
@cjellick Closing this issue as per your comments.
