### ISSUE TITLE
rancher catalog install --answers flag usage with custom template

### ISSUE THREAD

**Issue by slimatic** [rancher/rancher#7682]
I tried to install a custom template using the --answers flag since the default were not being used;
`rancher catalog install catalog-id -a`

the CLI prompts for a response even though there is a default answer already showing. I am trying to bypass the questions by either:

1. Bypassing the questions since there is a default answer already in place ( -y or -f command)
2. Getting more documentation help on how to use the `--answers` flag properly.

**Comment by slimatic** [comment]
I figured a walk around but open to ideas on best way to do this:
`echo -ne '\n' | rancher catalog install template-id`

**Comment by ZachMatics** [comment]
This is great. Running into problem with multiline prompts though. Still no solution?

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
