### ISSUE TITLE
rancher/net ipsec-router Excessive Logging

### ISSUE THREAD

**Issue by gcallsen** [rancher/rancher#7683]
**Rancher Versions:**
Server: v1.3.3
healthcheck: v0.2.0
ipsec: 0.0.2
network-services: v0.0.8
scheduler: v0.3.0
kubernetes (if applicable):

**Docker Version:**
All hosts Docker v1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):**
All hosts Ubuntu 16.04.1 LTS (4.4.0), all cloud.

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher. External DB.

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
All environments Cattle orchestration.

**Steps to Reproduce:**
Launch any services with above setup.

**Results:** 
Get excessive logging output from rancher/net:v0.8.1. I've attached a small (super ugly, sorry) example of the log output. We use a fork of rapid7/docker-logentries (https://github.com/pitrho/docker-logentries) to pipe all logs from Docker to Logentries. Our normal usage is between 16-20GB/month.  We upgraded to Rancher 1.3.3 on Tuesday (Jan 31) and our usage for February is already 7.2 GB as of this morning (Feb 3). I modified our logentries deployment to skip any log output from any images /rancher\/.*/, which has taken care of the issue for now on our end. However, I'm curious if this is intended or if we have done something wrong on our end?

Many thanks,
Gilman

![image](https://cloud.githubusercontent.com/assets/633975/22615186/479c5dfc-ea5d-11e6-920b-edbba82ef30d.png)

**Comment by leodotcloud** [comment]
@gcallsen There is a fix for this ready. https://github.com/rancher/rancher/issues/7311
