### ISSUE TITLE
Once add "Windows" from catalog, orchestration is switched to Windows and never rollback

### ISSUE THREAD

**Issue by k8w** [rancher/rancher#7684]
**Rancher Versions:**
Server: 1.3.3
healthcheck: 0.2.0
ipsec:rancher/net:holder
network-services: rancher/network-manager:v0.4.0
scheduler: rancher/scheduler:v0.5.1
kubernetes (if applicable):

**Docker Version:**
1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):**
Cloud (Aliyun)

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle (Before)

**Steps to Reproduce:**
A Cattle environment, add "Windows(Experimental)" from catalog, and orchestration is changed to Windows automatically.
Not expect this, wanna rollback.
But find no way to modify orchestration.
Once try to delete stack "Windows", there would be error :
> Error deleting
Driver from service is in use by instances (1i3673,1i3674,1i3675,1i5913)

**Results:** 
Some containers cannot work, seems like because of network (get IP timeout).

**Comment by jinhong-** [comment]
I am getting the same issue too on a local rancher install using RancherOS. Adding a windows environment caused my default environment's orchestration to become Windows as well. Also seems like there is no way to revert.
![image](https://cloud.githubusercontent.com/assets/3448324/23396025/89c72252-fdcc-11e6-8bc6-9a7108d253f5.png)

**Comment by taina0407** [comment]
+1

**Comment by taina0407** [comment]
Step 1: Use my previous comment to temporary convert orchestration to Cattle (or any thing else)
Step 2: Go to Stack -> Infrastructure, try to stop & remove "windows" stack, if you success you are done!, else go to Step 3.
Step 3: Go to HOST:PORT/env/1a5/infra/containers/CONTAINER_ID , then you will know which container is currently using "windows" infrastructure. Find stack of this container and "upgrade" to create new containers use the orchestration which we set at Step 1, remember to "finish upgrade" to remove old containers.
Repeat step 2 until you can stop & remove "windows" stack

After you remove the "windows" stack, orchestration will permanence revert to the original

**Comment by loganhz** [comment]
Fixed in v1.6.22
