### ISSUE TITLE
Feature request: Mount volume for /var/log/containers from kubelet to host to enable fluentd logging

### ISSUE THREAD

**Issue by ryanwalls** [rancher/rancher#7688]
**Rancher Versions:**
Server: 1.3.3
healthcheck: v0.2.0
ipsec: rancher/net:v0.8.1
network-services: rancher/metadata:v0.7.0, rancher/network-manager:v0.4.0
scheduler: rancher/k8s:v1.5.1-rancher1-7
kubernetes (if applicable): rancher/k8s:v1.5.1-rancher1-7

**Docker Version:**
1.13.0

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 14.04.5 LTS, hosted in EC2, t2.small instance

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node, external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
Setup k8s environment with default configuration

**Results:** 
(Edited to reflect the new request)
I'm trying to aggregate logs using fluentd and this filter: https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter.  That filter relies on the pod name, etc being in the log file names.  By default in `docker_manager.go` (see https://github.com/kubernetes/kubernetes/blob/v1.3.2/pkg/kubelet/dockertools/docker_manager.go#L1527-L1530) the kubelet creates a symlink from the containers `LogPath` to `/var/log/containers` that includes the extra metadata.  

The kubelet is creating the symlinks. It is just creating them inside its container. Currently, rancher is not mounting that directory to the host by default.  This request is to get the default kubelet config to map this `/var/log/containers`  directory to the host so that I can access it for log aggregation.

**Comment by ryanwalls** [comment]
Found the issue.  

The kubelet is creating the symlink.  It is just creating it inside its container.  Currently, rancher is not mounting that directory to the host by default.  

Updating the title to reflect the request to mount that directory by default to the host.

**Comment by alena1108** [comment]
@wlan0 I believe to solve this, we'd have to create a mount to log directory similar to how we do it for /host/dev:

https://github.com/rancher/kubernetes-package/blob/ebd90cd1560e955e43abec51f4dd344cd8e90e94/package/entry.sh#L51

@ryanwalls kubernetes-package repo is used for building k8s services images using official k8s binaries + some custom stuff we inject on the startup (like fetching/injecting the certs, bind mounting the kubelet volumes) via ```entry.sh```  - the script that is being executed at the k8s service instance start. To test custom changes you make to entry.sh, you'd have to:

1) change entry.sh
2) execute ```make``` from the root of kubernetes-package dir. It would build the images with the updated entry.sh
3) reference those images from your k8s catalog - you'd have to point infra catalog repo to your private catalog repo location that uses updated k8s images.

**Comment by ryanwalls** [comment]
@alena1108 Thanks.  The only fuzzy part is step 3.  "reference those images from your k8s catalog".  How do I modify the k8s catalog?

**Comment by ryanwalls** [comment]
Nevermind.  I figured it out. :)

Here's my steps for anyone who wants to replicate.
- Fork https://github.com/rancher/kubernetes-package.
- Fork https://github.com/rancher/rancher-catalog.

**Comment by deniseschannon** [comment]
This was fixed in earlier versions of k8s but can be tested with k8s  v1.6.1 in the v1.6.0-dev branch.

**Comment by jmreicha** [comment]
@deniseschannon Is there any way this functionality can be ported to Cattle based environments?  It would make log shipping a lot easier.  I opened a feature request for adding this but I don't think it has been prioritized.

**Comment by ryanwalls** [comment]
@jmreicha This only applies to Kubernetes environments.  There are no kubelets in a Cattle based environment.

**Comment by jmreicha** [comment]
@ryanwalls Yeah.  I'm wondering if the same type of functionality could be added to the rancher-agent (or somewhere else) so that we can get logs in Cattle environments, in a similar way to Kubernetes.

**Comment by galal-hussein** [comment]
Rancher server: master build
Kubernetes: 1.6.1

When examining the host's /var/log/containers directory, i can see multiple broken links pointing to /var/log/pods which is not mounted to the host:

```
~# ls /var/log/containers/ -l
total 56
lrwxrwxrwx 1 root root 65 Apr 21 19:09 heapster-780945131-zwk30_kube-system_heapster-b391e84a69695574102dbd3bab42b2077be7773949f3407ed63ebebddfe05631.log -> /var/log/pods/f7fa4363-26c5-11e7-b0f0-02793dae9446/heapster_0.log
lrwxrwxrwx 1 root root 77 Apr 21 19:09 kubernetes-dashboard-2118248793-5kh4s_kube-system_kubernetes-dashboard-5a2d072500f6412de7bf8997b7575e55f2e9b46e243cdb2654deac041ec4ae52.log -> /var/log/pods/f7f986c6-26c5-11e7-b0f0-02793dae9446/kubernetes-dashboard_0.log
...

~# ls /var/log/pods
ls: cannot access '/var/log/pods': No such file or directory
```

**Comment by ryanwalls** [comment]
@galal-hussein @deniseschannon This is broken in Rancher 1.6.6 with k8s 1.6.  Starting in k8s 1.6 the kubelet writes logs to `/var/log/pods`.  So we need to add `/var/log/pods` to the mount list for the kubelet so they get written to the host.

**Comment by galal-hussein** [comment]
Rancher server v1.6.6-rc2
Kubernetes version: v1.7.1-rancher2

I can verify that `/var/log/containers` has a working symlinks to `/var/log/pods`
```
# ls -l /var/log/pods/9bc2402d-6ed7-11e7-8f37-02b893ed240a/
total 4
lrwxrwxrwx 1 root root 165 Jul 22 12:16 grafana_0.log -> /var/lib/docker/containers/475753d275593f1974afe06be9d5333f9f47fa09a7f2974ea295673a8cd66f5a/475753d275593f1974afe06be9d5333f9f47fa09a7f2974ea295673a8cd66f5a-json.log
```
```
# ls -l /var/log/containers/
total 32
lrwxrwxrwx 1 root root 65 Jul 22 12:16 heapster-4285517626-3wlf8_kube-system_heapster-a8a4511ad8ae87731a38acb9ec7d4b671fbd93d8f8bb753c2bb094298f1ecf15.log -> /var/log/pods/9c470dbf-6ed7-11e7-8f37-02b893ed240a/heapster_0.log
lrwxrwxrwx 1 root root 64 Jul 22 12:17 kube-dns-2981845537-flr73_kube-system_dnsmasq-0e606b95031fe96602cc405db9708a7032226782831a7908cdeba8b2735e6960.log -> /var/log/pods/a11c4542-6ed7-11e7-8f37-02b893ed240a/dnsmasq_0.log
lrwxrwxrwx 1 root root 64 Jul 22 12:17 kube-dns-2981845537-flr73_kube-system_kubedns-50c20cfe92e2354ae92a27e8dfd2434dfcd7237846fe920311be5e3472a16236.log -> /var/log/pods/a11c4542-6ed7-11e7-8f37-02b893ed240a/kubedns_0.log
lrwxrwxrwx 1 root root 64 Jul 22 12:17 kube-dns-2981845537-flr73_kube-system_sidecar-b9788c920923fe70eb34de7e20ccfe11cc9b5d2775146c73c62518a367cff05a.log -> /var/log/pods/a11c4542-6ed7-11e7-8f37-02b893ed240a/sidecar_0.log
lrwxrwxrwx 1 root root 77 Jul 22 12:17 kubernetes-dashboard-716739405-j1j1p_kube-system_kubernetes-dashboard-94bc5364d776742c0e7148d4559f2f3c98672ce68badb43833292a38daaf4248.log -> /var/log/pods/9edcf770-6ed7-11e7-8f37-02b893ed240a/kubernetes-dashboard_0.log
lrwxrwxrwx 1 root root 64 Jul 22 12:16 monitoring-grafana-3552275057-b8q19_kube-system_grafana-475753d275593f1974afe06be9d5333f9f47fa09a7f2974ea295673a8cd66f5a.log -> /var/log/pods/9bc2402d-6ed7-11e7-8f37-02b893ed240a/grafana_0.log
lrwxrwxrwx 1 root root 65 Jul 22 12:16 monitoring-influxdb-4110454889-vk9cd_kube-system_influxdb-79feb3d0203ba37f0508605cab71021097997c63612760349833441a4971bb11.log -> /var/log/pods/9d1ec6e4-6ed7-11e7-8f37-02b893ed240a/influxdb_0.log
lrwxrwxrwx 1 root root 63 Jul 22 12:17 tiller-deploy-737598192-dw8cf_kube-system_tiller-c90a819fa8d9f635abdbb12301a26a76cf43862a9b257526604c81b04e464166.log -> /var/log/pods/9f687bd6-6ed7-11e7-8f37-02b893ed240a/tiller_0.log
```
