### ISSUE TITLE
Get "Failed authentication" response when opening k8s dashboard

### ISSUE THREAD

**Issue by ryanwalls** [rancher/rancher#7692]
Rancher Versions:
Server: 1.3.3
healthcheck: v0.2.0
ipsec: rancher/net:v0.8.1
network-services: rancher/metadata:v0.7.0, rancher/network-manager:v0.4.0
scheduler: rancher/k8s:v1.5.1-rancher1-7
kubernetes (if applicable): rancher/k8s:v1.5.1-rancher1-7

Docker Version:
1.13.0

OS and where are the hosts located? (cloud, bare metal, etc):
Ubuntu 14.04.5 LTS, hosted in EC2, t2.small instance

Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)
Single node, external DB

Environment Type: (Cattle/Kubernetes/Swarm/Mesos)
Kubernetes

Steps to Reproduce:
Not entirely sure.  I setup k8s environment with default configuration.  At one point I did change the rancher address... but then changed it back.  Basically all I'm doing is clicking on "Dashboard" link in kubernetes dropdown.

Results:
Get a "Failed authentication" message with status code 401 in browser.

**Comment by ryanwalls** [comment]
Setup a brand new environment.  Was good for a while, then when I scaled in a server in my auto scaling group that my cluster lives on, started getting 401 unauthorized again.

**Comment by ryanwalls** [comment]
Error in rancher server logs is:

```
level=info msg="Invalid backend host requested." hostUuid=af0d42f8-3a78-455a-6301-27277b2d3026 
```

**Comment by ryanwalls** [comment]
I would have voted for leaving in kubernetes rancher visualization until the dashboard integration was a little tighter... 

After seeing the error about `invalid backend host`, I removed some disconnected hosts.  Now I get this error when trying to open k8s dashboard:

```
level=error msg="Error looking up token." error="HTTP error: 404 Not Found, 404" 
```

**Comment by superseb** [comment]
Thanks for reporting, the steps to reproduce for now are:

* Setup k8s
* Change Host Registration URL (or did you change DNS?)
* Change Host Registration URL back (or DNS)
* Dashboard fails?

**Comment by ryanwalls** [comment]
I haven't seen this in recent versions of rancher server, so will close.
