### ISSUE TITLE
Heapster cannot install automatically

### ISSUE THREAD

**Issue by niusmallnan** [rancher/rancher#7696]
**Rancher Versions:** v1.4.0
kubernetes (if applicable): rancher/k8s:v1.5.2-rancher1-2

addon-updates.sh in https://github.com/rancher/kubernetes-package
```
for f in $(find /etc/kubernetes/addons -name '*.yaml'); do
  kubectl --kubeconfig=/etc/kubernetes/ssl/kubeconfig --namespace=kube-system replace --force -f ${f}
done
``` 

But, these heapster files end with "yml".
![image](https://cloud.githubusercontent.com/assets/998984/22636331/2e9d3f96-ec75-11e6-8345-aeb5ee181770.png)

**Comment by pengjiang80** [comment]
Same problem here.
