### ISSUE TITLE
Rancher being insistent about having stopped containers.

### ISSUE THREAD

**Issue by kaithar** [rancher/rancher#7698]
Ok, I'm at a loss... Rancher seems to like randomly creating copies of containers that are running quite happily.

For instance I have one host that insists on having a stopped copy of the ipsec router and ipsec containers.  If I delete them it'll recreate them, start them, then stop them again.  Completely ignoring the running ones.
I have the same thing happening with healthcheck containers and even most of my Prometheus stack.

I don't know where to even start debugging this since I can't work out which part of rancher is doing it.  Is it a healthcheck thing?  A metadata confusion?  Scheduling trying to enforce requirements improperly?  Where should I start looking for some kind of reasoning for this?

| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.3.3` Cattle: `v0.175.9` UI: `v1.3.5` |
|Orchestration|`Cattle`|

Sometimes the stopped containers appear in the stack...
![image](https://cloud.githubusercontent.com/assets/76736/22639069/0e74ea74-ec44-11e6-92ab-01b7832685ee.png)

Sometimes they appear as stand alone...
![image](https://cloud.githubusercontent.com/assets/76736/22639101/308241d4-ec44-11e6-9dd5-ffc5b9023abb.png)

Sometimes they remember they're supposed to be sidekicks but not that they're in a stack...
![image](https://cloud.githubusercontent.com/assets/76736/22639140/6f121154-ec44-11e6-9293-24a7ba90fad2.png)

**Comment by vincent99** [comment]
My first guess would be multiple server containers running at the same time because of `--restart=always` instead of `--restart=unless-stopped` and they're pointed at the same database

**Comment by kaithar** [comment]
I can see the logic there but I've double checked and there's not two running.

**Comment by einfallstoll** [comment]
@vincent99 I guess the documentation leads to this interpretation when setting up HA:

> Running Rancher server in High Availability (HA) is as easy as running Rancher server using an external database, exposing an additional port, and adding in an additional argument to the command for the external load balancer. (Source: http://docs.rancher.com/rancher/v1.2/en/installing-rancher/installing-server/#multi-nodes)

I assumed I can just connect two server to the same external database and rancher "will just work".

**Comment by superseb** [comment]
@kaithar Did you figure this out, can we help debugging?
