### ISSUE TITLE
NATS logging driver support

### ISSUE THREAD

**Issue by ravlio** [rancher/rancher#7699]
**Rancher version:**
1.4

Docker already supporting NATS logging driver (https://docs.docker.com/engine/admin/logging/overview/), but I do not see it in Rancher interface.

**Comment by alekzonder** [comment]
[docker 1.13](https://docs.docker.com/v1.13/engine/admin/logging/overview/#/supported-logging-drivers) has NATS support, but in [docker 17](https://docs.docker.com/engine/admin/logging/overview/#configure-the-logging-driver-for-a-container) NATS logging driver removed without any comments 

https://github.com/docker/docker.github.io/pull/2240

> The NATS driver was never integrated into Docker and should not be in
the docs.

**Comment by vincent99** [comment]
I guess we're going with not adding it then if it doesn't exist...
