### ISSUE TITLE
Inter-Stack-Communication not working after 1.4.0 update

### ISSUE THREAD

**Issue by 0ff** [rancher/rancher#7700]
**Rancher Versions:**
Server: v1.4.0
healthcheck: 0.2.3
ipsec: 0.0.4
network-services: 0.0.10
scheduler: 0.4.0
network-policy-manager: 0.0.1 (installed manually after the update)

**Docker Version:**
Docker version 1.12.3, build 6b644ec

**OS and where are the hosts located? (cloud, bare metal, etc):**
AWS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher, external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Spin up 1.3.3, upgrade to 1.4.0

**Results:** 
Expected: Inter-Stack-Communication works as before
Actual: Inter-Stack-Communication does not work at all

**Problem:**
My guess (!) is that during the update, `defaultPolicyAction` is not touched for an existing environment. When the `rancher-agent` is then upgraded, it doesn't know about it and restricts communication.

**Workaround:**
1. Set `defaultPolicyAction` to `allow` in rancher-server:8080/v2-beta/projects/1a5/networks (should be the first env you've created; if you have multiple set it for every cattle env at least).
2. restart `rancher-agent` on every host using `docker restart rancher-agent`

**Fix:**
Eiter set the default to `allow` or make sure that no value actually means allow in code.

**Comment by sangeethah** [comment]
@off , i am not able to reproduce the issue where inter-Stack-Communication is broken after upgrading from 1.3.3 to 1.4.0. I am testing with hosts from GCE with OS version - ```Ubuntu 16.04.1 LTS (4.4.0)``` and docker version  - 1.12.6.

As you have mentioned in the bug , i do see ```defaultPolicyAction```  and ```policy``` set to null even after the following steps where done:

1. Upgrade rancher-server to 1.4.0 
2. Do not ugrade any of the infra stacks.
3.  inter-Stack-Communication works.
4. Upgrade all infra stacks (to 1.4)
5.  inter-Stack-Communication works.
6. Install network-policy-manager
7.  inter-Stack-Communication works.

Even though I see  ```defaultPolicyAction```  and ```policy``` set to null  , intercommunication between stacks continues to work in my case as expected.

Can you please check , if in your case ipset is empty ? You can get to it from the network-policy-manager container  - ```ipset -L```

**Comment by leodotcloud** [comment]
@0ff I see your point that after upgrade `defaultPolicyAction: null`. But that shouldn't cause any problems in the environment.

Looking at the code: https://github.com/rancher/network-policy-manager/blob/v0.1.0/policy/watcher.go#L456, in a 1.3.3 setup, `len(np.Rules) = 0` causing to take the else block and since I am checking for an explicit `deny` for `defaultPolicyAction` there shouldn't be any rules programmed at all.

I am curious as to how you could have run into the problem of communication not working.

Can you please share your OS details?

Also if you are planning on trying to reproduce the issue, before doing any workaround, can you please check the output of the following commands on all the hosts?
```
iptables-save
ipset -L 
```

**Comment by 0ff** [comment]
Thanks for both of your responses! I will try to reproduce the setup tomorrow and get in touch with the results.
Just to clarify _why_ I am suspecting something with the `defaultPolicyAction`: I tried `ping`ing (and `curl`ing) 3 different kinds of hosts in my ipsec network:

1. hosts in the same stack on the same host -> worked
2. hosts in a different stack on the same host -> didn't work
3. hosts in a different stack on a different host -> didn't work

Unfortunately, I didn't test same stack/different host so I can't say for sure that it was only related to the 1.4.0 changes. Also, at some point, the `rancher-agent` on one (and only one) of the hosts (out of 3 in this setup) went kind of rouge, which means that for some reason (most certainly not related to this) even after restarting it wouldn't assign IP Addresses to new containers which lead to all containers breaking with `Timeout getting IP address`.
By this time (though I can't be sure if it was like this before or not), the `healthcheck` container on this host (and again, only this host) went into failure saying that some services couldn't be reached. The other `healthcheck`s were always green (which, I realise, is quite in contrast to `1.` above).

So I really hope that we can replicate the error so that there may be a fix for other users. I'll update you tomorrow!
If anything else comes to mind which might explain the above, please let me know!

**Comment by leodotcloud** [comment]
@0ff I think you were hitting a different issue altogether. May be: https://github.com/rancher/rancher/issues/6858

When you try to reproduce, please make sure the environment upgrade went fine and all of your stacks are reachable before even you install `network-policy-manager`.

Let us know how it goes.

**Comment by leodotcloud** [comment]
@0ff Did you get a chance to reproduce the issue?

**Comment by einfallstoll** [comment]
I run into the same issue. We've got a HA Rancher setup with two hosts and a stack consisting of two services which got deployed one on each host. If I execute a shell on one host and try to ping the service on the other host it will timeout. Although the DNS resolves correctly.

There's no additional setup or configuration in rancher and the two services are not configured further as well.

**Comment by einfallstoll** [comment]
I was able to resolve my issue by recreating the `rancher-agent` container using the correct IPs. Our hosts are behind a firewall with NAT, so I was confused about which IP I should use.

    docker run -e CATTLE_AGENT_IP="<INTERNAL_IP>"  -e CATTLE_HOST_LABELS='io.rancher.host.external_dns_ip=<EXTERNAL_IP>'  -d --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.2.0 http://rancher-rulez:8080/v1/scripts/idAnDStUfF

@0ff Could this be the problem for you as well? If not I was just facing a similar issue.

**Comment by 0ff** [comment]
Hi @einfallstoll - our hosts are in fact also running behind a NAT but unfortunately I wasn't able to reproduce the error when replicating the setup and upgrading in the same way.

I guess @leodotcloud was correct in that the whole problem was caused by the `Timeout getting IP address` error instead of the new `network-policy-manager`.
In the end, restarting rancher-agent fixed it for us too (our hosts did know about their correct IPs) and so I think the issue can be closed.

**Comment by einfallstoll** [comment]
Ok, great. So this issue can be closed now :)
