### ISSUE TITLE
API Key does not work with rancher-server v1.4.0

### ISSUE THREAD

**Issue by potzkovge** [rancher/rancher#7701]
**Rancher Versions:**
Server: 1.4.0
healthcheck: v0.2.3
ipsec: holder
network-services: v0.7.0 v0.4.5
scheduler: v0.6.3

**Docker Version:**
Docker version 1.12.3, build 6b644ec
**OS and where are the hosts located? (cloud, bare metal, etc):**
ros os version
v0.7.1
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher,  internal DB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
installed v1.4.0 from scratch and tried to create a user stack in the default environment (downloaded the new rancher-compose version v0.12.2

i already tried to create a new API Key same result different API Key
**Results:** 
ERRO[0000] Failed to open project haproxy-mikroways: Can not create a stack, check API key [4144AEF710AF4F02C653] for [http://192.168.10.113:8080/]
FATA[0000] Failed to read project: Can not create a stack, check API key [4144AEF710AF4F02C653] for [http://192.168.10.113:8080/]

**Comment by deniseschannon** [comment]
Do you have an environmnt API key or account API key?

The default API key type in the API section is "Account" which is used with Rancher CLI, but in the "Advanced OPtions" you can find an environment key for rancher-compose.

**Comment by potzkovge** [comment]
Thanks i used an older version of rancher before where it was only the environment API key. i feel stupid now...
