### ISSUE TITLE
Upgrading stack never finishes

### ISSUE THREAD

**Issue by shoutcool** [rancher/rancher#7709]
**Rancher Versions:**
Server: 1.4.0
healthcheck: v0.2.3
ipsec: v0.8.7
network-services: v0.4.5
scheduler: v0.6.3

**Docker Version:**
1.12

**Steps to Reproduce:**
1. Start some image (e.g. Sonarqube) from catalog.
2. Open the API View of the Stack
3. Push the upgrade button on the right and enter invalid data for dockerCompose and rancherCompose and some new external id:

_dockerCompose:_
sonarqube-foo: 
   a: 1
   b: 2 

_rancherCompose:_
.catalog: 
   a: 1
   b: 2 

_externalId:_
Sonar2

4. Send the Request
5. Rancher answers with http code 202 --> so everything seems OK
6. But if you take a look at the rancher logs you will find following errors:

<pre>time="2017-02-04T00:33:16Z" level=info msg="Upgrade Stack Event Received" eventId=e4ce1caa-4d4d-4912-afb5-69f4aa0616a0 resourceId=1st6
time="2017-02-04T00:33:16Z" level=error msg="Could not parse config for project sonarqube : Unsupported config option for b service: 'a'\nUnsupported config option for sonarqube-foo service: 'b'"
time="2017-02-04T00:33:16Z" level=error msg="Stack Upgrade Event Failed: Unsupported config option for b service: 'a'\nUnsupported config option for sonarqube-foo service: 'b'" eventId=e4ce1caa-4d4d-4912-afb5-69f4aa0616a0 resourceId=1st6 
2017-02-04 00:33:16,489 ERROR [:] [] [] [] [cutorService-13] [.e.s.i.ProcessInstanceDispatcherImpl] Unknown exception running process [stack.upgrade:2121] on [6], canceled by [State [upgrading] is not valid for process [stack.error:2132] on resource [6]] 
</pre>

**Results:** 
On the Rancher UI the Stack is still showing the "upgrading" animation but the upgrade will never finish.

There is no way to programmatically find out that the upgrade failed --> State is still "upgrading". Nothing seems wrong.

**Comment by tfiduccia** [comment]
UI - From a UI perspective, you are not able to enter bad data.  So this would have to be fixed in the backend (shouldn't return ok with bad data).

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
