### ISSUE TITLE
Split Rancher images?

### ISSUE THREAD

**Issue by TheAifam5** [rancher/rancher#7710]
Hey,
Actually Rancher can be installed with docker image.
I think would be nice when Rancher will split into specific packages like "server" and "ui".
"server" package will be like actual Rancher image but without UI.
"ui" can be installed optionally or at local machine.

Regards,
Mateusz Paluszkiewicz

**Comment by superseb** [comment]
The UI repository has instructions to run it locally, and we provide a single Docker image because it also needs to run airgapped/without internet.
