### ISSUE TITLE
Processes page theme issue

### ISSUE THREAD

**Issue by pulberg** [rancher/rancher#7712]
**Rancher Versions:**
Server: 1.4.0
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker Version:**
1.12.6
**OS and where are the hosts located? (cloud, bare metal, etc):**
RHEL 7.3, vmware esxi
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node, external db
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
n/a
**Steps to Reproduce:**
v1.4.0, use "dark" theme, view "Admin --> Processes".
**Results:** 
Tabs and content area not dark themed.  Tested in Chrome and FF on Mac OS X 10.12.3

![screen shot 2017-02-06 at 6 43 09 pm](https://cloud.githubusercontent.com/assets/11069351/22673125/da0f6322-ec9d-11e6-866a-ee7b29d507f3.png)

**Comment by tfiduccia** [comment]
Version - master 2/6
Yep, checked and the grid is white.  Should match grid on container's page.

**Comment by westlywright** [comment]
@tfiduccia i think this got resolved somewhere along the line that the ticket was never moved.

**Comment by pulberg** [comment]
@westlywright I still see this in v1.6.1, and is tagged v2.0 -

![screen shot 2017-06-08 at 2 13 20 pm](https://user-images.githubusercontent.com/11069351/26946406-c04eb16a-4c54-11e7-8827-ce7fc70f9777.png)

**Comment by westlywright** [comment]
@pulberg the fix has probably not been released to the wild yet

**Comment by pulberg** [comment]
@westlywright after 4 months, I practically don't care anymore...  If it comes down to improving etcd in my k8s envs vs. theme colors, i'll gladly take etcd 👍

**Comment by tfiduccia** [comment]
Version - Wagyu 6/8
Verified fixed.
@pulberg - this fix will not show up in any of the 1.6 versions.

**Comment by vincent99** [comment]
@pulberg Not helpful.  Whatever the problem with etcd is, the UI team isn't going to be the one fixing it.

**Comment by pulberg** [comment]
@vincent99 obviously, it was a comment in relation to prioritization of resources/tasks.
