### ISSUE TITLE
Webhook-service scaleHost driver

### ISSUE THREAD

**Issue by mrajashree** [rancher/rancher#7713]
Add driver for scaling up/down hosts for webhook-service

**Comment by mrajashree** [comment]
@cjellick , I discussed with Sangeetha and Soumya and these are some of the questions/edge cases that aren't considered yet:
1. While creating webhooks, the user selects a label, so if there's no host with that label should we still allow webhook creation? Because while executing we're as it is checking if there are hosts with the label. Currently we don't allow creation of such webhooks and I think this is fine but I can change it.
2. We are using labels as selectors to differentiate the host scaling groups. But users can edit these label or add the same label to a host that should not be a part of this host scaling group. So should we also add some internal label to hosts from one group, such that this internal label is not shown/is readonly for users. This will maintain integrity of the labels wrt hostscaling groups.
3. I haven't separated hosts in `Error` state from `Active` hosts while scaling up/down. So I will change that to remove such hosts from the logic to clone/decide number of hosts in the host scaling group.
4. Hosts in reconnecting, disconnected or deactivated state might go to Active state. So should we consider these a part of host scaling group for scaling up/down or not? How should they affect scale up/down logic?
5. While scaling down we provide options to remove Most recent/least recently added hosts. Should hosts in state disconnecting/reconnecting/deactivated state be given priority over this order?
6. Right now we're using the first created host as base host for cloning. So should we tell the user which host we used since the entire config, resources of this base host will be used for all new hosts?
7. I'm using only the host label as selector, and only checking if the key:value pair in webhook and that in the host label are an exact match. So should this behavior be changed so we can include other comparators in these selectors, or if not then should we not call it a selector?

Also I've only been trying with Digital Ocean, I will try the current code with some other driver that is not enabled by default.

**Comment by mrajashree** [comment]
- [ ] No scaling for custom hosts (driver = nil)

- [ ] While executing, at least one host in the scaling group should be present

**Comment by cjellick** [comment]
> While creating webhooks, the user selects a label, so if there's no host with that label should we still allow webhook creation? Because while executing we're as it is checking if there are hosts with the label. So I've changed this to allow webhook creation even when no host with that  label exists

Agree with this.

> We are using labels as selectors to differentiate the host scaling groups. But users can edit these label or add the same label to a host that should not be a part of this host scaling group. So should we also add some internal label to hosts from one group, such that this internal label is not shown/is readonly for users. This will maintain integrity of the labels wrt hostscaling groups.
As we have discussed, labels are entirely upto the user. So no internal labels will be added

Agree

> I haven't separated hosts in `Error` state from `Active` hosts while scaling up/down. So I will change that to remove such hosts from the logic to clone/decide number of hosts in the host scaling group.

Makes sense.

> Hosts in reconnecting, disconnected or deactivated state might go to Active state. So should we consider these a part of host scaling group for scaling up/down or not? How should they affect scale up/down logic?

Good question. For scale down, I would definitely target disconnected, reconnecting, inactive first, in that order. But if you cannot squeeze that in, it does not need to be in this release. For scale up, I don't think it matters much. For min/max calculation, I would include these hosts in the count.

> While scaling down we provide options to remove Most recent/least recently added hosts. Should hosts in state disconnecting/reconnecting/deactivated state be given priority over this order?

Seems to me that we cannot give the user the option to specify most/least recent and then violate that by picking one that is in one of those states. However, if we let them specify that as another option, that would work. So, they would pick between most or least recent and then also check a box for "When scaling down, first remove hosts in bad states." I'll get @vincent99 input on this.

> Right now we're using the first created host as base host for cloning. So should we tell the user which host we used since the entire config, resources of this base host will be used for all new hosts?

The UI could _perhaps_ make a note of it. But  the contract of the webhook is that any host in the group is a valid candidate for cloning. We should not allow them to specify any further than that.

> I'm using only the host label as selector, and only checking if the key:value pair in webhook and that in the host label are an exact match. So should this behavior be changed so we can include other comparators in these selectors, or if not then should we not call it a selector?

What you have now is fine for this release. If we get requests for more types of selector operations, we can add them.

**Comment by cjellick** [comment]
@mrajashree after talking with vincent, lets just _always_ prefer "bad" hosts. We dont need to add a flag to the API. Vince will just make a note of it in the UI.

**Comment by soumyalj** [comment]
Tested with master. Feature to scale hosts through webhooks is functional.
