### ISSUE TITLE
Backup local user db

### ISSUE THREAD

**Issue by geostant** [rancher/rancher#7716]
**Rancher Versions:**
Server: 1.4.0

**Docker Version:**
1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node

Is it possible to backup and restore the local user db for authentication ?
I've several ranchers installed across our environments and I would like to sync the users across all of them.

Thanks

**Comment by superseb** [comment]
No this is unsupported.
