### ISSUE TITLE
Rancher HA in another Rancher standalone

### ISSUE THREAD

**Issue by Negashev** [rancher/rancher#7719]
**Rancher Versions:** v1.3.4
Server: 
healthcheck: v0.2.0
ipsec: net: holder
network-services: metadata:v0.7.0/manager:v0.4.0
scheduler: v0.5.1
kubernetes (if applicable): None

**Docker Version:** 1.12.*

**OS and where are the hosts located? (cloud, bare metal, etc):** cloud/bare metal

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:**

1. Create mysql
2. Create Rancher server with link to mysql
3. Scale Rancher server
![screenshot 3](https://cloud.githubusercontent.com/assets/4653589/22685677/1082f496-ed43-11e6-9d3e-51ebdcb6ef49.png)

**Results:** 
![screenshot 4](https://cloud.githubusercontent.com/assets/4653589/22685844/babdb932-ed43-11e6-96f4-c79a70fbbf7b.png)

secondary node waiting on

```
[main] [ConsoleStatus] Starting DB migration
[main] [ConsoleStatus] DB migration done
[main] [ConsoleStatus] Cluster membership changed [127.0.0.1:9345]
[main] [ConsoleStatus] Checking cluster state on start-up
[main] [ConsoleStatus] Waiting to become master
```

**Question:** 
How I can create true stack?

for example
![screenshot 2](https://cloud.githubusercontent.com/assets/4653589/22685887/de5faca6-ed43-11e6-9c52-3d6f29038412.png)

**Comment by vincent99** [comment]
The advertise addresses are both localhost.  They need to be different and mutually reachable.

**Comment by Negashev** [comment]
Ok I find in doc option `--advertise-address` and start rancher server with command `--advertise-address eth0`
