### ISSUE TITLE
Long render ui

### ISSUE THREAD

**Issue by Negashev** [rancher/rancher#7720]
**Rancher Versions:** v1.3.4
Server: 
healthcheck: v0.2.0
ipsec: net: holder
network-services: metadata:v0.7.0/manager:v0.4.0
scheduler: v0.5.1
kubernetes (if applicable): None

**Docker Version:** 1.12.*

**OS and where are the hosts located? (cloud, bare metal, etc):** cloud/bare metal

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:**

after upgrade from 1.1 to 1.2

**Results:** 

**ui open arter 2.5 minutes!**
7 env
~50-170 containers in env
~1-16 servers in env
![1](https://cloud.githubusercontent.com/assets/4653589/22689222/bec2b178-ed51-11e6-8d16-bd7225e976de.png)

**Comment by HenryTheSir** [comment]
Seams simular to : https://github.com/rancher/rancher/issues/7548

**Comment by vincent99** [comment]
Yes, run 1.1 cleanup script, 15,000 volunteers is not good.

See `docker run --rm rancher/cleanup-1-1` for usage.

**Comment by Negashev** [comment]
Thanks! It helped, but for older `env's`, ui is still a very long time is something to consider mounts

**Comment by aemneina** [comment]
Closing as cleanup helped here.
