### ISSUE TITLE
Timer in UI that shows how long container has been running

### ISSUE THREAD

**Issue by jamrizzi** [rancher/rancher#7722]
This is just a feature request for a timer in the UI that shows how long a container has been running.

**Comment by loganhz** [comment]
![image](https://user-images.githubusercontent.com/21168270/37136435-a569eb08-22dc-11e8-8ee4-00e88a1af26f.png)

**Comment by tfiduccia** [comment]
Version - 2.0 master 3/26
Verified fixed.
