### ISSUE TITLE
Webhok 1.4 version, 404 Not Found

### ISSUE THREAD

**Issue by VAdamec** [rancher/rancher#7723]
**Rancher Versions:**
Server: 1.4.0
healthcheck: 0.2.3
ipsec: net:v0.8.7
network-services: net:v0.8.7
scheduler: scheduler:v0.6.3

**Docker Version:**
1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):**
Oracle Linux 7

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher with external DB (galera)

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Start simple stack application - Wordpress
Create webhooks - scale-down-wordpress and scale-up-wordpress
Call URLs

**Results:** 

```404 Not Found```

```
curl -v http://rancher-ui.example.com/v1-webhooks/endpoint\?token\=xxxxxxxx

*   Trying xxx.xxx.xxx.xxx...
* TCP_NODELAY set
* Connected to rancher-ui.example.com (xxx.xxx.xxx.xxx) port 80 (#0)
> GET /v1-webhooks/endpoint?token=xxxxxxxx HTTP/1.1
> Host: rancher-ui.example.com:9000
> User-Agent: curl/7.51.0
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Content-Length: 19
< Content-Type: text/plain; charset=UTF-8
< Date: Tue, 07 Feb 2017 14:19:29 GMT
< Expires: Thu, 01 Jan 1970 00:00:00 GMT
< Server: Jetty(9.2.11.v20150529)
< Set-Cookie: PL=rancher;Path=/
< X-Api-Schemas: http://rancher-ui.example.com/v1/schemas
< X-Content-Type-Options: nosniff
< X-Rancher-Version: v1.4.0
<
404 page not found
```

**Comment by mrajashree** [comment]
The path `/v1-webhooks/endpoint?` accepts a POST request to execute the webhook. GET requests won't get any response. 
So `> GET /v1-webhooks/endpoint?token=xxxxxxxx HTTP/1.1` is giving 404

**Comment by VAdamec** [comment]
Ahh, sorry I miss it in documentation
