### ISSUE TITLE
Feature Request: Option to choose shell for Execute Shell

### ISSUE THREAD

**Issue by ecliptik** [rancher/rancher#7727]
**Rancher Versions:**
Server: 1.2.2
healthcheck: v0.2.0
ipsec: v0.8.1
network-services: v0.4.0
scheduler: v0.5.0

**Docker Version:**
1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):**
AWS EC2

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single-node
MySQL RDS external
Amazon Linux 2016.09

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
cattle

**Steps to Reproduce:**

I think this is related to how docker exec in the Rancher UI is calling a shell. Most of our containers are using `FROM alpine` and we do not install the bash package, so `/bin/sh` is the only available shell.

With Rancher 1.1.4 using the UI to exec into a container worked fine, but with 1.2 it immediately errors out. When I try to docker exec into the container from the host, I get:

```
[ec2-user@ip-10-9-2-201 ~]$ sudo docker exec -it 2030471e1d67 /bin/bash
rpc error: code = 2 desc = "oci runtime error: exec failed: exec: \"/bin/bash\": stat /bin/bash: no such file or directory"[ec2-user@ip-10-9-2-201 ~]$ sudo docker exec -it 2030471e1d67 /bin/sh
However, when I do sudo docker exec -it 2030471e1d67 /bin/sh it works.
```

Was there a change in 1.2 where `/bin/bash` is the default shell to exec into from the UI? I searched through the code base but didn't find anything.

If this is the case, and `/bin/bash` is default now, could we put in a feature request to make an option to change the default exec shell in the Admin section.

This was originally mentioned in https://github.com/rancher/rancher/issues/6861

**Comment by superseb** [comment]
What AMI ID to make sure I test on the correct AMI?

**Comment by ecliptik** [comment]
@superseb we're using `ami-23e8a343` in us-west-1.

We do a few additional things with user-data, such as installing docker, setting up Rancher, and adding a few telemetry things like New Relic and cloudwatch but no major modifications.

**Comment by superseb** [comment]
Ok, can you post the output of `docker version` and `rpm -q docker` ?

**Comment by ecliptik** [comment]
@superseb 

```
[ec2-user@ip-10-9-2-227 ~]$ sudo docker version
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   7392c3b/1.12.6
 Built:        Fri Jan  6 22:16:21 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   7392c3b/1.12.6
 Built:        Fri Jan  6 22:16:21 2017
 OS/Arch:      linux/amd64
[ec2-user@ip-10-9-2-227 ~]$ rpm -q docker
docker-1.12.6-1.17.amzn1.x86_64
```

**Comment by vincent99** [comment]
The command is [here](https://github.com/rancher/ui/blob/master/app/components/container-shell/component.js#L5) and jumps through all sorts of hoops to see if bash exists, set TERM, work if screen/tmux is used, etc but hasn't changed in probably a year.

**Comment by superseb** [comment]
Thanks @vincent99 , wanted to reproduce because I couldn't believe it changed. We have a lot of containers with only `/bin/sh`.

@ecliptik Can you give me a reproducable case with a container? If I launch Amazon Linux with Rancher 1.2.2 and run container `alpine` I can Execute shell from the GUI.

**Comment by ecliptik** [comment]
@vincent99 that seems like that should do it and use `/bin/sh` if it's there. Not sure why then it wouldn't be working since the 1.2 upgrade.

@superseb  We've gone through our alpine based images and just added the `bash` package for now and `Execute Shell` is working. I can try to go through today and re-deploy an older image where it wasn't working and see if I can reproduce it. This issue was opened after being in https://github.com/rancher/rancher/issues/6861 a month ago and may not be relevant any longer.

I'll close this out as a feature request and if I can reproduce it again or someone else runs into a similar issue it can be re-opened as a potential bug.
