### ISSUE TITLE
Adding registry to environment running kubernetes not working in rancher 1.4.0

### ISSUE THREAD

**Issue by ryanwalls** [rancher/rancher#7728]
**Rancher Versions:**
Server: 1.4.0

**Docker Version:**
1.13.1 

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 14.04.5 LTS, hosted in EC2, t2.small instance

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node, external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
Create rancher server with latest tag.  Create k8s environment.  Add quay.io registry and credentials.

**Results:** 
I'm getting 403 "failed to pull image".  These same credentials and registry were working in 1.3.3.

**Comment by tfiduccia** [comment]
@ryanwalls - I cannot reproduce your issue.  Can you try a couple of things? Can you please completely delete the registry and re-enter it.  If that doesn't work can you add it to a cattle environment and see if it works there?

**Comment by ryanwalls** [comment]
@tfiduccia Must have been some sort of race condition.  After waiting until today, the same pulls started succeeding again.  Thanks.
