### ISSUE TITLE
Can't add host if the host running external scheduler went down and was not re-scheduled to another host due to no healthchecks being active in Rancher

### ISSUE THREAD

**Issue by StrongMonkey** [rancher/rancher#7729]
**Rancher Versions:**
1.4 
If the host which run external scheduler went down, the scheduler is still reported as healthy and active in cattle database, Thus when adding another host, all the microservice containers on the second host will still find the dead scheduler to delegate scheduler requests. That will cause those container stuck at scheduling phase and failed to start because the dead scheduler can't reply to those events.

**Comment by deniseschannon** [comment]
@chrisurwin has verified this is fixed in v1.4.1-rc1
