### ISSUE TITLE
Kuberentes api responds with timeout about 1 out of 10 times

### ISSUE THREAD

**Issue by ryanwalls** [rancher/rancher#7731]
**Rancher Versions:**
Server: 1.4.0
kubernetes (if applicable): 1.5.2

**Docker Version:**
1.13.1-rc2

**OS and where are the hosts located? (cloud, bare metal, etc):**
AWS on t2.small.  DB is t2.small as well.

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single with external db

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
K8s

**Steps to Reproduce:**
Regular setup.  Run multiple api commands from a script.

**Results:** 
Periodically get:

```
Error from server (ServerTimeout): the server cannot complete the requested operation at this time, try again later 
```

**Comment by superseb** [comment]
Closing as stale.
