### ISSUE TITLE
[ui] Minimal Docker version for host not displayed because minDockerVersion is missing

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#7734]
**Rancher Versions:**
Server: 1.4.0

**Steps to Reproduce:**
1) Start rancher/server:v1.4.0
2) Open the GUI and the notification bar states: `Before adding your first service or launching a container, you'll need to add a Linux host that supports Docker or higher. `

**Results:** 
See above.

This commit (https://github.com/rancher/cattle/commit/dd705a1e365a74b436bf7d07cb4ffa6d4f4302a9) removed `ui.min.docker.version=v1.10.3` and added `supported.docker.range=~v1.10.3 || ~v1.12.3`. Not sure if you want to display that or just link to the supported Docker versions page.

cc @vincent99

**Comment by vincent99** [comment]
Sigh; that should probably link to the docs and say supported version too like the other one you changed.

**Comment by superseb** [comment]
https://github.com/rancher/ui/pull/1018

**Comment by superseb** [comment]
Merged, closing
