### ISSUE TITLE
Is Rancher DNS case sensitive ?

### ISSUE THREAD

**Issue by twoeo** [rancher/rancher#7737]
**Rancher Versions:**
Server:1.4.0

Use nginx to proxy to service by service_name.stack_name.

It works in 1.1.x version.

After upgrade to 1.4.0, there is an error that `resolver cannot resolve huskyhome.indexserver`.

My service name and stack name is `HuskyHome.IndexServer`, while nginx tell me cannot resolve `huskyhome.indexserver`. (seems because of case)

But it deed works in previous version, so is Rancher DNS be case insensitive before, but be sensitive now ?

**Comment by vincent99** [comment]
No; DNS in general is not case-sensitive or -preserving.
