### ISSUE TITLE
1.4.0 Upgrade breaks Kubernetes 

### ISSUE THREAD

**Issue by Dmitry1987** [rancher/rancher#7740]
A bug report,
**Rancher agents version: 1.1.3**
**Rancher Versions:**
Server: 1.4.0
kubernetes (if applicable):
1.5.1
**OS and where are the hosts located? (cloud, bare metal, etc):**
RancherOS latest AMI,   AWS
**HA rancher,  external DB**
**Environment Type: Kubernetes**
**Steps to Reproduce:**
upgrade 3 master rancher nodes from 1.3.3 to 1.4.0  with live kubernetes environments and nodes
**Results:** 
rancher lost all connection or sync with its agents on kubernetes minions... I have 4 k8s nodes, 1 cattle node, 3 rancher masters, 1 external db.

![image](https://cloud.githubusercontent.com/assets/9369080/22730437/acc2d7c0-edef-11e6-8c46-53148126c457.png)

now I have no idea if to just restart rancher agents on all nodes, or reattach nodes somehow from scratch, with launch of new agents... all k8s env is broken :( .

**Comment by Dmitry1987** [comment]
The stack looks like this after upgrade:

![image](https://cloud.githubusercontent.com/assets/9369080/22730928/944680be-edf1-11e6-948e-9920f9135435.png)

I updated all components then, both rancher and k8s, like healthcheck, ipsec,scheduler, etc'
but it remains in red.  probably because it thinks has no hosts.

oh, and the agents all show this in logs:
```
INFO: Starting agent for 0D62BC70B58DF4C7DCA4
ERROR: Credentials are no longer valid, please re-register this agent
```

so, question is, why this happened, and how to avoid in future? :)

**Comment by deniseschannon** [comment]
When upgrading did anything change? Did the IP of your Rancher server change?

It seems as if your agents can't connect with Rancher server. If you go to "Add Host" and grab the command from the "Custom" option, you can re-register your agents, but running the command again.

**Comment by Dmitry1987** [comment]
Hi @deniseschannon , 
before and after upgrade - all instances were with same IPs, no changes.
agent was not the latest 1.2.0 (but 1.1.3) , maybe this is the reason.
I was able to re-register them, but this is still a bug report  =) , others might run production and this will break their 100 hosts with no easy command at hand to re-register them all quickly back...   
it worth to check why happens.   Thanks!

**Comment by deniseschannon** [comment]
In our QA, we upgrade HA setups in kubernetes and did not have this issue, so I'm not sure why this could have occurred in your setup and not our test setups.

**Comment by superseb** [comment]
Thanks for reporting, I can start reproducing now but I don't think its worth the effort. Please file a new issue when it occurs so we can investigate.
