### ISSUE TITLE
Rancher CLI --system option not respected while installing catalog

### ISSUE THREAD

**Issue by wlan0** [rancher/rancher#7741]
When I install a system catalog from the rancher cli (v0.4.1) using --system flag, then the stack that I create does not show up in the Infrastructure stacks menu.

If I look in the API, the the system parameter of the stack is set to false, even though I specified it in the CLI.

Rancher version: v1.4.0

Environment: Cattle

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
