### ISSUE TITLE
mainpage can't display before new mesos or kubernetes worked

### ISSUE THREAD

**Issue by godcong** [rancher/rancher#7742]
**Rancher Versions:**
Server: 1.4
healthcheck: v0.2.3:rancher/healthcheck:v0.2.3   
ipsec: v0.0.4:rancher/net:holder 
network-services: v0.0.10: rancher/metadata:v0.7.0 rancher/network-manager:v0.4.5  
scheduler: v0.4.0:rancher/scheduler:v0.6.3
kubernetes/mesos (if applicable): any

**Docker Version:
1.12.5

**OS and where are the hosts located? (cloud, bare metal, etc):
centos7

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)
single node rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)
 Mesos/Kubernetes

**Steps to Reproduce:**
when i create a new [mesos or kubernetes]
if mesos is not work well
i cant  see the main page
like: http://192.168.1.201:8080/env/1a5/mesos
**Results:** 
a page only displayed with background color

**Comment by tfiduccia** [comment]
@godcong - I am unable to reproduce your issue.  I created a CentOS7 machine through Digital Ocean and put rancher on it.  I then created a Kubernetes and Mesos environment and went to those environment and the page came up fine.  Can you provide more information?

**Comment by godcong** [comment]
today is ok...
i think i missed some steps...

**Comment by dlaplexurenet** [comment]
godcong, what did you do in order that it works now?
