### ISSUE TITLE
Network Policy Phase 2

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#7743]
The following two rules will be supported as part of phase 2.

```
{
  "within": "service",
  "action": "allow"/"deny"
}
```

```
{
  "within": "linked",
  "action": "allow"/"deny"
}
```

**Comment by sangeethah** [comment]
```within service``` and ```within linked``` are available with rancher/network-policy-manager:v0.2.1.

Issues found when testing this feature is tracked as different issues - 
https://github.com/rancher/rancher/issues?q=is%3Aissue+author%3Asangeethah+label%3Aarea%2Fnetwork-policy+milestone%3A%22Release+1.5.0%22
