### ISSUE TITLE
Kubernetes and persistent storage

### ISSUE THREAD

**Issue by GuillaumeM69** [rancher/rancher#7745]
Hello,
I host 4 CoreOS nodes on a hyperV cluster. What solution would you recommend for persistent storage on a kubernetes environment with rancher 1.4? Rancher-nfs being incompatible in catalogue. I am looking for a simple and fairly robust solution. 
Thanks for your advices.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
