### ISSUE TITLE
With network policy set to allow within linked services / allow within service , sidekick containers are not reachable.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#7748]
Rancher Versions: Build from master
Network policy manager version - rancher/network-policy-manager:v0.2.0

With network policy set to allow within linked services / allow within service , sidekick containers are not reachable.

Steps to reproduce the problem:

Scenario1:
Create a stack.
Create a service - S1 with side kick - SK1.
Set Network policy to ```{"within": "service", "action": "allow"} ``` and defaultPolicyAction set to ```deny```.

From instances of S1 , try to ping (/access) instances of SK1.
Not able to ping instances of SK1.

From instances of SK1 , try to ping (/access) instances of SK.
Not able to ping instances of SK.

Expected Behavior:
Instances of SK1 should be reachable from instances of S1.
Instances of S1 should be reachable from instances of SK1.

Scenario 2:
Create a stack -T1.
Create a service - S1 with side kick - SK1.
Set Network policy to ```{"within": "linked", "action": "allow"} ``` and defaultPolicyAction set to ```deny```.

Create a service - S2 which is linked to S1.

From instances of S2 , try to ping (/access) instances of SK1.
Not able to ping instances of SK1.

Expected Behavior:
Instances of SK1 should be reachable from instances of S2.

**Comment by leodotcloud** [comment]
Fixed this issue with `rancher/network-policy-manager:v0.2.1`

**Comment by sangeethah** [comment]
Tested with latest build from master and rancher/network-policy-manager:v0.2.1

Steps to reproduce the problem:

Scenario1:
Create a stack.
Create a service - S1 with side kick - SK1.
Set Network policy to  ```{"within": "service", "action": "allow"} ``` and defaultPolicyAction set to deny.

From instances of S1 , try to ping (/access) instances of SK1.
Able to ping instances of SK1.

From instances of SK1 , try to ping (/access) instances of SK.
Able to ping instances of SK.

Scenario 2:
Create a stack -T1.
Create a service - S1 with side kick - SK1.
Set Network policy to ```{"within": "linked", "action": "allow"}``` and defaultPolicyAction set to deny.

Create a service - S2 which is linked to S1.

From instances of S2 , try to ping (/access) instances of SK1.
Able to ping instances of SK1 and S1.
