### ISSUE TITLE
rancher server 's memory usage increase too large

### ISSUE THREAD

**Issue by duluosheng** [rancher/rancher#7750]
**Rancher Versions:**
Server:1.4.0
healthcheck:0.2.3
ipsec:0.0.4
network-services:0.0.10
scheduler:0.4.0

**Docker Version:**
1.12.6
**OS and where are the hosts located? (cloud, bare metal, etc):**
CentOS 7.3 with kernel 4.4.22 on Aliyun ECS
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node, Aliyun RDS, IOPS 600
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
I upgrade rancher version from 1.1.4 to 1.3.3, and upgrade docker version from 1.2.0 to 1.2.6.
after that I upgrade rancher version to 1.4.0.
**Results:** 
my rancher server's memory usage increase from 512m to 6GB, and it is still increasing. (I set -m 8GB to this container)
When I enter to the container, I find that it is the java progress cause this.
The progress:
 java -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -Xms128m -Xmx4g -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/var/lib/cattle/logs -Dlogback.bootstrap.level=WARN -cp /usr/share/cattle/f7a48ecb251f47be0327fa235781109c:/usr/share/cattle/f7a48ecb251f47be0327fa235781109c/etc/cattle io.cattle.platform.launcher.Main

Current logs:
2/9/2017 10:27:48 AMtime="2017-02-09T02:27:48Z" level=info msg="Shutting down backend df1cc4c5-8062-4e27-8a1e-e92330b3ce43. Connection closed because: websocket: close 1006 unexpected EOF."
2/9/2017 10:27:48 AMtime="2017-02-09T02:27:48Z" level=info msg="Removed backend. Key: df1cc4c5-8062-4e27-8a1e-e92330b3ce43. Session ID edaf8884-7407-4b38-9fbc-407081c1d922 ."
2/9/2017 10:27:50 AMtime="2017-02-09T02:27:50Z" level=info msg="Shutting down backend 58635ffb-ea07-4039-82f1-ce50350c1488. Connection closed because: websocket: close 1006 unexpected EOF."
2/9/2017 10:27:50 AMtime="2017-02-09T02:27:50Z" level=info msg="Removed backend. Key: 58635ffb-ea07-4039-82f1-ce50350c1488. Session ID 557dccbc-c210-4aef-9695-c19068ea3eb5 ."
2/9/2017 10:27:56 AMtime="2017-02-09T02:27:56Z" level=info msg="Handling backend connection request."
2/9/2017 10:27:56 AMtime="2017-02-09T02:27:56Z" level=info msg="Registering backend for host df1cc4c5-8062-4e27-8a1e-e92330b3ce43 with session ID be41c6d5-151c-4cd8-ad0d-8c476fd219bf."
2/9/2017 10:27:57 AMtime="2017-02-09T02:27:57Z" level=info msg="Handling backend connection request."
2/9/2017 10:27:57 AMtime="2017-02-09T02:27:57Z" level=info msg="Registering backend for host 58635ffb-ea07-4039-82f1-ce50350c1488 with session ID b02cf5c5-87ec-4d81-a358-8390a973f7dd."
2/9/2017 10:27:57 AMtime="2017-02-09T02:27:57Z" level=info msg="Exiting go-machine-service"
2/9/2017 10:27:57 AMtime="2017-02-09T02:27:57Z" level=info msg="Shutting down backend 9e46e80f-f60e-43df-9c95-dda158c8723d. Connection closed because: websocket: close 1006 unexpected EOF."
2/9/2017 10:27:57 AMtime="2017-02-09T02:27:57Z" level=info msg="Removed backend. Key: 9e46e80f-f60e-43df-9c95-dda158c8723d. Session ID 55b84997-6e13-4206-a313-1a3d51a44325 ."
2/9/2017 10:27:57 AMtime="2017-02-09T02:27:57Z" level=info msg="Shutting down backend e5f3e851-1d8e-45e3-b648-e706853aa5ef. Connection closed because: websocket: close 1006 unexpected EOF."
2/9/2017 10:27:57 AMtime="2017-02-09T02:27:57Z" level=info msg="Removed backend. Key: e5f3e851-1d8e-45e3-b648-e706853aa5ef. Session ID 795c876c-9c2d-4d04-afdc-88749568600a ."
2/9/2017 10:27:58 AMtime="2017-02-09T02:27:58Z" level=info msg="Setting log level" logLevel=info
2/9/2017 10:27:58 AMtime="2017-02-09T02:27:58Z" level=info msg="Starting go-machine-service..." gitcommit=v0.35.0
2/9/2017 10:27:58 AMtime="2017-02-09T02:27:58Z" level=info msg="Waiting for handler registration (1/2)"
2/9/2017 10:27:59 AMtime="2017-02-09T02:27:59Z" level=info msg="Initializing event router" workerCount=10
2/9/2017 10:27:59 AMtime="2017-02-09T02:27:59Z" level=info msg="Connection established"
2/9/2017 10:27:59 AMtime="2017-02-09T02:27:59Z" level=info msg="Starting websocket pings"
2/9/2017 10:27:59 AMtime="2017-02-09T02:27:59Z" level=info msg="Waiting for handler registration (2/2)"
2/9/2017 10:28:00 AMtime="2017-02-09T02:28:00Z" level=info msg="Initializing event router" workerCount=10
2/9/2017 10:28:00 AMtime="2017-02-09T02:28:00Z" level=info msg="Connection established"
2/9/2017 10:28:00 AMtime="2017-02-09T02:28:00Z" level=info msg="Starting websocket pings"
2/9/2017 10:28:00 AMtime="2017-02-09T02:28:00Z" level=info msg="Installing builtin drivers"
2/9/2017 10:28:00 AMtime="2017-02-09T02:28:00Z" level=info msg="Downloading all drivers"
2/9/2017 10:28:00 AMtime="2017-02-09T02:28:00Z" level=info msg="Done downloading all drivers"
2/9/2017 10:28:00 AMtime="2017-02-09T02:28:00Z" level=info msg="Shutting down backend 7fa095ea-f853-48cf-adf0-ca806aa65957. Connection closed because: websocket: close 1006 unexpected EOF."
2/9/2017 10:28:00 AMtime="2017-02-09T02:28:00Z" level=info msg="Removed backend. Key: 7fa095ea-f853-48cf-adf0-ca806aa65957. Session ID 696ec44c-91c3-4905-bc2a-c7354070740f ."
2/9/2017 10:28:02 AMtime="2017-02-09T02:28:02Z" level=info msg="Shutting down backend 50a2f634-6b61-4162-90b0-dd6c72e4596d. Connection closed because: websocket: close 1006 unexpected EOF."
2/9/2017 10:28:02 AMtime="2017-02-09T02:28:02Z" level=info msg="Removed backend. Key: 50a2f634-6b61-4162-90b0-dd6c72e4596d. Session ID f231a4cf-88c8-4b3c-8999-9211700ef7e7 ."
2/9/2017 10:28:02 AMtime="2017-02-09T02:28:02Z" level=info msg="Shutting down backend 0f979d7f-9f9d-4729-b613-17ea9a06d1b1. Connection closed because: websocket: close 1006 unexpected EOF."
2/9/2017 10:28:02 AMtime="2017-02-09T02:28:02Z" level=info msg="Removed backend. Key: 0f979d7f-9f9d-4729-b613-17ea9a06d1b1. Session ID 6fd48204-acbd-4226-9ed9-f86787ca963f ."
2/9/2017 10:28:02 AMtime="2017-02-09T02:28:02Z" level=info msg="Shutting down backend 3befc42f-2d1d-4749-87c2-3ec263eec0d2. Connection closed because: websocket: close 1006 unexpected EOF."
2/9/2017 10:28:02 AMtime="2017-02-09T02:28:02Z" level=info msg="Removed backend. Key: 3befc42f-2d1d-4749-87c2-3ec263eec0d2. Session ID dd285281-4aa9-4b47-a5e5-68c72791b4dc ."
2/9/2017 10:28:03 AMtime="2017-02-09T02:28:03Z" level=info msg="Handling backend connection request."
2/9/2017 10:28:03 AMtime="2017-02-09T02:28:03Z" level=info msg="Registering backend for host 9e46e80f-f60e-43df-9c95-dda158c8723d with session ID 0e63541f-0b46-4847-9a1c-0e998f7f1844."
2/9/2017 10:28:04 AMtime="2017-02-09T02:28:04Z" level=info msg="Handling backend connection request."
2/9/2017 10:28:04 AMtime="2017-02-09T02:28:04Z" level=info msg="Registering backend for host e5f3e851-1d8e-45e3-b648-e706853aa5ef with session ID cdd53422-b060-40a9-8da3-997f42ac72fc."
2/9/2017 10:28:05 AMtime="2017-02-09T02:28:05Z" level=info msg="Shutting down backend de8ae5ed-95f3-45be-a552-b8b5f153969d. Connection closed because: websocket: close 1006 unexpected EOF."
2/9/2017 10:28:05 AMtime="2017-02-09T02:28:05Z" level=info msg="Removed backend. Key: de8ae5ed-95f3-45be-a552-b8b5f153969d. Session ID 1a1918a0-f55e-4c51-8d17-da7829d1c957 ."
2/9/2017 10:28:06 AMtime="2017-02-09T02:28:06Z" level=info msg="Handling backend connection request."
2/9/2017 10:28:06 AMtime="2017-02-09T02:28:06Z" level=info msg="Registering backend for host 7fa095ea-f853-48cf-adf0-ca806aa65957 with session ID 02d5b3b3-9253-4ac4-b2ba-3677dacc56df."
2/9/2017 10:28:07 AMtime="2017-02-09T02:28:07Z" level=info msg="Exiting rancher-compose-executor" version=v0.12.2
2/9/2017 10:28:08 AMtime="2017-02-09T02:28:08Z" level=info msg="Starting rancher-compose-executor" version=v0.12.2
2/9/2017 10:28:08 AMtime="2017-02-09T02:28:08Z" level=info msg="Handling backend connection request."
2/9/2017 10:28:08 AMtime="2017-02-09T02:28:08Z" level=info msg="Registering backend for host 50a2f634-6b61-4162-90b0-dd6c72e4596d with session ID acaf725a-0cd3-467a-90b9-426e21ef125e."
2/9/2017 10:28:08 AMtime="2017-02-09T02:28:08Z" level=info msg="Handling backend connection request."
2/9/2017 10:28:08 AMtime="2017-02-09T02:28:08Z" level=info msg="Registering backend for host 3befc42f-2d1d-4749-87c2-3ec263eec0d2 with session ID 2567d4cd-bde5-4476-bab8-9b3b4470df59."
2/9/2017 10:28:09 AMtime="2017-02-09T02:28:09Z" level=info msg="Handling backend connection request."
2/9/2017 10:28:09 AMtime="2017-02-09T02:28:09Z" level=info msg="Registering backend for host 0f979d7f-9f9d-4729-b613-17ea9a06d1b1 with session ID d5e73953-a0d7-46b5-b1c5-c2a236a7bba3."
2/9/2017 10:28:10 AMtime="2017-02-09T02:28:10Z" level=info msg="Initializing event router" workerCount=10
2/9/2017 10:28:10 AMtime="2017-02-09T02:28:10Z" level=info msg="Connection established"
2/9/2017 10:28:10 AMtime="2017-02-09T02:28:10Z" level=info msg="Starting websocket pings"
2/9/2017 10:28:11 AMtime="2017-02-09T02:28:11Z" level=info msg="Handling backend connection request."
2/9/2017 10:28:11 AMtime="2017-02-09T02:28:11Z" level=info msg="Registering backend for host de8ae5ed-95f3-45be-a552-b8b5f153969d with session ID 7a6d7314-1afa-48d3-8b3c-c21db43d884a."
2/9/2017 12:17:10 PMtime="2017-02-09T04:17:10Z" level=error msg="Failed to pull the catalog from git repo https://git.rancher.io/community-catalog.git, error: exit status 1"
2/9/2017 12:17:10 PMtime="2017-02-09T04:17:10Z" level=info msg="Will not refresh the catalog since Pull Catalog faced error: exit status 1"
2/9/2017 1:10:11 PMtime="2017-02-09T05:10:11Z" level=error msg="Failed to pull the catalog from git repo https://git.rancher.io/rancher-catalog.git, error: exit status 1"
2/9/2017 1:10:11 PMtime="2017-02-09T05:10:11Z" level=info msg="Will not refresh the catalog since Pull Catalog faced error: exit status 1"

**Comment by beatcracker** [comment]
Yep, I have the same issue after 1.4 upgrade. My Rancher server instance is almost unusable.

**Comment by ibuildthecloud** [comment]
Are you running HA setup or not?  If you could please share what admin->processes->summary and pools (only on non-HA) pages show that would help.

**Comment by beatcracker** [comment]
Non-HA setup, nothing suspicious in the `admin->processes->summary and pools `. As I've said, upping memory worked for me. With 1GB VM was crawling due to heavy swapping.

Does v1.4.0 has higher memory requirements and [docs](http://docs.rancher.com/rancher/v1.4/en/installing-rancher/installing-server/#requirements) have to be updated or it's something that can be fixed?

**Comment by ibuildthecloud** [comment]
@beatcracker There were some core changes that were made that may have impacted memory.  We are looking at it.  It would be considered a bug if the memory needs are higher.

**Comment by beatcracker** [comment]
I'm back, Rancher ate my RAM again. Here is the `top` from the `rancher/server` container:

```
root@30c7757836f2:/# top -o %MEM -c
top - 22:40:11 up 7 days,  9:20,  0 users,  load average: 0.78, 1.48, 1.66
Tasks:  14 total,   1 running,  13 sleeping,   0 stopped,   0 zombie
%Cpu(s): 17.3 us,  4.3 sy,  0.0 ni, 77.2 id,  0.1 wa,  0.0 hi,  1.2 si,  0.0 st
KiB Mem:   1987912 total,  1946148 used,    41764 free,       40 buffers
KiB Swap:  2097148 total,   127172 used,  1969976 free.   360764 cached Mem

  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
    7 root      20   0 3274356 788492   8640 S  0.0 39.7   1554:21 java -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnable+
   23 mysql     20   0 1041492 487740   4148 S  0.0 24.5 618:25.87 /usr/sbin/mysqld --basedir=/usr --datadir=/var/lib/mysql +
  163 root      20   0  128764  13772   3632 S  0.0  0.7 168:54.51 websocket-proxy
  131 root      20   0  307408  11924   2928 S  0.0  0.6  27:53.48 rancher-catalog-service -configFile repo.json -refreshInt+
61770 root      20   0  195748   7904    332 S  0.0  0.4   0:08.07 go-machine-service
61771 root      20   0   16940   4840    580 S  0.0  0.2   0:04.12 rancher-compose-executor
21070 root      20   0   19804   3884   3376 S  0.0  0.2   0:00.03 bash
21107 root      20   0   21484   2792   2436 R  0.0  0.1   0:00.00 top -o %MEM -c
  186 root      20   0  110604   2752    264 S  0.0  0.1   0:15.25 rancher-auth-service
  162 root      20   0   26144     44      0 S  0.0  0.0   0:00.44 secrets-api server --enc-key-path .
    1 root      20   0     192      4      0 S  0.0  0.0   0:08.27 /usr/bin/s6-svscan /service
    5 root      20   0     192      0      0 S  0.0  0.0   0:00.00 s6-supervise cattle
    6 root      20   0     192      0      0 S  0.0  0.0   0:00.00 s6-supervise mysql
  164 root      20   0   29948      0      0 S  0.0  0.0   0:00.44 webhook-service
```

Is there a way to debug why it needs much more RAM now? I've been running previous versions of Rancher on VM with 1GB of memory and never had any issues.

**Comment by beatcracker** [comment]
Rancher did it again:

```
Tasks: 136 total,   1 running, 135 sleeping,   0 stopped,   0 zombie
%Cpu(s): 18.0 us,  4.5 sy,  0.0 ni, 76.2 id,  0.1 wa,  0.0 hi,  1.2 si,  0.0 st
KiB Mem :  1987912 total,    20236 free,  1714720 used,   252956 buff/cache
KiB Swap:  2097148 total,  1717104 free,   380044 used.   179196 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
29912 root      20   0 3337200 1.009g      0 S  0.0 53.2   3668:08 java -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -Xms128m -Xmx1g -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/var/lib/cattle/logs -Dlogback.bootstrap.lev+
29928 102       20   0 1050364 427152   1708 S  0.0 21.5   1545:45 /usr/sbin/mysqld --basedir=/usr --datadir=/var/lib/mysql --plugin-dir=/usr/lib/mysql/plugin --user=mysql --log-error=/var/log/mysql/error.log --pid-file=/var/run/mysqld+
```

I'm probably going to make a cron job restarting `rancher/server` container every 24 hours until this is fixed.

**Comment by ibuildthecloud** [comment]
@beatcracker Can you please try 1.5.1

**Comment by beatcracker** [comment]
@ibuildthecloud Upgraded to 1.5.1. I'll let it run for a while and let you know how it works out.

**Comment by beatcracker** [comment]
Rancher 1.5.1, running for two days:

```
top - 11:51:25 up 2 days, 23:38,  0 users,  load average: 0.02, 0.18, 0.45
Tasks:  13 total,   1 running,  12 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.7 us,  0.7 sy,  0.0 ni, 98.7 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem:   1995404 total,  1971816 used,    23588 free,        0 buffers
KiB Swap:  2097148 total,    78484 used,  2018664 free.   394776 cached Mem

  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
    7 root      20   0 3226464 1.007g   2404 S  0.3 52.9 656:30.09 java -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -+
   23 mysql     20   0  898840 219296      0 S  0.0 11.0 349:08.16 /usr/sbin/mysqld --basedir=/usr --datadir=/var/lib/mysql --p+
  150 root      20   0  142620  11152   3316 S  0.0  0.6   0:46.17 rancher-catalog-service --config repo.json --refresh-interva+
  198 root      20   0  125384   6736    764 S  0.0  0.3  42:30.31 websocket-proxy
24563 root      20   0  195656   5704    596 S  0.0  0.3   0:08.16 go-machine-service
24570 root      20   0   17068   4400      0 S  0.0  0.2   0:04.28 rancher-compose-executor
28683 root      20   0   21472   2852   2520 R  0.0  0.1   0:00.04 top -o %MEM -c
  214 root      20   0  112712   2704      0 S  0.0  0.1   0:05.91 rancher-auth-service
  218 root      20   0   26144    128     36 S  0.0  0.0   0:00.19 secrets-api server --enc-key-path .
  213 root      20   0   27324     80      0 S  0.0  0.0   0:00.17 webhook-service
    1 root      20   0     188     16      0 S  0.0  0.0   0:03.36 /usr/bin/s6-svscan /service
    5 root      20   0     188      0      0 S  0.0  0.0   0:00.00 s6-supervise cattle
    6 root      20   0     188      0      0 S  0.0  0.0   0:00.00 s6-supervise mysql
```

I'll keep container running to see if it hits 2Gb limit.

**Comment by beatcracker** [comment]
Rancher 1.5.1 running for 11 days:

#### ` top -o %MEM -c` in `rancher/server` container
```
top - 15:40:21 up 11 days,  3:27,  0 users,  load average: 3.05, 3.30, 3.89
Tasks:  15 total,   1 running,  14 sleeping,   0 stopped,   0 zombie
%Cpu(s): 93.4 us,  5.6 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.0 hi,  1.0 si,  0.0 st
KiB Mem:   1995404 total,  1970376 used,    25028 free,        0 buffers
KiB Swap:  2097148 total,   271516 used,  1825632 free.   113948 cached Mem

  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
    7 root      20   0 3422024 1.275g      0 S 88.0 67.0   3120:52 java -XX:+UseConcMarkSweepGC +
   23 mysql     20   0  900720 224664      0 S  8.7 11.3   1354:23 /usr/sbin/mysqld --basedir=/u+
```

### `htop` on host

```
  CPU[||||||||||||||||||||||||||||||100.0%]   Tasks: 38; 3 running
  Mem[|||||||||||||||||||||||||1.74G/1.90G]   Load average: 2.28 2.91 3.63
  Swp[|||||                     265M/2.00G]   Uptime: 11 days, 03:30:40

  PID USER      PRI  NI  VIRT   RES   SHR S CPU% MEM%   TIME+  Command
 1347 root       20   0 3341M 1306M     0 S 97.4 67.1 52h03:49 java -XX:+UseConcMarkSweepGC
 1365 102        20   0  879M  220M     0 S  1.3 11.3 22h34:31 /usr/sbin/mysqld --basedir=/u
```

**Comment by mnzaki** [comment]
Can confirm same issue on the Rancher 1.4.2 (`stable` from last week I think), and top also shows the java vm growing uncontrollably, eventually crashing 1GB droplet.

**Comment by jimdelois** [comment]
Confirming on `latest/1.5.3`.  It is almost entirely un-usable on a 1GB droplet.  I will be trying a 2GB droplet but would hate to have to upgrade further until/unless this is determined to be a minimum requirement...

**Comment by dustindauncey** [comment]
I am also running into this issue on a fresh install of Rancher on RancherOS with a 4 GB node on OVH. If I view top, I see a heap dump process for "out of memory".

 1741  1740 root     S    4187m 108%   1% java -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -Xms128m -Xmx2g -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/var/lib/cattle/logs -Dlogback.bootstr

Please let me know if there is anything I can provide which would be useful in fixing such a bug.

**Comment by LukeChannings** [comment]
I run it with `--memory="1g"`, It's definitely the most memory hungry container I use, idles at around 800MB RAM.

**Comment by vincent99** [comment]
@LukeChannings 1GB is the [documented requirement](http://rancher.com/docs/rancher/v1.6/en/installing-rancher/installing-server/#requirements) for the server.  This issue is for a memory leaking problem going far beyond that (which I'm guessing has been fixed since there's been no recent discussion).
