### ISSUE TITLE
container restarting before service becoming stable for mcsaky/openkm

### ISSUE THREAD

**Issue by buts101** [rancher/rancher#7754]
docker pull mcsaky/openkm

/9/2017 3:02:38 PM2017-02-09 09:17:38,299 [main] INFO  org.apache.catalina.startup.Catalina- Initialization processed in 1667 ms
2/9/2017 3:02:38 PMFeb 09, 2017 9:17:38 AM com.openkm.util.LoggerWatchdog doOnChange
2/9/2017 3:02:38 PMINFO: *** Log4j configuration file changed ***
2/9/2017 3:02:38 PM2017-02-09 09:17:38,393 [main] INFO  org.apache.catalina.core.StandardService- Starting service Catalina
2/9/2017 3:02:38 PM2017-02-09 09:17:38,395 [main] INFO  org.apache.catalina.core.StandardEngine- Starting Servlet Engine: Apache Tomcat/7.0.53
2/9/2017 3:02:38 PM2017-02-09 09:17:38,430 [localhost-startStop-1] INFO  org.apache.catalina.startup.HostConfig- Deploying web application archive /usr/local/tomcat/webapps/OpenKM.war
2/9/2017 3:03:02 PM2017-02-09 09:18:02,569 [localhost-startStop-1] INFO  org.apache.catalina.core.ContainerBase.[Catalina].[localhost].[/OpenKM]- No Spring WebApplicationInitializer types detected on classpath
2/9/2017 3:03:02 PM2017-02-09 09:18:02,728 [localhost-startStop-1] INFO  org.apache.catalina.core.ContainerBase.[Catalina].[localhost].[/OpenKM]- Initializing Spring root WebApplicationContext
2/9/2017 3:03:02 PM2017-02-09 09:18:02,728 [localhost-startStop-1] INFO  org.springframework.web.context.ContextLoader- Root WebApplicationContext: initialization started
2/9/2017 3:03:02 PM2017-02-09 09:18:02,982 [localhost-startStop-1] INFO  org.springframework.web.context.support.XmlWebApplicationContext- Refreshing Root WebApplicationContext: startup date [Thu Feb 09 09:18:02 UTC 2017]; root of context hierarchy
2/9/2017 3:03:03 PM2017-02-09 09:18:03,197 [localhost-startStop-1] INFO  org.springframework.beans.factory.xml.XmlBeanDefinitionReader- Loading XML bean definitions from ServletContext resource [/WEB-INF/applicationContext.xml]
2/9/2017 3:03:06 PM2017-02-09 09:18:06,414 [localhost-startStop-1] INFO  org.springframework.context.annotation.ClassPathBeanDefinitionScanner- JSR-250 'javax.annotation.ManagedBean' found and supported for component scanning
2/9/2017 3:03:19 PM2017-02-09 09:18:19,929 [localhost-startStop-1] INFO  org.springframework.beans.factory.xml.XmlBeanDefinitionReader- Loading XML bean definitions from class path resource [META-INF/cxf/cxf.xml]
2/9/2017 3:03:20 PM2017-02-09 09:18:20,577 [localhost-startStop-1] INFO  org.springframework.beans.factory.xml.XmlBeanDefinitionReader- Loading XML bean definitions from class path resource [META-INF/cxf/cxf-servlet.xml]
2/9/2017 3:03:46 PMKilled
2/9/2017 3:03:52 PMUsing CATALINA_BASE:   /usr/local/tomcat
2/9/2017 3:03:52 PMUsing CATALINA_HOME:   /usr/local/tomcat
2/9/2017 3:03:52 PMUsing CATALINA_TMPDIR: /usr/local/tomcat/temp
2/9/2017 3:03:52 PMUsing JRE_HOME:        /usr/local/java
2/9/2017 3:03:52 PMUsing CLASSPATH:       /usr/local/tomcat/bin/bootstrap.jar:/usr/local/tomcat/bin/tomcat-juli.jar
2/9/2017 3:03:52 PMUsing CATALINA_PID:    /usr/local/tomcat/catalina.pid
2/9/2017 3:03:54 PM2017-02-09 09:18:54,423 [main] INFO  org.apache.catalina.core.AprLifecycleListener- The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: :/usr/local/tomcat/lib/sigar:/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
2/9/2017 3:03:54 PM2017-02-09 09:18:54,908 [main] INFO  org.apache.coyote.http11.Http11Protocol- Initializing ProtocolHandler ["http-bio-0.0.0.0-8080"]
2/9/2017 3:03:54 PM2017-02-09 09:18:54,938 [main] INFO  org.apache.coyote.ajp.AjpProtocol- Initializing ProtocolHandler ["ajp-bio-127.0.0.1-8009"]
2/9/2017 3:03:54 PM2017-02-09 09:18:54,946 [main] INFO  org.apache.catalina.startup.Catalina- Initialization processed in 1524 ms
2/9/2017 3:03:54 PMFeb 09, 2017 9:18:54 AM com.openkm.util.LoggerWatchdog doOnChange
2/9/2017 3:03:54 PMINFO: *** Log4j configuration file changed ***
2/9/2017 3:03:55 PM2017-02-09 09:18:55,038 [main] INFO  org.apache.catalina.core.StandardService- Starting service Catalina
2/9/2017 3:03:55 PM2017-02-09 09:18:55,039 [main] INFO  org.apache.catalina.core.StandardEngine- Starting Servlet Engine: Apache Tomcat/7.0.53
2/9/2017 3:03:55 PM2017-02-09 09:18:55,073 [localhost-startStop-1] INFO  org.apache.catalina.startup.HostConfig- Deploying web application archive /usr/local/tomcat/webapps/OpenKM.war
2/9/2017 3:04:21 PM2017-02-09 09:19:20,961 [localhost-startStop-1] INFO  org.apache.catalina.core.ContainerBase.[Catalina].[localhost].[/OpenKM]- No Spring WebApplicationInitializer types detected on classpath
2/9/2017 3:04:21 PM2017-02-09 09:19:21,012 [localhost-startStop-1] INFO  org.apache.catalina.core.ContainerBase.[Catalina].[localhost].[/OpenKM]- Initializing Spring root WebApplicationContext
2/9/2017 3:04:21 PM2017-02-09 09:19:21,012 [localhost-startStop-1] INFO  org.springframework.web.context.ContextLoader- Root WebApplicationContext: initialization started
2/9/2017 3:04:21 PM2017-02-09 09:19:21,165 [localhost-startStop-1] INFO  org.springframework.web.context.support.XmlWebApplicationContext- Refreshing Root WebApplicationContext: startup date [Thu Feb 09 09:19:21 UTC 2017]; root of context hierarchy
2/9/2017 3:04:21 PM2017-02-09 09:19:21,218 [localhost-startStop-1] INFO  org.springframework.beans.factory.xml.XmlBeanDefinitionReader- Loading XML bean definitions from ServletContext resource [/WEB-INF/applicationContext.xml]
2/9/2017 3:04:23 PM2017-02-09 09:19:23,487 [localhost-startStop-1] INFO  org.springframework.context.annotation.ClassPathBeanDefinitionScanner- JSR-250 'javax.annotation.ManagedBean' found and supported for component scanning
2/9/2017 3:04:30 PM2017-02-09 09:19:30,628 [localhost-startStop-1] INFO  org.springframework.beans.factory.xml.XmlBeanDefinitionReader- Loading XML bean definitions from class path resource [META-INF/cxf/cxf.xml]
2/9/2017 3:04:30 PM2017-02-09 09:19:30,802 [localhost-startStop-1] INFO  org.springframework.beans.factory.xml.XmlBeanDefinitionReader- Loading XML bean definitions from class path resource [META-INF/cxf/cxf-servlet.xml]
2/9/2017 3:04:35 PMKilled
2/9/2017 3:04:41 PMUsing CATALINA_BASE:   /usr/local/tomcat
2/9/2017 3:04:41 PMUsing CATALINA_HOME:   /usr/local/tomcat
2/9/2017 3:04:41 PMUsing CATALINA_TMPDIR: /usr/local/tomcat/temp
2/9/2017 3:04:41 PMUsing JRE_HOME:        /usr/local/java
2/9/2017 3:04:41 PMUsing CLASSPATH:       /usr/local/tomcat/bin/bootstrap.jar:/usr/local/tomcat/bin/tomcat-juli.jar
2/9/2017 3:04:41 PMUsing CATALINA_PID:    /usr/local/tomcat/catalina.pid
2/9/2017 3:04:42 PM2017-02-09 09:19:42,357 [main] INFO  org.apache.catalina.core.AprLifecycleListener- The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: :/usr/local/tomcat/lib/sigar:/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
2/9/2017 3:04:43 PM2017-02-09 09:19:43,064 [main] INFO  org.apache.coyote.http11.Http11Protocol- Initializing ProtocolHandler ["http-bio-0.0.0.0-8080"]
2/9/2017 3:04:43 PM2017-02-09 09:19:43,118 [main] INFO  org.apache.coyote.ajp.AjpProtocol- Initializing ProtocolHandler ["ajp-bio-127.0.0.1-8009"]
2/9/2017 3:04:43 PM2017-02-09 09:19:43,138 [main] INFO  org.apache.catalina.startup.Catalina- Initialization processed in 1454 ms
2/9/2017 3:04:43 PMFeb 09, 2017 9:19:43 AM com.openkm.util.LoggerWatchdog doOnChange
2/9/2017 3:04:43 PMINFO: *** Log4j configuration file changed ***
2/9/2017 3:04:43 PM2017-02-09 09:19:43,362 [main] INFO  org.apache.catalina.core.StandardService- Starting service Catalina
2/9/2017 3:04:43 PM2017-02-09 09:19:43,364 [main] INFO  org.apache.catalina.core.StandardEngine- Starting Servlet Engine: Apache Tomcat/7.0.53
2/9/2017 3:04:43 PM2017-02-09 09:19:43,422 [localhost-startStop-1] INFO  org.apache.catalina.startup.HostConfig- Deploying web application archive /usr/local/tomcat/webapps/OpenKM.war
2/9/2017 3:05:09 PM2017-02-09 09:20:09,215 [localhost-startStop-1] INFO  org.apache.catalina.core.ContainerBase.[Catalina].[localhost].[/OpenKM]- No Spring WebApplicationInitializer types detected on classpath
2/9/2017 3:05:09 PM2017-02-09 09:20:09,708 [localhost-startStop-1] INFO  org.apache.catalina.core.ContainerBase.[Catalina].[localhost].[/OpenKM]- Initializing Spring root WebApplicationContext
2/9/2017 3:05:09 PM2017-02-09 09:20:09,718 [localhost-startStop-1] INFO  org.springframework.web.context.ContextLoader- Root WebApplicationContext: initialization started
2/9/2017 3:05:10 PM2017-02-09 09:20:09,990 [localhost-startStop-1] INFO  org.springframework.web.context.support.XmlWebApplicationContext- Refreshing Root WebApplicationContext: startup date [Thu Feb 09 09:20:09 UTC 2017]; root of context hierarchy
2/9/2017 3:05:10 PM2017-02-09 09:20:10,077 [localhost-startStop-1] INFO  org.springframework.beans.factory.xml.XmlBeanDefinitionReader- Loading XML bean definitions from ServletContext resource [/WEB-INF/applicationContext.xml]
2/9/2017 3:05:12 PM2017-02-09 09:20:12,540 [localhost-startStop-1] INFO  org.springframework.context.annotation.ClassPathBeanDefinitionScanner- JSR-250 'javax.annotation.ManagedBean' found and supported for component scanning
2/9/2017 3:05:20 PMKilled
2/9/2017 3:05:26 PMUsing CATALINA_BASE:   /usr/local/tomcat
2/9/2017 3:05:26 PMUsing CATALINA_HOME:   /usr/local/tomcat
2/9/2017 3:05:26 PMUsing CATALINA_TMPDIR: /usr/local/tomcat/temp
2/9/2017 3:05:26 PMUsing JRE_HOME:        /usr/local/java
2/9/2017 3:05:26 PMUsing CLASSPATH:       /usr/local/tomcat/bin/bootstrap.jar:/usr/local/tomcat/bin/tomcat-juli.jar
2/9/2017 3:05:26 PMUsing CATALINA_PID:    /usr/local/tomcat/catalina.pid
2/9/2017 3:05:27 PM2017-02-09 09:20:27,732 [main] INFO  org.apache.catalina.core.AprLifecycleListener- The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: :/usr/local/tomcat/lib/sigar:/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
2/9/2017 3:05:28 PM2017-02-09 09:20:28,232 [main] INFO  org.apache.coyote.http11.Http11Protocol- Initializing ProtocolHandler ["http-bio-0.0.0.0-8080"]
2/9/2017 3:05:28 PM2017-02-09 09:20:28,259 [main] INFO  org.apache.coyote.ajp.AjpProtocol- Initializing ProtocolHandler ["ajp-bio-127.0.0.1-8009"]
2/9/2017 3:05:28 PM2017-02-09 09:20:28,269 [main] INFO  org.apache.catalina.startup.Catalina- Initialization processed in 1405 ms
2/9/2017 3:05:28 PMFeb 09, 2017 9:20:28 AM com.openkm.util.LoggerWatchdog doOnChange
2/9/2017 3:05:28 PMINFO: *** Log4j configuration file changed ***
2/9/2017 3:05:28 PM2017-02-09 09:20:28,383 [main] INFO  org.apache.catalina.core.StandardService- Starting service Catalina
2/9/2017 3:05:28 PM2017-02-09 09:20:28,384 [main] INFO  org.apache.catalina.core.StandardEngine- Starting Servlet Engine: Apache Tomcat/7.0.53
2/9/2017 3:05:28 PM2017-02-09 09:20:28,432 [localhost-startStop-1] INFO  org.apache.catalina.startup.HostConfig- Deploying web application archive /usr/local/tomcat/webapps/OpenKM.war
2/9/2017 3:05:52 PM2017-02-09 09:20:52,807 [localhost-startStop-1] INFO  org.apache.catalina.core.ContainerBase.[Catalina].[localhost].[/OpenKM]- No Spring WebApplicationInitializer types detected on classpath
2/9/2017 3:05:52 PM2017-02-09 09:20:52,913 [localhost-startStop-1] INFO  org.apache.catalina.core.ContainerBase.[Catalina].[localhost].[/OpenKM]- Initializing Spring root WebApplicationContext
2/9/2017 3:05:52 PM2017-02-09 09:20:52,914 [localhost-startStop-1] INFO  org.springframework.web.context.ContextLoader- Root WebApplicationContext: initialization started
2/9/2017 3:05:53 PM2017-02-09 09:20:53,073 [localhost-startStop-1] INFO  org.springframework.web.context.support.XmlWebApplicationContext- Refreshing Root WebApplicationContext: startup date [Thu Feb 09 09:20:53 UTC 2017]; root of context hierarchy
2/9/2017 3:05:53 PM2017-02-09 09:20:53,329 [localhost-startStop-1] INFO  org.springframework.beans.factory.xml.XmlBeanDefinitionReader- Loading XML bean definitions from ServletContext resource [/WEB-INF/applicationContext.xml]
2/9/2017 3:05:56 PM2017-02-09 09:20:56,743 [localhost-startStop-1] INFO  org.springframework.context.annotation.ClassPathBeanDefinitionScanner- JSR-250 'javax.annotation.ManagedBean' found and supported for component scanning
2/9/2017 3:06:02 PM2017-02-09 09:21:02,339 [localhost-startStop-1] INFO  org.springframework.beans.factory.xml.XmlBeanDefinitionReader- Loading XML bean definitions from class path resource [META-INF/cxf/cxf.xml]
2/9/2017 3:06:02 PM2017-02-09 09:21:02,575 [localhost-startStop-1] INFO  org.springframework.beans.factory.xml.XmlBeanDefinitionReader- Loading XML bean definitions from class path resource [META-INF/cxf/cxf-servlet.xml]
2/9/2017 3:06:04 PMKilled
2/9/2017 3:06:09 PMUsing CATALINA_BASE:   /usr/local/tomcat
2/9/2017 3:06:09 PMUsing CATALINA_HOME:   /usr/local/tomcat
2/9/2017 3:06:09 PMUsing CATALINA_TMPDIR: /usr/local/tomcat/temp
2/9/2017 3:06:09 PMUsing JRE_HOME:        /usr/local/java
2/9/2017 3:06:09 PMUsing CLASSPATH:       /usr/local/tomcat/bin/bootstrap.jar:/usr/local/tomcat/bin/tomcat-juli.jar
2/9/2017 3:06:09 PMUsing CATALINA_PID:    /usr/local/tomcat/catalina.pid
2/9/2017 3:06:11 PM2017-02-09 09:21:11,124 [main] INFO  org.apache.catalina.core.AprLifecycleListener- The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: :/usr/local/tomcat/lib/sigar:/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
2/9/2017 3:06:11 PM2017-02-09 09:21:11,739 [main] INFO  org.apache.coyote.http11.Http11Protocol- Initializing ProtocolHandler ["http-bio-0.0.0.0-8080"]
2/9/2017 3:06:11 PM2017-02-09 09:21:11,770 [main] INFO  org.apache.coyote.ajp.AjpProtocol- Initializing ProtocolHandler ["ajp-bio-127.0.0.1-8009"]
2/9/2017 3:06:11 PM2017-02-09 09:21:11,779 [main] INFO  org.apache.catalina.startup.Catalina- Initialization processed in 1520 ms
2/9/2017 3:06:11 PMFeb 09, 2017 9:21:11 AM com.openkm.util.LoggerWatchdog doOnChange
2/9/2017 3:06:11 PMINFO: *** Log4j configuration file changed ***
2/9/2017 3:06:11 PM2017-02-09 09:21:11,867 [main] INFO  org.apache.catalina.core.StandardService- Starting service Catalina
2/9/2017 3:06:11 PM2017-02-09 09:21:11,867 [main] INFO  org.apache.catalina.core.StandardEngine- Starting Servlet Engine: Apache Tomcat/7.0.53
2/9/2017 3:06:11 PM2017-02-09 09:21:11,905 [localhost-startStop-1] INFO  org.apache.catalina.startup.HostConfig- Deploying web application archive /usr/local/tomcat/webapps/OpenKM.war
2/9/2017 3:06:37 PM2017-02-09 09:21:37,746 [localhost-startStop-1] INFO  org.apache.catalina.core.ContainerBase.[Catalina].[localhost].[/OpenKM]- No Spring WebApplicationInitializer types detected on classpath
2/9/2017 3:06:38 PM2017-02-09 09:21:38,015 [localhost-startStop-1] INFO  org.apache.catalina.core.ContainerBase.[Catalina].[localhost].[/OpenKM]- Initializing Spring root WebApplicationContext
2/9/2017 3:06:38 PM2017-02-09 09:21:38,015 [localhost-startStop-1] INFO  org.springframework.web.context.ContextLoader- Root WebApplicationContext: initialization started
2/9/2017 3:06:39 PM2017-02-09 09:21:39,186 [localhost-startStop-1] INFO  org.springframework.web.context.support.XmlWebApplicationContext- Refreshing Root WebApplicationContext: startup date [Thu Feb 09 09:21:39 UTC 2017]; root of context hierarchy
2/9/2017 3:06:40 PM2017-02-09 09:21:40,907 [localhost-startStop-1] INFO  org.springframework.beans.factory.xml.XmlBeanDefinitionReader- Loading XML bean definitions from ServletContext resource [/WEB-INF/applicationContext.xml]

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.3.2` Cattle: `v0.175.8` UI: `v1.3.5` |
|Access|`Disabled`|
|Orchestration|`Cattle`|
|Route|`service.labels`|

**Comment by superseb** [comment]
Usually means it's being killed by going out-of-memory. Are you running this from the UI -> Add container? What specs does the rancher/agent systems have?

**Comment by superseb** [comment]
@buts101 Can you let us know if you need any help on this, and if so, answer the questions so we can help you track it down?

**Comment by superseb** [comment]
Please respond if you need any help with this.
