### ISSUE TITLE
Rancher Metadata return is empty

### ISSUE THREAD

**Issue by ephillipe** [rancher/rancher#7758]
**Rancher Versions:**
Server: v1.4.0
healthcheck: v0.2.3
ipsec: v0.0.4
network-services: v0.0.10
scheduler: v0.4.0
kubernetes (if applicable):

**Docker Version:**
Docker version 1.12.6, build 78d1802

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu Xenial 16.04

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
AWS EC2 Custom 
External DB (RDS)

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Exec on Rancher Host: 
curl -s http://rancher-metadata/2015-12-19/self/host/hostId 

**Results:** 

Empty result

**Comment by niusmallnan** [comment]
@ephillipe
You can use uuid. 
```
curl -s http://rancher-metadata/2015-12-19/self/host/uuid
3e6083f6-4424-423b-8a55-c8f6cb5365dc
```

If you want to get host object, just use like this:
```
http://<rancher-server>/v2-beta/hosts?uuid=3e6083f6-4424-423b-8a55-c8f6cb5365dc
```

**Comment by ephillipe** [comment]
Hi @niusmallnan , 

Same problem:

´´´
ubuntu@ip-172-31-11-120:~$ curl -s http://rancher-metadata/2015-12-19/self/host/uuid
ubuntu@ip-172-31-11-120:~$ 
´´´

**Comment by niusmallnan** [comment]
@ephillipe
You curl rancher-metadata in you host? not in container?

**Comment by ephillipe** [comment]
@niusmallnan In previous version work. This is changed in version 1.4.0?

**Comment by niusmallnan** [comment]
@ephillipe 
If you want to use it in host, pls `curl -s http://169.254.169.250/2015-12-19/self/host/uuid` .
Because there is no dns resolv for **rancher-metadata** , just use IP address directly.

**Comment by superseb** [comment]
Still happening @ephillipe ?

**Comment by superseb** [comment]
Please file a new ticket if you're still experiencing issues.
