### ISSUE TITLE
Access control

### ISSUE THREAD

**Issue by geostant** [rancher/rancher#7759]
Seems like access control isn't working much
Read-Only users in environment can't do any operation EXCEPT for deleting containers
Restricted users in environment can do ALL actions on containers (just like owner / member)

Am I don't something wrong ?
I have expected read-only users to be able to view only as documentation suggests.

Thanks

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.4.0` Cattle: `v0.176.8` UI: `v1.4.6` |
|Access|`localauth` |
|Orchestration|`Cattle`|
|Route|`containers.index`|

**Comment by tfiduccia** [comment]
@geostant - 

Restricted Users are able to work in stacks.  They are only prohibited from Editing/Deleting the Environment & Add/Edit/Remove Hosts.

Read-only members do have the delete option showing for containers, but if they try it will give them a "method not allowed" error and won't delete.  There is already a issues to change this message - #4210

**Comment by geostant** [comment]
Thank you @tfiduccia 
Is it possible to allow read-only users to see container logs as well ?

**Comment by tfiduccia** [comment]
@geostant - Yes read-only user can already view container logs.  It is available and working from the menu drop-down.
![image](https://cloud.githubusercontent.com/assets/11514927/22796971/cee08a94-eeb9-11e6-9a07-d4dcdd4a8e7b.png)
