### ISSUE TITLE
[api-spec] Account schema identity reference is not named consistently.

### ISSUE THREAD

**Issue by SamMousa** [rancher/rancher#7760]
The API-SPEC specifies the reference as a string which is the identifier for a resource.
For example, the entity `apikey` specifies:
````
accountId: reference[account]
````

This makes sense, the apikey has a field called `accountId` which value is of type `string`, more specifically a `string` that identifies an `account`.
The account entity however has an `identity` field, which is a reference to an `identity` entity. This naming is inconsistent, the field does not contain the `identity` entity but the `identityId`.

**Comment by vincent99** [comment]
True, but not going to make a breaking change to rename this.

**Comment by SamMousa** [comment]
Would you be open to adding `identityId` as well? That way you could deprecate the `identity` field and only make the breaking change when you have other breaking changes as well.
