### ISSUE TITLE
Feature Request : Global Environment Variables

### ISSUE THREAD

**Issue by qtzar** [rancher/rancher#7763]
Currently you can add environment variables to the service layer so that each docker container in the service will have those environment variables set.

I would like to see an option that would allow you to add global environment variables to a Rancher Environment and to a Rancher Stack. These environment variables would then be added to any service that is added to the stack or environment with the lower level taking precedent over any variables with the same name at a higher level.

The idea behind this would be to allow the infrastructure manager to set something like 'spring.active.profile=dev' on a Rancher environment for development so that the developers don't accidentally forget to add them to the service level.

**Comment by vincent99** [comment]
Yes, this is basically the same thing as #5579.
