### ISSUE TITLE
UI - Please make nav header static

### ISSUE THREAD

**Issue by pulberg** [rancher/rancher#7765]
**Rancher Versions:**
Server: v1.4.0

**Steps to Reproduce:**
goto any page with enough content to require scrolling, like "Processes --> Recently Completed".

**Results:** 
user is required to scroll back to top of page to use header nav controls.

**Comment by vincent99** [comment]
The newer table views are paged and have a floating header, which minimizes how far down you can actually go.  All the other table views will be converted to that over time.

The main navigation is not going to be made static (`position: fixed` ...  the CSS term for the current behavior is actually `position: static`).
