### ISSUE TITLE
[UI] Add delay to the user-dropdown

### ISSUE THREAD

**Issue by willseward** [rancher/rancher#7766]
**Rancher Versions:**
Server: 1.4.0

**Steps to Reproduce:**

1. Attempt to change the stack view from grouped to dots.
2. Overshoot the pointer and accidentally log out.

**Results:** 

1. You are logged out.

**Expected**

1. The user drop-down should wait a fraction of a second before popping-out.
2. You stay logged in!

**Comment by tfiduccia** [comment]
The drop-down is not positioned the same in 2.0, so it won't be as easy to logout
