### ISSUE TITLE
k8s - etcd being provisioned where orchestration=true

### ISSUE THREAD

**Issue by pulberg** [rancher/rancher#7768]
**Rancher Versions:**
Server:v1.4.0
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):
rancher/k8s:v1.5.2-rancher1-2
**Docker Version:**
1.12.6
**OS and where are the hosts located? (cloud, bare metal, etc):**
RHEL7.3, vmware
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher, external mysql db
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
k8s
**Steps to Reproduce:**
start up new k8s env, add hosts, add labels to 3 hosts - etcd=true/nopods=true, add label to 2 hosts - orchestration=true
**Results:** 
etcd provisioned on hosts with label orchestration=true

![screen shot 2017-02-09 at 2 27 27 pm](https://cloud.githubusercontent.com/assets/11069351/22803080/1c849280-eed9-11e6-8a69-b2f856e59351.png)

**Comment by LLParse** [comment]
@pulberg In order to use the labeled features of our k8s distro, you need to register the hosts and label them _before_ making the environment into a Kubernetes environment. The reason for this is our use of soft host_label affinity constraints - this allows us to support both unlabeled and labeled k8s environments.

You have two choices to repair the current installation:
1. Tear down your existing cluster by deleting the infrastructure stack and follow [v1.2+ installation instructions](https://github.com/rancher/rancher/wiki/Kubernetes-Management#instructions-rancher-v12)
2. Follow the overlapping to separated planes [migration instructions](https://github.com/rancher/rancher/wiki/Kubernetes-Management#overlapping-planes-to-separated-planes)

**Comment by pulberg** [comment]
Thanks, I have re-created the env from scratch and will be going through some common "failure" scenarios - loss of network, docker restart, host failure, etc. to see how the env holds up. This is where I ran into issues before, and maybe the "migration" steps will need to be followed to get the env working again, but that sure doesn't feel like a "resilient" setup.

**Comment by LLParse** [comment]
The UX for a labeled k8s environment is understandably frustrating.

It might be counter-intuitive to schedule containers against the will of the user, but that is how soft constraints work. The idea is, in the face of error, to aggressively attempt to restore resilience, even if it means violating the scheduling rules. We plan to make this configurable so the user can choose if they want soft/hard label constraints.

**Comment by pulberg** [comment]
I stopped docker on one of the etcd hosts, etcd was moved to one of my hosts with no label.  I certainly do *not* want that behavior (un-labeled hosts are for our client pods only).  Do I need to add etcd=false to my client-only hosts?

**Comment by vincent99** [comment]
As @LLParse said they are soft constraints ("the host SHOULD have").  If the scale that is set cannot be met meeting, the soft constraints are dropped one at a time until the scale can be met or there are none left.  Changing the value doesn't affect this, `true` vs `false` or any other string have no special meaning, they just either match what was requested or they don't.

The alternative is hard constraints ("the host MUST have"), and if they can't be met then scheduling just fails.  Which is what you're asking for, but there is no option exposed for.

**Comment by pulberg** [comment]
@vincent99 Thanks for following up, I'm getting a much better idea of what will be required to run a proper, self-healing k8s env.

**Comment by LLParse** [comment]
@pulberg This is basically the template you want: https://github.com/LLParse/rancher-catalog-proper/tree/master/templates/k8s/11

It uses hard constraints and users can have hot stand-bys ready to restore resiliency. Installation of this template is non-trivial, and will involve forking rancher-catalog, copying the folder from rancher-catalog-proper and updating version. You then install this repository as the 'Rancher Certified' by adding a custom catalog with name `library`. This causes other problems - we need to conditionally add hard constraint capabilities to the Rancher-maintained template.

**Comment by pulberg** [comment]
I have re-built my k8s env. as per the instructions for resilient separated planes, and I pre-built all fail-over nodes as well - 

6x for etcd (3 active/3 passive)
4x for orchestration (2 active/2 passive)
4x for my app pods

Everything is working well, including the k8s dashboard.  I did notice something interesting when creating deployments with and "external" service (LB).  The resulting LB is only 1 node, and the stack - "kubernetes-loadbalancers" seems to not care about any labels, is that also the expected behavior for the LB stack?

**Comment by LLParse** [comment]
@pulberg Maybe it's expected, but it's definitely a bug... the LB _should_ care about the labels. At a bare minimum, it shouldn't run on dedicated etcd hosts. Would you mind opening a separate issue for this?

**Comment by pulberg** [comment]
@LLParse sure thing, I tested by scaling up the LB's and they only get provision on nodes with label "etcd=true"

**Comment by LLParse** [comment]
https://github.com/rancher/rancher-catalog/pull/491

**Comment by LLParse** [comment]
Solved via use of hard affinities, available in all newer k8s templates.
