### ISSUE TITLE
kubelet - Unexpected command output Device "eth0" does not exist.

### ISSUE THREAD

**Issue by pulberg** [rancher/rancher#7770]
**Rancher Versions:**
Server:v1.4.0
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):
rancher/k8s:v1.5.2-rancher1-2
**Docker Version:**
1.12.6
**OS and where are the hosts located? (cloud, bare metal, etc):**
RHEL7.3, vmware
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher, external mysql db
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
k8s

```
2/9/2017 2:28:44 PME0209 20:28:44.462581   19876 docker_manager.go:373] NetworkPlugin cni failed on the status hook for pod 'tiller-deploy-3991468440-8k23w' - Unexpected command output Device "eth0" does not exist.
2/9/2017 2:28:44 PM with error: exit status 1
2/9/2017 2:28:44 PME0209 20:28:44.473595   19876 docker_manager.go:373] NetworkPlugin cni failed on the status hook for pod 'tiller-deploy-3991468440-8k23w' - Unexpected command output Device "eth0" does not exist.
2/9/2017 2:28:44 PM with error: exit status 1
```

**Comment by wlan0** [comment]
@pulberg I could not reproduce this issue.

What is your kernel version?

And what is your SELinux policy?

**Comment by pulberg** [comment]
@wlan0 -

Security Options: seccomp
Kernel Version: 3.10.0-514.2.2.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.3 (Maipo)

SELinux policy -
sudo getenforce
Permissive

I don't see this in my current kubelet logs, closing.
