### ISSUE TITLE
Multiple global services/lbs can be created for the same exposed port

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#7772]
**Rancher Versions:**
Server:v1.4.0
Scheduler: rancher/scheduler:v0.6.3

**Docker Version:**1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):**Ubuntu, Cloud

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**Single node

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**Cattle

**Steps to Reproduce:**
1. Create a global service  "globalservice1" with exposed port 1007
2. Create another global service "globalservice2" with the same exposed port 1007

Both global services get created which should not be allowed. Same is true for global lbs.

**Comment by sangeethah** [comment]
This issue is also reproducible in using rancher-server version-v1.3.4 and rancher/scheduler:v0.5.1

```
-A CATTLE_PREROUTING ! -i docker0 -p tcp -m tcp --dport 9000 -j MARK --set-xmark 0x1068/0xffffffff
-A CATTLE_PREROUTING ! -i docker0 -p tcp -m tcp --dport 9000 -j DNAT --to-destination 10.42.81.222:80
-A CATTLE_PREROUTING -p tcp -m tcp --dport 9000 -m addrtype --dst-type LOCAL -j DNAT --to-destination 10.42.81.222:80
-A CATTLE_PREROUTING ! -i docker0 -p tcp -m tcp --dport 9000 -j MARK --set-xmark 0x1068/0xffffffff
-A CATTLE_PREROUTING ! -i docker0 -p tcp -m tcp --dport 9000 -j DNAT --to-destination 10.42.145.229:80
-A CATTLE_PREROUTING -p tcp -m tcp --dport 9000 -m addrtype --dst-type LOCAL -j DNAT --to-destination 10.42.145.229:80
-A CATTLE_PREROUTING ! -i docker0 -p tcp -m tcp --dport 9000 -j MARK --set-xmark 0x1068/0xffffffff
-A CATTLE_PREROUTING ! -i docker0 -p tcp -m tcp --dport 9000 -j DNAT --to-destination 10.42.17.64:80
-A CATTLE_PREROUTING -p tcp -m tcp --dport 9000 -m addrtype --dst-type LOCAL -j DNAT --to-destination 10.42.17.64:80
-A DOCKER -i docker0 -j RETURN
```

**Comment by StrongMonkey** [comment]
This is related to global service are sending requestHostID to scheduler and every reservation becomes force no matter what constraints they have. @cjellick will discuss with @ibuildthecloud to see if the behavior should be changed.
