### ISSUE TITLE
Rancher stuck during launching Swarm (swarmkit)

### ISSUE THREAD

**Issue by shuoyenl** [rancher/rancher#7774]
**Rancher Versions:**
Server:v1.4.0
healthcheck:healthcheck:v0.2.3
ipsec:rancher/net:holder
network-services:ancher/network-manager:v0.4.5, rancher/metadata:v0.7.0
scheduler:rancher/scheduler:v0.6.3
kubernetes (if applicable):

**Docker Version:**
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64
 Experimental: false

**OS and where are the hosts located? (cloud, bare metal, etc):**
cloud

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Swarm

**Steps to Reproduce:**
1. Start Rancher
2. Add an environment using the Swarm template
3. Add hosts
 
**Results:** 
Stuck at Setting up Swarm...Starting Services: swarmkit-mon  	Image: rancher/swarmkit:v1.13-1
The error from the rancher container shows:
level=error msg="Error Invalid character(s) found in minor number \"13-beta\" loading semver for version string 1.13-beta.1" 
level=error msg="Error Invalid character(s) found in minor number \"13-beta\" getting semVersion "

**Comment by mickibayo** [comment]
Hi,

I'm having the same issue

**Comment by LLParse** [comment]
The version doesn't follow semver standards. I've also removed the 1.13.x version restriction so the template may be used with any future version of Docker.

https://github.com/rancher/community-catalog/pull/429

**Comment by LLParse** [comment]
Available on master branch of community-catalog

**Comment by shuoyenl** [comment]
It's also in Rancher 1.3.4 the stable version. FYI.
Should Docker v1.12 be used before it's fixed?

**Comment by LLParse** [comment]
The template's release cycle is independent of Rancher versioning. Since this is an experimental template and the change low risk, I've made it available now. You should be able to use it with Rancher v1.2.2+, just delete your old stack and `v1.13.0-beta.1` template should be an available option.

**Comment by soumyalj** [comment]
Tested with v1.5.0-alpha1, swarm template ```v1.13.0-beta.1 ```and docker 1.13.1 hosts.
Created an environment with Swarm template and added hosts. All Swarm containers were in running state and Swarm started successfully.
