### ISSUE TITLE
rancher network metadata dns service crashes when a stack is called "Y"

### ISSUE THREAD

**Issue by dabelenda** [rancher/rancher#7776]
**Rancher Versions:**
Server: 1.3.3
healthcheck: 0.2.0
ipsec: rancher/net:v0.8.1
network-services: metadata:v0.7.0 network-manager:v0.4.0
scheduler: 0.5.1
kubernetes (if applicable): N/A

**Docker Version:** 1.13.0

**OS and where are the hosts located? (cloud, bare metal, etc):**
Bare Metal (Centos7, SELinux Enforcing and Disabled)

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node Rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**

* Setup Clean Rancher install
* Start a Stack naming it with single capital letter "Y"

**Results:** 
The network's stack metadata service dns sidekick crashes with the following logs:

2/10/2017 9:22:44 AMtime="2017-02-10T08:22:44Z" level=info msg="Starting rancher-dns v0.13.0"
2/10/2017 9:22:44 AMtime="2017-02-10T08:22:44Z" level=info msg="Loaded answers"
2/10/2017 9:22:44 AMtime="2017-02-10T08:22:44Z" level=info msg="Listening for Reload on 127.0.0.1:8113"
2/10/2017 9:22:44 AMtime="2017-02-10T08:22:44Z" level=info msg="Listening on :53"
2/10/2017 9:22:44 AMtime="2017-02-10T08:22:44Z" level=error msg="Failed to generate answers: json: cannot unmarshal bool into Go value of type string"
2/10/2017 9:22:44 AMtime="2017-02-10T08:22:44Z" level=error msg="Failed to generate answers: json: cannot unmarshal bool into Go value of type string"
2/10/2017 9:22:44 AMpanic: runtime error: invalid memory address or nil pointer dereference
2/10/2017 9:22:44 AM[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x40e3dd]
2/10/2017 9:22:44 AM
2/10/2017 9:22:44 AMgoroutine 16 [running]:
2/10/2017 9:22:44 AMpanic(0x7d7620, 0xc420016050)
2/10/2017 9:22:44 AM	/usr/local/go/src/runtime/panic.go:500 +0x1a1
2/10/2017 9:22:44 AMmain.route(0xbd8960, 0xc420049d50, 0xc420054750)
2/10/2017 9:22:44 AM	/go/src/github.com/rancher/rancher-dns/main.go:321 +0x90d
2/10/2017 9:22:44 AMgithub.com/rancher/rancher-dns/vendor/github.com/miekg/dns.HandlerFunc.ServeDNS(0x864580, 0xbd8960, 0xc420049d50, 0xc420054750)
2/10/2017 9:22:44 AM	/go/src/github.com/rancher/rancher-dns/vendor/github.com/miekg/dns/server.go:82 +0x44
2/10/2017 9:22:44 AMgithub.com/rancher/rancher-dns/vendor/github.com/miekg/dns.(*ServeMux).ServeDNS(0xc420016900, 0xbd8960, 0xc420049d50, 0xc420054750)
2/10/2017 9:22:44 AM	/go/src/github.com/rancher/rancher-dns/vendor/github.com/miekg/dns/server.go:186 +0x61
2/10/2017 9:22:44 AMgithub.com/rancher/rancher-dns/vendor/github.com/miekg/dns.(*Server).serve(0xc420053e10, 0xbd4120, 0xc420165c50, 0xbd1620, 0xc420016900, 0xc4200c3400, 0x22, 0x200, 0xc4200240d0, 0xc42016d2e0, ...)
2/10/2017 9:22:44 AM	/go/src/github.com/rancher/rancher-dns/vendor/github.com/miekg/dns/server.go:535 +0x4e6
2/10/2017 9:22:44 AMcreated by github.com/rancher/rancher-dns/vendor/github.com/miekg/dns.(*Server).serveUDP
2/10/2017 9:22:44 AM	/go/src/github.com/rancher/rancher-dns/vendor/github.com/miekg/dns/server.go:489 +0x2c8

**Comment by dabelenda** [comment]
Note, for some reason it doesn't crash when the name of the stack is "X".

**Comment by vincent99** [comment]
"Y" (and "N", but not "X") are being parsed as a boolean instead of a string.

**Comment by dabelenda** [comment]
Ok, so "Y" and "N" are taken as booleans. Are there other strings to be aware of (things like "nil")?
Apparently numbers are not an issue.

**Comment by alena1108** [comment]
@vincent99 @dabelenda what is the metadata version for this issue? 

There is some major refactoring done on the metadata microservice side that will be available in Rancher 1.5 and metadata version v0.8.0+. I can't reproduce the issue with the latest rancher/metadata service combo.

@sangeethah could you please double check.

**Comment by dabelenda** [comment]
As stated when I opened the issue, this is using metadata:v0.7.0 it is a production rancher setup so we use the rancher/server:stable image.

**Comment by soumyalj** [comment]
Tested with v1.5.0-alpha1. Stacks by Y and N can be created successfully. No crashes in the network-services-metadata-dns containers.
