### ISSUE TITLE
Switching to one spectific environment is very slow

### ISSUE THREAD

**Issue by mcanevet** [rancher/rancher#7777]
**Rancher Versions:**
Server: 1.3.4
healthcheck: 0.2.0
ipsec: 0.0.2
network-services: 0.0.8
scheduler: 0.3.0

**Docker Version:**
1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04 LTS on OVH's OpenStack

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node Rancher with external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Results:** 
We have a Rancher Server with 16 environments. Switching from one environment to another in the WebUI is quite fast (a few seconds), except for one where it is very slow (a minute or more) and sometimes does not even works.

**Comment by HenryTheSir** [comment]
Check https://github.com/rancher/rancher/issues/7548

**Comment by vincent99** [comment]
As @HenryTheSir points to, if you upgraded from < 1.2 you probably have thousands of mounts being loaded.  See `docker run --rm rancher/cleanup-1-1`

**Comment by mcanevet** [comment]
@vincent99 I didn't upgrade from < 1.2, but I can try to launch the cleanup. Should I shutdown the application first? Is it safe to run it on a production server? Or should I backup the database first?

**Comment by mcanevet** [comment]
Even if I didn't upgrade from < 1.2, I launched the cleanup script and it fixed my issue.
Thanks.
