### ISSUE TITLE
Rancher Agent v1.13  Exited (125) 6 minutes ago

### ISSUE THREAD

**Issue by narbutas** [rancher/rancher#7778]
**Rancher Versions:** 1.1.3
**Docker Version:** 1.13.1
**OS and where are the hosts located? (cloud, bare metal, etc):** OracleLinux 7.2

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** Running Rancher Agent 1.13 container

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Kubernetes

**Steps to Reproduce:** sudo docker run --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.1.3 http://XXX:8080/v1/scripts/E625D2CA7AE4E1EA3568:1486724400000:3jq8ju2PrJMleXy0XcEM5Gi5MZU

**Results:** 

INFO: Running Agent Registration Process, CATTLE_URL=http://XXX:8080/v1
INFO: Attempting to connect to: http://XXX:8080/v1
INFO: http://XXX:8080/v1 is accessible
INFO: Inspecting host capabilities
INFO: Boot2Docker: false
INFO: Host writable: true
INFO: Token: xxxxxxxx
INFO: Running registration
INFO: Printing Environment
INFO: ENV: CATTLE_ACCESS_KEY=9EB1AFCF1B77E121BEF4
INFO: ENV: CATTLE_HOME=/var/lib/cattle
INFO: ENV: CATTLE_REGISTRATION_ACCESS_KEY=registrationToken
INFO: ENV: CATTLE_REGISTRATION_SECRET_KEY=xxxxxxx
INFO: ENV: CATTLE_SECRET_KEY=xxxxxxx
INFO: ENV: CATTLE_URL=http://XXX:8080/v1
INFO: ENV: DETECTED_CATTLE_AGENT_IP=XXX.XXX.XXX.XXX
INFO: ENV: RANCHER_AGENT_IMAGE=rancher/agent:v1.1.3
INFO: Deleting container rancher-agent
docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:245: running exec setns process for init caused \"exit status 16\"".

What might be wrong and how to fix it? Same issue happening on 3 nodes.

**Comment by vincent99** [comment]
I don't know that this will specifically fix this error, but each service has it's own independent version number, and while there happens to now be a `v1.1.3` tag for `rancher/agent` that not at all the right one for a Rancher 1.1.3 installation.  Use the agent tag that the custom Add Host screen tells you to.

Right now you're running an agent 6 months newer than the server, and the agent was even completely rewritten in that interim (from python to golang) so I'd be surprised if it works at all.  And on top of that against a version of Docker that didn't exist at that time, which we won't officially support until the *next* release (1.5).

**Comment by iain17** [comment]
I seem to be having this problem on rancher/server:stable. When I try to install kubernetes, the kubelet container will just throw this error ("process_linux.go:245: running exec setns process for init caused "exit status 16") at me. Using the agent tag that the custom Add Host screen tells me to use. which is: v1.2.2!
I'm testing rancher out by having the two agents run on Rancher OS: v1.0.1 - Docker 17.03.1-ce - Linux 4.9.24

**Comment by superseb** [comment]
@iain17 Bare in mind that the supported Docker versions for Kubernetes are 1.10.3 and 1.12.3 <-> 1.12.6.

**Comment by iain17** [comment]
yeah exactly, sorry. Just read http://docs.rancher.com/rancher/v1.6/en/hosts/#supported-docker-versions

I'll give it another shot.

**Comment by superseb** [comment]
Agreed, filed as https://github.com/rancher/rancher/issues/9444
