### ISSUE TITLE
External Service + LoadBalacer - nothing to select in Target field

### ISSUE THREAD

**Issue by pdanysz** [rancher/rancher#7779]
**Rancher Versions:**
Server: 1.4.0 with latest rancher services

**Docker Version:**
Docker version 1.12.5, build 047e51b/1.12.5
**OS and where are the hosts located? (cloud, bare metal, etc):**
Bare Metal / ESX 
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single, External DB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
- create own Stack
- add / create LoadBalancer
- add / create External Service (ES)
- add / create alias to External Service

**Problem / Bug / Design ?**
I don't know if it's a bug or design feature, but when I want to add LB rule to redirect connection for specific domain to external service, I don't see it on the list in "Target" field. 

So I made an Alias to that external service and that works. I can choose as target my Alias which is alias to external service. 

I'm trying to understand why I need to create such a workaround ?:)

![LoadBanalcer1]
(https://cloud.githubusercontent.com/assets/385259/22833981/07ed0fd8-efb4-11e6-9c6d-f1636a34472a.png)
![LoadBalancer2]
(https://cloud.githubusercontent.com/assets/385259/22833982/07f4e51e-efb4-11e6-9a45-5c9c376f7eb1.png)

**Comment by vincent99** [comment]
External aliases that point to a hostname are not currently allowed.  Balancing to a hostname is complicated, you need to decide how often to look up that hostname in DNS, what to do if a lookup fails, how to weight things if there are multiple entries which each have names that return multiple names, etc.
