### ISSUE TITLE
[api-spec] [rancher-catalog-service] Missing collectionFilters

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#7783]
**Steps to Reproduce:**
Browse to `http://{CATTLE_IP}:8080/v1-catalog/schemas/`, there is no `collectionFilters` field specified. 

From UI, a sample request: `http://{CATTLE_IP}:8080/v1-catalog/templates?category_ne=system&catalogId=test-np-catalog&minimumRancherVersion_lte=v1.4.0&maximumRancherVersion_gte=v1.4.0`

The different fields of the `template` resource have filtering capabilities, but it's not exposed in the schema. This makes it hard to discover what filtering capabilities are available for the resources, because of which the REST client in the browser doesn't show "Filter" options.

**Results:** 
Expect the API to be consistent.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
