### ISSUE TITLE
Should we allow connectivity between containers within the same deployment unit even when defaultNetworkPolicy is set to None.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#7784]
Rancher Versions: Build from master

Steps to reproduce the problem:
Create a service S1 with 2 sidekicks sk1 and sk2.
Set defaultNetworkPolicy to "deny" and policy to None for the network.

With this setting , should we still expect connectivity between containers within the same deployment unit to be allowed?
Currently there is no connectivity  between containers within the same deployment unit.

**Comment by leodotcloud** [comment]
This is inline with our design. If the default policy action is `deny` it means, the user wants to lockdown every communication. Now unless a policy is defined to enable communication, no two containers can communicate with each other. If the sidekick containers were sharing the same network as the primary service, then this question anyways doesn't come into picture as the two containers would be sharing the same network stack.

**Comment by deniseschannon** [comment]
Closing as this is expected behavior
