### ISSUE TITLE
Exponential Backoff resets to 15 seconds after 130 tries

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#7785]
**Rancher Versions:**
Server: v1.4.0 

**Steps to Reproduce:**
If you have a service that fails, after 130 re-attempts, it will reset the backoff to 15 seconds and start trying to schedule actively again.

**Comment by sangeethah** [comment]
Tested with rancher/server:v1.4.1-rc1:
Created a service with invalid image.
Service reconcile continues to happen only after every 2 mts (after 175 attempts).
