### ISSUE TITLE
Action menu bug - view logs

### ISSUE THREAD

**Issue by geostant** [rancher/rancher#7787]
When entering the containers menu and selecting a container
the drop down action menu have the item "view logs" however clicking on it doesn't do anything.

I'm set as owner permissions.

[sorry in advance if such bug is already open in the system - I couldn't find any]

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.4.0` Cattle: `v0.176.8` UI: `v1.4.6` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`containers.index`|

**Comment by tfiduccia** [comment]
@geostant - I am unable to reproduce the issue.  A couple of questions:
1.  Does this happen with all containers on the page?
2.  If you go to host page or service details page and select log, does it come up?
3.  If it's only a specific container, was it stand-along and what image where you using?

**Comment by geostant** [comment]
@tfiduccia 

1. Yes
2. Yes it come up
3. No - it's with all the containers - in the example it's a stand-alone arangodb container

While opening the console menu in my browser I can see an exception while clicking on the 'view logs' button:
```
Uncaught TypeError: this.get(...)[e] is not a function  controller.js:27
    at n.applyBulkAction (controller.js:27)
    at o.join (ember.prod.js:345)
    at Function.l.join (ember.prod.js:22919)
    at ember.prod.js:11055
    at Object.p [as flaggedInstrument] (ember.prod.js:19341)
    at l (ember.prod.js:11054)
    at n.executeBulkAction (sortable-table.js:64)
    at n.send (ember.prod.js:39308)
    at n [as send] (ember.prod.js:23950)
    at ember.prod.js:11517
```

**Comment by tfiduccia** [comment]
Version - master 2/23
This was in reference to the bulk actions menu at the top and the not the specific menu for each container. 
Verified fixed
