### ISSUE TITLE
Rancher thinks container is still starting when using drbdmanage, however container is actually running already.

### ISSUE THREAD

**Issue by gerwim** [rancher/rancher#7788]
**Rancher Versions:**
Server: 1.3.4
healthcheck: 0.2.0
ipsec: 0.8.1
network-services: 0.4.0
scheduler: 0.5.1
kubernetes (if applicable): n/a

**Docker Version:** 1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):** Ubuntu 16.04, VM on local hardware

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single node rancher, internal db.

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:**
1) Set up two DRBD9 nodes and set them up properly
2) Create a docker volume using the drbdmanage plugin
3) Start (in this case) a simple wordpress container on host A using the drbdmanage volume driver.
4) Shutdown host A, Rancher will reschedule to host B
5) Wordpress container on host B keeps in starting state, according to rancher. The container is actually already started and wordpress works.

The container does fully start in rancher when removing the drbdmanage volume driver, however, the container is actually started.

**Results:** 
Rancher thinks the wordpress container is still starting (status in stack is: _(Waiting: container starting [container:1i23977])_

From docker logs:
```
root@bravo:~# docker logs 3462a918bcab
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.42.58.145. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.42.58.145. Set the 'ServerName' directive globally to suppress this message
[Sun Feb 12 10:49:35.042728 2017] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.10 (Debian) PHP/5.6.30 configured -- resuming normal operations
[Sun Feb 12 10:49:35.042772 2017] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND
```

Doing a simple cURL to the IP address above:
```
root@bravo:~# curl 10.42.58.145
<!DOCTYPE html>
<html lang="en-US">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
<title>admin | Just another WordPress site</title>
```

The rancher logs:
```
java.lang.IllegalStateException: More than one volume exists for volume URI [drbdmanage:///run/docker/drbdmanage/mnt/wordpress] or name/externalId [wordpress] and storage pool [57].
	at io.cattle.platform.docker.process.dao.impl.DockerComputeDaoImpl.getDockerVolumeInPool(DockerComputeDaoImpl.java:54)
```

Docker volumes
```
root@bravo:~# docker volume ls
DRIVER              VOLUME NAME
local               b597c5fe6e43aa2e27a4836876baad35e584a977992a2e2b24cdfa8c53a1cd3e
local               cc251135792de71426e350aa45af5644f7b27bcda4750e63c19e80911072b94e
drbdmanage         mariadb
drbdmanage         wordpress
local               rancher-agent-state
local               rancher-cni
local               rancher-cni-driver
```

drbdmanage list-volumes
```
root@bravo:~# drbdmanage list-volumes 
+------------------------------------------------------------------------------------------------------------+
| Name                    | Vol ID |    Size | Minor |                                               | State |
|------------------------------------------------------------------------------------------------------------|
| mariadb   |      0 |   1 GiB |   101 |                                               |    ok |
| wordpress |      0 | 200 MiB |   100 |                                               |    ok |
+------------------------------------------------------------------------------------------------------------+
```

**Comment by adamgoose** [comment]
I'm experiencing the same thing with the Portworx catalog service.

```
version: '2'
volumes:
  testvol:
    external: true
    driver: pxd
services:
  busybox:
    image: busybox
    stdin_open: true
    volumes:
    - testvol:/testvol
    tty: true
    labels:
      io.rancher.container.pull_image: always
```

**Comment by adamgoose** [comment]
Looks like Rancher is automatically setting `external: true` in the volume configuration. When I created a stack from compose.yml v2, and set `external: false`, the container starts successfully, and Rancher shows it as healthy.

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
