### ISSUE TITLE
Hosts in disconnected state and unreachable over ssh

### ISSUE THREAD

**Issue by santo74** [rancher/rancher#7791]
**Rancher Versions:**
Server: v1.4
healthcheck: v0.2.3
ipsec: v0.8.7
network-services: metadata: v0.7.0, network-manager: v0.4.5
scheduler: v0.6.3
kubernetes (if applicable):

**Docker Version:**
v1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
RancherOS v0.7.1 running on OpenStack

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher, internal db

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Set up a new Rancher v1.4 server and add a host with 1GB of memory running RancherOS v0.7.1

**Results:** 
After several hours, the host is in a disconnected state and the host is even not reachable anymore via ssh

Please also see [this](https://github.com/rancher/os/issues/1247) topic in RancherOS for more details

**Comment by e120078** [comment]
Hi @santo74 , I think I got the same issue with yours. May I know whether your problem has been solved? All of my windows hosts added to Rancher server will eventually get disconnected and even unreachable.

**Comment by santo74** [comment]
Hi @e120078, no it's not solved yet.
As mentioned in the referred ticket it seems to occur especially on systems that are low on memory.
Do your windows hosts have limited memory as well by any chance?

Maybe it's related to [this](https://github.com/rancher/rancher/issues/7849) issue?

**Comment by superseb** [comment]
According to https://github.com/rancher/rancher/issues/7849, this should be solved in metadata v0.7.2. Please file a new issue if you're still having this problem.

**Comment by Vespira** [comment]
I'm having the same issue with Rancher 1.5.2 and some CoreOS hosts that are being disconnected. It seems like it happened randomly, and SSH wasn't available when disconnected. Still, I'm able to keep doing operation on containers hosted (I see rancher agent, and all other system or app pods running).

Before disconnecting, it's seems that RAM usage was nearly to the max capacity on the VM. But I freed a lot of containers from the host, still it doesn't seems to be brought back to life.

**Comment by warnickr** [comment]
Seeing this issue with 1.6.23.

There doesn't seem to be any indication in any log as to what happened. The host becomes unresponsive and has to be forcibly rebooted.
