### ISSUE TITLE
rancher don't show standalone containers created with user-defined network

### ISSUE THREAD

**Issue by stszap** [rancher/rancher#7792]
**Rancher Versions:**
Server: 1.4
healthcheck: 0.2.3
ipsec: 0.8.7
network-services: 0.4.5
scheduler: 0.6.3

**Docker Version:**
1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):**
3.12.52-gentoo-r1

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
cattle

**Steps to Reproduce:**
```
docker network create testnet
docker run -d --name testcontainer --net testnet node sleep 1h
```

**Results:** 
"testcontainer" is not showing in rancher web interface. With default bridge network everything works. I can reliably reproduce this.

**Comment by superseb** [comment]
Thanks for reporting. This does show up now in v1.5.10, but bare in mind that we don't support libnetwork as we implemented CNI.
