### ISSUE TITLE
Restrict Hosts only being able to launch service with label: foo=bar 

### ISSUE THREAD

**Issue by StrongMonkey** [rancher/rancher#7795]
Scheduler will allow hosts to only allow service to be launched with special Labels.
For example, Host A requires service to have one of the labels `foo=bar` or  `infra=true`, host B requires service to have one of the labels `foo1=bar1` or `infra=true`, host C requires nothing.
Service 1 has label foo=bar, 1 will go to  [Host A, Host C]
Service 2 has label foo1=bar2, 2 will go to [Host B, Host C]
Service 3 has label infra=true, 3 will go to [Host A, Host B, Host C]
Service 4 has no label, 4 will go to [Host C]

**Comment by StrongMonkey** [comment]
https://github.com/rancher/scheduler/pull/35

**Comment by StrongMonkey** [comment]
Also need to write a documentation for this feature.

**Comment by sangeethah** [comment]
This feature is available with master builds from cattle and rancher/scheduler:v0.7.1 and rancher/network-manager:v0.4.6.
Some of the issues found when validating this feature are tracked as different issues.
Some of the issues encountered when testing this feature:
https://github.com/rancher/rancher/issues/7875
https://github.com/rancher/rancher/issues/7870
