### ISSUE TITLE
(Expected state running but got error: Image [index.docker.io/xxxx/XXXXXX] failed to pull: Downloading)

### ISSUE THREAD

**Issue by sankaet** [rancher/rancher#7796]
Hi seems like Rancher is unable to to downloaded updated images from docker for some containers.

Somehow some containers are updating but some are not.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.2.2` Cattle: `v0.174.13` UI: `v1.2.40` |
|Access|`github` `admin`|
|Orchestration|`Cattle`|
|Route|`stack.index`|

**Comment by sankaet** [comment]
Even when I try to rollback an update I get this error

> Rolling-Back (Expected state running but got error: Image [xx/xxx] failed to pull: Downloading)

**Comment by sankaet** [comment]
Also this is just happening within one environment, not all.

**Comment by cloudnautique** [comment]
Is this a private repository? Registry credentials are per environment. Can you log onto the host and do `docker pull XXXXX/XXXXXX`? You might be able to get more info there. 

Other places to look would be the rancher-agent container logs. 

Which version of Docker are you using? I believe 1.2.x works well with 1.10.x and 1.12.3+.

**Comment by sankaet** [comment]
Hi @cloudnautique 

**Is this a private repository?**

yes it is.

**Registry credentials are per environment. Can you log onto the host and do docker pull XXXXX/XXXXXX?**

Will try it now and post the results in 5

**Which version of Docker are you using?**

We are using Docker version 1.12.6. Let me try docker pull.

**Comment by sankaet** [comment]
Seems like the issue was with the droplet (not sure what still). But removing the droplet and adding a new one solved this problem.
