### ISSUE TITLE
Ability to switch from DOMAIN\user username to LDAP style DN's for backend authentication

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#7802]
When using Active Directory, use flag to switch the way the auth provider authenticates against the backend. Say from DOMAIN\user username to LDAP style DN's eg: (uid=Waddams.Milton, ou=Accounting, dc=example, dc=com)

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
