### ISSUE TITLE
Suggestion: Environment variables to environment

### ISSUE THREAD

**Issue by twoeo** [rancher/rancher#7805]
**Case**
We have 2 environment: `test` and `production`.
We wanna deploy and test some stack on `test`, and just copy them from `test` to `production`.
We do this by export docker-compose and rancher-compose and import them in a new environment.
Our service judge environment by container environment variable, to use different config.

**Problem**
After we export *-compose, before we import them again, we must modify somewhere.
For example the environment variable `RUN_ENV: test` to `RUN_ENV: production`

**Suggestion**
As it's a common scene to deploy service to different env,
it may be useful if it can assign environment variable at **[ Edit Environment ]**.
And these will add to containers automatically.

**Comment by erindru** [comment]
I would like to see this too. It would be good to be able to define a base set of "things" that are added to all services in a stack by default. For example, volume config, logging driver config, environment variables etc.

**Comment by superseb** [comment]
Thanks for this, can you agree that we close this as duplicate to https://github.com/rancher/rancher/issues/7763?
