### ISSUE TITLE
Suggestion: Support export/import some appointed service, rather than must whole stack.

### ISSUE THREAD

**Issue by k8w** [rancher/rancher#7806]
**Case**
We have many environment : dev, test, production ...
We always use export and import to deploy,
We have many services and stacks, and we must ensure consistency between environments.

**Problem**
StackA have serviceA and serviceB, it is deployed on test and production.
When serviceA is updated, and a serviceC is added, it is difficult to sync stack by export & import.

**Suggestion**
Support export/import some appointed service, rather than must whole stack.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
