### ISSUE TITLE
my rancher server ui can't open on port 8080 

### ISSUE THREAD

**Issue by lezi1022** [rancher/rancher#7808]
**Rancher Versions:**
Server:stable
healthcheck:v0.2.0
ipsec:v0.8.1
network-services:v0.4.0
scheduler:v0.5.1
kubernetes (if applicable):

**Docker Version:**
1.13.0, build 49bf474
**OS and where are the hosts located? (cloud, bare metal, etc):**
Linux ubuntu 3.13.0-24-generic #46-Ubuntu SMP Thu Apr 10 19:11:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
physical machine;
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node
internal db
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
cattle
**Steps to Reproduce:**
* my rancher server ui listen on 8080, when i start lb-service-haproxy:v0.4.6 with 8080 port ,  rancher server ui is unreachable, i telnet 127.0.0.1:8080, but it promot " Unable to connect to remote host: No route to host". 

*  i try many ways, restart rancher server , remove all rancher container, restart docker,  but it still can't work.  

* my netstat -anp show:
>
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1341/sshd
tcp        0    224 10.2.64.51:22           10.2.236.155:64095      ESTABLISHED 14648/sshd: gf [pri
tcp6       0      0 :::22                   :::*                    LISTEN      1341/sshd
tcp6       0      0 :::8080                 :::*                    LISTEN      43014/docker-proxy

* finally, i use port 8081 to start rancher server, surprise, it does work.

**Results:** 
null

**Comment by lezi1022** [comment]
i reset iptables, then it becomes useful

**Comment by aemneina** [comment]
Thanks for the update I'll close this out.
