### ISSUE TITLE
Azure doesn't appear on lets encrypt at the catalog in Rancher

### ISSUE THREAD

**Issue by IsmaelAlvarez** [rancher/rancher#7813]
Guys I'm having some problems trying to deploy a lets encrypt container (this one https://github.com/janeczku/rancher-letsencrypt ) from your Catalog, I'm using Azure and it should have support:
![screen shot 2017-02-14 at 3 51 27 pm](https://cloud.githubusercontent.com/assets/7153162/22943922/e7c7ab4c-f2cd-11e6-8b04-ac308de100f4.png)
But what i see is this:
![screen shot 2017-02-14 at 3 23 38 pm](https://cloud.githubusercontent.com/assets/7153162/22944084/5b75795c-f2ce-11e6-8344-a08d5a6185db.png)
I dont even see AWS 😢 dunno what to do, is this an issue or not (?)
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.4.1` Cattle: `v0.176.9` UI: `v1.4.6` |
|Access|`Disabled`|
|Orchestration|`Cattle`|
|Route|`authenticated.project.help`|

**Comment by vincent99** [comment]
AWS would be Route53...

This is a community template that we do not maintain as a company (though @janeczku does happen to be an employee of Rancher now).  Please create an issue in its repo.

**Comment by janeczku** [comment]
@IsmaelAlvarez The application has support for Azure, but the Let's Encrypt catalog template has not been updated yet with the new configuration parameters. You could add the environment variables for the Azure credentials yourself though: https://github.com/janeczku/rancher-letsencrypt/blob/master/context.go#L77-L81

**Comment by IsmaelAlvarez** [comment]
Thank you @janeczku will try.
