### ISSUE TITLE
K8s addon_starter container missing host_label affinity

### ISSUE THREAD

**Issue by LLParse** [rancher/rancher#7816]
**Rancher Versions:**
kubernetes (if applicable): rancher/k8s:v1.5.1-rancher1-7 (folder 18)

**Steps to Reproduce:**
1. Create a [separated-planes](https://github.com/rancher/rancher/wiki/Kubernetes-Management#instructions-rancher-v12) K8s environment

**Results:** addon-starter container doesn't always schedule to host labeled `orchestration=true`

**Expected:** addon-starter container always schedules to host labeled `orchestration=true`

**Comment by LLParse** [comment]
Available in rancher-catalog `v1.5.0-dev` branch

**Comment by galal-hussein** [comment]
@LLParse On Rancher server v1.5.0-alpha1, I validated that the addon container always starts on the host with `orchestration=true` label.
