### ISSUE TITLE
"Timeout getting IP address" on container with network "managed"

### ISSUE THREAD

**Issue by Kilhog** [rancher/rancher#7817]
**Rancher Versions:**
Server: 1.4.1 (same with 1.3.x)
healthcheck: 0.2.3
ipsec: 0.0.4
scheduler: 0.4.0

**Docker Version:**
1.12.6 & 1.13.1
**OS and where are the hosts located? (cloud, bare metal, etc):**
Fresh install of Debian 8 bare metal (OVH) 
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
* Clear install of Debian 8 on dedicated-server (Debian 8.7 stable (Jessie) Server HOST-64-H - 64G Xeon D-1540) 
* Install docker-engine 1.12.6 or 1.13.1
* `docker run -d --restart=unless-stopped -p 8080:8080 rancher/server`
* `docker run -d --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.2.0 http://***:8080/v1/scripts/*******`

**Results:** 
"Timeout getting IP address" on stack "healthcheck", "ipsec" and "scheduler".
If I create a standalone container "redis" with network "bridge" it's start and run perfectly, but if I create one with network "managed" I have a error "Timeout getting IP address"

If you could give me any solution to get around this problem I will be very grateful 😀

(I have already tried `{ "dns": ["8.8.8.8", "8.8.4.4"], "dns-search": ["example.org"] }` in daemon.json, and change DNS in resolv.conf
I also try to put the rancher host on another server)

**Comment by aemneina** [comment]
@Kilhog can you try something, can you add an entry into `/etc/hosts` with the following `169.254.169.250 rancher-metadata` and let us know if the services come up?

**Comment by Kilhog** [comment]
@aemneina Ok, I think you find something. So, when a restart the host, firstly I've had the "timeout" error, but when the stack automatically restart all the default stacks have a IP 😁 👍 . 
But now 😆 ... 
The healthcheck & scheduler stacks are blocked in "Initializing".
* Healthcheck logs `14/02/2017 22:54:29time="2017-02-14T21:54:29Z" level=fatal msg="Get http://rancher-metadata/2015-12-19/version: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"`
* Scheduler logs `
14/02/2017 22:53:08time="2017-02-14T21:53:08Z" level=info msg="Listening for health checks on 0.0.0.0:80/healthcheck"
14/02/2017 22:53:08time="2017-02-14T21:53:08Z" level=info msg="Subscribing to metadata changes."
14/02/2017 22:53:08time="2017-02-14T21:53:08Z" level=info msg="Connecting to cattle event stream."
14/02/2017 22:53:08time="2017-02-14T21:53:08Z" level=info msg="Initializing event router" workerCount=100
14/02/2017 22:53:08time="2017-02-14T21:53:08Z" level=info msg="Connection established"
14/02/2017 22:53:08time="2017-02-14T21:53:08Z" level=info msg="Starting websocket pings"
`

(Thank you very much for your quick reply 👍 )

**Comment by aemneina** [comment]
Do you run rancher with 1 host (server and agent)? If you when adding the rancher-agent make sure to pass in the following with your hosts IP `-e CATTLE_AGENT_IP=<ip_here>`

**Comment by aemneina** [comment]
Maybe a better question is, how many agent hosts do you have? Can they communicate with each other across UDP ports 500 and 4500?

**Comment by Kilhog** [comment]
I have only 1 ranger-host and 1 ranger-agent on the same server (this will not be the final production environnement, if you want tomorrow I can deploy ranger-server on another server if you think it can help), I tried with `-e CATTLE_AGENT_IP=<public_ip>` and `-e CATTLE_AGENT_IP=<127.0.0.1>` some result. 
`nmap (127.0.0.1 or <publie_ip>) -p (500 or 4500)` return closed, not filtered

**Comment by Kilhog** [comment]
I just test in production environnement like.
So I have a rancher/server on 192.168.100.51 and I make a host in 192.168.100.4 the  CATTLE_AGENT_IP will be 192.168.100.4, If it's correct I have the same issue.
And iptables on 192.168.100.4 look good. 
On 192.168.100.51 an `nmap 192.168.100.4 -p 500` return closed

**Comment by Kilhog** [comment]
So,
If I go into the "healthcheck-1" & "ipsec-router-1" containers and I add `172.17.0.2 rancher-metadata` in `/etc/hosts` all stack turned green.
![capture d ecran 2017-02-15 a 13 00 52](https://cloud.githubusercontent.com/assets/4045682/22973740/43d9cc88-f37f-11e6-88f9-87a824768680.png)

This helps someone understand the problem ?

**Comment by niusmallnan** [comment]
First, do net use docker 1.13.x, Pls see the SUPPORTED DOCKER VERSIONS for Rancher.
http://docs.rancher.com/rancher/v1.4/en/hosts/#supported-docker-versions

Second, just upgrade the infra services(ipsec/healthcheck/scheduler) to the latest version.

**Comment by superseb** [comment]
Please upgrade to latest stable with a supported Docker version and report back with the findings, so we can reproduce/troubleshoot. There shouldn't be a need of manual editing files to get stuff running.

**Comment by superseb** [comment]
Please file a new ticket if you're still experiencing issues.
