### ISSUE TITLE
API Interceptors: Configuration only match first interceptor block when two configurations are specified with different paths

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#7818]
**Rancher Versions:**
Server: master build

**Docker Version:**
1.12.6
**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
1- Add the following api interceptor configuration:

```
{
		"requestInterceptors": [{
			"type": "http",
			"paths": ["/v2-beta/projects/{path:.*}"],
			"endpoint": "http://x.x.x.x:8000/",
			"methods": ["get"],
			"secretToken": ""
		},
		{
			"type": "http",
			"paths": ["/v2-beta/projects/1a5/stacks{path:.*}"],
			"endpoint": "http://y.y.y.y:8000/secret",
			"methods": ["get"],
			"secretToken": "rancher123"
		}]
}

```
2- Add two interceptors on the specified IPs (x.x.x.x, y.y.y.y)
3- Navigate to /v2-beta/projects/1a5/stacks

**Results:** 

The request will be intercepted by only the first interceptor (x.x.x.x) and will not be intercepted by all interceptors.

**Expected**

The request should be intercepted by both the general regex path  /v2-beta/projects and the more literal path /v2-beta/projects/1a5/stacks

**Comment by prachidamle** [comment]
Will move this to "status-to-test" after new release of websocket-proxy is available and Cattle points to it

**Comment by galal-hussein** [comment]
@prachidamle I tested with latest master build, i was able to validate the previous case and various other cases with general paths with regexes and the more full paths.
