### ISSUE TITLE
Heapster doesn't startup when k8s is started

### ISSUE THREAD

**Issue by wlan0** [rancher/rancher#7820]
This is because addon starter looks for files ending with yaml and the heapster files have the extension yml.

**Comment by wlan0** [comment]
Steps to test 

Launch k8s
Ensure that heapster pods are showing in the infrastructure page

**Comment by wlan0** [comment]
This should be tested in v1.5.0-dev

**Comment by galal-hussein** [comment]
Rancher Server: v1.5.0-alpha1

I was able to validate that Heapster is installed and working correctly along with Grafana and Influxdb, i was able to see Pods/nodes stats through Grafana correctly.
