### ISSUE TITLE
ERROR: <> is (STILL!) not accessible

### ISSUE THREAD

**Issue by paprika27** [rancher/rancher#7822]
I have perused several pages of google results, repeatedly removed the containers, changed ports, rebooted and removed the agent state to no avail. Am new so please point me to tutorials or post commands for c&p, thanks!

**Rancher Versions:**
Server: 1.4.1
Agent: was latest, v1.2.0 no difference
Cattle: v0.176.9
UI: v1.4.6

**Docker Version:**
was 1.13.1, out of desperation downgraded to 1.12.6 no difference

**OS and where are the hosts located? (cloud, bare metal, etc):**
> `# uname -a
> Linux los.lod 3.10.0-514.6.1.el7.x86_64`

> `# cat /etc/centos-release
> CentOS Linux release 7.3.1611 (Core)`

dedicated single machine LAN IP 10.10.10.106, no outside access desired, fresh install

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher, no other functions or installed software, rancher authentication was enabled, out of desperation now disabled.

> `# iptables -L -n --line-numbers -t nat
> Chain PREROUTING (policy ACCEPT)
> num  target     prot opt source               destination
> 1    PREROUTING_direct  all  --  0.0.0.0/0            0.0.0.0/0
> 2    PREROUTING_ZONES_SOURCE  all  --  0.0.0.0/0            0.0.0.0/0
> 3    PREROUTING_ZONES  all  --  0.0.0.0/0            0.0.0.0/0
> 4    DOCKER     all  --  0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL
> 
> Chain INPUT (policy ACCEPT)
> num  target     prot opt source               destination
> 
> Chain OUTPUT (policy ACCEPT)
> num  target     prot opt source               destination
> 1    OUTPUT_direct  all  --  0.0.0.0/0            0.0.0.0/0
> 2    DOCKER     all  --  0.0.0.0/0           !127.0.0.0/8          ADDRTYPE match dst-type LOCAL
> 
> Chain POSTROUTING (policy ACCEPT)
> num  target     prot opt source               destination
> 1    MASQUERADE  all  --  172.17.0.0/16        0.0.0.0/0
> 2    POSTROUTING_direct  all  --  0.0.0.0/0            0.0.0.0/0
> 3    POSTROUTING_ZONES_SOURCE  all  --  0.0.0.0/0            0.0.0.0/0
> 4    POSTROUTING_ZONES  all  --  0.0.0.0/0            0.0.0.0/0
> 5    MASQUERADE  tcp  --  172.17.0.2           172.17.0.2           tcp dpt:8080
> 
> Chain DOCKER (2 references)
> num  target     prot opt source               destination
> 1    RETURN     all  --  0.0.0.0/0            0.0.0.0/0
> 2    DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:8080 to:172.17.0.2:8080`
with Docker Chain successfully being changed on deploy.

IP Forwarding 1

**Steps to Reproduce:**

> `# docker run --name rerv -d --restart=unless-stopped -p 8080:8080 rancher/server`

> `# curl -i  http://los.lod:8080/v1/scripts/***:***:***
> HTTP/1.1 200 OK
> Content-Type: text/plain
> Date: Tue, 14 Feb 2017 22:41:45 GMT
> Expires: Thu, 01 Jan 1970 00:00:00 GMT
> Server: Jetty(9.2.11.v20150529)
> Set-Cookie: PL=rancher;Path=/
> Vary: Accept-Encoding, User-Agent
> X-Api-Account-Id: 1a1
> X-Api-Schemas: http://los.lod:8080/v1/schemas
> X-Api-User-Id: 1a1
> X-Rancher-Version: v1.4.1
> Content-Length: 259
> 
> #!/bin/sh
> 
> export CATTLE_REGISTRATION_ACCESS_KEY="registrationToken"
> export CATTLE_REGISTRATION_SECRET_KEY="***:***:***"
> export CATTLE_URL="http://los.lod:8080/v1"
> export DETECTED_CATTLE_AGENT_IP="172.17.0.1"`

> `# docker run --name ra -e CATTLE_AGENT_IP="172.17.0.1" --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent http://los.lod:8080/v1/scripts/***:***:***`

**Results:**

> `INFO: Running Agent Registration Process, CATTLE_URL=http://los.lod:8080/v1
> INFO: Attempting to connect to: http://los.lod:8080/v1
> ERROR: http://los.lod:8080/v1 is not accessible`

**Comment by HenryTheSir** [comment]
Are you running RancherServer and agent on same Server?

**Comment by paprika27** [comment]
yes (I understood that is called single node rancher?)

**Comment by adrianovieira** [comment]
same error here.

I'm trying to run Rancher/Server and Rancher/Agent on the same host.

for now my workaround was `iptables --flush; iptables --flush -t nat`.

**Comment by paprika27** [comment]
not working for me, unfortunately:

`[root@los ~]# iptables --flush`
`[root@los ~]# iptables --flush -t nat`
`[root@los ~]# curl -i  http://los.lod:8080/v1/scripts/***:***:***`
`HTTP/1.1 200 OK`
`Content-Type: text/plain`
`Date: Mon, 27 Feb 2017 12:43:37 GMT`
`Expires: Thu, 01 Jan 1970 00:00:00 GMT`
`Server: Jetty(9.2.11.v20150529)`
`Set-Cookie: PL=rancher;Path=/`
`Vary: Accept-Encoding, User-Agent`
`X-Api-Account-Id: 1a1`
`X-Api-Schemas: http://los.lod:8080/v1/schemas`
`X-Api-User-Id: 1a1`
`X-Rancher-Version: v1.4.1`
`Content-Length: 259`

`#!/bin/sh`

`export CATTLE_REGISTRATION_ACCESS_KEY="registrationToken"`
`export CATTLE_REGISTRATION_SECRET_KEY="***:***:***"`
`export CATTLE_URL="http://los.lod:8080/v1"`
`export DETECTED_CATTLE_AGENT_IP="172.17.0.1"`
`[root@los ~]# docker run --name ra -e CATTLE_AGENT_IP="172.17.0.1" -d --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent http://los.lod:8080/v1/scripts/***:***:***`
`[root@los ~]# docker logs ra`

`INFO: Running Agent Registration Process, CATTLE_URL=http://los.lod:8080/v1`
`INFO: Attempting to connect to: http://los.lod:8080/v1`
`ERROR: http://los.lod:8080/v1 is not accessible`

**Comment by paprika27** [comment]
fix:

uninstall docker, remove everything,
disable firewalld (without uninstall, stopping or disabling firewalld just causes docker to fail to start a container)
reinstall docker
try setting up rancher
