### ISSUE TITLE
How to add removed Windows host to Rancher?

### ISSUE THREAD

**Issue by e120078** [rancher/rancher#7826]
Rancher Version: v1.3.1

Rancher server: Ubuntu 16.04 in VM

Steps to reproduce the problem:
Add Windows Server (previously added and removed) as host, it comes to a failure and the Windows Server is not displayed in the Host list

Log:
time="2017-02-15T14:38:10+08:00" level=info msg="Launching agent" 
time="2017-02-15T14:38:10+08:00" level=info msg="http://10.20.30.81:8080/v16E9351F0802C17537917fUqaidFruSRx58rfVmgo84wgwgDm6QtaoFuUBTaN" 
time="2017-02-15T14:38:10+08:00" level=info msg="Listening for events on http://10.20.30.81:8080/v1" 
time="2017-02-15T14:38:10+08:00" level=info msg="launching hostapi" 
time="2017-02-15T14:38:10+08:00" level=info msg="Starting event router." 
time="2017-02-15T14:38:10+08:00" level=error msg="error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/json?all=1&filters=%7B%22status%22%3A%7B%22paused%22%3Atrue%2C%22running%22%3Atrue%7D%7D&limit=0: open //./pipe/docker_engine: The system cannot find the file specified." 
time="2017-02-15T14:38:22+08:00" level=error msg="Get http://10.20.30.81:8080/v1/schemas: EOF" 
time="2017-02-15T14:38:32+08:00" level=error msg="Get http://10.20.30.81:8080/v1: EOF" 
time="2017-02-15T14:39:15+08:00" level=error msg="Get http://10.20.30.81:8080/v1: EOF" 
time="2017-02-15T14:39:23+08:00" level=error msg="Get http://10.20.30.81:8080/v1: EOF" 
time="2017-02-15T14:39:29+08:00" level=error msg="Get http://10.20.30.81:8080/v1: EOF" 
time="2017-02-15T14:39:37+08:00" level=error msg="Get http://10.20.30.81:8080/v1: EOF" 
time="2017-02-15T14:39:44+08:00" level=error msg="Get http://10.20.30.81:8080/v1: EOF" 
time="2017-02-15T14:39:52+08:00" level=error msg="Get http://10.20.30.81:8080/v1: EOF" 
time="2017-02-15T14:39:54+08:00" level=fatal msg="Failed to initialize handlers. Exiting go-agent" 

Thank you.

**Comment by StrongMonkey** [comment]
Hi @e120078. Can you please try http://docs.rancher.com/rancher/v1.4/en/windows/#removing-windows-hosts to see if you can re-register your hosts again? And also make sure that your docker daemon is running.

**Comment by e120078** [comment]
@StrongMonkey Thanks very much for your kind reply. As I mentioned in question, I tried to re-register the hosts but it didn't succeed. I found that both the registry keys need to be deleted on host server and the rancher agent state need to be deleted on rancher server so that we can re-register hosts. Anyway, thank you very much.

**Comment by bhgraham** [comment]
@e120078 What were the steps to clean up after the windows hosts?  This issue should not have been closed.  If you add a host, clone that host, and then try to remove and readd the host you are not able to.  That is still the crux of this issue and it looks like @e120078 found a workaround but the issue is still not fixed.
