### ISSUE TITLE
Question about Rancher DNS and VPN services

### ISSUE THREAD

**Issue by maZahaca** [rancher/rancher#7827]
Hi,
I've installed a VPN server from the catalog (openvpn-httpbasic).
For now it allows me to auth and discover internal services IPs.

But the thing is: I want to be able to use server names (and actually use them somehow in the browser).
I have services called "kue" it's in the "app" stack.

```
nslookup kue.app
Server:		169.254.169.250
Address:	169.254.169.250#53

Name:	kue.app
Address: 10.42.214.71
```

My `/etc/resolv.conf` under VPN:
```
search rancher.internal
nameserver 169.254.169.250
nameserver 8.8.8.8
nameserver 8.8.4.4
```

However I cannot access this name in the browser (By IP it works).
Is it an option to do that? Assign custom accessible domain name for the internal IP.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.1.4` Cattle: `v0.165.8.4` UI: `v1.1.14` |
|Access|`github` `admin`|
|Orchestration|`Cattle`|
|Route|`environment.index`|

**Comment by janeczku** [comment]
What's the result when you are doing this on the VPN client side:

```
ip route get 169.254.169.250
ping 169.254.169.250
dig @169.254.169.250 kue.app 
```

**Comment by maZahaca** [comment]
route -n get 169.254.169.250
```
   route to: 169.254.169.250
destination: 169.254.169.250
    gateway: 10.43.0.5
  interface: utun1
      flags: <UP,GATEWAY,HOST,DONE,b016,WASCLONED>
 recvpipe  sendpipe  ssthresh  rtt,msec    rttvar  hopcount      mtu     expire
       0         0         0         0         0         0      1440         0
```

ping 169.254.169.250
```
PING 169.254.169.250 (169.254.169.250): 56 data bytes
64 bytes from 169.254.169.250: icmp_seq=0 ttl=63 time=55.690 ms
64 bytes from 169.254.169.250: icmp_seq=1 ttl=63 time=56.037 ms
64 bytes from 169.254.169.250: icmp_seq=2 ttl=63 time=55.223 ms
64 bytes from 169.254.169.250: icmp_seq=3 ttl=63 time=55.679 ms
```

dig @169.254.169.250 kue.app
```
; <<>> DiG 9.8.3-P1 <<>> @169.254.169.250 kue.app
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 24153
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;kue.app.			IN	A

;; ANSWER SECTION:
kue.app.		1	IN	A	10.42.214.71

;; Query time: 56 msec
;; SERVER: 169.254.169.250#53(169.254.169.250)
;; WHEN: Wed Feb 15 22:35:56 2017
;; MSG SIZE  rcvd: 41
```

**Comment by maZahaca** [comment]
Btw, client on MacOS Sierra, VPN via TunnelBlick

**Comment by maZahaca** [comment]
I've experienced that it became accessible by the full name, like that kue.app.rancher.internal
But short name (kue.app) is still unaccessible.

**Comment by maZahaca** [comment]
And is it possible to set custom name somehow? To have it like kue.custom.name

**Comment by janeczku** [comment]
@maZahaca It looks like your question is specific to the openvpn catalog stack which is managed by the community. Could you post your question there please? https://github.com/rancher/community-catalog/issues. Thanks!

**Comment by maZahaca** [comment]
I will. But from my understanding it relates to rancher-dns which cares about resolving internal domains. It's it?
Basically I just need to create in it a custom domain name for my service.

**Comment by maZahaca** [comment]
So, do you have an answer for rancher-dns question?

**Comment by janeczku** [comment]
@maZahaca rancher-dns is correctly answering queries for short names as confirmed by your tests. This seems to be more an issue how MacOS resolved DNS with VPN connections:
http://serverfault.com/questions/474305/how-to-make-short-not-fully-qualified-hostnames-work-with-mountain-lion-tunne?rq=1

**Comment by maZahaca** [comment]
Actually both of them works (long name and short name) it was all about not flushed DNS on Mac or in browser caches domain as failed.

I'm still have a question (last one) about possibility to assign custom domain name to a service in rancher and provider it via rancher-dns. Is it possible?

**Comment by janeczku** [comment]
@maZahaca you can use service aliases to make services discoverable by custom names. The domain name is always "rancher.internal" since rancher-dns does not provide public DNS services. Why do you require a custom internal domain?

**Comment by maZahaca** [comment]
@janeczk

So in my case:
I have several resources: like 
* redis.app
* kue.app
* jira.jira
* grafana.prometheus
as 
{service}.{stack}

But I would like to create a custom domain (like *.internal) and organize them all together in one zone.
For the only one way to do that: change all stacks according expected zones (but that is not suitable).

**Comment by janeczku** [comment]
You can use "service alias" to group services from different stack under a single zone/subdomain:

1. Create a new stack "myzone"
2. Add "service alias" for all services that should be resolvable under that zone

 rancher-dns would then create CNAME records and you could use "jira.myzone", "grafana.myzone" to resolve the services.

**Comment by maZahaca** [comment]
Mmm, thanks. Will try it and get back

**Comment by maZahaca** [comment]
Ok it works, however it's not a trivial way. Thanks
