### ISSUE TITLE
Replacing built-in, self-signed `rancher/server` certificate?

### ISSUE THREAD

**Issue by dchambers** [rancher/rancher#7830]
When you run `rancher-server` (non-HA) you are immediately able to connect via `https`, but the server uses a self-signed certificate issued by 'cattle'. Does anybody know where this file is within the `rancher/server` container so I can use an alternate certificate of my choosing?

I know that the [Installing Rancher Server With SSL](https://docs.rancher.com/rancher/v1.4/en/installing-rancher/installing-server/basic-ssl-config/#installing-rancher-server-with-ssl) document talks about using a reverse proxy for this, but it's not clear why we need this extra complexity?

**Comment by junkiebev** [comment]
Isn't it located at /var/lib/rancher/etc/ssl/host.key ?

**Comment by dchambers** [comment]
Hi @junkiebev, many thanks for the help here! For me, even `/var/lib/rancher` doesn't exist as a directory of the running `rancher/server` container (v1.3.1). Might it be that you're using a different version of Rancher to me?

**Comment by dchambers** [comment]
> Isn't it located at /var/lib/rancher/etc/ssl/host.key ?
>
>(this may only be on ROS)

Just read this again, and I figured out that you are referring to a file on the host OS rather than the container itself, and sure enough it is! Thanks again for your help here 👍 .

**Comment by dchambers** [comment]
Oh, I just checked an Ubuntu host I have on a different cluster (the one I'm currently working on is using RancherOS), and although this one doesn't have a `/var/lib/rancher/etc/ssl/host.key` file, it does have a `/var/lib/rancher/etc` directory, where I presume you could put that file.
