### ISSUE TITLE
UI Feature Request - Conditionally hide environments in the environment dropdown

### ISSUE THREAD

**Issue by junkiebev** [rancher/rancher#7836]
It would (maybe) be useful for managers of a large number of environments to be able to conditionally hide  what is displayed by hovering over the environment selector dropdown box in the web UI.

Switching to a "hidden" environment could still be accomplished via the existing method located in "Manage Environments". Maybe a checkbox in the environment list and when adding a new environment would be appropriate?

**Comment by HenryTheSir** [comment]
You can manage this via Access Control if you have the authority to manage this setting you can 'hide' unwanted environments. Maybe this works for you as a workarround.

**Comment by junkiebev** [comment]
I can dig that but I'm an admin of the entire instance and don't want to add and remove myself often as owner of an environment in order to make changes to it.

**Comment by vincent99** [comment]
The dropdown shows environments you are a member of.  The Manage Environments screen shows you all of them (if you are an admin) and lets you switch to any of them.  As an admin, the only real thing being a member of a particular environment does is make it show (or not) in the dropdown.  You have access to it regardless.  So I don't understand the problem, but do not want to add another flag for "I want to be a member but not see it anyway".
