### ISSUE TITLE
If external service points to a container (in managed network) , services linked to external service is denied access to external service when policy set to "allow within linked".

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#7839]
Rancher Versions: Build from master

Steps to reproduce the problem:
Set network policy to "allow within linked" and defaultNetworkPolicy to "deny".
Create an external service that  points to a standalone container in managed network (10.42.x.x).
Create service with link to this external service.
Container from the service is not able to reach external service.

Expected Behavior:
Container from the service should be able to reach external service.

**Comment by leodotcloud** [comment]
Since external service is meant for use with IP addresses outside of Rancher managed network, we don't need to support this use case. The same functionality can be used with either links or service aliases.
