### ISSUE TITLE
Rancher K8S container with Glusterfs SSL issues

### ISSUE THREAD

**Issue by hiscal2015** [rancher/rancher#7841]
**Rancher Versions:** 1.4.1

**Docker Version:** 1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):** Ubuntu16.04
 
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single 

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Kubernetes

**Steps to Reproduce:**

Since Kubelet was running as containers in Rancher, so when mounting glusterfs volumes, glusterfs client in Kubelet container was running. The problem is, version of our glusterfs server is 3.9.1, but  glusterfs client in Kubelet container is 3.5.2, if we don't enable glusterfs SSL, then everything is fine, but we have to enable SSL for glusterfs, the mismatching glusterfs version between server and client is one of the problem. The other problem is, we have to put 3 certificates to /etc/ssl to glusterfs client, that is, we have to put the certificates to /etc/ssl to kubelet containers (SSL for glusterfs is special). 
So with the two problems, I can't find a way to go, any ideas for this?

**Comment by niusmallnan** [comment]
Try to custom rancher/k8s image, just see this repo https://github.com/rancher/kubernetes-package .
