### ISSUE TITLE
Rancher metadata service memory usage increases continually

### ISSUE THREAD

**Issue by timonmat** [rancher/rancher#7844]
**Rancher Versions:**
Server: 1.4.1
healthcheck:
ipsec:
network-services:

**Docker Version:**
1.13
**OS and where are the hosts located? (cloud, bare metal, etc):**
cloud, ubuntu 14.04.5
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node, internal db
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
cattle, 8 hosts
**Steps to Reproduce:**
? - just upgraded to 1.4.1
**Results:** 

![image](https://cloud.githubusercontent.com/assets/15153521/23024801/5b40443e-f464-11e6-9032-a255638f175e.png)

I upgraded our rancher cluster from 1.1.4 to 1.4.1, and have experienced metadata service related crashing of containers. Metadata service eats up all the memory available -> things start crashing. It's gone up to 600mb in some cases. 

Metadata container logging doesn't look weird.  just this repeated.
```
16/02/2017 13:08:10time="2017-02-16T11:08:10Z" level=info msg="Downloaded in 166.361995ms"
16/02/2017 13:08:10time="2017-02-16T11:08:10Z" level=info msg="Loading answers"
16/02/2017 13:08:11time="2017-02-16T11:08:11Z" level=info msg="Loaded answers"
16/02/2017 13:08:11time="2017-02-16T11:08:11Z" level=info msg="Applied http://x.x.x.x:8080/v1/configcontent/metadata-answers?version=1865-5cc6db6887beb3525be1bd696730805e"
```
well, for other than the fact that direct http and ip is used, although I've set up https and a url for the host registration, which at least in 1.1.x seemed to be used for all api traffic.

**Comment by boedy** [comment]
I'm running into the same issue.

**Docker Version:**
1.12.6
**OS and where are the hosts located? (cloud, bare metal, etc):**
RancherOS v0.8.0 - AWS EC2
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node, internal db
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
cattle, 2 hosts
**Steps to Reproduce:**
? - just upgraded to 1.4.1
**Results:**


![screen shot 2017-02-18 at 10 35 06](https://cloud.githubusercontent.com/assets/2030968/23092208/21e3d8e6-f5c6-11e6-8427-f385747cf17c.png)

**Comment by JoelESvensson** [comment]
I have the same issue too.
*Docker Version:*
1.12.6
*OS and where are the hosts located? (cloud, bare metal, etc):*
CoreOS 1235.9.0 - Openstack
*Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)*
single node, internal db
*Environment Type: (Cattle/Kubernetes/Swarm/Mesos)*
cattle, 3 hosts
*Steps to Reproduce:*
As soon as i upgraded to 1.4.1 with the latest infrastructure stacks. My metadata service is at version 0.7.0

**Comment by sshipkov** [comment]
I have the same issue too.
Docker Version:
1.12.6
OS and where are the hosts located? (cloud, bare metal, etc):
Ubuntu 16.4 - cloud
Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)
single node, internal db
Environment Type: (Cattle/Kubernetes/Swarm/Mesos)
cattle, 3 hosts
Steps to Reproduce:
install 1.4.1

**Comment by ibuildthecloud** [comment]
Please make sure you are running metadata 0.7.1.  We are currently investigating the memory usage, but 0.7.1 does fix a leak that happens when the management server is unavailable.

**Comment by JoelESvensson** [comment]
@ibuildthecloud 0.7.1 is not what the catalogue tells me to install. But i'll try it

**Comment by sshipkov** [comment]
Metadata 0.7.1 uses 10 mb memory after start or restart.
Over time, the memory usage grows to 200 and higher.

**Comment by JoelESvensson** [comment]
@sshipkov The exact same thing is happening to me after I upgraded

**Comment by timonmat** [comment]
What's the correct process of upgrading the metadata service? 

I'm at 0.7.0, and tried just upgrading the infrastructure stack by changing the version tag. The services upgraded ok, but would work after that. The metadata service logs would  complain about 'no route to host 169....', which is not our rancher api url at all. 

Sorry, that i forgot to take the logs. Having production go down seems has that effect. -> Rolled back to 0.7.0.

**Comment by iglooJuan** [comment]
I'm having the same problem, also after upgrading to v1.4.1
Today I saw there is an upgrade available, hopefully it will fix this problem. Now I have metadata v0.7.2

<img width="950" alt="screen shot 2017-02-23 at 3 26 58 pm" src="https://cloud.githubusercontent.com/assets/1686668/23278267/e13233fc-f9de-11e6-9df6-54c10d6d25ef.png">

**Comment by JoelESvensson** [comment]
<img width="972" alt="screen shot 2017-02-23 at 22 49 32" src="https://cloud.githubusercontent.com/assets/6786740/23280674/6faea6e8-fa1a-11e6-9b1f-79a73361afc3.png">

It's unfortunately not fixed yet. Incase you can't se the image: i'm running 0.7.2

**Comment by alena1108** [comment]
@sangeethah we should monitor performance for new metadata and make sure that it doesn't grow with time (when the data - number of instances, etc - remains the same)

**Comment by mattdodge** [comment]
For what it's worth, I've been running the 0.7.2 rancher/metadata image in my network services stack for about a week and the memory leak is still happening. We are not adding/removing hosts/instances/containers. Here are the graphs of the docker memory usage of all rancher/metadata containers over the last two days:
![screenshot 2017-02-28 18 54 13](https://cloud.githubusercontent.com/assets/797259/23442715/755f2b82-fde7-11e6-9442-fa42e2634f46.png)

The memory consistently climbs until the host runs out and becomes unresponsive. Eventually, the memory resets (the fall on the graphs) seemingly corresponding to when the metadata container downloads and applies its answers. Only once that happens does the host become responsive again.

At least this is bug is allowing us to harden our resiliency to host failures...

**Comment by alena1108** [comment]
@rawmind0 could you test it with v0.8.10 rancher-metadata image?

**Comment by rawmind0** [comment]
Tested and working ok with v0.8.11 rancher-metadata image.
