### ISSUE TITLE
Incorrect host status label

### ISSUE THREAD

**Issue by sankaet** [rancher/rancher#7845]
Just wanted to bring this to your attention. Seems like Rancher is marking these hosts as disconnected when they are indeed connected and working.

<img width="1278" alt="screen shot 2017-02-16 at 8 01 37 am" src="https://cloud.githubusercontent.com/assets/1951158/23029137/6297a3ee-f41e-11e6-9bdb-83eb28c0ba9a.png">

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.1.4` Cattle: `v0.165.8.4` UI: `v1.1.14` |
|Access|`github` `admin`|
|Orchestration|`Cattle`|
|Route|`hosts.index`|

**Comment by superseb** [comment]
Did you see any logging on the rancher/server? You are running a fairly old release, can you try to reproduce and file a new issue with more information how this is happening (random intervals, after adding x nodes, proxy in front yes/no?)
