### ISSUE TITLE
I can't remove environment... Rancher Version 1.4.1 and Docker 1.13.1

### ISSUE THREAD

**Issue by ccesara** [rancher/rancher#7846]
Rancher	v1.4.1
Cattle	v0.176.9
User Interface	v1.4.6
Rancher CLI	v0.4.1
Rancher Compose	v0.12.2

Docker version 1.13.1, build 092cba3

(AWS) SMP Debian (Jessie) 3.16.39-1 (2016-12-30) x86_64 GNU/Linux

single node rancher

Environment Type: (Cattle)

I created a stack, but I can not delete it. It's like that for many hours...
Is there any place in the database where I can manually remove this? I searched using ID but I'm not finding it. There are many tables ...

Very thanks.

![image](https://cloud.githubusercontent.com/assets/690284/23033637/090f0852-f460-11e6-80e7-f56478ab34f2.png)

**Comment by superseb** [comment]
Before fixing it manually, can you share what you did to end up in this state? Maybe check the logging and provide it if there is something in there.

You can find the environments under the `v2-beta/projects` endpoint, by sending a HTTP `DELETE` to the correct ID you can remove it but I think the GUI is hiding it because it's stuck in Deactivating

**Comment by ebr** [comment]
I believe Docker 1.13 is not yet supported, so you might want to downgrade if this is reproducible. It could help to look at your host and server logs, as suggested above. `Error loading schema` in the screenshot (top right) might mean the env has already been actually removed. You can try restarting the Rancher server container and see if it trues up its state with the DB upon restart.
PS: Unrelated, but you might want to redact your screenshot to remove your Rancher URL, and put your Rancher install behind SSL (I doubt it has anything to do with this error, but just a good practice).

**Comment by vincent99** [comment]
The delete action is based on whether the API is going to allow it in the current state so calling or from the API won't help.  The admin ->processes ascend should give some insight into what is going on related to that environment.

**Comment by ccesara** [comment]
Thanks for you good pratice @ebr . :+1: 
I remove and recreate rancher server (using same database) and solved. Thanks @vincent99  and @superseb
