### ISSUE TITLE
Do not show Network Policy option in "Edit Environment" page for environments with orchestration other than "cattle".

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#7848]
Rancher Versions: v1.5.0-alpha1

Currently ``Network Policy``` option is shown in "Edit Environment" page for environments with orchestration other than "cattle".

Do not show ```Network Policy``` option in "Edit Environment" page for environments with orchestration other than "cattle".

**Comment by vincent99** [comment]
This is a pain to detect, and prevented indirectly by #7828

**Comment by vincent99** [comment]
n/a to 2.0.
