### ISSUE TITLE
self/service does not return service details for services with name in mixed/upper case.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#7853]
Rancher Versions: v1.5.0-alpha1

Steps to reproduce the problem:
Create a service with name having mixed/upper case.
From within the container of the service , ```curl rancher-metadata/latest/self/service``` returns nothing.
Expected Behavior:
Should return service details

**Comment by alena1108** [comment]
test with metadata v0.8.5

**Comment by sangeethah** [comment]
Tested with build from master.

```wget http://rancher-metadata/latest/self/service``` return service details as expected.
