### ISSUE TITLE
name and primary_name mismatch in service metadata for services with upper/mixed case.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#7854]
Rancher Versions: v1.5.0-alpha1

Steps to reproduce the problem:
Create a service with name having mixed/upper case.

Fetch rancher metadata using ```curl rancher-metadata/latest/services/<id>/```
name shows in all lower case
primary_service_name preserves the case.

**Comment by sangeethah** [comment]
@alena1108 , network policy manager relies on name and primary_service_name to be the same to determine that service is a primary/sidekick services.

**Comment by alena1108** [comment]
test with metadata v0.8.5

**Comment by sangeethah** [comment]
Tested with build from master.

In service metadata , name and primary_name are in lowercase  for services with upper/mixed case.
