### ISSUE TITLE
updated coreos -> multiple rancher hosts with same name

### ISSUE THREAD

**Issue by kkvilekval** [rancher/rancher#7856]
**Rancher Versions:**
Server: 1.4.1
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker Version:**
1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):**
coreos  baremetal 

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher 

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
cattle.
**Steps to Reproduce:**

We use pxeboot to boot coreos .. we upgrade every month or so.  After reboot the rancher-agent comes back  and we have multiple entries for the same host.

our nodes have an attached disk where /var/lib/docker is stored the containers are not destroyed on reboot/upgrade.

**Results:** 

Note b0002 was rebooted with a new coreos.  

I had the same issue with b0001 but I deleted the node.. then had to stop and manually remove the rancher/agent and then manually re-add the node.   Not so good for large installations.

 

![screenshot from 2017-02-16 15 34 26](https://cloud.githubusercontent.com/assets/15788968/23046420/2f246732-f45e-11e6-9e4b-b0f38073e907.png)

**Comment by kkvilekval** [comment]
I should mention that if you remove either node then then both are removed.

**Comment by superseb** [comment]
Rancher state is kept in `/var/lib/rancher/state`, what is happening to the contents when you reboot/update/recycle?

**Comment by superseb** [comment]
Closed due to inactivity, please comment if you need any help on this so we can help track it down.

**Comment by kgk** [comment]
I must have missed the original request. 

/var/lib/docker is on permanent attached storage, but /var/lib/rancher is tmpfs

core@b0002 ~ $ df
Filesystem                       1K-blocks        Used   Available Use% Mounted on
devtmpfs                           3952604           0     3952604   0% /dev
tmpfs                              4089468           0     4089468   0% /dev/shm
tmpfs                              4089468      408304     3681164  10% /run
tmpfs                              4089468           0     4089468   0% /sys/fs/cgroup
tmpfs                              4089468      134028     3955440   4% /
/dev/loop0                          242688      242688           0 100% /usr
tmpfs                              4089468           0     4089468   0% /tmp
tmpfs                              4089468           0     4089468   0% /media
barrel.cs.ucsb.edu:/data       42486208512 37713398784  4772809728  89% /cluster/data
barrel.cs.ucsb.edu:/home       16104040448  3765189632 12338850816  24% /cluster/home
128.111.247.210:/datasets      30469611520 11310063104 19159548416  38% /cluster/materials
brain.ece.ucsb.edu:/connectome 62505885696 61527571456   978314240  99% /cluster/brain
/dev/mapper/vg00-scratch         568337448     2812936   536631536   1% /var/lib/docker
tmpfs                               817892           0      817892   0% /run/user/500

Does this also need to be on permanent storage?
