### ISSUE TITLE
Can't make node-exporter service work visiable to prometheus in rancher

### ISSUE THREAD

**Issue by KaimingWan** [rancher/rancher#7859]
I am using docker 1.13.

I try to use the images [basi/prometheus-swarm](https://store.docker.com/community/images/basi/prometheus-swarm) to monitor my swarm cluster. However, the doc in  [basi/prometheus-swarm](https://store.docker.com/community/images/basi/prometheus-swarm) only tells how to start all the services with command 'docker create service'. When using 'docker create service' command to create service, those services will not show up in rancher web UI. So I try to create stacks and services in rancher web ui. 

In rancher, there are five services need to be start. I have set the service tag 'io.rancher.container.network=true' in these services to make the same effect as using 'docker network create' command which will creates a overlay network.

I have started node-exporter successfully, but in the prometheus web UI, I can't see the node information at the 'target' view. I have create a overlay network and using managed network. Why the prometheus can't detect these nodes? And even I link the node-exporter service to prometheus serive, the problem still exists.

Now I get the target view like this:
![image](https://cloud.githubusercontent.com/assets/4374015/23052109/af6beaae-f509-11e6-96bd-4b66f7594b43.png)

And what I expect is like this:

![image](https://cloud.githubusercontent.com/assets/4374015/23052119/c3d97a38-f509-11e6-9783-606ac6d3d13c.png)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.4.1` Cattle: `v0.176.9` UI: `v1.4.6` |
|Access|`localauth` `admin`|
|Orchestration|`Swarm`|
|Route|`stack.index`|

**Comment by temp** [comment]
Same problem here - but without Swarm.
I started the node-exporter container, with the suggested options. But I can't connect to the metrics endpoint externally. Doing a local telnet <ip> 9100 works fine. 
Never had a similar problem with other services.
Any suggestions?

**Comment by nico01f** [comment]
+1

**Comment by superseb** [comment]
This is gone pretty much stale, please file a new issue with used versions and what you are trying to achieve so we can take a look.
