### ISSUE TITLE
Internal DNS not update after modify stack name

### ISSUE THREAD

**Issue by k8w** [rancher/rancher#7860]
**Rancher Versions:**
Server:1.4.1
healthcheck: 0.2.3
ipsec: holder
network-services: 0.4.5
scheduler: 0.6.3

**Docker Version:**
1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):**
cloud

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
![](http://p1.bpimg.com/567571/96864e1174efefbd.png)

**Stack and Service**
![](http://p1.bpimg.com/567571/1f8ac3284eb25100.png)

Not work even if change the stack name.
Have modify stack name before this.

**Conclusion**
It seems that DNS result isn't change after modify stack name.
It will resolve normally if restart metadata-service.

**Comment by janeczku** [comment]
Reproduced. After changing the stack name the service is not resolvable under the new name.

**Comment by janeczku** [comment]
ping @vincent99

**Comment by vincent99** [comment]
The dns server just answers what it's told... I assume metatdata doesn't change until the services are upgraded.  @alena1108

**Comment by superseb** [comment]
Merging this into https://github.com/rancher/rancher/issues/10234
