### ISSUE TITLE
Memory Reservations - Scheduler can't make reservation despite there being enough resource

### ISSUE THREAD

**Issue by smiffy1989** [rancher/rancher#7864]
Rancher 1.4.1
RancherOS 0.8.0

Scheduler log snippet:

17/02/2017 11:16:28time="2017-02-17T11:16:28Z" level=info msg="Adding resource pool [instanceReservation] with total 1000000 and used 19 for host  1655cab1-4504-46c7-bf16-b0fa03c14674"
17/02/2017 11:16:28time="2017-02-17T11:16:28Z" level=info msg="Adding resource pool [cpuReservation] with total 2000 and used 0 for host  1655cab1-4504-46c7-bf16-b0fa03c14674"
17/02/2017 11:16:28time="2017-02-17T11:16:28Z" level=info msg="Adding resource pool [memoryReservation] with total 16819159040 and used 12884901888 for host  1655cab1-4504-46c7-bf16-b0fa03c14674"
17/02/2017 11:16:28time="2017-02-17T11:16:28Z" level=info msg="Adding resource pool [storageSize] with total 92568748 and used 0 for host  1655cab1-4504-46c7-bf16-b0fa03c14674"
17/02/2017 11:16:28time="2017-02-17T11:16:28Z" level=info msg="Adding resource pool [portReservation], ip set [0.0.0.0], ports map tcp map[0.0.0.0:map[5672:50a03b4f-6040-4de1-9536-916be7981f81 15672:50a03b4f-6040-4de1-9536-916be7981f81]], ports map udp map[0.0.0.0:map[500:d56413a8-8309-4499-9695-d4505453d102 4500:d56413a8-8309-4499-9695-d4505453d102]] for host 1655cab1-4504-46c7-bf16-b0fa03c14674"
17/02/2017 11:16:28time="2017-02-17T11:16:28Z" level=info msg="Adding resource pool [storageSize] with total 92410736 and used 0 for host  72f7577d-f3ea-4d32-a0da-298b93d08e50"
17/02/2017 11:16:28time="2017-02-17T11:16:28Z" level=info msg="Adding resource pool [instanceReservation] with total 1000000 and used 15 for host  72f7577d-f3ea-4d32-a0da-298b93d08e50"
17/02/2017 11:16:28time="2017-02-17T11:16:28Z" level=info msg="Adding resource pool [cpuReservation] with total 2000 and used 0 for host  72f7577d-f3ea-4d32-a0da-298b93d08e50"
**17/02/2017 11:16:28time="2017-02-17T11:16:28Z" level=info msg="Adding resource pool [memoryReservation] with total 16819159040 and used 8589934592 for host  72f7577d-f3ea-4d32-a0da-298b93d08e50"**
17/02/2017 11:16:28time="2017-02-17T11:16:28Z" level=info msg="Adding resource pool [portReservation], ip set [0.0.0.0], ports map tcp map[0.0.0.0:map[5672:588ae174-bb51-4e94-855d-c252ef12e785 15672:588ae174-bb51-4e94-855d-c252ef12e785]], ports map udp map[0.0.0.0:map[500:3d2a221e-e914-4736-bd95-142b5dc09fad 4500:3d2a221e-e914-4736-bd95-142b5dc09fad]] for host 72f7577d-f3ea-4d32-a0da-298b93d08e50"
17/02/2017 11:16:28time="2017-02-17T11:16:28Z" level=info msg="Connection established"
17/02/2017 11:16:28time="2017-02-17T11:16:28Z" level=info msg="Starting websocket pings"
17/02/2017 11:19:52time="2017-02-17T11:19:52Z" level=info msg="Received event: Name: scheduler.prioritize, Event Id: b4cd3fad-613c-41f4-bf81-6b6f604190e2, ResourceId : 1i1139"
17/02/2017 11:19:52time="2017-02-17T11:19:52Z" level=info msg="Reply: Name: reply.5773374185727142074, PreviousIds: [b4cd3fad-613c-41f4-bf81-6b6f604190e2], ResourceId: 1i1139, Data: map[prioritizedCandidates:[72f7577d-f3ea-4d32-a0da-298b93d08e50]]."
17/02/2017 11:19:52time="2017-02-17T11:19:52Z" level=info msg="Received event: Name: scheduler.reserve, Event Id: 01ec9dbb-5965-4cc6-a0c7-791cfa48a760, ResourceId : 1i1139"
17/02/2017 11:19:52time="2017-02-17T11:19:52Z" level=info msg="Reserving [{Resource:instanceReservation Amount:1} {Resource:memoryReservation Amount:4294967296} {Resource:instanceReservation Amount:1} {Resource:instanceReservation Amount:1}] for 72f7577d-f3ea-4d32-a0da-298b93d08e50. Force=false"
**17/02/2017 11:19:52time="2017-02-17T11:19:52Z" level=error msg="Not enough available resources on host 72f7577d-f3ea-4d32-a0da-298b93d08e50 to reserve {memoryReservation 4294967296}."**

**Comment by StrongMonkey** [comment]
@smiffy1989 this is a bug and will be addressed in 1.5.

**Comment by aemneina** [comment]
Closing as this looks resolved in 1.5.x
