### ISSUE TITLE
Edit/Remove of system labels for a host does not take effect.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#7868]
Rancher Versions: Build from master

Steps to reproduce the problem:

Have a label set in host with following values:
key = ```io.rancher.scheduler.require_any```
value = ```test1=value1```

Now edit host and change the value of the existing label to ```test1=value1,test2=value2``` and save.

Try to view the labels for the host using "Edit host" page.

Notice that the value of the label gets reset to ```test1=value2```

Also  trying to delete this label , does not result in the label being deleted.

**Comment by cjellick** [comment]
I'm willing to bet that this isn't the UI's fault. @alena1108 any chance that your change for case insensitivity caused this?

**Comment by sangeethah** [comment]
@cjellick , Doing this from UI works fine.

**Comment by sangeethah** [comment]
@vincent99 @cjellick , seems like we dont allow for any edits for system labels from UI, though we allow for it to be set.

**Comment by tfiduccia** [comment]
We don't allow system labels to be modified through the UI.  The only reason you can add the scheduler one in the first place is because it didn't exist before.  If you tried to add/change any other system label (that already exists) it will be completely ignored and won't even show up.

**Comment by tfiduccia** [comment]
Version - 2/23
Verified fixed - A new section was created for io.rancher.scheduler.require_any.  If you try and put it in the standard label section it will move it to new section.  Looks to be working correctly.

Sangeetha, I sending this to you.  Unless there is some other reason why you wanted to be able to modify system labels, this is fixed.

**Comment by sangeethah** [comment]
Tested with master build from 2/23.

Able to edit/remove labels in "Require Container Label" and the edited lables gets saved as expected.
