### ISSUE TITLE
Editing the "required_any" label to include a the label of the global service, does not result in instances of the global service being created on the host.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#7870]
Rancher Versions: Build from master
scheduler - rancher/scheduler:v0.7.0

Steps to reproduce the problem:
3 hosts in the setup with following labels:

host1 - io.rancher.scheduler.require_any = ```test1=value1```
host2 - io.rancher.scheduler.require_any = ```test1=value1```
host3 - io.rancher.scheduler.require_any = ```test1=value2```

Deploy a global service with label ```test1=value1```.
Global service instances get deployed in host1 and host2.

Scenario 1:
Edit label in host3 to io.rancher.scheduler.require_any = ```test1=value1```
This does not result in global service instances getting deployed in host3.

Scenario 2:
Remove the label  io.rancher.scheduler.require_any from host3.
This does not result in global service instances getting deployed in host3.

In both the above scenarios , we expect global service instances to get deployed in host3.

**Comment by StrongMonkey** [comment]
Did you do that in UI?

**Comment by sangeethah** [comment]
@StrongMonkey , host label edit was done thru api.

**Comment by StrongMonkey** [comment]
what happens in here is that service reconcile may happen before hosts get updated on metadata so scheduler doesn't know the label has changed in the host. It appears to be an important issue to address.

**Comment by sangeethah** [comment]
Tested with latest build from master (feb 22) and rancher/scheduler:v0.7.2

3 hosts in the setup with following labels:

host1 - io.rancher.scheduler.require_any = test1=value1
host2 - io.rancher.scheduler.require_any = test1=value1
host3 - io.rancher.scheduler.require_any = test1=value2

Deploy a global service with label test1=value1.
Global service instances get deployed in host1 and host2.

Scenario 1:
Edit label in host3 to io.rancher.scheduler.require_any = test1=value1
This results in global service instances getting deployed in host3.

Scenario 2:
Add another host - host4 with  io.rancher.scheduler.require_any = test1=value2
Global service instances do not get deployed in host4 as expected.
Edit host4 and remove io.rancher.scheduler.require_any  label .

This results in global service instances getting deployed in host4 as expected.
