### ISSUE TITLE
"rancher host create" fails with use of "--amazonec2-private-address-only" flag

### ISSUE THREAD

**Issue by yourbuddyconner** [rancher/rancher#7873]
**Rancher Versions:**
Server: v1.3.3
healthcheck: (N/A)
ipsec: (N/A)
network-services: (N/A)
scheduler: (N/A)
kubernetes (if applicable): (N/A

**Docker Version:**
(N/A)

**OS and where are the hosts located? (cloud, bare metal, etc):**
AWS EC2, provisioning Ubuntu Hosts

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node Rancher with External DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle 

**Steps to Reproduce:**
Per the Docker-machine docs, there is an argument `--amazonec2-private-address-only` that takes no value. The presence of this argument disables the provisioning of a public IP address while creating an EC2 Instance. 

Run the following using the Rancher CLI: 
```
rancher host create \
--driver amazonec2 \
--amazonec2-access-key <KEY> \
--amazonec2-secret-key <KEY> \
--amazonec2-private-address-only \
host-name
```

OR 
```
rancher host create \
--driver amazonec2 \
--amazonec2-access-key <KEY> \
--amazonec2-secret-key <KEY> \
--amazonec2-private-address-only True \
host-name
```

**Results:** 
Passing the first command to the Rancher CLI results in many containers being created named after the arguments passed after `--amazon-ec2-private-key`: 

![screen shot 2017-02-17 at 10 46 42 am](https://cloud.githubusercontent.com/assets/2635475/23080127/8942d6c6-f504-11e6-81ba-d07451a4827d.png)

Passing the second command results in a failure as well: 
![screen shot 2017-02-17 at 11 31 46 am](https://cloud.githubusercontent.com/assets/2635475/23080197/bebde8fe-f504-11e6-81f7-5b8f0c92ff56.png)

I mentioned this in the rancher-users slack and @vincent99 verified that passing boolean variables to this `rancher host create` command results in a failure.

**Comment by matthijsvdr** [comment]
When adding a host using the UI of Rancher and checking the "Use only private IP address" wont add a host in rancher, showing up with a variaty of errors. The instance does get started in aws, and it only has a private ip, rancher master can reach the instance without problems (ping ect).

When adding a host using the same settings but dont check the private it, everything works fine.
note: securety groups are setup that servers are not allowed to connect externaly so servers get added with there private ip anyway.

However i would like to remove the public ip from some rancher nodes :)

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
