### ISSUE TITLE
During upgrade of service/ service reconcilation ,  intermediate errors seen when upgraded instances have to started in a different host.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#7878]
Rancher server - Build from master
Steps to reproduce the problem:
Set up has 2 hosts.
host1-  ```io.rancher.scheduler.require_any="test1=value1"```
host2 - ```io.rancher.scheduler.require_any="test1=value2"```

Deploy service with label - test1=value1. All instances of the service go to host1.
Upgrade service and alter label to test1=value2 , so that the new upgraded instances are forced to go to host2.

When service upgrade is in progress , the new instance that gets started always encounters allocation error and gets to "Error" state. And then eventually gets deployed in the right host and upgrade succeeds.

Why does the create of new instances get allocation error ? Does it not go thru the external scheduler?

**Comment by StrongMonkey** [comment]
I found this is related to https://github.com/rancher/rancher/issues/7444. Everytime when we upgrade service, we always have a valid host constraint which always set the initial host as the valid one. This appears until it gets removed and be created with a new deployment uuid.

**Comment by StrongMonkey** [comment]
@cjellick i am probably not able to fix it in 1.5 per discussion in another issue.

**Comment by sangeethah** [comment]
Another scenario where we encounter a similar issue:

Deactivate host. Delete an instance of a service that is running on this host that is deactivated. Notice that the first time service reconcile kicks in it fails and gets an instance created in Error state - gives an allocation error saying - ```Degraded (Failed to allocate instance [container:1i2694]: Bad instance [container:1i2694] in state [error]: Allocation failed: No healthy hosts with sufficient resources available)``` Next attempt to reconcile succeeds.

**Comment by StrongMonkey** [comment]
@sangeethah plz re-test as i remember you closed a similar issue.

**Comment by sangeethah** [comment]
This issue is not reproducible when testing with rancher-server - v1.6.0-rc1
