### ISSUE TITLE
Linked services from services that have sidekicks are not reachable from containers of primary service.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#7880]
Rancher Versions: Build from master

Create a stack -T1.
Create a service - S1 with side kick - SK1 , SK2.
Set Network policy to {"within": "linked", "action": "allow"} and defaultPolicyAction set to deny.

Create a service - S2. 

Link S1 to S2.

From instances of S1 , try to ping (/access) instances of S2.
Able to access instances of S2 from containers of side kick SK1 and SK2.
But not able to access  instances of S2  from containers of S1 (which is the primary service).

**Comment by leodotcloud** [comment]
Root cause: https://github.com/rancher/rancher/issues/7914

**Comment by sangeethah** [comment]
Tested with rancher/network-policy-manager:v0.2.2

Create a stack -T1.
Create a service - S1 with side kick - SK1 , SK2.
Set Network policy to {"within": "linked", "action": "allow"} and defaultPolicyAction set to deny.

Create a service - S2.

Link S1 to S2.

From instances of S1 , try to ping (/access) instances of S2.
Able to access instances of S2 from containers of side kick SK1 and SK2 and from S1 as expected.
