### ISSUE TITLE
Port 8080 between high availability nodes?

### ISSUE THREAD

**Issue by mattdodge** [rancher/rancher#7882]
**Rancher Versions:**
Server: 1.4.1
healthcheck: 0.2.3
ipsec: 0.0.4
network-services: 0.0.10
scheduler: 0.4.0

**OS and where are the hosts located? (cloud, bare metal, etc):**
EC2 in the same VPC

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA Rancher, external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

After upgrading to 1.4.1 and switching over to a classic load balancer (from single node, 1.3, ALB) I am seeing weirdness with websockets. Some sockets/stats won't load on the UI with a message about timing out before handshake being completed.

What is peculiar is the error message I'm seeing in the rancher server logs:
```
level=error msg="Error dialing websocket backend." error="dial tcp 10.0.4.247:8080: getsockopt: connection timed out"
```

I have two Rancher server nodes (10.0.4.247 and 10.0.6.162 internal IP in the VPC) but the above log message is coming from the other node! It appears it's trying to get socket details from the other node's private IP on port 8080. According to [the docs](https://docs.rancher.com/rancher/v1.4/en/installing-rancher/installing-server/#requirements-for-ha) on high availability the only port open between server nodes needs to be 9345. When I add 8080 to my firewall rules between nodes the error stops appearing and everything works normally.

So, do we need to have 9345 *and* 8080 open between nodes?

**Comment by superseb** [comment]
Thanks for reporting, this is fixed in https://github.com/rancher/rancher.github.io/commit/cde54f76a41acce6dd8da71921d59f54312011a1
