### ISSUE TITLE
k8s LB info not updating in k8s dashboard

### ISSUE THREAD

**Issue by pulberg** [rancher/rancher#7883]
**Rancher Versions:**
Server:v1.4.1
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):
rancher/k8s:v1.5.2-rancher1-2

**Docker Version:**
1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):**
RHEL7.3, vmware

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node Rancher, external mysql db

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
k8s

**Steps to Reproduce:**
in the k8s dashboard - 
create a deployment, add an "external" service listening on a port (i used nginx:latest, 80:80)
see that your pod gets created and an LB gets created also
stop docker on the host with the LB, see that the LB gets moved to another available host.

**Results:** 
once the LB has been created on a different host, observe that the k8s dashboard info for the service still has the previous host IP listed for "external endpoints", but the Rancher info for the LB is updated.

![screen shot 2017-02-18 at 10 26 10 pm](https://cloud.githubusercontent.com/assets/11069351/23099423/e842b18c-f62b-11e6-817b-fd67186efdf6.png)

![screen shot 2017-02-18 at 10 26 32 pm](https://cloud.githubusercontent.com/assets/11069351/23099424/eff308e6-f62b-11e6-9e87-a9fccf02b0c7.png)

**Comment by pulberg** [comment]
After 2 days the k8s dashboard now has the correct host info for the LB.  I'll test this a few more times to make sure it wasn't some sort of fluke.

![screen shot 2017-02-20 at 1 24 27 pm](https://cloud.githubusercontent.com/assets/11069351/23139036/24e1c674-f770-11e6-8a7d-5d2b96433183.png)

**Comment by pulberg** [comment]
#7909

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
