### ISSUE TITLE
It `s too slowly that open the rancher home page.

### ISSUE THREAD

**Issue by yeruisen** [rancher/rancher#7884]
**Rancher Versions:**
Server: 1.3.2

**OS and where are the hosts located? (cloud, bare metal, etc):**
bare metal

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

![image](https://cloud.githubusercontent.com/assets/12295648/23100491/65e92422-f6bd-11e6-8fa5-620ecac16bc3.png)

**Comment by HenryTheSir** [comment]
Use DB Cleanup Tool:
See docker run --rm rancher/cleanup-1-1 for usage.

@vincent99 : I had to use this tool although I am on 1.3.3/1.3.4 is this still a problem in this versions? I thought it is just for versions prior 1.2

**Comment by yeruisen** [comment]
@HenryTheSir Thank you for your help, now it `s work well.

**Comment by superseb** [comment]
Closing this, please file a new issue if you are experiencing issues.
