### ISSUE TITLE
Rancher deploying to a disconnected host

### ISSUE THREAD

**Issue by obenziane2** [rancher/rancher#7885]
**Rancher Versions:**
Server: 1.4.1
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker Version:**
1.13.1

**OS and where are the hosts located? (cloud, bare metal, etc):**
EC2

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**
<img width="270" alt="screen shot 2017-02-19 at 9 01 09 am" src="https://cloud.githubusercontent.com/assets/11947294/23104396/0063b5ee-f682-11e6-8cdd-340907ba9b89.png">

**Results:** 

Not sure why Rancher deploys to a disconnected host/instance. I have added the constaints labels but still going to the wrong active slave. Is there anyway to check for a tag if the sever is down and not to deploy to the unhealthy host ?

**Comment by superseb** [comment]
How many hosts are you running? And did you launc stack `connect` after this host went into `Disconnected` and it still landed on this host?

**Comment by obenziane2** [comment]
I'm closing this out. thanks
