### ISSUE TITLE
Both Amazon EC2 & Digital Ocean STUCK on "installing rancher agent"

### ISSUE THREAD

**Issue by jfmyers** [rancher/rancher#7888]
Rancher Version:
1.4.0

Docker Version:
1.12 (installed via "https://releases.rancher.com/install-docker/1.12.sh")

OS and where are the hosts located? (cloud, bare metal, etc):
AWS us-east-1
Digital Ocean NYC-3

Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)
Single node Rancher server

Environment Type: (Cattle/Kubernetes/Swarm/Mesos)
Cattle

Steps to Reproduce:
EC2 host deployment to public subnet using internal or external Rancher server host registration 
Rancher created rancher-machine EC2 security group used for hosts

Results:
Hosts get stuck on provisioning stage 'Installing Rancher Agent' 

Expected:
Host nodes should install and register with the Rancher server

**Comment by jfmyers** [comment]
I should note, this was working as of last night and that nothing in my configuration has changed since then.

**Comment by btro** [comment]
I have this issue with the current release (1.5.1 and Docker 1.2.6 for the server). Any idea where this comes from?
