### ISSUE TITLE
Windows hosts got disconnected

### ISSUE THREAD

**Issue by e120078** [rancher/rancher#7889]
Rancher Version: v1.3.1
Rancher Server: Ubuntu 16.04 in VM

Docker version:
Version on hosts: 1.12.2-cs2-ws-beta
Version on Rancher server: 1.13.0

Steps to reproduce:
Add Windows hosts to the Rancher Server, everything is fine and the host is shown as 'Active'
After a while/after reboot (on different hosts), the host state changed to Reconnecting and Disconnected.
Moreover, **we can't ping and enter the host servers**. 

Here is a guess that the ip address or network config is changed. May I know how to settle this issue? Thank you very much for your kind help!

**Comment by StrongMonkey** [comment]
@e120078 Guess your ip address has changed since you did a reboot. Is that an aws instance?

**Comment by superseb** [comment]
If the IP changed you can re-register the host to get it back working again. If you're running on a cloud where you have possibilities to retain IP, you can use those. Please reply if you need any other kind of assistance.
