### ISSUE TITLE
agent-instance: Missing SHA1SUMS files, invalid download

### ISSUE THREAD

**Issue by zhangyashen** [rancher/rancher#7893]
**Rancher Versions:**
Server:  1.1.0
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker Version:**
Server Version: 1.10.3
Storage Driver: overlay
 Backing Filesystem: xfs
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: host bridge null
Kernel Version: 4.7.0

**OS and where are the hosts located? (cloud, bare metal, etc):**
cloud ,  centos6.5
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
external DB, single node rancher 
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
have no idea, maybe many people use a same account? 

**Results:** 
agent-instalce error  as following:
[config.sh:126] tar xzf /var/lib/cattle/download.NXo7clo/download -C /var/lib/cattle/download.NXo7clo
[config.sh:135] rm /var/lib/cattle/download.NXo7clo/download
[[[config.sh:137] ls -1 /var/lib/cattle/download.NXo7clo
[[config.sh:137] basename ipsec-1-4b51c8e71d42d91125304a01ef945b6e164231315f0b504a2a7ef67443bd93f4
[config.sh:137] local dir=ipsec-1-4b51c8e71d42d91125304a01ef945b6e164231315f0b504a2a7ef67443bd93f4
[config.sh:138] '[' '!' -e /var/lib/cattle/download.NXo7clo/ipsec-1-4b51c8e71d42d91125304a01ef945b6e164231315f0b504a2a7ef67443bd93f4 ']'
[config.sh:145] cd /var/lib/cattle/download.NXo7clo
[config.sh:147] '[' '!' -e ipsec-1-4b51c8e71d42d91125304a01ef945b6e164231315f0b504a2a7ef67443bd93f4/SHA1SUMSSUM ']'
[config.sh:148] error 'Missing SHA1SUMS files, invalid download'
[scripts.sh:24] echo ERROR: 'Missing SHA1SUMS files, invalid download'
ERROR: Missing SHA1SUMS files, invalid download
[config.sh:149] exit 1
[config.sh:1] cleanup
[config.sh:9] EXIT=1
[config.sh:11] '[' -e /var/lib/cattle/download.NXo7clo ']'
[config.sh:12] rm -rf /var/lib/cattle/download.NXo7clo
[config.sh:15] return 1
The system is going down NOW!
Sent SIGTERM to all processes
Sent SIGKILL to all processes
Requesting system reboot

**Comment by superseb** [comment]
I would highly suggest to run a newer version of Rancher, at the time of issue creation Rancher v1.4.1 was available and now we are at v1.5.10 as stable. This has significant improvements. Please file a new issue if you still experience problems with a newer version.
