### ISSUE TITLE
rancher-nfs: docker-compose syntax for environment scoped volumes is invalid

### ISSUE THREAD

**Issue by waarg** [rancher/rancher#7894]
**Rancher Versions:**
Server: 1.3.2
healthcheck: 0.2.0
ipsec: 0.8.1
network-services: 0.4.0
scheduler: 0.5.1
kubernetes (if applicable): NA
rancher/storage-nfs: 0.6.0

**Docker Version:** 
1.12.5

**OS and where are the hosts located? (cloud, bare metal, etc):** 
RedHat 7, AWS EC2

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** 
3 node HA + external (RDS) database

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** 
Cattle

**Steps to Reproduce:**

Create a stack using docker-compose.yml, including an environment-scoped rancher-nfs volume using the syntax specified in the [documentation](https://docs.rancher.com/rancher/v1.3/en/rancher-services/storage-service/#environment-scoped-1):

`
version: '2'
volumes:
  data:
    driver: 'rancher-nfs'
    external: true
`    

**Results:** 
Run docker-compose build against the same docker-compose.yml, the following error occurs:

`ERROR: Volume logs declared as external but specifies additional attributes (driver).`

According to the docker-compose [documentation](https://docs.docker.com/compose/compose-file/compose-file-v2/#/external):

> external cannot be used in conjunction with other volume configuration keys (driver, driver_opts).

**Comment by jhoglin** [comment]
+1 for this issue, tried different ways to override this in a docker-compose.override.yml but with no success.  
Should this be moved to rancher-compose so the syntax is still docker-compose valid?

**Comment by HaiNguyen007** [comment]
My same problem, in Rancher UI when I click "View config" of a stack with rancher-nfs volumes => all drivers have "null" as value:
volumes:
odoo-web-data:
external: true
driver: 'null'
odoo-db-data:
external: true
driver: 'null'

**Comment by deniseschannon** [comment]
These should be fixed in v1.6.1. 

You are able to import in compose files that have volume drivers and they are exported correctly.
