### ISSUE TITLE
[api-spec] Collection of minor issues.

### ISSUE THREAD

**Issue by SamMousa** [rancher/rancher#7897]
This issue tracks several minor issues related to api specification compliance.

--------------------------------
The API returns the following type information for the id field:
````
"id": {
    "type": "int",
    "description": null,
    "create": false,
    "update": false,
    "nullable": true,
    "readOnCreateOnly": false
},
````
My ids look like this: 1a90, which is a string. Also is the id supposed to be nullable?

--------------------------------
Rancher 1.4.1 returns a `CreatedTS` field in its data for a `Host` entity, but it is not mentioned in the schema.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
