### ISSUE TITLE
[api-spec] Entity inheritance

### ISSUE THREAD

**Issue by SamMousa** [rancher/rancher#7898]
Currently the api-spec documentation only mentions inheritance at the collection level.

This is what it says:
### Inheritance ###
Collections MAY support multiple resource types through simple inheritance:
  - The `resourceType:` SHOULD refer to the 'base' resource type.
  - Define additional sub-types that have all the same fields and filters as the base type, plus additional info.
  - Return a `createTypes:` map in the collection, with a mapping of type ids that can be created &rarr; the URL where they SHOULD be POSTed.
    - If the 'base' type can also be created, it SHOULD be present in the map.
    - The URL for each entry MAY be the same as the collection's self link, or it can be different to provide additional flexibility in the service.

```javascript
  "createTypes": {
    "file":      "https://base/v1/files",
    "textFile":  "https://base/v1/files",
    "imageFile": "https://base/v1/files?image=1",
  },
```

----------------------------------------

There does not seem to be way to get this inheritance relation from the schema(s). Currently the inheritance could be discovered by iterating over all collections and checking their `createTypes` array. Theoretically different collections for the same entity could also create different inheritance relations.

Would it be a good idea to add something like a `parentType` field to the schema of each entity?

**Comment by SamMousa** [comment]
It seems that `createTypes` does not always identify all inheritance options (makes sense since not all of them need to be creatable).

For example endpoint: `/genericobjects` can (amongst others) return an object of type `register` in its collection.
Is there any way, other than checking if attributes of one entity are a subset of another entities' attributes, to determine a relation between 2 entities?

**Comment by cjellick** [comment]
@SamMousa no, there is no way to explicitly check the inheritance relationship between two entities beyond what you've already described with createTypes.

Is there something specific you're attempting to accomplish? Might be able to help with or address some specific use case.

**Comment by vincent99** [comment]
There is `type` vs `baseType`, i.e. container extends instance so they are `type: container`, `baseType: instance`.

**Comment by SamMousa** [comment]
@cjellick I'm just trying to replicate the entity hierarchy in another language (PHP) purely from information in the spec combined with information provided by the API.
It is more of an academic interest than a practical one: https://github.com/SAM-IT/php-rancher-client

Also I want to update certificates via the API, but that's rather simple and to do that I don't need to actually have an advanced client.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
