### ISSUE TITLE
docker-compose file with $$ characters

### ISSUE THREAD

**Issue by lezi1022** [rancher/rancher#7899]
**Rancher Versions:**
Server:1.4.1
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker Version:**

**OS and where are the hosts located? (cloud, bare metal, etc):**

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**
my docker-compose file defined an environment  and it value contains $$ character, when i create an stack from ui and import docker-compose from local file,  it will change $$ to $

example
```
environment:
  Securities: "https://xxxxx.com/api/rest.svc/security_list/wiub9558tn/FOALL$$ALL_3803?pageNo=1&outputtype=json"
```
but i got a Securities environment ,it will reduce a $ charactor
```
Securities: https://xxxxx.com/api/rest.svc/security_list/wiub9558tn/FOALL$ALL_3803?pageNo=1&outputtype=json
```
**Results:**

**Comment by joshwget** [comment]
This is the expected behavior. `$` is a special character because of interpolation. `$$` is the escape sequence to result in a single `$` (https://docs.rancher.com/rancher/v1.5/en/cattle/rancher-compose/environment-interpolation/#environment-interpolation-formats).
