### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by 0ff** [rancher/rancher#7901]
**Rancher Versions:**
Server: v1.4.0
healthcheck: 0.2.3
ipsec: 0.0.4
network-services: 0.0.10
scheduler: 0.4.0

**Docker Version:**
Docker version 1.12.3, build 6b644ec

**OS and where are the hosts located? (cloud, bare metal, etc):**
AWS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher, external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Unsure

**Results:** 
When restarting the `healthcheck` service on one of our hosts, the `rancher-agent` on the same host restarts with the following error:

```
panic: runtime error: slice bounds out of range

goroutine 233 [running]:
panic(0x8e8a40, 0xc42000c0c0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
bufio.(*Reader).ReadSlice(0xc42012b440, 0xa, 0x0, 0xc420313748, 0x4b7358, 0xc4203cf2e0, 0x878a7b)
	/usr/local/go/src/bufio/bufio.go:308 +0x1ee
bufio.(*Reader).ReadBytes(0xc42012b440, 0x442f0a, 0xc420313bc0, 0x9af11e, 0x1, 0x0, 0x1)
	/usr/local/go/src/bufio/bufio.go:408 +0x66
bufio.(*Reader).ReadString(0xc42012b440, 0x9af10a, 0x1, 0xc420313bc0, 0x1, 0x20)
	/usr/local/go/src/bufio/bufio.go:448 +0x38
github.com/rancher/agent/service/hostapi/stats.getContainerStats.func1(0xc42012b440, 0xc420391e60, 0x4418, 0xc420392ea0, 0xc420377b00)
	/go/src/github.com/rancher/agent/service/hostapi/stats/common.go:38 +0x83
created by github.com/rancher/agent/service/hostapi/stats.getContainerStats
	/go/src/github.com/rancher/agent/service/hostapi/stats/common.go:53 +0x1bc
```

The result is that many services on this host are yellow (as they are not checked by the healthcheck).

Any idea as to how to fix this?

**Comment by 0ff** [comment]
Rebooting the affected host resolved the problem; restarting `rancher-agent` did not.

**Comment by superseb** [comment]
Please reopen if issue persists.
