### ISSUE TITLE
unable to resolve own service name

### ISSUE THREAD

**Issue by santo74** [rancher/rancher#7903]
**Rancher Versions:**
Server: v1.4.1
healthcheck: v0.2.3
ipsec: v0.8.7
network-services: metadata: v0.7.0, network-manager: v0.4.5
scheduler: v0.6.3
kubernetes (if applicable):

**Docker Version:**
v1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04 on cloud servers

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher, internal db

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Deploy or upgrade one or more services
exec into (one of) the container(s) and do an nslookup of its own service name

e.g. if you deploy a service called my-service, then try the following:
`nslookup my-service 169.254.169.250`

**Results:** 
Sometimes this works, sometimes it doesn't.
Because I need the service name during the startup of my application in order to set up a cluster, this has a severe impact on the availability of my application.
I.e. when the service name can't be resolved, my application won't be able to set up / join the cluster and finally exits with an error.

** Expected result:**
```
bash-4.3$ nslookup my-service 169.254.169.250
Server:    169.254.169.250
Address 1: 169.254.169.250

Name:      my-service
Address 1: 10.42.134.130 6955d9f801ac
```

After several minutes it often start works, but then it's too late because my application already exited

**Comment by maltyxx** [comment]
me too :(

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
