### ISSUE TITLE
Test label with only key for require_any Constraints

### ISSUE THREAD

**Issue by StrongMonkey** [rancher/rancher#7905]
Need to test the following functionality added to external scheduler:
In require_any label, if host has a label: `io.rancher.scheduler.require_any: foo=bar,foo1`
Then any service with a label that has key foo1 will meet the requirement no matter what value it has .
For example,
Service A has label `foo1=bar1`, 
Service B HAS label `foo1=bar2`,
Both are qualified for the hosts.

**Comment by cjellick** [comment]
Can't be assign to @sangeethah as we haven't released the scheduler for this yet.

**Comment by sangeethah** [comment]
Tested with latest build from master, rancher/scheduler:v0.7.1 and rancher/network-manager:v0.4.6 .
io.rancher.scheduler.require_any label is case insensitive.
Host with require_any label set to only keys (with out any values) like  ```io.rancher.scheduler.require_any: foo=bar,foo1``` is allowed to have containers with labels that have the keys set to "foo1" with label's value being anything like ```foo1=bar1``` or ```foo1=bar2```.
