### ISSUE TITLE
k8s - LB is provisioned on node with label etcd=true

### ISSUE THREAD

**Issue by pulberg** [rancher/rancher#7909]
**Rancher Versions:**
Server: v1.4.1
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable): rancher/k8s:v1.5.2-rancher1-2

**Docker Version:**
1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):**
RHEL7.3, vmware

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node Rancher, external mysql db

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
k8s

**Steps to Reproduce:**
in the k8s dashboard -
create a deployment, add an "external" service listening on a port (i used nginx:latest, 80:80)

**Results:** 
observe that the service LB gets created on a node with label etcd=true

![screen shot 2017-02-21 at 1 07 45 pm](https://cloud.githubusercontent.com/assets/11069351/23180361/ccb3c1ec-f836-11e6-8c16-30748864b2ae.png)

**Expected Behavior**
LB's should not be created on dedicated etcd hosts

**Comment by deniseschannon** [comment]
From a duplicate issue: Spoke with @alena1108 about making the ingress controller hae a configuration option to request to not schedule on the planes.

**Comment by pulberg** [comment]
"removed this from the Release 1.7.0 milestone", so...will this be addressed in any release before Rancher 2, or be addressed as part of Rancher 2?

**Comment by pulberg** [comment]
@deniseschannon @alena1108 I still have this issue in Rancher v1.6.14

![screen shot 2018-01-30 at 2 05 51 pm](https://user-images.githubusercontent.com/11069351/35588658-ef0c65d4-05c6-11e8-9531-3537f0cc3076.png)

Services are a part of many k8s charts that I have been testing/using.  I tried the example here - http://rancher.com/docs/rancher/v1.6/en/kubernetes/ingress/#example-of-scheduling-a-load-balancer-on-a-host, but it didn't seem to work - `io.rancher.scheduler.affinity.host_label: "foo=bar"`, does this only apply to ingress or services as well?

Phillip

**Comment by pulberg** [comment]
@deniseschannon any update on if this will make into Rancher v1.6.xx+ or only Rancher v2?

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

In Rancher v2, this should be fixed as the nodes are marked as non-schedulable.
