### ISSUE TITLE
All template categories were first letter upper case all rest were lower.  Now test is showing up as all lower

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#7911]
**Rancher Versions:** master 2/21

**Steps to Reproduce:**
1.  Add 3 templates, Add Test to first one as category, TEST to second and test to third
2.  Refresh catalog and click on Category drop-down

**Results:** 
![image](https://cloud.githubusercontent.com/assets/11514927/23186219/8f84180a-f843-11e6-95e6-c7b2d3451363.png)

Before in 1.4
![image](https://cloud.githubusercontent.com/assets/11514927/23186251/acccf6a2-f843-11e6-9a8a-f6451fb2e708.png)

**Comment by tfiduccia** [comment]
Vincent said this was you.

**Comment by joshwget** [comment]
This should be fixed in v0.16.4

**Comment by tfiduccia** [comment]
Version - master 3/2
Verified fixed
