### ISSUE TITLE
Not cleaning up Categories from catalog_category once templates that uses it is removed

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#7912]
**Rancher Versions:** master 2/21

**Steps to Reproduce:**
1.  Remove community catalog
2.  Go to db and do a select all from catalog_category

**Results:** Notice that even thou I removed all those templates, the categories associated to them are still in db.

**Comment by joshwget** [comment]
Does this cause any issues? This is kind of how I expected it to work.

**Comment by tfiduccia** [comment]
Clean-up is important?
