### ISSUE TITLE
Links and Sidekick names need to be converted to lower_case

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#7914]
Create two services with Upper case names. Say Stack: ST1, services S1, S2. Link S1->S2.

```
curl -H "Accept: application/json" 169.254.169.250/latest/services/13/links
{"ST1/S2":"db"}
```

This link should be stored in lower case.

This same issue is applicable to a service with sidekicks started with Upper Case.
```
curl 169.254.169.250/latest/services/14/sidekicks/0
S1SK1
```

**Comment by sangeethah** [comment]
Tested with rancher/metadata:v0.8.7.

Creates a service S1 with sidekick SK2 and SK3.
Create service - hello1 and link it to service S1.

links and sidekick metadata are presented in lowercase.
```
root@7ffb0f4d3f04:/# curl rancher-metadata/latest/services/hello/links
test4%2Fs1
root@7ffb0f4d3f04:/# curl rancher-metadata/latest/services/s1/sidekicks/1
sk3root@7ffb0f4d3f04:/#
```
