### ISSUE TITLE
Document recommendation to cleanup etcd volume mount on host when k8s environment gets recreated

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#7915]
As we do not cleanup etcd volume mount created by k8s etcd service - for DR recovery purpose - we should document the cases where we actually advise TO clean it up.

1) When host is being re-added to the different environment where k8s needs to run.
2) When k8s system stack gets removed and recreated (via user's manual steps) on the same set of host.

If cleanup is not performed, the data from saved etcd volume will be used by the new k8s system stack. It can cause several problems like:

1) User might not want to recreate the all pre-existing k8s apps that are stored in etcd data, yet it is gonna happen when k8s API service gets connected to the etcd service mapped to saved etcd data.
2) IMPORTANT: every new k8s API service obtains a new certificate from Rancher. That makes all previously created k8s secrets stored in etcd volume, obsolete. It means that any k8s app that needs to communicate with k8s api service - dashboard, helm, heapster, and any user app that needs this kind of communication - broken. And the only way to work around that - recreate user pods using the old set of secrets.

@wlan0

**Comment by deniseschannon** [comment]
Added in 1.5 docs.
