### ISSUE TITLE
Azure driver does not support AzureUSGovernmentCloud regions

### ISSUE THREAD

**Issue by codevalve** [rancher/rancher#7916]
**Rancher Versions:**
Server: 1.4.1

**Docker Version:**
1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04 LTS , bare metal

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle/Azure

**Steps to Reproduce:**
Add a new host using Azure driver (For AzureUSGovernmentCloud)

**Results:** 
Azure.com regions are not available to the Azure.us system.

**Comment by tfiduccia** [comment]
Version - master 2/21
We don't have the government regions in the drop-down.  The ones we need to add are:
US GOV VIRGINIA	US GOV IOWA	US DOD EAST	US DOD CENTRAL

**Comment by vincent99** [comment]
Obviously we can't test them, but they're there now... https://github.com/rancher/ui/pull/1081

**Comment by tfiduccia** [comment]
version - master 4/27
Verified fixed

**Comment by codevalve** [comment]
Thanks!
