### ISSUE TITLE
rancher-metadata runs at high CPU

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#7922]
**Steps to Reproduce:**
Create a test stack: testservicealiases
Create two services s1 and s2 in this stack.
Now add a service alias s12 and point to both these services s1 and s2.
Create one more service alias sz -> s12
create one more service alias sy -> sz
create one more service alias sx -> sy
Now edit sz and point it to both s12 and sx.

This will cause rancher-metadata to run at very high CPU.

**Results:** 
The service alias loop shouldn't cause high CPU usage.

**Comment by tpgxyz** [comment]
rancher/metadata:v0.7.0 hogs CPU. docker 1.10.3

all i see in rancher docker is this:
time="2017-03-01T20:35:11Z" level=info msg="Downloaded in 122.144ms" 
time="2017-03-01T20:35:11Z" level=info msg="Loading answers" 
time="2017-03-01T20:35:12Z" level=info msg="Loaded answers" 
time="2017-03-01T20:35:12Z" level=info msg="Applied http://abf.openmandriva.org:8080/v1/configcontent/metadata-answers?version=166776-5cc6db6887beb3525be1bd696730805e" 
time="2017-03-01T20:35:12Z" level=info msg="Downloaded in 152.465ms" 
time="2017-03-01T20:35:12Z" level=info msg="Loading answers" 
time="2017-03-01T20:35:12Z" level=info msg="Loaded answers" 
time="2017-03-01T20:35:12Z" level=info msg="Applied http://abf.openmandriva.org:8080/v1/configcontent/metadata-answers?version=166776-5cc6db6887beb3525be1bd696730805e"

@fedya

**Comment by fedya** [comment]
@tpgxyz looking

**Comment by ibuildthecloud** [comment]
This should be significantly better in Rancher 1.5.x w/ metadata >= v0.8.x

**Comment by superseb** [comment]
Should be fixed in 0.7.2, and above. Please file a new issue if you experience problems with metadata.

**Comment by tuwid** [comment]
Having the same issue on rancher 1.6.2 / Ubuntu 16.04 / docker 17.03.1-ce, build c6d412e

**Comment by kilmarnock** [comment]
Having the same issue on rancher 1.6.3 / Ubuntu 16.04 / docker 1.13.1   @superseb
I observer high cpu on the rancher service also. iotop on mysql shows high traffic on disk writes causes by rancher

**Comment by superseb** [comment]
@tuwid @kilmarnock Thanks for reporting, are your issues related to the scenario described on top? If not, please find other issue matching your case or create a new one.

**Comment by kilmarnock** [comment]
sorry, you are right. my scenario is different.
