### ISSUE TITLE
ui.pl doesn't support Chinese character

### ISSUE THREAD

**Issue by pengjiang80** [rancher/rancher#7923]
Go to advanced settings, set ui.pl to Chinese character. Refresh the page, internal error 500 will be returned.
Can only recovered by modifying the database setting table directly. 

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.4.1` Cattle: `v0.176.9` UI: `v1.4.6` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`admin-tab.settings`|

**Comment by vincent99** [comment]
Does this still happen, and is it with a 3-byte character or 4-byte?  There's no reason settings shouldn't be able to handle 3-byte, but the default character encoding of tables doesn't support 4-byte characters (less common things, and many emoji).

**Comment by tfiduccia** [comment]
@loganhz - can you give me an example of Chinese characters that should work.  The ones I put in still gave me a 500 page.

**Comment by loganhz** [comment]
It looks good in `rancher/server:v1.6.15-rc8`. Can you please try 中国 ?

**Comment by tfiduccia** [comment]
Version - v1.6.15-rc8
Verified fixed
