### ISSUE TITLE
[CLI] Provide an official Rancher CLI image

### ISSUE THREAD

**Issue by kelchm** [rancher/rancher#7924]
It would be fantastic if an official Rancher CLI image could be provided on Docker Hub. Of course I can roll my own, but part of the beauty of containers is being able to leverage pre-existing images.

For me this would be most useful for setting up automated deployments from GitLab.

**Comment by kelchm** [comment]
Noticed this the other day: https://hub.docker.com/r/rancher/cli/

Thanks @ibuildthecloud :+1:

**Comment by superseb** [comment]
Closing this as request is fulfilled.
