### ISSUE TITLE
Rancher doesn't work with Kubernetes cluster autoscalar

### ISSUE THREAD

**Issue by ryanwalls** [rancher/rancher#7925]
**Rancher Versions:**
Server: 1.4.1
kubernetes (if applicable): rancher/k8s:v1.5.2-rancher1-2

**Docker Version:**
1.13.1

**OS and where are the hosts located? (cloud, bare metal, etc):**

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes 

**Steps to Reproduce:**
Setup standard kubernetes environment.  
Try to deploy kubernetes cluster auto scalar for AWS.   (https://github.com/kubernetes/charts/tree/master/stable/aws-cluster-autoscaler)

**Results:** 
Get error log:
```
2017-02-22T17:47:53.283080951Z W0222 17:47:53.282795       1 cluster_autoscaler.go:202] Cluster is not ready for autoscaling: Wrong id: expected format aws:///<zone>/<name>, got rancher://8b0288af-5ee7-430c-8621-9c801fe655c3
```

The problem is that the autoscalar is looking for a `node.Spec.ProviderID` that matches the format `aws:///zone/name`.  See: https://github.com/kubernetes/contrib/blob/da3de63e48323ea9cfa2ce2abcd66d662e330b53/cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go#L77 

It appears that rancher doesn't follow this pattern for its provider id.

**Comment by pulberg** [comment]
When you set up k8s, did you pick AWS as the cloud provider? - 

![screen shot 2017-02-22 at 6 39 29 pm](https://cloud.githubusercontent.com/assets/11069351/23239717/75e4b472-f92e-11e6-9537-70f0aa494dc4.png)

**Comment by ryanwalls** [comment]
@pulberg Where is that screenshot from?  I didn't see options like this when I setup the k8s environment in rancher.

**Comment by pulberg** [comment]
@ryanwalls Looks like these options are only available if you set up your env like - 

1. create a new "Cattle" env, then from the catalog, select "Kubernetes", you will be presented with screen of options for k8s env.

2. create a custom env template, select "Kubernetes", the select "edit config", you will then be presented with screen of options for k8s env.

**Comment by deniseschannon** [comment]
I recently added docs on how to set up cloud providers for k8s.

http://docs.rancher.com/rancher/v1.4/en/kubernetes/providers/

**Comment by ryanwalls** [comment]
@pulberg Thanks.  That got it fixed for me.

@deniseschannon Great.  That was a good addition.  Might be good to describe how to update an existing k8s environment, or explicitly say that an existing one cannot be updated to use AWS as a provider.

**Comment by nikitsrj** [comment]
Hey Guys, How we can use this in rancher 2.0, RKE
