### ISSUE TITLE
[Webhooks:ServiceUpgrade] Sidekicks are not upgraded for service upgrade through webhooks

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#7932]
**Rancher Versions:**
Server: Master

**Docker Version:**1.13.1

**OS and where are the hosts located? (cloud, bare metal, etc):**Ubuntu, Cloud

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**Single node

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**Cattle

**Steps to Reproduce:**
1. Create a service with sidekick, both having the same label test1=value1 and different images
2. Create a webhook to upgrade service with tag latest and label test1=value1
3. Use the URL generated from the webhook creation in step 2 and add it as a dockerhub webhook
4. Push the image with latest tag

Only the primary service gets upgraded to the latest version. Sidekick is not upgraded to the latest version

Expected:
Sidekick should also be upgraded to the latest version of the image

**Comment by mrajashree** [comment]
@soumyalj @sangeethah these are the upgrade cases for services with sidekicks
1. If service has the label and sidekick doesn't, just upgrade service
2. If just sidekick has the label, only upgrade sidekick
3. If both have label, upgrade them both
Is this right?

**Comment by sangeethah** [comment]
@mrajashree , yes. 
Additionally , service can have multiple sidekicks. It is possible that only one of the sidekicks or few/all sidekicks to be qualified for upgrades depending on the labels.

**Comment by mrajashree** [comment]
@sangeethah yes the PR is covering that case too

**Comment by soumyalj** [comment]
Tested with master with the following steps:

1. Create a service with primary service having label test1=value1, image "redis" and sidekick having label test2=value2, image "nginx"
2. Create a webhook to upgrade service with tag latest and label test2=value2
3. Use the URL generated from the webhook creation in step 2 and add it as a dockerhub webhook
4. Push an ubuntu image with latest tag

Only the sidekick gets upgraded to the new image as expected. But the primary service is also getting upgraded/recreated with the same configuration it had .

**Comment by soumyalj** [comment]
Tested with master. Followed the steps above, only sidekick is upgraded to the new image and the primary service is not upgraded/recreated with the same configuration it had.
