### ISSUE TITLE
Memory/Cpu resources held by a deleted instance is not released until they are purged.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#7933]
Rancher Versions: Build from master
Steps to reproduce the problem:
There are 3 hosts in the setup with 1000 mcpu.

Create a service with cpu reservation set to  400 mcpu (which ends up accounting for 800 mcpu - https://github.com/rancher/rancher/issues/7930) with scale 3.

1 instance of the service gets deployed in each of the hosts.

Delete this service.

Create another service with cpu reservation set to  400 mcpu  with scale 3.
Instances are not getting deployed on any host because of cpu reservation requirement not being satisfied since the resources held by deleted instances are not released . 

After some time , instances are able to launch successfully on the host when the deleted instances get to "purged" state when the resources actually get released.

Expected Behavior:
We expect the Memory/Cpu resources held by a deleted instance  to be released immediately , so that it can be allocated to other containers.

**Comment by StrongMonkey** [comment]
could either be addressed by https://github.com/rancher/cattle/pull/2516 or https://github.com/rancher/cattle/pull/2427.

**Comment by StrongMonkey** [comment]
move to the next release

**Comment by cjellick** [comment]
https://github.com/rancher/rancher/issues/7933
https://github.com/rancher/rancher/issues/8568

**Comment by sangeethah** [comment]
Tested with rancher-server version - v1.6.0-rc3
Setup has 3 hosts in the setup with 1000 mcpu.

Create a service with cpu reservation set to 800 mcpu with scale 3.
1 instance of the service gets deployed in each of the hosts.
Delete this service.

Create another service with cpu reservation set to 800 mcpu with scale 3.
1 instance of the service gets deployed in each of the hosts without encountering any allocation failures.
