### ISSUE TITLE
k8s - k8s dashboard "service unavailable" if not logged into Rancher

### ISSUE THREAD

**Issue by pulberg** [rancher/rancher#7934]
**Rancher Versions:**
Server: v1.4.1

kubernetes (if applicable): 
rancher/k8s:v1.5.2-rancher1-2

**Docker Version:**
1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):**
RHEL7.3, vmware

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node Rancher, external mysql db

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
k8s

**Steps to Reproduce:**
log into Rancher, change to a k8s env, launch k8s dashboard ui, log out of Rancher, refresh k8s dashboard ui

**Results:** 
"Service Unavailable" on k8s dashboard ui if logged out of Rancher.

**Comment by hicaoc** [comment]
same problem
![image](https://cloud.githubusercontent.com/assets/8174631/23251083/cf5f814a-f9e6-11e6-9403-3df446c37537.png)

**Comment by RyanHartje** [comment]
Experiencing this on RancherOS guest vm on Libvirt (Centos7) as well
Docker Server 1.4.1
ancher/k8s:v1.5.2-rancher1-2
Docker version 1.12.6, build 78d1802
RancherOS on Centos7/KVM
One guest vm for RancherOS Server
Another guest vm for the agent

Steps to reproduce:
Log into rancher, change to a k8s env, launch k8s dash ui (never logs in)

What logs or other tools can be used to troubleshoot this? Thanks in advance for any help.

**Comment by hadyrashwan** [comment]
I confirm having the same issue on
rancher version:1.5.1

**Comment by vincent99** [comment]
While not the most helpful message, this is a feature.  Rancher access control controls access to the kubernetes running inside it, if you're not logged in then you can't user it.

**Comment by pulberg** [comment]
@vincent99 That seems to contradict the reason that Rancher stopped using their own k8s pages, and decided to use the native k8s dashboard introduced in 1.4.0, what is the point of giving users the native k8s ui if i have to go to the Rancher ui anyway? #ux101

**Comment by Kagu-chan** [comment]
@vincent99 i got it that this is a feature, but im logged in in my case (which is btw only working with http, not https (via proxy reverse)).
Should i create a new ticket or can someone provide a link with further information and troubleshooting?
(Also - can i run default environment and k8 environment on the same machine? it disconnected my other env and im afraid i cant manage the other containers as before...)

**Comment by dexterddit** [comment]
I don`t know if it`s related or not but seam to be having the same issue . 

Rancher Versions:
Server: v1.5.10


Docker Version:
1.12.6 (for nodes)
17.03-ce (for server)

OS and where are the hosts located? (cloud, bare metal, etc):
Centos7 Xenserver
Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)
single node Rancher, external mysql db

Environment Type: (Cattle/Kubernetes/Swarm/Mesos)
k8s

Steps to Reproduce:
Deploy service and try to access dashboard 
Note :
Results:
"Service Unavailable" on k8s dashboard

**Comment by jackiehope** [comment]
@dexterddit I have the same environment and facing the same problem.
But i think the reason is that my k8s-dashboard is not ready.
```
# kubectl get nodes
NAME        STATUS     AGE
localhost   NotReady   9m
```
`Infrastructure Stacks` is healthy but kube pod stuck in Pending.
```
# kubectl get pods --all-namespaces
NAMESPACE     NAME                                    READY     STATUS    RESTARTS   AGE
default       mysql-vhfpk                             0/1       Pending   0          51m
kube-system   heapster-818085469-chgfq                0/1       Pending   0          1h
kube-system   kube-dns-1208858260-nt95c               0/4       Pending   0          1h
kube-system   kubernetes-dashboard-2492700511-p8cjh   0/1       Pending   0          1h
kube-system   monitoring-grafana-832403127-crn8v      0/1       Pending   0          1h
kube-system   monitoring-influxdb-2441835288-m247m    0/1       Pending   0          1h
kube-system   tiller-deploy-3991468440-zln7b          0/1       Pending   0          1h
```

**Comment by anjia0532** [comment]
Where are you from? in china , u can not download from gcr.io because gfw firewall. u need change `kube-system` image source

**Comment by jackiehope** [comment]
@anjia0532  哈哈，被发现了。卡了这么久大家都知道是什么原因，开了代理就ok了。

**Comment by anjia0532** [comment]
@jackiehope 你是咋开的代理？(how do u use proxy？) 系统全局代理？(os global proxy？) docker代理？(docker proxy？)，我用了docker代理，不起作用(the docker proxy setting is not work) 
 
https://docs.docker.com/engine/admin/systemd/#httphttps-proxy

我做了gcr.io的镜像(i make a gcr.io's mirror on docker hub)，超过1280个容器(more than 1280 containers) https://hub.docker.com/r/anjia0532/

**Comment by jackiehope** [comment]
@anjia0532  I forgot that, not using rancher for a few months。

**Comment by superseb** [comment]
This is becoming a gathering of different issues, please open a new issue when you experience problems. Regarding the original issue, I think it was already answered that the auth of Rancher is needed to access the dashboard.
