### ISSUE TITLE
Show vxlan as an option when creating a kubernetes template

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#7938]
**Rancher Versions:**
Server: 1.5.0-alpha1

When trying to add a new kubernetes template, vxlan doesn't show up as an option, instead you can see only ipsec.

![vxlan](https://cloud.githubusercontent.com/assets/3309968/23267346/24a7a7c0-f9f3-11e6-865b-ec8a37a34ee2.png)

**Comment by deniseschannon** [comment]
Verified with v1.5.0-rc6
