### ISSUE TITLE
[Rancher Agent] Agent v1.1.3 does not seem to detect existing containers running on a host and importing them into Rancher.

### ISSUE THREAD

**Issue by Niceplace** [rancher/rancher#7940]
**Rancher Versions:**
Server: stable
healthcheck: 0.2.0
ipsec: 0.8.1
network-services: 0.4.0
scheduler: 0.5.1
kubernetes (if applicable): N/A (using Cattle)

**Docker Version:**
1.12.6
**OS and where are the hosts located? (cloud, bare metal, etc):**
RHEL 7.2 (Maipo) - Cloud
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher external DB (Mysql)
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
1. Run active containers on host (in our case we have a mattermost instance as well as an ELK stack)
2. Launch rancher/server:stable
3. Launch rancher/agent:1.1.3 and register agent to the host

**Results:** 
4. Notice existing running containers are not shown in the GUI

@cjellick Referencing #47
More specifically : https://github.com/rancher/rancher/issues/47#issuecomment-281468469

To answer your questions : 

**If you deploy a container from the UI, does it come up successfully?** : I tried a jenkins installation, it came up and was running fine.

**If you do a simple docker run -d ubuntu from the host, does it show up in the UI?** Yup !

**Comment by aemneina** [comment]
This seems related to #7941. @Niceplace are you using docker-compose to spin up your ELK stack?

**Comment by Niceplace** [comment]
Yep ! Forgot to mention that.

I thought docker-compose was only a wrapper to native docker commands, I didn't think it would affect the behavior.

**Comment by aemneina** [comment]
sounds good, thanks for confirming!
