### ISSUE TITLE
docker-compose created containers not showing up in rancher

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#7941]
**Rancher Versions:**
Server: 1.4.1

**Steps to Reproduce:**
create a generic docker-compose.yml file
do a docker-compose up, with yaml, on a host managed by rancher

**Results:** 
container doesnt appear in the rancher API

**Expected:**
unmanaged containers should appear in rancher.

**Comment by StrongMonkey** [comment]
This is fixed in 1.5. Here is the related ticket https://github.com/rancher/rancher/issues/6911.
