### ISSUE TITLE
upgrading infra stacks doesnt have an indicator which template version is latest

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#7943]
**Rancher Versions:**
Server: 1.4.1

**Steps to Reproduce:**
- click upgrade on a infra stack item
- click on template version drop down

**Results:** 
you get a dropdown of versions, we make it clear what the current version in use is... but not what the latest or recommended template is.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
