### ISSUE TITLE
Cloning machine does not keep require.any labels

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#7944]
**Rancher Versions:** master 2/23

**Steps to Reproduce:**
1.  Add a Require Container label to a host
2.  Clone host

**Results:** The cloned host does not get the require.any label passed onto it.

**Comment by vincent99** [comment]
These would need to be copied from the original host and added to the host labels which will be used for the new host.

**Comment by vincent99** [comment]
..but this doesn't apply to 2.0 anyway.
