### ISSUE TITLE
Helm not working from the local machine or the web console

### ISSUE THREAD

**Issue by nithin-bose** [rancher/rancher#7947]
**Rancher Versions:**
Server: 1.3.4
healthcheck: 0.2.0
scheduler: kubernetes
kubernetes (if applicable): k8s:v1.5.1-rancher1-7

**Docker Version:**
1.13.1
**OS and where are the hosts located? (cloud, bare metal, etc):**
Hosts are running RancherOS v0.7.1 (4.4.24) on aws
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher with external db. The rancher master is exposed to port 80 with ``-p 80:8080`` while running rancher/server container
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes
**Steps to Reproduce:**
1. helm install stable/mysql (from local machine or the web console)

**Results:** 
``Error: forwarding ports: error upgrading connection: error dialing backend: dial tcp <host-ip>:10250: getsockopt: connection timed out``

**Expected:**
The package to be installed

I am using rancher catalogs for my deployments to the k8s cluster ans since the support for catalogs has been dropped in 1.4, I need to get helm working before I can migrate to 1.4.

**Comment by iambowen** [comment]
I have the same issue, using rancher server version 1.5.2

**Comment by moshe0076** [comment]
@iambowen I had the same problem. When I opened all the TCP ports between the Kubernetes hosts (Kubernetes 1.5.4 running on Rancher) it started working.
Can you check it?

**Comment by dawood95** [comment]
@moshe0076  TCP port was the problem. I assume helm needs a specific port ?

**Comment by iambowen** [comment]
right, do you mean the firewall rules or ?

**Comment by dawood95** [comment]
Yeah. Firewall

**Comment by iambowen** [comment]
cool, I get this, thanks~

**Comment by moshe0076** [comment]
https://github.com/kubernetes/helm/issues/2212

**Comment by superseb** [comment]
Thanks for reporting, we'll wait on the upstream fix.
