### ISSUE TITLE
[loadbalancer] Insecure headers X-Forwarded-Port and X-Forwarded-Proto

### ISSUE THREAD

**Issue by SamMousa** [rancher/rancher#7949]
The load balancer adds the following headers if not set:
`X-Forwarded-Port` and `X-Forwarded-Proto`

It also always overrides `X-Forwarded-For` with the real client IP.

The issue is that these headers are usually part of a group. If my application trusts the LB it will very likely trust all these headers. In reality, with the standard configuration rancher uses, 2 of these 3 headers are insecure and can be overwritten by (malicious) clients.

These are the headers my application receives:
````
["HTTP_X_FORWARDED_PROTO"]=>
  string(5) "https"
  ["HTTP_X_FORWARDED_PORT"]=>
  string(2) "-5"
  ["HTTP_X_FORWARDED_FOR"]=>
  string(12) "MY_REAL_IP"
````

Obviously I have to decide to trust those or not. But the current default configuration of the load balancer doesn't allow me to trust all fields. The `x-forwarded-for` can be trusted, but the others clearly cannot (this test environment doesn't use https and definitely not negative port numbers).

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
