### ISSUE TITLE
[rancher-compose] Can not create a stack

### ISSUE THREAD

**Issue by piwi91** [rancher/rancher#7950]
**Rancher Versions:**
Server: 1.4.1
rancher-compose: 0.12.2

**Docker Version:**
1.13.

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node Rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
1. Set env variables or add configuration as options to the CLI
2. Run `rancher-compose up -d`

**Results:** 

```
DEBU[0000] Environment Context from file : map[]
DEBU[0000] Opening compose files: docker-compose.prd.yml
DEBU[0000] [0/1] [prd-application]: Adding
DEBU[0000] [0/1] [prd-web]: Adding
DEBU[0000] Opening rancher-compose file: /home/administrator/projects/continuous-delivery/rancher-compose.yml
ERRO[0000] Failed to open project continuous-delivery: Can not create a stack, check API key [xxx] for [http://xxx:8080/]
FATA[0000] Failed to read project: Can not create a stack, check API key [xxx] for [http://xxx:8080/]
```

**Comment by deniseschannon** [comment]
You are using an account API key not en environment API key, which is needed for rancher-compose.

Please see the note in this section on how to get an environment API key:
http://docs.rancher.com/rancher/v1.4/en/cattle/rancher-compose/#setting-up-rancher-compose-with-rancher-server

**Comment by MCord** [comment]
It would be very helpful if the error message would be more explicit about this issue.
