### ISSUE TITLE
Global service instances do not respect required_any flag 

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#7951]
Rancher Versions: v1.5.0-rc1

Steps to reproduce the problem:
3 hosts in the setup
host1 - required_any - io.rancher.container.system , test1=value1
host2 - required_any - io.rancher.container.system , test1=value1 --> has scheduler running in this instance
host3  -  required_any - io.rancher.container.system , foo=bar

Create a global service with label foo-bar.
There is only 1 instance of  global service which lands in host3 as expected.
power down host2.

Notice that 1 instance of  global service now gets created in host1 even though this host is not available for this instance to deploy. This happens because of scheduler instance being unhealthy/unreachable at this point.

**Comment by StrongMonkey** [comment]
When external scheduler goes down we lost all the functionality it brings to us. We can solve this by duplicating the logic in cattle, but that is not what we actually want initially.

**Comment by StrongMonkey** [comment]
Launching multiple scheduler instance in a time will prevent single point of failure and eventually solve the problem, but it requires a bit of work to change the initial design of the external scheduler.

**Comment by deniseschannon** [comment]
After a change for another fix, global services are no longer respecting the `requires_any` label

**Comment by StrongMonkey** [comment]
move to next release as 1) need to figure out a new way to apply global service to external scheduler. 2) also require scheduler HA.

**Comment by SamMousa** [comment]
I'm getting this behavior regardless of hosts going down and up. My global services seem to totally ignore the required label setting on the host.

**Comment by SamMousa** [comment]
Why was this closed? Has it been resolved or has a decision been made that it won't be resolved?

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

**Comment by SamMousa** [comment]
I understand, does it make sense to have a label like `wontfix` for that? 
At the very least please leave a comment stating it won't be fixed.. :wink:
