### ISSUE TITLE
CNI plugin uses the same if_index for all the containers

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#7954]
Upstream CNI plugin (bridge) doesn't set the if_index on the container side properly. All the containers end up with the same if_index making it hard to track which container is associated with a particular veth.

Need to figure out the code and submit a PR to upstream CNI.

CC: @aemneina @wlan0 @ibuildthecloud

**Comment by leodotcloud** [comment]
Instead of fixing the if_index, another idea is to use the container ID in veth names instead of random ones.

**Comment by leodotcloud** [comment]
Fixed in Network Services v0.2.2, network-manager:v0.7.2

**Comment by sangeethah** [comment]
Tested with Network Services v0.2.2, network-manager:v0.7.3.

Containers on managed network have the veth names starting with "vethr" and the first few 10 characters of the container's docker ID.
