### ISSUE TITLE
Problem with dangling veth

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#7955]
On a k8s cluster, when the k8s-api-server container moves from one host to another, it leaves behind a dangling veth on the host. Due to this, any container running on the host where the past k8s-api-server container was running will have problems connecting with the api server.

To confirm the issue, install "arping" and run `arping kubernetes.kubernetes.rancher.internal` to see the duplicate ARP replies.

CC: @aemneina @wlan0 @ibuildthecloud

**Comment by leodotcloud** [comment]
Fixed in Network Services v0.2.2, network-manager:v0.7.3.

**Comment by sangeethah** [comment]
Tested with rancher-server version - v1.6.3-rc1 using Network Services v0.2.2, network-manager:v0.7.3.

Set up - rancher-server with 3 Rhel 7.3 hosts.

Deploy "pinger" from https://github.com/leodotcloud/pinger-catalog-item.git catalog.

Deploy "dokuwiki" stack from community catalog. This service has a sidekick  with start_once set to true.

Deploy "janitor"  stack from community catalog. This would result in cleaning up the sidekick instance of "dokuwiki-server " that is in stopped state, resulting in service reconcile kicking in and resulting in new instance of "dokuwiki-server " and its sidekick being created in new host.

After keeping this setup around for over night , there was no dangling veth on the hosts. 

There were few instances when the Network manager was able to detect dangling veths and clean them up.

```
time="2017-06-21T23:35:51Z" level=debug msg="vethsync/utils: checking for dangling veths"
time="2017-06-21T23:35:51Z" level=debug msg="vethsync/utils: dangling veth found: &{{20 1500 0 vethr8e6cecd3f0 c2:03:d0:5e:4f:4b up|broadcast|multicast 69699 3 4 <nil>  0xc4202420e0 0 <nil> ether} }"
time="2017-06-21T23:35:51Z" level=debug msg="vethsync: dangling: map[20:0xc4202a8ec0]"
time="2017-06-21T23:35:51Z" level=debug msg="vethsync/utils: cleaning up dangling veths"
```

**Comment by leodotcloud** [comment]
Link: https://github.com/moby/moby/issues/31937
