### ISSUE TITLE
Rancher UI becomes unresponsive, k8s dashboard won't load with many terminated Jobs

### ISSUE THREAD

**Issue by ryanwalls** [rancher/rancher#7959]
**Rancher Versions:**
Server: 1.4.1
kubernetes (if applicable): 1.5.2

**Docker Version:**
1.13.1

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu on AWS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher with external RDS

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
* Setup rancher environment with k8s.  
* Run a few hundred Jobs on k8s

**Results:** 
* Rancher UI became super slow/unresponsive.  
* k8s dashboard wouldn't load
* etcd stopped working in cluster

**Comment by vincent99** [comment]
The UI is the least of the problems (and dependent on etcd) if etcd is dying.

**Comment by ryanwalls** [comment]
Yep, I'd say the only improvement for this ticket now is to somehow notify the user when the dashboard is not responding correctly.  If this isn't a priority, feel free to close.

**Comment by superseb** [comment]
Regarding UI, we know at a certain amount it becomes unresponsive/sluggish and will be improved in 2.0.

Regarding scaling, we have upped the requests/limits for the dashboard by default and made them configurable in the template.

I don't think there are any limits on etcd, this would be running out of resources and must be ran on hosts with more resources I suppose.

Let me know if you don't agree.
