### ISSUE TITLE
DNS Update (RFC2136) cannot load self ca certificates

### ISSUE THREAD

**Issue by hiscal2015** [rancher/rancher#7960]
**Rancher Versions:** 1.4.1

** DNS Update (RFC2136) version: v0.6.2-rancher1

**Docker Version:** 1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):** Ubuntu16.04

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Kubernetes

**Steps to Reproduce:**

I have rancher running with SSL enabled, ca certificate was placed in /var/lib/rancher/etc/ssl/ca.crt, when I create DNS Update (RFC2136) from catalog, it failed to start with below errors:

2/26/2017 6:18:29 PMtime="2017-02-26T10:18:29Z" level=info msg="Starting Rancher External DNS service"
2/26/2017 6:18:29 PMtime="2017-02-26T10:18:29Z" level=fatal msg="Failed to configure cattle client: Get https://rancher.example.com/v1: x509: certificate signed by unknown authority"

Please help, thanks.

**Comment by hiscal2015** [comment]
Can anyone look into this please? Thanks.

**Comment by janeczku** [comment]
Hi @hiscal2015 self-signed certificates are currently not supported by the services in the Rancher catalog. See the docs here: https://docs.rancher.com/rancher/v1.4/en/installing-rancher/installing-server/basic-ssl-config/#using-self-signed-certs-beta

If you have to use a self-signed cert, you could crate a custom external-dns image injecting your CA certificate.

**Comment by hiscal2015** [comment]
@janeczku OK, so where can I find the dockerfile of dnsupdate rancher used?

**Comment by janeczku** [comment]
@hiscal2015 The dockerfile is here: https://github.com/rancher/external-dns/blob/master/package/Dockerfile

You can easily build a custom image derived from the official one and just add your CA certificate to the trust store. Something along  the lines of:

```
FROM rancher/external-dns:v0.6.1
ADD my-ca.crt /usr/local/share/ca-certificates/
RUN update-ca-certificates
```

**Comment by hiscal2015** [comment]
@janeczku make sense, really appreciate for the help!
