### ISSUE TITLE
Error messages for webhooks don't show properly, because they are wrong content type

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#7961]
**Rancher Versions:** master 2/26

**Steps to Reproduce:**
1.  Create a webhook
2.  Clone webhook and don't change name

**Results:** The message say "{"actions":{},"links":{"self":"http://104.154.31.113:8080/v1-webhooks/receivers"},"message":"Cannot have duplicate webhook name, webhook hostup already exists","status":"Server Error","statusCode":400,"type":"error"}"

UI can't parsed because the content type in response header is Content-Type:text/plain; charset=UTF-8, instead of JSON.

**Comment by mrajashree** [comment]
@tfiduccia sending it back, let me know if this issue persists with master

**Comment by tfiduccia** [comment]
Version - master 2/28
Verified fixed
