### ISSUE TITLE
Host webhook creating hosts with duplicate names

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#7962]
**Rancher Versions:** Master 2/26

**Steps to Reproduce:**
1.  Create a host scale 2 named hostname-1
2.  Add the label foo=bar on hostname-1
3.  Create a webhook to scale up 1 for label foo=bar
4.  Run webhook

**Results:** Creates a host called hostname-2, although it already exist.  We should check all host names and create unique host.

**Comment by mrajashree** [comment]
@tfiduccia but creation of hosts with duplicate names is allowed.

**Comment by tfiduccia** [comment]
@mrajashree - only by some drivers.   Not all host providers allow duplicate names.

**Comment by cjellick** [comment]
Interesting bug. Bit of an edge case. I'd rather not address in 1.5.0

**Comment by mrajashree** [comment]
moving out of 1.5 
cc @cjellick

**Comment by ItsReddi** [comment]
problematic driver for example, hetzner
its creating ssh keys based on host name, if the hostname allready exist, anything fails.

if youre scaling 15 host upwards an this error occurs the cpu on rancher will start to get panic and the rancher server is unreachable for some minutes.
