### ISSUE TITLE
Labels for webhooks are not case insensitive

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#7963]
**Rancher Versions:** master 2/26

**Steps to Reproduce:**
1.  Create host
2.  Add a label to host foo=bar
3.  Create a webhook for host with label Foo=Bar
4.  Run webhook

**Results:** Get 400 with error that host with label does not exist.  Labels for webhooks should be case insensitive just like the scheduler.

**Comment by tfiduccia** [comment]
@soumyalj - when you test case insensitivity for webhook (host), can you verify this?

**Comment by soumyalj** [comment]
Tested with master. Labels used for webhooks to scale a host are not case sensitive, but the case should be maintained when the host is cloned.

**Comment by soumyalj** [comment]
Tested with master again. Labels used for webhooks to scale a host are not case sensitive. The case is maintained when the host is scaled up.
