### ISSUE TITLE
[UI] Chinese characters can't be displayed correctly in web shell

### ISSUE THREAD

**Issue by pengjiang80** [rancher/rancher#7966]
Step to reproduce:

1.	Create a service with Ubuntu:14.04 docker image.
2.	Docker exec to the shell of container and run the following command:
a.	sudo apt-get install language-pack-zh-hans 
b.	locale -a and ensure zh_CN.utf8 is listed
c.	export LC_ALL='zh_CN.utf8'
3.	Create a file with Chinese filename in the host, for example “中文.log”
4.	Docker cp to copy the file into the container
5.	Docker exec to the container and run ls to check the file list inside container, 中文.log can be displayed correctly. 
6.	Go to the webshell through Rancher UI and ls check again, Chinese character can’t be displayed correctly.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.4.1` Cattle: `v0.176.9` UI: `v1.4.6` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`stacks.index`|

**Comment by tfiduccia** [comment]
Version - master 2/28
I was able to ssh through terminal and create the file.  I went to container's shell through rancher UI and the file is showing as ??????.log.
Here is a reference to previous bug that had same problem.  Looks like you updated xterm.js before to get it to work.

**Comment by loganhz** [comment]
the same issue via rancher cli
rancher exec -i -t 1iXXX bash

**Comment by dengshaodong** [comment]
Chinese can not be input from web terminal either.

**Comment by loganhz** [comment]
well....
it's not an issue at all.
The step is wrong.

export LC_ALL='zh_CN.utf8' 

should be 

echo export LC_ALL='zh_CN.utf8' >> ~/.bashrc

it's a basic linux knowledge

**Comment by tfiduccia** [comment]
@loganhz 
I tried using the echo export and still can't see my file
![image](https://cloud.githubusercontent.com/assets/11514927/23472483/3621ba56-fe6a-11e6-925b-6024d8480848.png)

**Comment by loganhz** [comment]
@tfiduccia 
please try to re-lanuch the shell or run
source ~/.bashrc
to make the setup load

![image](https://cloud.githubusercontent.com/assets/21168270/23488799/d94e42d4-ff29-11e6-90d4-513323186763.png)

**Comment by tfiduccia** [comment]
@loganhz = thanks that worked for me!

Verified  in master 3/2, steps to entering and see Chinese in shell:
1.  apt-get update
2.  install language-pack-zh-hans
3.  locale -a <to see if installed>
4.  echo export LC_ALL='zh_CN.utf8' >> ~/.bashrc
5.  source ~/.bashrc
6.  echo 'hello' > 中文.log
7.  ls

Closing bug.
