### ISSUE TITLE
[go-rancher] How to use client.Service.ActionRestart()?

### ISSUE THREAD

**Issue by emcniece** [rancher/rancher#7967]
**Rancher Versions:**
Server: 1.4.1
healthcheck: 0.2.3
ipsec: 0.8.7
network-services: metadata:v0.7.2, network-manager:v0.4.5
scheduler: 0.6.3

**Docker Version:** 1.13.1

I'm writing a Go app with [go-rancher](https://github.com/rancher/go-rancher) that needs to restart some specific containers. How is `client.Service.ActionRestart` supposed to be called?

```go
func main() {

  // my starter class - go-rancher is functional in `client` from here on
  client := rancher.NewRancherServer(*configFilePtr, *keysFilePtr)

  services, err := client.Service.List(&client.ListOpts{})
  if err != nil {
    log.Fatal("Could not list services")
  }
  for _, service := range services.Data {
    if service.Name == "nginx" {
      fmt.Printf("Service: %+v\n", service.Name )
      var ret, err = client.Service.ActionRestart(&service, RancherServer.Client.ServiceRestart)
      fmt.Printf("ret: %+v\n", ret)
      fmt.Printf("err: %+v\n", err)
    }
  }
```

... produces error:

```sh
# command-line-arguments
./main.go:39: cannot use RancherServer.Client.ServiceRestart (type client.ServiceRestartOperations) as type *client.ServiceRestart in argument to RancherServer.Client.Service.ActionRestart
```

Is there a good example somewhere of how to call these action methods?

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
