### ISSUE TITLE
lstat error when running rancher agent inside lxd container

### ISSUE THREAD

**Issue by charlesmulder** [rancher/rancher#7968]
**Rancher Versions:**

**Docker Version:**
Docker version 1.12.3, build 6b644ec

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu Xenial bare metal

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher server running in Ubuntu Xenial LXD container.
Unable to start an agent in another Ubuntu Xenial LXD container. 

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**

Install LXD on Ubuntu Xenial. 
```bash
$ sudo apt update
$ sudo apt install lxd
```
Launch Rancher Server
```bash 
$ lxc launch images:ubuntu/xenial/amd64 rancher-server -p default -p docker
$ lxc exec docker -- apt update
$ lxc exec docker -- apt dist-upgrade -y
$ lxc exec docker -- apt install docker.io -y
$ lxc exec rancher-server -- docker run -d --restart=unless-stopped -p 8080:8080 rancher/server
```
Launch Rancher Agent
```bash
$ lxc launch images:ubuntu/xenial/amd64 rancher-agent -p default -p docker
$ lxc exec docker -- apt update
$ lxc exec docker -- apt dist-upgrade -y
$ lxc exec docker -- apt install docker.io -y
```

Check the container IP for rancher-server
```bash
$ lxc list
```

Open the-container-ip:8080 in your browser

Add host

Copy the command to create an agent

Access the rancher-agent
```bash
$ lxc exec rancher-agent bash
```
Copy and paste the agent creation command. You should get the following error: 

**Results:** 
docker: Error response from daemon: linux runtime spec devices: lstat /dev/.lxc/proc/447/fdinfo/13: no such file or directory.

**Comment by boshido** [comment]
I got the same problem but I tried to run rancher-agent in lxc privileged container and got this error 
```
docker: Error response from daemon: linux runtime spec devices: lstat /dev/.lxc/proc/728/fdinfo/18: no such file or directory
```
I thought this problem should discuss to lxd team

I found one error that might relate to this issue

https://github.com/lxc/lxd/issues/2825

**Comment by CarltonSemple** [comment]
`docker: Error response from daemon: linux runtime spec devices: lstat /dev/.lxc/proc/728/fdinfo/18: no such file or directory`
is fixed with https://github.com/opencontainers/runc/pull/1327 .

So, as of the moment, you'll have to build docker referencing the runC version with that fix. It references runC here https://github.com/docker/docker/blob/1.13.x/hack/dockerfile/install-binaries.sh#L21

**Comment by infinitydon** [comment]
@CarltonSemple -- Please how did you apply this fix exactly, can you please provide some steps.

I am also facing the same problem.

**Comment by CarltonSemple** [comment]
@infinitydon are you trying to run privileged Docker containers inside of LXD? If so, there were other issues that ultimately blocked me.

**Comment by superseb** [comment]
Seems to be fixed in upstream rc (https://github.com/moby/moby/issues/32968), let me know if we can do anything within our scope to make this work.

**Comment by kopax** [comment]
@superseb Hi, is it possible to know in which version of docker-ce is this fix release ?

**Comment by superseb** [comment]
This was tested in 17.06 rc2 (https://github.com/moby/moby/issues/32968#issuecomment-307561319)
