### ISSUE TITLE
rancher cli doesn't return output from exec if run from non-interactive shell

### ISSUE THREAD

**Issue by stszap** [rancher/rancher#7971]
**Rancher Versions:**
Server: 1.4
healthcheck: 0.2.3
ipsec: 0.8.7
network-services: 0.4.5
scheduler: 0.6.3
cli: 0.4.1

**Docker Version:**
1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):**
3.12.52-gentoo-r1

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
cattle

We are trying to use Jenkins and Rancher for continuous integration. For some services before/after upgrade we need to call "rancher exec" and parse it's output (all of this in Jenkinsfile). But we discovered that "rancher exec" just always returns empty string. Same results if run in cron. From console everything works fine. As a workaround we are using "empty" emulator now.

**Steps to Reproduce:**
create cron job to ran rancher exec and save output to file
`*/1   *   *   *   *   /usr/local/bin/rancher exec Default/test uname -a >> /tmp/rancher_cli.log 2>&1`

**Results:** 
empty file 

If I run `/usr/local/bin/rancher exec Default/test uname -a >> /tmp/rancher_cli.log 2>&1` from console, file gets populated. I tried to add "-i" option, but it didn't help.

**Comment by eikevons** [comment]
I'm seeing the same issue. Probably related to [exec.go+55](https://github.com/rancher/cli/blob/master/cmd/exec.go#L55)?

Same as the reporter, this blocks me from using the cli on Jenkins.

I can reproduce the issue with 
```
% setsid sh -x -c "tty; ./rancher-v0.4.1/rancher exec -i $CONTAINER_ID does_not_exist; echo $?"  < /dev/null >log 2>&1`
% echo $?
0
% cat log # is empty
```

With an attached tty it's working:
```
% tty
/dev/pts/1
%  ./rancher-v0.4.1/rancher exec -i $CONTAINER_ID does_not_exist
rpc error: code = 13 desc = invalid header field value "oci runtime error: exec failed: container_linux.go:247: starting container process caused \"exec: \\\"does_not_exist\\\": executable file not found in $PATH\"\n"
% echo $?
126
```


---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.4.1` Cattle: `v0.176.9` UI: `v1.4.6` |
|Access|`ldap` |
|Orchestration|`Cattle`|
|Route|`stacks.index`|

**Comment by deviousgeek** [comment]
Same issue here with Rancher 1.4.1.

**Comment by eikevons** [comment]
As a workaround I'm now using `script` to fake a tty:
```
script --return --quiet --command "rancher exec -ti …" /dev/null
```

**Comment by dchambon** [comment]
@eikevons Could you share your Jenkinsfile? I tried your workaround but it seems that in my environment it does not work...

**Comment by bradjones1** [comment]
I think this is missing a bug label? There is a work-around, but it's a little awkward. Also, for anyone copy and pasting the code above, It needed the `-f` flag to work for me. See https://github.com/rancher/rancher/issues/8602#issuecomment-316909465

**Comment by nicholasdille** [comment]
+1 for a fix... and thanks @eikevons for the workaround

**Comment by gaieges** [comment]
@eikevons I had the same problem, but ran into some trouble with the `script` tool, namely that it adds junk data to the output of the command.  

For anyone else who's interested, I had luck with the `unbuffer` tool to solve this problem, which is part of the `expect` package in alpine:

`unbuffer rancher exec -it myservice curl -s localhost:8001/jsonendpoint | jq '.data[].id' -r`

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

**Comment by andree0** [comment]
If I use `unbuffer` or `script` on gilab for `rancher exec` command, I don't get any output. If I give command that should fail, job is still passed. If I use directly `rancher exec` I get error `provided file is not a console`.
Maybe someone helps ?

Rancher server 1.6
Environment on gitlab for command:
Rancher CLI v0.6.14
Python 3.11-alpine

**Comment by andree0** [comment]
My solution:
- use rancher cli v0.6.8
- use Docker-in-Docker image for pipelines job on Gitlab
- unset DOCKER_HOST variable before You use `unbuffer rancher exec -i ...` command
- you should install `expect` package (for alpine) and use `rancher exec -i` (important: with -i flag) inside `unbuffer` command

`unbuffer rancher exec ...` (without -i flag) will always succeed and you won't get output
