### ISSUE TITLE
[rancher-catalog] external-dns:v0.6.2 Updating Route53 too frequently

### ISSUE THREAD

**Issue by mortrom** [rancher/rancher#7977]
**Rancher Versions:**
Server: 
1.3.4

Agent:
1.1.3

healthcheck:
0.2.0

ipsec:
net/holder

network-services:
metadata: 0.7.0
dns: 0.13.0
network-manager: 0.4.0

scheduler:
kubernetes (if applicable): n/a

**Docker Version:**
1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04.2 LTS/Azure with AWS Route53

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node, multiple environment

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Install from catalog, selecting Route 53 DNS (certified)
Set all parameters as normal along with root domain set to "route53.svcengine.company.com" (obfuscated the host name to match the attached log example)
Immediately starts to repeatedly update DNS.
Occasionally considers the environment unchanged but more regularly removes and adds entries.
End result intermittent unaccessible sites.
Workaround at the moment is to switch this service off.
Note that two other environments are also active alongside, both with the same external-dns service running and only updating on change.  One of these two is the default environment.  Switching these off has no affect.
Also tried downgrading with the same result.

**Results:** 
See the attached file - host names and IPs have been filtered, debug has been set.
[rancher-externaldns-filtered.txt](https://github.com/rancher/rancher/files/805192/rancher-externaldns-filtered.txt)

**Comment by janeczku** [comment]
Hi @mortrom the issue here is that you have multiple instances of external-dns running alongside in different environments that are updating the same DNS names.
For example, there seem to be at least two instances that are updating the A records for `apimanager.apimanager.svcmanagement-default.route53.svcengine.company.com.` so you end up with a race between the two.

If the environments you are running external-dns in are using identical environment, stack and service names you need to configure each of the external-dns instances with a unique name template. E.g: 

name template for environment1:  %{{service_name}}.%{{stack_name}}.environment1
name template for environment2:  %{{service_name}}.%{{stack_name}}.environment1

I am closing this issue. Please reopen if this information does not solve the issue for you.

**Comment by mortrom** [comment]
Thanks for your response @janeczku 

The name template is set to the following in all environments

%{{service_name}}.%{{stack_name}}.%{{environment_name}}

Please explain why you think the apimanager line is being updated by two instances.

BTW I don't see anywhere for me to reopen this issue.

**Comment by janeczku** [comment]
@mortrom 

I assume "svcmanagement-default" is not a unique name but the name assigned to at least two different environments?

**Comment by mortrom** [comment]
No. **svcManagement-default** (for better or worse!) is a unique environment name.

The other two environments using external-dns are called (more conventionally) **Development** (the default) and **Test**.

What do you need to know?

**Comment by janeczku** [comment]
Well, something other than the service for which you provided the logs keeps changing this records IP address to `3.4.185.240`. That is what triggers the frequent updates, as the service is trying to modify the record back to `1.2.119.186` again.

> time="2017-02-27T04:16:19Z" level=debug msg="DNS records from provider: (...) {apimanager.apimanager.svcmanagement-default.route53.svcengine.company.com. [1.2.119.186] A 60}

> time="2017-02-27T04:17:20Z" level=debug msg="DNS records from provider: (...){apimanager.apimanager.svcmanagement-default.route53.svcengine.company.com. [3.4.185.240] A 30}

which then triggers the update back to the correct IP:

>  time="2017-02-27T04:17:22Z" level=info msg="DNS records to update: [{apimanager.apimanager.svcmanagement-default.route53.svcengine.company.com. [1.2.119.186]

**Comment by mortrom** [comment]
Thanks for your explanation @janeczku.

I've been pulled away to other things at the moment, but will investigate and update this issue.

**Comment by mortrom** [comment]
Looks like this mysterious issued has been solved.

After some digging I found a couple of servers no longer showing under the Rancher GUI but potentially still operating.  I couldn't access them, but following their deletion this issue has disappeared and this Rancher DNS service has remained stable since.

Thanks again @janeczku for your patience and help!
