### ISSUE TITLE
Can't create sidekick - Name is required error

### ISSUE THREAD

**Issue by esazhin** [rancher/rancher#7979]
**Rancher Versions:1.3.6**

**Docker Version:1.12.3**

**OS and where are the hosts located? (cloud, bare metal, etc): AWS**

**Environment Type: Cattle**

**Steps to Reproduce:
1. create a stack via rancher ui 
2. try to create a sidekick via UI with a name provided
**

**Results:** 
Fails to create the sidekick complaining that the name is required, while the name is there. See screenshot:

![image](https://cloud.githubusercontent.com/assets/7494500/23383644/7c967504-fd15-11e6-85c3-6e907b5eb21c.png)

**Comment by tfiduccia** [comment]
@esazhin - Looks like your Primary Service does not have a Name.  You have to have a name on both.

**Comment by esazhin** [comment]
@tfiduccia Yes, that's probably the actual reason - thank you! I didn't realize i can't create a sidekick separately from a service - which makes total sense. BUT the problem then is that I can't ADD a sidekick to already existing service - the upgrade UI doesn't allow that. So the only way to do that is to redefine service from scratch?

**Comment by sangeethah** [comment]
@esazhin  - Currently UI does not support the ability to Add/Remove sidekicks as part of upgrade which is tracked in https://github.com/rancher/rancher/issues/6381 . But we have support for Add/Remove sidekicks  as part of service upgrade at the API level.

**Comment by aemneina** [comment]
Looks like this was sorted and appropriate tracking ticket filed. Closing this out
