### ISSUE TITLE
Add instructions for migrating an unlabeled k8s to a labeled k8s

### ISSUE THREAD

**Issue by LLParse** [rancher/rancher#7980]
We need to document the procedure for migrating a kubernetes deployment without labels or with the old soft constraint labels to the new, hard constraint deployment model.

This applies for any k8s stack that is not `v1.5.2-rancher1-3` or later.

**Comment by LLParse** [comment]
The migration process is performed in two stages. The first stage involves setting the labels to automatically migrate the data and orchestration planes state of your k8s stack. We will also model the compute plane's current topology - k8s pods will not move in this stage.
1. Add hosts to your environment so you have at least 3 hosts dedicated to etcd, 2 hosts dedicated to orchestration, and 1 or more hosts dedicated to compute
2. Label at least 3 hosts with `etcd=true`.
2. Label at least 2 hosts with `orchestration=true`. You can technically get away with 1, but in the even of host failure, k8s API will be unavailable until a new orchestration host is added.
3. _For all hosts without the label_ `nopods=true`, add the label `compute=true`.
4. Perform the upgrade.

Now that this is done, you can move pods off of the data/orchestration hosts. Follow this procedure:

To move etcd off of a compute/orchestration host, you must initially have 3 healthy etcd containers. Once this is the case, follow this procedure:
1. Add a new host, if necessary, and label it `etcd=true`.
2. Remove the offending `etcd=true` label from the compute/orchestration host. On the same host, find etcd and delete its data container sidekick. This will force etcd to reschedule onto the new host. Wait until the new etcd becomes healthy (green circle).
3. If necessary, repeat these steps until all etcd containers are running on dedicated hosts.

To move pods off of a data/orchestration host, follow this procedure:
1. Remove the offending `compute=true` label from all data/orchestration hosts.
2. Open the CLI and run `kubectl delete node <host>`, where host is the hostname visible in Rancher UI. You may list the nodes by running `kubectl get node` if the hostname is truncated. If you are running important workload that needs to remain available, decommission the hosts one by one, ensuring resiliency is restored after every delete operation.

**Comment by pulberg** [comment]
@LLParse great to see the progress on this.  I decided to build a new k8s env in 1.5.0-rc1, is the `compute=true` label to be used to define where all user pods should go?  i noticed that the `kube-system` pods got set up on the nodes with `compute=true`  Am I incorrect in thinking that the `kube-system` pods should be on the nodes with `orchestration=true` since they are more of a "system" resource rather than a "user/client" resource.

![screen shot 2017-02-27 at 10 04 29 pm](https://cloud.githubusercontent.com/assets/11069351/23391313/b695600c-fd39-11e6-8872-2b229ea63223.png)

**Comment by LLParse** [comment]
@pulberg You are correct - `compute=true` dictates where _user_ pods should be go. We don't want the addons running on these hosts, but they currently do. To achieve the more appropriate placement of these pods would look like this:

Create new `kubelet-system` and `proxy-system` global services with hard affinity to `orchestration=true`. These kubelets will need to _taint_ their respective nodes, such that pods will not be scheduled except for PodSpecs annotated to _tolerate_ the taint. This alone isn't enough, we will also need to label the nodes on registration, such that PodSpecs may be annotated with a `requiredDuringSchedulingIgnoredDuringExecution` node affinity constraint to enforce the addon pods are _only_ scheduled to these special nodes.

**Comment by pulberg** [comment]
@LLParse thanks for the info. is what you described for hard affinity the "current" method for setup, or will it always be a set of manual steps?  just trying to gauge LOE with some of these things to determine what is "actually" important to me.

**Comment by pulberg** [comment]
@LLParse Also, is the fix for lb's being deployed on etcd hosts in the 1.5.x branch?

**Comment by LLParse** [comment]
@pulberg The hard affinity model is the only labeled model we are going to support from Rancher 1.5.0 moving forward. The migration steps listed above are a one-time procedure for upgrading an unlabeled / soft-constraint environment. From this point on, there will be no scheduling ambiguity.

The LBs aren't actually part of the template, unfortunately. The service is created by cattle (rancher server). I really can't speak to this one - it's tightly coupled with Rancher release cycle until we get it out of cattle, into the catalog. If the issue doesn't have a linked PR, it's safe to assume it won't be fixed.

**Comment by deniseschannon** [comment]
@pulberg Since you love testing bleeding edge, I just put some docs in our 1.5 branch, which will be published when 1.5 goes out. 

http://docs.rancher.com/rancher/v1.5/en/kubernetes/#configuring-kubernetes

http://docs.rancher.com/rancher/v1.5/en/kubernetes/resiliency-planes/

**Comment by pulberg** [comment]
Maybe I'm confused, but on 1.5.0-rc4 I am getting "user" pods created on hosts with `etcd=true`, shouldn't the pods only be going to hosts with `compute=true`?

![screen shot 2017-03-02 at 5 49 15 pm](https://cloud.githubusercontent.com/assets/11069351/23532386/dae63e66-ff70-11e6-99f3-c7b2cefeb8b2.png)

**Comment by deniseschannon** [comment]
Docs available:

http://docs.rancher.com/rancher/v1.5/en/kubernetes/upgrading/
