### ISSUE TITLE
Catalog service should return 404 for non-existant catalogs/templates/versions

### ISSUE THREAD

**Issue by joshwget** [rancher/rancher#7982]

**Comment by joshwget** [comment]
Should be fixed in v0.16.5.

**Comment by tfiduccia** [comment]
Version - master 3/2
Verified fixed

Format for testing this was:
<url>/env/1a5/catalog/<catalog name>:fakecatalog?catalogId=<catalog name>
Infrastruction, community and custom catalogs were tested
