### ISSUE TITLE
External services not appearing in load balancer configuration page

### ISSUE THREAD

**Issue by brettneese** [rancher/rancher#7984]
**Rancher Versions:**
Server: 1.4.0

**Docker Version:** 1.13

**OS and where are the hosts located? (cloud, bare metal, etc):** AWS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** HA rancher, external (RDS) DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:** 

1. Create external service
2. Attempt to add external service to the load balancer

**Results:** There is not an option to select the external service in the load balancer config.

This seemed possible at on point but appears to be a regression: https://github.com/rancher/rancher/issues/2624#issuecomment-277448137

I don't see where I could find the load balancer version number but I just updated to the latest one - 0.5.something.

(We're trying to get around some SSL cert mismatch issues by proxying our requests through Rancher.)

**Comment by tfiduccia** [comment]
Version - 1.5.0-rc1
External Services that use a hostname instead of IP address as Target are not showing up in the Target drop-down for Load Balancers.  This is indeed a regression of #2624.

**Comment by mathewpeterson** [comment]
I am also running into this on v1.4.1

**Comment by brettneese** [comment]
This is still broken in 1.5.5 :-(

**Comment by vincent99** [comment]
No, it's not.  External **hostnames** intentionally do not show up because balancing to a name has a variety of implications and tradeoffs and configuration that we do not have controls to manage.

External **IPs** were probably broken in 1.4 but work fine in 1.5.

**Comment by brettneese** [comment]
Yes, it very much is, because it is a regression of #2624.
