### ISSUE TITLE
Templates disappear

### ISSUE THREAD

**Issue by spender0** [rancher/rancher#7985]
**Rancher Versions:**
Server: 1.3.4
healthcheck: 1.2.0
ipsec: 0.0.2
network-services: 0.0.8
scheduler: 0.3.0
kubernetes (if applicable):

**Docker Version:**
 1.12.3
**OS and where are the hosts located? (cloud, bare metal, etc):**
 RancherOS v0.7.1 (4.4.24) amazonec2
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher and external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
1. Go to "manage environments"
2. Add a new public template. Cattle orchestration. Configured route 53 and rancher-ebs.
3. Go to other sections then return to "manage environments". 
**Results:** 
The new template is absent in the template list.

**Comment by spender0** [comment]
Here is a similar issue https://forums.rancher.com/t/templates-disappear/4990

**Comment by tfiduccia** [comment]
Version - master 2/28

Finally was able to reproduce.  The key work here was "public templates".  It seems random but it's probably after git clone fails.  It's definitely a bug.

**Comment by tfiduccia** [comment]
Version - v1.5.0-rc4
Verified fixed
