### ISSUE TITLE
Packet Loss across Rancher Managed Network on GCP

### ISSUE THREAD

**Issue by adamgoose** [rancher/rancher#7986]
I have 4 hosts at Digital Ocean, one bare-metal at our colo, and 3 hosts at Google Compute Engine.

For some strange reason, when making a `curl` request across the Rancher Managed Network (10.42.0.0/16) that returns an HTTP response of any sizable size, the connection simply halts and no HTTP headers are returned. However, while `curl`ing the exact same service over the public network (via a Traefik proxy), the HTTP headers and complete response return just fine.

This only occurs when running the `curl` from a GCE host (inside or outside of a container) to an IP of a container that is not on the same host. Running the `curl` from a DO or colo host works fine against the Rancher IP.

10.42.202.193:8500 is a consul master running on a GCE host (same issues when it runs on a DO host).

`curl -v 10.42.202.193:8500/v1/kv/neally/docker/env?recurse` from the colo host:

```
adam@bigdhost:~$ curl -v 10.42.202.193:8500/v1/kv/neally/docker/env?recurse
* Hostname was NOT found in DNS cache
*   Trying 10.42.202.193...
* Connected to 10.42.202.193 (10.42.202.193) port 8500 (#0)
> GET /v1/kv/neally/docker/env?recurse HTTP/1.1
> User-Agent: curl/7.35.0
> Host: 10.42.202.193:8500
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: application/json
< X-Consul-Index: 818206
< X-Consul-Knownleader: true
< X-Consul-Lastcontact: 0
< Date: Tue, 28 Feb 2017 09:22:17 GMT
< Transfer-Encoding: chunked
<
[{"LockIndex":0,"Key":"neally/docker/env/AMI_HOST","Flags":0,"Value":"...[truncated]
```

`curl -v 10.42.202.193:8500/v1/kv/neally/docker/env?recurse` from a GCE host that the target is *not* running on:

```
root@rancher-hosts-t3df:~# curl -v 10.42.202.193:8500/v1/kv/neally/docker/env?recurse
* Hostname was NOT found in DNS cache
*   Trying 10.42.202.193...
* Connected to 10.42.202.193 (10.42.202.193) port 8500 (#0)
> GET /v1/kv/neally/docker/env?recurse HTTP/1.1
> User-Agent: curl/7.35.0
> Host: 10.42.202.193:8500
> Accept: */*
>
[prompt hangs here]
```

`curl -v 10.42.202.193:8500/v1/kv/neally/docker/env/APP_ENV` (which returns a substantially smaller response) from the same GCE host works fine:

```
root@rancher-hosts-t3df:~# curl -v 10.42.202.193:8500/v1/kv/neally/docker/env/APP_ENV
* Hostname was NOT found in DNS cache
*   Trying 10.42.202.193...
* Connected to 10.42.202.193 (10.42.202.193) port 8500 (#0)
> GET /v1/kv/neally/docker/env/APP_ENV HTTP/1.1
> User-Agent: curl/7.35.0
> Host: 10.42.202.193:8500
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: application/json
< X-Consul-Index: 214337
< X-Consul-Knownleader: true
< X-Consul-Lastcontact: 0
< Date: Tue, 28 Feb 2017 09:27:51 GMT
< Content-Length: 130
<
* Connection #0 to host 10.42.202.193 left intact
[{"LockIndex":0,"Key":"neally/docker/env/APP_ENV","Flags":0,"Value":"cHJvZHVjdGlvbg==","CreateIndex":214337,"ModifyIndex":214337}]
```

The GCE hosts are running Docker 1.12.6, whereas the other hosts are running 1.12.5.

I'm relatively new to GCP, and advanced networking is a bit above my head. The only change to the Network settings in the GCP Console is illustrated below. I added the Rancher IP range and our own internal VPN IP range to the "internal" firewall rule.

![](http://d.enge.me/hDhN+)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.4.1` Cattle: `v0.176.9` UI: `v1.4.6` Docker: `1.12.5-6` |
|Access|`github` `admin`|
|Orchestration|`Cattle`|
|Route|`service.containers`|

**Comment by vincent99** [comment]
Containers are given an IP in 10.42.0.0/16 but those IPs are only used inside the overlay network, so adding that to firewall rules doesn't do anything.  That communication happens between the hosts registered IPs (as shown in the UI) over 500+4500/udp.  So you need a firewall rule to allow that between all the hosts.

**Comment by adamgoose** [comment]
Yeah, it isn't a firewall issue. I'm starting to think that it's because our Rancher nodes communicate with the Rancher server over our OpenVPN server. Thus, the nodes are communicating over IPSec over OpenVPN.

I spun up a new Rancher Server and nodes, all on GCP. They use the GCP private network to communicate (while they're all still on our OpenVPN, they don't communicate over that ix). Works great!

**Comment by vincent99** [comment]
With multiple layers involved like that my guess would then be MTU-mismatch; so packets are being sent that are too large, they're getting dropped and MTU path discovery isn't working for some reason in this situation.
