### ISSUE TITLE
ISO didn't recognized the HDD

### ISSUE THREAD

**Issue by mrmunch** [rancher/rancher#7987]
**Rancher Version:**
v0.8.1

**OS and where are the hosts located? (cloud, bare metal, etc):**
Cloud (KeyWeb: https://www.keyweb.de/de/)

**Issue:**
The IT team of KeyWeb wasn't able to install RancherOS from ISO because the ISO didn't recognized the HDD.

**Comment by aemneina** [comment]
@mrmunch you should probably file this here: https://github.com/rancher/os/issues I'm going to close this ticket out.
