### ISSUE TITLE
Upgrade hangs when unable to pull image

### ISSUE THREAD

**Issue by teamon** [rancher/rancher#7994]
**Rancher Versions:**
Server: 1.4.1
healthcheck: 0.2.3
ipsec: 0.0.4
network-services: 0.0.14
scheduler: 0.4.0

**Docker Version:** 
1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):** 
Cloud, CoreOS 1235.9.0

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher, internal db

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
1. Wait for AWS outage which takes down Docker Hub with it
2. Upgrade rancher service setting "always pull image"

**Results:** 
Service locked in "upgrading" state. When canceled stuck at "finishing", then stuck at "rolling-back" etc. Starting/stopping containers does not help.

Agent logs:

```
time="2017-02-28T19:54:20Z" level=error msg="Error processing event" err="Image [my/image:tag] failed to pull: Pulling repository docker.io/my/image" eventId=b209dedb-dc64-40b4-bd78-51dfdf86faf6 eventName=compute.instance.activate resourceId=1ihm713
```

**Expected behaviour**
When encountered an repeated pull image error rollback to previous version / use the image from host, or try to move into a different host that might have this image downloaded.

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
