### ISSUE TITLE
schedule against virtual-machine VCPU for virtual-machine use cases

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#7998]
Virtual machines have a different from containers for setting cpu: `vcpu`
We need to be able to schedule against that.

### Considerations
**Over/under provisioning**: we need a way for users to specify an amount to overprovision by.

- should vm's vcpu field be separate from cotnainer's milliCpuReservation field for the purposes of scheduling? Meaning you have two separate fields that do no impact each other.
- Should we allow users to specify this on a per host basis or once at the environment level?
- Should it be a label or an api field?

**Comment by cjellick** [comment]
Had a design discussion with @vincent99 and @ibuildthecloud. Here is what we came up with:

### High level analysis (and motivation for our solution)
VMs and containers are ultimately using the same cpu resource on the host (shares of CPU) and as such should use the same resource pool for scheduling purposes. However, in the container use case users are directly specifying the exact number of shares of the cpu.

In the VM use case, the user should normally only specify a number of vcpus. So for the vm use case, rancher should use an overprovisioning ratio to determine the value for milliCpuReservation based off of the user specified vcpu field. If the user explicit passes the milliCpuReservation field, then rancher will use the user supplied value and not do the default overprovisioning calculation.

This solution will give users a lot of control with sane defaults. We already pre-populate the amount of millCpu available on a host based off of the actual number of cores on the host and we allow the user to modify that number. Users can deploy containers with exact amounts of cpu and VMs with simple vcpu values that get sanely translated to an amoount of cpu that takes into account a configurable overprovisioning ratio. It will also allow us to distinguish between "fast" and "slow" cpus for vms in the future simply by allocating a higher number for the milliCpuReservation for "fast" vms.

### Implementation details
Schedulable host CPUs are tracked as milliCPUs. So, if a host has 8 cores, it has 8000 milliCpu that can be scheduled/allocated.

The formula for calculating milliCpuReservation from vcpu is `# of vcpu requested * overprovisioning setting = milliCpuReservation`.

We'll set the default overprovisioning setting to 100, so if the user created a vm with 2 vcpu, milliCpuReservation would be set to 200 (`2 * 100 = 200`).

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
