### ISSUE TITLE
ip address shown on UI does not reflect the real ip address in container

### ISSUE THREAD

**Issue by bseng** [rancher/rancher#7999]
**Rancher Versions:**
Server: v1.4.1
healthcheck: 
ipsec:
network-services:
scheduler:
kubernetes (if applicable):
no
**Docker Version:**
1.12.6
**OS and where are the hosts located? (cloud, bare metal, etc):**
centos at VM
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher external DB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
cattle
**Steps to Reproduce:**
start docker normally
start rancher
stop docker
change ip address for docker with -bip
start docker again
rancher container ip should be updated to the new one

**Results:** 
rancher container ip should be updated to the new one

ip address shown on UI
![image](https://cloud.githubusercontent.com/assets/1452937/23440948/5e0abe9c-fe73-11e6-88df-d3d10a288f0c.png)

ip address in shell
![image](https://cloud.githubusercontent.com/assets/1452937/23440964/74e173fe-fe73-11e6-9ea9-18f3c0c5df0a.png)

**Comment by leodotcloud** [comment]
@bseng can you please check if you are having the same problem with the latest release of rancher?

**Comment by superseb** [comment]
Closing as stale
