### ISSUE TITLE
Metadata refactoring

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#8004]
Today all metadata versions are being generated on cattle side, and propagated to all the hosts in cattle. Following improvements are needed:

PHASE1 - available as a part of Rancher 1.5

- [x] Generate basic set of data only on cattle side (list of containers, hosts, services, etc). All versions generation should be done on the rancher-metadata microservice side.
- [x] Stream json payload to the microservice instead of generating yml
- [x] Cache data on cattle side to minimize number of DB queries

PHASE2
- [ ] Split metadata microservice into master-slave configuration. Propagate data from cattle to master only. Versions are generated only on master, and then propagated to slaves.

**Comment by Rucknar** [comment]
@alena1108 Any docs/write-ups of how the metadata service is used?

I've forked the repo ands have begun looking at tuning the code to reduce the service impact of https://github.com/rancher/rancher/issues/9957 
It's not totally obvious how the metadadata service all hooks together.

**Comment by vincent99** [comment]
Metadata already updates incrementally for 2.0.  Any change that substantially improves this in 1.x is likely to be major impact (i.e. making it update incrementally) and a tough sell to get into stable.

Also the container you note in #9957 is rancher-dns, which is a sidekick of, and reader of, metadata.

**Comment by Rucknar** [comment]
@vincent99 Appreciate re-write is a separate issue. Was more thinking around the internal code to the metadata service and any potential improvements there. 

Updated the related issue, rancher-dns is just one of the containers hitting high CPU, i've included further info.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
