### ISSUE TITLE
github catlogs not showing in catlogs menu

### ISSUE THREAD

**Issue by alfredfrancis** [rancher/rancher#8006]
ive added following catalog url in settings.. https://github.com/alfredfrancis/rancher-catalogs
when i refresh im getting following log only..

time="2017-03-01T14:39:27Z" level=info msg="Using catalog pdd=https://github.com/alfredfrancis/rancher-catalogs.git"

rancher version : rancher v1.4.1.

**Comment by tfiduccia** [comment]
@alfredfrancis - Version v1.4.1 & master:
I am unable to reproduce your problem.  I added your catalog and was able to see it in the UI.
![image](https://cloud.githubusercontent.com/assets/11514927/23474145/f39396d6-fe6f-11e6-8cb0-94116f4a0abb.png)
![image](https://cloud.githubusercontent.com/assets/11514927/23474115/dec9e6d8-fe6f-11e6-87a0-1e1808238977.png)

**Comment by aemneina** [comment]
@alfredfrancis are you still hitting this? I'm going to close this ticket, feel free to holler if you have issues with this.
