### ISSUE TITLE
[rancher cli] Format flag not documented correctly

### ISSUE THREAD

**Issue by jmreicha** [rancher/rancher#8009]
**Rancher CLI:**
version: v0.4.1
OS: OSX

**Steps to Reproduce:**

Run any help command.  For example, `rancher env ls -h`.  It shows a message similar to,

```--format value  'json' or Custom format: {{.Id}} {{.Name}}```

**Results:** 

Then run `rancher env ls --format {{.Name}}` and the CLI errors.

Running `rancher env ls --format {{.Environment.Name}} / {{.Environment.Id}}` works, so I think the help docs just need to be fixed.

I tried the command on Windows as well and the `format` flag didn't seem to work at all.

**Comment by mishak87** [comment]
I think `.Environment` should become `.`.

**Comment by superseb** [comment]
This has been fixed in https://github.com/rancher/cli/commit/66de9b4b6b5d2f9e0a3b70d243ceb8aae0de2a18
