### ISSUE TITLE
Newly added catalog templates don't show up until refresh

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#8012]
**Rancher Versions:** master 3/1

**Steps to Reproduce:**
1.  Add a catalog
2.  Go directly to that catalog

**Results:** Templates aren't showing up.  They won't show up until a refresh is done.

**Comment by joshwget** [comment]
@vincent99 It looks like the catalog tabs in the UI don't come from the backend. I made a fix that doesn't add the catalog until the templates are cloned but I still see the tab for it showing up immediately.
