### ISSUE TITLE
Provide some indication on which planes different services of kubernetes stacks belongs.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#8017]
Rancher Versions: Build from master

Different services of the Kubernetes stack belong to one of the 3 planes (etcd/compute/orchestration).
compute plane:
addon-starter
proxy
kubelet

etcd plane:
etcd

Rest of the services are orchestration plane.

Can we provide some visual indication of which planes the different services of kubernetes stacks belongs to?

**Comment by LLParse** [comment]
@sangeethah Do you envision this as part of documentation or UI?
