### ISSUE TITLE
If I update already existing catalog with new version and catalog fails, you keep old one

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#8019]
**Rancher Versions:** Version master 3/1

**Steps to Reproduce:**
1.  Set library to enabled
2.  Go to catalog/library and make sure all templates have pulled
3.  Now disable library and create a custom item that has library as name but garbage in rest of fields.
4.  Go to catalog/library and refresh 

**Results:** Library templates are still there.  This is confusing cause I don't know that my new link is actually broken and I'm not getting updates for my catalogs.

**Comment by amy** [comment]
Proposal:
When either library or community catalogs are disabled, we should not display them. Along with that, we should receive an http status that denotes a failed refresh and display that error.
