### ISSUE TITLE
Restricted users cannot use Rancher CLI to view logs or exec

### ISSUE THREAD

**Issue by jayhding** [rancher/rancher#8020]
**Rancher Versions:**
Server: v1.4.1

**Docker Version:**
v1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):**
RHEL 7.2

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
External DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
1. Create a user as Restricted role
2. Use Rancher CLI to view container logs

**Results:** 
```
$ rancher logs <service or container name>
ERRO[0001] Failed to handle connection: Failed to find action: dockersocket
```

** Expected Results:**
According to https://docs.rancher.com/rancher/v1.4/en/environments/#restricted users with `Restricted` role should be able to able to perform all actions related to stacks/services and it is the case through Rancher UI. But it is not working with Rancher CLI.

After changing the user role to `Member`, checking logs via CLI works fine.

**Comment by aemneina** [comment]
@JayHaoDing There might have been an explicit/good reason for doing this... let me check around.

**Comment by aemneina** [comment]
Looks like a user with restricted access can view container logs from the UI.

**Comment by JayHaoDing** [comment]
@aemneina that's right and it is why I opened this issue. Good to see the kind is bug now :)

**Comment by cjellick** [comment]
This issue has a pretty large scope as it is caused by a fundamental design deicision to call the docker socket via proxy and restricted users do  not have acess to that

**Comment by warroyo** [comment]
any update on this issue?

**Comment by deniseschannon** [comment]
Available with Rancher CLI v0.6.9-rc1, please test restricted users ability to view logs as well as exec into containers.

**Comment by JayHaoDing** [comment]
Verified OK with Rancher CLI v0.6.9-rc1, thanks for the work

**Comment by kingsd041** [comment]
@deniseschannon 
CLI v0.6.9-rc1 is available in Windows environments.

**Comment by soumyalj** [comment]
Reproduced the issue with CLI version v0.6.7
Tested with v1.6.17-rc1 using CLI v0.6.9-rc1. Created a restricted user and configured CLI to use the restricted user's keys. Viewing logs and exec into container works with CLI
```
ancher-v0.6.9-rc1 soumya$  ./rancher logs -f Default/testredis
00 2018-04-09T21:50:41.132415533Z 1:C 09 Apr 21:50:41.131 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo

00 2018-04-09T21:50:41.132508460Z 1:C 09 Apr 21:50:41.132 # Redis version=4.0.9, bits=64, commit=00000000, modified=0, pid=1, just started

00 2018-04-09T21:50:41.132717166Z 1:C 09 Apr 21:50:41.132 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf

```

```
rancher-v0.6.9-rc1 soumya$ ./rancher exec -i -t 1s7 bash
http://35.193.248.79:8080/v2-beta/projects/1a5/containers/1i21/?action=execute
root@6942e27f2a03:/# 
```
