### ISSUE TITLE
js error where create my everiment

### ISSUE THREAD

**Issue by askie** [rancher/rancher#8022]
when I "Add Environment" like below:
![image](https://cloud.githubusercontent.com/assets/1140973/23495147/11a566c6-ff52-11e6-92eb-4d543ef249f3.png)
and then click dhf switch to it，
brower location to : http://v1:8080/env/1a15/swarm/console
and console show the below error：
![image](https://cloud.githubusercontent.com/assets/1140973/23494240/8241efae-ff4c-11e6-845b-a95e973798db.png)

the page is blank！

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.4.1` Cattle: `v0.176.9` UI: `v1.4.6` |
|Access|`github` `admin`|
|Orchestration|`Cattle`|
|Route|`stacks.index`|

**Comment by askie** [comment]
only Environment Templates  "Cattle"  can be created and stwich it is ok , others "Mesos","Swarm" could created,but switched to get a blank page just like up screen.

**Comment by HenryTheSir** [comment]
Can you try with English Language? We had with language to german some issues and switched back to english, where our error did not occur.

**Comment by askie** [comment]
with English Language  all are ok!

**Comment by tfiduccia** [comment]
Version - master 3/2 - Verified this is broken in Chinese.

**Comment by tfiduccia** [comment]
Version - v1.5.0-rc5
Verified fixed.  Switching to all types of environments work.
