### ISSUE TITLE
cli random port mapping

### ISSUE THREAD

**Issue by vijayvammi** [rancher/rancher#8023]
Hi,

I am planning to use rancher for managing my containers. On my dev box, we plan to bring up several containers each serving a REST api. 

I am able to automate the process of building up my containers using jenkins and want to run the container using rancher to take advantage of random host port mapping. I am able to do this using rancher UI but unable to find the way to automate it using cli. 

ex: 
Jennkins builds Container_A exposes 8080 -> Jenkins also executes rancher cli to run the container mapping 8080 to a random port of host. And the same for Container_B exposing 8080. 

Hope my question makes sense.
Thanks
Vijay

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
