### ISSUE TITLE
Auth framework should have support for limiting concurrent user sessions

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#8024]
Requirement:

There should be a configuration option for the auth backends that will make it so that there can't be multiple concurrent sessions for a single user account.

**Comment by mrajashree** [comment]
When user tries to login to different browser, to avoid multiple concurrent sessions, delete previous token(jwt) from `auth_token` created for this account. To get the jwt previously created for any user, we need to add a column `external_id` to `auth_token` table. It's value will be same as the `external_id` from `account` table

**Comment by mrajashree** [comment]
Concurrent user sessions should not be allowed. So if a user is already logged in, and is starting another session, the existing token will get deleted. This will limit the user to have only one active session.

**Comment by vincent99** [comment]
Just to be clear; this needs to be **optional** and **not enabled** by default.

**Comment by mrajashree** [comment]
@vincent99  Oh, I was doing it by default, my bad. I'll add a setting that can be configured and if it's set to `True` then only call the delete?

**Comment by vincent99** [comment]
Yes (with a default of false in one of the properties files)

**Comment by cjellick** [comment]
Regarding @prachidamle's upgrade statement. Offline discussion determined that for users who wanted to turn this feature on, they could truncate the auth_token table. We would need to doc that, possibly in the release notes and in emails to specfic users asking for it.

**Comment by galal-hussein** [comment]
Test cases https://github.com/rancher/rancher/issues/8887
@mrajashree in the 5th test case, i can see that the invalid session is logged out automatically after 5 minutes.

**Comment by sangeethah** [comment]
@mrajashree @cjellick , Following are 2 test scenarios for which we need follow up action:

4- Open multiple sessions with the same user and then enable the restriction option in one of the sessions, the other sessions will continue to work normally and you can create resources in them until any new login happens, then the other sessions will have an invalid token.

5- Enable auth.limit.concurrent.sessions . Open one user session and then open another new session for the same user. In the first session you will not be logged out immediately, and you will still see the resources created until one of the following is done:
1.Manual refresh 
2. request a new url 
3. After 5 minutes.

**Comment by deniseschannon** [comment]
When documenting the feature, @mrajashree can you document number 4. Can you make sure to document that after enabling the feature, you'll need to wait 16 hours for all user tokens to expire and then a user will only be able to have a single valid token. 

#8901 addresses number 5.
