### ISSUE TITLE
Cattle Load Balancer Failing: CATTLE_URL is not set, fail to init Rancher LB provider

### ISSUE THREAD

**Issue by jfmyers** [rancher/rancher#8027]
**Rancher Versions:**
Server: 1.4.1

**Docker Version:**
1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):**
 Ubuntu 16.04.1 LTS (4.4.0), AWS
 
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA Rancher, external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Just started happening today for the first time (we've been running on Cattle for about 2 weeks), nothing has changed in out setup. We have two separate environments for prod and staging, it's occurred in both the prod and staging lb's.

The message from Cattle LB:
```
3/2/2017 2:17:30 PMtime="2017-03-02T19:17:30Z" level=info msg="Starting Rancher LB service"
3/2/2017 2:17:30 PMtime="2017-03-02T19:17:30Z" level=fatal msg="CATTLE_URL is not set, fail to init Rancher LB provider"
3/2/2017 2:19:19 PMtime="2017-03-02T19:19:19Z" level=info msg="KUBERNETES_URL is not set, skipping init of kubernetes controller"
3/2/2017 2:19:19 PMtime="2017-03-02T19:19:19Z" level=info msg="CATTLE_URL is not set, skipping init of Rancher LB provider"
3/2/2017 2:19:19 PMtime="2017-03-02T19:19:19Z" level=info msg="Starting Rancher LB service"
3/2/2017 2:19:19 PMtime="2017-03-02T19:19:19Z" level=fatal msg="CATTLE_URL is not set, fail to init Rancher LB provider"
```

**Results:** 
The only way I could get my services back up was to remove them from the environment and re-add them, which is a bit concerning. 

Has anyone else encountered this issue?

**Comment by jfmyers** [comment]
Anyone have any ideas here?

**Comment by alena1108** [comment]
@jfmyers did the error happen on the LB that used to work before? or on the newly created LBs. CATTLE_URL/CATTLE_ACCESS_KEY/CATTLE_SECRET_KEY are the environment variables that get set in the LB container in order for it to communicate with Rancher server. 


The environment variables get set based on the ```io.rancher.container.create_agent``` label that should be internally set on every LB service. If you hit it again, could you check:

1) that the label is set on the service
2) If yes, execute 2 following queries:

```
select id, name, state, agent_id from instance where id=<lb container id>;

select * from agent where id=<agent_id retrieved on the previous step>
```

3) Check what environment variables are present inside the LB container.

I've never seen this error before, so if it happens on your setup, the debug info from above would be really helpful.

**Comment by andyshinn** [comment]
I just ran into this upgrading from a earlier 1.2.x environment to 1.5.1. The LB were old style ones (from 1.1.x) and they did not have `io.rancher.container.create_agent=true` set. I set the label and deleting the old containers and then the new ones were created with the proper environment variables.

**Comment by jurajseffer** [comment]
I just got this during deployment/upgrade of a load balancer on 1.3.0. Removing the load balancer service and creating it again fixed it.

**Comment by huttarichard** [comment]
Same thing here, except we did not upgrade anything. Starts happening from no obvious reason. Re-adding helps. But this issue took our backend down for like 3 hours.

**Comment by superseb** [comment]
@huttarichard What versions (`rancher/server` and `lb-service-haproxy`) are you running?

**Comment by huttarichard** [comment]
we have latest `rancher/server:stable` and `rancher/lb-service-haproxy:v0.6.4`

**Comment by superseb** [comment]
If this happens again, please follow instructions in https://github.com/rancher/rancher/issues/8027#issuecomment-284095542 and file a new issue.

**Comment by kucerarichard** [comment]
if you are here because of the access key "fail" message, in my case it was simply an ergonomic issue (laziness) was due to migrating a stack to test using the docker-compose.yml but NOT the rancher-compose.yml.     You need both.   Copy/paste both,  then load balancer comes up.
