### ISSUE TITLE
Hitting refresh button with bad catalog makes button change and throws 404 in console

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#8031]
**Rancher Versions:** v1.5.0-rc4

**Steps to Reproduce:**
1.  Go to settings and add a catalog with a bad url
2.  Go to All catalog page and hit the refresh button in upper right.

**Results:** Console throws error - POST http://35.184.114.100:8080/v1-catalog/templates?refresh&action=refresh 400 (Bad Request) and the button turns into a triangle ! icon.

**comment:** Not sure if this is actually a bug, but it's shows different behavior than 1.4.1 used to show.

**Comment by amy** [comment]
Here, we should display an error about an incorrect URL.
