### ISSUE TITLE
ip address for container is in cidr notation if using a cni ipam plugin other than rancher

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#8034]
**Steps to Reproduce:**
I dont know if there a realistic steps to reproduce. You would have to have a CNI based network setup that _does_ use our network-manager stack but uses a different IPAM plugin.

If you can get that setup, the IP displayed in the UI for containers will be in cidr notation like `192.168.207.100/24`. The /24 shouldn't be there.

**Comment by cjellick** [comment]
The associated code change for this has been in since v1.5.4.
There is no practical way to test the functionality change at the moment, but when we eventually test DHCP based IPAM (for rancher-vm), we could verify it then. The important thing right now would just be to verify that this didnt introduce any regressions. Given that the code change has been in since v1.5.4, I think we've proven that.

**Comment by sangeethah** [comment]
Will validate this issue using rancher-vm deployments.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
