### ISSUE TITLE
Rolling back kubernetes stack update failed when upgrading from 1.4.1 to 1.50 with required isolation plane

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#8035]
**Rancher Versions:**
Server: v1.5.0-rc4

**Docker Version:**
1.12
**OS and where are the hosts located? (cloud, bare metal, etc):**
ROS 0.8
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes
**Steps to Reproduce:**
- On rancher 1.4.1 install kubernetes on 3 nodes
- Deploy some containers
- Add 3 more hosts
- upgrade Rancher to 1.5.0-rc4
- Add etcd, orchestration, compute labels on the hosts, make sure to add etcd=true label on at leas 3 hosts where one of them had already etcd container
- upgrade kubernetes and set plane isolation to required.

The upgrade failed due to stale data from previous etcd containers.

- Rollback to the previous kubernetes version.

**Results:** 

The rollback stuck forever.

**Comment by LLParse** [comment]
I think this is a more generic problem with the rollback feature in Rancher. I have not once seen it function correctly in a failure scenario - it usually gets stuck waiting for the upgraded containers to stabilize, which will never happen (hence the need for rollback).

**Comment by superseb** [comment]
Closing as stale.
