### ISSUE TITLE
Etcd breaks when scheduled on different hosts during upgrade to a required isolation plane

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#8036]
**Rancher Versions:**
Server: v1.5.0-rc4

**Steps to Reproduce:**
- On 1.4.1 install kubernetes on 3 agents
- Deploy few rcs/services
- Add 3 more hosts
- Upgrade Rancher from 1.4.1 to 1.5.0-rc4
- Add labels on hosts, make sure to add one etcd label on one of the old 3 hosts and the other two on the new hosts, make sure also to add orchestration and compute labels.
- Upgrade kubernetes and set isolation plane to required.

**Results:** 

The etcd breaks quorum and the etcd containers starts to throw 503 error
```
3/3/2017 3:24:18 AM
3/3/2017 3:24:33 AMHTTP 503
3/3/2017 3:24:33 AM
3/3/2017 3:24:48 AMHTTP 503
3/3/2017 3:24:48 AM
3/3/2017 3:25:03 AMHTTP 503
3/3/2017 3:25:03 AM
3/3/2017 3:25:18 AMHTTP 503
3/3/2017 3:25:18 AM
3/3/2017 3:25:33 AMHTTP 503
```

**Comment by deniseschannon** [comment]
In our docs and readme for k8s, we have noted that when upgrading from an existing install, the `etcd=true` labels are required to be on the hosts with those services.
