### ISSUE TITLE
How to configure the load balancer haproxy

### ISSUE THREAD

**Issue by mariadb-Emrys** [rancher/rancher#8037]
system:ubuntu16.04
rancher:1.1.4

setup
1、setup haproxy
global
        maxconn 4096
        maxpipes 1024
        uid 99
        gid 99
        daemon
	log 127.0.0.1 local3 info
	tune.ssl.default-dh-param 2048
        ssl-default-bind-options no-sslv3 no-tlsv10

defaults
        log     global
        mode    http 
        option  tcplog
        option  dontlognull
        option  redispatch
        option http-server-close
        retries 3
        timeout connect 5000
        timeout client 50000
        timeout server 50000
	option forwardfor
	option httpclose

frontend rancher_80_frontend
    bind *:80
    mode   http
    default_backend rancher_80_backend

frontend rancher_443_frontend
    bind *:443 
    mode  tcp
    default_backend rancher_443_backend

frontend rancher_18080_frontend
    bind *:18080
    mode  http 

    default_backend rancher_18080_backend

backend rancher_80_backend
        mode http
	option forwardfor header X-Forwarded-For
        server rancher_01 10.28.4.101:80
        server rancher_02 10.28.4.102:80
        server rancher_03 10.28.4.103:80

backend rancher_443_backend
        mode tcp 
        server rancher_01 10.28.4.101:443   check
        server rancher_02 10.28.4.102:443  check
        server rancher_03 10.28.4.103:443  check 

backend rancher_18080_backend
	mode http 
        timeout check 1000
        option httpchk GET /ping HTTP/1.0
        server rancher_01 10.28.4.101:18080 check port 18080 inter 1000 rise 1 fall 2
        server rancher_02 10.28.4.102:18080 check port 18080 inter 1000 rise 1 fall 2
        server rancher_03 10.28.4.103:18080 check port 18080 inter 1000 rise 1 fall 2
2、sudo docker run -d --restart=always -p 8080:8080 \
-e CATTLE_DB_CATTLE_MYSQL_HOST="10.28.4.101" \
-e CATTLE_DB_CATTLE_MYSQL_PORT=3306 \
-e CATTLE_DB_CATTLE_MYSQL_NAME="cattle" \
-e CATTLE_DB_CATTLE_USERNAME="cattle" \
-e CATTLE_DB_CATTLE_PASSWORD="cattle" \
rancher/server:v1.1.4
3、setup HA,
4、shutdown node1
5、exec rancher-ha.sh    every one node

![1](https://cloud.githubusercontent.com/assets/4919916/23540149/8e4ea8d6-001a-11e7-86ec-ba6e7ea19521.jpg)
![2](https://cloud.githubusercontent.com/assets/4919916/23540204/d7d778a2-001a-11e7-8cd5-703aa390ec53.jpg)

question：
![w1](https://cloud.githubusercontent.com/assets/4919916/23540212/e158784a-001a-11e7-940d-55fab19aec0a.jpg)

![w2](https://cloud.githubusercontent.com/assets/4919916/23540218/e9bb4760-001a-11e7-8cb0-ba0b87b59c9a.jpg)

2、
sudo docker run -d --privileged -e CA_FINGERPRINT="37:3A:17:D1:C7:E1:EA:31:B7:B1:3D:3C:EF:29:98:A6:F5:AB:A9:97" -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.0.2 https://xx.beecloud.com/v1/scripts/7981D8DC5F2947C5125A:1488520800000:s2jzxKj3Ye1GjVfTd3CkQVe6HFs

mkdir /var/lib/rancher/etc/ssl/ -p
chmod 400 ca.crt   

![w2-1](https://cloud.githubusercontent.com/assets/4919916/23540304/6d9263b6-001b-11e7-892a-62a7f0a67281.jpg)

![w2-2](https://cloud.githubusercontent.com/assets/4919916/23540342/a869e63a-001b-11e7-8961-379403a4e504.jpg)
10.28.4.104 ——>haproxy IP
10.28.4.104 ——>haproxy IP
![w2-3](https://cloud.githubusercontent.com/assets/4919916/23540335/a26e7ef8-001b-11e7-968b-20fb0220e5c0.jpg)

**Comment by mariadb-Emrys** [comment]
![w2-4](https://cloud.githubusercontent.com/assets/4919916/23541033/bd5a5350-001f-11e7-9620-079a9f61930d.jpg)

10.28.4.104 ——>haproxy IP

**Comment by kaos** [comment]
@mariadb-Emrys sorry, but what is your question?

**Comment by aemneina** [comment]
You might need to specify CATTLE_AGENT_IP when registering your hosts, so they get the right IP. It also looks like potential websocket issue at your load balancer that fronts rancher.

**Comment by loganhz** [comment]
Can you try https://github.com/rancher/rancher/issues/8037#issuecomment-303852403, please?

Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
