### ISSUE TITLE
Kubelet can not access rancher-metadata sometimes

### ISSUE THREAD

**Issue by niusmallnan** [rancher/rancher#8038]
I have two k8s node, one is on AWS, the other is on Azure.  The OS are both ubuntu server 16.04 LTS.

AWS is ok, but kubelet in the node of Azure can not work fine.
```
2/3/2017 18:29:39+ curl -s -f http://rancher-metadata/2015-12-19/stacks/Kubernetes/services/kubernetes/uuid
2/3/2017 18:29:39Waiting for metadata
2/3/2017 18:29:39+ echo Waiting for metadata
2/3/2017 18:29:39+ sleep 1
2/3/2017 18:29:40+ curl -s -f http://rancher-metadata/2015-12-19/stacks/Kubernetes/services/kubernetes/uuid
2/3/2017 18:29:40Waiting for metadata
```

Try to ping rancher-metadata, get unknown host error. But dig/nslookup can work fine.
```
root@a:/# dig rancher-metadata

; <<>> DiG 9.9.5-9+deb8u10-Debian <<>> rancher-metadata
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 32129
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;rancher-metadata.		IN	A

;; ANSWER SECTION:
rancher-metadata.	600	IN	A	169.254.169.250

;; Query time: 0 msec
;; SERVER: 169.254.169.250#53(169.254.169.250)
;; WHEN: Fri Mar 03 06:43:52 UTC 2017
;; MSG SIZE  rcvd: 50

root@a:/# ping rancher-metadata
ping: unknown host
```

Try to use strace(strace ping rancher-metadata -c 1) to diagnose it. I find the answer.
the node on Azure:
![image](https://cloud.githubusercontent.com/assets/998984/23541126/67387852-0020-11e7-83e3-6e7950c62ccb.png)

the node on AWS:
![image](https://cloud.githubusercontent.com/assets/998984/23541132/7283b64a-0020-11e7-9695-5f68b2f9c201.png)

If we use dig/nslookup, system will use dns resolve first.  If we use ping, I think the system process is as follows(the nscd has been installed in OS).
ping--->nss--->nscd(cache)--->dns resolve

So we should know the essential reason. Try to uninstall nscd(the node on Azure), kubelet should work fine.

But why container kubelet  has the nscd socket(/var/run/nscd/socket), I think it is just because kubelet mount the host dir /var/run.
![image](https://cloud.githubusercontent.com/assets/998984/23541396/19fd4250-0022-11e7-91a6-949ed7839518.png)

So we have a second solution, we can umout /var/run/nscd/socket and remove it. I will submit a PR to fix it. After all, many people want to keep nscd in  their OS.

**Comment by niusmallnan** [comment]
Add more information about nscd. 

If you can disable nscd hosts cache via nscd.conf:

![image](https://cloud.githubusercontent.com/assets/998984/23542446/19d012de-0028-11e7-9c6e-5a43e4715529.png)

If you do this, kubelet can also work fine.

**Comment by janeczku** [comment]
@niusmallnan What are the contents of `/etc/resolv.conf` and `/etc/nsswitch.conf`?

**Comment by niusmallnan** [comment]
@janeczku
You mean the kubelet container?

`/etc/resolv.conf`
```
root@ip-172-31-1-132:/# cat /etc/resolv.conf
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
# nameserver 172.31.0.2
search cn-north-1.compute.internal kubelet.kubernetes.rancher.internal kubernetes.rancher.internal rancher.internal
nameserver 169.254.169.250
```

`/etc/nsswitch.conf`
```
# /etc/nsswitch.conf
#
# Example configuration of GNU Name Service Switch functionality.
# If you have the `glibc-doc-reference' and `info' packages installed, try:
# `info libc "Name Service Switch"' for information about this file.

passwd:         compat
group:          compat
shadow:         compat
gshadow:        files

hosts:          files dns
networks:       files

protocols:      db files
services:       db files
ethers:         db files
rpc:            db files

netgroup:       nis
```

**Comment by galal-hussein** [comment]
Rancher version: v1.5.2-rc2
Kubernetes version: 1.5.4

The nscd with kubernetes is still failing, the kubelet isn't starting correctly after installing nscd on the host, i think kubelet is trying to call rancher-metadata before the nscd masking happens.

```
3/21/2017 1:03:57 AM+ curl -s -f http://rancher-metadata/2015-12-19/stacks/Kubernetes/services/kubernetes/uuid
3/21/2017 1:03:57 AMWaiting for metadata
3/21/2017 1:03:57 AM+ echo Waiting for metadata
3/21/2017 1:03:57 AM+ sleep 1
3/21/2017 1:03:58 AM+ curl -s -f http://rancher-metadata/2015-12-19/stacks/Kubernetes/services/kubernetes/uuid
3/21/2017 1:03:58 AMWaiting for metadata
3/21/2017 1:03:58 AM+ echo Waiting for metadata
3/21/2017 1:03:58 AM+ sleep 1
3/21/2017 1:03:59 AM+ curl -s -f http://rancher-metadata/2015-12-19/stacks/Kubernetes/services/kubernetes/uuid
3/21/2017 1:03:59 AM+ echo Waiting for metadata
3/21/2017 1:03:59 AMWaiting for metadata
3/21/2017 1:03:59 AM+ sleep 1
```

**Comment by ibuildthecloud** [comment]
https://github.com/rancher/kubernetes-package/pull/34/files

**Comment by deniseschannon** [comment]
k8s image: `rancher/k8s:v1.5.4-rancher1-1`

**Comment by galal-hussein** [comment]
Rancher version: 1.5.2-rc2
k8s version: rancher/k8s:v1.5.4-rancher1-3

Steps:

- Install nscd on a host
- Register this host to Rancher
- Install kubernetes stack

I was able to ping rancher-metadata from inside kubelet, and i was able to verify that the masking for /var/run/nscd has taken place:

```
root@hgalal-nscd-01:/# ping rancher-metadata
PING rancher-metadata.rancher.internal (169.254.169.250): 56 data bytes
64 bytes from 169.254.169.250: icmp_seq=0 ttl=64 time=0.179 ms
64 bytes from 169.254.169.250: icmp_seq=1 ttl=64 time=0.091 ms

root@hgalal-nscd-01:/# mount | grep nscd
/dev/mapper/docker-253:1-258819-c784385fe099f5b77f41de0e7026c15157dd347d29d9e415
ed7b829130e49cec on /run/nscd type xfs (rw,relatime,nouuid,attr2,inode64,logbsiz
e=64k,sunit=128,swidth=128,noquota)

root@hgalal-nscd-01:/# ls /var/run/nscd/
root@hgalal-nscd-01:/#
```
