### ISSUE TITLE
external-dns is not aware of scheduler ips

### ISSUE THREAD

**Issue by ffaraone** [rancher/rancher#8039]
**Rancher Versions:**
Server: 1.4.0
healthcheck:
ipsec:
network-services:
scheduler:
external-dns: 0.6.2
kubernetes (if applicable):

**Docker Version:**
1.12.3
**OS and where are the hosts located? (cloud, bare metal, etc):**

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**

**Results:** 

It seems that the external-dns service update the route53 hosted zone always with the agent ip and not with the ip that the scheduler assign to the service in a multi-ip setup.

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
