### ISSUE TITLE
New Hosts aren't appearing in Rancher

### ISSUE THREAD

**Issue by wrsuarez** [rancher/rancher#8042]
I've created 3 CentOs7 machines with Docker installed. The agent docker command has been run on them but they do not appear in Rancher. I'm seeing an error in the Docker logs about WebSockets not working but I've set up the ELB policy for this load balancer as described in the documentation:

{
    "PolicyDescriptions": [
        {
            "PolicyAttributeDescriptions": [
                {
                    "AttributeName": "ProxyProtocol", 
                    "AttributeValue": "true"
                }
            ], 
            "PolicyName": "rancher-dev-elb-policy", 
            "PolicyTypeName": "ProxyProtocolPolicyType"
        }
    ]
}

Here's the docker logs:

INFO: Downloading http://redacted/v1//configcontent//host-config current=host-config-1-6d1e996b0dd5b4ca6ff6145b7d222ecf1d9b00df19f4db64f3e4a16a1f2c075b
INFO: Already up to date
INFO: Sending host-config applied 1-6d1e996b0dd5b4ca6ff6145b7d222ecf1d9b00df19f4db64f3e4a16a1f2c075b
time="2017-03-03T18:18:05Z" level=info msg="Launching agent" 
time="2017-03-03T18:18:05Z" level=info msg="http://redacted/v1ECB12B21331605B9A62CGYe9So2a5o7SQtRoxRYUyd86BMDrNMPLQkzdWUd8" 
time="2017-03-03T18:18:05Z" level=info msg="Listening for events on http://redacted/v1" 
time="2017-03-03T18:18:05Z" level=info msg="launching hostapi" 
time="2017-03-03T18:18:05Z" level=info msg="Starting event router." 
time="2017-03-03T18:18:05Z" level=info msg="Initializing event router" workerCount=50 
time="2017-03-03T18:18:05Z" level=error msg="invalid character 'c' looking for beginning of value" 
time="2017-03-03T18:18:05Z" level=error msg="Error subscribing to events: websocket: bad handshake" subscribeUrl="ws://redacted/v1/subscribe?eventNames=compute.instance.pull&eventNames=storage.volume.activate&eventNames=storage.volume.remove&eventNames=ping&eventNames=config.update&eventNames=compute.instance.activate&eventNames=compute.instance.deactivate&eventNames=compute.instance.force.stop&eventNames=compute.instance.inspect&eventNames=compute.instance.remove&eventNames=storage.image.activate" 
time="2017-03-03T18:18:05Z" level=error msg="Got error response" responseHeaders=map[X-Api-Schemas:[http://redacted/v1/schemas] X-Api-User-Id:[1a12] X-Rancher-Version:[v1.4.1] Content-Type:[application/json; charset=utf-8] Date:[Fri, 03 Mar 2017 18:18:05 GMT] Expires:[Thu, 01 Jan 1970 00:00:00 GMT] Server:[Jetty(9.2.11.v20150529)] X-Api-Account-Id:[1a12] Content-Length:[1236] Connection:[keep-alive] Set-Cookie:[PL=rancher;Path=/] Vary:[Accept-Encoding, User-Agent] X-Api-Client-Ip:[10.151.4.69]] status="200 OK" statusCode=200 
time="2017-03-03T18:18:05Z" level=error msg="Error response: {\"type\":\"collection\",\"resourceType\":\"subscribe\",\"links\":{\"self\":\"http:\\/\\/redacted\\/v1\\/subscribe\"},\"createTypes\":{},\"actions\":{},\"data\":[],\"sortLinks\":{\"eventNames\":\"http:\\/\\/redacted\\/v1\\/subscribe?eventNames=compute.instance.pull&eventNames=storage.volume.activate&eventNames=storage.volume.remove&eventNames=ping&eventNames=config.update&eventNames=compute.instance.activate&eventNames=compute.instance.deactivate&eventNames=compute.instance.force.stop&eventNames=compute.instance.inspect&eventNames=compute.instance.remove&eventNames=storage.image.activate&sort=eventNames\"},\"pagination\":null,\"sort\":null,\"filters\":{\"eventNames\":[{\"modifier\":\"eq\",\"value\":\"compute.instance.pull\"},{\"modifier\":\"eq\",\"value\":\"storage.volume.activate\"},{\"modifier\":\"eq\",\"value\":\"storage.volume.remove\"},{\"modifier\":\"eq\",\"value\":\"ping\"},{\"modifier\":\"eq\",\"value\":\"config.update\"},{\"modifier\":\"eq\",\"value\":\"compute.instance.activate\"},{\"modifier\":\"eq\",\"value\":\"compute.instance.deactivate\"},{\"modifier\":\"eq\",\"valu" 
time="2017-03-03T18:18:05Z" level=fatal msg="Exiting. Error: websocket: bad handshake" 
INFO: Starting agent for ECB12B21331605B9A62C
INFO: Access Key: ECB12B21331605B9A62C
INFO: Config URL: http://redacted/v1
INFO: Storage URL: http://redacted/v1
INFO: API URL: http://redacted/v1
INFO: IP: 10.151.4.69
INFO: Port:
INFO: Required Image: rancher/agent:v1.2.0
INFO: Current Image: rancher/agent:v1.2.0
INFO: Using image rancher/agent:v1.2.0
INFO: Downloading agent http://redacted/v1/configcontent/configscripts
INFO: Updating configscripts
INFO: Downloading http://redacted/v1//configcontent//configscripts current=
INFO: Running /var/lib/cattle/download/configscripts/configscripts-1-f0f3fb2e1110b5ada7c441705981f93a480313a324294321cff467f0c3e12319/apply.sh
INFO: Sending configscripts applied 1-f0f3fb2e1110b5ada7c441705981f93a480313a324294321cff467f0c3e12319
INFO: Updating pyagent
INFO: Downloading http://redacted/v1//configcontent//pyagent current=
INFO: Running /var/lib/cattle/download/pyagent/pyagent-1-9e3dcab12585149a65d818082279708965cd826df1937a55b24f48428f8f0c0644fc1033b5be15c88dcf9540b1c04c67/apply.sh
INFO: Updating host-api
INFO: Downloading http://redacted/v1//configcontent//host-api current=1-9608ead804f8cebbfe95b9f114701d8a5ac4244d603d196068043c902b1a0bdf
INFO: Already up to date
INFO: Sending host-api applied 1-9608ead804f8cebbfe95b9f114701d8a5ac4244d603d196068043c902b1a0bdf
INFO: Updating python-agent
INFO: Downloading http://redacted/v1//configcontent//python-agent current=1-936086fb3866b781d82a97bdc0832430463ab8b2b33bfbeafd5ecf60d50d0766
INFO: Already up to date
INFO: Sending python-agent applied 1-936086fb3866b781d82a97bdc0832430463ab8b2b33bfbeafd5ecf60d50d0766
INFO: Sending pyagent applied 1-9e3dcab12585149a65d818082279708965cd826df1937a55b24f48428f8f0c0644fc1033b5be15c88dcf9540b1c04c67
INFO: Starting agent /var/lib/cattle/pyagent/apply.sh
INFO: Executing /var/lib/cattle/pyagent/agent
INFO: Updating host-config
INFO: Downloading http://redacted/v1//configcontent//host-config current=host-config-1-6d1e996b0dd5b4ca6ff6145b7d222ecf1d9b00df19f4db64f3e4a16a1f2c075b
INFO: Already up to date
INFO: Sending host-config applied 1-6d1e996b0dd5b4ca6ff6145b7d222ecf1d9b00df19f4db64f3e4a16a1f2c075b
time="2017-03-03T18:18:48Z" level=info msg="Launching agent" 
time="2017-03-03T18:18:48Z" level=info msg="http://redacted/v1ECB12B21331605B9A62CGYe9So2a5o7SQtRoxRYUyd86BMDrNMPLQkzdWUd8" 
time="2017-03-03T18:18:48Z" level=info msg="Listening for events on http://redacted/v1" 
time="2017-03-03T18:18:48Z" level=info msg="launching hostapi" 

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.4.1` Cattle: `v0.176.9` UI: `v1.4.6` |
|Access|`Disabled`|
|Orchestration|`Cattle`|
|Route|`authenticated.project.help`|

**Comment by aemneina** [comment]
@wrsuarez I see you enabled proxy protocol, did you define the port the rancher server listens on, for the proxy protocol?


when describing the ELB you should see something like:
```
            "BackendServerDescriptions": [
                {
                    "InstancePort": 8080,
                    "PolicyNames": [
                        "EnableProxyProtocol"
                    ]
                }
            ],
```

The command is outlined [here](https://docs.rancher.com/rancher/v1.4/en/installing-rancher/installing-server/basic-ssl-config/#configuration-requirements-for-elastic-load-balancer-elb)

**Comment by superseb** [comment]
Did this work @wrsuarez ? Let us know if you need any more help!
