### ISSUE TITLE
Automate K8s Ingress test cases relating to global , host affinity and service selector updates.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#8044]
Automate K8s Ingress test cases relating to following features:

https://github.com/rancher/rancher/issues/7517 
https://github.com/rancher/rancher/issues/5240 
https://github.com/rancher/rancher/issues/8010

**Comment by soumyalj** [comment]
Automated the tests. https://github.com/rancher/validation-tests/pull/310
