### ISSUE TITLE
After upgrade, environments with no hosts will have an hour delay before automatically upgrading network-services

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#8047]
**Rancher Versions:**
Server: v1.5.0

Upgrading `network-services` is required for v1.5.0. An upgrade manager was introduced to automatically upgrade the `network-services` infrastructure stack. 

But if you have environments with no hosts, after adding a host, it takes an hour before the stack is automatically upgrade.

Workaround: If you have an environment with no hosts, before or immediately after adding hosts, make sure to upgrade your `network-services` stack.

**Comment by soumyalj** [comment]
Tested with upgrade from v1.4.2 to v1.5.2-rc2 with no hosts in the environment. Network services stack got upgraded automatically to the latest version after rancher upgrade. After adding a host to the environment, network manager and metadata containers on the host had the latest version.
