### ISSUE TITLE
Automatic upgrade not done for  network-services stack for envrionments that have one of the host in "disconnected" state.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#8048]
Rancher Versions: v1.4.1 upgraded to v1.5.0
Steps to reproduce the problem:
Fresh install of v1.4.1 with 2 hosts.
power down one of the host and wait for it to go to "Disconnected" state.
Upgrade to 1.5.0

After upgrade, network-services does not get upgraded automatically.
It continues to be in v0.0.16 with "upgrade available" option presented to the user.

Expected behavior:
After upgrade, network-services should get upgraded automatically.

Even after the host that was powered down was powered on , this did not trigger network-service upgrade.

There was a service upgrade that was done much later.
What triggers this service upgrade ? Is there a check for service upgrade that happens on a regular basis?

**Comment by soumyalj** [comment]
Tested with upgrade from v1.4.2 to v1.5.2-rc2 with one of the hosts in disconnected state. Network services stack got upgraded automatically to the latest version. After powering ON the host, the network manager and metadata containers on the host had the latest version.
