### ISSUE TITLE
Stacks UI hung if I add a service with an 1.1.x catalog format.

### ISSUE THREAD

**Issue by bitninjaio** [rancher/rancher#8050]
I had a 1.1.* version on my local dev environment on a vagrant machine with ubuntu 16. I tried to upgrade it to the latest stable. After the upgrade for some reason the /apps/stacks interface didn't show up anymore. I thought I screwed up something with the upgrade, so I created a fresh rancher install with a brand new vagrant box. After the setup I started a stack from our self made cataloge, and the same issue happened. Once again the /apps/stacks became unavailable. Everything else works just fine. I believed, it is probably a bug in the latest stable, so I downgraded to 1.4.0, but the same issue remain. Any idea on how to debug this issue?

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.4.0` Cattle: `v0.176.8` UI: `v1.4.6` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`containers.index`|

**Comment by bitninjaio** [comment]
I think the problem was that I tried to use an older catalog format to bring up my stacks. 
So I have to first convert the services from 1.1.x to 1.2.x and create the new catalog files. 

Is there any other differences in the catalog rancher-compose and docker-compse ymls than this this?
version: '2'
services:

Is there any easy way to convert from 1.1.x format to 1.2.x+ or I must actually do the conversion?

**Comment by bitninjaio** [comment]
But it would be nice if the UI could handle this situation somehow a bit better, or simply deny the use of older template formats, as currently the UI hungs if I try to add a stack using an 1.1.x format catalog, and I don't even know how to recover from that state. It recovers if I delete the stack, but I can't delete the stack if I close the original browser window where I created it.

**Comment by deniseschannon** [comment]
Can you share your catalog tempalte (docker-compose.yml and rancher-compose.yml)? You shouldn't need to put it in `v2` format.

**Comment by bitninjaio** [comment]
Uploaded the catalog template files.

[test-stack.zip](https://github.com/rancher/rancher/files/820932/test-stack.zip)

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
