### ISSUE TITLE
intermittent hostname lookup failures

### ISSUE THREAD

**Issue by kkvilekval** [rancher/rancher#8052]
**Rancher Versions:**
Server: 1.4.1
healthcheck: 0.2.3
ipsec:holder/0.8.7
network-services:metatdata 0.7.2 and manager 0.4.5
scheduler: 0.6.3
kubernetes (if applicable):

**Docker Version:**
1.13.1
**OS and where are the hosts located? (cloud, bare metal, etc):**
ubuntu 16.04 baremetal
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
cattle

**Steps to Reproduce:**
I have an external postgres database at bisque-db.cyverse.org.   99% of the time I have no issue connecting to the database .. however, our services will suddenly get 100-500 requests which fail with following message "could not translate host name "bisque-db" to address: No address associated with hostname"  .   Eventually it corrects itself, but our services our definitely not available for 2 to 3 minutes.

**Results:**

**Comment by ptempier** [comment]
try to have a look at your logs and see if you get Failed to generate answers: in the metadata container, and if the answer.jsonb file is empty in the dns container.

your issue may look like https://github.com/rancher/rancher/issues/9894  and

https://github.com/rancher/rancher/issues/10632

**Comment by superseb** [comment]
Let me know if you can't relate to either of those issues @kkvilekval
