### ISSUE TITLE
TCP Sockets don't close on service upgrades

### ISSUE THREAD

**Issue by siosphere** [rancher/rancher#8053]
**Rancher Versions:**
Server: 1.4.1
healthcheck: 0.2.3
ipsec: 0.0.4
network-services: 0.0.16
scheduler: 0.4.0
kubernetes (if applicable):

**Docker Version:** 
1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04.1 LTS AWS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher, external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Create a rabbitmq service (can use from catalog, or plain rabbitmq docker image), make sure it has the rabbitmqctl so you can view queue/consumer details.

Create a service that has python with pip (used to install pika to communicate with rabbitmq), you can execute shell and install the tools needed: (for example, using centos:7)
```
yum install -y python python-pip && \
pip install pika && \
curl -o send.py https://gist.githubusercontent.com/siosphere/c981416100f974cc97b4f69edbebf12b/raw/0908cc3a56ee377e69414fb721c5c0252d7ed580/send.py
curl -o receive.py https://gist.githubusercontent.com/siosphere/86987d2933e3842db6a6da0418c1cdee/raw/0269a5586ce8ff1c8ae147068e4a6d8583017214/receive.py
```
You can run the send script, and verify the queue is created, with 0 consumers:
```
python send.py
```
```
rabbitmqctl list_queues name consumers
# hello   0
```
Run the receive script, and you can now see there is 1 listening consumer:
```
hello   1
```
Kill the receive script with CTRL + C, and you'll see the consumer properly removed from rabbitmq, listing it shows once again, 0 consumers.

Now, leave the consumer running (python receive.py), close the shell (the command will still be running), verify that you still have 1 consumer, and then upgrade the image (this happens both in the WebUI and via rancher-compose), after the upgrade has taken place, and the old container is stopped, running rabbitmqctl to view the consumers still shows 1 consumer attached to the queue. 

Hitting finish upgrade, which completely removes the container, and you will still see 1 consumer attached to the queue.

This is caused because RabbitMQ still believes the socket is open, as it isn't being terminated properly.

**Results:** 
This happens in Python and PHP that I've tested. It does not happen when run locally using straight docker (and killing/restarting the container).

I can get around it now by doing heartbeats in the code, however I feel that other applications, not just rabbitmq will be affected.

**Comment by garnold54** [comment]
We are seeing this issue with our application when deployed with Rancher. We have a model where we have workers that connect to a core through a TCP socket. If we scale the workers down, the containers get stopped, but our core still sees them as connected because the socket doesn't get closed. Similarly, if a host that had workers on it goes down, the core still sees the workers that were on that host as connected, even though they are not running.

When I launch the same stack using Docker Swarm, I can scale up and down and remove hosts and the sockets are disconnected when the container goes down. Same if I run it on one host just with the docker bridge network.

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
