### ISSUE TITLE
network policy: a linked service can not reach the linking service

### ISSUE THREAD

**Issue by derDieDasJojo** [rancher/rancher#8054]
**Rancher Versions:**
Server: 1.5

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
1) Configure Network Policy: Allow between linked containers, allow within service, allow within Stack, Deny Everything Else
2) Start Service 1 in Stack A
3) Start Service 2 in Stack B (linked to Service 1 in Stack A)
4) ping from Service 2 in Stack B to Service 1 in Stack A: service is reachable
5) ping from Service 1 in Stack A to Service 2 in Stack B: **service is not reachable**

**Results:** 
pinging back from a linked service to a linking one is not possible. Is this the desired design ?

**Use Case**
I have a usecase where all incoming traffic is reaching Service 1 in Stack A.
Service 1 in Stack A is supposed to redirect the traffice to different Services in different Stacks.
But at startup time of Service 1 in Stack A does not know to wich services it has to forward.
Because linking happens at startup time it is not possible to use it.

**Proposal**
Linked services should be able to start communication in both directions (with the Network Policy: Allow between linked containers )

**Comment by deniseschannon** [comment]
Correct, this is design. 

Service 1 is linked to Service 2, so only service 1 can communicate to service 2. If you want communication both ways, then you would need to link service 2 to service 1. 

http://docs.rancher.com/rancher/v1.5/en/rancher-services/network-policy/#containers-of-services-that-are-linked
