### ISSUE TITLE
Error if unauthenticated user is in Rancher when admin turns on Authentication

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#806]
v0.20.1
Steps:
1.  Rancher Access Control is not configured (unauthenticated)
2.  In Chrome log in as you
3.  In Firefox log in as rancherdev
4.  In Chrome Authenticate with GitHub
5.  In Firefox click on Containers to go to containers list page

Results:  I get an error page
![image](https://cloud.githubusercontent.com/assets/11514927/7642216/2fe0b0e2-fa44-11e4-9efe-98abb03cafc1.png)

Expected:  Should take me back to the login page without having to see Error page

**Comment by vincent99** [comment]
I guess it can just go to logout in this case even though it thinks access control is disables...

**Comment by tfiduccia** [comment]
No longer errors.  Separate bug #4049 for waiting screen not resolving
