### ISSUE TITLE
Container started via Docker CLI has DNAT 'anywhere' rules applied

### ISSUE THREAD

**Issue by bradjones1** [rancher/rancher#8060]
**Rancher Versions:**
Server: 1.4.1
healthcheck: 0.2.3
ipsec: holder/0.8.7
network-services: rancher/metadata:v0.7.3, rancher/network-manager:v0.4.5
scheduler: 0.6.3

**Docker Version:**
```
Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:42:29 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**OS and where are the hosts located? (cloud, bare metal, etc):**

Ubuntu 14.04.5 - Bare metal

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

Single node rancher, external dB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

Cattle

**Steps to Reproduce:**

Start a container via the Docker CLI with an exposed port and also requesting an IP on the Rancher managed network. E.g.:

`docker run -d -p 1.2.3.4:3306:3306 --label io.rancher.container.network=true mysql`

The expected result would be the container gets placed on the managed Rancher network and has Docker publish port `3336` on IP `1.2.3.4`. Docker publishes the port as expected, however Rancher adds a DNAT prerouting rule from "anywhere," resulting in the port being accessible on any IP on the machine. The expected result is that the port would be accessible at the Rancher managed IP, but only on `1.2.3.4` on the host machine.

**Results:**
```
Chain DOCKER (2 references)
target     prot opt source               destination         
RETURN     all  --  anywhere             anywhere            
DNAT       tcp  --  anywhere             1.2.3.4              tcp dpt:mysql to:172.17.0.4:3306
```
```
Chain CATTLE_PREROUTING (1 references)
MARK       tcp  --  anywhere             anywhere             tcp dpt:mysql MARK set 0x1068
DNAT       tcp  --  anywhere             anywhere             tcp dpt:mysql to:10.42.206.253:3306
DNAT       tcp  --  anywhere             anywhere             tcp dpt:mysql ADDRTYPE match dst-type LOCAL to:10.42.206.253:3306
```

**Comment by bradjones1** [comment]
I would also note the ipsec service has the same consideration?

**Comment by bradjones1** [comment]
@leodotcloud Possibly related to https://github.com/rancher/rancher/issues/4324 ?

**Comment by leodotcloud** [comment]
@bradjones1 I don't think it's related to 4324. That's a different issue.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
