### ISSUE TITLE
Setup Notifications (Slack, Email) in Rancher

### ISSUE THREAD

**Issue by borntorock** [rancher/rancher#8061]
Feature Request, as present in Docker Cloud. 

We must have the notifications section in Rancher, mainly Slack, Email and others for the deployment of containers, health check of containers, or on nodes.

**Comment by egobude** [comment]
Notifications in Mattermost would be cool too :)

**Comment by ket4yii** [comment]
I've been waiting for this feature so long and thought about to implement this as an external service by myself.

**Comment by superseb** [comment]
Please upvote https://github.com/rancher/rancher/issues/52, closing as duplicate. Please respond if you don't agree.
