### ISSUE TITLE
[1.5.0] Community Catalog refresh failed

### ISSUE THREAD

**Issue by JeanDaniel-Fischer** [rancher/rancher#8064]
**Rancher Versions:**
Server: 1.5.0
healthcheck: 0.2.3
ipsec: 0.0.5
network-services: 0.1.0
scheduler: 0.5.0
kubernetes (if applicable): no

**Docker Version:**
1.12.1 (version that contains rancher server and mysql) / 1.13.0 / 1.13.1 / 17.03.0-ce

**OS and where are the hosts located? (cloud, bare metal, etc):**
Linux machines (debian)

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle and Swarm (2 differents environments)

**Steps to Reproduce:**
Upgrade from 1.3.4 to 1.5 with community catalog enabled.

**Results:** 
When Community catalog is activated, update of catalogs failed due to some encoding error. We have the following logs:

(Error 1366: Incorrect string value: '\xE2\x9D\xA4\xEF\xB8\x8F...' for column 'readme' at row 1)
[2017-03-06 12:05:25]

(Error 1366: Incorrect string value: '\xE2\x9D\xA4\xEF\xB8\x8F...' for column 'readme' at row 1)
[2017-03-06 12:06:06]
time="2017-03-06T12:06:06Z" level=error msg="Failed to perform catalog refresh: Error 1366: Incorrect string value: '\\xE2\\x9D\\xA4\\xEF\\xB8\\x8F...' for column 'readme' at row 1"

Database seems to be in latin1_swedish
show full columns from catalog_template;
+-----------------+---------------+-------------------+------+-----+---------+----------------+---------------------------------+---------+
| Field           | Type          | Collation         | Null | Key | Default | Extra          | Privileges                      | Comment |
+-----------------+---------------+-------------------+------+-----+---------+----------------+---------------------------------+---------+
| id              | bigint(20)    | NULL              | NO   | PRI | NULL    | auto_increment | select,insert,update,references |         |
| created_at      | datetime      | NULL              | YES  |     | NULL    |                | select,insert,update,references |         |
| updated_at      | datetime      | NULL              | YES  |     | NULL    |                | select,insert,update,references |         |
| environment_id  | varchar(255)  | latin1_swedish_ci | YES  | MUL | NULL    |                | select,insert,update,references |         |
| catalog_id      | bigint(20)    | NULL              | YES  | MUL | NULL    |                | select,insert,update,references |         |
| name            | varchar(1024) | latin1_swedish_ci | YES  |     | NULL    |                | select,insert,update,references |         |
| is_system       | varchar(255)  | latin1_swedish_ci | YES  |     | NULL    |                | select,insert,update,references |         |
| description     | varchar(1024) | latin1_swedish_ci | YES  |     | NULL    |                | select,insert,update,references |         |
| default_version | varchar(1024) | latin1_swedish_ci | YES  |     | NULL    |                | select,insert,update,references |         |
| path            | varchar(1024) | latin1_swedish_ci | YES  |     | NULL    |                | select,insert,update,references |         |
| maintainer      | varchar(1024) | latin1_swedish_ci | YES  |     | NULL    |                | select,insert,update,references |         |
| license         | mediumtext    | latin1_swedish_ci | YES  |     | NULL    |                | select,insert,update,references |         |
| project_url     | varchar(1024) | latin1_swedish_ci | YES  |     | NULL    |                | select,insert,update,references |         |
| upgrade_from    | varchar(1024) | latin1_swedish_ci | YES  |     | NULL    |                | select,insert,update,references |         |
| folder_name     | varchar(1024) | latin1_swedish_ci | YES  |     | NULL    |                | select,insert,update,references |         |
| catalog         | varchar(1024) | latin1_swedish_ci | YES  |     | NULL    |                | select,insert,update,references |         |
| base            | varchar(1024) | latin1_swedish_ci | YES  |     | NULL    |                | select,insert,update,references |         |
| icon            | mediumtext    | latin1_swedish_ci | YES  |     | NULL    |                | select,insert,update,references |         |
| icon_filename   | varchar(255)  | latin1_swedish_ci | YES  |     | NULL    |                | select,insert,update,references |         |
| readme          | mediumtext    | latin1_swedish_ci | YES  |     | NULL    |                | select,insert,update,references |         |
+-----------------+---------------+-------------------+------+-----+---------+----------------+---------------------------------+---------+

**Comment by JeanDaniel-Fischer** [comment]
It works if I changed the collation with this command:

ALTER TABLE catalog_template MODIFY readme mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

Should rancher create the table with the good collation ?

**Comment by ket4yii** [comment]
Oh, I have the same problem. But I use external DB.

**Comment by LLParse** [comment]
Worked for me - I had to bounce the server after applying the DDL statement.

**Comment by vincent99** [comment]
You have the default charset and collation for the database on your external database set wrong, they should be `utf8` and `utf8_general_ci`.  There is no need to use `utf8mb4` vs `utf8` unless you really want to store 4-byte supplemental characters.

 http://docs.rancher.com/rancher/v1.4/en/installing-rancher/installing-server/#launching-rancher-server---single-container---external-database

**Comment by vincent99** [comment]
...Which that particular character is not, but some others are, like 🍵🍶🍷🍸.

So we should probably change the docs to suggest `utf8mb4` anyway, it doesn't require any extra space.

**Comment by joshwget** [comment]
@vincent99 Is there anyway we can set the character set for this column without users having to set the default character set? I see this being a pretty common issue for users using an external database. Or maybe we can store README as a blob to avoid this?

**Comment by vincent99** [comment]
You could, but there's 1001 other fields with the same problem (i.e. the description on everything).  Users should follow instructions..

Switching to mb4 causes other issues unless you also do various other things to allow indexes to be 3kb instead or 767 bytes as is the default in some MySQL versions.  varchar(255) * 3 bytes/char for utf8 = 765 bytes, switching to mb4 gives you 255*4 = 1020 and you can't index any names anymore..
