### ISSUE TITLE
Building Rancher server image when "http://gondor.apana.org.au" cannot be reached

### ISSUE THREAD

**Issue by Cerfoglg** [rancher/rancher#8065]
As of the time of this issue being posted, I've attempted to build the rancher server image by running the build-image.sh script inside the server directory of this repo, in order to build a custom version of the rancher server. Unfortunately the build always stops with this error:

`curl -R -L -O http://gondor.apana.org.au/~herbert/dash/files/dash-0.5.8.tar.gz`
`curl: (7) Failed to connect to gondor.apana.org.au port 80: Connection refused`

This is probably due to the site in question being currently offline. As a result, the server image cannot be built this way at this time.

**Comment by superseb** [comment]
We can't do anything on a host being down, maybe change the source where we built from. I'm still curious what commit/branch you were trying to build here which came up with this error?
