### ISSUE TITLE
etcd constantly losing quorum

### ISSUE THREAD

**Issue by schuylr** [rancher/rancher#8066]
**Rancher Versions:**
Rancher	v1.4.1
Cattle	v0.176.9
User Interface	v1.4.6
Rancher CLI	v0.4.1
Rancher Compose	v0.12.2

**Docker Version:** 1.12.6

**OS and where are the hosts located?:** AWS EC2

**Setup Details:** Single Node Rancher External DB

**Environment Type:** Cattle

**Steps to Reproduce:**

1. Mark at least 7 hosts with the `etcd=true` label
2. Start a fresh etcd install with 3-7 hosts (I used 7)
3. Allow it to scale up and leave it running

**Results:** 

Within the hour, logs fill with service reconciliation issues and quorum is lost. An otherwise stable etcd service is broken by Cattle:

![screen shot 2017-03-06 at 9 51 15 am](https://cloud.githubusercontent.com/assets/12628715/23614863/776db3e8-0252-11e7-9ed4-657145082a38.png)

The result is a bunch of containers stuck in a giddyup race condition when more than 2 containers are lost at the same time. Data is also lost and I have to restore manually from the backups.

Note that I also turned off container recreation from the health checks to confirm an issue with the scheduling.

Paging @LLParse ?

**Comment by LLParse** [comment]
@schuylr Thanks for bringing this to my attention. The plan for a while has been to remove `giddyup` from the image and instead use etcd for leader election - no sense reinventing the wheel. I will see that it is done as part of https://github.com/rancher/rancher/issues/7705
We fork this process so it will only impact backup creation and should not block etcd from running.

The scheduling issues you are seeing are really troublesome. I did a quick test and found a different problem https://github.com/rancher/rancher/issues/8070

@cjellick Can you make anything of the service errors in the audit log?

**Comment by schuylr** [comment]
@LLParse Please!!! Giddyup has the biggest problems especially when 2+ hosts get killed because it makes an incorrect member list when trying to reconnect to etcd so I constantly get "Member Count is unequal".

The issue #8070 you made is actually the reason I made this issue as it was the cause of all of this. With a perfectly stable 7-node cluster, Rancher tries to schedule a new container on existing hosts, which then triggers the anti-affinity, which then triggers the race condition in my issue above. I think it has to do something with the status "Incomplete: 1"

I was troubleshooting this with @ibuildthecloud on Slack and he said that the bigger issue may have stemmed from an earlier point in the service log, but I haven't seen anything other than what I screenshotted above. I suspect a bigger Cattle orchestration issue happening here, but I don't want to cry wolf.

**Comment by LLParse** [comment]
@schuylr I'm sorry for your trouble with all of this. I just did a _fresh_ deployment of 7-node etcd and ran into the same dang problem - seems like a regression to me. I updated the ticket.

Your orchestration suspicions are noted... ;-)

**Comment by shakefu** [comment]
We ran into the same thing doing a trial deployment of etcd from the catalog, which is why we decided to hold off on using it. Glad to hear it's being worked on!

**Comment by LLParse** [comment]
Fixed in Rancher v1.6.0

Any further problems, please open a new issue. Thanks
