### ISSUE TITLE
Only Cattle available as an environment type

### ISSUE THREAD

**Issue by DarrenRatcliffe** [rancher/rancher#8067]
When deploying & using version 1.5.0 the only 'orchestrator type' available when creating new environment is Cattle?

![image](https://cloud.githubusercontent.com/assets/1911051/23615006/de3aa354-027c-11e7-820d-0bec8ca219f5.png)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.5.0` Cattle: `v0.177.7` UI: `v1.5.6` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`settings.projects.new`|

**Comment by niusmallnan** [comment]
Pls check and make sure the **library catalog** can clone completely.

**Comment by DarrenRatcliffe** [comment]
@niusmallnan I can see Kubernetes & Windows experimental in the catalog and I can use them to deploy to the 'default' environment

**Comment by DarrenRatcliffe** [comment]
it may have taken a while to propagate but I can see all of the orchestrators that I would expect to see, it is just that they all seem to now have cattle logos and none are experimental:

![image](https://cloud.githubusercontent.com/assets/1911051/23615819/9a9decfc-027f-11e7-895d-15d571f987de.png)

**Comment by vincent99** [comment]
If you look at the names at the bottom they work fine, there's just a UI bug finding the right icon because of a catalog change.

**Comment by DarrenRatcliffe** [comment]
@vincent99 thanks, so is the UI bug already an issue? if so I will close this?

**Comment by vincent99** [comment]
Yes, it's fixed for 1.5.1.
