### ISSUE TITLE
503 from LB

### ISSUE THREAD

**Issue by derDieDasJojo** [rancher/rancher#8068]
The Loadbalancer does not seem to work.
I tried a very basic configuration with the UI (resulting in the folowing docker-compose.yml)
and when i try to call the service i get: 503 Service Unavailable

https://gist.github.com/derDieDasJojo/f1255f842acc45c1fd28f77ce1c9934c

what can i do ?
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.5.0` Cattle: `v0.177.7` UI: `v1.5.6` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`stacks.index`|

**Comment by aemneina** [comment]
Have you tried the suggestion in the gist comments?

**Comment by superseb** [comment]
Closing as stale.
