### ISSUE TITLE
scaling down hosts using webhooks

### ISSUE THREAD

**Issue by DarrenRatcliffe** [rancher/rancher#8069]
When using a webhook to scale down hosts, the webhook works and it triggers docker machine to delete the host but in the rancher UI the hosts show as inactive. When you try to delete the host manually from the UI, it displays method not supported:

![image](https://cloud.githubusercontent.com/assets/1911051/23620540/3364ba06-028f-11e7-9fda-d67fd1f2eb44.png)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.5.0` Cattle: `v0.177.7` UI: `v1.5.6` |
|Access|`localauth` `admin`|
|Orchestration|`Kubernetes`|
|Route|`hosts.index`|

**Comment by sangeethah** [comment]
@DarrenRatcliffe -  This issue is tracked in - https://github.com/rancher/rancher/issues/7913 . In rancher-server side this host is already in  purged state but the state is not reflected in the UI . When UI is manually refreshed , you should see the host not show in the UI any more.

**Comment by DarrenRatcliffe** [comment]
@sangeethah thanks I will close this issue then
