### ISSUE TITLE
Document Rancher/K8s containers required for air gapped installs

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#8074]
Document Rancher/K8s containers, as well as versions required, to be present/provided for air gapped installs.

**Comment by aemneina** [comment]
Talking to @sangeethah about having a link/tag to always point to the latest template, for versions of templates/images to be easily derived.

**Comment by deniseschannon** [comment]
That doesn't solve the issue as you'd still have to click on each individual template for each infra service.

**Comment by aemneina** [comment]
document the requirement to have a git repo for airgapped installs to maintain infra catalog items wholesale... so you dont have to fiddle with individual services :)

**Comment by ullbergm** [comment]
@aemneina , does that mean that you have successfully been able to run rancher is complete airgap?

I'm having issues getting it to work in an environment where the docker service can pull down any containers it wants but there is no access to the internet beyond that.

It looks to be getting stuck trying to pull down the charts via git maybe.

The UI never loads, it is stuck on 'Loading...'

Same results using a single docker container as well as a 3-node HA rke install.

**Comment by superseb** [comment]
We have the following guides:

For 1.6: https://rancher.com/docs/rancher/v1.6/en/installing-rancher/installing-server/no-internet-access/#using-a-private-registry
For 2.0: https://rancher.com/docs/rancher/v2.x/en/installation/air-gap-installation/

@aemneina Anything else needed on this?

@ullbergm Yes it can be run in airgap, can you share output from developer tools to see what call is hanging and the `rancher/rancher` container logging? Is this with or without proxy?

**Comment by superseb** [comment]
- Output of `docker logs container_id_or_name` of `rancher/rancher` container
- Browser developer tools output of network connections when visiting the UI
- Output of `curl -k https://IP` on the command line

**Comment by ullbergm** [comment]
I'm not able to access the UI for the developer tools. It's stuck on 'Loading...'

Docker logs
https://pastebin.com/p5CVL8Ra

root@developer:~# curl https://localhost/ --insecure
{"type":"collection","links":{"self":"https://localhost/"},"actions":{},"pagination":{"limit":1000},"sort":{"order":"asc","reverse":"https://localhost/?order=desc"},"resourceType":"apiRoot","data":[{"actions":{},"apiVersion":{"group":"meta.cattle.io","path":"/meta","version":"v1"},"baseType":"apiRoot","links":{"apiRoots":"https://localhost/meta/apiroots","root":"https://localhost/meta","schemas":"https://localhost/meta/schemas","self":"https://localhost/meta","subscribe":"https://localhost/meta/subscribe"},"type":"apiRoot"},{"actions":{},"apiVersion":{"group":"management.cattle.io","path":"/v3","version":"v3"},"baseType":"apiRoot","links":{"authConfigs":"https://localhost/v3/authconfigs","catalogs":"https://localhost/v3/catalogs","clusterAlerts":"https://localhost/v3/clusteralerts","clusterComposeConfigs":"https://localhost/v3/clustercomposeconfigs","clusterEvents":"https://localhost/v3/clusterevents","clusterLoggings":"https://localhost/v3/clusterloggings","clusterPipelines":"https://localhost/v3/clusterpipelines","clusterRegistrationTokens":"https://localhost/v3/clusterregistrationtokens","clusterRoleTemplateBindings":"https://localhost/v3/clusterroletemplatebindings","clusters":"https://localhost/v3/clusters","dynamicSchemas":"https://localhost/v3/dynamicschemas","globalComposeConfigs":"https://localhost/v3/globalcomposeconfigs","globalRoleBindings":"https://localhost/v3/globalrolebindings","globalRoles":"https://localhost/v3/globalroles","groupMembers":"https://localhost/v3/groupmembers","groups":"https://localhost/v3/groups","listenConfigs":"https://localhost/v3/listenconfigs","nodeDrivers":"https://localhost/v3/nodedrivers","nodePools":"https://localhost/v3/nodepools","nodeTemplates":"https://localhost/v3/nodetemplates","nodes":"https://localhost/v3/nodes","notifiers":"https://localhost/v3/notifiers","pipelineExecutionLogs":"https://localhost/v3/pipelineexecutionlogs","pipelineExecutions":"https://localhost/v3/pipelineexecutions","pipelines":"https://localhost/v3/pipelines","podSecurityPolicyTemplateProjectBindings":"https://localhost/v3/podsecuritypolicytemplateprojectbindings","podSecurityPolicyTemplates":"https://localhost/v3/podsecuritypolicytemplates","preferences":"https://localhost/v3/preferences","principals":"https://localhost/v3/principals","projectAlerts":"https://localhost/v3/projectalerts","projectLoggings":"https://localhost/v3/projectloggings","projectNetworkPolicies":"https://localhost/v3/projectnetworkpolicies","projectRoleTemplateBindings":"https://localhost/v3/projectroletemplatebindings","projects":"https://localhost/v3/projects","roleTemplates":"https://localhost/v3/roletemplates","root":"https://localhost/v3","self":"https://localhost/v3","settings":"https://localhost/v3/settings","sourceCodeCredentials":"https://localhost/v3/sourcecodecredentials","sourceCodeRepositories":"https://localhost/v3/sourcecoderepositories","subscribe":"https://localhost/v3/subscribe","templateContents":"https://localhost/v3/templatecontents","templateVersions":"https://localhost/v3/templateversions","templates":"https://localhost/v3/templates","tokens":"https://localhost/v3/tokens","users":"https://localhost/v3/users"},"type":"apiRoot"},{"actions":{},"apiVersion":{"group":"cluster.cattle.io","path":"/v3/cluster","version":"v3"},"baseType":"apiRoot","links":{"namespaces":"https://localhost/v3/cluster/namespaces","persistentVolumes":"https://localhost/v3/cluster/persistentvolumes","root":"https://localhost/v3/cluster","self":"https://localhost/v3/cluster","storageClasses":"https://localhost/v3/cluster/storageclasses","subscribe":"https://localhost/v3/cluster/subscribe"},"type":"apiRoot"},{"actions":{},"apiVersion":{"group":"project.cattle.io","path":"/v3/project","version":"v3"},"baseType":"apiRoot","links":{"appRevisions":"https://localhost/v3/project/apprevisions","apps":"https://localhost/v3/project/apps","basicAuths":"https://localhost/v3/project/basicauths","certificates":"https://localhost/v3/project/certificates","configMaps":"https://localhost/v3/project/configmaps","cronJobs":"https://localhost/v3/project/cronjobs","daemonSets":"https://localhost/v3/project/daemonsets","deployments":"https://localhost/v3/project/deployments","dnsRecords":"https://localhost/v3/project/dnsrecords","dockerCredentials":"https://localhost/v3/project/dockercredentials","ingresses":"https://localhost/v3/project/ingresses","jobs":"https://localhost/v3/project/jobs","namespaceComposeConfigs":"https://localhost/v3/project/namespacecomposeconfigs","namespacedBasicAuths":"https://localhost/v3/project/namespacedbasicauths","namespacedCertificates":"https://localhost/v3/project/namespacedcertificates","namespacedDockerCredentials":"https://localhost/v3/project/namespaceddockercredentials","namespacedSecrets":"https://localhost/v3/project/namespacedsecrets","namespacedServiceAccountTokens":"https://localhost/v3/project/namespacedserviceaccounttokens","namespacedSshAuths":"https://localhost/v3/project/namespacedsshauths","persistentVolumeClaims":"https://localhost/v3/project/persistentvolumeclaims","pods":"https://localhost/v3/project/pods","replicaSets":"https://localhost/v3/project/replicasets","replicationControllers":"https://localhost/v3/project/replicationcontrollers","root":"https://localhost/v3/project","secrets":"https://localhost/v3/project/secrets","self":"https://localhost/v3/project","serviceAccountTokens":"https://localhost/v3/project/serviceaccounttokens","services":"https://localhost/v3/project/services","sshAuths":"https://localhost/v3/project/sshauths","statefulSets":"https://localhost/v3/project/statefulsets","subscribe":"https://localhost/v3/project/subscribe","workloads":"https://localhost/v3/project/workloads"},"type":"apiRoot"}]}

**Comment by ullbergm** [comment]
Ah, *those* developer tools, I was looking for some Rancher specific ones.. too early in the morning still i guess. :)

Although i am behind a proxy server (it should not apply when talking to the rancher server), I don't see any blocked connections in chrome.
https://imgur.com/a/6rUTWTJ
And for what it is worth, this is what view-source shows:
https://pastebin.com/bMWR3Ngt

**Comment by superseb** [comment]
Is this directly talking to the IP of the host running the `rancher/rancher` container? And are you visiting `https://192.168.223.42` (note the `https://` and not `http://`)

**Comment by ullbergm** [comment]
it is an openstack vm with a floating ip, but other than that yes, the connection is going straight to that vm with https. http correctly redirects me to https.

I'm going have someone else try it on another computer in about an hour to make sure it is not something environmental on my machine.

**Comment by ullbergm** [comment]
@superseb Turns out it was something on my machine. Apologies for wasting your time on this.
Thanks again for having a air gap scenario, more projects should follow your lead on that.

**Comment by superseb** [comment]
Awesome, let me know if you run into anything else.
