### ISSUE TITLE
RancherLabs should provide repositories of supported docker-engine versions

### ISSUE THREAD

**Issue by dabelenda** [rancher/rancher#8077]
**Rancher Versions:** N/A
Server: N/A
healthcheck: N/A
ipsec: N/A
network-services: N/A
scheduler: N/A
kubernetes (if applicable): N/A

**Docker Version:** N/A

**OS and where are the hosts located? (cloud, bare metal, etc):** any

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** any

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** any

**Steps to Reproduce:**

When installing a new RHEL7 rancher-agent setup, we hit hard the new install method for docker where the older versions of docker-engine are not available anymore in the new "CE" repositories.
Moreover, the official rancher install steps (https://docs.rancher.com/rancher/v1.4/en/hosts/), is kind of a "install once, never update" approach.

It would be great to have a repository per rancher version containing only officially supported versions of docker for that specific rancher version.

Maybe rancher-server itself could provide the repositories so that you always have the correct version of docker to work with this version of docker available via the rancher url.

**Results:**

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
