### ISSUE TITLE
Catalog Upgrade Bug - Container Allocation Failing

### ISSUE THREAD

**Issue by LLParse** [rancher/rancher#8084]
**Rancher Versions:**
Server: v1.5.1
healthcheck: v0.2.3
ipsec: v0.9.4
network-services: v0.9.4
scheduler: v0.7.4

**Docker Version:** 1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):**Ubuntu 16.04.1 LTS (4.4.0), AWS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single node, external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:**
1. Add the https://github.com/rancher/rancher-tools-catalog catalog
2. Launch Git Mirror 0.6 named `git-mirror` and wait until it becomes active
3. Upgrade Git Mirror to 1.0 without changing any options
4. Launch a separate Git Mirror 1.0 named `git-mirror2` without changing any options

**Results:** 
The Upgraded stack's mirror service is stuck at scale=1. When manually asked to scale, allocation errors pour in that seem to be related to the one-container-per-host anti-affinity.

![bad upgrade](http://i.imgur.com/ep2gGIz.png)
![logs](http://i.imgur.com/srSwB4o.png)

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
