### ISSUE TITLE
Too many colons in address

### ISSUE THREAD

**Issue by jmreicha** [rancher/rancher#8085]
**Rancher Versions:**
Server: 1.4.1 -> 1.5.1
healthcheck: v0.2.3
ipsec: rancher/net:holder
network-services: v0.4.5
scheduler: v0.6.3
kubernetes (if applicable):

**Docker Version:**  1.13

**OS and where are the hosts located? (cloud, bare metal, etc):**  CoreOS in AWS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** HA, external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:**  Upgrade Rancher server version from 1.4.1 to 1.5.1 and rancher agent from 1.2.0 to 1.2.1

**Results:** 

Following error in the rancher server logs after upgrading.  No other changes were made.

```
time="2017-03-07T18:16:54Z" level=fatal msg="dial tcp: too many colons in address rancher.xxx.us-west-1.rds.amazonaws.com:3306:3306"
time="2017-03-07T18:16:56Z" level=fatal msg="dial tcp: too many colons in address rancher.xxx.us-west-1.rds.amazonaws.com:3306:3306"
time="2017-03-07T18:16:58Z" level=fatal msg="dial tcp: too many colons in address rancher.xxx.us-west-1.rds.amazonaws.com:3306:3306"
time="2017-03-07T18:17:00Z" level=fatal msg="dial tcp: too many colons in address rancher.xxx.us-west-1.rds.amazonaws.com:3306:3306"
time="2017-03-07T18:17:02Z" level=fatal msg="dial tcp: too many colons in address rancher.xxx.us-west-1.rds.amazonaws.com:3306:3306"
```

**Comment by jmreicha** [comment]
I was using `--db-host rancher-server-ha.c6jsgxysrq7u.us-west-1.rds.amazonaws.com:3306` and `--db-port 3306` in my rancher server command.  I chopped the port off the `db-host` and it is working now.

**Comment by marcbachmann** [comment]
Thanks, I also just ran into this issue.
I've used `aws_db_instance.rancher.endpoint` instead of `aws_db_instance.rancher.address` when I deployed rancher with terraform.

Maybe some better messages would be nice.
