### ISSUE TITLE
Kubernetes infrastructure stack tries to continue running on disconnected hosts - causes outages

### ISSUE THREAD

**Issue by ryanwalls** [rancher/rancher#8086]
**Rancher Versions:**
Server: 1.4.1
healthcheck: v0.2.3
ipsec: rancher/net:holder
network-services: rancher/network-manager:v0.4.5
scheduler: rancher/k8s:v1.5.2-rancher1-4
kubernetes (if applicable): v1.5.2-rancher1-4

**Docker Version:**
1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu on AWS EC2 instances

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher with external RDS database

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes 

**Steps to Reproduce:**
* Run k8s cluster with 3 hosts.
* Scale up custer to 25 hosts.
* Scale down to 10 hosts.

**Results:** 
* Network services shows "degraded" and tries to keep placing `network-manager` containers on the disconnected instances.  See screenshot.
<img width="1385" alt="screen shot 2017-03-01 at 4 28 04 pm" src="https://cloud.githubusercontent.com/assets/842653/23677449/746f1ae2-033d-11e7-99c5-79804e9554d2.png">

* `proxy` does same thing.  Tries to run on disconnected instances.
* `kubelet` does same thing.
* Ingress routing to our applications stops working.

The only way to recover is to manually go through and deactivate/delete the disconnected hosts and then manually delete the extra `proxy`, `kubelet`, and `network-manager` containers.

**Comment by ryanwalls** [comment]
Here's a shot of another one of our environments demonstrating the issue.
<img width="1852" alt="screen shot 2017-03-07 at 2 11 02 pm" src="https://cloud.githubusercontent.com/assets/842653/23678107/f4242ec4-033f-11e7-80a3-605a7e833445.png">

**Comment by deniseschannon** [comment]
Kubernetes 1.5.2 does not support DOcker 1.13.1. Please try with Docker 1.12.6

**Comment by ryanwalls** [comment]
@deniseschannon 
Tried with Docker 1.12.6.  Still happens.  We only have 8 servers running right now, but have 84 network service containers running, 14 kubulets, 29 proxies, 72 ipsec containers, etc.  
![image](https://cloud.githubusercontent.com/assets/842653/23771255/8878d9a0-04d3-11e7-9b44-fbdbeaf9caa5.png)

The problem is that the rancher networking seems to be still trying to route to these dead hosts... so our Production UI has 5+ second requests to get static files from our UI containers (it seems to route to dead hosts, eventually times out after 5 seconds, and then routes to healthy hosts.)

Can you reopen this?  Thanks.

**Comment by ryanwalls** [comment]
@alena1108 If you can shed any light on this, it would be greatly appreciated!  I know you're one of the kubernetes/rancher experts.

**Comment by ryanwalls** [comment]
If anyone at Rancher wants to take a peek at our system and see the behavior first hand, we would be happy to do a screen share.

**Comment by deniseschannon** [comment]
@ryanwalls I suspect it has something to do with scaling up/down. How are you scaling down the cluster? I'm assuming cluster is the hosts in Rancher.

**Comment by ryanwalls** [comment]
@deniseschannon We are scaling using the kubernetes cluster-autoscaler.  https://github.com/kubernetes/contrib/tree/master/cluster-autoscaler.  Yes, each instance in the cluster is also a host in rancher.

**Comment by deniseschannon** [comment]
If you're running autoscaler, did you make sure to update your cloud provider to AWS? If the cloud provider is set to "Rancher", the default, there may be issues.

Rancher docs on how to do it in v1.5.x.

http://docs.rancher.com/rancher/v1.5/en/kubernetes/providers/

**Comment by ryanwalls** [comment]
@deniseschannon Yes, the cloud provider is set to AWS.  Correct, auto-scaler won't work without that setting.

**Comment by superseb** [comment]
Closing as stale.
