### ISSUE TITLE
Containers in Compose files

### ISSUE THREAD

**Issue by joshwget** [rancher/rancher#8091]
Support adding standalone containers in a Compose file via the `containers` key. The syntax for container configs should be similar to service configs.

The lifecycle of containers created via a Compose file should be tied to the corresponding stack.

**Comment by tfiduccia** [comment]
Version - 2.0 master 8/5
Exporting config with container is now showing the container section.  But you can't import with that.  Says:
" | Error |  -- | -- | -- Failed to find service config for container1"
