### ISSUE TITLE
Remove docker-compose.yml/rancher-compose.yml distinction

### ISSUE THREAD

**Issue by joshwget** [rancher/rancher#8092]
The distinction between `docker-compose.yml` and `rancher-compose.yml` should be removed. Rancher Compose should be able to run files that contain fields from either. Backwards compatibility should be achieved by merging `docker-compose.yml` and `rancher-compose.yml` and treating it as if it were one file.

The `catalog` section of `rancher-compose.yml` should be supported in a separate configuration file for catalog templates in the future.

**Comment by soumyalj** [comment]
Tested with master. Created stacks using docker-compose files with few fields from rancher-compose. 
Created stacks using only docker-compose files with all fields from rancher compose merged in it.  
Created stack using only rancher-compose file with all fields from docker-compose file [docker-compose should have only version field]
