### ISSUE TITLE
healthcheck, ipsec, network-manager all stuck on "activating" or "unhealthy"

### ISSUE THREAD

**Issue by ryanwalls** [rancher/rancher#8095]
Rancher Versions:
Server: 1.4.1
healthcheck: v0.2.3
ipsec: rancher/net:holder
network-services: rancher/network-manager:v0.4.5
scheduler: rancher/k8s:v1.5.2-rancher1-4
kubernetes (if applicable): v1.5.2-rancher1-4

Docker Version:
1.12.6

OS and where are the hosts located? (cloud, bare metal, etc):
Ubuntu on AWS EC2 instances

Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)
single node rancher with external RDS database

Environment Type: (Cattle/Kubernetes/Swarm/Mesos)
Kubernetes

Steps to Reproduce:
* Create new k8s environment
* Add hosts

**Results:** 
Nothing comes online.  Containers are stuck.  SSH to individual boxes and some of the containers are there, but Rancher never leaves "activating"
![image](https://cloud.githubusercontent.com/assets/842653/23686033/7c331d9c-0364-11e7-9def-f10a216a43c0.png)

Also, the `global` services are only trying to activate on one machine.

**Comment by aemneina** [comment]
@ryanwalls can your ipsec containers ping each other?

**Comment by ryanwalls** [comment]
@aemneina The ipsec seems to have gotten in a locked/race condition state.  It would never leave "activating."  We tried deleting ipsec but it said the driver was in use.  We finally ended up deleting all containers that were using the driver.  Then we deleted the ipsec service and re-added it.  And then finally the environment resolved.
