### ISSUE TITLE
Web Shell can not be used in mobile browser

### ISSUE THREAD

**Issue by dengshaodong** [rancher/rancher#8097]
Rancher Versions:
"CATTLE_RANCHER_SERVER_VERSION=v1.4.1",
"CATTLE_RANCHER_COMPOSE_VERSION=v0.12.2",
"CATTLE_RANCHER_CLI_VERSION=v0.4.1",
"CATTLE_CATTLE_VERSION=v0.176.9",
"CATTLE_RANCHER_SERVER_VERSION=v1.4.1",
"CATTLE_RANCHER_COMPOSE_VERSION=v0.12.2",
"CATTLE_RANCHER_CLI_VERSION=v0.4.1",
"CATTLE_CATTLE_VERSION=v0.176.9",

Docker Version:
"DockerVersion": "1.13.0",

Web shell can be opened in mobile browser, but nothing can be input through it .
 I tried in ios 10.0 and Android , both have the problem.

**Comment by vincent99** [comment]
![img_5394](https://user-images.githubusercontent.com/753917/30315413-b86d2d56-9758-11e7-989d-2b353117ec84.PNG)

**Comment by SemvandenBroek** [comment]
This is still an issue for me on Android 7.0.1. The keyboard is not opened when I click the shell window allowing no input at all.

**Comment by vincent99** [comment]
@SemvandenBroek I haven't tried specifically with Android but this was changed for the 2.0 preview, not 1.x.

**Comment by SemvandenBroek** [comment]
@vincent99 Oh I haven't noticed that. I will try it out in the near future! Thanks
