### ISSUE TITLE
Rancher should notify when failing to pull image

### ISSUE THREAD

**Issue by trondhindenes** [rancher/rancher#8099]
**Rancher Versions:**
1.4, cattle

If rancher fails to pull a (private) image, the container will be forever stuck in "starting" according to the web ui. It would be much better if there was a separate status "pulling image" or something, so that it was easier to see whats going on. "Starting" is too generic.

**Comment by tfiduccia** [comment]
@trondhindenes - For stand-alone containers, the container actually goes to Error for me with the message " Error (Error response from daemon: manifest for tani/notreal:latest not found"
For Services, basically the same thing happens with the error showing up on the Stack/Service level.  The container itself will error, stop, delete then retry.  Which is the proper behavior.

**Comment by trondhindenes** [comment]
What happened to me was that the pull was successful, but not the extract. The behavior you describe is not what I'm seeing.

**Comment by StrongMonkey** [comment]
@trondhindenes It is actually a bug which is already fixed in 1.5. In 1.5 you can see the real time status in UI when pulling images

**Comment by deniseschannon** [comment]
@trondhindenes Please let us know if you are still having issues when you upgrae to 1.5.
