### ISSUE TITLE
Privileged service with host network can't access stack data through metadata service

### ISSUE THREAD

**Issue by JKWalrave** [rancher/rancher#8101]
**Rancher Versions:**
Server: v1.4.1
healthcheck: v0.2.3
ipsec: v0.0.4
network-services: v0.0.16
scheduler: v0.4.0

**Docker Version:**
1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04.1 LTS (with KVM) (4.4.0) on an Openstack Cloud

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node with External DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Create a service on any node in your environment. Use the following settings:
`Network: Host`
`DNS: Enable Rancher DNS service discovery`
`Privileged: Full access to the host`

Query the rancher metadata service from inside the container. For reproduction purposes we're using curl:
`curl http://rancher-metadata.rancher.internal/latest/self/host`
`curl http://172.17.0.2/latest/self/host`
`curl http://169.254.169.250/latest/self/host`

**Results:** 
What we're seeing is the environment_uuid, but we'de also like to get the environment_name.

In non-host-networked services it is possible to get the environment_name through the stacks metadata. However, this metadata is also not available on a host-networked service.

**Comment by leodotcloud** [comment]
The metadata service relies on the source IP address of the request to figure out "self". A container with `--net=host` uses the host networking and hence it's not possible to figure out which container is sending this request. So only the "host" section of self is populated. I believe there shouldn't be any difference in figuring out environment_uuid from host namespace containers.

If you want to figure out the name of environment, you can query the API.

**Comment by leodotcloud** [comment]
Please create a new issue if you are still having problems.
