### ISSUE TITLE
Feature-idea: Ability to add catalog items when creating environment templates

### ISSUE THREAD

**Issue by pangdudu** [rancher/rancher#8102]
**Rancher Versions:**
Server: 1.5.1

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Feature idea**
When creating a new environment template, it would be awesome, if one could also add community catalog items (and pre-configure them).

We're creating QA environments on-the-fly for testing our micro-services and need to have:
* sentry
* rabbit
* ELK stack

running.

It's awesome that we can already configure:
* rancher-nfs
* secrets

with the templates, but being able to configure the rest of our setup in the template would be supreme.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
