### ISSUE TITLE
Registering hosts using ELB for “Host Registration URL” fails. 

### ISSUE THREAD

**Issue by dexterddit** [rancher/rancher#8103]
Title:
**Registering hosts using ELB for “Host Registration URL” fails.** 

Description
•	Rancher is install in HA configuration (3 nodes pointing to a RDS MySQL). A elb is configure in from of the rancher nodes. With this configuration it is impossible to add hosts if the Host registration URL points to the elb address.  If we use the Master elected node address for the Host registration URL instead the host is added successfully.

Logs:
Found container ID: dc4b9ea6ad911a04748c40ac78fd645b0417d1363a1ab25210a6ae742fee0b5f
Checking root: /host/run/runc
Checking file: 25f8a284859e7a654955efd095e838267429ec7bafc5af10fdcf9db2fcf3cd4a
Checking file: dc4b9ea6ad911a04748c40ac78fd645b0417d1363a1ab25210a6ae742fee0b5f
Found state.json: dc4b9ea6ad911a04748c40ac78fd645b0417d1363a1ab25210a6ae742fee0b5f
time="2017-03-07T15:38:44Z" level=info msg="Execing [/usr/bin/nsenter --mount=/proc/3497/ns/mnt -F -- /var/lib/docker/overlay2/310c961a29330d83f2d394e75b92c64c2b7896ec01d0d28815fbe31c957f7e2e/merged/usr/bin/share-mnt --stage2 /var/lib/rancher/volumes /var/lib/kubelet -- norun]"
Found container ID: dc4b9ea6ad911a04748c40ac78fd645b0417d1363a1ab25210a6ae742fee0b5f
Checking root: /run/runc
Checking file: 25f8a284859e7a654955efd095e838267429ec7bafc5af10fdcf9db2fcf3cd4a
Checking file: dc4b9ea6ad911a04748c40ac78fd645b0417d1363a1ab25210a6ae742fee0b5f
Found state.json: dc4b9ea6ad911a04748c40ac78fd645b0417d1363a1ab25210a6ae742fee0b5f
INFO: Starting agent for 2EC30B8108AB906D0E88
INFO: Access Key: 2EC30B8108AB906D0E88
INFO: Config URL: http://acmelb-00000000.eu-west-1.elb.amazonaws.com/v1
INFO: Storage URL: http://acmelb-00000000.eu-west-1.elb.amazonaws.com/v1
INFO: API URL: http://acmelb-00000000.eu-west-1.elb.amazonaws.com/v1
INFO: IP: xx.xxx.xxx.xxx
INFO: Port:
INFO: Required Image: rancher/agent:v1.2.0
INFO: Current Image: rancher/agent:v1.2.0
INFO: Using image rancher/agent:v1.2.0
INFO: Downloading agent http://acmelb-00000000.eu-west-1.elb.amazonaws.com/v1/configcontent/configscripts
INFO: Updating configscripts
INFO: Downloading http://acmelb-00000000.eu-west-1.elb.amazonaws.com/v1//configcontent//configscripts current=
INFO: Running /var/lib/cattle/download/configscripts/configscripts-1-f0f3fb2e1110b5ada7c441705981f93a480313a324294321cff467f0c3e12319/apply.sh
INFO: Sending configscripts applied 1-f0f3fb2e1110b5ada7c441705981f93a480313a324294321cff467f0c3e12319
INFO: Updating pyagent
INFO: Downloading http://acmelb-00000000.eu-west-1.elb.amazonaws.com/v1//configcontent//pyagent current=
INFO: Running /var/lib/cattle/download/pyagent/pyagent-1-9e3dcab12585149a65d818082279708965cd826df1937a55b24f48428f8f0c0644fc1033b5be15c88dcf9540b1c04c67/apply.sh
INFO: Updating host-api
INFO: Downloading http://acmelb-00000000.eu-west-1.elb.amazonaws.com/v1//configcontent//host-api current=
INFO: Running /var/lib/cattle/download/host-api/1-9608ead804f8cebbfe95b9f114701d8a5ac4244d603d196068043c902b1a0bdf/apply.sh
INFO: Sending host-api applied 1-9608ead804f8cebbfe95b9f114701d8a5ac4244d603d196068043c902b1a0bdf
INFO: Updating python-agent
INFO: Downloading http://acmelb-00000000.eu-west-1.elb.amazonaws.com/v1//configcontent//python-agent current=
INFO: Running /var/lib/cattle/download/python-agent/1-936086fb3866b781d82a97bdc0832430463ab8b2b33bfbeafd5ecf60d50d0766/apply.sh
INFO: Sending python-agent applied 1-936086fb3866b781d82a97bdc0832430463ab8b2b33bfbeafd5ecf60d50d0766
INFO: Sending pyagent applied 1-9e3dcab12585149a65d818082279708965cd826df1937a55b24f48428f8f0c0644fc1033b5be15c88dcf9540b1c04c67
INFO: Starting agent /var/lib/cattle/pyagent/apply.sh
INFO: Executing /var/lib/cattle/pyagent/agent
INFO: Updating host-config
INFO: Downloading http://acmelb-00000000.eu-west-1.elb.amazonaws.com/v1//configcontent//host-config current=
INFO: Running /var/lib/cattle/download/host-config/host-config-1-5778dfa54a58425eae8d3a0a6ed2028fddefd49194d428d59ef79dfbb887e58c/apply.sh
INFO: HOME -> ./
INFO: HOME -> ./etc/
INFO: HOME -> ./etc/cattle/
INFO: HOME -> ./etc/cattle/api.crt
INFO: Sending host-config applied 1-5778dfa54a58425eae8d3a0a6ed2028fddefd49194d428d59ef79dfbb887e58c
time="2017-03-07T15:39:22Z" level=info msg="Launching agent"
time="2017-03-07T15:39:22Z" level=info msg="http://acmelb-00000000.eu-west-1.elb.amazonaws.com/v12EC30B8108AB906D0E888u8mYVcp8ruDRNPkaKbdGCCCYwYPCDeepftqBPLP"
time="2017-03-07T15:39:22Z" level=info msg="Listening for events on http://acmelb-00000000.eu-west-1.elb.amazonaws.com/v1"
time="2017-03-07T15:39:22Z" level=info msg="launching hostapi"
time="2017-03-07T15:39:22Z" level=info msg="Starting event router."
time="2017-03-07T15:39:22Z" level=error msg="invalid character 'i' in literal false (expecting 'a')"
time="2017-03-07T15:39:37Z" level=error msg="Get http://acmelb-00000000.eu-west-1.elb.amazonaws.com/v1/schemas: net/http: request canceled (Client.Timeout exceeded while awaiting headers)"
time="2017-03-07T15:39:40Z" level=info msg="Initializing event router" workerCount=50
time="2017-03-07T15:39:40Z" level=error msg="Error subscribing to events: websocket: bad handshake" subscribeUrl="ws://acmelb-00000000.eu-west-1.elb.amazonaws.com/v1/subscribe?eventNames=compute.instance.inspect&eventNames=compute.instance.remove&eventNames=storage.volume.activate&eventNames=config.update&eventNames=storage.image.activate&eventNames=storage.volume.remove&eventNames=ping&eventNames=compute.instance.activate&eventNames=compute.instance.deactivate&eventNames=compute.instance.force.stop&eventNames=compute.instance.pull"
time="2017-03-07T15:39:40Z" level=error msg="Got error response" responseHeaders=map[X-Api-User-Id:[1a18] X-Rancher-Version:[v1.4.1] Content-Type:[application/json; charset=utf-8] Expires:[Thu, 01 Jan 1970 00:00:00 GMT] Server:[Jetty(9.2.11.v20150529)] X-Api-Client-Ip:[34.250.254.161] X-Api-Schemas:[http://acmelb-00000000.eu-west-1.elb.amazonaws.com/v1/schemas] Content-Length:[1308] Connection:[keep-alive] Date:[Tue, 07 Mar 2017 15:39:40 GMT] Set-Cookie:

**Comment by dexterddit** [comment]
@smw355  Found something the docs (https://docs.rancher.com/rancher/v1.4/en/installing-rancher/installing-server/#elb) seems to fail on my end . Are there any know issues with this ?

**Comment by superseb** [comment]
@dexterddit Did you enable proxy protocol mode according to the docs? The error implies lack of websocket proxying.

**Comment by superseb** [comment]
Please reply if you still need help with this.

**Comment by dexterddit** [comment]
Nope I`m good  fixed it thanks :)
