### ISSUE TITLE
How to force a container to connect to the service instance on the same host

### ISSUE THREAD

**Issue by stieler-it** [rancher/rancher#8104]
**Rancher Versions:**
Server: v1.4.1
healthcheck: v0.2.3
ipsec: v0.0.4
network-services: v0.0.16
scheduler: v0.4.0
kubernetes (if applicable): -

**Docker Version:** v1.12

**OS and where are the hosts located? (cloud, bare metal, etc):** Ubuntu on OpenStack cloud

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** Single node rancher, internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:**

Simplified: We want to deploy two different containers on every host with a given tag. Container service-a should connect to container service-b that is running **on the same host**.

Approach 1: stack-a contains service-a, stack-b contains service-b, both services have a deployment rule of "all hosts with tag X"
Approach 2: only one stack contains service-a, which has stack-b as a side kick

**Results:** 

With approach 1, when service-b connects to service-a, it seems to connect to **any** instance of service-a. This breaks our scaling model but is probably the expected behaviour?

With approach 2 (which is not optimal because I would prefer to split both services to different stacks as they are built by different people) we experience similar problems. When starting the stack, some of service-b have connected to a service-a on a different host. According to the docs, I would have assumed that side kicks always resolve to their belonging containers. Can this be a timing issue because service-b is loading too fast?

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
