### ISSUE TITLE
Log in Screen UI issues

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#8105]
- [x] Instead of "Username", say "Email Address"
![image](https://cloud.githubusercontent.com/assets/11514927/23724306/73eda490-0409-11e7-9331-1064f7bafdd5.png)

- [x] Clicking on language drop-down, Help Translate Rancher text runs outside of drop-down.  This is really bad in other languages as well.
![image](https://cloud.githubusercontent.com/assets/11514927/23724313/7b405b5c-0409-11e7-9c5f-fe1eb3837ad0.png)

- [x] Howdy message, the space between the lines of text seems especially close
![image](https://cloud.githubusercontent.com/assets/11514927/23724350/9b8b7d06-0409-11e7-9c5a-46810451a632.png)

- [x] Password text is too close to Username box
![image](https://cloud.githubusercontent.com/assets/11514927/23724379/b5827098-0409-11e7-878f-5a90feaefa84.png)

- [x] Too much space between Cloud text and language drop-down.  Same with Password box and Log In button.
![image](https://cloud.githubusercontent.com/assets/11514927/23724446/f70c1186-0409-11e7-95ed-753d4c652209.png)
![image](https://cloud.githubusercontent.com/assets/11514927/23724454/fc8d0f84-0409-11e7-9948-878d3f913158.png)

- [x] Amount of space at top should match the amount of space on bottom.  So the Log in information is centered.  Instead there is more space on bottom then on top. (can this be checked in the Reset password and the Signup screens as well?)
![image](https://cloud.githubusercontent.com/assets/11514927/23724497/2a4852c6-040a-11e7-8767-043c4c8901f9.png)
____________________________________________
![image](https://cloud.githubusercontent.com/assets/11514927/23724510/34667d96-040a-11e7-8c26-096341271a77.png)

- [x] Reset Password screen, the Email address box and reset/cancel buttons are too close
![image](https://cloud.githubusercontent.com/assets/11514927/23724594/8c1bdd60-040a-11e7-816a-2d3fbc62fce7.png)

**Comment by lvuch** [comment]
https://github.com/rancher/ui/pull/1063

**Comment by tfiduccia** [comment]
Version - build on 3/9
Verified all fixed!
