### ISSUE TITLE
Cattle update to call `purge` on secrets api.

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#8109]
In the new version of the Secrets API a user can opt to have secrets stored in Vault backend instead of encrypted in the Rancher MySQL DB. As part of the lifecycle secrets need to be cleaned up/purged from Vault when they are deleted from Rancher.

Two new action endpoints were added:

`/v1-secrets/secrets/purge`
`/v1-secrets/secrets/purge?bulk`

All backends implement the action, you should get a 200 back.

**Comment by ibuildthecloud** [comment]
https://github.com/rancher/cattle/pull/2553

**Comment by galal-hussein** [comment]
Rancher server: master build

`/v1-secrets/secrets/purge` endpoint is not found in the latest master build.

**Comment by deniseschannon** [comment]
@cloudnautique Could you confirm this is working as you needed?

**Comment by cloudnautique** [comment]
Cattle is doing the right thing and calls delete when the secret is deleted.
