### ISSUE TITLE
Add Environment: Environment Templates are missing

### ISSUE THREAD

**Issue by wahmedswl** [rancher/rancher#8110]
**Rancher Versions:**
Server: v1.5.1
healthcheck:v0.2.3
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker Version:**
Docker version 1.12.6, build 78d1802
**OS and where are the hosts located? (cloud, bare metal, etc):**
RancherOS, HyperV
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
Fresh installation of Rancher and then add new Environment
**Results:** 
There is no option to select any template eg Kubernetes/Swarm etc

![image](https://cloud.githubusercontent.com/assets/15020561/23741258/5d761c7c-04c9-11e7-8e6f-1ce9b5479ec1.png)

**Comment by tfiduccia** [comment]
@wahmedswl - I am unable to reproduce your problem.  First can you go to settings and in the Catalog section make sure Rancher Certified Library and Community are enabled?  If not can you enable them and click on save.  If they are, can you disable, save then reenable them?  If the templates are still not showing up.  Can you go into the rancher container logs and see if there are errors?

**Comment by wahmedswl** [comment]
@tfiduccia spin-up new RancherOS VM with Rancher, now can see Environment Templates.
