### ISSUE TITLE
For docker images management

### ISSUE THREAD

**Issue by JermineHu** [rancher/rancher#8111]
Rancher should provide a management  function for docker  images , Thanks a lot!

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.3.3` Cattle: `v0.175.9` UI: `v1.3.5` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`hosts.index`|

**Comment by deniseschannon** [comment]
Duplicate of https://github.com/rancher/rancher/issues/1277
