### ISSUE TITLE
[UI] ui-driver-skel doesn't load - 403 Forbidden

### ISSUE THREAD

**Issue by brunograz** [rancher/rancher#8112]
**Rancher Version:**
**v1.4.1, v1.5.0rc2
Docker Version:
1.12.6
OS and where are the hosts located? (cloud, bare metal, etc):
Ubuntu-Trusty-Tahr-14.04.2-LTS
Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)
single node**

**Steps to Reproduce:**
Clone ui-drive-skel repository.
Change the driver name in package.json.
`npm install`
`bower install`
`npm start `
Add a custom docker machine driver via the UI.
Custom UI URL: http://<gulp_server>:3000/component.json

**Similar Issues:**
#6313

**Results:** 
The Custom UI does not load, instead and error screen displays: "Error loading custom driver UI".
Rancher server was unable to fetch component.css and component.js from the url provided.

![selection_019](https://cloud.githubusercontent.com/assets/8091247/23743332/85aa8aca-04b0-11e7-96c2-7ac4dd3cecb3.png)

**Notes:**
The URL for the custom ui-driver can be accessed from rancher-server container.
I didn't change any file in the ui-driver-skel repo, only the driver name in package.json (to be consistent with the driver added).
The driver options are displayed if I don't provide the Custom UI URL.
I cannot see any incoming connections in the gulp server (debug enabled).

Any pointers on how to solve this issue?

**Comment by brunograz** [comment]
The issue was solved by adding the server address (<gulp_server>:3000) to the "api.proxy.whitelist=" parameter in the advanced settings in the rancher UI.

This was not clear at all in the ui-driver-skel repo documentation which only stated:
"You can run this while developing and point the Rancher settings there."

**Comment by dmportella** [comment]
i am trying this and it is not working for me
