### ISSUE TITLE
Deutsch language doesn't allow delete from UI

### ISSUE THREAD

**Issue by chrisurwin** [rancher/rancher#8113]
**Rancher Versions:**
Server: 1.4.0, 1.5.1
**Steps to Reproduce:**
In the infrastructure view change language to Deutsch, deactivate a host and then click on delete
**Results:** 
An overlay appears but the dialog box for deleting the host doesn't appear so you can't confirm delete.

**Comment by tfiduccia** [comment]
Version - v1.5.1
This is indeed a bug in the dutch language translation. Console error: Uncaught Error: A value must be provided for: isServiceButton

**Comment by janeczku** [comment]
@vincent99 need to put my suggestion in http://translate.rancher.com/translate/rancher-ui/1/enus-de#785

**Comment by tfiduccia** [comment]
Version - 4/26
Verified fixed
