### ISSUE TITLE
Allow updating LDAP configuration without disabling access control

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#8115]
**Rancher Versions:**
Server: 1.4.1

When a user needs to update the LDAP/AD/SAML provider config, e.g. due to password rotation for the Service Account, he should not have to disable Access Control as this will compromise security.

**Comment by junkiebev** [comment]
+1

**Comment by tksd123** [comment]
and is it possible to keep an admin local account in addation to the LDAP accounts ?

**Comment by deniseschannon** [comment]
@tksd123 that's a different enhancement request: https://github.com/rancher/rancher/issues/8740

**Comment by galal-hussein** [comment]
The UI doesn't provide the ability to change the configuration without disabling access control yet.

**Comment by galal-hussein** [comment]
Rancher server: build from version v1.6

I was able to edit and change the configuration for AD without disabling access control.

**Comment by deniseschannon** [comment]
Available in v1.6.8-rc1

**Comment by galal-hussein** [comment]
Rancher server: v1.6.8-rc3

Tested the feature test plan and all tests passed for changing the AD configuration without disabling the authentication.

**Comment by cjellick** [comment]
Hm. @tksd123 This issue being closed and resolved is misleading. It is not (yet) implemented for OpenLDAP, just for AD.

**Comment by tksd123** [comment]
Thx but the title of the issue is quite confusing because it includes "LDAP", so now, we cant edit anything without disabling auth module :(

**Comment by cjellick** [comment]
RIght. So, it is not implemented for OpenLDAP yet. I'll retitle this and open a new issue OpenLDAP
