### ISSUE TITLE
[UI] Rancher agent container name in Hosts screen

### ISSUE THREAD

**Issue by RobertKozak** [rancher/rancher#8116]
**Rancher Versions:**
Server: v1.4.1
healthcheck: n/a
ipsec: n/a
network-services: n/a
scheduler: n/a
kubernetes (if applicable): n/a

**Docker Version:**
n/a
**OS and where are the hosts located? (cloud, bare metal, etc):**
n/a
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
n/a
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**

Adding a new host with provided command like: 
sudo docker run -d --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.2.0 http://rancher1.nowcom.io:8080/v1/scripts/C07E7275B12F11C8F68D:1483142400000:x65SZMEfVxbParEdg8iJfYOvRw

**Results:** 
starts off a container with an arbitrary name and spawns another container called rancher-agent. 
![untitled](https://cloud.githubusercontent.com/assets/85093/23762227/3aae5b2e-04aa-11e7-88e7-41d2faa6aea8.png)
1. the original container doesn't have a proper name and looks confusing sitting there
2. the original container is stopped and marked in a red circle making it look unnecessary
3. should it be marked green indicating its healthy or removed altogether. or given a proper name to indicate its purpose.

**Comment by deniseschannon** [comment]
This is exactly as expected. The red circle container is not necessary and can be deleted, but you would need to delete it yourself. When rancher agent launches it spins up a new container that is actually named `rancher-agent`.

**Comment by RobertKozak** [comment]
Ok this begs the question why we need to delete it manually? Why isn't the --rm flag used in the original command to setup a host?
