### ISSUE TITLE
Rancher agent deletes existing agent and respawns new one without testing first if required

### ISSUE THREAD

**Issue by RobertKozak** [rancher/rancher#8117]
**Rancher Versions:**
Server: v1.4.1
healthcheck: n/a
ipsec: n/a
network-services: n/a
scheduler: n/a
kubernetes (if applicable): n/a

**Docker Version:**
n/a
**OS and where are the hosts located? (cloud, bare metal, etc):**
n/a
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
n/a
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**

run the command below more than once: 
sudo docker run -d --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.2.0 http://rancher1.nowcom.io:8080/v1/scripts/C07E7275B12F11C8F68D:1483142400000:x65SZMEfVxbParEdg8iJfYOvRw

**Results:** 
If there is already an existing running rancher/agent is will delete the rancher/agent and spawn a new one. There should be a test to see if the correct version is already running and not delete and recreate. 
Since the rancher agent should be idempotent it needs to make a test first to see if necessary to delete and restart.

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
