### ISSUE TITLE
URL for external link not resolving inside a container but does resolve on the rancher host.

### ISSUE THREAD

**Issue by sebradloff** [rancher/rancher#8118]
**Rancher Versions:**
Server: v1.4.1
healthcheck: v0.2.3
ipsec:  image: rancher/net:holder (latest?)
network-services: network-manager:v0.4.5 & metadata:v0.7.0
scheduler: v0.6.3

**Docker Version:**
1.12.6
**OS and where are the hosts located? (cloud, bare metal, etc):**
VMs on bare metal
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Rancher server in it's own VM with rancher agents in their own VMs.
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
No idea on how to reproduce, but for some reason our external DB connection strings are not resolving on a very specific rancher agent. To reiterate, we are attempting to connect to a database that is external to our rancher setup and hosted elsewhere. We do have resolution for the database connection string on all the rancher agents themselves. However, on one specific agent, when we execute a shell into any of the containers on that agent, the DB connection string can NOT resolve. 

I went through the network troubleshooting docs: http://docs.rancher.com/rancher/v1.5/en/faqs/troubleshooting/#cross-host-communication
and was reading up on the networking docs: http://docs.rancher.com/rancher/v1.5/en/rancher-services/networking/

We do NOT have any custom rancher network configuration, we are using the default managed option.

Is there a reason why the containers on one specific host would have different network configurations than any other host? Are there any commands/steps we can run to confirm this difference?

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
