### ISSUE TITLE
FR: Automatic service rollback on failed healthcheck

### ISSUE THREAD

**Issue by LarsKumbier** [rancher/rancher#8119]
The current process of upgrading a service involves a manual check of the upgraded service and to manually confirm the upgrade to be successful. This is soooo 2016! ;)

I propose to use the custom healthcheck functionality already in the roadmap to allow Rancher to confirm the upgrade by itself through an option toggle in the service definition. That way, a developer team could setup a CD-pipeline, in which 

* a developer would inform Rancher on an upgrade wish
* Rancher would start the upgrade process by pulling in the new image and upgrading the service
* run the custom health check provided in the rancher-compose.yml.
* if the healthcheck failes,
* it would automatically start the rollback

This would be great for teams having a good test coverage and a high confidence in their pipeline.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
