### ISSUE TITLE
LDAP/AD provider should support separate search bases for users and groups

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#8122]
**Rancher Versions:**
Server: 1.4.1

**Steps to reproduce**

Given a AD where users and groups have distinguished names in the form of:

user DN: `CN=user-foo,OU=Employees,OU=Acme Users,DC=acme,DC=com`
group DN: `CN=group-bar,OU=Standard,OU=Acme Groups,DC=acme,DC=com`

setup access control with the AD backend.

**Actual:**

User has to configure the AD provider with the very broad search base `DC=acme,DC=com` so that both user and group lookups will work.
This causes problems where
1) The AD server does not allow queries with a broad search base
2) There are multiple objects under the broad search base that match the user/group identifier (This will break LDAP authentication).

**Expected:**

User should be able to configure a separate "search base" for Groups in the LDAP/AD access control provider. This would be an optional setting which defaults to the current (global) search base setting for backwards compatibility.

(User) search base: `OU=Employees,OU=Acme Users,DC=acme,DC=com`
Group search base: `OU=Standard,OU=Acme Groups,DC=acme,DC=com`

**Comment by mrajashree** [comment]
The same search base is used for users and groups in AD.
For this issue https://github.com/rancher/rancher/issues/8122, a new field called group search base will be added. 
1. It will be a comma separated list like the `Search Base` and its default value will be same as the search base
2. It can be an additional field for `Groups` under `Customize Schema`
![schema](https://cloud.githubusercontent.com/assets/10672776/23877284/d13e4e30-07fe-11e7-9f36-6b1ae8caf034.png)
3. `ADConfig` has a field called `domain` corresponding to the `Search Base` in UI. One more field called `groupDomain` will be added for the `Group Search Base` field. `searchIdentities` in `LDAPIdentityProvider` will lookup the `groupDomain` for groups.

**Comment by deniseschannon** [comment]
When testing, please make sure to not only test the enhancement, but upgrading from a 1.5 setup to a new setup.

**Comment by galal-hussein** [comment]
Rancher server: master build
I tested various test cases including:

```
1- In Rancher LDAP authentication set the search domain and the and group search domain to none try to add  a group outside of the user search domain to an environment, you should not be able to add this group.

2- In Rancher LDAP authentication set the search domain to a domain different than the group search domain, now try to add a group that belong to the same organizational unit of the group search domain, you should be able to add this group normally.

3- In Rancher LDAP authentication set the search domain to more wider domain and group search domain to a subset of this domain, now you should be able to add the group that only belong to the subset domain and not any group outside this subset.

4- In Rancher LDAP authentication set the search domain to a domain different than the group search domain, you should be able to add users normally that belong to user domain to an environment .
```

@mrajashree I didn't find any issues so far, however the UI doesn't have the group search domain field yet.

**Comment by mrajashree** [comment]
@galal-hussein thanks, yes the UI isn't done yet. Assigning it over.

**Comment by tfiduccia** [comment]
Version - master 4/27
Verified fixed

**Comment by galal-hussein** [comment]
Tested LDAP group search base domain with upgraded setup from Rancher 1.5.8 to 1.6.0-rc6, no issues found.
