### ISSUE TITLE
UI: Orphaned configuration settings on Active Directory configuration page

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#8123]
**Rancher Versions:**
Server: 1.4.1

The following two settings are visible on the AD access control provider setup page but they have no effect since the API `ldapconfig` resource does not have these attributes:

- "Group Member User Attribute" (groupMemberUserAttribute)
- "Group DN Field" (groupDN)

**Comment by vincent99** [comment]
These both exist in 1.6.[something]+
