### ISSUE TITLE
Log in Screen UI issues #2

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#8124]
**Issues:**

- [x] Signup header text is too close together.  Basically the Cloud text below rest of text looks crowded.
![image](https://cloud.githubusercontent.com/assets/11514927/23771050/c787166c-04d2-11e7-97b3-3772971febec.png)

- [x] When clicking on Create Account, the Create Account modal jumps up and is no at the same height as the Log In and the Reset Password modal.
![image](https://cloud.githubusercontent.com/assets/11514927/23771192/4d51abc2-04d3-11e7-9b54-830cf2b8fc12.png)
![image](https://cloud.githubusercontent.com/assets/11514927/23771186/4616f9b6-04d3-11e7-9cf2-567cd6eed56c.png)

- [x] All other languages "Help Translate Rancher" text is bleeding out of drop-down.
![image](https://cloud.githubusercontent.com/assets/11514927/23771267/9661a696-04d3-11e7-8b02-d7de79ee1b15.png)

- [x] Drop-down button and drop-down list are not aligned
![image](https://cloud.githubusercontent.com/assets/11514927/23771308/be078a08-04d3-11e7-954c-bd7c4cd610da.png)

- [x] Drop-down list has weird grey strip at top and bottom
![image](https://cloud.githubusercontent.com/assets/11514927/23771337/d8e30bc2-04d3-11e7-9149-61fcf116ed8e.png)

- [x] Drop-down list has grey space between translate and Deutsch items.  I guess this might be on purpose, but it kinda looks weird.
![image](https://cloud.githubusercontent.com/assets/11514927/23771387/f626c69c-04d3-11e7-823e-4383eecebdd9.png)

- [x] There are double lines between languages in the language drop-down and only single on the border.  Should be same thickness.
![image](https://cloud.githubusercontent.com/assets/11514927/23770934/5419dab6-04d2-11e7-8ca4-08f1414c22d0.png)

**Comment by lvuch** [comment]
https://github.com/rancher/ui/pull/1065

**Comment by tfiduccia** [comment]
Version 4/5
Verified fixed
