### ISSUE TITLE
Inconsistent UI behavior on selecting Host Registration URL

### ISSUE THREAD

**Issue by oskapt** [rancher/rancher#8126]
In a new installation, when adding the first host, Rancher asks for the Host Registration URL. Selecting the text box for "Something Else" and beginning to type does not change the radio button from the first option to the second option.

Later, after installation, in Settings, when changing the Host Registration URL, entering text in the "Something Else" box _does_ change the radio button. 

I was familiar with the latter, so when creating a new Rancher env, I didn't notice that entering a custom host registration url in the box didn't actually change the setting.

**Rancher Versions:**
Server: 1.4.1

**Docker Version:** 1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):** EC2

**Setup Details: ** single node

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** N/A

**Steps to Reproduce:**

1. create new rancher server
2. begin to add new host
3. when presented with Host Registration URL page, enter text in the text box for "Something Else"
4. note that the radio button does not change
5. save
6. go to Settings
7. note that the host registration url did not change
8. click in the text box and begin to type
9. note that the radio button changes and the warning appears

**Expected behavior:** 

1. the radio button should change when text is entered in the box in all instances where this content is displayed.

**Comment by vincent99** [comment]
Changed in 2.0 (possibly 1.x somewhere..)
