### ISSUE TITLE
Kubernetes dashboard link returns 404

### ISSUE THREAD

**Issue by ryanwalls** [rancher/rancher#8128]
Rancher Versions:
Server: 1.4.1
healthcheck: v0.2.3
ipsec: rancher/net:holder
network-services: rancher/network-manager:v0.4.5
scheduler: rancher/k8s:v1.5.2-rancher1-4
kubernetes (if applicable): v1.5.2-rancher1-4

Docker Version:
1.12.6

OS and where are the hosts located? (cloud, bare metal, etc):
Ubuntu on AWS EC2 instances

Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)
single node rancher with external RDS database

Environment Type: (Cattle/Kubernetes/Swarm/Mesos)
Kubernetes

**Steps to Reproduce:**
* Setup regular k8s environment

**Results:** 
* Spontaneously, rancher has stopped serving up the k8s api.  All calls to the k8s api fail with this message: 
```
error: couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
```
* Dashboard page also returns a 404.

**Comment by ryanwalls** [comment]
![image](https://cloud.githubusercontent.com/assets/842653/23777479/480775ec-04f2-11e7-831a-c8b6b8e6ccba.png)

**Comment by tsublette** [comment]
+1

**Comment by vincent99** [comment]
What's odd is that's an error screen from the UI but `/r/projects/...` should be responded to by the API.  Instead it's apparently sending back the index.html which causes the UI to load (and then that's not a route it knows so it shows 404).

What's doing the SSL termination and/or balancing?  ALB?  We've seen weird unreproducible issues with ALB that only go away by recreating another balancer with exactly the same settings, and have gone back to recommending ELB.

**Comment by ryanwalls** [comment]
Will give it a shot and report back.

**Comment by ryanwalls** [comment]
@vincent99 No luck with new ALB.  Trying ELB.

**Comment by ryanwalls** [comment]
@vincent99 ELB made kubectl start working again.  Unfortunately, UI just spins and spins.  Never loads.  Restarting rancher server now...

**Comment by ryanwalls** [comment]
Got it all working with an ELB.  Closing.  Thanks @vincent99!

**Comment by karthik101** [comment]
@ryanwalls I have the same issue with rancher/server:v1.6.11, even kubectl isnt working, i run rancher server on one node and a single agent on another node. Creating elb for a server node has no effect. Do i need an elb for single node ?
Previously it used to work out of the box with different rancher/server.

**Comment by superseb** [comment]
@karthik101 This is over 8 months old. You don't need a LB if you can connect directly to the`rancher/server` container, but if you are using it, you need a properly configured ELB. Can you open a new issue with the description of your setup and error logging?

**Comment by karthik101** [comment]
It was a port issue, resolved. Thanks.
