### ISSUE TITLE
Not able to upgrade catalog stack with global labels

### ISSUE THREAD

**Issue by jmreicha** [rancher/rancher#8129]
**Rancher Versions:**
Server: 1.5.1
healthcheck: v0.2.3
ipsec: rancher/net:holder
network-services: v0.8.11
scheduler: v0.7.4

**Docker Version:** 1.13

**OS and where are the hosts located? (cloud, bare metal, etc):** AWS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**HA External DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:**

1) Create a stack from a catalog that doesn't do any global scheduling
2) Update the catalog entry to use global scheduling
3) Click the Upgrade button in the Rancher UI

**Results:** 

The upgrade hangs, and never actually finishes.  It isn't clear in the Rancher UI what exactly is happening.  I had to pull logs out of the Rancher server, they show the following error:

```
time="2017-03-10T00:46:32Z" level=error msg="Stack Upgrade Event Failed: Bad response statusCode [422]. Status [422 status code 422]. Body: [code=InvalidOption, baseType=error, fieldName=Switching from global scale to fixed (and vice versa)] from [http://localhost:8080/v2-beta/projects/1a7/services/1s139/?action=upgrade]" eventId=xxx resourceId=xxx
```

**Comment by vincent99** [comment]
We should be able to surface that message better, but as it says changing an existing service to or from global is not supported.

**Comment by jmreicha** [comment]
It's okay with me, as long as it's easy to see what went wrong and why.

**Comment by Caspain** [comment]
Same here io.rancher.scheduler.global: 'true' wont work, only custom labels

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
