### ISSUE TITLE
Error validating AWS Access & Secret keys to provision Instances

### ISSUE THREAD

**Issue by samhitha30** [rancher/rancher#8130]
**Rancher Versions:1.5.1
Server:
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker Version:**

**OS and where are the hosts located? (cloud, bare metal, etc):Cloud - AWS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** Single Node

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Kubernetes

**Steps to Reproduce:** Add Kubernetes Environment, Go to Add hosts, then provide AWS requirements (Access keys and Secret Keys), you will get error as 

Rancher-KubeHost-Tokyo
Error setting machine configuration from flags provided: AuthFailure: AWS was not able to validate the provided access credentials

**Results:** 
Error setting machine configuration from flags provided: AuthFailure: AWS was not able to validate the provided access credentials

**Comment by deniseschannon** [comment]
It sounds like your credentials were invalid. I am able to spin up EC2 instances in the Tokyo region.

**Comment by samhitha30** [comment]
Hi @deniseschannon ,

Thank you for updating me that you were successfully provisioned EC2 instances using Rancher UI. But, still i am getting same error.

i tried US-EAST-1, sa-east-1 and ap-northeast-1 with ubuntu 14.10, 16.10 and RancherOS. but i got no luck.

Please find error info i am getting at Rancher UI and help me to fix it. Presently we are evaluating Rancher to propose for one of our potential Customer.

Error ...

ERROR
Rancher-SauPoulo-KubeHost
Error setting machine configuration from flags provided: AuthFailure: AWS was not able to validate the provided access credentials
 
ERROR
Rancher-Tokyo-KuberHost1
Error setting machine configuration from flags provided: AuthFailure: AWS was not able to validate the provided access credentials
 
ERROR
Rancher-Tokyo-KuberHost2
Error setting machine configuration from flags provided: AuthFailure: AWS was not able to validate the provided access credentials

**Comment by deniseschannon** [comment]
The error means that your AWS credentials (access key and secret key) are incorrect.

There is nothing that Rancher can do in that case. You can try to validate your credentials using AWS CLI.

**Comment by samhitha30** [comment]
Hi @deniseschannon ,

i can confirm that i don't have issues with my AWS account. i've used my access keys and secret keys to provision instances using Cli..

PFB the cli script i used in sa-northeast-1 (sau-paulo) region

aws ec2 run-instances --image-id ami-f9daac96 --count 1 --instance-type t2.micro --key-name Windows_Terraform --security-groups Windows_Terraform

i guess there is an issue with Rancher 1.5.1.

recently i upgraded my rancher version from 1.1.0 to 1.5.1 and from there it has these kind of issues.

Please help me to get it fixed

**Comment by deniseschannon** [comment]
I have not been able to have anyone reproduce your issue on v1.5.1. Everyone has been able to launch hosts. 

When exactly are you getting the error? Is it when you step through the UI screens or after you try to launch the actual machine?

Are you sure there is no white space before or after your access key/secret key?

**Comment by byavv** [comment]
Sometimes it happens, when your system time is broken.

**Comment by vincent99** [comment]
@byavv yes that is a good one to point out.

The authorization for AWS is based on signing  the request text, which includes the clients idea of the current time.  So if the client (web browser/your computer) or server (transfer/server container's host) are off the correct time by more than 5 minutes authorization well fail.

**Comment by samhitha30** [comment]
got it.

my setup is working fine now after re-running rancher server Image with stable tag. Thanks for your support @deniseschannon , @vincent99 @byavv

**Comment by superseb** [comment]
Closing as solved.

**Comment by rex** [comment]
> Sometimes it happens, when your system time is broken.

To any future frustrated wanderers, do yourselves a favor and *check this first*. I was stuck for nearly an hour until checking this (thanks to @byavv above) and it resolved all my issues instantly. On modern ubuntu the command `timedatectl status` should show a line containing 

```
System clock synchronized: yes
```

If it doesn't, or if you're on another distro, look at this ServerFault answer that resolved all my problems: [Force systemd timesyncd to sync time with NTP server immediately](https://serverfault.com/a/972336/135581)
