### ISSUE TITLE
how do i add CNI frame work in rancher?

### ISSUE THREAD

**Issue by asdarunasd** [rancher/rancher#8132]
i want to try CNI framework in rancher cause i want only one ip address to be exposed from the container build through rancher?

**Rancher Versions:**
Server:  1.5.1
healthcheck: yes
ipsec:yes
network-services:yes
scheduler:
kubernetes (if applicable):

**Docker Version:**
1.12.6
**OS and where are the hosts located? (cloud, bare metal, etc):** baremetal

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single node rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
cattle
**Steps to Reproduce:**

**Results:**

**Comment by leodotcloud** [comment]
@asdarunasd if you have started a cluster using 1.5.1 release and launched a container either in standalone mode or using services/stacks, there will only be one IP address assigned for the `eth0` interface.

If you were using using the `docker run` command, then you need to pass one additional argument and label to work with CNI.

```
docker run --name testcni --net=none --label io.rancher.container.network=true -itd nginx
docker exec -it testcni bash
ip addr
```

Please let me know if you have more questions.

**Comment by deniseschannon** [comment]
The CNI framework is part of the infrastructure services started in an environment, so as @leodotcloud mentioned, starting any contianer would be using it.
