### ISSUE TITLE
Pre-define rancher loadbalancer name

### ISSUE THREAD

**Issue by hiscal2015** [rancher/rancher#8134]
Rancher Versions: 1.5.0

Docker Version: 1.12.6

OS and where are the hosts located? (cloud, bare metal, etc): Ubuntu16.04

Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB) single

Environment Type: (Cattle/Kubernetes/Swarm/Mesos) Kubernetes

Steps to Reproduce:

When creating a rancher loadbalancer either from Kubernetes ingress or Kubernetes loadbalancer service, we can't control the name of LB, can we pre-define the name so we can have the fixed DNS record?

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
