### ISSUE TITLE
Request: Hardening instructions

### ISSUE THREAD

**Issue by btro** [rancher/rancher#8135]
A dedicated hardening guide or tips for Rancher(OS) would be great. A central and up to date write up would help newcomers and even other users to check if they have Rancher(OS) set up correctly and securely.

Thoughts?

**Comment by bacheson** [comment]
Check the rancher-bench-security catalogue app

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
