### ISSUE TITLE
Not able to get lbs's working for two ingress in two different k8s namespaces

### ISSUE THREAD

**Issue by ohullv** [rancher/rancher#8136]
Hello, I have a kubernetes-rancher 1.4.1, the problem is I am creating two ingress in two different k8s namespaces and have a label filter to use the same two hosts for the lbs's, the second lbs got the error "Allocation failed: needs host with label infrastructurelayer: true)"
It would be okay if I used only one k8s ingress, but it won't let me specify the namespace for every specific service  in the rules

**Rancher Versions:**
Server: 1.4.1
healthcheck:0.2.3
ipsec:holder
network-services:0.4.5
scheduler:
kubernetes (if applicable):

**Docker Version:**
1.12.3
**OS and where are the hosts located? (cloud, bare metal, etc):**
bare metal

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher, ext db
Kubernetes**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**

**Results:** 
Allocation failed: needs host with label infrastructurelayer: true)

**Comment by deniseschannon** [comment]
Do you have example ingress files that i could look at?

**Comment by superseb** [comment]
Please comment if you still need help with this.
