### ISSUE TITLE
Support for choosing docker version - 17.03.0-ce when adding Docker Machine hosts.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#8138]
**Rancher Versions: v1.5.1

Steps to reproduce the problem:
Add a host (using docker machine) . 
If user does not set ```Docker install version``` In "Advanced Options" tab, host gets docker 1.12.6 by default.
In "Advanced Options" tab , Docker install version - https://releases.rancher.com/install-docker/1.13.sh is available ,which installs docker 1.13.1
There is no way to choose - docker version - 17.03.0-ce specifically.
We are able to get  docker version - 17.03.0-ce by specifying  ```Docker install version`` to http://get.docker.com

**Comment by StrongMonkey** [comment]
@deniseschannon @sangeethah I believe this is added recently by @vincent99 https://github.com/rancher/install-docker

**Comment by deniseschannon** [comment]
@StrongMonkey You're right, it's just adding it in the UI.

**Comment by tfiduccia** [comment]
Version 4/26
This is not in the UI drop-down
![image](https://cloud.githubusercontent.com/assets/11514927/25461005/61b320c6-2a9b-11e7-9ed6-88c1198a79ab.png)

**Comment by deniseschannon** [comment]
In master, but not v1.6.0-rc1.

**Comment by tfiduccia** [comment]
I'm still not seeing it in the drop-down list

**Comment by tfiduccia** [comment]
Version - master 4/27
Verified fixed
