### ISSUE TITLE
network-manager wouldnt initialize because proxy was blocking rancher-metadata

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#8141]
**Rancher Versions:**
Server:v1.5.1
**Docker Version:**
1.12.6
**OS and where are the hosts located? (cloud, bare metal, etc):**
RHEL 7.3 ESXi VM

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
cattle/proxy between hosts and internet

**Steps to Reproduce:**
Create a cattle environment

**Results:** 
Failed at bringing up network-manager. @ibuildthecloud believed this should be avoidable.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
