### ISSUE TITLE
Kubernetes will not remove dead add-on containers

### ISSUE THREAD

**Issue by hiscal2015** [rancher/rancher#8143]
Rancher Versions: 1.5.0

Docker Version: 1.12.6

OS and where are the hosts located? (cloud, bare metal, etc): Ubuntu16.04

Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB) single

Environment Type: (Cattle/Kubernetes/Swarm/Mesos) Kubernetes

**Steps to Reproduce:**

1) Create a new Kubernetes environment
2) Add the first host (e.g. named host1) to this environment
3) Kubernetes master containers will be started on host1 including controller manager, scheduler, etc... and the add-on starter will create dashboard, tiller, heapster and some other containers on host1
4) Proceed to add host2 and host3 to this environment
5) Now force shutdown host1, after a while, Kubernetes master role containers and add-on containers will failover to host2 or host3
6) Rancher will remove the dead Kubernetes master role containers after they're running on host2 or host3, but for dead add-on containers, they're still dead in there, see below picture, is this an expected behavior or an issue? Do I have to remove them manually? Thanks.
![k8sstoppedcontainers](https://cloud.githubusercontent.com/assets/15604715/23820976/bd1fb604-0660-11e7-928a-a5950ffa3ea3.jpg)

**Comment by deniseschannon** [comment]
Correct, this is expected behavior. Rancher will not automatically remove the add-on containers.
