### ISSUE TITLE
kube-apiserver doesn't start in user modified stack

### ISSUE THREAD

**Issue by Dmitry1987** [rancher/rancher#8146]
**Rancher Versions:**
Server: 1.4.1
kubernetes (if applicable): 1.5.2 (latest from catalog)
AWS.

**Steps to Reproduce:**
Create Kubernetes environment, add host, wait until all ready, export config (the 2 yml files).
**Results:** 
Create Cattle environment, use "new stack" to upload exported configs (with slight changes like etcd external URL or whatever else that you might need).
The kube-apiserver will not start with this kind of issue:

```
3/12/2017 7:08:52 PM+ CATTLE_ACCESS_KEY=XXXXXXXXXXXXX
3/12/2017 7:08:52 PM+ CATTLE_SECRET_KEY=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
3/12/2017 7:08:52 PM+ curl -s -f http://rancher-metadata/2015-12-19/stacks/Kubernetes/services/kubernetes/uuid
3/12/2017 7:08:52 PM+ /usr/bin/update-rancher-ssl
3/12/2017 7:08:52 PM++ curl -s http://rancher-metadata/2015-12-19/stacks/Kubernetes/services/kubernetes/uuid
3/12/2017 7:08:52 PM+ UUID=eadee54f-5129-4481-b1d5-cfaeeefc0df8
3/12/2017 7:08:52 PM++ curl -s -u XXXXXXXXXXXXXX:XXXXXXXXXXXXXXXXXXXXXXXX 'http://rancher-url.example.com:8080/v1/services?uuid=eadee54f-5129-4481-b1d5-cfaeeefc0df8'
3/12/2017 7:08:52 PM++ jq -r '.data[0].actions.certificate'
3/12/2017 7:08:52 PM+ ACTION=null
3/12/2017 7:08:52 PM+ KUBERNETES_URL=https://kubernetes.kubernetes.rancher.internal:6443
3/12/2017 7:08:52 PM+ '[' -n null ']'
3/12/2017 7:08:52 PM+ mkdir -p /etc/kubernetes/ssl
3/12/2017 7:08:52 PM+ cd /etc/kubernetes/ssl
3/12/2017 7:08:52 PM+ curl -s -u XXXXXXXXXXXXXXX:XXXXXXXXXXXXXXXXXXXXX -X POST null
```

The problem happens on this step:
``` 
curl -s -u http://rancher-url.example.com:8080/v1/services?uuid=eadee54f-5129-4481-b1d5-cfaeeefc0df8
```
it has to extract the "ACTION" string which in healthy k8s environment looks like:
```
ACTION='http://rancher-url.example.com:8080/v1/services/1s836/?action=certificate'
```

instead it gets "null" as a result of this curl command piped through jq.

related part in /usr/bin/entry.sh is:

```
UUID=$(curl -s http://rancher-metadata/2015-12-19/stacks/Kubernetes/services/kubernetes/uuid)
ACTION=$(curl -s -u $CATTLE_ACCESS_KEY:$CATTLE_SECRET_KEY "$CATTLE_URL/services?uuid=$UUID" | jq -r '.data[0].actions.certificate')
```

I have verified the CATTLE_ACCESS_KEY and CATTLE_SECRET_KEY  are good, (at the beginning was trying to overwrite them suspecting automatic keys propagation into container env vars is bad).

so my question is: why '.data[0].actions.certificate'  doesn't exist?  
what I see in this JSON response ".data[0].actions" section is:

```
      "actions": {
        "rollback": "http://rancher.example.com:8080/v1/services/1s907/?action=rollback",
        "remove": "http://rancher.example.com:8080/v1/services/1s907/?action=remove",
        "finishupgrade": "http://rancher.example.com:8080/v1/services/1s907/?action=finishupgrade",
        "removeservicelink": "http://rancher.example.com:8080/v1/services/1s907/?action=removeservicelink",
        "addservicelink": "http://rancher.example.com:8080/v1/services/1s907/?action=addservicelink",
        "setservicelinks": "http://rancher.example.com:8080/v1/services/1s907/?action=setservicelinks"
      },

```

any ideas why this works when out of the box "kubernetes" environment is created, but creating the same from "exported config" doesn't work?    I expected to be able to export and modify the infrastructure stack.

**Comment by rebhisaid** [comment]
+1

**Comment by superseb** [comment]
Closing as stale.
