### ISSUE TITLE
how to get rancher internal dns server ip?

### ISSUE THREAD

**Issue by askie** [rancher/rancher#8148]
where use nginx, some error just like: Upstream server temporarily disabled
the problem just like this : http://forum.predix.io/questions/1774/upstream-server-temporarily-disabled.html

I have to fix this by config nginx to add resolver [dns server ip]:  https://tenzer.dk/nginx-with-dynamic-upstreams/

how to get rancher internal dns server ip?
Is it rancher internal dns server ip is Dynamically generated ？
 
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.5.1` Cattle: `v0.177.8` UI: `v1.5.7` |
|Access|`github` `admin`|
|Orchestration|`Cattle`|
|Route|`service.containers`|

**Comment by HenryTheSir** [comment]
resolver 169.254.169.250 valid=5s ipv6=off;

this works for us

**Comment by askie** [comment]
@HenryTheSir  thx
I find it in the container /etc/resove.conf, It is the same with yours.
Is this 169.254.169.250  static or Dynamically generated ?

**Comment by vincent99** [comment]
It is static and connects to the DNS container running on that host.
