### ISSUE TITLE
Network barrier after upgrade service if "retain ip" is checked

### ISSUE THREAD

**Issue by FullTS** [rancher/rancher#8149]
**Rancher Versions:**
1.5.1
Server: latest
healthcheck: latest
ipsec: latest
network-services: latest
scheduler: latest
kubernetes (if applicable):

**Docker Version:**
1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):**
CentOS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Upgrade Service A, check Network > Retain IP.
Once service A is upgraded, 
ping serviceA in serviceB, can resolve IP, but cannot got any return.
It can't work even ping the IP.

**Results:**

**Comment by tfiduccia** [comment]
@FullTS 

I cannot reproduce your issue.  Here are my steps:

1.  Create a stack and add two services, service1 and service2
2.  Go to service2 and ping service1 ip
3.  Upgrade service1 and check retainIP
4.  Finish upgrade for service1 and go to service2 shell and ping service1 IP

I pinged service1 and got a response.

**Comment by leodotcloud** [comment]
@FullTS please create a new issue if you are still having a problem.
