### ISSUE TITLE
Environment variables not replaced

### ISSUE THREAD

**Issue by raphink** [rancher/rancher#8152]
When upgrading a stack with a new variables, the old ones are kept and merged instead of being replaced. As a result, there is no way to deprecate old variable in a stack upgrade.

**Comment by deniseschannon** [comment]
How are you trying to upgrade the stack?

**Comment by raphink** [comment]
@deniseschannon using catalog templates.

**Comment by deniseschannon** [comment]
Can you share your compose files?

**Comment by raphink** [comment]
It doesn't have to do with compose files, but with catalog templates. If a new version of an existing catalog template has dropped variables, these variables are not removed from the stack.

**Comment by deniseschannon** [comment]
Catalog templates are comprised of compose files. It would help for me to understand what "variables" you are speaking of. 

Are you talking about the variables that are part of configuration options of templates? 

Are you talking about environment variables of a container?

**Comment by raphink** [comment]
I'm talking about the variables from the `.catalog` section in `rancher-compose`, that get fed into `answers.txt` in a catalog template. When a new version of the template drops one of these variables, the new variable does not appear in the UI form, but the value is still stored in the API.

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
