### ISSUE TITLE
Allow to switch from fixed scale to global, and vice versa

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#8159]
Today we disallow switching from fixed scale to global, and the other way around. We should remove this limitation (requires some fixes in  Global/Default service planners)

**Comment by lachnerd** [comment]
Any news here ?
I see this Issue exists for over one year and it is still unscheduled.
Would be a very helpful feature for a small and special problem.

**Comment by alena1108** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches
