### ISSUE TITLE
change to kubernetes Environment page response empty

### ISSUE THREAD

**Issue by tangxusc** [rancher/rancher#8162]

**Comment by deniseschannon** [comment]
@tangxusc Can you give some more details on what you are trying to do and what version of Rancher you are running?

**Comment by tangxusc** [comment]
my step:
1.docker run -d --restart=always -v /rancher/db:/var/lib/mysql --name rancher-server -p 8888:8080  rancher/server
2.Manage Environments-->Add Environment(Environment Template is kubernetes)
3.Switch to new Environment
4.Browser does not display content
------------------rancher version--------------------
Rancher 	v1.4.2
Cattle 	v0.176.10
User Interface 	v1.4.9
Rancher CLI 	v0.4.1
Rancher Compose 	v0.12.2

**Comment by tangxusc** [comment]
I restart rancher, the page can be displayed

**Comment by tangxusc** [comment]
I modified the language settings for Chinese, there is no page content
I will change the language into English, the page will appear content

**Comment by vincent99** [comment]
This was a broken translation in Chinese in some version and resolved in current releases.
