### ISSUE TITLE
Not able to send emails

### ISSUE THREAD

**Issue by dalareo** [rancher/rancher#8163]
**Rancher Versions:**
Server: v1.5.1
healthcheck: 
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker Version:**
17.03.0-ce

**OS and where are the hosts located? (cloud, bare metal, etc):**

Ubuntu 16.04 - Bare metal

**Setup Details: single node rancher**
**Environment Type: Cattle**

**Steps to Reproduce:**
If I set UI_MODE as "caas" some features related to container cloud are enabled but when I try to register an user from the UI after setting Sendgrid API Key
**Results:** 
No email is send and I get an error:

statuscode is undefined

**Comment by vincent99** [comment]
You're going to not want to be on master for a while.. I am not going to be getting into user support of unreleased things in master of the UI, but there are various other settings which must be set to define the templates to use in your sendgrid account. And you need to be running the UI as an actual node server.

**Comment by dalareo** [comment]
Thanks @vincent99 !!
