### ISSUE TITLE
Health Check in Templates not working

### ISSUE THREAD

**Issue by KuroObi** [rancher/rancher#8164]
**Rancher Versions:**
Server: v1.5
healthcheck: v0.2.3
network-services: v0.8.11
scheduler: v0.7.4
kubernetes (if applicable):

**Docker Version:**
17.03.0-ce

**OS and where are the hosts located? (cloud, bare metal, etc):**
bare metal (debian 8 (4.9.0)

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single rancher master, 10 rancher agents, external MySQL

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
I add a Health Check to one of my Services, export them and build the Health Check into my Template.
Than i refresh my Templates (in the preview of the templates the Health Check is still visible)
I start up my new Stack, and in the config there are no more Health Checks.

**Results:** 
Can't add Health Checks to my templates

**Comment by deniseschannon** [comment]
Would you be able to share what your catalog looks like so I could test it out?

**Comment by KuroObi** [comment]
sure, here is the part with the health check

services:
  elasticsearch-master:
    scale: 1
    start_on_create: true
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 9200
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      request_line: GET "_cluster/health" "HTTP/1.0"
      reinitializing_timeout: 60000

**Comment by deniseschannon** [comment]
And you are launching a brand new stack, not trying to upgrade, correct?

**Comment by KuroObi** [comment]
i solved the issue, my fault.
