### ISSUE TITLE
Host labels mix ro and rw informations

### ISSUE THREAD

**Issue by raphink** [rancher/rancher#8165]
Host labels are currently a mix of "read-only" (undocumented) and read-write informations.

As of rancher-agent 1.2, 4 computed labels are currently returned:

* io.rancher.host.agent_image
* io.rancher.host.docker_version
* io.rancher.host.kvm
* io.rancher.host.linux_kernel_version

## What I expect

The labels API should let me specify additional labels (configuration, such as `io.rancher.host.external_dns_ip`) without altering internal data

## What happens

If I use the API to manage additonal labels, it removes automatic labels that are computed from host informations.

**Comment by vincent99** [comment]
They're not read-only, actually special in any way, or used by us for much of importance.  They are pushed in by the agent periodically mainly for use as scheduling option inputs on services.

**Comment by raphink** [comment]
@vincent99 right. I should have said "computed" instead. The point is that the labels map mixes live data (these computed labels) and configuration (other labels) which is a problem to manage configuration in an idempotent manner.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
