### ISSUE TITLE
[rancher-catalog] Adding templates for Windows Stack

### ISSUE THREAD

**Issue by Ashthos** [rancher/rancher#8166]
**Rancher Versions:**
Server: 1.4.2

**Docker Version:**
1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):**
Unix / Windows

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle / Windows Experimental

**Question**

Having created a rancher catalog for our Linux / Cattle stack, we would like to create entries in the catalog for the windows stack. 

Currently we just want to run single services, so have no need of load balancers or aliases within the Windows stack.

Is there a way of tagging the catalog items as being for the Windows stack, currently they appear when we are in the linux environment, and nothing appears when we are in the windows environment.

**Comment by loganhz** [comment]
You can define your own environment template in latest rancher server version `v.16.22`.
