### ISSUE TITLE
TCP/SNI support for Kubernetes ingress

### ISSUE THREAD

**Issue by hiscal2015** [rancher/rancher#8171]
**Rancher Versions:** 1.5.0
**Docker Version:** 1.12.6
**OS and where are the hosts located? (cloud, bare metal, etc):** Ubuntu 16.04
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single node rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Kubernetes
**Steps to Reproduce:**

Seems when creating an ingress resource in kubernetes rancher can only support http/https protocol, but rancher loadbalancer has the function to support TCP/SNI, so how can I create an ingress resource with TCP protocol on rancher loadbalancer?

**Comment by jrosengren** [comment]
+1

I've been struggling with this as well... I was setting up an InfluxDB service in Kubernetes and the graphite endpoint won't work behind an HTTP proxy.  It'd be great to have "tcp.port =" annotation support in the ingress resource yaml to tell Rancher to use a TCP load balancer.

**Comment by 9teen90nine** [comment]
same issue - I'd like to pass ssl traffic to nginx directly via tcp

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
