### ISSUE TITLE
Rancher session expires

### ISSUE THREAD

**Issue by felixsanz** [rancher/rancher#8173]
Even if you are using the dashboard, the session will expire and you will be kicked out.

Every interaction should restart the session expire timer imo.

**Rancher Versions:**
Server: 1.5.1

**OS and where are the hosts located? (cloud, bare metal, etc):**
bare-metal

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
cattle

**Comment by felixsanz** [comment]
I'm using latest version, `1.5.1`.

I edited the initial message because i used rancherOS version there.

**Comment by superseb** [comment]
Are you experiencing short timeouts? I believe it's already quite long. Are you runnng anything in front of rancher/server?

**Comment by superseb** [comment]
Please reply if you need any more help on this.
