### ISSUE TITLE
Installing postgres stack from Catalog deploys rancher/lb-service-haproxy with an invalid mode http.

### ISSUE THREAD

**Issue by pstrzelczak** [rancher/rancher#8174]
**Rancher Versions:**
Server: v1.4.2
healthcheck: v0.2.3
ipsec: v0.8.7
network-services: v0.4.5
scheduler: v0.6.3

**Docker Version:**
Docker version 1.12.6, build 96d83a5/1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):**
CentOS Linux release 7.3.1611 (Core) KVM virtualization

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
One node for rancher server, two hosts attached

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
1. Install Rancher
2. Install postgresql stack from Catalog

**Results:** 
Postgresql database is not reachable via load balancer.

Symptoms:

~ $  psql -h 10.9.4.115 -U postgres_user postgres_sb
psql: received invalid response to SSL negotiation: H

**After load balancer mode is manually changed to tcp, DB can be accessed:**

~ $ psql -h 10.9.4.115 -U postgres_user postgres_sb
Password for user postgres_user: 
psql (9.3.16, server 9.6.2)
WARNING: psql major version 9.3, server major version 9.6.
         Some psql features might not work.
Type "help" for help.

postgres_sb=# 

The issue is also present with the latest Rancher version (v1.5.1)

![postgres-stack-preview](https://cloud.githubusercontent.com/assets/7737102/23946454/c30c1d7e-097a-11e7-8c60-dec09c8c0b99.png)
![postgres-stack-launching](https://cloud.githubusercontent.com/assets/7737102/23946460/c75c196a-097a-11e7-9a4c-cf41b7937e58.png)
![postgres-stack-after-launch](https://cloud.githubusercontent.com/assets/7737102/23946466/cc804a7e-097a-11e7-82c1-08c7dda17be5.png)
![postgres-stack-invalid-http-mode](https://cloud.githubusercontent.com/assets/7737102/23946471/cfd3f5f4-097a-11e7-9b33-6bc64f3d9fbd.png)

**Comment by chvanikoff** [comment]
Thanks @pstrzelczak - I had the same issue and after the described upgrade it worked for me.

**Comment by superseb** [comment]
Thanks for reporting @pstrzelczak , as this is a community-catalog item, I created a new issue here https://github.com/rancher/community-catalog/issues/514 .
