### ISSUE TITLE
rancher-compose not applying changes in rancher-compose.yml for lb_config

### ISSUE THREAD

**Issue by michlaustn** [rancher/rancher#8175]
**Rancher Versions:**
Server: 1.4.2
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker Version:**

1.12.16

**OS and where are the hosts located? (cloud, bare metal, etc):**

Ubuntu 16.04 AWS EC2

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

Single server, two nodes.

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

Cattle

**Steps to Reproduce:**

Update an existing stack through rancher-compose using updated docker-compose and rancher-compose configuration files.

**Results:** 

Changes from docker-compose are applied, changes from rancher-compose are not applied.  Configuration of rancher-compose stays the same within Rancher.

If the stack is deleted and the rancher-compose run again then the stack is created with the correct configuration.  If rancher-compose is run again with new configuration no changes are applied.

**Comment by mhdev90** [comment]
+1 same issue

**Comment by leafish-dylan** [comment]
I can confirm this, using the latest few versions of rancher-compose. It means that it's impossible for us to add or adjust healthchecks using "rancher-compose up", or change lb_config. Without --force-upgrade, rancher-compose detects no changes to rancher-compose.yml no matter how much I mangle it. If I make a change through the UI (such as adding a healthcheck), then run the command again, a change is detected and the healthcheck will be removed, but the contents of rancher-compose.yml is still not applied correctly.

**Comment by tcdev0** [comment]
nothing to add, +1

**Comment by tcdev0** [comment]
tested with rancher-server:v1.5.6 -> not working

**Comment by michlaustn** [comment]
As this was added as a milestone for Release 1.6.0, has it been resolved?

**Comment by michlaustn** [comment]
Tested with rancher-server-1.6.0 rancher-agent-1.2.2 the problem is still occurring.

**Comment by michlaustn** [comment]
The problem also occurs when using the rancher-cli.

**Comment by leafish-dylan** [comment]
This (and volume bugs), have prevented us from upgrading beyond Rancher 1.1, which is almost 12 months old. Does anybody have a workaround for this, or any idea what/where the problem might be?

**Comment by earzur** [comment]
currently, our only option is to rm / up the service, for a lb in production with 50 containers and constant stream of requests, it totally defeats the purpose of upgrades with no service interruptions.

**Comment by joshwget** [comment]
Is this a regression in functionality? Has this worked as expected in previous Rancher versions?

**Comment by earzur** [comment]
@joshwget if it's not a regression, it's undocumented. It seems logical that changing only `rancher-compose.yml` would trigger update somehow. --force-update doesn't work either.

It's affecting rancher-haproxy-lb based services for instance, at the moment, the only way (i'm aware of - i'm a rancher noob) to make them aware of change in port_rules of services connected with labels is to fully restart (rancher rm && rancher up), generating significant troubles for people like me who use this with a CNAME DNS record pointing to the lb record in a DNS zone managed with the route53 service. Guaranteed downtime (LB containers would be started on another instance -> DNS record change -> down during your record TTL, and a lot of ISPs DNS servers will override your record's TTL to 1800 or 3600. FUN). I know I should add another layer of LB.

**Comment by leafish-dylan** [comment]
This works in 1.1, at least, and we rely on it to update running stacks and the load-balancer in that version.

It seems even more important that this works now that the Rancher LB has been improved, and more variables exposed in the rancher-compose.yml. Without this, I don't see how we're able to automate the LB settings for a running stack (ie, changing port and host header information if new values are provided as part of a deployment) without destroying stacks and causing downtime.

**Comment by jbmusso** [comment]
We're seeing this issue using Rancher server v1.5.6 and v1.5.8 (two different setups), both using rancher-compose v0.12.5 and Docker 17.03.1-ce.
The rm && up workaround works, but obviously isn't an option when using stateful volumes (data sidekick containers).

**Comment by parruda** [comment]
Terraform user here.
Just tested on 1.6.2 and problem still occurs.
I am trying to scale up a service. I change to "scale: 4" on rancher-compose.yml, then apply the changes. I see the stack upgrading on the UI, but when I click "view config", the old value "scale: 1" is still there.

**Comment by michlaustn** [comment]
Problem is still occurring in 1.6.5.

**Comment by ptcuops** [comment]
It would be great to get an official comment on this. I spent longer than I';d like to admin trying to figure out why my changes to lb_config in rancher-compose simply were not being absorbed. Fortunately, our apps aren't in production yet so an "rm -> up" isn't out of the question, but this does make me very reluctant to move them into production under rancher if I can't perform upgrades without significant downtime.

**Comment by DoingItNow** [comment]
Bumping this issue as I can't even get rancher compose CLI to use the rancher-compose.yml at all. Whats the point of having a rancher-compose.yml when Rancher just ignores it and uses the default yml file?  It does not makes sense that an integral part of what Rancher is doesn't work and there is not even a comment saying "hey this is a problem and we are looking into it".

**Comment by joshwget** [comment]
@DoingItNow It sounds like your issue is pretty different from the original issue. Can you file this separately to keep comments here in scope?

**Comment by DoingItNow** [comment]
Yep I have created a new issue #9874

**Comment by myownsoul** [comment]
Same problem here. I've add healthcheck to the new rancher-compose.yml file.
But it didn't take any effect/change by using `rancher-compose -p PROJECE_NAME up -d -c --upgrade`.

***rancher-server***: 1.6.4 
***rancher-agent***: 1.2.2
***rancher-compose***: 0.12.5
***docker***: 1.12.6

@michlaustn  Has the problem been solved?

**Comment by ozbillwang** [comment]
Got the same issue and stuck here. 

Report this issue to rancher forum to check if we can get any updates. 

https://forums.rancher.com/t/rancher-compose-not-applying-changes-in-rancher-compose-yml-8175/10074

**Comment by deniseschannon** [comment]
In all these cases, I believe the specific issue at hand is that if you try to upgrade a load balancer, the `lb_config` section gets ignored in rancher-compose.yml when trying to do an ugprade. I've updated the issue title for this use case.

**Comment by deniseschannon** [comment]
I am unable to reproduce this using the Rancher CLI, both healthchecks and LBconfig (in the rancher-compose.yml files) appear to be updated.  We are no longer adding in fixes in the rancher-compose CLI as everything that you can do in the rancher-compose CLI can be accomplished in the Rancher CLI using the `rancher up` command. 

https://rancher.com/docs/rancher/v1.6/en/cli/commands/#rancher-up-reference

Please move towards using the Rancher CLI and if you still have issues using Rancher CLI, please open a new issue. 

Some people have always been wary about using the Rancher CLI as we have it labeled as "beta" in the UI, but we actually support and maintain the Rancher CLI in 1.6. We'll be removing the "beta" from the UI in this next release.

**Comment by ozbillwang** [comment]
@deniseschannon 

Frankly, I am not sure what you are working for. By the way, to change the subject and add it to only for `lb_config` is totally a misunderstanding for the problem I am reporting (I think the others are facing similar issue, if not, pleas point out)
 
The subject is about rancher-compose cli, then I found the similar issue in rancher cli as well.

So if I have a simple `rancher-compose.yml` and deploy as new, three containers will run

```
version: '2'
services:
  helloworld:
    scale: 3
    start_on_create: true
```

But if I change the scale to `5` or other number, run `rancher-compose` again, the command runs fine, but still keep 3 containers.  That's the problem I am facing currently.

**Comment by deniseschannon** [comment]
@ozbillwang You are the first one in this entire thread to have provided an actual yaml with an actual example of what specific field you think is failing.

Note: If you are running `rancher-compose`, then you are actually using rancher-compose CLI, which we aren't maintaining at this time as we moved over to using Rancher CLI as indicated in my previous comment.

For scaling services, you are required to use the `scale` command and not the upgrade command. So in your case if you want to scale, please use `rancher-compose scale helloworld=5` as this is how docker compose handles scaling services as well. 

If you are to use Rancher CLI, the way to reference the service is slightly different. Ways of how to scale using CLI are listed in our docs:

https://rancher.com/docs/rancher/v1.6/en/cattle/rancher-compose/commands/#stopdown--scale-command
https://rancher.com/docs/rancher/v1.6/en/cli/commands/#rancher-scale-reference

**Comment by deniseschannon** [comment]
To follow up, there is also a specific note in the docs about how scale must be done with either the UI or using the scale command for rancher-composeCLI

https://rancher.com/docs/rancher/v1.6/en/cattle/upgrading/#upgrading-services

**Comment by ozbillwang** [comment]
@deniseschannon 

Thanks to clarify this. 

For your statement, it makes confusion for rancher end users.

>Note: If you are running rancher-compose, then you are actually using rancher-compose CLI, which we aren't maintaining at this time as we moved over to using Rancher CLI as indicated in my previous comment.

But when login rancher UI, the `Download CLI` still give us two choices:

![screen shot 2018-05-09 at 9 40 04 am](https://user-images.githubusercontent.com/8954908/39788311-36607cba-536d-11e8-9c6c-86673d77d654.png)

If Rancher Labs formally doesn't maintain `Rancher-compose` CLI, please remove it that we all know it is not supported any more.

**Comment by ozbillwang** [comment]
Back to the function. `Rancher-compose.yml` are defined by Rancher Labs only, and used by both `rancher-compose` and `rancher` CLI.  If it can't be used to manage the scale or others features (done by rancher cli), then I will think it is something we should improve it.

**Comment by Joeasaurus** [comment]
My use case with the scaling is for simple CI. My CI is set up to run rancher-compose upgrade on every commit, if I change the scale in a commit, how do I go about detecting that myself such that I can run a different command ("scale")?
