### ISSUE TITLE
Make description of already deployed library templates available

### ISSUE THREAD

**Issue by kirrmann** [rancher/rancher#8176]
After a library template got deployed, the description is not longer available. It would be nice if we could instead still open the details, but disable the "Launch" Button and the input boxes.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.4.1` Cattle: `v0.176.9` UI: `v1.4.6` |
|Access|`ldap` `admin`|
|Orchestration|`Cattle`|
|Route|`service.containers`|

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
