### ISSUE TITLE
Rancher-compose will not update external services

### ISSUE THREAD

**Issue by sra** [rancher/rancher#8177]
**Rancher Versions:**
Server: 1.4.1
healthcheck: 0.2.3
ipsec: 
network-services: 0.4.5
scheduler: 0.6.3
kubernetes (if applicable):

**Docker Version:**
1.12.3 on the rancher hosts (Rancher OS 0.7.1)
17.03.whatever_they_are_doing_now_days

**OS and where are the hosts located? (cloud, bare metal, etc):**
OS Mac OS X and library/docker image
Hosts in AWs

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**

Deploy a stack using rancher-compose (0.12.3) with a service reference or external service reference and update it and update it with  `rancher-compose up` or `rancher-compose up -u` is run. Even adding `--force-recreate` does nothing.  It cannot be changed unless it is deleted or done in the gui.

Example compose file:

docker-compose.yml:

```
version: '2'
  dbserver:
    image: rancher/external-service
```

rancher-compose.yml:

```
version: '2'
  dbserver:
    hostname: example.com
```

**Comment by joshwget** [comment]
This is largely the same as #8175. Closing in favor of that.
