### ISSUE TITLE
Always starting kubernetes-ingress-lbs

### ISSUE THREAD

**Issue by dweidenfeld** [rancher/rancher#8178]
**Rancher Versions:**
Server: Ubuntu LInux
healthcheck: on
ipsec: - 
network-services: -
scheduler: -
kubernetes (if applicable): yes

**Docker Version:**
1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu bare metal

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node Rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
I deployed a custom traefik ingress controller, which I want to use. 
Everything works fine, I just have had to stop the default load-balancer listening on port 80 (because of duplicate usage).
Now everytime I setup a new Ingress rancher tries to setup the default load balancer again in the kubernetes-ingress-lbs stack. This (of course) fails, because port 80 is already in use by my traefik controller.

Is it possible to stop rancher from creating new loadbalancers automatically, because I want to manage the Ingress myself?

// Edit:
Or did I missunderstood something. 
My goal is to setup traefik for automatic SSL certificate generation and forwarding everything requesting on port 80 to 443.

**Comment by joshwget** [comment]
It will be possible to disable the Rancher ingress controller in an upcoming version of Rancher (#5999). For those looking to use a different ingress controller exclusively this would solve your issue.

**Comment by deniseschannon** [comment]
Verified in the k8s v1.6 template taht you are able to disable the rancher ingress controller.

**Comment by cuseinovic** [comment]
Hi,
Sorry to reopen but i need to know @dweidenfeld  how do you solved this ?

**Comment by dweidenfeld** [comment]
You can edit the template for kubernetes. I think that solves the issue. 

I switched to a plain kubernetes setup meanwhile. Using kubeadm etc ;) ... Works for me much better

**Comment by cuseinovic** [comment]
I will try ! Thanks for your answer 👍 
Yeah i'm testing rancher with ingress  / lb but some trouble like this. 
I'm actually testing rancher2.0 with some pods and command line it's better like you said :)
