### ISSUE TITLE
[rancher-dns] Rancher's DNS does not respond with `NxDomain` for hostnames it's unaware of

### ISSUE THREAD

**Issue by dchambers** [rancher/rancher#8180]
If you type `nslookup google.com` then this will cause the following speculative DNS queries to be made:

  - `google.com.default.svc.cluster.local`
  - `google.com.svc.cluster.local`
  - `google.com.cluster.local`
  - `google.com.kubelet.kubernetes.rancher.internal`
  - `google.com.kubernetes.rancher.internal`
  - `google.com.rancher.internal`

as a consequence of how `search` is defined within `resolv.conf`:

```
search default.svc.cluster.local svc.cluster.local cluster.local kubelet.kubernetes.rancher.internal kubernetes.rancher.internal rancher.internal
```

As [described here](http://www.openwall.com/lists/musl/2017/03/15/11), queries relating to Kubernetes service discovery correctly respond with `NxDomain`, whereas queries relating to rancher-dns **do not**. As [you can see from this issue](https://github.com/gliderlabs/docker-alpine/issues/8#issuecomment-243578965), this is causing resolution of external names to fail within Alpine Linux based containers.

Given how popular Alpine Linux based containers have become, particularly given that they have been standardized on by Docker themselves, this is quite a big issue for Rancher users (and maybe others too?).

**Comment by dchambers** [comment]
Oops, this seems to be a dupe [of this issue](https://github.com/rancher/rancher/issues/8180), but it's hopefully still useful given that it contains [explanatory technical analysis](http://www.openwall.com/lists/musl/2017/03/15/11) from the author of musl libc.

**Comment by aemneina** [comment]
appreciate it @dchambers . I'm going to close this but the fact its linked to other issues should be plenty good for others to find this. Feel free to holler if you think I'm off base here.

**Comment by dchambers** [comment]
Yep, sounds good @aemneina :+1:.
