### ISSUE TITLE
Cannot update/delete host label

### ISSUE THREAD

**Issue by bseng** [rancher/rancher#8188]
*Describe your issue here*

*steps to reproduce*
Edit host
Add a label io.rancher.host.external_dns_ip with an ip address
press save

edit host
remove label io.rancher.host.external_dns_ip
press save

edit host
the same label still exist

also edit the label text or value doesn't change it as well.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.4.1` Cattle: `v0.176.9` UI: `v1.4.6` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`hosts.index`|

**Comment by bseng** [comment]
look into a bit more the label actually got deleted in the database and just stuck in the ui it seems.

**Comment by tfiduccia** [comment]
Version - 1.5.1 - this is no longer reproducible in the current build.  Looks like we fixed it :)

**Comment by gaieges** [comment]
For what it's worth, if anyone has been experiencing this issue in 1.4.1, I've seen the same thing and the problem exists not in the system itself, but in the UI making an incorrect request to the server without the updated labels.

To solve it, what I did was made the request to change the host via the UI, and captured it in dev tools network panel in chrome.  The request to the `http://rancher:8080/v2-beta/projects/1a1/hosts/1h1` path includes the labels that are incorrect.  Right click, copy to curl, and then modify that request to contain the updated labels you want.  Sending that request should do the trick.
