### ISSUE TITLE
there is no catalog menu on the kube env rancher1.5.1 dashboard 

### ISSUE THREAD

**Issue by lannyMa** [rancher/rancher#8189]
*Describe your issue here*
i try rancher k8s env,but when i switch to k8s env, the rancher ui is unusal ,it is not have catalog menu, and kubenetes drop-down menu on include , my menu like this:

kubenetes            infrastructure           admin          api
 dashboard
 cli
 infrastructure stacks

but not have pods/rc... menu.. ,
can u help me?the k8s env is already ok.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.5.1` Cattle: `v0.177.8` UI: `v1.5.7` |
|Access|`Disabled`|
|Orchestration|`Cattle`|
|Route|`catalog-tab.launch`|

**Comment by vincent99** [comment]
We now package the kubernetes dashboard and helm instead of our own UI for kubernetes.
