### ISSUE TITLE
Requesting documentation for the Openstack Host driver

### ISSUE THREAD

**Issue by btro** [rancher/rancher#8192]
The current version offers a Openstack Host driver, but it is not clear which of the parameters it requests are needed and which are optional. In some cases I'm not even sure where to find the parameters. I've been searching in the Wiki and the docs to find info on this, but I couldn't find anything. Is there some documentation somewhere here or do I have to look somewhere else?

I'm thankful for any input on this. :)

Edit: The only thing I could find was:
https://docs.docker.com/machine/drivers/openstack/#usage
So my guess is the provider is just a wrapper for all of these parameters?

**Comment by deniseschannon** [comment]
Rancher is just providing a convenient way to launch Openstack using docker-machine. 

The docs that you have are the ones that I would provide.
