### ISSUE TITLE
[k8s] Dashboard show blank page

### ISSUE THREAD

**Issue by pengjiang80** [rancher/rancher#8194]
1. New deployment with k8s environment. Try to access dashboard, it just showed blank page without error.
2. Use kubectl check pod and service status. Both are okay. Checked logs of dashboard container, no errors.
3. Tried to view source code of blank page in browser, it contains info as below:

<!doctype html> <html ng-app="kubernetesDashboard"> <head> <meta charset="utf-8"> <title>Kubernetes Dashboard</title> <link rel="icon" type="image/png" href="assets/images/kubernetes-logo.png"> <meta name="viewport" content="width=device-width"> <link rel="stylesheet" href="static/vendor.36bb79bb.css"> <link rel="stylesheet" href="static/app.968d5cf5.css"> </head> <body>  <kd-chrome layout="column" layout-fill> </kd-chrome> <script src="static/vendor.633c6c7a.js"></script> <script src="api/appConfig.json"></script> <script src="static/app.29a51112.js"></script> </body> </html> 

4. Kubectl edit services kubernetes-dashboard --namespace=kube-system, change service from clusterip to nodeport.

5. Tried to access nodeport. The dashboard page can be opened successfully.

It seems there are some problems when proxying the request to kubernetes dashboard and it thinks we are using "outdated" browser. 

K8s Host: Ubuntu 16.04 LTS
Docker version: v1.12.6
Rancher Server Host: CentOS 7.2 with docker v1.10
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.4.2` Cattle: `v0.176.10` UI: `v1.4.9` |
|Access|`localauth` `admin`|
|Orchestration|`Kubernetes`|
|Route|`hosts.index`|

**Comment by pengjiang80** [comment]
K8s Host: Ubuntu 16.04 LTS
Docker version: v1.12.6

**Comment by njordr** [comment]
Hi @pengjiang80 

I have the same issue and tried your solution, but probably I make a typo. This is my service definition:
spec:
  clusterIP: 10.43.231.53
  ports:
  - nodePort: 31566
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    k8s-app: kubernetes-dashboard
  sessionAffinity: None
  type: NodePort

but the kubernets dashboard doesn't work

**Comment by pengjiang80** [comment]
@njordr  my steps are as below. Hope it's helpful.

1. Go to the addon-starter container.
2. Modify the /etc/kubernetes/addons/dashboard-svc.yaml file like below. I just added the type: NodePort part.
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-dashboard
  namespace: kube-system
  labels:
    k8s-app: kubernetes-dashboard
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    k8s-app: kubernetes-dashboard
  ports:
  - port: 9090
  type: NodePort

3. Run the addons-update.sh shell to let it recreate services. 
4. Use kubectl get services --namespace=kube-system to check the nodeport allocated.

**Comment by ryanwalls** [comment]
FYI, we also have a blank screen when loading the k8s dashboard UI from rancher 1.5.3.

**Comment by lmangani** [comment]
+1 same issue after updating Rancher/Kubernetes to the latest official release.

@pengjiang80 it should be noted this change allows unauthenticated entry to the dashboard to anyone

**Comment by pjmorr** [comment]
Just a note as I struggled with this for a few days before reading this in the manual (I know, don't judge).  
In my case, I had previously installed kubernetes on this device and deleted it.  
https://docs.rancher.com/rancher/v1.5/en/kubernetes/deleting/  
Specifically what I had to do was completely delete all docker volumes, containers and images that were on my test box.  I had thousands of dangling docker volumes, one of which was this etcd volume which the documentation specifically states will cause problems.  

> For any hosts that had run the etcd service, there are a couple of items that need to be cleaned up by execing onto each host:

> A named volume etcd: Remove the named volume by running docker volume rm etcd.
By default, backups are enabled and stored at /var/etcd/backups: Remove the backups by running rm -r /var/etcd/backups/*.

I then completely deleted the environment and created a new one using kubernetes as the orchestration engine and added my 'now clean' host and the kube-dashboard now works as advertised.

**Comment by ofsole** [comment]
same issue, @pjmorr , works for me

**Comment by zengyulu** [comment]
@pjmorr  after clean up volume etcd, the dashboard UI is back. Thanks!

**Comment by superseb** [comment]
As this is documented, please file a new issue when you encounter other problems.
