### ISSUE TITLE
Can't start Portainer after starting Swarm template

### ISSUE THREAD

**Issue by LLParse** [rancher/rancher#8196]
**Rancher Versions:**
Server: 1.5.1

**Docker Version:** 1.13.1

**OS and where are the hosts located? (cloud, bare metal, etc):** Ubuntu 16.04.1, AWS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single internal

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle->Swarm

**Steps to Reproduce:**
1. Create a cattle environment, add some Docker 1.13 hosts
2. Launch the swarm template

**Results:** 
Swarm UI options appear and catalog goes away, looks like a Swarm environment.
Portainer UI link yields `Service Unavailable`.
Portainer stack didn't start (as is expected, it's a separate template).
User can't launch the Portainer UI from catalog.

I'm not entirely sure what _should_ happen, but it might be worth addressing.

**Comment by mwthink** [comment]
I've experienced this issue as well. Are you connecting to your Rancher server via a hostname or an IP address?

Switching to an IP address got Portainer to boot successfully for me, however once it starts up it is unable to connect to the Docker socket.


The hostname issue is strange, as the output logs say it's unable to resolve the hostname, but if I ssh into that container after it has booted (After switching the hostname to an IP address), I can ping the hostname all day, no issues.

**Comment by mwthink** [comment]
Played around with it a bit more and found a solution to the unable to connect to socket issue.

Upgrade the portainer service to use the `latest` or more recent tag than `pr572`, which is what it currently is hardcoded to use. That resolved the socket issue for me, and it might even have solved hostname resolution as well.

Probably should make a PR to update the rancher configs as this is 100% broken in production at this point.

**Comment by jbreuer95** [comment]
Just delete the entire stack and reinstall via the add from catalog function. You get the latest and greatest working fine

**Comment by Tzrlk** [comment]
@jbreuer95 Tried that. Just gave me the same version and continued to fail. "Upgrading" to the 'latest' tag of portainer/portainer just gives me the same issue. All the logs tell me is that the portainer-agent can't perform dns lookup.

**Comment by emanb29** [comment]
Same issue here

**Comment by hdep** [comment]
Hello,

just got the same issue.
the portainer report in his logs : 

> 24/10/2017 15:12:07time="2017-10-24T13:12:07Z" level=fatal msg="Exiting: Get http://rancher.recette.local:8080/v2-beta: dial tcp: lookup rancher.recette.local: no such host"

**Comment by superseb** [comment]
The problem here is that you configured `rancher.recette.local` as the URL to reach the Rancher API (i.e. `CATTLE_URL`) but this is not resolvable from within the container. Using `.local` is also not recommended. Could you try using an IP or FQDN with a valid TLD to see if this helps? Not 100% sure if you're hitting the same issue as this issue describes.

**Comment by hdep** [comment]
This container is not able to resolv it, but my rancher host know how to do this.

I did change the Host Registration URL on Admin => Settings, use the IP in place of the DNS record, redeploy the Portainer Stack but the settings is not updated. 

Where should I change the CATTLE_URL settings ? 

Thanks

**Comment by superseb** [comment]
That should be enough, how did you "redeploy the Portainer Stack" ?

**Comment by hdep** [comment]
I go in : 
stack -> Infrastructure delete portainer stack
Then I go to Add from Catalog => Look for portainer view details => Launch
