### ISSUE TITLE
Deploying Route 53 catalog fails with a template error 

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#8197]
**Rancher Versions:**
Server: Master with rancher-compose executor

**OS and where are the hosts located? (cloud, bare metal, etc):**Ubuntu, Cloud

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**Single node

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**Cattle

**Steps to Reproduce:**
1. Create a cattle setup with AWS hosts
2. Deploy Route 53 catalog

**Results:** 
The catalog deployment fails with an error as below:
```
Error (template: template:43: function "service_name" not defined
```

**Comment by joshwget** [comment]
Closing in favor of #8271 which describes the issue a bit more specifically.
