### ISSUE TITLE
Setting up GitHub Auth on 1.4.2 doesnt work

### ISSUE THREAD

**Issue by nhumrich** [rancher/rancher#8198]
**Rancher Versions:**
Server: 1.4.2

**Steps to Reproduce:**
Spin up a new server of 1.4.2, go to the access control page, and choose github. Make a new github application and input the parameters given.

**Results:** 
When you click "test" you get an error.

I tried to debug this issue a little myself, and it looks like rancher is sending me to github with an error in the callback url, so github is actually correctly authenticating, but the callback url makes it seam like there was an authentication error. The url where rancher is sending me is:

```https://github.com/login/oauth/authorize?client_id=XXXXXXXXX&scope=read:org&state=0.1567394015601108&redirect_uri=https://rancher.example.com/?error=redirect_uri_mismatch&error_description=The redirect_uri MUST match the registered callback URL for this application.&error_uri=https://developer.github.com/v3/oauth/#redirect-uri-mismatch&state=0.34985224630196976&isTest=1```

(I url decoded a couple times)

If I manually paste the url in a new tab and remove the `?error` portion, it works, but that isnt a workaround as I still cant get past the github auth setup page, as it never realizes it actually works.

**Comment by vincent99** [comment]
When Github redirects back it goes to the URL that is configured in the Github application (the application matching that `client_id`).  If that does not match the URL that you actually came from, they add those query params and you don't get the token back, so you don't get logged in.

So the URL configured in the GitHub application has to match the URL that you're serving on.

**Comment by nhumrich** [comment]
It does. I have checked the url like 100 times. Like I said, I have tried modifying the url rancher uses manually to remove the section after ?error, and everything works. The url I posted is the URL rancher sends me too. There is no reason for that `?error` stuff to be in the URL. That url is the "authorize this app" page on github, BEFORE github checks the redirect_uri

**Comment by nhumrich** [comment]
Nevermind. I tried again just now, and it worked. I wonder if github was having an issue or something... Sorry for the waste of time.

**Comment by vincent99** [comment]
Note that when it doesn't work they redirect to the URL they **do** think is right, so if that happens to resolve to the same server it will work if you click login a 2nd time because you're going $wrong_url login -> github -> $right_url login -> github again -> $right_url logged in.
