### ISSUE TITLE
Service never stops creating containers if not enough hosts to support exposed ports, need better error messaging

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#820]
v0.20.2
Steps:
1.  Create three machine/hosts
2.  Go to Services & create environment
3.  Add Service - Scale = 4, image = mysql, Public and Private Port = 4406, Environment Vars Name = MYSQL_ROOT_PASSWORD and Value = password.
4.  Click on Create

Results:
Because I'm trying to create 4 containers with the same port and only have 3 hosts, the 4th container just continues to try and create and the service is never fully activated.

Expected:
We should recognize this situation.  
Suggestions
1.  Stop service and throw error.
2.  If port is used we check for number of host and give them a warning.

**Comment by alena1108** [comment]
Service Discovery code doesn't have allocator specific knowledge, so it treats allocation failure as any other failure (especially considering that the fact that allocation failure results in generic Exception). There is also no way to check against allocator if there are hosts that qualify for deployment; and even if it was, the failures would still be possible as there might be timing issue when "check allocator" call returns true, but at the moment of execution allocator fails to find a placement. 


The behavior today is - keep on trying the failed process. To correct the situation - either add another host, or reduce the scale.

**Comment by alena1108** [comment]
@sonchang Son, we might want to think about throwing allocation specific error, and propagating it to the API - basically treat allocation error as unrecoverable. But it should be done on generic way, not just for the service instances, but for regular instances, or/and other objects in cattle (we can go use case by use case). Reopening the bug by now till we figure out the right approach

**Comment by deniseschannon** [comment]
Closed many prior bugs to capture what needs to happen in this 1 bug. 

Essentially, we need better error message when service will fail to scale due to lack of open ports or invalid container info.

**Comment by deniseschannon** [comment]
@tfiduccia There was a "better scheduling error messages" added to cattle recently. 

Now, the error message shows in the UI as
`Removed (Scheduling failed: host needs ports 8000/tcp available)`

**Comment by tfiduccia** [comment]
This is still sitting in an activating state and not throwing an error.

**Comment by alena1108** [comment]
@tfiduccia we are not going to change the logic for the failed containers start in the service. It will continue staying in Transitioning state till the user fixes it manually. What we would do is:

* provide transitioning message on the service indicating the last error happening during service reconcile
* if the service instance fails to start - and that the most common case causing service being stuck in activating state - it won't be removed immediately. It would stay in Error state for 1 hour (configurable) and still be associated with the service. When user sees the instance in Error state, he can look at its Transitioning field to check for the instance start failure cause. 

All the above was introduced by https://github.com/rancher/cattle/pull/1236. We might need some UI fixes for that. Not sure if we already have support for displaying transitioning messages of the instances. And we should probably add transitioning message for the service. @vincent99

**Comment by tfiduccia** [comment]
Version - master 3/7
Verified fixed
