### ISSUE TITLE
General UI Issues & Host Page

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#8202]
**Issues:**

- [ ] If last host in list has labels, the lower bottom of border is missing
![image](https://cloud.githubusercontent.com/assets/11514927/24021256/436d6c6a-0a5d-11e7-96d7-b1416d67f27c.png)
- [x] Too much white space on left and right side of app, also why is it a set size where the white space just keeps getting bigger instead of the rancher app itself?
![image](https://cloud.githubusercontent.com/assets/11514927/24023348/fa9cdf82-0a68-11e7-8ba5-4dbbc0f62be6.png)
- [x] There is border around the upper part of the host pod if there are labels, but no border if there isn't.  Maybe we should always have a border?  That way the checkbox and expand arrow look centered on something?
![image](https://cloud.githubusercontent.com/assets/11514927/24021753/af9fe384-0a5f-11e7-9dc2-611eeaa2ba9c.png)
- [ ] In group and list view, the hosts are lining up on right instead of left side when there are too many to fit onto one row
![image](https://cloud.githubusercontent.com/assets/11514927/24023484/dd4ab39a-0a69-11e7-95d3-6b4f88328bdd.png)
- [ ] Group and list view when you have multiple, the second one on bottom has lots of white space between it and the host above it?
![image](https://cloud.githubusercontent.com/assets/11514927/24024023/6e16684e-0a6d-11e7-8074-3956c3aa3e72.png)
- [x] Action Menu - The menu itself needs to be fixed.  The menu needs to be narrower, the text used to be left with the buttons aligned on the right.
![image](https://cloud.githubusercontent.com/assets/11514927/24020731/b456da36-0a5a-11e7-90b0-fb5d26ae4fb4.png)

- [x] Add Host button and display buttons are too close together
![image](https://cloud.githubusercontent.com/assets/11514927/24021167/d07c613e-0a5c-11e7-9bb5-6b84c3e90338.png)

- [x] Can't really tell what sorting is being done.  The up and down arrows are not clearly defined so you can tell.
![image](https://cloud.githubusercontent.com/assets/11514927/24021203/f4601442-0a5c-11e7-823e-9a4b8f09433f.png)

- [x] Need a border around host boxes in Icon and Group Host views.
![image](https://cloud.githubusercontent.com/assets/11514927/24021344/bd43dbb4-0a5d-11e7-8333-32dc4a96a866.png)

- [x] Delete confirmation modal text should be redone a bit.  Nicer Font, space between are you sure & list of host.  Maybe the host names themselves can be bold or something?
![image](https://cloud.githubusercontent.com/assets/11514927/24021970/ec46ed86-0a60-11e7-8267-db1dc5612b0c.png)

- [x] The state text and icon should be centered so it aligns with the checkbox/expand arrow, if there are no labels (I think it's just the state one, but could be rest of info as well?)
![image](https://cloud.githubusercontent.com/assets/11514927/24022601/c12fa18e-0a64-11e7-9f71-5e8d430758e3.png)

- [x] For container on host page, none of the info in the row is centered.
![image](https://cloud.githubusercontent.com/assets/11514927/24022811/d2f23e8a-0a65-11e7-84dd-89cf56f83c67.png)

- [x] When I start to type in the search box, it changes size.  Maybe it should just be a size?
![image](https://cloud.githubusercontent.com/assets/11514927/24022897/48d8b052-0a66-11e7-99cb-5b5f87b8aaa1.png)
![image](https://cloud.githubusercontent.com/assets/11514927/24022904/4f14c4ba-0a66-11e7-8b58-b0f6d94fe17d.png)

- [x] The X box to remove text from search is too big.  Should be same size as search box and maybe a little bit smaller in general?
![image](https://cloud.githubusercontent.com/assets/11514927/24022934/6ce277f8-0a66-11e7-9d17-de7448256062.png)

- [x] In Icon and group view, when you hover over container/stack name, the old menu style is showing up with the dark blue and black.  Not sure if this was on purpose or not
![image](https://cloud.githubusercontent.com/assets/11514927/24023447/9ffb1ee4-0a69-11e7-8fe5-ea0675972d82.png)

- [x] In group view, the menu is too close to the IP address
![image](https://cloud.githubusercontent.com/assets/11514927/24023468/c1279f16-0a69-11e7-9bbf-3bf86a72c0ad.png)

- [x] In group view, add container is white text on light grey background and hard to see
![image](https://cloud.githubusercontent.com/assets/11514927/24023509/01eb7eb4-0a6a-11e7-8c88-b412cf0c07b4.png)

- [x] View logs, I can't read the logs with new black background.
![image](https://cloud.githubusercontent.com/assets/11514927/24024040/923106ee-0a6d-11e7-8139-b08c0efab4d6.png)

- [x] View logs, the Combined, Out and Error tabs are now a link list instead of tabs

**Comment by lvuch** [comment]
@vincent99 #2 action menu width is bootstrap voodoo, some of the issues in grouped host view layout I'm not sure what the cause is

**Comment by tfiduccia** [comment]
Version - 4/5
Verified issues - created new issue for unresolved and new bugs
