### ISSUE TITLE
ipsec: don't initiate connections from both ends

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#8204]
When bringing up ipsec tunnel between two hosts, both of them start initiating, need to disable that and have only one peer initiate a connection.

**Comment by leodotcloud** [comment]
Fixed in `ipsec: 0.1.4` with image: `rancher/net:v0.11.8`

**Comment by leodotcloud** [comment]
**Before the fix:**
Inside the `ipsec-router` container.
```
root@0bdd7892710e:/# swanctl --list-sas | grep 52.201.218.52
conn-52.201.218.52: #4, ESTABLISHED, IKEv2, 7bc5a524cc208be0_i 93040e4b5c227399_r*
  remote '10.42.239.206' @ 52.201.218.52[4500]
conn-52.201.218.52: #2, ESTABLISHED, IKEv2, b8aa5ae584281fcf_i* 420c093339e973a2_r
  remote '10.42.239.206' @ 52.201.218.52[4500]
root@0bdd7892710e:/#
```
From the above output we can see there are two SAs. The first one is initialized from the remote end based on `r*` and the second one is initialized from the current one based on `i*`.

**After fix:**
We should be able to see only one SA initiated from the Host with the lower IP address (string comparison, not IP comparison) of the two.

**Comment by sangeethah** [comment]
Rancher versions: v1.6.8-rc4 with rancher/net:v0.11.8

Between any 2 hosts , we only see one SA initiated which is from the host with lower ip(by string comparison).

```
root@531274b73892:/# swanctl --list-sas | grep <host1 ip>
conn-<host1 ip>: #3, ESTABLISHED, IKEv2, e91697ae94241521_i e81d1a0d3e73730
2_r*
  remote '10.42.162.10' @ <host1 ip>[4500]
  child-<host1 ip>: #6, reqid 1234, INSTALLED, TUNNEL-in-UDP, ESP:AES_GCM_1
6-128/MODP_2048
root@531274b73892:/#

```

```
root@43858fd7c597:/# swanctl --list-sas | grep <host2 ip>
conn-35.<host2 ip>: #4, ESTABLISHED, IKEv2, e91697ae94241521_i* e81d1a0d3e737302_
r
  remote '10.42.199.0' @ <host2 ip>[4500]
  child-<host2 ip>: #12, reqid 1234, INSTALLED, TUNNEL-in-UDP, ESP:AES_GCM_16-
128/MODP_2048
root@43858fd7c597:/#
```

**Comment by leodotcloud** [comment]
Reopening this issue. Strongswan doesn't seem to retry the tunnel creation. Need extra logic to handle those scenarios.
Reverting the earlier change.

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
