### ISSUE TITLE
ipsec: get rid of server running on port 8111

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#8205]
we don't use this anymore

**Comment by dpaar** [comment]
We are actually using this port in our deployment for IPsec health checks until Rancher healthcheck supports UDP port scanning or ping.

**Comment by leodotcloud** [comment]
@dpaar thanks for the feedback. Plans have changed already to use this port to run the healthcheck.

**Comment by leodotcloud** [comment]
Not relevant anymore, closing this issue.
