### ISSUE TITLE
ipsec: conntrack cache problem

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#8207]

**Comment by ibuildthecloud** [comment]
Linking related issue that was reported in Docker: https://github.com/docker/docker/issues/8795

Just to be clear Docker suffers from the same stale conntrack UDP issues Rancher does, but since Rancher does not use Docker native networking anymore we will fix it in Rancher.

**Comment by deniseschannon** [comment]
Available in rancher/net:v0.11.0 (ipsec template version `v0.0.5`)  and rancher/network-manager:v0.6.0 (network-services template version `v0.1.2`)

**Comment by sangeethah** [comment]
Closing as per the findings from #8412 (comment).
