### ISSUE TITLE
Adding an Azure Host specifying an existing subnet returns InUseSubnetCannotBeUpdated error message

### ISSUE THREAD

**Issue by bmmathe** [rancher/rancher#8208]
**Rancher Versions:**
Server:1.5.1

**Docker Version:**
17.03.0-ce

**OS and where are the hosts located? (cloud, bare metal, etc):**
Azure

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
No hosts

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Swarm Kit (1.12+)

**Steps to Reproduce:**
Create a new environment and add Host.  Select Azure Driver
Fill out all the details including an existing subnet and existing VNET.
The reason for existing subnet and vnet is because it was configured to be part of our internal network.
It is important to specify the RG in the VNET name like ContosoRG:ContosoVNET1.  Also you must specify the subnet CIDR otherwise the Azure driver will try to modify the existing subnet and will fail (if you run the command in docker-machine).  

If you specify these parameters directly in a docker-machine create command the host is created properly however when executing an "Add Host" from Rancher I get the error below.

**Results:** 
Status=400 Code="InUseSubnetCannotBeUpdated" Message="Subnet ContosoSubnet1 is in use and cannot be updated." Details=[]

Again, with the same parameters passed to docker-machine create it will run successfully and not update my subnet.

**Comment by bmmathe** [comment]
I was using the VNET address range rather than the Subnet CIDR :(

**Comment by vincent99** [comment]
Just FYI the options are pretty much directly passed to docker-machine so it would be pretty unusual for us to be breaking something like that..

**Comment by bmmathe** [comment]
I'm having issues with the storage not being ready now.
Please use a storage account managed by Storage Resource Provider.
I read that this error might be related to docker-machine not waiting for the storage to be ready.
