### ISSUE TITLE
implicit issues with lb backend names

### ISSUE THREAD

**Issue by kaos** [rancher/rancher#8209]
Rancher: 1.4.1

There are some subtle issues that can arise from the use of backend name in the LB routing rules.

If you reuse the same backend name on several routing rules, the generated haproxy config does not end up as you want it to.

There are no hints, errors or other messages alerting you to this fact, other than to manually inspect the generated `haproxy.cfg`.

A check when setting a backend name to not allow duplicates would be in order ;)
(or, perhaps, auto append a sequence number to resolve any conflicts)

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
