### ISSUE TITLE
Restarting service make it unaccessible

### ISSUE THREAD

**Issue by PCXDME** [rancher/rancher#8211]
**Rancher Versions:**
Server: 1.5.1
healthcheck: 0.2.3
ipsec: 0.9.4
network-services: 0.4.8, metadata 0.8.11
scheduler: 0.7.4
kubernetes (if applicable):

**Docker Version:**
1.12.6
**OS and where are the hosts located? (cloud, bare metal, etc):**
RancherOS, bare metal
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher, internal DB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
I have upgraded RancherOS and Rancher. Forgotten the old version.
1. Have a running service that binds to port or linked from load balance
2. Right now, the service can be connected from internal, external IP.
3. Restart service
**Results:** 
The IP of service can not be connected from internal, external IP, can only be accessed in it's own container.

To make the service accessible, there are two ways.
1. Stop service then start
2. Upgrade service

**Comment by soumyalj** [comment]
@PCXDME : Tested with 1.5.1 on Ubuntu. Created service of scale 2 and also a loadbalancer pointing to the service. Restarted the service. After restart, the the containers of the service were reachable from the loadbalancer on the port specified. The containers of the service were pingable from containers of other service.
Although, we do see this issue occassionally https://github.com/rancher/rancher/issues/7625

**Comment by PCXDME** [comment]
I forgot to mention that Rancher DNS service discovery for Host network also did not work after upgrading.
I have **reinstall** RancherOS and Rancher Server and all the problem are gone.
Maybe it is caused by **upgrading** Rancher Server?

**Comment by superseb** [comment]
Closing as stale.
