### ISSUE TITLE
restart-policy set on service/container should not be set on the docker container.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#8216]
Rancher Versions: Build from master 

Steps to reproduce the problem:
Create a service/container with the following launch-config:
```
    launch_config = {"imageUuid": TEST_IMAGE_UUID,
                     "restartPolicy": {"name": "on-failure"},
                     "command": ["/bin/sh", "-c", "exit 3",
                                 ";", "echo", "$?"]
                     }
```
This results in following restartPolicy set on docker container:
```
            "RestartPolicy": {
                "Name": "on-failure",
                "MaximumRetryCount": 0
            },
```
Container gets restarted by both rancher and docker.

We expect only rancher to be handling the restartPolicy in this case. So restart-policy should not be set on docker run when this container is launched.

**Comment by alena1108** [comment]
@ibuildthecloud let us know at which point we should disable it on the backend - can be done now or when the refactored cattle code is reviewed/stabilized more.

**Comment by tfiduccia** [comment]
@deniseschannon Seems like the restart-policy was redone in 2.0.  Do you want to verify with Alena, that this is no longer an issue?
