### ISSUE TITLE
Attempt to create instances on deleted hosts for global services.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#8221]
Rancher Versions: Build from master

Steps to reproduce the problem:
Create a global service.
Deactivate and remove one of the existing hosts.
There is an attempt made to  create instances on deleted hosts which keeps failing.

**Comment by deniseschannon** [comment]
Fixed in wagyu branch

**Comment by sangeethah** [comment]
Rancher Versions: Build from master(07/07)

Steps to reproduce the problem:
Create a global service.
Deactivate and remove one of the existing hosts.
There is no repeated attempts made to create instances on deleted hosts anymore.
