### ISSUE TITLE
Rancher server stops responding when few hosts in the setup (with global services ) was deleted.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#8223]
Rancher Versions: Build from master

Set up had  7 hosts.
There were 2-3 global services running on these hosts.
Deleted  4 hosts from the setup.
After this Rancher server stops responding  and I am not able to load UI.

Following errors were seen repeatedly in logs:
```
```2017-03-17 23:36:27,145 INFO  [:] [] [] [] [cutorService-10] [i.c.p.c.v.impl.ConfigUpdatePublisher]         Finished work item stack:3 [661973574] with exception [class io.cattle.platform.async.utils.TimeoutException:Timeout] ```
```

**Comment by sangeethah** [comment]
Could be related to https://github.com/rancher/rancher/issues/8221

**Comment by deniseschannon** [comment]
Fixed in wagyu branch

**Comment by sangeethah** [comment]
Tested with rancher server build from master (07/07)
Had a set up with 3 host and had had global services running .
Deleted 1 host.

Rancher-server continues to be in good health and accessible.
