### ISSUE TITLE
Host IP address change result in a connect issue

### ISSUE THREAD

**Issue by rayang2004** [rancher/rancher#8224]
**Rancher Versions:**
Server:1.5.1
healthcheck:0.2.3
ipsec:
network-services: ipsec
scheduler:0.7.4
kubernetes (if applicable):

**Docker Version:1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):**
ubuntu 16.04 on aws

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
reboot the node on aws result in a ip change of the node
**Results:** 
Health-check and scheduller stack keep initializing,ssh with rancher cli use the old ip address of the node.

**Comment by aemneina** [comment]
@rayang2004 this is expected behavior. If you rerun the host registration your hosts IP address will update. IPSec should working again and health checks start passing.
