### ISSUE TITLE
Created EC2 Hosts stuck at 'Installing Rancher agent'

### ISSUE THREAD

**Issue by btro** [rancher/rancher#8225]
**Rancher Versions:**
Server: 1.5.1
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker Version:**
Rancher server:
 Version:      1.12.6
 API version:  1.24
**OS and where are the hosts located? (cloud, bare metal, etc):**
AWS default OS (no change when selecting "add Host"
Rancher VM: Ubuntu 14.04 64, AWS
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node (docker quick start guide)
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
cattle
**Steps to Reproduce:**
Create cattle env
Add hosts
Select EC2
Enter credentials 
Add to same Availability Zone as Rancher Server
Use security group provided by Rancher
Select 3 micro instances (everything set to default)
Create, wait, never finishes

**Results:** 
Stuck at 'Installing Rancher agent'

Any idea what the problem could be?

**Comment by jurajseffer** [comment]
I'd log into the instances and check they have internet access and inspect the security group applied to rancher server and nodes.

**Comment by vincent99** [comment]
Installing the agent suggests it was able to SSH to the host to install docker but that the registration URL for rancher is either wrong, unreachable, or untrusted (self-signed SSL cert),

**Comment by btro** [comment]
I'm not sure, but I think I don't have the ssh keypair which is used for rolling out the machines. They have been created by Rancher itself. 
@vincent99 The untrusted cert is possibly the problem, any idea/hint how I can fix that? I don't have a CA signed cert at hand.

**Comment by btro** [comment]
ok, I fixed it by using http:// instead of https:// for the registration URL. Thanks for the hint guys!
