### ISSUE TITLE
Cattle: multiple healthchecks per service and healthcheck command exec in rancher-compose

### ISSUE THREAD

**Issue by ketchoop** [rancher/rancher#8227]
Just why not? It seems not to be so hard to implement and really useful. E.g. Kube has it.

**Comment by Moeser** [comment]
Health check support in rancher could really use some more love.  I've recently been needing docker exec health checks as well.  Have also needed udp health checks, or health check actions that can do more than just re-launch the container. (Actions like roll back the service if the rollback option is still available? Or some way to fail over to a secondary stack in a blue/green stack setup?  Or just run a container that can use the api to implement whatever health-recovery strategy we need, anything but blindly relaunch the container endlessly).

This issue would be a great starting point though, but it wasn't added to milestone, or even commented on.  Is there a public roadmap that explains what features/enhancements will be prioritized?

**Comment by ingardm** [comment]
👍

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
