### ISSUE TITLE
[go-rancher] creation of hosts with custom docker machine drivers not supported

### ISSUE THREAD

**Issue by bfosberry** [rancher/rancher#8228]
**Rancher Versions:**
Server: *
healthcheck: *
ipsec: *
network-services: *
scheduler: *
kubernetes (if applicable): *

**Docker Version:**
Any

**OS and where are the hosts located? (cloud, bare metal, etc):**
Any

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Any

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Any

**Steps to Reproduce:**
Try to use the go-rancher bindings to create a custom docker-machine driver host

**Results:** 
go-rancher does not support injecting custom json fields in order to support customer docker-machine driver.

e.x using the vultr docker-machine driver, the API supports and expects {"hostname": "bhal", "vultrConfig":{"etc": "abc"}}, however there is no way using the generate host struct in go-rancher to marshal into this json field. As a result it is impossible to support host creation with custom docker machine drivers, even though the API supports it.

Suggested fixes: (one of)
1) Update Create (https://github.com/rancher/go-rancher/blob/master/v2/generated_host.go#L145) to accept interface type, which would allow annonymous struct extension
2) Update the generic doCreate (https://github.com/rancher/go-rancher/blob/master/v2/common.go#L406) to inject extra args as need and update all Create calls for resources to allow passing those
3) Update doCreate/Create to pass an interface which would allow the extraction of extra args

**Comment by joshwget** [comment]
Hi @bfosberry, I'm pretty sure what you're looking to do is possible with the generic `Create` API call. I create hosts from arbitrary drivers [here](https://github.com/rancher/rancher-compose-executor/blob/master/rancher/host.go#L143). Let me know if that's what you're looking for!

**Comment by bfosberry** [comment]
That is exactly what I need to do, it feels kinda shitty to use the underlying client directly like this, but dynamic type handling isnt a strongpoint of Go and this unblocks me for now!

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
