### ISSUE TITLE
Rancher 1.4.1 VxLan performance is terrible.

### ISSUE THREAD

**Issue by henrypfhu** [rancher/rancher#8229]
**Rancher Versions:**
Server: rancher/server  v1.4.1  a00ee3070422  4 weeks ago 950.6 MB
healthcheck: rancher/healthcheck  v0.2.3  491349141109    7 weeks ago  383.3 MB

rancher/network-manager                   v0.4.5.1            ee435e0593f6        2 days ago          241.7 MB
rancher/metadata                        v0.7.3              4509d408a416        2 weeks ago         246.9 MB
rancher/server                          latest              a00ee3070422        4 weeks ago         950.6 MB
rancher/server                          v1.4.1              a00ee3070422        4 weeks ago         950.6 MB
rancher/scheduler                       v0.6.3              e9fbe11760fd        6 weeks ago         243.7 MB
rancher/agent                           v1.2.0              24d2df8fa301        6 weeks ago         233.7 MB
rancher/net                             v0.8.7              332e26ab5cba        7 weeks ago         264.4 MB
rancher/dns                             v0.13.3             a5567dd898f0        7 weeks ago         239.9 MB
rancher/healthcheck                     v0.2.3              491349141109        7 weeks ago         383.3 MB
rancher/lb-service-haproxy              v0.5.9              7e77aadd5d9e        7 weeks ago         334.1 MB

kubernetes (if applicable): N/A

**Docker Version:**
docker -v
Docker version 1.12.6, build 78d1802

**OS and where are the hosts located? (cloud, bare metal, etc):**
uname -a
Linux DevOps-Master 4.4.52-1.el7.elrepo.x86_64 #1 SMP Sun Feb 26 08:48:14 EST 2017 x86_64 x86_64 x86_64 GNU/Linux
cat /etc/centos-release
CentOS Linux release 7.2.1511 (Core)
Running in QingCloud.com

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node Rancher, External DB Mysql

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Network Using**
VxLan

**Environment Infrastructure**
![image](https://cloud.githubusercontent.com/assets/8036030/24077767/eb3e8e10-0c92-11e7-8a3c-b0ca2a0408dc.png)

**Steps to Reproduce: Performance is good**
***HostB --> HostA***
HostA run iperf3 -s
![image](https://cloud.githubusercontent.com/assets/8036030/24077655/6d51fc8c-0c90-11e7-8629-a13881fe7fee.png)

HostB run iperfs -c hosta
![image](https://cloud.githubusercontent.com/assets/8036030/24077658/8f310154-0c90-11e7-8fc8-54f4e573aa7e.png)

***Docker InstanceB on HostB --> HostA****
![image](https://cloud.githubusercontent.com/assets/8036030/24077684/104314f8-0c91-11e7-8370-8b99e9265045.png)

**Steps to Reproduce: Performance is bad using VxLan between docker instances on different Hosts**
***Docker InstanceB on HostB --> Docker InstanceA on HostA****
![image](https://cloud.githubusercontent.com/assets/8036030/24077712/250ecaca-0c92-11e7-9b9e-3c218b682589.png)

![image](https://cloud.githubusercontent.com/assets/8036030/24077716/58c14b04-0c92-11e7-993a-d48848b4d345.png)

**Comment by henrypfhu** [comment]
Anybody using VxLan met the same issue?

**Comment by aemneina** [comment]
@henrypfhu are you using 10Gig nics? Looks like you're getting 9Gigs throughput... which would be inline with expectations of 10% overhead.

**Comment by vincent99** [comment]
@aemneina Those are the direct host->host numbers.. The last screen for container->container shows ~99.95% overhead.

**Comment by aemneina** [comment]
Thanks for pointing that out @vincent99, that's abysmal performance. @leodotcloud I wonder if a smaller MTU is hurting vxlan, all the recommendations I see around it to to add about 50 bytes or go jumbo frames.

**Comment by ibuildthecloud** [comment]
That is horrendous, that's not normal.  @leodotcloud Thoughts?

**Comment by henrypfhu** [comment]
Additional information:
If I use IPSec Infrastructure between Docker instances on different Hosts, the iperf test result is about 290Mbits/sec. It's much better than VxLAN, but it's still too heavy effort used in unkown step. 

For these two scenarios, I checked the CPU,  all CPU are idle, CPU is not the bottleneck.

It's weird.

**Comment by leodotcloud** [comment]
@ibuildthecloud @henrypfhu The last time I measured the stats using `iperf`, VXLAN was definitely better than IPSec.

@henrypfhu Can you please share your setup/topology details? Steps to reproduce on my end? What images are you using to run the containers?
From the screenshot of the containers, I don't see any IP address in the `10.42.0.0/16` subnet. Did you customize something?

Can you please share output of the following commands?

On both hosts:
- `ip addr`
- `ip route`
- `ip neigh`

Inside the containers on both sides:
- `ip addr`
- `ip route`
- `ip neigh`
- `bridge fdb show`

@aemneina The above commands will display the MTU details as well.

**Comment by henrypfhu** [comment]
For question: From the screenshot of the containers, I don't see any IP address in the 10.42.0.0/16 subnet. Did you customize something?
I change the subnet from the default 10.42.0.0/16 to 10.254.0.0/16.

** For HostA  ip addr **
[root@Demo-Server01 ~]# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 52:54:ef:16:6e:e2 brd ff:ff:ff:ff:ff:ff
    inet 10.39.0.18/24 brd 10.39.0.255 scope global dynamic eth0
       valid_lft 63239sec preferred_lft 63239sec
    inet6 fe80::5054:efff:fe16:6ee2/64 scope link
       valid_lft forever preferred_lft forever
3: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP
    link/ether 02:42:31:8b:07:29 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 scope global docker0
       valid_lft forever preferred_lft forever
    inet 10.254.0.1/16 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:31ff:fe8b:729/64 scope link
       valid_lft forever preferred_lft forever
52: vethd1e8957@if51: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP
    link/ether 7e:f3:ad:59:34:7e brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::7cf3:adff:fe59:347e/64 scope link
       valid_lft forever preferred_lft forever
81: veth05ae75ed@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP
    link/ether ba:2c:50:43:45:05 brd ff:ff:ff:ff:ff:ff link-netnsid 1
    inet6 fe80::b82c:50ff:fe43:4505/64 scope link
       valid_lft forever preferred_lft forever
82: vethc5ecd797@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP
    link/ether 02:6b:26:ba:32:24 brd ff:ff:ff:ff:ff:ff link-netnsid 2
    inet6 fe80::6b:26ff:feba:3224/64 scope link
       valid_lft forever preferred_lft forever
83: vetha84e3722@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP
    link/ether 02:cd:0f:31:b6:7a brd ff:ff:ff:ff:ff:ff link-netnsid 3
    inet6 fe80::cd:fff:fe31:b67a/64 scope link
       valid_lft forever preferred_lft forever
84: vethafbad11d@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP
    link/ether fe:a9:ff:60:27:70 brd ff:ff:ff:ff:ff:ff link-netnsid 4
    inet6 fe80::fca9:ffff:fe60:2770/64 scope link
       valid_lft forever preferred_lft forever
85: veth2c9142e6@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP
    link/ether 92:13:f0:28:9b:ef brd ff:ff:ff:ff:ff:ff link-netnsid 5
    inet6 fe80::9013:f0ff:fe28:9bef/64 scope link
       valid_lft forever preferred_lft forever
95: veth0f54b74a@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP
    link/ether 22:39:04:87:5a:fb brd ff:ff:ff:ff:ff:ff link-netnsid 6
    inet6 fe80::2039:4ff:fe87:5afb/64 scope link
       valid_lft forever preferred_lft forever
[root@Demo-Server01 ~]#

** For HostA ip route **
[root@Demo-Server01 ~]# ip route
default via 10.39.0.1 dev eth0  proto static  metric 100
10.39.0.0/24 dev eth0  proto kernel  scope link  src 10.39.0.18  metric 100
10.254.0.0/16 dev docker0  proto kernel  scope link  src 10.254.0.1
169.254.169.250 dev docker0  scope link
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.0.1
[root@Demo-Server01 ~]#

** For HostA ip neigh **
[root@Demo-Server01 ~]# ip neigh
10.254.135.151 dev docker0 lladdr 02:a8:c3:0e:80:48 REACHABLE
10.39.0.9 dev eth0 lladdr 52:54:97:1f:9c:9d REACHABLE
10.254.247.82 dev docker0 lladdr 02:a8:c3:7d:cf:7f STALE
10.254.52.60 dev docker0 lladdr 02:a8:c3:ba:4e:47 STALE
10.254.124.127 dev docker0 lladdr 02:a8:c3:44:f8:50 STALE
10.254.218.79 dev docker0 lladdr 02:a8:c3:5a:2b:8b REACHABLE
10.254.83.91 dev docker0 lladdr 02:a8:c3:10:c6:2a STALE
10.254.127.90 dev docker0 lladdr 02:a8:c3:33:cd:0b STALE
10.39.0.21 dev eth0 lladdr 52:54:fb:47:0f:82 REACHABLE
10.254.226.69 dev docker0 lladdr 02:a8:c3:77:85:0e REACHABLE
10.254.88.56 dev docker0  FAILED
10.254.145.224 dev docker0 lladdr 02:a8:c3:64:cf:11 STALE
10.39.0.38 dev eth0 lladdr 52:54:18:d3:99:db STALE
10.254.111.42 dev docker0 lladdr 02:a8:c3:25:76:21 STALE
10.254.89.70 dev docker0  FAILED
10.254.84.137 dev docker0 lladdr 02:a8:c3:4f:46:c5 STALE
10.254.201.247 dev docker0  FAILED
172.17.0.2 dev docker0 lladdr 02:c2:08:df:d2:7e REACHABLE
169.254.169.250 dev docker0 lladdr 02:c2:08:df:d2:7e REACHABLE
10.39.0.1 dev eth0 lladdr 02:54:d4:90:3a:57 REACHABLE
10.254.43.177 dev docker0 lladdr 02:a8:c3:75:0a:fc STALE
10.254.6.125 dev docker0 lladdr 02:a8:c3:db:79:36 STALE
10.254.226.31 dev docker0 lladdr 02:a8:c3:17:6e:e6 STALE
10.39.0.22 dev eth0 lladdr 52:54:48:0f:8c:f7 REACHABLE
[root@Demo-Server01 ~]#


** For HostB ip addr **
[root@Demo-Server02 ~]# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 52:54:fb:47:0f:82 brd ff:ff:ff:ff:ff:ff
    inet 10.39.0.21/24 brd 10.39.0.255 scope global dynamic eth0
       valid_lft 81131sec preferred_lft 81131sec
    inet6 fe80::5054:fbff:fe47:f82/64 scope link
       valid_lft forever preferred_lft forever
3: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP
    link/ether 02:42:4b:b2:4f:35 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 scope global docker0
       valid_lft forever preferred_lft forever
    inet 10.254.0.1/16 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:4bff:feb2:4f35/64 scope link
       valid_lft forever preferred_lft forever
34: veth1e604ec@if33: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP
    link/ether e6:03:95:dc:05:7e brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::e403:95ff:fedc:57e/64 scope link
       valid_lft forever preferred_lft forever
57: veth648297ba@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP
    link/ether fa:ea:bd:0d:8d:30 brd ff:ff:ff:ff:ff:ff link-netnsid 2
    inet6 fe80::f8ea:bdff:fe0d:8d30/64 scope link
       valid_lft forever preferred_lft forever
58: veth8139577e@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP
    link/ether 9e:08:c8:b5:59:26 brd ff:ff:ff:ff:ff:ff link-netnsid 3
    inet6 fe80::9c08:c8ff:feb5:5926/64 scope link
       valid_lft forever preferred_lft forever
60: veth9498c652@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP
    link/ether ee:f8:a2:54:3b:97 brd ff:ff:ff:ff:ff:ff link-netnsid 1
    inet6 fe80::ecf8:a2ff:fe54:3b97/64 scope link
       valid_lft forever preferred_lft forever
[root@Demo-Server02 ~]#

** For HostB ip route **
[root@Demo-Server02 ~]# ip route
default via 10.39.0.1 dev eth0  proto static  metric 100
10.39.0.0/24 dev eth0  proto kernel  scope link  src 10.39.0.21  metric 100
10.254.0.0/16 dev docker0  proto kernel  scope link  src 10.254.0.1
169.254.169.250 dev docker0  scope link
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.0.1
[root@Demo-Server02 ~]#

** For HostB ip neigh **
[root@Demo-Server02 ~]# ip neigh
10.254.56.151 dev docker0 lladdr 02:a8:c3:d3:29:0b STALE
10.254.22.148 dev docker0 lladdr 02:a8:c3:0c:65:2e STALE
10.254.146.165 dev docker0 lladdr 02:a8:c3:e1:13:2d REACHABLE
10.39.0.18 dev eth0 lladdr 52:54:ef:16:6e:e2 DELAY
10.254.153.216 dev docker0 lladdr 02:a8:c3:bd:39:2d STALE
169.254.169.250 dev docker0 lladdr 02:c2:08:e7:cb:a9 REACHABLE
10.254.223.83 dev docker0 lladdr 02:a8:c3:49:48:48 STALE
10.254.216.73 dev docker0 lladdr 02:a8:c3:b3:12:18 STALE
10.254.145.250 dev docker0  FAILED
10.254.189.60 dev docker0 lladdr 02:a8:c3:21:20:57 REACHABLE
10.254.61.240 dev docker0 lladdr 02:a8:c3:d5:6c:88 STALE
10.254.20.227 dev docker0  FAILED
10.39.0.9 dev eth0 lladdr 52:54:97:1f:9c:9d REACHABLE
10.254.228.98 dev docker0 lladdr 02:a8:c3:09:76:b7 STALE
172.17.0.2 dev docker0 lladdr 02:c2:08:e7:cb:a9 DELAY
10.254.210.156 dev docker0 lladdr 02:a8:c3:31:c4:ec STALE
10.254.175.208 dev docker0 lladdr 02:a8:c3:4f:02:68 STALE
10.254.60.187 dev docker0 lladdr 02:a8:c3:07:45:dc STALE
10.254.193.205 dev docker0 lladdr 02:a8:c3:af:d0:d8 STALE
10.254.135.25 dev docker0 lladdr 02:a8:c3:d3:be:cf STALE
10.254.60.53 dev docker0 lladdr 02:a8:c3:c6:0b:1c STALE
10.254.138.46 dev docker0 lladdr 02:a8:c3:55:61:f9 STALE
10.39.0.22 dev eth0 lladdr 52:54:48:0f:8c:f7 REACHABLE
10.39.0.27 dev eth0 lladdr 52:54:2c:1a:8c:21 STALE
10.254.252.176 dev docker0 lladdr 02:a8:c3:b7:23:59 STALE
10.254.82.95 dev docker0  FAILED
10.254.82.163 dev docker0 lladdr 02:a8:c3:bc:95:77 STALE
10.39.0.1 dev eth0 lladdr 02:54:d4:90:3a:57 REACHABLE
10.254.15.134 dev docker0 lladdr 02:a8:c3:27:80:5c STALE
10.254.25.111 dev docker0  FAILED
10.254.2.187 dev docker0 lladdr 02:a8:c3:73:4b:6a STALE
10.254.63.131 dev docker0 lladdr 02:a8:c3:15:4a:d7 REACHABLE

**Comment by henrypfhu** [comment]
**For Docker InstanceA on HostA ip addr**
bash-4.3# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
3: eth0@if85: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1450 qdisc noqueue state UP
    link/ether 02:a8:c3:77:85:0e brd ff:ff:ff:ff:ff:ff
    inet 10.254.226.69/16 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::a8dd:24ff:fea3:62bb/64 scope link tentative flags 08
       valid_lft forever preferred_lft forever

**For Docker InstanceA on HostA ip route**
bash-4.3# ip route
default via 10.254.0.1 dev eth0
10.254.0.0/16 dev eth0  src 10.254.226.69
169.254.169.250 via 10.254.0.1 dev eth0

**For Docker InstanceA on HostA ip neigh**
bash-4.3# ip neigh
10.254.0.1 dev eth0 lladdr 02:42:31:8b:07:29 ref 1 used 0/0/0 probes 1 REACHABLE
10.254.5.33 dev eth0 lladdr 02:a8:c3:0e:80:48 ref 1 used 0/0/0 probes 1 REACHABLE
10.254.86.41 dev eth0 lladdr 02:a8:c3:0e:80:48 ref 1 used 0/0/0 probes 5 INCOMPLETE
10.254.88.56 dev eth0 lladdr 02:a8:c3:b7:ac:b7 used 0/0/0 probes 1 STALE
10.254.146.165 dev eth0 lladdr 02:a8:c3:0e:80:48 ref 1 used 0/0/0 probes 1 REACHABLE
10.254.164.153 dev eth0 lladdr 02:a8:c3:c9:c2:0e ref 1 used 0/0/0 probes 1 REACHABLE
10.254.189.60 dev eth0 lladdr 02:a8:c3:0e:80:48 ref 1 used 0/0/0 probes 1 DELAY
10.254.135.151 dev eth0 lladdr 02:a8:c3:0e:80:48 used 0/0/0 probes 0 STALE
10.254.83.91 dev eth0 lladdr 02:a8:c3:0e:80:48 used 0/0/0 probes 6 FAILED
10.254.87.119 dev eth0 lladdr 02:a8:c3:0e:80:48 used 0/0/0 probes 1 STALE
10.254.84.137 dev eth0 lladdr 02:a8:c3:4f:46:c5 used 0/0/0 probes 0 STALE


**For Docker InstanceB on HostB ip addr**
bash-4.3# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
3: eth0@if60: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1450 qdisc noqueue state UP
    link/ether 02:a8:c3:21:20:57 brd ff:ff:ff:ff:ff:ff
    inet 10.254.189.60/16 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::1095:b2ff:fef5:26f2/64 scope link tentative flags 08
       valid_lft forever preferred_lft forever

**For Docker InstanceB on HostB ip route**
bash-4.3# ip route
default via 10.254.0.1 dev eth0
10.254.0.0/16 dev eth0  src 10.254.189.60
169.254.169.250 via 10.254.0.1 dev eth0

**Comment by vincent99** [comment]
IPSec should be mostly limited by the speed of the AES-NI in the CPU, which [varies considerably](https://calomel.org/aesni_ssl_performance.html) by SKU.

**Comment by henrypfhu** [comment]
Any progress for this VxLan performance issue?

**Comment by niusmallnan** [comment]
Test on AWS China, also use VXLAN networking.

host-> host :
![image](https://cloud.githubusercontent.com/assets/998984/24339616/7f5061d0-12df-11e7-92ee-3669ff91dcde.png)

container->container :
![image](https://cloud.githubusercontent.com/assets/998984/24339640/9c660f7c-12df-11e7-92f1-4d828ef5b1d7.png)

The performance seems good.

I see that you are running Rancher on Qingcloud.com. I guess the root cause is MTU. Because AWS use MTU 9001, it is Huge Jumbo Frame.

I am an engineer in Rancher China, maybe I can help you more.
@henrypfhu can you add my Wechat(id: niusmallnan)?

**Comment by henrypfhu** [comment]
@niusmallnan I changed the eth0 MTU default value to 9001, and reboot all related hosts. The testing results are same as before, improved nothing.

**Comment by henrypfhu** [comment]
@niusmallnan Even I changed the eth0 MTU value to 9001, but veth network MTU values are still 1500. How can I change these veth networks?

**Comment by niusmallnan** [comment]
Test on Qing public cloud.
container --> container (vxlan)
![image](https://cloud.githubusercontent.com/assets/998984/24387783/b8f1148c-13a9-11e7-970f-94374d6c46bc.png)

@henrypfhu  The performance seems good.

**Comment by leodotcloud** [comment]
@henrypfhu You cannot change the MTU of `eth0`, this is dictated by the actual cloud provider. If the underlying network's MTU doesn't match with `eth0`, it will cause performance issues. Also if your servers are not bare metal servers but Virtual Machines, the network throughput of 1Gbps is not completely dedicated at all times.

> Even I changed the eth0 MTU value to 9001, but veth network MTU values are still 1500. How can I change these veth networks?

The MTU is configurable when you create a new Environment template using VXLAN catalog item.

One more point to remember is to restart docker with the appropriate MTU. If you have configured `eth0` to be 9000 and the same for VXLAN catalog but docker is still running as 1500, you will hit performance issues.

**Comment by superseb** [comment]
@henrypfhu Any updates on this? Are you still experiencing bad performance on VXLAN?

**Comment by superseb** [comment]
Please comment if you still need help with this.

**Comment by segator** [comment]
I have same problem,
Host -- Host  13,7Gbits/sec
Using containers but connecting using Host IP
Container -- Container  150Mbits/sec
Using Rancher Managed Network I tried both IPSEC and VXLAN(NO Cpu overhead when testing)

The setup is a ubuntu host running 2 docker machine (KVM)
MTU default

**Comment by leodotcloud** [comment]
We have changes in how VXLAN is implemented: https://github.com/rancher/rancher/issues/9414. This will significantly improve the performance. Targeted for 1.6.11 release.
If you have MTUs more than 1500, we still have a pending issue: https://github.com/rancher/rancher/issues/9774.

**Comment by JamesColeman-LW** [comment]
Just a note, I had similar performance issues as mentioned and was able to resolve it by turning off hardware acceleration on the vxlan interface itself:

```
ethtool -K vxlan100 tx off rx off
```
