### ISSUE TITLE
Rancher Agent 0.60 on Windows Nano 2016

### ISSUE THREAD

**Issue by calloes** [rancher/rancher#8230]
**Rancher Versions:**
Server:1.4.2
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker Version:17.03.0-ee-117.03.0-ee-1

**OS and where are the hosts located? (cloud, bare metal, etc):Windows Nano 2016

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)Cattle

**Steps to Reproduce:Rancher Agent 0.6.0 fails to start.

[nano-server1]: PS C:\Users\Administrator\Documents> get-content C:\ProgramData\rancher\agent.log
time="2017-03-20T11:12:44+11:00" level=error msg="Error while downloading error: Get /scripts/api.
crt: unsupported protocol scheme \"\"" 
time="2017-03-20T11:12:44+11:00" level=error msg="registration failed. err: Get /scripts/api.crt: 
unsupported protocol scheme \"\"" 

Trying to get rancher agent to start on Windows 2016 Nano, have stopped firewall etc etc docker running is high version

[nano-server1]: PS C:\Users\Administrator\Documents> docker version
Client:
 Version:      17.03.0-ee-1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   9094a76
 Built:        Wed Mar  1 00:49:51 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.03.0-ee-1
 API version:  1.26 (minimum version 1.24)
 Go version:   go1.7.5
 Git commit:   9094a76
 Built:        Wed Mar  1 00:49:51 2017
 OS/Arch:      windows/amd64
 Experimental: false

**Comment by StrongMonkey** [comment]
@calloes Can you check if your rancher server is reachable from your 2016 windows nano server by the IP you put in the registration url?

**Comment by calloes** [comment]
Definitely i have rancheros boxes on the same network that work fine, from the nano server i can hit 443 of my rancher server, also the github download of the agent works fine.

**Comment by StrongMonkey** [comment]
I am wondering if the registration url is unreachable(the url is wrong, untrusted certs(self signed certs) from the agent.

**Comment by superseb** [comment]
Can you share the command you used to register the agent? Please remove any sensitive info.

**Comment by linusyong** [comment]
I have a similar problem:

Rancher Server 
- OS: CentOS 7.3.1611
- Rancher Server Version: v1.6.4
- Docker version: 17.06.0-ce

Rancher Host:
- OS: Windows Server 2016
- Agent version: 0.6.0
- Docker version: 17.03.1-ee-3

Environment:
- Using a corporate proxy (both http and https), authenticated, with self-signed certificate.

PS C:\>Get-Content C:\ProgramData\rancher\agent.log
time="2017-07-20T08:22:07+10:00" level=error msg="Error while downloading error: Get /scripts/api.crt: unsupported protocol schema \"\""
time="2017-07-20T08:22:07+10:00" level=error msg="registration failed. err: Get /scripts/api.crt: unsupported protocol schema \"\""

I registered the agent via:
PS C:\> & 'C:\Program Files\rancher\agent.exe' -url http://10.x.x.x:8080/v1/scripts/50BFxxxxxxxxxxxxxxx:1483xxxxxxxxx:bqbBXxxxxxxxxxxxxxxxxxxxx
PS C:\> Start-Service rancher-agent

Also verified that the url is reachable:

PS C:\> curl http://10.x.x.x:8080/v1/scripts/50BFxxxxxxxxxxxxxxx:1483xxxxxxxxx:bqbBXxxxxxxxxxxxxxxxxxxxx

StatusCode           : 200
StatusDescription : OK
... ... ...

and my docker installation can pull images from DockerHub:

PS C:\> docker pull openjdk:8u131-jdk-nanoserver
8u131-jdk-nanoserver: Pulling from library/openjdk
Digest: sha256:7607050daa6e08d984... ... ...
... ... ...

**Comment by schulzp** [comment]
I'm running into the same issue trying to register a Windows 2016 Server as rancher host/agent. @calloes / @linusyong could you figure out a solution/workaround?

**Comment by schulzp** [comment]
I did some digging, here is what I found out: When the agent(.exe) starts it GETs the URL passed to -register-service which returns a bash script defining environment some variables, e.g. `CATTLE_URL`. If that first GET fails the CATTLE_URL is not defined and when the agent tries to GET `CATTLE_URL + '/scripts/api.crt'` that effective URL is `/scripts/api.crt` [which the GO runtime cannot deal with](http://nanxiao.me/en/fix-unsupported-protocol-scheme-issue-in-golang/).

In my case the first GET failed due to firewall rules. In order to fix that all I had to add static hostname-IP-mappings in `C:\Windows\System32\drivers\etc\hosts` pointing to the internal IP of the reverse proxy in front of the rancher service et vóila it works.

@calloes, @linusyong please see `C:\ProgramData\rancher` for `agent|panic.log` and make sure `etc\Cattle\api.crt` is not empty (which is another indicator for the service not being reachable).

**Comment by superseb** [comment]
Closing as stale.
