### ISSUE TITLE
Upgrading hostname through catalog for a LB causes stack to get stuck

### ISSUE THREAD

**Issue by VAdamec** [rancher/rancher#8233]
**Rancher Versions:**
Server: 1.5.1
healthcheck: up2date
ipsec: up2date
network-services: up2date
scheduler: up2date

**Rancher compose:**
Tested versions from v0.12.3 to last RC (v0.12.4-rc1)

**Docker Version:**
1.13.1

**OS and where are the hosts located? (cloud, bare metal, etc):**
OpenStack

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher + ext DB (Galera)

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Setup and create new stack with lb_config and hostname set, for example:

- rancher-compose.yml

```
  wordpress:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - hostname: test-1.example.com
        target_port: 80
```

than change hostname to different value and update/upgrade/force upgrade/recreate, none of these operation will change it (UI or HAproxy setup)

**Results:** 
LB and GUI no change in hostname setup, keep same value. Only possible way is to ```delete and create``` stack again. 

Also good to mention, LB configuration is copied to all sidekicks, not sure If this is correct behaviour.

**Comment by tfiduccia** [comment]
@VAdamec - I am able to change the hostname through the UI.  But it's not working if you are trying to do it by upgrading a stack through the catalog service.

Version - v1.5.3
Steps:
1.  Create a catalog where you have two version.
2.  Version1 has a service and lb pointing to it
3.  Version2 just adds a -hostname = test-1.example.com
4.  Deploy version1
5.  Upgrade stack to version2

Results:  Stack gets stuck in Upgrading (upgrading stack) and no services update.  I have to cancel and rollback to get stack to resolve.

**Comment by VAdamec** [comment]
How do you change it via UI ? I don't see lb_config in UI at all (only in Compose YAML view) but no option to edit it. I'll try catalog, but that mean change of how we deploy stacks.

**Comment by tfiduccia** [comment]
@VAdamec - the hostname will actually exist in the load balancer service itself.  I just sent you picture in other bug... but here it is again:

![image](https://cloud.githubusercontent.com/assets/11514927/24394068/5fc6262c-134f-11e7-99b4-72dce23a3b5f.png)

**Comment by VAdamec** [comment]
![screen shot 2017-03-28 at 9 55 07 am](https://cloud.githubusercontent.com/assets/5555130/24394546/a94f9ea2-139c-11e7-9e9e-9f46741f8978.png)

this is my simple setup in balancer. Everything else (like request host) is service/stack specific. And using lb_config in services works, you just cannot set it up during service creation (#8237) and than you can't change it (this issue).

**Comment by tfiduccia** [comment]
Repeat from previous bug but just in case you didn't see it there:

Although you can't see the rule through the UI, you can go to the shell in the load balancer container and go to 'cat /etc/haproxy/haproxy.cfg' to see the list of rules there.

**Comment by VAdamec** [comment]
Not sure if the stuck issue If you use catalog is same, as via CLI I don't get any issue, just change is not reflected (and Haproxy still sees original hostname).

```
version: '2'
services:
  test:
    start_on_create: true
    lb_config:
      port_rules:
      - hostname: ${DOMAIN}
        target_port: 8080
```

1. Run
```DOMAIN=test1.example.com rancher-compose --project-name test up -d --force-upgrade```
2. Run with hostname set to test2.example.com
```DOMAIN=test2.example.com rancher-compose --project-name test  up -d --force-upgrade```
3. Service is upgraded (new container started), but hostname is not changed, still test1.example.com

only removing service and create it again help (but then I'm hitting #7892)

**Comment by tfiduccia** [comment]
Looks like you can't edit/update selector rules that are created through service using lb_config.

**Comment by VAdamec** [comment]
Any luck with this issue ? I would say it complicate any reasonable deployment.  Or everybody use blue&green and always delete service before update ? :-)

**Comment by VAdamec** [comment]
Any update ? It's quite annoying bug

**Comment by VAdamec** [comment]
Still cannot change some already provisioned parameters from rancher-compose.yml. As nobody solving it I take it as a feature.
