### ISSUE TITLE
Port open on both LB and service

### ISSUE THREAD

**Issue by nsimmonds** [rancher/rancher#8236]
A mistake we made in our rancher-compose file was to open a udp port (12201) that was also exposed on one of the services. Rancher would let us do this without complaint, and then traffic to that port would simply fail. In addition, the UI would no longer allow upgrades, because every change triggered an error regarding the invalid port. Finding the issue in our own files and updating fixed both issues.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.5.1` Cattle: `v0.177.8` UI: `v1.5.7` |
|Access|`Disabled`|
|Orchestration|`Cattle`|
|Route|`service.containers`|

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
