### ISSUE TITLE
Host get overridden when adding new host

### ISSUE THREAD

**Issue by danielschlegel** [rancher/rancher#8238]
I have 4 Hosts in a rancher kubernetes environment. If i add a 5th host the 4th is getting overridden. They have different ip addresses and are different VM's behind.
How can this happen. Whats the id(ip address?) that rancher uses to separate one host from each other?

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.4.2` Cattle: `v0.176.10` UI: `v1.4.9` |
|Access|`github` `admin`|
|Orchestration|`Kubernetes`|
|Route|`hosts.index`|

**Comment by aemneina** [comment]
Do your hosts go through a NAT to reach the rancher server? The server will use the source IP of the connection as a detection method when adding the host. To override this behavior you can use CATTLE_AGENT_IP when registering the agent hosts.

**Comment by danielschlegel** [comment]
I found some logs.

```
time="2017-03-22T16:39:48Z" level=info msg="Handling backend connection request." 
time="2017-03-22T16:39:48Z" level=info msg="Registering backend for host cc1d8c06-ae48-46eb-6ba6-39fe1892cdd6 with session ID ae28fac9-4027-47d8-90c8-28ad1b34c3e3." 
2017/03/22 16:40:09 http: proxy error: net/http: request canceled
time="2017-03-22T16:40:09Z" level=info msg="Shutting down backend cc1d8c06-ae48-46eb-6ba6-39fe1892cdd6. Connection closed because: websocket: close 1006 unexpected EOF." 
time="2017-03-22T16:40:09Z" level=info msg="Not removing backend for key cc1d8c06-ae48-46eb-6ba6-39fe1892cdd6. The provided session ID e075efcf-e56d-439b-9d36-404edd452a8a doesn't match registered session ID ae28fac9-4027-47d8-90c8-28ad1b34c3e3." 
2017-03-22 16:40:09,895 ERROR [0e4eb2d8-f6d5-4f7d-b98a-74281318d483:1460] [service:8] [service.update] [] [cutorService-10] [c.p.e.p.i.DefaultProcessInstanceImpl] Expected state running but got removed 
```

**Comment by danielschlegel** [comment]
I have updated to rancher version 1.5.2 but i still have the same issue. Is the IP really the UUID that rancher takes for adding hosts?

**Comment by vincent99** [comment]
No, there's a uuid in `/var/lib/rancher/state` and in newer versions a docker volume named `rancher-agent-state`.  If you're imaging the hosts you need to remove that first, or image or before ever adding it as a host.

**Comment by danielschlegel** [comment]
I could solve the problem. Unfortunately i don't know the exact problem but it was related to a copied VM. After Setting up new VM instead of cloning it works like it should.
