### ISSUE TITLE
add new aws instance types t2.xlarge and t2.2xlarge

### ISSUE THREAD

**Issue by spender0** [rancher/rancher#8239]
**Rancher Versions:**
Server: 1.5.1

**Steps to Reproduce:**

1. Try to add Amazon EC2 Host
2. Try to find  t2.xlarge or t2.2xlarge in "Instance type"

**Results:** 
It is not possible to add t2.xlarge and t2.2xlarge

**Comment by vincent99** [comment]
https://github.com/rancher/ui/commit/1b37daca7f5349883937742c5fdabab3df1755d8

**Comment by tfiduccia** [comment]
Version - 4/26
Verified fixed
