### ISSUE TITLE
Network policies: Non-linked container can communicate on same host

### ISSUE THREAD

**Issue by courcelm** [rancher/rancher#8240]
**Rancher Versions:**
Server: 1.5.0
healthcheck: 0.2.3
ipsec:
network-services: 0.4.8
scheduler: 0.7.4
kubernetes (if applicable):
network-policy-manager:v0.2.4

**Docker Version:**

17.03.0-ce

**OS and where are the hosts located? (cloud, bare metal, etc):**

 Ubuntu 16.04.1 LTS (4.4.0), bare metal

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

Cattle

**Steps to Reproduce:**
In network policies, allow linked services, deny for the rest
Create two stacks on the same host.
Ping container from the other stack

**Results:** 

Container get ping response. 

This issue is not present for all my hosts.

**Comment by sangeethah** [comment]
@courcelm , I tried to follow your steps and am not able to reproduce the issue. In my case , pinging between containers belonging to different stacks times out (even when they are on the same host). Only pinging between containers that belong to linked services succeed.

 Could you check that you have "deny" set for "Everything Else" option as well?
<img width="1171" alt="screen shot 2017-03-20 at 3 24 35 pm" src="https://cloud.githubusercontent.com/assets/4266958/24127339/045f5614-0d91-11e7-884a-ec42ece7b93c.png">

**Comment by courcelm** [comment]
I have the same network policies like this screenshot. It seems to be host specific, maybe there is something else. I have a 4 stacks running on this host. Some services are linked within stack , other have external links. I also have stack with load balancer only.

**Comment by courcelm** [comment]
I evacuated the host, rebooted and re-created stacks. The issue is gone.
