### ISSUE TITLE
"Phantom" ports after removal from load balancer

### ISSUE THREAD

**Issue by nsimmonds** [rancher/rancher#8241]
I had a UDP port open in a previous version of my load balancer, but it has been removed from the rancher-compose definition for that service. However, even after completely deleting and recreating the stack, that port shows up in the UI for the new load balancer. Further however, though, when going to edit the LB that port is not shown, and clicking the "edit" button at the bottom removes it from the stack view.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.5.1` Cattle: `v0.177.8` UI: `v1.5.7` |
|Access|`Disabled`|
|Orchestration|`Cattle`|
|Route|`stack.index`|

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
