### ISSUE TITLE
vxlan: make it upgradeable, similar to ipsec.

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#8242]

**Comment by meggarr** [comment]
Hi, yesterday I upgrade my vxlan stack in rancher+k8s, now the inter-host communication inside container cannot just work, in network 10.42.0.1/16. Ping to 10.42.0.1 or containers in the same host is ok, but not working across hosts..

I suppose this implied by this issue, how can I recover it even it's not upgradable ? Thanks!

**Comment by sangeethah** [comment]
Tested the following upgrade path:

Vxlan set up with 1.6.5 . Have few containers running and make sure cross host networking works.

Upgrade to 1.6.6-rc3.
Upgrade Network services.
cross host networking continues to works.
Upgrade vxlan.
vxlan service is stuck in "upgrading" state forever.

<img width="1739" alt="screen shot 2017-07-25 at 4 16 59 pm" src="https://user-images.githubusercontent.com/4266958/28597779-bc2cc7f0-7154-11e7-9b33-bcf13c9a56b8.png">

**Comment by leodotcloud** [comment]
@sangeethah the template has been updated to version 0.2.0. This version is applicable for fresh installs only.

**Comment by sangeethah** [comment]
V0.2.0 is available only with fresh install of rancher-server v1.6.6-rc5.

When there are rancher-servers with older version of vxlan - 0.1.1 that get upgraded to v1.6.6-rc5 , they are not presented with option to upgrade to v0.2.0 as expected.
