### ISSUE TITLE
[rancher-compose] Create a rancher-compose latest URL for Downloads

### ISSUE THREAD

**Issue by jrhjr07** [rancher/rancher#8245]
**Rancher Versions:**
Server: ALL
healthcheck: ALL
ipsec: ALL 
network-services: ALL
scheduler: ALL
kubernetes (if applicable): ALL

**Docker Version:**
ALL

**OS and where are the hosts located? (cloud, bare metal, etc):**
ALL
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
ALL
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
ALL
**Steps to Reproduce:**
When downloading the rancher-compose files it would nice to have a https://releases.rancher.com/compose/latest URL to hit rather than https://releases.rancher.com/compose/v0.12.2/rancher-compose-linux-amd64-v0.12.2.tar.gz

This would assist with automated builds.

**Comment by deniseschannon** [comment]
The `latest` URL does exist for each artifact type.

So `https://releases.rancher.com/compose/v0.12.2/rancher-compose-linux-amd64-v0.12.2.tar.gz`
would be `https://releases.rancher.com/compose/latest/rancher-compose-linux-amd64.tar.gz`

**Comment by jrhjr07** [comment]
@deniseschannon is this documented anywhere, I couldn't find it.
