### ISSUE TITLE
copy virtualbox host to add rancher host, the new host will cover the old host

### ISSUE THREAD

**Issue by askie** [rancher/rancher#8249]
a  virtualbox host ip:  10.0.2.5
then user virtualbox copy this host to new ,ip reset to :10.0.2.6

in rancher when add new host 10.0.2.6,
the old host 10.0.2.5 will be coved by 10.0.2.6

only left the new host 10.0.2.6
the 10.0.2.5 was gone

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.5.1` Cattle: `v0.177.8` UI: `v1.5.7` |
|Access|`Disabled`|
|Orchestration|`Cattle`|
|Route|`hosts.index`|

**Comment by superseb** [comment]
Can you check if (http://rancher.com/docs/rancher/v1.6/en/faqs/agents/#using-a-cloned-vm) solves your problem?

Run ```rm -rf /var/lib/rancher/state; docker rm -fv rancher-agent; docker rm -fv rancher-agent-state``` before registering.

**Comment by jfsc** [comment]
@superseb
Yes, it works for me.
