### ISSUE TITLE
Docker 1.12 installation fails on Ubuntu 16.10 minimal

### ISSUE THREAD

**Issue by stieler-it** [rancher/rancher#8250]
**Docker Version:** 1.12

**OS and where are the hosts located? (cloud, bare metal, etc):** Ubuntu 16.10 Bare Metal

**Steps to Reproduce:**

* Fresh install of Ubuntu 16.10 Minimal
* `apt-get update && apt-get upgrade`
* `uname -a => Linux Ubuntu-1610-yakkety-64-minimal 4.8.0-34-generic #36-Ubuntu SMP Wed Dec 21 17:24:18 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`
* `curl https://releases.rancher.com/install-docker/1.12.sh | sh`

**Results:** 

`E: Version '' for 'docker-engine' was not found`

The problem seems to be a missing package:

```
root@Ubuntu-1610-yakkety-64-minimal ~ # apt-cache madison docker-engine
docker-engine | 17.03.0~ce-0~ubuntu-yakkety | https://apt.dockerproject.org/repo ubuntu-yakkety/main amd64 Packages
docker-engine | 1.13.1-0~ubuntu-yakkety | https://apt.dockerproject.org/repo ubuntu-yakkety/main amd64 Packages
docker-engine | 1.13.0-0~ubuntu-yakkety | https://apt.dockerproject.org/repo ubuntu-yakkety/main amd64 Packages
```

**Comment by vincent99** [comment]
The install-rancherscripts aren't magic, they're just tweaked to install a specific package instead of the newest one.  Docker only packages 1.13+ for 16.10.

**Comment by stieler-it** [comment]
Makes sense. I was just surprised that using a recommended OS with the provided install script fails. But I agree that this is not a bug that should be solved, maybe just a missing hint in the documentation.
