### ISSUE TITLE
After adding a new host, global service does not pick the new host for deployment

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#8259]
**Rancher Versions:**
Server:v1.5.2-rc3
network-services:v0.5.3

**Docker Version:**1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):**Ubuntu, Cloud

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**Single node

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**Cattle

**Steps to Reproduce:**
1. Create a cattle setup in 1.5.1 and upgrade to 1.5.2-rc3 or create a 1.5.2-rc3 setup
2. Add a a new host

**Results:** 
After adding the new host, the metadata container does not startup on this host. In-turn, IP-sec and health check containers fail to start for this host. After adding the new host, global service does not pick the new host for container deployment

**Comment by alena1108** [comment]
@soumyalj please reopen if you see it again; @StrongMonkey applied some fix to scheduler, lets see if you hit it.

**Comment by soumyalj** [comment]
Tested with upgrade from 1.5.8 to 1.6.0-rc6. Added new host. IPsec, Healthcheck containers and all global services started successfully on this host.
