### ISSUE TITLE
Feature Request - Web Hooks (publishing of events)

### ISSUE THREAD

**Issue by dbones** [rancher/rancher#8262]
I am interested in events of Rancher, and have web hooks into them. as it will let me react to them as they occur (in an event driven manor)

for example when a service is up/down, when a container is up/down etc.

**not to be confused with (#619)** which seems to be a client of a webhook. 

maybe this may help, this is how Github explains a webhook for a repo:

> Webhooks allow external services to be notified when certain events happen within your repository. When the specified events happen, we’ll send a POST request to each of the URLs you provide. Learn more in our Webhooks Guide.

**Comment by ekristen** [comment]
I'd definitely love to see a way to register webhooks with rancher, similar to registering webhooks with GitHub. They could be global, environmental, and per project scoped. I want to react to things happening inside of Rancher, this is a sensible way to do it.

**Comment by lee5i3** [comment]
Yeah I definitely want this as well, currently trying to find a way to notify when a service has been created or upgraded

**Comment by eldadfux** [comment]
This is a must have feature in 2018. We are also looking for a way to notify team members when a service has been upgraded. Event webhook will be the perfect solution for us.

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
