### ISSUE TITLE
Container Info - Auto Restart always shows "no"

### ISSUE THREAD

**Issue by dzirkler** [rancher/rancher#8264]
**Rancher Versions:**
Server: 1.4.1
healthcheck: 0.2.3
ipsec: 0.8.7
network-services: 0.7.3
scheduler: 0.6.3
kubernetes (if applicable): n/a

**Docker Version:**
1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04LTS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA Rancher, External DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
1. View a running container who's service's Restart = Always. 
2. Navigate to the container info, Command Tab.
3. See that it says "Auto Restart: no"

**Results:** 
![image](https://cloud.githubusercontent.com/assets/10255175/24181948/84f9e560-0e7b-11e7-996c-af5b2e070907.png)

This always says "no" regardless of the Restart setting for the service.

**Comment by alena1108** [comment]
@dzirkler for service's containers, auto restart is managed by Rancher server. The behavior is to always restart service containers, no matter what restart policy is set via API. In order to prevent docker from interfering, the restartPolicy field is removed from the container on its start, so it will never show up on docker inspect.

**Comment by dzirkler** [comment]
@alena1108: Please re-read the issue. This issue is 100% regarding changing a setting in Rancher UI, and it not reporting properly within the Rancher UI. 

If we set "Always" in the Rancher UI, it should show that when we view the status on the container (also in the Rancher UI). The container page always shows "Auto Restart: no" regardless of the setting in Rancher.

**Comment by alena1108** [comment]
@dzirkler I see the issue, thank you. On container tab, UI reads the restartPolicy from the container, not from the service. And even though restartAlways is set on the service, it is not being set on the container's fields; and if not set Docker defaults it to "no" - this is backpopulated to Rancher, and thats what the UI displays. We are going to follow up with the UI team to see how it can be handled/represented better.

**Comment by vincent99** [comment]
The container is actually `restartPolicy: null` in the API, so it's just the UI showing `no` based on that since that's my default.  If it's going to stay null and that that actually means `always` then I change that.

**Comment by wjimenez5271** [comment]
Thanks @vincent99 I'm not sure it means `always` in every case, it might only be in the case where the parent service has such a policy of `always`. @alena1108 can you confirm?

**Comment by alena1108** [comment]
@wjimenez5271 when restart policy is set to Null on service container, it would mean "always". 

For standalone container restartpolicy=null always means "no".

**Comment by wjimenez5271** [comment]
Thanks @alena1108. OK @vincent99 would it be possible to show that in the UI? So make it `always` when said container is within a service? Or would it just be easier to reflect `Null` as `undefined` or the like in the UI? To me both are an improvement to the end-user exp.

**Comment by westlywright** [comment]
This is fixed for 2.0 when its released

**Comment by tfiduccia** [comment]
Version - Wagyu (master 7/25)

On Failure up to [5] times option is not showing up in the details page.  All other options are showing up properly.

**Comment by tfiduccia** [comment]
Version - master 2.0 7/31
Verified fixed
