### ISSUE TITLE
Catalog template fails to deploy due to unescaped templating character

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#8271]
**Rancher Versions:**
Server: master (3/22/17)

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**

Deploy Route53 template from official infra catalog. 
Note the DNS name template value:
```
%{{service_name}}.%{{stack_name}}.%{{environment_name}}
```
And in answers.txt the curly braces are escaped but not the `%` percentage sign which is used to designate functions/variables in go txt template.

```
NAME_TEMPLATE=%\{\{service_name\}\}.%\{\{stack_name\}\}.%\{\{environment_name\}\}
```

**Results:** 
The stack fails to be created with error:
>  Error (template: template:43: function "service_name" not defined)

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
