### ISSUE TITLE
Selector based port rules dont include standalone containers. 

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#8275]
Rancher server version - Build from wagyu

Steps to reproduce the problem:
Create a standalone container with labels "test1=value1"
Create a LB service with following  selector based port rules:

```
"portRules": [
{
"type": "portRule",
"priority": 1,
"protocol": "http",
"selector": "test1=value1",
"sourcePort": 8000,
"targetPort": 80,
},
],
```
ha proxy configuration does not include standalone containers as targets for the backend relating to this portRule.

**Comment by alena1108** [comment]
Would require an ability to specify port rules on the target container side; that would be like a special feature. Moving to unscheduled for now.
