### ISSUE TITLE
Rancher managed network not work with error `Couldn't bring up network: netplugin failed but error parsing its diagnostic message "": unexpected end of JSON input`

### ISSUE THREAD

**Issue by snipking** [rancher/rancher#8276]
**Rancher Versions:**
Server: 1.5.0/1.5.2/1.5.5
healthcheck: 0.2.3
ipsec: 0.0.5
vxlan: 0.0.5
network-services: 0.1.1
scheduler: 0.5.1
kubernetes (if applicable):

**Docker Version:**
1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):**
CoreOS 1298.5.0 / 1298.6.0 on Azure cloud vm

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher & internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
1. run rancher agent on a new host without `-e CATTLE_AGENT_IP='real_internal_ip like 172.0.0.27'`
2. the host shows ip address 172.17.0.1, and ipsec or vxlan seems working, healthcheck and scheduler always initializing.
3. run a container on this host with managed network and port forward, the port forward
 not work.

**Steps to Reproduce:**
1. run rancher agent on a new host with `-e CATTLE_AGENT_IP='real_internal_ip like 172.0.0.27'`
2. the host shows ip address 172.0.0.27, and ipsec or vxlan route container cannot startup, with error `Couldn't bring up network: netplugin failed but error parsing its diagnostic message "": unexpected end of JSON input`

**Comment by snipking** [comment]
After different sequence try to create vxlan or ipsec, now it always failed with `Expected state running but got error: Timeout getting IP address` when run rancher/net.

**Comment by ckreutz** [comment]
Same problem running also on CoreOS. Rancher 1.5.2. It worked in the first environment, but does not work in the second environment with other hosts. I get the same error message for **health check container**  0.2.3 and for stacks I want to load through docker compose.

**Comment by aemneina** [comment]
can you share logs from the containers within network services. I'd imagine the error is in there.

**Comment by snipking** [comment]
@aemneina There's no log in the failed network container.

After some try I got this work again by delete all infrastructure containers and re-run them. And vxlan or ipsec service must run after network-service working well. But there's no dependence between this two service.

And the origin error happens because I reboot some of my host.

**Comment by ckreutz** [comment]
Here are the logs from two network container

25.3.2017 10:20:24time="2017-03-25T09:20:24Z" level=info msg="Setting up binaries for: map[rancher-bridge:4b1fd6da27dab245dee29eb03c84b93fc062cd4dd8bc2d138a0f917b441df05a]"
25.3.2017 10:20:24time="2017-03-25T09:20:24Z" level=error msg="Failed to apply cni conf: Error: No such container: 4b1fd6da27dab245dee29eb03c84b93fc062cd4dd8bc2d138a0f917b441df05a"

80f361761e8caf500caa2baac7a3c27f5dd0e871c7a25116 networkMode=ipsec
25.3.2017 10:21:02nsenter: cannot open /proc/8193/ns/ipc: No such file or directory
25.3.2017 10:21:02time="2017-03-25T09:21:02Z" level=error msg="Failed to evaluate networking: netplugin failed but error parsing its diagnostic message \"\": unexpected end of JSON input"
25.3.2017 10:21:03time="2017-03-25T09:21:03Z" level=info msg="Evaluating state from retry" cid=3663663d150ee930eb47bccfac26c66dee5fca28a9c2c91723e4ccb6653caa59 count=10
25.3.2017 10:21:03time="2017-03-25T09:21:03Z" level=info msg="CNI up" cid=3663663d150ee930eb47bccfac26c66dee5fca28a9c2c91723e4ccb6653caa59 networkMode=ipsec

**Comment by snipking** [comment]
This issue related to #8368. I've found more precise reason.

**Comment by ibuildthecloud** [comment]
If you are running the rancher server and agent on the same machine you always need to set `CATTLE_AGENT_IP` otherwise it will detect the bridge IP which is typically `172.17.0.1`.  I'm closing as this is a known issue.

**Comment by tuwid** [comment]
I'm having the same issue with 1.6.10 with a setup of 2 different hosts

**Comment by calexandre** [comment]
I too am having this issue with 1.6.10...i cannot upgrade ipsec  services :/

**Comment by VinceBT** [comment]
I had the same problem and it came from the fact that a machine was used both as a server and as an agent, so in the Hosts tab, it was detected with a wrong IP because it resolved it locally au lieu of resolving the IP in an external way (eg: 172.17.0.1). Which made the machine unaccessible from anywhere.

I stopped the agent where the IP was 172.17.0.1 and ```docker run``` the agent with :
```sh
-e CATTLE_AGENT_IP="$(ifconfig eth0 | grep 'inet ' | cut -d ' ' -f10 | awk '{ print $1}')"
```
You may have to modify the line a bit if your configuration is different.

Everything works fine now and the right IP shows on the Hosts tab.
