### ISSUE TITLE
io.rancher.lb_service.target not working

### ISSUE THREAD

**Issue by imranazad** [rancher/rancher#8278]
I have io.rancher.lb_service.target set to only-local. I have two services

load balancer (rancher load balancer x1 container)

Nginx container x1

I have two hosts, host A and host B both with the same affinity label. If I shutdown host B, the nginx container isn't accessible via the http load balancer from host A for at least a minute or two. I don't understand why host A is being affected.

**Comment by galal-hussein** [comment]
Can you elaborate more on the services on the hosts, where does both of the services resides originally on host A or host B?

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
