### ISSUE TITLE
When scheduler crashed and got to "stopped" state , there was no attempt made to start the scheduler container.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#8280]
Rancher Versions: Built from wagyu

Setup - Rancher server with 3 hosts
rancher/scheduler:v0.7.5

scheduler container was running successfully.
After a while , scheduler container crashed and went to "stopped" state.This issue is tarcked in https://github.com/rancher/rancher/issues/8279 .

In this case , we would expect service reconcile to kick in and attempt to start the container. This did not happen.

Scheduler continued to remain in stopped state . Had to start the container manually.

**Comment by tfiduccia** [comment]
Version - 2.0 master 8/5
Scheduler no longer separate container/stack.  No applicable in 2.0
