### ISSUE TITLE
Feature: Add deactivate as action to healtcheck failure

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#8281]
## Use Case

We have services that interact with hardware, unfortunately the hardware can sometimes become unavailable or not work properly resulting in many many different types of internal errors. Rancher is very good at ensuring the containers continue to run, which isn't always desired. 

## Desired 

If a service's health check becomes unheathly, allow for an option to deactivate (stop) the service vs re-create or do-nothing.

**Comment by ekristen** [comment]
Any thoughts on this?

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
