### ISSUE TITLE
Self-signed cert support for external-dns (route53)

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#8284]
**Rancher Versions:**
Server: 1.5.1

**Docker Version:**
1.12.6

**Steps to Reproduce:**
*prereq: rancher server HA setup with self-signed cert
deploy the catalog item for route53 (rancher/external-dns:v0.6.2 image)

**Results:** 
external dns provider fails to mount provided certs on host, and wont connect to rancher server url.

**Comment by deniseschannon** [comment]
Needs to be tested for Rancher v1.5 and Rancher v1.6. 

Templates are in `v1.5.x-externaldns` branch of catalog.

**Comment by galal-hussein** [comment]
Testing on v1.5.8-rc1 has no issues, i was able to run rotue53 external dns catalog on a Rancher server with self signed certificate.

Testing on v1.6.0-rc1 showed an error with dns registration:

```
5/2/2017 10:15:21 PMtime="2017-05-02T19:15:21Z" level=info msg="Adding dns record: {{{`wordpress.wordpress.default`}}.rancher-test.com. [130.211.171.206] A 60}"
5/2/2017 10:16:21 PMtime="2017-05-02T19:16:21Z" level=info msg="Adding dns record: {{{`wordpress.wordpress.default`}}.rancher-test.com. [130.211.171.206] A 60}"
```

**Comment by deniseschannon** [comment]
Template has been updated are in `v1.5.x-externaldns` branch of catalog.

**Comment by galal-hussein** [comment]
Tested and verified the external dns template with Rancher v1.6
