### ISSUE TITLE
Healthcheck block in Initializing

### ISSUE THREAD

**Issue by XciD** [rancher/rancher#8289]
**Rancher Versions:**
Server: v1.5.2
healthcheck: 0.2.3
ipsec: last
network-services: 0.5.3 / 0.8.11
scheduler: 0.7.5
kubernetes (if applicable):

**Docker Version:**
All hosts with 1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):**
own machine, debian 8

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node Rancher, Internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
We have two types of machines, few in our datacenters, and other in other providers.
Add a machine from our datacenter, without public address, just internal adress. 
But the machine can reach the rancher master (which is in the datacenter with a public address and internal address)
**Results:** 
Healthcheck block in  Initializing, no pertinent log about that in other services

**Comment by XciD** [comment]
Just return on 1.12.6 version of docker and still the error... even with a fresh agent install

**Comment by vincent99** [comment]
All hosts in an environment need to be able to reach all others via their registered public IP (shown on the host in the UI).  Health checks for a container are scheduled to 3

**Comment by XciD** [comment]
Thanks for the understanding
