### ISSUE TITLE
[gdapi-python] 

### ISSUE THREAD

**Issue by disaster37** [rancher/rancher#8290]
**Rancher Versions:**
Server: 1.5.2

**Docker Version:**
1.12.6

Hi,

I have upgraded my Rancher from 1.3.4 to 1.5.2 but now the API seems little different ?
It contunus to use v1 API but  the following code now is breaked ?

```python
# The url is sufixed with /v1
client = cattle.Client(url, key, secret)
listEnvironments = client.list('environment')
```

It's return the following error 
```
environment is not a valid type
...
File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 381, in list
24/03/2017 13:22:08    raise ClientApiError(type + ' is not a valid type')
24/03/2017 13:22:08ClientApiError: environment is not a valid type
```

**Comment by niusmallnan** [comment]
Be careful, a non-admin user can not allow list all user's environments from 1.4.x.

**Comment by disaster37** [comment]
Hum, maybee,

But on v1 api, the `environment` mean `stack` and `project` mean `environment`, so i don't understand why user that have all right in current environment can't list stack (aka environment) ?

**Comment by niusmallnan** [comment]
@disaster37
You mean this?
![image](https://cloud.githubusercontent.com/assets/998984/24363517/aeafdc90-1342-11e7-8113-9263960b8b76.png)

or
![image](https://cloud.githubusercontent.com/assets/998984/24363717/36f02696-1343-11e7-8933-701a1b5f45d6.png)

Both work fine.

**Comment by disaster37** [comment]
On the first, I get `environment is not a valid type` on Rancher 1.5.2

**Comment by disaster37** [comment]
and in my case I use cattle and not gdapi, but it seems the same ?

```python
import cattle
client = cattle.Client(url, key, secret)
envs = client.list('environment')

```

**Comment by disaster37** [comment]
I finnaly found the cause of problem.
In rancher-backup, we set the following label to grab access on Rancher API:
```
io.rancher.container.create_agent: true
io.rancher.container.agent.role: environment
```

But now, the right can't permit to list the stack on current environment.
From my point of view, it's king of bug because of role `environment` mean access on current `project`.

**Comment by disaster37** [comment]
Instead `v1` api, use `v2-beta`.
Thx @vincent99
