### ISSUE TITLE
Can't filter LDAP users while searching in directory

### ISSUE THREAD

**Issue by aleksejlopasov** [rancher/rancher#8292]
**Rancher Versions:**
Server: 1.4.2
healthcheck: 0.2.3
ipsec: 0.0.4
network-services: 0.0.17
scheduler: 0.4.0
kubernetes (if applicable):
mesos: 0.28.1

**Docker Version:**
17.03.0-ce
**OS and where are the hosts located? (cloud, bare metal, etc):**
CentOS 7.3, Proxmox VE
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher, internal DB, no HA
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Mesos

**Steps to Reproduce:**
Hi,
Please help me to understand how can I determine the filters while configuring OpenLDAP Authentification in Rancher
I don't want all users in my directory to access Rancher. I want to add user to group "rancher" and then filter them in Rancher in such a way e.g. "(&(objectClass=inetorgperson)(memberOf=cn=rancher,cn=groups,cn=accounts,dc=domain,dc=com))"
**Results:** 
Unfortunatelly I don't see any filters in OpenLDAP configuration panel. Rancher finds users using base dn "cn=accounts,dc=domain,dc=com" and search field "uid" but there is no filtering and anyone can access rancher
Do you support filtering while searching for users in LDAP directory?

**Comment by tfiduccia** [comment]
On login you cannot set filtering.  But once you login you can restrict access to a specific group.  In the Site Access section, select the Restrict Access radio option and enter your group or select it from the drop-down.  The admin person must be part of the group to see it in the drop-down.

![image](https://cloud.githubusercontent.com/assets/11514927/24373982/1eb6935e-12e8-11e7-82cc-6c7f8d53d4ad.png)

**Comment by aleksejlopasov** [comment]
@tfiduccia 
According to rancher docs it works only for ACTIVE DIRECTORY/GITHUB/SHIBBOLETH. I'm using OpenLDAP. I don't see any Site Access section after Access Control is configured using OpenLDAP protocol.

"...
AZURE AD/OPENLDAP
For Azure AD and OpenLDAP, any user that is a member of your setup will be able to access the Rancher site.
..." Docs (c)

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
