### ISSUE TITLE
Add support for security_opt: - "credentialspec=file://gmsaDocker.json"

### ISSUE THREAD

**Issue by originalnoe-nazvanie** [rancher/rancher#8293]
**Rancher Versions:**
Server: 1.5.1

**Docker Version:**
17.03.0-ce

**OS and where are the hosts located? (cloud, bare metal, etc):**
windows server 2016 datacenter on hyper-v vm with nested virtualization enabled

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
2 rancher manager nodes, currently only 1 is in use, haproxy, 3 mariadb-s with galera

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
windows

**Steps to Reproduce:**
1) create gmsa Active Directory account for the container
https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/manage-serviceaccounts
2) export credentials to json file
3) run windows container from rancher UI(or from rancher-cli) with docker-compose.yml

**Results:**
No success. If it will be done from the windows node(where rancher agent is installed) using docker CLI it'll be successful. Reason - that yml file with configuration of the rancher service has a string **credentialspec=file://gmsaDocker.json**, but this file will not be transmitted to server, even if is located in the same folder as the rancher-cli executable

version: '2'
services:
  test-express-23-dc:
    image: "microsoft/windowsservercore"
    network_mode: "transparent"
    security_opt:
      **- "credentialspec=file://gmsaDocker.json"**

does not work because file is not transmitted to docker service

That parameter works with docker cli only if there is a file gmsaDocker.json that is located in c:\ProgramData\Docker\Credentialspec 

**Suggested Improvements:**
some way to provide this file from rancher-cli to rancher-server and to rancher-agent 
 may be manually put that file to some location on the target machine, for example c:\programmdata\docker

**Comment by novig** [comment]
Fix:

file: https://github.com/rancher/agent/blob/master/core/compute/compute_windows.go

Paste this code at the end of the function setupFieldsHostConfig
hostConfig.SecurityOpt = fields.SecurityOpt

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
