### ISSUE TITLE
EBS volume scheduling 

### ISSUE THREAD

**Issue by StrongMonkey** [rancher/rancher#8295]
In order to better schedule EBS volume, we need to add the following functionality:
1. Agent needs to be aware of the cloud provider and populate the correct Availability zone label to the host. (go-agent)
2. Ebs volume needs to populate the cloud provider info and availability zone to cattle and persist it. (rancher/storage)
3. Scheduler needs to schedule the ebs volume to only the hosts with the same availability zone label.(cattle or outside micro-scheduler)

@LLParse @cjellick

**Comment by StrongMonkey** [comment]
https://github.com/rancher/rancher/issues/8283

**Comment by LLParse** [comment]
This is a good tentative plan - while we're implementing #1, we should also populate a region label. This will be useful for EFS volume scheduling.

**Comment by StrongMonkey** [comment]
The bug is, when we create a EBS volume, it is specifically bind to an availability zone and can not be used by other instance outside the zone. So what could happen in here is: 
1. User created a volume named `foo`, and bind-mount it to instance 1. Instance 1 gets allocated to host A, and the volume is created with availability zone west.
2. User deleted instance 1, volume `foo` gets detached and then user created instance 2 using `foo`. Schedule it to host B with availability zone east.
Result: Host B is considered as valid because `foo` is not used by any instances so cattle would just put a soft constraints to host A. So When you deactivate host A, host-B will be chosen as a candidate, which is wrong.
Expected: Volume with specific availability zone should never go to other hosts in different zones. We should put a hard constraint for these hosts.
@cjellick

**Comment by StrongMonkey** [comment]
So here is the implementation detail after :
1. In go-agent, open a go-routine to hit ec2-metadata every minute. If success, set the region and availability zone labels to the host.
2. In storage, back-populate ebs volume labels with availability zone. Persist the availability zone to database.
3. Using existing https://github.com/rancher/scheduler/pull/43 scheduler feature to only schedule the instance to certain hosts where it should be. It should populate the a distribution label to instances according to the label on the volume.

**Comment by LLParse** [comment]
Does go-agent really need to hit EC2 metadata _every minute_? I guess the real question would be, will instances ever change region/availability zone? I would think one-time calls during registration would be sufficient, unless I am over-simplifying.

Here's another implementation detail:
2.5. Make cattle send volume information along with instance context to external scheduler.

**Comment by StrongMonkey** [comment]
@LLParse I agree with your analysis and i also don't think the instance could change its own region or availability zone. Since this is the solution we just came out, we can discuss it later to see if there is really a need to update that dynamically.
<Make cattle send volume information along with instance context to external scheduler.>
We will probably use the new scheduler feature and will delegate the scheduler decision to this one.

**Comment by cjellick** [comment]
The idea was every minute until we get a response. Once we get the data we need, that goroutine can die

**Comment by cjellick** [comment]
Actually, every minute seems way too infrequently. Seems like we could hit it ever 10 or 15 seconds

**Comment by StrongMonkey** [comment]
This will address the issue that once a EBS volume is created, the container which uses the volume can only be scheduled to the hosts which have the same availability zone with EBS volume. This is because EBS volume can only be attached to the instances which are in the same AZ. @sangeethah @soumyalj

**Comment by StrongMonkey** [comment]
the fix is in `rancher/storage-ebs:v0.8.0`. @soumyalj

**Comment by soumyalj** [comment]
Tested with 1.6.0-rc3. Containers using EBS volume and the volume can be scheduled to hosts in the same availability zone. EBS volumes cannot move across zones. 
Created 2 hosts(host1 and host2) in zone west2a and one host in zone east. Created EBS volume and service using the volume on host1 in zone west 2a. Data was written to the volume. Deleted host1. The volume and containers using it moved to host2 in west2a and not the host in zone east.
