### ISSUE TITLE
Security Exposure: Any authenticated users can disable auth via API

### ISSUE THREAD

**Issue by will-chan** [rancher/rancher#8296]
**Rancher Versions:**
Server: 1.2.0+

**Docker Version:**
Any

**OS and where are the hosts located? (cloud, bare metal, etc):**

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**
Log into Rancher as an authenticated user (any role) and disable auth via the API.

**Results:** 
Authentication is disabled.

**Comment by deniseschannon** [comment]
Verified in v1.2.4, v1.3.5, v1.4.3 and v1.5.3.
