### ISSUE TITLE
Healthcheck enabled standalone containers do no get recreated when the host on which they are running is powered down.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#8298]
Rancher Versions: Build from wagyu

Steps to reproduce the problem:

Have standalone containers that are healthcheck enabled.
Power down the host where these containers are running.
containers get to "stopped" state and continue to remain in "stopped" state even after the host goes from "active"->"reconnecting"->"disconnected" state

**Comment by alena1108** [comment]
@sangeethah if instance went into stopped state, it means that the agent reported it as stopped before health check took over. Health checker only considers instances in Running/Starting states. So this use case falls into different category - restart if the instance was stopped on the backend. If you want stopped instances to be autorestarted, you'd have to set the restart policy. 

Can you retest considering the above.

**Comment by sangeethah** [comment]
Tested with build from master(07/07)

Have standalone containers that are healthcheck enabled.
Power down the host where these containers are running.
Containers are not able to start successfully on other hosts.

```
I see the container marked as "unhealthy" but then it gets removed when it is still in "reinitializing" state.

mysql>  select id,name,state, health_state,removed,created,start_count from instance where name like "%testhealth%";
+----+------------+---------+----------------+---------------------+---------------------+-------------+
| id | name       | state   | health_state   | removed             | created             | start_count |
+----+------------+---------+----------------+---------------------+---------------------+-------------+
| 80 | testhealth | removed | reinitializing | 2017-07-07 23:15:15 | 2017-07-07 23:11:10 |           2 |
+----+------------+---------+----------------+---------------------+---------------------+-------------+
1 row in set (0.00 sec)

mysql> 
```
