### ISSUE TITLE
Health check enabled service instances are not able to get recreated on different hosts when host is powered down.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#8299]
Rancher server build from wagyu

Setup with 3 hosts

Steps to reproduce the problem:
Have service that are healthcheck enabled.
Power down the host where the service containers are running.
containers get to "unhealthy" state as expected.
But they get deleted and recreated on the same host which does not succeed.
Attempt to recreate containers on the disconnected host continues to happen forever.

Expected Behavior:
Containers should get recreated successfully on other hosts.

**Comment by alena1108** [comment]
@sangeethah was it global service you've tested it for?

**Comment by rancherdev** [comment]
@alena1108 , service was not global service.

**Comment by deniseschannon** [comment]
Fixed in wagyu branch

**Comment by sangeethah** [comment]
Tested with rancher-server build from master (07/07)
Have services that are healthcheck enabled.
Power down the host where the service containers are running.
containers get to "unhealthy" state as expected and get deleted.
They get recreated on other hosts in the setup and get to "healthy" state.
