### ISSUE TITLE
Can see purged containers on environments page

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#830]
Steps:
1.  Create a service, scale 3
2.  When finished, Delete then purge a container in Service

Results:
The purged container is still showing up.  I have to refresh the page to get it to disappear.

Expected:
Purged container should not show anymore.

Comments:
It also has a menu and I can click on View logs which will give me a 404 page.

**Comment by tfiduccia** [comment]
This is probably the same as #758

**Comment by deniseschannon** [comment]
I think the view logs issue is similar to this issue: https://github.com/rancherio/rancher/issues/804 API should not allow logs for purged containers?

**Comment by vincent99** [comment]
@tfiduccia Can you recheck this, I assume it doesn't apply anymore..

**Comment by tfiduccia** [comment]
version - master jan 07
Not applicable anymore.
