### ISSUE TITLE
Lunch only one instance of an image per host

### ISSUE THREAD

**Issue by XciD** [rancher/rancher#8301]
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
Lunch a image, scale
**Results:** 
Something, cattle choose the same host to run the new service.
Can we set that we only want to have on instance of a service per host ? and keep the scale feature ?

**Comment by vincent99** [comment]
http://docs.rancher.com/rancher/v1.5/en/cattle/scheduling/
