### ISSUE TITLE
Rancher Compose Issue - not remote access to container

### ISSUE THREAD

**Issue by fabriziotorelli-wipro** [rancher/rancher#8302]
**Rancher Versions:**
Server: 0.9.0
healthcheck: latest
ipsec: latest
network-services: latest
scheduler: latest
kubernetes (if applicable): latest

**Docker Version:**
1.12.1

**OS and where are the hosts located? (cloud, bare metal, etc):**
AWS EC2

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

Single Rancher Server node, internal DB, EC2 client agent (Rancher AWS ami) + lastest Rancher server + No Access Control (test phase)

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle/Kubernetes/Mesos/Swarm/Customs: Any

**Steps to Reproduce:**
try to connect with rancher client to an executable container such as : 
rancher --url [api-v2-url] --env [env-id] --host [host-id] exec -i -t [container-api-id] /bin/bash
I seems the container expects docker in the container. Docker provided in the Rancher OS PATH, in all users included root.

The same command works in the web interface. Trying to improve my company experience with Rancher.
 
**Results:** 
rancher --url http://rancher-server-master.xxxx:8080/v2-beta --env 1a22 --host 1h3 exec -i -t 1s197 /bin/bash
Containers:
[1] xxxxxxxx-xxxxxx-jenkins-jenkinsvolumes-1 (10.42.180.171)
[2] xxxxxxxx-xxxxxx-jenkins-1 (10.42.92.106)
Select: 2
FATA[0013] exec: "docker": executable file not found in $PATH 

**Suggested Improvements:**
* No SSH Key option provided in the host ssh connection to the host via rancher ssh command, using the rancher client. In my case I have custom instances to join our architecture (rig), so an ssh keys option for the client, would be very appreciated. We have commanded hosts, manually joined at the moment (custom hosts);
* A Full Working AWS ami should be suitable (right now the most proficient are stored in Digital Ocean), the current ones (for any region I used, mostly all) fails during the ssh connection, I used the rancher suggested amis, defined in the Docs (exactly in the region/ami list of the official documentation, link suggested by rancher during the AWS host creation). I tried to create my own image, from the rancher image, with authorized_keys for the server users, a set of rancher, root and ubuntu users all authorizing the server keys, however it didn't working. Revealing some mechanisms could be an improvement for us, cloud specialists, and can allow our contribution to the rancher community.

**Comment by scomma** [comment]
I think I have the same issue here. From the web interface, I can click on the container circles and Execute Shell. However when I try to run `rancher exec` locally, which I assume is the command line equivalence to that function, I get a fatal error "executable file not found in $PATH."

Other `rancher` commands work fine e.g. I can `rancher ps`.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
