### ISSUE TITLE
Feature in Rancher cattle to deploy the new updated image on the containers, similar to Kubernetes deployment feature

### ISSUE THREAD

**Issue by borntorock** [rancher/rancher#8307]
We are deploying our images with the help of docker-compose and rancher-compose yml configuration files. As of now, we have been tagging our images with the `latest` tag and mentioned that in the docker-compose.yml file. 

But now, we want our images to be tagged with the release tag of our application code. Since a new version of application code is released with new tag quite often, it is not possible to change the image tag in the docker-compose.yml file again and again. 

Wanted to know, if we do have any feature similar to Kubernetes deployment so as to deploy the updated image on the containers. Say, in Kubernetes with `kubectl set image deployment/nginx-deployment nginx=nginx:1.9.1` we can deploy the nginx:1.9.1 on the containers with no downtime. 

Reference: kubectl set image deployment/nginx-deployment nginx=nginx:1.9.1

CC/ @alena1108 @prachidamle

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
