### ISSUE TITLE
CLI: Unable to scale with up/upgrade command

### ISSUE THREAD

**Issue by gerich-home** [rancher/rancher#8309]
**Rancher Versions:**
Server: 1.5.1
healthcheck: 0.2.3
ipsec: 0.0.5
network-services: 0.1.1
scheduler: 0.5.1

**Docker Version:** 1.12.6 on agents, 17.03.0-ce on the server 

**OS and where are the hosts located? (cloud, bare metal, etc):** Ubuntu 16.04.2 LTS (with KVM) (4.4.0), cloud, DigitalOcean

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single node rancher, internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:**
1. Prepare `docker-compose.yml` and `rancher-compose.yml` files so that there a service with scale=1 in it:
```
version: '2'
services:
  my-app
    scale: 1
```
2. Deploy the stack using CLI command of the following form:
```
rancher --url http://some-domain.com:8080 --access-key XXXX --secret-key YYY --env Default up -s my-stack -d --upgrade --confirm-upgrade
```
3. Change the scale parameter from 1 to 2 in `rancher-compose.yml`:
```
version: '2'
services:
  my-app
    scale: 2
```
4. Run the same command to redeploy the stack:
```
rancher --url http://some-domain.com:8080 --access-key XXXX --secret-key YYY --env Default up -s my-stack -d --upgrade --confirm-upgrade
```

**Actual Results:** 
The deployed application has scale = 1

**Expected Results:** 
The deployed application has scale = 2

**Comment by deniseschannon** [comment]
Rancher CLI expects users to use the `rancher scale` [command](http://docs.rancher.com/rancher/v1.5/en/cli/commands/#rancher-scale-reference). The ability to upgrade scale using `rancher up --upgrade` is not supported

**Comment by gerich-home** [comment]
Yes, I know the command you mention.
However it does not allow you to just take your rancher-compose file and feed it into it!
You need to take scale numbers from rancher-compose (**manually!**) and feed it into `rancher scale` instead of just passing the file into the command (`rancher scale` or `rancher up`).
For some reason scaling services is not first-class-citizen operation while changing the structure and connections of services is.

Please reopen the feature request, it is really just a missing piece.
At least please explain why it won't be implemented.

**Comment by jakubknejzlik** [comment]
I have to agree with @gerich-home, we are using the rancher-cli for service deployment and by missing this feature we are unable to control scale. Except the case where we manually parse the rancher-compose.yml and iterate&scale through all services.

**Comment by joshwget** [comment]
The attribute should really be called `initial_scale` since the attribute is mutable after first launch. If upgrade always reverted back to that scale it could have unintended results.

Imagine you set scale to 3 in your Compose file, then run `rancher scale service=5`, and then upgrade the stack. If it was handled entirely through the Compose file then it'd be reverted back to 3.

For users who are aware of this it might make sense to add a second attribute that controls scale even on upgrade.

**Comment by jakubknejzlik** [comment]
@joshwget I have to agree with you. More I think of it, more it seems to me that's it's the matter of point of view. It could be confusing that it reverts back to this value for users using 'rancher scale' but also confusing that it won't update for those who use it as "compose file is reflection of current state". The initial_scale vs scale could help IMO

**Comment by vincent99** [comment]
**im**mutable...  (https://www.youtube.com/watch?v=Q8mD2hsxrhQ)
