### ISSUE TITLE
CLI: Dry run/check mode for up/upgrade command

### ISSUE THREAD

**Issue by gerich-home** [rancher/rancher#8310]
**Rancher Versions:**
Server: 1.5.1
healthcheck: 0.2.3
ipsec: 0.0.5
network-services: 0.1.1
scheduler: 0.5.1

**Docker Version:** 1.12.6 on agents, 17.03.0-ce on the server 

**OS and where are the hosts located? (cloud, bare metal, etc):** Ubuntu 16.04.2 LTS (with KVM) (4.4.0), cloud, DigitalOcean

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single node rancher, internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Suggestion**:
When you automate your deplyments sometime you need to know whether something will change (or at least have changed) when you run upgrade command.
I describe my cloud of rancher machines in Ansible scripts and I want to be able to run Ansible in check mode to know if my current infrastructure is different from the desired infrastructure.
Part of infrastructure is described as a set of `docker-compose.yml` and `rancher-compose.yml` files and I deploy them using Rancher CLI as follows:
```
rancher --url http://some-domain.com:8080 --access-key XXXX --secret-key YYY --env Default up -s my-stack -d --upgrade --confirm-upgrade
```

It will be useful to:
1. Has an ability to check if something **will** change if I run `upgrade` command
2. Has an ability to check if something **has** changed if I have run `upgrade` command (to report a change if Ansible was run in non-check mode).

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
