### ISSUE TITLE
Discussion: Network policy; block any outgoing connection

### ISSUE THREAD

**Issue by SilentHunter124** [rancher/rancher#8312]
I would like to start a discussion about the following feature:

* Generally when policy manager is set to block, do not allow any outgoing traffic
* Watcher should check if external service with specific ip is defined inside stack
* Only allow outgoing traffic to defined external services, nothing else

What do you think about that?

**Comment by SilentHunter124** [comment]
I created a pull request where you can test this functionality: https://github.com/rancher/network-policy-manager/pull/7

**Comment by leodotcloud** [comment]
Commented on the PR.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
