### ISSUE TITLE
Failure when attaching a container to a port

### ISSUE THREAD

**Issue by aimartin** [rancher/rancher#8322]
**Rancher Versions:**
Server: 1.5.3
healthcheck: rancher/healthcheck:v0.2.3
ipsec: rancher/net:v0.9.4   rancher/net:holder	
network-services: rancher/metadata:v0.8.11  rancher/network-manager:v0.5.3
scheduler:  rancher/scheduler:v0.7.5
kubernetes (if applicable): No

**Docker Version:** Docker version 17.03.0-ce, build 60ccb22

**OS and where are the hosts located? (cloud, bare metal, etc):** Bare Metal

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** Single Node Rancher with External DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:** 
Issue a LB, sometimes works fine, sometimes don't. Once the port is marked as "in use", nothing can be attached to it, even though the port is not actually used.

**Results:** 
 (Failed to allocate instance [container:1i3085]: Bad instance [container:1i3085] in state [stopping]: Allocation failed: No healthy hosts meet the resource constraints: [ports: [8090:8090/tcp], ResourceType: instanceReservation, Amount: 1])

**Extra information:** No application is running in TCP port 8090
netstat -ltpn | grep 8090
root@mini:~# 

docker ps -a | grep 8090
root@mini:~# 

telnet localhost 8090
Trying ::1...
Trying 127.0.0.1...
telnet: Unable to connect to remote host: Connection refused

**Workaround**
Restarting the host "fix" the issue and allow to attach a container to the port again.

**Comment by aemneina** [comment]
not able to reproduce this with 1.5.9.... @aimartin are you still experiencing this?

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
