### ISSUE TITLE
Compose export: add support for hosts/containers/secrets

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#8328]
Rancher Versions: Build from wagyu

Steps to reproduce the problem:
Create a stack .
Create a  standalone container in this stack.
Exported config file for this service does not include container information.

**Comment by alena1108** [comment]
@sangeethah that would be done as a part of bigger change for export. So lets modify this ticket to keep track of all the expected changes.

1) Add export support for: 

- host
- container
- secret

2) Create top level keys for following service types:

* loadBalancerService
* dnsService
* etc

**Comment by deniseschannon** [comment]
Also, need to update so that export config is 1 `compose.yml` file instead of a `rancher-compose.yml` and `docker-compose.yml`.

**Comment by StrongMonkey** [comment]
secrets export supports are tracked in this issue. https://github.com/rancher/rancher/issues/9059

**Comment by deniseschannon** [comment]
With the release of [Tech Preview 2](https://forums.rancher.com/t/rancher-release-v2-0-0-tech-preview-2/8282/3), the architecture behind 2.0 has significantly changed. Any issues with any release prior to v2.0.0-alpha12 is most likely invalid. 

Please watch our [Tech Preview 2 meetup](https://www.youtube.com/watch?v=ld7ctOg3waM&t=4s) to learn more about the changes in 2.0 in Tech Preview 2. 

Please file new issues after using Tech Preview 2 (any release v2.0.0-alpha12+). As always, thanks for using Rancher!
