### ISSUE TITLE
LB service restarts

### ISSUE THREAD

**Issue by kaos** [rancher/rancher#8337]
I have a environment (Shipyard-DC1) with two agent nodes, and a LB service with global scale (thus, two instances).

We have a service we use that deploys stacks, and updates this LB with routing config using the API. This happens fairly frequent, thus there are a lot of HAproxy config updates. By inspecting the LB update in the audit logs, I see no difference in our calls to the API, compared to that made by the UI.

Our issue is that I see frequent restarts of the LB containers, where they go down completely. At times they take turns, so at least on is up while the other one is restarting, but at times, they are both gone, for tens of seconds before being back online again (don't have exact figures or frequencies right now, but can collect if necessary).

At first, I thought it was in relation to our LB updates, but looking at the times in the logs below, I see that there has not been any updates for a good ten minutes before the LB services were restarted.

This becomes most visible by continuously polling the DNS for the LB service (using `dig`), where I can see in the response when I have two, one or no instances, and see that they get new IP addresses rather frequently (which also is unexpected as I've set `retainIp` to `true` on the LB service, but that is besides the point).

Before I go dig much deeper I felt it would be nice to see if this is a known issue, perhaps something in our setup/use that is bad practice (I hope), or a bug.

We do have custom haproxy config enabled:
```
balance source

stats enable
stats uri /ops/haproxy?stats
```

Besides that, nothing special. (Listening on Public HTTP on port 80, Internal HTTPS on 443, and a few public TCP ports, ~30-ish port rules)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.4.1` Cattle: `v0.176.9` UI: `v1.4.6` |
|Access|`ldap` `admin`|
|Orchestration|`Cattle`|
|Route|`service.containers`|

LB Service Logs (at approx 09:28 AM):

```
09:23:45 AM	INFO	service.trigger.info	Service already reconciled	 
09:23:45 AM	INFO	service.trigger.info	Created: 2, Unhealthy: 0, Bad: 0, Incomplete: 0	 
09:23:45 AM	INFO	service.trigger	Re-evaluating state	 
09:23:40 AM	INFO	service.update.info	Service reconciled: Created: 2, Unhealthy: 0, Bad: 0, Incomplete: 0	 
09:23:36 AM	INFO	service.instance.create	Creating extra service instance	 
09:23:36 AM	INFO	service.update (4 sec)	Updating service	 
09:23:36 AM	INFO	service.update.wait (4 sec)	Waiting for instances to start	 
09:23:36 AM	INFO	service.update.info	Created: 1, Unhealthy: 0, Bad: 0, Incomplete: 0	 
09:23:35 AM	INFO	service.trigger	Re-evaluating state	 
09:23:35 AM	INFO	service.trigger.info	Created: 1, Unhealthy: 0, Bad: 0, Incomplete: 0	 
09:23:27 AM	INFO	service.update.exception	Need to restart service reconcile	 
09:23:21 AM	INFO	service.update.wait (6 sec)	Waiting for instances to start	 
09:23:21 AM	INFO	service.instance.delete	Removing unhealthy service instance	 
09:23:21 AM	INFO	service.update.info	Created: 0, Unhealthy: 1, Bad: 0, Incomplete: 0	 
09:23:21 AM	INFO	service.update (6 sec)	Updating service	 
09:23:21 AM	INFO	service.instance.create	Creating extra service instance	 
09:23:17 AM	INFO	service.trigger.info	Created: 0, Unhealthy: 1, Bad: 0, Incomplete: 0	 
09:23:17 AM	INFO	service.trigger	Re-evaluating state	 
09:23:17 AM	INFO	service.update.exception	Need to restart service reconcile	 
09:23:16 AM	INFO	service.instance.delete	Removing unhealthy service instance	 
09:23:16 AM	INFO	service.update.info	Created: 1, Unhealthy: 1, Bad: 0, Incomplete: 0	 
09:23:16 AM	INFO	service.update (1 sec)	Updating service	 
09:23:16 AM	INFO	service.trigger.info	Created: 1, Unhealthy: 1, Bad: 0, Incomplete: 0	 
09:23:16 AM	INFO	service.update.wait	Waiting for instances to start	 
09:23:15 AM	INFO	service.trigger (1 sec)	Re-evaluating state	 
09:20:53 AM	INFO	service.trigger.info	Created: 2, Unhealthy: 0, Bad: 0, Incomplete: 0
```

Audit Logs:

```
Time 	Event Type 	Description 	Environment 	Resource Type:ID 	Identity 	Auth & IP
18 minutes ago	api.loadBalancerService.update 	None	Shipyard-DC1	loadBalancerService: 1s377	API Key 172.17.0.1
43 minutes ago	api.loadBalancerService.update 	None	Shipyard-DC1	loadBalancerService: 1s377	USERID Andreas Stenius UI Session my.ip.addr.here
```

In the rancher server logs I see pretty much of lines like this:

```
2017-03-29 07:08:08,485 ERROR [:] [] [] [] [utorService-438] [.e.s.i.ProcessInstanceDispatcherImpl] Unknown exception running process [service.remove:11915627] on [2948] org.jooq.exception.DataChangedException: Database record has been changed
2017-03-29 07:08:26,733 ERROR [42586e79-8134-4828-bd73-38b9c9e2646b:11915441] [instance:487049->instanceHostMap:483212] [instance.start->(InstanceStart)->instancehostmap.activate] [] [utorService-422] [c.p.e.p.i.DefaultProcessInstanceImpl] Agent error for [compute.instance.activate.reply;agent=191]: Timeout getting IP address 
2017-03-29 07:18:32,992 ERROR [ed67507d-4b21-4e0d-8192-e38c1ebba9fa:11920070] [instance:487214] [instance.start] [] [utorService-431] [c.p.e.p.i.DefaultProcessInstanceImpl] Unknown exception org.jooq.exception.DataChangedException: Database record has been changed
2017-03-29 07:18:33,015 ERROR [:] [] [] [] [utorService-431] [.e.s.i.ProcessInstanceDispatcherImpl] Unknown exception running process [instance.start:11920070] on [487214] org.jooq.exception.DataChangedException: Database record has been changed
```

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
