### ISSUE TITLE
UI: Where is the audit log timestamp?

### ISSUE THREAD

**Issue by kaos** [rancher/rancher#8338]
When looking at the audit log, I may need to correlate the data with other logs, like firewall etc.. but without an exact timestamp, that is impossible...

![image](https://cloud.githubusercontent.com/assets/72965/24445032/dfd31b1c-1468-11e7-8e58-4d4240d85fef.png)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.4.1` Cattle: `v0.176.9` UI: `v1.4.6` |
|Access|`ldap` `admin`|
|Orchestration|`Cattle`|
|Route|`admin-tab.audit-logs`|

**Comment by vincent99** [comment]
#7382
