### ISSUE TITLE
Can i use Rancher of multi Project?

### ISSUE THREAD

**Issue by Ima8** [rancher/rancher#8339]
I wanna setup Rancher server at only one But I have projects that separate from each other.

Ex : 
Project A  have 3 Services and 1 API Key Infra  that can create one or more node.
Project B have 10 Services and 2 API Key Infra  #that can create one or more node.

and each Project can't use the same infra.

Thank you.

**Comment by deniseschannon** [comment]
Yes, you would use multiple environments for this purpose.

http://docs.rancher.com/rancher/v1.5/en/environments/

**Comment by Ima8** [comment]
Excuse me , How I manage environments via API or Nodejs lib ?
