### ISSUE TITLE
Host and container stats don't display ... connecting

### ISSUE THREAD

**Issue by chrisyoung12345** [rancher/rancher#8341]
**Rancher Versions:**
Server: v1.4.1
healthcheck: rancher/healthcheck:v0.2.3
ipsec: rancher/net:v0.8.7
network-services: rancher/network-manager:v0.4.5.1
scheduler: rancher/k8s:v1.5.2-rancher1-4
kubernetes: 1.5.2-rancher1-4

Docker Version: 1.12.6
OS and where are the hosts located? (cloud, bare metal, etc): 
- AWS EC2 Amazon Linux 2016.09.1 (for the Rancher servers) - deployed in an auto-scaling group (ASG) for HA purposes using a static 2 min, 2 desired, 2 max configuration
- AWS EC2 Ubuntu 16.04 instances (for the hosts)
Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)
- HA Rancher connecting to an AWS Aurora HA DB
Environment Type: Kubernetes

**Steps to Reproduce:**
1) Deploy Rancher in the configuration listed above2) 
2) Deploy 2 hosts using the EC2 machine driver via the Rancher interface
3) Go to the hosts and look at the CPU / Memory / Network stats graphs

**Results:** 
No information is displayed in the stats graphs. The same is true of any of the individual containers.

**Comment by tfiduccia** [comment]
@chrisyoung12345 - Graphs were fixed in 1.5.  Please upgrade and if you find the graphs are still not displaying properly, reopen issue.

**Comment by chrisyoung12345** [comment]
@tfiduccia Please reopen this issue. I upgraded to v1.5.3 and I am still facing the same issue.

**Comment by chrisyoung12345** [comment]
@tfiduccia Is there anything that I can be doing to provide additional information on this issue that would allow for its resolution? If so, please advise. I'd like to see this working.

**Comment by chrisyoung12345** [comment]
@tfiduccia This issue was resolved per the resolution of #8467. Thank you for your assistance.
