### ISSUE TITLE
LB Service not Starting

### ISSUE THREAD

**Issue by abyss1** [rancher/rancher#8343]
**Rancher Versions:**
Server:1.5.3
healthcheck:rancher/healthcheck:v0.2.3
ipsec:rancher/net:v0.9.4
network-services:rancher/network-manager:v0.5.3
scheduler:rancher/scheduler:v0.7.5
kubernetes (if applicable):

**Docker Version:**
Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:53:29 2017
 OS/Arch:      linux/amd64
 Experimental: false

**OS and where are the hosts located? (cloud, bare metal, etc):**
Debian Jessie todays patch level. 3 Servers

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA Rancher 2 Nodes on RancherOS on VMware 6.0

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Mesos , but error is reproducible regardless of environment except windows of course.

**Steps to Reproduce:**
Clean rebuild new install debian times 3 new agent install

All services are green except the loadbalancers they wont start error out. I suspect a network issue but can get it from the below error

The services they are supposed to balance are running and reachable over their control ports. The loadbalancer is used to redirect port 80 traffic to the services which run on varios ports but are all inherrent web services.

I have a simular setup running in production same base guidesetup without errors. Only differnce is it still runs 1.5.1. But I tried a downgrade from 1.5.3 to 1.5.1 even cleaning the hosts this made no difference.

**Results:** 
3/29/2017 10:51:38 PMruntime.cgocall(0x1bd7320, 0xc82003bbd8, 0x0)
3/29/2017 10:51:38 PM	/usr/local/go/src/runtime/cgocall.go:123 +0x11b fp=0xc82003bb78 sp=0xc82003bb48
3/29/2017 10:51:38 PMnet._C2func_getaddrinfo(0x7fe6c0000a10, 0x0, 0xc8203d86c0, 0xc820096548, 0x0, 0x0, 0x0)
3/29/2017 10:51:38 PM	??:0 +0x55 fp=0xc82003bbd8 sp=0xc82003bb78
3/29/2017 10:51:38 PMnet.cgoLookupIPCNAME(0xc8201b4637, 0x1c, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x296ac00)
3/29/2017 10:51:38 PM	/usr/local/go/src/net/cgo_unix.go:111 +0x448 fp=0xc82003bd50 sp=0xc82003bbd8
3/29/2017 10:51:38 PMnet.cgoLookupIP(0xc8201b4637, 0x1c, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
3/29/2017 10:51:38 PM	/usr/local/go/src/net/cgo_unix.go:163 +0x56 fp=0xc82003bda8 sp=0xc82003bd50
3/29/2017 10:51:38 PMnet.lookupIP(0xc8201b4637, 0x1c, 0x0, 0x0, 0x0, 0x0, 0x0)
3/29/2017 10:51:38 PM	/usr/local/go/src/net/lookup_unix.go:67 +0x94 fp=0xc82003be18 sp=0xc82003bda8
3/29/2017 10:51:38 PMnet.glob.func16(0x296acf0, 0xc8201b4637, 0x1c, 0x0, 0x0, 0x0, 0x0, 0x0)
3/29/2017 10:51:38 PM	/usr/local/go/src/net/hook.go:10 +0x4d fp=0xc82003be58 sp=0xc82003be18
3/29/2017 10:51:38 PMnet.lookupIPDeadline.func1(0x0, 0x0, 0x0, 0x0)
3/29/2017 10:51:38 PM	/usr/local/go/src/net/lookup.go:106 +0x71 fp=0xc82003bed8 sp=0xc82003be58
3/29/2017 10:51:38 PMinternal/singleflight.(*Group).doCall(0x36664d0, 0xc82009a6e0, 0xc8201b4637, 0x1c, 0xc820462700)
3/29/2017 10:51:38 PM	/usr/local/go/src/internal/singleflight/singleflight.go:93 +0x2c fp=0xc82003bf88 sp=0xc82003bed8
3/29/2017 10:51:38 PMruntime.goexit()
3/29/2017 10:51:38 PM	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc82003bf90 sp=0xc82003bf88
3/29/2017 10:51:38 PMcreated by internal/singleflight.(*Group).DoChan
3/29/2017 10:51:38 PM	/usr/local/go/src/internal/singleflight/singleflight.go:86 +0x3ee
3/29/2017 10:51:38 PM
3/29/2017 10:51:38 PMgoroutine 1 [select, locked to thread]:
3/29/2017 10:51:38 PMnet/http.(*Transport).getConn(0xc8200ea000, 0xc8200f20e0, 0x0, 0xc8201b4630, 0x4, 0xc8201b4637, 0x21, 0x0, 0x0, 0x0)
3/29/2017 10:51:38 PM	/usr/local/go/src/net/http/transport.go:711 +0x4ef
3/29/2017 10:51:38 PMnet/http.(*Transport).RoundTrip(0xc8200ea000, 0xc8200f20e0, 0xc8200ea000, 0x0, 0x0)
3/29/2017 10:51:38 PM	/usr/local/go/src/net/http/transport.go:311 +0x7e9
3/29/2017 10:51:38 PMnet/http.send(0xc8200f2000, 0x7fe6ce8b6620, 0xc8200ea000, 0xed06e1564, 0x3a8870f4, 0x3667ba0, 0xc8201b4720, 0x0, 0x0)
3/29/2017 10:51:38 PM	/usr/local/go/src/net/http/client.go:260 +0x6b7
3/29/2017 10:51:38 PMnet/http.(*Client).send(0xc8201b4660, 0xc8200f2000, 0xed06e1564, 0x3a8870f4, 0x3667ba0, 0xc82009c9a0, 0x0, 0x0)
3/29/2017 10:51:38 PM	/usr/local/go/src/net/http/client.go:155 +0x185
3/29/2017 10:51:38 PMnet/http.(*Client).doFollowingRedirects(0xc8201b4660, 0xc8200f2000, 0x296af18, 0x0, 0x0, 0x0)
3/29/2017 10:51:38 PM	/usr/local/go/src/net/http/client.go:475 +0x8a4
3/29/2017 10:51:38 PMnet/http.(*Client).Do(0xc8201b4660, 0xc8200f2000, 0x14, 0x0, 0x0)
3/29/2017 10:51:38 PM	/usr/local/go/src/net/http/client.go:188 +0xff
3/29/2017 10:51:38 PMgithub.com/rancher/lb-controller/vendor/github.com/rancher/go-rancher/v2.setupRancherBaseClient(0xc8204625e0, 0xc8200707c0, 0x0, 0x0)
3/29/2017 10:51:38 PM	/go/src/github.com/rancher/lb-controller/vendor/github.com/rancher/go-rancher/v2/common.go:156 +0x2a3
3/29/2017 10:51:38 PMgithub.com/rancher/lb-controller/vendor/github.com/rancher/go-rancher/v2.NewRancherClient(0xc8200707c0, 0xc8200707c0, 0x0, 0x0)
3/29/2017 10:51:38 PM	/go/src/github.com/rancher/lb-controller/vendor/github.com/rancher/go-rancher/v2/generated_client.go:319 +0xcb
3/29/2017 10:51:38 PMgithub.com/rancher/lb-controller/provider/rancher.init.1()
3/29/2017 10:51:38 PM	/go/src/github.com/rancher/lb-controller/provider/rancher/rancher.go:65 +0x49d
3/29/2017 10:51:38 PMgithub.com/rancher/lb-controller/provider/rancher.init()
3/29/2017 10:51:38 PM	/go/src/github.com/rancher/lb-controller/provider/rancher/rancher.go:889 +0x77
3/29/2017 10:51:38 PMmain.init()
3/29/2017 10:51:38 PM	/go/src/github.com/rancher/lb-controller/plugins.go:12 +0x8d
3/29/2017 10:51:38 PM
3/29/2017 10:51:39 PMgoroutine 17 [syscall, locked to thread]:
3/29/2017 10:51:39 PMruntime.goexit()
3/29/2017 10:51:39 PM	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1
3/29/2017 10:51:39 PM
3/29/2017 10:51:39 PMgoroutine 19 [chan receive]:
3/29/2017 10:51:39 PMgithub.com/rancher/lb-controller/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x3667fe0)
3/29/2017 10:51:39 PM	/go/src/github.com/rancher/lb-controller/vendor/github.com/golang/glog/glog.go:882 +0x67
3/29/2017 10:51:39 PMcreated by github.com/rancher/lb-controller/vendor/github.com/golang/glog.init.1
3/29/2017 10:51:39 PM	/go/src/github.com/rancher/lb-controller/vendor/github.com/golang/glog/glog.go:410 +0x297
3/29/2017 10:51:39 PM
3/29/2017 10:51:39 PMgoroutine 23 [syscall]:
3/29/2017 10:51:39 PMos/signal.signal_recv(0x17)
3/29/2017 10:51:39 PM	/usr/local/go/src/runtime/sigqueue.go:116 +0x132
3/29/2017 10:51:39 PMos/signal.loop()
3/29/2017 10:51:39 PM	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
3/29/2017 10:51:39 PMcreated by os/signal.init.1
3/29/2017 10:51:39 PM	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37
3/29/2017 10:51:39 PM
3/29/2017 10:51:39 PMgoroutine 34 [select]:
3/29/2017 10:51:39 PMgithub.com/rancher/lb-controller/vendor/github.com/patrickmn/go-cache.(*janitor).Run(0xc8204b8800, 0xc820070700)
3/29/2017 10:51:39 PM	/go/src/github.com/rancher/lb-controller/vendor/github.com/patrickmn/go-cache/cache.go:1037 +0x15c
3/29/2017 10:51:39 PMcreated by github.com/rancher/lb-controller/vendor/github.com/patrickmn/go-cache.runJanitor
3/29/2017 10:51:39 PM	/go/src/github.com/rancher/lb-controller/vendor/github.com/patrickmn/go-cache/cache.go:1056 +0x81
3/29/2017 10:51:39 PM
3/29/2017 10:51:39 PMgoroutine 35 [chan receive]:
3/29/2017 10:51:39 PMgithub.com/rancher/lb-controller/vendor/github.com/rancher/event-subscriber/locks.locker()
3/29/2017 10:51:39 PM	/go/src/github.com/rancher/lb-controller/vendor/github.com/rancher/event-subscriber/locks/locks.go:61 +0xdf
3/29/2017 10:51:39 PMcreated by github.com/rancher/lb-controller/vendor/github.com/rancher/event-subscriber/locks.init.1
3/29/2017 10:51:39 PM	/go/src/github.com/rancher/lb-controller/vendor/github.com/rancher/event-subscriber/locks/locks.go:7 +0x59
3/29/2017 10:51:39 PM
3/29/2017 10:51:39 PMgoroutine 36 [select]:
3/29/2017 10:51:39 PMnet/http.setRequestCancel.func4(0x0, 0xc8201b4750, 0xc820070880, 0xc82006f2c0)
3/29/2017 10:51:39 PM	/usr/local/go/src/net/http/client.go:333 +0x12e
3/29/2017 10:51:39 PMcreated by net/http.setRequestCancel
3/29/2017 10:51:39 PM	/usr/local/go/src/net/http/client.go:341 +0x2f7
3/29/2017 10:51:39 PM
3/29/2017 10:51:39 PMgoroutine 37 [select]:
3/29/2017 10:51:39 PMnet.lookupIPDeadline(0xc8201b4637, 0x1c, 0xed06e1578, 0x3aebc95a, 0x3667ba0, 0x0, 0x0, 0x0, 0x0, 0x0)
3/29/2017 10:51:39 PM	/usr/local/go/src/net/lookup.go:109 +0x6a6
3/29/2017 10:51:39 PMnet.internetAddrList(0x2555df0, 0x3, 0xc8201b4637, 0x21, 0xed06e1578, 0x3aebc95a, 0x3667ba0, 0x0, 0x0, 0x0, ...)
3/29/2017 10:51:39 PM	/usr/local/go/src/net/ipsock.go:252 +0x6ee
3/29/2017 10:51:39 PMnet.resolveAddrList(0x25511e0, 0x4, 0x2555df0, 0x3, 0xc8201b4637, 0x21, 0xed06e1578, 0x3aebc95a, 0x3667ba0, 0x0, ...)
3/29/2017 10:51:39 PM	/usr/local/go/src/net/dial.go:158 +0x466
3/29/2017 10:51:39 PMnet.(*Dialer).Dial(0xc82009a410, 0x2555df0, 0x3, 0xc8201b4637, 0x21, 0x0, 0x0, 0x0, 0x0)
3/29/2017 10:51:39 PM	/usr/local/go/src/net/dial.go:216 +0x124
3/29/2017 10:51:39 PMnet.(*Dialer).Dial-fm(0x2555df0, 0x3, 0xc8201b4637, 0x21, 0x0, 0x0, 0x0, 0x0)
3/29/2017 10:51:39 PM	/usr/local/go/src/net/http/transport.go:38 +0x6e
3/29/2017 10:51:39 PMnet/http.(*Transport).dial(0xc8200ea000, 0x2555df0, 0x3, 0xc8201b4637, 0x21, 0x0, 0x0, 0x0, 0x0)
3/29/2017 10:51:39 PM	/usr/local/go/src/net/http/transport.go:659 +0x96
3/29/2017 10:51:39 PMnet/http.(*Transport).dialConn(0xc8200ea000, 0x0, 0xc8201b4630, 0x4, 0xc8201b4637, 0x21, 0x0, 0x0, 0x0)
3/29/2017 10:51:39 PM	/usr/local/go/src/net/http/transport.go:762 +0x1e3d
3/29/2017 10:51:39 PMnet/http.(*Transport).getConn.func4(0xc8200ea000, 0x0, 0xc8201b4630, 0x4, 0xc8201b4637, 0x21, 0xc82006f380)
3/29/2017 10:51:39 PM	/usr/local/go/src/net/http/transport.go:706 +0x66
3/29/2017 10:51:39 PMcreated by net/http.(*Transport).getConn
3/29/2017 10:51:39 PM	/usr/local/go/src/net/http/transport.go:708 +0x262

**Comment by robxu9** [comment]
Can confirm, getting the same thing on RancherOS, but single node Rancher + Cattle environment:

```
runtime.cgocall(0x1bd7320, 0xc820037bd8, 0x0)
	/usr/local/go/src/runtime/cgocall.go:123 +0x11b fp=0xc820037b78 sp=0xc820037b48
net._C2func_getaddrinfo(0x7f798c0008c0, 0x0, 0xc8201449c0, 0xc8200fa5a0, 0x0, 0x0, 0x0)
	??:0 +0x55 fp=0xc820037bd8 sp=0xc820037b78
net.cgoLookupIPCNAME(0xc82023fbc7, 0x14, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x296ac00)
	/usr/local/go/src/net/cgo_unix.go:111 +0x448 fp=0xc820037d50 sp=0xc820037bd8
net.cgoLookupIP(0xc82023fbc7, 0x14, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/cgo_unix.go:163 +0x56 fp=0xc820037da8 sp=0xc820037d50
net.lookupIP(0xc82023fbc7, 0x14, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/lookup_unix.go:67 +0x94 fp=0xc820037e18 sp=0xc820037da8
net.glob.func16(0x296acf0, 0xc82023fbc7, 0x14, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/hook.go:10 +0x4d fp=0xc820037e58 sp=0xc820037e18
net.lookupIPDeadline.func1(0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/lookup.go:106 +0x71 fp=0xc820037ed8 sp=0xc820037e58
internal/singleflight.(*Group).doCall(0x36664d0, 0xc82000aaa0, 0xc82023fbc7, 0x14, 0xc820165ec0)
	/usr/local/go/src/internal/singleflight/singleflight.go:93 +0x2c fp=0xc820037f88 sp=0xc820037ed8
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820037f90 sp=0xc820037f88
created by internal/singleflight.(*Group).DoChan
	/usr/local/go/src/internal/singleflight/singleflight.go:86 +0x3ee

goroutine 1 [select, locked to thread]:
net/http.(*Transport).getConn(0xc8200e2000, 0xc8201100e0, 0x0, 0xc82023fbc0, 0x4, 0xc82023fbc7, 0x19, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:711 +0x4ef
net/http.(*Transport).RoundTrip(0xc8200e2000, 0xc8201100e0, 0xc8200e2000, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:311 +0x7e9
net/http.send(0xc820110000, 0x7f799b4b5550, 0xc8200e2000, 0xed071141f, 0xa04f50e, 0x3667ba0, 0xc82023fc50, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:260 +0x6b7
net/http.(*Client).send(0xc82023fbf0, 0xc820110000, 0xed071141f, 0xa04f50e, 0x3667ba0, 0xc82010f1e0, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:155 +0x185
net/http.(*Client).doFollowingRedirects(0xc82023fbf0, 0xc820110000, 0x296af18, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:475 +0x8a4
net/http.(*Client).Do(0xc82023fbf0, 0xc820110000, 0x14, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:188 +0xff
github.com/rancher/lb-controller/vendor/github.com/rancher/go-rancher/v2.setupRancherBaseClient(0xc820165da0, 0xc8202de800, 0x0, 0x0)
	/go/src/github.com/rancher/lb-controller/vendor/github.com/rancher/go-rancher/v2/common.go:156 +0x2a3
github.com/rancher/lb-controller/vendor/github.com/rancher/go-rancher/v2.NewRancherClient(0xc8202de800, 0xc8202de800, 0x0, 0x0)
	/go/src/github.com/rancher/lb-controller/vendor/github.com/rancher/go-rancher/v2/generated_client.go:319 +0xcb
github.com/rancher/lb-controller/provider/rancher.init.1()
	/go/src/github.com/rancher/lb-controller/provider/rancher/rancher.go:65 +0x49d
github.com/rancher/lb-controller/provider/rancher.init()
	/go/src/github.com/rancher/lb-controller/provider/rancher/rancher.go:889 +0x77
main.init()
	/go/src/github.com/rancher/lb-controller/plugins.go:12 +0x8d

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 20 [chan receive]:
github.com/rancher/lb-controller/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x3667fe0)
	/go/src/github.com/rancher/lb-controller/vendor/github.com/golang/glog/glog.go:882 +0x67
created by github.com/rancher/lb-controller/vendor/github.com/golang/glog.init.1
	/go/src/github.com/rancher/lb-controller/vendor/github.com/golang/glog/glog.go:410 +0x297

goroutine 5 [syscall]:
os/signal.signal_recv(0x17)
	/usr/local/go/src/runtime/sigqueue.go:116 +0x132
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 50 [select]:
github.com/rancher/lb-controller/vendor/github.com/patrickmn/go-cache.(*janitor).Run(0xc82042b450, 0xc8202de780)
	/go/src/github.com/rancher/lb-controller/vendor/github.com/patrickmn/go-cache/cache.go:1037 +0x15c
created by github.com/rancher/lb-controller/vendor/github.com/patrickmn/go-cache.runJanitor
	/go/src/github.com/rancher/lb-controller/vendor/github.com/patrickmn/go-cache/cache.go:1056 +0x81

goroutine 51 [chan receive]:
github.com/rancher/lb-controller/vendor/github.com/rancher/event-subscriber/locks.locker()
	/go/src/github.com/rancher/lb-controller/vendor/github.com/rancher/event-subscriber/locks/locks.go:61 +0xdf
created by github.com/rancher/lb-controller/vendor/github.com/rancher/event-subscriber/locks.init.1
	/go/src/github.com/rancher/lb-controller/vendor/github.com/rancher/event-subscriber/locks/locks.go:7 +0x59

goroutine 52 [select]:
net/http.setRequestCancel.func4(0x0, 0xc82023fc80, 0xc8202de8c0, 0xc82033f260)
	/usr/local/go/src/net/http/client.go:333 +0x12e
created by net/http.setRequestCancel
	/usr/local/go/src/net/http/client.go:341 +0x2f7

goroutine 53 [select]:
net.lookupIPDeadline(0xc82023fbc7, 0x14, 0xed0711433, 0xa06fbf3, 0x3667ba0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/lookup.go:109 +0x6a6
net.internetAddrList(0x2555df0, 0x3, 0xc82023fbc7, 0x19, 0xed0711433, 0xa06fbf3, 0x3667ba0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/ipsock.go:252 +0x6ee
net.resolveAddrList(0x25511e0, 0x4, 0x2555df0, 0x3, 0xc82023fbc7, 0x19, 0xed0711433, 0xa06fbf3, 0x3667ba0, 0x0, ...)
	/usr/local/go/src/net/dial.go:158 +0x466
net.(*Dialer).Dial(0xc820088410, 0x2555df0, 0x3, 0xc82023fbc7, 0x19, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/dial.go:216 +0x124
net.(*Dialer).Dial-fm(0x2555df0, 0x3, 0xc82023fbc7, 0x19, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:38 +0x6e
net/http.(*Transport).dial(0xc8200e2000, 0x2555df0, 0x3, 0xc82023fbc7, 0x19, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:659 +0x96
net/http.(*Transport).dialConn(0xc8200e2000, 0x0, 0xc82023fbc0, 0x4, 0xc82023fbc7, 0x19, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:762 +0x1e3d
net/http.(*Transport).getConn.func4(0xc8200e2000, 0x0, 0xc82023fbc0, 0x4, 0xc82023fbc7, 0x19, 0xc82033f380)
	/usr/local/go/src/net/http/transport.go:706 +0x66
created by net/http.(*Transport).getConn
	/usr/local/go/src/net/http/transport.go:708 +0x262
```

**Comment by claybbs** [comment]
I had got the same error.

**Comment by aemneina** [comment]
Curious if this is a problem on the latest (or 1.5.10+)?

**Comment by robxu9** [comment]
I just upgraded to the latest Rancher version - it's no longer a problem for me. Thanks! If nobody else has this issue, feel free to close this.
