### ISSUE TITLE
Classic Host Functional issues

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#8345]
**Rancher Versions:** 3/28

**Issues:** 

- [x] InterouteVDC - Can't see Icon?
![image](https://cloud.githubusercontent.com/assets/11514927/24473336/c4e77180-147d-11e7-80df-1bf48e8b73a4.png)

- [x] When switching between different drivers, the icons appear and disappear depending on which one you have selected.
When first enter:
![image](https://cloud.githubusercontent.com/assets/11514927/24473406/f93e8446-147d-11e7-875c-c1e033cf5186.png)

After clicking a couple of the drivers on top:
![image](https://cloud.githubusercontent.com/assets/11514927/24473438/1d9789a0-147e-11e7-93b8-7f2f37524e91.png)

- [ ] Click on InterouteVDC driver and it hangs.  Error:
Uncaught EmberError {description: undefined, fileName: undefined, lineNumber: undefined, message: "Assertion Failed: HTMLBars error: Could not find c…o component or template with that name was found)", name: "Error"…}

- [x] Classic Add host, Close & Create buttons should take me back to Host list page, not the New Add Host page.

- [x] Create button creates host, but doesn't leave add page.

- [x] Can't scale host on add host page

**Comment by westlywright** [comment]
@tfiduccia most of this is fixed except the interroute driver which we talked about breaking into another ticket

**Comment by tfiduccia** [comment]
Version - 4/24
Verified fixed
