### ISSUE TITLE
StoragePools from storage drivers of scope local do not get cleaned up when hosts are removed

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#8346]
**Rancher Versions:**
Server: v1.5.x

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
Create a cattle environment, and deploy the secrets volume driver. 
Note on the Infrastructure->Storage tab the Storage pools.
Remove a host, and observe that the storage pool still exists on the storage tab.

**Results:** 
Storage pools that are scoped local to the host, should be removed when the host is removed from the system.

**Comment by sangeethah** [comment]
Tested with v1.6-development branch.

Create a cattle environment with 2 hosts .
Deploy the rancher-secrets and secrets-bridge-v2  volume driver.
Remove a host.
Storage pool does not list the removed host anymore.
