### ISSUE TITLE
skydns pods are deployed to one host

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#8347]
**Rancher Versions:**
Server: v1.5.3
kubernetes (if applicable):
1.5.2

**Steps to Reproduce:**
deploy kubernetes. have > 3 hosts
kube-dns deploys all pods to one host

**Desired:**
have the kube-dns pods spread across the infra by using anti-affinity.

**Comment by aemneina** [comment]
Looks like this will do the trick: https://github.com/rancher/kubernetes-package/pull/46

**Comment by aemneina** [comment]
and this: https://github.com/rancher/rancher-catalog/pull/621

**Comment by aemneina** [comment]
Tracking work here: https://github.com/rancher/rancher/issues/8530

**Comment by alena1108** [comment]
Once the template is released, following things need to be tested:

1) Setting up the scale for sky dns service via template field
2) Make sure that sky dns containers always land on the separate hosts (there is an anti affinity rule present)
3) try restart addon manager, and make sure that the sky dns service comes up correctly (we replace all addon driven services on the restart to handle upgrade use case)

**Comment by alena1108** [comment]
@galal-hussein can be tested with the latest 1.7.1 kubernetes template

**Comment by galal-hussein** [comment]
Validated the scalability features for SkyDNS:

- Deploy Kubernetes on 3 hosts and set kubedns scale to 3, make sure that you see 3 kubedns pods being deployed one on each host.
- Deploy Kubernetes on 3 hosts and set kubedns scale to 4, make sure that you see only 3 kubedns pods being deployed one on each host.
- Deploy kubernetes on 3 hosts and set kubedns scale to 2, one one of the host deploy a test pod and then bring down the host that contain one of the kubedns pods and not the dnstiming pod, make sure that no interruptions happen in the dns queries from the test pod.
- Deploy kubernetes on 3 hosts and set kubedns scale to 2, one one of the host deploy a test pod and then remove one of the kubedns pods, make sure that no interruptions happen in the dns queries from the test pod.
