### ISSUE TITLE
[external-dns] Error creating multiple records without invalidating

### ISSUE THREAD

**Issue by ebar0n** [rancher/rancher#8353]
**Rancher Versions:**
Server: v1.5.3
digitalocean-dns: external-dns:v0.6.2
healthcheck: v0.2.3
ipsec: :holder
network-services: metadata:v0.8.11 and network-manager:v0.5.3
nfs: storage-nfs:v0.6.5
portainer: portainer-agent:v0.1.0
scheduler: scheduler:v0.7.5
swarm: swarmkit:v1.13.0-beta.1

**Docker Version:**

1.13.1

**OS and where are the hosts located? (cloud, bare metal, etc):**

Digitalocean

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

Single node rancher internal DB

**Environment Type:**

Swarm

**Steps to Reproduce:**

2 servers reserved for database and 2+n for applications (where there are services such as celery, apis and nginx servers, with load balancers).

Install all the services mentioned and a custom application stack, after that add a load balancer, and finally add a dns service.

**Results:** 

The DNS service, from time to time updates the records to the DNS provider used, in this case Digital Ocean.

That service has no routines (or not working) that seeks to eliminate invalid DNS records, only updates and as a consequence creates a huge amount of records that collapse the provider, even leaving records of hosts created and eliminated.

Attached are 2 images that check it, leave some hosts started all night and the result in the morning was to have 2414 A records in the DNS provider and some ips were already invalid because they delete some hosts.

![DNS](https://cloud.githubusercontent.com/assets/1896362/24509508/240f9c7e-152c-11e7-89b1-1d2eb1b3875d.png)
![RANCHER](https://cloud.githubusercontent.com/assets/1896362/24509509/24274d74-152c-11e7-896d-86bb854cdd41.png)

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
