### ISSUE TITLE
healthState of container is healthy while stack is stopped

### ISSUE THREAD

**Issue by kelchm** [rancher/rancher#8354]
**Rancher Versions:**
Rancher	v1.4.1
Cattle	v0.176.9
User Interface	v1.4.6
Rancher CLI	v0.4.1
Rancher Compose	v0.12.2

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Rancher HA

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Setup a basic stack with a single service that has a health check. Stop this stack after creating it.

**Results:** 
When querying the API for a container within the service it will show a `healthState` of "healthy" despite the fact it is currently stopped.

**Comment by aemneina** [comment]
hey @kelchm if one were to explicitly stop/deactivate a service, that would be a graceful exit the stack, and remove the healthchecks for that service. I'd say this would be desired behavior.
