### ISSUE TITLE
Adding initializing/re-initializing timeouts for all services in k8s template 

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#8356]
**Rancher Versions:**
Server: 1.5.3
kubernetes (if applicable): 1.5.2

**Steps to Reproduce:**
- Run k8s on 3 hosts
- Stop docker daemon on one of the hosts that has rancher-kubernetes-agent or kubectld

**Results:** 

The host goes to Disconnected state and the kubectld and rancher-kubernetes-agent are not rescheduled on a healthy host, they are stuck in reinitializing state forever.

**Comment by soumyalj** [comment]
On a Kubernetes setup with 3 hosts turned OFF all three hosts . After all the hosts were in disconnected state, powered ON two hosts and one host was still left in disconnected state. The etcd cluster was healthy. But the scheduler container was on the disconnected host and it was stuck in re-initializing state. It did not move to an active host. New pods created were in pending state.
```
> kubectl describe pod k8testrc12-pq5mc
Name:           k8testrc12-pq5mc
Namespace:      default
Node:           /
Labels:         k8s-app=k8test12-service
Status:         Pending
IP:
Controllers:    ReplicationController/k8testrc12
Containers:
  testcontainer:
    Image:      sangeetha/testnewhostrouting
    Port:       80/TCP
    Volume Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-b34jq (ro)
    Environment Variables:      <none>
Volumes:
  default-token-b34jq:
    Type:       Secret (a volume populated by a Secret)
    SecretName: default-token-b34jq
QoS Class:      BestEffort
Tolerations:    <none>
No events.

```
<img width="1050" alt="screen shot 2017-03-30 at 5 06 30 pm" src="https://cloud.githubusercontent.com/assets/18536626/24531085/3bedfa36-156b-11e7-9e2a-ac6d8ba5493d.png">

**Comment by alena1108** [comment]
@leodotcloud could you add initializing_timeout, reinitializing_timeout to rancher-compose of new k8s 1.6 template? consult with @LLParse @cloudnautique on what is usually the adequate timeouts on the services to init.

**Comment by deniseschannon** [comment]
@soumyalj How did you start k8s in your case? `scheduler` should not be present in the default environment template for k8s. Was this a setup where it started as a cattle template and you started k8s from the catalog?

**Comment by soumyalj** [comment]
@deniseschannon : This is Kubernetes-Scheduler, not the scheduler which is part of our infra-stacks.

**Comment by galal-hussein** [comment]
Rancher version: 1.5.4-rc1
Kubernetes: v1.5.4-rancher1-1

Didn't see the problem again with kubernetes infra stack, however i am still seeing this problem with kubernetes-ingress-lbs stack and kubernetes-lbs stack.

**Comment by galal-hussein** [comment]
Rancher server: 1.5.4-rc2

@deniseschannon I was able to verify the initializing/reinitializing timeout for LB services in k8s, after stopping the host that has LB container, it remained in reinitializing state for 1 minute and then got removed.
