### ISSUE TITLE
SSH keys are not removed when we remove machines/host

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#836]
Steps:
1.  Create a machine/host
2.  Delete and purge the machine/host

Results:
The machine is removed but the SSH keys are still left around.  For some Hosts it means I can't reuse the name because the SSH key is still out there and thinks I'm creating a duplicate.  So our host creation errors out.

Expected:
Any way we can remove these?

**Comment by will-chan** [comment]
I assume you mean the SSH key left on the cloud provider?  This might be more difficult because it would mean we would have to write custom API calls against these providers.

**Comment by vincent99** [comment]
Yes.. If you look at any of our provider accounts you'll see they are littered with orphaned SSH keys.

**Comment by will-chan** [comment]
Unfortunately, docker-machine doesn't remove this so if we want to do this, we'd have to make the call against all the providers.

**Comment by tfiduccia** [comment]
Version - master 07/14/2016
Checked supported hosts, and ssh keys are removed if you create & destroy through the UI.  Closing bug
