### ISSUE TITLE
Falied to add environment

### ISSUE THREAD

**Issue by niusmallnan** [rancher/rancher#8367]
**Rancher Versions:**
Server: v1.5.3

![image](https://cloud.githubusercontent.com/assets/998984/24534951/a3693d22-1603-11e7-898e-5ec7d7898d64.png)

![image](https://cloud.githubusercontent.com/assets/998984/24534954/a8a68696-1603-11e7-98f4-46c60c68502f.png)

**Comment by niusmallnan** [comment]
Just disable community catalog, you can reproduce.

**Comment by jgreat** [comment]
We are using rancher 1.5.3 also.  Looks like even with community catalog enabled its failing.  We are getting the following in the error in the rancher server logs (console out on the server container)

```
docker/rancher-server[17334]: [2017-03-31 20:42:20]  
docker/rancher-server[17334]: time="2017-03-31T20:42:22Z" level=error msg="Failed to perform catalog refresh: community: Error 1366: Incorrect string value: '\\xE2\\x9D\\xA4\\xEF\\xB8\\x8F...' for column 'readme' at row 1"
docker/rancher-server[17334]: (Error 1366: Incorrect string value: '\xE2\x9D\xA4\xEF\xB8\x8F...' for column 'readme' at row 1)
```

As a work around we were able to use the rancher cli to create an environment.

**Comment by vincent99** [comment]
There's a community catalog entry with emoji in the README, which depending on the charset of the database you're using cannot be stored into the field.  For now we just removed the bad characters until we have a proper solution.

**Comment by jgreat** [comment]
Thanks, the community catalog now loads.  

The new environment page still fails to load if the community catalog is disabled.

**Comment by aemneina** [comment]
@vincent99 I can repro @jgreat's issue.

**Comment by deniseschannon** [comment]
Closing in favor of https://github.com/rancher/rancher/issues/8461 

The UI for this page is broken if the catalogs are disabled.
