### ISSUE TITLE
add convoy-gluster Volumes Rancher Panel

### ISSUE THREAD

**Issue by andruwa13** [rancher/rancher#8371]
*Can not mount convoy-gluster drive*
Log: `level=fatal msg="open /host/var/run/docker/execdriver/native: no such file or directory"`

Stack convoy-gluster:

docker-compose.yml and rancher-compose.yml
[compose.zip](https://github.com/rancher/rancher/files/884775/compose.zip)

Stack GlusterFS Server:

docker-compose.yml and rancher-compose.yml
[GlusterFS_Serber.zip](https://github.com/rancher/rancher/files/884781/GlusterFS_Serber.zip)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.5.3` Cattle: `v0.177.10` UI: `v1.5.8` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`service.containers`|
|Docker| `v1.12.5`

**Comment by aemneina** [comment]
convoy-gluster was deprecated long ago, I wouldnt expect this to work with anything newer than rancher 1.1.x
