### ISSUE TITLE
500 Internal Server Error when trying to access any catalog in v1.5.3, v1.5.2 & v1.5.1 using RancherOS v0.9.1 & v0.8.1

### ISSUE THREAD

**Issue by richbos** [rancher/rancher#8372]
**Rancher Versions:**
Server: Tested under v1.5.3, v1.5.2 & v1.5.1
healthcheck: unobtainable
ipsec: unobtainable
network-services: unobtainable
scheduler: unobtainable
kubernetes (if applicable):

**Docker Version:**
As is included with RancherOS v0.9.1 & v0.8.1

**OS and where are the hosts located? (cloud, bare metal, etc):**
RancherOS v0.9.1 and/or v0.8.1 EC2 AMI for the Rancher server. Deployed in AWS. 
No hosts currently deployed but the error was the same when so.

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node Rancher deployed from the following TF plan - https://github.com/SkeltonThatcher/aws-terraform-rancher-single-node-ha

Access via ALB or direct via EC2 instance public IP
External RDS DB.

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**
Install via TF plan as detailed, try to access any catalog.

**Results:** 
As per the following screen grab.

![rancher-catalog-error](https://cloud.githubusercontent.com/assets/1983458/24544283/98ed22fe-15fa-11e7-8a3c-7ff400977d6b.png)

**Comment by vincent99** [comment]
Server container log?

**Comment by richbos** [comment]
Hi Vincent, I have attached the server container log as requested from one of our failed (now destroyed) builds. Apologies there for not doing so initially.
Any guidance would be most appreciated as we did have this working great, but now we get the error, it would seem all versions, plus rancherOS and Ubuntu. As such it would seem to point at our config, however it's baffling as Rancher server itself seems to install and we can access it.

That said, I'm wondering if this line from the log might be relevant?

`2017-04-01 15:53:14,862 ERROR [:] [] [] [] [qtp859417998-83] [i.g.i.g.r.handler.ExceptionHandler  ] Exception in API for request [http://ros81ran153.skeltonthatcher.space:8080/v1/proxy/http://localhost:8088/v1-catalog/catalogs]. Error id: [3f27ba4c-c1a6-4f8b-a265-f75a08eaa741]. org.apache.http.conn.HttpHostConnectException: Connect to localhost:8088 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused`

[server container log.txt](https://github.com/rancher/rancher/files/887800/server.container.log.txt)

**Comment by richbos** [comment]
Hi Vincent, we have had this issue raised on our own repo, with the member highlighting that you now longer support ALB (over ELB).

https://github.com/SkeltonThatcher/aws-terraform-rancher-single-node-ha/issues/1

We switched to ALB from ELB as advised several months ago.

Perhaps this might be the cause of the issue? 

I shall test with an ELB regressed TF plan this week and update with my findings.

**Comment by mcanevet** [comment]
It looks like I fall on the same issue on one of our Rancher Servers. I though it was because my database was in `latin1` because of #8064, but I recreate it from scratch using `COLLATE = 'utf8_general_ci' CHARACTER SET = 'utf8'` and I still can get the catalog.
The server is running on RHEL7.2 using docker-engine 1.12.6. I don't have any issues on Ubuntu 16.04.

**Comment by mcanevet** [comment]
@vincent99 I can reproduce on an RHEL7.2/Docker-engine 12.6 with this setup : https://gist.github.com/mcanevet/445af52fb4c5eec3884c372f76c29f04 with a blank database.

**Comment by richbos** [comment]
To address my previous comments re ALB/ELB, it's definitely not that. We have tested extensively today with an https/ssl enabled ELB deployment and are getting the same issue.

**Comment by richbos** [comment]
Hi, to update we have tested today with v1.4.2 (server) and catalog access is OK, no problems at all.

We only get the 500 error when using Rancher v1.51, v1.5.2 or v1.5.3. With ELB or ALB, RDS, and either RancherOS or Ubuntu.

**Comment by danieljgraves** [comment]
Somewhat new to docker here, but how do you manually specify the version of the rancher server container to an older version? For example I had in my TF build: rancher/server:stable and changed it to rancher/server:1.4.2, which obviously failed, but I don't know how to test against an older version. I'd like to test richbos update of pointing my container version to 1.4.2 (server).

**Comment by richbos** [comment]
Hi, to further update. We have ascertained that this is an issue when using RDS. Testing with a local DB the catalog(s) all load fine.

We have created a DB parameter group using Terraform with the following settings, however the issue is still present.

`resource "aws_db_parameter_group" "rancher" {
  name   = "rancher-pg"
  family = "mysql5.6"

  parameter {
    name  = "character_set_client"
    value = "utf8"
  }

  parameter {
    name  = "collation_connection"
    value = "utf8_general_ci"
  }

  parameter {
    name  = "character_set_database"
    value = "utf8"
  }

  parameter {
    name  = "character_set_filesystem"
    value = "utf8"
  }

  parameter {
    name  = "character_set_results"
    value = "utf8"
  }

  parameter {
    name  = "character_set_server"
    value = "utf8"
  }

  parameter {
    name  = "collation_connection"
    value = "utf8_general_ci"
  }

  parameter {
    name  = "collation_server"
    value = "utf8_general_ci"
  }

}`

To clarify, Rancher still loads, we have enabled SSL/ELB which works fine, but we are getting an error 500 if trying to access any catalogs when using RDS on Rancher v1.5.0/5.1/5.3/5.3.
Versions 1.4.1/4.2/4.3 are fine.

**Comment by lukaspour** [comment]
I can confirm this issue. Rancher catalog does not work with RDS(Aurora).

**Comment by mcanevet** [comment]
I'm not using RDS but an external database using the mysql:5.7 image and I also have this issue... But only on RedHat7, not on Ubuntu 16.04

**Comment by richbos** [comment]
I did try with Ubuntu 16.04 and the error was still there for us, however now I'm curious so will re-test to verify.
We are currently using RancherOS.

**Comment by richbos** [comment]
I have discovered what the issue was ([with our TF plan](https://github.com/SkeltonThatcher/aws-terraform-rancher-single-node-ha)) and have resolved the catalog access issue.

In our plan, the `aws_db_instance.rancher` var from `server.tf` which feeds the `userdata_srv.template` was using the endpoint attribute. This was doubling up the port (for dial tcp) and adding an extra 3306 (i.e. 3306:3306).

Changing the attribute to use address (as follows) has resolved the catalog access issue.

`database_address = "${aws_db_instance.rancher.address}"`

**Comment by mcanevet** [comment]
@richbos I'm not sure to understand your fix...

**Comment by richbos** [comment]
Hi, the issue we were having was specific to our Terraform plan...

https://github.com/SkeltonThatcher/aws-terraform-rancher-single-node-ha

In our plan, in server.tf we were using `aws_db_instance.rancher.endpoint` as a var to feed `/files/userdata_srv.template`.

As I discovered from tailing the docker server container log during a deployment, this was adding an extra 3306 to the address used by dial tcp (i.e. :3306:3306), which was giving an error.

The RDS endpoint does include :3306, so by changing `endpoint` to `address` in the var then string that was passed only contained the RDS DB address, without the extra :3306.

I am presuming that `dial tcp` is the mechanism by which the catalog is accessed (I could be wrong), but it would seem to be so as by resolving the issue there we can now access the catalog from an installation of Rancher server deployed using our Terraform plan.

Hope that helps to explain, although perhaps you may have a different issue, but with the same symptom?
