### ISSUE TITLE
[rancher-dns]  dns server caches erroneous responses

### ISSUE THREAD

**Issue by stszap** [rancher/rancher#8375]
**Rancher Versions:**
Server: 1.4
healthcheck: 0.2.3
ipsec: 0.8.7
network-services: 0.4.5
scheduler: 0.6.3

**Docker Version:**
17.03.0-ce
**OS and where are the hosts located? (cloud, bare metal, etc):**
bare metal
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
cattle
**Steps to Reproduce:**
If rancher's internal dns service makes a query and receives response with  SERVFAIL reply code it will cache it for 10 minutes by default.

**Results:** 
Even if dns outage was for less than a minute, rancher's dns service will not try to resolve requested domain name for 10 minutes.

I can 100% reproduce it with rancher/dns:v0.13.0 and rancher/dns:v0.14.1.

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
