### ISSUE TITLE
Feature Request: Out-of-band Heartbeat for Agent <-> Server Communication

### ISSUE THREAD

**Issue by ecliptik** [rancher/rancher#8380]
### Summary
Feature request of adding an optional out-of-band heartbeat as a secondary method for `rancher/agent`<-> `rancher/server` communication.

Original request is for maintaining stability of a cluster to avoid agents going into disconnected or inactive states while still running application stacks. Could be expanded in the future for additional heartbeat features such as shared resource control.

#### Justification
- Avoid single point of failure if primary network communication is severed between agent and master
- Allow for rudimentary management of cluster hosts to help recover during a communication breakdown
- Avoid possible split-brain scenarios when not knowing if a stack is running elsewhere due to an agent disconnect
- Is a major feature in other enterprise clustering systems such as Oracle RAC, Yarn, Veritas, etc

#### Challenges
- May be difficult to configure or even impossible in a public cloud environment
- Adds additional layer of complexity for agent <-> master communication (should be optional)

#### Suggestions
- Use secondary private network on a secondary network device
- Use a shared storage mechanism that doesn't rely on primary network (eg EBS for AWS)

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
