### ISSUE TITLE
sidekicks array not empty for the sidekick container in metadata

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#8382]
```curl -H "Accept: application/json" 169.254.169.250/latest/services | jq '.[] | select (.kind | contains("networkDriverService") ) | {name: .name, sidekicks: .sidekicks}'
{
  "name": "cni-driver",
  "sidekicks": [
    "router",
    "cni-driver"
  ]
}
{
  "name": "ipsec",
  "sidekicks": [
    "router",
    "cni-driver"
  ]
}
{
  "name": "router",
  "sidekicks": [
    "router",
    "cni-driver"
  ]
}
```

"router" and "cni-driver" are the sidekicks of "ipsec". Shouldn't the "sidekicks" array be empty for the other two except "ipsec"?

some might think of sidekick as “other launch configs of the service other than myself”, not secondary launch configs. But you can get this info via primary service anyways, so I think setting “sidekicks” just on the primary service is fine

here is the place in the code where it can be fixed: https://github.com/rancher/cattle/blob/master/code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/dao/impl/MetaDataInfoDaoImpl.java#L412

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
