### ISSUE TITLE
[rancher-net] when a container is restart , the dns link  still point the old ip address

### ISSUE THREAD

**Issue by luojinqq** [rancher/rancher#8385]
**Rancher Versions:**
Server: v1.5.3
healthcheck: v0.2.3
ipsec:  v0.9.4
network-services:  v0.5.3
scheduler: v0.7.5

**Docker Version:**
 v 1.13.1
**OS and where are the hosts located? (cloud, bare metal, etc):**
centos 7.2
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher, external DB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
cattle
**Steps to Reproduce:**
when a container is restart  , the dns link  still point the old ip address
when a container is stop, the ip still can ping .

**Results:** 
the front nginx can't find the backend service is rebuild .still access the old ip addreess.
the issues is sometime happend.

**Comment by niusmallnan** [comment]
@luojinqq 

It may cause by https://github.com/rancher/rancher/issues/8206 .
Pls update and if you still have this problem, just let me know.

**Comment by leodotcloud** [comment]
@luojinqq Please create a new issue if you are still having problems.
