### ISSUE TITLE
Problem with clone catalog

### ISSUE THREAD

**Issue by divo1** [rancher/rancher#8387]
**Rancher Versions:**
Server: 1.5.1
healthcheck: rancher/healthcheck:v0.2.3
ipsec: rancher/net:v0.9.4
network-services: rancher/network-manager:v0.4.8
scheduler: rancher/scheduler:v0.7.4

**Docker Version:**
Docker version 17.03.0-ce, build 60ccb22

**OS and where are the hosts located? (cloud, bare metal, etc):**
Private dedicated server

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node, internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
I restart docker server, reboot host. Few times. After this I was try to download my templates. Don't work. I getting errors:
time="2017-04-01T15:01:28Z" level=error msg="Failed to update existing repo cache: exit status 128"

When I go to catalog/community and click to refresh. It refreshing some time, but after that time icon change to triangle. I get this:
time="2017-04-01T14:57:02Z" level=error msg="Failed to update existing repo cache: exit status 128"
time="2017-04-01T14:57:04Z" level=error msg="Failed to update existing repo cache: exit status 128"
time="2017-04-01T14:57:13Z" level=error msg="Failed to update existing repo cache: exit status 128"
time="2017-04-01T14:57:22Z" level=error msg="Failed to update existing repo cache: exit status 128"
time="2017-04-01T14:57:24Z" level=error msg="Failed to update existing repo cache: exit status 128"
time="2017-04-01T14:57:35Z" level=error msg="Failed to update existing repo cache: exit status 128"
time="2017-04-01T14:57:43Z" level=error msg="Failed to update existing repo cache: exit status 128"
time="2017-04-01T14:57:44Z" level=error msg="Failed to update existing repo cache: exit status 128"
time="2017-04-01T14:57:55Z" level=error msg="Failed to update existing repo cache: exit status 128"
time="2017-04-01T14:58:03Z" level=error msg="Failed to update existing repo cache: exit status 128"
time="2017-04-01T14:58:16Z" level=error msg="Failed to update existing repo cache: exit status 128"
time="2017-04-01T14:58:23Z" level=error msg="Failed to update existing repo cache: exit status 128"
time="2017-04-01T14:58:38Z" level=error msg="Failed to update existing repo cache: exit status 128"
time="2017-04-01T14:58:44Z" level=error msg="Failed to update existing repo cache: exit status 128"
time="2017-04-01T14:58:58Z" level=error msg="Failed to update existing repo cache: exit status 128"
time="2017-04-01T14:59:05Z" level=error msg="Failed to update existing repo cache: exit status 128"
time="2017-04-01T14:59:18Z" level=error msg="Failed to update existing repo cache: exit status 128"
time="2017-04-01T14:59:25Z" level=error msg="Failed to update existing repo cache: exit status 128"
time="2017-04-01T14:59:40Z" level=error msg="Failed to update existing repo cache: exit status 128"
time="2017-04-01T14:59:46Z" level=error msg="Failed to update existing repo cache: exit status 128"
time="2017-04-01T15:00:00Z" level=error msg="Failed to update existing repo cache: exit status 128"
time="2017-04-01T15:00:06Z" level=error msg="Failed to update existing repo cache: exit status 128"
time="2017-04-01T15:00:09Z" level=error msg="Failed to update existing repo cache: exit status 128"
time="2017-04-01T15:00:20Z" level=error msg="Failed to update existing repo cache: exit status 128"
time="2017-04-01T15:00:26Z" level=error msg="Failed to update existing repo cache: exit status 128"
time="2017-04-01T15:00:29Z" level=error msg="Failed to update existing repo cache: exit status 128"
time="2017-04-01T15:00:42Z" level=error msg="Failed to update existing repo cache: exit status 128"
time="2017-04-01T15:00:47Z" level=error msg="Failed to update existing repo cache: exit status 128"
time="2017-04-01T15:00:49Z" level=error msg="Failed to update existing repo cache: exit status 128"

Even when I don't refresh. Of course when I changeing my private templates nothing happen.

I try to git pull in /var/lib/cattle/cache/global/{id}/ but get this:
fatal: unable to access 'https://github.com/my-public-repo/': Could not resolve host: github.com

ping google.pl not working. Of course in docker rancher-server.

Someone can help?

**Comment by rammaram06** [comment]
I'm getting similar error, I don't see any catalogs on dashboard..I tried adding internal git repos but it is still not working. 

I'm using Rancher: 1.5.3-try2 version. I'm seeing below errors in my log file.

I'm using rancher server built on top of redhat-7 base image.

```
2017-04-05 20:13:20,653 ERROR [:] [] [] [] [ecutorService-1] [i.c.p.task.impl.TaskManagerImpl     ] Task [run.scheduled] failed io.cattle.platform.lock.exception.FailedToAcquireLockException: Failed to acquire lock [SCHEDULED.UPGRADE]
	at io.cattle.platform.lock.provider.impl.StandardLock.lock(StandardLock.java:56) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$1.withLock(AbstractLockManagerImpl.java:17) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:30) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.systemstack.service.UpgradeManager.run(UpgradeManager.java:112) ~[cattle-system-stack-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.systemstack.task.RunScheduledTask.run(RunScheduledTask.java:23) ~[cattle-system-stack-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.task.impl.TaskManagerImpl$1.doRun(TaskManagerImpl.java:100) ~[cattle-framework-system-task-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:15) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_121]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_121]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_121]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
time="2017-04-05T20:13:20Z" level=error msg="Failed to update existing repo cache: exit status 129" 
time="2017-04-05T20:13:21Z" level=error msg="Failed to update existing repo cache: exit status 129" 
time="2017-04-05T20:13:21Z" level=error msg="Failed to update existing repo cache: exit status 129" 
time="2017-04-05T20:13:22Z" level=error msg="Failed to update existing repo cache: exit status 129" 
time="2017-04-05T20:13:23Z" level=error msg="Failed to update existing repo cache: exit status 129" 
time="2017-04-05T20:13:23Z" level=error msg="Failed to update existing repo cache: exit status 129" 
time="2017-04-05T20:13:24Z" level=error msg="Failed to update existing repo cache: exit status 129" 
time="2017-04-05T20:13:25Z" level=error msg="Failed to update existing repo cache: exit status 129" 
time="2017-04-05T20:13:25Z" level=error msg="Failed to update existing repo cache: exit status 129" 
time="2017-04-05T20:13:26Z" level=error msg="Failed to update existing repo cache: exit status 129" 
time="2017-04-05T20:13:27Z" level=error msg="Failed to update existing repo cache: exit status 129" 
time="2017-04-05T20:13:27Z" level=error msg="Failed to update existing repo cache: exit status 129" 
time="2017-04-05T20:13:28Z" level=error msg="Failed to update existing repo cache: exit status 129" 
time="2017-04-05T20:13:29Z" level=error msg="Failed to update existing repo cache: exit status 129" 
time="2017-04-05T20:13:29Z" level=error msg="Failed to update existing repo cache: exit status 129" 
time="2017-04-05T20:13:30Z" level=error msg="Failed to update existing repo cache: exit status 129" 
time="2017-04-05T20:13:31Z" level=error msg="Failed to update existing repo cache: exit status 129" 
time="2017-04-05T20:13:31Z" level=error msg="Failed to update existing repo cache: exit status 129"
```

This is My Dockerfile 

> https://gist.github.com/rammaram06/2e9e589d2ffc53a34ee6a80015effcd5

**Comment by rammaram06** [comment]
### contents of /var/lib/cattle from official rancher server image
![image](https://cloud.githubusercontent.com/assets/8261270/24726290/debe4384-1a1f-11e7-909b-308ff20991d0.png)

### contents of /var/lib/cattle from image built on redhat 7
![image](https://cloud.githubusercontent.com/assets/8261270/24726329/0f7bcb0e-1a20-11e7-854d-357c83549602.png)

* local.db file is missing on the redhat Image I built, could you pls let me know what I'm missing in my Dockerfile

**Comment by divo1** [comment]
`
root@02d7ffe10735:/# ls -la /var/lib/cattle
total 5156
drwxr-xr-x  4 root root    4096 Apr  4 22:24 .
drwxr-xr-x 36 root root    4096 Mar 24 16:35 ..
drwxr-xr-x  3 root root    4096 Mar 24 16:37 cache
-rw-r--r--  1 root root      36 Apr  4 22:23 cluster-id
-rw-r--r--  1 root root     105 Apr  4 22:22 keys.properties
-rw-r--r--  1 root root 5246976 Mar 24 16:37 local.db
drwxr-xr-x  2 root root    4096 Apr  5 00:00 logs
-rw-r--r--  1 root root       0 Apr  4 22:23 master.conf
-rw-r--r--  1 root root      32 Apr  4 22:24 rancher
-rw-r--r--  1 root root     350 Apr  4 22:24 repo.json

`

Here i have local.db. I remove all images and containers and still not working. Before I was using 1.2 rancher and all was fine. Maybe it crash when I upgrade?

**Comment by mcanevet** [comment]
Same problem as #8372 maybe?

**Comment by divo1** [comment]
Thanks for comment. I will check database. I have different errors but maybe it will help :) Thanks for advice.

**Comment by steve-todorov** [comment]
Having the same problem. Everything else seems to be working just fine, but the custom catalogue is unreachable. The log pretty much shows the same thing.

**Comment by steve-todorov** [comment]
I managed to resolve the issue. The git repository we were storing our catalog was private. For some reason, though, the private key installed on the rancher server (in `./ssh/*`) was not working. In case somebody else is having similar issues - try fixing your key.

**Comment by rammaram06** [comment]
I was able to solve my issue..redhat 7 had old version of git and it caused the issue. After upgrading it, everything working well.

**Comment by panho66** [comment]
@rammaram06  what version of Redhat and git version that fixed this problem ?

**Comment by superseb** [comment]
Please reply if you still run into anything.

**Comment by cthiebault** [comment]
In case other people hits this problem:
I also had this error and our problem was because of an existing `.git/index.lock` in cached repo.
So in our Rancher container, we looked for our custom catalog repo in `/var/lib/cattle/cache/global/`. 
`git pull` gave us following error:
```
fatal: Unable to create '/var/lib/cattle/cache/global/c55dba93ce64e96ccc91a3c81ff18c39/.git/index.lock': File exists.

If no other git process is currently running, this probably means a
git process crashed in this repository earlier. Make sure no other git
process is running and remove the file manually to continue.
```
We just deleted this `.git/index.lock` and everything went fine :-)
