### ISSUE TITLE
Getting 401 unauthorized when contacting k8s api after etcd restore

### ISSUE THREAD

**Issue by ryanwalls** [rancher/rancher#8388]
**Rancher Versions:**
Server: 1.5.3
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable): rancher/k8s:v1.5.4-rancher1-3

**Docker Version:**
1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu on AWS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node with external rds

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
Setup a separated resilient plane k8s setup with 3 etcd servers, 2 orchestration, and at least 1 compute server.  Restore from an etcd backup.

**Results:** 
Getting this in one of our DaemonSet's after the restore was complete: 

```
Invalid Kubernetes API v1 endpoint https://10.43.0.1:443/api: 401 Unauthorized
```

Also, k8s dashboard doesn't work.  And kube-state-metrics is also crashing with an authentication error:
```
Failed to create client: ERROR communicating with apiserver: the server has asked for the client to provide credentials
```

![image](https://cloud.githubusercontent.com/assets/842653/24583278/e931e330-1712-11e7-8080-5dea6c3f5549.png)

Ironically, rest of pods start fine, but they also aren't trying to communicate with API server.  I imagine any pod that wants to talk to API server would have similar problems.

API prints over and over the following error:
```
4/1/2017 8:36:48 PME0402 00:36:48.463960       1 handlers.go:58] Unable to authenticate the request due to an error: crypto/rsa: verification error
4/1/2017 8:36:48 PME0402 00:36:48.464327       1 handlers.go:58] Unable to authenticate the request due to an error: crypto/rsa: verification error
4/1/2017 8:36:48 PME0402 00:36:48.464562       1 handlers.go:58] Unable to authenticate the request due to an error: crypto/rsa: verification error
4/1/2017 8:36:48 PME0402 00:36:48.688907       1 handlers.go:58] Unable to authenticate the request due to an error: crypto/rsa: verification error
4/1/2017 8:36:48 PME0402 00:36:48.710669       1 handlers.go:58] Unable to authenticate the request due to an error: crypto/rsa: verification error
4/1/2017 8:36:48 PME0402 00:36:48.710690       1 handlers.go:58] Unable to authenticate the request due to an error: crypto/rsa: verification error
4/1/2017 8:36:48 PME0402 00:36:48.721174       1 handlers.go:58] Unable to authenticate the request due to an error: crypto/rsa: verification error
4/1/2017 8:36:48 PME0402 00:36:48.721187       1 handlers.go:58] Unable to authenticate the request due to an error: crypto/rsa: verification error
```

**Comment by ryanwalls** [comment]
Figured out the problem.  The tokens stored as Secrets were no longer valid for some reason after the restore.

To fix the issue I had to delete all the previous tokens:
```
NAMESPACE     NAME                            TYPE                                  DATA      AGE
default       3dsim-rancher-pull-secret       kubernetes.io/dockerconfigjson        1         21d
default       default-token-sf2vf             kubernetes.io/service-account-token   3         1m
default       sumologic                       Opaque                                1         1h
kube-system   default-token-sg8rv             kubernetes.io/service-account-token   3         2m
kube-system   io-rancher-system-token-7c2ww   kubernetes.io/service-account-token   3         47s
```

Specifically, I had to delete the 2nd, 4th, and 5th tokens in the list above.  

Then I had to delete any pods that had mounted those tokens, so that they got the new tokens.  

I'm going to leave this issue up, because I don't see anywhere documented in the https://docs.rancher.com/rancher/v1.5/en/kubernetes/backups/#restoring-backups that we need to deal with deleting service account tokens.

**Comment by meggarr** [comment]
I ran into the exact same problem as shown in the logs. For the reproducible steps, I also restored the etcd backup from a previous env. (tore down from a falsy vxlan env.)

**Comment by meggarr** [comment]
Wondering which is the one creates the secrets and ignores the existing..

**Comment by joshwget** [comment]
When restoring, are you reusing the hosts that were running the former cluster? If so the issue might be that the `etcd` volume from the former cluster is left behind on the hosts. When the new cluster starts etcd will pick up this volume with a stale secret token.

I'm trying to determine whether a stale secret can occur from other reasons, so if anyone has information on how they hit it then it would definitely help me out.

**Comment by ryanwalls** [comment]
@joshwget My situation.  I had environment A running kubernetes but not in separated planes.  I backed up environment A.  Then I spun up environment B with separated planes (different hosts).  I followed the restore procedure.  Tokens were stale.  Hope that helps!

**Comment by joshwget** [comment]
Yeah, that's a different scenario than I was expecting. Certainly helpful, thanks @ryanwalls.

**Comment by meggarr** [comment]
@joshwget Though I reuse the host, I did below cleanup before run the rancher agent to register
```
docker rm -f `docker ps -aq`
docker volume rm `docker volume ls -q`
umount /var/lib/rancher/volumes
rm -rf /var/lib/rancher/
systemctl restart docker

mkdir -p /var/lib/rancher/etc/ssl
mv /my/cacert.pem /var/lib/rancher/etc/ssl/ca.crt

sleep 1
reboot # for clean iptables.
```
So I think it is not a stale `etcd` volume in my case, and again, I restore the backup after the host is registered in Rancher - just same as it described in the document.

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.

**Comment by matthax** [comment]
Hey @loganhz , I'm still having the same problem in Rancher 2.1.1 - is there any way we could get this retagged and reopened?

**Comment by superseb** [comment]
@matthax This issue was filed on Rancher v1.5.3 and has no relation to v2.x. Please file a new issue with all details requested in the issue template so we can take a look.
