### ISSUE TITLE
Hosts UI loads slowly with many containers

### ISSUE THREAD

**Issue by sebgie** [rancher/rancher#8393]
**Rancher Versions:**
Server: v1.5.3
healthcheck: v0.2.3
ipsec: n/a
network-services: n/a
scheduler: v0.7.5
kubernetes (if applicable):

**Docker Version:**

1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):**

Ubuntu 14.04/DigitalOcean

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

single node, external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

Cattle

**Steps to Reproduce:**

In an environment with many containers (> 1000) the hosts screen loads quite slow and becomes more or less unusable when going beyond 2000 containers.

Steps to reproduce:
- Add 1.000 containers
- Navigate to "Infrastructure" - "Hosts
- loading takes about 10 seconds
- use the dropdown on one of the services to select "Edit"
- loading takes about 10 seconds
- press cancel
- loading takes about 10 seconds

According to Chrome developer tools this has nothing to do with network load but with script operations on the client.

![rancher_und_new_issue_ _rancher_rancher](https://cloud.githubusercontent.com/assets/539213/24608528/2c999d56-1877-11e7-87ff-2a81546b858c.png)

**Optional:** 

I understand that handling this amount of containers is probably out of scope. An alternate  solution for this problem would be to be able to remove stacks from the hosts view to make this page useable with many containers.

**Comment by vincent99** [comment]
2.0 has a host view where containers are not shown unless expanded (and paginated)
