### ISSUE TITLE
How to add a customized answer to Rancher-dns

### ISSUE THREAD

**Issue by qiuwei** [rancher/rancher#8394]
I would like to add a customized answer for a domain name  to Rancher-dns 's answer.yml

Is there any easy way to achieve this?

**Comment by joshwget** [comment]
[External services](http://docs.rancher.com/rancher/v1.5/en/cattle/adding-external-services/) might be what you're looking for.

**Comment by qiuwei** [comment]
@joshwget  Could you provide some more instructions on how to do this?
I checked the documentation but couldn't figure out.

To illustrate my problem, I get a bunch of containers all need to call services at hosname.example.org (which are hard-coded in the source code)

Now I am developing services at hostname.example.org, and get them deployed somewhere else(say 10.10.10.10) for test purpose.
I want to get hostname.example.org resolved to 10.10.10.10 for all of the containers.

How can I achieve this using external services?

**Comment by niusmallnan** [comment]
@qiuwei 

![image](https://cloud.githubusercontent.com/assets/998984/24745512/8d684c86-1ae8-11e7-8ed7-b689078d9cab.png)

![image](https://cloud.githubusercontent.com/assets/998984/24745528/97d456b0-1ae8-11e7-9c80-9bfcf2bf72c1.png)

**Comment by qiuwei** [comment]
@niusmallnan , I know how to add external service, but it doesn't solve my problem.

I cannot add "hostname.example.org" as the name of the external service. Rancher complains that there are invalid characters.

Thanks anyway!

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
