### ISSUE TITLE
Internal DNS does not resolve correctly

### ISSUE THREAD

**Issue by PCXDME** [rancher/rancher#8395]
**Rancher Versions:**
Server: v1.5.1
healthcheck: v0.2.3
ipsec: IDK
network-services: v0.5.3
scheduler: v0.7.5
kubernetes (if applicable):

**Docker Version:**
1.12.6
**OS and where are the hosts located? (cloud, bare metal, etc):**
Rancher OS, Bare metal
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
1. I have db and redis service.
2. I have a service linked to db and redis service in different stack.
3. Execute "dig db" or "dig redis"

**Results:** 
This happens sometimes.
```
; <<>> DiG 9.9.5-9+deb8u10-Debian <<>> db
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 63001
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;db.                            IN      A

;; ANSWER SECTION:
db.                     600     IN      A       10.42.7.55

;; Query time: 0 msec
;; SERVER: 169.254.169.250#53(169.254.169.250)
;; WHEN: Mon Apr 03 09:13:44 UTC 2017
;; MSG SIZE  rcvd: 36
```
But sometimes, the result is
```
; <<>> DiG 9.9.5-9+deb8u10-Debian <<>> db
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 45054
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;db.                            IN      A

;; AUTHORITY SECTION:
.                       18725   IN      SOA     a.root-servers.net. nstld.verisi
gn-grs.com. 2017040200 1800 900 604800 86400

;; Query time: 0 msec
;; SERVER: 169.254.169.250#53(169.254.169.250)
;; WHEN: Mon Apr 03 08:55:40 UTC 2017
;; MSG SIZE  rcvd: 106
```
Somtimes redis and db can't be resolved, sometimes redis can be resolved but db can't, sometimes both can be resolved.
Restarting the main service does not fix the problem. After waiting for a while (more than 3 minutes), "dig" can then be run successfully.
"ping" always works for both db and redis.

**while "dig db" does not work**
- "dig db.rancher.internal" works
- "dig MariaDB.MySQL.rancher.internal" works

**Notes:**
I usually have problem about Internal DNS (Unknown host db in Java) sometimes when restarting service but I am not sure why it only fails after restarting. So investigate that dig does not work properly. I think it only fails after restarting because there are some kind of dns cache in the container so if it success resolving the first time, it will be able to resolve from cache later on. However, if it does not resolve the first time, it will cause bugs in my service.
I have no issue with very old version of rancher(can't remember which version).
This is from fresh install of Rancher OS and Rancher.
External domains have no problem.

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
