### ISSUE TITLE
AWS ELB Classic External LB Service Repeated Fails With Go Stack Trace

### ISSUE THREAD

**Issue by loyal** [rancher/rancher#8396]
Attempting to create AWS Classic ELB with Rancher 

With this Service:
rancher/external-lb:v0.2.1
Entrypoint:  None
Command:  -provider=elbv1

On this version: Rancher: v1.5.3 HA

The container log repeatedly generates this stacktrace, when:
- The label io.rancher.service.external_lb.endpoint is set on one other service.

This error stops, when I unset the label, but that means this service isn't adding any AWS EC2 instances to the AWS Classic Load Balancer.

I tried this combinations of setting or not setting the option environments variables to the Rancher AWS ELB Classic External LB Service.  I followed the steps discussed here: http://rancher.com/inside-the-external-elb-catalog-template/.  I did see at one point the message in my service with the label state "Updating LB config"; however, the instances were not getting added in the Load Balance in the AWS Console.

I also looked at the Forum for discussion about this, and found this: https://forums.rancher.com/t/load-balancing-with-elb/2839.

Apologies offered in advanced if this fix is documented somewhere and I have missed it!

Here is the stack track with my information redacted:
4/1/2017 12:45:46 PMgoroutine 1 [running]:
4/1/2017 12:45:46 PMpanic(0xb6b2c0, 0xc820012080)
4/1/2017 12:45:46 PM	/usr/local/go/src/runtime/panic.go:481 +0x3e6
4/1/2017 12:45:46 PMgithub.com/rancher/external-lb/providers/elbv1/elbv1svc.(*ELBClassicService).LookupInstancesByFilter(0xc8203acb40, 0xc820069808, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
4/1/2017 12:45:46 PM	/go/src/github.com/rancher/external-lb/providers/elbv1/elbv1svc/ec2.go:82 +0x78c
4/1/2017 12:45:46 PMgithub.com/rancher/external-lb/providers/elbv1/elbv1svc.(*ELBClassicService).GetInstancesByID(0xc8203acb40, 0xc8202ce300, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0)
4/1/2017 12:45:46 PM	/go/src/github.com/rancher/external-lb/providers/elbv1/elbv1svc/ec2.go:31 +0xf8
4/1/2017 12:45:46 PMgithub.com/rancher/external-lb/providers/elbv1.(*AWSELBv1Provider).GetLBConfigs(0xc8200653e0, 0x0, 0x0, 0x0, 0x0, 0x0)
4/1/2017 12:45:46 PM	/go/src/github.com/rancher/external-lb/providers/elbv1/aws_elbv1.go:152 +0xe0b
4/1/2017 12:45:46 PMmain.getProviderLBConfigs(0x9fbec0, 0x0, 0x0)
4/1/2017 12:45:46 PM	/go/src/github.com/rancher/external-lb/external-lb.go:37 +0x60
4/1/2017 12:45:46 PMmain.UpdateProviderLBConfigs(0xc8203719b0, 0xc8203719b0, 0x0, 0x0)
4/1/2017 12:45:46 PM	/go/src/github.com/rancher/external-lb/external-lb.go:19 +0x39
4/1/2017 12:45:46 PMmain.main()
4/1/2017 12:45:46 PM	/go/src/github.com/rancher/external-lb/main.go:126 +0x50f
4/1/2017 12:45:49 PMtime="2017-04-01T19:45:49Z" level=info msg="Starting Rancher External LoadBalancer service"
4/1/2017 12:45:49 PMtime="2017-04-01T19:45:49Z" level=info msg="Configured AWS ELB Classic provider in region XX-XXXX-X and VPC XXX-XXXXXXXX"
4/1/2017 12:45:49 PMtime="2017-04-01T19:45:49Z" level=info msg="LB_TARGET_RANCHER_SUFFIX is not set, using default suffix 'rancher.internal'"
4/1/2017 12:45:49 PMtime="2017-04-01T19:45:49Z" level=info msg="Healthcheck handler is listening on :1000"
4/1/2017 12:45:50 PMpanic: runtime error: invalid memory address or nil pointer dereference
4/1/2017 12:45:50 PM[signal 0xb code=0x1 addr=0x0 pc=0x6e00bc]

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.5.3` Cattle: `v0.177.10` UI: `v1.5.8` |
|Access|`Disabled`|
|Orchestration|`Cattle`|
|Route|`authenticated.project.help`|

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
