### ISSUE TITLE
Catalog API - Fetch by catalog name no longer working

### ISSUE THREAD

**Issue by mattdodge** [rancher/rancher#8399]
**Rancher Versions:**
Server: 1.5.3

In version 1.4.1 of Rancher server the following API endpoint would return all of the catalog templates from a given catalog (`catalog_name`).

```
GET /v1-catalog/catalogs/catalog_name/templates
```

In Rancher 1.5.3 that endpoint returns a 404. Is there another endpoint where we can fetch the templates from a specific catalog?

**Comment by joshwget** [comment]
You can use `GET /v1-catalog/templates?catalog=catalog_name` in the new catalog service that's used starting with 1.5.x.

**Comment by andrewf78** [comment]
Can confirm the above path works as expected. Thanks @joshwget

**Comment by mattdodge** [comment]
Ah, thanks. I had actually tried `name=catalog_name` but didn't think to try catalog
