### ISSUE TITLE
CLI - restricted user account types not warned about no perms to view service logs

### ISSUE THREAD

**Issue by cmosetick** [rancher/rancher#8400]
**Rancher Versions:**
Server: 1.5.3

**CLI Version:**
Rancher CLI version is unknown, as this user is on Mac OS,  
and rancher returns `dev` for `rancher --version` on mac OS.
`brew info` indicates that we are using v0.5.0

**Steps to Reproduce:**
* Create a user account with local auth.
* Add user to an environment, by setting the environment as a "Restricted" user type.
* Run `rancher logs stack-name/service-name`

**Results:**
The logs for the specified service are not returned, nor is a warning message returned that a user does not have permission to access the logs via the Rancher CLI because they are a "Restricted" user. Note that Restricted users can see the logs through the Rancher web-ui, so this behavior is puzzling to them.

**RFE**
A simple warning message should be returned through the CLI.

**Comment by vincent99** [comment]
#8020
