### ISSUE TITLE
Health check instance stuck in "Initilaizing" state 

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#8403]
Rancher Versions: Build from wagyu

Steps to reproduce the problem:
Add 2 hosts to "Default" environment.
Health check instance stuck in "Initializing" state on 1 of the host and there is no health check instance that gets created on the  other host

```
mysql> select id,name,state,created,removed,health_state from instance where name like "health%";
+----+---------------------------+---------+---------------------+---------+--------------+
| id | name                      | state   | created             | removed | health_state |
+----+---------------------------+---------+---------------------+---------+--------------+
| 12 | healthcheck-healthcheck-1 | running | 2017-04-03 22:42:23 | NULL    | initializing |
+----+---------------------------+---------+---------------------+---------+--------------+
1 row in set (0.00 sec)

mysql> 
```

Service activation fails with error - ```Failed to acquire lock [DEPLOYMENT.UNIT.5])```

**Comment by deniseschannon** [comment]
Can you re-test with the new container refactoring?

**Comment by sangeethah** [comment]
Tested with rancher-server builds from master (07/07) with 3 hosts.
Health check instances get deployed successfully on all hosts and get to "healthy" state.
