### ISSUE TITLE
docker live-restore

### ISSUE THREAD

**Issue by gyalai** [rancher/rancher#8404]
**Rancher Versions:**
Server: v1.5.1

**Docker Version:** 1.13.1

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04 Bare Metal

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
I wanted to run the docker daemon with the live-restore functionality (https://docs.docker.com/engine/admin/live-restore/).  When the daemon restarted none of the container gets restarted as it expected. 

**Results:** 
The rancher-agent container lost its connection with the docker daemon socket and after that it is not able to do anything on the host. After the rancher-agent gets restarted the connection with the docker daemon restored but it still can not create new containers but can stop running ones.

**Comment by balleddog** [comment]
Hitting the same issue here

**Comment by marcbachmann** [comment]
That issue got closed without any useful comment https://github.com/rancher/rancher/issues/9072, so it doesn't look like they won't support it in the near future.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
