### ISSUE TITLE
Port mapping doesn't work on any containers started by Rrancher (incl. ipsec, loadbalancer, etc)

### ISSUE THREAD

**Issue by teebeey** [rancher/rancher#8405]
**Rancher Versions:**
Server: 1.5.3
healthcheck: 0.2.3
ipsec: 0.9.4
network-services: 0.5.3
scheduler: 0.7.5
kubernetes (if applicable): -
rancher/agent: 1.2.1

**Docker Version:**
Server Version: 1.12.6
Storage Driver: btrfs
 Build Version: Btrfs v3.18.2+20150430
 Library Version: 101
Plugins:
 Volume: local
 Network: bridge null overlay host

**OS and where are the hosts located? (cloud, bare metal, etc):**
VM on OTC/Openstack
Kernel Version: 3.12.69-60.64.32-default
Operating System: SUSE Linux Enterprise Server 12 SP1
Architecture: x86_64

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher, internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Create VM from customized (MCOS) SLES 12 SP1 Image
Install Docker 1.12.6-90.1 from a mirror of original SUSE repository.
Start Rancher server and add at least one agent.
Start anything on the Rancher website, which requires port-mapping (ipsec network, load balancer or a custom container).

**Results:** 
Container starts with no errors.
Rancher sais the port mapping is there.
Docker and iptables say, no mapping present for the container.

**Other useful info:**
Same works with older Rancher/server (1.1.4) and rancher/agent(1.0.2) same Kernel version, same Docker version, same OS image.
Containers started with docker-compose have functional port-mapping.

**Comment by vincent99** [comment]
Newer versions of Rancher use CNI for networking, and map ports using iptables.  The docker daemon is given `--net=none` so the ports do not show up in `docker ps`, but this doesn't indicate that something is wrong.  The easiest way to see them is `iptables-save`.

**Comment by teebeey** [comment]
Yes, you're right, thank you!
