### ISSUE TITLE
Can't reach internal host from some other hosts

### ISSUE THREAD

**Issue by XciD** [rancher/rancher#8406]
**Rancher Versions:**
Server: 1.5.3
healthcheck: 0.2.3
ipsec: 0.9.4
network-services: 0.8.11/0.5.3
scheduler: 0.7.5

**Docker Version:**
1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):**
custom provider

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA Rancher (3 nodes)+ External DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

I don't know where to start to reproduce the bug. I've a cluster with 100 machines registred.
I've created a HDFS Cluster stack and another service depending on hdfs (named hdfs)
All my infrastructure stack are green.

On various host, I can't reach HDFS Cluster by internal IP.

When I try to ping the hdfs host 
```
ping hdfs
PING hdfs.rancher.internal (10.42.60.109) 56(84) bytes of data.
```
With no end...

But if I curl the public address, I can reach the port:
```
curl public_ip:50070
<some html>
```

How can I debug this ?

**Comment by aemneina** [comment]
@XciD are you able to ping other ipsec containers? The output from this should be helpful

```
for i in `curl -s rancher-metadata/latest/self/service/containers/` ; do id=$(echo $i| cut -f1 -d=) ; name=$(echo $i| cut -f2 -d=) ; echo " ---- $name --------" ; ping -c2 `curl -s curl rancher-metadata/latest/self/service/containers/$id/primary_ip` ; done
```

**Comment by XciD** [comment]
Fixed by removing and readding the host.
Thanks for the command, will try this when reappear
