### ISSUE TITLE
Feature Request: Permissions for stacks

### ISSUE THREAD

**Issue by wzrdtales** [rancher/rancher#8407]
It would be great to see permissions for a single stack to be added to limit users (or groups) to just view, update and also access (logs, shell) them.

The use case for this is for example limitations resulting from the data protection laws and requirements if you want to comply to them. While you can mange this currently, kind of, via different environments, it doesn't completely solves the issue. Especially as you can't put a single server into two environments. In fact there are services that share the same environment, but are limited in the way they are allowed to communicate with each other, which would also need to be applied to the user access level as well.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
