### ISSUE TITLE
Single point of failure for kube-dns addon

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#8409]
**Rancher Versions:**
Server: v1.5.4
**Docker Version:**
v1.12.6
**OS and where are the hosts located? (cloud, bare metal, etc):**
Cloud
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes 1.5.4
**Steps to Reproduce:**

- Install kubernetes stack.
- Run few pods.
- stop the host that contain kube-dns

**Results:** 

The pods will fail to resolve any queries until the kubedns is restored, the kubedns took about 5 minutes and 49 seconds to be rescheduled on another host.

the kubernetes stack should has a solution to have multiple kube-dns pods.

**Comment by sangeethah** [comment]
When this issue gets addressed https://github.com/rancher/rancher/issues/8423 ,  recreating kubedns instance could happen faster than the current 5 minutes it takes .
