### ISSUE TITLE
Services not failing over when all hosts have been disconnected

### ISSUE THREAD

**Issue by chrisurwin** [rancher/rancher#8416]
**Rancher Versions:**
Server: 1.5.3
healthcheck: v0.2.3
ipsec:
network-services: v0.5.3
scheduler: 0.7.5
kubernetes (if applicable):

**Docker Version:**
1.12.3
**OS and where are the hosts located? (cloud, bare metal, etc):**
AWS Rancher OS
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
Stand up and environment add 3 hosts and add some services with healthcheck. destroy all of the hosts and wait for them the go into disconnected state. Add in 3 more hosts and these should become active.
**Expected Results:** 
Services should fail health check and fail over onto the new hosts
**Actual Result**
The services all stay green on the disconnected hosts and never fail over

**Comment by sangeethah** [comment]
@chrisurwin , This is similar to the issue to tracked in   https://github.com/rancher/rancher/issues/3961.
Once there is atleast 1 container running on the newly added host , health-check enabled istances should be able to failover to this newly added host.
Can you check , if adding new instances to the host , results in health check enabled instances to failover?

**Comment by sangeethah** [comment]
Tested with v1.6.0-rc3
Setup with 3 custom Rancher os hosts from AWS.
Deploy few services that are health check enabled.
Destroy all of the 3 hosts and wait for them the go into disconnected state.
All health check enabled instances continue to be shown as being in "running" state.

Add 3 new hosts to the setup.
As soon as health check containers start successfully on the new hosts , all health check enabled instances get recreated successfully on the new hosts.
