### ISSUE TITLE
rancher env ls - no environment visible

### ISSUE THREAD

**Issue by VAdamec** [rancher/rancher#8417]
**Rancher Versions:**
Server: 1.5.3
CLI: v0.5.1

**Docker Version:**
13.1

**OS and where are the hosts located? (cloud, bare metal, etc):**
CentOS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher, ext DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
1. Create account API key (admin role assigned)
2. Export keys and 

```
export RANCHER_URL=https://<URL>
export RANCHER_ACCESS_KEY=XXXXX
export RANCHER_SECRET_KEY=XXXXXXXXXXXXXXXXXXXX
```

3. List envs

➜  ~ rancher env ls
ID        NAME      ORCHESTRATION   STATE     CREATED

**Results:** 
 no environments visible (there are five of them, all catles)

commands like ```rancher --env xxx ps``` works without any problems.

**Comment by superseb** [comment]
Thanks for reporting, is this something still seen on v1.6.10?

**Comment by superseb** [comment]
Please report back so we can take a look.
