### ISSUE TITLE
Host UI Issues

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#8421]
**Rancher Versions:** 4/5

**Issues:** 

- [x] Host text disappears when I move mouse over Apps
![image](https://cloud.githubusercontent.com/assets/11514927/24722153/8549889a-19f7-11e7-9cf7-e2aeb826e29c.png)

- [x] If last host has a label, part of the bottom of the border is missing
![image](https://cloud.githubusercontent.com/assets/11514927/24722203/b3d72262-19f7-11e7-80ce-93d0790ea4b1.png)

- [x] There is border around the upper part of the host pod if there are labels, but no border if there isn't.  Maybe we should always have a border?  That way the checkbox and expand arrow look centered on something?
![image](https://cloud.githubusercontent.com/assets/11514927/24021753/af9fe384-0a5f-11e7-9dc2-611eeaa2ba9c.png)

- [x] In group and list view, the hosts are lining up on right instead of left side when there are too many to fit onto one row
![image](https://cloud.githubusercontent.com/assets/11514927/24023484/dd4ab39a-0a69-11e7-95d3-6b4f88328bdd.png)

- [x] Group and list view when you have multiple, the second one on bottom has lots of white space between it and the host above it?
![image](https://cloud.githubusercontent.com/assets/11514927/24024023/6e16684e-0a6d-11e7-8074-3956c3aa3e72.png)

- [x] Hover over containers in hosts page needs to be fixed
![image](https://cloud.githubusercontent.com/assets/11514927/24722567/0b3762f0-19f9-11e7-9c95-56d734818544.png)

- [x] X for search should go inside the search field and the field should stay same size
![image](https://cloud.githubusercontent.com/assets/11514927/24722619/477cf392-19f9-11e7-96de-d8f1675ed4af.png)

- [x] If I put something in the search box, the amount of container goes from 0 to a bold 0/0
![image](https://cloud.githubusercontent.com/assets/11514927/24879382/90a3647a-1deb-11e7-9a5d-b1996d8ac691.png)

- [x] Icon view, the Container menu on host page, there is a while outline around menu button and it's smaller then the container text info box next to it.
![image](https://cloud.githubusercontent.com/assets/11514927/24722700/99bf396c-19f9-11e7-9f13-a6e2684c3c29.png)

- [x] Group view, clicking on menu causes border to go over IP address of container
![image](https://cloud.githubusercontent.com/assets/11514927/24722752/cdf17cd6-19f9-11e7-8f95-d160e2ce4d89.png)

**Comment by lvuch** [comment]
https://github.com/rancher/ui/pull/1139#event-1049054043

**Comment by tfiduccia** [comment]
Version 4-24
Verified fixed
