### ISSUE TITLE
Pods are evicted to another host after 5 minutes when host fails

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#8423]
**Rancher Versions:**
Server: v1.5.3

kubernetes (if applicable): 1.5.4

**Steps to Reproduce:**
- Create a setup with 3 hosts
- Install kubernetes
- Create a pod on any host
- stop the host that has this pod.

**Results:** 

The pod will be evicted after 5 minutes after the host goes to reconnecting state, this is because the `kube-controller-manager` didn't start with `pod-eviction-timout` option which defaults to `5m0s`

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
