### ISSUE TITLE
API - to pull images from docker registry / kubernetes  in Rancher UI.

### ISSUE THREAD

**Issue by PoojaTakavale** [rancher/rancher#8425]
Hello,

I ma trying to find an API in github code for Rancher-Cattle.
I want the API logic where the images are pulled from the docker or kubernetes in rancher.

I want to know whether there are existing APIs which can just the pull images from one server host to other server. (From one account to rancher)?
Or is there any mediator which does the job.

Please provide me understandings where API is written for the pulling images from one account.
Authentication done to do so and login handling.

I am working on an application which demands me to pull images and push images from accounts like docker hub account.
So, I am searching for readymade APIs which does this job.
Please provide me the thread to do so.

Thank you.
Your help will be highly appreciated.

**Comment by superseb** [comment]
For Cattle I would say: 
https://github.com/rancher/cattle/blob/060bd6b0104a21ea7221ea5ad17d5696fdb26a29/code/implementation/docker/compute/src/main/java/io/cattle/platform/docker/process/instance/DockerInstancePreCreate.java#L53 and https://github.com/rancher/cattle/blob/ccb4ee49ca93ac29cd26fc204fb9e113ed024c11/code/implementation/docker/storage/src/main/java/io/cattle/platform/docker/storage/dao/impl/DockerStorageDaoImpl.java#L30.

Hope this helps!
