### ISSUE TITLE
API: Want to know when Machine are created

### ISSUE THREAD

**Issue by Ima8** [rancher/rancher#8427]
i use  "CREATE    POST: **/v2-beta/projects/${PROJECT_ID}/machines**" but that return in immediate . i wanna know when machine that ready for use.

Referenced by http://docs.rancher.com/rancher/v1.5/en/api/v2-beta/api-resources/machine/

**Comment by vincent99** [comment]
For v2/1.2+ you should create a `host` instead of a `machine`.  It still exists for backwards compatibility but machine indirectly creates a host entry, while you can just directly create one now.

All create calls are asynchronous.  You need to poll the `self` link of the returned resource and watch the `state` or `transitioning` fields to know when something is done.

**Comment by Ima8** [comment]
Thank you @vincent99 ,

I tried to change from machine to host but it **returns 422**

`{ statusCode: 422,
  headers:
   { 'content-type': 'application/json; charset=utf-8',
     date: 'Thu, 06 Apr 2017 02:21:42 GMT',
     expires: 'Thu, 01 Jan 1970 00:00:00 GMT',
     server: 'Jetty(9.2.11.v20150529)',
     'set-cookie': [ 'PL=rancher;Path=/' ],
     'x-api-account-id': '1a5',
     'x-api-client-ip': '49.231.xx.xx',
     'x-api-schemas': 'http://172.104.xx.xx:8888/v2-beta/projects/1a5/schemas',
     'x-api-user-id': '1a1',
     'x-rancher-version': 'v1.5.3',
     'content-length': '193',
     connection: 'close' } }`


And this JSON I send

`{
      digitaloceanConfig: {
        accessToken: optionsParams.accessToken,
        region: optionsParams.region || 'sgp1',
        size: optionsParams.size || '1gb',
        image: optionsParams.image || 'ubuntu-16-04-x64',
        dockerVersion: '17.03.0-ce',
        sshPort: '22',
        sshUser: 'root',
        backups: false,
        ipv6: true,
        privateNetworking: false,
      },
      name: optionsParams.nameNode,
     }`
to **/v2-beta/projects/1a5/hosts**

**Comment by Ima8** [comment]
Done . I forgot "hostname" but i don't understand what different between `hostname `and `name`

**Comment by vincent99** [comment]
`hostname` is the name you request from the provider and can be set only on create.  After create it's whatever the actual hostname the provider put on the VM says and can't be changed (it is usually a variant of the hostname you put in, with extra domains or such).

`name` can be set (on create or later) to override what is shown in the UI with a name you choose.

**Comment by Ima8** [comment]
Thank you @vincent99
