### ISSUE TITLE
INFO: difference Stack vs Service

### ISSUE THREAD

**Issue by Ima8** [rancher/rancher#8428]
What difference between Stack and Service? or can you explain with usecase? 

Thank you,

**Comment by superseb** [comment]
Hi @Ima8 , we try to keep a good source of documentation over at http://docs.rancher.com, I've linked two sections relevant for you. Please let me know if you need any more information, or if it's unclear.

Stacks (http://docs.rancher.com/rancher/v1.6/en/cattle/stacks/): A stack is a group of services. Stacks can be used to group together services that together implement an application.

Service (http://docs.rancher.com/rancher/v1.6/en/cattle/adding-services/): Cattle adopts the standard Docker Compose terminology for services and defines a basic service as one or more containers created from the same Docker image.
