### ISSUE TITLE
docker-compose mac_address field not respected

### ISSUE THREAD

**Issue by cpoole** [rancher/rancher#8429]
**Rancher Versions:**
Server: 1.4.1
healthcheck: 0.2.3
ipsec: 0.0.4
network-services: 0.0.17
scheduler: cattle 0.4.0

**Docker Version:**
1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):**
ubuntu 16.04 AWS EC2

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Rancher HA with external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle 

**Steps to Reproduce:**
set the `mac_address` field in a docker-compose.yml
run rancher-compose up

**Results:** 
notice the mac address field is ignored and the container has a randomly assigned mac address

However, if you set the label `io.rancher.container.mac_address` rancher does respect this.

I'd like to help out if possible for this 

It appears this functionality is possible in the rancher-cni-bridge according to this func
https://github.com/rancher/rancher-cni-bridge/blob/master/bridge.go#L92

And the io.rancher.container.mac_address field is respected here: 
https://github.com/rancher/cniglue/blob/master/cni.go#L73

would fixing this be as simple as adding in a statement there to to also check for the `mac_address` field in the given docker-compose?

Finally why isnt this documented? Is it officially supported or am I going to run into problems if I rely on this? If it is officially supported I'm happy to open up a pr on the docs.

**Comment by cpoole** [comment]
any comments on this one?

@leodotcloud would a PR be accepted to add a check for docker-compose `mac_address` field at https://github.com/rancher/cniglue/blob/master/cni.go#L73

**Comment by leodotcloud** [comment]
@cpoole The label `io.rancher.container.mac_address` is set to the MAC address decided by Cattle. So the CNI bridge plugin uses it to program inside the container. I think the fix should be in rancher-compose, @joshwget ???

**Comment by cpoole** [comment]
ah, so im potentially breaking cattle by hardcoding that label in my docker-compose? 

I see where cattle creates an entry to the NicTable, and I see where that nic is fetched for the container metadata. But im unclear on where cattle generates the mac address and where cattle sets the label `io.rancher.container.mac_address`

I'd assume that label gets set somewhere within cattle and that rancher-compose just passes the label to cattle if it already exists? 

This is my first deep dive into cattle

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
