### ISSUE TITLE
Token field should not be set in metadata for /self/stack/service.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#8435]
Rancher Versions: v1.5.4-rc1
Steps to reproduce the problem:
Create a service.
From within the containers of the service  , access service metadata using - http://rancher-metadata/2015-12-19/self/stack/service or http://rancher-metadata/2016-07-29/self/stack/service 

token field has data.

Expected Behavior:
token field should be empty

**Comment by ibuildthecloud** [comment]
@sangeethah I misunderstood this.  It is fine for the token to be in /self/service of any version.  It should not be in any of the /services paths.

**Comment by sangeethah** [comment]
Tokens are not set when accessing http://rancher-metadata/2015-12-19/self/stack/services/0/token  or http://rancher-metadata/2016-07-29/self/stack/services/0/token anymore.

Closing this issue.
