### ISSUE TITLE
Display catalog-service errors

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#8438]
There are a couple issues related to the fact that we have easy way to identify that a bad catalog refresh would cause your catalog not to update or why it's broken. Overall, if we had better way to show errors from catalog service, the user would have clearer understanding of why their catalog isn't pulling the correct templates.

https://github.com/rancher/rancher/issues/8019
https://github.com/rancher/rancher/issues/8031

**Comment by joshuacox** [comment]
Displaying more information in errors in general would not be a bad idea, let me include another useless error that gives me no indication of what went wrong [ ![screenshot from 2017-08-25 08-43-23](https://user-images.githubusercontent.com/6137404/29716643-b5c55fa0-8971-11e7-8f24-d5a245c27623.png)
](url)  I think this is related to some [proxy issues](https://github.com/rancher/rancher/issues/9420#issuecomment-324582808) , but nonetheless.

**Comment by amy** [comment]
Along with above tagged issues, we should also consider addressing the following:
> When parsing issues arise for `rancher-compose.yml` catalog does not show up, & we get a 200. However, server logs do show relevant error information. 
> When key files are excluded (`config.yml`, `rancher-compose.yml`, `docker-compose.yml`), we don't get an error message
> We still have this issue: https://github.com/rancher/rancher/issues/8806 
    More generally, when `git clone` fails, we get a 500 status but no UI indication of what failed. 
    However, logs will output relevant information.
> If the directory structure is wrong, the catalog will return a `200` and no errors are displayed or logged.

NOTE: `docker-compose` parsing problems are displayed after you launch the catalog so those problems are not in the scope of this issue.

**Comment by amy** [comment]
Per offline discussion, the current plan to improve error messages is as follows:

- We will add a `transition state` and `transition message` field for catalogs. These fields will be stored in the DB.
- The transition states are `yes`, `no`, `error`
- Add a refresh action to catalogs which will start the process for catalogs transitioning
  This new endpoint will return a list of catalogs along with their transition state.
- Error messages will be returned based on transition states and transition messages

Concerns to address later:
- If we fire a refresh twice, we should refuse to refresh until all catalogs are no longer refreshing. More thought is required in the case of global catalogs and users from 2 environments refreshing the same catalog.

**Comment by amy** [comment]
Issue https://github.com/rancher/rancher/issues/8806 will not be addressed in this issue. The process and solution will be tracked in issue #8806.
