### ISSUE TITLE
cattle: create container with expose port and null protocol

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#8439]
When protocol is not specified using the API, cattle should default it to "tcp", otherwise it's propagated incorrectly to metadata.

Incorrect: `0.0.0.0:3000:3000`
Correct: `0.0.0.0:4500:4500/udp`

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
