### ISSUE TITLE
Rancher load balancer 503

### ISSUE THREAD

**Issue by ed11e** [rancher/rancher#8441]
**Rancher Versions:**
Server: 1.5.3

**Docker Version:**
17.03.1-ce

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node Rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Add a load balancer to an existing rancher stack.
Target container running on port 5000 with the load balancer pointing to this port. Have tried setting the load balancer access to 5000 and 80 with the same result. 

**Results:** 
A 503 error is given when attempting to access via the load balancer. The target container can be accessed directly and is running.

**Comment by codereviewvideos** [comment]
Indeed, I am seeing the same - spent all day trying to track down what is causing this. 

My config is - based on what I've seen elsewhere - very basic. 

I have an nginx site using the stock Symfony nginx config - http://symfony.com/doc/current/setup/web_server_configuration.html#nginx

Without a load balancer, if I expose port 80 publicly, I can hit the site no problem.

I then followed numerous examples, but predominantly this one:

https://www.sakshamappinternational.com/how-to-secure-your-rancher-web-app-with-lets-encrypt-on-ubuntu-16-04/

to add in LetsEncrypt.

LetEncrypt wants to use port 80 also. I add a rule in for LetsEncrypt as described in the above link, and I can see I get a certificate issued - which as I'm using HTTP must mean that my site is available somehow on port 80 for `/.well-known/acme-challenge`

I then add another rule for port 80 to my nginx container, but this always comes back:

```
<html>
    <body>
        <h1>503 Service Unavailable</h1>
No server is available to handle this request.
    </body>
</html>
```

That, as best I can tell, is coming from the load balancer. It's hard to track down as I cant get any logs from HAProxy.

I have also tried removing the public > private port setup for the nginx container, and that doesn't make any difference. 

I am very confused - any guidance greatly appreciated. There's a strong possibility I am doing something very obviously wrong, but I can't spot it.

**Rancher Versions:**
Server: 1.5.3

**Docker Version:**
1.12.6, build 78d1802 

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node Rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Comment by ed11e** [comment]
This is similar to the issue we are having. Tried switching the primary and sidekik around but, still giving the same result.

**Comment by codereviewvideos** [comment]
Hi @ed11e 

I just had further fun with my load balanacer config this morning.

One thing that totally caught me out was that with two hosts online, the new load balancer I added was being brought up on a host with a different external IP. I used labels / scheduling to ensure the new LB was added to the expected host and that fixed this issue. I'm posting this here in the slim hope it may help you.

Chris

**Comment by ed11e** [comment]
Hi @codereviewvideos 

Thanks so much for this! This fixed my issue as well. 

I'm not really sure if this is expected behaviour or not, but it would be interesting to know more. I would also love to know what it won't work without labels! 

Thanks again!

**Comment by codereviewvideos** [comment]
I've gone with a single 'global' load balancer now, which isn't my ideal setup but it's working. I wish I could give you a better answer, but happy to have helped all the same :)

**Comment by superseb** [comment]
Closing as stale, please file a new issue if you still experience issues.
