### ISSUE TITLE
Add Docker label for the environment UUID when creating containers

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#8442]
**Rancher Versions:**
Server:
1.5.3

When we create containers we add Docker labels for the stack and service name the container belongs to.

1. There should also be a label for the environment name, ie. `io.rancher.environment.name`.
2. The label `io.rancher.container.system` should be set to false for non system containers (currently this label is not set at all for non system containers)

**Comment by StrongMonkey** [comment]
We basically only use the key `io.rancher.container.system` to identify the system container not value. The second one doesn't really apply as it would break things.

**Comment by deniseschannon** [comment]
@janeczku we will not be implementing the `io.rancher.container.system=false` on user containers, as the assumption will be if that label does not exist, it is a user container.

**Comment by cjellick** [comment]
No consensus was reached on adding this label. @vincent99's in particular had a good argument against it. The gist was that we're slowly adding every API field to metadata and every metadata field to container labels.

So, I think the solution to the underlying problem @janeczku is attempting to address is to integrate with rancher metadata.

**Comment by deniseschannon** [comment]
I believe they wanted this label for logging drivers which relay on labels and not metadata, but @janeczku could correct me.

**Comment by janeczku** [comment]
@cjellick @deniseschannon They are using the sysdig agent for shipping container metrics to sysdig cloud. The agent does not (and wont for the foreseeable future) integrate with rancher-metadata. It tags container metrics with docker labels. Without the environment label they are unable to partition container metrics by Rancher environment.

**Comment by cjellick** [comment]
Updating where this issue is:
- @vincent99 has raised concerns about adding this label because environment names can change and thus the label can become out of date
- @cloudnautique has explained that we accomplish the same end goal (environment specific dashboards in sysdig) by adding a custom tag of the env name to the sys dig agent.
  - @janeczku noted that if you are adding the sys dig agent via ros cloud config (as opposed to a stack in rancher), this solution may not be acceptable

We are effectively at a design impasse.

**Comment by deniseschannon** [comment]
Instead of using environmnt name, we should use environment UUID as it stays the same even if you rename the stack.

**Comment by sangeethah** [comment]
Tested with rancher server version - v1.6.8-rc1

Service containers and standalone containers  now have a system label ```io.rancher.environment.uuid``` set.
