### ISSUE TITLE
Connectivity broken between few hosts during upgrade , which caused etcd container to be stuck in "Initiliazing" state forever.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#8444]
Rancher Versions:v1.4.1

Deploy K8s env and deploy few user pods.

Point "Library" catalog to - https://github.com/rancher/rancher-catalog branch - v1.4.3-updates.
Upgrade  ipsec , network-manager and K8s stack that have "upgrade required" option.
I upgraded ipsec service after which network-manager was upgraded , followed by K8s stack.

Even when ipsec service was getting upgraded , one of etcd containers got to "Initializing" state and continued to remain in this state.

At this point , this etcd container was not able to reach other etcd containers.
Also at this point , DNS resolution from user pods was not functional. But was able to ping google using ip address. So connectivity between few sets of hosts were fine but few others seems to have been broken.

Even after upgrading the network-manager and K8s stacks , etcd continues to be in "Initializing" state.

After a while ( almost 1hour from the time it lost connectivity) , connection was restored by itself.
At this point , DNS resolution from user pods also started succeeding.

**Comment by leodotcloud** [comment]
@sangeethah Do you think we can close this issue with the recent networking fixes?

**Comment by superseb** [comment]
Closing this out
