### ISSUE TITLE
webhook-service enhancement: serviceUpgrade: support docker registry notifications

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#8445]
From @mnzaki:

The serviceUpgrade driver currently supports Docker Hub webhooks. It would be immensely useful to also support notification events from the docker registry, for people hosting their own private registries.

Example payloads: https://docs.docker.com/registry/notifications/#envelope

**Comment by kobellem** [comment]
any updates on this?

I just ran into the issue when creating a continuous deployment pipeline with gitlab and a private registry. My workaround for now is doing the http call at the end of the script (after the image has been pushed). But it would be much cleaner if rancher webhooks were compatible with private registries.
