### ISSUE TITLE
containers in “stopped” state along with a running ones when pods are created

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#8447]
Rancher server version - v1.4.1 
Library catalog set to https://github.com/rancher/rancher-catalog branch - v1.4.3-updates.

Steps to reproduce the problem:
I was testing some test cases around bringing down hosts in orchestration plane .
Once orchestartion services gets recreated on different hosts and K8s infra stack is in healthy state,
tried to deploy few pods.

For few of the pod deployments,there are containers in “stopped” state along with a running one when pods are launched. 
This stopped container have a 10.42.x.x ipaddress assigned to it.
These containers continue to  be reported as being in "stopped" state even after 12 hours.

**Comment by joshwget** [comment]
Garbage collection occurs after a certain number of stopped pods. Until that number is reached this is expected.

It would be nice to be able to configure this flag on controller manager though (#4751).

**Comment by sangeethah** [comment]
Related issue https://github.com/rancher/rancher/issues/8549

**Comment by deniseschannon** [comment]
There is no issue with the  stopped pods and we should track being able to configure the other flags in the #4751 issue if we want it different from the default values.
