### ISSUE TITLE
Rancher Server errors out after being idle for a while

### ISSUE THREAD

**Issue by sheng-liang** [rancher/rancher#8448]
**Rancher Versions:**
Server: 1.5.3
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker Version:** 
1.13.1-cs3
**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04.1, on my laptop running VMware workstation
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node Rancher server, 2 hosts. Rancher server node serving as one host
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
Setup Rancher server, add two hosts, start some services and containers, left it running for 19 hours
**Results:** 
Rancher server went down. (Because this is a laptop-based setup, there was obviously intermittent
 network connection issues. But host IPs never changed.) Exceptions in server log observed.
[server.zip](https://github.com/rancher/rancher/files/906452/server.zip)

**Comment by ibuildthecloud** [comment]
Did the Rancher server IP change?

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
