### ISSUE TITLE
Adding initializing/re-initializing timeouts for all services in infra stack

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#8449]
**Rancher Versions:**
Server: v1.5.4-rc1

sometimes services that has healthcheck enabled may be stuck in reinitializing state when the host powered off unexpectedly, these services include:

- healthcheck stack
- scheduler stack

**Comment by joshwget** [comment]
On a related note, it probably makes sense to have a conservative value set for all services by default.

**Comment by loganhz** [comment]
Added in latest version v1.6.22
