### ISSUE TITLE
Internal load balancer fails scheduling because it's looking for external port availability

### ISSUE THREAD

**Issue by oskapt** [rancher/rancher#8456]
**Rancher Versions:**
Server: 1.5.3
**Docker Version:**
1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):**
EC2/Ubuntu 16.04

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Standalone Server, internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
1. Deploy a single agent node
2. Deploy a load balancer that listens on port 80
3. In a different stack, deploy another one that is internal, listens on 80 and sends to 80
  * scheduling will fail because it looks for availability of `0.0.0.0/80` and no hosts satisfy the requirement
4. Change it to listen on 8000 instead
  * scheduling will still fail because it still wants availability of `0.0.0.0/80`

![lb-schedule-fail](https://cloud.githubusercontent.com/assets/171292/24836351/18f5df80-1cf0-11e7-998a-d0ed40e5272a.png)

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
