### ISSUE TITLE
helm client behind http proxy issue

### ISSUE THREAD

**Issue by hiscal2015** [rancher/rancher#8458]
**Rancher Versions:** 1.5.3

**Docker Version:** 1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):** Ubuntu16.04

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Kubernetes

**Steps to Reproduce:**

1. Disable http proxy and run "kubectl version" and "helm list" from **outside of cluster**, everything works fine.
2. Enable http proxy and run "kubectl version", it works fine.
3. Enable htto proxy and run "helm list", error:
```
$helm list
Error: forwarding ports: error upgrading connection: error sending request: Post https://rancher.demo.com/r/projects/1a7/kubernetes/api/v1/namespaces/kube-system/pods/tiller-deploy-1323696517-81jm7/portforward: http: server gave HTTP response to HTTPS client
```

Can anyone tell me how to fix it? Thanks.

**Comment by joshwget** [comment]
Are you also setting `HTTPS_PROXY`?

**Comment by hiscal2015** [comment]
@joshwget Yes I have both http and https proxy enabled.

**Comment by aemneina** [comment]
@hiscal2015 I assume you have a LB in front of rancher? If so can you share that configuration?

**Comment by hiscal2015** [comment]
@aemneina I have nginx in front of Rancher, here's the conf:

```
upstream rancher {
    server rancher-server:8080;
}

server {
    listen 443 ssl;
    server_name rancher.demo.com;
    ssl_certificate /etc/nginx/ssl/rancher.demo.com/1_rancher.demo.com_bundle.crt;
    ssl_certificate_key /etc/nginx/ssl/rancher.demo.com/2_rancher.demo.com.key;

    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://rancher;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        # This allows the ability for the execute shell window to remain open for up to 15 minutes. Without this parameter, the default is 1 minute and will automatically close.
        proxy_read_timeout 900s;
        client_max_body_size 0;
    }
}

server {
    listen 80;
    server_name rancher.demo.com;
    return 301 https://$server_name$request_uri;
}
```

**Comment by aemneina** [comment]
can you try with the following listen directive:
`listen 443 ssl spdy;`

**Comment by hiscal2015** [comment]
@aemneina I'm using nginx container with version 1.10.3, it has no spdy module enabled, but as I know, spdy is for speeding up SSL, will this be the cause?

**Comment by aemneina** [comment]
yeah, the spdy protocol is required for helm...

**Comment by ihcsim** [comment]
> yeah, the spdy protocol is required for helm...

I have issue with accessing tiller using external helm too, using a nginx LB in front of Rancher. Specifying the spdy protocol seems to solve my problem. If not already, I think this should be documented. 

The example in the [doc](https://docs.rancher.com/rancher/v1.6/en/installing-rancher/installing-server/basic-ssl-config/#example-nginx-configuration) does specify spdy, but I removed it because nginx 1:12 complained with the following warning:
```sh
lb_1 2017/06/18 17:33:32 [warn] 1#1: invalid parameter "spdy": ngx_http_spdy_module was superseded by ngx_http_v2_module in /etc/nginx/nginx.conf:17
lb_1 nginx: [warn] invalid parameter "spdy": ngx_http_spdy_module was superseded by ngx_http_v2_module in /etc/nginx/nginx.conf:17
```
Despite of the warning, everything is working fine for me with spdy.
