### ISSUE TITLE
UI displays error while switching from detail page of lb service to non-lb service

### ISSUE THREAD

**Issue by zionwu** [rancher/rancher#8460]
**Rancher Versions:**
Server: 1.5.3
healthcheck: 0.2.3
ipsec:0.9.4
network-services:0.5.3
scheduler:0.7.5
kubernetes (if applicable):

**Docker Version:**
Version 17.03.1-ce-mac5

**OS and where are the hosts located? (cloud, bare metal, etc):**
MacOs

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
1. Go to the service detail page for Load Balance Service,  click the second tag "Balancer Rules".
2. Click the drop down to show other service on the top left corner.
3. choose another non load balance service.  

![wechatimg1](https://cloud.githubusercontent.com/assets/1213386/24847251/6b30eeae-1df2-11e7-9cfb-a16cc59bc700.jpeg)

**Results:** 
UI display error message as blow:    
![wechatimg23](https://cloud.githubusercontent.com/assets/1213386/24847291/997d1ea4-1df2-11e7-93d4-8a18fe2345f8.jpeg)

**Comment by tfiduccia** [comment]
Version - master 4/10
This bug exist in master, Error in console:
Application Error TypeError: e.initPorts is not a function    route.js:71

**Comment by tfiduccia** [comment]
Version - master 4/26
Verified fixed
