### ISSUE TITLE
How to test a private catalog

### ISSUE THREAD

**Issue by qiuwei** [rancher/rancher#8462]
I've created a private catalog. However, one of the templates doesn't show up in Rancher.

Is there any tool to validate the templates?

Or where lies the log which shows what's going wrong in the templates?

**Comment by tfiduccia** [comment]
@qiuwei 

I add the private catalog then just ssh into the machine that has rancher on it.
Then:
sudo -s
docker ps
docker logs --tail=100 -f <containerid from docker ps for rancher>

If this works can you please close this issue.

**Comment by rbucker** [comment]
does not work... not even with the container name

**Comment by tfiduccia** [comment]
@rbucker docker logs --tail=100 -f <container id>.  This will show you the logs of rancher container and may help you track down your catalog issues.

I also suggest you take a look at http://rancher.com/docs/rancher/v1.6/en/catalog/private-catalog/, this is the help documentation we have for creating and using private catalogs.

**Comment by rbucker** [comment]
You are welcome to close this ticket however it is not resolved. [a] the docker command you indicate does not work as expected... -f does not actually follow the logs [b] the logs do not include any information when I refresh the page.

**Comment by tfiduccia** [comment]
@rbucker -  
[a] We have no control if the docker command works or not.  This is actually something from docker.  docker logs --help, will give you the log options.  If you have more issue with docker commands I would suggest you go to https://docs.docker.com/engine/reference/commandline/docker/.

[b]  The logs are not a tool that will tell you how to fix your catalog.  It may be a first step in showing you which template in your catalog is not working.  If the refresh button is not working, remove then re-add your catalog and see if that helps.  If no templates at all are loading, then it maybe that the catalog structure itself is not correct.  I would again suggest you go our help and ensure you have the correct format. 

If in the logs the catalog loads but your template can't be read.   You can post a issue with your yaml for us to look at, or go to rancher forums and post your yaml to get help.
