### ISSUE TITLE
[Webhook] Wrong environments upgraded from webhook when working with different imagenames on same tag

### ISSUE THREAD

**Issue by nitzek** [rancher/rancher#8463]
When I create a webhook with tag 'latest' and label environmentType='test' and I add the label on both my server and database environment, both environments get upgraded to the image I specified in the payload.

Wouldn't the way this should work be that you only upgrade those environments which have matching image/repo names? I can't think of any usecases in which you  suddenly want your container to become something completely different.

**Comment by mrajashree** [comment]
@nitzek it was designed in a way that all services with the label you provide will get upgraded. Since this feature relies on the user provided labels, I'll suggest using different labels for services with totally different repo/image names.

**Comment by ocasta** [comment]
I agree with nitzek on  this. Checking the image name before upgrading makes a lot of sense

The current approach feels wrong and is repetitive to setup. If I have three images and three matching containers in my dev environment and I want each to be updated when a new _dev_ image becomes available I need to setup three different web hooks and configure each within the right repo on docker hub (or equivalent). There's no point in using different labels as there is no way to map different images to different labels with the same web hook. Anyway, I already have a way of differentiating the images - its the image name!

**Comment by nitzek** [comment]
@mrajashree Can you provide a usecase in which this would be the wanted behavior? 

If any such usecases exist, I would suggest adding a checkbox(which is ticked by default) "Only upgrade matching imagenames". 

I agree with @ocasta that this is repetitive and sensitive to mistakes.

**Comment by janeczku** [comment]
@nitzek @ocasta what do you think about this changed approach:

Webhook configuration changes:
1. `Image Tag` option accepts a literal tag (e.g. "dev") or a regular expression (e.g. `^v[0-9.]+` to upgrade only release images).
2. `Service Selector` is optional

Flow:
1. Webhook is called
2. POST payload `tag` is checked against `Image Tag` configured in the webhook
3. If the tag does not match -> Noop
4. Find all services that use an image matching the `repo_name` in the POST payload
5. If `Service Selector` is defined, any services not matching the selector are skipped
6. Upgrade the matching services with the new image

**Comment by ocasta** [comment]
This would be a much better match with our needs. Thanks

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
