### ISSUE TITLE
Newly created rancher-ebs volumes are not empty

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#8465]
**Rancher Versions:**
Server: 1.5.3

Actual behavior:

The volume has a lost+found directory in it (created by fsck that is run after formatting).
This causes issues with applications that expect an empty data folder (e.g. mysql, kafka) and refuse to start up otherwise.

Expected behavior:

The volume should be empty.

**Comment by cjellick** [comment]
@janeczku - @StrongMonkey added a fix that deletes the lost+found dir, but I don't think that that is a viable solution. My understanding is that there are circumstances where that can/will comeback. I _think_ putting lost+found at the root of the file system is an inescapable feature/consequence of ext4.  There is a similar issue opened for the mysql container in the docker-library repo: https://github.com/docker-library/mysql/issues/252

So, I want to say that it needs to be up to the application developer to work around this quirk of ext4.

I may be wrong here, so I'm open to differing opinions.
Ping @vincent99 and @ibuildthecloud for your opinions

**Comment by StrongMonkey** [comment]
@cjellick I thought it would get recreated after `fsck` https://askubuntu.com/questions/165614/is-it-safe-to-delete-a-lostfound-folder. Not 100% sure

**Comment by vincent99** [comment]
Can rancher-ebs transparently make a subdir on the actual EBS filesystem and expose only that dir to the container?

**Comment by cjellick** [comment]
@vincent99 @yasker just suggested the same exact thing in slack. seems like a decent solution

**Comment by cjellick** [comment]
But apparently @ibuildthecloud told @StrongMonkey to just delete the dir if its empty

**Comment by cjellick** [comment]
Darren agreed with the subdir idea. But the impl will be more complicated since docker gives you the path to which you must mount the volume. So, we'll have to do two mounts, I think

**Comment by janeczku** [comment]
@cjellick i think it's the other way around: volume driver provides the mountpoint path to Docker. So we merely need to create a `rootfs` subdir in the root 😉  and pass that back to docker.

**Comment by cjellick** [comment]
@janeczku FYI, apparently this is an issue with k8x flexvols (which i'm not super familiar with).

**Comment by cjellick** [comment]
@StrongMonkey @soumyalj When this is tested, make sure you test the "legacy" volume flow. @StrongMonkey will be able to explain what that means and its implications

**Comment by StrongMonkey** [comment]
the fix is available at rancher/storage-ebs:v0.8.1.

**Comment by StrongMonkey** [comment]
Already sync with @soumyalj. The basic test flow would be:
1. Create a new EBS volume. Attached it to a container, the path inside the container should be empty. The mountpoint for the container should be /var/lib/rancher/volume/rancher-ebs/volumename/_rancher-data. (rancher will mount the subdir(_rancher-data) to container if user doesn't have pre-existing data).
2. Create a new EBS volume. Write some files to it. Attached it to a container, the path inside the container should **not** be empty. The mountpoint for the container should be /var/lib/rancher/volume/rancher-ebs/volumename, which should have the files that were previously written. (rancher will still mount the root directory to preserve the old data)

**Comment by soumyalj** [comment]
Tested with 1.6.0-rc4. 
1. Created a new volume and a service with scale 2 using the volume mounted to directory /mydata. The directory /mydata is empty without any lost+found directory
