### ISSUE TITLE
Waiting for Kubernetes API

### ISSUE THREAD

**Issue by chrisyoung12345** [rancher/rancher#8474]
All of the containers are showing "green" and there are no obvious indications of error but the system is stuck at "Waiting for Kubernetes API".

---
Rancher	v1.5.3
Cattle	v0.177.10
User Interface	v1.5.8
Rancher CLI	v0.5.1
Rancher Compose	v0.12.4
Kubernetes rancher/k8s:v1.5.4-rancher1-3

**Comment by deniseschannon** [comment]
Where is the "Waiting for Kubernetes API" text?  Is it in the UI?

Have you tried doing a refresh to see if the Kubernetes tab shows up?

**Comment by chrisyoung12345** [comment]
@deniseschannon This issue was resolved last night thanks to the wonderful support from the Rancher team. The issue turned out to be related to stale tokens in the environment. The resolution involved the following steps, as provided by Adrian Goins:

The solution:
    
    Delete the token first:
    Get the token id with:
    `kubectl -n kube-system describe serviceaccount io-rancher-system`
    `kubectl –n kube-system delete secret <token name>`
    then remove the add-on's:
    `kubectl -n kube-system get pods`
    delete tiiler, kube-dns, kubernetes-dashboard, heapster pods, and only the pods.     They'll be recreated and should be able to access the k8s api.

*DO NOT* delete influxdb

This can be closed. Thank you for the follow up.
