### ISSUE TITLE
Containers don't see each other in 10.42.0.0/16 network

### ISSUE THREAD

**Issue by ekb100500** [rancher/rancher#8476]
**Rancher Versions:**
Server: 1.5.4
healthcheck: v0.2.3
network-services: v0.6.6
scheduler: v0.7.5
**Docker Version: 1.12.6**
**OS: Centos 7 x64, Cloud**
**Setup Details: Single node with internal DB**
**Environment Type: Cattle**

I have single Rancher server(rancher) with 2 hosts(dc0, dc1) 
I have a problem with network 10.42.0.0/16 between containers, containers don't see each other(don't ping each other)
I disabled firewalld and selinux before install Rancher
Container healthcheck is OK only when one host is added to rancher(dc0 or dc1), if the second host is added to Rancher then container healthcheck gets Warning status http://screencloud.net/v/tMeF3

Additional information:
rancher https://pastebin.com/raw/R4aj0LQV
dc0 https://pastebin.com/raw/dxBTJWPW
dc1 https://pastebin.com/raw/qEaHKh3m

rancher server container on rancher https://pastebin.com/raw/KujwcnBQ

healthcheck     container on dc0 https://pastebin.com/raw/cj1JZsm2
scheduler       container on dc0 https://pastebin.com/raw/b2tecQ6r
network-manager container on dc0 https://pastebin.com/raw/njwXHYmU
metadata        container on dc0 https://pastebin.com/raw/fT220bJX
rancher-agent   container on dc0 https://pastebin.com/raw/3xRzQGbJ

healthcheck     container on dc1 https://pastebin.com/raw/wAVHqzFh
network-manager container on dc1 https://pastebin.com/raw/LLKuFXLs
metadata        container on dc1 https://pastebin.com/raw/nNssSwaE
rancher-agent   container on dc1 https://pastebin.com/raw/0cU8jVgs

What was my mistake?

Thanks

**Comment by deniseschannon** [comment]
Do you have UDP ports 500 and 4500 open? If you exec into a container, can you ping the `10.42.x.x` IP address of a container on the other host?

**Comment by ekb100500** [comment]
Hi, Denise
Yes, ports 500 and 4500 are open
Yes, I tried to exec into a container and ping container with IP 10.42.x.x in other host and it wasn't successful

**Comment by aemneina** [comment]
@ekb100500 do you have the iptables service running?

**Comment by githubsaritasa** [comment]
Hi @aemneina,
No, service firewalld is disabled
But the iptables is controlled via Rancher https://pastebin.com/raw/R4aj0LQV

**Comment by superseb** [comment]
@githubsaritasa Your host screenshots show 2 hosts with the same agent IP registered, did you copy paste the `docker run` command for the agent on both hosts? I think this will make routing hard.

**Comment by aemneina** [comment]
Good eye @superseb that's most likely the issue. The IPSec network gets established between hosts using their registered ip. This can also happen when agents connect through a NAT

**Comment by ekb100500** [comment]
@superseb @aemneina yes, im sorry, i copied the command wrong
Now it's looks like this http://screencloud.net/v/nRka2
Cluster works well till the restart of servers, after restart Rancher and hosts in cluster i got an error like up on the screenshot

**Comment by superseb** [comment]
What's the complete error message for network-manager? (Error response from daemon...)

**Comment by ekb100500** [comment]
@superseb http://screencloud.net/v/D3sOh

**Comment by superseb** [comment]
Are you using RedHat supplied Docker or upstream Docker? `docker version` + `docker info` would help

**Comment by ekb100500** [comment]
@superseb 
`[root@dc1 ~]# docker version
Client:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-common-1.12.6-11.el7.centos.x86_64
 Go version:      go1.7.4
 Git commit:      96d83a5/1.12.6
 Built:           Tue Mar  7 09:23:34 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-common-1.12.6-11.el7.centos.x86_64
 Go version:      go1.7.4
 Git commit:      96d83a5/1.12.6
 Built:           Tue Mar  7 09:23:34 2017
 OS/Arch:         linux/amd64
[root@dc1 ~]# 
[root@dc1 ~]# docker info
Containers: 9
 Running: 4
 Paused: 0
 Stopped: 5
Images: 8
Server Version: 1.12.6
Storage Driver: devicemapper
 Pool Name: docker-253:0-33589486-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 728.4 MB
 Data Space Total: 107.4 GB
 Data Space Available: 29.11 GB
 Metadata Space Used: 2.343 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.145 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.135-RHEL7 (2016-09-28)
Logging Driver: journald
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Security Options: seccomp
Kernel Version: 3.10.0-514.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 2
CPUs: 1
Total Memory: 1.796 GiB
Name: dc1
ID: LLNU:LHIF:5FVC:ZCZD:VMTM:PPW6:ADH5:WHC3:AXBR:L5UM:F5WW:N7BT
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8
Registries: docker.io (secure)
[root@dc1 ~]# 
`

**Comment by superseb** [comment]
@ekb100500 You are experiencing the same problem as https://github.com/rancher/rancher/issues/8582. I will close this, please continue in the other issue. The workaround is to remove RHEL's packaged Docker and install upstream Docker packages.
