### ISSUE TITLE
Kubernetes services not being created in DB after network-services upgrade

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#8477]
**Rancher Versions:**
Server:v1.4.1

**Docker Version:**1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):**Ubuntu, Cloud

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**Single node

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**Kubernetes

**Steps to Reproduce:**
1. Create pods/ingresses/lbs on a v1.4.1  Kubernetes setup. Ensure they are functional
2. Point the library catalog to  https://github.com/rancher/rancher-catalog, v1.4.3-updates branch
3. Upgrade IPsec and then Network services stack
4. After network services stack is upgraded, create new pods and ingress.
Pod creation is successful. But ingress is not programmed correctly and is not functional. The haproxy.cfg file does not show the targets programmed for the ingress LB.

Ingress controller logs below:
```

4/11/2017 2:22:15 PMtime="2017-04-11T21:22:15Z" level=error msg="Failed to apply lb config on provider: Failed to find service [319b0663-1eeb-11e7-bbf7-02d2df5c13ed] in Rancher"
4/11/2017 2:22:15 PMtime="2017-04-11T21:22:15Z" level=error msg="Failed to apply lb config on provider: Failed to find service [319b0663-1eeb-11e7-bbf7-02d2df5c13ed] in Rancher"
4/11/2017 2:22:15 PMtime="2017-04-11T21:22:15Z" level=error msg="Failed to apply lb config on provider: Failed to find service [d5470a68-1ef4-11e7-bbf7-02d2df5c13ed] in Rancher"

```

**Comment by deniseschannon** [comment]
The root cause of the ingress not working is the kubernetes services being created were not being added to the `service` table in the DB as there was an issue in the kubernetes-agent. After restarting the agent, services were being inserted in to the DB correctly.

**Comment by galal-hussein** [comment]
Rancher server 1.6.2 to 1.6.3-rc7
Setup: HA setup with 3 rancher server nodes

I am seeing the same issue after upgrading network-services stack to newer version after upgrading rancher server, kubernetes-agent doesn't populate the services created in rancher DB.
