### ISSUE TITLE
Unable to Deploy Stacks if Image Didn't Previously Exist

### ISSUE THREAD

**Issue by ecliptik** [rancher/rancher#8478]
**Rancher Versions:**
Server: 1.5.4
healthcheck: rancher/healthcheck:v0.2.3
ipsec: rancher/net:v0.11.2
network-services: rancher/network-manager:v0.6.6, rancher/metadata:v0.9.1
scheduler: rancher/scheduler:v0.7.5

**Docker Version:**
1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04 on AWS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher master

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
cattle

**Steps to Reproduce:**
Deploy a stack with a service that has an invalid docker image tag with `rancher-compose`, such as a typo or incorrectly generated tag.

Attempt to re-deploy stack with corrected docker image tag.

**Results:** 
With the incorrect docker image tag, Rancher will report the image doesn't exist and fail to launch the stack. However if the stack is re-deployed with a known working docker image tag it never fully starts and hangs indefinitely. Deleting and re-deploying the stack does not fix the issue. Manually starting a service via the UI does bring the service up, but deploying via `rancher-compose` does not work.

It appears that the incorrect image continually sticks around in the delayed process tab. This seems to affect all stacks deploying, even those without the incorrect image tag.

<img width="1357" alt="screen shot 2017-04-11 at 4 14 18 pm" src="https://cloud.githubusercontent.com/assets/1261742/24935054/47dd6634-1ed4-11e7-90ec-07c2254c00ab.png">

Logs in rancher-server show continual errors for the incorrect image tag

```
2017-04-11 23:17:40,796 ERROR [:] [] [] [] [ecutorService-1] [.e.s.i.ProcessInstanceDispatcherImpl] Agent error for [compute.instance.pull.reply;agent=13]: Error response from daemon: No such image: demandbase/dashboard-api:develop-bed50capull-16963
2017-04-11 23:17:40,801 ERROR [:] [] [] [] [ecutorService-3] [.e.s.i.ProcessInstanceDispatcherImpl] Agent error for [compute.instance.pull.reply;agent=13]: Error response from daemon: No such image: demandbase/dashboard-api:develop-bed50capull-16962
2017-04-11 23:17:41,735 ERROR [7204d830-d429-4023-89fa-d28f8bc9b10d:16964] [genericObject:260] [genericobject.create] [] [ecutorService-2] [c.p.e.p.i.DefaultProcessInstanceImpl] Agent error for [compute.instance.pull.reply;agent=13]: Error response from daemon: No such image: demandbase/dashboard-api:develop-bed50capull-16964
2017-04-11 23:17:41,759 ERROR [:] [] [] [] [ecutorService-2] [.e.s.i.ProcessInstanceDispatcherImpl] Agent error for [compute.instance.pull.reply;agent=13]: Error response from daemon: No such image: demandbase/dashboard-api:develop-bed50capull-16964
2017-04-11 23:17:41,805 ERROR [a1bcfa78-4b62-4bdd-ab7d-d9a0c18966ca:16966] [genericObject:259] [genericobject.create] [] [ecutorService-3] [c.p.e.p.i.DefaultProcessInstanceImpl] Agent error for [compute.instance.pull.reply;agent=2]: Error response from daemon: No such image: demandbase/dashboard-api:develop-bed50capull-16966
2017-04-11 23:17:41,831 ERROR [13f37547-66fa-4610-be72-dd4988cc6a49:16965] [genericObject:261] [genericobject.create] [] [ecutorService-1] [c.p.e.p.i.DefaultProcessInstanceImpl] Agent error for [compute.instance.pull.reply;agent=2]: Error response from daemon: No such image: demandbase/dashboard-api:develop-bed50capull-16965
2017-04-11 23:17:41,843 ERROR [:] [] [] [] [ecutorService-3] [.e.s.i.ProcessInstanceDispatcherImpl] Agent error for [compute.instance.pull.reply;agent=2]: Error response from daemon: No such image: demandbase/dashboard-api:develop-bed50capull-16966
2017-04-11 23:17:41,860 ERROR [:] [] [] [] [ecutorService-1] [.e.s.i.ProcessInstanceDispatcherImpl] Agent error for [compute.instance.pull.reply;agent=2]: Error response from daemon: No such image: demandbase/dashboard-api:develop-bed50capull-16965
2017-04-11 23:17:42,771 ERROR [04059b48-cd81-4512-a0c5-2fea5ac76e1c:16967] [genericObject:262] [genericobject.create] [] [ecutorService-2] [c.p.e.p.i.DefaultProcessInstanceImpl] Agent error for [compute.instance.pull.reply;agent=13]: Error response from daemon: No such image: demandbase/dashboard-api:develop-bed50capull-16967
2017-04-11 23:17:42,794 ERROR [:] [] [] [] [ecutorService-2] [.e.s.i.ProcessInstanceDispatcherImpl] Agent error for [compute.instance.pull.reply;agent=13]: Error response from daemon: No such image: demandbase/dashboard-api:develop-bed50capull-16967
2017-04-11 23:18:09,692 ERROR [fca6d757-e1de-4876-8b92-6887a6ed4133:16692] [genericObject:241] [genericobject.create] [] [ecutorService-3] [c.p.e.p.i.DefaultProcessInstanceImpl] Agent error for [compute.instance.pull.reply;agent=13]: Error response from daemon: No such image: demandbase/dashboard-web:d8bd03b-newrelic-developmentpull-16692
2017-04-11 23:18:09,726 ERROR [:] [] [] [] [ecutorService-3] [.e.s.i.ProcessInstanceDispatcherImpl] Agent error for [compute.instance.pull.reply;agent=13]: Error response from daemon: No such image: demandbase/dashboard-web:d8bd03b-newrelic-developmentpull-16692
```

rancher-compose command used to deploy:

```
rancher-compose --verbose \
        -f docker-compose-rancher.yml \
        --env-file .env.export \
        -p stack-name \
        up \
        --confirm-upgrade \
        --pull \
        -d
```

**Comment by cjellick** [comment]
From one of the bad genericobjects:
```
Database changed                                                                                                                                       [2/42]
mysql> select * from generic_object where id = 262;
+-----+------+------------+----------+--------------------------------------+-------------+------------+---------------------+---------+-------------+-------
-------------------------------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------+------+
| id  | name | account_id | kind     | uuid                                 | description | state      | created             | removed | remove_time | data
                                                                                 | key  |
+-----+------+------------+----------+--------------------------------------+-------------+------------+---------------------+---------+-------------+-------
-------------------------------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------+------+
| 262 | NULL |          7 | pullTask | b1dad7b8-03c5-4f85-89f4-2c6d6fb31ba9 | NULL        | activating | 2017-04-11 21:57:12 | NULL    | NULL        | {...} | NULL |
+-----+------+------------+----------+--------------------------------------+-------------+------------+---------------------+---------+-------------+-------
-------------------------------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------+------+
1 row in set (0.04 sec)
```

**Comment by ibuildthecloud** [comment]
@ecliptik I'll look into what is happing, but this can be avoided by not doing `-p`.  Nothing has changed in this area for a bit, so not too sure whats up.

**Comment by ibuildthecloud** [comment]
@ecliptik I think I'm wrong, can you share what rancher-compose version you are using?

**Comment by ecliptik** [comment]
@ibuildthecloud this is a newish install from last week when we split our development master away from production master and now have two endpoints to test newer versions of Rancher before rolling to our production master. 

It was originally 1.5.3 but I upgraded it to 1.5.4 last night after it was released. Before 1.5.4 I don't remember seeing this issue. Although we did have problems were stacks would go into `upgraded` and we had to manually finish them instead of them automatically completing like before.

Version of rancher-compose is `v0.12.3`

**Comment by ecliptik** [comment]
I'm not exactly sure where these incorrect tag names are coming from either, since I don't see anywhere in our Jenkins jobs that adds a `pull-17138` or anything of that type to a image tag for the two stacks that are reporting an incorrect image tag name.

It does appear that `pull-17138` could refer to `PullTaskCreate` and process id `17138`.

**Comment by cjellick** [comment]
Update from slack convo with @ibuildthecloud  and @ecliptik :
pull-XXX is intentionally added by rancher to make the pull task idempotent. We temporarily tag the image like that and then delete the tag subsequently.
The bug is centered around why we cannot delete the temporary tag after the pull succeeds.

**Comment by ibuildthecloud** [comment]
This issue seems to be a regression from https://github.com/rancher/cattle/pull/2593 which was introduced in v1.5.4.  That PR is to address a memory leak caused by how we used topics in Hazelcast.  While addressing that issue we caused a scenario in which a single message can be delivered N times.  During testing this bug was not discovered because we have as a general characteristic of our system is that all operations are idempotent and assume concurrent events will happen.  So for pretty much everything the fact a double message is delivered doesn't matter.  Except..... image pulling from `rancher-compose pull` or `rancher-compose up -p`.  It was found that while the operation is idempotent it can not be ran concurrently for the same message.  This was not discovered in our testing unfortunately as its a pretty specific failure scenario.  The scenario to reproduce is to restart the rancher-agent 2-3 times with about 5 seconds in between each restart.  Then do a `rancher-compose pull` or `rancher-compose up -p` and it would fail.

**Comment by ibuildthecloud** [comment]
Also, just a bit more context.  This issue requires HA to be enabled.  If you run HA w/ multiple servers you get a 1/N chance of hitting this bug, but HA with 1 node is 100% chance of hitting it.

**Comment by ecliptik** [comment]
Attempted to re-produce with v1.5.6.-rc1 and wasn't able to. Looks good on our end.

**Comment by galal-hussein** [comment]
Rancher server: v1.5.6-rc1
HA setup with only 1 node
I don't see the problem when trying to deploy a stack with broken image, and then trying to redeploy the same stack with a working docker image tag.
Also i tested restarting rancher-agent 2-3 times with 5 seconds between each restart, and i can see rancher-compose pull and rancher-compose up -p works.
