### ISSUE TITLE
Unable to launch any Catalog services

### ISSUE THREAD

**Issue by tombmurphy** [rancher/rancher#8479]
**Rancher Versions:**
Server: v1.5.5
kubernetes: 1.5.4-rancher1-3

**Docker Version:**
```Containers: 17
 Running: 16
 Paused: 0
 Stopped: 1
Images: 14
Server Version: 1.12.6
Storage Driver: btrfs
 Build Version: Btrfs v4.4
 Library Version: 101
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null overlay host bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-64-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.952 GiB
Name: xxx
ID: FHB6:2PP7:TQN7:ICVW:XEFV:56LG:LQT3:TEKO:QK24:QJM6:WSCN:IBI3
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**OS and where are the hosts located? (cloud, bare metal, etc):**
AWS rancher-server running behing a reverse proxy

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node with external RD RDS

**Environment Type:**
Kubernetes

**Steps to Reproduce:**
Go to the Catalog
Launch anything

**Results:** 
The stack gets created with nil containers.

No useful log:

```time="2017-04-12T03:56:51Z" level=info msg="Stack Create Event Received" eventId=985d4a49-7fd6-4289-a0c5-4fa5813a0b08 resourceId=1st45 
time="2017-04-12T03:56:51Z" level=info msg="Stack Create Event Done" eventId=985d4a49-7fd6-4289-a0c5-4fa5813a0b08 resourceId=1st45 
```

Screenshot:
![redis](https://cloud.githubusercontent.com/assets/2703290/24940971/0b735f8a-1f8a-11e7-9e90-32990a7afdac.png)

**Comment by deniseschannon** [comment]
When you say nil containers, do you mean it comes up with 0 containers? 

Can you share a screen shot of the stacks?

Did your infrastructure stacks come up with any containers?

**Comment by tombmurphy** [comment]
@deniseschannon yes that's correct. I've noticed this behaviour since v1.5.3 as well.

Screenshot attached to issue.

**Comment by deniseschannon** [comment]
The catalog is deprecated for Kubernetes in favor of providing Helm as of 1.4. You've found a path to the catalog where templates are still shown, but the backend is not there to deploy them anymore.

There are a couple of ways to "find" your way to the catalog linked in this other issue:

https://github.com/rancher/rancher/issues/8336
