### ISSUE TITLE
[Bug] Initial API call to create Ldap config returns HTTP 503

### ISSUE THREAD

**Issue by Batro** [rancher/rancher#8481]
**Rancher Versions:**
Server: 1.5.2
healthcheck: 
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker Version:** 17.03-ce

**OS and where are the hosts located? (cloud, bare metal, etc):** Ubuntu Trusty 64 on an OpenStack Cloud

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** Single node Rancher, internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:** Install a fresh new Rancher Server, then try to enable Active Directory access control using an API call (manually via cURL or automatically) with valid parameters for you AD config.

**Results:** API response is a HTTP 503, with a "Ldap is not configured" message, instead of a 201.

**Details:** After configuring the Ldap access control manually within the UI, all following API calls to modify Ldap config succeed

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
