### ISSUE TITLE
The new MTU does not take effect after IPSec upgrade

### ISSUE THREAD

**Issue by meggarr** [rancher/rancher#8482]
**Rancher Versions:**
Server:
1.5.4
healthcheck:
rancher/healthcheck:v0.2.3
ipsec:
rancher/net:v0.11.2
network-services:
rancher/network-manager:v0.6.6
scheduler:
kubernetes (if applicable):

**Docker Version:**
12.6

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu, bare metal

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Full HA

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
Update the IPSec to a version, and change the MTU from 1460 to 1400, 

**Results:** 
The MTU does not take effect for all containers' interface.

**Comment by meggarr** [comment]
I guess the MTU should be inherited from the environment setting, but not be a configurable param for IPSec

**Comment by aemneina** [comment]
@meggarr i think its a combination of both. Your docker bridge and underlying interface need that MTU set first. If not the newly created virtual interfaces wont get the larger MTU size... @leodotcloud does that sound about right?

**Comment by meggarr** [comment]
The docker's interface MTU are all 1460 which is a config in my environment's IPSec parameter. When I do a upgrade, I think that parameter should not be changeable, and it is not applied even it is changed.

I wouldn't think it's a combination, as it comes from IPSec all the time, the only question is about ability to customize/change during an upgrade.

**Comment by leodotcloud** [comment]
@meggarr The MTU setting for IPSec is used to set the MTU of the network interface inside the container created by Rancher. Currently, we do not touch the docker bridge to change it's MTU, this has to be done outside of Rancher. Docker config is managed by the SysAdmin of the host. So in your case if you have changed the MTU in the IPSec template you also need to restart docker daemon with the new MTU setting.

Second thing, we do not change the MTU of already running containers. So you would have to restart the already running containers for the new MTU to take effect.

**Comment by meggarr** [comment]
I guess I am more confused based on what I see in my host, the `docker0` is set to the MTU of same number in Rancher `mtu 1460`, while no one set it. The only chance is Rancher did it - because I config'd it as `1460` in Rancher, see the list on my host below..

```
@rankube-master1:~$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: ens3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 52:54:00:fe:23:bf brd ff:ff:ff:ff:ff:ff
    inet 10.245.247.220/24 brd 10.245.247.255 scope global ens3
       valid_lft forever preferred_lft forever
    inet6 fe80::5054:ff:fefe:23bf/64 scope link
       valid_lft forever preferred_lft forever
3: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1460 qdisc noqueue state UP group default
    link/ether 02:42:8f:4a:c7:da brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 scope global docker0
       valid_lft forever preferred_lft forever
    inet 10.42.0.1/16 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:8fff:fe4a:c7da/64 scope link
       valid_lft forever preferred_lft forever
9: veth99b97d6@if8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP group default
    link/ether 1e:ef:26:f1:4c:86 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::1cef:26ff:fef1:4c86/64 scope link
       valid_lft forever preferred_lft forever
10: veth62c81ed7@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1460 qdisc noqueue master docker0 state UP group default
    link/ether da:38:17:d3:a6:8d brd ff:ff:ff:ff:ff:ff link-netnsid 1
    inet6 fe80::d838:17ff:fed3:a68d/64 scope link
       valid_lft forever preferred_lft forever
48: veth48a6d522@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1460 qdisc noqueue master docker0 state UP group default
    link/ether 36:79:d2:22:cb:aa brd ff:ff:ff:ff:ff:ff link-netnsid 3
    inet6 fe80::3479:d2ff:fe22:cbaa/64 scope link
       valid_lft forever preferred_lft forever
54: veth516f008a@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1460 qdisc noqueue master docker0 state UP group default
    link/ether 8a:9f:e6:6c:27:3b brd ff:ff:ff:ff:ff:ff link-netnsid 9
    inet6 fe80::889f:e6ff:fe6c:273b/64 scope link
       valid_lft forever preferred_lft forever
170: vethf340630f@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1460 qdisc noqueue master docker0 state UP group default
    link/ether 1a:15:4e:e5:c9:b4 brd ff:ff:ff:ff:ff:ff link-netnsid 5
    inet6 fe80::1815:4eff:fee5:c9b4/64 scope link
       valid_lft forever preferred_lft forever
175: veth8a96893c@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1460 qdisc noqueue master docker0 state UP group default
    link/ether 36:5f:78:d3:ad:3e brd ff:ff:ff:ff:ff:ff link-netnsid 4
    inet6 fe80::345f:78ff:fed3:ad3e/64 scope link
       valid_lft forever preferred_lft forever
184: vethe61ecd6e@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1460 qdisc noqueue master docker0 state UP group default
    link/ether ee:03:e9:11:47:8e brd ff:ff:ff:ff:ff:ff link-netnsid 7
    inet6 fe80::ec03:e9ff:fe11:478e/64 scope link
       valid_lft forever preferred_lft forever
185: veth759c66f6@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1460 qdisc noqueue master docker0 state UP group default
    link/ether fe:cc:01:8b:93:8f brd ff:ff:ff:ff:ff:ff link-netnsid 8
    inet6 fe80::fccc:1ff:fe8b:938f/64 scope link
       valid_lft forever preferred_lft forever
188: vethd97fe7a2@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1460 qdisc noqueue master docker0 state UP group default
    link/ether c6:e5:83:fd:cd:48 brd ff:ff:ff:ff:ff:ff link-netnsid 6
    inet6 fe80::c4e5:83ff:fefd:cd48/64 scope link
       valid_lft forever preferred_lft forever
189: vethc28b6b1b@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1460 qdisc noqueue master docker0 state UP group default
    link/ether 76:4a:93:03:a4:54 brd ff:ff:ff:ff:ff:ff link-netnsid 2
    inet6 fe80::744a:93ff:fe03:a454/64 scope link
       valid_lft forever preferred_lft forever
```

WRT the 2nd one, i will try that later.

**Comment by superseb** [comment]
We added some docs on changing the MTU here: http://rancher.com/docs/rancher/v1.6/en/rancher-services/networking/#changing-the-mtu.

Please let us know if you need any more help.
