### ISSUE TITLE
Rancher deletes Kubernetes Ingress Lbs after edit (Rancher UI)

### ISSUE THREAD

**Issue by mliese** [rancher/rancher#8483]
**Rancher Versions:**
Server: 1.5.5
healthcheck: rancher/healthcheck:v0.2.3
kubernetes: rancher/k8s:v1.5.4-rancher1-3

**Docker Version:** 17.03.1-ce on Rancher Server

**OS and where are the hosts located? (cloud, bare metal, etc):** Cloud Ubuntu 14.04

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** Single node Rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Kubernetes

**Steps to Reproduce:**
- Install a fresh new Rancher Server
- Add host
- Add sample kubernetes app "hello-node" in kubernetes
- Add sample ingress-lb in kubernetes
- Edit kubernetes-ingress-lb in rancher (Change or Add ServiceRule, Port)

**Results:** 
After pressing "edit", the loadbalancer is gone from rancher and is not anymore loadbalancing (Showing "No Services").
After a short time, the load balancer gets recreated with old rules. (Loadbalancing again, but new rules are gone)

**Details**
I would expect, that the rancher ui shows errors and is not completely deleting the lb on edit.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
