### ISSUE TITLE
How to uninstall/stop service

### ISSUE THREAD

**Issue by hhirsch** [rancher/rancher#8484]
How can I uninstall or stop rancher and cattle on Linux in general?

**Comment by aemneina** [comment]
```
docker stop <id|name of container>
docker rm -fr <id|name of container>
```

**Comment by monotek** [comment]
for ID in $(docker ps |grep "rancher/" | awk '{print $1}');do docker container stop ${ID};done

**Comment by nikolaypopov** [comment]
for ID in $(docker ps |grep "rancher/" | awk '{print $1}');do docker rm -f ${ID};done

because:
docker: 'container' is not a docker command.
See 'docker --help'.
