### ISSUE TITLE
API v2 stacks endpoint do not display docker and rancher compose for the stacks built by hand

### ISSUE THREAD

**Issue by njordr** [rancher/rancher#8485]
Hi.

If I call /v2-beta/stacks endpoint I can see the docker and rancher compose for the default stacks and the ones installed from the catalog, but not for the ones built by hand (but i can see the two compose files using the web interface)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.5.3` Cattle: `v0.177.10` UI: `v1.5.8` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`stack.code`|

**Comment by joshwget** [comment]
What do you mean by "built by hand" in this case?

**Comment by njordr** [comment]
The ones created from scratch using the web interface.

In my case i created a stack and then add services to it (3 services: mysl, gogs and postfix)

**Comment by joshwget** [comment]
I think this is expected. If you create services manually there won't be any Compose file associated with them. If you export the stack then compose files can be generated based on the values from the Compose file.

**Comment by vincent99** [comment]
Those fields are the input you provided when creating the stack and are not updated as things are changed.  To get the current YAML for a stack use the `exportConfig` action.

**Comment by njordr** [comment]
Great, thanks
