### ISSUE TITLE
UI RFE: When switching environments the current view should be preserved

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#8486]
**Rancher Versions:**
Server: 1.5.5

**Actual behavior**
If you switch environments you are always redirected to the User Stacks page of the environment regardless what view was active when you switched.

**Expected behavior**
When switching environments it should navigate to the current view for the new environment (e.g. Hosts page Env A => Click to switch to Env B => Shows Hosts page for Env B).

**Comment by janeczku** [comment]
@vincent99

**Comment by vincent99** [comment]
No?  This could only work on top-level pages, if you're on any detail page that resource doesn't exist, if you're on the catalog the selected catalog might not exist (soon), etc.  So it still sometimes has to go somewhere you weren't, and it's worse if appears you go to a *random* page when switching.

**Comment by tfiduccia** [comment]
@janeczku - been this way since beginning with Vincent giving me the same response. 
#612

**Comment by tfiduccia** [comment]
Areas that don't persist:
Advanced tab on Containers
Hosts list page
Apps list page
Catalog list page
Resources & Admin menu items

**Comment by tfiduccia** [comment]
@loganhz - Can you give me a list of persistent pages?  Is it only on the project level?  Is it across clusters.  Please give some detail as the work you have done.

**Comment by loganhz** [comment]
If you switch between clusters, all of the cluster menu will be preserved. (Cluster, Nodes, PV, SC, Projects, Members, Alerts, Notifier, Logging, Pipeline)

If you switch between projects, all of the project menu will be preserved. (Workloads, Catalog Apps, Alerts, Certificates, Config Maps, Logging, Registries, Secrets, Namespaces, Members)

**Comment by tfiduccia** [comment]
Work done in 2.0.5.  Full testing will bleed into 2.0.6, so i moved the milestone.

**Comment by tfiduccia** [comment]
Version - 2.0 master 7/23
Verified fixed
