### ISSUE TITLE
[catalog] feature request: support templating

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#8488]
The catalog is a very powerful feature but it is extremely limiting in what can be done with the compose files and the questions section. 

It would be very advantageous if catalog docker compose and rancher compose files supported golang templates, or some other sort of templating system that would allow for if statements.

Most of my private applications are configured by environment variables and under certain conditions we want to leave the env var out entirely vs setting it, as of right now, at least to my knowledge there is no way to do `if question == answer then include env var else exclude` 

Supporting a template system would make the catalog and question/answer system so much more powerful a lot more logic could be put in place to give catalog services more power. 

```
someservice:
  image: someimage
  environment:
    {{ if answer_one == "production" }}
    - this_env_var=yes
    {{ else }}
    - this_other_env_var=yes
    {{ endif }}
```

**Comment by joshwget** [comment]
This is already supported in 1.5.x actually (https://docs.rancher.com/rancher/v1.5/en/cli/variable-interpolation/#templating). This also applies to all Compose files and not just those created through CLI.

**Comment by ekristen** [comment]
What?! Mind is blown! Thanks rancher team! I just have just missed that in the docs! Exciting times!

**Comment by tfiduccia** [comment]
@ekristen Your welcome.  Here is the section in the help - http://docs.rancher.com/rancher/v1.5/en/cli/variable-interpolation/#templating

I'm going to close this.  Glad we could help.

**Comment by ekristen** [comment]
Does this also offer a different way or a new way to do variable substitution or has that remained the same?

**Comment by deniseschannon** [comment]
@ekristen Variable Substitution remains the same.
