### ISSUE TITLE
[Language Bug] Setting language to German breaks the host delete modal

### ISSUE THREAD

**Issue by Braintelligence** [rancher/rancher#8489]
When setting the language of the rancher web ui to German and trying to delete a host you do not see a modal at all, you only see the background turning grey as if a modal should appear.

This error appears in the dev console of Firefox:
`Error: A value must be provided for: isServiceButton` `vendor.css:5:9515`

If I set language to English the error doesn't appear and I see a modal.

**Comment by tfiduccia** [comment]
Version - master 4/12
This is indeed an issue and affects all the delete modals (host, service, stack, etc...)

**Comment by tfiduccia** [comment]
Version: master 4/26
Verified fixed
