### ISSUE TITLE
Rancher agent refuses to work with rancher server behind proxy doing SSL termination

### ISSUE THREAD

**Issue by nwlucas** [rancher/rancher#8490]
Using HAProxy as load balancer and SSL termination to Rancher Servers.

Have HAProxy node setup to route requests to 3 **rancher/server** nodes. The proxy also does SSL termination.

The UI for **rancher/server** worked without issue. **rancher/server** was also started with the custom CA certificate via the `-v <some-dir>/certfile.crt:/var/lib/rancher/etc/ssl/ca.crt`
When trying to add a host the initial container that pulls configs from rancher/server always errored out stating it wasn't able to connect to https URL.

The only output from the rancher-agent container is:
```shell
Updating certificates in /etc/ssl/certs...
WARNING: rancherAddedCA.pem does not contain a certificate or CRL: skipping
1 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
Found container ID: 47a9edf85039306a5f293e0d4c3a1f5c0c43cf7a22a65f15e24caad4530d2970
Checking root: /host/run/runc
Checking file: 47a9edf85039306a5f293e0d4c3a1f5c0c43cf7a22a65f15e24caad4530d2970
Found state.json: 47a9edf85039306a5f293e0d4c3a1f5c0c43cf7a22a65f15e24caad4530d2970
time="2017-04-12T18:46:30Z" level=info msg="Execing [/usr/bin/nsenter --mount=/proc/17434/ns/mnt -F -- /var/lib/docker/overlay/8ccb117f367d70b3cb7759029ef0254dfa31bf49e9946752b17146661acaf451/merged/usr/bin/share-mnt --stage2 /var/lib/rancher/volumes /var/lib/kubelet -- norun]" 
Found container ID: 47a9edf85039306a5f293e0d4c3a1f5c0c43cf7a22a65f15e24caad4530d2970
Checking root: /run/runc
Checking file: 47a9edf85039306a5f293e0d4c3a1f5c0c43cf7a22a65f15e24caad4530d2970
Found state.json: 47a9edf85039306a5f293e0d4c3a1f5c0c43cf7a22a65f15e24caad4530d2970
INFO: Starting agent for 2AFA257F05E22220C007
INFO: Starting agent for 2AFA257F05E22220C007
INFO: Starting agent for 2AFA257F05E22220C007
INFO: Starting agent for 2AFA257F05E22220C007
INFO: Starting agent for 2AFA257F05E22220C007
INFO: Starting agent for 2AFA257F05E22220C007
INFO: Starting agent for 2AFA257F05E22220C007
INFO: Starting agent for 2AFA257F05E22220C007
INFO: Starting agent for 2AFA257F05E22220C007
INFO: Starting agent for 2AFA257F05E22220C007
INFO: Starting agent for 2AFA257F05E22220C007
INFO: Starting agent for 2AFA257F05E22220C007
```

It continue like that for some time and then exits.

No relevant logs from any rancher/server that I can see

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.5.3` Cattle: `v0.177.10` UI: `v1.5.8` |
|Access|`ldap` `admin`|
|Orchestration|`Kubernetes`|
|Route|`admin-tab.ha`|

**Comment by aemneina** [comment]
Did you [add the certificate to the agent host](https://docs.rancher.com/rancher/v1.5/en/installing-rancher/installing-server/basic-ssl-config/#adding-hosts) trying to connect to the rancher server?

**Comment by nwlucas** [comment]
I added to the initial script line that the rancher server prodived when
you do the "Add Host" that script ran without issue and starts the
rancher-agent automatically.

How do I add the CA file to the agent after it has been started already?

**Comment by nwlucas** [comment]
Nvm misread the last few lines of that document and I will try that in the morning and report if it was successful

**Comment by aemneina** [comment]
Better logging message for the agent when it cant connect to the rancher server. Covers the case where self signed certs are in play.

**Comment by rocketeer125** [comment]
I have found often that you have to clear down /var/lib/rancher on the agent docker-engine when you are making changes like this.

**Comment by janeczku** [comment]
@aemneina agent log issue is tracked here: https://github.com/rancher/rancher/pull/8452

**Comment by superseb** [comment]
This has been resolved.
