### ISSUE TITLE
Cattle Scheduler (0.7.5) no longer working correctly

### ISSUE THREAD

**Issue by nhumrich** [rancher/rancher#8493]
**Rancher Versions:**
Server: 1.5.3
healthcheck: 0.2.3
ipsec: holder
network-services: metadata:v0.9.1, network-manager:v0.6.6
scheduler: 0.7.5

**Docker Version:** 
1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu, AWS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA Rancher, 2 nodes. 

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Issue:**
The Scheduler no longer seams to "balance" containers across hosts. The "should not" rule doesnt seem to do anything anymore.

**Steps to Reproduce:**
Add a single host to rancher. add a couple services and scale them all 2. Create a second host. Once the host is healthy, start upgrading services. 
Next, when upgrading a specific service, add a `host - should not - have a service with the name - {name of current service}

**Results:** 
The containers will keep deploying to the first host and will not move over to the second host ever, even after adding the should not rule.
The only way to get them to move over to the other host is to add the MUST NOT rule. Even then, it tries to schedule initially on the same host, but then fails. On the retry it then finally puts a container on the second host.

**Comment by superseb** [comment]
I don't think this applies anymore, let us know if it still present on the latest version.
