### ISSUE TITLE
kubelet initialization: no such file or directory errors

### ISSUE THREAD

**Issue by joshwget** [rancher/rancher#8495]
@danielfn wrote:

Original issue: https://github.com/rancher/rancher/issues/7252

Seems that entry.sh is removing mount points that are needed for kubelet. I think that this issue stems from this recent commit:

https://github.com/rancher/kubernetes-package/commit/6471676a7ed98b910813447628abe81c3e73375a

My kubelet container logs:
```
+ for i in '$(DOCKER_API_VERSION=1.22 ./docker info 2>&1  | grep -i '\''docker root dir'\'' | cut -f2 -d:)' /var/lib/docker /run /var/run
++ grep '^/var/lib/docker/'
++ awk '{print $2}'
++ tac /proc/mounts
...
+ for m in '$(tac /proc/mounts | awk '\''{print $2}'\'' | grep ^${i}/)'
+ umount /var/lib/docker/aufs/mnt/8e01638295032725248e8fab5c586e871129871d87088dd181fef9fc6fb717cb/sys/fs/cgroup/memory
+ for m in '$(tac /proc/mounts | awk '\''{print $2}'\'' | grep ^${i}/)'
+ umount /var/lib/docker/aufs/mnt/8e01638295032725248e8fab5c586e871129871d87088dd181fef9fc6fb717cb/sys/fs/cgroup/cpuset
+ for m in '$(tac /proc/mounts | awk '\''{print $2}'\'' | grep ^${i}/)'
+ umount /var/lib/docker/aufs/mnt/8e01638295032725248e8fab5c586e871129871d87088dd181fef9fc6fb717cb/sys/fs/cgroup
+ for m in '$(tac /proc/mounts | awk '\''{print $2}'\'' | grep ^${i}/)'
+ umount /var/lib/docker/aufs/mnt/8e01638295032725248e8fab5c586e871129871d87088dd181fef9fc6fb717cb/sys
...
F0105 07:55:53.905924   24138 kubelet.go:1210] Failed to start cAdvisor inotify_add_watch /var/lib/docker/aufs/mnt/8e01638295032725248e8fab5c586e871129871d87088dd181fef9fc6fb717cb/sys/fs/cgroup/memory: no such file or director

```
More info about my environment:
* Linux rancher-agent1 4.4.39-boot2docker SMP Thu Dec 15 17:43:51 UTC 2016 x86_64 GNU/Linux
* docker version: 1.12.5
* rancher/k8s v1.5.1-rancher1-7
* rancher/agent v1.1.3

[kubelet-full-log.txt](https://github.com/rancher/kubernetes-package/files/686972/kubelet-full-log.txt)

@ibuildthecloud responded: 

We are looking for a solution to this.  On the one hand cadvisor wants to look at container mounts, but on the other hand that has the tendency to fail container delete and orphan assets.  So neither is ideal.  We unmount all the `/var/lib/docker` folders in order to prevent `DEAD` containers in Docker.

Also, unfortunately Rancher has never supported Docker 1.11. We went from 1.10 to 1.12+. 1.11 had too many issues. 1.12 had a lot of issues but eventually got fixed in 1.12.x releases.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
