### ISSUE TITLE
Not allowed to use volumes with scope External unless a volume entry is created.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#8497]
Rancher server - Build from master

Steps to reproduce the problem:
Create a stack with docker compose file having volume with scope External.
Stack creation fails with ```Error (Volume hello declared as external, but could not be found. Please create the volume manually and try again.)```
 
I had to create a volume entry , before i could use it in compose file to create stacks.

Expected Behavior:
We should be allowed to user volumes with scope External without having to create a volume entry in rancher server ? in master builds, i am not allowed to do this .

**Comment by sangeethah** [comment]
Tested with latest build from master - Apr 17 .

When creating a service with volume set to external: true , volume get created with scope stack.
yml use to create the stack:

```
version: '2'
services:
  nginx5:
    image: nginx
    volumes:
    - yello1:/data1

volumes:
  yello1:
    external: true
    driver: rancher-nfs
```

volume template craeted has external set to "false"
```
{
"id": "1vt2",
"type": "volumeTemplate",
"links": {
"self": "…/v2-beta/projects/1a5/volumetemplates/1vt2",
"account": "…/v2-beta/projects/1a5/volumetemplates/1vt2/account",
"stack": "…/v2-beta/projects/1a5/volumetemplates/1vt2/stack",
"volumes": "…/v2-beta/projects/1a5/volumetemplates/1vt2/volumes",
},
"actions": {
"activate": "…/v2-beta/projects/1a5/volumetemplates/1vt2/?action=activate",
"update": "…/v2-beta/projects/1a5/volumetemplates/1vt2/?action=update",
"remove": "…/v2-beta/projects/1a5/volumetemplates/1vt2/?action=remove",
},
"baseType": "volumeTemplate",
"name": "yello1",
"state": "inactive",
"accountId": "1a5",
"created": "2017-04-18T16:33:41Z",
"createdTS": 1492533221000,
"description": null,
"driver": "rancher-nfs",
"driverOpts": null,
"external": false,
"kind": "volumeTemplate",
"perContainer": false,
"removed": null,
"stackId": "1st10",
"transitioning": "no",
"transitioningMessage": null,
"transitioningProgress": null,
"uuid": "5b15827e-a9d9-460d-9e83-71603378a274",
},
```

**Comment by jrosengren** [comment]
I was bit by this bug today as I was launching new stacks.  Is there any way this could get into 1.5.6 instead of waiting for 1.6.0?

**Comment by untoldone** [comment]
Would this type of fix give a workaround for https://forums.rancher.com/t/java-illegalstateexception-more-than-one-volume-exists-for-volume-uri/6216? I'm not 100% sure, but it looks like `1.2.0` broke prior behavior around using Docker Volume drivers from composing files (or I'm looking at a separate, unrelated, issue).

My expectation was that a docker-compose v1 file would behave like `external: true`, however, I believe it currently does stack-scoped behavior, where it expects to create a volume. Pre-1.2.0, no form of action would take place outside of docker mounting the volume. That said, a workaround for this breaking change would be to migrate to docker-compose version 2 with `external: true` ... however, if you use a Docker Volume Driver (rather than the Rancher Storage Drivers) you'll get this error message.

All this said, I might be miss-interpreting the code I've been reading + not have a good handle on the actual history here.

**Comment by SamMousa** [comment]
I dont think this is a bug.
https://docs.rancher.com/rancher/v1.5/en/rancher-services/storage-service/#environment-scoped-1

It is explicitly documented.

**Comment by deniseschannon** [comment]
Verified with rancher-compose-executor v0.14.4. 

```
version: '2'
services:
  nginx5:
    image: nginx
    volumes:
    - yello1:/data1

volumes:
  yello1:
    external: true
    driver: rancher-nfs
```

```

"id": "1vt1",
"type": "volumeTemplate",
"links": {
"self": "…/v2-beta/volumetemplates/1vt1",
"account": "…/v2-beta/volumetemplates/1vt1/account",
"volumes": "…/v2-beta/volumetemplates/1vt1/volumes",
},
"actions": {
"activate": "…/v2-beta/volumetemplates/1vt1/?action=activate",
"update": "…/v2-beta/volumetemplates/1vt1/?action=update",
"remove": "…/v2-beta/volumetemplates/1vt1/?action=remove",
},
"baseType": "volumeTemplate",
"name": "yello1",
"state": "inactive",
"accountId": "1a5",
"created": "2017-05-01T22:25:40Z",
"createdTS": 1493677540000,
"data": { },
"description": null,
"driver": "rancher-nfs",
"driverOpts": null,
"external": true,
"kind": "volumeTemplate",
"perContainer": false,
"removeTime": null,
"removed": null,
"stackId": null,
"transitioning": "no",
"transitioningMessage": null,
"transitioningProgress": null,
"uuid": "3cd4def8-6c0c-43f7-b08f-00d24752a8b9",
},
],
"sortLinks": {
"accountId": "…/v2-beta/volumetemplates?sort=accountId",
"created": "…/v2-beta/volumetemplates?sort=created",
"description": "…/v2-beta/volumetemplates?sort=description",
"driver": "…/v2-beta/volumetemplates?sort=driver",
"external": "…/v2-beta/volumetemplates?sort=external",
"id": "…/v2-beta/volumetemplates?sort=id",
"kind": "…/v2-beta/volumetemplates?sort=kind",
"name": "…/v2-beta/volumetemplates?sort=name",
"perContainer": "…/v2-beta/volumetemplates?sort=perContainer",
"removeTime": "…/v2-beta/volumetemplates?sort=removeTime",
"removed": "…/v2-beta/volumetemplates?sort=removed",
"stackId": "…/v2-beta/volumetemplates?sort=stackId",
"state": "…/v2-beta/volumetemplates?sort=state",
"uuid": "…/v2-beta/volumetemplates?sort=uuid",
```

**Comment by soumyalj** [comment]
I see the same issue for rancher-ebs. Creating a service with new volume using external=true, creates the volume at stack level scope:
```
version: '2'
services:
  foo:
    image: ubuntu
    stdin_open: true
    scale: 2
    volumes:
    - soumyatestvol2:/mydata
volumes:
  soumyatestvol2:
    external: true
    driver: rancher-ebs
    driver_opts:
      size: '5'


```

**Comment by sangeethah** [comment]
Tested with rancher-server version -  1.6.0-rc3 and v0.6.0-rc5

Create a service with volume that does not exist in rancher side with the following yml .
service creation succeeds , but the volume gets created as native docker volume with no volumetemplate associated with it.

 ```version: '2'
volumes:
  test123:
    external: true
    driver: rancher-nfs
services:
  testyello:
    image: ubuntu:14.04.3
    stdin_open: true
    volumes:
    - test123:/testdata```

[5:05] 
 ```Sangeethas-MBP:rancher-v0.6.0-rc5 sangeethahariharan1$ ./rancher up -f dc.yml
INFO[0002] Creating stack rancher-v0-6-0-rc5            
INFO[0002] Creating volume template test123             
INFO[0002] [testyello]: Creating                        
INFO[0002] Creating service testyello                   
INFO[0002] [testyello]: Created                         
INFO[0002] Existing volume template found for test123   
INFO[0002] [testyello]: Starting                        
INFO[0010] [testyello]: Started ```

Volume details
```
{
"id": "1v2669",
"type": "volume",
"links": {
"self": "…/v2-beta/projects/1a5/volumes/1v2669",
"account": "…/v2-beta/projects/1a5/volumes/1v2669/account",
"backups": "…/v2-beta/projects/1a5/volumes/1v2669/backups",
"image": "…/v2-beta/projects/1a5/volumes/1v2669/image",
"instance": "…/v2-beta/projects/1a5/volumes/1v2669/instance",
"mounts": "…/v2-beta/projects/1a5/volumes/1v2669/mounts",
"snapshots": "…/v2-beta/projects/1a5/volumes/1v2669/snapshots",
"storagePools": "…/v2-beta/projects/1a5/volumes/1v2669/storagepools"
},
"actions": {
"deallocate": "…/v2-beta/projects/1a5/volumes/1v2669/?action=deallocate",
"update": "…/v2-beta/projects/1a5/volumes/1v2669/?action=update"
},
"baseType": "volume",
"name": null,
"state": "active",
"accessMode": null,
"accountId": "1a5",
"created": "2017-05-02T23:50:27Z",
"createdTS": 1493769027000,
"description": null,
"driver": null,
"driverOpts": null,
"externalId": null,
"hostId": null,
"imageId": "1i1563",
"instanceId": "1i1564",
"isHostPath": false,
"kind": "volume",
"mounts": null,
"removed": null,
"sizeMb": null,
"stackId": null,
"storageDriverId": null,
"transitioning": "no",
"transitioningMessage": null,
"transitioningProgress": null,
"uri": null,
"uuid": "27732f9d-e489-437b-b152-5fcdc53a6bd7",
"volumeTemplateId": null
}
```

**Comment by sangeethah** [comment]
Tested with rancher-server version - 1.6.0-rc4

Scenario 1:
Create a service with volume with scope external that does not exist in rancher side.
Service creation fails with following error - ```Failed to locate volume for instance of deployment unit [17f2453a-c895-4721-a22e-ae5ac95a4915]:```

In this case volumeTemplayte gets created but volume does not get created.

Scenario 2:
Create a volume from UI after which volume is in "inactive" state.
Create a service with this volume with scope external.
Service creation succeeds and the existing volume in rancher-server gets used by the containers of the service.

Sample yml used:
```
version: '2'
volumes:
 test123:
   external: true
   driver: rancher-nfs
services:
 testyello:
   image: ubuntu:14.04.3
   stdin_open: true
   volumes:
   - test123:/testdata
```

**Comment by checksrc** [comment]
+1 for this issue upon rancher-compose - (Failed to locate volume for instance of deployment unit [51f2fa31-d935-48bf-bcea-cd6f31b51005]: )

**Comment by deniseschannon** [comment]
@checksrc This is expected error that you'd see. In order to use an environment scoped volume in a volume template, you'd need to create the volume in Rancher beforehand (either through the UI or create a volume on your service without specifying a volume template (something under the `volumes` key). We are working on docs to make this more clear to our users.

**Comment by knepperjm** [comment]
@deniseschannon (yes/no?) can we not name external volumes in Rancher scoped at the environment-level?   I have created the following volumes on my host using the rexray create volume command line, and still get the above error.

`version: '2' 
services:
  influxdb:
    image: "demandbase/influxdb:${DOCKER_TAG}"
    ports:
     - "20026:8083"
     - "8086:8086"
     - "8088:8088"
     - "8089:8089/udp"
     - "25826:25826"
     - "2003:2003"
    labels:
      io.rancher.scheduler.affinity:host_label: cluster-type=memory
      io.rancher.container.pull_image: always
      io.rancher.container.start_once: 'true'
      io.rancher.stack.name: "demandbase/influxdb:${DOCKER_TAG}"
      com.demandbase.environment: "$ENVIRONMENT"
    environment:
      - INACTIVITY_TIMEOUT=5m 
      - INFLUXDB_BACKUP=${INFLUXDB_BACKUP}
    volume_driver: rexray
    volumes:
      - influxdb:/var/lib/influxdb
    restart: always
    tty: true
    stdin_open: true
volumes:
  influxdb:
    driver: rexray
    external: true`

**Comment by BlackBurn83** [comment]
@deniseschannon maybe I missed something, but why not automatically create the volume if it is environment scoped, instead of first manually create them in UI?

**Comment by vishnuvpotty** [comment]
I am having this issue in  rancher-server version - v1.6.5 .
Any solutions/ workarounds.

**Comment by jinghuaz** [comment]
1.6.10 still error:
Expected state running but got error: Error response from daemon: Get https://docker-registry.patsnap.com/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

**Comment by BarryOwens** [comment]
I'm using the following syntax in my docker-compose file: 
```volumes:
  backups:
    driver: rancher-ebs
    external:
      name: backups_production # This would be passed as an env variable
```

When I do this I get the error "Failed to locate volume for instance of deployment unit"
And when I check the docker-compose file in rancher it has become:
``` backups:
    driver: rancher-ebs
    external: true
```

Looking at https://github.com/rancher/rancher-compose-executor/pull/49 it looks like it just ignores any external configuration and instead just uses `external: true`. Is this expected?
