### ISSUE TITLE
rancher-nfs: When detached volumes are deleted in quick succession , volumes do not get deleted from nfs server.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#8498]
Rancher Versions: v1.5.4

Steps to reproduce the problem:
Deploy nfs driver.
Create a service with volume - vol1 in nfs driver.
Delete the service. This will result in vol1 being in "detached" state.
Repeat the above steps so that you have few ( ~5 ) volumes in "detached" state.
Delete all the 5 volumes in "detached" state one after the other in quick succession.

All volumes get deleted in the rancher-side.
Notice that only couple of volumes get actually deleted form nfs-server.

Expected Behavior:
All volumes should get deleted from nfs-server.

**Comment by sangeethah** [comment]
agent logs and nfs driver logs - 
[nfslogs.zip](https://github.com/rancher/rancher/files/1012798/nfslogs.zip)

**Comment by cjellick** [comment]
NOTE: Fix is for 2.0 only. Need completely different fix for 1.6

**Comment by claytonsilva** [comment]
This problem occur on TinyCore Linux and boot2docker ( for vmware Vcenter ).

Is there any workaround to work rancher-nfs with this limitation? 

manual install of plugin on host ... or other  solution.
