### ISSUE TITLE
New feature request

### ISSUE THREAD

**Issue by aleksejlopasov** [rancher/rancher#8499]
Hi,
According to issue #8292 there is no way to filter users using OpenLDAP authentication. Could you add this feature to rancher?
It's ridiculous to permit login all users, that are present in LDAP directory.  
Thanks

**Comment by vincent99** [comment]
a) If you already know (and created yourself, in this case) there's an issue for something, intentionally making a duplicate is not helpful.

b) "Login" is not at all the same "and have access to any environments".  Users that are not a member of an environment (or a member of a group which is) will see nothing but a new empty environment created for them.
