### ISSUE TITLE
Scheduling One Instance of Service Per-Host

### ISSUE THREAD

**Issue by RonWilliams** [rancher/rancher#8502]
**Rancher Versions:**
Server: 1.4
scheduler: 0.6.3	

**Docker Version:**
1.12.6

We have 5 cattle hosts running several stacks. I'd like to configure an apache service on each host. I have set the service scale to 5 and the set scheduling to the following rule:

The host "should not" have a "service with the name" [stack-name]/apache. This seems to work and the hosts each have one instance of Apache. Is there any issue with having a circular scheduling reference?

**Comment by StrongMonkey** [comment]
maybe you should check out this http://docs.rancher.com/rancher/v1.5/en/cattle/scheduling/#global-service

**Comment by aemneina** [comment]
@RonWilliams no issue using that scheduling rule in that way. Thats one of its intended uses... anti-affinity of containers within the same service.

**Comment by RonWilliams** [comment]
@aemneina Thanks for the confirmation. 

@StrongMonkey Good suggestion. I have some cases where I run 3 Apache instance on the 5 hosts and I don't want 2 of instances running on the same host. Hopefully someone runs across this topic for scheduling.

**Comment by deniseschannon** [comment]
@RonWilliams You are trying to achieve anti-affinity to itself when scheduling services. 

If you use rancher-compose, you can add a label: 

http://docs.rancher.com/rancher/v1.5/en/cattle/scheduling/#example-1

```
labels:
  io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
```

In the UI, in the scheduling tab, you could select "must not" have a "service name" and then in the text box for the value, you would put the stack name and service name. 

So if you were creating "serviceA" in the "foo" stack, you would put `foo/serviceA` in the text box.

**Comment by perlun** [comment]
It's even easier today to apply @deniseschannon 's advice, since you don't even have to type in the service name - there is now a friendly UI dropdown where you can just pick the service.
