### ISSUE TITLE
UI Issues DS

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#8507]
**Rancher Versions:** 4/13

**Issues:** 

- [ ] Can we add an image or something to create new account email?
![image](https://cloud.githubusercontent.com/assets/11514927/25020769/8a9aaf42-2044-11e7-82a9-1edba8720d2f.png)

- [x] Successfully verified email modal needs a bit of cleanup
![image](https://cloud.githubusercontent.com/assets/11514927/25020930/2133937e-2045-11e7-957e-fb34a83849cf.png)

- [x] Add Hosts Favorites empty page -   Need to fix the text.  "You have not favorites."  Should be "You have no favorites."
![image](https://cloud.githubusercontent.com/assets/11514927/25021107/e0060926-2045-11e7-85a1-50911b609742.png)

- [x] Add Host Favorites empty page - The text section when there are no favorites is too thin and doesn't match any other page.
![image](https://cloud.githubusercontent.com/assets/11514927/25021093/d34955a8-2045-11e7-86d6-ae61c857aff3.png)

- [x] Add Host Detail section needs to be redone
![image](https://cloud.githubusercontent.com/assets/11514927/25021173/21b1ca22-2046-11e7-9500-c0dd8c936731.png)

- [ ] New Host key Name title is all lower case.  First letter should be upper case
![image](https://cloud.githubusercontent.com/assets/11514927/25021245/63597b46-2046-11e7-948f-4831398bed45.png)

- [x] New Host Labels section has "Labels" title twice.
![image](https://cloud.githubusercontent.com/assets/11514927/25021279/7f6119c0-2046-11e7-90e5-243e75e01525.png)

- [x] Add Host Favorites - when I move my mouse over favorite or browse, a line appears but it's not aligned
![image](https://cloud.githubusercontent.com/assets/11514927/25026608/0bf3bd42-205c-11e7-9503-bd5285a131de.png)

- [ ] Can't add container when I first get in.  Null stack

- [x] Container navigation jumps when switching between it and other navigation (like scaling groups, LB... etc...)

**Comment by lvuch** [comment]
<img width="547" alt="screen shot 2017-04-13 at 8 36 23 pm" src="https://cloud.githubusercontent.com/assets/3013118/25032439/ee5703fc-2088-11e7-95d8-47a1afb3a7af.png">

When I try to create an account I get and error but the error isn't printing text.

**Comment by lvuch** [comment]
@tfiduccia since the add host screens have changed a few of these I can't track down but let me know if I'm wrong

**Comment by tfiduccia** [comment]
Version: 4/14

Verified all checked were fixed.  removed unchecked one and sent to other bug
