### ISSUE TITLE
Adding users to environments isn't clear

### ISSUE THREAD

**Issue by smw355** [rancher/rancher#851]
When I am in a project, and I click on "access control" it allows me to add a user. My assumption was that adding a new github user would add them to the project I was working in, but it seems that it adds them generally to the system, and creates a private project for them.

To add users to a specific project, I have to go to the manage projects page, and then add users to that project.

**Comment by deniseschannon** [comment]
We designed it so that if you add a user to the project (now environment), they'd automatically be added to the site. it would basically grant them permissions so the site.

@hibooboo2 please correct me if i'm incorrect.

**Comment by hibooboo2** [comment]
@deniseschannon you are correct. Just add them to the environment.

**Comment by vincent99** [comment]
This is also why the list of users for access control is now hidden by default under the Customize button, because you probably don't need to change it.  But some extra text there could make it more obvious what you're doing affects access to the system, not to the environment.

**Comment by deniseschannon** [comment]
With the various changes, I don't believe this has made it more explicitly clear on the environments side (adding members to environments adds them to the site) as well as default would require you to customize who has access to the site. 

v0.51.0
