### ISSUE TITLE
[ui] Network issues cause empty error message.

### ISSUE THREAD

**Issue by SamMousa** [rancher/rancher#8510]
**Rancher Versions:**
Server: 1.5.5

**Steps to Reproduce:**
I noticed I had some DNS trouble, so after logging in the hostname for rancher would not resolve.
When trying to save something I got this:
![image](https://cloud.githubusercontent.com/assets/547021/25040079/943adbe4-2107-11e7-815b-35b84a1ffc89.png)

![image](https://cloud.githubusercontent.com/assets/547021/25040106/bcbcdfea-2107-11e7-9297-a373ce5c044c.png)

**Results:** 
Ideally the front end should detect client side AJAX errors and show a proper error message.

**Comment by deniseschannon** [comment]
Available with `v1.6.15-rc6`

**Comment by tfiduccia** [comment]
Version - v1.6.15-rc8
Verified fixed
