### ISSUE TITLE
catalog template always starts services regardless of start_on_create

### ISSUE THREAD

**Issue by ahaynssen** [rancher/rancher#8514]
**Rancher Versions:**
Server: 1.5.1
scheduler: Cattle

**Docker Version:**
Docker version 1.11.2, build b9f10c9

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu, AWS EC2

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA Rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Create catalog template .yml with `start_on_create: false`
Refresh Catalog and try to deploy catalog template

**Results:** 
Checkbox for "Start services after creating" is always checked 
If I try just ignoring this and depending on my rancher-compose.yml config, I still get the services starting up on creation

If I uncheck manually I get the correct behavior. 

Seems this setting is being ignored

**Comment by cjeanneret** [comment]
Hello,

For information, this is also present in previous versions, at least 1.4.3

Would be great to get some fix on that :).

Cheers,

C.

**Comment by deniseschannon** [comment]
Duplicate of https://github.com/rancher/rancher/issues/7287
