### ISSUE TITLE
Setting net: host results in service deployed in managed network.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#8516]
**Rancher Versions: Build from master
Rancher cli version - rancher-v0.6.0-rc1

Steps to reproduce the problem:
Creating service from rancher cli using the following compose file results in service created with managed network

```
$ cat dc_metadata_hostnet.yml 
testhostdns:
  labels:
    io.rancher.container.dns: 'true'
  tty: true
  image: sangeetha/testclient33:latest
  stdin_open: true
  net: host
$ cat rc_metadata_hostnet.yml 
testhostdns:
  scale: 3

```

**Comment by deniseschannon** [comment]
This is a regression from Rancher CLI v0.5.2. 

If I use the same compose files in v1.5.5, the service is set to `networkMode: Host` in the API.

**Comment by deniseschannon** [comment]
This is specifically broken if you have a rancher-compose.yml with the same service. If you create the service with no rancher-compose.yml, it works as expected.

**Comment by deniseschannon** [comment]
Verified in master 4/27 with rancher-compose-executor v0.14.3.
