### ISSUE TITLE
WebHooks for services don't work

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#8519]
**Rancher Versions:** 4/14

**Steps to Reproduce:**
1.  Create a scaling group and add a container
2.  Try to add a webhook to the service

**Results:** 	Can only create webhooks for Services. The supplied service is of type scalingGroup
![image](https://cloud.githubusercontent.com/assets/11514927/25057934/6b89050a-2129-11e7-8833-9fa6a4f384f5.png)

**Comment by carolynhu** [comment]
@deniseschannon "service" is not changing to "scalingGroup" anymore
