### ISSUE TITLE
feature: catalog entries with host affinity tags

### ISSUE THREAD

**Issue by kgk** [rancher/rancher#8520]
**Rancher Versions:**
Server: 1.5.4
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker Version:**
1.13

**OS and where are the hosts located? (cloud, bare metal, etc):**

bare metal

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle 

**Steps to Reproduce:**

There is currently no way to give scheduling suggestions to catalog entries. Specifically I would like to add host affinity tags to the containers started so I can control where the catalog entry containers are going to be deployed.   

My  current method is to hack up the catalog entry into a docker-compose/rancher-compose and deploy from the command line, which is less than ideal.

**Comment by tfiduccia** [comment]
@kgk I have utilized  'io.rancher.scheduler.affinity:host_label: foo=bar' type rule in my docker-compose.ym. for a catalog to get a container to go to a specific host and it worked fine.  Is there something else you are trying to do?

**Comment by kkvilekval** [comment]
that's the point.. you have to make your own.. I was wondering about adding labels to catalog entry without needing to edit the actual docker-compose file.

**Comment by aemneina** [comment]
yeah, you'll need to clone and maintain customizations to templates.
