### ISSUE TITLE
[HA] All Hosts in state "Disconnected"

### ISSUE THREAD

**Issue by akafrmn** [rancher/rancher#8522]
Setup: v1.5.5
Servers: 3x in ha behing load balancer
db: xtradb 3x percona 5.7

After stop all instances and up them one by one. All connected hosts become in state "Disconnected". From load balancer all them recieve 403 http error from rancher servers.

<IP> - 71758952B0AB72E969E3 [16/Apr/2017:11:29:37 +0000] "POST /v1/serviceevents HTTP/1.1" 403 167 "-" "Go-http-client/1.1"
<IP> - 6908ABF511BE5D594255 [16/Apr/2017:11:29:37 +0000] "POST /v1/serviceevents HTTP/1.1" 403 168 "-" "Go-http-client/1.1"
<IP> - F60203C477F6107672AE [16/Apr/2017:11:29:37 +0000] "GET /v1/schemas/configcontent HTTP/1.1" 401 177 "-" "curl/7.47.0"

<IP> - 71758952B0AB72E969E3 [16/Apr/2017:11:29:37 +0000] "POST /v1/serviceevents HTTP/1.1" 403 167 "-" "Go-http-client/1.1"
<IP> - 6908ABF511BE5D594255 [16/Apr/2017:11:29:37 +0000] "POST /v1/serviceevents HTTP/1.1" 403 168 "-" "Go-http-client/1.1"
<IP> - F60203C477F6107672AE [16/Apr/2017:11:29:37 +0000] "GET /v1/schemas/configcontent HTTP/1.1" 401 177 "-" "curl/7.47.0"
<IP> - 09832FCAEB798EB994F6 [16/Apr/2017:11:29:37 +0000] "POST /v1/serviceevents HTTP/1.1" 403 168 "-" "Go-http-client/1.1"
<IP> - 08F0B1C7E93276621766 [16/Apr/2017:11:29:37 +0000] "POST /v1/serviceevents HTTP/1.1" 403 167 "-" "Go-http-client/1.1"
<IP>6 - EBC2C9349C8097B7CE5D [16/Apr/2017:11:29:37 +0000] "POST /v1/serviceevents HTTP/1.1" 403 168 "-" "Go-http-client/1.1"
<IP> - 85726D1154E14A283698 [16/Apr/2017:11:29:37 +0000] "POST /v2-beta/publish HTTP/1.1" 201 0 "-" "Go-http-client/1.1"
<IP> - BD3B6C7D5325AD4F0CC6 [16/Apr/2017:11:29:37 +0000] "POST /v2-beta/publish HTTP/1.1" 201 0 "-" "Go-http-client/1.1"
<IP> - 8642F38F983750076713 [16/Apr/2017:11:29:37 +0000] "POST /v2-beta/publish HTTP/1.1" 201 0 "-" "Go-http-client/1.1"
<IP> - B06F244348C2D97305F8 [16/Apr/2017:11:29:37 +0000] "POST /v2-beta/publish HTTP/1.1" 201 0 "-" "Go-http-client/1.1"
<IP> - E59225FB7D5009500388 [16/Apr/2017:11:29:37 +0000] "POST /v2-beta/publish HTTP/1.1" 201 0 "-" "Go-http-client/1.1"
<IP> - D2CEBE3693224B29072B [16/Apr/2017:11:29:37 +0000] "POST /v2-beta/publish HTTP/1.1" 201 0 "-" "Go-http-client/1.1"
3<IP> - A4655C200FBF7B3536FD [16/Apr/2017:11:29:37 +0000] "POST /v1/serviceevents HTTP/1.1" 403 168 "-" "Go-http-client/1.1"
<IP> - 68BB91CDB692D7ED6EC1 [16/Apr/2017:11:29:37 +0000] "POST /v2-beta/publish HTTP/1.1" 201 0 "-" "Go-http-client/1.1"
<IP> - 64B559533A652D5327C4 [16/Apr/2017:11:29:37 +0000] "POST /v2-beta/publish HTTP/1.1" 201 0 "-" "Go-http-client/1.1"
<IP> - D53C84F3DDAE438A033D [16/Apr/2017:11:29:37 +0000] "POST /v2-beta/publish HTTP/1.1" 201 0 "-" "Go-http-client/1.1"
<IP> - 081C7B45071E4E3CD191 [16/Apr/2017:11:29:37 +0000] "POST /v2-beta/publish HTTP/1.1" 201 0 "-" "Go-http-client/1.1"
<IP>- 3B9FE2B63116EDD45413 [16/Apr/2017:11:29:37 +0000] "POST /v1/serviceevents HTTP/1.1" 403 167 "-" "Go-http-client/1.1"
<IP> - 6D57DB1E23DFC05BF9BF [16/Apr/2017:11:29:38 +0000] "POST /v1/serviceevents HTTP/1.1" 403 169 "-" "Go-http-client/1.1"

Same for ssl connections:

<IP> - A64FEC060B87166C9627 [16/Apr/2017:11:29:37 +0000] "POST /v1/serviceevents HTTP/2.0" 403 432 "-" "Go-http-client/2.0"
<IP> - 7E19AA26A2A02EE06457 [16/Apr/2017:11:29:37 +0000] "POST /v1/serviceevents HTTP/2.0" 403 433 "-" "Go-http-client/2.0"
<IP> - E884299754C621225E82 [16/Apr/2017:11:29:37 +0000] "POST /v1/serviceevents HTTP/2.0" 403 431 "-" "Go-http-client/2.0"

No errors in debug log on each of backend rancher server. So i cannot verify problem.
Very critical for us as we have large amount of nodes connected :(
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.5.5` Cattle: `v0.178.2` UI: `v1.5.8` |
|Access|`Disabled`|
|Orchestration|`Cattle`|
|Route|`stacks.index`|

**Comment by akafrmn** [comment]
level=error msg="Failed to report status 11bf57f8-8be1-4e4f-a701-c54169d5676c_ede7c0f6-e616-40d7-a9bc-bcee46cbf94b_1=DOWN: Bad response from [http://<RANCHER-SERVER>:8080/v1/serviceevents], statusCode [403]. Status [403 Forbidden]. Body: [{\"id\":\"65e2adc0-f364-4bd6-ac33-dfc93be4d9ef\",\"type\":\"error\",\"links\":{},\"actions\":{},\"status\":403,\"code\":\"CantVerifyHealthcheck\",\"message\":\"CantVerifyHealthcheck\",\"detail\":null,\"baseType\":\"error\"}]"

here is log from any healthcheck service on nodes

**Comment by aemneina** [comment]
whats in the rancher/server container logs? What LB do you have in front of rancher/

**Comment by akafrmn** [comment]
Rancher server did not contains any error/fatal logs while this happens. We are using nginx 1.11 with recommended configuration from documentation.

**Comment by kleinsasserm** [comment]
We are facing the same problem. All hosts are disconnected an we are using the documented nginx configuration. We have a test-rancher environment which is completely disconnected. A productive-rancher environment is full functional. After rebooting one of the hosts, it came back active.

Log Output example from rancher-agent. There may be a problem with the nginx configuration and or the HA-rancher servers.

As I told, after rebooting the hosts all is green!

```
time="2017-05-03T08:21:46Z" level=info msg="Connecting to proxy." url="wss://rt.xx.xx.com/v1/connectbackend?token="xxxxxxxxxxxxxxxxx"
time="2017-05-03T08:21:51Z" level=warning msg="Hit websocket pong timeout. Last websocket ping received at 2017-05-03 08:21:36.503470521 +0000 UTC. Closing connection." 
time="2017-05-03T08:23:36Z" level=error msg="Received error reading from socket. Exiting." error="read tcp 10.xxxxxxxx:42416->10.xxxxxxxx:443: read: connection reset by peer" 
time="2017-05-03T08:23:36Z" level=error msg="read tcp 10.xxxxxx:42416->10.xxxxxxxx:443: read: connection reset by peer" ```

**Comment by cjellick** [comment]
What is your last log from @kleinsasserm? Before or after you reboot?

**Comment by superseb** [comment]
Please file a new issue if you are still encountering problems.

**Comment by behroozam** [comment]
I dont have any lb front rancher server , but i have same problem on ha implementation on centos , after a while hosts become dissconected and they work and i can excute shell or see logs but i dont have any stats or healthcheck
