### ISSUE TITLE
Failed to install kubernetes stack using rancher cli

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#8526]
**Rancher Versions:**
Server: v1.5.5

**Steps to Reproduce:**
- Run the following command against rancher environment:
```
rancher --wait-state active --debug --env Default catalog install library/k8s:v1.5.4-rancher1-1 --answers answers.txt --name kubernetes --system
```
**Results:** 
The kubernetes stack is created with no services.

I think the problem is that the docker-compose file is now called `docker-compose.yml.tpl` instead of `docker-compose.yml`, and the cli only reference the .yml extension https://github.com/rancher/cli/blob/master/cmd/catalog.go#L276

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
