### ISSUE TITLE
[cli] What is the tag v0.5.2 for?

### ISSUE THREAD

**Issue by bfontaine** [rancher/rancher#8529]
Hello there,
The last two tags on the rancher/cli repo point to the same commit. One is [v0.5.2-rc1](https://github.com/rancher/cli/tree/v0.5.2-rc1), listed as a [pre-release](https://github.com/rancher/cli/releases), and the other is [v0.5.2](https://github.com/rancher/cli/tree/v0.5.2), not listed on the releases page. What is the latter for? Does this mean v0.5.2 is the latest stable release?

**Comment by deniseschannon** [comment]
This should be updated now. We forgot to release the artifacts in our github repo.

**Comment by bfontaine** [comment]
Thanks!
