### ISSUE TITLE
Kubernetes cannot pull from private DockerHub readonly repositories

### ISSUE THREAD

**Issue by bluemalkin** [rancher/rancher#8533]
**Rancher Versions:**
Server: v1.5.5

**Environment Type:**
Kubernetes

**Steps to Reproduce:**
Create an user in DockerHub, add to a team then add the team as a "readonly" Collaborator on the private repository.

**Results:** 
Kubernetes cannot pull the image(s)
`Failed to pull image "PRIVATEREPO/IMAGE-NAME:TAG": Error: image PRIVATEREPO/IMAGE-NAME:TAG not found`

If the DockerHub user is moved to the "owners" team it works without issues.

It might be a bug with Kubernetes itself ?

**Comment by superseb** [comment]
Is this still a thing @bluemalkin ?

**Comment by superseb** [comment]
Let us know if this needs work.
