### ISSUE TITLE
Got error: Failed to find rancher-agent container in adding host from Cloud provider (DigitalOcean)

### ISSUE THREAD

**Issue by maestrofx** [rancher/rancher#8534]
**Docker Version:**
Version:      17.03.1-ce

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04 | Baremetal

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
- single node rancher with internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
-
**Steps to Reproduce:**
- install Rancher management platform
- add host with cloud driver - DigitalOcean
got error `Failed to find rancher-agent container`
more detail error:
`

> "digitaloceanConfig": {
> "accessToken": "ACCESS_KEY_TOKEN",
> "image": "ubuntu-16-04-x64",
> "region": "sgp1",
> "size": "512mb",
> "sshKeyFingerprint": "",
> "sshKeyPath": "",
> "sshPort": "22",
> "sshUser": "root",
> "userdata": "",
> "privateNetworking": true,
> "backups": false
> },
> "dockerVersion": null,
> "driver": "digitalocean",
> "engineEnv": { },
> "engineInsecureRegistry": [ ],
> "engineInstallUrl": "https://releases.rancher.com/install-docker/1.12.sh",
> "engineLabel": { },
> "engineOpt": { },
> "engineRegistryMirror": [ ],
> "engineStorageDriver": "",
> "hostTemplateId": null,
> "hostname": "do-dev-01",
> "info": null,
> "instanceIds": null,
> "kind": "host",
> "labels": { },
> "localStorageMb": null,
> "memory": 536870912,
> "milliCpu": 0,
> "packetConfig": null,
> "physicalHostId": "1ph5",
> "publicEndpoints": null,
> "removed": null,
> "stackId": null,
> "transitioning": "error",
> "transitioningMessage": "Failed to find rancher-agent container",
> "transitioningProgress": null,
> "uuid": "66763fef-188c-4587-aacf-a73326002a1c"
> }

`

Any help, thank you.

**Comment by cdgraff** [comment]
I got into the same issue, the problem was the agent can't access to Rancher UI url, for the Firewall, in my case using AWS, after open the port to the correct IPs and rebuild all work as expected

**Comment by maestrofx** [comment]
Hi @cdgraff ,
can you elaborate about the solution?
In my case, the rancher UI (server) runs behind ELB and the security group opens only to https(443) proxied to rancher_server:8080.

Any help, please!

**Comment by cjellick** [comment]
@maestrofx if you are running behind an ELB, did you follow the procedure for setting up proxy protocol?
https://docs.rancher.com/rancher/v1.6/en/installing-rancher/installing-server/#running-rancher-server-behind-an-elasticclassic-load-balancer-elb-in-aws

**Comment by maestrofx** [comment]
Hi @cjellick,
Here is a brief description of my topology:

- I setup my environment with AWS VPC scenario 2[1] and put the rancher server in private subnet.
- the rancher servers are provisioned with 2 nodes (HA) backed by ELB and got SSL via AWS certificate. At this point all setup are good!
- The strange part for my setup is when I add hosts. I add hosts located in Digital Ocean, it works well. But, when I add hosts in the same VPC in the same private subnet, it got error `Failed to find rancher-agent container`. The same error with the hosts located in public subnet in same VPC.
- But, the hosts works again when I put the hosts located in the different VPC with the Rancher server.

When I try to dig the log, I found it's caused by the Rancher API's not accessible from that nodes `ERROR: https://RANCHER_SERVER/v1 is not accessible` as mentioned in this https://github.com/rancher/rancher/issues/136 issue.

Yes I follow this [2] suggestion. I try to manually add custom hosts. And found that the Rancher API's still not accessible, but when I try to access https://RANCHER_SERVER/v1  via curl, it returns value.

Any suggestion?
Thank you.

---
1. http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_Scenario2.html

1. https://docs.rancher.com/rancher/v1.6/en/installing-rancher/installing-server/#running-rancher-server-behind-an-elasticclassic-load-balancer-elb-in-aws

**Comment by aphillipo** [comment]
@maestrofx did you ever find a solution I'm having what looks like the exact same issue!

**Comment by maestrofx** [comment]
Hi @aphillipo, I have solved the problem myself.

Can you elaborate the case your architecture is?

Basically, my setup as I mentioned before:

1. The stack are fully in AWS and using AWS VPC scenario 2.
1. Rancher server are HA, cluster of EC2 nodes located in a private subnet.

The issue occured to my setup:
1. When the hosts added are setup using private IP, it got the error.
1. And when I setup the hosts using the public IP assigned to that node, it got error too. But when I dig more the logs, it's because the NAT problem in the subnet, so basically the traffic routed from that node to communicate with the API is not accessible.
So, my suggestion, make sure the host you want to added can access `https://RANCHER_SERVER/v1`.

**Comment by piyush8096** [comment]
For a host in different VPC , you will have to initiate a peering and accept from the VPC where your Rancher server lies

**Comment by gbittu** [comment]
I have followed the directions diligently from Rancher site and added proxy settings to classic ELB but still getting error message. From the new machine created I am able to access all my ranchers instances as well as ELB via curl. I can even access last script executed in the API calls.
