### ISSUE TITLE
io.rancher.container.requested_ip is not honored when upgrading a service

### ISSUE THREAD

**Issue by mcanevet** [rancher/rancher#8544]
**Rancher Versions:**
Server: v1.5.5
healthcheck: v0.2.3
ipsec: v0.0.7
network-services: v0.1.2
scheduler: v0.5.1

**Docker Version:**
1.12.6

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Create a service with `io.rancher.container.requested_ip` set to one specific IP, than upgrade it.

**Results:** 
`io.rancher.container.requested_ip` is honored only during service creation. When upgrading, the IP is considered as not available and thus the container gets a random IP ; even if the start behavior is not set to "Start before Stopping" (which in that case would be understandable). A new upgrade fixed the issue as the IP is considered available again.

**Comment by tfiduccia** [comment]
@mcanevet - on upgrade to ensure you get the same IP, you must check retain IP.  If you are using the UI, it's under the Networking tab.

**Comment by mcanevet** [comment]
@tfiduccia is there a way to do it using the API (via rancher-compose or terraform's rancher_stack resource), or is it only a WebUI feature?

**Comment by deniseschannon** [comment]
If you are using teh API directly, you would update the `retainIp` field to `true`. 

http://docs.rancher.com/rancher/v1.5/en/api/v2-beta/api-resources/service/

If you're using compose files, in the rancher-compose.yml

```
servicename:
  retain_ip: true
```

**Comment by deniseschannon** [comment]
But now that I re-read your issue, I think that this is a bug. If you use a `io.rancher.container.requested_ip`, I think it should automatically use the same IP since you've requested that specific IP. 

How are you creating and upgrading your services? Using `rancher-compose up` and `rancher-compose up --upgrade`?

**Comment by mcanevet** [comment]
@deniseschannon I usually use Terraform's rancher_stack resource which calls the rancheclient.Environment.ActionUpgrade method of rancher/go-rancher/client  : https://github.com/hashicorp/terraform/blob/master/builtin/providers/rancher/resource_rancher_stack.go#L247

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
