### ISSUE TITLE
[external-dns]  support Infoblox DNS updates

### ISSUE THREAD

**Issue by joshuadunham** [rancher/rancher#8546]
Hi Rancher,

    I'm submitting this as a feature request. The target is the rancher-dns module for updating external DNS tables managed by Infoblox.

   Some API examples can be found at,
https://community.infoblox.com/t5/API-Integration/The-definitive-list-of-REST-examples/td-p/1214
https://community.infoblox.com/t5/Community-Blog/Getting-Started-with-the-Infoblox-Web-API/ba-p/3161
https://ipam.illinois.edu/wapidoc/#

Go Client from manufacturer,
https://github.com/infobloxopen/infoblox-go-client

Is this possible?

Best,
-Joshua

**Comment by Ashthos** [comment]
This would be very useful for us also.

**Comment by vincent99** [comment]
We're have no particular interest but PRs are welcome; https://github.com/rancher/external-dns/tree/master/providers

**Comment by rocketeer125** [comment]
+1 to this. Infoblox is becoming the defacto DNS provider for a number of corporates I work for.

**Comment by aiwantaozi** [comment]
@rocketeer125 @Ashthos @joshuadunham Hi guys, we have added Infoblox DNS support, welcome to try.  You could add catalog https://github.com/aiwantaozi/external-dns.git branch: work-master
If you have any questions, feel free to comment.

**Comment by kingsd041** [comment]
@aiwantaozi   Hi, I use catalog https://github.com/aiwantaozi/community-catalog.git branch: work-master for testing.
Test passed.

**Comment by jdunhamvrtx** [comment]
@aiwantaozi, @kingsd041 : Sorry to pester but could you point me to some reference on compiling using Dapper? I'm set up on a Gitlab / Gitlab-CI workflow so need to tweak that a bit. :|

**Comment by aiwantaozi** [comment]
@jdunhamvrtx is there any other problem except need logo for infoblox ? Please list here, thanks.

**Comment by yasker** [comment]
@aiwantaozi Can you make a PR to community-catalog?

**Comment by aiwantaozi** [comment]
@yasker yes, double check I just set the image to my images, and denise will update later, right?

**Comment by yasker** [comment]
No, let me ask Denise to do a release first.

**Comment by yasker** [comment]
@aiwantaozi Denise already made v0.7.5 external DNS release. Please update your PR accordingly.

**Comment by aiwantaozi** [comment]
@yasker Just update the PR https://github.com/rancher/community-catalog/pull/624

**Comment by kingsd041** [comment]
Tested with rancher-server version- v1.6.10 with rancher/external-dns: v0.7.5
Test passed. 
But I found some new problems:
https://github.com/rancher/rancher/issues/10076
https://github.com/rancher/rancher/issues/10077
