### ISSUE TITLE
Rancher support for docker-ee (Enterprise Edition)

### ISSUE THREAD

**Issue by rocketeer125** [rancher/rancher#8547]
We've a requirement to run docker-ee, rather than docker-ce.
Can you folks please confirm if you are adding ee into the list of supported versions?
http://docs.rancher.com/rancher/v1.5/en/hosts/#supported-docker-versions

Docker version 17.03.1-ee-3, build 3fcee33

**Comment by djk** [comment]
I agree, this would be good to know and have visibility of.

**Comment by vincent99** [comment]
Yes; https://github.com/rancher/rancher.github.io/pull/757
