### ISSUE TITLE
Purge one time run containers from UI

### ISSUE THREAD

**Issue by bluemalkin** [rancher/rancher#8551]
Raising to issue to ask whether there's already an auto-purge setting, if not feature request.

**Rancher Versions:**
Server: v1.5.5

**Steps to Reproduce:**
Create lots of "cron" one time run containers or Jobs in Kubernetes.

**Results:** 
The Hosts page in the Rancher UI is very slow to load and long to scroll down. See example:

<img width="839" alt="jobs" src="https://cloud.githubusercontent.com/assets/2703290/25206918/52b916c6-25ae-11e7-87cf-eaf58f2b637f.png">

**Comment by flaccid** [comment]
I guess workaround is one of the GC tools out there, e.g. https://github.com/flaccid/docker-docker-gc-crond.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
