### ISSUE TITLE
Interim error when creating a service with scheduler label and making an associated host inactive

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#8553]
Rancher Versions:
Server:Master with scheduler image daishan1992/scheduler

**Docker Version:**17.04.0-ce

**OS and where are the hosts located? (cloud, bare metal, etc):**Ubuntu, Cloud

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**Single node

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**Cattle

Steps to Reproduce:

1. Create a master setup with 3 hosts and use the scheduler image daishan1992/scheduler. Create label on host1 as zone1=east and label on host2 as zone2=west and host3 with no label
2. Create a service of scale 2 and add label to the service with key as io.rancher.scheduler.host_scale_group and value as "zone1=east". 
3.  Make  host1 inactive
4. Create another service of scale4 having label with key asi o.rancher.scheduler.host_scale_group and value as "zone1=east". 

**Results:** 
There is an intermediate error as shown below: 
```(Failed to allocate instance [container:1i255]: Bad instance [container:1i255] in state [error]: Allocation failed: No healthy hosts with sufficient resources available). ```
It fixes itself after sometime and the containers are scheduled on host2

**Comment by StrongMonkey** [comment]
the facet is that external scheduler never know if a host is inactive or not. Possibly we need to make sure metadata populate the host.state info so that scheduler can make decision based on that.
