### ISSUE TITLE
DNS on outbound lookup timeout (How to add secondary DNS Server)

### ISSUE THREAD

**Issue by puttpotsawee** [rancher/rancher#8556]
**Rancher Versions:** 1.1.4

**Docker Version:** 1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):** Ubuntu 16.04 on Digital Ocean

**Setup Details: HA rancher, internal DB**

**Environment Type: Cattle**

**Steps to Reproduce:**
I have 5 hosts cluster on Cattle hosted on Digital Ocean. The system was on _production_ with about 100++ unique sessions per day.
The system worked fine (despite the known issue solved by some workaround) for 3 months.

We have numbers of Node.js apps that consume some external services via API (api.braintree.com is one of them). The API consumption work pretty good so far.

Today, we face some error according to the outbound DNS.

the node [dns.js](https://nodejs.org/api/dns.html) return this error:

```
Error: getaddrinfo EAI_AGAIN api.braintreegateway.com:443
    at Object.exports._errnoException (util.js:893:11)
    at errnoException (dns.js:31:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)
```

this error is thrown due to the [DNS lookup timeout](http://stackoverflow.com/questions/40182121/error-getaddrinfo-eai-again).

this occurs to almost **every** different domain name API endpoint we integrated.

And it just happens for a _2-3 hours_ period of time.

I know this could be due to some _network error_ at **Digital Ocean** side.

However, I want to know the following:

1. Seeing from `/var/lib/cattle/etc/cattle/dns/answers.json ` at the network agent instance, I assume the `"recurse": [ "8.8.8.8"] ` inside `"default"` is where the lookup actually goes through? If that so, is there anyway to add secondary default lookup DNS server?
2. I tried to upgrade a relevant service and add additional DNS server at `Resolving Servers` setting on `Network` tab at Rancher UI, Is this the right way to add the secondary DNS lookup server for each service?

I know that our Rancher version and Docker is outdated, the plan for upgrading it is ongoing. However, our app is running in Production so we are still studying and trying out the newer version on Dev Environment.

Thanks for any help in advance :D

**Comment by superseb** [comment]
Are you still experiencing this? And does it occur on newer versions? Can you file a new issue if you still encounter it?
