### ISSUE TITLE
rancher/server containers are not excluded when importing containers to rancher

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#856]
This affects our vagrant build in particular, since agent and server are run in the same vm.

We need to add the appropriate label to the rancher/server image so that we know to exclude it.

**Comment by enriquemorenotent** [comment]
Thanks for doing the report :)

**Comment by cjellick** [comment]
Actually, simply adding the same label (`LABEL "io.rancher.container.system"="rancher-server"`)we use for other system containers probably won't work. We'd think it is a erroneous rancher system container and try to force stop it.

Will think this through a little bit
