### ISSUE TITLE
Setting custom name when registering an Host

### ISSUE THREAD

**Issue by YoannMa** [rancher/rancher#8561]
Hi,

When you add an Host in Rancher, the default name is the `hostname -f` (i guess)

With Azure, you got something like that : 

![image](https://cloud.githubusercontent.com/assets/18331529/25269152/bb71b7d6-267b-11e7-8c2c-c3b78e3eec65.png)

Manually updatating the custom name of each is long and i was thinking if adding the possibility to set the custom name while registering the Host would be possible, to be more `A e s t h e t i c` without human action.

Using either `CATTLE_HOST_LABELS` or another environment variable like `CATTLE_CUSTOM_NAME`

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
