### ISSUE TITLE
403: Forbidden error when using account API key.

### ISSUE THREAD

**Issue by wrsuarez** [rancher/rancher#8565]
I just had a strange issue where I added a new user to my environment. They created an account API key to access the environment but were getting a `403:Forbidden` error. (edited)
When I had him create an "environment" key, then it worked but according to the docs, the regular api key should work for all envs you have access to
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.5.3` Cattle: `v0.177.10` UI: `v1.5.8` |
|Access|`ldap` `admin`|
|Orchestration|`Cattle`|
|Route|`admin-tab.ha`|

**Comment by tfiduccia** [comment]
@wrsuarez - I am unable to reproduce your problem.  I used the Open Ldap and added a user as a member to an environment.  I then logged in as that member and created an account API key and was able to use it.  So...
1.  What type of permission did you give you new user to the environment
2.  In the Access Control page, what type of site access do you have turned on (I currently have Allow any valid Users)
3.  When you go to Accounts page, what "Kind" of user is your new user?

Can you also have your user try again with a new account key?

**Comment by superseb** [comment]
Please comment if you still need help with this.
