### ISSUE TITLE
Clicking exposed port hyperlink should not direct to https

### ISSUE THREAD

**Issue by wrsuarez** [rancher/rancher#8567]
When you click the hyperlink for the exposed port in the Rancher UI, the link ignores the fact the exposed port may be 80 and always directs you to the host IP on https. It should respect the port number when generating the URL

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.5.3` Cattle: `v0.177.10` UI: `v1.5.8` |
|Access|`ldap` `admin`|
|Orchestration|`Cattle`|
|Route|`admin-tab.ha`|

**Comment by aemneina** [comment]
@wrsuarez do you have examples of this? I dont think rancher is interfering and redirecting you.
