### ISSUE TITLE
Scheduler incorrectly schedules the container instance on a host with a different zone label  after deleting one instance of the service

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#8568]
**Rancher Versions:**
Server:Server:Master with scheduler image daishan1992/scheduler

**Docker Version:**17.04.0-ce

**OS and where are the hosts located? (cloud, bare metal, etc):**Ubuntu, Cloud

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**Single node

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**Cattle

**Steps to Reproduce:**
1. Create a master setup with 4 hosts and use the scheduler image daishan1992/scheduler. The hosts have the label as below:
Host1 with label - goup=east
Host2 with label - group=west
Host3 with label - group=north
Host 4 with no label
2. Create service with scale 4 with label io.rancher.scheduler.scale_per_group: key=group; east=1, west=3. One container gets created in host1 and three containers get created on host2 as expected
3. Delete one instance of the service on host2 which has label group=west
4. After service reconcile, the container gets created on host1 which has label group=east

Expected
1. After service reconcile, the container should be created on host2

**Comment by soumyalj** [comment]
The same issue is seen when we upgrade a service.

**Comment by StrongMonkey** [comment]
The feature needs to be re-designed to use api fields. Ticket is invalid.
