### ISSUE TITLE
auth redirect for k8s dashboard 

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#8569]
We should create an auth redirect for the k8s dashboard starting as of 1.6

**Comment by deniseschannon** [comment]
@galal-hussein For testing:

From @ibuildthecloud: You have to signout of Rancher and then go to the dashboard URL and it should redirect to the login. You login and then it goes to the dashboard without the user seeing rancher UI.  You have to test failed login

**Comment by galal-hussein** [comment]
@deniseschannon on Rancher v1.6.1-rc8 and k8s 1.6, i tested the following:

- Enable Github authentication.
- Install k8s 1.6
- Log out of Rancher
- go to the dashboard URL:
`http://x.x.x.x:8080/r/projects/1a5/kubernetes-dashboard:9090/#!/workload?namespace=default`

Result:

I can access the dashboard directly without authentication.

**Comment by pulberg** [comment]
Works for me on v1.6.1

**Comment by galal-hussein** [comment]
Rancher Server: v1.6.2
K8s version: 1.6

I followed the same steps, and now i am getting the login page when trying to access the dashboard.
