### ISSUE TITLE
After deleting service instances in any zone, the instance count is not cleaned up on the host and leads to incorrect container scheduling 

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#8570]
Server:Master with scheduler image daishan1992/scheduler

**Docker Version:**17.04.0-ce

**OS and where are the hosts located? (cloud, bare metal, etc):**Ubuntu, Cloud

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**Single node

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**Cattle
**Steps to Reproduce:**
1. Create a master setup with 4 hosts and use the scheduler image daishan1992/scheduler. Create label on host1 as group=east and label on host2 as group=west and label on host3 as group=north  label on host4 as group=north and host5 with no label
2. Create few services of scale 4 with scheduling as label io.rancher.scheduler.scale_per_group: key=group; east=1, west=3 OR  io.rancher.scheduler.scale_per_group: key=group; east=1, west=3, north=4
3. Delete few instances of the services
4. Create a new service  io.rancher.scheduler.scale_per_group: key=group; east=1,north=3

**Results:** 
All containers of the new service go to the host with label group=north.
After some instances of a service are deleted, the instance count on the host is not cleaned up and results in incorrect instance distribution across hosts.

**Comment by StrongMonkey** [comment]
the fix was in cattle master now.

**Comment by StrongMonkey** [comment]
@deniseschannon it is based on the uncompleted scheduler pr(across zone). Since we decide to use api field instead of labels, this ticket is no longer valid.
