### ISSUE TITLE
Stack Scoped volumes create volumes with underscores in name. Not all Docker Volume Plugins support underscores

### ISSUE THREAD

**Issue by untoldone** [rancher/rancher#8572]
For example, Google Compute Platform (GCE/GCP) volumes cannot have underscores in their name (only letters, numbers, and hyphens).

The result is any reasonably intuitive implementation of a GCE docker volume plugin would not work with rancher stack scoped volumes.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
