### ISSUE TITLE
rancher-cli ssh key not found

### ISSUE THREAD

**Issue by ihackalot** [rancher/rancher#8573]
I set a local testing environment with a couple of agents spinned locally with docker-machine running rancherOS 1.0. I also set rancher-cli to communicate with my server and everything looks fine: I can run docker commands via cli and stuff. For example, the following returns my running containers on the selected host: `rancher --host 1h16 docker ps`.

However, I cannot ssh into any of my local hosts. For example the following doesn't work: `rancher ssh -i ~/.docker/machine/machines/lab01/id_rsa docker@lab01` and returns the following error:
```
FATA[0001] Not found: ~/.docker/machine/machines/lab01/id_rsa
```

However the following command works just fine: `ssh -i ~/.docker/machine/machines/lab01/id_rsa docker@192.168.99.100`

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
