### ISSUE TITLE
how to access Kubernetes api from outside of Rancher

### ISSUE THREAD

**Issue by hiscal2015** [rancher/rancher#8574]
**Rancher Versions:** 1.5.5

**Docker Version:** 1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):** Ubuntu 16.04 

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Kubernetes

**Steps to Reproduce:**

I need to access K8S api from outside of Rancher for Prometheus metrics, but I don't know how to specify the token. 

Here are the available parameters in Prometheus we can use to discover Kubernetes, we can either use "basic_auth", "bearer_token" or "bearer_token_file" to access api server:

```
[ api_server: <host> ]
role: <role>

# Optional authentication information used to authenticate to the API server.
# Note that `basic_auth`, `bearer_token` and `bearer_token_file` options are
# mutually exclusive.

# Optional HTTP basic authentication information.
basic_auth:
  [ username: <string> ]
  [ password: <string> ]

# Optional bearer token authentication information.
[ bearer_token: <string> ]

# Optional bearer token file authentication information.
[ bearer_token_file: <filename> ]
```
So, how can I find the value of api server url and authentication values ("basic_auth", "bearer_token" or "bearer_token_file")?

Thanks for the help.

**Comment by aemneina** [comment]
@hiscal2015 navigate to the kubernetes -> CLI tab in the GUI. from there click generate config, the valules stored in there should have the k8s api endpoint url and keys to authenticate with.

**Comment by hiscal2015** [comment]
@aemneina  Thanks, "basic_auth:" works, I made a mistake that I should use api user key and password instead of login user and password.
