### ISSUE TITLE
Automatically create a TLS certificate for secure access of Rancher UI

### ISSUE THREAD

**Issue by McPringle** [rancher/rancher#8575]
By default, rancher is only available unencrypted by HTTP. An automatically created self signed TLS certificate for HTTPS access of rancher is much better than the unencrypted default. Of course, an integration of Let's Encrypt would be much better…

**Rancher Versions:**
Server: 1.5.5

**Docker Version:**
17.03.1-ce, build c6d412e

**OS and where are the hosts located? (cloud, bare metal, etc):**
CentOS Linux release 7.3.1611 (Core)
bare metal

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
cattle

**Steps to Reproduce:**
Start a fresh new rancher instance.

**Results:** 
The rancher UI is only available using unencrypted HTTP requests.

**Comment by phpfs** [comment]
This would be absolutely great +1

**Comment by KyleSanderson** [comment]
As a new user of Rancher, I was trying to figure out why on earth nothing's listening on port 80,443... Having Rancher be insecure out of the box is pretty devastating when it's supposed to be a secure orchestration tool.

**Comment by Toflar** [comment]
I think this can be closed, because it's supported in 2.0 :)

**Comment by superseb** [comment]
Thanks!
