### ISSUE TITLE
docker-compose not treated like docker-compose anymore

### ISSUE THREAD

**Issue by untoldone** [rancher/rancher#8576]
Having just upgraded to 1.5.5 from 1.1.4 yesterday, I was really surprised to find rancher's handling of docker-compose's files don't really follow docker-compose's docs anymore ... e.g. I can no longer use docker-compose documentation to figure out how a docker-compose file used with Rancher works. Likewise, rancher's documentation on its own docker-compose format seems to assume Docker's documentation is the authority on docker-compose files used with rancher ... It's close, but not the same.

I also came across the bug https://github.com/rancher/rancher/issues/6564 that suggests this is the current decided upon pattern / attempting to conform to docker-compose's format is no longer the objective. Other examples include additions such as `per_container` on volumes that work in a rancher docker-compose file, but don't in a normal docker-compose file.

I would argue that this is a direction that will lead to pretty significant user confusion. At a minimum, I really think there should be a single piece of documentation that describes the differences (e.g. I spent 30 minutes this morning trying to figure out why `.env` files didn't work https://docs.docker.com/compose/env-file/ vs https://docs.rancher.com/rancher/v1.5/en/cli/variable-interpolation/). I'd submit an alternative could either be A: entirely renaming the file to avoid confusion -- e.g. use rancher-compose.yml for everything rather than docker-compose to suggest the similar but different nature of the file, or B, keep rancher-specific directive on constructs in docker-compose.yml that don't break the format as defined in the docker-compose docs.

**Comment by joshwget** [comment]
As it is now our format is largely a superset of Docker Compose <= 2.0. We support additional fields in `docker-compose.yml` but they can be placed in `rancher-compose.yml` to keep a file that will be compatible with Docker Compose (`per_container` is the only exception I'm aware of).

We'll likely go with route A going forward because of how tied the Compose format and Swarm are becoming. The docs will be updated to reflect any changes.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
