### ISSUE TITLE
Serverless support

### ISSUE THREAD

**Issue by mytototo** [rancher/rancher#8577]
Hi there,

Is there any plans to have a serverless tool running on Rancher? This way, we'd be able to build _functions as a service_ on top of orchestration tools like Cattle or Kubernetes. I don't want to rely on AWS or GCP just for this kind of features...

A Rancher tool for serverless, orchestration agnostic and connected to the Rancher secrets API (Vault) would be awesome.

Thanks.

**Comment by joshwget** [comment]
There are some serverless frameworks like [fission](https://github.com/fission/fission) and [kubeless](https://github.com/bitnami/kubeless) for Kubernetes that you might want to check out. We don't have any current plans for a Cattle serverless framework yet, but we are interested in the idea.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
