### ISSUE TITLE
Internal DNS not working in Kubernetes 

### ISSUE THREAD

**Issue by tombmurphy** [rancher/rancher#8580]
**Rancher Versions:**
Server: v1.5.5
kubernetes: 1.5.4-rancher1-1

**Environment Type:**
Kubernetes

**Details:**
I'm raising this issue to get some clarification on the current mechanism for internal DNS with Kubernetes.

The latest official Rancher documentation is for an old version of Rancher v1.2: https://docs.rancher.com/rancher/v1.2/en/kubernetes/k8s-internal-dns-service/

There is no documentation available for the latest version.

In v1.5.5 the `kube-dns` service runs in the kube-system namespace. Also confirmed when I query the kubernetes cluster:
```kubectl cluster-info
Kubernetes master is running at https://XXXX/r/projects/1a842/kubernetes
KubeDNS is running at https://xxxx/r/projects/1a842/kubernetes/api/v1/proxy/namespaces/kube-system/services/kube-dns
```
BUT the internal Rancher DNS containers are also running when you go to Infrastructure Stacks, network services, metadata.

All my pods are using the kube-dns IP as resolver but they do no not resolve the services endpoints. 
The services endpoint do resolve if I query the Rancher Internal DNS IP `169.254.169.250`

Can someone please shed some light on this and how I should setup my Kubernetes deployments/pods to use the Rancher internal DNS ?

**Comment by oskapt** [comment]
Hi, Tom. Can you provide some information about what you're trying to resolve and how you're trying to do it? In my k8s environment I'm able to resolve k8s containers and infrastructure service containers without needing to specify the resolver endpoint.

Perhaps you can paste a copy of the output from the commands you're running and some information about where you're logged in when running them?

**Comment by superseb** [comment]
Please comment if you still need help with this.
