### ISSUE TITLE
External service in compose files does not create properly

### ISSUE THREAD

**Issue by alex-hempel** [rancher/rancher#8581]
The creation of external services via compose files in Cattle does not work as described in https://docs.rancher.com/rancher/v1.5/en/cattle/adding-external-services/.

**Rancher Versions:**
Server: 1.5.5
healthcheck: 0.2.3
ipsec: 
network-services: 0.6.6
scheduler: 0.7.5
kubernetes (if applicable):

**Docker Version:**
1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):**
AWS EC2

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
- Manually create a stack with an external service
- export config
- create new stack with exported config (docker-compose.yml and rancher-compose.yml)

Alternatively:

- Create a docker-compose with an external service as:
docker-compose.yml
```
externalservice:
      image: rancher/external-service
```

rancher-compose.yml
```
externalservice:
        external_ips:
        - 172.2.3.4
```
- Create a new stack with these files

**Results:** 
External Service creation fails with error: 

> Expected state running but got error: Image [index.docker.io/rancher/external-service] failed to pull: Pulling repository docker.io/rancher/external-service

**Comment by deniseschannon** [comment]
How are you launching these compose files?

In v1.5.5, when I create using the same compose files using Rancher CLI v0.5.2, it works for me. It also works for me when I put the compose files in the UI under "Add Stack".

**Comment by alex-hempel** [comment]
Hi Denise,

it appears my compose files were malformed. I've made some corrections and things are now working as expected.

Thank you for your response.
