### ISSUE TITLE
Deployment speed degradation without known reason

### ISSUE THREAD

**Issue by VAdamec** [rancher/rancher#8583]
Hi, we got stable Rancher platform for deployment, which was started as 1.4 version and during time upgraded to actual version 1.5.5. Right now we struggle with long deployment time (using rancher-compose v0.12.4), it takes about 3-4 minutes to start application consist from two services (both have sidekicks, so four containers). If I target same Jenkins pipeline job to clean 1.4.3 or 1.5.5/6 rancher environments creation tooks about 20-30s. So far no luck to find where is the issue, I was suspicious about database, but no luck to get any evidence. Can you help me with debugging ?

Production Rancher
1x Rancher server
3x external DB (mariaDB via HAproxy, on server as primary, rest as backup)
1x hosts
1x balancer (host just for Haproxy stack)

Testing clusters
1x Rancher server
1x host
1x balancer (host just for Haproxy stack)

same HW parameters (OpenStack VMs, same flavor)

rancher-compose to production rancher stacks:
```
+ /bin/rancher-compose --project-name servicetest-dev-null up -d --force-upgrade --pull
time="2017-04-23T23:45:56-07:00" level=info msg="[0/4] [server]: Creating " 
time="2017-04-23T23:45:56-07:00" level=info msg="Creating service server" 
time="2017-04-23T23:45:58-07:00" level=info msg="[0/4] [server]: Created " 
time="2017-04-23T23:45:58-07:00" level=info msg="[0/4] [ui]: Creating " 
time="2017-04-23T23:45:58-07:00" level=info msg="[0/4] [filebeat-server]: Creating " 
time="2017-04-23T23:45:58-07:00" level=info msg="[0/4] [filebeat-server]: Created " 
time="2017-04-23T23:45:58-07:00" level=info msg="Creating service ui" 
time="2017-04-23T23:46:01-07:00" level=info msg="[0/4] [ui]: Created " 
time="2017-04-23T23:46:01-07:00" level=info msg="[0/4] [filebeat-ui]: Creating " 
time="2017-04-23T23:46:01-07:00" level=info msg="[0/4] [filebeat-ui]: Created " 
time="2017-04-23T23:46:01-07:00" level=info msg="[0/4] [server]: Starting " 
time="2017-04-23T23:46:06-07:00" level=info msg="Finished pulling registry.example.com/servicetest/server-dev-null:28" 
time="2017-04-23T23:46:07-07:00" level=info msg="Finished pulling registry.example.com/servicetest/filebeat-dev-null:28" 
time="2017-04-23T23:46:07-07:00" level=info msg="Updating server" 
time="2017-04-23T23:46:10-07:00" level=info msg="Upgrading server" 
time="2017-04-23T23:47:15-07:00" level=info msg="[1/4] [server]: Started " 
time="2017-04-23T23:47:15-07:00" level=info msg="[1/4] [filebeat-server]: Starting " 
time="2017-04-23T23:47:15-07:00" level=info msg="[1/4] [ui]: Starting " 
time="2017-04-23T23:47:15-07:00" level=info msg="[2/4] [filebeat-server]: Started " 
time="2017-04-23T23:47:17-07:00" level=info msg="Finished pulling registry.example.com/servicetest/ui-dev-null:28" 
time="2017-04-23T23:47:17-07:00" level=info msg="Finished pulling registry.example.com/servicetest/filebeat-dev-null:28" 
time="2017-04-23T23:47:17-07:00" level=info msg="Updating ui" 
time="2017-04-23T23:47:21-07:00" level=info msg="Upgrading ui" 
time="2017-04-23T23:48:39-07:00" level=info msg="[3/4] [ui]: Started " 
time="2017-04-23T23:48:39-07:00" level=info msg="[3/4] [filebeat-ui]: Starting " 
time="2017-04-23T23:48:39-07:00" level=info msg="[4/4] [filebeat-ui]: Started " 
```

rancher-compose to clean rancher stacks:
```
+ /bin/rancher-compose --project-name servicetest-dev-test up -d --force-upgrade --pull
time="2017-04-23T23:56:15-07:00" level=info msg="[0/4] [server]: Creating " 
time="2017-04-23T23:56:15-07:00" level=info msg="Creating service server" 
time="2017-04-23T23:56:15-07:00" level=info msg="[0/4] [server]: Created " 
time="2017-04-23T23:56:15-07:00" level=info msg="[0/4] [filebeat-server]: Creating " 
time="2017-04-23T23:56:15-07:00" level=info msg="[0/4] [ui]: Creating " 
time="2017-04-23T23:56:15-07:00" level=info msg="[0/4] [filebeat-server]: Created " 
time="2017-04-23T23:56:15-07:00" level=info msg="Creating service ui" 
time="2017-04-23T23:56:15-07:00" level=info msg="[0/4] [ui]: Created " 
time="2017-04-23T23:56:15-07:00" level=info msg="[0/4] [filebeat-ui]: Creating " 
time="2017-04-23T23:56:15-07:00" level=info msg="[0/4] [filebeat-ui]: Created " 
time="2017-04-23T23:56:15-07:00" level=info msg="[0/4] [server]: Starting " 
time="2017-04-23T23:56:25-07:00" level=info msg="Finished pulling registry.example.com/servicetest/filebeat-dev-test:29" 
time="2017-04-23T23:56:25-07:00" level=info msg="Finished pulling registry.example.com/servicetest/server-dev-test:29" 
time="2017-04-23T23:56:25-07:00" level=info msg="Updating server" 
time="2017-04-23T23:56:25-07:00" level=info msg="Upgrading server" 
time="2017-04-23T23:56:35-07:00" level=info msg="[1/4] [server]: Started " 
time="2017-04-23T23:56:35-07:00" level=info msg="[1/4] [filebeat-server]: Starting " 
time="2017-04-23T23:56:35-07:00" level=info msg="[2/4] [filebeat-server]: Started " 
time="2017-04-23T23:56:35-07:00" level=info msg="[2/4] [ui]: Starting " 
time="2017-04-23T23:56:35-07:00" level=info msg="Finished pulling registry.example.com/servicetest/filebeat-dev-test:29" 
time="2017-04-23T23:56:35-07:00" level=info msg="Finished pulling registry.example.com/servicetest/ui-dev-test:29" 
time="2017-04-23T23:56:35-07:00" level=info msg="Updating ui" 
time="2017-04-23T23:56:36-07:00" level=info msg="Upgrading ui" 
time="2017-04-23T23:56:42-07:00" level=info msg="[3/4] [ui]: Started " 
time="2017-04-23T23:56:42-07:00" level=info msg="[3/4] [filebeat-ui]: Starting " 
time="2017-04-23T23:56:42-07:00" level=info msg="[4/4] [filebeat-ui]: Started " 
```

with --debug it only shows you that it waits in "Upgrading server" step, in UI I see that a most of time it spends in "Starting"

time="2017-04-24T00:45:00-07:00" level=info msg="Upgrading server" 
time="2017-04-24T00:46:05-07:00" level=debug msg="Finding service server" 

Any thoughts ?

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.5.5` Cattle: `v0.178.3` UI: `v1.5.8` |
|Access|`ldap` `admin`|
|Orchestration|`Cattle`|
|Route|`stacks.index`|

**Comment by VAdamec** [comment]
So I create new mariadb cluster, dump and upload DB content, switch rancher servers to this new cluster (haproxy) and now no problem at all. New DB servers has lower HW params, but same network (OpenStack), ... so still no clue what happened.

**Comment by VAdamec** [comment]
@aemneina closed ? it's not fixed, seems that this permanent issue, after a two weeks or more it happens again. At least will be good how to debug such issues. Why it sometimes takes seconds and next run it takes 10 minutes, without any logged error.

**Comment by superseb** [comment]
@VAdamec What version of `rancher-compose` are you using? And can you share the compose files so we can reproduce?

**Comment by VAdamec** [comment]
Actual used versions:
```
Rancher server: 1.6.0 (latest)
Rancher-compose version v0.12.5
Rancher version v0.6.0
```

it could be some datacenter network issues, but will be good to have some method to analyze this behavior (to have some proof). Right now I just see result without any reason.

I'll prepare github repo with testing compose files, it's simple stack, just two services - redis + hastebin service.

**Comment by VAdamec** [comment]
Simple benchmark test: https://github.com/VAdamec/rancher-speedtest result in Grafana is like this:

![screen shot 2017-05-15 at 2 23 47 pm](https://cloud.githubusercontent.com/assets/5555130/26057498/3675b908-397a-11e7-921b-d2d72d6f8834.png)

seems that some host has some issue (our issue, so no fix from Rancher side).  Want just help with debugging. And maybe change Rancher server/compose logging to catch such problems in some clear way (it's ipsec issue ? resource issue? db not responding? ....). Right now it's really unclear what's the reason.
