### ISSUE TITLE
[rancher-dns] Allow overriding name template for specific services by setting io.rancher.service.external_dns_name_template label to it in docker-compose.yml

### ISSUE THREAD

**Issue by gerich-home** [rancher/rancher#8584]
**Rancher Versions:**
Server: 1.5.1
healthcheck: 0.2.3
ipsec: 0.0.5
network-services: 0.1.1
scheduler: 0.5.1

**Docker Version:** 1.12.6 on agents, 17.03.0-ce on the server 

**OS and where are the hosts located? (cloud, bare metal, etc):** Ubuntu 16.04.2 LTS (with KVM) (4.4.0), cloud, DigitalOcean

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single node rancher, internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Suggestion**:
Currently it is not possible to specify Custom DNS name template for External DNS services (https://try.rancher.com/env/1a45133/catalog?category=External%20DNS) at service level.
It is essential to be able to do that, so that for majaority of services will have the default naming scheme, but for some of them you will be able to define shorter names.

I have already prepared the corresponding PR that is pending for more than 2 weeks: https://github.com/rancher/external-dns/pull/74

With this change you are able to specify the custom pattern in `io.rancher.service.external_dns_name_template` label in your `docker-compose.yml` file at the level of individual services.

**Comment by janeczku** [comment]
Supported as of https://github.com/rancher/external-dns/releases/tag/v0.6.4

**Comment by gerich-home** [comment]
Created PR to include this change into catalog item for DigitalOcean external DNS:
https://github.com/rancher/community-catalog/pull/496

**Comment by janeczku** [comment]
reopening for testing

**Comment by sabiodelhielo** [comment]
Tested the following scenarios with rancher/server:v1.6.8-rc4 and rancher/external-dns:v0.7.0:

1) Created exposed service first, and added Route53 External DNS service with custom dns label name, after Route53 service was created, a dns record was added with the correct fqdn name.
2) Created a new exposed service, a dns record was created with expected formatted from the dns template name.
3) Upgrading the dns template label for the service, the external-dns service updated the record updated for the upgraded service

**Comment by sabiodelhielo** [comment]
So, the concern I have is that the default DNS template name can now be changed to a format that will cause multiple record conflicts. For example setting the DNS template name like 'workspace.%{{environment}}' will give the same record name for all exposed services in an environment. Should there be validation to protect the user from creating this issue for themselves?

**Comment by janeczku** [comment]
@sabiodelhielo might be worth a discussion, but out of scope for this ticket which deals with the per-service label and not the templating of the default DNS template (which was introduced earlier).

**Comment by sangeethah** [comment]
@janeczku , allowing users to override the fqdn per service using a label will also have the same issue of allowing users to be able to add DNS labels that could  have been potentially tied up for other services.

**Comment by sabiodelhielo** [comment]
Additionally tested:

1) upgrading external dns from v0.6.4 to v0.7.0.
2) Removing an exposed service also removed the associated DNS record

**Comment by sabiodelhielo** [comment]
I verified these steps with digitalocean dns service v0.6.4
