### ISSUE TITLE
Add ability to add environment variable to rancher run command in CLI

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#8589]
**Rancher Versions:** v1.5.5

Customer would like ability to add environment variable to container/services through CLI.  Currently not able to do this.

**Comment by deniseschannon** [comment]
Example: ```
rancher run -e "key=value" image
```

**Comment by cjellick** [comment]
Implement exactly like `docker run` same behavior for `-e A=B`, `-e A=`, `-e A`, `-e =B`

**Comment by carolynhu** [comment]
The list of supports:
1. -e "foo=bar". Container must have env variables with foo=bar
2. -e "foo". Container must have an env variable with $foo, where $foo is defined outside. If it is not defined, it should be empty.
3. -e "foo=", Container must have a env variable with foo="".
4. -e "foo=bar" -e "foo1=bar1". Container must have env variables with foo=bar and foo1=bar1.
5. -e "=foo" not supported

**Comment by deniseschannon** [comment]
Available in CLI v0.6.2-rc1

**Comment by soumyalj** [comment]
Tested with rancher CLI v0.6.2-rc1 on rancher 1.6.3-rc1. 
Example: ```./rancher run -e "test=value" -i --name testcont ubuntu```
Verified that the environment variable is set by doing an exec into the container and checking the exported variables. Also verified by doing an inspect on the container.
```
root@5d7418f43e7f:/# export
declare -x HOME="/root"
declare -x HOSTNAME="5d7418f43e7f"
declare -x LS_COLORS="rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd
=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=3
4;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;
31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tz
o=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=
01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz
2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*
.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;
31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm
=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*
.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=0
1;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*
.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;
35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv
=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.e
mf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36
:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=0
0;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:"
declare -x OLDPWD
declare -x PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
declare -x PWD="/"
declare -x SHLVL="1"
declare -x TERM="xterm-256color"
declare -x test="value"
```

Tested with the following options:
1. -e "test=value"
2. -e "foo"
3. -e "foo="
4. -e "foo=bar" -e "foo1=bar1" -e "foo2=bar2"
5. =e "=bar" is not supported

**Comment by dizlexik** [comment]
I'm getting errors when trying to use `-e` on `rancher exec`. Does anyone know of a way to accomplish this? This issue appears to only apply to `rancher run`, unfortunately.

**Comment by cjellick** [comment]
Yep, we only implemented it in run, not exec. 
What version of rancher are you on?

**Comment by dizlexik** [comment]
I'm running Rancher v1.6.26 with Rancher CLI v0.6.13

I'm working around this for now by doing `rancher exec myService /bin/bash -c "ENV_VAR=value /bin/myCommand arg1 arg2"`
