### ISSUE TITLE
Allow to disable rancher DNS

### ISSUE THREAD

**Issue by ketchoop** [rancher/rancher#8590]
It would be redundant and get you in some troubles if you use another SD, e.g. consul, and internal discovery is running.

**Comment by ket4yii** [comment]
Guys, please, do something with this thing. I don't know why, but your internal DNS breaks consul DNS when address of service was changed(after deploy, for example). Maybe it's caching or something else, but it is really awful.

**Comment by superseb** [comment]
The issue regarding caching was resolved and you should be able to point it to a different DNS server. Replacing/disabling Rancher DNS won't be supported as other components depend on it.
