### ISSUE TITLE
Adding hosts by specifying host template in docker compose fails

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#8592]
**Rancher Versions:**
Server: Master

**Docker Version:** 17.04.0-ce

**OS and where are the hosts located? (cloud, bare metal, etc):**Ubuntu, Cloud

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**Single node

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**Cattle

**Steps to Reproduce:**
1. Create a host template specifying the driver, public values and secret values
{
"driver": "digitalocean",
"name": "hosttemplate4",
"secretValues": {
"digitaloceanConfig": "{{'accessToken': 'abcdefgh',}}",
},
"publicValues": {
"digitaloceanConfig": "{{'region': 'nyc3',\r\n 'size': 1gb',\r\n}}",
},
}
2. Use the template name in the docker compose file and create a stack. Example below:
```
version: '2'
services:
  serva:
    image: nginx
hosts:
  soumyah1:
    template: hosttemplate4

```

**Results:** 
Stack creation fails with the error below:
```
Error (Bad response statusCode [422]. Status [422 status code 422]. Body: [code=DriverConfigExactlyOneRequired, baseType=error, message=DriverConfigExactlyOneRequired] from [http://localhost:8080/v2-beta/projects/1a5/hosts])

```
Audit log response object:
```
{
  "id": "95bda386-d4e4-4e8a-beea-7a1730533a7d",
  "type": "error",
  "links": {},
  "actions": {},
  "status": 422,
  "code": "DriverConfigExactlyOneRequired",
  "message": "DriverConfigExactlyOneRequired",
  "detail": null,
  "baseType": "error"
}

```

**Comment by cjellick** [comment]
Its a cattle change wherein we need to change the api validation. Currently, we look to see that one driver config is set, but we dont take hostTemplate into account
