### ISSUE TITLE
[rancher-compose] does not recognize trusted certs on macOS

### ISSUE THREAD

**Issue by mindlace** [rancher/rancher#8593]
#**Rancher Versions:**
Server: 1.4.1
Rancher-Compose: v0.12.4-rc1

**OS and where are the hosts located? (cloud, bare metal, etc):**
Running rancher compose on macOS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Rancher server over SSL using organization-signed CA 

**Steps to Reproduce:**
1.) Add a self-generated root CA cert to your os x machine
2.) Start a Rancher Server using a cert signed by the same CA
3.) attempt to use rancher-compose 

**Results:** 
ERRO[0000] Failed to open project WEB-APP: Get https://`rancher-domain`/v2-beta: x509: certificate signed by unknown authority
FATA[0000] Failed to read project: Get https://`rancher-domain`/v2-beta: x509: certificate signed by unknown authority

**Discussion**

I found this issue https://github.com/golang/go/issues/14514 which seems to suggest that the problem has been solved since 1.7.1. Therefore, I suspect there is something with the build environment that is not properly picking up certs. 

Attempting to build rancher-compose on macOS does not produce a macOS compatible binary, so I was unable to investigate further.

**Comment by janeczku** [comment]
Rancher CLI doesn't work with self-signed certificates either OOB. It's because we are cross-building the Darwin binaries. See https://github.com/golang/go/issues/14514.

**Workaround**
Add the self-signed certificate to the MacOS SystemRootCertificates.keychain like so:

```console
$ sudo security add-trusted-cert -k /System/Library/Keychains/SystemRootCertificates.keychain certificate.crt
```

**Comment by Zevran** [comment]
You should use https://github.com/hashicorp/go-rootcerts that allows to load certificates stored in Login and System Keychain and not only certificates in System Roots.

As explained: https://github.com/golang/go/issues/14514#issuecomment-216690812

**Comment by sstine** [comment]
Unfortunately, @janeczku's suggestion to add the cert to the System Root Keychain requires disabling System Integrity Protection in recovery mode.  Are there any plans to implement the suggested go-rootcerts package?

**Comment by Zevran** [comment]
@sstine @janeczku I've forked [go-rancher](https://github.com/rancher/go-rancher) to update http client construction -> https://github.com/Zevran/go-rancher/commit/4ce81ecda33da8dd1edaed59bcea69d5169c309e
There aren't any contribution guide so I don't know if there is more to do to get it working.

**Comment by ikogan** [comment]
I'm having some issues with this. I tried to build a version of rancher-cli based on 0.6.4 by finding the go-rancher commit 0.6.4 was built off of, forking from there and applying your commit to that. The result of that is https://github.com/ikogan/go-rancher/tree/mac-self-signed-fix.

When I try to do `rancher --url https://internal.domain config` I get:

```
FATA[0028] Get https://internal.domain/v2-beta: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

I then try to query the same URL with curl from the same machine:

```
curl -X GET https://internal.domain/v2-beta -H 'authorization: Basic encoded-keys' 
```
This seems to work fine and responds quite quickly.

**Comment by sebastienfr** [comment]
Any news on that issue and/or the opened pull request ?

**Comment by zeidlos** [comment]
Hi, any update on this?

**Comment by deniseschannon** [comment]
As 1.6 is EOL as of June 30, 2020, we are closing 1.6 issues.
