### ISSUE TITLE
Rancher, RDS, and IAM Integration

### ISSUE THREAD

**Issue by allingeek** [rancher/rancher#8595]
Today the documentation for Rancher includes instructions for bootstrapping a MySQL database. In every case the operator uses a predetermined user and password. Operators need to automate environment configuration but must compromise security to do so. Operators provide that secret material to any management nodes via user-data, CloudFormation templates (or parameters), or other automation tooling. **This is tragic because the username and password become difficult to rotate. Users store the secrets in cleartext, and in some terrible cases source control.**

The proper solution on AWS is to leverage [IAM database authentication](http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.html). Doing so would allow AWS to generate and rotate secrets automatically, push database communication over SSL, and drop any database bootstrapping requirements (you can already seed the initial database, this would allow you to seed user access).

Database security is a serious matter for businesses of any size, but cliché configuration shortcomings like these can be show stoppers for a major enterprise.

**Comment by vincent99** [comment]
We generally avoid provider-specific integration in any of the core code... Couldn't this be done with a generic local proxy and no Cattle/client change?

**Comment by allingeek** [comment]
I completely understand the hesitance. However, there are few providers that actually offer a complete solution like AWS does. I'm not sure that running a local proxy which forwards unauthenticated requests over SSL to be executed as an admin user would fly with enterprise customers any more than cleartext passwords. The authentication mullet proxy - if such a thing exists today - would be a fantastic opportunity for misconfiguration.

The majority of my clients use AWS and of my clients exactly 0% want to run their own databases. Integrating with RDS this way makes it easier to adopt Rancher securely on AWS than not. The superior provisioning experience alone would be worth the integration. Avoiding cleartext root database user credentials is a really nice benefit.

**Comment by cloudnautique** [comment]
I'm not very familiar with this part of AWS, but if there is a standalone service that can manage/broker credentials on container starts, then it would be pretty straightforward to inject them. 

https://github.com/rancher/rancher/blob/master/server/artifacts/cattle.sh#L59

**Comment by allingeek** [comment]
I hoped that I could do this when I was reading about IAM DB credentials, but unfortunately the integration requires that clients use token based authentication (generated using EC2 instance role credentials and db parameters). There is a code sample for Java [here](http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.html#UsingWithRDS.IAMDBAuth.Getting). 

The other pile of suck that I just came across is that RDS instances use certs signed with a specific CA. I had hoped that they were signed with Amazon's public CA so that we could avoid injecting custom trust stores. [That does not seem to be the case](http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL.html).

**Comment by vincent99** [comment]
If you're already executing code on the host or in the server container then you can just make your own request to get credentials from RDS and talk to it directly.  Having a separate process do that work for you and present a (local) interface compatible with the standard client doesn't fundamentally change the security.

**Comment by vincent99** [comment]
FWIW <15% of active Rancher installs (opted in to telemetry) have their server container on AWS.

**Comment by allingeek** [comment]
Your point about the local proxy is well taken. However, its still not a good idea for all the same reasons that running with unauthenticated local connections on LAMP stacks was a bad idea. It is way too easy to accidentally bind to the wrong interface

Interesting to see the data on the Rancher install base. I would never have guessed. Have those numbers been sanitized for "demo" environments or workstation installs? Is longevity measured? I can't count the number of Rancher labs I've setup in the past.

Anecdotally many AWS users I know are on ECS because its a default solution. I'd hope that is a mindset that Rancher can help change. Making it simple install while getting the most from AWS RDS authentication would be a nice way to further that story.

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
