### ISSUE TITLE
When upgrading k8s stacks using rancher-cli , rancher-ingress-controller/rancher-kubernetes-agent continue to be in "active" state. 

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#8597]
Rancher Versions: v1.5.6

K8s environment with 3 hosts.

Steps to reproduce the problem:

Force upgrade K8s stack using rancher cli  , using command ```rancher up --stack kubernetes --force-upgrade -d ```

Even after waiting for 20 mts , rancher-ingress-controller/rancher-kubernetes-agent continues to be in "active" state. I noticed that these 2 services go "unhealthy" and get back to "active" state when etcd is getting upgraded. All other services in the stack get to "upgraded" state as expected.

**Comment by deniseschannon** [comment]
As a workaround, if this occurs during k8s upgrade using CLI, you will need to manually upgrade these images.
