### ISSUE TITLE
[question] deploying Rancher Server via Docker Swarm

### ISSUE THREAD

**Issue by ebr** [rancher/rancher#8599]
This may be a weird ask, but here goes: I'd like to try to deploy Rancher **Server** In HA mode on top of Docker Swarm. The rationale for that is to have a low-level orchestration layer in place for Server only, which would not require any existing external resources, e.g. a database or a discovery endpoint.

The catch is that each Rancher Server node in HA mode has to be launched with its unique `--advertise-address` option. I am stuck trying to find a way of getting that set up on Swarm, as `docker service create` command does not provide for any way of specifying this value per host.

Any ideas would be appreciated!

**Comment by vvetu** [comment]
Any progress? I'm in the same situation...
