### ISSUE TITLE
Rancher HA server default log levels + sensible information

### ISSUE THREAD

**Issue by zot24** [rancher/rancher#8605]
**Rancher Versions:**
Server:
healthcheck: 0.2.3
ipsec: holder
network-services: metadata 0.9.1 network-manager 0.6.6
scheduler: 0.7.5
kubernetes (if applicable):

**Docker Version:**

The default on Rancher OS 1.0.1

**OS and where are the hosts located? (cloud, bare metal, etc):**

AWS cloud using Rancher OS 1.0.1

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

HA rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

N/A

**Steps to Reproduce:**

Run Rancher HA with the following configuration

```
#cloud-config
write_files:
- content: |
    #!/bin/bash
    wait-for-docker
    docker run -d --restart=unless-stopped \
      --name=rancher-ha-server \
      --log-driver=gelf \
      --log-opt gelf-address=udp://${gelf_address}:${gelf_port} \
      -p 8080:8080 -p 9345:9345 \
      rancher/server:${rancher_version} \
      --db-host ${db_host} \
      --db-name ${db_name} \
      --db-port ${db_port} \
      --db-user ${db_user} \
      --db-pass ${db_pass} \
      --advertise-address $(ip route get 8.8.8.8 | awk '{print $NF;exit}')
  path: /etc/rc.local
  permissions: "0500"
  owner: root
```

> Notice the `docker log driver` is `GELF`

**Results:** 

Rancher by default log `info` messages revealing sensible data as you can see on the image below, the `command` that initialise rancher it's shown multiple times in plain text with all the credentials to our database.

<img width="1412" alt="screen_shot_2017-04-27_at_14_34_17" src="https://cloud.githubusercontent.com/assets/678498/25496403/bd037150-2b78-11e7-8bd8-b4ee58f1143e.png">

Is there a way to set the default log level to else `error`?

I commented in here as well about this problem https://forums.rancher.com/t/rancher-ha-default-log-levels/6253/3

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
