### ISSUE TITLE
Label Selector tweaks for SNI/SSL Needed.

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#8609]
**Rancher Versions:**
Server: v1.5.6

**Details:**
We recommend that users run a load balancer outside of Rancher that points to every host in an autoscaling group or on some dedicated nodes. These LBs are configured to point at common ports (80,443, etc) where a Rancher load balancer is running. The Rancher load balancer is often responsible for routing traffic to all services in the Rancher environment that need to be exposed publicly. This is possible because of host and path based routing capabilities for HTTP traffic. 

Operationally, there is the potential for a challenge if people have to manage adding host/path rules into the load balancer to add/remove services. Typically, the operators of Rancher would manage this primary ingress point. With selectors this becomes a lot easier, because it is able to gather the configuration from the services in the stacks.

 The new problem occurs when you want to use SSL and terminate the SSL at the individual stack LBs. Pointing to stack level load balancers reduces the number of reloads of the primary ingress  during service deployments. It isolates the impact of reloads to the stack load balancers. The flow looks something like:

[ELB]->[Rancher Global LB]->[Stack LB]->[Service]

The current behavior, when you try to apply the selector for the global lb to the stack lb, the configuration for the HA Proxy lbs do not end up routing traffic to the service. The `lb_config` information on the stack lb seems to confuse the global lb config, and it can not handle the merging in the controller.

I tried to move the lb_config to the service, and put a selector rule on the stack lb, but that didn't seem to work either.

Ultimately, the end goal is to have a global lb that supports SNI and allows routing to stack level load balancers handling SSL termination.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
