### ISSUE TITLE
Issue finishing upgrade or rollback if container is deleted during process

### ISSUE THREAD

**Issue by Robbie1977** [rancher/rancher#8611]
```Finishing-Upgrade (State [purged] is not valid for process [instance.stop:104155] on resource [1991])```

I've managed to get stuck in a loop where neither the upgrade or the rollback will complete as it's trying to delete a container that has already been (manually - sorry!) deleted.

It probably should just accept the purged state (skip the delete) and continue as this is what it was trying to achieve in the first place. 

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.5.3` Cattle: `v0.177.10` UI: `v1.5.8` |
|Access|`github` `admin`|
|Orchestration|`Cattle`|
|Route|`authenticated.project.help`|

**Comment by deniseschannon** [comment]
Duplicate of https://github.com/rancher/rancher/issues/8601
