### ISSUE TITLE
Label Name changes

### ISSUE THREAD

**Issue by StrongMonkey** [rancher/rancher#8612]
We changed the name of the label we put to detect an AWS instance. Now if host is an AWS instance we automatically populate `io.rancher.host.provider`, `io.rancher.host.region` and `io.rancher.host.zone` to it. If a EBS volume is created on a specific zone(east), the container using the volume will be scheduled a hard affinity rule `io.rancher.scheduler.affinity:host_label: io.rancher.host.zone=east`. @soumyalj Can you verify this?

**Comment by soumyalj** [comment]
Tested with v1.6.0-rc2. AWS instances are automatically populated with labels io.rancher.host.provider, io.rancher.host.region and io.rancher.host.zone. When EBS volume is created on a specific ```zone```, the containers using the volume will have the scheduling set to io.rancher.scheduler.affinity:host_label: io.rancher.host.zone = ```zone```(east,west etc)
