### ISSUE TITLE
Not able to launch Dashboard UI after upgrading rancher-server.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#8613]
Rancher server version - v1.5.7-rc3

Steps to reproduce the problem:

Kubernetes setup with 3 hosts with rancher-server version - v1.5.7-rc2

Force upgrades was done multiple times on k8s stack. One of the attempts had  services stuck in “Finising-upgrade” state  - https://github.com/rancher/rancher/issues/8601

Upgraded to v1.5.7-rc3 , after which the service that was stuck in “Finising-upgrade” got to "active" state.

After this , we are not able to launch the Dashboard anymore.
Following errors seen in rancher-server logs:
```
time="2017-04-28T05:56:01Z" level=error msg="Error looking up token." error="HTTP error: 404 Not Found, 404" 
time="2017-04-28T05:56:35Z" level=error msg="Error looking up token." error="HTTP error: 404 Not Found, 404" 
time="2017-04-28T05:58:05Z" level=error msg="Error looking up token." error="HTTP error: 404 Not Found, 404" 
time="2017-04-28T05:58:38Z" level=error msg="Error looking up token." error="HTTP error: 404 Not Found, 404"
```

**Comment by deniseschannon** [comment]
Have been unable to hit this issue in upgrading multiple k8s setups.
