### ISSUE TITLE
java HeapDumpOnOutOfMemoryError

### ISSUE THREAD

**Issue by wmbutler** [rancher/rancher#8620]
**Rancher Versions:**
Server: 1.5.6
healthcheck: 0.2.3
ipsec: No indication
network-services: 0.9.1 metadata, 0.7.0 network-manager
scheduler: 0.7.5
kubernetes (if applicable): N/A

**Docker Version:**
1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04.2 LTS, Cloud, AWS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node Rancher, External DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
- Install xenial AWS image `ami-17ba2a77`, m4.xlarge
- Login to the server and send these commands.

```
#!/bin/bash
INSTANCE_ID=`/usr/bin/curl -s http://169.254.169.254/latest/meta-data/instance-id`
echo cavo-rancher-server > /etc/hostname; hostname -F /etc/hostname
apt-get install -y docker.io
docker run -d --restart=unless-stopped -p 8080:8080 rancher/server:stable \
--db-host mysql.host.ip \
--db-port 3306 --db-user cattle --db-pass PASSWORD --db-name cattle
```
- Install htop
```
sudo apt-get install htop
```
- run htop

**Results:** 

Full writeup:

https://forums.rancher.com/t/rancher-server-errors-in-xenial-when-looking-at-htop/6263

**Comment by aemneina** [comment]
In the logs provided I dont see any complaints about memory... and your host seems to have more than enough resources available. The logs provided look like there are ailing (flapping) services in this deployment... is there a screen cap of the processes tab under the admin section? How do the infrastructure stacks look, are they healthy?

**Comment by Epiclemonaid** [comment]
running into the same error 
![screen shot 2017-07-24 at 6 15 09 pm](https://user-images.githubusercontent.com/11666664/28550453-192255fe-709e-11e7-81cf-8ce9fa427b97.png)

**Comment by TheBoroer** [comment]
Were you guys using VXLAN between the hosts when you saw this error? I switched my hosts from IPsec to VXLAN and then started seeing this issue so I'm wondering if it's something with vxlan?

**Comment by superseb** [comment]
Closing this issue as stale.

@TheBoroer Can you file a new issue with the versions used so we can investigate if you are experiencing issues?

**Comment by jpoa** [comment]
Getting the same situation on a 1.6.26 fresh install.

![2019-03-20-143936_1920x1080_scrot](https://user-images.githubusercontent.com/1116028/54688526-141c1e80-4b1e-11e9-8225-0a4311bfe9ea.png)

Also guessing that now with version 2 out this will not get so much attention, if any.
