### ISSUE TITLE
[rancher-dns] feasible for RFC2136 provider to use a subdomain without a distinct zone?

### ISSUE THREAD

**Issue by csnavely** [rancher/rancher#8621]
**Rancher Versions:**
Server: 1.5.6
healthcheck: 0.2.3
ipsec: 0.0.7
network-services: 0.1.2
scheduler: 0.5.1
kubernetes (if applicable): n/a

**Docker Version:**
1.13.1

**OS and where are the hosts located? (cloud, bare metal, etc):**
CentOS 7 / VMware

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node, external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Deploy external-dns with the RFC2136 provider using a zone name of a subdomain (foo.bar.com) that is not a distinct zone with its own SOA, but instead, was simply issued a key with permission to create A, AAAA, and TXT records, eg:

  grant rancher-key. subdomain foo.bar.com. A AAAA TXT;

Policy, management, and technical constraints in our environment make creating distinct zones for subdomains difficult. Our DNS admins would like for the RFC2136 provider to act more like a DHCP server: namely, to not require an initial AXFR, and to only issue record creation requests within the subdomain.

Is this feasible? (I suspect that it hampers the provider's ability to baseline upon startup.)

**Results:** 
Initialization throws "bad authentication" error during initial AXFR. (The key is known to be correct.) The error appears to occur when the domain of the SOA (eg bar.com) mismatches the configured zone name (eg foo.bar.com). Subsequent record creation fails and the subsystem loops endlessly.

4/7/2017 12:21:58 PMtime="2017-04-07T19:21:58Z" level=info msg="Starting Rancher External DNS service"
4/7/2017 12:21:58 PMtime="2017-04-07T19:21:58Z" level=info msg="Configured RFC2136 with zone 'test.spin.nersc.gov.' and nameserver 'nsx.lbl.gov:53'"
4/7/2017 12:21:58 PMtime="2017-04-07T19:21:58Z" level=info msg="Healthcheck handler is listening on :1000"
4/7/2017 12:21:58 PMtime="2017-04-07T19:21:58Z" level=error msg="AXFR envelope error: dns: bad authentication"
4/7/2017 12:22:00 PMtime="2017-04-07T19:22:00Z" level=error msg="AXFR envelope error: dns: bad authentication"
[...]
4/7/2017 12:22:00 PMtime="2017-04-07T19:22:00Z" level=error msg="Failed to add DNS record to provider {...}: RFC2136 query failed: dns: bad authentication"

(end)

**Comment by csnavely** [comment]
Humbly pinging @janeczku for a rough sense of feasibility on this, or help directing to the right community member. Thanks!

**Comment by janeczku** [comment]
@csnavely, external-dns expects the configured zone name to the zone apex. And since AXFR works at the zone scope but you are using a subdomain (foo.bar.com) the authentication failure is expected.
I guess it would be feasible to support this subdomain use case. We would have to add an additional configuration parameter to specify the zone apex of the subdomain under which records should be created.
I don't know about the second requirement though (not using AXFR at all). External-dns needs to know what records currently exist on the nameserver when it does the initial sync.

**Comment by csnavely** [comment]
Thanks for the feedback; that was my conclusion as well wrt the initial AXFR. I'll talk a little more with folks here to see how our requirements might be adapted.

**Comment by csnavely** [comment]
Just to follow up, we were able to set up a scheme that defined distinct zones for the subdomains we wanted our DNS records to be created within, so it all works as expected. Thanks for confirming the nature of the problem!

**Comment by gaddamas** [comment]
how is the subdomain problem solved? looking for a way to dynamically create zones for subdomains.
assuming external-dns rfc2136 zone is internal.example.com, can external-dns creates subdomain records (like host1.cluste-a.internal.example.com) in rfc2136 provider which is setup for zone 
internal.example.com?

**Comment by csnavely** [comment]
You control the format of the A record created, so you can have it go several levels deep. Check out the documentation for the catalog entry and the form to add the service to see how to customize it.
