### ISSUE TITLE
[external-dns] Cloudflare container stops working

### ISSUE THREAD

**Issue by hanselke** [rancher/rancher#8622]
**Rancher Versions:
Server:1.5.6
healthcheck:0.2.3
ipsec: rancher/net:holder ( says 0 when i look in view in API)
network-services: metadata:v0.9.1 network-manager:0.6.6
scheduler: 0.7.5
kubernetes (if applicable):
** docker version on rancher server
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:14:09 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:14:09 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Docker Version on host
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   d5236f0
 Built:        Wed Apr 26 21:47:57 2017
 OS/Arch:      linux/amd64
Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   d5236f0
 Built:        Wed Apr 26 21:47:57 2017
 OS/Arch:      linux/amd64

**OS and where are the hosts located? (cloud, bare metal, etc):**
Container Linux by CoreOS stable (1353.7.0)
Google compute engine

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher with external DB on ubuntu16.04.2
3 hosts on GCE on CoreOS

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
cattle

**Steps to Reproduce:**
Run Cloudflare DNS from catalog

Launch new catalog packages then stop for a while

**Results:** 

Cloudflare container stops updating, which you can see via logs. 

Restarting the container makes it work for a while, but then it hangs again after a while.

Dont know how to debug it as i dont see any logs in the container

**Comment by superseb** [comment]
Did you get any further on this @hanselke ?

**Comment by superseb** [comment]
Let me know if I can assist on this
