### ISSUE TITLE
rancher-compose won't update services of type external-service

### ISSUE THREAD

**Issue by sra** [rancher/rancher#8623]
**Rancher Versions:**
Server: 1.5.7
healthcheck: 0.2.3
ipsec: 0.11.2
network-services: 0.9.1,0.6.6
scheduler: 0.7.5
kubernetes (if applicable): NA

**Docker Version:**

17.03.1-ce

**OS and where are the hosts located? (cloud, bare metal, etc):**

RancherOS 1.0.1 on AWS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher behind AWS ALB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

Cattle

**Steps to Reproduce:**

Deploy a docker compose stack containing a service pointing to an external host alias:

docker-compose.yml:

```
version: '2'
services:
  dbserver:
    image: rancher/external-service
```
rancher-compose.yml:
```
version: '2'
services: 
 dbserver:
    hostname: example.com
```

Deploy:

```
rancher-compose --project-name scott-test -f docker-compose.yml -r rancher-compose.yml up -d
INFO[0000] Creating stack scott-test
INFO[0000] [0/1] [dbserver]: Creating
INFO[0000] Creating service dbserver
INFO[0000] [0/1] [dbserver]: Created
INFO[0000] [0/1] [dbserver]: Starting
INFO[0002] [1/1] [dbserver]: Started
```

Edit `rancher-compose.yml` to change the hostname to something else and deploy again.

```
rancher-compose --project-name scott-test -f docker-compose.yml -r rancher-compose.yml up -d -u
INFO[0000] [0/1] [dbserver]: Creating
INFO[0000] [0/1] [dbserver]: Created
INFO[0000] [0/1] [dbserver]: Starting
INFO[0000] [1/1] [dbserver]: Started
```

Note that the service alias remains the original value. Try using force upgrade:

```
rancher-compose --project-name scott-test -f docker-compose.yml -r rancher-compose.yml up -d -u --force-recreate
INFO[0000] [0/1] [dbserver]: Creating
INFO[0000] [0/1] [dbserver]: Created
INFO[0000] [0/1] [dbserver]: Starting
INFO[0000] [1/1] [dbserver]: Started
```
**Results:** 

The service alias will never change until it is deleted.

It appears that this is intended behavior because the code explicitly returns false to "shouldUpgrade" in the case of these external services. https://github.com/rancher/rancher-compose/blame/master/rancher/upgrade.go#L36 

It is, however, fairly frustrating in practice.

**Comment by niallthomson** [comment]
This has been causing issues for us as well, we've had to create a wrapper utility to allow us to update these services via the API.

**Comment by joshwget** [comment]
This is largely the same as #8175. Closing in favor of that.
