### ISSUE TITLE
Catalog fails to load in UI (time out)

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#8624]
**Rancher Versions:**
Server: 1.5.4
scheduler:
cattle

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
On-premise HA rancher with RDS Aurora database in AWS (12 network hops between server and DB)

**Steps to Reproduce:**
a) In the UI click on Catalog -> All
b) In the UI click on Catalog -> Community

**Results:** 
a) 504 gateway timeout page appears after 30 seconds
b) Sometimes catalog is displayed after a load time short of 30 seconds

Even after setting `logback.root.level` to TRACE and replicating the issue no log entries relating to the catalog timeout were printed.

<img width="934" alt="catalog-timedout" src="https://cloud.githubusercontent.com/assets/3813921/25581310/5f15f006-2e87-11e7-8c22-6bdad771b20b.png">

**Comment by vincent99** [comment]
That is from the SSL termination device or proxy in between.  Probably Apache from the message.  There is no timeout in Rancher.

**Comment by janeczku** [comment]
@vincent99 Correct, haproxy timeout is set to 30 sec. The issue is that the catalog page should not take 30+ seconds to load in the first place.

**Comment by deniseschannon** [comment]
Verified that this is working significantly faster and no longer an issue with this on-premise setup.
