### ISSUE TITLE
LDAP service account password not masked in the API

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#8625]
**Rancher Versions:**
Server: 1.5.4

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
1. Enable Active Directory LDAP authentication
2. Navigate to `/v2-beta/settings/api.auth.ldap.service.account.password`

**Actual Result:** 
The current LDAP service account password is returned as a rseponse from API as clear text

**Expected Result:** 
Password should not be in API return

**Comment by mrajashree** [comment]
This affects all providers. But settings are encrypted only for AD, Github and SAML. None of the provider specific settings such as `api.auth.ldap...` or `api.auth.github...` or `api.auth.shibboleth...` will be stored in setting table. For all providers, AD, openldap, github, azure, the secret value settings such as `"api.auth.ldap.service.account.password", "api.auth.ldap.openldap.service.account.password", "api.auth.azure.admin.password", "api.auth.github.client.secret"` should not be returned in plaintext via api calls

**Comment by sangeethah** [comment]
Following tests done with rancher/server version - 1.6.6-rc2

1. Upgraded  github auth enabled setup:

Have github enabled setup in v1.6.5
v2-beta/settings/api.auth.github.client.secret —> returns in clear text
Upgrade to 1.6.6-rc2
v2-beta/settings/api.auth.github.client.secret -> return null
Encryted password is stored in generic_object in DB.
Able to add more users to environment successfully.

2. Fresh install  of 1.6.6-rc2 with github enabled:
Encryted password is stored in generic_object in DB.
v2-beta/settings/api.auth.github.client.secret -> return null


3. Upgraded  AD auth enabled  setup:

Have AD setup in v1.6.5
/v2-beta/settings/api.auth.ldap.service.account.password -> returned in clear text

4. Upgrade to 1.6.6-rc2

/v2-beta/settings/api.auth.ldap.service.account.password - returns null

Encryted password is stored in generic_object in DB.


5. Upgraded   Open LAD auth enabled  setup:

Have Open LAD setup in v1.6.5

/v2-beta/settings/api.auth.ldap.openldap.service.account.password -> returned in clear text

Upgrade to 1.6.6-rc2

v2-beta/settings/api.auth.ldap.openldap.service.account.password -> returns null

There is no encryption of password in this case. 

6.Fresh install  of 1.6.6-rc2 with SAML auth(Ping Federator)  enabled:

SAML related settings are encrypted and generic_object in DB.

**Comment by deniseschannon** [comment]
Available in v1.6.8-rc1

**Comment by sangeethah** [comment]
Tested with rancher-server version - v1.6.8-rc1

1. Fresh install of 1.6.8-rc1 with AD auth enabled:
Encryted password is stored in generic_object in DB.
v2-beta/settings/api.auth.ldap.service.account.password -> returns null

2. Fresh install of 1.6.7 with AD auth enabled upgraded to 1.6.8-rc1.
Encryted password is stored in generic_object in DB. 
v2-beta/settings/api.auth.ldap.service.account.password -> returns null

**Comment by galal-hussein** [comment]
Rancher Server: v1.6.8-rc3

1- Fresh installation of 1.6.8-rc3 with AD enabled `v2-beta/settings/api.auth.ldap.service.account.password` -> returns null

2. Upgraded version of AD from 1.6.7 to 1.6.8-rc3, before upgrade the `v2-beta/settings/api.auth.ldap.service.account.password` -> returns password in clear text, after upgrade it returns null
