### ISSUE TITLE
Orchestrating mix of docker & non docker applications

### ISSUE THREAD

**Issue by hanselke** [rancher/rancher#8630]
Hi,

Use Case: Rancher Catalog to launch Dockerized containers as well as execute commands in Linux host with legacy multi tenent application

So I'm using docker in order to run many single tenent applications for various clients. However, as part of my stack i also have a multi tenent application that is just a pain in the butt to run in docker, and to keep it maintained as components keep changing.

So the legacy application uses DNS based routing, and only uses http & https ports.

The idea is that i would install a rancher agent on it, and then execute a run once container that sends a command to the host to execute "app add new user ${clientid}". I get ${clientid} from rancher catalog.

Is this as simple as building a docker image with CMD: app add new user ?

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
