### ISSUE TITLE
[UI] host health feedback

### ISSUE THREAD

**Issue by kaos** [rancher/rancher#8632]
When the healthchecks for a host reports unhealthy, wouldn't it be fitting to reflect this in the UI?

Output from a healthcheck instance:

```
"healthcheckStates": [ 3 items
{
"hostId": "1h110",
"healthState": "healthy"
},
{
"hostId": "1h65",
"healthState": "healthy"
},
{
"hostId": "1h338",
"healthState": "unhealthy"
}
]
```

The `1h338` was showing a green `Active` on the hosts page.. although all healthcheck instances reported it as unhealthy..

Also, is there any information available, as to what is unhealthy about it?
In this case, I knew what it was, but one can easily imagine a scenario where that would not be the case ;)

**Comment by aemneina** [comment]
Healthchecks are for health checking services and not hosts. This should show degraded at the environment level, I believe.

**Comment by kaos** [comment]
Ah, right. Will check next time I see it..

**Comment by superseb** [comment]
I think this will explain the output from the API:

`When health checks are enabled either on an individual container or a service, each container is then monitored by up to three healthcheck containers running on separate hosts. The container is considered healthy if at least one HAProxy instance reports a “passed” health check and it is considered unhealthy when all HAProxy instances report a “unhealthy” health check.`

Do you want to drill down in the UI to see every healthcheck instantiated in containers from up to 3 hosts @kaos ?

**Comment by kaos** [comment]
Something like that would be nice. Somewhere to check the status of
services would be helpful when trouble shooting.
tors 18 maj 2017 kl. 15:01 skrev Sebastiaan van Steenis <
notifications@github.com>:

**Comment by vincent99** [comment]
I don't see how exposing the individual check status is particularly useful enough to expose in the UI.  Maybe if there was something more useful to show like the response code/body.

As-is it's maybe an indirect way to debug a problem that is actually with the healthcheck host/container and not the target service.
