### ISSUE TITLE
[webhook]

### ISSUE THREAD

**Issue by hanselke** [rancher/rancher#8634]
would be really useful if there can be a web hook to launch a new stack from a catalog.

**Comment by mrajashree** [comment]
@hanselke Launch a new stack in response to any particular event?

**Comment by hanselke** [comment]
i'm using an API call now to launch stacks when stripe payments are made. does the job, but would be nice if there was a webhook instead.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
