### ISSUE TITLE
Cattle w/ vxlan Hosts unable to communicate.

### ISSUE THREAD

**Issue by HcgRandon** [rancher/rancher#8635]
**Rancher Versions:**
Server: v1.5.7
healthcheck: v0.2.3
ipsec: n/a
network-services: metadata = v0.2.3, network manager = v0.6.6
scheduler: v0.7.5
kubernetes (if applicable):

**Docker Version:**
17.03.0-ce x 2
17.03.1-ce x 1
17.04.0-ce x 1

**OS and where are the hosts located? (cloud, bare metal, etc):**
Debian 8 x 4
bare metal

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle w/ vxlan

**Steps to Reproduce:**
Simply running Cattle with vxlan 0.0.7

**Results:** 
Hosts are not able to communicate at all. Tried again multiple times. Switching to ipsec works perfectly.

**Comment by leodotcloud** [comment]
The fix for this went in `rancher/network-manager:v0.7.0`

**Comment by leodotcloud** [comment]
Same as https://github.com/rancher/rancher/issues/8496

**Comment by HcgRandon** [comment]
Thanks, I updated my network manager manually. However I am now having massive issues with all my containers talking.

I have about 64 runner processes. That talk back to a master. When using the internal service mapping stuff is extremely broken. Some runners can talk to the main process. some can't and its not limited to nodes. For example 4 from node 1 can join. and then 20 from node 2 etc. its really annoying. Any thoughts?

**Comment by perunb** [comment]
We have the same issue with Ubuntu 14 and 16, Cattle and VxLan.
We've tried it with Rancher 1.5.3-1.6.0 (standalone mode) and Docker versions 1.12.6 - 17.03.1-ce > no success.

**Comment by niusmallnan** [comment]
@leodotcloud 
I think this might be another issue. In Docker 1.12 and earlier, the default FORWARD chain policy was ACCEPT. But Docker 1.13+ sets the default policy of the FORWARD chain to DROP.

VXLAN network requires FORWARD chain to complete cross host communication.

Here is the Docker [doc](https://docs.docker.com/engine/userguide/networking/default_network/container-communication/#container-communication-between-hosts)

I submit a PR to fix it. https://github.com/rancher/plugin-manager/pull/72

**Comment by perunb** [comment]
Thx a lot niusmallnan :)
with "sudo iptables -P FORWARD ACCEPT" at the hosts it works (Ubuntu 14)

**Comment by superseb** [comment]
@niusmallnan nice find 👍 , @leodotcloud PTAL :)

**Comment by dahendel** [comment]
@superseb Thanks for the referral to this issue. We came to the same conclusion and changed the iptables rule from drop to accept.

**Comment by gsf-greece** [comment]
After upgrading to v1.6.2 to avoid the healthcheck stucking issue, containers can't communicate with each other even if they are on the same host.

Since I'm only a user of the rancher service, I can't really give more details right now. Is this issue still open because it is a known bug, or we should start investigating the vxlan configuration?

**Comment by leodotcloud** [comment]
Fixed in Network Services v0.2.2, network-manager:v0.7.2.

**Comment by sangeethah** [comment]
Tested with Rancher server version - v1.6.3-rc1 using Network Services v0.2.2 and  network-manager:v0.7.3.

Cross host networking works fine both with docker version 17.05.0-ce (Ubuntu 16.04.2) and docker 1.13.1(Ubuntu 16.04.2).
