### ISSUE TITLE
Error message is misleading when allocation fails due to port already in use

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#8636]
**Rancher Versions:**
Server: 1.5.4
Scheduler: v0.6.3
Cattle

Regression from 1.2 (https://github.com/rancher/rancher/issues/6249#issuecomment-256727493)

**Steps to Reproduce:**
1. Given that:

- There is 1 host in the environment that has a label of "foo=true"
- Port 8086/tcp is already bound on that host by an existing service

2. Create a new service using the following docker-compose.yml:

```Docker
version: '2'
services:
  test:
    image: ubuntu:14.04
    tty: true
    ports:
    - 8086:8086/tcp
    labels:
      io.rancher.scheduler.affinity:host_label: foo=true
```

**Expected Result:**
Service startup should fail with error indicating that allocation failed due to non available host port 8086

**Actual Result:**
Service startup fails with the following error message:

> Failed to allocate instance [container:1i13038]: Bad instance [container:1i13038] in state [stopping]: Allocation failed: needs host with label foo: true

**Comment by StrongMonkey** [comment]
After the fix, error message will be something like this:
`Allocation failed: needs host with label foo: bar, ResourceRequests: [ports: [8080:8080/tcp], ResourceType: instanceReservation, Amount: 1]`

**Comment by StrongMonkey** [comment]
Available at cattle@master

**Comment by soumyalj** [comment]
Tested with 1.6.1-rc8. On a setup with two hosts h1 and h2. h1 has label foo=true set. Created a service test1 with exposed port 8086 and scheduling set to host with label foo=true. Created another stack as below:
```
version: '2'
services:
  test:
    image: ubuntu:14.04
    tty: true
    ports:
    - 8086:8086/tcp
    labels:
      io.rancher.scheduler.affinity:host_label: foo=true

```
The service creation failed with the error including all the constraints as expected 
```
test (Failed to allocate instance [container:1i75]: Bad instance [container:1i75] in state [error]: Allocation failed: needs host with label foo: true and resource constraints: [8086:8086/tcp portReservation, 1 instanceReservation]) 
```
For the same use case, on a host with one setup, the error message does not include all the constraints(The host label constraint foo=true is ignored)
```
(Failed to allocate instance [container:1i82]: Bad instance [container:1i82] in state [error]: Allocation failed: No healthy hosts meet the resource constraints: [8086:8086/tcp portReservation, 1 instanceReservation])
```

**Comment by cjellick** [comment]
This is ok/expected behavior. In the second scenario there are _no_ valid hosts based solely on the port requested, regardless of the label. So, we never get to the point of evaluating the label constraints. This is an optimization designed to eliminate unnecessary DB calls.
