### ISSUE TITLE
[external-dns] Service FQDN property is not updated when using custom naming template

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#8641]
**Rancher Versions:**
Server: 1.5.4
external-dns: v0.6.3

When using a DNS name template that does not begin with `%{{serviceName}}.%{{stackName}}` the FQDN property for the service is not updated in Cattle.

**Comment by deniseschannon** [comment]
Available in the catalog at the branch `external-dnsv070`.

Using external-dns:v0.7.0. 

Please test on 1.5.10 and 1.6.2.

**Comment by deniseschannon** [comment]
Available in `external-dnsv070` branch of rancher catalog. 

Can we make sure to test in v1.5 and in v1.6 (different templates due to templating changes in code)?

**Comment by galal-hussein** [comment]
Rancher server: v1.6.2 and v1.5.10
External DNS: v0.7.0

I started the external dns with custom service name and i can see the FQDN property is updated with the custom name:

`"fqdn": "test15wekandb.wekan.default.rancher-test.com",`
