### ISSUE TITLE
VolumeTemplate name uniqueness is enforced across all environments

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#8642]
**Rancher Versions:**
Server: v1.6.0-rc3

**Steps to Reproduce:**
1. Create two environments
2. In the first, using the cli create a stack that has an external volume with name "foo" (or whatever)
3. In the second environment, create the same exact stack being sure to use the same name for the external volume

**Results:** 
Actual:
You get a "Not Unique" API error when creating the stack in the second environment when the cli attempts to create a volumeTemplate for foo
Expected:
VolumeTemplate name uniqueness should be enforced at the environment level, so you should be able to have duplicate volumeTemplate names as long as they are in different environments

**Comment by sangeethah** [comment]
Tested with Rancher Server build from master

Create two environments.

In the first environment, using the cli create a stack that has an external volume with name "mynewvol" using the following yml.
```
version: '2'
volumes:
  mynewvol:
    external: true
    driver: rancher-nfs
services:
  testnginx:
    image: nginx
    volumes:
    - mynewvol:/testme
```
In the second environment, create a stack using the same yml which uses the same external volume.
Able to create stack successfully.

Able to see 2 volumeTemplates with the same name being created.

```
|  3 | mynewvol |          5 | volumeTemplate | 9ff6cc2c-b407-45c0-a408-06b94ec32a01 | NULL        | inactive | 2017-05-24 23:54:14 | NULL                | NULL                | {}   | rancher-nfs |             15 |         |               |
|  4 | mynewvol |         23 | volumeTemplate | d492021c-91e2-4f2e-8c30-2987add4fa10 | NULL        | inactive | 2017-05-25 00:05:57 | NULL                | NULL                | {}   | rancher-nfs |             17 |         |               |
```
