### ISSUE TITLE
How to reinstall rancher-nfs driver?

### ISSUE THREAD

**Issue by zhangalex** [rancher/rancher#8644]
Hi Guys,

Is there anybody know how to reinstall rancher nfs driver on UI ? 

Thanks.

**Comment by arjuneyy** [comment]
Hi,

1. You can do this by deleting the **nfs** stack.
![image](https://cloud.githubusercontent.com/assets/12705617/25651549/45592bca-3016-11e7-9fc3-f6bfc230bfea.png)

2. Then go to **catalog** and search for **rancher nfs**.
3. Then click **Rancher NFS** to install.

Hope this helps.

**Comment by superseb** [comment]
@arjuneyy Thanks!

@zhangalex Should do the job, let me know if you need any more help.

**Comment by zhangalex** [comment]
@arjuneyy @superseb 

thank you very much !
