### ISSUE TITLE
[UI] Volume names validation should be skipped when a volume driver is set to infinit

### ISSUE THREAD

**Issue by vberetti** [rancher/rancher#8646]
**Rancher Versions:**
UI: 1.5, 1.6, 2.0

**Docker Version:**
1.12.6

**Environment Type: Cattle**

**Steps to Reproduce:**
Some volume drivers have a format for volume name that is not compatible with the default volume name validation (introduced by this [commit](https://github.com/rancher/ui/commit/2ea037e39682bd012e5982c0f3de2f41a427ea45) ).
For example [infinit](https://infinit.sh/documentation/docker/volume-plugin) volume driver requires the volume name to be like : \<user\>/\<volume name\>
This prevents the integration of Infinit in Rancher using the UI but can apply to other volume driver as the volume name format can vary.

**Results:** 
We should be able to enter a volume name with hyphen or slash when a driver volume is set to infinit but also potentially other volume driver.

**Comment by vberetti** [comment]
I've create a pull request for 1.6 branch : https://github.com/rancher/ui/pull/1163

**Comment by vberetti** [comment]
Also created a pull request for master branch : https://github.com/rancher/ui/pull/1164

**Comment by tfiduccia** [comment]
Version - v1.6.1-rc10
If you have driver specified we do not validate the volume name
Verified fixed
