### ISSUE TITLE
Stack Updates Required Hard Refresh to Show

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#8648]
**Rancher Versions:**

Server: 1.5.4

**Steps to Reproduce:**

1. Deploy a stack from a catalog item
2. Update the catalog item
3. Refresh the catalog
4. Go back to the stack, it will not show there is an update.
5. Hard refresh your browser and when the rancher ui reloads it will show an update.

**Expected Behavior:**

If there is a catalog update when browsing the stacks, the update button should be checked against the catalog entries without having to hard reload the entire Rancher UI.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
