### ISSUE TITLE
Containers Unable to Communicate Across Hosts

### ISSUE THREAD

**Issue by nathangoulding** [rancher/rancher#8650]
**Rancher Versions:**
Server: v1.3.1
healthcheck: v0.2.0
ipsec: v0.8.1
network-manager: v0.4.0
scheduler: v0.5.1

**Docker Version:** 1.12.6

**OS and where are the hosts located?:** Container Linux Stable (1235.9.0), bare metal

**Setup Details:** HA rancher, external DB

**Environment Type:** Cattle

**Steps to Reproduce:**

Run for some number of weeks or months with multiple containers setup and linked across multiple hosts.

**Results:** 

Without warning, containers will be unable to communicate with each other.

**Comments:**

@ibuildthecloud summarizing our offline discussion and information here for tracking purposes:

```
container1 -> ipsec1 -> host1
container2 -> ipsec2 -> host2
```

- container1 is unable to ping container2 using its 10.42.x.x IP address
- ipsec1 is able to ping to container2
- tcpdump on ipsec1 sees the icmp request from container1 to container2, no icmp reply from container2
- restarting ipsec1 container resolves the issue

**Comment by ibrokethecloud** [comment]
We have noticied similar random behaviour.

A look at the ipsec-router logs shows nothing useful.

We are on rancher 1.4.1, running on an internal cloud using vmware on rhel 7.2

**Comment by leodotcloud** [comment]
@nathangoulding @ibrokethecloud We have fixed a lot of networking related issues since 1.3.x and 1.4.x. Can you please try with the latest releases?
One very relevant IPSec fix: https://github.com/rancher/rancher/issues/9377.

**Comment by leodotcloud** [comment]
Please open a new issue if you are still having problems.
