### ISSUE TITLE
CLI timeout too short

### ISSUE THREAD

**Issue by sheng-liang** [rancher/rancher#8654]
**Rancher Versions:**
1.5.8
Server:
1.5.8
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker Version:**

**OS and where are the hosts located? (cloud, bare metal, etc):**

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
Setup Rancher CLI, when there're lots of containers, commands timeout. Timeout value seems too small.
**Results:** 
```
ubuntu@ip-172-31-32-163:~/netstress$ time rancher ps -c --format json
FATA[0016] Get http://ec2-52-23-171-71.compute-1.amazonaws.com:8080/v2-beta/projects/1a5/containers?limit=-2&removed_null=1&state_ne=inactive&state_ne=stopped&state_ne=removing&system=false: net/http: request canceled (Client.Timeout exceeded while awaiting headers) 

real    0m16.422s
user    0m0.108s
sys    0m0.016s
```

**Comment by aemneina** [comment]
Configurable client timeout would be nice.

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
