### ISSUE TITLE
Upgrade does nothing

### ISSUE THREAD

**Issue by tholcman** [rancher/rancher#8658]
**Rancher Versions:**
Server: rancher/server:v1.5.3
healthcheck: 0.2.3
ipsec: 0.0.5
network-services: 0.1.2
scheduler: 0.5.1

**Docker Version:**
17.03.x-ce

**OS and where are the hosts located? (cloud, bare metal, etc):**
AWS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA 2 nodes with public IPs (primary + failover) + nginx with upstream of both servers

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Issue:**
We had 40 hosts, 1 stack, 2 global services with mapped ports, with 2 sidekicks.

We have tried to run `Upgrade` of one service with change of image tag. After 5 seconds Rancher told us `Upgraded` but did nothing. See attached screenshot of logs.

We have tried to run upgrade with 5, 4, 2 batch size and it happened almost all times. Even when we run upgrade one by one it is happening from time to time.

Sometimes it upgrades one or more batches and died telling `Upgraded` but half of instances are running with old image. In such case pressing `Finish upgrade` upgrades rest of containers by batch size.

We are facing this issue really often with almost all bigger services. There is nothing in logs of Rancher server. Where else can we look? What can we do?

![rancher-bad-upgrade](https://cloud.githubusercontent.com/assets/791679/25709946/0ed84d30-30eb-11e7-8f2d-6844dc79e9e0.png)

**Comment by MatthewHartstonge** [comment]
Hi @tholcman, did you tick the `always pull before creating` box under the 'select image' panel?
But in this case, technically, I would imagine a change of tag should automatically pull the different image...

**Comment by tholcman** [comment]
Yes, I keep this always checked. It's not unique or sporadic issue. It is happening pretty often in different environments, with different services and different upgrade options ...

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
