### ISSUE TITLE
Rancher-dns cache ignores TTL

### ISSUE THREAD

**Issue by tholcman** [rancher/rancher#8659]
**Rancher Versions:**
network-services: 0.1.2

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
cattle

**Steps to Reproduce:**
Having external DNS record with short TTL for example Amazon ELB which has TTL 60s. In any container run:
```
$ watch -n 1 dig dns-name-with-short-ttl.example.com
```
Change DNS record and `rancher-dns` will return old address for next aprox. 600s (10 minutes)

**Comment by superseb** [comment]
Thanks for reporting @tholcman. As most of the testing/workaround/discussions has been in #8805 , I'll close this one.
