### ISSUE TITLE
Improve/Provide Useful Feedback for Unhealthy Services (especially if due to scheduling conflicts)

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#8660]
Unfortunately this is the one major area of Rancher that is severely lacking in my humble opinion. 

Rancher gives little, to no useful information as to why a service is unhealthy, especially if it is because of scheduling problems.

Example: If you try and schedule a service that requires a host have a specific label, and have no hosts that meet that criteria, the service will just sit in an unhealthy state with no explanation. It'll say something like `Service already reconciled`, `Created: 0, Unhealthy: 0, Bad: 0, Incomplete: 9` and never actually mention why it is not being scheduled.

I would ask that time be spent to add in to the log exactly why services are in an unhealthy state, health checks vs scheduling problems. If scheduling problems detail why. If health check, explain why. 

Just to be clear I'm a huge fan of Rancher, I appreciate all you've done for the community and will continue to do. I do want to be honest and provide useful feedback at the same time.

**Comment by loganhz** [comment]
Now the error message is something like `Failed to allocate instance [container:1i30]: Bad instance [container:1i30] in state [error]: Allocation failed: needs host with label a: b`
