### ISSUE TITLE
System containers don't show up if no hosts

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#8662]
**Rancher Versions:** 5/4

**Steps to Reproduce:**
1.  Create a environment without hosts
2.  Go to container page and check Show System

**Results:** The system containers do not show up.
![image](https://cloud.githubusercontent.com/assets/11514927/25719784/7aee00d6-30bf-11e7-98ff-dfe0946a0a9c.png)

**Comment by MatthewHartstonge** [comment]
That's because you don't have any hosts to have system containers on!
You need a minimum of one rancher host to have any system containers to show up.

So maybe what you are after is a UI element that says: `oh no! No hosts have been set up! Set one up? <link to set up rancher host>`
