### ISSUE TITLE
Services with volumes using driver_opts(export and host) from older rancher-nfs version will not be able to mount volumes.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#8663]
Rancher server version - v1.5.8 upgraded to v1.6.0-rc5

Steps to reproduce the problem:
Fresh install of v1.5.8
Deploy rancher-nfs (rancher/storage-nfs:v0.6.5)

Create a service with volume ( test1) using rancher-nfs driver with driver_opts  (host and export) .
In this case there is no subfolder created for the volume under export directory and entire export directory is mounted.

Upgrade rancher server to  v1.6.0-rc6

After this upgrade  rancher-nfs ( rancher/storage-nfs:v0.8.2)

After upgrade , try to start a new service with the above volume - test1.
Instances that get started on hosts where this volume was not mounted previously( from the older instances before upgrade) would fail to start with the following error because of not having the expected mount directory which includes the volume name as the subfolder.

```
 Error (Error response from daemon: error while mounting volume '/var/lib/rancher/volumes/rancher-nfs/test1': VolumeDriver.Mount: Failed nsenter -t 10524 -n mount <host>:/var/nfs/test1 /var/lib/rancher/volumes/rancher-nfs/test1)
```

**Comment by LLParse** [comment]
https://github.com/rancher/storage/pull/56

**Comment by sangeethah** [comment]
@LLParse ,  I have assigned this issue back to you , since the fixes are not merged yet. 
Assign it back to me when you it is available for testing.

**Comment by deniseschannon** [comment]
@sangeethah When testing, please make sure that rancher-nfs custom NFS server driver_opts are able to  create subfolders [https://github.com/rancher/rancher/issues/7906]

**Comment by LLParse** [comment]
@deniseschannon @soumyalj This doesn't need to be validated; we never released the code that would introduce this bug. @sangeethah merely filed it so we wouldn't forget about the breaking changes. The team decided to retain the existing behavior for host/export, so this is no longer an issue.

I am going to close this one out for now.

**Comment by deniseschannon** [comment]
We should be testing this when a storage PR is merged: Create a volume with host/export driver_opts defined with the old NFS driver version, attach a container and write data, delete container, do nfs driver upgrade (to the unreleased code that you put in PR), attach a container and read data

**Comment by LLParse** [comment]
@soumyalj Please test with Rancher v1.6.2

URL: https://github.com/rancher/rancher-catalog
Branch: nfsv083

**Comment by soumyalj** [comment]
Started with v1.5.8 with rancher/storage-nfs:v0.6.5. Created a volume with host/export driver options. Created a service service1 using this volume and data was written to the container. 
Upgraded to rancher v1.6.2 and upgraded nfs to rancher/storage-nfs:v0.8.3
Created another service service2 using the same volume. No errors in service creation. Data was intact. Was able to write data to the volume and read from it.
