### ISSUE TITLE
Support configuring PingFederate Identity Provider with Rancher's Shibboleth Service Provider

### ISSUE THREAD

**Issue by mrajashree** [rancher/rancher#8665]
Rancher's Shibboleth access control uses an external go-saml library. Shibboleth and Ping are different implementations of saml. Rancher's access control had only been tested with Shibboleth Identity Provider. For Ping Identity Provider, the integration would return these errors:
```
Caused by: com.pingidentity.common.util.xml.InvalidXmlException: Invalid XML - errors: [error: cvc-complex-type.2.1: Element 'NameIDPolicy@urn:oasis:names:tc:SAML:2.0:protocol' with empty content type cannot have text or element content.]
```
and
```
2017-05-03 23:50:52,685 tid:WktR2mAgSdliSfeYuW1le459MpA ERROR [org.sourceid.saml20.profiles.idp.HandleAuthnRequest] Exception occurred during request processing
org.sourceid.saml20.profiles.StatusResponseException: ProtocolBinding:  disallowed for transport of SSO response.
```

These were because of the external go-saml library being used.
The first error of invalidXMLException was fixed changing the NameIDPolicy struct's field tags.
For the second error, a field called `ProtocolBinding` was added to a struct called AuthnRequest.

The referenced PR contains Rancher's fork of the saml library having the above fixes.

**Comment by cjellick** [comment]
@mrajashree Please start working with @sangeethah or @soumyalj on the testing scenarios

**Comment by cjellick** [comment]
Per @vincent99 the UI should be updated to show that it supports Ping Identity. @mrajashree follow up with @vincent99 on this. The feature shouldn't be considered done until that's updated (but obviously can be tested without that change)

**Comment by galal-hussein** [comment]
I did a validation test pass on the PingFederator auth service, all the test cases passed and will be written in  #8845
