### ISSUE TITLE
On Rancher Server upgrade, new Rancher hosts won't start any containers successfully

### ISSUE THREAD

**Issue by MatthewHartstonge** [rancher/rancher#8668]
**Rancher Versions:**
Server: v1.5.9
healthcheck: v0.2.3
ipsec: v0.0.5
network-services: v0.2.0
scheduler: v0.5.1
kubernetes (if applicable):

**Docker Version:**
1.12.6 - Database Hosts (Fine)
17.03.0-ce - Compute Hosts

**OS and where are the hosts located? (cloud, bare metal, etc):**
RancherOS v0.8.1 - DB
RancherOS v1.0.1 - Compute Hosts

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node Rancher, external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
- Killed rancher/server:stable
- Pulled latest rancher/server:stable
- Started rancher/server:stable
- All current hosts upgraded to agent version v1.2.2 due to rancher
- All hosts then upgraded to `Network Services` v0.2.2
- Destroyed old Compute Servers to upgrade underlying RancherOS to LTS (v1.0.1 from v0.9.1)
- New Hosts get `Timeout unable to get IP`

**Results:** 
The new version of Rancher automatically updated:
- Agents across the cluster
- Network Services

The Agent upgraded fine, but all Network Stacks were stuck in "Upgraded" state. As such, any new host that was added to the cluster would start creating the "System Services", but every container would fail due to `Timeout unable to get IP`. Turns out, due to being in the `Upgraded` state, the Rancher `Network Stack` (Metadata and Network-Manager) was not propagating to any new hosts added to the cluster. 

Being that the `Network Stack` is a dependency for **any** container managed under a Rancher Host to work, Rancher should automatically either:
* Finish the Upgrade
* Only bring up the new version, on rollback, bring up the old version
* Bring up the old version, then rollover to the new version (then be in the same state as other hosts)
* Give the user a Toaster notification saying 'Confirm Infrastructure Stack Upgrades?'

Conversely, this issue will go away when the "Upgraded" step is removed in a later version of Rancher. (Was mentioned in the last Rancher monthly meetup)

**Comment by ibuildthecloud** [comment]
The "Finish the Upgrade" step is going to be removed.  There is currently a big issue in that when in the "Upgraded" state we don't reconcile services, meaning nothing happens.  If services are left in "Upgraded" then it is effectively in a "Pause" or "Do nothing" state.  As such we are removing it.  I'm currently working on that (and a lot of other reliability issues around upgrades in general).

**Comment by ibuildthecloud** [comment]
@MatthewHartstonge Did you upgrade from Rancher <= 1.4?  The network services only auto upgrades when going from one of those versions (1.2, 1.3, 1.4).  If you upgrade now from 1.5.x to 1.6 (just released today) we won't auto upgrade anything.

**Comment by MatthewHartstonge** [comment]
@ibuildthecloud upgraded from 1.5.3 -> 1.5.9 (was staging/UAT) so didn't matter, but will be an issue to remember/know of until 1.6 is `:stable`.

**Comment by MatthewHartstonge** [comment]
Closing as will be fixed in version 1.6.X+ of Rancher. 👌
