### ISSUE TITLE
Killing router container disrupts IPSEC traffic

### ISSUE THREAD

**Issue by sheng-liang** [rancher/rancher#8670]
**Rancher Versions:**
Server: 1.5.8
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker Version:**

**OS and where are the hosts located? (cloud, bare metal, etc):**

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node server, 2 hosts.
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
1. Setup Rancher with 2 hosts.
2. Create an instance of the `shengliang/apache-php` container on each host
3. Run this command in one of the apache-php containers: 
    ```
    while true; do curl -sSf http://10.42.c.d -o /dev/null; echo `date` $?; done
    ```
    `10.42.c.d` is the IP of the other apache-php container.
4. On the host running the first apache-php container, do `docker kill` the IPSEC router container
**Results:** 
HTTP traffic is disrupted. Killing the router should not disrupt IPSEC traffic.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
