### ISSUE TITLE
Memory Usage too high

### ISSUE THREAD

**Issue by 4406arthur** [rancher/rancher#8672]
**Rancher Versions:**

Server: V1.5.7
healthcheck: rancher/healthcheck:v0.2.3
ipsec: rancher/net:holder
network-services: rancher/network-manager:v0.7.0
kubernetes:rancher/k8s:v1.5.4-rancher1-4

**Docker Version:**
 
Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:20:01 2017
 OS/Arch:      linux/amd64

**OS and where are the hosts located? (cloud, bare metal, etc):**

VM, CentOS-7.2, 3.10.0-514.16.1.el7.x86_64 

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes with 3 nodes.

**Steps to Reproduce:**

```
docker stats <YOUR-RANCHER-SERVER-CID>

```

**Results:** 
![screen shot 2017-05-05 at 3 51 11 pm](https://cloud.githubusercontent.com/assets/5071988/25737507/cfa0a048-31aa-11e7-86fd-e69624cd801a.png)

**Comment by aemneina** [comment]
Single node rancher runs cattle, websocket proxy, go machine service and a mysql database. 1GB for all of that (and orchestrating k8s) doesnt seem that high at 1gb of mem used...

**Comment by JulianKingman** [comment]
It seems too high to me, too. In the docs it lists the minimum specs as 1gb, but I'm hitting memory errors pretty consistently (this may just be temporary as I'm in the midst of migrating hosts).

**Comment by frol** [comment]
Well, given the bug in Docker stats (https://github.com/moby/moby/issues/10824 [fixed in Docker 17.06]) and in Rancher (https://github.com/rancher/rancher/issues/2953), I would re-evaluate the actual memory consumption by either updating to Docker 17.06 or by dropping the disk caches and buffers (`sh -c 'echo 3 > /proc/sys/vm/drop_caches'`) before digging into the possibly phantom memory leaks.

**Comment by djtm** [comment]
Actually, I've noted if you compare the memory statistics from rancher with those from top, you can have big differences:
449+ MB via Rancher (stable)
200 MB via `free -h` on the system.

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
