### ISSUE TITLE
Unable to create stack from the UI with secret in docker-compose.yml

### ISSUE THREAD

**Issue by courcelm** [rancher/rancher#8677]
**Rancher Versions:**
Server: 1.6.0
healthcheck: 0.3.1
ipsec: 0.1.0
network-services: 0.7.0
scheduler: 0.7.5

**Docker Version:**
17.03.1-ce

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04 on bare metal

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**

Add a stack from the UI with the following docker-compose.yml

```
version: '2'
services:
  test:
    image: ubuntu
    stdin_open: true
    tty: true
    secrets:
    - uid: '0'
      gid: '0'
      mode: '444'
      name: ''
      secretId: 1
    labels:
      io.rancher.container.pull_image: always
```

**Results:** 

Rancher UI is stuck with this message:

Activating (In Progress)

I think it would be more convenient to replace secretId with secretName.

**Comment by courcelm** [comment]
In rancher-server  log:

05/05/2017 09:15:16panic: interface conversion: interface {} is nil, not map[string]interface {}
05/05/2017 09:15:16
05/05/2017 09:15:16goroutine 52 [running]:
05/05/2017 09:15:16github.com/rancher/rancher-compose-executor/config.parseValidTypesFromSchema(0xc4202f3d40, 0xc42034cfa0, 0x15, 0x0, 0xc42034cfa0, 0x15)
05/05/2017 09:15:16	/go/src/github.com/rancher/rancher-compose-executor/config/schema_helpers.go:72 +0x73e
05/05/2017 09:15:16github.com/rancher/rancher-compose-executor/config.oneOfMessage(0xc4202175c0, 0xc4202f3d40, 0xd3f8e0, 0xc4202fcdc0, 0xd3f360, 0xc4202fcc40, 0x0, 0x4f28bf)
05/05/2017 09:15:16	/go/src/github.com/rancher/rancher-compose-executor/config/validation.go:162 +0x5d6
05/05/2017 09:15:16github.com/rancher/rancher-compose-executor/config.generateErrorMessages(0xc4202175c0, 0xc4202f3d40, 0xc42034c820, 0xc420262060, 0xc42034c820)
05/05/2017 09:15:16	/go/src/github.com/rancher/rancher-compose-executor/config/validation.go:258 +0x1069
05/05/2017 09:15:16github.com/rancher/rancher-compose-executor/config.validateV2(0xc4202f3a10, 0x0, 0xc4202f3d10)
05/05/2017 09:15:16	/go/src/github.com/rancher/rancher-compose-executor/config/validation.go:222 +0x13f
05/05/2017 09:15:16github.com/rancher/rancher-compose-executor/config.MergeServicesV2(0xc4202f0d40, 0xd36420, 0xc4203600c8, 0xd363e0, 0xd8d988, 0x0, 0x0, 0xc4202f3a10, 0xc42055a690, 0xeb, ...)
05/05/2017 09:15:16	/go/src/github.com/rancher/rancher-compose-executor/config/merge_v2.go:13 +0x43
05/05/2017 09:15:16github.com/rancher/rancher-compose-executor/config.Merge(0xc4202f0d40, 0xd36420, 0xc4203600c8, 0xd363e0, 0xd8d988, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
05/05/2017 09:15:16	/go/src/github.com/rancher/rancher-compose-executor/config/merge.go:167 +0x1173
05/05/2017 09:15:16github.com/rancher/rancher-compose-executor/project.(*Project).load(0xc42055a2d0, 0x0, 0x0, 0xc42055a1e0, 0xeb, 0xf0, 0xc4201fa540, 0xc4202f2ff0)
05/05/2017 09:15:16	/go/src/github.com/rancher/rancher-compose-executor/project/project.go:165 +0xe3
05/05/2017 09:15:16github.com/rancher/rancher-compose-executor/project.(*Project).Parse(0xc42055a2d0, 0xc42055a2d0, 0x30)
05/05/2017 09:15:16	/go/src/github.com/rancher/rancher-compose-executor/project/project.go:97 +0x15b
05/05/2017 09:15:16github.com/rancher/rancher-compose-executor/rancher.NewProject(0xc42032f6c0, 0xc4202f2d50, 0xc420567a38, 0x2)
05/05/2017 09:15:16	/go/src/github.com/rancher/rancher-compose-executor/rancher/project.go:35 +0x26d
05/05/2017 09:15:16github.com/rancher/rancher-compose-executor/executor/handlers.constructProject(0xc420018a40, 0xc4200a2000, 0xc420221f60, 0x1d, 0xc420016012, 0x14, 0xc420018092, 0x28, 0xc4201069e0, 0xc42041e000, ...)
05/05/2017 09:15:16	/go/src/github.com/rancher/rancher-compose-executor/executor/handlers/project.go:91 +0x4d2
05/05/2017 09:15:16github.com/rancher/rancher-compose-executor/executor/handlers.createStack(0xc420018a40, 0xc4204f8410, 0xc420326000, 0x1, 0xc420124f30)
05/05/2017 09:15:16	/go/src/github.com/rancher/rancher-compose-executor/executor/handlers/create_handler.go:46 +0x166
05/05/2017 09:15:16github.com/rancher/rancher-compose-executor/executor/handlers.CreateStack(0xc4204f8410, 0xc420326000, 0xc420100101, 0xc42036fde8)
05/05/2017 09:15:16	/go/src/github.com/rancher/rancher-compose-executor/executor/handlers/create_handler.go:22 +0x269
05/05/2017 09:15:16github.com/rancher/rancher-compose-executor/executor/handlers.WithTimeout.func1(0xc4204f8410, 0xc420326000, 0xc420124de0, 0x2d)
05/05/2017 09:15:16	/go/src/github.com/rancher/rancher-compose-executor/executor/handlers/common.go:54 +0x46
05/05/2017 09:15:16github.com/rancher/rancher-compose-executor/vendor/github.com/rancher/event-subscriber/events.doWork(0xc4204f8410, 0xc4201dcc90, 0xc420326000, 0xd33560, 0xc420291860)
05/05/2017 09:15:16	/go/src/github.com/rancher/rancher-compose-executor/vendor/github.com/rancher/event-subscriber/events/worker.go:94 +0x28d
05/05/2017 09:15:16github.com/rancher/rancher-compose-executor/vendor/github.com/rancher/event-subscriber/events.(*skippingWorkerPool).HandleWork.func1(0xc4203822d0, 0x1, 0xc4204f8410, 0xc4201dcc90, 0xc420326000)
05/05/2017 09:15:16	/go/src/github.com/rancher/rancher-compose-executor/vendor/github.com/rancher/event-subscriber/events/worker.go:47 +0x9e
05/05/2017 09:15:16created by github.com/rancher/rancher-compose-executor/vendor/github.com/rancher/event-subscriber/events.(*skippingWorkerPool).HandleWork
05/05/2017 09:15:16	/go/src/github.com/rancher/rancher-compose-executor/vendor/github.com/rancher/event-subscriber/events/worker.go:48 +0x18d

**Comment by joshwget** [comment]
The syntax in #8025 is incorrect. I've updated the issue to remove Compose file. Can you try again using the syntax from the [Docker Compose docs](https://docs.docker.com/compose/compose-file)?

Note, we support secrets in version 2 of Compose rather than version 3. We'll update our docs to reflect this difference soon.

**Comment by courcelm** [comment]
The docker-compose.yml syntax I used above is the one that Rancher show if you add a container with a secret to a stack manually. 

I looked in Docker compose v2 doc and I don't see any mention of secret.

**Comment by joshwget** [comment]
Secrets are a Docker Compose v3 feature but they are backported to version 2 in Rancher.

I'll look into why our export is incorrect for secrets.

**Comment by joshwget** [comment]
I created #8680 to track the export issue.

**Comment by courcelm** [comment]
Following v3 doc, I got it to work with:

```
version: '2'
services:
  test:
    image: ubuntu
    stdin_open: true
    tty: true
    secrets:
    - test
    labels:
      io.rancher.container.pull_image: always
      
  
    
```

Thanks, @joshwget for your quick assistance.
