### ISSUE TITLE
Webhook upgrade service doesn't wait long enough to confirm upgrade

### ISSUE THREAD

**Issue by bacheson** [rancher/rancher#8678]
**Rancher Versions:**
Server: 1.6.0
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker Version:**
1.12.6
**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
Create 50 services in a stack. Create a webhook that upgrades all these services.
**Results:** 
Many of the services remain in an "upgraded" state. There seems to be a race condition where confirm doesn't wait until the service has been upgraded before firing.

**Comment by bacheson** [comment]
any eta on this? I know this is experimental but in it's current state it's not even functioning on a moderate level...it's a shame because it's a very useful feature

**Comment by ItsReddi** [comment]
Well we discovered this also today but only with 2 services that are upgraded at the same time.
one of the services were stuck in upgraded state
@bacheson do you have any workaround for that?

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
