### ISSUE TITLE
Expose ha-proxy loadbalancer stats as an API so that they can be displayed in the UI

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#8679]
This is a follow up/enhancement to https://github.com/rancher/rancher/issues/8627

We would eventually like to display pertinent load balancer stats (ie active connections) in the UI. To do so, we just need to jsonify and expose the haproxy csv stats.

The implementation should follow the same paradigm as normal container stats where there is a link/action on the lb-container for "lb-stats", which points you at wsp with a token, which the proxies to host-api on the host where the container is running, which then connects to the lb-container to get the stats

**Comment by tuwid** [comment]
people so need this

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
