### ISSUE TITLE
A typo in v1.6.0 release note 

### ISSUE THREAD

**Issue by Fufuhu** [rancher/rancher#8682]
Hi,

Excuse me for not following the template for issues.
That's why it's not the problem in Rancher itself but in release notes.

There might be a typo in release note, so I'd like to inform you of it.

In the features section, at Rancher EBS volume support.
> EBS has also been enabled with support for additional options such as volumetype, ios, encrypted, ksmKeyId, and snapshotId.

**such as volumetype, ios, encrypted...**

I think the statement ios should be IOPS, isn't it?

Regards,

**Rancher Versions:**
Server: 
healthcheck: 
ipsec: 
network-services: 
scheduler: 
kubernetes (if applicable): 
**Docker Version:**
**OS and where are the hosts located? (cloud, bare metal, etc):**
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
**Steps to Reproduce:**
**Results:**

**Comment by superseb** [comment]
Thank you, fixed.
