### ISSUE TITLE
Image Garbage Collection

### ISSUE THREAD

**Issue by StrongMonkey** [rancher/rancher#8685]
The initial design of this feature:
we may need four properties for image garbage collection:
```
image.garbage.collection
image.maximum.age
image.gc.high.threshold
image.gc.low.threshold
```
`image.garbage.collection`: `true` indicates the gc has been enabled. `false` means not.
`image.maximum.age`: the maximum life time that an image can live. If it has pass the maximum lifetime from the last detected time, it will be deleted. This prevents deleting images that have been recently pulled.
`image.gc.high.threshold`: the percent of disk usage which triggers image garbage collection
`image.gc.low.threshold`: the percent of disk usage to which image garbage collection attempts to free.

**Comment by StrongMonkey** [comment]
The agent should start a go routine process to keep track of those images(lastDetectedTime, size) and clean them every five minutes.

**Comment by vincent99** [comment]
![image](https://cloud.githubusercontent.com/assets/753917/25768464/823ac3ba-31b9-11e7-9677-29921acff9fa.png)

"maximum age" sounds a "minimum" to me.  "You must be at least 21 to enter".

Consistent prefix for related settings and descriptive units please.  I don't know if these are the best names and haven't looked through the list of existing things lately, but for example:

```
image.gc.enabled
image.gc.min.age.seconds
image.gc.trigger.percent
image.gc.target.percent
```

`</namingpolice>`

**Comment by StrongMonkey** [comment]
![image](https://cloud.githubusercontent.com/assets/9203378/25768483/de89aafa-31b9-11e7-90d7-5dbd1568614a.png)

**Comment by StrongMonkey** [comment]
Estimated time: 3 days(can't guarantee)

**Comment by cjellick** [comment]
@StrongMonkey Thats why its an estimate!
Thanks for giving it. I know it feels weird since we havent really done that

**Comment by cjellick** [comment]
Design looks good with @vincent99's config name changes.

**Comment by StrongMonkey** [comment]
@sangeethah This is implemented as a [rancher micro-service](https://github.com/StrongMonkey/rancher-catalog/tree/gc-manager/infra-templates/gc-manager). Fully explanation on this feature will be available on catalog README.md.

**Comment by sangeethah** [comment]
@StrongMonkey  Initial set of test cases for this feature - https://github.com/rancher/rancher/issues/8789

**Comment by sangeethah** [comment]
Initial validation was done. 
Issues found during testing is tracked in:

#8802
#8828
