### ISSUE TITLE
[cli] Use safe storage for creditials (Keychain on macOS)

### ISSUE THREAD

**Issue by iBobik** [rancher/rancher#8689]
Currently creditials are stored in `.rancher/cli.json` what is globally readable by all programs running in account. This file should be protected to be accessible only by rancher-cli and rancher-compose because it usually contains creditials to production servers.

I do not know how to do it on other platforms, but on macOS there is system vault for secrets Keychain what stores everything safely and offers API for apps.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
