### ISSUE TITLE
When `upgrade-manager: true`, services will be upgraded/downgraded to whatever the "default" value in the catalog template

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#8691]
The `default` version in the config.yml does not necessarily mean that the default version applies to the Rancher version. 

Upgrade manager disregards the min/max Rancher version set in the default template.

**Comment by soumyalj** [comment]
Tested with v1.6.1-rc9. 
1. Create a v1.6.1-rc9 setup. Set upgrade.manager=all in advanced settings
2. Create a private repo for rancher-catalog having folder with updated version(0.2.2) for network services. Set the minimum rancher version to v1.6.0-rc1. Set default version in config.yml to v0.1.0
3. Change the catalog on the setup to point to the private catalog in the appropriate branch
4. Trigger upgrade using upgrade.shedule task( http://IP:8080/v2-beta/tasks/1t15)

Network services stack was automatically upgraded to v0.2.2. The minimum rancher version was not ignored.
