### ISSUE TITLE
Python error (?) when create a host

### ISSUE THREAD

**Issue by JiayeLiJing** [rancher/rancher#8692]
**Rancher Versions:**
Server: latest
healthcheck:v0.2.3
ipsec:v0.11.2
network-services:v0.9.1
scheduler:v0.7.5
kubernetes (if applicable):

**Docker Version:**
v.1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):**
Fedora, ubuntu

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
cattle with 2 nodes
**Steps to Reproduce:**
I want to deploy Hadoop +YARN from catalog in Rancher. I installed rancher/server in desktop whose system is Fedora with docker v1.12.6. Then I want to create a host in my laptop whose system is Ubuntu (I forget its version of docker but its higher than that of desktop) and add it in Hadoop.
When I execute this:
` sudo docker run --rm --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.2.2 http://192.168.3.240:8080/v1/scripts/9AC0900BB999AAEDAEC4:1483142400000:3rfc2hqW9ZRdDgz5JNwyr0Pp4`
I got this:

> INFO:Running Agent Registration Process,CATTLE_URL=http://192.168.2.240:8080/v1
INFO:Attempting to connect to http://192.168.3.240:8080/v1
INFO:http://192.168.3.240:8080/v1 is accessible
INFO:Inspecting host capabilities
INFO:Boot2Docker:false
INFO:Host writable : true
INFO:Token:xxxxxxxx
INFO:Running registration
Traceback (most recent call last):
File "./register.py", line 30, in <module>
r = client.create_register(key=key)
AttributeError:'Client' object has no attritube 'create_register'

Ps.1.The command '`sudo docker run`' is not wrong, and I can visit http://192.168.3.240:8080 in my laptop.
2.Python version is 2.7.

**Results:** 
I reinstalled the Ubuntu system today, installed docker v1.12.6 and executed the command again. I got this:

> Unable to find image 'rancher/agent:v1.2.2' locally
v1.2.2: Pulling from rancher/agent
b3e1c725a85f: Pull complete 
4daad8bdde31: Pull complete 
63fe8c0068a8: Pull complete 
4a70713c436f: Pull complete 
bd842a2105a8: Pull complete 
3f7d6fd71888: Pull complete 
16914729cfd3: Pull complete 
b9c91512c230: Pull complete 
Digest: sha256:cfb7fc0de1146680ca26e3bc8cd09cc7a0274eff99f5b84246c33642a99f81da
Status: Downloaded newer image for rancher/agent:v1.2.2
INFO: Running Agent Registration Process, CATTLE_URL=http://192.168.3.240:8080/v1
INFO: Attempting to connect to: http://192.168.3.240:8080/v1
INFO: http://192.168.3.240:8080/v1 is accessible
INFO: Inspecting host capabilities
INFO: Boot2Docker: false
INFO: Host writable: true
INFO: Token: xxxxxxxx
INFO: Running registration
Traceback (most recent call last):
  File "./register.py", line 11, in <module>
    secret_key=os.environ['CATTLE_REGISTRATION_SECRET_KEY'])
  File "/usr/local/lib/python2.7/dist-packages/cattle.py", line 45, in from_env
    return gdapi.from_env(prefix=prefix, factory=Client, **kw)
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 613, in from_env
    return _from_env(prefix=prefix, factory=factory, **args)
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 632, in _from_env
    return factory(**result)
  File "/usr/local/lib/python2.7/dist-packages/cattle.py", line 12, in __init__
    super(Client, self).__init__(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 197, in __init__
    self._load_schemas()
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 315, in _load_schemas
    response = self._get_response(self._url)
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 264, in _get_response
    headers=self._headers)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='172.17.0.1', port=8080): Max retries exceeded with url: /v1 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fa3c44b4810>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by niusmallnan** [comment]
If you run rancher-server and agent in the same node, make sure add CATTLE_AGENT_IP env.
![image](https://cloud.githubusercontent.com/assets/998984/25885456/0ab9e426-358b-11e7-98f2-54579ebb1404.png)

**Comment by JiayeLiJing** [comment]
I run server in my desktop and agent in laptop.

**Comment by JiayeLiJing** [comment]
I tried again. I changed the desktop system into Ubuntu 16.04LTS , upgraded docker version to 17.05 as well as laptop. Yet there was same error "ConnectionError" . Is it possible a bug of rancher?

**Comment by niusmallnan** [comment]
In your logs, agent recognizes that the rancher-server IP is incorrect, it should not be "172.17.0.1".
```
requests.exceptions.ConnectionError: HTTPConnectionPool(host='172.17.0.1', port=8080): Max retries exceeded with url: /v1 (Caused by 
```
Do not know your network setting, I've never had a problem like this.

Can you please set the CATTLE_AGENT_IP as I mentioned above?

**Comment by JiayeLiJing** [comment]
Thanks. I have fixed the error. Just as you said, I set the wrong server IP which should be 192.168.3.240.
