### ISSUE TITLE
[UI] Memory leak when having a tab with the host detail view open in the background

### ISSUE THREAD

**Issue by mijgame** [rancher/rancher#8693]
**Rancher Versions:**
According to the Rancher release page:
rancher/server:v1.6.0
rancher/agent:v1.2.2
rancher/lb-service-haproxy:v0.7.1
rancher-v0.6.0
rancher-compose-v0.12.5

**Docker Version:**
Docker 17.03.0-ce

**OS and where are the hosts located? (cloud, bare metal, etc):**
My OS: Microsoft Windows 10 Enterprise (10.0.15063 Build 15063)
The Rancher host is bare metal (HP thin cliënt, AMD G-T56N Processor with 4GB ram). OS is RancherOS (v1.0.1 - LTS).

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher with an internal database.

**Steps to Reproduce:**
In Chrome (58.0.3029.96 64-bit, most recent version), open the detail view of a Rancher host (Infrastructure -> Hosts) and click on a host to view graphs and containers.
Now open a new tab, leaving the Rancher-tab open in the background. Memory usage will grow until ~4 GB before Chrome forcefully closes the tab. The memory usage grows with 2 - 3 MB per second on my machine.

**Results:** 
Massive memory use.

![image](https://cloud.githubusercontent.com/assets/8114544/25781241/7836d2bc-3337-11e7-9539-9c00b936b02d.png)

**Comment by vincent99** [comment]
I think this is due to the graphing library used for the large graphs in 1.x, which is different in 2.0.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
