### ISSUE TITLE
VMware Pool not found

### ISSUE THREAD

**Issue by spyworldxp** [rancher/rancher#8695]
Rancher Versions: Since version v1.5.5 - v1.6.0 (current)
Operating System: Rancher v1.0.1
Virtualization: VMware ESXi 6.5 (vCenter 6.5)
Environment Type: Cattle

Enable vSphere Machine Driver and Add new Host with "Pool". This problem should be related to new vCenter 6.5 API.

Error with pre-create check: "resource pool 'Docker' not found"

**Comment by aemneina** [comment]
will most likely need to be fixed [here](https://github.com/docker/machine/tree/master/drivers/vmwarevsphere) , for rancher to leverage.

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
