### ISSUE TITLE
Unable to pass CLUSTER_ADVERTISE IP HA to ECS

### ISSUE THREAD

**Issue by obenziane2** [rancher/rancher#8699]
**Rancher Versions:**
Server:1.5.9
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):
NA
**Docker Version:**
1.12.6 on AWS ECS
**OS and where are the hosts located? (cloud, bare metal, etc):**
ECS
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**
Run Rancher server on ECS to pass HA arguments --advertise-address "awslocal"
or CATTLE_CLUSTER_ADVERTISE_ADDRES variable
**Results:** 
I was unable to pass those extra arguments to the containers from AWS ECS since the OS environments are string and not variable and also could not override the entry point and CMD like:
`Command["/usr/bin/s6-svscan","/service","--advertise-address aws-local"]`

Are they anyway to pass the HA CLUSTER_ADVERTISE IP address to ECS containers ?

**Comment by aemneina** [comment]
Not sure if the fix [here](https://github.com/rancher/rancher/issues/7343)  should also work for ECS.

**Comment by aemneina** [comment]
@obenziane2 can you share how you're configuring your ECS instances? Is this using user data, if so can you share a sanitized copy?

**Comment by obenziane2** [comment]
Thanks aemneina for your quick response!

I'm using CloudFormation ECS template and ECS json to push the definition tasks (see code below), but I'm not using UserData to control the docker images, etc..
`        "ContainerDefinitions":[
          {
            "Name":"rancher-server",
            "Cpu":"500",
            "Essential":"true",
            "Image": {"Ref" : "RancherReleaseVersion"},
            "Memory":"600",
            "LogConfiguration":{
              "LogDriver":"awslogs",
              "Options":{
                "awslogs-group":{
                  "Ref":"CloudwatchLogsGroup"
                },
                "awslogs-region":{
                  "Ref":"AWS::Region"
                },
                "awslogs-stream-prefix":{ "Fn::Join" : [ "", ["ecs-",{"Ref" : "ServiceEnvironmentName"},{"Ref" : "ServiceName"}]]}
              }
            },
            "PortMappings":[
              {
                "ContainerPort":8080,
                "HostPort":8080,
                "Protocol" : "tcp"
              }
            ]
          }
          ]`


My ECS:

{
  "containerDefinitions": [
    {
      "name": "rancher-server",
      "environment": [
          {
              "name": "CATTLE_DB_CATTLE_PASSWORD",
              "value": "Nets98gS!3739ee$3&"
          },
          {
              "name": "CATTLE_DB_CATTLE_MYSQL_PORT",
              "value": "3306"
          },
          {
              "name": "CATTLE_DB_CATTLE_MYSQL_HOST",
              "value": "rancher-server-rds.test.example.com"
          },
          {
              "name": "CATTLE_DB_CATTLE_MYSQL_NAME",
              "value": "cattle"
          },
          {
              "name": "CATTLE_API_ALLOW_CLIENT_OVERRIDE",
              "value": "true"
          },
          {
              "name": "CATTLE_DB_CATTLE_USERNAME",
              "value": "rancheradmintest"
          }
      ],
      "image": "rancher/server:v1.5.9",
      "logConfiguration": {
          "logDriver": "awslogs",
          "options": {
              "awslogs-region": "us-east-1",
              "awslogs-stream-prefix": "ecs-testrancher-server",
              "awslogs-group": "ECSLogGroup-rancher-server-test"
          }
      },
      "cpu": 500,
      "command": [
      ],
      "memory": 600,
      "portMappings": [
          {
            "containerPort": 8080,
            "hostPort": 8080
          },
          {
            "hostPort": 9345,
            "containerPort": 9345,
            "protocol": "tcp"
          }
      ],
      "essential": true
    }
  ],
  "family": "rancher-server-test",
  "networkMode": "bridge",
  "volumes": []
}

**Comment by obenziane2** [comment]
I've also added to the entry point and it says:

container_linux.go:247: starting container process caused "exec: \"/usr/bin/entry --advertise-address aws-local\": stat /usr/bin/entry --advertise-address aws-local: no such file or directory"
container_linux.go:247: starting container process caused "exec: \"/usr/bin/entry --advertise-address aws-local\": stat /usr/bin/entry --advertise-address aws-local: no such file or directory"




<img width="787" alt="screen shot 2017-05-08 at 12 24 24 pm" src="https://cloud.githubusercontent.com/assets/11947294/25821291/5b4b6a84-33e9-11e7-9962-2022ed4a03b7.png">

**Comment by obenziane2** [comment]
Thanks Guys! I have fixed it using the right syntax :)


      "entryPoint": [
        "/usr/bin/entry",
        "--advertise-address",
        "awslocal"
      ],
<img width="787" alt="screen shot 2017-05-08 at 12 24 24 pm" src="https://cloud.githubusercontent.com/assets/11947294/25826321/389178b4-33fb-11e7-93a5-272982b6e296.png">
