### ISSUE TITLE
Support pulling CA certs from default OS locations

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#8700]
We currently use /var/lib/rancher/etc/ssl/ca.crt file in order to get private / self signed CA certficates into the trusted OS store. This file is a non-standard location for the base operating system.

This was done by design to avoid having the privileged agent container from stepping outside of its boundaries. It is also done to isolate any differences between the base OS and the containers Ubuntu image. 

It has been brought up that it might be worth revisiting this design to ease operational overhead.

**Comment by dweidenfeld** [comment]
+1

**Comment by cloudnautique** [comment]
This was tied to v1.6 and the way TLS was handled. Since v1.6 is not gaining any additional feature enhancements at this time. I'm going to close this issue.
