### ISSUE TITLE
Catalog Service: Catalog image not pulling up when added per environment basis

### ISSUE THREAD

**Issue by amy** [rancher/rancher#8701]
- Project/environment ID is sent as a header for the normal API requests, but that's not possible for loading an image.
- `image` link/URL in the API response needs to contain enough info for you to be able to respond with the right image when that URL is retrieved.  
- Add `projectId=1a5` to the query string, or construct URLs as `/v1-catalog/projects/1a5/templates/foo?image`

**Comment by cjellick** [comment]
Available for testing on master

**Comment by tfiduccia** [comment]
Version - master 5/17
Verified fixed
