### ISSUE TITLE
Ensure per-environment catalogs work in rancher

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#8702]
Obviously, need more specific requirements and scope for this. Right off the bat, this includes:
- https://github.com/rancher/rancher/issues/8701
- https://github.com/rancher/rancher/issues/8752
- #8766 

But there are probably more items and I want an umbrella issue to capture the full scope

**Comment by joshwget** [comment]
I think #8319 is also good to add to this list.

**Comment by amy** [comment]
Added https://github.com/rancher/rancher/issues/8752 above

**Comment by cjellick** [comment]
Moved to testing because we are in the stage of just fixing bugs as they are found by @amy and @tfiduccia

**Comment by tfiduccia** [comment]
Version - 1.6.1-rc8
Verified added
