### ISSUE TITLE
Change behavior of default version for catalog templates

### ISSUE THREAD

**Issue by joshwget** [rancher/rancher#8705]
The `defaultVersion` field should be the latest version compatible with the current Rancher version. The `version` field from `config.yml` should be ignored.

**Comment by cjellick** [comment]
@joshwget whats the current behavior of defaultVersion?

**Comment by deniseschannon** [comment]
There is no `defaultVersion` right now in the `config.yml`. Just `version` in the `config.yml`, which really means "the default version compatible with the latest Rancher version".

**Comment by deniseschannon** [comment]
Closing in favor of #8319 as it should be included with all the file name changes
