### ISSUE TITLE
Should not be able to create containers with same name

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#8706]
**Rancher Versions:** 5/8

**Steps to Reproduce:**
1.  Go into Add Container
2.  Set scale to 2
3.  Create

**Results:** two containers with the same name get created.  There should be a error returned saying name is not Unique from API.

**Comment by vincent99** [comment]
The API should add `-${num}` to make them unique.

**Comment by tfiduccia** [comment]
Version - 6/12 (2.0 Alpha)
Verified fixed
