### ISSUE TITLE
Ghost Containers with no host cant be removed

### ISSUE THREAD

**Issue by robertoamoreno** [rancher/rancher#8708]
**Rancher Versions:**
Rancher	v1.4.1
Cattle	v0.176.9
User Interface	v1.4.6
Rancher CLI	v0.4.1
Rancher Compose	v0.12.2
Cattle

I have a couple containers that have been trying to get removed since an upgrade but are not able to be removed. 

The containers do not have host attached to them.
<img width="1461" alt="screen shot 2017-05-08 at 6 04 36 pm" src="https://cloud.githubusercontent.com/assets/16195292/25830275/f92c924e-3418-11e7-9712-e439dbde28da.png">

https://www.useloom.com/share/0131a68bc7634fcd9d67610388d8d96a

**Comment by aemneina** [comment]
@robertoamoreno when you click the menu for those containers, do you get the option to delete? If not can you select API in the menu for those items, and use the API browser to delete those?

**Comment by robertoamoreno** [comment]
@aemneina Hello No I do not get the option to delete in the api I get the option to delete but if i submit it response with ok but it still there.

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
