### ISSUE TITLE
Azure - Unable to use SSH key after deploying RancherOS from Azure's Marketplace

### ISSUE THREAD

**Issue by mabicca** [rancher/rancher#8709]
Trying to deploy the RancherOS from Rancher Labs on Azure, using the marketplace image is not working when set up to use SSH key, it looks like after the VM is deployed only password is working and it will fail since it was deployed using SSH key.

At the moment the workaround would be to do a reset password through the Azure portal , then password login will work just fine.

Is there any way we can get a request to update the image in there to the one that has this fixed?

Steps to reproduce are very straightforward, assuming you have an Azure account, you just have to deploy the Rancher OS and use SSH Key instead of password.

Please, let me know if you guys need any other details.

RancherOS v 3.1

I'll try to get more details in the meantime but this looks to be an issue maybe with cloud-init.

**Comment by joshwget** [comment]
Can you open this in the [RancherOS issues](https://github.com/rancher/os/issues)? This is unrelated to Rancher.
