### ISSUE TITLE
load balancer support "balance url depth" "hash-type consistent"?

### ISSUE THREAD

**Issue by kkvilekval** [rancher/rancher#8710]
**Rancher Versions:**
1.5.5
**Docker Version:**
1.13+
**OS and where are the hosts located? (cloud, bare metal, etc):**
cloud and bare metal
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

Trying to add consistent hashing based on url.  Is there a way ?

**Comment by aemneina** [comment]
You should be using a custom haproxy configuration and adding `balance uri depth X` to the backend definition. Take a look here for an example config: http://docs.rancher.com/rancher/v1.5/en/cattle/adding-load-balancers/#custom-haproxy-configuration

**Comment by kkvilekval** [comment]
It's not quite clear whether the servers will be updated automatically as the service scales.  Does load balancer recognize the $IP and replace it with multiple server definitions when the linked service scales or do I lose that functionality?

**Comment by aemneina** [comment]
this should be usable in your custom haproxy configuration. you can use it in conjunction with the server $IP definition.

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
