### ISSUE TITLE
New pods are restarting with error Stopped (Failed to find labels provider)

### ISSUE THREAD

**Issue by moshe0076** [rancher/rancher#8711]
**Rancher Versions:**
Server:1.6
healthcheck:v0.2.3
ipsec:0.0.7
network-services:0.1.2
scheduler:0.5.1
kubernetes (if applicable):v1.5.4-rancher1-4.1

**Docker Version: 1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc): Ubuntu 16.04.1 LTS (4.4.0)

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB):HA/RDS

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos):Kubernetes

**Steps to Reproduce:**
When launching need containers on one of the compute nodes I see in Rancher:Stopped (Failed to find labels provider)
In Kubernetes I see:
Error syncing pod, skipping: failed to "SetupNetwork" for "log-rotate-f2t5c_production-infra" with SetupNetworkError: "Failed to setup network for pod \"log-rotate-f2t5c_production-infra(e6e903f2-33de-11e7-a659-02c4cc2dda69)\" using network plugins \"cni\": No MAC address found; Skipping pod"
 

**Results:** 
Pods are restarted in an infinite loop.

**Comment by aemneina** [comment]
@moshe0076 it looks like there might be an issue with the network services containers. Are there any telling logs being emitted from there?

**Comment by moshe0076** [comment]
Hi,

It looks like the RDS instance was overloaded (memory). After I increased the RDS instance size and updated all the services  the cluster had stabilized.

Thanks,

Moshe
