### ISSUE TITLE
DNS sync very slow after upgrade service

### ISSUE THREAD

**Issue by k8w** [rancher/rancher#8712]
*Describe your issue here*
I have a web server, reverse proxy by nginx.

nginx conf:

```
set $backend http://serviceName.stackName:3000;
location ^~ /api/{
        rewrite ^/api/(.*) /$1 break;
        proxy_pass $backend;
    }
```

But once I update the service (Start before Stopping checked),
it will take so long time that nginx can resolve the new ip.
Also can not ping in the container shell. (Bad address shown).
It always took more than 10min to recover, or restart network-service mannually.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.5.6` Cattle: `v0.178.4` UI: `v1.5.9` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`service.containers`|

**Comment by lingzhang-lyon** [comment]
Any update on this issue?

We got similar issue that DNS sync very slow after upgrade a service or create a new stack.

This only happen on our production environment where there are more than 200 stacks (3000 containers).   
The DNS sync is much faster on our qa environment,  which have less than 20 stacks (300 containers).

We are on Rancher 1.5.3.

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
