### ISSUE TITLE
when I want to upgrade container use volumes it can't  judge file or folder

### ISSUE THREAD

**Issue by polo13999** [rancher/rancher#8713]
**Rancher Versions:**
Server:  mac os serra
healthcheck: ok
ipsec: ok
network-services: ok
scheduler: ok
kubernetes (if applicable):

**Docker Version:**
nginx:lasest
**OS and where are the hosts located? (cloud, bare metal, etc):**
ubuntu 16.4
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
when I want to upgrade container use volumes to map  signle file ex. nginx.conf 
if map local file not exist it's will create a folder 
**Results:** 
I think if can judge file or folder will be better

**Comment by joshwget** [comment]
This is the default behavior for bind mounts in Docker. Unfortunately there isn't anyway for Rancher to override this functionality.

**Comment by superseb** [comment]
For reference: https://github.com/moby/moby/issues/13121
