### ISSUE TITLE
Optimize database calls for catalog service to only update on different templates versus all templates during refresh.

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#8716]
Currently, catalog-service will remove all DB entries for catalog templates and then re-add all of them. It would be better if it only did the templates that have changes.

**Comment by amy** [comment]
Comparing hashes of DB catalog templates against hashes of new templates.
```
// create hashmap of `key=template-hash` `value=template` for both new incoming templates and db templates

if (a hash in new-template-hashes doesn't match any hashes in db-template-hashes){
    // add new hash to DB
}

if (hash in db-template-hashes doesn't match any hashes in new-template-hashes) {
    // delete the template
}
```

Another thing we should consider, is ensuring template name uniqueness within a catalog for clarity's sake. What currently happens if there two templates with the same name in the same catalog, are that they are both shown.

**Comment by amy** [comment]
@cjellick and I talked about implementation for this. Ultimately we will be using git to figure out the latest relevant hash for the current working directory. 

Commit SHAs will be stored:
- per version (calculated by a SHA from the version directory level)
- per template (calculated by a SHA from the config file directory level)
- per catalog (the SHA is already calculated for this)

Updates will happen intelligently on a:
- version level
- template metadata level
- catalog metadata level

To do this. We are using the following logic:
- if the commit SHA of the version changes for incoming versions, add the version to the DB. If the SHA of the version from the DB does not exist in the incoming version SHAs, delete the version entry
- if the commit SHA of the template changes, update the template metadata information. 
- if the commit SHA of the catalog changes, update the catalog metadata information. 

For the latter 2, the SHA will probably change if a field below it changes, but I'll look into that and make sure to update metadata fields when necessary.

**Comment by amy** [comment]
For testing: assure that every catalog component creates, updates, and deletes as expected.

Due to implementation, this is how we confirm that my updates have worked. There is no other code path to update the database.

**Comment by cjellick** [comment]
As per @vincent99, one potential issue this was addressing was that it was possible to exceed the maximum number of things you can do in a transaction. This would happen in a big catalog with a lot of template/versions. We should assert that large catalogs do not cause that with this fix.

**Comment by cjellick** [comment]
With the focus on 2.0, its safe to say this isnt going to be merged
