### ISSUE TITLE
Kubernetes RBAC integration

### ISSUE THREAD

**Issue by joshwget** [rancher/rancher#8717]
- [x] Add [kubernetes-auth](https://github.com/rancher/kubernetes-auth) to Kubernetes template
- [x] Add a healthcheck to kubernetes-auth
- [x] Auth redirect for dashboard
- [x] Disable unsecured port
- [x] Multitenant web kubectl shell
- [x] kubernetes/dashboard#1539
- [x] Support remaining Rancher auth providers
- [x] Group authentication
- [x] Description on `RBAC` parameter for catalog
- [x] Docs

**Comment by galal-hussein** [comment]
https://github.com/rancher/rancher/issues/9151 RBAC test plan

**Comment by galal-hussein** [comment]
Rancher server: v1.6.3-rc2

RBAC test plan tested and verified on k8s 1.6.6 on v1.6.3-rc2.
