### ISSUE TITLE
Add custom host - No info about hosts on same machine as server

### ISSUE THREAD

**Issue by enriquemorenotent** [rancher/rancher#872]
When someone tries to create a custom new host, you can see the instructions to run the agent, but it fails to explain that if the machine where the Host is created is the same one as the one where the server  container is running, an extra environment variable is needed:

    -e CATTLE_AGENT_IP=<IP_OF_RANCHER_SERVER>

**Comment by deniseschannon** [comment]
:+1: We should add it to the UI as there are a lot of people who add their hosts on the same one as server. @vincent99 what do you think?

**Comment by clemenko** [comment]
Is it possible to make the agent work the same way across all nodes?

**Comment by deniseschannon** [comment]
Now that've we've added ability to add in host labels and it adds fields into the command. Could we add in something in the UI so that it would do the same? 

Maybe a checkbox if you are using the same machine as your server and that would add in the `-e CATTLE_AGENT_IP=<ip_of_server>` into the code?

**Comment by clemenko** [comment]
What is causing the agent to not get the ip correctly when running it on the same box as the server?

**Comment by deniseschannon** [comment]
i don't have a great reason to give, but maybe @ibuildthecloud can shed some light.

**Comment by baskinsy** [comment]
Hello,

Although I am adding "-e CATTLE_AGENT_IP=<ip_of_server>", I'm still experiencing the "connecting" issue when I run the agent on the same host. Any hints on what is wrong or where to look? All host details are displayed, except CPU and Memory.

Thanks.

**Comment by deniseschannon** [comment]
@baskinsy Can you provide what version of rancher you are running? If you click on the cow in the upper left corner, it should give you a version number. 

Rancher is now communicating through a proxy to the hosts, so if the graphs aren't showing up, it'll most likely be a websocket-proxy issue. @cjellick should be able to help troubleshoot the proxy.

**Comment by ibuildthecloud** [comment]
In the UI make sure the "Host Registration" setting is not localhost but the IP of the machine.  The setting is in the upper right of the UI

**Comment by baskinsy** [comment]
Hello,

I'm running the following:

Rancher 	v0.25.0
Cattle 	v0.58.0
User Interface 	v0.29.0
Rancher Compose 	latest

Something additional that might help. If I select "View in API" for the host, I can see load and memory details.

cpuInfo": {

    "count": 2,
    "cpuCoresPercentages": [ 2 items
        5.064,
        3.106,
    ],
    "loadAvg": [ 3 items
        0.03,
        0.11,
        0.09,
    ],
    "mhz": 3411.482,
    "modelName": "Common KVM processor",

},
"memoryInfo": {

    "memTotal": 2001.531,
    "swapTotal": 2047.996,
    "cached": 857.922,
    "swapCached": 0.68,
    "swapFree": 2046.43,
    "memAvailable": 1143.754,
    "memFree": 118.164,
    "inactive": 658.523,
    "active": 1035.078,
    "buffers": 200.695,

**Comment by baskinsy** [comment]
Ok, I have more info. It seems a proxy issue but I don't know why. I attached to the rancher-agent container and it shows this:

```
time="2015-07-11T22:03:38Z" level="info" msg="Starting event router." 
time="2015-07-11T22:03:38Z" level="info" msg="Watching state directory: /var/lib/rancher/state/containers" 
time="2015-07-11T22:03:38Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"c49ca3c093df97157eb1d1f2fceee4437a61d35f9f58ee9f75f2414d755107a9\", From:\"-simulated-\", Time:0}" 
time="2015-07-11T22:03:38Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"ca4777aec31043b1aeb1127ccc06de85e675cf18e35617da556d6deec1277c72\", From:\"-simulated-\", Time:0}" 
time="2015-07-11T22:03:38Z" level="info" msg="Connecting to proxy." url="wss://stratosdock1.str5.net:8080/v1/connectbackend?token=eyJhbGciOiJSUzI1NiJ9.eyJleHAiOjE0MzY2NTI1MTgsInN1YiI6ImNhdHRsZSIsImlzcyI6Imh0dHA6XC9cL2NhdHRsZS5pbyIsInJlcG9ydGVkVXVpZCI6IjgwMTNjZjg5LTA2NjYtNGVlOC05YzZjLWZkNzRmZWY3MjEwOSIsImlhdCI6MTQzNjY1MjIxOCwia2lkIjoiZGVmYXVsdCJ9.MzaaXhhP1lae1eb-PpQ1FFU_ocMoXOGmG8X-HFiXpPySvt2AiOeffRbwT-bS3CwfFb4zQgWXhw2ZnLBM9rS5Ek79pcjoOTgWQV7bImsXnH3YRJSFqLYf0WCJGtJ7_gbBHOibjaPb36nwlblsvcCFSKUW1_B_-7gQF1hYz6JMSWA6xwNwUZ_5aMN6eYpiXKubYWIEDrV3YRr41UFEF4BdXBCix-IbLwVwBbjAnru9yeruLv14uxrpArxJndHqeJleGcJVAv0sIIjAzXzj3R1pEfQfQzNZ8oztGetkZ3yMTKn3VvwZSR9TwXXgqkl2EZ5AsE6UJP4WB0MFfuOq52PJGw" 
time="2015-07-11T22:03:38Z" level="fatal" msg="Failed to connect to proxy." error="tls: oversized record received with length 20527"
```

**Comment by vincent99** [comment]
This is the same cause as another issue someone had in our forums:  http://forums.rancher.com/t/getting-error-typeerror-cannot-read-property-login-of-undefined/41/15

The proxy config we suggest for SSL has `proxy_buffer_size 512` to fix an issue with messages from the host being buffered for too long, but turning that down that low causes large responses from the proxied backend to be too big.  We'll be working on it this week.

**Comment by baskinsy** [comment]
The strange thins is that I haven't setup SSL anywhere... so I don't know if it has to do with the stats (CPU and memory) issue that I have.

**Comment by vincent99** [comment]
Hmm... The only reason the URL in the error should say `wss://` (instead of `ws://`) is if a setting was changed, and it's only for if you are trying to do SSL.  Can you show us the output of `docker inspect` on the `rancher/server` container?

What version did you start with originally and what version(s) have you upgraded it to?  If you've never tried to setup SSL then there's likely some way the setting gets set wrong in the upgrade path.

**Comment by baskinsy** [comment]
There was no upgrade. I just followed the upgrade procedure to launch a rancher-data container. The version before and after was the same.

Output of docker inspect:

```
docker inspect rancher-server
[
{
    "Id": "ca4777aec31043b1aeb1127ccc06de85e675cf18e35617da556d6deec1277c72",
    "Created": "2015-07-11T10:49:13.71162628Z",
    "Path": "/usr/bin/s6-svscan",
    "Args": [
        "/service"
    ],
    "State": {
        "Running": true,
        "Paused": false,
        "Restarting": false,
        "OOMKilled": false,
        "Dead": false,
        "Pid": 1241,                                                                                                                                                    
        "ExitCode": 0,                                                                                                                                                  
        "Error": "",                                                                                                                                                    
        "StartedAt": "2015-07-11T21:52:51.995916467Z",                                                                                                                  
        "FinishedAt": "2015-07-11T21:52:31.481722283Z"
    },
    "Image": "c4466cf0a719f979ef9fe098fcb03b1680cd35e3b5932e1961e46cba4bd7bc82",
    "NetworkSettings": {
        "Bridge": "",
        "EndpointID": "49a25758125c860f6c2ebde955fea7a802d15c373b1b10a9df358fb3f507bb90",
        "Gateway": "172.17.42.1",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "HairpinMode": false,
        "IPAddress": "172.17.0.1",
        "IPPrefixLen": 16,
        "IPv6Gateway": "",
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "MacAddress": "02:42:ac:11:00:01",
        "NetworkID": "d742468995fed1a2310e3fd0a00ecb7d9999d12fbb4b8fcfcd95f9942c728814",
        "PortMapping": null,
        "Ports": {
            "3306/tcp": null,
            "8080/tcp": [
                {
                    "HostIp": "0.0.0.0",
                    "HostPort": "8080"
                }
            ]
        },
        "SandboxKey": "/var/run/docker/netns/ca4777aec310",
        "SecondaryIPAddresses": null,
        "SecondaryIPv6Addresses": null
    },
    "ResolvConfPath": "/var/lib/docker/containers/ca4777aec31043b1aeb1127ccc06de85e675cf18e35617da556d6deec1277c72/resolv.conf",
    "HostnamePath": "/var/lib/docker/containers/ca4777aec31043b1aeb1127ccc06de85e675cf18e35617da556d6deec1277c72/hostname",
    "HostsPath": "/var/lib/docker/containers/ca4777aec31043b1aeb1127ccc06de85e675cf18e35617da556d6deec1277c72/hosts",
    "LogPath": "/var/lib/docker/containers/ca4777aec31043b1aeb1127ccc06de85e675cf18e35617da556d6deec1277c72/ca4777aec31043b1aeb1127ccc06de85e675cf18e35617da556d6deec1277c72-json.log",
    "Name": "/rancher-server",
    "RestartCount": 0,
    "Driver": "aufs",
    "ExecDriver": "native-0.2",
    "MountLabel": "",
    "ProcessLabel": "",
    "Volumes": {
        "/var/lib/cattle": "/var/lib/docker/volumes/f0d05c9112e9c590cd9e92ba4269b8622db5d590ef3cb5277f4281ca8265b3a2/_data",
        "/var/lib/mysql": "/var/lib/docker/volumes/9f274ad54a16ba0598ba9574ecaeb730bb27a3f93858d52f6dc814906051231c/_data"
    },
    "VolumesRW": {
        "/var/lib/cattle": true,
        "/var/lib/mysql": true
    },
    "AppArmorProfile": "",
    "ExecIDs": null,
    "HostConfig": {
        "Binds": null,
        "ContainerIDFile": "",
        "LxcConf": [],
        "Memory": 0,
        "MemorySwap": 0,
        "CpuShares": 0,
        "CpuPeriod": 0,
        "CpusetCpus": "",
        "CpusetMems": "",
        "CpuQuota": 0,
        "BlkioWeight": 0,
        "OomKillDisable": false,
        "Privileged": false,
        "PortBindings": {
            "8080/tcp": [
                {
                    "HostIp": "",
                    "HostPort": "8080"
                }
            ]
        },
        "Links": null,
        "PublishAllPorts": false,
        "Dns": null,
        "DnsSearch": null,
        "ExtraHosts": null,
        "VolumesFrom": [
            "rancher-data"
        ],
        "Devices": [],
        "NetworkMode": "bridge",
        "IpcMode": "",
        "PidMode": "",
        "UTSMode": "",
        "CapAdd": null,
        "CapDrop": null,
        "RestartPolicy": {
            "Name": "always",
            "MaximumRetryCount": 0
        },
        "SecurityOpt": null,
        "ReadonlyRootfs": false,
        "Ulimits": null,
        "LogConfig": {
            "Type": "json-file",
            "Config": {}
        },
        "CgroupParent": ""
    },
    "Config": {
        "Hostname": "ca4777aec310",
        "Domainname": "",
        "User": "",
        "AttachStdin": false,
        "AttachStdout": false,
        "AttachStderr": false,
        "PortSpecs": null,
        "ExposedPorts": {
            "3306/tcp": {},
            "8080/tcp": {}
        },
        "Tty": false,
        "OpenStdin": false,
        "StdinOnce": false,
        "Env": [
            "CATTLE_API_ALLOW_CLIENT_OVERRIDE=true",
            "CATTLE_HOST_API_PROXY_SCHEME=wss",
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "DEBIAN_FRONTEND=noninteractive",
            "CATTLE_HOME=/var/lib/cattle",
            "DEFAULT_CATTLE_API_UI_INDEX=//releases.rancher.com/ui/0.29.0",
            "CATTLE_DB_CATTLE_DATABASE=mysql",
            "S6_SERVICE_DIR=/service",
            "CATTLE_HOST_API_PROXY_MODE=embedded",
            "CATTLE_RANCHER_SERVER_IMAGE=v0.25.0",
            "CATTLE_RANCHER_COMPOSE_VERSION=latest",
            "DEFAULT_CATTLE_RANCHER_COMPOSE_LINUX_URL=https://releases.rancher.com/compose/latest/rancher-compose-linux-amd64.tar.gz",
            "DEFAULT_CATTLE_RANCHER_COMPOSE_DARWIN_URL=https://releases.rancher.com/compose/latest/rancher-compose-darwin-amd64.tar.gz",
            "DEFAULT_CATTLE_RANCHER_COMPOSE_WINDOWS_URL=https://releases.rancher.com/compose/latest/rancher-compose-windows-386.zip",
            "CATTLE_CATTLE_VERSION=v0.58.0",
            "DEFAULT_CATTLE_MACHINE_EXECUTE=true"
        ],
        "Cmd": [
            "/usr/bin/s6-svscan",
            "/service"
        ],
        "Image": "rancher/server",
        "Volumes": {
            "/var/lib/cattle": {},
            "/var/lib/mysql": {}
        },
        "VolumeDriver": "",
        "WorkingDir": "",
        "Entrypoint": null,
        "NetworkDisabled": false,
        "MacAddress": "",
        "OnBuild": null,
        "Labels": {}
    }
}
]
```

**Comment by deniseschannon** [comment]
@vincent99 Could we add a link in the UI to point to this documentation?  http://docs.rancher.com/rancher/rancher-ui/infrastructure/hosts/custom/#samehost

**Comment by vincent99** [comment]
@baskinsy The wss:// thing is because `CATTLE_HOST_API_PROXY_SCHEME=wss` is set in the environment vars for your server container; This is only appropriate when you are doing SSL termination in front of Rancher (`CATTLE_API_ALLOW_CLIENT_OVERRIDE=true` too, but that one doesn't actively break things).

Did you use the command in http://docs.rancher.com/rancher/installing-rancher/installing-server/basic-ssl-config/ to start `rancher/server` instead of http://docs.rancher.com/rancher/installing-rancher/installing-server/ ?

@deniseschannon (@ibuildthecloud) I can add that to the UI... but I'd rather we just detect the situation and not have to have people set the variable in the first place, since it's the first thing setting up Rancher on their laptop has to deal with.

**Comment by loderunner84** [comment]
time="2015-07-21T14:46:07Z" level="info" msg="Starting event router." 
time="2015-07-21T14:46:07Z" level="info" msg="Watching state directory: /var/lib/rancher/state/containers" 
time="2015-07-21T14:46:07Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"213814ca9481f73202a0ca8216125ce9586109164d542d09663e86a7ccd5a447\", From:\"-simulated-\", Time:0}" 
time="2015-07-21T14:46:07Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"f50ebe8778c0551b26d4f9f2611a3d6b8cf027d052ed6b20d9c7880362d57af7\", From:\"-simulated-\", Time:0}" 
time="2015-07-21T14:46:07Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"ce19d323d28523d19e51d3491f28c8e4a5fdeeb8347988961887147f8ede7bc7\", From:\"-simulated-\", Time:0}" 
time="2015-07-21T14:46:07Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"ae2237e42a3ec1bb02d433b41a6a7d4ac6e91bb63f2912cb47e9f1ae76f3cf01\", From:\"-simulated-\", Time:0}" 
time="2015-07-21T14:46:07Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"4b653df6a8a3f475fa01fa995a90d9d23af51c9474198fe46d78fe4ee0572de1\", From:\"-simulated-\", Time:0}" 
time="2015-07-21T14:46:07Z" level="info" msg="Connecting to proxy." url="ws://192.168.2.131:8085/v1/connectbackend?token=eyJhbGciOiJSUzI1NiJ9.eyJleHAiOjE0Mzc0OTAyNjcsInN1YiI6ImNhdHRsZSIsImlzcyI6Imh0dHA6XC9cL2NhdHRsZS5pbyIsInJlcG9ydGVkVXVpZCI6ImJiYjY4MTdmLTBhMTgtNGJjNi1hNWFhLTRlNDA1MDI2ODgxZSIsImlhdCI6MTQzNzQ4OTk2Nywia2lkIjoiZGVmYXVsdCJ9.a_AkNtFQrgM2i8mGoigRpDPDaYp8zuNBZooeJOJDDDn2Y-Km8cACU_Bf4u1mmHBzEKJ2BEDR6IqMj3fNQMtQU70DHF6vAszovacEKdgj0z1PmBcjX9PaxYtr4Z9ketyCn13RgpkjZMEA5SZyqSgOOH7lmzf9tMrFPMRN0AyMojnBahW-n9yxczJUbjYKXUQLwOhOzdUvhjOcihYDYGfBmHaA5lHwKNA62Y2q3wcifnxZIyft4c-THcmBgOZ1vqrI2NWVvbVrOITlAoO6WrYUlAaPDc-7CADDQ3dCtgPBkwLNnjOBur_2FI7Lk9vSNWMKcCrG748L82QVc5jjs68OZQ" 
time="2015-07-21T14:46:07Z" level="fatal" msg="Failed to connect to proxy." error="websocket: bad handshake"
May I fix it by myself?

**Comment by pwFoo** [comment]
I tried to add rancher server and agent to the same host (CentOS7). Also with 
    -e CATTLE_AGENT_IP=<IP_OF_RANCHER_SERVER>
it doesn't work.

I have to open the firewall (172.x.x.x to <public ip>:8080) to see the host in the rancher ui.
Is there another fix to get it work?

**Comment by chriswayg** [comment]
I, like others, tried to add rancher server and agent to the same host. Also with 
-e CATTLE_AGENT_IP=... - it doesn't work:
```
INFO: Running Agent Registration Process, CATTLE_URL=http://example.org:54321/v1
INFO: Checking for Docker version >= 1.6.0
INFO: Found Server version: 1.8.3
INFO: docker version: Client version: 1.6.0
INFO: docker version: Client API version: 1.18
INFO: docker version: OS/Arch (client): linux/amd64
INFO: docker version: Server version: 1.8.3
INFO: docker version: Server API version: 1.20
...
INFO: Attempting to connect to: http://example.org:54321/v1
ERROR: http://example.org:54321/v1 is not accessible
````
How do should I troubleshoot this to get it working?

**Comment by deniseschannon** [comment]
@chriswayg 

Have you tried looking at our troubleshooting docs? It sounds like you need to make sure that your host registration is set up correctly. 

http://docs.rancher.com/rancher/faqs/troubleshooting/

**Comment by tfiduccia** [comment]
Version - master 3/17
Verified fixed
