### ISSUE TITLE
Add option to use nginx ingress controller

### ISSUE THREAD

**Issue by joshwget** [rancher/rancher#8720]

**Comment by joshwget** [comment]
In the Kubernetes 1.6 template the Rancher ingress controller can be disabled. The nginx ingress controller can then be launched via Helm.

**Comment by galal-hussein** [comment]
Rancher server: v1.6.2
Kubernetes: 1.6

I was able to disable Rancher ingress controller and started nginx ingress controller using helm:
```
$ helm install stable/nginx-ingress
```
I was able to test the nginx ingress resources and it worked as expected.
