### ISSUE TITLE
Access to environments with LDAP groups using FreeIPA

### ISSUE THREAD

**Issue by eugeny-zurawski** [rancher/rancher#8725]
Rancher Versions: 1.5.9
Hi,
Please help me to understand what parameters are needed to configure OpenLDAP authentication in Rancher.

I have a LDAP (FreeIPA v4.3) where users with attributes:
objectClass: person
DN: uid=user1,cn=users,cn=accounts,dc=company,dc=com
memberOf: cn=group1,cn=groups,cn=accounts,dc=company,dc=com
And groups:
objectClass: groupofnames
DN: cn=group1,cn=groups,cn=accounts,dc=company,dc=com
member: uid=user1,cn=users,cn=accounts,dc=company,dc=com

I try to configure OpenLDAP authentication in Rancher with customized schema like this:
Users
Search Base: dc=company,dc=com
Object Class: person
Login Field: uid
Name Field: displayName
Search Field: uid
User Member Atribute: memberOf
Group
Search Base: dc=company,dc=com
Object Class: posixgroup
Name Field: cn
Search Field: cn
Group Member User Attribute: uid
Group Member Mapping Attribute: member
Group DN Field: member

Also I add 'group1' to Members of environment with type 'Group'.

So, when I login with user1 to Rancher I don't have access to environment (as a member of group1).
But, If I add the user1 to Members of environment with type 'User' separately - this user can access the environment.

**Comment by ray65536** [comment]
Very strange - in my case Rancher request attributes with "User Member Attribute" (memberOf?), and loops through them, trying to ask something like this:
`Filter: (&(XXATRRXX=cn=rancher_users,cn=groups,cn=accounts,dc=company,dc=name)(objectClass=OBCLASS))`
where XXATRRXX - it's value of field of user, specified by "User Member Attribute" (it's actually memberOf in my configuration, and contains DN's of groups)
and OBCLASS - value of Group - "Object Class" field.

Of course, whatever I set in Group DN Filed - no field of any group contains DN  of group itself, and as a result - only auth by user in mode "Any valid user" is working now.

How to authenticate via group membership? How should it work?

**Comment by mrajashree** [comment]
@eugeny-zurawski looks like while configuring Rancher the value of objectclass for group you're providing is posixgroup, but it should be groupofnames. Can you try with that please?

**Comment by ivan-exness** [comment]
@mrajashree I have tried with GroupOfNames, but users can't access my env until I add them by login

![screen shot 2017-07-17 at 10 40 10](https://user-images.githubusercontent.com/17728801/28259368-9a0a08a8-6ade-11e7-92a1-586f9b9664e8.png)
![screen shot 2017-07-17 at 10 41 27](https://user-images.githubusercontent.com/17728801/28259369-9a2b49f0-6ade-11e7-9ecd-c064e134704f.png)

**Comment by eugeny-zurawski** [comment]
Thank you all for the comments.

Yes, I tried to use groupOfNames as "Groups: Object Class" attribute, but it does not work.
I also tried various combinations of attributes on newer versions (current version 1.6.4).

At the moment, I was not able to make separate access to environment via group membership.
But I can successfully add a group from LDAP as the type "Group" via "Manage Environments" - "Access Control". Sо, I think the problem is in correct mapping of user in group.

**Comment by rocketeer125** [comment]
Same issue here.

**Comment by ReidWeb** [comment]
I also believe I am having this issue.

**Comment by mrajashree** [comment]
@ReidWeb which rancher version are you using? Is your provider Openldap too or is it Active Directory?

**Comment by ReidWeb** [comment]
@mrajashree I am using OpenLDAP, Rancher v1.6.9

My users of are of type `inetOrgPerson`, groups of type `groupOfUniqueNames`.

Group membership does not appear to be mapping correctly, I have configuration as below.
![screen shot 2017-09-19 at 21 10 53](https://user-images.githubusercontent.com/3649078/30614320-eab38c1c-9d82-11e7-80e3-eefb7c7600ee.png)

**Comment by prachidamle** [comment]
@eugeny-zurawski  

To enable the group access correctly, following two fields need to be configured correctly in Rancher OpenLDAP config: Group Member User Attribute and Group DN Field

1) Group Member User Attribute:  This property helps incase your group object contains the attribute like "member" listing the members of the group.

Value of "Group Member User Attribute" should be the attribute of your User Object whose value is same as what is stored against the "member" property of Group Object.

Thus, if your Group object schema shows:
```
objectClass: groupofnames
DN: cn=group1,cn=groups,cn=accounts,dc=company,dc=com
member: uid=user1,cn=users,cn=accounts,dc=company,dc=com
```

Then, find the attribute on your userObject that has the complete value "uid=user1,cn=users,cn=accounts,dc=company,dc=com". 
If there is no visible attribute, fetch the "operational attributes" of the user Object. Most likely there should be the operation attribute "entryDN" that has this complete DN of the user.

Try the default value 'entryDN' for "Group Member User Attribute" on Rancher config and see if that helps.

2) Group DN Field: This property helps incase your user object contains the attribute like "memberOf" that points to groups the user is part of.

Value of "Group DN Field" should be the attribute of your Group Object whose value is same as what is stored against the "memberOf" property of User Object - this is most likely an attribute that gives entire DN of your group.

Thus if your User object schema shows:
```
objectClass: person
DN: uid=user1,cn=users,cn=accounts,dc=company,dc=com
memberOf: cn=group1,cn=groups,cn=accounts,dc=company,dc=com
```
Then find the attribute on your group object that has the complete value "cn=group1,cn=groups,cn=accounts,dc=company,dc=com" - likely again the operational attribute like entryDN will be the one incase there is no other attribute. 

Please try 'entryDN' as the value for "Group DN" on Rancher config.

 @ray65536 @ivan-exness @rocketeer125 @ReidWeb Please can you check the above as well, along with other config like userObject/groupObject as needed for your OpenLdap

**Comment by matthijsvdr** [comment]
So in rancher 1.6.10 using freeipa configured the following:
![rancher-ldap](https://user-images.githubusercontent.com/1271035/30797358-00dc6412-a1d6-11e7-9ba5-74f180804bfa.PNG)

![rancher-advanced](https://user-images.githubusercontent.com/1271035/30800158-6122bc28-a1df-11e7-9acd-639e2abcc665.PNG)


**Only** the `admins` group gives users access, adding people into the `rancher-admins` group does not allow them to login and they will get the following error:

![rancher-noaccsess](https://user-images.githubusercontent.com/1271035/30797384-1a729388-a1d6-11e7-9492-e8bd592dac55.PNG)

I short:
If I add the test user to only the `admins` group -> access
If I add the test user to only the `rancher-admins` group -> no access

Talk about this with @superseb on slack but he never came back to me.

**Comment by Kurisutian** [comment]
I have trouble setting up group access as well. In the LDAP setup used in my company, the user does not have a field which includes the groups the user is a member of. Instead we have a member attribute in the groups which lists all members of the group. The "problem" is that this field does not only contains the username but is something like "uid=<username>". So I currently do not know what to put into the group member mapping attribute to tell rancher to just take the username and ignore the "uid=" part of that content. Does anyone know what to put into that field? 
Everything else (single user management, finding the groups) works but somehow rancher does not know about the members of each group.

**Comment by m4ce** [comment]
Running rancher 1.6.15 and tried to hook it up to FreeIPA. Group-based authentication is still not working :/

**Comment by superseb** [comment]
This is going to need a code change to make it work, because of  the way Rancher looks up the group which seems to work for OpenLDAP but not for IPA like systems.

**Comment by 222Acc** [comment]
I've managed to enable group access with "entryDN" as "Group Member User Attribute" and "member" as "Group Member Mapping Attribute" ( v1.6.18 )
![rancher_ldap](https://user-images.githubusercontent.com/41634487/43142000-07d6baf6-8f60-11e8-8fdf-363e852c1924.png)

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

Rancher 2.0 has specific FreeIPA icon in the UI and you can search for groups on the cluster and project level.

**Comment by leopepe** [comment]
The same problem is happening with Rancher 2
