### ISSUE TITLE
Proposal: Make Project/Environment name unique

### ISSUE THREAD

**Issue by Nosmoht** [rancher/rancher#8728]
**Rancher Versions: 1.5.8**

Hi all,

i'm currently implementing some Ansible modules to manage all kind of Rancher stuff using API v2-beta.

While implementing a module to create, update and delete Projects/Environments i realized that i can create a project with the same name multiple times. 

Proposal: make the name attribute unique. 

I don't see any reason why i should have multiple projects/environments with the same name. Is there any?

Kind regards,
Thomas

**Comment by vincent99** [comment]
1) Alice creates a project and names it "dev".
2) Bob creates a project and also names it "dev".
3) Alice adds Bob as a member of her project.  Bob now has access to two environments with the same name.

The only way they can be unique ID if they are globally unique (ala Amazon S3 buckets), which we don't like and users don't like ("I don't even know Alice, why does she get 'dev?'").  It leads to land rushes where people pre-grab all the "good" names just so they can have them.

**Comment by Nosmoht** [comment]
Valid point. Sorry for proposing a solution without mentioning the problem.

The problem is that i need to identify a project based on something else than the id. Is there any way how to do that (e.g. user.id + project.name)? 

As i'm planing to implement some more modules i would also like to know if the is a documentation about the data model.

Thanks

**Comment by vincent99** [comment]
I don't understand the problem, why do you need to identify a project by something other than its identity?  There is a `uuid` too, but I don't think that's going to be any different to you.

User <-> Env membership (or ownership) is a many-to-many mapping.  So user_id+project_name is no more unique.

While it is possible sad I said above, it is sufficiently confusing when a user gets in that situation that it doesn't come up (or stay that way) very often.  So one option may by to assume the name is unique to that use and fail if you get back more than one with that name.

**Comment by Nosmoht** [comment]
Why i need that: 

I use Ansible to deploy systems. Each Ansible module ensures the state of a defined resource, like a Rancher Project. The process is mostly always the same: check if the resource does exist, create it if not, update it if properties differ, delete it if ```state==absent``` (CRUD). Users don't know the internal id or uuid of a project and like to use something human readable and understandable like a name.

Example
```yaml
- name: Ensure Rancher project exists
  rancher_project:
    name: demo
    description: Demo project
    template: Kubernetes
```

In addition Ansible likes idempotency. Running a playbook a second time should not change anything if nothing changed.

If i don't have anything to uniquely identify the project  (except id+uuid which i don't know within the first Ansible run when the project will be created) the module has to create the project with every tun, ending up in an endless amount of projects.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
