### ISSUE TITLE
Error: Add Host - register.py, line 21 IndexError: list index out of range

### ISSUE THREAD

**Issue by house-md** [rancher/rancher#8729]
**Rancher Versions:**
Server: v1.6.0 (I tried also version v1.5.8)
**Docker Version:**
17.03.1.-ce

**OS and where are the hosts located? (cloud, bare metal, etc):**
Debian jessie virtualized

**Setup Details: single node**

**Environment Type: Cattle**

**Steps to Reproduce:**
install fresh rancher/server sudo docker run -d --restart=unless-stopped -p 8080:8080 rancher/server

set internal IP for host registrations

run command for adding host sudo docker run --rm --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.2.2 http://192.168.2.19:8080/v1/scripts/D34CFBF55A0D351D1075:1483142400000:H063eao6fveZB6tbncuOURLdMh8

**Results:** 
container_linux.go:247: starting container process caused "operation not permitted"
docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "operation not permitted".

when I try add host with the same command but without --privileged I got this:
INFO: Running Agent Registration Process, CATTLE_URL=http://192.168.2.19:8080/v1
INFO: Attempting to connect to: http://192.168.2.19:8080/v1
INFO: http://192.168.2.19:8080/v1 is accessible
INFO: Inspecting host capabilities
container_linux.go:247: starting container process caused "operation not permitted"
docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "operation not permitted".

INFO: Boot2Docker:
INFO: Host writable:
INFO: Token:
INFO: Running registration
Traceback (most recent call last):
  File "./register.py", line 21, in <module>
    key = sys.argv[1]
IndexError: list index out of range

**Comment by superseb** [comment]
Can you run any privileged container i.e. is this Rancher specific?

What does `uname -r` and `docker info` return?

**Comment by house-md** [comment]
@superseb right now i tried another container in privileged mode and got this error
**docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "operation not permitted".**
without --privileged it was ok

**uname -r** => 3.16.0-4-amd64
**docker info** => Containers: 11
 Running: 4
 Paused: 0
 Stopped: 7
Images: 12
Server Version: 17.03.1-ce
Storage Driver: vfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie) (containerized)
OSType: linux
Architecture: x86_64
CPUs: 24
Total Memory: 31.47 GiB
Name: ##########
ID: FE6I:EGQS:IPT5:74YO:OBBR:543G:WWKY:BVXD:RZ5M:5CVD:WDAI:CTE2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by house-md** [comment]
@superseb I'm sorry for mistake in first message. I wrote it's on bare metal but this one is running in virtual machine.

**Comment by superseb** [comment]
Ok, this is not a Rancher specific issue it seems. You can't run any privileged container which will  influence running the rancher/agent container. Please file an issue here https://github.com/moby/moby/issues to fix your privileged run issue and please try running the Rancher agent again. Going to close this as I can't do much at the moment. Jump on Rancher Users Slack if you need help filing the Docker/moby issue.
