### ISSUE TITLE
Pagination on hosts

### ISSUE THREAD

**Issue by ciokan** [rancher/rancher#8730]
We have about 60 hosts/servers on our current setup and loading the page where they are being displayed is a hit and miss 50% of the time. The browser simply crashes. We're about to migrate 120 more servers but it will make it impossible to do even the simplest operations I believe.

Is there any plan at addressing this issue at all?

**Comment by vincent99** [comment]
Yes, already in master for 2.0.  Try using the "dots" view for now, it's significantly faster.
