### ISSUE TITLE
HAProxy LB debug level logs on Rancher. 

### ISSUE THREAD

**Issue by sagarmah** [rancher/rancher#8731]
**Rancher Versions:**
Server: 1.5.5
healthcheck: 0.2.3
ipsec: 0.11.2
network-services: 0.6.6
scheduler: 0.6.3
kubernetes (if applicable):

**Docker Version: 17.03.0**

**OS and where are the hosts located? (cloud, bare metal, etc): CentOS 7 bare metal **

**Setup Details: HA Rancher with External DB**

**Environment Type: Cattle**

Problem: I have added the loadbalancer service to my stack, I am getting some rare 504 and 503 Errors on the browser, I would like to get debug level logs from the HAProxy Loadbalancer. I see the LB uses rancher/lb-service-haproxy:v0.6.4 image and inside the container rsyslog and haproxy are running, but I dont see any logs saved in the errors, traffic and events files. I even have a ELK stack on my Rancher, If someone can suggest a way to push these LB logs to Kibana or Logstash even that will be great. I need to find what causes the 504s. I understand similar questions have been asked, but I find no resolution yet. Thanks.

**Comment by aemneina** [comment]
@sagarmah you need to add a custom configuration for the LB to enable logging. Under the custom haproxy.cfg tab in the ui you can specify:
```
defaults
log 127.0.0.1:8514 local0 debug
```

and then you should see events/traffic/error logs populated.

**Comment by GeBeater** [comment]
@aemneina Regarding the documentation, this will work "As of Rancher v1.6.11".

http://rancher.com/docs/rancher/v1.6/en/faqs/troubleshooting/

Do you or anybody else know how to enable debug logging for previous version?

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
