### ISSUE TITLE
`upgrade_from` doesn't work with catalog-service

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#8733]
Currently, you are supposed to be able to put in `upgrade_from` in the rancher-compose.yml files to restrict which template could upgrade to the specific version. 

http://docs.rancher.com/rancher/v1.6/en/catalog/private-catalog/#rancher-catalog-templates

**Comment by cjellick** [comment]
Available to test on master

**Comment by tfiduccia** [comment]
Version - master 5/17
Verified fixed
