### ISSUE TITLE
[external-dns] support OVH as a DNS provider

### ISSUE THREAD

**Issue by jon-d** [rancher/rancher#8735]
OVH is an important ISP providing a public DNS service with an API.

They published a go library to use their API : https://github.com/ovh/go-ovh

It would be really nice to support this provider in the external-dns service.

If you find this request worthy of interest, I may be able to provide a patch (no strong promises here, I never coded a line in go :-)).

**Comment by vincent99** [comment]
PRs welcome, these are mostly community contributed.  (external-dns BTW, rancher-dns is not the same thing)

**Comment by jon-d** [comment]
Ok thanks for your answer, I will give an update here if I try to make a patch.

For the title I followed the link in external-dns README file.
