### ISSUE TITLE
Ability to have an admin in the local DB as well authenticate with other providers.  

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#8740]
Comment from https://github.com/rancher/rancher/issues/5488#issuecomment-235931132

**Comment by dmariage** [comment]
need

**Comment by rv-cdiaz** [comment]
Would love to see this!

**Comment by deniseschannon** [comment]
This is available in Rancher 2.0. Ability to have local users as well as authenticate for other providers.

**Comment by sangeethah** [comment]
With latest 2.0 build from master .

We have the ability to allow for existing local auth users to continue to have access to rancher server when AD/github auth is enabled.
