### ISSUE TITLE
Question: a file with variables to be used in docker/rancher compose

### ISSUE THREAD

**Issue by pdonorio** [rancher/rancher#8741]
Hello,

I find very comfortable to use the `.env` file for docker-compose when using docker, as specified in [their documentation](https://docs.docker.com/compose/env-file/)

I didn't understand if there is such a mechanism with rancher and didn't find anything about this in the documentation. This is very important when uploading new stacks from a docker-compose and rancher-compose file, because you may use the same element in different services definition.

May you kindly lead me to a solution?

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
