### ISSUE TITLE
Health Checks never complete on initial build for any thing but "Heaven1 and Capricorn1"

### ISSUE THREAD

**Issue by qtopia7100** [rancher/rancher#8743]
*Describe your issue here*

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.5.9` Cattle: `v0.178.12` UI: `v1.5.9` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`service.containers`|

**Comment by qtopia7100** [comment]
This is happening in AWS from your AMI (SIEMonster-2.5 - ami-8fad36ef)

**Comment by vincent99** [comment]
While it appears this product uses Rancher under the hood, its setup instructions and AMIs have nothing to do with us and your should contact them.

But you probably have the security group or network config won't on the hosts that aren't working if there are two hosts that _can_ communicate.  Health checks check each other.
