### ISSUE TITLE
Distinguish between user and group when listing identities

### ISSUE THREAD

**Issue by joshwget** [rancher/rancher#8744]
`/v2-beta/identities` returns various information and it would helpful to be able to distinguish between users and groups. Some additional field that can have value `user` or `group` would probably be enough.

The alternative is to just search for `*_user`, which is a little hacky.

```
    {
        "id": "1i!github_user:6208550",
        "type": "identity",
        "links": {
            "self": "…/v2-beta/identities/1i!github_user:6208550"
        },
        "actions": { },
        "baseType": "identity",
        "all": null,
        "externalId": "6208550",
        "externalIdType": "github_user",
        "login": "joshwget",
        "name": "Josh Curl",
        "profilePicture": "https://avatars3.githubusercontent.com/u/6208550?v=3",
        "profileUrl": "https://github.com/joshwget",
        "projectId": null,
        "role": null
    },
    {
        "id": "1i!github_team:1580870",
        "type": "identity",
        "links": {
            "self": "…/v2-beta/identities/1i!github_team:1580870"
        },
        "actions": { },
        "baseType": "identity",
        "all": null,
        "externalId": "1580870",
        "externalIdType": "github_team",
        "login": "sherdock",
        "name": "Sherdock",
        "profilePicture": "https://avatars0.githubusercontent.com/u/9343010?v=3",
        "profileUrl": "https://github.com/orgs/rancher/teams/sherdock",
        "projectId": null,
        "role": null
    },
    {
        "id": "1i!rancher_id:1a1",
        "type": "identity",
        "links": {
            "self": "…/v2-beta/identities/1i!rancher_id:1a1"
        },
        "actions": { },
        "baseType": "identity",
        "all": null,
        "externalId": "1a1",
        "externalIdType": "rancher_id",
        "login": null,
        "name": "Josh Curl",
        "profilePicture": null,
        "profileUrl": null,
        "projectId": null,
        "role": null
    },
    {
        "id": "1i!github_org:9343010",
        "type": "identity",
        "links": {
            "self": "…/v2-beta/identities/1i!github_org:9343010"
        },
        "actions": { },
        "baseType": "identity",
        "all": null,
        "externalId": "9343010",
        "externalIdType": "github_org",
        "login": "rancher",
        "name": "Rancher",
        "profilePicture": "https://avatars0.githubusercontent.com/u/9343010?v=3",
        "profileUrl": "https://github.com/rancher",
        "projectId": null,
        "role": null
    },
]
```

**Comment by mrajashree** [comment]
The field `externalIdType` does differentiate between the user and group, but since a field with only values `user` or `group` is needed, I'll add a new field to the `Identity` class in cattle. Should I call it `identityType`?
@vincent99 @prachidamle @cjellick

**Comment by joshwget** [comment]
Each returned identity should have two additional fields.
`me` - Identity is associated with the current access key / private key
`user` - Identity is a user type and not non-user type (group, team, etc...)

**Comment by prachidamle** [comment]
@mrajashree maybe we should be able to take care of this issue while you are working in the same area for above fix:
https://github.com/rancher/rancher/issues/8754

**Comment by cjellick** [comment]
Let's limit the scope for now to just implementing `me` and `user`.

**Comment by cjellick** [comment]
available to test on master

**Comment by sangeethah** [comment]
Tested with latest build from master:
When accessing http://<rancher-server>:8080/v2-beta/identities , ```"user": true``` is set for the user entries.

For github auth enabled setup , following 2 entries have "user": true set:
"externalIdType": "github_user”,
"externalIdType": “rancher_id

For openLdap auth enabled setup , following  2 entries have "user": true set:
"externalIdType": “openldap_user”,
"externalIdType": “rancher_id

For local auth enabled setup,1 entry has  "user": true set:
"externalIdType": "rancher_id”,

**Comment by sangeethah** [comment]
For SAML auth provider(Tested with PingFederator) , 2 entries have "user": true set:
"externalIdType": “shibboleth_user”,
"externalIdType": “rancher_id"
