### ISSUE TITLE
 Use java.net.URI in cattle framework. java.net.URL breaks websocket protocol in some cases

### ISSUE THREAD

**Issue by ketchoop** [rancher/rancher#8745]
When java.net.URL parses URL it reads, for example, X-Forwarded-Proto(when you use proxies) that can contain WS protocol. So, it breaks ws connection at all and make troubles with UI.

More details in [this related issue ](https://github.com/fabiolb/fabio/issues/133)

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
