### ISSUE TITLE
is it possible to customize rancher/lb-service-haproxy

### ISSUE THREAD

**Issue by earzur** [rancher/rancher#8746]
**Rancher versions:**
rancher/server: 1.4.1
rancher/agent: 1.2.0

**Infrastructure Stack versions:**
healthcheck: 0.2.3
ipsec: ??
network-services: 0.6.6
scheduler: 0.6.3
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
```
Containers: 27
 Running: 26
 Paused: 0
 Stopped: 1
Images: 81
Server Version: 1.12.6
Storage Driver: devicemapper
 Pool Name: docker-thinpool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file:
 Metadata file:
 Data Space Used: 6.557 GB
 Data Space Total: 18.43 GB
 Data Space Available: 11.87 GB
 Metadata Space Used: 10.12 MB
 Metadata Space Total: 20.97 MB
 Metadata Space Available: 10.85 MB
 Thin Pool Minimum Free Space: 1.843 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.110 (2015-10-30)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-64-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.795 GiB
Name: ip-10-2-7-117
ID: MYAW:Z6TW:QLK5:GMBX:DZ6L:3A6H:WY64:ICYE:CREA:SVU6:UC5Y:NBOJ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
erwan@ip-10-2-7-117:~$ cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
erwan@ip-10-2-7-117:~$ uname -r
4.4.0-64-generic
```
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
server with external DB (RDS) running 2 environments (ASGs with auto registration)
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Context**

rancher/lb-service-haproxy:v0.5.9 in front of several containers for a JSON based API. I'm trying to make haproxy send JSON error responses instead of HTML (so clients can easily parse errors from the LB)

So i tried to build a simple container with rancher/lb-service-haproxy as a base and replace the files in /etc/haproxy/errrors with my own customized templates.

We use packer (packer.io) to build our containers the json template is as follow:

```json
{
  "variables": {
    "aws_access_key": "",
    "aws_secret_key": "",
    "region": "eu-central-1",
    "service_build": "{{isotime \"20060102150405\"}}",
    "container": "my/rancher-lb",
    "docker_tag": "latest"
  },
  "builders": [
    {
      "type": "docker",
      "image": "rancher/lb-service-haproxy:v0.5.9",
      "commit": true,
      "pull": false,
      "changes": [
        "CMD [ \"lb-controller.sh\", \"--controller\", \"rancher\",\"--provider\",\"haproxy\" ]"
      ],
      "run_command": ["-d","-u","0", "-i", "-t", "{{.Image}}", "/bin/bash"]
    }
  ],
  "provisioners": [
    {
      "type": "shell",
      "inline": "mkdir -p /etc/haproxy/errors"
    },
    {
      "type": "file",
      "source": "errors/",
      "destination": "/etc/haproxy/errors"
    }
  ],
  "post-processors": [
    [
      {
        "type": "docker-tag",
        "repository": "{{user `container`}}",
        "tag": "{{ user `service_build`}}"
      }
    ]
  ]
}
```

When i replace the standard image with my custom image in the stack's `docker-compose.yml`, rancher successfully deploys it, but i get the following error messages in the container's logs:
`Error: Unknown schema type [certificate] 'my-custom-cert' Coudln't get certificate by name`

Just like the `lb-controller.sh` script could not correctly retrieve informations from the meta-data service... is it a naming issue ? Does the server do something special regarding containers named "rancher/lb-service-haproxy" ?

If i'm doing it wrong, what would be the easiest way to do that kind of operations that change some stuff in haproxy's anciliary configuration ?

Thanks in advance

**Comment by 0ff** [comment]
@earzur okay so we've run into the very same problem multiple times and now I think we might've figured out where the problem is with this `Error: Unknown schema type [certificate] 'my-custom-cert' Coudln't get certificate by name`.

It seems that rancher somehow (undocumented, which is bad, obviously) validates the image of the LB accessing certificates. It does so using the setting `lb.instance.image.uuid`.
Please try the following: 

1. Upgrade your LB to your custom image (via API or CLI, UI won't allow until you've changed admin setting)
2. Observe the error in the log
3. Shutdown your LB
4. Go here: http://rancher:8080/v2-beta/settings/lb.instance.image.uuid - change the `value` to `docker:` + the name of your image, such as: `docker:my/rancher-lb:latest`
5. Restart your LB
6. Party hard as error is gone 🎉

**Comment by earzur** [comment]
AWESOME. That was exactly what I was thinking about. I just wonder how you
ended up finding that setting ?

if our paths ever cross, i owe you a beer ;-)
