### ISSUE TITLE
Ability to protect environments/stacks from certain actions (i.e. delete)

### ISSUE THREAD

**Issue by imorti** [rancher/rancher#8747]
When creating an environment in Rancher there should be an option for termination protection on a stack. For example, if I create a production environment on Rancher for certain stacks. I don't want to be able to just click on the stack and select delete. I'd like the option, on the environment or stack level, to enable delete protection. This is similar to termination protection in AWS.

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/8407
