### ISSUE TITLE
Link to current version on every docs page should try to stay on the same page (if it exists)

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#8748]
If you hit a docs page of a previous version, the banner `These docs are for Rancher v1.x, for the current version, see here.` appears. If you click it, it takes you to the root of latest. It should try to locate the same page for latest, if it does not exist anymore, go to earlier subsection or root.

**Comment by gaieges** [comment]
I believe this regressed as of another change that @superseb eluded to.  I think this should be open still.

**Comment by superseb** [comment]
Yep there was a redirect problem which we cannot reproduce yet :/

**Comment by superseb** [comment]
I think @deniseschannon fixed this, @gaieges mind trying it out?

**Comment by gaieges** [comment]
Confirmed, looks good, thanks @superseb !  Makes my life so much more convenient :)
