### ISSUE TITLE
service description field causing error when importing from rancher-compose

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#8749]
**Rancher versions:** v1.6.0

**Steps to Reproduce:**
1.  Create a v1 catalog template where rancher compose has a description field for a service
2.  Try to run the catalog

**Results:**  I get an error saying "Error (unsupported config option for <servicename> service: 'description')  When I run this same catalog in 1.4 it runs fine.

**Comment by deniseschannon** [comment]
Available in master

**Comment by tfiduccia** [comment]
Version - master 5/26
Verified fixed
