### ISSUE TITLE
Unable to bring up catalog questions when added per environment

### ISSUE THREAD

**Issue by amy** [rancher/rancher#8752]
Unable to bring up catalog questions when catalog added per environment.

![image](https://cloud.githubusercontent.com/assets/5957700/25972305/7439884c-366d-11e7-9528-0b2c1d2410e8.png)

**Comment by vincent99** [comment]
This appears to be the UI not sending the project ID header for that request...

**Comment by tfiduccia** [comment]
Version - master 5/17
Verified fixed
