### ISSUE TITLE
Auth framework enhancement: List identities call seems to grab user identities from external auth provider every time

### ISSUE THREAD

**Issue by prachidamle** [rancher/rancher#8754]
**Rancher versions:**
rancher/server: 1.6

It seems like /v2-beta/identities list API seems to connect to backend auth provider to get the user's identities each time. 

Instead we should be using the identities stored in the JWT of auth_token record saved when the user logs in. 

We can decide to fetch the identities from backend depending on how old the token has been (say if token has been created within last say 4 hrs(configurable), just use the identities from the token, else grab from backend)

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
