### ISSUE TITLE
Rancher UI requires a browser reload extremely  slow to do anything

### ISSUE THREAD

**Issue by obenziane2** [rancher/rancher#8756]
**Rancher versions:**
rancher/server: 1.5.9
rancher/agent: 1.2.2

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
1.12.6
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
AWS linux machine, also happens on Ubuntu 14.04 
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**
Install rancher 1.5.9 with MySQL 5.6 or 5.7 with HA two nodes with virtually virgin install

**Results:**

If i create one stack or any task it does not complete in few but a several minutes or forever. I can only fix it if i refresh the browser and then it's done.

Not sure if this is a Browser or server or Database issue ?
<img width="1331" alt="screen shot 2017-05-11 at 3 32 25 pm" src="https://cloud.githubusercontent.com/assets/11947294/25974755/87bf8e2e-365f-11e7-800c-91a309bf9cc4.png">

**Comment by obenziane2** [comment]
To add , it takes a few second to complete but forever to refresh the status of the page unless i reload the browser page
<img width="1127" alt="screen shot 2017-05-11 at 4 11 52 pm" src="https://cloud.githubusercontent.com/assets/11947294/25975703/c8b8bb6c-3664-11e7-9d2a-62ac2d4be06b.png">

**Comment by vincent99** [comment]
Check the network tab of the browser dev tools, you're probably not connected to the websocket (`/v2-beta/subscribe`) for some reason.

**Comment by obenziane2** [comment]
You're right! I'm using the ELB and not ALB for this setup. Are they any settings to make it work without having switch to ALB ?

**Comment by vincent99** [comment]
TCP/TLS listener and target with PROXY protocol: http://docs.rancher.com/rancher/v1.6/en/installing-rancher/installing-server/#elb

**Comment by obenziane2** [comment]
Thank you so much , I have switched to ALB
