### ISSUE TITLE
Services With Crontab Are Started Even When Stack is Stopped / Service Inactive

### ISSUE THREAD

**Issue by derks** [rancher/rancher#8757]
I understand this is for a community supported catalog item, however I submitted this there (I think this was the right place?) and have not had any reply (https://github.com/rancher/container-crontab/issues/1):

**Rancher versions:**
rancher/server: `1.0.0`
rancher/agent: `1.2.0`

**Infrastructure Stack versions:**
healthcheck: `0.2.3`
ipsec: `0.0.4`
network-services: `v0.0.7`
scheduler: `0.4.0`
kubernetes (if applicable): `n/a`

**Docker version: (`docker version`,`docker info` preferred)**

docker: `1.12.6`

docker info:

```
Containers: 70
 Running: 22
 Paused: 0
 Stopped: 48
Images: 32
Server Version: 1.12.6
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local rancher-nfs
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.9.21-rancher
Operating System: RancherOS v1.0.0
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.67 GiB
Name: SCRUBBED
ID: SCRUBBED
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

```
$ cat /etc/os-release
NAME="RancherOS"
VERSION=v1.0.0
ID=rancheros
ID_LIKE=
VERSION_ID=v1.0.0
PRETTY_NAME="RancherOS v1.0.0"
HOME_URL="http://rancher.com/rancher-os/"
SUPPORT_URL="https://forums.rancher.com/c/rancher-os"
BUG_REPORT_URL="https://github.com/rancher/os/issues"
BUILD_ID=

$ uname -r
4.9.21-rancher
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

HA Rancher:
- App: 3 Nodes
- Compute: 4 Nodes
- DB: AWS RDS MySQL

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

Cattle

**Steps to Reproduce:**

- Install Container Crontab from Community Catalog (`0.1.0-rancher1`)
- Create a Stack
- Create a Service with label: `cron.schedule`
- Stop Stack or Service

**Results:**

Stacks/Containers that are stopped/inactive will still be executed by `container-cron`.

**Comment by cloudnautique** [comment]
Container crontab, is Docker based and has no concept of Rancher'isms. The reasoning behind docker based events is that it can run anywhere, particularly RancherOS. In general, I'm hoping to keep this fairly unintelligent, but it might a need a little bit of smarts.

Would upgrading the service to have`cron.action=none` before stopping be viable? I'm not sure if we are supporting label editing yet. `none` doesn't exist yet, but that could disable it. Thinking about the normal Cron behavior, you have to remove the entry or edit the file. So this would be a similar approach.

**Comment by vincent99** [comment]
That sounds not very friendly/convenient...

I'd say check `curl http://rancher-metadata/2016-07-29/self/stack/state` and proceed if you get back DNS error so it will still work standalone.  But `stacks` don't currently have `state` in metadata...

**Comment by vincent99** [comment]
Actually stacks don't ever go inactive so just looking at service.state == active would work, and that is in metadata...

**Comment by derks** [comment]
@cloudnautique our use case on this was that during the deploy of our app stack, we stop related cron services, then once upgrade is completed or rolled back, then start the cron services back up.  Trouble being that even if the stack/services were stopped those containers were running during upgrade.

The other use case is during testing (staging)...  at times we might want to halt cron services to prevent cleanup items from happening while we fix edge-case issues.  Stopping the stack makes sense... but having to edit all the services one by one to disable cron isn't fun, and having to modify `docker-compose.yml` and re-deploying isn't ideal either.

**Comment by abeMedia** [comment]
I have been noticing a similar problem. I have a number of containers which are meant to run once a day and perform maintenance tasks, however since using rancher-crontab they are restarted continuously throughout the day, even though `cron.schedule` is set to `@midnight`.

**Comment by cloudnautique** [comment]
PR rancher/container-crontab#5 has QA instructions.

**Comment by galal-hussein** [comment]
@cloudnautique I was able to run the QA tests on the crontab service with both rancher mode and normal mode, and it ran successfully with no issues, i was also able to verify that container crontab service exposes Prometheus metrics on port 9191
