### ISSUE TITLE
Unable to edit service alias

### ISSUE THREAD

**Issue by njordr** [rancher/rancher#8759]
Hi.
I defined a service alias for a service. After that I need to remove the service to re-create it.
Now if I try to edit the service alias, all the page become white (I suppose it's the modal), but no way to change its settings, because no form appears

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.5.8` Cattle: `v0.178.11` UI: `v1.5.9` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`stacks.index`|

**Comment by aemneina** [comment]
@njordr do you have any browser plugins? Curious what browser this is... I wasnt able to reproduce this with 1.5.9 (local auth as well).

**Comment by njordr** [comment]
It's Firefox, but I tried also with brave and Chrome

**Comment by greggythefly** [comment]
I have the same Issue on Chrome and Safari

**Comment by greggythefly** [comment]
<img width="825" alt="capture d ecran 2017-05-20 a 08 35 05" src="https://cloud.githubusercontent.com/assets/913000/26273757/56496962-3d37-11e7-9a42-dfb8b2722eba.png">

**Comment by vukor** [comment]
Have same issue on version 1.5.9 and 1.6 in browsers Safari 10.1 (12603.1.30.0.34) and Chrome 58.0.3029.110 (64-bit).
![screen shot 2017-05-23 at 14 23 14](https://cloud.githubusercontent.com/assets/4919948/26342800/a877cd62-3fc3-11e7-802f-81a888e085a3.png)

**Comment by greggythefly** [comment]
I have narrowed it down, the issue appears only for alias where the destination doesn't exists anymore

**Comment by vincent99** [comment]
@tfiduccia I think we fixed this a while ago in 1.6.x

**Comment by tfiduccia** [comment]
Version - 1.6.10 & 2.0 master 10/10
Verified fixed
