### ISSUE TITLE
Algorithm for Service Load Balancer limited to Round Robin

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#876]
v0.21.1
When I add a Service Load Balancer the Algorithm is limited to Round Robin only.  When I add a regular Load Balancer through the Load Balancer page, I get a choice of three: Round Robin, LeastConn & source.

Expected:
The Service Load Balancer should also give the three choices for Algorithm.

**Comment by alena1108** [comment]
yea, thats a known issue. As algorithm is a field on the listener, and in service we derive the listener object from the port defined in launch config, there is no way to put that property there. We should change perhaps by defining the algorithm on per lb config basis.

**Comment by vincent99** [comment]
@alena1108 Seems like now that we have labels we could them for the balancing algorithm.  For example

`io.rancher.loadbalancer.algorithm=leastconn` and it applies to every listener,
or `io.rancher.loadbalancer.algorithm.80=leastconn`, `io.rancher.loadbalancer.algorithm.90=source` to do per-listener ports.

**Comment by alena1108** [comment]
This PR fixes it: https://github.com/rancher/cattle/pull/1160

**Comment by alena1108** [comment]
@sangeethah you can specify algorithm in "defaults" section of loadBalancerConfig.haproxyConfig parameter

**Comment by sangeethah** [comment]
Test with rancher server version - v0.50-rc1

I tried with the following configuration set in LB service:

"haproxyConfig": {
"global": "group haproxy",
"defaults": "balance first",
},

I see the string passed for "global" and "defaults" are appended to the end in "global" and "default" section.

I don't see the "balance first" take effect , when I try to access the LB url, i still see only round robin access.

**Comment by sangeethah** [comment]
Rancher server version - v0.50-rc2 , does not have the fixes yet.

**Comment by sangeethah** [comment]
Tested with Rancher server version - v0.50-rc3.

I tried with the following configuration set in LB service:

"haproxyConfig": {
"global": "group haproxy",
"defaults": "balance first",
},

I see the string passed for "global" and "defaults" are appended to the end in "global" and "default" section.

I see that balancer policy set take effect now.
