### ISSUE TITLE
[rancher-efs failure] Expected state running but got error: Error response from daemon: create nexus-data: VolumeDriver.Create: Failed in create: An error occurred (FileSystemAlreadyExists) when calling the CreateFileSystem operation: None

### ISSUE THREAD

**Issue by gaahrdner** [rancher/rancher#8760]
**Rancher versions:**
rancher/server: 1.5.1
rancher/agent: 1.2.1

**Infrastructure Stack versions:**
healthcheck: 0.2.3
network-services: 0.9.4
scheduler: 0.7.5

**Docker version:**
```
Containers: 12
 Running: 11
 Paused: 0
 Stopped: 1
Images: 13
Server Version: 1.12.6
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 87
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local rancher-efs
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.13.0-92-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 14.94 GiB
Name: 
ID: ULLO:57ZI:BHD5:42YE:M2LE:264C:RBC7:SKXO:Y7RR:5RCI:ZI4Y:ZGL6
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Operating system and kernel:**
3.13.0-92-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher, external DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
1. Create a new storage volume, using `rancher-efs` as the driver.
2. Create a stack.
3. Create a new service in the stack, and configure the service to use the volume created in step, using the rancher-efs.
4. Watch as the service is stuck activating. The EFS volume however is created, which you can verify in the AWS console.

**Results:**
```
Expected state running but got error: Error response from daemon: create nexus-data: VolumeDriver.Create: Failed in create: An error occurred (FileSystemAlreadyExists) when calling the CreateFileSystem operation: None	 
```

The storage driver should create the EFS volume, and then mount it in the container.  Maybe it needs to do an upsert-like operation instead?

**Comment by aemneina** [comment]
@gaahrdner can you share your stack definition? Might help in pinpointing the issue.

**Comment by gaahrdner** [comment]
Sure thing, pretty simple:

```
version: "2"

services:
  nexus:
    image: sonatype/nexus3
    volumes:
      - "nexus-data:/nexus-data"
    ports:
      - "8081:8081"
  
volumes:
  nexus-data: 
    driver: rancher-efs
```

I've also tried adding `external: true` based on this thread, but got the same error. https://forums.rancher.com/t/java-illegalstateexception-more-than-one-volume-exists-for-volume-uri/6216/6

**Comment by StrongMonkey** [comment]
@gaahrdner Do you have a existing EFS with the same name in your region? We use the name as the creation-token to prevent creating EFS with the same name.

**Comment by gaahrdner** [comment]
@StrongMonkey I do not not have existing EFS volumes with the same name.

**Comment by gaahrdner** [comment]
#6713 related?

**Comment by superseb** [comment]
rancher-efs is deprecated per v1.6.6 (https://github.com/rancher/rancher/releases/tag/v1.6.6), alternative is rancher-nfs (http://rancher.com/docs/rancher/v1.6/en/rancher-services/storage-service/rancher-nfs/#using-the-rancher-nfs-driver-on-amazon-efs)
