### ISSUE TITLE
Mapping two host ports to the same container port not working

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#8761]
**Rancher versions:**
rancher/server: 1.5.8 / 1.6.0
scheduler: cattle
Docker 1.12.6

**Steps to Reproduce:**

1. Add a new service using an image that exposes a service on port 80 (tutum/hello-world) and configure it with two port mappings:
80 -> 80
3306 -> 80

**Results:**
1. Service is reported active/healthy
2. Connecting to port 3306 on the hosts succeeds
3. Connecting to port 80 on the host times out
4. Port 3306 seems to be bound to both the primary IP address as well as 0.0.0.0
4. UI shows incorrect port information (duplicate address for port 3306, missing entry for port 80)

![bildschirmfoto 2017-05-12 um 18 24 30](https://cloud.githubusercontent.com/assets/3813921/26007345/6d2a00b2-3740-11e7-8709-998424276efb.png)
![bildschirmfoto 2017-05-12 um 18 24 12](https://cloud.githubusercontent.com/assets/3813921/26007346/6d2ecf5c-3740-11e7-8232-8570e22e11b0.png)

**Comment by vincent99** [comment]
You're showing three different variations of the 2nd port number, but regardless the problem appears to be with mapping the same target port multiple times, regardless of the image or host port.

```
{
  "launchConfig": {
    "ports": [
      "80:80/tcp",
      "81:80/tcp"
    ]
  },
  "publicEndpoints": [
    {
      "type": "publicEndpoint",
      "hostId": "1h1",
      "instanceId": "1i20",
      "ipAddress": "1.2.3.4",
      "port": 81,
      "serviceId": "1s13"
    },
    {
      "type": "publicEndpoint",
      "hostId": "1h1",
      "instanceId": "1i20",
      "ipAddress": "1.2.3.4",
      "port": 81,
      "serviceId": "1s13"
    }
  ]
}
```

**Comment by janeczku** [comment]
@vincent99 fixed port number typo in description

**Comment by GiGurra** [comment]
I can reproduce the same issue. 
Assigned 2 external ports to the same internal port. Only one actual port gets forwarded.

**Comment by GiGurra** [comment]
@vincent99 More alarming, is that rancher seems to think the port is no longer available on the system. Even if I remove the port mapping entirely and deploy (ok), and then just add a single forwarded port, it will fail with error 
```
 Upgrading (Failed to allocate instance [container:1i157]: Bad instance [container:1i157] in state [error]: Allocation failed: No healthy hosts meet the resource constraints: [ports: [12345:80/tcp], ResourceType: instanceReservation, Amount: 1])
Type:
```

**Comment by janeczku** [comment]
Could reproduce @GiGurra's observation. Even after removing the original service the second host port can not be used by any new services.

**Comment by StrongMonkey** [comment]
@GiGurra You can restart your scheduler container as a workaround. There is a bug in how we are scheduling ports and we are addressing it now.

**Comment by StrongMonkey** [comment]
Available at cattle@master

**Comment by soumyalj** [comment]
Tested with v1.6.1-rc8. Created a service with expose ports 3306 and 80 with container port as 80. 


<img width="1233" alt="screen shot 2017-05-31 at 11 15 49 am" src="https://cloud.githubusercontent.com/assets/18536626/26646982/a3dfe89a-45f2-11e7-9477-c33c741a1ef1.png">



Able to access the container successfully on these ports.
