### ISSUE TITLE
Wrong command parsing behaviour

### ISSUE THREAD

**Issue by ketchoop** [rancher/rancher#8763]
**Rancher versions:**
rancher/server: 1.5.5

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

Rancher HA, external DB Galera cluster.

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

Cattle

**What's wrong**:

I have this command:
```
/fabio --proxy.strategy "rr" --ui.color "blue lighten-3" --ui.title "Herzen Gateway" --proxy.addr ":80,:443;proto=https;cs=vault" --proxy.cs "cs=vault;type=vault;cert=secret/fabio/certs" --log.access.target "stdout"
```

And when I want to upgrade my service I get **this thing** in input where is supposed to be command that I set before:

```
/fabio --proxy.strategy rr --ui.color 'blue lighten-3' --ui.title 'Herzen Gateway' --proxy.addr :80,:443;proto=https;cs=vault --proxy.cs cs=vault;type=vault;cert=secret/fabio/certs --log.access.target stdout
```

And of course it breaks container because of args that isn't passed right way.

**N.B:** When I run this first time my container works fine and it happens only if I want to upgrade this.

**Steps to Reproduce:**

Just use this command and **magiconair/fabio** image. After that try to upgrade the container. But I think choice of image doesn't matter. Also, It happens and when I use compose files and when I up the service in UI.

**Comment by loganhz** [comment]
It looks like `launchConfig. command` field in API is not changed when upgrade.
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
