### ISSUE TITLE
External IP from LoadBalancer is not immediately usable

### ISSUE THREAD

**Issue by localghost** [rancher/rancher#8764]
**Rancher versions:**
rancher/server: 1.5.9
rancher/agent: 1.2.2

**Infrastructure Stack versions:**
healthcheck: 0.2.3
ipsec: 0.11.2
network-services: metadata:v0.9.1 / network-manager:v0.6.6
scheduler: k8s:v1.5.4-rancher1-4
kubernetes (if applicable): k8s:v1.5.4-rancher1-4

**Docker version: (`docker version`,`docker info` preferred)**
1.12.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
CentOS 7.3 (3.10.0-327.el7.x86_64)

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
KVM

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
1. Setup Rancher with Kubernetes
2. Run container `arwmar/simple-flask-test` e.g. locally
```
docker run -it --rm arwmar/simple-flask-test
```
3. Copy Kubernetes CLI configuration to `/root/.kube/config` (within the container)
4. Run the test (from with the container)
```
./run.sh http://[IP_ADDRESS]:11111/run
```
`IP_ADDRESS` - IP address of the Rancher host

(If the test hangs please hit _Ctrl-C_ and all the test artifacts - service and deployment - will be cleaned up.)

Exact scenario of the test is as follows (executed by `run.sh` and `test.py` scripts bundled within the docker image):
1. Create deployment from docker image with simple python flask application (`arwmar/simple-flask`).
The application exposes two endpoints `/` and `/run`, the first one responds immediately and the second one sleeps for 10 seconds before sending back a response.
2. Create service matching the deployment with external load balancer (sets `type: LoadBalancer` in the service spec).
3. Wait for pod with the application to be marked as ready
4. Wait for load balancer to assign external IP
This is done by repeatedly checking if response from `kubectl` contains `load_balancer` field in test service status.
5. Execute GET request to the `/run` endpoint
6. Remove service
7. Remove deployment

**Results:**
Expected: I would expect for the endpoint to return 200 after 10 seconds
Actual: Application logs `error: [Errno 32] Broken pipe` and connection to the endpoint hangs on the client-side.

The test passes when its endpoint is exposed via `externalIPs` or if some delay is introduced between establishing that load balancer assigned external IP and the request to the endpoint.
Additionally, if I hit the `/` endpoint - which responds immediately - I get valid response (200).

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
