### ISSUE TITLE
Why is container failing to pull when download is complete?

### ISSUE THREAD

**Issue by bkuhl** [rancher/rancher#8765]
This error fixed itself after retrying a few times.  But I've seen this a few times the past few days and am having trouble making sense of the error message.  How can I debug what the problem is here?

![screen shot 2017-05-15 at 12 58 18 pm](https://cloud.githubusercontent.com/assets/524933/26069276/4de4ecbe-396e-11e7-9214-ce5481321f6e.png)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.5.9` Cattle: `v0.178.12` UI: `v1.5.9` |
|Access|`github` `admin`|
|Orchestration|`Cattle`|
|Route|`admin-tab.processes.index`|

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
