### ISSUE TITLE
Ability to edit an existing catalog

### ISSUE THREAD

**Issue by joshwget** [rancher/rancher#8766]

**Comment by ibuildthecloud** [comment]
@joshwget What happens if you try to edit a global catalog?

**Comment by joshwget** [comment]
Global catalogs still use the config file based method so the new APIs don't apply to them.

**Comment by ibuildthecloud** [comment]
@joshwget What if I use the same name as a global catalog when I create a catalog for myself?  Do you validate or check that?

**Comment by joshwget** [comment]
Looks like we don't even validate that `(environment, catalog name)` is unique. It might make sense to allow using the same name as a global catalog to override it for that environment, though that might get confusing.

**Comment by cjellick** [comment]
IMO, letting an environment scoped catalog override a global one by re-using its name is a bad idea. I think we should make name unique. Though, this raises some challenges when it comes to global catalogs.

**Comment by vincent99** [comment]
+1, `(environment, catalog name)` should be validated unique and if a name is in use for global it shouldn't be allowed for environment.  The race-condition could maybe be lived with for now...

**Comment by cjellick** [comment]
available to test on master

**Comment by tfiduccia** [comment]
Version - master 5/17
Does not work

**Comment by amy** [comment]
This should fix previous issue where you could not save the catalog.
https://github.com/rancher/catalog-service/pull/79

**Comment by cjellick** [comment]
Available on master again (https://github.com/rancher/cattle/commit/83ff43bd2d14d973cc847cae8f92f3634b0642c6)

**Comment by tfiduccia** [comment]
Master 5/18 - Still not fixed
Created new valid entry in Manage Catalogs
Re-entered and changed all four fields (Name, URL, Kind & Branch) & hit Save
Re-entered Manage Catalog

None of the changes I made to the 4 fields saved.

**Comment by tfiduccia** [comment]
Version - master 5/25
Verified fixed
