### ISSUE TITLE
Validation for authentication fields

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#8767]
**Rancher versions:**
rancher/server: 1.5.3

**Steps to Reproduce:**
1. was inputting fields for LDAP authentication, there must have been a copy paste issue where ^@ was appearing in the logs e.g." `Failed to search: (sAMAccountName^@=`

**Results:**
Hoping some simple validation either at the API or UI level could help surface this.

**Comment by vincent99** [comment]
The UI enforces the (lack of) [in]validChars definitions that are set on the config schema.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
