### ISSUE TITLE
Enable arbitrary tags when launching host in EC2 via UI

### ISSUE THREAD

**Issue by oskapt** [rancher/rancher#8768]
**Rancher versions:**
rancher/server: 1.5.9

The Rancher API allows the `amazonec2Config` to contain a `tags` field in the form of `key1,value1,key2,value2`. These tags are then set on the instance when it is deployed.

When using the UI to launch a host there is no option for setting this field. As a result, only the `Name` tag is set.

I would like to request that a `Tags` field be added to the machine driver for EC2 and used to set tags on the deployed instance.

**Comment by aemneina** [comment]
looks like those can be passed through to the docker-machine ec2 driver param:

```--amazonec2-tags: AWS extra tag key-value pairs (comma-separated, e.g. key1,value1,key2,value2).```

**Comment by vincent99** [comment]
That is a horrifying input format, with no provision for escaping/including a literal comma.. so the UI should use `form-key-value` and add validation to prevent any key or value from containing a comma.

**Comment by deniseschannon** [comment]
Available in v1.6.8-rc5

**Comment by tfiduccia** [comment]
Version - 1.6.8-rc5
Verified added.
