### ISSUE TITLE
LDAP/AD: NPE encountered if userAccountControl attribute value not found in LDAP search result

### ISSUE THREAD

**Issue by prachidamle** [rancher/rancher#8769]
**Rancher versions:**
rancher/server: 1.5.x
rancher/cattle tag: v0.177.10

**Steps to Reproduce:**
If the "Status" field in the ldap/ad config UI is set to something like "userAccountControl" and suppose that attribute is not found in the attributes returned back by the LDAP search, we see an NPE logged in the cattle logs.

https://github.com/rancher/cattle/blob/v0.177.10/code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/LDAPIdentityProvider.java#L269

**Expected:**
We should be able to avoid hitting this NPE and error gracefully instead

**Comment by lehn-etracker** [comment]
When you do an _ldapsearch_ you can see, **userAccountControl** is usually not reported. MS uses this only within filters, so Rancher should never suppose to get a value for it.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
