### ISSUE TITLE
Support for showing IP other than agent IP for port-mapping information 

### ISSUE THREAD

**Issue by wjimenez5271** [rancher/rancher#8770]
Rancher computes port-mapping information for services currently based on the IP that the agent is bound to, some users have requested the ability to use the IP address of another interface on the host, such as the interface for an internal management network that they access services in Rancher over. This is only an issue when the network they want to access services on is not the same network they want agents to bind to.

**Comment by vincent99** [comment]
The default is `0.0.0.0`; if you want to bind to something specific you can and it will be reflected.

**Comment by wjimenez5271** [comment]
When i look at the UI, I see actual interface addresses however, and I haven't specified anything 
(see screenshot)
<img width="736" alt="screen shot 2017-05-15 at 6 26 02 pm" src="https://cloud.githubusercontent.com/assets/322834/26082106/0ac00878-399c-11e7-9cbc-96bf7c250ec1.png">

**Comment by vincent99** [comment]
Showing 0.0.0.0 is not very helpful/clickable, so the agent IP is shown in the UI.  But that doesn't mean it's listening *only* on that IP.  And if you add additional IPs to a host and request a specific IP, it will show there instead.  FWIW, 2.0 shows both, i.e. `0.0.0.0 (192.168.64.7)`.

![image](https://cloud.githubusercontent.com/assets/753917/26082927/5b71ea4e-3987-11e7-883d-9d649079cf82.png)

![image](https://cloud.githubusercontent.com/assets/753917/26082842/dad81b10-3986-11e7-9c05-802f0ce48644.png)

![image](https://cloud.githubusercontent.com/assets/753917/26082916/4a1492d8-3987-11e7-8dd0-6e9687dce0af.png)


![image](https://cloud.githubusercontent.com/assets/753917/26082902/3f7c06d0-3987-11e7-9302-afc097771f8c.png)

**Comment by wjimenez5271** [comment]
Yea I understand it is actually listening on all interfaces, the issue is the customer has a lot of internal users who don't understand that fact and so they expect to be able to click the link in the UI and be taken to the correct URL.

**Comment by vincent99** [comment]
What is the mechanism by which you would like it to divine the correct URL?

**Comment by wjimenez5271** [comment]
I don't have a preference. If your looking for ideas I could imagine a label on a host being a nice way to specify the "presentation" IP address for the host.

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
