### ISSUE TITLE
[cli] Add docker to rancher/cli docker image

### ISSUE THREAD

**Issue by elfrinjo** [rancher/rancher#8771]
**Rancher versions:**
rancher/cli: 0.6.0

**Steps to Reproduce:**
```
$ docker run -it --rm \
-e RANCHER_URL=${myHost} \
-e RANCHER_ACCESS_KEY=${myKey} \
-e RANCHER_SECRET_KEY=${mySecret} \
-e RANCHER_ENVIRONMENT=${myEnv} \
rancher/cli exec ${myContainer} exec  uname
FATA[0000] exec: "docker": executable file not found in $PATH 
```
**Reason**
The dockerimage for rancher/cli is currently built from alpine with rancher and ssh added.
"rancher exec" relies on "docker exec" inside it's container

**Possible resolution**
Add docker packages to rancher's cli image

**Comment by sergey-koba-mobidev** [comment]
I've created an image, where I installed docker and rancher clie-s https://hub.docker.com/r/skoba/rancher-cli/
I will update it with Dockerfile and readme soon.
`rancher exec` works

**Comment by iBobik** [comment]
@aemneina Why label question? It seems more like a bug - `rancher exec` does not work in official Docker image.

**Comment by iBobik** [comment]
Solved here: https://github.com/rancher/cli/pull/111

**Comment by geertvanheusden** [comment]
@sergey-koba-mobidev, would you be willing to share your Dockerfile for *skoba/rancher-cli*?

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
