### ISSUE TITLE
Deactivating all environments removes the environment dropdown

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#8775]
**Rancher versions:**
rancher/server: v1.6.1-rc4
**Steps to Reproduce:**
deactivated all environments in my deployment. eventually i get to a screen that only has the admin drop down. 

**Results:**
No environment tab to create new environment.

**Comment by vincent99** [comment]
It is supposed to be gone, but you're also supposed to be redirected to the manage env page.  I suppose you were, then because you're an admin you went off somewhere into admin pages and can't get back?
