### ISSUE TITLE
Immutable Catalog Questions

### ISSUE THREAD

**Issue by LLParse** [rancher/rancher#8779]
Today, any catalog question may be answered at two different times: 

* before first launch
* before an upgrade

The implicit requirement is that any question must be modifiable. Consider selecting a persistent storage backend. While technically possible to migrate the data from one storage type to another during an upgrade, this might take extraordinary effort with little payoff.

Sometimes we want to answer the question before first launch but disallow modification during upgrade. This allows us to focus our efforts on the valuable upgrade paths instead of supporting all of them implicitly.

**Proposal**
Add a `modifiable` or `upgradable` boolean to the catalog question schema. Default is true (current behavior). If set to false, a user will not be able to modify the value during upgrade. 

Ideally, the unmodifiable fields are still displayed but disabled. If it's easier, don't display the fields at all. API validation of immutable fields is probably overkill.

**Suggested Impl**
catalog-service: Add the new field and ensure it is exposed in relevant API calls
ui: Disable fields on upgrade screen based on field

**Comment by vincent99** [comment]
The matching schema field would `update` (and `create` for the opposite, settable on first create).
