### ISSUE TITLE
Catalog Stack fails to deploy if rancher-compose healthcheck service doesnt exist in docker-compose

### ISSUE THREAD

**Issue by gregkeys** [rancher/rancher#8781]
**Rancher versions:**
rancher/server: 1.6.0
rancher/agent: 1.2.2

**Infrastructure Stack versions:**
healthcheck: 0.3.1
ipsec: 0.11.2
network-services: 0.7.0
scheduler: 0.7.5
kubernetes (if applicable): n/a

**Docker version: (`docker version`,`docker info` preferred)** 
v1.12.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
RancherOS v0.8.1 (4.9.12)

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node w external DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**

docker-compose.yml
```sh
services:
  some_service_1:
      image: service:v1.1

{{- if eq .Values.service_2 "true" }}
  some_service_2:
      image: other_service:v1.2
{{- end }}
```

rancher-compose.yml
```sh
version: '2'

.catalog:
  name: stack-configurator
  version: 0.0.2
  description: Configure the services to deploy to the stack
  minimum_rancher_version: v1.5.1
  questions:
    - variable: service_2 
      description: "add service 2"
      label: Add Service 2
      default: false
      type: boolean

services:
  some_service_1:
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 8080
      unhealthy_threshold: 3
      initializing_timeout: 120000
      interval: 2000
      strategy: recreate
      request_line: GET "/" "HTTP/1.0"
      reinitializing_timeout: 60000

  some_service_2:
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 80
      unhealthy_threshold: 3
      initializing_timeout: 120000
      interval: 2000
      strategy: recreate
      request_line: GET "/" "HTTP/1.0"
      reinitializing_timeout: 60000
```

**Results:**
`code=InvalidOption, fieldName=Image is required when selectorContainer is not passed in, baseType=error`

**Comment by deniseschannon** [comment]
You can move the healthcheck section from rancher-compose.yml into docker-compose.yml to get this to work. This functionality only works in Rancher 1.6+.

**Comment by gregkeys** [comment]
Excellent, this did exactly what we needed it to do. Thank you

**Comment by deniseschannon** [comment]
@gregkeys Great! i'll close the issue/
