### ISSUE TITLE
Limit logging in Rancher Server

### ISSUE THREAD

**Issue by huggla** [rancher/rancher#8782]
**Rancher versions:**
rancher/server: 1.6.0

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
RancherOS v.1.0.0

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal, rancheros.iso with cloud-config

When a container is left in unhealthy state for a longer time, the log files in /var/lib/docker/volumes grows huge. That is a problem, especially when running Rancher Server on a diskless host. We need a way to limit the size of the debug logs. Several temporary log files are created but never(?) removed. Also, when looking at the log files, you find a lot of redundant text strings which could be replaced by lookup keys. Is it really necessary to have the same error message repeated indefinitely in the logs, for example when a container fails to start?

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
