### ISSUE TITLE
[UI] Suggestion: Open K8Ns Dashboard immediately, skip page with single button

### ISSUE THREAD

**Issue by davidhiendl** [rancher/rancher#8784]
**Rancher versions: rancher/server: 1.6**
**Environment Template: Kubernetes**

**Suggestion:**
Open Kubernetes dashboard immediately after clicking on the the "Kubernetes > Dashboard" entry in the navigation and skip the confirmation page with a single button.

**Description:**
The K8Ns dashboard is currently available by clicking the "Dashboard" entry in the main navigation. After clicking it you have to click on a second button "Kubernetes UI" to open the dashboard. This is kind of annoying since there is no other action on that page. I think it would be much more convenient if the dashboard would open imminently in a new Tab.

**Comment by vincent99** [comment]
n/a to 2.0.
