### ISSUE TITLE
only one host added, at a time, previous host(S) and containers destroyed 

### ISSUE THREAD

**Issue by korenlev** [rancher/rancher#8785]
*Describe your issue here*

to recreate - just installed rancher/server:stable , 
all hosts-to-rancher server are on same private network and dns/ip reachable etc.
add host,
copy-paste to command on some 1st docker linux machine- registered ok, can create containers.
add another host, 
copy-paste to command on some 2nd docker linux machine - rancher destroys 1st, add 2nd , killing all containers on 1st.
 

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.5.9` Cattle: `v0.178.12` UI: `v1.5.9` |
|Access|`github` `admin`|
|Orchestration|`Cattle`|
|Route|`authenticated.project.help`|

**Comment by korenlev** [comment]
17.03.x-ce on all hosts

**Comment by superseb** [comment]
Hi @korenlev, would be great if you could update your issue using the issue template (hit New Issue and copy/paste or look here https://github.com/rancher/rancher/blob/master/.github/ISSUE_TEMPLATE.md)

**Comment by korenlev** [comment]
the details on the template:

Rancher versions: rancher/server: :v1.5.10 rancher/agent: v1.2.2

Infrastructure Stack versions: healthcheck: ipsec: network-services: scheduler: kubernetes (if applicable):not relevant

Docker version:
17.03.0-ce:
Containers: 6
 Running: 6
 Paused: 0
 Stopped: 0
Images: 6
Server Version: 17.03.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 136
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-21-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 15.67 GiB
Name:xxremovedxx
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: http://removed
Username: korenlev
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

Operating system and kernel: (cat /etc/os-release, uname -r preferred):
kernel: 4.4.0-21-generic
NAME="Ubuntu"
VERSION="16.04 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
UBUNTU_CODENAME=xenial


Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)" any ubuntu linux host

Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB): single node rancher , multiple hosts

Environment Template: (Cattle/Kubernetes/Swarm/Mesos): Cattle

Steps to Reproduce:
install rancher/server:stable ,
all hosts-to-rancher server are on same private network and dns/ip reachable directly 1to1.
add a host,
copy-paste bash line to command on some 1st docker linux machine- registered ok, can create containers.
add another host,
copy-paste bash line to command on some 2nd docker linux machine - 
Results:
rancher destroys 1st, adding 2nd , killing all containers on 1st.

**Comment by vincent99** [comment]
Are the hosts created from the same custom OS image or cloned from each other?  This sounds like the same uuid in `/var/lib/rancher/state` has been copied to all hosts.  So when one connects it is the "same" host and is now running no containers, so they're removed.

**Comment by korenlev** [comment]
Agree. Sound like the case. Its indeed a clone fir all hosts but ofcourse different hostname dns mac-address and ip address etc. So rancher dont care about all those different ids but solaly on one thing? Where is this uuid? is it in docker-machine setup files?Koren


Sent from my Samsung device

-------- Original message --------

**Comment by vincent99** [comment]
None of those are reliably different on different hosts, or necessarily the same when something changes on the same host.  We just generate a UUID for each host if one doesn't already exist.  Either create the image before the machine has been added as a host, or remove its identity by`rm -rf /var/lib/rancher/state` before imaging.

**Comment by korenlev** [comment]
Vincent, so the uuid is randomly generated at agent image creation?


Sent from my Samsung device

-------- Original message --------

**Comment by korenlev** [comment]
All hosts where cloned with docker pre installed and before installing rancher So we wonder when uuid is generated and how?


Sent from my Samsung device

-------- Original message --------
From: korenlev <korenlev@gmail.com> 
Date: 5/24/17  13:29  (GMT+02:00) 
To: rancher/rancher <reply@reply.github.com>, rancher/rancher <rancher@noreply.github.com> 
Cc: Mention <mention@noreply.github.com> 
Subject: Re: [rancher/rancher] only one host added, at a time, previous
  host(S) and containers destroyed (#8785) 


    
Vincent, so the uuid is randomly generated at agent image creation?


Sent from my Samsung device

-------- Original message --------

**Comment by vincent99** [comment]
It's not in the docker image, it is read or generated when the agent container is run.

What you have described does not fit with you saying the machine is imaged "before installing rancher".

**Comment by korenlev** [comment]
So this is something else then. Not able to re create on your side? Which logs do you need?Koren


Sent from my Samsung device

-------- Original message --------

**Comment by vincent99** [comment]
The uuid *is* the host's identity.  Nothing else explains the behavior you describe.

Have you actually looked at a deployed machine and seen that there's no `/var/lib/rancher/state` in it?  Or possibly a `rancher-agent-state` docker volume, but I'm pretty sure it's only stored in there if `/var/lib` is not writable.

**Comment by superseb** [comment]
@korenlev Do you need any more help with this?

**Comment by superseb** [comment]
Please comment if you still need help with this.
