### ISSUE TITLE
No healthy hosts meet the resource constraints

### ISSUE THREAD

**Issue by rktechworld** [rancher/rancher#8786]
**Rancher versions:**
rancher/server: v1.6.0
rancher/agent: v1.2.2

Docker Version:
1.12.3
OS and where are the hosts located? (cloud, bare metal, etc):
Ubunt 16.o4

Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)
Single node rancher
Environment Type: (Cattle/Kubernetes/Swarm/Mesos)
Cattle
Steps to Reproduce:

Run Rancher server v1.6.0
Register few agents
Create a container with mapped port

Results:
container failed to start
Failed to allocate instance [container:1i407]: Bad instance [container:1i407] in state [error]: Allocation failed: No healthy hosts meet the resource constraints: [ports: [8302:8888/tcp], ResourceType: instanceReservation, Amount: 1]

**Comment by vmozgovoy** [comment]
Same problem

**Comment by neanex** [comment]
same problem

**Comment by aemneina** [comment]
@rktechworld looks like you already have a service bound to port 8302. That's preventing your new service from coming up. Can you confirm that's the case?

**Comment by niklashim** [comment]
Had a similar issue with the Mongodb catalog item, for some reason it bound to my external IP and since i only had 2 hosts and 3 replica members. After i removed the service link with a upgrade it worked :)

**Comment by flantel** [comment]
I have this same issue on Rancher 1.5.9 host docker 17.03.2-ce on Ubuntu Trusty.

Trying to run a load balancer:

**Allocation failed: No healthy hosts meet the resource constraints: [ports: [443:443/tcp]**

There is nothing running on port 443.

**Comment by danielschlegel** [comment]
i have same problem with 

kubernetes-rancher-kubernetes-agent

Allocation failed: No healthy hosts meet the resource constraints

**Comment by danielschlegel** [comment]
for me the solution was to restart rancher.

**Comment by superseb** [comment]
The original reported issue sounds like there is not a host available with the requested port (either claimed or scale is bigger than amount of hosts available). If you are certain that the host is available, you can check `View in API` on that host (Infrastructure -> Hosts) and check `publicEndpoints` to see whats being used by what.

Please file a new issue so we can track it down if this is a real bug.

**Comment by nelsonomuto** [comment]
@superseb you are right, the port was already in use as was evident in the `View in API` ui, I was able to stop the process listening on this port on my host and then as @danielschlegel points out, I restarted rancher (by restarting the docker service fixed my issue `service docker restart` on my rancher host)

This fixed my issue

**Comment by Gloix** [comment]
I'm having this problem as well. I have two healthy hosts and a service with scale of 2, but only scales to one host before failing with the "(Failed to allocate instance [container:1i392]: Bad instance [container:1i392] in state [stopping]: Allocation failed: No healthy hosts meet the resource constraints: [5002:80/tcp portReservation, instanceReservation: 1].)" error.

I checked the second host through View in API and port 5002 is not taken.
