### ISSUE TITLE
Automatically register stack services with global loadbalancer

### ISSUE THREAD

**Issue by gregkeys** [rancher/rancher#8793]
**Rancher versions:**
rancher/server: 1.6.0
rancher/agent: 1.2.2

**Infrastructure Stack versions:**
healthcheck: 0.3.1
ipsec: 0.11.2
network-services: 0.7.0
scheduler: 0.7.5
kubernetes (if applicable): na

**Docker version: (`docker version`,`docker info` preferred)**
v1.12.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
RancherOS v0.8.1 (4.9.12)

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node w external DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Requested Feature**
I would like to be able to add a label or environment variable to a service in our docker-compose.yml that would allow a loadbalancer in another stack to see it and register the service to a path

for example in a docker-compose.yml
```sh
services:
  websocket_service:
    image: some_ws_service_image:v1234
    labels:
      io.rancher.loadbalancer.target.websocket_service: ${CLIENT_DOMAIN}:443/ws=8080
```
I realize that this label is intended for the loadbalancer, it would be nice if the loadbalancer would scan all stacks for this label or one similar to it and use it to add endpoints, this would allow stacks to automatically wire themselves up to a global loadbalancer.

Currently we have to manually add endpoints to our loadbalancer whenever we add a new stack

**Comment by vincent99** [comment]
http://docs.rancher.com/rancher/v1.6/en/cattle/adding-load-balancers/#selector

**Comment by gregkeys** [comment]
@vincent That does not accomplish what I'm requesting because it assumes that you know what services, hostnames and ports you want to Target at the time you setup the loadbalancer.

I'm requesting the ability to dynamically register those things on the fly without knowledge of them ahead of time.

For instance as we acquire new customers we use a catalog which sets up the hostname, paths, defined and ports which the load balancer find and adds.

Similar to how the route 53 service looks for labels and adds stacks to route 53

**Comment by gregkeys** [comment]
@vincent99 correction I didn't see that you can add the lb_config to the service
