### ISSUE TITLE
Unable to set access control with rancher-server behind Nginx as https reverse proxy.

### ISSUE THREAD

**Issue by up9cloud** [rancher/rancher#8794]
**Rancher versions:**
rancher/server: latest

$ docker exec rancher-server env          
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=5f4291676d58
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_ALL=en_US.UTF-8
DEBIAN_FRONTEND=noninteractive
CATTLE_HOME=/var/lib/cattle
DEFAULT_CATTLE_API_UI_INDEX=//releases.rancher.com/ui/1.6.1
CATTLE_API_UI_URL=//releases.rancher.com/api-ui/1.0.8
CATTLE_DB_CATTLE_DATABASE=mysql
CATTLE_USE_LOCAL_ARTIFACTS=true
no_proxy=localhost,127.0.0.1,localaddress,.localdomain.com
S6_SERVICE_DIR=/service
CATTLE_HOST_API_PROXY_MODE=embedded
CATTLE_RANCHER_SERVER_VERSION=v1.6.0
CATTLE_RANCHER_COMPOSE_VERSION=v0.12.5
DEFAULT_CATTLE_RANCHER_COMPOSE_LINUX_URL=https://releases.rancher.com/compose/v0.12.5/rancher-compose-linux-amd64-v0.12.5.tar.gz
DEFAULT_CATTLE_RANCHER_COMPOSE_DARWIN_URL=https://releases.rancher.com/compose/v0.12.5/rancher-compose-darwin-amd64-v0.12.5.tar.gz
DEFAULT_CATTLE_RANCHER_COMPOSE_WINDOWS_URL=https://releases.rancher.com/compose/v0.12.5/rancher-compose-windows-386-v0.12.5.zip
CATTLE_RANCHER_CLI_VERSION=v0.6.0
DEFAULT_CATTLE_RANCHER_CLI_LINUX_URL=https://releases.rancher.com/cli/v0.6.0/rancher-linux-amd64-v0.6.0.tar.gz
DEFAULT_CATTLE_RANCHER_CLI_DARWIN_URL=https://releases.rancher.com/cli/v0.6.0/rancher-darwin-amd64-v0.6.0.tar.gz
DEFAULT_CATTLE_RANCHER_CLI_WINDOWS_URL=https://releases.rancher.com/cli/v0.6.0/rancher-windows-386-v0.6.0.zip
DEFAULT_CATTLE_CATALOG_URL={"catalogs":{"community":{"url":"https://git.rancher.io/community-catalog.git","branch":"master"},"library":{"url":"https://git.rancher.io/rancher-catalog.git","branch":"master"}}}
CATTLE_CATTLE_VERSION=v0.179.7
DEFAULT_CATTLE_API_UI_JS_URL=/api-ui/ui.min.js
DEFAULT_CATTLE_API_UI_CSS_URL=/api-ui/ui.min.css
DEFAULT_CATTLE_MACHINE_EXECUTE=true
DEFAULT_CATTLE_COMPOSE_EXECUTOR_EXECUTE=true
DEFAULT_CATTLE_CATALOG_EXECUTE=true
DEFAULT_CATTLE_AUTH_SERVICE_EXECUTE=true
DEFAULT_CATTLE_WEBHOOK_SERVICE_EXECUTE=true
DEFAULT_CATTLE_SECRETS_API_EXECUTE=true
CATTLE_RANCHER_SERVER_IMAGE=rancher/server
HOME=/root

rancher/agent:

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**

$ docker version
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Wed Jan 11 00:23:16 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Wed Jan 11 00:23:16 2017
 OS/Arch:      linux/amd64

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

$ uname -r
4.9.12-rancher

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

aws

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

single node rancher, external DB
nginx:
$ docker exec nginx nginx -v
nginx version: nginx/1.13.0

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

Cattle

**Steps to Reproduce:**

- create a rds and a ec2 on aws
- up rancher-server and nginx container (follow https://docs.rancher.com/rancher/v1.6/en/installing-rancher/installing-server/basic-ssl-config/#example-nginx-configuration or #1151)
- browse the domain
- click nav ADMIN button -> click dropdown menu "access control"

**Results:**
![screen shot 2017-05-18 at 10 12 20](https://cloud.githubusercontent.com/assets/8325632/26183704/0d8a398e-3bb3-11e7-8cfa-ea32729cb4dc.png)

![screen shot 2017-05-18 at 10 12 06](https://cloud.githubusercontent.com/assets/8325632/26183712/19ad49cc-3bb3-11e7-9811-8a06d9eb9476.png)

**Comment by superseb** [comment]
Can't reproduce, can you show your `nginx.conf` and the commands you ran to start it up?

**Comment by up9cloud** [comment]
Hi,

- `nginx.conf`

```
# docker nginx default
user  nginx;

# cpu core * 2
worker_processes 2;

# worker_connections * 1 < worker_rlimit_nofile <= worker_connections * 2
worker_rlimit_nofile 65535;

# docker nginx default
error_log  /var/log/nginx/error.log warn;

# docker nginx default
pid        /var/run/nginx.pid;

events {
    # max connections (65535?) / worker_processes
    worker_connections 20480;
    multi_accept on;
    use epoll;
}

http {
    # let $ sign can be use.
    geo $dollar {
        default "$";
    }

    # docker nginx default
    include       /etc/nginx/mime.types;

    # docker nginx default
    default_type  application/octet-stream;

    # docker nginx default
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    # docker nginx default
    access_log /var/log/nginx/access.log main;

    # docker nginx default
    sendfile           on;

    # docker nginx default
    keepalive_timeout  65;

    # security reason
    server_tokens      off;
    charset            utf-8;

    ssl_prefer_server_ciphers   on;
    ssl_stapling                on;
    ssl_stapling_verify         on;
    ssl_session_cache           shared:SSL:10m;
    add_header Strict-Transport-Security "max-age=15768000; includeSubDomains" always;

    client_max_body_size        10m;
    client_body_buffer_size     16k;
    #client_body_temp_path       /usr/local/nginx/cache/body;

    # gzip
    gzip                on;
    gzip_comp_level     6;
    gzip_min_length     1k;
    gzip_buffers        4 16k;
    gzip_vary           on;
    gzip_proxied        any;
    gzip_types          *;
    #gzip_disable        "msie6";

    # proxy
    proxy_set_header            Host $host;
    proxy_set_header            X-Real-IP $remote_addr;
    proxy_set_header            X-Forwarded-Proto $scheme;
    proxy_set_header            X-Forwarded-Port $server_port;
    proxy_set_header            X-Forwarded-For $proxy_add_x_forwarded_for;

    proxy_buffers               4 32k;
    proxy_buffer_size           16k;
    proxy_busy_buffers_size     32k;

    # http://www.aichengxu.com/diannao/24099.htm
    proxy_max_temp_file_size 0;
    proxy_buffering off;
    #proxy_temp_file_write_size  64k;
    #proxy_temp_path             /usr/local/nginx/cache/tmp;
    proxy_store off;

    # docker nginx default
    # include /etc/nginx/conf.d/80.conf;
    include /etc/nginx/conf.d/*.conf;
}
```

- `conf.d/rancher.conf`

```
upstream rancher {
	server rancher-server:8080;
}
server {
	listen      443 ssl http2;
	listen [::]:443 ssl http2;
	server_name <secret>;

	ssl_certificate         /etc/ssl/live/<secret>/fullchain.pem;
	ssl_certificate_key     /etc/ssl/live/<secret>/privkey.pem;
	ssl_trusted_certificate /etc/ssl/live/<secret>/chain.pem;

	access_log /var/log/nginx/<secret>/access.log main;
	error_log  /var/log/nginx/<secret>/error.log warn;

	# https://docs.rancher.com/rancher/v1.6/en/installing-rancher/installing-server/basic-ssl-config/#example-nginx-configuration
	# https://github.com/rancher/rancher/issues/1151
	location / {
		proxy_pass http://rancher;

		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "Upgrade";
		# This allows the ability for the execute shell window to remain open for up to 15 minutes. Without this #parameter, the default is 1 minute and will automatically close.
		proxy_read_timeout 900s;
	}
}
```

- up rancher

```sh
NAME=rancher-server

docker run \
-d \
--name ${NAME} \
--restart=unless-stopped \
--memory="1g" \
--memory-swappiness=0 \
rancher/server \
--db-host ${DB_HOST_rancher_cattle} \
--db-port ${DB_PORT_rancher_cattle} \
--db-user ${DB_USER_rancher_cattle} \
--db-pass ${DB_PASS_rancher_cattle} \
--db-name cattle
```

- up nginx

```sh
#!/bin/bash

NAME=nginx

docker run \
-d \
--name ${NAME} \
--restart=always \
--memory="128m" \
--memory-swappiness=0 \
-p 80:80 \
-p 443:443 \
-v /data/data/${NAME}/html:/usr/share/nginx/html \
-v /data/data/letsencrypt:/etc/ssl \
-v /data/deploy/${NAME}/nginx.conf:/etc/nginx/nginx.conf \
-v /data/deploy/${NAME}/conf.d:/etc/nginx/conf.d \
-v /data/log/${NAME}:/var/log/nginx \
--link rancher-server \
nginx:1-alpine
```

**Comment by superseb** [comment]
I don't think I was able to reproduce this, if you are still experiencing issues, let me know and we can investigate further.
