### ISSUE TITLE
healthcheck status different in API and web gui

### ISSUE THREAD

**Issue by nheinemans** [rancher/rancher#8796]
**Rancher versions:**
rancher/server: 1.5.9
rancher/agent: 1.2.2

**Infrastructure Stack versions:**
healthcheck: 0.3.1
ipsec: 0.11.2
network-services: 0.6.6
scheduler: 0.7.5

**Docker version: (`docker version`,`docker info` preferred)**
17.03.1-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
rancheros 1.0.1

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VMware and Openstack

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher, external DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Not found yet

I'm looking into the following issue. Our monitoring reports one of the rancher instances on a host is not healthy. Monitoring is performed using sensu in a container, which uses the metadata to gather info. In the web gui, everything looks fine. However, in the API, I see this for the healthcheck service:

"healthcheckStates": [ 3 items
{
"hostId": "1h7440",
"healthState": "healthy"
},
{
"hostId": "1h7443",
"healthState": "healthy"
},
{
"hostId": "1h7446",
"healthState": "initializing"
}
] 

After restarting the service, all containers are healthy again. We currently have 2 hosts which show this issue, so I can perform some additional tests if necessary.

**Comment by superseb** [comment]
Difference UI vs API is explained in https://github.com/rancher/rancher/issues/8632.

If you keep having issues with initializing/unhealthy checks, you can check the haproxy.cfg in the healthcheck container and debug where it's failing. Also check network/metadata containers as there might be going in there.
