### ISSUE TITLE
The client feign death

### ISSUE THREAD

**Issue by mariadb-Emrys** [rancher/rancher#8797]
**Rancher versions:**
rancher/server: v1.14
rancher/agent: v1.0.2

1、Add the container through the rancher server （10.228.2.14）
Error (Scheduling failed: No candidates available)

2、The physical state of machine（10.228.2.14）
![1](https://cloud.githubusercontent.com/assets/4919916/26195398/42accb0a-3bee-11e7-9e2d-70f69a285779.jpg)

3、stop docker （10.228.2.14）
Active is still displayed on the rancher server

![1](https://cloud.githubusercontent.com/assets/4919916/26195398/42accb0a-3bee-11e7-9e2d-70f69a285779.jpg)

4、restart docker （10.228.2.14）
Add  container  ：Error (Scheduling failed: No candidates available)

**Comment by superseb** [comment]
Thanks for reporting @mariadb-Emrys , is it correct you are running v1.1.4? There have been many releases and improvements, could you try on a newer release?

**Comment by mariadb-Emrys** [comment]
{"log":"2017-05-19 01:52:40,219 ERROR [e7253fe9-f3fc-4f47-9738-cee5fbaae2be:1498596] [instance:9060] [instance.start-\u003e(InstanceStart)] [] [orService-12596] [i.c.p.process.instance.InstanceStart] Failed to Scheduling for instance [9060] \n","stream":"stdout","time":"2017-05-19T01:52:40.22069707Z"}

**Comment by mariadb-Emrys** [comment]
@superseb  How to restore

**Comment by superseb** [comment]
@mariadb-Emrys You can look in this issue to recover: https://github.com/rancher/rancher/issues/5873.

As stated, there is a fix in later releases for this situation. My advice is to upgrade as soon as possible to prevent this.

**Comment by mariadb-Emrys** [comment]
@superseb  thx
