### ISSUE TITLE
Using host templates to store provider keys, adding hosts with them

### ISSUE THREAD

**Issue by imikushin** [rancher/rancher#8803]
We are going to use hostTemplates for storing/using sensitive parts of hosts’ configs (like access key).

While it is possible to store more than just credentials in the host template, the user experience in caas will be to just put the sensitive fields in the host template.

We need to make sure the API to manage (CRUD) host templates works and hosts can be created with host templates (then used, then deleted).

Additionally, it would be nice if the API validated that the selected hostTemplate had a driver field that matches the config that was set on the host:

- hostTemplate has `driver` string field that will have a value like "digitalocean"
- host has fields like `digitaloceanConfig`

Impl note: the validation can be done in the class MachineValidationFilter

Deliverables: test plan, validation tests, (possibly) bug fixes

**Comment by soumyalj** [comment]
Note: We need to ensure that host template names are unique

**Comment by soumyalj** [comment]
https://github.com/rancher/rancher/issues/8807

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
