### ISSUE TITLE
Compose question/answer improvements

### ISSUE THREAD

**Issue by joshwget** [rancher/rancher#8804]
- [ ] Refactor `lookup` package. It was a useful interface when variables were lazily evaluated, but templating requires all values to be given as a map up front. A simple map will probably suffice for variables everywhere now. The important part is precedence when merging the various sources.
- [ ] Questions should only be asked if they aren't already specified as an environment variable or in an answers file. I think this is equivalent to #8798, but not sure.
- [ ] Empty variables should still be populated when using templating. Currently empty variables won't even be available as a variable when using templating.
- [ ] Validate UX by testing with Kubernetes template. This has a mix of multiple question types, interpolation, and templating. If there are any remaining quirks they'll probably get caught by trying this out.

**Comment by cjellick** [comment]
From : https://github.com/rancher/rancher/issues/8798
> Just noticed other problem with Rancher CLI v0.6.0. It keeps on expecting a value, even if is not required (set to false). The only workaround, for now, is to remove all questions.

Seems like an important thing to address in the CLI

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
