### ISSUE TITLE
Mispelled github URL (https://gihtub.com) causes Manage Catalog modal to hang

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#8806]
**Rancher versions:** master 5/18

**Steps to Reproduce:**
1.  Go to Catalog page
2.  Click on Manage button
3.  Enter a catalog bug make the url: `https://gihtub.com`
4.  Save

**Results:**  The Save button starts spinning and never stops.  This should save the url and just continue.

**Comment by amy** [comment]
Unable to reproduce

**Comment by tfiduccia** [comment]
@amy 
Try https://gihtub/tfiduccia/qa-catalog

**Comment by amy** [comment]
^ *https://gihtub.com/tfiduccia/qa-catalog

**Comment by amy** [comment]
We will implement a `catalog.pull.timeout` setting to address the case of a invalid URL timing out.
