### ISSUE TITLE
Validate host template creation and addition of hosts using them

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#8807]
Test Plan for host template creation and addition of hosts attached:

[Host Templates and addition of hosts.xlsx](https://github.com/rancher/rancher/files/1015081/Host.Templates.and.addition.of.hosts.xlsx)

**Comment by imikushin** [comment]
LGTM

**Comment by imikushin** [comment]
I believe I implemented all of the "Automate" scenarios in rancher/validation-tests#319
