### ISSUE TITLE
lb_config does not work in docker-compose.yml with global loadbalancer

### ISSUE THREAD

**Issue by gregkeys** [rancher/rancher#8811]
**Rancher versions:**
rancher/server: 1.6.0
rancher/agent: 1.2.2

**Infrastructure Stack versions:**
healthcheck: 0.3.1
ipsec: 0.11.2
network-services: 0.7.0
scheduler: 0.7.5
kubernetes (if applicable): na

**Docker version: (`docker version`,`docker info` preferred)**
v1.12.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
RancherOS v0.8.1 (4.9.12)

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node w external DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
docker-compose.yml
```sh
version: '2'
services:
  websocket:
    image: websocket_image:latest
    labels:
      io.rancher.container.pull_image: always
      loadbalancer.backend: true
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 8080
      unhealthy_threshold: 3
      initializing_timeout: 120000
      interval: 2000
      strategy: recreate
      request_line: GET "/" "HTTP/1.0"
      reinitializing_timeout: 60000
    lb_config:
      port_rules:
      - target_port: 8080
        hostname: ${CLIENT_DOMAIN}/ws

  webapp:
    image: demo-webapp:latest
    labels:
      io.rancher.service.external_dns: always
      io.rancher.container.pull_image: always
      loadbalancer.frontend: true
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 80
      unhealthy_threshold: 3
      initializing_timeout: 120000
      interval: 2000
      strategy: recreate
      request_line: GET "/" "HTTP/1.0"
      reinitializing_timeout: 60000
    lb_config:
      port_rules:
      - target_port: 80
        hostname: ${CLIENT_DOMAIN}
```
NOTE!! we can not put lb_config into the rancher-compose.yml service description because we have conditional services that if they are not selected with the configuration causes rancher to throw an error when deploying the stack.

rancher-compose.yml from separate loadbalancer stack
```sh
version: '2'
services:
  public-loadbalancer:
    start_on_create: true
    lb_config:
      certs: []
      config: |-
        frontend http-frontend
            bind *:80
            mode http
            redirect scheme https if !{ ssl_fc }
      default_cert: *example.com
      port_rules:
      - hostname: '*'
        path: ''
        priority: 2
        protocol: http
        selector: foo=bar
        source_port: 80
        target_port: 80
      - priority: 3
        protocol: https
        selector: loadbalancer.backend=true
        source_port: 443
      - priority: 4
        protocol: https
        selector: loadbalancer.frontend=true
        source_port: 443
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      interval: 2000
      strategy: recreate
```
**Results:**
services not registered with loadbalancer

**Comment by gregkeys** [comment]
Update: This is working better in 1.6.5+ However Priority attribute seems to be ignored. when you view the config in the api it shows lb_config properties having been moved over to the rancher-compose (which I believe is the intended behavior) however the Priority attribute is missing.

this causes a problem with the loadbalancer haproxy config generation because more often then not webapp with path "/" is placed at the top of the compose files.

If the webapp or root path is placed at the top of the compose files  this makes it the highest priority in the loadbalancer which intercepts all paths making it impossible to have additional services respond to different paths.

what service is responsible for processing the docker-compose.yml from catalogs?

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
