### ISSUE TITLE
Different docker bridge network subnets breaks ipsec network

### ISSUE THREAD

**Issue by qiuwei** [rancher/rancher#8814]
**Rancher versions:**
rancher/server: 1.5.9
rancher/agent: 1.2.2

**Infrastructure Stack versions:**
healthcheck:  0.3.1
ipsec:  rancher/net:holder
network-services: rancher/metadata:v0.9.1, rancher/network-manager:v0.6.6
scheduler: rancher/scheduler:v0.7.5
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
Containers: 40
 Running: 38
 Paused: 0
 Stopped: 2
Images: 86
Server Version: 1.12.6
Storage Driver: btrfs
 Build Version: Btrfs v4.4
 Library Version: 101
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-71-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 24
Total Memory: 188.9 GiB
Name: node1
ID: WWOB:T7TY:MAMQ:ERCW:PXD6:B42P:AAM4:VUOG:NCHM:QVJG:H324:2JP2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8

Containers: 104
 Running: 101
 Paused: 0
 Stopped: 3
Images: 83
Server Version: 1.12.6
Storage Driver: btrfs
 Build Version: Btrfs v4.4
 Library Version: 101
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-75-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 40
Total Memory: 288.3 GiB
Name: node2
ID: NMMC:3GGO:ZZXP:5CQX:ZJOT:2KOA:GGXX:6LG3:5PDA:RVQH:SEPE:ON4F
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8

Containers: 29
 Running: 26
 Paused: 0
 Stopped: 3
Images: 82
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 548
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge overlay null host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 4.4.0-71-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 70.79 GiB
Name: node3
ID: IMRR:CMFW:L2HO:E33G:5362:MGU4:ITKB:TVVJ:3X3R:UAGA:UCEC:HL7V
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
see above

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
singel node rancher, internal DB persistent using a volume

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Docker on node3 is upgraded from an old version, thus the docker0 interface has a different default ip address.  This was fine a while ago. After a network failure, we upgraded rancher server from 1.5.2 to 1.5.9. Since then whenever we add node3, the whole ipsec network stops working, i.e., pinging from one ipsec container to another on a different node doesn't work.

@superseb  can reproduce this by setting up a 3-node cluster, then manualy configuring the docker0 interface of one node to use 172.17.42.1(It was the default before docker 1.9)

We manually reconfigured all of the docker0 interfaces on different nodes to use the same ip address. Afterwards the problem is gone.

**Results:**

**Comment by leodotcloud** [comment]
Related: https://github.com/rancher/rancher/issues/8383

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
