### ISSUE TITLE
RFE: rancher cli ability to pull images before starting the stack/services

### ISSUE THREAD

**Issue by pasikarkkainen** [rancher/rancher#8815]
Older rancher-compose tool allows pulling docker container images before actually starting the stack, using "rancher-compose pull" command, but I can't find such feature on the newer rancher CLI tool.

rancher CLI has the "--pull" option for "up" command, but that'll automatically create/start the services in the stack aswell. Sometimes it's good to be able to first "pull" the images as a separate action when preparing things, and then later on start the stack/services as a separate action.

Did I miss something, or is this feature still missing from the rancher CLI tool?

Thanks.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
