### ISSUE TITLE
rancher/agent accepts anything given in CATTLE_AGENT_IP

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#8816]
**Rancher versions:**
rancher/agent: v1.2.2

**Steps to Reproduce:**
* Set up rancher/server
* Add Custom Host with a non-IP value in `CATTLE_AGENT_IP`:

`sudo docker run -e CATTLE_AGENT_IP="asfsdfdsfdsfdsfdsfdsfsdf"  --rm --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.2.2 http://x:8080/v1/scripts/x:x`

**Results:**
Agent runs successfully. Being added to cluster with no IP showing in Host view and will never be Active.

This can be fixed by:
* Checking valid IP in run.sh (rancher/agent)
* Checking valid IP when host is being registered (rancher/cattle)

**Comment by deniseschannon** [comment]
Available with rancher/agent:v1.6.8-rc1

**Comment by sangeethah** [comment]
Tested with rancher/agent:v1.2.8-rc1.

Able to validate that we allow only for valid ip format ( without http:// or https://) to be set for CATTLE_AGENT_IP when running registration command for Custom Hosts.
