### ISSUE TITLE
TLS handshake issues, on managed network, when client need ECDH

### ISSUE THREAD

**Issue by AndreSteenbergen** [rancher/rancher#8817]
**Rancher versions:**
rancher/server: 1.6.0

**Infrastructure Stack versions:**
healthcheck: active
ipsec: active
network-services:  active

Ubuntu hosted on azure
Single node rancher
Environment Template: Cattle

**Steps to Reproduce:**
Add a stack with any name
Add 2 neo 4j docker instances in this stack, one with managed network, on in bridge
Run a new ubuntu in the bridge network (docker run -it ubuntu) give these command:
apt-get update && apt-get install openssl

when in ubuntu I can run the following commands: (in <<>> replace with IP)
openssl s_client -connect <<neo4jbridge>>:7687 ----> (no problem)

when running the same command from a managed network ubuntu
openssl s_client -connect <<neo4jmanaged>>:7687 ----> internal error:
CONNECTED(00000003)
140371479381664:error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error:s23_clnt.c:770:

But when running this command in the same ubuntu machine it will work
openssl s_client -connect <<neo4jmanaged>>:7687 -cipher 'DEFAULT:!ECDH'

I guess servers in the managed network have an issue with ECDH cipher.

**Comment by AndreSteenbergen** [comment]
Never mind, rebooted server, I can't reproduce anymore.

**Comment by vincent99** [comment]
I would be pretty surprised if the overlay network were somehow causing this...
