### ISSUE TITLE
dns: can not ping from a `net=host` container to a linked service from other stack

### ISSUE THREAD

**Issue by giabao** [rancher/rancher#8819]
**Rancher versions:**
rancher/server: 1.5.9
rancher/agent: 1.2.2

**Infrastructure Stack versions:**
healthcheck: 0.2.3
ipsec: rancher/net:holder, rancher/net:v0.11.2
network-services: metadata:v0.9.1, network-manager:v0.6.6
scheduler: 0.7.5
kubernetes (if applicable): NA

**Docker version: (`docker version`,`docker info` preferred)**
```
# docker version
Client:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:42:17 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:42:17 2016
 OS/Arch:      linux/amd64

# docker info
Containers: 53
 Running: 35
 Paused: 0
 Stopped: 18
Images: 718
Server Version: 1.12.5
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1833
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay bridge null host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-59-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 23.52 GiB
Name: dev
ID: 2RW4:6TJ3:AZVI:UE7J:T7QZ:6WL2:FORA:PP52:JTHT:WHHU:VQEQ:35NG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
# cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
# uname -r
4.4.0-59-generic
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
SIngle node, external DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**

1. Create 2 stacks: st1, st2
2. In st1, create service sv11: image=nginx:1.13, command=sh
3. In st2, create service sv21:
image=nginx:1.13, command=sh, net=host
choose: Enable Rancher DNS service discovery
add service link from sv11
4. execute shell in sv21. In the shell, run: `ping sv11`

**Results:**
`ping: unknown host sv11`

**Notes:**

- If we add service sv22 (in stack st2), and upgrade sv11 with service link: Destination Service = sv22 , As Name = sv22alias. Then in sv21, we also can NOT ping sv22alias.
- if sv21 using Managed Network then ping success (in both cases: sv11 has net=host OR net=managed)

**Comment by vincent99** [comment]
Aliases/"as name" works by adding an answer for that name for the specific containers.  The DNS server looks at the ip who is asking the question to determine which answers to use.  With net host the ip is the host, so it is not possible to get container-specific answers in 1.x.

For 2.0 we have a different way of determining the requesting container that will allow this.

**Comment by jrohde** [comment]
**Workaround:**
Use the full service.stack.rancher.internal name (e.g. sv11.st1.rancher.internal).
