### ISSUE TITLE
Create a DO host with a hostTemplateId ignores digitaloceanConfig fields in the posted Host object

### ISSUE THREAD

**Issue by imikushin** [rancher/rancher#8820]
**Rancher versions:**
rancher/server:master
rancher/agent:v1.2.2

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:

**Docker version (on both rancher server and the created DO host):**
```
Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04.2 LTS
4.4.0-78-generic

**Type/provider of hosts:** DO

**Setup details:** single node rancher, internal DB

**Environment Template:** Cattle

### Pre-requisites

Create a hostTemplate:
```json
{
  "name": "ivan-do-key-ht0",
  "driver": "digitalocean",
  "secretValues": {
    "digitaloceanConfig": {
      "accessToken": null,
    }
  }
}
```

### Repro

Create a host:
```json
{
  "hostTemplateId": "1ht1",
  "hostname": "ivan-do-h1",
  "digitaloceanConfig": {
    "image": "ubuntu-17-04-x64",
    "region": "sfo2",
    "size": "1gb"
  }
}
```

## Results

The host is successfully created, but using the provider default settings, effectively ignoring the parameters set in `host.digitaloceanConfig`.

**Comment by soumyalj** [comment]
Added a host with amazonec2Config. I see the same issue as above. The request was to create a t2.small host in the west zone. A t2.micro host was created in the east zone with all the default settings. The requested docker version was 1.12.6, but docker 17.05.0-ce was installed.

**Comment by deniseschannon** [comment]
Due to changes in 2.0 architecture, closing old issues that were to be tested with the original 2.0 refactoring.
