### ISSUE TITLE
Support for newer Amazon EC2 types

### ISSUE THREAD

**Issue by PicoCreator** [rancher/rancher#8821]
**Rancher versions:**
rancher/server: v1.5.9

**Environment Template: Cattle**

**Steps to Reproduce:**
Go through the machine driver steps to create an instance managed by rancher

**Results:**
Unable to select newer instance types (such as r4). Screenshot as attached

![screen shot 2017-05-20 at 1 03 06 pm](https://cloud.githubusercontent.com/assets/17175484/26273181/f64e232e-3d5c-11e7-8c41-114298f202f7.png)

**Workaround (for now)**
Overwrite the HTML code to allow such an option, seems to be working somewhat for now (YMMV)

![screen shot 2017-05-20 at 1 27 26 pm](https://cloud.githubusercontent.com/assets/17175484/26273309/3448ee36-3d60-11e7-83f9-95d8dcce62a7.png)

**Comment by davidwindell** [comment]
@PicoCreator thanks for the workaround hint! We needed r4 also just now.

**Comment by vincent99** [comment]
There is annoyingly no (1st-party) API to list the instance types, so there's a hardcoded list in the UI.

Adding the missing ones, and also grouping by type..

![image](https://user-images.githubusercontent.com/753917/28485591-6ddc9f08-6e2f-11e7-8f71-29aff29e9edb.png)

**Comment by tfiduccia** [comment]
Version - 1.6.6-rc3
Verified fixed
