### ISSUE TITLE
[external-dns] gandi provider present but no catalog entry ?

### ISSUE THREAD

**Issue by fredleger** [rancher/rancher#8823]
noticed there is a gandi provider in the external-dns repo, but no instructions on how to use it and no catalog entry seems to be present on try.rancher.com (used to test quickly if it wasn't a new feature).

Any idea how it should be used ?

**Comment by superseb** [comment]
Seems there is no catalog item indeed. Maybe @janeczku can tell something about the status of this provider.

If you want to use it, you can create the catalog item. The base is in another provider, i.e. https://github.com/rancher/community-catalog/blob/master/templates/dnsimple/2/docker-compose.yml

`ROOT_DOMAIN`, `NAME_TEMPLATE` and `TTL` are generic, you want to remove `DNSIMPLE_*` and add `GANDI_APIKEY` as described here: https://github.com/rancher/external-dns/blob/master/providers/gandi/gandi.go#L37

I can help you if you want to test it, let me know.

**Comment by superseb** [comment]
Thanks for adding this
