### ISSUE TITLE
use vxlan set subnet failed!

### ISSUE THREAD

**Issue by 694982827** [rancher/rancher#8824]
*Describe your issue here*

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.0` Cattle: `v0.179.7` UI: `v1.6.1` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`settings.projects.edit-template`|
---
in vxlan's config,I set the subnet 10.1.138.0/24,but the container created by rancher is not work correctly。it's netmask is 255.255.0.0 why?

**Comment by niusmallnan** [comment]
@694982827 
Can you share the vxlan cniconfig ? You can view the Vxlan stack "view config" to find these contents.

**Comment by 694982827** [comment]
now I have another question,the container created by vxlan failed to ping  169.254.169.250 but it can success ping the host ip.and the host could also ping  169.254.169.250 and 172.17.0.0/16.
netwofk config:
********************
auto lo
iface lo inet loopback
auto eth0
iface eth0 inet manual
auto br0
iface br0 inet static
address 10.1.139.100
network 10.1.139.0
netmask 255.255.255.0
broadcast 10.1.139.255
gateway 10.1.139.254
dns-nameservers 8.8.8.8
bridge_ports eth0
bridge_stp off
bridge_fd 0
bridge_maxwait 0
***************************
root@expcloud13121843:~# ifconfig
br0       Link encap:Ethernet  HWaddr 1a:53:82:41:b8:3e  
          inet addr:10.1.139.100  Bcast:10.1.139.255  Mask:255.255.255.0
          inet6 addr: fe80::e051:a7ff:fe76:4eea/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:1169003 errors:0 dropped:0 overruns:0 frame:0
          TX packets:237725 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:231944004 (231.9 MB)  TX bytes:277995390 (277.9 MB)

docker0   Link encap:Ethernet  HWaddr 02:42:8d:24:00:01  
          inet addr:172.17.0.1  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::42:8dff:fe24:1/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:2766545 errors:0 dropped:0 overruns:0 frame:0
          TX packets:2862510 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:4258594791 (4.2 GB)  TX bytes:737480141 (737.4 MB)

eth0      Link encap:Ethernet  HWaddr e2:51:a7:76:4e:ea  
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:1460782 errors:0 dropped:0 overruns:0 frame:0
          TX packets:530780 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:611847070 (611.8 MB)  TX bytes:297782618 (297.7 MB)

************************************************************************************
root@expcloud13121843:~# brctl show
bridge name	bridge id		STP enabled	interfaces
br0		8000.1a538241b83e	no		eth0
							veth-cni
							veth0c70dfa5
							veth45e4464c
							veth577a6acc
							veth7b8dbac9
							vethb1dcc392
							vethb66f3cb5
							vethecd04d67
							vethee332d5e
docker0		8000.02428d240001	no		veth-doc
							veth0ff0dcb
							veth1644d22


the vxlan config is :
*************************** rancher-compose.yml**********************************
version: '2'
services:
  vxlan:
    network_driver: &id001
      cniConfig:
        10-rancher-vxlan.conf:
          bridge: br0
          bridgeSubnet: 10.1.139.0/24
          hairpinMode: true
          hostNat: true
          ipam:
            isDebugLevel: 'false'
            logToFile: /var/log/rancher-cni.log
            routes:
            - dst: 169.254.169.250/32
            type: rancher-cni-ipam
          isDebugLevel: 'false'
          isDefaultGateway: true
          linkMTUOverhead: 50
          logToFile: /var/log/rancher-cni.log
          mtu: 1500
          name: rancher-cni-network
          type: rancher-bridge
      defaultNetwork:
        dns:
        - 169.254.169.250
        dnsSearch:
        - rancher.internal
        hostPorts: true
        name: vxlan
        subnets:
        - networkAddress: 10.1.139.0/24
          cidrSize: 24
        defaultPolicyAction: allow
      name: Rancher VXLAN
    start_on_create: true
  cni-driver:
    network_driver: *id001
    scale: 1
    start_on_create: true
*********************end  rancher-compose.yml*****************

*************************docker-compose.yml ******************
version: '2'
services:
  vxlan:
    cap_add:
    - NET_ADMIN
    image: rancher/net:v0.11.2
    environment:
      RANCHER_DEBUG: 'false'
    network_mode: vxlan
    logging:
      driver: json-file
      options:
        max-file: '2'
        max-size: 25m
    volumes_from:
    - cni-driver
    ports:
    - 4789:4789/udp
    command:
    - start-vxlan.sh
    labels:
      io.rancher.container.agent_service.vxlan: 'true'
      io.rancher.sidekicks: cni-driver
      io.rancher.cni.link_mtu_overhead: '0'
      io.rancher.service.selector.link: io.rancher.internal.service.vxlan=true
      io.rancher.network.arpsync: 'true'
      io.rancher.container.create_agent: 'true'
      io.rancher.network.macsync: 'true'
      io.rancher.scheduler.global: 'true'
      io.rancher.internal.service.vxlan: 'true'
  cni-driver:
    privileged: true
    image: rancher/net:v0.11.2
    network_mode: host
    logging:
      driver: json-file
      options:
        max-file: '2'
        max-size: 25m
    pid: host
    command:
    - sh
    - -c
    - touch /var/log/rancher-cni.log && exec tail ---disable-inotify -F /var/log/rancher-cni.log
    labels:
      io.rancher.network.cni.binary: rancher-bridge
      io.rancher.container.dns: 'true'
      io.rancher.service.selector.link: io.rancher.internal.service.vxlan=true

**Comment by niusmallnan** [comment]
@694982827

1. You mentioned before using the subnet is 10.1.138.0/24, but your cniconfig setting is 10.1.139.0/24. I dont know why you set this? 
2. what's your br0 support for? Rancher cannot run with other platform, because iptable rules may conflict.

**Comment by 694982827** [comment]
@niusmallnan 
1、Before the subnet is 10.1.138.0/24  and the config setting is 10.1.138.0/24 . Because of some reasons I changed the subnet 10.1.138.0/24  to 10.1.139.0/24 and now  the cniconfig setting is 10.1.139.0/24。
2、I use br0 in vxlan's config，when creating vxlan there is a blank  "Docker Bridge" and I set br0 .  I just want to set  container on a same subnet as host.

**Comment by niusmallnan** [comment]
1. If you set br0 for vxlan, you must set docker bridge to br0(not docker0).
2. If you  want to set container on a same subnet as host, you cannot do this. Because vxlan is an overlay networking, use rancher-flat network will meet your requirements.

Here some points:
Rancher flat: https://github.com/rancher/rancher/issues/8673
Rancher macvlan: https://github.com/rancher/rancher/issues/8686
Rancher Calico: https://github.com/rancher/rancher/issues/8603

**Comment by 694982827** [comment]
Is it the same way as http://www.greatops.net/?id=106&utm_source=tuicool&utm_medium=referral?I use this to meet myrequirements.

**Comment by 694982827** [comment]
@niusmallnan 
I changed to rancher-flat network,I add one host on UI is ok,but when I add another host,there is something  wrong with the first host,the first host's container will restart and it's host ip also changed to 172.17.0.1.And the new added host could't show on UI,  Is there anything wrong with my config？

**Comment by niusmallnan** [comment]
@694982827 
You can add host with CATTLE_AGENT_IP param, this will avoid your problem.

**Comment by 694982827** [comment]
@niusmallnan 
I have tried to set CATTLE_AGENT_IP like this :

- host-one:

docker run -e CATTLE_AGENT_IP="10.1.139.100"  --rm --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.2.2 http://10.1.139.100:8080/v1/scripts/631738D6E1F6D4450F85:1483142400000:8NIp8TxMw94rWA9iDD9fVUzc4EA

- host-two::

 docker run -e CATTLE_AGENT_IP="10.1.139.101"  --rm --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.2.2 http://10.1.139.100:8080/v1/scripts/631738D6E1F6D4450F85:1483142400000:8NIp8TxMw94rWA9iDD9fVUzc4EA

but when I add host-two it seems does not work and  caused rancher/server exited

**Comment by 694982827** [comment]
@niusmallnan 
The second host is copyed by the first one,and I changed the ip、hostname、interface‘s mac address and restart it but is seems there is something conflict with the first when adding the second host。I changed a new host everything is ok。

and today I find another problem:using rancher-flat network  env,when add an user stack etcd on catalog,the etcd container could init successfully,the log output:

2017-5-27 11:34:32wget: server returned error: HTTP/1.1 404 Not Found
and I find the etcd container's run.sh:
http://rancher-metadata.rancher.internal/2015-12-19/self/stacks/name, it can't get is's data from here because there is no data.but when I changed the default env,it works well and the etcd contailer could get data from http://rancher-metadata.rancher.internal/2015-12-19/self/stacks/name.I can;t understand this，could you give me some advises?

**Comment by niusmallnan** [comment]
@694982827 
Are you in China？My wechat: niusmallnan.
See this: https://github.com/rancher/rancher/issues/8884#issuecomment-304425067

**Comment by 694982827** [comment]
@niusmallnan 
Yes , thank you very much!

**Comment by superseb** [comment]
Is this still on-going or can we close this? @694982827 @niusmallnan ?

**Comment by 694982827** [comment]
@superseb 
You can close it.

**Comment by leodotcloud** [comment]
Same as:
https://github.com/rancher/rancher/issues/8938
https://github.com/rancher/rancher/issues/6511

Waiting for this PR to be merged: https://github.com/rancher/rancher-net/pull/60
