### ISSUE TITLE
Parity for Rancher support for docker-ce and docker-ee (Enterprise Edition)

### ISSUE THREAD

**Issue by rocketeer125** [rancher/rancher#8825]
Further to https://github.com/rancher/rancher/issues/8547

As Docker is now releasing CE and EE versions of Docker, supported docker versions should probably show some parity between the two streams as they are effectively the same releases:
http://docs.rancher.com/rancher/v1.6/en/hosts/#supported-docker-versions

Current:
```
17.03.x-ee
17.03.x-ce
17.04.x-ce
17.05.x-ce
```
Should be:
```
17.03.x-(ce|ee)
17.04.x-(ce|ee)
17.05.x-(ce|ee)
```

**Comment by vincent99** [comment]
A) They are not the same release.  They are not supported for the same amount of time by Docker and will not be supported for the same amount of time by us.
B) There exists no public download link for EE.
C) EE is quarterly, 17.04 and 05 EE do not exist.
