### ISSUE TITLE
Automate rancher-compose-commands tests through rancher CLI

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#8830]
Automate the following rancher-compose commands tests through rancher CLI(both V1 and V2)
1. test_rancher_compose_services_security()
2. test_rancher_compose_services_log_driver()
3. test_rancher_compose_services_network()
4. test_rancher_compose_services_volume()

Automate all rancher compose commands tests for V2
Automate CLI tests with v2 compose files

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
