### ISSUE TITLE
Can't clone a host

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#8832]
**Rancher versions:** 5/22

**Steps to Reproduce:**
1.  Try to clone a host

**Results:** takes me to the Error page.  error in console is ember.debug.js:18023 TypeError: Cannot read property 'find' of undefined
![image](https://cloud.githubusercontent.com/assets/11514927/26331617/bab12996-3f06-11e7-81e8-4be34a5391c2.png)

**Comment by vincent99** [comment]
Removing host clone in favor of hostTemplates.
