### ISSUE TITLE
Stack details page Scaling group missing accordian

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#8835]
**Rancher versions:** 5/22

**Steps to Reproduce:**
1.  Create a stack that has services and stand-alone containers
2.  Go to stack detail page

**Results:** 
- [x] Stand-alone containers are missing from container section.  
- [x] Scaling Group and Load Balancer container should not be in container section
- [x] Scaling Group & Load Balancer should have sub-accordian with their respective containers

**Comment by westlywright** [comment]
@vincent99 looks like maybe you resolved this can you confirm?

**Comment by vincent99** [comment]
The first one is but SG and LB should be expandable to show the containers under those

**Comment by tfiduccia** [comment]
Version - 6/12 (2.0 alpha)
Verified fixed
