### ISSUE TITLE
no containers and services create in k8s template

### ISSUE THREAD

**Issue by colinlabs** [rancher/rancher#8837]
**Rancher versions:**
rancher/server: v1.6.0
rancher/agent: v1.2.2

**Infrastructure Stack versions:**
healthcheck:v0.3.1
ipsec:  rancher/net:holder
network-services:  network-manager:v0.7.0|metadata:v0.9.1
scheduler:
kubernetes (if applicable):
v1.5.4-rancher1-4

**Docker version: (`docker version`,`docker info` preferred)**
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:26:30 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:26:30 2017
 OS/Arch:      linux/amd64

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.4 LTS
Release:	14.04
Codename:	trusty

3.13.0-86-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
ECS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
internal DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
1. add k8s template
2. add host
3. add `wordpress`  catalog from k8s template
4. launch

**Results:**
there are no containers and services create
![image](https://cloud.githubusercontent.com/assets/10361796/26336117/48e2e49c-3fa3-11e7-8bcf-d5adcf23396b.png)

**Comment by aemneina** [comment]
I dont believe there are catalog items for kubernetes within rancher anymore. You should be using helm/tiller to deploy to kubernetes, unless you have your own services defined.

**Comment by deniseschannon** [comment]
These k8s templates were no longer valid as of v1.3.99 but we didn't appropriately put in maximum rancher version on the templates. They are now hidden in Rancher.
