### ISSUE TITLE
Rancher server container restarted when external database is not available or failover

### ISSUE THREAD

**Issue by pengjiang80** [rancher/rancher#8838]
Backend database supported by keepalived and MySQL replication. When there is a fail-over (1-2 seconds), rancher server container will be restarted due to db connection lost.  And it will take some time for the rancher server container fully started.

Expected: Rancher server container should not restart when DB is not available. 

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.0` Cattle: `v0.179.7` UI: `v1.6.1` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`stacks.index`|

**Comment by pengjiang80** [comment]
Log of container as below:

FATAL: Exiting due to failed cluster check-in
time="2017-05-23T07:53:54Z" level=info msg="Exiting go-machine-service" service=gms
time="2017-05-23T07:53:54Z" level=info msg="Exiting rancher-compose-executor" version=v0.13.3
time="2017-05-23T07:53:54Z" level=fatal msg="Parent process went away. Shutting down."

**Comment by pengjiang80** [comment]
Per https://github.com/rancher/cattle/blob/95e01609f5673d3aa34244e79210c5555b830f73/code/implementation/hazelcast/common/src/main/java/io/cattle/platform/hazelcast/membership/DBDiscovery.java, we will do system.exit when failed in cluster membership checkin, is it mandatory?

**Comment by pengjiang80** [comment]
Changed cluster.checkin.seconds and cluster.checkin.misses in api settings seems helpful. Is it safe to change the settings? What's the recommended settings if we don't want to restart Rancher server container during database failover? Thanks.

**Comment by ibuildthecloud** [comment]
It's pretty important to the design of the cluster in Rancher that if the DB becomes unavailable the server must die.  The current settings are the recommended settings.  If there are any issues I would say it would be the fact that restart takes a long time, not that it restarted in the first place.  If DB becomes unavailable, we really have to restart.

**Comment by pengjiang80** [comment]
Got it. Thanks for reply. @ibuildthecloud
