### ISSUE TITLE
Rancher affinity host must have label condition

### ISSUE THREAD

**Issue by DuratarskeyK** [rancher/rancher#8839]
Greetings. Is it possible to somehow specify range of label values for 1 label name? So for example I have 6 hosts each with label key and value 1 through 6 respectivly on each host. I'd like to deploy a service to 3 of these host by specifying labels 1,2,3 or 2,3,4. But I can't. If I have several affinity conditions with a must have host label, it won't deploy service, because it uses and, not or for the conditions and will not deploy. Question: is it possible to somehow specify conditions for labels with an OR?

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
