### ISSUE TITLE
Canceling out of clone from host details page takes me back to main host page

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#884]
v0.21.2
Steps:
1.  Create a host/machine
2.  Click on host name to go to details page
3.  From menu on right, select Clone
4.  Click on Cancel

Results:
Takes me to the main host page

Expected:
Should take me back to the host details page

**Comment by deniseschannon** [comment]
v0.51.0 - This is still an issue.

**Comment by tfiduccia** [comment]
Version - master 3/15
Verified fixed
