### ISSUE TITLE
Rancher-dns answer section order

### ISSUE THREAD

**Issue by gyalai** [rancher/rancher#8840]
**Rancher versions:**
rancher/server: 1.6.0
rancher/agent: 1.2.2

**Infrastructure Stack versions:**
ipsec: 0.1.0
network-services: 0.9.1

**Docker version: (`docker version`,`docker info` preferred)**
17.05.0-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04 4.4.0-77-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Call the `dig www.microsoft.com A` command. 

**Results:**
; <<>> DiG 9.9.5-9+deb8u11-Debian <<>> www.microsoft.com A
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 2490
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4000
;; QUESTION SECTION:
;www.microsoft.com.             IN      A

;; ANSWER SECTION:
www.microsoft.com-c-2.edgekey.net.globalredir.akadns.net. 705 IN CNAME e1863.dspb.akamaiedge.net.
e1863.dspb.akamaiedge.net. 10   IN      A       104.123.141.179
www.microsoft.com-c-2.edgekey.net. 4966 IN CNAME www.microsoft.com-c-2.edgekey.net.globalredir.akadns.net.
www.microsoft.com.      943     IN      CNAME   www.microsoft.com-c-2.edgekey.net.

;; Query time: 0 msec
;; SERVER: 169.254.169.250#53(169.254.169.250)
;; WHEN: Tue May 23 10:49:04 UTC 2017
;; MSG SIZE  rcvd: 212

`

`

In the answer section the CNAME and the A order is different in almost every DNS call. With our DNS the result is always in the same order. First the CNAMEs and at the and the A.

We are using java code where if the A value is before the CNAME than we get java.net.UnknownHostException . The java version is OpenJdk 1.8.0_111.

**Comment by superseb** [comment]
Thanks for reporting. This should be fixed by https://github.com/rancher/rancher-dns/pull/63, let me know if you don't agree.
