### ISSUE TITLE
externalIdType for users in ping federator auth enabled setups is set as "shibboleth_user"

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#8844]
Rancher server version - v1.6.0
Setup - ping federator auth enabled setup
Log in as any valid user to a ping federator auth enabled setup.
When accessing http://<rancher-server> :8080/v2-beta/identities , externalIdType is set as "shibboleth_user".

```
{
"id": "1i!shibboleth_user:testuser11",
"type": "identity",
"links": {
"self": "…/v2-beta/identities/1i!shibboleth_user:testuser11",
},
"actions": { },
"baseType": "identity",
"all": null,
"externalId": "testuser11",
"externalIdType": "shibboleth_user",
"login": null,
"name": null,
"profilePicture": null,
"profileUrl": null,
"projectId": null,
"role": null,
"user": true,
},
```

**Comment by deniseschannon** [comment]
@nathan-jenan-rancher when implementing SAML 2.0 for Rancher 2.0, just be conscious that we use other external types besides shibboleth, so it should be more generic.

**Comment by vincent99** [comment]
That's the name of the provider so that's the type.  For 2.0 every individual auth product we support will have its own config.
