### ISSUE TITLE
Validate PingFederator auth service.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#8845]

**Comment by sangeethah** [comment]
For feature issue - https://github.com/rancher/rancher/issues/8665

**Comment by galal-hussein** [comment]
Test cases included:

## PingFederate Authentication:

- [x] 1. Enable Access Control . Choose “Allow any valid User” as “Site Access”. Make sure any SAML user is able to access the site.
- [x] 2. Enable Access Control . Choose “Restrict to Specific User”  and add few users. Make sure only the specified users have access to the server. Others should get authentication error.
- [x] 3. Enable Access Control . Choose “Restrict to Specific User”  and a SAML group. Make sure only all  users belonging to the group have access to the server Others should get authentication error. 
- [x] 4. Log in as a SAML user (who has access to server but not a member of any environment) , a new default environment should be created for this user with this user account being the owner of the environment. Account entry should get created for this user.
- [x] 5. Log in as a SAML user (who has access to server) , create a new environment. This user should become the owner of the environment.
- [x] 6. As owner of environment , Add a SAML user as “member” of an environment.Make sure this user gets  access to this environment.
- [x] 7. As owner of environment , Add a SAML user as “owner” of an environment.Make sure this user gets  access to this environment. User should also have ability to manage this environment which is to add/delete member of the environment.
- [x] 8. As owner of environment , Add a SAML group as “member” of an environment.Make sure that all  users that belong to  this group get access to the environment.
- [x] 9. As owner of environment , Add a SAML group as “owner” of an environment.Make sure all users of the group gets  access to this environment. User should also have ability to manage this environment which is to add/delete member of the environment.
- [x] 10. As owner of environment , change the role of a member of the environment from “owner” to “member”. Make sure his access control reflects this change.
- [x] 11. As owner of environment , change the role of a member of the environment from “member” to “owner”. Make sure his access control reflects this change.
- [x] 12. As owner  of environment, remove an existing “owner” member of the environment.Make sure this user does not have access to environment anymore.
- [x] 13. As owner of environment, remove an existing “member” member of the environment.Make sure this user does not have access to environment anymore.
- [x] 14. As owner of environment, deactivate the environment. Members of the environment should have no access to environment. Owners should only be able to see in their manage environments but not list of active environments.
- [x] 15. As owner of environment, Activate a deactivated environment. Members of the environment should now have access to environment.
- [x] 16. As owner of environment, delete a deactivated environment.Members of the environment should not have access to environment. All hosts relating to the environment should be purged (only hosts created through docker-machine). Custom hosts will not be purged.
- [x] 17. As admin user, deactivate an existing account. Account should have no access to rancher server.
- [x] 18. As admin user, activate a deactivated account.Account should get back access to rancher server.
- [x] 19. As admin user, delete an existing account. Once account is purged, make sure that account is not a member of environments.
- [x] 20. As member user of environment, trying to add a member to environment should fail.
- [x] 21. As member user of environment, trying to delete an existing member to the environment should fail
- [x] 22. As member user of environment, trying to deactivate an environment should fail
- [x] 23. As member user of environment, trying to delete an environment should fail.
- [x] 24. As member user of environment, trying to change the role of an existing  member to the environment should fail.
- [x] 25. As admin user, change account type of existing "user" to "admin". Check that they have access to "Admin" tab.
