### ISSUE TITLE
agent panic

### ISSUE THREAD

**Issue by StrongMonkey** [rancher/rancher#8848]
```
time="2017-05-23T17:09:35Z" level=error msg="read tcp 10.128.0.51:58788->35.184.217.139:8080: use of closed network connection" 
panic: send on closed channel

goroutine 167084 [running]:
panic(0x96d600, 0xc42156a5f0)
    /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/rancher/agent/service/hostapi/stats.(*HostStatsHandler).Handle.func2(0xc4202d02c0, 0x24, 0xc420929d40, 0xc4236e6a30)
    /go/src/github.com/rancher/agent/service/hostapi/stats/host_stats.go:64 +0x1a0
created by github.com/rancher/agent/service/hostapi/stats.(*HostStatsHandler).Handle
    /go/src/github.com/rancher/agent/service/hostapi/stats/host_stats.go:69 +0x266
INFO: Starting agent for 36FE4EBFA653FA564389
```

The reason is that if web-socket connection is dropped, we closed the channel used to deliver the message. But at the same there could be several go-routines still writing to that channel and then panic happens. The safest way is to not close the channel if we don't explicitly require them to do.

**Comment by sangeethah** [comment]
Tested with rancher-server v1.6.15-rc3 and rancher agent version - rancher/agent:v1.2.10-rc3 .
Tried the following steps multiple times and did no see a panic in agent logs:

1. Have the host stats page open in UI , so there is active connection and data exchange .
2. Kill the websocket proxy process .
3. This results in status in the UI not shown for sometime and then when  websocket proxy process gets recreated , UI get   to "connecting" state and the shows the stats eventually.
4. In the agent log , there is no panic noticed. Agent restarts successfully.
