### ISSUE TITLE
Cloning host broken

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#8849]
**Rancher versions:** 5/23

**Steps to Reproduce:**
1.  Try to clone a host

**Results:**  Get an error page - ember.prod.js:16699 TypeError: Cannot read property 'find' of undefined
![image](https://cloud.githubusercontent.com/assets/11514927/26380655/b9fb1416-3fd4-11e7-8d71-70384a1cc514.png)

**Comment by vincent99** [comment]
#8832
