### ISSUE TITLE
Host status frequently changes to "reconnecting" while k8s node status is always displayed as "Ready."

### ISSUE THREAD

**Issue by nayang777** [rancher/rancher#8851]
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.0` Cattle: `v0.179.7` UI: `v1.6.1` |
|Access|`localauth` `admin`|
|Orchestration|`Kubernetes`|
|Route|`hosts.index`|

**Docker version: (1.12.6)**

**Operating system and kernel: (Centos 7.2 - 3.10.0)**

**Steps to Reproduce:**
Host status frequently changes to "reconnecting" while node status is always displayed as "Ready."

![image](https://cloud.githubusercontent.com/assets/19829696/26389981/2214e170-408f-11e7-94f5-12b0594b26f0.png)

![image](https://cloud.githubusercontent.com/assets/19829696/26390034/6048e05e-408f-11e7-9b4c-449fc4db7a31.png)

**Results:**

**Comment by superseb** [comment]
The host status is determined by the rancher-agent responding to "ping" packets from rancher server, the Ready state is determined by the kubelet giving a NodeReady event.

So the place to debug this is in the rancher/agent container log.
