### ISSUE TITLE
Serious: Stack resetting its (volume) scope - data reset - data loss on prune

### ISSUE THREAD

**Issue by EugenMayer** [rancher/rancher#8853]
**Rancher versions:**
rancher/server: 1.6.0
rancher/agent: 1.2.2

**Infrastructure Stack versions:**
healthcheck: v0.3.1
ipsec: v0.11.2
network-services: v0.7.0
scheduler: v0.7.5
network-manager: v0.7.0

**Docker version: (`docker version`,`docker info` preferred)**
Docker version 17.03.1-ce, build c6d412e

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
4.9.24-rancher

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
 private proxmox4/KVM, VM, rancheros 1.0.1 LTS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
no ha, local DB for the rancherdb.
Managing rancher-server is not on the agent ( host ) being managed

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
I am yet not entirely sure what leads to this, but my guess is, while having stacks running ( with named volumes ) and you remove (deactivate/delete) the host to add it with a new ip, the new stacks simply get a new scope and get new volumes, so all stack are broken - resetted.

It happened to all of my stacks - it yet did never happened until now ( did IP changes before ). It think that might be an 1.6.0 issue or a very recent version.

**Results:**
Stacks do detach from there volumes, getting a new scope and creating new volumes - leaving the production volumes to be pruned.

**Comment by EugenMayer** [comment]
I do yet have no lab setup at hand and i cannot try this on my production instances, since that does a lot of harm, even if noticed ( huge work ... ) if not noticed, the data is lost

**Comment by EugenMayer** [comment]
Is this really so uninteresting? This is not at all a question.

**Comment by StrongMonkey** [comment]
@EugenMayer are you using container-scoped volume? There is a known issue in 1.6 which the volume will be deleted at some circumstances.(https://github.com/rancher/rancher/issues/8755)

**Comment by EugenMayer** [comment]
It is unrelated @StrongMonkey i most probably think. In this case, simply the scope changes, the scope suffix is regenerated due to a host change. There was no "upgrade" process - though it might be something run when you dettach a host and attach it again and it detects stacks running on that  - i do not know. In any case, yes i think my issue was introduced in 1.6 and it really scares me off

And having this tagged as question for ten days scares me too - since i guess this are the kind of issues you want to be fixed instantly.

**Comment by janeczku** [comment]
@EugenMayer are you using a storage driver or docker (local) volumes? Could you please paste an example docker-compose?

**Comment by EugenMayer** [comment]
local volumes

**Comment by EugenMayer** [comment]
I could finally reproduce this issue.

When you rename a stack using edit in the stack oversight, and then on the next upgrade / container delete, a new container is created, the "stack scope" is changing to the new name, thus new stack named volumes are created, resulting in data loss.

Is seriously nobody caring about this?

**Comment by aemneina** [comment]
@EugenMayer you're using stack scoped volumes, so @StrongMonkey was homing in on your issue. You can use a local volume where the volume name wont change based on stack (re-)creation.

**Comment by EugenMayer** [comment]
@aemneina i am aware of how to recover - still this can be an automatic outage of a complete stack and also recovering is not a "stupid easy" task either.

I am not sure how you would use unscoped  volumes, because even using the old fashioned custom "prefix" using a vairable wont help, since the scope name is added nevertheless. So unless you use anon volumes, which is obviously nothing being an option, you run into this issue all the time.

@aemneina could you explain how you marked this issue a question? Not sure, what kind of a question we have here

**Comment by aemneina** [comment]
It's marked question because what you're observing is expected. I don't see a bug here, I could be wrong. We can change it at any point we determine there is a bug.

[Stacked scoped volumes](http://docs.rancher.com/rancher/v1.6/en/rancher-services/storage-service/#stack-scoped-1) are created and removed as part of the stacks' lifecycle. Your volume name would resemble `stackname_servicename_id` if you were to do a `docker volume ls` on the host where the service was created. 

[Environment scoped volumes](http://docs.rancher.com/rancher/v1.6/en/rancher-services/storage-service/#environment-scoped-1) will persist beyond your stack upgrades/deletes. Moreover the name has no hashes and should be identical to what you named it. `docker volume ls` on the host will validate this. The example in the docs uses the rancher-nfs plugin. But for a local docker volume with environment scoped you could use this as an example:

```
version: '2'
services:
  test:
    image: ubuntu:16.10
    volumes:
    - testvol:/testmount
```

Let me know if that clears things up.

**Comment by EugenMayer** [comment]
@aemneina if that is _really_ desired you should remove _any_ option to rename a stack or write a big fat warning in front of it, that this will result in this havoc. This is not inconvenient - this is shocking. Who ever implemented the stack name as unique key would have at least though about: 

 - removing the option to change the primary (suprise )
 - migrate the "old volumes" to the new ones automatically ( so damn easy )
 - or at least write a huge fat warning about this

Instead, once again, i get a "by design" - its all good - nothing to worry about. I cannot really think about how you touch those kind of areas which are storage... it feels you are playing with toys here and just throw something at the people and see what happens.

I heard this a lot in rancher already, the same story with having no scope at all back in the days. I got told you guys made this by intention and here you go, months later you finally have it and stopped being that kind of "defensive" about such requests - but there was the same approach, "its by design, its like it should be" - as it was back in times when no-scope volume were the default "by design".

You are treating data as it is generated trash and can be thrown away at any time. You are hurting the trust into rancher SO much with those kind of things. Including all the other issues, be it DNS issues with take your stack out since 1.2+ and more or less nobody cares and everybody is scared to ever upgrade again to see something else go completely nuts ( like 1.6.0 ).

I am not sure who is driving your design decisions, i really like rancher, but especially this points are so ridiculous that it hurts telling anybody else, "try rancher, it great". Yes, thats kind of a rant, because i really see this getting repeated and repeated over and over again.

**Comment by EugenMayer** [comment]
To add something - having a bug is "that just happens" - esp. with such a huge project. Having a bug in the storage / user data layer is even more a pitty and must be treated carefully.

But getting a "by design" in those kind of things is "by design" driving people crazy. 

And months later, suddenly, the design changes.

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
