### ISSUE TITLE
Scaling group doesn't convert to scaling or take a name

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#8860]
**Rancher versions:** 5/24

**Steps to Reproduce:**
1.  Create a container
2.  After it's active, select convert to scaling group
3.  Change the name to something else
4.  Go to scaling group page (name issue)
5.  Go to menu for container (convert to SG is still available)

**Results:**
1.  The Scaling group Name is still the container name instead of new name I gave it.  Field doesn't seem to exist in the api.
2.  Container that I converted to scaling group doesn't recognize it as scaling group & convert to scaling group is still available

**Comment by ibuildthecloud** [comment]
The name has been removed from the API.  Convert to SG still available is fixed in https://github.com/rancher/cattle/pull/2714

**Comment by tfiduccia** [comment]
I guess name can't change?  So this needs to be updated in UI

**Comment by tfiduccia** [comment]
Version - master 2.0 (8/2)
Verified fixed
