### ISSUE TITLE
Links are not showing up in edit/upgrade or clone

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#8865]
**Rancher versions:** 5/24

**Steps to Reproduce:**
1.  Create a container with a few links
2.  Edit/upgrade or clone that container

**Results:**  Links are not showing up

**Comment:** 
 I checked the post and they are there, and I checked the API and they seem to be there as well

**Comment by tfiduccia** [comment]
Version - Wagyu (master 7/25)

The links are still not showing up in upgrade/edit/clone for Containers.

**Comment by westlywright** [comment]
@tfiduccia the schema for containers says that links are not updatable. I thought they were. We should put in an issue to allow them to be updated or argue with @vincent99 as to why they should not be haha

**Comment by tfiduccia** [comment]
version - 2.0 master 1/10
no links in containers
