### ISSUE TITLE
New stacks created through Add container/Scaling group are not showing up in UI

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#8868]
**Rancher versions:** 5/24

**Steps to Reproduce:**
1.  Create a container and add it to a new stack that you create at same time as container
2.  Change container view to group view
3.  Go to Scaling Group page

**Results:**  The new stack does not show up and those containers are not showing up

**Comment by vincent99** [comment]
Each tab shows only the stacks that have one ore more of that kind of resource in it.

**Comment by tfiduccia** [comment]
Version - 5/25
Verified ok....
