### ISSUE TITLE
Plenty of "Error looking up token" logs

### ISSUE THREAD

**Issue by hiscal2015** [rancher/rancher#8874]
**Rancher versions:** 1.5.10

**Docker version: (`docker version`,`docker info` preferred)** 1.12.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)** Ubuntu16.04

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** Bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)** Single

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)** Kubernetes

**Steps to Reproduce:**

Setup a CLEAN rancher server, check docker logs and found below, any ideas what they are?

```
 time="2017-05-25T01:14:43Z" level=error msg="Error looking up token." error="HTTP error: 403 Forbidden, 403" 
 time="2017-05-25T01:14:44Z" level=error msg="Error looking up token." error="HTTP error: 403 Forbidden, 403" 
 time="2017-05-25T01:14:45Z" level=error msg="Error looking up token." error="HTTP error: 403 Forbidden, 403" 
 time="2017-05-25T01:14:46Z" level=error msg="Error looking up token." error="HTTP error: 403 Forbidden, 403" 
 time="2017-05-25T01:14:47Z" level=error msg="Error looking up token." error="HTTP error: 403 Forbidden, 403" 
 time="2017-05-25T01:14:48Z" level=error msg="Error looking up token." error="HTTP error: 403 Forbidden, 403" 
 time="2017-05-25T01:14:49Z" level=error msg="Error looking up token." error="HTTP error: 403 Forbidden, 403" 
 time="2017-05-25T01:14:50Z" level=error msg="Error looking up token." error="HTTP error: 403 Forbidden, 403" 
 time="2017-05-25T01:14:51Z" level=error msg="Error looking up token." error="HTTP error: 403 Forbidden, 403" 
 time="2017-05-25T01:14:52Z" level=error msg="Error looking up token." error="HTTP error: 403 Forbidden, 403" 
 time="2017-05-25T01:14:53Z" level=error msg="Error looking up token." error="HTTP error: 403 Forbidden, 403" 

```

Before this, there are key errors as below:
```
time="2017-05-25T01:13:43Z" level=info msg="Downloading key from http://localhost:8081/v1/scripts/api.crt" 
 time="2017-05-25T01:13:43Z" level=fatal msg="Error getting config." error="Invalid key content" 
 2017-05-25 01:13:43,795 ERROR [:] [] [] [] [ecutorService-1] [o.a.c.m.context.NoExceptionRunnable ] Uncaught exception org.jooq.exception.DataAccessException: SQL [insert into `data` (`name`, `visible`, `value`) values (?, ?, ?)]; (conn:11) Duplicate entry 'host.api.key' for key 'idx_data_name'
 Query is: insert into `data` (`name`, `visible`, `value`) values (?, ?, ?), parameters ['host.api.key',0,'-----BEGIN RSA PRIVATE KEY-----

```

**Comment by vincent99** [comment]
An old host pointed at the same ip the new server is running on.  The new server doesn't know anything about that host's API keys, so the request is rejected.

**Comment by hiscal2015** [comment]
@vincent99 I have cleaned up all containers on all hosts, there should not be any host communicate to the new server.

**Comment by manwanth** [comment]
Getting "Host not registered yet. Sleeping 1 second and trying" message while adding host into Rancher and host not connecting to Rancher. Any one noticed such behavior?

Rancher : V.1.6.11
Docker : 1.12.6
Kubernetes : V1.8.3

time="2017-11-27T14:36:54Z" level=info msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=8 reportedUuid=3db62505-2baa-4622-4b8c-789b8afa0e74
time="2017-11-27T14:36:55Z" level=info msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=9 reportedUuid=3db62505-2baa-4622-4b8c-789b8afa0e74
time="2017-11-27T14:36:56Z" level=info msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=10 reportedUuid=3db62505-2baa-4622-4b8c-789b8afa0e74
time="2017-11-27T14:36:57Z" level=info msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=11 reportedUuid=3db62505-2baa-4622-4b8c-789b8afa0e74
time="2017-11-27T14:36:58Z" level=info msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=12 reportedUuid=3db62505-2baa-4622-4b8c-789b8afa0e74
time="2017-11-27T14:36:59Z" level=info msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=13 reportedUuid=3db62505-2baa-4622-4b8c-789b8afa0e74
time="2017-11-27T14:37:00Z" level=info msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=14 reportedUuid=3db62505-2baa-4622-4b8c-789b8afa0e74
time="2017-11-27T14:37:01Z" level=info msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=15 reportedUuid=3db62505-2baa-4622-4b8c-789b8afa0e74
time="2017-11-27T14:37:02Z" level=info msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=16 reportedUuid=3db62505-2baa-4622-4b8c-789b8afa0e74

**Comment by superseb** [comment]
Issue has been closed 4 months ago, please file a new issue with reproducible steps so we can take a look.
