### ISSUE TITLE
Can't connect to container in other host after restart docker daemon

### ISSUE THREAD

**Issue by radishgz** [rancher/rancher#8875]
**Rancher versions:
rancher/server:v1.5.9
rancher/agent:v1.2.2 

**Infrastructure Stack versions:**
healthcheck: still in 'Initializing' ,it's log continued output '2017-5-25 09:39:11time="2017-05-25T01:39:11Z" level=info msg="healthCheck -- no changes in haproxy config\n"
ipsec: active
network-services:active
scheduler:active
kubernetes (if applicable): 

**Docker version: (`docker version`,`docker info` preferred)**
Containers: 8
 Running: 8
 Paused: 0
 Stopped: 0
Images: 13
Server Version: 1.12.6
Storage Driver: devicemapper
 Pool Name: docker-253:0-50745758-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.514 GB
 Data Space Total: 107.4 GB
 Data Space Available: 20.2 GB
 Metadata Space Used: 5.628 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.142 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.135-RHEL7 (2016-09-28)
Logging Driver: json-file
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Security Options: seccomp
Kernel Version: 3.10.0-514.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 2
CPUs: 1
Total Memory: 3.703 GiB
Name: 6centos.wh
ID: YFBV:KJK6:EFHM:IE7F:47S4:57ZN:UYSN:PROS:O4RE:CKAC:M7MN:UL5E
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 10.0.2.50
 127.0.0.0/8
Registries: docker.io (secure)
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Linux 6centos.wh 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
[root@6centos testlogs]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Install an fluentd 0.14 in a node , an elasticsearch 5.3.1 in another node.

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
cattle + vxlan 
**Steps to Reproduce:**
1. exec command: systemctl stop docker, 
2. after one minute, exec systemctl start docker
**Results:**
fluentd container started but can't connect to elasticsearch .
use docker exec into fluentd container, exec ping
root@41b44abf3f4f:/home/fluent# ping elasticsearch-clients
PING elasticsearch-clients.elk.rancher.internal (10.42.141.126) 56(84) bytes of data.
From 10.42.249.188 icmp_seq=1 Destination Host Unreachable
From 10.42.249.188 icmp_seq=2 Destination Host Unreachable

the ip of elasticsearch is right.

network is use default mode: managed

**Comment by superseb** [comment]
Healthcheck in initializing usually means no functioning ipsec network, can you check the logs of `network-manager`?

Are you using multiple IP's on a host running the `rancher/agent` container?

Would be nice if you could test this on a newer version too (`v1.6.10`)

**Comment by superseb** [comment]
Please report back if you need help on this.
