### ISSUE TITLE
kubernetes: too many search suffixes in /etc/resolv.conf inside a pod.

### ISSUE THREAD

**Issue by omegarus** [rancher/rancher#8876]
**Rancher versions:**
rancher/server:v1.5.9
rancher/agent:v1.2.2

**Infrastructure Stack versions:**
healthcheck:v0.2.3
ipsec:v0.0.7
network-services:v0.1.2
scheduler:v0.5.1
kubernetes (if applicable):v1.5.4-rancher1-4

**Docker version: (`docker version`,`docker info` preferred)**
```#docker info
Containers: 13
Running: 11
Paused: 0
Stopped: 2
Images: 10
Server Version: 1.12.5
Storage Driver: aufs
Root Dir: /var/lib/docker/aufs
Backing Filesystem: extfs
Dirs: 69
Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
Volume: local
Network: host null bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.19.0-77-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.67 GiB
Name: host2
ID: GJ37:EDR5:XSCJ:HXFA:4A3Z:JEKQ:AMIX:5NAJ:553P:CTLO:BKJQ:MHG4
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
127.0.0.0/8
# docker version
Client:
Version:      1.12.5
API version:  1.24
Go version:   go1.6.4
Git commit:   7392c3b
Built:        Fri Dec 16 02:30:42 2016
OS/Arch:      linux/amd64
 
Server:
Version:      1.12.5
API version:  1.24
Go version:   go1.6.4
Git commit:   7392c3b
Built:        Fri Dec 16 02:30:42 2016
OS/Arch:      linux/amd64
```
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
#cat /etc/os-release
NAME="Ubuntu"
VERSION="14.04.5 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.5 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
#uname -r
3.19.0-77-generic
```
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VMware
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher server + 2 hosts
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes
**Steps to Reproduce:**
My hosts /etc/resolve.conf looks like this:
```
search super1.dom super2.dom
nameserver 192.168.192.1
```
Inside a pod its look like this:
```
search namespace-name.svc.cluster.local svc.cluster.local cluster.local kubelet.kubernetes.rancher.internal kubernetes.rancher.internal rancher.internal super1.dom super2.dom
nameserver 10.43.0.10
options ndots:5
```
**Results:**
Fail to resolve host `pc1` from domain super1.dom.
After some googling i found that resolv.conf search suffix limited to six domains and 256 characters.
There is more than 6 suffixes in search field. So my domains are omitted from search.

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/8172
