### ISSUE TITLE
PowerDNS external-dns Library out of date

### ISSUE THREAD

**Issue by dahendel** [rancher/rancher#8877]
While trying to use the PowerDNS external DNS service I discovered that the used library is out of date. The call should be placed to domain:port/api/v1/servers.... instead the api/v1 is stripped out and the wrong call is made to powerdns. The jgreat library is froked from [https://github.com/waynz0r/go-powerdns](url) which is up to date and seems to be maintained more often. Could we update the library for rancher/external-dns to the better maintained waynz0r/go-powerdns? 

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.0` Cattle: `v0.179.7` UI: `v1.6.1` |
|Access|`Disabled`|
|Orchestration|`Cattle`|
|Route|`service.containers`|

**Comment by dahendel** [comment]
There is actually a pull request for this already [https://github.com/rancher/external-dns/pull/80](url)

**Comment by superseb** [comment]
And merged.
