### ISSUE TITLE
Add container UI issues #2

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#8878]
**Rancher versions:** 5/25

**Issues:**
- [x] In scheduling when I have specific host selected the drop-down seems a bit too close
![image](https://cloud.githubusercontent.com/assets/11514927/26464421/9b05b41c-413c-11e7-820e-422d0c2ccd26.png)

- [x] In scheduling for automatically pick host, is the remove button centered?
![image](https://cloud.githubusercontent.com/assets/11514927/26464474/c54a8554-413c-11e7-9d21-ddddb46063f2.png)

- [x] the Scheduling text for radio buttons are two different colors (I think they should be black as other section have the radio button and tex tin black)
![image](https://cloud.githubusercontent.com/assets/11514927/26465264/71d08114-413f-11e7-91b9-8a7eb4066245.png)

- [x] Health check the text field and type text are same color?
![image](https://cloud.githubusercontent.com/assets/11514927/26464539/f4b4c7f0-413c-11e7-922a-f554ba0ed24e.png)

- [x] Health check section, the When Unhealthy text is too close to check timeout and it seems like a lot of padding between the radio buttons (this seem to only be in scaling group at the moment?)
![image](https://cloud.githubusercontent.com/assets/11514927/26465183/20e6fd46-413f-11e7-8eeb-e3d49590d92f.png)

- [x] Health check section, the two radio button options are different colors (once again this seem to only be in Add scaling group)
![image](https://cloud.githubusercontent.com/assets/11514927/26465664/e3f38b5a-4140-11e7-8295-0019ab437d93.png)
![image](https://cloud.githubusercontent.com/assets/11514927/26465666/e94e3122-4140-11e7-90c7-0ace6ba54fa4.png)

- [x] In command section the Add Option button not centered
![image](https://cloud.githubusercontent.com/assets/11514927/26464594/21fe6716-413d-11e7-808e-65acb6b4b2eb.png)

- [x] In command section when you add a Log Option, the Key/Value should are not aligned with Driver
![image](https://cloud.githubusercontent.com/assets/11514927/26464606/30759a62-413d-11e7-84d0-e9a06cfa7106.png)

- [x] In Networking section, the Resolving Servers & Search domains remove buttons are cut off in front
![image](https://cloud.githubusercontent.com/assets/11514927/26464670/7c022b94-413d-11e7-946a-812a3256d9c9.png)

- [x] In Networking section, the radio button text is blue.  Seems like we might want to make that black to fall in line with the other sections
![image](https://cloud.githubusercontent.com/assets/11514927/26465796/4cd7b0ba-4141-11e7-9d79-eaaf53bbac2c.png)

- [x] In Security section for Device binding, seems like a lot of space?
![image](https://cloud.githubusercontent.com/assets/11514927/26464742/b438fbdc-413d-11e7-8584-f73416d83ddc.png)

- [x] In Volumes section, the Add Volume not adding new line
![image](https://cloud.githubusercontent.com/assets/11514927/26464777/c8e1ed5a-413d-11e7-8272-834b8c2da6d5.png)

- [x] In Volumes section, it seems like a lot of padding?
![image](https://cloud.githubusercontent.com/assets/11514927/26464807/d749bc1a-413d-11e7-90ac-001233dc211d.png)

**Comment by lvuch** [comment]
@tfiduccia resolved not merged

**Comment by tfiduccia** [comment]
Version - 5/30
Verified fixed
