### ISSUE TITLE
Can't add scaling group with healthcheck cause 'recreateOnQuorumStrategyConfig' field is missing

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#8879]
**Rancher versions:** 5/25

**Steps to Reproduce:**
1.  Add scaling group
2.  In health check section fill out, select Check that a TCP connection opens successfully
3.  Add a listening port
4.  Select Re-create, but only if at least [4] containers are healthy
5. Try to Launch Scaling Group

**Results:**  Validation failed in API: strategy is not a valid option.  It looks like 'recreateOnQuorumStrategyConfig' field in missing from API

**Comment by deniseschannon** [comment]
@ibuildthecloud says that recreate on quorum is being dropped so we need to get the UI to no longer show it.

**Comment by tfiduccia** [comment]
Version - 5/20
Verified fixed
