### ISSUE TITLE
Import compose only give me a place for 1 file, but export config still gives me two

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#8881]
**Rancher versions:** 5/25

**Steps to Reproduce:**
1.  Click on Import compose.yml button
2.  Close and go to a scaling group and view it's config

**Results:** There is only 1 place to import a file in import, but when we view or export our config into yml files it gives me two.

**Comment:**  Also should we not be backward compatible and allow the two files?

**Comment by StrongMonkey** [comment]
Need UI changes too cause backend only returns `string` instead of `<String, String>` now.

**Comment by tfiduccia** [comment]
I'm not sure what was done.  But I think this might be confusing for something else.  This bug was supposed to "support single file" yml for 2.0.  Which includes, export, import and UI work.  2.0 does not have any of this support in it.  Added to trello.

**Comment by tfiduccia** [comment]
Version - 2.0 master 8/5
Verified fixed - export single file
