### ISSUE TITLE
using  rancher-flat network  couldn't add more than one host

### ISSUE THREAD

**Issue by 694982827** [rancher/rancher#8884]
*Describe your issue here*

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.0` Cattle: `v0.179.7` UI: `v1.6.1` |
|Access|`Disabled`|
|Orchestration|`Cattle`|
|Route|`hosts.index`|

my Rancher server is on 10.1.139.100/24  and I use  rancher-flat network succussfully add one host 10.1.139.100 on UI:
![image](https://cloud.githubusercontent.com/assets/14134883/26478133/b10c5cfa-41fc-11e7-9cc2-fc61d0bf843c.png)

when I add another host 10.1.139.101:
![qq 20170526102140](https://cloud.githubusercontent.com/assets/14134883/26478239/7815e870-41fd-11e7-9495-993be43aacd7.png)

and the rancher/server exited!

![qq 20170526102843](https://cloud.githubusercontent.com/assets/14134883/26478368/5602c734-41fe-11e7-8320-0df5317ca06b.png)

![image](https://cloud.githubusercontent.com/assets/14134883/26478010/00396594-41fc-11e7-9da9-d36c77b925b8.png)

**Comment by niusmallnan** [comment]
@694982827 
1. I build my test setup by Vagrant. https://github.com/niusmallnan/flatnet-env
2. In rancher-flat mode, you cannot run rancher-server and agent in the same node.
3. All network adapter on the agent node need promisc mode.
