### ISSUE TITLE
Containers wont allocate if label value is too long

### ISSUE THREAD

**Issue by AntoCard** [rancher/rancher#8886]
**Rancher versions:** 1.4.1, 1.5.5

**Docker version:** 17.04.0-ce

**Operating system and kernel:** Ubuntu 16.04

**Type/provider of hosts:** AWS

**Setup details:** HA rancher, RDS Mysql, Traefik LB

**Steps to Reproduce:** Upgrade a service with a label too long, in my case traefik.alias.fqdn with 537 domain entries (service listens in that number of different domains for business reasons)

**Results:**
Container stuck in "allocating"

`Error message: Caused by: java.sql.SQLDataException: (conn:23997) Data too long for column 'value' at row 1`

**Comment by AntoCard** [comment]
Changed `key` field from `VARCHAR(1024)` to `VARCHAR(62300)` for testing and the containers get allocated and running.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
