### ISSUE TITLE
[feature request] Allow a way to mark a service to be removed in rancher template

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#8890]
Currently if you create a new template version for a Rancher Catalog template and in this new version you remove a service that existed in the older version, it will not remove the old service. 

I believe there should be an option in a rancher-compose.yml to flag a service as no longer needed so on updates we can kill services no longer needed.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
