### ISSUE TITLE
"Type" for members of an environment should not include auth provider.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#8891]
Racher server build from master

Setup - ping federator auth enabled setup
Log in as any admin user to a ping federator auth enabled setup.
Go to "Manage Environment"
Under "Access Control" , "Type" for members of an environment is listed as "shibboleth_user?".

<img width="1327" alt="screen shot 2017-05-26 at 11 37 55 am" src="https://cloud.githubusercontent.com/assets/4266958/26508198/a4d28368-4208-11e7-8942-8c9f218fe25c.png">

**Comment by sangeethah** [comment]
With any auth provider , we expect the "type" to be shown as user/group without including auth provider name.

**Comment by tfiduccia** [comment]
Version - 1.6.1-rc10
Now says "User"
Verified fixed
