### ISSUE TITLE
When upgraded DNS service  was left in "upgraded" state , dns service instances get purged in the next few minutes.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#8893]
Rancher versions: v1.6.0

Steps to reproduce the problem:

Upgrade Rancher server to v1.6.1-rc7.

Network-services show "Upgrade Available". Upgrade this stack.
This results in 	network-services-metadata-dns service getting (upgraded from 1.15.0 -> 1.15.1)
Leave the stack in "upgraded" state.
Notice that after few minutes ( wait up to 5 minutes),  containers of the dns service are getting purged.

Expected Behavior:
We should not see containers of service that is in "upgraded" state getting purged.

**Comment by cjellick** [comment]
Another scenario to test:
On an up and running installation of Rancher (with this new code), remove a host and add it back in and make sure it joins networking properly

**Comment by galal-hussein** [comment]
Rancher version: v1.6.0 to v1.6.1-rc8

Upgraded the network-service stack and left it in the upgraded state for 10 minutes, and didn't see any containers getting purged, also i tested @cjellick scenario and made sure the networking is working successfully after joining back the host.
