### ISSUE TITLE
If I remove a catalog then add another with same name, the new one does not show up

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#8894]
**Rancher versions:** 5/25

**Steps to Reproduce:**
1.  Create a local catalog named "catalog1" and point it to a valid url and Save
2.  Under the catalog menu go to that catalog
3.  Go back to manage catalog and delete catalog1 and add Catalog at same time
4.  Name it "catalog1" and point it to a different valid url

**Results:**  Old catalog gets deleted but the new one is not added.  Need to do all deletes first then Adds on Save

**Comment by amy** [comment]
Update: This occurs because on delete and then recreation of the same catalog, the `create catalog` endpoint is hit instead of the `update catalog` endpoint. Thus, the catalog added with the same name and different URL is seen as a duplicate.

**Comment by vincent99** [comment]
It's the delete of a new entry with the same name that causes this; changed to not send a delete when removing a row that didn't come from the server in the first place.

**Comment by tfiduccia** [comment]
Version - 1.6.1-rc10
Verified fixed
