### ISSUE TITLE
Azure AD Integration Not Working - HTTP 400 Bad Request

### ISSUE THREAD

**Issue by zimmertr** [rancher/rancher#8895]
# System Information
**Rancher versions:**
rancher/server: Replicated on both v1.5.5 and v1.5.10

**Infrastructure Stack versions:**
N/A

**Docker version: (`docker version`,`docker info` preferred)**

```
rancher@rancher-controller:~$ docker --version
Docker version 17.05.0-ce, build 89658be
rancher@rancher-controller:~$ docker info
Containers: 6
 Running: 1
 Paused: 0
 Stopped: 5
Images: 5
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 51
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-78-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 6.804GiB
Name: rancher-controller
ID: 7J64:JVNR:BX43:4AFB:HMDW:ZW3X:2O6N:I7FN:MBE4:3CLF:SVI6:2N2W
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

```
rancher@rancher-controller:~$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
rancher@rancher-controller:~$ uname -r
4.4.0-78-generic
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Azure

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node, no hosts. 

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
N/A

# The Error
**Steps to Reproduce:**

**1) Create Application Registration in Azure** 
-Navigate: Azure Active Directory -> App Registrations -> New Application Registration
-Application Type: Native
-Sign-on URL: rancher.domain.io

**2) Configure Application Registration:**
-Navigate: Azure Active Directory -> App Registrations -> Your App -> Required Permissions -> Windows Azure Active Directory API
-Select all Delegated Permissions
-Save your changes & Grant Permissions to the API

**3) Create Active Directory Service Account**
-Navigate: Azure Active Directory -> Users and Groups -> All Users -> New User
-User name: ad_service@domain.com
-Groups: Domain Group
-Directory Role: Service administrator & User Administrator
-Save
-Navigate: portal.azure.com -> Sign in as new user and set a new password

**4) Configure Rancher Server**
-`docker run -d --restart=unless-stopped -p 8080:8080 rancher/server:v1.5.10`
-Navigate: https://ip.add.re.ss:8080/v1/settings/logback.root.level
-Click Edit and replace INFO with TRACE
-Show Request -> Send Request
-Restart Rancher Server: `docker restart >containerid<`
-Connect to the Rancher Server container: `docker exec -it >containerid< bash`
-Tail the debug log: `tail -F /var/lib/cattle/logs/cattle-debug.log`

**5) Configure Azure AD** 
-Wait 1 minute and Navigate: https://ip.add.re.ss:8080/
-Navigate: Admin -> Access Control -> Azure AD

(Sidenote: The next two fields should be renamed in your application/documentation. It is very confusing since Application ID appears above Object ID on Azure, but Tenant ID appears above Client ID in Rancher. And they're named differently too...)

-Copy `Object ID` from Azure Application Registration to `Tenant ID` in the first field.
-Copy `Application ID` from Azure Application Registration to `Client ID` in the second field.
-Insert domain into third field.
-Provide ad_service@domain.com credentials to fields four and five.
-Provide personal user account credentials to fields six and seven.
-Click `Authenticate with Azure`

**6) Experience Login Failure**
-Navigate: http://ip.add.re.ss:8080/login
-Open Developer Console in your browser to view HTTP errors
-Try and sign in as any user in the domain, or even your service account
-Rancher verifies credentials are correct, appears to login, and loops back to the login page. Invalid credentials are always rejected. Valid AD credentials are always `accepted` for lack of a better word.

**Results:**

Login is accepted by Rancher and then immediately jumps back to the login prompt. Rancher must be able to perform an identify lookup in Azure AD because it can tell if credentials are correct or not. Incorrect credentials won't be accepted by the form and it will simply say `Username or Password Incorrect`

Several HTTP error occur at different times. 400, 401, and 500. 

Several 400 errors in trace logs. Predominantly `Failed to get Azure user account info by Id. io.github.ibuildthecloud.gdapi.exception.ClientVisibleException: Error from Azure: 400` and 

```
Response from Azure API: HTTP/1.1 400 Bad Request 
Error received from Azure: null 
Error Description received from Azure: null 
Got error from Azure. io.github.ibuildthecloud.gdapi.exception.ClientVisibleException: Error from Azure: 400
``` 

## Log Files and Screenshots
1) Developer Console post login attempt: http://i.imgur.com/WMJjStl.png
2) Debug Trace while Enabling Azure AD Access Control: https://goo.gl/RpCPDs
3) Debug Trace during Login Attempt: https://goo.gl/6bJF9q

## Possible issues
1) Azure might be rejecting requests from servers without valid SSL certificates? 
2) Possible misconfiguration on the Azure AD side? I have tried this as both the service account I created here and as an AD user that is an owner in the subscription

## Attempted Troubleshooting steps
1) Have tried using a user account that is an `Owner` of the Azure subscription instead of a service account. Still receive 400 errors. 
2) Have tried all of this using SSL termination behind an NGINX reverse proxy as well. This issue was made with an example running over HTTP. However, I first experienced this issue on my Rancher Server that was using SSL Termination behind an NGINX reverse proxy though. SSL Labs gave it a A- grade as I was using the full chain and everything.
3) Reached out in Public slack channel for support.
4) Read countless Google Search results via variations of this query: https://goo.gl/hBrqZs

Please help. :(

**Comment by zimmertr** [comment]
I've noticed at least two other similar issues to this one on the Issue Tracker. Although I believe that both of them are unique in that they are using Multi-Factor Authentication and we are not. So I thought it would be better to create a new issue rather than commenting on theirs. 

https://github.com/rancher/rancher/issues/5772

**Comment by zimmertr** [comment]
Is it possible that the underlying Linux host that the Rancher Server container is running on must be joined to the domain it's trying to authenticate against?

**Comment by superseb** [comment]
@tfiduccia Is this something you can check/verify?

**Comment by prachidamle** [comment]
@zimmertr can you try few requests to Azure AD using a REST tool (like Advanced Rest Client tool for Chrome)? We would know if the issue is outside of Rancher or not, depending on if these requests error out/work.

1. Login to Azure login using Advance rest client tool and check what response you get from Azure.
Here is a screenshot of what the request should look like, you would need to provide the clientId, username and password and URL encode the special characters if any.
<img width="1071" alt="azure_rest_login" src="https://cloud.githubusercontent.com/assets/1470602/26605504/2b5b7bbe-4543-11e7-9003-64d9aeb892f1.png">

2. If the login works, copy the access token you get back from Azure and use it to search for your user and group details as below (This is the request that is seen to be failing in Rancher logs):

- a. To search your user:
   - Do a HTTP GET request to 
https://graph.windows.net/(tenantId)/users/feb4e488-6faa-4852-91c2-3a80f13ecbda?api-version=1.6
   - Set the following request headers:
Accept: application/json
Authorization: Bearer <access_token received in login above>

- b. To look for your group
   - Do  a HTTP GET request to 
https://graph.windows.net/(tenantId)/groups/321cf82a-e6fa-4349-87b1-c8fce7298e47?api-version=1.6
   - Set the following request headers:
Accept: application/json
Authorization: Bearer <access_token received in login above>


- And Check what response you get for the user/group search.

**Comment by zimmertr** [comment]
Hi @prachidamle , thank you very much for your reply. I performed the POST and I did receive an error `invalid_grant`. What exactly is graph.windows.net? I noticed it was passed as a string during the POST. Was I supposed to edit this to something specific on my end? Sorry, I'm still relatively amateur at working with REST APIs. 

```
{
"error": "invalid_grant",
"error_description": "AADSTS50034: To sign into this application the account must be added to the graph.windows.net directory. Trace ID: 00a2b0b8-f9c5-46d4-b53f-e57da11e1700 Correlation ID: af255cde-08ae-4418-85c6-454af127efbf Timestamp: 2017-05-31 14:46:08Z",
"error_codes": [
  50034
],
"timestamp": "2017-05-31 14:46:08Z",
"trace_id": "00a2b0b8-f9c5-46d4-b53f-e57da11e1700",
"correlation_id": "af255cde-08ae-4418-85c6-454af127efbf"
}
```

**Comment by zimmertr** [comment]
Hi @prachidamle, thank you very much for your response. It has been incredibly valuable to me. It appears that the error is that the service account that I have created has not been added to the graph.windows.net directory. I've done some research on the Graph API and I understand that it provides access to AD via Odata endpoints. 

```
{
"error": "invalid_grant",
"error_description": "AADSTS50034: To sign into this application the account must be added to the graph.windows.net directory. Trace ID: 00a2b0b8-f9c5-46d4-b53f-e57da11e1700 Correlation ID: af255cde-08ae-4418-85c6-454af127efbf Timestamp: 2017-05-31 14:46:08Z",
"error_codes": [
  50034
],
```

Perhaps there is still an issue with fully understanding how this all fits together, but isn't the Graph API a tool used to perform lookups against AD? Is the error misleading me into thinking that I have to add some sort of Graph role to my service user account? Google isn't helping a whole lot with this unfortunately, so I'm sorry for my naivety.

**Comment by zimmertr** [comment]
Hi @prachidamle, thank you very much for your response. It has been incredibly valuable to me. It appears that the error is that the service account that I have created has not been added to the graph.windows.net directory. I've done some research on the Graph API and I understand that it provides access to AD via Odata endpoints.

```
{
"error": "invalid_grant",
"error_description": "AADSTS50034: To sign into this application the account must be added to the graph.windows.net directory. Trace ID: 00a2b0b8-f9c5-46d4-b53f-e57da11e1700 Correlation ID: af255cde-08ae-4418-85c6-454af127efbf Timestamp: 2017-05-31 14:46:08Z",
"error_codes": [
  50034
],
```

Perhaps there is still an issue with fully understanding how this all fits together, but isn't the Graph API a tool used to perform lookups against AD? Is the error misleading me into thinking that I have to add some sort of Graph role to my service user account? Google isn't helping a whole lot with this unfortunately, so I'm sorry for my naivety. My service user has the Directory Role Limited Administrator with the subroles Service Administrator and User Administrator. Beyond this, I'm not sure what needs to be done.

Thank you again for your help, I really appreciate it. Rancher is a very awesome organization.

**Comment by zimmertr** [comment]
@prachidamle 

Hi, okay so I've managed to obtain an Access Token via Step 1) from your instructions. However, when I try and perform a GET via Step 2A) or Step 2B), it bombs out with `Invalid domain name in the request url.`

I've replaced the `tenantid` portion of the URL. Nothing else should be mandatory, correct? Where do we go from here?

**Comment by bejonwe** [comment]
@zimmertr I'm experiencing the same problem. Have you been able to fix this?

**Comment by zimmertr** [comment]
I'm fairly certain this was user error pertaining to the application not having requisite permissions to perform read actions against the directory. Closing this ticket as it is no long relevant and appeared to be my fault to begin with.
