### ISSUE TITLE
If Community and Library are disabled in Global I still can't use them locally

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#8896]
**Rancher versions:** 5/25

**Steps to Reproduce:**
1.  Disable Library and Community catalogs in setting
2.  Go to Catalog and try to create a Library and Community catalog locally (though Manage)

**Results:**  Will give me a "name is not unique" error.  Should not do that.
![image](https://cloud.githubusercontent.com/assets/11514927/26509828/673a7a5e-420f-11e7-82b8-367cbd1eee78.png)

**Comment by amy** [comment]
Update: This seems to be a UI validation issue. If I disable the library and community catalogs in the ui and hit save. Then, via the api, add an environment catalog with those names, it works.

**Comment by westlywright** [comment]
@tfiduccia can you retest this in 1.6 and master? I was able to disable global catalogs then add a catalog called library in the env catalog modal. I also created a new env and saw that the globals were disabled for that one as they should be.

**Comment by tfiduccia** [comment]
Version - v1.6.3-rc1
Verified fixed
