### ISSUE TITLE
Creating a second catalog with same name, when I remove it, it deletes both catalogs

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#8897]
**Rancher versions:** 5/25

**Steps to Reproduce:**
1.  Create a local catalog and name it "catalog1", Save
2.  Go back to manage and create another catalog call "catalog1" and try to save
3.  After unique name error.  Delete the catalog and Save

**Results:**  Both catalogs are gone.  Really only the one that was erroring should be removed and the one that was previously saved should still be there.

**Comment by amy** [comment]
Update: I also think this should be a UI situation. If the API is sent a delete request. It will delete the entry with the matching environment ID and name. 

In terms of whether the delete request is sent, I think the UI should resolve that.

**Comment by vincent99** [comment]
Isn't this the same as #8894 ?

**Comment by tfiduccia** [comment]
Version - 1.6.1-rc10
Verified fixed
