### ISSUE TITLE
A PingFederate UI option for authentication

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#8899]
Currently we use Shibboleth option to configure PingFederate since it has basically the same configuration, but there is no separate option for using PingFederate.

cc @mrajashree

**Comment by vincent99** [comment]
There should be separate auth configs for each system like this that we support so that we don't get burned when it later turns out that there is actually a difference needed in configuration.  If they're 100% the same then they can share the same code behind the scenes.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
