### ISSUE TITLE
Concurrent sessions are not logged out immediately even after a new login occur

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#8901]
**Rancher versions:**
rancher/server: master build

**Steps to Reproduce:**
- Enable `auth.limit.concurrent.sessions`.
- Open one user session and then open another new session for the same user.

**Results:**

In the first session you will not be logged out immediately, and you will still see the resources created until one of the following is done:
1.Manual refresh
2. request a new url
3. After 5 minutes.

**Comment by cjellick** [comment]
Fix merged. Need to backport to 1.6

**Comment by cjellick** [comment]
Available in the v1.6 branch of cattle for testing

**Comment by galal-hussein** [comment]
Rancher server: master

Steps to validate:

- Enable Github Authentication
- Login in one browser and set the option in advanced setting to true
`api.auth.restrict.concurrent.sessions=true`
- Login in another browser

Results: The first session is immediately logged off automatically.
