### ISSUE TITLE
rancher-agent & rancher-agent-bootstrap are in both stand-alone and default stack

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#8902]
**Rancher versions:** 5/25

**Steps to Reproduce:**
1.  Create new account
2.  Add host
3.  Wait for rancher-agent and rancher-agent-bootstrap to start/active/stop

**Results:**  Both of those containers are added to Default but the UI doesn't show them in that stack.  In hosts, it shows up under a section called Stand-alone and they don't show up at all in Scaling group.
![image](https://cloud.githubusercontent.com/assets/11514927/26516155/e7d67bfa-4236-11e7-8de2-64e20d429459.png)

**Comment by StrongMonkey** [comment]
Isn't rancher-agent-bootstrap being removed? I remember darren added "--rm" to add hosts command.

**Comment by tfiduccia** [comment]
All containers I create and try to put in Default are showing up in a standalone section for hosts.

**Comment by tfiduccia** [comment]
Version - 5/30
Verified fixed
