### ISSUE TITLE
Host disconnected (Timeout getting IP address) on Ubuntu 16.04 with Rancher 1.6

### ISSUE THREAD

**Issue by dj-hedgehog** [rancher/rancher#8903]
**Rancher versions:**
rancher/server: 1.6
rancher/agent: 1.2.2

**Infrastructure Stack versions:**
healthcheck: 0.3.1
ipsec: net:holder (?)
network-services: network-manager 0.7.0, metadata 0.9.1
scheduler: 0.7.5

**Docker version: (`docker version`,`docker info` preferred)**

```
Containers: 11
 Running: 10
 Paused: 0
 Stopped: 1
Images: 9
Server Version: 17.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-78-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 11.73 GiB
Name: v22017053660349765
ID: GXV4:HZIG:5TGV:AN3B:YKZH:GIBX:MBCM:LJJM:CA2Y:IQGS:VSYR:V4RN
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)** 

4.4.0-78-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

Bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

single node rancher, internal DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

Cattle

**Results:**

Host is disconnected, Scheduler disconnected

Agent log shows the infamous "Timeout getting IP address":

```
time="2017-05-27T08:24:29Z" level=error msg="Error processing event" err=Timeout getting IP address eventId=234e6368-354c-4592-aa40-59fd5fdc22ed eventName=compute.instance.activate resourceId=1ihm19
```

**Comment by dj-hedgehog** [comment]
I am very sorry. A co-worker added the host but forgot to specify the IP. I re-added the host with public IP and it fixed the problem. Good job, Rancher team.

**Comment by danielmotaleite** [comment]
Just to complete this, as it is not clear and to help others.

the missing IP is the "Host Registration URL" dns/IP in the rancher server settings page
