### ISSUE TITLE
Creating server with volume: Operating system error number 13 in a file operation.

### ISSUE THREAD

**Issue by JulianKingman** [rancher/rancher#8904]
**Rancher versions:**
rancher/server: 1.6
rancher/agent: n/a

**Docker version:  17.05.0-ce**

**Operating system and kernel: 16.04.2 LTS (Xenial Xerus)**

**Type/provider of hosts: Digital Ocean droplet (1gb)**

**Steps to Reproduce:**
I'm trying to set up a data container, so I run this: `docker run -d rancher/server:latest`, but it exits right away with the following error:
````
170527 16:06:43 [Note] /usr/sbin/mysqld (mysqld 5.5.53-0ubuntu0.14.04.1) starting as process 24 ...
170527 16:06:43 [Warning] Using unique option prefix myisam-recover instead of myisam-recover-options is deprecated and will be removed in a future release. Please use the full name instead.
170527 16:06:43 [Note] Plugin 'FEDERATED' is disabled.
/usr/sbin/mysqld: Can't find file: './mysql/plugin.frm' (errno: 13)
170527 16:06:43 [ERROR] Can't open the mysql.plugin table. Please run mysql_upgrade to create it.
170527 16:06:43 InnoDB: The InnoDB memory heap is disabled
170527 16:06:43 InnoDB: Mutexes and rw_locks use GCC atomic builtins
170527 16:06:43 InnoDB: Compressed tables use zlib 1.2.8
170527 16:06:43 InnoDB: Using Linux native AIO
170527 16:06:43 InnoDB: Initializing buffer pool, size = 128.0M
170527 16:06:43 InnoDB: Completed initialization of buffer pool
170527 16:06:43  InnoDB: Operating system error number 13 in a file operation.
InnoDB: The error means mysqld does not have the access rights to
InnoDB: the directory.
InnoDB: File name ./ibdata1
InnoDB: File operation call: 'create'.
InnoDB: Cannot continue operation.
````
I have an sql backup that I want to load into the container volume, but I can't get it to initialize for me to do that. Ideas?

Edit: Also happens when bind-mounting like this `docker run -d -v <host_vol>:/var/lib/mysql --restart=unless-stopped -p 8080:8080 rancher/server`

**Comment by aemneina** [comment]
You most likely need to change the permissions for the mysql directory, to have the correct ownership. Check [here](https://docs.rancher.com/rancher/v1.6/en/upgrading/#upgrading-a-single-container-non-ha---bind-mounted-mysql-volume) and let us know if that does the trick.

**Comment by JulianKingman** [comment]
After carefully following those instructions, I got it working, thanks!
Another thing that I ran into was a bunch of errors like this:
```
170529 12:39:06 [Note] /usr/sbin/mysqld (mysqld 5.5.53-0ubuntu0.14.04.1) starting as process 25 ...
170529 12:39:07 [Note] /usr/sbin/mysqld (mysqld 5.5.53-0ubuntu0.14.04.1) starting as process 24 ...
170529 12:39:07 [Note] /usr/sbin/mysqld (mysqld 5.5.53-0ubuntu0.14.04.1) starting as process 24 ...
170529 12:39:08 [Note] /usr/sbin/mysqld (mysqld 5.5.53-0ubuntu0.14.04.1) starting as process 24 ...
170529 12:39:09 [Note] /usr/sbin/mysqld (mysqld 5.5.53-0ubuntu0.14.04.1) starting as process 24 ...
170529 12:39:11 [Note] /usr/sbin/mysqld (mysqld 5.5.53-0ubuntu0.14.04.1) starting as process 24 ...
170529 12:39:15 [Note] /usr/sbin/mysqld (mysqld 5.5.53-0ubuntu0.14.04.1) starting as process 24 ...
170529 12:39:22 [Note] /usr/sbin/mysqld (mysqld 5.5.53-0ubuntu0.14.04.1) starting as process 24 ...
```
I think it was related to having restored the files using mariadb, instead of just copy/pasting them directly. After removing mariadb (from server) and copy/pasting the files, it worked. Just upgrading the agents.
