### ISSUE TITLE
UI/API Show rancher servers failure to connect to DB

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#8906]
**Steps to Reproduce:**
Fire up a server with invalid db host or credentials. View the UI for server. In this case it was post upgrade where the system used github auth. the user was able to login, but functionality was hindered. It'd be good to have a banner showing the server was failing to connect to the DB.

**Comment by vincent99** [comment]
The UI has no way to know this.  And I find it hard to believe you can login when the token gets written to the database...
