### ISSUE TITLE
Add configurability to infrastructure upgrade behavior

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#8907]
Issue, each environment in this specific use case has only 2 hosts. When network-services stack upgrade the batch size effectively takes out DNS and metadata across the hosts. Ideally this could be configurable to only have 1 go down at a time. Also have the pull happen before cutting over services to make the outage window smaller.

**Comment by janeczku** [comment]
Similarly, when there are  many environments or environments with a lot of hosts, the pre-set small batch size of just 1 or 2 results in prolonged maintenance windows.
Users might want to bump the batch size in these cases.

**Comment by vincent99** [comment]
This is already in 2.0, the upgrade options are a property of the service that is persisted instead of a one-time input to the upgrade action.

**Comment by janeczku** [comment]
> upgrade options are a property of the service that is persisted instead of a one-time input to the upgrade action

@vincent99 How would users change the upgrade options (batch size) for infra services that are coming from Ranchers catalog?

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
