### ISSUE TITLE
Catalog that previously ran, fail with "Error with unsupported config option" error

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#8909]
**Rancher versions:** v1.6.1-rc8

**Steps to Reproduce:**
1.  Add my catalog
2.  Run the Config test 2 or Config test 3 catalogs

**Results:**  Error (Unsupported config option for version service: 'questions' Unsupported config option for name service: 'version' Unsupported config option for service: 'name')

**These catalogs were tested for config changed in 1.5.10 and were working at that time.**

**Comment by deniseschannon** [comment]
Both Config Test 2/3 are invalid as expected. These catalogs are invalid as you can't put the `.catalog` info under the `services` key. 

@tfiduccia Can you fix your catalogs?

**Comment by gizmotronic** [comment]
I was able to fix this simply by moving ```.catalog``` out from under the ```services``` key as @deniseschannon suggested. Is there documentation on this somewhere that I've missed?
