### ISSUE TITLE
how to view the stickiness policy on rancher UI with read-only user 

### ISSUE THREAD

**Issue by borntorock** [rancher/rancher#8911]
We have stickiness policy enabled on the Rancher Load Balancers, but seems there is no option to view whether the stickiness policy has been enabled or not with the read-only user created. 

Though the admin users and members can view the policy on clicking the Edit / Update button on the rancher load balancer service, but how the read-only users can view via the Rancher UI.

**Comment by borntorock** [comment]
Ahh, Looks like the user can click on view config of required stack and then in the rancher-compose.yml file can see the stickiness policy.

But, the preferrable way would be to have an extra tab near to Labels , balancer rules, and others which shows the stickiness policy of the rancher LBs.

**Comment by vincent99** [comment]
2.0 shows all the details of a balancer service, including these.
