### ISSUE TITLE
HA Kubernetes enhancements

### ISSUE THREAD

**Issue by joshwget** [rancher/rancher#8914]
- [ ] Run all Kubernetes orchestration components as global services. This is the simplest approach for adding redundancy across multiple hosts.
- [ ] Same as above but for etcd, as long as this fits in with the etcd operator changes from @LLParse 
- [ ] Remove the "isolated planes" configuration and replace with dynamic configuration based on hosts deployed with particular labels.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
