### ISSUE TITLE
Please update the troubleshooting doco in rancher 1.5 to show the default subnet

### ISSUE THREAD

**Issue by juliangamble** [rancher/rancher#8916]
**Rancher versions:**
rancher/server: 1.5.10

**Infrastructure Stack versions:**
rancher/healthcheck:v0.2.3
rancher/net:v0.11.2
 image: rancher/metadata:v0.9.1
image: rancher/dns:v0.14.2
image: rancher/network-manager:v0.6.6
rancher/scheduler:v0.7.5

Hi Denise, 

Thanks for all your patient work supporting the rancher community. 

A documentation request: Here you explicitly state that the default subnet in rancher is 10.42.0.0
http://docs.rancher.com/rancher/v1.0/en/faqs/troubleshooting/

Here you removed it!
http://docs.rancher.com/rancher/v1.5/en/faqs/troubleshooting/
(I know the mechanism has changed - but knowing that the default subnet is 10.42.0.0 is really critical!)

Could you please put the default subnet back? (For all those people who need to make the mental jump saying "my network is 10.42.* and docker's default subnet is 10.42.* and those iptable rules are doing to clash! I really need to change the docker subnet to 10.32.* !")

(It would also be helpful if you could add additional details on editing the template files (which ones - which entry)

Something like - see this:

    defaultNetwork:
        dns:
        - 169.254.169.250
        dnsSearch:
        - rancher.internal
        hostPorts: true
        name: ipsec
        subnets:
        - networkAddress: 10.42.0.0/16

Change this to this:

        - networkAddress: 10.32.0.0/16

And whether or not to touch this:

    services:
      router:
        network_driver: &id001
          cniConfig:
            10-rancher.conf:
              bridge: docker0
              bridgeSubnet: 10.42.0.0/16

to this

          bridgeSubnet: 10.32.0.0/16

Cheers
Julian

**Comment by deniseschannon** [comment]
Thanks @juliangamble for the feedback. I've added some docs to make it more clear on how you can edit the configuration of the infrastructure service. 

Also, our docs are open source and you can always make a PR at https://github.com/rancher/rancher.github.io :)
