### ISSUE TITLE
SSH using RSA key downloaded from machine config Permission denied (publickey)

### ISSUE THREAD

**Issue by jwarder** [rancher/rancher#8917]
**Rancher versions:**
rancher/server: RancherOS v0.8.1 (4.9.12) V1.5.8
rancher/agent:  RancherOS v1.0.1 (4.9.24)

**Docker version: (`docker version`,`docker info` preferred)**
Docker version 1.12.6, build 78d1802 (Server)
Docker version 17.03.1-ce, build c6d412e (Agent)

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
RancherOS 

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
- Add host EC2 using ami-75cbcb13, ssh user rancher
- Download machine config
- run SSH -i id_rsa rancher@IP

**Results:**
Permission denied (publickey).

This has always worked until I upgraded the server to V1.5.8

**Comment by superseb** [comment]
Is this still an issue? I don't recall an issue on `docker-machine`, providing this issue. Please report back if we can help you.
