### ISSUE TITLE
Rancher UI does not set X-Api-CSRF if using Apache as SSL-Proxy

### ISSUE THREAD

**Issue by irockel** [rancher/rancher#8918]
**Rancher versions:**
rancher/server: 1.6.0
rancher/agent: 1.2.2

**Infrastructure Stack versions:**
healthcheck: 0.3.1
ipsec: net 0.11.2
network-services: metadata 0.9.1, network-manager: 0.7.0
scheduler: 0.7.5
kubernetes (if applicable): n/a

**Docker version: (`docker version`,`docker info` preferred)**
Containers: 13
 Running: 10
 Paused: 0
 Stopped: 3
Images: 30
Server Version: 17.05.0-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.16.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 20
Total Memory: 125.8GiB
Name: de-cg1-docker03.1worldsync.de
ID: XTA3:KPC2:45EA:A7NV:HUMH:XQIM:W43C:N2YW:AXR6:SYK7:Y7AT:3SL2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

3.10.0-514.16.1.el7.x86_64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node Rancher with internal DB using Active Directory for authentication

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Set up Apache with HTTPS using the Virtual Host configuration as mentioned here:

https://docs.rancher.com/rancher/v1.6/en/installing-rancher/installing-server/basic-ssl-config/#example-apache-configuration

Activate Active Directory Authentication configured.

Try to login with any valid user via the HTTPS proxy.

**Results:**
If trying to login through SSL Proxy a "CSRF header and cookie do not match" is logged and reported in the Login Match.

Using the direct way to log in (via HTTP, no Proxy) it works as expected.

Using a HTTP Trace Tool in the Browser comparing the successful and the failed request, one can see the X-Api-CSRF Header is missing in the Requests using the Apache SSL Proxy:

**Successful Request (partly)**

POST http://<docker-host>:8099/v2-beta/token
Origin: http://<docker-host>:8099
x-api-action-links: actionLinks
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/58.0.3029.110 Chrome/58.0.3029.110 Safari/537.36
content-type: application/json
x-api-no-challenge: true
accept: application/json
x-api-csrf: 3209AD4010
Referer: http://<docker-host>:8099/login
Accept-Encoding: gzip, deflate
Accept-Language: de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4,nb;q=0.2
Cookie: PL=rancher; CSRF=3209AD4010

**Failed Request (partly)**

https://<https-virtual-host>/v2-beta/token

POST https://<https-virtual-host>/v2-beta/token
x-api-no-challenge: true
accept: application/json
Origin: https://<https-virtual-host>
x-api-action-links: actionLinks
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/58.0.3029.110 Chrome/58.0.3029.110 Safari/537.36
content-type: application/json
Referer: https://<https-virtual-host>/login
Accept-Encoding: gzip, deflate, br
Accept-Language: de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4,nb;q=0.2
Cookie: PL=rancher; CSRF=91B3593D26

The only log message I get is:

[i.g.i.g.r.handler.CSRFCookieHandler ] Request's CSRF header did not match cookie

(from cattle-debug.log)

I'm pretty much out of ideas what to do here...

**Comment by vincent99** [comment]
This seems hard to believe, the UI has absolutely no logic around it (https://github.com/vincent99/ui/blob/1.6-dev/app/mixins/store-tweaks.js#L16-L19) and there are lots of people using Apache.  Do you have other config that is changing the cookies to `httponly` or something?  That's all I can think of that would explain there being a cookie in the request but the UI doesn't see it and therefore doesn't set the header.

**Comment by irockel** [comment]
This was indeed the problem, this is a central Apache for a lot of services and deep down in its configuration there was a:

`Header edit Set-Cookie ^(.*)$ $1;HttpOnly;Secure`

The admin removed the "HttpOnly" and now it is properly working. Thanks a lot for the hint! I didn't see the HttpOnly while debugging the first time.
