### ISSUE TITLE
Io.rancher.container.ip Docker label not set on containers

### ISSUE THREAD

**Issue by lukewhiting** [rancher/rancher#8919]
**Rancher versions:**
rancher/server: 1.5.9
rancher/agent: 1.2.2

**Infrastructure Stack versions:**
healthcheck: 0.2.0
ipsec: holder
network-services: 0.6.6 & 0.91 (Metadata)
scheduler: 0.7.5

**Docker version: (`docker version`,`docker info` preferred)**
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:14:09 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:14:09 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

Kernal: 4.4.0-1017-aws

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher, external db

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Deploy stack, go to it's container, see that Io.rancher.container.ip is sometimes missing

**Results:**
Here's a screenshot of one of our ElasticSearch containers:

![screenshot from 2017-05-30 16-35-11](https://cloud.githubusercontent.com/assets/897881/26591728/79182f4c-4556-11e7-8211-5ef76204018a.png)

You can see that the Io.rancher.container.ip label is missing. This is a major problem for us as we use DataDog for our monitoring and it relies on this label being present as part of its service detection.

As far as I can see in the documentation this label should be set for all containers and container the current assigned managed IP address.

**Comment by superseb** [comment]
@lukewhiting Is there more context to when this is happening? "Sometimes missing" is that 1 stack sometimes it does, sometimes it does not? How often does this occur?

**Comment by lukewhiting** [comment]
Looking through the containers it seems to be isolated to just that stack... All containers in that stack seem to be missing it however other stacks in the same environment seem to be fine, including containers running on the same boxes as the "infrastructure" stack that is missing it.

**Comment by ilucker** [comment]
I Have the similar issue. Whenever i use "Retain IP" option, io.rancher.container.ip label not set.

**Comment by mowday** [comment]
@ilucker is correct, when setting "Retain IP" the `io.rancher.container.ip` isn't set. This is a bug right, or is there a reasoning behind this?

**Comment by 0ff** [comment]
This turned out to be a rather huge problem for us as well - as we use this label to identify containers in prometheus, we effectively can't track instances that use `retain_ip: true`.

It seems this is due to the fact that the label is added on instance.create in the rancher-agent (this is where it should be added https://github.com/rancher/agent/blob/v0.12.0/core/compute/compute_unix.go#L159) and my guess is that a **retained** ip is not known *yet*.

The rancher-agent does not seem to differentiate between retained/non-retained containers so I guess the *bug* is actually within the service that sends out the `compute.instance.activate` event (https://github.com/rancher/agent/blob/v0.12.0/handlers/common.go#L39), as it should populate the `instanceHostMap.instance.nics[0].ipAddresses`. (https://github.com/rancher/agent/blob/v0.12.0/handlers/test_events/instance_activate_basic#L74)

**Comment by lukewhiting** [comment]
After more investigation this does indeed seem to happens when retain IP is set. Is there any update on this issue as it continues to cause problems for services that depend on that label for container IP discovery?

**Comment by claudeatsafe** [comment]
@superseb any updates on this? Is there a workaround to set that label manually? It breaks the datadog integration.

**Comment by ofhk** [comment]
We also had this issue and we use this workaround for services with scale 1. if that does not work we clone the service, like aerospike1, aerospike2, aerospike3. After the service is up we update the service to enable "retain ip" and we add manually the label io.rancher.container.ip=xx.xx.xx.xx/xx with IP the container has received. Not beautiful but it works.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
