### ISSUE TITLE
80Gb used by rancher server (100%)

### ISSUE THREAD

**Issue by ciokan** [rancher/rancher#8920]
rancher/server: 1.5.6
ubuntu 16.04 - DigitalOcean
single node + mysql server on same host

Any idea what I can do to prevent this? Is there something I can do to reduce the amount of storage used or I have to simply..throw more GB at this thing? 80Gb seems like a lot for an application though.

**Comment by vincent99** [comment]
Look at where the space is used?  We use far smaller instances for day-to-day QA.

**Comment by ciokan** [comment]
Good catch. nginx access logs. I cleared `/var/log/nginx.log` but didn't look inside `/var/log/nginx`. Thank you.
