### ISSUE TITLE
Portworx needs special characters for volume name (corresponds to meta-data)

### ISSUE THREAD

**Issue by jsilberm** [rancher/rancher#8925]
**Rancher versions:**
rancher/server: 1.5.5
rancher/agent: 1.2.2

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
[root@my-centos-3 ~]# docker info
Containers: 9
 Running: 9
 Paused: 0
 Stopped: 0
Images: 9
Server Version: 17.03.1-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.16.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.702 GiB
Name: my-centos-3
ID: AUID:D7C2:KA65:HEHD:WB5X:FWSR:YF5Z:O2PK:GFRI:AOFB:FCW4:SR2C
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: wilkins
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-ip6tables is disabled
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
3.10.0-514.16.1.el7.x86_64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
DO
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Make sure to install Portworx from the Rancher Catalog

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
N/A
**Steps to Reproduce:**
"Add Container".   Use default ubuntu:14.04.3
"Volumes".   "Add Volume"
"Volume Driver" :  "pxd"

Portworx provides "storage on demand".   You don't have to create volumes in advance,  you can create them at run-time by providing all the appropriate volume meta-data  (see https://docs.portworx.com/scheduler/mesosphere-dcos/inline.html) 

For example, the volume name can be :   "name=jvol,size=10,repl=3"

**Results:**
This should work fine.   But currently throws an error:
"Volume names can only contain letters, numbers, hyphen, underscore, and dot."

Please fix this --- atleast when "volume driver = pxd".

Thanks.

**Comment by vberetti** [comment]
I think this should be fixed by #8646

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
