### ISSUE TITLE
Can't login to the UI after enable authentication

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#8926]
**Rancher versions:**
rancher/server: master build

**Docker version: (`docker version`,`docker info` preferred)**
1.12
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
ubuntu 16.04
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
GCE
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
- Enable Github or LDAP authentication
- Try to login

**Results:**

After logging in i get immediately logged out from the setup, a DELETE call happens immediately after logging in to  v2-beta/token/current

**Comment by mrajashree** [comment]
@vincent99 @cjellick The access control creates a token in the auth_token table. And then a DELETE on `v2-beta/token/current` is getting called. This call is not made from the cattle code, and it deletes the created token.

**Comment by vincent99** [comment]
This is because the `backups` and `snapshots` APIs were deleted, and if there's an error loading stuff the UI needs on pageload it kicks you out.

**Comment by mrajashree** [comment]
@vincent99 oh, I see

**Comment by tfiduccia** [comment]
Version - v1.6.1-rc10
Verified fixed
