### ISSUE TITLE
Bad Handshake

### ISSUE THREAD

**Issue by ghost** [rancher/rancher#8927]
Currently receiving the error message below.

time="2017-05-30T21:41:19Z" level=error msg="Failed to connect to proxy." error="websocket: bad handshake"
time="2017-05-30T21:41:19Z" level=error msg="websocket: bad handshake"
time="2017-05-30T21:41:24Z" level=info msg="Connecting to proxy." url="wss://domain .cloud/v1/connectbackend?token=eyJhbGciOiJSUzI1NiJ9.eyJyZXBvcnRlZFV1aWQiOiI0NGNlMTY3Yy01NTc4LTRiZmQtNTUzZS1kMTgwMzBlYWFhZWYiLCJzdWIiOiJjYXR0bGUiLCJraWQiOiJkZWZhdWx0IiwiaXNzIjoiaHR0cDpcL1wvY2F0dGxlL

The Shell and Stats are currently not working in the UI. 

Has anyone got any thoughts?

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.0` Cattle: `v0.179.7` UI: `v1.6.1` |
|Access|`github` `admin`|
|Orchestration|`Cattle`|
|Route|`admin-tab.processes.list`|

**Comment by LLParse** [comment]
Looks like there might be HTTP load balancer or similar in front of your Rancher server. You need to use TCP load balancer for websockets to function. Relevant documentation [here](http://docs.rancher.com/rancher/v1.6/en/installing-rancher/installing-server/#running-rancher-server-behind-an-elasticclassic-load-balancer-elb-in-aws).

**Comment by aemneina** [comment]
Let us know if that does the trick @gordymunro3

**Comment by superseb** [comment]
Yep, we have example configs available in the docs. http://rancher.com/docs/rancher/v1.6/en/installing-rancher/installing-server/basic-ssl-config/
