### ISSUE TITLE
Support for Integrated Windows Authentication in containers 

### ISSUE THREAD

**Issue by wjimenez5271** [rancher/rancher#8929]
It seems this is a supported path from Microsoft when using 'CredentialSpec' with windows containers: https://blogs.msdn.microsoft.com/containerstuff/2017/01/30/create-a-container-with-active-directory-support/.

This would need to be tested in the context of Rancher

**Comment by superseb** [comment]
Did you take a look at https://github.com/rancher/rancher/issues/8293 ?

**Comment by wjimenez5271** [comment]
@superseb thanks looks similar, should we combine?

**Comment by superseb** [comment]
Yup, if you agree it is the same 👍
