### ISSUE TITLE
Kubernetes proxy start up errors

### ISSUE THREAD

**Issue by hiscal2015** [rancher/rancher#8931]
**Rancher versions:** 1.5.10

**Docker version: (`docker version`,`docker info` preferred)** 1.12.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)** Ubuntu16.04

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** Bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)** Single

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)** Kubernetes

**Steps to Reproduce:**

I have a few errors during kubernetes-proxy starting up, I don't know whether they have to be fixed. One of them is the node name issue, when hosts being added to rancher, fqdn is the default node name added to Kubernetes, so "Get http://kubernetes.kubernetes.rancher.internal/api/v1/nodes/server01" is definitely won't work.

```
5/25/2017 12:27:01 PM+ exec kube-proxy --master=http://kubernetes.kubernetes.rancher.internal --v=2 --healthz-bind-address=0.0.0.0
5/25/2017 12:27:01 PMI0525 04:27:01.395476       7 iptables.go:176] Could not connect to D-Bus system bus: dial unix /var/run/dbus/system_bus_socket: connect: no such file or directory
5/25/2017 12:27:01 PMI0525 04:27:01.395618       7 server.go:168] setting OOM scores is unsupported in this build
5/25/2017 12:27:01 PME0525 04:27:01.535928       7 server.go:421] Can't get Node "server01", assuming iptables proxy, err: Get http://kubernetes.kubernetes.rancher.internal/api/v1/nodes/server01: dial tcp 10.42.219.235:80: getsockopt: connection refused
5/25/2017 12:27:01 PMI0525 04:27:01.539800       7 server.go:215] Using iptables Proxier.
5/25/2017 12:27:01 PMW0525 04:27:01.554079       7 server.go:468] Failed to retrieve node info: Get http://kubernetes.kubernetes.rancher.internal/api/v1/nodes/server01: dial tcp 10.42.219.235:80: getsockopt: connection refused
5/25/2017 12:27:01 PMW0525 04:27:01.554416       7 proxier.go:249] invalid nodeIP, initialize kube-proxy with 127.0.0.1 as nodeIP
5/25/2017 12:27:01 PMW0525 04:27:01.554425       7 proxier.go:254] clusterCIDR not specified, unable to distinguish between internal and external traffic
5/25/2017 12:27:01 PMI0525 04:27:01.554456       7 server.go:227] Tearing down userspace rules.
5/25/2017 12:27:01 PMI0525 04:27:01.554531       7 healthcheck.go:119] Initializing kube-proxy health checker
5/25/2017 12:27:01 PMI0525 04:27:01.576259       7 conntrack.go:81] Set sysctl 'net/netfilter/nf_conntrack_max' to 131072
5/25/2017 12:27:01 PMI0525 04:27:01.577056       7 conntrack.go:66] Setting conntrack hashsize to 32768
5/25/2017 12:27:01 PMI0525 04:27:01.577434       7 conntrack.go:81] Set sysctl 'net/netfilter/nf_conntrack_tcp_timeout_established' to 86400
5/25/2017 12:27:01 PMI0525 04:27:01.577460       7 conntrack.go:81] Set sysctl 'net/netfilter/nf_conntrack_tcp_timeout_close_wait' to 3600
```

```
> kubectl get nodes
NAME                                   STATUS    AGE
server01.demo.com   Ready     6d
server02.demo.com   Ready     6d
server03.demo.com   Ready     6d
```

**Comment by joshwget** [comment]
Do you notice any issues with the cluster after it's brought up?

**Comment by hiscal2015** [comment]
@joshwget I have this issue, I don't know whether it is something related:
https://github.com/rancher/rancher/issues/8885

The issue is very tricky, I can telnet nodeport from some of my servers, but some can't...

**Comment by hiscal2015** [comment]
@joshwget I'm trying to add below code to entry.sh to fix this issue but still failed, any ideas?

```
elif [ "$1" == "kube-proxy" ]; then
    FQDN=$(hostname --fqdn || hostname)
    exec "$@" --hostname-override ${FQDN}

```

**Comment by joshwget** [comment]
Were you able to successfully launch it with the change? Same logs as before?

Your fix seems like the right approach so if you end up getting stuck I'll probably try something similar.

**Comment by hiscal2015** [comment]
@joshwget Changed code to below resolved this issue, because kube-proxy has to wait kubelet to register node to Kubernetes

```
elif [ "$1" == "kube-proxy" ]; then
    FQDN=$(hostname --fqdn || hostname)
    while ! curl -s -f http://kubernetes.kubernetes.rancher.internal/api/v1/nodes/${FQDN}; do
        echo Waiting for node info
        sleep 1
    done
    exec "$@" --hostname-override ${FQDN}
```

**Comment by hiscal2015** [comment]
@joshwget Confirmed my nodeport issue has been resolved after kube-proxy issued fixed! I don't know why, but issue was gone!

**Comment by hiscal2015** [comment]
@joshwget Oh, sorry, nodeport issue appears again, but #8931 can be closed. I'll re-open #8885, for #8885, I can reproduce now.

**Comment by joshwget** [comment]
Adding `--hostname-override ${FQDN}` definitely seems like a good change. I'm not sure about waiting on the node to be registered first though. It's something I haven't seen in other Kubernetes installation methods.

Is your latest conclusion that #8885 is resolved with your fix? It's hard to tell what the sequence of comments was.
