### ISSUE TITLE
edit the kernel command line

### ISSUE THREAD

**Issue by yankunsam** [rancher/rancher#8932]
**Rancher versions:**
rancher/server:
rancher/agent:

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**
How to edit the kernel command line ,like "ima_tcb " ?
**Results:**

**Comment by superseb** [comment]
Like discussed on Slack, I created this PR to add to the docs: https://github.com/rancher/os/pull/1887
