### ISSUE TITLE
Rancher doesn't pay attention to port conflicts in host network mode.

### ISSUE THREAD

**Issue by ketchoop** [rancher/rancher#8933]
**Rancher versions:**
rancher/server: 1.5.10
rancher/agent: 1.2.2

**Infrastructure Stack versions:**
network-services: net-manager 0.6.6

**Docker version: (`docker version`,`docker info` preferred)**

17.04.0-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
RancherOS v1.0.1 kernel 4.9.24

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

Parallels VM

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

Rancher HA external DB galera cluster

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

cattle

**Steps to Reproduce:**

I used hashicorp vault server and scaled it to 3 instances with host network(net=host) without any scheduling rules.

**Results:**

Two containers were deployed on the different nodes, but the last one were deployed on the same node as the second one. And I've got port conflict that can't be resolved because rancher tries to deploy container on the node that it had used before.

**Comment by lukewhiting** [comment]
You can solve this using affinity labels. Adding this to your docker-compose's labels section should do the job: 

`io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}`

IE Don't put this container on a host that already has a container from the same stack and service.

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
