### ISSUE TITLE
Automated deploy rancher/agent from VM (via Vagrantfile)

### ISSUE THREAD

**Issue by olegkolner** [rancher/rancher#8935]
The problem is that by registration of rancher/agent I need the unique token (for authorization purposes). 
Is it possible somehow automatically deploy rancher/agent from VM, e.g. via Vagrantfile or some scripts with no need to input the unique token in docker-command for registration of rancher/agent?

**Comment by vincent99** [comment]
With access control disabled you don't actually need a registration token.  Once it's on, allowing any machine that wants to to join the environment with no authentication would be a very bad idea.

**Comment by olegkolner** [comment]
actually I need to build a cluster with for example 20 VMs with running rancher/agent and I need also to provide access control. So it would be pretty useful to provide automated registration of each VM without much of manual work with copy-paste of unique tokens for each VM

**Comment by vincent99** [comment]
Registration tokens (the URL in the command) are per-environment, you don't need a unique one for each host.
