### ISSUE TITLE
implement delete flag for rancher-nfs - protected volumes

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#8936]
**Steps to Reproduce:**
Right now if you create a volume in rancher-nfs, and delete it, the data in that volume is removed. We want to prevent data deletion by users with a rancher-nfs driver scoped flag to block deletion.

**Comment by LLParse** [comment]
RFR
https://github.com/rancher/storage/pull/60
https://github.com/rancher/rancher-catalog/pull/735

**Comment by cjellick** [comment]
Please ping me with the test plan for this @sangeethah. I want to make sure I understand that feature.

**Comment by sangeethah** [comment]
TestPlan - 
[NFS-OnRemove-Flag-TestPlan.xlsx](https://github.com/rancher/rancher/files/1156811/NFS-OnRemove-Flag-TestPlan.xlsx)

**Comment by sangeethah** [comment]
Tested with rancher server build from v1.6 branch with rancher/storage-nfs:v0.8.4.
There is a new ON_REMOVE parameter that is introduced that defaults to "purge".
Issues found when testing this feature:

https://github.com/rancher/rancher/issues/9381

**Comment by djskinner** [comment]
Is there documentation for this feature?

**Comment by superseb** [comment]
@djskinner It's here: https://github.com/rancher/rancher.github.io/pull/843/files

We'll get this merged asap.
