### ISSUE TITLE
more verbose logging for rancher-nfs

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#8937]
more verbose logging for rancher-nfs: right now we get a generic removing message. Is it actually deleting data or skipping delete? More insight around the operations being conducted, the better.

**Comment by LLParse** [comment]
RFR
https://github.com/rancher/storage/pull/61

**Comment by sangeethah** [comment]
Tested with rancher/storage-nfs:v0.8.4 

Set   up:   Rancher-NFS deployed with onRemove=retain
Scenario 1:

1.   Create Volume - "abc" (using "Add Volumes" option from   Infrastructure Storage)  
 2. Create a service - S1 that uses external volume - "abc" . Write some contents. 
 3. Create another service - S2  that uses the same external   volume - "abc". 
 4. Delete service S1 and S2.
5. Delete volume "abc"   

Volume gets deleted from rancher-server  and continues to be present in the nfs server as expected.
```
7/18/2017 9:38:21 AMtime="2017-07-18T16:38:21Z" level=info msg=remove.request name=test-4319
7/18/2017 9:38:21 AMtime="2017-07-18T16:38:21Z" level=info msg=remove.response message=retained name=test-4319 status=Success
```

Absence of Purging subfolder logs indicates that actual delete is not attempted for this delete request:
 
``` 7/18/2017 9:57:45 AMtime="2017-07-18T16:57:45Z" level=info msg="Purging subfolder /tmp/cyv57/testnow"```



Scenario 2:
1.   Create Volume - "abc" (using "Add Volumes" option from   Infrastructure Storage) with driver_opt onRemove=purge   
2. Create a service - S1 that uses external volume - "testnow" . Write some   contents.  
3. Create another service - S2   that uses the same external   volume - "testnow". 
4. Delete service S2 and Delete service S1.   
5. Delete volume - "testnow"

Volume gets deleted as expected from the nfs server.

We expect volume delete to have succeeded only from 1 host in this case ?

Why is the actual call made to delete the volume - which is ```7/18/2017 9:57:44 AMtime=“2017-07-18T16:57:44Z” level=info msg=“Purging subfolder /tmp/fugyp/testnow” ``` ? not reporting a failure from 1 of the hosts ?

```
Host 1:
7/18/2017 9:55:27 AMtime="2017-07-18T16:55:27Z" level=info msg=unmount.request name=testnow
7/18/2017 9:55:27 AMtime="2017-07-18T16:55:27Z" level=info msg=unmount.response name=testnow
7/18/2017 9:55:30 AMtime="2017-07-18T16:55:30Z" level=info msg="container 05fe21d6ab018766e5625778d7a1d76c83e9e78e1c006e5f7732a66758f0416d destroyed"
7/18/2017 9:55:31 AMtime="2017-07-18T16:55:31Z" level=info msg="Unmounting /var/lib/rancher/volumes/rancher-nfs/testnow"
7/18/2017 9:55:31 AMtime="2017-07-18T16:55:31Z" level=error msg="Failed to unmount /var/lib/rancher/volumes/rancher-nfs/testnow: Lookup mount: stat /var/lib/rancher/volumes/rancher-nfs/testnow: no such file or directory"
7/18/2017 9:55:31 AMtime="2017-07-18T16:55:31Z" level=error msg="Failed to run GC: Lookup mount: stat /var/lib/rancher/volumes/rancher-nfs/testnow: no such file or directory"
7/18/2017 9:57:43 AMtime="2017-07-18T16:57:43Z" level=info msg=remove.request name=testnow
7/18/2017 9:57:44 AMtime="2017-07-18T16:57:44Z" level=info msg="Purging subfolder /tmp/fugyp/testnow"
7/18/2017 9:57:44 AMtime="2017-07-18T16:57:44Z" level=info msg=remove.response message=purged name=testnow status=Success


Host 2:
7/18/2017 9:55:12 AMtime="2017-07-18T16:55:12Z" level=info msg=unmount.request name=testnow
7/18/2017 9:55:12 AMtime="2017-07-18T16:55:12Z" level=info msg=unmount.response name=testnow
7/18/2017 9:55:15 AMtime="2017-07-18T16:55:15Z" level=info msg="container 371926fd850722083c44a0ea88c90f5de5b789a512f34e53919efbe80ef9b13c destroyed"
7/18/2017 9:55:16 AMtime="2017-07-18T16:55:16Z" level=info msg="Unmounting /var/lib/rancher/volumes/rancher-nfs/testnow"
7/18/2017 9:55:16 AMtime="2017-07-18T16:55:16Z" level=error msg="Failed to unmount /var/lib/rancher/volumes/rancher-nfs/testnow: Lookup mount: stat /var/lib/rancher/volumes/rancher-nfs/testnow: no such file or directory"
7/18/2017 9:55:16 AMtime="2017-07-18T16:55:16Z" level=error msg="Failed to run GC: Lookup mount: stat /var/lib/rancher/volumes/rancher-nfs/testnow: no such file or directory"
7/18/2017 9:57:45 AMtime="2017-07-18T16:57:45Z" level=info msg=remove.request name=testnow
7/18/2017 9:57:45 AMtime="2017-07-18T16:57:45Z" level=info msg="Purging subfolder /tmp/cyv57/testnow"
7/18/2017 9:57:45 AMtime="2017-07-18T16:57:45Z" level=info msg=remove.response message=purged name=testnow status=Success
```

**Comment by LLParse** [comment]
@sangeethah I agree we need to be a little more clear when purging/not purging, I will explicitly log `Retaining volume` when this happens.

If you are experiencing the same volume being deleted on multiple hosts, that is a bug. The volume delete logic should only be called once. Can you please file this?

**Comment by LLParse** [comment]
I changed my mind about the multiple delete behavior. We designed delete to be idempotent in all of our storage plugins, consequently it doesn't matter if it is triggered more than once.

**Comment by sangeethah** [comment]
Tested with rancher/storage-nfs:v0.8.5:
Logs when purging volumes:

```
7/21/2017 11:06:53 AMtime="2017-07-21T18:06:53Z" level=info msg=remove.request name=hello
7/21/2017 11:06:54 AMtime="2017-07-21T18:06:54Z" level=info msg="Purging volume (subfolder)" name=hello
7/21/2017 11:06:55 AMtime="2017-07-21T18:06:55Z" level=info msg=remove.response message=purged name=hello status=Success
```

Logs when retaining volumes:

```
7/21/2017 11:17:36 AMtime="2017-07-21T18:17:36Z" level=info msg=remove.request name=testme123
7/21/2017 11:17:36 AMtime="2017-07-21T18:17:36Z" level=info msg="Retaining volume" name=testme123
7/21/2017 11:17:36 AMtime="2017-07-21T18:17:36Z" level=info msg=remove.response message=retained name=testme123 status=Success
```
