### ISSUE TITLE
Tool to collect logs for networking debugging/analysis

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#8939]
**Overview of the feature:**
As a Rancher User, I should be able to click a link in the UI to download a tar file with all the logs needed to troubleshoot/debug a problem in Rancher Environment.

**High level Design:**
A new service, along with a new catalog item will be created which will be responsible to collect the logs using the Rancher CLI communicating directly with the API. 
This catalog item needs to be deployed as part of the Infrastructure stacks. The UI needs to be modified to accommodate the new link pointing to service URL (`/r/projects/<project_id>/<service name>:<some_port>/`).

The service needs to be launched with `io.rancher.container.agent.role: 'environmentAdmin'` to be able to get the API keys to be used with Rancher CLI.

The service will be always running but the logs are generated on demand (only when the user clicks in the UI). The logs are generated with a timestamp of when they were requested and will be cleaned up after 30 min to reduce the disk usage.

TBD:
Catalog Name: ??? (support-tools)
Service Name: ??? (logs-collector)
Port Number: ??? (8765)

**Dependencies:**
https://github.com/rancher/rancher/issues/8922
https://github.com/rancher/rancher/issues/8940

**Comment by ibuildthecloud** [comment]
This task should just be focused on networking, don't need to think of this as a general tool.  Maybe we can expand it to that, but for now just focus on networking.  Random comments below:

You do not need to listen on a published port, so port 80 would actually make things easier.  It is expected that the UI will create a link that will go through the websocket proxy to access the service, so something like `/r/projects/1a5/network-support/download` where network-support is the download tool.

The tool should be collecting networking information at a configured interval and a max number of backups to keep.  So default might be every 15 minutes and keep 1000.  This should capture all the important networking tables in likes (arp, route, xfrm, etc.).  Logs don't need to be collected on an interval.

This tool should also be constantly pinging peer hosts and peer containers in an intelligent fashion.  For example, if you can't ping the host, don't ping the peer ipsec router.  If you can't ping the peer ipsec router, don't try other peer containers.  Record any failures you encounter.

This tool should have a healthcheck (with healthcheck action none) that reports bad when a good peer containers or host can't be ping after X tries.

On demand when the UI download things is should grab the historical dumps from all hosts plus the important logs.

**Comment by vincent99** [comment]
- Can this be packaged into the server container instead and just be always on?  (Like telemetry, except not conditional.  It runs in the container and exposes an API endpoint)
- If it's a separate catalog/stack/service/container then it has to be deployed, orchestrated and working in order to get logs at a time when something is by definition going wrong.
- If generating the file is going to take more than a few seconds then I need to show progress/waiting somehow.
- Prefer zip instead of tar

**Comment by ibuildthecloud** [comment]
@vincent99 That is a good point.  There could be two aspects of this.  One that runs on the server and does the download of the info.  A second part to run as agents on each host.

**Comment by leodotcloud** [comment]
There are three different tasks which need to be done:

Task A) On every host collect networking info periodically
Task B) Do pings between every other container
Task C) A backend service which acts as a logs aggregator from different hosts and allows for download of a zip file.


Options for Task A:
1) This can be implemented a separate microservice with --net=host and --privileged
    1a) - Deployed as serviced in a separate stack
    1b) - Deployed as service in existing network-services stack
    **1c) - Deployed as a service inside the network-driver stack.**
2) Can be integrated as another goroutine inside "plugin-manager", aka network-manager

Options for Task B:
1) This can be implemented a separate microservice with --net=host and --privileged
    1a) - Deployed as serviced in a separate stack
    1b) - Deployed as service in existing network-services stack
    **1c) - Deployed as a service inside the network-driver stack.**
2) Can be integrated as another goroutine inside "plugin-manager", aka network-manager

Options for Task C:
**1) Implement this as a service with API keys so that rancher cli can be used. This would need to be deployed inside the cluster.**
2) Implement as a binary inside the rancher/server container itself.

After discussing with @vincent99 and @ibuildthecloud here is the summary:
Implement Task A and Task B as two different goroutines inside the same microservice.
This microservice will be deployed as part of the network-driver stack (ipsec/vxlan)

For Task C: Implement as a different stack deployed inside the environment.

**Comment by cjellick** [comment]
This issue now represent the UI component for the tool. It will only go into 2.o

**Comment by cjellick** [comment]
Once general QA is done, can we have @aemneina take the feature for a quick test drive so he knows how to use it?

**Comment by sangeethah** [comment]
@cjellick @leodotcloud Issues found when testing this feature:

https://github.com/rancher/rancher/issues/9309
https://github.com/rancher/rancher/issues/9299
https://github.com/rancher/rancher/issues/9296

**Comment by soumyalj** [comment]
Closed this one as there are other issues logged regarding the tool.
