### ISSUE TITLE
cpu过高的问题

### ISSUE THREAD

**Issue by tianwaizhiyin** [rancher/rancher#8947]
用新的centos7.3阿里云服务搭建的rancher1.5服务，由于以下这个进程导致cpu过高，所以kill -9 杀死了进程，然后问题是rancher-server服务的docker容器起来了，8080端口也起来了，但是web页面怎么也登陆不了，一直报502错误。重启的rancher-server容器服务和docker服务都没有，请问这个是什么问题，怎么解决呢？谢谢！
root     12846 12843 99 May23 ?        10-17:48:32 java -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -Xms128m -Xmx4g -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/var/lib/cattle/logs -Dlogback.bootstrap.level=WARN -cp /usr/share/cattle/318643a6f97e36adaffc3f8ad817dac1:/usr/share/cattle/318643a6f97e36adaffc3f8ad817dac1/etc/cattle io.cattle.platform.launcher.Main

**Comment by tianwaizhiyin** [comment]
root     12846 12843 99 May23 ?        10-17:48:32 java -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -Xms128m -Xmx4g -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/var/lib/cattle/logs -Dlogback.bootstrap.level=WARN -cp /usr/share/cattle/318643a6f97e36adaffc3f8ad817dac1:/usr/share/cattle/318643a6f97e36adaffc3f8ad817dac1/etc/cattle io.cattle.platform.launcher.Main
root     12946 12846  0 May23 ?        00:04:13 rancher-catalog-service --config repo.json --refresh-interval 300
root     12997 12846  0 May23 ?        00:46:55 websocket-proxy
root     13008 12846  0 May23 ?        00:00:00 secrets-api server --enc-key-path .
root     13013 12846  0 May23 ?        00:00:10 webhook-service
root     13276 12846  0 04:03 ?        00:00:17 go-machine-service
root     13284 12846  0 04:03 ?        00:00:06 rancher-compose-executor
root     15532 12846  0 May23 ?        00:00:24 rancher-auth-service
root     17527 12846  0 09:46 ?        00:00:00 telemetry client

**Comment by loganhz** [comment]
@tianwaizhiyin please use English to describe your issue here. or you can find us via wechat by searching RancherLabsChina。 请用英文在这里提问，或者添加我们的微信（RancherLabsChina），可以加入中国Rancher微信技术支持群

**Comment by superseb** [comment]
See above, we can reopen in English or please contact RancherLabsChina.
