### ISSUE TITLE
[feature request] expose ports via UI

### ISSUE THREAD

**Issue by JulianKingman** [rancher/rancher#8948]
I understand that Rancher doesn't use (or like?) exposed ports, but there are containers that communicate with each other and rely on exposed ports, so it should at least be possible to set them in the UI, even if it serves little purpose for Rancher.
Related:
https://github.com/rancher/rancher/issues/2198
https://github.com/rancher/rancher/issues/159

Edit: It appears that jwilder/nginx-proxy and adi90x/rancher-active-proxy rely on expose

**Comment by vincent99** [comment]
You can set `expose` with the API or compose/CLI.  Ad-hoc `--expose` on run is intentionally not included in the UI because it does nothing and/or is actively misleading to 99.9% of users.

`EXPOSE`d ports declared in the image are are included in the list of ports returned by the Rancher API/metadata (with a `null` public value unless it's actually published to something).  This is what `adi90x/rancher-active-proxy` is using.  It also has a label alternative.

**Comment by JulianKingman** [comment]
I understand not wanting to mislead... what about a `flags` field, where you could specify arbitrary flags, such as `expose` and others?

**Comment by pasikarkkainen** [comment]
@vincent99 : can you clarify where exactly should I see the exposed ports in the rancher metadata service? 

in docker-compose.yml:

web:
    expose:
    - "1234"

And I launch a new stack with rancher cli using that docker-compose.yml + rancher-compose.yml, and then check rancher metadata service.. but I can't see anything under services/<id>/expose
(the value of expose is "0").

Or does it show up somewhere else? I'm currently using rancher v1.5.10.

**Comment by pasikarkkainen** [comment]
Another related issue: https://github.com/rancher/rancher/issues/4121

**Comment by superseb** [comment]
@pasikarkkainen It's returning an array, with `0` being the first element. You can always pass the header to accept JSON to see raw data, i.e. ```curl -H "Accept: application/json" 169.254.169.250/latest/services/4/expose```

**Comment by superseb** [comment]
@JulianKingman Your request is focused on adding the expose flag through the UI, correct?

**Comment by pasikarkkainen** [comment]
@superseb : Of course. I should have realized that.. now I feel stupid :) Thanks a lot! Seems to work fine via docker-compose.yml.

And yep, it'd nice to be able to see the expose array via the UI aswell.

**Comment by JulianKingman** [comment]
Yes, that's right.

**Comment by vincent99** [comment]
Still against this.  It makes little sense separated from the ports section, and will be confusing if it is part of it.
