### ISSUE TITLE
Single Rancher Server says it's 'Clustered', but it's not

### ISSUE THREAD

**Issue by stefanlasiewski** [rancher/rancher#8949]
My Rancher Cluster has a single Rancher Server. The Rancher Server says that it's clustered, but it's not. Is this a problem?

![image](https://cloud.githubusercontent.com/assets/142752/26694667/1081a6d0-46bd-11e7-8426-baf8f2d78179.png)

My Rancher Server was installed using the Puppet garethr/puppet module , and is started via Systemd with these flags:

```
/usr/bin/docker create \
    --net bridge -m 0b -p 8080:8080 -p 9345:9345 --restart=unless-stopped -v /etc/pki/tls/certs/example.org-cert.pem:/ca.pem:ro \
    --name rancher-server \
    rancher/server:v1.5.10 \
    --db-host db1.example.org --db-user rancher --db-name cattle --advertise-address 192.168.100.100
```

A couple questions:

Which commandline flag activates the clustering?

What happens if this single Rancher Server thinks it needs to wait for quorum with other non-existent nodes in the cluster? I'm asking because this cluster froze with an error that looked a bit like that happened. If so, I'll file a new bug.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.5.10` Cattle: `v0.178.14` UI: `v1.5.9` |
|Access|`openldap` `admin`|
|Orchestration|`Cattle`|
|Route|`admin-tab.ha`|

**Comment by pengjiang80** [comment]
It may be because you used "--advertise-address 192.168.100.100" and "-p 9345:9345". These parameters are used for cluster deployment.

**Comment by stefanlasiewski** [comment]
@pengjiang80 Yeah, that's what I expect. I'd love to have some sort of authoritative answer on this. Many of our hosts are multi-homed, so I like to be explicit with the advertised address for a service.

**Comment by superseb** [comment]
Indeed the `--advertise-address` triggers clustering options, see here: https://github.com/rancher/rancher/blob/master/server/bin/entry#L25

I believe there is just locking, no quorum. Can you open a new issue with logging you were seeing when this was happening?
