### ISSUE TITLE
Rancher-cli incorrect help documentation

### ISSUE THREAD

**Issue by mrproper** [rancher/rancher#8950]
**Rancher versions:**
rancher/server:
rancher/cli: v0.5.3

**Steps to Reproduce:**
rancher stacks --help
NAME:
   rancher stacks - Operations on stacks

USAGE:
   rancher stacks command [command options] [arguments...]

COMMANDS:
     ls      List stacks
     create  Create a stacks

OPTIONS:
   --system, -s    Show system resources
   --quiet, -q     Only display IDs
   --format value  'json' or Custom format: {{.Id}} {{.Name}}
   --help, -h      show help
``

**Results:**
``
rancher stacks --format {{.Id}} {{.Name}}
FATA[0000] template: :1:2: executing "" at <.Id>: can't evaluate field Id in type *cmd.StackData 
``

Usage should be updated to:
'{{.ID}} {{.Stack.Name}}'

**Comment by superseb** [comment]
https://github.com/rancher/cli/pull/67

**Comment by superseb** [comment]
https://github.com/rancher/rancher.github.io/pull/833

**Comment by deniseschannon** [comment]
Available as of v0.6.3-rc1

**Comment by superseb** [comment]
This is released in v0.6.3
