### ISSUE TITLE
Container without healthcheck not re-scheduled when agent is not available

### ISSUE THREAD

**Issue by pengjiang80** [rancher/rancher#8951]
1. Create service without healthcheck. Ensure the containers are scheduled to multiple hosts.
2. Poweroff one of the hosts directly or just docker stop rancher-agent. Ensure the host is in disconnected status.
3. Containers in the disconnected host are not rescheduled. 

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.5.9
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`stacks.index`|

**Comment by deniseschannon** [comment]
This is the correct behavior. Containers without a healthcheck will not be moved to a different host until a host is deleted from Rancher. When Rancher loses connection with the Rancher agent, it has no way of knowing if those containers are still running or not. As a user of Rancher, if one of your hosts becomes disconnected, we expect the users to monitor to see if that host should be deleted or if it will be reconnected to Rancher.

**Comment by pengjiang80** [comment]
I know. But it may not be good as Rancher just support TCP/HTTP healthcheck. For some special containers,  TCP/HTTP healthcheck can't be used to monitor the healthy. And in that case if the server is down, containers will not be re-scheduled. A Rancher user told me they plan to switch to k8s because of this.
