### ISSUE TITLE
[Feature Request] Make problematic container cleanup delay configurable

### ISSUE THREAD

**Issue by pengjiang80** [rancher/rancher#8952]
Cattle will delete problematic container and try to re-create new one. Sometimes we need to check the log of problematic container to know the failure reason. Currently the problematic one is removed in a short time. We may need to set the time configurable.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.0` Cattle: `v0.179.7` UI: `v1.6.1` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`stacks.index`|

**Comment by yeta-io** [comment]
+1

Really needed feature. Broken containers removed so fast, not possible to investigate why it fails.

**Comment by cjellick** [comment]
Is it possible to give a more detailed set of steps to reproduce? How is the problematic container dying? Is it failing to deploy? Is its healthcheck failing? Is it failing to start?

**Comment by pengjiang80** [comment]
Healthcheck failing should be one of the scenarios. For example I have some tomcat containers running with healthcheck enabled. Due to some reason tomcat or the application has some problem and failed in healthcheck, Rancher will create the containers very quickly and delete failed one. Then it's hard to us to collect container log and find clues.

**Comment by StrongMonkey** [comment]
There are two cases.
One is for health-check. It can be configured with `checkInterval * Unhealthy threshold` to configure the time interval when healthcheck reports the service as unhealthy. Also initializing and reinitializing timeout can also be used.
One is for clean-up for the error state container. We need thumbs up on whether we set the interval on a per-service level or on a global setting level. @cjellick @ibuildthecloud

**Comment by StrongMonkey** [comment]
@alena1108 mentioned: to implement the second case, we require a more complicated solution to leave bad instance around but not delaying the recreate process. So we would like to leave the work to 2.0 milestone.

**Comment by alena1108** [comment]
To implement the feature, following needs to be done:

1) Today we destroy the failed container before recreating its replacement. Instead the error/unhealthy container should be stopped, and left around and marked for cleanup (new DB data field is needed for that). Container's replacement should be created right away.
2) There should be a periodic cleanup task removing the containers that were marked for cleanup, that hit the cleanup timeout. The timeout can be set either on per service basis, or globally. 

1) can be tricky as certain resources like ip address, can't be allocated to more than one container at a time. So retainIp feature can't be utilized in this case. There might be more use cases that have to be considered and investigated.

**Comment by alena1108** [comment]
Closing as Rancher 2.0 is k8s based now
