### ISSUE TITLE
service health checks does not get updated on v1.5.10

### ISSUE THREAD

**Issue by obenziane2** [rancher/rancher#8953]
**Rancher versions:**
rancher/server: 1.5.10
rancher/agent:1.2.2

**Infrastructure Stack versions:**
healthcheck:v0.2.3
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
1.12.6
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Amazon linux AMI
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
EC2
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**

The health check settings from the database does not align with the rancher-compose.
I've updated the health check to 15000 ms and rancher does not respect it and keeps checking on every 2000ms

**Results:**

See screenshots
<img width="1207" alt="screen shot 2017-06-02 at 11 14 34 pm" src="https://cloud.githubusercontent.com/assets/11947294/26751257/eebc3f8c-47e9-11e7-8740-d7b78fab0cd1.png">
<img width="620" alt="screen shot 2017-06-02 at 11 14 55 pm" src="https://cloud.githubusercontent.com/assets/11947294/26751256/eebae862-47e9-11e7-93a8-30a5cf71c4f6.png">

**Comment by tfiduccia** [comment]
Version - 1.6.1
I cannot reproduce your issue in the latest version.  Can you upgrade and see if you are still having problem.

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
