### ISSUE TITLE
[UI] Device binding permission is not configurable from 1.2 to 1.6.1

### ISSUE THREAD

**Issue by pengjiang80** [rancher/rancher#8954]
1. Create a service. Switch to Security/Host.
2. Click to add a device binding.
3. The permission field is showed as read/write/mknod and is not changeable. (Tried 1.2, 1.4, 1.5, 1.6)
4. In 1.1.0, it's a list of read/write/mknod with a checkbox in front of each of them. 

Is is a design change or a bug? 

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.1` Cattle: `v0.181.3` UI: `v1.6.5` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`stacks.index`|

**Comment by vincent99** [comment]
Bug, but that's the text for not-editing display.  Apparently not a lot of people interested in read-only devices though.

**Comment by deniseschannon** [comment]
Available with `v1.6.15-rc6`

**Comment by tfiduccia** [comment]
Version - v1.6.15-rc6
Verified fixed
