### ISSUE TITLE
Being able to change IPsec ports

### ISSUE THREAD

**Issue by checksrc** [rancher/rancher#8955]
**Rancher versions:**
rancher/server:latest
rancher/agent:1.22

FEATURE REQUEST - allow custom ports to be specified for the rancher-agent (UDP 500, 4500)

This can be done easily by updating the Dockerfile linked below with two EXPOSE lines https://github.com/rancher/rancher/blob/master/agent/Dockerfile

```
EXPOSE 450/udp
EXPOSE 4500/udp
```
This would come in handy when limiting the range of ports Docker can use with, so that rancher agents can still communicate when the required ports published are within the limited docker port range. Command for setting that range is as follows ;
```
echo "30000 39999" > /proc/sys/net/ipv4/ip_local_port_range
``

**Comment by vincent99** [comment]
IPSec software is not very friendly to changing the ports.  `EXPOSE` is just metadata and changing them by themselves does nothing.

**Comment by superseb** [comment]
@checksrc Do you want to be able to change the ports that IPsec uses to communicate? If so, please check https://github.com/rancher/rancher/issues/2139 which I think is the same request.

**Comment by leodotcloud** [comment]
Agree with @vincent99 it's not as simple as changing the Dockerfile.

**Comment by leodotcloud** [comment]
Closing this in favor of https://github.com/rancher/rancher/issues/2139
