### ISSUE TITLE
Unable to edit service alias

### ISSUE THREAD

**Issue by bkuhl** [rancher/rancher#8959]
The `wordpress-database` alias referenced a service that was cloned and the original deleted.  This led to the alias referencing nothing.  When trying to edit it, to point it to it's new primary service, I encounter an overlay that prevents me from being able to do anything on the page.

![service-alias](https://cloud.githubusercontent.com/assets/524933/26769188/cb79faa4-497a-11e7-8b60-c4b16cb6df5c.gif)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.5.9` Cattle: `v0.178.12` UI: `v1.5.9` |
|Access|`github` `admin`|
|Orchestration|`Cattle`|
|Route|`stacks.index`|

**Comment by loganhz** [comment]
UI breaks in this case.  A PR has been submitted  for it.
but maybe you have to remove and re-add the service alias for now.

**Comment by tfiduccia** [comment]
Version - master
Verified fixed
