### ISSUE TITLE
Editing from container details takes me back to main page

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#896]
v0.21.3
Steps:
1.  From the host or container main page click on container name to get to details page
2.  From right menu select edit
3.  Click on Save or Cancel

Results:
Takes me back to the main Host or Container list page

Expected:
Should take me to details page

**Comment by vincent99** [comment]
Works for me.. try again new build?

**Comment by tfiduccia** [comment]
v0.22.0-rc1
Failed - still doesn't work for me.  If I'm on host page and click on container name.  Then choose edit and Save, it takes me to host page, instead of details page.

**Comment by deniseschannon** [comment]
v0.23.0-rc1: Still doesn't work.

**Comment by deniseschannon** [comment]
This seems to be working in v0.23.0-rc5, but would like @tfiduccia to verify.

**Comment by vincent99** [comment]
None of the overlays change the URL any more, so any bugs like this no longer apply.

**Comment by deniseschannon** [comment]
v0.27.0-rc4 Verified fixed
