### ISSUE TITLE
Misleading UI error for malformed Docker image input

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#8961]
**Rancher versions:**
rancher/server: 1.5.8

**Steps to Reproduce:**

Try to add a new service in the UI entering an invalid image string under "Select Image". E.g. `google / cadvisor`.

**Results:**
The following error is shown to the user: `Validation failed in API: imageUuid`

**Expected results:**
User did not enter a image UUID so this message is confusing. The error should rather indicate that the specified image name is invalid.

![bildschirmfoto 2017-06-05 um 17 15 41](https://cloud.githubusercontent.com/assets/3813921/26790053/a7d8f5e4-4a12-11e7-8916-44bb9ba9cdd3.png)

**Comment by vincent99** [comment]
The field is called `image` in 2.0, so this will no longer apply.
