### ISSUE TITLE
In Chinese mode can‘t open container shell

### ISSUE THREAD

**Issue by pkevin0909** [rancher/rancher#8963]
*Describe your issue here*

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.1` Cattle: `v0.181.3` UI: `v1.6.5` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`service.containers`|

**Comment by lanmingle** [comment]
``` bash

Component	Version
Rancher	v1.6.2
Cattle	v0.181.4
User Interface	v1.6.5
Rancher CLI	v0.6.1
Rancher Compose	v0.12.5

```
change chinese open shell is error, change english or shift + l , open shell is auto close ! 

呵呵~

**Comment by deniseschannon** [comment]
@tfiduccia Can you test with v1.6.3-rc1?

**Comment by tfiduccia** [comment]
Version - v1.6.3-rc1
Verified fixed
