### ISSUE TITLE
Service Alias refresh very slow

### ISSUE THREAD

**Issue by lingzhang-lyon** [rancher/rancher#8965]
When I switch/edit a service alias to link to a different service, it take more than 1 min to resolve to the correct service container.
I checked from the api, the "linkedServices" already show correct service,  but when I use`nslookup <alias-name> 169.254.169.250` in a container, it still resolve to old service container ip for 1-2 mins. 

We have about 3000 containers in our cluster. This slowness not happened when in a small cluster.

How service alias resolve to correct service and how fast it can refresh when there is a change for the alias? 

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.5.3` Cattle: `v0.177.10` UI: `v1.5.8` |
|Access|`github` `admin`|
|Orchestration|`Cattle`|
|Route|`stack.index`|

**Comment by lingzhang-lyon** [comment]
@aemneina any updates on this issue?     
I found that the more service aliases we used, it got refreshed much slower.  some times it need 10 mins to  resolve to correct container.  This make our deploy pipeline unusable. 

How rancher update the metadata for the service alias?   looks like if I use the `<service name>.<stack_name>` , it can resolve to correct container much faster.
Do they generate the metadata in different ways?

Thank you very much for the help.

**Comment by vincent99** [comment]
This sounds like a problem with caching in rancher-dns that will be mostly fixed in 1.6.4 (#8805).

**Comment by lingzhang-lyon** [comment]
hi @vincent99 , thank you very much.

we are on rancher 1.6.2 now, and I just checked pr in #8805 (rancher/rancher-catalog#751) ,  looks like the new version of network service already in use in 1.6.2. 
we tested with setting --ttl to 10,  the metadata refresh still very slow even for upgrading one service container when we reach around total 3000 containers/alias.   

how many containers usually Rancher can support per environment? 

Thanks again for all your help.

**Comment by deniseschannon** [comment]
@lingzhang-lyon That PR has not made the official release of Rancher catalog for v1.6.2. Did you pick up the specific branch to test out that template?

**Comment by lingzhang-lyon** [comment]
hi @deniseschannon 

I just checked the changes in that PR for catalog,
looks like the `network-services` is  using:
```
rancher/network-manager:v0.7.4
rancher/metadata:v0.9.2
rancher/dns:v0.15.1
```
which already in use in rancher 1.6.2.

The only difference I notice is the command for `dns` service changed with a --ttl option.
```
command: rancher-dns --metadata-server=localhost --answers=/etc/rancher-dns/answers.json --recurser-timeout ${DNS_RECURSER_TIMEOUT} --ttl ${TTL}
```
so I just upgrade that service with new cmd added --ttl 10

is this a correct way to test out the changes?  or there are something else I need to change as well?

Thanks again for the help.

**Comment by lingzhang-lyon** [comment]
The load test results are as following: 


1) 3k containers ( in 3k stacks, 1 container/stack)  :
upgrade one service container, dns refreshed very faster,  like in few seconds.

2) 3k containers ( all in 1 stack A )  + 1 container ( 1 stack B) :
upgrade one service container in stack B , dns refreshed also in few seconds.

3) 3k aliases (in 250 stacks, 12 aliases/stack)  + 1 container ( 1 stack B) :
upgrade one service container in stack B , dns refreshed extremely slow, need > 12 mins

4) 300 aliases (in 25 stacks, 12 aliases/stack)   + 1 container ( 1 stack B) :
upgrade one service container in stack B , dns refreshed extremely slow, need 1~2 mins

above tests all run after upgraded `dns` service with --ttl 10

so looks like service alias affect speed of syncing metadata quite a lot.

could you help to point to the code how rancher update metadata for service alias?

**Comment by vincent99** [comment]
I'm curious what you're doing that has use for thousands of aliases...

The cache in rancher-dns is only a thousand entries so it's possible the order you're requesting them is the only thing determining the difference you're measuring.

**Comment by lingzhang-lyon** [comment]
hi @vincent99. this is just for load testing, we usually just have less than 300 alias in our production env.  but it's still slow, need 1~2 mins to refresh the dns after upgrade one service.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
