### ISSUE TITLE
Multiple Aliases for an External Link

### ISSUE THREAD

**Issue by russ** [rancher/rancher#8966]
I just ran into this and it took me a minute to figure out what as going.

Our setup has a load balancer that maps multiple host names to the same app. Works great for the load balancing but fails when it comes to mapping that using external links.

```
external_links:
  - myloadbalancer/loadbalancer:service1.web
  - myloadbalancer/loadbalancer:service2.web
  - myloadbalancer/loadbalancer:service3.web
```

Only the last mapped link gets loaded and the first two go away on the container. I can see why it's done this way but is there a way to make this work in the future?

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
