### ISSUE TITLE
Set as Default and Switch to Environment menu options missing in Manage Environment

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#8972]
**Rancher versions:** 6/5

**Steps to Reproduce:**
1.  Go to Manage Environments
2.  Add another Environment
3.  Click on the menu for that environment

**Results:**  Set as default and Switch to environment are missing from the menu

**Comment by vincent99** [comment]
Switch is intentionally removed, set as default a bug.

**Comment by tfiduccia** [comment]
Version - Wagyu (master 7/25)
Verified fixed
