### ISSUE TITLE
App isn't remove on Delete until refresh

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#8973]
**Rancher versions:** 6/5

**Steps to Reproduce:**
1.  Deploy a template
2.  Go to Application main page and delete the "app"

**Results:**  App stays showing until refresh browser.

**Comment by vincent99** [comment]
@westlywright route needs to return a live array filtered in the controller instead of filtered in the route.

**Comment by tfiduccia** [comment]
Version - 6/12 (2.0 alpha)
Verified fixed
