### ISSUE TITLE
[gdapi-python] How to setup Kubernetes stack programmatically?

### ISSUE THREAD

**Issue by afgane** [rancher/rancher#8976]
I'm trying to use `gdapi` to create a Kubernetes stack but am not getting anywhere and can't find the relevant docs. For now, it's a single host setup installing Docker and Rancher on a clean Ubuntu 16.04 (I keep rebuilding the instance using Ansible). After the initial installation, I'd like to programmatically setup Kubernetes but `gdapi` keeps asking for an ID, even though it seems to be an optional argument:
```
$ gdapi kubernetesStack-create --help
usage: gdapi kubernetesStack-create [-h] [--id ID]

optional arguments:
  -h, --help  show this help message and exit
  --id ID
```
What should this ID be? Or more broadly, how should I go about setting up K8S using the API? Setting it up by hand using the UI works fine.

Thanks.

**Rancher versions:**
rancher/server: 1.5.3
rancher/agent: 1.5.3

**Infrastructure Stack versions:**
healthcheck: OK
ipsec: OK
network-services: OK
scheduler: OK
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
```
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:38:45 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:38:45 2017
 OS/Arch:      linux/amd64Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:38:45 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:38:45 2017
 OS/Arch:      linux/amd64
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
OpenStack VM

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node.

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
Run `gdapi kubernetesStack-create`

**Results:**
```
Traceback (most recent call last):
  File "bin/gdapi", line 11, in <module>
    sys.exit(_main())
  File "lib/python2.7/site-packages/gdapi.py", line 858, in _main
    _run_cli(client, args)
  File "lib/python2.7/site-packages/gdapi.py", line 785, in _run_cli
    obj = client.by_id(type_name, args['id'])
KeyError: 'id'
```

**Comment by vincent99** [comment]
`kubernetesStack` is the Cattle equivalent of deployed kubernetes namespace and not what you're looking for.  You want to create a `project` (the API equivalent of an environment in the UI) and specify the kubernetes `projectTemplate`.

**Comment by afgane** [comment]
Thanks for getting back quickly. However, I'm still not quite sure what this `projectTemplate` should be. I tried using the contents of `rancher-compose.yml` available in the _Preview_ window of the K8S Catalog entry. That created a new environment but it's blank. 
Alternatively, is there a way to a activate the available Catalog entry programmatically and just use the template available there?

**Comment by afgane** [comment]
Doesn't really solve the most recent question but gets the original intent: the following command will programmatically create a new Kubernetes environment (likely, the key being `projectTemplateId":"1pt1"` part): 
```
curl -X POST -H "Content-Type: application/json" -d '{"allowSystemRole":false,"virtualMachine":false,"type":"project","name":"k8s","description":null,"projectTemplateId":"1pt1","projectMembers":[],"created":null,"healthState":null,"kind":null,"removeTime":null,"removed":null,"uuid":null,"version":null,"hostRemoveDelaySeconds":null,"members":[]}' http://IP:PORT/v2-beta/project
```

**Comment by superseb** [comment]
You can use it as follows:

* Retrieve ID of Kubernetes projecttemplate
```ID=`gdapi --format json list-projectTemplate --name Kubernetes | jq --raw-output .[].id` ```
* Create new environment based on that projecttemplate
```gdapi create-project --name yourownenv --projectTemplateId $ID```

Like you already found, you can easily replicate API calls by capturing the calls from the browser and use `curl`.

Using `rancher/cli` this is as easy as `rancher env create -t kubernetes yourownenv`.
