### ISSUE TITLE
Scaling Group state displays state of Load Balancer but doesn't show them

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#8981]
**Rancher versions:** 6/6

**Steps to Reproduce:**
1.  Create a scaling group and add a service
2.  Add a load balancer to that scaling group
3.  Go to scaling group main page and hover over the state of scaling group

**Results:**  The results show 1 active & 1 healthy.  The healthy one is the load balancer but you don't show the load balancer on this page, so it's very confusing.
![image](https://user-images.githubusercontent.com/11514927/26845782-76896916-4aac-11e7-87ce-a6a1acbef52f.png)

**Comment by vincent99** [comment]
That pill was the state of the entire stack.  But is no longer shown anyway.
