### ISSUE TITLE
Stop from menu and stop from top button are different (top button does not work)

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#8982]
**Rancher versions:** 6/6

**Steps to Reproduce:**
1.  Go to Scaling Group page and create a scaling group
2.  After it's active, checkbox the scaling group
3.  Click on Stop button on top

**Results:**  Unknown action: stop
![image](https://user-images.githubusercontent.com/11514927/26846069-7e2c8c10-4aad-11e7-8354-bf07768684a4.png)
![image](https://user-images.githubusercontent.com/11514927/26846018-570f49d8-4aad-11e7-96c6-52f4d320e50e.png)

**Comments:** The stop when I click on the menu for the scaling group is different and works.
![image](https://user-images.githubusercontent.com/11514927/26846058-7659ac34-4aad-11e7-95a1-d1ee5f508f90.png)

**Comment by westlywright** [comment]
@vincent99 kicking this over to you as its dealing with Containers and Services. Basically we're passing this service off to the modal for container stop rather then deactivate. Maybe deactivate for a scaling group shouldn't be bulkable? Mixing in container stop and sg deactivate will be a bit of a mess I think.

**Comment by tfiduccia** [comment]
Version - 2.0 master 8/5
Verified fixed
