### ISSUE TITLE
Need to refresh to get status to change to healthly

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#8983]
**Rancher versions:** 6/6

**Steps to Reproduce:**
1.  Add host so all system stacks are active
2.  Stop the metadata scaling group, wait then restart
3.  Scheduler will stop and reinitialize

**Results:**  It will all go healthy but the status for the stack will get stuck in initializing.  Have to do a browser refresh for it to turn green and say Healthy.
![image](https://user-images.githubusercontent.com/11514927/26846369-4fc43110-4aae-11e7-8b70-79ccf4dacc4d.png)

**Comments:** Seems to only happen on automatic updates, not on manual stopped and restarted stacks.  Saw the same thing when I removed host then added it back in.  At least one of the stacks was all healthy but the stack status was red and said "Stopped"

**Comment by westlywright** [comment]
@vincent99 this seems to be an api issue. The health state from the API is still sitting in `initializing`. Unless there is an underlying mechanic i'm not seeing here?

**Comment by tfiduccia** [comment]
Version - 2.0 master 8/5
Scheduler is dealt with differently now.  So this is a non-issue
