### ISSUE TITLE
Rancher-secrets created 2500 Docker volumes, which causes lengthy delays when starting Docker

### ISSUE THREAD

**Issue by stefanlasiewski** [rancher/rancher#8984]
I rebooted a Rancher node. The system came up fine.

Docker tried to start, but doesn't seem to start completely. It seems to be waiting for the rancher-secrets plugin. 

I'm including logs for Docker immediately after a reboot.  The logs show that systemd begins starting Docker at 17:55:32. This is followed by numerous messages mentioning "rancher-secrets". Docker is finally finished starting at 19:16, 81 minutes later. I rebooted twice, and this 81 minute delay happened both times. I provided proof of this 81 minute delay below.

```
[root@docker6 ~]# journalctl -b -u docker -u systemd |less
-- Logs begin at Mon 2017-06-05 17:54:23 PDT, end at Tue 2017-06-06 11:35:32 PDT. --
Jun 05 17:55:32 docker6.example.org systemd[1]: Starting Docker Application Container Engine...
Jun 05 17:55:32 docker6.example.org docker[1268]: Command "daemon" is deprecated, and will be removed in Docker 1.16. Please run `dockerd` directly.
Jun 05 17:55:34 docker6.example.org docker[1268]: time="2017-06-05T17:55:34.770197274-07:00" level=info msg="libcontainerd: new containerd process, pid: 2589"
Jun 05 17:55:37 docker6.example.org docker[1268]: time="2017-06-05T17:55:37.092945996-07:00" level=warning msg="devmapper: Base device already exists and has filesystem xfs on it. User specified filesystem  will be ignored."
Jun 05 17:55:40 docker6.example.org docker[1268]: time="2017-06-05T17:55:40.737732433-07:00" level=warning msg="Unable to locate plugin: rancher-secrets, retrying in 1s"
Jun 05 17:55:41 docker6.example.org docker[1268]: time="2017-06-05T17:55:41.738065606-07:00" level=warning msg="Unable to locate plugin: rancher-secrets, retrying in 2s"
Jun 05 17:55:43 docker6.example.org docker[1268]: time="2017-06-05T17:55:43.738373190-07:00" level=warning msg="Unable to locate plugin: rancher-secrets, retrying in 4s"
Jun 05 17:55:47 docker6.example.org docker[1268]: time="2017-06-05T17:55:47.738705385-07:00" level=warning msg="Unable to locate plugin: rancher-secrets, retrying in 8s"
Jun 05 17:55:55 docker6.example.org docker[1268]: time="2017-06-05T17:55:55.739135017-07:00" level=warning msg="Error restoring volume" driver=rancher-secrets error="error while checking if volume \"AAAABBBBCCCCDDDD\" exists in driver \"rancher-secrets\": Error looking up volume plugin rancher-secrets: legacy plugin: plugin not found" volume=AAAABBBBCCCCDDDD
Jun 05 17:55:55 docker6.example.org docker[1268]: time="2017-06-05T17:55:55.739325867-07:00" level=warning msg="Unable to locate plugin: rancher-secrets, retrying in 1s"
Jun 05 17:55:56 docker6.example.org docker[1268]: time="2017-06-05T17:55:56.739636974-07:00" level=warning msg="Unable to locate plugin: rancher-secrets, retrying in 2s"
Jun 05 17:55:58 docker6.example.org docker[1268]: time="2017-06-05T17:55:58.739982055-07:00" level=warning msg="Unable to locate plugin: rancher-secrets, retrying in 4s"
Jun 05 17:56:02 docker6.example.org docker[1268]: time="2017-06-05T17:56:02.740296222-07:00" level=warning msg="Unable to locate plugin: rancher-secrets, retrying in 8s"
Jun 05 17:56:10 docker6.example.org docker[1268]: time="2017-06-05T17:56:10.740660119-07:00" level=warning msg="Error restoring volume" driver=rancher-secrets error="error while checking if volume \"EEEEFFFFGGGGGHHHHH\" exists in driver \"rancher-secrets\": Error looking up volume plugin rancher-secrets: legacy plugin: plugin not found" volume=EEEEFFFFGGGGGHHHHH
```

And then, 81 minutes later and numerous errors about rancher-secrets, Docker starts, and eventually Rancher-Agent starts and everything starts behaving normally again.

```
Jun 05 19:15:55 docker6.example.org docker[1268]: time="2017-06-05T19:15:55.742382318-07:00" level=warning msg="Unable to locate plugin: rancher-secrets, retrying in 1s"
Jun 05 19:15:56 docker6.example.org docker[1268]: time="2017-06-05T19:15:56.742713812-07:00" level=warning msg="Unable to locate plugin: rancher-secrets, retrying in 2s"
Jun 05 19:15:58 docker6.example.org docker[1268]: time="2017-06-05T19:15:58.743052281-07:00" level=warning msg="Unable to locate plugin: rancher-secrets, retrying in 4s"
Jun 05 19:16:02 docker6.example.org docker[1268]: time="2017-06-05T19:16:02.743395731-07:00" level=warning msg="Unable to locate plugin: rancher-secrets, retrying in 8s"
Jun 05 19:16:10 docker6.example.org docker[1268]: time="2017-06-05T19:16:10.743667834-07:00" level=warning msg="Error restoring volume" driver=rancher-secrets error="error while checking if volume \"IIIIJJJJKKKKLLLL\" exists in driver \"rancher-secrets\": Error looking up volume plugin rancher-secrets: legacy plugin: plugin not found" volume=IIIIJJJJKKKKLLLL
Jun 05 19:16:10 docker6.example.org docker[1268]: time="2017-06-05T19:16:10.769703597-07:00" level=info msg="Graph migration to content-addressability took 0.00 seconds"
Jun 05 19:16:10 docker6.example.org docker[1268]: time="2017-06-05T19:16:10.782673367-07:00" level=info msg="Loading containers: start."

# NOTE: There are 322 messages like this:
Jun 05 19:16:10 docker6.example.org docker[1268]: time="2017-06-05T19:16:10.850554743-07:00" level=error msg="Failed to load container MMMMNNNNOOOOPPPP: open /var/lib/docker/containers/MMMMNNNNOOOOPPPP/config.v2.json: no such file or directory"
Jun 05 19:16:10 docker6.example.org docker[1268]: time="2017-06-05T19:16:10.852911996-07:00" level=error msg="Failed to load container QQQQRRRRSSSSTTTTUUUU: open /var/lib/docker/containers/QQQQRRRRSSSSTTTTUUUU/config.v2.json: no such file or directory"
... SNIP ....

# And finally Docker starts
Jun 05 19:16:10 docker6.example.org docker[1268]: time="2017-06-05T19:16:10.905994030-07:00" level=info msg="Firewalld running: false"
Jun 05 19:16:11 docker6.example.org docker[1268]: time="2017-06-05T19:16:11.157291757-07:00" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
Jun 05 19:16:11 docker6.example.org docker[1268]: time="2017-06-05T19:16:11.783323629-07:00" level=info msg="Loading containers: done."
Jun 05 19:16:11 docker6.example.org docker[1268]: time="2017-06-05T19:16:11.849633466-07:00" level=info msg="Daemon has completed initialization"
Jun 05 19:16:11 docker6.example.org docker[1268]: time="2017-06-05T19:16:11.849694399-07:00" level=info msg="Docker daemon" commit=c6d412e graphdriver=devicemapper version=17.03.1-ce
Jun 05 19:16:11 docker6.example.org systemd[1]: Started Docker Application Container Engine.
Jun 05 19:16:11 docker6.example.org docker[1268]: time="2017-06-05T19:16:11.861151166-07:00" level=info msg="API listen on /var/run/docker.sock"
Jun 05 19:16:13 docker6.example.org docker[1268]: time="2017-06-05T19:16:13.143427172-07:00" level=error msg="Handler for GET /v1.22/containers/rancher-agent-upgrade/json returned error: No such container: rancher-agent-upgrade"
Jun 05 19:16:13 docker6.example.org docker[1268]: time="2017-06-05T19:16:13.144064048-07:00" level=error msg="Handler for GET /v1.22/images/rancher-agent-upgrade/json returned error: No such image: rancher-agent-upgrade"
```

After this, Rancher-agent starts and everything works well.

---

According to the system logs, 81 minutes elapsed between the "Linux version" message and when Docker starts loading containers.

```
[root@docker6 ~]# egrep 'Linux version|msg="Loading containers: start."' /var/log/messages
# 15:54 to 17:15 is 81 minutes
Jun  5 15:54:38 docker6 kernel: Linux version 3.10.0-514.10.2.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) ) #1 SMP Fri Mar 3 00:04:05 UTC 2017
Jun  5 17:15:07 docker6 docker: time="2017-06-05T17:15:07.465969414-07:00" level=info msg="Loading containers: start."

# 17:54 to 19:16 is 81 minutes
Jun  5 17:54:23 docker6 kernel: Linux version 3.10.0-514.10.2.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) ) #1 SMP Fri Mar 3 00:04:05 UTC 2017
Jun  5 19:16:10 docker6 docker: time="2017-06-05T19:16:10.782673367-07:00" level=info msg="Loading containers: start."
```

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.5.9` Cattle: `v0.178.12` UI: `v1.5.9` |
|Access|`openldap` `admin`|
|Orchestration|`Cattle`|
|Route|`hosts.index`|

OS: CentOS 7.3
Docker version: Docker 17.03.1-ce (docker-engine-17.03.1.ce-1.el7.centos.x86_64)
Docker storage driver: devicemapper with direct-lvm

**Comment by stefanlasiewski** [comment]
Ah! It seems that I have many, many volumes for rancher-secrets.

```
[root@docker6 ~]# docker volume ls |grep -c rancher-secrets
2418
[root@docker6 ~]#
```

Earlier, I pointed out these errors in the Rancher logs:

```
# NOTE: There are 322 messages like this:
Jun 05 19:16:10 docker6.example.org docker[1268]: time="2017-06-05T19:16:10.850554743-07:00" level=error msg="Failed to load container MMMMNNNNOOOOPPPP: open /var/lib/docker/containers/MMMMNNNNOOOOPPPP/config.v2.json: no such file or directory"
Jun 05 19:16:10 docker6.example.org docker[1268]: time="2017-06-05T19:16:10.852911996-07:00" level=error msg="Failed to load container QQQQRRRRSSSSTTTTUUUU: open /var/lib/docker/containers/QQQQRRRRSSSSTTTTUUUU/config.v2.json: no such file or directory"
```

Turns out, the directories at `/var/lib/docker/containers/QQQQRRRRSSSSTTTTUUUU/`  seem to map to volumes for rancher-secrets

**Comment by stefanlasiewski** [comment]
Pruning unused Docker volumes didn't free up these volumes:

```
[root@docker6 ~]# docker volume prune
WARNING! This will remove all volumes not used by at least one container.
Are you sure you want to continue? [y/N] y
Deleted Volumes:
rancher-nfs
123456789012345678901234567890123456789012345678901234567890
abcdefgabcdefgabcdefgabcdefgabcdefgabcdefgabcdefgabcdefgabcdefg
Total reclaimed space: 0 B
[root@docker6 ~]#
```

**Comment by stefanlasiewski** [comment]
I found a list of volumes under Infrastructure > Hosts > docker6 > Storage . They are in a "Detached" state, and there hundreds of them. If I view these volumes in the API, and every volume seems to say that the device is under staging, like:

```
"driverOpts": {
"device": "/var/lib/rancher/volumes/rancher-secrets/staging/0b1557bc3a073c3199fe47af3a66459e89e8aa7a59d6d6d271043a9707343406",
...
}
```

**Comment by cloudnautique** [comment]
HI @stefanlasiewski, definitely looks like you hit a bug. I'm guessing the startup problem is exacerbated by the fact that it queries for the volumes before starting the volume driver container. So it looks like it has to go through all of the backoff per volume. We have something in the works for 2.0 that mitigates the Docker volume behavior. 

Any idea how the 2400 volumes were created? Was there a service that failed to reconcile? Just upgrade/downgrades over a period of time? I'd like to be able to reproduce it and see if we can figure out how there got to be so many. The volume isn't related to the number of secrets in Rancher, every container that needs a secret gets a volume dedicated to it.

**Comment by stefanlasiewski** [comment]
> Any idea how the 2400 volumes were created? 

I'm not sure how 2400 volumes were created. However, this situation is present on all 4 servers in this particular environment (but not in two other environments). The number of volumes is growing. Here's a count from another server in the same environment which also shows this problem:

```
# Yesterday
[root@docker08 ~]# docker volume ls |grep -c rancher-secrets
2419
# today
[root@docker08 ~]# docker volume ls |grep -c rancher-secrets
2459
[root@docker08 ~]#
```

> Was there a service that failed to reconcile?  Just upgrade/downgrades over a period of time?

I think so. This environment is a development environment, and there have been a smattering of issues, and I'm sure my colleagues ran some upgrades and rollbacks.

Our private registry became unavailable from Friday - Monday, and the containers in at least two stacks were stuck in upgrade/rollback loops, which can happen when containers fail in certain ways. One of those may have been using a secret.

Before I ran into this issue, I was rebooting the 4 nodes to try and resolve an inter-host container connectivity issue that I couldn't figure out (Containers within the same stack couldn't always ping each other. But that's a different topic.) I rebooted the first host, and Docker took 81 minutes to start, which is how I found this issue. I'm holding off on rebooting the other three hosts until I figure this out.

I want to highlight that these four CentOS 7.3 hosts are using Devicemapper with direct+lvm, following the recommended procedure at https://docs.docker.com/engine/userguide/storagedriver/device-mapper-driver/#configure-direct-lvm-mode-for-production . I think Devicemapper with Docker might be buggy, and sometimes Devicemapper refuses to delete Devicemapper devices which were requested by Docker.

**Comment by cloudnautique** [comment]
Thanks, will take a look into trying to reproduce. 

This is its own storage driver, and creates a tmpfs mount in the staging directory then does a bind mount when the container starts from the non-staging directory.

**Comment by stefanlasiewski** [comment]
The situation on docker6 has changed since yesterday. I haven't knowingly done anything which would have changed this. 

On this one host, Docker volume no longer shows 2500 docker volumes like I did yesterday, and I see no 'dangling' volumes:

```
[root@docker6 ~]# docker volume ls |grep -c rancher-secrets
0
[root@docker6 ~]# docker volume ls -f dangling=true
DRIVER              VOLUME NAME
[root@docker6 ~]#
```

However, Rancher still shows hundreds of "detached" under ' Infrastructure > Hosts > docker6 > Storage', and restarting Docker still takes 80+ minutes.

The only thing I did since yesterday was:

1. I "evacuated" this host from Rancher
2. I restarted Docker and went home.
3. Docker started 1+ hour later.
4. Rancher-agent started soon after Docker
5. And then around 10AM this morning I reactivated this host in Rancher, and the Rancher Infrastructure Stack came up.
6. Then later, I noticed that `docker volume ls` no longer showed thousands of volumes.

I have no idea what changed.

**Comment by stefanlasiewski** [comment]
@cloudnautique Have you had any luck reproducing this?

One more clue. Three servers in my environment still have this problem. `docker volume ls -f dangling=true |grep rancher-secrets` lists the exact same volume names on all three nodes. Is that right? Shouldn't the volumes have completely unique IDs on the three different nodes?

Here's a comparison of the last 10 volumes listed on each node:

```
[root@docker08 ~]#  docker volume ls -f dangling=true |grep rancher-secrets |tail -10
rancher-secrets     ff33249048160b7c685a5818cf60ec62b7a38864bd46ac17278ee0090635fbd1
rancher-secrets     ff42c1d39c074a7a4b1b50d7e4423e65e40d4da2dc4a5e4a02af9b0b365706f2
rancher-secrets     ff6e969c2fb681f933037c5f99c081d961eb90dc2b0ad280663b629407688f28
rancher-secrets     ff7fc24593d5c8d95f1eebca226fc609a9621c0098eb63b6ad59a6a4dc27dfc3
rancher-secrets     ff8d86c3925661eb7ee9b263656b2c18787d4ed890d3c3fc7400c838b51213e4
rancher-secrets     ff91deaaeeb777719de53df1becddd3baef4354ccf5d149049e9842e62b0226a
rancher-secrets     ff9394cde499a372eaf36ee2b55bc7cf46d40c2ab03340c6f250c6df337a2c71
rancher-secrets     ffce40674c6b8e1ca7a88029f8730a8be6d93c1edb23602b380027224c46d10d
rancher-secrets     ffd8f1cb0fc650f246124411d7f6a14b3269781acfa031235473ba22ae90baeb
rancher-secrets     ffde06cf1d1afd81389db2d0bd6323333e33f9d4bcdc867ed357b51236c25764
[root@docker08 ~]# 
```

```
[root@docker07 ~]#  docker volume ls -f dangling=true |grep rancher-secrets |tail -10
rancher-secrets     ff33249048160b7c685a5818cf60ec62b7a38864bd46ac17278ee0090635fbd1
rancher-secrets     ff42c1d39c074a7a4b1b50d7e4423e65e40d4da2dc4a5e4a02af9b0b365706f2
rancher-secrets     ff6e969c2fb681f933037c5f99c081d961eb90dc2b0ad280663b629407688f28
rancher-secrets     ff7fc24593d5c8d95f1eebca226fc609a9621c0098eb63b6ad59a6a4dc27dfc3
rancher-secrets     ff8d86c3925661eb7ee9b263656b2c18787d4ed890d3c3fc7400c838b51213e4
rancher-secrets     ff91deaaeeb777719de53df1becddd3baef4354ccf5d149049e9842e62b0226a
rancher-secrets     ff9394cde499a372eaf36ee2b55bc7cf46d40c2ab03340c6f250c6df337a2c71
rancher-secrets     ffce40674c6b8e1ca7a88029f8730a8be6d93c1edb23602b380027224c46d10d
rancher-secrets     ffd8f1cb0fc650f246124411d7f6a14b3269781acfa031235473ba22ae90baeb
rancher-secrets     ffde06cf1d1afd81389db2d0bd6323333e33f9d4bcdc867ed357b51236c25764
[root@docker07 ~]# 
```

```
[root@docker06 ~]#  docker volume ls -f dangling=true |grep rancher-secrets |tail -10
rancher-secrets     ff33249048160b7c685a5818cf60ec62b7a38864bd46ac17278ee0090635fbd1
rancher-secrets     ff42c1d39c074a7a4b1b50d7e4423e65e40d4da2dc4a5e4a02af9b0b365706f2
rancher-secrets     ff6e969c2fb681f933037c5f99c081d961eb90dc2b0ad280663b629407688f28
rancher-secrets     ff7fc24593d5c8d95f1eebca226fc609a9621c0098eb63b6ad59a6a4dc27dfc3
rancher-secrets     ff8d86c3925661eb7ee9b263656b2c18787d4ed890d3c3fc7400c838b51213e4
rancher-secrets     ff91deaaeeb777719de53df1becddd3baef4354ccf5d149049e9842e62b0226a
rancher-secrets     ff9394cde499a372eaf36ee2b55bc7cf46d40c2ab03340c6f250c6df337a2c71
rancher-secrets     ffce40674c6b8e1ca7a88029f8730a8be6d93c1edb23602b380027224c46d10d
rancher-secrets     ffd8f1cb0fc650f246124411d7f6a14b3269781acfa031235473ba22ae90baeb
rancher-secrets     ffde06cf1d1afd81389db2d0bd6323333e33f9d4bcdc867ed357b51236c25764
[root@docker06 ~]# 
```

**Comment by stefanlasiewski** [comment]
@cloudnautique Have you had any luck reproducing this? I still have this problem on two nodes.

It's fixed itself on two other nodes, but I'm really not sure how.

**Comment by ket4yii** [comment]
@stefanlasiewski It's well-known issue and happens with all rancher's storage plugins. For example related issue #8433.

**Comment by stefanlasiewski** [comment]
@ketchoop I'm on that ticket also. While the issue shares some of the same behavior, it's a different issue.

The fundamental issue here is that rancher-secrets created 2500 volumes about 5 weeks ago and Rancher doesn't clean them up.

I only have 2 secrets in this particular environment.

**Comment by stefanlasiewski** [comment]
As a workaround, I'm going to try and clean these volumes using the CLI. I'll post a status when this completes.

```
$ ./rancher volume ls |grep -c "detached.*rancher-secrets"
2454
$ ./rancher volume ls |grep "detached.*rancher-secrets" | awk '{print $2}' |head -1000 |while read volume; do rancher volume rm $volume; done
```

**Comment by besishblia** [comment]
priority this please!!

**Comment by aemneina** [comment]
worked with @stefanlasiewski and @cjellick on this. we noticed the docker volumes metadata.db was ~2mb. Which is large for a system with a handful of volumes. We backed up and removed the metadata file then restarted docker. Docker restarted fairly quickly and rebuilt its volumes metadata db. Ensure you have proper data backups/persistence in place in the case that docker doesnt recover. This could potentially void warranties and or cause excommunication from your place of worship. You've been warned. 
The long term goal here for rancher-secrets is to move away from docker volumes. Flapping containers can cause orphaned volumes, and with the right constellation alignment docker wont clean up after itself.

**Comment by stefanlasiewski** [comment]
Here is some more information. It looks like metadata.db may have stale data.

metadata.db was larger than expected:
```
[root@docker05 ]# ls -ld /var/lib/docker/volumes/metadata.db
-rw-------. 1 root root 2097152 Jul  5 18:31 metadata.db
[root@docker05 ]#
```

There should be no rancher-secrets volumes on this node:

```
[root@docker05 ]# docker volume ls |grep -c rancher-secrets
0
[root@docker05 ]#
```

Searching metadata.db shows many occurrences of Rancher secrets.

```
# Searching the metadata file shows many occurrences of rancher-secrets
[root@docker05 ]# hexdump -C /var/lib/docker/volumes/metadata.db |grep -c secrets
1406
[root@docker05 ]# strings /var/lib/docker/volumes/metadata.db |grep -ic rancher-secrets
478
[root@docker05 ]# 
```

After `mv /var/lib/docker/volumes/metadata.db ~/tmp/metadata.db.bak && systemctl restart docker`; Docker re-populates metadata.db and it's now 32K:

```
[root@docker05 ]#  ls -ld /var/lib/docker/volumes/metadata.db
-rw------- 1 root root 32768 Jul  7 16:24 /var/lib/docker/volumes/metadata.db
[root@docker05 ]# hexdump -C /var/lib/docker/volumes/metadata.db |grep -c secrets
0
[root@docker05 ]# docker volume ls |grep -c rancher-secrets
0
[root@docker05 ]#
```

And Docker now restarts in < 1 minute: ```
[root@docker05 ]# time systemctl restart docker

real    0m45.688s
user    0m0.017s
sys     0m0.019s
[root@docker05 ]#
```

**Comment by cloudnautique** [comment]
I have been able to reproduce the behavior when "evacuating" hosts from Rancher. The volumes are removed from Rancher and the host according to our volume driver. However, the `docker volume ls` still lists the docker volumes. Restarting Docker, or rebooting the host, results in the lengthy startup time where each volume is queried by the daemon and undergoes a series of timeouts. The timeouts are caused because the volume driver is not running, it is a container and the Docker Daemon isn't finished starting.

**Comment by wallnerryan** [comment]
@cloudnautique seeing the same thing with other volume drivers as well.

**Comment by wallnerryan** [comment]
is there an upstream docker-ce bug for this?

**Comment by cloudnautique** [comment]
@wallnerryan, not sure if there is an upstream issue. We are still using the older docker plugin model. We have some plans on how to handle this in the future.  But, yes this isn't exclusive to secrets all volume drivers run this risk.

Can you confirm how you end up in the situation? Are you using the "Evacuate" host functionality?

**Comment by wallnerryan** [comment]
@cloudnautique im actually not using rancher. 

Im using docker 1.13.1 with lvm/devicemapper on centos 7.3.

I see this when nodes are up for some time and accumulate volumes and then just a reboot with cause this, having the daemon stuck for about 50+ minutes on the timeouts.

**Comment by wcgcoder** [comment]
@deniseschannon will that fix still be implemented in 1.6 per the label on this issue? Thanks!

**Comment by soumyalj** [comment]
Reproduced the issue with v1.6.14 release. 
Launched rancher-secrets catalog on a 3 host setup(h1,h2,h3). 
Created 2 secrets and around 50 containers using the secrets. 
With 50 containers on host h3, evacuated the host.
After host evacuation checked that docker volumes still existed.
Activated the host and issued the command `time service docker restart`
It took around 7minutes for docker to restart completely.
root@soumyasecrettest3:~# time sudo service docker restart
```
real	7m41.868s
user	0m0.012s
sys	0m0.004s
```

**Comment by stefanlasiewski** [comment]
Once this is fixed, what would be the proper way to clean up the rogue docker-secrets volumes. Is there a more elegant solution besides `rm /var/lib/docker/volumes/metadata.db && systemctl restart docker`

**Comment by ijansch** [comment]
I have a setup where the workaround with metadata.db doesnt seem to work. The file gets recreated, is at 32kb, but immediately syslog start filling up with "Unable to locate plugin: rancher-nfs, retrying in ..." messages. Were there any other workarounds?

**Comment by stefanlasiewski** [comment]
Hey @ijansch : Removing metadata.db won't resolve rancher-nfs issues. The 'rancher-nfs' issue is a different but similar bug. See #8433
