### ISSUE TITLE
How to setup sidekick with the same network of primary service ?

### ISSUE THREAD

**Issue by artemus717** [rancher/rancher#8992]
**Rancher versions:**
rancher/server: 1.5.5
rancher/agent:

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
1.12.6
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**

**Results:**

SIDEKICK SERVICES
Rancher supports the colocation, scheduling, and lock step scaling of a set of services by allowing users to group these services by using the notion of sidekicks. A service with one or more sidekicks is typically created to support shared volumes (i.e. --volumes_from) and networking (i.e. --net=container) between containers.

In Cattle mode with managed network , sidekick and primary service containers have different ip address within containers.
For example ,  I run a nginx in primary container and i want a varnish in sidekick container communicate with nginx using 127.0.0.1

**Comment by aemneina** [comment]
@artemus717 I think this might be an example of how to do this:
https://github.com/rancher/rancher-catalog/blob/master/infra-templates/ipsec/8/docker-compose.yml#L24

**Comment by artemus717** [comment]
@aemneina 
Thanks , I will have a look .

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
