### ISSUE TITLE
Rancher Server gets internal IP after some time instead of the assigned Public IP

### ISSUE THREAD

**Issue by kongreddgrass** [rancher/rancher#8993]
**Rancher versions:**
rancher/server: 1.5.10
rancher/agent: 1.2.2

**Infrastructure Stack versions:**
healthcheck: 0.2.3
ipsec: 0.11.2
network-services: 0.6.6
scheduler: 0.7.5
kubernetes (if applicable): no, use cattle

**Docker version: (`docker version`,`docker info` preferred)** 
Containers: 21
 Running: 15
 Paused: 0
 Stopped: 6
Images: 78
Server Version: 1.12.6
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp selinux
Kernel Version: 4.9.24-coreos
Operating System: Container Linux by CoreOS 1353.8.0 (Ladybug)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.801 GiB
Name: gabi
ID: IZBS:MVYL:BOO2:J4DF:DIVZ:TAZO:ASTZ:GO45:36QE:NDWT:W4ZZ:VIJQ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 10.0.3.102:5000
 127.0.0.0/8

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
4.9.24-coreos

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Private Server / runs on ESX-Server

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Server 1: Rancher Server and Main Server with internal DB, single node
Server 2 and Server 3 added some days ago

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
If the Server 1 reboots, the public IP is correct (10.0.3.102) and all rancher-services start correctly.
IP-tables shows the correct ip:

hoshi tharoot # iptables -L -n -t nat | grep 8080
MASQUERADE  tcp  --  172.17.0.1           172.17.0.1           tcp dpt:8080
DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:8080 to:172.17.0.1:8080

Server 1 can correspond with Server 2 and 3 and deploy the container on all host perfectly.
After some hours, Server 1 shows under "Infrastructure->Hosts" not the public  IP. It shows the docker IP 172.17.0.1 and IP-tables shows now the wrong IP:

hoshi tharoot # iptables -L -n -t nat | grep 8080
MASQUERADE  tcp  --  172.17.0.2           172.17.0.2           tcp dpt:8080
DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:8080 to:172.17.0.2:8080

**Results:**
Everytime when the "Public IP" is 172.17.0.1, the services "healthcheck" and "scheduler" stucks at "initializing". 

**Quick temporary troubleshooting**
Restart the Rancher Server 1, the services came up and everything works until the next crash.

**further information**
To prevent this problem, i added some lines in the /etc/hosts, but i think, this wouldn't help.

172.17.0.1      localhost
10.0.3.102      localhost

**Final**
what can i do to fix this issue, or is this issue in rancher?

**Comment by superseb** [comment]
Please specify `CATTLE_AGENT_IP` when multihomed/NAT or when running `rancher/agent` on the same machine as `rancher/server`.

See documentation here: https://docs.rancher.com/rancher/v1.6/en/faqs/troubleshooting/#are-the-ips-of-the-hosts-correct-in-the-ui

This should solve your problem.

**Comment by kongreddgrass** [comment]
Thank you very much for the fast response. This was the ultimative solution. 
With every day I like Rancher even more. The documentation is super described. :-)
