### ISSUE TITLE
Search on docs.rancher.com link to incorrect version docs

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#8996]
Steps to reproduce:

1. Navigate to http://docs.rancher.com/rancher/v1.6/en/
2. In top right search bar, enter the search string: load balancer

Expected result:
1. Links to v1.6 docs are displayed in the overlay window

Actual result: 
1. Overlay window is clogged with ads, user needs to scroll to see results
2. There are no links to 1.6 docs, instead results for v1.1, v1.2 etc. docs are displayed

**Comment by wjimenez5271** [comment]
This is a good point I feel the docs search experience could be a lot better

**Comment by wjimenez5271** [comment]
at the risk of throwing a hammer at this, I wonder if any of these tools for static site search would be helpful:

* https://blog.algolia.com/instant-search-blog-documentation-jekyll-plugin/
* https://learn.cloudcannon.com/jekyll/jekyll-search-using-lunr-js/

**Comment by deniseschannon** [comment]
Fixed

**Comment by janeczku** [comment]
@deniseschannon there are still issues: For example "latest" returns different search results than "1.6". Aren't there better search solutions? @wjimenez5271 
![search-results](https://user-images.githubusercontent.com/3813921/27135548-0d10ed38-5119-11e7-854a-69616488d51f.png)

**Comment by deniseschannon** [comment]
@janeczku This occurs as there are very few docs which have re-directs for `latest`. I've removed the `latest` from the search box as it doesn't help users as we don't have a specific `latest` folder to search on.
