### ISSUE TITLE
agent should detect and log the fact firewalld is active/running

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#8999]
Ran into a situation where firewalld was clobbering requests to program iptables rules. Agent could detect and warn about this in its logs.

**Comment by leodotcloud** [comment]
Related reading: https://groups.google.com/forum/#!topic/coreos-dev/AXCs_2_J6Mc

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
