### ISSUE TITLE
Exclude load balancers from evacuation 

### ISSUE THREAD

**Issue by ebr** [rancher/rancher#9001]
**Rancher versions:**
rancher/server: 1.5.8
rancher/agent: 1.2.2

**Infrastructure Stack versions:**
healthcheck: 0.2.3
ipsec: holder
network-services: 0.9.1/0.6.6
scheduler: 0.7.5

**Docker version: (`docker version`,`docker info` preferred)**
1.12.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher, external DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Perform `Evacuate` on a host

**Results:**
All user containers removed, including Load Balancers.

**Expectation**
Load balancers should be left running while all other user containers are removed.

There is justification for leaving Load Balancers running. This would help with **controlled** migrations to new hosts in case where there's a "bulkhead" load balancer in front of the Rancher load balancers, instead of relying on healthchecks alone.

Here's an example: We have an Nginx reverse proxy in front of all Rancher hosts that acts as a load balancer. It is orchestrated by something that isn't Rancher-aware. We need to replace Rancher hosts that are behind this LB. Not all of our services have healthchecks configured, for reasons beyond this scope.

- If we terminate Rancher hosts first, the Nginx LB stops sending traffic to them right away. But there is a delay before Rancher healthchecks fail and it figures out those hosts are dead _(unless we deactivate them and delete from Rancher at just the right moment - not realistic)_. So LBs on the "live" hosts still try sending *some* traffic to the now-dead worker containers.
- If we delete those hosts from Rancher first, OR `Evacuate` them, the Nginx LB is not aware of this, and until its own healthchecks fail, it will try sending traffic to those hosts.

If we were able to `Evacuate` just the service containers, but not the load-balancers, we could then:
- Launch new hosts (traffic goes to both `old` and `new`, workers handle requests on both `old` and `new`)
- Evacuate old hosts (traffic goes to both `old` and `new`, workers handle requests only on `new`, Rancher LBs are aware of this)
- Terminate old hosts (traffic goes to `new` only)
- Remove old hosts from Rancher

This would enable true zero-downtime migrations without additional pains. 
We currently execute a variant of this process: setting "old" hosts to "Inactive" and then upgrading **each worker service** to remove those containers from deprecated hosts, before finally terminating them and deleting from Rancher....... very manual and tedious).

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
