### ISSUE TITLE
Untested docker version banner not showing up in Main Host page

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#9006]
**Rancher versions:** 6/7

**Steps to Reproduce:**
1.  Add a host using Docker 17.05.0-ce

**Results:**  Untested Docker version banner is missing from main Host page.

**Comment by westlywright** [comment]
Appears as a tooltip around the docker version number in master.

**Comment by tfiduccia** [comment]
Version - master 9/19
Verified fixed
