### ISSUE TITLE
Service reporting upgraded after first container

### ISSUE THREAD

**Issue by HcgRandon** [rancher/rancher#9007]
**Rancher versions:**
rancher/server: v1.6.0
rancher/agent: v1.2.2

**Infrastructure Stack versions:**
healthcheck: v0.3.1
vxlan: v0.11.2
network-services: metadata: v0.9.1, manager: v0.7.0
scheduler: v0.7.5
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
2 x 17.03.0-ce
3 x 17.03.1-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
5 x Debian 8: uname -r: 3.16.0-4-amd64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle w/ vxlan

**Steps to Reproduce:**
Create a stack with 5 of the same image services each service is set to start all containers on one host
Service1 -> host1
Service2 -> host2
...

Set each service to 20 containers

Start a upgrade on several of the services.

**Results:**
Some of the upgrades will report 'upgraded' after the first container on the host, this container never starts just stays stopped. and the only way to progress the upgrade is to click 'Finish upgrade' causing the ability to rollback to be lost

**Comment by GiGurra** [comment]
I've seen this behavior as well

**Comment by superseb** [comment]
Probably fixed by https://github.com/rancher/rancher/issues/12084, let me know if it happens on the latest version.
