### ISSUE TITLE
Is there any way to retrieve container sequence number as ${CONTAINER_SEQ} and use it to pass through env variables to container

### ISSUE THREAD

**Issue by xeagle2** [rancher/rancher#9008]
Hi there,

This is mostly the question if there any way to retrieve container sequence number as ${CONTAINER_SEQ} and use it to pass through env variables to container.

For example: when I have service in terms of rancher and many scaled containers across different hosts, in a list the of containers each one is named as 

{container}-**1**
{container}-**2**
{container}-**3**
....

When the container is launched, is there any way to get access to that sequence id **1**, **2**, **3** or use some variable in ranched to pass it through the container configuration > environment variables?

Looking forward to hearing from you soon.

Thank you,

**Comment by vincent99** [comment]
No, but it's in metadata (create_index)

**Comment by xeagle2** [comment]
Hi @vincent99,

Thanks for the answer.

If I understand correctly, it means that there is a possibility to have a rest call to rancher rest meta data api to retrieve this information somehow knowing some input parameters. It looks a bit complicated, we would need anyway to pass the service name, container name to container configuration or maybe also something like container id to retrieve this kind of information.

Would be great if other more simple way exists to retrieve this kind of data.

Thank you,

**Comment by vincent99** [comment]
You don't need to know those, metadata knows what container is asking for it and has a secton fro "self".  So you want `curl http://rancher-metadata/2016-07-29/self/container/create_index`

**Comment by xeagle2** [comment]
Thanks for the suggestion! I will try this option!

**Comment by xeagle2** [comment]
It works and solves my current case! Thanks again for your assistance!
