### ISSUE TITLE
RBAC: Changing account settings for users doesn't affect access to k8s API

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#9011]
**Rancher versions:**
rancher/server: v1.6.1
kubernetes (if applicable): 1.6

**Steps to Reproduce:**
- Enable Github authentication
- Deploy kubernetes with RBAC enabled
- Add `user1` to k8s environment as member.
- Login with `user1`
- Try to query kubernetes API:
```
$ kubectl get nodes
Error from server (Forbidden): the server does not allow access to the requested resource (get nodes)
```
- Login with admin user and change the account setting for `user1` from user to Admin
- Wait for 5 minutes
- Login with user1 and try to query the API again

**Expected Results**

The user1 should has full access to the kubernetes API after being an admin.

**Results:**
user1 query still showing (Forbidden error)

**Comment by joshwget** [comment]
Discussed with @galal-hussein. This is expected since being made an admin for a Rancher installation shouldn't give a user access to clusters in every environment. An admin could manually make themselves an owner for environments of their choice though.
