### ISSUE TITLE
Can't edit scaling group created by Catalog

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#9012]
**Rancher versions:** 6/8

**Steps to Reproduce:**
1.  Add a catalog template
2.  Go to Main Scaling Group page and try to edit the scaling group inside the stack.

**Results:**  Subscribe ping (projectId=1a12, sockId=1)
route.js:75 Application Error TypeError: Cannot read property 'forEach' of null

![image](https://user-images.githubusercontent.com/11514927/26955888-c11598c4-4c6e-11e7-898c-6a750f296301.png)

**Comment by vincent99** [comment]
Catalog creates services with secondaruLaunchConfigs null instead of empty array.

**Comment by tfiduccia** [comment]
Version - Wagyu (master 7/25)
Verified fixed
