### ISSUE TITLE
Web Socket Subscription Errors in Browser don't surface in UI

### ISSUE THREAD

**Issue by wjimenez5271** [rancher/rancher#9013]
**Rancher versions:**
rancher/server: 1.6.1-rc9
rancher/agent: N/A

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**

1. Connect to rancher server UI in an environment where something is interfering with web sockets

**Results:**
No error message in UI, only new events don't get detected. This caused extended troubleshooting because we thought a host was not being added that in fact was. Chrome debug showed websocket subscription errors after further investigation.

**Comment by vincent99** [comment]
There is no access to the underlying error in the js websocket client, so all we can possibly do is show "not connected for some reason".

**Comment by wjimenez5271** [comment]
That would be sufficient, at least user would know to suspect the data they were viewing
________________________________

**Comment by vincent99** [comment]
Adding as part of #7389.
