### ISSUE TITLE
Maybe a bug,rancher/server container broken and could not restart

### ISSUE THREAD

**Issue by lvhuat** [rancher/rancher#9014]
**Rancher versions:**
rancher/server:1.3 and 1.6 both 

`1.6` for mysql HA 
`1.3` for run container directly

i don't known how to do, it just happen one day

docker logs --tail  containerId,any it say:
./run not found.

so i `dock exec -it` into the container,i found that the `/service` has changed

Normally, the folder structure is:
```
/service
    |
   cattle/{event/,supervise/,run,finish}
    |  
    |
   mysql/
```
when broken, it come to be:
```
/service
   |
   cattle/
   |
   mysql/
   |
   event/
   |
   supervise/
   |
   run
   |
   finish
```
Maybe the folders of  [event & supervise] in cattle before were all moved out.
So it repaired the forders, it could be restart and work well again.

**Comment by superseb** [comment]
Not really sure what happened in this case, if you have a way to reproduce on the latest version, let me know.
