### ISSUE TITLE
Admin should be able to turn off automatic project creation

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#9016]
When a user logs into Rancher and they don't belong to any projects, Rancher creates a project for them.
We need to add a setting to turn this feature off.

The code that creates the project is here: io.cattle.platform.iaas.api.auth.projects.ProjectResourceManager.createProjectForUser(Identity)

When the backend is done, @vincent99 will need to add this to the Admin UI.

Will need backported to 1.6

**Comment by cjellick** [comment]
Need to figure out setting name with @vincent99 and @ibuildthecloud

**Comment by amy** [comment]
Need to document authentication files for various roles. Will hold off on documentation until later when the feature is implemented in cattle.

**Comment by amy** [comment]
The label we decided on is: `project.create.default=false`

**Comment by amy** [comment]
To turn off automatic project deletion:
Sign in as an admin
Hit this endpoint: `http://your-rancher-server:8080/v2-beta/settings/project.create.default`
Click on edit
change the fieldname `value` to `false`

**Comment by soumyalj** [comment]
Tested with master 1.6 branch. 
1. Created a cattle setup. Logged in as an admin and set ```project.create.default``` as ```false``` by using the below settings link
http://your-rancher-server:8080/v2-beta/settings/project.create.default
2. Created a new user by adding the user in access control and logged in 
3. A new default environment was not created.

When project.create.default was set as true, a default environment got created when a new user was added and signed in.
