### ISSUE TITLE
Test, Bug fix, and Document controlling RBAC via auth json files

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#9017]
There is currently a feature that would allow admins to override our auth controls by bind mounting a json file into the rancher/server contianer.

The file would follow the same format as our [project-auth.json file](https://github.com/rancher/cattle/blob/4b2210b4eedf1790410ac51aa67a8100737a5cf1/resources/content/schema/project/project-auth.json).

We specifically want to prove that using this you can turn off the ability for users to create projects

**Comment by amy** [comment]
These are the permissions customizations we would also like to make:
*Role* -> *What it maps to in our roles* | *How it should behave* | *Overrides needed*
Admin -> Admin | Just like admin | None
Environment Admin -> Environment Owner | Just like owner: can do anything in the env including add/remove users | None
Environment Access Admin -> Member | can add/remove users | Need to take CUD away from hosts, physical hosts, & machines
Environment member -> Restricted member | cannot add/remove users| No mods needed*
Read Only -> Ready only | Can just read everything in envs | None (edited)

Sample json files for environment overrides. This will allow the override case where you do not want non-admin users to be able to create, update, or delete environments.
admin permissions file:
```
// admin-auth.json
{
    "authorize" : {
        "project" : "crud",
        "end" : ""
    }
}
```
user permissions file:
```
// user-auth.json
{
    "authorize" : {
        "project" : "r",
        "end" : ""
    }
}
```

This command will bind mount your user permissions to your Rancher server. Edit the local paths to point to your respective admin-auth.json and user-auth.json.
```
docker run -d -p 8080:8080 \
    -v /local/path/to/admin-auth.json:/usr/share/cattle/war/schema/admin/admin-auth.json.d/overrides/admin-auth.json \
    -v /local/path/to/user-auth.json:/usr/share/cattle/war/schema/user/user-auth.json.d/overrides/user-auth.json \
    rancher/server:stable
```

---------------
Overall, for overrides for more granular roles, you must find the role in `/code/packaging/app-config/src/main/resources/META-INF/cattle/legacy/spring-legacy-context.xml`
and use the class path as a mount point inside the docker container like in the run command above. Same json file permissions that you can use for mounting inside the
container are located in ./resources/content/(the class path of role you found in spring-legacy-context.xml)

**Comment by soumyalj** [comment]
@cjellick , @amy : 1.Do we have separate auth.json files for each of the roles where we can provide different permissions and try ?
2. Can these permissions be set for only project or for any object such as service/container ?

**Comment by cjellick** [comment]
@soumyalj they can be set for anything, but thats not the scope of testing. scope of testing are just a few specific scenarios needed to meet user requirements

**Comment by cjellick** [comment]
Yes, separate auth files per role

**Comment by amy** [comment]
How to test `Environment Access Admin -> Member | can add/remove users | Need to take CUD away from hosts, physical hosts, & machines`

To allow environment members to add/remove users: 
Change this setting `http://localhost:8081/v2-beta/settings/set.member.roles` to `owner,members`

To disallow environment members from CUD hosts...
Create this file
```
// member-auth.json
{
    "authorize" : {
        "machine": "r",
        "machine.authCertificateAuthority": "r",
        "machine.authKey": "r",
        "machine.dockerVersion": "r",
        "machine.driver": "r",
        "machine.engineEnv": "r",
        "machine.engineInsecureRegistry": "r",
        "machine.engineInstallUrl": "r",
        "machine.engineLabel": "r",
        "machine.engineOpt": "r",
        "machine.engineRegistryMirror": "r",
        "machine.engineStorageDriver": "r",
        "machine.externalId": "r",
        "machine.labels": "r",
        "machine.name": "r",

        "host" : "r",
        "host.agentState" : "r",
        "host.agentId" : "r",
        "host.computeTotal" : "r",
        "host.hostname" : "r",
        "host.info" : "r",
        "host.physicalHostId" : "r",
        "host.zoneId" : "r",
        "host.labels" : "r",
        "host.publicEndpoints" : "r",
        "host.agentIpAddress" : "r",
        "host.instanceIds" : "r",
        "host.localStorageMb" : "r",
        "host.memory" : "r",
        "host.milliCpu" : "r",
        "host.stackId" : "r",
        "host.hostTemplateId" : "r",

        "end" : ""
    }
}
```

docker run -d -p 8080:8080 \
    -v /local/path/to/member-auth.json:/usr/share/cattle/war/schema/member-auth/member-auth.json.d/overrides/member-auth.json \
    rancher/server:stable

**Comment by amy** [comment]
Note: All sub-permissions (i.e. host.* and machine.* are needed to override permissions. Just setting "host": "r" and "machine": "r" does not override the sub-permissions.)

**Comment by soumyalj** [comment]
Issues filed for this feature:
https://github.com/rancher/rancher/issues/9170
https://github.com/rancher/rancher/issues/9183
https://github.com/rancher/rancher/issues/9184

**Comment by m4ce** [comment]
I was looking for this specific feature in the official docs and I couldn't find it :/ it might be good to document this. I am using GitHub issues as my source of documentation at current...
