### ISSUE TITLE
Azure MySQL: "this user requires mysql native password authentication."

### ISSUE THREAD

**Issue by fkollmann** [rancher/rancher#9018]
**Rancher versions:**
rancher/server: 1.6.2
rancher/agent: -

**Infrastructure Stack versions:**
---

**Docker version: (`docker version`,`docker info` preferred)**
17.03.0-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 14.04.5 LTS

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Azure VM

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
external DB: Azure MySQL

CATTLE_DB_CATTLE_DATABASE=mysql
CATTLE_DB_CATTLE_MYSQL_HOST=exg-rancher.mysql.database.azure.com
CATTLE_DB_CATTLE_MYSQL_NAME=rancher
CATTLE_DB_CATTLE_MYSQL_PORT=3306
CATTLE_DB_CATTLE_USERNAME=rancher@exg-rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
run clean docker image for rancher server with Azure MySQL connection.

```bash
# pull the new image
DOCKERIMAGE="rancher/server:v$(get_octopusvariable 'Octopus.Release.Number')"

sudo docker pull $DOCKERIMAGE

# run the new container
sudo docker run -d --restart=unless-stopped -p 80:8080 -p 8080:8080 -p 9345:9345 $DOCKERIMAGE \
    --db-host "$(get_octopusvariable 'RancherDbHostname')" \
    --db-port "$(get_octopusvariable 'RancherDbPort')" \
    --db-user "$(get_octopusvariable 'RancherDbUsername')" \
    --db-pass "$(get_octopusvariable 'RancherDbPassword')" \
    --db-name "$(get_octopusvariable 'RancherDbName')" \
    --advertise-address $(hostname -I | sed -r 's/.*?(10\.229\.[0-9\.]+).*/\1/')
```

**Results:**
`level=fatal msg="this user requires mysql native password authentication."`

**Comment by fkollmann** [comment]
The official statement from Microsoft Azure Support (REG:117061315887758):

> For JDBC connectivity, we support the use of MySQL Connector/J 5.1.
> Please find a list of connection libraries for Azure Database for MySQL at "Connection libraries for Azure Database for MySQL | Microsoft Docs" (https://docs.microsoft.com/en-us/azure/mysql/concepts-connection-libraries).
> 
> The connection libraries listed in the document are those that we tested and we ensured are properly working. We are also making sure that further development in Azure Database for MySQL does not break them.
> 
> We are developing the service in accordance to MySQL official protocol specifications. We noticed that there are implementation issues with certain libraries that cause incompatibility. We are actively working with the community to address these issues, so we expect to expand the list of supported libraries over time.

**Comment by janeczku** [comment]
@fkollmann Native password authentication has to be explicitly enabled for the catalog service. Please give this a try:

```console
docker run -e CATTLE_DB_CATTLE_GO_PARAMS="allowNativePasswords=true"  (...) rancher/server:stable
```

**Comment by fkollmann** [comment]
Specifying the environment variable `CATTLE_DB_CATTLE_GO_PARAMS="allowNativePasswords=true"` did resolve the issue.

@janeczku The issue is resolved, from my POV.

**Comment by janeczku** [comment]
Great, thanks for confirming @fkollmann
