### ISSUE TITLE
Rework volume scope documentation for local storage

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#9019]
The documentation around volume scopes is geared toward shared storage. We must rework documentation to clearly document the behaviour with regards to scopes and scheduling for local volumes depending on whether they were defined in-line (v1 form) or in the top-level volume key (v2 form). Most importantly:
- top-level declared volumes create stack scoped volumes by default and Rancher will take care of scheduling additional services consuming that volume to the corresponding host
- inline/v1 declared volumes are not managed by Rancher at all and are just passed through to Docker. That means users needs to use host affinity rules to consume that volume in other services.

Specific points of confusion that were brought up that need clarification:
- The behavior when you have mixed-mode of some volumes defined at the top level and some defined only within a service's volume section
- The concept of a "host scoped" volume, which is effectively what you get when using local storage.
- That this is valid syntax and is the most succinct way to get local stack scoped volumes:
  ```
  volumes:
    vol-foo: {}
  ```
- If we don't fix it by raising an error (tracked here #9020), we need to at least document that while `volumes: {}` is valid syntax, it will not created any stack scoped volumes and it is not equivalent to `volumes: foo: {}`
- If we dont fix it by raising an error when you have an unused top-level volume (tracked here #9021), we need to document that volumes declared at the top level that are not used by any service are simply ignored

As part of this rework, the documentation [here](https://docs.rancher.com/rancher/v1.5/en/rancher-services/storage-service/#volume-scopes):
> “By default, all volumes are created at the stack scope. Services referencing the same volume in a Compose file or stack will be sharing the same volume. When launching a new stack from the same Compose file, a new volume will be created. When a stack is deleted, its corresponding volumes are removed.”

should be clarified to read:
> “By default, all volumes **defined in the volumes section** are created at the stack scope. Services referencing the same volume in a Compose file or stack will be sharing the same volume. When launching a new stack from the same Compose file, a new volume will be created. When a stack is deleted, its corresponding volumes are removed.”

And additional clarification should be added that says:
> If a volume appears in a service definition but does not have a corresponding definition in the `volumes` section, then it will not be treated as a stack scoped volume. It will be created on-demand when the corresponding container is deployed to a host.

**Comment by janeczku** [comment]
We also need to clarify the behaviour for local volumes that are created or attached via "Add Service" in the UI.
- What scope does the volume have?
- Does Rancher take care of scheduling other services consuming that volume to the corresponding hosts?
- Can the UI behaviour be replicated by creating a stack from a docker-compose file?
