### ISSUE TITLE
Rancher 1.6.1 does not use X-Forwarded-Context and thus does not work behind reverse proxy with context

### ISSUE THREAD

**Issue by FFock** [rancher/rancher#9025]
**Rancher versions:**
rancher/server: 1.6.1
rancher/agent:

**Docker version: (`docker version`,`docker info` preferred)**
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   78d1802
 Built:        Tue Jan 31 23:35:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   78d1802
 Built:        Tue Jan 31 23:35:14 2017
 OS/Arch:      linux/amd64

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
OTC

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
external DB

**Steps to Reproduce:**
Use nginx as reverse proxy and then

upstream rancher {
        server 127.0.0.1:8082;
}
server {
        location /rancher/ {
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Forwarded-Port $server_port;
				proxy_set_header X-Forwarded-Context /rancher;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_pass http://rancher/;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "Upgrade";
        }
}

**Results:**
Assets are loaded from default context instead from https://.../rancher/assets/...

**Comment by vincent99** [comment]
Rancher expects to be run at `/` and we have no plans to change that.  Sharing cookies and origins opens up a variety of potential for conflicts or abuse.

**Comment by vijaysg** [comment]
I think there should be an option to having non-root context. Especially when I am trying it out and would be installing it with other apps which may use the root context. The lack of this option simply would not allow me to finish development setup.
