### ISSUE TITLE
Unable to resolve DNS inside containers created by rancher

### ISSUE THREAD

**Issue by ArunParthiban10** [rancher/rancher#9027]
**Rancher versions:**
rancher/server: v1.6.0
rancher/agent: v1.2.2

**Infrastructure Stack versions:**
healthcheck: v0.3.1
ipsec: v0.11.2
network-services:
rancher/metadata:v0.9.1
rancher/network-manager:v0.7.0
scheduler: v0.7.5
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
docker version : 
Client:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-common-1.12.6-11.el7.centos.x86_64
 Go version:      go1.7.4
 Git commit:      96d83a5/1.12.6
 Built:           Tue Mar  7 09:23:34 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-common-1.12.6-11.el7.centos.x86_64
 Go version:      go1.7.4
 Git commit:      96d83a5/1.12.6
 Built:           Tue Mar  7 09:23:34 2017
 OS/Arch:         linux/amd64

docker info :
Containers: 13
 Running: 11
 Paused: 0
 Stopped: 2
Images: 19
Server Version: 1.12.6
Storage Driver: overlay
 Backing Filesystem: xfs
Logging Driver: journald
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: overlay null bridge host
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Security Options: seccomp selinux
Kernel Version: 3.10.0-514.16.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 2
CPUs: 8
Total Memory: 15.66 GiB
Name: [redacted] 
ID: 24KD:RNKG:W2QT:QUFH:D3KK:BCRX:MAO3:JYQO:VC5Z:PPDQ:SXFT:2A73
Docker Root Dir: /data/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: http://10.101.6.4:9090/
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
Registries: docker.io (secure)

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

cat /etc/os-release:

NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

uname -r
3.10.0-514.16.1.el7.x86_64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VMware 

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher with internal DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)** Cattle 

**Steps to Reproduce:**
Created a rancher cluster with one master and 3 slave nodes and deployed a container.

**Results:**
Services deployed through rancher can't resolve DNS when in "managed" mode but work when in "host" mode.

**Comment by superseb** [comment]
Can show the output of the following inside the container? Also, what container are you running?

`cat /etc/resolv.conf`
`dig/nslookup <dns name you are trying to reach`

**Comment by ArunParthiban10** [comment]
cat /etc/resolv.conf
search  arun.rancher.internal arun.arun.rancher.internal rancher.internal mycompany
.com
nameserver 169.254.169.250

nslookup api.mycompany.com
Server:         169.254.169.250
Address:        169.254.169.250#53

api.mycompany.com  canonical name =xyz.mycompany.com.
Name:  xyz.mycompany.com
Address: 161._ _ _._ _._ _

**Comment by superseb** [comment]
Ah CNAME resolving was bugged in 1.6.0, see https://github.com/rancher/rancher/issues/8669. Could you update and try again?

**Comment by ArunParthiban10** [comment]
Upgrading to v1.6.2 fixed it!! Thanks !!
