### ISSUE TITLE
io.rancher.container.pull_image: always disappears when upgrading container

### ISSUE THREAD

**Issue by hanselke** [rancher/rancher#9030]
thru the UI, when i click on an individual container to upgrade it, it understandably moves the scheduling rancher labels over to the schedule segment.

However, io.rancher.container.pull_image: always is supposed to be still in labels but that disappears as well. have to manually add it in each time now

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.5.6` Cattle: `v0.178.4` UI: `v1.5.9` |
|Access|`github` `admin`|
|Orchestration|`Cattle`|
|Route|`service.new`|

**Comment by vincent99** [comment]
Pull image and various other things have their own UI controls and are therefore not shown in user labels.
