### ISSUE TITLE
Can't ping between containers across host

### ISSUE THREAD

**Issue by taikhuu** [rancher/rancher#9031]
**Rancher versions:**
rancher/server: v1.6.2
rancher/agent: v1.2.2

**Infrastructure Stack versions:**
healthcheck: 0.3.1 
ipsec: 0.3.1 
network-services: network-manager:v0.7.1
scheduler: v0.8.0 
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:05:44 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:05:44 2017
 OS/Arch:      linux/amd64
 Experimental: false
```
docker info:
```
Containers: 10
 Running: 10
 Paused: 0
 Stopped: 0
Images: 11
Server Version: 17.03.1-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: kx1iqkf3kk5wq8bhm8c28xt05
 Is Manager: true
 ClusterID: 4kcx9m6fbor0syuoqqpo2dg3e
 Managers: 2
 Nodes: 2
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: xxx
 Manager Addresses:
  xxx:2377
  xxx:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.10.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.26 GiB
Name: xxx
ID: ZEC7:PHVB:W2OO:OQEQ:WTJ6:B5NM:UJNP:7VFU:SYUV:T7FC:UAX3:XOTC
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
3.10.0-514.10.2.el7.x86_64
Centos 7

SELinux disable

No firewalld installed

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher server external DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Swarm

**Steps to Reproduce:**
Run Rancher Server
Add 2 Host using the command generated(Without host specified)
Ipsec running normally
network-manager running normally
health check : 1 running. 1 stuck at initializing
Scheduler: 1 running 1 stuck at intiializing
**Results:**
Expected:
Be able to ping in other hosts

Actual:
- Only be able to ping container in same host. Ping container in other hosts hang.
 - traceroute show request stop at ipsec from samehost

**Comment by taikhuu** [comment]
swantctl --list-sas show
```
 #1, CONNECTING, IKEv2
```

**Comment by taikhuu** [comment]
restart. delete everything and add host again it still not working

**Comment by superseb** [comment]
IPsec needs port 500/UDP and 4500/UDP open between agents to work, did you open those ports?

**Comment by taikhuu** [comment]
The public IP won't work. Private ones do. Sorry for this ticket.
