### ISSUE TITLE
Rancher cannot display information

### ISSUE THREAD

**Issue by waterlufei** [rancher/rancher#9033]
[*Describe](url) your issue here*
I've already opened udp500 and 4500

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.1` Cattle: `v0.181.3` UI: `v1.6.5` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`hosts.new.index`|

**Comment by waterlufei** [comment]
![qq 20170612153417](https://user-images.githubusercontent.com/24197674/27024203-3e2833e6-4f88-11e7-8879-b2310af47edc.png)

**Comment by papezt** [comment]
I have same issue, when i want show logs i see only "disconnected". 
Bare-metal - Docker 17.03.0-ce + Ubuntu 16.04.2 LTS

**Comment by loganhz** [comment]
If you're using chrome can you share any logs from the dev tools console?

**Comment by waterlufei** [comment]
Yes, I use the Google browser

**Comment by loganhz** [comment]
can you provide the console log, please?

**Comment by loganhz** [comment]
@waterlufei 
you can ssh to the agent and run `docker exec` to check if it works.

if there is a nginx in front of rancher server, please make sure you have correct nginx config to proxy websocket.
