### ISSUE TITLE
HA and websocket access via haproxy

### ISSUE THREAD

**Issue by VAdamec** [rancher/rancher#9036]
Hi,
 using HA Rancher (3x servers) with MariaDB cluster (one active, rest fallback, vi haproxy). I find out that only "master" server provides access to shell and logs (websocket issue?). I'm using Haproxy for SSL termination and balancing rancher servers. 

 Testing via direct accessing IP addresses and attempt to launch shell or see logs in UI. Only on actual master server websocket works, on the rest I got disconnect (logs) or long timeout (shell).

Did I miss something in haproxy config ? need some special websocket proxying to do proper roundrobin ?

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.2` Cattle: `v0.181.4` UI: `v1.6.5` |
|Access|`ldap` `admin`|
|Orchestration|`Cattle`|
|Route|`service.containers`|

**Comment by VAdamec** [comment]
Also is there any way how to recognize master server ?

**Comment by aemneina** [comment]
Hey @VAdamec you can crosscheck your haproxy config with the example config provided in the docs: http://docs.rancher.com/rancher/v1.6/en/installing-rancher/installing-server/basic-ssl-config/#example-haproxy-configuration

Let us know if that helps.

**Comment by VAdamec** [comment]
Hi, yes I used this configuration plus add simple health check, also for now removed ssl communication to backend servers to simplify debug. I can login, create services, ... but when I need websocket get nothing (timeout/disconnect - wss://.... 502 gateway timeout) when I'm not on master.

```
defaults
  mode http
  balance roundrobin
  option redispatch
  option forwardfor

  timeout connect 5s
  timeout queue 5s
  timeout client 36000s
  timeout server 36000s
  timeout tunnel 3600s

frontend http-in
  bind *:80
  redirect scheme https if !{ ssl_fc }
  bind *:443 ssl crt /etc/certs/justfordemo.pem force-tlsv12 no-sslv3
  default_backend rancher_servers

# Add headers for SSL offloading
  http-request set-header X-Forwarded-Proto https if { ssl_fc }
  http-request set-header X-Forwarded-Ssl on if { ssl_fc }

  acl is_websocket hdr(Upgrade) -i WebSocket
  acl is_websocket hdr_beg(Host) -i ws
  use_backend rancher_servers if is_websocket

backend rancher_servers
  option httpchk get /ping
  http-check expect string pong
  server rancher-001 10.0.0.10:8080 check weight 1 maxconn 1024
  server rancher-002 10.0.0.11:8080 check weight 1 maxconn 1024
  server rancher-003 10.0.0.12:8080 check weight 1 maxconn 1024
```

**Comment by VAdamec** [comment]
Test procedure is easy, just find out in logs who is master and assign the rest as a backup. Like this:

```
  server rancher-001 10.0.0.10:8080 check weight 1 maxconn 1024 backup
  server rancher-002 10.0.0.11:8080 check weight 1 maxconn 1024
  server rancher-003 10.0.0.12:8080 check weight 1 maxconn 1024 backup
```

also tried 

```
  balance source
  hash-type consistent
```

but seems that websocket communication is not affected.

**Comment by VAdamec** [comment]
So if it possible to get who is master via API, we can easily use healthcheck. Is there any API/URL with this information ?

**Comment by VAdamec** [comment]
It seems to work with clean installation (same config, network, db backend setup), so it needs to be something in database (some db migration issue? we went through 1.4 to actual 1.6 versions). Trying to get more information

**Comment by VAdamec** [comment]
No luck to find anything useful, closing.
