### ISSUE TITLE
[10acre-ranch] not able to install Kubernetes in multi-host setup

### ISSUE THREAD

**Issue by errordeveloper** [rancher/rancher#9037]
**Rancher versions:**
rancher/server:v1.6.2
rancher/agent:v1.2.2

**Infrastructure Stack versions:**
healthcheck:v0.3.1
ipsec:holder
network-services:v0.9.1
scheduler:v0.8.0
kubernetes (if applicable):v1.5.4-rancher1-4

**Docker version: (`docker version`,`docker info` preferred)** 

```
sudo docker info
Containers: 35
 Running: 34
 Paused: 0
 Stopped: 1
Images: 26
Server Version: 1.12.6
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 188
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay bridge host null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.8.0-52-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 29.45 GiB
Name: rancher-test-1-10acre-1
ID: MFRR:DKAC:YAJL:PDLT:TUTP:EFSW:XU4E:ZYJS:BLBS:CIQE:HETJ:6QB6
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
4.8.0-52-generic
```
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

GCE

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
```
./bin/gce-10acre-ranch -u https://releases.rancher.com/install-docker/1.12.sh -n 3 -m n1-standard-4 -M n1-standard-8 -z europe-west1-b -c rancher-test-1
```
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes
**Steps to Reproduce:**
1. Run `gce-10acre-ranch` command shown above
2. Install Kubernetes from the catalogue with default parameters.
3. Kubernetes fails to start, with most of containers showing "cannot join network of a non running container" error
4. De-activate all but one host
5. Remove Kubernetes and re-install it
6. Re-activate all hosts
7. Run `kubectl get node` – only one node is registered
8.  only one etcd is healthy in Rancher UI, two of other etcd nodes are in " Initializing" state
9. Removing all but one host gets results in `etcd-2` and `etcd-3` crash looping with " Allocation failed: host must not have a container with label io.rancher.stack_service.name=kubernetes/etcd and resource constraints: [1 instanceReservation])"
10. Re-installing Kubernetes seems to work okay

Additional observations:
-  all 3 of the healthcheck container (`healthcheck-healthcheck-{1,2,3}`) don't leave "Initializing" state
- `scheduler-scheduler-1` doesn't leave "Initializing" state

**Results:**

Kubernetes seems to install only in single-host cluster. I've spent half-a-day trying different versions of Docker and chasing logs of containers that died quicker then I could get the logs.

**Comment by deniseschannon** [comment]
I have run the same command many times with no issues. Are you sure you have UDP ports 500 and 4500 open on your GCE instances?

**Comment by errordeveloper** [comment]
@deniseschannon yes, I'm sure those ports are open.

![](https://www.dropbox.com/s/v9o8uigbobmvtay/Screenshot%202017-06-13%2009.58.04.png?dl=1)

**Comment by leodotcloud** [comment]
@errordeveloper Can you please collect the logs using: https://github.com/leodotcloud/rancher-logs-collector 
Seems like you might be having trouble with networking?

**Comment by errordeveloper** [comment]
With @cloudnautique's help, we've identified that opening all ports to the public resolves the issue.
I think this needs documenting, but also it'd be best to identify how to solve the issue without exposing all of the ports to the internet.
