### ISSUE TITLE
[cli] Add `docker cp` alternative

### ISSUE THREAD

**Issue by iBobik** [rancher/rancher#9039]
Docker cli has feature to copy files and folders between container and local. I did not found similar feature in Rancher cli.

I expected it in the first level (`rancher cp`) or under stacks (`rancher stack cp`).

**Comment by nvgoldin** [comment]
Is this somehow possible with `rancher docker` subcommand?

**Comment by srics** [comment]
@nvgoldin - i guess if you can figure out the hostId and containerId (or name) you construct something like this,

`rancher --host <hostId> docker cp <containerID>:/path/file .`

hostId can be retrieved by metadata-service (`curl 'http://rancher-metadata/2015-12-19/self/host/hostId`). However I couldn't find a reliable way to find the containerId or name from a stack name. Any ideas?

Again, all this is cumbersome, hence `rancher cp` will be an helpful addition to rancher cli.

**Comment by esazhin** [comment]
While the workaround with rancher docker comamnd and host is working it is requiring host level access and ability to figure out the name of the actual container on the host and so on. So this operation requires higher level privilege. I think that "rancher cp" command should allow to copy files in and out of a container without requiring "member" level access.

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.

**Comment by kingbuzzman** [comment]
Had this issue, my ops team doesn't give me access to the underlining machines themselves, so i had to get creative. You can just change `directory_name` to the local directory you're trying to copy on the rancher instance, and the `NAME_OF_RANCHER_INSTANCE` to the name of the instance. Whichever directory you are in when you execute this, it will copy it there.

NOTE: this does not copy over file permissions -- i didn't need it, if you do, you might want to add it.

```
(
  directory_name=/app/media;
  for file in $(rancher exec NAME_OF_RANCHER_INSTANCE find $directory_name -type f); do 
    local_file=$(echo $file | sed "s|$directory_name|./$(basename $directory_name)|"); 
    local_dir=$(dirname $local_file);  
    mkdir -p $local_dir; 
    rancher exec certman-django “cat $file” > $local_file;
  done
)
```
