### ISSUE TITLE
In main Project list page, service is first, but in details my balancer is first

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#904]
v0.21.3
Steps:
1.  Create a project
2.  Add a Service named Service1
3.  Add a Balancer named lb1

Results:  
Notice in the Main list view page, the Service is first and the Balancer is second.  But if you go into the details page for that project, the Balancer is first and the Service is second.

Expected:
The order should be same no matter what page I'm in

**Comment by vincent99** [comment]
They were just generally unsorted on the list page.

**Comment by tfiduccia** [comment]
v0.22.0-rc1
failed - the balancer is still sorting after Service on main page and first on details page.

**Comment by deniseschannon** [comment]
I'm unable to reproduce on v0.49.0-rc1, but will have @tfiduccia check as well.

**Comment by tfiduccia** [comment]
Both pages have changed quite a bit so this bug is no longer valid.
