### ISSUE TITLE
Metadata Service keeps showing 'updating-healthy' state even after 40 minutes of restarting the service

### ISSUE THREAD

**Issue by Edenshaw** [rancher/rancher#9040]
**Rancher versions:**
rancher/server: 1.5.10
rancher/agent: 1.2.2

**Docker version: (`docker version`,`docker info` preferred)**
Containers: 20
 Running: 18
 Paused: 0
 Stopped: 2
Images: 40
Server Version: 17.03.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 346
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-1017-aws
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.67 GiB
Name: ---
ID: ---
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Live Restore Enabled: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04.2 LTS
Kernel: 4.4.0-1017-aws

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node Rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Use these configurations to deploy a Stack:

**docker-compose.yml:**
  
  load-balancer:
    image: rancher/lb-service-haproxy:v0.6.4
    ports:
    - 280:280/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'

**rancher-compose.yml:**

  load-balancer:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      reinitializing_timeout: 60000

Using another container, enter the shell and query the metadata service, in order to find the health_check status of the load-balancer that you just deployed. Something like this (e.g.):

http://rancher-metadata/latest/containers/51/health_state

The response of the request should be:

healthy

Now, if you restart the load-balancer container and query the metadata, the response will be:

updating_healthy

After 40 minutes does not have change its state, it keeps showing: updating_healthy.

If you select the load-balancer container and select the option "View in API", it reflects the correct health state of the container, even after restarting the service.

This issue is related to this closed ticket https://github.com/rancher/rancher/issues/3130 but it does not present any relevant information on how to solve this issue.

Regards,

**Comment by jeffreyalexander88** [comment]
We are also seeing this v1.6.7

container updates, api response says container is healthy, metadata service (both latest and 2015-12-19) report container as "updating_healthy"

redeploying the service will clear this up. We notice this when doing an upgrade of a service

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
