### ISSUE TITLE
RBAC: Can't access Kubernetes API after enabling and then disabling Authentication

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#9041]
**Rancher versions:**
rancher/server: v1.6.2

kubernetes (if applicable): 1.6

**Steps to Reproduce:**

- Enable Github authentication
- Deploy kubernetes with RBAC enabled
- Login with admin user
- Query the API (eg. kubectl get nodes)
- Disable authentication
- Try to query the API again.

**Results:**

k8s respond with this error:
```
error: You must be logged in to the server (the server has asked for the client to provide credentials)
```

**Comment by deniseschannon** [comment]
@galal-hussein Can you re-test with the recent changes to websocket-proxy?

**Comment by deniseschannon** [comment]
re-tested and still same error.

**Comment by galal-hussein** [comment]
Rancher server: v1.6.3-rc2
k8s image: rancher/k8s:v1.6.6-rancher1-4

Tried the same steps and can't see the problem anymore.
