### ISSUE TITLE
Add support for creating environment scoped volumes in compose

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#9042]
As a user, I should be able to create environment-scoped volumes in compose that do not get deleted when the stack is deleted and that properly cause containers to be scheduled to the host where the volume resides.

Right now the workaround solution for this is to use host affinity rules and to not declare the volumes at the top level in compose. This is a definite gap in our volume implementation and we want to fix.

To address it, we want to introduce a scope field on volumes whose value can be environment, stack, service, or container. Let's ignore service and container scope for now as they apply to different use cases and may implemented in a later phase. When set to stack the volume would  behave the same way as the current default behavior. The new scope environment would directly address your use case. When a volume's scope is set to environment:
1. The volume will get created if it does not already exist.
1. The volume will not be deleted when the stack is deleted.
1. Containers using the volume will automatically get scheduled to the host(s) where the volume exists.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
