### ISSUE TITLE
Add support for underscores and periods in service names

### ISSUE THREAD

**Issue by brettneese** [rancher/rancher#9043]
**Rancher versions:**
rancher/server: v1.5.5
rancher/agent: v1.2.0

**Docker version:** 17.03.1-ce

**Environment Template:** cattle

**Steps to Reproduce:**
1. Create a service with `_` and/or `.` characters using the Web UI (have not tried `rancher-compose` recently but if my hazy memory serves me correctly I had the same problem there)

**Results:**
`"Name" contains 2 invalid characters: _ .`

**Expected results:**
Service names should allow the `_` and `.` characters, as these are perfectly valid characters for services in Docker/Docker Compose, per https://github.com/docker/compose/pull/1624

We like to version all of our service names (`fooservice_1.2.3-4`), and while we are currently doing a regex to replace the periods and underscores with dashes, this is a rather ugly solution (especially given that Docker/Docker Compose themselves support the underscore and period characters.)

**Comment by vincent99** [comment]
This is not going to be changing.  Service names are used in DNS and need to be a valid [single] label.  `_` is not allowed in a DNS label, despite working in many but not all places..

https://github.com/rancher/rancher/issues/1176
https://github.com/rancher/rancher/issues/3589
https://github.com/rancher/rancher/issues/5017
https://github.com/rancher/rancher/issues/5195

**Comment by brettneese** [comment]
@vincent99 why not just substitute `-` & `.` when creating domain names? how does docker itself handle this problem? pretty big deal for us...

**Comment by vincent99** [comment]
Remapping create a new class of problem where you can end up with unique names that map to non-unique hostnames.  I don't know what Swarm does off-hand, but Docker Cloud rejects underscore too.  TBH what you're doing is quite unusual.
