### ISSUE TITLE
Load Balancer details not showing Target, Port or backend info for container target

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#9046]
**Rancher versions:** 6/12 master

**Steps to Reproduce:**
1.  Add a container
2.  Add a load balancer and select the container as the target (add port)
3.  Go to details page and click on Target Rules

**Results:** Target, Port and Backend not showing up
![image](https://user-images.githubusercontent.com/11514927/27060704-64bb2d0a-4f93-11e7-9d29-cbd4ffa657e5.png)

Getting error: ember.prod.js:16699 Error: You must provide param `scaling_group_id` to `generate`.

Also no target after that will display

**Comment by westlywright** [comment]
@tfiduccia when i merge my next pr you'll see a change, LB's now showcase there target rules using the same component as add target rules. This table didn't make as much so we opted to reuse the component much as we do with the other input/edit components shared between containers, service, etc. I'll move this to you when its merged.

**Comment by tfiduccia** [comment]
The container target is still not showing up in the details.
![image](https://user-images.githubusercontent.com/11514927/28598975-01b11b44-715c-11e7-880b-a1ee9fb0e580.png)

**Comment by tfiduccia** [comment]
Version - master 2.0 7-31
Verified fixed
