### ISSUE TITLE
Enable Go sql native passwords by default

### ISSUE THREAD

**Issue by chrisurwin** [rancher/rancher#9049]
There is an issue with the way that the Go MYSQL DSN parser works with usernames and passwords with an @ symbol in them

This can be bypassed by passing ```-e CATTLE_DB_CATTLE_GO_PARAMS=allowNativePasswords=true```

Update the build properties of Rancher server to set this to true as default

**Comment by galal-hussein** [comment]
Rancher server: v1.6.3-rc2

Steps to validate:

- On azure create a mysql db preview instance with admin login name `cattletesting` and password `cattle@testing1`
- Connect to the Mysql instance and create the cattle database
- Create an ubuntu instance on Azure and install docker and run rancher server with external db paremeters
```
docker run -d --restart=unless-stopped -p 8080:8080 rancher/server:v1.6.3-rc2 --db-host x.x.x.x  --db-port 3306 --db-user cattletesting@hgalal --db-pass cattle@testing1 --db-name cattle
``` 
- Make sure that rancher server is up and running

After running the previous steps i was able to see rancher server starting correctly and connecting to the database successfully.
