### ISSUE TITLE
Container‘s state is not correct as docker cli

### ISSUE THREAD

**Issue by 694982827** [rancher/rancher#9050]
image:nvidia/cuda
rancher:1.6
docker:17.03.1-ce
OS:Ubuntu 16.04.2 LTS
      when I creating the container nvidia/cuda on rancher UI,the container's state is always starting,but when I
shell "docker ps" the container is up and I  go into it "docker exec -it bb99c1365333  /bin/bash" ,the container is normal and did't have anything wrong. why ?
…………………………………………………………………………………………………………………………………………………………………………
then I tested I found I could use 'docker run -v nvidia_driver_370.28:/usr/local/nvidia:ro -it imgname' to mount the nvidia_driver_370.28 volume to container's /usr/local/nvidia but the rancher UI could't correctly get it's state and  rancher ui set the state 'starting'. when I creating the nvidia/cuda without any volume the rancher ui is just ok.

**Comment by cszhe** [comment]
Hi, we have exactly the same problem. Do you find any workaround?

**Comment by 694982827** [comment]
@cszhe
 using docker run --volume-driver=nvidia-docker 
--volume=nvidia_driver_【version】:/usr/local/nvidia:ro 
--device=/dev/nvidiactl 
--device=/dev/nvidia-uvm 
--device=/dev/nvidia0
instead of using nvidia-docker.

**Comment by 694982827** [comment]
@cszhe 
As follows:
![image](https://user-images.githubusercontent.com/14134883/27417100-68ee6794-5744-11e7-8d8e-0a07eb8e1e39.png)

**Comment by raviv** [comment]
Nvidia Docker 2.0 now uses the `--runtime` flag.
However, I don't think Rancher supports this flag.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
