### ISSUE TITLE
Dont send traffic to backend before it starts passing health check(s)

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#9051]
Have the ability to only add containers, for a service, to the existing LB only after the container starts passing health checks.

**Steps to Reproduce:**
1. scale a service, which has a health check enabled, where the service isnt immediately able to service requests
2. lb gets programmed with backend
3. some requests fail as service isn't ready to field requests yet

**Comment by aemneina** [comment]
Current workaround is to use backend checks with custom haproxy config. Not sure if this actually works, will need confirmation.

**Comment by deniseschannon** [comment]
@sangeethah Could you have someone test to see if this works today? @prachidamle has indicated this has been working, so need confirmation for @aemneina

**Comment by cjellick** [comment]
You can even see in the haproxy config inside the LB container that the backend is added with the same healthcheck that is configured for rancher.

**Comment by jkopelioff** [comment]
@alena1108 @kinarashah Is there any info you need from us to help diagnose?

**Comment by alena1108** [comment]
@jkopelioff we were planning to do the initial testing using some standard web image, but it would be nice if you could share the details of your application:

* how much time does it usually take for the service to be fully ready? 
* the health check settings

**Comment by kinarashah** [comment]
The load balancer gets programmed even if servers are in initializing state, but haproxy has its own configurations for health check and requests are never forwarded to the servers unless they are in the healthy state. 
Confirmed by CURLing the load balancer, checking the haproxy config and seeing where it forwards the request to. 

Steps to illustrate  - 
1. Create a stack with one load balancer and two or more services with health check enabled. 
2. Force one of them to stay in the initializing state. (for instance - by setting HTTP Request page to a non existent file.) 
3. docker exec into the load balancer and see haproxy.cfg file - IP addresses of all 
the servers are present irrespective of their health states, along with the healthcheck configured:

Example of haproxy config where the health check is enabled in the backend section: 

```
backend 70_
acl forwarded_proto hdr_cnt(X-Forwarded-Proto) eq 0
acl forwarded_port hdr_cnt(X-Forwarded-Port) eq 0
    http-request add-header X-Forwarded-Port %[dst_port] if forwarded_port
    http-request add-header X-Forwarded-Proto https if { ssl_fc } forwarded_proto
    timeout check 2000
    option httpchk GET "/name.html" "HTTP/1.0"
mode http
server 3e2ceea7ad9cba7ec6fc3782604b3849d4f44ec8 10.42.186.25:80  check port 80 inter 2000 rise 2 fall 3 // healthcheck configured, server is healthy
server 1fa7696394b5f8259f4a6b32b2ed4cabcce2a136 10.42.10.140:80  check port 80 inter 2000 rise 2 fall 3 // healthcheck configured, server is initializing
```

4. CURL the load balancer IP to confirm the server in initializing state is never called. With haproxy configured, only healthy server 10.42.186.25:80 is called repeatedly. 
5. Bring the server in initializing state to healthy by making the file pointed by HTTP Request page available. Observe all servers now get called in a round-robin schedule.
