### ISSUE TITLE
If import fails, can't see stack to delete it or fix it

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#9054]
**Rancher versions:** 6/13  (2.0 alpha)

**Steps to Reproduce:**
1.  Import a compose file that will fail to create a container
2. Get out of stack details
3.  Try to go back to stack details

**Results:** I can't go back because, I can't see the stack anywhere.  Containers were not created, so the stack is floating out there failing and I can't do anything about it.

**Comment by deniseschannon** [comment]
There is also an issue where if you try and re-create the stack with the same name, it'll fail as the stack name exists somewhere in the API but is not visible in the UI.

**Comment by tfiduccia** [comment]
Version - 2.0 master 8/5
Verified fixed
