### ISSUE TITLE
Optimize catalog fetch in catalog-service

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#9057]
Currently, we always pull a version of the Rancher catalog, even if it hasn't changed. We should optimize so it only fetches when there has been a change based on commit reference.

https://developer.github.com/changes/2016-02-24-commit-reference-sha-api/
https://developer.github.com/v3/repos/commits/#get-the-sha-1-of-a-commit-reference

for catalog-service, we'll need to do something like 

```
if ( github.com/{org}/{repo} ) {
  Send request to https://api.github.com/repos/{org}/{repo}/commits/{branch}
  Also follow redirects, because those send a redirect now that they don't mention in docs...
  if ( response is 304 ) { 
    do nothing
  }
} else if ( git.rancher.io )  {
  Send similar request to ${some url we creates}
  if ( response is 304 ) {
    do nothing
  }
}

do regular update
```

**Comment by sangeethah** [comment]
Tested with rancher-server version v1.6.3-rc5
Changes done on catalog side ( like add/edits/deletes of existing templates) get reflected in the rancher-server side within the next 5 mts ( default catalog.refresh.interval.seconds).

**Comment by sangeethah** [comment]
Optimization for catalog fetch works for catalogs hosted in github.com and git.rancher.io .
Optimization for catalog fetch will not work with  catalogs hosted in private mirrors.

**Comment by sangeethah** [comment]
We should include optimizations for users with personal mirrors which is tracked in  -
 https://github.com/rancher/rancher/issues/9273
