### ISSUE TITLE
Make sure Secrets export work

### ISSUE THREAD

**Issue by StrongMonkey** [rancher/rancher#9059]
Cattle exports for secrets should follow https://docs.docker.com/compose/compose-file/#secrets exactly.

**Comment by StrongMonkey** [comment]
Available at V1.6 now. Noticed that [this](https://github.com/rancher/cattle/pull/2771#issuecomment-309598115) won't work currently

**Comment by soumyalj** [comment]
Tested with rancher v1.6.6-rc4. Export for stack with secrets is functional, except for the issue https://github.com/rancher/rancher/issues/9501
