### ISSUE TITLE
[Proposal] Add --pod-eviction-timeout parameter to Kubernetes catalog for controller-manager

### ISSUE THREAD

**Issue by hiscal2015** [rancher/rancher#9060]
Hi, 

Kubernetes controller-manager has a parameter "--pod-eviction-timeout" to define the timeout when node is inaccessible, see the section "Maintenance on a Node" from below url:
https://kubernetes.io/docs/tasks/administer-cluster/cluster-management/

The default value is 5 minutes, it is too long for most of production use cases, if the host was down, pods on it will take longer than 5 minutes to migrate if kubernetes and controller-manager components were also on the broken host (almost 8~9 minutes by my testing). 

So my proposal is, can we add a parameter to Kubernetes catalog, to let user define his own pod-eviction-timeout? Thanks.

**Comment by joshwget** [comment]
I'm not sure if we'll explicitly add a flag for this or wait until we support adding of arbitrary flags. I definitely agree it would be useful to customize this.

**Comment by hiscal2015** [comment]
Created custom catalog.
