### ISSUE TITLE
Deadlocks! Deadlocks everywhere

### ISSUE THREAD

**Issue by ket4yii** [rancher/rancher#9061]
**Rancher versions:**
rancher/server: 1.6.2
rancher/agent: 1.2.2

**Infrastructure Stack versions:**
network-services: net-manager 0.6.6

**Docker version: (`docker version`,`docker info` preferred)**

17.04.0-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
RancherOS v1.0.1 kernel 4.9.24

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

Parallels VM

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

Rancher HA. External DB: galera cluster

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

cattle
**Steps to Reproduce:**

Just when service state is changed it can show deadlock, sometimes

**Results:**

One of messages:
```
Could not commit JDBC transaction; nested exception is java.sql.SQLTransactionRollbackException: (conn:47160) Deadlock found when trying to get lock; try restarting transaction Query is : COMMIT) 
```

Also, I have deadlock with **service_log**, but it's well known issue, I think.

**Comment by ket4yii** [comment]
Service_log deadlock:
```
 (SQL [insert into `service_log` (`account_id`, `kind`, `description`, `created`, `data`, `end_time`, `event_type`, `service_id`, `instance_id`, `transaction_id`, `sub_log`, `level`) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]; (conn:47659) Got error 35 "Resource deadlock avoided" during COMMIT Query is: insert into `service_log` (`account_id`, `kind`, `description`, `created`, `data`, `end_time`, `event_type`, `service_id`, `instance_id`, `transaction_id`, `sub_log`, `level`) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), parameters [28,'serviceLog','Could not commit JDBC transaction; nested exception is java.sql.SQLTransactionRollbackException: (conn:47671) Deadlock found when trying to get lock; try restarting transaction Query is : COMMIT','2017-06-14 07:57:18.88','{}','2017-06-14 07:57:18.88','service.upgrade.wait.exception',1150,<null>,'6e7d75d7-58b3-4992-afd0-749ad4836581',1,'error']) 
```

N.B. All of this log are from UI

**Comment by Nosmoht** [comment]
Seems like your load balancer proxies requests to all available galera nodes. I had the same issue. Rancher docu tells us that load balancer should only route traffic to one node. Did you try that?

**Comment by ket4yii** [comment]
@Nosmoht I know about transaction locks in galera, but I think it souldn't be so painless to be unable to do anything with your services(it shows internal server error) and see this red messages in UI. This is server-side issue and a lot of apps deals with deadlock errors by retrying a transaction. I think, maybe it'll be better to play with retry_autocommit. Anyway, thank you for advice. Do you know some good solutions that can do this? I mean, single-node write, multiple-nodes read strategy.

**Comment by ket4yii** [comment]
Now it's not relevant for me. I'm closing it.
