### ISSUE TITLE
agent optional configuration

### ISSUE THREAD

**Issue by lanmingle** [rancher/rancher#9062]
请求运行 agent 可以自定义挂载点,以及不要强制创建 /var/lib/kubelet 这些目录,要求取消强制设置.

Request the running agent to customize the mount point, and not to force the creation /var/lib/kubelet directories, to call off the mandatory Settings !

**Comment by aemneina** [comment]
@lanmingle this is configurable in newer templates of kubernetes. If you upgrade your k8s stack, do you see the option to change this location?
