### ISSUE TITLE
Adding rancher/agent via docker-compose

### ISSUE THREAD

**Issue by olegkolner** [rancher/rancher#9063]
Hi, 
I need to add the host (rancher agent) to rancher server via docker-compose.yml. To do that in plain Rancher UI I need to run docker command with specified URL with some token ("docker run --rm --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent http://<server ip>:<port>/v1/scripts/<registration token>"). So how can I specify this docker-command in docker-compose.yml  file (version 2)?

**Comment by vincent99** [comment]
You just convert the command to the equivalent yaml... similar to http://docs.rancher.com/os/running-rancher-on-rancheros/#launching-agents-using-cloud-config

**Comment by olegkolner** [comment]
thx!

**Comment by aemneina** [comment]
@olegkolner you should be able to query your server at the following path to derive the registration token: `/v2-beta/projects/<environment_id>/registrationtoken`

**Comment by uvwild** [comment]
since this link above is dead and the issue remains I wil start a new issue to point this out.
starting the agent together with a server using docker-compose is an important use case in our environment.

that's the problem when answer are posted as simple links (which  die eventually)
