### ISSUE TITLE
Enhance the restrictions on the restricted user type

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#9064]
The restricted role is currently only restricted from creating, updating, or deleting hosts. We're going to expand on that in the following ways:
- A restricted user cannot create, update, or delete infrastructure stacks, services, or containers
- A restricted user cannot exec into containers with the io.container.create_agent label
- A restricted user cannot exec into any containers belonging to infrastructure services
- A restricted user cannot set the `privileged` field to true on a service or container
- A restricted user cannot set the `capAdd` field on a service or container
- A restricted user can only perform host bind mounts to a whitelisted set of host directories (controlled by a setting in Rancher)

To implement the restrictions to CUDing infra services and execing into containers, we want to key off of the user's permissions to hosts as opposed to hardcoding it to specific roles. In other words, instead of checking if the user has the role "restricted", we want to check if the user is unable to create, update, or delete hosts. If that is true, then we'll remove the ability to CUD infra services or exec into their containers. We want to implement it this way so that our users can tweak other roles to not be able to create hosts and get the restricted infra-service behavior automatically.

**Comment by cjellick** [comment]
I have some WIP code for this that I wanted to start to prove it out. So, ping me before you start so that I can share.

**Comment by cjellick** [comment]
Added: A restricted user cannot access the dockersocket action on a host

**Comment by sangeethah** [comment]
@cjellick , Have the following questions regarding restricted user's abilities

1. io.rancher.container.create_agent  - LB instances have this flag. 
Are there any other containers that have this label set ?
Should restricted users  be allowed to create/delete/stop LB services

2. In addtion to capAdd , Should we also be restricting restricted users from using capDrop?

3. Network agent container - Do we need to restrict exec into  Network agent container?

**Comment by sangeethah** [comment]
Test plan tracked in https://github.com/rancher/rancher/issues/9125

**Comment by cjellick** [comment]
@sangeethah

1. Restricted users *can* start/stop/create LB containers, just shouldnt be able to exec into them. Yes, many other containers have that label, but most of them are infrastructure services, so they'd be excluded for that reason as well. I don't have a comprehensive list of the containers with that label because we use it a lot in our infra services.

2. capDrop can only lower their privileges, so there's no real need to restrict that.

3. Yes, Network agent container should be an infrastructure container and thus should be restricted

**Comment by sangeethah** [comment]
Following feature is not yet implemented and is tracked in a separate issue -  https://github.com/rancher/rancher/issues/9161

- A restricted user can only perform host bind mounts to a whitelisted set of host directories (controlled by a setting in Rancher)

**Comment by sangeethah** [comment]
Test execution results from the identified set of test cases - 
[TestPlanRestrictedUser.xlsx](https://github.com/rancher/rancher/files/1103259/TestPlanRestrictedUser.xlsx)

**Comment by sangeethah** [comment]
Issues found when testing this enhancement:
https://github.com/rancher/rancher/issues/9160
https://github.com/rancher/rancher/issues/9162

**Comment by sangeethah** [comment]
Enhancements to restricted user is available with rancher-server version - v1.6.3-rc2.
Issues found when validating this feature are tracked as separate issues.
Closing this issue.

**Comment by sangeethah** [comment]
Following 2 restrictions will not be imposed on restricted users:

A restricted user cannot set the privileged field to true on a service or container
A restricted user cannot set the capAdd field on a service or container

**Comment by sangeethah** [comment]
Tested with rancher/server:v1.6.3-rc5 

As restricted user , Able to create/upgrade/delete services with  privileged field and capAdd flag set. These fields get set for the service containers as expected.

As restricted user , Able to create/delete container with privileged field and caAadd flag set.
