### ISSUE TITLE
Persistence volume claim doesn't work with a custom template

### ISSUE THREAD

**Issue by saphoooo** [rancher/rancher#9067]
**Rancher versions:**
rancher/server:v1.6.2
rancher/agent:v1.2.2

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):v1.5.4

**Docker version: (`docker version`,`docker info` preferred)**

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
RancherOS v1.0.2, v0.9.2
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node with external database
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes
**Steps to Reproduce:**
Made a copy of Kubernetes template, just changing cloud provider to aws, then set up your environment.
**Results:**
No volume created on AWS, so volume claim doesn't work.

**Comment by joshwget** [comment]
The cloud provider can be set be making an environment template rather than making a custom template. Can you try out this method?

**Comment by saphoooo** [comment]
I already know that environment template works, but I wonder why a simple copy with just the cloud provider option changed doesn't. What is the goal of cloning an environment template if he hasn't the same properties? Means unpredictable results if I have one environment K8s on AWS and another one on premises (or on another cloud provider) with Rancher hosted on AWS. It's not fear.

**Comment by superseb** [comment]
If you use your template, does the `--cloud-provider` get set to `aws` on all the components (`kubelet`, `apiserver` and `controller-manager`)?

**Comment by superseb** [comment]
Let me know if we can assist on this.
