### ISSUE TITLE
[RFC] Need more information about what metrics are exposed through 9108 port

### ISSUE THREAD

**Issue by pengjiang80** [rancher/rancher#9070]
Per https://github.com/infinityworksltd/Guide_Rancher_Monitoring , we can expose metric port during Rancher server startup by using -p 9108:9108. Customer would like to know what metrics are exposed, a full list is required. 

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.2` Cattle: `v0.181.4` UI: `v1.6.5` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`stacks.index`|

**Comment by deniseschannon** [comment]
Rancher doesn't export anything on port 9108.

See: https://github.com/rancher/rancher/blob/master/server/Dockerfile

Based on the repo shared, it sounds like that port is being used by prometheus to do something.

**Comment by niusmallnan** [comment]
@pengjiang80 
https://github.com/rancher/rancher/blob/master/server/artifacts/metric-map.conf
Maybe this is useful to you
