### ISSUE TITLE
[RFC] Any impact of enable live-restore=true  of docker in hosts managed by Rancher

### ISSUE THREAD

**Issue by pengjiang80** [rancher/rancher#9072]
Does Rancher support docker engine with live-restore enabled? Any potential impact to Rancher/cattle side? 

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.2` Cattle: `v0.181.4` UI: `v1.6.5` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`stacks.index`|

**Comment by deniseschannon** [comment]
`live-restore=true` will not work with Rancher.

**Comment by rysiekpl** [comment]
@deniseschannon why won't it work? Can you provide more context please?
