### ISSUE TITLE
Unable to make new user an admin

### ISSUE THREAD

**Issue by bkuhl** [rancher/rancher#9075]
After granting a new user access to Rancher, I'm unable to make them an admin.  I suspect this might be because they haven't logged in yet.  I'd still expect to be able to make them an admin before they login for the first time.

Notice ddecker-realpage:
![screen shot 2017-06-15 at 9 33 15 am](https://user-images.githubusercontent.com/524933/27183777-d4b9d1a8-51ad-11e7-8d36-a7635945876e.png)

User doesn't show up here:
![screen shot 2017-06-15 at 9 34 46 am](https://user-images.githubusercontent.com/524933/27183794-e7765244-51ad-11e7-9a7e-2fe7ce1fb79f.png)

I've tried logging out and back in with no luck.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.2` Cattle: `v0.181.4` UI: `v1.6.5` |
|Access|`github` `admin`|
|Orchestration|`Cattle`|
|Route|`admin-tab.accounts.index`|

**Comment by livehybrid** [comment]
I'm also having this issue, trying to avoid a dirty hack to create the users manually...thoughts?

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
