### ISSUE TITLE
LB service fails after editing

### ISSUE THREAD

**Issue by bacheson** [rancher/rancher#9076]
**Rancher versions:**
rancher/server: 
1.6.2
rancher/agent:
1.2.2

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
cattle
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
1.12.6
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
ubuntu 16.04
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Google Cloud
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**
Create LB and add service rules...add new rule...save
**Results:**
lb now returns 503 for all services

**Comment by bacheson** [comment]
rebooting all servers and re-instantiating the lb containers fixed the issue...nervous to edit rules moving forward

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
