### ISSUE TITLE
document kubelet host ports required for exec/logs

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#9081]
had issues with exec and logs for kubernetes in a fairly locked down environments. Turns out need kubelet host ports 10250 and 10255 exposed as well.

**Comment by aemneina** [comment]
@deniseschannon I submitted this: https://github.com/rancher/rancher.github.io/pull/798 I'm sure you'll want to fix it up before it hits the doc's site.

**Comment by deniseschannon** [comment]
Documented and added into readme for k8s templates.
