### ISSUE TITLE
Rancher Upgrade gui does not parse multiple host affinity scheduling rules correctly

### ISSUE THREAD

**Issue by GiGurra** [rancher/rancher#9086]
**Rancher versions:**
rancher/server: v1.6.2

First - the runtime behavior is correct. This is a bug report on the Rancher GUI (when deploying services with Cattle) itself.

When setting host affinity scheduling rules using labels, e.g:
      io.rancher.scheduler.affinity:host_label: type=service-node,testlabel=abc123

Expected behavior:
![image](https://user-images.githubusercontent.com/1761299/27225955-d6afc41e-529c-11e7-815a-a1e037a41378.png)

Actual behavior:
![image](https://user-images.githubusercontent.com/1761299/27225929-bae9572c-529c-11e7-856b-5431c47e9c4d.png)

Steps to reproduce:
1. Upgrade a service and add 2 or more affinity scheduling rules as shown above.
2. Accept the upgrade
3. Open up the upgrade gui again and go to the Scheduling tab.

**Comment by vincent99** [comment]
There is really only one label, these are both equivalent and there is no way to know which of the two ways you entered it previously.
