### ISSUE TITLE
Can't ping old running container when upgrading

### ISSUE THREAD

**Issue by ketchoop** [rancher/rancher#9091]
*Describe your issue here*

When I upgrade containers and set batch interval with start-before stopped I can't ping the old one. So, blue-green deployment just doesn't work. Happens with managed network.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.2` Cattle: `v0.181.4` UI: `v1.6.5` |
|Access|`openldap` `admin`|
|Orchestration|`Cattle`|
|Route|`stacks.index`|

**Comment by leodotcloud** [comment]
I just tried this scenario and I was able to connect to the old container before the new one started. @ket4yii can you please share steps to reproduce?

**Comment by ket4yii** [comment]
* Upgrade container with *batch time* around 20s and *start before stopping*.
* Try to connect to the old container from another host
* Server unreachable

But it's really strange, that I can ping it from the same host where container is running.

**Comment by ket4yii** [comment]
@leodotcloud looks similar #9105. Just can't connect to it. As I see it'll be fixed in the next version. Anyway, thank you for response to the issue!

**Comment by ketchoop** [comment]
@leodotcloud now it's ok with 1.6.4. Closing the issue
