### ISSUE TITLE
Rancher-nfs volume driver doesn't pay attention to container's user and mounts volumes as root.

### ISSUE THREAD

**Issue by ketchoop** [rancher/rancher#9092]
*Describe your issue here*

As I know, named volumes in docker pay attention to rights and user in docker container.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.2` Cattle: `v0.181.4` UI: `v1.6.5` |
|Access|`openldap` `admin`|
|Orchestration|`Cattle`|
|Route|`storagepools.pools`|

**Comment by cjellick** [comment]
Thanks for the bug report @ketchoop! Can you provide explicit steps to reproduce and expected vs actual results?

**Comment by ketchoop** [comment]
@cjellick  Just, use container that have `USER` different from root and mount directory with this `USER` permission. E.g. I had Elasticsearch and mounted volume for it.

**Comment by iljaweis** [comment]
I believe that's how Docker volumes are supposed to work. The ownership/permissions of them volume's root aren't taken from the USER parameter, but instead from the directory in the Docker image where you are mounting.

So if you want /home/user to mount as a volume, have /home/user in your image with ownership user:user.

**Comment by ketchoop** [comment]
@iljaweis I

**Comment by iljaweis** [comment]
We're using that feature and it generally works with rancher-nfs. Here's a minimal example of what we're doing.

Dockerfile:
```
FROM ubuntu:14.04.3

RUN useradd hello && mkdir /hello && chown hello /hello
```

docker-compose.yml:
```
version: '2'
volumes:
  hello:
    driver: rancher-nfs
services:
  hello:
    image: hello
    stdin_open: true
    volumes:
    - hello:/hello
```

and that creates the mounted directory with the expected owner:
```ls -la /hello
total 8
drwxr-xr-x  2 hello root 4096 Aug  6 08:12 .
drwxr-xr-x 36 root  root 4096 Aug 14 09:22 ..
```

**Comment by stuckj** [comment]
Could this just be an NFS 4 permissions issue? I'm assuming you're using nfsv4 with rancher-nfs.

**Comment by jimvermillion** [comment]
Has there been any movement on this issue? 
I'm having a similar permissions problem mounting a named rancher-nfs volume for elasticseach. I've tried implementing the example that @iljaweis provided with no luck. Once the stack is built, I'm able to find the corresponding dir on the host machine and do a 
`chown 1000:1000 ${ELASTICSEARCH_VOLUME}` which remedies the issue, but no way to do it through CI.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
