### ISSUE TITLE
[cli] Adding a custom host via rancher CLI 

### ISSUE THREAD

**Issue by afgane** [rancher/rancher#9093]
I'd like to add a _custom_ host (i.e., already provisioned) to an environment via the `rancher` CLI but the following command does not work:
```
rancher --url http://localhost:8080 --env k8 host create --driver custom h1
FATA[0000] Invalid driver: custom
```
``--help`` on the `create` option lists the following driver options `packet, amazonec2, azure, digitalocean [$MACHINE_DRIVER]` but the UI shows _custom_ (and gives an option to add more). I don't see anything about the CLI options in the general docs (https://docs.rancher.com/rancher/v1.5/en/hosts/custom/). 

Is there a way to add a custom host via the CLI? What is the appropriate driver name?

**Rancher versions:**
rancher/server: 1.5.3
rancher/agent: 1.5.3
rancher/cli: 0.6.1

**Comment by vincent99** [comment]
Custom doesn't actually _do_ anything, it's just instructions for you to run the agent on the host.

**Comment by afgane** [comment]
Fair enough but is there a way to get that command via the CLI client?

The [docs](http://docs.rancher.com/rancher/v1.6/en/hosts/custom/) say:
> If you are using different environments, the command provided through the UI will be unique to whatever environment that you are in.

So how can the specific command be generated?

(for reference, for anyone else that might come across this, the command will look similar to this: `sudo docker run -e CATTLE_AGENT_IP="10.10.10.10"  -d --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.2.1 http://10.10.10.10:8080/v1/scripts/D46E3087637D38708210:1483143400000:Tt9QW2jK4xVMm0OEr1i6pss1Z1f`

**Comment by blsaws** [comment]
I have the same issue and sent a note on #rancher and the rancher forum on this "How to create a generic host via CLI" https://forums.rancher.com/t/how-to-create-a-generic-host-via-cli/7145 
No response yet but I am watching. 
In the meantime I looked into using the "generic" driver which (I think) will launch rancher/agent. I found that for the CLI to accept the generic driver I had to manually enable that machine-driver through the UI. I am currently working thru issues with passing the ssh key in the command (seems the rancher/server container can't get the key file as the host filesystem is not accessible in the rancher/server container...). But if I make progress on this including any way to script custom driver creation I will post that here. My overall goal is to create a CI/CD environment deploying and testing NFV applications using rancher as the cloud control plane (e.g. vs OpenStack) as part of our work in the OPNFV project (https://www.opnfv.org/).

**Comment by shank7485** [comment]
@blsaws Thanks. It would be really helpful if you share the custom driver script. 

I am using Rancher to automate ONAP (https://www.onap.org/) deployment on Kubernetes which I think will relate to OPNFV eventually. ;)

**Comment by senica** [comment]
`curl http://localhost:8080/v2-beta/registrationtokens`

I'm using it like this in a script to setup my development environment shell script
```
URL=$(curl \
  -H "Accept: application/json" \
  -H "Content-Type: application/json" \
  http://localhost:8080/v2-beta/registrationtokens \
  | python -c "import sys,json;print(json.load(sys.stdin)['data'][0]['command'])")
```

**Comment by jeff1evesque** [comment]
I'm trying to create a generalized rancher install script:

- https://github.com/jeff1evesque/machine-learning/blob/508f572357966d621026ff144731a29c6faed939/install_rancher

However, I'm having the following problems after running my custom rancher script:

- each of the services in the stack doesn't not have any containers
- no rancher host is created

Any willing to help me debug, and commit changes? Also, feel free to recycle this script for your own purpose.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
