### ISSUE TITLE
[Rancher Server] Interface crashes in "View Logs" of container when log is overloaded

### ISSUE THREAD

**Issue by FireDrunk** [rancher/rancher#9095]
**Rancher versions:**
rancher/server: 1.6.0
rancher/agent: 1.2.2

**Infrastructure Stack versions:**
healthcheck: 0.3.1
ipsec: 0.11.2
network-services: n/a
scheduler: 0.9.1/0.7.0
kubernetes (if applicable): not used

**Docker version: (`docker version`,`docker info` preferred)**
 Boot2Docker 17.05.0-ce (4.4.66)

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
 Boot2Docker 17.05.0-ce (4.4.66)

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VMWare Guests created by rancher via Machine Driver.
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
4 nodes HA, but rancher server lives outside the rancher hosts.
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
Deploy a container with failty configuration which keeps rebooting and/or spewing logs
**Results:**
Rancher webinterface crashes

A little more story: I was trying to get the Keepalived container running on rancher, when it started spewing logs regarding a kernel module (which was in no way ranchers fault). The complete Rancher interface crashed when clicking on the "View logs" button in one of the container detail pages.
I think this has something to do with the websocket that is receiving the log data.

Maybe some kind of throttling is needed to prevent the issue.

**Comment by RutledgePaulV** [comment]
I'm also seeing this. When I tail the logs of a busy kubernetes pod from my laptop our rancher interface crashes. The CLI likewise fails to tail the logs during this "crash / reset". These commands were run in quick succession (~2s in between).

```
~/IdeaProjects
❯ kubectl logs -f <pod-name>

<spews a bunch of logs (successful)>

~/IdeaProjects
❯  kubectl logs -f <pod-name>
error: serializer for text/plain; charset=utf-8 doesn't exist

~/IdeaProjects
❯  kubectl logs -f <pod-name>
Error from server (InternalError): an error on the server ("Service unavailable") has prevented the request from succeeding (get pods <pod-name>)

~/IdeaProjects
❯  kubectl logs -f <pod-name>
Error from server (InternalError): an error on the server ("Service unavailable") has prevented the request from succeeding (get pods <pod-name>)

~/IdeaProjects
❯ kubectl logs -f <pod-name>

<spews a bunch of logs (successful)>
```

We're running rancher 1.6.10 and agent 1.2.6

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
