### ISSUE TITLE
[Feature Request] Upgrade container on stop

### ISSUE THREAD

**Issue by furkilic** [rancher/rancher#9096]
It will be great to be able to have an option (endpoint) where during a service upgrade (with start first then stop) after creating the upgraded container instead of "force" stopping the previous one, to wait until  the previous container stop by itself. 

With this option it will be easier to make graceful upgrades and not kill potential tasks running in the previous containers. 

We can imagine this option like the "start first then stop" option where the value will be something like "only start". 
It will then start an upgraded container every batch interval. 

The label "Upgraded" will appear whenever all the upgraded containers will be started, and previous containers be stopped. 

It  will also be easy to rollback because the previous container will be already alive. So no dead time. 

Comment if you need more information. 

regards 

Furkilic

**Comment by loganhz** [comment]
I guess you can set `Drain Timeout` on a service in v1.6.22. Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
