### ISSUE TITLE
[UX Bug] Host IP Address gets cleared on upgrade

### ISSUE THREAD

**Issue by wzrdtales** [rancher/rancher#9099]
**Rancher versions:**
rancher/server: 1.6.2
rancher/agent: 1.2.2

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**

- Create a loadbalancer
- Create a new entry and press show host IP address options.
- Enter a custom IP
- Finish the upgrade
- Repeat without the second and third step
- custom IP is gone

**Results:**

Custom IP disappears and gets overwritten with the default settings.

**Comment by deniseschannon** [comment]
Duplicate of https://github.com/rancher/rancher/issues/7288
