### ISSUE TITLE
[Bug] Loadbalancer ignores scheduler ips

### ISSUE THREAD

**Issue by wzrdtales** [rancher/rancher#9100]
**Rancher versions:**
rancher/server: 1.6.2
rancher/agent: 1.2.2

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**

- Create a host with two dedicated ips
- Setup a local service on the server on port 80 and bind to one of the ips
- Add the host to rancher
- Setup the host scheduler IP settings to use the other ip
- Create a loadbalancer
- Create a new entry on port 80
- connect to both ips on port 80
- you should only be able to connect to the rancher services

**Results:**

IP settings from the host scheduler ip settings are completely ignored and all traffic is being redirected to the loadbalancer which may break any other host setup.

**Expected behavior**

Use the scheduler ip settings if no other settings on the loadbalancer are specified.

**Comment by ikogan** [comment]
I'm confirming this behavior after creating brand new hosts. This is basically making Rancher completely unusable for my installation.

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
