### ISSUE TITLE
[RFE] Customizable stack name when using catalog items from the UI

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#9101]
Allow for a name to be specified when launching a catalog item via the UI. Not sure if this is strictly UI, the CLI has this functionality...

**Comment by aemneina** [comment]
Added ask or angle: inject repo name in the stack name...

**Comment by deniseschannon** [comment]
being able to customize the names of community catalog templates already exists today for catalog items through UI and CLI, but we don't allow customizing the name of templates from the library catalog. We don't allow changing the names of the infrastructure templates as we only allow deploying 1 stack of those at a time. 

As the stack name is customizable through the UI, you can update the stack name to whatever you want. 

Through the rancher CLI, you can specify the name when deploying a catalog item.

```
rancher catalog install <CATALOG_ID> --name <NAME_OF_STACK>
```
