### ISSUE TITLE
Stack upgrade doesn't work when there is only scale number changed in rancher-compose

### ISSUE THREAD

**Issue by pengjiang80** [rancher/rancher#9103]
When calling stack upgrade API with only scale number changed in rancher-compose, the stack will be showed as upgraded but the scale number will not be changed. Also tested this with different catalog template versions and it doesn’t work either. 

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.2` Cattle: `v0.181.4` UI: `v1.6.5` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`stacks.index`|

**Comment by vincent99** [comment]
#8175
