### ISSUE TITLE
Run before stop not respected by HA-Proxy

### ISSUE THREAD

**Issue by Robbie1977** [rancher/rancher#9105]
If a single container service is upgraded with run before stop ticked I would expect the proxy to keep routing services to the existing running container until stopped but instead a 503 is returned the second the upgrade starts.

I shouldn't be forced to have multiple containers to ensure continuous service is delivered, I could live with a few seconds but to drop all services immediately on upgrade seems to defeat the purpose of having the start before stop tick-box!?

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.5.9` Cattle: `v0.178.12` UI: `v1.5.9` |
|Access|`github` `admin`|
|Orchestration|`Cattle`|

**Comment by deniseschannon** [comment]
@soumyalj This should be fixed with this issue: https://github.com/rancher/rancher/issues/8684 Please test this use case using v1.6.3-rc1+.

**Comment by soumyalj** [comment]
Tested with master 1.6 branch and 1.6.3-rc1.

1. Created service test and lb pointing to this service
2. Upgraded the service with start before stop option set
3. During upgrading state, Lb could reach its targets on the specified port. There was no 503 error.
