### ISSUE TITLE
NFS connectivity issues when message with "9 volumes" found in logs

### ISSUE THREAD

**Issue by dzolotov** [rancher/rancher#9108]
Hello, 

We are investigating error when trying to connect with NFSv4 server for the volumes, which prefixed with some strange log messages:

19.06.2017 22:05:02time="2017-06-19T19:05:02Z" level=warning msg="9 volumes with name=git-data found in Rancher"
19.06.2017 22:05:02time="2017-06-19T19:05:02Z" level=warning msg="9 volumes with name=git-config found in Rancher"
19.06.2017 22:05:02time="2017-06-19T19:05:02Z" level=warning msg="9 volumes with name=git-log found in Rancher"

This issue affects only some volumes, differentiated by these messages. Any other volumes (on same hosts) mounts fine. We've tried to restart NFS server, but these actions don't change this behavior.

**Rancher versions:**
rancher/server: 1.6.2
rancher/agent: 1.2.2

**Infrastructure Stack versions:**
network-services: 0.6.6

**Docker version: (`docker version`,`docker info` preferred)** 
17.04.0-ce
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
RancherOS v1.0.1 kernel 4.9.24

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Parallels VM

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Rancher HA. External DB: galera cluster

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
cattle

**Steps to Reproduce:**
Do some service upgrades (with mounted NFS external volumes)
**Results:**
Container starts and immediately stops, or stays in "Starting" phase.

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
