### ISSUE TITLE
review rancher-secrets volume permissions

### ISSUE THREAD

**Issue by oskapt** [rancher/rancher#9109]
## Summary

Rancher Secrets creates a tmpfs volume under `/var/lib/rancher/volumes/rancher-secrets`, within which it places the the file(s) with the secret information.

`rancher-secrets` is mode 0755 and the subsequent volume is 1777.  The files inside are created with the mode designated in the Rancher UI. 

The result of this is that anyone with an account on the system can read any secret. Additionally, because the tmpfs volume is 1777, they can create new files that appear inside of the container in `/run/secrets`.

## Workaround

When attaching a secret to a service, select the link to "Customize file ownership & permissions" and set permissions there as follows:
- set file mode '0440'
- if running as a specific user inside of the container, set the uid and/or gid to match the container user
- manually or via automation set permissions on `/var/lib/rancher/volumes/rancher-nfs` to 0711

## Proposed Solution

The tmpfs volume created is a 65-character string. In order to be secure by default, setting `/var/lib/rancher/volumes/rancher-secrets` to mode 0711 would allow Rancher to access the contents of the directory by name (a name that it already knows) and prevent normal users on the host from using `ls` to determine the directory name. This would prevent anyone from changing into the directory to read the secrets files.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
