### ISSUE TITLE
DNS resolving of services in stack suddenly is broken

### ISSUE THREAD

**Issue by EugenMayer** [rancher/rancher#9111]
**Rancher versions:**
rancher/server:
1.6.2
rancher/agent:
latest

**Infrastructure Stack versions:**
healthcheck: latest (upgraded max)
ipsec: latest (upgraded max)
network-services: latest (upgraded max)
scheduler:latest (upgraded max)

**Docker version: (`docker version`,`docker info` preferred)**
Server Version: 17.03.1-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
rancheros 1.0.1-LTS

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Baremetal under KVM (proxmox)

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
no HA, internal DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
no idea

**Results:**
Suddenly the containers cannot resolve any other services in their stack.

I could fixed it removing the net metadata container + sidekick (DNS) in the network-services server and the removing the container and creating them again - this restored the DNS capability.

What i tried also (and did not help):
 - restarting rancher os
 - restart the stack
 - removing containers
 - upgrading from 1.6.0 to 1.6.2
 - upgrading all inftrastructure-servers in the upgrade from 1.6.0->1.6.2

**Comment by leodotcloud** [comment]
@EugenMayer any steps to reproduce this issue would be helpful. Also could you please share the logs using: https://github.com/leodotcloud/rancher-logs-collector

**Comment by aemneina** [comment]
Would you happen to have the logs for the metadata+sidekick before you deleted them? That might help uncover the issue.

**Comment by EugenMayer** [comment]
no logs here, but if you tell me how to retrieve them, i will come back when it happens again.

There are, for sure, some bugs with the DNS server, e.g. cache issues - removing the DNS sidekick container and creating it again does fix this too.

**Comment by JoelESvensson** [comment]
This happens a lot for me when I upgrade services. DNS resolution for linked services stops working until I restart metadata. I'm using 1.6.2 and my containers use Alpine Linux as the base

**Comment by EugenMayer** [comment]
Restarting the DNS services works for "flushing DNS" - so clearing the cache in case of issues. Restarting it when local DNS resolving is broken does not help though

**Comment by ket4yii** [comment]
Maybe this issue connected with #8805. But if not, maybe it would be a ping for developers :)

**Comment by superseb** [comment]
@EugenMayer We do appreciate reported issues, please keep reporting them. In comment https://github.com/rancher/rancher/issues/9111#issuecomment-309873440 there is a link to a repository to retrieve logs. Let me know if this works for you.

I'm interested in the logging of the metadata container, it seems it hangs or is unresponsive.

**Comment by leodotcloud** [comment]
ping @EugenMayer

**Comment by EugenMayer** [comment]
@leodotcloud whats the matter? thats a `kind/question` here, i cannot see a reason to continue working on this item - sorry

**Comment by leodotcloud** [comment]
@EugenMayer We were hoping if you had run into this again and could share logs with us.

**Comment by leodotcloud** [comment]
I am closing this issue, please feel free to open a new one if you hit it again. Remember to use the logs collector tool: https://github.com/rancher/rancher-logs-collector

**Comment by EugenMayer** [comment]
@leodotcloud sure. All i wanted to say, i was treating the issue with the importance you (aemneina) was treating it. So if you plan to give the issue a weight or consider it interesting since its an important bug, you might not use a label which reflects the "come back to this issue when really nothing is left else" label.

Still, no worries / hard feelings. Learned my lesson too.

**Comment by aemneina** [comment]
Hi @EugenMayer `kind/question` is more for us to track that we havent determined the nature of the ticket. After determining its a bug we move it over to `kind/bug`. Sorry for the confusion.
