### ISSUE TITLE
Needs to update generic object data with api

### ISSUE THREAD

**Issue by orangedeng** [rancher/rancher#9113]
**Rancher versions:**
rancher/server:master
rancher/agent:v1.2.2

**Infrastructure Stack versions:**
healthcheck: n/a
ipsec: n/a
network-services: n/a
scheduler: n/a
kubernetes (if applicable): n/a

**Docker version: (`docker version`,`docker info` preferred)**
n/a
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
n/a
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
n/a
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
n/a
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
1. use api to save a new generic object.
2. use api to update the `resourceData` field of generic object.
**Results:**
rancher does not allow me to update.

**Comment by yasker** [comment]
@cjellick Do you have time for this? CICD progress has been blocked by this.

**Comment by cjellick** [comment]
This is needed by the ciproject team. There isn't much to test here and it isnt something that users will interact with directly, just indirectly through their consumption of the ci-pipeline feature.

**Comment by orangedeng** [comment]
Already in use. Solved.
