### ISSUE TITLE
Kubectl on host returns error: couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" 

### ISSUE THREAD

**Issue by gargamile** [rancher/rancher#9114]
**Rancher versions:**
Rancher 	v1.6.2

**Infrastructure Stack versions:**
kubernetes (if applicable):
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.6", GitCommit:"7fa1c1756d8bc963f1a389f4a6937dc71f08ada2", GitTreeState:"clean", BuildDate:"2017-06-16T18:34:20Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"2+", GitVersion:"v1.2.0-rancher-1", GitCommit:"ed6532f975cff184196dbe214de8fa0198b415ef", GitTreeState:"clean", BuildDate:"", GoVersion:"", Compiler:"", Platform:""}

**Docker version: (`docker version`,`docker info` preferred)**
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   78d1802
 Built:        Tue Jan 31 23:35:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   78d1802
 Built:        Tue Jan 31 23:35:14 2017
 OS/Arch:      linux/amd64

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04.02 LTS

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Two node rancher. This is on the Kubernetes / Rancher master, trying to run kubectl commands manually and returning an error, I believe this is due to different server and client version installed. 

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
1) Download and run Rancher/stable docker container
2) Setup environment in Rancher with Kubernetes 
3) SSH into Rancher Master and install kubectl
4) Create YAML file:

kind: PersistentVolume
apiVersion: v1
metadata:
  name: repo-DB-pv
  labels:
    type: amazonEBS
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-0cc2XXXXXXX
    fsType: ext4

5)  kubectl create -f repo-pv.YAML

**Results:**
$ kubectl create -f repo-pv.YAML
error: couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }

Note: This is an issue for all kubectl commands run on the host (except for version), running the commands in Rancher Kubernetes CLI works correctly however.

Rancher CLI shows kubectl version as 1.5.4 for both server and client:
> kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.4", GitCommit:"7243c69eb523aa4377bce883e7c0dd76b8470
9a1", GitTreeState:"clean", BuildDate:"2017-03-07T23:53:09Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"
}
Server Version: version.Info{Major:"1", Minor:"5+", GitVersion:"v1.5.4-rancher1", GitCommit:"6ed2b64b2e1df9637661077d877
a0483c58a6ae5", GitTreeState:"clean", BuildDate:"2017-03-17T16:58:04Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"li
nux/amd64"}

**Comment by gargamile** [comment]
Creating ~/.kube/config and placing this into the host allowed

**Comment by m-abramovich** [comment]
I also faced same issue.
Most likely this is caused by Rancher authentication.
```
kubectl config view
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: http://rancher.abc.com:80/r/projects/1a34/kubernetes:6443
  name: abc
contexts:
- context:
    cluster: abc
    user: abc
  name: abc
current-context: abc
kind: Config
preferences: {}
users:
- name: abc
  user:
    token: abc123ABC
```
If I request over there:
```
$ curl http://rancher.abc.com:8080/r/projects/1a34/kubernetes:6443
<a href="/login?redirectTo=%2Fr%2Fprojects%2F1a34%2Fkubernetes%3A6443#">Found</a>.
```
But kubectl expects to see the APIVersion (exactly like said in error):
```
{
"paths": [
"/api",
"/api/v1",
"/apis",
"/apis/",
"/apis/admissionregistration.k8s.io",
"/apis/admissionregistration.k8s.io/v1beta1",
"/apis/apiextensions.k8s.io",
"/apis/apiextensions.k8s.io/v1beta1",
"/apis/apiregistration.k8s.io",
"/apis/apiregistration.k8s.io/v1beta1",
"/apis/apps",
"/apis/apps/v1",
"/apis/apps/v1beta1",
"/apis/apps/v1beta2",
"/apis/authentication.k8s.io",
"/apis/authentication.k8s.io/v1",
"/apis/authentication.k8s.io/v1beta1",
"/apis/authorization.k8s.io",
"/apis/authorization.k8s.io/v1",
"/apis/authorization.k8s.io/v1beta1",
"/apis/autoscaling",
"/apis/autoscaling/v1",
"/apis/autoscaling/v2beta1",
"/apis/batch",
"/apis/batch/v1",
"/apis/batch/v1beta1",
"/apis/batch/v2alpha1",
"/apis/certificates.k8s.io",
"/apis/certificates.k8s.io/v1beta1",
"/apis/events.k8s.io",
"/apis/events.k8s.io/v1beta1",
"/apis/extensions",
"/apis/extensions/v1beta1",
"/apis/networking.k8s.io",
"/apis/networking.k8s.io/v1",
"/apis/policy",
"/apis/policy/v1beta1",
"/apis/rbac.authorization.k8s.io",
"/apis/rbac.authorization.k8s.io/v1",
"/apis/rbac.authorization.k8s.io/v1beta1",
"/apis/storage.k8s.io",
"/apis/storage.k8s.io/v1",
"/apis/storage.k8s.io/v1beta1",
"/healthz",
...
...
...
"/logs",
"/metrics",
"/swagger-2.0.0.json",
"/swagger-2.0.0.pb-v1",
"/swagger-2.0.0.pb-v1.gz",
"/swagger.json",
"/swaggerapi",
"/ui",
"/ui/",
"/version"
]
}
```
I guess this [answer](url=https://github.com/rancher/rancher/issues/7504#issuecomment-366162590) worths to be reviewed.

**Comment by ica10888** [comment]
This error can happen in case you have no `~/.kube/config` in place.

**Comment by mcarbonera** [comment]
I got this error on google cloud. Needed to run:
gcloud container clusters get-credentials <CLUSTER_NAME>

**Comment by emanuele-leopardi** [comment]
I had a similar error in other circumstances. try simply add -o yaml as the output of the apply command

**Comment by yuriy-filatov** [comment]
Seems you need to rerun `aws configure` and set output to json instead of text.

**Comment by imcom** [comment]
> Seems you need to rerun `aws configure` and set output to json instead of text.

this saved my day!

**Comment by williwlwilliwll** [comment]
> > Seems you need to rerun `aws configure` and set output to json instead of text.
> 
> this saved my day!

Same!

**Comment by sobankhan12** [comment]
> Seems you need to rerun `aws configure` and set output to json instead of text.

Same!

**Comment by OctavioBR** [comment]
set `AWS_DEFAULT_OUTPUT=json` env before running your command if you don't want change your default aws-cli output
