### ISSUE TITLE
UI doesnt give the option of disabling scheduler in env template creation screen

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#9115]
**Rancher versions:**
rancher/server: 1.5.10

**Steps to Reproduce:**
1. create environment template (in this case kubernetes based)
2. scheduler stack/service is enabled
3. no option to disable scheduler stack from env template

**Comment by aemneina** [comment]
@deniseschannon pointed out that you have to hit Ctrl or Command + clicking the requied. maybe a pop up dialog or something to hint would be nice.

**Comment by vincent99** [comment]
302 @willchan, the only reason there's a hidden option is because I didn't want to make them required...

**Comment by vincent99** [comment]
Old and n/a to 2.0.
