### ISSUE TITLE
Services that depend on rancher-efs volume driver are slow to start

### ISSUE THREAD

**Issue by wjimenez5271** [rancher/rancher#9116]
**Rancher versions:**
rancher/server: 1.6.2
rancher/agent:

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
Docker version 17.03.1-ce, build c6d412e

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
Kernel 3.10.0-327.10.1.el7.x86_64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single master, internal DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
1. Create service with a volume defined that uses the rancher-efs volume driver.
2. Service will take up to 4 minutes to start

**Results:**

Logs from efs infrastructure stack:

```
6/20/2017 1:29:50 PMtime="2017-06-20T03:29:50Z" level=info msg=Running
6/20/2017 1:29:50 PMtime="2017-06-20T03:29:50Z" level=info msg=Starting
6/20/2017 1:29:51 PMtime="2017-06-20T03:29:51Z" level=info msg="Running on host rancher-node-0a-ad-3a-8d-de-20(1h1) with driver rancher-efs(1sd2)"
6/20/2017 1:29:51 PMtime="2017-06-20T03:29:51Z" level=info msg="Starting plugin for rancher-efs"
6/20/2017 2:06:01 PMtime="2017-06-20T04:06:01Z" level=info msg=create.request name=foofoo1
6/20/2017 2:08:42 PMtime="2017-06-20T04:08:42Z" level=info msg="Updating volume foofoo1 (1v58) rancher-efs:1sd2 on 1h1, state inactive => updating-inactive" err=<nil>
6/20/2017 2:08:42 PMtime="2017-06-20T04:08:42Z" level=info msg=create.response
6/20/2017 2:08:42 PMtime="2017-06-20T04:08:42Z" level=info msg=attach.request name=foofoo1
6/20/2017 2:08:42 PMtime="2017-06-20T04:08:42Z" level=info msg=attach.response
6/20/2017 2:08:43 PMtime="2017-06-20T04:08:43Z" level=info msg=mount.request name=foofoo1
6/20/2017 2:09:47 PMtime="2017-06-20T04:09:47Z" level=info msg=mount.response mountpoint="/var/lib/rancher/volumes/rancher-efs/foofoo1"
6/20/2017 2:09:47 PMtime="2017-06-20T04:09:47Z" level=info msg=unmount.request name=foofoo1
6/20/2017 2:09:47 PMtime="2017-06-20T04:09:47Z" level=info msg=unmount.response
6/20/2017 2:09:47 PMtime="2017-06-20T04:09:47Z" level=info msg=mount.request name=foofoo1
6/20/2017 2:09:47 PMtime="2017-06-20T04:09:47Z" level=info msg="foofoo1 already mounted on /var/lib/rancher/volumes/rancher-efs/foofoo1"
6/20/2017 2:09:47 PMtime="2017-06-20T04:09:47Z" level=info msg=mount.response mountpoint="/var/lib/rancher/volumes/rancher-efs/foofoo1"
```

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
