### ISSUE TITLE
[go-rancher] How do I use go-rancher generate the rancher-catalog ? 

### ISSUE THREAD

**Issue by LanceNero** [rancher/rancher#9117]
**Rancher versions:**
rancher/server: v1.4
rancher/agent: v1.2.2

 Hi ：
    I would like to ask how to use go-rancher generate the rancher-catalog and add it to rancher?

    I did not find any test sample or example in the project

    if your have some guide-doc or example ,Can you tell me where I can see it?

Thanks for your help~

**Comment by leodotcloud** [comment]
@LanceNero `go-rancher` is a Go library for accessing Rancher REST API. I don't understand what you are trying to achieve? Did you mean you want to add your own catalog using the library calls?

**Comment by LanceNero** [comment]
@leodotcloud 
 Yes , I want use go-rancher to add some catalog ,  but i didn't know how use the library 
 After that, I found some code for use this library in other project , and  I can refer to these code to use the library.

- [https://github.com/hashicorp/terraform/tree/v0.9.6/builtin/providers/rancher](url)
- https://github.com/rancher/cli/tree/master/cmd

 Thanks for you reply. :)
