### ISSUE TITLE
Deleting a stack automatically deletes the load balancer's selector rules

### ISSUE THREAD

**Issue by jeanpommier** [rancher/rancher#9118]
Hi
In my main Load balancer, I've got several selector rules that redirect the traffic to internal load balancers in my stacks. The selector rules are mutual for all the stacks.
If I delete one of the stacks, it automatically removes the selector rules from my main load balancer, even if other stacks used them too. That's a bit of a nuisance. It would be much better not to touch selector rules at all.
Thanks

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.2` Cattle: `v0.181.4` UI: `v1.6.5` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`admin-tab.auth.localauth`|

**Comment by deniseschannon** [comment]
@jeanpommier Could you provide exact steps of what you're doing. We've tried reproducing and am unable to reproduce it. What is a sample docker-compose.yml of your stacks? Where are you seeing the selector rules being deleted?

**Comment by jeanpommier** [comment]
Hi,
Yes sure, I can ry to make it clearer. As a matter of fact, if you can wait a few days (I've got things to finish quick), I can try to make up a testing environment at your disposal, setting up a few VMs.
For now : 
I deploy some stacks with internal load balancers. I'm following a post from https://medium.com/@AaronThorp/rancher-load-balancing-multiple-domains-and-ssl-ec0d2d81a0f3 : every stack has its load balancers, one for http and the other one for https. Them have, respectively, labels web.http=true and web.https=true. They filter out the requests depending on the targeted hostname
I have a global load balancer, in an independent stack, that has 2 selector rules : 
- one getting all traffic on port 80 to rule web.http=true, port 80
- the other one for ssl termination does the same from port 443 to web.https=true, port 80
If I remove one of the stacks, either from UI or CLI, the stack is removed, but also the 2 selector rules in the global load balancer.
I'll try to set up a testing environment and let you know when it's done.

**Comment by jeanpommier** [comment]
@deniseschannon Hi, I've set up for you a minimal infrastructure (2 VPS, one hosting rancher, the other one serving as host)  reproducing the bug. I'm willing to give you credentials to these servers so that you could track this behaviour. However, I'd prefer not to broadcast them. Can you please contact me at jean.pommier at pi-geosolutions.fr or give me your email ? Thanks

**Comment by alena1108** [comment]
@jeanpommier do you mind sharing the exported docker-compose/rancher-compose files of your global lb stack and intrenal load balancer(s) stacks?

**Comment by jeanpommier** [comment]
@alena1108 Hi, sorry : I had set up a specific config for you to test, but I've been 15 days without news from you guys and moved on. I've tried to set it back, but I can't reproduce the bug. I'll try some more and let you know if I manage to get it back (it seems necessary to run operations in a specific order, I still haven't found precisely the pattern...

**Comment by jeanpommier** [comment]
@alena1108 Hi again,
Finally I managed to get it [not working] again. I've tried to reduced the config at its minimum while preserving this improper behavior.
Here are my compose files. I define 3 stacks : 
 - default is the entry stack (public LB). You''l have to set a SSL certificate, since it seems to need at least 2 selector rules to trigger the strange behavior.
 - stack 1 and 2 have the internal LBs

If you look at the main LB, you'll see a service rule pointing to one of the services in stack 1. And the selector rules would redirect traffic to one of the internal LBs in each stack, depending on whether we're using SSL or not (setup inspired from https://medium.com/@AaronThorp/rancher-load-balancing-multiple-domains-and-ssl-ec0d2d81a0f3)

Try removing stack1 and then check the main-LB. It should have kept at least the selector rules, since they are used in stack 2 too, but it will have removed all rules.
[compose-defaultstack.zip](https://github.com/rancher/rancher/files/1148099/compose-defaultstack.zip)
[compose-stack1.zip](https://github.com/rancher/rancher/files/1148104/compose-stack1.zip)
[compose-stack2.zip](https://github.com/rancher/rancher/files/1148103/compose-stack2.zip)

**Comment by alena1108** [comment]
@jeanpommier thanks for the info, will look into it

**Comment by alena1108** [comment]
@sangeethah the bug is very easy to reproduce. Steps:

1) Create service foo.
2) Create LB with 2 port rules, one have a selector, and one points to the service foo. No need to have a backend service satisfying the selector.
3) Remove service foo. Validate that only the port rule pointing to service foo, is gone; selector based rule should stay intact.

@jeanpommier great issue, thanks for reporting it.

**Comment by sangeethah** [comment]
Tested with rancher-server build from branch V1.6
Lb image - rancher/lb-service-haproxy:v0.7.6

Steps to reproduce the problem:
Create service foo.
Create LB with 2 port rules .
1 service port rule pointing to   service foo. 
1 selector port rule. 
Remove service foo. 

Only port rule pointing to service foo get deleted from LB service.
Selector rule is still present in LB and is reachable as expected.
