### ISSUE TITLE
rancher/external-dns: gandi provider fails with error "No such version 'xxx'] code: 581042"

### ISSUE THREAD

**Issue by fredleger** [rancher/rancher#9122]
**Rancher versions:**
rancher/server: 1.5.3
rancher/agent:

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
1.12.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Debian 8

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
OVH

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node, internal DB bind mounted

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Just let it run for a while and it while happens

**Results:**
```
20/06/2017 23:35:47time="2017-06-20T21:35:47Z" level=error msg="Failed to update provider with new DNS records: Provider error reading dns entries: Failed to get records in zone: error: \"Error on object : OBJECT_ZONE (CAUSE_NOTFOUND) [No such version '342']\" code: 581042"
20/06/2017 23:35:48time="2017-06-20T21:35:48Z" level=error msg="Failed to update provider with new DNS records: Provider error reading dns entries: Failed to get records in zone: error: \"Error on object : OBJECT_ZONE (CAUSE_NOTFOUND) [No such version '342']\" code: 581042"
20/06/2017 23:35:49time="2017-06-20T21:35:49Z" level=error msg="Failed to update provider with new DNS records: Provider error reading dns entries: Failed to get records in zone: error: \"Error on object : OBJECT_ZONE (CAUSE_NOTFOUND) [No such version '342']\" code: 581042"
20/06/2017 23:35:50time="2017-06-20T21:35:50Z" level=error msg="Failed to update provider with new DNS records: Provider error reading dns entries: Failed to get records in zone: error: \"Error on object : OBJECT_ZONE (CAUSE_NOTFOUND) [No such version '342']\" code: 581042"
```

I went through the code and i think this is related to the fact that Gandi is only keeping 5 versions of zones accessible to the API. At least it's what we can see from the GUI :

<img width="961" alt="capture d ecran 2017-06-20 a 23 45 55" src="https://user-images.githubusercontent.com/2778741/27357558-edceb974-5612-11e7-8a28-b0bb19a1df78.png">

**Comment by deniseschannon** [comment]
@fredleger I've released  `rancher/external-dns:v0.7.2` that has this fix.
