### ISSUE TITLE
Add host fails on an authenticated setup 

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#9128]
**Rancher versions:**
rancher/server:v1.6.3-rc1
rancher/agent:rancher/agent:v1.2.3-rc1

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**Ubuntu

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**Digital Ocean/AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**Single node

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**Cattle

**Steps to Reproduce:**
1. Create a cattle setup and enable auth. OR Upgrade from 1.6.2 to 1.6.3-rc1 with auth enabled
2. Add a host through UI

**Results:**
Rancher agent fails to start with the following error. Add host is unsuccessful.
```
ERROR: http://35.184.218.248:8080/v1 is not accessible (The requested URL returned error: 401 Unauthorized)
ERROR: http://35.184.218.248:8080/v1 is not accessible (The requested URL returned error: 401 Unauthorized)
ERROR: http://35.184.218.248:8080/v1 is not accessible (The requested URL returned error: 401 Unauthorized)
ERROR: http://35.184.218.248:8080/v1 is not accessible (The requested URL returned error: 401 Unauthorized)
ERROR: http://35.184.218.248:8080/v1 is not accessible (The requested URL returned error: 401 Unauthorized)
```

**Comment by deniseschannon** [comment]
Available in rancher/agent:v1.2.3-rc2.

This is now in master and v1.6 branch of cattle.

**Comment by soumyalj** [comment]
Tested with master v1.6 branch. Enabled auth on the setup and added a host. Addition of host was successful. Agent version was rancher/agent:v1.2.3-rc2

**Comment by ramagopr1976** [comment]
I am getting the same error. Please let me know what is the solution. All I am trying is to add a host to the rancher server running inside a docker container.

RAMKUMARs-MBP:~ ramagopr$ sudo docker run -e CATTLE_AGENT_IP="52.62.40.106"  --rm --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /private/var/lib/rancher:/var/lib/rancher rancher/agent:v1.2.5 http://localhost:32772/v1/scripts/27E241A87324A765AEDE:1483142400000:mHM9ukEqCB0Pqd6MTv1lO7g3UE8

INFO: Running Agent Registration Process, CATTLE_URL=http://192.168.65.2:32772/v1
INFO: Attempting to connect to: http://192.168.65.2:32772/v1
ERROR: http://192.168.65.2:32772/v1 is not accessible (The requested URL returned error: 404 Not Found)
ERROR: http://192.168.65.2:32772/v1 is not accessible (The requested URL returned error: 404 Not Found)
ERROR: http://192.168.65.2:32772/v1 is not accessible (The requested URL returned error: 404 Not Found)
ERROR: http://192.168.65.2:32772/v1 is not accessible (The requested URL returned error: 404 Not Found)
