### ISSUE TITLE
Test plan for LDAP porting to auth service

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#9129]
Test plan for the LDAP changes tracked in these issues:
#8115 
#6378 

@mrajashree Can you please review these test cases, i added the old test cases as well, to have one tesplan for all LDAP/AD features.

[LDAP-Test-Plan.xlsx](https://github.com/rancher/rancher/files/1092683/LDAP-Test-Plan.xlsx)

**Comment by mrajashree** [comment]
Looks good
