### ISSUE TITLE
Add support for`init-path` option in docker-compose.yml

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#9133]
Separated from `init-path` from the original issue: https://github.com/rancher/rancher/issues/8608

**Rancher Versions:**
Server: 1.5.4

Init option configures the container to run an init process as PID1 that forwards signals and reaps zombie processes. Docker run command currently supports the `init-path` option in addition to `init` but this has been removed as of Docker 17.05 (https://github.com/moby/moby/pull/32470). 
 ```
$ docker run --help | grep init
      --init-path string           Path to the docker-init binary
 ```

`init-path` is not supported in compose yet. 

Requirement:
We need to be able to specify those in either docker-compose or rancher-compose files.

**Comment by aemneina** [comment]
@prachidamle or @janeczku would you be able to take a peek at this when you get a chance?

**Comment by janeczku** [comment]
@deniseschannon i have updated your description to clarify that `init-path` has been dropped from docker run command.
