### ISSUE TITLE
dockerfile directive in docker-compose.yml (v1 and v2) is ignored

### ISSUE THREAD

**Issue by arnauorriols** [rancher/rancher#9134]
When you have a docker-compose.yml with custom dockerfile name for your services, this directive is ignored, and rancher tries to find a file "Dockerfile" in the root of the build context. Basically, what I want is what can be seen in this integration test of rancher-compose-executor, which is currently being skipped: https://github.com/rancher/rancher-compose-executor/blob/90cfd1c2a7e230dc5963152f3ce8649712f54552/tests/integration/cattletest/core/test_compose.py#L182

I'm currently designing the development workflow of a team, and while I can workaround the need to expose the build context with a git server, not being able to have multiple dockerfiles inside my repo is a no-go. This test is currently being skipped, which tells me that this is a known issue. Regardless of when exactly do you plan to fix it, it would be very helpful for me to know if you plan on fixing this in the short-middle term, or if for some rancher-specific constraint, you have decided not to support this directive any time soon. This will tell me if I can assume this working eventually, or I should just redesign the development workflow altogether to achieve what I want in another way. 

FWIW, docker-compose does parse my docker-compose.yml correctly, so it's a Rancher specific issue. 

**Rancher versions:**
rancher/server: 1.5.10
rancher/agent: 1.2.2

**Infrastructure Stack versions:**
healthcheck: 0.2.3  
scheduler: 0.7.5
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
```
Containers: 9
 Running: 1
 Paused: 0
 Stopped: 8
Images: 8
Server Version: 17.05.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.66-boot2docker
Operating System: Boot2Docker 17.05.0-ce (TCL 7.2); HEAD : 5ed2840 - Fri May  5 21:04:09 UTC 2017
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 995.6MiB
Name: rancher-host-3
ID: 5CTV:QFTY:TOUW:KXJD:XGU3:AKWM:TI6L:T7VH:LO5F:NEPU:BPQB:XHHF
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 21
 Goroutines: 27
 System Time: 2017-06-22T06:47:44.646341957Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**: 4.4.66-boot2docker

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**: Docker-machine over Virtualbox

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**: single node rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**: Cattle

**Steps to Reproduce:**: Try to deploy a stack with the following docker-compose.yml:
```
database:
  build: git://192.168.99.1/#:deploy/dockerfiles/
  dockerfile: mongodb/Dockerfile
  hostname: mongo
  dns: 172.17.0.1
  expose:
    - "28017"
  restart: always
  command: /usr/bin/mongod --dbpath /var/lib/mongodb
```

**Results:**
```
time="2017-06-21T19:51:26Z" level=info msg="Received event: Name: storage.image.activate, Event Id: 14f23a46-4511-4a97-b121-f31705294467, Resource Id: 1ispm691" 
time="2017-06-21T19:52:15Z" level=error msg="Error processing event" err="Error response from daemon: Cannot locate specified Dockerfile: Dockerfile" eventId=14f23a46-4511-4a97-b121-f31705294467 eventName=storage.image.activate resourceId=1ispm691
```

**Comment by PaoloC68** [comment]
This seems to me to be a serious bug, I wasted a lot of time trying to understand why I could not get mys services up and running and now I discovered this, please prioritize this issue!

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
