### ISSUE TITLE
rancher-compose Failed Starting service (Client.Timeout exceeded while awaiting headers)

### ISSUE THREAD

**Issue by asciiman** [rancher/rancher#9136]
**Rancher versions:**
1.1.4

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

When I run docker-compose I am getting timeouts.

```
$ rancher-compose -p ${ENV}-blue up --force-upgrade --pull -d --confirm-upgrade
time="2017-06-22T10:31:17Z" level=info msg="[0/1] [messaging-service]: Starting " 
time="2017-06-22T10:31:19Z" level=info msg="Finished pulling registry.example.com/backend/messaging:staging" 
time="2017-06-22T10:31:19Z" level=info msg="Updating messaging-service" 
time="2017-06-22T10:31:21Z" level=info msg="Upgrading messaging-service" 
time="2017-06-22T10:31:49Z" level=error msg="Failed Starting messaging-service : Get https://rancher.example.com/v1/services/1s146: net/http: request canceled (Client.Timeout exceeded while awaiting headers)" 
time="2017-06-22T10:31:49Z" level=error msg="Failed to start: messaging-service : Get https://rancher.example.com/v1/services/1s146: net/http: request canceled (Client.Timeout exceeded while awaiting headers)" 
time="2017-06-22T10:31:49Z" level=fatal msg="Get https://rancher.example.com/v1/services/1s146: net/http: request canceled (Client.Timeout exceeded while awaiting headers)" 
mesg: ttyname failed: Inappropriate ioctl for device
ERROR: Build failed: exit status 1
```

I followed the instructions in [this issue](https://github.com/rancher/rancher/issues/6243), restarting rancher-compose-executor service and web-socket-proxy, and I'm still getting the error.

I am seeing one of my go machines is trying to be removed and seems to be stuck.

![image](https://user-images.githubusercontent.com/645336/27431153-bc0fa346-574b-11e7-9217-c9739313879a.png)

I am also seeing several volume purges that timed out, and an agent.reconnect that timed out.  I'm not sure if these are related and how to resolve it if they are.

![image](https://user-images.githubusercontent.com/645336/27431181-e0eb4800-574b-11e7-8683-4937d82dd4f4.png)

**Comment by fkollmann** [comment]
Same issue here. Seems to happen if the compose file contains volumes (rancher-nfs in our case).

**Comment by superseb** [comment]
Closing this as it's reported on v1.1.4. @fkollmann @asciiman can you reproduce on a recent version and file an issue with the definition that produces this error so I can reproduce?
