### ISSUE TITLE
Add host does not work on Rachner server machine (server 1.6.1/agent 1.2.2)

### ISSUE THREAD

**Issue by FFock** [rancher/rancher#9137]
**Rancher versions:**
rancher/server: 1.6.1
rancher/agent: 1.2.2

**Infrastructure Stack versions:**
healthcheck: n/a
ipsec: n/a
network-services: n/a
scheduler: n/a
kubernetes (if applicable): n/a

**Docker version: (`docker version`,`docker info` preferred)**
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   78d1802
 Built:        Tue Jan 31 23:35:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   78d1802
 Built:        Tue Jan 31 23:35:14 2017
 OS/Arch:      linux/amd64

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
4.4.0-81-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Open Telekom Cloud (OTC)

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node, external DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**
Run the following command. 192.168.1.4 is the internal IPv4 address of the security group of the virtual server. UDP 500 and 4500 are open inbound and outbound within security group:
sudo docker run -e CATTLE_AGENT_IP="192.168.1.4" --add-host myhost:192.168.1.4  --rm --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.2.2 https://myhost/v1/scripts/5E472D19CC95C1C6256B:1483142400

**Results:**
_Server_:
2017-06-22 14:02:01,925 ERROR [:] [] [] [] [TaskScheduler-1] [i.c.p.a.s.ping.impl.PingMonitorImpl ] Failed to get ping from agent [5] count [3]
2017-06-22 14:02:06,927 ERROR [:] [] [] [] [TaskScheduler-1] [i.c.p.a.s.ping.impl.PingMonitorImpl ] Failed to get ping from agent [5] count [4]
2017-06-22 14:02:11,928 ERROR [:] [] [] [] [TaskScheduler-1] [i.c.p.a.s.ping.impl.PingMonitorImpl ] Failed to get ping from agent [5] count [5]
2017-06-22 14:02:16,929 ERROR [:] [] [] [] [TaskScheduler-1] [i.c.p.a.s.ping.impl.PingMonitorImpl ] Failed to get ping from agent [5] count [6]
2017-06-22 14:02:16,931 ERROR [:] [] [] [] [TaskScheduler-1] [i.c.p.a.s.ping.impl.PingMonitorImpl ] Scheduling reconnect for [5]
2017-06-22 14:02:21,950 ERROR [:] [] [] [] [TaskScheduler-2] [i.c.p.a.s.ping.impl.PingMonitorImpl ] Failed to get ping from agent [5] count [7]
2017-06-22 14:02:26,952 ERROR [:] [] [] [] [TaskScheduler-1] [i.c.p.a.s.ping.impl.PingMonitorImpl ] Failed to get ping from agent [5] count [8]
2017-06-22 14:02:31,955 ERROR [:] [] [] [] [TaskScheduler-1] [i.c.p.a.s.ping.impl.PingMonitorImpl ] Failed to get ping from agent [5] count [9]

_Agent:_
Updating certificates in /etc/ssl/certs...
1 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
Found container ID: 6a8a5d0111fa7570b0ab6ba1a144ca16855847fd2d9b0d0677473d9e3f306a27
Checking root: /host/run/runc
Checking file: 6a8a5d0111fa7570b0ab6ba1a144ca16855847fd2d9b0d0677473d9e3f306a27
Found state.json: 6a8a5d0111fa7570b0ab6ba1a144ca16855847fd2d9b0d0677473d9e3f306a27
time="2017-06-22T14:01:36Z" level=info msg="Execing [/usr/bin/nsenter --mount=/proc/80224/ns/mnt -F -- /var/lib/docker/overlay/9aa815b826dd3f8c381ce730bf9dd2396cf6f53ab094fa4744b26ff31e64c53d/merged/usr/bin/share-mnt --stage2 /var/lib/rancher/volumes /var/lib/kubelet -- norun]"
Found container ID: 6a8a5d0111fa7570b0ab6ba1a144ca16855847fd2d9b0d0677473d9e3f306a27
Checking root: /run/runc
Checking file: 6a8a5d0111fa7570b0ab6ba1a144ca16855847fd2d9b0d0677473d9e3f306a27
Found state.json: 6a8a5d0111fa7570b0ab6ba1a144ca16855847fd2d9b0d0677473d9e3f306a27
INFO: Starting agent for 8B250759F46F0214DC73
INFO: Starting agent for 8B250759F46F0214DC73
INFO: Starting agent for 8B250759F46F0214DC73
INFO: Starting agent for 8B250759F46F0214DC73
INFO: Starting agent for 8B250759F46F0214DC73
INFO: Starting agent for 8B250759F46F0214DC73
INFO: Starting agent for 8B250759F46F0214DC73
...

The host does not appear in the Rancher UI Hosts list and the last "INFO: Starting agent..." log entry repeats for ever.

How can I debug this issue any further? 
Why is the agent continously started (without error message about any failure)?

**Comment by vincent99** [comment]
You cannot use add-host, the command you're running starts another container that will not have it and exits.

**Comment by FFock** [comment]
I am using --add-host, what is wrong with that?

**Comment by vincent99** [comment]
As I said, you cannot use it because the container you run starts another container that is not going to have it.

**Comment by FFock** [comment]
But connection to the rancher server does only work if I use it, if I do not add it, the command fails with 
ERROR: https://myhost/v1 is not accessible
So it does work - at least on some layer. 
But how can I propagate the hostname/IP mapping to the final container then?

**Comment by FFock** [comment]
Apparently it seems to be related to the usage of HTTPs and SSL certificate - maybe also using the reverse proxy nginx as SSL endpoint. 
I tried with running the agent directly on the rancher server IP with its 8080 port and it worked then.
For our current setup, this solution might be ok, but nevertheless, the HTTPs approach should work too.

**Comment by superseb** [comment]
Can you retry with the latest version and file a new issue when you encounter it again? We have improved logging on the agent to track down what is causing issues.
