### ISSUE TITLE
[question] What is rancher/cleanup-1-1 image?

### ISSUE THREAD

**Issue by ket4yii** [rancher/rancher#9138]
Just a simple question. Does it make any sense to use it for cleanup rancher meta or internal cleanup in rancher-server container is based on it and there isn't any diffrence between them?

**Comment by aemneina** [comment]
its meant to clean up data marked as removed in the rancher database. Meant to be executed before upgrading from rancher 1.1 -> 1.2+.

**Comment by ket4yii** [comment]
@aemneina Ok, thank you!
