### ISSUE TITLE
Change VXLAN programming logic

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#9140]
On a fresh start of VXLAN, when we read from metadata, compare with an empty in-memory state and calculate the difference/delta, everything becomes an ADD. We program all the entries and update the in-memory state. On the next metadata update, we use the in-memory state again and the logic goes on.

When needs to be done is to not use any in-memory state, but read the actual entries to build the current state to calculate the delta for programming entries.

**Comment by niusmallnan** [comment]
Steps to Reproduce:
1. Change the vxlan docker-compose similar to ipsec one. https://github.com/leodotcloud/test-vxlan-catalog
2. Restart vxlan-router container, then you can see the error logs.

**Comment by niusmallnan** [comment]
Performence test between containers on AWS:
```
$ iperf3 -c 10.42.79.74 -P 10
......
......
[SUM]   0.00-10.00  sec   648 MBytes   543 Mbits/sec  2017             sender
[SUM]   0.00-10.00  sec   645 MBytes   541 Mbits/sec                  receiver
```

**Comment by sangeethah** [comment]
Tested with rancher server version-v1.6.6-rc2 and cni driver - rancher/net:v0.11.4.
Automated validation runs reports success except for the known failures relating to timing issues.
