### ISSUE TITLE
Use full screen size

### ISSUE THREAD

**Issue by CodingSpiderFox** [rancher/rancher#9142]
Hello,

I am using a screen resolution of 1920x1080 and my browser window is maximized (Google Chrome)

I have only two hosts but the available space on the screen is not used, thus I can't read what's written in the red box:

![image](https://user-images.githubusercontent.com/25173078/27458354-dc9af82e-57a8-11e7-9e00-6c15cada8193.png)
"Storage ... Pulli...", also the container names.

As long as there aren't so many nodes, more horizontal space should be acquired by the hosts' columns so I can see more content.

**Comment by vincent99** [comment]
No.  The corollary is one host 1900px wide and you can't tell what row anything is on anymore.  2.0 has (will have) a different list view option you may like better
