### ISSUE TITLE
The IRC channel is not useful

### ISSUE THREAD

**Issue by skullydazed** [rancher/rancher#9145]
In a lot of places (EG, /README.md) Rancher points to FreeNode's #rancher channel as a place to talk with people who know Rancher. However, it seems that the channel has basically been abandoned as evidenced by the chat logs:

https://botbot.me/freenode/rancher

Until I decided to try out Slack I had given up the rancher community as dead or uncontactable. I am glad that I was in error, but now I wonder how many other people reached the same conclusion but didn't go check out slack.

It feels like a hard thing to ask people to go back to IRC, after all who has time for both? Given that the community seems to have settled on slack as The Place To Be could the documentation be updated to reflect reality?

**Comment by junkiebev** [comment]
This is a feature for 1.7 I'm pretty sure

**Comment by aemneina** [comment]
Not sure if rancher-users slack is documented... might be a good idea to add it there. Could make it into 1.6.x

**Comment by vincent99** [comment]
...

`The topic for #rancher is: Rancher, RancherOS, and Rancher Labs in general http://rancher.com http://github.com/rancher https://slack.rancher.io https://botbot.me/freenode/rancher`

![image](https://user-images.githubusercontent.com/753917/27608453-7c028bf2-5b3c-11e7-8903-bcbb720cb590.png)

![image](https://user-images.githubusercontent.com/753917/27609173-e4dd6244-5b3e-11e7-9f2f-cc27ca964e7d.png)

**Comment by vincent99** [comment]
![image](https://user-images.githubusercontent.com/753917/27650577-338b2ce0-5bea-11e7-808c-cc08feb6d4ad.png)
