### ISSUE TITLE
kubernetes install fails to start

### ISSUE THREAD

**Issue by hiucimon** [rancher/rancher#9146]
**Rancher versions:**
rancher/server: v1.6.2
rancher/agent: same

**Infrastructure Stack versions:**
healthcheck:same
ipsec:same
network-services:same
scheduler:same
kubernetes (if applicable):v1.5.4-rancher1-4

**Docker version: (`docker version`,`docker info` preferred)** 1.12.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)** RHEL 7.3

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**SINGLE

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**
Install RHEL in AWS, Install Docker, Install Rancher, Enable standalone security, Add one host(custom), Install Kubernetes from Catelog with all defaults

**Results:**
kubectl, rancher-ingress-controller, and rancher-kubernetes-agent all loop from initiallizing to unhealthy forever. The only errors I see in the logs are:

01:43:31 PM	ERROR	service.update.wait.exception	Expected state running but got stopped	 
01:43:31 PM	ERROR	service.update.exception	Expected state running but got stopped

This is my first exposure to Rancher, so not even sure where to get logs.

**Comment by superseb** [comment]
Things to check here are logs of containers in service `kubernetes/kubernetes`, `kubernetes/kubelet`. If this is not showing any relevant, you can check `kubernetes/controller-manager` as well. Please report back if we can help you with the setup.
