### ISSUE TITLE
Kubernetes outgoing SSL connections not working

### ISSUE THREAD

**Issue by dweidenfeld** [rancher/rancher#9149]
Hi,

I've setup a latest rancher server with Kubernetes on my contabo server.
If I am running a `curl --head https://accounts.google.com/` I get an SSL error. 
If I am running the same container in docker-compose everything works.

So it must be a problem with rancher/kubernetes because it will not pick up the public SSL certificates..

How do I solve the problem?

**Comment by aemneina** [comment]
Can you execute the following: `openssl s_client -showcerts -connect accounts.google.com:443` from your container?

**Comment by dweidenfeld** [comment]
Sorry. Problem is already solved. Mounted /etc/ssl in the container.
