### ISSUE TITLE
volumes_from in rancher

### ISSUE THREAD

**Issue by EugenMayer** [rancher/rancher#9152]
HINT: changed the issue after i found out volumes_from is supported and the issue was just a service-name having an underscore.

Reading in some issues about :ro support in volumes_from, that volumes_from might be removed due to the deprecation in v3. I would really please you to not do that, please see my comment here https://github.com/docker/compose/issues/4693#issuecomment-310892561 )

I think volumes_from in that particular scenario is absolutely critical and until either 3.3 introduced some options for `volumes` to adopt the anon-volume way somehow, i cannot think about anything else.

Specifically in how rancher does stack upgrade ( pull / down / up ) anon volumes are very important here

**Comment by berisberis** [comment]
Using a sidekick to contain a volume of only the app code and not all the infrastructure, lets you upgrade a service really fast and separate the infra from the app. For example, having various containers for a php, nginx, php-worker and CLI sharing a volume with only the app code is the most efficient way to build this kind of projects. Even letting you separate infra code from the repo of the app and triggering an docker image build on push on both repos. 
A Docker image using FROM busybox and adding the app code, thats it.
I don't like to "Dockerize" Apps merging in the image all the infra with the app code, its slow on ci build times and any change to infra has to test the whole app in ci.
Is there going to be any to do this in 2.0?

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
