### ISSUE TITLE
Layer-3 routed networking support in Cattle

### ISSUE THREAD

**Issue by niusmallnan** [rancher/rancher#9153]
It‘s very similar to this. https://coreos.com/flannel/docs/latest/aws-vpc-backend.html

![image](https://user-images.githubusercontent.com/998984/28244977-95dd9a8a-6a2d-11e7-9072-de3513854a80.png)

For network-manager:
1. Compatible with masqrade rules to ensure that the container can access the external network.
2. Generate CNI configuration for host-subnet

For CNI library:
Continue to use the rancher-cni-bridge, but bridgeSubnet needs to be set according to host subnet.

For IPAM:
No need to use rancher-ipam, host-local-ipam is required in this case.
https://github.com/niusmallnan/rancher-host-local-ipam

For scheduler:
Change the scheduler to make sure containers with "retain_ip: true" always get restarted on the same host.
But can not get retainer_ip information in the scheduler. Tried some way and found that it was not too reasonable. I think that the best way is to make some changes in cattle.
When triggering the event scheduler.prioritize, scheduler can get the context data. If there is a retain_ip flag, it is best to include the IP information in the context data. The container that was originally created does not need to contain it, and the upgraded container needs to contain it. Then I can use IP information to filter on which host the container should be scheduled for.

How to use：
1. Add a catalog repo：https://github.com/niusmallnan/host-subnet-catalog
2. Create a new environment with this networking
3. Add host with label "`io.rancher.network.per_host_subnet.subnet=xx.xx.xx.xx/xx`"
4. Set the CIDR of the host label settings to the VPC routing table, note the settings for the security group

**Comment by leodotcloud** [comment]
@niusmallnan can you please update PR:79 to get this issue resolved?

**Comment by niusmallnan** [comment]
@leodotcloud 
I have updated, please recheck.

**Comment by yasker** [comment]
Catalog updated at: https://github.com/rancher/rancher-catalog/pull/940

**Comment by kingsd041** [comment]
**Tested with rancher-server version- v1.6-development with rancher/net:v0.13.0**
**Type/provider of hosts: AWS**
**Problem**

1. Requested IP is not supported.
2. Retain IP is not supported.
3. Readme write error
![image](https://user-images.githubusercontent.com/19684717/31340813-fa596624-accc-11e7-9ac9-a3ae333efdfd.png)

4. Load Balancer failed to start
```
level=fatal msg="Error reading self service metadata: Error 404 accessing /self/service path
```
5. Remove per-host-network container, host routing information is not cleared.
![image](https://user-images.githubusercontent.com/19684717/31341136-2d4dea18-acce-11e7-88bf-d3c3c6f3467c.png)

**Comment by leodotcloud** [comment]
@kingsd041 Minor suggestion about the process, I see the QA team here files new issues during testing and point them to the original issue instead of reopening. [There is nothing wrong with your approach, it's just what everyone is used to here]

**Comment by yasker** [comment]
@kingsd041 It depends on you. If you think it's easier for tracking some major issues separately, you can open a new issue for it and link the current issue. You also can keep the small issues in the same issue.

**Comment by yasker** [comment]
@kingsd041 is there anything else we're waiting for except for #10074 ? I saw you pointed out a typo, have we fixed that yet?

**Comment by kingsd041** [comment]
@yasker  Typo and https://github.com/rancher/rancher/issues/10074 have been fixed.
But I can not close the issue Because https://github.com/rancher/rancher/issues/9978 hasn't been tested yet

**Comment by kingsd041** [comment]
@yasker  Sorry, I just clicked the wrong button.

**Comment by kingsd041** [comment]
Issue https://github.com/rancher/rancher/issues/9978 has been tested.
Close the issue.
