### ISSUE TITLE
kubectl port-forward doesn't work with lower cased "Connection: upgrade" header

### ISSUE THREAD

**Issue by IlyaSemenov** [rancher/rancher#9155]
**Rancher versions:**
rancher/server: 1.6.2
rancher/agent: 1.2.2

**Infrastructure Stack versions:**
Not sure how do I get them? This is a completely fresh install of 1.6.2, fully wiped internal database, so the infrastructure is as per 1.6.2 defaults. No external catalogs.

**Docker version: (`docker version`,`docker info` preferred)** Server: 17.03.0-ce, Host: 1.12.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)** Server: Ubuntu 16.04.2 LTS, Host: Debian 8 jessie, 4.4.67-1-pve

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** Bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)** rancher server on a separate node (with internal DB), rancher agent on its own node.

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)** Kubernetes

**Steps to Reproduce:**

Expose Rancher server at <https://rancher.xxxxx.com> via [jwilder/nginx-proxy](https://github.com/jwilder/nginx-proxy) and [JrCs/docker-letsencrypt-nginx-proxy-companion](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion) for https.

On an external machine, configure kubectl then run `kubectl port-forward tiller-deploy-3991468440-g4sl7 --namespace=kube-system 5555:44135 --v=9` then run `curl localhost:5555`, you will get a time out. Or simply run `helm version` (which relies on port-forward to tiller), it will not be able to retrieve the tiller version.

Now, docker exec into the proxy container, edit `/etc/nginx/conf.d/default` and in this block:

```
# If we receive Upgrade, set Connection to "upgrade"; otherwise, delete any
# Connection header that may have been passed to this server
map $http_upgrade $proxy_connection {
  default upgrade;
  '' close;
}
```

replace `default upgrade;` with `default Upgrade;`. Run `killall -1 nginx`.

`kubectl port-forward` will start working. Replace "Upgrade" with "upgrade" back, it will stop working.

**Expected behaviour:**

"Connection: upgrade" header must be treated in case-insensitive manner, as specified by [RFC7230](https://tools.ietf.org/html/rfc7230#section-6.1), section 6.1: "Connection options are case-insensitive."

I'm not sure where is the fault, in Rancher or in kube-apiserver (or even somewhere deeper). If it's not in Rancher, please specifically capitalize the header until it's fixed in upstream.

**Additional details:**

This is what I gathered with tcpdump on port 80 in a docker container that runs kube-apiserver:

```
POST /api/v1/namespaces/kube-system/pods/tiller-deploy-3991468440-g4sl7/portforward HTTP/1.1
Host: rancher.xxxxxx.com
User-Agent: kubectl/v1.6.4 (darwin/amd64) kubernetes/d6f4332
Content-Length: 0
Authorization: Basic xxxxxx
Connection: upgrade
Upgrade: SPDY/3.1
X-Forwarded-For: 10.0.2.140, 172.17.0.5
X-Forwarded-Port: 443
X-Forwarded-Proto: https
X-Forwarded-Ssl: on
X-Real-Ip: 10.0.2.140
X-Stream-Protocol-Version: portforward.k8s.io
Accept-Encoding: gzip

HTTP/1.1 101 Switching Protocols
Connection: Upgrade
Upgrade: SPDY/3.1
X-Stream-Protocol-Version: portforward.k8s.io
Date: Mon, 26 Jun 2017 10:52:18 GMT
```

It *reports* that it worked, although it didn't. It only starts to work when it sees "Connection: Upgrade" (capitalized) here.

**Gratitudes:**

I was thinking I would never find where was the problem, but then I discovered that it was already reported here: https://forums.rancher.com/t/timeout-on-kubectl-exec-on-with-nginx-ssl-termination/3916/3

I decided to report this to GitHub because I believe [jwilder/nginx-proxy](https://github.com/jwilder/nginx-proxy) is a quite common setup (over 5K GitHub stars) and it's very hard to trace to the cause (there's no errors reported anywhere).

**Comment by superseb** [comment]
How did you configure your nginx? This was merged (https://github.com/rancher/rancher.github.io/commit/4185a647fd82091905d32e2f9880de939b97f8aa) 6 days ago where it went from lowercase to uppercase. (along with only upgrading when upstream was set).

**Comment by IlyaSemenov** [comment]
As I explained above, I am running [jwilder/nginx-proxy](https://github.com/jwilder/nginx-proxy), with the default setup. This is a Docker container (widely used by other people), I did not configure it, it comes pre-configured. I provisioned it with Terraform ([nginx_proxy.tf](https://gist.github.com/IlyaSemenov/dffde5535a752405232e2f03e3aecb0c)) but it's the same as if I ran it manually.

This is the specific nginx config file that was generated: [default.conf](https://gist.github.com/IlyaSemenov/db89ee114d791e5ca1996be137029b44) - and yes, it has lower-case "upgrade". This is because it is lower-case in the config template: [nginx.tmpl](https://github.com/jwilder/nginx-proxy/blob/master/nginx.tmpl#L37).

Does that answer the question?

It wouldn't make sense to create an issue for jwilder/nginx-proxy, because there is nothing wrong in lower-case "upgrade" header [according to standards](https://tools.ietf.org/html/rfc7230#section-6.1). It's not the proxy issue, it's either Rancher or kube-apiserver issue.

**Comment by IlyaSemenov** [comment]
From what I understand, https://github.com/rancher/rancher.github.io/commit/4185a647fd82091905d32e2f9880de939b97f8aa is only a documentation improve, so it's not really a fix. If there's not enough resources to trace the problem, I think at the very least the documentation must be amended with something like:

> **It is utterly important that Upgrade header is sent properly capitalized.** If you are using an external proxy and experience problems with port forwarding, please make sure it's "Upgrade" and not "upgrade".

After all, it's not the first time (https://github.com/rancher/rancher/issues/4278) when there is a problem with proxy and incompatible header capitalization.

**Comment by vincent99** [comment]
And that was (also) a case where third party software was handling it wrong, reported, and patched.  So you should put in a bug for k8s, and we've already updated the docs to avoid suggesting something that doesn't work, but we're not going to put in a hack to rewrite the header.

**Comment by krishofmans** [comment]
I was using rancher behind a kubernetes cluster with the stable/nginx-ingress.
`helm install stable/nginx-ingress \
--name=ing-impl --namespace=custom-system \
--set controller.hostNetwork=true,controller.kind=DaemonSet \
--set controller.stats.enabled=true \
--set controller.metrics.enabled=true`

This has a nginx.tmpl that contains: 
`    map $http_upgrade $connection_upgrade {
        default          upgrade;
        ''               close;
    }
`

I had to change the template to:
 `    map $http_upgrade $connection_upgrade {
        default          upgrade;
        ''               close;
    }
`

Otherwise kubectl exec, portforward, helm commands failed. Lets hope other people don't waste as much time on this issue as I have.

**Comment by los93sol** [comment]
> I was using rancher behind a kubernetes cluster with the stable/nginx-ingress. `helm install stable/nginx-ingress \ --name=ing-impl --namespace=custom-system \ --set controller.hostNetwork=true,controller.kind=DaemonSet \ --set controller.stats.enabled=true \ --set controller.metrics.enabled=true`
> 
> This has a nginx.tmpl that contains: ` map $http_upgrade $connection_upgrade { default upgrade; '' close; }`
> 
> I had to change the template to: ` map $http_upgrade $connection_upgrade { default Upgrade; '' close; }`
> 
> Otherwise kubectl exec, portforward, helm commands failed. Lets hope other people don't waste as much time on this issue as I have.

I realize this is quite old, but I'm actually struggling with this right now, doesn't seem to matter what I do, kubectl with ingress-nginx terminating for the kube-apiserver just kills the connection after about 1 minute.  Do you have any other info on the issue and how to fix it?

**Comment by krishofmans** [comment]
> > I was using rancher behind a kubernetes cluster with the stable/nginx-ingress. `helm install stable/nginx-ingress \ --name=ing-impl --namespace=custom-system \ --set controller.hostNetwork=true,controller.kind=DaemonSet \ --set controller.stats.enabled=true \ --set controller.metrics.enabled=true`
> > This has a nginx.tmpl that contains: ` map $http_upgrade $connection_upgrade { default upgrade; '' close; }`
> > I had to change the template to: ` map $http_upgrade $connection_upgrade { default Upgrade; '' close; }`
> > Otherwise kubectl exec, portforward, helm commands failed. Lets hope other people don't waste as much time on this issue as I have.
> 
> I realize this is quite old, but I'm actually struggling with this right now, doesn't seem to matter what I do, kubectl with ingress-nginx terminating for the kube-apiserver just kills the connection after about 1 minute. Do you have any other info on the issue and how to fix it?

Hi, if I remember correctly, the websocket for me never worked at all, not shutting down after 1 minute. This sounds more like a timeout or lack of keep-alive and not related to this header case sensitivity.

**Comment by los93sol** [comment]
Thanks, I ended up chasing it down to an asymmetric routing issue and got it resolved
