### ISSUE TITLE
the removed stacks are still listed on UI

### ISSUE THREAD

**Issue by shaoyangyu** [rancher/rancher#9156]
*Describe your issue here*
Hi, 

I used commands:rancher up -s stackname -d and rancher rm stackname with same stackname several times.
everything looks fine, except when I relogin in ,I found all the removed stacks are still listed on UI and there is no way to clear them. Any idea for this?

---
| Useful | Info |
| :-- | :-- |
|Versions|Ra
<img width="1428" alt="rancher ui 2" src="https://user-images.githubusercontent.com/1483923/27538932-b55f1cb4-5abd-11e7-88d0-3eac970ef7a4.png">
<img width="1292" alt="rancher ui" src="https://user-images.githubusercontent.com/1483923/27538933-b5630626-5abd-11e7-954a-2dd1c8e76c6a.png">

ncher `v1.6.2` Cattle: `v0.181.4` UI: `v1.6.5` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`stacks.index`|

**Comment by aemneina** [comment]
can you open developer tools and refresh the page? Are there errors logged in the networking tab?

**Comment by shaoyangyu** [comment]
Hi Aemneina
Thanks for response.  I created the env with vm on my laptops, the problem happened after I resumed the vm. But I  did not see it happen again in other vms.  For now , the VM has been deleted, sorry I can't recreate the problem and provide more details .

**Comment by aemneina** [comment]
No problem, i'll close the issue. if you hit it again feel free to reopen. I suspect the vm's ip might have changed and the browser could have been pointing to the old location.
