### ISSUE TITLE
Upgrading Service Stack Referenced as External Service Causes Links to Never Work Again

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#9159]
## Problem

If you have Stack A referenced by Stack B as external service link so that they get DNS entries in Stack B. If you update any of the services in Stack A, then all connections in Stack B stop working. It takes a full re-deploy or update to Stack B to re-associate the services.

## Expected

Rancher should ensure all external links are up-to-date when a stack being referenced by an external link is update.

## Actual 

It seems that when a stack is update Rancher does not update the external links which causes multiple problems when you have multiple stacks depending on each other.

## Comments 

This is a pretty big bug. It basically makes it so that you break your entire environment if you rely on linking services together. 

## Use Case

I run a NSQd stack, a consul stack, and then multiple product stacks all of which talk to each other. If I run an update to the NSQ stack, I have to then force a redeploy all on all my product stacks because the external links stop working.

**Comment by ekristen** [comment]
Any idea if there is a work around for this besides having to update every stack?

**Comment by vincent99** [comment]
What does "stop working" mean?  The name no longer resolves?  Resolves to the wrong address? Resolves to the right address but doesn't connect anymore?

**Comment by ekristen** [comment]
@vincent99 I'll take the hit on this one, I'm unable to duplicate this now.  I could have been wrong to begin with or perhaps the recent upgrade I did fix the underlying issue. I'll keep a close eye on things.
