### ISSUE TITLE
Restricted user is allowed to upgrade services that have privileged/capadd fields set which results in upgraded container not having both of these flags set.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#9160]
rancher/server: v1.6.3-rc2

Steps to reproduce the problem:
As a regular user , create a service with privileged/capadd fields set. 
Containers of the service gets created with these fields set.

As a restricted user , upgrade this service. Once the service is upgraded , the upgraded containers do not have  privileged/capadd fields set anymore.

**Comment by sangeethah** [comment]
Another related question , Should restricted users be prevented from being able to set CapDrop flag when he tries to upgrade an existing service ?

**Comment by cjellick** [comment]
I don't think we need to restrict capDrop. Our goal is to prevent gaining _more_ access to the host. You can't do that by using capDrop

**Comment by cjellick** [comment]
We're rolling back this change. Behavior of restricted user will continue as it was in 1.6.2 regarding privileged/cappAdd (they can still set it)

**Comment by cjellick** [comment]
I'm going to close this issue. The original change that caused this was rolled back and I don't think we are going to implement it at this time.
