### ISSUE TITLE
Change k8s image in rancher from debian to ubuntu base

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#9168]
**Rancher versions:**
rancher/server: 1.6.2
kubernetes (if applicable): 1.5.4

What triggered this was a change to self signed certificates. Seems debian is ignoring multiple/unordered certificates in its trusted certs file. This caused the k8s api service to fail to connect back to the rancher server properly. @ibuildthecloud suggested we change the base image, to ubuntu, where it appears to work properly.

**Comment by deniseschannon** [comment]
The images have all been updated to `agent-base` which is ubuntu-based, and these changes have been updated in k8s 1.6.

**Comment by aemneina** [comment]
awesome!
