### ISSUE TITLE
When CUD of hosts is restricted for a member, host addition should error out as "action not allowed" and deactivate/ evacuate/edit hosts and download machine config should not be allowed

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#9170]
**Rancher versions:**
rancher/server:v1.6.3-rc2
rancher/agent:rancher/agent:v1.2.3-rc2

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**Ubuntu

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**AWS/GCE

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**Single node

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**Cattle

**Steps to Reproduce:**
1. Create a member-auth.json file with read only permissions set
2. Create a rancher server using the below command: 
docker run -d -p 8080:8080 -v /local/path/to/member-auth.json:/usr/share/cattle/war/schema/member-auth/member-auth.json.d/overrides/member-auth.json rancher/server:v1.6.3-rc2
3. Enable auth using git-hub
4. Create another environment and add another github user as a member
5. Login as a member and add a host

Host addition fails with " Error: No machine name specified". It should fail with  ```action not allowed for a member``` or some appropriate error

<img width="541" alt="screen shot 2017-06-26 at 6 51 34 pm" src="https://user-images.githubusercontent.com/18536626/27567444-9a86e5ec-5aa0-11e7-9376-75cc01e3df2c.png">

**Comment by cjellick** [comment]
@soumyalj can you provide the contents of the auth.json file(s) that you used?

**Comment by sangeethah** [comment]
@cjellick , contents of auth.json file

```
root@sangeetest1:~# cat member-auth.json 
{
    "authorize" : {
        "machine": "r",
        "machine.authCertificateAuthority": "r",
        "machine.authKey": "r",
        "machine.dockerVersion": "r",
        "machine.driver": "r",
        "machine.engineEnv": "r",
        "machine.engineInsecureRegistry": "r",
        "machine.engineInstallUrl": "r",
        "machine.engineLabel": "r",
        "machine.engineOpt": "r",
        "machine.engineRegistryMirror": "r",
        "machine.engineStorageDriver": "r",
        "machine.externalId": "r",
        "machine.labels": "r",
        "machine.name": "r",

        "host" : "r",
        "host.agentState" : "r",
        "host.agentId" : "r",
        "host.computeTotal" : "r",
        "host.hostname" : "r",
        "host.info" : "r",
        "host.physicalHostId" : "r",
        "host.zoneId" : "r",
        "host.labels" : "r",
        "host.publicEndpoints" : "r",
        "host.agentIpAddress" : "r",
        "host.instanceIds" : "r",
        "host.localStorageMb" : "r",
        "host.memory" : "r",
        "host.milliCpu" : "r",
        "host.stackId" : "r",
        "host.hostTemplateId" : "r",

        "end" : ""
    }
}
```

**Comment by sangeethah** [comment]
@cjellick , When a member’s access is restricted to read only for host (by overrriding member-auth.json) , user is allowed to deactivate/ evacuate/edit hosts and download machine config.

These actions should also be restricted on the hosts.

**Comment by cjellick** [comment]
We are changing the implementation to be based off a settng, not overriding the auth file

**Comment by cjellick** [comment]
To @alena1108 for review

**Comment by sangeethah** [comment]
Tested with rancher-server version - v1.6.6-rc2.
Set modify.infrastructure.roles to not include roles: 
```member/v1-member``` 

As a member of the host , "Add account" option is presented to the user. When member attempts to add hosts , it fails with "Cannot create host"  as expected.

As a member of the host , deactivate/ evacuate/edit hosts and download machine config options are not presented to the user in UI.

When Attempting delete using API , API fails with:
```
"status": 403,
"code": "Forbidden",
"message": "Cannot delete host",
```
When Attempting to edit using API , API fails with:
```
"status": 403,
"code": "Forbidden",
"message": "Cannot update host",
```
