### ISSUE TITLE
Load balancer published ports missing from containers in HA setup 

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#9172]
This causes networking to not program host port rules correctly and thus for traffic to be dropped.

**Rancher versions:**
rancher/server: 1.6.2

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
cattle

**Steps to Reproduce:**
1. Create an HA setup
2. Create a load balancer
3. Check the ports for the load balancer container in metadata. Observe that the ports added originally are in metadata
4. After load balancer is created, add a port rule to it.
5. Look up the load balancer container in rancher-metadata, specifically its ports.

**Results:**
Expected:
Load balancer container's ports are always updated in metadata after a rule is added or removed

Actual:
After adding or removing the new port rule to the load balancer, the change may or may not be reflected in metadata. If the change isn't reflected in MD, then networking doesn't program the host iptables rules correctly and traffic is lost.

Note that if you add a port, once that port shows up in metadata, it will definitely continue to show up until you do something (like deploy another container) to cause metadata 

This only happens ocassionally. In a two host rancher-ha setup, I saw it like one out 20 or 30 times of adding/removing a port rule from the LB

**Comment by sangeethah** [comment]
Tested with v1.6.3-rc3 on a rancher-server HA setup with 3 hosts.
Created a Load Balancer with 1 port rule.
Then added more port rules ( 1 rule at a time multiple times). 
Every time a new port rule was added with a new source port , new port (along with existing source ports from the existing port rules)  are reflected in ``rancher-metadata/latest/containers/ports``.
Also LB is accessible using all the source ports.

**Comment by sangeethah** [comment]
Automated test case for validating the every time a new port is added for LB , Lb is 
 reachable with the new port added and all the existing ports - https://github.com/rancher/validation-tests/pull/333/f
