### ISSUE TITLE
does rancher support mysql group replication ?

### ISSUE THREAD

**Issue by Jamlee** [rancher/rancher#9173]
**Rancher versions:**
rancher/server: 1.5.0

i made a mysql group replication mutiple master cluster, and starting rancher server by using external database. but i get the error:
 
![719680713](https://user-images.githubusercontent.com/5196641/27571858-0cc90320-5b3b-11e7-97d8-0caa2fc5ae84.jpg)

checked the mysql doc, i found the requirement:
![785872604](https://user-images.githubusercontent.com/5196641/27571861-1154bbbe-5b3b-11e7-85fb-dadcdd077da4.jpg)

Sorry for the pic is not too clearfy!  DODES RANCHER HAVE TABLE WITH NO PRIMARY KEY?

**Comment by superseb** [comment]
Merging into https://github.com/rancher/rancher/issues/9329
