### ISSUE TITLE
Rancher UI cannot support to adjust the column width

### ISSUE THREAD

**Issue by YYSAM** [rancher/rancher#9174]
**Rancher versions:**
rancher/server:1.6.2
rancher/agent:1.2.2

**Steps to Reproduce:**
Open INFRASTRUCTURE -> HOSTS, select one hosts and open a new page.

**Results:**
The containers grid cannot adjust the column width, the container's name is hiding.
Please check the image below:
![default](https://user-images.githubusercontent.com/723900/27574780-407e2be6-5b4a-11e7-9d6f-20797c82d23a.png)

**Comment by vincent99** [comment]
We're not going to do resizable columns, but they are better laid out / 2 rows and no left sidebar in 2.0 so there is room to see more of them.
