### ISSUE TITLE
Rancher webhooks not support Aliyun docker hub

### ISSUE THREAD

**Issue by KevinMyDing** [rancher/rancher#9175]
Our company use Aliyun docker hub, it is auto tigger webhook and not support configuration parameter, can you support Aliyun docker hub webhook?

**Comment by cjellick** [comment]
Can be tested on v1.6-development as of the time/date of this comment

**Comment by kingsd041** [comment]
Tested with rancher-server version v1.16.3-rc3 with UI:1.6.24
Test passed.
