### ISSUE TITLE
Volume deactivate process stuck indefinitely

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#9178]
**Rancher versions:**
rancher/server: 1.6.2 issue most likely happened in ~1.5.8
rancher/agent: 1.2.2

**Docker version: (`docker version`,`docker info` preferred)**
1.12.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
CentOS 7.3

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS

**Steps to Reproduce:**
1. observed docker pull not working anymore (docker was being stubborn)
2. restarted docker
3. was able to pull again
... not sure if those above are related ...
4. noticed long running instance stop processes in UI
5. drilled down and noticed volume.deactivate to be the failing processes
6. manually fiddled with the volume fields in the db (_8(|)

**Results:**
At that point the instance.stops went forward without issue, knock on wood.

**Desired:**
Have some sort of timeout/retry on volume.deactivate

**Comment by galal-hussein** [comment]
Rancher server: v1.6.2 and v1.6.3-rc5
OS: RHEL 7.3

Steps:

- Started Rancher server with following docker-compose https://github.com/superseb/rancher-mariadb-networktest, which uses netem to simulate 3000ms delay to the DB container.
- Registered agents.
- Started multiple stacks each with one service that has local volume mounted.
- Scaled each service to 100 containers
- Deleted one service while its scaling, and deleted the other after it is scaled.

I couldn't reproduce the problem, i didn't see the volume.deactivate process stuck even with higher delays simulations, i can see services create/scaled/deleted normally.

**Comment by aemneina** [comment]
@cjellick I have logs for this on 1.6.2 if that helps.

**Comment by deniseschannon** [comment]
We added a fix in 1.6.3 but as we couldn't actively reproduce it, we've kept this open in case someone else hit it after our fix. 

If someone hits this issue in a version after Rancher v1.6.3, , please ping me and we'll investigate again.
