### ISSUE TITLE
Test Plan for RBAC via JSON files/settings

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#9179]
[Test Plan - RBAC with auth json files.xlsx](https://github.com/rancher/rancher/files/1106245/Test.Plan.-.RBAC.with.auth.json.files.xlsx)

https://github.com/rancher/rancher/issues/9017

**Comment by sangeethah** [comment]
@soumyalj , Need to add 1 test case relating to updating an existing "owner" to any other role which should be not be allowed.

**Comment by soumyalj** [comment]
Updated Test Plan
[Test Plan - RBAC with auth json files.xlsx](https://github.com/rancher/rancher/files/1107035/Test.Plan.-.RBAC.with.auth.json.files.xlsx)

**Comment by soumyalj** [comment]
Updated Test Plan
[Test Plan-RBAC with auth json files.xlsx](https://github.com/rancher/rancher/files/1125618/Test.Plan-RBAC.with.auth.json.files.xlsx)
