### ISSUE TITLE
Clone an existing container to a given service under a given environment

### ISSUE THREAD

**Issue by Nicofuma** [rancher/rancher#918]
Sometimes we run some containers directly from the host to test various configuration and when we have a right configuration we would like to copy directly the container (actually its configuration) to a service (so without having to rewrite it using the web interface).

An other use case could be to copy a container to an other service to use it as a base per example

**Comment by vincent99** [comment]
This makes sense as a compliment to the container clone action.  There are some parts of a container config that are ignored for a service, so there would need to be some checks/warnings if the container uses them.

**Comment by will-chan** [comment]
We need a "clone" services enhancement as well.
