### ISSUE TITLE
Kubernetes environment in unrecoverable state on start up after rancher server and hosts have been turned off for an extended period of time

### ISSUE THREAD

**Issue by JTarball** [rancher/rancher#9181]
**Rancher versions:**
rancher/server: v1.6.2

**Docker version: 1.12**

**Operating system and kernel: Ubuntu**

**Type/provider of hosts: AWS**

**Setup details: single node rancher internal DB**

**Environment Template: Kubernetes**

**Steps to Reproduce:**
- all aws hosts for rancher and kubernetes hosts
(note: I used an even number of kubernetes hosts)
- power off all hosts at the same time
- (wait for few days (probably dont need to do this*))
- power on all hosts at the same time
**Results:**
- The kubernetes UI doesnt sync with kubectl. UI shows namespaces which dont exist via kubectl on power up. Kube config username and password seem different. Seemed to possibly suggest two kubernetes environments? 
- kubernetes components constantly initialising - stopping etc never get to a stable state

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
