### ISSUE TITLE
rancher/external-dns:0.6.2 Does not support Rancher with Custom CA

### ISSUE THREAD

**Issue by wcgcoder** [rancher/rancher#9182]
**Rancher versions:**
rancher/server: v1.6.0
rancher/agent: v1.2.2

**Infrastructure Stack versions:**
healthcheck: v0.3.1
ipsec: v0.11.2
network-services: 0.2.0
scheduler: 0.5.1
kubernetes (if applicable): N/A

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**

1. Launch External DNS from Infrastructure Services into environment
2. Configure appropriately to connect to DNS
3. Launch

**Results:**
Container fails to start, giving error message:
```
6/27/2017 12:13:55 PMtime="2017-06-27T19:13:55Z" level=info msg="Starting Rancher External DNS service"
6/27/2017 12:13:55 PMtime="2017-06-27T19:13:55Z" level=fatal msg="Failed to configure cattle client: Get https://x.x.x/v1: x509: certificate signed by unknown authority"
6/27/2017 12:14:04 PMtime="2017-06-27T19:14:04Z" level=info msg="Starting Rancher External DNS service"
6/27/2017 12:14:04 PMtime="2017-06-27T19:14:04Z" level=fatal msg="Failed to configure cattle client: Get https://x.x.x/v1: x509: certificate signed by unknown authority"
```

**Expected Results**
Container should successfully connect to Rancher by first importing and updating the certificate trust store if a file is found on the host, here: `/var/lib/rancher/etc/ssl/ca.crt`

This would mimic the procedures required by the rancher-agent when using a Custom CA.

Thanks!

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
