### ISSUE TITLE
Script to retrieve the template versions of infra stacks and images/tags in those templates

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#9189]
The script Input should be the Rancher server version, e.g. `v1.6.2`

Minimum set of infra stacks to provide info:

healthcheck
network-services
ipsec
vxlan
scheduler
k8s

Potential Example Script Output: 
```
Rancher Server Version: v1.6.2

network-services:v0.2.1
  - rancher/network-manager:v0.7.1
  - rancher/metadata:v0.9.1
  - rancher/dns:v0.15.1
healthcheck:v0.x.x
  - rancher/healthcheck:v0.x.x
```

**Notes: **
Pick the default version in `config.yml` of each template

Branches in Catalog

Rancher v1.6.0 and below use `master` branch
Rancher v1.6.1-v1.6.xx use `v1.6-release` branch
Rancher v2.0 will use `v2.0-relesae` branch

**Comment by cjellick** [comment]
@deniseschannon could you effectively QA this by giving the script a try and seeing if it gives you what you want?

**Comment by deniseschannon** [comment]
Verified this is working as expected.
