### ISSUE TITLE
Script to update catalogs in current format to new format

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#9190]
In 2.0, the new format for catalog will accept the following changes:

1. Convert the folder number (`0`, `1`, `2`) to using the `version` for that catalog template, which is in the `rancher-compose.yml` file. 
2. Change `config.yml` to `template.yml`
  a. Update `version` in the old `config.yml` to `default_version` in the `template.yml`
3. Remove `catalog` from the `catalogIcon` names. Supported values are `icon.extension` and `icon-templatename.extension`
4. Move all services information from `rancher-compose.yml` and merge with contents in `docker-compose.yml`. 
  a. Rename file from `docker-compose.yml` to `compose.yml`.  Or `docker-compose.yml.tpl` to `compose.yml.tpl`. 
  b. Rename file from `rancher-compose.yml` to `template-version.yml`. Only remaining items should be whatever is in the `.catalog` section. Remove the `.catalog` from the top level in the file. 
5. Convert `projectURL` to `project_url`. 

We should create a tool that will easily take someone's existing catalog and convert to the new one.

**Comment by LLParse** [comment]
Tool is available for testing
https://github.com/LLParse/v2-catalog-transform/releases/tag/v0.0.1
