### ISSUE TITLE
rancher-agent is incompatible with runtime-spec v1.0 (docker 17.06)

### ISSUE THREAD

**Issue by iltish** [rancher/rancher#9192]
**Summary**
rancher-agent (1.2.2/1.2.3) is incompatible with [runtime-spec v1.0](https://github.com/opencontainers/runtime-spec/releases/download/v1.0.0-rc5/oci-runtime-spec-v1.0.0-rc5.html) and thus does not work on docker 17.06. More details - [moby/issues/33829](https://github.com/moby/moby/issues/33829)

**Rancher versions:**
rancher/server: 1.6.2
rancher/agent: 1.2.2/1.2.3

**Infrastructure Stack versions:**
N/A (does not start)

**Docker version: (`docker version`,`docker info` preferred)**
```
root@rancher-client:/home/it# docker version
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:23:31 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:19:04 2017
 OS/Arch:      linux/amd64
 Experimental: false
root@rancher-client:/home/it# cd ~
root@rancher-client:~# 
root@rancher-client:~# 
root@rancher-client:~# docker version
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:23:31 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:19:04 2017
 OS/Arch:      linux/amd64
 Experimental: false
root@rancher-client:~# docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 8
Server Version: 17.06.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 29
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.8.0-56-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.613GiB
Name: rancher-client
ID: IZLZ:4FUS:7N4I:M6OP:WN7K:QR7R:AQI3:WVVW:JGO2:HSNA:5KKL:TK7Y
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
root@rancher-client:~# cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
root@rancher-client:~# uname -r
4.8.0-56-generic

```
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
n1-standard-1 (1 vCPU, 3.75 GB memory) on GCE, but the same issues is reproducible with other environment configurations.

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
`docker run -d --restart=unless-stopped -p 80:8080 rancher/server`

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
N/A

**Steps to Reproduce:**
Launch rancher-agent on docker 17.06:
`docker run --rm --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.2.2 http://<host1>/v1/scripts/<key1>:<key2>:<key3>`

**Results:**
```
# docker ps
CONTAINER ID        IMAGE                  COMMAND             CREATED              STATUS                          PORTS               NAMES
14cabd80df8f        rancher/agent:v1.2.2   "/run.sh run"       About a minute ago   Restarting (1) 10 seconds ago                       rancher-agent
# docker logs rancher-agent
Found container ID: 011c0f599e468b2c4ef944f532ba1c3c5d20da4dbeb2a6203ffb522a42955d2e
Checking root: /host/run/runc
Checking file: 011c0f599e468b2c4ef944f532ba1c3c5d20da4dbeb2a6203ffb522a42955d2e
Found state.json: 011c0f599e468b2c4ef944f532ba1c3c5d20da4dbeb2a6203ffb522a42955d2e
time="2017-06-26T17:42:04Z" level=fatal msg="json: cannot unmarshal object into Go value of type []string" 
Found container ID: 151dddfb48cdd03f6fa65c948851b6203380e0c32da79733ccfb4f7807d64406
Checking root: /host/run/runc
Checking file: 14cabd80df8fc70773dbb12ca20e8d39d4bf61e1d28b08699106a0513562ae03
Checking file: 151dddfb48cdd03f6fa65c948851b6203380e0c32da79733ccfb4f7807d64406
Found state.json: 151dddfb48cdd03f6fa65c948851b6203380e0c32da79733ccfb4f7807d64406
time="2017-06-26T17:42:05Z" level=fatal msg="json: cannot unmarshal object into Go value of type []string"
...
```

**Comment by house-md** [comment]
+1 we have the same problem, our server admin did update on server along with docker to 17.06.0-ce and rancher-agent keeps restarting with the same error.

**Comment by superseb** [comment]
I just want to note that we keep a list of supported versions (where we run tests on) here: http://rancher.com/docs/rancher/v1.6/en/hosts/#supported-docker-versions

Of course, we will make sure that we support running on recent versions of Docker.

**Comment by alexishida** [comment]
+1 we have the same problem!

level=fatal msg="json: cannot unmarshal object into Go value of type []string"
...

**Comment by ibuildthecloud** [comment]
Will looking this, thanks!

**Comment by deniseschannon** [comment]
https://github.com/rancher/rancher/commit/d31e47eae080add5be493a287ce87dc47bb778bd

**Comment by galal-hussein** [comment]
Rancher Server: 1.6.3-rc4
Rancher Agent: v1.2.4-rc1
Docker Version: 17.06.0-ce
OS: Ubuntu 16.04

Rancher Agents started successfully without errors and the infrastructure stack containers started as well.

**Comment by alexandrst88** [comment]
@iltish you docker version is not capable with rancher agent version:
check this doc for supported versions: http://rancher.com/docs/rancher/v1.5/en/hosts/#supported-docker-versions

**Comment by eskogh** [comment]
How can I upgrade just the rancher/agent when I'm not able to manage the docker host from Rancher?

**Comment by cjellick** [comment]
Upgrading you rancher/server containers should be enough. When you do that, we force new versions of the rancher agent to be deployed.
And here's the latest version of the doc that @alexandrst88 referenced: http://rancher.com/docs/rancher/latest/en/hosts/

**Comment by eskogh** [comment]
Rancher is upgraded on the Rancher-server, two of our cluster is running Docker 1.12.6 and are connected to Rancher and got a new version of rancher/agent (v1.2.5). Two other cluster have upgraded Docker versions (17.06.1-ce and 17.06.2-ce) and have rancher/agent v1.2.2 but both cluster are shown as Disconnected in Rancher and therefore Rancher is not able to push out a newer version of rancher/agent and v1.2.2 is not supported with Docker 17.06.x.

I want update the rancher/agent on our discconected hosts so they can be Connected to rancher. My second option is to rollback to docker.io 1.12.6 so it been Connected to Rancher and it automatically push out a newer version of rancher/agent, then i can upgrade to docker-ce 17.06.2 again, but I'm sure there's a easier solution out there..

**Comment by cjellick** [comment]
Ah, you can just rerun the registration command for those hosts. Since rancher/server is upgrade, it'll have the proper rancher/agent version in the command.

Get the updated command from the add host page and the run it again on the disconnected nodes.
