### ISSUE TITLE
 Aliyun Block Storage support in Rancher Storage

### ISSUE THREAD

**Issue by thxCode** [rancher/rancher#9194]
Prepare!

**Comment by hongxiaolu** [comment]
Test passed！

**Comment by zionwu** [comment]
https://github.com/thxCode/storage/tree/aliyun-bs

**Comment by thxCode** [comment]
WIP on [Here](https://github.com/thxCode/rancher-catalog/tree/aliyun-bs). I have already pulled an image on [Docker Hub](https://hub.docker.com/r/maiwj/rancher-storage-abs/). 

Prepare for testing on Aliyun  and cooperating with @hongxiaolu.

**Comment by hongxiaolu** [comment]
Test passed！

**Comment by nayang777** [comment]
@thxCode Please submit PR. thx!

**Comment by thxCode** [comment]
@nayang777 , the PR of rancher/storage on [here](https://github.com/rancher/storage/pull/65) and the PR of rancher/rancher-catalog on [here](https://github.com/rancher/rancher-catalog/pull/836).

**Comment by nayang777** [comment]
https://github.com/rancher/storage/pull/65
https://github.com/rancher/rancher-catalog/pull/836

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
