### ISSUE TITLE
modify default Environment name “Forbidden”

### ISSUE THREAD

**Issue by chenchanglei** [rancher/rancher#9199]
*Describe your issue here*

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.2` Cattle: `v0.181.4` UI: `v1.6.5` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`settings.projects.detail`|

**Comment by tfiduccia** [comment]
@chenchanglei - I wasn't sure exactly what you are trying to say, but if you want the "Default" environment to be named "Forbidden" you can:
1.  Go to Manage Environments
2.  Edit Default Environment
3.  Change the name and save

If you want us to change "Default" to "Forbidden" every time we create that first environment, this would not make sense for us.  It's not a "Forbidden" environment and can be used by anyone that has access.  I'm going to close this.  Please reopen if this did not answer your question.
