### ISSUE TITLE
rancher-nfs timeout with nfsv4 callbacks to a nfs server inside the rancher managed network

### ISSUE THREAD

**Issue by mitcdh** [rancher/rancher#9203]
**Rancher versions:**
rancher/server: v1.6.2
rancher/agent: v1.2.2

**Infrastructure Stack versions:**
rancher/healthcheck: v0.3.1
ipsec: v0.1.0
network-services: v0.2.1
rancher/scheduler: v0.8.0
rancher/storage-nfs: v0.8.3

**Docker version: (`docker version`,`docker info` preferred)**
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 11:02:43 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 11:02:43 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

4.10.8-docker-1 (scaleway image)

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Scaleway, VPS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher, internal db, three node cluster

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
cattle

**Steps to Reproduce:**
1. Deploy a NFSv4 server (supporting callbacks) as a container within a rancher managed network spanning more than a single host, I used my fork of janeczku's docker-nfs-ganesha updated to Ganesha 2.5: [mitcdh/docker-nfs-ganesha](https://github.com/mitcdh/docker-nfs-ganesha)
2. Deploy rancher-nfs using the NFS servers rancher.internal name as NFS_SERVER.
3. Create two containers mounting volumes on different cluster hosts.

**Results:**
The first container will successfully start, the second container will error as the nfs-service on the second cluster host will time out at the point of running: `nsenter -t $PID -n mount -o ,nfsvers=4 $SERVER://$MOUNT /var/lib/rancher/volumes/rancher-nfs/$MOUNT`

````
30/06/2017 3:09:59 pm+ cmd='nsenter -t 13209 -n mount -o ,nfsvers=4 ganesha.nfs.rancher.internal://auth-config /var/lib/rancher/volumes/rancher-nfs/auth-config'
30/06/2017 3:09:59 pm++ nsenter -t 13209 -n mount -o ,nfsvers=4 ganesha.nfs.rancher.internal://auth-config /var/lib/rancher/volumes/rancher-nfs/auth-config
30/06/2017 3:15:07 pm+ error='mount.nfs: Connection timed out'
30/06/2017 3:15:07 pm+ '[' 32 -ne 0 ']'
````

This appears to be because the NFSv4 mount command is automatically evaluating the clientaddr as 10.42.0.1 for all instances of nfs-service in the cluster, the first node is able to establish the callback delegation channel, and all other nodes timeout while mounting.

Example from adding -vvv to the failed mount command:

    mount.nfs: trying text-based options 'nfsvers=4,addr=10.42.56.241,clientaddr=10.42.0.1'

Manually re-running the mount command on the nfs-service container or modifying the rancher-nfs script to specify the individual nfs-service containers managed network IP address allows mounting on secondary hosts to complete. Working nsenter for the above error would have been:

    nsenter -t 13209 -n mount -vvv -o clientaddr=10.42.140.62,nfsvers=4 ganesha.sync.rancher.internal://auth-config /var/lib/rancher/volumes/rancher-nfs/auth-config

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
