### ISSUE TITLE
Custom registries require email?

### ISSUE THREAD

**Issue by xinity** [rancher/rancher#921]
been trying to test custom registries with rancher.
has for quay.io and dockerhub , email is required , i don't know why this is still required for custom registries.

For example , registried protected by nginx does not need any email to authenticate users, so why is this required in custom config ?

**Comment by ibuildthecloud** [comment]
Good question.  Seems like it shouldn't be. Just curious, we honestly haven't tested nginx protected registries.  Do they actually work with Rancher?

**Comment by vincent99** [comment]
So what's the correct behavior here.. just make all 3 fields optional in the API and require user/email/pass for dockerhub in the UI?

**Comment by xinity** [comment]
i think (but that's my own opinion) that email should not be a requirement only for custom registries.
as far i as know dockerhub AND quay requires email/login/password

**Comment by xinity** [comment]
@ibuildthecloud i've tested nginx protected registry (0.9.1 AND 2.0) both works perfectly behind nginx

**Comment by xinity** [comment]
any update on this one ?
latest version of rancher still requires email :(

i know this isn't on high priority just asking :)

**Comment by vincent99** [comment]
Docker login in their v1 API takes three fields.  I think it's gone now in registry v2.

**Comment by vincent99** [comment]
It looks like email can be safely dropped now if the API is changed to not be marked required.

**Comment by tfiduccia** [comment]
Version - master 11/14
Verified fixed
