### ISSUE TITLE
Provisioning on AWS fails with: Error running apt-get update: ssh command error:

### ISSUE THREAD

**Issue by moelsayed** [rancher/rancher#9211]
**Rancher versions:** 1.6.2
rancher/server: latest
rancher/agent: 1.2.2

**Infrastructure Stack versions:**
healthcheck: v0.3.1
ipsec: v0.11.2
network-services: rancher/metadata:v0.9.1 rancher/network-manager:v0.7.1
scheduler: v0.8.0
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
```
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 17.03.2-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 23
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-1020-aws
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.795 GiB
Name: ip-172-31-26-142
ID: SUOQ:4IBO:5U6B:3ZJJ:T2BM:4OJV:FSIK:YPAO:VA7S:4TKN:ZEQU:A276
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
Linux ip-172-31-26-142 4.4.0-1020-aws #29-Ubuntu SMP Wed Jun 14 15:54:52 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
Intermittent error. I created several hosts using the following rancher cli command, issue was triggered 3 times:
```
 rancher --debug host create --driver amazonec2  --amazonec2-access-key $KEY --amazonec2-secret-key $SKEY --amazonec2-security-group rancher-machine --amazonec2-region eu-west-2 --amazonec2-zone b  --name test-$RANDOM --amazonec2-instance-type t2.small --engine-install-url=https://releases.rancher.com/install-docker/17.03.sh  --amazonec2-ami ami-cc7066a8
```
**Results:**
Provisioning fails and UI shows the message:
> Error running provisioning: Error running apt-get update: ssh command error:

Rancher server logs:

[error_log.txt](https://github.com/rancher/rancher/files/1116884/error_log.txt)

**Comment by vincent99** [comment]
Since `apt-get update` Is failing and it's intermittent, the mirror repo is probably having issues...

**Comment by moelsayed** [comment]
That would explain it I guess. I will try to test and confirm this.
