### ISSUE TITLE
Socket disconnects when using CentOS 7.3 as Agent

### ISSUE THREAD

**Issue by FireDrunk** [rancher/rancher#9212]
**Rancher versions:**
Component	Version
Rancher	v1.6.2
Cattle	v0.181.4
User Interface	v1.6.5
Rancher CLI	v0.6.1
Rancher Compose	v0.12.5
Agent: 1.2.2

**Infrastructure Stack versions:**
healthcheck: 0.3.1
ipsec: 0.11.2
network-services: 0.9.1/0.15.1
scheduler: 0.8.0

**Docker version: (`docker version`,`docker info` preferred)**
17.03.0-ce
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
CentOS 7.3 Kernel 3.10.0
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
vSphere VM's
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Rancher Server on seperate host, internal DB. 4 vSphere VM's as Rancher Nodes.
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
Did fresh install of new Rancher server, added my existing hosts, try to view stats or execute shell.
**Results:**
No stats / No shell

Error log in Chrome:

Socket connecting (id=23, url=ws://internal-hostname:5001/v1/containerstats...)
socket.js:217 Socket opened (state=connecting, id=23)
socket.js:169 Socket null closed
subscribe.js:150 Subscribe ping (projectId=1a5, sockId=1)
socket.js:217 Socket closing (state=connected, id=14)
socket.js:169 Socket 14 closed
subscribe.js:150 Subscribe ping (projectId=1a5, sockId=1)
socket.js:48 Socket connecting (id=24, url=ws://internal-hostname:5001/v1/containerstats...)
socket.js:217 Socket opened (state=connecting, id=24)
socket.js:169 Socket null closed

Tried Windows + Chrome, Windows + Firefox, (Seperate machine) Linux + Chrome, all give same result.

I've ran Rancher Server on RancherOS, no difference, now Rancher Server container is running on external Fedora 25 host. Same result.

The /var/lib/cattle/logs/cattle.log file inside the rancher server container doesn't show anything regarding the disconnects.

**Comment by aemneina** [comment]
@FireDrunk do you have a load balancer or a firewall appliance in front of your rancher server? Do your agent hosts show that they're connected fine?

**Comment by FireDrunk** [comment]
Nope, only a single router hop.

**Comment by FireDrunk** [comment]
`Socket connecting (id=7, url=ws://192.168.1.3:5001/v1/containerstats/ceb2971bc82d0b3bf04d656ca6ba004dcf591b41500621624608d5b9afce3a25...)
ui-9ff4e0f7149d48d6bb46c780a83cf75d.js:111 Socket opened (state=connecting, id=7)
ui-9ff4e0f7149d48d6bb46c780a83cf75d.js:111 Socket null closed`

Even on same subnet i'm having the issues now. Is the socket connection being rerouted directly from the Rancher Server to the Agents?

Oh, and yeah, Agent connection is fine, and docker containers work fine.

![image](https://user-images.githubusercontent.com/6359704/27767676-3b1bfc74-5eff-11e7-9ceb-1c421f97eb55.png)

**Comment by FireDrunk** [comment]
As a test, i've tried running the boot2docker thru the vSphere Machine Driver, and i get this issue inside the boot2docker rancher-agent:
https://github.com/docker/compose/issues/2515

I think i'm starting from scratch, because now i don't trust anything anymore...

**Comment by FireDrunk** [comment]
After removing every docker container from the original hosts, and reinstalling the Rancher Server container on a new machine, everything is working again.

In the past i've switched IP's for the Rancher Server a few times, without cleaning the agents from the connected hosts, perhaps some residual configs remained in the /var/lib/ directories, which interfered.

**Comment by superseb** [comment]
Thanks for reporting back
