### ISSUE TITLE
rancher agent not inheriting proxy settings from docker daemon

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#9213]
**Rancher versions:**
rancher/server: 1.6.2
rancher/agent: 1.2.2

**Docker version: (`docker version`,`docker info` preferred)**
1.12.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
RHEL 7.3
Configured proxy settings according to the docs [here](https://docs.docker.com/engine/admin/systemd/#httphttps-proxy)

as recommended by [this rancher doc page](http://rancher.com/docs/rancher/v1.6/en/hosts/custom/#hosts-behind-a-proxy)

systemctl show --property=Environment docker
Environment=HTTP_PROXY=http://myproxy.example.com:80/ HTTPS_PROXY=https://myproxy.example.com:443/

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA

**Steps to Reproduce:**
1. following recommendation from the rancher doc page.

**Results:**

**Desired:**
have agent leverage proxy settings configured in the docker environment settings.

**Comment by aiwantaozi** [comment]
@yasker @aemneina 

I also try to reproduce this and find something wired. The command with environment params like this: -e http_proxy,  may not stable.
https://github.com/rancher/rancher/blob/master/agent/run.sh
docker run \
        -d \
        --net=host \
        --pid=host \
        --privileged \
        -e http_proxy \
	 -e HTTP_PROXY \
        -e https_proxy \
	 -e HTTPS_PROXY \
        -e NO_PROXY \
        -e no_proxy \
        nginx

I have set the http_proxy,  HTTP_PROXY, https_proxy, HTTPS_PROXY environment params in with different value: 

- /etc/systemd/system/docker.service.d/http-proxy.conf
- /etc/default/docker
- export param in host 

and I inspect the container, then find only the http_proxy and https_proxy have been set, and with the value export in the host. 

 "Env": [
                "http_proxy=small.std.com",
                "HTTP_PROXY",
                "https_proxy=smalls.std.com",
                "HTTPS_PROXY",
                "NO_PROXY=127.0.0.1",
                "no_proxy=127.0.0.1",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "NGINX_VERSION=1.13.3-1~stretch",
                "NJS_VERSION=1.13.3.0.1.11-1~stretch"
            ]

Docker version: 1.12.6
OS version: Ubuntu 16.04.2 LTS

**Comment by aiwantaozi** [comment]
@aemneina @yasker Just reading the Doc again and again, the doc seems not talk about that the agent will inherit the http_proxy from the docker daemon, and I think maybe the proxy just use for pull the images. http://rancher.com/docs/rancher/v1.6/en/hosts/custom/#hosts-behind-a-proxy

**Comment by aiwantaozi** [comment]
Hi, this issue base on the rancher doc here  http://rancher.com/docs/rancher/v1.6/en/hosts/custom/#hosts-behind-a-proxy.  It tells us the way to set up a host behind a proxy. The proxy values are used by the daemon, for instance when it needs to pull an image, it will not pass to rancher agent container automatically. Something is in the docker daemon's env does not mean it should ever propagate to containers. 

The way we use to start the agent, the http_proxy params is from the host environment params, not the docker daemon environment, docker will not propagating the environment params configured in the init system file to the containers. 

docker run \
        --net=host \
        --pid=host \
        --privileged \
        -e http_proxy \
          nginx

In addition, the file /etc/default/docker is only used for systems running "Upstart" or "SysVinit" as an init system, systemd need to config in another place, and the file also has the notice for that. https://github.com/docker/docker/blob/v17.03.1-ce/contrib/init/sysvinit-debian/docker.default#L1-L8 (higher version docker)

These init systems will not pass the environment params config in the service init system file to the host environment params. (We tried the systemd). 

Docker doesn't automatically support the environment propagating. If we want to set the http_proxy to the container, we could set the http_proxy to the environment params, and run container with the -e http_proxy. Or find ways to let the init system pass the environment setting for service to the host.

**Comment by loganhz** [comment]
hi @aemneina @yasker , may I know why we need the proxy setting in `rancher-agent` ? is it for talking to `rancher-server` ?

**Comment by deniseschannon** [comment]
@aiwantaozi @yasker does rancher work behind a proxy based on the docs?

**Comment by deniseschannon** [comment]
Based on conversations with @aemneina, the customer expected that the agent container would have the proxy settings inside the container. This will not occur unless you specifically edit the custom command to add in the environment variables. 

I've updated the docs to include that information: 

https://github.com/rancher/rancher.github.io/pull/915

In terms of any issues with setting up Rancher behind a proxy, any issues should be filed as a separate issue.

**Comment by yasker** [comment]
Thanks @deniseschannon
