### ISSUE TITLE
LoadBalancer failed to forward all after restart if rules include tcp protocol type

### ISSUE THREAD

**Issue by shaoyangyu** [rancher/rancher#9214]
*Describe your issue here*
HI,  
I am really new to Rancher and haproxy.
I created a lb in my stack and added port rules which include one tcp protocal, like below in rancher-compose.yml:
      - priority: 3
        protocol: tcp
        service: nginx
        source_port: 443
        target_port: 443
part in docker-compose.yml
  hcare-lb:
    image: rancher/lb-service-haproxy:v0.7.5
    ports:
    - 81:81/tcp
    - 80:80/tcp
    - 443:443/tcp
    - 9292:9292/tcp
    - 9191:9191/tcp
    - 8181:8181/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
everything looks good, but after host reboot, all port forwarding rules failed unless I upgrade the lb.  

Any comments for this?

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.2` Cattle: `v0.181.4` UI: `v1.6.5` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`service.containers`|

**Comment by shaoyangyu** [comment]
BTW, If I remove the TCP protocol port rule, the problem don't happen.

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
