### ISSUE TITLE
Can't use localhost or 127.0.0.1 as host registration URL

### ISSUE THREAD

**Issue by shaoyangyu** [rancher/rancher#9215]
*Describe your issue here*
HI,
I am not sure if my usecase is reasonable, I need setup a host(baremetal) in one network env and then move it to other net env,the host ip will be changed. I want to make sure Rancher server and Rancher agent and the stacks I installed on the host, still work in new net env. So I tried to use 127.0.0.1 as host registration url as below screen shot, but when I tried to use the reg to run agent, error message said cant find the endpoint(it is emtpy).

Any suggestion?

![image](https://user-images.githubusercontent.com/1483923/27766628-92b048e6-5f09-11e7-86a6-e50f1c83fb0d.png)

![image](https://user-images.githubusercontent.com/1483923/27766632-a4780ce4-5f09-11e7-81e8-b67dac20dd10.png)

![image](https://user-images.githubusercontent.com/1483923/27766633-b8d96002-5f09-11e7-896f-76d5581973a1.png)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.2` Cattle: `v0.181.4` UI: `v1.6.5` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`hosts.new.index`|

**Comment by vincent99** [comment]
You can't use localhost (or 127.0.0.1, or similar).  Localhost inside of a container (like the agent container) is the container itself.

**Comment by shaoyangyu** [comment]
Hi, Vincent
I just realized the 127.0.0.1 is pointed the container itself. Then in the context(the rancher agent and the rancher server are in the same baremetal), is it ok to run the agent container as net host mode，then could use 127.0.0.1 or localhost for registration and not need to re-config rancher env?

**Comment by vincent99** [comment]
While maybe possible for an installation with exactly one host, we do not test or support that configuration because most of the point of the product is managing multiple hosts.

**Comment by shaoyangyu** [comment]
I would think it is very useful usecase. 
For example, my current project is going to provide a tiny private cloud solution on one appliance(it is baremetal), so in common case, we only have one host .
what I am doing now for that as below :   
1. install RancherOS on the appliance , 
2 create a static secondary ip on nic(like 192.168.3.100), 
3 use the secondary ip to add new host on rancher, 
4 deploy stacks on the host  then even the appliance is started in customer env with different ip ,the stacks on the env still can work well with the secondary ip.
So far looks good.:)
Your suggestions are welcome.
