### ISSUE TITLE
upgrade - allow service to finish requests before killing it

### ISSUE THREAD

**Issue by dbones** [rancher/rancher#9217]
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

Feature request (or information request)

In short: allow a service instance to know when it is about to be stopped for an upgrade. 

more detail
All my services has multiple interfaces (HTTP and AMQP). on upgrade the services may be processing messages (from either of the interfaces), ideally complete these in-flight messages, and would need to prevent any new messages (again from both interfaces) from being accepted. 

Possible proposal on upgrade: 

* For HTTP, Rancher  to remove the container instance from the load balancer (thus no new requests to that container)
* For AMPQ,  Rancher to notify the container being upgraded (maybe by a simple HTTP call to a known endpoint ie container/api/invokeUpgrade), allowing the container to handle AMQP things internally

and finally a mechanism to allow Rancher to know the service has completed any in-flight transactions. possibly exposing an API call for the container to make or for the Rancher to poll a known endpoint ie container/api/readyForUpgrade (which can return a payload)

this would minimise the number of message (HTML, AMPQ, etc) from being thrown into a faulted state.

**Comment by janeczku** [comment]
@dbones 

> For AMPQ, Rancher to notify the container being upgraded

When we stop a container a SIGTERM is sent to the process in the container. You should make your application handle that signal to finish in-flight requests and gracefully shutdown. By default Docker gives a grace period of 10 seconds upon which the container process is terminated with a SIGKILL. See also https://github.com/rancher/rancher/issues/7715.

> For HTTP, Rancher to remove the container instance from the load balancer (thus no new requests to that container)

This enhancement is already tracked here: https://github.com/rancher/rancher/issues/2777

Are you okay with closing this ticket?

**Comment by dbones** [comment]
this is excellent, I have modified my services to react to the SIGTERM (will need to run some tests)

I have +1'ed the linked tickets

re #2777 that should work in my case 

for now I will close this ticket.
