### ISSUE TITLE
[feature request] Configmap-like thing in cattle.

### ISSUE THREAD

**Issue by ketchoop** [rancher/rancher#9218]
Just strange to see, that rancher doesn't have this killer feature. Even swarm implemented similar thing.

**Comment by blaggacao** [comment]
Meanwhile usurping secrets:
```bash
#!/usr/bin/env bash
set -e
# While we are dealing with rancher, which has no ConfigSets
for folder in $(find /run/secrets -maxdepth 1 -mindepth 1 -type f -name "__*" ); do
	target=${folder#/run/secrets/}
	target=${target//__//}
	mkdir -p ${target%/*}
	rm -f ${target}
	cp -rp "${folder}" "${target}"
    echo "Copied ${folder} to ${target} (Rancher Indirection)"
done;
```

Replaces `__` in the filename by `/` (as in folder hierarchy) and strips `/run/secrets/` all together...

**Comment by blaggacao** [comment]
@superseb Is something like this planned for rancher 2.0? Or is there a different approach to config management in 2.0 which I didn't figure out, yet?

**Comment by vincent99** [comment]
2.0 is kubernetes, which obviously has ConfigMaps.  So you can use them directly, they will probably make their way into  the UI eventually.

**Comment by blaggacao** [comment]
> they will probably make their way into the UI eventually.

Hopefully!!! :wink: It's a silver bullet for (how I understand) config management

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
