### ISSUE TITLE
when I create a loadbalance in my stack,it always  pull the image from internet. whether the local host has the image. rancher 1.6.2

### ISSUE THREAD

**Issue by waldron-xing** [rancher/rancher#9219]
**Rancher versions:**
rancher/server:1.6.2
rancher/agent:1.2.2

when I create a loadbalance in my stack,an exception appear which is "(Failed to allocate instance [container:1i2440]: Bad instance [container:1i2440] in state [error]: Image [index.docker.io/rancher/lb-service-haproxy:v0.7.5] failed to pull: Pulling repository docker.io/rancher/lb-service-haproxy".
But I have the images rancher/lb-service-haproxy:v0.7.5  on my local host.
My local host is no internet access.

**Comment by superseb** [comment]
Did you follow the documentation for installing Rancher without internet access? http://rancher.com/docs/rancher/v1.6/en/installing-rancher/installing-server/no-internet-access/#using-a-private-registry

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
