### ISSUE TITLE
Full text search in registries

### ISSUE THREAD

**Issue by xinity** [rancher/rancher#922]
is there any plan to add Full Text search for registries ? especially for custom registries ? 

this feature would be really awesome and free users/admins to have a specific registry webui to search for a docker image.

thanks for this awesome piece of work guys !

**Comment by vincent99** [comment]
I'd like to but last time I looked the dockerhub API is pretty painfully slow for autocomplete.  Maybe it would be better for custom registries.

**Comment by xinity** [comment]
indeed @vincent99 as docker registry 2.0 dropped the search API as well, this can be hard to implement :(

**Comment by xinity** [comment]
Any update on this one maybe? Docker registry added recently a catalog API, which should helps a lot implementing search in rancher ;-)

**Comment by Verikon** [comment]
+1 - I'm currently curling to get names as a JSON object.
curl -u user:pass https://myreg.domain.com:5000/v2/_cataog

It seems odd to not be able to add a registry but not peer into the contents.

**Comment by vincent99** [comment]
Really don't think this will ever be practical given the size and speed of Dockerhub.
