### ISSUE TITLE
when I tried to add a host to rancher, I got an excption

### ISSUE THREAD

**Issue by hailisun** [rancher/rancher#9220]
*Describe your issue here*
that is the excption's details:

requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /v1 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fe41df8a810>: Failed to establish a new connection: [Errno 111] Connection refused',))

any suggestions?

best wishes

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.2` Cattle: `v0.181.4` UI: `v1.6.5` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`hosts.new.index`|

**Comment by vincent99** [comment]
You can't use `localhost` as the registration URL.  Localhost is always the thing it's being resolved in, i.e. the agent containeritself in this case, not the server container.

**Comment by hailisun** [comment]
yeah, I got it! thank you very much!
