### ISSUE TITLE
Please add Docker 17.05 support 

### ISSUE THREAD

**Issue by aboettger-tuhh** [rancher/rancher#9221]
**Rancher versions:**
rancher/server:
rancher/agent:

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**

**Results:**

**Comment by vincent99** [comment]
We do not and will not support Edge releases, as they are only supported by Docker for a month (and for 17.05 that month is already up). 

17.06 support will be in the next patch release.
