### ISSUE TITLE
Unable to add host in Rancher server

### ISSUE THREAD

**Issue by khulfreedos** [rancher/rancher#9222]
I was unable to add host in Rancher server. Those hosts were deployed in Azure using this template.

https://github.com/siemonster/azure

This works fine before during the first and second redeployment. However, during the 3rd redeployment, the host was unable now to be added in Rancher. 

Unable to find image 'rancher/agent:v1.2.2' locally
v1.2.2: Pulling from rancher/agent
b3e1c725a85f: Pull complete
4daad8bdde31: Pull complete
63fe8c0068a8: Pull complete
4a70713c436f: Pull complete
bd842a2105a8: Pull complete
3f7d6fd71888: Pull complete
16914729cfd3: Pull complete
b9c91512c230: Pull complete
Digest: sha256:cfb7fc0de1146680ca26e3bc8cd09cc7a0274eff99f5b84246c33642a99f81da
Status: Downloaded newer image for rancher/agent:v1.2.2

INFO: Running Agent Registration Process, 
CATTLE_URL=http://xx.xx.xx.xx:8080
INFO: Attempting to connect to: http://xx.xx.xx.xx:8080
INFO: http://xx.xx.xx.xx:8080 is accessible
INFO: Inspecting host capabilities
INFO: Boot2Docker: false
INFO: Host writable: true
INFO: Token: xxxxxxxx
INFO: Running registration
INFO: Printing Environment
INFO: ENV: CATTLE_ACCESS_KEY=F37658F09EC5580E2F48
INFO: ENV: CATTLE_HOME=/var/lib/cattle
INFO: ENV: CATTLE_HOST_LABELS=capricorn=1&heaven=1
INFO: ENV: CATTLE_REGISTRATION_ACCESS_KEY=registrationToken
INFO: ENV: CATTLE_REGISTRATION_SECRET_KEY=xxxxxxx
INFO: ENV: CATTLE_SECRET_KEY=xxxxxxx
INFO: ENV: CATTLE_URL=http://xx.xx.xx.xx:8080
INFO: ENV: DETECTED_CATTLE_AGENT_IP=xx.xx.xx.xx
INFO: ENV: RANCHER_AGENT_IMAGE=rancher/agent:v1.2.2
INFO: Launched Rancher Agent: bfcbeebd4337066a77f228b2f4b3463d2609c32ace346a72f2b250e05abf2934

root@siemonsternodes0:/var/lib# docker -v
Docker version 17.06.0-ce, build 02c1d87
root@siemonsternodes0:/var/lib# docker ps -a
CONTAINER ID        IMAGE                  COMMAND             CREATED             STATUS                          PORTS               NAMES
bfcbeebd4337        rancher/agent:v1.2.2   "/run.sh run"       9 minutes ago       Restarting (1) 18 seconds ago                       rancher-agent

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.2` Cattle: `v0.181.4` UI: `v1.6.5` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`hosts.index`|

**Comment by superseb** [comment]
You are running `17.06.0-ce`, this has a known bug in combination with `rancher/agent:v1.2.2` (https://github.com/rancher/rancher/issues/9192)

This will be fixed in v1.6.3, please downgrade till then.

**Comment by khulfreedos** [comment]
Thanks! It works.

**Comment by thinhlvv** [comment]
@khulfreedos  Could you please advice the step to fix? Is this issue cause by version ?

**Comment by khulfreedos** [comment]
@thinhlvv Yes, this was due to the version. I downgraded to a lower docker version. You should downgrade it in the rancher server and all the hosts. After that, you need to restart the docker.
