### ISSUE TITLE
Rancher Load balancer 503 error 

### ISSUE THREAD

**Issue by ArunParthiban10** [rancher/rancher#9225]
**Rancher versions:**
rancher/server: v1.6.2
rancher/agent: v0.181.4

**Infrastructure Stack versions:**
healthcheck:v0.3.1
ipsec:holder
network-services: rancher/metadata:v0.9.1, rancher/network-manager:v0.7.1
scheduler:v0.8.0
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**

Containers: 40
 Running: 39
 Paused: 0
 Stopped: 1
Images: 21
Server Version: 1.12.6
Storage Driver: devicemapper
 Pool Name: docker-253:0-132-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 6.944 GB
 Data Space Total: 107.4 GB
 Data Space Available: 100.2 GB
 Metadata Space Used: 14.88 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.133 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /data/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /data/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: journald
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Security Options: seccomp selinux
Kernel Version: 3.10.0-514.16.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 2
CPUs: 4
Total Memory: 15.66 GiB
Name: ALA00043.deluxe.com
ID: 2DNI:FNTJ:YY3J:ADYG:JLZU:CCZF:7SIZ:W346:RZOW:KVOP:IPYC:PW2R
Docker Root Dir: /data/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
Registries: docker.io (secure)

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
3.10.0-514.16.1.el7.x86_64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Private Cloud 

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
1. Create a service  (with only one container)
2. add a load balancer pointing to service in step 1
3. Move service in step one to a differnet host.
4. Try using the load balancer. (returns 503 error)

This error looks similar to the error reported here https://github.com/rancher/rancher/issues/3360

**Results:**
The load balancer will return a 503 error

**Comment by aemneina** [comment]
@ArunParthiban10 how did you move the container described in step 3 of the repro?

**Comment by ArunParthiban10** [comment]
Hi @aemneina, thanks for getting back. I move it by upgrading the service and then selecting a different agent in the scheduling tab (under the "run all containers on a specific host" option)

**Comment by superseb** [comment]
I can't reproduce this by following your steps, can you share the docker-compose and rancher-compose files just to be sure?

**Comment by funkydorian** [comment]
@superseb Same happening on me with the latest stable Rancher on k8s

**Comment by superseb** [comment]
@funkydorian This issue is regarding a Cattle environment and a Cattle specific use-case. Can you please open a new issue if you experience problems.

**Comment by superseb** [comment]
@ArunParthiban10 Please comment if you still need help on this.
