### ISSUE TITLE
Catalog URL has "000" appended to the end in "Manage Catalogs" page.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#9227]
Rancher Server version - v1.6.3-rc5
Steps to reproduce the problem:
Go to "Catalog" -> "All" ( or any option) and click on "Manage Catalogs" option.

"Manage Catalogs" page that shows up , has 000" appended to Catalog URLs for "library" and "community".

<img width="1013" alt="screen shot 2017-07-03 at 10 22 31 am" src="https://user-images.githubusercontent.com/4266958/27802779-c23eaa2c-5fda-11e7-87f8-b9952b48271a.png">

**Comment by LLParse** [comment]
Definitely caused by https://github.com/rancher/catalog-service/pull/91

**Comment by LLParse** [comment]
@joshwget What do you think is the most reasonable way to fix this?

**Comment by will-chan** [comment]
there's real no need to hide this.

**Comment by LLParse** [comment]
The more serious issue this exposed is that our API credentials weren't getting picked up by catalog-service (hence the nil UUID). Here's the PR that fixed that https://github.com/rancher/catalog-service/pull/95

**Comment by vincent99** [comment]
This is going to break the UI, which is expecting them to be the current known URLs.  There's no reason to "hide" it but there's also no reason to return that as the URL in the API.  Report the regular URL and append the uuid when actually fetching it where appropriate.

**Comment by sangeethah** [comment]
Tested with Rancher versions: 1.6.3-rc6 .
"Manage Catalogs" page does not show uuid in the url anymore.

But the X-INSTALL-UUID header set still has only "0000" values and not a valid uuid.

<img width="1608" alt="screen shot 2017-07-05 at 3 19 27 pm" src="https://user-images.githubusercontent.com/4266958/27888268-099f4a00-619a-11e7-857e-f41a73569833.png">

**Comment by LLParse** [comment]
@sangeethah Can you retest with rc7?

**Comment by sangeethah** [comment]
Tested with Rancher Server version - v1.6.3-rc7

X-INSTALL-UUID header set correctly on the calls made to get git.rancher.io.
<img width="1259" alt="screen shot 2017-07-06 at 8 05 16 am" src="https://user-images.githubusercontent.com/4266958/27927558-0b241476-6241-11e7-94b6-15a0fac51c1a.png">
