### ISSUE TITLE
Container / Stack priority queue

### ISSUE THREAD

**Issue by PicoCreator** [rancher/rancher#9229]
Kubernetes work in progress idea found here : https://github.com/kubernetes/kubernetes/issues/28928

The following elaborates why this would be needed in larger scale environment.

> The need of this was made apparently in my infrastructure recently. With the equivalent of multiple nodes failure occured. This set off an entire chain of approximately a 1000 containers that needed to be rebuilt into other nodes. Which in effect brings it to approximately 2000+ process for "Running/Ready/Delayed"
> 
> Unfortunately, however as the various containers form dependencies that required one to be functional before starting another. I noticed in the process queue, that when a dependency is not met, the container is tossed back the queue (with the minor delay mechanism).
> 
> The problem here, i noticed (my rancher setup) can handle approximately 200 process commands at a time maxed out. This left the system with about 1800+ commands on the delay/running list. As processes get done. Another process is taken up from the queue, at what seem to be non-sequential order (I maybe wrong).
> 
> The thing is, the majority of about 900 containers were waiting for 100 containers first. And as a result constantly bouncing between run, being toss back to delay, then back to the queue, then run again.
> 
> The core 100 nodes that was needed were very extremely slowly being allocated.
> 
> Long passing the 3hrs mark, and lacking sleep (2am). Extreme measures was taken as a result. A cluster wide stop was done. Bringing up critical items first, before bringing up supporting containers.
> 

Ideally what is needed containers which takes priority over others. In event of a massive container failure/reallocation larger then the processing limit.

Kudos ~ lack sleep

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
