### ISSUE TITLE
Can't get kubernetes environment to run: process_linux.go:245: running exec setns process for init caused \"exit status 16\"")

### ISSUE THREAD

**Issue by javadevmtl** [rancher/rancher#9233]
**Rancher versions:**
rancher/server: 1.6.2
rancher/agent: 1.2.2

**Infrastructure Stack versions:**
All versions expected to be ran with 1.6.2 Creating environment through the rancher UI.

**Docker version: (`docker version`,`docker info` preferred)**
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      linux/amd64
 Experimental: false
----------
Containers: 10
 Running: 9
 Paused: 0
 Stopped: 1
Images: 15
Server Version: 17.03.1-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.34-rancher
Operating System: RancherOS v1.0.3
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.67 GiB
Name: temp-rancher.novalocal
ID: ZMYI:J7XM:OHZX:PLRZ:JYZC:SPIV:VS3G:7S7G:2BSO:5AMM:YQDV:YSMS
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
WARNING: No cpu shares support
WARNING: No cpuset support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="RancherOS"
VERSION=v1.0.3
ID=rancheros
ID_LIKE=
VERSION_ID=v1.0.3
PRETTY_NAME="RancherOS v1.0.3"
HOME_URL="http://rancher.com/rancher-os/"
SUPPORT_URL="https://forums.rancher.com/c/rancher-os"
BUG_REPORT_URL="https://github.com/rancher/os/issues"
BUILD_ID=

4.9.34-rancher

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Openstack

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher, internal DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Trying to luanch Kubernetes Environment

**Steps to Reproduce:**
Make fresh install of Rancher onto Rancher OS
Tried with 1 agent and 3 agents the results are the same.

**Results:**
Kubernetes services just keep throwing errors and restarting.
Some examples....
```
kubernetes-kubelete-1:  Stopped (Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:245: running exec setns process for init caused \"exit status 16\"")
```

```
kubernetes-kubernetes-1: Error (Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:258: applying cgroup configuration for process caused \"mountpoint for cgroup not found\"")
```

**Comment by superseb** [comment]
Kubernetes only supports Docker `1.12.6`, please downgrade the user docker and try again.

```
sudo ros engine switch docker-1.12.6
```

Closing this out as not-a-bug, please reply if you need any more help.

**Comment by javadevmtl** [comment]
It would be nice if the UI explained this or the docs. It doesn't seem apparent. trying it out noe see if it works with your suggestion. Thanks

**Comment by javadevmtl** [comment]
Ok seems to work now :)

**Comment by vincent99** [comment]
http://rancher.com/docs/rancher/v1.6/en/hosts/#supported-docker-versions
