### ISSUE TITLE
Healthcheck scheduler recreates failing container on same host

### ISSUE THREAD

**Issue by RonWilliams** [rancher/rancher#9234]
**Rancher versions:**
rancher/server: v1.4.1
rancher/agent: v1.2.0

**Infrastructure Stack versions:**
healthcheck: v0.2.3
ipsec: 0.0.5-a
network-services: v0.0.18
scheduler: v0.4.0

**Docker version: (`docker version`,`docker info` preferred)**
1.12.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
RHEL 7

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Custom VM

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher server, external DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Create a basic web service requiring network connectivity between multiple hosts. Enable a healthcheck that expects the container service to require connectivity to secondary backend containers (ex. Apache connecting to backend DB). Configure the healthcheck to recreate the container on failure. When IPSEC network connectivity is diminished, the healthcheck will attempt to recreate the container repeatedly on same host with network failure. 

**Expected Behavior:**
Scheduler/Healthcheck recreation should migrate affected containers to new host when affect hosts are experiencing outage conditions. 

**Potential Solutions:**
1. Detect potential network issues outside of container specific problems and avoid scheduling replacement containers on same host. 
2. Recreate containers on new host and apply conditions to isolate host usage for stack/service combination for escalating periods of time.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
