### ISSUE TITLE
Feature Request - Option to save git credentials

### ISSUE THREAD

**Issue by vikas027** [rancher/rancher#9235]
**Rancher versions:**
rancher/server: 1.6.2
rancher/agent: 1.2.2

**Problem:**
At the moment, there is no option to save Git credentials (Password or SSH Key) somewhere in Rancher. This is particularly useful while adding a custom Rancher Catalog.

**Workaround:**
Very insecure. Save credentials in the Git URL of Rancher Catalog
```
https://username:password@github.com/username/repository.git
```

**Comment by joshwget** [comment]
Duplicate of #3248 / #7638
