### ISSUE TITLE
Feature Request - Update Catalogs automatically on a git commit 

### ISSUE THREAD

**Issue by vikas027** [rancher/rancher#9236]
**Rancher versions:**
rancher/server: 1.6.2
rancher/agent: 1.2.2

**Problem:**
At the moment, we need to refresh the catalogs manually whenever we update our git repo
![2017-07-05_10-18-55](https://user-images.githubusercontent.com/6998650/27844896-948b5872-616b-11e7-96ab-f2cbddde9e87.png)

**Workaround (have not checked yet):**
Have a git hook which makes a curl call to refresh the catalog.

**Comment by vincent99** [comment]
It updates every five minutes.

**Comment by vikas027** [comment]
@vincent99 Can we tweak the parameter which does that?
