### ISSUE TITLE
Can't change 'Support' field in Catalog

### ISSUE THREAD

**Issue by vikas027** [rancher/rancher#9237]
**Rancher versions:**
rancher/server: 1.6.2
rancher/agent: 1.2.2

**Problem:**
I couldn't find an option to change this field in the Rancher Catalog (`config.yml`). In my `config.yml`, I had tried setting `support` parameter to something else in vain.
![2017-07-05_10-28-14](https://user-images.githubusercontent.com/6998650/27845114-fd98890e-616e-11e7-9774-6c2c8ac15e8d.png)

**Comment by superseb** [comment]
This is not possible, as it's hard coded here https://github.com/rancher/ui/blob/045c4dc74dbbb26402b1377dc1cc778e5388d119/app/components/new-catalog/template.hbs#L26

You can use the maintainer field to specify maintainer and contact info, is this enough or do you want to change the support field>

**Comment by vikas027** [comment]
Hey @superseb , 

This is our use case - we at work are looking to have this option as the catalogs would be created by different teams and thus the users who will use the catalogs can directly reach out to the team which has created it.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
