### ISSUE TITLE
resolve (rpc error: code = 13 desc = invalid header field value "oci runtime error: exec failed)

### ISSUE THREAD

**Issue by burncode** [rancher/rancher#9239]
I looked for a long time, and finally found the problem.If you choose the Managed network.Console below command， You can't choose Interactive & TTY .You can resolve this error by choosing None.
If you choose the Bridge and  choose Interactive & TTY ,you can resolve this error too.

**Comment by superseb** [comment]
Sorry, we'll need some more info. Please specify steps to reproduce the error, preferably by using the issue template. I can reopen if we have more info.
