### ISSUE TITLE
Optimized catalog fetch is not used when catalog url is "http://"

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#9246]
Rancher versions: 1.6.3-rc5

Steps to reproduce the problem:
Add a catalog with catalog url set to http://<git url>

Once catalog is synced to rancher-server, attempt a manual refresh of catalog.

tcpdump shows the old http calls (not the new optimized calls) being made to fetch catalog changes.

<img width="1700" alt="screen shot 2017-07-05 at 11 50 41 am" src="https://user-images.githubusercontent.com/4266958/27881294-f0fa6d58-617c-11e7-957a-6e00a606724c.png">

**Comment by sangeethah** [comment]
Tested with Rancher versions: 1.6.3-rc6 by setting library catalog to http://git.rancher.io/rancher-catalog.git.
Tcpdump shows the new http calls (optimized) calls being made:

<img width="1608" alt="screen shot 2017-07-05 at 3 19 27 pm" src="https://user-images.githubusercontent.com/4266958/27888062-ee2bcdbc-6198-11e7-9a29-e7126c073107.png">

**Comment by sangeethah** [comment]
Optimized fetch now works fine for git mirror - ( http://git.rancher.io/) but it is still not working with http://github.com or https://github.com

**Comment by LLParse** [comment]
@sangeethah Can you retest with rc7?

**Comment by sangeethah** [comment]
Tested with Rancher versions: v1.6.3-rc7

In case of https://github.com or http://github.com , fetch happens only when there are changes to be synced to the rancher-server as expected.
