### ISSUE TITLE
Need Global to have +- added to them

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#9247]
**Rancher versions:** console

**Steps to Reproduce:**
1.  Add host to an environment
2. Create a global service
3. After it's active, click on arrow to show container
4. Click on name to go to details

**Results:**  There is no + - associated to the service.  Also the Scale in details says n/a.  Thought we were going to allow them to do this.
![image](https://user-images.githubusercontent.com/11514927/27882060-ff75f43a-617f-11e7-8951-25f068e0f9bb.png)
![image](https://user-images.githubusercontent.com/11514927/27890080-80596f94-61a5-11e7-87b1-27f4c92f12af.png)

**Comment by westlywright** [comment]
@tfiduccia can you verify this on master? I believe it was resolved but the issue was never moved.

**Comment by tfiduccia** [comment]
Version - master 7/31
Verified fixed
