### ISSUE TITLE
Cannot start new stack.  Receive Wrongportformat error #422

### ISSUE THREAD

**Issue by dnadave** [rancher/rancher#9255]
When we went to start a new stack, we received the following error:

`Error (Bad response statusCode [422]. Status [422 status code 422]. Body: [code=PortWrongFormat, message=PortWrongFormat, baseType=error] from [http://localhost:8080/v2-beta/projects/1a5/services])`

This led us to discover that ipec, healthcheck, and scheduler are not running and cannot be activated either by restarting docker or by rebooting the server.  All of this had been working previously.

**Rancher versions:**
rancher/server: v1.6.2
rancher/agent: v1.2.2

**Infrastructure Stack versions:**
healthcheck: v0.2.3
ipsec: v0.11.2
network-services: v0.6.6
scheduler: v0.6.3
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
Docker version 1.12.6, build 78d1802

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="openSUSE Leap"
VERSION="42.1"
VERSION_ID="42.1"
PRETTY_NAME="openSUSE Leap 42.1 (x86_64)"
ID=opensuse
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:opensuse:42.1"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://opensuse.org/"
ID_LIKE="suse"
4.1.39-56-default

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher using external DB with host and agent on same machine

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Unkown

**Results:**
Server runs, existing containers run, but cannot start new containers.

**Comment by dnadave** [comment]
This is the error we see on the scheduler:

`Error (Couldn't bring up network: netplugin failed but error parsing its diagnostic message "": unexpected end of JSON input)`

**Comment by dnadave** [comment]
ipsec plugin error:

`Error (Couldn't bring up network: netplugin failed but error parsing its diagnostic message "": unexpected end of JSON input)`

**Comment by dnadave** [comment]
One thing I did notice was that despite starting the agent with `-e CATTLE_AGENT_IP=xx.xx.xx.xx`, I see that this value appears to not be used by `DETECTED_CATTLE_AGENT_IP` which is the value I see in the agent resources on the hosts tab on Rancher:

`# docker run --rm --privileged -e CATTLE_AGENT_IP=10.0.253.11 -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.2.2 http://10.0.253.11:8080/v1/scripts/2F6F26BB76A161E052B0:1483142400000:I8O5FVh8Ej3CBRiBCxO8ORhwk

INFO: Running Agent Registration Process, CATTLE_URL=http://10.0.253.11:8080/v1
INFO: Attempting to connect to: http://10.0.253.11:8080/v1
INFO: http://10.0.253.11:8080/v1 is accessible
INFO: Inspecting host capabilities
INFO: Boot2Docker: false
INFO: Host writable: true
INFO: Token: xxxxxxxx
INFO: Running registration
INFO: Printing Environment
INFO: ENV: CATTLE_ACCESS_KEY=AD5FECF63AA27846ADE1
INFO: ENV: CATTLE_AGENT_IP=10.0.253.11
INFO: ENV: CATTLE_HOME=/var/lib/cattle
INFO: ENV: CATTLE_REGISTRATION_ACCESS_KEY=registrationToken
INFO: ENV: CATTLE_REGISTRATION_SECRET_KEY=xxxxxxx
INFO: ENV: CATTLE_SECRET_KEY=xxxxxxx
INFO: ENV: CATTLE_URL=http://axiohost13:8080/v1
INFO: ENV: DETECTED_CATTLE_AGENT_IP=172.17.0.1
INFO: ENV: RANCHER_AGENT_IMAGE=rancher/agent:v1.2.2
INFO: Deleting container rancher-agent
INFO: Launched Rancher Agent: 4db5aff4ec90a901f226c4cd24d14f588057b1b2e560d6443087db77328f366b`

**Comment by dnadave** [comment]
While waiting for anyone to reply, we tried the suggestion by stefanlasiewski on https://github.com/rancher/rancher/issues/6858.  This wiped out our rancher-data container (I should have thought of that, first).  The consequences of this are:

1) I had to recreate our entire environment.  This really sucks as this is the only solution that EVER works when rancher fails.
2) When rancher came back up, it stopped and DELETED all of our other containers that had been running.  THIS IS A HUGE PROBLEM FOR US!  We do research and many of our research projects were running on those containers.  WHY?  WHY WOULD YOU HAVE THIS DONE BY DEFAULT???

I really wish there was an alternative to rancher.

**Comment by dnadave** [comment]
We're still getting this error trying to start up a new stack from our catalog:

`Error (Bad response statusCode [422]. Status [422 status code 422]. Body: [message=PortWrongFormat, baseType=error, code=PortWrongFormat] from [http://localhost:8080/v2-beta/projects/1a5/services])`

**Comment by dnadave** [comment]
All of the network services (ipsec, scheduler, etc.) are running without error, but we cannot start up new stacks and we have lost all of our old ones.

**Comment by dnadave** [comment]
I'm at a loss.  I've even deleted /var/lib/rancher and we still can't start up a stack.  Things work fine from the command line, but rancher can't do anything.

**Comment by dnadave** [comment]
If I try one of the community catalog entries, I can create a stack (or at least the rocketchat one).  If I use one of our catalog entries (which have worked until recently and were not changed recently), I get the bad port error.

Below are the docker-compose.yml and rancher-compose.yml for one that fails:

rancher-compose.yml
```
.catalog:
  name: "RStudio with Microarray Packages"
  version: "v0.7-may2017"
  description: "RStudio session with Microarray tagged packages installed"
  uuid: microarray-0

#microarray:
```

docker-compose.yml
```
microarray:
  image: dnadave/release_microarray:may2017
  ports:
  - :8787/tcp
  labels:
    io.rancher.container.pull_image: always
  tty: true
  hostname: axiohost13
  volumes:
  - /Projects/BIGdata:/data:rw
  stdin_open: true
  net: bridge
  privileged: true
```

Why won't these work anymore?  We haven't made any changes to them since early May and they stopped working in late June.

**Comment by cjellick** [comment]
The thing that is causing it to break is the leading `:` before 8787.
I tested your compose with various rancher versions going back to Feb 2017 (v1.6.0, 1.5.10, 1.5.0, & 1.4.0). It failed with that error message in all of them.
I took a look at the code and the bit that raises this error message hasn't been changed in awhile.

When it was working, was it with v1.6.2 or was it with a different version of rancher?
When it was working, how would you deploy: via copying the compose text into the text area in the UI for create stack, via a custom Catalog, via the `rancher-compose` command line, or via the `rancher` command line?

**Comment by dnadave** [comment]
?  This syntax has worked in all the versions you listed for us until a few
weeks ago.  The purpose of the : is to have Rancher assign a random port
that is mapped to 8787.  This syntax is what I was told to use when that
feature (port allocation randomly assigned by Rancher) was implemented.

So, I'm confused.  A feature that previously worked has been silently
removed?

**Comment by vincent99** [comment]
It's possible if you go back enough versions `:8787/tcp` didn't explode.  But as @cjellick said the correct syntax for a random port is, and [always has been](https://docs.docker.com/compose/compose-file/#ports), just specifying the container port.  

`8787` (or `8787/tcp`, which is the same thing because TCP is the default).

**Comment by dnadave** [comment]
When was this documented?  What changenotes is the change documented in?

**Comment by dnadave** [comment]
I requested this feature long ago and was told the syntax used in the yml I
provided, so it hasn't "always been".

**Comment by vincent99** [comment]
We're not doing this again with you.

It's not valid.  It was never valid.

The compose format is in Docker's docs, not ours.  It has never been valid for Docker either.

There is no change or documentation because it is not valid and was never valid. I was being generous and saying that _maybe_ some old version happened to work with it wrong.

Random ports were not added because of nor in response to you.  The original issue is (#2097)[https://github.com/rancher/rancher/issues/2097] and does not involve you, but _does_ say: 

> If service has a port defined under "ports" parameter as "80" or "80/tcp" (with no public port specified), public port will get automatically assigned to the port from environment.servicesPortRange

**Comment by vincent99** [comment]
And @cjellick was being *very* generous when he said it hasn't changed in a while.  The current code is from a 3 year old commit that added port validation, which far pre-dates the company and or a public release, and it has been completely unchanged since.

https://github.com/rancher/cattle/commit/f4be7f0b3e7abf0b962e9ea8375937978af2b484#diff-893bf93223c5b5202d36379888a2c6c5R18
