### ISSUE TITLE
Failed to initialize: EFS unavailable in region ap-southeast-2

### ISSUE THREAD

**Issue by stevenmunro** [rancher/rancher#9257]
I'm new to Rancher.

rancher/server: 1.6.2
Docker version: 1.12.6
Operating system and kernel:  Ubuntu 16.04.2 LTS (4.4.0)
Type/provider of hosts: AWS
Setup details: 3 test instances setup in the ap-southeast-2 region

Added rancher-efs storage driver. following errors produced in logs for all  efs-efs-driver containers

`06/07/2017 12:15:06time="2017-07-06T00:15:06Z" level=info msg="Running on host test3(1h4) with driver rancher-efs(1sd2)"`
`06/07/2017 12:15:07time="2017-07-06T00:15:07Z" level=fatal msg="Failed to initialize: EFS unavailable in region ap-southeast-2"`

AWS EFS *is* available in ap-southeast-2

https://ap-southeast-2.console.aws.amazon.com/efs/home?region=ap-southeast-2#/wizard/1

Is this a Rancher EFS driver issue or an AWS API issue?

**Comment by stevenmunro** [comment]
Ok, I figured it out. I've created my first ever pull request.
https://github.com/rancher/storage/pull/59

**Comment by superseb** [comment]
Thanks! This was merged.

Be aware EFS has been deprecated per v1.6.6.
