### ISSUE TITLE
name valume with bind-mount seems not work in rancher

### ISSUE THREAD

**Issue by shaoyangyu** [rancher/rancher#9261]
*Describe your issue here*
Hi 
Not sure if it is known issue, seems the bind-mount mode doesn't work in rancher, like below peace. I tried it in docker, it works.
  hcarefs-data:
     driver_opts:
         type: none
        device: /mnt/storage
        o: bind

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.2` Cattle: `v0.181.4` UI: `v1.6.5` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`service.containers`|

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
