### ISSUE TITLE
DNS lookup fails for container launched with docker and attached by tag

### ISSUE THREAD

**Issue by No3x** [rancher/rancher#9262]
**Rancher versions:**
rancher/server: v1.5.10
rancher/agent: rancher/agent:v1.2.2

**Infrastructure Stack versions:**
healthcheck: rancher/healthcheck:v0.2.3
ipsec: rancher/net:holder
network-services: v0.1.2
scheduler: v0.5.1

**Docker version: (`docker version`,`docker info` preferred)**
```
docker version
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

```
docker info
Containers: 37
 Running: 11
 Paused: 0
 Stopped: 26
Images: 78
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 461
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-83-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.953GiB
Name: v22016063647435330
ID: LYJ5:XGVQ:H7MU:PAHV:67ZV:XIKA:ATR3:5IAA:WTOJ:UDJT:6N2P:ZV5P
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
uname -r
4.4.0-83-generic
```
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
```
Ubuntu VPS
```
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
```
single node rancher
```
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
```
Cattle
```
**Steps to Reproduce:**
Dockerfile:
```dockerfile
FROM node:8.1.2

# Set current working directory as /home/app/code
WORKDIR /home/app/code

CMD ["node", "app.js"]

```
app.js
```node
require('dns').lookup('iana.org', (err, address, family) => {
  if (err) {
     console.log("Not found");
  } else {
     console.log("Found");
  }
});
```
The funny part:
docker-compose.yml Version 1
```yml
version: '2'
services:
 ranchertest:
   build:
     context: .
     dockerfile: Dockerfile
   environment:
     - HOME=/home/app/code
   volumes:
     - .:/home/app/code
```
docker-compose.yml Version 2
Adding to the ranchertest service the `labels`:
```yml
...
 ranchertest:
   labels:
     - io.rancher.container.network=true
   build:
...
```
Now running `docker-compose build` `docker-compose up` for each docker-compose.yml variants.
**Results:**
Version 1 outputs: `Found`
Version 2 outputs: `Not found`
With Variant 2 the container shows up in rancher infra/hosts section as standalone container:
![t](https://user-images.githubusercontent.com/2690708/27908976-cb3fc7ca-624e-11e7-89b9-35bd759b2bea.PNG)
So it must be registered by rancher definitely.
I don't understand this behavior.

**Comment by leodotcloud** [comment]
@No3x 
I run containers all the time in a similar fashion and I don't have any problem. Can you add `net: none` while you are adding the label? And also they show up as standalone containers because this container doesn't belong to any stack. Looks like the container is in stopped state after it has finished running?

```
docker run --name testcontainer \
--privileged -itd \
--net=none \
--label io.rancher.container.network=true \
leodotcloud/golang:1.7 bash
```

**Comment by leodotcloud** [comment]
@No3x When the container is started using `--net=none` and the label, Rancher CNI kicks in and sets up networking and `resolv.conf` for the container. Probably you are hitting a race condition when you are trying to resolve the address before the setup is done? Could you add retry logic in your app.js code instead of failing on first error?

**Comment by leodotcloud** [comment]
I can reproduce what you are seeing:

```
root@sangee16master-10acre-1:~# docker run --name testcontainer --privileged -it --net=none --label io.rancher.container.network=true leodotcloud/golang:1.7 ping google.com
ping: unknown host google.com
root@sangee16master-10acre-1:~# docker rm -f testcontainer
testcontainer
root@sangee16master-10acre-1:~# docker run --name testcontainer --privileged -it --net=none --label io.rancher.container.network=true leodotcloud/golang:1.7 sleep 1; ping google.com
PING google.com (173.194.74.102) 56(84) bytes of data.
64 bytes from jb-in-f102.1e100.net (173.194.74.102): icmp_seq=1 ttl=53 time=0.679 ms
64 bytes from jb-in-f102.1e100.net (173.194.74.102): icmp_seq=2 ttl=53 time=0.335 ms
^C
--- google.com ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 0.335/0.507/0.679/0.172 ms
root@sangee16master-10acre-1:~#
```
It takes a few milliseconds for networking to be setup, adding a retry logic (not sleep though) would solve your problem.

**Comment by No3x** [comment]
app.js
```node
const dns = require('dns');

setInterval(function() {
    dns stuff
});
}, 3000);
```
Outputs:
```
Recreating 441c1d4e76ea_441c1d4e76ea_cnn_ranchertest_1
Attaching to cnn_ranchertest_1
ranchertest_1  | Not found
ranchertest_1  | Not found
ranchertest_1  | Not found
ranchertest_1  | Not found
ranchertest_1  | Not found
ranchertest_1  | Not found
ranchertest_1  | Not found
ranchertest_1  | Not found
```
Then thought I maybe have to delay the node start. So I changed my Dockerfile like this:
```
CMD sleep 10; node app.js
```
same output as above. But this waiting is blocking - so it might not be fair. But I don't know any other methods to wait.
This tests are without adding network none.
When I try to add the network none to the docker-compose.yml as follows (Not sure this is equivalent to the cli command):

```yml
   networks:
     - none
```
```
$docker-compose build
ERROR: Service "ranchertest" uses an undefined network "none"
```

**Comment by leodotcloud** [comment]
@No3x If you could share a repo which has a test app.js file along with the other needed files, I can try to run the container myself and see what's going on.

**Comment by No3x** [comment]
@leodotcloud 
Please checkout [No3x/rancher-network-label-issue](https://github.com/No3x/rancher-network-label-issue)
Hope it contains everything. I created this on a client with docker (but without rancher) - `build` and `up` worked - output: `Found`. The same repo on the rancher machine: `Not Found`. This is the expected behavior like described in my first comment - it reproduces the issue and proves it has somethign to do with rancher.

**Comment by superseb** [comment]
Closing as stale.
