### ISSUE TITLE
Exception in Must have scheduling rule and unexpected behavior with should have scheduling rule while deploying new service

### ISSUE THREAD

**Issue by arminderlubana** [rancher/rancher#9263]
**Rancher versions:**
rancher/server: latest version
rancher/agent: v1.6.2

**Docker version: (`docker version`,`docker info` preferred)**
1.12.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04.2 LTS (4.4.0)

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher 

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle 

**Pre- requisite:**

1. Host A has label - io.rancher.scheduler.require_any="test1=value1, name1=value1"
2. Host B has label - io.rancher.scheduler.require_any="test1=value2, name2=value2" and hello1=value1
3. Host C has label - io.rancher.scheduler.require_any="test1=value1, name2=value2"
4. Host D has no labels.
5. Host E has label - io.rancher.scheduler.require_any="test1=value3"

**Bug detail:**

1. Deploy service with label - test1=value2 and hello1=value1 with exposed port and scale 1 and host label affinity set to hello1=value1.
2. Host label affinity can be set under the scheduling tab with two rules must have and should have.
3. When Host label affinity set with must have scheduling rule service instance should deployed in host B, but it is creating with an error.
4. When host label affinity set with should have scheduling rule service instance should get deployed in host B, Edit the require_any host labels in host B to remove the test1=value2 from the io.rancher.sheduler.require_any list. Delete the service instance. When the service reconcile triggered, instance should not be able to start on any host, whereas it gets started on host D

**Expected Result:**

1. Service should create with must have scheduling rule.
2. In case of should have scheduling rule when the service reconcile triggered, instance should not be able to start on any host.

**Actual Result:**

1. In case of must have scheduling rule an error occurred while creating a service.
2. In case of should have scheduling rule after deleting the service instance, instance is again getting started on host B.

**Steps to Reproduce**

1. Fulfill the prerequisites.
2. Deploy service with label - test1=value2 and hello1=value1 with exposed port - public host port "2000" and private container port "80". Scaled up the service to 1.

3. Set host label affinity with scheduling rule- Must have
  3.1. Set host label affinity to “hello1=value1" selecting must have host label from the drop down under scheduling tab.
   3.2. An error occurs on the creation of service “(Failed to allocate instance [container: 1i90]: Bad instance [container: 1i90] in state [error]: Allocation failed: needs host with label hello1: value1 and resource constraints: [2000:80/tcp portReservation, 1 instanceReservation])”.

4. Set host label affinity with scheduling rule- Should have
   4.1. Set host label affinity to hello1=value1 selecting should have label from the drop down under scheduling tab.
    4.2. Service instance is being deployed in host B.
    4.3. Edit the require_any host labels in host B to remove the test1=value2 from the io.rancher.sheduler.require_any list.
    4.4. Delete the service instance, once the service instance is deleted, the service reconcile is triggered, the instance is getting started on host D (which is not the expected result).

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
