### ISSUE TITLE
Unexpected behavior while deploying global service with label.

### ISSUE THREAD

**Issue by arminderlubana** [rancher/rancher#9265]
**Rancher versions:**
rancher/server: latest version
rancher/agent: v1.6.2

**Docker version:** (docker version,docker info preferred)
1.12.6

**Operating system and kernel:** (cat /etc/os-release, uname -r preferred)
Ubuntu 16.04.2 LTS (4.4.0)

**Type/provider of hosts:** (VirtualBox/Bare-metal/AWS/GCE/DO)
AWS

**Setup details:** (single node rancher vs. HA rancher, internal DB vs. external DB)
single node rancher

**Environment Template:** (Cattle/Kubernetes/Swarm/Mesos)
Cattle

**Pre- requisite:**
1.	Host A has label - io.rancher.scheduler.require_any="test1=value1, name1=value1"
2.	Host B has label - io.rancher.scheduler.require_any="test1=value2, name2=value2" and hello1=value1
3.	Host C has label - io.rancher.scheduler.require_any="test1=value1, name2=value2"
4.	Host D has no labels.
5.	Host E has label - io.rancher.scheduler.require_any="test1=value3"

**Bug detail:**
1. Global service with label="test1=value1" is being deployed on all hosts- Host A, B, C, D, E. 
2. When new host-h1 with io.rancher.sheduler.require_any="test1=value2" is created the instance of global service is deployed there as well.
3. Once host-h2 without any label created, the instance of global service deployed there as well.

**Expected Result:**
Global service instances should deployed only in host A, C and D. Service should be in "Active" state. Once host h2 is available, new instance for the global service should not deployed in this host.

**Actual Result:**
Global service instance deployed on all the hosts- Host A, B, C, D, E, h1 and h2.

**Steps to Reproduce**
1. Fulfill prerequisites.
2. Deploy a Global service with label="test1=value1".
3. Global service instance gets deployed on all hosts- Host A,B,C,D,E whereas it should get deployed only in host A,C and D.
4. When new host-h1, h2 created global service instance deployed there as well.

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
