### ISSUE TITLE
Unexpected behavior of health check enabled containers sometimes

### ISSUE THREAD

**Issue by arminderlubana** [rancher/rancher#9266]
**Rancher versions:**
rancher/server: latest version
rancher/agent: v1.6.2

**Docker version:** (docker version,docker info preferred)
1.12.6

**Operating system and kernel:** (cat /etc/os-release, uname -r preferred)
Ubuntu 16.04.2 LTS (4.4.0)

**Type/provider of hosts:** (VirtualBox/Bare-metal/AWS/GCE/DO)
AWS

**Setup details:** (single node rancher vs. HA rancher, internal DB vs. external DB)
single node rancher

**Environment Template:** (Cattle/Kubernetes/Swarm/Mesos)
Cattle

**Pre- requisite:** 
1.	Multiple Hosts - 2 IPs for each host.
2.	IPs are pre-configured on the hosts.
3.	Use nginx image
4.	Health check enabled containers as part of service.

**Expected Result:**
1.	Health check enabled containers should be created and should be accessible on exposed port using curl.
2.	When host on which the containers are created is Power OFF then the containers should move to another host and accessible on the exposed port using curl.

**Actual Result:**
1.	Sometimes Health check enabled containers stuck while initializing. 
2.	If these are started then on stopping their host, they are not migrating to the other host sometimes.

**Steps to Reproduce:**
1.	Fulfill the prerequisites.
2.	Create 2 health check enabled containers as a part of service by choosing TCP Connection Opens option under Health Check tab. Give Port= 80.
3.	On creation of health check enable containers,
3.1	Containers stuck while initializing sometimes.
3.2	If these are created  successfully then on stopping their host, these are not migrating to the other host sometimes.

**Comment by leodotcloud** [comment]
ping @sangeethah

**Comment by arminderlubana** [comment]
Hello @leodotcloud from where to ping @sangeethah from Slack or Git comment. if Slack then i did't get any user with name sangeethah or similar. Please suggest.

**Comment by arminderlubana** [comment]
hello @sangeethah , can you please verify the defect reported above?

**Comment by superseb** [comment]
How many hosts are you running when you experience this? What is the definition of sometimes, how often does this happen?

**Comment by arminderlubana** [comment]
Hello @superseb , 

we tried with 2 hosts and most of the time we are facing this behavior i.e. if we tried 10 time only 1 or 2 time it is working as expected. 

Please let me know if you require  any further information about it.

**Comment by sangeethah** [comment]
@arminderlubana , wanted to confirm that when you are assigning multiple ips to host , each of the assigned ips are reachable across hosts in the environment ? 
Also in the case , where you see the containers are stuck in "Initializing" state , can you check if you are able to ping the container's managed ip from healthcheck containers that are present in each of the host in your environment.

**Comment by arminderlubana** [comment]
Hello @sangeethah,  We are facing some challenges with latest version of Rancher Lab on our environment.  Let us fix the environment problem first, after that i can confirm the points mentioned by you.

**Comment by arminderlubana** [comment]
Hello @sangeethah, regarding multiple IPs, each assigned IPs are reachable across hosts in the environment. When health-check containers are stuck in "Initializing" state, we are able to curl these containers across the hosts.

**Comment by superseb** [comment]
Closing as stale.
