### ISSUE TITLE
Not able to curl the containers on the exposed port after Power ON the host.

### ISSUE THREAD

**Issue by arminderlubana** [rancher/rancher#9267]
**Rancher versions:**
rancher/server: latest version
rancher/agent: v1.6.2

**Docker version:** (docker version,docker info preferred)
1.12.6

**Operating system and kernel:** (cat /etc/os-release, uname -r preferred)
Ubuntu 16.04.2 LTS (4.4.0)

**Type/provider of hosts:** (VirtualBox/Bare-metal/AWS/GCE/DO)
AWS

**Setup details:** (single node rancher vs. HA rancher, internal DB vs. external DB)
single node rancher

**Environment Template:** (Cattle/Kubernetes/Swarm/Mesos)
Cattle

**Pre- requisite:**
1.	Single host with 2 IPs.
2.	IPs are pre-configured on the hosts.
3.	Use nginx image
4.	Containers within a service
5.	Power OFF/ON in a single host setup.

**Expected Result:**
After Power ON the host, containers should be accessible on the exposed port using curl.

**Actual Result:**
After Power ON the host, containers are not accessible on the exposed port using curl.

**Steps to Reproduce**
1.	Create two containers (with the same exposed port) on the host.
2.	Containers should be accessible on the exposed port using curl.
3.	Power OFF the host. 
4.	Power ON the host, containers should be accessible using curl.

**Comment by leodotcloud** [comment]
@arminderlubana Doesn't the IP address of the host change in AWS after you power off and power on the VM?

**Comment by arminderlubana** [comment]
@leodotcloud yes, IP address is changing after power off and on the AWS machine but we are trying curl with new IP address assigned to machine.

**Note: After Power off and on the AWS machine, if we restart the container from Rancher UI then we are able to do the curl.**

**Comment by leodotcloud** [comment]
@arminderlubana 
- If you create standalone containers on the host, they won't be started by default after power cycle of the host. The port will not be accessible if the container is down.
- I created a global service with an expose port and power cycled the host. This time the port is accessible on the new IP address coz the container is started automatically.

**Comment by leodotcloud** [comment]
@arminderlubana I hope that answers your question. Please open a new issue if you are still having problems.
