### ISSUE TITLE
Launching a service with non-existent image and a secret orphans vols in Rancher

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#9272]
**Rancher versions:**
rancher/server: v1.6.3-rc7

**Infrastructure Stack versions:**
rancher-secrets:v0.0.2

**Docker version: (`docker version`,`docker info` preferred)**
17.03.1-ce
**Steps to Reproduce:**
in Cattle env
create a secret
launch secret storage driver from catalog
create a service with an image that doesn't exist and uses a secret

**Results:**
Volumes are created in the inactive state as the service tries to reconcile. These volumes exist only in Rancher and are never called down to the volume driver. 

**Expected**
Since they are created and associated to the container, once the container errors out and is destroyed the volume should also be cleaned up.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
