### ISSUE TITLE
LB UI issues

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#9276]
**Rancher versions:** console 6/7

**Issues:**

- [x] State for all list pages is not centered properly.  It's too high
![image](https://user-images.githubusercontent.com/11514927/27937116-b08e5fca-6269-11e7-8893-fef6c22a5d85.png)

- [x] Search is always showing up to the left and off the screen (Open details page, make browser a little smaller, open a Nav that will have the Search field)
![image](https://user-images.githubusercontent.com/11514927/27934524-10d74d2e-625b-11e7-8ba3-48207c645b2a.png)

- [x] Target Rules needs to have some design issues
![image](https://user-images.githubusercontent.com/11514927/27934592-43c0f532-625b-11e7-8fbf-c8a55eb4ac0e.png)

- [x] Stack header info on LB list page is not aligned properly.  Should look more like container stack header.
![image](https://user-images.githubusercontent.com/11514927/27936695-fc8f766e-6266-11e7-9326-793e5657acfa.png)

**Comment by lvuch** [comment]
I can't recreate the second list item (search bar)

**Comment by lvuch** [comment]
@westlywright can you take a look at the search bar on containers?

**Comment by westlywright** [comment]
@lvuch yep i know what it is, though i thought i resolved this already :/

**Comment by tfiduccia** [comment]
Version - wagyu (master 7-25)
Verified fixed
