### ISSUE TITLE
[cli] rancher ssh into aws give permission denied(publickey).

### ISSUE THREAD

**Issue by kgk** [rancher/rancher#9278]
**Rancher versions:**
rancher/server: 1.6.2
rancher/agent:

**Infrastructure Stack versions:**
healthcheck:0.3.1
ipsec:net:holder
network-services:metadata:v0.9.2
scheduler:scheduler:v0.8.1
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**

1.12
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**
Create a new AWS node in UI

from terminal somewhere 
$ rancher hosts 
ID        HOSTNAME   STATE     CONTAINERS   IP              LABELS                               DETAIL
1h46      devc1      active    22           52.X.X.X.X   
1h63      devd1      active    11           52.Y.Y.Y.Y   

$ rancher  ssh devd1
Permission denied (publickey).

**Results:**
Expected to be able to ssh into the node without downloading the machine info (i.e. keys). Thought this would be handled by the rancher cli

**Comment by leodotcloud** [comment]
Syntax: `rancher ssh ${HOST_ID} -l ${USERNAME}`
`rancher ssh 1h1 -l root` or `rancher ssh 1h1 -l ubuntu` or `rancher ssh 1h1 -l ec2-user` depending on the cloud provider and OS.

**Comment by superseb** [comment]
Can you check the above comment and report back if it's still an issue?
