### ISSUE TITLE
Filtering of instances with a certain label does not change results

### ISSUE THREAD

**Issue by Tenoke** [rancher/rancher#9281]
**Rancher versions:**
rancher/server: v.1.5.10
rancher/agent: v1.2.2

**Infrastructure Stack versions:**
rancher/healthcheck:v0.2.3       
rancher/scheduler:v0.7.5        
rancher/net:v0.11.2              
rancher/net:holder               
rancher/dns:v0.14.2              
rancher/net:v0.11.2              
rancher/metadata:v0.9.1          
rancher/network-manager:v0.6.6   
rancher/agent:v1.2.2             

**Docker version: (`docker version`,`docker info` preferred)**
17.05.0-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="Ubuntu"
VERSION="16.10 (Yakkety Yak)"

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Virtualbox, docker-machine
Operating System: Boot2Docker 17.05.0-ce (TCL 7.2); HEAD : 5ed2840 - Fri May  5 21:04:09 UTC 2017

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
1. Create containers for a given label, 
2. try to filter their instances via the API e.g. {URL}/v2-beta/labels/1l1642/instances?state=removed

**Results:**
You'll get all instances with that label (including all purged and removed containers) no matter which filter you try

**Comment by arnauorriols** [comment]
Is there any alternative way to filter containers or services by label?

**Comment by vincent99** [comment]
This is the same root-cause as https://github.com/rancher/rancher/issues/5321 .  I don't think there is any server-side way to filter for this (and the `labels` collection itself is not actually a publicly documented part of the API)
