### ISSUE TITLE
Host not showing up after adding

### ISSUE THREAD

**Issue by ctejada10** [rancher/rancher#9285]
**Rancher versions:**
rancher/server: v1.5.5
rancher/agent: N/A

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
`Server Version: 17.06.0-ce`

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)** 
macOS 10.12.5

**Steps to Reproduce:**

**Results:**

After I run the Rancher Agent container on my home computer, nothing happens. Apparently it stays in a infinite restarting loop and does not show on my server.

Thanks.

**Comment by vincent99** [comment]
- Docker 17.06 is only supported by Rancher 1.6.3(+) and does not work in older versions
- Docker for Mac is not supported and the way they do networking does not fit very well with Rancher.

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
