### ISSUE TITLE
retain_ip should be possible for load balancers as well

### ISSUE THREAD

**Issue by stieler-it** [rancher/rancher#9288]
**Rancher versions:**
rancher/server: 1.6.2
rancher/agent: 1.2.2

**Infrastructure Stack versions:**
healthcheck: 0.3.1
ipsec: 0.11.2
network-services: manager 0.7.1, metadata 0.9.1
scheduler: 0.8.0

**Environment Template: Cattle**

**Steps to Reproduce:**

For regular services, we can choose that the IP address is not changed during e.g. an upgrade (retain_ip: true). We would also like to have that feature in Rancher load balancers as well.

**Comment by stieler-it** [comment]
Btw, it **is** possible while creating a stack by including retain_ip and even io.rancher.container.requested_ip in the YML files. So my suggestion would just be to add this feature to the UI.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
