### ISSUE TITLE
lost service resolv after rename and restart a stack

### ISSUE THREAD

**Issue by danielscai** [rancher/rancher#9289]
**Rancher versions:**
rancher/server:   1.4.3
rancher/agent: 1.2.0

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.4.3` Cattle: `v0.176.11` UI: `v1.4.9` |
|Access|`ldap` `admin`|
|Orchestration|`Cattle`|
|Route|`stack.index`|

**Infrastructure Stack versions:**
healthcheck: v0.2.3
ipsec: rancher/net:holder
network-services: rancher/metadata:v0.7.4 , rancher/network-manager:v0.6.6 
scheduler: rancher/scheduler:v0.6.3
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
1.12.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="14.04.4 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.4 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
```
and 
```
$ uname -r 
4.2.0-040200-generic
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
kvm 

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher external DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
cattle 

**Steps to Reproduce:**
1. create one stack, named stackA, with one service named serviceA. (image alping , whatever ) 
2.create another stack, named stackB, ,with one service named serviceB (image, alpine, whatever)
2.1 Add Service Alias in stackB, named serviceA, set target stackA/serviceA. 
2.2 now you can ping "serviceA" in serviceB 
2.3 rename stackA to stackC. now you can still ping "serviceA" , but rancher resolv servieA as " servicea.stackb.rancher.internal" , but it is still reachalbe 
3. restart stackC, you will get a "unknow host" error when you ping "serviceA" in serviceB. (ping: unknown host serviceA) 

**Results:**
you will get a "unknow host" error when you ping "serviceA" in serviceB. 
```
ping: unknown host serviceA
```

**Comment by sangeethah** [comment]
In step 2.3 , there is a typo - rename stackB to stackC is what it was intended to be ?
I am able to reproduce this issue where we get the following error from serviceB.

```
/ # ping serviceA
ping: bad address 'serviceA'
```

**Comment by danielscai** [comment]
@sangeethah sorry for the typo. 
 I mean " rename stackA to stackC. " 

you did the the right reproduce step.

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
