### ISSUE TITLE
Re-using same host and old containers are showing up, but starting them doesn't add them to the managed network.

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#929]
Version: v0.22.0-rc1

Steps to Reproduce:
1. Use an existing host that had containers running on it. Stop the rancher agent and all containers.
2. Launch a new rancher/agent command that has the same rancher/agent version.

Result: Any old containers show up, but network agent doesn't show up. The ability to start the container exists in the UI and the container will start. But the old network agent doesn't start so the container doesn't get assigned to the managed network.

Not sure what the expected result should be, but this is what I'm assuming:

You can re-start the old containers, but they should be part of the managed network. Therefore, if the network agent hasn't started, it should launch the network agent container and assign a container IP to the container. If network agent has already started, it should be providing the newly started container with a container IP.

**Comment by will-chan** [comment]
Not sure we can do much here.  Our native networking currently requires a label (and they are immutable once the container starts).  Now, if we add the ability to configure the docker daemon with Rancher's subnet IP space, this problem should be automatically resolved.
