### ISSUE TITLE
Feature to mention the batch size in the rancher-compose file

### ISSUE THREAD

**Issue by borntorock** [rancher/rancher#9291]
There should be an option to mention the deploy batch size in the rancher-compose file for the different services. 

As we can mention the scale for a particular service in the rancher compose file, there must be an option to mention the batch size as well in the rancher-compose file. 

@ibuildthecloud @prachidamle @vincent99

**Comment by vincent99** [comment]
The upgrade options are ephemeral input to the upgrade action in 1.x, but already moved to a stored property of the services for 2.0.

**Comment by borntorock** [comment]
@vincent99 Sorry, didn't followed? Can you point me to the docs link, how batch size can be used for a particular service.

I don't see any release with 2.0. All of them are of 1.x
