### ISSUE TITLE
rancher-cli install creates empty stack without services

### ISSUE THREAD

**Issue by irockel** [rancher/rancher#9295]
I've a local rancher installation. I've created an evironment and a API Key for it. I also have a custom catalog. If I now try to create a new stack using the following command line:

``
rancher catalog install customcat/testitem:1.0 --name test
``

the stack is successfully created, but does not contain any services. If I do the same using the GUI I get the expected services in my stack. Using --debug doesn't give any useful additional informations and the logs are empty either. 

Am I missing something?

Rancher-CLI Version: 0.6.2 (current version offered as download)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.0` Cattle: `v0.179.7` UI: `v1.6.1` Rancher-CLI: `v0.6.2`|
|Access|`ldap` `admin`|
|Orchestration|`Cattle`|
|Route|`stacks.index`|

**Comment by binary64** [comment]
I think I have the same issue:

`docker run -v /usr/local/share:/usr/local/share -it rancher/cli --url http://192.168.33.10:8888 stack create --docker-compose /usr/local/share/docker-compose.yml` creates an empty stack

and when i try and add a Service within the newly created Stack, it says "Validation failed in API: stackId"

**Comment by rawmind0** [comment]
Hi @irockel ,

is your custom testitem package using go templating in you docker compose file, `docker-compose.yml.tmpl`?? 

If yes, may be related to that, https://github.com/rancher/cli/pull/108

**Comment by deniseschannon** [comment]
There was an issue with CLI where running `catalog install` for a `docker-compose.yml.tpl` file would create a stack but no services. This is now fixed with v0.6.8-rc1.

**Comment by irockel** [comment]
Hi @rawmind0 

As fas as I remember, I got this in both cases. But I just retested it (we recently updated the rancher environment to 1.6.12) and I can no longer reproduce the issue. I just tried to launch a catalog item and the stack just started fine. So this issue can be closed.
