### ISSUE TITLE
IPSec service rollback non-stop

### ISSUE THREAD

**Issue by snipking** [rancher/rancher#9298]
**Rancher versions:**
rancher/server: 1.6.2
rancher/agent: 1.2.2

**Infrastructure Stack versions:**
healthcheck: 0.3.0
ipsec: 0.1.0
network-services: 0.2.2
scheduler: 0.6.1
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
1.12.6, build d5236f0

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
4.9.9-coreos-r1

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Azure

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher, external DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**

Update IPSec service cannot finish. Rancher loop drop-create IPSec service instance even all service instance complete update. Then rollback IPSec, the process non-stop too. Even all IPSec instance rollback success. Rancher still stop working IPSec service instance on every host and create a new one.

In Admin -> Processes, `stack.rollback` process always `TIMEOUT` and with following exception on `rancher-compose-executor`

```
io.cattle.platform.async.utils.TimeoutException: Timeout
	at io.cattle.platform.async.retry.impl.RetryTimeoutServiceImpl.retry(RetryTimeoutServiceImpl.java:41)
	at sun.reflect.GeneratedMethodAccessor401.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by anzersy** [comment]
After investigation of the issue. Got the summarization as below:

# Appearance
User tried to upgrade the IPSec service and got failed as unexpected, then user chose to roll back the IPSec service to ensure the online service going well and it did not work as well.

# Log
The key information which collected from ends was listed here to find the further solution.

**Rancher Server:**
2017-07-11 02:20:36,893 ERROR [530f9385-26d4-4e35-a4b1-9abb87d598f3:33735624] [instance:1875981->instanceHostMap:77245] [instance.start->(InstanceStart)->instancehostmap.activate] [] [cutorService-67] [c.p.e.p.i.DefaultProcessInstanceImpl] Agent error for [compute.instance.activate.reply;agent=381750]: Timeout getting IP address 
2017-07-11 02:20:36,893 ERROR [530f9385-26d4-4e35-a4b1-9abb87d598f3:33735624] [instance:1875981] [instance.start->(InstanceStart)] [] [cutorService-67] [i.c.p.process.instance.InstanceStart] Failed [1/5] to Starting for instance [1875981] 

**Rancher Agent:**
_INFO: Sending host-config applied 1-32a65fc33906cede2d730cd3dc87d949c4414d724a0839a2974d64cd7649f3e4
time="2017-07-11T00:39:03Z" level=info msg="Launching agent" 
time="2017-07-11T00:39:03Z" level=info msg="https://rancher.local.zhishinet.com/v11FEB96EC39C3FDECC7A2rUcAiyFtkMMFkBstcA4mvTS7PcP9TnA1kvCq95pQ" 
time="2017-07-11T00:39:03Z" level=info msg="Listening for events on https://rancher.local.zhishinet.com/v1" 
time="2017-07-11T00:39:03Z" level=info msg="launching hostapi" 
time="2017-07-11T00:39:03Z" level=info msg="Serialize compute requests: false, driver: overlay" 
time="2017-07-11T00:39:03Z" level=info msg="Initializing event router" workerCount=250 
time="2017-07-11T00:39:03Z" level=info msg="Starting event router." 
time="2017-07-11T00:39:04Z" level=info msg="Connection established" 
time="2017-07-11T00:39:04Z" level=info msg="Starting websocket pings" 
time="2017-07-11T00:39:04Z" level=info msg="Connecting to proxy." url="wss://rancher.local.zhishinet.com/v1/connectbackend?token=eyJhbGciOiJSUzI1NiJ9.eyJyZXBvcnRlZFV1aWQiOiJjOTQzYzdiMi1mZDg0LTQ4YjgtYTM4ZS02ZGQzMmJhNTBhODYiLCJzdWIiOiJjYXR0bGUiLCJraWQiOiJkZWZhdWx0IiwiaXNzIjoiaHR0cDpcL1wvY2F0dGxlLmlvIiwiZXhwIjoxNDk5NzMzODQ0LCJpYXQiOjE0OTk3MzM1NDR9.Pj_XMoucv2NMiF7Apc9qtHK1pzymHFoz9XO04v8GJ-lqRdZ-1V7N9gn78BLCcxfRGJxA3hTr7m_xqOTJ4Uh3zefCzmuQqMSk4IJ94G3zVGFJZE7mqfKH0QBFQddyf2vNKz0xQ3QQ2US1EO4X3ah437x2xQhRbtK7MYEFdq8XFebiEw8Wd7l3eJK0KPi1ZZRIzc69FsMBksQVlGzTdVSsThVeQNBJH0leGIeyy3FRMycV1IaQP5Q3xeaaiIcsRKEONrZU1-LZdYrEBsvMVbdJAiH9If0DlyUpTPQVeZTyNN865wkU3sl4eLQ9C4uTEx3stpKhGIasop0K0jL8_BiraQ" 
time="2017-07-11T00:57:32Z" level=error msg="Post https://rancher.local.zhishinet.com/v2-beta/publish: EOF"_ 

**Metadata:**
_time="2017-07-11T00:01:44Z" level=error msg="Failed to download and reload metadata: non-200 response 502: " 
time="2017-07-11T00:01:44Z" level=error msg="Error subscribing to events: websocket: bad handshake" subscribeUrl="wss://rancher.local.zhishinet.com/v1/subscribe?eventNames=ping&eventNames=config.update" 
time="2017-07-11T00:01:44Z" level=error msg="Got error response" responseHeaders=map[Content-Type:[text/html] Content-Length:[173] Connection:[keep-alive] Keep-Alive:[timeout=5] Server:[nginx/1.10.3] Date:[Tue, 11 Jul 2017 00:01:44 GMT]] status="502 Bad Gateway" statusCode=502 
time="2017-07-11T00:01:44Z" level=error msg="Error response: " 
time="2017-07-11T00:01:44Z" level=error msg="Exiting subscriber: websocket: bad handshake"_ 

**DNS:**
_time="2017-07-11T00:01:52Z" level=error msg="Error reading metadata version: Get http://localhost/2015-12-19/version?wait=true&value=677739-4f3c5c96fb170da7fa8781d4ac55192c&maxWait=5: net/http: request canceled"_ 

**Network-Manager:**
_time="2017-07-11T00:05:14Z" level=error msg="Error reading metadata version: Get http://169.254.169.250/2016-07-29/version?wait=true&value=677739-4f3c5c96fb170da7fa8781d4ac55192c&maxWait=5: net/http: request canceled"_ 

# Action
Checked the Kernel/Docker/Rancher on targeted hosts and found nothing special but the usage of CPU of external Mysql server was going to almost 100% while upgrading the IPSec service.

Suggested the user allocate more CPU resources to external Mysql server and ensure the cattle and metadata service work fine before upgrading the infrastructure service.

**Comment by snipking** [comment]
We use following step to stop rancher loop drop-create.

1. Find stack update/rollback process id in `Admin` -> `Processes`. Find stack & service id in rancher service API page.
2. Stop all rancher-server.
3. Connect to rancher database and update process record.
```
update process_instance set exit_reason='DONE', end_time=NOW() where id=xxxxxxxx;
```
4. Set service status to `active`
```
update service set state='active' where id=xxx;
```
5. Set stack status to `active`
```
update environment set state='active' where id=xxx;
```
6. Start all rancher-server

**Comment by snipking** [comment]
This issue has gone after we reboot all hosts.

**Comment by leodotcloud** [comment]
@snipking Please open a new issue if you are still having problems. Closing this one.

**Comment by yevheniidehtiar** [comment]
@snipking thanks for tip. I have same problem with my own stack. Manual updating records in cattle db helped me.
