### ISSUE TITLE
Rancher still not mysql galera cluster compatible

### ISSUE THREAD

**Issue by roffe** [rancher/rancher#9301]
**Rancher versions:**
rancher/server:

**Docker version: (`docker version`,`docker info` preferred)**
1.12.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
RancherOS 4.9.24-rancher

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher, External DB
Percona XtraDB GALERA Cluster 5.7

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cannot start rancher server so no environmnt can be made

**Steps to Reproduce:**
Create 3 node mysql galera cluster as recomended by rancher for resillience.

"For true HA, a replicated MySQL database with proper backups is recommended. Using Galera and forcing writes to a single node, due to transaction locks, would be an alternative."
https://www.percona.com/software/mysql-database/percona-xtradb-cluster

**Results:**

Err_empty_response from rancher master and nothing happends
[rancher database error.txt](https://github.com/rancher/rancher/files/1138261/rancher.database.error.txt)

**Comment by vincent99** [comment]
The log is 10mb of basically `cattle.DATABASECHANGELOG [needs a] explicit primary key with pxc_strict_mode = ENFORCING or MASTER`.  Have you tried adding one (or reducing strict mode)?

**Comment by roffe** [comment]
PXC_STRICT_MODE has been tried with both ENCORFING & MASTER as well as scaling the cluster down to 1 node instead of 3.

If i set it to permissive the whole cluster b0rks after a while as rancher is doing some non cluster safe table lockings it seems.

Also all writes are directed to a single node as per Rancher instructions

**Comment by roffe** [comment]
Rancher needs to provide a working example of a mysql HA setup certified to work with their product or remove the instructions regarding it.

**Comment by vincent99** [comment]
Galera and XtraDB are not the same thing.  Galera has no such strict mode and works fine, and XtraDB is mentioned nowhere in our docs.

**Comment by roffe** [comment]
that is correct. strict mode ensures non supported operations are blocked. like the ones you are doing.

https://www.percona.com/doc/percona-xtradb-cluster/LATEST/features/pxc-strict-mode.html

Percona XtraDB Cluster is an active/active high availability and high scalability open source solution for MySQL® clustering. It integrates Percona Server and Percona XtraBackup with the Codership Galera library of MySQL high availability solutions in a single package

**Please provide a Rancher certified solution for mysql HA with hot-standby / active failover**

Also please update the docs on your homepage to mention that Percona Cluster is NOT supported as it's a very popular product to create HA mysql clusters

**Comment by superseb** [comment]
Merging this into https://github.com/rancher/rancher/issues/9329, if you are able to test the proposed solution, that would help.
