### ISSUE TITLE
rancher scheduler crashes with no reason

### ISSUE THREAD

**Issue by KuroObi** [rancher/rancher#9302]
**Rancher versions:**
rancher/server: v1.6.3
rancher/agent: v1.2.5

**Infrastructure Stack versions:**
healthcheck: v0.3.1
ipsec: v0.1.1
network-services: v0.7.4
scheduler: v0.8.1

**Docker version:**
Server Version: 17.05.0-ce
**Operating system and kernel:**
Debian 4.9.30-2~bpo8
**Setup details:**
single node rancher server with external DB
**Environment Template:**
Cattle
**Steps to Reproduce:**
When roling out out 50 Container distributed Software into an environment with 9 rancher-agents the rancher scheduler crashes for no good reason with the following error message:

level=error msg="Exiting scheduler with error: <nil>"

In our environment it is reproducible, and causes massiv delays in deployment of templates into the environment, If i scale up the amount of rancher schedulers it happens to all of them at different times, regardless on which server it starts.

**Comment by superseb** [comment]
Did you try this on a supported version of Docker as well? This is where we run our test on: http://rancher.com/docs/rancher/v1.6/en/hosts/#supported-docker-versions

And can you specify what you are launching? Multiple stacks with multiple services? Maybe you have the yml files available so we can reproduce?

What is the status of the metadata service, what does the logging say?

Would be nice to grab some debug logs from the scheduler as well, if you upgrade the stack inside Infrastructure stacks you can enable debug to get some more information why it crashes.

**Comment by KuroObi** [comment]
We rolled back to docker 17.03.2-ce, still got the same problem.
it is a single stack with 42 services and 64 containers in this stack.
For the yml files, except for Cassandra and elastic search there all self build containers that basically just run.

Also we noticed that  in the process tabs on the master there are over 200 delayed jobs all time, mostly volumestoragepoolmap.remove, don't know if it has something to do with that.

Where can i get the status of the metadata service?

here is the output from the scheduling service:
time="2017-07-12T07:26:01Z" level=info msg="Received event: Name: scheduler.prioritize, Event Id: e6763c6c-c599-4fbb-9bc3-f5b4d8d32832, ResourceId : 1i162666" 
time="2017-07-12T07:26:01Z" level=info msg="Reply: Name: reply.7182482497770553762, PreviousIds: [e6763c6c-c599-4fbb-9bc3-f5b4d8d32832], ResourceId: 1i162666, Data: map[prioritizedCandidates:[211bc856-c54b-47aa-b274-9fbd73f190f8 ae06eb50-a11f-4431-b781-299cd6fb21ca 9dcb3827-c69a-429d-92af-76b889618d5c 6586df24-a5a1-4cf6-959b-bbca6aed0a98 01d46beb-a83d-4c60-b7ae-fd402843c2e8 a5d48563-b225-43ed-93ba-3276bbd8cac3 cc4ff6ab-dfdd-45e7-bb88-476e24adb856 01177991-44e2-46f5-b606-175175dcd737 52777f6b-0fc8-42b0-9451-b344e30e9739]]." 
time="2017-07-12T07:26:01Z" level=debug msg="Processing event." event={scheduler.reserve 70226f07-5617-4d4d-96e0-a4c2ae6ccf76    reply.7182482497770553762 1i162666 instance     map[schedulerRequest:map[hostID:211bc856-c54b-47aa-b274-9fbd73f190f8 resourceRequests:[map[resource:instanceReservation amount:1 type:computePool]] phase:instance.allocate context:[map[zoneId:1 stackId:<nil> networkContainerId:<nil> removeTime:<nil> dnsSearchInternal:xxxxxxx.rancher.internal,yyyyy.xxxxx.rancher.internal,rancher.internal removed:<nil> accountId:95 instanceTriggeredStop:stop domain:<nil> healthState:<nil> description:<nil> userdata:<nil> uuid:5fa40830-5bb0-482b-b582-5412601ff698 kind:container token:V8dPEJFDYI7bqmuOM7mjPEMpuKtKRIJ3qxBB2fwwLWqZ571Zap7xuthhPJ3ZQKYuXDlsw1eQVVW55XKntSQ system:false data:map[fields:map[vcpu:1 labels:map[io.rancher.service.deployment.unit:adcff518-b547-42a3-b24b-242cbdff62c9 io.rancher.project.name:xxxxx io.rancher.project_service.name:xxxxx/content-age-service-v1 io.rancher.container.hostname_override:container_name io.rancher.container.pull_image:always io.rancher.stack_service.name:xxxxx/yyyyyy io.rancher.service.launch.config:io.rancher.service.primary.launch.config io.rancher.stack.name:xxxxx io.rancher.service.hash:0bc49b4154a2b7eb91ac72ba149f13a30c54b38d] tty:false dataVolumes:[] serviceIndex:1 readOnly:false environment:map[CASSANDRA_SERVERS:cassandra YYYYY:yyyyy JVM_ARGS:-Xmx512m] transitioningProgress:32 allocatedIpAddress:<nil> dnsSearch:[xxxxx.rancher.internal yyyyyyyy.xxxxx.rancher.internal rancher.internal] networkIds:[30] startOnCreate:true networkMode:managed logConfig:map[] internalVolumes:[] publishAllPorts:false memory:5.36870912e+08 stdinOpen:false privileged:false dataVolumeMounts:map[] imageUuid:docker:nexus.zzzzzz.com:5001/aaaa/yyyyyyy:SNAPSHOT dns:[169.254.169.250] transitioningMessage:Scheduling]] created:1.499844358e+12 name:xxxxx-yyyyyyy-v1-1 nativeContainer:false healthUpdated:<nil> state:starting version:0 dnsInternal:169.254.169.250 agentId:<nil> deploymentUnitUuid:adcff518-b547-42a3-b24b-242cbdff62c9 serviceId:<nil> firstRunning:<nil> registryCredentialId:139 hostname:xxxxx-yyyyyyyy-v1-1 memoryReservation:<nil> allocationState:activating id:162666 memoryMb:<nil> compute:<nil> serviceIndexId:59726 milliCpuReservation:<nil> externalId:<nil> startCount:0 createIndex:4 imageId:162602]]]] 1.499844361666e+12} 
time="2017-07-12T07:26:01Z" level=info msg="Received event: Name: scheduler.reserve, Event Id: 70226f07-5617-4d4d-96e0-a4c2ae6ccf76, ResourceId : 1i162666" 
time="2017-07-12T07:26:01Z" level=info msg="Reserving [{Resource:instanceReservation Amount:1}] for 211bc856-c54b-47aa-b274-9fbd73f190f8. Force=false" 
time="2017-07-12T07:26:01Z" level=info msg="New pool amount on host 211bc856-c54b-47aa-b274-9fbd73f190f8: instanceReservation total: 1000000 used: 20." 
time="2017-07-12T07:26:01Z" level=info msg="Reply: Name: reply.7182482497770553762, PreviousIds: [70226f07-5617-4d4d-96e0-a4c2ae6ccf76], ResourceId: 1i162666, Data: map[]." 
time="2017-07-12T07:26:02Z" level=debug msg="Processing event." event={scheduler.reserve b50fe976-448f-4a60-b4ab-48c270fd93bd    reply.145298030699605309 1i162666 instance     map[schedulerRequest:map[phase:instance.start context:[map[compute:<nil> domain:<nil> description:<nil> accountId:95 uuid:5fa40830-5bb0-482b-b582-5412601ff698 agentId:<nil> hostname:xxxxx-yyyyyy removeTime:<nil> dnsSearchInternal:xxxxx.rancher.internal,yyyyyy.xxxxx.rancher.internal,rancher.internal memoryMb:<nil> kind:container deploymentUnitUuid:adcff518-b547-42a3-b24b-242cbdff62c9 memoryReservation:<nil> data:map[fields:map[dnsSearch:[xxxxx.rancher.internal yyyyyy.xxxxx.rancher.internal rancher.internal] imageUuid:docker:nexus.zzzzzz.com:5001/aaaaa/yyyyy:SNAPSHOT transitioningProgress:32 allocatedIpAddress:<nil> privileged:false environment:map[JVM_ARGS:-Xmx512m CASSANDRA_SERVERS:cassandra YYYYYYY:yyyyyy] dataVolumeMounts:map[] dns:[169.254.169.250] logConfig:map[] vcpu:1 stdinOpen:false startOnCreate:true dataVolumes:[] internalVolumes:[] publishAllPorts:false tty:false networkIds:[30] labels:map[io.rancher.stack.name:xxxxx io.rancher.container.pull_image:always io.rancher.service.launch.config:io.rancher.service.primary.launch.config io.rancher.project.name:xxxxx io.rancher.project_service.name:xxxxx/yyyyy io.rancher.container.hostname_override:container_name io.rancher.service.hash:0bc49b4154a2b7eb91ac72ba149f13a30c54b38d io.rancher.service.deployment.unit:adcff518-b547-42a3-b24b-242cbdff62c9 io.yyyyyyyyy:xxxxx/content-age-service-v1] transitioningMessage:Scheduling networkMode:managed serviceIndex:1 memory:5.36870912e+08 readOnly:false]] version:0 userdata:<nil> serviceId:<nil> stackId:<nil> firstRunning:<nil> nativeContainer:false id:162666 zoneId:1 startCount:0 registryCredentialId:139 instanceTriggeredStop:stop created:1.499844358e+12 removed:<nil> healthState:<nil> networkContainerId:<nil> externalId:<nil> milliCpuReservation:<nil> system:false dnsInternal:169.254.169.250 createIndex:4 imageId:162602 healthUpdated:<nil> state:starting name:xxxxx-yyyyyy serviceIndexId:59726 token:V8dPEJFDYI7bqmuOM7mjPEMpuKtKRIJ3qxBB2fwwLWqZ571Zap7xuthhPJ3ZQKYuXDlsw1eQVVW55XKntSQ allocationState:inactive]] hostID:211bc856-c54b-47aa-b274-9fbd73f190f8 resourceRequests:[map[resource:instanceReservation amount:1 type:computePool]]]] 1.499844362606e+12} 
time="2017-07-12T07:26:02Z" level=info msg="Received event: Name: scheduler.reserve, Event Id: b50fe976-448f-4a60-b4ab-48c270fd93bd, ResourceId : 1i162666" 
time="2017-07-12T07:26:02Z" level=info msg="Reserving [] for 211bc856-c54b-47aa-b274-9fbd73f190f8. Force=false" 
time="2017-07-12T07:26:02Z" level=info msg="Reply: Name: reply.145298030699605309, PreviousIds: [b50fe976-448f-4a60-b4ab-48c270fd93bd], ResourceId: 1i162666, Data: map[]." 
time="2017-07-12T07:26:02Z" level=debug msg="No changes in metadata version" 
time="2017-07-12T07:26:17Z" level=info msg="Hit websocket pong timeout. Last websocket ping received at 2017-07-12 07:26:02.12061893 +0000 UTC. Closing connection." 
time="2017-07-12T07:26:17Z" level=error msg="Exiting scheduler with error: <nil>"

**Comment by niusmallnan** [comment]
Fixed by https://github.com/rancher/rancher/issues/9306

**Comment by superseb** [comment]
Can you verify it's fixed in the latest version and report back if not? Thanks
