### ISSUE TITLE
How can i check and solve cross host communication issues ?

### ISSUE THREAD

**Issue by artemus717** [rancher/rancher#9308]
I am dealing with health check stuck in initializing state problems.
And in official faqs , this maybe cause by cross host communication.

**Rancher versions:**
rancher/server: 1.5.10
rancher/agent: 1.2.2

**Infrastructure Stack versions:**
healthcheck:0.2.3
vxlan:0.11.2
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
1.12.6
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
CentOS 7.2 3.10.514
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**

**Results:**

**Comment by aemneina** [comment]
if you ran the following from each ipsec router container, you could get a good indication of which leg, or all, are broken:

```
for i in `curl -s rancher-metadata/latest/self/service/containers/| cut -f1 -d=` ; do ping -c2 `curl -s curl rancher-metadata/latest/self/service/containers/$i/primary_ip` ; done
```

**Comment by artemus717** [comment]
@aemneina thanks, i find it is a bug mentioned in #8635
and i will try Network Diagnostics Stack.
