### ISSUE TITLE
Have network settings in kubernetes template and addon starter configurable

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#9310]
There's a lot of hard coded values for the default ipsec network. When one changes the ipsec default cidr, that requires a lot of modifications to the k8s template. It'd be nice to have a variable we could pass in that would change the ipsec subnet/cidr values in the k8s template.

**Comment by deniseschannon** [comment]
@galal-hussein Can you work with @alena1108 to see what repos might need to be looked at?

**Comment by galal-hussein** [comment]
@moelsayed Can be tested with master and kubernetes `v1.8.0-beta.1-rancher2-etcdv2`, the following cases should be tested:

- Create a new k8s template and change IPSEC catalog configuration to use different pod cidr, make sure that pods can be started normally with the new pod subnet.

- Create a new k8s template and change k8s configuration, and change the `Service Cluster IP CIDR`, `KubeDNS cluster IP`, and `KubeAPI cluster IP for TLS certificate` to a new service cidr (for example: 10.49.0.0/16, 10.49.0.12, and 10.49.0.1 respectively), and make sure that new services are created in this cidr and all addons are working correctly, and pods/rc/deployments/services are running normally.

- Create new k8s template with both ipsec changes and service cluster changes, and make sure these cidrs don't overlap.

**Comment by moelsayed** [comment]
@galal-hussein All three cases passed with no problems. Thank you.
