### ISSUE TITLE
database crash

### ISSUE THREAD

**Issue by rps35** [rancher/rancher#9312]
*Describe your issue here*

problem with database always crashed
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.5.5` Cattle: `v0.178.3` UI: `v1.5.8` |
|Access|`github` |
|Orchestration|`Cattle`|
|Route|`stack.code`|

**Comment by rps35** [comment]
my database crashed with true password always stopped

**Comment by rps35** [comment]
i dont find the solution my database crashed all time do you have solution

**Comment by aemneina** [comment]
@rps35 we'll probably need a bit of info to move this issue forward. Maybe rancher server logs to start. Logs from the db server could also be helpful. maybe the specs (server/OS/config) of said db server could also be of use.

**Comment by superseb** [comment]
Please comment if you need more help on this.
