### ISSUE TITLE
external links aren't applied, occasionally, when adding new stack from compose files

### ISSUE THREAD

**Issue by xaka** [rancher/rancher#9313]
**Rancher versions:**
rancher/server: 1.6.3

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
- add stack
- paste docker/rancher compose files with `external_links`

**Results:**
- occasionally, more often for stacks with 50+ services, external links get lost and nothing is linked at the end; deleting and re-adding stack using same compose files helps sometimes, but almost never for stacks with 50+ services

**Comment by xaka** [comment]
ping! we're blocked by this as we cannot migrate to latest rancher from very old release by exporting/importing compose files

**Comment by deniseschannon** [comment]
@xaka Do you have example files that we could use to test it out? You're using the add stack functionality with compose files in the UI, correct?

**Comment by xaka** [comment]
@deniseschannon you're correct; unfortunately it's challenging to share our files as those include private services that are based on private docker images

what i'd suggest:
- create 3 random stacks each running basic nginx service
- create 4th stack with 50 random basic nginx services each externally linking first 3 stacks

i bet it should be enough to catch race condition

**Comment by grabekm90** [comment]
I used to have the same issue. When I add an external link to a not existing service, all external links disappear and the linked service cannot be resolved using the alias.
Try to check whether all services exist.

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it

**Comment by grabekm90** [comment]
Reproduced with Rancher Server v1.6.22:
When I add an external link to a not existing service, all external links disappear and any other linked existing service cannot be resolved using its alias.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches. Please let me know if you think this issue is critical.
