### ISSUE TITLE
OpenLDAP access control without "Service Account" (anonymous bind)

### ISSUE THREAD

**Issue by mash-graz** [rancher/rancher#9314]
**Rancher versions:**
rancher/server: 1.6.3

why doesn't ranchers OpenLDAP support work without service account, if the access to all the relevant information is also available by anonymous bind within the local network? only password verification needs an explicit binding on our LDAP setup, but in this case you are using the affected user identification or root-bind, all other LDAP browsing could be handled with anonymous binding just as well.

can we bypass this mandatory service account fields in ranchers OpenLDAP access control setup to use anonymous bind?

**Comment by mash-graz** [comment]
while looking for a solution i found two other tickets concerning the same topic:
#2372 #5669

nevertheless it still looks like an open issue. :(

**Comment by mash-graz** [comment]
see RFC 4513 section 5.1.1, 5.1.2 and  B.1.2  for a standard compliant LDAP .

 https://tools.ietf.org/html/rfc4513#section-5.1.1

in appendix B.1.2 it refers to sect. 4.2.2 of RFC 2251: 

B.1.2.  Section 4.2.2 ("Authentication and Other Security Services")

   - RFC 2251 states that anonymous authentication MUST be performed
     using the simple bind method.  **This specification defines the
     anonymous authentication mechanism of the simple bind method and
     requires all conforming implementations to support it.**  Other
     authentication mechanisms producing anonymous authentication and
     authorization state may also be implemented and used by conforming
     implementations.

**Comment by superseb** [comment]
This is an open request: https://github.com/rancher/rancher/issues/2372, closing as duplicate.

**Comment by mash-graz** [comment]
> This is an open request: #2372, closing as duplicate.

as long as it gets solved finally, that's fine to me.
