### ISSUE TITLE
Rancher EBS continues to create new volumes if IAM permissions are incorrect

### ISSUE THREAD

**Issue by oskapt** [rancher/rancher#9315]
**Summary:**

If a service using an EBS volume fails to start because of IAM permissions problems when creating the volume, the volume is not deleted.  

**Steps to Reproduce:**

- Create an IAM user with a policy missing `ec2:CreateTags` like:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Stmt1499811186000",
            "Effect": "Allow",
            "Action": [
                "ec2:AttachVolume",
                "ec2:CreateVolume",
                "ec2:CreateSnapshot",
                "ec2:DeleteVolume",
                "ec2:DescribeVolumeAttribute",
                "ec2:DescribeVolumesModifications",
                "ec2:DescribeVolumeStatus",
                "ec2:DescribeVolumes",
                "ec2:DescribeSnapshots",
                "ec2:DescribeTags",
                "ec2:DetachVolume",
                "ec2:ModifyVolume",
                "ec2:ModifyVolumeAttribute"
            ],
            "Resource": [
                "*"
            ]
        }
    ]
}
```
- use this user's keys with rancher-ebs
- start a new service that creates an EBS volume
- the service will fail with an error about not having the CreateTags permission
- the service will continue to restart
- every time the service restarts, it will create another EBS volume
- these volumes are never deleted and will incur AWS charges if left around

**Comment by ekristen** [comment]
I've seen this error too.

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
