### ISSUE TITLE
 Agent cloud provider for aliyun

### ISSUE THREAD

**Issue by hippper** [rancher/rancher#9318]
Currently，our latest version of agent does not support aliyun cloud provider。We should add this feature。

**Comment by longwuyuan** [comment]
I could not add a host.
I tried public-ipaddress with ssl termination.
I tried lan ipaddress without SSL.
I just stumbled on this issue so just requesting to know if this issues means adding a host to rancher is not possible if the host is a vm on Aliyun Cloud.

**Comment by hippper** [comment]
@longwuyuan  no, this issues just add the feature of getting host information from Aliyun cloud VM。Currently，rancher can support adding a host with a vm on Aliyun cloud。Maybe you can get help from rancher docs 【http://rancher.com/docs/rancher/v1.6/en/hosts/】

**Comment by hippper** [comment]
@longwuyuan sorry，http://rancher.com/docs/rancher/v1.6/en/hosts/

**Comment by yasker** [comment]
Merged. Need to test against both AWS and Aliyun after release.

**Comment by kingsd041** [comment]
@aiwantaozi 
I use the agent:v1.6 branch to test, add Aliyun and AWS host. 
In the "Edit Host" page, I can get "provider", "region", "zone" lables.

**Comment by yasker** [comment]
@kingsd041 Change has been merged into Rancher v1.6.11-rc1.

**Comment by kingsd041** [comment]
@yasker @aiwantaozi  

**Rancher versions:**
rancher/server: v1.6.11-rc2
rancher/agent: v1.2.7-rc2
**Docker version:**
17.06.2-ce

Test passed.
