### ISSUE TITLE
Has anybody  deployed kubernetes on rancher 1.6.3 successfully?

### ISSUE THREAD

**Issue by joew2016** [rancher/rancher#9320]
Hi:
    Has anybody deployed kubernetes on rancher 1.6.3 successfully ?  I want to test kubernetes 1.6 with rancher 1.6.3, but failed!  It takes much time to debug this problem. So, I want to know anybody who has deployed kubernetes 1.6 on rancher 1.6.3 successfully, could you please tell me what docker version , os version and rancher 1.6.3 rc do you use?
Thanks very much!!!

**Comment by superseb** [comment]
We can help you if you provide us with the details in the issue template? But if you want to know, we test on Ubuntu 16.04 and upstream Docker 1.12.6 among others, so that should help you out. Please update your post with your settings so we can help you out and we can reopen.
