### ISSUE TITLE
Is there anyone here who already deployed rancher on production environment?

### ISSUE THREAD

**Issue by joew2016** [rancher/rancher#9321]
Hi:
    We are evaluating rancher for production use with kubernetes deployed now. Is there anyone here who already deployed rancher on production environment ?

**Comment by vincent99** [comment]
Lots of people have, but issues are for issues and not an appropriate place for casual discussion.  

Forum: http://forums.rancher.com
Slack: https://slack.rancher.io
IRC: #rancher on freenode
StackOverflow, Reddit, etc.
