### ISSUE TITLE
Have builtin feature to clean up unused images

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#9323]
**Rancher versions:**
rancher/server: 1.6.3
rancher/agent: 1.2.5

Have a janitor like feature built into rancher.

**Comment by superseb** [comment]
Is this https://github.com/rancher/rancher/issues/8685 ?

**Comment by aemneina** [comment]
could be... seems to be closed and no catalog item present in the community/library catalogs.

**Comment by aemneina** [comment]
after learning how to read, i see its slated for 2.0. will close this out.
