### ISSUE TITLE
couldn't bring up network failed to find plugin rancher-bridge if /opt/cni/bin/rancher-bridge is a directory

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#9324]
**Rancher versions:**
rancher/server: 1.6.3
rancher/agent: 1.2.5

**Infrastructure Stack versions:**
healthcheck:v0.3.0
ipsec: v0.1.1
network-services:v0.2.2
scheduler:v0.6.1

**Docker version: (`docker version`,`docker info` preferred)**
any
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
any
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
any
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node, internal DB
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
1) Remove `/opt/cni/bin/rancher-bridge` and create it as a directory 
(```docker exec -ti `docker ps -q -a --filter 'label=io.rancher.project_service.name=network-services/network-manager'` sh -c "rm -rf /opt/cni/bin/rancher* && mkdir /opt/cni/bin/rancher-bridge"```)
2) Remove ipsec containers
(```docker rm -f `docker ps -q -a --filter 'label=io.rancher.stack.name=ipsec'` ```)
**Results:**
It never recovers

**Comment by leodotcloud** [comment]
@niusmallnan The fix for this would be in `network-manager`. Before generating the binaries, check if `rancher-bridge` is a directory and delete it.

**Comment by niusmallnan** [comment]
@superseb 
I would like to know how `rancher-bridge` will become a directory If you do not have to manually create it.

**Comment by leodotcloud** [comment]
Fixed in `network-services: v0.2.6` with `rancher/network-manager:v0.7.8`.

**Comment by sangeethah** [comment]
Tested with rancher-server version - v1.6.8-rc4 using network-services: v0.2.6 with rancher/network-manager:v0.7.8.

1. From network-manager container , remove /opt/cni/bin/rancher-bridge and create it as a directory.
2. Delete ipsec container that is running on the same host as the network-manager container where rancher-bridge directory was created.

New ipsec container is able to start successfully.

Following logs are seen in network-manager container where existing rancher-bridge directory gets deleted and  rancher-bridge file gets created:

```8/22/2017 4:05:32 PMtime="2017-08-22T23:05:32Z" level=info msg="/opt/cni/bin/rancher-bridge is a dir, remove it"```
