### ISSUE TITLE
Rancher 1.6.3 allows to expose the same port on the same host from multiple containers (impossible configuration)

### ISSUE THREAD

**Issue by iltish** [rancher/rancher#9325]
**Rancher versions:**
rancher/server: 1.6.3
rancher/agent: 1.2.5

**Infrastructure Stack versions:**
healthcheck: 0.3.0
ipsec: 0.1.1
network-services: 0.2.2
scheduler: 0.6.1
kubernetes (if applicable): N/A

**Docker version: (`docker version`,`docker info` preferred)**
```
root@rancher-client:~# docker version
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:23:31 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:19:04 2017
 OS/Arch:      linux/amd64
 Experimental: false
root@rancher-client:~# docker info
Containers: 11
 Running: 11
 Paused: 0
 Stopped: 0
Images: 31
Server Version: 17.06.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 121
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.8.0-56-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.613GiB
Name: rancher-client
ID: IZLZ:4FUS:7N4I:M6OP:WN7K:QR7R:AQI3:WVVW:JGO2:HSNA:5KKL:TK7Y
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
root@rancher-client:~# cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
root@rancher-client:~# uname -r
4.8.0-56-generic

```
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
n1-standard-1 (1 vCPU, 3.75 GB memory) on GCE, but the same issues is reproducible with other environment configurations.

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
`docker run -d --restart=unless-stopped -p 80:8080 rancher/server`

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
1.  Add single host (**rancher-client**) to rancher
2.  Create and start two nginx containers each with:
   a.  Scheduling set to "Run all containers on a specific host" (**rancher-client**)
   b.  Exposed port 80:80

**Results:**
Rancher displays that **both** nginx are successfully running with the same port on the same host (**rancher-client**).

Expected result: displayed configuration is impossible and rancher should display error that it's not possible to schedule two containers on the same host with the same exposed port.

![image](https://user-images.githubusercontent.com/23225158/28141901-766451e8-6713-11e7-9d95-682d57108633.png)

![image](https://user-images.githubusercontent.com/23225158/28141945-a9e4c138-6713-11e7-9c11-b042c4de2bc5.png)

**Comment by matq007** [comment]
Any update so far? This would be a nice feature to have.

**Comment by cjellick** [comment]
https://github.com/rancher/rancher/issues/3323 might address this, depending on how we decide to implement it.

**Comment by aldarionsevero** [comment]
Thinking without this feature, what is the best way of addressing this? Force specific hosts using the hosts labels? But forcing this reduces a lot of what the Rancher HA service does, right?

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it

**Comment by marcinpraczko** [comment]
We are having Rancher version 1.6.16 and this is also visible:
Result from Host - which allowed expose the same PORT into two different containers

```bash
iptables -nvL -t nat | grep docker0 | grep -E "tcp dpt:80 "
    0     0 DNAT       tcp  --  !docker0 *       0.0.0.0/0            0.0.0.0/0            tcp dpt:80 to:10.42.118.68:8080
    0     0 DNAT       tcp  --  !docker0 *       0.0.0.0/0            0.0.0.0/0            tcp dpt:80 to:10.42.189.31:80
```
