### ISSUE TITLE
Cattle should detect obvious problems when new hosts are added

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#9326]
When adding hosts to cattle some of the obvious errors should be logged and probably notify the User.

Example:
- Host 1 and Host 2 have the same source IP address detected by cattle.
- Host source IP address is `172.17.0.1`

Related:
https://github.com/rancher/rancher/issues/7220

Possibly one more area where cattle can become more intelligent? Link: https://github.com/rancher/rancher/issues/9326

**Comment by furkanmustafa** [comment]
Additional error case that should be (& can be) detected by cattle IMO;

 - Hosts cannot communicate between each other (500/4500 when ipsec networking used)

**Comment by yasker** [comment]
It affects user experiences greatly as a recent customer case @pengjiang80 debugged.

**Comment by yasker** [comment]
Also, we shouldn't allow hosts to be added with the existing IP.

**Comment by niusmallnan** [comment]
When adding a host as an agent, the agent can get `DETECTED_CATTLE_AGENT_IP` via `registration.sh` script from cattle.
```
#!/bin/sh

export CATTLE_REGISTRATION_ACCESS_KEY="${CATTLE_REGISTRATION_ACCESS_KEY}"
export CATTLE_REGISTRATION_SECRET_KEY="${CATTLE_REGISTRATION_SECRET_KEY}"
export CATTLE_URL="${CATTLE_URL}"
export DETECTED_CATTLE_AGENT_IP="${CATTLE_AGENT_IP}"
```
If we use Rancher v1.6.x,  the `DETECTED_CATTLE_AGENT_IP` is here, https://github.com/rancher/cattle/blob/v1.6/code/implementation/register/src/main/java/io/cattle/platform/register/api/RegisterScriptHandler.java#L56
```
        .....
        tokens.put("CATTLE_AGENT_IMAGE", IMAGE.get());
        tokens.put("CATTLE_AGENT_IP", request.getClientIp());
        .....
```

Then in some scenarios, the `DETECTED_CATTLE_AGENT_IP` will be repeated, such as:
- hosts behind the NAT
- User input is repeated

So what we should do is, when the agent uses DETECTED_CATTLE_AGENT_IP as the agent IP, should terminate the registration process once `DETECTED_CATTLE_AGENT_IP` is repeated, or give some friendly hints.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
