### ISSUE TITLE
[RFE] deprecate rancher-ingress-controller altogether

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#9327]
There's the ability to disable the rancher ingress controller in rancher 1.6.3/k8s 1.6.6. This is to signal the removal of the rancher ingress controller in liu of what kubernetes provides out of the box for ingress providers.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
