### ISSUE TITLE
websocket-proxy & scheduler memory leak

### ISSUE THREAD

**Issue by eerootsus** [rancher/rancher#9332]
**Rancher versions:**
rancher/server: 1.6.3-rc7
rancher/agent: 1.2.5

**Docker version: (`docker version`,`docker info` preferred)**
```
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 2
Server Version: 17.03.2-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 32
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-78-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.859 GiB
Name: XXX
ID: HEEP:BXPK:PRSI:UZVU:5T33:A2PM:4OQ5:TJOR:HE4K:BHY7:QMYD:YTDF
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

```
4.4.0-78-generic
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
OpenStack

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node, no HA, externdal database

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Unknown

**Results:**
Slowly host machine memory was exhausted until oom killer stepped in:
```
[198255.658175] Out of memory: Kill process 6066 (websocket-proxy) score 537 or sacrifice child
[198255.660414] Killed process 6066 (websocket-proxy) total-vm:2463264kB, anon-rss:2170636kB, file-rss:0kB
```

Agents reported:
```
time="2017-07-13T11:53:43Z" level=error msg="Received error reading from socket. Exiting." error="websocket: close 1006 (abnormal closure): unexpected EOF" 
time="2017-07-13T11:53:43Z" level=error msg="websocket: close 1006 (abnormal closure): unexpected EOF" 
```
Obviously due to the server instance being restarted. 

No meaningful logs from the server container.

Currently downgraded to stable (1.6.2), will monitor how this handles.

**Comment by eerootsus** [comment]
Seeing same memory exhaustion with 1.6.2 - about 1GB of memory in 6 hours.

Any suggestions how to debug?

**Comment by eerootsus** [comment]
This seems to be related to scheduler (v0.8.1)

Scheduler is constantly doing a fair bit of networking:
![screenshot 2017-07-14 08 02 31](https://user-images.githubusercontent.com/5171437/28198995-f9fb5468-686a-11e7-8bce-e97a5057fbb4.png)

And every time there is metadata update the traffic peaks and memory is used up.
![screenshot 2017-07-14 08 03 34](https://user-images.githubusercontent.com/5171437/28198996-fa024066-686a-11e7-830d-61d824592ba4.png)

And the received metadata update seems to be slightly larger and larger every time. Even though nothing has been changed in the environment.


We have four environments and in every one I'm seeing scheduler being moved between hosts. The scheduler network usage and memory usage slowly creeps higher and higher until something kills it. Killing the scheduler seems to resolve memory issues on the rancher-server, but not always and the websocket-proxy gets killed by oom killer.

**Comment by eerootsus** [comment]
Two hours later scheduler memory and network have slowly increased.
![screenshot 2017-07-14 09 12 07](https://user-images.githubusercontent.com/5171437/28200407-931a4ccc-6874-11e7-9bf5-8794bd5bed0a.png)
![screenshot 2017-07-14 09 11 31](https://user-images.githubusercontent.com/5171437/28200408-933b5408-6874-11e7-88ed-e6752c255757.png)

This is network on Zabbix from this environment hosts. Evidence slowly more data is moved from scheduler until it gets killed and moved to another host.
![screenshot 2017-07-14 08 53 29](https://user-images.githubusercontent.com/5171437/28200435-b97a32b0-6874-11e7-83e9-5322c95f37f3.png)

**Comment by eerootsus** [comment]
@StrongMonkey Super, thanks! Sounds exactly right.

**Comment by eerootsus** [comment]
Exactly as in #9306 - establised network connections increase at about a rate of 3 connections in 2s.

Will try development catalogue.

**Comment by deniseschannon** [comment]
Fix available in the `v1.6-development` branch of catalog with `scheduler:v0.8.2`

**Comment by sangeethah** [comment]
Tested with rancher-server 1.6.3 and scheduler v0.8.2 in the v1.6-development branch.

Memory used by scheduler container remains at ~ 10 MB when automation runs relating to creating/scaling/deleting services where executed on the rancher-sever.


When similar tests where run using scheduler v0.8.1 , Memory used by scheduler container increased up to ~150 MB.

**Comment by eerootsus** [comment]
Yes, I can confirm scheduler version 0.8.2 fixes the issue and I had no problems over the weekend.

Cheers and thanks!
