### ISSUE TITLE
Kubernetes UI failing to start correctly due to authentication error with rancher-kubernetes-auth when upgrading from 1.6.2 to 1.6.3

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#9333]
**Rancher versions:**
rancher/server: v1.6.2 --> v1.6.3

kubernetes (if applicable): v1.5.4 --> v1.6.6

**Docker version: (`docker version`,`docker info` preferred)**
1.12
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
RancherOS 1.0.3
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes
**Steps to Reproduce:**
- Start Kubernetes 1.5.4 on Rancher 1.6.2 with ROS 1.0.3 and Docker 1.12
- Enable authentication
- Upgrade rancher server to 1.6.3
- Upgrade kubernetes to 1.6.6

**Results:**

Rancher kubernetes agent and Rancher ingress controllers are failing to start correctly, Both services are showing authentication errors:

rancher-kubernetes-agent:
```
7/13/2017 3:37:14 PMtime="2017-07-13T12:37:14Z" level=info msg="Connecting to event stream." url="wss://kubernetes.kubernetes.rancher.internal:6443/apis/extensions/v1beta1/namespaces?watch=true"
7/13/2017 3:37:14 PMtime="2017-07-13T12:37:14Z" level=error msg="Couldn't retrieve list of objects, status code: 401"
7/13/2017 3:37:14 PMtime="2017-07-13T12:37:14Z" level=error msg="kubernetes Sync and stream listener exited with error: Couldn't retrieve list of objects, status code: 401"
7/13/2017 3:37:14 PMtime="2017-07-13T12:37:14Z" level=info msg=Exiting.
```
Kube API logs:
```
7/13/2017 3:52:31 PME0713 12:52:31.679176       1 authentication.go:58] Unable to authenticate the request due to an error: [invalid bearer token, [invalid bearer token, Post http://rancher-kubernetes-auth/: dial tcp 10.42.241.165:80: i/o timeout]]
7/13/2017 3:52:35 PME0713 12:52:35.512105       1 authentication.go:58] Unable to authenticate the request due to an error: [invalid bearer token, [invalid bearer token, Post http://rancher-kubernetes-auth/: dial tcp 10.42.241.165:80: i/o timeout]]
7/13/2017 3:52:35 PME0713 12:52:35.680046       1 authentication.go:58] Unable to authenticate the request due to an error: [invalid bearer token, [invalid bearer token, Post http://rancher-kubernetes-auth/: dial tcp 10.42.241.165:80: i/o timeout]]
7/13/2017 3:52:39 PME0713 12:52:39.523605       1 authentication.go:58] Unable to authenticate the request due to an error: [invalid bearer token, [invalid bearer token, Post http://rancher-kubernetes-auth/: dial tcp 10.42.241.165:80: i/o timeout]]
7/13/2017 3:52:39 PME0713 12:52:39.680223       1 authentication.go:58] Unable to authenticate the request due to an error: [invalid bearer token, [invalid bearer token, Post http://rancher-kubernetes-auth/: dial tcp 10.42.241.165:80: i/o timeout]]
7/13/2017 3:52:43 PME0713 12:52:43.522781       1 authentication.go:58] Unable to authenticate the request due to an error: [invalid bearer token, [invalid bearer token, Post http://rancher-kubernetes-auth/: dial tcp 10.42.241.165:80: i/o timeout]]
7/13/2017 3:52:43 PME0713 12:52:43.683835       1 authentication.go:58] Unable to authenticate the request due to an error: [invalid bearer token, [invalid bearer token, Post http://rancher-kubernetes-auth/: dial tcp 10.42.241.165:80: i/o timeout]]
```

**Comment by aemneina** [comment]
@galal-hussein was the workaround to this restarting rancher-kubernetes-auth service?

**Comment by galal-hussein** [comment]
@aemneina Yes i restarted rancher-kubernetes-auth, and then both rancher kubernetes agent and ingress controller started successfully.

**Comment by joshwget** [comment]
Do you suspect this is a RancherOS only issue? It seems like this would affect any distro.

**Comment by moelsayed** [comment]
I hit the same issue with the follow parameters:
* OS: RHEL 7.3
* Docker 1.12.6 upstream
* Upgrading from rancher 1.6.5 -> 1.6.6-rc2

Steps to reproduce:
* Install rancher 1.6.5
* Enable authentication
* Upgrade rancher 1.6.5 to 1.6.6-rc2
* Upgrade IPsec infrastructure stack
* upgrade Network-Services infrastructure stack

**Comment by joshwget** [comment]
Checking out the setup from @moelsayed I noticed that it's the UI that has a bad token. Every refresh of the UI causes a new line in the API server logs. Cluster health other than this seems fine.

**Comment by deniseschannon** [comment]
Closing as this is most likely the dangling veth issue seen in https://github.com/rancher/rancher/issues/9481#issuecomment-318778631

As the setups are now gone, we will close for now and re-open if we have determined that the dangling veth is not the issue and something else should be looked at.
