### ISSUE TITLE
Certify gitlab charts

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#9334]
Certify gitlab charts with k8s 1.6.

```
https://github.com/kubernetes/charts/tree/master/stable/gitlab-ce
https://docs.gitlab.com/ee/install/kubernetes/gitlab_chart.html
https://docs.gitlab.com/ce/install/kubernetes/gitlab_chart.html
https://about.gitlab.com/installation/
```

**Comment by moelsayed** [comment]
I managed to successfully deploy the gitlab chart on Rancher 1.6.3 with k8s 1.6.6. 
For the deployment to succeed, you will need to have a storage provisioner defined on you k8s cluster. For the purpose of this deployment, I used [nfs-client-provisioner](https://github.com/kubernetes-incubator/external-storage/tree/master/nfs-client).

The gitlab chart is highly configurable, however to get a basic working deployment working you only need to configure the following parameters in values.yaml

*  externalUrl: This should be a FQDN.
* storageClass: The chart needs 5 persistent storage volumes to work. You should set this variable for all volumes in the values.yaml file. Even if you have a default storageClass defined in k8s, you need to explicitly set this variable to "default".

Steps to deploy are:

* Add [gitlab's chart repo](https://gitlab.com/charts/charts.gitlab.io) to your helm setup.
```
$ helm repo add gitlab https://charts.gitlab.io
$ helm init --client-only
```
* Download the gitlab chart
```
$ helm fetch gitlab/gitlab --untar
```
* Download chart dependencies
```
$ cd gitlab
$ helm dep update
$ helm dep build
```
* Deploy the gitlab chart
```
$ helm install --namespace <NAMESPACE> --name gitlab ./
```

**Comment by moelsayed** [comment]
For testing, I will be using basic scenarios form the [Getting Started](https://docs.gitlab.com/ce/intro/README.html) guide.
