### ISSUE TITLE
[SEC] Implement Checksums

### ISSUE THREAD

**Issue by guusverbeek** [rancher/rancher#9336]
Hi All,

For example on https://github.com/rancher/os-services/blob/master/images/20-iscsi/build.sh

You download open-iscsi using `

VERSION="0.97"
  | curl -sL https://github.com/open-iscsi/open-isns/archive/v${VERSION}.tar.gz > open-isns${VERSION}.tar.gz
  | tar zxvf open-isns${VERSION}.tar.gz
  | rm -rf /dist/isns
  | mv open-isns-${VERSION}/ /dist/isns/
 

`
This poses a risk as everyone could potentially pose as https://github.com/*

By implementing a checksum we can be more certain that the binary that will compile is actually the binary that we want to compile.

Best Regards,

Guus Verbeek

**Comment by superseb** [comment]
Hi Guus,

probably pointed you in the wrong direction, can you file it here?

https://github.com/rancher/os/issues/new
