### ISSUE TITLE
Kubernetes 1.7 doesn't set the public ips for nodes

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#9341]
**Rancher versions:**
rancher/server: v1.6.3
kubernetes (if applicable): 1.7.0

**Steps to Reproduce:**
- Start kubernetes 1.7
- run `kubectl get nodes -o json | grep address`

**Results:**

Kubernetes only stores the private ips for the nodes, unlike kubernetes 1.5.4 and 1.6.6 which stores the both public and private ips for the node:

in k8s 1.6.6:
```
$ kubectl get nodes -o json 
....
"addresses": [
          {
            "address": "<public-ip>",
            "type": "ExternalIP"
          },
          {
            "address": "<public-ip>",
            "type": "LegacyHostIP"
          },
          {
            "address": "hgalal-k8s-10acre-1.c.rancher-qa.internal",
            "type": "Hostname"
          }
....
```
in k8s 1.7.0:
```
"addresses": [
          {
            "address": "172.16.100.169",
            "type": "InternalIP"
          },
          {
            "address": "hgalal-k8s-10acre-1.c.rancher-qa.internal",
            "type": "Hostname"
          }
        ],
```

**Comment by alena1108** [comment]
@joshwget most likely related to the cloud provider refactoring, could you take a look?

**Comment by alena1108** [comment]
@galal-hussein can be tested with v1.7.1-rancher2

**Comment by galal-hussein** [comment]
Rancher server: v1.6.6-rc2
K8S version: rancher/k8s:v1.7.1-rancher2

I can see the external IP now when running `kubectl get nodes -o json`:

```
....
"status": {
        "addresses": [
          {
            "address": "x.x.x.x",
            "type": "ExternalIP"
          },
          {
            "address": "hgalal-10acre-3.c.rancher-qa.internal",
            "type": "Hostname"
          }
....
```
