### ISSUE TITLE
[BUG] Distribute containers evenly on all hosts as we scale +/-

### ISSUE THREAD

**Issue by mananpreetsingh** [rancher/rancher#9342]
**Rancher versions:**

Rancher | v1.6.2
Cattle | v0.181.4
User Interface | v1.6.5
Rancher CLI | v0.6.1
Rancher Compose | v0.12.5

**Infrastructure Stack versions:**
healthcheck:v0.3.1
ipsec:rancher/net:holder
network-services: network-manager:v0.7.4
scheduler: v0.8.1

**Docker version: 17.03.1-ce

**Operating system and kernel: Ubuntu 14.04.5 LTS / 16

**Type/provider of hosts:  AWS

**Environment Template: Cattle

###########################

Requirement: Start new container evenly on host as we scale up the containers.

Set Up: 5 containers running on 5 Hosts and I am using below rancher label to start the container evenly on Hosts:

`io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
`

Problem: Above label is working fine when we bring the new stack up. But when I increase the scale to add more containers it keeps adding container on single host, rancher don't distribute evenly once the stack is up and running.

Expected result: If I have to scale up the containers (assume each host is running one container) then it should start distributing container evenly. e.g: adding 4 more container (5 old + 4 new) should be started on any 4 hosts just not on all 4 on single host.

thanks,
MS

**Comment by superseb** [comment]
Can you include a screenshot of the `Infrastructure` -> `Hosts` view please?

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rancher/issues/8080
