### ISSUE TITLE
Traffic is not forwarded for other network plugins

### ISSUE THREAD

**Issue by niusmallnan** [rancher/rancher#9345]
**Description:**
When `per-host-subnet` plugin is deployed, the traffic between the containers is not accepted in the FORWARD chain.

~Old Description:~
~Network-manager can handle port rules when we use IPSec/VXLAN, because of IPSec/VXLAN networking use UDP ports to connect. Network-manager will add some tag traffic rules in IPtables by port rules. For example:~
~```~
~iptables -t raw -N CATTLE_RAW_PREROUTING~
~iptables -t raw -A PREROUTING -m addrtype --dst-type LOCAL -j CATTLE_RAW_PREROUTING~
~iptables -t raw -A CATTLE_RAW_PREROUTING ! -i docker0 -p udp -m udp --dport 4789 -j MARK --set-xmark 0x1068/0xffffffff~
~~
~```~
~~
~But when we use the l2-flat / l3-routing network, network-manager can not handle port rules, because there are not ports for these networkings.~
~~
~We should tag the traffic, because, the Forward chain defaults to drop after Docker v1.13.~

**Comment by yasker** [comment]
#79 merged to fix this issue.

**Comment by kingsd041** [comment]
Test passed.
