### ISSUE TITLE
High CPU Load after upgrading to 1.6.3 ( from 1.6.1)

### ISSUE THREAD

**Issue by EugenMayer** [rancher/rancher#9346]
**Rancher versions:**
rancher/server: 1.6.3
rancher/agent: 1.2.5

**Infrastructure Stack versions:**
healthcheck: 0.3.1
ipsec: 0.11.3
network-services: 0.7.4
scheduler: 0.8.1

**Docker version: (`docker version`,`docker info` preferred)**
Docker version 17.03.1-ce, build c6d412e

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
rancheros 1.0.3
Linux rancher.kontextwork.com 4.9.34-rancher #1 SMP Mon Jun 26 01:54:18 UTC 2017 x86_64 GNU/Linux

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS - 2GB small

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher - this server does only run rancher-server,openldap(very little instance container) and a letsencrypt image for SSL Certs.
It uses the internal mysql db

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
cattle

**Steps to Reproduce:**
No idea - it seems to be steady or probably triggered by accessing the catalog list

**Results:**
High CPU load, about 14 average, never drops.
It has been working with this setup very smooth with 1.6.1 - could though also be related with rancheros 1.0.3 since i upgraded at the same time

It seems like cattlle.launcher.main is the processes to get all the CPU (22+%  each- steady never drops), mysql gets involved second (11%). The parent process seems to be `s6-supervise cattle` see https://goo.gl/XyVpvH

**Comment by EugenMayer** [comment]
when i restart the server, it just continues

**Comment by EugenMayer** [comment]
found https://github.com/rancher/rancher/issues/6857, so adding some informations

6 environments, about 30 containers spreaded on 6 hosts, no swarm, no scheduling or host migration, no h

**Comment by superseb** [comment]
Can you share logging from the `rancher/server` container?

**Comment by EugenMayer** [comment]
can be closed, fixed with the upgrade to newer versions
