### ISSUE TITLE
dnsupdate-rfc2136 (v0.6.2-rancher2) not removing DNS entry after Stack or container is deleted from a Rancher Environment

### ISSUE THREAD

**Issue by royerhq** [rancher/rancher#9352]
**Rancher versions:**
rancher/server: v1.6.2
rancher/agent: v.1.2.2

**Infrastructure Stack versions:**
healthcheck: v0.3.0
ipsec: v0.1.0
network-services: v0.2.0
scheduler: v.0.5.1

**Docker version: (`docker version`,`docker info` preferred)**
Server: 17.03.1-ce

**Operating system**
CentOS Linux release 7.3.1611 (Core)

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS EC2

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA Rancher, RDS DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle 

**Steps to Reproduce:**
Install dnsupdate-rfc2136 service Add a stack+container with container exposing a port.
Remove Stack or container and check your DNS. Entry from DNS server is not removed 

**Expect Results:**
DNS record should be removed from the DNS server after container is removed/deleted from environment

**Additional Notes**
Using Windows DNS.

**Comment by superseb** [comment]
Is it possible to share debug logs from the external-dns container?

**Comment by royerhq** [comment]
Here a short snapshot of today's logs

`7/17/2017 9:26:34 AMtime="2017-07-17T16:26:34Z" level=error msg="AXFR envelope error: dns: no SOA"
7/17/2017 9:26:34 AMtime="2017-07-17T16:26:34Z" level=info msg="DNS records to add: [{rlbs.admin-console.admin-console-ci.devplatform.net. [10.206.41.91] A 60} {sftp-server.efs-manage.admin-console-ci.devplatform.net. [10.206.40.109] A 60} {external-dns-26e6b18c-5b66-4d1b-8018-79c19e251761.ingroovesplatform.net. [rlbs.admin-console.admin-console-ci.devplatform.net. sftp-server.efs-manage.admin-console-ci.devplatform.net.] TXT 60}]"
7/17/2017 9:26:34 AMtime="2017-07-17T16:26:34Z" level=info msg="Adding dns record: {rlbs.admin-console.admin-console-ci.devplatform.net. [10.206.41.91] A 60}"
7/17/2017 9:26:34 AMtime="2017-07-17T16:26:34Z" level=info msg="Adding dns record: {sftp-server.efs-manage.admin-console-ci.devplatform.net. [10.206.40.109] A 60}"
7/17/2017 9:26:34 AMtime="2017-07-17T16:26:34Z" level=info msg="Adding dns record: {external-dns-26e6b18c-5b66-4d1b-8018-79c19e251761.devplatform.net. [rlbs.admin-console.admin-console-ci.devplatform.net. sftp-server.efs-manage.admin-console-ci.devplatform.net.] TXT 60}"
7/17/2017 9:26:37 AMtime="2017-07-17T16:26:37Z" level=error msg="AXFR envelope error: dns: no SOA"
7/17/2017 9:26:42 AMtime="2017-07-17T16:26:42Z" level=error msg="AXFR envelope error: dns: no SOA"
7/17/2017 9:26:47 AMtime="2017-07-17T16:26:47Z" level=error msg="AXFR envelope error: dns: no SOA"
7/17/2017 9:26:52 AMtime="2017-07-17T16:26:52Z" level=error msg="AXFR envelope error: dns: no SOA"
7/17/2017 9:26:57 AMtime="2017-07-17T16:26:57Z" level=error msg="AXFR envelope error: dns: no SOA"
7/17/2017 9:27:02 AMtime="2017-07-17T16:27:02Z" level=error msg="AXFR envelope error: dns: no SOA"`

**Comment by royerhq** [comment]
@superseb This issue was due to a configuration that was remove by someone on our team without communicating the change. I do apologize for this! 
Thanks for looking into it.
