### ISSUE TITLE
Feature Request: Prevent Scaling

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#9353]
There are some services that should only be allowed to have 1 instance running. It would be great to have a way to disable scaling so it cannot accidentally scaled up. However rescheduling from a bad host to a new host should be allowed.

Being able to define a services as not being able to scale and disabling that capability via the API and in the UI would be awesome.

**Comment by vincent99** [comment]
This is implemented for 2.0 already; min, max, and increment (e.g. to require an odd number).  Also global with n containers per host, and a max number of distinct hosts to schedule to.

**Comment by ekristen** [comment]
Fantastic to hear @vincent99 thanks! Is there a way to view/test 2.0?

**Comment by vincent99** [comment]
Not in a way that works much... Next month.

**Comment by ekristen** [comment]
@vincent99 thanks, looking forward to seeing it.
