### ISSUE TITLE
rancher-agent is using to much memory after upgraded to 1.2.5

### ISSUE THREAD

**Issue by hiscal2015** [rancher/rancher#9355]
**Rancher versions:** 1.6.4

**Docker version: (`docker version`,`docker info` preferred)** 1.12.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)** Ubuntu16.04

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** Bare-metal/

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)** Single

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)** Kubernetes

**Steps to Reproduce:**

I upgraded rancher from v1.5.10 to v1.6.4, the new version of rancher-agent is v1.2.5, most of the rancher-agent's memory usage is less than 100MB, but some are using more than 1GB memory, is this normal?

![rancheragent](https://user-images.githubusercontent.com/15604715/28243693-25302b0c-6a07-11e7-9b15-b938d2702c91.jpg)

**Comment by superseb** [comment]
Can you specify a bit more on `some are using more`. Is it totally random or can you pinpoint to something? Is it reproducible?

**Comment by hiscal2015** [comment]
keep watching, closed for now.
