### ISSUE TITLE
Feature request: Connect to managed network from external server

### ISSUE THREAD

**Issue by Richard87** [rancher/rancher#9356]
Hi!

I have some issues setting up storage... I have successfully set up rancher-nfs with my storage server, but I'm worried that the traffic is not encrypted. I think an *easy* an flexible solution would be for my server to connect to the managed network, and route nfs traffic on there.

I assume this should be pretty straight forward if I have the correct configuration and the correct certificates. 

Would it be possible for Rancher-Server to create certificate for this use, or would that mess up the configuration for the available hosts?

Could someone provide a simple config on how a ipsec would be set up? I have some troubles trying to understand how it would work :/

Thanks, Richard

**Comment by Richard87** [comment]
Also, this would work very well for everyone that want to run their database or similar on bare metal, and still be secure when using the servers over the internett...

**Comment by superseb** [comment]
Everything needed to setup the tunnels is gathered by metadata which consists of hosts/stacks/services in Rancher.

If you can add the host to your Rancher environment and let no containers schedule on them, you can run a Dockerized NFS server and add it to the managed network (https://rancher.com/docs/rancher/latest/en/rancher-services/networking/#containers-created-with-the-docker-cli).

I don't see adding external hosts to the ipsec network happening soon.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
