### ISSUE TITLE
Catalog: mysql_send_long_data() is longer than 'max_long_data_size' bytes

### ISSUE THREAD

**Issue by marvinwankersteen** [rancher/rancher#9357]
**Rancher versions:**
rancher/server:v1.6.4
rancher/agent:v1.2.5

**Infrastructure Stack versions:**
healthcheck:v0.3.1
ipsec:v0.11.3
network-services:v0.7.4
scheduler:v0.8.2
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 11:02:43 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 11:02:43 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04.2 LTS

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
KVM, Bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher with external DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Activate/refresh catalogs

**Results:**
```
(Error 1105: Parameter of prepared statement which is set through mysql_send_long_data() is longer than 'max_long_data_size' bytes) 
[2017-07-16 19:02:27]  
ERRO[0013] Failed to perform catalog refresh: community: Error 1105: Parameter of prepared statement which is set through mysql_send_long_data() is longer than 'max_long_data_size' bytes 

(Error 1105: Parameter of prepared statement which is set through mysql_send_long_data() is longer than 'max_long_data_size' bytes) 
[2017-07-16 19:02:33]  
ERRO[0020] Failed to perform catalog refresh: community: Error 1105: Parameter of prepared statement which is set through mysql_send_long_data() is longer than 'max_long_data_size' bytes
```

I found the above errors every ~6 seconds in "`docker logs`" and `cattle-debug.log`. The error appears, I think, after the upgrade from 1.6.2 to 1.6.4. I tried to increase the `max_long_data_size` from `1048576` to `2097152` but the error appears until I disable the catalogs in admin settings.
```
mysql> show variables like 'max_long_data_size'\G
Variable_name: max_long_data_size
        Value: 2097152
```

How can I find out how big is `mysql_send_long_data`?

**Comment by superseb** [comment]
Are you sure this started since upgrading to 1.6.4? Can you tell me what database server and what database server version you are running? Try to up `max_allowed_packet` in the meantime

**Comment by marvinwankersteen** [comment]
No I am not totally sure. But after the upgrade to 1.6.2 I did not saw this error.

I use the image mysql:5.5 as database.

I tried to increase the `max_allowed_packet` but the error still there:
`mysql> set global max_allowed_packet=2097152;`

```
root@rancher:~$ docker logs -f --tail=100 rancher_server_1
..
..
(Error 1105: Parameter of prepared statement which is set through mysql_send_long_data() is longer than 'max_long_data_size' bytes) 
[2017-07-17 12:38:59]  
ERRO[63408] Failed to perform catalog refresh: community: Error 1105: Parameter of prepared statement which is set through mysql_send_long_data() is longer than 'max_long_data_size' bytes 

(Error 1105: Parameter of prepared statement which is set through mysql_send_long_data() is longer than 'max_long_data_size' bytes) 
[2017-07-17 12:39:21]  

(Error 1105: Parameter of prepared statement which is set through mysql_send_long_data() is longer than 'max_long_data_size' bytes) 
[2017-07-17 12:39:41]
..
..
```

**Comment by superseb** [comment]
Can you try setting it to `16777216` or higher?

**Comment by marvinwankersteen** [comment]
Its a bit strange... I set `max_long_data_size=16777216` and `max_allowed_packet` to default and the error not appeared anymore.
Then I removed all the settings so its the default settings of the image, and the error also is gone.
After every change I recreated the database-container.

Maybe the errors is gone because the server could update the requested data once?

I let the container run the next hours to see if the error comes back. I will give feedback.

**Comment by superseb** [comment]
This should be detectable and/or documented, please report back and thanks for testing.

**Comment by ekristen** [comment]
I recently ran into this error, I had to up the max_allowed_packet on my database server.

**Comment by gregkeys** [comment]
been receiving the same error in our HA environment we are using amazon rds with maria db 10.0
this might be some helpful information

`
max_allowed_packet |   | 1024-1073741824 | true | engine-default | dynamic | integer | This value by default is small, to catch large (possibly incorrect) packets. Must be increased if using large BLOB columns or long strings. As big as largest BLOB.
`

**Comment by ekristen** [comment]
You'll need to increase the max_allowed_packet. I increased mine to `16777216` to resolve the problem.

**Comment by superseb** [comment]
go-mysql-driver defaults to `16777216` (https://github.com/go-sql-driver/mysql/blob/0b58b37b664c21f3010e836f1b931e1d0b0b0685/const.go#L13)

Defaults on max_allowed_packet, based on Dockerhub images and RDS

| Type | Version | max_allowed_packet |
|------|---------|--------------------|
| mysql     |   5.5      | 1048576                   |
|  mysql    |   5.6      | 4194304                   |
|  mysql   |   5.7      | 4194304                    |
| mysql | 8.0 | 4194304 |
| mariadb | 5.5 | 16777216 |
| mariadb | 10.0 | 16777216 |
| RDS | 5.7 | 4194304 |

**Comment by leodotcloud** [comment]
If using a compose file, you can pass in the config via "command":
```
version: 2
services:
    db:
        image: mysql:5.5.53
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        command:
            - --max_allowed_packet=16M
```

**Comment by cloudnautique** [comment]
We are updating our docs to recommend using a `max_packet_size` of 32M or so. 
The record for the catalog has (2) Medium blob fields each can be a max of 16MB. Right now, it appears a 4MB max_packet_size will work for the existing entries. Still  the possibility of this error exists even in those setups with 16M.
