### ISSUE TITLE
"Scheduling failed: No candidates available" error

### ISSUE THREAD

**Issue by LKJonDoe** [rancher/rancher#9359]
i got this error when i wanna update or finish update some instances, do you have any ideas ?

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.0.0` Cattle: `v0.159.2` UI: `v0.100.3` |
|Access|`github` `admin`|
|Route|`service.containers`|

**Comment by tfiduccia** [comment]
Does your service have a scheduling rule associated to it?

**Comment by superseb** [comment]
Closing as stale.
