### ISSUE TITLE
Get the error "invalid character 'b' looking for beginning of value" when adding a host

### ISSUE THREAD

**Issue by ias-gmckeever** [rancher/rancher#9360]
**Rancher versions:**
rancher/server: 1.6.2
rancher/agent: 1.2.2

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 10
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay bridge null host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-83-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.66 GiB
Name: phoenix-2
ID: QVEE:E623:YQYE:IBYW:BZBC:TSZI:K5PP:PUJP:LKBS:KFLB:GLXS:7TNG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04.1
Kernel: 4.4.0-83-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Rancher and agent host are running on bare metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node, external DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
When adding a Rancher node on a particular box, it always fails with the following error:

Found container ID: 73d208812f9e83763cd7ea445077d97e3dac58053de0d43606a8e68c945c4a1f
Checking root: /host/run/runc
Checking file: 6cfa7fd139505c1d3bdbcba6b313b738278f820f8d34bd34cfcda885e0183137
Checking file: 73d208812f9e83763cd7ea445077d97e3dac58053de0d43606a8e68c945c4a1f
Found state.json: 73d208812f9e83763cd7ea445077d97e3dac58053de0d43606a8e68c945c4a1f
time="2017-07-17T14:49:03Z" level=info msg="Execing [/usr/bin/nsenter --mount=/proc/18506/ns/mnt -F -- /var/lib/docker/aufs/mnt/2be52f5307ec6c8ea590fc21781ddeb268fe7e347e86659e55533b41f4f0e926/usr/bin/share-mnt --stage2 /var/lib/rancher/volumes /var/lib/kubelet -- norun]" 
Found container ID: 73d208812f9e83763cd7ea445077d97e3dac58053de0d43606a8e68c945c4a1f
Checking root: /run/runc
Checking file: 6cfa7fd139505c1d3bdbcba6b313b738278f820f8d34bd34cfcda885e0183137
Checking file: 73d208812f9e83763cd7ea445077d97e3dac58053de0d43606a8e68c945c4a1f
Found state.json: 73d208812f9e83763cd7ea445077d97e3dac58053de0d43606a8e68c945c4a1f
INFO: Starting agent for F1F152456D5FB67F841B
INFO: Access Key: F1F152456D5FB67F841B
INFO: Config URL: http://10.40.0.220:8080/v1
INFO: Storage URL: http://10.40.0.220:8080/v1
INFO: API URL: http://10.40.0.220:8080/v1
INFO: IP: 10.40.0.224
INFO: Port:
INFO: Required Image: rancher/agent:v1.2.2
INFO: Current Image: rancher/agent:v1.2.2
INFO: Using image rancher/agent:v1.2.2
Updating certificates in /etc/ssl/certs...
1 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
INFO: Downloading agent http://10.40.0.220:8080/v1/configcontent/configscripts
INFO: Updating configscripts
INFO: Downloading http://10.40.0.220:8080/v1//configcontent//configscripts current=
INFO: Running /var/lib/cattle/download/configscripts/configscripts-1-f0f3fb2e1110b5ada7c441705981f93a480313a324294321cff467f0c3e12319/apply.sh
INFO: Sending configscripts applied 1-f0f3fb2e1110b5ada7c441705981f93a480313a324294321cff467f0c3e12319
INFO: Updating pyagent
INFO: Downloading http://10.40.0.220:8080/v1//configcontent//pyagent current=
INFO: Running /var/lib/cattle/download/pyagent/pyagent-1-9e3dcab12585149a65d818082279708965cd826df1937a55b24f48428f8f0c0644fc1033b5be15c88dcf9540b1c04c67/apply.sh
INFO: Updating host-api
INFO: Downloading http://10.40.0.220:8080/v1//configcontent//host-api current=1-9608ead804f8cebbfe95b9f114701d8a5ac4244d603d196068043c902b1a0bdf
INFO: Already up to date
INFO: Sending host-api applied 1-9608ead804f8cebbfe95b9f114701d8a5ac4244d603d196068043c902b1a0bdf
INFO: Updating python-agent
INFO: Downloading http://10.40.0.220:8080/v1//configcontent//python-agent current=1-e5bc76967b58923fc4ff4242bc0c4970e5f7a6a8f9d1c88212444fc0d75db6ab
INFO: Already up to date
INFO: Sending python-agent applied 1-e5bc76967b58923fc4ff4242bc0c4970e5f7a6a8f9d1c88212444fc0d75db6ab
INFO: Sending pyagent applied 1-9e3dcab12585149a65d818082279708965cd826df1937a55b24f48428f8f0c0644fc1033b5be15c88dcf9540b1c04c67
INFO: Starting agent /var/lib/cattle/pyagent/apply.sh
INFO: Executing /var/lib/cattle/pyagent/agent
INFO: Updating host-config
INFO: Downloading http://10.40.0.220:8080/v1//configcontent//host-config current=host-config-1-ed3d92450e05a36610eda5c2a14c00b1089ce9cdb4ec6596a43688a3e954ff43
INFO: Already up to date
INFO: Sending host-config applied 1-ed3d92450e05a36610eda5c2a14c00b1089ce9cdb4ec6596a43688a3e954ff43
time="2017-07-17T14:49:06Z" level=info msg="Launching agent" 
time="2017-07-17T14:49:06Z" level=info msg="http://10.40.0.220:8080/v1F1F152456D5FB67F841B3SuJnTK3z6TAbSMRREtD8Cze8K1X3cfwNco7uP3L" 
time="2017-07-17T14:49:06Z" level=info msg="Listening for events on http://10.40.0.220:8080/v1" 
time="2017-07-17T14:49:06Z" level=info msg="launching hostapi" 
time="2017-07-17T14:49:06Z" level=info msg="Serialize compute requests: false, driver: aufs" 
time="2017-07-17T14:49:06Z" level=info msg="Starting event router." 
time="2017-07-17T14:49:06Z" level=info msg="Initializing event router" workerCount=250 
time="2017-07-17T14:49:06Z" level=info msg="Connection established" 
time="2017-07-17T14:49:06Z" level=info msg="Starting websocket pings" 
time="2017-07-17T14:49:06Z" level=error msg="invalid character 'b' looking for beginning of value"

I noticed the issue https://github.com/rancher/rancher/issues/8656 but that applies to a node behind a proxy and this node is not behind a proxy.

I also found https://github.com/rancher/rancher/issues/7424 but that was due to a DNS issue and DNS appears to be fine on this box.

I tried searching the Rancher source, but the error message doesn't appear to be generated by Rancher itself, so I'm out of ideas.  Do you know what may be causing this or how I can get more detailed information about the request that is failing so that I can resume troubleshooting?  This Rancher server has multiple nodes connected to it from other hosts and they are working perfectly fine.

**Comment by superseb** [comment]
This happens when the JSON that gets returned cannot be parsed, which can happen sometime when it's starting up but not continuously. Are you still seeing these errors?

If you do, I tried to create something to dump the response to see if we can retrieve what's going wrong: https://github.com/superseb/rancherws.

**Comment by ias-gmckeever** [comment]
I see these errors consistently.  The invalid character is sometimes different but the agent always throws this error and fails to start.

Thank you very much for providing this tool to dump the data.  I will try it and post the results.

**Comment by ias-gmckeever** [comment]
Here is the output of the docker container when executed from the machine in which the Rancher agent fails (I redacted some data on the command line):

docker run nexus.iassoftware.com:5000/rancherws 10.40.0.220:8080 XXXXXXXXXXXX YYYYYYYYYYYYYYYYY ZZZ
Socket opened
{"id":"18a64867-0a89-49c7-8a4c-86849c637b07","name":"ping","resourceId":null,"resourceType":null,"data":{"options":{},"resources":[]},"time":1501698928125}
ping
{"id":"04db174b-d51c-4a50-a3d4-4743d7910ef3","name":"ping","resourceId":null,"resourceType":null,"data":{"options":{},"resources":[]},"time":1501698933126}
ping
{"id":"d4fc6a8c-1b58-45a2-81bd-61a2c57d763b","name":"ping","resourceId":null,"resourceType":null,"data":{"options":{},"resources":[]},"time":1501698938127}
ping
{"id":"f7e65267-9028-43cb-a42a-13b13535ccb8","name":"ping","resourceId":null,"resourceType":null,"data":{"options":{},"resources":[]},"time":1501698943127}
ping
{"id":"86e279cc-be33-4f81-841e-636fe98aecb3","name":"ping","resourceId":null,"resourceType":null,"data":{"options":{},"resources":[]},"time":1501698948128}


I executed an instance of the same image on a machine that is capable of executing a Rancher agent with no problems and the output was very similar.

**Comment by superseb** [comment]
Ok, this doesn't help us as this is working just fine. I'll try to get a minimalistic test going with the used Go code.

**Comment by cjellick** [comment]
I opened a PR to add some context around our logging on startup. Hopefully, this will catch this particular error and provide us with some value context.

**Comment by ias-gmckeever** [comment]
@cjellick Thank you!

**Comment by ghatwala** [comment]
Hi All,

Getting similar error as above whilst adding hosts to rancher server.

```
# docker logs rancher-agent
Found container ID: 04375381c748dd500de19bac5ec3010c79a7d6ea4b671e3cd27bd895d2186661
Checking root: /host/run/runc
Checking file: 04375381c748dd500de19bac5ec3010c79a7d6ea4b671e3cd27bd895d2186661
Found state.json: 04375381c748dd500de19bac5ec3010c79a7d6ea4b671e3cd27bd895d2186661
time="2017-08-16T10:16:56Z" level=info msg="Execing [/usr/bin/nsenter --mount=/proc/4582/ns/mnt -F -- /var/lib/docker/overlay2/d557488f7b8f07192c5b6625b375fa0ebc33bf63d518d42bfc6ef11eaccf0e7c/merged/usr/bin/share-mnt --stage2 /var/lib/rancher/volumes /var/lib/kubelet -- norun]"
Found container ID: 04375381c748dd500de19bac5ec3010c79a7d6ea4b671e3cd27bd895d2186661
Checking root: /run/runc
Checking file: 04375381c748dd500de19bac5ec3010c79a7d6ea4b671e3cd27bd895d2186661
Found state.json: 04375381c748dd500de19bac5ec3010c79a7d6ea4b671e3cd27bd895d2186661
/run.sh: /var/patch.py: /bin/python: bad interpreter: No such file or directory
INFO: Starting agent for 68CE3B06D44CC55B910D
INFO: Access Key: 68CE3B06D44CC55B910D
INFO: Config URL: http://10.51.226.189:8080/v1
INFO: Storage URL: http://10.51.226.189:8080/v1
INFO: API URL: http://10.51.226.189:8080/v1
INFO: IP: 10.77.67.146
INFO: Port:
INFO: Required Image: rancher/agent:v1.2.5
INFO: Current Image: rancher/agent:v1.2.5
INFO: Using image rancher/agent:v1.2.5
Updating certificates in /etc/ssl/certs...
1 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
INFO: Downloading agent http://10.51.226.189:8080/v1/configcontent/configscripts
INFO: Updating configscripts
INFO: Downloading http://10.51.226.189:8080/v1//configcontent//configscripts current=
INFO: Running /var/lib/cattle/download/configscripts/configscripts-1-f0f3fb2e1110b5ada7c441705981f93a480313a324294321cff467f0c3e12319/apply.sh
INFO: Sending configscripts applied 1-f0f3fb2e1110b5ada7c441705981f93a480313a324294321cff467f0c3e12319
INFO: Updating pyagent
INFO: Downloading http://10.51.226.189:8080/v1//configcontent//pyagent current=
INFO: Running /var/lib/cattle/download/pyagent/pyagent-1-9e3dcab12585149a65d818082279708965cd826df1937a55b24f48428f8f0c0644fc1033b5be15c88dcf9540b1c04c67/apply.sh
INFO: Updating host-api
INFO: Downloading http://10.51.226.189:8080/v1//configcontent//host-api current=1-9608ead804f8cebbfe95b9f114701d8a5ac4244d603d196068043c902b1a0bdf
INFO: Already up to date
INFO: Sending host-api applied 1-9608ead804f8cebbfe95b9f114701d8a5ac4244d603d196068043c902b1a0bdf
INFO: Updating python-agent
INFO: Downloading http://10.51.226.189:8080/v1//configcontent//python-agent current=1-e59dee1ccc967da0f643e7081756a9742c29c1ed2d57a848e5c5878e648d3fed
INFO: Already up to date
INFO: Sending python-agent applied 1-e59dee1ccc967da0f643e7081756a9742c29c1ed2d57a848e5c5878e648d3fed
INFO: Sending pyagent applied 1-9e3dcab12585149a65d818082279708965cd826df1937a55b24f48428f8f0c0644fc1033b5be15c88dcf9540b1c04c67
INFO: Starting agent /var/lib/cattle/pyagent/apply.sh
INFO: Executing /var/lib/cattle/pyagent/agent
INFO: Updating host-config
INFO: Downloading http://10.51.226.189:8080/v1//configcontent//host-config current=host-config-1-14cb66512bbe8e03c9346613d7fd7bdf36e5cd8eb5debffb121514145453ab92
INFO: Already up to date
INFO: Sending host-config applied 1-14cb66512bbe8e03c9346613d7fd7bdf36e5cd8eb5debffb121514145453ab92
time="2017-08-16T10:17:01Z" level=info msg="Launching agent"
time="2017-08-16T10:17:01Z" level=info msg="Listening for events on http://10.51.226.189:8080/v1"
time="2017-08-16T10:17:01Z" level=info msg="launching hostapi"
time="2017-08-16T10:17:01Z" level=info msg="Starting event router."
time="2017-08-16T10:17:01Z" level=info msg="Serialize compute requests: false, driver: overlay2"
time="2017-08-16T10:17:01Z" level=error msg="invalid character 'c' looking for beginning of value"
time="2017-08-16T10:17:01Z" level=info msg="Initializing event router" workerCount=250
time="2017-08-16T10:17:02Z" level=info msg="Connection established"
time="2017-08-16T10:17:02Z" level=info msg="Starting websocket pings"
time="2017-08-16T10:17:02Z" level=warning msg="Failed to collect data from collector cpuInfo error msg: failed to get cpu info: open /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq: no such file or directory"
time="2017-08-16T10:17:06Z" level=error msg="invalid character 'c' looking for beginning of value"
time="2017-08-16T10:17:11Z" level=error msg="invalid character 'c' looking for beginning of value"
time="2017-08-16T10:17:16Z" level=error msg="invalid character 'c' looking for beginning of value"
time="2017-08-16T10:17:21Z" level=error msg="invalid character 'c' looking for beginning of value"
time="2017-08-16T10:17:26Z" level=error msg="invalid character 'c' looking for beginning of value"
time="2017-08-16T10:17:31Z" level=error msg="invalid character 'c' looking for beginning of value"
time="2017-08-16T10:17:36Z" level=error msg="invalid character 'c' looking for beginning of value"
time="2017-08-16T10:17:41Z" level=error msg="invalid character 'i' in literal false (expecting 'a')"
time="2017-08-16T10:17:47Z" level=error msg="invalid character 'i' in literal false (expecting 'a')"
time="2017-08-16T10:17:52Z" level=error msg="invalid character 'i' in literal false (expecting 'a')"
time="2017-08-16T10:17:57Z" level=error msg="invalid character 'i' in literal false (expecting 'a')"
time="2017-08-16T10:18:02Z" level=error msg="invalid character 'c' looking for beginning of value"
time="2017-08-16T10:18:07Z" level=error msg="invalid character 'i' in literal false (expecting 'a')"
time="2017-08-16T10:18:12Z" level=error msg="invalid character 'i' in literal false (expecting 'a')"
```

Docker images present
```
#docker images | grep rancher
rancher/agent           v1.2.5              c1a0bd68291c        11 minutes ago      386MB
rancher/agent-base      v0.3.0              368edfee80c0        28 minutes ago      372MB
```

Operating system and kernel: 
```
# cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.1 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.1 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
UBUNTU_CODENAME=xenial

# uname -r
4.4.0-62-generic

# lscpu
Architecture:          ppc64le
Byte Order:            Little Endian
CPU(s):                3
On-line CPU(s) list:   0-2
Thread(s) per core:    1
Core(s) per socket:    3
Socket(s):             1
NUMA node(s):          1
Model:                 2.1 (pvr 004b 0201)
Model name:            POWER8E (raw), altivec supported
Hypervisor vendor:     KVM
Virtualization type:   para
L1d cache:             64K
L1i cache:             32K
NUMA node0 CPU(s):     0-2

```
Any pointers to resolve the issue of adding hosts to rancher/server?

**Comment by ghatwala** [comment]
hi all , issue got resolved after i moved to a lower version of agent binary
go get -v github.com/rancher/agent
cd $GOPATH/src/github.com/rancher/agent
git checkout 4e5f7502ad55e8ab50696e51e79e660888997d35
go build main.go
cp main $GOPATH/bin/agent

seems like the latest version of agent binary was giving the above issue . building from this : 4e5f7502ad55e8ab50696e51e79e660888997d35, should just show only one character error msg and then work fine ...and then we are able to add hosts successfully to rancher server.

**Comment by superseb** [comment]
The logging was added in `rancher/server:v1.6.8` and matched `rancher/agent:v1.2.6`. Please try these version if you are experiencing this issue as well.

**Comment by ghatwala** [comment]
@superseb - thanks for the response. So actually the version which worked for me was still rancher/server:v1.6.7 and rancher/agent:v1.2.5 , as had pointed out lower version of agent binary worked and helped to get over the above error and also was able to boot up rancher/agent container successfully on my added host . 

NOTE : Would like to mention that the hosts were ppc64le.

**Comment by superseb** [comment]
Closing this, we have additional logging in `rancher/agent:v1.2.6`.
