### ISSUE TITLE
Problems logging in with GitHub when the user has Unicode in their name

### ISSUE THREAD

**Issue by oskarpearson** [rancher/rancher#9361]
**Rancher versions:**
rancher/server: v1.6.2
rancher/agent: N/A

**Infrastructure Stack versions:**
healthcheck:N/A
ipsec:N/A
network-services:N/A
scheduler:N/A
kubernetes (if applicable):N/A
Rancher User Interface	v1.6.5

**Docker version: (`docker version`,`docker info` preferred)**

1.13.1, build 092cba3

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

16.04.2 LTS (Xenial Xerus) / 4.4.0-1022-aws

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

HA Rancher with AWS RDS external DB backend (RDS MySQL 5.6.27)

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

Cattle v0.181.4

**Steps to Reproduce:**

The problem occurs when someone with Unicode in their GitHub user-profile name logs in to Rancher with GitHub OAuth for the first time 

1. Set up a Rancher instance and grant it access to GitHub, setting things up so that an organisation has permission to log in.
2. Get a colleague that's part of their organisation but has not yet accessed your rancher instance to update their name so that it contains unicode (specific example, http://www.fileformat.info/info/unicode/char/0144/index.htm - Kopiński)
3. Get that colleague to try log in to your Rancher instance for the first time.
4. The user will get an internal server error

Note that this particular error occurs on creation of the account for the first time - but there may be similar issues that could occur if a user updates their name when they already exist. I've not tested these.

**Results:**

On the Rancher server, `docker logs` of the rancher container will show:

2017-07-17 15:27:55,835 ERROR [:] [] [] [] [.....] [i.g.i.g.r.handler.ExceptionHandler  ] Exception in API for request [https://rancher.bloomandwild.com/v2-beta/token]. Error id: [uuid-over-here]. org.jooq.exception.DataAccessException: SQL [insert into `account` (`name`, `kind`, `uuid`, `state`, `created`, `data`, `external_id`, `external_id_type`, `health_state`, `version`) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]; (conn:10052) Incorrect string value: '\xC5\x84ski' for column 'name' at row 1
Query is: insert into `account` (`name`, `kind`, `uuid`, `state`, `created`, `data`, `external_id`, `external_id_type`, `health_state`, `version`) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?), parameters ['... Kopiński','user','...uuid-over-here....','requested','2017-07-17 15:27:55.829','{}','1584002','github_user','healthy','2']

**Comment by vincent99** [comment]
This works fine on the default internal database, so I expect you have the wrong string encoding setup on your RDS.  `utf8` character set, `utf8_general_ci` collation.
