### ISSUE TITLE
rancher-ebs plugin defaulting to "Host" networking

### ISSUE THREAD

**Issue by garceri** [rancher/rancher#9364]
We use the rancher-ebs plugin on our AWS environment.
As we try to avoid hardcoding credentials as much as possible , we use IAM roles instead of setting AWS credentials on the environment for the ebs plugin container.

We have an additional security requirement as assigning the required Role to the rancher EC2 instance would mean that any of the containers could make use of the permissions granted for the EBS IAM role
In order to avoid that pitfall we make use of https://github.com/lyft/metadataproxy, the solution works pretty well as long as the containers use the "Managed"  networkk.
Unfortunately rancher-ebs defaults to Host networking and prevents this solution from working out of the box, requiring us to "upgrade" the container to use the managed network.

Is there any specific reason why rancher-ebs defaults to Host Networking?, as far as i can tell i don't see any problems running it in "Managed"  network mode..

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
