### ISSUE TITLE
Redundant logging relating to haproxy in /var/log/messages and /var/log/haproxy/traffic/events

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#9369]
rancher/server: Build from V1.6 branch
Lb image - rancher/lb-service-haproxy:v0.7.6

Steps to reproduce the problem:
Create a service
Add a load balancer and configure a port with its target pointing to this service with following custom config for enabling logs:
```
defaults
log 127.0.0.1:8514 local0 debug
```
Make some requests to the load balancer's port

Haproxy events and traffic related messages get logged in both - /var/log/haproxy/traffic and /var/log/haproxy/events

```
root@f9faf0c2429f:/# cat /var/log/haproxy/traffic
Jul 17 23:50:53 localhost haproxy[53]: Connect from <ip>:53642 to <lb-ip>:8091 (8091/HTTP)
Jul 17 23:50:56 localhost haproxy[53]: Connect from <ip>:53644 to 1<lb-ip>:8091 (8091/HTTP)

root@f9faf0c2429f:/# cat /var/log/haproxy/events
Jul 17 23:50:16 localhost haproxy[52]: Proxy default started.
Jul 17 23:50:16 localhost haproxy[52]: Proxy 8091 started.
Jul 17 23:50:16 localhost haproxy[52]: Proxy 8091_ started.
root@f9faf0c2429f:/#

root@f9faf0c2429f:/# cat /var/log/messages
Jul 17 23:50:14 f9faf0c2429f rsyslogd: [origin software="rsyslogd" swVersion="8.
16.0" x-pid="23" x-info="http://www.rsyslog.com"] start
Jul 17 23:50:16 localhost haproxy[52]: Proxy default started.
Jul 17 23:50:16 localhost haproxy[52]: Proxy 8091 started.
Jul 17 23:50:16 localhost haproxy[52]: Proxy 8091_ started.
Jul 17 23:50:53 localhost haproxy[53]: Connect from <ip>:53642 to <lb-ip>:8091 (8091/HTTP)
Jul 17 23:50:56 localhost haproxy[53]: Connect from <ip>:53644 to <lb-ip>:8091 (8091/HTTP)

```

We should have the ability to log HA proxy related messages in only 1 place ( /var/log/messages or in /var/log/haproxy/)

**Comment by alena1108** [comment]
Can be tested with haproxy v0.7.9

**Comment by sangeethah** [comment]
Tested with haproxy v0.7.9
Haproxy events and traffic related messages do not get logged in /var/log/messages anymore.

They are redirected to stdout/stderr now.
