### ISSUE TITLE
Rancher compose not getting updated with `rancher-compose up --force-upgrade` or `rancher-compose up --force-recreate`

### ISSUE THREAD

**Issue by borntorock** [rancher/rancher#9370]
we have scale (taken as a parameterised value) and health check params mentioned in the rancher-compose.yml file. 

Scale is taken as parameterised value from the jenkins job and replaced in the final rancher-compose.yml file.

But now while executing the rancher-compose up command with either `--force-upgrade` or `--force-recreate` via the ansible playbook, the updated rancher-compose is not getting used via the rancher-compose CLI while creating and upgrading the services. 

Can someone please help with this.

**Comment by borntorock** [comment]
@ibuildthecloud @deniseschannon @vincent99 Any solution on how we could resolve this in rancher.

**Comment by vincent99** [comment]
It doesn't work, scale is managed by `rancher-compose scale` after creating.  #8175 .  Please don't randomly @spam people.
