### ISSUE TITLE
rancher agent is aways  reconnecting

### ISSUE THREAD

**Issue by waldron-xing** [rancher/rancher#9371]
**Rancher versions:**
rancher/server:1.6.2
rancher/agent:1.2.2

I've installed the Rancher Server and then, in another server, a Rancher Agent using the command provided from Rancher Server. I can see the node in the host section but every 5 minutes rancher shows the message "Reconnecting" to the node.

**Comment by waldron-xing** [comment]
the rancher/server log :
2017-07-18 07:47:31,278 ERROR [:] [] [] [] [TaskScheduler-2] [i.c.p.a.s.ping.impl.PingMonitorImpl ] Failed to get ping from agent [1] count [3]

**Comment by superseb** [comment]
Reconnecting can have many causes, such as:

- Node pressure being high (CPU/mem)
- Network being slow or dropping packets

Can you tell me where your nodes are located and do you see an exact 5 minute pattern in the logs?

**Comment by superseb** [comment]
Please reply if you need help on this.
