### ISSUE TITLE
Cannot create a stack matching selector port rule in a load balancer in a second stack if the first stack contains lb_config data and the first stack/service does not already exist

### ISSUE THREAD

**Issue by feverpitch-tom** [rancher/rancher#9372]
**Rancher versions:**
rancher/server: v1.5.10
rancher/agent: v1.2.2

**Infrastructure Stack versions:**
healthcheck: v0.2.3
ipsec: "holder"
metadata:v0.9.1
network-manager:v0.6.6
scheduler:v0.7.5
net: v0.11.2

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
IBM SoftLayer VM

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher with external DB (MariaDB + Galera)

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Create a Load Balancer, add a selector port rule as follows:
```
Access: Public
Protocol: HTTP
Request Host: catchall
Request Port: 80
Path: [empty]
Target: load_balance_http=true
Target Port: 80
```

Extract the following ZIP file into a new directory:
[rancher-issue.zip](https://github.com/rancher/rancher/files/1155972/rancher-issue.zip)

Run the following command from the CLI:
```rancher up --stack test-issue-stack --pull --upgrade -d```

**Results:**
```
INFO[0001] Creating stack test-issue-stack              
INFO[0001] [app]: Creating                              
INFO[0001] Creating service app                         
ERRO[0002] Failed Creating app : Bad response statusCode [422]. Status [422 Unprocessable Entity]. Body: [fieldName=serviceId, baseType=error, code=MissingRequired] from [https://rancher.sbx.zone/v2-beta/projects/1a10139/loadbalancerservices] 
ERRO[0002] Failed to start: app : Bad response statusCode [422]. Status [422 Unprocessable Entity]. Body: [fieldName=serviceId, baseType=error, code=MissingRequired] from [https://rancher.sbx.zone/v2-beta/projects/1a10139/loadbalancerservices] 
FATA[0002] Bad response statusCode [422]. Status [422 Unprocessable Entity]. Body: [fieldName=serviceId, baseType=error, code=MissingRequired] from [https://rancher.sbx.zone/v2-beta/projects/1a10139/loadbalancerservices] 
```

Further details including an attempted workaround are documented here:
https://forums.rancher.com/t/dynamic-add-service-to-load-balanacer/4919/17

**Comment by superseb** [comment]
Please try removing `source_port` from your `rancher-compose.yml`.

**Comment by feverpitch-tom** [comment]
Yes, that worked - thank you very much @superseb
