### ISSUE TITLE
Throttle metadata CPU usage

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#9373]
Set cpuShares for the metadata container to less than the default 1024.

More details to come

**Rancher versions:**
rancher/server:
rancher/agent:

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**

**Results:**

**Comment by aemneina** [comment]
Work is being tracked here: https://github.com/rancher/rancher/issues/9957
Going to close this out for housekeeping.
