### ISSUE TITLE
Failed to perform catalog refresh error msg. need recommendations on innodb_log_file_size

### ISSUE THREAD

**Issue by bsommers** [rancher/rancher#9374]
**Rancher versions:**
rancher/server: 1.6.4
rancher/agent: 1.2.5

**Infrastructure Stack versions:**
healthcheck: v0.3.1
ipsec: 0.1.1
network-services: 0.9.2
scheduler: 0.8.1
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
Docker version 17.03.1-ce, build c6d412e

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

NAME="Red Hat Enterprise Linux Server"
VERSION="7.3 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="7.3"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.3 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.3:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.3
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.3"

3.10.0-514.6.1.el7.x86_64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VMWare

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA Rancher, external DB, mysql 

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**

docker stop rancher-server
docker rm rancher-server
docker run .... rancher/server:v1.6.4 ...   \# ha mode w/ dbuser, etc.
upgraded from 1.6.2 to 1.6.4 (stable)

**Results:**
docker logs showing the following messages:
````
time="2017-07-18T15:50:51Z" level=error msg="Failed to perform catalog refresh: community: Error 1118: The size of BLOB/TEXT data inserted in one transaction is greater than 10% of redo log size. Increase the redo log size using innodb_log_file_size."
````

 about once a second:
````
(Error 1118: The size of BLOB/TEXT data inserted in one transaction is greater than 10% of redo log size. Increase the redo log size using innodb_log_file_size.)
[2017-07-18 15:53:36]

(Error 1118: The size of BLOB/TEXT data inserted in one transaction is greater than 10% of redo log size. Increase the redo log size using innodb_log_file_size.)
[2017-07-18 15:53:40]
````

**Comment by cloudnautique** [comment]
@bsommers, which database server are you using? which version?

**Comment by cloudnautique** [comment]
The catalog service uses medium blobs for a few bits of template data. There are currently a few entries 1Mb< entry <4Mb range that could have been written. Depending on the default size of the DB server which ranges from 5Mb to 50Mb.

We are updating our docs to recommend larger settings if possible.

Closing this issue for now, if you find that this theory doesn't make sense, please update issue with server version and settings for `innodb_log_file_size`
