### ISSUE TITLE
rancher catalog panics and UI wont login when catalogs are inaccessible

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#9378]
**Rancher versions:**
rancher/server:1.6.4

In a setup that is air-gapped, and doesnt leverage a git mirror, the user is effectively locked out of the UI. Go panics ensue.

**Comment by prachidamle** [comment]
Auth returns success, but user is not able to login since UI gets an error for the API call /v1-catalog/catalogs and does not let the login proceed. Can we make this API call after the user is allowed to go to the landing page?

**Comment by prachidamle** [comment]
go panic in logs:

`goroutine 38 [running]:
panic(0xa336c0, 0xc42001a060)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/rancher/catalog-service/git.RemoteShaChanged(0xc4202114d0, 0x2c, 0xc420229098, 0x6, 0xc420211500, 0x28, 0xc4202b42a0, 0x24, 0x9bc0c0)
	/go/src/github.com/rancher/catalog-service/git/git.go:76 +0x2aa
github.com/rancher/catalog-service/manager.(*Manager).prepareGitRepoPath(0xc420206280, 0xc420229092, 0x6, 0xc4202290c0, 0x9, 0xc4202114d0, 0x2c, 0xc420229098, 0x6, 0xc420211500, ...)
	/go/src/github.com/rancher/catalog-service/manager/local.go:86 +0x339
github.com/rancher/catalog-service/manager.(*Manager).prepareRepoPath(0xc420206280, 0xc420229092, 0x6, 0xc4202290c0, 0x9, 0xc4202114d0, 0x2c, 0xc420229098, 0x6, 0xc420211500, ...)
	/go/src/github.com/rancher/catalog-service/manager/local.go:32 +0x99
github.com/rancher/catalog-service/manager.(*Manager).refreshCatalog(0xc420206280, 0xc420229092, 0x6, 0xc4202290c0, 0x9, 0xc4202114d0, 0x2c, 0xc420229098, 0x6, 0xc420211500, ...)
	/go/src/github.com/rancher/catalog-service/manager/manager.go:102 +0x82
github.com/rancher/catalog-service/manager.(*Manager).refreshConfigCatalogs(0xc420206280, 0x1, 0x0, 0x0)
	/go/src/github.com/rancher/catalog-service/manager/manager.go:73 +0x2ae
github.com/rancher/catalog-service/manager.(*Manager).RefreshAll(0xc420206280, 0x1, 0x0, 0x0)
	/go/src/github.com/rancher/catalog-service/manager/manager.go:39 +0x38
github.com/rancher/catalog-service/cmd.refresh(0xc420206280, 0x1)
	/go/src/github.com/rancher/catalog-service/cmd/root.go:177 +0x38
github.com/rancher/catalog-service/cmd.autoRefresh(0xc420206280, 0x12c)
	/go/src/github.com/rancher/catalog-service/cmd/root.go:186 +0x4f
created by github.com/rancher/catalog-service/cmd.run
	/go/src/github.com/rancher/catalog-service/cmd/root.go:145 +0x50e
time="2017-07-18T19:29:50Z" level=info msg="Starting Catalog Service (port 8088, refresh interval 300 seconds)" 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x6c23fa]`

**Comment by amy** [comment]
To replicate issue:
Turn off internet connection
Refresh catalogs

**Comment by amy** [comment]
In the situation for an air-gapped network, this is the workaround fix for `v1.6.3` and `v1.6.4`:
Change the `catalog.url` setting via `http://<your-ip>/v2-beta/settings/catalog.url` to
```
{"catalogs":{"community":{"url":"<your-ip>","branch":"master"},"library":{"url":"<your-ip>","branch":"${RELEASE}"}}}
```

Delete the catalog entries in the catalog table:
`docker ps`
`docker exec -it <your-container-id> mysql cattle`
`SELECT * FROM catalog;`
`DELETE FROM catalog WHERE id = <id of library> OR id = <id of community>;`

**Comment by amy** [comment]
Another relevant issue is: https://github.com/rancher/rancher/issues/9401 in which a kubernetes install behind a proxy does not show the default environment templates.

**Comment by deniseschannon** [comment]
Tested and validated using v1.6.5-rc1 by @LLParse and @chrisurwin with airgapped setup and proxys.
