### ISSUE TITLE
When external volume names are reused after a volume with driver_opts onRemove=retain, volumes would get purged on volume delete.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#9381]
Rancher server version - Build from v1.6 branch
rancher/storage-nfs:v0.8.4

Steps to reproduce the problem:

1. Create Volume - "abc" (using "Add Volumes" option from Infrastructure Storage) with driver_opt onRemove=retain

2. Create a service - S1with this volume - "abc" using UI . Write some contents.

3. Delete service S1.

4. Delete volume - "abc"  — Volume gets deleted from rancher-server. But it continues to be in nfs server as expected.

5. Create another service - S2  using the same volume name - "abc" using UI.

This results in a new volume getting created in rancher-server with no driver_opt set.
Existing volume from rancher-nfs gets used for this service as expected.

Delete service S2.
Delete volume "abc". 

Volume gets deleted from rancher-server. Volume also gets deleted in nfs server.

**Comment by cjellick** [comment]
@sangeethah This is not a bug, this is the intended and expected behavior. We don't propagate driver opts when a volume is deleted and another with the same name is created.

**Comment by vincent99** [comment]
Makes sense to me.. you created and deleted a volume, and it was retained.  That life cycle ends at 4.  5 is a new volume that happens to have the same name; it doesn't have retain, so when you delete it the underlying data should be deleted.  The directory doesn't "remember" that it was supposed to be retained for a different volume long gone.

If anything, the problem to solve is that at step 5 it is unknown and unknowable (without direct access to the NFS server) if creating "abc" is going to give me a fresh new empty volume or a recycled pre-owned one that's already got someone's stuff in it.  Seems like you should have to explicitly say reusing is ok and it should error if you don't and the directory already exists.

**Comment by sangeethah** [comment]
The other issue is the automatic creation of volumes ( which happens on creation of service with a volume that does not exist in rancher-server) not having the ability to set any driver_opts.

**Comment by LLParse** [comment]
The explicit "reusing is ok" flag, defaulted to false, would be really helpful in testing. I've run into strange test results more than once because I was reusing a host/export in different environments and the volume names happened to collide.
