### ISSUE TITLE
Support Aliyun DNS in Rancher external-dns

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#9382]

**Comment by hongxiaolu** [comment]
Test passed！

You need to map the port when running the service and visit your service through   <service_name>.<stack_name>.<environment_name>.<root_domain>: port（ If it's port 80, there's no need to add it here .

**Comment by yasker** [comment]
Fixed and merged. Close this issue.

**Comment by loganhz** [comment]
thanks @janeczku @yasker for your merge

here is the PR for community-catalog

https://github.com/rancher/community-catalog/pull/600

**Comment by kingsd041** [comment]
Tested with rancher-server version- v1.6.10 with rancher/external-dns: v0.7.5
Test passed. 
But I found some new problems:
https://github.com/rancher/rancher/issues/10063
https://github.com/rancher/rancher/issues/10076  
https://github.com/rancher/rancher/issues/10077
