### ISSUE TITLE
K8s host(s) go into NotReady state after IPsec forced upgrade

### ISSUE THREAD

**Issue by moelsayed** [rancher/rancher#9389]
**Rancher versions:**
rancher/server: v1.6.4

**Infrastructure Stack versions:**
healthcheck: v0.3.1
ipsec: rancher/net:v0.11.3
network-services: rancher/metadata:v0.9.2 rancher/network-manager:v0.7.4
kubernetes (if applicable): rancher/k8s:v1.6.6-rancher1-4

**Docker version: (`docker version`,`docker info` preferred)**
1.12
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
GCE
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes
**Steps to Reproduce:**
The problem happens only sometime,the steps are:

- Deploy kubernetes environment
- Register 4 Hosts
- force upgrade ipsec to the same version multiple times.

**Results:**

One or more hosts go into NotReady state. They eventually go back to Ready state after up to 10 or 15 minutes.

**Comment by leodotcloud** [comment]
As part of the fix for: #8684 (related PRs: rancher/cattle#2760, rancher/cattle#2766), the metadata started having information about stopped containers. Due to this during ipsec service upgrade, two tunnels started getting established for both running and stopped ipsec containers. This caused a disruption in traffic over the ipsec tunnel.

Fix would be to use only "running" or "starting" containers to consider for setting up tunnels.

**Comment by galal-hussein** [comment]
Rancher Server: v1.6.6-rc6

After running stress tests multiple times that force upgrade ipsec over than 20 times, at each iteration all kube nodes are back to Ready state, and can't see this issue anymore.

**Comment by leodotcloud** [comment]
Notes:
- build containers `map[hostIP:hostPort/protocol]` but only for running/starting containers
- Read conntrack entries, build the lookup key based on the info in the entry.
- lookup the map built previously. If hit, check if the conntrack entry has correct ip address of container. else don't do anything.

So the case of stopping containers losing traffic will happen when there is a new starting/running container with a different managed IP and with the same expose port on the same host. (This basically logically not possible)

This logic is mainly for upgraded containers .... An old container has IP: `o.o.o.o` with expose port say 4500/tcp. When it's upgraded a new container with IP: `n.n.n.n`, the old conntrack entry which was pointing to the old IP need to be flushed.

**Comment by leodotcloud** [comment]
@sangeethah @moelsayed Fixed in `rancher/network-manager:v0.7.7`.
