### ISSUE TITLE
[Q] LB service host ports

### ISSUE THREAD

**Issue by cavemandaveman** [rancher/rancher#9392]
Sorry if this has been asked before, but I couldn't find previous issues or documentation that explain this.

I have the Rancher load balancer (rancher/server:v1.6.4 and rancher/lb-service-haproxy:v0.7.5) set up to forward port 443 to a service. This works correctly but I am unsure _how_ it is working. 

-  `docker ps` does not show host port 443 being routed to the LB container. 
-  Host commands like `ss` and `netstat` do _not_ show that any process is listening on 443. 
-  `iptables` shows no rules for port 443.

I am confused as to how I can successfully connect to my host on 443 externally without seeing it explicitly being routed on the host.

**Comment by cavemandaveman** [comment]
Turns out `iptables` does show the rules, I just wasn't looking in the right place. 

Rancher puts its stuff in a CATTLE_PREROUTING chain, and you need to look at the NAT table to see these.
`iptables -L -nt nat` will show them.

**Comment by aemneina** [comment]
@cavemandaveman sounds like you've solved it on your own... safe to close?

**Comment by cavemandaveman** [comment]
Yes, thank you.
