### ISSUE TITLE
Rancher CLI should return non-zero exit status on error

### ISSUE THREAD

**Issue by bradjones1** [rancher/rancher#9393]
Using CLI version `0.6.2`, commands like `rancher inspect` print an error yet exit with a status of 0, which makes testing on the exit status impossible.

**Steps to Reproduce:**

```bash
bradj@home:~$ rancher -v
rancher version v0.6.2
bradj@home:~$ rancher inspect stackdoesntexist/web
error stackdoesntexist/web: Not found: stackdoesntexist/web
bradj@home:~$ echo $?
0
```

**Results:**
The exit status is 0, but would be more helpful if it were `!= 0`.

**Comment by bradjones1** [comment]
In the meantime, I have been piping output for select commands that would output json results through `jq`, which will return a non-zero exit status if it can't parse the result, e.g., on an error message.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

**Comment by bartoszcisek** [comment]
I'm frustrated. This is another bug closed with the same statement. Not going to invest time in rancher 2.x and risk being left behind with unsupported branch.

**Comment by bradjones1** [comment]
@bartoszcisek Software upgrades are inevitable; end of life decisions are also inevitable. I am guessing you're an open-source user (as am I) and as such paid nothing for software you clearly believe is critical to your operation. I'd suggest cooling down the tone. If you truly need a bug fixed in 1.x, I'm sure Rancher would be happy to talk to you about becoming a paying customer.
