### ISSUE TITLE
Any user level can create new environments.. should have a user acl for this permission.

### ISSUE THREAD

**Issue by skyscooby** [rancher/rancher#9396]
**Rancher versions:**
rancher/server: 1.6.4
rancher/agent: 1.2.5

**Steps to Reproduce:**
Log into a rancher server as any user in directory.
User can then create environments possibly negatively effecting existing environments if they bootstrap many nodes into a new environment they created when the existing server is managing production loads.. server instance then could become overloaded and impact important environments.

**Expected Results:**
I'd like to give users access to see their environment but not allow them to create new environments as a result. Only admin users and users specifically granted this permission should be able to create new environments to be managed on the server.

**Comment by amy** [comment]
@skyscooby  a partial solution is that I can give you instructions to disallow *all* non-admin users from creating environments. With this, only admin users are able to activate, deactivate, delete, create, and update environments.

Locally create the following files:
```
// user-auth.json
{
    "authorize" : {
        "project" : "r",
        "project.resourceActions.activate": "",
        "project.resourceActions.deactivate": ""
    }
}
```
```
// admin-auth.json
{
    "authorize" : {
        "project" : "crud",
        "project.resourceActions.activate": "c",
        "project.resourceActions.deactivate": "c"
    }
}
```

Then adjust and run the following command:
```
docker run -d -p 8080:8080 \
  -v /local/path/to/admin-auth.json:/usr/share/cattle/war/schema/admin/admin-auth.json.d/overrides/admin-auth.json \
  -v /local/path/to/user-auth.json:/usr/share/cattle/war/schema/user/user-auth.json.d/overrides/user-auth.json \
  rancher/server:latest
```

**Comment by amy** [comment]
@skyscooby  a partial solution for the **upcoming** release `v1.6.6` is that I can give you instructions to disallow **all** non-admin users from creating environments. With this, only admin users are able to activate, deactivate, delete, create, and update environments.

Locally create the following files:
```
// user-auth.json
{
    "authorize" : {
        "project" : "r",
        "project.resourceActions.activate": "",
        "project.resourceActions.deactivate": ""
    }
}
```
```
// admin-auth.json
{
    "authorize" : {
        "project" : "crud",
        "project.resourceActions.activate": "c",
        "project.resourceActions.deactivate": "c"
    }
}
```

Then adjust and run the following command:
```
docker run -d -p 8080:8080 \
  -v /local/path/to/admin-auth.json:/usr/share/cattle/war/schema/admin/admin-auth.json.d/overrides/admin-auth.json \
  -v /local/path/to/user-auth.json:/usr/share/cattle/war/schema/user/user-auth.json.d/overrides/user-auth.json \
  rancher/server:latest
```

**Comment by deniseschannon** [comment]
@skyscooby The comments that @amy had provided on how you would be able to do this are not going to be applicable for this release. Apologize for the confusion. We're looking for a proper solution in 2.0.

**Comment by cjellick** [comment]
We are discussing implementing in the 1.6.x line as a simple setting the admin can set. It would be like:
`environment.manage.project.roles=admin,user` which you could update to just `admin`.

**Comment by skyscooby** [comment]
This sounds reasonable. Have you considered the use case whereby a DevOps style organisation would like to get a rancher environment stood up from scratch from say automation like Ansible without human intervention in the UI using a custom infrastructure stack and settings such as above? Am I right to assume at this point this basically means making direct API calls to the initial state of the rancher instance?

**Comment by deniseschannon** [comment]
In 2.0, we've introduced much more fine grain RBAC control. Users can now be given permissions to create clusters/projects/namespaces. 

We won't be backporting this kind of detailed RBAC into 1.6 line due to the complex architectural changes required. 

Please watch our [Tech Preview 2 meetup](https://www.youtube.com/watch?v=ld7ctOg3waM&t=4s) to learn more about the features  in 2.0 in Tech Preview 2.
