### ISSUE TITLE
Exported config file does not have  requestedIpAddress field for a service created with requestedIpAddress.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#9398]
Rancher versions: Build from v1.6 branch

Create a service by passing requestedIpAddress field in launch_config.
View the export config file for this service.
Exported config file does not have  requestedIpAddress field.

**Comment by vincent99** [comment]
That is not a settable field.  The label is the only way to request an ip.

**Comment by StrongMonkey** [comment]
@vincent99 It is a settable field for launchConfig, but i think in UI and compose they both set them as label
