### ISSUE TITLE
Documentation out of date regarding dedicated kube planes

### ISSUE THREAD

**Issue by skyscooby** [rancher/rancher#9399]
**Rancher versions:**
rancher/server: 1.6.4
rancher/agent: 1.2.5

**Steps to Reproduce:**
Document states that proxy and kubelet won't be/shouldn't be scheduled on separated control plane after upgrading an environment with isolated planes. 
http://rancher.com/docs/rancher/v1.6/en/kubernetes/upgrading/
"Optional: If you want the kubelet and proxy to be removed from the host, you can perform an upgrade on the kubelet service and the proxy service, without changing any settings. Ensure all pods are deleted on the hosts before running this upgrade."

**Results:**
It seems like actually the proxy is still scheduled on all nodes regardless and a different container 'kublet-unschedulable' will be targeted to the data and orchestration plane.

**Comment by joshwget** [comment]
The docs are slightly out of date here. The kubelets running on orchestration and etcd nodes will only run daemon sets and not general workloads.
