### ISSUE TITLE
addon-starter-1 and kubectl-shell-1 do not migrate when primary orchestration node fails

### ISSUE THREAD

**Issue by skyscooby** [rancher/rancher#9400]
**Rancher versions:**
rancher/server: 1.6.4
rancher/agent: 1.2.5

**Infrastructure Stack versions:**
healthcheck:0.3.1
ipsec:holder
network-services:0.7.4
scheduler:v1.6.6-rancher1-4
kubernetes (if applicable): v1.6.6-rancher1-4

**Docker version: (`docker version`,`docker info` preferred)**
1.12.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
4.4.0-83-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare Metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher, external DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes with split control planes.

**Steps to Reproduce:**
create two orchestration=true nodes
(also using isolated 3 etcd nodes and X compute nodes)

**Results:**
Shutdown -h now on the host with the active kuberenetes components.
After rancher sees host disconnected, many of the services shift over to second orchestration=true node. But addon-starter-1 and kubectl-shell-1 do not and this stops the CLI from working via the rancher server UI..

**Comment by joshwget** [comment]
This was caused by the lack of a healthcheck on these services. It was added to kubectl-shell already and #9577 covers addon-starter. Thanks for filing @skyscooby.
