### ISSUE TITLE
Kubernetes install behind a Proxy

### ISSUE THREAD

**Issue by lucevers** [rancher/rancher#9401]
**Rancher versions:**
rancher/server:
rancher/agent:

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
     sudo docker info
Containers: 4
 Running: 4
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 1.12.6
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 43
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null overlay bridge host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-83-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 56
Total Memory: 251.8 GiB
Name: CoreGAM1
ID: EUW4:SHD3:YGRD:F7PA:SUYP:FVZ7:3JQX:ICA7:K6YI:PUL7:KGZP:IP5D
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: http://10.124.11.215:8080
No Proxy: localhost,127.0.0.1,<server1>,<server2>,<server3>
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
  cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

uname -r
4.4.0-83-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-Metal
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
3 servers
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes
**Steps to Reproduce:**
Start installing 
**Results:**

**installing Kubernetes**

Without Proxy server there are no problems. Kubernetes rancher/k8s:v1.5.4-rancher1-4.

**Behind a proxy server** I'm missing the Default Environment Templates.
So I can only Add a Template with the new Kubernetes 1.6 which is not working.
Kubernetes 1.6 installation Blocks on Starting services (2 of 12)
We don't see blocking domains in the Proxy!
The proxy is configured on the Ubuntu server (/etc/environments) + for docker systemd config file.

**Comment by aemneina** [comment]
@lucevers see related ticket, should be fixed in a recent rc, care to try it there?

**Comment by LLParse** [comment]
Tested with Rancher Server `v1.6.5` and Kubernetes `1.6.6` (template `v1.6.6-rancher1-4`). Setup server and 3 nodes (RancherOS 1.0.3) behind a Squid proxy. Observed Rancher catalog and Docker Registry traffic passing through the proxy.

Tested with Rancher Server `v1.6.6-rc4` and Kubernetes `1.7.2` (template `v1.7.2-rancher5`). Setup server and 3 nodes (RancherOS 1.0.3) behind a Squid proxy. Observed Rancher catalog and Docker Registry traffic passing through the proxy.

Hang tight and I will test with Ubuntu 16.04 by configuring proxy variables in `/etc/environment`.

**Comment by moelsayed** [comment]
@lucevers I tested with the following setup:
* Rancher server v1.6.8-rc4/k8s:v1.7.4-rancher1
* Ubuntu 16.04
* squid proxy configured with /etc/environment system wide and docker systemd files. 

I managed to complete a successful deployment with k8s for 3 hosts with no problems. Could you please try this configuration and confirm it went well ?

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
