### ISSUE TITLE
Cannot add custom host to server: Timeout getting IP address

### ISSUE THREAD

**Issue by DarianAnjuhal** [rancher/rancher#9402]
Hi there,

unfortunately I cannot add a second host to a running server. I would be nice if somebody can point me to the correct direction. I don't even know  how to debug the issue.

On docker3 a rancher server and a client is running on the same server
I want to connect a second host docker2 to the rancher server which does not work.
The host docker2 appears in the host overview but the following 3 infrastructure containers cannot start:

***Infrastructure***
rancher/healthcheck:v0.2.3
rancher/net:holder
rancher/net:v0.9.4

***Rancher versions:***
rancher/server:v1.5.2
rancher/agent:v1.2.1

Error: 'Timeout getting IP address' (then the container is removed automatically and started again )

***Docker version***
 17.05.0-ce, build 89658be (Untested docker version -> but i think thats not the problem?)

Port 500 and 4500 should be open:

***nc -vz -u docker3.mydomain.com 500***
DNS fwd/rev mismatch: docker3.mydomain.com != v22xxxxx.otherdomain.com
docker3.mydomain.com [1xx.xxx.xxx.xxx] 500 (isakmp) open

***nc -vz -u docker3.mydomain.com 4500***
DNS fwd/rev mismatch: docker3.mydomain.com != v22xxxxx.otherdomain.com
docker3.mydomain.com [1xx.xxx.xxx.xxx] 4500 (ipsec-nat-t) open

How can I figure out the problem in order to solve this issue?

Thx and bye
Darian

**Comment by aemneina** [comment]
@DarianAnjuhal in the infrastructure->hosts page, do all your hosts have unique ip addresses? can your ipsec containers ping each other? Any interesting logs in the metadata containers?

**Comment by DarianAnjuhal** [comment]
Thank you for your answer. I used the information from https://github.com/rancher/rancher/issues/9367 in order the solve the issue. The "Template version not found" is gone.
But now the healthcheck stuck in initializing. Is this something I can ignore?

Thx for your help and your informations
Darian

**Comment by aemneina** [comment]
Hey @DarianAnjuhal did you ever solve your health check issue? Thats typically ipsec overlay not working. Please try a more modern version of rancher and if you see errors there, feel free to open a new issue with the problem.

**Comment by DarianAnjuhal** [comment]
Thx i did the same one week ago and its working now.
