### ISSUE TITLE
chown operation not permitted with mongo:3.4 when mounting NFS volume

### ISSUE THREAD

**Issue by jgato** [rancher/rancher#9403]
**Rancher versions:1.6.2**
rancher/server: 1.6:
rancher/agent: 1.2.2

**Docker version: 
```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 21:44:32 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 21:44:32 2016
 OS/Arch:      linux/amd64
```
**Operating system and kernel**: VERSION="14.04.4 LTS, Trusty Tahr", Linux env06 3.13.0-86-generic #131-Ubuntu SMP Thu May 12 23:33:13 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Type/provider of hosts: VirtualMAchines

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Template: Cattle**

Trying to run mongoDB:3.4 with a shared volume with NFS. I have already an NFS Sever and Rancher-NFS configured. My own containers can mount NFS volumes, no problem. But Mongo (or others like Rabbit) cannot mount because a chwon issue:

```
Expected state running but got error: Error response from daemon: chown /var/lib/rancher/volumes/rancher-nfs/MONGO-Storage: operation not permitted
```
I have raised this issue also in the [mongo repository](https://github.com/docker-library/mongo/issues/127#issuecomment-315981731), but without success. Any help about this?

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
