### ISSUE TITLE
kube-system add-on are schedule on etcd=true node node..

### ISSUE THREAD

**Issue by skyscooby** [rancher/rancher#9406]
**Rancher versions:**
rancher/server: 1.6.4
rancher/agent: 1.2.5

**Infrastructure Stack versions:**
defaults for template below.

**Docker version: (`docker version`,`docker info` preferred)**
1.12.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04 LTS 2

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
4.4.0-83-generic 

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher imbedded DB.

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kube 1.6.6-rancher1-4 template with plane isolation required and Add-Ons enabled.

**Steps to Reproduce:**
Create two orchestration=true nodes.
Create three etcd=true nodes.
Wait.. 

**Results:**
kube-system pods for add-ons will be scheduled onto an unscheduable node.. (etcd=true in my case).
Would expect that these pods would not be scheduled until an available compute=true node is added into the cluster.

**Comment by skyscooby** [comment]
![kube-system on unschedulable node](https://user-images.githubusercontent.com/4450935/28431186-725844f8-6d51-11e7-9dae-ed158db8cb01.png)

**Comment by joshwget** [comment]
Does `xcd1` have a service named `kubelet` or `kubelet-unschedulable`? Can you show the output of `kubectl get node`?

**Comment by skyscooby** [comment]
Yes xcd1 has kubelet-unschedulable and the node is marked as SchedulingDisabled in get nodes. I also noticed DaemonSet are is scheduled to these nodes as well..

**Comment by joshwget** [comment]
DaemonSets being scheduled to these nodes is intended. Add-ons being scheduled to them is definitely not intended.

Is this consistently reproducible for you? I tried following your steps was wasn't able to hit the same issue.

**Comment by skyscooby** [comment]
I will have to get back to you.. I have been using the same hosts over and over again thinking that if I nuked everything in Docker and the Docker volumes that I'd be good to reinstall but I have since discovered some state information is preserved in /var/lib/rancher and /var/lib/kubelet via bind mounts which possibly was present from a different environment these host were part of prior.. So I will attempt this again at some point with freshly provisioned systems but I can't interrupt some testing we are doing with them at the moment.

**Comment by joshwget** [comment]
Labeling this as a docs issue. I'm pretty sure the issue here was the leftover `/var/lib/kubelet` directory. We should document the procedure for cleaning hosts for reuse.

**Comment by deniseschannon** [comment]
we already document how you should clean up kuberentes. 

http://rancher.com/docs/rancher/v1.6/en/kubernetes/deleting/

**Comment by superseb** [comment]
Let us know if there is more help needed on this.
