### ISSUE TITLE
Close http response body

### ISSUE THREAD

**Issue by amy** [rancher/rancher#9410]
http body in catalog service was not closed after checking for the SHA. This would trigger an issue similar to https://github.com/rancher/rancher/issues/9306

The fix is here: https://github.com/rancher/catalog-service/pull/111

**Comment by cjellick** [comment]
You can test by adding a custom catalog and continually hitting the refresh button for it in the UI while also looking at the connections in the rancher/server container like this:`
```
netstat -anp | grep catalog
```

**Comment by sabiodelhielo** [comment]
Verified on rancher/server:v1.6.6-rc1

Added custom catalog, the number of connections did not grow per refresh of the page:

root@0bed65d56729:/# netstat -anp | grep catalog
tcp        0      0 172.17.0.2:41630        35.160.158.227:443      ESTABLISHED 196/rancher-catalog
tcp        0      0 127.0.0.1:55334         127.0.0.1:3306          ESTABLISHED 196/rancher-catalog
tcp        0      0 127.0.0.1:55356         127.0.0.1:3306          ESTABLISHED 196/rancher-catalog
tcp      168      0 172.17.0.2:50332        192.30.255.116:443      CLOSE_WAIT  196/rancher-catalog
tcp6       0      0 :::8088                 :::*                    LISTEN      196/rancher-catalog
tcp6       0      0 127.0.0.1:8088          127.0.0.1:56584         ESTABLISHED 196/rancher-catalog
tcp6       0      0 127.0.0.1:8088          127.0.0.1:56578         ESTABLISHED 196/rancher-catalog
tcp6       0      0 127.0.0.1:8088          127.0.0.1:56588         ESTABLISHED 196/rancher-catalog
tcp6       0      0 127.0.0.1:8088          127.0.0.1:56586         ESTABLISHED 196/rancher-catalog
tcp6       0      0 127.0.0.1:8088          127.0.0.1:55210         ESTABLISHED 196/rancher-catalog
tcp6       0      0 127.0.0.1:8088          127.0.0.1:56582         ESTABLISHED 196/rancher-catalog
tcp6       0      0 127.0.0.1:8088          127.0.0.1:55254         ESTABLISHED 196/rancher-catalog
tcp6       0      0 127.0.0.1:8088          127.0.0.1:55314         ESTABLISHED 196/rancher-catalog
root@0bed65d56729:/# netstat -anp | grep catalog
tcp        0      0 172.17.0.2:41630        35.160.158.227:443      ESTABLISHED 196/rancher-catalog
tcp        0      0 127.0.0.1:55334         127.0.0.1:3306          ESTABLISHED 196/rancher-catalog
tcp        0      0 127.0.0.1:55356         127.0.0.1:3306          ESTABLISHED 196/rancher-catalog
tcp      168      0 172.17.0.2:50332        192.30.255.116:443      CLOSE_WAIT  196/rancher-catalog
tcp6       0      0 :::8088                 :::*                    LISTEN      196/rancher-catalog
tcp6       0      0 127.0.0.1:8088          127.0.0.1:56584         ESTABLISHED 196/rancher-catalog
tcp6       0      0 127.0.0.1:8088          127.0.0.1:56578         ESTABLISHED 196/rancher-catalog
tcp6       0      0 127.0.0.1:8088          127.0.0.1:56588         ESTABLISHED 196/rancher-catalog
tcp6       0      0 127.0.0.1:8088          127.0.0.1:56586         ESTABLISHED 196/rancher-catalog
tcp6       0      0 127.0.0.1:8088          127.0.0.1:55210         ESTABLISHED 196/rancher-catalog
tcp6       0      0 127.0.0.1:8088          127.0.0.1:56582         ESTABLISHED 196/rancher-catalog
tcp6       0      0 127.0.0.1:8088          127.0.0.1:55254         ESTABLISHED 196/rancher-catalog
tcp6       0      0 127.0.0.1:8088          127.0.0.1:55314         ESTABLISHED 196/rancher-catalog

....
root@0bed65d56729:/# netstat -anp | grep catalog
tcp        0      0 127.0.0.1:55494         127.0.0.1:3306          ESTABLISHED 196/rancher-catalog
tcp        0      0 127.0.0.1:55578         127.0.0.1:3306          ESTABLISHED 196/rancher-catalog
tcp6       0      0 :::8088                 :::*                    LISTEN      196/rancher-catalog
tcp6       0      0 127.0.0.1:8088          127.0.0.1:56584         ESTABLISHED 196/rancher-catalog
tcp6       0      0 127.0.0.1:8088          127.0.0.1:56578         ESTABLISHED 196/rancher-catalog
tcp6       0      0 127.0.0.1:8088          127.0.0.1:56588         ESTABLISHED 196/rancher-catalog
tcp6       0      0 127.0.0.1:8088          127.0.0.1:56586         ESTABLISHED 196/rancher-catalog
tcp6       0      0 127.0.0.1:8088          127.0.0.1:55210         ESTABLISHED 196/rancher-catalog
tcp6       0      0 127.0.0.1:8088          127.0.0.1:56582         ESTABLISHED 196/rancher-catalog
tcp6       0      0 127.0.0.1:8088          127.0.0.1:55254         ESTABLISHED 196/rancher-catalog
tcp6       0      0 127.0.0.1:8088          127.0.0.1:55314         ESTABLISHED 196/rancher-catalog
