### ISSUE TITLE
[RFE] Custom separator to lb name generated by ingress controller

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#9412]
Today ingress controller creates load balancers in a format of:

```
<stackname>-rancherlb-<ingressname>
```

rancherlb is a static part, and there was a request to make it customizable via flag in kubernetes template

**Comment by alena1108** [comment]
@galal-hussein can be tested with v1.7.1-rancher2 template

**Comment by galal-hussein** [comment]
Rancher Version: v1.6.6-rc2
Kubernetes Version: v1.7.1-rancher2

I was able to start kubernetes with a custom name for ingress separator, and i verified that the new ingresses will take that name:
![ingress-custom-name](https://user-images.githubusercontent.com/3309968/28491480-2cc2d3f8-6efb-11e7-9f3a-1b42f9f095b1.png)
