### ISSUE TITLE
Run VXLAN in host namespace

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#9414]
Currently, vxlan (rancher-net) runs in `router` namespace. Need to change this to `--net=host` and make VXLAN work.

- Create a new catalog item vxlan-hostns
- Check if there are any code changes needed for this.

**Comment by niusmallnan** [comment]
If do this, really need to do some updates in the network-manager.
For example, about `LocalNetworks` https://github.com/rancher/plugin-manager/blob/master/network/local.go#L13 :
```
...
for _, aContainer := range service.Containers {
	if aContainer.HostUUID == host.UUID {
		routers[aContainer.NetworkUUID] = aContainer
	}
}
...
```
Because the router's network into `--net=host` network, which may lead to confusion of other programs.

Other questions that I may need for further testing.

**Comment by leodotcloud** [comment]
@niusmallnan yes definitely we would need changes at multiple places.

**Comment by sangeethah** [comment]
Tested with rancher server from v1.6 branch "library" pointing to rancher-catalog from v1.6-development branch using rancher/net:v0.12.0
Deployed a cattle setup using vxlan having 3 hosts.
Validation tests run on this setup reported success except for known issues.

Able to upgrade vxlan stack from previous version of rancher-server  (using rancher/net:v0.11.9) successfully. While upgrade is in progress there is loss of network connection between hosts  , which results in health check containers to get recreated.

All validations done after upgrade of vxlan stack succeeds.

**Comment by leodotcloud** [comment]
Targeted for 1.6.11 release.

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
