### ISSUE TITLE
Decrypt ipsec packets with the current keys

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#9415]
Currently if we do a `tcpdump -i eth0 -n -v '(port 4500)'` inside the ipsec-router container, all the packets are encrypted and we cannot see the payload. We need a way to decrypt the packets using the keys programmed in the linux kernel.

There are two options, need to see which one would be easier.
1) Create a simple go program which reads the current ipsec keys from the kernel, starts packet capture and uses these keys to decrypt the packets before printing them on the screen.
References:
- https://github.com/google/gopacket
- http://www.devdungeon.com/content/packet-capture-injection-and-analysis-gopacket

2) Check the tcpdump source code if it's easier to add a custom dissector/printer. 
Reference:
- https://github.com/the-tcpdump-group/tcpdump
- https://github.com/the-tcpdump-group/tcpdump/blob/be1e19f50cc0d88bdb0140ed6d99574249a3c297/print-isakmp.c

**Comment by yasker** [comment]
Is it possible for us to use wireshark?

https://wiki.strongswan.org/projects/strongswan/wiki/CorrectTrafficDump#Decrypting-IKEESP-traffic-in-Wireshark

**Comment by niusmallnan** [comment]
@leodotcloud @yasker 
It is ok to use Wireshark. I wrote a simple tool.
https://github.com/niusmallnan/decrypt-ipsec

**Comment by yasker** [comment]
Great! Thanks @niusmallnan !

**Comment by leodotcloud** [comment]
@niusmallnan Thanks for the script to help grab the keys from the container. Also it can be improved upon by figuring out the docker id of the router container automatically. `docker ps -a | grep ipsec-router | awk '{print $1}'`
Following the instructions from strongswan website, I was able to decrypt the packets using Wireshark. But it's very tedious process to copy the pcap file out and then manually enter the SA configs.

@yasker Let's keep this issue open for now and get back to it when we have some time. It's very handy to be able to decrypt the packets on a live setup rather than copying the pcap files out.

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
