### ISSUE TITLE
healthcheck/healthcheck stuck in Initializing

### ISSUE THREAD

**Issue by khulfreedos** [rancher/rancher#9422]
*Describe your issue here*
Please see Logs:
7/21/2017 6:25:41 PMtime="2017-07-21T10:25:41Z" level=info msg="healthCheck -- no changes in haproxy config\n"
7/21/2017 6:25:42 PMtime="2017-07-21T10:25:42Z" level=info msg="Scheduling apply config"
7/21/2017 6:25:42 PMtime="2017-07-21T10:25:42Z" level=info msg="healthCheck -- no changes in haproxy config\n"
7/21/2017 6:25:42 PMtime="2017-07-21T10:25:42Z" level=info msg="Scheduling apply config"
7/21/2017 6:25:42 PMtime="2017-07-21T10:25:42Z" level=info msg="healthCheck -- no changes in haproxy config\n"
7/21/2017 6:25:43 PMtime="2017-07-21T10:25:43Z" level=info msg="Scheduling apply config"
7/21/2017 6:25:43 PMtime="2017-07-21T10:25:43Z" level=info msg="healthCheck -- no changes in haproxy config\n"
7/21/2017 6:25:44 PMtime="2017-07-21T10:25:44Z" level=info msg="Scheduling apply config"
7/21/2017 6:25:44 PMtime="2017-07-21T10:25:44Z" level=info msg="healthCheck -- no changes in haproxy config\n"
7/21/2017 6:25:45 PMtime="2017-07-21T10:25:45Z" level=info msg="5f277538-d4f9-45c7-8c0c-1d88effaa008_4c17b77a-8b42-4730-a9fa-d284f53d3e0d_1=DOWN"
7/21/2017 6:26:46 PMtime="2017-07-21T10:26:46Z" level=info msg="Scheduling apply config"

root@siemnodes1:~# docker -v
Docker version 17.06.0-ce, build 02c1d87
root@siemnodes1:~# docker ps -a
CONTAINER ID        IMAGE                            COMMAND                  CREATED             STATUS              PORTS               NAMES
5b702958f3b3        rancher/net:v0.11.3              "/rancher-entrypoi..."   8 minutes ago       Up 8 minutes                            r-ipsec-ipsec-router-2-a3b92f1e
291c3ad9c14e        rancher/dns:v0.15.1              "/rancher-entrypoi..."   9 minutes ago       Up 9 minutes                            r-network-services-metadata-dns-9-00bc8a6d
3db86f027487        rancher/network-manager:v0.7.4   "/rancher-entrypoi..."   9 minutes ago       Up 9 minutes                            r-network-services-network-manager-6-eada9967
8736bedac864        rancher/healthcheck:v0.3.1       "/.r/r /rancher-en..."   9 minutes ago       Up 9 minutes                            r-healthcheck-healthcheck-8-592019bc
e0c96468cd64        rancher/net:v0.11.3              "/rancher-entrypoi..."   9 minutes ago       Up 9 minutes                            r-ipsec-ipsec-cni-driver-2-e1c29bce
23be440fe5f0        rancher/metadata:v0.9.2          "/rancher-entrypoi..."   9 minutes ago       Up 9 minutes                            r-network-services-metadata-9-2b1f2057
7e69f7b95b74        rancher/net:holder               "/.r/r /rancher-en..."   9 minutes ago       Up 9 minutes                            r-ipsec-ipsec-2-bca5c9c9
16caec08cf95        rancher/agent:v1.2.5             "/run.sh run"            9 minutes ago       Up 9 minutes                            rancher-agent

docker
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.5` Cattle: `v0.182.1` UI: `v1.6.9` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`hosts.index`|

**Comment by khulfreedos** [comment]
Hello, please help me on this. Thank you!

**Comment by aemneina** [comment]
can your healthcheck containers ping each other? Sounds like you have an issue with your ipsec tunnel.

**Comment by khulfreedos** [comment]
@aemneina I can not ping the healthcheck container using execute shell.

**Comment by superseb** [comment]
Do you have UDP port 500 and 4500 opened between the hosts running `rancher/agent` ?

**Comment by khulfreedos** [comment]
I've added the ports in the rule and it works. Thank you!
