### ISSUE TITLE
1.6.5 Repeating errors

### ISSUE THREAD

**Issue by bacheson** [rancher/rancher#9430]
**Rancher versions:**
rancher/server: 1.6.5
rancher/agent: 1.2.5

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
1.12.6
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
GCE
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Sing node
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**
view syslog
**Results:**

repeating errors:

Jul 21 15:12:37 instance-group-production-public-1-qn0d dockerd[1766]: time="2017-07-21T15:12:37.843854455-04:00" level=error msg="collecting stats for 89664d3c019aa871e0c12212c92b4e17735a66808f572578fb59cb9c47fe3712: invalid id: "
Jul 21 15:12:38 instance-group-production-public-1-qn0d dockerd[1766]: time="2017-07-21T15:12:38.861396598-04:00" level=error msg="collecting stats for 89664d3c019aa871e0c12212c92b4e17735a66808f572578fb59cb9c47fe3712: invalid id: "
Jul 21 15:12:39 instance-group-production-public-1-qn0d dockerd[1766]: time="2017-07-21T15:12:39.949749906-04:00" level=error msg="collecting stats for 89664d3c019aa871e0c12212c92b4e17735a66808f572578fb59cb9c47fe3712: invalid id: "
Jul 21 15:12:40 instance-group-production-public-1-qn0d dockerd[1766]: time="2017-07-21T15:12:40.907039673-04:00" level=error msg="collecting stats for 89664d3c019aa871e0c12212c92b4e17735a66808f572578fb59cb9c47fe3712: invalid id: "

**Comment by superseb** [comment]
Is this from scratch? Did you run any container or only the Rancher spawned ones?

**Comment by bacheson** [comment]
this occurred when upgrading the agent from 1.2.4 to 1.2.5 ... it works from scratch

**Comment by deniseschannon** [comment]
@bacheson What version of Rancher were you upgrading from?

**Comment by pilsy** [comment]
I just had this problem in our dev environment, nothing changed .. it just started to do this

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
