### ISSUE TITLE
Update packet driver, expose more sizes and OS choices

### ISSUE THREAD

**Issue by vincent99** [rancher/rancher#9431]
https://github.com/packethost/docker-machine-driver-packet/releases/tag/v0.1.4

**Comment by westlywright** [comment]
I was able to add more options to the list but not all options that the driver added. This list should container a few more options at least

**Comment by westlywright** [comment]
also we should not merge this until the referenced cattle PR is merged

**Comment by tfiduccia** [comment]
Wes is going to change it to read from API instead instead of from hard-coded list.

**Comment by tfiduccia** [comment]
Version - 2.0 master 10/11
Verified fixed
