### ISSUE TITLE
Pods get stuck in Pending state. 

### ISSUE THREAD

**Issue by moelsayed** [rancher/rancher#9433]
**Rancher versions:** v1.6-development
rancher/server: v1.6-development
rancher/agent: v1.2.5     

kubernetes (if applicable): 1.7.1-etcd v2

**Docker version: (`docker version`,`docker info` preferred)**
v1.12.6
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
RHEL 7.3, ubuntu 14.04, ubuntu 16.04
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node internal DB
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
k8s
**Steps to Reproduce:**
Intermittent issue. Pods sometimes fail to bind to a host and get suck in pending state.

**Comment by moelsayed** [comment]
Related k8s issue: https://github.com/kubernetes/kubernetes/issues/49314

**Comment by alena1108** [comment]
@moelsayed when you hit the issue again, could you check the state of the nodes in the system? ```kubectl describe nodes```. And update the corresponding kubernetes ticket with the output.

We should also monitor the system to check when and how often kubelets lose the connectivity to the k8s master api server (by checking kubelet/api server container logs)

**Comment by deniseschannon** [comment]
Available in the `k8s:v1.7.4-rancher1` image.

**Comment by moelsayed** [comment]
Tested with the following parameters:
* rancher/server:v1.6.8-rc4
* k8s:v1.7.4-rancher1
* instances with 8GB root disk 
* validation tests ran for 3 passes.

All tests passed successfully.
