### ISSUE TITLE
Pod Infra Container Image failed to be pulled when using private registry

### ISSUE THREAD

**Issue by acscloud** [rancher/rancher#9435]
**Rancher versions:** 1.6.5

**Docker version: (`docker version`,`docker info` preferred)** 1.12.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)** Ubuntu 16.04

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** Bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)** Single

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)** Kubernetes

**Steps to Reproduce:**

1) Setup new rancher server v1.6.5
2) Configure default registry to my private registry e.g. reg.demo.com in advanced settings
3) Modify default Kubernetes template and set registry to my private registry e.g. reg.demo.com
4) Set "Pod Infra Container Image" to "google_containers/pause-amd64:3.0"
5) Create a new environment named test with modified Kubernetes template
6) Switch to test environment and add a registry with my private registry url
7) Add one host to test environment
8) All infra containers were created successfully with my private images except Kubernetes addons
9) logs:
```
7/22/2017 4:06:39 PME0722 08:06:39.448499   11441 kuberuntime_sandbox.go:54] CreatePodSandbox for pod "monitoring-grafana-2686382131-1q7x3_kube-system(01f7afb2-6eb2-11e7-b067-02afb7a42c13)" failed: rpc error: code = 2 desc = unable to pull sandbox image "reg.demo.com/google_containers/pause-amd64:3.0": Error: image google_containers/pause-amd64:3.0 not found
```
10) SSH to my host, 
```
root@host1:~# docker pull reg.demo.com/google_containers/pause-amd64:3.0
Pulling repository reg.demo.com/google_containers/pause-amd64
Error: image google_containers/pause-amd64:3.0 not found
root@host1:~# docker login reg.demo.com
Username: myusername    
Password: 
Login Succeeded
root@host1:~# docker pull reg.demo.com/google_containers/pause-amd64:3.0
3.0: Pulling from google_containers/pause-amd64
a3ed95caeb02: Pull complete 
f11233434377: Pull complete 
Digest: sha256:3b3a29e3c90ae7762bdf587d19302e62485b6bef46e114b741f7d75dba023bd3
Status: Downloaded newer image for reg.demo.com/google_containers/pause-amd64:3.0
```
11) Then all of the addons were started.

From step 10, looks like kubelet didn't login to my private registry to pull the pause-amd64 image.

**Comment by deniseschannon** [comment]
Can you share your docker-compose.yml of your kubernetes stack in the UI in the test environment?

In the kubelet service, you should see this as part of the command
```
- --pod-infra-container-image=${REGISTRY}/${POD_INFRA_CONTAINER_IMAGE}
```

In the add-on starter, you should see
```
environment: 
    REGISTRY: ${REGISTRY}
```

If you don't see any values for where ${REGISTRY} is set, then the Kubernetes template was not updated.

**Comment by acscloud** [comment]
@deniseschannon There they are:

![kubelet](https://user-images.githubusercontent.com/27944860/28551988-148a48aa-711e-11e7-9182-cc4bf7206243.jpg)

![kubelet2](https://user-images.githubusercontent.com/27944860/28551993-1968e7be-711e-11e7-850c-88a44e1562c8.jpg)

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
