### ISSUE TITLE
rbd: failed to modprobe rbd error:executable file not found in $PATH  

### ISSUE THREAD

**Issue by joew2016** [rancher/rancher#9437]
Hi:

   rancher server 1.6.2
   k8s 1.5.4
   CentOS 7.3

    I got a problem here! I try to create a kubernetes statefull nginx service with ceph rbd as the backend dynamically provision persistent volume on rancher, but failed, it shows the error "rbd: failed to modprobe rbd error:executable file not found in $PATH ". I checked the  image rancher/k8s:v1.5.4-rancher1-4 and  the container kubernetes-controller-manager-1, they both have the rbd command!
    I try to follow the example web.yaml on https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/
  **web-0  logs:**
   1h		1m		60	{kubelet ceph-osd219}			Warning	  FailedMount	MountVolume.SetUp failed for volume "kubernetes.io/rbd/fc8b7dab-6ec2-11e7-8665-02672b04ad55-pvc-e6a430b4-6eb3-11e7-aa48-02672b869d7f" (spec.Name: "pvc-e6a430b4-6eb3-11e7-aa48-02672b869d7f") pod "fc8b7dab-6ec2-11e7-8665-02672b04ad55" (UID: "fc8b7dab-6ec2-11e7-8665-02672b04ad55") with: rbd: failed to modprobe rbd error:executable file not found in $PATH
  1h		51s		48	{kubelet ceph-osd219}			Warning	  FailedMount	Unable to mount volumes for pod "web-0_default(fc8b7dab-6ec2-11e7-8665-02672b04ad55)": timeout expired waiting for volumes to attach/mount for pod "default"/"web-0". list of unattached/unmounted volumes=[www]
  1h		51s		48	{kubelet ceph-osd219}			Warning	  FailedSync	Error syncing pod, skipping: timeout expired waiting for volumes to attach/mount for pod "default"/"web-0". list of unattached/unmounted volumes=[www]
  
  # kubectl get pvc|grep web
www-web-0   Bound     pvc-e6a430b4-6eb3-11e7-aa48-02672b869d7f   1Gi        RWO           3h
www-web-1   Bound     pvc-e6ab7435-6eb3-11e7-aa48-02672b869d7f   1Gi        RWO           3h

  ==================================================
  also, there's another problem with ceph rbd 
  **ceph-secret.yaml**
  apiVersion: v1
kind: Secret
metadata:
  name: ceph-secret
  namespace: default
type: "kubernetes.io/rbd"
data:
  key: "QVFDM0htNVphbjlMRGhBQVhaSENkQUYzOWJYY0V3ZHBWNnkvY0E9PQo="

**ceph-rbd-storageclass.yaml**

  apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
   name: fast
provisioner: kubernetes.io/rbd
parameters:
  monitors: 172.30.30.215:6789,172.30.30.217:6789,172.30.30.219:6789
  adminId: k8s
  adminSecretName: ceph-secret
  adminSecretNamespace: default
  pool: k8s
  userId: k8s
  userSecretName: ceph-secret

**kubernetes on rancher 1.6.2 only works when the ceph secret's namespace is default, if change the namespace to kube-system.The PVC can not be bound!**

**Comment by aemneina** [comment]
Looks like a k8s specific bug: https://github.com/kubernetes/kubernetes/issues/38923

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
