### ISSUE TITLE
301 redirects to healthcheck stays yellow (initializing)

### ISSUE THREAD

**Issue by joshuacox** [rancher/rancher#9438]
**Rancher versions:**
rancher/server: 1.6.4
rancher/agent:

**Infrastructure Stack versions:**
healthcheck: rancher/healthcheck:v0.3.1

**Docker version: (`docker version`,`docker info` preferred)**

```
[rancher@heimdall ~]$ docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      linux/amd64
 Experimental: false

[rancher@heimdall ~]$ docker info
Containers: 23
 Running: 19
 Paused: 0
 Stopped: 4
Images: 20
Server Version: 17.03.1-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local rancher-nfs
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.34-rancher
Operating System: RancherOS v1.0.3
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 5.241 GiB
Name: heimdall
ID: MDWQ:C6TX:2M27:FU3R:4E7H:P2GG:2F3M:JTXL:DXWN:4FAG:JZZJ:6HKT
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)** ros 1.0.3

```
[rancher@heimdall ~]$ uname -r
4.9.34-rancher
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**  KVM

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**  single node rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

cattle

**Steps to Reproduce:**

start up something with a healthcheck that enforces redirect, the healthcheck willl receive 301 redirects and never go green.  Is there a way I can pass hostname along with the request line?  What exactly fires off the request line? Is it curl?

**Results:**

container stays yellow

**Comment by joshuacox** [comment]
logging into the container directly I can add the host header and get a successful `wget --header 'Host: correct.example.com' 127.0.0.1`

is there some way to add this header to whatever is calling the request line?

**Comment by vincent99** [comment]
The Host option appears if you change the request to HTTP/1.1.  There is no host header in HTTP/1.0.

**Comment by joshuacox** [comment]
What is the option?  Is there a man page that lists these out?0

**Comment by joshuacox** [comment]
of note, I found out where it 'appears' like you said, which is if you add the healthcheck manually using the GUI, but I am talking about adding it to the rancher-compose.yml

**Comment by joshuacox** [comment]
```
requestLine": "GET \"/\" \"HTTP/1.1\\r\\nHost: my.example.com\"",
```
