### ISSUE TITLE
UX: Host unavailable or Unkown in Stacks view when Rancher doesn't know the status of the host

### ISSUE THREAD

**Issue by Richard87** [rancher/rancher#9439]
**Rancher versions:**
rancher/server: 1.6.4
rancher/agent: 1.2.5

When a host is disconnected, the stacks running on the affected hosts should have a warning in the stacks view, right now the look "healthy", even if rancher doesn't know the state (the host is actually down), so it should say "Unkown" or "Host unavailable"...

**Comment by vincent99** [comment]
This is already done, but in master for 2.0.
