### ISSUE TITLE
[Help needed] Run only one version of my image at once

### ISSUE THREAD

**Issue by Richard87** [rancher/rancher#9440]
**Rancher versions:**
rancher/server: 1.6.4

Hi!

My Image will automatically migrate to the last version specified inside the image (either migrate up to a newer version, or down to a earlier version if rolled back)

But that means I can't have different version of my application live at once, because the database would be out of sync...

How can I make sure any updates shuts down all existing containers before launching the new version?

**Comment by ekristen** [comment]
Just so that I understand, you are saying that you have something internal to your image updating your image to the latest version instead of deploying a new image?

**Comment by Richard87** [comment]
No, I just want to upgrade all containers at once (bacause the application
is tied to the database scheme

>
>

**Comment by Richard87** [comment]
A batchsize of -1 would be nice to upgrade all at once :)

**Comment by aemneina** [comment]
makes sense @Richard87 I'll mark this ticket as an RFE. I guess in the meantime batch size of # of containers should do the trick.

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
