### ISSUE TITLE
[Help needed] How to config openldap to grant access by group

### ISSUE THREAD

**Issue by acscloud** [rancher/rancher#9442]
**Rancher versions:** 1.6.5

Hi, I can't get group access working with openldap, here's the structure of my ldap user and group:

user:
```
dn: uid=t100,ou=Users,dc=demo,dc=com
objectClass: inetOrgPerson
objectClass: posixAccount
givenName: test
sn: test
cn: test
uid: t100
uidNumber: 10000
gidNumber: 10000
homeDirectory: /home/t100
userPassword:: 
mail: t100@demo.com
```

group:
```
dn: cn=DevOps,ou=Groups,dc=demo,dc=com
objectClass: posixGroup
cn: DevOps
gidNumber: 10000
description: Group account
memberUid: t100
```

With default openldap settings provided by rancher, I added group "DevOps" to environment and granted owner role, but then I used uid t100 to login rancher got failed. If I add t100 directly to environment then login can success.
Seems rancher requests memberOf attribute on users, but "memberOf" is actually a virtual attribute, it wasn't there in most of the cases. So how to config this to let rancher find user group member by memberUid attribute of group dn? Thanks.

![rancherldap](https://user-images.githubusercontent.com/27944860/28498410-63c548d4-6fcf-11e7-9a3c-9d2184afddf7.jpg)

**Comment by johnhoran** [comment]
![screenshot from 2017-07-26 22-39-07](https://user-images.githubusercontent.com/3147650/28630766-619cbed8-7255-11e7-93ea-8910b601cbbf.png)

This works for me, though you might want to change display name to givenName

**Comment by acscloud** [comment]
@johnhoran It works now, but facing another issue:

![error](https://user-images.githubusercontent.com/27944860/28698562-e833fe94-7376-11e7-8cbf-b8ae0cd83086.jpg)
