### ISSUE TITLE
ternal services

### ISSUE THREAD

**Issue by farzeni** [rancher/rancher#9443]
**Rancher versions:**
rancher/server:
rancher/agent:

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**

**Results:**

**Comment by superseb** [comment]
Could you add the details in the issue so we can help figure it out?

**Comment by farzeni** [comment]
I'm sorry, i opened this issue by mistake.

you can close it
