### ISSUE TITLE
UI should show supported Docker version based on orchestrator

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#9444]
Currently, we have one range of supported Docker versions but it depends on the orchestrator used. This means that the UI won't display unsupported if you add a host to a Kubernetes environment with an unsupported Docker version installed.

This would help users troubleshoot their environment.

```
supported.docker.range=~v1.12.3 || ~v1.13.0 || ~v17.03.0 || ~v17.06.0
supported.docker.kubernetes.range=~v1.12.6
```

Other option would be to deny hosts to be added with an unsupported Docker version unless you explicitly specify to allow it.

**Comment by vincent99** [comment]
This won't be relevant anymore with 2.0, support is going to be whatever it is and not depend on orchestrator.
