### ISSUE TITLE
Private Catalog menu not sorted after upgrade to 1.6.x

### ISSUE THREAD

**Issue by jgreat** [rancher/rancher#9446]
**Rancher versions:**
Rancher	v1.6.5
Cattle	v0.182.1
User Interface	v1.6.9
Rancher CLI	v0.6.2
Rancher Compose	v0.12.5

**Steps to Reproduce:**
In 1.5.x the catalogs listing in the Catalog menu was sorted by alphabetical order. Now it just seems to be random.

![image](https://user-images.githubusercontent.com/5324639/28534100-241c28a6-7065-11e7-8a58-dbf79fe2d9bf.png)

**Comment by soumyalj** [comment]
Reproduced the issue in rancher v1.6.6. Tested the fix in v1.6.8-rc3. 
The private catalogs are sorted in alphabetical order.
<img width="236" alt="screen shot 2017-08-15 at 3 54 21 pm" src="https://user-images.githubusercontent.com/18536626/29340066-11f12b1c-81d2-11e7-8577-3c0c53cfc14b.png">
