### ISSUE TITLE
Kubernetes avoids scheduling pods on one of the nodes

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#9449]
**Rancher versions:**
rancher/server: v1.6.6-rc2
kubernetes (if applicable): v1.7.1-rancher2

**Docker version: (`docker version`,`docker info` preferred)**
1.12
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
GCE
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes
**Steps to Reproduce:**
- Deploy kubernetes on 3 hosts
- deploy rc with more than 20 pods

**Results:**
The pods get scheduled on two nodes, while the third node got no pods.

**Comment by alena1108** [comment]
figured out the reason for this behavior. It will happen only on:

1) k8s 1.7 where rancher cloud provider came into picture
2) when k8s orchestration plain is not isolated (kubelets and k8s orchestration containers can get deployed on the same host)
3) The troubled node will always be the node where rancher-cloud-provider is launched initially.

The reason why it happens is: rancher-cloud-provider updates the status of the node it runs on, with the following set of labels:

```
failure-domain.beta.kubernetes.io/region=Region1
failure-domain.beta.kubernetes.io/zone=FailureDomain1
```

that causes this node to be treated in a diff zone from where other nodes (kubelets) are located, and always be prioritized much lower than the rest of the nodes in the system.

Need to look at the rancher cloud controller manager to see how/why these flags are being passed, and if it is possible to eliminate them.

@joshwget

**Comment by alena1108** [comment]
@galal-hussein can be tested with v1.7.2-rancher3

**Comment by galal-hussein** [comment]
Rancher server: v1.6.6-rc4
k8s: rancher/k8s:v1.7.2-rancher4

Tested running rc with 50 pods scale, and pods ran evenly on the three pods
```
➜   kubectl get pods -o wide | grep hgalal-newk8s-10acre-1 | wc -l
16
➜   kubectl get pods -o wide | grep hgalal-newk8s-10acre-2 | wc -l
17
➜   kubectl get pods -o wide | grep hgalal-newk8s-10acre-3 | wc -l
17
```
