### ISSUE TITLE
Kubernetes dashboard is failing to recover after the host its scheduled on is down

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#9451]
Rancher versions:
rancher/server: v1.6.6-rc2
kubernetes (if applicable): v1.7.2-rancher1

Docker version: (docker version,docker info preferred)
1.12
Operating system and kernel: (cat /etc/os-release, uname -r preferred)
Ubuntu 16.04
Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)
GCE
Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)
single node rancher
Environment Template: (Cattle/Kubernetes/Swarm/Mesos)
Kubernetes
Steps to Reproduce:
- Deploy kubernetes on 3 hosts.
- Stop docker daemon on the host that has the dashboard pod.

Results:

Dashboard is evicted and scheduled on another node, however the old pod is in unknown state, and the dashboard link doesn't work:

```
$ curl http://x.x.x.x:8080/r/projects/1a5/kubernetes-dashboard:9090/\#
Service unavailable
```

```
$ kubectl get pods -n kube-system
NAME                                   READY     STATUS    RESTARTS   AGE
....
kubernetes-dashboard-716739405-3747l   1/1       Unknown   0          2h
kubernetes-dashboard-716739405-7w8xq   1/1       Running   0          30m
....
```

**Comment by alena1108** [comment]
Most likely happens due to service token caching on websocket proxy side (as per @ibuildthecloud). Even though k8s replaced the container, and updated its corresponding cluster ip service endpoints, our websocket-proxy continues directing the requests to the old ip address. Need help figuring out the right way to fix it (adjust timeout just for this particular service perhaps?). Today the workaround would be to restart websocket-proxy or wait for the token expiration

**Comment by sangeethah** [comment]
Rancher versions:
rancher/server: v1.6.6-rc6
kubernetes (if applicable): rancher/k8s:v1.7.2-rancher5 

Force upgrade Ipsec service.
Even after the Ipsec service was upgraded successfully , one of the hosts (compute node) continues to be in "NotReady" state.
For the time Host is in "NotReady" state , we are not able to access the Dashbord and we get timeout issues:

```Get https://10.43.0.1:443/api/v1/namespaces/default/pods: dial tcp 10.43.0.1:443: i/o timeout```

We see 2 Dashboard containers.

Once the hosts gets to "Ready" state ( have seen it take up to 20 mts) , Dashboard starts to work.

@alena1108:
unfortunately we can’t do much about this particular dashborad scenario. It really all comes down to broken network connectivity and the fact that we do not manage healthcheck for k8s containers
so we can’t kill that dashboard, and k8s can’t kill it either as kubelet/api server connectivity is broken

**Comment by galal-hussein** [comment]
Rancher version: v1.6.6-rc6
Kubernetes: rancher/k8s:v1.7.2-rancher5

I can't reproduce the dashboard issue anymore, when the compute host is down the dashboard pod evicted to another host and will be up and running.
