### ISSUE TITLE
Can't login to Rancher server after upgrade from 1.6.5 to 1.6.6-rc2 with AD TLS authentication enabled using IP instead of hostname

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#9459]
**Rancher versions:**
rancher/server: v1.6.5

**Steps to Reproduce:**
- Start rancher server v1.6.5
- Enable AD with TLS authentication using IP and not hostname
- Upgrade rancher server to v1.6.6-rc2
- try to login

**Results:**
Can't login to rancher server, and getting this error `Error Response from Auth service`

Rancher server logs:
```
time="2017-07-25T00:04:22Z" level=error msg="GetToken failed with error: Error Error LDAP Result Code 200 \"\": x509: cannot validate certificate for 52.11.206.191 because it doesn't contain any IP SANs creating ssl connection creating connection" 
2017-07-25 00:04:22,581 ERROR [:] [] [] [] [tp1020391880-14] [.a.a.i.e.ExternalServiceAuthProvider] Got error from Auth service. statusCode: 500 
time="2017-07-25T00:04:28Z" level=info msg="Now generating Ldap token" 
time="2017-07-25T00:04:28Z" level=error msg="GetToken failed with error: Error Error LDAP Result Code 200 \"\": x509: cannot validate certificate for 52.11.206.191 because it doesn't contain any IP SANs creating ssl connection creating connection" 
2017-07-25 00:04:28,901 ERROR [:] [] [] [] [tp1020391880-15] [.a.a.i.e.ExternalServiceAuthProvider] Got error from Auth service. statusCode: 500 
time="2017-07-25T00:04:34Z" level=info msg="Now generating Ldap token" 
time="2017-07-25T00:04:34Z" level=error msg="GetToken failed with error: Error Error LDAP Result Code 200 \"\": x509: cannot validate certificate for 52.11.206.191 because it doesn't contain any IP SANs creating ssl connection creating connection" 
2017-07-25 00:04:34,713 ERROR [:] [] [] [] [tp1020391880-62] [.a.a.i.e.ExternalServiceAuthProvider] Got error from Auth service. statusCode: 500
```

**Comment by vincent99** [comment]
This should have never worked in the first place and is being fixed to correctly fail now.  Encryption is essentially worthless if you don't verify the identity of the other side of the line...  The hostname you're connecting to needs to match the certificate.

**Comment by galal-hussein** [comment]
As a workaround, i disabled the authentication from the DB, and then renabled using hostname:
```
mysql> select * from setting where id=23;
+----+----------------------+-------+
| id | name                 | value |
+----+----------------------+-------+
| 23 | api.security.enabled | true  |
+----+----------------------+-------+

mysql> update setting set value="false" where id=23;
```

**Comment by mrajashree** [comment]
This verification is handled by golang tls package. 
Should we document this workaround?

**Comment by deniseschannon** [comment]
As this is a security issue, we will be providing workarounds on how to fix your setup before upgrade or if you have upgraded, how to fix it afterwards. @galal-hussein will be providing these details

**Comment by deniseschannon** [comment]
For users who are authenticated with AD using TLS and have configured Access Control using an IP that doesn't match the hostname of their certificate, please follow the following workarounds:
 
**Prior to Upgrading to v1.6.6+** 
Through the settings in the  v2-beta endpoint (`<SERVER_IP:PORT>/v2-beta/settings/`), which can be found under **API** -> **Keys**, update the value of `api.auth.ldap.server` from the IP to the hostname that matches the certificate.  After upgrading to v1.6.6, you should face no issues with your authentication.

**Upgrading after v1.6.6+**
If you have already upgraded to v1.6.6, you will not be able to log in. An admin who has access to the Rancher DB will need to [disable access control through the DB](http://rancher.com/docs/rancher/v1.6/en/faqs/troubleshooting/#help-i-turned-on-access-control-and-can-no-longer-access-rancher-how-do-i-reset-rancher-to-disable-access-control). After access control has been disabled, you will need to re-enable with access control with the correct hostname and not the IP. 

> Note: When disabling and re-enabling your access control, your [site access](http://rancher.com/docs/rancher/v1.6/en/configuration/access-control/#site-access) will be reset. You will need to adjust this back to your previous settings.
