### ISSUE TITLE
disable conntrack for certain traffic

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#9460]
1) We don't need to track connections to metadata IP address
```
root@ip-172-31-53-43:/# conntrack -L | grep 169.254.169.250 | wc -L
conntrack v1.4.3 (conntrack-tools): 125 flow entries have been shown.
170
```

2) Connections between containers on the managed network (After disabling this, need to verify network-policy still works)
```
root@ip-172-31-53-43:/# conntrack -L | grep "src=10.42" | grep "dst=10.42" | wc -L
conntrack v1.4.3 (conntrack-tools): 127 flow entries have been shown.
172
```

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
