### ISSUE TITLE
sky-dns deployment with self anti affinity fails to upgrade 

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#9461]
In Rancher, to support HA for sky dns service in k8s cluster, it gets deployed with user configurable scale and corresponding pods get spread cross hosts based on anti affinity rule to itself on sky-dns deployment.

But sometimes upgrading to the newest deployment fails as upgraded pod fails to come up on the node where the old pod of the same deployment is still running. Looks very similar to the issue in the comment: https://github.com/kubernetes/features/issues/60#issuecomment-263843173

Workaround would be - modify skydns template with a diff label in kubernetes-package repo when upgrade is needed.

@LLParse

**Comment by alena1108** [comment]
@galal-hussein can be tested with v1.7.2-rancher3

**Comment by galal-hussein** [comment]
Upgraded from Rancher v1.6.5 to Rancher v1.6.6-rc6, and kubernetes to rancher/k8s:v1.7.2-rancher5 with kubdns scale 3, i can see old kubedns being deleted and new kubedns pods being deployed, and new kubedns deployment has label: `rancher-app: kube-dns1`
