### ISSUE TITLE
Better error message when AD fails to authenticate

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#9462]
**Rancher versions:** v1.6.6-rc2

**Steps to Reproduce:**
1.  Go to Access Control
2.  Put in IP and turn on TLS
3.  Fill in rest with valid data
4.  Try to Authenticate 

**Results:**  Error Response from Auth service (Status code from Auth Service: 500) - Is there anyway we can get a better and more descriptive error message?

![image](https://user-images.githubusercontent.com/11514927/28550299-c1968a16-7094-11e7-84ba-f05bcac86001.png)

**Comment by deniseschannon** [comment]
500 is the correct error code, but auth-service could have better error message and then cattle to return that auth-service message.

**Comment by prachidamle** [comment]
We will be providing a generic error message in case of 500 error code. No details of the auth failure will be shown. The generic message to use is "Error communicating with authentication provider"

**Comment by deniseschannon** [comment]
Available in v1.6.8-rc1

**Comment by sangeethah** [comment]
Tested with  v1.6.8-rc1
Scenario1:
Enable AD setup with TLS and having "Hostname" set to ipaddress of AD server.
Click on "Test" after providing all correct values.
User is presented with the following message which is the same error message LDAP server returned:

```Error LDAP Result Code 200 "": x509: cannot validate certificate for <ip address> because it doesn't contain any IP SANs creating ssl connection```

Scenario2:
Have AD setup without TLS.
Edit AD settings and change the "Hostname" to ipaddress of AD server and enable TLS.
Click on "Test and Save".
User is presented with error message - ```Internal Server Error```

```
time="2017-08-09T19:12:53Z" level=info msg="newProvider ldap" 
time="2017-08-09T19:12:53Z" level=info msg="Now generating Ldap token" 
time="2017-08-09T19:12:53Z" level=info msg="Now creating Ldap connection" 
time="2017-08-09T19:12:53Z" level=error msg="GetProvider: Error in login Error LDAP Result Code 200 \"\": x509: cannot validate certificate for <ip> because it doesn't contain any IP SANs creating ssl connection" 
time="2017-08-09T19:12:53Z" level=error msg="TestLogin GetProvider failed with error: Error LDAP Result Code 200 \"\": x509: cannot validate certificate for <ip> because it doesn't contain any IP SANs creating ssl connection" ```


Reopening this issue to fix scenario 2.

**Comment by prachidamle** [comment]
Scenario2 is a UI issue. Server is sending out the status code as 500 with the actual LDAP error message as seen in logs. I think UI has a translation for error code 500, that overrides the error message to a standard "Internal Server Error"

**Comment by prachidamle** [comment]
@vincent99 @westlywright can we remove the 500 error message translation for "Edit Settings /v1-auth/testlogin" API since we want to show the detail error message to admin at this point.

**Comment by vincent99** [comment]
Updated, but it's going to show the raw JSON because the response says it's text:

`content-type:text/plain; charset=UTF-8`

The error response should say it's `application/json`.

**Comment by prachidamle** [comment]
Which UI tag to use to get this fix? @vincent99 @deniseschannon

**Comment by deniseschannon** [comment]
@prachidamle UI tag `1.6.19`

**Comment by sangeethah** [comment]
Tested with rancher-servr version - v1.6.8-rc3
Have AD setup without TLS.
Edit AD settings and change the "Hostname" to ipaddress of AD server and enable TLS.
Click on "Test and Save".
User is presented with error message - 
```Error creating ssl connection: LDAP Result Code 200 "": x509: cannot validate certificate for 13.56.44.9 because it doesn't contain any IP SANs```
