### ISSUE TITLE
The drop-down menu  and the list of environment variables are inconsistent.

### ISSUE THREAD

**Issue by hongxiaolu** [rancher/rancher#9463]
**Rancher versions:**
rancher/server:v1.6.4
rancher/agent:v1.2.5

**Infrastructure Stack versions:**
healthcheck:v0.3.1
ipsec:holder
ipsec CNI driver :v0.11.3
network-services:v0.7.4 
scheduler:v0.8.2
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
1.12.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 14.04.2 LTS (4.4.1) 

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
ali cloud (ECS)

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**

**Results:**

The drop-down menu  and the list of environment manage are inconsistent. See the following drawing

<img width="332" alt="2" src="https://user-images.githubusercontent.com/20707603/28553057-362a0a94-7124-11e7-876c-18354ce6c983.png">
<img width="608" alt="1" src="https://user-images.githubusercontent.com/20707603/28553049-2e89d8d2-7124-11e7-99ad-7f3649b9c5d6.png">

**Comment by vincent99** [comment]
Since you are an admin, the environments page shows ALL environments in the installation and you have access to all of them.  The dropdown shows the subset which you are a member of, so that you do not need to wade through the entire list to use your own stuff.
