### ISSUE TITLE
cross node communication failures

### ISSUE THREAD

**Issue by joshuacox** [rancher/rancher#9467]
**Rancher versions:**
rancher/server: 1.6.5
rancher/agent: :v1.2.5  

**Infrastructure Stack versions:**
healthcheck: 0.3.1
ipsec: holder
network-services: 0.7.4  metadata 0.9.2 
scheduler:  0.8.2

**Docker version: (`docker version`,`docker info` preferred)**

```
rancher@rancher:~$ docker info
Containers: 32
 Running: 1
 Paused: 0
 Stopped: 31
Images: 20
Server Version: 17.03.1-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local rancher-nfs
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.34-rancher
Operating System: RancherOS v1.0.3
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 4.834 GiB
Name: rancher
ID: DRVM:BVVB:X6KB:UY3N:RKPD:EI6L:HNLC:WVBP:ZC3R:ADYR:QOHZ:IKHH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

```
rancher@rancher:~$ cat /etc/os-release 
NAME="RancherOS"
VERSION=v1.0.3
ID=rancheros
ID_LIKE=
VERSION_ID=v1.0.3
PRETTY_NAME="RancherOS v1.0.3"
HOME_URL="http://rancher.com/rancher-os/"
SUPPORT_URL="https://forums.rancher.com/c/rancher-os"
BUG_REPORT_URL="https://github.com/rancher/os/issues"
BUILD_ID=
rancher@rancher:~$ uname -r
4.9.34-rancher
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

KVM

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

single node rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

cattle

**Steps to Reproduce:**

setup three rancher nodes, all in the same KVM host with a bridged interface with one assignable public IP, and a private virtual network for all the nodes to connect to each other from.

one with dual NIC and both private and public IPs, and label `publice=true`,

two with single NIC and only private IP and label `private=true`

**Results:**

eventually I find containers lose communication across one of the containers like in this [issue](https://github.com/rancher/community-catalog/issues/564). Now here's the weird part I "fixed" this by evacuating one of the `private=true` hosts.  As long as the host stays inactive everything stays green and good.  But if I activate both these weird problems start cropping up.  `Evacuate` and in about ten minutes everything is back to green again.  It seems to be preceded by one of the private host's healthchecks going yellow.  The healthcheck appears to be fine other than losing it's ability to communicate with other containers, log look like this:

```
7/25/2017 2:52:53 PMtime="2017-07-25T19:52:53Z" level=info msg="Scheduling apply config"
7/25/2017 2:52:53 PMtime="2017-07-25T19:52:53Z" level=info msg="healthCheck -- no changes in haproxy config\n"
```

  I am at a loss here as to explain what is going wrong.  Any ideas?  And does anyone else see this behavior?  It seems to happen only on long running environments (months and have survived many upgrades of rancher and rancherOS beneath it).

**Comment by superseb** [comment]
Can you share a screenshot of the Infrastructure -> Hosts view?

**Comment by joshuacox** [comment]
![screenshot from 2017-07-25 15-24-03](https://user-images.githubusercontent.com/6137404/28592166-c17a1df4-714d-11e7-9712-a714560727ab.png)

Tiger is the host that is deactivated in this instance, you can see that the healthcheck is also still yellow

**Comment by superseb** [comment]
You erased the host IP's, which is fine, I assume they are unique for every host and not in the Docker bridge subnet (172.17.0.0/16)?

What are the IP's of every metadata-x container?

**Comment by joshuacox** [comment]
lion has it's public IP, the other two show up as the KVM host's IP ( I think this is all from the perspective of the rancher server and where it sees the api calls coming from), both lion's public IP and the host's IP are actual public IPs and not `172.17.0.0/16`

**Comment by joshuacox** [comment]
looking back at this, what do you mean by `metadata-x container` ?

**Comment by leodotcloud** [comment]
@joshuacox can you please share the screenshot with the IP addresses in a private message on Slack (https://slack.rancher.io)? I have suspicion on the private/public IP addresses. Do leopard and tiger have the same IP address?

**Comment by joshuacox** [comment]
@leodotcloud  they both appear to the rancher server to come from the same IP address, so yes the IP in that displayed area is an IP address that neither of them have assigned to their interfaces.  It is the KVM hosts IP  address.  They both, and in fact all three hosts, have interfaces in a private virtual network.  This is a private virtual netwok created inside KVM and will NAT external traffic for all three VMs and anything else inside this private virtual net.  All three VMs have static assigned IP addresses inside the private virtual net,  and access some services external to the `ranch` like NFS for example.  One of the virtual machines `lion` has two virtual NICs and the second NIC is bridged to the public interface of the KVM and has a public IP address.  This node I assigne labels like `public=true`, `smtp=true`, `traefik_lb=true` and other such stuff if I need a public port for a service.  I'll gladly give you the public IPs privately, etc.  But that might answer your question right there?

**Comment by joshuacox** [comment]
This is all in preparation for couple of really nice IBM units I'll be setting up where in each rancherOS will not be virtualized at all, and most of the units will be in a private service net with a public facing nodes.  But I need to see all this work virtually as I'd love to have a giant hardware cluster just for testing, but people want to put those things in production.

**Comment by leodotcloud** [comment]
@joshuacox All the hosts shown in the Rancher UI should have unique IP addresses AND these IP addresses should be reachable from one another. If these conditions don't match, you will have problems with cross-host networking.

**Comment by joshuacox** [comment]
@leodotcloud they do have unique IP addresses, and they do indeed communicate with each other and other services on the private network.

But the rancher server does not see it that way as they are NAT'ing out of the KVM hosts IP (not their IP). Then how do a bunch of private nodes communicate with an external rancher server?  And if I make an internal rancher server I run into problems getting it back out through reverse proxies etc:
https://github.com/rancher/rancher/issues/9420

**Comment by leodotcloud** [comment]
@joshuacox when you are registering the host can you try using `CATTLE_AGENT_IP` so that cattle doesn't use the KVM host's IP address for both of these nodes?

**Comment by joshuacox** [comment]
@leodotcloud `This generally works for machines with unique public IPs, but will not work if the machine is behind a firewall/NAT`  Note I am behind a NAT

**Comment by leodotcloud** [comment]
@joshuacox if the hosts are not uniquely addressable by an IP address be it private/public IP address, then we cannot establish cross host networking.

**Comment by joshuacox** [comment]
they have unique IP addresses and they are communicating, and tiger came back after I deleted and readded using the `CATTLE_AGENT_IP` and it is receiving communication from the rancher server, adding containers etc, I can execute a shell in a container right now and communicate just fine across the environment without issue, BUT the healthcheck does not leave yellow, end eventually the environment stop communicating in my experience.

**Comment by joshuacox** [comment]
ok readded all hosts, using the cattle agent ip,  including lion and now all are green and happy and all services, so what does this warning mean?

```
This generally works for machines with unique public IPs, but will not work if the machine is behind a firewall/NAT
```

The rancher server CANNOT contact the individual nodes by those IPs, so I guess I completely misunderstood `Specify the public IP that should be registered for this host. If left empty, Rancher will auto-detect the IP to use.` that this was the IP the server would use?  But clearly that is not the case?

**Comment by joshuacox** [comment]
closing for now as everything is staying healthy with this method of using the private IPs as `CATTLE_AGENT_IP`
