### ISSUE TITLE
Rancher admin users should be authenticated to all Kubernetes environments

### ISSUE THREAD

**Issue by joshwget** [rancher/rancher#9468]
Rancher admin users should not need to be explicitly added to Kubernetes environments to be authenticated.

~~~Depends on rancher/rancher#9473~~~ Found a method that doesn't require this.

**Comment by galal-hussein** [comment]
Rancher version: v1.6.6-rc4
Kubernetes: rancher/k8s:v1.7.2-rancher4
RBAC: Enabled
Authentication: Local

I validated that i can query the kubernetes api normally with admin user that is not added explicitly to kubernetes environment.
