### ISSUE TITLE
"Edit" option should not be presented in "OpenLDAP" access control page.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#9469]
Rancher versions:v1.6.6-rc3

Steps to reproduce the problem:

Enable OpenLDAP access control.
Navigate to "Admin/Access Control".

"Edit" option is presented in "OpenLDAP" access control page.

Expected Behavior:
"Edit" option should not be presented in "OpenLDAP" access control page.

**Comment by tfiduccia** [comment]
Version - 1.6.6-rc4
Verified fixed
