### ISSUE TITLE
There should be no "Delete" option provided for the LoadBalancer that is created as part of LB service.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#947]
Server version - v0.22.0-rc2

Create LB service that is linked to another service S1.
Activate LB service and service S1.

This will result in an LoadBalancer being created.

Go to Load Balancers tab and try to delete the Load Balancer.
API returns 422 and deletion of LB fails.

UI should not expose this option .

**Comment by vincent99** [comment]
API should not return the `remove` action if it's not going to work.

**Comment by alena1108** [comment]
As LoadBalancer created as a part of the service, uses the same API object definition as the regular LB - with only one extra field "serviceId" - there is no way in our current API to hide certain action based on the object's certain field(s) presence/absence.  By now, can we just hide all actions for the LB having not null serviceId, from the UI, @vincent99?

**Comment by alena1108** [comment]
Closing as won't fix as support for standalone LB is disabled now.
