### ISSUE TITLE
Issues with Rancher Agent, Private VPC's and Nat Gateways

### ISSUE THREAD

**Issue by jrhjr07** [rancher/rancher#9470]
**Rancher versions:**
rancher/server:1.6.4
rancher/agent:1.2.5

**Infrastructure Stack versions:**
healthcheck: rancher/healthcheck:v0.3.1
ipsec: rancher/net:v0.11.3
network-services: rancher/network-manager:v0.7 rancher/metadata:v0.9.2
scheduler: rancher/scheduler:v0.7.5

**Docker version: (`docker version`,`docker info` preferred)**
```MASTER:
Containers: 12
 Running: 1
 Paused: 0
 Stopped: 11
Images: 5
Server Version: 1.12.5
Storage Driver: devicemapper
 Pool Name: docker-202:2-20971941-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 3.719 GB
 Data Space Total: 107.4 GB
 Data Space Available: 12.52 GB
 Metadata Space Used: 7.823 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.14 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.135-RHEL7 (2016-09-28)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-514.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.3 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.388 GiB
Name: XXXXXXXXXX
ID: NJOQ:OYLP:CQBK:OFL3:2NDY:FWK4:ATL7:EZU3:LWHO:SUKY:USJA:7AUN
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8

HOST:
Containers: 14
 Running: 14
 Paused: 0
 Stopped: 0
Images: 13
Server Version: 17.06.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 94
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-1026-aws
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.795GiB
Name: XXXXXXXXXXx
ID: QLH5:CTRT:UYKL:OH5T:6XSB:QMLK:UMZW:73IP:AIUW:ARO6:KTO6:HIY3
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```# uname -r
4.4.0-1026-aws
```

# cat /etc/os-release
```NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher with RDS DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Single Rancher Environment using Hosts in single VPC.  VPC consists of 5 subnets - 3 routing to an internet gateway(external subnets) and 2 routing to a nat gateway(internal subnet).  Two hosts have been provisioned with RancherOS and the Rancher UI and configured with External IP's in the external subnets and all services are working as expected.  

Provisioned 3 Ubuntu 16.04 host from AWS UI, installed Docker CE 17.06 as seen above in docker info section.  Using Private subnet and Custom Docker Host registration, passed 'CATTLE_AGENT_IP=$eth0_IP' with docker run command.  'DETECTED_CATTLE_AGENT_IP' states NAT gateway IP address and IPSEC containers on external hosts attempt to connect to NAT Gateway IP as well.

IPSEC Log:
'sending packet: from 10.42.12.197[500] to 35.164.56.106[500]'

![screen shot 2017-07-25 at 3 37 34 pm](https://user-images.githubusercontent.com/5836299/28592782-b04d4b80-714f-11e7-99a8-c3c32e9c5814.png)

**Comment by jrhjr07** [comment]
root@ip-10-0-2-22:~# sudo docker run -e CATTLE_AGENT_IP="10.0.2.22"  --rm --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.2.5 https://XXXXXXXXX/v1/scripts/4DEFF6B57D96A1F4E2EC:1483142400000:Vgz6z7jPyaJCHdMoPhY0tzBiA
Unable to find image 'rancher/agent:v1.2.5' locally
v1.2.5: Pulling from rancher/agent
b3e1c725a85f: Pull complete
4daad8bdde31: Pull complete
63fe8c0068a8: Pull complete
4a70713c436f: Pull complete
bd842a2105a8: Pull complete
3f7d6fd71888: Pull complete
16914729cfd3: Pull complete
d34b76ed901e: Pull complete
80ff31d61b2d: Pull complete
Digest: sha256:4cec4c6093d04c87375c2ff580d77e5857be19999ee098bea1d4084b734df989
Status: Downloaded newer image for rancher/agent:v1.2.5

INFO: Running Agent Registration Process, CATTLE_URL=https://XXXXXXX/v1
INFO: Attempting to connect to: https://XXXXXXXX/v1
INFO: https://XXXXXXXXX/v1 is accessible
INFO: Inspecting host capabilities
INFO: Boot2Docker: false
INFO: Host writable: true
INFO: Token: xxxxxxxx
INFO: Running registration
INFO: Printing Environment
INFO: ENV: CATTLE_ACCESS_KEY=XXXXXXXXXXX
INFO: ENV: CATTLE_AGENT_IP=10.0.2.22
INFO: ENV: CATTLE_HOME=/var/lib/cattle
INFO: ENV: CATTLE_REGISTRATION_ACCESS_KEY=registrationToken
INFO: ENV: CATTLE_REGISTRATION_SECRET_KEY=xxxxxxx
INFO: ENV: CATTLE_SECRET_KEY=xxxxxxx
INFO: ENV: CATTLE_URL=https://rancher.inexa.io/v1
INFO: ENV: DETECTED_CATTLE_AGENT_IP=35.164.56.106
INFO: ENV: RANCHER_AGENT_IMAGE=rancher/agent:v1.2.5
INFO: Launched Rancher Agent: 61b6f26ea732482f7f3d258218006f11cda8139684ecdd783eff22eadb922166

**Comment by vincent99** [comment]
`DETECTED_...`is what would have been used but `CATTLE_AGENT_IP` is what is actually used, as your screen shows.  Hosts attempt to communicate with each other using the registered IP, as displayed on each host (`54...3`, `34...228` and `10.0.2.22` in this case.  All need to be able to reach each other using those IPs.

**Comment by superseb** [comment]
Need any more help on this @jrhjr07 ?

**Comment by superseb** [comment]
Please reply if you need more help on this @jrhjr07
