### ISSUE TITLE
validate k8s + vxlan

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#9476]

**Comment by sangeethah** [comment]
vxlan router not able to to start in Rhel 7.3  with native docker -https://github.com/rancher/rancher/issues/9677

**Comment by sangeethah** [comment]
Automated K8s validation tests reported success (except for know issues) on vxlan setups using hosts with ubuntu 16.04 with docker 1.12.6.

**Comment by sangeethah** [comment]
Automated K8s validation tests reported success (except for know issues) on vxlan setups using hosts with Rhel 7.3 with upstream docker 1.12.6 with selinux disabled.

**Comment by sangeethah** [comment]
Automated K8s validation tests reported success (except for know timing issues) on vxlan setups using hosts with Rhel 7.3 with native docker and with selinux enabled.
