### ISSUE TITLE
Users/Groups in "Site Access" showup as external ids instead of SAM Accountname in "Access Control" page

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#9478]
Rancher versions: v1.6.6-rc3
Set up:
AD auth enabled setup with "Site Access" set to "Allow members of Environments.plus Authorized Users and Organization" and add few Users/Groups to this list.

Navigate back to "Admin/Access Control" to get to Access Control page.

Notice that Users/Groups in "Site Access" showup as external ids instead of SAM Accountname.

<img width="1079" alt="screen shot 2017-07-25 at 6 10 25 pm" src="https://user-images.githubusercontent.com/4266958/28600168-2ac75648-7165-11e7-89cc-322a3f4bccd8.png">

**Comment by deniseschannon** [comment]
Available in v1.6.8-rc1

**Comment by sangeethah** [comment]
Tested with v1.6.8-rc1

Users/Groups in "Site Access" showup as names now.
