### ISSUE TITLE
kubectl-shell pod fails to recover if the host running it is down.

### ISSUE THREAD

**Issue by moelsayed** [rancher/rancher#9480]
**Rancher versions:**
rancher/server: v1.6.6-rc3

kubernetes (if applicable): rancher/k8s:v1.7.2-rancher1

**Docker version: (`docker version`,`docker info` preferred)**
1.12.6
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
ubuntu 16.04
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node, internal DB
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
k8s
**Steps to Reproduce:**

   * Deploy kubernetes on 3 hosts.
    * Stop docker daemon on the host that has the kubectl-shell pod.

**Results:**

kubectl-shell is restarted on another node, but it's not accessible through the UI.

**Comment by alena1108** [comment]
Will be fixed by enabling healthcheck on the kubectld-shell service in k8s template

**Comment by moelsayed** [comment]
Fix validation:
rancher/server: v1.6.6-rc4
kubernetes (if applicable): rancher/k8s:v1.7.2-rancher5

**Steps to validated:**

   * Deploy kubernetes on 3 hosts.
    * Stop docker daemon on the host that has the kubectl-shell pod.

**Results:**

kubectl-shell was restarted on another host and connected correctly to k8s API.
