### ISSUE TITLE
Container images with long names are truncated

### ISSUE THREAD

**Issue by benclapp** [rancher/rancher#9482]
If a container has a really long image name, it is truncated on the service page, making it hard to find the image tag.

![image](https://user-images.githubusercontent.com/6227220/28603081-184beaf4-7216-11e7-8626-e5321f0236c6.png)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.5` Cattle: `v0.182.1` UI: `v1.6.9` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`service.containers`|

**Comment by jonaskello** [comment]
The same is true for the Containers tab on the Host page. All my images are from a gitlab registry and therefore have really long prefixes which all are the same. A tooltip too see the full name would be very helpful here!

**Comment by jonaskello** [comment]
I noticed on the hosts page (where you see all hosts) the container names are truncated to show only the end which is more helpful than seeing the beginning.

**Comment by loganhz** [comment]
added a tooltip

**Comment by deniseschannon** [comment]
Available with `v1.6.15-rc6`

**Comment by tfiduccia** [comment]
Version - v1.6.15-rc6
No tooltip is showing up for me.  Maybe not pushed?

**Comment by loganhz** [comment]
![image](https://user-images.githubusercontent.com/21168270/37440435-a6086f70-2837-11e8-9330-ae8cec89fee0.png)

@tfiduccia  Can you try again, please?
The tooltip is added in the `image` column. I didn't add it in container name column.

**Comment by tfiduccia** [comment]
Version - v1.6.15-rc8
Verified fixed
