### ISSUE TITLE
Issue with taking docker-compose.yml of catalog template e.g. Rancher NFS

### ISSUE THREAD

**Issue by jwarder** [rancher/rancher#9486]
If I copy the docker-compose.yml of Rancher NFS and deploy this in a user stack I get the following exception:

rancher-nfs is not a driver registered with the current Rancher 

I should be able to use a template docker-compose.yml file without deploying the template itself. The reason I am doing it this way is because I am using terraform to deploy my stacks e.g.

`resource "rancher_stack" "efs" {
  name           = "NFS"
  description    = "NFS stack"
  environment_id = "${rancher_environment.rancher_env.id}"
  catalog_id     = "library:infra*nfs:3"
  scope          = "system"

  environment {
    MOUNT_DIR    = "/"
    NFS_SERVER   = "fs-ae548767.efs.eu-west-1.amazonaws.com"
  }
}`

**Comment by superseb** [comment]
Was this fixed using Terraform v0.10.0?

**Comment by superseb** [comment]
Please respond if you need help on this.
