### ISSUE TITLE
Feature request: Already deployed catalog items should be reconfigurable

### ISSUE THREAD

**Issue by nerdicbynature** [rancher/rancher#9487]
**Rancher versions:**
rancher/server: 1.6.2
rancher/agent: 1.2.2

**Infrastructure Stack versions:**
healthcheck: 0.3.1
ipsec: net:holder
network-services: 0.9.2
scheduler: 0.8.2
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
17.03.1.ce-1.el7.centos
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
RHEL7

## Need feature: Already deployed catalog items should be reconfigurable

If I deploy an item from a catalog you may or may not asked a couple of configuration questions like storage type, ports or loglevel. 

Having a stack from catalog already running I realize that one of the answers was wrong or that I just want to change the loglevel for debugging purposes. From what I know there are two options:

* I can delete the stack and deploy it again from the catalog with the modified answers. As a consequence I have to answer every non-default question again. Maybe a stack scoped volume also gets deleted.

* I can upgrade the service to alter configuration of a service. But this is not reflected during future catalog item upgrades. 

On the other hand: If there is an upgrade available for your catalog item and you click on upgrade, all questions are already filled with your previous answers you give at first deploy time  and you.
Using "rancher inspect <stack>" I can see that all catalog answers are actually stored as environment entries for a service.

I'd like to have a GUI feature where I can "upgrade" to the same version of the catalog item, having asked and pre-filled all answers so that I can modify that one answer that I want to change.

Kind regards,
Andre.

**Comment by vincent99** [comment]
Click the "Up to date" button, you can do an "upgrade" to the same version specifically you change answers.

**Comment by nerdicbynature** [comment]
Thanks a lot. Never realized that this is a button acutally. :-)
