### ISSUE TITLE
Docker 17.06 with Rancher 1.6.4

### ISSUE THREAD

**Issue by alaa89** [rancher/rancher#9488]
Hello,

I have recently upgraded docker version from 17.03 to 17.06. However, It shows unsupported docker version from Rancher UI.
In the documentation, it is stated that docker 17.06 is supported with Rancher v1.6.3+.
Link: http://rancher.com/docs/rancher/v1.6/en/hosts/#supported-docker-versions

Please confirm whether this docker version is supported or not?

Thanks

**Comment by superseb** [comment]
Can you share a screenshot of Infrastructure -> Hosts view? Or tell what OS you are running and how you are installing Docker?

**Comment by superseb** [comment]
The documentation is correct, please let me know if you run into any problems.
