### ISSUE TITLE
Network Agent Flaps every 5 seconds if uuid is duplicated on the host

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#949]
This was discovered by @sangeethah when starting/stopping/removing the network agent directly on the host. In that scenario, removing the network agent from the host caused the entire docker daemon to hang.

When the daemon was restarted, a bug in docker caused the original network agent container to land in a "dead" state **_and**_ have its name changed from the rancher uuid id to a docker generated one.

When rancher decided it needed to recreate the network agent, this caused two containers to be on the host with the same value for the `io.rancher.container.uuid` label.

This label duplication caused the rancher ping logic to detect the container as both up and down at the same time. So, rancher tried to restart the container, which it did successfully to the **_real**_ network agent, but the dead container stayed dead and caused the next ping to still think the network agent was down.

The end result is that rancher tries to restart the network agent container every five seconds (every ping).

---

The real world way to reproduce this (hanging the docker daemon and getting the a dead container with a new name but old uuid) is really hard to do. Here's an easier way to reproduce:
1. Start rancher and create a container so that the network agent is created.
2. Inspect the net agent container to obtain the rancher uuid label.
3. Do `docker run -itd --label io.rancher.container.uuid=<value from step 2> --label io.rancher.container.system=NetworkAgent echo hi`.

---

@ibuildthecloud and I discussed the right thing to do in this scenario. We decided that the ping logic needs to detect when we have more than one container with the same rancher uuid. When we detect that, we consider the best match to be the one with the docker id that matches the recorded externalId in rancher.

For all containers that are not the best match, we will force stop them. If they are already stopped, we will do nothing.

**Comment by cjellick** [comment]
Ping @sangeethah. Just wanted to let you know that I wrote up this issue and also that I will not get to fixing it until next week.

**Comment by sangeethah** [comment]
@cjellick thanks for including a detailed explanation of the issue seen.

**Comment by deniseschannon** [comment]
With the introduction of CNI and network drivers in v1.2.0, there is no network agent running on hosts anymore. This is no longer applicable.
