### ISSUE TITLE
Service Account Password should not save when I disable access

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#9490]
**Rancher versions:** v1.6.6-rc4

**Steps to Reproduce:**
1.  Authenticate using Active Directory
2.  Deactivate Active Directory

**Results:**  The Service Account Password is being saved.  It didn't use to save, and I think the Password should have to be re-entered every time for security?

**Comment by deniseschannon** [comment]
Available in v1.6.8-rc1

**Comment by sangeethah** [comment]
Tested with v1.6.8-rc1

Enable acces control using Active Directory
Disable Access control
Try to enable acces control using Active Directory again.
"Service Account Password" field is empty , as expected.
"serviceAccountPassword" field is empty when AD is enabled/disabled in http://<ip-address>:8080/v1-auth/config
