### ISSUE TITLE
Allow catalog-service to run without access keys

### ISSUE THREAD

**Issue by LLParse** [rancher/rancher#9492]
Instead of failing to run when not provided with valid Rancher access keys, log a warning and disable tracking.

@sangeethah To test this, install a fresh Rancher 2.0 and observe the Rancher server logs. You should see `Couldn't load install uuid: Get v2-beta: unsupported protocol scheme ""` in the logs at some point.

To test in isolation (optional):
1. Download catalog service binary to a test machine.
2. Ensure environment variable `CATALOG_SERVICE_CATTLE_URL` is _not_ set.
3. Start the service via `./catalog-service --sqlite` or similar.

Expected: A message appears in logs:  `Couldn't load install uuid: Get v2-beta: unsupported protocol scheme ""`

**Comment by deniseschannon** [comment]
Verified with master of catalog-service with master of cattle (with no access keys).
