### ISSUE TITLE
Make rancher-cloud-controller-manager/addonstarter independent image

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#9493]
Today rancher-cloud-controller-manager/addon starter are released as a part of rancher/k8s image. It means every time there are changes to the cloud provider code or new addon template is being modified, we bump up the generic k8s image tag. We should spit them up, so k8s image only captures k8s binaries updates.

@deniseschannon

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
