### ISSUE TITLE
Token is not being returned causing server to not respond

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#9495]
**Rancher versions:** v1.6.6-rc4

**Steps to Reproduce:**
1.  Auth into LDAP
2. Deactivate LDAP
3. Auth into AD

**Results:**  AD login page stays up and I have to refresh or sometime re-login again to get it show up.  Then if I log out for any reason, I can get my server into a state where it stops responding completely.

**Comment by deniseschannon** [comment]
Available in v1.6.8-rc1

**Comment by galal-hussein** [comment]
Rancher Server: v1.6.8-rc4

Steps:

- Turn on/off LDAP 100 times
- Turn on/off AD 100 times
- Turn on and login with AD

I didn't see the problem.

**Comment by tfiduccia** [comment]
@galal-hussein - this problem was actually cause by trying to log into AD unsuccessfully.  So trying to log in with the wrong credentials.  Rajashree was still seeing it after the initial fix.

**Comment by mrajashree** [comment]
@tfiduccia Yes I tried logging into AD unsuccessfully multiple times. But I couldn't repro after the handleResponse fix suggested by @cjellick @ibuildthecloud . I'm not sure which fix you're referring to?

**Comment by mrajashree** [comment]
Oh I think I know, so I first had a cattle PR with the handleResponse fix, but in that PR I added the fix to only 5 out of 6 functions, I missed the 6th one. Then during PR review it was pointed out and on adding the fix to that last function that I missed, I couldn't repro

**Comment by galal-hussein** [comment]
@tfiduccia @mrajashree I tried login with invalid credentials for over than 20 times, and i can't reproduce the problem.
