### ISSUE TITLE
Inconsistency in showing edit button for Owner role which has ability to set members but not edit environment.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#9497]
Rancher versions: V1.6.6-rc4

When owner of an environment is given access to set members but not edit environment , we dont see the “Edit” option  in the dropdown list of action for Environment .But we have the “Edit <project Name>” option from Envrionment drop down which works as expected ( name is greyed out and able to set members).

**Comment by tfiduccia** [comment]
Version - v1.6.6-rc5
Verified fixed
