### ISSUE TITLE
Advice for error "code=InvalidOption, fieldName=Image is required when selectorContainer is not passed in, baseType=error"

### ISSUE THREAD

**Issue by richbos** [rancher/rancher#9498]
**Rancher versions:**
rancher/server: 1.6.3
rancher/agent: 1.2.4

**Infrastructure Stack versions:**
healthcheck: :v0.3.1
ipsec: 
network-services:
scheduler: v0.8.2
kubernetes (if applicable): No

**Docker version: (`docker version`,`docker info` preferred)**
17.03.1-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
RancherOS v1.0.3 (4.9.34)

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node (server) with external RDS DB + host

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Deploy the (experimental) Splunk stack from our custom catalog at https://github.com/SkeltonThatcher/rancher-buildeng-catalog

**Results:**
Receive following error on stack launch -

``code=InvalidOption, fieldName=Image is required when selectorContainer is not passed in, baseType=error``

--

Hi, apologies as I know this isn't an error as such, but more a request for advice. We are trying to create a custom catalog item for splunk, adapting the official splunk docker image from https://hub.docker.com/r/splunk/splunk/ but with an EBS volume for /opt/splunk (pre-created using the Rancher EBS stack/plugin).
The base docker-compose as detailed from Docker hub runs fine locally (non EBS) but we have we are having difficulty configuring it as a catalog item. 
Any pointers would be most appreciated (we are thinking it is possibly something to do with missing label entries?). I have included the current docker-compose and rancher-compose files. 

Many thanks.

**docker-compose.yml**

```splunk:
  image: splunk/splunk:6.5.3-monitor
  environment:
    SPLUNK_START_ARGS: --accept-license --answer-yes
    SPLUNK_ENABLE_LISTEN: 9997
    SPLUNK_ADD: tcp 1514
    SPLUNK_USER: root
  volumes:
    - ${data_volume}:/opt/splunk
    - /var/lib/docker/containers:/host/containers:ro
    - /var/run/docker.sock:/var/run/docker.sock:ro
  volume_driver: ${volume_driver}
  ports:
    - ${public_port}:8000
    - 9997:9997
    - 8088:8088
    - 1514:1514
```
**rancher-compose.yml**

```.catalog:
  name: splunk-ent-mon
  version: 6.5.3-monitor
  description: |
    STCL-Tech Splunk Enterprise Monitor
  maintainer: "Rich Bos <richard.bosomworth@skeltonthatcher.com"
  uuid: splunk-ent-mon-0
  questions:
    - variable: public_port
      description: "Public port to access splunk"
      label: "Public Port"
      required: true
      default: "8000"
      type: "int"
    - variable: "data_volume"
      description: "EBS volume for splunk data"
      label: "Data volume:"
      required: true
      default: "splunkebs"
      type: "string"
    - variable: "volume_driver"
      description: "The volume driver type"
      label: "Volume driver:"
      default: "rancher-ebs"
      required: true
      type: "string"
splunk-ent-mon:
  scale: 1
  retain_ip: true
  health_check:
    port: 8000
    interval: 2000
    initializing_timeout: 60000
    unhealthy_threshold: 3
    strategy: recreate
    healthy_threshold: 2
    response_timeout: 2000
```

**Comment by rawmind0** [comment]
splunk-ent-mon template is wrong, you are calling service splunk different in docker-compose and rancher-compose. 
PR solves it and get better with volumes. 
https://github.com/SkeltonThatcher/rancher-buildeng-catalog/pull/1

**Comment by richbos** [comment]
We have identified the cause of this issue. Many thanks to https://github.com/rawmind0

We detailed `splunk-ent-mon` in `rancher-compose.yml`. Changed to just `splunk`.
