### ISSUE TITLE
Not able to log in to local auth setup because of "JWTNotProvided" error.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#9499]
Rancher versions: v1.6.6-rc4

Had a local auth enabled setup with few accounts.
Was able to log in to this set successfully for sometime.

After letting the setup be idle for sometime , attempting to login with valid credentials would log me in and immediately log me out.

Multiple attempts to log in failed.

After a while i was able to log in back successfully.

UI made the following request:
```
Request URL:http://138.68.96.110:8080/v2-beta/token/current
Request Method:DELETE
Status Code:500 Internal Server Error
Remote Address:138.68.96.110:8080
Referrer Policy:no-referrer-when-downgrade
```
```
id: "00e7952e-7397-47c5-a68b-c086d71cbfcf", type: "error", links: {}, status: 500,…}
actionLinks:{}
baseType:"error"
code:"JWTNotProvided"
detail:null
id:"00e7952e-7397-47c5-a68b-c086d71cbfcf"
links:{}
message: "Request does not contain JWT cookie"
status: 500 type:"error"
```

**Comment by cjellick** [comment]
Not needed for 8/4 RC

**Comment by vitaly-shestovskiy** [comment]
Similar issue here, not able to login via github. 
`
{"id":"93e4eabe-a937-47a9-89e9-21469db6b182","type":"error","links":{},"status":500,"code":"JWTNotProvided","message":"Request does not contain JWT cookie","detail":null,"baseType":"error","actionLinks":{}}
`

**Comment by SashaSirotkin** [comment]
I am afflicted with this issue as well with the response as everyone else:
```
{"id":"49bcf35f-0061-4454-baaa-94b33ac76d89","type":"error","links":{},"status":500,"code":"JWTNotProvided","message":"Request does not contain JWT cookie","detail":null,"baseType":"error","actionLinks":{}}
```
