### ISSUE TITLE
On upgrade settings.telemetry.opt dissapears

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#9505]
**Rancher versions:** v1.6.6-rc5

**Steps to Reproduce:**
1.   Install 1.6.5 server
2.  Go to rancher and opt out of telemetry
3.  Upgrade to 1.6.6-rc5

**Results:**  Telemetry setting is missing, so the opt in/out model comes back up.

**Comment by westlywright** [comment]
@tfiduccia can you test with master? Talked to Vince about this being a backend issue and he agreed but said he was unable to repro.

**Comment by tfiduccia** [comment]
Version - 1.6.5 to 1.6.6
My build was turning off telemetry but not setting it in db.  So when I upgrade it saw it wasn't set and asked again.  So this was not a bug.
