### ISSUE TITLE
Kubernetes environment stuck at "Waiting for Kubernetes API" after change ldap auth from user to group

### ISSUE THREAD

**Issue by acscloud** [rancher/rancher#9506]
**Rancher versions:** 1.6.5

**Docker version: (`docker version`,`docker info` preferred)** 1.12.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)** Ubuntu 16.04

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** Bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)** Single

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)** Kubernetes

**Steps to Reproduce:**

1. Enable access control with openldap, create one Kubernetes environment, and grant access to one ldap user with owner role.
2. Add hosts
3. Kubernetes environment works fine.
4. Disable access control, change some settings for group search, then enable access control again
5. Delete the user above from Kubernetes environment, add the user's group instead
6. Login Kubernetes environment, found environment stuck at "Waiting for Kubernetes API"

![error](https://user-images.githubusercontent.com/27944860/28699319-80a6c89c-737b-11e7-9bc5-3340ec3c0979.jpg)

Reference:
https://github.com/rancher/rancher/issues/9442

Add:
Recreated the whole environment, issue persists, error logs here:
```
7/28/2017 10:14:49 AME0728 02:14:49.142579       1 authentication.go:58] Unable to authenticate the request due to an error: [invalid bearer token, [invalid bearer token, invalid bearer token]]
7/28/2017 10:14:49 AME0728 02:14:49.163340       1 authentication.go:58] Unable to authenticate the request due to an error: [invalid bearer token, [invalid bearer token, invalid bearer token]]
7/28/2017 10:14:55 AME0728 02:14:55.025851       1 authentication.go:58] Unable to authenticate the request due to an error: [invalid bearer token, [invalid bearer token, invalid bearer token]]
7/28/2017 10:14:55 AME0728 02:14:55.569272       1 authentication.go:58] Unable to authenticate the request due to an error: [invalid bearer token, [invalid bearer token, invalid bearer token]]
7/28/2017 10:15:00 AME0728 02:15:00.855652       1 authentication.go:58] Unable to authenticate the request due to an error: [invalid bearer token, [invalid bearer token, invalid bearer token]]
7/28/2017 10:15:06 AME0728 02:15:06.153319       1 authentication.go:58] Unable to authenticate the request due to an error: [invalid bearer token, [invalid bearer token, invalid bearer token]]
7/28/2017 10:15:11 AME0728 02:15:11.437003       1 authentication.go:58] Unable to authenticate the request due to an error: [invalid bearer token, [invalid bearer token, invalid bearer token]]
```

**Comment by deniseschannon** [comment]
You are hitting this issue: https://github.com/rancher/rancher/issues/9150

Groups don't work with k8s RBAC in k8s 1.6.5 but it will be fixed in the next Rancher release with our k8s v1.7.
