### ISSUE TITLE
[Help needed] Generate environment Kubernetes token

### ISSUE THREAD

**Issue by acscloud** [rancher/rancher#9507]
**Rancher versions:** 1.6.5
Kubernetes version : 1.6.6

Hi, 

Rancher v1.6.5 changed kubectld authentication from username/password to token, but this is a user level token, how can I generate an environment level token? looks like we can only get a key pair from api tab. Thanks a lot.

**Comment by joshwget** [comment]
We changed the authentication for Kubernetes to be at the user level to better integrate with RBAC. Is there a reason you'd prefer to have this at the environment level in your case?

**Comment by acscloud** [comment]
@joshwget OK. Not a mandatory requirement, just with user level token we have to create dedicated users for CICD purpose.

**Comment by acscloud** [comment]
@joshwget Just one more question, is it possible to pre-create an user level token instead of checking it out from generated kubeconfig file? Because we can only get a user/password key pair from api tab, how can we convert it to the token used for kubectl? Thanks.
