### ISSUE TITLE
option to disable healthcheck in cattle

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#9510]
Sometimes in a problematic k8s environment rancher-k8s-agent, rancher-k8s-ingress are in a delete, recreate loop making it difficult to do any kind of debugging. Disabling the healthcheck stack is not sufficient to stop this loop. Need an option in cattle to turn off healthcheck logic.

**Comment by leodotcloud** [comment]
I think we should disable healthcheck during ipsec/vxlan upgrades. This will make the k8s cluster much stable during upgrades, instead of moving around services.

**Comment by LLParse** [comment]
@leodotcloud Responding to your top comment.

I agree it is difficult to debug a container in a crash loop. I would like to see exponential backoff of some sort added to cattle to alleviate the CPU strain when this happens. This will simultaneously make it possible to actually read the failing container's logs from the UI.

That alone isn't enough, a generic log aggregation tool similar to https://github.com/galal-hussein/rancher-fluentd-Influxdb can capture the historical logs for analysis. We might even consider making it an infra-service that is installed by default. Log data could be purged aggressively via configurable retention period.

Could you create a new issue for the latter comment? I don't necessarily agree that disabling healthchecks in cattle should be a user-available option and want to keep the two different use cases separate.

**Comment by LLParse** [comment]
I changed my mind - being able to disable healthchecks would be a valuable feature. We should carefully consider what to do regarding healthchecks during overlay network upgrades.

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
