### ISSUE TITLE
Not able to launch Dashboard UI after force upgrading ipsec.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#9511]
Rancher versions:v1.6.6-rc5

Kubernetes environment with isolated planes.
Able to launch Dashboard successfully.
Force upgraded ipsec service.

After ipsec service was upgraded successfully , not able to launch Dashboard successfully. It hangs for sometime after which timeout error message is seen:

<img width="1637" alt="screen shot 2017-07-28 at 12 21 11 pm" src="https://user-images.githubusercontent.com/4266958/28733155-a7e03f10-738f-11e7-8b84-2accd1cae29e.png">

**Comment by alena1108** [comment]
Duplicate of https://github.com/rancher/rancher/issues/9451

**Comment by alena1108** [comment]
Opening this bug so we can track ipsec failure here. So what happened is:

1) Initially dashboard D1 pod was launched on host1.
2) ipsec upgraded.
3) Host1 ipsec network was not available from any other hosts in the system after that.
4) k8s recreated the dashboard container D2 on another host.

websocket proxy continued pointing to D1 container though for the dashboard due to cache (resolved as a part of the fix for 9451). D1 could not be destroyed as kubelet on this host was unreachable by the k8s api server. Once the connectivity got restored, the D1 got destroyed as well

**Comment by leodotcloud** [comment]
Networking issue is being tracked here: https://github.com/rancher/rancher/issues/9508. @alena1108 @deniseschannon I think we can close this?

**Comment by sangeethah** [comment]
Rancher versions:
rancher/server: v1.6.6-rc6
kubernetes (if applicable): rancher/k8s:v1.7.2-rancher5

Force upgrade Ipsec service.
Even after the Ipsec service was upgraded successfully , one of the hosts (compute node) continues to be in "NotReady" state.
For the time Host is in "NotReady" state , we are not able to access the Dashbord and we get timeout issues:

Get https://10.43.0.1:443/api/v1/namespaces/default/pods: dial tcp 10.43.0.1:443: i/o timeout

We see 2 Dashboard containers.

Once the hosts gets to "Ready" state ( have seen it take up to 20 mts) , Dashboard starts to work.

@alena1108 's comments:
unfortunately we can’t do much about this particular dashborad scenario. It really all comes down to broken network connectivity and the fact that we do not manage healthcheck for k8s containers
so we can’t kill that dashboard, and k8s can’t kill it either as kubelet/api server connectivity is broken

**Comment by sangeethah** [comment]
@leodotcloud In case of  #9508 , kubernetes stack itself is unhealthy. But in this case , K8s stack is reported as being in healthy state. We have problems only launching the Dashboard in this case and have noticed that the issues goes away once all the hosts get to "Ready" state.

The issue of hosts taking a long time to get to "Ready" state after a forced upgrade of ipsec is tracked in https://github.com/rancher/rancher/issues/9389 .

**Comment by sangeethah** [comment]
Tested with rancher-server version - v1.6.6-rc6 , rancher/net:v0.11.5 , rancher/network-manager:v0.7.6 and rancher/k8s:v1.7.2-rancher5.

Tested with kubernetes deployed in requirer plane with 3 etcd nodes , 4 compute nodes and 4 orchestration nodes.

After force upgrading ipsec , all compute nodes get to "Ready" state quickly and able to launch Dashboard UI.

Tested this multiple times and did not encounter any issues relating to launching Dashboard.
