### ISSUE TITLE
Debugging private catalogs

### ISSUE THREAD

**Issue by zambon** [rancher/rancher#9513]
**Rancher versions:**
rancher/server: v1.6.4
rancher/agent: v1.2.5

**Infrastructure Stack versions:**
healthcheck: v0.3.0
ipsec: 0.1.1
network-services: v0.2.3
scheduler: v0.6.2
kubernetes (if applicable): N/A

**Docker version: (`docker version`,`docker info` preferred)** 17.03.1-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04.2
4.4.0-21-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** Internal dev cloud

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)** Single node, external DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:**

Start by adding a private Rancher catalog. Then:

1. Make changes to the latest version of the template.
2. Force a catalog refresh using the UI.
3. Repeat.

**Results:**

Sometimes the modified template won't be list in the _Template Version_ dropdown.

I _suspect_ this issue can be triggered by publishing a template version with syntax errors. Restarting Rancher server seems to fix the problem (granted the syntax errors on the template are fixed).

How can I debug this problem? Rancher server's output and `/var/lib/cattle/logs` don't have any error messages related to the catalogs.

**Comment by joshuacox** [comment]
+1  I'd personally like to see some sort of console when hitting the catalog reload button that let's me know when I blew up the yaml etc, this can lead to insanity.

**Comment by jmaasing** [comment]
Some sort of console or easy access to logging would be great. I have tried several times to add private self-hosted catalogs and while git has no problem cloning them (without any auth or anything) they just do not show up in the UI.

**Comment by deniseschannon** [comment]
Displaying catalog-service errors when trying to pull a catalog would be the first item that could help with debugging.  https://github.com/rancher/rancher/issues/8438

**Comment by cianiandreadev** [comment]
@deniseschannon what is the status of this? Is there a way to have some feedback? It is really driving me crazy :(

**Comment by deniseschannon** [comment]
@cianiandreadev

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

What are you specifically facing for an issue? Are your templates showing up or not?
