### ISSUE TITLE
unable to find history of mac_address in cattle

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#9516]
While debugging a networking problem when an ARP entry seemed to flap for few minutes, I wanted to find out which container had the MAC address. But I couldn't find this information in the database. The NIC table had `purged` entries but the MAC address was set to NULL.

Storing this historical information is important both for audit and debugging purposes.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
