### ISSUE TITLE
K8s pods failing with "The node was low on resource: [DiskPressure]." After upgrade from Rancher v1.5.7 to v1.6.6-rc6

### ISSUE THREAD

**Issue by moelsayed** [rancher/rancher#9518]
**Rancher versions:**
rancher/server: v.16.6-rc6

**Infrastructure Stack versions:**
kubernetes (if applicable): rancher/k8s:v1.7.2-rancher5

**Docker version: (`docker version`,`docker info` preferred)**
1.12.6
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
 Ubuntu 16.04.2 LTS
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node, internal DB
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
k8s
**Steps to Reproduce:**
* Install Rancher v1.5.7
* Create a k8s environment
* Upgrade to Rancher v1.6.6-rc6
* Upgrade infrastructure stacks
* Upgrade k8s 
* Create some pods

**Results:**
Some pods are failing with the error:
```
The node was low on resource: [DiskPressure]. 
```
Kubelet log on the node is showing:
```
7/29/2017 11:23:35 PMW0729 21:23:35.409653   14475 helpers.go:771] eviction manager: no observation found for eviction signal allocatableNodeFs.available
7/29/2017 11:23:45 PMW0729 21:23:45.454615   14475 helpers.go:771] eviction manager: no observation found for eviction signal allocatableNodeFs.available
7/29/2017 11:23:55 PMW0729 21:23:55.488275   14475 helpers.go:771] eviction manager: no observation found for eviction signal allocatableNodeFs.available
```

**Comment by moelsayed** [comment]
Possibly related to: https://github.com/kubernetes/kubernetes/issues/48703

**Comment by alena1108** [comment]
```no observation found for eviction signal allocatableNodeFs.available``` is sync message, happens every 10 secs. Will be disabled in the future release of k8s. 

```The node was low on resource: [DiskPressure]. ``` is a real indication that the host was actually down on the disk space. Happened on 10GC qa host setup when the disk usage was ~90% with k8s eviction limit <=10% of free space. Closing as works as expected.
