### ISSUE TITLE
Feature Request: Makes k8s service IP range configurable

### ISSUE THREAD

**Issue by dbason** [rancher/rancher#9520]
In our environment we can't use the 10.43.0.0 CIDR for k8s so it would be nice if this was an option to be changed in the infra template.

There are a few places in the docker-compose template that need to be updated.  The heapster and dns deployments in the k8s image for the addon-starter would also need to be updated to have the dns address and api address configurable.

**Comment by superseb** [comment]
This is released in v1.6.11 and higher: https://github.com/rancher/rancher/issues/9310
