### ISSUE TITLE
Kubernetes pulled image digest instead of tag

### ISSUE THREAD

**Issue by hiscal2015** [rancher/rancher#9525]
**Rancher versions:** 1.6.5
Kubernetes version: 1.6.6

Hi, After upgrade/or clean install rancher v1.6.5, found it will not show the readable image version any more (except rancher infrastructure images), please see the picture below, is this an expected behavior? Thanks.

![rancherimage](https://user-images.githubusercontent.com/15604715/28765267-92334e4a-75fc-11e7-8604-dce8e7e62184.jpg)

**Comment by hiscal2015** [comment]
Does anyone know is this an issue or expected behavior? Thanks.

**Comment by vincent99** [comment]
AFAIK we show exactly what the container was deployed with, and always have.

**Comment by hiscal2015** [comment]
@vincent99 by docker ps from the host, the version is the same indeed, but I didn't change anything, it is normal before Rancher v1.6.5, what's the possible cause?

```
31be7982cf1f        demo.com/grafana@sha256:e0ea8b2ff0df2a6df0dca997a9ef95c2c4bd94c3c921f434588b23172a17a0a9                                  "/run.sh"                6 days ago          Up 6 days                               k8s_devops-grafana_devops-grafana-1623218485-7t03v_default_085c8e56-774f-11e7-88ea-02afb77fd1db_0
```

**Comment by hiscal2015** [comment]
and by checking deployment from Kubernetes dashboard, I defined with image tag not digest.

![image](https://user-images.githubusercontent.com/15604715/29108962-b89855da-7d13-11e7-8c42-d508fbb2be24.jpg)

**Comment by hiscal2015** [comment]
@vincent99 did you experience this issue after rancher v1.6.5, only I have such issue?
