### ISSUE TITLE
Cannot select Docker engine on RancherOS when specifying --engine-install-url through machine

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#9528]
**Rancher versions:**
rancher/server: v1.6.5
rancher/agent: n/a

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
RancherOS v1.0.3

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS, AMI ami-bed0c7c7

**Steps to Reproduce:**
* Add Host using AWS machine driver using RancherOS AMI, and by leaving engine-install-url to the default of `https://releases.rancher.com/install-docker/1.12.sh`

**Results:**
RancherOS gets added with default Docker version (`17.03.1-ce`)

**Solution:**
Update docker-machine so it includes the fix to use engine-install-url to switch Docker version on RancherOS (https://github.com/docker/machine/pull/4082/files)

**Comment by deniseschannon** [comment]
If go-machine-service updates to at least `v0.12.2` of docker-machine, then this should be possible/working.

**Comment by rockandska** [comment]
The update of docker-machine to v0.12.2 should solve rancher/os#1750 too

**Comment by cjellick** [comment]
Can be tested on v1.6-development as of time/date of this comment

**Comment by soumyalj** [comment]
Tested with v1.6-development. Added host using AWS machine driver using RancherOS AMI. The default install URL(https://releases.rancher.com/install-docker/1.12.sh) was chosen. Host with docker 1.12.6 was added successfully.
<img width="258" alt="screen shot 2017-10-10 at 2 34 13 pm" src="https://user-images.githubusercontent.com/18536626/31411952-25113be8-adc8-11e7-8224-0ecdf903f7b0.png">
