### ISSUE TITLE
Ports are not being sent when I edit/upgrade

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#9531]
**Rancher versions:** master 2.0 7/31

**Steps to Reproduce:**
1.  Upgrade container and add a port

**Results:** The port is missing from the payload
![image](https://user-images.githubusercontent.com/11514927/28803618-c445b4a2-7612-11e7-93ad-73c543bacdc9.png)

**Comment by westlywright** [comment]
@tfiduccia similar to the previous issue we had about this, the ports schema indicates this can not be updated. I will do an audit of the container edit/upgrade page and verify everything on the page is updatable. I'll remove ports for now but we should maybe open a bug in cattle if ports should be editable.
