### ISSUE TITLE
 Portainer 1.13.4 is not working with rancher swarm template

### ISSUE THREAD

**Issue by AmreeshTyagi** [rancher/rancher#9538]
*In build portainer not loading docker images & containers, but I can see them from terminal & swarm cli tool.*

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.6` Cattle: `v0.183.5` UI: `v1.6.17` |
|Access|`localauth` `admin`|
|Orchestration|`Swarm`|
|Route|`swarm-tab.dashboard`|

**Comment by superseb** [comment]
Can you describe what you are trying to do and what does not work? Also, used OS and Docker versions.
