### ISSUE TITLE
Problem using Kubernetes with AWS cloud provider and AzureAD authentication on rancher-server

### ISSUE THREAD

**Issue by cabrinoob** [rancher/rancher#9539]
**Rancher versions:**
rancher/server: 1.6.4
rancher/agent: rancher/k8s:v1.6.6-rancher1-4

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
1.12.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS

**Steps to Reproduce:**
1-Enable Azure AD Authentication
2-Create a new K8S environment template by choosing AWS cloud provider (and save)
3-Create a new environment with this K8S new template

**Results:**
Everything works well until the last step : "Waiting for Kubernetes API" (always spining)

The problem is that, when the K8S environment is setting up, the kubernetes agent is blocked on this error : 

    01/08/2017 10:54:23E0801 08:54:23.602992       1 authentication.go:58] Unable to authenticate the request due to an error: [invalid bearer token, [invalid bearer token, an error on the server ("Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [code=AzureAccessToken, message=No Azure Access token, baseType=error] from [http://rancher-server.xxxx.net/v2-beta/projectmembers?projectId=1a502]") has prevented the request from succeeding]]

If I deactivate the authentication, it works!

If I leave AzureAD authent and if I choose "rancher" cloud provider, it works too.

Is it a bug?

**Comment by joshwget** [comment]
@cabrinoob Do you mind trying this again with Rancher v1.6.6 or v1.6.7 and Kubernetes 1.7?

**Comment by cabrinoob** [comment]
Ok, I'll try

**Comment by superseb** [comment]
Closing as stale.
