### ISSUE TITLE
Linked services do not get populated properly when you edit a container

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#9544]
**Rancher versions:**
rancher/server: 1.5.10
rancher/agent: 1.2.2

If you edit a container directly in the UI that has linked services (whether in the same stack or others) it will not populate the dropdowns.

![screen shot 2017-08-01 at 1 19 46 pm](https://user-images.githubusercontent.com/48329/28842764-20840648-76bc-11e7-80d8-4bce37b91f93.png)

**Comment by vincent99** [comment]
Container links are to a specific container instance.  If you're linking to an instance created by a service and that service is upgraded, a healthcheck fails, or any other condition that causes that container to be replaced, it's no longer the same container and that link is now to nowhere.

You're talking about stack and service though, so container links don't even make any sense.

What's happening is:
  - You create service A with scale=3
  - 3 containers for `stack-A-1` (1i42), `stack-A-2` (1i43), `stack-A-3` (1i44)
  - You create service B with scale=1 and link to A
  - A container is created for `stack-B-1`, it has a single instance link to **one of** the three A containers (randomly?)
  - A is upgraded, so 1i42/43/44 is deleted and replaced with new ones
  - B now has an instanceLink pointed at 1i42, which no longer exists
  - On edit no instance matches 1i42, so nothing is selected in the dropdown

@alena1108 why are service links even creating instanceLinks?

**Comment by ekristen** [comment]
Fair enough @vincent99, it seemed like a bug, if not so be it, just trying to report inconsistencies. I though this was like the service dropdowns in the catalog not populating back to their configured values on update or change.

**Comment by vincent99** [comment]
It is a bug, but I think the bug is that instance links show up at all...

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
