### ISSUE TITLE
Feature Request: Rancher Server Process Queue Metrics 

### ISSUE THREAD

**Issue by wjimenez5271** [rancher/rancher#9545]
It would be useful to have metrics on the performance of the rancher process queues, such as queue depth, avg. processing time, etc. Ideally these would be exportable to some time series database such as graphite, and/or consumable through a prometheus scraper.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
