### ISSUE TITLE
rancher webhooks

### ISSUE THREAD

**Issue by zhouxt** [rancher/rancher#9551]
*Describe your issue here*
hi,when i use rancher webhoos,I excute the command "curl -H 'Accept: application/json'  -u "D84999571488186B7AD9:VnvE95bmAGVuULPQfVMDoQBEhVenF9dA5ic4jFW3" http://10.192.52.18:8080/v1-webhooks/endpoint?key=IuQlDl5s8tt8NQU44KUXajfEGwc0ESu4kcAmrmXR&projectId=1a377" ,result is 404 page not found,why?

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.5` Cattle: `v0.182.1` UI: `v1.6.9` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`stacks.index`|

**Comment by mrajashree** [comment]
@zhouxt The request needs to be POST, the one you posted above is GET

**Comment by zhouxt** [comment]
@mrajashree  hello ,thanks for your answers, I try it with add the option "-X POST", and it doesn't work

**Comment by mrajashree** [comment]
@zhouxt can you share the output of your curl command?

**Comment by superseb** [comment]
Please comment if you need help on this.
