### ISSUE TITLE
Heapster failed on k8s 1.7.2

### ISSUE THREAD

**Issue by antmanler** [rancher/rancher#9552]
**Rancher versions:**
rancher/server: v1.6.6

**Infrastructure Stack versions:**
kubernetes (if applicable): rancher/k8s:v1.7.2-rancher5

**Docker version: (`docker version`,`docker info` preferred)**

```shell
docker version
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:26:30 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:26:30 2017
 OS/Arch:      linux/amd64
```
```shell
docker info
Containers: 46
 Running: 37
 Paused: 0
 Stopped: 9
Images: 33
Server Version: 1.12.6
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 276
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local rancher-nfs
 Network: host null bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 4.4.0-62-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.42 GiB
Name: ra-worker1
ID: MLL5:R6B6:TL7B:SBFU:6XYI:MZC7:ANRL:XQXO:UIVL:JOPR:PNUT:CGXJ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Labels:
 provider=we87
Insecure Registries:
 127.0.0.0/8
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

```shell
cat /etc/os-release
NAME="Ubuntu"
VERSION="14.04.5 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.5 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"

uname -r
4.4.0-62-generic
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

aliyun

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher, external DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

Kubernetes

**Steps to Reproduce:**

* Install rancher v1.6.6
* Deploy k8s environment
* Check the log of running heapster

**Results:**

> 8/2/2017 8:51:05 AME0802 00:51:05.000295       1 kubelet.go:280] Node ra-master0 has no valid hostname and/or IP address: ra-master0
> 8/2/2017 8:51:05 AME0802 00:51:05.000302       1 kubelet.go:280] Node ra-worker0 has no valid hostname and/or IP address: ra-worker0
> 8/2/2017 8:51:05 AME0802 00:51:05.000307       1 kubelet.go:280] Node ra-worker1 has no valid hostname and/or IP address: ra-worker1
> 8/2/2017 8:51:05 AME0802 00:51:05.000313       1 kubelet.go:280] Node ra-worker2 has no valid hostname and/or IP address: ra-worker2
> 8/2/2017 8:52:05 AME0802 00:52:05.000352       1 kubelet.go:280] Node ra-worker3 has no valid hostname and/or IP address: ra-worker3

**Comment by antmanler** [comment]
I think this issue is introduced by 

https://github.com/rancher/rancher-cloud-controller-manager/blob/master/rancher/rancher.go#L656

```go
for _, ip := range host.IPAddresses {
	addresses = append(addresses, api.NodeAddress{
		Type:    api.NodeExternalIP,
		Address: ip.Address,
	})
}
```

before 1.7, cloud provider was embedded in k8s repo and `api.NodeLegacyHostIP` was added to node object:

https://github.com/rancher/kubernetes/blob/v1.6.6-rancher/pkg/cloudprovider/providers/rancher/rancher.go#L643

```go
addresses := []api.NodeAddress{}
for _, ip := range host.IPAddresses {
	addresses = append(addresses, api.NodeAddress{Type: api.NodeExternalIP, Address: ip.Address})
	addresses = append(addresses, api.NodeAddress{Type: api.NodeLegacyHostIP, Address: ip.Address})
}
addresses = append(addresses, api.NodeAddress{Type: api.NodeHostName, Address: host.RancherHost.Hostname})
```

?

```diff
for _, ip := range host.IPAddresses {
	addresses = append(addresses, api.NodeAddress{
		Type:    api.NodeExternalIP,
		Address: ip.Address,
	})
+	addresses = append(addresses, api.NodeAddress{
+		Type:    api.NodeLegacyHostIP,
+		Address: ip.Address,
+	})
}
```

**Comment by alena1108** [comment]
@antmanler NodeLegacyHostIp was removed in k8s 1.7 (https://github.com/kubernetes/kubernetes/pull/44830) 

I'm going to look if putting an internalIpAddress on a node object would fix the problem. I recall that having it had some issues

**Comment by alena1108** [comment]
@antmanler could you share the output of ```kubectl describe node``` while the problem is happening (without your [patch](https://github.com/we87/rancher-cloud-controller-manager/commit/89f14ea608bbb30aec6553188e7e50079370cba1))? I'd like to see what ip addresses were set to.

**Comment by antmanler** [comment]
@alena1108 The following output is copied from slack (I pasted yesterday)

My vms are in aliyun VPC, vm host has only one network card with an intranet IP

```
kubectl describe node/ra-worker0
Name:            ra-worker0
Role:
Labels:            beta.kubernetes.io/arch=amd64
            beta.kubernetes.io/os=linux
            compute=true
            etcd=true
            io.rancher.host.docker_version=1.12
            io.rancher.host.linux_kernel_version=4.4
            kubernetes.io/hostname=ra-worker0
Annotations:        io.rancher.labels.compute=
            io.rancher.labels.etcd=
            io.rancher.labels.io.rancher.host.docker_version=
            io.rancher.labels.io.rancher.host.linux_kernel_version=
            node.alpha.kubernetes.io/ttl=0
            volumes.kubernetes.io/controller-managed-attach-detach=true
Taints:            <none>
CreationTimestamp:    Tue, 01 Aug 2017 21:32:55 +0800
Conditions:
  Type            Status    LastHeartbeatTime            LastTransitionTime            Reason                Message
  ----            ------    -----------------            ------------------            ------                -------
  OutOfDisk         False     Wed, 02 Aug 2017 08:53:22 +0800     Tue, 01 Aug 2017 21:32:55 +0800     KubeletHasSufficientDisk     kubelet has sufficient disk space available
  MemoryPressure     False     Wed, 02 Aug 2017 08:53:22 +0800     Tue, 01 Aug 2017 21:32:55 +0800     KubeletHasSufficientMemory     kubelet has sufficient memory available
  DiskPressure         False     Wed, 02 Aug 2017 08:53:22 +0800     Tue, 01 Aug 2017 21:32:55 +0800     KubeletHasNoDiskPressure     kubelet has no disk pressure
  Ready         True     Wed, 02 Aug 2017 08:53:22 +0800     Tue, 01 Aug 2017 21:33:05 +0800     KubeletReady             kubelet is posting ready status
Addresses:
  ExternalIP:    192.168.87.64
  Hostname:    ra-worker0
Capacity:
 cpu:        4
 memory:    8175100Ki
 pods:        110
Allocatable:
 cpu:        4
 memory:    8072700Ki
 pods:        110
System Info:
 Machine ID:
 System UUID:            002EC33D-FFB0-48BE-8889-B67F61356B0A
 Boot ID:            c8a798ab-bc86-4833-b240-442d5164c1c9
 Kernel Version:        4.4.0-78-generic
 OS Image:            Ubuntu 16.04.1 LTS
 Operating System:        linux
 Architecture:            amd64
 Container Runtime Version:    docker://1.12.6
 Kubelet Version:        v1.7.2
 Kube-Proxy Version:        v1.7.2
ExternalID:            ra-worker0
Non-terminated Pods:        (8 in total)
  Namespace            Name                        CPU Requests    CPU Limits    Memory Requests    Memory Limits
  ---------            ----                        ------------    ----------    ---------------    -------------
  kube-system            fluentd-pilot-g0fqj                100m (2%)    0 (0%)        200Mi (2%)    200Mi (2%)
  kube-system            kubernetes-dashboard-716739405-scl9g        100m (2%)    100m (2%)    50Mi (0%)    50Mi (0%)
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  CPU Requests    CPU Limits    Memory Requests    Memory Limits
  ------------    ----------    ---------------    -------------
  200m (5%)    100m (2%)    250Mi (3%)    250Mi (3%)
Events:        <none>
```

**Comment by antmanler** [comment]
here is the code from heapster to find node's IP,  brefore 1.7.2, rancher's cloud provider also sets `api.NodeLegacyHostIP `, which hits heapster's fallback when `addr.Address != "" && ip == ""`, so it works as expected

https://github.com/kubernetes/heapster/blob/master/metrics/sources/kubelet/kubelet.go#L302

```go
for _, addr := range node.Status.Addresses {
	if addr.Type == kube_api.NodeHostName && addr.Address != "" {
		hostname = addr.Address
	}
	if addr.Type == kube_api.NodeInternalIP && addr.Address != "" {
		if net.ParseIP(addr.Address).To4() != nil {
			ip = addr.Address
		}
	}
	if addr.Type == kube_api.NodeLegacyHostIP && addr.Address != "" && ip == "" {
		ip = addr.Address
	}
}
if ip != "" {
	return hostname, ip, nil
}
return "", "", fmt.Errorf("Node %v has no valid hostname and/or IP address: %v %v", node.Name, hostname, ip)
```

**Comment by alena1108** [comment]
@antmanler thanks, I'll check the heapster. One more question - is the externalIp=192.168.87.64 from the "describe node" is the ip address that you see on the host object in Rancher?

**Comment by antmanler** [comment]
Yes it's the same IP

**Comment by alena1108** [comment]
@antmanler NodeLegacyHostIP was removed from k8s node API, so it can no longer be set. We will add NodeInternalIP. Hope it will resolve the heapster issue given that it tries to get it from the NodeInternalIP address first:

```
if addr.Type == kube_api.NodeInternalIP && addr.Address != "" {
```

**Comment by antmanler** [comment]
@alena1108 yes, adding NodeInternalIP fixed my issue, and I forked rancher-cloud-controller-manager and had a quick fix, heapster worked normally.

https://github.com/we87/rancher-cloud-controller-manager/commit/89f14ea608bbb30aec6553188e7e50079370cba1

But, I think this simple patch is not good enough, what if someone has host with more than one IP, say, one for internal and one public. I think rancher should figure out how to handle nodes' IPs correctly when applying k8s infras

**Comment by alena1108** [comment]
Can be validated with rancher/k8s:v1.7.2-rancher7

@antmanler agree with you. But distinguishing between ips of the host first has to be implemented in rancher (cattle) before fixing it in kubernetes, because today there is none.

**Comment by deniseschannon** [comment]
@antmanler Can you try using rancher/k8s:v1.7.2-rancher7 in the `v1.6-development` branch of Rancher catalog to see if that solves it for you? Note: We went back to using our forked branch and upon upgrading, you'll need to remove the `rancher-cloud-controller-manager` service from the kuberenetes stack manually.

**Comment by laszlocph** [comment]
I'd be also happy to try, but don't really know how to set a specific branch in the environment templates. I only see v1.7.2-rancher5

**Comment by laszlocph** [comment]
I was able to add it, thanks to @superseb 
> Add a catalog through Admin -> Settings and name it library, with the rancher-catalog github url and the given branch

and now Heapster is sending the metrics. No other obvious issue with the branch for now.

**Comment by antmanler** [comment]
@deniseschannon  sorry for late reply, and thx @laszlocph 

I tried on a fresh cluster with k8s switching to v1.7.2-rancher7, this issue seems to be fixed. 👍

**Comment by galal-hussein** [comment]
Rancher server: v1.6.7-rc1
 Kubernetes: rancher/k8s:v1.7.2-rancher7

Heapster seems to be working correctly, and grafana is showing the stats correctly for the nodes and the pods.
