### ISSUE TITLE
Rancher dashboard is vulnerable to Clickjacking.

### ISSUE THREAD

**Issue by introvertmac** [rancher/rancher#9553]
Rancher dashboard opens in an iframe of other websites, which is a security issue. It can be fixed by using x-frame-header with sameorigin or deny values.

More on Clickjacking: [Clickjacking](https://en.wikipedia.org/wiki/Clickjacking) 

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.5` Cattle: `v0.182.1` UI: `v1.6.9` |
|Access|`github` |
|Orchestration|`Cattle`|
|Route|`stacks.index`|

**Comment by vincent99** [comment]
True (except it's `X-Frame-Options`), but also a feature for some users, so it needs to be configurable with a setting.

**Comment by introvertmac** [comment]
I don't want my Rancher dashboard to open in other's iframe. Can I add X-frame-options on my side, is there any settings available for that from UI?

**Comment by vincent99** [comment]
It is not currently.  If you're doing SSL termination you can add the header there (and if you're not clickjacking probably should be the top of your last of problems...)

**Comment by introvertmac** [comment]
Let me check! Thanks for your time @vincent99 👍
