### ISSUE TITLE
Web interface Infrastructure -> host page very slow can crash the browser

### ISSUE THREAD

**Issue by jean-francois-labbe** [rancher/rancher#9555]
**Rancher versions:**
rancher/server:1.6.3
rancher/agent:

**Docker version: 17.03**

**Operating system and kernel: rancher-os**

**Type/provider of hosts: AWS**

**Setup details: HA rancher**

**Environment Template: Cattle**

**Steps to Reproduce:**
Create multiple hosts and deploy multiple services on them
browse to the host page, remove a host or restart a stack or perform some operation that will affect many stacks or many hosts, then the web page will be very slow and will eventually kill the browser tab.

**Comment by jean-francois-labbe** [comment]
This is happening very frequently to me.
The web interface is very slow when deploying multiple containers.

I manage a continuous integration environment with rancher, a lots of containers gets created and deleted, then the page infrastructure -> host tries to display all the containers status and finally crashes.

**Comment by superseb** [comment]
The dots view might help you out for now. How many hosts and containers are we talking about? We are doing lots of work for performance/scale in 2.0.

**Comment by vincent99** [comment]
2.0 sends less events and draws a limited set of hosts and containers at a time, so this should be better.
