### ISSUE TITLE
Catalog page content not updating when picking new catalog from dropdown.

### ISSUE THREAD

**Issue by pulberg** [rancher/rancher#9558]
**Rancher versions:**
rancher/server: v1.6.6
rancher/agent: v1.2.5

**Docker version: (`docker version`,`docker info` preferred)**
1.12.6 / 17.06-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16 / RHEL7.3

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
vmware

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
cattle

**Steps to Reproduce:**
Navigate to main catalog page, choose any catalog item and click "view details".  Now, from the "Catalog" drop-down menu in the upper left, choose any catalog item.  

**Results:**
Notice that the main info and form fields are for the previously selected catalog item, but the newly chosen catalog item logo and info is displayed.

![screen shot 2017-08-02 at 5 01 34 pm](https://user-images.githubusercontent.com/11069351/28896965-4d2b0bd6-77a4-11e7-85ad-71d10326d1f7.png)

**Comment by cjellick** [comment]
Is this a custom catalog? If so,  is it hosted on github as a public repo or is it hosted somewhere else?

**Comment by pulberg** [comment]
No, these are just the default public catalogs.

**Comment by vincent99** [comment]
#6470
