### ISSUE TITLE
ip route missing

### ISSUE THREAD

**Issue by hongxiaolu** [rancher/rancher#9563]
**Rancher versions:**
rancher/server:v1.6.5
rancher/agent:v1.2.5

**Infrastructure Stack versi.ons:**
healthcheck:v0.3.1
ipsec:
       net: v0.11.3
       net: holder
network-services: 
        network-manager:v0.7.4
        metadata:v0.9.2
        dns:v0.15.1
scheduler:
        rancher/scheduler:v0.8.2
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
1.12.6
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
ubuntu 16.04.2 LTS
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VMware Fusion
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**

**Results:**

When Executing command to add Rancher-agent node, the error prompted: Failed to connect to xxx.xxx.xxx.xxx port 8080 :No route to host 

I executed the command （ip route）to see the routing table, No routing information about docker0 was found. When I restart host, the problem will disappear

<img width="922" alt="wx20170801-153738 2x" src="https://user-images.githubusercontent.com/20707603/28905025-4566a188-7841-11e7-8aab-2ce4563cb7cf.png">

**Comment by niusmallnan** [comment]
@hongxiaolu 
The routing table for docker0 is controlled by docker itself.
Agent registration is running in a docker container, if docker0 routing table is missing, agent process cannot access rancher server.

Please find the reason for docker0 routing table missing, when you have a chance.

**Comment by hongxiaolu** [comment]
thanks!
