### ISSUE TITLE
Feature Request - Global Custom Catalogs

### ISSUE THREAD

**Issue by vikas027** [rancher/rancher#9564]
**Rancher versions:**
rancher/server: 1.6.6
rancher/agent: 1.2.5

**Problem**
If we have a repository for custom catalogs, then it needs to be added in each environment. 

**Feature Request**
It would be great if a custom catalog can also be inherited in each environment like the default ones (`library` and `community`). This feature can be optional too. 

**Workaround** (May be)
Can we manage (create/delete) catalogs using APIs? I couldn't find anything in [v1](http://rancher.com/docs/rancher/v1.6/en/api/v1/api-resources/) or [v2-beta](http://rancher.com/docs/rancher/v1.6/en/api/v2-beta/) APIs, inspecting `Network` in the browser or in rancher [cli](https://github.com/rancher/cli).

```
$ rancher catalog --help
Operations with catalogs

Usage: rancher catalog [OPTIONS] COMMAND [arg...]

Version: v0.6.3

Options:
  --quiet, -q     Only display IDs
  --format value  'json' or Custom format: '{{.ID}} {{.Template.Id}}'
  --system, -s    Show system templates, not user
  --help, -h      show help

Commands:
  ls       List catalog templates
  install  Install catalog template
  help     Shows a list of commands or help for one command

Run 'rancher catalog COMMAND --help' for more information on a command.
```

**Comment by vincent99** [comment]
Admin -> Settings has global catalogs.

**Comment by vikas027** [comment]
Thanks Vincent, Can I manage it thru API? I couldn't find a way to do it.

**Comment by vikas027** [comment]
I have figured out the payload to pass on curl post request now, closing the ticket.
