### ISSUE TITLE
Suggestion: Please add commit and push interface in rancher web ui.

### ISSUE THREAD

**Issue by lifubang** [rancher/rancher#9565]
Our experiment environment is deploy by rancher. When the container changed, I need to login the server to commit and push docker image. If the rancher web ui supply commit and push button, It'll be better or perfect. Then the rancher will become the full stack docker operating platform.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
