### ISSUE TITLE
Configuring persistent storage is prohibitively difficult outside of AWS

### ISSUE THREAD

**Issue by robotmay** [rancher/rancher#9566]
Unless you're using AWS then configuring storage volumes in Rancher is a massive pain in the arse. I have a split-cloud approach at the moment and the options are severely limited. I don't even want persistent volumes; I host my databases outside of the stack and any data written to the volumes is stuff I really don't care about, but it's incredibly awkward to get any of the current solutions set up. Unfortunately quite a few existing catalogs require volumes to be set up, and it would be useful when moving containers between hosts etc.

Is there no simple way to just set a directory on one of the servers as a storage volume? All the existing approaches are frustrating in their own way:

* NFS: have to manage security and access across two clouds
* Portworx: requires an etcd cluster, which never boots correctly for me
* Rex-ray: catalog entry doesn't support all the platforms, limited to only working on one of my two hosting platforms, and it's pretty complicated to set up

I've even tried using a dockerized NFS server, but that only worked when accessed via a public IP, which is weird.

This is the one major stumbling block I've found when trying to set up a server stack using Rancher.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.5` Cattle: `v0.182.1` UI: `v1.6.9` |
|Access|`github` `admin`|
|Orchestration|`Cattle`|
|Route|`catalog-tab.launch`|

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
