### ISSUE TITLE
named volume with local driver won't scale

### ISSUE THREAD

**Issue by kgk** [rancher/rancher#9569]
**Rancher versions:**
rancher/server: 1.6.5
rancher/agent: 1.2.5

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler: v0.8.2
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
docker info
Containers: 16
 Running: 15
 Paused: 0
 Stopped: 1
Images: 15
Server Version: 1.12.6
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 119
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local rancher-nfs
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-57-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.795 GiB
Name: node1
ID: LOTK:QQZQ:KDDV:J4TS:3ZQ4:CAWX:HTZT:TINL:F4QJ:Z4CX:YWSU:CT3V
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Labels:
 provider=amazonec2
Insecure Registries:
 127.0.0.0/8

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

NAME="Ubuntu"
VERSION="16.04.1 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.1 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
cattle

**Steps to Reproduce:**
docker compose

version: '2'
volumes:
    test_data:
         driver: local 

services:
    image: ubuntu
    volumes:
        test_data: /data

rancher-compose up 
rancher-compose scale 2

**Results:**
 Degraded (Failed to allocate instance [container:1i172196]: Bad instance [container:1i172196] in state [error]: Allocation failed: Host must satisfy resource constraints: [valid host(s) [78], volume [177531] must have exactly these pool(s): [148])

I would have expected each container to get it's own local volume, instead I cannot scale past 1.

**Comment by LLParse** [comment]
@kgk There is a feature `per_container: true` that you can set on the volume definition. It will do what you want it to do.

```
volumes:
  test_data:
    driver: local
    per_container: true
```

**Comment by kgk** [comment]
Hm .. that flag is completely ignored for me using rancher 1.6.5 and rancher-compose 0.12.5
Still receiving a scheduling conflict. 

Is this something that will be supported in a future release?
I just searched for per_container and found https://github.com/rancher/rancher/issues/8683
so it appears there are some operational issues with it.  My use case is simpler though.

**Comment by LLParse** [comment]
It should work, however I've never tried using it in conjunction with `rancher-compose`. Perhaps using `rancher` CLI, the UI, or a catalog entry might yield better results?

Could you please share your compose files complete with indentation?

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
