### ISSUE TITLE
AD Auth: Users cannot login after setting up site access 

### ISSUE THREAD

**Issue by prachidamle** [rancher/rancher#9573]
**Rancher versions:**
rancher/server: latest v1.6 branch

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
1. Setup AD Access Control 
2. Logout and check that users can login fine
3. Login back as the Admin user, goto Admin -> Access Control
4. Enable Site access, Select (restricted or required mode), add users and Save.
5. Logout
6. Now no user can login. Admin cannot login too.

Screenshot of error during login:
<img width="933" alt="screen shot 2017-08-03 at 9 18 42 pm" src="https://user-images.githubusercontent.com/1470602/28954089-608087c2-7891-11e7-8ea5-497499d4fe7c.png">

**Comment by prachidamle** [comment]
This seems to be a regression after fixing the hiding of ServiceAccount Password bug.

**Comment by deniseschannon** [comment]
Available in v1.6.8-rc1

**Comment by sangeethah** [comment]
Tested with v1.6.8-rc1:

Setup AD Access Control
Logout and check that users can login fine
Login back as the Admin user, goto Admin -> Access Control
Enable Site access, Select (restricted or required mode), add users and Save.
Logout

In both restricted and required mode, admin user and all other users who have access to rancher-server are able to log in successfully.
