### ISSUE TITLE
Aliyunecs machine driver UI enhance

### ISSUE THREAD

**Issue by orangedeng** [rancher/rancher#9575]
**Rancher versions:**
rancher/server: 1.6.5
rancher/agent: 1.2.2

**Infrastructure Stack versions:**
healthcheck: n/a
ipsec: n/a
network-services: n/a
scheduler: n/a
kubernetes (if applicable): n/a

**Docker version: (`docker version`,`docker info` preferred)**
n/a
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
n/a
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
n/a
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
n/a
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
1. Activate Aliyunecs machine driver
2. Add host with Aliyunecs and Select 'Instance Storage I/O Optimized' to optimized.

**Results:**
Add host fail because wrong 'Instance Storage I/O Optimized' parameter is parsed to driver. This is a typo on https://github.com/rancher/ui/blob/master/app/components/machine/driver-aliyunecs/template.hbs#L108 . It should be `ioOptimized`.

**Comment by orangedeng** [comment]
@menglingwei @anzersy This is the issue of Aliyunecs machine ui. It is a bug and need to be fixed.

**Comment by anzersy** [comment]
This issue always come up with following err:

```
Aliyun API Error: RequestId: D61AA811-B694-48C4-8FFB-E0BD44F4FF4E Status Code: 404 Code: DependencyViolation.IoOptimized Message: The specified instancetype must be IoOptimized instance
```

Reference API link:
https://help.aliyun.com/document_detail/25499.html?spm=5176.doc25484.6.791.MGTuYX

Please pay attention to the IoOptimized parameter that you must provide the value(optimized) to ECS
API handler if you try to new instance of series II/III.

**Comment by Tracy1994** [comment]
rancher/ui test case:
total: 234 cases
pass: 28 cases
fail: 4 cases
skip: 202 cases
get more detail :https://github.com/Tracy1994/rancher-test_case
In all , even through the ecs.n4.large can be created, but these bugs still need to be fixed.
