### ISSUE TITLE
etcd disaster recovery fails on a 8 host setup because of network partitioning

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#9578]
**Rancher versions:**
rancher/server:Upgrade from v1.6.6 to v1.6.7-rc1

**Docker version: (`docker version`,`docker info` preferred)**1.12.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**Ubuntu

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**DO

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**Single node

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**Kubernetes

**Steps to Reproduce:**
1. Create a 8 host Kubernetes setup with etcd scale of 3 on v1.6.6
2. Create pods/rcs/services
3. Upgrade rancher to v1.6.7-rc1
4. Upgrade Network services, IPsec and Kubernetes stacks
5. Power down two hosts 
6. etcd cluster is unhealthy
7. Perform disaster recovery by issuing the command "disaster" on the etcd which is the sole survivor. This is the etcd which is in running state

**Results**:
After disaster recovery, kubectl does not list any of the resources. The data is lost.
Kubernetes dashboard fails to launch with the error "Service unavailable"

**Comment by leodotcloud** [comment]
Rootcause: https://github.com/rancher/rancher/issues/9418

**Comment by LLParse** [comment]
The disaster recovery process itself wasn't designed to withstand a permanent network partition. When this happens, metadata is unreachable and cattle deletes/creates the container once the healthcheck initializing timeout (2 minutes) is reached. At this point, the other (new) members contain the lowest create index and assume the leadership role. One of those new members bootstraps a fresh cluster only if the DR container hasn't completed its objective.

The result is either complete data loss, or a split brain scenario where 2 different clusters are competing within the same service. Both are very bad scenarios.

**Comment by deniseschannon** [comment]
Since the root cause is networking related  (#9418) and a fix has been put in place to address, can you please re-test to see if you hit this when testing #9418.

**Comment by soumyalj** [comment]
Tested using v1.6.7-rc7 with the latest fixes in rancher/net:v0.11.7. Disaster recovery cases succeeded and there was no data loss after recovery.
