### ISSUE TITLE
1-click HA-deployments for validation testing

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#9588]
Would make QA and dev's lives much easier if we could  have a 1-click or 1-script-run way of setting up an HA rancher environment running behind an ELB loadbalancer

**Comment by galal-hussein** [comment]
https://github.com/galal-hussein/rancher-ha-terraform

This Terraform script should set up a Rancher HA environment on AWS, the repo docs describe how to run the scripts directly and how can you configure it in jenkins as a pipeline job.

**Comment by galal-hussein** [comment]
The improvements added to the terraform script:

- The user doesn't have to enter the AMI for the os, however terraform will take care of that for you by using the `aws_ami` resource, all of you have to do is to write the OS name for example: `rhel-7.3`

- The user can choose now `aws_use_defaults` for the networking options and will not have to enter the aws vpc id or subnets ids/cidrs, terraform will use the default subnets and vpc automatically.

- The user now can change the docker version for the ROS systems, for example use docker 1.12 with ROS 1.0.4

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
