### ISSUE TITLE
Environment members are wrong if GitHub url is changed

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#959]
v0.22.0-rc1
Steps:
1.  Authenticate as regular GitHub user
2.  Create multiple Environments, giving random owner/member access to rancherdev & rancherdev2
3.  Disable Access Control
4.  Authenticate as Enterprise user

Results:
If you go to Manage Environments and check the Environments, you will see you are owner to them all, but if you click on drop-down there is only one.

Expected:
All Environments should show up in drop-down that you are owner to.

**Comment by vincent99** [comment]
@will-chan I think this should move to 1.0.  It's probably not a very common use case to switch GitHub URLs, and it's not very clear what we should do with old project member records if you do.

**Comment by tfiduccia** [comment]
Closing and added to #5450 for single point of reference
