### ISSUE TITLE
Internal and external DNS resolution stops working inside container until container is destroyed and recreated.

### ISSUE THREAD

**Issue by queer** [rancher/rancher#9598]
**Rancher versions:**
rancher/server: `stable` at the time of writing
rancher/agent: 1.2.5

**Infrastructure Stack versions:**
healthcheck: 0.3.1
ipsec: 0.11.3
network-services: 0.7.4
scheduler: 0.8.2
kubernetes (if applicable): N/A

**Docker version: (`docker version`,`docker info` preferred)**
```
Containers: 27
 Running: 27
 Paused: 0
 Stopped: 0
Images: 41
Server Version: 17.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local rancher-secrets
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.33-mod-std-ipv6-64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 31.37GiB
Name: amybot-node-01
ID: ORUP:ZXJH:YOM4:RQQA:YRHJ:BAZO:DQP4:VZCU:X5QD:5OPU:Y7J5:H5MG
Docker Root Dir: /home/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
`lsb_release -a`
```
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.1 (stretch)
Release:	9.1
Codename:	stretch
```

`uname -r`
```
4.9.33-mod-std-ipv6-64
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node Rancher, internal DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Note: The issue is unfortunately sporadic so I'm not 100% certain on how to reproduce. As far as I know, it goes roughly like:

1. Launch container
2. Restart container at a later date
3. Observe DNS not working until container is destroyed and recreated

**Results:**
Expected: DNS works fine
Actual: DNS to both internal Rancher services and external sites is non-functional (nothing can be resolved)

**Comment by superseb** [comment]
Did you confirm that network is working and only DNS is affected?

**Comment by queer** [comment]
Hey,

Sorry for the late response. After some attempts to reproduce, it seems that it's an issue with the application itself, not Rancher.
