### ISSUE TITLE
Temporarily disable rancher-cloud-controller-manager

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#9599]
When Rancher is deployed as an external cloud controller manager (CCM) along with kuberners controller manager (KCM), there were cases when the labels populated by CCM weren't set on the node. Those labels are:

* instancetype
* failure domain
* region

It was caused by CCM node initializing code not being called sometimes. As a result, in the same cluster there were hosts with failureDomain/region present, and some hosts where those parameters were missing. That in turn could cause k8s scheduler to prioritize hosts with no labels over the hosts with the labels, and some hosts never got pods deployed.

There might be more consequences of CCM init not being called, but scheduling was one that was caught. 

https://github.com/kubernetes/kubernetes/issues/50107

For rancher 1.6.x and k8s 1.7, we temporarily disable the CCM and go back to using forked version of k8s so the users don't get affected.

**Comment by galal-hussein** [comment]
Kubernetes on Rancher v1.6.8-rc3 installed without rancher-cloud-controller and i can see validation passing on this kubernetes release.
