### ISSUE TITLE
Rancher doesn't accept service with underscore in name 

### ISSUE THREAD

**Issue by redmed666** [rancher/rancher#9601]
**Rancher versions:**
rancher/server: 1.6.5

**Docker version: (`docker version`,`docker info` preferred)**
17.03.1-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
4.9.34-rancher

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
1 Rancher server with 3 rancher nodes

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Upload a docker-compose.yml with a service name like "db_test"

**Results:**
Error (Bad response statusCode [422]. Status [422 status code 422]. Body: [code=InvalidCharacters, fieldName=name, baseType=error] from [http://localhost:8080/v2-beta/projects/1a388/services])

**Comment by vincent99** [comment]
Service names are used for DNS records and must be named a valid DNS label.
