### ISSUE TITLE
Rancher caches container from Docker hub?

### ISSUE THREAD

**Issue by redmed666** [rancher/rancher#9602]
Hi Rancher team,

First thing, thank you for your hard work with Rancher, RancherOS and Cattle! These softs are simply amazing!

I would like to know if Rancher keeps somewhere a sort of a cache with the recent pulled containers from a registry for example? And if yes, is there a possibility to remove everything inside this cache manually?

This was my use case:
1) I did docker build -t $DOCKER_ID_USER/myapp:v1 .
2) I pushed that using docker push ...
3) Upload the docker-compose.yml to Rancher in order to create a new stack
4) Built again with docker build -t $DOCKER_ID_USER/myapp:v1 . (so same tag but I changed one line in package.json)
5) Reupload that to Rancher
6) Issue is still there, package.json was not updated even if locally , it is fine with a docker run.

That's why this made me think that Rancher keeps a cache with recently pulled images.

Thanks for your time.

Kind regards,

Mehdi

**Comment by aemneina** [comment]
@redmed666 I believe the problem is that youre using the same tag, so there are no changes detected to pull a new (updated in this case) image. Have you tried using 'always pull image' option when redeploying?

**Comment by redmed666** [comment]
@aemneina I saw this option when updating an image if I'm not mistaken but I haven't seen it when uploading a docker-compose file. But it should indeed solve this "issue"

**Comment by superseb** [comment]
This should help you out:

```

io.rancher.container.pull_image | always | Used to always pull a new image before deploying container.

```

http://rancher.com/docs/rancher/v1.6/en/cattle/labels/#rancher-compose-labels-for-services

Let me know if you need help on this.

**Comment by StevenWillett** [comment]
Similar scenario being experienced with Rancher v1.6.12

I create my docker image with a standard tag i.e. dockerHub/myImage**:staged**
(I will always be updating the **:staged** tag version of the image for our staging environment.)

Then I run this locally to test the image contains the the new changes, once confirmed all is fine, I then push the image to docker hub.

My docker hub is already added to Rancher as a registry and working.

Once my docker hub image with the tag :staged has been pushed and updated i then simply "upgrade" without making any changes to the settings, the stack to get the new image. 

Once the upgrade completes and I finalise the upgrade as well the image is not updated?

**Notes:**
-  Always pull image before creating = ticked
- Must delete container completely, then upgrade to make work.
- I have added the label "io.rancher.container.pull_image = always" to the stack in question

Any other ideas or pointers for what may be causing a caching like experience?
