### ISSUE TITLE
[RFE] throttle docker deletes when finishing upgrade of service

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#9603]
**Rancher versions:**
rancher/server: 1.6.5

The problem is that docker can go catatonic when bombarded with a large number of deletes. This feature request is to implement something like the batch upgrade pattern with deletes (when finishing an upgrade).

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
