### ISSUE TITLE
"ghost" stack appearing in the UI when starting a new stack

### ISSUE THREAD

**Issue by leucos** [rancher/rancher#9606]
When starting a stack ("main") in the Default environment (only this one is in use), another stack starts (let's call it "ghost") automatically, and disappear when "main" is destroyed.

Interestingly, this "ghost" stack is only visible when browsing "Stacks/All" in the UI, despite having the "User stack" icon (see capture).

![2017-08-06-17 14 54_region_886x255_scrot](https://user-images.githubusercontent.com/158845/29004636-3b4eebd8-7acb-11e7-9236-41f6f5f9fdd6.png)

I had previously had a stack by that name, but it has been destroyed some time ago. However, services in the "main" stack are mostly the same as they were in stack "ghost".

In the "ghost" stack, only one service is present with not containers:

![2017-08-06-17 22 57_region_375x180_scrot](https://user-images.githubusercontent.com/158845/29004690-0d1c0d3a-7acc-11e7-8953-844a5e977add.png)

The "main" stack is started using `rancher up -s main` and "ghost" is not mentioned anywhere in `docker-composer.yml` or `rancher-compose.yml`.

If I stop "main", "ghost" stays up. If I delete "ghost" and restart "main", "ghost" comes back.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.6` Cattle: `v0.183.5` UI: `v1.6.17` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`stacks.index`|

Note:
- I work in HA (with a MariaDB 10.1 galera cluster).
- stack names have been obfuscated to protect the innocent

**Comment by aemneina** [comment]
Do you have some sanitized docker/rancher compose that reproduces this?

**Comment by leucos** [comment]
Unfortunately no :( 
The ghost name in the stack (`loneservice` here) isn't even mentionned in the docker/rancher compose files/.
However, they relate to and old stack name; I suspect this is coming back from the cattle database to haunt us. But I have no clue on how to get rid of it besides a massive grep against a mysql dump.

**Comment by leucos** [comment]
Well, I started from scratch, dropped cattle DB, and it's coming back to haunt me in the new rancher setup.
This stack only appears in Stacks/All, but not in Stacks/User or Stacks/Infrastructure.

The only service in the ghost (keycloak) has the same name as another service in the application stack.

If I stop destroy the ghost stack, keycloak in the application stack turns unhealthy and show 0 containers. I have to upgrade application stack keycloak to make it working again. But this brings back the keycloack in the ghost stack.

Any clue appreciated !

**Comment by leucos** [comment]
After reinstalling from scratch (including OSes), still had the issue. 
After that we rebuilt new versions of sone container (kc) in the stack and the issue when away.

Still, I don't know how some container image ended up creating a new stack in Rancher (which was, in fact, a composeStack in the API).

Closing this since the issue is gone. Thanks.
