### ISSUE TITLE
containers that are stopped during upgrade are restarted by crontab

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#9609]
**Rancher versions:**
rancher/server: 1.6.4

Steps to reproduce:
1. have crontab service deployed
2. upgrade stack
3. if the upgraded stack doesnt get finished before crontab runs, stopped containers get started

**Comment by cloudnautique** [comment]
This is a duplicate of #8757.

The behavior is known. The crontab service has no awareness of Rancher services.

**Comment by deniseschannon** [comment]
@galal-hussein Can we just verify that the latest crontab fixes this specific use case?

**Comment by galal-hussein** [comment]
Rancher server: v1.6.11-rc4

I was able to verify that in the new crontab catalog that run in --rancher-mode the old stopped containers in upgraded stack will still be in stopped state even after the crontab run executes.
