### ISSUE TITLE
Memory leak in crontab service

### ISSUE THREAD

**Issue by raphink** [rancher/rancher#9610]
**Rancher versions:**
rancher/server: 1.6.4
rancher/agent: 1.2.5

**Infrastructure Stack versions:**
healthcheck: 0.3.0
ipsec: 0.1.0
network-services: 0.2.1
scheduler: 0.6.0

**Docker version: (`docker version`,`docker info` preferred)**

```
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:38:45 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:38:45 2017
 OS/Arch:      linux/amd64
```

```
Containers: 31
 Running: 21
 Paused: 0
 Stopped: 10
Images: 29
Server Version: 1.12.6
Storage Driver: overlay2
 Backing Filesystem: extfs
Logging Driver: journald
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-1026-aws
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.795 GiB
Name: ip-10-200-1-50
ID: 2ZVE:43TC:OQRG:ZSIR:QZNQ:UOJE:WOJN:37EQ:5PRJ:BAMC:DW7T:ZV2P
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

```
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

```
4.4.0-1026-aws
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

single node, external DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

Cattle

**Steps to Reproduce:**

Start a container with a `cron.schedule = 0 * * * * *` label

**Results:**

Memory for crontab containers goes up, reaching 500+MB after a week.

![screenshot from 2017-08-07 14-27-02](https://user-images.githubusercontent.com/650430/29026529-8470af66-7b7c-11e7-9766-6776b9d8d3de.png)

![screenshot from 2017-08-07 14-27-22](https://user-images.githubusercontent.com/650430/29026541-918eb4ae-7b7c-11e7-9807-4418b87e3353.png)

**Comment by cloudnautique** [comment]
I wonder if this is caused by the robfig/cron library not allowing the removal of jobs from the crontab. Does your environment have a lot of updates to cron?

**Comment by cloudnautique** [comment]
Cool, there is a v2 API of the cron lib. I'll start updating there.

**Comment by raphink** [comment]
The cron tasks don't really change, but they run often. For now, my workaround has been to schedule them `@every 5 minutes` so the oom is reached after one month instead of a week...

**Comment by cloudnautique** [comment]
I think I found the issue, we were leaking go routines and file descriptors. In my testing it seems to have leveled off, and certainly not growing at the same rate. 

PR rancher/container-crontab#5 has the fixes. Will come out as part of the catalog.

**Comment by raphink** [comment]
Great.

**Comment by galal-hussein** [comment]
Rancher Server: v1.6-development

Tested the new catalog of crontab, the memory usage didn't increase for the crontab containers and the service works fine for both normal and Rancher mode.
