### ISSUE TITLE
Host went to disconnected state as docker daemon stopped running

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#9612]
**Rancher versions:**
rancher/server:v1.6.7-rc1
rancher/agent:rancher/agent:v1.2.5

kubernetes (if applicable):1.7.2-rancher7

**Docker version: (`docker version`,`docker info` preferred)**1.12.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**Ubuntu

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**DO

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**Single node

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**Kubernetes

**Steps to Reproduce:**
1. Create a 3 node Kubernetes setup 
2. Add two hosts
3. Infra containers and user pods came up correctly on these hosts

After a few minutes, on one of the hosts, docker daemon stopped running and host went to disconnected state
```
root@soumya167kubetest5:~# service docker status
● docker.service
   Loaded: loaded (/etc/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2017-08-07 18:14:02 UTC; 6min ago
  Process: 1322 ExecStart=/usr/bin/dockerd -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --storage-driver aufs --tlsverify --tlscacert /etc/docker/ca.pem --tlscert /etc/docker/server.pem --tlskey /etc/doc
 Main PID: 1322 (code=exited, status=1/FAILURE)

Aug 07 18:14:01 soumya167kubetest5 systemd[1]: Started docker.service.
Aug 07 18:14:01 soumya167kubetest5 dockerd[1322]: time="2017-08-07T18:14:01.461331411Z" level=info msg="libcontainerd: new containerd process, pid: 1431"
Aug 07 18:14:02 soumya167kubetest5 dockerd[1322]: time="2017-08-07T18:14:02.752771515Z" level=fatal msg="Error starting daemon: layer does not exist"
Aug 07 18:14:02 soumya167kubetest5 systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Aug 07 18:14:02 soumya167kubetest5 systemd[1]: docker.service: Unit entered failed state.
Aug 07 18:14:02 soumya167kubetest5 systemd[1]: docker.service: Failed with result 'exit-code'.


```

**Comment by cjellick** [comment]
This is not related to the other agent disconnect bugs (#9388 #8522) we are seeing.
