### ISSUE TITLE
Redirect haproxy logs to stdout

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#9616]
When haproxy logging is enabled via LB custom config, everything gets logged to a file. We need to redirect it to stdout/stderr as well.

**Comment by alena1108** [comment]
Can be tested with haproxy v0.7.9

**Comment by sangeethah** [comment]
@alena1108 @kinarashah can you include some details on what we expect to see in stdout/stderr ?
With ```defaults log 127.0.0.1:8514 local0 debug``` set , I still dont see any logging in stdout/stderr when LB is used to direct traffic to targets it services.

**Comment by sangeethah** [comment]
I had to use a new line character after defaults for the haproxy config to take effect.

With this settings , we are able to see the traffic being shown in "Combined" and "Standard Out" tabs when using "View logs" option from rancher UI. 
```
defaults 
log 127.0.0.1:8514 local0 debug
```

**Comment by meggarr** [comment]
Hi, I am using Rancher `v1.6.7`, so is this available in `lb-service-haproxy:v0.7.6` ? And which Rancher version has the `v0.7.9`. Thanks!

**Comment by superseb** [comment]
`v0.7.9` is used in Rancher `v1.6.8-v1.6.9-v1.6.10`

**Comment by Caspain** [comment]
This is resolved in rancher v1.6.17 with haproxy v.0.9.1
