### ISSUE TITLE
Rancher / Request Catalog for Nimble Storage

### ISSUE THREAD

**Issue by narayaar** [rancher/rancher#9622]
**Rancher versions:**
rancher/server:  1.5.5
rancher/agent:  1.2.2

**Infrastructure Stack versions:**
healthcheck:  0.2.3
ipsec:  0.11.2
network-services:  0.7.4  
scheduler: 0.7.5
kubernetes (if applicable):  N/A.  We're using Cattle.

**Docker version: (`docker version`,`docker info` preferred)**
Server Version: 17.03.1-ce
Kernel Version: 4.9.34-rancher
Operating System: RancherOS v1.0.3

Server Version: 17.03.1-ce
Kernel Version: 4.9.24-rancher
Operating System: RancherOS v1.0.1

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VMWare vSphere 5.5/6.0

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA Rancher / External DB (MySQL)

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
N/A

**Results:**
N/A

At my organization, to float containerized apps, we've been using RancherOS (HA) for a year now, with the orchestration being managed through Cattle.  Being long-time users (yes, a year constitutes a long time nowadays), we're fans of the whole Rancher ecosystem, and love the way you guys have brought it all together.

We've recently procured SDS from Nimble, who do have a published volume plugin for Docker.  Really wanting to see how things work and take our apps to the next level, we were sad when we realized that Rancher did not have a catalog for Nimble, and while there are some workarounds that we can apply, we really want(ed) to go via the easy/lazy route of having Rancher do everything for us (as always).

https://store.docker.com/plugins/nimble

Therefore, we were wondering (and also requesting very nicely ;)) when a catalog for Nimble would be made available.  We understand you guys are super-busy focusing on the 2.0 release, but considering we are also evaluating tying up with Rancher for paid support, this would go a long way in terms of building that support.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
