### ISSUE TITLE
meatadata - rancher-dns : level=fatal msg="Failed to subscribeGet v2-beta: unsupported protocol scheme \"\"" 

### ISSUE THREAD

**Issue by paradxum** [rancher/rancher#9627]
**Rancher versions:**
rancher/server: stable
rancher/agent: v1.2.5

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-manager: 0.7.4
metadata: 0.9.2
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
Containers: 7
 Running: 4
 Paused: 0
 Stopped: 3
Images: 10
Server Version: 17.03.1-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.34-rancher
Operating System: RancherOS v1.0.3
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.861 GiB
Name: rancher
ID: CMZF:66QQ:4GEM:2DCN:6QBL:WX64:OSR6:5CEU:UKQX:Q5JD:UUQL:XE3U
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="RancherOS"
VERSION=v1.0.3
ID=rancheros
ID_LIKE=
VERSION_ID=v1.0.3
PRETTY_NAME="RancherOS v1.0.3"
HOME_URL="http://rancher.com/rancher-os/"
SUPPORT_URL="https://forums.rancher.com/c/rancher-os"
BUG_REPORT_URL="https://github.com/rancher/os/issues"
BUILD_ID=

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
vmware

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancheros, rancher-server, rancher-agent

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Install rancheros, enable rancher-server-stable, install agent and join

**Results:**
All infrastructure services fail due to dns being down.

docker run  rancher/metadata:v0.9.2 /rancher-entrypoint.sh start.sh rancher-metadata -subscribe
time="2017-08-08T20:53:38Z" level=info msg="Subscribing to events" 
time="2017-08-08T20:53:38Z" level=fatal msg="Failed to subscribeGet v2-beta: unsupported protocol scheme \"\""

**Comment by paradxum** [comment]
seems error was elsewhere

**Comment by wcgcoder** [comment]
I've been experiencing this issue randomly today. I'm curious what troubleshooting steps you took to troubleshoot. I only experience on some machines; strangely enough the machines that don't have the problem have the same configuration within the same environment. 

Rancher v1.6.8
Agent v1.2.6
Env Cattle
Docker 17.06.2-ce

**Comment by YeonSeoMom** [comment]
I have the same issue. Help plz.
Rancher v1.6.17
agent v1.2.10
Env cattle
Docker 1.12.6
