### ISSUE TITLE
ipsec tunnel broken between 2 hosts.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#9628]
Rancher versions: v1.5.7 upgraded to v1.6.7-rc1

Fresh install of rancher-server v1.5.7 have kubernetes evironment in isolated planes with:

3 compute nodes
6 etcd nodes
2 orchestartion nodes

Have few pods and ingress deployed in K8s environment.
Even when in v1.5.7 , network connectivity between 2 of the hosts was broken. Not able to ping between ipsec containers of these hosts.

Upgrade rancher server to rancher-server v1.6.7-rc1

Upgrade all infra stacks , network-services , ipsec , scheduler and healthcheck.
Upgrade Kubernets stack.

Infra images:
rancher/net:v0.11.7
rancher/network-manager:v0.7.7
rancher/metadata:v0.9.3

Network connectivity between 2 of the hosts continue to broken. Not able to ping between ipsec containers of these hosts.

**Comment by pilsy** [comment]
Wondering if this is related to #9123 ?
