### ISSUE TITLE
How to refresh / resync the names of host managed running containers?

### ISSUE THREAD

**Issue by Dark-o** [rancher/rancher#9630]
If I run a docker container on a registered host, in rancher I can see the name of the running container.

If I run a docker container and, in rapid sequence, I run <docker container rename $CURRENT_NAME $NEW_NAME>, in rancher I can see the new name of the container.

If I run a docker container then I wait 20 secs, when I run <docker container rename $CURRENT_NAME $NEW_NAME>, in rancher remain the old name of the container.

I cannot find a way to refresh the names of the running containers on a rancher managed host. It's seems that rancher acquire the container name only when a container start/restart (if I restart the container fron rancher console the name become the correct new one) or if deregister the host and I federate again (very slow) the correct name will be shown.

I'm trying to have a continuous deploy Green/Blue procedure that runs a new container named Service_green, then wait 20 seconds to verify that the container is up and running, rename the old one in  Service_blue and finally Service_green in Service. Then remove Service_blue.

If I remove the safety 20 secs pause in rancher I have the correct name, but with the pause at the end of the procedure in rancher remains Service_green. 

If on the host I exec a docker ps I can see the correct name "Service"

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.5` Cattle: `v0.182.1` UI: `v1.6.9` |
|Access|`Disabled`|
|Orchestration|`Cattle`|
|Route|`hosts.index`|

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
