### ISSUE TITLE
Certs error when creating host in AWS EC2

### ISSUE THREAD

**Issue by galioy** [rancher/rancher#9631]
**Rancher versions:**
v1.6.4

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS eu-west-2 (London)
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
Tried creating a host in AWS EC2, in `rancher-machine` and `default` sec groups, with all the default settings:
Instance type: `t2.micro`
Root size: `16 GB`
AMI: <none>
SSH User: `ubuntu`
AMI Profile: <none>

**Results:**
```
Error checking the host: Error checking and/or regenerating the certs: There was an error validating certificates for host "SOME_IP:2376": dial tcp SOME_IP:2376: i/o timeout
```

The last running step before the error is "Checking connection to Docker..."

These are the last lines from the instance logs:
```
> [34mINFO[0m[0018] [15/16] [docker]: Started                    
> [34mINFO[0m[0018] [16/16] [preload-user-images]: Started       
> [34mINFO[0m[0018] Project [os]: Project started                
> [34mINFO[0m[0018] [3/4] Starting sync                          
> [34mINFO[0m[0018] [4/4] Starting banner                        
> [34mINFO[0m[0018] RancherOS v1.0.3 started
// and the rancher logo printed
```

**Comment by aemneina** [comment]
not entirely sure where the issue is here... do you really use ssh user: `ubuntu` for a rancherOS host? The user should be `rancher`.

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
