### ISSUE TITLE
Can't see the Container Environment variables set, on Rancher UI

### ISSUE THREAD

**Issue by borntorock** [rancher/rancher#9632]
We're using Rancher v1.6.0, Cattle framework. 

Via User with readonly permission, the user can't see the environment variables set inside the docker container. It's getting displayed as None. 

Needless to say, environment variables are visible from member and admin role permissions. 

Would be great, if you could remove the restriction of viewing the environment variables from readonly role / permission.

**Comment by borntorock** [comment]
Any update on this issue?

**Comment by vincent99** [comment]
This is intentional because they often contain passwords (despite being poorly-advised) and will not be changing in 1.x.  In 2.0 it will likely be a capability to can toggle on a role.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
