### ISSUE TITLE
kmsKeyId parameter should be optional when specifying rancher-ebs volume

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#9633]
**Rancher versions:**
rancher/server: v1.6.7

**Infrastructure Stack versions:**
rancher-ebs: v0.3.0

**Steps to Reproduce:**
When specifying an encrypted EBS volume, you have to specify kmsKeyId. According to the AWS CLI docs, when --kms-key-id is not specified it defaults to the default CMK for EBS (which is created automatically).

References:
http://docs.aws.amazon.com/cli/latest/reference/ec2/create-volume.html
https://github.com/rancher/storage/blob/master/package/ebs/rancher-ebs#L144

**Comment by deniseschannon** [comment]
Available with `storage-ebs:v0.8.8`, in EBS template: `v0.4.0`

**Comment by moelsayed** [comment]
Tested and confirmed working. Validation tests passed.
