### ISSUE TITLE
Issue with Catalog templates starting with the same semver version

### ISSUE THREAD

**Issue by amy** [rancher/rancher#9639]
Example: 
Given two templates with the same semver version...
```
// Template 1
version: v1.7.2-rancher8-blah
upgradeFrom: 0.0.0
```
```
// Template 2
version: v1.7.2-rancher8
upgrade_from: <v1.7.2-rancher8
```
When launching Template 1, you will see Template 2 in the upgrade links. This should not happen.
Hypothesis is the way semver evaluates which versions are less than each other after the formatted version.

**Comment by deniseschannon** [comment]
This was due to the fact that `v1.7.2-rancher8-blah` is considered a earlier version of `v1.7.2-rancher8` as we sort anything after the `v1.7.2` alphabetically.
