### ISSUE TITLE
Excessive CPU usage

### ISSUE THREAD

**Issue by AliYmn** [rancher/rancher#9640]
Hi, https://i.hizliresim.com/XX1mA6.png (img link)

<img src="https://i.hizliresim.com/XX1mA6.png"/>

Why does the Agent application use so many CPUs?

**Comment by StrongMonkey** [comment]
Hi, which rancher version and agent version you are running? can you provide more detail information?

**Comment by AliYmn** [comment]
* Ubuntu 16.04
* Docker version 17.06.0-ce, build 02c1d87
* mysql  Ver 14.14 Distrib 5.7.19, for Linux (x86_64) using  EditLine wrapper
* rancher : lastest

Where can I learn the rancher version?

**Comment by StrongMonkey** [comment]
In UI on the bottom left there should be a button to show the rancher version. Also any logs from agent would be appreciated.

**Comment by AliYaman** [comment]
Rancher version =  v1.6.7

<img src="https://i.hizliresim.com/jWbqym.png" />

The system has 8 gb ram. The use of such a CPU is very strange because it is not installed on any service or container.

**Comment by superseb** [comment]
Can you add logs from the agent, and where are you running this machine on? (Provider + instance type?)

**Comment by AliYaman** [comment]
IP : http://185.198.72.227 He's working on this rope.
How do I add a day?

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
