### ISSUE TITLE
How do I get the public/private IP of the agent host?

### ISSUE THREAD

**Issue by MadMichael888** [rancher/rancher#9644]
Hi,

I'm trying to run redis container on every host in the cluster, and my services would like to connect to the redis container that's running on the same host. So my idea is to get the public/private IP of the host and use the IP to connect to the redis container. The problem is that I don't see a way to get this dynamically when the service is scaling up. Any suggestion is appreciated.

Thanks,
Mike

**Rancher versions:**
rancher/server: 1.6
rancher/agent: 1.6

**Infrastructure Stack versions:**
healthcheck: 0.3.1
ipsec: 0.11.2
network-services: 0.7.0
scheduler: 0.7.5
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
ubuntu 16.04 LTS

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
internal DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**

**Results:**

**Comment by vincent99** [comment]
You can get it from [metadata](http://rancher.com/docs/rancher/v1.6/en/rancher-services/metadata-service/), `/self/host/agent_ip`.

**Comment by MadMichael888** [comment]
Perfect! Thanks a lot.
