### ISSUE TITLE
Scheduler healthcheck cause panic

### ISSUE THREAD

**Issue by leibowitz** [rancher/rancher#9654]
**Rancher versions:**
rancher/server: stable
rancher/agent: v1.2.5
Rancher 1.6.5
RancherOS v1.0.3 (4.9.34)

**Infrastructure Stack versions:**
healthcheck: v0.3.1
ipsec: rancher/net:holder rancher/net:v0.11.3 (not sure?)
network-services: rancher/network-manager:v0.7.4 rancher/metadata:v0.9.2
scheduler: v0.8.2

**Docker version: (`docker version`,`docker info` preferred)**
Docker version 17.03.1-ce, build c6d412e
```
Containers: 10
 Running: 9
 Paused: 0
 Stopped: 1
Images: 9
Server Version: 17.03.1-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.34-rancher
Operating System: RancherOS v1.0.3
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.953 GiB
Name: ip-192-168-199-188.ec2.internal
ID: XHII:2G27:JPUI:76XZ:MWPL:MNVM:5QLR:QDUV:OIM3:BFUH:KIWX:TBK6
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
4.9.34-rancher
```
NAME="RancherOS"
VERSION=v1.0.3
ID=rancheros
ID_LIKE=
VERSION_ID=v1.0.3
PRETTY_NAME="RancherOS v1.0.3"
HOME_URL="http://rancher.com/rancher-os/"
SUPPORT_URL="https://forums.rancher.com/c/rancher-os"
BUG_REPORT_URL="https://github.com/rancher/os/issues"
BUILD_ID=
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher, external DB (AWS RDS MySQL)

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Create an environment, add a host, and check the scheduler logs. Once every ~30s the panic will be shown in the logs

**Results:**
```
http: panic serving 10.42.225.160:33078: runtime error: invalid memory address or nil pointer dereference
goroutine 1078 [running]:
net/http.(*conn).serve.func1(0xc42028eaa0)
	/usr/local/go/src/net/http/server.go:1721 +0xd0
panic(0x8e0f00, 0xd97b70)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
main.startHealthCheck.func1(0xda9620, 0xc4201f49a0, 0xc4203fce00)
	/go/src/github.com/rancher/scheduler/main.go:136 +0xd7
net/http.HandlerFunc.ServeHTTP(0xc420145a60, 0xda9620, 0xc4201f49a0, 0xc4203fce00)
	/usr/local/go/src/net/http/server.go:1942 +0x44
net/http.(*ServeMux).ServeHTTP(0xdd2320, 0xda9620, 0xc4201f49a0, 0xc4203fce00)
	/usr/local/go/src/net/http/server.go:2238 +0x130
net/http.serverHandler.ServeHTTP(0xc420363b80, 0xda9620, 0xc4201f49a0, 0xc4203fce00)
	/usr/local/go/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc42028eaa0, 0xda9ee0, 0xc4202fad40)
	/usr/local/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2668 +0x2ce
```

**Comment by leibowitz** [comment]
I am still wondering what is causing this. I was getting this while trying to setup a rancher-nfs stack using terraform 0.9.11
https://github.com/terraform-providers/terraform-provider-rancher/issues/28

Now that I've updated to 0.10.0, I cannot reproduce the problem. I guess it should never panic, but not sure what is causing that. 

Anyway if the code hasn't changed, it should be pretty trivial to fix the panic:
```go
		cattleURL := os.Getenv("CATTLE_URL")
		resp, err := http.Get(cattleURL[:len(cattleURL)-2] + "ping")
		if err != nil {
			healthy = false
		}
		defer resp.Body.Close()
```
From https://github.com/rancher/scheduler/blob/9e55a8960719c8da76263ed38c1bfdc2c3fbc145/main.go#L132-L136

Should probably be updated to something like that:
```go
		cattleURL := os.Getenv("CATTLE_URL")
		resp, err := http.Get(cattleURL[:len(cattleURL)-2] + "ping")
		if err != nil {
			healthy = false
		}
		if resp != nil {
			defer resp.Body.Close()
		}
```

> When err is nil, resp always contains a non-nil resp.Body. Caller should close resp.Body when done reading from it.
Source: https://golang.org/pkg/net/http/#Client.Get

**Comment by fbrenciu** [comment]
Any progress on this I've encountered the same issue with scheduler.

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
