### ISSUE TITLE
Disaster recovery fails with etcd v3

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#9655]
**Rancher versions:**
rancher/server:v1.6.8-rc1
rancher/agent:

**Infrastructure Stack versions:**
kubernetes (if applicable):1.7.2-rancher8-etcdv3
rancher/etcd:v3.0.17

**Docker version: (`docker version`,`docker info` preferred)**1.12.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**Ubuntu

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**DO

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**Single node

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**Kubernetes

**Steps to Reproduce:**
1. Create a 3 node Kubernetes setup and create some pods/rcs/ingress
2. Power OFF two hosts which results in a disaster recovery scenario
3. Perform Disaster recovery.

Results

Disaster recovery fails and there is no healthy etcd cluster formed. The running etcd container on which the DR was performed also errored out.
<img width="1292" alt="screen shot 2017-08-10 at 1 37 15 pm" src="https://user-images.githubusercontent.com/18536626/29191144-96196eae-7dd1-11e7-8cf6-6e035555b0ba.png">

```
bash-4.3# etcdctl cluster-health
cluster may be unhealthy: failed to list members
Error:  client: etcd cluster is unavailable or misconfigured
error #0: dial tcp 127.0.0.1:2379: getsockopt: connection refused
error #1: dial tcp 127.0.0.1:4001: getsockopt: connection refused



```

etcd logs
```
8/10/2017 1:39:58 PM2017-08-10 20:39:58.045318 I | membership: added member c161b229d9ec24e8 [http://10.42.252.67:2380] to cluster 5dcde0088b02 from store
8/10/2017 1:39:58 PM2017-08-10 20:39:58.045352 I | membership: added member dc4085a3bd6ef2c8 [http://10.42.80.54:2380] to cluster 5dcde0088b02 from store
8/10/2017 1:39:58 PM2017-08-10 20:39:58.045383 I | membership: added member 288fb1180572ae34 [http://10.42.48.20:2380] to cluster 5dcde0088b02 from store
8/10/2017 1:39:58 PM2017-08-10 20:39:58.045420 I | membership: set the cluster version to 3.0 from store
8/10/2017 1:39:58 PM2017-08-10 20:39:58.049376 I | etcdmain: stopping listening for client requests on localhost:2379
8/10/2017 1:39:58 PM2017-08-10 20:39:58.049539 I | etcdmain: stopping listening for peers on http://localhost:2380
8/10/2017 1:39:58 PM2017-08-10 20:39:58.049621 C | etcdmain: database file (/pdata/data.20170810.203957.DR/member/snap/db) of the backend is missing
8/10/2017 1:39:58 PMGet http://127.0.0.1:2379/health: dial tcp 127.0.0.1:2379: getsockopt: connection refused
8/10/2017 1:40:00 PMGet http://127.0.0.1:2379/health: dial tcp 127.0.0.1:2379: getsockopt: connection refused
```

**Comment by soumyalj** [comment]
Tested on master with Kubernetes 1.7.4-rancher2-etcdv3 on a 3 node setup. Disaster recovery succeeds. etcd cluster is healthy and creation of new pods and ingress is successful in the setup. 
```
bash-4.3# etcdctl cluster-health
member 2ab0d867a6aadf0b is healthy: got healthy result from http://10.42.105.166
:2379
member e7e0ca9ba4827bc6 is healthy: got healthy result from http://10.42.209.164
:2379
member fa6685fa31863613 is healthy: got healthy result from http://10.42.37.199:
2379
cluster is healthy
bash-4.3#


```

**Comment by verenion** [comment]
I'm seeing a similar thing happening in v1.6.14. Just this error repeatedly in the new etcd nodes after running disaster recovery.

```08/03/2018 17:32:15Get http://10.42.5.46:2379/health: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
08/03/2018 17:32:23Get http://10.42.5.46:2379/health: dial tcp 10.42.5.46:2379: getsockopt: no route to host```
