### ISSUE TITLE
Audit Log, when I click on Time sort order, I lose the ability to see the most current events

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#9656]
**Rancher versions:** master 2.0 8/10

**Steps to Reproduce:**
1.  Go to Audit Log
2.  Click on Time, click on it again

**Results:**  It only returns events that are "a day ago", all the most current fired events are lost

**Comment by loganhz** [comment]
hi @tfiduccia , I can not reproduce this issue against `master` and `v2.0.0-alpha9`.  I can see the current events when I click on Time and click it again.

**Comment by tfiduccia** [comment]
@loganhz - I have demonstrated this to Vincent, it still exist and he know why.  Please touch base with him.

**Comment by vincent99** [comment]
You have to have a longer history/more events to see.  The problem is the initial set of events is sorted server-side, but clicking on the headers after that is doing client-side sorting of only the data that was already loaded instead of going back to the server to get more.

**Comment by tfiduccia** [comment]
Version - 2.0 master 10/16
Verified fixed
