### ISSUE TITLE
Network bandwith (transfer/receive) over-reported?

### ISSUE THREAD

**Issue by PicoCreator** [rancher/rancher#9659]
**Rancher versions:**
rancher/server: v1.5.9
rancher/agent: v1.2.2

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
host : AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
SSH into the respective host, and use bmon to monitor the network, compare with host network reporting on rancher

**Results:**
![screen shot 2017-08-11 at 2 32 20 pm](https://user-images.githubusercontent.com/17175484/29203358-e5f2f4e6-7ea2-11e7-92d6-d027db81d5a4.png)

Instance have 1 network adapter for ingress/outgress traffic. Rancher over-reports the total traffic (5.5 times in this case, after taking into account bits / bytes differences) of the instance. The assumption here is that perhaps Network usage in rancher now uses the total of all virtual and physical interfaces? Hence the potential for double or more counting, when including internal traffic.

Perhaps either relabel the "Network" to "internal+external network", to make clearer the number representation. Or filter for "external network" only. Or show both as different lines.

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
