### ISSUE TITLE
[LB] Idea : host redirect rule

### ISSUE THREAD

**Issue by Dremor** [rancher/rancher#9662]
Hi.

Would it be possible to make available redirect rules for the load balancer, that redirect request to another host port, protocol, etc?

This would for example allow to redirect http to https, or redirect to a new web address.

Best regards

**Comment by jmaasing** [comment]
For http -> https redirects there is a way https://github.com/rancher/rancher/issues/3505
But it would be nice to be able to add/change the rules generated by the GUI in some way.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
