### ISSUE TITLE
CLI silently ignores invalid answers file format

### ISSUE THREAD

**Issue by wjimenez5271** [rancher/rancher#9665]
If you supply the CLI with an answers file for deploying a catalog item that doesn't have the correct format, it will silently ignore the values. An exception here will improve the user experience so they know they are not supplying the values properly. 

I also updated the docs to explain the desired format (`key`=`value`\n)

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
