### ISSUE TITLE
Delay in responding to pings on upgraded instance of containers that were launched with retain_ip enabled.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#9666]
Rancher version - rancher-server v1.6.7-rc1

Steps to Reproduce the problem:
Create a cattle environment with 3 hosts
Create a service of scale=2 that specifies retain_ip: true
Deactivate the host where an instance of the service is running.
Upgrade service.
This results in the newer instance of the service to be launched in a different host.
When service is still in upgraded state , this newer instance of the service that was launched in a different host is able to communicate with other instances of the service.

There is a 10-15 sec delay for the ping (of ipaddress of other containers in the service) to respond . After this the response is prompt.

**Comment by LLParse** [comment]
FWIW, I was recently testing out Swarm's overlay networking for Windows and it is similarly afflicted...the first ICMP request frequently fails on a freshly started container. This seems to be a common issue.
