### ISSUE TITLE
Save/Cancel returning to different page from Host Registration page

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#967]
v0.22.0-rc2
Steps:
1.  From the settings menu go to Host Registration
2.  Click on Save or Cancel

Results:
Returns me to the previous page I was on, this makes sense when you take me there.  But doesn't make any sense when I go to page from settings.

Expected:
Should stay on page, with saved or cancelled setting.  The only time it should move me off of page is when you take me there automatically from Add Host.

**Comment by vincent99** [comment]
There is no cancel button anymore, there us only zuul.
