### ISSUE TITLE
Unable to use HAProxy as a root process

### ISSUE THREAD

**Issue by PhilippeVienne** [rancher/rancher#9673]
**Rancher versions:**
rancher/server: 1.6.6
rancher/agent: 1.2.5

**Infrastructure Stack versions:**
healthcheck: 0.3.1
ipsec: 0.11.7
network-services: 0.7.7
scheduler: 0.9.3

**Docker version: (`docker version`,`docker info` preferred)**
16.06.0-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04 LTS

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
OVH Public Cloud (OpenStack)

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node Rancher with Internal DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Create a LB with the custom HAProxy config:
```
global
user root
group root
```
**Results:**
HAProxy does not consider it self as a root owned process

**Comment by PhilippeGeek** [comment]
I think problem comes from config overwriting, and suggest a Pull Request:
https://github.com/rancher/lb-controller/pull/90

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
