### ISSUE TITLE
Certification for RHEL 7.4

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#9674]
Validate the following configuration using  RHEL 7.4 hosts using rancher/server:v1.6.8-rc1

1. Cattle environment with  RHEL 7.4 hosts having docker upstream 17.06
2. Cattle environment with  RHEL 7.4 hosts having native docker 
3. Kubernetes environment with  RHEL 7.4 hosts having native docker 
4. Kubernetes environment with  RHEL 7.4 hosts having  upstream docker 1.12

**Comment by moelsayed** [comment]
Cattle environment with RHEL 7.4 hosts having native docker: #9676 
Kubernetes environment with RHEL 7.4 hosts having native docker: #9676
