### ISSUE TITLE
AD auth: Error not thrown when Service Account Password is empty, while re-enabling auth after disabling it

### ISSUE THREAD

**Issue by prachidamle** [rancher/rancher#9675]
**Steps to Reproduce:**
1. Enable AD Auth
2. Disable Access Control
3. Enable AD again now but with Service Account Password as empty.
4. No error is thrown

Expected:
Error should be thrown indicating that the Service Account Password is empty.

**Comment by sangeethah** [comment]
Tested with  rancher server version - v1.6.8-rc3

Enable AD Auth
Disable Access Control
Enable AD again now but with Service Account Password as empty.
User is presented with error message - "Failed to login, service account password not provided"
No error is thrown
