### ISSUE TITLE
Kubernetes UI shell ask for credentials after upgrade from v1.6.6 to v1.6.7

### ISSUE THREAD

**Issue by hiscal2015** [rancher/rancher#9679]
**Rancher versions:** v1.6.7
 
**Docker version: (`docker version`,`docker info` preferred)** 1.12.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)** Ubuntu 16.04

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** Bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)** Single

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)** Kubernetes

Upgrade from rancher v1.6.6 to v1.6.7, upgrade Kubernetes from rancher/k8s:v1.7.2-rancher5 to rancher/k8s:v1.7.2-rancher7,

Login to UI > Kubernetes > CLI

![shell](https://user-images.githubusercontent.com/15604715/29300500-5fe1d6d4-81a8-11e7-8f23-d86267de1714.jpg)

**Comment by joshwget** [comment]
What type of auth are you using? Are you able to access Kubernetes with a generated kubeconfig?

**Comment by hiscal2015** [comment]
@joshwget RBAC was disabled, and I was able to access Kubernetes with a generated kubeconfig, but the strange thing is, now I can access CLI from UI now, doing nothing... I have 3 more environments to upgrade, I'll check if this is reproduceable.

![shell2](https://user-images.githubusercontent.com/15604715/29302207-b762d410-81b4-11e7-9dfb-cba0b1828858.jpg)

**Comment by hiscal2015** [comment]
Closed at this time, cannot reproduce.
