### ISSUE TITLE
Invalid backend host requested

### ISSUE THREAD

**Issue by funkydorian** [rancher/rancher#9683]
**Rancher versions:**
rancher/server: 1.6.7
rancher/agent: 1.2.5

**Infrastructure Stack versions:**
healthcheck: 0.3.1
ipsec: 0.11.7
network-services: 0.7.7
scheduler: r-kubernetes-scheduler-1-b2dee56d
kubernetes (if applicable): 1.7.2

**Docker version: (`docker version`,`docker info` preferred)**
1.12.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
4.11.12-coreos-r1

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
GCE

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
container is moved another host
When i click to Kubernetes UI
I got the error: Service unavailable
I see from the output: 
time="2017-08-15T09:00:01Z" level=info msg="Invalid backend host requested." hostUuid=511e0d74-983c-4367-5b73-0b56563d6e17 

**Results:**

**Comment by superseb** [comment]
Sorry for the late response, let us know if we can help reproduce this.
