### ISSUE TITLE
rancher agent fails update with internal docker repository

### ISSUE THREAD

**Issue by Xaseron** [rancher/rancher#9684]
**Rancher versions:**
rancher/server: 1.6.5
rancher/agent: 1.2.2

**Infrastructure Stack versions:**
healthcheck: 0.3.1
ipsec: 0.1.1
network-services: 0.2.3
scheduler: 0.8.2
kubernetes (if applicable):
cattle

**Docker version: (`docker version`,`docker info` preferred)**
```
Containers: 12
 Running: 12
 Paused: 0
 Stopped: 0
Images: 26
Server Version: 1.12.6
Storage Driver: devicemapper
 Pool Name: vg01-thinpool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: 
 Metadata file: 
 Data Space Used: 3.953 GB
 Data Space Total: 48.31 GB
 Data Space Available: 44.36 GB
 Metadata Space Used: 1.741 MB
 Metadata Space Total: 1.07 GB
 Metadata Space Available: 1.068 GB
 Thin Pool Minimum Free Space: 4.831 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: json-file
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: bridge host null overlay
 Authorization: rhel-push-plugin
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Security Options: seccomp
Kernel Version: 3.10.0-514.6.1.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.3 (Maipo)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 2
CPUs: 4
Total Memory: 15.51 GiB
Name: a0001.example.com
ID: WQJZ:L4R4:UCJK:NLRP:7ALJ:VM7T:7P4L:I6BP:6NGX:A2AI:DLM4:XBSH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://internal.example.de:9091/v1/
Insecure Registries:
 127.0.0.0/8
Registries: internal.example.de:9091 (secure)
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
NAME="Red Hat Enterprise Linux Server"
VERSION="7.3 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="7.3"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.3 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.3:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.3
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.3"
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
vm

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node, internal db

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
cattle

**Steps to Reproduce:**
- internal docker proxy with credentials
- update rancher server 1.5.8 -> 1.6.5

**Results:**
- rancher agent (v1.2.2) is unable to pull new rancher agent image (v1.2.5)
- rancher agent gets the error authorization required
- rancher agent can not get the required credentials from the rancher server because of the update of the rancher server
- the host system is logged in into the internal docker proxy repo

**workaround:**
- manually pulling the rancher agent image

**Comment by superseb** [comment]
A workaround is described here: https://github.com/rancher/rancher/issues/13440
