### ISSUE TITLE
When trying to add invalid user/group to  site access , there is no error message presented to user.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#9689]
Rancher versions: v1.6.8-rc3
AD Auth enabled setup.

Steps to reproduce the problem: 
Try to add invalid  user/group to  site access.
The invalid  user/group does not get added to the "Authorized Users and Organizations" list but there is no error message presented to the user which is confusing.

When trying to add invalid  user/group to environment access control , user is provided with error message- ```Identity not found: <user/group name>```.

We should provide the same user experience when adding invalid  user/group to  site access.

**Comment by deniseschannon** [comment]
Available in v1.6.8-rc5

**Comment by tfiduccia** [comment]
Version - v1.6.8-rc5
Verified fixed.
