### ISSUE TITLE
Better error message when edit settings results in admin user not being the same as existing admin user.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#9690]
Rancher versions: v1.6.8-rc3
Scenario 1:
Have LDAP auth enabled setup.
In "Admin/Access Control", use "Edit" option to change the "Hostname" to point to a different LDAP server.
Use "Test and Save" to test and commit the changes to configuration.
User is presented with following error message - "Mismatch in ExternalId of the Admin account, with new server settings"

Can this error message be made better?

Scenario 2:
Have LDAP auth enabled setup.
In "Admin/Access Control", use "Edit" option to make the user search base more restrictive such that the current admin user is not a valid user under this search base.

Use "Test and Save" to test and commit the changes to configuration.
User is presented with error message - "Cannot locate the user information with new server settings"

Can this error message be made better?

**Comment by prachidamle** [comment]
Scenario 1: With advise from @vincent99 will change the message to be:
 "Authentication succeeded, but the user returned has a different Distinguished Name than you are currently logged in to.  Changing the underlying directory tree is not supported."

Scenario 2: Will change this on same lines to be "Authentication succeeded, but cannot locate the user information with new server settings"

**Comment by deniseschannon** [comment]
Available with rancher/server:v1.6.8-rc4

**Comment by sangeethah** [comment]
Rancher versions: v1.6.8-rc3
Scenario 1:
Have LDAP auth enabled setup.
In "Admin/Access Control", use "Edit" option to change the "Hostname" to point to a different LDAP server.
Use "Test and Save" to test and commit the changes to configuration.
User is presented with following error message - "Authentication succeeded, but the user returned has a different Distinguished Name than you are currently logged in to. Changing the underlying directory tree is not supported"


Scenario 2:
Have LDAP auth enabled setup.
In "Admin/Access Control", use "Edit" option to make the user search base more restrictive such that the current admin user is not a valid user under this search base.

Use "Test and Save" to test and commit the changes to configuration.
User is presented with error message - "Authentication succeeded, but cannot locate the user information with new server schema settings"
