### ISSUE TITLE
Cannot see full name of services in link graph

### ISSUE THREAD

**Issue by zhaoyao91** [rancher/rancher#9691]
**Rancher versions:**
rancher/server: 1.6.7

Sometimes the service name can be a little long, by now, we can only see a short prefix in link graph which makes a lot of confusing.

![image](https://user-images.githubusercontent.com/3808838/29348077-85ee8bb6-8283-11e7-9dce-cbd66474be09.png)

**Comment by tfiduccia** [comment]
Version - 1.6.14-rc2
Verified fixed.  On hover you can now see the full name
