### ISSUE TITLE
rancher up hangs while upgrading if the container health check fails

### ISSUE THREAD

**Issue by borntorock** [rancher/rancher#9692]
**Rancher versions:**
rancher/server: 1.6.0
rancher/agent: v1.2.2

**Infrastructure Stack versions:**
healthcheck: v0.3.0
ipsec: 0.1.0
network-services: v0.2.0
scheduler: v0.5.1
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
17.03

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
4.11.0-1.el7.elrepo.x86_64

/etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA Rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

We're currently making use of above rancher v1.6.0 which has cattle v0.179.7 installed. We have also configured the healthcheck of the container and mentioned the values of both initializing_timeout and reinitializing_timeout of around 80 seconds.

Now, while doing rancher upgrade via `rancher up -s <stack-name> --force-recreate --pull --batch-size 1 -d`

the health check of the container fails, but the rancher up command simply hangs up and doesn't fails, in the jenkins job. 

**What we want to have finally**
We are actually looking for the rancher up command to fail automatically if the application deployment inside the container fails and print the container logs on the jenkins console itself. 

Really need help on this. @deniseschannon @ibuildthecloud

**Comment by cjellick** [comment]
What's the full configuration of your healthcheck? Could you post the docker-compose.yml and rancher-compose.yml files (with any sensitive parts sanitized)?

**Comment by borntorock** [comment]
@cjellick 

Please see the modified (with sensitive parts sanitized) docker-compose.yml and rancher-compose.yml file. 

docker-compose.yml
`version: '2'
services:
  nginx-test:
    mem_limit: 150000000
    image: modified-nginx
    hostname: nqa-docker-nginx-test
    environment:
      ENV: nqa
    command:
    - /usr/bin/supervisord
    labels:
      io.rancher.container.pull_image: always`

So, in the modified-nginx image, we have installed supervisord and configured supervisord to execute the start.sh script present in /mnt1. 

now, in /mnt1/start.sh script, I have 

`#!/bin/bash
sleep 60
exit 1`

rancher-compose.yml 
`version: '2'
services:
  nginx-test:
    scale: 2
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 5000
      port: 80
      unhealthy_threshold: 2
      initializing_timeout: 80000
      interval: 10000
      strategy: recreate
      reinitializing_timeout: 80000`

the healthcheck is configured as mentioned above in rancher-compose.yml file. 

now while running this, rancher up command or rancher-compose up command with the below options `--force-recreate --pull --batch-size 1`

keeps on spawning containers again and again in the jenkins job. Via the jenkins job itself, we're not able to identify whether the deployment inside the container is failing or not or whether container is healthy or not. 

let me know, if you need any other info.

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
