### ISSUE TITLE
Could not able to add Rancher Catalog with gitlabs

### ISSUE THREAD

**Issue by sjkeerthi** [rancher/rancher#9694]
**Rancher versions:**
rancher/server: v1.6.6
rancher/agent: v1.2.5

I am trying to add my own catalog, which in out own gitlabs the repo was pointed as pubic.
After I add the repo I could see as 

ERROR
There are no compatible templates

**Comment by superseb** [comment]
Can you share the layout of the repository? (`find /directory`) And the contents of your `.yml` files, please remove any sensitive info.

**Comment by sjkeerthi** [comment]
/tmp/red
/tmp/red/templates
/tmp/red/templates/red
config.yml
0

**Comment by sjkeerthi** [comment]
from the rancher/server when I try to clone I get the error below since my gitlab was with set with Letsencrypt Certficate.

git clone http://root@gitlab.star-systems.in/root/redington.git
Cloning into 'redington'...
fatal: unable to access 'https://xxxxxxx//root/xxxxxx.git/': server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none

When I checked under the rancher/server 
/etc/ssl/certs
there is no pem for the letsencrypt

**Comment by superseb** [comment]
This was related to the Apache 2.4 in front of Gitlab.

`curl https://gitlab.star-systems.in/root/redington.git` would return valid certificate, but `git clone https://root@gitlab.star-systems.in/root/redington.git` returns `server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none`.

Git uses GnuTLS and demands correct ordering of root and intermediate certs, and this means a different config on Apache 2.4 (specifically 2.4) like so:

```
SSLCertificateFile /etc/letsencrypt/live/$DOMAIN/cert.pem
SSLCertificateKeyFile /etc/letsencrypt/live/$DOMAIN/privkey.pem
SSLCertificateChainFile /etc/letsencrypt/live/$DOMAIN/chain.pem
```

This is different than `fullchain.pem` which is usually recommended. After applying the above config and a restart, the clone succeeded.
