### ISSUE TITLE
Refactor CNI config/wrapper script generation logic

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#9698]
Currently the CNI config and wrapper scripts are generated/injected by `network-manager`. Need to move this logic to CNI driver service so it's self managed.

**Comment by sangeethah** [comment]
Rancher Server version - Build from v1.6
rancher/network-manager:v0.7.10 and rancher/net:v0.13.0
Cattle validation tests succeeded and reported no new failures.

**Comment by leodotcloud** [comment]
https://github.com/rancher/rancher-catalog/commit/3123fb5fc61a23d9f2674ef88fc5285d7e717621
