### ISSUE TITLE
can not access rancher via nginx proxy, error 301 (permanently removed)

### ISSUE THREAD

**Issue by olegkolner** [rancher/rancher#9699]
I would like to provide routing to the rancher, e.d. http://myserver/rancher. I do this via nginx proxy with the following nginx.conf : 

        upstream rancher {
                server myserver:8080;
        }

        server {
                listen       80;
                server_name  myserver;

                #charset koi8-r;

                #access_log  logs/host.access.log  main;

                location / {
                        root   html;
                        index  index.html index.htm;
                }

                location /rancher/ {
                        proxy_set_header Host $host;
                        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                        proxy_pass http://rancher;
                        proxy_http_version 1.1;
                        proxy_set_header Upgrade $http_upgrade;
                        proxy_set_header Connection "upgrade";
                }

        }

But unfortunately become 301 status by http request:(

**Comment by aemneina** [comment]
@olegkolner can you access the rancher servers directly? Can you share your nginx config and maybe logs from nginx?

**Comment by olegkolner** [comment]
sry, I've accidentally clicked "enter" before to write a description:D

**Comment by vincent99** [comment]
The server expects to be run at the root path `/` and we do not support using a subdirectory `/rancher`.

**Comment by olegkolner** [comment]
oh, why so? Is it any logical reason for that?

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
