### ISSUE TITLE
When updating the scale for a service , update API forces us to also send service name.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#970]
Server Version - v0.22.0-rc1

Currently When updating the scale for a service , update API forces us to also send service name.
We should be able to only pass the scale parameter to service update api when I want to scale up/scale down the service.

**Comment by alena1108** [comment]
Thats a gdapi problem I believe; Darren already knows about it. By now, just pass the current name to your calls in tests.

**Comment by alena1108** [comment]
This bug no longer happens, so closing.
