### ISSUE TITLE
Handle conflicting container network mode

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#9700]
Comments from: https://github.com/rancher/cattle/pull/2881

Also there seems to be the bigger issue that the presence of io.rancher.container.network=true label overrides the networkMode to managed for native containers started with --net=host (start container with docker run -d -it --net=host --label io.rancher.container.network=true ubuntu:latest and you'll see 10.42.x.x address set on the container); not sure if that needs to be fixed. This PR just makes sure to not set the label on k8s containers with hostNetwork=true.

Related: https://github.com/rancher/rancher/issues/9678

**Summary:** A container launched with `--net=host` and the label `io.rancher.container.network: true` should not be registered under managed network.

<img width="1136" alt="screen shot 2017-10-26 at 11 37 36 am" src="https://user-images.githubusercontent.com/19392926/32070734-2362e4b4-ba42-11e7-9886-9b8356605f05.png">

===================================

One more issue that's being tracked here is from a customer:
**Problem:** The mac address of the host was changed and due to a security violation that host was not allowed to communicate anymore causing it to be disconnected from `rancher/server`.
**Notes:**
- There was an upgrade of the setup from 1.6.7 to 1.6.10
- Since the macsync happens only during the start of `network-manager`, may be there were problems due to https://github.com/rancher/rancher/issues/10103 (Fix: https://github.com/rancher/plugin-manager/pull/111)
- Likely caused due to containers with `--net=host` and sidekicks to that. This is the same scenario when using k8s, coz all containers are using network from the POD container.

**Comment by leodotcloud** [comment]
Discussing with @ibuildthecloud the label `io.rancher.container.network` should be used only for back-populated containers. So we need to ignore this label when a container is started from the UI.

**Comment by soumyalj** [comment]
This issue of host mac address issue change can be reproduced in the following use cases:
1. Create a 1.6.4 Kubernetes setup and create pods using the below yaml:
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx2
  labels:
    app: nginx
spec:
  hostNetwork: true
  containers:
  - name: nginx
    image: sangeetha/testnewhostrouting
    ports:
    - containerPort: 80
```
2. Restart Network Manager.
3. The mac address of the hosts change and the host goes to reconnecting/disconnected state.

**Comment by leodotcloud** [comment]
Targeted for 1.6.11-rc6. network-manager: v0.7.13.

**Comment by leodotcloud** [comment]
The MAC prefix will be handled in https://github.com/rancher/rancher/issues/9755

**Comment by soumyalj** [comment]
Tested with upgrade from v1.6.7 to v1.6.11-rc6. Upgraded network manager. The hosts did not go to reconnecting state (The mac address sync did not kick in for pods with hostNetwork: true)

**Comment by sangeethah** [comment]
Tested with rancher server version - v1.6.11-rc6 and rancher/network-manager:v0.7.14

[rancher_network_modes_test_Results.xlsx](https://github.com/rancher/rancher/files/1436028/rancher_network_modes_test_Results.xlsx)
