### ISSUE TITLE
UI: The "Up to date" button is misleading

### ISSUE THREAD

**Issue by trondhindenes** [rancher/rancher#9706]
By clicking the "Up to date" button for an infrastructure stack, it's possible to change the behavior of the existing stack, for example changing Kubernetes settings. I would argue that this button has a misleading name, and the "up to date/upgrade available" should be moved to a separate ui element (label) so that the button itself could be renamed to something more fitting, like "change stack configuration" or whatever. It feels very counter-intuitive that clicking a button that says "up to date" actually allows me to change aspects of my environment.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
