### ISSUE TITLE
Scheduler stack is down

### ISSUE THREAD

**Issue by zhaoyao91** [rancher/rancher#9707]
**Rancher versions:**
rancher/server:1.6.7
rancher/agent:1.2.5

**Infrastructure Stack versions:**
healthcheck:0.3.0
ipsec:0.1.3
network-services:0.2.5
scheduler:0.6.3
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**

17.06-ce.0

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

3.13.0-107-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

single node rancher, internal and external db

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

Cattle

**Steps to Reproduce:**

I don't know how and when it happened

**Results:**

Scheduler is down and I have no way to restart it

```
Error
service.instance.delete
Removing bad service instance: Timeout getting IP address
```

**Comment by superseb** [comment]
What is the status of the rest of the `Infrastructure Stacks` ?

**Comment by zhaoyao91** [comment]
I am currently not fixing this cluster, if there would be more info, i will reopen it, thanks.
