### ISSUE TITLE
Custom catalog 'There are no compatible templates.'

### ISSUE THREAD

**Issue by chriskacerguis** [rancher/rancher#9708]
**Rancher versions:**
rancher/server: 1.6.5
rancher/agent: 1.2.5

**Infrastructure Stack versions:**
healthcheck: 0.3.1
ipsec: 0.11.3
network-services: 0.7.4
scheduler: 0.8.2
kubernetes (if applicable): n/a

**Docker version: (`docker version`,`docker info` preferred)**

```
# docker info
Containers: 18
 Running: 18
 Paused: 0
 Stopped: 0
Images: 18
Server Version: 17.06.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 183
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-89-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.691GiB
Name: nuc
ID: NON4:EGP4:JIRL:VORA:DR7V:N7Q3:T2QK:NP4B:U5LV:CL7D:YV7O:7DJI
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

```
# cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

```
# uname -r
4.4.0-89-generic
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

Bare-metal (Intel NUC)

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

single node rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

Cattle

**Steps to Reproduce:**

1.  Add a new custom catalog
2. Add the following:
> Name: Cowdog
> URL: https://github.com/chriskacerguis/rancher-catalog.git
> Branch: master
3.  Go to the custom catalog

**Results:**

Seeing the following error message:

There are no compatible templates.

(tried refreshing and waiting to no luck)

**Comment by superseb** [comment]
You are missing the `catalog` key in `rancher-compose.yml`: https://github.com/superseb/rancher-catalog-1/commit/f16bb03d1ad19599d03a1795487e54d573a30614

And the config file should be called `config.yml`.

Let me know if this fixes the problem for you.

**Comment by chriskacerguis** [comment]
@superseb thanks for responding so quickly.  I made the changes you suggested, and still no luck.

**Comment by superseb** [comment]
Did you manually refresh the catalog by hitting the update button on top?

**Comment by chriskacerguis** [comment]
Yes (several times)

**Comment by superseb** [comment]
The diff is for `rancher-catalog.yml` , not `docker-compose.yml` ;-)

**Comment by chriskacerguis** [comment]
<- I'm with stupid.

That fixed it...I clearly need more coffee :)

Thanks for your help @superseb I really appreciate it.
