### ISSUE TITLE
Add more fields to container/service create

### ISSUE THREAD

**Issue by ibuildthecloud** [rancher/rancher#971]
workingDir
securityOpt
logConfig
pidMode
extraHosts
readOnly

https://github.com/rancherio/cattle/pull/499

**Comment by vincent99** [comment]
I think all the ones we care about have been previously added...

**Comment by xlight** [comment]
will the workDir be added in v1.0 ?

**Comment by deniseschannon** [comment]
@xlight workingDir is part of the API. 

http://docs.rancher.com/rancher/api/api-resources/launchConfig/

Not sure if it's in the UI @vincent99

**Comment by vincent99** [comment]
`workingDir` is in 1.0.1: https://github.com/rancher/ui/pull/597

**Comment by tfiduccia** [comment]
Version - v1.0.1-rc7
Working Dir added
Verified fixed.

**Comment by n0rig** [comment]
I really need to disable some apparmor and seccomp security fields. Please add.

**Comment by feffi** [comment]
+1 for SecComp

**Comment by tfiduccia** [comment]
Added #8585.  This issues was closed and we don't normally look at those.  So I added an enhancement issue for the two requested security fields.
