### ISSUE TITLE
We need different TTL configs for internal and external DNS records

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#9711]
Today the TTL for rancher dns service applies to both internal and external DNS records; ideally we should separate them into 2 independent parameters

**Comment by parin921996** [comment]
is there any progress on this issue ? Rancher DNS floods external dns server with a lot of DNS queries. Currently we are need internal DNS cache TTL as lowest as possible but external TTL can be something more reasonable .

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

**Comment by mkaurin** [comment]
Has this been addressed in versions >2.0?
