### ISSUE TITLE
Containers from a Custom Host is not accessible

### ISSUE THREAD

**Issue by gpyzy** [rancher/rancher#9717]
**Rancher versions:**
rancher/server: v1.6.5
rancher/agent: v1.2.5

**Infrastructure Stack versions:**
healthcheck: v0.3.1
ipsec: v0.11.3
network-services: v0.7.4
scheduler: v0.8.2
kubernetes (if applicable):

**Docker version: (`17.06.0-ce-mac19 (18663)`)**

**Operating system and kernel: (`MacOS Sierra 10.12.6 (16G29)`, `16.7.0`)**

**Type/provider of hosts: HyperKit VM based on Alpine Linux on a Mac OS**

**Setup details: single node**

**Environment Template: Cattle**

**Steps to Reproduce:**
 - install rancher-server and create the container on my Mac OS, local IP is 192.168.1.1
 - go to http:192.168.1.1, go to Admin -> Settings -> Host Registration URL, set address as http://192.168.1.1:8080
 - go to Infrastructure -> Host -> Add Host -> Custom -> step 4, fill IP 192.168.1.1, copy the scripts in step 5, run the scripts in the bash command at my Mac OS.
 - Go to Infrastructure -> Host, verify my local Custom Host is created. <img width="344" alt="2017-08-19 12 22 38" src="https://user-images.githubusercontent.com/74477/29483767-5dc0e0f0-84d9-11e7-90df-4bb8def4870b.png">
 - Go to https://github.com/gpyzy/rancher-compose-helloworld/ to download the rancher-compose file and docker-compose file I prepared.
 - run `rancher-compose --debug up -d` on my Mac OS, wait for the cli complete the work.
 - Go to Stacks -> User, expand rancher-compose-helloworld, find 'helloworld' service.<img width="1102" alt="2017-08-19 12 37 25" src="https://user-images.githubusercontent.com/74477/29483840-2fe8eef0-84db-11e7-91b2-7c38bd706c2d.png">
 - Click the port number 80, the browser opens a new tab, redirect me to http://192.168.1.1

**Results:**
I expect to see a hello world screen like this 
<img width="709" alt="2017-08-19 12 43 11" src="https://user-images.githubusercontent.com/74477/29483866-fff22bc0-84db-11e7-8590-44c876025740.png">, but I see the http error '`ERR_CONNECTION_REFUSED`'. Looks like the port mapping is not working. I need some guidance.

**Comment by vincent99** [comment]
Docker for Mac is not supported.

You're really running a Linux VM (called Moby) and when you publish ports in Docker for Mac they map the connection from the Mac to the VM.  Rancher and CNI drivers use iptables rules to do pretty mapping, so there are no ports published as far as Docker for Mac  is concerned.

**Comment by gpyzy** [comment]
@vincent99 Thank you for the quick response. If I do want to learn and research rancher with my mac system, what should I do? Can I deploy rancher on a boot2docker Linux distribution, like, docker Toolbox for Mac? Below is the description from dokcer site. https://docs.docker.com/docker-for-mac/docker-toolbox/

The Docker Toolbox environment
Docker Toolbox installs docker, docker-compose, and docker-machine in /usr/local/bin on your Mac. It also installs VirtualBox. At installation time, Toolbox uses docker-machine to provision a VirtualBox VM called default, running the boot2docker Linux distribution, with Docker Engine with certificates located on your Mac at $HOME/.docker/machine/machines/default.

**Comment by gpyzy** [comment]
I found the similar topic had been discussed at https://github.com/rancher/rancher/issues/5356. I will try the workaround https://github.com/rancher/10acre-ranch/#docker-machine-on-macos. Thanks!
