### ISSUE TITLE
[Feature Request] - Additional data - Rancher Metadata

### ISSUE THREAD

**Issue by Rucknar** [rancher/rancher#9719]
**Summary**
Following discussions with @cloudnautique I've been re-writing the Prometheus Rancher Exporter to use the rancher-metadata service as a source of information. This allows us to simplify authentication and run the service in a more secure way. 

I'm 80% through re-writing the exporter, i've noticed however that i don't have access to some of the data that i'll need to maintain the existing widely used metrics and labels. 

rancher-metadata is missing the following: 
* Service health state (healthy or not)
* Stack health state (healthy or not)
* Host state (active, registering...etc)

I've had a quick look at the codebase, couldn't easily spot how this information is collated. If I get time then i'm happy to put together a PR to add the missing data. Might need some pointers in this case, raised here to track the requirements.

**Comment by Rucknar** [comment]
Had a look at the codebase, seems the data is fed in through cattle, code seemingly living inside `cattle/code/iaas/config-item/server/src/main/java/io/cattle/platform/configitem/context/data/metadata/common/` I'm not that familiar with the java codebase. I'll have a look at getting a PR together for feedback, that's of course presuming that the team at Rancher are happy adding this kind of data to the metadata service?

**Comment by vincent99** [comment]
I don't like it, because it changes rapidly and requires updating metadata on every host frequently and metadata is slowly becoming a slightly outdated copy of the API that is slightly easier to access.

But there's already container state in there, so...

**Comment by cloudnautique** [comment]
We could make helper functions in go-rancher-metadata based off of container health.

**Comment by Rucknar** [comment]
@vincent99 If the metadata isn't very close to current then driving dashboards off this data would probably a bad idea. I wasn't aware of the inner workings of the metadata service itself.

**Comment by Rucknar** [comment]
Though, i'd much rather get this stuff directly and submit a PR for integrated prometheus metrics :) Sadly not got the time or skills in java to take on such a task.

**Comment by cloudnautique** [comment]
@Rucknar, I believe what @vincent99 was getting at is not to add the fields directly to Metadata since the container data is already present. The updating of the container->service->stack would cause 3 reloads vs. deriving it from the container level data. Primarily, Rancher uses metadata vs. hitting the server API for just about everything. It is our preferred design pattern.

**Comment by Rucknar** [comment]
Right, okay. Apologies, put the confusion down to sleep deprivation!

**Comment by Rucknar** [comment]
Okay, i've managed to derive health state for services and stacks by making use of the `go-rancher-metadata` package and `[]container`.

That covers:
* Service health state (healthy or not)
* Stack health state (healthy or not)

I can't see an easy way however to obtain 
* Host state (active, registering...etc)
* Stack state (I initially thought i could obtain this from the status of the services, but the possible states are different for stacks/services).

Feels like i'm back in feature-request land with the above two requirements. What's the best way to proceed?

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
