### ISSUE TITLE
Unable to join Azure Host 

### ISSUE THREAD

**Issue by raghu-shukla** [rancher/rancher#9720]
*Describe your issue here*
I am trying to join Azure host, as with default configuration. its stucking as waiting to connect ssh.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.7` Cattle: `v0.183.5` UI: `v1.6.17` |
|Access|`localauth` `admin`|
|Orchestration|`Kubernetes`|
|Route|`hosts.index`|

**Comment by superseb** [comment]
You are trying to add a host through Azure machine driver? And what does the logging on the `rancher/server` say? The host running `rancher/server` should be able to connect to the machine over SSH (TCP/22)

**Comment by raghu-shukla** [comment]
Thanks superseb, Its got resolved now, i upgraded rancher to latest and it worked,
