### ISSUE TITLE
Rancher hosts try to connect to deleted nfs volumes

### ISSUE THREAD

**Issue by shuckepco** [rancher/rancher#9722]
**Rancher versions:**
rancher/server: v1.6.7
rancher/agent: 1.2.5

**Infrastructure Stack versions:**
healthcheck: v0.3.1
net: v0.11.3
network-policy-manager: v0.2.4
network-manager: v0.7.7
scheduler: v0.8.2
storage-nfs: v0.8.5
kubernetes (if applicable): no

**Docker version: (`docker version`,`docker info` preferred)**
`docker version`
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:20:04 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:18:59 2017
 OS/Arch:      linux/amd64
 Experimental: false

`docker info:`
Containers: 13
 Running: 13
 Paused: 0
 Stopped: 0
Images: 51
Server Version: 17.06.0-ce
Storage Driver: aufs
 Root Dir: /home/docker/aufs
 Backing Filesystem: extfs
 Dirs: 333
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local rancher-nfs
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.864GiB
Name: RancherHost02
ID: <some-ID-deleted>
Docker Root Dir: /home/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 101
 Goroutines: 98
 System Time: 2017-08-21T11:36:44.5839877+02:00
 EventsListeners: 4
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
`cat /etc/os-release:`
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

`uname -r`
3.16.0-4-amd64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Hyper-v

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single-node server, multiple hosts, internal DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**

1. Spin up a container with some nfs shares mounted via rancher-nfs
1. Delete the container -> nfs share are in "detached" state
1. Delete the detached nfs volumes via Rancher UI ("Infrastructure" -> "Storage" -> "Delete" the volume
1. Reboot Rancher host
1. docker ps hangs, in /var/log/daemon.log you can see that dockerd tries to mount nfs volumes but fails as described in #8433 )
1. The strange thing is: Rancher tries to mount nfs volumes _that have been deleted_ - and some volumes are shown with a blank name in /var/log/daemon.log.

**Results:**
- Dockerd/Rancher tries to load deleted volumes
- Expected: Deleted volumes should be completeley removed when they are deleted

**/var/log/daemon.log (examples):**
````
Aug 21 11:14:17 RancherHost02 dockerd[563]: time="2017-08-21T11:14:17.339068800+02:00" level=warning msg="Error restoring volume" driver=rancher-nfs error="error while checking if volume \"\" exists in driver \"rancher-nfs\": Error looking up volume plugin rancher-nfs: legacy plugin: plugin not found" volume=
Aug 21 11:14:17 RancherHost02 dockerd[563]: time="2017-08-21T11:14:17.339216100+02:00" level=warning msg="Unable to locate plugin: rancher-nfs, retrying in 1s"
Aug 21 11:14:18 RancherHost02 dockerd[563]: time="2017-08-21T11:14:18.339502300+02:00" level=warning msg="Unable to locate plugin: rancher-nfs, retrying in 2s"
Aug 21 11:14:20 RancherHost02 dockerd[563]: time="2017-08-21T11:14:20.339815800+02:00" level=warning msg="Unable to locate plugin: rancher-nfs, retrying in 4s"
Aug 21 11:14:24 RancherHost02 dockerd[563]: time="2017-08-21T11:14:24.340194500+02:00" level=warning msg="Unable to locate plugin: rancher-nfs, retrying in 8s"
...
Aug 21 11:14:47 RancherHost02 dockerd[563]: time="2017-08-21T11:14:47.341953500+02:00" level=warning msg="Error restoring volume" driver=rancher-nfs error="error while checking if volume \"angry-leavitt20-config\" exists in driver \"rancher-nfs\": Error looking up volume plugin rancher-nfs: legacy plugin: plugin not found" volume=angry-leavitt20-config
Aug 21 11:14:47 RancherHost02 dockerd[563]: time="2017-08-21T11:14:47.342100100+02:00" level=warning msg="Unable to locate plugin: rancher-nfs, retrying in 1s"
Aug 21 11:14:48 RancherHost02 dockerd[563]: time="2017-08-21T11:14:48.342415100+02:00" level=warning msg="Unable to locate plugin: rancher-nfs, retrying in 2s"
Aug 21 11:14:50 RancherHost02 dockerd[563]: time="2017-08-21T11:14:50.342738400+02:00" level=warning msg="Unable to locate plugin: rancher-nfs, retrying in 4s"
Aug 21 11:14:54 RancherHost02 dockerd[563]: time="2017-08-21T11:14:54.343047900+02:00" level=warning msg="Unable to locate plugin: rancher-nfs, retrying in 8s"
````

The volumes and corresponding containers do not appear in `docker volume ls`, `docker ps` oder `docker container ls` output. We already searched hosts and server for files containing references to the deleted volumes - with no luck. How can we get rid of this old volumes. Due to #8433 this has a huge impact on host startup time.

**Comment by shuckepco** [comment]
Maybe even related to #8984 ?!

**Comment by shuckepco** [comment]
@cjellick : You were involved in some other tickets closely related to this one. Any suggestions?

Thank you very much for your help!

**Comment by shuckepco** [comment]
We found the solution by ourselves:
It was some garbage in the metadata.db located in Docker's `volumes` folder _on the Rancher server_. Thought I had inspected it before, but I suppose I only did so on the hosts... :-/

Resolved the issue by doing what was suggested in (see https://github.com/rancher/rancher/issues/8984#issuecomment-313751841) -> deleted metadata.db and did a restart.

Is there a way to prevent this from happening again (e.g. by a specific order when deleting a container and it's nfs volumes)? Is this is a bug in Rancher or in Docker?

**Comment by shuckepco** [comment]
We found the solution by ourselves:
It was some garbage in the metadata.db located in Docker's `volumes` folder _on the Rancher server_. Thought I had inspected it before, but I suppose I only did so on the hosts... :-/

Resolved the issue by doing what was suggested in (see https://github.com/rancher/rancher/issues/8984#issuecomment-313751841) -> deleted metadata.db and did a restart.

Is there a way to prevent this from happening again (e.g. by a specific order when deleting a container and it's nfs volumes)? Is this is a bug in Rancher or in Docker?

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it

**Comment by nico01f** [comment]
Hi guys.

Two weeks ago I resolved a similar issue, this was caused by a container it doesn't exist. I tried to stop NFS container in rancherUI, but not working. After several tries, I found that certain volumes of the container wasn't removed. 
If you use rancher-cli you listing all volumes in rancher, but some don't. You should compare wich one are using what the missing volumes that NFS services needs.

My fix was removed the missing volumes and then tried startup the broken container, and voila! 
The issue was fixed.
Not is necessary to remove metadata of volumes, with rancher-cli is useful.

Maybe this fix is some new, but could be useful for others.

Bye!
Best regards!
