### ISSUE TITLE
Remove host/container from load balancer before terminating container

### ISSUE THREAD

**Issue by dwene** [rancher/rancher#9723]
I've been playing around with rancher for a couple of weeks now, but I haven't quite found this option yet. There are times when I need to remove a host from my environment(or project if you're looking from the API docs), and I'd like to drain all the requests from the load balancer and have rancher redistribute the containers before removing the host. I know there is the host "evacuate" option, but that also seems to hard eject containers so all currently executing web requests will timeout. Is there a way to accomplish something like this with the default rancher LB? Perhaps I could attach a label to the host and the load balancer would know not to direct any traffic to it?

**Comment by pulberg** [comment]
@dwene See #2777 and #8627
