### ISSUE TITLE
Afetr host was rebooted , there is no ipsec tunnel being established with other hosts.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#9725]
Rancher versions: v1.6.8-rc4 with rancher/net:v0.11.8

Steps to reproduce the problem:
Set up with 3 hosts.
Make sure inter host communication using managed network is fine between all 3 hosts.
Power down one of the host in the set up.
After the host gets to "Disconnected" state , power on the host.

Once the host gets to "Active" state , health check that gets started on this host is stuck in "Initializing" state forever.

ipsec tunnel is not being established with other hosts in the setup.
``swanctl --list-sas`` command from ipsec router from this host has no entries.

**Comment by leodotcloud** [comment]
Original issue: https://github.com/rancher/rancher/issues/8204

**Comment by leodotcloud** [comment]
Fixed in ipsec: 0.1.4 with image: rancher/net:v0.11.9

**Comment by sangeethah** [comment]
Rancher versions: v1.6.8-rc4 with rancher/net:v0.11.9

This issue is not see anymore. After host is rebooted , inter host communication between hosts in the environment works as expected.
