### ISSUE TITLE
Mixed content error behind traefik

### ISSUE THREAD

**Issue by w3blogfr** [rancher/rancher#9726]
**Rancher versions:**
rancher/server: 1.6.6

Hello,

Web interface call api without https after few minutes.

If i refresh the page, I can submit form (like edit host name), it's call https, and it's work fine
But, few minute later, if I submit same form, I have the mix content issue and I have to refresh the page to do my change .

As issue seem to be present with traefik, and nginx (#5016 ), I supposed, that is not a traefik issue, but may be I'm wrong.

** Step to reproduce **

You can find a reproduce docker-compose on my repo https://github.com/w3blogfr/rancher-error-https-exemple

Thanks in advance.

**Comment by w3blogfr** [comment]
I found a solution by upgrading traefik to 1.4.2 to use custom header.
Please see the example  https://github.com/w3blogfr/rancher-error-https-exemple

Need to pass use file provider instead of docker provider until next traefik version 1.5

**Comment by superseb** [comment]
Thanks!
