### ISSUE TITLE
CLI for rancher 2.0

### ISSUE THREAD

**Issue by StrongMonkey** [rancher/rancher#9728]
Fix rancher cli for 2.0

**Comment by StrongMonkey** [comment]
- [make run create containers if --scale isn't passed ] 

- [make ps show services and standalone container (serviceId == null) ] 

- [make pull work ] 

- [make up work] 

- [make env switch work ] 

- [add go-prompt ] 

- [make sure ssh work ]

**Comment by sangeethah** [comment]
Tested with rancher version v1.0.0-alpha1

1. Able to stop/start/exec/view logs/list(ps) for standalone containers.
2. Able to pull images to host successfully using ```./rancher  --env <env-id> pull --hosts <host-id> <image>```
3. Able to use rancher up command to start services using compose.yml
4. Able to switch environment using ```--env``` option when default environment is set  using rancher config command.
