### ISSUE TITLE
Kube-dns pod fails to setup with "secrets "kube-dns-token-p5h1h" not found" error

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#9734]
Steps to reproduce:
1) Deploy k8s cluster
2) Restart addonstarter cluster component
3) Do describe on kube-dns pod. Chances are high that you'll see the error:

```
 secrets "kube-dns-token-p5h1h" not found
```

Happens because kube-dns RC starts using kube-dns system account that addon starter replaces (along with other components) on its restart. The fix will be to use `io-rancher-system` account that never gets replaced.

**Comment by galal-hussein** [comment]
Rancher version: v1.6.8-rc5
Tested restarting the addon starter multiple times, and i can describe kubedns pods and see that they are still using the `io-rancher-system` account.

**Comment by matthijsvdr** [comment]
We have the same issue, almost every time the cluster is rebooted we get this error.
Note currently the cluster shuts down every evening, and starts up again in the morning.
Rancher 1.6.7
Kubernetes v1.7.2-rancher7

**Comment by matthijsvdr** [comment]
@alena1108 Should i open a new issue for this?
