### ISSUE TITLE
Auto purge of hosts using host.remove.delay.seconds doesn't handle kubernetes

### ISSUE THREAD

**Issue by ryanwalls** [rancher/rancher#9737]
**Rancher versions:**
rancher/server: 1.6.3

**Infrastructure Stack versions:**
kubernetes (if applicable): 1.6.6

**Docker version: (`docker version`,`docker info` preferred)**
1.12.6

**Steps to Reproduce:**
* Setup kubernetes cluster in Rancher.
* Set `host.remove.delay.seconds` to 60 in advanced rancher settings
* Terminate an instance
* Wait a couple mins.

**Results:**
Instance is removed from Rancher, but is not removed as a node in kubernetes.

Note:  Up until now we have been using a script to remove autoscaled nodes from Rancher and it has successfully removed those nodes from k8s.  We just deactivate them first.  Wait 20 seconds or so, and then remove them.  Trying to transition to `host.remove.delay.seconds` but it doesn't meet our needs because the node isn't removed from kubernetes.

**Comment by tuwid** [comment]
for me it doesnt work in general, i've set it to 30 seconds and it still not removing the instances

**Comment by superseb** [comment]
@tuwid A host that is in `Disconnected` state will be removed after `host.remove.delay.seconds`. If this is not the case for you, please create a new issue specifying what version and how to reproduce.

**Comment by superseb** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
