### ISSUE TITLE
Re-ordering port rules in LB bug

### ISSUE THREAD

**Issue by rmdort** [rancher/rancher#9739]
**Rancher versions:**
rancher/server:1.6.7

**Infrastructure Stack versions:**
kubernetes (if applicable): 1.7.2

**Steps to Reproduce:**

Go to Kubernetes -> Infrastructure stacks -> Load balancer

![image](https://user-images.githubusercontent.com/118231/29597189-8f91203c-87f3-11e7-879c-30fb15d7aa0b.png)

And Click on `Down` arrow in re-order control

**Results:**

The entry gets removed from the list

**Comment by vincent99** [comment]
https://github.com/rancher/rancher/issues/6885
