### ISSUE TITLE
[10acre-ranch] Warning: the "docker" command appears to already exist on this system

### ISSUE THREAD

**Issue by gpyzy** [rancher/rancher#9742]
**Rancher versions:**
rancher/server:v1.6.5
rancher/agent:v1.2.5

**Infrastructure Stack versions:**
healthcheck:v0.3.1
ipsec:v0.11.3
network-services:v0.7.4
scheduler:v0.8.2
kubernetes (if applicable):

**Docker version: (17.06.0-ce-mac19 (18950))**

**Operating system and kernel: (MacOS Sierra 10.12.6 (16G29), 16.7.0)**

**Type/provider of hosts: (HyperKit VM based on Alpine Linux on a Mac OS)**

**Setup details: (single node)**

**Environment Template: (Cattle)**

**Steps to Reproduce:**
- Follow the instruction from https://github.com/rancher/10acre-ranch/#docker-machine-on-macos, install docker-machine-driver-xhyve.
- run `mac-ranch -c rancher-server`

**Results:**
- I see the following error
====================================
Running pre-create checks...
Creating machine...
(rancher-server) Downloading /Users/jony/.docker/machine/cache/boot2docker.iso from https://releases.rancher.com/os/latest/rancheros.iso...
(rancher-server) 0%....10%....20%....30%....40%....50%....60%....70%....80%....90%....100%
(rancher-server) Creating VM...
(rancher-server) /dev/disk7          	                               	/Users/jony/.docker/machine/machines/rancher-server/b2d-image
(rancher-server) "disk7" unmounted.
(rancher-server) "disk7" ejected.
(rancher-server) Generating 20000MB disk image...
(rancher-server) created: /Users/jony/.docker/machine/machines/rancher-server/root-volume.sparsebundle
(rancher-server) Creating SSH key...
(rancher-server) Fix file permission...
(rancher-server) Generate UUID...
(rancher-server) Convert UUID to MAC address...
(rancher-server) Starting rancher-server...
(rancher-server) Waiting for VM to come online...
(rancher-server) Waiting on a pseudo-terminal to be ready... done
(rancher-server) Hook up your terminal emulator to /dev/ttys006 in order to connect to your VM
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with rancheros...
Error creating machine: Error running provisioning: error selecting docker: (ssh command error:
command : wget -O- https://get.docker.com | sh -
err     : exit status 1
output  : Connecting to get.docker.com (54.192.151.47:443)
-                    100% |*******************************| 18446   0:00:00 ETA

Executing docker install script, commit: 29533f9
Warning: the "docker" command appears to already exist on this system.

If you already have Docker installed, this script can cause trouble, which is
why we're displaying this warning and provide the opportunity to cancel the
installation.

If you installed the current Docker package using this script and are using it
again to update Docker, you can safely ignore this message.

You may press Ctrl+C now to abort this script.
+ sleep 20

Either your platform is not easily detectable or is not supported by this
installer script.
Please visit the following URL for more detailed installation instructions:

https://docs.docker.com/engine/installation/

) 

===================================

**Comment by vincent99** [comment]
I made it default to RancherOS a while ago, but you currently need the beta channel version of Docker for Mac (instead of stable) to have a new enough docker-machine that can provision rancheros correctly. 

Or use `-b` to run boot2docker instead.

**Comment by gpyzy** [comment]
@vincent99 , I don't find a beta version from Docker store at https://store.docker.com/editions/community/docker-ce-desktop-mac. What I found is a stable version and an edge version. Is Edge version the same as beta version you mentioned?

**Comment by pulberg** [comment]
@gpyzy i just tested with Docker Edge v17.07.0-ce-rc3-mac23, install is working and Rancher is up.

**Comment by superseb** [comment]
@gpyzy Yes, edge == beta. See this quote from https://docs.docker.com/docker-for-mac/release-notes/: 
```Release notes for stable and edge releases are listed below. (Starting with the CE release model, beta releases are called edge releases.) You can learn about both kinds of releases, and download stable and edge product installers at Download Docker for Mac.```

Please check out these links to switch:
 https://docs.docker.com/docker-for-mac/install/#download-docker-for-mac and https://docs.docker.com/docker-for-mac/faqs/#stable-and-edge-channels

Closing this as not-a-bug, but please comment if you need help.

**Comment by vincent99** [comment]
Sorry, yes edge.

**Comment by gpyzy** [comment]
Thanks all for the help. I tried Docker Edge v17.07.0-ce-rc3-mac23 and the error has gone, I'm all good now!
