### ISSUE TITLE
rancher k8s get node , not find other node

### ISSUE THREAD

**Issue by ztskycn** [rancher/rancher#9743]
*Describe your issue here*
Rancher Versions:
Server: 1.6.7
healthcheck: 0.2.3
vxlan: v0.11.2
network-services: v0.6.6
kubernetes: 1.5.4

Kernel：4.12 （From Centos7.3  3.10.0-514.26.2）
Docker Version:
1.12.3 on agents, 17.03.1-ce on rancher host

docker info 
Containers: 11
 Running: 10
 Paused: 0
 Stopped: 1
Images: 15
Server Version: 1.12.3
Storage Driver: devicemapper
 Pool Name: docker-253:0-67156248-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.785 GB
 Data Space Total: 107.4 GB
 Data Space Available: 42.66 GB
 Metadata Space Used: 5.042 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.142 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.12.7-1.el7.elrepo.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.857 GiB
Name: k8s-node05
ID: Z63P:RKII:NKWT:H5X3:HGX4:PO64:ANWN:OCLL:2XWY:KVWM:ARE3:IEQS
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.7` Cattle: `v0.183.5` UI: `v1.6.17` |
|Access|`Disabled`|
|Orchestration|`Kubernetes`|
|Route|`hosts.index`|

kubectl get nodes
NAME         STATUS    AGE       VERSION
k8s-node04   Ready     8h        v1.5.4-rancher1

why not find k8s-node05?

![image](https://user-images.githubusercontent.com/11976391/29611734-4ec22fc2-8831-11e7-8d2c-2ae7e8d9aab9.png)
![image](https://user-images.githubusercontent.com/11976391/29611744-583ddf24-8831-11e7-96e4-b7b10aa9a5d5.png)
![image](https://user-images.githubusercontent.com/11976391/29611763-657bfc0c-8831-11e7-9d32-e9c5f04c6101.png)

**Comment by superseb** [comment]
Can you describe what steps you followed to get into this state? As you are running k8s 1.5.4 on rancher v1.6.7 there was an upgrade involved?

**Comment by superseb** [comment]
Please report back so we can help on this.
