### ISSUE TITLE
[external-dns] RFE: protection from creating dns record conflicts with the dns name template 

### ISSUE THREAD

**Issue by sabiodelhielo** [rancher/rancher#9747]
**Rancher versions:**
rancher/server: v1.6.8-rc5
rancher/agent: v1.2.6-rc2

**Infrastructure Stack versions:**
rancher/external-dns:v0.7.0

**Docker version: (`docker version`,`docker info` preferred)**
docker 17.03-ce
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
ubuntu16.0.4

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
aws

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher, internal db

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
cattle

** Suggestion:
The issue was brought up in https://github.com/rancher/rancher/issues/8584, but the DNS Name Template and the per service override label 'io.rancher.service.external_dns_name_template' can lead to conflicts between services who might already have that FQDN. Is there way to protect against creating these conflicts?

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
