### ISSUE TITLE
catalog-service should restore corrupt git repository 

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#9753]
**Rancher versions:**
rancher/server: v1.6.7

**Steps to Reproduce:**

-  Git repo can get corrupted by any means (disk/network etc), simulate by emptying the index file of a catalog repository (`> /var/lib/cattle/cache/<id>/.git/index`)

**Results:**
Observe logging 
```
time="2017-08-25T13:34:32Z" level=error msg="Failed to perform catalog refresh: library: exit status 128"
```

catalog-service will not be able to fix this without manual intervention (removing the directory), but it should. `git status` will show the status of the git repo before fetching updates, and we can remove and retry.

```
# git status
fatal: index file smaller than expected
```
#

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
