### ISSUE TITLE
Deletion of one of the authorised users from LDAP kills the Access Control page

### ISSUE THREAD

**Issue by palfrey** [rancher/rancher#9754]
**Rancher versions:**
rancher/server: 1.6.7

**Infrastructure Stack versions:**
healthcheck: 0.2.3
ipsec: 0.11.2
network-services: 0.2.2
scheduler: 0.7.5

**Docker version: (`docker version`,`docker info` preferred)**
1.12.5

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 14.04, with 4.4 kernel

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node, external DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
1. Setup LDAP access control
2. Tick "Allow members of Environments, plus Authorized Users and Organizations"
3. Add a user to the list
4. Save config
5. Delete user from LDAP source

**Results:**
Access Control page is blank, and Javascript console shows "Uncaught TypeError: Cannot read property 'externalIdType' of null"

Was able to manually delete the user using the API, but it's annoying.

**Comment by schoeppler** [comment]
Hello,

i have the same problem. Thanks for sharing.

One question:
When a list all users with v1/accounts/ the deleted ldap user are not shown.

How did you delete the deleted ldap user using the api?

Thanks in advance

**Comment by palfrey** [comment]
1. Goto the API page, and click "Add Account API Key"
2. `curl -u <access key>:<secret key> http://<rancher host>/v2-beta/openldapconfigs | jq .data[0] > ldap.json`
3. Edit "ldap.json" and look at the "allowedIdentities" list. There should be a null entry. Delete it.
4. `curl -H 'Content-Type: application/json' -u <access key>:<secret key> -XPOST http://<rancher host>/v2-beta/openldapconfigs --data @ldap.json`

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it

**Comment by muffix** [comment]
Hi @loganhz, I just faced the exact same issue. Deleting the `null` entry resolved it for me, too, but it's still annoying. Almost the exact same setup as @palfrey.
