### ISSUE TITLE
Resolving kubernetes service using search domain breaks when domain directive is specified in /etc/resolv.conf

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#9757]
**Rancher versions:**
rancher/server: v1.6.7
rancher/agent: v1.2.5

**Infrastructure Stack versions:**
healthcheck: v0.3.0
ipsec: v0.1.3
network-services: v0.2.5
scheduler: n/a
kubernetes (if applicable): v1.7.2-rancher7

**Docker version: (`docker version`,`docker info` preferred)**
1.12.6
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
any
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
n/a
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher, internal db
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes
**Steps to Reproduce:**
Get hosts setup with directives `search` and `domain` both present in `/etc/resolv.conf`
**Results:**
Depending on the order of those, from the manpage (http://man7.org/linux/man-pages/man5/resolv.conf.5.html), the kubernetes services depending on resolving `kubernetes` by using domains in the `search` directive will not work.

```
The domain and search keywords are mutually exclusive.  If more than one instance of these keywords is present, the last instance wins.
```

If `domain` is the last directive inside `/etc/resolv.conf`, the `search` directive is ignored and will never be used to resolve `kubernetes` to its FQDN. This is a configuration error, the question is, do we document it or fix it in our own components.

This will result in the following logging (for reference):

proxy
```
25/08/2017 23:06:39E0825 21:06:39.869276       1 reflector.go:201] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:72: Failed to list *api.Endpoints: Get https://kubernetes:6443/api/v1/endpoints?resourceVersion=0: dial tcp: lookup kubernetes on 169.254.169.250:53: no such host
25/08/2017 23:06:39E0825 21:06:39.869283       1 reflector.go:201] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:72: Failed to list *api.Service: Get https://kubernetes:6443/api/v1/services?resourceVersion=0: dial tcp: lookup kubernetes on 169.254.169.250:53: no such host
25/08/2017 23:06:40E0825 21:06:40.878646       1 reflector.go:201] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:72: Failed to list *api.Service: Get https://kubernetes:6443/api/v1/services?resourceVersion=0: dial tcp: lookup kubernetes on 169.254.169.250:53: no such host
```

kubectl get pods -n kube-system
```
NAME                                   READY     STATUS             RESTARTS   AGE
heapster-4285517626-9rn3p              1/1       Running            5          5h
kube-dns-646531078-tqd98               1/3       CrashLoopBackOff   155        5h
kubernetes-dashboard-716739405-231sx   0/1       CrashLoopBackOff   74         5h
monitoring-grafana-3552275057-1ps89    1/1       Running            5          5h
monitoring-influxdb-4110454889-m1mqb   1/1       Running            4          5h
tiller-deploy-737598192-b40jc          0/1       CrashLoopBackOff   123        5h
```
kubectl logs kube-dns-646531078-tqd98 kubedns -n kube-system
```
I0825 21:04:57.142139       1 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...
F0825 21:04:57.642139       1 dns.go:168] Timeout waiting for initialization
```

kubectl logs kube-dns-646531078-tqd98 sidecar -n kube-system
```
ERROR: logging before flag.Parse: W0825 21:08:57.628902       1 server.go:64] Error getting metrics from dnsmasq: read udp 127.0.0.1:59654->127.0.0.1:53: read: connection refused
ERROR: logging before flag.Parse: W0825 21:09:02.629270       1 server.go:64] Error getting metrics from dnsmasq: read udp 127.0.0.1:41490->127.0.0.1:53: read: connection refused
```

Discussed with @leodotcloud , we can either add documentation or fix it inside the container by merging the `domain` directive in to the `search` directive if we find the `domain` directive.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
