### ISSUE TITLE
The create a new service or upgrade a service can be scheduled to the deactivate  host 

### ISSUE THREAD

**Issue by hongxiaolu** [rancher/rancher#9762]
**Rancher versions:**
rancher/server:v1.6.5
rancher/agent:v1.2.5  

**Infrastructure Stack versions:**
healthcheck:v0.3.1 
ipsec:v0.11.3、holder
network-services:
    - metadata:v0.9.2
    - network-manager:v0.7.4
scheduler:v0.8.2
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
1.12.6
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
OS:Ubuntu 16.04.3 LTS      kernel:4.4.0-87-generic
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
vmware 
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher and HA rancher, internal DB and external DB
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
If there are two hosts （A and B）in the default environment, and deactivate the B host. Create a service and schedule to the B host,This service can be created and run on the deactivate  host。or ,
Create a service and schedule to the A host,Next ，upgrade the service  and  scheduler to B host.

**Results:**
You can schedule it to deactivate host by create a new service or upgrading your service.

![1](https://user-images.githubusercontent.com/20707603/29739353-800a6402-8a6e-11e7-8785-7188948bb4bd.png)
![2](https://user-images.githubusercontent.com/20707603/29739354-83e09542-8a6e-11e7-966c-60caed2fda6f.png)

**Comment by vincent99** [comment]
I'd you set it to run on a specific host, that's where it goes. There is no scheduling.

**Comment by hongxiaolu** [comment]
thanks！
