### ISSUE TITLE
Persistance drivers for cluster sql

### ISSUE THREAD

**Issue by thomasb0123** [rancher/rancher#9763]
Hello, i'd like to use persistance and differents disks for my cluster mysql and persistance disk also when it scales.

For simple persistance i know i can use that : 
- /pathtomySSD/data/scaleid:/var/lib/mysql
But for dynamic persistance i'd like to do this way, but it's not working
- /pathtomySSD/data/{{ .Stack.Id}}:/var/lib/mysql

Any idea or better to create a NFS with persistance and use it at disk ?

**Comment by aemneina** [comment]
@thomasb0123 have you looked at the rancher-nfs volume driver? This might help you out:

https://github.com/rancher/rancher-catalog/tree/v1.6-development/infra-templates/nfs/4

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
