### ISSUE TITLE
[aliyun-machine-driver] Input then remove content from the memory/cpu input box, form will fail to be submitted

### ISSUE THREAD

**Issue by Tracy1994** [rancher/rancher#9765]
**Rancher versions:**
rancher/server: 1.6.9

**Steps to Reproduce:**

1. try to add a new host with machine driver from UI
2. click advanced options and input memory limit field
3. clear the memory limit field

**Results:**

User can not submit the form

**Expectation：**

User should be able to submit the form

**Comment by orangedeng** [comment]
Problem maybe in 
https://github.com/rancher/ui/blob/master/app/components/limit-parameters/component.js#L17-L19

When the input box of memory and cpu have been change, the property in model has been set to the empty string. I think this will needs UI engineer to ensure the problem.

**Comment by yasker** [comment]
@loganhz Can you look at this?

**Comment by loganhz** [comment]
Rancher versions:
rancher/server: 1.6.9

Steps to Reproduce:

1. try to add a new host with machine driver from UI
2. click advanced options and input memory limit field
3. clear the memory limit field

Results:

User can not submit the form

Expectation：

User should be able to submit the form

**Comment by loganhz** [comment]
I know how to fix it in 1.6 from UI side.
we can just pass a `null` to backend instead of an empty string. Then server will not complain anymore.

however, 99% users will not go to this scenario in 1.6 and it works well in 2.0.

should I fix it ? @yasker

**Comment by yasker** [comment]
@loganhz Not worth it. I will close the issue as WONTFIX

If any customer requires this later, we will take a second look.
