### ISSUE TITLE
Rancher is throwing an java.netUnknownHostException when attempting to create a host on AWS

### ISSUE THREAD

**Issue by SleepingTalent** [rancher/rancher#9767]
Rancher 	**v1.6.7**
Cattle 		**v0.183.5**
User Interface 	**v1.6.17**
Rancher CLI 	**v0.6.3**
Rancher Compose **v0.12.5**

Rancher is throwing an **java.netUnknownHostException** when attempting to create a host on AWS

I am trying to create a host on **eu-west-1**

The following exception is thrown:

 *java.netUnknownHostException : ec2.eu-west-1.amazonaws.com*

When I ping **ec2.eu-west-1.amazonaws.com** I do receive a response so my machine can see **ec2.eu-west-1.amazonaws.com**

I have also tried creating an AWS host using a few different regions, each time the error is the same

The GUI displays the following error message on the add Host page.

*XMLParserError: o.getElementsByTagName(...)[0] is undefined*

Any ideas how I can resolve this?

**Comment by superseb** [comment]
Please try to re-create on a newer version and update/file the issue.
