### ISSUE TITLE
delete the host when the docker is installing ,host can't be delete completely

### ISSUE THREAD

**Issue by Tracy1994** [rancher/rancher#9768]
**Rancher versions:**
rancher/server: stable
rancher/ui: 1.6-dev
aliyun ecs list: https://ecs.console.aliyun.com/#/server/region/cn-shenzhen

**Steps to Reproduce:**
1.add host through ui
2.machine had already create
3.docker installing
4.delete host

**Results:**
aliyun ecs lists shows that host is running, but when I try to reset it password, it told me that instance is not exit.
**expectation：**
that host had deleted both in rancher ui and aliyun ecs list

#9575 
@yasker @orangedeng

**Comment by yasker** [comment]
@Tracy1994 

So it's in the same state later? Or it's just failed intermediately. Sounds like Aliyun ECS bug if it's true.

**Comment by orangedeng** [comment]
Can we login to instance? Or just See them in the host list? Because the ECS list in Aliyun console may delay for a few secounds.

**Comment by Tracy1994** [comment]
The host will be deleted in aliyun about 3 minutes later. Even though host had been removed through UI, it still need some times to delete it in the background.

**Comment by yasker** [comment]
That's acceptable. Backend may delay a bit but the operation is completed in the end. We don't require UI and backend to be completed at the same time.
