### ISSUE TITLE
Aliyun host cannot be deleted when the infrastructure stack is installing

### ISSUE THREAD

**Issue by Tracy1994** [rancher/rancher#9769]
**Rancher versions:**
rancher/server: stable
rancher/ui: 1.6-dev
aliyun ecs list: https://ecs.console.aliyun.com/#/server/region/cn-shenzhen

**Steps to Reproduce:**
1.add host through ui
2.machine had already create
3.docker install done
4.agent install done
5.infrastructure installing
6.delete host 

**Results:**
aliyun ecs lists shows that host is stop
**expectation：**
that host had deleted， both in rancher ui and aliyun ecs list

#9575 
@yasker @orangedeng

**Comment by yasker** [comment]
Hi @Tracy1994 

If infrastructure stack installation is completed, will the action to delete the host successful?

**Comment by yasker** [comment]
@orangedeng 

Where is our Aliyun ECS machine driver?

It sounds like a bug with it.

**Comment by orangedeng** [comment]
Aliyun ECS machine driver repo is https://github.com/AliyunContainerService/docker-machine-driver-aliyunecs 

I am going to update the driver to newest version in my repo. I am not sure that it will fix this problem or not because I didn't see related commits.

**Comment by Tracy1994** [comment]
The host will be delete in aliyun ECS list in 3 minutes later.

**Comment by yasker** [comment]
It's fine to have the host removed after 3 minutes.
