### ISSUE TITLE
user experience suggestion about I/O optimized

### ISSUE THREAD

**Issue by Tracy1994** [rancher/rancher#9770]
**Rancher versions:**
rancher/server: stable
rancher/ui: 1.6-dev
### Since
 only the I/O Optimized and the instance type is match, can the host be created.
### But
when the user after filling in the instance type, they don't know whether they should select I/O optimized or not until the host give out error. Bad usr experience.
### Suggestion
After the user filling in the instance type, we match the I/O optimized automatically and don't let the user changed it. 

@yasker @orangedeng

**Comment by kingsd041** [comment]
Rancher versions:
rancher/server: 1.6.11-rc3
rancher/ui: 1.6.24

Test passed.
