### ISSUE TITLE
Feature Request: Allow uploading/pasting of answers file when deploying catalog via the UI

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#9771]
It would be nice to be able to allow an answers file to be uploaded or pasted into a field to auto-populate the question's answers when deploying a catalog template from the UI.

**Comment by tfiduccia** [comment]
@loganhz - this has not been implemented for 2.0.   There is no upload button for the answers?

**Comment by loganhz** [comment]
It only works for Library app for now. There is a read form file button in UI. The PR for helm catalog is not merged yet

**Comment by tfiduccia** [comment]
Version - 2.1 master 9/10
Verified fixed
