### ISSUE TITLE
Update Catalog Preview to show Answers in YAML format

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#9772]
With #9305 being closed, it would be preferred to have the `answers.txt` be changed over to `answers.yaml` in the Preview section when deploying a catalog template from the UI.

**Comment by ekristen** [comment]
Is this only going to be in version v2? Or will it be made available in v1.x as well?

**Comment by ekristen** [comment]
Ok

**Comment by tfiduccia** [comment]
Version - 2.1 master 9/10
Verified fixed
