### ISSUE TITLE
vxlan: Need to support MTU > 1500

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#9774]
Related: https://github.com/rancher/rancher/issues/9414
Based on the discussion here: https://github.com/rancher/vxlan/pull/1#discussion_r133151312, the MTU is being configured on the VTEP and the interface but something seems to be not working.

Please take a look at this @niusmallnan.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
