### ISSUE TITLE
The documentation is lacking a full matrix that shows what CRUD privileges apply for different types of users (admin, user, owner, member, restricted)

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#9775]
Especially:
- CRUD privileges for private templates and private environments
- CRUD privileges for public templates
- CRUD privileges for Infrastructure, ie.  "Storage", "Secrets", "Certificates" and "Registries"

**Comment by deniseschannon** [comment]
http://rancher.com/docs/rancher/v1.6/en/environments/#permissions-key
