### ISSUE TITLE
Validate k8s 1.8

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#9776]
Once k8s 1.8 is available, we should:

1) Release rancher template for it.
2) Update addons to the latest versions
3) Validate the template:
* basic functionality
* with Docker 1.12.6, 1.13.x and 17.03

**Comment by superseb** [comment]
Upstream validation issue: https://github.com/kubernetes/kubernetes/issues/42926

**Comment by moelsayed** [comment]
https://github.com/rancher/rancher/issues/9858

**Comment by moelsayed** [comment]
#9866

**Comment by moelsayed** [comment]
Docker 1.12.x:
- Ubuntu 16.04: **Validation passed**.
- Ubuntu 14.04: **Validation passed**.
- RHEL 7.3 / upstream docker: **Validation passed**.
- RHEL 7.3 / native docker: **Validation passed**.

Docker 1.13.x:
- Ubuntu 16.04: **Validation passed**.
- Ubuntu 14.04: **Validation passed**.
- RHEL 7.3 / upstream docker: **Validation passed**.
- RHEL 7.3 / native docker: **NA**.

**Comment by moelsayed** [comment]
Upgrade test from `rancher/k8s:v1.7.4-rancher2` to `rancher/k8s:v1.8.0-beta.1-rancher4` passed successfully.

**Comment by sangeethah** [comment]
Reopening to test some of the configurations with latset k8s 1.8 templates.

**Comment by moelsayed** [comment]
Using `v1.6.11-rc3`:

Docker 1.12.x:
- Ubuntu 16.04: **Validation passed**.
- Ubuntu 14.04: **Validation passed**.
- RHEL 7.3 / upstream docker: **Validation passed**.
- RHEL 7.3 / native docker: **Validation passed**.
- RancherOS 1.0.3: **Validation passed**.

Docker 1.13.x:
- Ubuntu 16.04: **Validation passed**.
- Ubuntu 14.04: 
- RHEL 7.3 / upstream docker:
- RHEL 7.3 / native docker: **NA**.
- RancherOS 1.0.3:

Docker 17.03.x:
- Ubuntu 16.04: 
- Ubuntu 14.04: 
- RHEL 7.3 / upstream docker: 
- RHEL 7.3 / native docker:
- RancherOS 1.0.3: **Validation passed**.
