### ISSUE TITLE
Setting up OpenLDAP Access Control using the API doesn't work

### ISSUE THREAD

**Issue by ghost** [rancher/rancher#9777]
I've been trying setting up Access Control via OpenLDAP using the API and the result is that I got locked out of the UI, when trying again with the exact same settings from the UI the authentication worked fine.

The command I used (with of course sensitive information cleaned out):
`curl -u xxx:xxx -X POST -H 'Accept: application/json' -H 'Content-Type: application/json' -d '{"accessMode":"unrestricted","connectionTimeout":1000,"domain":"ou=people,dc=xxx,dc=xx","enabled":true,"groupMemberMappingAttribute":"memberUid","groupNameField":"name","groupObjectClass":"groupOfNames","groupSearchField":"cn","loginDomain":"","name":"openldapconfig","port":389,"server":"xxxxxxx","serviceAccountPassword":"xxx","serviceAccountUsername":"uid=xxx,ou=people,dc=xxx,dc=xxx","tls":false,"userDisabledBitMask":0,"userEnabledAttribute":"","userLoginField":"cn","userMemberAttribute":"memberOf","userNameField":"name","userObjectClass":"inetOrgPerson","userSearchField":"cn"}' https://xxxxxx/v1/openldapconfig`

Everything seemed to work fine but I got booted out from the UI and could not login in any way. In the logs I could see these kind of exceptions:
`2017-08-28 10:34:50,476 ERROR [:] [] [] [] [1020391880-4638] [i.a.a.i.l.O.OpenLDAPIdentityProvider] When searching ldap from /v1/identity Failed to search: (&(=cn=xxx,ou=group,dc=xxx,dc=xxx)(objectClass=groupOfNames)) scope:ou=people,dc=xxx,dc=xxx javax.naming.directory.InvalidSearchFilterException: invalid attribute description`
I'm suspecting the problem is the = sign that comes right before cn in the beginning of the query string.

If I do the exact same setup with the same parameters from the UI the authentication works correctly.

Also another thing I noticed is that disabling the OpenLDAP Access Control by invoking the API with "enabled": false doesn't work, Rancher was still trying to connect to our LDAP server. I had to tear down and recreate the cluster for gaining access again to the UI.

**Rancher versions:**
rancher/server: 1.6.5
rancher/agent: 1.2.5

**Docker version: (`docker version`,`docker info` preferred)**
`docker version`:
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 08:01:32 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 08:01:32 2017
 OS/Arch:      linux/amd64
 Experimental: false

`docker info`:
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 17.03.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 21
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-1030-aws
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.952 GiB
Name: ip-10-177-202-180
ID: WBPT:643K:E7RO:H2CT:3HHW:HWXA:KZS5:2RNG:FVYB:ZZIA:TKDP:SSO5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
`cat /etc/os-release`:
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

`uname -r`:
4.4.0-1030-aws

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS t2.small instance

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Comment by cjellick** [comment]
The UI only interacts with the API, so it isn't doing anything through the backdoor. There must be some nuanced difference between your api calls and the UI's api calls. You could open up the developer tools option in your browser and look at the requests that the UI is making when auth is enabled and compare them to your own.

**Comment by matq007** [comment]
It's because of the search query `(&(=cn=xxx,ou=group,dc=xxx,dc=xxx)(objectClass=groupOfNames))`. I have currently the same issue, looks like a bug. If you remove the first `=` it should work.

**Comment by robertofpaf** [comment]
Yes, I know that it's because of the first `=` sign, but if you look at the message I sent via API I don't have that query string anywhere available. So how do I remove it?

**Comment by matq007** [comment]
You can't remove it. The rancher is doing it in the background when it's trying to build a query. This has to be fixed, searching for the code now.

**Comment by robertofpaf** [comment]
Ok sorry, I thought the "if you remove" was meant to me :)

**Comment by cjellick** [comment]
@matq007 are you also attempting to do this via the API directly or are you seeing it just by going through the UI?

**Comment by matq007** [comment]
Hey @cjellick, not really. I'm trying to setup our Windows AD with the rancher. I found out this problem happened when I tried to log in with my credentials. After some docker logs I've discovered that the cattle is generating the `=` sign. If you want I can provide some more log info. I think it should be fixed somewhere here: https://github.com/rancher/cattle/blob/v0.178.4/code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/LDAPIdentityProvider.java. 
What do you think?

**Comment by vincent99** [comment]
The resulting looks like userSearchField (or groupSearchField) is somehow not set.

But there seems to be some general confusion here, as you are configuring OpenLDAP but say you're trying to use AD.  The `openldapconfig` type is for OpenLDAP.  `ldapconfig` is for AD (because at the time we only supported AD and thought it would work for any LDAP implementation, but that didn't pan out).

**Comment by matq007** [comment]
You think @vincent99 someone could check it out? I can try to fix it otherwise.
My case is to just use the windows AD for authentication in our company :).

**Comment by cjellick** [comment]
@matq007 to Vincent's point, which icon did you click to configure auth: Active Directory or OpenLDAP? Also, what version of rancher are you on?

@mrajashree have you looked into this issue yet (she wrote the Active Directory integration code).

**Comment by mrajashree** [comment]
@cjellick yes I was going to ask about the version, the bug originally is for 1.6.5 Openldap, so @matq007 can you share what version and as mentioned above which icon you clicked?

**Comment by matq007** [comment]
hey @mrajashree sorry for late response. everything is fine now. I was trying to setup the AD using OpenLDAP :|.

**Comment by robertofpaf** [comment]
But this points to the fact that there's a bug lingering around in OpenLDAP that causes invalid queries to be sent to an LDAP server, doesn't it?

**Comment by superseb** [comment]
Closing as stale.
