### ISSUE TITLE
[add host through aliyun machine driver] Name is invalid, but the form still can be submitted.

### ISSUE THREAD

**Issue by Tracy1994** [rancher/rancher#9778]
**Rancher versions:**
rancher/server: stable
rancher/ui: 1.6-dev
host api: http://120.78.12.209:8000/v2-beta/projects/1a5/host

**Steps to Reproduce:**
1. Add host through aliyun machine driver.
2-1. Host name is number only.
2-2.  Host name is number-letter combination.
2-3.  Host name contain special character . such as "_" 

**Results:**
1.Form submit successfully.
2.Machine create fail.

**expectation：**
Form cannot be submit and remind user "your hostname is invalid, the rules is ...".

#9575 
@yasker @orangedeng @jimmy-peng

**Comment by kingsd041** [comment]
Rancher versions:
rancher/server: 1.6.11-rc3
rancher/ui: 1.6.24

1. I add Aliyun host to the rancher UI, "Name" can start with a number. Aliyun is unsupported.
2. "Name" cannot be entered "_", Aliyun is supported.
reference：
It must be 2-128 characters long and start with an uppercase/lowercase letter or a Chinese character. It can contain numbers, '.', '_', or '-'

**Comment by yasker** [comment]
@orangedeng You should move this issue from Implement to Review when you've done coding. Check the flowchart. I will do it for you this time.

Also, don't allow Chinese character.

**Comment by kingsd041** [comment]
Rancher versions:
rancher/server: 1.6.11-rc5
rancher/ui: 1.6.26

Test passed.
