### ISSUE TITLE
[Proposal] Upgrade helm and tiller to v2.6.0

### ISSUE THREAD

**Issue by hiscal2015** [rancher/rancher#9779]
Hi, Rancher team

Since Kubernetes has been upgrade to v1.7 from rancher v1.6.6, but old helm version does not support many features of K8S 1.7 until helm v2.6.0, can you please upgrade tiller and helm client to v2.6.0 from Rancher v1.6.8 stable? Thanks a lot.

**Comment by superseb** [comment]
We added some documentation on updating tiller and helm here: http://rancher.com/docs/rancher/v1.6/en/kubernetes/addons/#upgrading-helm

For v1.8 we have tasks to update the addons as described here: https://github.com/rancher/rancher/issues/9776

Let me check what the plan is for v1.7 in the next release.

**Comment by hiscal2015** [comment]
The upgrade document can be considered as a workaround, if kubernetes-addon container restarted it should be changed back to the old version right? Currently I have to customize the rancher k8s image to replace till version.

**Comment by superseb** [comment]
True, we have this issue to cover that. https://github.com/rancher/rancher/issues/10045

Closing this as both cases are covered, please reply if you don't agree.
