### ISSUE TITLE
Agent can't connect to server on same host

### ISSUE THREAD

**Issue by elsmorian** [rancher/rancher#9782]
Basically as described here: https://forums.rancher.com/t/cant-get-rancher-agent-running-on-the-same-host-as-the-rancher-server/7156

Agent running on same machine as the server can't connect. Have set the CATTLE_AGENT_IP env variable as seems to be the common problem, but no joy..

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.7` Cattle: `v0.183.5` UI: `v1.6.17` |
|Access|`Disabled`|
|Orchestration|`Cattle`|
|Route|`authenticated.project.help`|

**Comment by aemneina** [comment]
try using `-e CATTLE_AGENT_IP='<ip_addr_of_host>'` with your docker run command for your agent host.

**Comment by elsmorian** [comment]
As I stated above and in the Forum post, I have tried that and get the same behaviour...

**Comment by elsmorian** [comment]
For anyone finding this issue, the cause was the /etc/hosts file on that machine was pointing to the wrong IP for the domain name the rancher server was advertising! Many thanks to @superseb for the help!
