### ISSUE TITLE
[rancher-dns] Digital Ocean provider TTL

### ISSUE THREAD

**Issue by SamMousa** [rancher/rancher#9785]
According to the source code of the DO plugin, DO does not support a per record TTL.

https://github.com/rancher/external-dns/blob/8ce04fb3e0f502f98268acd1f6f9d2eb0d22cdee/providers/digitalocean/digitalocean.go#L73

However it seems that statement is no longer true.
In fact as far as I can tell, currently DO supports a per record TTL. 

Furthermore it seems there is no way to configure the TTL, the environment variable is ignored and all I'm getting is TTLs of 1800, regardless of any configuration.

The relevant API docs are here: https://developers.digitalocean.com/documentation/v2/#create-a-new-domain-record

---> I don't speak GO, but I think just removing line https://github.com/rancher/external-dns/blob/8ce04fb3e0f502f98268acd1f6f9d2eb0d22cdee/providers/digitalocean/digitalocean.go#L73 could solve the issue..

**Comment by SamMousa** [comment]
I've created a PR; is there any timeframe for reviewing PRs?

I'm not in a hurry, but the external-dns repo has PRs without any feedback that have been open almost 5 months.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
