### ISSUE TITLE
Settings link in the "Access Control is not configured" bar is not obvious.

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#979]
v0.22.1-rc1

The fact that the word "Settings" is a link in the red bar is not obvious. It should stand out more. 

![screen shot 2015-05-29 at 12 03 49 pm](https://cloud.githubusercontent.com/assets/11410997/7890447/f5939a22-05fa-11e5-9655-f7646ddb91b5.png)

**Comment by vincent99** [comment]
![image](https://cloud.githubusercontent.com/assets/753917/11969689/6fee0d66-a8da-11e5-92c0-4943134f9049.png)
