### ISSUE TITLE
Kubernetes and private registry: image for "pause" container fails to be pulled 

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#9790]
Steps to reproduce:

1) Create private repo (auth protected), register the repo in Rancher. Upload image for "pause" pod container to the repo (original image tag is gcr.io/google_containers/pause-amd64:3.0)
2) Deploy Kubernetes with "Pod Infra Container Image" pointing to the image from the private repo.

Bug: Kubernetes fails to pull an image for "pause" container, so none of the addon pods start. 
Workaround: download the image to all the hosts manually.
Note: images for user containers are being pulled just fine from the private repo; the problem is just with the pulling for `pause-amd64:3.0`

https://github.com/kubernetes/kubernetes/issues/51293

**Comment by cjellick** [comment]
@alena1108's upstream fix landed in 1.8. Can we validate as part of k8s 1.8 integration validation?

**Comment by alena1108** [comment]
Workaround: prepull pause container images to all the hosts

**Comment by moelsayed** [comment]
@alena1108 @cjellick Upstream fix didn't make it to a release yet.

**Comment by moelsayed** [comment]
Tested with v1.6.11-rc1 and k8s v1.8.0-rancher4. Upstream fix confirmed.
