### ISSUE TITLE
Add manual pre and post setup and validation to 

### ISSUE THREAD

**Issue by sabiodelhielo** [rancher/rancher#9792]
Some of the setup and validation for upgrade are done manually. We can automate these manual steps with the API client.

Steps that are missing for setup and validation test code:
* Pre-upgrade:
  * Add setup AD Auth (there is already test examples to do this)
  * Add second environment 
  * Add second user to second environment (generate API keys as well)  -> this needs to be pass along in pipeline to the post-upgrade validation
  * Use second user to create a host in the second environment
  * Add a service to secondary environment with secondary user
* Post-upgrade: 
  * Add verification secondary user can modify secondary env and not the primary
  * Add a host in primary env and verify global service start on it
  * Download machine config and use it to ssh into new host

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
