### ISSUE TITLE
Update/Create script to handle the upgrade for non-HA/HA rancher server tags

### ISSUE THREAD

**Issue by sabiodelhielo** [rancher/rancher#9793]
Update the python script or create a new script better suited to update a rancher/server for non-HA and HA setups that will be used by Jenkins automation for Upgrade Validation.

The script will need to be able to log into the host or hosts and update accordingly for the type of rancher server setup (non-HA or HA)

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
