### ISSUE TITLE
rancher/server can't start after restart from ui  operation

### ISSUE THREAD

**Issue by hnmas** [rancher/rancher#9795]
**Rancher versions:**
rancher/server:1.6.7
rancher/agent:1.2.5

**Docker version: (`docker version`,`docker info` preferred)**
1.12.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
ubuntu16.4   4.10.0-28-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VMware12.5.7

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher, internal DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
1.Add new host, after host active,click rancher-server container;
2.rancher-server container right top menu, open and click restart;
3.rancher-server begin restart,but can't start in final;
5.use docker start id, the rancher-server start and exit direct;
5.reboot the host, rancher-server start and exit direct;
6.rancher-server can't start in any way.
7.only can  docker run to create a new rancher-server.

but, if not restart rancher-server in rancher UI, the rancher-server is work normal,and when reboot the host, rancher-server still work normal.

**Comment by cjellick** [comment]
I'm confused. Are you running two different ranchers in a rancher-in-rancher type setup? Or are you adding the host running rancher-server as a node in your setup and then restarting the container that is running the rancher-server that you are currently activating?

**Comment by Xstoudi** [comment]
Same here.
I restarted rancher-server from the UI and it won't start anymore.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
