### ISSUE TITLE
Regex support for tags in Service Upgrade Webhook 

### ISSUE THREAD

**Issue by WoLfulus** [rancher/rancher#9796]
We started using Docker Hub to save our images and we configured webhooks to trigger a Rancher service upgrade. Everything works fine except that we can't use versioning on the containers anymore since tag doesn't support wildcards/regex.

Is this planned? Because webhooks for service upgrade becomes useless in this scenario. 

Thanks!

**Comment by loganhz** [comment]
related to https://github.com/rancher/rancher/issues/8446
