### ISSUE TITLE
[alidns catalog] Host DNS records won't remove after the alidns service was deleted.

### ISSUE THREAD

**Issue by Tracy1994** [rancher/rancher#9797]
**Rancher versions:**
rancher/server: 1.6.8-rc7
rancher/agent: 1.6.8-rc7
aliyun domain console: https://dc.aliyun.com/tcparse/dns.htm?init=false&dtoken=q9jeqFjNxEteQZ_Go

**Steps to Reproduce:**
1. Launch alidns catalog.
2. Stop and delete alidns service.
3. Launch alidns catalog again.

**Results:**
1. Alidns launch success.
2. Host records don't removed.
![image](https://user-images.githubusercontent.com/18595707/29877348-f055ddca-8dd1-11e7-8af0-e245e020af4c.png)
agent logs:
> ime="2017-08-30T14:17:24Z" level=info msg="Received event: Name: storage.volume.remove, Event Id: 2ae8b3ca-706d-4bc4-8963-060f873ef215, Resource Id: 1vspm63" 
time="2017-08-30T14:17:24Z" level=error msg="Error getting container info." error=EOF id=bdcdfb2e36ea873132689dbffe65bd29cc0a4d858ab9cc5a30b4860683f4cf31 
time="2017-08-30T14:17:24Z" level=info msg="rancher id [1vspm63]: Volume with name [] has been removed" 
time="2017-08-30T14:17:24Z" level=info msg="Reply: 2ae8b3ca-706d-4bc4-8963-060f873ef215, storage.volume.remove, 1vspm63:volumeStoragePoolMap" 

3. Launch fail because domain had been occupied.
logs:
> 2017/8/30 下午1:03:25time="2017-08-30T05:03:25Z" level=info msg="Healthcheck handler is listening on :1000"
2017/8/30 下午1:03:25time="2017-08-30T05:03:25Z" level=fatal msg="Failed to ensure upgrade: Alibaba Cloud API call has failed: Aliyun API Error: RequestId:  Status Code: -1 Code: AliyunGoClientFailure Message: json: cannot unmarshal string into Go struct field RecordType.TTL of type int32"
2017/8/30 下午1:03:40time="2017-08-30T05:03:40Z" level=info msg="Starting Rancher External DNS service v0.7.3"
2017/8/30 下午1:03:40time="2017-08-30T05:03:40Z" level=info msg="Configured AliDNS with zone 'cnrancher.cn'" 

**expectation：**
Host records will be removed and alidns launch successfully.

@yasker

**Comment by yasker** [comment]
I think it will take some time to remove. Can you double check?

**Comment by Tracy1994** [comment]
Check it already. The problem should be alidns service cannot syncs up with rancher-metadata service events.

**Comment by loganhz** [comment]
Aliyun DNS API changed these days... I have a [PR](https://github.com/rancher/external-dns/pull/89) to fix it.

**Comment by loganhz** [comment]
@yasker I guess we can close this issue. it's working now
