### ISSUE TITLE
View local volumes in UI

### ISSUE THREAD

**Issue by jonaskello** [rancher/rancher#9802]
**Rancher versions:**
rancher/server: 1.6.7

I would like to be able to view local volumes in the UI. 

In the menu option `Infrastructure > Storage` the local volumes are not visible and I find no local driver to install. The information I'm looking for is the output of `rancher volume ls -a` filtered to local volumes.

**Comment by vincent99** [comment]
Local volumes are specifically excluded because they are numerous and effectively meaningless random IDs that you'd have no way to correlate to anything else in the UI.

**Comment by jonaskello** [comment]
FWIW, that is not entirely true. My use-case is named local volumes and they have meaningful names. For example `docker -v my_volume:/my_volume ...` will create a local volume named `my_volume`. 

Named local volumes is also the only way to work with volumes if your hosts don't have access to a storage solution like NFS or something like that.
