### ISSUE TITLE
Why one of host down, then the entire site down?

### ISSUE THREAD

**Issue by zhangalex** [rancher/rancher#9804]
I deploy a site on two hosts with two containers, and without health check because I don't want to configure a map port (it likely that if need health check then you have to expose a port?). The big problem is that if I have a problem with part of the system, for example a host down, the entire site down !!!

Could you please tell me why have such design?

|Versions|Rancher `v1.6.7` Cattle: `v0.183.5` UI: `v1.6.17` |

**Comment by HenryTheSir** [comment]
You need HC for Container failover. The Port must not be exposed.

**Comment by zhangalex** [comment]
@HenryTheSir    But if I expose the port, the containers will always display as 'initialing' after HC set.

**Comment by cjellick** [comment]
You do not need to publish a port for healthchecks. The healthchecks are done over the rancher overlay networks and all ports are accessible to the HC container.
