### ISSUE TITLE
UI Issues in Add Service/Container

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#9805]
**Rancher versions:** master 2.0 8/31

**Results:**

- [x] Upgrade Policy section, the pre-pull image radio buttons have too much space between them.  If you look at the command section you will see the radio buttons there look nice in comparison.
![image](https://user-images.githubusercontent.com/11514927/29946610-e9126388-8e5a-11e7-83a4-b1ea3d72fadc.png)

- [x] Host Scheduling - the min scale/max scale section is confusing?
![image](https://user-images.githubusercontent.com/11514927/29946661-0f58d9fa-8e5b-11e7-83a1-8b7bb5316d95.png)

- [x] Volumes Section - weird to have a + and drop-down button icon.  Especially since the + doesn't actually add a line if I click on it?  Maybe just eh drop-down icon would be good?
![image](https://user-images.githubusercontent.com/11514927/29946725-4c51e5cc-8e5b-11e7-8ef2-9c7649a7fb08.png)

- [ ] Drop-down that have nothing in them, are showing this little thin drop-down.
![image](https://user-images.githubusercontent.com/11514927/29946852-cc4320ac-8e5b-11e7-9d78-62c3169e5e63.png)

- [x] Upgrade Policy - Replacement behavior options and text are not aligned
![image](https://user-images.githubusercontent.com/11514927/29946897-f7289202-8e5b-11e7-9b43-2ce9359aa281.png)

- [x] In all sections - Sometimes the - is attached to the field and other times it's not.  We should pick one and have it be consistent across the whole page.
![image](https://user-images.githubusercontent.com/11514927/29947001-7764faa0-8e5c-11e7-8595-907c796046b4.png)
![image](https://user-images.githubusercontent.com/11514927/29946958-3f77a9bc-8e5c-11e7-94e8-48140b8e3f32.png)
![image](https://user-images.githubusercontent.com/11514927/29946973-518f28a0-8e5c-11e7-91c1-9657c33cbf36.png)
![image](https://user-images.githubusercontent.com/11514927/29946979-572a1388-8e5c-11e7-801a-e22626794055.png)
![image](https://user-images.githubusercontent.com/11514927/29946981-5c8eb66c-8e5c-11e7-8d3d-33fae40bc044.png)

You probably get the idea :).

- [x] Networking - the Set a specific hostname edit field is really small with really small text?
![image](https://user-images.githubusercontent.com/11514927/29947099-cc786838-8e5c-11e7-9619-d581d94c866d.png)

- [x] Host Template page - the templates are messed up
![image](https://user-images.githubusercontent.com/11514927/29985275-2057d7de-8f13-11e7-8f73-9ea631a5c039.png)
![image](https://user-images.githubusercontent.com/11514927/29985293-3b23206e-8f13-11e7-8061-e68654019d28.png)

**Comment by lvuch** [comment]
https://github.com/rancher/ui/pull/1337

**Comment by tfiduccia** [comment]
Version - master 9/7
Verified fixed
