### ISSUE TITLE
[rancher-abs] Cannot get mate-data when using classic network.

### ISSUE THREAD

**Issue by Tracy1994** [rancher/rancher#9807]
**Rancher versions:**
rancher/server:1.6.7
catalog: https://github.com/thxCode/rancher-catalog.git
branch: aliyun-bs
network: classic

**Steps to Reproduce:**
1. Launch rancher-abs service.
2. Add stack.
3. Add server.
4. Set volume and volume driver.
5. Create server.

**Results:**
1. Fail to create disk.
2. Fail to get instance Id.
3. Fail to curl 100.100.100.200

**Expectation**
1. Success in getting instance ID.
2. Or remind  user "only VPC network can mount disk through rancher-abs server".

@yasker  @thxCode 
#9194

**Comment by thxCode** [comment]
I will add a notice on the [catalog](https://github.com/thxCode/rancher-catalog/tree/aliyun-bs), meanwhile, I add a validation on [storage](https://github.com/thxCode/storage/tree/aliyun-bs) when installing.

**Comment by gitlawr** [comment]
Clarified that only VPC model is supported in the documentation.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
