### ISSUE TITLE
Cannot delete service links if there are multiple links to the same service

### ISSUE THREAD

**Issue by EyMaddis** [rancher/rancher#9810]
**Rancher versions:**
rancher/server: 1.6.7
rancher/agent: v1.2.5

**Infrastructure Stack versions:**
healthcheck: v0.3.1
ipsec: how to find?
network-services: manager=v0.7.4, metdata=v0.9.2
scheduler: v0.8.2

**Docker version: (`docker version`,`docker info` preferred)**
```
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Wed Jan 11 00:23:16 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Wed Jan 11 00:23:16 2017
 OS/Arch:      linux/amd64
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

```
NAME="RancherOS"
VERSION=v0.8.1
ID=rancheros
ID_LIKE=
VERSION_ID=v0.8.1
PRETTY_NAME="RancherOS v0.8.1"
HOME_URL="http://rancher.com/rancher-os/"
SUPPORT_URL="https://forums.rancher.com/c/rancher-os"
BUG_REPORT_URL="https://github.com/rancher/os/issues"
BUILD_ID=
```
uname: `4.9.12-rancher`

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle v0.183.5

**Steps to Reproduce:**
Setup Stack with `docker-compose.yml`:
```version: '2'
services:
  ubuntu:
    image: ubuntu:14.04.3
    stdin_open: true
    tty: true
    links:
    - httpbin:httpbin1
    - httpbin:httpbin2
    labels:
      io.rancher.container.pull_image: always
  httpbin:
    image: citizenstig/httpbin
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
```

and `rancher-compose.yml`
```
version: '2'
services:
  ubuntu:
    scale: 1
    start_on_create: true
  httpbin:
    scale: 1
    start_on_create: true
```

Then remove the link `httpbin2` with an upgrade. Both API and UI calls lead to the same result.
Finish the upgrade.

**Results:**
The removed link `httpbin2` is still shown in the list of links in the service overview and on the upgrade view.

**Workaround:**
It is possible to remove both httpbin links at once, this will result in one of the links being deleted.

Related to #9781

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
