### ISSUE TITLE
Rancher image won't start on centos minimal 

### ISSUE THREAD

**Issue by CrazybernieNL** [rancher/rancher#9811]
**Rancher versions:**
rancher/server:  Latest version
rancher/agent:1.25

Docker version:
Server Version: 1.12.6
Storage Driver: devicemapper
 Pool Name: docker-253:0-67161923-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 323.4 MB
 Data Space Total: 107.4 GB
 Data Space Available: 48.38 GB
 Metadata Space Used: 974.8 kB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.147 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-514.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 272
Total Memory: 78.38 GiB
Name: NL-GK-PHINODE04
ID: G3WJ:2FZB:DBMM:YM44:ZZW4:7KBT:MHVW:SIZN:DKJ7:5DI6:H44W:X25H
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
3.10.0-514.el7.x86_64
Centos Minimal install 
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare metal install Xeon Phi Knights Landing --> We're planning to deploy specific images that have been designed to use the Xeon phi capabilities. 

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Rancher HA environment external database
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes 
**Steps to Reproduce:**
sudo docker run --rm --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.2.5 http://192.168.201.52:8080/v1/scripts/[Secret]

**Results:**
runtime stack:
runtime.throw(0x1817d50, 0x17)
        /usr/local/go/src/runtime/panic.go:527 +0x90
runtime.procresize(0x110, 0x0)
        /usr/local/go/src/runtime/proc1.go:2713 +0xb0f
runtime.schedinit()
        /usr/local/go/src/runtime/proc1.go:72 +0x110
runtime.rt0_go(0x7ffc1bf98138, 0x5, 0x7ffc1bf98138, 0x4003a0, 0x1106b9c, 0x0, 0x500000000, 0x7ffc1bf98138, 0x46e510, 0x4003a0, ...)
        /usr/local/go/src/runtime/asm_amd64.s:109 +0x132

Any suggestions as to what i am doing wrong ?

**Comment by cjellick** [comment]
Is that the entirety of the logs from the agent? If not, can you add the rest?

**Comment by superseb** [comment]
Please reply so we can reproduce and fix this.
