### ISSUE TITLE
AD: GetIdentity errors out with "More than one result found"

### ISSUE THREAD

**Issue by prachidamle** [rancher/rancher#9813]
**Rancher versions:**
rancher/server: 1.6.8 with AD auth ON

Pre-requisites:
This affects only such AD setups that have multiple objects under the User records - most likely mobile and activesync objects.

**Steps to Reproduce:**
usecase1) Either a setup that is upgraded to 1.68 OR a fresh install of 1.6.8  
a. AD auth is turned ON
b. Edit some environment
c. Search a user to be added as member of this environment, search succeeds.
d. Save to add the newly searched user - this fails and logs show following error:
`[.a.a.i.e.ExternalServiceAuthProvider] getIdentity: Got error from Auth service. statusCode: 500 
level=error msg="SearchIdentities Failed with error More than one result found"`

usecase2) A setup with K8s that is upgraded to 1.68
a. AD auth is turned ON
b. Using kubectl remotely having kubeconfig created before upgrade, gives error 
c. rancher/server logs show errors:
`time="2017-08-31T20:07:13Z" level=error msg="More than one result" 
time="2017-08-31T20:07:13Z" level=error msg="Error looking up token." error=`

**Comment by prachidamle** [comment]
Root cause: "More than one result" is logged when ldap search yields more than one object.

GetIdentity is called in both usecases above. This makes a ldap search that  is looking for (objectClass=*) and also looks at entire subtree of a given object base.

In case of the AD where there exist multiple objects under the User records - most likely mobile and activesync objects, the above search yields multiple objects and errors out.

Fix is to only look at specific objectClass (user or group), and search for one object and not the entire subtree scope.

**Comment by deniseschannon** [comment]
Available in v1.6.9-rc1. Verified with the user that this corrects their issue with their AD server.
