### ISSUE TITLE
Typo in Steps to Rollback, release note v1.6.8

### ISSUE THREAD

**Issue by Fufuhu** [rancher/rancher#9814]
Hi,

This issue is not related to the Rancher software, itself,
but related to the documentation.

I found a typo in Steps to Rollback section, release note v1.6.8.

In the top of the section, it says We support rolling back to Rancher v1.6.7 from Rancher v1.6.8.
However, in the content it says rollback from v1.6.8 to v1.6.5, but
I think it's correct to say rollback to v1.6.7.
This might cause misunderstand.

**Comment by deniseschannon** [comment]
Thanks for pointing that out! I've updated it.
