### ISSUE TITLE
AD bind fails if password contains colon ':'

### ISSUE THREAD

**Issue by mrajashree** [rancher/rancher#9815]
**Rancher versions**
Rancher server:v1.6.8

**Steps to Reproduce:**
1. Login as a user with password containing ':'

**Results:**
```
time="2017-09-02T01:24:43Z" level=info msg="Now generating Ldap token"
time="2017-09-02T01:24:44Z" level=error msg="GetToken failed with error: Error in ldap bind: LDAP Result Code 49 \"Invalid Credentials\": 80090308: LdapErr: DSID-0C09042F, comment: AcceptSecurityContext error, data 52e, v2580\x00"
2017-09-02 01:24:44,442 ERROR [:] [] [] [] [tp1020391880-93] [.a.a.i.e.ExternalServiceAuthProvider] Got error from Auth service. statusCode: 401, message: Error in ldap bind: LDAP Result Code 49 "Invalid Credentials": 80090308: LdapErr: DSID-0C09042F, comment: AcceptSecurityContext error, data 52e, v2580
```

**Expected**
Login should be successful

**Comment by thomasbergmann** [comment]
same here, seems already ldap bind is failing. no colon in bind user password, but other special characters. rancher/server:stable 1.6.7 is fine.

**Comment by mrajashree** [comment]
@thomasbergmann can you please specify what other special characters and also provide rancher server logs for bind failure?

**Comment by sangeethah** [comment]
Scenario 1:
Tested with fresh install of rancher-server - v1.6.9-rc2

1. Login as a user with password containing ':'

Log in succeeds.

2. Login as a user with password containing following characters ```" !"#$%&'()*+,-./:;<=>?@[\]^_`{|}~"```

Log in succeeds.

Scenario 2:

Install rancher-server - v1.6.8

1. Login as a user with password containing ':'
Log in fails and user is presented with error message - "Username or Password incorrect."


2. Login as a user with password containing following characters ```" !"#$%&'()*+,-./:;<=>?@[\]^_`{|}~"```
Log in fails and user is presented with error message - "Username or Password incorrect."

Upgrade rancher-server to  v1.6.9-rc2
1. Login as a user with password containing ':'

Log in succeeds.

2. Login as a user with password containing following characters ```" !"#$%&'()*+,-./:;<=>?@[\]^_`{|}~"```

Log in succeeds.
