### ISSUE TITLE
[rancher-abs][storage][driver options] Add driver options should be from select box. 

### ISSUE THREAD

**Issue by Tracy1994** [rancher/rancher#9816]
**Rancher versions:**
rancher/server:1.6.7
catalog: https://github.com/thxCode/rancher-catalog.git
branch: aliyun-bs
network: VPC

**Steps to Reproduce:**
1. Launch rancher-abs service.
2. Infrastructure->Storage.
3. Add volume.
4. Driver options -> add pairs.

**Results:**
1. User only can set the keys and values from input box but they don't know what keys they can have, what the edges are.etc

**expectation**
1. User select the keys and values from select box.

@yasker  @thxCode 
#9194

**Comment by yasker** [comment]
This can be pretty big enhancement since it's not what our storage driver supported today. But it will have better user experience if we can do this.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
