### ISSUE TITLE
[rancher-abs][storage]Delete volume from aliyun console, volume state not change.

### ISSUE THREAD

**Issue by Tracy1994** [rancher/rancher#9817]
**Rancher versions:**
rancher/server:1.6.7
catalog: https://github.com/thxCode/rancher-catalog.git
branch: aliyun-bs
network: VPC

**Steps to Reproduce:**
1. Launch rancher-abs service.
2. Add stack.
3. Add server.
4. Set volume and volume driver.
5. Volume is created and its state is active.
6. Delete volume from aliyun console.

**Results:**
1. Volume state still active on storage page.
2. No error give out from the server mount the disk.

**Expectation**
1. Volume state should be inactive.
2. Error should be gave out from the server that mount the disk.
@yasker  @thxCode 
#9194

**Comment by yasker** [comment]
@Tracy1994 

Is the disk still mounted on the host after volume was deleted?
