### ISSUE TITLE
[rancher-abs][upgrade]Volume has two path in the same container.

### ISSUE THREAD

**Issue by Tracy1994** [rancher/rancher#9818]
**Rancher versions:**
rancher/server:1.6.7
catalog: https://github.com/thxCode/rancher-catalog.git
branch: aliyun-bs
network: VPC

**Steps to Reproduce:**
1. Launch rancher-abs service.
2. Add stack.
3. Add server.
4. Set volume and volume driver.
5. Volume is created and its state is active.
6. Upgrade the volume path.

**Results:**
1. On storage page, that volume shows two path.
![image](https://user-images.githubusercontent.com/18595707/30009842-f069f550-915d-11e7-9347-0bd85b8c1928.png)

**Expectation**
1. Volume path update completed when the service in this state.
![image](https://user-images.githubusercontent.com/18595707/30009922-998279c8-915e-11e7-808c-647d56e363fa.png)

@yasker  @thxCode 
#9194

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
