### ISSUE TITLE
[rancher-abs][HA] Fail to switch the volume from one host to another host.

### ISSUE THREAD

**Issue by Tracy1994** [rancher/rancher#9820]
**Rancher versions:**
rancher/server:1.6.7
catalog: https://github.com/thxCode/rancher-catalog.git
branch: aliyun-bs
network: VPC

**Steps to Reproduce:**
1. Launch rancher-abs service.
2. Add two hosts agent1 and agent2.
3. Launch wordpress catalog.
4. Three services of wordpress deploy on this two host randomly.
5. Upgrade agent2 and add a volume in mariadb service.
6. Disk create, attach and mount successfully.
7. Delete agent2.

**Results:**
1. Mariadb launch fail because it cannot find its volume.

**Expectation**
1. All the services of wordpress switch to agent1 and launch normally.
2. Volume switch from agent2 to agent1.

@yasker  @thxCode 
#9194

**Comment by Tracy1994** [comment]
Only abs shows this problem, ebs is normal.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
