### ISSUE TITLE
Kubernetes environment stuck at "Starting services (4 of 12)

### ISSUE THREAD

**Issue by Parth6288** [rancher/rancher#9824]
**Rancher versions:**
rancher/server: Stable 
rancher/agent: v1.2.5

**Infrastructure Stack versions:**
healthcheck: v0.3.1
ipsec: 
network-services:  v0.11.7
scheduler:
kubernetes (if applicable): v1.7.2-rancher7

**Docker version: (`docker version`,`docker info` preferred)**
 Docker version 1.12.6, build 88a4867/1.12.6
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Hyper-V

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes
**Steps to Reproduce:**
1) installed Rancher following the official guidelines
2) added 3 hosts in the K8s environment

**Results:**
The services are stuck at installing. Attached is service stack status screenshot.
![capture](https://user-images.githubusercontent.com/16204776/30030967-251fe9cc-91ad-11e7-9176-23d7675e2b3d.PNG)
![2](https://user-images.githubusercontent.com/16204776/30031009-461c86bc-91ad-11e7-828a-53156e8c21ab.PNG)

**Comment by aemneina** [comment]
Healthcheck not being happy indicates the overlay network isn't operating properly. Do you have UDP ports, 500 and 4500, open between the agent hosts?

**Comment by Parth6288** [comment]
@aemneina Yes it is. I set up the whole environment on Azure using CentOS7 VM and facing the same issues. The infrastructure stack will not become active. For testing further i created similar set up using Ubuntu16.04 and it worked like a charm. Not sure if there is an issue with the CentOS7 with Rancher stable version.

**Comment by chadha** [comment]
@aemneina me too,
Did you find a solution for that ?

**Comment by aemneina** [comment]
@chadha yeah, you should make sure udp ports between the agent hosts.

**Comment by superseb** [comment]
Please report if there are still issues in Kubernetes, this seems to be related to unhealthy infrastructure services that Kubernetes needs.
