### ISSUE TITLE
422 status code from API

### ISSUE THREAD

**Issue by ivo5307** [rancher/rancher#9826]
FATA[0006] Bad response statusCode [422]. Status [422 status code 422]. Body: [code=MissingRequired, fieldName=namespace, baseType=error] from [http://vagrant_ip:8080/v2-beta/projects/1a7/kubernetesstacks] 

http://rancher.com/docs/rancher/v1.2/en/cli/commands/#rancher-catalog-reference
does not describe such fieldname. Could you update docs?
Or at least give me friendly help here

**Comment by aemneina** [comment]
@ivo5307 This seems to be missing a lot of information. It looks like youre trying to do something to, or with, kubernetes, possibly using the rancher CLI? Can you explain what youre trying to do and with what tools? Versions of the software youre using would also be helpful.

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
