### ISSUE TITLE
lb-controller (haproxy) seems to leak memory

### ISSUE THREAD

**Issue by 0ff** [rancher/rancher#9829]
**Rancher versions:**
rancher/server:v1.6.7
rancher/agent:v1.2.5

**Infrastructure Stack versions:**
rancher/lb-service-haproxy:v0.7.6

**Docker version: (`docker version`,`docker info` preferred)**
```
Containers: 24
 Running: 24
 Paused: 0
 Stopped: 0
Images: 25
Server Version: 17.03.1-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.40-rancher
Operating System: RancherOS v1.0.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.797 GiB
Name: ip-10-100-200-40.eu-central-1.compute.internal
ID: XLSM:ZUGQ:UDBB:6KNN:LO7C:ZOOY:XJBE:GDNV:WDG7:7MY5:DLUS:2IFC
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
4.9.40-rancher
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher, external DB
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
Deploy rancher loadbalancer, monitor memory usage, create traffic on the LB
**Results:**
Expected: Memory does not increase over time
Actual: Memory increases drastically over time

After deploying rancher, we've noticed quite a dramatic increase in memory over time for all of our loadbalancer-containers:
![memory](https://user-images.githubusercontent.com/1755213/30087579-c5dec41a-92a1-11e7-95eb-28bb6254a85d.png)

At first we thought HAProxy could be the problem, but after checking the container itself it became apparent that HAProxy only consumes a minor portion of the whole memory:
```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU     TIME+ COMMAND
    1 root      20   0    4380    668    580 S   0.0   0:02.51 tini
    9 root      20   0  262632  35416  26548 S   0.0   0:38.58 lb-controller
   30 root      20   0  174428   3172   2012 S   0.0   1:11.57 rsyslogd
   69 haproxy   20   0   63924  21928   3340 S   0.0   7:16.00 haproxy
```

As you can see, of the total memory, `haproxy` only takes about 12% (please note that the image does not show the container at the same point in time).
This raises the question: why does `lb-controller` use that much memory and how can this be mitigated?

As for `rsyslogd`, our current workaround was to disable the logs in the custom haproxy.cfg (i.e. remove `log 0.0.0.0:8514 local0`) and that seems to have helped a bit at least.

Any input would be appreciated, thanks!

**Comment by jwoertink** [comment]
I think my app may be experiencing the same thing. We've been battling with our app going down, and restarting hosts and containers has been the only thing that seemed to fix it. It felt like a memory leak, but we were never able to pin point where. What sort of info could I look at to confirm if this is the same issue?

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
