### ISSUE TITLE
Feature request: Tail more of a container's log

### ISSUE THREAD

**Issue by jonaskello** [rancher/rancher#9831]
**Rancher versions:**
rancher/server: v1.6.7

One of the most common operations I do is viewing the log a container. Most of the time to find errors. Today only a few lines of the log are visible so if there is a long stack trace it is not possible to see the root cause.

I would like to be able to enter a number and have that amount of tail of the log, similar to `docker logs --tail 1000 my_container`.

This request is similar to #5794 but with a tail instead of seeing all log (which I think is unpractical). In  #5794 it is suggested that you go to the host. However, that would require you to find the private, key, ssh into the host, find the correct container id, do a `docker logs --tail | less` etc. That seems like a lot of work to do one of the most common operations in troubleshooting a container. Rancher is on a mission to make it easier to run containers, and having this feature I think would make it easier than doing all of the aforementioned steps manually.

**Comment by aemneina** [comment]
hi @jonaskello , looks like the rancher cli provides this functionality.

```$ rancher logs --help
Fetch the logs of a container

Example:
  $ rancher logs web

Usage: rancher [global options] logs [OPTIONS] [CONTAINERNAME CONTAINERID...] or [SERVICENAME SERVICEID...]

Options:
   --service, -s     Show service logs
   --sub-log         Show service sub logs
   --follow, -f      Follow log output
   --tail value      Number of lines to show from the end of the logs (default: 100)
   --since value     Show logs since timestamp
   --timestamps, -t  Show timestamps```

**Comment by jonaskello** [comment]
Yes that `--tail` the option is exactly what I would like to have in the UI!

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
