### ISSUE TITLE
Rancher Agent stuck on "INFO: Deleting container rancher-agent"

### ISSUE THREAD

**Issue by vishnuvpotti** [rancher/rancher#9832]
Hi,

We just upgraded rancher server to v1.6.8 from v1.6.5 and then tried to add the hosts .  But I see the agent is not getting added and stuck with  "INFO: Deleting container rancher-agent"

**Rancher versions:**
rancher/server: v1.6.8
rancher/agent: v1.2.6

**Infrastructure Stack versions:**
healthcheck:v0.3.3
ipsec:v0.11.9
network-services:v0.7.8
scheduler:v0.8.2
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
Containers: 9
 Running: 0
 Paused: 0
 Stopped: 9
Images: 1
Server Version: 17.06.0-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.26.2.el7.x86_64
Operating System: Red Hat Enterprise Linux
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.899GiB
Name: Linuxmachine
ID: DOQP:GFMQ:YAYV:PMNJ:W732:Z2AK:XCG7:OQM6:HZFU:KDG6:KG5Z:WWEG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: http://mycredentails@myproxy:8080/
Https Proxy: https://mycredentails@myproxy:8080/
No Proxy: localhost,127.0.0.1
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="Red Hat Enterprise Linux Server"
VERSION="7.3 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="7.3"
PRETTY_NAME="Red Hat Enterprise Linux"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.3:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.3
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.3"

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** Hyper-V VM.

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node, internal DB
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
1) Logged in to Rancher and selected Cattle Environment
2) Clicked on Add host button
3) Copied the code from "Copy, paste, and run the command below to register the host with Rancher:" section to add a agent.
4) In the linux machine, executed this code .

**Results:**
```
 ⚡ root@linuxmachine  sudo docker run --rm --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.2.6 http://10.xx.xxx.xxx:8080/v1/scripts/864025A75E10EC24A110:1483142400000:Q58mmOLnMuQ6qiddb0PL7vwU
Unable to find image 'rancher/agent:v1.2.6' locally
v1.2.6: Pulling from rancher/agent
b3e1c725a85f: Already exists
6a710864a9fc: Already exists
d0ac3b234321: Already exists
87f567b5cf58: Already exists
063e24b217c4: Already exists
d0a3f58caef0: Already exists
16914729cfd3: Already exists
2ce3828c0b9d: Pull complete
7df47a98fc4b: Pull complete
Digest: sha256:a68afd351c7417e6d66a77e97144113ceb7a9c3cdd46fb6e1fd5f5a5a33111cd
Status: Downloaded newer image for rancher/agent:v1.2.6

INFO: Running Agent Registration Process, CATTLE_URL=http://10.xx.xxx.xxx:8080/v1
INFO: Attempting to connect to: http://10.xx.xxx.xxx:8080/v1
INFO: http://10.xx.xxx.xxx:8080/v1 is accessible
INFO: Inspecting host capabilities
INFO: Boot2Docker: false
INFO: Host writable: true
INFO: Token: xxxxxxxx
INFO: Running registration
INFO: Printing Environment
INFO: ENV: CATTLE_ACCESS_KEY=1C811499FRGDDDDD
INFO: ENV: CATTLE_HOME=/var/lib/cattle
INFO: ENV: CATTLE_REGISTRATION_ACCESS_KEY=registrationToken
INFO: ENV: CATTLE_REGISTRATION_SECRET_KEY=xxxxxxx
INFO: ENV: CATTLE_SECRET_KEY=xxxxxxx
INFO: ENV: CATTLE_URL=http://10.xx.xxx.xxx:8080/v1
INFO: ENV: DETECTED_CATTLE_AGENT_IP=10.1x.1xx.2xx
INFO: ENV: RANCHER_AGENT_IMAGE=rancher/agent:v1.2.6
INFO: Deleting container rancher-agent
INFO: Deleting container rancher-agent
INFO: Deleting container rancher-agent
INFO: Deleting container rancher-agent
INFO: Deleting container rancher-agent
INFO: Deleting container rancher-agent
INFO: Deleting container rancher-agent
INFO: Deleting container rancher-agent
INFO: Deleting container rancher-agent
INFO: Deleting container rancher-agent
INFO: Deleting container rancher-agent
INFO: Deleting container rancher-agent
INFO: Deleting container rancher-agent
```

**Comment by cjellick** [comment]
Can you post the results of `docker ps -a` and `docker inspect rancher-agent` (with any sensitive info removed)?
Wondering if the container named `rancher-agent` is in an undeletable state.

**Comment by superseb** [comment]
@vishnuvpotti If you can provide the needed info we can investigate.
