### ISSUE TITLE
[storage]Should not allow user create two volumes which have the same name.

### ISSUE THREAD

**Issue by Tracy1994** [rancher/rancher#9834]
**Rancher versions:**
rancher/server: v1.6.8
network: PVC
OS: Ubuntu 16.04

**Steps to Reproduce:**
1. Deploy ceph service.
2. Launch ceph-rbd service.
3. To storage page.
4. Create a volume call "va".
5. Create another volume call "va" again.
6. Launch a service which mount "va" volume.

**Results:**
1. Succeed created two volume call "va".
2. Fail to launch.
>Could not process named volume va. More than one volume with that name exists.

**Expectation**
1. Remind user "volume called va had already exist" when they create the second "va" volume.

@yasker

**Comment by yasker** [comment]
Can you share screenshot?

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
