### ISSUE TITLE
rancher load balancer doesn't check for duplicate paths

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#9835]
**Rancher versions:**
rancher/server: v1.6.7
rancher/agent: v1.2.5

**Steps to Reproduce:**
1. Create two services
2. create a lb pointing to the two services using two selector rules
    selector rules use the same path, in this case `/`

**Results:**
LB round robins between them.

**Expected**
a warning or error preventing the unintended clash.

[rancher-compose.txt](https://github.com/rancher/rancher/files/1281830/rancher-compose.txt)

[docker-compose.txt](https://github.com/rancher/rancher/files/1281829/docker-compose.txt)

**Comment by deniseschannon** [comment]
Currently, this is by design. 

We expect the users to set up their hostname routing rules to map according to their services. If there is more than 1 service in a path, the load balancer will round robin between the services as expected.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
