### ISSUE TITLE
CLI: exec option "--user" not working

### ISSUE THREAD

**Issue by marvinwankersteen** [rancher/rancher#9836]
**Rancher versions:**
```
rancher/server: v1.6.7
rancher/agent: v1.2.5
```

**Infrastructure Stack versions:**
```
healthcheck: v0.3.1
ipsec: v0.11.7
network-services: v0.7.7
scheduler:
kubernetes (if applicable):
```

**Docker version: (`docker version`,`docker info` preferred)**
```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:34:45 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:34:45 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
Debian 8.8
4.9.0-0.bpo.2-amd64
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
`KVM`

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
`Single node with external DB`

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
`Cattle`

**Rancher-CLI version**
`rancher version v0.6.3`

**Steps to Reproduce:**
Run rancher exec with a defined user IN container.

```
$ rancher exec -ti --user www-data nextcloud/web php occ -V
$ rancher exec -ti --user www-data nextcloud/web id
$ rancher exec -ti -u www-data nextcloud/web id
$ rancher exec -ti -u 33 nextcloud/web id
```

**Results:**
```
FATA[0000] Not found: www-data
FATA[0000] Not found: www-data
FATA[0000] Not found: www-data
FATA[0000] Not found: 33
```

Some other command without the `--user`:
```
$ rancher exec -ti nextcloud/web id
uid=0(root) gid=0(root) groups=0(root)
```

The command on the host directly with docker exec:
```
$ docker exec -ti -u www-data r-Nextcloud-web-1-1f6cd87d php occ -V
Cloud version 12.0.2

$ docker exec -ti -u www-data r-Nextcloud-web-1-1f6cd87d id
uid=33(www-data) gid=33(www-data) groups=33(www-data)
```

Is this a bug or am I doing something wrong?

**Comment by jjscarafia** [comment]
Any news on this? Same happens to me. Thanks!

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.

**Comment by sbarsotti** [comment]
I have the same problem and I solved it as follows:

Command:
```
$ rancher exec -it --user=root grafana / grafana id
```
Results:
```
uid=0(root) gid=0(root) groups=0(root)
```

Options in ``rancher exec`` are not exactly the same as those of docker, contrary to what is mentioned in the Rancher-Cli documentation.
you must add a **=** between the **--user** option and the **username**.
