### ISSUE TITLE
kube-dns does not start correctly

### ISSUE THREAD

**Issue by matthijsvdr** [rancher/rancher#9841]
**Rancher versions:**
rancher/server: 1.6.7
rancher/agent: 1.2.5

**Infrastructure Stack versions:**
All latest stable: healthcheck, ipsec, network-services, scheduler
kubernetes (if applicable): v1.7.2-rancher7
**Docker version: (`docker version`,`docker info` preferred)**
1.12.6
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single rancher, external db

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes
**Steps to Reproduce:**
Reboot kubernetes
**Results:**

The kubernetes dns pod fails. This happens almost every reboot.

error: 

> MountVolume.SetUp failed for volume "kube-dns-token-lgqnz" : secrets "kube-dns-token-lgqnz" not found Error syncing pod Terminated: Completed

**Comment by joshwget** [comment]
If I remember correctly this is already fixed in newer versions of Rancher. @alena1108?

**Comment by jsco2t** [comment]
Hitting the exact same issue - FWIW. Took a long time to work out why `service` name resolution wasn't behaving as expected inside a `k8s` cluster.

**Comment by rafaelri** [comment]
I've managed to get it running by exporting its yml, removing it and recreating it on kube-system namespace.

**Comment by superseb** [comment]
Should be fixed since v1.6.8: https://github.com/rancher/rancher/issues/9734
