### ISSUE TITLE
Can't find documentation on rancher service proxy urls

### ISSUE THREAD

**Issue by frankh** [rancher/rancher#9842]
There seems to be a way to access services using rancher as a proxy, as used by e.g. kubernetes at: https://rancher.example.com/r/projects/1a2486/kubernetes-dashboard:9090/#!/workload

However, I can't find any documentation on how this works.

Can I use this for my own internal services? Does the service name have to be unique or can I specify the stack somehow?

**Comment by frankh** [comment]
@superseb are you still working on this? Would still love an answer, and also if this is still a feature in rancher 2?

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
