### ISSUE TITLE
[RFE] UI when launching stack, have option to validate yaml before submitting it

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#9843]
**Rancher versions:**
rancher/server: v1.6.7

**Steps to Reproduce:**
when launching a stack with issues (like malformed yaml) have the rancher UI validate the yaml before attempting to launch it. The issue today is you'd have to launch the stack only to have it bail.

**Comment by vincent99** [comment]
JS YAML parsers are significant size and largely fail to address the real problem, which is "is rancher-compose-executor going to complain about this file".  An API call to run the input through and actually validate against the actual code that needs to interpret it would be much more useful.
