### ISSUE TITLE
Windows volume mount issue

### ISSUE THREAD

**Issue by linusyong** [rancher/rancher#9846]
**Rancher versions:**
rancher/server: v1.6.8
rancher/agent: v0.6.0 (Windows agent.exe)

**Infrastructure Stack versions:**
healthcheck:  - NA -
ipsec: - NA -
network-services: - NA -
scheduler: - NA -
kubernetes (if applicable):- NA -

**Docker version: (`docker version`,`docker info` preferred)**
```
PS C:\tmp> docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 12
Server Version: 17.06.1-ee-2
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.1593.amd64fre.rs1_release.170731-1934)
Operating System: Windows Server 2016 Standard
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 1.999GiB
Name: nt228drnch01
ID: 7VHT:ASNI:NOR4:HMJT:QJOJ:QUAQ:C55H:2WLN:IYRV:VVL6:7MVA:AFNA
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 10.16.193.141:9000
 127.0.0.0/8
Live Restore Enabled: false
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
Windows Server 2016:

PS C:\tmp> [System.Environment]::OSVersion.Version
Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      14393  0
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**: Hyper-V

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**: single node rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**: Windows

**Steps to Reproduce:**
*  Install `docker-compose` on Windows the version information:
   ```
   PS C:\tmp> docker-compose version
   docker-compose version 1.12.0, build ee0f34e1
   docker-py version: 2.2.1
   CPython version: 2.7.13
   OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
   ```
*  Create a `docker-compose.yml` file:
   ```
   version: '2.1'
   services:
     epa-web-backend:
       image: test
   #    environment:
   #      - COMPOSE_CONVERT_WINDOWS_PATHS=1
       stdin_open: true
       tty: true
       network_mode: nat
       ports:
         - "8080:8080/tcp"
       volumes:
         - C:\nas\epa\:C:\nasepa\:rw
   ```
*  Run `docker-compose up`
*  The container started with `C:\nas\epa\` on the host mounted as `C:\nasepa\` in the container
*  Use the same `docker-compose.yml` (update the version to `version: '2'`) and run `rancher-compose up` (I've also tried create a catalog and launch it)

**Results:**
*  The Rancher server UI shows:
```epa-web-backend (Failed to allocate instance [container:1i178]: Bad instance [container:1i178] in state [error]: Error response from daemon: invalid volume spec "\\nas\\epa\\": invalid volume specification: '\nas\epa\')```

**Other information:**
I tried to:
*  use \\\c\nas\epa\\:\\\c\nasepa\\:rw
*  use \\\c\nas\epa:\\\c\nasepa:rw
*  use \\\nas\epa\\:\\\nasepa\\:rw
*  use \\\nas\epa:\\\nasepa:rw
*  use / instead of \
*  removed the :rw at the back
*  setting the COMPOSE_CONVERT_WINDOWS_PATHS environment variable to 1 and 0 or removing it all together in the Rancher Host (Windows)

all of the above doesn't work

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
