### ISSUE TITLE
Healthcheck intervals behaving strangely

### ISSUE THREAD

**Issue by frankh** [rancher/rancher#9849]
I have a service that has a healthcheck interval of 5000 - instead of getting hit once per 5 seconds it gets hit 29 times (all at once) every 15 seconds.

I'm running in a high availability rancher service with 3 nodes, in an environment with 4 hosts

**Rancher versions:**
rancher/server: v1.6.6
rancher/agent: v1.2.5
rancher/cli: v0.6.1

**Docker version: (`docker version`,`docker info` preferred)**
17.03.1-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
RancherOS v1.0.3 (4.9.34)

EDIT: I've realised the problem was partly to do with my healthcheck taking too long to response. Fixing it to respond instantly has the slightly more sane ~3 healthchecks every 5 seconds.

**Comment by frankh** [comment]
Going to close as I misunderstood the problem at first

The issue seems to be that every host (or n - 1 hosts) runs the healthcheck, instead of just a single host

**Comment by vincent99** [comment]
For n >= 4 hosts, health checks are scheduled to 3 (not n-1) hosts which are not running the target container.  For n < 4, they are run on all hosts (including the one running the target container).
