### ISSUE TITLE
User added to site access after upgrade is lost after rollback

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#9850]
**Rancher versions:**
rancher/server: v1.6.7 to v1.6.9-rc5

**Docker version: (`docker version`,`docker info` preferred)**

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**Ubuntu

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**GCE/DO

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**Single node

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**Cattle

**Steps to Reproduce:**
1. Create a setup in v1.6.7 with AD enabled and provide site access to two users 
2. Upgrade to v1.6.9-rc5.
3. After upgrade, add another user "testnewuser" to site access and verify that the user has access to the setup
4. Rollback to v1.6.7.

After rollback, 'testnewuser' is not listed in the site access page and does not have access to the setup.

**Comment by cjellick** [comment]
Ping @mrajashree @prachidamle. Should this be documented as a known issue? I recall us discussing that if you were to rollback from new-AD to old-AD, you would get the old AD's config because we started saving the config differently. But it looks like we did not add that as a release note.

CC @deniseschannon

**Comment by deniseschannon** [comment]
I did note it as an issue, but in the rollback section. I don't believe we'll be able to fix this for rollback due to how we handle settings. 

> Note on Rollback: If you are rolling back and have authentication enabled using Active Directory, any new users/groups added to site access on the Access Control page after the upgrade will not be retained upon rolling back. Any users added before the upgrade will continue to remain. [#9850]
