### ISSUE TITLE
Rancher server reports wrong memory usage of containers

### ISSUE THREAD

**Issue by truongdo** [rancher/rancher#9851]
**Rancher versions:**
rancher/server: 1.6.8

From the rancher UI, the memory reported for one of my containers is 327MB.
But from `docker stats`  commands, it is only 84.33MB.

**Comment by Baklap4** [comment]
Anyone on this? facing this also in 1.6.14

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
