### ISSUE TITLE
The accelerated deployment of Kubernetes  in Rancher .

### ISSUE THREAD

**Issue by hongxiaolu** [rancher/rancher#9853]
Hi, everybody. 
      At present, the deployment of Kubernetes users in China mainly rely on our customized catalog. before deployment,  need to disable library catalog, replaced by custom catalog. But custom catalog can cause a lot of problems, for example, the Infrastructure Stacks  container cannot be updated in time.  So, I made a little change to the rancher-catalog and kubernetes-package Code: replacing the original namespace (google_containers and kubernetes-helm) with variables，The default value of the variable corresponds to the original parameter. Users do not have to change the library catalog address, and only need to configure  the registry address and namespace in the environment template. I submitted two PR:https://github.com/rancher/rancher-catalog/pull/867, https://github.com/rancher/kubernetes-package/pull/95,

**Comment by hongxiaolu** [comment]
NEW  PR : https://github.com/rancher/rancher-catalog/pull/878

**Comment by yasker** [comment]
Both PR merged. Issue fixed. Wait for testing

**Comment by hongxiaolu** [comment]
@nayang777

**Comment by kingsd041** [comment]
@hongxiaolu 

Rancher version: **v1.6.11-rc1**
Docker version: **1.12.3**
provider of hosts: **Aliyun**
Environment with **3** hosts
Private Registry for Add-Ons and Pod Infra Container Image： **registry.cn-shenzhen.aliyuncs.com**
Pod Infra Container Image：**rancher_cn/pause-amd64:3.0**
Image namespace for kubernetes-helm： **rancher_cn**
Image namespace for  Add-Ons and Pod Infra Container Image： **rancher_cn**

After testing, I can use service, deployment, ingress and so on.
But. There are some error logs, I don't know why.

Here a short snapshot of today's logs

**kubernetes-kubelet logs：**
```
I1013 08:16:14.878451   27282 reconciler.go:290] Volume detached for volume "default-token-zf6x5" (UniqueName: "kubernetes.io/secret/6f727275-afed-11e7-b459-022bd22943b4-default-token-zf6x5") on node "iz2ze3tphuqvc6yu391timz" DevicePath ""
I1013 08:17:23.429484   27282 reconciler.go:212] operationExecutor.VerifyControllerAttachedVolume started for volume "default-token-zf6x5" (UniqueName: "kubernetes.io/secret/f09f6bec-afee-11e7-b459-022bd22943b4-default-token-zf6x5") pod "nginx-service-lrxzb" (UID: "f09f6bec-afee-11e7-b459-022bd22943b4")
W1013 09:04:03.042041   27282 pod_container_deletor.go:77] Container "e7867aaa254c82645d665b33c88f7e69ea370ae4a358e5509f7142753744740c" not found in pod's containers
W1013 09:04:03.043818   27282 cni.go:265] CNI failed to retrieve network namespace path: Cannot find network namespace for the terminated container "e7867aaa254c82645d665b33c88f7e69ea370ae4a358e5509f7142753744740c"
I1013 09:04:03.138140   27282 reconciler.go:186] operationExecutor.UnmountVolume started for volume "default-token-zf6x5" (UniqueName: "kubernetes.io/secret/f09f6bec-afee-11e7-b459-022bd22943b4-default-token-zf6x5") pod "f09f6bec-afee-11e7-b459-022bd22943b4" (UID: "f09f6bec-afee-11e7-b459-022bd22943b4")
I1013 09:04:03.152409   27282 operation_generator.go:535] UnmountVolume.TearDown succeeded for volume "kubernetes.io/secret/f09f6bec-afee-11e7-b459-022bd22943b4-default-token-zf6x5" (OuterVolumeSpecName: "default-token-zf6x5") pod "f09f6bec-afee-11e7-b459-022bd22943b4" (UID: "f09f6bec-afee-11e7-b459-022bd22943b4"). InnerVolumeSpecName "default-token-zf6x5". PluginName "kubernetes.io/secret", VolumeGidValue ""
I1013 09:04:03.238738   27282 reconciler.go:290] Volume detached for volume "default-token-zf6x5" (UniqueName: "kubernetes.io/secret/f09f6bec-afee-11e7-b459-022bd22943b4-default-token-zf6x5") on node "iz2ze3tphuqvc6yu391timz" DevicePath ""
W1013 09:04:04.048889   27282 cni.go:265] CNI failed to retrieve network namespace path: Cannot find network namespace for the terminated container "e7867aaa254c82645d665b33c88f7e69ea370ae4a358e5509f7142753744740c"
W1013 09:04:14.111299   27282 cni.go:265] CNI failed to retrieve network namespace path: Cannot find network namespace for the terminated container "e7867aaa254c82645d665b33c88f7e69ea370ae4a358e5509f7142753744740c"
```

**rancher-kubernetes-agent logs:**
```
2017/10/13 下午5:23:52time="2017-10-13T09:23:52Z" level=error msg="Error getting node: [iZ2ze3tphuqvc7o5nj38t8Z] by name from kubernetes, err: [nodes \"iZ2ze3tphuqvc7o5nj38t8Z\" not found]"
2017/10/13 下午5:23:54time="2017-10-13T09:23:54Z" level=error msg="Error getting node: [iZ2ze3tphuqvc6yu391timZ] by name from kubernetes, err: [nodes \"iZ2ze3tphuqvc6yu391timZ\" not found]"
2017/10/13 下午5:23:54time="2017-10-13T09:23:54Z" level=error msg="Error getting node: [iZ2ze3tphuqvc6yu391timZ] by name from kubernetes, err: [nodes \"iZ2ze3tphuqvc6yu391timZ\" not found]"
2017/10/13 下午5:23:54time="2017-10-13T09:23:54Z" level=error msg="Error getting node: [iZ2ze3tphuqvc7o5nj38t7Z] by name from kubernetes, err: [nodes \"iZ2ze3tphuqvc7o5nj38t7Z\" not found]"
```

**Comment by hongxiaolu** [comment]
Hi,@kingsd041    For this problem, my solution is to turn off swap.

**Comment by yasker** [comment]
@hongxiaolu I don't think it's SWAP. If swap is on, k8s won't start.

These errors are after k8s started.

**Comment by yasker** [comment]
Per @galal-hussein 
------
hgalal [12:57 AM] 
 this error related to the node label syncer code, it may had happened when the node is just added to rancher and not seen by kubernetes yet, however the error doesn't mean that the labels didn't sync, it means it can't find the node at first, and the code retries again multiple times until it finds the node


[12:58] 
if the node doesn't exist in k8s and all retries failed, you should see something like that in the logs: `Error syncing host labels:`

---

I think it's safe to close it.
