### ISSUE TITLE
Load Balancer refuses to properly set IP on TCP mapping after upgrade to 1.6.7

### ISSUE THREAD

**Issue by ikogan** [rancher/rancher#9854]
**Rancher versions:**
rancher/server: v1.6.7
rancher/agent: v1.2.5

**Infrastructure Stack versions:**
healthcheck: v0.3.1
ipsec: v0.11.7, 
network-services: v0.9.3
scheduler: v0.8.2

**Docker version:**
```
Client:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-32.git88a4867.el7.centos.x86_64
 Go version:      go1.7.4
 Git commit:      88a4867/1.12.6
 Built:           Mon Jul  3 16:02:02 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-32.git88a4867.el7.centos.x86_64
 Go version:      go1.7.4
 Git commit:      88a4867/1.12.6
 Built:           Mon Jul  3 16:02:02 2017
 OS/Arch:         linux/amd64
```

```
Containers: 22
 Running: 20
 Paused: 0
 Stopped: 2
Images: 97
Server Version: 1.12.6
Storage Driver: devicemapper
 Pool Name: cl_docker--docker--pool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file:
 Metadata file:
 Data Space Used: 17.89 GB
 Data Space Total: 42.69 GB
 Data Space Available: 24.79 GB
 Metadata Space Used: 6.013 MB
 Metadata Space Total: 130 MB
 Metadata Space Available: 124 MB
 Thin Pool Minimum Free Space: 4.268 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: journald
Cgroup Driver: systemd
Plugins:
 Volume: local-persist rancher-nfs local
 Network: host null bridge overlay
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Security Options: seccomp selinux
Kernel Version: 3.10.0-514.26.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 2
CPUs: 8
Total Memory: 7.541 GiB
Name: 
ID: 
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
Registries: docker.io (secure)
```

**Operating system and kernel:**
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

```
3.10.0-514.26.2.el7.x86_64
```

**Type/provider of hosts:**
KVM on Proxmox

**Setup details:**
Single node server with internal DB, 3 agent nodes.

**Environment Template:**
Cattle

**Details:**
My hosts have a floating secondary IP managed by Corosync specifically for GitLab, which includes it's SSH port. I have a Load Balancer configured with the Host IP set to that floating IP. This works for ports 80 and 443. Port 22, however, insists on being on the primary IPs of all of the hosts. Here are some screenshots:

<img width="1357" alt="screen shot 2017-09-10 at 19 28 37" src="https://user-images.githubusercontent.com/1840337/30254089-0e133af0-9661-11e7-9d8b-3c9db58de7dc.png">

<img width="460" alt="screen shot 2017-09-10 at 19 28 50" src="https://user-images.githubusercontent.com/1840337/30254091-18463054-9661-11e7-8100-e2f46e61b2b1.png">

<img width="184" alt="screen shot 2017-09-10 at 19 28 58" src="https://user-images.githubusercontent.com/1840337/30254093-22cbac7a-9661-11e7-907c-91b2768f0207.png">

<img width="920" alt="screen shot 2017-09-10 at 19 29 11" src="https://user-images.githubusercontent.com/1840337/30254092-1cec49a4-9661-11e7-8e99-d7943cb0d2fa.png">

No matter how many times I restart or update the load balancer, setting that IP. This is the result every time.

**Comment by ikogan** [comment]
Edit: After destroying and recreating the load balancer, it looks like it's working properly:

```
Chain CATTLE_PREROUTING (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 DNAT       tcp  --  !docker0 *       0.0.0.0/0            10.1.42.5            tcp dpt:80 to:10.42.32.57:80
    0     0 DNAT       tcp  --  *      *       0.0.0.0/0            10.1.42.5            tcp dpt:80 to:10.42.32.57:80
    0     0 DNAT       tcp  --  !docker0 *       0.0.0.0/0            10.1.42.5            tcp dpt:443 to:10.42.32.57:443
    0     0 DNAT       tcp  --  *      *       0.0.0.0/0            10.1.42.5            tcp dpt:443 to:10.42.32.57:443
    0     0 DNAT       tcp  --  !docker0 *       0.0.0.0/0            10.1.42.5            tcp dpt:22 to:10.42.32.57:22
    0     0 DNAT       tcp  --  *      *       0.0.0.0/0            10.1.42.5            tcp dpt:22 to:10.42.32.57:22
    0     0 DNAT       udp  --  !docker0 *       0.0.0.0/0            10.1.42.27           udp dpt:500 to:10.42.172.168:500
    0     0 DNAT       udp  --  *      *       0.0.0.0/0            10.1.42.27           udp dpt:500 to:10.42.172.168:500
    0     0 DNAT       udp  --  !docker0 *       0.0.0.0/0            10.1.42.27           udp dpt:4500 to:10.42.172.168:4500
    0     0 DNAT       udp  --  *      *       0.0.0.0/0            10.1.42.27           udp dpt:4500 to:10.42.172.168:4500
```

**Comment by ikogan** [comment]
This bug just happened again and, unlike last time, I cannot get it to create the rules correctly even after destroying and re-creating the load balancer. However, I noticed that _all_ of the IPs listed are always 10.1.42.5 now. I did double check that I had the others listed as scheduler IPs but apparently it's just completely ignoring them.

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
