### ISSUE TITLE
Run a health check tool for Rancher network

### ISSUE THREAD

**Issue by niusmallnan** [rancher/rancher#9859]
There are three detection methods, all for containers with the managed network option:

1. Ping, send 5 Ping packets to the target container to see if there is a packet loss.
2. Arping, send 5 arp requests to the target container to see if the returned mac address is consistent.
3. HTTP, request http ping for the router container to see if the networking service is ok.

The network-healthcheck will turn red in Rancher UI when any container's network is unreachable. Then you can look at the network-healthcheck log and it will tell you which container it is.

**Comment by yasker** [comment]
Tool is available at: https://github.com/niusmallnan/network-healthcheck
Currently, the catalog is available at: https://github.com/niusmallnan/network-healthcheck-catalog

**Comment by yasker** [comment]
@niusmallnan Can you make a PR to https://github.com/rancher/network-healthcheck ?
