### ISSUE TITLE
“rancher cli run” command can not specify the host-label

### ISSUE THREAD

**Issue by neillau24** [rancher/rancher#9861]
“rancher cli run” command can not specify the host-label

$rancher_cli --url $rancher_url --access-key $rancher_access_key --secret-key $rancher_secret_key --env $rancher_env --wait --wait-state active --wait-timeout $rancher_wait_timeout run --name $rancher_stack/$app_name --privileged -p $port_out:$port_in -e MEM="$run_mem" -v /etc/localtime:/etc/localtime:ro -i -t --pull $image_name

**Comment by zyf0330** [comment]
You can use this `-l "io.rancher.scheduler.affinity:host_label=value" `, but I have not found how to add multi

**Comment by loganhz** [comment]
Please try `-l`
