### ISSUE TITLE
Rancher healtcheck (and all haproxy containers) stuck on initializing after host reconnect

### ISSUE THREAD

**Issue by typia** [rancher/rancher#9862]
Rancher versions:
rancher/server: 1.6.7
rancher/agent: 1.2.5

Infrastructure Stack versions:
healthcheck: 0.3.1
ipsec: 0.11.7
network-services: 0.7.7 (metadata 0.9.3)
scheduler: 0.8.2
kubernetes (if applicable):

Docker version: (docker version,docker info preferred)
17.06.2-ce
Operating system and kernel: (cat /etc/os-release, uname -r preferred)
Debian GNU/Linux 8 (jessie)
Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)
VMware esxi VMs
Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)
single node rancher, external DB
Environment Template: (Cattle/Kubernetes/Swarm/Mesos)
Cattle
Steps to Reproduce:
I made some testing with healthcheck by configuring services and then disconnecting network interfaces from host.
Results:
When I reconnect hosts network interfaces healtcheck containers and haproxy based containers (rancher lb / galera-lb) are stuck on initalizing 
Only way to restart containers is to restart docker service on host

**Comment by guodong** [comment]
you can try [阿里云经典网络与Rancher VXLAN兼容性问题](https://mp.weixin.qq.com/s/TCvCOJN3SVHDyhaikKYOrA)

**Comment by aemneina** [comment]
I believe the ipsec service had an issue where it wouldnt try to reestablish its tunnels aggressively. It would give up after a few failed attempts [#9971](https://github.com/rancher/rancher/issues/9971) Also rekey intervals, which are configurable in more modern versions of ipsec, should be helpful here.

**Comment by superseb** [comment]
Please report back if you are still experiencing issues.
