### ISSUE TITLE
Can not update client ID in Github Auth

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#9868]
Rancher Versions: 2.0/master
Server: master

Steps to Reproduce:

1. configure access control for github (intentionally put in bad client id)
2. click `save` and then authenticate with github
3. github shows 404 as the client id doesn't exist
4. update the client id to the correct one and click `save`

Results:

github still shows 404
it is still using the wrong client id in the OAuth URL 

Expected:

It should redirect to the correct github auth URL with the updated client id.
That means user can never change the client id once they set it up at the first time.

**Comment by yasker** [comment]
Is it reproducible in 1.6?

**Comment by loganhz** [comment]
@yasker it looks good in 1.6

**Comment by loganhz** [comment]
Auth largely doesn't work right now in 2.0. It is using rancher-auth-service v0.4.2 in master. someone else is working on it
