### ISSUE TITLE
SSL configuration not being included

### ISSUE THREAD

**Issue by bkuhl** [rancher/rancher#9870]
My SSL certificate currently shows as "Active" and my load balancer shows as healthy, but configuration isn't being applied because of this problem?

```
9/13/2017 1:01:16 PMtime="2017-09-13T17:01:16Z" level=error msg="Failed to apply lb config on provider: error reloading  -- reloading haproxy config with the new config changes\n * Reloading haproxy haproxy\n[ALERT] 255/170116 (120) : parsing [/etc/haproxy/haproxy.cfg:47] : 'bind *:443' : unable to load SSL private key from PEM file '/etc/haproxy/certs/current/.pem'.\n[ALERT] 255/170116 (120) : Error(s) found in configuration file : /etc/haproxy/haproxy.cfg\n[WARNING] 255/170116 (120) : config : 'option forwardfor' ignored for proxy 'default' as it requires HTTP mode.\n[ALERT] 255/170116 (120) : Fatal errors found in configuration.\n   ...fail!\n: exit status 1"
```

I've double-checked that I'm supplying the correct components of the certificate.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.2` Cattle: `v0.181.4` UI: `v1.6.5` |
|Access|`github` `admin`|
|Orchestration|`Cattle`|
|Route|`stacks.index`|

**Comment by bkuhl** [comment]
I was able to resolve this issue by deleting my load balancer and recreating it.  I was never able to get edits to apply.

**Comment by gisostallenberg** [comment]
We had the same issue and found that cleanup_temp_certs in /usr/bin/haproxy_reload leaves hidden files, because it removes the files using `rm -f /etc/haproxy/certs/new/*`.
We are not sure yet how this empty (and 'hidden') `.pem` file gets there, but just removing it from /etc/haproxy/certs/new/ spared us recreating a loadbalancer.

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
