### ISSUE TITLE
Unable to select VPC/subnets for ec2 in try.rancher.com

### ISSUE THREAD

**Issue by bfosberry** [rancher/rancher#9871]
<img width="866" alt="screen shot 2017-09-13 at 11 57 11 am" src="https://user-images.githubusercontent.com/1553039/30395485-34d2cebe-987b-11e7-8769-aa934aa6fe5c.png">
**Rancher versions:**
rancher/server: try.rancher.com
rancher/agent: try.rancher.com

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** AWS EC2

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)** Kubernetes

**Steps to Reproduce:**
Create environment for k8s
Click add hosts
Insert AWS creds, select region and click next

**Results:**
VPC/subnet dropdown should be missing
Form cannot be submitted

**Comment by bfosberry** [comment]
This also happens with a local install of rancher 1.6.9

**Comment by bfosberry** [comment]
Ah, figured this out. The issue is that the AZ dropdown needs to be toggled before the VPC dropdown populates. Prob still want to fix this

**Comment by tfiduccia** [comment]
Version - 1.6 and 2.0 master 10/16
Verified fixed
