### ISSUE TITLE
Document container capabilities

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#9872]
When starting a container, without specifying specific capabilities, you get the default docker container capabilities. This is noticeable via docker inspect on the container and seeing the following:
 
```
            "CapAdd": null,
            "CapDrop": null,
```
 
This is also visible in the container API view in the rancher UI. You can add or drop capabilities and those too will be present in the inspect/api output. Here are a couple examples:
 
```
            "CapAdd": [
                "CHOWN",
                "KILL",
                "NET_ADMIN",
                "NET_BIND_SERVICE",
                "NET_BROADCAST",
                "NET_RAW"
            ],
            "CapDrop": [
                "AUDIT_CONTROL",
                "AUDIT_WRITE",
                "BLOCK_SUSPEND",
                "SYS_RAWIO",
                "SYS_RESOURCE",
                "SYS_TIME",
                "SYS_TTY_CONFIG",
                "WAKE_ALARM"
            ],
```
 
OR
 
```
            "CapAdd": [
                "ALL"
            ],
            "CapDrop": [],
```

This isnt documented anywhere in the rancher docs

**Comment by deniseschannon** [comment]
Rancher will not specifically list out what will work/not work as this is documented in Docker. 

https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities
