### ISSUE TITLE
rancher "forgets" storage driver

### ISSUE THREAD

**Issue by pschrammel** [rancher/rancher#9875]
**Rancher versions:**
rancher/server: 1.6.5
rancher/agent: 1.2.5

**Infrastructure Stack versions:**
healthcheck: rancher/healthcheck:v0.3.1
ipsec: 	rancher/net:v0.11.3
network-services: metadata 0.9.2, manager: 0.7.4
scheduler:  rancher/scheduler:v0.8.2
storage-ebs: 0.8.1

**Docker version: (`docker version`,`docker info` preferred)**
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:23:31 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:19:04 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
4.4.0-1032-aws
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
aws
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher,external db
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
cattle
**Steps to Reproduce:**
Hard to say but it happened twice already:

Install rancher-ebs, create a container with a a volume on ebs. Then the ebs storage driver disappears from the storage (No storage drivers) after a while. It could be the case that the mounting container moved into another AZ. Ebs stack is working (no errors in the logs), if I start the mounting container in the right AZ it can mount the ebs volume.

**Results:**
UI shows "No storage drivers" if you open Infrastructur -> Storage

**Comment by cjellick** [comment]
Can you ellaborate on "after a while" - how long is that?
How many times has this happened to you? Does it ever reappear?
Where does it disappear from? The storage page? Is the rancher-ebs stack on the stacks page still present and healthy? Are its containers still deployed?

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
