### ISSUE TITLE
Failed requests during service downscaling

### ISSUE THREAD

**Issue by kwaio** [rancher/rancher#9877]
**Rancher versions:**
rancher/server: 1.4.1
rancher/agent: 1.2.0

**Infrastructure Stack versions:**
healthcheck: 0.2.3
ipsec: holder
network-services: 0.7.4
scheduler: 0.6.3
kubernetes (if applicable): n/a

**Docker version: (`docker version`,`docker info` preferred)**
1.12

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
CentOS 7
4.4.57-1.el7.elrepo.x86_64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VMware

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
4 node cluster, single instance rancher server, external DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
1. Spawn a service X with at least 2 containers
2. Add a load-balancer sending traffic to service X
3. Start benchmarking / load testing your service
4. downscale service X

**Results:**
Some requests are lost/failed/dropped

**Expected Results:**
Haproxy removing container from load balancing before container is destroyed
No failed requests

**Comment by cjellick** [comment]
This should be addressed in https://github.com/rancher/rancher/issues/2777, in which we will properly drain connections from LB before stopping container

**Comment by aemneina** [comment]
Will close this out as its slated to be fixed soon.
