### ISSUE TITLE
Fail to release port resource when LB update

### ISSUE THREAD

**Issue by carolynhu** [rancher/rancher#9879]
To reproduce:
1.add a host, and add a few fake ip for host, such as 192.168.10.10,  192.168.20.20
2.create a stack 
3.add a service (named "service1" here) in stack
4.add a load balancer service
<img width="1358" alt="screen shot 2017-09-18 at 9 57 04 am" src="https://user-images.githubusercontent.com/29208297/30553981-c3bf86aa-9c57-11e7-970b-befa31fe0e72.png">
the two ports being bounded to ip:192.168.10.10, respectively
<img width="546" alt="screen shot 2017-09-18 at 9 58 17 am" src="https://user-images.githubusercontent.com/29208297/30554046-02e2d7a6-9c58-11e7-96ec-81ffaeb8b17b.png">
5.add a service2, with ip address 192.168.10.10 and port 100:100, which will be failed, since this port resource is being utilized
6.but when you upgrade LB service, which is to remove 100:100 port, then add a service3 with ip address 192.168.10.10 and port 100:100, which will still be failed
<img width="1363" alt="screen shot 2017-09-18 at 10 02 55 am" src="https://user-images.githubusercontent.com/29208297/30554211-9c17bd06-9c58-11e7-93fd-e82e5194f808.png">
<img width="1396" alt="screen shot 2017-09-18 at 10 03 04 am" src="https://user-images.githubusercontent.com/29208297/30554213-9dd94290-9c58-11e7-8d05-9dea66ec426b.png">

therefore, ports resource have not been released after ports being removed.

**Comment by soumyalj** [comment]
Tested with rancher v1.6.11-rc3
1. Create a one host setup and add a scheduler IP to the host
2. Create a service ser1 and a loadbalancer(mylb) with port 9001 with target ser1
3. Create another service ser2 with port 9001 . The service creation will fail as the port 9001 is not available
4. Edit mylb and change the port 9001 to 9003. 
5. Port 9001 will be released in step 4 and ser2 will be able to use port 9001 and will he healthy
