### ISSUE TITLE
External Services health checks cannot be changed (affects API, UI, and CLI)

### ISSUE THREAD

**Issue by Moeser** [rancher/rancher#9880]
**Rancher versions:**
rancher/server: 1.6.7 (confirmed in previous versions too)
rancher/agent: n/a

**Infrastructure Stack versions:**
healthcheck: n/a
ipsec: n/a
network-services: n/a
scheduler: n/a
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
n/a

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
n/a

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
n/a

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher with external DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Create an external service.
Try to change the health check for that external service after it is created.

**Results:**
You'll find that the option to change health checks for external services just isn't present in the UI.  You'll also find that the CLI works but changes nothing if you provide a new health check in your compose files.  And finally, the API responds with a 200 if you send a valid PUT with new health check parameters defined, but changes nothing.

**Comment by Moeser** [comment]
For others who are running into this, here's a work-around to updating the health check without downtime:

* Rename the external service (If it's called ServiceName, then rename it to something like ServiceName-old)
* Clone ServiceName-old and update your health check parameters, and drop the -old (you should now have ServiceName with the correct health check params, and ServiceName-old with the incorrect params)
* Edit the load balancer and switch the target from ServiceName-old to ServiceName (rancher switched the target to ServiceName-old automatically when you first renamed the external service, so now you just need the load balancer to point to the updated service)
* Rinse and repeat for all of your external services and load balancers that you want to update (for us, it was a lot).  It's a painstaking and manual process, but better than taking downtime.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
