### ISSUE TITLE
Unable to start pod infra images in k8s

### ISSUE THREAD

**Issue by naveensrinivasan** [rancher/rancher#9882]
**Rancher versions:**
rancher/server: v1.7.2
rancher/agent:

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable): k8s

**Docker version: (`docker version`,`docker info` preferred)** 1.12

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)** ubuntu xenial

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single node

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)** k8s

**Steps to Reproduce:**
We are running k8s with private docker registry.
We want all the pods to run from the private docker registry so that it can be air-gapped.

Here is our k8s version v1.7.2

Here is my configuration for pod infra images
[https://discourse-cdn-sjc1.com/standard/uploads/rancher/original/2X/f/f8481bfd59a2937aa5d88e1b325f24ab4e43da9b.png](https://discourse-cdn-sjc1.com/standard/uploads/rancher/original/2X/f/f8481bfd59a2937aa5d88e1b325f24ab4e43da9b.png)
My registry is set to ip-10-0-0-160:5000/gcr.io without a trailing slash. Learnt it the hard way the trailing slash causes issues.

Here is my log on docker pull
```
docker pull ip-10-0-0-160:5000/gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64:1.14.2
1.14.2: Pulling from gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64

Digest: sha256:70b157a6695e5dddc5a3741c401c0507f0fd9326376c77162c690f5f5e82a264
Status: Image is up to date for ip-10-0-0-160:5000/gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64:1.14.2
```
The kube dns does not comeup.
```
NAME                                   READY     STATUS             RESTARTS   AGE
heapster-1584063577-n56m2              1/1       Running            0          16h
kube-dns-1842970385-ww5vm              0/3       Pending            0          16h
kube-dns-2943014524-gsskt              0/3       InvalidImageName   0          14m
kubernetes-dashboard-96113950-48pz7    1/1       Running            0          16h
monitoring-grafana-1854198434-ngjt4    1/1       Running            0          16h
monitoring-influxdb-2450037842-wwt38   1/1       Running            0          16h
tiller-deploy-3765135481-f9dg8         1/1       Running            0          16h
```
And this is what is in the logs in kubectl describe
```
Events:
  FirstSeen	LastSeen	Count	From							SubObjectPath			Type		Reason			Message
  ---------	--------	-----	----							-------------			--------	------			-------
  14m		14m		6	default-scheduler									Warning		FailedScheduling	No nodes are available that match all of the following predicates:: MatchInterPodAffinity (1).
  14m		14m		1	default-scheduler									Normal		Scheduled		Successfully assigned kube-dns-2943014524-gsskt to ip-10-0-0-160.us-west-1.compute.internal
  14m		14m		1	kubelet, ip-10-0-0-160.us-west-1.compute.internal					Normal		SuccessfulMountVolume	MountVolume.SetUp succeeded for volume "kube-dns-config"
  14m		14m		1	kubelet, ip-10-0-0-160.us-west-1.compute.internal					Normal		SuccessfulMountVolume	MountVolume.SetUp succeeded for volume "kube-dns-token-p41d6"
  14m		13m		3	kubelet, ip-10-0-0-160.us-west-1.compute.internal					Normal		SandboxChanged		Pod sandbox changed, it will be killed and re-created.
  14m		4s		68	kubelet, ip-10-0-0-160.us-west-1.compute.internal					Warning		FailedSync		Error syncing pod
  13m		4s		65	kubelet, ip-10-0-0-160.us-west-1.compute.internal	spec.containers{kubedns}	Warning		InspectFailed		Failed to apply default image tag "ip-10-0-0-160:5000/gcr.io//google_containers/k8s-dns-kube-dns-amd64:1.14.2": couldn't parse image reference "ip-10-0-0-160:5000/gcr.io//google_containers/k8s-dns-kube-dns-amd64:1.14.2": invalid reference format
  13m		4s		65	kubelet, ip-10-0-0-160.us-west-1.compute.internal	spec.containers{dnsmasq}	Warning		InspectFailed		Failed to apply default image tag "ip-10-0-0-160:5000/gcr.io//google_containers/k8s-dns-dnsmasq-nanny-amd64:1.14.2": couldn't parse image reference "ip-10-0-0-160:5000/gcr.io//google_containers/k8s-dns-dnsmasq-nanny-amd64:1.14.2": invalid reference format
  13m		4s		65	kubelet, ip-10-0-0-160.us-west-1.compute.internal	spec.containers{sidecar}	Warning		InspectFailed		Failed to apply default image tag "ip-10-0-0-160:5000/gcr.io//google_containers/k8s-dns-sidecar-amd64:1.14.2": couldn't parse image reference "ip-10-0-0-160:5000/gcr.io//google_containers/k8s-dns-sidecar-amd64:1.14.2": invalid reference format
```

**Results:**
The issue is the code seems to be adding additional trailing slash ip-10-0-0-160:5000/gcr.io//google_containers/k8s-dns-kube-dns-amd64:1.14.2"

**Comment by alena1108** [comment]
@naveensrinivasan could you please share the exported docker/rancher compose files of your kubernetes stack (you can retrieve it by clicking "Export Config" option in the UI for the stack).

**Comment by galal-hussein** [comment]
@naveensrinivasan I sat up a private registry with hostname `ip-10-0-0-160:5000` and I tested on kubernetes 1.7.2 with the same value in private registry `ip-10-0-0-160:5000/gcr.io` but i can't reproduce, the addons started correctly on the hosts and i didn't see any issue.

**Comment by naveensrinivasan** [comment]
@galal-hussein I am not certain whether it was `1.6` or `1.7.2`. I had deleted that ENV. Will try and recreate and post the config and results here. Thanks

**Comment by galal-hussein** [comment]
@naveensrinivasan I wanted to follow up on this problem, were you able to reproduce with new environment?

**Comment by naveensrinivasan** [comment]
@galal-hussein  Thanks for following up.
It is an issue. I am using the stable version of rancher and here is the output 
```

**Comment by naveensrinivasan** [comment]
I don't know how to export the settings. Could you please share where it is? Thanks

**Comment by galal-hussein** [comment]
@naveensrinivasan Thanks for the information, its a bit different from other output you sent earlier, you can export the config by doing the following: navigate to **Kubernetes** Tab -> **Infrastructure Stacks**, and in the infrastructure stacks click over kubernetes stack options and select export config:

![screenshot from 2017-09-20 07-36-47](https://user-images.githubusercontent.com/3309968/30658752-09d1a9ee-9e3c-11e7-9c46-5ad080603945.png)

Can you share what value did you use for **Pod Infra Container Image** in the k8s catalog?

**Comment by naveensrinivasan** [comment]
@galal-hussein  Here it is
[compose.zip](https://github.com/rancher/rancher/files/1319254/compose.zip)

and is my setting that you had asked for 
![image](https://user-images.githubusercontent.com/172697/30667687-62a3560a-9e26-11e7-9033-dfce21079b31.png)

Thanks

**Comment by galal-hussein** [comment]
@naveensrinivasan the problem is that you sat up pod infra container image incorrectly:

Registry: localhost:5000/gcr.io
Pod infra image: gcr.io/google_containers/pause-amd64:3.0

This resulted in a duplication for `gcr.io` so it resulted in the following option:

`--pod-infra-container-image=localhost:5000/gcr.io/gcr.io/google_containers/pause-amd64:3.0`

That's why kubelet can't pull this image, to fix this you can change the **Pod Infra Container Image** to `google_containers/pause-amd64:3.0`, and make sure that `localhost:5000/gcr.io/google_containers/pause-amd64:3.0` exists in the private registry.

**Comment by naveensrinivasan** [comment]
@galal-hussein  Thanks, that solved the issue. Closing this.

**Comment by anjia0532** [comment]
hei , in the china ,i can not access gcr.io.

so i use new york vps pull the gcr.io image and push to docker hub.



## get rancher-k8s original version

// copy to k8s cli and run it to get gcr.io images version
```bash
k8s=(
    heapster
    kube-dns
    kubernetes-dashboard
    monitoring-grafana
    monitoring-influxdb
    tiller-deploy
)
for imageName in ${k8s[@]} ; do
    for t in $(kubectl --namespace=kube-system describe deployment $imageName | grep gcr | awk '{print $2}') ; do
        echo $t
    done
done
```
// output ,copy it
```
gcr.io/google_containers/heapster-amd64:v1.3.0-beta.1
gcr.io/google_containers/k8s-dns-kube-dns-amd64:1.14.5
gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64:1.14.5
gcr.io/google_containers/k8s-dns-sidecar-amd64:1.14.5
gcr.io/google_containers/kubernetes-dashboard-amd64:v1.6.1
gcr.io/google_containers/heapster-grafana-amd64:v4.0.2
gcr.io/google_containers/heapster-influxdb-amd64:v1.3.3
gcr.io/kubernetes-helm/tiller:v2.3.0
```



## pull gcr.io image and push to docker hub

```bash
hubName=anjia0532

images=(
    gcr.io/google_containers/heapster-amd64:v1.3.0-beta.1
    gcr.io/google_containers/k8s-dns-kube-dns-amd64:1.14.5
    gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64:1.14.5
    gcr.io/google_containers/k8s-dns-sidecar-amd64:1.14.5
    gcr.io/google_containers/kubernetes-dashboard-amd64:v1.6.1
    gcr.io/google_containers/heapster-grafana-amd64:v4.0.2
    gcr.io/google_containers/heapster-influxdb-amd64:v1.3.3
    gcr.io/kubernetes-helm/tiller:v2.3.0
)

for imageName in ${images[@]} ; do
    imgName=$(echo ${imageName} | cut -d"/" -f3)
    docker pull $imageName
    docker tag $imageName $hubName/$imgName
    docker push $hubName/$imgName
done
```

## change rancher-k8s namespace=kube-system's res image source

```bash
kubectl --namespace=kube-system edit deployment  heapster
kubectl --namespace=kube-system edit deployment  kube-dns
kubectl --namespace=kube-system edit deployment  kubernetes-dashboard
kubectl --namespace=kube-system edit deployment  monitoring-grafana
kubectl --namespace=kube-system edit deployment  monitoring-influxdb

:%s#gcr.io/google_containers#anjia0532#g
:wq!

kubectl --namespace=kube-system edit deployment  tiller-deploy

:%s#gcr.io/kubernetes-helm#anjia0532#g
:wq!
```

## but, rancher-k8s is keep pending

```bash
$ kubectl --namespace=kube-system  get pods
NAME                                    READY     STATUS              RESTARTS   AGE
heapster-2407085140-hgddj               0/1       ContainerCreating   0          48m
kube-dns-570853077-hcqzg                0/3       Pending             0          1h
kube-dns-638003847-8vps9                0/3       ContainerCreating   0          2h
kubernetes-dashboard-3888044391-wm3s3   0/1       ContainerCreating   0          14m
monitoring-grafana-3847008717-06988     0/1       ContainerCreating   0          14m
monitoring-influxdb-3527312529-n3xxw    0/1       ContainerCreating   0          14m
tiller-deploy-402017509-jkw7n           0/1       ContainerCreating   0          13m

```

**Comment by behroozam** [comment]
iam from iran.  please use dockerhub for k8s  instead of gcr . its painful to set proxy for getting that images . google banned iranian to use gcr as well as china users. and why you use gcr by the way ?

**Comment by deniseschannon** [comment]
@behroozam gcr is the default registry for the k8s images. in the k8s template, you can change the registry to a private registry for the pod infra container as well as the add-on images. 

in the next k8s release, we are defaulting all images to `dockerhub/rancher`.
