### ISSUE TITLE
Healthchecks require a newline in the response

### ISSUE THREAD

**Issue by monitorjbl** [rancher/rancher#9883]
**Rancher versions:**
rancher/server: 1.6.7
rancher/agent: 1.2.6

**Infrastructure Stack versions:**
healthcheck: 0.3.0
ipsec: 0.1.3
network-services: 0.2.5
scheduler: 0.6.3
kubernetes (if applicable): n/a

**Docker version: (`docker version`,`docker info` preferred)**

```
# docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:45:26 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:45:26 2017
 OS/Arch:      linux/amd64
 Experimental: false

# docker info
Containers: 17
 Running: 17
 Paused: 0
 Stopped: 0
Images: 16
Server Version: 17.03.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 121
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local pylon-cinder
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-81-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.796 GiB
Name: pylon-worker-0
ID: WR3Z:FBKX:WPSR:YUGJ:H2KK:D5JR:LDQZ:BWCY:PUGV:PC7R:NTY7:244Q
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

```
# cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

# uname -r
4.4.0-81-generic
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

Openstack VMs

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

Single node rancher server, single node rancher host

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**

1. Create an image with a web server that returns a 200 and single line of output with no trailing newline when a GET request is issued to /health. 
1. Create an image with a web server that returns a 200 and single line of output with a trailing newline when a GET request is issued to /health. 
1. Create a stack using the image from 1. and add the healthcheck shown below
1. Create a stack using the image from 2. and add the healthcheck shown below

```
version: '2'
services:
  server:
    scale: 1
    health_check:
      port: 2379
      request_line: GET /health HTTP/1.0
      interval: 5000
      unhealthy_threshold: 10
      strategy: none
      healthy_threshold: 2
      response_timeout: 1000
```

**Results:**
The image in 1. does not ever register as healthy, while the image in 2. does.

**Comment by monitorjbl** [comment]
This took me a couple hours of beating my head into my desk, and it left me with a bad taste in my mouth because it's so damn arbitrary. I added a healthcheck that worked elsewhere but changed the endpoint to something that returns a 200 as long as the server is healthy. After trying just about everything else to debug this, I finally compared the request bodies and noted the lack of a newline in the failing case. I switched to another endpoint that does return a newline and voila, it worked.

If this is expected behavior, I feel very strongly that the expectations need to be changed. I personally can't think of any reason why this would be necessary, though I'd love to hear if there is one.

**Comment by vincent99** [comment]
Can you capture the raw request and response (`tcpdump -w dump.pcap port 80` or similar, container needs `--privileged` to capture)

Healthchecks are done by haproxy so it seems far more likely your response is wrong than they don't know how to handle a http request.

For example if the Content-Length is off by one byte (perhaps because of CR vs CRLF conversion) the response isn't done yet so the client (haproxy) is just going to wait for more body until the check times out.

**Comment by monitorjbl** [comment]
Do you have an example image I can use for the tcpdump? I tried installing tcpdump in a privileged ubuntu 16 container, but I'm getting a bunch of permission denied errors when I try to run it in Rancher.

**Comment by vincent99** [comment]
Just `ubuntu` with --privileged, then `apt-get update && apt-get install tcpdump` should work.

`curl -ivs --raw https://10.42.x.y/health | xxd -c 30` from some container may be good enough too, though it's not the real request from haproxy.

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
