### ISSUE TITLE
External DNS Tests

### ISSUE THREAD

**Issue by JasonGiedymin** [rancher/rancher#9886]
Proposal: external-dns integration tests 
Desc: no provider tests exist (at least I couldn't find them). At the least either a live integration run by rancher or by the end user. Would be nice to run a series of tests for route53 for example, with user provided API IAM creds that will go ahead and setup and tear down a test zone.

Just some food for thought.

I plan on adding a provider, and was just a little taken aback that there no tests.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
