### ISSUE TITLE
cattle-debug.log tmp files growing indefinitely

### ISSUE THREAD

**Issue by maciejdrozdzowski** [rancher/rancher#9887]
Our versions are: 
kubernetes: rancher/k8s:v1.7.2-rancher7
rancher-ha, rancher/enterprise:v1.6.7

We've noticed that log files created by the rancher-ha containers take up all available space. The files have names like `cattle-debug.log18007271715426027.tmp` and we get around 4 every day. Each file is a little over 100MB.

Is there any way of suppressing those logs, or better - automatically pruning them? Shouldn't they be deleted after they're zipped?

**Comment by aemneina** [comment]
Fairly straight forward to reproduce, it seems to be a bug in the logback logging library we use. We need to check if bumping up the version of logback fixes this.

**Comment by sangeethah** [comment]
Tested with v1.6.11-rc2 . tmp files gets created and zipped as expected when it reaches ```logback.max.file.size``` . This was hardcoded to 100MB in the previous releases.

```
root@a44f3363f5c9:/var/lib/cattle/logs# ls -lth 
total 13M
-rw-r--r-- 1 root root 779K Oct  9 17:28 cattle-debug.log
-rw-r--r-- 1 root root 147K Oct  9 17:28 cattle-debug.2017-10-09.2.log.gz
-rw-r--r-- 1 root root  11M Oct  9 17:28 cattle-debug.2017-10-09.2.log6300906581811.tmp
-rw-r--r-- 1 root root 591K Oct  9 17:27 cattle-debug.2017-10-09.1.log.gz
-rw-r--r-- 1 root root 558K Oct  9 17:24 cattle-debug.2017-10-09.0.log.gz
root@a44f3363f5c9:/var/lib/cattle/logs# ls -lth 
total 3.4M
-rw-r--r-- 1 root root 1.7M Oct  9 17:28 cattle-debug.log
-rw-r--r-- 1 root root 583K Oct  9 17:28 cattle-debug.2017-10-09.2.log.gz
-rw-r--r-- 1 root root 591K Oct  9 17:27 cattle-debug.2017-10-09.1.log.gz
-rw-r--r-- 1 root root 558K Oct  9 17:24 cattle-debug.2017-10-09.0.log.gz
root@a44f3363f5c9:/var/lib/cattle/logs# 
```
