### ISSUE TITLE
Use labels in CNI IPAM

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#9893]
the IP and mac address are already containers labels, right?  so it's feasible that we just read the ip and mac from the docker inspect, pass as CNI arg and then we never talk to metadata?

**Comment by vincent99** [comment]
I feel like we've learned nothing from the "but what if I want to change the subnet while the plane is in the air" discussions last week...

![image](https://user-images.githubusercontent.com/753917/30510169-d9ee66e8-9a73-11e7-9bb9-cb367429625b.png)

**Comment by leodotcloud** [comment]
@vincent99 this is per @ibuildthecloud's request for "fast" path.
