### ISSUE TITLE
centos7 kernel  3.10.0-693.2.2.el7.x86_64 got Time out getting ip address,3.10.0-123.9.3.el7.x86_64 is good

### ISSUE THREAD

**Issue by chloroplast1983** [rancher/rancher#9895]
**Rancher versions:**
rancher/server:v1.6.5
rancher/agent:v1.2.5 

**Infrastructure Stack versions:**
healthcheck:v0.3.0
ipsec:v0.1.1
network-services:v0.2.3
scheduler:v0.6.3
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
1.10.3
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
 3.10.0-693.2.2.el7.x86_64
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
aliyun
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher external DB
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
Add host
**Results:**

Time out getting ip address.

![snip20170917_63](https://user-images.githubusercontent.com/2979824/30515869-baa52aca-9b62-11e7-90c8-13016531954f.png)
![snip20170917_64](https://user-images.githubusercontent.com/2979824/30515870-baa8dbd4-9b62-11e7-8bfe-f39c185d96e7.png)

Bug if i use kernel 3.10.0-123.9.3.el7.x86_64, everything is good.

![snip20170917_65](https://user-images.githubusercontent.com/2979824/30515880-e0edba8a-9b62-11e7-8a5d-ed1f3ece7f50.png)

**Comment by superseb** [comment]
Kernel 3.10.0-693 is used in RHEL/CentOS 7.4 which is known to be broken in Rancher earlier than v1.6.8. Please use a newer version of Rancher to see if that solves your problem. Keep in mind that support for Docker 1.10 is dropped per Rancher v1.6.6.

Going to close as not-a-bug, please create a new issue if you still experience problems if you used a newer version.
