### ISSUE TITLE
Tencent Cloud features support

### ISSUE THREAD

**Issue by niusmallnan** [rancher/rancher#9896]
- [ ]  external-dns: https://cloud.tencent.com/document/product/302
- [ ]  external-lb: https://cloud.tencent.com/document/product/214/888
- [ ]  rancher-storage: 
https://cloud.tencent.com/document/product/362/2345
https://cloud.tencent.com/product/cfs 

- [ ]  routes updater for Tencent Cloud VPC in per-host-subnet

**Comment by hiscal2015** [comment]
external-lb +1  
cfs +1

**Comment by yasker** [comment]
It turns out Tencent Cloud doesn't have Go SDK available for us to develop the related functions for Rancher, so we have to put a hold on this one for now until Tencent produce the SDK for Go.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
