### ISSUE TITLE
Timeout getting IP address

### ISSUE THREAD

**Issue by neillau24** [rancher/rancher#9897]
**Rancher versions:**
rancher/server:1.6.9
rancher/agent:1.2.6

**Infrastructure Stack versions:**
healthcheck:v0.3.1
ipsec:
network-services:v0.7.0
scheduler:v0.7.5
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
[root@localhost ~]# docker info
Containers: 9
 Running: 6
 Paused: 0
 Stopped: 3
Images: 12
Server Version: 17.06.2-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-693.2.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.51GiB
Name: localhost
ID: JFVU:UDDN:AQFZ:AWIL:HLOR:L3N3:LRVI:Y5JN:OHFA:NRFL:UEJI:UPTO
Docker Root Dir: /home/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 https://rmj1scoz.mirror.aliyuncs.com/
Live Restore Enabled: false
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
vsphere
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node ranche
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
![40cdb070fd95833e66c4d363bbb9227](https://user-images.githubusercontent.com/19727969/30532023-836d5686-9c84-11e7-95c3-825e457b3f90.png)
**Results:**
![40cdb070fd95833e66c4d363bbb9227](https://user-images.githubusercontent.com/19727969/30532033-8f821ae2-9c84-11e7-911c-ef29ec0f3c89.png)

**Comment by leodotcloud** [comment]
@neillau24 Can you please collect logs using `https://github.com/rancher/rancher-logs-collector`? Do you see any error messages in the logs?

**Comment by leodotcloud** [comment]
Also check: https://github.com/rancher/rancher/issues/9367

**Comment by superseb** [comment]
Any update @neillau24 ?

**Comment by superseb** [comment]
Let us know if we can assist on this.
