### ISSUE TITLE
Degraded ETCD cluster result in K8S service failure

### ISSUE THREAD

**Issue by hongxiaolu** [rancher/rancher#9899]
**Rancher versions:**
rancher/server:v1.6.5、v1.6.7 etc.
rancher/agent: v1.2.6 、v1.2.5

**Infrastructure Stack versions:**
rancher/lb-service-haproxy:v0.7.9
rancher/net:v0.11.9
rancher/net:holder
rancher/scheduler:v0.8.2
rancher/lb-service-haproxy:v0.7.9
rancher/dns:v0.15.3
rancher/healthcheck:v0.3.3
rancher/metadata:v0.9.4
rancher/net:v0.11.9
rancher/network-manager:v0.7.8

kubernetes (if applicable):
v1.7.2   v1.7.4
**Docker version: (`docker version`,`docker info` preferred)**
1.12.3
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04.3 LTS  4.4.0-87-generic
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VirtualBox、VMware
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher  、
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes 

**Steps to Reproduce:**

I deployed K8S in rancher，I have three rancher  agent host,when I delete one of the rancher agent host (for example, host3),
 the ETCD service in the Kubernetes stack is beginning to show an unhealthy state.Looking at the ETCD service, the third instance container is constantly being dispatched to the host that has been deleted(host3), and finally the ETCD service reconstruction failed, and ETCD failed to provide service to Kubernetes.

**Results:**
ETCD cannot provide service to Kubernetes, causing the ADD-ONS component to stop working.

**Comment by hongxiaolu** [comment]
@nayang777

**Comment by yasker** [comment]
Per @alena1108 , it's by design:

```
I think we want to preserve hard anti affinity. Ideally in the system number of hosts suitable for etcd, should be greater than etcd scale
```

**Comment by hongxiaolu** [comment]
Hi, all.  
Sorry, I need to correct one of my description errors： I have three nodes, and I have deleted any two of them. Now the ADD-ONS service prompt will not find ETCD leader

Here are the logs generated by ADD-ONS

2017/9/19 下午2:30:32+ FQDN=eb43efe420eb
2017/9/19 下午2:30:32+ '[' addons-update.sh == kubelet ']'
2017/9/19 下午2:30:32+ '[' addons-update.sh == kube-proxy ']'
2017/9/19 下午2:30:32+ '[' addons-update.sh == kube-apiserver ']'
2017/9/19 下午2:30:32+ exec addons-update.sh
2017/9/19 下午2:30:32+ '[' == true ']'
2017/9/19 下午2:30:32/usr/bin/addons-update.sh: line 4: [: ==: unary operator expected
2017/9/19 下午2:30:32+ export KUBECONFIG=/etc/kubernetes/ssl/kubeconfig
2017/9/19 下午2:30:32+ KUBECONFIG=/etc/kubernetes/ssl/kubeconfig
2017/9/19 下午2:30:32+ kubectl --namespace=kube-system get ns kube-system
2017/9/19 下午2:30:32+ kubectl delete --namespace kube-system deployment influxdb-grafana
2017/9/19 下午2:30:32+ true
2017/9/19 下午2:30:32+ kubectl apply -f -
2017/9/19 下午2:30:32+ cat
2017/9/19 下午2:30:32serviceaccount "io-rancher-system" configured
2017/9/19 下午2:30:32clusterrolebinding "addons-binding" configured
2017/9/19 下午2:30:32+ GCR_IO_REGISTRY=registry.cn-shenzhen.aliyuncs.com
2017/9/19 下午2:30:32+ DOCKER_IO_REGISTRY=registry.cn-shenzhen.aliyuncs.com
2017/9/19 下午2:30:32+ INFLUXDB_RETENTION=0s
2017/9/19 下午2:30:32+ DNS_REPLICAS=1
2017/9/19 下午2:30:32+ ADDONS_IMAGE_NAMESPACE=rancher_cn
2017/9/19 下午2:30:32+ INFLUXDB_HOST_PATH=
2017/9/19 下午2:30:32+ '[' '' == '' ']'
2017/9/19 下午2:30:32+ INFLUXDB_VOLUME='emptyDir: {}'
2017/9/19 下午2:30:32++ find /etc/kubernetes/addons -name '*.yaml'
2017/9/19 下午2:30:32+ for f in '$(find /etc/kubernetes/addons -name '\''*.yaml'\'')'
2017/9/19 下午2:30:32+ sed -i 's|$GCR_IO_REGISTRY|registry.cn-shenzhen.aliyuncs.com|g' /etc/kubernetes/addons/heapster/heapster-deployment.yaml
2017/9/19 下午2:30:32+ sed -i 's|$DOCKER_IO_REGISTRY|registry.cn-shenzhen.aliyuncs.com|g' /etc/kubernetes/addons/heapster/heapster-deployment.yaml
2017/9/19 下午2:30:32+ sed -i 's|$INFLUXDB_VOLUME|emptyDir: {}|g' /etc/kubernetes/addons/heapster/heapster-deployment.yaml
2017/9/19 下午2:30:32+ sed -i 's|$INFLUXDB_RETENTION|0s|g' /etc/kubernetes/addons/heapster/heapster-deployment.yaml
2017/9/19 下午2:30:32+ sed -i 's|$DNS_REPLICAS|1|g' /etc/kubernetes/addons/heapster/heapster-deployment.yaml
2017/9/19 下午2:30:32+ sed -i 's/$ADDONS_IMAGE_NAMESPACE/rancher_cn/g' /etc/kubernetes/addons/heapster/heapster-deployment.yaml
2017/9/19 下午2:30:32+ kubectl --namespace=kube-system replace --force -f /etc/kubernetes/addons/heapster/heapster-deployment.yaml
2017/9/19 下午2:30:38error: error when deleting "/etc/kubernetes/addons/heapster/heapster-deployment.yaml": Delete https://kubernetes.kubernetes.rancher.internal:6443/apis/extensions/v1beta1/namespaces/kube-system/deployments/heapster: unexpected EOF
2017/9/19 下午2:30:40+ '[' addons-update.sh == kubelet ']'
2017/9/19 下午2:30:40+ curl -s -f http://rancher-metadata/2015-12-19/stacks/Kubernetes/services/kubernetes/uuid
2017/9/19 下午2:30:40+ /usr/bin/update-rancher-ssl
2017/9/19 下午2:30:40++ curl -s http://rancher-metadata/2015-12-19/stacks/Kubernetes/services/kubernetes/uuid
2017/9/19 下午2:30:40+ UUID=29b20d5f-fcc0-4e46-9bb3-73b203c47c55
2017/9/19 下午2:30:40++ jq -r '.data[0].actions.certificate'
2017/9/19 下午2:30:40++ curl -s -u 9D016E9363406FF42056:GHnUYQPkHV5Qxw6heKMgtDzB52kr3gA9uSJBcpxF 'http://192.168.100.100:8080/v1/services?uuid=29b20d5f-fcc0-4e46-9bb3-73b203c47c55'
2017/9/19 下午2:30:40+ ACTION='http://192.168.100.100:8080/v1/services/1s16/?action=certificate'
2017/9/19 下午2:30:40+ KUBERNETES_URL=https://kubernetes.kubernetes.rancher.internal:6443
2017/9/19 下午2:30:40+ '[' -n 'http://192.168.100.100:8080/v1/services/1s16/?action=certificate' ']'
2017/9/19 下午2:30:40+ mkdir -p /etc/kubernetes/ssl
2017/9/19 下午2:30:40+ cd /etc/kubernetes/ssl
2017/9/19 下午2:30:40+ curl -s -u 9D016E9363406FF42056:GHnUYQPkHV5Qxw6heKMgtDzB52kr3gA9uSJBcpxF -X POST 'http://192.168.100.100:8080/v1/services/1s16/?action=certificate'
2017/9/19 下午2:30:40+ unzip -o certs.zip
2017/9/19 下午2:30:4029b20d5f-fcc0-4e46-9bb3-73b203c47c55Archive:  certs.zip
2017/9/19 下午2:30:40  inflating: ca.pem
2017/9/19 下午2:30:40  inflating: cert.pem
2017/9/19 下午2:30:40  inflating: key.pem
2017/9/19 下午2:30:40+ cd /
2017/9/19 下午2:30:40++ awk '{print $1}'
2017/9/19 下午2:30:40++ sha256sum
2017/9/19 下午2:30:40++ cat /etc/kubernetes/ssl/key.pem
2017/9/19 下午2:30:40+ TOKEN=a8600974c359d7ca56633e0a3f5dacb43c1b7b2391fd207e1aea0a41cd517cd6
2017/9/19 下午2:30:40+ cat
2017/9/19 下午2:30:40+ cat
2017/9/19 下午2:30:40+ '[' addons-update.sh == kubelet ']'
2017/9/19 下午2:30:40++ hostname --fqdn
2017/9/19 下午2:30:40+ FQDN=eb43efe420eb
2017/9/19 下午2:30:40+ '[' addons-update.sh == kubelet ']'
2017/9/19 下午2:30:40+ '[' addons-update.sh == kube-proxy ']'
2017/9/19 下午2:30:40+ '[' addons-update.sh == kube-apiserver ']'
2017/9/19 下午2:30:40+ exec addons-update.sh
2017/9/19 下午2:30:40+ '[' == true ']'
2017/9/19 下午2:30:40/usr/bin/addons-update.sh: line 4: [: ==: unary operator expected
2017/9/19 下午2:30:40+ export KUBECONFIG=/etc/kubernetes/ssl/kubeconfig
2017/9/19 下午2:30:40+ KUBECONFIG=/etc/kubernetes/ssl/kubeconfig
2017/9/19 下午2:30:40+ kubectl --namespace=kube-system get ns kube-system
2017/9/19 下午2:30:40+ sleep 2
2017/9/19 下午2:30:42+ kubectl --namespace=kube-system get ns kube-system
2017/9/19 下午2:30:42+ sleep 2
2017/9/19 下午2:30:44+ kubectl --namespace=kube-system get ns kube-system
2017/9/19 下午2:30:45+ sleep 2
2017/9/19 下午2:30:47+ kubectl --namespace=kube-system get ns kube-system
2017/9/19 下午2:30:47+ kubectl delete --namespace kube-system deployment influxdb-grafana
2017/9/19 下午2:30:47+ true
2017/9/19 下午2:30:47+ kubectl apply -f -
2017/9/19 下午2:30:47+ cat
2017/9/19 下午2:30:48serviceaccount "io-rancher-system" configured
2017/9/19 下午2:30:48clusterrolebinding "addons-binding" configured
2017/9/19 下午2:30:48+ GCR_IO_REGISTRY=registry.cn-shenzhen.aliyuncs.com
2017/9/19 下午2:30:48+ DOCKER_IO_REGISTRY=registry.cn-shenzhen.aliyuncs.com
2017/9/19 下午2:30:48+ INFLUXDB_RETENTION=0s
2017/9/19 下午2:30:48+ DNS_REPLICAS=1
2017/9/19 下午2:30:48+ ADDONS_IMAGE_NAMESPACE=rancher_cn
2017/9/19 下午2:30:48+ INFLUXDB_HOST_PATH=
2017/9/19 下午2:30:48+ '[' '' == '' ']'
2017/9/19 下午2:30:48+ INFLUXDB_VOLUME='emptyDir: {}'
2017/9/19 下午2:30:48++ find /etc/kubernetes/addons -name '*.yaml'
2017/9/19 下午2:30:48+ for f in '$(find /etc/kubernetes/addons -name '\''*.yaml'\'')'
2017/9/19 下午2:30:48+ sed -i 's|$GCR_IO_REGISTRY|registry.cn-shenzhen.aliyuncs.com|g' /etc/kubernetes/addons/heapster/heapster-deployment.yaml
2017/9/19 下午2:30:48+ sed -i 's|$DOCKER_IO_REGISTRY|registry.cn-shenzhen.aliyuncs.com|g' /etc/kubernetes/addons/heapster/heapster-deployment.yaml
2017/9/19 下午2:30:48+ sed -i 's|$INFLUXDB_VOLUME|emptyDir: {}|g' /etc/kubernetes/addons/heapster/heapster-deployment.yaml
2017/9/19 下午2:30:48+ sed -i 's|$INFLUXDB_RETENTION|0s|g' /etc/kubernetes/addons/heapster/heapster-deployment.yaml
2017/9/19 下午2:30:48+ sed -i 's|$DNS_REPLICAS|1|g' /etc/kubernetes/addons/heapster/heapster-deployment.yaml
2017/9/19 下午2:30:48+ sed -i 's/$ADDONS_IMAGE_NAMESPACE/rancher_cn/g' /etc/kubernetes/addons/heapster/heapster-deployment.yaml
2017/9/19 下午2:30:48+ kubectl --namespace=kube-system replace --force -f /etc/kubernetes/addons/heapster/heapster-deployment.yaml
2017/9/19 下午2:31:03Error from server: error when deleting "/etc/kubernetes/addons/heapster/heapster-deployment.yaml": client: etcd cluster is unavailable or misconfigured; error #0: client: etcd member http://etcd.kubernetes.rancher.internal:2379 has no leader

**Comment by hongxiaolu** [comment]
<img width="799" alt="wx20170919-145853 2x" src="https://user-images.githubusercontent.com/20707603/30627046-79273872-9e00-11e7-8771-521a1a024507.png">

**Comment by superseb** [comment]
If majority fails, you need to recover your etcd. As scale was 3, you lost majority and you need to run disaster recovery. (see https://coreos.com/etcd/docs/latest/v2/admin_guide.html and http://rancher.com/docs/rancher/v1.6/en/kubernetes/disaster-recovery/)

**Comment by hongxiaolu** [comment]
ok  thanks.
