### ISSUE TITLE
1.6.9 Release Notes Wrong?

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#9908]
Release Notes say that `Docker 17.06.0-ce/ee` is supported, I suppose that is suppose to be `Docker 17.05.0-ce/ee` instead?

**Comment by deniseschannon** [comment]
No, we only support the stable versions of Docker, which will be 17.03/17.06/17.09/17.12 for the year 2017. 

17.05 is an "edge" release which we will not support.

**Comment by ekristen** [comment]
@deniseschannon ah, thanks for the info, I couldn't find the 17.06 initially, it's installed a different way now.

**Comment by frekele** [comment]
@deniseschannon rancher 1.6.x will supported with docker-ce 17.09?

**Comment by vincent99** [comment]
An upcoming 1.6 release will, yes.  I do not know if there are any particular issues with it in 1.6.10, but it has not gone through our QA release cycle yet.
