### ISSUE TITLE
Trying to deploy AWS EC2 Rancher host, fails on waiting for SSH to be available

### ISSUE THREAD

**Issue by ericstoekl** [rancher/rancher#9909]
Similar to this issue: https://github.com/rancher/rancher/issues/6056

When I try to deploy through EC2, the machine gets created in my account with the proper security group (SSH inbound is open), however, the machine never gets picked up by Rancher, which hangs on 'waiting for SSH to be available':

[Screenshot](https://i.imgur.com/GeGASAf.png)

AWS AMI: rancheros-v1.1.0-hvm-1 (ami-9515feed)

**Rancher versions:**
rancher/server:
rancher/agent:

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
AWS AMI: rancheros-v1.1.0-hvm-1 (ami-9515feed)
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**

**Results:**

**Comment by vincent99** [comment]
Docker-machine runs inside of the server container and tries to SSH to the instance created using the IP it gets from the EC2 API for the instance.  So the instance ip needs to be reachable on 22 from the server container, and the problem is invariably VPC/security group settings.

**Comment by vincent99** [comment]
When you use custom there is no SSH connection from the server container to VM involved, you're doing it from your workstation.

There is no "template"; you pick a bunch of options with the UI and then all we are really doing is running `docker-machine --driver amazonec2 ...`.

The part that's failing is inside of docker-machine, has nothing specifically to do with rancher, and is going to be because the port actually isn't reachable for some reason, or the wrong username was provided.

**Comment by ericstoekl** [comment]
Just got it working, as you said, the username was set wrong. I had it set to `ubuntu` (100% my fault, however the UI had that as the default), should be `rancher`. Thanks @vincent99 !

**Comment by zaakiy** [comment]
I am using a Rancher AMI with username rancher, but I'm getting the same issue as OP.

![image](https://user-images.githubusercontent.com/10609818/30951216-0c8ea748-a465-11e7-90dd-c0e3ea28ed28.png)
![image](https://user-images.githubusercontent.com/10609818/30951247-3838961a-a465-11e7-9d00-6671ee82678b.png)

**Comment by cjellick** [comment]
Is port 22 of the VM being create reachable from the host where rancher/server is running?
Often, incorrect security groups are to blame. See https://rancher.com/docs/rancher/latest/en/hosts/amazon/#launching-amazon-ec2-hosts

**Comment by zaakiy** [comment]
Yes it was  ... Thanks

I just figured it out. Port 8080 on the Rangers server wasn't accessible by the clients.

**Comment by 7wonders** [comment]
Just ran into this issue and realised my subnet was not associated with the route table. That fixed it.

**Comment by miguelconde91** [comment]
I have the same issue, I'm making the deploy from a rancher with docker in my laptop and I'm not have a real IP, my aws instances need connect to the rancher server in my laptop?? or only my server need access to the 22 port in the EC2 instance.

**Comment by gvko** [comment]
Having the same issue. I am actually cloning an existing Host, and I've done it successfully before. Now I've tried for like 6-7 times and it always fails either with "failing to install docker" or "waiting for SSH to be available".
