### ISSUE TITLE
[rancher-compose] New services sometimes not started and have the state of 'Inactive'

### ISSUE THREAD

**Issue by marvinwankersteen** [rancher/rancher#9910]
**Rancher versions:**
rancher/server: v1.6.2
rancher/agent: v1.2.2

**Infrastructure Stack versions:**
healthcheck: v0.3.1
ipsec: v0.11.2
network-services: v0.7.4
scheduler: v0.8.2

**Docker version: (`docker version`,`docker info` preferred)**
17.03.1-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04.3 LTS

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher with external DB as container

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Rancher-compose version:**
v0.12.5

**Steps to Reproduce:**
It's hard to reproduce.
We generate with an own tool a new service in the `docker-compose.yml` and `rancher-compose.yml`. After this, we update the stack:
`rancher-compose up -u -d <new service-name>`

The INFO-output from `rancher-compose` looks like this:
```
INFO[0000] [0/85] [<name-of-service>]: Creating                       
INFO[0000] Creating service <name-of-service>                                                
INFO[0000] [0/85] [<name-of-service>]: Created                                               
INFO[0000] [0/85] [<name-of-service>]: Starting                       
INFO[0006] [1/85] [<name-of-service>]: Started
```
Between "Starting" and "Started" are only 1 to 2 seconds.

**Results:**
Sometimes, I dont know when and why, the service will only be created but not started. The service has then the state 'Inactive' in the GUI. The INFO-output of `rancher-compose` says "Started". No container are created. First, if we start the service manully in the GUI or API, the service get's started and the container created.

We tried to insert the `--debug` option, but then we get all INFO and DEBUG logs from any service in the stack.

In our old cluster, we used `rancher-server v1.1.1` and `rancher-compose v.0.8.6`. With this versions we had no problems with the services.
We have not updated the cluster. The new cluster is newly installed.

The problem is similar to this https://github.com/rancher/rancher/issues/1655. But we create only a new service and do not upgrade the service from `<oldservice>` to `<newservice>`.

**Comment by cjellick** [comment]
I don't have a solution off hand, but wanted to say that teh `rancher` cli is now preferred over `rancher-compose`. We are effectively deprecating the rancher-compose cli. So, your problem may be fixed in the `rancher` cli.

**Comment by aemneina** [comment]
rancher cli might emit better error messages, but you might want to look at the log file for the containers. Can you share a sanitized version of your stack?

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
