### ISSUE TITLE
Regular users cannot filter by stack label

### ISSUE THREAD

**Issue by jonaskello** [rancher/rancher#9911]
**Rancher versions:**
rancher/server: v1.6.7

As admin when I open the `STACKS` top level menu I have:

```
All
--
User
Infrastructure
--
Label1
Label2
Label3
```

If I select `Label1` the view is filtered to the stacks with that label.

If I login to rancher as a regular user (not admin) I see this in the STACKS top level menu:

```
All
```

So the labels are not displayed and there is no way to filter by label. What I expected to see as a regular user is:

```
All
--
Label1
Label2
Label3
```

However the regular user can still edit labels on the stacks, only he does not get the option in the `STACKS` menu to filter by them. Not sure if this is a bug,  working as intended, or if I have some misconfiguration.

**Comment by tfiduccia** [comment]
Version - v1.6.15-rc6
Verified fixed
