### ISSUE TITLE
Unable to specify empty logging option. 

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#9912]
**Rancher versions:**
rancher/server: 1.6.9
rancher/agent: 1.2.6

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
17.06.0

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

```
4.4.0-83-generic
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA Rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Try and use an custom log driver and set a log option that's empty.

**Results:**
It'll remove the logging option.

**Expected Results:**
I need to be able to clear the `tag` logging option when using my custom logger. But if I try and set it to nothing, Rancher just removes the option entirely.

**Comment by aemneina** [comment]
@ekristen are you removing the logging field from the UI? Just trying to figure out what component this maps to in rancher.
