### ISSUE TITLE
[cli] "rancher run" missing/can't add service links when adding new service to existing stack

### ISSUE THREAD

**Issue by danibjor** [rancher/rancher#9913]
**Rancher versions:**
rancher/server: v1.6.9
rancher/agent: rancher/agent:v1.2.6

**Infrastructure Stack versions:**
healthcheck: rancher/healthcheck:v0.3.3
ipsec: rancher/net:holder rancher/net:v0.11.9
network-services: rancher/network-manager:v0.7.8 rancher/metadata:v0.9.4
scheduler: rancher/scheduler:v0.8.2
kubernetes (if applicable):

**Rancher CLI:**
rancher-v0.6.4 

**Docker version: (`docker version`,`docker info` preferred)**
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 20:00:17 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:59:11 2017
 OS/Arch:      linux/amd64
 Experimental: false

Containers: 28
 Running: 25
 Paused: 0
 Stopped: 3
Images: 31
Server Version: 17.06.2-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 305
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local rancher-nfs
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-87-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 7.753GiB
Name: ubuntu-rancher-dell-01
ID: JD6E:EKNQ:HVJH:AMBZ:CGY3:XPNP:WWYY:4JPC:3576:7M6C:YNWH:3O7Y
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

4.4.0-87-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
1x Bare-metal
3x VirtualBox (on MacOS)

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Container (non-HA)- Bind mounted MySQL volume

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Rancher-CLI (MacOS)

`./rancher run some/image --name my-existing-stack/new-service-name --service-link some-stack/some-db:mongodb `

**Results:**
new service gets added to stack, but have to manually add ServiceLink. 

There should be a way to add a service-link programmatically when creating new services and adding those to an existing system. 

Only way I see to do this right now is creating a new Service, with both my api and (a new) database. There is no way to re-use the existing database in the stack (or another stack).

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
