### ISSUE TITLE
Feature Request - ability to Execute Shell as a different user

### ISSUE THREAD

**Issue by junkiebev** [rancher/rancher#9914]
Docker supports running an exec command as a different user. 
Example: 
    `docker exec -it --user root CONTAINER /bin/bash` 
would launch /bin/bash as the user root inside container CONTAINER

1) Is it possible to support this feature in a future release?
2) (probably a duplicate) Would it possible to specify the exec shell in a future release?

Thanks!

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.9` Cattle: `v0.183.21` UI: `v1.6.23` |
|Access|`ldap` `admin`|
|Orchestration|`Cattle`|
|Route|`stacks.index`|

**Comment by aemneina** [comment]
assuming this is for the UI, is that correct @junkiebev ?

**Comment by junkiebev** [comment]
@aemneina  - Sorry, I just noticed this! Yes it is.

**Comment by kdebisschop** [comment]
I'd love to see this as a feature as well - connecting as root is not making our Security teams super happy.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
