### ISSUE TITLE
Feature request: Deploy only one load balancer for K8 ingresses with a common ip/port

### ISSUE THREAD

**Issue by rbq** [rancher/rancher#9915]
**Versions:**
rancher/server: 1.6.9
rancher/agent: 1.2.6
Kubernetes: v1.7.4-rancher1 (?)

Hi there, I'd like to allow multiple users to deploy their own apps on a shared cluster. Each user should be able to create their own ingresses and I need them to be deployed as a single load-balancer with host-based/SNI.

Current behaviour: If you create two ingresses for different host-names, two load balancers are deployed. Only the first one works. The (non-matching) rest of the traffic will never reach the second load-balancer.

Ideal behaviour: If two ingresses are scheduled to the same host, only one load balancer should be created. It should bind to all the ports specified, take into account all the host/path rules and route incoming traffic to the correct service. More specific rules should probably take precedence over more general ones, so that an ingress without any rules doesn't accidentally steal all the traffic for the whole cluster.

Does that make sense?

**Comment by rbq** [comment]
@aemneina: No, that is an entirely different feature. I wasn't talking about routing traffic to different clusters. AFAIK the behaviour I'm asking for is actually the default when using stock K8 plus Nginx/Traefik.

**Comment by rbq** [comment]
Here is an [example for ordering (host-based) Ingress rules in Traefic](https://docs.traefik.io/user-guide/kubernetes/#specifying-priority-for-routing). This wouldn't be possible if multiple load-balancers were deployed.

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.
