### ISSUE TITLE
lb-service-haproxy shows "Failed to initialize Kubernetes controller: KUBERNETES_URL is not set" in log

### ISSUE THREAD

**Issue by shukla2009** [rancher/rancher#9916]
**Rancher Version:**

Rancher	v1.6.5
Cattle	v0.182.1
User Interface	v1.6.9
Rancher CLI	v0.6.2
Rancher Compose	v0.12.5

Agent : rancher/agent:v1.2.5
Server: rancher/agent:stable
ha-proxy :lb-service-haproxy:v0.7.6 

**Docker Version:**

17.03.2-ce, build f5ec1e2

**OS and where are the hosts located? (cloud, bare metal, etc):**
rancheros-v1.1.0-hvm-1 - ami-4866042b on AWS

**Environment Type:**
Cattle

**Logs:**
```
20/09/2017 02:43:42time="2017-09-19T21:13:42Z" level=error msg="Failed to initialize Kubernetes controller: KUBERNETES_URL is not set"
20/09/2017 02:43:42time="2017-09-19T21:13:42Z" level=info msg="Starting Rancher LB service"
20/09/2017 02:43:42time="2017-09-19T21:13:42Z" level=info msg="LB controller: rancher"
20/09/2017 02:43:42time="2017-09-19T21:13:42Z" level=info msg="LB provider: haproxy"
20/09/2017 02:43:42time="2017-09-19T21:13:42Z" level=info msg="starting rancher controller"
20/09/2017 02:43:42time="2017-09-19T21:13:42Z" level=info msg="Healthcheck handler is listening on :10241"
20/09/2017 02:43:43time="2017-09-19T21:13:43Z" level=info msg=" -- starting haproxy\n * Starting haproxy haproxy\n[WARNING] 261/211342 (36) : config : 'option forwardfor' ignored for proxy 'default' as it requires HTTP mode.\n[WARNING] 261/211342 (37) : config : 'option forwardfor' ignored for proxy 'default' as it requires HTTP mode.\n   ...done.\n"
```

**Comment by luisehk** [comment]
Yeah, the same is happening to me too... since yesterday for some random reason.

**Comment by cjellick** [comment]
@shukla2009 @luisehk what rancher/server version? The information provided in the original comment is inaccurate. To get the relevant version info, for the rancher UI, you can click the version number in the bottom left and copy and paste the contents.

**Comment by luisehk** [comment]
rancher/rancher:latest

I found it only happens when I add multiple hosts to my environment. If I switch back to one host, load-balancer works again.

**Comment by cjellick** [comment]
Sorry, but rancher/rancher:latest doesnt give me enough information actually (we move the latest tag, so it could point to any number of releases)

**Comment by shukla2009** [comment]
Updated rancher version

**Comment by at-daonguyen** [comment]
Me too. Today this error occurs after I restart load balancer.

**Comment by huggla** [comment]
I got this error too after upgrade to v1.6.10. Tried to downgrade to v1.6.7 but the problem persists.

**Comment by cjellick** [comment]
```
Load balancer not working (Failed to initialize Kubernetes controller: KUBERNETES_URL is not set) 
```

this message is misleading. Not really an error. We'll knock that down to debug. Can you describe the symptoms you are experiencing outside of the log statement?

**Comment by alena1108** [comment]
@kinarashah we should change the log level for this message:
```
20/09/2017 02:43:42time="2017-09-19T21:13:42Z" level=error msg="Failed to initialize Kubernetes controller: KUBERNETES_URL is not set"
```
as it is simply an indication that k8s controller skips initializing, because rancher controller is chosen.

@cjellick luisehk  LB not working might be a different issue, this error message shouldn't affect the behavior. If the LB gets stuck in initializing state, in most of the cases - especially when there are multiple hosts in the system - it means that the healthcheck for LB is failing due to cross hosts communication failures.

**Comment by luisehk** [comment]
Sorry I can't provide more info, I moved my services from Rancher.

The error happened when adding a new host to my single-host setup. If I removed the new host, load balancer would work again.

I added the new host using the web interface, didn't do any extra steps through the CLI.

Hope that helps.

**Comment by at-daonguyen** [comment]
I discover `cni-driver` service failed on the host which HAProxy service schedule on. I try to stop all services. Stop all `cni-driver` containers (I cannot stop this service). Start all services again (Infra first). Then HAProxy work well again. Hope this help.

**Comment by f3l1x** [comment]
Hi, is there any way how to solve it? 

LB version: `rancher/lb-service-haproxy:v0.7.9`

**Comment by lfoppiano** [comment]
Guys, I'm having the same problem. I'm using haproxy 0.7.9 with rancher 1.6.0. 

I was thinking to update to version 0.7.15 but apparently if I have understand from @alena1108 it seems a problem between the multiple hosts, however I have no idea where to start looking...  

First, stupid question, any idea if is possible to increase the log level? I cannot touch the instance, as I'm the one managing it. Is there a way to change the log levels from the settings? 

Second, I have two hosts one public and one private, the public is supposed to have the load balancer and the instances while the private to have the containers holding the internal services (like healthchecks and so on). 

Also, I have a load balancer on the public host which is mapped from the port 443 with the /xyz entrypoint poiniting to a deployed container on the same host on port 8080 (not the same port).  

Any idea where should I start having a look? 
I know I'm not giving enough information, please feel free to ask if I have not mentioned something important. Unfortunately not having access and familiarity with the tool make it more difficult to write meaningful comments. :-(

**Comment by superseb** [comment]
This is becoming an aggregation of issues, while the log message is not telling us anything. I marked this an enhancement.

For other issues, please ensure cross host networking is working properly (http://rancher.com/docs/rancher/v1.6/en/faqs/troubleshooting/#cross-host-communication). If this is the case, please file a new issue describing what isn't working as expected with all the relevant versions and information to reproduce.

**Comment by lfoppiano** [comment]
@superseb thanks. 

I've tried to ping some random container and they seems to work, it's mentioned the following: 
`Every so often, the IP of the host will accidentally pick up the docker bridge IP instead of the actual IP. These are typically 172.17.42.1 or starting with 172.17.x.x. If this is the case, you need to re-register your host with the correct IP by explicitly setting the CATTLE_AGENT_IP environment variable in the docker run command.`

When I look the hosts configuration I have the main host (the one I connect to play around) which has actually ip 172.17.X.Y, while the second host (private) have 134.158.Z.W... does this means that the main host picked up the wrong ip address?

**Comment by superseb** [comment]
The overlay network is built using the IP's show in the `Infrastructure` -> `Hosts` view, these should be the correct IP's (no duplicates, no docker0 IP's, just the private or public IP of the machine where they can all reach other on to build the overlay network)

**Comment by arturslogins** [comment]
Any update about this issue???

**Comment by cjellick** [comment]
@arturslogins as @superseb pointed out, this issue ended up having multiple unrelated issues, some of which weren't exactly valid. Can you give more details on the specific problem you are having? You might even be better served by opening a new issue and fully completing the issue template.

**Comment by superseb** [comment]
Locking this, this issue is to get the unneeded log line removed to avoid any confusion when lb-service-haproxy is started. Any functional issues, please file a new issue so we can take a look.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
