### ISSUE TITLE
On editing AD settings after auth is enabled, ldap timeout is not in milliseconds

### ISSUE THREAD

**Issue by mrajashree** [rancher/rancher#9920]
**Rancher versions:**
rancher/server: v1.6.10
rancher/agent:

**Steps to reproduce**
1. Setup AD auth 
2. Click `Edit` on Access Control page
3. Enter password and hit `Test and Save`
4. Test query timeout

**Expected**
Connection timeout should be followed

**Comment by deniseschannon** [comment]
available in rancher-auth-service v0.4.20

**Comment by galal-hussein** [comment]
Rancher server v1.6.11-rc1
Tested query timeout after edit the settings and the timeout still in milleseconds.
