### ISSUE TITLE
Unable to edit AD settings if test account's password contains ':'

### ISSUE THREAD

**Issue by mrajashree** [rancher/rancher#9921]
**Rancher versions:**
rancher/server: v1.6.10

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
1. Configure AD auth with test account containing `:` in its password
2. Click on `Edit` to edit settings, enter passwords (Service account and user)
3. Click on `Test and Save`

**Results:**
Invalid credentials error

**Expected**
Edit settings should work

**Comment by pulberg** [comment]
This happens in v1.6.9 as well.

**Comment by deniseschannon** [comment]
available in rancher-auth-service v0.4.20

**Comment by galal-hussein** [comment]
Rancher v1.6-development

- Configure AD auth with test account containing : in its password
- Click on Edit to edit settings, enter passwords (Service account and user)
- Click on Test and Save

The setup edited successfully and no issues found.
