### ISSUE TITLE
Unable to use Edit settings after AD auth is enabled if username contains domain as prefix

### ISSUE THREAD

**Issue by mrajashree** [rancher/rancher#9922]
**Rancher versions:**
rancher/server: v1.6.10

**Steps to Reproduce:**
1. In 1.6.7 setup AD auth by providing test username prefixed with default login domain
2. Upgrade to 1.6.10
3. Go to `Edit` on Access control page to edit settings
4. Enter passwords and hit `Test and Save`

**Results:**
Failed to get auth token

**Expected**
Edit settings should work

**Comment by deniseschannon** [comment]
available in rancher-auth-service v0.4.20

**Comment by galal-hussein** [comment]
Rancher Server: v1.6-development

Tested the following scenario:

- Enable AD auth by providing test username prefixed with default login domain
- Upgrade to 1.6.10
- Go to Edit on Access control page to edit settings
- Enter passwords and hit Test and Save

The setup edited successfully with no problem.

**Comment by galal-hussein** [comment]
@mrajashree on Rancher v1.6-development i tried the following:

- Enable AD with sauser testad\sauser and with user testad\testuser1
- Edit the setup and enter the passwords (i noticed that testuser1 is testuser1 not testad\testuser1)
- click save

i get an error:
```
Error in ldap bind: LDAP Result Code 49 "Invalid Credentials": 80090308: LdapErr: DSID-0C09042F, comment: AcceptSecurityContext error, data 52e, v2580
```

**Comment by galal-hussein** [comment]
Rancher server: v1.6.11-rc4

- Enable AD with sauser testad\sauser and with user testad\testuser1.
- Edit the setup and enter the passwords.
- Click save.

I was able to edit settings successfully and no error happened.
