### ISSUE TITLE
IPsec service fails to start: Timeout getting IP address

### ISSUE THREAD

**Issue by oliverorav** [rancher/rancher#9923]
**Rancher versions:**
rancher/server: v1.6.5
rancher/agent: v1.2.5

**Infrastructure Stack versions:**
healthcheck: v0.3.0
ipsec: v0.1.0
network-services: v0.2.0
scheduler: v0.5.1

**Docker version: (`docker version`,`docker info` preferred)**
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:23:59 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:23:59 2016
 OS/Arch:      linux/amd64

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Red Hat Enterprise Linux Server release 7.3 (Maipo), 3.10.0-693.1.1.el7.x86_64

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node with external MariaDB. 

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Issue**
The issue is same to [https://github.com/rancher/rancher/issues/8383](8383) that ipsec service doesn't start, but currently any of the solutions provided in there or other issues do not work. 
**Logs pointing to the problem**
network-manager:
`msg="rancher id [92651]: Container with docker id [c9788207780e6a48f4b52ce19147cf4b9f58936386910253d1b466ad49858537] has been started" 
msg="Error processing event" err=Timeout getting IP address eventId=12024d88-30b8-4187-984a-55a0e1ee6a21 eventName=compute.instance.activate resourceId=1ihm2941 
msg="Received event: Name: compute.instance.activate, Event Id: 4862de72-fab3-4799-888c-db08f5a4ec45, Resource Id: 1ihm2941" 
time="2017-09-21T06:46:51Z" level=error msg="Error processing event" err=Timeout getting IP address eventId=4862de72-fab3-4799-888c-db08f5a4ec45 eventName=compute.instance.activate resourceId=1ihm2941 
`
network-manager:
`msg="Failed to evaluate network state for a76c852397d1cc42a3eb187bf054cd786dbf726c12fede2dafaa5f3ce5288359: Get http://rancher-metadata/2015-12-19/version: dial tcp: i/o timeout"`

Issue came after our production servers where updated, but we cannot pinpoint exact application/lib update that caused the issue (the agent and infra services work in our development environments with the same updates). When one of the production machines updates were rolled back, it started to work again, but like said we cannot find the exact cause. AFAIK the updates contained some security patches also and therefore rolling back all the servers could cause security risks. 
Could anybody give extra information and tips how to debug and what to look for more or what else to try.

**Comment by Toonix** [comment]
did you restart network services and heal check?

**Comment by oliverorav** [comment]
We still haven't found out what causes the problem. 
Currently the only solution we fond for the problem is that we do updates to our servers, roll-back said updates and run the update process again. This suggests that the problem might not be in Rancher per se, but in the order in which RHEL package manager installs the updates.

**Comment by Joni-Lover** [comment]
try to downgrade kernel to 3.10.0-514. It's work for me.
