### ISSUE TITLE
IPsec infra service unable to start on an added host(ppc64le)

### ISSUE THREAD

**Issue by ghatwala** [rancher/rancher#9925]
**Rancher versions:**
rancher/server:v1.6.7
rancher/agent:v.1.2.5

**Infrastructure Stack versions:**
healthcheck:v0.3.1
ipsec: 0.1.3
network-services: v0.2.5
scheduler: v0.6.3
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
on server
```
# docker info
Containers: 25
 Running: 1
 Paused: 0
 Stopped: 24
Images: 157
Server Version: 1.12.6
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 294
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host null overlay bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.13.0-24-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.955 GiB
Name: hj-ibmibm519
ID: TSFV:REUE:WLNE:73H2:UMYV:NR2M:2JXS:G6RN:WI2U:JRFA:627C:IFFP
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
WARNING: No kernel memory limit support
Insecure Registries:
 127.0.0.0/8
```
On host ( ppc64le ) added
```
# docker info
Containers: 8
 Running: 6
 Paused: 0
 Stopped: 2
Images: 61
Server Version: 17.06.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 93
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-38-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: ppc64le
CPUs: 1
Total Memory: 7.973GiB
Name: pts00449-vm29
ID: RWB6:DCET:ZA6A:FKFH:BZWQ:H6WV:COQP:2BZB:SACV:HAIK:M66M:YFAV
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
on server
```
# uname -r
3.13.0-24-generic

# cat /etc/os-release
NAME="Ubuntu"
VERSION="14.04.5 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.5 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
```
on host
```
# cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.1 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.1 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
UBUNTU_CODENAME=xenial

# uname -r
4.4.0-38-generic
```

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node 

**Steps to Reproduce:**
https://forums.rancher.com/t/ipsec-infrastructure-stack-service-unable-to-start-on-added-host/7354

**Results:**
Attaching the logs as per link : https://github.com/rancher/rancher-logs-collector

hi @leodotcloud , please check the log and other details above.

**Comment by ghatwala** [comment]
[rancher.logs.RgOdtg.zip](https://github.com/rancher/rancher/files/1322285/rancher.logs.RgOdtg.zip)
please ignore the previous log and consider this to be the latest one @leodotcloud

**Comment by leodotcloud** [comment]
@ghatwala Just saw you mentioned `Architecture: ppc64le`. I don't think we have support for PPC. I am not sure if there is full support from Docker itself. If you need special support for PPC, please feel free to reach out to our Sales team.

**Comment by ghatwala** [comment]
> "There  is a lot of work involved to get all the microservices cross compiled and rebuild all of the infra containers using the PPC Base images." 

 fyi we have ported the few infra services( healthcheck,scheduler, ipsec network-services,network-policy manager to power already . the docker image for these are present here already : https://hub.docker.com/u/zambon/ . Also the list of PR's created thus far are here : https://github.com/rancher/rancher/issues/9751.

Now the only issue we are facing is the we are unable to find the reason y the 3 docker containers of ipsec are unable to boot up successfully on power. The ipsec's cni-driver docker container is booting successfully on power(ppc64le) , however the problem is with the other 2.

**Comment by leodotcloud** [comment]
Oh wait, did I interact either with you or one of your team members few days back.

> jiust fyi we have ported the few infra services( healthcheck,scheduler, ipsec network-services,network-policy manager to power already . the docker image for these are present here already : https://hub.docker.com/u/zambon/ . Also the list of PR's created thus far are here : #9751. 

Thanks for the awesome work! Didn't get a chance to take a look at the PRs.

Can you please ping me on Slack directly, we can jump on a call and take a look at your setup.

**Comment by ghatwala** [comment]
@leodotcloud : so the issue has been fixed now , thanks for sparing time to screen share with me to debug this . Now all infrastructure services(network-policy manager , network-services, ipsec , healthcheck ,scheduler) are up and running on added host (pps64le) .  Appreciate all the help received from your end!!!
