### ISSUE TITLE
Rancher server not staring after stop because of mysql

### ISSUE THREAD

**Issue by jgato** [rancher/rancher#9926]
**Rancher versions:**
rancher/server: 1.6.2

I have been trying to make a backup of rancher server volume. So I stopped my rancher server, I did some backups of /var/lib/mysql, and so on... After a while, I restarted the rancher server container and now it is not working, it just shows an extrange error from mysqld:

```
170921 14:53:29 [Note] /usr/sbin/mysqld (mysqld 5.5.55-0ubuntu0.14.04.1) starting as process 25 ...
170921 14:53:38 [Note] /usr/sbin/mysqld (mysqld 5.5.55-0ubuntu0.14.04.1) starting as process 26 ...
170921 14:53:53 [Note] /usr/sbin/mysqld (mysqld 5.5.55-0ubuntu0.14.04.1) starting as process 25 ...
170921 14:54:20 [Note] /usr/sbin/mysqld (mysqld 5.5.55-0ubuntu0.14.04.1) starting as process 25 ...
```

I am pretty sure I didnnt touch anything in the Volume, I just did a tar to be used in other volumes for a backup/restore purpose. Any help?

**Comment by cjellick** [comment]
Maybe you're out of diskspace on the host? Just a shot in the dark.

**Comment by jgato** [comment]
Yes it was that, good pointing besides of the dark ;) many thanks
