### ISSUE TITLE
Rancher stuck during launching Swarm (swarmkit) -- duplicates #7774

### ISSUE THREAD

**Issue by denizin** [rancher/rancher#9927]
**Rancher versions:**
rancher/server: 1.6.5
rancher/agent: 1.2.5

**Infrastructure Stack versions:**
healthcheck: 0.3.0
ipsec: 0.1.1
network-services: 0.2.3
scheduler: 0.6.3
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
Containers: 14
 Running: 13
 Paused: 0
 Stopped: 1
Images: 47
Server Version: 17.06.0-ce
Storage Driver: devicemapper
 Pool Name: docker-thinpool
 Pool Blocksize: 524.3kB
 Base Device Size: 10.74GB
 Backing Filesystem: xfs
 Data file: 
 Metadata file: 
 Data Space Used: 12.03GB
 Data Space Total: 204GB
 Data Space Available: 192GB
 Metadata Space Used: 6.177MB
 Metadata Space Total: 2.143GB
 Metadata Space Available: 2.137GB
 Thin Pool Minimum Free Space: 20.4GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: i0rw0byfv2aiszikt3h51ue3y
 Is Manager: false
 Node Address: 
 Manager Addresses:
  172.27.2.67:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.26.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 62.5GiB
Name:
ID: LP2X:5RXC:BVSW:MFIK:2JTE:LWPN:TH4S:Y7RG:QA2T:5FR5:LANO:GEPD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
3.10.0-514.26.2.el7.x86_64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA Rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Swarm

**Steps to Reproduce:**
 Initializing	swarm-swarmkit-mon-3 
Just stuck in that state always.  So the entire swarm infrastructure doesn't start in the Rancher gui.

9/18/2017 4:57:37 PMAdding ca.crt to Certs.
9/18/2017 4:57:37 PMWARNING: ca-certificates.crt does not contain exactly one certificate or CRL: skipping
9/18/2017 4:57:37 PMtime="2017-09-18T20:57:37Z" level=info msg="Listening on port: 2378"
9/18/2017 5:06:46 PMtime="2017-09-18T21:06:46Z" level=info msg="Listening on port: 2378"
9/19/2017 7:59:19 PMMetadata not ready
9/19/2017 7:59:25 PMMetadata not ready
9/19/2017 7:59:31 PMMetadata not ready
9/19/2017 7:59:37 PMMetadata not ready
9/19/2017 7:59:43 PMMetadata not ready

Any questions on how to move this 1 out of 4 swarm-swarmkit-mon's out of initializing?   I don't even know where to start.  Thank you.

**Comment by denizin** [comment]
What it looks like is all docker worker nodes can't join the swarm:

jq: error (at <stdin>:1): Cannot index string with string "Description"
jq: error (at <stdin>:1): Cannot index string with string "Spec"
jq: error (at <stdin>:1): Cannot index string with string "Spec"
jq: error (at <stdin>:1): Cannot index string with string "Spec"
/opt/rancher/run.sh: line 245: + : syntax error: operand expected (error token is "+ ")

**Comment by gaui** [comment]
Same problem here, the other nodes hang when joining the swarm. It works if I manually initialize the Swarm and then manually join the Swarm on the servers before setting up the agents.
