### ISSUE TITLE
enable vsphere as a cloud provider for kubernetes

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#9931]
Enable the use of vsphere as a Kubernetes cloud provider. Looking to use persistent volume claims against that vsphere provider.

**Comment by danielhass** [comment]
Any updates/plans on this one? I would love to see this feature in an upcoming release.

**Comment by frenchtoasters** [comment]
Is there any update on this issue?

**Comment by spawnia** [comment]
This can be done now as of #13115, although i must say the configuration is a bit rough and the support is spotty.

**Comment by deniseschannon** [comment]
This can already be done as of v2.0.3. You can edit the yaml when creating clusters and add in the cloud provider. 

Docs on how to do it: 
https://rancher.com/docs/rke/v0.1.x/en/config-options/cloud-providers/
