### ISSUE TITLE
Network problem on Docker DIND with managed network

### ISSUE THREAD

**Issue by disaster37** [rancher/rancher#9933]
**Rancher versions:**
rancher/server:1.6.7
rancher/agent:1.2.5

**Infrastructure Stack versions:**
healthcheck: rancher/healthcheck:v0.3.1
ipsec: rancher/net:v0.11.7
network-services: rancher/network-manager:v0.7.7
scheduler: rancher/scheduler:v0.8.2
kubernetes (if applicable): NA

**Docker version: (`docker version`,`docker info` preferred)**
Server Version: 17.06.2-ce
Storage Driver: btrfs
 Build Version: Btrfs v3.17
 Library Version: 101
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Kernel Version: 4.9.0-0.bpo.3-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.64GiB
Name: node-03
ID: I5QJ:RZ6D:NB37:4FPI:6GFA:IG7N:B2QM:RY4V:CNZ2:MJ2Q:VBVT:OGZT
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

4.9.0-0.bpo.3-amd64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher and external DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Run new stack with service "docker dind" (docker in docker) with full privilledge and network managed.
You can use this image : index.docker.io/docker:17.07-dind
Go to the shell and run `docker run -ti debian /bin/bash`
Finnaly run `apt-get update`

**Results:**
The update break and you get time out.
If you do the same think with bridge network (instead of managed), all works as expected.

**Comment by disaster37** [comment]
It's the same problem on rancher 1.6.10 (maybee it's more problem)

**Comment by nicholasdille** [comment]
Hi, I am having the same issue on Rancher 1.6.9. I haven't seen this on Rancher 1.4.3 before we upgraded

**Comment by disaster37** [comment]
Yes, it's the same for me. I have found a little hack to work.
I use docker:dind as sidekick service of my main service (that contain docker cli) and I set my docker:dind service to use bridge network.

**Comment by nicholasdille** [comment]
@disaster37 Interesting... is this your solution to be able to talk to containers in the 10.42. network?

**Comment by nicholasdille** [comment]
Any updates?

**Comment by nicholasdille** [comment]
Has this been solved in a later version of Rancher 1.6?

**Comment by nicholasdille** [comment]
That's a pity. So is Rancher 2 the only way out of this bug for the time being?

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
