### ISSUE TITLE
Logs of failing containers

### ISSUE THREAD

**Issue by blar** [rancher/rancher#9935]
**Rancher versions:**
rancher/server: v1.6.10
rancher/agent:

**Infrastructure Stack versions:**
healthcheck: v0.3.3
ipsec: v.0.11.9
network-services: v0.9.4
scheduler: v0.8.2

**Docker version: 17.06.1-ce**

**Operating system and kernel: Debian 8.x**

**Type/provider of hosts: Bare-metal**

**Setup details: (single node rancher, external DB)**

**Environment Template: Cattle**

**Steps to Reproduce:**

Deploy a failing docker image

**Results:**

Containers restarts in loop. You cannot watch the log output of the container because the gui update the context menu and hide the "View Logs". With the rancher-cli it is possible to view the logs of the failing container.

**Comment by aemneina** [comment]
preserve flapping logs in ui as a feature?

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
