### ISSUE TITLE
Fix the agent provider backoff and improve the notify message

### ISSUE THREAD

**Issue by aiwantaozi** [rancher/rancher#9936]
**Rancher versions:**
rancher/server: 1.6
rancher/agent: 1.6

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)** 
1.12.6
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
ubuntu 16.04
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VirtualBox
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
**Problem**
1. Confusing logging information, need clear log info.
2. Retry backoff interval now is 500 microsecond, the unit is too small.
3. There is not a flag to control the agent to get host info or not.

**Results:**
**TODO**
1. fix the back off for both providers, set to 30 seconds * 6 times
2. Adding clear logging to explain what we are doing if it doesn't already exist, like `"Detecting cloud provider"` `"Checking for AWS metadata provider"` ... `"Now cloud provider detected"`
3. Adding the env var flag to turn the clould provider off in the bootstrap container https://github.com/rancher/rancher/blob/v1.6/agent/run.sh#L163-L178
```
 docker run -e CATTLE_DETECT_CLOUD_PROVIDER=false ... rancher/agent
```

@yasker 
Inside the agent, it will receive the ping event and handle it, if the ping event does not include the data "options", "resources", it will not get the host lablel.
https://github.com/rancher/agent/blob/v1.6/core/ping/ping_common.go#L33
https://github.com/rancher/agent/blob/v1.6/core/ping/ping_common.go#L188
The ping event  include some data like this:
```
time="2017-09-24T11:54:35Z" level=info msg="Received event: Name: ping, Event Id: e3c9ce25-5ef3-4005-b539-8a9f42f59b20, Resource Id: 1a1, Type agent, data map[options:map[instances:true resources:true] resources:[]]"
```
The ping event not  include some data like this:
```
time="2017-09-24T11:55:36Z" level=info msg="Received event: Name: ping, Event Id: fc5cbafd-76c8-4f58-bf0d-160fd203771d, Resource Id: , Type , data map[options:map[] resources:[]]"
```
I could see the agent get the ping event have data each minute, this will try to ready the data from info.json.
![image](https://user-images.githubusercontent.com/5936271/30782346-17b10b1a-a0f6-11e7-973e-8e9098d7951f.png)

**Comment by aiwantaozi** [comment]
@cjellick @yasker Really thanks for your help for the cloud provider, this issue is for improving the cloud provider. I'm very sorry for the problems I caused.

Just add two PR to fix them.
https://github.com/rancher/agent/pull/240
https://github.com/rancher/rancher/pull/9937
Welcome to comment.

**Comment by yasker** [comment]
If the resource will only refresh once per minutes, it doesn't necessary to try once per 30 seconds for the metadata. But I guess the cost is low enough for 30 seconds.

**Comment by aiwantaozi** [comment]
@yasker There is two-step:
1. generate the hostInfo.json file by the cloud provider(now we set to retry once per 30 seconds)
2. get the host info from hostInfo.json, trigger by rancher ping event (get ping event once per minutes)

**Comment by aiwantaozi** [comment]
@yasker Just update the control cloud provider flag inside the agent, could help review?

**Comment by kingsd041** [comment]
@aiwantaozi 
Tested with rancher-server version- v1.6.10 with micheliac/agent:v1.2.6 

Test passed！
But I used micheliac/agent:v1.2.6 image and .agent:v1.6 branch.

**Comment by cjellick** [comment]
For changes that are affecting mainline rancher, I want to make sure we coordinate QA between the US and CN teams.

Ping @sangeethah @deniseschannon

**Comment by deniseschannon** [comment]
Available with rancher/agent:v1.2.7-rc1

**Comment by cjellick** [comment]
@kingsd041 why did this get reopened? What issue did you discover?

**Comment by kingsd041** [comment]
@cjellick   Sorry, I clicked the wrong button.

**Comment by kingsd041** [comment]
@yasker 

**Rancher versions:**
rancher/server: v1.6.11-rc2
rancher/agent: v1.2.7-rc2
**Docker version:**
17.06.2-ce

Test passed.
