### ISSUE TITLE
SSL Rancher Managed network 

### ISSUE THREAD

**Issue by ivo5307** [rancher/rancher#9938]
**Rancher versions:**
rancher/server: 1.6.7
rancher/agent: 1.2.6

**Infrastructure Stack versions:**
healthcheck: Green OK
ipsec: Yes Green
network-services: Yes green
scheduler: Yes green
kubernetes (if applicable): Yes running

**Docker version: (`docker version`,`docker info` preferred)** 1.2.3

Issue that i am having is seems Managed network is responsible for intermittent SSL issues
talking with a jenkins server 

I am getting

 * Unknown SSL protocol error in connection to jenkins.machine.com:8443
* Closing connection 0
curl: (35) Unknown SSL protocol error in connection to jenkins.machine.com:8443 

However only around 30-40% of the time, the rest 50-60% i am getting what i expect

 * Server certificate:
*      subject: C=US; ST=New York; L=Armonk; O=Company Corp.; CN=*.devops.com
*      start date: 2017-03-22 00:00:00 GMT
*      expire date: 2020-06-13 23:59:59 GMT
*      issuer: C=US; O=GeoTrust Inc.; CN=GeoTrust SSL CA - G3
*      SSL certificate verify ok. 

When i tried using minikube kubernetes with bridged network -> 100% of the time OK.

If somebody knows rancher networking appreciate any help.
could you show me how to swithch everything to bridged networking in rancher without losing DNS and other stuff.

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
