### ISSUE TITLE
Site Access doesn't get saved to database

### ISSUE THREAD

**Issue by Toonix** [rancher/rancher#9940]
After Upgrade from Rancher 1.3.4 to 1.6.10 site Access changes are not saved in the database. After restarting Rancher, the settings are back like after the migration.

Authentication settings get saved, but any users added to Site Access are lost.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.10` Cattle: `v0.183.22` UI: `v1.6.23` |
|Access|`ldap` `admin`|
|Orchestration|`Cattle`|
|Route|`admin-tab.auth.activedirectory`|

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
