### ISSUE TITLE
Add a NFS storage volume to a container

### ISSUE THREAD

**Issue by SivaIntegrator** [rancher/rancher#9941]
**Rancher versions:**
rancher/server: v1.6.7
rancher/agent: v1.6.7

**Docker version: (`docker version`,`docker info` preferred)**
17.04

**OS and where are the hosts located? (cloud, bare metal, etc):**
boot2dockerm vsphere VM's, private cloud.

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
3.10.0-514.2.2.el7.x86_64

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
External NFS server (Synology)

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Deploy a rancher nfs storage with the server IP address and its Export data folder
Create a volume (inactivate)
Create a container, in its Volume Driver: "rancher-nfs" inserted

**Results:**
The container has a timeout getting IP address

Actually, I'm beginner on Rancher, I'm using its web interface.
I have my host, I think my Rancher-nfs storage is well configured, I created a volume X from it. But i'm not sure to do it well about adding this volume X to a new container.
Can you please help me on this point?

Thanks by advance

**Comment by cjellick** [comment]
Can you deploy containers without an NFS volume? The "timeout getting IP address" error is generally unrelated to storage issues.

**Comment by cjellick** [comment]
Closed by accident. Misclicked

**Comment by SivaIntegrator** [comment]
I've just tried and I had the same error...

**Comment by aemneina** [comment]
Can you start your container without the nfs volume? Do you get timeout getting ip address there?

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
