### ISSUE TITLE
Internal DNS lookup fails for linked service names in services with net=host

### ISSUE THREAD

**Issue by jrohde** [rancher/rancher#9943]
**Rancher versions:**
rancher/server: 1.6.7
rancher/agent: 1.2.5

**Infrastructure Stack versions:**
healthcheck: 0.3.0 (template version)
ipsec: 0.1.3 (template version)
network-services: 0.2.5 (template version)
scheduler: 0.6.3 (template version)

**Docker version:**
17.06.1-ce

**Operating system and kernel:**
RancherOS v1.1.0 / 4.9.45-rancher

**Type/provider of hosts:**
Bare-Metal * 3

**Setup details:**
Single Node, internal DB

**Environment Template:**
Cattle

**Steps to Reproduce:**
1. Create serviceA in stack1
2. Create serviceB in stack2 with **host networking** and io.rancher.container.dns:true checked
3. Link serviceA to serviceB as linkA
4. Ping linkA from container(s) in serviceB

**Results:**
No ping/resolv.
I do can ping 'serviceA.stack1.rancher.internal' so it looks like it's just the alias resolving which is broken.
On services with managed networks all is good.

**Additional info:**
resolv.conf of the net=**host** container:

```
# cat /etc/resolv.conf 
# nameserver 8.8.8.8
# nameserver 8.8.4.4
search serviceB-1.stack2.rancher.internal stack2.rancher.internal rancher.internal
nameserver 169.254.169.250
```
...and a **managed** container:

```
# cat /etc/resolv.conf 
search stack2.rancher.internal serviceB-1.stack2.rancher.internal rancher.internal
nameserver 169.254.169.250
```
The order of search domains is switched!?

**Tried fixing by:**
- Manually changing the lookup/search order: no diff.
- Deleting/Restarting metadata+dns services (used to resolve these kind of issues): no diff.

**Current workaround:**
Use the full service.stack.rancher.internal name (e.g. serviceA.stack1.rancher.internal).

100% reproducible on my systems. 
I'm pretty sure though this worked fine before. Anyone ideas?

**Comment by kinarashah** [comment]
Possibly similar to [rancher/rancher#8819](https://github.com/rancher/rancher/issues/8819).

**Comment by vincent99** [comment]
Yes, #8819
