### ISSUE TITLE
Kubernetes 1.7.4 controller-manager behaves like 1.6 for Ceph volume controller

### ISSUE THREAD

**Issue by nielspardon** [rancher/rancher#9944]
**Rancher versions:**
rancher/server: 1.6.9
rancher/agent: 1.2.6

**Infrastructure Stack versions:**
healthcheck: healthy
ipsec: healthy
network-services: healthy
scheduler: healthy
kubernetes (if applicable): healthy

**Docker version: (`docker version`,`docker info` preferred)**
Docker version 1.12.6, build 78d1802

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-Metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher, internal DB, data volume container

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes 1.7.4

**Steps to Reproduce:**

When I try to create a kubernetes.io/rdb storage class in Rancher Kubernetes it does not support the new parameters `imageFormat`, `imageFeatures`, `fsType`.

https://kubernetes.io/docs/concepts/storage/persistent-volumes/#ceph-rbd

**Results:**

It fails with an error message telling me that the parameters are not supported.

**Comment by aemneina** [comment]
That seems to be working in 1.8.0-alpha2 in k8s. This feature appears to have brought that in: Allow StorageClass Ceph RBD to specify image format and image features. [#45805](https://github.com/kubernetes/kubernetes/pull/45805) so I'd say known issue for k8s 1.7.x. I believe k8s 1.8 template is being worked on and probably close to being available, if its not already in an rc.

**Comment by nielspardon** [comment]
I was a little confused that the documentation on kubernetes.io for 1.7 already shows that feature: https://kubernetes-io-v1-7.netlify.com/docs/concepts/storage/persistent-volumes/#ceph-rbd

And seems you are correct. The `release-1.7`branch does not contain that fix: https://github.com/kubernetes/kubernetes/blob/release-1.7/pkg/volume/rbd/rbd_util.go

While the `release-1.8` branch does contain it:
https://github.com/kubernetes/kubernetes/blob/release-1.8/pkg/volume/rbd/rbd_util.go

So I guess the 1.7 documentation is simply wrong for now.
