### ISSUE TITLE
Rancher agents need restart to apply registry password change

### ISSUE THREAD

**Issue by flaccid** [rancher/rancher#9945]
**Rancher versions:**
rancher/server: 1.6.7
rancher/agent: 1.2.5

**Docker version: (`docker version`,`docker info` preferred)**
17.03.0-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
cattle

**Steps to Reproduce:**
With a private registry in Infrastructure | Registries - change the user's password in the registry itself and then update it in Rancher. For the new password to be used on hosts to pull images, the rancher-agent container needs to be restarted.

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
