### ISSUE TITLE
external DB not working: kubectl-shell container don't stay up

### ISSUE THREAD

**Issue by de13** [rancher/rancher#9947]
**Rancher versions:**
rancher/server: **rancher/server:v2.0-alpha6**
rancher/agent: **rancher/agent:v2.0-alpha4**

**Infrastructure Stack versions:**
healthcheck: N/A
ipsec: N/A
network-services: N/A
scheduler: N/A
kubernetes (if applicable): N/A

**Docker version: (`docker version`,`docker info` preferred)**

17.03.2-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

4.9.45-rancher

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

Bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

Single node external DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

N/A (it's K8s)

**Steps to Reproduce:**

Simply bootstrap rancher/server, add host agent on the same host (with the correct CATTLE_AGENT_IP set)

**Results:**

kubectl-shell container don't stay up with error: 

```error on container (1i1341): an error on the server ("") has prevented the request from succeding (get namespace cattle-system)```

**Comment by deniseschannon** [comment]
External DB isn't working in `v2.0.0-alpha6`, which is the cause of your issue.

**Comment by deniseschannon** [comment]
The `preview` tag has been updated to `v2.0.0-alpha7` and now has support for external DB.

There is no support for upgrades between preview versions, so you'll need to do a fresh install.
