### ISSUE TITLE
Rancher 2.0 Preview: x509: failed to load system roots and no roots provided in metadata system container

### ISSUE THREAD

**Issue by ecliptik** [rancher/rancher#9948]
**Rancher versions:**
rancher/server: v2.0.0-alpha6
rancher/agent: v2.0-alpha2

**Infrastructure Stack versions:**
healthcheck: rancher/healthcheck:v0.3.3
ipsec: rancher/net:v0.12.3 
network-services: rancher/network-manager:v0.8.6, rancher/net:v0.12.3, rancher/dns:v0.16.3
scheduler: none
kubernetes (if applicable): Rancher 2.0 Preview

**Docker version: (`docker version`,`docker info` preferred)**
17.06.2-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
ubuntu@ip-10-7-3-119:~$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
ubuntu@ip-10-7-3-119:~$ uname -a
Linux ip-10-7-3-119 4.4.0-1022-aws #31-Ubuntu SMP Tue Jun 27 11:27:55 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Rancher 2.0 Preview. Master behind a AWS ELB with HTTPS 443 -> 8080 using a signed certificate for the domain.

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Rancher 2.0

**Steps to Reproduce:**
1. Setup Rancher 2.0 Preview Master listening on port 8080
2. Create AWS ALB
3. Setup HTTPS 443 to point to 8080

**Results:**
Seems that the some of the new Rancher preview services containers do not container a `ca-certificates` or equivalent package. Services fail to get the Rancher v3 API information due to the error 

`Get https://rancher-preview.domain.com/v3: x509: failed to load system roots and no roots provided`

The certificate we are using is not self-signed and is the certificate we use for all of our domain SSL certs. Doing a search for this error shows that it may be related to missing certs packages: https://github.com/moby/moby/issues/5157

Logs of `core-services-metadata-1` container in System services.

<img width="895" alt="screen shot 2017-09-26 at 1 46 58 pm" src="https://user-images.githubusercontent.com/1261742/30883645-ad997898-a2c1-11e7-8bce-4d7aa1a07310.png">

This causes all other System services to fail,

<img width="1261" alt="screen shot 2017-09-26 at 1 51 11 pm" src="https://user-images.githubusercontent.com/1261742/30883688-d366613a-a2c1-11e7-823e-123c15191d1a.png">

**Comment by deniseschannon** [comment]
I just pushed a change to our `v2.0-development` branch of our rancher-catalog to get ssl working for metadata, if you want to try it out. We haven't tested it but I figured I'd offer. 

Image version is `rancher/metadata:v1.0.7`. You might be able to just upgrade that service, but once again (not tested yet).

**Comment by ecliptik** [comment]
@deniseschannon upgraded the metadata container to v1.0.7 and it seems like everything is working now, thank you.

<img width="1276" alt="screen shot 2017-09-26 at 2 37 22 pm" src="https://user-images.githubusercontent.com/1261742/30885570-9ed6988e-a2c8-11e7-811d-f8db3b70c401.png">

**Comment by deniseschannon** [comment]
The `preview` tag has been updated to `v2.0.0-alpha7` and now has support for SSL in the catalog.

There is no support for upgrades between preview versions, so you'll need to do a fresh install.
