### ISSUE TITLE
kubectl-shell container not starting up

### ISSUE THREAD

**Issue by damniamgood** [rancher/rancher#9951]
**Rancher versions:**
rancher/server:v2.0.0-alpha6
rancher/agent:v2.0-alpha4

**Infrastructure Stack versions:**
healthcheck:v0.3.3
ipsec:v0.12.3
network-services:v0.12.3
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
Client:
 Version:      17.07.0-ce
 API version:  1.30 (downgraded from 1.31)
 Go version:   go1.9
 Git commit:   8784753
 Built:        unknown-buildtime
 OS/Arch:      darwin/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:59:19 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Core Linux (boot2docker)
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VirtualBox
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher, internalDB
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**
1. Bootstrap docker-machine host with new rancher registration command from rancher/server:v2.0.0-alpha6
2. Most of the system services comes up except kubernetes-support stack

**Results:**
![image](https://user-images.githubusercontent.com/1093727/30896561-5a22b6f8-a306-11e7-81d8-01a332e8bf4c.png)

Logs from Rancher Server'
```
time="2017-09-27T05:01:18Z" level=info msg="Creating pod kubernetes-support-kubectl-shell-1-abed6d9c"
time="2017-09-27T05:01:18Z" level=info msg="Waiting for containers of pod kubernetes-support-kubectl-shell-1-abed6d9c to be ready"
time="2017-09-27T05:01:19Z" level=info msg="Waiting for containers of pod kubernetes-support-kubectl-shell-1-abed6d9c to be ready"
time="2017-09-27T05:01:20Z" level=info msg="Waiting for containers of pod kubernetes-support-kubectl-shell-1-abed6d9c to be ready"
time="2017-09-27T05:01:21Z" level=info msg="Waiting for containers of pod kubernetes-support-kubectl-shell-1-abed6d9c to be ready"
time="2017-09-27T05:01:22Z" level=info msg="Waiting for containers of pod kubernetes-support-kubectl-shell-1-abed6d9c to be ready"
time="2017-09-27T05:01:23Z" level=info msg="Waiting for containers of pod kubernetes-support-kubectl-shell-1-abed6d9c to be ready"
time="2017-09-27T05:01:24Z" level=info msg="Waiting for containers of pod kubernetes-support-kubectl-shell-1-abed6d9c to be ready"
time="2017-09-27T05:01:25Z" level=info msg="Waiting for containers of pod kubernetes-support-kubectl-shell-1-abed6d9c to be ready"
time="2017-09-27T05:01:26Z" level=info msg="Waiting for containers of pod kubernetes-support-kubectl-shell-1-abed6d9c to be ready"
time="2017-09-27T05:01:27Z" level=info msg="Waiting for containers of pod kubernetes-support-kubectl-shell-1-abed6d9c to be ready"
time="2017-09-27T05:01:28Z" level=info msg="Waiting for containers of pod kubernetes-support-kubectl-shell-1-abed6d9c to be ready"
time="2017-09-27T05:01:29Z" level=info msg="Waiting for containers of pod kubernetes-support-kubectl-shell-1-abed6d9c to be ready"
time="2017-09-27T05:01:30Z" level=info msg="Waiting for containers of pod kubernetes-support-kubectl-shell-1-abed6d9c to be ready"
time="2017-09-27T05:01:31Z" level=info msg="Waiting for containers of pod kubernetes-support-kubectl-shell-1-abed6d9c to be ready"
time="2017-09-27T05:01:32Z" level=info msg="Waiting for containers of pod kubernetes-support-kubectl-shell-1-abed6d9c to be ready"
```

**Comment by MatthewHartstonge** [comment]
Kubernetes 1.7.x only supports docker up to version 1.12.6
Reference: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.7.md#external-dependency-version-information

**Comment by superseb** [comment]
Logging from the `kubelet` container would be nice in this case.

**Comment by ricardohmon** [comment]
I had a similar issue where the `kubectl-shell` wouldn't stay up. The container's log itself didn't provide any information. However, looking into `kubelet`'s log helped me discover that the hostname (as provided by an Azure VM) was simply too long. The log line looked like this:
```
kubelet_node_status.go:106] Unable to register node "XXXXXXX.internal.cloudapp.net" with API server: Node "XXXXXXX.internal.cloudapp.net" is invalid: metadata.labels: Invalid value: "XXXXXXX.internal.cloudapp.net": must be no more than 63 characters.
```
Overriding the hostname inside the VM did the work.
Thanks

**Comment by superseb** [comment]
@ricardohmon Thanks for sharing

@damniamgood Please reply if you need help on this.
