### ISSUE TITLE
Feature request - Provide option to have grouped view for hosts as default

### ISSUE THREAD

**Issue by damniamgood** [rancher/rancher#9952]
**Rancher versions:**
rancher/server:v2.0.0-alpha6
rancher/agent:v2.0-alpha4

In order to keep actual cattle experience, one of the host view that has grown into default is "grouped". It will be nice to have an option to keep that UX. Gives a sense of assurance when hosts shows up 👍 

![image](https://user-images.githubusercontent.com/1093727/30896674-f40ca788-a306-11e7-95b5-85a2bfb80625.png)

**Comment by loganhz** [comment]
@vincent99 maybe we can put it in local storage?

**Comment by vincent99** [comment]
We have user preference storage. @loganhz you can add ones for this and other similar view choice.

But the reason that the old view is not default is that showing all of everything doesn't scale very well. We've mostly left it as-is but it's going to need to change, not be available over X hosts/container, or go away eventually.

**Comment by tfiduccia** [comment]
Version - 2.0 master 8/5
Verified fixed

**Comment by damniamgood** [comment]
Awesome! thnx
