### ISSUE TITLE
 Shibboleth request timestamp format

### ISSUE THREAD

**Issue by oliverorav** [rancher/rancher#9953]
**Rancher versions:**
rancher/server: v1.6.5
rancher/agent: v1.2.5

**Infrastructure Stack versions:**
healthcheck: v0.3.0
ipsec: v0.1.0
network-services: v0.2.0
scheduler: v0.5.1

**Docker version: (`docker version`,`docker info` preferred)**
Version: 1.12.5
API version: 1.24
Go version: go1.6.4
Git commit: 7392c3b
Built: Fri Dec 16 02:23:59 2016
OS/Arch: linux/amd64

Server:
Version: 1.12.5
API version: 1.24
Go version: go1.6.4
Git commit: 7392c3b
Built: Fri Dec 16 02:23:59 2016
OS/Arch: linux/amd64

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Red Hat Enterprise Linux Server release 7.3 (Maipo), 3.10.0-693.1.1.el7.x86_64

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node with external MariaDB.

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Issue**
Microsoft SAML server refuses to accept the request sent by Rancher:
`MSIS0018: The SAML protocol message cannot be read because it contains data that is not valid. --> System.FormatException: String was not recognized as a valid DateTime.`
Seems that Rancher writes timestamp in more detail than Microsoft can handle. It looks like the reason may lay within the very nature of the DateTime-structure in .NET which is based on 100-nanosecond vs. nanoseconds in Go (7 floating points vs 9 floating points).

Would it be possible to add configuration field to change/alter the precision of the timestamp?

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
