### ISSUE TITLE
Rancher (logging) service not discoverable

### ISSUE THREAD

**Issue by pkaramol** [rancher/rancher#9955]
**Rancher versions:**
rancher/server: latest (as on 27th Sept. 2017)
rancher/agent: 1.2.6

**Infrastructure Stack versions:**
healthcheck: 0.3.3
ipsec: 0.11.9
network-services: 
rancher/metadata:v0.9.4
rancher/network-manager:v0.7.8
scheduler: v0.8.2
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 17.07.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 34
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 3addd840653146c90a254301d6c3a663c7fd6429
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-96-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.953GiB
Name: server
ID: TGWR:BFPO:U6QJ:QUWV:HY4Z:LXA7:JKRP:2DU2:FK7V:7H6O:A7E4:W67W
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04.03
4.4.0-96-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VirtualBox

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
1 Rancher server node, 2 host nodes

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
I want to send logs from one `rancher` service (e.g. `my_service`) to another `rancher` service running the `ELK` stack with the `syslog` driver 

Setting up my stack via a `docker-compose` as follows more or less:

     elk-custom:
        # image: elk-custom
        build:
          context: .
          dockerfile: Dockerfile-elk
        ports:
          - 5601:5601
          - 9200:9200
          - 5044:5044
          - 5151:5151
          - 5152:5152

    
      my_service:
        image: some_image_from_my_local_registry
        depends_on:
          - elk-custom
        logging:
         driver: syslog
         options:
           syslog-address: "tcp://elk-custom:5151"

However, on the stack dashboard, for `my_service` I get:

    my_service (Expected state running but got error: Error response from daemon: failed to initialize logging driver: dial tcp: lookup elk-custom on 10.0.2.3:53: server misbehaving)

Is there anything additional needed to make the specific logging (`elk-custom`) service discoverable?
**Results:**

**Comment by cjellick** [comment]
Are you asking something different here than what you asked on the forums at https://forums.rancher.com/t/rancher-service-not-discoverable/7431/3 ?

Was @vincent99 answer not sufficient?

**Comment by cjellick** [comment]
Or can this be close based off of the discussion in forums?

**Comment by pkaramol** [comment]
Yes it is the same thing.

Discussion can be closed.

Many thanks.

**Comment by cjellick** [comment]
Np! Thanks
