### ISSUE TITLE
Private Registry not working in 2.0: Private docker repo doesn't work (access forbidden)

### ISSUE THREAD

**Issue by vb4life** [rancher/rancher#9956]
There seems to be a problem with pulling docker images from a private registry (hosted using the registry feature in GitLab).

I added a private registry under Resources -> Registries and tested that the credentials work with `docker login registry.example.com`. Still, when trying to deploy a container with Kubernetes, it doesn't seem to use the credentials at all.

The error I get is:
`Failed to pull image "registry.example.com/path/name:1.0.0": rpc error: code = 2 desc = Error response from daemon: {"message":"Get https://registry.example.com/v2/path/name/manifests/1.0.0: denied: access forbidden"}`

If I manually pull the image, it works.

Any hints on what to check for?
(Pulling public images like `ubuntu:xenial` works)

It is a newly setup RancherOS v1.1.0 instance with Rancher v2.0.0-alpha6 installed in the local disk.

_note: registry.example.com is not the proper URL, of course_ :)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0-alpha6` Cattle: `v0.184.7` UI: `v2.0.7` |
|Access|`Disabled`|
|Orchestration|``|
|Route|`admin-tab.processes.index`|

**Comment by kurtbrose** [comment]
I'm having the exact same issue (gitlab registry + kubernetes = access forbidden)

**Comment by doerler** [comment]
Exact same issue here on Rancher v2.0.0-alpha7, looks like the rancher registry settings are not passed to k8s.
Our temporary workaround: Execute shell on `kubelet` container and docker login to your private registry.

**Comment by deniseschannon** [comment]
This should be fixed with Rancher v2.0.0-alpha8, which should be tagged as preview now. 

Note: with the tech preview releases, we are not supporting upgrades between releases.

**Comment by sirhill** [comment]
I am getting the same issue with Rancher v2.0.0-alpha9 and gitlab.

**Comment by Ilya-Kuchaev** [comment]
Even in alpha23

**Comment by superseb** [comment]
Commenting on closed issue won't help much, please file a new issue describing what you have configured and what logging you get so we can investigate.

**Comment by Ilya-Kuchaev** [comment]
Why should one create the duplicates?

**Comment by superseb** [comment]
This was filed & fixed 5 months ago on a version architecturally way different than the version you are reporting it on, so pointless to reopen under the same issue. The discussion has not been flowing since, there has been no acknowledgment, only another issue reported which didnt report back so this issue has no value to reopen.
