### ISSUE TITLE
Excessive load on scaling event (Hosts)

### ISSUE THREAD

**Issue by Rucknar** [rancher/rancher#9957]
**Summary**
When scaling our autoscaling server groups, we experience a high load average on both the servers coming online and the existing servers. Upon inspection, the load average is driven by the CPU usage of the containers with names similar to: `r-network-services-metadata*`.

This high load average across our hosts is causing a degradation in service due to our diminished capacity whilst scaling. We've upgraded from 6.2 to 6.3 and up to 6.10 inclusive of infrastructure stack upgrades, the issue persists however.

We might expect a higher than usual load average on the new hosts whilst they unpack and deploy containers, it's not expected however that the existing hosts should experience high CPU and load average, given the services we run on theses hosts don't undergo any changes.

We've already ruled out shared services such as DB/Cache, the stats for the containers running on the host however the CPU stats for these hosts suggest the issue lies with the metadata/network services in Rancher its-self. 

**Rancher versions:**
rancher/server: `1.6.2,1.6.3,1.6.10`
rancher/agent: `1.2.6`

**Infrastructure Stack versions:**
healthcheck: `0.3.3`
ipsec: `0.11.9`
network-services (metadata): `0.9.2`
network-services: (network-manager) `0.7.4`
scheduler: `0.8.2`

**Docker version: (`docker version`,`docker info` preferred)**
`17.03.1-ce`
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
`RancherOS v1.0.2`
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS EC2 T2

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
- Single Rancher server
- RDS DB for Rancher server

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Standard running state, 4x hosts of a variety of roles. ~10 user containers per host (allocated through the global policy and labels.)
Increase autoscaling group from 1 > 10 for our 'web' server role.

**Results:**
Upon registering with rancher load average and CPU stats for the new/existing hosts go wild. We also observe a notable increase in network activity to all the affected hosts.

**Comment by Rucknar** [comment]
Related to 
https://github.com/rancher/rancher/issues/9373
https://github.com/rancher/rancher/issues/8505

**Comment by Rucknar** [comment]
<img width="2383" alt="container_cpu" src="https://user-images.githubusercontent.com/5539660/31618166-156d7eac-b289-11e7-97d2-a1ebdbc01f13.png">
^ output of the containers i'm seeing the CPU spike on.

**Comment by sangeethah** [comment]
Tested with rancher server version - v1.6.11-rc5 using  rancher/metadata:v0.9.5

rancher-metadata container now get created with:
```
            "CpuPeriod": 100000,
            "CpuQuota": 70000,
```

Even with the above settings , metadata takes up > 70% of the cpu when adding ~15 hosts to existing set up of 3 hosts.

Modified "CpuQuota": 50000 for rancher-metadata service.
In a setup with ~20 hosts , when I deactivate and activate 15 global services , metadata takes up > 50%  of available CPU (2.5 GHz total cpu)  .

cpu consumption for rancher-metadata when deactivate/activate of 15 global services:
```
PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
29214 root      20   0  248080  65852   7996 S 60.0  3.8   1:38.12 rancher-metadat                                                                                                                                                                           
29214 root      20   0  248080  65852   7996 S 50.0  3.8   1:38.21 rancher-metadat                                                                                                                                                                           
29214 root      20   0  248080  65852   7996 S 18.8  3.8   1:38.24 rancher-metadat                                                                                                                                                                           
29214 root      20   0  248080  65852   7996 S 26.7  3.8   1:38.29 rancher-metadat                                                                                                                                                                           
29214 root      20   0  248080  65852   7996 S 66.7  3.8   1:38.40 rancher-metadat                                                                                                                                                                           
29214 root      20   0  248080  65852   7996 S 50.0  3.8   1:38.48 rancher-metadat                                                                                                                                                                           
29214 root      20   0  248080  65852   7996 S 56.2  3.8   1:38.57 rancher-metadat                                                                                                                                                                           
29214 root      20   0  248080  65852   7996 S 37.5  3.8   1:38.63 rancher-metadat                                                                                                                                                                           
29214 root      20   0  248080  65852   7996 S 50.0  3.8   1:38.72 rancher-metadat                                                                                                                                                                           
29214 root      20   0  248080  65852   7996 S 13.3  3.8   1:38.74 rancher-metadat                                                                                                                                                                           
29214 root      20   0  248080  65852   7996 S 31.2  3.8   1:38.79 rancher-metadat                                                                                                                                                                           
29214 root      20   0  248080  65852   7996 S 33.3  3.8   1:38.85 rancher-metadat                                                                                                                                                                           
29214 root      20   0  248080  65852   7996 S 50.0  3.8   1:38.93 rancher-metadat                                                                                                                                                                           
29214 root      20   0  248080  65852   7996 S 60.0  3.8   1:39.02 rancher-metadat                                                                                                                                                                           
29214 root      20   0  248080  65852   7996 S 26.7  3.8   1:39.06 rancher-metadat                                                                                                                                                                           
```

**Comment by alena1108** [comment]
@sangeethah cpu_quota is not a hard limit at any given time, but rather an average. As an example, for values:

cpu_quota 100 000 (microseconds)
cpu_period 50 000 (microseconds)

rancher-metadata won't allocate CPU for more than 50 milliseconds out of 100 milliseconds. Think of it as a percentage within the time frame. It can still use 100% of CPU during the dedicated time.

We are still going to adjust the values to be cpu_quota =200 000, and cpu_period = 400 000 to ensure that CPU is fully exercised during the metadata reload that can take up to ~200 milliseconds. 

As a part of the fix, we reduced number of metadata to be throttled (once in 1 second by default, configurable). That itself should reduce number of cpu spikes. Correcting cpu_period and cpu_quota will ensure that metada container will not make other services on the host unusable.

**Comment by deniseschannon** [comment]
With the latest RC and increasing the metadata interval, the load is decreased and it takes less time for global services to come up when scaling up hosts. 

As you increase the metadata interval, metadata updates throughout the system will be slowed down. Please be aware this might have side effects for any services relying on metadata.

**Comment by Rucknar** [comment]
<img width="1762" alt="screen shot 2017-11-12 at 15 48 01" src="https://user-images.githubusercontent.com/5539660/32700773-7d740244-c7c1-11e7-844f-0ccfb310270f.png">
Thanks @deniseschannon , for others benefit. The above graphs shows us scaling a cluster of servers from 1, to 30. In the first run i'm using the latest RC, this loading represents an improvement over the current stable build. load is less spikey and overall reduced. In the second scaling test, we modified the ` -reload-interval-limit=1000` to ` -reload-interval-limit=5000` for the metatdata service. This, as you can see reduced the load significantly again. 

Worth noting however, that this is fine for us and how we use the metadata service, it needs consideration before applying.

**Comment by brandonpalmer** [comment]
FYI all,  this also appears to be an issue when there are containers on the hosts which have large number of listening ports (i.e we are using haproxy containers with ~ 1000 open ports (legacy requirements we're working to remove).  Once I updated -reload-interval-limit,  all load issues cleared up well.
