### ISSUE TITLE
[2.x.x] Environment with no System Services

### ISSUE THREAD

**Issue by jloisel** [rancher/rancher#9958]
**Rancher versions:**
rancher/server: v2.x.x (tech preview)

We're using Rancher with no single system services. We removed them after creating the environment. This is working perfectly fine in Rancher 1.6.x. We're worried about the future 2.x.x support for such kind of environment.

Our Product: https://octoperf.com

_Slack transcript of conversation with Adrian:_
**Jerome**:
We're having our entire product based on Rancher, heavily using the API to run containers.
**Adrian**:
great! that will all continue to work.
**Jerome**
We have an environment setup with no system services
**Adrian**
the API will be promoted to v3 but still maintain full backwards compatibility
**Jerome**
Because we just want to run containers on a cluster of machines without the need for ipsec, health check and more
**Jerome**
Ah ok, so api calls to v2-beta will remain functional ?
**Adrian** 
yes
**Jerome**
I have tried in the latest tech preview to remove all the system services from the environment / cluster (don't understand the difference even when reading the doc). I mean, I can't remove some kubernetes related stuff
**Adrian**
so you run rancher just to have API access to do things, but you don't use anything like the overlay network, health checking, scheduling, etc?
**Adrian**
why not just use Docker?
**Jerome**
Because Rancher solves the pain of launching containers on multiple machines via a Rest API, manages the nodes being connected. We could do our own agent to do this, but hell that's a lot  of work for nothing if an open-source product already does this for you. Rancher provides the ground layer for a distributed system to run containers easily on multiple machines via the Rest API
**Adrian**
what would happen if you just left those services running? other than not wanting to, is there any reason not to?
**Jerome**
The machines connected to our Rancher server are inside our clients network with no ports open (behind firewall), only outgoing traffic allowed. We removed the system services because they kept trying to connect via ipsec, restarting and restarting. Containers are launched in bridged mode on all the machines, only an internet connection is required.
**Adrian**
rancher, as a product, is designed to provide scheduling, health checking, overlay, orchestration, etc. it's reasonable that they would be restarting, because they expect to be running as part of the product offering.
**Jerome**
I understand. The system is designed to run on a favorable network with no connectivity issues between machines. We also use Rancher for our infrastructure, to run our backend server and database, which is completely fine in this context.
**Adrian**
sounds like you have a pretty specific use case that's outside of the normal profile. you're the first i've encountered that does this. if being able to shut off all system services and just use a subset of the functionality is a requirement, i recommend that you open a GH issue that describes your use case so that the engineering team can consider it. This is an early tech preview, so if that functionality is present now, i don't see why it can't be included in 2.0. i don't make those decisions, though. :slightly_smiling_face:

**Comment by vincent99** [comment]
Anything you looked at in preview1 is now going to be irrelevant; Preview2+ are 100% kubernetes, so its services and its agent (kublet) are running on the nodes.  You can experiment with RKE and disabling the various services to figure out what a minimal cluster looks like, but as Adrian said this is far outside the realm of the typical user profile.

There is a customer looking to do something somewhat similar sounding in 2.0, you should talk to our sales team to see what they can tell you about it how well it matches your use.

**Comment by jloisel** [comment]
Thanks for the insight. We may move out of Rancher if Kubernetes cannot be disabled, as we only need to launch containers on a cluster of machines in bridged networking mode.
