### ISSUE TITLE
[webhook-service] Request a new driver 'serviceWebhook'

### ISSUE THREAD

**Issue by biblesyme** [rancher/rancher#9959]
In CI project, We need a mechanism to redirect the webhook request from GitHub into our pipeline-service. So we added this new driver to support our requirements. 

I've submited a [PR](https://github.com/rancher/webhook-service/pull/66) to request this new feature. Please consider it.

**Comment by deniseschannon** [comment]
Merged and released webhook service v0.9.11 and is available in cattle
