### ISSUE TITLE
How to switch aws IAM role?

### ISSUE THREAD

**Issue by vinayakbhat24** [rancher/rancher#9960]
After logging into the aws account with my access key and secret access key,  I like to switch my IAM role. But I am not finding any way to switch the role.  Can you please suggest how to switch the role.
Thanks,

Best Regards,
Vinayak Bhat

**Comment by aemneina** [comment]
@vinayakbhat24 not sure if your question is posted in the right place. Where are you using these account/IAM roles? Through the aws web console?

**Comment by loganhz** [comment]
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it
