### ISSUE TITLE
[rancher-dns] wrongly replies with ServFail instead of NxDomain

### ISSUE THREAD

**Issue by richfelker** [rancher/rancher#9961]
I'm not a user but maintainer of musl libc, and have gotten several reports of slow dns lookups with rancher, and some quick reading of the source revealed that the problem is rancher-dns returning ServFail in the reply in place of NxDomain. I wrote up an explanation and identified the location in the source that's responsible in this comment on an existing ticket, which was previously closed without resolution:

https://github.com/rancher/rancher/issues/4177#issuecomment-332571951

**Comment by superseb** [comment]
Thanks for reporting, do you have a testcase where you see this behavior? In my latest tests I see `NXDOMAIN` being returned properly when querying non-existent records.

**Comment by richfelker** [comment]
As I said I'm not a user so I can't say for sure, but nothing seems to have changed in the code since I read it before and commented on what seems to be the cause of the problem, so I think the issue is still there. It looks to me like ServFail is returned instead of NxDomain except in the case where the server is authoritative for a suffix of the requested name (lines 359-375). There is no other code capable of setting the rcode to NxDomain (RcodeNameError) that I can find.

As an aside, the comment and logic at lines 383-389 is also wrong. If the nameserver returns NxDomain to you for an AAAA query, that definitively means the requested name does not exist at all (has no RRs), not just that it lacks AAAA records. Rewriting to claim the name does exist but lacks AAAA records, which is what you're doing now, will yield the wrong behavior when musl's stub resolver gets the answer, and will prevent subsequent search domains from getting searched (since there was already a definitive answer received).

**Comment by fangel** [comment]
We've been trying to identify the cause of a slow-down of one of our apps after deploying it to Rancher - and it is exactly this problem. The Rancher DNS server responds with a `SERVFAIL`, and then Must retries until the timeout is reached.

It isn't every domain that triggers this, so it might also stem from a misconfiguration in the specific domains' DNS – but other DNS-servers seems to handle it better than Rancher's, so a little more resilience might be nice.

One domain that triggers the behaviour is `feed.theplatform.com`. As an example, see the following output for `dig`:

__With the Rancher DNS-server__:
```bash
bash-4.3# dig feed.theplatform.com AAAA

; <<>> DiG 9.11.3 <<>> feed.theplatform.com AAAA
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 10392
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;feed.theplatform.com.          IN      AAAA

;; Query time: 209 msec
;; SERVER: 169.254.169.250#53(169.254.169.250)
;; WHEN: Mon Jul 23 13:18:14 CEST 2018
;; MSG SIZE  rcvd: 49
```

__With Google's DNS-server__:
```bash
bash-4.3# dig @8.8.8.8 feed.theplatform.com AAAA

; <<>> DiG 9.11.3 <<>> @8.8.8.8 feed.theplatform.com AAAA
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 40520
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;feed.theplatform.com.          IN      AAAA

;; Query time: 107 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Mon Jul 23 13:18:16 CEST 2018
;; MSG SIZE  rcvd: 49
```

**Comment by loganhz** [comment]
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.

**Comment by richfelker** [comment]
Is there reason to believe this issue does not exist in Rancher 2.0? Is it

**Comment by loganhz** [comment]
Hi @richfelker 

Yes, it is totally a rewrite. Rancher 2.0 is based on Kubernetes. So Kubernetes native `kubedns` is used in 2.0 as the dns component instead of the `rancher-dns` which created by Rancher in 1.6.

https://rancher.com/docs/

> The most of Rancher is redesigned to work on Kubernetes. 
Rancher 2.0 retains the user-friendly features of version 1.6, such as the UI and catalog.
