### ISSUE TITLE
change the role policy in rancher

### ISSUE THREAD

**Issue by manojRy** [rancher/rancher#9962]
I have created kubernetes template and want to add aws as a host for that I have provided the access key and secret access key. I was able to see my VPC id there but the actual problem is I cannot launch instances using VPC id mentoined there for that I have to change to another role. I cannot see any option like that on the ui, is that possible using rancher. eg: Now I am on account admin role which don't have permissions to run the instances here so every time when I log into aws I will change to cloud admin, I want to do this with rancher also. Below is the picture where I got stuck.
Thanks.
<img width="808" alt="cfhpt" src="https://user-images.githubusercontent.com/16360625/30927973-716695a0-a3ba-11e7-8298-21663df2b2c8.png">

**Comment by vincent99** [comment]
The UI does not support using instance profiles for the various requests it makes before the actual docker-machine call to create the instance at this time.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
