### ISSUE TITLE
Tail logs without formating and time provided by rancher

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#9967]
I'd really like the ability to tail my container logs with rancher without rancher imposing format, dates, and additional information for each line. Can we just get a raw=true as an option to the logs stream? Thanks!!

Related: https://github.com/rancher/rancher/issues/9966

**Rancher versions:**
rancher/server: 1.6.9

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
