### ISSUE TITLE
rancher+kubernetes cluster add three nodes successfully, but failed when adding another one

### ISSUE THREAD

**Issue by markqiu** [rancher/rancher#9969]
**Rancher versions:** 
rancher/server: 1.6.9
rancher/agent: v1.7.4-rancher1

**Infrastructure Stack versions:**
healthcheck: rancher/healthcheck:v0.3.3
ipsec: rancher/net:v0.11.9
network-services: rancher/metadata:v0.9.4, rancher/network-manager:v0.7.8
scheduler: rancher/scheduler:v0.8.2
kubernetes (if applicable): rancher/k8s:v1.7.4-rancher2

**Docker version: (`docker version`,`docker info` preferred)**
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:20:01 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:20:01 2017
 OS/Arch:      linux/amd64

Containers: 10
 Running: 10
 Paused: 0
 Stopped: 0
Images: 8
Server Version: 1.12.6
Storage Driver: devicemapper
 Pool Name: docker-253:0-1143306-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.87 GB
 Data Space Total: 107.4 GB
 Data Space Available: 29.79 GB
 Metadata Space Used: 3.441 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.144 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.140-RHEL7 (2017-05-03)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-693.2.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.51 GiB
Name: tjhdp2
ID: 3ZS6:XRJ5:Z2WG:HFQX:IU2P:SIQZ:7LJC:LUT5:WCLL:CGXP:SHZY:PKH4
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

3.10.0-514.26.2.el7.x86_64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher, internal DB
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes
**Steps to Reproduce:**
add a new envirnment of kube and add three hosts at first, run some days, then add another host
**Results:**
kubectl get node only show three hosts, the forth host doesn't show.

the attachment is the log info from the forth host's kubelet container.
[kube.zip](https://github.com/rancher/rancher/files/1340336/kube.zip)

**Comment by markqiu** [comment]
error log:
I0930 01:51:13.599872    8380 rancher.go:658] ExternalID [tjhdp2.local]
I0930 01:51:13.599886    8380 rancher.go:665] InstanceID [tjhdp2.local]
E0930 01:51:13.609212    8380 kubelet_node_status.go:78] Unable to construct v1.Node object for kubelet: failed to get external ID from cloud provider: instance not found
E0930 01:51:13.861618    8380 eviction_manager.go:238] eviction manager: unexpected err: failed GetNode: node 'tjhdp2.local' not found
I0930 01:51:15.763965    8380 kubelet.go:1820] skipping pod synchronization - [Kubelet failed to get node info: failed to get external ID from cloud provider: instance not found]
E0930 01:51:17.392648    8380 kubelet_network.go:193] checkLimitsForResolvConf: Resolv.conf file '/etc/resolv.conf' contains search line consisting of more than 3 domains!
I0930 01:51:20.609622    8380 kubelet_node_status.go:247] Setting node annotation to enable volume controller attach/detach
I0930 01:51:20.609693    8380 rancher.go:658] ExternalID [tjhdp2.local]
I0930 01:51:20.609712    8380 rancher.go:665] InstanceID [tjhdp2.local]
E0930 01:51:20.619190    8380 kubelet_node_status.go:78] Unable to construct v1.Node object for kubelet: failed to get external ID from cloud provider: instance not found
I0930 01:51:20.764305    8380 kubelet.go:1820] skipping pod synchronization - [Kubelet failed to get node info: failed to get external ID from cloud provider: instance not found]
E0930 01:51:23.899558    8380 eviction_manager.go:238] eviction manager: unexpected err: failed GetNode: node 'tjhdp2.local' not found
I0930 01:51:25.764666    8380 kubelet.go:1820] skipping pod synchronization - [Kubelet failed to get node info: failed to get external ID from cloud provider: instance not found]
I0930 01:51:27.619465    8380 kubelet_node_status.go:247] Setting node annotation to enable volume controller attach/detach
I0930 01:51:27.619507    8380 rancher.go:658] ExternalID [tjhdp2.local]
I0930 01:51:27.619515    8380 rancher.go:665] InstanceID [tjhdp2.local]
E0930 01:51:27.628118    8380 kubelet_node_status.go:78] Unable to construct v1.Node object for kubelet: failed to get external ID from cloud provider: instance not found

**Comment by markqiu** [comment]
error log:
time="2017-09-30T01:48:36Z" level=info msg="Received event: [{\"type\":\"MODIFIED\",\"object\":{\"kind\":\"ReplicaSet\",\"apiVersion\":\"extensions/v1beta1\",\"metadata\":{\"name\":\"ability-1559360115\",\"namespace\":\"website\",\"selfLink\":\"/apis/extensions/v1beta1/namespaces/website/replicasets/ability-1559360115\",\"uid\":\"c95d740e-a422-11e7-9b3d-023a640ca6e8\",\"resourceVersion\":\"1683070\",\"generation\":1,\"creationTimestamp\":\"2017-09-28T07:58:17Z\",\"labels\":{\"app\":\"ability\",\"pod-template-hash\":\"1559360115\"},\"annotations\":{\"deployment.kubernetes.io/desired-replicas\":\"1\",\"deployment.kubernetes.io/max-replicas\":\"2\",\"deployment.kubernetes.io/revision\":\"1\"},\"ownerReferences\":[{\"apiVersion\":\"extensions/v1beta1\",\"kind\":\"Deployment\",\"name\":\"ability\",\"uid\":\"c95c4e1d-a422-11e7-9b3d-023a640ca6e8\",\"controller\":true,\"blockOwnerDeletion\":true}]},\"spec\":{\"replicas\":1,\"selector\":{\"matchLabels\":{\"app\":\"ability\",\"pod-template-hash\":\"1559360115\"}},\"template\":{\"metadata\":{\"creationTimestamp\":null,\"labels\":{\"app\":\"ability\",\"pod-template-hash\":\"1559360115\"}},\"spec\":{\"volumes\":[{\"name\":\"ability-config\",\"persistentVolumeClaim\":{\"claimName\":\"ability-pv\"}}],\"containers\":[{\"name\":\"ability\",\"image\":\"registry.cn-hangzhou.aliyuncs.com/jinchongzi/ability:v1.0_20170927\",\"ports\":[{\"containerPort\":5001,\"protocol\":\"TCP\"},{\"containerPort\":5002,\"protocol\":\"TCP\"}],\"resources\":{\"limits\":{\"memory\":\"4Gi\"},\"requests\":{\"cpu\":\"100m\",\"memory\":\"256Mi\"}},\"terminationMessagePath\":\"/dev/termination-log\",\"terminationMessagePolicy\":\"File\",\"imagePullPolicy\":\"IfNotPresent\"}],\"restartPolicy\":\"Always\",\"terminationGracePeriodSeconds\":30,\"dnsPolicy\":\"ClusterFirst\",\"securityContext\":{},\"schedulerName\":\"default-scheduler\"}}},\"status\":{\"replicas\":1,\"fullyLabeledReplicas\":1,\"observedGeneration\":1}}}\n]"
time="2017-09-30T01:48:36Z" level=info msg="Received event: [{\"type\":\"MODIFIED\",\"object\":{\"kind\":\"Deployment\",\"apiVersion\":\"extensions/v1beta1\",\"metadata\":{\"name\":\"ability\",\"namespace\":\"website\",\"selfLink\":\"/apis/extensions/v1beta1/namespaces/website/deployments/ability\",\"uid\":\"c95c4e1d-a422-11e7-9b3d-023a640ca6e8\",\"resourceVersion\":\"1683071\",\"generation\":1,\"creationTimestamp\":\"2017-09-28T07:58:17Z\",\"labels\":{\"app\":\"ability\",\"version\":\"1.0\"},\"annotations\":{\"deployment.kubernetes.io/revision\":\"1\"}},\"spec\":{\"replicas\":1,\"selector\":{\"matchLabels\":{\"app\":\"ability\"}},\"template\":{\"metadata\":{\"creationTimestamp\":null,\"labels\":{\"app\":\"ability\"}},\"spec\":{\"volumes\":[{\"name\":\"ability-config\",\"persistentVolumeClaim\":{\"claimName\":\"ability-pv\"}}],\"containers\":[{\"name\":\"ability\",\"image\":\"registry.cn-hangzhou.aliyuncs.com/jinchongzi/ability:v1.0_20170927\",\"ports\":[{\"containerPort\":5001,\"protocol\":\"TCP\"},{\"containerPort\":5002,\"protocol\":\"TCP\"}],\"resources\":{\"limits\":{\"memory\":\"4Gi\"},\"requests\":{\"cpu\":\"100m\",\"memory\":\"256Mi\"}},\"terminationMessagePath\":\"/dev/termination-log\",\"terminationMessagePolicy\":\"File\",\"imagePullPolicy\":\"IfNotPresent\"}],\"restartPolicy\":\"Always\",\"terminationGracePeriodSeconds\":30,\"dnsPolicy\":\"ClusterFirst\",\"securityContext\":{},\"schedulerName\":\"default-scheduler\"}},\"strategy\":{\"type\":\"RollingUpdate\",\"rollingUpdate\":{\"maxUnavailable\":1,\"maxSurge\":1}}},\"status\":{\"observedGeneration\":1,\"replicas\":1,\"updatedReplicas\":1,\"unavailableReplicas\":1,\"conditions\":[{\"type\":\"Available\",\"status\":\"True\",\"lastUpdateTime\":\"2017-09-28T07:58:17Z\",\"lastTransitionTime\":\"2017-09-28T07:58:17Z\",\"reason\":\"MinimumReplicasAvailable\",\"message\":\"Deployment has minimum availability.\"}]}}}\n]"
Request => GET https://kubernetes.kubernetes.rancher.internal:6443/api/v1/nodes/tjhdp2.local
time="2017-09-30T01:48:38Z" level=error msg="Error getting node: [tjhdp2.local] by name from kubernetes, err: [Bad response from [https://kubernetes.kubernetes.rancher.internal:6443/api/v1/nodes/tjhdp2.local], statusCode [404]. Status [404 Not Found]. Body: [{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"nodes \\\"tjhdp2.local\\\" not found\",\"reason\":\"NotFound\",\"details\":{\"name\":\"tjhdp2.local\",\"kind\":\"nodes\"},\"code\":404}\n]]"
time="2017-09-30T01:48:38Z" level=error msg="Error getting node: [tjhdp2.local] by name from kubernetes, err: [Bad response from [https://kubernetes.kubernetes.rancher.internal:6443/api/v1/nodes/tjhdp2.local], statusCode [404]. Status [404 Not Found]. Body: [{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"nodes \\\"tjhdp2.local\\\" not found\",\"reason\":\"NotFound\",\"details\":{\"name\":\"tjhdp2.local\",\"kind\":\"nodes\"},\"code\":404}\n]]"
time="2017-09-30T01:48:39Z" level=info msg="Received event: [{\"type\":\"MODIFIED\",\"object\":{\"kind\":\"Pod\",\"apiVersion\":\"v1\",\"metadata\":{\"name\":\"ability-1559360115-3nmfk\",\"generateName\":\"ability-1559360115-\",\"namespace\":\"website\",\"selfLink\":\"/api/v1/namespaces/website/pods/ability-1559360115-3nmfk\",\"uid\":\"c95f13d2-a422-11e7-9b3d-023a640ca6e8\",\"resourceVersion\":\"1683081\",\"creationTimestamp\":\"2017-09-28T07:58:17Z\",\"labels\":{\"app\":\"ability\",\"pod-template-hash\":\"1559360115\"},\"annotations\":{\"kubernetes.io/created-by\":\"{\\\"kind\\\":\\\"SerializedReference\\\",\\\"apiVersion\\\":\\\"v1\\\",\\\"reference\\\":{\\\"kind\\\":\\\"ReplicaSet\\\",\\\"namespace\\\":\\\"website\\\",\\\"name\\\":\\\"ability-1559360115\\\",\\\"uid\\\":\\\"c95d740e-a422-11e7-9b3d-023a640ca6e8\\\",\\\"apiVersion\\\":\\\"extensions\\\",\\\"resourceVersion\\\":\\\"1363192\\\"}}\\n\"},\"ownerReferences\":[{\"apiVersion\":\"extensions/v1beta1\",\"kind\":\"ReplicaSet\",\"name\":\"ability-1559360115\",\"uid\":\"c95d740e-a422-11e7-9b3d-023a640ca6e8\",\"controller\":true,\"blockOwnerDeletion\":true}]},\"spec\":{\"volumes\":[{\"name\":\"ability-config\",\"persistentVolumeClaim\":{\"claimName\":\"ability-pv\"}},{\"name\":\"default-token-t1wb9\",\"secret\":{\"secretName\":\"default-token-t1wb9\",\"defaultMode\":420}}],\"containers\":[{\"name\":\"ability\",\"image\":\"registry.cn-hangzhou.aliyuncs.com/jinchongzi/ability:v1.0_20170927\",\"ports\":[{\"containerPort\":5001,\"protocol\":\"TCP\"},{\"containerPort\":5002,\"protocol\":\"TCP\"}],\"resources\":{\"limits\":{\"memory\":\"4Gi\"},\"requests\":{\"cpu\":\"100m\",\"memory\":\"256Mi\"}},\"volumeMounts\":[{\"name\":\"default-token-t1wb9\",\"readOnly\":true,\"mountPath\":\"/var/run/secrets/kubernetes.io/serviceaccount\"}],\"terminationMessagePath\":\"/dev/termination-log\",\"terminationMessagePolicy\":\"File\",\"imagePullPolicy\":\"IfNotPresent\"}],\"restartPolicy\":\"Always\",\"terminationGracePeriodSeconds\":30,\"dnsPolicy\":\"ClusterFirst\",\"serviceAccountName\":\"default\",\"serviceAccount\":\"default\",\"nodeName\":\"tjhdp3\",\"securityContext\":{},\"schedulerName\":\"default-scheduler\",\"tolerations\":[{\"key\":\"node.alpha.kubernetes.io/notReady\",\"operator\":\"Exists\",\"effect\":\"NoExecute\",\"tolerationSeconds\":300},{\"key\":\"node.alpha.kubernetes.io/unreachable\",\"operator\":\"Exists\",\"effect\":\"NoExecute\",\"tolerationSeconds\":300}]},\"status\":{\"phase\":\"Running\",\"conditions\":[{\"type\":\"Initialized\",\"status\":\"True\",\"lastProbeTime\":null,\"lastTransitionTime\":\"2017-09-28T09:01:51Z\"},{\"type\":\"Ready\",\"status\":\"False\",\"lastProbeTime\":null,\"lastTransitionTime\":\"2017-09-30T01:48:36Z\",\"reason\":\"ContainersNotReady\",\"message\":\"containers with unready status: [ability]\"},{\"type\":\"PodScheduled\",\"status\":\"True\",\"lastProbeTime\":null,\"lastTransitionTime\":\"2017-09-28T09:01:51Z\"}],\"hostIP\":\"192.168.1.69\",\"podIP\":\"10.42.188.240\",\"startTime\":\"2017-09-28T09:01:51Z\",\"containerStatuses\":[{\"name\":\"ability\",\"state\":{\"waiting\":{\"reason\":\"CrashLoopBackOff\",\"message\":\"Back-off 5m0s restarting failed container=ability pod=ability-1559360115-3nmfk_website(c95f13d2-a422-11e7-9b3d-023a640ca6e8)\"}},\"lastState\":{\"terminated\":{\"exitCode\":1,\"reason\":\"Error\",\"startedAt\":\"2017-09-30T01:48:21Z\",\"finishedAt\":\"2017-09-30T01:48:36Z\",\"containerID\":\"docker://3ccf8b51f237c82485c3109665295d5b3cf4d0986993d14be1e204c0f2552e77\"}},\"ready\":false,\"restartCount\":437,\"image\":\"registry.cn-hangzhou.aliyuncs.com/jinchongzi/ability:v1.0_20170927\",\"imageID\":\"docker-pullable://registry.cn-hangzhou.aliyuncs.com/jinchongzi/ability@sha256:34bbae0a898ccc22e78286f054333db25be90ab239c1bdc60c371d9c58b6f41a\",\"containerID\":\"docker://3ccf8b51f237c82485c3109665295d5b3cf4d0986993d14be1e204c0f2552e77\"}],\"qosClass\":\"Burstable\"}}}\n]"

**Comment by markqiu** [comment]
seems to be the same as #9682

**Comment by markqiu** [comment]
I upgraded to v1.7.7-rancher1, the problem solved.

**Comment by markqiu** [comment]
the bug reproduced:
the error is caused by the host file. In my host file, I had the following line:
192.168.1.68  tjhdp2.local      tjhdp2
After I ran the rancher install command, the tjhdp2.local showed in the rancher host page, but can't get to show as a kube node. So I changed the line to the follow solving the problem:
192.168.1.68  tjhdp2

note: I changed very host file in the cluster.

**Comment by superseb** [comment]
I'm filing an issue for this today to see if we can make this a better experience. (code and/or docs)
