### ISSUE TITLE
Self sign certs not working adding host

### ISSUE THREAD

**Issue by fabiobsantos92** [rancher/rancher#9970]
I'm having the same error as issue #4293.
I'm using openssl to generate the certs and when i'm adding the host i see the message:
"INFO: Running Agent Registration Process, CATTLE_URL=https://rancher.xxx.xxx/v1
INFO: Attempting to connect to: https://rancher.xxx.xxx/v1
ERROR: https://rancher..xxx.xxx/v1 is not accessible (server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none)"

**Comment by cjellick** [comment]
You followed this guide @fabiobsantos92 http://rancher.com/docs/rancher/latest/en/installing-rancher/installing-server/basic-ssl-config/#using-self-signed-certs-beta ?

**Comment by fabiobsantos92** [comment]
Yes i followed this guide.
My current configuration is:
1- Rancher server version: v1.6.10, agent version: :v1.2.6
2- Self sign generation with openssl using version "OpenSSL 1.0.2g  1 Mar 2016".
3- Haproxy loadbalancer with the configuration of the guide; 
4- Host Registration URL: https://<domain>
5- Launch rancher server with option: -v <host_path>/rancher.crt:/var/lib/rancher/etc/ssl/ca.crt:Z (I see on server logs the cert was added)
6- Added at host path the same cert: /var/lib/rancher/etc/ssl/ca.crt

I think the problem cloud be the version or configuration of openssl.
I will attach the script a use to generate the cert.
[generate_rancher_cert.txt](https://github.com/rancher/rancher/files/1343869/generate_rancher_cert.txt)

**Comment by superseb** [comment]
Merging this into https://github.com/rancher/rancher/issues/10233
