### ISSUE TITLE
[ipsec] run strongswan/charon in holder container

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#9972]
Problem:
Currently strongswan/charon runs along side rancher-net in the same container. During upgrades, the charon daemon also get's restarted which causes all the tunnels to be teared down and recreated. This causes a disruption in traffic during upgrades.

Solution:
Run charon in holder container and run rancher-net in a separate container. This would leave the existing tunnels as is during upgrades.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
