### ISSUE TITLE
Consistent service index

### ISSUE THREAD

**Issue by RonRademaker** [rancher/rancher#9980]
Hi, I'm wondering if it's possible to make sure containers do not change their service index. We run a mongo replica set cluster that is linked by container name, but our hosts regularly change. More often than not, a new healthy node creates a new service_index for the replacement container which breaks the replica set configuration. For example: the host running the container mongo-mongo-cluster-1  breaks down, a new host spins up and start the container mongo-mongo-cluster-4.

**Rancher versions:**
rancher/server: 1.5.10

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
