### ISSUE TITLE
Failed to apply Kubernetes resource ServiceAccount/rancher-kubernetes-dashboard: exit status 1 (Error from server (NotFound): error when creating "STDIN": namespaces "kube-system" not found )

### ISSUE THREAD

**Issue by ReidWeb** [rancher/rancher#9982]
**Rancher versions:**
rancher/server: v2.0.0-alpha7
rancher/agent: v2.0-alpha4

**Infrastructure Stack versions:**
healthcheck: v0.3.3
ipsec: v0.12.3
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)** Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 20:00:17 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:59:11 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

4.4.0-96-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)** internal-db

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)** Kubernetes

**Steps to Reproduce:** Setup fresh rancher server preview instance on Ubuntu 16.04, add a new host, change to kube-system namespace/env.

**Results:** Cannot load dashboards from link, get error
`Failed to apply Kubernetes resource ServiceAccount/rancher-kubernetes-dashboard: exit status 1 (Error from server (NotFound): error when creating "STDIN": namespaces "kube-system" not found )`
<img width="1260" alt="screen shot 2017-09-29 at 20 43 22" src="https://user-images.githubusercontent.com/3649078/31033139-e1bd9c8e-a556-11e7-8cb9-90da511a9f5d.png">

**Comment by nefuddos** [comment]
with the same problem in rancher/server: v2.0.0-alpha10.

**Comment by suikast42** [comment]
Did you solve this issue ?

**Comment by deniseschannon** [comment]
With the release of [Tech Preview 2](https://forums.rancher.com/t/rancher-release-v2-0-0-tech-preview-2/8282/3), the architecture behind 2.0 has significantly changed. Any issues with any release prior to v2.0.0-alpha12 is most likely invalid. 

Please file new issues after using Tech Preview 2 (any release v2.0.0-alpha12+). As always, thanks for using Rancher!
