### ISSUE TITLE
Propagate host state in metadata

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#9984]
Currently in ipsec, we add or delete the host the host based on presence of the host information in metadata. We should be deleting the ipsec tunnels to the remote host if the host is in "Disconnected" state and also once we add retry logic for the SAS(https://github.com/rancher/rancher/issues/9971), we shouldn't retry if the host is in disconnected state.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
