### ISSUE TITLE
API Keys stop working when Azure AD token expires. Requires logging in twice to get get tokens to work

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#9986]
More details to come. Just wanted to get this in as a placeholder on the board

**Comment by cjellick** [comment]
Not in an RC yet. can be tested via rancher/server:v1.6-development

**Comment by prachidamle** [comment]
Details on the issue:

User's report: 
Setup Azure AD, created account API keys. However API keys do not work.
I have to login to the web ui, log out.  I have to do that 2-4 times ( it varies).  It works if I remain logged in after a few login/logout sessions, or if I logout.  After that, CLI or REST API work for 4-6 hours.  It will work for as many tries as I make in that window.  Then I will need to login to web UI again.

Issue reproduced in house:
- Setup Azure AD
- Create account API keys
- Use Keys for REST API, they work for first time.
- However keys fetch empty results for every next try, until one logs out and logs back in on web UI.
- Same is reproduced when the auth_token in the Db expires at 16 hours. (keys stop working, work after logout-login)

**Comment by galal-hussein** [comment]
Rancher server: v1.6.11-rc3

I ran the steps described by @prachidamle, i was able to use the account key multiple times without the need to logout-login.
