### ISSUE TITLE
Support AWS VPC for per-host-subnet networking

### ISSUE THREAD

**Issue by niusmallnan** [rancher/rancher#9989]
We should automatically synchronize rules in AWS VPC routing.

per-host-subnet: https://github.com/rancher/per-host-subnet
aws-vpc-route-tables: http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_Route_Tables.html

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
