### ISSUE TITLE
Host labels from rancher agent doesn't propagate to kubernetes agent

### ISSUE THREAD

**Issue by sherpc** [rancher/rancher#9992]
**Rancher versions:**
rancher/server: 2.0.0-alpha7
rancher/agent: agent:v2.0-alpha4

**Infrastructure Stack versions:**
healthcheck: v0.3.3
ipsec: v0.12.3
network-services: net:v0.12.3, network-manager:v0.8.6
scheduler: netes:v1.7.6-netes2-1
kubernetes (if applicable): 

**Docker version: (`docker version`,`docker info` preferred)**
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 11:02:43 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 11:02:43 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher server with internal db, as per quick start guide

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
rancher 2.0 tech preview

**Steps to Reproduce:**
Create rancher 2.0 cluster as per quick start guide, add custom host with rancher agent started with CATTLE_HOST_LABELS="test.label=some.data" env variable. Wait for kubernetes cluster to start up.

**Results:**
In Rancher dashboard I can see my `test.label` on hosts, but in Kubernetes dashboard (and kubectl) I can't see my `test.label`. Seems like kubelet started without custom host labels.

**Comment by sherpc** [comment]
Hi @alena1108 , what's the meaning of `status/resolved`? I just want to know about your plans to implement this feature =)

**Comment by deniseschannon** [comment]
With the release of [Tech Preview 2](https://forums.rancher.com/t/rancher-release-v2-0-0-tech-preview-2/8282/3), the architecture behind 2.0 has significantly changed. Any issues with any release prior to v2.0.0-alpha12 is most likely invalid. 

Please watch our [Tech Preview 2 meetup](https://www.youtube.com/watch?v=ld7ctOg3waM&t=4s) to learn more about the changes in 2.0 in Tech Preview 2. 

Please file new issues after using Tech Preview 2 (any release v2.0.0-alpha12+). As always, thanks for using Rancher!
