### ISSUE TITLE
Slowness creating stacks and having load balancers discover them

### ISSUE THREAD

**Issue by mattdodge** [rancher/rancher#9997]
**Rancher versions:**
- rancher/server: 1.6.9
- rancher/agent: 1.2.6

**Infrastructure Stack versions:**
- healthcheck: 0.3.3
- ipsec: 0.1.4
- network-services: 0.2.6
- scheduler: 0.6.3

 
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
- Running Cattle with HA Rancher (2 nodes), external DB.
- Rancher Server runs 2 EC2 Ubuntu c4.xlarge instances. 
- HAProxy load balancers run on 2 EC2 Ubuntu c4.large instances with nothing but the load balancers running on them
- New services/stacks run on one of 3 EC2 Ubuntu c4.2xlarge instances that **each** have ~100 stacks and ~100 containers running on them

**Steps to Reproduce:**
Given a load balancer with a selector rule that listens to new services, launch a new service with a corresponding `lb_config` entry in the `rancher-compose.yml`. The service takes about 30 seconds to go from `Starting` to `Started` state (some potentially relevant CNI logs below) and then anywhere from 1 to 2 minutes after that to be discovered by the load balancer. Until this happens the load balancer requests return 503 for the new hostname.

**Load balancer stuff**
So my first instinct was to look at the load balancer logs during this period of slowness. There's nothing logged during the waiting period (1-2) minutes but I can confirm that incoming requests to my newly created hostname switch from returning 503 to returning 200 at the same time that this log message appears in the `rancher/lb-service-haproxy` container:
```
time="2017-10-03T00:03:38Z" level=info msg=" -- reloading haproxy config with the new config changes\n * Reloading haproxy haproxy\n[WARNING] 275/000338 (473) : config : 'option forwardfor' ignored for proxy 'default' as it requires HTTP mode.\n[WARNING] 275/000338 (475): config : 'option forwardfor' ignored for proxy 'default' as it requires HTTP mode.\n   ...done.\n"
```
I'm not so concerned with the warning, but it does tell me that that is when the haproxy reload happens. I have tried launching services using the API, the rancher-compose CLI, and the UI. All three methods demonstrate the same behavior.

**Rancher agent stuff**
I then tried to figure out either why the load balancer was taking so long to reload and/or why the services took so long to start. I checked out the logs of the `rancher/agent` and the `rancher/network-manager` containers on the host that the new service was starting on. No real luck on the load balancer waiting period, but I did notice what was maybe causing the waiting when the service is stuck in the starting state periodically. Here are the logs from `rancher/agent` during that time:
```
time="2017-10-03T00:43:36Z" level=info msg="Setting up resolv.conf for ContainerId [b49da3d274b0605ecd71e20a4682d767e6149ee6377cf41d709569e8ecbf1775]"
time="2017-10-03T00:43:36Z" level=info msg="CNI up" cid=b49da3d274b0605ecd71e20a4682d767e6149ee6377cf41d709569e8ecbf1775 networkMode=ipsec
time="2017-10-03T00:44:25Z" level=info msg="CNI up done" cid=b49da3d274b0605ecd71e20a4682d767e6149ee6377cf41d709569e8ecbf1775 networkMode=ipsec result=IP4:{IP:{IP:10.42.88.101 Mask:ffff0000} Gateway:10.42.0.1 Routes:[{Dst:{IP:169.254.169.250 Mask:ffffffff} GW:<nil>} {Dst:{IP:0.0.0.0 Mask:00000000} GW:10.42.0.1}]}, DNS:{Nameservers:[] Domain: Search:[] Options:[]}
```
It seems like it's taking 49 seconds for the CNI to come up. The whole time the cni container (`r-ipsec-cni-driver`) shows logs saying `Waiting to find IP for container:`. I'm not sure if that's helpful or related but that's another slowness I'd like to resolve.

**Synopsis/Questions**
So overall we're seeing about 2 minutes of waiting between the time we spawn a service and it's available to be accessed through the load balancer. For what it's worth, we also have a stage environment that is running far less containers and also not running Rancher in HA mode (although still uses external DB) and this time period is nearly instant (1-2 seconds total). Here are some direct questions that may help:

1. What causes the load balancer to reload its haproxy config when a new service is started/stopped. Is there anything that could cause a delay in that happening?
2. Why does it take almost a minute for the CNI to come up? Is that itself the problem or more just a symptom of another problem?
3. Are there better container logs for me to look at for diagnosis? There are so many hosts and different containers running on them that it's sometimes hard to know where to look for something like this.

**Comment by loganhz** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
