### ISSUE TITLE
docker-compose.yml uploading via the ui breaks go templating

### ISSUE THREAD

**Issue by pkaramol** [rancher/rancher#9999]
**Rancher versions:**
rancher/server: latest (as on 27th Sept. 2017)
rancher/agent: 1.2.6

**Infrastructure Stack versions:**
healthcheck: 0.3.3
ipsec: 0.11.9
network-services: 
rancher/metadata:v0.9.4
rancher/network-manager:v0.7.8
scheduler: v0.8.2
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 17.07.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 34
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 3addd840653146c90a254301d6c3a663c7fd6429
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-96-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.953GiB
Name: server
ID: TGWR:BFPO:U6QJ:QUWV:HY4Z:LXA7:JKRP:2DU2:FK7V:7H6O:A7E4:W67W
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04.03
4.4.0-96-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VirtualBox

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
1 Rancher server node, 2 host nodes

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Using the following `docker-compose.yml` to create a sample stack with some logging options:

```
version: '2'

services:
  myservice:
    image: mysql:latest
    logging:
      driver: syslog
      options:
        syslog-address: tcp://someloggingserver:acustomloggingport
        tag: '{{ index .ContainerLabels "io.rancher.container.name" }}'
```

**Α.**
Uploading the file via rancher ui when creating a new stack, results in : 

> Error (yaml: line 9: found unexpected end of stream)

**B.**
`ssh`-ing into the rancher server and (after downloading the `rancher-compose` cli) executing

`./rancher-compose --debug -f /<path>/<to>/docker-compose.yml up
`
works just fine.

Using the **exact same file** in both cases.

**Comment by deniseschannon** [comment]
With the release of [Tech Preview 2](https://forums.rancher.com/t/rancher-release-v2-0-0-tech-preview-2/8282/3), the architecture behind 2.0 has significantly changed. Any issues with any release prior to v2.0.0-alpha12 is most likely invalid. 

Please file new issues after using Tech Preview 2 (any release v2.0.0-alpha12+), but we recommend using the `preview` tag to get the latest. We are currently at `v2.0.0-beta3`. As always, thanks for using Rancher!
